Qt 4.8: QSqlResult Class Reference
QSqlResult Class Reference abstract
The QSqlResult class provides an abstract interface for accessing data from specific SQL databases.
#include <qsqlresult.h>
Public Functions
virtual QVariant handle () const
Returns the low-level database handle for this result set wrapped in a QVariant or an invalid QVariant if there is no handle.
virtual ~QSqlResult ()
Destroys the object and frees any allocated resources.
Protected Types
enum BindingSyntax { PositionalBinding, NamedBinding }
This enum type specifies the different syntaxes for specifying placeholders in prepared queries.
enum VirtualHookOperation { BatchOperation, DetachFromResultSet, SetNumericalPrecision, NextResult }
Protected Functions
void addBindValue (const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to the next available position in the current record (row).
int at () const
Returns the current (zero-based) row position of the result.
BindingSyntax bindingSyntax () const
Returns the binding syntax used by prepared queries.
virtual void bindValue (int pos, const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to position index in the current record (row).
virtual void bindValue (const QString &placeholder, const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to the placeholder name in the current record (row).
QSql::ParamType bindValueType (const QString &placeholder) const
Returns the parameter type for the value bound with the given placeholder name.
QSql::ParamType bindValueType (int pos) const
Returns the parameter type for the value bound at position index.
QVariant boundValue (const QString &placeholder) const
Returns the value bound by the given placeholder name in the current record (row).
QVariant boundValue (int pos) const
Returns the value bound at position index in the current record (row).
int boundValueCount () const
Returns the number of bound values in the result.
QString boundValueName (int pos) const
Returns the name of the bound value at position index in the current record (row).
QVector< QVariant > & boundValues () const
Returns a vector of the result's bound values for the current record (row).
void clear ()
Clears the entire result set and releases any associated resources.
virtual QVariant data (int i)=0
Returns the data for field index in the current row as a QVariant.
void detachFromResultSet ()
const QSqlDriver * driver () const
Returns the driver associated with the result.
virtual bool exec ()
Executes the query, returning true if successful; otherwise returns false.
bool execBatch (bool arrayBind=false)
Executes a prepared query in batch mode if the driver supports it, otherwise emulates a batch execution using bindValue() and exec().
QString executedQuery () const
Returns the query that was actually executed.
virtual bool fetch (int i)=0
Positions the result to an arbitrary (zero-based) row index.
virtual bool fetchFirst ()=0
Positions the result to the first record (row 0) in the result.
virtual bool fetchLast ()=0
Positions the result to the last record (last row) in the result.
virtual bool fetchNext ()
Positions the result to the next available record (row) in the result.
virtual bool fetchPrevious ()
Positions the result to the previous record (row) in the result.
bool hasOutValues () const
Returns true if at least one of the query's bound values is a QSql::Out or a QSql::InOut; otherwise returns false.
bool isActive () const
Returns true if the result has records to be retrieved; otherwise returns false.
bool isForwardOnly () const
Returns true if you can only scroll forward through the result set; otherwise returns false.
virtual bool isNull (int i)=0
Returns true if the field at position index in the current row is null; otherwise returns false.
bool isSelect () const
Returns true if the current result is from a SELECT statement; otherwise returns false.
bool isValid () const
Returns true if the result is positioned on a valid record (that is, the result is not positioned before the first or after the last record); otherwise returns false.
QSqlError lastError () const
Returns the last error associated with the result.
virtual QVariant lastInsertId () const
Returns the object ID of the most recent inserted row if the database supports it.
QString lastQuery () const
Returns the current SQL query text, or an empty string if there isn't one.
bool nextResult ()
QSql::NumericalPrecisionPolicy numericalPrecisionPolicy () const
virtual int numRowsAffected ()=0
Returns the number of rows affected by the last query executed, or -1 if it cannot be determined or if the query is a SELECT statement.
virtual bool prepare (const QString &query)
Prepares the given query for execution; the query will normally use placeholders so that it can be executed repeatedly.
QSqlResult (const QSqlDriver *db)
Creates a QSqlResult using database driver db.
virtual QSqlRecord record () const
Returns the current record if the query is active; otherwise returns an empty QSqlRecord.
virtual bool reset (const QString &sqlquery)=0
Sets the result to use the SQL statement query for subsequent data retrieval.
virtual bool savePrepare (const QString &sqlquery)
Prepares the given query, using the underlying database functionality where possible.
virtual void setActive (bool a)
This function is provided for derived classes to set the internal active state to active.
virtual void setAt (int at)
This function is provided for derived classes to set the internal (zero-based) row position to index.
virtual void setForwardOnly (bool forward)
Sets forward only mode to forward.
virtual void setLastError (const QSqlError &e)
This function is provided for derived classes to set the last error to error.
void setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy policy)
virtual void setQuery (const QString &query)
Sets the current query for the result to query.
virtual void setSelect (bool s)
This function is provided for derived classes to indicate whether or not the current statement is a SQL SELECT statement.
virtual int size ()=0
Returns the size of the SELECT result, or -1 if it cannot be determined or if the query is not a SELECT statement.
virtual void virtual_hook (int id, void *data)
Private Functions
void resetBindCount ()
Properties
QSqlResultPrivate * d
Friends
class QSqlQuery
class QSqlResultPrivate
class QSqlTableModelPrivate
Detailed Description
The QSqlResult class provides an abstract interface for accessing data from specific SQL databases.
Attention
Module: QtSql
Normally, you would use QSqlQuery instead of QSqlResult, since QSqlQuery provides a generic wrapper for database-specific implementations of QSqlResult.
If you are implementing your own SQL driver (by subclassing QSqlDriver), you will need to provide your own QSqlResult subclass that implements all the pure virtual functions and other virtual functions that you need.
See also
QSqlDriver
Definition at line 63 of file qsqlresult.h.
Enumerations
BindingSyntax
enum QSqlResult::BindingSyntax protected
This enum type specifies the different syntaxes for specifying placeholders in prepared queries.
PositionalBinding Use the ODBC-style positional syntax, with "?" as placeholders.
NamedBinding Use the Oracle-style syntax with named placeholders (e.g., ":id")
BindByPosition
BindByName
See also
bindingSyntax()
Enumerator
PositionalBinding
NamedBinding
Definition at line 74 of file qsqlresult.h.
{
         PositionalBinding,
         NamedBinding
 #ifdef QT3_SUPPORT
         , BindByPosition = PositionalBinding,
         BindByName = NamedBinding
 #endif
     };
VirtualHookOperation
enum QSqlResult::VirtualHookOperation protected
Warning
This function is not part of the public interface.
Enumerator
BatchOperation
DetachFromResultSet
SetNumericalPrecision
NextResult
Definition at line 133 of file qsqlresult.h.
 { BatchOperation, DetachFromResultSet, SetNumericalPrecision, NextResult };
Constructors and Destructors
~QSqlResult()
QSqlResult::~QSqlResult () virtual
Destroys the object and frees any allocated resources.
Definition at line 270 of file qsqlresult.cpp.
 {
     delete d;
 }
QSqlResult()
QSqlResult::QSqlResult (const QSqlDriver * db) explicit protected
Creates a QSqlResult using database driver db.
The object is initialized to an inactive state.
See also
isActive(), driver()
Definition at line 257 of file qsqlresult.cpp.
 {
     d = new QSqlResultPrivate(this);
     d->sqldriver = const_cast<QSqlDriver *>(db);
     if(db) {
         setNumericalPrecisionPolicy(db->numericalPrecisionPolicy());
     }
 }
Functions
addBindValue()
void QSqlResult::addBindValue (const QVariant & val, QSql::ParamType paramType) protected
Binds the value val of parameter type paramType to the next available position in the current record (row).
See also
bindValue()
Definition at line 784 of file qsqlresult.cpp.
 {
     d->binds = PositionalBinding;
     bindValue(d->bindCount, val, paramType);
     ++d->bindCount;
 }
at()
int QSqlResult::at () const protected
Returns the current (zero-based) row position of the result.
May return the special values QSql::BeforeFirstRow or QSql::AfterLastRow.
See also
setAt(), isValid()
Definition at line 306 of file qsqlresult.cpp.
Referenced by QSqlCachedResult::cacheNext(), QPSQLResult::data(), QSqlCachedResult::data(), QDB2Result::fetch(), QSymSQLResult::fetch(), QPSQLResult::fetch(), QMYSQLResult::fetch(), QSqlCachedResult::fetch(), QODBCResult::fetch(), QDB2Result::fetchFirst(), QMYSQLResult::fetchFirst(), QSqlCachedResult::fetchFirst(), QODBCResult::fetchFirst(), QDB2Result::fetchLast(), QSymSQLResult::fetchLast(), QMYSQLResult::fetchLast(), QSqlCachedResult::fetchLast(), QODBCResult::fetchLast(), QDB2Result::fetchNext(), QSymSQLResult::fetchNext(), QMYSQLResult::fetchNext(), QSqlCachedResult::fetchNext(), QODBCResult::fetchNext(), QSqlCachedResult::fetchPrevious(), QODBCResult::fetchPrevious(), QOCIResult::gotoNext(), QSqlCachedResult::isNull(), and QPSQLResult::isNull().
 {
     return d->idx;
 }
bindingSyntax()
QSqlResult::BindingSyntax QSqlResult::bindingSyntax () const protected
Returns the binding syntax used by prepared queries.
Definition at line 867 of file qsqlresult.cpp.
 {
     return d->binds;
 }
bindValue() [1/2]
void QSqlResult::bindValue (int index, const QVariant & val, QSql::ParamType paramType) protected virtual
Binds the value val of parameter type paramType to position index in the current record (row).
See also
addBindValue()
Reimplemented in QSqlNullResult.
Definition at line 727 of file qsqlresult.cpp.
 {
     d->binds = PositionalBinding;
     d->indexes[qFieldSerial(index)] = index;
     if (d->values.count() <= index)
         d->values.resize(index + 1);
     d->values[index] = val;
     if (paramType != QSql::In || !d->types.isEmpty())
         d->types[index] = paramType;
 }
bindValue() [2/2]
void QSqlResult::bindValue (const QString & placeholder, const QVariant & val, QSql::ParamType paramType) protected virtual
Binds the value val of parameter type paramType to the placeholder name in the current record (row).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Values cannot be bound to multiple locations in the query, eg:
INSERT INTO testtable (id, name, samename) VALUES (:id, :name, :name)
Binding to name will bind to the first :name, but not the second.
Note
Binding an undefined placeholder will result in undefined behavior.
See also
QSqlQuery::bindValue()
Reimplemented in QSqlNullResult.
Definition at line 757 of file qsqlresult.cpp.
 {
     d->binds = NamedBinding;
     // if the index has already been set when doing emulated named
     // bindings - don't reset it
     int idx = d->indexes.value(placeholder, -1);
     if (idx >= 0) {
         if (d->values.count() <= idx)
             d->values.resize(idx + 1);
         d->values[idx] = val;
     } else {
         d->values.append(val);
         idx = d->values.count() - 1;
         d->indexes[placeholder] = idx;
     }
     if (paramType != QSql::In || !d->types.isEmpty())
         d->types[idx] = paramType;
 }
bindValueType() [1/2]
QSql::ParamType QSqlResult::bindValueType (const QString & placeholder) const protected
Returns the parameter type for the value bound with the given placeholder name.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 838 of file qsqlresult.cpp.
Referenced by QDB2Result::exec(), QODBCResult::exec(), QOCIResultPrivate::isBinaryValue(), and QOCIResultPrivate::isOutValue().
 {
     return d->types.value(d->indexes.value(placeholder, -1), QSql::In);
 }
bindValueType() [2/2]
QSql::ParamType QSqlResult::bindValueType (int index) const protected
Returns the parameter type for the value bound at position index.
See also
boundValue()
Definition at line 824 of file qsqlresult.cpp.
 {
     return d->types.value(index, QSql::In);
 }
boundValue() [1/2]
QVariant QSqlResult::boundValue (const QString & placeholder) const protected
Returns the value bound by the given placeholder name in the current record (row).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
bindValueType()
Definition at line 813 of file qsqlresult.cpp.
 {
     int idx = d->indexes.value(placeholder, -1);
     return d->values.value(idx);
 }
boundValue() [2/2]
QVariant QSqlResult::boundValue (int index) const protected
Returns the value bound at position index in the current record (row).
See also
bindValue(), boundValues()
Definition at line 797 of file qsqlresult.cpp.
 {
     return d->values.value(index);
 }
boundValueCount()
int QSqlResult::boundValueCount () const protected
Returns the number of bound values in the result.
See also
boundValues()
Definition at line 848 of file qsqlresult.cpp.
Referenced by QOCIResult::exec().
 {
     return d->values.count();
 }
boundValueName()
QString QSqlResult::boundValueName (int index) const protected
Returns the name of the bound value at position index in the current record (row).
See also
boundValue()
Definition at line 905 of file qsqlresult.cpp.
 {
     return d->holderAt(index);
 }
boundValues()
QVector< QVariant > & QSqlResult::boundValues () const protected
Returns a vector of the result's bound values for the current record (row).
See also
boundValueCount()
Definition at line 859 of file qsqlresult.cpp.
Referenced by QIBaseResult::exec(), QDB2Result::exec(), QOCIResult::exec(), QSQLiteResult::exec(), QSymSQLResult::exec(), QPSQLResult::exec(), QODBCResult::exec(), QOCIResult::virtual_hook(), and QMYSQLResult::virtual_hook().
 {
     return d->values;
 }
clear()
void QSqlResult::clear (void) protected
Clears the entire result set and releases any associated resources.
Definition at line 876 of file qsqlresult.cpp.
 {
     d->clear();
 }
data()
QVariant QSqlResult::data (int index) protected pure virtual
Returns the data for field index in the current row as a QVariant.
This function is only called if the result is in an active state and is positioned on a valid record and index is non-negative. Derived classes must reimplement this function and return the value of field index, or QVariant() if it cannot be determined.
Implemented in QODBCResult, QMYSQLResult, QPSQLResult, QSqlCachedResult, QSymSQLResult, QDB2Result, and QSqlNullResult.
detachFromResultSet()
void QSqlResult::detachFromResultSet () protected
Warning
This function is not part of the public interface.
Definition at line 1020 of file qsqlresult.cpp.
 {
     if (driver()->hasFeature(QSqlDriver::FinishQuery)
             || driver()->hasFeature(QSqlDriver::SimpleLocking))
         virtual_hook(DetachFromResultSet, 0);
 }
driver()
const QSqlDriver * QSqlResult::driver () const protected
Returns the driver associated with the result.
This is the object that was passed to the constructor.
Definition at line 389 of file qsqlresult.cpp.
Referenced by QIBaseResult::exec(), QPSQLResult::exec(), QODBCResult::fetch(), QIBaseResult::prepare(), QSQLiteResult::prepare(), QSymSQLResult::prepare(), QODBCResult::prepare(), QSQLite2Result::reset(), QPSQLResult::reset(), QMYSQLResult::reset(), QTDSResult::reset(), QODBCResult::reset(), QODBCResult::~QODBCResult(), and QSQLiteResult::~QSQLiteResult().
 {
     return d->sqldriver;
 }
exec()
bool QSqlResult::exec () protected virtual
Executes the query, returning true if successful; otherwise returns false.
See also
prepare()
Reimplemented in QODBCResult, QPSQLResult, QSqlNullResult, QSymSQLResult, QSQLiteResult, QOCIResult, QDB2Result, and QIBaseResult.
Definition at line 675 of file qsqlresult.cpp.
Referenced by QPSQLResult::exec(), and QMYSQLResult::virtual_hook().
 {
     bool ret;
     // fake preparation - just replace the placeholders..
     QString query = lastQuery();
     if (d->binds == NamedBinding) {
         int i;
         QVariant val;
         QString holder;
         for (i = d->holders.count() - 1; i >= 0; --i) {
             holder = d->holders.at(i).holderName;
             val = d->values.value(d->indexes.value(holder));
             QSqlField f(QLatin1String(""), val.type());
             f.setValue(val);
             query = query.replace(d->holders.at(i).holderPos,
                                    holder.length(), driver()->formatValue(f));
         }
     } else {
         QString val;
         int i = 0;
         int idx = 0;
         for (idx = 0; idx < d->values.count(); ++idx) {
             i = query.indexOf(QLatin1Char('?'), i);
             if (i == -1)
                 continue;
             QVariant var = d->values.value(idx);
             QSqlField f(QLatin1String(""), var.type());
             if (var.isNull())
                 f.clear();
             else
                 f.setValue(var);
             val = driver()->formatValue(f);
             query = query.replace(i, 1, driver()->formatValue(f));
             i += val.length();
         }
     }
     // have to retain the original query with placeholders
     QString orig = lastQuery();
     ret = reset(query);
     d->executedQuery = query;
     setQuery(orig);
     d->resetBindCount();
     return ret;
 }
execBatch()
bool QSqlResult::execBatch (bool arrayBind = false) protected
Executes a prepared query in batch mode if the driver supports it, otherwise emulates a batch execution using bindValue() and exec().
Warning
This function is not part of the public interface.
Since
4.2
QSqlDriver::hasFeature() can be used to find out whether a driver supports batch execution.
Batch execution can be faster for large amounts of data since it reduces network roundtrips.
For batch executions, bound values have to be provided as lists of variants (QVariantList).
Each list must contain values of the same type. All lists must contain equal amount of values (rows).
NULL values are passed in as typed QVariants, for example {QVariant(QVariant::Int)} for an integer NULL value.
Example:
QSqlQuery q;
q.prepare("insert into test (i1, i2, s) values (?, ?, ?)");
QVariantList col1;
QVariantList col2;
QVariantList col3;
col1 << 1 << 3;
col2 << 2 << 4;
col3 << "hello" << "world";
q.bindValue(0, col1);
q.bindValue(1, col2);
q.bindValue(2, col3);
if (!q.execBatch())
    qDebug() << q.lastError();
Here, we insert two rows into a SQL table, with each row containing three values.
See also
exec(), QSqlDriver::hasFeature()
Definition at line 997 of file qsqlresult.cpp.
 {
     if (driver()->hasFeature(QSqlDriver::BatchOperations)) {
         virtual_hook(BatchOperation, &arrayBind);
         d->resetBindCount();
         return d->error.type() == QSqlError::NoError;
     } else {
         QVector<QVariant> values = d->values;
         if (values.count() == 0)
             return false;
         for (int i = 0; i < values.at(0).toList().count(); ++i) {
             for (int j = 0; j < values.count(); ++j)
                 bindValue(j, values.at(j).toList().at(i), QSql::In);
             if (!exec())
                 return false;
         }
         return true;
     }
     return false;
 }
executedQuery()
QString QSqlResult::executedQuery () const protected
Returns the query that was actually executed.
This may differ from the query that was passed, for example if bound values were used with a prepared query and the underlying database doesn't support prepared queries.
See also
exec(), setQuery()
Definition at line 889 of file qsqlresult.cpp.
 {
     return d->executedQuery;
 }
fetch()
bool QSqlResult::fetch (int index) protected pure virtual
Positions the result to an arbitrary (zero-based) row index.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the row index, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
isActive(), fetchFirst(), fetchLast(), fetchNext(), fetchPrevious()
Implemented in QODBCResult, QSqlCachedResult, QMYSQLResult, QPSQLResult, QSymSQLResult, QDB2Result, and QSqlNullResult.
fetchFirst()
bool QSqlResult::fetchFirst () protected pure virtual
Positions the result to the first record (row 0) in the result.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the first record, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
fetch(), fetchLast()
Implemented in QODBCResult, QSqlCachedResult, QMYSQLResult, QSymSQLResult, QPSQLResult, QDB2Result, and QSqlNullResult.
fetchLast()
bool QSqlResult::fetchLast () protected pure virtual
Positions the result to the last record (last row) in the result.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the last record, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
fetch(), fetchFirst()
Implemented in QODBCResult, QSqlCachedResult, QMYSQLResult, QSymSQLResult, QPSQLResult, QDB2Result, and QSqlNullResult.
fetchNext()
bool QSqlResult::fetchNext () protected virtual
Positions the result to the next available record (row) in the result.
This function is only called if the result is in an active state. The default implementation calls fetch() with the next index. Derived classes can reimplement this function and position the result to the next record in some other way, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
fetch(), fetchPrevious()
Reimplemented in QODBCResult, QSqlCachedResult, QMYSQLResult, QSymSQLResult, and QDB2Result.
Definition at line 555 of file qsqlresult.cpp.
 {
     return fetch(at() + 1);
 }
fetchPrevious()
bool QSqlResult::fetchPrevious () protected virtual
Positions the result to the previous record (row) in the result.
This function is only called if the result is in an active state. The default implementation calls fetch() with the previous index. Derived classes can reimplement this function and position the result to the next record in some other way, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
Reimplemented in QODBCResult, QSqlCachedResult, and QSymSQLResult.
Definition at line 571 of file qsqlresult.cpp.
Referenced by QSymSQLResult::fetchPrevious().
 {
     return fetch(at() - 1);
 }
handle()
QVariant QSqlResult::handle () const virtual
Returns the low-level database handle for this result set wrapped in a QVariant or an invalid QVariant if there is no handle.
Warning
Use this with uttermost care and only if you know what you're doing.
The handle returned here can become a stale pointer if the result is modified (for example, if you clear it).
The handle can be NULL if the result was not executed yet.
The handle returned here is database-dependent, you should query the type name of the variant before accessing it.
This example retrieves the handle for a sqlite result:
QSqlQuery query = ...
QVariant v = query.result()->handle();
if (v.isValid() && qstrcmp(v.typeName(), "sqlite3_stmt*")) {
    // v.data() returns a pointer to the handle
    sqlite3_stmt *handle = *static_cast<sqlite3_stmt **>(v.data());
    if (handle != 0) { // check that it is not NULL
        ...
    }
}
This snippet returns the handle for PostgreSQL or MySQL:
if (v.typeName() == "PGresult*") {
    PGresult *handle = *static_cast<PGresult **>(v.data());
    if (handle != 0) ...
}
if (v.typeName() == "MYSQL_STMT*") {
    MYSQL_STMT *handle = *static_cast<MYSQL_STMT **>(v.data());
    if (handle != 0) ...
}
See also
QSqlDriver::handle()
Reimplemented in QODBCResult, QTDSResult, QMYSQLResult, QOCIResult, QPSQLResult, QSQLite2Result, QSymSQLResult, QSQLiteResult, QDB2Result, and QIBaseResult.
Definition at line 1078 of file qsqlresult.cpp.
 {
     return QVariant();
 }
hasOutValues()
bool QSqlResult::hasOutValues () const protected
Returns true if at least one of the query's bound values is a QSql::Out or a QSql::InOut; otherwise returns false.
See also
bindValueType()
Definition at line 916 of file qsqlresult.cpp.
Referenced by QDB2Result::exec(), QOCIResult::exec(), and QODBCResult::exec().
 {
     if (d->types.isEmpty())
         return false;
     QHash<int, QSql::ParamType>::ConstIterator it;
     for (it = d->types.constBegin(); it != d->types.constEnd(); ++it) {
         if (it.value() != QSql::In)
             return true;
     }
     return false;
 }
isActive()
bool QSqlResult::isActive () const protected
Returns true if the result has records to be retrieved; otherwise returns false.
Definition at line 340 of file qsqlresult.cpp.
Referenced by QSymSQLResult::fetch(), QPSQLResult::fetch(), QSqlCachedResult::fetch(), QSymSQLResult::fetchLast(), QSQLiteResult::lastInsertId(), QOCIResult::lastInsertId(), QPSQLResult::lastInsertId(), QMYSQLResult::lastInsertId(), QSymSQLResult::lastInsertId(), QIBaseResult::record(), QSQLite2Result::record(), QDB2Result::record(), QSQLiteResult::record(), QOCIResult::record(), QPSQLResult::record(), QSymSQLResult::record(), QMYSQLResult::record(), QODBCResult::record(), QMYSQLResult::reset(), and QIBaseResult::size().
 {
     return d->active;
 }
isForwardOnly()
bool QSqlResult::isForwardOnly () const protected
Returns true if you can only scroll forward through the result set; otherwise returns false.
See also
setForwardOnly()
Definition at line 582 of file qsqlresult.cpp.
Referenced by QSqlCachedResult::cacheNext(), QDB2Result::exec(), QDB2Result::fetch(), QMYSQLResult::fetch(), QODBCResult::fetch(), QDB2Result::fetchFirst(), QMYSQLResult::fetchFirst(), QODBCResult::fetchFirst(), QDB2Result::fetchLast(), QMYSQLResult::fetchLast(), QODBCResult::fetchLast(), QODBCResult::fetchPrevious(), QSqlCachedResult::init(), QDB2Result::prepare(), and QDB2Result::reset().
 {
     return d->forwardOnly;
 }
isNull()
bool QSqlResult::isNull (int i) protected pure virtual
Returns true if the field at position index in the current row is null; otherwise returns false.
Implemented in QODBCResult, QMYSQLResult, QPSQLResult, QSqlCachedResult, QDB2Result, QSymSQLResult, and QSqlNullResult.
isSelect()
bool QSqlResult::isSelect () const protected
Returns true if the current result is from a SELECT statement; otherwise returns false.
See also
setSelect()
Definition at line 379 of file qsqlresult.cpp.
Referenced by QMYSQLResult::data(), QIBaseResult::exec(), QODBCResult::exec(), QMYSQLResult::nextResult(), QIBaseResult::prepare(), QSQLite2Result::record(), QSQLiteResult::record(), QOCIResult::record(), QPSQLResult::record(), QSymSQLResult::record(), QMYSQLResult::record(), QODBCResult::record(), QMYSQLResult::reset(), QIBaseResult::size(), QMYSQLResult::size(), and QMYSQLResult::virtual_hook().
 {
     return d->isSel;
 }
isValid()
bool QSqlResult::isValid () const protected
Returns true if the result is positioned on a valid record (that is, the result is not positioned before the first or after the last record); otherwise returns false.
See also
at()
Definition at line 320 of file qsqlresult.cpp.
Referenced by QSQLiteResult::exec(), QSymSQLResult::exec(), and QSQLite2Result::reset().
 {
     return d->idx != QSql::BeforeFirstRow && d->idx != QSql::AfterLastRow;
 }
lastError()
QSqlError QSqlResult::lastError () const protected
Returns the last error associated with the result.
Definition at line 427 of file qsqlresult.cpp.
Referenced by QSQLiteResult::exec(), QSymSQLResult::exec(), and QSQLite2Result::reset().
 {
     return d->error;
 }
lastInsertId()
QVariant QSqlResult::lastInsertId () const protected virtual
Returns the object ID of the most recent inserted row if the database supports it.
An invalid QVariant will be returned if the query did not insert any value or if the database does not report the id back. If more than one row was touched by the insert, the behavior is undefined.
Note that for Oracle databases the row's ROWID will be returned, while for MySQL databases the row's auto-increment field will be returned.
See also
QSqlDriver::hasFeature()
Reimplemented in QSymSQLResult, QMYSQLResult, QPSQLResult, QOCIResult, and QSQLiteResult.
Definition at line 955 of file qsqlresult.cpp.
 {
     return QVariant();
 }
lastQuery()
QString QSqlResult::lastQuery () const protected
Returns the current SQL query text, or an empty string if there isn't one.
See also
setQuery()
Definition at line 294 of file qsqlresult.cpp.
Referenced by QOCIResult::exec(), QSymSQLResult::exec(), and QOCIResult::gotoNext().
 {
     return d->sql;
 }
nextResult()
bool QSqlResult::nextResult () protected
Warning
This function is not part of the public interface.
Definition at line 1044 of file qsqlresult.cpp.
 {
     if (driver()->hasFeature(QSqlDriver::MultipleResultSets)) {
         bool result = false;
         virtual_hook(NextResult, &result);
         return result;
     }
     return false;
 }
numericalPrecisionPolicy()
QSql::NumericalPrecisionPolicy QSqlResult::numericalPrecisionPolicy () const protected
Warning
This function is not part of the public interface.
Definition at line 1037 of file qsqlresult.cpp.
Referenced by QDB2Result::data(), QSymSQLResult::data(), QPSQLResult::data(), QMYSQLResult::data(), QODBCResult::data(), QSQLiteResultPrivate::fetchNext(), QOCICols::getValues(), QIBaseResult::gotoNext(), and QOCICols::qMakeOraField().
 {
     return d->precisionPolicy;
 }
numRowsAffected()
int QSqlResult::numRowsAffected () protected pure virtual
Returns the number of rows affected by the last query executed, or -1 if it cannot be determined or if the query is a SELECT statement.
See also
size()
Implemented in QODBCResult, QTDSResult, QMYSQLResult, QSymSQLResult, QPSQLResult, QOCIResult, QDB2Result, QSQLiteResult, QSQLite2Result, QSqlNullResult, and QIBaseResult.
prepare()
bool QSqlResult::prepare (const QString & query) protected virtual
Prepares the given query for execution; the query will normally use placeholders so that it can be executed repeatedly.
Returns true if the query is prepared successfully; otherwise returns false.
See also
exec()
Reimplemented in QODBCResult, QPSQLResult, QSqlNullResult, QSymSQLResult, QSQLiteResult, QOCIResult, QDB2Result, and QIBaseResult.
Definition at line 641 of file qsqlresult.cpp.
Referenced by QOCIResult::prepare(), QPSQLResult::prepare(), and QMYSQLResult::virtual_hook().
 {
     int n = query.size();
     bool inQuote = false;
     int i = 0;
     while (i < n) {
         QChar ch = query.at(i);
         if (ch == QLatin1Char(':') && !inQuote
                 && (i == 0 || query.at(i - 1) != QLatin1Char(':'))
                 && (i + 1 < n && qIsAlnum(query.at(i + 1)))) {
             int pos = i + 2;
             while (pos < n && qIsAlnum(query.at(pos)))
                 ++pos;
             d->holders.append(QHolder(query.mid(i, pos - i), i));
             i = pos;
         } else {
             if (ch == QLatin1Char('\''))
                 inQuote = !inQuote;
             ++i;
         }
     }
     d->sql = query;
     return true; // fake prepares should always succeed
 }
record()
QSqlRecord QSqlResult::record () const protected virtual
Returns the current record if the query is active; otherwise returns an empty QSqlRecord.
The default implementation always returns an empty QSqlRecord.
See also
isActive()
Reimplemented in QODBCResult, QTDSResult, QMYSQLResult, QSymSQLResult, QPSQLResult, QOCIResult, QDB2Result, QSQLiteResult, QSQLite2Result, and QIBaseResult.
Definition at line 936 of file qsqlresult.cpp.
 {
     return QSqlRecord();
 }
reset()
bool QSqlResult::reset (const QString & query) protected pure virtual
Sets the result to use the SQL statement query for subsequent data retrieval.
Derived classes must reimplement this function and apply the query to the database. This function is only called after the result is set to an inactive state and is positioned before the first record of the new result. Derived classes should return true if the query was successful and ready to be used, or false otherwise.
See also
setQuery()
Implemented in QODBCResult, QTDSResult, QMYSQLResult, QPSQLResult, QSymSQLResult, QOCIResult, QSQLite2Result, QSQLiteResult, QDB2Result, QIBaseResult, and QSqlNullResult.
resetBindCount()
void QSqlResult::resetBindCount () private
Definition at line 894 of file qsqlresult.cpp.
 {
     d->resetBindCount();
 }
savePrepare()
bool QSqlResult::savePrepare (const QString & query) protected virtual
Prepares the given query, using the underlying database functionality where possible.
Returns true if the query is prepared successfully; otherwise returns false.
See also
prepare()
Reimplemented in QSqlNullResult.
Definition at line 615 of file qsqlresult.cpp.
 {
     if (!driver())
         return false;
     d->clear();
     d->sql = query;
     if (!driver()->hasFeature(QSqlDriver::PreparedQueries))
         return prepare(query);
     if (driver()->hasFeature(QSqlDriver::NamedPlaceholders)) {
         // parse the query to memorize parameter location
         d->namedToPositionalBinding();
         d->executedQuery = d->positionalToNamedBinding();
     } else {
         d->executedQuery = d->namedToPositionalBinding();
     }
     return prepare(d->executedQuery);
 }
setActive()
void QSqlResult::setActive (bool active) protected virtual
This function is provided for derived classes to set the internal active state to active.
See also
isActive()
Reimplemented in QSqlNullResult.
Definition at line 402 of file qsqlresult.cpp.
Referenced by QSqlCachedResult::cleanup(), QPSQLResult::cleanup(), QMYSQLResult::cleanup(), QSQLite2ResultPrivate::cleanup(), QSQLiteResultPrivate::cleanup(), QSymSQLResultPrivate::cleanup(), QIBaseResult::exec(), QDB2Result::exec(), QOCIResult::exec(), QSQLiteResult::exec(), QSymSQLResult::exec(), QODBCResult::exec(), QOCICols::execBatch(), QDB2Result::nextResult(), QMYSQLResult::nextResult(), QODBCResult::nextResult(), QIBaseResult::prepare(), QDB2Result::prepare(), QODBCResult::prepare(), QDB2Result::reset(), QSQLite2Result::reset(), QMYSQLResult::reset(), QTDSResult::reset(), QODBCResult::reset(), and QMYSQLResult::virtual_hook().
 {
     if (active && d->executedQuery.isEmpty())
         d->executedQuery = d->sql;
     d->active = active;
 }
setAt()
void QSqlResult::setAt (int index) protected virtual
This function is provided for derived classes to set the internal (zero-based) row position to index.
See also
at()
Reimplemented in QSqlNullResult.
Definition at line 352 of file qsqlresult.cpp.
Referenced by QSqlCachedResult::cacheNext(), QSqlCachedResult::cleanup(), QPSQLResult::cleanup(), QMYSQLResult::cleanup(), QSQLite2ResultPrivate::cleanup(), QSQLiteResultPrivate::cleanup(), QSymSQLResultPrivate::cleanup(), QSqlCachedResult::clearValues(), QIBaseResult::exec(), QDB2Result::exec(), QOCIResult::exec(), QSymSQLResult::exec(), QODBCResult::exec(), QOCICols::execBatch(), QDB2Result::fetch(), QSymSQLResult::fetch(), QPSQLResult::fetch(), QMYSQLResult::fetch(), QSqlCachedResult::fetch(), QODBCResult::fetch(), QDB2Result::fetchFirst(), QSqlCachedResult::fetchFirst(), QODBCResult::fetchFirst(), QDB2Result::fetchLast(), QSymSQLResult::fetchLast(), QSqlCachedResult::fetchLast(), QODBCResult::fetchLast(), QDB2Result::fetchNext(), QSymSQLResult::fetchNext(), QMYSQLResult::fetchNext(), QSqlCachedResult::fetchNext(), QODBCResult::fetchNext(), QSQLite2ResultPrivate::fetchNext(), QSQLiteResultPrivate::fetchNext(), QSymSQLResultPrivate::fetchNext(), QODBCResult::fetchPrevious(), QIBaseResult::gotoNext(), QOCIResult::gotoNext(), QTDSResult::gotoNext(), QDB2Result::nextResult(), QMYSQLResult::nextResult(), QODBCResult::nextResult(), QIBaseResult::prepare(), QDB2Result::prepare(), QODBCResult::prepare(), QDB2Result::reset(), QMYSQLResult::reset(), QTDSResult::reset(), QODBCResult::reset(), and QMYSQLResult::virtual_hook().
 {
     d->idx = index;
 }
setForwardOnly()
void QSqlResult::setForwardOnly (bool forward) protected virtual
Sets forward only mode to forward.
If forward is true, only fetchNext() is allowed for navigating the results. Forward only mode needs much less memory since results do not have to be cached. By default, this feature is disabled.
Setting forward only to false is a suggestion to the database engine, which has the final say on whether a result set is forward only or scrollable. isForwardOnly() will always return the correct status of the result set.
Note
Calling setForwardOnly after execution of the query will result in unexpected results at best, and crashes at worst.
See also
isForwardOnly(), fetchNext(), QSqlQuery::setForwardOnly()
Reimplemented in QODBCResult, and QSqlNullResult.
Definition at line 603 of file qsqlresult.cpp.
Referenced by QODBCResult::exec(), QODBCResult::reset(), and QODBCResult::setForwardOnly().
 {
     d->forwardOnly = forward;
 }
setLastError()
void QSqlResult::setLastError (const QSqlError & error) protected virtual
This function is provided for derived classes to set the last error to error.
See also
lastError()
Reimplemented in QSqlNullResult.
Definition at line 417 of file qsqlresult.cpp.
Referenced by QDB2Result::exec(), QOCIResult::exec(), QSQLiteResult::exec(), QSymSQLResult::exec(), QODBCResult::exec(), QOCICols::execBatch(), QDB2Result::fetch(), QMYSQLResult::fetch(), QODBCResult::fetch(), QDB2Result::fetchFirst(), QODBCResult::fetchFirst(), QODBCResult::fetchLast(), QDB2Result::fetchNext(), QMYSQLResult::fetchNext(), QODBCResult::fetchNext(), QSQLiteResultPrivate::fetchNext(), QSymSQLResultPrivate::fetchNext(), QODBCResult::fetchPrevious(), QSQLite2ResultPrivate::finalize(), QOCIResult::gotoNext(), QTDSResult::gotoNext(), QSymSQLResultPrivate::initColumns(), QDB2Result::nextResult(), QMYSQLResult::nextResult(), QODBCResult::nextResult(), QDB2Result::prepare(), QOCIResult::prepare(), QSQLiteResult::prepare(), QSymSQLResult::prepare(), QODBCResult::prepare(), QPSQLResult::prepare(), QSqlNullResult::QSqlNullResult(), QDB2Result::reset(), QSQLite2Result::reset(), QMYSQLResult::reset(), QTDSResult::reset(), QODBCResult::reset(), QMYSQLResult::virtual_hook(), and QIBaseResultPrivate::writeArray().
 {
     d->error = error;
 }
setNumericalPrecisionPolicy()
void QSqlResult::setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy policy) protected
Warning
This function is not part of the public interface.
Definition at line 1029 of file qsqlresult.cpp.
 {
     d->precisionPolicy = policy;
     virtual_hook(SetNumericalPrecision, &policy);
 }
setQuery()
void QSqlResult::setQuery (const QString & query) protected virtual
Sets the current query for the result to query.
You must call reset() to execute the query on the database.
See also
reset(), lastQuery()
Reimplemented in QSqlNullResult.
Definition at line 282 of file qsqlresult.cpp.
 {
     d->sql = query;
 }
setSelect()
void QSqlResult::setSelect (bool select) protected virtual
This function is provided for derived classes to indicate whether or not the current statement is a SQL SELECT statement.
The select parameter should be true if the statement is a SELECT statement; otherwise it should be false.
See also
isSelect()
Reimplemented in QSqlNullResult.
Definition at line 367 of file qsqlresult.cpp.
Referenced by QDB2Result::exec(), QOCIResult::exec(), QSQLiteResult::exec(), QSymSQLResult::exec(), QODBCResult::exec(), QOCICols::execBatch(), QDB2Result::nextResult(), QMYSQLResult::nextResult(), QODBCResult::nextResult(), QIBaseResult::prepare(), QSQLiteResult::prepare(), QSymSQLResult::prepare(), QDB2Result::reset(), QSQLite2Result::reset(), QMYSQLResult::reset(), QTDSResult::reset(), QODBCResult::reset(), and QMYSQLResult::virtual_hook().
 {
     d->isSel = select;
 }
size()
int QSqlResult::size () protected pure virtual
Returns the size of the SELECT result, or -1 if it cannot be determined or if the query is not a SELECT statement.
See also
numRowsAffected()
Implemented in QODBCResult, QTDSResult, QMYSQLResult, QSymSQLResult, QPSQLResult, QOCIResult, QDB2Result, QSQLiteResult, QSQLite2Result, QSqlNullResult, and QIBaseResult.
virtual_hook()
void QSqlResult::virtual_hook (int id, void * data) protected virtual
Warning
This function is not part of the public interface.
Reimplemented in QODBCResult, QSqlCachedResult, QMYSQLResult, QSymSQLResult, QOCIResult, QDB2Result, QSQLiteResult, QSQLite2Result, and QPSQLResult.
Definition at line 962 of file qsqlresult.cpp.
Referenced by QPSQLResult::virtual_hook(), QDB2Result::virtual_hook(), QSymSQLResult::virtual_hook(), QMYSQLResult::virtual_hook(), QSqlCachedResult::virtual_hook(), and QODBCResult::virtual_hook().
 {
 }
Friends and Related Functions
QSqlQuery
friend class QSqlQuery friend
Definition at line 65 of file qsqlresult.h.
QSqlResultPrivate
friend class QSqlResultPrivate friend
Definition at line 67 of file qsqlresult.h.
QSqlTableModelPrivate
friend class QSqlTableModelPrivate friend
Definition at line 66 of file qsqlresult.h.
Properties
d
QSqlResultPrivate* QSqlResult::d private
Definition at line 142 of file qsqlresult.h.
The documentation for this class was generated from the following files:
/src/sql/kernel/qsqlresult.h
/src/sql/kernel/qsqlresult.cpp