Qt 4.8: QTextEncoder Class Reference
QTextEncoder Class Reference
The QTextEncoder class provides a state-based encoder.
#include <qtextcodec.h>
Public Functions
QByteArray fromUnicode (const QString &str)
Converts the Unicode string str into an encoded QByteArray.
QByteArray fromUnicode (const QChar *uc, int len)
Converts len characters (not bytes) from uc, and returns the result in a QByteArray.
bool hasFailure () const
Determines whether the eecoder encountered a failure while decoding the input.
QTextEncoder (const QTextCodec *codec)
Constructs a text encoder for the given codec.
QTextEncoder (const QTextCodec *codec, QTextCodec::ConversionFlags flags)
Constructs a text encoder for the given codec and conversion flags.
~QTextEncoder ()
Destroys the encoder.
Properties
const QTextCodec * c
QTextCodec::ConverterState state
Detailed Description
The QTextEncoder class provides a state-based encoder.
Note
This class or function is reentrant.
A text encoder converts text from Unicode into an encoded text format using a specific codec.
The encoder converts Unicode into another format, remembering any state that is required between calls.
See also
QTextCodec::makeEncoder(), QTextDecoder
Definition at line 160 of file qtextcodec.h.
Constructors and Destructors
QTextEncoder() [1/2]
QTextEncoder::QTextEncoder (const QTextCodec * codec) inline explicit
Constructs a text encoder for the given codec.
Definition at line 163 of file qtextcodec.h.
 : c(codec), state() {}
QTextEncoder() [2/2]
QTextEncoder::QTextEncoder (const QTextCodec * codec, QTextCodec::ConversionFlags flags)
Constructs a text encoder for the given codec and conversion flags.
Since
4.7
Definition at line 1521 of file qtextcodec.cpp.
     : c(codec), state()
 {
     state.flags = flags;
 }
~QTextEncoder()
QTextEncoder::~QTextEncoder ()
Destroys the encoder.
Definition at line 1530 of file qtextcodec.cpp.
 {
 }
Functions
fromUnicode() [1/2]
QByteArray QTextEncoder::fromUnicode (const QString & str)
Converts the Unicode string str into an encoded QByteArray.
Definition at line 1551 of file qtextcodec.cpp.
Referenced by QXmlStreamWriterPrivate::checkIfASCIICompatibleCodec(), fromUnicode(), and QXmlStreamWriterPrivate::write().
 {
     QByteArray result = c->fromUnicode(str.constData(), str.length(), &state);
     return result;
 }
fromUnicode() [2/2]
QByteArray QTextEncoder::fromUnicode (const QChar * uc, int len)
Converts len characters (not bytes) from uc, and returns the result in a QByteArray.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1566 of file qtextcodec.cpp.
 {
     QByteArray result = c->fromUnicode(uc, len, &state);
     return result;
 }
hasFailure()
bool QTextEncoder::hasFailure () const
Determines whether the eecoder encountered a failure while decoding the input.
Warning
This function is not part of the public interface.
Since
4.5 If an error was encountered, the produced result is undefined, and gets converted as according to the conversion flags.
Definition at line 1543 of file qtextcodec.cpp.
 {
     return state.invalidChars != 0;
 }
Properties
c
const QTextCodec* QTextEncoder::c private
Definition at line 173 of file qtextcodec.h.
Referenced by fromUnicode().
state
QTextCodec::ConverterState QTextEncoder::state private
Definition at line 174 of file qtextcodec.h.
Referenced by fromUnicode(), hasFailure(), and QTextEncoder().
The documentation for this class was generated from the following files:
/src/corelib/codecs/qtextcodec.h
/src/corelib/codecs/qtextcodec.cpp