Qt 4.8: QDeclarativeWorkerScriptEnginePrivate Class Reference
QDeclarativeWorkerScriptEnginePrivate Class Reference
Classes
struct ScriptEngine
struct WorkerScript
Public Types
enum WorkerEventTypes { WorkerDestroyEvent = QEvent::User + 100 }
Signals
void stopThread ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QScriptValue getWorker (int)
QDeclarativeWorkerScriptEnginePrivate (QDeclarativeEngine *eng)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QDeclarativeWorkerScriptEnginePrivate * get (QScriptEngine *e)
static QScriptValue onMessage (QScriptContext *ctxt, QScriptEngine *engine)
static QVariant scriptValueToVariant (const QScriptValue &)
static QScriptValue sendMessage (QScriptContext *ctxt, QScriptEngine *engine)
static QScriptValue variantToScriptValue (const QVariant &, QScriptEngine *)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables
QMutex m_lock
int m_nextId
QWaitCondition m_wait
QDeclarativeEngine * qmlengine
ScriptEngine * workerEngine
QHash< int, WorkerScript * > workers
Protected Functions
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void processLoad (int, const QUrl &)
void processMessage (int, const QVariant &)
void reportScriptException (WorkerScript *)
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 121 of file qdeclarativeworkerscript.cpp.
Enumerations
WorkerEventTypes
enum QDeclarativeWorkerScriptEnginePrivate::WorkerEventTypes
Enumerator
WorkerDestroyEvent
Definition at line 125 of file qdeclarativeworkerscript.cpp.
{
         WorkerDestroyEvent = QEvent::User + 100
     };
Constructors and Destructors
QDeclarativeWorkerScriptEnginePrivate()
QDeclarativeWorkerScriptEnginePrivate::QDeclarativeWorkerScriptEnginePrivate (QDeclarativeEngine * eng)
Definition at line 194 of file qdeclarativeworkerscript.cpp.
 : workerEngine(0), qmlengine(engine), m_nextId(0)
 {
 }
Functions
event()
bool QDeclarativeWorkerScriptEnginePrivate::event (QEvent * e) protected virtual
This virtual function receives events to an object and should return true if the event e was recognized and processed.
The event() function can be reimplemented to customize the behavior of an object.
See also
installEventFilter(), timerEvent(), QApplication::sendEvent(), QApplication::postEvent(), QWidget::event()
Reimplemented from QObject.
Definition at line 263 of file qdeclarativeworkerscript.cpp.
 {
     if (event->type() == (QEvent::Type)WorkerDataEvent::WorkerData) {
         WorkerDataEvent *workerEvent = static_cast<WorkerDataEvent *>(event);
         processMessage(workerEvent->workerId(), workerEvent->data());
         return true;
     } else if (event->type() == (QEvent::Type)WorkerLoadEvent::WorkerLoad) {
         WorkerLoadEvent *workerEvent = static_cast<WorkerLoadEvent *>(event);
         processLoad(workerEvent->workerId(), workerEvent->url());
         return true;
     } else if (event->type() == (QEvent::Type)WorkerDestroyEvent) {
         emit stopThread();
         return true;
     } else {
         return QObject::event(event);
     }
 }
get()
static QDeclarativeWorkerScriptEnginePrivate* QDeclarativeWorkerScriptEnginePrivate::get (QScriptEngine * e) inline static
Definition at line 150 of file qdeclarativeworkerscript.cpp.
Referenced by onMessage(), reportScriptException(), and sendMessage().
{
         return static_cast<ScriptEngine *>(e)->p;
     }
getWorker()
QScriptValue QDeclarativeWorkerScriptEnginePrivate::getWorker (int id)
Definition at line 237 of file qdeclarativeworkerscript.cpp.
Referenced by processLoad().
 {
     QHash<int, WorkerScript *>::ConstIterator iter = workers.find(id);
     if (iter == workers.end())
         return workerEngine->nullValue();
     WorkerScript *script = *iter;
     if (!script->initialized) {
         script->initialized = true;
         script->object = workerEngine->newObject();
         QScriptValue api = workerEngine->newObject();
         api.setData(script->id);
         api.setProperty(QLatin1String("onMessage"), workerEngine->newFunction(onMessage),
                         QScriptValue::PropertyGetter | QScriptValue::PropertySetter);
         api.setProperty(QLatin1String("sendMessage"), workerEngine->newFunction(sendMessage));
         script->object.setProperty(QLatin1String("WorkerScript"), api);
     }
     return script->object;
 }
onMessage()
QScriptValue QDeclarativeWorkerScriptEnginePrivate::onMessage (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 199 of file qdeclarativeworkerscript.cpp.
Referenced by getWorker().
 {
     QDeclarativeWorkerScriptEnginePrivate *p = QDeclarativeWorkerScriptEnginePrivate::get(engine);
     int id = ctxt->thisObject().data().toVariant().toInt();
     WorkerScript *script = p->workers.value(id);
     if (!script)
         return engine->undefinedValue();
     if (ctxt->argumentCount() >= 1)
         script->callback = ctxt->argument(0);
     return script->callback;
 }
processLoad()
void QDeclarativeWorkerScriptEnginePrivate::processLoad (int id, const QUrl & url) private
Definition at line 300 of file qdeclarativeworkerscript.cpp.
Referenced by event().
 {
     if (url.isRelative())
         return;
     QString fileName = QDeclarativeEnginePrivate::urlToLocalFileOrQrc(url);
     QFile f(fileName);
     if (f.open(QIODevice::ReadOnly)) {
         QByteArray data = f.readAll();
         QString sourceCode = QString::fromUtf8(data);
         QScriptValue activation = getWorker(id);
         QScriptContext *ctxt = QScriptDeclarativeClass::pushCleanContext(workerEngine);
         QScriptValue urlContext = workerEngine->newObject();
         urlContext.setData(QScriptValue(workerEngine, url.toString()));
         ctxt->pushScope(urlContext);
         ctxt->pushScope(activation);
         ctxt->setActivationObject(activation);
         QDeclarativeScriptParser::extractPragmas(sourceCode);
         workerEngine->baseUrl = url;
         workerEngine->evaluate(sourceCode);
         WorkerScript *script = workers.value(id);
         if (script) {
             script->source = url;
             if (workerEngine->hasUncaughtException()) {
                 reportScriptException(script);
                 workerEngine->clearExceptions();
             }
         }
         workerEngine->popContext();
     } else {
         qWarning().nospace() << "WorkerScript: Cannot find source file " << url.toString();
     }
 }
processMessage()
void QDeclarativeWorkerScriptEnginePrivate::processMessage (int id, const QVariant & data) private
Definition at line 281 of file qdeclarativeworkerscript.cpp.
Referenced by event().
 {
     WorkerScript *script = workers.value(id);
     if (!script)
         return;
     if (script->callback.isFunction()) {
         QScriptValue args = workerEngine->newArray(1);
         args.setProperty(0, variantToScriptValue(data, workerEngine));
         script->callback.call(script->object, args);
         if (workerEngine->hasUncaughtException()) {
             reportScriptException(script);
             workerEngine->clearExceptions();
         }
     }
 }
reportScriptException()
void QDeclarativeWorkerScriptEnginePrivate::reportScriptException (WorkerScript * script) private
Definition at line 340 of file qdeclarativeworkerscript.cpp.
Referenced by processLoad(), and processMessage().
 {
     if (!script || !workerEngine->hasUncaughtException())
         return;
     QDeclarativeError error;
     QDeclarativeExpressionPrivate::exceptionToError(workerEngine, error);
     error.setUrl(script->source);
     QDeclarativeWorkerScriptEnginePrivate *p = QDeclarativeWorkerScriptEnginePrivate::get(workerEngine);
     QMutexLocker(&p->m_lock);
     if (script->owner)
         QCoreApplication::postEvent(script->owner, new WorkerErrorEvent(error));
 }
scriptValueToVariant()
QVariant QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant (const QScriptValue & value) static
Definition at line 356 of file qdeclarativeworkerscript.cpp.
Referenced by QDeclarativeWorkerScript::sendMessage(), and sendMessage().
 {
     if (value.isBool()) {
         return QVariant(value.toBool());
     } else if (value.isString()) {
         return QVariant(value.toString());
     } else if (value.isNumber()) {
         return QVariant((qreal)value.toNumber());
     } else if (value.isDate()) {
         return QVariant(value.toDateTime());
 #ifndef QT_NO_REGEXP
     } else if (value.isRegExp()) {
         return QVariant(value.toRegExp());
 #endif
     } else if (value.isArray()) {
         QVariantList list;
         quint32 length = (quint32)value.property(QLatin1String("length")).toNumber();
         for (quint32 ii = 0; ii < length; ++ii) {
             QVariant v = scriptValueToVariant(value.property(ii));
             list << v;
         }
         return QVariant(list);
     } else if (value.isQObject()) {
         QDeclarativeListModel *lm = qobject_cast<QDeclarativeListModel *>(value.toQObject());
         if (lm) {
             QDeclarativeListModelWorkerAgent *agent = lm->agent();
             if (agent) {
                 QDeclarativeListModelWorkerAgent::VariantRef v(agent);
                 return QVariant::fromValue(v);
             } else {
                 return QVariant();
             }
         } else {
             // No other QObject's are allowed to be sent
             return QVariant();
         }
     } else if (value.isObject()) {
         QVariantHash hash;
         QScriptValueIterator iter(value);
         while (iter.hasNext()) {
             iter.next();
             hash.insert(iter.name(), scriptValueToVariant(iter.value()));
         }
         return QVariant(hash);
     }
     return QVariant();
 }
sendMessage()
QScriptValue QDeclarativeWorkerScriptEnginePrivate::sendMessage (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 215 of file qdeclarativeworkerscript.cpp.
Referenced by getWorker().
 {
     if (!ctxt->argumentCount())
         return engine->undefinedValue();
     QDeclarativeWorkerScriptEnginePrivate *p = QDeclarativeWorkerScriptEnginePrivate::get(engine);
     int id = ctxt->thisObject().data().toVariant().toInt();
     WorkerScript *script = p->workers.value(id);
     if (!script)
         return engine->undefinedValue();
     QMutexLocker(&p->m_lock);
     if (script->owner)
         QCoreApplication::postEvent(script->owner,
                                     new WorkerDataEvent(0, scriptValueToVariant(ctxt->argument(0))));
     return engine->undefinedValue();
 }
stopThread
void QDeclarativeWorkerScriptEnginePrivate::stopThread () signal
Referenced by event().
variantToScriptValue()
QScriptValue QDeclarativeWorkerScriptEnginePrivate::variantToScriptValue (const QVariant & value, QScriptEngine * engine) static
Definition at line 412 of file qdeclarativeworkerscript.cpp.
Referenced by QDeclarativeWorkerScript::event(), and processMessage().
 {
     if (value.userType() == QVariant::Bool) {
         return QScriptValue(value.toBool());
     } else if (value.userType() == QVariant::String) {
         return QScriptValue(value.toString());
     } else if (value.userType() == QMetaType::QReal) {
         return QScriptValue(value.toReal());
     } else if (value.userType() == QVariant::DateTime) {
         return engine->newDate(value.toDateTime());
 #ifndef QT_NO_REGEXP
     } else if (value.userType() == QVariant::RegExp) {
         return engine->newRegExp(value.toRegExp());
 #endif
     } else if (value.userType() == qMetaTypeId<QDeclarativeListModelWorkerAgent::VariantRef>()) {
         QDeclarativeListModelWorkerAgent::VariantRef vr = qvariant_cast<QDeclarativeListModelWorkerAgent::VariantRef>(value);
         if (vr.a->scriptEngine() == 0)
             vr.a->setScriptEngine(engine);
         else if (vr.a->scriptEngine() != engine)
             return engine->nullValue();
         QScriptValue o = engine->newQObject(vr.a);
         o.setData(engine->newVariant(value)); // Keeps the agent ref so that it is cleaned up on gc
         return o;
     } else if (value.userType() == QMetaType::QVariantList) {
         QVariantList list = qvariant_cast<QVariantList>(value);
         QScriptValue rv = engine->newArray(list.count());
         for (quint32 ii = 0; ii < quint32(list.count()); ++ii)
             rv.setProperty(ii, variantToScriptValue(list.at(ii), engine));
         return rv;
     } else if (value.userType() == QMetaType::QVariantHash) {
         QVariantHash hash = qvariant_cast<QVariantHash>(value);
         QScriptValue rv = engine->newObject();
         for (QVariantHash::ConstIterator iter = hash.begin(); iter != hash.end(); ++iter)
             rv.setProperty(iter.key(), variantToScriptValue(iter.value(), engine));
         return rv;
     } else {
         return engine->nullValue();
     }
 }
Properties
m_lock
QMutex QDeclarativeWorkerScriptEnginePrivate::m_lock
Definition at line 156 of file qdeclarativeworkerscript.cpp.
Referenced by QDeclarativeWorkerScriptEngine::QDeclarativeWorkerScriptEngine(), reportScriptException(), sendMessage(), and QDeclarativeWorkerScriptEngine::~QDeclarativeWorkerScriptEngine().
m_nextId
int QDeclarativeWorkerScriptEnginePrivate::m_nextId
Definition at line 174 of file qdeclarativeworkerscript.cpp.
m_wait
QWaitCondition QDeclarativeWorkerScriptEnginePrivate::m_wait
Definition at line 157 of file qdeclarativeworkerscript.cpp.
Referenced by QDeclarativeWorkerScriptEngine::QDeclarativeWorkerScriptEngine().
qmlengine
QDeclarativeEngine* QDeclarativeWorkerScriptEnginePrivate::qmlengine
Definition at line 154 of file qdeclarativeworkerscript.cpp.
Referenced by QDeclarativeWorkerScriptEnginePrivate::ScriptEngine::networkAccessManager().
workerEngine
ScriptEngine* QDeclarativeWorkerScriptEnginePrivate::workerEngine
Definition at line 149 of file qdeclarativeworkerscript.cpp.
Referenced by getWorker(), processLoad(), processMessage(), and reportScriptException().
workers
QHash<int, WorkerScript *> QDeclarativeWorkerScriptEnginePrivate::workers
Definition at line 171 of file qdeclarativeworkerscript.cpp.
Referenced by getWorker(), onMessage(), processLoad(), processMessage(), sendMessage(), and QDeclarativeWorkerScriptEngine::~QDeclarativeWorkerScriptEngine().
The documentation for this class was generated from the following file:
/src/declarative/qml/qdeclarativeworkerscript.cpp