Qt 4.8: QResource Class Reference
QResource Class Reference
The QResource class provides an interface for reading directly from resources.
#include <qresource.h>
Public Functions
QString absoluteFilePath () const
Returns the real path that this QResource represents, if the resource was found via the QDir::searchPaths() it will be indicated in the path.
const uchar * data () const
Returns direct access to a read only segment of data that this resource represents.
QString fileName () const
Returns the full path to the file that this QResource represents as it was passed.
bool isCompressed () const
Returns true if the resource represents a file and the data backing it is in a compressed format, false otherwise.
bool isValid () const
Returns true if the resource really exists in the resource hierarchy, false otherwise.
QLocale locale () const
Returns the locale used to locate the data for the QResource.
QResource (const QString &file=QString(), const QLocale &locale=QLocale())
Constructs a QResource pointing to file.
void setFileName (const QString &file)
Sets a QResource to point to file.
void setLocale (const QLocale &locale)
Sets a QResource to only load the localization of resource to for locale.
qint64 size () const
Returns the size of the data backing the resource.
~QResource ()
Releases the resources of the QResource object.
Static Public Functions
static void addSearchPath (const QString &path)
Use QDir::addSearchPath() with a prefix instead.
static bool registerResource (const QString &rccFilename, const QString &resourceRoot=QString())
Registers the resource with the given rccFileName at the location in the resource tree specified by mapRoot, and returns true if the file is successfully opened; otherwise returns false.
static bool registerResource (const uchar *rccData, const QString &resourceRoot=QString())
static QStringList searchPaths ()
Use QDir::searchPaths() instead.
static bool unregisterResource (const QString &rccFilename, const QString &resourceRoot=QString())
Unregisters the resource with the given rccFileName at the location in the resource tree specified by mapRoot, and returns true if the resource is successfully unloaded and no references exist for the resource; otherwise returns false.
static bool unregisterResource (const uchar *rccData, const QString &resourceRoot=QString())
Protected Functions
QStringList children () const
Returns a list of all resources in this directory, if the resource represents a file the list will be empty.
bool isDir () const
Returns true if the resource represents a directory and thus may have children() in it, false if it represents a file.
bool isFile () const
Returns true if the resource represents a file and thus has data backing it, false if it represents a directory.
Protected Variables
QScopedPointer< QResourcePrivate > d_ptr
Friends
class QResourceFileEngine
class QResourceFileEngineIterator
Detailed Description
The QResource class provides an interface for reading directly from resources.
Note
This class or function is reentrant.
Since
4.2
QResource is an object that represents a set of data (and possibly children) relating to a single resource entity. QResource gives direct access to the bytes in their raw format. In this way direct access allows reading data without buffer copying or indirection. Indirection is often useful when interacting with the resource entity as if it is a file, this can be achieved with QFile. The data and children behind a QResource are normally compiled into an application/library, but it is also possible to load a resource at runtime. When loaded at run time the resource file will be loaded as one big set of data and then given out in pieces via references into the resource tree.
A QResource can either be loaded with an absolute path, either treated as a file system rooted with a / character, or in resource notation rooted with a : character. A relative resource can also be opened which will be found in the list of paths returned by QDir::searchPaths().
A QResource that is representing a file will have data backing it, this data can possibly be compressed, in which case qUncompress() must be used to access the real data; this happens implicitly when accessed through a QFile. A QResource that is representing a directory will have only children and no data.
Dynamic Resource Loading
A resource can be left out of an application's binary and loaded when it is needed at run-time by using the registerResource() function. The resource file passed into registerResource() must be a binary resource as created by rcc. Further information about binary resources can be found in The Qt Resource System documentation.
This can often be useful when loading a large set of application icons that may change based on a setting, or that can be edited by a user and later recreated. The resource is immediately loaded into memory, either as a result of a single file read operation, or as a memory mapped file.
This approach can prove to be a significant performance gain as only a single file will be loaded, and pieces of data will be given out via the path requested in setFileName().
The unregisterResource() function removes a reference to a particular file. If there are QResources that currently reference resources related to the unregistered file, they will continue to be valid but the resource file itself will be removed from the resource roots, and thus no further QResource can be created pointing into this resource data. The resource itself will be unmapped from memory when the last QResource that points to it is destroyed.
See also
{The Qt Resource System}, QFile, QDir, QFileInfo
Definition at line 58 of file qresource.h.
Constructors and Destructors
QResource()
QResource::QResource (const QString & file = QString(), const QLocale & locale = QLocale())
Constructs a QResource pointing to file.
locale is used to load a specific localization of a resource data.
See also
QFileInfo, QDir::searchPaths(), setFileName(), setLocale()
Definition at line 382 of file qresource.cpp.
                                                                : d_ptr(new QResourcePrivate(this))
 {
     Q_D(QResource);
     d->fileName = file;
     d->locale = locale;
 }
~QResource()
QResource::~QResource ()
Releases the resources of the QResource object.
Definition at line 392 of file qresource.cpp.
 {
 }
Functions
absoluteFilePath()
QString QResource::absoluteFilePath () const
Returns the real path that this QResource represents, if the resource was found via the QDir::searchPaths() it will be indicated in the path.
See also
fileName()
Definition at line 457 of file qresource.cpp.
 {
     Q_D(const QResource);
     d->ensureInitialized();
     return d->absoluteFilePath;
 }
addSearchPath()
void QResource::addSearchPath (const QString & path) static
Use QDir::addSearchPath() with a prefix instead.
Adds path to the search paths searched in to find resources that are not specified with an absolute path. The path must be an absolute path (start with /).
The default search path is to search only in the root (:/). The last path added will be consulted first upon next QResource creation.
Definition at line 577 of file qresource.cpp.
Referenced by QDir::addResourceSearchPath().
 {
     if (!path.startsWith(QLatin1Char('/'))) {
         qWarning("QResource::addResourceSearchPath: Search paths must be absolute (start with /) [%s]",
                  path.toLocal8Bit().data());
         return;
     }
     QMutexLocker lock(resourceMutex());
     resourceSearchPaths()->prepend(path);
 }
children()
QStringList QResource::children () const protected
Returns a list of all resources in this directory, if the resource represents a file the list will be empty.
See also
isDir()
Definition at line 554 of file qresource.cpp.
Referenced by QResourceFileEngineIterator::hasNext(), and qwsFontPath().
 {
     Q_D(const QResource);
     d->ensureChildren();
     return d->children;
 }
data()
const uchar * QResource::data () const
Returns direct access to a read only segment of data that this resource represents.
If the resource is compressed the data returns is compressed and qUncompress() must be used to access the data. If the resource is a directory 0 is returned.
See also
size(), isCompressed(), isFile()
Definition at line 526 of file qresource.cpp.
Referenced by QFontDatabasePrivate::addQPF2File(), QTranslatorPrivate::do_load(), loadSingleEngine(), and QDynamicFileResourceRoot::registerSelf().
 {
     Q_D(const QResource);
     d->ensureInitialized();
     return d->data;
 }
fileName()
QString QResource::fileName () const
Returns the full path to the file that this QResource represents as it was passed.
See also
absoluteFilePath()
Definition at line 443 of file qresource.cpp.
Referenced by QDynamicFileResourceRoot::mappingFile().
 {
     Q_D(const QResource);
     d->ensureInitialized();
     return d->fileName;
 }
isCompressed()
bool QResource::isCompressed () const
Returns true if the resource represents a file and the data backing it is in a compressed format, false otherwise.
See also
data(), isFile()
Definition at line 497 of file qresource.cpp.
Referenced by QTranslatorPrivate::do_load().
 {
     Q_D(const QResource);
     d->ensureInitialized();
     return d->compressed;
 }
isDir()
bool QResource::isDir () const protected
Returns true if the resource represents a directory and thus may have children() in it, false if it represents a file.
See also
isFile()
Definition at line 540 of file qresource.cpp.
Referenced by qwsFontPath().
 {
     Q_D(const QResource);
     d->ensureInitialized();
     return d->container;
 }
isFile()
bool QResource::isFile () const inline protected
Returns true if the resource represents a file and thus has data backing it, false if it represents a directory.
See also
isDir()
Definition at line 90 of file qresource.h.
Referenced by qwsFontPath().
 { return !isDir(); }
isValid()
bool QResource::isValid () const
Returns true if the resource really exists in the resource hierarchy, false otherwise.
Definition at line 470 of file qresource.cpp.
Referenced by QTranslatorPrivate::do_load(), QResourceFileEngineIterator::hasNext(), and loadSingleEngine().
 {
     Q_D(const QResource);
     d->ensureInitialized();
     return !d->related.isEmpty();
 }
locale()
QLocale QResource::locale () const
Returns the locale used to locate the data for the QResource.
Definition at line 415 of file qresource.cpp.
Referenced by QResource(), and setLocale().
 {
     Q_D(const QResource);
     return d->locale;
 }
registerResource() [1/2]
bool QResource::registerResource (const QString & rccFileName, const QString & mapRoot = QString()) static
Registers the resource with the given rccFileName at the location in the resource tree specified by mapRoot, and returns true if the file is successfully opened; otherwise returns false.
See also
unregisterResource()
Definition at line 1077 of file qresource.cpp.
 {
     QString r = qt_resource_fixResourceRoot(resourceRoot);
     if(!r.isEmpty() && r[0] != QLatin1Char('/')) {
         qWarning("QDir::registerResource: Registering a resource [%s] must be rooted in an absolute path (start with /) [%s]",
                  rccFilename.toLocal8Bit().data(), resourceRoot.toLocal8Bit().data());
         return false;
     }
     QDynamicFileResourceRoot *root = new QDynamicFileResourceRoot(r);
     if(root->registerSelf(rccFilename)) {
         root->ref.ref();
         QMutexLocker lock(resourceMutex());
         resourceList()->append(root);
         return true;
     }
     delete root;
     return false;
 }
registerResource() [2/2]
bool QResource::registerResource (const uchar * rccData, const QString & mapRoot = QString()) static
Since
4.3
Registers the resource with the given rccData at the location in the resource tree specified by mapRoot, and returns true if the file is successfully opened; otherwise returns false.
Warning
The data must remain valid throughout the life of any QFile that may reference the resource data.
See also
unregisterResource()
Definition at line 1151 of file qresource.cpp.
 {
     QString r = qt_resource_fixResourceRoot(resourceRoot);
     if(!r.isEmpty() && r[0] != QLatin1Char('/')) {
         qWarning("QDir::registerResource: Registering a resource [%p] must be rooted in an absolute path (start with /) [%s]",
                  rccData, resourceRoot.toLocal8Bit().data());
         return false;
     }
     QDynamicBufferResourceRoot *root = new QDynamicBufferResourceRoot(r);
     if(root->registerSelf(rccData)) {
         root->ref.ref();
         QMutexLocker lock(resourceMutex());
         resourceList()->append(root);
         return true;
     }
     delete root;
     return false;
 }
searchPaths()
QStringList QResource::searchPaths () static
Use QDir::searchPaths() instead.
Returns the current search path list. This list is consulted when creating a relative resource.
See also
QDir::addSearchPath() QDir::setSearchPaths()
Definition at line 603 of file qresource.cpp.
 {
     QMutexLocker lock(resourceMutex());
     return *resourceSearchPaths();
 }
setFileName()
void QResource::setFileName (const QString & file)
Sets a QResource to point to file.
file can either be absolute, in which case it is opened directly, if relative then the file will be tried to be found in QDir::searchPaths().
See also
absoluteFilePath()
Definition at line 429 of file qresource.cpp.
 {
     Q_D(QResource);
     d->clear();
     d->fileName = file;
 }
setLocale()
void QResource::setLocale (const QLocale & locale)
Sets a QResource to only load the localization of resource to for locale.
If a resource for the specific locale is not found then the C locale is used.
See also
setFileName()
Definition at line 404 of file qresource.cpp.
 {
     Q_D(QResource);
     d->clear();
     d->locale = locale;
 }
size()
qint64 QResource::size () const
Returns the size of the data backing the resource.
See also
data(), isFile()
Definition at line 510 of file qresource.cpp.
Referenced by QFontDatabasePrivate::addQPF2File(), QTranslatorPrivate::do_load(), and loadSingleEngine().
 {
     Q_D(const QResource);
     d->ensureInitialized();
     return d->size;
 }
unregisterResource() [1/2]
bool QResource::unregisterResource (const QString & rccFileName, const QString & mapRoot = QString()) static
Unregisters the resource with the given rccFileName at the location in the resource tree specified by mapRoot, and returns true if the resource is successfully unloaded and no references exist for the resource; otherwise returns false.
See also
registerResource()
Definition at line 1112 of file qresource.cpp.
 {
     QString r = qt_resource_fixResourceRoot(resourceRoot);
     QMutexLocker lock(resourceMutex());
     ResourceList *list = resourceList();
     for(int i = 0; i < list->size(); ++i) {
         QResourceRoot *res = list->at(i);
         if(res->type() == QResourceRoot::Resource_File) {
         QDynamicFileResourceRoot *root = reinterpret_cast<QDynamicFileResourceRoot*>(res);
         if(root->mappingFile() == rccFilename && root->mappingRoot() == r) {
                 resourceList()->removeAt(i);
                 if(!root->ref.deref()) {
                     delete root;
                     return true;
                 }
                 return false;
             }
     }
     }
     return false;
 }
unregisterResource() [2/2]
bool QResource::unregisterResource (const uchar * rccData, const QString & mapRoot = QString()) static
Since
4.3
Unregisters the resource with the given rccData at the location in the resource tree specified by mapRoot, and returns true if the resource is successfully unloaded and no references exist into the resource; otherwise returns false.
See also
registerResource()
Definition at line 1183 of file qresource.cpp.
 {
     QString r = qt_resource_fixResourceRoot(resourceRoot);
     QMutexLocker lock(resourceMutex());
     ResourceList *list = resourceList();
     for(int i = 0; i < list->size(); ++i) {
         QResourceRoot *res = list->at(i);
         if(res->type() == QResourceRoot::Resource_Buffer) {
         QDynamicBufferResourceRoot *root = reinterpret_cast<QDynamicBufferResourceRoot*>(res);
         if(root->mappingBuffer() == rccData && root->mappingRoot() == r) {
                 resourceList()->removeAt(i);
                 if(!root->ref.deref()) {
                     delete root;
                     return true;
                 }
         return false;
             }
     }
     }
     return false;
 }
Friends and Related Functions
QResourceFileEngine
friend class QResourceFileEngine friend
Definition at line 87 of file qresource.h.
QResourceFileEngineIterator
friend class QResourceFileEngineIterator friend
Definition at line 88 of file qresource.h.
Properties
d_ptr
QScopedPointer<QResourcePrivate> QResource::d_ptr protected
Definition at line 94 of file qresource.h.
The documentation for this class was generated from the following files:
/src/corelib/io/qresource.h
/src/corelib/io/qresource.cpp