Qt 4.8: QScript::FunctionWithArgWrapper Class Reference
QScript::FunctionWithArgWrapper Class Reference
#include <qscriptfunction_p.h>
Classes
struct Data
Public Functions
void * arg () const
virtual const JSC::ClassInfo * classInfo () const
QScriptEngine::FunctionWithArgSignature function () const
FunctionWithArgWrapper (JSC::ExecState *, int length, const JSC::Identifier &, QScriptEngine::FunctionWithArgSignature, void *)
~FunctionWithArgWrapper ()
Static Public Variables
static const JSC::ClassInfo info = { "QtNativeFunctionWithArgWrapper", &PrototypeFunction::info, 0, 0 }
Private Functions
virtual JSC::ConstructType getConstructData (JSC::ConstructData &)
Static Private Functions
static JSC::JSValue JSC_HOST_CALL proxyCall (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSObject * proxyConstruct (JSC::ExecState *, JSC::JSObject *, const JSC::ArgList &)
Properties
Data * data
Detailed Description
Definition at line 80 of file qscriptfunction_p.h.
Constructors and Destructors
FunctionWithArgWrapper()
QScript::FunctionWithArgWrapper::FunctionWithArgWrapper (JSC::ExecState * exec, int length, const JSC::Identifier & name, QScriptEngine::FunctionWithArgSignature function, void * arg)
Definition at line 116 of file qscriptfunction.cpp.
     : JSC::PrototypeFunction(exec, length, name, proxyCall),
       data(new Data())
 {
     data->function = function;
     data->arg = arg;
 }
~FunctionWithArgWrapper()
QScript::FunctionWithArgWrapper::~FunctionWithArgWrapper ()
Definition at line 125 of file qscriptfunction.cpp.
 {
     delete data;
 }
Functions
arg()
void* QScript::FunctionWithArgWrapper::arg () const inline
Definition at line 100 of file qscriptfunction_p.h.
Referenced by QScript::QMetaObjectWrapperObject::execute(), and FunctionWithArgWrapper().
     { return data->arg; }
classInfo()
virtual const JSC::ClassInfo* QScript::FunctionWithArgWrapper::classInfo () const inline virtual
Definition at line 94 of file qscriptfunction_p.h.
 { return &info; }
function()
QScriptEngine::FunctionWithArgSignature QScript::FunctionWithArgWrapper::function () const inline
Definition at line 97 of file qscriptfunction_p.h.
Referenced by QScript::QMetaObjectWrapperObject::execute().
     { return data->function; }
getConstructData()
JSC::ConstructType QScript::FunctionWithArgWrapper::getConstructData (JSC::ConstructData & consData) private virtual
Definition at line 130 of file qscriptfunction.cpp.
 {
     consData.native.function = proxyConstruct;
     return JSC::ConstructTypeHost;
 }
proxyCall()
JSC::JSValue QScript::FunctionWithArgWrapper::proxyCall (JSC::ExecState * exec, JSC::JSObject * callee, JSC::JSValue thisObject, const JSC::ArgList & args) static private
Definition at line 136 of file qscriptfunction.cpp.
 {
     FunctionWithArgWrapper *self = static_cast<FunctionWithArgWrapper*>(callee);
     QScriptEnginePrivate *eng_p = QScript::scriptEngineFromExec(exec);
     JSC::ExecState *oldFrame = eng_p->currentFrame;
     eng_p->pushContext(exec, thisObject, args, callee);
     QScriptContext *ctx = eng_p->contextForFrame(eng_p->currentFrame);
     QScriptValue result = self->data->function(ctx, QScriptEnginePrivate::get(eng_p), self->data->arg);
     eng_p->popContext();
     eng_p->currentFrame = oldFrame;
     return eng_p->scriptValueToJSCValue(result);
 }
proxyConstruct()
JSC::JSObject * QScript::FunctionWithArgWrapper::proxyConstruct (JSC::ExecState * exec, JSC::JSObject * callee, const JSC::ArgList & args) static private
Definition at line 154 of file qscriptfunction.cpp.
Referenced by getConstructData().
 {
     FunctionWithArgWrapper *self = static_cast<FunctionWithArgWrapper*>(callee);
     QScriptEnginePrivate *eng_p = QScript::scriptEngineFromExec(exec);
     JSC::ExecState *oldFrame = eng_p->currentFrame;
     eng_p->pushContext(exec, JSC::JSValue(), args, callee, true);
     QScriptContext *ctx = eng_p->contextForFrame(eng_p->currentFrame);
     QScriptValue result = self->data->function(ctx, QScriptEnginePrivate::get(eng_p) , self->data->arg);
     if (!result.isObject())
         result = ctx->thisObject();
     eng_p->popContext();
     eng_p->currentFrame = oldFrame;
     return JSC::asObject(eng_p->scriptValueToJSCValue(result));
 }
Properties
data
Data* QScript::FunctionWithArgWrapper::data private
Definition at line 112 of file qscriptfunction_p.h.
Referenced by FunctionWithArgWrapper(), and ~FunctionWithArgWrapper().
info
const JSC::ClassInfo QScript::FunctionWithArgWrapper::info = { "QtNativeFunctionWithArgWrapper", &PrototypeFunction::info, 0, 0 } static
Definition at line 95 of file qscriptfunction_p.h.
Referenced by QScript::QMetaObjectWrapperObject::execute().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptfunction_p.h
/src/script/bridge/qscriptfunction.cpp