Qt 4.8: QClipboardData Class Reference
QClipboardData Class Reference
Public Functions
void clear ()
void clear ()
QClipboardData ()
QClipboardData ()
QClipboardData ()
QClipboardData (QClipboard::Mode mode)
void releaseIData ()
void setSource (QMimeData *s)
void setSource (QMimeData *s)
void setSource (QMimeData *s)
QMimeData * source ()
QMimeData * source ()
QMimeData * source () const
~QClipboardData ()
~QClipboardData ()
~QClipboardData ()
~QClipboardData ()
Public Variables
QWidget * clipBoardViewer
QOleDataObject * iData
QClipboard::Mode mode
HWND nextClipboardViewer
Time timestamp
QClipboardWatcher watcher
Static Public Variables
static QMimeData * clipboardData = 0
static QMimeData * selectionData = 0
Private Functions
QMimeData *& mimeDataRef () const
Properties
QMimeData * src
Detailed Description
Definition at line 105 of file qclipboard_qws.cpp.
Constructors and Destructors
QClipboardData() [1/4]
QClipboardData::QClipboardData ()
Definition at line 144 of file qclipboard_qws.cpp.
Referenced by clipboardData(), and source().
 {
     src = 0;
 #if 0
     tindex=0;
 #endif
 }
~QClipboardData() [1/4]
QClipboardData::~QClipboardData ()
Definition at line 152 of file qclipboard_qws.cpp.
Referenced by QClipboardData(), and source().
 {
     delete src;
 }
QClipboardData() [2/4]
QClipboardData::QClipboardData () inline
Definition at line 141 of file qclipboard_win.cpp.
         : iData(0)
         , nextClipboardViewer(0)
     {
         clipBoardViewer = new QWidget();
         clipBoardViewer->createWinId();
         clipBoardViewer->setObjectName(QLatin1String("internal clipboard owner"));
         // We don't need this internal widget to appear in QApplication::topLevelWidgets()
         if (QWidgetPrivate::allWidgets)
             QWidgetPrivate::allWidgets->remove(clipBoardViewer);
     }
~QClipboardData() [2/4]
QClipboardData::~QClipboardData () inline
Definition at line 153 of file qclipboard_win.cpp.
     {
         Q_ASSERT(clipBoardViewer->testAttribute(Qt::WA_WState_Created));
         ChangeClipboardChain(clipBoardViewer->internalWinId(), nextClipboardViewer);
         delete clipBoardViewer;
         releaseIData();
     }
QClipboardData() [3/4]
QClipboardData::QClipboardData (QClipboard::Mode mode)
Definition at line 214 of file qclipboard_x11.cpp.
 {
     timestamp = CurrentTime;
     mode = clipboardMode;
 }
~QClipboardData() [3/4]
QClipboardData::~QClipboardData ()
QClipboardData() [4/4]
QClipboardData::QClipboardData ()
~QClipboardData() [4/4]
QClipboardData::~QClipboardData ()
Functions
clear() [1/2]
void QClipboardData::clear ()
Definition at line 157 of file qclipboard_qws.cpp.
Referenced by QClipboardWatcher::getDataInFormat(), qt_check_clipboard_sentinel(), qt_check_selection_sentinel(), and source().
 {
     delete src;
     src = 0;
 }
clear() [2/2]
void QClipboardData::clear () inline
Definition at line 193 of file qclipboard_x11.cpp.
     {
         timestamp = CurrentTime;
         if (selectionData == clipboardData) {
             mimeDataRef() = 0;
         } else {
             QMimeData *&src = mimeDataRef();
             delete src;
             src = 0;
         }
     }
mimeDataRef()
QMimeData*& QClipboardData::mimeDataRef () const inline private
Definition at line 163 of file qclipboard_x11.cpp.
     {
         if(mode == QClipboard::Selection)
             return selectionData;
         return clipboardData;
     }
releaseIData()
void QClipboardData::releaseIData () inline
Definition at line 161 of file qclipboard_win.cpp.
Referenced by isProcessBeingDebugged(), and QClipboard::~QClipboard().
     {
         if (iData) {
             delete iData->mimeData();
             iData->releaseQt();
             iData->Release();
             iData = 0;
         }
     }
setSource() [1/3]
void QClipboardData::setSource (QMimeData * s) inline
Definition at line 55 of file qplatformclipboard_qpa.cpp.
     {
         if (s == src)
             return;
         delete src;
         src = s;
     }
setSource() [2/3]
void QClipboardData::setSource (QMimeData * s) inline
Definition at line 111 of file qclipboard_qws.cpp.
Referenced by clipboardData(), and QClipboardWatcher::getDataInFormat().
     {
         if (s == src)
             return;
         delete src;
         src = s;
     }
setSource() [3/3]
void QClipboardData::setSource (QMimeData * s) inline
Definition at line 174 of file qclipboard_x11.cpp.
     {
         if ((mode == QClipboard::Selection && selectionData == s)
             || clipboardData == s) {
             return;
         }
         if (selectionData != clipboardData) {
             delete mimeDataRef();
         }
         mimeDataRef() = s;
     }
source() [1/3]
QMimeData* QClipboardData::source () inline
Definition at line 62 of file qplatformclipboard_qpa.cpp.
         { return src; }
source() [2/3]
QMimeData* QClipboardData::source () inline
Definition at line 118 of file qclipboard_qws.cpp.
Referenced by clipboardData(), QClipboardWatcher::getDataInFormat(), send_selection(), and send_targets_selection().
         { return src; }
source() [3/3]
QMimeData* QClipboardData::source () const inline
Definition at line 188 of file qclipboard_x11.cpp.
     {
         return mimeDataRef();
     }
Properties
clipboardData
QMimeData * QClipboardData::clipboardData = 0 static
Definition at line 206 of file qclipboard_x11.cpp.
Referenced by clipboardData().
clipBoardViewer
QWidget* QClipboardData::clipBoardViewer
Definition at line 172 of file qclipboard_win.cpp.
Referenced by clipboardData(), isProcessBeingDebugged(), QtCeGetClipboard(), and QtCeSetClipboard().
iData
QOleDataObject* QClipboardData::iData
Definition at line 171 of file qclipboard_win.cpp.
Referenced by isProcessBeingDebugged(), and QClipboard::~QClipboard().
mode
QClipboard::Mode QClipboardData::mode
Definition at line 208 of file qclipboard_x11.cpp.
Referenced by clipboardData().
nextClipboardViewer
HWND QClipboardData::nextClipboardViewer
Definition at line 173 of file qclipboard_win.cpp.
Referenced by clipboardData(), and isProcessBeingDebugged().
selectionData
QMimeData * QClipboardData::selectionData = 0 static
Definition at line 205 of file qclipboard_x11.cpp.
src
QMimeData * QClipboardData::src private
Definition at line 136 of file qclipboard_qws.cpp.
Referenced by clear(), clipboardData(), QClipboardData(), setSource(), source(), and ~QClipboardData().
timestamp
Time QClipboardData::timestamp
Definition at line 207 of file qclipboard_x11.cpp.
Referenced by QClipboardWatcher::getDataInFormat(), qt_xfixes_clipboard_changed(), and qt_xfixes_selection_changed().
watcher
QClipboardWatcher QClipboardData::watcher
Definition at line 174 of file qclipboard_win.cpp.
Referenced by isProcessBeingDebugged().
The documentation for this class was generated from the following files:
/src/gui/kernel/qclipboard_qws.cpp
/src/gui/kernel/qclipboard_win.cpp
/src/gui/kernel/qclipboard_x11.cpp
/src/gui/kernel/qplatformclipboard_qpa.cpp