Qt 4.8: QAbstractXmlReceiver Class Reference
QAbstractXmlReceiver Class Reference abstract
The QAbstractXmlReceiver class provides a callback interface for transforming the output of a QXmlQuery.
#include <qabstractxmlreceiver.h>
Public Functions
virtual void atomicValue (const QVariant &value)=0
This callback is called when an atomic value appears in the XQuery Sequence.
virtual void attribute (const QXmlName &name, const QStringRef &value)=0
This callback is called when an attribute node appears in the XQuery Sequence.
virtual void characters (const QStringRef &value)=0
This callback is called when a text node appears in the XQuery Sequence.
virtual void comment (const QString &value)=0
This callback is called when a comment node appears in the XQuery Sequence.
virtual void endDocument ()=0
This callback is called when the end of a document node appears in the XQuery Sequence.
virtual void endElement ()=0
This callback is called when the end of an element node appears in the XQuery Sequence.
virtual void endOfSequence ()=0
This callback is called once only, right after the XQuery Sequence ends.
virtual void item (const QPatternist::Item &item)
virtual void namespaceBinding (const QXmlName &name)=0
This callback is called when a namespace binding is in scope of an element.
virtual void processingInstruction (const QXmlName &target, const QString &value)=0
This callback is called when a processing instruction appears in the XQuery Sequence.
QAbstractXmlReceiver ()
Constructs an abstract xml receiver.
virtual void startDocument ()=0
This callback is called when a document node appears in the XQuery Sequence.
virtual void startElement (const QXmlName &name)=0
This callback is called when a new element node appears in the XQuery Sequence.
virtual void startOfSequence ()=0
This callback is called once only, right before the XQuery Sequence begins.
virtual void whitespaceOnly (const QStringRef &value)
This function may be called instead of characters() if, and only if, value consists only of whitespace.
virtual ~QAbstractXmlReceiver ()
Destroys the xml receiver.
Protected Functions
QAbstractXmlReceiver (QAbstractXmlReceiverPrivate *d)
void sendAsNode (const QPatternist::Item &outputItem)
Treats outputItem as a node and calls the appropriate function, e.
Protected Variables
QScopedPointer< QAbstractXmlReceiverPrivate > d_ptr
Private Functions
template<const QXmlNodeModelIndex::Axis axis>
void sendFromAxis (const QXmlNodeModelIndex &node)
Detailed Description
The QAbstractXmlReceiver class provides a callback interface for transforming the output of a QXmlQuery.
Note
This class or function is reentrant.
Since
4.4
QAbstractXmlReceiver is an abstract base class that provides a callback interface for receiving an XQuery Sequence, usually the output of an QXmlQuery, and transforming that sequence into a structure of your choosing, usually XML. Consider the example:
QXmlQuery query;
query.setQuery("doc('index.html')/html/body/p[1]");
QXmlSerializer serializer(query, myOutputDevice);
query.evaluateTo(&serializer);
First it constructs a QXmlQuery {query} that gets the first paragraph from document index.html. Then it constructs an QXmlSerializer {XML serializer} with the QXmlQuery {query} and QIODevice {myOutputDevice} (Note the QXmlSerializer {serializer} is an {XML receiver}, ie a subclass of QAbstractXmlReceiver). Finally, it QXmlQuery::evaluateTo() {evaluates} the QXmlQuery {query}, producing an ordered sequence of calls to the QXmlSerializer {serializer's} callback functions. The sequence of callbacks transforms the query output to XML and writes it to QIODevice {myOutputDevice}.
Although the example uses QXmlQuery to produce the sequence of callbacks to functions in QAbstractXmlReceiver, you can call the callback functions directly as long as your sequence of calls represents a valid XQuery Sequence.
XQuery Sequences
An XQuery sequence is an ordered collection of zero, one, or many items. Each item is either an {atomic value} or a {node}. An {atomic value} is a simple data value.
There are six kinds of nodes.
An {Element Node} represents an XML element.
An {Attribute Node} represents an XML attribute.
A {Document Node} represents an entire XML document.
A {Text Node} represents character data (element content).
A {Processing Instruction Node} represents an XML processing instruction, which is used in an XML document to tell the application reading the document to perform some action. A typical example is to use a processing instruction to tell the application to use a particular XSLT stylesheet to display the document.
And a {Comment node} represents an XML comment.
The sequence of nodes and {atomic values} obeys the following rules. Note that {Namespace Node} refers to a special {Attribute Node} with name {xmlns}.
Each node appears in the sequence before its children and their descendants appear.
A node's descendants appear in the sequence before any of its siblings appear.
A {Document Node} represents an entire document. Zero or more {Document Nodes} can appear in a sequence, but they can only be top level items (i.e., a {Document Node} can't be a child of another node.
{Namespace Nodes} immediately follow the {Element Node} with which they are associated.
{Attribute Nodes} immediately follow the {Namespace Nodes} of the element with which they are associated, or...
If there are no {Namespace Nodes} following an element, then the {Attribute Nodes} immediately follow the element.
An {atomic value} can only appear as a top level item, i.e., it can't appear as a child of a node.
{Processing Instruction Nodes} do not have children, and their parent is either a {Document Node} or an {Element Node}.
{Comment Nodes} do not have children, and their parent is either a {Document Node} or an {Element Node}.
The sequence of nodes and {atomic values} is sent to an QAbstractXmlReceiver (QXmlSerializer in the example above) as a sequence of calls to the receiver's callback functions. The mapping of callback functions to sequence items is as follows.
startDocument() and endDocument() are called for each {Document Node} in the sequence. endDocument() is not called until all the {Document Node's} children have appeared in the sequence.
startElement() and endElement() are called for each {Element Node}. endElement() is not called until all the {Element Node's} children have appeared in the sequence.
attribute() is called for each {Attribute Node}.
comment() is called for each {Comment Node}.
characters() is called for each {Text Node}.
processingInstruction() is called for each {Processing Instruction Node}.
namespaceBinding() is called for each {Namespace Node}.
atomicValue() is called for each {atomic value}.
For a complete explanation of XQuery sequences, visit http://www.w3.org/TR/xpath-datamodel/ {XQuery Data Model}.
See also
{http://www.w3.org/TR/xpath-datamodel/}{W3C XQuery 1.0 and XPath 2.0 Data Model (XDM)}
QXmlSerializer
QXmlResultItems
Definition at line 63 of file qabstractxmlreceiver.h.
Constructors and Destructors
QAbstractXmlReceiver() [1/2]
QAbstractXmlReceiver::QAbstractXmlReceiver ()
Constructs an abstract xml receiver.
Definition at line 220 of file qabstractxmlreceiver.cpp.
                                            : d_ptr(0)
 {
 }
~QAbstractXmlReceiver()
QAbstractXmlReceiver::~QAbstractXmlReceiver () virtual
Destroys the xml receiver.
Definition at line 227 of file qabstractxmlreceiver.cpp.
 {
 }
QAbstractXmlReceiver() [2/2]
QAbstractXmlReceiver::QAbstractXmlReceiver (QAbstractXmlReceiverPrivate * d) protected
Warning
This function is not part of the public interface.
Definition at line 212 of file qabstractxmlreceiver.cpp.
   : d_ptr(d)
 {
 }
Functions
atomicValue()
void QAbstractXmlReceiver::atomicValue (const QVariant & value) pure virtual
This callback is called when an atomic value appears in the XQuery Sequence.
The value is a simple QVariant {data value}. It is guaranteed to be QVariant::isValid() {valid}.
Implemented in QXmlSerializer, and QXmlFormatter.
Referenced by item().
attribute()
void QAbstractXmlReceiver::attribute (const QXmlName & name, const QStringRef & value) pure virtual
This callback is called when an attribute node appears in the XQuery Sequence.
name is the QXmlName {attribute name} and the value string contains the attribute value.
Implemented in QXmlSerializer, and QXmlFormatter.
Referenced by sendAsNode().
characters()
void QAbstractXmlReceiver::characters (const QStringRef & value) pure virtual
This callback is called when a text node appears in the XQuery Sequence.
The value contains the text. Adjacent text nodes may not occur in the XQuery Sequence, i.e., this callback must not be called twice in a row.
Implemented in QXmlSerializer, and QXmlFormatter.
Referenced by sendAsNode(), and whitespaceOnly().
comment()
void QAbstractXmlReceiver::comment (const QString & value) pure virtual
This callback is called when a comment node appears in the XQuery Sequence.
The value is the comment text, which must not contain the string "--".
Implemented in QXmlSerializer, and QXmlFormatter.
Referenced by sendAsNode().
endDocument()
void QAbstractXmlReceiver::endDocument () pure virtual
This callback is called when the end of a document node appears in the XQuery Sequence.
Implemented in QXmlSerializer, and QXmlFormatter.
Referenced by sendAsNode().
endElement()
void QAbstractXmlReceiver::endElement () pure virtual
This callback is called when the end of an element node appears in the XQuery Sequence.
Implemented in QXmlSerializer, and QXmlFormatter.
Referenced by sendAsNode().
endOfSequence()
void QAbstractXmlReceiver::endOfSequence () pure virtual
This callback is called once only, right after the XQuery Sequence ends.
Implemented in QXmlSerializer, and QXmlFormatter.
Referenced by QXmlQuery::evaluateTo().
item()
void QAbstractXmlReceiver::item (const QPatternist::Item & item) virtual
Warning
This function is not part of the public interface.
Reimplemented in QXmlSerializer, and QXmlFormatter.
Definition at line 488 of file qabstractxmlreceiver.cpp.
 {
     if(item.isNode())
         return sendAsNode(item);
     else
         atomicValue(QPatternist::AtomicValue::toQt(item.asAtomicValue()));
 }
namespaceBinding()
void QAbstractXmlReceiver::namespaceBinding (const QXmlName & name) pure virtual
This callback is called when a namespace binding is in scope of an element.
A namespace is defined by a URI. In the QXmlName name, the value of QXmlName::namespaceUri() is that URI. The value of QXmlName::prefix() is the prefix that the URI is bound to. The local name is insignificant and can be an arbitrary value.
Implemented in QXmlSerializer.
processingInstruction()
void QAbstractXmlReceiver::processingInstruction (const QXmlName & target, const QString & value) pure virtual
This callback is called when a processing instruction appears in the XQuery Sequence.
A processing instruction is used in an XML document to tell the application reading the document to perform some action. A typical example is to use a processing instruction to tell the application to use a particular XSLT stylesheet to process the document.
<?xml-stylesheet type="test/xsl" href="formatter.xsl"?>
target is the QXmlName {name} of the processing instruction. Its prefix and {namespace URI} must both be empty. Its {local name} is the target. In the above example, the name is {xml-stylesheet}.
The value specifies the action to be taken. Note that the value must not contain the string "?>". In the above example, the value is type="test/xsl" href="formatter.xsl.
Generally, use of processing instructions should be avoided, because they are not namespace aware and in many contexts are stripped out anyway. Processing instructions can often be replaced with elements from a custom namespace.
Implemented in QXmlSerializer, and QXmlFormatter.
Referenced by sendAsNode().
sendAsNode()
void QAbstractXmlReceiver::sendAsNode (const QPatternist::Item & outputItem) protected
Treats outputItem as a node and calls the appropriate function, e.
Warning
This function is not part of the public interface.
g., attribute() or comment(), depending on its QXmlNodeModelIndex::NodeKind.
This is a helper function that subclasses can use to multiplex Nodes received via item().
Definition at line 397 of file qabstractxmlreceiver.cpp.
Referenced by item(), QXmlSerializer::item(), and sendFromAxis().
 {
     Q_ASSERT(outputItem);
     Q_ASSERT(outputItem.isNode());
     const QXmlNodeModelIndex asNode = outputItem.asNode();
     switch(asNode.kind())
     {
         case QXmlNodeModelIndex::Attribute:
         {
             const QString &v = outputItem.stringValue();
             attribute(asNode.name(), QStringRef(&v));
             return;
         }
         case QXmlNodeModelIndex::Element:
         {
             startElement(asNode.name());
             /* First the namespaces, then attributes, then the children. */
             asNode.sendNamespaces(this);
             sendFromAxis<QXmlNodeModelIndex::AxisAttribute>(asNode);
             sendFromAxis<QXmlNodeModelIndex::AxisChild>(asNode);
             endElement();
             return;
         }
         case QXmlNodeModelIndex::Text:
         {
             const QString &v = asNode.stringValue();
             characters(QStringRef(&v));
             return;
         }
         case QXmlNodeModelIndex::ProcessingInstruction:
         {
             processingInstruction(asNode.name(), outputItem.stringValue());
             return;
         }
         case QXmlNodeModelIndex::Comment:
         {
             comment(outputItem.stringValue());
             return;
         }
         case QXmlNodeModelIndex::Document:
         {
             startDocument();
             sendFromAxis<QXmlNodeModelIndex::AxisChild>(asNode);
             endDocument();
             return;
         }
         case QXmlNodeModelIndex::Namespace:
             Q_ASSERT_X(false, Q_FUNC_INFO, "Not implemented");
     }
     Q_ASSERT_X(false, Q_FUNC_INFO,
                QString::fromLatin1("Unknown node type: %1").arg(asNode.kind()).toUtf8().constData());
 }
sendFromAxis()
template<const QXmlNodeModelIndex::Axis axis> void QAbstractXmlReceiver::sendFromAxis (const QXmlNodeModelIndex & node) private
Definition at line 196 of file qabstractxmlreceiver.cpp.
 {
     Q_ASSERT(!node.isNull());
     const QXmlNodeModelIndex::Iterator::Ptr it(node.iterate(axis));
     QXmlNodeModelIndex next(it->next());
     while(!next.isNull())
     {
         sendAsNode(next);
         next = it->next();
     }
 }
startDocument()
void QAbstractXmlReceiver::startDocument () pure virtual
This callback is called when a document node appears in the XQuery Sequence.
Implemented in QXmlSerializer, and QXmlFormatter.
Referenced by sendAsNode().
startElement()
void QAbstractXmlReceiver::startElement (const QXmlName & name) pure virtual
This callback is called when a new element node appears in the XQuery Sequence.
name is the valid QXmlName {name} of the node element.
Implemented in QXmlSerializer, and QXmlFormatter.
Referenced by sendAsNode().
startOfSequence()
void QAbstractXmlReceiver::startOfSequence () pure virtual
This callback is called once only, right before the XQuery Sequence begins.
Implemented in QXmlSerializer, and QXmlFormatter.
Referenced by QXmlQuery::evaluateTo().
whitespaceOnly()
void QAbstractXmlReceiver::whitespaceOnly (const QStringRef & value) virtual
This function may be called instead of characters() if, and only if, value consists only of whitespace.
Warning
This function is not part of the public interface.
The caller gurantees that value is not empty.
Whitespace refers to a sequence of characters that are either spaces, tabs, or newlines, in any order. In other words, not all the Unicode whitespace category is considered whitespace here.
However, there is no guarantee or requirement that whitespaceOnly() is called for text nodes containing whitespace only. characters() may be called just as well. This is why the default implementation for whitespaceOnly() calls characters().
See also
characters()
Definition at line 477 of file qabstractxmlreceiver.cpp.
 {
     Q_ASSERT_X(value.toString().trimmed().isEmpty(), Q_FUNC_INFO,
                "The caller must guarantee only whitespace is passed. Use characters() in other cases.");
     const QString &v = value.toString();
     characters(QStringRef(&v));
 }
Properties
d_ptr
QScopedPointer<QAbstractXmlReceiverPrivate> QAbstractXmlReceiver::d_ptr protected
Definition at line 94 of file qabstractxmlreceiver.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qabstractxmlreceiver.h
/src/xmlpatterns/api/qabstractxmlreceiver.cpp