Qt 4.8: QAxObject Class Reference
QAxObject Class Reference
The QAxObject class provides a QObject that wraps a COM object.
#include <qaxobject.h>
Public Functions
const char * className () const
bool doVerb (const QString &verb)
Requests the COM object to perform the action verb.
const QMetaObject * metaObject () const
QAxObject (QObject *parent=0)
Creates an empty COM object and propagates parent to the QObject constructor.
QAxObject (const QString &c, QObject *parent=0)
Creates a QAxObject that wraps the COM object c.
QAxObject (IUnknown *iface, QObject *parent=0)
Creates a QAxObject that wraps the COM object referenced by iface.
QObject * qObject () const
int qt_metacall (QMetaObject::Call, int, void **)
void * qt_metacast (const char *)
~QAxObject ()
Releases the COM object and destroys the QAxObject, cleaning up all allocated resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QAxBase
QVariant asVariant () const
Returns a QVariant that wraps the COM object.
virtual void clear ()
Disconnects and destroys the COM object.
QString control () const
the name of the COM object wrapped by this QAxBase object.
void disableClassInfo ()
Disables the class info generation for this ActiveX container.
void disableEventSink ()
Disables the event sink implementation for this ActiveX container.
void disableMetaObject ()
Disables the meta object generation for this ActiveX container.
QVariant dynamicCall (const char *name, const QVariant &v1=QVariant(), const QVariant &v2=QVariant(), const QVariant &v3=QVariant(), const QVariant &v4=QVariant(), const QVariant &v5=QVariant(), const QVariant &v6=QVariant(), const QVariant &v7=QVariant(), const QVariant &v8=QVariant())
Calls the COM object's method function, passing the parameters var1, var1, var2, var3, var4, var5, var6, var7 and var8, and returns the value returned by the method, or an invalid QVariant if the method does not return a value or when the function call failed.
QVariant dynamicCall (const char *name, QList< QVariant > &vars)
Calls the COM object's method function, passing the parameters in vars, and returns the value returned by the method.
QString generateDocumentation ()
Returns a rich text string with documentation for the wrapped COM object.
bool isNull () const
Returns true if there is no COM object loaded by this wrapper; otherwise return false.
PropertyBag propertyBag () const
Returns a name:value map of all the properties exposed by the COM object.
virtual bool propertyWritable (const char *) const
Returns true if the property prop is writable; otherwise returns false.
QAxBase (IUnknown *iface=0)
Creates a QAxBase object that wraps the COM object iface.
long queryInterface (const QUuid &, void **) const
Requests the interface uuid from the COM object and sets the value of iface to the provided interface, or to 0 if the requested interface could not be provided.
QAxObject * querySubObject (const char *name, const QVariant &v1=QVariant(), const QVariant &v2=QVariant(), const QVariant &v3=QVariant(), const QVariant &v4=QVariant(), const QVariant &v5=QVariant(), const QVariant &v6=QVariant(), const QVariant &v7=QVariant(), const QVariant &v8=QVariant())
Returns a pointer to a QAxObject wrapping the COM object provided by the method or property name, passing passing the parameters var1, var1, var2, var3, var4, var5, var6, var7 and var8.
QAxObject * querySubObject (const char *name, QList< QVariant > &vars)
The QVariant objects in vars are updated when the method has out-parameters.
bool setControl (const QString &)
void setPropertyBag (const PropertyBag &)
Sets the properties of the COM object to the corresponding values in bag.
virtual void setPropertyWritable (const char *, bool)
Sets the property prop to writable if ok is true, otherwise sets prop to be read-only.
QStringList verbs () const
Returns the list of verbs that the COM object can execute.
virtual ~QAxBase ()
Shuts down the COM object and destroys the QAxBase object.
Protected Functions
void connectNotify (const char *signal)
Reimplemented Function
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QAxBase
void connectNotify ()
Connects to all event interfaces of the object.
long indexOfVerb (const QString &verb) const
virtual bool initialize (IUnknown **ptr)
This virtual function is called by setControl() and creates the requested COM object.
bool initializeActive (IUnknown **ptr)
Connects to an active instance running on the current machine, and returns the IUnknown interface to the running object in ptr.
void initializeFrom (QAxBase *that)
Used by subclasses generated with dumpcpp to implement cast-operators.
bool initializeFromFile (IUnknown **ptr)
Creates the COM object handling the filename in the control property, and returns the IUnknown interface to the object in ptr.
bool initializeLicensed (IUnknown **ptr)
Creates an instance of a licensed control, and returns the IUnknown interface to the object in ptr.
bool initializeRemote (IUnknown **ptr)
Creates the instance on a remote server, and returns the IUnknown interface to the object in ptr.
void internalRelease ()
Used by subclasses generated with dumpcpp to balance reference count.
Private Functions
const QMetaObject * parentMetaObject () const
Static Private Attributes
static QMetaObject staticMetaObject
Friends
class QAxEventSink
Additional Inherited Members
Public Types inherited from QAxBase
typedef QMap< QString, QVariant > PropertyBag
A QMap<QString,QVariant> that can store properties as name:value pairs.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Signals inherited from QAxBase
void exception (int, const QString &, const QString &, const QString &)
This signal is emitted when the COM object throws an exception while called using the OLE automation interface IDispatch.
void propertyChanged (const QString &)
If the COM object supports property notification, this signal gets emitted when the property called name is changed.
void signal (const QString &, int, void *)
This generic signal gets emitted when the COM object issues the event name.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAxObject class provides a QObject that wraps a COM object.
Attention
Module: QAxContainer
A QAxObject can be instantiated as an empty object, with the name of the COM object it should wrap, or with a pointer to the IUnknown that represents an existing COM object. If the COM object implements the IDispatch interface, the properties, methods and events of that object become available as Qt properties, slots and signals. The base class, QAxBase, provides an API to access the COM object directly through the IUnknown pointer.
QAxObject is a QObject and can be used as such, e.g. it can be organized in an object hierarchy, receive events and connect to signals and slots.
QAxObject also inherits most of its ActiveX-related functionality from QAxBase, notably dynamicCall() and querySubObject().
Warning
You can subclass QAxObject, but you cannot use the Q_OBJECT macro in the subclass (the generated moc-file will not compile), so you cannot add further signals, slots or properties. This limitation is due to the metaobject information generated in runtime. To work around this problem, aggregate the QAxObject as a member of the QObject subclass.
See also
QAxBase, QAxWidget, QAxScript, {ActiveQt Framework}
Definition at line 54 of file qaxobject.h.
Constructors and Destructors
QAxObject() [1/3]
QAxObject::QAxObject (QObject * parent = 0)
Creates an empty COM object and propagates parent to the QObject constructor.
To initialize the object, call setControl .
Definition at line 93 of file qaxobject.cpp.
Referenced by qObject().
 : QObject(parent)
 {
 }
QAxObject() [2/3]
QAxObject::QAxObject (const QString & c, QObject * parent = 0)
Creates a QAxObject that wraps the COM object c.
parent is propagated to the QObject constructor.
See also
setControl()
Definition at line 104 of file qaxobject.cpp.
 : QObject(parent)
 {
     setControl(c);
 }
QAxObject() [3/3]
QAxObject::QAxObject (IUnknown * iface, QObject * parent = 0)
Creates a QAxObject that wraps the COM object referenced by iface.
parent is propagated to the QObject constructor.
Definition at line 114 of file qaxobject.cpp.
 : QObject(parent), QAxBase(iface)
 {
 }
~QAxObject()
QAxObject::~QAxObject ()
Releases the COM object and destroys the QAxObject, cleaning up all allocated resources.
Definition at line 123 of file qaxobject.cpp.
Referenced by qObject().
 {
     clear();
 }
Functions
className()
const char * QAxObject::className () const virtual
Warning
This function is not part of the public interface.
Implements QAxBase.
Definition at line 157 of file qaxobject.cpp.
Referenced by qObject().
 {
     return "QAxObject";
 }
connectNotify()
void QAxObject::connectNotify (const char * signal) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 181 of file qaxobject.cpp.
 {
     QAxBase::connectNotify();
 }
doVerb()
bool QAxObject::doVerb (const QString & verb)
Requests the COM object to perform the action verb.
Since
4.1
The possible verbs are returned by verbs().
The function returns true if the object could perform the action, otherwise returns false.
Definition at line 197 of file qaxobject.cpp.
Referenced by qObject().
 {
     if (!verbs().contains(verb))
         return false;
     IOleObject *ole = 0;
     queryInterface(IID_IOleObject, (void**)&ole);
     if (!ole)
         return false;
     LONG index = indexOfVerb(verb);
     HRESULT hres = ole->DoVerb(index, 0, 0, 0, 0, 0);
     ole->Release();
     return hres == S_OK;
 }
metaObject()
const QMetaObject * QAxObject::metaObject () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QAxBase.
Definition at line 131 of file qaxobject.cpp.
Referenced by QAxScript::functions(), and QAxScript::load().
 {
     return QAxBase::metaObject();
 }
parentMetaObject()
const QMetaObject * QAxObject::parentMetaObject () const private virtual
Warning
This function is not part of the public interface.
Implements QAxBase.
Definition at line 139 of file qaxobject.cpp.
Referenced by qObject().
 {
     return &QObject::staticMetaObject;
 }
qObject()
QObject * QAxObject::qObject () const inline virtual
Warning
This function is not part of the public interface.
Implements QAxBase.
Definition at line 61 of file qaxobject.h.
 { return (QObject*)this; }
qt_metacall()
int QAxObject::qt_metacall (QMetaObject::Call call, int id, void ** v) virtual
Warning
This function is not part of the public interface.
Reimplemented from QAxBase.
Definition at line 165 of file qaxobject.cpp.
 {
     id = QObject::qt_metacall(call, id, v);
     if (id < 0)
         return id;
     return QAxBase::qt_metacall(call, id, v);
 }
qt_metacast()
void * QAxObject::qt_metacast (const char * cname)
Warning
This function is not part of the public interface.
Definition at line 147 of file qaxobject.cpp.
Referenced by qobject_cast< QAxObject * >().
 {
     if (!qstrcmp(cname, "QAxObject")) return (void*)this;
     if (!qstrcmp(cname, "QAxBase")) return (QAxBase*)this;
     return QObject::qt_metacast(cname);
 }
Friends and Related Functions
QAxEventSink
friend class QAxEventSink friend
Definition at line 56 of file qaxobject.h.
Properties
staticMetaObject
QMetaObject QAxObject::staticMetaObject static private
Definition at line 76 of file qaxobject.h.
The documentation for this class was generated from the following files:
/src/activeqt/container/qaxobject.h
/src/activeqt/container/qaxobject.cpp