Qt 4.8: QDateTimeEdit Class Reference
QDateTimeEdit Class Reference
The QDateTimeEdit class provides a widget for editing dates and times.
#include <qdatetimeedit.h>
Public Types
enum Section {
NoSection = 0x0000, AmPmSection = 0x0001, MSecSection = 0x0002, SecondSection = 0x0004,
MinuteSection = 0x0008, HourSection = 0x0010, DaySection = 0x0100, MonthSection = 0x0200,
YearSection = 0x0400, TimeSections_Mask = AmPmSection|MSecSection|SecondSection|MinuteSection|HourSection, DateSections_Mask = DaySection|MonthSection|YearSection
}
Public Types inherited from QAbstractSpinBox
enum ButtonSymbols { UpDownArrows, PlusMinus, NoButtons }
This enum type describes the symbols that can be displayed on the buttons in a spin box.
enum CorrectionMode { CorrectToPreviousValue, CorrectToNearestValue }
This enum type describes the mode the spinbox will use to correct an QValidator::Intermediate value if editing finishes.
enum StepEnabledFlag { StepNone = 0x00, StepUpEnabled = 0x01, StepDownEnabled = 0x02 }
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void setDate (const QDate &date)
void setDateTime (const QDateTime &dateTime)
void setTime (const QTime &time)
Public Slots inherited from QAbstractSpinBox
void selectAll ()
Selects all the text in the spinbox except the prefix and suffix.
void stepDown ()
Steps down by one linestep Calling this slot is analogous to calling stepBy(-1);.
void stepUp ()
Steps up by one linestep Calling this slot is analogous to calling stepBy(1);.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void dateChanged (const QDate &date)
This signal is emitted whenever the date is changed.
void dateTimeChanged (const QDateTime &date)
This signal is emitted whenever the date or time is changed.
void timeChanged (const QTime &date)
This signal is emitted whenever the time is changed.
Signals inherited from QAbstractSpinBox
void editingFinished ()
This signal is emitted editing is finished.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool calendarPopup () const
QCalendarWidget * calendarWidget () const
Returns the calendar widget for the editor if calendarPopup is set to true and (sections() & DateSections_Mask) != 0.
virtual void clear ()
Reimplemented Function
void clearMaximumDate ()
void clearMaximumDateTime ()
void clearMaximumTime ()
void clearMinimumDate ()
void clearMinimumDateTime ()
void clearMinimumTime ()
Section currentSection () const
int currentSectionIndex () const
QDate date () const
QDateTime dateTime () const
Sections displayedSections () const
QString displayFormat () const
bool event (QEvent *event)
Reimplemented Function
QDate maximumDate () const
QDateTime maximumDateTime () const
QTime maximumTime () const
QDate minimumDate () const
QDateTime minimumDateTime () const
QTime minimumTime () const
QDateTimeEdit (QWidget *parent=0)
Constructs an empty date time editor with a parent.
QDateTimeEdit (const QDateTime &dt, QWidget *parent=0)
Constructs an empty date time editor with a parent.
QDateTimeEdit (const QDate &d, QWidget *parent=0)
Constructs an empty date time editor with a parent.
QDateTimeEdit (const QTime &t, QWidget *parent=0)
Constructs an empty date time editor with a parent.
Section sectionAt (int index) const
Returns the Section at index.
int sectionCount () const
QString sectionText (Section section) const
Returns the text from the given section.
void setCalendarPopup (bool enable)
void setCalendarWidget (QCalendarWidget *calendarWidget)
Sets the given calendarWidget as the widget to be used for the calendar pop-up.
void setCurrentSection (Section section)
void setCurrentSectionIndex (int index)
void setDateRange (const QDate &min, const QDate &max)
Convenience function to set minimum and maximum date with one function call.
void setDateTimeRange (const QDateTime &min, const QDateTime &max)
Convenience function to set minimum and maximum date time with one function call.
void setDisplayFormat (const QString &format)
void setMaximumDate (const QDate &max)
void setMaximumDateTime (const QDateTime &dt)
void setMaximumTime (const QTime &max)
void setMinimumDate (const QDate &min)
void setMinimumDateTime (const QDateTime &dt)
void setMinimumTime (const QTime &min)
void setSelectedSection (Section section)
Selects section.
void setTimeRange (const QTime &min, const QTime &max)
Convenience function to set minimum and maximum time with one function call.
void setTimeSpec (Qt::TimeSpec spec)
QSize sizeHint () const
Reimplemented Function
virtual void stepBy (int steps)
Reimplemented Function
QTime time () const
Qt::TimeSpec timeSpec () const
Public Functions inherited from QAbstractSpinBox
Qt::Alignment alignment () const
ButtonSymbols buttonSymbols () const
CorrectionMode correctionMode () const
bool hasAcceptableInput () const
bool hasFrame () const
QVariant inputMethodQuery (Qt::InputMethodQuery) const
Reimplemented Function
void interpretText ()
This function interprets the text of the spin box.
bool isAccelerated () const
bool isReadOnly () const
bool keyboardTracking () const
QSize minimumSizeHint () const
Reimplemented Function
QAbstractSpinBox (QWidget *parent=0)
Constructs an abstract spinbox with the given parent with default wrapping , and alignment properties.
void setAccelerated (bool on)
void setAlignment (Qt::Alignment flag)
void setButtonSymbols (ButtonSymbols bs)
void setCorrectionMode (CorrectionMode cm)
void setFrame (bool)
void setKeyboardTracking (bool kt)
void setReadOnly (bool r)
void setSpecialValueText (const QString &txt)
void setWrapping (bool w)
QString specialValueText () const
QString text () const
bool wrapping () const
~QAbstractSpinBox ()
Called when the QAbstractSpinBox is destroyed.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
virtual QDateTime dateTimeFromText (const QString &text) const
Returns an appropriate datetime for the given text.
virtual void fixup (QString &input) const
Reimplemented Function
virtual void focusInEvent (QFocusEvent *event)
Reimplemented Function
virtual bool focusNextPrevChild (bool next)
Reimplemented Function
void initStyleOption (QStyleOptionSpinBox *option) const
Initialize option with the values from this QDataTimeEdit.
virtual void keyPressEvent (QKeyEvent *event)
Reimplemented Function
virtual void mousePressEvent (QMouseEvent *event)
Reimplemented Function
virtual void paintEvent (QPaintEvent *event)
Reimplemented Function
QDateTimeEdit (const QVariant &val, QVariant::Type parserType, QWidget *parent=0)
virtual StepEnabled stepEnabled () const
Reimplemented Function
virtual QString textFromDateTime (const QDateTime &dt) const
This virtual function is used by the date time edit whenever it needs to display dateTime.
virtual QValidator::State validate (QString &input, int &pos) const
Reimplemented Function
virtual void wheelEvent (QWheelEvent *event)
Reimplemented Function
Protected Functions inherited from QAbstractSpinBox
void changeEvent (QEvent *event)
Reimplemented Function
void closeEvent (QCloseEvent *event)
Reimplemented Function
void contextMenuEvent (QContextMenuEvent *event)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
Reimplemented Function
void hideEvent (QHideEvent *event)
Reimplemented Function
void initStyleOption (QStyleOptionSpinBox *option) const
Initialize option with the values from this QSpinBox.
void keyReleaseEvent (QKeyEvent *event)
Reimplemented Function
QLineEdit * lineEdit () const
This function returns a pointer to the line edit of the spin box.
void mouseMoveEvent (QMouseEvent *event)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *event)
Reimplemented Function
QAbstractSpinBox (QAbstractSpinBoxPrivate &dd, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
Reimplemented Function
void setLineEdit (QLineEdit *edit)
Sets the line edit of the spinbox to be lineEdit instead of the current line edit widget.
void showEvent (QShowEvent *event)
Reimplemented Function
void timerEvent (QTimerEvent *event)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool calendarPopup
the current calendar pop-up showing mode.
Section currentSection
the current section of the spinbox
int currentSectionIndex
the current section index of the spinbox
QDate date
the QDate that is set in the widget
QDateTime dateTime
the QDateTime that is set in the QDateTimeEdit
Sections displayedSections
the currently displayed fields of the date time edit
QString displayFormat
the format used to display the time/date of the date time edit
QDate maximumDate
the maximum date of the date time edit
QDateTime maximumDateTime
the maximum datetime of the date time edit
QTime maximumTime
the maximum time of the date time edit
QDate minimumDate
the minimum date of the date time edit
QDateTime minimumDateTime
the minimum datetime of the date time edit
QTime minimumTime
the minimum time of the date time edit
int sectionCount
the number of sections displayed.
QTime time
the QTime that is set in the widget
Qt::TimeSpec timeSpec
the current timespec used by the date time edit.
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QDateTimeEdit class provides a widget for editing dates and times.
QDateTimeEdit allows the user to edit dates by using the keyboard or the arrow keys to increase and decrease date and time values. The arrow keys can be used to move from section to section within the QDateTimeEdit box. Dates and times appear in accordance with the format set; see setDisplayFormat().
QDateTimeEdit *dateEdit = new QDateTimeEdit(QDate::currentDate());
dateEdit->setMinimumDate(QDate::currentDate().addDays(-365));
dateEdit->setMaximumDate(QDate::currentDate().addDays(365));
dateEdit->setDisplayFormat("yyyy.MM.dd");
Here we've created a new QDateTimeEdit object initialized with today's date, and restricted the valid date range to today plus or minus 365 days. We've set the order to month, day, year.
The minimum value for QDateTimeEdit is 14 September 1752, and 2 January 4713BC for QDate. You can change this by calling setMinimumDate(), setMaximumDate(), setMinimumTime(), and setMaximumTime().
Using a Pop-up Calendar Widget
QDateTimeEdit can be configured to allow a QCalendarWidget to be used to select dates. This is enabled by setting the calendarPopup property. Additionally, you can supply a custom calendar widget for use as the calendar pop-up by calling the setCalendarWidget() function. The existing calendar widget can be retrieved with calendarWidget().
Screenshot of a Windows XP style date time editing widget
A date time editing widget shown in the Windows XP Style Widget Gallery{Windows XP widget style}.
Screenshot of a Macintosh style date time editing widget
A date time editing widget shown in the Macintosh Style Widget Gallery{Macintosh widget style}.
Screenshot of a Plastique style date time editing widget
A date time editing widget shown in the Plastique Style Widget Gallery{Plastique widget style}.
See also
QDateEdit, QTimeEdit, QDate, QTime
Definition at line 61 of file qdatetimeedit.h.
Enumerations
Section
enum QDateTimeEdit::Section
NoSection
AmPmSection
MSecSection
SecondSection
MinuteSection
HourSection
DaySection
MonthSection
YearSection
DateSections_Mask
TimeSections_Mask
Enumerator
NoSection
AmPmSection
MSecSection
SecondSection
MinuteSection
HourSection
DaySection
MonthSection
YearSection
TimeSections_Mask
DateSections_Mask
Definition at line 84 of file qdatetimeedit.h.
                  {
         NoSection = 0x0000,
         AmPmSection = 0x0001,
         MSecSection = 0x0002,
         SecondSection = 0x0004,
         MinuteSection = 0x0008,
         HourSection   = 0x0010,
         DaySection    = 0x0100,
         MonthSection  = 0x0200,
         YearSection   = 0x0400,
         TimeSections_Mask = AmPmSection|MSecSection|SecondSection|MinuteSection|HourSection,
         DateSections_Mask = DaySection|MonthSection|YearSection
     };
Constructors and Destructors
QDateTimeEdit() [1/5]
QDateTimeEdit::QDateTimeEdit (QWidget * parent = 0) explicit
Constructs an empty date time editor with a parent.
Definition at line 171 of file qdatetimeedit.cpp.
     : QAbstractSpinBox(*new QDateTimeEditPrivate, parent)
 {
     Q_D(QDateTimeEdit);
     d->init(QDateTime(QDATETIMEEDIT_DATE_INITIAL, QDATETIMEEDIT_TIME_MIN));
 }
QDateTimeEdit() [2/5]
QDateTimeEdit::QDateTimeEdit (const QDateTime & datetime, QWidget * parent = 0) explicit
Constructs an empty date time editor with a parent.
The value is set to datetime.
Definition at line 183 of file qdatetimeedit.cpp.
     : QAbstractSpinBox(*new QDateTimeEditPrivate, parent)
 {
     Q_D(QDateTimeEdit);
     d->init(datetime.isValid() ? datetime : QDateTime(QDATETIMEEDIT_DATE_INITIAL,
                                                       QDATETIMEEDIT_TIME_MIN));
 }
QDateTimeEdit() [3/5]
QDateTimeEdit::QDateTimeEdit (const QDate & date, QWidget * parent = 0) explicit
Constructs an empty date time editor with a parent.
The value is set to date.
Definition at line 198 of file qdatetimeedit.cpp.
     : QAbstractSpinBox(*new QDateTimeEditPrivate, parent)
 {
     Q_D(QDateTimeEdit);
     d->init(date.isValid() ? date : QDATETIMEEDIT_DATE_INITIAL);
 }
QDateTimeEdit() [4/5]
QDateTimeEdit::QDateTimeEdit (const QTime & time, QWidget * parent = 0) explicit
Constructs an empty date time editor with a parent.
The value is set to time.
Definition at line 212 of file qdatetimeedit.cpp.
     : QAbstractSpinBox(*new QDateTimeEditPrivate, parent)
 {
     Q_D(QDateTimeEdit);
     d->init(time.isValid() ? time : QDATETIMEEDIT_TIME_MIN);
 }
QDateTimeEdit() [5/5]
QDateTimeEdit::QDateTimeEdit (const QVariant & var, QVariant::Type parserType, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 223 of file qdatetimeedit.cpp.
     : QAbstractSpinBox(*new QDateTimeEditPrivate, parent)
 {
     Q_D(QDateTimeEdit);
     d->parserType = parserType;
     d->init(var);
 }
Functions
calendarPopup()
bool QDateTimeEdit::calendarPopup () const
Referenced by setDisplayFormat().
calendarWidget()
QCalendarWidget * QDateTimeEdit::calendarWidget () const
Returns the calendar widget for the editor if calendarPopup is set to true and (sections() & DateSections_Mask) != 0.
Since
4.4
This function creates and returns a calendar widget if none has been set.
Definition at line 797 of file qdatetimeedit.cpp.
 {
     Q_D(const QDateTimeEdit);
     if (!d->calendarPopup || !(d->sections & QDateTimeParser::DateSectionMask))
         return 0;
     if (!d->monthCalendar) {
         const_cast<QDateTimeEditPrivate*>(d)->initCalendarPopup();
     }
     return d->monthCalendar->calendarWidget();
 }
clear()
void QDateTimeEdit::clear () virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 1128 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
     d->clearSection(d->currentSectionIndex);
 }
clearMaximumDate()
void QDateTimeEdit::clearMaximumDate ()
Definition at line 520 of file qdatetimeedit.cpp.
 {
     setMaximumDate(QDATETIMEEDIT_DATE_MAX);
 }
clearMaximumDateTime()
void QDateTimeEdit::clearMaximumDateTime ()
Definition at line 406 of file qdatetimeedit.cpp.
 {
     setMaximumDateTime(QDATETIMEEDIT_DATETIME_MAX);
 }
clearMaximumTime()
void QDateTimeEdit::clearMaximumTime ()
Definition at line 593 of file qdatetimeedit.cpp.
 {
     setMaximumTime(QDATETIMEEDIT_TIME_MAX);
 }
clearMinimumDate()
void QDateTimeEdit::clearMinimumDate ()
Definition at line 484 of file qdatetimeedit.cpp.
 {
     setMinimumDate(QDATETIMEEDIT_COMPAT_DATE_MIN);
 }
clearMinimumDateTime()
void QDateTimeEdit::clearMinimumDateTime ()
Definition at line 360 of file qdatetimeedit.cpp.
 {
     setMinimumDateTime(QDateTime(QDATETIMEEDIT_COMPAT_DATE_MIN, QDATETIMEEDIT_TIME_MIN));
 }
clearMinimumTime()
void QDateTimeEdit::clearMinimumTime ()
Definition at line 557 of file qdatetimeedit.cpp.
 {
     setMinimumTime(QDATETIMEEDIT_TIME_MIN);
 }
currentSection()
Section QDateTimeEdit::currentSection () const
Referenced by setSelectedSection(), and setTimeRange().
currentSectionIndex()
int QDateTimeEdit::currentSectionIndex () const
Referenced by sectionAt().
date()
QDate QDateTimeEdit::date () const
Referenced by QDateTimeEdit(), and setDateTime().
dateChanged
void QDateTimeEdit::dateChanged (const QDate & date) signal
This signal is emitted whenever the date is changed.
The new date is passed in date.
dateTime()
QDateTime QDateTimeEdit::dateTime () const
Referenced by QDateTimeEdit(), and stepBy().
dateTimeChanged
void QDateTimeEdit::dateTimeChanged (const QDateTime & datetime) signal
This signal is emitted whenever the date or time is changed.
The new date and time is passed in datetime.
dateTimeFromText()
QDateTime QDateTimeEdit::dateTimeFromText (const QString & text) const protected virtual
Returns an appropriate datetime for the given text.
This virtual function is used by the datetime edit whenever it needs to interpret text entered by the user as a value.
See also
textFromDateTime(), validate()
Definition at line 1455 of file qdatetimeedit.cpp.
 {
     Q_D(const QDateTimeEdit);
     QString copy = text;
     int pos = d->edit->cursorPosition();
     QValidator::State state = QValidator::Acceptable;
     return d->validateAndInterpret(copy, pos, state);
 }
displayedSections()
Sections QDateTimeEdit::displayedSections () const
Referenced by setTimeRange(), and stepBy().
displayFormat()
QString QDateTimeEdit::displayFormat () const
Referenced by sectionText().
event()
bool QDateTimeEdit::event (QEvent * event) virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 1098 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
     switch (event->type()) {
     case QEvent::ApplicationLayoutDirectionChange: {
         const bool was = d->formatExplicitlySet;
         const QString oldFormat = d->displayFormat;
         d->displayFormat.clear();
         setDisplayFormat(oldFormat);
         d->formatExplicitlySet = was;
         break; }
     case QEvent::LocaleChange:
         d->updateEdit();
         break;
     case QEvent::StyleChange:
 #ifdef Q_WS_MAC
     case QEvent::MacSizeChange:
 #endif
         d->setLayoutItemMargins(QStyle::SE_DateTimeEditLayoutItem);
         break;
     default:
         break;
     }
     return QAbstractSpinBox::event(event);
 }
fixup()
void QDateTimeEdit::fixup (QString & input) const protected virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 1481 of file qdatetimeedit.cpp.
 {
     Q_D(const QDateTimeEdit);
     QValidator::State state;
     int copy = d->edit->cursorPosition();
     d->validateAndInterpret(input, copy, state, true);
 }
focusInEvent()
void QDateTimeEdit::focusInEvent (QFocusEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 1300 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
     QAbstractSpinBox::focusInEvent(event);
     QString *frm = 0;
     const int oldPos = d->edit->cursorPosition();
     if (!d->formatExplicitlySet) {
         if (d->displayFormat == d->defaultTimeFormat) {
             frm = &d->defaultTimeFormat;
         } else if (d->displayFormat == d->defaultDateFormat) {
             frm = &d->defaultDateFormat;
         } else if (d->displayFormat == d->defaultDateTimeFormat) {
             frm = &d->defaultDateTimeFormat;
         }
         if (frm) {
             d->readLocaleSettings();
             if (d->displayFormat != *frm) {
                 setDisplayFormat(*frm);
                 d->formatExplicitlySet = false;
                 d->edit->setCursorPosition(oldPos);
             }
         }
     }
     const bool oldHasHadFocus = d->hasHadFocus;
     d->hasHadFocus = true;
     bool first = true;
     switch (event->reason()) {
     case Qt::BacktabFocusReason:
         first = false;
         break;
     case Qt::MouseFocusReason:
     case Qt::PopupFocusReason:
         return;
     case Qt::ActiveWindowFocusReason:
         if (oldHasHadFocus)
             return;
     case Qt::ShortcutFocusReason:
     case Qt::TabFocusReason:
     default:
         break;
     }
     if (isRightToLeft())
         first = !first;
     d->updateEdit(); // needed to make it update specialValueText
     d->setSelected(first ? 0 : d->sectionNodes.size() - 1);
 }
focusNextPrevChild()
bool QDateTimeEdit::focusNextPrevChild (bool next) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1353 of file qdatetimeedit.cpp.
Referenced by keyPressEvent().
 {
     Q_D(QDateTimeEdit);
     const int newSection = d->nextPrevSection(d->currentSectionIndex, next);
     switch (d->sectionType(newSection)) {
     case QDateTimeParser::NoSection:
     case QDateTimeParser::FirstSection:
     case QDateTimeParser::LastSection:
         return QAbstractSpinBox::focusNextPrevChild(next);
     default:
         d->edit->deselect();
         d->edit->setCursorPosition(d->sectionPos(newSection));
         QDTEDEBUG << d->sectionPos(newSection);
         d->setSelected(newSection, true);
         return false;
     }
 }
initStyleOption()
void QDateTimeEdit::initStyleOption (QStyleOptionSpinBox * option) const protected
Initialize option with the values from this QDataTimeEdit.
This method is useful for subclasses when they need a QStyleOptionSpinBox, but don't want to fill in all the information themselves.
See also
QStyleOption::initFrom()
Definition at line 2441 of file qdatetimeedit.cpp.
Referenced by sizeHint().
 {
     if (!option)
         return;
     Q_D(const QDateTimeEdit);
     QAbstractSpinBox::initStyleOption(option);
     if (d->calendarPopupEnabled()) {
         option->subControls = QStyle::SC_ComboBoxFrame | QStyle::SC_ComboBoxEditField
                               | QStyle::SC_ComboBoxArrow;
         if (d->arrowState == QStyle::State_Sunken)
             option->state |= QStyle::State_Sunken;
         else
             option->state &= ~QStyle::State_Sunken;
     }
 }
keyPressEvent()
void QDateTimeEdit::keyPressEvent (QKeyEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 1137 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
     int oldCurrent = d->currentSectionIndex;
     bool select = true;
     bool inserted = false;
     switch (event->key()) {
 #ifdef QT_KEYPAD_NAVIGATION
     case Qt::Key_NumberSign:    //shortcut to popup calendar
         if (QApplication::keypadNavigationEnabled() && d->calendarPopupEnabled()) {
             d->initCalendarPopup();
             d->positionCalendarPopup();
             d->monthCalendar->show();
             return;
         }
         break;
     case Qt::Key_Select:
         if (QApplication::keypadNavigationEnabled()) {
             if (hasEditFocus()) {
                 if (d->focusOnButton) {
                     d->initCalendarPopup();
                     d->positionCalendarPopup();
                     d->monthCalendar->show();
                     d->focusOnButton = false;
                     return;
                 }
                 setEditFocus(false);
                 selectAll();
             } else {
                 setEditFocus(true);
                 //hide cursor
                 d->edit->d_func()->setCursorVisible(false);
                 d->edit->d_func()->control->setCursorBlinkPeriod(0);
                 d->setSelected(0);
             }
         }
         return;
 #endif
     case Qt::Key_Enter:
     case Qt::Key_Return:
         d->interpret(AlwaysEmit);
         d->setSelected(d->currentSectionIndex, true);
         event->ignore();
         emit editingFinished();
         return;
     default:
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled() && !hasEditFocus()
             && !event->text().isEmpty() && event->text().at(0).isLetterOrNumber()) {
             setEditFocus(true);
             //hide cursor
             d->edit->d_func()->setCursorVisible(false);
             d->edit->d_func()->control->setCursorBlinkPeriod(0);
             d->setSelected(0);
             oldCurrent = 0;
         }
 #endif
         if (!d->isSeparatorKey(event)) {
             inserted = select = !event->text().isEmpty() && event->text().at(0).isPrint()
                        && !(event->modifiers() & ~(Qt::ShiftModifier|Qt::KeypadModifier));
             break;
         }
     case Qt::Key_Left:
     case Qt::Key_Right:
         if (event->key() == Qt::Key_Left || event->key() == Qt::Key_Right) {
             if (
 #ifdef QT_KEYPAD_NAVIGATION
                 QApplication::keypadNavigationEnabled() && !hasEditFocus()
                 || !QApplication::keypadNavigationEnabled() &&
 #endif
                 !(event->modifiers() & Qt::ControlModifier)) {
                 select = false;
                 break;
             }
 #ifdef Q_WS_MAC
             else
 #ifdef QT_KEYPAD_NAVIGATION
                 if (!QApplication::keypadNavigationEnabled())
 #endif
             {
                 select = (event->modifiers() & Qt::ShiftModifier);
                 break;
             }
 #endif
         }
         // else fall through
     case Qt::Key_Backtab:
     case Qt::Key_Tab: {
         event->accept();
         if (d->specialValue()) {
             d->edit->setSelection(d->edit->cursorPosition(), 0);
             return;
         }
         const bool forward = event->key() != Qt::Key_Left && event->key() != Qt::Key_Backtab
                              && (event->key() != Qt::Key_Tab || !(event->modifiers() & Qt::ShiftModifier));
 #ifdef QT_KEYPAD_NAVIGATION
         int newSection = d->nextPrevSection(d->currentSectionIndex, forward);
         if (QApplication::keypadNavigationEnabled()) {
             if (d->focusOnButton) {
                 newSection = forward ? 0 : d->sectionNodes.size() - 1;
                 d->focusOnButton = false;
                 update();
             } else if (newSection < 0 && select && d->calendarPopupEnabled()) {
                 setSelectedSection(NoSection);
                 d->focusOnButton = true;
                 update();
                 return;
             }
         }
         // only allow date/time sections to be selected.
         if (newSection & ~(QDateTimeParser::TimeSectionMask | QDateTimeParser::DateSectionMask))
             return;
 #endif
         //key tab and backtab will be managed thrgout QWidget::event
         if (event->key() != Qt::Key_Backtab && event->key() != Qt::Key_Tab)
             focusNextPrevChild(forward);
         return; }
     }
     QAbstractSpinBox::keyPressEvent(event);
     if (select && !d->edit->hasSelectedText()) {
         if (inserted && d->sectionAt(d->edit->cursorPosition()) == QDateTimeParser::NoSectionIndex) {
             QString str = d->displayText();
             int pos = d->edit->cursorPosition();
             if (validate(str, pos) == QValidator::Acceptable
                 && (d->sectionNodes.at(oldCurrent).count != 1
                     || d->sectionMaxSize(oldCurrent) == d->sectionSize(oldCurrent)
                     || d->skipToNextSection(oldCurrent, d->value.toDateTime(), d->sectionText(oldCurrent)))) {
                 QDTEDEBUG << "Setting currentsection to"
                           << d->closestSection(d->edit->cursorPosition(), true) << event->key()
                           << oldCurrent << str;
                 const int tmp = d->closestSection(d->edit->cursorPosition(), true);
                 if (tmp >= 0)
                     d->currentSectionIndex = tmp;
             }
         }
         if (d->currentSectionIndex != oldCurrent) {
             d->setSelected(d->currentSectionIndex);
         }
     }
     if (d->specialValue()) {
         d->edit->setSelection(d->edit->cursorPosition(), 0);
     }
 }
maximumDate()
QDate QDateTimeEdit::maximumDate () const
Referenced by clearMinimumDate().
maximumDateTime()
QDateTime QDateTimeEdit::maximumDateTime () const
Referenced by setMinimumDateTime().
maximumTime()
QTime QDateTimeEdit::maximumTime () const
Referenced by clearMinimumTime(), and stepBy().
minimumDate()
QDate QDateTimeEdit::minimumDate () const
Referenced by setDateTimeRange().
minimumDateTime()
QDateTime QDateTimeEdit::minimumDateTime () const
Referenced by setTime().
minimumTime()
QTime QDateTimeEdit::minimumTime () const
Referenced by clearMaximumDate(), and stepBy().
mousePressEvent()
void QDateTimeEdit::mousePressEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 1562 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
     if (!d->calendarPopupEnabled()) {
         QAbstractSpinBox::mousePressEvent(event);
         return;
     }
     d->updateHoverControl(event->pos());
     if (d->hoverControl == QStyle::SC_ComboBoxArrow) {
         event->accept();
         if (d->readOnly) {
             return;
         }
         d->updateArrow(QStyle::State_Sunken);
         d->initCalendarPopup();
         d->positionCalendarPopup();
         //Show the calendar
         d->monthCalendar->show();
     } else {
         QAbstractSpinBox::mousePressEvent(event);
     }
 }
paintEvent()
void QDateTimeEdit::paintEvent (QPaintEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 2361 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
     if (!d->calendarPopupEnabled()) {
         QAbstractSpinBox::paintEvent(event);
         return;
     }
     QStyleOptionSpinBox opt;
     initStyleOption(&opt);
     QStyleOptionComboBox optCombo;
     optCombo.init(this);
     optCombo.editable = true;
     optCombo.frame = opt.frame;
     optCombo.subControls = opt.subControls;
     optCombo.activeSubControls = opt.activeSubControls;
     optCombo.state = opt.state;
     if (d->readOnly) {
         optCombo.state &= ~QStyle::State_Enabled;
     }
     QPainter p(this);
     style()->drawComplexControl(QStyle::CC_ComboBox, &optCombo, &p, this);
 }
sectionAt()
QDateTimeEdit::Section QDateTimeEdit::sectionAt (int index) const
Returns the Section at index.
Since
4.3
If the format is 'yyyy/MM/dd', sectionAt(0) returns YearSection, sectionAt(1) returns MonthSection, and sectionAt(2) returns YearSection,
Definition at line 725 of file qdatetimeedit.cpp.
 {
     Q_D(const QDateTimeEdit);
     if (index < 0 || index >= d->sectionNodes.size())
         return NoSection;
     return d->convertToPublic(d->sectionType(index));
 }
sectionCount()
int QDateTimeEdit::sectionCount () const
Referenced by sectionAt().
sectionText()
QString QDateTimeEdit::sectionText (Section section) const
Returns the text from the given section.
See also
currentSection()
Definition at line 881 of file qdatetimeedit.cpp.
 {
     Q_D(const QDateTimeEdit);
     if (section == QDateTimeEdit::NoSection || !(section & d->sections)) {
         return QString();
     }
     d->updateCache(d->value, d->displayText());
     const int sectionIndex = d->absoluteIndex(section, 0);
     return d->sectionText(sectionIndex);
 }
setCalendarPopup()
void QDateTimeEdit::setCalendarPopup (bool enable)
Definition at line 998 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
     if (enable == d->calendarPopup)
         return;
     setAttribute(Qt::WA_MacShowFocusRect, !enable);
     d->calendarPopup = enable;
 #ifdef QT_KEYPAD_NAVIGATION
     if (!enable)
         d->focusOnButton = false;
 #endif
     d->updateEditFieldGeometry();
     update();
 }
setCalendarWidget()
void QDateTimeEdit::setCalendarWidget (QCalendarWidget * calendarWidget)
Sets the given calendarWidget as the widget to be used for the calendar pop-up.
Since
4.4
The editor does not automatically take ownership of the calendar widget.
Note
calendarPopup must be set to true before setting the calendar widget.
See also
calendarPopup
Definition at line 820 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
     if (!calendarWidget) {
         qWarning("QDateTimeEdit::setCalendarWidget: Cannot set a null calendar widget");
         return;
     }
     if (!d->calendarPopup) {
         qWarning("QDateTimeEdit::setCalendarWidget: calendarPopup is set to false");
         return;
     }
     if (!(d->display & QDateTimeParser::DateSectionMask)) {
         qWarning("QDateTimeEdit::setCalendarWidget: no date sections specified");
         return;
     }
     d->initCalendarPopup(calendarWidget);
 }
setCurrentSection()
void QDateTimeEdit::setCurrentSection (Section section)
Definition at line 690 of file qdatetimeedit.cpp.
Referenced by setSelectedSection().
 {
     Q_D(QDateTimeEdit);
     if (section == NoSection || !(section & d->sections))
         return;
     d->updateCache(d->value, d->displayText());
     const int size = d->sectionNodes.size();
     int index = d->currentSectionIndex + 1;
     for (int i=0; i<2; ++i) {
         while (index < size) {
             if (d->convertToPublic(d->sectionType(index)) == section) {
                 d->edit->setCursorPosition(d->sectionPos(index));
                 QDTEDEBUG << d->sectionPos(index);
                 return;
             }
             ++index;
         }
         index = 0;
     }
 }
setCurrentSectionIndex()
void QDateTimeEdit::setCurrentSectionIndex (int index)
Definition at line 776 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
     if (index < 0 || index >= d->sectionNodes.size())
         return;
     d->edit->setCursorPosition(d->sectionPos(index));
 }
setDate
void QDateTimeEdit::setDate (const QDate & date) slot
Definition at line 285 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
     if (date.isValid()) {
         if (!(d->sections & DateSections_Mask))
             setDateRange(date, date);
         d->clearCache();
         d->setValue(QDateTime(date, d->value.toTime(), d->spec), EmitIfChanged);
         d->updateTimeSpec();
     }
 }
setDateRange()
void QDateTimeEdit::setDateRange (const QDate & min, const QDate & max)
Convenience function to set minimum and maximum date with one function call.
setDateRange(min, max);
is analogous to:
setMinimumDate(min);
setMaximumDate(max);
If either min or max are not valid, this function does nothing.
See also
setMinimumDate(), maximumDate(), setMaximumDate(), clearMinimumDate(), setMinimumTime(), maximumTime(), setMaximumTime(), clearMinimumTime(), QDate::isValid()
Definition at line 616 of file qdatetimeedit.cpp.
Referenced by setDate(), setDateTime(), and setDisplayFormat().
 {
     Q_D(QDateTimeEdit);
     if (min.isValid() && max.isValid()) {
         setDateTimeRange(QDateTime(min, d->minimum.toTime(), d->spec),
                          QDateTime(max, d->maximum.toTime(), d->spec));
     }
 }
setDateTime
void QDateTimeEdit::setDateTime (const QDateTime & dateTime) slot
Definition at line 253 of file qdatetimeedit.cpp.
Referenced by stepBy().
 {
     Q_D(QDateTimeEdit);
     if (datetime.isValid()) {
         d->clearCache();
         if (!(d->sections & DateSections_Mask))
             setDateRange(datetime.date(), datetime.date());
         d->setValue(QDateTime(datetime.date(), datetime.time(), d->spec), EmitIfChanged);
     }
 }
setDateTimeRange()
void QDateTimeEdit::setDateTimeRange (const QDateTime & min, const QDateTime & max)
Convenience function to set minimum and maximum date time with one function call.
Since
4.4
setDateTimeRange(min, max);
is analogous to:
setMinimumDateTime(min);
setMaximumDateTime(max);
If either min or max are not valid, this function does nothing.
See also
setMinimumDate(), maximumDate(), setMaximumDate(), clearMinimumDate(), setMinimumTime(), maximumTime(), setMaximumTime(), clearMinimumTime(), QDateTime::isValid()
Definition at line 441 of file qdatetimeedit.cpp.
Referenced by setDateRange(), and setTimeRange().
 {
     Q_D(QDateTimeEdit);
     const QDateTime minimum = min.toTimeSpec(d->spec);
     QDateTime maximum = max.toTimeSpec(d->spec);
     if (min > max)
         maximum = minimum;
     d->setRange(minimum, maximum);
 }
setDisplayFormat()
void QDateTimeEdit::setDisplayFormat (const QString & format)
Definition at line 936 of file qdatetimeedit.cpp.
Referenced by event(), and focusInEvent().
 {
     Q_D(QDateTimeEdit);
     if (d->parseFormat(format)) {
         d->unreversedFormat.clear();
         if (isRightToLeft()) {
             d->unreversedFormat = format;
             d->displayFormat.clear();
             for (int i=d->sectionNodes.size() - 1; i>=0; --i) {
                 d->displayFormat += d->separators.at(i + 1);
                 d->displayFormat += d->sectionFormat(i);
             }
             d->displayFormat += d->separators.at(0);
             d->separators = reverse(d->separators);
             d->sectionNodes = reverse(d->sectionNodes);
         }
         d->formatExplicitlySet = true;
         d->sections = d->convertSections(d->display);
         d->clearCache();
         d->currentSectionIndex = qMin(d->currentSectionIndex, d->sectionNodes.size() - 1);
         const bool timeShown = (d->sections & TimeSections_Mask);
         const bool dateShown = (d->sections & DateSections_Mask);
         Q_ASSERT(dateShown || timeShown);
         if (timeShown && !dateShown) {
             QTime time = d->value.toTime();
             setDateRange(d->value.toDate(), d->value.toDate());
             if (d->minimum.toTime() >= d->maximum.toTime()) {
                 setTimeRange(QDATETIMEEDIT_TIME_MIN, QDATETIMEEDIT_TIME_MAX);
                 // if the time range became invalid during the adjustment, the time would have been reset
                 setTime(time);
             }
         } else if (dateShown && !timeShown) {
             setTimeRange(QDATETIMEEDIT_TIME_MIN, QDATETIMEEDIT_TIME_MAX);
             d->value = QDateTime(d->value.toDate(), QTime(), d->spec);
         }
         d->updateEdit();
         d->_q_editorCursorPositionChanged(-1, 0);
     }
 }
setMaximumDate()
void QDateTimeEdit::setMaximumDate (const QDate & max)
Definition at line 512 of file qdatetimeedit.cpp.
Referenced by clearMaximumDate().
 {
     Q_D(QDateTimeEdit);
     if (max.isValid()) {
         setMaximumDateTime(QDateTime(max, d->maximum.toTime(), d->spec));
     }
 }
setMaximumDateTime()
void QDateTimeEdit::setMaximumDateTime (const QDateTime & dt)
Definition at line 411 of file qdatetimeedit.cpp.
Referenced by clearMaximumDateTime(), setMaximumDate(), and setMaximumTime().
 {
     Q_D(QDateTimeEdit);
     if (dt.isValid() && dt.date() <= QDATETIMEEDIT_DATE_MAX) {
         const QDateTime m = dt.toTimeSpec(d->spec);
         const QDateTime min = d->minimum.toDateTime();
         d->setRange((min < m ? min : m), m);
     }
 }
setMaximumTime()
void QDateTimeEdit::setMaximumTime (const QTime & max)
Definition at line 584 of file qdatetimeedit.cpp.
Referenced by clearMaximumTime().
 {
     Q_D(QDateTimeEdit);
     if (max.isValid()) {
         const QDateTime m(d->maximum.toDate(), max);
         setMaximumDateTime(m);
     }
 }
setMinimumDate()
void QDateTimeEdit::setMinimumDate (const QDate & min)
Definition at line 476 of file qdatetimeedit.cpp.
Referenced by clearMinimumDate().
 {
     Q_D(QDateTimeEdit);
     if (min.isValid() && min >= QDATETIMEEDIT_DATE_MIN) {
         setMinimumDateTime(QDateTime(min, d->minimum.toTime(), d->spec));
     }
 }
setMinimumDateTime()
void QDateTimeEdit::setMinimumDateTime (const QDateTime & dt)
Definition at line 365 of file qdatetimeedit.cpp.
Referenced by clearMinimumDateTime(), setMinimumDate(), and setMinimumTime().
 {
     Q_D(QDateTimeEdit);
     if (dt.isValid() && dt.date() >= QDATETIMEEDIT_DATE_MIN) {
         const QDateTime m = dt.toTimeSpec(d->spec);
         const QDateTime max = d->maximum.toDateTime();
         d->setRange(m, (max > m ? max : m));
     }
 }
setMinimumTime()
void QDateTimeEdit::setMinimumTime (const QTime & min)
Definition at line 548 of file qdatetimeedit.cpp.
Referenced by clearMinimumTime().
 {
     Q_D(QDateTimeEdit);
     if (min.isValid()) {
         const QDateTime m(d->minimum.toDate(), min, d->spec);
         setMinimumDateTime(m);
     }
 }
setSelectedSection()
void QDateTimeEdit::setSelectedSection (Section section)
Selects section.
Since
4.2
If section doesn't exist in the currently displayed sections this function does nothing. If section is NoSection this function will unselect all text in the editor. Otherwise this function will move the cursor and the current section to the selected section.
See also
currentSection()
Definition at line 856 of file qdatetimeedit.cpp.
Referenced by keyPressEvent().
 {
     Q_D(QDateTimeEdit);
     if (section == NoSection) {
         d->edit->setSelection(d->edit->cursorPosition(), 0);
     } else if (section & d->sections) {
         if (currentSection() != section)
             setCurrentSection(section);
         d->setSelected(d->currentSectionIndex);
     }
 }
setTime
void QDateTimeEdit::setTime (const QTime & time) slot
Definition at line 319 of file qdatetimeedit.cpp.
Referenced by setDisplayFormat(), and stepBy().
 {
     Q_D(QDateTimeEdit);
     if (time.isValid()) {
         d->clearCache();
         d->setValue(QDateTime(d->value.toDate(), time, d->spec), EmitIfChanged);
     }
 }
setTimeRange()
void QDateTimeEdit::setTimeRange (const QTime & min, const QTime & max)
Convenience function to set minimum and maximum time with one function call.
setTimeRange(min, max);
is analogous to:
setMinimumTime(min);
setMaximumTime(max);
If either min or max are not valid, this function does nothing.
See also
setMinimumDate(), maximumDate(), setMaximumDate(), clearMinimumDate(), setMinimumTime(), maximumTime(), setMaximumTime(), clearMinimumTime(), QTime::isValid()
Definition at line 643 of file qdatetimeedit.cpp.
Referenced by setDisplayFormat().
 {
     Q_D(QDateTimeEdit);
     if (min.isValid() && max.isValid()) {
         setDateTimeRange(QDateTime(d->minimum.toDate(), min, d->spec),
                          QDateTime(d->maximum.toDate(), max, d->spec));
     }
 }
setTimeSpec()
void QDateTimeEdit::setTimeSpec (Qt::TimeSpec spec)
Definition at line 1028 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
     if (spec != d->spec) {
         d->spec = spec;
         d->updateTimeSpec();
     }
 }
sizeHint()
QSize QDateTimeEdit::sizeHint () const virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 1041 of file qdatetimeedit.cpp.
 {
     Q_D(const QDateTimeEdit);
     if (d->cachedSizeHint.isEmpty()) {
         ensurePolished();
         const QFontMetrics fm(fontMetrics());
         int h = d->edit->sizeHint().height();
         int w = 0;
         QString s;
         s = d->textFromValue(d->minimum) + QLatin1String("   ");
         w = qMax<int>(w, fm.width(s));
         s = d->textFromValue(d->maximum) + QLatin1String("   ");
         w = qMax<int>(w, fm.width(s));
         if (d->specialValueText.size()) {
             s = d->specialValueText;
             w = qMax<int>(w, fm.width(s));
         }
         w += 2; // cursor blinking space
         QSize hint(w, h);
 #ifdef Q_WS_MAC
         if (d->calendarPopupEnabled()) {
             QStyleOptionComboBox opt;
             d->cachedSizeHint = style()->sizeFromContents(QStyle::CT_ComboBox, &opt, hint, this);
         } else {
 #else
         {
 #endif
             QSize extra(35, 6);
             QStyleOptionSpinBox opt;
             initStyleOption(&opt);
             opt.rect.setSize(hint + extra);
             extra += hint - style()->subControlRect(QStyle::CC_SpinBox, &opt,
                                                 QStyle::SC_SpinBoxEditField, this).size();
             // get closer to final result by repeating the calculation
             opt.rect.setSize(hint + extra);
             extra += hint - style()->subControlRect(QStyle::CC_SpinBox, &opt,
                                                 QStyle::SC_SpinBoxEditField, this).size();
             hint += extra;
             opt.rect = rect();
             d->cachedSizeHint = style()->sizeFromContents(QStyle::CT_SpinBox, &opt, hint, this)
                                 .expandedTo(QApplication::globalStrut());
         }
         d->cachedMinimumSizeHint = d->cachedSizeHint;
         // essentially make minimumSizeHint return the same as sizeHint for datetimeedits
     }
     return d->cachedSizeHint;
 }
stepBy()
void QDateTimeEdit::stepBy (int steps) virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 1375 of file qdatetimeedit.cpp.
 {
     Q_D(QDateTimeEdit);
 #ifdef QT_KEYPAD_NAVIGATION
     // with keypad navigation and not editFocus, left right change the date/time by a fixed amount.
     if (QApplication::keypadNavigationEnabled() && !hasEditFocus()) {
         // if date based, shift by day.  else shift by 15min
         if (d->sections & DateSections_Mask) {
             setDateTime(dateTime().addDays(steps));
         } else {
             int minutes = time().hour()*60 + time().minute();
             int blocks = minutes/15;
             blocks += steps;
             /* rounding involved */
             if (minutes % 15) {
                 if (steps < 0) {
                     blocks += 1; // do one less step;
                 }
             }
             minutes = blocks * 15;
             /* need to take wrapping into account */
             if (!d->wrapping) {
                 int max_minutes = d->maximum.toTime().hour()*60 + d->maximum.toTime().minute();
                 int min_minutes = d->minimum.toTime().hour()*60 + d->minimum.toTime().minute();
                 if (minutes >= max_minutes) {
                     setTime(maximumTime());
                     return;
                 } else if (minutes <= min_minutes) {
                     setTime(minimumTime());
                     return;
                 }
             }
             setTime(QTime(minutes/60, minutes%60));
         }
         return;
     }
 #endif
     // don't optimize away steps == 0. This is the only way to select
     // the currentSection in Qt 4.1.x
     if (d->specialValue() && displayedSections() != AmPmSection) {
         for (int i=0; i<d->sectionNodes.size(); ++i) {
             if (d->sectionType(i) != QDateTimeParser::AmPmSection) {
                 d->currentSectionIndex = i;
                 break;
             }
         }
     }
     d->setValue(d->stepBy(d->currentSectionIndex, steps, false), EmitIfChanged);
     d->updateCache(d->value, d->displayText());
     d->setSelected(d->currentSectionIndex);
     d->updateTimeSpec();
 }
stepEnabled()
QDateTimeEdit::StepEnabled QDateTimeEdit::stepEnabled () const protected virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 1495 of file qdatetimeedit.cpp.
 {
     Q_D(const QDateTimeEdit);
     if (d->readOnly)
         return StepEnabled(0);
     if (d->specialValue()) {
         return (d->minimum == d->maximum ? StepEnabled(0) : StepEnabled(StepUpEnabled));
     }
     QAbstractSpinBox::StepEnabled ret = 0;
 #ifdef QT_KEYPAD_NAVIGATION
     if (QApplication::keypadNavigationEnabled() && !hasEditFocus()) {
         if (d->wrapping)
             return StepEnabled(StepUpEnabled | StepDownEnabled);
         // 3 cases.  date, time, datetime.  each case look
         // at just the relavant component.
         QVariant max, min, val;
         if (!(d->sections & DateSections_Mask)) {
             // time only, no date
             max = d->maximum.toTime();
             min = d->minimum.toTime();
             val = d->value.toTime();
         } else if (!(d->sections & TimeSections_Mask)) {
             // date only, no time
             max = d->maximum.toDate();
             min = d->minimum.toDate();
             val = d->value.toDate();
         } else {
             // both
             max = d->maximum;
             min = d->minimum;
             val = d->value;
         }
         if (val != min)
             ret |= QAbstractSpinBox::StepDownEnabled;
         if (val != max)
             ret |= QAbstractSpinBox::StepUpEnabled;
         return ret;
     }
 #endif
     switch (d->sectionType(d->currentSectionIndex)) {
     case QDateTimeParser::NoSection:
     case QDateTimeParser::FirstSection:
     case QDateTimeParser::LastSection: return 0;
     default: break;
     }
     if (d->wrapping)
         return StepEnabled(StepDownEnabled|StepUpEnabled);
     QVariant v = d->stepBy(d->currentSectionIndex, 1, true);
     if (v != d->value) {
         ret |= QAbstractSpinBox::StepUpEnabled;
     }
     v = d->stepBy(d->currentSectionIndex, -1, true);
     if (v != d->value) {
         ret |= QAbstractSpinBox::StepDownEnabled;
     }
     return ret;
 }
textFromDateTime()
QString QDateTimeEdit::textFromDateTime (const QDateTime & dateTime) const protected virtual
This virtual function is used by the date time edit whenever it needs to display dateTime.
If you reimplement this, you may also need to reimplement validate().
See also
dateTimeFromText(), validate()
Definition at line 1440 of file qdatetimeedit.cpp.
 {
     Q_D(const QDateTimeEdit);
     return locale().toString(dateTime, d->displayFormat);
 }
time()
QTime QDateTimeEdit::time () const
Referenced by QDateTimeEdit(), setDate(), setDisplayFormat(), setTime(), and stepBy().
timeChanged
void QDateTimeEdit::timeChanged (const QTime & time) signal
This signal is emitted whenever the time is changed.
The new time is passed in time.
timeSpec()
Qt::TimeSpec QDateTimeEdit::timeSpec () const
Referenced by setCalendarPopup().
validate()
QValidator::State QDateTimeEdit::validate (QString & input, int & pos) const protected virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 1468 of file qdatetimeedit.cpp.
Referenced by keyPressEvent().
 {
     Q_D(const QDateTimeEdit);
     QValidator::State state;
     d->validateAndInterpret(text, pos, state);
     return state;
 }
wheelEvent()
void QDateTimeEdit::wheelEvent (QWheelEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 1290 of file qdatetimeedit.cpp.
 {
     QAbstractSpinBox::wheelEvent(event);
 }
Properties
calendarPopup
bool QDateTimeEdit::calendarPopup private
the current calendar pop-up showing mode.
Since
4.2
The calendar pop-up will be shown upon clicking the arrow button. This property is valid only if there is a valid date display format.
See also
setDisplayFormat()
Definition at line 79 of file qdatetimeedit.h.
currentSection
QDateTimeEdit::Section QDateTimeEdit::currentSection private
the current section of the spinbox
setCurrentSection()
Definition at line 76 of file qdatetimeedit.h.
currentSectionIndex
int QDateTimeEdit::currentSectionIndex private
the current section index of the spinbox
Since
4.3
If the format is 'yyyy/MM/dd', the displayText is '2001/05/21' and the cursorPosition is 5 currentSectionIndex returns 1. If the cursorPosition is 3 currentSectionIndex is 0 etc.
setCurrentSection()
See also
currentSection()
Definition at line 80 of file qdatetimeedit.h.
date
QDate QDateTimeEdit::date private
the QDate that is set in the widget
Returns the date of the date time edit.
By default, this property contains a date that refers to January 1, 2000.
See also
time, dateTime
Definition at line 68 of file qdatetimeedit.h.
dateTime
QDateTime QDateTimeEdit::dateTime private
the QDateTime that is set in the QDateTimeEdit
When setting this property the timespec of the QDateTimeEdit remains the same and the timespec of the new QDateTime is ignored.
By default, this property contains a date that refers to January 1, 2000 and a time of 00:00:00 and 0 milliseconds.
See also
date, time
Definition at line 67 of file qdatetimeedit.h.
displayedSections
QDateTimeEdit::Sections QDateTimeEdit::displayedSections private
the currently displayed fields of the date time edit
Returns a bit set of the displayed sections for this format. setDisplayFormat(), displayFormat()
Definition at line 77 of file qdatetimeedit.h.
displayFormat
QString QDateTimeEdit::displayFormat private
the format used to display the time/date of the date time edit
This format is the same as the one used described in QDateTime::toString() and QDateTime::fromString()
Example format strings (assuming that the date is 2nd of July 1969):
Format Result
dd.MM.yyyy 02.07.1969
MMM d yy Jul 2 69
MMMM d yy July 2 69
Note that if you specify a two digit year, it will be interpreted to be in the century in which the date time edit was initialized. The default century is the 21 (2000-2099).
If you specify an invalid format the format will not be set.
See also
QDateTime::toString(), displayedSections()
Definition at line 78 of file qdatetimeedit.h.
maximumDate
QDate QDateTimeEdit::maximumDate private
the maximum date of the date time edit
When setting this property the minimumDate is adjusted if necessary to ensure that the range remains valid. If the date is not a valid QDate object, this function does nothing.
By default, this property contains a date that refers to December 31, 7999.
See also
minimumDate, minimumTime, maximumTime, setDateRange()
Definition at line 72 of file qdatetimeedit.h.
maximumDateTime
QDateTime QDateTimeEdit::maximumDateTime private
the maximum datetime of the date time edit
Since
4.4
When setting this property the minimumDateTime() is adjusted if necessary to ensure that the range remains valid. If the datetime is not a valid QDateTime object, this function does nothing.
The default maximumDateTime can be restored with clearMaximumDateTime().
By default, this property contains a date that refers to 31 December, 7999 and a time of 23:59:59 and 999 milliseconds.
See also
minimumDateTime(), minimumTime(), maximumTime(), minimumDate(), maximumDate(), setDateTimeRange(), setDateRange(), setTimeRange(), clearMinimumDateTime(), clearMinimumDate(), clearMaximumDate(), clearMinimumTime(), clearMaximumTime()
Definition at line 70 of file qdatetimeedit.h.
maximumTime
QTime QDateTimeEdit::maximumTime private
the maximum time of the date time edit
When setting this property, the minimumTime is adjusted if necessary to ensure that the range remains valid. If the time is not a valid QTime object, this function does nothing.
By default, this property contains a time of 23:59:59 and 999 milliseconds.
See also
minimumTime, minimumDate, maximumDate, setTimeRange()
Definition at line 74 of file qdatetimeedit.h.
minimumDate
QDate QDateTimeEdit::minimumDate private
the minimum date of the date time edit
When setting this property the maximumDate is adjusted if necessary, to ensure that the range remains valid. If the date is not a valid QDate object, this function does nothing.
By default, this property contains a date that refers to September 14, 1752. The minimum date must be at least the first day in year 100, otherwise setMinimumDate() has no effect.
See also
minimumTime(), maximumTime(), setDateRange()
Definition at line 73 of file qdatetimeedit.h.
minimumDateTime
QDateTime QDateTimeEdit::minimumDateTime private
the minimum datetime of the date time edit
Since
4.4
When setting this property the maximumDateTime() is adjusted if necessary to ensure that the range remains valid. If the datetime is not a valid QDateTime object, this function does nothing.
The default minimumDateTime can be restored with clearMinimumDateTime()
By default, this property contains a date that refers to September 14, 1752 and a time of 00:00:00 and 0 milliseconds.
See also
maximumDateTime(), minimumTime(), maximumTime(), minimumDate(), maximumDate(), setDateTimeRange(), setDateRange(), setTimeRange(), clearMaximumDateTime(), clearMinimumDate(), clearMaximumDate(), clearMinimumTime(), clearMaximumTime()
Definition at line 71 of file qdatetimeedit.h.
minimumTime
QTime QDateTimeEdit::minimumTime private
the minimum time of the date time edit
When setting this property the maximumTime is adjusted if necessary, to ensure that the range remains valid. If the time is not a valid QTime object, this function does nothing.
By default, this property contains a time of 00:00:00 and 0 milliseconds.
See also
maximumTime, minimumDate, maximumDate, setTimeRange()
Definition at line 75 of file qdatetimeedit.h.
sectionCount
int QDateTimeEdit::sectionCount private
the number of sections displayed.
If the format is 'yyyy/yy/yyyy', sectionCount returns 3
Since
4.3
Definition at line 81 of file qdatetimeedit.h.
time
QTime QDateTimeEdit::time private
the QTime that is set in the widget
Returns the time of the date time edit.
By default, this property contains a time of 00:00:00 and 0 milliseconds.
See also
date, dateTime
Definition at line 69 of file qdatetimeedit.h.
timeSpec
Qt::TimeSpec QDateTimeEdit::timeSpec private
the current timespec used by the date time edit.
Since
4.4
Definition at line 82 of file qdatetimeedit.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qdatetimeedit.h
/src/gui/widgets/qdatetimeedit.cpp