Qt 4.8: QScriptDebugger Class Reference
QScriptDebugger Class Reference
The QScriptDebugger class provides a Qt Script debugger.
#include <qscriptdebugger_p.h>
Public Types
enum DebuggerAction {
InterruptAction, ContinueAction, StepIntoAction, StepOverAction,
StepOutAction, RunToCursorAction, RunToNewScriptAction, ToggleBreakpointAction,
ClearDebugOutputAction, ClearErrorLogAction, ClearConsoleAction, FindInScriptAction,
FindNextInScriptAction, FindPreviousInScriptAction, GoToLineAction
}
enum DebuggerWidget {
ConsoleWidget, StackWidget, ScriptsWidget, LocalsWidget,
CodeWidget, CodeFinderWidget, BreakpointsWidget, DebugOutputWidget,
ErrorLogWidget
}
Signals
void started () const
void stopped () const
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QAction * action (DebuggerAction action, QObject *parent)
QScriptBreakpointsWidgetInterface * breakpointsWidget () const
QAction * clearConsoleAction (QObject *parent) const
QAction * clearDebugOutputAction (QObject *parent) const
QAction * clearErrorLogAction (QObject *parent) const
QScriptDebuggerCodeFinderWidgetInterface * codeFinderWidget () const
QScriptDebuggerCodeWidgetInterface * codeWidget () const
QScriptDebuggerConsoleWidgetInterface * consoleWidget () const
QAction * continueAction (QObject *parent) const
QMenu * createStandardMenu (QWidget *widgetParent, QObject *actionParent)
QToolBar * createStandardToolBar (QWidget *widgetParent, QObject *actionParent)
QScriptDebugOutputWidgetInterface * debugOutputWidget () const
QScriptErrorLogWidgetInterface * errorLogWidget () const
bool eventFilter (QObject *, QEvent *e)
Reimplemented Function
QAction * findInScriptAction (QObject *parent) const
QAction * findNextInScriptAction (QObject *parent) const
QAction * findPreviousInScriptAction (QObject *parent) const
QScriptDebuggerFrontend * frontend () const
QAction * goToLineAction (QObject *parent) const
QAction * interruptAction (QObject *parent) const
bool isInteractive () const
QScriptDebuggerLocalsWidgetInterface * localsWidget () const
QScriptDebugger (QObject *parent=0)
Constructs a new QScriptDebugger object.
QAction * runToCursorAction (QObject *parent) const
QAction * runToNewScriptAction (QObject *parent) const
QScriptDebuggerScriptsWidgetInterface * scriptsWidget () const
void setBreakpointsWidget (QScriptBreakpointsWidgetInterface *breakpointsWidget)
void setCodeFinderWidget (QScriptDebuggerCodeFinderWidgetInterface *codeFinderWidget)
void setCodeWidget (QScriptDebuggerCodeWidgetInterface *codeWidget)
void setConsoleWidget (QScriptDebuggerConsoleWidgetInterface *consoleWidget)
void setDebugOutputWidget (QScriptDebugOutputWidgetInterface *debugOutputWidget)
void setErrorLogWidget (QScriptErrorLogWidgetInterface *errorLogWidget)
void setFrontend (QScriptDebuggerFrontend *frontend)
void setLocalsWidget (QScriptDebuggerLocalsWidgetInterface *localsWidget)
void setScriptsWidget (QScriptDebuggerScriptsWidgetInterface *scriptsWidget)
void setStackWidget (QScriptDebuggerStackWidgetInterface *stackWidget)
void setWidgetFactory (QScriptDebuggerWidgetFactoryInterface *factory)
QScriptDebuggerStackWidgetInterface * stackWidget () const
QAction * stepIntoAction (QObject *parent) const
QAction * stepOutAction (QObject *parent) const
QAction * stepOverAction (QObject *parent) const
QAction * toggleBreakpointAction (QObject *parent) const
QWidget * widget (DebuggerWidget widget)
QScriptDebuggerWidgetFactoryInterface * widgetFactory () const
~QScriptDebugger ()
Destroys this QScriptDebugger.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QScriptDebugger (QScriptDebuggerPrivate &dd, QObject *parent)
void timerEvent (QTimerEvent *e)
Reimplemented Function
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QScriptDebugger class provides a Qt Script debugger.
Since
4.5
Warning
This function is not part of the public interface.
Definition at line 79 of file qscriptdebugger_p.h.
Enumerations
DebuggerAction
enum QScriptDebugger::DebuggerAction
Enumerator
InterruptAction
ContinueAction
StepIntoAction
StepOverAction
StepOutAction
RunToCursorAction
RunToNewScriptAction
ToggleBreakpointAction
ClearDebugOutputAction
ClearErrorLogAction
ClearConsoleAction
FindInScriptAction
FindNextInScriptAction
FindPreviousInScriptAction
GoToLineAction
Definition at line 96 of file qscriptdebugger_p.h.
{
         InterruptAction,
         ContinueAction,
         StepIntoAction,
         StepOverAction,
         StepOutAction,
         RunToCursorAction,
         RunToNewScriptAction,
         ToggleBreakpointAction,
         ClearDebugOutputAction,
         ClearErrorLogAction,
         ClearConsoleAction,
         FindInScriptAction,
         FindNextInScriptAction,
         FindPreviousInScriptAction,
         GoToLineAction
     };
DebuggerWidget
enum QScriptDebugger::DebuggerWidget
Enumerator
ConsoleWidget
StackWidget
ScriptsWidget
LocalsWidget
CodeWidget
CodeFinderWidget
BreakpointsWidget
DebugOutputWidget
ErrorLogWidget
Definition at line 84 of file qscriptdebugger_p.h.
{
         ConsoleWidget,
         StackWidget,
         ScriptsWidget,
         LocalsWidget,
         CodeWidget,
         CodeFinderWidget,
         BreakpointsWidget,
         DebugOutputWidget,
         ErrorLogWidget
     };
Constructors and Destructors
QScriptDebugger() [1/2]
QScriptDebugger::QScriptDebugger (QObject * parent = 0)
Constructs a new QScriptDebugger object.
Definition at line 1298 of file qscriptdebugger.cpp.
     : QObject(*new QScriptDebuggerPrivate, parent)
 {
     ++scriptDebuggerCount;
 }
~QScriptDebugger()
QScriptDebugger::~QScriptDebugger ()
Destroys this QScriptDebugger.
Definition at line 1307 of file qscriptdebugger.cpp.
 {
     --scriptDebuggerCount;
     if ((scriptDebuggerCount == 0) && eventCallbackRegistered) {
         eventCallbackRegistered = false;
         QInternal::unregisterCallback(QInternal::EventNotifyCallback,
                                       scriptDebuggerEventCallback);
     }
 }
QScriptDebugger() [2/2]
QScriptDebugger::QScriptDebugger (QScriptDebuggerPrivate & dd, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 1320 of file qscriptdebugger.cpp.
     : QObject(dd, parent)
 {
 }
Functions
action()
QAction * QScriptDebugger::action (DebuggerAction action, QObject * parent)
Definition at line 1347 of file qscriptdebugger.cpp.
Referenced by createStandardMenu(), and createStandardToolBar().
 {
     switch (action) {
     case InterruptAction:
         return interruptAction(parent);
     case ContinueAction:
         return continueAction(parent);
     case StepIntoAction:
         return stepIntoAction(parent);
     case StepOverAction:
         return stepOverAction(parent);
     case StepOutAction:
         return stepOutAction(parent);
     case RunToCursorAction:
         return runToCursorAction(parent);
     case RunToNewScriptAction:
         return runToNewScriptAction(parent);
     case ToggleBreakpointAction:
         return toggleBreakpointAction(parent);
     case ClearDebugOutputAction:
         return clearDebugOutputAction(parent);
     case ClearErrorLogAction:
         return clearErrorLogAction(parent);
     case ClearConsoleAction:
         return clearConsoleAction(parent);
     case FindInScriptAction:
         return findInScriptAction(parent);
     case FindNextInScriptAction:
         return findNextInScriptAction(parent);
     case FindPreviousInScriptAction:
         return findPreviousInScriptAction(parent);
     case GoToLineAction:
         return goToLineAction(parent);
     }
     return 0;
 }
breakpointsWidget()
QScriptBreakpointsWidgetInterface * QScriptDebugger::breakpointsWidget () const
Definition at line 1629 of file qscriptdebugger.cpp.
Referenced by setBreakpointsWidget(), and widget().
 {
     Q_D(const QScriptDebugger);
     return d->breakpointsWidget;
 }
clearConsoleAction()
QAction * QScriptDebugger::clearConsoleAction (QObject * parent) const
Definition at line 1838 of file qscriptdebugger.cpp.
Referenced by action(), and clearConsoleAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->clearConsoleAction) {
         QIcon clearConsoleIcon;
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->clearConsoleAction = new QAction(clearConsoleIcon, QScriptDebugger::tr("Clear Console"), parent);
         QObject::connect(d->clearConsoleAction, SIGNAL(triggered()),
                          that, SLOT(_q_clearConsole()));
     }
     return d->clearConsoleAction;
 }
clearDebugOutputAction()
QAction * QScriptDebugger::clearDebugOutputAction (QObject * parent) const
Definition at line 1812 of file qscriptdebugger.cpp.
Referenced by action(), and clearDebugOutputAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->clearDebugOutputAction) {
         QIcon clearDebugOutputIcon;
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->clearDebugOutputAction = new QAction(clearDebugOutputIcon, QScriptDebugger::tr("Clear Debug Output"), parent);
         QObject::connect(d->clearDebugOutputAction, SIGNAL(triggered()),
                          that, SLOT(_q_clearDebugOutput()));
     }
     return d->clearDebugOutputAction;
 }
clearErrorLogAction()
QAction * QScriptDebugger::clearErrorLogAction (QObject * parent) const
Definition at line 1825 of file qscriptdebugger.cpp.
Referenced by action(), and clearErrorLogAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->clearErrorLogAction) {
         QIcon clearErrorLogIcon;
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->clearErrorLogAction = new QAction(clearErrorLogIcon, QScriptDebugger::tr("Clear Error Log"), parent);
         QObject::connect(d->clearErrorLogAction, SIGNAL(triggered()),
                          that, SLOT(_q_clearErrorLog()));
     }
     return d->clearErrorLogAction;
 }
codeFinderWidget()
QScriptDebuggerCodeFinderWidgetInterface * QScriptDebugger::codeFinderWidget () const
Definition at line 1592 of file qscriptdebugger.cpp.
Referenced by setCodeFinderWidget(), and widget().
 {
     Q_D(const QScriptDebugger);
     return d->codeFinderWidget;
 }
codeWidget()
QScriptDebuggerCodeWidgetInterface * QScriptDebugger::codeWidget () const
Definition at line 1554 of file qscriptdebugger.cpp.
Referenced by setCodeWidget(), and widget().
 {
     Q_D(const QScriptDebugger);
     return d->codeWidget;
 }
consoleWidget()
QScriptDebuggerConsoleWidgetInterface * QScriptDebugger::consoleWidget () const
Definition at line 1463 of file qscriptdebugger.cpp.
Referenced by setConsoleWidget(), and widget().
 {
     Q_D(const QScriptDebugger);
     return d->consoleWidget;
 }
continueAction()
QAction * QScriptDebugger::continueAction (QObject * parent) const
Definition at line 1694 of file qscriptdebugger.cpp.
Referenced by action(), and continueAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->continueAction) {
         QIcon continueIcon;
         continueIcon.addPixmap(d->pixmap(QString::fromLatin1("play.png")), QIcon::Normal);
         continueIcon.addPixmap(d->pixmap(QString::fromLatin1("d_play.png")), QIcon::Disabled);
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->continueAction = new QAction(continueIcon, QScriptDebugger::tr("Continue"), parent);
         d->continueAction->setEnabled(d->interactive);
         d->continueAction->setShortcut(QScriptDebugger::tr("F5"));
         QObject::connect(d->continueAction, SIGNAL(triggered()),
                          that, SLOT(_q_continue()));
     }
     return d->continueAction;
 }
createStandardMenu()
QMenu * QScriptDebugger::createStandardMenu (QWidget * widgetParent, QObject * actionParent)
Definition at line 1915 of file qscriptdebugger.cpp.
 {
     QMenu *menu = new QMenu(widgetParent);
     menu->setTitle(QScriptDebugger::tr("Debug"));
     menu->addAction(action(ContinueAction, actionParent));
     menu->addAction(action(InterruptAction, actionParent));
     menu->addAction(action(StepIntoAction, actionParent));
     menu->addAction(action(StepOverAction, actionParent));
     menu->addAction(action(StepOutAction, actionParent));
     menu->addAction(action(RunToCursorAction, actionParent));
     menu->addAction(action(RunToNewScriptAction, actionParent));
     menu->addSeparator();
     menu->addAction(action(ToggleBreakpointAction, actionParent));
     menu->addSeparator();
     menu->addAction(action(ClearDebugOutputAction, actionParent));
     menu->addAction(action(ClearErrorLogAction, actionParent));
     menu->addAction(action(ClearConsoleAction, actionParent));
     return menu;
 }
createStandardToolBar()
QToolBar * QScriptDebugger::createStandardToolBar (QWidget * widgetParent, QObject * actionParent)
Definition at line 1939 of file qscriptdebugger.cpp.
 {
     QToolBar *tb = new QToolBar(widgetParent);
     tb->setObjectName(QLatin1String("qtscriptdebugger_standardToolBar"));
     tb->addAction(action(ContinueAction, actionParent));
     tb->addAction(action(InterruptAction, actionParent));
     tb->addAction(action(StepIntoAction, actionParent));
     tb->addAction(action(StepOverAction, actionParent));
     tb->addAction(action(StepOutAction, actionParent));
     tb->addAction(action(RunToCursorAction, actionParent));
     tb->addAction(action(RunToNewScriptAction, actionParent));
     tb->addSeparator();
     tb->addAction(action(FindInScriptAction, actionParent));
     return tb;
 }
debugOutputWidget()
QScriptDebugOutputWidgetInterface * QScriptDebugger::debugOutputWidget () const
Definition at line 1617 of file qscriptdebugger.cpp.
Referenced by setDebugOutputWidget(), and widget().
 {
     Q_D(const QScriptDebugger);
     return d->debugOutputWidget;
 }
errorLogWidget()
QScriptErrorLogWidgetInterface * QScriptDebugger::errorLogWidget () const
Definition at line 1653 of file qscriptdebugger.cpp.
Referenced by setErrorLogWidget(), and widget().
 {
     Q_D(const QScriptDebugger);
     return d->errorLogWidget;
 }
eventFilter()
bool QScriptDebugger::eventFilter (QObject * watched, QEvent * e) virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 1965 of file qscriptdebugger.cpp.
 {
     Q_D(QScriptDebugger);
     if (watched == d->codeWidget) {
         if (e->type() == QEvent::KeyPress) {
             d->_q_findInScript();
             d->codeFinderWidget->setText(static_cast<QKeyEvent*>(e)->text());
             return true;
         }
     }
     return false;
 }
findInScriptAction()
QAction * QScriptDebugger::findInScriptAction (QObject * parent) const
Definition at line 1851 of file qscriptdebugger.cpp.
Referenced by action(), and findInScriptAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->findInScriptAction) {
         QIcon findInScriptIcon;
         findInScriptIcon.addPixmap(d->pixmap(QString::fromLatin1("find.png")), QIcon::Normal);
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->findInScriptAction = new QAction(findInScriptIcon, QScriptDebugger::tr("&Find in Script..."), parent);
         d->findInScriptAction->setShortcut(QScriptDebugger::tr("Ctrl+F"));
         d->findInScriptAction->setEnabled(
             (d->codeFinderWidget != 0)
             && (d->codeWidget != 0)
             && (d->codeWidget->currentView() != 0));
         QObject::connect(d->findInScriptAction, SIGNAL(triggered()),
                          that, SLOT(_q_findInScript()));
     }
     return d->findInScriptAction;
 }
findNextInScriptAction()
QAction * QScriptDebugger::findNextInScriptAction (QObject * parent) const
Definition at line 1870 of file qscriptdebugger.cpp.
Referenced by action(), and findNextInScriptAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->findNextInScriptAction) {
         QIcon findNextInScriptIcon;
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->findNextInScriptAction = new QAction(findNextInScriptIcon, QScriptDebugger::tr("Find &Next"), parent);
         d->findNextInScriptAction->setEnabled(d->codeFinderWidget && !d->codeFinderWidget->text().isEmpty());
         d->findNextInScriptAction->setShortcut(QScriptDebugger::tr("F3"));
         QObject::connect(d->findNextInScriptAction, SIGNAL(triggered()),
                          that, SLOT(_q_findNextInScript()));
     }
     return d->findNextInScriptAction;
 }
findPreviousInScriptAction()
QAction * QScriptDebugger::findPreviousInScriptAction (QObject * parent) const
Definition at line 1885 of file qscriptdebugger.cpp.
Referenced by action(), and findPreviousInScriptAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->findPreviousInScriptAction) {
         QIcon findPreviousInScriptIcon;
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->findPreviousInScriptAction = new QAction(findPreviousInScriptIcon, QScriptDebugger::tr("Find &Previous"), parent);
         d->findPreviousInScriptAction->setEnabled(d->codeFinderWidget && !d->codeFinderWidget->text().isEmpty());
         d->findPreviousInScriptAction->setShortcut(QScriptDebugger::tr("Shift+F3"));
         QObject::connect(d->findPreviousInScriptAction, SIGNAL(triggered()),
                          that, SLOT(_q_findPreviousInScript()));
     }
     return d->findPreviousInScriptAction;
 }
frontend()
QScriptDebuggerFrontend * QScriptDebugger::frontend () const
Definition at line 1325 of file qscriptdebugger.cpp.
Referenced by setFrontend().
 {
     Q_D(const QScriptDebugger);
     return d->frontend;
 }
goToLineAction()
QAction * QScriptDebugger::goToLineAction (QObject * parent) const
Definition at line 1900 of file qscriptdebugger.cpp.
Referenced by action(), and goToLineAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->goToLineAction) {
         QIcon goToLineIcon;
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->goToLineAction = new QAction(goToLineIcon, QScriptDebugger::tr("Go to Line"), parent);
         d->goToLineAction->setShortcut(QScriptDebugger::tr("Ctrl+G"));
         d->goToLineAction->setEnabled((d->codeWidget != 0) && (d->codeWidget->currentView() != 0));
         QObject::connect(d->goToLineAction, SIGNAL(triggered()),
                          that, SLOT(_q_goToLine()));
     }
     return d->goToLineAction;
 }
interruptAction()
QAction * QScriptDebugger::interruptAction (QObject * parent) const
Definition at line 1677 of file qscriptdebugger.cpp.
Referenced by action(), and interruptAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->interruptAction) {
         QIcon interruptIcon;
         interruptIcon.addPixmap(d->pixmap(QString::fromLatin1("interrupt.png")), QIcon::Normal);
         interruptIcon.addPixmap(d->pixmap(QString::fromLatin1("d_interrupt.png")), QIcon::Disabled);
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->interruptAction = new QAction(interruptIcon, QScriptDebugger::tr("Interrupt"), parent);
         d->interruptAction->setEnabled(!d->interactive);
         d->interruptAction->setShortcut(QScriptDebugger::tr("Shift+F5"));
         QObject::connect(d->interruptAction, SIGNAL(triggered()),
                          that, SLOT(_q_interrupt()));
     }
     return d->interruptAction;
 }
isInteractive()
bool QScriptDebugger::isInteractive () const
Definition at line 1956 of file qscriptdebugger.cpp.
 {
     Q_D(const QScriptDebugger);
     return d->interactive;
 }
localsWidget()
QScriptDebuggerLocalsWidgetInterface * QScriptDebugger::localsWidget () const
Definition at line 1538 of file qscriptdebugger.cpp.
Referenced by setLocalsWidget(), and widget().
 {
     Q_D(const QScriptDebugger);
     return d->localsWidget;
 }
runToCursorAction()
QAction * QScriptDebugger::runToCursorAction (QObject * parent) const
Definition at line 1762 of file qscriptdebugger.cpp.
Referenced by action(), and runToCursorAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->runToCursorAction) {
         QIcon runToCursorIcon;
         runToCursorIcon.addPixmap(d->pixmap(QString::fromLatin1("runtocursor.png")), QIcon::Normal);
         runToCursorIcon.addPixmap(d->pixmap(QString::fromLatin1("d_runtocursor.png")), QIcon::Disabled);
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->runToCursorAction = new QAction(runToCursorIcon, QScriptDebugger::tr("Run to Cursor"), parent);
         d->runToCursorAction->setEnabled(d->interactive);
         d->runToCursorAction->setShortcut(QScriptDebugger::tr("Ctrl+F10"));
         QObject::connect(d->runToCursorAction, SIGNAL(triggered()),
                          that, SLOT(_q_runToCursor()));
     }
     return d->runToCursorAction;
 }
runToNewScriptAction()
QAction * QScriptDebugger::runToNewScriptAction (QObject * parent) const
Definition at line 1779 of file qscriptdebugger.cpp.
Referenced by action(), and runToNewScriptAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->runToNewScriptAction) {
         QIcon runToNewScriptIcon;
         runToNewScriptIcon.addPixmap(d->pixmap(QString::fromLatin1("runtonewscript.png")), QIcon::Normal);
         runToNewScriptIcon.addPixmap(d->pixmap(QString::fromLatin1("d_breakonscriptload.png")), QIcon::Disabled);
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->runToNewScriptAction = new QAction(runToNewScriptIcon,
                                                            QScriptDebugger::tr("Run to New Script"), parent);
         d->runToNewScriptAction->setEnabled(d->interactive);
         QObject::connect(d->runToNewScriptAction, SIGNAL(triggered()),
                          that, SLOT(_q_runToNewScript()));
     }
     return d->runToNewScriptAction;
 }
scriptsWidget()
QScriptDebuggerScriptsWidgetInterface * QScriptDebugger::scriptsWidget () const
Definition at line 1511 of file qscriptdebugger.cpp.
Referenced by setScriptsWidget(), and widget().
 {
     Q_D(const QScriptDebugger);
     return d->scriptsWidget;
 }
setBreakpointsWidget()
void QScriptDebugger::setBreakpointsWidget (QScriptBreakpointsWidgetInterface * breakpointsWidget)
Definition at line 1635 of file qscriptdebugger.cpp.
Referenced by widget().
 {
     Q_D(QScriptDebugger);
     if (d->breakpointsWidget) {
         // ### invalidate
     }
     d->breakpointsWidget = breakpointsWidget;
     if (breakpointsWidget) {
         if (!d->breakpointsModel) {
             d->breakpointsModel = new QScriptBreakpointsModel(d, d, this);
             if (d->interactive)
                 d->scheduleJob(new SyncBreakpointsJob(d));
         }
         d->breakpointsWidget->setBreakpointsModel(d->breakpointsModel);
         d->breakpointsWidget->setScriptsModel(d->scriptsModel);
     }
 }
setCodeFinderWidget()
void QScriptDebugger::setCodeFinderWidget (QScriptDebuggerCodeFinderWidgetInterface * codeFinderWidget)
Definition at line 1598 of file qscriptdebugger.cpp.
Referenced by widget().
 {
     Q_D(QScriptDebugger);
     if (d->codeFinderWidget) {
         QObject::disconnect(d->codeFinderWidget, 0, this, 0);
     }
     d->codeFinderWidget = codeFinderWidget;
     if (codeFinderWidget) {
         QObject::connect(codeFinderWidget, SIGNAL(findRequest(QString,int)),
                          this, SLOT(_q_onFindCodeRequest(QString,int)));
     }
     if (d->findInScriptAction) {
         d->findInScriptAction->setEnabled(
             (codeFinderWidget != 0)
             && (d->codeWidget != 0)
             && (d->codeWidget->currentView() != 0));
     }
 }
setCodeWidget()
void QScriptDebugger::setCodeWidget (QScriptDebuggerCodeWidgetInterface * codeWidget)
Definition at line 1560 of file qscriptdebugger.cpp.
Referenced by widget().
 {
     Q_D(QScriptDebugger);
     if (d->codeWidget) {
         d->codeWidget->removeEventFilter(this);
     }
     d->codeWidget = codeWidget;
     if (codeWidget) {
         if (!d->scriptsModel) {
             d->scriptsModel = new QScriptDebuggerScriptsModel(this);
             if (d->interactive)
                 d->scheduleJob(new SyncScriptsJob(d));
         }
         codeWidget->setScriptsModel(d->scriptsModel);
         if (!d->breakpointsModel) {
             d->breakpointsModel = new QScriptBreakpointsModel(d, d, this);
             if (d->interactive)
                 d->scheduleJob(new SyncBreakpointsJob(d));
         }
         codeWidget->setBreakpointsModel(d->breakpointsModel);
         codeWidget->setToolTipProvider(d);
         codeWidget->installEventFilter(this);
     }
     bool hasScript = (codeWidget != 0) && (codeWidget->currentView() != 0);
     if (d->findInScriptAction)
         d->findInScriptAction->setEnabled(hasScript && (d->codeFinderWidget != 0));
     if (d->goToLineAction)
         d->goToLineAction->setEnabled(hasScript);
     if (d->toggleBreakpointAction)
         d->toggleBreakpointAction->setEnabled(hasScript);
 }
setConsoleWidget()
void QScriptDebugger::setConsoleWidget (QScriptDebuggerConsoleWidgetInterface * consoleWidget)
Definition at line 1469 of file qscriptdebugger.cpp.
Referenced by widget().
 {
     Q_D(QScriptDebugger);
     if (d->consoleWidget) {
         QObject::disconnect(d->consoleWidget, 0, this, 0);
     }
     d->consoleWidget = consoleWidget;
     if (consoleWidget) {
         consoleWidget->setCommandHistorian(d->console);
         consoleWidget->setCompletionProvider(d);
         QObject::connect(consoleWidget, SIGNAL(lineEntered(QString)),
                          this, SLOT(_q_onLineEntered(QString)));
         d->console->showDebuggerInfoMessage(consoleWidget);
     }
 }
setDebugOutputWidget()
void QScriptDebugger::setDebugOutputWidget (QScriptDebugOutputWidgetInterface * debugOutputWidget)
Definition at line 1623 of file qscriptdebugger.cpp.
Referenced by widget().
 {
     Q_D(QScriptDebugger);
     d->debugOutputWidget = debugOutputWidget;
 }
setErrorLogWidget()
void QScriptDebugger::setErrorLogWidget (QScriptErrorLogWidgetInterface * errorLogWidget)
Definition at line 1659 of file qscriptdebugger.cpp.
Referenced by widget().
 {
     Q_D(QScriptDebugger);
     d->errorLogWidget = errorLogWidget;
 }
setFrontend()
void QScriptDebugger::setFrontend (QScriptDebuggerFrontend * frontend)
Definition at line 1331 of file qscriptdebugger.cpp.
 {
     Q_D(QScriptDebugger);
     if (d->frontend)
         d->frontend->setEventHandler(0);
     d->frontend = frontend;
     if (frontend) {
         frontend->setEventHandler(d);
         if (!eventCallbackRegistered) {
             eventCallbackRegistered = true;
             QInternal::registerCallback(QInternal::EventNotifyCallback,
                                         scriptDebuggerEventCallback);
         }
     }
 }
setLocalsWidget()
void QScriptDebugger::setLocalsWidget (QScriptDebuggerLocalsWidgetInterface * localsWidget)
Definition at line 1544 of file qscriptdebugger.cpp.
Referenced by widget().
 {
     Q_D(QScriptDebugger);
     if (d->localsWidget) {
         // ### d->localsWidget->setLocalsModel(0);
     }
     localsWidget->setCompletionProvider(d);
     d->localsWidget = localsWidget;
 }
setScriptsWidget()
void QScriptDebugger::setScriptsWidget (QScriptDebuggerScriptsWidgetInterface * scriptsWidget)
Definition at line 1517 of file qscriptdebugger.cpp.
Referenced by widget().
 {
     Q_D(QScriptDebugger);
     if (d->scriptsWidget) {
         QObject::disconnect(d->scriptsWidget, 0, this, 0);
     }
     d->scriptsWidget = scriptsWidget;
     if (scriptsWidget) {
         if (!d->scriptsModel) {
             d->scriptsModel = new QScriptDebuggerScriptsModel(this);
             if (d->interactive)
                 d->scheduleJob(new SyncScriptsJob(d));
         }
         scriptsWidget->setScriptsModel(d->scriptsModel);
         QObject::connect(scriptsWidget, SIGNAL(currentScriptChanged(qint64)),
                          this, SLOT(_q_onCurrentScriptChanged(qint64)));
         QObject::connect(d->scriptsWidget, SIGNAL(scriptLocationSelected(int)),
                          this, SLOT(_q_onScriptLocationSelected(int)));
     }
 }
setStackWidget()
void QScriptDebugger::setStackWidget (QScriptDebuggerStackWidgetInterface * stackWidget)
Definition at line 1492 of file qscriptdebugger.cpp.
Referenced by widget().
 {
     Q_D(QScriptDebugger);
     if (d->stackWidget) {
         QObject::disconnect(d->stackWidget, 0, this, 0);
     }
     d->stackWidget = stackWidget;
     if (stackWidget) {
         if (!d->stackModel) {
             d->stackModel = new QScriptDebuggerStackModel(this);
             if (d->interactive)
                 d->scheduleJob(new SyncStackJob(d));
         }
         stackWidget->setStackModel(d->stackModel);
         QObject::connect(stackWidget, SIGNAL(currentFrameChanged(int)),
                          this, SLOT(_q_onCurrentFrameChanged(int)));
     }
 }
setWidgetFactory()
void QScriptDebugger::setWidgetFactory (QScriptDebuggerWidgetFactoryInterface * factory)
Definition at line 1671 of file qscriptdebugger.cpp.
 {
     Q_D(QScriptDebugger);
     d->widgetFactory = factory;
 }
stackWidget()
QScriptDebuggerStackWidgetInterface * QScriptDebugger::stackWidget () const
Definition at line 1486 of file qscriptdebugger.cpp.
Referenced by setStackWidget(), and widget().
 {
     Q_D(const QScriptDebugger);
     return d->stackWidget;
 }
started
void QScriptDebugger::started () const signal
stepIntoAction()
QAction * QScriptDebugger::stepIntoAction (QObject * parent) const
Definition at line 1711 of file qscriptdebugger.cpp.
Referenced by action(), and stepIntoAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->stepIntoAction) {
         QIcon stepIntoIcon;
         stepIntoIcon.addPixmap(d->pixmap(QString::fromLatin1("stepinto.png")), QIcon::Normal);
         stepIntoIcon.addPixmap(d->pixmap(QString::fromLatin1("d_stepinto.png")), QIcon::Disabled);
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->stepIntoAction = new QAction(stepIntoIcon, QScriptDebugger::tr("Step Into"), parent);
         d->stepIntoAction->setEnabled(d->interactive);
         d->stepIntoAction->setShortcut(QScriptDebugger::tr("F11"));
         QObject::connect(d->stepIntoAction, SIGNAL(triggered()),
                          that, SLOT(_q_stepInto()));
     }
     return d->stepIntoAction;
 }
stepOutAction()
QAction * QScriptDebugger::stepOutAction (QObject * parent) const
Definition at line 1745 of file qscriptdebugger.cpp.
Referenced by action(), and stepOutAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->stepOutAction) {
         QIcon stepOutIcon;
         stepOutIcon.addPixmap(d->pixmap(QString::fromLatin1("stepout.png")), QIcon::Normal);
         stepOutIcon.addPixmap(d->pixmap(QString::fromLatin1("d_stepout.png")), QIcon::Disabled);
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->stepOutAction = new QAction(stepOutIcon, QScriptDebugger::tr("Step Out"), parent);
         d->stepOutAction->setEnabled(d->interactive);
         d->stepOutAction->setShortcut(QScriptDebugger::tr("Shift+F11"));
         QObject::connect(d->stepOutAction, SIGNAL(triggered()),
                          that, SLOT(_q_stepOut()));
     }
     return d->stepOutAction;
 }
stepOverAction()
QAction * QScriptDebugger::stepOverAction (QObject * parent) const
Definition at line 1728 of file qscriptdebugger.cpp.
Referenced by action(), and stepOverAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->stepOverAction) {
         QIcon stepOverIcon;
         stepOverIcon.addPixmap(d->pixmap(QString::fromLatin1("stepover.png")), QIcon::Normal);
         stepOverIcon.addPixmap(d->pixmap(QString::fromLatin1("d_stepover.png")), QIcon::Disabled);
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->stepOverAction = new QAction(stepOverIcon, QScriptDebugger::tr("Step Over"), parent);
         d->stepOverAction->setEnabled(d->interactive);
         d->stepOverAction->setShortcut(QScriptDebugger::tr("F10"));
         QObject::connect(d->stepOverAction, SIGNAL(triggered()),
                          that, SLOT(_q_stepOver()));
     }
     return d->stepOverAction;
 }
stopped
void QScriptDebugger::stopped () const signal
timerEvent()
void QScriptDebugger::timerEvent (QTimerEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 1981 of file qscriptdebugger.cpp.
 {
     Q_D(QScriptDebugger);
     if (e->timerId() == d->updatesEnabledTimerId) {
         killTimer(d->updatesEnabledTimerId);
         d->updatesEnabledTimerId = -1;
         if (d->stackWidget)
             d->stackWidget->setUpdatesEnabled(true);
         if (d->localsWidget)
             d->localsWidget->setUpdatesEnabled(true);
     } else {
         QObject::timerEvent(e);
     }
 }
toggleBreakpointAction()
QAction * QScriptDebugger::toggleBreakpointAction (QObject * parent) const
Definition at line 1796 of file qscriptdebugger.cpp.
Referenced by action(), and toggleBreakpointAction().
 {
     Q_D(const QScriptDebugger);
     if (!d->toggleBreakpointAction) {
         QIcon toggleBreakpointIcon;
         QScriptDebugger *that = const_cast<QScriptDebugger*>(this);
         that->d_func()->toggleBreakpointAction = new QAction(toggleBreakpointIcon,
                                                              QScriptDebugger::tr("Toggle Breakpoint"), parent);
         d->toggleBreakpointAction->setShortcut(QScriptDebugger::tr("F9"));
         d->toggleBreakpointAction->setEnabled((d->codeWidget != 0) && (d->codeWidget->currentView() != 0));
         QObject::connect(d->toggleBreakpointAction, SIGNAL(triggered()),
                          that, SLOT(_q_toggleBreakpoint()));
     }
     return d->toggleBreakpointAction;
 }
widget()
QWidget * QScriptDebugger::widget (DebuggerWidget widget)
Definition at line 1384 of file qscriptdebugger.cpp.
 {
     switch (widget) {
     case ConsoleWidget: {
         QScriptDebuggerConsoleWidgetInterface *w = consoleWidget();
         if (!w && widgetFactory()) {
             w = widgetFactory()->createConsoleWidget();
             setConsoleWidget(w);
         }
         return w;
     }
     case StackWidget: {
         QScriptDebuggerStackWidgetInterface *w = stackWidget();
         if (!w && widgetFactory()) {
             w = widgetFactory()->createStackWidget();
             setStackWidget(w);
         }
         return w;
     }
     case ScriptsWidget: {
         QScriptDebuggerScriptsWidgetInterface *w = scriptsWidget();
         if (!w && widgetFactory()) {
             w = widgetFactory()->createScriptsWidget();
             setScriptsWidget(w);
         }
         return w;
     }
     case LocalsWidget: {
         QScriptDebuggerLocalsWidgetInterface *w = localsWidget();
         if (!w && widgetFactory()) {
             w = widgetFactory()->createLocalsWidget();
             setLocalsWidget(w);
         }
         return w;
     }
     case CodeWidget: {
         QScriptDebuggerCodeWidgetInterface *w = codeWidget();
         if (!w && widgetFactory()) {
             w = widgetFactory()->createCodeWidget();
             setCodeWidget(w);
         }
         return w;
     }
     case CodeFinderWidget: {
         QScriptDebuggerCodeFinderWidgetInterface *w = codeFinderWidget();
         if (!w && widgetFactory()) {
             w = widgetFactory()->createCodeFinderWidget();
             setCodeFinderWidget(w);
         }
         return w;
     }
     case BreakpointsWidget: {
         QScriptBreakpointsWidgetInterface *w = breakpointsWidget();
         if (!w && widgetFactory()) {
             w = widgetFactory()->createBreakpointsWidget();
             setBreakpointsWidget(w);
         }
         return w;
     }
     case DebugOutputWidget: {
         QScriptDebugOutputWidgetInterface *w = debugOutputWidget();
         if (!w && widgetFactory()) {
             w = widgetFactory()->createDebugOutputWidget();
             setDebugOutputWidget(w);
         }
         return w;
     }
     case ErrorLogWidget: {
         QScriptErrorLogWidgetInterface *w = errorLogWidget();
         if (!w && widgetFactory()) {
             w = widgetFactory()->createErrorLogWidget();
             setErrorLogWidget(w);
         }
         return w;
     }
     }
     return 0;
 }
widgetFactory()
QScriptDebuggerWidgetFactoryInterface * QScriptDebugger::widgetFactory () const
Definition at line 1665 of file qscriptdebugger.cpp.
Referenced by widget().
 {
     Q_D(const QScriptDebugger);
     return d->widgetFactory;
 }
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebugger_p.h
/src/scripttools/debugging/qscriptdebugger.cpp