Qt 4.8: QXmlUtils Class Reference
QXmlUtils Class Reference
This class contains helper functions related to XML, for validating character classes, productions in the XML specification, and so on.
#include <qxmlutils_p.h>
Static Public Functions
static bool isChar (const QChar c)
Determines whether c is a valid instance of production [2]Char in the XML 1.0 specification.
static bool isEncName (const QString &encName)
Determines whether encName is a valid instance of production [81]EncName in the XML 1.0 specification.
static bool isLetter (const QChar c)
Determines whether c is a valid instance of production [84]Letter in the XML 1.0 specification.
static bool isNameChar (const QChar c)
Determines whether c is a valid instance of production [4]NameChar in the XML 1.0 specification.
static bool isNCName (const QStringRef &ncName)
Determines whether c is a valid instance of production [4]NCName in the XML 1.0 Namespaces specification.
static bool isNCName (const QString &ncName)
static bool isPublicID (const QString &candidate)
Determines whether c is a valid instance of production [12] PubidLiteral in the XML 1.0 specification.
Private Types
typedef const QXmlCharRange * RangeIter
Static Private Functions
static bool isBaseChar (const QChar c)
static bool isCombiningChar (const QChar c)
static bool isDigit (const QChar c)
static bool isExtender (const QChar c)
static bool isIdeographic (const QChar c)
static bool rangeContains (RangeIter begin, RangeIter end, const QChar c)
Performs a binary search between begin and end inclusive, to check whether c is contained.
Detailed Description
This class contains helper functions related to XML, for validating character classes, productions in the XML specification, and so on.
Warning
This function is not part of the public interface.
Definition at line 69 of file qxmlutils_p.h.
Typedefs
RangeIter
typedef const QXmlCharRange* QXmlUtils::RangeIter private
Definition at line 81 of file qxmlutils_p.h.
Functions
isBaseChar()
bool QXmlUtils::isBaseChar (const QChar c) static private
Definition at line 219 of file qxmlutils.cpp.
 {
     return rangeContains(g_base_begin, g_base_end, c);
 }
isChar()
bool QXmlUtils::isChar (const QChar c) static
Determines whether c is a valid instance of production [2]Char in the XML 1.0 specification.
Warning
This function is not part of the public interface.
If it is, true is returned, otherwise false.
See also
http://www.w3.org/TR/REC-xml/#NT-Char {Extensible Markup Language (XML) 1.0 (Fourth Edition), [2] Char}
Definition at line 271 of file qxmlutils.cpp.
Referenced by fixedCharData(), and QPatternist::AccelTreeResourceLoader::retrieveUnparsedText().
 {
     return (c.unicode() >= 0x0020 && c.unicode() <= 0xD7FF)
            || c.unicode() == 0x0009
            || c.unicode() == 0x000A
            || c.unicode() == 0x000D
            || (c.unicode() >= 0xE000 && c.unicode() <= 0xFFFD);
 }
isCombiningChar()
bool QXmlUtils::isCombiningChar (const QChar c) static private
Definition at line 186 of file qxmlutils.cpp.
 {
     return rangeContains(g_combining_begin, g_combining_end, c);
 }
isDigit()
bool QXmlUtils::isDigit (const QChar c) static private
Definition at line 200 of file qxmlutils.cpp.
 {
     return rangeContains(g_digit_begin, g_digit_end, c);
 }
isEncName()
bool QXmlUtils::isEncName (const QString & encName) static
Determines whether encName is a valid instance of production [81]EncName in the XML 1.0 specification.
Warning
This function is not part of the public interface.
If it is, true is returned, otherwise false.
See also
http://www.w3.org/TR/REC-xml/#NT-EncName {Extensible Markup Language (XML) 1.0 (Fourth Edition), [81] EncName}
Definition at line 234 of file qxmlutils.cpp.
Referenced by QXmlStreamReaderPrivate::startDocument().
 {
     /* Right, we here have a dependency on QRegExp. Writing a manual parser to
      * replace that regexp is probably a 70 lines so I prioritize this to when
      * the dependency is considered alarming, or when the rest of the bugs
      * are fixed. */
     const QRegExp encNameRegExp(QLatin1String("[A-Za-z][A-Za-z0-9._\\-]*"));
     Q_ASSERT(encNameRegExp.isValid());
     return encNameRegExp.exactMatch(encName);
 }
isExtender()
bool QXmlUtils::isExtender (const QChar c) static private
Definition at line 214 of file qxmlutils.cpp.
 {
     return rangeContains(g_extender_begin, g_extender_end, c);
 }
isIdeographic()
bool QXmlUtils::isIdeographic (const QChar c) static private
Definition at line 157 of file qxmlutils.cpp.
 {
     return rangeContains(g_ideographic_begin, g_ideographic_end, c);
 }
isLetter()
bool QXmlUtils::isLetter (const QChar c) static
Determines whether c is a valid instance of production [84]Letter in the XML 1.0 specification.
Warning
This function is not part of the public interface.
If it is, true is returned, otherwise false.
See also
http://www.w3.org/TR/REC-xml/#NT-Letter {Extensible Markup Language (XML) 1.0 (Fourth Edition), [84] Letter}
Definition at line 256 of file qxmlutils.cpp.
Referenced by fixedXmlName(), and isNCName().
 {
     return isBaseChar(c) || isIdeographic(c);
 }
isNameChar()
bool QXmlUtils::isNameChar (const QChar c) static
Determines whether c is a valid instance of production [4]NameChar in the XML 1.0 specification.
Warning
This function is not part of the public interface.
If it is, true is returned, otherwise false.
See also
http://www.w3.org/TR/REC-xml/#NT-NameChar {Extensible Markup Language (XML) 1.0 (Fourth Edition), [4] NameChar}
Definition at line 291 of file qxmlutils.cpp.
Referenced by fixedXmlName(), and isNCName().
 {
     return isBaseChar(c)
            || isDigit(c)
            || c.unicode() == '.'
            || c.unicode() == '-'
            || c.unicode() == '_'
            || c.unicode() == ':'
            || isCombiningChar(c)
            || isIdeographic(c)
            || isExtender(c);
 }
isNCName() [1/2]
bool QXmlUtils::isNCName (const QStringRef & ncName) static
Determines whether c is a valid instance of production [4]NCName in the XML 1.0 Namespaces specification.
Warning
This function is not part of the public interface.
If it is, true is returned, otherwise false.
See also
http://www.w3.org/TR/REC-xml-names/#NT-NCName {W3CNamespaces in XML 1.0 (Second Edition), [4] NCName}
Definition at line 377 of file qxmlutils.cpp.
Referenced by QPatternist::NamePool::allocateBinding(), QPatternist::NamePool::allocateQName(), QPatternist::AccelTreeBuilder< true >::attribute(), QPatternist::ComputedNamespaceConstructor::evaluateToSequenceReceiver(), QPatternist::DerivedString< TypeToken >::fromLexical(), QXmlName::isNCName(), QPatternist::XPathHelper::isQName(), StringSplitter::loadNext(), QXmlStreamReaderPrivate::parse(), QXmlName::QXmlName(), QPatternist::XsdSchemaParser::readNameAttribute(), QPatternist::XPathHelper::splitQName(), QPatternist::NamePool::unlockedAllocateLocalName(), QPatternist::NCNameConstructor::validateTargetName(), and QPatternist::yyparse().
 {
     if(ncName.isEmpty())
         return false;
     const QChar first(ncName.at(0));
     if(!QXmlUtils::isLetter(first) && first.unicode() != '_' && first.unicode() != ':')
         return false;
     const int len = ncName.size();
     for(int i = 0; i < len; ++i)
     {
         const QChar &at = ncName.at(i);
         if(!QXmlUtils::isNameChar(at) || at == QLatin1Char(':'))
             return false;
     }
     return true;
 }
isNCName() [2/2]
static bool QXmlUtils::isNCName (const QString & ncName) inline static
Definition at line 77 of file qxmlutils_p.h.
Referenced by isNCName().
 { return isNCName(&ncName); }
isPublicID()
bool QXmlUtils::isPublicID (const QString & candidate) static
Determines whether c is a valid instance of production [12] PubidLiteral in the XML 1.0 specification.
Warning
This function is not part of the public interface.
If it is, true is returned, otherwise false.
See also
http://www.w3.org/TR/REC-xml/#NT-PubidLiteral {Extensible Markup Language (XML) 1.0 (Fourth Edition), [12] PubidLiteral}
Definition at line 316 of file qxmlutils.cpp.
Referenced by fixedPubidLiteral(), and QXmlStreamReaderPrivate::parse().
 {
     const int len = candidate.length();
     for(int i = 0; i < len; ++i)
     {
         const ushort cp = candidate.at(i).unicode();
         if ((cp >= 'a' && cp <= 'z')
             || (cp >= 'A' && cp <= 'Z')
             || (cp >= '0' && cp <= '9'))
         {
             continue;
         }
         switch (cp)
         {
             /* Fallthrough all these. */
             case 0x20:
             case 0x0D:
             case 0x0A:
             case '-':
             case '\'':
             case '(':
             case ')':
             case '+':
             case ',':
             case '.':
             case '/':
             case ':':
             case '=':
             case '?':
             case ';':
             case '!':
             case '*':
             case '#':
             case '@':
             case '$':
             case '_':
             case '%':
                 continue;
             default:
                 return false;
         }
     }
     return true;
 }
rangeContains()
bool QXmlUtils::rangeContains (RangeIter begin, RangeIter end, const QChar c) static private
Performs a binary search between begin and end inclusive, to check whether c is contained.
Remember that the QXmlCharRange instances must be in numeric order.
Definition at line 67 of file qxmlutils.cpp.
 {
     const ushort cp(c.unicode());
     // check the first two ranges "manually" as characters in that
     // range are checked very often and we avoid the binary search below.
     if (cp <= begin->max)
         return cp >= begin->min;
     ++begin;
     if (begin == end)
         return false;
     if (cp <= begin->max)
         return cp >= begin->min;
     while (begin != end) {
         int delta = (end - begin) / 2;
         RangeIter mid = begin + delta;
         if (mid->min > cp)
             end = mid;
         else if (mid->max < cp)
             begin = mid;
         else
             return true;
         if (delta == 0)
             break;
     }
     return false;
 }
The documentation for this class was generated from the following files:
/src/corelib/xml/qxmlutils_p.h
/src/corelib/xml/qxmlutils.cpp