Qt 4.8: QGraphicsSystem Class Reference
QGraphicsSystem Class Reference abstract
#include <qgraphicssystem_p.h>
Public Functions
virtual QPixmapData * createPixmapData (QPixmapData::PixelType type) const =0
virtual QPixmapData * createPixmapData (QPixmapData *origin)
virtual QWindowSurface * createWindowSurface (QWidget *widget) const =0
virtual QGraphicsSystemEx * platformExtension ()
virtual ~QGraphicsSystem ()
Static Public Functions
static QPixmapData * createDefaultPixmapData (QPixmapData::PixelType type)
Detailed Description
Definition at line 68 of file qgraphicssystem_p.h.
Constructors and Destructors
~QGraphicsSystem()
QGraphicsSystem::~QGraphicsSystem () virtual
Definition at line 65 of file qgraphicssystem.cpp.
 {
 }
Functions
createDefaultPixmapData()
QPixmapData * QGraphicsSystem::createDefaultPixmapData (QPixmapData::PixelType type) static
Definition at line 69 of file qgraphicssystem.cpp.
Referenced by QPixmapData::create(), QPixmapData::createCompatiblePixmapData(), QBitmap::fromImage(), QPixmap::fromImage(), and QPixmap::fromImageReader().
 {
 #ifdef Q_WS_QWS
     Q_UNUSED(type);
 #endif
 #if defined(Q_WS_X11)
     return new QX11PixmapData(type);
 #elif defined(Q_WS_WIN)
     return new QRasterPixmapData(type);
 #elif defined(Q_WS_MAC)
     return new QMacPixmapData(type);
 #elif defined(Q_WS_QPA)
     return QApplicationPrivate::platformIntegration()->createPixmapData(type);
 #elif defined(Q_OS_SYMBIAN)
     return new QSymbianRasterPixmapData(type);
 #elif !defined(Q_WS_QWS)
 #error QGraphicsSystem::createDefaultPixmapData() not implemented
 #endif
     return 0;
 }
createPixmapData() [1/2]
virtual QPixmapData* QGraphicsSystem::createPixmapData (QPixmapData::PixelType type) const pure virtual
Implemented in QRuntimeGraphicsSystem, QGLGraphicsSystem, QVGGraphicsSystem, QWSGraphicsSystem, QDirectFBScreenPrivate, QTraceGraphicsSystem, QCoreGraphicsSystem, QRasterGraphicsSystem, QMeeGoGraphicsSystem, and ShivaVGGraphicsSystem.
Referenced by QPixmapData::create(), QPixmapData::createCompatiblePixmapData(), createPixmapData(), QRuntimeGraphicsSystem::createPixmapData(), QBitmap::fromImage(), QPixmap::fromImage(), QPixmap::fromImageReader(), QWSGraphicsSystem::QWSGraphicsSystem(), and QRuntimeGraphicsSystem::setGraphicsSystem().
createPixmapData() [2/2]
QPixmapData * QGraphicsSystem::createPixmapData (QPixmapData * origin) virtual
Reimplemented in QMeeGoGraphicsSystem.
Definition at line 90 of file qgraphicssystem.cpp.
 {
     return createPixmapData(origin->pixelType());
 }
createWindowSurface()
virtual QWindowSurface* QGraphicsSystem::createWindowSurface (QWidget * widget) const pure virtual
Implemented in QRuntimeGraphicsSystem, QGLGraphicsSystem, QVGGraphicsSystem, QWSGraphicsSystem, QTraceGraphicsSystem, QCoreGraphicsSystem, QRasterGraphicsSystem, QMeeGoGraphicsSystem, and ShivaVGGraphicsSystem.
Referenced by QWidgetPrivate::createDefaultWindowSurface(), QRuntimeGraphicsSystem::createWindowSurface(), QWSGraphicsSystem::QWSGraphicsSystem(), and QRuntimeGraphicsSystem::setGraphicsSystem().
platformExtension()
QGraphicsSystemEx * QGraphicsSystem::platformExtension () virtual
Definition at line 99 of file qgraphicssystem.cpp.
Referenced by QVGGraphicsSystem::createWindowSurface(), and QGLGraphicsSystem::createWindowSurface().
 {
 #ifdef Q_OS_SYMBIAN
     // this is used on raster graphics systems. HW accelerated
     // graphics systems will overwrite this function.
     return symbianPlatformExtension();
 #endif
     return 0;
 }
The documentation for this class was generated from the following files:
/src/gui/painting/qgraphicssystem_p.h
/src/gui/painting/qgraphicssystem.cpp