Qt 4.8: QHttpResponseHeader Class Reference
QHttpResponseHeader Class Reference
The QHttpResponseHeader class contains response header information for HTTP.
#include <qhttp.h>
Public Functions
int majorVersion () const
Returns the major protocol-version of the HTTP response header.
int minorVersion () const
Returns the minor protocol-version of the HTTP response header.
QHttpResponseHeader & operator= (const QHttpResponseHeader &header)
Copies the contents of header into this QHttpResponseHeader.
QHttpResponseHeader ()
Constructs an empty HTTP response header.
QHttpResponseHeader (const QHttpResponseHeader &header)
Constructs a copy of header.
QHttpResponseHeader (const QString &str)
Constructs a HTTP response header from the string str.
QHttpResponseHeader (int code, const QString &text=QString(), int majorVer=1, int minorVer=1)
Constructs a QHttpResponseHeader, setting the status code to code, the reason phrase to text and the protocol-version to majorVer and minorVer.
QString reasonPhrase () const
Returns the reason phrase of the HTTP response header.
void setStatusLine (int code, const QString &text=QString(), int majorVer=1, int minorVer=1)
Sets the status code to code, the reason phrase to text and the protocol-version to majorVer and minorVer.
int statusCode () const
Returns the status code of the HTTP response header.
QString toString () const
Reimplemented Function
Public Functions inherited from QHttpHeader
void addValue (const QString &key, const QString &value)
Adds a new entry with the key and value.
QStringList allValues (const QString &key) const
Returns all the entries with the given key.
uint contentLength () const
Returns the value of the special HTTP header field content-length.
QString contentType () const
Returns the value of the special HTTP header field content-type.
bool hasContentLength () const
Returns true if the header has an entry for the special HTTP header field content-length; otherwise returns false.
bool hasContentType () const
Returns true if the header has an entry for the special HTTP header field content-type; otherwise returns false.
bool hasKey (const QString &key) const
Returns true if the HTTP header has an entry with the given key; otherwise returns false.
bool isValid () const
Returns true if the HTTP header is valid; otherwise returns false.
QStringList keys () const
Returns a list of the keys in the HTTP header.
QHttpHeader & operator= (const QHttpHeader &h)
Assigns h and returns a reference to this http header.
QHttpHeader ()
Constructs an empty HTTP header.
QHttpHeader (const QHttpHeader &header)
Constructs a copy of header.
QHttpHeader (const QString &str)
Constructs a HTTP header for str.
void removeAllValues (const QString &key)
Removes all the entries with the key key from the HTTP header.
void removeValue (const QString &key)
Removes the entry with the key key from the HTTP header.
void setContentLength (int len)
Sets the value of the special HTTP header field content-length to len.
void setContentType (const QString &type)
Sets the value of the special HTTP header field content-type to type.
void setValue (const QString &key, const QString &value)
Sets the value of the entry with the key to value.
void setValues (const QList< QPair< QString, QString > > &values)
Sets the header entries to be the list of key value pairs in values.
QString value (const QString &key) const
Returns the first value for the entry with the given key.
QList< QPair< QString, QString > > values () const
Returns all the entries in the header.
virtual ~QHttpHeader ()
Destructor.
Protected Functions
bool parseLine (const QString &line, int number)
Protected Functions inherited from QHttpHeader
bool parse (const QString &str)
Parses the HTTP header string str for header fields and adds the keys/values it finds.
QHttpHeader (QHttpHeaderPrivate &dd, const QString &str=QString())
QHttpHeader (QHttpHeaderPrivate &dd, const QHttpHeader &header)
void setValid (bool)
Friends
class QHttpPrivate
Additional Inherited Members
Protected Variables inherited from QHttpHeader
QScopedPointer< QHttpHeaderPrivate > d_ptr
Detailed Description
The QHttpResponseHeader class contains response header information for HTTP.
Attention
Module: QtNetwork
This class is used by the QHttp class to report the header information that the client received from the server.
HTTP responses have a status code that indicates the status of the response. This code is a 3-digit integer result code (for details see to RFC 1945). In addition to the status code, you can also specify a human-readable text that describes the reason for the code ("reason phrase"). This class allows you to get the status code and the reason phrase.
See also
QHttpRequestHeader, QHttp, {HTTP Example}
Definition at line 119 of file qhttp.h.
Constructors and Destructors
QHttpResponseHeader() [1/4]
QHttpResponseHeader::QHttpResponseHeader ()
Constructs an empty HTTP response header.
Definition at line 1055 of file qhttp.cpp.
     : QHttpHeader(*new QHttpResponseHeaderPrivate)
 {
     setValid(false);
 }
QHttpResponseHeader() [2/4]
QHttpResponseHeader::QHttpResponseHeader (const QHttpResponseHeader & header)
Constructs a copy of header.
Definition at line 1064 of file qhttp.cpp.
     : QHttpHeader(*new QHttpResponseHeaderPrivate, header)
 {
     Q_D(QHttpResponseHeader);
     d->statCode = header.d_func()->statCode;
     d->reasonPhr = header.d_func()->reasonPhr;
     d->majVer = header.d_func()->majVer;
     d->minVer = header.d_func()->minVer;
 }
QHttpResponseHeader() [3/4]
QHttpResponseHeader::QHttpResponseHeader (const QString & str)
Constructs a HTTP response header from the string str.
The string is parsed and the information is set. The str should consist of one or more "\r\n" delimited lines; the first line should be the status-line (format: HTTP-version, space, status-code, space, reason-phrase); each of remaining lines should have the format key, colon, space, value.
Definition at line 1096 of file qhttp.cpp.
     : QHttpHeader(*new QHttpResponseHeaderPrivate)
 {
     parse(str);
 }
QHttpResponseHeader() [4/4]
QHttpResponseHeader::QHttpResponseHeader (int code, const QString & text = QString(), int majorVer = 1, int minorVer = 1)
Constructs a QHttpResponseHeader, setting the status code to code, the reason phrase to text and the protocol-version to majorVer and minorVer.
Since
4.1
See also
statusCode() reasonPhrase() majorVersion() minorVersion()
Definition at line 1114 of file qhttp.cpp.
     : QHttpHeader(*new QHttpResponseHeaderPrivate)
 {
     setStatusLine(code, text, majorVer, minorVer);
 }
Functions
majorVersion()
int QHttpResponseHeader::majorVersion () const virtual
Returns the major protocol-version of the HTTP response header.
See also
minorVersion() statusCode() reasonPhrase()
Implements QHttpHeader.
Definition at line 1168 of file qhttp.cpp.
Referenced by QHttpSocketEngine::slotSocketReadNotification().
 {
     Q_D(const QHttpResponseHeader);
     return d->majVer;
 }
minorVersion()
int QHttpResponseHeader::minorVersion () const virtual
Returns the minor protocol-version of the HTTP response header.
See also
majorVersion() statusCode() reasonPhrase()
Implements QHttpHeader.
Definition at line 1179 of file qhttp.cpp.
Referenced by QHttpSocketEngine::slotSocketReadNotification().
 {
     Q_D(const QHttpResponseHeader);
     return d->minVer;
 }
operator=()
QHttpResponseHeader & QHttpResponseHeader::operator= (const QHttpResponseHeader & header)
Copies the contents of header into this QHttpResponseHeader.
Definition at line 1077 of file qhttp.cpp.
 {
     Q_D(QHttpResponseHeader);
     QHttpHeader::operator=(header);
     d->statCode = header.d_func()->statCode;
     d->reasonPhr = header.d_func()->reasonPhr;
     d->majVer = header.d_func()->majVer;
     d->minVer = header.d_func()->minVer;
     return *this;
 }
parseLine()
bool QHttpResponseHeader::parseLine (const QString & line, int number) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QHttpHeader.
Definition at line 1187 of file qhttp.cpp.
 {
     Q_D(QHttpResponseHeader);
     if (number != 0)
         return QHttpHeader::parseLine(line, number);
     QString l = line.simplified();
     if (l.length() < 10)
         return false;
     if (l.left(5) == QLatin1String("HTTP/") && l[5].isDigit() && l[6] == QLatin1Char('.') &&
         l[7].isDigit() && l[8] == QLatin1Char(' ') && l[9].isDigit()) {
         d->majVer = l[5].toLatin1() - '0';
         d->minVer = l[7].toLatin1() - '0';
         int pos = l.indexOf(QLatin1Char(' '), 9);
         if (pos != -1) {
             d->reasonPhr = l.mid(pos + 1);
             d->statCode = l.mid(9, pos - 9).toInt();
         } else {
             d->statCode = l.mid(9).toInt();
             d->reasonPhr.clear();
         }
     } else {
         return false;
     }
     return true;
 }
reasonPhrase()
QString QHttpResponseHeader::reasonPhrase () const
Returns the reason phrase of the HTTP response header.
See also
statusCode() majorVersion() minorVersion()
Definition at line 1157 of file qhttp.cpp.
 {
     Q_D(const QHttpResponseHeader);
     return d->reasonPhr;
 }
setStatusLine()
void QHttpResponseHeader::setStatusLine (int code, const QString & text = QString(), int majorVer = 1, int minorVer = 1)
Sets the status code to code, the reason phrase to text and the protocol-version to majorVer and minorVer.
Since
4.1
See also
statusCode() reasonPhrase() majorVersion() minorVersion()
Definition at line 1131 of file qhttp.cpp.
Referenced by QHttpResponseHeader().
 {
     Q_D(QHttpResponseHeader);
     setValid(true);
     d->statCode = code;
     d->reasonPhr = text;
     d->majVer = majorVer;
     d->minVer = minorVer;
 }
statusCode()
int QHttpResponseHeader::statusCode () const
Returns the status code of the HTTP response header.
See also
reasonPhrase() majorVersion() minorVersion()
Definition at line 1146 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotReadyRead(), and QHttpSocketEngine::slotSocketReadNotification().
 {
     Q_D(const QHttpResponseHeader);
     return d->statCode;
 }
toString()
QString QHttpResponseHeader::toString () const virtual
Reimplemented Function
Reimplemented from QHttpHeader.
Definition at line 1219 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotReadyRead().
 {
     Q_D(const QHttpResponseHeader);
     QString ret(QLatin1String("HTTP/%1.%2 %3 %4\r\n%5\r\n"));
     return ret.arg(d->majVer).arg(d->minVer).arg(d->statCode).arg(d->reasonPhr).arg(QHttpHeader::toString());
 }
Friends and Related Functions
QHttpPrivate
friend class QHttpPrivate friend
Definition at line 143 of file qhttp.h.
The documentation for this class was generated from the following files:
/src/network/access/qhttp.h
/src/network/access/qhttp.cpp