Qt 4.8: QAccessibleTable2Interface Class Reference
QAccessibleTable2Interface Class Reference abstract
#include <qaccessible2.h>
Public Functions
virtual QAccessibleInterface * caption () const =0
virtual QAccessibleTable2CellInterface * cellAt (int row, int column) const =0
virtual int columnCount () const =0
virtual QString columnDescription (int column) const =0
virtual bool isColumnSelected (int column) const =0
virtual bool isRowSelected (int row) const =0
virtual QAccessible2::TableModelChange modelChange () const =0
QAccessible2Interface * qAccessibleTable2CastHelper ()
virtual int rowCount () const =0
virtual QString rowDescription (int row) const =0
virtual bool selectColumn (int column)=0
virtual int selectedCellCount () const =0
virtual QList< QAccessibleTable2CellInterface * > selectedCells () const =0
virtual int selectedColumnCount () const =0
virtual QList< int > selectedColumns () const =0
virtual int selectedRowCount () const =0
virtual QList< int > selectedRows () const =0
virtual bool selectRow (int row)=0
virtual QAccessibleInterface * summary () const =0
virtual bool unselectColumn (int column)=0
virtual bool unselectRow (int row)=0
Public Functions inherited from QAccessible2Interface
virtual ~QAccessible2Interface ()
Protected Functions
virtual void columnsInserted (const QModelIndex &parent, int first, int last)=0
virtual void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)=0
virtual void columnsRemoved (const QModelIndex &parent, int first, int last)=0
virtual void modelReset ()=0
virtual void rowsInserted (const QModelIndex &parent, int first, int last)=0
virtual void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)=0
virtual void rowsRemoved (const QModelIndex &parent, int first, int last)=0
Friends
class QAbstractItemView
class QAbstractItemViewPrivate
Detailed Description
Definition at line 269 of file qaccessible2.h.
Functions
caption()
virtual QAccessibleInterface* QAccessibleTable2Interface::caption () const pure virtual
Implemented in QAccessibleTable2.
cellAt()
virtual QAccessibleTable2CellInterface* QAccessibleTable2Interface::cellAt (int row, int column) const pure virtual
Implemented in QAccessibleTree, and QAccessibleTable2.
columnCount()
virtual int QAccessibleTable2Interface::columnCount () const pure virtual
Implemented in QAccessibleTable2.
columnDescription()
virtual QString QAccessibleTable2Interface::columnDescription (int column) const pure virtual
Implemented in QAccessibleTable2.
columnsInserted()
virtual void QAccessibleTable2Interface::columnsInserted (const QModelIndex & parent, int first, int last) protected pure virtual
Implemented in QAccessibleTable2.
Referenced by QAbstractItemViewPrivate::_q_columnsInserted().
columnsMoved()
virtual void QAccessibleTable2Interface::columnsMoved (const QModelIndex & parent, int start, int end, const QModelIndex & destination, int column) protected pure virtual
Implemented in QAccessibleTable2.
columnsRemoved()
virtual void QAccessibleTable2Interface::columnsRemoved (const QModelIndex & parent, int first, int last) protected pure virtual
Implemented in QAccessibleTable2.
Referenced by QAbstractItemViewPrivate::_q_columnsRemoved().
isColumnSelected()
virtual bool QAccessibleTable2Interface::isColumnSelected (int column) const pure virtual
Implemented in QAccessibleTable2.
isRowSelected()
virtual bool QAccessibleTable2Interface::isRowSelected (int row) const pure virtual
Implemented in QAccessibleTree, and QAccessibleTable2.
modelChange()
virtual QAccessible2::TableModelChange QAccessibleTable2Interface::modelChange () const pure virtual
Implemented in QAccessibleTable2.
modelReset()
virtual void QAccessibleTable2Interface::modelReset () protected pure virtual
Implemented in QAccessibleTable2.
Referenced by QAbstractItemViewPrivate::_q_layoutChanged(), and QAbstractItemView::reset().
qAccessibleTable2CastHelper()
QAccessible2Interface* QAccessibleTable2Interface::qAccessibleTable2CastHelper () inline
Definition at line 272 of file qaccessible2.h.
 { return this; }
rowCount()
virtual int QAccessibleTable2Interface::rowCount () const pure virtual
Implemented in QAccessibleTree, and QAccessibleTable2.
rowDescription()
virtual QString QAccessibleTable2Interface::rowDescription (int row) const pure virtual
Implemented in QAccessibleTree, and QAccessibleTable2.
rowsInserted()
virtual void QAccessibleTable2Interface::rowsInserted (const QModelIndex & parent, int first, int last) protected pure virtual
Implemented in QAccessibleTable2.
Referenced by QAbstractItemViewPrivate::_q_rowsInserted().
rowsMoved()
virtual void QAccessibleTable2Interface::rowsMoved (const QModelIndex & parent, int start, int end, const QModelIndex & destination, int row) protected pure virtual
Implemented in QAccessibleTable2.
rowsRemoved()
virtual void QAccessibleTable2Interface::rowsRemoved (const QModelIndex & parent, int first, int last) protected pure virtual
Implemented in QAccessibleTable2.
Referenced by QAbstractItemViewPrivate::_q_rowsRemoved().
selectColumn()
virtual bool QAccessibleTable2Interface::selectColumn (int column) pure virtual
Implemented in QAccessibleTable2.
selectedCellCount()
virtual int QAccessibleTable2Interface::selectedCellCount () const pure virtual
Implemented in QAccessibleTable2.
selectedCells()
virtual QList<QAccessibleTable2CellInterface*> QAccessibleTable2Interface::selectedCells () const pure virtual
Implemented in QAccessibleTable2.
selectedColumnCount()
virtual int QAccessibleTable2Interface::selectedColumnCount () const pure virtual
Implemented in QAccessibleTable2.
selectedColumns()
virtual QList<int> QAccessibleTable2Interface::selectedColumns () const pure virtual
Implemented in QAccessibleTable2.
selectedRowCount()
virtual int QAccessibleTable2Interface::selectedRowCount () const pure virtual
Implemented in QAccessibleTable2.
selectedRows()
virtual QList<int> QAccessibleTable2Interface::selectedRows () const pure virtual
Implemented in QAccessibleTable2.
selectRow()
virtual bool QAccessibleTable2Interface::selectRow (int row) pure virtual
Implemented in QAccessibleTree, and QAccessibleTable2.
summary()
virtual QAccessibleInterface* QAccessibleTable2Interface::summary () const pure virtual
Implemented in QAccessibleTable2.
unselectColumn()
virtual bool QAccessibleTable2Interface::unselectColumn (int column) pure virtual
Implemented in QAccessibleTable2.
unselectRow()
virtual bool QAccessibleTable2Interface::unselectRow (int row) pure virtual
Implemented in QAccessibleTable2.
Friends and Related Functions
QAbstractItemView
friend class QAbstractItemView friend
Definition at line 325 of file qaccessible2.h.
QAbstractItemViewPrivate
friend class QAbstractItemViewPrivate friend
Definition at line 326 of file qaccessible2.h.
The documentation for this class was generated from the following file:
/src/gui/accessible/qaccessible2.h