Qt 4.8: QGtkPainter Class Reference
QGtkPainter Class Reference
#include <qgtkpainter_p.h>
Public Functions
GtkStyle * getStyle (GtkWidget *gtkWidget)
GtkStateType gtkState (const QStyleOption *option)
void paintArrow (GtkWidget *gtkWidget, const gchar *part, const QRect &arrowrect, GtkArrowType arrow_type, GtkStateType state, GtkShadowType shadow, gboolean fill, GtkStyle *style, const QString &pmKey=QString())
void paintBox (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkShadowType shadow, GtkStyle *style, const QString &pmKey=QString())
void paintBoxGap (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkShadowType shadow, GtkPositionType gap_side, gint x, gint width, GtkStyle *style)
void paintCheckbox (GtkWidget *gtkWidget, const QRect &rect, GtkStateType state, GtkShadowType shadow, GtkStyle *style, const QString &detail)
void paintExpander (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkExpanderStyle expander_state, GtkStyle *style, const QString &pmKey=QString())
void paintExtention (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkShadowType shadow, GtkPositionType gap_pos, GtkStyle *style)
void paintFlatBox (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkShadowType shadow, GtkStyle *style, const QString &=QString())
void paintFocus (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkStyle *style, const QString &pmKey=QString())
void paintHandle (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkShadowType shadow, GtkOrientation orientation, GtkStyle *style)
void paintHline (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkStyle *style, int x1, int x2, int y, const QString &pmKey=QString())
void paintOption (GtkWidget *gtkWidget, const QRect &rect, GtkStateType state, GtkShadowType shadow, GtkStyle *style, const QString &detail)
void paintResizeGrip (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkShadowType shadow, GdkWindowEdge edge, GtkStyle *style, const QString &pmKey=QString())
void paintShadow (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkShadowType shadow, GtkStyle *style, const QString &pmKey=QString())
void paintSlider (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkShadowType shadow, GtkStyle *style, GtkOrientation orientation, const QString &pmKey=QString())
void paintVline (GtkWidget *gtkWidget, const gchar *part, const QRect &rect, GtkStateType state, GtkStyle *style, int y1, int y2, int x, const QString &pmKey=QString())
QGtkPainter (QPainter *painter)
void setAlphaSupport (bool value)
void setClipRect (const QRect &rect)
void setFlipHorizontal (bool value)
void setFlipVertical (bool value)
void setUsePixmapCache (bool value)
Static Public Functions
static QPixmap getIcon (const char *iconName, GtkIconSize size=GTK_ICON_SIZE_BUTTON)
Private Functions
QPixmap renderTheme (uchar *bdata, uchar *wdata, const QRect &)
Properties
bool m_alpha
QRect m_cliprect
bool m_hflipped
QPainter * m_painter
bool m_usePixmapCache
bool m_vflipped
GtkWidget * m_window
Detailed Description
Definition at line 67 of file qgtkpainter_p.h.
Constructors and Destructors
QGtkPainter()
QGtkPainter::QGtkPainter (QPainter * painter)
Definition at line 145 of file qgtkpainter.cpp.
         : m_window(QGtkStylePrivate::gtkWidget("GtkWindow"))
         , m_painter(_painter)
         , m_alpha(true)
         , m_hflipped(false)
         , m_vflipped(false)
         , m_usePixmapCache(true)
 {}
Functions
getIcon()
QPixmap QGtkPainter::getIcon (const char * iconName, GtkIconSize size = GTK_ICON_SIZE_BUTTON) static
Definition at line 191 of file qgtkpainter.cpp.
Referenced by setUsePixmapCache(), QGtkStyle::standardIconImplementation(), and QGtkStyle::standardPixmap().
 {
     GtkStyle *style = QGtkStylePrivate::gtkStyle();
     GtkIconSet* iconSet  = QGtkStylePrivate::gtk_icon_factory_lookup_default (iconName);
     GdkPixbuf* icon = QGtkStylePrivate::gtk_icon_set_render_icon(iconSet,
                                                  style,
                                                  GTK_TEXT_DIR_LTR,
                                                  GTK_STATE_NORMAL,
                                                  size,
                                                  NULL,
                                                  "button");
     uchar* data = (uchar*)QGtkStylePrivate::gdk_pixbuf_get_pixels(icon);
     int width = QGtkStylePrivate::gdk_pixbuf_get_width(icon);
     int height = QGtkStylePrivate::gdk_pixbuf_get_height(icon);
     QImage converted(width, height, QImage::Format_ARGB32);
     uchar* tdata = (uchar*)converted.bits();
     for ( int index = 0 ; index < height * width*4 ; index +=4 ) {
         //int index = y * rowstride + x;
         tdata[index + QT_RED] = data[index + GTK_RED];
         tdata[index + QT_GREEN] = data[index + GTK_GREEN];
         tdata[index + QT_BLUE] = data[index + GTK_BLUE];
         tdata[index + QT_ALPHA] = data[index + GTK_ALPHA];
     }
     QGtkStylePrivate::gdk_pixbuf_unref(icon);
     // should we free iconset?
     return QPixmap::fromImage(converted);
 }
getStyle()
GtkStyle * QGtkPainter::getStyle (GtkWidget * gtkWidget)
Definition at line 182 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawComplexControl(), QGtkStyle::drawControl(), and QGtkStyle::drawPrimitive().
 {
     Q_ASSERT(gtkWidget);
     GtkStyle* style = gtkWidget->style;
     Q_ASSERT(style);
     return style;
 }
gtkState()
GtkStateType QGtkPainter::gtkState (const QStyleOption * option)
Definition at line 169 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawComplexControl(), QGtkStyle::drawControl(), and QGtkStyle::drawPrimitive().
 {
     GtkStateType state = GTK_STATE_NORMAL;
     if (!(option->state & QStyle::State_Enabled))
         state = GTK_STATE_INSENSITIVE;
     else if (option->state & QStyle::State_MouseOver)
         state = GTK_STATE_PRELIGHT;
     return state;
 }
paintArrow()
void QGtkPainter::paintArrow (GtkWidget * gtkWidget, const gchar * part, const QRect & arrowrect, GtkArrowType arrow_type, GtkStateType state, GtkShadowType shadow, gboolean fill, GtkStyle * style, const QString & pmKey = QString())
Definition at line 488 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawComplexControl(), QGtkStyle::drawControl(), QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     QRect rect = m_cliprect.isValid() ? m_cliprect : arrowrect;
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(QLS(part), state, shadow, rect.size())
                          % HexString<uchar>(arrow_type)
                          % pmKey;
     GdkRectangle gtkCliprect = {0, 0, rect.width(), rect.height()};
     int xOffset = m_cliprect.isValid() ? arrowrect.x() - m_cliprect.x() : 0;
     int yOffset = m_cliprect.isValid() ? arrowrect.y() - m_cliprect.y() : 0;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_arrow (style, pixmap, state, shadow,
                                          &gtkCliprect,
                                          gtkWidget,
                                          part,
                                          arrow_type, fill,
                                          xOffset, yOffset,
                                          arrowrect.width(),
                                          arrowrect.height()))
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintBox()
void QGtkPainter::paintBox (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkShadowType shadow, GtkStyle * style, const QString & pmKey = QString())
Definition at line 291 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawComplexControl(), QGtkStyle::drawControl(), QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     if (!paintRect.isValid())
         return;
     QPixmap cache;
     QRect rect = paintRect;
     // To avoid exhausting cache on large tabframes we cheat a bit by
     // tiling the center part.
     const int maxHeight = 256;
     const int maxArea = 256*512;
     const int border = 32;
     if (rect.height() > maxHeight && (rect.width()*rect.height() > maxArea))
         rect.setHeight(2 * border + 1);
     QString pixmapName = uniqueName(QLS(part), state, shadow,
                                     rect.size(), gtkWidget) % pmKey;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_box (style,
                                            pixmap,
                                            state,
                                            shadow,
                                            NULL,
                                            gtkWidget,
                                            part,
                                            0, 0,
                                            rect.width(),
                                            rect.height()));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     if (rect.size() != paintRect.size()) {
         // We assume we can stretch the middle tab part
         // Note: the side effect of this is that pinstripe patterns will get fuzzy
         const QSize size = cache.size();
         // top part
         m_painter->drawPixmap(QRect(paintRect.left(), paintRect.top(),
                                     paintRect.width(), border), cache,
                               QRect(0, 0, size.width(), border));
         // tiled center part
         QPixmap tilePart(cache.width(), 1);
         QPainter scanLinePainter(&tilePart);
         scanLinePainter.drawPixmap(QRect(0, 0, tilePart.width(), tilePart.height()), cache, QRect(0, border, size.width(), 1));
         scanLinePainter.end();
         m_painter->drawTiledPixmap(QRect(paintRect.left(), paintRect.top() + border,
                                          paintRect.width(), paintRect.height() - 2*border), tilePart);
         // bottom part
         m_painter->drawPixmap(QRect(paintRect.left(), paintRect.top() + paintRect.height() - border,
                                     paintRect.width(), border), cache,
                               QRect(0, size.height() - border, size.width(), border));
     } else
         m_painter->drawPixmap(paintRect.topLeft(), cache);
 }
paintBoxGap()
void QGtkPainter::paintBoxGap (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkShadowType shadow, GtkPositionType gap_side, gint x, gint width, GtkStyle * style)
Definition at line 224 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     if (!paintRect.isValid())
         return;
     QPixmap cache;
     QRect rect = paintRect;
     // To avoid exhausting cache on large tabframes we cheat a bit by
     // tiling the center part.
     const int maxHeight = 256;
     const int border = 16;
     if (rect.height() > maxHeight && (gap_side == GTK_POS_TOP || gap_side == GTK_POS_BOTTOM))
         rect.setHeight(2 * border + 1);
     QString pixmapName = uniqueName(QLS(part), state, shadow, rect.size(), gtkWidget)
                          % HexString<uchar>(gap_side)
                          % HexString<gint>(width)
                          % HexString<gint>(x);
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_box_gap (style,
                                            pixmap,
                                            state,
                                            shadow,
                                            NULL,
                                            gtkWidget,
                                            (gchar*)part,
                                            0, 0,
                                            rect.width(),
                                            rect.height(),
                                            gap_side,
                                            x,
                                            width));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     if (rect.size() != paintRect.size()) {
         // We assume we can stretch the middle tab part
         // Note: the side effect of this is that pinstripe patterns will get fuzzy
         const QSize size = cache.size();
         // top part
         m_painter->drawPixmap(QRect(paintRect.left(), paintRect.top(),
                                     paintRect.width(), border), cache,
                              QRect(0, 0, size.width(), border));
         // tiled center part
         QPixmap tilePart(cache.width(), 1);
         QPainter scanLinePainter(&tilePart);
         scanLinePainter.drawPixmap(QRect(0, 0, tilePart.width(), tilePart.height()), cache, QRect(0, border, size.width(), 1));
         scanLinePainter.end();
         m_painter->drawTiledPixmap(QRect(paintRect.left(), paintRect.top() + border,
                                          paintRect.width(), paintRect.height() - 2*border), tilePart);
         // bottom part
         m_painter->drawPixmap(QRect(paintRect.left(), paintRect.top() + paintRect.height() - border,
                                     paintRect.width(), border), cache,
                              QRect(0, size.height() - border, size.width(), border));
     } else
         m_painter->drawPixmap(paintRect.topLeft(), cache);
 }
paintCheckbox()
void QGtkPainter::paintCheckbox (GtkWidget * gtkWidget, const QRect & rect, GtkStateType state, GtkShadowType shadow, GtkStyle * style, const QString & detail)
Definition at line 682 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawControl(), QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     QRect rect = m_cliprect.isValid() ? m_cliprect : checkrect;
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(detail, state, shadow, rect.size());
     GdkRectangle gtkCliprect = {0, 0, rect.width(), rect.height()};
     int xOffset = m_cliprect.isValid() ? checkrect.x() - m_cliprect.x() : 0;
     int yOffset = m_cliprect.isValid() ? checkrect.y() - m_cliprect.y() : 0;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_check (style,
                                          pixmap,
                                          state,
                                          shadow,
                                          &gtkCliprect,
                                          gtkWidget,
                                          detail.toLatin1(),
                                          xOffset, yOffset,
                                          checkrect.width(),
                                          checkrect.height()));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintExpander()
void QGtkPainter::paintExpander (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkExpanderStyle expander_state, GtkStyle * style, const QString & pmKey = QString())
Definition at line 413 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(QLS(part), state, GTK_SHADOW_NONE, rect.size(), gtkWidget)
                          % HexString<uchar>(expander_state)
                          % pmKey;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_expander (style, pixmap,
                                             state, NULL,
                                             gtkWidget, part,
                                             rect.width()/2,
                                             rect.height()/2,
                                             expander_state));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintExtention()
void QGtkPainter::paintExtention (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkShadowType shadow, GtkPositionType gap_pos, GtkStyle * style)
Definition at line 625 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawControl(), and setUsePixmapCache().
 {
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(QLS(part), state, shadow, rect.size(), gtkWidget)
                          % HexString<uchar>(gap_pos);
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_extension (style, pixmap, state, shadow,
                                              NULL, gtkWidget,
                                              (gchar*)part, 0, 0,
                                              rect.width(),
                                              rect.height(),
                                              gap_pos));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintFlatBox()
void QGtkPainter::paintFlatBox (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkShadowType shadow, GtkStyle * style, const QString & pmKey = QString())
Definition at line 600 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawComplexControl(), QGtkStyle::drawControl(), QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(QLS(part), state, shadow, rect.size()) % pmKey;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_flat_box (style,
                                             pixmap,
                                             state,
                                             shadow,
                                             NULL,
                                             gtkWidget,
                                             part, 0, 0,
                                             rect.width(),
                                             rect.height()));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintFocus()
void QGtkPainter::paintFocus (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkStyle * style, const QString & pmKey = QString())
Definition at line 440 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawComplexControl(), QGtkStyle::drawControl(), QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(QLS(part), state, GTK_SHADOW_NONE, rect.size(), gtkWidget) % pmKey;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_focus (style, pixmap, state, NULL,
                                          gtkWidget,
                                          part,
                                          0, 0,
                                          rect.width(),
                                          rect.height()));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintHandle()
void QGtkPainter::paintHandle (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkShadowType shadow, GtkOrientation orientation, GtkStyle * style)
Definition at line 522 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawControl(), QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(QLS(part), state, shadow, rect.size())
                          % HexString<uchar>(orientation);
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_handle (style,
                                           pixmap,
                                           state,
                                           shadow,
                                           NULL,
                                           gtkWidget,
                                           part, 0, 0,
                                           rect.width(),
                                           rect.height(),
                                           orientation));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintHline()
void QGtkPainter::paintHline (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkStyle * style, int x1, int x2, int y, const QString & pmKey = QString())
Definition at line 353 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawControl(), QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(QLS(part), state, GTK_SHADOW_NONE, rect.size(), gtkWidget)
                          % HexString<int>(x1)
                          % HexString<int>(x2)
                          % HexString<int>(y)
                          % pmKey;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_hline (style,
                                          pixmap,
                                          state,
                                          NULL,
                                          gtkWidget,
                                          part,
                                          x1, x2, y));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintOption()
void QGtkPainter::paintOption (GtkWidget * gtkWidget, const QRect & rect, GtkStateType state, GtkShadowType shadow, GtkStyle * style, const QString & detail)
Definition at line 651 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawControl(), QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     QRect rect = m_cliprect.isValid() ? m_cliprect : radiorect;
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(detail, state, shadow, rect.size());
     GdkRectangle gtkCliprect = {0, 0, rect.width(), rect.height()};
     int xOffset = m_cliprect.isValid() ? radiorect.x() - m_cliprect.x() : 0;
     int yOffset = m_cliprect.isValid() ? radiorect.y() - m_cliprect.y() : 0;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_option(style, pixmap,
                                          state, shadow,
                                          &gtkCliprect,
                                          gtkWidget,
                                          detail.toLatin1(),
                                          xOffset, yOffset,
                                          radiorect.width(),
                                          radiorect.height()));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintResizeGrip()
void QGtkPainter::paintResizeGrip (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkShadowType shadow, GdkWindowEdge edge, GtkStyle * style, const QString & pmKey = QString())
Definition at line 464 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawControl(), and setUsePixmapCache().
 {
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(QLS(part), state, shadow, rect.size(), gtkWidget) % pmKey;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_resize_grip (style, pixmap, state,
                                                NULL, gtkWidget,
                                                part, edge, 0, 0,
                                                rect.width(),
                                                rect.height()));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintShadow()
void QGtkPainter::paintShadow (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkShadowType shadow, GtkStyle * style, const QString & pmKey = QString())
Definition at line 580 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawComplexControl(), QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(QLS(part), state, shadow, rect.size()) % pmKey;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_shadow(style, pixmap, state, shadow, NULL,
                                          gtkWidget, part, 0, 0, rect.width(), rect.height()));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintSlider()
void QGtkPainter::paintSlider (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkShadowType shadow, GtkStyle * style, GtkOrientation orientation, const QString & pmKey = QString())
Definition at line 551 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawComplexControl(), and setUsePixmapCache().
 {
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(QLS(part), state, shadow, rect.size(), gtkWidget) % pmKey;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_slider (style,
                                           pixmap,
                                           state,
                                           shadow,
                                           NULL,
                                           gtkWidget,
                                           part,
                                           0, 0,
                                           rect.width(),
                                           rect.height(),
                                           orientation));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
paintVline()
void QGtkPainter::paintVline (GtkWidget * gtkWidget, const gchar * part, const QRect & rect, GtkStateType state, GtkStyle * style, int y1, int y2, int x, const QString & pmKey = QString())
Definition at line 382 of file qgtkpainter.cpp.
Referenced by QGtkStyle::drawComplexControl(), QGtkStyle::drawPrimitive(), and setUsePixmapCache().
 {
     if (!rect.isValid())
         return;
     QPixmap cache;
     QString pixmapName = uniqueName(QLS(part), state, GTK_SHADOW_NONE, rect.size(), gtkWidget)
                         % HexString<int>(y1)
                         % HexString<int>(y2)
                         % HexString<int>(x)
                         % pmKey;
     if (!m_usePixmapCache || !QPixmapCache::find(pixmapName, cache)) {
         DRAW_TO_CACHE(QGtkStylePrivate::gtk_paint_vline (style,
                                          pixmap,
                                          state,
                                          NULL,
                                          gtkWidget,
                                          part,
                                          y1, y2,
                                          x));
         if (m_usePixmapCache)
             QPixmapCache::insert(pixmapName, cache);
     }
     m_painter->drawPixmap(rect.topLeft(), cache);
 }
renderTheme()
QPixmap QGtkPainter::renderTheme (uchar * bdata, uchar * wdata, const QRect & rect) private
Definition at line 79 of file qgtkpainter.cpp.
Referenced by setUsePixmapCache().
 {
     const int bytecount = rect.width() * rect.height() * 4;
     for (int index = 0; index < bytecount ; index += 4) {
         uchar val = bdata[index + GTK_BLUE];
         if (m_alpha) {
             int alphaval = qMax(bdata[index + GTK_BLUE] - wdata[index + GTK_BLUE],
                                 bdata[index + GTK_GREEN] - wdata[index + GTK_GREEN]);
             alphaval = qMax(alphaval, bdata[index + GTK_RED] - wdata[index + GTK_RED]) + 255;
             bdata[index + QT_ALPHA] = alphaval;
         }
         bdata[index + QT_RED] = bdata[index + GTK_RED];
         bdata[index + QT_GREEN] = bdata[index + GTK_GREEN];
         bdata[index + QT_BLUE] = val;
     }
     QImage converted((const uchar*)bdata, rect.width(), rect.height(), m_alpha ?
                      QImage::Format_ARGB32_Premultiplied : QImage::Format_RGB32);
     if (m_hflipped || m_vflipped) {
         return QPixmap::fromImage(converted.mirrored(m_hflipped, m_vflipped));
     } else {
         // on raster graphicssystem we need to do a copy here, because
         // we intend to deallocate the qimage bits shortly after...
         return QPixmap::fromImage(converted.copy());
     }
 }
setAlphaSupport()
void QGtkPainter::setAlphaSupport (bool value) inline
Definition at line 75 of file qgtkpainter_p.h.
Referenced by QGtkStyle::drawPrimitive().
 { m_alpha = value; }
setClipRect()
void QGtkPainter::setClipRect (const QRect & rect) inline
Definition at line 76 of file qgtkpainter_p.h.
Referenced by QGtkStyle::drawComplexControl(), QGtkStyle::drawControl(), and QGtkStyle::drawPrimitive().
 { m_cliprect = rect; }
setFlipHorizontal()
void QGtkPainter::setFlipHorizontal (bool value) inline
Definition at line 77 of file qgtkpainter_p.h.
Referenced by QGtkStyle::drawControl().
 { m_hflipped = value; }
setFlipVertical()
void QGtkPainter::setFlipVertical (bool value) inline
Definition at line 78 of file qgtkpainter_p.h.
 { m_vflipped = value; }
setUsePixmapCache()
void QGtkPainter::setUsePixmapCache (bool value) inline
Definition at line 79 of file qgtkpainter_p.h.
Referenced by QGtkStyle::drawComplexControl(), and QGtkStyle::drawPrimitive().
 { m_usePixmapCache = value; }
Properties
m_alpha
bool QGtkPainter::m_alpha private
Definition at line 117 of file qgtkpainter_p.h.
Referenced by renderTheme(), and setAlphaSupport().
m_cliprect
QRect QGtkPainter::m_cliprect private
Definition at line 121 of file qgtkpainter_p.h.
Referenced by paintArrow(), paintCheckbox(), paintOption(), and setClipRect().
m_hflipped
bool QGtkPainter::m_hflipped private
Definition at line 118 of file qgtkpainter_p.h.
Referenced by renderTheme(), and setFlipHorizontal().
m_painter
QPainter* QGtkPainter::m_painter private
Definition at line 116 of file qgtkpainter_p.h.
Referenced by paintArrow(), paintBox(), paintBoxGap(), paintCheckbox(), paintExpander(), paintExtention(), paintFlatBox(), paintFocus(), paintHandle(), paintHline(), paintOption(), paintResizeGrip(), paintShadow(), paintSlider(), and paintVline().
m_usePixmapCache
bool QGtkPainter::m_usePixmapCache private
Definition at line 120 of file qgtkpainter_p.h.
Referenced by paintArrow(), paintBox(), paintBoxGap(), paintCheckbox(), paintExpander(), paintExtention(), paintFlatBox(), paintFocus(), paintHandle(), paintHline(), paintOption(), paintResizeGrip(), paintShadow(), paintSlider(), paintVline(), and setUsePixmapCache().
m_vflipped
bool QGtkPainter::m_vflipped private
Definition at line 119 of file qgtkpainter_p.h.
Referenced by renderTheme(), and setFlipVertical().
m_window
GtkWidget* QGtkPainter::m_window private
Definition at line 115 of file qgtkpainter_p.h.
The documentation for this class was generated from the following files:
/src/gui/styles/qgtkpainter_p.h
/src/gui/styles/qgtkpainter.cpp