Qt 4.8: QDeclarativeEngineDebugPrivate Class Reference
QDeclarativeEngineDebugPrivate Class Reference
Public Functions
void decode (QDataStream &, QDeclarativeDebugContextReference &)
void decode (QDataStream &, QDeclarativeDebugObjectReference &, bool simple)
int getId ()
void message (const QByteArray &)
QDeclarativeEngineDebugPrivate (QDeclarativeDebugConnection *)
void statusChanged (QDeclarativeEngineDebug::Status status)
~QDeclarativeEngineDebugPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static void remove (QDeclarativeEngineDebug *, QDeclarativeDebugEnginesQuery *)
static void remove (QDeclarativeEngineDebug *, QDeclarativeDebugRootContextQuery *)
static void remove (QDeclarativeEngineDebug *, QDeclarativeDebugObjectQuery *)
static void remove (QDeclarativeEngineDebug *, QDeclarativeDebugExpressionQuery *)
static void remove (QDeclarativeEngineDebug *, QDeclarativeDebugWatch *)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QDeclarativeEngineDebugClient * client
QHash< int, QDeclarativeDebugEnginesQuery * > enginesQuery
QHash< int, QDeclarativeDebugExpressionQuery * > expressionQuery
int nextId
QHash< int, QDeclarativeDebugObjectQuery * > objectQuery
QHash< int, QDeclarativeDebugRootContextQuery * > rootContextQuery
QHash< int, QDeclarativeDebugWatch * > watched
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 66 of file qdeclarativeenginedebug.cpp.
Constructors and Destructors
QDeclarativeEngineDebugPrivate()
QDeclarativeEngineDebugPrivate::QDeclarativeEngineDebugPrivate (QDeclarativeDebugConnection * c)
Definition at line 115 of file qdeclarativeenginedebug.cpp.
 : client(new QDeclarativeEngineDebugClient(c, this)), nextId(0)
 {
 }
~QDeclarativeEngineDebugPrivate()
QDeclarativeEngineDebugPrivate::~QDeclarativeEngineDebugPrivate ()
Definition at line 120 of file qdeclarativeenginedebug.cpp.
 {
     if (client)
         client->priv = 0;
     delete client;
     QHash<int, QDeclarativeDebugEnginesQuery*>::iterator enginesIter = enginesQuery.begin();
     for (; enginesIter != enginesQuery.end(); ++enginesIter) {
         enginesIter.value()->m_client = 0;
         if (enginesIter.value()->state() == QDeclarativeDebugQuery::Waiting)
             enginesIter.value()->setState(QDeclarativeDebugQuery::Error);
     }
     QHash<int, QDeclarativeDebugRootContextQuery*>::iterator rootContextIter = rootContextQuery.begin();
     for (; rootContextIter != rootContextQuery.end(); ++rootContextIter) {
         rootContextIter.value()->m_client = 0;
         if (rootContextIter.value()->state() == QDeclarativeDebugQuery::Waiting)
             rootContextIter.value()->setState(QDeclarativeDebugQuery::Error);
     }
     QHash<int, QDeclarativeDebugObjectQuery*>::iterator objectIter = objectQuery.begin();
     for (; objectIter != objectQuery.end(); ++objectIter) {
         objectIter.value()->m_client = 0;
         if (objectIter.value()->state() == QDeclarativeDebugQuery::Waiting)
             objectIter.value()->setState(QDeclarativeDebugQuery::Error);
     }
     QHash<int, QDeclarativeDebugExpressionQuery*>::iterator exprIter = expressionQuery.begin();
     for (; exprIter != expressionQuery.end(); ++exprIter) {
         exprIter.value()->m_client = 0;
         if (exprIter.value()->state() == QDeclarativeDebugQuery::Waiting)
             exprIter.value()->setState(QDeclarativeDebugQuery::Error);
     }
     QHash<int, QDeclarativeDebugWatch*>::iterator watchIter = watched.begin();
     for (; watchIter != watched.end(); ++watchIter) {
         watchIter.value()->m_client = 0;
         watchIter.value()->setState(QDeclarativeDebugWatch::Dead);
     }
 }
Functions
decode() [1/2]
void QDeclarativeEngineDebugPrivate::decode (QDataStream & ds, QDeclarativeDebugContextReference & c)
Definition at line 270 of file qdeclarativeenginedebug.cpp.
Referenced by decode(), and message().
 {
     ds >> c.m_name >> c.m_debugId;
     int contextCount;
     ds >> contextCount;
     for (int ii = 0; ii < contextCount; ++ii) {
         c.m_contexts.append(QDeclarativeDebugContextReference());
         decode(ds, c.m_contexts.last());
     }
     int objectCount;
     ds >> objectCount;
     for (int ii = 0; ii < objectCount; ++ii) {
         QDeclarativeDebugObjectReference obj;
         decode(ds, obj, true);
         obj.m_contextDebugId = c.m_debugId;
         c.m_objects << obj;
     }
 }
decode() [2/2]
void QDeclarativeEngineDebugPrivate::decode (QDataStream & ds, QDeclarativeDebugObjectReference & o, bool simple)
Definition at line 207 of file qdeclarativeenginedebug.cpp.
 {
     QDeclarativeEngineDebugService::QDeclarativeObjectData data;
     ds >> data;
     o.m_debugId = data.objectId;
     o.m_class = data.objectType;
     o.m_idString = data.idString;
     o.m_name = data.objectName;
     o.m_source.m_url = data.url;
     o.m_source.m_lineNumber = data.lineNumber;
     o.m_source.m_columnNumber = data.columnNumber;
     o.m_contextDebugId = data.contextId;
     o.m_parentId = data.parentId;
     o.m_needsMoreData = simple;
     if (simple)
         return;
     int childCount;
     bool recur;
     ds >> childCount >> recur;
     for (int ii = 0; ii < childCount; ++ii) {
         o.m_children.append(QDeclarativeDebugObjectReference());
         decode(ds, o.m_children.last(), !recur);
     }
     int propCount;
     ds >> propCount;
     for (int ii = 0; ii < propCount; ++ii) {
         QDeclarativeEngineDebugService::QDeclarativeObjectProperty data;
         ds >> data;
         QDeclarativeDebugPropertyReference prop;
         prop.m_objectDebugId = o.m_debugId;
         prop.m_name = data.name;
         prop.m_binding = data.binding;
         prop.m_hasNotifySignal = data.hasNotifySignal;
         prop.m_valueTypeName = data.valueTypeName;
         switch (data.type) {
             case QDeclarativeEngineDebugService::QDeclarativeObjectProperty::Basic:
             case QDeclarativeEngineDebugService::QDeclarativeObjectProperty::List:
             case QDeclarativeEngineDebugService::QDeclarativeObjectProperty::SignalProperty:
             case QDeclarativeEngineDebugService::QDeclarativeObjectProperty::Variant:
             {
                 prop.m_value = data.value;
                 break;
             }
             case QDeclarativeEngineDebugService::QDeclarativeObjectProperty::Object:
             {
                 QDeclarativeDebugObjectReference obj;
                 obj.m_debugId = prop.m_value.toInt();
                 prop.m_value = QVariant::fromValue(obj);
                 break;
             }
             case QDeclarativeEngineDebugService::QDeclarativeObjectProperty::Unknown:
                 break;
         }
         o.m_properties << prop;
     }
 }
getId()
int QDeclarativeEngineDebugPrivate::getId ()
Definition at line 161 of file qdeclarativeenginedebug.cpp.
 {
     return nextId++;
 }
message()
void QDeclarativeEngineDebugPrivate::message (const QByteArray & data)
Definition at line 299 of file qdeclarativeenginedebug.cpp.
Referenced by QDeclarativeEngineDebugClient::messageReceived().
 {
     QDataStream ds(data);
     QByteArray type;
     ds >> type;
     //qDebug() << "QDeclarativeEngineDebugPrivate::message()" << type;
     if (type == "LIST_ENGINES_R") {
         int queryId;
         ds >> queryId;
         QDeclarativeDebugEnginesQuery *query = enginesQuery.value(queryId);
         if (!query)
             return;
         enginesQuery.remove(queryId);
         int count;
         ds >> count;
         for (int ii = 0; ii < count; ++ii) {
             QDeclarativeDebugEngineReference ref;
             ds >> ref.m_name;
             ds >> ref.m_debugId;
             query->m_engines << ref;
         }
         query->m_client = 0;
         query->setState(QDeclarativeDebugQuery::Completed);
     } else if (type == "LIST_OBJECTS_R") {
         int queryId;
         ds >> queryId;
         QDeclarativeDebugRootContextQuery *query = rootContextQuery.value(queryId);
         if (!query)
             return;
         rootContextQuery.remove(queryId);
         if (!ds.atEnd())
             decode(ds, query->m_context);
         query->m_client = 0;
         query->setState(QDeclarativeDebugQuery::Completed);
     } else if (type == "FETCH_OBJECT_R") {
         int queryId;
         ds >> queryId;
         QDeclarativeDebugObjectQuery *query = objectQuery.value(queryId);
         if (!query)
             return;
         objectQuery.remove(queryId);
         if (!ds.atEnd())
             decode(ds, query->m_object, false);
         query->m_client = 0;
         query->setState(QDeclarativeDebugQuery::Completed);
     } else if (type == "EVAL_EXPRESSION_R") {
         int queryId;
         QVariant result;
         ds >> queryId >> result;
         QDeclarativeDebugExpressionQuery *query = expressionQuery.value(queryId);
         if (!query)
             return;
         expressionQuery.remove(queryId);
         query->m_result = result;
         query->m_client = 0;
         query->setState(QDeclarativeDebugQuery::Completed);
     } else if (type == "WATCH_PROPERTY_R") {
         int queryId;
         bool ok;
         ds >> queryId >> ok;
         QDeclarativeDebugWatch *watch = watched.value(queryId);
         if (!watch)
             return;
         watch->setState(ok ? QDeclarativeDebugWatch::Active : QDeclarativeDebugWatch::Inactive);
     } else if (type == "WATCH_OBJECT_R") {
         int queryId;
         bool ok;
         ds >> queryId >> ok;
         QDeclarativeDebugWatch *watch = watched.value(queryId);
         if (!watch)
             return;
         watch->setState(ok ? QDeclarativeDebugWatch::Active : QDeclarativeDebugWatch::Inactive);
     } else if (type == "WATCH_EXPR_OBJECT_R") {
         int queryId;
         bool ok;
         ds >> queryId >> ok;
         QDeclarativeDebugWatch *watch = watched.value(queryId);
         if (!watch)
             return;
         watch->setState(ok ? QDeclarativeDebugWatch::Active : QDeclarativeDebugWatch::Inactive);
     } else if (type == "UPDATE_WATCH") {
         int queryId;
         int debugId;
         QByteArray name;
         QVariant value;
         ds >> queryId >> debugId >> name >> value;
         QDeclarativeDebugWatch *watch = watched.value(queryId, 0);
         if (!watch)
             return;
         emit watch->valueChanged(name, value);
     } else if (type == "OBJECT_CREATED") {
         emit q_func()->newObjects();
     }
 }
remove() [1/5]
void QDeclarativeEngineDebugPrivate::remove (QDeclarativeEngineDebug * c, QDeclarativeDebugEnginesQuery * q) static
Definition at line 166 of file qdeclarativeenginedebug.cpp.
Referenced by QDeclarativeDebugEnginesQuery::~QDeclarativeDebugEnginesQuery(), QDeclarativeDebugExpressionQuery::~QDeclarativeDebugExpressionQuery(), QDeclarativeDebugObjectQuery::~QDeclarativeDebugObjectQuery(), QDeclarativeDebugRootContextQuery::~QDeclarativeDebugRootContextQuery(), and QDeclarativeDebugWatch::~QDeclarativeDebugWatch().
 {
     if (c && q) {
         QDeclarativeEngineDebugPrivate *p = (QDeclarativeEngineDebugPrivate *)QObjectPrivate::get(c);
         p->enginesQuery.remove(q->m_queryId);
     }
 }
remove() [2/5]
void QDeclarativeEngineDebugPrivate::remove (QDeclarativeEngineDebug * c, QDeclarativeDebugRootContextQuery * q) static
Definition at line 174 of file qdeclarativeenginedebug.cpp.
 {
     if (c && q) {
         QDeclarativeEngineDebugPrivate *p = (QDeclarativeEngineDebugPrivate *)QObjectPrivate::get(c);
         p->rootContextQuery.remove(q->m_queryId);
     }
 }
remove() [3/5]
void QDeclarativeEngineDebugPrivate::remove (QDeclarativeEngineDebug * c, QDeclarativeDebugObjectQuery * q) static
Definition at line 183 of file qdeclarativeenginedebug.cpp.
 {
     if (c && q) {
         QDeclarativeEngineDebugPrivate *p = (QDeclarativeEngineDebugPrivate *)QObjectPrivate::get(c);
         p->objectQuery.remove(q->m_queryId);
     }
 }
remove() [4/5]
void QDeclarativeEngineDebugPrivate::remove (QDeclarativeEngineDebug * c, QDeclarativeDebugExpressionQuery * q) static
Definition at line 191 of file qdeclarativeenginedebug.cpp.
 {
     if (c && q) {
         QDeclarativeEngineDebugPrivate *p = (QDeclarativeEngineDebugPrivate *)QObjectPrivate::get(c);
         p->expressionQuery.remove(q->m_queryId);
     }
 }
remove() [5/5]
void QDeclarativeEngineDebugPrivate::remove (QDeclarativeEngineDebug * c, QDeclarativeDebugWatch * w) static
Definition at line 199 of file qdeclarativeenginedebug.cpp.
 {
     if (c && w) {
         QDeclarativeEngineDebugPrivate *p = (QDeclarativeEngineDebugPrivate *)QObjectPrivate::get(c);
         p->watched.remove(w->m_queryId);
     }
 }
statusChanged()
void QDeclarativeEngineDebugPrivate::statusChanged (QDeclarativeEngineDebug::Status status)
Definition at line 294 of file qdeclarativeenginedebug.cpp.
Referenced by QDeclarativeEngineDebugClient::statusChanged().
 {
     emit q_func()->statusChanged(status);
 }
Properties
client
QDeclarativeEngineDebugClient* QDeclarativeEngineDebugPrivate::client
Definition at line 76 of file qdeclarativeenginedebug.cpp.
Referenced by ~QDeclarativeEngineDebugPrivate().
enginesQuery
QHash<int, QDeclarativeDebugEnginesQuery *> QDeclarativeEngineDebugPrivate::enginesQuery
Definition at line 89 of file qdeclarativeenginedebug.cpp.
Referenced by message(), remove(), and ~QDeclarativeEngineDebugPrivate().
expressionQuery
QHash<int, QDeclarativeDebugExpressionQuery *> QDeclarativeEngineDebugPrivate::expressionQuery
Definition at line 92 of file qdeclarativeenginedebug.cpp.
Referenced by message(), remove(), and ~QDeclarativeEngineDebugPrivate().
nextId
int QDeclarativeEngineDebugPrivate::nextId
Definition at line 77 of file qdeclarativeenginedebug.cpp.
Referenced by getId().
objectQuery
QHash<int, QDeclarativeDebugObjectQuery *> QDeclarativeEngineDebugPrivate::objectQuery
Definition at line 91 of file qdeclarativeenginedebug.cpp.
Referenced by message(), remove(), and ~QDeclarativeEngineDebugPrivate().
rootContextQuery
QHash<int, QDeclarativeDebugRootContextQuery *> QDeclarativeEngineDebugPrivate::rootContextQuery
Definition at line 90 of file qdeclarativeenginedebug.cpp.
Referenced by message(), remove(), and ~QDeclarativeEngineDebugPrivate().
watched
QHash<int, QDeclarativeDebugWatch *> QDeclarativeEngineDebugPrivate::watched
Definition at line 94 of file qdeclarativeenginedebug.cpp.
Referenced by message(), remove(), and ~QDeclarativeEngineDebugPrivate().
The documentation for this class was generated from the following file:
/src/declarative/debugger/qdeclarativeenginedebug.cpp