Qt 4.8: QPlatformGLContext Class Reference
QPlatformGLContext Class Reference abstract
The QPlatformGLContext class provides an abstraction for native GL contexts.
#include <qplatformglcontext_qpa.h>
Public Functions
virtual void doneCurrent ()
Reimplement in subclass to release current context.
virtual void * getProcAddress (const QString &procName)=0
Reimplement in subclass to native getProcAddr calls.
virtual void makeCurrent ()
Reimplement in subclass to do makeCurrent on native GL context.
virtual QPlatformWindowFormat platformWindowFormat () const =0
QWidget has the function qplatformWindowFormat().
QPlatformGLContext ()
All subclasses needs to specify the platformWindow.
virtual void swapBuffers ()=0
Reimplement in subclass to native swap buffers calls.
virtual ~QPlatformGLContext ()
If this is the current context for the thread, doneCurrent is called.
Static Public Functions
static const QPlatformGLContext * currentContext ()
Returns the last context which called makeCurrent.
Protected Variables
QScopedPointer< QPlatformGLContextPrivate > d_ptr
Private Functions
void deleteQGLContext ()
Q_DECLARE_PRIVATE (QPlatformGLContext)
Q_DISABLE_COPY (QPlatformGLContext)
void * qGLContextHandle () const
void setQGLContextHandle (void *handle, void(*qGLContextDeleteFunction)(void *))
Friends
class QGLContext
class QWidgetPrivate
Detailed Description
The QPlatformGLContext class provides an abstraction for native GL contexts.
Since
4.8
Warning
This function is not part of the public interface. This function is under development and subject to change.
In QPA the way to support OpenGL or OpenVG or other technologies that requires a native GL context is through the QPlatformGLContext wrapper.
There is no factory function for QPlatformGLContexts, but rather only one accessor function. The only place to retrieve a QPlatformGLContext from is through a QPlatformWindow.
The context which is current for a specific thread can be collected by the currentContext() function. This is how QPlatformGLContext also makes it possible to use the QtOpenGL module withhout using QGLWidget. When using QGLContext::currentContext(), it will ask QPlatformGLContext for the currentContext. Then a corresponding QGLContext will be returned, which maps to the QPlatformGLContext.
Definition at line 56 of file qplatformglcontext_qpa.h.
Constructors and Destructors
QPlatformGLContext()
QPlatformGLContext::QPlatformGLContext () explicit
All subclasses needs to specify the platformWindow.
It can be a null window.
Definition at line 112 of file qplatformglcontext_qpa.cpp.
     :d_ptr(new QPlatformGLContextPrivate())
 {
 }
~QPlatformGLContext()
QPlatformGLContext::~QPlatformGLContext () virtual
If this is the current context for the thread, doneCurrent is called.
Definition at line 120 of file qplatformglcontext_qpa.cpp.
 {
     if (QPlatformGLContext::currentContext() == this) {
         doneCurrent();
     }
 }
Functions
currentContext()
const QPlatformGLContext * QPlatformGLContext::currentContext () static
Returns the last context which called makeCurrent.
This function is thread aware.
Definition at line 100 of file qplatformglcontext_qpa.cpp.
Referenced by QDri2Context::QDri2Context(), QWaylandGLContext::setEglSurface(), QWaylandReadbackEglContext::swapBuffers(), QWaylandReadbackGlxContext::swapBuffers(), and ~QPlatformGLContext().
 {
     QPlatformGLThreadContext *threadContext = qplatformgl_context_storage.localData();
     if(threadContext) {
         return threadContext->context;
     }
     return 0;
 }
deleteQGLContext()
void QPlatformGLContext::deleteQGLContext () private
Definition at line 162 of file qplatformglcontext_qpa.cpp.
 {
     Q_D(QPlatformGLContext);
     if (d->qGLContextDeleteFunction && d->qGLContextHandle) {
         d->qGLContextDeleteFunction(d->qGLContextHandle);
         d->qGLContextDeleteFunction = 0;
         d->qGLContextHandle = 0;
     }
 }
doneCurrent()
void QPlatformGLContext::doneCurrent () virtual
Reimplement in subclass to release current context.
Typically this is calling makeCurrent with 0 "surface"
Reimplemented in EAGLPlatformContext, QBBGLContext, QGLXContext, QWaylandXCompositeGLXContext, QGLXContext, QWaylandReadbackEglContext, QWaylandReadbackGlxContext, QWaylandXCompositeEGLContext, QDri2Context, QWaylandGLContext, QDirectFbGLContext, and QEGLPlatformContext.
Definition at line 140 of file qplatformglcontext_qpa.cpp.
Referenced by QDirectFbGLContext::doneCurrent(), QEGLPlatformContext::doneCurrent(), QWaylandGLContext::doneCurrent(), QWaylandReadbackGlxContext::doneCurrent(), QWaylandXCompositeEGLContext::doneCurrent(), QWaylandReadbackEglContext::doneCurrent(), QDri2Context::doneCurrent(), QGLXContext::doneCurrent(), QWaylandXCompositeGLXContext::doneCurrent(), QBBGLContext::doneCurrent(), EAGLPlatformContext::doneCurrent(), QGLXContext::QGLXContext(), ~QPlatformGLContext(), and QPlatformGLThreadContext::~QPlatformGLThreadContext().
 {
     QPlatformGLContextPrivate::setCurrentContext(0);
 }
getProcAddress()
void * QPlatformGLContext::getProcAddress (const QString & procName) pure virtual
Reimplement in subclass to native getProcAddr calls.
Note: its convenient to use qPrintable(const QString &str) to get the const char * pointer
Implemented in EAGLPlatformContext, QBBGLContext, QGLXContext, QWaylandXCompositeGLXContext, QGLXContext, QWaylandReadbackEglContext, QWaylandReadbackGlxContext, QWaylandXCompositeEGLContext, QDri2Context, QWaylandGLContext, QDirectFbGLContext, and QEGLPlatformContext.
makeCurrent()
void QPlatformGLContext::makeCurrent () virtual
Reimplement in subclass to do makeCurrent on native GL context.
Reimplemented in EAGLPlatformContext, QBBGLContext, QGLXContext, QWaylandXCompositeGLXContext, QGLXContext, QWaylandReadbackEglContext, QWaylandReadbackGlxContext, QWaylandXCompositeEGLContext, QDri2Context, QWaylandGLContext, QDirectFbGLContext, and QEGLPlatformContext.
Definition at line 131 of file qplatformglcontext_qpa.cpp.
Referenced by QDirectFbGLContext::makeCurrent(), QEGLPlatformContext::makeCurrent(), QWaylandGLContext::makeCurrent(), QWaylandReadbackEglContext::makeCurrent(), QWaylandXCompositeEGLContext::makeCurrent(), QDri2Context::makeCurrent(), QWaylandReadbackGlxContext::makeCurrent(), QGLXContext::makeCurrent(), QWaylandXCompositeGLXContext::makeCurrent(), QBBGLContext::makeCurrent(), EAGLPlatformContext::makeCurrent(), and QGLXContext::QGLXContext().
 {
     QPlatformGLContextPrivate::setCurrentContext(this);
 }
platformWindowFormat()
QPlatformWindowFormat QPlatformGLContext::platformWindowFormat () const pure virtual
QWidget has the function qplatformWindowFormat().
That function is for the application programmer to request the format of the window and the context that he wants.
Reimplement this function in a subclass to indicate what format the glContext actually has.
Implemented in EAGLPlatformContext, QGLXContext, QBBGLContext, QWaylandXCompositeGLXContext, QGLXContext, QDri2Context, QWaylandReadbackEglContext, QWaylandReadbackGlxContext, QWaylandXCompositeEGLContext, QWaylandGLContext, QDirectFbGLContext, and QEGLPlatformContext.
Referenced by QGLWidget::event().
Q_DECLARE_PRIVATE()
QPlatformGLContext::Q_DECLARE_PRIVATE (QPlatformGLContext) private
Q_DISABLE_COPY()
QPlatformGLContext::Q_DISABLE_COPY (QPlatformGLContext) private
qGLContextHandle()
void * QPlatformGLContext::qGLContextHandle () const private
Definition at line 149 of file qplatformglcontext_qpa.cpp.
Referenced by QGLWidget::event().
 {
     Q_D(const QPlatformGLContext);
     return d->qGLContextHandle;
 }
setQGLContextHandle()
void QPlatformGLContext::setQGLContextHandle (void * handle, void(*)(void *) qGLContextDeleteFunction) private
Definition at line 155 of file qplatformglcontext_qpa.cpp.
 {
     Q_D(QPlatformGLContext);
     d->qGLContextHandle = handle;
     d->qGLContextDeleteFunction = qGLContextDeleteFunction;
 }
swapBuffers()
void QPlatformGLContext::swapBuffers () pure virtual
Reimplement in subclass to native swap buffers calls.
Implemented in EAGLPlatformContext, QBBGLContext, QGLXContext, QWaylandXCompositeGLXContext, QGLXContext, QWaylandReadbackEglContext, QWaylandReadbackGlxContext, QWaylandXCompositeEGLContext, QDri2Context, QWaylandGLContext, QDirectFbGLContext, and QEGLPlatformContext.
Referenced by QWaylandGLWindowSurface::flush().
Friends and Related Functions
QGLContext
friend class QGLContext friend
Definition at line 78 of file qplatformglcontext_qpa.h.
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 79 of file qplatformglcontext_qpa.h.
Properties
d_ptr
QScopedPointer<QPlatformGLContextPrivate> QPlatformGLContext::d_ptr protected
Definition at line 74 of file qplatformglcontext_qpa.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qplatformglcontext_qpa.h
/src/gui/kernel/qplatformglcontext_qpa.cpp