Qt 4.8: QWaylandWindow Class Reference
QWaylandWindow Class Reference abstract
#include <qwaylandwindow.h>
Public Types
enum WindowType { Shm, Egl }
Public Functions
void attach (QWaylandBuffer *buffer)
void configure (uint32_t time, uint32_t edges, int32_t x, int32_t y, int32_t width, int32_t height)
void damage (const QRect &rect)
QWaylandWindow (QWidget *window)
void setParent (const QPlatformWindow *parent)
This function is called to enable native child widgets in QPA.
void setVisible (bool visible)
Reimplemented in subclasses to show the surface if visible is true, and hide it if visible is false.
void waitForFrameSync ()
virtual WindowType windowType () const =0
WId winId () const
Reimplement in subclasses to return a handle to the native window.
struct wl_surface * wl_surface () const
~QWaylandWindow ()
Public Functions inherited from QPlatformWindow
virtual QRect geometry () const
Returnes the current geometry of a window.
virtual QPlatformGLContext * glContext () const
Reimplement to return the glContext associated with the window.
virtual void lower ()
Reimplement to be able to let Qt lower windows to the bottom of the desktop.
QPlatformWindow (QWidget *tlw)
Constructs a platform window with the given top level widget.
virtual void raise ()
Reimplement to be able to let Qt rais windows to the top of the desktop.
virtual void requestActivateWindow ()
Reimplement to let Qt be able to request activation/focus for a window.
virtual void setGeometry (const QRect &rect)
This function is called by Qt whenever a window is moved or the window is resized.
virtual void setOpacity (qreal level)
Reimplement to be able to let Qt set the opacity level of a window.
virtual Qt::WindowFlags setWindowFlags (Qt::WindowFlags flags)
Requests setting the window flags of this surface to type.
virtual void setWindowTitle (const QString &title)
Reimplement to set the window title to title.
QWidget * widget () const
Returnes the widget which belongs to the QPlatformWindow.
virtual Qt::WindowFlags windowFlags () const
Returns the effective window flags for this surface.
virtual ~QPlatformWindow ()
Virtual destructor does not delete its top level widget.
Protected Functions
virtual void newSurfaceCreated ()
Protected Variables
QWaylandBuffer * mBuffer
QWaylandDisplay * mDisplay
QWaitCondition mFrameSyncWait
struct wl_surface * mSurface
bool mWaitingForFrameSync
WId mWindowId
Protected Variables inherited from QPlatformWindow
QScopedPointer< QPlatformWindowPrivate > d_ptr
Static Private Functions
static void frameCallback (struct wl_surface *surface, void *data, uint32_t time)
Detailed Description
Definition at line 54 of file qwaylandwindow.h.
Enumerations
WindowType
enum QWaylandWindow::WindowType
Enumerator
Shm
Egl
Definition at line 57 of file qwaylandwindow.h.
                     {
         Shm,
         Egl
     };
Constructors and Destructors
QWaylandWindow()
QWaylandWindow::QWaylandWindow (QWidget * window)
Definition at line 59 of file qwaylandwindow.cpp.
     : QPlatformWindow(window)
     , mSurface(0)
     , mDisplay(QWaylandScreen::waylandScreenFromWidget(window)->display())
     , mBuffer(0)
     , mWaitingForFrameSync(false)
 {
     static WId id = 1;
     mWindowId = id++;
 #ifdef QT_WAYLAND_WINDOWMANAGER_SUPPORT
         mDisplay->windowManagerIntegration()->mapClientToProcess(qApp->applicationPid());
         mDisplay->windowManagerIntegration()->authenticateWithToken();
 #endif
 }
~QWaylandWindow()
QWaylandWindow::~QWaylandWindow ()
Definition at line 75 of file qwaylandwindow.cpp.
 {
     if (mSurface)
         wl_surface_destroy(mSurface);
     QList<QWaylandInputDevice *> inputDevices = mDisplay->inputDevices();
     for (int i = 0; i < inputDevices.size(); ++i)
         inputDevices.at(i)->handleWindowDestroyed(this);
 }
Functions
attach()
void QWaylandWindow::attach (QWaylandBuffer * buffer)
Definition at line 122 of file qwaylandwindow.cpp.
Referenced by QWaylandReadbackEglContext::geometryChanged(), QWaylandReadbackGlxContext::geometryChanged(), QWaylandXCompositeEGLContext::geometryChanged(), QWaylandXCompositeGLXContext::geometryChanged(), and QWaylandShmWindowSurface::resize().
 {
     mBuffer = buffer;
     if (mSurface) {
         wl_surface_attach(mSurface, buffer->buffer(),0,0);
     }
 }
configure()
void QWaylandWindow::configure (uint32_t time, uint32_t edges, int32_t x, int32_t y, int32_t width, int32_t height)
Definition at line 109 of file qwaylandwindow.cpp.
Referenced by QWaylandDisplay::shellHandleConfigure().
 {
     Q_UNUSED(time);
     Q_UNUSED(edges);
     QRect geometry = QRect(x, y, width, height);
     setGeometry(geometry);
     QWindowSystemInterface::handleGeometryChange(widget(), geometry);
 }
damage()
void QWaylandWindow::damage (const QRect & rect)
Definition at line 130 of file qwaylandwindow.cpp.
Referenced by QWaylandShmWindowSurface::flush(), QWaylandReadbackGlxContext::swapBuffers(), QWaylandReadbackEglContext::swapBuffers(), QWaylandXCompositeEGLContext::swapBuffers(), and QWaylandXCompositeGLXContext::swapBuffers().
 {
     //We have to do sync stuff before calling damage, or we might
     //get a frame callback before we get the timestamp
     if (!mWaitingForFrameSync) {
         mDisplay->frameCallback(QWaylandWindow::frameCallback, mSurface, this);
         mWaitingForFrameSync = true;
     }
     wl_surface_damage(mSurface,
                       rect.x(), rect.y(), rect.width(), rect.height());
 }
frameCallback()
void QWaylandWindow::frameCallback (struct wl_surface * surface, void * data, uint32_t time) static private
Definition at line 152 of file qwaylandwindow.cpp.
Referenced by damage().
 {
     Q_UNUSED(time);
     Q_UNUSED(surface);
     QWaylandWindow *self = static_cast<QWaylandWindow*>(data);
     self->mWaitingForFrameSync = false;
 }
newSurfaceCreated()
void QWaylandWindow::newSurfaceCreated () protected virtual
Reimplemented in QWaylandEglWindow.
Definition at line 143 of file qwaylandwindow.cpp.
Referenced by QWaylandShmWindow::QWaylandShmWindow(), and setVisible().
 {
     if (mBuffer) {
         wl_surface_attach(mSurface,mBuffer->buffer(),0,0);
         wl_surface_damage(mSurface,
                           0,0,mBuffer->size().width(),mBuffer->size().height());
     }
 }
setParent()
void QWaylandWindow::setParent (const QPlatformWindow * parent) virtual
This function is called to enable native child widgets in QPA.
It is common not to support this feature in Window systems, but can be faked. When this function is called all geometry of this platform window will be relative to the parent.
Reimplemented from QPlatformWindow.
Definition at line 90 of file qwaylandwindow.cpp.
 {
     Q_UNUSED(parent);
     qWarning("Sub window is not supported");
 }
setVisible()
void QWaylandWindow::setVisible (bool visible) virtual
Reimplemented in subclasses to show the surface if visible is true, and hide it if visible is false.
Reimplemented from QPlatformWindow.
Definition at line 96 of file qwaylandwindow.cpp.
 {
     if (!mSurface && visible) {
         mSurface = mDisplay->createSurface(this);
         newSurfaceCreated();
     }
     if (!visible) {
         wl_surface_destroy(mSurface);
         mSurface = NULL;
     }
 }
waitForFrameSync()
void QWaylandWindow::waitForFrameSync ()
Definition at line 160 of file qwaylandwindow.cpp.
Referenced by QWaylandShmWindowSurface::beginPaint(), QWaylandReadbackGlxContext::geometryChanged(), QWaylandReadbackEglContext::geometryChanged(), QWaylandReadbackEglContext::makeCurrent(), QWaylandReadbackGlxContext::swapBuffers(), QWaylandXCompositeEGLContext::swapBuffers(), and QWaylandXCompositeGLXContext::swapBuffers().
 {
     mDisplay->flushRequests();
     while (mWaitingForFrameSync)
         mDisplay->blockingReadEvents();
 }
windowType()
virtual WindowType QWaylandWindow::windowType () const pure virtual
Implemented in QWaylandEglWindow, QWaylandReadbackEglWindow, QWaylandShmWindow, QWaylandReadbackGlxWindow, QWaylandXCompositeEGLWindow, and QWaylandXCompositeGLXWindow.
winId()
WId QWaylandWindow::winId () const virtual
Reimplement in subclasses to return a handle to the native window.
Reimplemented from QPlatformWindow.
Definition at line 85 of file qwaylandwindow.cpp.
 {
     return mWindowId;
 }
wl_surface()
struct wl_surface* QWaylandWindow::wl_surface () const inline
Definition at line 78 of file qwaylandwindow.h.
 { return mSurface; }
Properties
mBuffer
QWaylandBuffer* QWaylandWindow::mBuffer protected
Definition at line 84 of file qwaylandwindow.h.
Referenced by attach(), and newSurfaceCreated().
mDisplay
QWaylandDisplay* QWaylandWindow::mDisplay protected
Definition at line 83 of file qwaylandwindow.h.
Referenced by damage(), QWaylandEglWindow::QWaylandEglWindow(), QWaylandWindow(), setVisible(), waitForFrameSync(), and ~QWaylandWindow().
mFrameSyncWait
QWaitCondition QWaylandWindow::mFrameSyncWait protected
Definition at line 87 of file qwaylandwindow.h.
mSurface
struct wl_surface* QWaylandWindow::mSurface protected
Definition at line 81 of file qwaylandwindow.h.
Referenced by attach(), damage(), QWaylandEglWindow::newSurfaceCreated(), newSurfaceCreated(), setVisible(), wl_surface(), and ~QWaylandWindow().
mWaitingForFrameSync
bool QWaylandWindow::mWaitingForFrameSync protected
Definition at line 86 of file qwaylandwindow.h.
Referenced by damage(), frameCallback(), and waitForFrameSync().
mWindowId
WId QWaylandWindow::mWindowId protected
Definition at line 85 of file qwaylandwindow.h.
Referenced by QWaylandWindow(), and winId().
The documentation for this class was generated from the following files:
/src/plugins/platforms/wayland/qwaylandwindow.h
/src/plugins/platforms/wayland/qwaylandwindow.cpp