Qt 4.8: QColor Class Reference
QColor Class Reference
The QColor class provides colors based on RGB, HSV or CMYK values.
#include <qcolor.h>
Public Types
enum Spec {
Invalid, Rgb, Hsv, Cmyk,
Hsl
}
The type of color specified, either RGB, HSV, CMYK or HSL.
Public Functions
int alpha () const
qreal alphaF () const
Returns the alpha color component of this color.
int black () const
qreal blackF () const
Returns the black color component of this color.
int blue () const
qreal blueF () const
Returns the blue color component of this color.
QColor convertTo (Spec colorSpec) const
Creates a copy of this color in the format specified by colorSpec.
int cyan () const
qreal cyanF () const
Returns the cyan color component of this color.
QColor dark (int f=200) const
Use darker(factor) instead.
QColor darker (int f=200) const
Returns a darker (or lighter) color, but does not change this object.
void getCmyk (int *c, int *m, int *y, int *k, int *a=0)
Sets the contents pointed to by c, m, y, k, and a, to the cyan, magenta, yellow, black, and alpha-channel (transparency) components of the color's CMYK value.
void getCmykF (qreal *c, qreal *m, qreal *y, qreal *k, qreal *a=0)
Sets the contents pointed to by c, m, y, k, and a, to the cyan, magenta, yellow, black, and alpha-channel (transparency) components of the color's CMYK value.
void getHsl (int *h, int *s, int *l, int *a=0) const
Sets the contents pointed to by h, s, l, and a, to the hue, saturation, lightness, and alpha-channel (transparency) components of the color's HSL value.
void getHslF (qreal *h, qreal *s, qreal *l, qreal *a=0) const
Sets the contents pointed to by h, s, l, and a, to the hue, saturation, lightness, and alpha-channel (transparency) components of the color's HSL value.
void getHsv (int *h, int *s, int *v, int *a=0) const
Sets the contents pointed to by h, s, v, and a, to the hue, saturation, value, and alpha-channel (transparency) components of the color's HSV value.
void getHsvF (qreal *h, qreal *s, qreal *v, qreal *a=0) const
Sets the contents pointed to by h, s, v, and a, to the hue, saturation, value, and alpha-channel (transparency) components of the color's HSV value.
void getRgb (int *r, int *g, int *b, int *a=0) const
Sets the contents pointed to by r, g, b, and a, to the red, green, blue, and alpha-channel (transparency) components of the color's RGB value.
void getRgbF (qreal *r, qreal *g, qreal *b, qreal *a=0) const
Sets the contents pointed to by r, g, b, and a, to the red, green, blue, and alpha-channel (transparency) components of the color's RGB value.
int green () const
qreal greenF () const
Returns the green color component of this color.
int hslHue () const
Returns the hue color component of this color.
qreal hslHueF () const
Returns the hue color component of this color.
int hslSaturation () const
Returns the saturation color component of this color.
qreal hslSaturationF () const
Returns the saturation color component of this color.
int hsvHue () const
Returns the hue color component of this color.
qreal hsvHueF () const
Returns the hue color component of this color.
int hsvSaturation () const
Returns the saturation color component of this color.
qreal hsvSaturationF () const
Returns the saturation color component of this color.
int hue () const
qreal hueF () const
Returns the hue color component of this color.
bool isValid () const
Returns true if the color is valid; otherwise returns false.
QColor light (int f=150) const
Use lighter(factor) instead.
QColor lighter (int f=150) const
Returns a lighter (or darker) color, but does not change this object.
int lightness () const
qreal lightnessF () const
Returns the lightness color component of this color.
int magenta () const
qreal magentaF () const
Returns the magenta color component of this color.
QString name () const
Returns the name of the color in the format "#RRGGBB"; i.e.
operator QVariant () const
Returns the color as a QVariant.
bool operator!= (const QColor &c) const
Returns true if this color has a different RGB and alpha values from color; otherwise returns false.
QColor & operator= (const QColor &)
Assigns a copy of color to this color, and returns a reference to it.
QColor & operator= (Qt::GlobalColor color)
Assigns a copy of color and returns a reference to this color.
bool operator== (const QColor &c) const
Returns true if this color has the same RGB and alpha values as color; otherwise returns false.
QColor ()
Constructs an invalid color with the RGB value (0, 0, 0).
QColor (Qt::GlobalColor color)
Constructs a new color with a color value of color.
QColor (int r, int g, int b, int a=255)
Constructs a color with the RGB value r, g, b, and the alpha-channel (transparency) value of a.
QColor (QRgb rgb)
Constructs a color with the value color.
QColor (const QString &name)
Constructs a named color in the same way as setNamedColor() using the given name.
QColor (const char *name)
Constructs a named color in the same way as setNamedColor() using the given name.
QColor (const QColor &color)
Constructs a color that is a copy of color.
QColor (Spec spec)
Constructs a color with the given spec.
int red () const
qreal redF () const
Returns the red color component of this color.
QRgb rgb () const
Returns the RGB value of the color.
QRgb rgba () const
Returns the RGB value of the color, including its alpha.
int saturation () const
qreal saturationF () const
Returns the saturation color component of this color.
void setAlpha (int alpha)
Sets the alpha of this color to alpha.
void setAlphaF (qreal alpha)
Sets the alpha of this color to alpha.
void setBlue (int blue)
Sets the blue color component of this color to blue.
void setBlueF (qreal blue)
Sets the blue color component of this color to blue.
void setCmyk (int c, int m, int y, int k, int a=255)
Sets the color to CMYK values, c (cyan), m (magenta), y (yellow), k (black), and a (alpha-channel, i.e.
void setCmykF (qreal c, qreal m, qreal y, qreal k, qreal a=1.0)
Sets the color to CMYK values, c (cyan), m (magenta), y (yellow), k (black), and a (alpha-channel, i.
void setGreen (int green)
Sets the green color component of this color to green.
void setGreenF (qreal green)
Sets the green color component of this color to green.
void setHsl (int h, int s, int l, int a=255)
Sets a HSL color value; h is the hue, s is the saturation, l is the lightness and a is the alpha component of the HSL color.
void setHslF (qreal h, qreal s, qreal l, qreal a=1.0)
Sets a HSL color lightness; h is the hue, s is the saturation, l is the lightness and a is the alpha component of the HSL color.
void setHsv (int h, int s, int v, int a=255)
Sets a HSV color value; h is the hue, s is the saturation, v is the value and a is the alpha component of the HSV color.
void setHsvF (qreal h, qreal s, qreal v, qreal a=1.0)
Sets a HSV color value; h is the hue, s is the saturation, v is the value and a is the alpha component of the HSV color.
void setNamedColor (const QString &name)
Sets the RGB value of this QColor to name, which may be in one of these formats:
void setRed (int red)
Sets the red color component of this color to red.
void setRedF (qreal red)
Sets the red color component of this color to red.
void setRgb (int r, int g, int b, int a=255)
Sets the RGB value to r, g, b and the alpha value to a.
void setRgb (QRgb rgb)
Sets the RGB value to rgb.
void setRgba (QRgb rgba)
Use setRgb() instead.
void setRgbF (qreal r, qreal g, qreal b, qreal a=1.0)
Sets the color channels of this color to r (red), g (green), b (blue) and a (alpha, transparency).
Spec spec () const
Returns how the color was specified.
QColor toCmyk () const
Creates and returns a CMYK QColor based on this color.
QColor toHsl () const
Creates and returns an HSL QColor based on this color.
QColor toHsv () const
Creates and returns an HSV QColor based on this color.
QColor toRgb () const
Create and returns an RGB QColor based on this color.
int value () const
qreal valueF () const
Returns the value color component of this color.
int yellow () const
qreal yellowF () const
Returns the yellow color component of this color.
Static Public Functions
static bool allowX11ColorNames ()
Returns true if setNamedColor() is allowed to look up colors in the X11 color database.
static QStringList colorNames ()
Returns a QStringList containing the color names Qt knows about.
static QColor fromCmyk (int c, int m, int y, int k, int a=255)
Static convenience function that returns a QColor constructed from the given CMYK color values: c (cyan), m (magenta), y (yellow), k (black), and a (alpha-channel, i.e.
static QColor fromCmykF (qreal c, qreal m, qreal y, qreal k, qreal a=1.0)
Static convenience function that returns a QColor constructed from the given CMYK color values: c (cyan), m (magenta), y (yellow), k (black), and a (alpha-channel, i.
static QColor fromHsl (int h, int s, int l, int a=255)
Static convenience function that returns a QColor constructed from the HSV color values, h (hue), s (saturation), l (lightness), and a (alpha-channel, i.
static QColor fromHslF (qreal h, qreal s, qreal l, qreal a=1.0)
Static convenience function that returns a QColor constructed from the HSV color values, h (hue), s (saturation), l (lightness), and a (alpha-channel, i.
static QColor fromHsv (int h, int s, int v, int a=255)
Static convenience function that returns a QColor constructed from the HSV color values, h (hue), s (saturation), v (value), and a (alpha-channel, i.e.
static QColor fromHsvF (qreal h, qreal s, qreal v, qreal a=1.0)
Static convenience function that returns a QColor constructed from the HSV color values, h (hue), s (saturation), v (value), and a (alpha-channel, i.
static QColor fromRgb (QRgb rgb)
Static convenience function that returns a QColor constructed from the given QRgb value rgb.
static QColor fromRgb (int r, int g, int b, int a=255)
Static convenience function that returns a QColor constructed from the RGB color values, r (red), g (green), b (blue), and a (alpha-channel, i.e.
static QColor fromRgba (QRgb rgba)
Static convenience function that returns a QColor constructed from the given QRgb value rgba.
static QColor fromRgbF (qreal r, qreal g, qreal b, qreal a=1.0)
Static convenience function that returns a QColor constructed from the RGB color values, r (red), g (green), b (blue), and a (alpha-channel, i.e.
static bool isValidColor (const QString &name)
Returns true if the name is a valid color name and can be used to construct a valid QColor object, otherwise returns false.
static void setAllowX11ColorNames (bool enabled)
Allow setNamedColor() to look up colors in the X11 color database if enabled.
Private Functions
void invalidate ()
Marks the color as invalid and sets all components to zero (alpha is set to fully opaque for compatibility with Qt 3).
QColor (int, int, int, Spec)
Use one of the other QColor constructors, or one of the static convenience functions, instead.
bool setColorFromString (const QString &name)
Properties
Spec cspec
union {
struct {
ushort alpha
ushort black
ushort cyan
ushort magenta
ushort yellow
} acmyk
struct {
ushort alpha
ushort hue
ushort lightness
ushort pad
ushort saturation
} ahsl
struct {
ushort alpha
ushort hue
ushort pad
ushort saturation
ushort value
} ahsv
struct {
ushort alpha
ushort blue
ushort green
ushort pad
ushort red
} argb
ushort array [5]
} ct
Friends
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QColor &)
Writes the color to the stream.
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QColor &)
Reads the color from the stream.
class QColormap
Related Functions
(Note that these are not member functions.)
int qAlpha (QRgb rgba)
Returns the alpha component of the ARGB quadruplet rgba.
int qBlue (QRgb rgb)
Returns the blue component of the ARGB quadruplet rgb.
int qGray (int r, int g, int b)
int qGray (QRgb rgb)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int qGreen (QRgb rgb)
Returns the green component of the ARGB quadruplet rgb.
int qRed (QRgb rgb)
Returns the red component of the ARGB quadruplet rgb.
QRgb qRgb (int r, int g, int b)
Returns the ARGB quadruplet (255, {r}, {g}, {b}).
QRgb
An ARGB quadruplet on the format #AARRGGBB, equivalent to an unsigned int.
QRgb qRgba (int r, int g, int b, int a)
Returns the ARGB quadruplet ({a}, {r}, {g}, {b}).
Detailed Description
The QColor class provides colors based on RGB, HSV or CMYK values.
A color is normally specified in terms of RGB (red, green, and blue) components, but it is also possible to specify it in terms of HSV (hue, saturation, and value) and CMYK (cyan, magenta, yellow and black) components. In addition a color can be specified using a color name. The color name can be any of the SVG 1.0 color names.
RGB HSV CMYK
The QColor constructor creates the color based on RGB values. To create a QColor based on either HSV or CMYK values, use the toHsv() and toCmyk() functions respectively. These functions return a copy of the color using the desired format. In addition the static fromRgb(), fromHsv() and fromCmyk() functions create colors from the specified values. Alternatively, a color can be converted to any of the three formats using the convertTo() function (returning a copy of the color in the desired format), or any of the setRgb(), setHsv() and setCmyk() functions altering this color's format. The spec() function tells how the color was specified.
A color can be set by passing an RGB string (such as "#112233"), or a color name (such as "blue"), to the setNamedColor() function. The color names are taken from the SVG 1.0 color names. The name() function returns the name of the color in the format "#RRGGBB". Colors can also be set using setRgb(), setHsv() and setCmyk(). To get a lighter or darker color use the lighter() and darker() functions respectively.
The isValid() function indicates whether a QColor is legal at all. For example, a RGB color with RGB values out of range is illegal. For performance reasons, QColor mostly disregards illegal colors, and for that reason, the result of using an invalid color is undefined.
The color components can be retrieved individually, e.g with red(), hue() and cyan(). The values of the color components can also be retrieved in one go using the getRgb(), getHsv() and getCmyk() functions. Using the RGB color model, the color components can in addition be accessed with rgb().
There are several related non-members: QRgb is a typdef for an unsigned int representing the RGB value triplet (r, g, b). Note that it also can hold a value for the alpha-channel (for more information, see the Alpha-Blended Drawing section). The qRed(), qBlue() and qGreen() functions return the respective component of the given QRgb value, while the qRgb() and qRgba() functions create and return the QRgb triplet based on the given component values. Finally, the qAlpha() function returns the alpha component of the provided QRgb, and the qGray() function calculates and return a gray value based on the given value.
QColor is platform and device independent. The QColormap class maps the color to the hardware.
For more information about painting in general, see the Paint System documentation.
.-Floating-Point-Precision
Integer vs. Floating Point Precision
QColor supports floating point precision and provides floating point versions of all the color components functions, e.g. getRgbF(), hueF() and fromCmykF(). Note that since the components are stored using 16-bit integers, there might be minor deviations between the values set using, for example, setRgbF() and the values returned by the getRgbF() function due to rounding.
While the integer based functions take values in the range 0-255 (except hue() which must have values within the range 0-359), the floating point functions accept values in the range 0.0 - 1.0.
Alpha-Blended Drawing
QColor also support alpha-blended outlining and filling. The alpha channel of a color specifies the transparency effect, 0 represents a fully transparent color, while 255 represents a fully opaque color. For example:
// Specify semi-transparent red
painter.setBrush(QColor(255, 0, 0, 127));
painter.drawRect(0, 0, width()/2, height());
// Specify semi-transparent blue
painter.setBrush(QColor(0, 0, 255, 127));
painter.drawRect(0, 0, width(), height()/2);
The code above produces the following output:
Alpha-blended drawing is supported on Windows, Mac OS X, and on X11 systems that have the X Render extension installed.
The alpha channel of a color can be retrieved and set using the alpha() and setAlpha() functions if its value is an integer, and alphaF() and setAlphaF() if its value is qreal (double). By default, the alpha-channel is set to 255 (opaque). To retrieve and set all the RGB color components (including the alpha-channel) in one go, use the rgba() and setRgba() functions.
Predefined Colors
There are 20 predefined QColors described by the Qt::GlobalColor enum, including black, white, primary and secondary colors, darker versions of these colors and three shades of gray. QColor also recognizes a variety of color names; the static colorNames() function returns a QStringList color names that QColor knows about.
Qt Colors
Additionally, the Qt::color0, Qt::color1 and Qt::transparent colors are used for special purposes.
Qt::color0 (zero pixel value) and Qt::color1 (non-zero pixel value) are special colors for drawing in QBitmaps. Painting with Qt::color0 sets the bitmap bits to 0 (transparent; i.e., background), and painting with Qt::color1 sets the bits to 1 (opaque; i.e., foreground).
Qt::transparent is used to indicate a transparent pixel. When painting with this value, a pixel value will be used that is appropriate for the underlying pixel format in use.
The HSV Color Model
The RGB model is hardware-oriented. Its representation is close to what most monitors show. In contrast, HSV represents color in a way more suited to the human perception of color. For example, the relationships "stronger than", "darker than", and "the opposite of" are easily expressed in HSV but are much harder to express in RGB.
HSV, like RGB, has three components:
H, for hue, is in the range 0 to 359 if the color is chromatic (not gray), or meaningless if it is gray. It represents degrees on the color wheel familiar to most people. Red is 0 (degrees), green is 120, and blue is 240.
S, for saturation, is in the range 0 to 255, and the bigger it is, the stronger the color is. Grayish colors have saturation near 0; very strong colors have saturation near 255.
V, for value, is in the range 0 to 255 and represents lightness or brightness of the color. 0 is black; 255 is as far from black as possible.
Here are some examples: pure red is H=0, S=255, V=255; a dark red, moving slightly towards the magenta, could be H=350 (equivalent to -10), S=255, V=180; a grayish light red could have H about 0 (say 350-359 or 0-10), S about 50-100, and S=255.
Qt returns a hue value of -1 for achromatic colors. If you pass a hue value that is too large, Qt forces it into range. Hue 360 or 720 is treated as 0; hue 540 is treated as 180.
In addition to the standard HSV model, Qt provides an alpha-channel to feature alpha-blended drawing.
The HSL Color Model
HSL is similar to HSV. Instead of value parameter from HSV, HSL has the lightness parameter. The lightness parameter goes from black to color and from color to white. If you go outside at the night its black or dark gray. At day its colorful but if you look in a really strong light a things they are going to white and wash out.
The CMYK Color Model
While the RGB and HSV color models are used for display on computer monitors, the CMYK model is used in the four-color printing process of printing presses and some hard-copy devices.
CMYK has four components, all in the range 0-255: cyan (C), magenta (M), yellow (Y) and black (K). Cyan, magenta and yellow are called subtractive colors; the CMYK color model creates color by starting with a white surface and then subtracting color by applying the appropriate components. While combining cyan, magenta and yellow gives the color black, subtracting one or more will yield any other color. When combined in various percentages, these three colors can create the entire spectrum of colors.
Mixing 100 percent of cyan, magenta and yellow does produce black, but the result is unsatisfactory since it wastes ink, increases drying time, and gives a muddy colour when printing. For that reason, black is added in professional printing to provide a solid black tone; hence the term 'four color process'.
In addition to the standard CMYK model, Qt provides an alpha-channel to feature alpha-blended drawing.
See also
QPalette, QBrush, QApplication::setColorSpec()
Definition at line 67 of file qcolor.h.
Enumerations
Spec
enum QColor::Spec
The type of color specified, either RGB, HSV, CMYK or HSL.
Rgb
Hsv
Cmyk
Hsl
Invalid
See also
spec(), convertTo()
Enumerator
Invalid
Rgb
Hsv
Cmyk
Hsl
Definition at line 70 of file qcolor.h.
 { Invalid, Rgb, Hsv, Cmyk, Hsl };
Constructors and Destructors
QColor() [1/9]
QColor::QColor () inline
Constructs an invalid color with the RGB value (0, 0, 0).
An invalid color is a color that is not properly set up for the underlying window system.
The alpha value of an invalid color is unspecified.
See also
isValid()
Definition at line 279 of file qcolor.h.
Referenced by convertTo(), fromCmyk(), fromCmykF(), fromHsl(), fromHslF(), fromHsv(), fromHsvF(), fromRgb(), fromRgbF(), isValidColor(), and operator=().
 { invalidate(); }
QColor() [2/9]
QColor::QColor (Qt::GlobalColor color)
Constructs a new color with a color value of color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
isValid(), {QColor::Predefined Colors}{Predefined Colors}
Definition at line 355 of file qcolor.cpp.
 {
 #define QRGB(r, g, b) \
     QRgb(((0xffu << 24) | ((r & 0xff) << 16) | ((g & 0xff) << 8) | (b & 0xff)))
 #define QRGBA(r, g, b, a) \
     QRgb(((a & 0xff) << 24) | ((r & 0xff) << 16) | ((g & 0xff) << 8) | (b & 0xff))
     static const QRgb global_colors[] = {
         QRGB(255, 255, 255), // Qt::color0
         QRGB(  0,   0,   0), // Qt::color1
         QRGB(  0,   0,   0), // black
         QRGB(255, 255, 255), // white
         /*
          * From the "The Palette Manager: How and Why" by Ron Gery,
          * March 23, 1992, archived on MSDN:
          *
          *     The Windows system palette is broken up into two
          *     sections, one with fixed colors and one with colors
          *     that can be changed by applications. The system palette
          *     predefines 20 entries; these colors are known as the
          *     static or reserved colors and consist of the 16 colors
          *     found in the Windows version 3.0 VGA driver and 4
          *     additional colors chosen for their visual appeal.  The
          *     DEFAULT_PALETTE stock object is, as the name implies,
          *     the default palette selected into a device context (DC)
          *     and consists of these static colors. Applications can
          *     set the remaining 236 colors using the Palette Manager.
          *
          * The 20 reserved entries have indices in [0,9] and
          * [246,255]. We reuse 17 of them.
          */
         QRGB(128, 128, 128), // index 248   medium gray
         QRGB(160, 160, 164), // index 247   light gray
         QRGB(192, 192, 192), // index 7     light gray
         QRGB(255,   0,   0), // index 249   red
         QRGB(  0, 255,   0), // index 250   green
         QRGB(  0,   0, 255), // index 252   blue
         QRGB(  0, 255, 255), // index 254   cyan
         QRGB(255,   0, 255), // index 253   magenta
         QRGB(255, 255,   0), // index 251   yellow
         QRGB(128,   0,   0), // index 1     dark red
         QRGB(  0, 128,   0), // index 2     dark green
         QRGB(  0,   0, 128), // index 4     dark blue
         QRGB(  0, 128, 128), // index 6     dark cyan
         QRGB(128,   0, 128), // index 5     dark magenta
         QRGB(128, 128,   0), // index 3     dark yellow
         QRGBA(0, 0, 0, 0)    //             transparent
     };
 #undef QRGB
 #undef QRGBA
     setRgb(qRed(global_colors[color]),
            qGreen(global_colors[color]),
            qBlue(global_colors[color]),
            qAlpha(global_colors[color]));
 }
QColor() [3/9]
QColor::QColor (int r, int g, int b, int a = 255) inline
Constructs a color with the RGB value r, g, b, and the alpha-channel (transparency) value of a.
The color is left invalid if any of the arguments are invalid.
See also
setRgba(), isValid()
Definition at line 282 of file qcolor.h.
 { setRgb(r, g, b, a); }
QColor() [4/9]
QColor::QColor (QRgb color)
Constructs a color with the value color.
The alpha component is ignored and set to solid.
See also
fromRgb(), isValid()
Definition at line 433 of file qcolor.cpp.
 {
     cspec = Rgb;
     ct.argb.alpha = 0xffff;
     ct.argb.red   = qRed(color)   * 0x101;
     ct.argb.green = qGreen(color) * 0x101;
     ct.argb.blue  = qBlue(color)  * 0x101;
     ct.argb.pad   = 0;
 }
QColor() [5/9]
QColor::QColor (const QString & name) inline
Constructs a named color in the same way as setNamedColor() using the given name.
The color is left invalid if the name cannot be parsed.
See also
setNamedColor(), name(), isValid()
Definition at line 288 of file qcolor.h.
 { setNamedColor(aname); }
QColor() [6/9]
QColor::QColor (const char * name) inline
Constructs a named color in the same way as setNamedColor() using the given name.
The color is left invalid if the name cannot be parsed.
See also
setNamedColor(), name(), isValid()
Definition at line 285 of file qcolor.h.
 { setNamedColor(QLatin1String(aname)); }
QColor() [7/9]
QColor::QColor (const QColor & color) inline
Constructs a color that is a copy of color.
See also
isValid()
Definition at line 291 of file qcolor.h.
     : cspec(acolor.cspec)
 { ct.argb = acolor.ct.argb; }
QColor() [8/9]
QColor::QColor (Spec spec)
Constructs a color with the given spec.
Warning
This function is not part of the public interface.
This function is primarly present to avoid that QColor::Invalid becomes a valid color by accident.
Definition at line 456 of file qcolor.cpp.
 {
     switch (spec) {
     case Invalid:
         invalidate();
         break;
     case Rgb:
         setRgb(0, 0, 0);
         break;
     case Hsv:
         setHsv(0, 0, 0);
         break;
     case Cmyk:
         setCmyk(0, 0, 0, 0);
         break;
     case Hsl:
         setHsl(0, 0, 0, 0);
         break;
     }
 }
QColor() [9/9]
QColor::QColor (int x, int y, int z, Spec colorSpec) private
Use one of the other QColor constructors, or one of the static convenience functions, instead.
Functions
allowX11ColorNames()
bool QColor::allowX11ColorNames () static
Returns true if setNamedColor() is allowed to look up colors in the X11 color database.
By default, this function returns false.
Note
This function is only available on the X11 platform.
See also
setAllowX11ColorNames()
Definition at line 2535 of file qcolor.cpp.
Referenced by qt_set_x11_resources(), setAllowX11ColorNames(), and setColorFromString().
 {
     return ::allowX11ColorNames;
 }
alpha()
int QColor::alpha () const
Referenced by setBlue(), setGreen(), setRed(), and setRgb().
alphaF()
qreal QColor::alphaF () const
Returns the alpha color component of this color.
See also
setAlphaF(), alpha(), {QColor::Alpha-Blended Drawing}{Alpha-Blended Drawing}
Definition at line 1106 of file qcolor.cpp.
Referenced by QGLPixmapGLPaintDevice::beginPaint(), QGLWidgetGLPaintDevice::beginPaint(), QVGPaintEngine::clearRect(), QVGPixmapColorizeFilter::draw(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QVGCompositionHelper::fillBackground(), QVGPaintEngine::fillRegion(), QTextControlPrivate::inputMethodEvent(), operator<<(), QLineControl::processInputMethodEvent(), qBrushSetAlphaF(), qt_premultiplyColor(), QInternalMimeData::renderDataHelper(), QGLShaderProgram::setAttributeValue(), setBlueF(), QVGPaintEnginePrivate::setBrush(), setGreenF(), setRedF(), QGLPixmapDropShadowFilter::setUniforms(), QGLShaderProgram::setUniformValue(), QVGPaintEnginePrivate::setupColorRamp(), QDeclarativeEnginePrivate::tint(), and translate_color().
 { return ct.argb.alpha / qreal(USHRT_MAX); }
black()
int QColor::black () const
Referenced by lightnessF().
blackF()
qreal QColor::blackF () const
Returns the black color component of this color.
See also
black(), getCmykF(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 1624 of file qcolor.cpp.
Referenced by blackF(), and operator<<().
 {
     if (cspec != Invalid && cspec != Cmyk)
         return toCmyk().blackF();
     return ct.acmyk.black / qreal(USHRT_MAX);
 }
blue()
int QColor::blue () const
Referenced by name(), setGreen(), and setRed().
blueF()
qreal QColor::blueF () const
Returns the blue color component of this color.
See also
setBlueF(), blue(), getRgbF()
Definition at line 1269 of file qcolor.cpp.
Referenced by QGLPixmapGLPaintDevice::beginPaint(), QGLWidgetGLPaintDevice::beginPaint(), blueF(), QVGPaintEngine::clearRect(), QVGPixmapColorizeFilter::draw(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QVGCompositionHelper::fillBackground(), QVGPaintEngine::fillRegion(), operator<<(), qt_premultiplyColor(), QInternalMimeData::renderDataHelper(), QGLShaderProgram::setAttributeValue(), QPSPrintEngine::setBrush(), QPdfEngine::setBrush(), QVGPaintEnginePrivate::setBrush(), setGreenF(), setRedF(), QGLPixmapDropShadowFilter::setUniforms(), QGLShaderProgram::setUniformValue(), QVGPaintEnginePrivate::setupColorRamp(), and QDeclarativeEnginePrivate::tint().
 {
     if (cspec != Invalid && cspec != Rgb)
         return toRgb().blueF();
     return ct.argb.blue / qreal(USHRT_MAX);
 }
colorNames()
QStringList QColor::colorNames () static
Returns a QStringList containing the color names Qt knows about.
See also
{QColor::Predefined Colors}{Predefined Colors}
Definition at line 632 of file qcolor.cpp.
 {
 #ifndef QT_NO_COLORNAMES
     return qt_get_colornames();
 #else
     return QStringList();
 #endif
 }
convertTo()
QColor QColor::convertTo (QColor::Spec colorSpec) const
Creates a copy of this color in the format specified by colorSpec.
See also
spec(), toCmyk(), toHsv(), toRgb(), isValid()
Definition at line 1927 of file qcolor.cpp.
Referenced by dark(), and light().
 {
     if (colorSpec == cspec)
         return *this;
     switch (colorSpec) {
     case Rgb:
         return toRgb();
     case Hsv:
         return toHsv();
     case Cmyk:
         return toCmyk();
     case Hsl:
         return toHsl();
     case Invalid:
         break;
     }
     return QColor(); // must be invalid
 }
cyan()
int QColor::cyan () const
Referenced by lightnessF().
cyanF()
qreal QColor::cyanF () const
Returns the cyan color component of this color.
See also
cyan(), getCmykF(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 1585 of file qcolor.cpp.
Referenced by cyanF(), and operator<<().
 {
     if (cspec != Invalid && cspec != Cmyk)
         return toCmyk().cyanF();
     return ct.acmyk.cyan / qreal(USHRT_MAX);
 }
dark()
QColor QColor::dark (int factor = 200) const
Use darker(factor) instead.
Definition at line 2447 of file qcolor.cpp.
Referenced by darker(), QWindowsCEStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawPrimitive(), and qt_set_windows_color_resources().
 {
     if (factor <= 0)                                // invalid darkness factor
         return *this;
     else if (factor < 100)                        // makes color lighter
         return lighter(10000 / factor);
     QColor hsv = toHsv();
     hsv.ct.ahsv.value = (hsv.ct.ahsv.value * 100) / factor;
     // convert back to same color spec as original color
     return hsv.convertTo(cspec);
 }
darker()
QColor QColor::darker (int factor = 200) const inline
Returns a darker (or lighter) color, but does not change this object.
Since
4.3
If the factor is greater than 100, this functions returns a darker color. Setting factor to 300 returns a color that has one-third the brightness. If the factor is less than 100, the return color is lighter, but we recommend using the lighter() function for this purpose. If the factor is 0 or negative, the return value is unspecified.
The function converts the current RGB color to HSV, divides the value (V) component by factor and converts the color back to RGB.
See also
lighter(), isValid()
Definition at line 301 of file qcolor.h.
Referenced by QRenderRule::configurePalette(), QDeclarativeEnginePrivate::darker(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QMacStyle::drawControl(), QStyleHelper::drawDial(), QWindowsVistaStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QMacStyle::drawPrimitive(), light(), QWindowsXPStyle::polish(), QMotifStyle::polish(), QWindowsVistaStyle::polish(), qBrushDark(), qt_cleanlooks_draw_buttongradient(), qt_cleanlooks_draw_mdibutton(), qt_plastique_draw_handle(), qt_plastique_drawFrame(), qt_plastique_drawShadedPanel(), qt_set_windows_color_resources(), QCleanlooksStyle::standardPalette(), QCDEStyle::standardPalette(), QGtkStyle::standardPalette(), QPlastiqueStyle::standardPalette(), QStyle::standardPalette(), QWindowsVistaStyle::styleHint(), and QCleanlooksStyle::styleHint().
 { return dark(f); }
fromCmyk()
QColor QColor::fromCmyk (int c, int m, int y, int k, int a = 255) static
Static convenience function that returns a QColor constructed from the given CMYK color values: c (cyan), m (magenta), y (yellow), k (black), and a (alpha-channel, i.e.
transparency).
All the values must be in the range 0-255.
See also
toCmyk(), fromCmykF(), isValid(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 2305 of file qcolor.cpp.
 {
     if (c < 0 || c > 255
         || m < 0 || m > 255
         || y < 0 || y > 255
         || k < 0 || k > 255
         || a < 0 || a > 255) {
         qWarning("QColor::fromCmyk: CMYK parameters out of range");
         return QColor();
     }
     QColor color;
     color.cspec = Cmyk;
     color.ct.acmyk.alpha   = a * 0x101;
     color.ct.acmyk.cyan    = c * 0x101;
     color.ct.acmyk.magenta = m * 0x101;
     color.ct.acmyk.yellow  = y * 0x101;
     color.ct.acmyk.black   = k * 0x101;
     return color;
 }
fromCmykF()
QColor QColor::fromCmykF (qreal c, qreal m, qreal y, qreal k, qreal a = 1.0) static
Static convenience function that returns a QColor constructed from the given CMYK color values: c (cyan), m (magenta), y (yellow), k (black), and a (alpha-channel, i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
e. transparency).
All the values must be in the range 0.0-1.0.
\sa toCmyk(), fromCmyk(), isValid(), {QColor#The CMYK Color
Model}{The CMYK Color Model}
Definition at line 2341 of file qcolor.cpp.
 {
     if (c < qreal(0.0) || c > qreal(1.0)
         || m < qreal(0.0) || m > qreal(1.0)
         || y < qreal(0.0) || y > qreal(1.0)
         || k < qreal(0.0) || k > qreal(1.0)
         || a < qreal(0.0) || a > qreal(1.0)) {
         qWarning("QColor::fromCmykF: CMYK parameters out of range");
         return QColor();
     }
     QColor color;
     color.cspec = Cmyk;
     color.ct.acmyk.alpha   = qRound(a * USHRT_MAX);
     color.ct.acmyk.cyan    = qRound(c * USHRT_MAX);
     color.ct.acmyk.magenta = qRound(m * USHRT_MAX);
     color.ct.acmyk.yellow  = qRound(y * USHRT_MAX);
     color.ct.acmyk.black   = qRound(k * USHRT_MAX);
     return color;
 }
fromHsl()
QColor QColor::fromHsl (int h, int s, int l, int a = 255) static
Static convenience function that returns a QColor constructed from the HSV color values, h (hue), s (saturation), l (lightness), and a (alpha-channel, i.
Since
4.6
e. transparency).
The value of \a s, \a l, and \a a must all be in the range 0-255; the value
of \a h must be in the range 0-359.
\sa toHsl(), fromHslF(), isValid()
Definition at line 2118 of file qcolor.cpp.
 {
     if (((h < 0 || h >= 360) && h != -1)
         || s < 0 || s > 255
         || l < 0 || l > 255
         || a < 0 || a > 255) {
         qWarning("QColor::fromHsv: HSV parameters out of range");
         return QColor();
     }
     QColor color;
     color.cspec = Hsl;
     color.ct.ahsl.alpha      = a * 0x101;
     color.ct.ahsl.hue        = h == -1 ? USHRT_MAX : (h % 360) * 100;
     color.ct.ahsl.saturation = s * 0x101;
     color.ct.ahsl.lightness  = l * 0x101;
     color.ct.ahsl.pad        = 0;
     return color;
 }
fromHslF()
QColor QColor::fromHslF (qreal h, qreal s, qreal l, qreal a = 1.0) static
Static convenience function that returns a QColor constructed from the HSV color values, h (hue), s (saturation), l (lightness), and a (alpha-channel, i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.6
e. transparency).
All the values must be in the range 0.0-1.0.
\sa toHsl(), fromHsl(), isValid()
Definition at line 2153 of file qcolor.cpp.
Referenced by QDeclarativeEnginePrivate::hsla().
 {
     if (((h < qreal(0.0) || h > qreal(1.0)) && h != qreal(-1.0))
         || (s < qreal(0.0) || s > qreal(1.0))
         || (l < qreal(0.0) || l > qreal(1.0))
         || (a < qreal(0.0) || a > qreal(1.0))) {
         qWarning("QColor::fromHsvF: HSV parameters out of range");
         return QColor();
     }
     QColor color;
     color.cspec = Hsl;
     color.ct.ahsl.alpha      = qRound(a * USHRT_MAX);
     color.ct.ahsl.hue        = (h == qreal(-1.0)) ? USHRT_MAX : qRound(h * 36000);
     if (color.ct.ahsl.hue == 36000)
         color.ct.ahsl.hue = 0;
     color.ct.ahsl.saturation = qRound(s * USHRT_MAX);
     color.ct.ahsl.lightness  = qRound(l * USHRT_MAX);
     color.ct.ahsl.pad        = 0;
     return color;
 }
fromHsv()
QColor QColor::fromHsv (int h, int s, int v, int a = 255) static
Static convenience function that returns a QColor constructed from the HSV color values, h (hue), s (saturation), v (value), and a (alpha-channel, i.e.
transparency).
The value of s, v, and a must all be in the range 0-255; the value of h must be in the range 0-359.
See also
toHsv(), fromHsvF(), isValid(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 2048 of file qcolor.cpp.
Referenced by QGraphicsScenePrivate::draw(), and parseColorValue().
 {
     if (((h < 0 || h >= 360) && h != -1)
         || s < 0 || s > 255
         || v < 0 || v > 255
         || a < 0 || a > 255) {
         qWarning("QColor::fromHsv: HSV parameters out of range");
         return QColor();
     }
     QColor color;
     color.cspec = Hsv;
     color.ct.ahsv.alpha      = a * 0x101;
     color.ct.ahsv.hue        = h == -1 ? USHRT_MAX : (h % 360) * 100;
     color.ct.ahsv.saturation = s * 0x101;
     color.ct.ahsv.value      = v * 0x101;
     color.ct.ahsv.pad        = 0;
     return color;
 }
fromHsvF()
QColor QColor::fromHsvF (qreal h, qreal s, qreal v, qreal a = 1.0) static
Static convenience function that returns a QColor constructed from the HSV color values, h (hue), s (saturation), v (value), and a (alpha-channel, i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
e. transparency).
All the values must be in the range 0.0-1.0.
\sa toHsv(), fromHsv(), isValid(), {QColor#The HSV Color
Model}{The HSV Color Model}
Definition at line 2083 of file qcolor.cpp.
 {
     if (((h < qreal(0.0) || h > qreal(1.0)) && h != qreal(-1.0))
         || (s < qreal(0.0) || s > qreal(1.0))
         || (v < qreal(0.0) || v > qreal(1.0))
         || (a < qreal(0.0) || a > qreal(1.0))) {
         qWarning("QColor::fromHsvF: HSV parameters out of range");
         return QColor();
     }
     QColor color;
     color.cspec = Hsv;
     color.ct.ahsv.alpha      = qRound(a * USHRT_MAX);
     color.ct.ahsv.hue        = h == qreal(-1.0) ? USHRT_MAX : qRound(h * 36000);
     color.ct.ahsv.saturation = qRound(s * USHRT_MAX);
     color.ct.ahsv.value      = qRound(v * USHRT_MAX);
     color.ct.ahsv.pad        = 0;
     return color;
 }
fromRgb() [1/2]
QColor QColor::fromRgb (QRgb rgb) static
Static convenience function that returns a QColor constructed from the given QRgb value rgb.
The alpha component of rgb is ignored (i.e. it is automatically set to 255), use the fromRgba() function to include the alpha-channel specified by the given QRgb value.
See also
fromRgba(), fromRgbF(), toRgb(), isValid()
Definition at line 1958 of file qcolor.cpp.
Referenced by fromRgba(), parseColorValue(), QmlJSDebugger::ColorPickerTool::pickColor(), and QWindowsVistaStyle::polish().
 {
     return fromRgb(qRed(rgb), qGreen(rgb), qBlue(rgb));
 }
fromRgb() [2/2]
QColor QColor::fromRgb (int r, int g, int b, int a = 255) static
Static convenience function that returns a QColor constructed from the RGB color values, r (red), g (green), b (blue), and a (alpha-channel, i.e.
transparency).
All the values must be in the range 0-255.
See also
toRgb(), fromRgbF(), isValid()
Definition at line 1988 of file qcolor.cpp.
 {
     if (r < 0 || r > 255
         || g < 0 || g > 255
         || b < 0 || b > 255
         || a < 0 || a > 255) {
         qWarning("QColor::fromRgb: RGB parameters out of range");
         return QColor();
     }
     QColor color;
     color.cspec = Rgb;
     color.ct.argb.alpha = a * 0x101;
     color.ct.argb.red   = r * 0x101;
     color.ct.argb.green = g * 0x101;
     color.ct.argb.blue  = b * 0x101;
     color.ct.argb.pad   = 0;
     return color;
 }
fromRgba()
QColor QColor::fromRgba (QRgb rgba) static
Static convenience function that returns a QColor constructed from the given QRgb value rgba.
Unlike the fromRgb() function, the alpha-channel specified by the given QRgb value is included.
See also
fromRgb(), isValid()
Definition at line 1974 of file qcolor.cpp.
Referenced by QSvgPaintEngine::saveGradientStops().
 {
     return fromRgb(qRed(rgba), qGreen(rgba), qBlue(rgba), qAlpha(rgba));
 }
fromRgbF()
QColor QColor::fromRgbF (qreal r, qreal g, qreal b, qreal a = 1.0) static
Static convenience function that returns a QColor constructed from the RGB color values, r (red), g (green), b (blue), and a (alpha-channel, i.e.
transparency).
All the values must be in the range 0.0-1.0.
See also
fromRgb(), toRgb(), isValid()
Definition at line 2017 of file qcolor.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs(), query_colormap(), and QDeclarativeEnginePrivate::rgba().
 {
     if (r < qreal(0.0) || r > qreal(1.0)
         || g < qreal(0.0) || g > qreal(1.0)
         || b < qreal(0.0) || b > qreal(1.0)
         || a < qreal(0.0) || a > qreal(1.0)) {
         qWarning("QColor::fromRgbF: RGB parameters out of range");
         return QColor();
     }
     QColor color;
     color.cspec = Rgb;
     color.ct.argb.alpha = qRound(a * USHRT_MAX);
     color.ct.argb.red   = qRound(r * USHRT_MAX);
     color.ct.argb.green = qRound(g * USHRT_MAX);
     color.ct.argb.blue  = qRound(b * USHRT_MAX);
     color.ct.argb.pad   = 0;
     return color;
 }
getCmyk()
void QColor::getCmyk (int * c, int * m, int * y, int * k, int * a = 0)
Sets the contents pointed to by c, m, y, k, and a, to the cyan, magenta, yellow, black, and alpha-channel (transparency) components of the color's CMYK value.
These components can be retrieved individually using the cyan(), magenta(), yellow(), black() and alpha() functions.
See also
setCmyk(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 2186 of file qcolor.cpp.
Referenced by getCmyk().
 {
     if (!c || !m || !y || !k)
         return;
     if (cspec != Invalid && cspec != Cmyk) {
         toCmyk().getCmyk(c, m, y, k, a);
         return;
     }
     *c = ct.acmyk.cyan >> 8;
     *m = ct.acmyk.magenta >> 8;
     *y = ct.acmyk.yellow >> 8;
     *k = ct.acmyk.black >> 8;
     if (a)
         *a = ct.acmyk.alpha >> 8;
 }
getCmykF()
void QColor::getCmykF (qreal * c, qreal * m, qreal * y, qreal * k, qreal * a = 0)
Sets the contents pointed to by c, m, y, k, and a, to the cyan, magenta, yellow, black, and alpha-channel (transparency) components of the color's CMYK value.
These components can be retrieved individually using the cyanF(), magentaF(), yellowF(), blackF() and alphaF() functions.
See also
setCmykF(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 2215 of file qcolor.cpp.
Referenced by getCmykF().
 {
     if (!c || !m || !y || !k)
         return;
     if (cspec != Invalid && cspec != Cmyk) {
         toCmyk().getCmykF(c, m, y, k, a);
         return;
     }
     *c = ct.acmyk.cyan    / qreal(USHRT_MAX);
     *m = ct.acmyk.magenta / qreal(USHRT_MAX);
     *y = ct.acmyk.yellow  / qreal(USHRT_MAX);
     *k = ct.acmyk.black   / qreal(USHRT_MAX);
     if (a)
         *a = ct.acmyk.alpha / qreal(USHRT_MAX);
 }
getHsl()
void QColor::getHsl (int * h, int * s, int * l, int * a = 0) const
Sets the contents pointed to by h, s, l, and a, to the hue, saturation, lightness, and alpha-channel (transparency) components of the color's HSL value.
Since
4.6
These components can be retrieved individually using the hueHsl(), saturationHsl(), lightness() and alpha() functions.
See also
setHsl()
Definition at line 798 of file qcolor.cpp.
Referenced by getHsl().
 {
     if (!h || !s || !l)
         return;
     if (cspec != Invalid && cspec != Hsl) {
         toHsl().getHsl(h, s, l, a);
         return;
     }
     *h = ct.ahsl.hue == USHRT_MAX ? -1 : ct.ahsl.hue / 100;
     *s = ct.ahsl.saturation >> 8;
     *l = ct.ahsl.lightness  >> 8;
     if (a)
         *a = ct.ahsl.alpha >> 8;
 }
getHslF()
void QColor::getHslF (qreal * h, qreal * s, qreal * l, qreal * a = 0) const
Sets the contents pointed to by h, s, l, and a, to the hue, saturation, lightness, and alpha-channel (transparency) components of the color's HSL value.
Since
4.6
These components can be retrieved individually using the hueHslF(), saturationHslF(), lightnessF() and alphaF() functions.
See also
setHsl()
Definition at line 765 of file qcolor.cpp.
Referenced by getHslF().
 {
         if (!h || !s || !l)
         return;
     if (cspec != Invalid && cspec != Hsl) {
         toHsl().getHslF(h, s, l, a);
         return;
     }
     *h = ct.ahsl.hue == USHRT_MAX ? qreal(-1.0) : ct.ahsl.hue / qreal(36000.0);
     *s = ct.ahsl.saturation / qreal(USHRT_MAX);
     *l = ct.ahsl.lightness / qreal(USHRT_MAX);
     if (a)
         *a = ct.ahsl.alpha / qreal(USHRT_MAX);
 }
getHsv()
void QColor::getHsv (int * h, int * s, int * v, int * a = 0) const
Sets the contents pointed to by h, s, v, and a, to the hue, saturation, value, and alpha-channel (transparency) components of the color's HSV value.
These components can be retrieved individually using the hue(), saturation(), value() and alpha() functions.
See also
setHsv(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 679 of file qcolor.cpp.
Referenced by darkenPixmap(), QCommonStyle::drawPrimitive(), getHsv(), QPalette::QPalette(), qt_palette_from_color(), and rgb2hsv().
 {
     if (!h || !s || !v)
         return;
     if (cspec != Invalid && cspec != Hsv) {
         toHsv().getHsv(h, s, v, a);
         return;
     }
     *h = ct.ahsv.hue == USHRT_MAX ? -1 : ct.ahsv.hue / 100;
     *s = ct.ahsv.saturation >> 8;
     *v = ct.ahsv.value      >> 8;
     if (a)
         *a = ct.ahsv.alpha >> 8;
 }
getHsvF()
void QColor::getHsvF (qreal * h, qreal * s, qreal * v, qreal * a = 0) const
Sets the contents pointed to by h, s, v, and a, to the hue, saturation, value, and alpha-channel (transparency) components of the color's HSV value.
These components can be retrieved individually using the hueF(), saturationF(), valueF() and alphaF() functions.
See also
setHsv() {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 651 of file qcolor.cpp.
Referenced by getHsvF().
 {
         if (!h || !s || !v)
         return;
     if (cspec != Invalid && cspec != Hsv) {
         toHsv().getHsvF(h, s, v, a);
         return;
     }
     *h = ct.ahsv.hue == USHRT_MAX ? qreal(-1.0) : ct.ahsv.hue / qreal(36000.0);
     *s = ct.ahsv.saturation / qreal(USHRT_MAX);
     *v = ct.ahsv.value / qreal(USHRT_MAX);
     if (a)
         *a = ct.ahsv.alpha / qreal(USHRT_MAX);
 }
getRgb()
void QColor::getRgb (int * r, int * g, int * b, int * a = 0) const
Sets the contents pointed to by r, g, b, and a, to the red, green, blue, and alpha-channel (transparency) components of the color's RGB value.
These components can be retrieved individually using the red(), green(), blue() and alpha() functions.
See also
rgb(), setRgb()
Definition at line 916 of file qcolor.cpp.
Referenced by getRgb().
 {
     if (!r || !g || !b)
         return;
     if (cspec != Invalid && cspec != Rgb) {
         toRgb().getRgb(r, g, b, a);
         return;
     }
     *r = ct.argb.red   >> 8;
     *g = ct.argb.green >> 8;
     *b = ct.argb.blue  >> 8;
     if (a)
         *a = ct.argb.alpha >> 8;
 }
getRgbF()
void QColor::getRgbF (qreal * r, qreal * g, qreal * b, qreal * a = 0) const
Sets the contents pointed to by r, g, b, and a, to the red, green, blue, and alpha-channel (transparency) components of the color's RGB value.
These components can be retrieved individually using the redF(), greenF(), blueF() and alphaF() functions.
See also
rgb(), setRgb()
Definition at line 887 of file qcolor.cpp.
Referenced by getRgbF().
 {
     if (!r || !g || !b)
         return;
     if (cspec != Invalid && cspec != Rgb) {
         toRgb().getRgbF(r, g, b, a);
         return;
     }
     *r = ct.argb.red   / qreal(USHRT_MAX);
     *g = ct.argb.green / qreal(USHRT_MAX);
     *b = ct.argb.blue  / qreal(USHRT_MAX);
     if (a)
         *a = ct.argb.alpha / qreal(USHRT_MAX);
 }
green()
int QColor::green () const
Referenced by name(), setBlue(), and setRed().
greenF()
qreal QColor::greenF () const
Returns the green color component of this color.
See also
setGreenF(), green(), getRgbF()
Definition at line 1241 of file qcolor.cpp.
Referenced by QGLPixmapGLPaintDevice::beginPaint(), QGLWidgetGLPaintDevice::beginPaint(), QVGPaintEngine::clearRect(), QVGPixmapColorizeFilter::draw(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QVGCompositionHelper::fillBackground(), QVGPaintEngine::fillRegion(), greenF(), operator<<(), qt_premultiplyColor(), QInternalMimeData::renderDataHelper(), QGLShaderProgram::setAttributeValue(), setBlueF(), QPSPrintEngine::setBrush(), QPdfEngine::setBrush(), QVGPaintEnginePrivate::setBrush(), setRedF(), QGLPixmapDropShadowFilter::setUniforms(), QGLShaderProgram::setUniformValue(), QVGPaintEnginePrivate::setupColorRamp(), and QDeclarativeEnginePrivate::tint().
 {
     if (cspec != Invalid && cspec != Rgb)
         return toRgb().greenF();
     return ct.argb.green / qreal(USHRT_MAX);
 }
hslHue()
int QColor::hslHue () const
Returns the hue color component of this color.
Since
4.6
See also
getHslF(), getHsl()
Definition at line 1433 of file qcolor.cpp.
Referenced by hslHue().
 {
     if (cspec != Invalid && cspec != Hsl)
         return toHsl().hslHue();
     return ct.ahsl.hue == USHRT_MAX ? -1 : ct.ahsl.hue / 100;
 }
hslHueF()
qreal QColor::hslHueF () const
Returns the hue color component of this color.
Since
4.6
See also
hue(), getHslF()
Definition at line 1485 of file qcolor.cpp.
Referenced by hslHueF(), and operator<<().
 {
     if (cspec != Invalid && cspec != Hsl)
         return toHsl().hslHueF();
     return ct.ahsl.hue == USHRT_MAX ? qreal(-1.0) : ct.ahsl.hue / qreal(36000.0);
 }
hslSaturation()
int QColor::hslSaturation () const
Returns the saturation color component of this color.
Since
4.6
See also
saturationF(), getHsv(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 1451 of file qcolor.cpp.
Referenced by hslSaturation().
 {
     if (cspec != Invalid && cspec != Hsl)
         return toHsl().hslSaturation();
     return ct.ahsl.saturation >> 8;
 }
hslSaturationF()
qreal QColor::hslSaturationF () const
Returns the saturation color component of this color.
Since
4.6
See also
saturationF() getHslF()
Definition at line 1502 of file qcolor.cpp.
Referenced by hslSaturationF(), and operator<<().
 {
     if (cspec != Invalid && cspec != Hsl)
         return toHsl().hslSaturationF();
     return ct.ahsl.saturation / qreal(USHRT_MAX);
 }
hsvHue()
int QColor::hsvHue () const
Returns the hue color component of this color.
See also
hueF(), getHsv(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 1311 of file qcolor.cpp.
Referenced by setBlueF().
 {
     if (cspec != Invalid && cspec != Hsv)
         return toHsv().hue();
     return ct.ahsv.hue == USHRT_MAX ? -1 : ct.ahsv.hue / 100;
 }
hsvHueF()
qreal QColor::hsvHueF () const
Returns the hue color component of this color.
See also
hue(), getHsvF(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 1377 of file qcolor.cpp.
Referenced by hueF().
 {
     if (cspec != Invalid && cspec != Hsv)
         return toHsv().hueF();
     return ct.ahsv.hue == USHRT_MAX ? qreal(-1.0) : ct.ahsv.hue / qreal(36000.0);
 }
hsvSaturation()
int QColor::hsvSaturation () const
Returns the saturation color component of this color.
See also
saturationF(), getHsv(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 1338 of file qcolor.cpp.
Referenced by hsvHue().
 {
     if (cspec != Invalid && cspec != Hsv)
         return toHsv().saturation();
     return ct.ahsv.saturation >> 8;
 }
hsvSaturationF()
qreal QColor::hsvSaturationF () const
Returns the saturation color component of this color.
See also
saturation() getHsvF(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 1403 of file qcolor.cpp.
Referenced by saturationF().
 {
     if (cspec != Invalid && cspec != Hsv)
         return toHsv().saturationF();
     return ct.ahsv.saturation / qreal(USHRT_MAX);
 }
hue()
int QColor::hue () const
Referenced by setBlueF(), toHsl(), and toHsv().
hueF()
qreal QColor::hueF () const
Returns the hue color component of this color.
The color is implicitly converted to HSV.
See also
hsvHueF(), hue(), getHsvF(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 1366 of file qcolor.cpp.
Referenced by hsvHueF(), and operator<<().
 {
     return hsvHueF();
 }
invalidate()
void QColor::invalidate () private
Marks the color as invalid and sets all components to zero (alpha is set to fully opaque for compatibility with Qt 3).
Warning
This function is not part of the public interface.
Definition at line 2563 of file qcolor.cpp.
Referenced by operator>>(), QColor(), setColorFromString(), setHsl(), setHsv(), setRgb(), and setRgbF().
 {
     cspec = Invalid;
     ct.argb.alpha = USHRT_MAX;
     ct.argb.red = 0;
     ct.argb.green = 0;
     ct.argb.blue = 0;
     ct.argb.pad = 0;
 }
isValid()
bool QColor::isValid () const inline
Returns true if the color is valid; otherwise returns false.
Definition at line 295 of file qcolor.h.
Referenced by QTextHtmlParser::applyAttributes(), QDeclarativeStringConverters::colorFromString(), QDirectFBScreen::connect(), QDeclarativeTextLayout::draw(), QCommonStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QPainter::drawStaticText(), drawTextItemDecoration(), QColorWell::dropEvent(), QColorShowLabel::dropEvent(), QDirectFBPaintEngine::fillRect(), QColorDialog::getRgba(), hash(), QGLOverlayWidget::initializeGL(), QTabBar::initStyleOption(), operator<<(), QCss::Parser::parseHexColor(), resolveColor(), QPainter::setPen(), toCmyk(), toHsl(), toHsv(), and toRgb().
 { return cspec != Invalid; }
isValidColor()
bool QColor::isValidColor (const QString & name) static
Returns true if the name is a valid color name and can be used to construct a valid QColor object, otherwise returns false.
Since
4.7
It uses the same algorithm used in setNamedColor().
See also
setNamedColor()
Definition at line 579 of file qcolor.cpp.
 {
     return !name.isEmpty() && QColor().setColorFromString(name);
 }
light()
QColor QColor::light (int factor = 150) const
Use lighter(factor) instead.
Definition at line 2391 of file qcolor.cpp.
Referenced by QWindowsStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsStyle::drawControl(), lighter(), and qt_set_windows_color_resources().
 {
     if (factor <= 0)                                // invalid lightness factor
         return *this;
     else if (factor < 100)                        // makes color darker
         return darker(10000 / factor);
     QColor hsv = toHsv();
     int s = hsv.ct.ahsv.saturation;
     int v = hsv.ct.ahsv.value;
     v = (factor*v)/100;
     if (v > USHRT_MAX) {
         // overflow... adjust saturation
         s -= v - USHRT_MAX;
         if (s < 0)
             s = 0;
         v = USHRT_MAX;
     }
     hsv.ct.ahsv.saturation = s;
     hsv.ct.ahsv.value = v;
     // convert back to same color spec as original color
     return hsv.convertTo(cspec);
 }
lighter()
QColor QColor::lighter (int factor = 150) const inline
Returns a lighter (or darker) color, but does not change this object.
Since
4.3
If the factor is greater than 100, this functions returns a lighter color. Setting factor to 150 returns a color that is 50% brighter. If the factor is less than 100, the return color is darker, but we recommend using the darker() function for this purpose. If the factor is 0 or negative, the return value is unspecified.
The function converts the current RGB color to HSV, multiplies the value (V) component by factor and converts the color back to RGB.
See also
darker(), isValid()
Definition at line 298 of file qcolor.h.
Referenced by QRenderRule::configurePalette(), dark(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QGtkStyle::drawControl(), QMacStyle::drawControl(), QStyleHelper::drawDial(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QDeclarativeEnginePrivate::lighter(), QDecorationWindows::paint(), QDecorationWindows::paintButton(), QCleanlooksStyle::polish(), qBrushLight(), qDrawEdge(), qDrawRoundedCorners(), qt_cleanlooks_draw_buttongradient(), qt_plastique_drawFrame(), qt_plastique_drawShadedPanel(), qt_set_windows_color_resources(), QCleanlooksStyle::standardPalette(), QCDEStyle::standardPalette(), QGtkStyle::standardPalette(), QStyle::standardPalette(), QMotifStyle::standardPalette(), QWindowsMobileStyle::standardPixmap(), and QScriptEdit::updateExtraSelections().
 { return light(f); }
lightness()
int QColor::lightness () const
Referenced by hslSaturation(), and toHsl().
lightnessF()
qreal QColor::lightnessF () const
Returns the lightness color component of this color.
Since
4.6
See also
value() getHslF()
Definition at line 1519 of file qcolor.cpp.
Referenced by lightnessF(), and operator<<().
 {
     if (cspec != Invalid && cspec != Hsl)
         return toHsl().lightnessF();
     return ct.ahsl.lightness / qreal(USHRT_MAX);
 }
magenta()
int QColor::magenta () const
Referenced by lightnessF().
magentaF()
qreal QColor::magentaF () const
Returns the magenta color component of this color.
See also
magenta(), getCmykF(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 1598 of file qcolor.cpp.
Referenced by magentaF(), and operator<<().
 {
     if (cspec != Invalid && cspec != Cmyk)
         return toCmyk().magentaF();
     return ct.acmyk.magenta / qreal(USHRT_MAX);
 }
name()
QString QColor::name () const
Returns the name of the color in the format "#RRGGBB"; i.e.
a "#" character followed by three two-digit hexadecimal numbers.
See also
setNamedColor()
Definition at line 529 of file qcolor.cpp.
Referenced by QmlJSDebugger::ToolBarColorBox::copyColorToClipboard(), QTextHtmlExporter::emitBackgroundAttribute(), QTextHtmlExporter::emitCharFormatStyle(), QTextHtmlExporter::emitFrameStyle(), generateWavyPixmap(), QmlJSDebugger::ToolBarColorBox::mouseMoveEvent(), QTextOdfWriter::writeBlockFormat(), and QTextOdfWriter::writeCharacterFormat().
 {
     QString s;
     s.sprintf("#%02x%02x%02x", red(), green(), blue());
     return s;
 }
operator QVariant()
QColor::operator QVariant () const
Returns the color as a QVariant.
Definition at line 2521 of file qcolor.cpp.
 {
     return QVariant(QVariant::Color, this);
 }
operator!=()
bool QColor::operator!= (const QColor & c) const
Returns true if this color has a different RGB and alpha values from color; otherwise returns false.
Definition at line 2514 of file qcolor.cpp.
 { return !operator==(color); }
operator=() [1/2]
QColor & QColor::operator= (const QColor & color)
Assigns a copy of color to this color, and returns a reference to it.
Definition at line 2464 of file qcolor.cpp.
Referenced by operator=().
 {
     cspec = color.cspec;
     ct.argb = color.ct.argb;
     return *this;
 }
operator=() [2/2]
QColor & QColor::operator= (Qt::GlobalColor color)
Assigns a copy of color and returns a reference to this color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2477 of file qcolor.cpp.
 {
     return operator=(QColor(color));
 }
operator==()
bool QColor::operator== (const QColor & c) const
Returns true if this color has the same RGB and alpha values as color; otherwise returns false.
Definition at line 2486 of file qcolor.cpp.
Referenced by operator!=().
 {
     if (cspec == Hsl && cspec == color.cspec) {
         return (ct.argb.alpha == color.ct.argb.alpha
                 && ((((ct.ahsl.hue % 36000) == (color.ct.ahsl.hue % 36000)))
                     || (ct.ahsl.hue == color.ct.ahsl.hue))
                 && (qAbs(ct.ahsl.saturation - color.ct.ahsl.saturation) < 50
                     || ct.ahsl.lightness == 0
                     || color.ct.ahsl.lightness == 0
                     || ct.ahsl.lightness == USHRT_MAX
                     || color.ct.ahsl.lightness == USHRT_MAX)
                 && (qAbs(ct.ahsl.lightness - color.ct.ahsl.lightness)) < 50);
     } else {
         return (cspec == color.cspec
                 && ct.argb.alpha == color.ct.argb.alpha
                 && (((cspec == QColor::Hsv)
                      && ((ct.ahsv.hue % 36000) == (color.ct.ahsv.hue % 36000)))
                     || (ct.ahsv.hue == color.ct.ahsv.hue))
                 && ct.argb.green == color.ct.argb.green
                 && ct.argb.blue  == color.ct.argb.blue
                 && ct.argb.pad   == color.ct.argb.pad);
     }
 }
red()
int QColor::red () const
Referenced by name(), setAlphaF(), setBlue(), and setGreen().
redF()
qreal QColor::redF () const
Returns the red color component of this color.
See also
setRedF(), red(), getRgbF()
Definition at line 1213 of file qcolor.cpp.
Referenced by QGLPixmapGLPaintDevice::beginPaint(), QGLWidgetGLPaintDevice::beginPaint(), QVGPaintEngine::clearRect(), QVGPixmapColorizeFilter::draw(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QVGCompositionHelper::fillBackground(), QVGPaintEngine::fillRegion(), operator<<(), qt_premultiplyColor(), redF(), QInternalMimeData::renderDataHelper(), QGLShaderProgram::setAttributeValue(), setBlueF(), QPSPrintEngine::setBrush(), QPdfEngine::setBrush(), QVGPaintEnginePrivate::setBrush(), setGreenF(), QGLPixmapDropShadowFilter::setUniforms(), QGLShaderProgram::setUniformValue(), QVGPaintEnginePrivate::setupColorRamp(), and QDeclarativeEnginePrivate::tint().
 {
     if (cspec != Invalid && cspec != Rgb)
         return toRgb().redF();
     return ct.argb.red / qreal(USHRT_MAX);
 }
rgb()
QColor::rgb () const
Returns the RGB value of the color.
Use getRgb() instead.
The alpha value is opaque.
See also
getRgb(), rgba()
Definition at line 1051 of file qcolor.cpp.
Referenced by QGLGlyphCache::allocTexture(), QGLContext::choosePixelFormat(), QX11PixmapData::createBitmapFromImage(), darkenPixmap(), QWindowsMobileStylePrivate::drawScrollbarGroove(), QWin32PrintEngine::drawTextItem(), QColorWell::dropEvent(), QX11PixmapData::fill(), QBitmap::fromImage(), QWindowsMobileStyle::generatedIconPixmap(), QColorShower::hsvEd(), makeBitmapCompliantIfNeeded(), operator<<(), QColorLuminancePicker::paintEvent(), QmlJSDebugger::ColorPickerTool::pickColor(), QCleanlooksStyle::polish(), qt_transparent_pixel(), QColorPicker::resizeEvent(), rgb(), QColorDialogPrivate::selectColor(), QPainter::setBackground(), QPainter::setBrush(), setColorFromString(), QColorDialog::setCurrentColor(), QGLColormap::setEntry(), QColorShower::setHsv(), QPainter::setPen(), QAhiScreen::solidFill(), QMotifStyle::standardPixmap(), QCommonStyle::styleHint(), QWindowsVistaStyle::styleHint(), QCleanlooksStyle::styleHint(), QX11PixmapData::toImage(), and QX11PaintEngine::updatePen().
 {
     if (cspec != Invalid && cspec != Rgb)
         return toRgb().rgb();
     return qRgb(ct.argb.red >> 8, ct.argb.green >> 8, ct.argb.blue >> 8);
 }
rgba()
QRgb QColor::rgba () const
Returns the RGB value of the color, including its alpha.
For an invalid color, the alpha value of the returned color is unspecified.
See also
setRgba(), rgb()
Definition at line 1019 of file qcolor.cpp.
Referenced by QPdfEnginePrivate::addImage(), QGLPixmapData::bind(), QRasterBuffer::colorizeBitmap(), colorizeBitmap(), QImageData::create(), QPixmap::createMaskFromColor(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QBlittablePixmapData::fill(), QMacPixmapData::fill(), QRasterPixmapData::fill(), QX11PixmapData::fill(), QVGPixmapData::fill(), QGLPixmapData::fill(), QImage::fill(), QGLPixmapData::fillImage(), QWindowsMobileStyle::generatedIconPixmap(), QDeclarativeCompiler::genLiteralAssignment(), QColorDialog::getRgba(), hash(), QGLPixmapData::paintEngine(), QColormap::pixel(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), QRenderRule::QRenderRule(), qt_conv16ToRgb(), qt_plastique_draw_gradient(), qt_plastique_draw_handle(), QSvgIOHandler::read(), rgba(), QPSPrintEngine::setBrush(), QPdfEngine::setBrush(), QSpanData::setup(), QAhiScreen::solidFill(), solidFill_template(), QWindowsMobileStyle::standardPixmap(), QGtkStyle::standardPixmap(), QCommonStyle::styleHint(), QStyleSheetStyle::styleHint(), QX11PaintEngine::updateBrush(), and QX11PaintEngine::updatePen().
 {
     if (cspec != Invalid && cspec != Rgb)
         return toRgb().rgba();
     return qRgba(ct.argb.red >> 8, ct.argb.green >> 8, ct.argb.blue >> 8, ct.argb.alpha >> 8);
 }
saturation()
int QColor::saturation () const
Referenced by hsvHue().
saturationF()
qreal QColor::saturationF () const
Returns the saturation color component of this color.
The color is implicitly converted to HSV.
See also
hsvSaturationF(), saturation() getHsvF(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 1392 of file qcolor.cpp.
Referenced by hsvSaturationF(), and operator<<().
 {
     return hsvSaturationF();
 }
setAllowX11ColorNames()
void QColor::setAllowX11ColorNames (bool enabled) static
Allow setNamedColor() to look up colors in the X11 color database if enabled.
By default, setNamedColor() does not look up colors in the X11 color database.
Note
This function is only available on the X11 platform.
See also
setNamedColor(), allowX11ColorNames()
Definition at line 2549 of file qcolor.cpp.
Referenced by qt_set_x11_resources().
 {
     ::allowX11ColorNames = enabled;
 }
setAlpha()
void QColor::setAlpha (int alpha)
Sets the alpha of this color to alpha.
Integer alpha is specified in the range 0-255.
See also
alpha(), alphaF(), {QColor::Alpha-Blended Drawing}{Alpha-Blended Drawing}
Definition at line 1094 of file qcolor.cpp.
Referenced by QTextLine::draw(), QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QMacStyle::drawControl(), QStyleHelper::drawDial(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsMobileStyle::generatedIconPixmap(), QPagePreview::paintEvent(), QLineEdit::paintEvent(), qt_plastique_draw_handle(), QGtkStyle::standardPixmap(), QX11PaintEngine::updateBrush(), and QX11PaintEngine::updatePen().
 {
     QCOLOR_INT_RANGE_CHECK("QColor::setAlpha", alpha);
     ct.argb.alpha = alpha * 0x101;
 }
setAlphaF()
void QColor::setAlphaF (qreal alpha)
Sets the alpha of this color to alpha.
qreal alpha is specified in the range 0.0-1.0.
See also
alphaF(), alpha(), {QColor::Alpha-Blended Drawing}{Alpha-Blended Drawing}
Definition at line 1117 of file qcolor.cpp.
Referenced by constructColor(), QMacStyle::drawControl(), QStyleHelper::drawDial(), QMacStyle::drawPrimitive(), QWidgetPrivate::drawWidget(), QCommonStyle::generatedIconPixmap(), make_widget_eventUPP(), qBrushSetAlphaF(), qt_premultiplyColor(), QItemDelegate::selected(), and QVGPaintEnginePrivate::setBrush().
 {
     QCOLOR_REAL_RANGE_CHECK("QColor::setAlphaF", alpha);
     qreal tmp = alpha * USHRT_MAX;
     ct.argb.alpha = qRound(tmp);
 }
setBlue()
void QColor::setBlue (int blue)
Sets the blue color component of this color to blue.
Integer components are specified in the range 0-255.
See also
blue(), blueF(), setRgb()
Definition at line 1199 of file qcolor.cpp.
Referenced by QCommandLinkButtonPrivate::mergedColors(), and mergedColors().
 {
     QCOLOR_INT_RANGE_CHECK("QColor::setBlue", blue);
     if (cspec != Rgb)
         setRgb(red(), green(), blue, alpha());
     else
         ct.argb.blue = blue * 0x101;
 }
setBlueF()
void QColor::setBlueF (qreal blue)
Sets the blue color component of this color to blue.
Float components are specified in the range 0.0-1.0.
See also
blueF(), blue(), setRgbF()
Definition at line 1282 of file qcolor.cpp.
Referenced by qt_premultiplyColor().
 {
     QCOLOR_REAL_RANGE_CHECK("QColor::setBlueF", blue);
     if (cspec != Rgb)
         setRgbF(redF(), greenF(), blue, alphaF());
     else
         ct.argb.blue = qRound(blue * USHRT_MAX);
 }
setCmyk()
void QColor::setCmyk (int c, int m, int y, int k, int a = 255)
Sets the color to CMYK values, c (cyan), m (magenta), y (yellow), k (black), and a (alpha-channel, i.e.
transparency).
All the values must be in the range 0-255.
See also
getCmyk(), setCmykF(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 2243 of file qcolor.cpp.
Referenced by QColor().
 {
     if (c < 0 || c > 255
         || m < 0 || m > 255
         || y < 0 || y > 255
         || k < 0 || k > 255
         || a < 0 || a > 255) {
         qWarning("QColor::setCmyk: CMYK parameters out of range");
         return;
     }
     cspec = Cmyk;
     ct.acmyk.alpha   = a * 0x101;
     ct.acmyk.cyan    = c * 0x101;
     ct.acmyk.magenta = m * 0x101;
     ct.acmyk.yellow  = y * 0x101;
     ct.acmyk.black   = k * 0x101;
 }
setCmykF()
void QColor::setCmykF (qreal c, qreal m, qreal y, qreal k, qreal a = 1.0)
Sets the color to CMYK values, c (cyan), m (magenta), y (yellow), k (black), and a (alpha-channel, i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
e. transparency).
All the values must be in the range 0.0-1.0.
\sa getCmykF() setCmyk(), {QColor#The CMYK Color Model}{The CMYK
Color Model}
Definition at line 2276 of file qcolor.cpp.
Referenced by qcolorFromCGColor().
 {
     if (c < qreal(0.0) || c > qreal(1.0)
         || m < qreal(0.0) || m > qreal(1.0)
         || y < qreal(0.0) || y > qreal(1.0)
         || k < qreal(0.0) || k > qreal(1.0)
         || a < qreal(0.0) || a > qreal(1.0)) {
         qWarning("QColor::setCmykF: CMYK parameters out of range");
         return;
     }
     cspec = Cmyk;
     ct.acmyk.alpha   = qRound(a * USHRT_MAX);
     ct.acmyk.cyan    = qRound(c * USHRT_MAX);
     ct.acmyk.magenta = qRound(m * USHRT_MAX);
     ct.acmyk.yellow  = qRound(y * USHRT_MAX);
     ct.acmyk.black   = qRound(k * USHRT_MAX);
 }
setColorFromString()
bool QColor::setColorFromString (const QString & name) private
Definition at line 584 of file qcolor.cpp.
Referenced by setNamedColor().
 {
     if (name.isEmpty()) {
         invalidate();
         return true;
     }
     if (name.startsWith(QLatin1Char('#'))) {
         QRgb rgb;
         if (qt_get_hex_rgb(name.constData(), name.length(), &rgb)) {
             setRgb(rgb);
             return true;
         } else {
             invalidate();
             return false;
         }
     }
 #ifndef QT_NO_COLORNAMES
     QRgb rgb;
     if (qt_get_named_rgb(name.constData(), name.length(), &rgb)) {
         setRgba(rgb);
         return true;
     } else
 #endif
     {
 #ifdef Q_WS_X11
         XColor result;
         if (allowX11ColorNames()
             && QApplication::instance()
             && QX11Info::display()
             && XParseColor(QX11Info::display(), QX11Info::appColormap(), name.toLatin1().constData(), &result)) {
             setRgb(result.red >> 8, result.green >> 8, result.blue >> 8);
             return true;
         } else
 #endif
         {
             invalidate();
             return false;
         }
     }
 }
setGreen()
void QColor::setGreen (int green)
Sets the green color component of this color to green.
Integer components are specified in the range 0-255.
See also
green(), greenF(), setRgb()
Definition at line 1170 of file qcolor.cpp.
Referenced by QCommandLinkButtonPrivate::mergedColors(), and mergedColors().
 {
     QCOLOR_INT_RANGE_CHECK("QColor::setGreen", green);
     if (cspec != Rgb)
         setRgb(red(), green, blue(), alpha());
     else
         ct.argb.green = green * 0x101;
 }
setGreenF()
void QColor::setGreenF (qreal green)
Sets the green color component of this color to green.
Float components are specified in the range 0.0-1.0.
See also
greenF(), green(), setRgbF()
Definition at line 1255 of file qcolor.cpp.
Referenced by qt_premultiplyColor().
 {
     QCOLOR_REAL_RANGE_CHECK("QColor::setGreenF", green);
     if (cspec != Rgb)
         setRgbF(redF(), green, blueF(), alphaF());
     else
         ct.argb.green = qRound(green * USHRT_MAX);
 }
setHsl()
void QColor::setHsl (int h, int s, int l, int a = 255)
Sets a HSL color value; h is the hue, s is the saturation, l is the lightness and a is the alpha component of the HSL color.
Since
4.6
The saturation, value and alpha-channel values must be in the range 0-255, and the hue value must be greater than -1.
See also
getHsl(), setHslF()
Definition at line 861 of file qcolor.cpp.
Referenced by QColor().
 {
     if (h < -1 || (uint)s > 255 || (uint)l > 255 || (uint)a > 255) {
         qWarning("QColor::setHsv: HSV parameters out of range");
         invalidate();
         return;
     }
     cspec = Hsl;
     ct.ahsl.alpha      = a * 0x101;
     ct.ahsl.hue        = h == -1 ? USHRT_MAX : (h % 360) * 100;
     ct.ahsl.saturation = s * 0x101;
     ct.ahsl.lightness  = l * 0x101;
     ct.ahsl.pad        = 0;
 }
setHslF()
void QColor::setHslF (qreal h, qreal s, qreal l, qreal a = 1.0)
Sets a HSL color lightness; h is the hue, s is the saturation, l is the lightness and a is the alpha component of the HSL color.
Since
4.6
All the values must be in the range 0.0-1.0.
See also
getHslF(), setHsl()
Definition at line 829 of file qcolor.cpp.
 {
     if (((h < qreal(0.0) || h > qreal(1.0)) && h != qreal(-1.0))
         || (s < qreal(0.0) || s > qreal(1.0))
         || (l < qreal(0.0) || l > qreal(1.0))
         || (a < qreal(0.0) || a > qreal(1.0))) {
         qWarning("QColor::setHsvF: HSV parameters out of range");
         return;
     }
     cspec = Hsl;
     ct.ahsl.alpha      = qRound(a * USHRT_MAX);
     ct.ahsl.hue        = h == qreal(-1.0) ? USHRT_MAX : qRound(h * 36000);
     ct.ahsl.saturation = qRound(s * USHRT_MAX);
     ct.ahsl.lightness  = qRound(l * USHRT_MAX);
     ct.ahsl.pad        = 0;
 }
setHsv()
void QColor::setHsv (int h, int s, int v, int a = 255)
Sets a HSV color value; h is the hue, s is the saturation, v is the value and a is the alpha component of the HSV color.
The saturation, value and alpha-channel values must be in the range 0-255, and the hue value must be greater than -1.
See also
getHsv(), setHsvF(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 734 of file qcolor.cpp.
Referenced by darkenPixmap(), QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QCleanlooksStyle::drawControl(), QStyleHelper::drawDial(), QCleanlooksStyle::drawPrimitive(), QColorShower::hsvEd(), QColorLuminancePicker::paintEvent(), QColor(), qt_cleanlooks_draw_mdibutton(), QColorPicker::resizeEvent(), QColorShower::setHsv(), and QGtkStyle::standardPalette().
 {
     if (h < -1 || (uint)s > 255 || (uint)v > 255 || (uint)a > 255) {
         qWarning("QColor::setHsv: HSV parameters out of range");
         invalidate();
         return;
     }
     cspec = Hsv;
     ct.ahsv.alpha      = a * 0x101;
     ct.ahsv.hue        = h == -1 ? USHRT_MAX : (h % 360) * 100;
     ct.ahsv.saturation = s * 0x101;
     ct.ahsv.value      = v * 0x101;
     ct.ahsv.pad        = 0;
 }
setHsvF()
void QColor::setHsvF (qreal h, qreal s, qreal v, qreal a = 1.0)
Sets a HSV color value; h is the hue, s is the saturation, v is the value and a is the alpha component of the HSV color.
All the values must be in the range 0.0-1.0.
See also
getHsvF(), setHsv(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 706 of file qcolor.cpp.
Referenced by QMacStyle::drawControl().
 {
     if (((h < qreal(0.0) || h > qreal(1.0)) && h != qreal(-1.0))
         || (s < qreal(0.0) || s > qreal(1.0))
         || (v < qreal(0.0) || v > qreal(1.0))
         || (a < qreal(0.0) || a > qreal(1.0))) {
         qWarning("QColor::setHsvF: HSV parameters out of range");
         return;
     }
     cspec = Hsv;
     ct.ahsv.alpha      = qRound(a * USHRT_MAX);
     ct.ahsv.hue        = h == qreal(-1.0) ? USHRT_MAX : qRound(h * 36000);
     ct.ahsv.saturation = qRound(s * USHRT_MAX);
     ct.ahsv.value      = qRound(v * USHRT_MAX);
     ct.ahsv.pad        = 0;
 }
setNamedColor()
void QColor::setNamedColor (const QString & name)
Sets the RGB value of this QColor to name, which may be in one of these formats:
#RGB (each of R, G, and B is a single hex digit)
#RRGGBB
#RRRGGGBBB
#RRRRGGGGBBBB
A name from the list of colors defined in the list of SVG color keyword names provided by the World Wide Web Consortium; for example, "steelblue" or "gainsboro". These color names work on all platforms. Note that these color names are not the same as defined by the Qt::GlobalColor enums, e.g. "green" and Qt::green does not refer to the same color.
transparent - representing the absence of a color.
X11 only: If allowX11ColorNames() returns true, any valid X11 color name. See the documentation for XParseColor() for information about valid X11 color names.
The color is invalid if name cannot be parsed.
See also
QColor(), name(), isValid(), allowX11ColorNames()
Definition at line 560 of file qcolor.cpp.
Referenced by QTextHtmlParser::applyAttributes(), and QCss::Parser::parseHexColor().
 {
     setColorFromString(name);
 }
setRed()
void QColor::setRed (int red)
Sets the red color component of this color to red.
Integer components are specified in the range 0-255.
See also
red(), redF(), setRgb()
Definition at line 1143 of file qcolor.cpp.
Referenced by QCommandLinkButtonPrivate::mergedColors(), and mergedColors().
 {
     QCOLOR_INT_RANGE_CHECK("QColor::setRed", red);
     if (cspec != Rgb)
         setRgb(red, green(), blue(), alpha());
     else
         ct.argb.red = red * 0x101;
 }
setRedF()
void QColor::setRedF (qreal red)
Sets the red color component of this color to red.
Float components are specified in the range 0.0-1.0.
See also
redF(), red(), setRgbF()
Definition at line 1227 of file qcolor.cpp.
Referenced by qt_premultiplyColor().
 {
     QCOLOR_REAL_RANGE_CHECK("QColor::setRedF", red);
     if (cspec != Rgb)
         setRgbF(red, greenF(), blueF(), alphaF());
     else
         ct.argb.red = qRound(red * USHRT_MAX);
 }
setRgb() [1/2]
void QColor::setRgb (int r, int g, int b, int a = 255)
Sets the RGB value to r, g, b and the alpha value to a.
All the values must be in the range 0-255.
See also
rgb(), getRgb(), setRgbF()
Definition at line 980 of file qcolor.cpp.
Referenced by QmlJSDebugger::ColorPickerTool::ColorPickerTool(), operator>>(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), QColor(), resolveColor(), rgb2hsv(), setBlue(), setColorFromString(), setGreen(), and setRed().
 {
     if ((uint)r > 255 || (uint)g > 255 || (uint)b > 255 || (uint)a > 255) {
         qWarning("QColor::setRgb: RGB parameters out of range");
         invalidate();
         return;
     }
     cspec = Rgb;
     ct.argb.alpha = a * 0x101;
     ct.argb.red   = r * 0x101;
     ct.argb.green = g * 0x101;
     ct.argb.blue  = b * 0x101;
     ct.argb.pad   = 0;
 }
setRgb() [2/2]
void QColor::setRgb (QRgb rgb)
Sets the RGB value to rgb.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The alpha value is set to opaque.
Definition at line 1066 of file qcolor.cpp.
 {
     cspec = Rgb;
     ct.argb.alpha = 0xffff;
     ct.argb.red   = qRed(rgb)   * 0x101;
     ct.argb.green = qGreen(rgb) * 0x101;
     ct.argb.blue  = qBlue(rgb)  * 0x101;
     ct.argb.pad   = 0;
 }
setRgba()
void QColor::setRgba (QRgb rgba)
Use setRgb() instead.
Sets the RGB value to rgba, including its alpha.
See also
rgba(), rgb()
Definition at line 1031 of file qcolor.cpp.
Referenced by setColorFromString(), and QColorShower::updateQColor().
 {
     cspec = Rgb;
     ct.argb.alpha = qAlpha(rgba) * 0x101;
     ct.argb.red   = qRed(rgba)   * 0x101;
     ct.argb.green = qGreen(rgba) * 0x101;
     ct.argb.blue  = qBlue(rgba)  * 0x101;
     ct.argb.pad   = 0;
 }
setRgbF()
void QColor::setRgbF (qreal r, qreal g, qreal b, qreal a = 1.0)
Sets the color channels of this color to r (red), g (green), b (blue) and a (alpha, transparency).
All values must be in the range 0.0-1.0.
See also
rgb(), getRgbF(), setRgb()
Definition at line 954 of file qcolor.cpp.
Referenced by qcolorFromCGColor(), QInternalMimeData::retrieveData(), setBlueF(), setGreenF(), setRedF(), and QDeclarativeEnginePrivate::tint().
 {
     if (r < qreal(0.0) || r > qreal(1.0)
         || g < qreal(0.0) || g > qreal(1.0)
         || b < qreal(0.0) || b > qreal(1.0)
         || a < qreal(0.0) || a > qreal(1.0)) {
         qWarning("QColor::setRgbF: RGB parameters out of range");
         invalidate();
         return;
     }
     cspec = Rgb;
     ct.argb.alpha = qRound(a * USHRT_MAX);
     ct.argb.red   = qRound(r * USHRT_MAX);
     ct.argb.green = qRound(g * USHRT_MAX);
     ct.argb.blue  = qRound(b * USHRT_MAX);
     ct.argb.pad   = 0;
 }
spec()
Spec QColor::spec () const inline
Returns how the color was specified.
See also
Spec, convertTo()
Definition at line 88 of file qcolor.h.
Referenced by operator<<(), and QColorDialogPrivate::setCocoaPanelColor().
     { return cspec; }
toCmyk()
QColor QColor::toCmyk () const
Creates and returns a CMYK QColor based on this color.
See also
fromCmyk(), convertTo(), isValid(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 1891 of file qcolor.cpp.
Referenced by blackF(), convertTo(), cyanF(), getCmyk(), getCmykF(), lightnessF(), magentaF(), toCmyk(), and yellowF().
 {
     if (!isValid() || cspec == Cmyk)
         return *this;
     if (cspec != Rgb)
         return toRgb().toCmyk();
     QColor color;
     color.cspec = Cmyk;
     color.ct.acmyk.alpha = ct.argb.alpha;
     // rgb -> cmy
     const qreal r = ct.argb.red   / qreal(USHRT_MAX);
     const qreal g = ct.argb.green / qreal(USHRT_MAX);
     const qreal b = ct.argb.blue  / qreal(USHRT_MAX);
     qreal c = qreal(1.0) - r;
     qreal m = qreal(1.0) - g;
     qreal y = qreal(1.0) - b;
     // cmy -> cmyk
     const qreal k = qMin(c, qMin(m, y));
     if (!qFuzzyIsNull(k - 1)) {
         c = (c - k) / (qreal(1.0) - k);
         m = (m - k) / (qreal(1.0) - k);
         y = (y - k) / (qreal(1.0) - k);
     }
     color.ct.acmyk.cyan    = qRound(c * USHRT_MAX);
     color.ct.acmyk.magenta = qRound(m * USHRT_MAX);
     color.ct.acmyk.yellow  = qRound(y * USHRT_MAX);
     color.ct.acmyk.black   = qRound(k * USHRT_MAX);
     return color;
 }
toHsl()
QColor QColor::toHsl () const
Creates and returns an HSL QColor based on this color.
See also
fromHsl(), convertTo(), isValid()
Definition at line 1834 of file qcolor.cpp.
Referenced by convertTo(), getHsl(), getHslF(), hslHue(), hslHueF(), hslSaturation(), hslSaturationF(), lightnessF(), and toHsl().
 {
     if (!isValid() || cspec == Hsl)
         return *this;
     if (cspec != Rgb)
         return toRgb().toHsl();
     QColor color;
     color.cspec = Hsl;
     color.ct.ahsl.alpha = ct.argb.alpha;
     color.ct.ahsl.pad = 0;
     const qreal r = ct.argb.red   / qreal(USHRT_MAX);
     const qreal g = ct.argb.green / qreal(USHRT_MAX);
     const qreal b = ct.argb.blue  / qreal(USHRT_MAX);
     const qreal max = Q_MAX_3(r, g, b);
     const qreal min = Q_MIN_3(r, g, b);
     const qreal delta = max - min;
     const qreal delta2 = max + min;
     const qreal lightness = qreal(0.5) * delta2;
     color.ct.ahsl.lightness = qRound(lightness * USHRT_MAX);
     if (qFuzzyIsNull(delta)) {
         // achromatic case, hue is undefined
         color.ct.ahsl.hue = USHRT_MAX;
         color.ct.ahsl.saturation = 0;
     } else {
         // chromatic case
         qreal hue = 0;
         if (lightness < qreal(0.5))
             color.ct.ahsl.saturation = qRound((delta / delta2) * USHRT_MAX);
         else
             color.ct.ahsl.saturation = qRound((delta / (qreal(2.0) - delta2)) * USHRT_MAX);
         if (qFuzzyCompare(r, max)) {
             hue = ((g - b) /delta);
         } else if (qFuzzyCompare(g, max)) {
             hue = (qreal(2.0) + (b - r) / delta);
         } else if (qFuzzyCompare(b, max)) {
             hue = (qreal(4.0) + (r - g) / delta);
         } else {
             Q_ASSERT_X(false, "QColor::toHsv", "internal error");
         }
         hue *= qreal(60.0);
         if (hue < qreal(0.0))
             hue += qreal(360.0);
         color.ct.ahsl.hue = qRound(hue * 100);
     }
     return color;
 }
toHsv()
QColor QColor::toHsv () const
Creates and returns an HSV QColor based on this color.
See also
fromHsv(), convertTo(), isValid(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 1783 of file qcolor.cpp.
Referenced by convertTo(), dark(), getHsv(), getHsvF(), hsvHue(), hsvHueF(), hsvSaturation(), hsvSaturationF(), light(), toHsv(), and valueF().
 {
     if (!isValid() || cspec == Hsv)
         return *this;
     if (cspec != Rgb)
         return toRgb().toHsv();
     QColor color;
     color.cspec = Hsv;
     color.ct.ahsv.alpha = ct.argb.alpha;
     color.ct.ahsv.pad = 0;
     const qreal r = ct.argb.red   / qreal(USHRT_MAX);
     const qreal g = ct.argb.green / qreal(USHRT_MAX);
     const qreal b = ct.argb.blue  / qreal(USHRT_MAX);
     const qreal max = Q_MAX_3(r, g, b);
     const qreal min = Q_MIN_3(r, g, b);
     const qreal delta = max - min;
     color.ct.ahsv.value = qRound(max * USHRT_MAX);
     if (qFuzzyIsNull(delta)) {
         // achromatic case, hue is undefined
         color.ct.ahsv.hue = USHRT_MAX;
         color.ct.ahsv.saturation = 0;
     } else {
         // chromatic case
         qreal hue = 0;
         color.ct.ahsv.saturation = qRound((delta / max) * USHRT_MAX);
         if (qFuzzyCompare(r, max)) {
             hue = ((g - b) /delta);
         } else if (qFuzzyCompare(g, max)) {
             hue = (qreal(2.0) + (b - r) / delta);
         } else if (qFuzzyCompare(b, max)) {
             hue = (qreal(4.0) + (r - g) / delta);
         } else {
             Q_ASSERT_X(false, "QColor::toHsv", "internal error");
         }
         hue *= qreal(60.0);
         if (hue < qreal(0.0))
             hue += qreal(360.0);
         color.ct.ahsv.hue = qRound(hue * 100);
     }
     return color;
 }
toRgb()
QColor QColor::toRgb () const
Create and returns an RGB QColor based on this color.
See also
fromRgb(), convertTo(), isValid()
Definition at line 1636 of file qcolor.cpp.
Referenced by blueF(), convertTo(), getRgb(), getRgbF(), greenF(), redF(), rgb(), rgba(), setAlphaF(), setGreen(), setRed(), toCmyk(), toHsl(), and toHsv().
 {
     if (!isValid() || cspec == Rgb)
         return *this;
     QColor color;
     color.cspec = Rgb;
     color.ct.argb.alpha = ct.argb.alpha;
     color.ct.argb.pad = 0;
     switch (cspec) {
     case Hsv:
         {
             if (ct.ahsv.saturation == 0 || ct.ahsv.hue == USHRT_MAX) {
                 // achromatic case
                 color.ct.argb.red = color.ct.argb.green = color.ct.argb.blue = ct.ahsv.value;
                 break;
             }
             // chromatic case
             const qreal h = ct.ahsv.hue == 36000 ? 0 : ct.ahsv.hue / qreal(6000.);
             const qreal s = ct.ahsv.saturation / qreal(USHRT_MAX);
             const qreal v = ct.ahsv.value / qreal(USHRT_MAX);
             const int i = int(h);
             const qreal f = h - i;
             const qreal p = v * (qreal(1.0) - s);
             if (i & 1) {
                 const qreal q = v * (qreal(1.0) - (s * f));
                 switch (i) {
                 case 1:
                     color.ct.argb.red   = qRound(q * USHRT_MAX);
                     color.ct.argb.green = qRound(v * USHRT_MAX);
                     color.ct.argb.blue  = qRound(p * USHRT_MAX);
                     break;
                 case 3:
                     color.ct.argb.red   = qRound(p * USHRT_MAX);
                     color.ct.argb.green = qRound(q * USHRT_MAX);
                     color.ct.argb.blue  = qRound(v * USHRT_MAX);
                     break;
                 case 5:
                     color.ct.argb.red   = qRound(v * USHRT_MAX);
                     color.ct.argb.green = qRound(p * USHRT_MAX);
                     color.ct.argb.blue  = qRound(q * USHRT_MAX);
                     break;
                 }
             } else {
                 const qreal t = v * (qreal(1.0) - (s * (qreal(1.0) - f)));
                 switch (i) {
                 case 0:
                     color.ct.argb.red   = qRound(v * USHRT_MAX);
                     color.ct.argb.green = qRound(t * USHRT_MAX);
                     color.ct.argb.blue  = qRound(p * USHRT_MAX);
                     break;
                 case 2:
                     color.ct.argb.red   = qRound(p * USHRT_MAX);
                     color.ct.argb.green = qRound(v * USHRT_MAX);
                     color.ct.argb.blue  = qRound(t * USHRT_MAX);
                     break;
                 case 4:
                     color.ct.argb.red   = qRound(t * USHRT_MAX);
                     color.ct.argb.green = qRound(p * USHRT_MAX);
                     color.ct.argb.blue  = qRound(v * USHRT_MAX);
                     break;
                 }
             }
             break;
         }
     case Hsl:
         {
             if (ct.ahsl.saturation == 0 || ct.ahsl.hue == USHRT_MAX) {
                 // achromatic case
                 color.ct.argb.red = color.ct.argb.green = color.ct.argb.blue = ct.ahsl.lightness;
             } else if (ct.ahsl.lightness == 0) {
                 // lightness 0
                 color.ct.argb.red = color.ct.argb.green = color.ct.argb.blue = 0;
             } else {
                 // chromatic case
                 const qreal h = ct.ahsl.hue == 36000 ? 0 : ct.ahsl.hue / qreal(36000.);
                 const qreal s = ct.ahsl.saturation / qreal(USHRT_MAX);
                 const qreal l = ct.ahsl.lightness / qreal(USHRT_MAX);
                 qreal temp2;
                 if (l < qreal(0.5))
                     temp2 = l * (qreal(1.0) + s);
                 else
                     temp2 = l + s - (l * s);
                 const qreal temp1 = (qreal(2.0) * l) - temp2;
                 qreal temp3[3] = { h + (qreal(1.0) / qreal(3.0)),
                                    h,
                                    h - (qreal(1.0) / qreal(3.0)) };
                 for (int i = 0; i != 3; ++i) {
                     if (temp3[i] < qreal(0.0))
                         temp3[i] += qreal(1.0);
                     else if (temp3[i] > qreal(1.0))
                         temp3[i] -= qreal(1.0);
                     const qreal sixtemp3 = temp3[i] * qreal(6.0);
                     if (sixtemp3 < qreal(1.0))
                         color.ct.array[i+1] = qRound((temp1 + (temp2 - temp1) * sixtemp3) * USHRT_MAX);
                     else if ((temp3[i] * qreal(2.0)) < qreal(1.0))
                         color.ct.array[i+1] = qRound(temp2 * USHRT_MAX);
                     else if ((temp3[i] * qreal(3.0)) < qreal(2.0))
                         color.ct.array[i+1] = qRound((temp1 + (temp2 -temp1) * (qreal(2.0) /qreal(3.0) - temp3[i]) * qreal(6.0)) * USHRT_MAX);
                     else
                         color.ct.array[i+1] = qRound(temp1 * USHRT_MAX);
                 }
                 color.ct.argb.red = color.ct.argb.red == 1 ? 0 : color.ct.argb.red;
                 color.ct.argb.green = color.ct.argb.green == 1 ? 0 : color.ct.argb.green;
                 color.ct.argb.blue = color.ct.argb.blue == 1 ? 0 : color.ct.argb.blue;
             }
             break;
         }
     case Cmyk:
         {
             const qreal c = ct.acmyk.cyan / qreal(USHRT_MAX);
             const qreal m = ct.acmyk.magenta / qreal(USHRT_MAX);
             const qreal y = ct.acmyk.yellow / qreal(USHRT_MAX);
             const qreal k = ct.acmyk.black / qreal(USHRT_MAX);
             color.ct.argb.red   = qRound((qreal(1.0) - (c * (qreal(1.0) - k) + k)) * USHRT_MAX);
             color.ct.argb.green = qRound((qreal(1.0) - (m * (qreal(1.0) - k) + k)) * USHRT_MAX);
             color.ct.argb.blue  = qRound((qreal(1.0) - (y * (qreal(1.0) - k) + k)) * USHRT_MAX);
             break;
         }
     default:
         break;
     }
     return color;
 }
value()
int QColor::value () const
Referenced by hsvSaturation().
valueF()
qreal QColor::valueF () const
Returns the value color component of this color.
See also
value() getHsvF(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 1416 of file qcolor.cpp.
Referenced by operator<<(), and valueF().
 {
     if (cspec != Invalid && cspec != Hsv)
         return toHsv().valueF();
     return ct.ahsv.value / qreal(USHRT_MAX);
 }
yellow()
int QColor::yellow () const
Referenced by lightnessF().
yellowF()
qreal QColor::yellowF () const
Returns the yellow color component of this color.
See also
yellow(), getCmykF(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 1611 of file qcolor.cpp.
Referenced by operator<<(), and yellowF().
 {
     if (cspec != Invalid && cspec != Cmyk)
         return toCmyk().yellowF();
     return ct.acmyk.yellow / qreal(USHRT_MAX);
 }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & stream, const QColor & color) friend
Writes the color to the stream.
See also
{Serializing Qt Data Types}
Definition at line 2638 of file qcolor.cpp.
 {
     if (stream.version() < 7) {
         if (!color.isValid())
             return stream << quint32(0x49000000);
         quint32 p = (quint32)color.rgb();
         if (stream.version() == 1) // Swap red and blue
             p = ((p << 16) & 0xff0000) | ((p >> 16) & 0xff) | (p & 0xff00ff00);
         return stream << p;
     }
     qint8   s = color.cspec;
     quint16 a = color.ct.argb.alpha;
     quint16 r = color.ct.argb.red;
     quint16 g = color.ct.argb.green;
     quint16 b = color.ct.argb.blue;
     quint16 p = color.ct.argb.pad;
     stream << s;
     stream << a;
     stream << r;
     stream << g;
     stream << b;
     stream << p;
     return stream;
 }
operator>>
QDataStream & operator>> (QDataStream & stream, QColor & color) friend
Reads the color from the stream.
See also
{Serializing Qt Data Types}
Definition at line 2677 of file qcolor.cpp.
 {
     if (stream.version() < 7) {
         quint32 p;
         stream >> p;
         if (p == 0x49000000) {
             color.invalidate();
             return stream;
         }
         if (stream.version() == 1) // Swap red and blue
             p = ((p << 16) & 0xff0000) | ((p >> 16) & 0xff) | (p & 0xff00ff00);
         color.setRgb(p);
         return stream;
     }
     qint8 s;
     quint16 a, r, g, b, p;
     stream >> s;
     stream >> a;
     stream >> r;
     stream >> g;
     stream >> b;
     stream >> p;
     color.cspec = QColor::Spec(s);
     color.ct.argb.alpha = a;
     color.ct.argb.red   = r;
     color.ct.argb.green = g;
     color.ct.argb.blue  = b;
     color.ct.argb.pad   = p;
     return stream;
 }
qAlpha()
int qAlpha (QRgb rgba) related
Returns the alpha component of the ARGB quadruplet rgba.
See also
qRgb(), QColor::alpha()
Definition at line 66 of file qrgb.h.
Referenced by destStoreARGB32(), fromRgba(), QColor(), setRgba(), and sourceOver().
 { return rgb >> 24; }
qBlue()
int qBlue (QRgb rgb) related
Returns the blue component of the ARGB quadruplet rgb.
See also
qRgb(), QColor::blue()
Definition at line 63 of file qrgb.h.
Referenced by destStoreARGB32(), findNearestColor(), fromRgb(), fromRgba(), QColor(), qGray(), qIsGray(), qt_convRgbTo16(), qt_write_dib(), setRgb(), setRgba(), and write_pbm_image().
 { return (rgb & 0xff); }
QColormap
friend class QColormap friend
Definition at line 272 of file qcolor.h.
qGray() [1/2]
int qGray (int r, int g, int b) related
Returns a gray value (0 to 255) from the (r, g, b) triplet.
The gray value is calculated using the formula (r * 11 + g * 16 + b * 5)/32.
Definition at line 75 of file qrgb.h.
Referenced by destStoreMono(), destStoreMonoLsb(), qGray(), read_dib_body(), write_pbm_image(), and write_xbm_image().
 { return (r*11+g*16+b*5)/32; }
qGray() [2/2]
int qGray (QRgb rgb) related
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns a gray value (0 to 255) from the given ARGB quadruplet rgb.
The gray value is calculated using the formula (R * 11 + G * 16 + B * 5)/32; the alpha-channel is ignored.
Definition at line 78 of file qrgb.h.
 { return qGray(qRed(rgb), qGreen(rgb), qBlue(rgb)); }
qGreen()
int qGreen (QRgb rgb) related
Returns the green component of the ARGB quadruplet rgb.
See also
qRgb(), QColor::green()
Definition at line 60 of file qrgb.h.
Referenced by destStoreARGB32(), findNearestColor(), fromRgb(), fromRgba(), QColor(), qGray(), qIsGray(), qt_convRgbTo16(), qt_write_dib(), setRgb(), setRgba(), and write_pbm_image().
 { return ((rgb >> 8) & 0xff); }
qRed()
int qRed (QRgb rgb) related
Returns the red component of the ARGB quadruplet rgb.
See also
qRgb(), QColor::red()
Definition at line 57 of file qrgb.h.
Referenced by destStoreARGB32(), findNearestColor(), fromRgb(), fromRgba(), QColor(), qGray(), qIsGray(), qt_convRgbTo16(), qt_write_dib(), setRgb(), setRgba(), and write_pbm_image().
 { return ((rgb >> 16) & 0xff); }
qRgb()
QRgb qRgb (int r, int g, int b) related
Returns the ARGB quadruplet (255, {r}, {g}, {b}).
See also
qRgba(), qRed(), qGreen(), qBlue()
Definition at line 69 of file qrgb.h.
Referenced by convert_rgb888_to_rgb32_C(), qsvg_get_hex_rgb(), qt_conv16ToRgb(), qt_get_hex_rgb(), read_dib_body(), read_pbm_body(), read_xbm_body(), and rgb().
 { return (0xffu << 24) | ((r & 0xff) << 16) | ((g & 0xff) << 8) | (b & 0xff); }
QRgb()
QRgb related
An ARGB quadruplet on the format #AARRGGBB, equivalent to an unsigned int.
The type also holds a value for the alpha-channel. The default alpha channel is ff, i.e opaque. For more information, see the Alpha-Blended Drawing section.
See also
QColor::rgb(), QColor::rgba()
qRgba()
QRgb qRgba (int r, int g, int b, int a) related
Returns the ARGB quadruplet ({a}, {r}, {g}, {b}).
See also
qRgb(), qRed(), qGreen(), qBlue()
Definition at line 72 of file qrgb.h.
Referenced by rgba().
 { return ((a & 0xff) << 24) | ((r & 0xff) << 16) | ((g & 0xff) << 8) | (b & 0xff); }
Properties
acmyk
struct { ... } QColor::acmyk
Referenced by fromCmyk(), fromCmykF(), and toCmyk().
ahsl
struct { ... } QColor::ahsl
Referenced by fromHsl(), fromHslF(), operator==(), and toHsl().
ahsv
struct { ... } QColor::ahsv
Referenced by dark(), fromHsv(), fromHsvF(), light(), operator==(), and toHsv().
alpha
int QColor::alpha
Returns the alpha color component of this color.
See also
setAlpha(), alphaF(), {QColor::Alpha-Blended Drawing}{Alpha-Blended Drawing}
Definition at line 242 of file qcolor.h.
Referenced by _q_interpolate(), QPdfEnginePrivate::addBrushPattern(), QDirectFbBlitter::alphaFillRect(), QSvgAnimateColor::apply(), cgColorForQColor(), clearRect(), QDirectFBScreen::connect(), QBlittablePixmapData::fill(), QMacPixmapData::fill(), QDirectFBPixmapData::fill(), QRasterPixmapData::fill(), QX11PixmapData::fill(), QPixmap::fill(), QGLPixmapData::fill(), QX11PaintEnginePrivate::fillPolygon_dev(), QBlitterPaintEngine::fillRect(), QVGPaintEngine::fillRect(), QBrush::isOpaque(), QX11Data::preMultiply(), QDirectFBPaintEnginePrivate::prepareForDraw(), qt_mix_colors(), QDeclarativePen::setColor(), QColorDialog::setCurrentColor(), QOpenGLPaintEnginePrivate::setGLBrush(), QOpenGLPaintEnginePrivate::setGLPen(), QDeclarativePen::setWidth(), QGtkStyle::standardPalette(), QDeclarativeEnginePrivate::tint(), QX11PaintEngine::updateBrush(), QBlitterPaintEnginePrivate::updateBrushState(), QPainterPrivate::updateEmulationSpecifier(), and QX11PaintEngine::updatePen().
argb
struct { ... } QColor::argb
Referenced by fromRgb(), fromRgbF(), operator<<(), operator=(), operator==(), operator>>(), QColor(), and toRgb().
array
ushort QColor::array[5]
Definition at line 269 of file qcolor.h.
Referenced by toRgb().
black
int QColor::black
Returns the black color component of this color.
See also
blackF(), getCmyk(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 260 of file qcolor.h.
Referenced by lightnessF().
blue
int QColor::blue
Returns the blue color component of this color.
See also
setBlue(), blueF(), getRgb()
Definition at line 245 of file qcolor.h.
Referenced by _q_interpolate(), QDirectFbBlitter::alphaFillRect(), QSvgAnimateColor::apply(), QAccessibleTextWidget::attributes(), cgColorForQColor(), clearRect(), QDirectFBScreen::connect(), QWindowsXPStyle::drawControl(), QWindowsMobileStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QDirectFBPixmapData::fill(), QWin32PrintEnginePrivate::fillPath_dev(), fromQColor(), QCommonStyle::generatedIconPixmap(), QCommandLinkButtonPrivate::mergedColors(), mergedColors(), QStaticTextPrivate::paintText(), QX11Data::preMultiply(), QDirectFBPaintEnginePrivate::prepareForDraw(), QColorToOLEColor(), qt_graphicsItem_highlightSelected(), qt_mac_display_change_callbk(), qt_mix_colors(), qt_set_windows_color_resources(), qt_transparent_pixel(), QMngHandlerPrivate::setBackgroundColor(), QCoreGraphicsPaintEnginePrivate::setFillBrush(), QOpenGLPaintEnginePrivate::setGLBrush(), QOpenGLPaintEnginePrivate::setGLPen(), setGreen(), QGtkStyle::standardPalette(), QWin32PrintEnginePrivate::strokePath_dev(), and translate_color().
cspec
Spec QColor::cspec private
Definition at line 239 of file qcolor.h.
Referenced by blackF(), blueF(), convertTo(), cyanF(), dark(), fromCmyk(), fromCmykF(), fromHsl(), fromHslF(), fromHsv(), fromHsvF(), fromRgb(), fromRgbF(), getCmyk(), getCmykF(), getHsl(), getHslF(), getHsv(), getHsvF(), getRgb(), getRgbF(), greenF(), hslHue(), hslHueF(), hslSaturation(), hslSaturationF(), hsvHue(), hsvHueF(), hsvSaturation(), hsvSaturationF(), invalidate(), isValid(), light(), lightnessF(), magentaF(), operator<<(), operator=(), operator==(), operator>>(), QColor(), redF(), rgb(), rgba(), setAlphaF(), setBlue(), setBlueF(), setCmyk(), setCmykF(), setGreen(), setGreenF(), setHsl(), setHslF(), setHsv(), setHsvF(), setRed(), setRedF(), setRgb(), setRgba(), setRgbF(), toCmyk(), toHsl(), toHsv(), toRgb(), valueF(), and yellowF().
ct
union { ... } QColor::ct
Referenced by alphaF(), blackF(), blueF(), cyanF(), dark(), fromCmyk(), fromCmykF(), fromHsl(), fromHslF(), fromHsv(), fromHsvF(), fromRgb(), fromRgbF(), getCmyk(), getCmykF(), getHsl(), getHslF(), getHsv(), getHsvF(), getRgb(), getRgbF(), greenF(), hslHue(), hslHueF(), hslSaturation(), hslSaturationF(), hsvHue(), hsvHueF(), hsvSaturation(), hsvSaturationF(), invalidate(), light(), lightnessF(), magentaF(), operator<<(), operator=(), operator==(), operator>>(), QColor(), redF(), rgb(), rgba(), setAlpha(), setAlphaF(), setBlue(), setBlueF(), setCmyk(), setCmykF(), setGreen(), setGreenF(), setHsl(), setHslF(), setHsv(), setHsvF(), setRed(), setRedF(), setRgb(), setRgba(), setRgbF(), toCmyk(), toHsl(), toHsv(), toRgb(), valueF(), and yellowF().
cyan
int QColor::cyan
Returns the cyan color component of this color.
See also
cyanF(), getCmyk(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 257 of file qcolor.h.
Referenced by lightnessF().
green
int QColor::green
Returns the green color component of this color.
See also
setGreen(), greenF(), getRgb()
Definition at line 244 of file qcolor.h.
Referenced by _q_interpolate(), QDirectFbBlitter::alphaFillRect(), QSvgAnimateColor::apply(), QAccessibleTextWidget::attributes(), cgColorForQColor(), clearRect(), QDirectFBScreen::connect(), QWindowsXPStyle::drawControl(), QWindowsMobileStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QDirectFBPixmapData::fill(), QWin32PrintEnginePrivate::fillPath_dev(), fromQColor(), QCommonStyle::generatedIconPixmap(), QCommandLinkButtonPrivate::mergedColors(), mergedColors(), QStaticTextPrivate::paintText(), QX11Data::preMultiply(), QDirectFBPaintEnginePrivate::prepareForDraw(), QColorToOLEColor(), qt_graphicsItem_highlightSelected(), qt_mac_display_change_callbk(), qt_mix_colors(), qt_set_windows_color_resources(), qt_transparent_pixel(), QMngHandlerPrivate::setBackgroundColor(), QCoreGraphicsPaintEnginePrivate::setFillBrush(), QOpenGLPaintEnginePrivate::setGLBrush(), QOpenGLPaintEnginePrivate::setGLPen(), setRed(), QGtkStyle::standardPalette(), QWin32PrintEnginePrivate::strokePath_dev(), and translate_color().
hue
int QColor::hue
Returns the hue color component of this color.
The color is implicitly converted to HSV.
See also
hsvHue(), hueF(), getHsv(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 250 of file qcolor.h.
Referenced by QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QCleanlooksStyle::drawControl(), QStyleHelper::drawDial(), QCleanlooksStyle::drawPrimitive(), hsvHue(), qt_cleanlooks_draw_mdibutton(), and QGtkStyle::standardPalette().
lightness
int QColor::lightness
Returns the lightness color component of this color.
Since
4.6
See also
lightnessF(), getHsl()
Definition at line 266 of file qcolor.h.
Referenced by hslSaturation().
magenta
int QColor::magenta
Returns the magenta color component of this color.
See also
magentaF(), getCmyk(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 258 of file qcolor.h.
Referenced by lightnessF().
pad
ushort QColor::pad
Definition at line 246 of file qcolor.h.
red
int QColor::red
Returns the red color component of this color.
See also
setRed(), redF(), getRgb()
Definition at line 243 of file qcolor.h.
Referenced by _q_interpolate(), QDirectFbBlitter::alphaFillRect(), QSvgAnimateColor::apply(), QAccessibleTextWidget::attributes(), cgColorForQColor(), clearRect(), QDirectFBScreen::connect(), QWindowsXPStyle::drawControl(), QWindowsMobileStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QDirectFBPixmapData::fill(), QWin32PrintEnginePrivate::fillPath_dev(), fromQColor(), QCommonStyle::generatedIconPixmap(), QCommandLinkButtonPrivate::mergedColors(), mergedColors(), QStaticTextPrivate::paintText(), QX11Data::preMultiply(), QDirectFBPaintEnginePrivate::prepareForDraw(), QColorToOLEColor(), qt_graphicsItem_highlightSelected(), qt_mac_display_change_callbk(), qt_mix_colors(), qt_set_windows_color_resources(), qt_transparent_pixel(), QLinuxFbScreen::set(), setAlphaF(), QMngHandlerPrivate::setBackgroundColor(), QCoreGraphicsPaintEnginePrivate::setFillBrush(), QOpenGLPaintEnginePrivate::setGLBrush(), QOpenGLPaintEnginePrivate::setGLPen(), QGtkStyle::standardPalette(), QWin32PrintEnginePrivate::strokePath_dev(), and translate_color().
saturation
int QColor::saturation
Returns the saturation color component of this color.
The color is implicitly converted to HSV.
See also
hsvSaturation(), saturationF(), getHsv(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 251 of file qcolor.h.
Referenced by QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QCleanlooksStyle::drawControl(), QStyleHelper::drawDial(), QCleanlooksStyle::drawPrimitive(), hsvSaturation(), and qt_cleanlooks_draw_mdibutton().
value
int QColor::value
Returns the value color component of this color.
See also
valueF(), getHsv(), {QColor::The HSV Color Model}{The HSV Color Model}
Definition at line 252 of file qcolor.h.
Referenced by QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QCleanlooksStyle::drawControl(), QStyleHelper::drawDial(), QCleanlooksStyle::drawPrimitive(), hsvSaturation(), qBrushSetAlphaF(), qt_cleanlooks_draw_mdibutton(), and QGtkStyle::standardPalette().
yellow
int QColor::yellow
Returns the yellow color component of this color.
See also
yellowF(), getCmyk(), {QColor::The CMYK Color Model}{The CMYK Color Model}
Definition at line 259 of file qcolor.h.
Referenced by lightnessF().
The documentation for this class was generated from the following files:
/src/gui/painting/qcolor.h
/src/gui/painting/qcolor.cpp