Qt 4.8: QMeeGoExtensions Class Reference
QMeeGoExtensions Class Reference
#include <qmeegoextensions.h>
Static Public Functions
static EGLint eglClientWaitSyncKHR (EGLDisplay dpy, EGLSyncKHR sync, EGLint flags, EGLTimeKHR timeout)
static EGLNativeSharedImageTypeNOK eglCreateSharedImageNOK (EGLDisplay dpy, EGLImageKHR image, EGLint *props)
static EGLSyncKHR eglCreateSyncKHR (EGLDisplay dpy, EGLenum type, const EGLint *attrib_list)
static bool eglDestroySharedImageNOK (EGLDisplay dpy, EGLNativeSharedImageTypeNOK img)
static bool eglDestroySyncKHR (EGLDisplay dpy, EGLSyncKHR sync)
static EGLBoolean eglGetSyncAttribKHR (EGLDisplay dpy, EGLSyncKHR sync, EGLint attribute, EGLint *value)
static bool eglLockSurfaceKHR (EGLDisplay display, EGLSurface surface, const EGLint *attrib_list)
static bool eglQueryImageNOK (EGLDisplay dpy, EGLImageKHR image, EGLint prop, EGLint *v)
static bool eglSetSurfaceScalingNOK (EGLDisplay dpy, EGLSurface surface, int x, int y, int width, int height)
static bool eglUnlockSurfaceKHR (EGLDisplay display, EGLSurface surface)
static void ensureInitialized ()
Static Private Functions
static void initialize ()
Static Private Attributes
static bool hasFenceSync = false
static bool hasImageShared = false
static bool hasLockSurface = false
static bool hasSurfaceScaling = false
static bool initialized = false
Detailed Description
Definition at line 99 of file qmeegoextensions.h.
Functions
eglClientWaitSyncKHR()
EGLint QMeeGoExtensions::eglClientWaitSyncKHR (EGLDisplay dpy, EGLSyncKHR sync, EGLint flags, EGLTimeKHR timeout) static
Definition at line 150 of file qmeegoextensions.cpp.
Referenced by QMeeGoLivePixmapData::lock().
 {
     if (!hasFenceSync)
         qFatal("EGL_KHR_fence_sync not found but trying to use capability!");
     return _eglClientWaitSyncKHR(dpy, sync, flags, timeout);
 }
eglCreateSharedImageNOK()
EGLNativeSharedImageTypeNOK QMeeGoExtensions::eglCreateSharedImageNOK (EGLDisplay dpy, EGLImageKHR image, EGLint * props) static
Definition at line 86 of file qmeegoextensions.cpp.
Referenced by QMeeGoPixmapData::imageToEGLSharedImage().
 {
     if (!hasImageShared)
         qFatal("EGL_NOK_image_shared not found but trying to use capability!");
     return _eglCreateSharedImageNOK(dpy, image, props);
 }
eglCreateSyncKHR()
EGLSyncKHR QMeeGoExtensions::eglCreateSyncKHR (EGLDisplay dpy, EGLenum type, const EGLint * attrib_list) static
Definition at line 134 of file qmeegoextensions.cpp.
Referenced by QMeeGoGraphicsSystem::createFenceSync().
 {
     if (!hasFenceSync)
         qFatal("EGL_KHR_fence_sync not found but trying to use capability!");
     return _eglCreateSyncKHR(dpy, type, attrib_list);
 }
eglDestroySharedImageNOK()
bool QMeeGoExtensions::eglDestroySharedImageNOK (EGLDisplay dpy, EGLNativeSharedImageTypeNOK img) static
Definition at line 102 of file qmeegoextensions.cpp.
Referenced by QMeeGoPixmapData::destroyEGLSharedImage().
 {
     if (!hasImageShared)
         qFatal("EGL_NOK_image_shared not found but trying to use capability!");
     return _eglDestroySharedImageNOK(dpy, img);
 }
eglDestroySyncKHR()
bool QMeeGoExtensions::eglDestroySyncKHR (EGLDisplay dpy, EGLSyncKHR sync) static
Definition at line 142 of file qmeegoextensions.cpp.
Referenced by QMeeGoGraphicsSystem::destroyFenceSync().
 {
     if (!hasFenceSync)
         qFatal("EGL_KHR_fence_sync not found but trying to use capability!");
     return _eglDestroySyncKHR(dpy, sync);
 }
eglGetSyncAttribKHR()
EGLBoolean QMeeGoExtensions::eglGetSyncAttribKHR (EGLDisplay dpy, EGLSyncKHR sync, EGLint attribute, EGLint * value) static
Definition at line 158 of file qmeegoextensions.cpp.
 {
     if (!hasFenceSync)
         qFatal("EGL_KHR_fence_sync not found but trying to use capability!");
     return _eglGetSyncAttribKHR(dpy, sync, attribute, value);
 }
eglLockSurfaceKHR()
bool QMeeGoExtensions::eglLockSurfaceKHR (EGLDisplay display, EGLSurface surface, const EGLint * attrib_list) static
Definition at line 118 of file qmeegoextensions.cpp.
Referenced by QMeeGoLivePixmapData::lock().
 {
     if (!hasLockSurface)
         qFatal("EGL_KHR_lock_surface2 not found but trying to use capability!");
     return _eglLockSurfaceKHR(display, surface, attrib_list);
 }
eglQueryImageNOK()
bool QMeeGoExtensions::eglQueryImageNOK (EGLDisplay dpy, EGLImageKHR image, EGLint prop, EGLint * v) static
Definition at line 94 of file qmeegoextensions.cpp.
Referenced by QMeeGoPixmapData::fromEGLSharedImage().
 {
     if (!hasImageShared)
         qFatal("EGL_NOK_image_shared not found but trying to use capability!");
     return _eglQueryImageNOK(dpy, image, prop, v);
 }
eglSetSurfaceScalingNOK()
bool QMeeGoExtensions::eglSetSurfaceScalingNOK (EGLDisplay dpy, EGLSurface surface, int x, int y, int width, int height) static
Definition at line 110 of file qmeegoextensions.cpp.
Referenced by QMeeGoGraphicsSystem::setSurfaceScaling().
 {
     if (!hasSurfaceScaling)
         qFatal("EGL_NOK_surface_scaling not found but trying to use capability!");
    return _eglSetSurfaceScalingNOK(dpy, surface, x, y, width, height);
 }
eglUnlockSurfaceKHR()
bool QMeeGoExtensions::eglUnlockSurfaceKHR (EGLDisplay display, EGLSurface surface) static
Definition at line 126 of file qmeegoextensions.cpp.
Referenced by QMeeGoLivePixmapData::lock(), and QMeeGoLivePixmapData::release().
 {
     if (!hasLockSurface)
         qFatal("EGL_KHR_lock_surface2 not found but trying to use capability!");
     return _eglUnlockSurfaceKHR(display, surface);
 }
ensureInitialized()
void QMeeGoExtensions::ensureInitialized () static
Definition at line 78 of file qmeegoextensions.cpp.
Referenced by QMeeGoGraphicsSystem::createFenceSync(), QMeeGoPixmapData::destroyEGLSharedImage(), QMeeGoGraphicsSystem::destroyFenceSync(), QMeeGoPixmapData::fromEGLSharedImage(), QMeeGoPixmapData::imageToEGLSharedImage(), QMeeGoLivePixmapData::initializeThroughEGLImage(), QMeeGoLivePixmapData::lock(), QMeeGoLivePixmapData::release(), and QMeeGoGraphicsSystem::setSurfaceScaling().
 {
     if (!initialized)
         initialize();
     initialized = true;
 }
initialize()
void QMeeGoExtensions::initialize () static private
Definition at line 168 of file qmeegoextensions.cpp.
Referenced by ensureInitialized().
 {
     QGLContext *ctx = (QGLContext *) QGLContext::currentContext();
     qt_resolve_eglimage_gl_extensions(ctx);
     if (QEgl::hasExtension("EGL_NOK_image_shared")) {
         qDebug("MeegoGraphics: found EGL_NOK_image_shared");
         _eglQueryImageNOK = (eglQueryImageNOKFunc) eglGetProcAddress("eglQueryImageNOK");
         _eglCreateSharedImageNOK = (eglCreateSharedImageNOKFunc) eglGetProcAddress("eglCreateSharedImageNOK");
         _eglDestroySharedImageNOK = (eglDestroySharedImageNOKFunc) eglGetProcAddress("eglDestroySharedImageNOK");
         _eglLockSurfaceKHR = (eglLockSurfaceKHRFunc) eglGetProcAddress("eglLockSurfaceKHR");
         _eglUnlockSurfaceKHR = (eglUnlockSurfaceKHRFunc) eglGetProcAddress("eglUnlockSurfaceKHR");
         Q_ASSERT(_eglQueryImageNOK && _eglCreateSharedImageNOK && _eglDestroySharedImageNOK);
         hasImageShared = true;
     }
     if (QEgl::hasExtension("EGL_NOK_surface_scaling")) {
         qDebug("MeegoGraphics: found EGL_NOK_surface_scaling");
         _eglSetSurfaceScalingNOK = (eglSetSurfaceScalingNOKFunc) eglGetProcAddress("eglSetSurfaceScalingNOK");
         Q_ASSERT(_eglSetSurfaceScalingNOK);
         hasSurfaceScaling = true;
     }
     if (QEgl::hasExtension("EGL_KHR_lock_surface2")) {
         qDebug("MeegoGraphics: found EGL_KHR_lock_surface2");
         _eglLockSurfaceKHR = (eglLockSurfaceKHRFunc) eglGetProcAddress("eglLockSurfaceKHR");
         _eglUnlockSurfaceKHR = (eglUnlockSurfaceKHRFunc) eglGetProcAddress("eglUnlockSurfaceKHR");
         Q_ASSERT(_eglLockSurfaceKHR && _eglUnlockSurfaceKHR);
         hasLockSurface = true;
     }
     if (QEgl::hasExtension("EGL_KHR_fence_sync")) {
         qDebug("MeegoGraphics: found EGL_KHR_fence_sync");
         _eglCreateSyncKHR = (eglCreateSyncKHRFunc) eglGetProcAddress("eglCreateSyncKHR");
         _eglDestroySyncKHR = (eglDestroySyncKHRFunc) eglGetProcAddress("eglDestroySyncKHR");
         _eglClientWaitSyncKHR = (eglClientWaitSyncKHRFunc) eglGetProcAddress("eglClientWaitSyncKHR");
         _eglGetSyncAttribKHR = (eglGetSyncAttribKHRFunc) eglGetProcAddress("eglGetSyncAttribKHR");
         Q_ASSERT(_eglCreateSyncKHR && _eglDestroySyncKHR && _eglClientWaitSyncKHR && _eglGetSyncAttribKHR);
         hasFenceSync = true;
     }
 }
Properties
hasFenceSync
bool QMeeGoExtensions::hasFenceSync = false static private
Definition at line 122 of file qmeegoextensions.h.
Referenced by eglClientWaitSyncKHR(), eglCreateSyncKHR(), eglDestroySyncKHR(), eglGetSyncAttribKHR(), and initialize().
hasImageShared
bool QMeeGoExtensions::hasImageShared = false static private
Definition at line 119 of file qmeegoextensions.h.
Referenced by eglCreateSharedImageNOK(), eglDestroySharedImageNOK(), eglQueryImageNOK(), and initialize().
hasLockSurface
bool QMeeGoExtensions::hasLockSurface = false static private
Definition at line 121 of file qmeegoextensions.h.
Referenced by eglLockSurfaceKHR(), eglUnlockSurfaceKHR(), and initialize().
hasSurfaceScaling
bool QMeeGoExtensions::hasSurfaceScaling = false static private
Definition at line 120 of file qmeegoextensions.h.
Referenced by eglSetSurfaceScalingNOK(), and initialize().
initialized
bool QMeeGoExtensions::initialized = false static private
Definition at line 118 of file qmeegoextensions.h.
Referenced by ensureInitialized().
The documentation for this class was generated from the following files:
/src/plugins/graphicssystems/meego/qmeegoextensions.h
/src/plugins/graphicssystems/meego/qmeegoextensions.cpp