Qt 4.8: QTreeView Class Reference
QTreeView Class Reference
The QTreeView class provides a default model/view implementation of a tree view.
#include <qtreeview.h>
Public Slots
void collapse (const QModelIndex &index)
Collapses the model item specified by the index.
void collapseAll ()
Collapses all expanded items.
void expand (const QModelIndex &index)
Expands the model item specified by the index.
void expandAll ()
Expands all expandable items.
void expandToDepth (int depth)
Expands all expandable items to the given depth.
void hideColumn (int column)
Hides the column given.
void resizeColumnToContents (int column)
Resizes the column given to the size of its contents.
void showColumn (int column)
Shows the given column in the tree view.
void sortByColumn (int column)
Sorts the model by the values in the given column.
Public Slots inherited from QAbstractItemView
void clearSelection ()
Deselects all selected items.
void edit (const QModelIndex &index)
Starts editing the item corresponding to the given index if it is editable.
void scrollToBottom ()
Scrolls the view to the bottom.
void scrollToTop ()
Scrolls the view to the top.
void setCurrentIndex (const QModelIndex &index)
Sets the current item to be the item at index.
void update (const QModelIndex &index)
Updates the area occupied by the given index.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void collapsed (const QModelIndex &index)
This signal is emitted when the item specified by index is collapsed.
void expanded (const QModelIndex &index)
This signal is emitted when the item specified by index is expanded.
Signals inherited from QAbstractItemView
void activated (const QModelIndex &index)
This signal is emitted when the item specified by index is activated by the user.
void clicked (const QModelIndex &index)
This signal is emitted when a mouse button is clicked.
void doubleClicked (const QModelIndex &index)
This signal is emitted when a mouse button is double-clicked.
void entered (const QModelIndex &index)
This signal is emitted when the mouse cursor enters the item specified by index.
void pressed (const QModelIndex &index)
This signal is emitted when a mouse button is pressed.
void viewportEntered ()
This signal is emitted when the mouse cursor enters the viewport.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool allColumnsShowFocus () const
int autoExpandDelay () const
int columnAt (int x) const
Returns the column in the tree view whose header covers the x coordinate given.
int columnViewportPosition (int column) const
Returns the horizontal position of the column in the viewport.
int columnWidth (int column) const
Returns the width of the column.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
Reimplemented Function
void doItemsLayout ()
Lays out the items in the tree view.
bool expandsOnDoubleClick () const
QHeaderView * header () const
Returns the header for the tree view.
int indentation () const
QModelIndex indexAbove (const QModelIndex &index) const
Returns the model index of the item above index.
QModelIndex indexAt (const QPoint &p) const
Reimplemented Function
QModelIndex indexBelow (const QModelIndex &index) const
Returns the model index of the item below index.
bool isAnimated () const
bool isColumnHidden (int column) const
Returns true if the column is hidden; otherwise returns false.
bool isExpanded (const QModelIndex &index) const
Returns true if the model item index is expanded; otherwise returns false.
bool isFirstColumnSpanned (int row, const QModelIndex &parent) const
Returns true if the item in first column in the given row of the parent is spanning all the columns; otherwise returns false.
bool isHeaderHidden () const
bool isRowHidden (int row, const QModelIndex &parent) const
Returns true if the item in the given row of the parent is hidden; otherwise returns false.
bool isSortingEnabled () const
bool itemsExpandable () const
void keyboardSearch (const QString &search)
Reimplemented Function
QTreeView (QWidget *parent=0)
Constructs a tree view with a parent to represent a model's data.
void reset ()
Reimplemented Function
bool rootIsDecorated () const
void scrollTo (const QModelIndex &index, ScrollHint hint=EnsureVisible)
Scroll the contents of the tree view until the given model item index is visible.
void selectAll ()
Reimplemented Function
void setAllColumnsShowFocus (bool enable)
void setAnimated (bool enable)
void setAutoExpandDelay (int delay)
void setColumnHidden (int column, bool hide)
If hide is true the column is hidden, otherwise the column is shown.
void setColumnWidth (int column, int width)
Sets the width of the given column to the width specified.
void setExpanded (const QModelIndex &index, bool expand)
Sets the item referred to by index to either collapse or expanded, depending on the value of expanded.
void setExpandsOnDoubleClick (bool enable)
void setFirstColumnSpanned (int row, const QModelIndex &parent, bool span)
If span is true the item in the first column in the row with the given parent is set to span all columns, otherwise all items on the row are shown.
void setHeader (QHeaderView *header)
Sets the header for the tree view, to the given header.
void setHeaderHidden (bool hide)
void setIndentation (int i)
void setItemsExpandable (bool enable)
void setModel (QAbstractItemModel *model)
Reimplemented Function
void setRootIndex (const QModelIndex &index)
Reimplemented Function
void setRootIsDecorated (bool show)
void setRowHidden (int row, const QModelIndex &parent, bool hide)
If hide is true the row with the given parent is hidden, otherwise the row is shown.
void setSelectionModel (QItemSelectionModel *selectionModel)
Reimplemented Function
void setSortingEnabled (bool enable)
void setUniformRowHeights (bool uniform)
void setWordWrap (bool on)
void sortByColumn (int column, Qt::SortOrder order)
Sets the model up for sorting by the values in the given column and order.
bool uniformRowHeights () const
QRect visualRect (const QModelIndex &index) const
Returns the rectangle on the viewport occupied by the item at index.
bool wordWrap () const
~QTreeView ()
Destroys the tree view.
Public Functions inherited from QAbstractItemView
bool alternatingRowColors () const
int autoScrollMargin () const
void closePersistentEditor (const QModelIndex &index)
Closes the persistent editor for the item at the given index.
QModelIndex currentIndex () const
Returns the model index of the current item.
Qt::DropAction defaultDropAction () const
DragDropMode dragDropMode () const
bool dragDropOverwriteMode () const
bool dragEnabled () const
EditTriggers editTriggers () const
bool hasAutoScroll () const
ScrollMode horizontalScrollMode () const
QSize iconSize () const
QWidget * indexWidget (const QModelIndex &index) const
Returns the widget for the item at the given index.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
Reimplemented Function
QAbstractItemDelegate * itemDelegate () const
Returns the item delegate used by this view and model.
QAbstractItemDelegate * itemDelegate (const QModelIndex &index) const
Returns the item delegate used by this view and model for the given index.
QAbstractItemDelegate * itemDelegateForColumn (int column) const
Returns the item delegate used by this view and model for the given column.
QAbstractItemDelegate * itemDelegateForRow (int row) const
Returns the item delegate used by this view and model for the given row, or 0 if no delegate has been assigned.
QAbstractItemModel * model () const
Returns the model that this view is presenting.
void openPersistentEditor (const QModelIndex &index)
Opens a persistent editor on the item at the given index.
QAbstractItemView (QWidget *parent=0)
Constructs an abstract item view with the given parent.
QModelIndex rootIndex () const
Returns the model index of the model's root item.
QAbstractItemView::SelectionBehavior selectionBehavior () const
QAbstractItemView::SelectionMode selectionMode () const
QItemSelectionModel * selectionModel () const
Returns the current selection model.
void setAlternatingRowColors (bool enable)
void setAutoScroll (bool enable)
void setAutoScrollMargin (int margin)
void setDefaultDropAction (Qt::DropAction dropAction)
void setDragDropMode (DragDropMode behavior)
void setDragDropOverwriteMode (bool overwrite)
void setDragEnabled (bool enable)
void setDropIndicatorShown (bool enable)
void setEditTriggers (EditTriggers triggers)
void setHorizontalScrollMode (ScrollMode mode)
void setIconSize (const QSize &size)
void setIndexWidget (const QModelIndex &index, QWidget *widget)
Sets the given widget on the item at the given index, passing the ownership of the widget to the viewport.
void setItemDelegate (QAbstractItemDelegate *delegate)
Sets the item delegate for this view and its model to delegate.
void setItemDelegateForColumn (int column, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given column.
void setItemDelegateForRow (int row, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given row.
void setSelectionBehavior (QAbstractItemView::SelectionBehavior behavior)
void setSelectionMode (QAbstractItemView::SelectionMode mode)
void setTabKeyNavigation (bool enable)
void setTextElideMode (Qt::TextElideMode mode)
void setVerticalScrollMode (ScrollMode mode)
bool showDropIndicator () const
QSize sizeHintForIndex (const QModelIndex &index) const
Returns the size hint for the item with the specified index or an invalid size for invalid indexes.
virtual int sizeHintForRow (int row) const
Returns the height size hint for the specified row or -1 if there is no model.
bool tabKeyNavigation () const
Qt::TextElideMode textElideMode () const
ScrollMode verticalScrollMode () const
~QAbstractItemView ()
Destroys the view.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Slots
void columnCountChanged (int oldCount, int newCount)
Informs the tree view that the number of columns in the tree view has changed from oldCount to newCount.
void columnMoved ()
This slot is called whenever a column has been moved.
void columnResized (int column, int oldSize, int newSize)
This function is called whenever {column}'s size is changed in the header.
void reexpand ()
void rowsRemoved (const QModelIndex &parent, int first, int last)
Informs the view that the rows from the start row to the end row inclusive have been removed from the given parent model item.
Protected Slots inherited from QAbstractItemView
virtual void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
Closes the given editor, and releases it.
virtual void commitData (QWidget *editor)
Commit the data in the editor to the model.
virtual void editorDestroyed (QObject *editor)
This function is called when the given editor has been destroyed.
virtual void horizontalScrollbarValueChanged (int value)
virtual void updateEditorData ()
Updates the data shown in the open editor widgets in the view.
virtual void updateEditorGeometries ()
Updates the geometry of the open editor widgets in the view.
virtual void verticalScrollbarAction (int action)
virtual void verticalScrollbarValueChanged (int value)
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Functions
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
Reimplemented Function
void dragMoveEvent (QDragMoveEvent *event)
Reimplemented Function
virtual void drawBranches (QPainter *painter, const QRect &rect, const QModelIndex &index) const
Draws the branches in the tree view on the same row as the model item index, using the painter given.
virtual void drawRow (QPainter *painter, const QStyleOptionViewItem &options, const QModelIndex &index) const
Draws the row in the tree view that contains the model item index, using the painter given.
void drawTree (QPainter *painter, const QRegion &region) const
Draws the part of the tree intersecting the given region using the specified painter.
int horizontalOffset () const
Returns the horizontal offset of the items in the treeview.
void horizontalScrollbarAction (int action)
int indexRowSizeHint (const QModelIndex &index) const
Returns the size hint for the row indicated by index.
bool isIndexHidden (const QModelIndex &index) const
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
Reimplemented Function
void mouseDoubleClickEvent (QMouseEvent *event)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *event)
Reimplemented Function
void mousePressEvent (QMouseEvent *event)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *event)
Reimplemented Function
QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers)
Move the cursor in the way described by cursorAction, using the information provided by the button modifiers.
void paintEvent (QPaintEvent *event)
Reimplemented Function
QTreeView (QTreeViewPrivate &dd, QWidget *parent=0)
int rowHeight (const QModelIndex &index) const
Returns the height of the row indicated by the given index.
void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
Informs the view that the rows from the start row to the end row inclusive are about to removed from the given parent model item.
void rowsInserted (const QModelIndex &parent, int start, int end)
Informs the view that the rows from the start row to the end row inclusive have been inserted into the parent model item.
void scrollContentsBy (int dx, int dy)
Scrolls the contents of the tree view by (dx, dy).
QModelIndexList selectedIndexes () const
Reimplemented Function
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Reimplemented Function
void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags command)
Applies the selection command to the items in or touched by the rectangle, rect.
int sizeHintForColumn (int column) const
Returns the size hint for the column's width or -1 if there is no model.
void timerEvent (QTimerEvent *event)
Reimplemented Function
void updateGeometries ()
Reimplemented Function
int verticalOffset () const
Returns the vertical offset of the items in the tree view.
bool viewportEvent (QEvent *event)
Reimplemented Function
QRegion visualRegionForSelection (const QItemSelection &selection) const
Returns the rectangle from the viewport of the items in the given selection.
Protected Functions inherited from QAbstractItemView
QPoint dirtyRegionOffset () const
Returns the offset of the dirty regions in the view.
void doAutoScroll ()
void dragEnterEvent (QDragEnterEvent *event)
This function is called with the given event when a drag and drop operation enters the widget.
void dragLeaveEvent (QDragLeaveEvent *event)
This function is called when the item being dragged leaves the view.
void dropEvent (QDropEvent *event)
This function is called with the given event when a drop event occurs over the widget.
DropIndicatorPosition dropIndicatorPosition () const
Returns the position of the drop indicator in relation to the closest item.
virtual bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event)
Starts editing the item at index, creating an editor if necessary, and returns true if the view's State is now EditingState; otherwise returns false.
bool event (QEvent *event)
Reimplemented Function
void executeDelayedItemsLayout ()
Executes the scheduled layouts without waiting for the event processing to begin.
void focusInEvent (QFocusEvent *event)
This function is called with the given event when the widget obtains the focus.
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
This function is called with the given event when the widget looses the focus.
int horizontalStepsPerItem () const
Returns the horizontal scroll bar's steps per item.
void inputMethodEvent (QInputMethodEvent *event)
Reimplemented Function
QAbstractItemView (QAbstractItemViewPrivate &, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
This function is called with the given event when a resize event is sent to the widget.
void scheduleDelayedItemsLayout ()
Schedules a layout of the items in the view to be executed when the event processing starts.
void scrollDirtyRegion (int dx, int dy)
Prepares the view for scrolling by ({dx},{dy}) pixels by moving the dirty regions in the opposite direction.
virtual QItemSelectionModel::SelectionFlags selectionCommand (const QModelIndex &index, const QEvent *event=0) const
Returns the SelectionFlags to be used when updating a selection with to include the index specified.
void setDirtyRegion (const QRegion &region)
Marks the given region as dirty and schedules it to be updated.
void setHorizontalStepsPerItem (int steps)
Sets the horizontal scroll bar's steps per item to steps.
void setState (State state)
Sets the item view's state to the given state.
void setVerticalStepsPerItem (int steps)
Sets the vertical scroll bar's steps per item to steps.
void startAutoScroll ()
virtual void startDrag (Qt::DropActions supportedActions)
Starts a drag by calling drag->exec() using the given supportedActions.
State state () const
Returns the item view's state.
void stopAutoScroll ()
int verticalStepsPerItem () const
Returns the vertical scroll bar's steps per item.
virtual QStyleOptionViewItem viewOptions () const
Returns a QStyleOptionViewItem structure populated with the view's palette, font, state, alignments etc.
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Functions
int visualIndex (const QModelIndex &index) const
Properties
bool allColumnsShowFocus
whether items should show keyboard focus using all columns
bool animated
whether animations are enabled
int autoExpandDelay
The delay time before items in a tree are opened during a drag and drop operation.
bool expandsOnDoubleClick
whether the items can be expanded by double-clicking.
bool headerHidden
whether the header is shown or not.
int indentation
indentation of the items in the tree view.
bool itemsExpandable
whether the items are expandable by the user.
bool rootIsDecorated
whether to show controls for expanding and collapsing top-level items
bool sortingEnabled
whether sorting is enabled
bool uniformRowHeights
whether all items in the treeview have the same height
bool wordWrap
the item text word-wrapping policy
Friends
class QAccessibleItemView
class QAccessibleTable2
class QAccessibleTable2Cell
class QAccessibleTree
Additional Inherited Members
Public Types inherited from QAbstractItemView
enum DragDropMode {
NoDragDrop, DragOnly, DropOnly, DragDrop,
InternalMove
}
Describes the various drag and drop events the view can act upon.
enum EditTrigger {
NoEditTriggers = 0, CurrentChanged = 1, DoubleClicked = 2, SelectedClicked = 4,
EditKeyPressed = 8, AnyKeyPressed = 16, AllEditTriggers = 31
}
This enum describes actions which will initiate item editing.
enum ScrollHint { EnsureVisible, PositionAtTop, PositionAtBottom, PositionAtCenter }
enum ScrollMode { ScrollPerItem, ScrollPerPixel }
enum SelectionBehavior { SelectItems, SelectRows, SelectColumns }
enum SelectionMode {
NoSelection, SingleSelection, MultiSelection, ExtendedSelection,
ContiguousSelection
}
This enum indicates how the view responds to user selections:
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QAbstractItemView
enum CursorAction {
MoveUp, MoveDown, MoveLeft, MoveRight,
MoveHome, MoveEnd, MovePageUp, MovePageDown,
MoveNext, MovePrevious
}
This enum describes the different ways to navigate between items,.
enum DropIndicatorPosition { OnItem, AboveItem, BelowItem, OnViewport }
This enum indicates the position of the drop indicator in relation to the index at the current mouse position:
enum State {
NoState, DraggingState, DragSelectingState, EditingState,
ExpandingState, CollapsingState, AnimatingState
}
Describes the different states the view can be in.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QTreeView class provides a default model/view implementation of a tree view.
A QTreeView implements a tree representation of items from a model. This class is used to provide standard hierarchical lists that were previously provided by the QListView class, but using the more flexible approach provided by Qt's model/view architecture.
The QTreeView class is one of the Model/View Classes and is part of Qt's Model/View Programming{model/view framework}.
QTreeView implements the interfaces defined by the QAbstractItemView class to allow it to display data provided by models derived from the QAbstractItemModel class.
It is simple to construct a tree view displaying data from a model. In the following example, the contents of a directory are supplied by a QFileSystemModel and displayed as a tree:
    QFileSystemModel *model = new QFileSystemModel;
    model->setRootPath(QDir::currentPath());
    QTreeView *tree = new QTreeView(splitter);
    tree->setModel(model);
The model/view architecture ensures that the contents of the tree view are updated as the model changes.
Items that have children can be in an expanded (children are visible) or collapsed (children are hidden) state. When this state changes a collapsed() or expanded() signal is emitted with the model index of the relevant item.
The amount of indentation used to indicate levels of hierarchy is controlled by the indentation property.
Headers in tree views are constructed using the QHeaderView class and can be hidden using header()->hide(). Note that each header is configured with its QHeaderView::stretchLastSection property set to true, ensuring that the view does not waste any of the space assigned to it for its header. If this value is set to true, this property will override the resize mode set on the last section in the header.
Key Bindings
QTreeView supports a set of key bindings that enable the user to navigate in the view and interact with the contents of items:
Key Action
Up Moves the cursor to the item in the same column on the previous row. If the parent of the current item has no more rows to navigate to, the cursor moves to the relevant item in the last row of the sibling that precedes the parent.
Down Moves the cursor to the item in the same column on the next row. If the parent of the current item has no more rows to navigate to, the cursor moves to the relevant item in the first row of the sibling that follows the parent.
Left Hides the children of the current item (if present) by collapsing a branch.
Minus Same as LeftArrow.
Right Reveals the children of the current item (if present) by expanding a branch.
Plus Same as RightArrow.
Asterisk Expands all children of the current item (if present).
PageUp Moves the cursor up one page.
PageDown Moves the cursor down one page.
Home Moves the cursor to an item in the same column of the first row of the first top-level item in the model.
End Moves the cursor to an item in the same column of the last row of the last top-level item in the model.
F2 In editable models, this opens the current item for editing. The Escape key can be used to cancel the editing process and revert any changes to the data displayed.
Warning
This function is not part of the public interface. Describe the expanding/collapsing concept if not covered elsewhere.
Screenshot of a Windows XP style tree view
Screenshot of a Macintosh style tree view
Screenshot of a Plastique style tree view
A Windows XP Style Widget Gallery{Windows XP style} tree view. A Macintosh Style Widget Gallery{Macintosh style} tree view. A Plastique Style Widget Gallery{Plastique style} tree view.
Improving Performance
It is possible to give the view hints about the data it is handling in order to improve its performance when displaying large numbers of items. One approach that can be taken for views that are intended to display items with equal heights is to set the uniformRowHeights property to true.
See also
QListView, QTreeWidget, {View Classes}, QAbstractItemModel, QAbstractItemView, {Dir View Example}
Definition at line 58 of file qtreeview.h.
Constructors and Destructors
QTreeView() [1/2]
QTreeView::QTreeView (QWidget * parent = 0) explicit
Constructs a tree view with a parent to represent a model's data.
Use setModel() to set the model.
See also
QAbstractItemModel
Definition at line 196 of file qtreeview.cpp.
     : QAbstractItemView(*new QTreeViewPrivate, parent)
 {
     Q_D(QTreeView);
     d->initialize();
 }
~QTreeView()
QTreeView::~QTreeView ()
Destroys the tree view.
Definition at line 216 of file qtreeview.cpp.
 {
 }
QTreeView() [2/2]
QTreeView::QTreeView (QTreeViewPrivate & dd, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 206 of file qtreeview.cpp.
     : QAbstractItemView(dd, parent)
 {
     Q_D(QTreeView);
     d->initialize();
 }
Functions
allColumnsShowFocus()
bool QTreeView::allColumnsShowFocus () const
Referenced by currentChanged(), drawRow(), and setAllColumnsShowFocus().
autoExpandDelay()
int QTreeView::autoExpandDelay () const
Referenced by setHeader().
collapse
void QTreeView::collapse (const QModelIndex & index) slot
Collapses the model item specified by the index.
See also
collapsed()
Definition at line 821 of file qtreeview.cpp.
Referenced by QTreeWidget::collapseItem(), QTreeViewPrivate::expandOrCollapseItemAtPos(), keyPressEvent(), and setExpanded().
 {
     Q_D(QTreeView);
     if (!d->isIndexValid(index))
         return;
     //if the current item is now invisible, the autoscroll will expand the tree to see it, so disable the autoscroll
     d->delayedAutoScroll.stop();
     if (d->delayedPendingLayout) {
         //A complete relayout is going to be performed, just un-store the expanded index, no need to layout.
         if (d->isPersistent(index) && d->expandedIndexes.remove(index))
             emit collapsed(index);
         return;
     }
     int i = d->viewIndex(index);
     if (i != -1) { // is visible
         d->collapse(i, true);
         if (!d->isAnimating()) {
             updateGeometries();
             viewport()->update();
         }
     } else {
         if (d->isPersistent(index) && d->expandedIndexes.remove(index))
             emit collapsed(index);
     }
 }
collapseAll
void QTreeView::collapseAll () slot
Collapses all expanded items.
Since
4.2
See also
expandAll() expand() collapse() setExpanded()
Definition at line 2715 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->expandedIndexes.clear();
     doItemsLayout();
 }
collapsed
void QTreeView::collapsed (const QModelIndex & index) signal
This signal is emitted when the item specified by index is collapsed.
Referenced by collapse(), and QTreeWidget::QTreeWidget().
columnAt()
int QTreeView::columnAt (int x) const
Returns the column in the tree view whose header covers the x coordinate given.
Definition at line 548 of file qtreeview.cpp.
 {
     Q_D(const QTreeView);
     return d->header->logicalIndexAt(x);
 }
columnCountChanged
void QTreeView::columnCountChanged (int oldCount, int newCount) protected slot
Informs the tree view that the number of columns in the tree view has changed from oldCount to newCount.
Definition at line 2595 of file qtreeview.cpp.
Referenced by setHeader().
 {
     Q_D(QTreeView);
     if (oldCount == 0 && newCount > 0) {
         //if the first column has just been added we need to relayout.
         d->doDelayedItemsLayout();
     }
     if (isVisible())
         updateGeometries();
     viewport()->update();
 }
columnMoved
void QTreeView::columnMoved () protected slot
This slot is called whenever a column has been moved.
Definition at line 2509 of file qtreeview.cpp.
Referenced by setHeader().
 {
     Q_D(QTreeView);
     updateEditorGeometries();
     d->viewport->update();
 }
columnResized
void QTreeView::columnResized (int column, int oldSize, int newSize) protected slot
This function is called whenever {column}'s size is changed in the header.
oldSize and newSize give the previous size and the new size in pixels.
See also
setColumnWidth()
Definition at line 2756 of file qtreeview.cpp.
Referenced by setHeader().
 {
     Q_D(QTreeView);
     d->columnsToUpdate.append(column);
     if (d->columnResizeTimerID == 0)
         d->columnResizeTimerID = startTimer(0);
 }
columnViewportPosition()
int QTreeView::columnViewportPosition (int column) const
Returns the horizontal position of the column in the viewport.
Definition at line 511 of file qtreeview.cpp.
Referenced by drawRow(), scrollTo(), timerEvent(), visualRect(), and visualRegionForSelection().
 {
     Q_D(const QTreeView);
     return d->header->sectionViewportPosition(column);
 }
columnWidth()
int QTreeView::columnWidth (int column) const
Returns the width of the column.
See also
resizeColumnToContents(), setColumnWidth()
Definition at line 522 of file qtreeview.cpp.
Referenced by scrollTo(), timerEvent(), visualRect(), and visualRegionForSelection().
 {
     Q_D(const QTreeView);
     return d->header->sectionSize(column);
 }
currentChanged()
void QTreeView::currentChanged (const QModelIndex & current, const QModelIndex & previous) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 3821 of file qtreeview.cpp.
Referenced by QTreeWidget::QTreeWidget().
 {
     QAbstractItemView::currentChanged(current, previous);
     if (allColumnsShowFocus()) {
         if (previous.isValid()) {
             QRect previousRect = visualRect(previous);
             previousRect.setX(0);
             previousRect.setWidth(viewport()->width());
             viewport()->update(previousRect);
         }
         if (current.isValid()) {
             QRect currentRect = visualRect(current);
             currentRect.setX(0);
             currentRect.setWidth(viewport()->width());
             viewport()->update(currentRect);
         }
     }
 #ifndef QT_NO_ACCESSIBILITY
     if (QAccessible::isActive() && current.isValid()) {
 #ifdef Q_WS_X11
         int entry = (visualIndex(current) + (header()?1:0))*current.model()->columnCount()+current.column() + 1;
         QAccessible::updateAccessibility(this, entry, QAccessible::Focus);
 #else
         int entry = visualIndex(current) + 1;
         if (header())
             ++entry;
         QAccessible::updateAccessibility(viewport(), entry, QAccessible::Focus);
 #endif
     }
 #endif
 }
dataChanged()
void QTreeView::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 706 of file qtreeview.cpp.
Referenced by QTreeWidget::QTreeWidget().
 {
     Q_D(QTreeView);
     // if we are going to do a complete relayout anyway, there is no need to update
     if (d->delayedPendingLayout)
         return;
     // refresh the height cache here; we don't really lose anything by getting the size hint,
     // since QAbstractItemView::dataChanged() will get the visualRect for the items anyway
     bool sizeChanged = false;
     int topViewIndex = d->viewIndex(topLeft);
     if (topViewIndex == 0) {
         int newDefaultItemHeight = indexRowSizeHint(topLeft);
         sizeChanged = d->defaultItemHeight != newDefaultItemHeight;
         d->defaultItemHeight = newDefaultItemHeight;
     }
     if (topViewIndex != -1) {
         if (topLeft.row() == bottomRight.row()) {
             int oldHeight = d->itemHeight(topViewIndex);
             d->invalidateHeightCache(topViewIndex);
             sizeChanged |= (oldHeight != d->itemHeight(topViewIndex));
             if (topLeft.column() == 0)
                 d->viewItems[topViewIndex].hasChildren = d->hasVisibleChildren(topLeft);
         } else {
             int bottomViewIndex = d->viewIndex(bottomRight);
             for (int i = topViewIndex; i <= bottomViewIndex; ++i) {
                 int oldHeight = d->itemHeight(i);
                 d->invalidateHeightCache(i);
                 sizeChanged |= (oldHeight != d->itemHeight(i));
                 if (topLeft.column() == 0)
                     d->viewItems[i].hasChildren = d->hasVisibleChildren(d->viewItems.at(i).index);
             }
         }
     }
     if (sizeChanged) {
         d->updateScrollBars();
         d->viewport->update();
     }
     QAbstractItemView::dataChanged(topLeft, bottomRight);
 }
doItemsLayout()
void QTreeView::doItemsLayout () virtual
Lays out the items in the tree view.
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 2080 of file qtreeview.cpp.
Referenced by collapseAll().
 {
     Q_D(QTreeView);
     if (d->hasRemovedItems) {
         //clean the QSet that may contains old (and this invalid) indexes
         d->hasRemovedItems = false;
         QSet<QPersistentModelIndex>::iterator it = d->expandedIndexes.begin();
         while (it != d->expandedIndexes.constEnd()) {
             if (!it->isValid())
                 it = d->expandedIndexes.erase(it);
             else
                 ++it;
         }
         it = d->hiddenIndexes.begin();
         while (it != d->hiddenIndexes.constEnd()) {
             if (!it->isValid())
                 it = d->hiddenIndexes.erase(it);
             else
                 ++it;
         }
     }
     d->viewItems.clear(); // prepare for new layout
     QModelIndex parent = d->root;
     if (d->model->hasChildren(parent)) {
         d->layout(-1);
     }
     QAbstractItemView::doItemsLayout();
     d->header->doItemsLayout();
 }
dragMoveEvent()
void QTreeView::dragMoveEvent (QDragMoveEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1277 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (d->autoExpandDelay >= 0)
         d->openTimer.start(d->autoExpandDelay, this);
     QAbstractItemView::dragMoveEvent(event);
 }
drawBranches()
void QTreeView::drawBranches (QPainter * painter, const QRect & rect, const QModelIndex & index) const protected virtual
Draws the branches in the tree view on the same row as the model item index, using the painter given.
The branches are drawn in the rectangle specified by rect.
Definition at line 1788 of file qtreeview.cpp.
Referenced by drawRow().
 {
     Q_D(const QTreeView);
     const bool reverse = isRightToLeft();
     const int indent = d->indent;
     const int outer = d->rootDecoration ? 0 : 1;
     const int item = d->current;
     const QTreeViewItem &viewItem = d->viewItems.at(item);
     int level = viewItem.level;
     QRect primitive(reverse ? rect.left() : rect.right() + 1, rect.top(), indent, rect.height());
     QModelIndex parent = index.parent();
     QModelIndex current = parent;
     QModelIndex ancestor = current.parent();
     QStyleOptionViewItemV2 opt = viewOptions();
     QStyle::State extraFlags = QStyle::State_None;
     if (isEnabled())
         extraFlags |= QStyle::State_Enabled;
     if (window()->isActiveWindow())
         extraFlags |= QStyle::State_Active;
     QPoint oldBO = painter->brushOrigin();
     if (verticalScrollMode() == QAbstractItemView::ScrollPerPixel)
         painter->setBrushOrigin(QPoint(0, verticalOffset()));
     if (d->alternatingColors) {
         if (d->current & 1) {
             opt.features |= QStyleOptionViewItemV2::Alternate;
         } else {
             opt.features &= ~QStyleOptionViewItemV2::Alternate;
         }
     }
     // When hovering over a row, pass State_Hover for painting the branch
     // indicators if it has the decoration (aka branch) selected.
     bool hoverRow = selectionBehavior() == QAbstractItemView::SelectRows
                     && opt.showDecorationSelected
                     && index.parent() == d->hover.parent()
                     && index.row() == d->hover.row();
     if (d->selectionModel->isSelected(index))
         extraFlags |= QStyle::State_Selected;
     if (level >= outer) {
         // start with the innermost branch
         primitive.moveLeft(reverse ? primitive.left() : primitive.left() - indent);
         opt.rect = primitive;
         const bool expanded = viewItem.expanded;
         const bool children = viewItem.hasChildren;
         bool moreSiblings = viewItem.hasMoreSiblings;
         opt.state = QStyle::State_Item | extraFlags
                     | (moreSiblings ? QStyle::State_Sibling : QStyle::State_None)
                     | (children ? QStyle::State_Children : QStyle::State_None)
                     | (expanded ? QStyle::State_Open : QStyle::State_None);
         if (hoverRow || item == d->hoverBranch)
             opt.state |= QStyle::State_MouseOver;
         else
             opt.state &= ~QStyle::State_MouseOver;
         style()->drawPrimitive(QStyle::PE_IndicatorBranch, &opt, painter, this);
     }
     // then go out level by level
     for (--level; level >= outer; --level) { // we have already drawn the innermost branch
         primitive.moveLeft(reverse ? primitive.left() + indent : primitive.left() - indent);
         opt.rect = primitive;
         opt.state = extraFlags;
         bool moreSiblings = false;
         if (d->hiddenIndexes.isEmpty()) {
             moreSiblings = (d->model->rowCount(ancestor) - 1 > current.row());
         } else {
             int successor = item + viewItem.total + 1;
             while (successor < d->viewItems.size()
                    && d->viewItems.at(successor).level >= uint(level)) {
                 const QTreeViewItem &successorItem = d->viewItems.at(successor);
                 if (successorItem.level == uint(level)) {
                     moreSiblings = true;
                     break;
                 }
                 successor += successorItem.total + 1;
             }
         }
         if (moreSiblings)
             opt.state |= QStyle::State_Sibling;
         if (hoverRow || item == d->hoverBranch)
             opt.state |= QStyle::State_MouseOver;
         else
             opt.state &= ~QStyle::State_MouseOver;
         style()->drawPrimitive(QStyle::PE_IndicatorBranch, &opt, painter, this);
         current = ancestor;
         ancestor = current.parent();
     }
     painter->setBrushOrigin(oldBO);
 }
drawRow()
void QTreeView::drawRow (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected virtual
Draws the row in the tree view that contains the model item index, using the painter given.
The option control how the item is displayed.
See also
setAlternatingRowColors()
Definition at line 1590 of file qtreeview.cpp.
Referenced by drawTree().
 {
     Q_D(const QTreeView);
     QStyleOptionViewItemV4 opt = option;
     const QPoint offset = d->scrollDelayOffset;
     const int y = option.rect.y() + offset.y();
     const QModelIndex parent = index.parent();
     const QHeaderView *header = d->header;
     const QModelIndex current = currentIndex();
     const QModelIndex hover = d->hover;
     const bool reverse = isRightToLeft();
     const QStyle::State state = opt.state;
     const bool spanning = d->spanning;
     const int left = (spanning ? header->visualIndex(0) : d->leftAndRight.first);
     const int right = (spanning ? header->visualIndex(0) : d->leftAndRight.second);
     const bool alternate = d->alternatingColors;
     const bool enabled = (state & QStyle::State_Enabled) != 0;
     const bool allColumnsShowFocus = d->allColumnsShowFocus;
     // when the row contains an index widget which has focus,
     // we want to paint the entire row as active
     bool indexWidgetHasFocus = false;
     if ((current.row() == index.row()) && !d->editorIndexHash.isEmpty()) {
         const int r = index.row();
         QWidget *fw = QApplication::focusWidget();
         for (int c = 0; c < header->count(); ++c) {
             QModelIndex idx = d->model->index(r, c, parent);
             if (QWidget *editor = indexWidget(idx)) {
                 if (ancestorOf(editor, fw)) {
                     indexWidgetHasFocus = true;
                     break;
                 }
             }
         }
     }
     const bool widgetHasFocus = hasFocus();
     bool currentRowHasFocus = false;
     if (allColumnsShowFocus && widgetHasFocus && current.isValid()) {
         // check if the focus index is before or after the visible columns
         const int r = index.row();
         for (int c = 0; c < left && !currentRowHasFocus; ++c) {
             QModelIndex idx = d->model->index(r, c, parent);
             currentRowHasFocus = (idx == current);
         }
         QModelIndex parent = d->model->parent(index);
         for (int c = right; c < header->count() && !currentRowHasFocus; ++c) {
             currentRowHasFocus = (d->model->index(r, c, parent) == current);
         }
     }
     // ### special case: treeviews with multiple columns draw
     // the selections differently than with only one column
     opt.showDecorationSelected = (d->selectionBehavior & SelectRows)
                                  || option.showDecorationSelected;
     int width, height = option.rect.height();
     int position;
     QModelIndex modelIndex;
     const bool hoverRow = selectionBehavior() == QAbstractItemView::SelectRows
                   && index.parent() == hover.parent()
                   && index.row() == hover.row();
     QVector<int> logicalIndices;
     QVector<QStyleOptionViewItemV4::ViewItemPosition> viewItemPosList; // vector of left/middle/end for each logicalIndex
     d->calcLogicalIndices(&logicalIndices, &viewItemPosList, left, right);
     for (int currentLogicalSection = 0; currentLogicalSection < logicalIndices.count(); ++currentLogicalSection) {
         int headerSection = logicalIndices.at(currentLogicalSection);
         position = columnViewportPosition(headerSection) + offset.x();
         width = header->sectionSize(headerSection);
         if (spanning) {
             int lastSection = header->logicalIndex(header->count() - 1);
             if (!reverse) {
                 width = columnViewportPosition(lastSection) + header->sectionSize(lastSection) - position;
             } else {
                 width += position - columnViewportPosition(lastSection);
                 position = columnViewportPosition(lastSection);
             }
         }
         modelIndex = d->model->index(index.row(), headerSection, parent);
         if (!modelIndex.isValid())
             continue;
         opt.state = state;
         opt.viewItemPosition = viewItemPosList.at(currentLogicalSection);
         // fake activeness when row editor has focus
         if (indexWidgetHasFocus)
             opt.state |= QStyle::State_Active;
         if (d->selectionModel->isSelected(modelIndex))
             opt.state |= QStyle::State_Selected;
         if (widgetHasFocus && (current == modelIndex)) {
             if (allColumnsShowFocus)
                 currentRowHasFocus = true;
             else
                 opt.state |= QStyle::State_HasFocus;
         }
         if ((hoverRow || modelIndex == hover)
             && (option.showDecorationSelected || (d->hoverBranch == -1)))
             opt.state |= QStyle::State_MouseOver;
         else
             opt.state &= ~QStyle::State_MouseOver;
         if (enabled) {
             QPalette::ColorGroup cg;
             if ((d->model->flags(modelIndex) & Qt::ItemIsEnabled) == 0) {
                 opt.state &= ~QStyle::State_Enabled;
                 cg = QPalette::Disabled;
             } else if (opt.state & QStyle::State_Active) {
                 cg = QPalette::Active;
             } else {
                 cg = QPalette::Inactive;
             }
             opt.palette.setCurrentColorGroup(cg);
         }
         if (alternate) {
             if (d->current & 1) {
                 opt.features |= QStyleOptionViewItemV2::Alternate;
             } else {
                 opt.features &= ~QStyleOptionViewItemV2::Alternate;
             }
         }
         /* Prior to Qt 4.3, the background of the branch (in selected state and
            alternate row color was provided by the view. For backward compatibility,
            this is now delegated to the style using PE_PanelViewItemRow which
            does the appropriate fill */
         if (headerSection == 0) {
             const int i = d->indentationForItem(d->current);
             QRect branches(reverse ? position + width - i : position, y, i, height);
             const bool setClipRect = branches.width() > width;
             if (setClipRect) {
                 painter->save();
                 painter->setClipRect(QRect(position, y, width, height));
             }
             // draw background for the branch (selection + alternate row)
             opt.rect = branches;
             style()->drawPrimitive(QStyle::PE_PanelItemViewRow, &opt, painter, this);
             // draw background of the item (only alternate row). rest of the background
             // is provided by the delegate
             QStyle::State oldState = opt.state;
             opt.state &= ~QStyle::State_Selected;
             opt.rect.setRect(reverse ? position : i + position, y, width - i, height);
             style()->drawPrimitive(QStyle::PE_PanelItemViewRow, &opt, painter, this);
             opt.state = oldState;
             drawBranches(painter, branches, index);
             if (setClipRect)
                 painter->restore();
         } else {
             QStyle::State oldState = opt.state;
             opt.state &= ~QStyle::State_Selected;
             opt.rect.setRect(position, y, width, height);
             style()->drawPrimitive(QStyle::PE_PanelItemViewRow, &opt, painter, this);
             opt.state = oldState;
         }
         d->delegateForIndex(modelIndex)->paint(painter, opt, modelIndex);
     }
     if (currentRowHasFocus) {
         QStyleOptionFocusRect o;
         o.QStyleOption::operator=(option);
         o.state |= QStyle::State_KeyboardFocusChange;
         QPalette::ColorGroup cg = (option.state & QStyle::State_Enabled)
                                   ? QPalette::Normal : QPalette::Disabled;
         o.backgroundColor = option.palette.color(cg, d->selectionModel->isSelected(index)
                                                  ? QPalette::Highlight : QPalette::Background);
         int x = 0;
         if (!option.showDecorationSelected)
             x = header->sectionPosition(0) + d->indentationForItem(d->current);
     QRect focusRect(x - header->offset(), y, header->length() - x, height);
         o.rect = style()->visualRect(layoutDirection(), d->viewport->rect(), focusRect);
         style()->drawPrimitive(QStyle::PE_FrameFocusRect, &o, painter);
         // if we show focus on all columns and the first section is moved,
         // we have to split the focus rect into two rects
         if (allColumnsShowFocus && !option.showDecorationSelected
             && header->sectionsMoved() && (header->visualIndex(0) != 0)) {
         QRect sectionRect(0, y, header->sectionPosition(0), height);
             o.rect = style()->visualRect(layoutDirection(), d->viewport->rect(), sectionRect);
             style()->drawPrimitive(QStyle::PE_FrameFocusRect, &o, painter);
         }
     }
 }
drawTree()
void QTreeView::drawTree (QPainter * painter, const QRegion & region) const protected
Draws the part of the tree intersecting the given region using the specified painter.
Since
4.2
See also
paintEvent()
Definition at line 1452 of file qtreeview.cpp.
Referenced by paintEvent().
 {
     Q_D(const QTreeView);
     const QVector<QTreeViewItem> viewItems = d->viewItems;
     QStyleOptionViewItemV4 option = d->viewOptionsV4();
     const QStyle::State state = option.state;
     d->current = 0;
     if (viewItems.count() == 0 || d->header->count() == 0 || !d->itemDelegate) {
         d->paintAlternatingRowColors(painter, &option, 0, region.boundingRect().bottom()+1);
         return;
     }
     int firstVisibleItemOffset = 0;
     const int firstVisibleItem = d->firstVisibleItem(&firstVisibleItemOffset);
     if (firstVisibleItem < 0) {
         d->paintAlternatingRowColors(painter, &option, 0, region.boundingRect().bottom()+1);
         return;
     }
     const int viewportWidth = d->viewport->width();
     QPoint hoverPos = d->viewport->mapFromGlobal(QCursor::pos());
     d->hoverBranch = d->itemDecorationAt(hoverPos);
     QVector<QRect> rects = region.rects();
     QVector<int> drawn;
     bool multipleRects = (rects.size() > 1);
     for (int a = 0; a < rects.size(); ++a) {
         const QRect area = (multipleRects
                             ? QRect(0, rects.at(a).y(), viewportWidth, rects.at(a).height())
                             : rects.at(a));
         d->leftAndRight = d->startAndEndColumns(area);
         int i = firstVisibleItem; // the first item at the top of the viewport
         int y = firstVisibleItemOffset; // we may only see part of the first item
         // start at the top of the viewport  and iterate down to the update area
         for (; i < viewItems.count(); ++i) {
             const int itemHeight = d->itemHeight(i);
             if (y + itemHeight > area.top())
                 break;
             y += itemHeight;
         }
         // paint the visible rows
         for (; i < viewItems.count() && y <= area.bottom(); ++i) {
             const int itemHeight = d->itemHeight(i);
             option.rect.setRect(0, y, viewportWidth, itemHeight);
             option.state = state | (viewItems.at(i).expanded ? QStyle::State_Open : QStyle::State_None)
                                  | (viewItems.at(i).hasChildren ? QStyle::State_Children : QStyle::State_None)
                                  | (viewItems.at(i).hasMoreSiblings ? QStyle::State_Sibling : QStyle::State_None);
             d->current = i;
             d->spanning = viewItems.at(i).spanning;
             if (!multipleRects || !drawn.contains(i)) {
                 drawRow(painter, option, viewItems.at(i).index);
                 if (multipleRects)   // even if the rect only intersects the item,
                     drawn.append(i); // the entire item will be painted
             }
             y += itemHeight;
         }
         if (y <= area.bottom()) {
             d->current = i;
             d->paintAlternatingRowColors(painter, &option, y, area.bottom());
         }
     }
 }
expand
void QTreeView::expand (const QModelIndex & index) slot
Expands the model item specified by the index.
See also
expanded()
Definition at line 787 of file qtreeview.cpp.
Referenced by QTreeWidget::expandItem(), QTreeViewPrivate::expandOrCollapseItemAtPos(), keyPressEvent(), scrollTo(), setExpanded(), and QTreeWidget::setItemExpanded().
 {
     Q_D(QTreeView);
     if (!d->isIndexValid(index))
         return;
     if (d->delayedPendingLayout) {
         //A complete relayout is going to be performed, just store the expanded index, no need to layout.
         if (d->storeExpanded(index))
             emit expanded(index);
         return;
     }
     int i = d->viewIndex(index);
     if (i != -1) { // is visible
         d->expand(i, true);
         if (!d->isAnimating()) {
             updateGeometries();
             d->viewport->update();
         }
     } else if (d->storeExpanded(index)) {
         emit expanded(index);
     }
 }
expandAll
void QTreeView::expandAll () slot
Expands all expandable items.
Since
4.2
Warning: if the model contains a large number of items, this function will take some time to execute.
See also
collapseAll() expand() collapse() setExpanded()
Definition at line 2695 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->viewItems.clear();
     d->interruptDelayedItemsLayout();
     d->layout(-1, true);
     updateGeometries();
     d->viewport->update();
 }
expanded
void QTreeView::expanded (const QModelIndex & index) signal
This signal is emitted when the item specified by index is expanded.
Referenced by drawBranches(), expand(), QTreeWidget::QTreeWidget(), and QFSCompleter::splitPath().
expandsOnDoubleClick()
bool QTreeView::expandsOnDoubleClick () const
Referenced by setItemsExpandable().
expandToDepth
void QTreeView::expandToDepth (int depth) slot
Expands all expandable items to the given depth.
Since
4.3
See also
expandAll() collapseAll() expand() collapse() setExpanded()
Definition at line 2731 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->viewItems.clear();
     d->expandedIndexes.clear();
     d->interruptDelayedItemsLayout();
     d->layout(-1);
     for (int i = 0; i < d->viewItems.count(); ++i) {
         if (d->viewItems.at(i).level <= (uint)depth) {
             d->viewItems[i].expanded = true;
             d->layout(i);
             d->storeExpanded(d->viewItems.at(i).index);
         }
     }
     updateGeometries();
     d->viewport->update();
 }
header()
QHeaderView * QTreeView::header () const
Returns the header for the tree view.
See also
QAbstractItemModel::headerData()
Definition at line 302 of file qtreeview.cpp.
Referenced by QTreeViewPrivate::adjustViewOptionsForIndex(), QTreeViewPrivate::calcLogicalIndices(), QTreeViewPrivate::columnAt(), QTreeViewPrivate::columnRanges(), currentChanged(), drawRow(), QTreeModel::executePendingSort(), QFileDialogTreeView::init(), QTreeViewPrivate::initialize(), QTreeWidget::isItemHidden(), QTreeViewPrivate::itemDecorationAt(), QTreeViewPrivate::itemDecorationRect(), moveCursor(), QTreeWidget::QTreeWidget(), resizeColumnToContents(), selectionChanged(), QTreeWidget::setItemHidden(), setModel(), setSortingEnabled(), QComboBox::showPopup(), QFileDialogTreeView::sizeHint(), QTreeWidget::sortColumn(), QTreeWidget::sortItems(), QTreeViewPrivate::startAndEndColumns(), QTreeViewPrivate::updateScrollBars(), and QTreeWidget::visualItemRect().
 {
     Q_D(const QTreeView);
     return d->header;
 }
hideColumn
void QTreeView::hideColumn (int column) slot
Hides the column given.
Note
This function should only be called after the model has been initialized, as the view needs to know the number of columns in order to hide column.
See also
showColumn(), setColumnHidden()
Definition at line 760 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->header->hideSection(column);
 }
horizontalOffset()
int QTreeView::horizontalOffset () const protected virtual
Returns the horizontal offset of the items in the treeview.
Note that the tree view uses the horizontal header section positions to determine the positions of columns in the view.
See also
verticalOffset()
Implements QAbstractItemView.
Definition at line 2131 of file qtreeview.cpp.
Referenced by scrollTo().
 {
     Q_D(const QTreeView);
     return d->header->offset();
 }
horizontalScrollbarAction()
void QTreeView::horizontalScrollbarAction (int action) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 2926 of file qtreeview.cpp.
 {
     QAbstractItemView::horizontalScrollbarAction(action);
 }
indentation()
int QTreeView::indentation () const
Referenced by setAutoExpandDelay().
indexAbove()
QModelIndex QTreeView::indexAbove (const QModelIndex & index) const
Returns the model index of the item above index.
Definition at line 2045 of file qtreeview.cpp.
Referenced by QTreeWidget::itemAbove().
 {
     Q_D(const QTreeView);
     if (!d->isIndexValid(index))
         return QModelIndex();
     d->executePostedLayout();
     int i = d->viewIndex(index);
     if (--i < 0)
         return QModelIndex();
     return d->viewItems.at(i).index;
 }
indexAt()
QModelIndex QTreeView::indexAt (const QPoint & p) const virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 2021 of file qtreeview.cpp.
Referenced by QTreeWidget::itemAt(), mouseDoubleClickEvent(), setSelection(), timerEvent(), and viewportEvent().
 {
     Q_D(const QTreeView);
     d->executePostedLayout();
     int visualIndex = d->itemAtCoordinate(point.y());
     QModelIndex idx = d->modelIndex(visualIndex);
     if (!idx.isValid())
         return QModelIndex();
     if (d->viewItems.at(visualIndex).spanning)
         return idx;
     int column = d->columnAt(point.x());
     if (column == idx.column())
         return idx;
     if (column < 0)
         return QModelIndex();
     return idx.sibling(idx.row(), column);
 }
indexBelow()
QModelIndex QTreeView::indexBelow (const QModelIndex & index) const
Returns the model index of the item below index.
Definition at line 2060 of file qtreeview.cpp.
Referenced by QTreeWidget::itemBelow(), and keyboardSearch().
 {
     Q_D(const QTreeView);
     if (!d->isIndexValid(index))
         return QModelIndex();
     d->executePostedLayout();
     int i = d->viewIndex(index);
     if (++i >= d->viewItems.count())
         return QModelIndex();
     return d->viewItems.at(i).index;
 }
indexRowSizeHint()
int QTreeView::indexRowSizeHint (const QModelIndex & index) const protected
Returns the size hint for the row indicated by index.
See also
sizeHintForColumn(), uniformRowHeights()
Definition at line 2843 of file qtreeview.cpp.
Referenced by dataChanged().
 {
     Q_D(const QTreeView);
     if (!d->isIndexValid(index) || !d->itemDelegate)
         return 0;
     int start = -1;
     int end = -1;
     int indexRow = index.row();
     int count = d->header->count();
     bool emptyHeader = (count == 0);
     QModelIndex parent = index.parent();
     if (count && isVisible()) {
         // If the sections have moved, we end up checking too many or too few
         start = d->header->visualIndexAt(0);
     } else {
         // If the header has not been laid out yet, we use the model directly
         count = d->model->columnCount(parent);
     }
     if (isRightToLeft()) {
         start = (start == -1 ? count - 1 : start);
         end = 0;
     } else {
         start = (start == -1 ? 0 : start);
         end = count - 1;
     }
     if (end < start)
         qSwap(end, start);
     int height = -1;
     QStyleOptionViewItemV4 option = d->viewOptionsV4();
     // ### If we want word wrapping in the items,
     // ### we need to go through all the columns
     // ### and set the width of the column
     // Hack to speed up the function
     option.rect.setWidth(-1);
     for (int column = start; column <= end; ++column) {
         int logicalColumn = emptyHeader ? column : d->header->logicalIndex(column);
         if (d->header->isSectionHidden(logicalColumn))
             continue;
         QModelIndex idx = d->model->index(indexRow, logicalColumn, parent);
         if (idx.isValid()) {
             QWidget *editor = d->editorForIndex(idx).widget.data();
             if (editor && d->persistent.contains(editor)) {
                 height = qMax(height, editor->sizeHint().height());
                 int min = editor->minimumSize().height();
                 int max = editor->maximumSize().height();
                 height = qBound(min, height, max);
             }
             int hint = d->delegateForIndex(idx)->sizeHint(option, idx).height();
             height = qMax(height, hint);
         }
     }
     return height;
 }
isAnimated()
bool QTreeView::isAnimated () const
Definition at line 944 of file qtreeview.cpp.
 {
     Q_D(const QTreeView);
     return d->animationsEnabled;
 }
isColumnHidden()
bool QTreeView::isColumnHidden (int column) const
Returns true if the column is hidden; otherwise returns false.
See also
hideColumn(), isRowHidden()
Definition at line 559 of file qtreeview.cpp.
Referenced by isIndexHidden(), and moveCursor().
 {
     Q_D(const QTreeView);
     return d->header->isSectionHidden(column);
 }
isExpanded()
bool QTreeView::isExpanded (const QModelIndex & index) const
Returns true if the model item index is expanded; otherwise returns false.
See also
expand(), expanded(), setExpanded()
Definition at line 859 of file qtreeview.cpp.
Referenced by QTreeWidget::isItemExpanded(), QScriptDebuggerLocalsItemDelegate::paint(), scrollTo(), QComboBox::showPopup(), QAccessibleTable2Cell::state(), and timerEvent().
 {
     Q_D(const QTreeView);
     return d->isIndexExpanded(index);
 }
isFirstColumnSpanned()
bool QTreeView::isFirstColumnSpanned (int row, const QModelIndex & parent) const
Returns true if the item in first column in the given row of the parent is spanning all the columns; otherwise returns false.
Since
4.3
See also
setFirstColumnSpanned()
Definition at line 651 of file qtreeview.cpp.
Referenced by QTreeWidget::isFirstItemColumnSpanned().
 {
     Q_D(const QTreeView);
     if (d->spanningIndexes.isEmpty() || !d->model)
         return false;
     QModelIndex index = d->model->index(row, 0, parent);
     for (int i = 0; i < d->spanningIndexes.count(); ++i)
         if (d->spanningIndexes.at(i) == index)
             return true;
     return false;
 }
isHeaderHidden()
bool QTreeView::isHeaderHidden () const
Definition at line 591 of file qtreeview.cpp.
 {
     Q_D(const QTreeView);
     return d->header->isHidden();
 }
isIndexHidden()
bool QTreeView::isIndexHidden (const QModelIndex & index) const protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 2934 of file qtreeview.cpp.
Referenced by selectedIndexes(), visualRect(), and visualRegionForSelection().
 {
     return (isColumnHidden(index.column()) || isRowHidden(index.row(), index.parent()));
 }
isRowHidden()
bool QTreeView::isRowHidden (int row, const QModelIndex & parent) const
Returns true if the item in the given row of the parent is hidden; otherwise returns false.
See also
setRowHidden(), isColumnHidden()
Definition at line 609 of file qtreeview.cpp.
Referenced by isIndexHidden(), and QTreeViewPrivate::layout().
 {
     Q_D(const QTreeView);
     if (!d->model)
         return false;
     return d->isRowHidden(d->model->index(row, 0, parent));
 }
isSortingEnabled()
bool QTreeView::isSortingEnabled () const
Definition at line 916 of file qtreeview.cpp.
Referenced by QTreeWidget::isSortingEnabled().
 {
     Q_D(const QTreeView);
     return d->sortingEnabled;
 }
itemsExpandable()
bool QTreeView::itemsExpandable () const
Referenced by QTreeViewPrivate::expandOrCollapseItemAtPos(), and setUniformRowHeights().
keyboardSearch()
void QTreeView::keyboardSearch (const QString & search) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1014 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (!d->model->rowCount(d->root) || !d->model->columnCount(d->root))
         return;
     QModelIndex start;
     if (currentIndex().isValid())
         start = currentIndex();
     else
         start = d->model->index(0, 0, d->root);
     bool skipRow = false;
     bool keyboardTimeWasValid = d->keyboardInputTime.isValid();
     qint64 keyboardInputTimeElapsed = d->keyboardInputTime.restart();
     if (search.isEmpty() || !keyboardTimeWasValid
         || keyboardInputTimeElapsed > QApplication::keyboardInputInterval()) {
         d->keyboardInput = search;
         skipRow = currentIndex().isValid(); //if it is not valid we should really start at QModelIndex(0,0)
     } else {
         d->keyboardInput += search;
     }
     // special case for searches with same key like 'aaaaa'
     bool sameKey = false;
     if (d->keyboardInput.length() > 1) {
         int c = d->keyboardInput.count(d->keyboardInput.at(d->keyboardInput.length() - 1));
         sameKey = (c == d->keyboardInput.length());
         if (sameKey)
             skipRow = true;
     }
     // skip if we are searching for the same key or a new search started
     if (skipRow) {
         if (indexBelow(start).isValid())
             start = indexBelow(start);
         else
             start = d->model->index(0, start.column(), d->root);
     }
     d->executePostedLayout();
     int startIndex = d->viewIndex(start);
     if (startIndex <= -1)
         return;
     int previousLevel = -1;
     int bestAbove = -1;
     int bestBelow = -1;
     QString searchString = sameKey ? QString(d->keyboardInput.at(0)) : d->keyboardInput;
     for (int i = 0; i < d->viewItems.count(); ++i) {
         if ((int)d->viewItems.at(i).level > previousLevel) {
             QModelIndex searchFrom = d->viewItems.at(i).index;
             if (searchFrom.parent() == start.parent())
                 searchFrom = start;
             QModelIndexList match = d->model->match(searchFrom, Qt::DisplayRole, searchString);
             if (match.count()) {
                 int hitIndex = d->viewIndex(match.at(0));
                 if (hitIndex >= 0 && hitIndex < startIndex)
                     bestAbove = bestAbove == -1 ? hitIndex : qMin(hitIndex, bestAbove);
                 else if (hitIndex >= startIndex)
                     bestBelow = bestBelow == -1 ? hitIndex : qMin(hitIndex, bestBelow);
             }
         }
         previousLevel = d->viewItems.at(i).level;
     }
     QModelIndex index;
     if (bestBelow > -1)
         index = d->viewItems.at(bestBelow).index;
     else if (bestAbove > -1)
         index = d->viewItems.at(bestAbove).index;
     if (index.isValid()) {
         QItemSelectionModel::SelectionFlags flags = (d->selectionMode == SingleSelection
                                                      ? QItemSelectionModel::SelectionFlags(
                                                          QItemSelectionModel::ClearAndSelect
                                                          |d->selectionBehaviorFlags())
                                                      : QItemSelectionModel::SelectionFlags(
                                                          QItemSelectionModel::NoUpdate));
         selectionModel()->setCurrentIndex(index, flags);
     }
 }
keyPressEvent()
void QTreeView::keyPressEvent (QKeyEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1984 of file qtreeview.cpp.
Referenced by QFileDialogTreeView::keyPressEvent().
 {
     Q_D(QTreeView);
     QModelIndex current = currentIndex();
     //this is the management of the expansion
     if (d->isIndexValid(current) && d->model && d->itemsExpandable) {
         switch (event->key()) {
         case Qt::Key_Asterisk: {
             QStack<QModelIndex> parents;
             parents.push(current);
                 while (!parents.isEmpty()) {
                     QModelIndex parent = parents.pop();
                     for (int row = 0; row < d->model->rowCount(parent); ++row) {
                         QModelIndex child = d->model->index(row, 0, parent);
                         if (!d->isIndexValid(child))
                             break;
                         parents.push(child);
                         expand(child);
                     }
                 }
                 expand(current);
             break; }
         case Qt::Key_Plus:
             expand(current);
             break;
         case Qt::Key_Minus:
             collapse(current);
             break;
         }
     }
     QAbstractItemView::keyPressEvent(event);
 }
mouseDoubleClickEvent()
void QTreeView::mouseDoubleClickEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1916 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (state() != NoState || !d->viewport->rect().contains(event->pos()))
         return;
     int i = d->itemDecorationAt(event->pos());
     if (i == -1) {
         i = d->itemAtCoordinate(event->y());
         if (i == -1)
             return; // user clicked outside the items
         const QPersistentModelIndex firstColumnIndex = d->viewItems.at(i).index;
         const QPersistentModelIndex persistent = indexAt(event->pos());
         if (d->pressedIndex != persistent) {
             mousePressEvent(event);
             return;
         }
         // signal handlers may change the model
         emit doubleClicked(persistent);
         if (!persistent.isValid())
             return;
         if (edit(persistent, DoubleClicked, event) || state() != NoState)
             return; // the double click triggered editing
         if (!style()->styleHint(QStyle::SH_ItemView_ActivateItemOnSingleClick, 0, this))
             emit activated(persistent);
         d->executePostedLayout(); // we need to make sure viewItems is updated
         if (d->itemsExpandable
             && d->expandsOnDoubleClick
             && d->hasVisibleChildren(persistent)) {
             if (!((i < d->viewItems.count()) && (d->viewItems.at(i).index == firstColumnIndex))) {
                 // find the new index of the item
                 for (i = 0; i < d->viewItems.count(); ++i) {
                     if (d->viewItems.at(i).index == firstColumnIndex)
                         break;
                 }
                 if (i == d->viewItems.count())
                     return;
             }
             if (d->viewItems.at(i).expanded)
                 d->collapse(i, true);
             else
                 d->expand(i, true);
             updateGeometries();
             viewport()->update();
         }
     }
 }
mouseMoveEvent()
void QTreeView::mouseMoveEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1974 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (d->itemDecorationAt(event->pos()) == -1) // ### what about expanding/collapsing state ?
         QAbstractItemView::mouseMoveEvent(event);
 }
mousePressEvent()
void QTreeView::mousePressEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1887 of file qtreeview.cpp.
Referenced by mouseDoubleClickEvent().
 {
     Q_D(QTreeView);
     bool handled = false;
     if (style()->styleHint(QStyle::SH_Q3ListViewExpand_SelectMouseType, 0, this) == QEvent::MouseButtonPress)
         handled = d->expandOrCollapseItemAtPos(event->pos());
     if (!handled && d->itemDecorationAt(event->pos()) == -1)
         QAbstractItemView::mousePressEvent(event);
 }
mouseReleaseEvent()
void QTreeView::mouseReleaseEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1900 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (d->itemDecorationAt(event->pos()) == -1) {
         QAbstractItemView::mouseReleaseEvent(event);
     } else {
         if (state() == QAbstractItemView::DragSelectingState)
             setState(QAbstractItemView::NoState);
         if (style()->styleHint(QStyle::SH_Q3ListViewExpand_SelectMouseType, 0, this) == QEvent::MouseButtonRelease)
             d->expandOrCollapseItemAtPos(event->pos());
     }
 }
moveCursor()
QModelIndex QTreeView::moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers) protected virtual
Move the cursor in the way described by cursorAction, using the information provided by the button modifiers.
Implements QAbstractItemView.
Definition at line 2168 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     Q_UNUSED(modifiers);
     d->executePostedLayout();
     QModelIndex current = currentIndex();
     if (!current.isValid()) {
         int i = d->below(-1);
         int c = 0;
         while (c < d->header->count() && d->header->isSectionHidden(c))
             ++c;
         if (i < d->viewItems.count() && c < d->header->count()) {
             return d->modelIndex(i, c);
         }
         return QModelIndex();
     }
     int vi = -1;
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
     // Selection behavior is slightly different on the Mac.
     if (d->selectionMode == QAbstractItemView::ExtendedSelection
         && d->selectionModel
         && d->selectionModel->hasSelection()) {
         const bool moveUpDown = (cursorAction == MoveUp || cursorAction == MoveDown);
         const bool moveNextPrev = (cursorAction == MoveNext || cursorAction == MovePrevious);
         const bool contiguousSelection = moveUpDown && (modifiers & Qt::ShiftModifier);
         // Use the outermost index in the selection as the current index
         if (!contiguousSelection && (moveUpDown || moveNextPrev)) {
             // Find outermost index.
             const bool useTopIndex = (cursorAction == MoveUp || cursorAction == MovePrevious);
             int index = useTopIndex ? INT_MAX : INT_MIN;
             const QItemSelection selection = d->selectionModel->selection();
             for (int i = 0; i < selection.count(); ++i) {
                 const QItemSelectionRange &range = selection.at(i);
                 int candidate = d->viewIndex(useTopIndex ? range.topLeft() : range.bottomRight());
                 if (candidate >= 0)
                     index = useTopIndex ? qMin(index, candidate) : qMax(index, candidate);
             }
             if (index >= 0 && index < INT_MAX)
                 vi = index;
         }
     }
 #endif
     if (vi < 0)
         vi = qMax(0, d->viewIndex(current));
     if (isRightToLeft()) {
         if (cursorAction == MoveRight)
             cursorAction = MoveLeft;
         else if (cursorAction == MoveLeft)
             cursorAction = MoveRight;
     }
     switch (cursorAction) {
     case MoveNext:
     case MoveDown:
 #ifdef QT_KEYPAD_NAVIGATION
         if (vi == d->viewItems.count()-1 && QApplication::keypadNavigationEnabled())
             return d->model->index(0, current.column(), d->root);
 #endif
         return d->modelIndex(d->below(vi), current.column());
     case MovePrevious:
     case MoveUp:
 #ifdef QT_KEYPAD_NAVIGATION
         if (vi == 0 && QApplication::keypadNavigationEnabled())
             return d->modelIndex(d->viewItems.count() - 1, current.column());
 #endif
         return d->modelIndex(d->above(vi), current.column());
     case MoveLeft: {
         QScrollBar *sb = horizontalScrollBar();
         if (vi < d->viewItems.count() && d->viewItems.at(vi).expanded && d->itemsExpandable && sb->value() == sb->minimum()) {
             d->collapse(vi, true);
             d->moveCursorUpdatedView = true;
         } else {
             bool descend = style()->styleHint(QStyle::SH_ItemView_ArrowKeysNavigateIntoChildren, 0, this);
             if (descend) {
                 QModelIndex par = current.parent();
                 if (par.isValid() && par != rootIndex())
                     return par;
                 else
                     descend = false;
             }
             if (!descend) {
                 if (d->selectionBehavior == SelectItems || d->selectionBehavior == SelectColumns) {
                     int visualColumn = d->header->visualIndex(current.column()) - 1;
                     while (visualColumn >= 0 && isColumnHidden(d->header->logicalIndex(visualColumn)))
                         visualColumn--;
                     int newColumn = d->header->logicalIndex(visualColumn);
                     QModelIndex next = current.sibling(current.row(), newColumn);
                     if (next.isValid())
                         return next;
                 }
                 int oldValue = sb->value();
                 sb->setValue(sb->value() - sb->singleStep());
                 if (oldValue != sb->value())
                     d->moveCursorUpdatedView = true;
             }
         }
         updateGeometries();
         viewport()->update();
         break;
     }
     case MoveRight:
         if (vi < d->viewItems.count() && !d->viewItems.at(vi).expanded && d->itemsExpandable
             && d->hasVisibleChildren(d->viewItems.at(vi).index)) {
             d->expand(vi, true);
             d->moveCursorUpdatedView = true;
         } else {
             bool descend = style()->styleHint(QStyle::SH_ItemView_ArrowKeysNavigateIntoChildren, 0, this);
             if (descend) {
                 QModelIndex idx = d->modelIndex(d->below(vi));
                 if (idx.parent() == current)
                     return idx;
                 else
                     descend = false;
             }
             if (!descend) {
                 if (d->selectionBehavior == SelectItems || d->selectionBehavior == SelectColumns) {
                     int visualColumn = d->header->visualIndex(current.column()) + 1;
                     while (visualColumn < d->model->columnCount(current.parent()) && isColumnHidden(d->header->logicalIndex(visualColumn)))
                         visualColumn++;
                     QModelIndex next = current.sibling(current.row(), visualColumn);
                     if (next.isValid())
                         return next;
                 }
                 //last restort: we change the scrollbar value
                 QScrollBar *sb = horizontalScrollBar();
                 int oldValue = sb->value();
                 sb->setValue(sb->value() + sb->singleStep());
                 if (oldValue != sb->value())
                     d->moveCursorUpdatedView = true;
             }
         }
         updateGeometries();
         viewport()->update();
         break;
     case MovePageUp:
         return d->modelIndex(d->pageUp(vi), current.column());
     case MovePageDown:
         return d->modelIndex(d->pageDown(vi), current.column());
     case MoveHome:
         return d->model->index(0, current.column(), d->root);
     case MoveEnd:
         return d->modelIndex(d->viewItems.count() - 1, current.column());
     }
     return current;
 }
paintEvent()
void QTreeView::paintEvent (QPaintEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1318 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->executePostedLayout();
     QPainter painter(viewport());
 #ifndef QT_NO_ANIMATION
     if (d->isAnimating()) {
         drawTree(&painter, event->region() - d->animatedOperation.rect());
         d->drawAnimatedOperation(&painter);
     } else
 #endif //QT_NO_ANIMATION
     {
         drawTree(&painter, event->region());
 #ifndef QT_NO_DRAGANDDROP
         d->paintDropIndicator(&painter);
 #endif
     }
 }
reexpand
void QTreeView::reexpand () protected slot
Warning
This function is not part of the public interface.
Definition at line 2519 of file qtreeview.cpp.
 {
     // do nothing
 }
reset()
void QTreeView::reset () virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2113 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->expandedIndexes.clear();
     d->hiddenIndexes.clear();
     d->spanningIndexes.clear();
     d->viewItems.clear();
     QAbstractItemView::reset();
 }
resizeColumnToContents
void QTreeView::resizeColumnToContents (int column) slot
Resizes the column given to the size of its contents.
See also
columnWidth(), setColumnWidth()
Definition at line 2613 of file qtreeview.cpp.
Referenced by setHeader().
 {
     Q_D(QTreeView);
     d->executePostedLayout();
     if (column < 0 || column >= d->header->count())
         return;
     int contents = sizeHintForColumn(column);
     int header = d->header->isHidden() ? 0 : d->header->sectionSizeHint(column);
     d->header->resizeSection(column, qMax(contents, header));
 }
rootIsDecorated()
bool QTreeView::rootIsDecorated () const
Referenced by setIndentation().
rowHeight()
int QTreeView::rowHeight (const QModelIndex & index) const protected
Returns the height of the row indicated by the given index.
Since
4.3
See also
indexRowSizeHint()
Definition at line 2913 of file qtreeview.cpp.
Referenced by QTreeViewPrivate::paintAlternatingRowColors().
 {
     Q_D(const QTreeView);
     d->executePostedLayout();
     int i = d->viewIndex(index);
     if (i == -1)
         return 0;
     return d->itemHeight(i);
 }
rowsAboutToBeRemoved()
void QTreeView::rowsAboutToBeRemoved (const QModelIndex & parent, int start, int end) protected virtual
Informs the view that the rows from the start row to the end row inclusive are about to removed from the given parent model item.
Reimplemented from QAbstractItemView.
Definition at line 2566 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     QAbstractItemView::rowsAboutToBeRemoved(parent, start, end);
     d->viewItems.clear();
 }
rowsInserted()
void QTreeView::rowsInserted (const QModelIndex & parent, int start, int end) protected virtual
Informs the view that the rows from the start row to the end row inclusive have been inserted into the parent model item.
Reimplemented from QAbstractItemView.
Definition at line 2528 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     // if we are going to do a complete relayout anyway, there is no need to update
     if (d->delayedPendingLayout) {
         QAbstractItemView::rowsInserted(parent, start, end);
         return;
     }
     //don't add a hierarchy on a column != 0
     if (parent.column() != 0 && parent.isValid()) {
         QAbstractItemView::rowsInserted(parent, start, end);
         return;
     }
     const int parentRowCount = d->model->rowCount(parent);
     const int delta = end - start + 1;
     if (parent != d->root && !d->isIndexExpanded(parent) && parentRowCount > delta) {
         QAbstractItemView::rowsInserted(parent, start, end);
         return;
     }
     const int parentItem = d->viewIndex(parent);
     if (((parentItem != -1) && d->viewItems.at(parentItem).expanded)
         || (parent == d->root)) {
         d->doDelayedItemsLayout();
     } else if (parentItem != -1 && (d->model->rowCount(parent) == end - start + 1)) {
         // the parent just went from 0 children to more. update to re-paint the decoration
         d->viewItems[parentItem].hasChildren = true;
         viewport()->update();
     }
     QAbstractItemView::rowsInserted(parent, start, end);
 }
rowsRemoved
void QTreeView::rowsRemoved (const QModelIndex & parent, int start, int end) protected slot
Informs the view that the rows from the start row to the end row inclusive have been removed from the given parent model item.
Since
4.1
Definition at line 2582 of file qtreeview.cpp.
Referenced by setModel().
 {
     Q_D(QTreeView);
     d->viewItems.clear();
     d->doDelayedItemsLayout();
     d->hasRemovedItems = true;
     d->_q_rowsRemoved(parent, start, end);
 }
scrollContentsBy()
void QTreeView::scrollContentsBy (int dx, int dy) protected virtual
Scrolls the contents of the tree view by (dx, dy).
Reimplemented from QAbstractScrollArea.
Definition at line 2448 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->delayedAutoScroll.stop(); // auto scroll was canceled by the user scrolling
     dx = isRightToLeft() ? -dx : dx;
     if (dx) {
         if (horizontalScrollMode() == QAbstractItemView::ScrollPerItem) {
             int oldOffset = d->header->offset();
             if (horizontalScrollBar()->value() == horizontalScrollBar()->maximum())
                 d->header->setOffsetToLastSection();
             else
                 d->header->setOffsetToSectionPosition(horizontalScrollBar()->value());
             int newOffset = d->header->offset();
             dx = isRightToLeft() ? newOffset - oldOffset : oldOffset - newOffset;
         } else {
             d->header->setOffset(horizontalScrollBar()->value());
         }
     }
     const int itemHeight = d->defaultItemHeight <= 0 ? sizeHintForRow(0) : d->defaultItemHeight;
     if (d->viewItems.isEmpty() || itemHeight == 0)
         return;
     // guestimate the number of items in the viewport
     int viewCount = d->viewport->height() / itemHeight;
     int maxDeltaY = qMin(d->viewItems.count(), viewCount);
     // no need to do a lot of work if we are going to redraw the whole thing anyway
     if (qAbs(dy) > qAbs(maxDeltaY) && d->editorIndexHash.isEmpty()) {
         verticalScrollBar()->update();
         d->viewport->update();
         return;
     }
     if (dy && verticalScrollMode() == QAbstractItemView::ScrollPerItem) {
         int currentScrollbarValue = verticalScrollBar()->value();
         int previousScrollbarValue = currentScrollbarValue + dy; // -(-dy)
         int currentViewIndex = currentScrollbarValue; // the first visible item
         int previousViewIndex = previousScrollbarValue;
         const QVector<QTreeViewItem> viewItems = d->viewItems;
         dy = 0;
         if (previousViewIndex < currentViewIndex) { // scrolling down
             for (int i = previousViewIndex; i < currentViewIndex; ++i) {
                 if (i < d->viewItems.count())
                     dy -= d->itemHeight(i);
             }
         } else if (previousViewIndex > currentViewIndex) { // scrolling up
             for (int i = previousViewIndex - 1; i >= currentViewIndex; --i) {
                 if (i < d->viewItems.count())
                     dy += d->itemHeight(i);
             }
         }
     }
     d->scrollContentsBy(dx, dy);
 }
scrollTo()
void QTreeView::scrollTo (const QModelIndex & index, ScrollHint hint = EnsureVisible) virtual
Scroll the contents of the tree view until the given model item index is visible.
The hint parameter specifies more precisely where the item should be located after the operation. If any of the parents of the model item are collapsed, they will be expanded to ensure that the model item is visible.
Implements QAbstractItemView.
Definition at line 1141 of file qtreeview.cpp.
Referenced by QTreeWidget::scrollToItem().
 {
     Q_D(QTreeView);
     if (!d->isIndexValid(index))
         return;
     d->executePostedLayout();
     d->updateScrollBars();
     // Expand all parents if the parent(s) of the node are not expanded.
     QModelIndex parent = index.parent();
     while (parent.isValid() && state() == NoState && d->itemsExpandable) {
         if (!isExpanded(parent))
             expand(parent);
         parent = d->model->parent(parent);
     }
     int item = d->viewIndex(index);
     if (item < 0)
         return;
     QRect area = d->viewport->rect();
     // vertical
     if (verticalScrollMode() == QAbstractItemView::ScrollPerItem) {
         int top = verticalScrollBar()->value();
         int bottom = top + verticalScrollBar()->pageStep();
         if (hint == EnsureVisible && item >= top && item < bottom) {
             // nothing to do
         } else if (hint == PositionAtTop || (hint == EnsureVisible && item < top)) {
             verticalScrollBar()->setValue(item);
         } else { // PositionAtBottom or PositionAtCenter
             const int currentItemHeight = d->itemHeight(item);
             int y = (hint == PositionAtCenter
                  //we center on the current item with a preference to the top item (ie. -1)
                      ? area.height() / 2 + currentItemHeight - 1
                  //otherwise we simply take the whole space
                      : area.height());
             if (y > currentItemHeight) {
                 while (item >= 0) {
                     y -= d->itemHeight(item);
                     if (y < 0) { //there is no more space left
                         item++;
                         break;
                     }
                     item--;
                 }
             }
             verticalScrollBar()->setValue(item);
         }
     } else { // ScrollPerPixel
         QRect rect(columnViewportPosition(index.column()),
                    d->coordinateForItem(item), // ### slow for items outside the view
                    columnWidth(index.column()),
                    d->itemHeight(item));
         if (rect.isEmpty()) {
             // nothing to do
         } else if (hint == EnsureVisible && area.contains(rect)) {
             d->viewport->update(rect);
             // nothing to do
         } else {
             bool above = (hint == EnsureVisible
                         && (rect.top() < area.top()
                             || area.height() < rect.height()));
             bool below = (hint == EnsureVisible
                         && rect.bottom() > area.bottom()
                         && rect.height() < area.height());
             int verticalValue = verticalScrollBar()->value();
             if (hint == PositionAtTop || above)
                 verticalValue += rect.top();
             else if (hint == PositionAtBottom || below)
                 verticalValue += rect.bottom() - area.height();
             else if (hint == PositionAtCenter)
                 verticalValue += rect.top() - ((area.height() - rect.height()) / 2);
             verticalScrollBar()->setValue(verticalValue);
         }
     }
     // horizontal
     int viewportWidth = d->viewport->width();
     int horizontalOffset = d->header->offset();
     int horizontalPosition = d->header->sectionPosition(index.column());
     int cellWidth = d->header->sectionSize(index.column());
     if (hint == PositionAtCenter) {
         horizontalScrollBar()->setValue(horizontalPosition - ((viewportWidth - cellWidth) / 2));
     } else {
         if (horizontalPosition - horizontalOffset < 0 || cellWidth > viewportWidth)
             horizontalScrollBar()->setValue(horizontalPosition);
         else if (horizontalPosition - horizontalOffset + cellWidth > viewportWidth)
             horizontalScrollBar()->setValue(horizontalPosition - viewportWidth + cellWidth);
     }
 }
selectAll()
void QTreeView::selectAll () virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2667 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (!selectionModel())
         return;
     SelectionMode mode = d->selectionMode;
     d->executePostedLayout(); //make sure we lay out the items
     if (mode != SingleSelection && !d->viewItems.isEmpty()) {
         const QModelIndex &idx = d->viewItems.last().index;
         QModelIndex lastItemIndex = idx.sibling(idx.row(), d->model->columnCount(idx.parent()) - 1);
         d->select(d->viewItems.first().index, lastItemIndex,
                   QItemSelectionModel::ClearAndSelect
                   |QItemSelectionModel::Rows);
     }
 }
selectedIndexes()
QModelIndexList QTreeView::selectedIndexes () const protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2427 of file qtreeview.cpp.
Referenced by QTreeWidget::dropEvent().
 {
     QModelIndexList viewSelected;
     QModelIndexList modelSelected;
     if (selectionModel())
         modelSelected = selectionModel()->selectedIndexes();
     for (int i = 0; i < modelSelected.count(); ++i) {
         // check that neither the parents nor the index is hidden before we add
         QModelIndex index = modelSelected.at(i);
         while (index.isValid() && !isIndexHidden(index))
             index = index.parent();
         if (index.isValid())
             continue;
         viewSelected.append(modelSelected.at(i));
     }
     return viewSelected;
 }
selectionChanged()
void QTreeView::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 3857 of file qtreeview.cpp.
Referenced by QTreeWidget::QTreeWidget().
 {
     QAbstractItemView::selectionChanged(selected, deselected);
 #ifndef QT_NO_ACCESSIBILITY
     if (QAccessible::isActive()) {
         // ### does not work properly for selection ranges.
         QModelIndex sel = selected.indexes().value(0);
         if (sel.isValid()) {
 #ifdef Q_WS_X11
             int entry = (visualIndex(sel) + (header()?1:0))*sel.model()->columnCount()+sel.column() + 1;
             Q_ASSERT(entry > 0);
             QAccessible::updateAccessibility(this, entry, QAccessible::Selection);
 #else
             int entry = visualIndex(sel) + 1;
             if (header())
                 ++entry;
             QAccessible::updateAccessibility(viewport(), entry, QAccessible::Selection);
 #endif
         }
         QModelIndex desel = deselected.indexes().value(0);
         if (desel.isValid()) {
 #ifdef Q_WS_X11
             int entry = (visualIndex(desel) + (header()?1:0))*desel.model()->columnCount()+desel.column() + 1;
             Q_ASSERT(entry > 0);
             QAccessible::updateAccessibility(this, entry, QAccessible::SelectionRemove);
 #else
             int entry = visualIndex(desel) + 1;
             if (header())
                 ++entry;
             QAccessible::updateAccessibility(viewport(), entry, QAccessible::SelectionRemove);
 #endif
         }
     }
 #endif
 }
setAllColumnsShowFocus()
void QTreeView::setAllColumnsShowFocus (bool enable)
Definition at line 964 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (d->allColumnsShowFocus == enable)
         return;
     d->allColumnsShowFocus = enable;
     d->viewport->update();
 }
setAnimated()
void QTreeView::setAnimated (bool enable)
Definition at line 938 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->animationsEnabled = animate;
 }
setAutoExpandDelay()
void QTreeView::setAutoExpandDelay (int delay)
Definition at line 366 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->autoExpandDelay = delay;
 }
setColumnHidden()
void QTreeView::setColumnHidden (int column, bool hide)
If hide is true the column is hidden, otherwise the column is shown.
See also
hideColumn(), setRowHidden()
Definition at line 570 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (column < 0 || column >= d->header->count())
         return;
     d->header->setSectionHidden(column, hide);
 }
setColumnWidth()
void QTreeView::setColumnWidth (int column, int width)
Sets the width of the given column to the width specified.
Since
4.2
See also
columnWidth(), resizeColumnToContents()
Definition at line 538 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->header->resizeSection(column, width);
 }
setExpanded()
void QTreeView::setExpanded (const QModelIndex & index, bool expanded)
Sets the item referred to by index to either collapse or expanded, depending on the value of expanded.
See also
expanded(), expand(), isExpanded()
Definition at line 871 of file qtreeview.cpp.
Referenced by QTreeWidget::setItemExpanded(), and timerEvent().
 {
     if (expanded)
         this->expand(index);
     else
         this->collapse(index);
 }
setExpandsOnDoubleClick()
void QTreeView::setExpandsOnDoubleClick (bool enable)
Definition at line 502 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->expandsOnDoubleClick = enable;
 }
setFirstColumnSpanned()
void QTreeView::setFirstColumnSpanned (int row, const QModelIndex & parent, bool span)
If span is true the item in the first column in the row with the given parent is set to span all columns, otherwise all items on the row are shown.
Since
4.3
See also
isFirstColumnSpanned()
Definition at line 675 of file qtreeview.cpp.
Referenced by QTreeWidget::setFirstItemColumnSpanned().
 {
     Q_D(QTreeView);
     if (!d->model)
         return;
     QModelIndex index = d->model->index(row, 0, parent);
     if (!index.isValid())
         return;
     if (span) {
         QPersistentModelIndex persistent(index);
         if (!d->spanningIndexes.contains(persistent))
             d->spanningIndexes.append(persistent);
     } else {
         QPersistentModelIndex persistent(index);
         int i = d->spanningIndexes.indexOf(persistent);
         if (i >= 0)
             d->spanningIndexes.remove(i);
     }
     d->executePostedLayout();
     int i = d->viewIndex(index);
     if (i >= 0)
         d->viewItems[i].spanning = span;
     d->viewport->update();
 }
setHeader()
void QTreeView::setHeader (QHeaderView * header)
Sets the header for the tree view, to the given header.
The view takes ownership over the given header and deletes it when a new header is set.
See also
QAbstractItemModel::headerData()
Definition at line 316 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (header == d->header || !header)
         return;
     if (d->header && d->header->parent() == this)
         delete d->header;
     d->header = header;
     d->header->setParent(this);
     if (!d->header->model()) {
         d->header->setModel(d->model);
         if (d->selectionModel)
             d->header->setSelectionModel(d->selectionModel);
     }
     connect(d->header, SIGNAL(sectionResized(int,int,int)),
             this, SLOT(columnResized(int,int,int)));
     connect(d->header, SIGNAL(sectionMoved(int,int,int)),
             this, SLOT(columnMoved()));
     connect(d->header, SIGNAL(sectionCountChanged(int,int)),
             this, SLOT(columnCountChanged(int,int)));
     connect(d->header, SIGNAL(sectionHandleDoubleClicked(int)),
             this, SLOT(resizeColumnToContents(int)));
     connect(d->header, SIGNAL(geometriesChanged()),
             this, SLOT(updateGeometries()));
     setSortingEnabled(d->sortingEnabled);
 }
setHeaderHidden()
void QTreeView::setHeaderHidden (bool hide)
Definition at line 597 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->header->setHidden(hide);
 }
setIndentation()
void QTreeView::setIndentation (int i)
Definition at line 392 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (i != d->indent) {
         d->indent = i;
         d->viewport->update();
     }
 }
setItemsExpandable()
void QTreeView::setItemsExpandable (bool enable)
Definition at line 477 of file qtreeview.cpp.
Referenced by QFileDialogTreeView::init().
 {
     Q_D(QTreeView);
     d->itemsExpandable = enable;
 }
setModel()
void QTreeView::setModel (QAbstractItemModel * model) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Reimplemented in QTreeWidget.
Definition at line 223 of file qtreeview.cpp.
Referenced by QTreeWidget::QTreeWidget().
 {
     Q_D(QTreeView);
     if (model == d->model)
         return;
     if (d->model && d->model != QAbstractItemModelPrivate::staticEmptyModel()) {
         disconnect(d->model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                 this, SLOT(rowsRemoved(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(modelAboutToBeReset()), this, SLOT(_q_modelAboutToBeReset()));
     }
     if (d->selectionModel) { // support row editing
         disconnect(d->selectionModel, SIGNAL(currentRowChanged(QModelIndex,QModelIndex)),
                    d->model, SLOT(submit()));
         disconnect(d->model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                    this, SLOT(rowsRemoved(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(modelAboutToBeReset()), this, SLOT(_q_modelAboutToBeReset()));
     }
     d->viewItems.clear();
     d->expandedIndexes.clear();
     d->hiddenIndexes.clear();
     d->header->setModel(model);
     QAbstractItemView::setModel(model);
     // QAbstractItemView connects to a private slot
     disconnect(d->model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                this, SLOT(_q_rowsRemoved(QModelIndex,int,int)));
     // do header layout after the tree
     disconnect(d->model, SIGNAL(layoutChanged()),
                d->header, SLOT(_q_layoutChanged()));
     // QTreeView has a public slot for this
     connect(d->model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
             this, SLOT(rowsRemoved(QModelIndex,int,int)));
     connect(d->model, SIGNAL(modelAboutToBeReset()), SLOT(_q_modelAboutToBeReset()));
     if (d->sortingEnabled)
         d->_q_sortIndicatorChanged(header()->sortIndicatorSection(), header()->sortIndicatorOrder());
 }
setRootIndex()
void QTreeView::setRootIndex (const QModelIndex & index) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 267 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->header->setRootIndex(index);
     QAbstractItemView::setRootIndex(index);
 }
setRootIsDecorated()
void QTreeView::setRootIsDecorated (bool show)
Definition at line 421 of file qtreeview.cpp.
Referenced by QFileDialogTreeView::init().
 {
     Q_D(QTreeView);
     if (show != d->rootDecoration) {
         d->rootDecoration = show;
         d->viewport->update();
     }
 }
setRowHidden()
void QTreeView::setRowHidden (int row, const QModelIndex & parent, bool hide)
If hide is true the row with the given parent is hidden, otherwise the row is shown.
See also
isRowHidden(), setColumnHidden()
Definition at line 622 of file qtreeview.cpp.
Referenced by QTreeWidget::setItemHidden().
 {
     Q_D(QTreeView);
     if (!d->model)
         return;
     QModelIndex index = d->model->index(row, 0, parent);
     if (!index.isValid())
         return;
     if (hide) {
         d->hiddenIndexes.insert(index);
     } else if(d->isPersistent(index)) { //if the index is not persistent, it cannot be in the set
         d->hiddenIndexes.remove(index);
     }
     d->doDelayedItemsLayout();
 }
setSelection()
void QTreeView::setSelection (const QRect & rect, QItemSelectionModel::SelectionFlags command) protected virtual
Applies the selection command to the items in or touched by the rectangle, rect.
See also
selectionCommand()
Implements QAbstractItemView.
Definition at line 2330 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (!selectionModel() || rect.isNull())
         return;
     d->executePostedLayout();
     QPoint tl(isRightToLeft() ? qMax(rect.left(), rect.right())
               : qMin(rect.left(), rect.right()), qMin(rect.top(), rect.bottom()));
     QPoint br(isRightToLeft() ? qMin(rect.left(), rect.right()) :
               qMax(rect.left(), rect.right()), qMax(rect.top(), rect.bottom()));
     QModelIndex topLeft = indexAt(tl);
     QModelIndex bottomRight = indexAt(br);
     if (!topLeft.isValid() && !bottomRight.isValid()) {
         if (command & QItemSelectionModel::Clear)
             selectionModel()->clear();
         return;
     }
     if (!topLeft.isValid() && !d->viewItems.isEmpty())
         topLeft = d->viewItems.first().index;
     if (!bottomRight.isValid() && !d->viewItems.isEmpty()) {
         const int column = d->header->logicalIndex(d->header->count() - 1);
         const QModelIndex index = d->viewItems.last().index;
         bottomRight = index.sibling(index.row(), column);
     }
     if (!d->isIndexEnabled(topLeft) || !d->isIndexEnabled(bottomRight))
         return;
     d->select(topLeft, bottomRight, command);
 }
setSelectionModel()
void QTreeView::setSelectionModel (QItemSelectionModel * selectionModel) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Reimplemented in QTreeWidget.
Definition at line 277 of file qtreeview.cpp.
Referenced by QTreeWidget::setSelectionModel().
 {
     Q_D(QTreeView);
     Q_ASSERT(selectionModel);
     if (d->selectionModel) {
         // support row editing
         disconnect(d->selectionModel, SIGNAL(currentRowChanged(QModelIndex,QModelIndex)),
                    d->model, SLOT(submit()));
     }
     d->header->setSelectionModel(selectionModel);
     QAbstractItemView::setSelectionModel(selectionModel);
     if (d->selectionModel) {
         // support row editing
         connect(d->selectionModel, SIGNAL(currentRowChanged(QModelIndex,QModelIndex)),
                 d->model, SLOT(submit()));
     }
 }
setSortingEnabled()
void QTreeView::setSortingEnabled (bool enable)
Definition at line 898 of file qtreeview.cpp.
Referenced by QFileDialogTreeView::init(), setHeader(), and QTreeWidget::setSortingEnabled().
 {
     Q_D(QTreeView);
     header()->setSortIndicatorShown(enable);
     header()->setClickable(enable);
     if (enable) {
         //sortByColumn has to be called before we connect or set the sortingEnabled flag
         // because otherwise it will not call sort on the model.
         sortByColumn(header()->sortIndicatorSection(), header()->sortIndicatorOrder());
         connect(header(), SIGNAL(sortIndicatorChanged(int,Qt::SortOrder)),
                 this, SLOT(_q_sortIndicatorChanged(int,Qt::SortOrder)), Qt::UniqueConnection);
     } else {
         disconnect(header(), SIGNAL(sortIndicatorChanged(int,Qt::SortOrder)),
                    this, SLOT(_q_sortIndicatorChanged(int,Qt::SortOrder)));
     }
     d->sortingEnabled = enable;
 }
setUniformRowHeights()
void QTreeView::setUniformRowHeights (bool uniform)
Definition at line 452 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->uniformRowHeights = uniform;
 }
setWordWrap()
void QTreeView::setWordWrap (bool on)
Definition at line 995 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (d->wrapItemText == on)
         return;
     d->wrapItemText = on;
     d->doDelayedItemsLayout();
 }
showColumn
void QTreeView::showColumn (int column) slot
Shows the given column in the tree view.
See also
hideColumn(), setColumnHidden()
Definition at line 771 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     d->header->showSection(column);
 }
sizeHintForColumn()
int QTreeView::sizeHintForColumn (int column) const protected virtual
Returns the size hint for the column's width or -1 if there is no model.
If you need to set the width of a given column to a fixed value, call QHeaderView::resizeSection() on the view's header.
If you reimplement this function in a subclass, note that the value you return is only used when resizeColumnToContents() is called. In that case, if a larger column width is required by either the view's header or the item delegate, that width will be used instead.
See also
QWidget::sizeHint, header()
Reimplemented from QAbstractItemView.
Definition at line 2801 of file qtreeview.cpp.
Referenced by resizeColumnToContents().
 {
     Q_D(const QTreeView);
     d->executePostedLayout();
     if (d->viewItems.isEmpty())
         return -1;
     ensurePolished();
     int w = 0;
     QStyleOptionViewItemV4 option = d->viewOptionsV4();
     const QVector<QTreeViewItem> viewItems = d->viewItems;
     int start = 0;
     int end = viewItems.count();
     if(end > 1000) { //if we have too many item this function would be too slow.
         //we get a good approximation by only iterate over 1000 items.
         start = qMax(0, d->firstVisibleItem() - 100);
         end = qMin(end, start + 900);
     }
     for (int i = start; i < end; ++i) {
         if (viewItems.at(i).spanning)
             continue; // we have no good size hint
         QModelIndex index = viewItems.at(i).index;
         index = index.sibling(index.row(), column);
         QWidget *editor = d->editorForIndex(index).widget.data();
         if (editor && d->persistent.contains(editor)) {
             w = qMax(w, editor->sizeHint().width());
             int min = editor->minimumSize().width();
             int max = editor->maximumSize().width();
             w = qBound(min, w, max);
         }
         int hint = d->delegateForIndex(index)->sizeHint(option, index).width();
         w = qMax(w, hint + (column == 0 ? d->indentationForItem(i) : 0));
     }
     return w;
 }
sortByColumn() [1/2]
void QTreeView::sortByColumn (int column, Qt::SortOrder order)
Sets the model up for sorting by the values in the given column and order.
Since
4.2
column may be -1, in which case no sort indicator will be shown and the model will return to its natural, unsorted order. Note that not all models support this and may even crash in this case.
See also
sortingEnabled
Definition at line 2653 of file qtreeview.cpp.
Referenced by setSortingEnabled(), and sortByColumn().
 {
     Q_D(QTreeView);
     //If sorting is enabled  will emit a signal connected to _q_sortIndicatorChanged, which then actually sorts
     d->header->setSortIndicator(column, order);
     //If sorting is not enabled, force to sort now.
     if (!d->sortingEnabled)
         d->model->sort(column, order);
 }
sortByColumn [2/2]
void QTreeView::sortByColumn (int column) slot
Sorts the model by the values in the given column.
Definition at line 2633 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     sortByColumn(column, d->header->sortIndicatorOrder());
 }
timerEvent()
void QTreeView::timerEvent (QTimerEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1240 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     if (event->timerId() == d->columnResizeTimerID) {
         updateGeometries();
         killTimer(d->columnResizeTimerID);
         d->columnResizeTimerID = 0;
         QRect rect;
         int viewportHeight = d->viewport->height();
         int viewportWidth = d->viewport->width();
         for (int i = d->columnsToUpdate.size() - 1; i >= 0; --i) {
             int column = d->columnsToUpdate.at(i);
             int x = columnViewportPosition(column);
             if (isRightToLeft())
                 rect |= QRect(0, 0, x + columnWidth(column), viewportHeight);
             else
                 rect |= QRect(x, 0, viewportWidth - x, viewportHeight);
         }
         d->viewport->update(rect.normalized());
         d->columnsToUpdate.clear();
     } else if (event->timerId() == d->openTimer.timerId()) {
         QPoint pos = d->viewport->mapFromGlobal(QCursor::pos());
         if (state() == QAbstractItemView::DraggingState
             && d->viewport->rect().contains(pos)) {
             QModelIndex index = indexAt(pos);
             setExpanded(index, !isExpanded(index));
         }
         d->openTimer.stop();
     }
     QAbstractItemView::timerEvent(event);
 }
uniformRowHeights()
bool QTreeView::uniformRowHeights () const
Referenced by QTreeViewPrivate::coordinateForItem(), QTreeViewPrivate::firstVisibleItem(), QTreeViewPrivate::itemAtCoordinate(), QTreeViewPrivate::itemHeight(), QTreeViewPrivate::layout(), setRootIsDecorated(), and QTreeViewPrivate::updateScrollBars().
updateGeometries()
void QTreeView::updateGeometries () protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2767 of file qtreeview.cpp.
Referenced by collapse(), columnCountChanged(), expand(), expandAll(), expandToDepth(), mouseDoubleClickEvent(), moveCursor(), setHeader(), and timerEvent().
 {
     Q_D(QTreeView);
     if (d->header) {
         if (d->geometryRecursionBlock)
             return;
         d->geometryRecursionBlock = true;
         QSize hint = d->header->isHidden() ? QSize(0, 0) : d->header->sizeHint();
         setViewportMargins(0, hint.height(), 0, 0);
         QRect vg = d->viewport->geometry();
         QRect geometryRect(vg.left(), vg.top() - hint.height(), vg.width(), hint.height());
         d->header->setGeometry(geometryRect);
         //d->header->setOffset(horizontalScrollBar()->value()); // ### bug ???
         QMetaObject::invokeMethod(d->header, "updateGeometries");
         d->updateScrollBars();
         d->geometryRecursionBlock = false;
     }
     QAbstractItemView::updateGeometries();
 }
verticalOffset()
int QTreeView::verticalOffset () const protected virtual
Returns the vertical offset of the items in the tree view.
See also
horizontalOffset()
Implements QAbstractItemView.
Definition at line 2142 of file qtreeview.cpp.
Referenced by drawBranches().
 {
     Q_D(const QTreeView);
     if (d->verticalScrollMode == QAbstractItemView::ScrollPerItem) {
         if (d->uniformRowHeights)
             return verticalScrollBar()->value() * d->defaultItemHeight;
         // If we are scrolling per item and have non-uniform row heights,
         // finding the vertical offset in pixels is going to be relatively slow.
         // ### find a faster way to do this
         d->executePostedLayout();
         int offset = 0;
         for (int i = 0; i < d->viewItems.count(); ++i) {
             if (i == verticalScrollBar()->value())
                 return offset;
             offset += d->itemHeight(i);
         }
         return 0;
     }
     // scroll per pixel
     return verticalScrollBar()->value();
 }
viewportEvent()
bool QTreeView::viewportEvent (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1289 of file qtreeview.cpp.
 {
     Q_D(QTreeView);
     switch (event->type()) {
     case QEvent::HoverEnter:
     case QEvent::HoverLeave:
     case QEvent::HoverMove: {
         QHoverEvent *he = static_cast<QHoverEvent*>(event);
         int oldBranch = d->hoverBranch;
         d->hoverBranch = d->itemDecorationAt(he->pos());
         QModelIndex newIndex = indexAt(he->pos());
         if (d->hover != newIndex || d->hoverBranch != oldBranch) {
             // Update the whole hovered over row. No need to update the old hovered
             // row, that is taken care in superclass hover handling.
             QRect rect = visualRect(newIndex);
             rect.setX(0);
             rect.setWidth(viewport()->width());
             viewport()->update(rect);
         }
         break; }
     default:
         break;
     }
     return QAbstractItemView::viewportEvent(event);
 }
visualIndex()
int QTreeView::visualIndex (const QModelIndex & index) const private
Definition at line 3894 of file qtreeview.cpp.
Referenced by QTreeViewPrivate::adjustViewOptionsForIndex(), QTreeViewPrivate::calcLogicalIndices(), currentChanged(), indexAt(), and selectionChanged().
 {
     Q_D(const QTreeView);
     d->executePostedLayout();
     return d->viewIndex(index);
 }
visualRect()
QRect QTreeView::visualRect (const QModelIndex & index) const virtual
Returns the rectangle on the viewport occupied by the item at index.
If the index is not visible or explicitly hidden, the returned rectangle is invalid.
Implements QAbstractItemView.
Definition at line 1101 of file qtreeview.cpp.
Referenced by currentChanged(), viewportEvent(), QTreeWidget::visualItemRect(), and visualRegionForSelection().
 {
     Q_D(const QTreeView);
     if (!d->isIndexValid(index) || isIndexHidden(index))
         return QRect();
     d->executePostedLayout();
     int vi = d->viewIndex(index);
     if (vi < 0)
         return QRect();
     bool spanning = d->viewItems.at(vi).spanning;
     // if we have a spanning item, make the selection stretch from left to right
     int x = (spanning ? 0 : columnViewportPosition(index.column()));
     int w = (spanning ? d->header->length() : columnWidth(index.column()));
     // handle indentation
     if (index.column() == 0) {
         int i = d->indentationForItem(vi);
         w -= i;
         if (!isRightToLeft())
             x += i;
     }
     int y = d->coordinateForItem(vi);
     int h = d->itemHeight(vi);
     return QRect(x, y, w, h);
 }
visualRegionForSelection()
QRegion QTreeView::visualRegionForSelection (const QItemSelection & selection) const protected virtual
Returns the rectangle from the viewport of the items in the given selection.
Since 4.7, the returned region only contains rectangles intersecting (or included in) the viewport.
Implements QAbstractItemView.
Definition at line 2369 of file qtreeview.cpp.
 {
     Q_D(const QTreeView);
     if (selection.isEmpty())
         return QRegion();
     QRegion selectionRegion;
     const QRect &viewportRect = d->viewport->rect();
     for (int i = 0; i < selection.count(); ++i) {
         QItemSelectionRange range = selection.at(i);
         if (!range.isValid())
             continue;
         QModelIndex parent = range.parent();
         QModelIndex leftIndex = range.topLeft();
         int columnCount = d->model->columnCount(parent);
         while (leftIndex.isValid() && isIndexHidden(leftIndex)) {
             if (leftIndex.column() + 1 < columnCount)
                 leftIndex = d->model->index(leftIndex.row(), leftIndex.column() + 1, parent);
             else
                 leftIndex = QModelIndex();
         }
         if (!leftIndex.isValid())
             continue;
         const QRect leftRect = visualRect(leftIndex);
         int top = leftRect.top();
         QModelIndex rightIndex = range.bottomRight();
         while (rightIndex.isValid() && isIndexHidden(rightIndex)) {
             if (rightIndex.column() - 1 >= 0)
                 rightIndex = d->model->index(rightIndex.row(), rightIndex.column() - 1, parent);
             else
                 rightIndex = QModelIndex();
         }
         if (!rightIndex.isValid())
             continue;
         const QRect rightRect = visualRect(rightIndex);
         int bottom = rightRect.bottom();
         if (top > bottom)
             qSwap<int>(top, bottom);
         int height = bottom - top + 1;
         if (d->header->sectionsMoved()) {
             for (int c = range.left(); c <= range.right(); ++c) {
                 const QRect rangeRect(columnViewportPosition(c), top, columnWidth(c), height);
                 if (viewportRect.intersects(rangeRect))
                     selectionRegion += rangeRect;
             }
         } else {
             QRect combined = leftRect|rightRect;
             combined.setX(columnViewportPosition(isRightToLeft() ? range.right() : range.left()));
             if (viewportRect.intersects(combined))
                 selectionRegion += combined;
         }
     }
     return selectionRegion;
 }
wordWrap()
bool QTreeView::wordWrap () const
Referenced by setWordWrap().
Friends and Related Functions
QAccessibleItemView
friend class QAccessibleItemView friend
Definition at line 221 of file qtreeview.h.
QAccessibleTable2
friend class QAccessibleTable2 friend
Definition at line 222 of file qtreeview.h.
QAccessibleTable2Cell
friend class QAccessibleTable2Cell friend
Definition at line 224 of file qtreeview.h.
QAccessibleTree
friend class QAccessibleTree friend
Definition at line 223 of file qtreeview.h.
Properties
allColumnsShowFocus
bool QTreeView::allColumnsShowFocus private
whether items should show keyboard focus using all columns
Since
4.2
If this property is true all columns will show focus, otherwise only one column will show focus.
The default is false.
Definition at line 68 of file qtreeview.h.
animated
QTreeView::animated private
whether animations are enabled
Since
4.2
If this property is true the treeview will animate expandsion and collasping of branches. If this property is false, the treeview will expand or collapse branches immediately without showing the animation.
By default, this property is false.
Definition at line 67 of file qtreeview.h.
autoExpandDelay
int QTreeView::autoExpandDelay private
The delay time before items in a tree are opened during a drag and drop operation.
Since
4.3
This property holds the amount of time in milliseconds that the user must wait over a node before that node will automatically open or close. If the time is set to less then 0 then it will not be activated.
By default, this property has a value of -1, meaning that auto-expansion is disabled.
Definition at line 61 of file qtreeview.h.
expandsOnDoubleClick
bool QTreeView::expandsOnDoubleClick private
whether the items can be expanded by double-clicking.
Since
4.4
This property holds whether the user can expand and collapse items by double-clicking. The default value is true.
See also
itemsExpandable
Definition at line 71 of file qtreeview.h.
headerHidden
QTreeView::headerHidden private
whether the header is shown or not.
Since
4.4
If this property is true, the header is not shown otherwise it is. The default value is false.
See also
header()
Definition at line 70 of file qtreeview.h.
indentation
int QTreeView::indentation private
indentation of the items in the tree view.
This property holds the indentation measured in pixels of the items for each level in the tree view. For top-level items, the indentation specifies the horizontal distance from the viewport edge to the items in the first column; for child items, it specifies their indentation from their parent items.
By default, this property has a value of 20.
Definition at line 62 of file qtreeview.h.
itemsExpandable
bool QTreeView::itemsExpandable private
whether the items are expandable by the user.
This property holds whether the user can expand and collapse items interactively.
By default, this property is true.
Definition at line 65 of file qtreeview.h.
rootIsDecorated
bool QTreeView::rootIsDecorated private
whether to show controls for expanding and collapsing top-level items
Items with children are typically shown with controls to expand and collapse them, allowing their children to be shown or hidden. If this property is false, these controls are not shown for top-level items. This can be used to make a single level tree structure appear like a simple list of items.
By default, this property is true.
Definition at line 63 of file qtreeview.h.
sortingEnabled
QTreeView::sortingEnabled private
whether sorting is enabled
Since
4.2
If this property is true, sorting is enabled for the tree; if the property is false, sorting is not enabled. The default value is false.
Note
In order to avoid performance issues, it is recommended that sorting is enabled after inserting the items into the tree. Alternatively, you could also insert the items into a list before inserting the items into the tree.
See also
sortByColumn()
Definition at line 66 of file qtreeview.h.
uniformRowHeights
bool QTreeView::uniformRowHeights private
whether all items in the treeview have the same height
This property should only be set to true if it is guaranteed that all items in the view has the same height. This enables the view to do some optimizations.
The height is obtained from the first item in the view. It is updated when the data changes on that item.
By default, this property is false.
Definition at line 64 of file qtreeview.h.
wordWrap
bool QTreeView::wordWrap private
the item text word-wrapping policy
Since
4.3
If this property is true then the item text is wrapped where necessary at word-breaks; otherwise it is not wrapped at all. This property is false by default.
Note that even if wrapping is enabled, the cell will not be expanded to fit all text. Ellipsis will be inserted according to the current QAbstractItemView::textElideMode.
Definition at line 69 of file qtreeview.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qtreeview.h
/src/gui/itemviews/qtreeview.cpp