Qt 4.8: QSqlDriver Class Reference
QSqlDriver Class Reference abstract
The QSqlDriver class is an abstract base class for accessing specific SQL databases.
#include <qsqldriver.h>
Public Types
enum DriverFeature {
Transactions, QuerySize, BLOB, Unicode,
PreparedQueries, NamedPlaceholders, PositionalPlaceholders, LastInsertId,
BatchOperations, SimpleLocking, LowPrecisionNumbers, EventNotifications,
FinishQuery, MultipleResultSets
}
This enum contains a list of features a driver might support.
enum IdentifierType { FieldName, TableName }
This enum contains a list of SQL identifier types.
enum StatementType {
WhereStatement, SelectStatement, UpdateStatement, InsertStatement,
DeleteStatement
}
This enum contains a list of SQL statement (or clause) types the driver can create.
Signals
void notification (const QString &name)
This signal is emitted when the database posts an event notification that the driver subscribes to.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual bool beginTransaction ()
This function is called to begin a transaction.
virtual void close ()=0
Derived classes must reimplement this pure virtual function in order to close the database connection.
virtual bool commitTransaction ()
This function is called to commit a transaction.
virtual QSqlResult * createResult () const =0
Creates an empty SQL result on the database.
virtual QString escapeIdentifier (const QString &identifier, IdentifierType type) const
Returns the identifier escaped according to the database rules.
virtual QString formatValue (const QSqlField &field, bool trimStrings=false) const
Returns a string representation of the field value for the database.
virtual QVariant handle () const
Returns the low-level database handle wrapped in a QVariant or an invalid variant if there is no handle.
virtual bool hasFeature (DriverFeature f) const =0
Returns true if the driver supports feature feature; otherwise returns false.
bool isIdentifierEscaped (const QString &identifier, IdentifierType type) const
Returns whether identifier is escaped according to the database rules.
virtual bool isOpen () const
Returns true if the database connection is open; otherwise returns false.
bool isOpenError () const
Returns true if the there was an error opening the database connection; otherwise returns false.
QSqlError lastError () const
Returns a QSqlError object which contains information about the last error that occurred on the database.
QSql::NumericalPrecisionPolicy numericalPrecisionPolicy () const
Returns the current default precision policy for the database connection.
virtual bool open (const QString &db, const QString &user=QString(), const QString &password=QString(), const QString &host=QString(), int port=-1, const QString &connOpts=QString())=0
Derived classes must reimplement this pure virtual function to open a database connection on database db, using user name user, password password, host host, port port and connection options options.
virtual QSqlIndex primaryIndex (const QString &tableName) const
Returns the primary index for table tableName.
QSqlDriver (QObject *parent=0)
Constructs a new driver with the given parent.
virtual QSqlRecord record (const QString &tableName) const
Returns a QSqlRecord populated with the names of the fields in table tableName.
virtual bool rollbackTransaction ()
This function is called to rollback a transaction.
void setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy precisionPolicy)
Sets the default numerical precision policy used by queries created by this driver to precisionPolicy.
virtual QString sqlStatement (StatementType type, const QString &tableName, const QSqlRecord &rec, bool preparedStatement) const
Returns a SQL statement of type type for the table tableName with the values from rec.
QString stripDelimiters (const QString &identifier, IdentifierType type) const
Returns the identifier with the leading and trailing delimiters removed, identifier can either be a table name or field name, dependent on type.
QStringList subscribedToNotifications () const
Returns a list of the names of the event notifications that are currently subscribed to.
bool subscribeToNotification (const QString &name)
This function is called to subscribe to event notifications from the database.
virtual QStringList tables (QSql::TableType tableType) const
Returns a list of the names of the tables in the database.
bool unsubscribeFromNotification (const QString &name)
This function is called to unsubscribe from event notifications from the database.
~QSqlDriver ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Slots
bool isIdentifierEscapedImplementation (const QString &identifier, IdentifierType type) const
This slot returns whether identifier is escaped according to the database rules.
QString stripDelimitersImplementation (const QString &identifier, IdentifierType type) const
This slot returns identifier with the leading and trailing delimiters removed, identifier can either be a tablename or field name, dependent on type.
QStringList subscribedToNotificationsImplementation () const
Returns a list of the names of the event notifications that are currently subscribed to.
bool subscribeToNotificationImplementation (const QString &name)
This slot is called to subscribe to event notifications from the database.
bool unsubscribeFromNotificationImplementation (const QString &name)
This slot is called to unsubscribe from event notifications from the database.
Protected Functions
virtual void setLastError (const QSqlError &e)
This function is used to set the value of the last error, error, that occurred on the database.
virtual void setOpen (bool o)
This function sets the open state of the database to open.
virtual void setOpenError (bool e)
This function sets the open error state of the database to error.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Friends
class QSqlDatabase
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSqlDriver class is an abstract base class for accessing specific SQL databases.
Attention
Module: QtSql
This class should not be used directly. Use QSqlDatabase instead.
If you want to create your own SQL drivers, you can subclass this class and reimplement its pure virtual functions and those virtual functions that you need. See How to Write Your Own Database Driver for more information.
See also
QSqlDatabase, QSqlResult
Definition at line 68 of file qsqldriver.h.
Enumerations
DriverFeature
enum QSqlDriver::DriverFeature
This enum contains a list of features a driver might support.
Use hasFeature() to query whether a feature is supported or not.
Transactions Whether the driver supports SQL transactions.
QuerySize Whether the database is capable of reporting the size of a query. Note that some databases do not support returning the size (i.e. number of rows returned) of a query, in which case QSqlQuery::size() will return -1.
BLOB Whether the driver supports Binary Large Object fields.
Unicode Whether the driver supports Unicode strings if the database server does.
PreparedQueries Whether the driver supports prepared query execution.
NamedPlaceholders Whether the driver supports the use of named placeholders.
PositionalPlaceholders Whether the driver supports the use of positional placeholders.
LastInsertId Whether the driver supports returning the Id of the last touched row.
BatchOperations Whether the driver supports batched operations, see QSqlQuery::execBatch()
SimpleLocking Whether the driver disallows a write lock on a table while other queries have a read lock on it.
LowPrecisionNumbers Whether the driver allows fetching numerical values with low precision.
EventNotifications Whether the driver supports database event notifications.
FinishQuery Whether the driver can do any low-level resource cleanup when QSqlQuery::finish() is called.
MultipleResultSets Whether the driver can access multiple result sets returned from batched statements or stored procedures.
More information about supported features can be found in the Qt SQL driver documentation.
See also
hasFeature()
Enumerator
Transactions
QuerySize
BLOB
Unicode
PreparedQueries
NamedPlaceholders
PositionalPlaceholders
LastInsertId
BatchOperations
SimpleLocking
LowPrecisionNumbers
EventNotifications
FinishQuery
MultipleResultSets
Definition at line 75 of file qsqldriver.h.
                        { Transactions, QuerySize, BLOB, Unicode, PreparedQueries,
                          NamedPlaceholders, PositionalPlaceholders, LastInsertId,
                          BatchOperations, SimpleLocking, LowPrecisionNumbers,
                          EventNotifications, FinishQuery, MultipleResultSets };
IdentifierType
enum QSqlDriver::IdentifierType
This enum contains a list of SQL identifier types.
FieldName A SQL field name
TableName A SQL table name
Enumerator
FieldName
TableName
Definition at line 83 of file qsqldriver.h.
 { FieldName, TableName };
StatementType
enum QSqlDriver::StatementType
This enum contains a list of SQL statement (or clause) types the driver can create.
WhereStatement An SQL WHERE statement (e.g., WHERE f = 5).
SelectStatement An SQL SELECT statement (e.g., SELECT f FROM t).
UpdateStatement An SQL UPDATE statement (e.g., UPDATE TABLE t set f = 1).
InsertStatement An SQL INSERT statement (e.g., INSERT INTO t (f) values (1)).
DeleteStatement An SQL DELETE statement (e.g., DELETE FROM t).
See also
sqlStatement()
Enumerator
WhereStatement
SelectStatement
UpdateStatement
InsertStatement
DeleteStatement
Definition at line 80 of file qsqldriver.h.
                        { WhereStatement, SelectStatement, UpdateStatement,
                          InsertStatement, DeleteStatement };
Constructors and Destructors
QSqlDriver()
QSqlDriver::QSqlDriver (QObject * parent = 0) explicit
Constructs a new driver with the given parent.
Definition at line 112 of file qsqldriver.cpp.
     : QObject(*new QSqlDriverPrivate, parent)
 {
 }
~QSqlDriver()
QSqlDriver::~QSqlDriver ()
Destroys the object and frees any allocated resources.
Definition at line 121 of file qsqldriver.cpp.
 {
 }
Functions
beginTransaction()
bool QSqlDriver::beginTransaction () virtual
This function is called to begin a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
commitTransaction(), rollbackTransaction()
Reimplemented in QODBCDriver, QPSQLDriver, QMYSQLDriver, QTDSDriver, QOCIDriver, QSymSQLDriver, QSQLite2Driver, QSQLiteDriver, QIBaseDriver, and QDB2Driver.
Definition at line 312 of file qsqldriver.cpp.
 {
     return false;
 }
close()
bool QSqlDriver::close () pure virtual
Derived classes must reimplement this pure virtual function in order to close the database connection.
Return true on success, false on failure.
See also
open(), setOpen()
Implemented in QPSQLDriver, QODBCDriver, QMYSQLDriver, QSymSQLDriver, QTDSDriver, QOCIDriver, QSQLite2Driver, QSQLiteDriver, QSqlNullDriver, QIBaseDriver, and QDB2Driver.
commitTransaction()
bool QSqlDriver::commitTransaction () virtual
This function is called to commit a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
beginTransaction(), rollbackTransaction()
Reimplemented in QODBCDriver, QPSQLDriver, QMYSQLDriver, QTDSDriver, QOCIDriver, QSymSQLDriver, QSQLite2Driver, QSQLiteDriver, QIBaseDriver, and QDB2Driver.
Definition at line 325 of file qsqldriver.cpp.
 {
     return false;
 }
createResult()
QSqlResult * QSqlDriver::createResult () const pure virtual
Creates an empty SQL result on the database.
Derived classes must reimplement this function and return a QSqlResult object appropriate for their database to the caller.
Implemented in QPSQLDriver, QODBCDriver, QMYSQLDriver, QTDSDriver, QSymSQLDriver, QOCIDriver, QSQLite2Driver, QSQLiteDriver, QSqlNullDriver, QIBaseDriver, and QDB2Driver.
Referenced by qInit().
escapeIdentifier()
QString QSqlDriver::escapeIdentifier (const QString & identifier, IdentifierType type) const virtual
Returns the identifier escaped according to the database rules.
identifier can either be a table name or field name, dependent on type.
The default implementation does nothing.
See also
isIdentifierEscaped()
Reimplemented in QODBCDriver, QPSQLDriver, QMYSQLDriver, QSymSQLDriver, QTDSDriver, QOCIDriver, QSQLite2Driver, QIBaseDriver, QDB2Driver, and QSQLiteDriver.
Definition at line 412 of file qsqldriver.cpp.
Referenced by prepareIdentifier().
 {
     return identifier;
 }
formatValue()
QString QSqlDriver::formatValue (const QSqlField & field, bool trimStrings = false) const virtual
Returns a string representation of the field value for the database.
Use the other formatValue() overload instead.
This is used, for example, when constructing INSERT and UPDATE statements.
The default implementation returns the value formatted as a string according to the following rules:
If field is character data, the value is returned enclosed in single quotation marks, which is appropriate for many SQL databases. Any embedded single-quote characters are escaped (replaced with two single-quote characters). If trimStrings is true (the default is false), all trailing whitespace is trimmed from the field.
If field is date/time data, the value is formatted in ISO format and enclosed in single quotation marks. If the date/time data is invalid, "NULL" is returned.
If field is bytearray data, and the driver can edit binary fields, the value is formatted as a hexadecimal string.
For any other field type, toString() is called on its value and the result of this is returned.
See also
QVariant::toString()
Reimplemented in QPSQLDriver, QODBCDriver, QMYSQLDriver, QTDSDriver, QOCIDriver, QIBaseDriver, and QDB2Driver.
Definition at line 597 of file qsqldriver.cpp.
Referenced by QDB2Driver::formatValue(), QIBaseDriver::formatValue(), QOCIDriver::formatValue(), QTDSDriver::formatValue(), QMYSQLDriver::formatValue(), QODBCDriver::formatValue(), QPSQLDriver::formatValue(), qCreateParamString(), and sqlStatement().
 {
     const QLatin1String nullTxt("NULL");
     QString r;
     if (field.isNull())
         r = nullTxt;
     else {
         switch (field.type()) {
         case QVariant::Int:
         case QVariant::UInt:
             if (field.value().type() == QVariant::Bool)
                 r = field.value().toBool() ? QLatin1String("1") : QLatin1String("0");
             else
                 r = field.value().toString();
             break;
 #ifndef QT_NO_DATESTRING
     case QVariant::Date:
             if (field.value().toDate().isValid())
                 r = QLatin1Char('\'') + field.value().toDate().toString(Qt::ISODate)
                     + QLatin1Char('\'');
             else
                 r = nullTxt;
             break;
         case QVariant::Time:
             if (field.value().toTime().isValid())
                 r =  QLatin1Char('\'') + field.value().toTime().toString(Qt::ISODate)
                      + QLatin1Char('\'');
             else
                 r = nullTxt;
             break;
         case QVariant::DateTime:
             if (field.value().toDateTime().isValid())
                 r = QLatin1Char('\'') +
                     field.value().toDateTime().toString(Qt::ISODate) + QLatin1Char('\'');
             else
                 r = nullTxt;
             break;
 #endif
         case QVariant::String:
         case QVariant::Char:
         {
             QString result = field.value().toString();
             if (trimStrings) {
                 int end = result.length();
                 while (end && result.at(end-1).isSpace()) /* skip white space from end */
                     end--;
                 result.truncate(end);
             }
             /* escape the "'" character */
             result.replace(QLatin1Char('\''), QLatin1String("''"));
             r = QLatin1Char('\'') + result + QLatin1Char('\'');
             break;
         }
         case QVariant::Bool:
             r = QString::number(field.value().toBool());
             break;
         case QVariant::ByteArray : {
             if (hasFeature(BLOB)) {
                 QByteArray ba = field.value().toByteArray();
                 QString res;
                 static const char hexchars[] = "0123456789abcdef";
                 for (int i = 0; i < ba.size(); ++i) {
                     uchar s = (uchar) ba[i];
                     res += QLatin1Char(hexchars[s >> 4]);
                     res += QLatin1Char(hexchars[s & 0x0f]);
                 }
                 r = QLatin1Char('\'') + res +  QLatin1Char('\'');
                 break;
             }
         }
         default:
             r = field.value().toString();
             break;
         }
     }
     return r;
 }
handle()
QVariant QSqlDriver::handle () const virtual
Returns the low-level database handle wrapped in a QVariant or an invalid variant if there is no handle.
Warning
Use this with uttermost care and only if you know what you're doing.
The handle returned here can become a stale pointer if the connection is modified (for example, if you close the connection).
The handle can be NULL if the connection is not open yet.
The handle returned here is database-dependent, you should query the type name of the variant before accessing it.
This example retrieves the handle for a connection to sqlite:
QSqlDatabase db = ...;
QVariant v = db.driver()->handle();
if (v.isValid() && qstrcmp(v.typeName(), "sqlite3*") == 0) {
    // v.data() returns a pointer to the handle
    sqlite3 *handle = *static_cast<sqlite3 **>(v.data());
    if (handle != 0) { // check that it is not NULL
        ...
    }
}
This snippet returns the handle for PostgreSQL or MySQL:
if (qstrcmp(v.typeName(), "PGconn*") == 0) {
    PGconn *handle = *static_cast<PGconn **>(v.data());
    if (handle != 0) ...
}
if (qstrcmp(v.typeName(), "MYSQL*") == 0) {
    MYSQL *handle = *static_cast<MYSQL **>(v.data());
    if (handle != 0) ...
}
See also
QSqlResult::handle()
Reimplemented in QPSQLDriver, QODBCDriver, QMYSQLDriver, QSymSQLDriver, QTDSDriver, QOCIDriver, QSQLite2Driver, QIBaseDriver, QSQLiteDriver, and QDB2Driver.
Definition at line 700 of file qsqldriver.cpp.
 {
     return QVariant();
 }
hasFeature()
bool QSqlDriver::hasFeature (DriverFeature feature) const pure virtual
Returns true if the driver supports feature feature; otherwise returns false.
Note that some databases need to be open() before this can be determined.
See also
DriverFeature
Implemented in QODBCDriver, QPSQLDriver, QMYSQLDriver, QSymSQLDriver, QTDSDriver, QOCIDriver, QSqlNullDriver, QDB2Driver, QSQLiteDriver, QSQLite2Driver, and QIBaseDriver.
Referenced by QSqlTableModelPrivate::exec(), formatValue(), and QSqlQueryModel::setQuery().
isIdentifierEscaped()
bool QSqlDriver::isIdentifierEscaped (const QString & identifier, IdentifierType type) const
Returns whether identifier is escaped according to the database rules.
identifier can either be a table name or field name, dependent on type.
Warning
Because of binary compatibility constraints, this function is not virtual. If you want to provide your own implementation in your QSqlDriver subclass, reimplement the isIdentifierEscapedImplementation() slot in your subclass instead. The isIdentifierEscapedFunction() will dynamically detect the slot and call it.
See also
stripDelimiters(), escapeIdentifier()
Definition at line 429 of file qsqldriver.cpp.
Referenced by QOCIDriver::escapeIdentifier(), QSqlTableModelPrivate::nameToIndex(), QRelation::populateDictionary(), prepareIdentifier(), QDB2Driver::primaryIndex(), QIBaseDriver::primaryIndex(), QSQLiteDriver::primaryIndex(), QOCIDriver::primaryIndex(), QSQLite2Driver::primaryIndex(), QTDSDriver::primaryIndex(), QODBCDriver::primaryIndex(), QPSQLDriver::primaryIndex(), qExtractSecurityPolicyFromString(), QDB2Driver::record(), QIBaseDriver::record(), QSQLiteDriver::record(), QOCIDriver::record(), QSQLite2Driver::record(), QTDSDriver::record(), QMYSQLDriver::record(), QODBCDriver::record(), QPSQLDriver::record(), stripDelimitersImplementation(), QDB2Driver::tables(), and QOCIDriver::tables().
 {
     bool result;
     QMetaObject::invokeMethod(const_cast<QSqlDriver*>(this),
                             "isIdentifierEscapedImplementation", Qt::DirectConnection,
                             Q_RETURN_ARG(bool, result),
                             Q_ARG(QString, identifier),
                             Q_ARG(IdentifierType, type));
     return result;
 }
isIdentifierEscapedImplementation
bool QSqlDriver::isIdentifierEscapedImplementation (const QString & identifier, IdentifierType type) const protected slot
This slot returns whether identifier is escaped according to the database rules.
Since
4.6
identifier can either be a table name or field name, dependent on type.
Because of binary compatibility constraints, isIdentifierEscaped() function (introduced in Qt 4.5) is not virtual. Instead, isIdentifierEscaped() will dynamically detect and call this slot. The default implementation assumes the escape/delimiter character is a double quote. Reimplement this slot in your own QSqlDriver if your database engine uses a different delimiter character.
See also
isIdentifierEscaped()
Definition at line 918 of file qsqldriver.cpp.
 {
     Q_UNUSED(type);
     return identifier.size() > 2
         && identifier.startsWith(QLatin1Char('"')) //left delimited
         && identifier.endsWith(QLatin1Char('"')); //right delimited
 }
isOpen()
bool QSqlDriver::isOpen () const virtual
Returns true if the database connection is open; otherwise returns false.
Reimplemented in QPSQLDriver.
Definition at line 182 of file qsqldriver.cpp.
Referenced by QDB2Driver::beginTransaction(), QIBaseDriver::beginTransaction(), QSQLiteDriver::beginTransaction(), QSQLite2Driver::beginTransaction(), QOCIDriver::beginTransaction(), QMYSQLDriver::beginTransaction(), QODBCDriver::beginTransaction(), QODBCDriver::cleanup(), QDB2Driver::close(), QIBaseDriver::close(), QSQLiteDriver::close(), QSQLite2Driver::close(), QOCIDriver::close(), QTDSDriver::close(), QMYSQLDriver::close(), QDB2Driver::commitTransaction(), QIBaseDriver::commitTransaction(), QSQLiteDriver::commitTransaction(), QSQLite2Driver::commitTransaction(), QOCIDriver::commitTransaction(), QMYSQLDriver::commitTransaction(), QODBCDriver::commitTransaction(), QMYSQLDriver::formatValue(), QIBaseDriver::open(), QSQLite2Driver::open(), QSQLiteDriver::open(), QOCIDriver::open(), QTDSDriver::open(), QDB2Driver::open(), QMYSQLDriver::open(), QODBCDriver::open(), QDB2Driver::primaryIndex(), QIBaseDriver::primaryIndex(), QSQLiteDriver::primaryIndex(), QOCIDriver::primaryIndex(), QSQLite2Driver::primaryIndex(), QTDSDriver::primaryIndex(), QMYSQLDriver::primaryIndex(), QODBCDriver::primaryIndex(), qExtractSecurityPolicyFromString(), QDB2Driver::record(), QIBaseDriver::record(), QSQLiteDriver::record(), QOCIDriver::record(), QSQLite2Driver::record(), QTDSDriver::record(), QMYSQLDriver::record(), QODBCDriver::record(), QDB2Driver::rollbackTransaction(), QIBaseDriver::rollbackTransaction(), QSQLiteDriver::rollbackTransaction(), QSQLite2Driver::rollbackTransaction(), QOCIDriver::rollbackTransaction(), QMYSQLDriver::rollbackTransaction(), QODBCDriver::rollbackTransaction(), QIBaseDriver::subscribeToNotificationImplementation(), QDB2Driver::tables(), QIBaseDriver::tables(), QSQLiteDriver::tables(), QOCIDriver::tables(), QSQLite2Driver::tables(), QTDSDriver::tables(), QMYSQLDriver::tables(), QODBCDriver::tables(), QIBaseDriver::unsubscribeFromNotificationImplementation(), QOCIDriver::~QOCIDriver(), and QODBCResult::~QODBCResult().
 {
     return d_func()->isOpen;
 }
isOpenError()
bool QSqlDriver::isOpenError () const
Returns true if the there was an error opening the database connection; otherwise returns false.
Definition at line 192 of file qsqldriver.cpp.
Referenced by QIBaseDriver::beginTransaction(), QSQLiteDriver::beginTransaction(), QSQLite2Driver::beginTransaction(), QIBaseDriver::commitTransaction(), QSQLiteDriver::commitTransaction(), QSQLite2Driver::commitTransaction(), qExtractSecurityPolicyFromString(), QIBaseDriver::rollbackTransaction(), QSQLiteDriver::rollbackTransaction(), and QSQLite2Driver::rollbackTransaction().
 {
     return d_func()->isOpenError;
 }
lastError()
QSqlError QSqlDriver::lastError () const
Returns a QSqlError object which contains information about the last error that occurred on the database.
Definition at line 360 of file qsqldriver.cpp.
 {
     return d_func()->error;
 }
notification
QSqlDriver::notification (const QString & name) signal
This signal is emitted when the database posts an event notification that the driver subscribes to.
Since
4.4
name identifies the event notification.
See also
subscribeToNotification()
Referenced by QPSQLDriver::_q_handleNotification(), and QIBaseDriver::qHandleEventNotification().
numericalPrecisionPolicy()
QSql::NumericalPrecisionPolicy QSqlDriver::numericalPrecisionPolicy () const
Returns the current default precision policy for the database connection.
Since
4.6
See also
QSql::NumericalPrecisionPolicy, setNumericalPrecisionPolicy(), QSqlQuery::numericalPrecisionPolicy(), QSqlQuery::setNumericalPrecisionPolicy()
Definition at line 987 of file qsqldriver.cpp.
Referenced by QSqlResult::QSqlResult().
 {
     return d_func()->precisionPolicy;
 }
open()
bool QSqlDriver::open (const QString & db, const QString & user = QString(), const QString & password = QString(), const QString & host = QString(), int port = -1, const QString & options = QString()) pure virtual
Derived classes must reimplement this pure virtual function to open a database connection on database db, using user name user, password password, host host, port port and connection options options.
The function must return true on success and false on failure.
See also
setOpen()
Implemented in QODBCDriver, QPSQLDriver, QMYSQLDriver, QDB2Driver, QSymSQLDriver, QTDSDriver, QOCIDriver, QSqlNullDriver, QSQLiteDriver, QSQLite2Driver, and QIBaseDriver.
Referenced by setOpen().
primaryIndex()
QSqlIndex QSqlDriver::primaryIndex (const QString & tableName) const virtual
Returns the primary index for table tableName.
Returns an empty QSqlIndex if the table doesn't have a primary index. The default implementation returns an empty index.
Reimplemented in QPSQLDriver, QODBCDriver, QMYSQLDriver, QSymSQLDriver, QTDSDriver, QSQLite2Driver, QOCIDriver, QSQLiteDriver, QIBaseDriver, and QDB2Driver.
Definition at line 387 of file qsqldriver.cpp.
 {
     return QSqlIndex();
 }
record()
QSqlRecord QSqlDriver::record (const QString & tableName) const virtual
Returns a QSqlRecord populated with the names of the fields in table tableName.
Use query.
If no such table exists, an empty record is returned. The default implementation returns an empty record.
record() instead.
Reimplemented in QPSQLDriver, QODBCDriver, QMYSQLDriver, QSymSQLDriver, QTDSDriver, QSQLite2Driver, QOCIDriver, QSQLiteDriver, QIBaseDriver, and QDB2Driver.
Definition at line 399 of file qsqldriver.cpp.
 {
     return QSqlRecord();
 }
rollbackTransaction()
bool QSqlDriver::rollbackTransaction () virtual
This function is called to rollback a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
beginTransaction(), commitTransaction()
Reimplemented in QODBCDriver, QPSQLDriver, QMYSQLDriver, QTDSDriver, QOCIDriver, QSymSQLDriver, QSQLite2Driver, QSQLiteDriver, QIBaseDriver, and QDB2Driver.
Definition at line 338 of file qsqldriver.cpp.
 {
     return false;
 }
setLastError()
void QSqlDriver::setLastError (const QSqlError & error) protected virtual
This function is used to set the value of the last error, error, that occurred on the database.
See also
lastError()
Reimplemented in QSqlNullDriver.
Definition at line 350 of file qsqldriver.cpp.
Referenced by QSQLiteDriver::beginTransaction(), QSQLite2Driver::beginTransaction(), QOCIDriver::beginTransaction(), QMYSQLDriver::beginTransaction(), QPSQLDriver::beginTransaction(), QODBCDriver::beginTransaction(), QSQLiteDriver::close(), QDB2Driver::commitTransaction(), QSQLiteDriver::commitTransaction(), QSQLite2Driver::commitTransaction(), QOCIDriver::commitTransaction(), QMYSQLDriver::commitTransaction(), QPSQLDriver::commitTransaction(), QODBCDriver::commitTransaction(), QODBCDriver::endTrans(), QSQLite2Driver::open(), QSQLiteDriver::open(), QOCIDriver::open(), QTDSDriver::open(), QDB2Driver::open(), QMYSQLDriver::open(), QPSQLDriver::open(), QODBCDriver::open(), QPSQLResultPrivate::processResults(), qExtractSecurityPolicyFromString(), QOCIDriver::QOCIDriver(), QSqlNullDriver::QSqlNullDriver(), QDB2Driver::rollbackTransaction(), QSQLiteDriver::rollbackTransaction(), QSQLite2Driver::rollbackTransaction(), QOCIDriver::rollbackTransaction(), QMYSQLDriver::rollbackTransaction(), QPSQLDriver::rollbackTransaction(), QODBCDriver::rollbackTransaction(), QDB2Driver::setAutoCommit(), QIBaseDriver::subscribeToNotificationImplementation(), QPSQLDriver::subscribeToNotificationImplementation(), QIBaseDriver::unsubscribeFromNotificationImplementation(), and QPSQLDriver::unsubscribeFromNotificationImplementation().
 {
     d_func()->error = error;
 }
setNumericalPrecisionPolicy()
void QSqlDriver::setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy precisionPolicy)
Sets the default numerical precision policy used by queries created by this driver to precisionPolicy.
Since
4.6
Note: Setting the default precision policy to precisionPolicy doesn't affect any currently active queries.
See also
QSql::NumericalPrecisionPolicy, numericalPrecisionPolicy(), QSqlQuery::setNumericalPrecisionPolicy(), QSqlQuery::numericalPrecisionPolicy()
Definition at line 971 of file qsqldriver.cpp.
 {
     d_func()->precisionPolicy = precisionPolicy;
 }
setOpen()
void QSqlDriver::setOpen (bool open) protected virtual
This function sets the open state of the database to open.
Derived classes can use this function to report the status of open().
See also
open(), setOpenError()
Reimplemented in QSqlNullDriver.
Definition at line 283 of file qsqldriver.cpp.
Referenced by QDB2Driver::close(), QIBaseDriver::close(), QSQLiteDriver::close(), QSQLite2Driver::close(), QOCIDriver::close(), QTDSDriver::close(), QMYSQLDriver::close(), QODBCDriver::close(), QPSQLDriver::close(), QIBaseDriver::open(), QSQLite2Driver::open(), QSQLiteDriver::open(), QOCIDriver::open(), QTDSDriver::open(), QDB2Driver::open(), QMYSQLDriver::open(), QPSQLDriver::open(), QODBCDriver::open(), QDB2Driver::QDB2Driver(), qExtractSecurityPolicyFromString(), QIBaseDriver::QIBaseDriver(), QMYSQLDriver::QMYSQLDriver(), QOCIDriver::QOCIDriver(), QODBCDriver::QODBCDriver(), QPSQLDriver::QPSQLDriver(), QSQLite2Driver::QSQLite2Driver(), QSQLiteDriver::QSQLiteDriver(), QSymSQLDriver::QSymSQLDriver(), and QTDSDriver::QTDSDriver().
 {
     d_func()->isOpen = open;
 }
setOpenError()
void QSqlDriver::setOpenError (bool error) protected virtual
This function sets the open error state of the database to error.
Derived classes can use this function to report the status of open(). Note that if error is true the open state of the database is set to closed (i.e., isOpen() returns false).
See also
open(), setOpen()
Reimplemented in QSqlNullDriver.
Definition at line 297 of file qsqldriver.cpp.
Referenced by QDB2Driver::close(), QIBaseDriver::close(), QSQLiteDriver::close(), QSQLite2Driver::close(), QOCIDriver::close(), QTDSDriver::close(), QMYSQLDriver::close(), QODBCDriver::close(), QPSQLDriver::close(), QIBaseDriver::open(), QSQLite2Driver::open(), QSQLiteDriver::open(), QOCIDriver::open(), QTDSDriver::open(), QDB2Driver::open(), QMYSQLDriver::open(), QPSQLDriver::open(), QODBCDriver::open(), QDB2Driver::QDB2Driver(), qExtractSecurityPolicyFromString(), QIBaseDriver::QIBaseDriver(), QMYSQLDriver::QMYSQLDriver(), QOCIDriver::QOCIDriver(), QODBCDriver::QODBCDriver(), QPSQLDriver::QPSQLDriver(), QSQLite2Driver::QSQLite2Driver(), QSQLiteDriver::QSQLiteDriver(), QSymSQLDriver::QSymSQLDriver(), and QTDSDriver::QTDSDriver().
 {
     d_func()->isOpenError = error;
     if (error)
         d_func()->isOpen = false;
 }
sqlStatement()
QString QSqlDriver::sqlStatement (StatementType type, const QString & tableName, const QSqlRecord & rec, bool preparedStatement) const virtual
Returns a SQL statement of type type for the table tableName with the values from rec.
If preparedStatement is true, the string will contain placeholders instead of values.
This method can be used to manipulate tables without having to worry about database-dependent SQL dialects. For non-prepared statements, the values will be properly escaped.
Definition at line 475 of file qsqldriver.cpp.
 {
     int i;
     QString s;
     s.reserve(128);
     switch (type) {
     case SelectStatement:
         for (i = 0; i < rec.count(); ++i) {
             if (rec.isGenerated(i))
                 s.append(prepareIdentifier(rec.fieldName(i), QSqlDriver::FieldName, this)).append(QLatin1String(", "));
         }
         if (s.isEmpty())
             return s;
         s.chop(2);
         s.prepend(QLatin1String("SELECT ")).append(QLatin1String(" FROM ")).append(tableName);
         break;
     case WhereStatement:
         if (preparedStatement) {
             for (int i = 0; i < rec.count(); ++i) {
                 s.append(prepareIdentifier(rec.fieldName(i), FieldName,this));
                 if (rec.isNull(i))
                     s.append(QLatin1String(" IS NULL"));
                 else
                     s.append(QLatin1String(" = ?"));
                 s.append(QLatin1String(" AND "));
             }
         } else {
             for (i = 0; i < rec.count(); ++i) {
                 s.append(prepareIdentifier(rec.fieldName(i), QSqlDriver::FieldName, this));
                 QString val = formatValue(rec.field(i));
                 if (val == QLatin1String("NULL"))
                     s.append(QLatin1String(" IS NULL"));
                 else
                     s.append(QLatin1String(" = ")).append(val);
                 s.append(QLatin1String(" AND "));
             }
         }
         if (!s.isEmpty()) {
             s.prepend(QLatin1String("WHERE "));
             s.chop(5); // remove tailing AND
         }
         break;
     case UpdateStatement:
         s.append(QLatin1String("UPDATE ")).append(tableName).append(
                  QLatin1String(" SET "));
         for (i = 0; i < rec.count(); ++i) {
             if (!rec.isGenerated(i))
                 continue;
             s.append(prepareIdentifier(rec.fieldName(i), QSqlDriver::FieldName, this)).append(QLatin1Char('='));
             if (preparedStatement)
                 s.append(QLatin1Char('?'));
             else
                 s.append(formatValue(rec.field(i)));
             s.append(QLatin1String(", "));
         }
         if (s.endsWith(QLatin1String(", ")))
             s.chop(2);
         else
             s.clear();
         break;
     case DeleteStatement:
         s.append(QLatin1String("DELETE FROM ")).append(tableName);
         break;
     case InsertStatement: {
         s.append(QLatin1String("INSERT INTO ")).append(tableName).append(QLatin1String(" ("));
         QString vals;
         for (i = 0; i < rec.count(); ++i) {
             if (!rec.isGenerated(i))
                 continue;
             s.append(prepareIdentifier(rec.fieldName(i), QSqlDriver::FieldName, this)).append(QLatin1String(", "));
             if (preparedStatement)
                 vals.append(QLatin1Char('?'));
             else
                 vals.append(formatValue(rec.field(i)));
             vals.append(QLatin1String(", "));
         }
         if (vals.isEmpty()) {
             s.clear();
         } else {
             vals.chop(2); // remove trailing comma
             s[s.length() - 2] = QLatin1Char(')');
             s.append(QLatin1String("VALUES (")).append(vals).append(QLatin1Char(')'));
         }
         break; }
     }
     return s;
 }
stripDelimiters()
QString QSqlDriver::stripDelimiters (const QString & identifier, IdentifierType type) const
Returns the identifier with the leading and trailing delimiters removed, identifier can either be a table name or field name, dependent on type.
If identifier does not have leading and trailing delimiter characters, identifier is returned without modification.
Warning
Because of binary compatibility constraints, this function is not virtual, If you want to provide your own implementation in your QSqlDriver subclass, reimplement the stripDelimitersImplementation() slot in your subclass instead. The stripDelimiters() function will dynamically detect the slot and call it.
Since
4.5
See also
isIdentifierEscaped()
Definition at line 455 of file qsqldriver.cpp.
Referenced by QSqlTableModelPrivate::nameToIndex(), QRelation::populateDictionary(), QDB2Driver::primaryIndex(), QIBaseDriver::primaryIndex(), QSQLiteDriver::primaryIndex(), QOCIDriver::primaryIndex(), QSQLite2Driver::primaryIndex(), QTDSDriver::primaryIndex(), QODBCDriver::primaryIndex(), QPSQLDriver::primaryIndex(), qExtractSecurityPolicyFromString(), QDB2Driver::record(), QIBaseDriver::record(), QSQLiteDriver::record(), QOCIDriver::record(), QSQLite2Driver::record(), QTDSDriver::record(), QMYSQLDriver::record(), QODBCDriver::record(), QPSQLDriver::record(), QDB2Driver::tables(), and QOCIDriver::tables().
 {
     QString result;
     QMetaObject::invokeMethod(const_cast<QSqlDriver*>(this),
                             "stripDelimitersImplementation", Qt::DirectConnection,
                             Q_RETURN_ARG(QString, result),
                             Q_ARG(QString, identifier),
                             Q_ARG(IdentifierType, type));
     return result;
 }
stripDelimitersImplementation
QString QSqlDriver::stripDelimitersImplementation (const QString & identifier, IdentifierType type) const protected slot
This slot returns identifier with the leading and trailing delimiters removed, identifier can either be a tablename or field name, dependent on type.
Since
4.6
If identifier does not have leading and trailing delimiter characters, identifier is returned without modification.
Because of binary compatibility constraints, the stripDelimiters() function (introduced in Qt 4.5) is not virtual. Instead, stripDelimiters() will dynamically detect and call this slot. It generally unnecessary to reimplement this slot.
See also
stripDelimiters()
Definition at line 944 of file qsqldriver.cpp.
 {
     QString ret;
     if (this->isIdentifierEscaped(identifier, type)) {
         ret = identifier.mid(1);
         ret.chop(1);
     } else {
         ret = identifier;
     }
     return ret;
 }
subscribedToNotifications()
QStringList QSqlDriver::subscribedToNotifications () const
Returns a list of the names of the event notifications that are currently subscribed to.
Warning
Because of binary compatibility constraints, this function is not virtual. If you want to provide event notification support in your own QSqlDriver subclass, reimplement the subscribedToNotificationsImplementation() slot in your subclass instead. The subscribedToNotifications() function will dynamically detect the slot and call it.
Since
4.4
See also
subscribeToNotification() unsubscribeFromNotification()
Definition at line 817 of file qsqldriver.cpp.
 {
     QStringList result;
     QMetaObject::invokeMethod(const_cast<QSqlDriver *>(this),
                   "subscribedToNotificationsImplementation", Qt::DirectConnection,
                   Q_RETURN_ARG(QStringList, result));
     return result;
 }
subscribedToNotificationsImplementation
QStringList QSqlDriver::subscribedToNotificationsImplementation () const protected slot
Returns a list of the names of the event notifications that are currently subscribed to.
Reimplement this slot to provide your own QSqlDriver subclass with event notification support; because of binary compatibility constraints, the subscribedToNotifications() function (introduced in Qt 4.4) is not virtual. Instead, subscribedToNotifications() will dynamically detect and call this slot. The default implementation simply returns an empty QStringList.
Since
4.4
See also
subscribedToNotifications()
Definition at line 894 of file qsqldriver.cpp.
 {
     return QStringList();
 }
subscribeToNotification()
bool QSqlDriver::subscribeToNotification (const QString & name)
This function is called to subscribe to event notifications from the database.
name identifies the event notification.
If successful, return true, otherwise return false.
The database must be open when this function is called. When the database is closed by calling close() all subscribed event notifications are automatically unsubscribed. Note that calling open() on an already open database may implicitly cause close() to be called, which will cause the driver to unsubscribe from all event notifications.
When an event notification identified by name is posted by the database the notification() signal is emitted.
Warning
Because of binary compatibility constraints, this function is not virtual. If you want to provide event notification support in your own QSqlDriver subclass, reimplement the subscribeToNotificationImplementation() slot in your subclass instead. The subscribeToNotification() function will dynamically detect the slot and call it.
Since
4.4
See also
unsubscribeFromNotification() subscribedToNotifications() QSqlDriver::hasFeature()
Definition at line 766 of file qsqldriver.cpp.
 {
     bool result;
     QMetaObject::invokeMethod(const_cast<QSqlDriver *>(this),
                   "subscribeToNotificationImplementation", Qt::DirectConnection,
                   Q_RETURN_ARG(bool, result),
                   Q_ARG(QString, name));
     return result;
 }
subscribeToNotificationImplementation
bool QSqlDriver::subscribeToNotificationImplementation (const QString & name) protected slot
This slot is called to subscribe to event notifications from the database.
name identifies the event notification.
If successful, return true, otherwise return false.
The database must be open when this slot is called. When the database is closed by calling close() all subscribed event notifications are automatically unsubscribed. Note that calling open() on an already open database may implicitly cause close() to be called, which will cause the driver to unsubscribe from all event notifications.
When an event notification identified by name is posted by the database the notification() signal is emitted.
Reimplement this slot to provide your own QSqlDriver subclass with event notification support; because of binary compatibility constraints, the subscribeToNotification() function (introduced in Qt 4.4) is not virtual. Instead, subscribeToNotification() will dynamically detect and call this slot. The default implementation does nothing and returns false.
Since
4.4
See also
subscribeToNotification()
Definition at line 849 of file qsqldriver.cpp.
 {
     Q_UNUSED(name);
     return false;
 }
tables()
QStringList QSqlDriver::tables (QSql::TableType tableType) const virtual
Returns a list of the names of the tables in the database.
The default implementation returns an empty list.
The tableType argument describes what types of tables should be returned. Due to binary compatibility, the string contains the value of the enum QSql::TableTypes as text. An empty string should be treated as QSql::Tables for backward compatibility.
Reimplemented in QPSQLDriver, QODBCDriver, QMYSQLDriver, QSymSQLDriver, QTDSDriver, QSQLite2Driver, QOCIDriver, QSQLiteDriver, QIBaseDriver, and QDB2Driver.
Definition at line 376 of file qsqldriver.cpp.
 {
     return QStringList();
 }
unsubscribeFromNotification()
bool QSqlDriver::unsubscribeFromNotification (const QString & name)
This function is called to unsubscribe from event notifications from the database.
name identifies the event notification.
If successful, return true, otherwise return false.
The database must be open when this function is called. All subscribed event notifications are automatically unsubscribed from when the close() function is called.
After calling this function the notification() signal will no longer be emitted when an event notification identified by name is posted by the database.
Warning
Because of binary compatibility constraints, this function is not virtual. If you want to provide event notification support in your own QSqlDriver subclass, reimplement the unsubscribeFromNotificationImplementation() slot in your subclass instead. The unsubscribeFromNotification() function will dynamically detect the slot and call it.
Since
4.4
See also
subscribeToNotification() subscribedToNotifications()
Definition at line 796 of file qsqldriver.cpp.
 {
     bool result;
     QMetaObject::invokeMethod(const_cast<QSqlDriver *>(this),
                   "unsubscribeFromNotificationImplementation", Qt::DirectConnection,
                   Q_RETURN_ARG(bool, result),
                   Q_ARG(QString, name));
     return result;
 }
unsubscribeFromNotificationImplementation
bool QSqlDriver::unsubscribeFromNotificationImplementation (const QString & name) protected slot
This slot is called to unsubscribe from event notifications from the database.
name identifies the event notification.
If successful, return true, otherwise return false.
The database must be open when this slot is called. All subscribed event notifications are automatically unsubscribed from when the close() function is called.
After calling this slot the notification() signal will no longer be emitted when an event notification identified by name is posted by the database.
Reimplement this slot to provide your own QSqlDriver subclass with event notification support; because of binary compatibility constraints, the unsubscribeFromNotification() function (introduced in Qt 4.4) is not virtual. Instead, unsubscribeFromNotification() will dynamically detect and call this slot. The default implementation does nothing and returns false.
Since
4.4
See also
unsubscribeFromNotification()
Definition at line 876 of file qsqldriver.cpp.
 {
     Q_UNUSED(name);
     return false;
 }
Friends and Related Functions
QSqlDatabase
friend class QSqlDatabase friend
Definition at line 70 of file qsqldriver.h.
The documentation for this class was generated from the following files:
/src/sql/kernel/qsqldriver.h
/src/sql/kernel/qsqldriver.cpp