Qt 4.8: QSslConfiguration Class Reference
QSslConfiguration Class Reference
The QSslConfiguration class holds the configuration and state of an SSL connection.
#include <qsslconfiguration.h>
Public Functions
QList< QSslCertificate > caCertificates () const
Returns this connection's CA certificate database.
QList< QSslCipher > ciphers () const
Returns this connection's current cryptographic cipher suite.
bool isNull () const
Returns true if this is a null QSslConfiguration object.
QSslCertificate localCertificate () const
Returns the certificate to be presented to the peer during the SSL handshake process.
bool operator!= (const QSslConfiguration &other) const
Returns true if this QSslConfiguration differs from other.
QSslConfiguration & operator= (const QSslConfiguration &other)
Copies the configuration and state of other.
bool operator== (const QSslConfiguration &other) const
Returns true if this QSslConfiguration object is equal to other.
QSslCertificate peerCertificate () const
Returns the peer's digital certificate (i.e., the immediate certificate of the host you are connected to), or a null certificate, if the peer has not assigned a certificate.
QList< QSslCertificate > peerCertificateChain () const
Returns the peer's chain of digital certificates, starting with the peer's immediate certificate and ending with the CA's certificate.
int peerVerifyDepth () const
Returns the maximum number of certificates in the peer's certificate chain to be checked during the SSL handshake phase, or 0 (the default) if no maximum depth has been set, indicating that the whole certificate chain should be checked.
QSslSocket::PeerVerifyMode peerVerifyMode () const
Returns the verify mode.
QSslKey privateKey () const
Returns the QSslKey {SSL key} assigned to this connection or a null key if none has been assigned yet.
QSsl::SslProtocol protocol () const
Returns the protocol setting for this SSL configuration.
QSslConfiguration ()
Constructs an empty SSL configuration.
QSslConfiguration (const QSslConfiguration &other)
Copies the configuration and state of other.
QSslCipher sessionCipher () const
Returns the socket's cryptographic QSslCipher {cipher}, or a null cipher if the connection isn't encrypted.
void setCaCertificates (const QList< QSslCertificate > &certificates)
Sets this socket's CA certificate database to be certificates.
void setCiphers (const QList< QSslCipher > &ciphers)
Sets the cryptographic cipher suite for this socket to ciphers, which must contain a subset of the ciphers in the list returned by supportedCiphers().
void setLocalCertificate (const QSslCertificate &certificate)
Sets the certificate to be presented to the peer during SSL handshake to be certificate.
void setPeerVerifyDepth (int depth)
Sets the maximum number of certificates in the peer's certificate chain to be checked during the SSL handshake phase, to depth.
void setPeerVerifyMode (QSslSocket::PeerVerifyMode mode)
Sets the verify mode to mode.
void setPrivateKey (const QSslKey &key)
Sets the connection's private QSslKey {key} to key.
void setProtocol (QSsl::SslProtocol protocol)
Sets the protocol setting for this configuration to be protocol.
void setSslOption (QSsl::SslOption option, bool on)
Enables or disables an SSL compatibility option.
bool testSslOption (QSsl::SslOption option) const
Returns true if the specified SSL compatibility option is enabled.
~QSslConfiguration ()
Releases any resources held by QSslConfiguration.
Static Public Functions
static QSslConfiguration defaultConfiguration ()
Returns the default SSL configuration to be used in new SSL connections.
static void setDefaultConfiguration (const QSslConfiguration &configuration)
Sets the default SSL configuration to be used in new SSL connections to be configuration.
Private Functions
QSslConfiguration (QSslConfigurationPrivate *dd)
Properties
QSharedDataPointer< QSslConfigurationPrivate > d
Friends
class QSslConfigurationPrivate
class QSslSocket
Detailed Description
The QSslConfiguration class holds the configuration and state of an SSL connection.
Since
4.4
Note
This class or function is reentrant.
Attention
Module: QtNetwork
QSslConfiguration is used by Qt networking classes to relay information about an open SSL connection and to allow the application to control certain features of that connection.
The settings that QSslConfiguration currently supports are:
The SSL/TLS protocol to be used
The certificate to be presented to the peer during connection and its associated private key
The ciphers allowed to be used for encrypting the connection
The list of Certificate Authorities certificates that are used to validate the peer's certificate
These settings are applied only during the connection handshake. Setting them after the connection has been established has no effect.
The state that QSslConfiguration supports are:
The certificate the peer presented during handshake, along with the chain leading to a CA certificate
The cipher used to encrypt this session
The state can only be obtained once the SSL connection starts, but not necessarily before it's done. Some settings may change during the course of the SSL connection without need to restart it (for instance, the cipher can be changed over time).
State in QSslConfiguration objects cannot be changed.
QSslConfiguration can be used with QSslSocket and the Network Access API.
Note that changing settings in QSslConfiguration is not enough to change the settings in the related SSL connection. You must call setSslConfiguration on a modified QSslConfiguration object to achieve that. The following example illustrates how to change the protocol to TLSv1 in a QSslSocket object:
QSslConfiguration config = sslSocket.sslConfiguration();
config.setProtocol(QSsl::TlsV1);
sslSocket.setSslConfiguration(config);
See also
QSsl::SslProtocol, QSslCertificate, QSslCipher, QSslKey QSslSocket, QNetworkAccessManager, QSslSocket::sslConfiguration(), QSslSocket::setSslConfiguration()
Definition at line 78 of file qsslconfiguration.h.
Constructors and Destructors
QSslConfiguration() [1/3]
QSslConfiguration::QSslConfiguration ()
Constructs an empty SSL configuration.
This configuration contains no valid settings and the state will be empty. isNull() will return true after this constructor is called.
Once any setter methods are called, isNull() will return false.
Definition at line 119 of file qsslconfiguration.cpp.
     : d(new QSslConfigurationPrivate)
 {
 }
QSslConfiguration() [2/3]
QSslConfiguration::QSslConfiguration (const QSslConfiguration & other)
Copies the configuration and state of other.
If other is null, this object will be null too.
Definition at line 128 of file qsslconfiguration.cpp.
     : d(other.d)
 {
 }
~QSslConfiguration()
QSslConfiguration::~QSslConfiguration ()
Releases any resources held by QSslConfiguration.
Definition at line 136 of file qsslconfiguration.cpp.
 {
     // QSharedDataPointer deletes d for us if necessary
 }
QSslConfiguration() [3/3]
QSslConfiguration::QSslConfiguration (QSslConfigurationPrivate * dd) inline private
Definition at line 115 of file qsslconfiguration_p.h.
     : d(dd)
 {
 }
Functions
caCertificates()
QList< QSslCertificate > QSslConfiguration::caCertificates () const
Returns this connection's CA certificate database.
The CA certificate database is used by the socket during the handshake phase to validate the peer's certificate. It can be modified prior to the handshake with setCaCertificates(), or with QSslSocket's QSslSocket::addCaCertificate() and QSslSocket::addCaCertificates().
See also
setCaCertificates()
Definition at line 503 of file qsslconfiguration.cpp.
Referenced by QSslSocket::setSslConfiguration().
 {
     return d->caCertificates;
 }
ciphers()
QList< QSslCipher > QSslConfiguration::ciphers () const
Returns this connection's current cryptographic cipher suite.
This list is used during the handshake phase for choosing a session cipher. The returned list of ciphers is ordered by descending preference. (i.e., the first cipher in the list is the most preferred cipher). The session cipher will be the first one in the list that is also supported by the peer.
By default, the handshake phase can choose any of the ciphers supported by this system's SSL libraries, which may vary from system to system. The list of ciphers supported by this system's SSL libraries is returned by QSslSocket::supportedCiphers(). You can restrict the list of ciphers used for choosing the session cipher for this socket by calling setCiphers() with a subset of the supported ciphers. You can revert to using the entire set by calling setCiphers() with the list returned by QSslSocket::supportedCiphers().
See also
setCiphers(), QSslSocket::supportedCiphers()
Definition at line 473 of file qsslconfiguration.cpp.
Referenced by setCiphers(), and QSslSocket::setSslConfiguration().
 {
     return d->ciphers;
 }
defaultConfiguration()
QSslConfiguration QSslConfiguration::defaultConfiguration () static
Returns the default SSL configuration to be used in new SSL connections.
The default SSL configuration consists of:
no local certificate and no private key
protocol SecureProtocols (meaning either TLS 1.0 or SSL 3 will be used)
the system's default CA certificate list
the cipher list equal to the list of the SSL libraries' supported SSL ciphers
See also
QSslSocket::supportedCiphers(), setDefaultConfiguration()
Definition at line 566 of file qsslconfiguration.cpp.
Referenced by QNetworkRequest::sslConfiguration(), and QHttpThreadDelegate::startRequest().
 {
     return QSslConfigurationPrivate::defaultConfiguration();
 }
isNull()
bool QSslConfiguration::isNull () const
Returns true if this is a null QSslConfiguration object.
A QSslConfiguration object is null if it has been default-constructed and no setter methods have been called.
See also
setProtocol(), setLocalCertificate(), setPrivateKey(), setCiphers(), setCaCertificates()
Definition at line 200 of file qsslconfiguration.cpp.
Referenced by QNetworkAccessHttpBackend::replySslConfigurationChanged(), QNetworkReply::setSslConfiguration(), and QNetworkReplyImpl::setSslConfigurationImplementation().
 {
     return (d->protocol == QSsl::SecureProtocols &&
             d->peerVerifyMode == QSslSocket::AutoVerifyPeer &&
             d->peerVerifyDepth == 0 &&
             d->allowRootCertOnDemandLoading == true &&
             d->caCertificates.count() == 0 &&
             d->ciphers.count() == 0 &&
             d->localCertificate.isNull() &&
             d->privateKey.isNull() &&
             d->peerCertificate.isNull() &&
             d->peerCertificateChain.count() == 0 &&
             d->sslOptions == ( QSsl::SslOptionDisableEmptyFragments
                               |QSsl::SslOptionDisableLegacyRenegotiation
                               |QSsl::SslOptionDisableCompression));
 }
localCertificate()
QSslCertificate QSslConfiguration::localCertificate () const
Returns the certificate to be presented to the peer during the SSL handshake process.
See also
setLocalCertificate()
Definition at line 316 of file qsslconfiguration.cpp.
Referenced by QSslSocket::setSslConfiguration().
 {
     return d->localCertificate;
 }
operator!=()
QSslConfiguration::operator!= (const QSslConfiguration & other) const inline
Returns true if this QSslConfiguration differs from other.
Two QSslConfiguration objects are considered different if any state or setting is different.
See also
operator==()
Definition at line 87 of file qsslconfiguration.h.
     { return !(*this == other); }
operator=()
QSslConfiguration & QSslConfiguration::operator= (const QSslConfiguration & other)
Copies the configuration and state of other.
If other is null, this object will be null too.
Definition at line 145 of file qsslconfiguration.cpp.
 {
     d = other.d;
     return *this;
 }
operator==()
bool QSslConfiguration::operator== (const QSslConfiguration & other) const
Returns true if this QSslConfiguration object is equal to other.
Two QSslConfiguration objects are considered equal if they have the exact same settings and state.
See also
operator!=()
Definition at line 160 of file qsslconfiguration.cpp.
 {
     if (d == other.d)
         return true;
     return d->peerCertificate == other.d->peerCertificate &&
         d->peerCertificateChain == other.d->peerCertificateChain &&
         d->localCertificate == other.d->localCertificate &&
         d->privateKey == other.d->privateKey &&
         d->sessionCipher == other.d->sessionCipher &&
         d->ciphers == other.d->ciphers &&
         d->caCertificates == other.d->caCertificates &&
         d->protocol == other.d->protocol &&
         d->peerVerifyMode == other.d->peerVerifyMode &&
         d->peerVerifyDepth == other.d->peerVerifyDepth &&
         d->allowRootCertOnDemandLoading == other.d->allowRootCertOnDemandLoading &&
         d->sslOptions == other.d->sslOptions;
 }
peerCertificate()
QSslCertificate QSslConfiguration::peerCertificate () const
Returns the peer's digital certificate (i.e., the immediate certificate of the host you are connected to), or a null certificate, if the peer has not assigned a certificate.
The peer certificate is checked automatically during the handshake phase, so this function is normally used to fetch the certificate for display or for connection diagnostic purposes. It contains information about the peer, including its host name, the certificate issuer, and the peer's public key.
Because the peer certificate is set during the handshake phase, it is safe to access the peer certificate from a slot connected to the QSslSocket::sslErrors() signal, QNetworkReply::sslErrors() signal, or the QSslSocket::encrypted() signal.
If a null certificate is returned, it can mean the SSL handshake failed, or it can mean the host you are connected to doesn't have a certificate, or it can mean there is no connection.
If you want to check the peer's complete chain of certificates, use peerCertificateChain() to get them all at once.
See also
peerCertificateChain(), QSslSocket::sslErrors(), QSslSocket::ignoreSslErrors(), QNetworkReply::sslErrors(), QNetworkReply::ignoreSslErrors()
Definition at line 370 of file qsslconfiguration.cpp.
 {
     return d->peerCertificate;
 }
peerCertificateChain()
QList< QSslCertificate > QSslConfiguration::peerCertificateChain () const
Returns the peer's chain of digital certificates, starting with the peer's immediate certificate and ending with the CA's certificate.
Peer certificates are checked automatically during the handshake phase. This function is normally used to fetch certificates for display, or for performing connection diagnostics. Certificates contain information about the peer and the certificate issuers, including host name, issuer names, and issuer public keys.
Because the peer certificate is set during the handshake phase, it is safe to access the peer certificate from a slot connected to the QSslSocket::sslErrors() signal, QNetworkReply::sslErrors() signal, or the QSslSocket::encrypted() signal.
If an empty list is returned, it can mean the SSL handshake failed, or it can mean the host you are connected to doesn't have a certificate, or it can mean there is no connection.
If you want to get only the peer's immediate certificate, use peerCertificate().
See also
peerCertificate(), QSslSocket::sslErrors(), QSslSocket::ignoreSslErrors(), QNetworkReply::sslErrors(), QNetworkReply::ignoreSslErrors()
Definition at line 402 of file qsslconfiguration.cpp.
 {
     return d->peerCertificateChain;
 }
peerVerifyDepth()
int QSslConfiguration::peerVerifyDepth () const
Returns the maximum number of certificates in the peer's certificate chain to be checked during the SSL handshake phase, or 0 (the default) if no maximum depth has been set, indicating that the whole certificate chain should be checked.
The certificates are checked in issuing order, starting with the peer's own certificate, then its issuer's certificate, and so on.
See also
setPeerVerifyDepth(), peerVerifyMode()
Definition at line 285 of file qsslconfiguration.cpp.
Referenced by QSslSocket::setSslConfiguration().
 {
     return d->peerVerifyDepth;
 }
peerVerifyMode()
QSslSocket::PeerVerifyMode QSslConfiguration::peerVerifyMode () const
Returns the verify mode.
This mode decides whether QSslSocket should request a certificate from the peer (i.e., the client requests a certificate from the server, or a server requesting a certificate from the client), and whether it should require that this certificate is valid.
The default mode is AutoVerifyPeer, which tells QSslSocket to use VerifyPeer for clients, QueryPeer for servers.
See also
setPeerVerifyMode()
Definition at line 252 of file qsslconfiguration.cpp.
Referenced by QSslSocket::setSslConfiguration().
 {
     return d->peerVerifyMode;
 }
privateKey()
QSslKey QSslConfiguration::privateKey () const
Returns the QSslKey {SSL key} assigned to this connection or a null key if none has been assigned yet.
See also
setPrivateKey(), localCertificate()
Definition at line 431 of file qsslconfiguration.cpp.
Referenced by QSslSocket::setSslConfiguration().
 {
     return d->privateKey;
 }
protocol()
QSsl::SslProtocol QSslConfiguration::protocol () const
Returns the protocol setting for this SSL configuration.
See also
setProtocol()
Definition at line 222 of file qsslconfiguration.cpp.
Referenced by setProtocol(), and QSslSocket::setSslConfiguration().
 {
     return d->protocol;
 }
sessionCipher()
QSslCipher QSslConfiguration::sessionCipher () const
Returns the socket's cryptographic QSslCipher {cipher}, or a null cipher if the connection isn't encrypted.
The socket's cipher for the session is set during the handshake phase. The cipher is used to encrypt and decrypt data transmitted through the socket.
The SSL infrastructure also provides functions for setting the ordered list of ciphers from which the handshake phase will eventually select the session cipher. This ordered list must be in place before the handshake phase begins.
See also
ciphers(), setCiphers(), QSslSocket::supportedCiphers()
Definition at line 420 of file qsslconfiguration.cpp.
 {
     return d->sessionCipher;
 }
setCaCertificates()
void QSslConfiguration::setCaCertificates (const QList< QSslCertificate > & certificates)
Sets this socket's CA certificate database to be certificates.
The certificate database must be set prior to the SSL handshake. The CA certificate database is used by the socket during the handshake phase to validate the peer's certificate.
See also
caCertificates()
Definition at line 516 of file qsslconfiguration.cpp.
 {
     d->caCertificates = certificates;
     d->allowRootCertOnDemandLoading = false;
 }
setCiphers()
void QSslConfiguration::setCiphers (const QList< QSslCipher > & ciphers)
Sets the cryptographic cipher suite for this socket to ciphers, which must contain a subset of the ciphers in the list returned by supportedCiphers().
Restricting the cipher suite must be done before the handshake phase, where the session cipher is chosen.
See also
ciphers(), QSslSocket::supportedCiphers()
Definition at line 488 of file qsslconfiguration.cpp.
 {
     d->ciphers = ciphers;
 }
setDefaultConfiguration()
void QSslConfiguration::setDefaultConfiguration (const QSslConfiguration & configuration) static
Sets the default SSL configuration to be used in new SSL connections to be configuration.
Existing connections are not affected by this call.
See also
QSslSocket::supportedCiphers(), defaultConfiguration()
Definition at line 578 of file qsslconfiguration.cpp.
 {
     QSslConfigurationPrivate::setDefaultConfiguration(configuration);
 }
setLocalCertificate()
void QSslConfiguration::setLocalCertificate (const QSslCertificate & certificate)
Sets the certificate to be presented to the peer during SSL handshake to be certificate.
Setting the certificate once the connection has been established has no effect.
A certificate is the means of identification used in the SSL process. The local certificate is used by the remote end to verify the local user's identity against its list of Certification Authorities. In most cases, such as in HTTP web browsing, only servers identify to the clients, so the client does not send a certificate.
See also
localCertificate()
Definition at line 337 of file qsslconfiguration.cpp.
 {
     d->localCertificate = certificate;
 }
setPeerVerifyDepth()
void QSslConfiguration::setPeerVerifyDepth (int depth)
Sets the maximum number of certificates in the peer's certificate chain to be checked during the SSL handshake phase, to depth.
Setting a depth of 0 means that no maximum depth is set, indicating that the whole certificate chain should be checked.
The certificates are checked in issuing order, starting with the peer's own certificate, then its issuer's certificate, and so on.
See also
peerVerifyDepth(), setPeerVerifyMode()
Definition at line 301 of file qsslconfiguration.cpp.
 {
     if (depth < 0) {
         qWarning("QSslConfiguration::setPeerVerifyDepth: cannot set negative depth of %d", depth);
         return;
     }
     d->peerVerifyDepth = depth;
 }
setPeerVerifyMode()
void QSslConfiguration::setPeerVerifyMode (QSslSocket::PeerVerifyMode mode)
Sets the verify mode to mode.
This mode decides whether QSslSocket should request a certificate from the peer (i.e., the client requests a certificate from the server, or a server requesting a certificate from the client), and whether it should require that this certificate is valid.
The default mode is AutoVerifyPeer, which tells QSslSocket to use VerifyPeer for clients, QueryPeer for servers.
See also
peerVerifyMode()
Definition at line 268 of file qsslconfiguration.cpp.
 {
     d->peerVerifyMode = mode;
 }
setPrivateKey()
void QSslConfiguration::setPrivateKey (const QSslKey & key)
Sets the connection's private QSslKey {key} to key.
The private key and the local QSslCertificate {certificate} are used by clients and servers that must prove their identity to SSL peers.
Both the key and the local certificate are required if you are creating an SSL server socket. If you are creating an SSL client socket, the key and local certificate are required if your client must identify itself to an SSL server.
See also
privateKey(), setLocalCertificate()
Definition at line 449 of file qsslconfiguration.cpp.
 {
     d->privateKey = key;
 }
setProtocol()
void QSslConfiguration::setProtocol (QSsl::SslProtocol protocol)
Sets the protocol setting for this configuration to be protocol.
Setting the protocol once the connection has already been established has no effect.
See also
protocol()
Definition at line 236 of file qsslconfiguration.cpp.
 {
     d->protocol = protocol;
 }
setSslOption()
void QSslConfiguration::setSslOption (QSsl::SslOption option, bool on)
Enables or disables an SSL compatibility option.
See also
testSSlOption()
Definition at line 527 of file qsslconfiguration.cpp.
 {
     if (on)
         d->sslOptions |= option;
     else
         d->sslOptions &= ~option;
 }
testSslOption()
bool QSslConfiguration::testSslOption (QSsl::SslOption option) const
Returns true if the specified SSL compatibility option is enabled.
Since
4.8
See also
testSSlOption()
Definition at line 545 of file qsslconfiguration.cpp.
 {
     return d->sslOptions & option;
 }
Friends and Related Functions
QSslConfigurationPrivate
friend class QSslConfigurationPrivate friend
Definition at line 130 of file qsslconfiguration.h.
QSslSocket
friend class QSslSocket friend
Definition at line 129 of file qsslconfiguration.h.
Properties
d
QSharedDataPointer<QSslConfigurationPrivate> QSslConfiguration::d private
Definition at line 132 of file qsslconfiguration.h.
Referenced by caCertificates(), ciphers(), isNull(), localCertificate(), operator=(), operator==(), peerCertificate(), peerCertificateChain(), peerVerifyDepth(), peerVerifyMode(), privateKey(), protocol(), sessionCipher(), setCaCertificates(), setCiphers(), QSslConfigurationPrivate::setDefaultConfiguration(), setLocalCertificate(), setPeerVerifyDepth(), setPeerVerifyMode(), setPrivateKey(), setProtocol(), QSslSocket::setSslConfiguration(), setSslOption(), and testSslOption().
The documentation for this class was generated from the following files:
/src/network/ssl/qsslconfiguration.h
/src/network/ssl/qsslconfiguration.cpp
/src/network/ssl/qsslconfiguration_p.h