Qt 4.8: QPatternist::FunctionFactoryCollection Class Reference
QPatternist::FunctionFactoryCollection Class Reference
A FunctionFactoryCollection instance is a FunctionFactory in its own right, but looks in its contained collection of factories for requested functions.
#include <qfunctionfactorycollection_p.h>
Public Types
typedef QExplicitlySharedDataPointer< FunctionFactoryCollection > Ptr
Public Types inherited from QPatternist::FunctionFactory
typedef QList< FunctionFactory::Ptr > List
typedef QExplicitlySharedDataPointer< FunctionFactory > Ptr
Public Types inherited from QList< T >
typedef const value_type * const_pointer
Typedef for const T *.
typedef const value_type & const_reference
Typedef for const T &.
typedef const_iterator ConstIterator
Qt-style synonym for QList::const_iterator.
typedef qptrdiff difference_type
Typedef for ptrdiff_t.
typedef iterator Iterator
Qt-style synonym for QList::iterator.
typedef value_type * pointer
Typedef for T *.
typedef value_type & reference
Typedef for T &.
typedef int size_type
Typedef for int.
typedef T value_type
Typedef for T.
Public Functions
virtual Expression::Ptr createFunctionCall (const QXmlName, const Expression::List &arguments, const StaticContext::Ptr &context, const SourceLocationReflection *const r)
virtual FunctionSignature::Hash functionSignatures () const
virtual bool isAvailable (const NamePool::Ptr &np, const QXmlName name, const xsInteger arity)
virtual FunctionSignature::Ptr retrieveFunctionSignature (const NamePool::Ptr &np, const QXmlName name)
Public Functions inherited from QPatternist::FunctionFactory
bool hasSignature (const FunctionSignature::Ptr &signature) const
virtual ~FunctionFactory ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QList< T >
void append (const T &t)
Inserts value at the end of the list.
void append (const QList< T > &t)
Appends the items of the value list to this list.
const T & at (int i) const
Returns the item at index position i in the list.
T & back ()
This function is provided for STL compatibility.
const T & back () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator begin ()
Returns an STL-style iterator pointing to the first item in the list.
const_iterator begin () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void clear ()
Removes all items from the list.
const_iterator constBegin () const
Returns a const STL-style iterator pointing to the first item in the list.
const_iterator constEnd () const
Returns a const STL-style iterator pointing to the imaginary item after the last item in the list.
QBool contains (const T &t) const
Returns true if the list contains an occurrence of value; otherwise returns false.
int count (const T &t) const
Returns the number of occurrences of value in the list.
int count () const
Returns the number of items in the list.
void detach ()
void detachShared ()
This prevents needless mallocs, and makes QList more exception safe in case of cleanup work done in destructors on empty lists.
bool empty () const
This function is provided for STL compatibility.
iterator end ()
Returns an STL-style iterator pointing to the imaginary item after the last item in the list.
const_iterator end () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool endsWith (const T &t) const
Returns true if this list is not empty and its last item is equal to value; otherwise returns false.
iterator erase (iterator pos)
Removes the item associated with the iterator pos from the list, and returns an iterator to the next item in the list (which may be end()).
iterator erase (iterator first, iterator last)
Removes all the items from begin up to (but not including) end.
T & first ()
Returns a reference to the first item in the list.
const T & first () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
T & front ()
This function is provided for STL compatibility.
const T & front () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int indexOf (const T &t, int from=0) const
Returns the index position of the first occurrence of value in the list, searching forward from index position from.
void insert (int i, const T &t)
Inserts value at index position i in the list.
iterator insert (iterator before, const T &t)
Inserts value in front of the item pointed to by the iterator before.
bool isDetached () const
bool isEmpty () const
Returns true if the list contains no items; otherwise returns false.
bool isSharedWith (const QList< T > &other) const
T & last ()
Returns a reference to the last item in the list.
const T & last () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int lastIndexOf (const T &t, int from=-1) const
Returns the index position of the last occurrence of value in the list, searching backward from index position from.
int length () const
This function is identical to count().
QList< T > mid (int pos, int length=-1) const
Returns a list whose elements are copied from this list, starting at position pos.
void move (int from, int to)
Moves the item at index position from to index position to.
bool operator!= (const QList< T > &l) const
Returns true if other is not equal to this list; otherwise returns false.
QList< T > operator+ (const QList< T > &l) const
Returns a list that contains all the items in this list followed by all the items in the other list.
QList< T > & operator+= (const QList< T > &l)
Appends the items of the other list to this list and returns a reference to this list.
QList< T > & operator+= (const T &t)
Appends value to the list.
QList< T > & operator<< (const QList< T > &l)
Appends the items of the other list to this list and returns a reference to this list.
QList< T > & operator<< (const T &t)
Appends value to the list.
QList< T > & operator= (const QList< T > &l)
Assigns other to this list and returns a reference to this list.
bool operator== (const QList< T > &l) const
Returns true if other is equal to this list; otherwise returns false.
const T & operator[] (int i) const
Same as at().
T & operator[] (int i)
Returns the item at index position i as a modifiable reference.
void pop_back ()
This function is provided for STL compatibility.
void pop_front ()
This function is provided for STL compatibility.
void prepend (const T &t)
Inserts value at the beginning of the list.
void push_back (const T &t)
This function is provided for STL compatibility.
void push_front (const T &t)
This function is provided for STL compatibility.
QList ()
Constructs an empty list.
QList (const QList< T > &l)
Constructs a copy of other.
int removeAll (const T &t)
Removes all occurrences of value in the list and returns the number of entries removed.
void removeAt (int i)
Removes the item at index position i.
void removeFirst ()
Removes the first item in the list.
void removeLast ()
Removes the last item in the list.
bool removeOne (const T &t)
Removes the first occurrence of value in the list and returns true on success; otherwise returns false.
void replace (int i, const T &t)
Replaces the item at index position i with value.
void reserve (int size)
Reserve space for alloc elements.
void setSharable (bool sharable)
int size () const
Returns the number of items in the list.
bool startsWith (const T &t) const
Returns true if this list is not empty and its first item is equal to value; otherwise returns false.
void swap (QList< T > &other)
Swaps list other with this list.
void swap (int i, int j)
Exchange the item at index position i with the item at index position j.
T takeAt (int i)
Removes the item at index position i and returns it.
T takeFirst ()
Removes the first item in the list and returns it.
T takeLast ()
Removes the last item in the list and returns it.
QSet< T > toSet () const
Returns a QSet object with the data contained in this QList.
std::list< T > toStdList () const
Returns a std::list object with the data contained in this QList.
QVector< T > toVector () const
Returns a QVector object with the data contained in this QList.
T value (int i) const
Returns the value at index position i in the list.
T value (int i, const T &defaultValue) const
If the index i is out of bounds, the function returns defaultValue.
~QList ()
Destroys the list.
Static Public Functions
static FunctionFactory::Ptr xpath10Factory ()
static FunctionFactory::Ptr xpath20Factory (const NamePool::Ptr &np)
static FunctionFactory::Ptr xslt20Factory (const NamePool::Ptr &np)
Static Public Functions inherited from QList< T >
static QList< T > fromSet (const QSet< T > &set)
Returns a QList object with the data contained in set.
static QList< T > fromStdList (const std::list< T > &list)
Returns a QList object with the data contained in list.
static QList< T > fromVector (const QVector< T > &vector)
Returns a QList object with the data contained in vector.
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::FunctionFactory
FunctionFactory ()
This constructor cannot be removed, because it can't be synthesized, for some reason.
Related Functions inherited from QList< T >
QDataStream & operator<< (QDataStream &out, const QList< T > &list)
Writes the list list to stream out.
QDataStream & operator>> (QDataStream &in, QList< T > &list)
Reads a list from stream in into list.
Detailed Description
A FunctionFactoryCollection instance is a FunctionFactory in its own right, but looks in its contained collection of factories for requested functions.
Note
the order of adding function libraries is significant.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 73 of file qfunctionfactorycollection_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<FunctionFactoryCollection> QPatternist::FunctionFactoryCollection::Ptr
Definition at line 78 of file qfunctionfactorycollection_p.h.
Functions
createFunctionCall()
Expression::Ptr FunctionFactoryCollection::createFunctionCall (const QXmlName name, const Expression::List & arguments, const StaticContext::Ptr & context, const SourceLocationReflection *const r) virtual
Creates a function call node.
Implements QPatternist::FunctionFactory.
Definition at line 55 of file qfunctionfactorycollection.cpp.
 {
     const_iterator it;
     const_iterator e(constEnd());
     Expression::Ptr function;
     for(it = constBegin(); it != e; ++it)
     {
         function = (*it)->createFunctionCall(name, arguments, context, r);
         if(function)
             break;
     }
     return function;
 }
functionSignatures()
FunctionSignature::Hash FunctionFactoryCollection::functionSignatures () const virtual
Implements QPatternist::FunctionFactory.
Definition at line 87 of file qfunctionfactorycollection.cpp.
Referenced by retrieveFunctionSignature().
 {
     /* We simply grab the function signatures for each library, and
      * put them all in one list. */
     const const_iterator e(constEnd());
     FunctionSignature::Hash result;
     for(const_iterator it(constBegin()); it != e; ++it)
     {
         const FunctionSignature::Hash::const_iterator e2((*it)->functionSignatures().constEnd());
         FunctionSignature::Hash::const_iterator sit((*it)->functionSignatures().constBegin());
         for(; sit != e2; ++sit)
             result.insert(sit.key(), sit.value());
     }
     return result;
 }
isAvailable()
bool FunctionFactoryCollection::isAvailable (const NamePool::Ptr & np, const QXmlName name, const xsInteger arity) virtual
Determines whether a function with the name name and arity arity is available. The implementation operates on the result of retrieveFunctionSignature() to determine the result.
Parameters
np the NamePool.
name the name of the function. For example fn:string-join.
arity the number of arguments the function must have.
Reimplemented from QPatternist::FunctionFactory.
Definition at line 75 of file qfunctionfactorycollection.cpp.
 {
     const_iterator it;
     const_iterator e(constEnd());
     for(it = constBegin(); it != e; ++it)
         if((*it)->isAvailable(np, name, arity))
             return true;
     return false;
 }
retrieveFunctionSignature()
FunctionSignature::Ptr FunctionFactoryCollection::retrieveFunctionSignature (const NamePool::Ptr & np, const QXmlName name) virtual
This is a convenience function for sub-classes. It retrieves the function signature for function with name name.
According to the specifications are function signatures identified by their name and arity, but currently is the arity not part of the signature.
If no function could be found for the given name, null is returned.
Implements QPatternist::FunctionFactory.
Definition at line 107 of file qfunctionfactorycollection.cpp.
 {
     return functionSignatures().value(name);
 }
xpath10Factory()
FunctionFactory::Ptr FunctionFactoryCollection::xpath10Factory () static
Returns
a FunctionFactory containing all core functions required for XPath 1.0.
Definition at line 112 of file qfunctionfactorycollection.cpp.
Referenced by xpath20Factory().
 {
     /* We don't use a global static for caching this, because AbstractFunctionFactory
      * stores state specific to the NamePool, when being used. */
     return  FunctionFactory::Ptr(new XPath10CoreFunctions());
 }
xpath20Factory()
FunctionFactory::Ptr FunctionFactoryCollection::xpath20Factory (const NamePool::Ptr & np) static
Returns
a FunctionFactory containing all core functions and constructor functions required for XPath 2.. The functions specified for XQuery 1.0 are the same as for XPath 2.0 so this FunctionFactory work for XQuery as well.
Definition at line 119 of file qfunctionfactorycollection.cpp.
Referenced by QXmlQueryPrivate::staticContext(), and xslt20Factory().
 {
     /* We don't use a global static for caching this, because AbstractFunctionFactory
      * stores state specific to the NamePool, when being used. */
     const FunctionFactoryCollection::Ptr fact(new FunctionFactoryCollection());
     fact->append(xpath10Factory());
     fact->append(FunctionFactory::Ptr(new XPath20CoreFunctions()));
     fact->append(FunctionFactory::Ptr(
                             new ConstructorFunctionsFactory(np, BasicTypesFactory::self(np))));
     return fact;
 }
xslt20Factory()
FunctionFactory::Ptr FunctionFactoryCollection::xslt20Factory (const NamePool::Ptr & np) static
Returns
a FunctionFactory containing all core functions required for XSL-T 2.0 functions.
Definition at line 131 of file qfunctionfactorycollection.cpp.
Referenced by QXmlQueryPrivate::staticContext().
 {
     const FunctionFactory::Ptr retval(xpath20Factory(np));
     static_cast<FunctionFactoryCollection *>(retval.data())->append(FunctionFactory::Ptr(new XSLT20CoreFunctions()));
     return retval;
 }
The documentation for this class was generated from the following files:
/src/xmlpatterns/functions/qfunctionfactorycollection_p.h
/src/xmlpatterns/functions/qfunctionfactorycollection.cpp