Qt 4.8: QWidgetResizeHandler Class Reference
QWidgetResizeHandler Class Reference
#include <qwidgetresizehandler_p.h>
Public Types
enum Action { Move = 0x01, Resize = 0x02, Any = Move|Resize }
Signals
void activate ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void doMove ()
void doResize ()
bool isActive () const
bool isActive (Action ac) const
bool isButtonDown () const
bool isMovingEnabled () const
QWidgetResizeHandler (QWidget *parent, QWidget *cw=0)
void setActive (bool b)
void setActive (Action ac, bool b)
void setExtraHeight (int h)
void setFrameWidth (int w)
void setMovingEnabled (bool b)
void setSizeProtection (bool b)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool eventFilter (QObject *o, QEvent *e)
Filters events if this object has been installed as an event filter for the watched object.
void keyPressEvent (QKeyEvent *e)
void mouseMoveEvent (QMouseEvent *e)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Types
enum MousePosition {
Nowhere, TopLeft, BottomRight, BottomLeft,
TopRight, Top, Bottom, Left,
Right, Center
}
Private Functions
bool isMove () const
bool isResize () const
void setMouseCursor (MousePosition m)
Properties
uint activeForMove:1
uint activeForResize:1
uint buttonDown:1
QWidget * childWidget
int extrahei
int fw
QPoint invertedMoveOffset
MousePosition mode
QPoint moveOffset
uint moveResizeMode:1
uint movingEnabled:1
int range
uint sizeprotect:1
QWidget * widget
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 66 of file qwidgetresizehandler_p.h.
Enumerations
Action
enum QWidgetResizeHandler::Action
Enumerator
Move
Resize
Any
Definition at line 71 of file qwidgetresizehandler_p.h.
                 {
         Move        = 0x01,
         Resize        = 0x02,
         Any        = Move|Resize
     };
MousePosition
enum QWidgetResizeHandler::MousePosition private
Enumerator
Nowhere
TopLeft
BottomRight
BottomLeft
TopRight
Top
Bottom
Left
Right
Center
Definition at line 106 of file qwidgetresizehandler_p.h.
{
         Nowhere,
         TopLeft, BottomRight, BottomLeft, TopRight,
         Top, Bottom, Left, Right,
         Center
     };
Constructors and Destructors
QWidgetResizeHandler()
QWidgetResizeHandler::QWidgetResizeHandler (QWidget * parent, QWidget * cw = 0) explicit
Definition at line 64 of file qwidgetresizehandler.cpp.
     : QObject(parent), widget(parent), childWidget(cw ? cw : parent),
       fw(0), extrahei(0), buttonDown(false), moveResizeMode(false), sizeprotect(true), movingEnabled(true)
 {
     mode = Nowhere;
     widget->setMouseTracking(true);
     QFrame *frame = qobject_cast<QFrame*>(widget);
     range = frame ? frame->frameWidth() : RANGE;
     range = qMax(RANGE, range);
     activeForMove = activeForResize = true;
     widget->installEventFilter(this);
 }
Functions
activate
void QWidgetResizeHandler::activate () signal
Referenced by eventFilter().
doMove()
void QWidgetResizeHandler::doMove ()
Definition at line 528 of file qwidgetresizehandler.cpp.
Referenced by QWorkspaceChild::doMove().
 {
     if (!activeForMove)
         return;
     mode = Center;
     moveResizeMode = true;
     moveOffset = widget->mapFromGlobal(QCursor::pos());
     invertedMoveOffset = widget->rect().bottomRight() - moveOffset;
 #ifndef QT_NO_CURSOR
     widget->grabMouse(Qt::SizeAllCursor);
 #else
     widget->grabMouse();
 #endif
     widget->grabKeyboard();
 }
doResize()
void QWidgetResizeHandler::doResize ()
Definition at line 498 of file qwidgetresizehandler.cpp.
Referenced by QWorkspaceChild::doResize().
 {
     if (!activeForResize)
         return;
     moveResizeMode = true;
     moveOffset = widget->mapFromGlobal(QCursor::pos());
     if (moveOffset.x() < widget->width()/2) {
         if (moveOffset.y() < widget->height()/2)
             mode = TopLeft;
         else
             mode = BottomLeft;
     } else {
         if (moveOffset.y() < widget->height()/2)
             mode = TopRight;
         else
             mode = BottomRight;
     }
     invertedMoveOffset = widget->rect().bottomRight() - moveOffset;
 #ifndef QT_NO_CURSOR
     setMouseCursor(mode);
     widget->grabMouse(widget->cursor() );
 #else
     widget->grabMouse();
 #endif
     widget->grabKeyboard();
     resizeHorizontalDirectionFixed = false;
     resizeVerticalDirectionFixed = false;
 }
eventFilter()
bool QWidgetResizeHandler::eventFilter (QObject * , QEvent *) protected virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QObject.
Definition at line 97 of file qwidgetresizehandler.cpp.
 {
     if (!isActive()
         || (ee->type() != QEvent::MouseButtonPress
             && ee->type() != QEvent::MouseButtonRelease
             && ee->type() != QEvent::MouseMove
             && ee->type() != QEvent::KeyPress
             && ee->type() != QEvent::ShortcutOverride)
         )
         return false;
     Q_ASSERT(o == widget);
     QWidget *w = widget;
     if (QApplication::activePopupWidget()) {
         if (buttonDown && ee->type() == QEvent::MouseButtonRelease)
             buttonDown = false;
         return false;
     }
     QMouseEvent *e = (QMouseEvent*)ee;
     switch (e->type()) {
     case QEvent::MouseButtonPress: {
         if (w->isMaximized())
             break;
         if (!widget->rect().contains(widget->mapFromGlobal(e->globalPos())))
             return false;
         if (e->button() == Qt::LeftButton) {
 #if defined(Q_WS_X11)
             /*
                Implicit grabs do not stop the X server from changing
                the cursor in children, which looks *really* bad when
                doing resizingk, so we grab the cursor. Note that we do
                not do this on Windows since double clicks are lost due
                to the grab (see change 198463).
             */
             if (e->spontaneous())
 #  if !defined(QT_NO_CURSOR)
                 widget->grabMouse(widget->cursor());
 #  else
                 widget->grabMouse();
 #  endif // QT_NO_CURSOR
 #endif // Q_WS_X11
             buttonDown = false;
             emit activate();
             bool me = movingEnabled;
             movingEnabled = (me && o == widget);
             mouseMoveEvent(e);
             movingEnabled = me;
             buttonDown = true;
             moveOffset = widget->mapFromGlobal(e->globalPos());
             invertedMoveOffset = widget->rect().bottomRight() - moveOffset;
             if (mode == Center) {
                 if (movingEnabled)
                     return true;
             } else {
                 return true;
             }
         }
     } break;
     case QEvent::MouseButtonRelease:
         if (w->isMaximized())
             break;
         if (e->button() == Qt::LeftButton) {
             moveResizeMode = false;
             buttonDown = false;
             widget->releaseMouse();
             widget->releaseKeyboard();
             if (mode == Center) {
                 if (movingEnabled)
                     return true;
             } else {
                 return true;
             }
         }
         break;
     case QEvent::MouseMove: {
         if (w->isMaximized())
             break;
         buttonDown = buttonDown && (e->buttons() & Qt::LeftButton); // safety, state machine broken!
         bool me = movingEnabled;
         movingEnabled = (me && o == widget && (buttonDown || moveResizeMode));
         mouseMoveEvent(e);
         movingEnabled = me;
         if (mode == Center) {
             if (movingEnabled)
                 return true;
         } else {
             return true;
         }
     } break;
     case QEvent::KeyPress:
         keyPressEvent((QKeyEvent*)e);
         break;
     case QEvent::ShortcutOverride:
         if (buttonDown) {
             ((QKeyEvent*)ee)->accept();
             return true;
         }
         break;
     default:
         break;
     }
     return false;
 }
isActive() [1/2]
bool QWidgetResizeHandler::isActive () const inline
Definition at line 80 of file qwidgetresizehandler_p.h.
Referenced by eventFilter(), isActive(), mouseMoveEvent(), and setActive().
 { return isActive(Any); }
isActive() [2/2]
bool QWidgetResizeHandler::isActive (Action ac) const
Definition at line 88 of file qwidgetresizehandler.cpp.
 {
     bool b = false;
     if (ac & Move) b = activeForMove;
     if (ac & Resize) b |= activeForResize;
     return b;
 }
isButtonDown()
bool QWidgetResizeHandler::isButtonDown () const inline
Definition at line 85 of file qwidgetresizehandler_p.h.
Referenced by QWorkspaceChild::leaveEvent().
 { return buttonDown; }
isMove()
bool QWidgetResizeHandler::isMove () const inline private
Definition at line 129 of file qwidgetresizehandler_p.h.
Referenced by keyPressEvent().
{
         return moveResizeMode && mode == Center;
     }
isMovingEnabled()
bool QWidgetResizeHandler::isMovingEnabled () const inline
Definition at line 83 of file qwidgetresizehandler_p.h.
 { return movingEnabled; }
isResize()
bool QWidgetResizeHandler::isResize () const inline private
Definition at line 132 of file qwidgetresizehandler_p.h.
Referenced by keyPressEvent().
{
         return moveResizeMode && !isMove();
     }
keyPressEvent()
void QWidgetResizeHandler::keyPressEvent (QKeyEvent * e) protected
Definition at line 374 of file qwidgetresizehandler.cpp.
Referenced by eventFilter().
 {
     if (!isMove() && !isResize())
         return;
     bool is_control = e->modifiers() & Qt::ControlModifier;
     int delta = is_control?1:8;
     QPoint pos = QCursor::pos();
     switch (e->key()) {
     case Qt::Key_Left:
         pos.rx() -= delta;
         if (pos.x() <= QApplication::desktop()->geometry().left()) {
             if (mode == TopLeft || mode == BottomLeft) {
                 moveOffset.rx() += delta;
                 invertedMoveOffset.rx() += delta;
             } else {
                 moveOffset.rx() -= delta;
                 invertedMoveOffset.rx() -= delta;
             }
         }
         if (isResize() && !resizeHorizontalDirectionFixed) {
             resizeHorizontalDirectionFixed = true;
             if (mode == BottomRight)
                 mode = BottomLeft;
             else if (mode == TopRight)
                 mode = TopLeft;
 #ifndef QT_NO_CURSOR
             setMouseCursor(mode);
             widget->grabMouse(widget->cursor());
 #else
             widget->grabMouse();
 #endif
         }
         break;
     case Qt::Key_Right:
         pos.rx() += delta;
         if (pos.x() >= QApplication::desktop()->geometry().right()) {
             if (mode == TopRight || mode == BottomRight) {
                 moveOffset.rx() += delta;
                 invertedMoveOffset.rx() += delta;
             } else {
                 moveOffset.rx() -= delta;
                 invertedMoveOffset.rx() -= delta;
             }
         }
         if (isResize() && !resizeHorizontalDirectionFixed) {
             resizeHorizontalDirectionFixed = true;
             if (mode == BottomLeft)
                 mode = BottomRight;
             else if (mode == TopLeft)
                 mode = TopRight;
 #ifndef QT_NO_CURSOR
             setMouseCursor(mode);
             widget->grabMouse(widget->cursor());
 #else
             widget->grabMouse();
 #endif
         }
         break;
     case Qt::Key_Up:
         pos.ry() -= delta;
         if (pos.y() <= QApplication::desktop()->geometry().top()) {
             if (mode == TopLeft || mode == TopRight) {
                 moveOffset.ry() += delta;
                 invertedMoveOffset.ry() += delta;
             } else {
                 moveOffset.ry() -= delta;
                 invertedMoveOffset.ry() -= delta;
             }
         }
         if (isResize() && !resizeVerticalDirectionFixed) {
             resizeVerticalDirectionFixed = true;
             if (mode == BottomLeft)
                 mode = TopLeft;
             else if (mode == BottomRight)
                 mode = TopRight;
 #ifndef QT_NO_CURSOR
             setMouseCursor(mode);
             widget->grabMouse(widget->cursor());
 #else
             widget->grabMouse();
 #endif
         }
         break;
     case Qt::Key_Down:
         pos.ry() += delta;
         if (pos.y() >= QApplication::desktop()->geometry().bottom()) {
             if (mode == BottomLeft || mode == BottomRight) {
                 moveOffset.ry() += delta;
                 invertedMoveOffset.ry() += delta;
             } else {
                 moveOffset.ry() -= delta;
                 invertedMoveOffset.ry() -= delta;
             }
         }
         if (isResize() && !resizeVerticalDirectionFixed) {
             resizeVerticalDirectionFixed = true;
             if (mode == TopLeft)
                 mode = BottomLeft;
             else if (mode == TopRight)
                 mode = BottomRight;
 #ifndef QT_NO_CURSOR
             setMouseCursor(mode);
             widget->grabMouse(widget->cursor());
 #else
             widget->grabMouse();
 #endif
         }
         break;
     case Qt::Key_Space:
     case Qt::Key_Return:
     case Qt::Key_Enter:
     case Qt::Key_Escape:
         moveResizeMode = false;
         widget->releaseMouse();
         widget->releaseKeyboard();
         buttonDown = false;
         break;
     default:
         return;
     }
     QCursor::setPos(pos);
 }
mouseMoveEvent()
void QWidgetResizeHandler::mouseMoveEvent (QMouseEvent * e) protected
Definition at line 203 of file qwidgetresizehandler.cpp.
Referenced by eventFilter().
 {
     QPoint pos = widget->mapFromGlobal(e->globalPos());
     if (!moveResizeMode && !buttonDown) {
         if (pos.y() <= range && pos.x() <= range)
             mode = TopLeft;
         else if (pos.y() >= widget->height()-range && pos.x() >= widget->width()-range)
             mode = BottomRight;
         else if (pos.y() >= widget->height()-range && pos.x() <= range)
             mode = BottomLeft;
         else if (pos.y() <= range && pos.x() >= widget->width()-range)
             mode = TopRight;
         else if (pos.y() <= range)
             mode = Top;
         else if (pos.y() >= widget->height()-range)
             mode = Bottom;
         else if (pos.x() <= range)
             mode = Left;
         else if ( pos.x() >= widget->width()-range)
             mode = Right;
         else if (widget->rect().contains(pos))
             mode = Center;
         else
             mode = Nowhere;
         if (widget->isMinimized() || !isActive(Resize))
             mode = Center;
 #ifndef QT_NO_CURSOR
         setMouseCursor(mode);
 #endif
         return;
     }
     if (mode == Center && !movingEnabled)
         return;
     if (widget->testAttribute(Qt::WA_WState_ConfigPending))
         return;
     QPoint globalPos = (!widget->isWindow() && widget->parentWidget()) ?
                        widget->parentWidget()->mapFromGlobal(e->globalPos()) : e->globalPos();
     if (!widget->isWindow() && !widget->parentWidget()->rect().contains(globalPos)) {
         if (globalPos.x() < 0)
             globalPos.rx() = 0;
         if (globalPos.y() < 0)
             globalPos.ry() = 0;
         if (sizeprotect && globalPos.x() > widget->parentWidget()->width())
             globalPos.rx() = widget->parentWidget()->width();
         if (sizeprotect && globalPos.y() > widget->parentWidget()->height())
             globalPos.ry() = widget->parentWidget()->height();
     }
     QPoint p = globalPos + invertedMoveOffset;
     QPoint pp = globalPos - moveOffset;
 #ifdef Q_WS_X11
     // Workaround for window managers which refuse to move a tool window partially offscreen.
     QRect desktop = QApplication::desktop()->availableGeometry(widget);
     pp.rx() = qMax(pp.x(), desktop.left());
     pp.ry() = qMax(pp.y(), desktop.top());
     p.rx() = qMin(p.x(), desktop.right());
     p.ry() = qMin(p.y(), desktop.bottom());
 #endif
     QSize ms = qSmartMinSize(childWidget);
     int mw = ms.width();
     int mh = ms.height();
     if (childWidget != widget) {
         mw += 2 * fw;
         mh += 2 * fw + extrahei;
     }
     QSize maxsize(childWidget->maximumSize());
     if (childWidget != widget)
         maxsize += QSize(2 * fw, 2 * fw + extrahei);
     QSize mpsize(widget->geometry().right() - pp.x() + 1,
                   widget->geometry().bottom() - pp.y() + 1);
     mpsize = mpsize.expandedTo(widget->minimumSize()).expandedTo(QSize(mw, mh))
                     .boundedTo(maxsize);
     QPoint mp(widget->geometry().right() - mpsize.width() + 1,
                widget->geometry().bottom() - mpsize.height() + 1);
     QRect geom = widget->geometry();
     switch (mode) {
     case TopLeft:
         geom = QRect(mp, widget->geometry().bottomRight()) ;
         break;
     case BottomRight:
         geom = QRect(widget->geometry().topLeft(), p) ;
         break;
     case BottomLeft:
         geom = QRect(QPoint(mp.x(), widget->geometry().y()), QPoint(widget->geometry().right(), p.y())) ;
         break;
     case TopRight:
         geom = QRect(QPoint(widget->geometry().x(), mp.y()), QPoint(p.x(), widget->geometry().bottom())) ;
         break;
     case Top:
         geom = QRect(QPoint(widget->geometry().left(), mp.y()), widget->geometry().bottomRight()) ;
         break;
     case Bottom:
         geom = QRect(widget->geometry().topLeft(), QPoint(widget->geometry().right(), p.y())) ;
         break;
     case Left:
         geom = QRect(QPoint(mp.x(), widget->geometry().top()), widget->geometry().bottomRight()) ;
         break;
     case Right:
         geom = QRect(widget->geometry().topLeft(), QPoint(p.x(), widget->geometry().bottom())) ;
         break;
     case Center:
         geom.moveTopLeft(pp);
         break;
     default:
         break;
     }
     geom = QRect(geom.topLeft(),
                   geom.size().expandedTo(widget->minimumSize())
                              .expandedTo(QSize(mw, mh))
                              .boundedTo(maxsize));
     if (geom != widget->geometry() &&
         (widget->isWindow() || widget->parentWidget()->rect().intersects(geom))) {
         if (mode == Center)
             widget->move(geom.topLeft());
         else
             widget->setGeometry(geom);
     }
     QApplication::syncX();
 }
setActive() [1/2]
void QWidgetResizeHandler::setActive (bool b) inline
Definition at line 78 of file qwidgetresizehandler_p.h.
Referenced by QWorkspacePrivate::maximizeWindow(), QWorkspacePrivate::minimizeWindow(), QWorkspacePrivate::normalizeWindow(), QWorkspaceChild::QWorkspaceChild(), and setActive().
 { setActive(Any, b); }
setActive() [2/2]
void QWidgetResizeHandler::setActive (Action ac, bool b)
Definition at line 77 of file qwidgetresizehandler.cpp.
 {
     if (ac & Move)
         activeForMove = b;
     if (ac & Resize)
         activeForResize = b;
     if (!isActive())
         setMouseCursor(Nowhere);
 }
setExtraHeight()
void QWidgetResizeHandler::setExtraHeight (int h) inline
Definition at line 87 of file qwidgetresizehandler_p.h.
Referenced by QWorkspaceChild::QWorkspaceChild().
 { extrahei = h; }
setFrameWidth()
void QWidgetResizeHandler::setFrameWidth (int w) inline
Definition at line 90 of file qwidgetresizehandler_p.h.
Referenced by QWorkspaceChild::QWorkspaceChild().
 { fw = w; }
setMouseCursor()
void QWidgetResizeHandler::setMouseCursor (MousePosition m) private
Definition at line 336 of file qwidgetresizehandler.cpp.
Referenced by doResize(), keyPressEvent(), mouseMoveEvent(), and setActive().
 {
 #ifdef QT_NO_CURSOR
     Q_UNUSED(m);
 #else
     QObjectList children = widget->children();
     for (int i = 0; i < children.size(); ++i) {
         if (QWidget *w = qobject_cast<QWidget*>(children.at(i))) {
             if (!w->testAttribute(Qt::WA_SetCursor) && !w->inherits("QWorkspaceTitleBar")) {
                 w->setCursor(Qt::ArrowCursor);
             }
         }
     }
     switch (m) {
     case TopLeft:
     case BottomRight:
         widget->setCursor(Qt::SizeFDiagCursor);
         break;
     case BottomLeft:
     case TopRight:
         widget->setCursor(Qt::SizeBDiagCursor);
         break;
     case Top:
     case Bottom:
         widget->setCursor(Qt::SizeVerCursor);
         break;
     case Left:
     case Right:
         widget->setCursor(Qt::SizeHorCursor);
         break;
     default:
         widget->setCursor(Qt::ArrowCursor);
         break;
     }
 #endif // QT_NO_CURSOR
 }
setMovingEnabled()
void QWidgetResizeHandler::setMovingEnabled (bool b) inline
Definition at line 82 of file qwidgetresizehandler_p.h.
 { movingEnabled = b; }
setSizeProtection()
void QWidgetResizeHandler::setSizeProtection (bool b) inline
Definition at line 88 of file qwidgetresizehandler_p.h.
Referenced by QWorkspaceChild::QWorkspaceChild(), and QWorkspace::setScrollBarsEnabled().
 { sizeprotect = b; }
Properties
activeForMove
uint QWidgetResizeHandler::activeForMove private
Definition at line 126 of file qwidgetresizehandler_p.h.
Referenced by doMove(), isActive(), QWidgetResizeHandler(), and setActive().
activeForResize
uint QWidgetResizeHandler::activeForResize private
Definition at line 123 of file qwidgetresizehandler_p.h.
Referenced by doResize(), isActive(), QWidgetResizeHandler(), and setActive().
buttonDown
uint QWidgetResizeHandler::buttonDown private
Definition at line 121 of file qwidgetresizehandler_p.h.
Referenced by eventFilter(), keyPressEvent(), and mouseMoveEvent().
childWidget
QWidget* QWidgetResizeHandler::childWidget private
Definition at line 114 of file qwidgetresizehandler_p.h.
Referenced by mouseMoveEvent().
extrahei
int QWidgetResizeHandler::extrahei private
Definition at line 119 of file qwidgetresizehandler_p.h.
Referenced by mouseMoveEvent().
fw
int QWidgetResizeHandler::fw private
Definition at line 118 of file qwidgetresizehandler_p.h.
Referenced by mouseMoveEvent().
invertedMoveOffset
QPoint QWidgetResizeHandler::invertedMoveOffset private
Definition at line 116 of file qwidgetresizehandler_p.h.
Referenced by doMove(), doResize(), eventFilter(), keyPressEvent(), and mouseMoveEvent().
mode
MousePosition QWidgetResizeHandler::mode private
Definition at line 117 of file qwidgetresizehandler_p.h.
Referenced by doMove(), doResize(), eventFilter(), keyPressEvent(), mouseMoveEvent(), and QWidgetResizeHandler().
moveOffset
QPoint QWidgetResizeHandler::moveOffset private
Definition at line 115 of file qwidgetresizehandler_p.h.
Referenced by doMove(), doResize(), eventFilter(), keyPressEvent(), and mouseMoveEvent().
moveResizeMode
uint QWidgetResizeHandler::moveResizeMode private
Definition at line 122 of file qwidgetresizehandler_p.h.
Referenced by doMove(), doResize(), eventFilter(), keyPressEvent(), and mouseMoveEvent().
movingEnabled
uint QWidgetResizeHandler::movingEnabled private
Definition at line 125 of file qwidgetresizehandler_p.h.
Referenced by eventFilter(), and mouseMoveEvent().
range
int QWidgetResizeHandler::range private
Definition at line 120 of file qwidgetresizehandler_p.h.
Referenced by mouseMoveEvent(), and QWidgetResizeHandler().
sizeprotect
uint QWidgetResizeHandler::sizeprotect private
Definition at line 124 of file qwidgetresizehandler_p.h.
Referenced by mouseMoveEvent().
widget
QWidget* QWidgetResizeHandler::widget private
Definition at line 113 of file qwidgetresizehandler_p.h.
Referenced by doMove(), doResize(), eventFilter(), keyPressEvent(), mouseMoveEvent(), QWidgetResizeHandler(), and setMouseCursor().
The documentation for this class was generated from the following files:
/src/gui/widgets/qwidgetresizehandler_p.h
/src/gui/widgets/qwidgetresizehandler.cpp