Qt 4.8: QScriptDebuggerScriptsModel Class Reference
QScriptDebuggerScriptsModel Class Reference
#include <qscriptdebuggerscriptsmodel_p.h>
Public Functions
void addExtraScriptInfo (qint64 id, const QMap< QString, int > &functionsInfo, const QSet< int > &executableLineNumbers)
void addScript (qint64 id, const QScriptScriptData &data)
int columnCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
void commit ()
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Reimplemented Function
QSet< int > executableLineNumbers (qint64 scriptId) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QModelIndex indexFromScriptId (qint64 id) const
QModelIndex parent (const QModelIndex &child) const
Reimplemented Function
QScriptDebuggerScriptsModel (QObject *parent=0)
void removeScript (qint64 id)
qint64 resolveScript (const QString &fileName) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QScriptScriptData scriptData (qint64 id) const
QPair< QString, int > scriptFunctionInfoFromIndex (const QModelIndex &index) const
qint64 scriptIdFromIndex (const QModelIndex &index) const
QScriptScriptMap scripts () const
~QScriptDebuggerScriptsModel ()
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Handles the data supplied by a drag and drop operation that ended with the given action.
virtual void fetchMore (const QModelIndex &parent)
Fetches any available data for the items with the parent specified by the parent index.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Returns the item flags for the given index.
virtual bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Returns true if parent has any children; otherwise returns false.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Returns the data for the given role and section in the header with the specified orientation.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
virtual bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count new columns into the model before the given column.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count rows into the model before the given row.
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
virtual QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
virtual QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of model indexes.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
virtual bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Sets the role data for the item at index to value.
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the data for the given role and section in the header with the specified orientation to the value supplied.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Sorts the model by column in the given order.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 64 of file qscriptdebuggerscriptsmodel_p.h.
Constructors and Destructors
QScriptDebuggerScriptsModel()
QScriptDebuggerScriptsModel::QScriptDebuggerScriptsModel (QObject * parent = 0)
Definition at line 98 of file qscriptdebuggerscriptsmodel.cpp.
     : QAbstractItemModel(*new QScriptDebuggerScriptsModelPrivate, parent)
 {
 }
~QScriptDebuggerScriptsModel()
QScriptDebuggerScriptsModel::~QScriptDebuggerScriptsModel ()
Definition at line 103 of file qscriptdebuggerscriptsmodel.cpp.
 {
 }
Functions
addExtraScriptInfo()
void QScriptDebuggerScriptsModel::addExtraScriptInfo (qint64 id, const QMap< QString, int > & functionsInfo, const QSet< int > & executableLineNumbers)
Definition at line 129 of file qscriptdebuggerscriptsmodel.cpp.
 {
     Q_D(QScriptDebuggerScriptsModel);
     QScriptDebuggerScriptsModelPrivate::Node *node = d->findScriptNode(sid);
     if (!node)
         return;
     QList<QPair<QString, int> > lst;
     QMap<QString, int>::const_iterator it;
     for (it = functionsInfo.constBegin(); it != functionsInfo.constEnd(); ++it)
         lst.append(qMakePair(it.key(), it.value()));
     node->functionsInfo = lst;
     node->executableLineNumbers = executableLineNumbers;
 }
addScript()
void QScriptDebuggerScriptsModel::addScript (qint64 id, const QScriptScriptData & data)
Definition at line 121 of file qscriptdebuggerscriptsmodel.cpp.
 {
     Q_D(QScriptDebuggerScriptsModel);
     int id = d->nextNodeId;
     ++d->nextNodeId;
     d->nodes.insert(id, new QScriptDebuggerScriptsModelPrivate::Node(sid, data));
 }
columnCount()
int QScriptDebuggerScriptsModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 276 of file qscriptdebuggerscriptsmodel.cpp.
 {
     return 1;
 }
commit()
void QScriptDebuggerScriptsModel::commit ()
Definition at line 145 of file qscriptdebuggerscriptsmodel.cpp.
 {
     layoutAboutToBeChanged();
     layoutChanged();
 }
data()
QVariant QScriptDebuggerScriptsModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 301 of file qscriptdebuggerscriptsmodel.cpp.
 {
     Q_D(const QScriptDebuggerScriptsModel);
     if (!index.isValid())
         return QVariant();
     int id = index.internalId();
     QScriptDebuggerScriptsModelPrivate::Node *node = d->nodes.value(id >> 12);
     if (!node)
         return QVariant();
     if (!(id & 1)) {
         if (role == Qt::DisplayRole) {
             QString fn = node->data.fileName();
             if (fn.isEmpty())
                 fn = QString::fromLatin1("<anonymous script, id=%0>").arg(node->scriptId);
             return fn;
         } else if (role == Qt::ToolTipRole) {
             QString fn = node->data.fileName();
             if (QFileInfo(fn).fileName() != fn)
                 return fn;
         } else if (role == Qt::UserRole) {
             return node->scriptId;
         } else if (role == Qt::UserRole+1) {
             return node->data.baseLineNumber();
         } else if (role == Qt::UserRole+2) {
             return node->data.contents();
         }
     } else {
         int functionIndex = (id >> 1) & ((1 << 11) - 1);
         if (role == Qt::DisplayRole)
             return node->functionsInfo[functionIndex].first;
     }
     return QVariant();
 }
executableLineNumbers()
QSet< int > QScriptDebuggerScriptsModel::executableLineNumbers (qint64 scriptId) const
Definition at line 184 of file qscriptdebuggerscriptsmodel.cpp.
Referenced by addExtraScriptInfo().
 {
     Q_D(const QScriptDebuggerScriptsModel);
     QScriptDebuggerScriptsModelPrivate::Node *node = d->findScriptNode(scriptId);
     if (!node)
         return QSet<int>();
     return node->executableLineNumbers;
 }
index()
QModelIndex QScriptDebuggerScriptsModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 240 of file qscriptdebuggerscriptsmodel.cpp.
 {
     Q_D(const QScriptDebuggerScriptsModel);
     if (!parent.isValid()) {
         if ((row < 0) || (row >= d->nodes.size()))
             return QModelIndex();
         if (column != 0)
             return QModelIndex();
         return createIndex(row, column, d->nodes.keys().at(row) << 12);
     }
     int id = parent.internalId();
     if (id & 1)
         return QModelIndex();
     return createIndex(row, column, id | (row << 1) | 1);
 }
indexFromScriptId()
QModelIndex QScriptDebuggerScriptsModel::indexFromScriptId (qint64 id) const
Definition at line 193 of file qscriptdebuggerscriptsmodel.cpp.
Referenced by parent().
 {
     Q_D(const QScriptDebuggerScriptsModel);
     int row = 0;
     QMap<int, QScriptDebuggerScriptsModelPrivate::Node*>::const_iterator it;
     for (it = d->nodes.constBegin(); it != d->nodes.constEnd(); ++it, ++row) {
         QScriptDebuggerScriptsModelPrivate::Node *n = it.value();
         if (n->scriptId == sid)
             return createIndex(row, 0, it.key() << 12);
     }
     return QModelIndex();
 }
parent()
QModelIndex QScriptDebuggerScriptsModel::parent (const QModelIndex & child) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 259 of file qscriptdebuggerscriptsmodel.cpp.
 {
     Q_D(const QScriptDebuggerScriptsModel);
     if (!index.isValid())
         return QModelIndex();
     int id = index.internalId();
     if (!(id & 1))
         return QModelIndex();
     QScriptDebuggerScriptsModelPrivate::Node *n = d->nodes.value(id >> 12);
     if (!n)
         return QModelIndex();
     return indexFromScriptId(n->scriptId);
 }
removeScript()
void QScriptDebuggerScriptsModel::removeScript (qint64 id)
Definition at line 107 of file qscriptdebuggerscriptsmodel.cpp.
 {
     Q_D(QScriptDebuggerScriptsModel);
     QMap<int, QScriptDebuggerScriptsModelPrivate::Node*>::iterator it;
     for (it = d->nodes.begin(); it != d->nodes.end(); ++it) {
         QScriptDebuggerScriptsModelPrivate::Node *n = it.value();
         if (n->scriptId == id) {
             d->nodes.erase(it);
             delete n;
             break;
         }
     }
 }
resolveScript()
qint64 QScriptDebuggerScriptsModel::resolveScript (const QString & fileName) const
Definition at line 172 of file qscriptdebuggerscriptsmodel.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsAboutToBeRemoved(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsDataChanged(), and QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsInserted().
 {
     Q_D(const QScriptDebuggerScriptsModel);
     QMap<int, QScriptDebuggerScriptsModelPrivate::Node*>::const_iterator it;
     for (it = d->nodes.constBegin(); it != d->nodes.constEnd(); ++it) {
         QScriptDebuggerScriptsModelPrivate::Node *n = it.value();
         if (n->data.fileName() == fileName)
             return n->scriptId;
     }
     return -1;
 }
rowCount()
int QScriptDebuggerScriptsModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 284 of file qscriptdebuggerscriptsmodel.cpp.
 {
     Q_D(const QScriptDebuggerScriptsModel);
     if (!parent.isValid())
         return d->nodes.size();
     int id = parent.internalId();
     if (id & 1)
         return 0;
     QScriptDebuggerScriptsModelPrivate::Node *n = d->nodes.value(id >> 12);
     if (!n)
         return 0;
     return n->functionsInfo.size();
 }
scriptData()
QScriptScriptData QScriptDebuggerScriptsModel::scriptData (qint64 id) const
Definition at line 151 of file qscriptdebuggerscriptsmodel.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointEnableRequest(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointToggleRequest(), QScriptDebuggerCodeWidgetPrivate::_q_onScriptsChanged(), and QScriptDebuggerPrivate::_q_toggleBreakpoint().
 {
     Q_D(const QScriptDebuggerScriptsModel);
     QScriptDebuggerScriptsModelPrivate::Node *node = d->findScriptNode(sid);
     if (!node)
         return QScriptScriptData();
     return node->data;
 }
scriptFunctionInfoFromIndex()
QPair< QString, int > QScriptDebuggerScriptsModel::scriptFunctionInfoFromIndex (const QModelIndex & index) const
Definition at line 220 of file qscriptdebuggerscriptsmodel.cpp.
 {
     Q_D(const QScriptDebuggerScriptsModel);
     QPair<QString, int> result;
     if (!index.isValid())
         return result;
     int id = index.internalId();
     if (!(id & 1))
         return result;
     QScriptDebuggerScriptsModelPrivate::Node *node = d->nodes.value(id >> 12);
     if (!node)
         return result;
     int functionIndex = (id >> 1) & ((1 << 11) - 1);
     result = node->functionsInfo.at(functionIndex);
     return result;
 }
scriptIdFromIndex()
qint64 QScriptDebuggerScriptsModel::scriptIdFromIndex (const QModelIndex & index) const
Definition at line 206 of file qscriptdebuggerscriptsmodel.cpp.
Referenced by QScriptDebuggerScriptsWidget::currentScriptId().
 {
     Q_D(const QScriptDebuggerScriptsModel);
     if (!index.isValid())
         return -1;
     int id = index.internalId();
     if (id & 1)
         return -1;
     QScriptDebuggerScriptsModelPrivate::Node *n = d->nodes.value(id >> 12);
     if (!n)
         return -1;
     return n->scriptId;
 }
scripts()
QScriptScriptMap QScriptDebuggerScriptsModel::scripts () const
Definition at line 160 of file qscriptdebuggerscriptsmodel.cpp.
 {
     Q_D(const QScriptDebuggerScriptsModel);
     QScriptScriptMap result;
     QMap<int, QScriptDebuggerScriptsModelPrivate::Node*>::const_iterator it;
     for (it = d->nodes.constBegin(); it != d->nodes.constEnd(); ++it) {
         QScriptDebuggerScriptsModelPrivate::Node *n = it.value();
         result.insert(n->scriptId, n->data);
     }
     return result;
 }
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerscriptsmodel_p.h
/src/scripttools/debugging/qscriptdebuggerscriptsmodel.cpp