Qt 4.8: QProcessManager Class Reference
QProcessManager Class Reference
Public Functions
void add (pid_t pid, QProcess *process)
void catchDeadChildren ()
void lock ()
QProcessManager ()
void remove (QProcess *process)
void run ()
The starting point for the thread.
void unlock ()
~QProcessManager ()
Public Functions inherited from QThread
void exit (int retcode=0)
Tells the thread's event loop to exit with a return code.
bool isFinished () const
Returns true if the thread is finished; otherwise returns false.
bool isRunning () const
Returns true if the thread is running; otherwise returns false.
Priority priority () const
Returns the priority for a running thread.
QThread (QObject *parent=0)
Constructs a new QThread to manage a new thread.
void setPriority (Priority priority)
This function sets the priority for a running thread.
void setStackSize (uint stackSize)
Sets the maximum stack size for the thread to stackSize.
uint stackSize () const
Returns the maximum stack size for the thread (if set with setStackSize()); otherwise returns zero.
bool wait (unsigned long time=ULONG_MAX)
Blocks the thread until either of these conditions is met:
~QThread ()
Destroys the QThread.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QHash< int, QProcessInfo * > children
QMutex mutex
Additional Inherited Members
Public Types inherited from QThread
enum Priority {
IdlePriority, LowestPriority, LowPriority, NormalPriority,
HighPriority, HighestPriority, TimeCriticalPriority, InheritPriority
}
This enum type indicates how the operating system should schedule newly created threads.
Public Slots inherited from QThread
void quit ()
Tells the thread's event loop to exit with return code 0 (success).
void start (Priority=InheritPriority)
Begins execution of the thread by calling run().
void terminate ()
Terminates the execution of the thread.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QThread
void finished ()
This signal is emitted when the thread has finished executing.
void started ()
This signal is emitted when the thread starts executing.
void terminated ()
This signal is emitted when the thread is terminated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QThread
static QThread * currentThread ()
Returns a pointer to a QThread which manages the currently executing thread.
static Qt::HANDLE currentThreadId ()
Returns the thread handle of the currently executing thread.
static int idealThreadCount ()
Returns the ideal number of threads that can be run on the system.
static void yieldCurrentThread ()
Yields execution of the current thread to another runnable thread, if any.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QThread
int exec ()
Enters the event loop and waits until exit() is called, returning the value that was passed to exit().
QThread (QThreadPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Protected Functions inherited from QThread
static void msleep (unsigned long)
Forces the current thread to sleep for msecs milliseconds.
static void setTerminationEnabled (bool enabled=true)
Enables or disables termination of the current thread based on the enabled parameter.
static void sleep (unsigned long)
Forces the current thread to sleep for secs seconds.
static void usleep (unsigned long)
Forces the current thread to sleep for usecs microseconds.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 176 of file qprocess_unix.cpp.
Constructors and Destructors
QProcessManager()
QProcessManager::QProcessManager ()
Definition at line 207 of file qprocess_unix.cpp.
 {
 #if defined (QPROCESS_DEBUG)
     qDebug() << "QProcessManager::QProcessManager()";
 #endif
     // initialize the dead child pipe and make it non-blocking. in the
     // extremely unlikely event that the pipe fills up, we do not under any
     // circumstances want to block.
     qt_safe_pipe(qt_qprocess_deadChild_pipe, O_NONBLOCK);
     // set up the SIGCHLD handler, which writes a single byte to the dead
     // child pipe every time a child dies.
     struct sigaction action;
     // use the old handler as template, i.e., preserve the signal mask
     // otherwise the original signal handler might be interrupted although it
     // was marked to never be interrupted
     ::sigaction(SIGCHLD, NULL, &action);
     action.sa_sigaction = qt_sa_sigchld_sigaction;
     // set the SA_SIGINFO flag such that we can use the three argument handler
     // function
     action.sa_flags = SA_NOCLDSTOP | SA_SIGINFO;
     ::sigaction(SIGCHLD, &action, &qt_sa_old_sigchld_handler);
 }
~QProcessManager()
QProcessManager::~QProcessManager ()
Definition at line 232 of file qprocess_unix.cpp.
 {
     // notify the thread that we're shutting down.
     qt_safe_write(qt_qprocess_deadChild_pipe[1], "@", 1);
     qt_safe_close(qt_qprocess_deadChild_pipe[1]);
     wait();
     // on certain unixes, closing the reading end of the pipe will cause
     // select in run() to block forever, rather than return with EBADF.
     qt_safe_close(qt_qprocess_deadChild_pipe[0]);
     qt_qprocess_deadChild_pipe[0] = -1;
     qt_qprocess_deadChild_pipe[1] = -1;
     qDeleteAll(children.values());
     children.clear();
     struct sigaction currentAction;
     ::sigaction(SIGCHLD, 0, &currentAction);
     if (currentAction.sa_sigaction == qt_sa_sigchld_sigaction) {
         ::sigaction(SIGCHLD, &qt_sa_old_sigchld_handler, 0);
     }
 }
Functions
add()
void QProcessManager::add (pid_t pid, QProcess * process)
Definition at line 311 of file qprocess_unix.cpp.
Referenced by QProcessPrivate::startProcess().
 {
 #if defined (QPROCESS_DEBUG)
     qDebug() << "QProcessManager::add() adding pid" << pid << "process" << process;
 #endif
     // insert a new info structure for this process
     QProcessInfo *info = new QProcessInfo;
     info->process = process;
     info->deathPipe = process->d_func()->deathPipe[1];
     info->exitResult = 0;
     info->pid = pid;
     int serial = idCounter.fetchAndAddRelaxed(1);
     process->d_func()->serial = serial;
     children.insert(serial, info);
 }
catchDeadChildren()
void QProcessManager::catchDeadChildren ()
Definition at line 289 of file qprocess_unix.cpp.
 {
     QMutexLocker locker(&mutex);
     // try to catch all children whose pid we have registered, and whose
     // deathPipe is still valid (i.e, we have not already notified it).
     QHash<int, QProcessInfo *>::Iterator it = children.begin();
     while (it != children.end()) {
         // notify all children that they may have died. they need to run
         // waitpid() in their own thread.
         QProcessInfo *info = it.value();
         qt_safe_write(info->deathPipe, "", 1);
 #if defined (QPROCESS_DEBUG)
         qDebug() << "QProcessManager::run() sending death notice to" << info->process;
 #endif
         ++it;
     }
 }
lock()
void QProcessManager::lock ()
Definition at line 342 of file qprocess_unix.cpp.
Referenced by QProcessPrivate::startProcess().
 {
     mutex.lock();
 }
remove()
void QProcessManager::remove (QProcess * process)
Definition at line 329 of file qprocess_unix.cpp.
Referenced by QProcessPrivate::findExitCode(), and QProcessPrivate::waitForDeadChild().
 {
     QMutexLocker locker(&mutex);
     int serial = process->d_func()->serial;
     QProcessInfo *info = children.take(serial);
 #if defined (QPROCESS_DEBUG)
     if (info)
         qDebug() << "QProcessManager::remove() removing pid" << info->pid << "process" << info->process;
 #endif
     delete info;
 }
run()
void QProcessManager::run (void) virtual
The starting point for the thread.
After calling start(), the newly created thread calls this function. The default implementation simply calls exec().
You can reimplement this function to facilitate advanced thread management. Returning from this method will end the execution of the thread.
See also
start() wait()
Reimplemented from QThread.
Definition at line 256 of file qprocess_unix.cpp.
 {
     forever {
         fd_set readset;
         FD_ZERO(&readset);
         FD_SET(qt_qprocess_deadChild_pipe[0], &readset);
 #if defined (QPROCESS_DEBUG)
         qDebug() << "QProcessManager::run() waiting for children to die";
 #endif
         // block forever, or until activity is detected on the dead child
         // pipe. the only other peers are the SIGCHLD signal handler, and the
         // QProcessManager destructor.
         int nselect = select(qt_qprocess_deadChild_pipe[0] + 1, &readset, 0, 0, 0);
         if (nselect < 0) {
             if (errno == EINTR)
                 continue;
             break;
         }
         // empty only one byte from the pipe, even though several SIGCHLD
         // signals may have been delivered in the meantime, to avoid race
         // conditions.
         char c;
         if (qt_safe_read(qt_qprocess_deadChild_pipe[0], &c, 1) < 0 || c == '@')
             break;
         // catch any and all children that we can.
         catchDeadChildren();
     }
 }
unlock()
void QProcessManager::unlock ()
Definition at line 347 of file qprocess_unix.cpp.
Referenced by QProcessPrivate::startProcess().
 {
     mutex.unlock();
 }
Properties
children
QHash<int, QProcessInfo *> QProcessManager::children private
Definition at line 192 of file qprocess_unix.cpp.
mutex
QMutex QProcessManager::mutex private
Definition at line 191 of file qprocess_unix.cpp.
The documentation for this class was generated from the following file:
/src/corelib/io/qprocess_unix.cpp