Qt 4.8: QWSTslibMouseHandlerPrivate Class Reference
QWSTslibMouseHandlerPrivate Class Reference
Public Functions
void calibrate (const QWSPointerCalibrationData *data)
void clearCalibration ()
QWSTslibMouseHandlerPrivate (QWSTslibMouseHandler *h, const QString &device)
void resume ()
void suspend ()
~QWSTslibMouseHandlerPrivate ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void readMouseData ()
Private Functions
void close ()
bool get_sample (struct ts_sample *sample)
bool open ()
Properties
bool calibrated
struct tsdev * dev
QString devName
QWSTslibMouseHandler * handler
int jitter_limit
int lastdx
int lastdy
struct ts_sample lastSample
QSocketNotifier * mouseNotifier
bool wasPressed
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 102 of file qmousetslib_qws.cpp.
Constructors and Destructors
QWSTslibMouseHandlerPrivate()
QWSTslibMouseHandlerPrivate::QWSTslibMouseHandlerPrivate (QWSTslibMouseHandler * h, const QString & device)
Definition at line 138 of file qmousetslib_qws.cpp.
     : handler(h), dev(0), mouseNotifier(0), jitter_limit(3)
 {
     QStringList args = device.split(QLatin1Char(':'), QString::SkipEmptyParts);
     QRegExp jitterRegex(QLatin1String("^jitter_limit=(\\d+)$"));
     int index = args.indexOf(jitterRegex);
     if (index >= 0) {
         jitter_limit = jitterRegex.cap(1).toInt();
         args.removeAt(index);
     }
     devName = args.join(QString());
     if (devName.isNull()) {
         const char *str = getenv("TSLIB_TSDEVICE");
         if (str)
             devName = QString::fromLocal8Bit(str);
     }
     if (devName.isNull())
         devName = QLatin1String("/dev/ts");
     if (!open())
         return;
     calibrated = true;
     int fd = ts_fd(dev);
     mouseNotifier = new QSocketNotifier(fd, QSocketNotifier::Read, this);
     connect(mouseNotifier, SIGNAL(activated(int)),this, SLOT(readMouseData()));
     resume();
 }
~QWSTslibMouseHandlerPrivate()
QWSTslibMouseHandlerPrivate::~QWSTslibMouseHandlerPrivate ()
Definition at line 172 of file qmousetslib_qws.cpp.
 {
     close();
 }
Functions
calibrate()
void QWSTslibMouseHandlerPrivate::calibrate (const QWSPointerCalibrationData * data)
Definition at line 307 of file qmousetslib_qws.cpp.
Referenced by QWSTslibMouseHandler::calibrate().
 {
     suspend();
     close();
     // default implementation writes to /etc/pointercal
     // using the same format as the tslib linear module.
     handler->QWSCalibratedMouseHandler::calibrate(data);
     calibrated = true;
     open();
     resume();
 }
clearCalibration()
void QWSTslibMouseHandlerPrivate::clearCalibration ()
Definition at line 297 of file qmousetslib_qws.cpp.
Referenced by QWSTslibMouseHandler::clearCalibration().
 {
     suspend();
     close();
     handler->QWSCalibratedMouseHandler::clearCalibration();
     calibrated = false;
     open();
     resume();
 }
close()
void QWSTslibMouseHandlerPrivate::close () private
Definition at line 198 of file qmousetslib_qws.cpp.
Referenced by calibrate(), clearCalibration(), open(), and ~QWSTslibMouseHandlerPrivate().
 {
     if (dev)
         ts_close(dev);
 }
get_sample()
bool QWSTslibMouseHandlerPrivate::get_sample (struct ts_sample * sample) inline private
Definition at line 220 of file qmousetslib_qws.cpp.
Referenced by readMouseData().
 {
     if (!calibrated)
         return (ts_read_raw(dev, sample, 1) == 1);
     return (ts_read(dev, sample, 1) == 1);
 }
open()
bool QWSTslibMouseHandlerPrivate::open () private
Definition at line 177 of file qmousetslib_qws.cpp.
Referenced by calibrate(), clearCalibration(), and QWSTslibMouseHandlerPrivate().
 {
     dev = ts_open(devName.toLocal8Bit().constData(), 1);
     if (!dev) {
         qCritical("QWSTslibMouseHandlerPrivate: ts_open() failed"
                   " with error: '%s'", strerror(errno));
         qCritical("Please check your tslib installation!");
         return false;
     }
     if (ts_config(dev)) {
         qCritical("QWSTslibMouseHandlerPrivate: ts_config() failed"
                   " with error: '%s'", strerror(errno));
         qCritical("Please check your tslib installation!");
         close();
         return false;
     }
     return true;
 }
readMouseData
void QWSTslibMouseHandlerPrivate::readMouseData () private slot
Definition at line 228 of file qmousetslib_qws.cpp.
Referenced by QWSTslibMouseHandlerPrivate().
 {
     if (!qt_screen)
         return;
     for(;;) {
         struct ts_sample sample = lastSample;
         bool pressed = wasPressed;
         // Fast return if there's no events.
         if (!get_sample(&sample))
             return;
         pressed = (sample.pressure > 0);
         // Only return last sample unless there's a press/release event.
         while (pressed == wasPressed) {
             if (!get_sample(&sample))
                 break;
             pressed = (sample.pressure > 0);
         }
         // work around missing coordinates on mouse release in raw mode
         if (!calibrated && !pressed && sample.x == 0 && sample.y == 0) {
             sample.x = lastSample.x;
             sample.y = lastSample.y;
         }
         int dx = sample.x - lastSample.x;
         int dy = sample.y - lastSample.y;
         // Remove small movements in oppsite direction
         if (dx * lastdx < 0 && qAbs(dx) < jitter_limit) {
             sample.x = lastSample.x;
             dx = 0;
         }
         if (dy * lastdy < 0 && qAbs(dy) < jitter_limit) {
             sample.y = lastSample.y;
             dy = 0;
         }
         if (wasPressed == pressed && dx == 0 && dy == 0)
             return;
 #ifdef TSLIBMOUSEHANDLER_DEBUG
         qDebug() << "last" << QPoint(lastSample.x, lastSample.y)
                  << "curr" << QPoint(sample.x, sample.y)
                  << "dx,dy" << QPoint(dx, dy)
                  << "ddx,ddy" << QPoint(dx*lastdx, dy*lastdy)
                  << "pressed" << wasPressed << pressed;
 #endif
         lastSample = sample;
         wasPressed = pressed;
         if (dx != 0)
             lastdx = dx;
         if (dy != 0)
             lastdy = dy;
         const QPoint p(sample.x, sample.y);
         if (calibrated) {
             // tslib should do all the translation and filtering, so we send a
             // "raw" mouse event
             handler->QWSMouseHandler::mouseChanged(p, pressed);
         } else {
             handler->sendFiltered(p, pressed);
         }
     }
 }
resume()
void QWSTslibMouseHandlerPrivate::resume ()
Definition at line 210 of file qmousetslib_qws.cpp.
Referenced by calibrate(), clearCalibration(), QWSTslibMouseHandlerPrivate(), and QWSTslibMouseHandler::resume().
 {
     memset(&lastSample, 0, sizeof(lastSample));
     wasPressed = false;
     lastdx = 0;
     lastdy = 0;
     if (mouseNotifier)
         mouseNotifier->setEnabled(true);
 }
suspend()
void QWSTslibMouseHandlerPrivate::suspend ()
Definition at line 204 of file qmousetslib_qws.cpp.
Referenced by calibrate(), clearCalibration(), and QWSTslibMouseHandler::suspend().
 {
     if (mouseNotifier)
         mouseNotifier->setEnabled(false);
 }
Properties
calibrated
bool QWSTslibMouseHandlerPrivate::calibrated private
Definition at line 127 of file qmousetslib_qws.cpp.
Referenced by calibrate(), clearCalibration(), get_sample(), QWSTslibMouseHandlerPrivate(), and readMouseData().
dev
struct tsdev* QWSTslibMouseHandlerPrivate::dev private
Definition at line 118 of file qmousetslib_qws.cpp.
Referenced by close(), get_sample(), open(), and QWSTslibMouseHandlerPrivate().
devName
QString QWSTslibMouseHandlerPrivate::devName private
Definition at line 128 of file qmousetslib_qws.cpp.
Referenced by open(), and QWSTslibMouseHandlerPrivate().
handler
QWSTslibMouseHandler* QWSTslibMouseHandlerPrivate::handler private
Definition at line 117 of file qmousetslib_qws.cpp.
Referenced by calibrate(), clearCalibration(), and readMouseData().
jitter_limit
int QWSTslibMouseHandlerPrivate::jitter_limit private
Definition at line 120 of file qmousetslib_qws.cpp.
Referenced by QWSTslibMouseHandlerPrivate(), and readMouseData().
lastdx
int QWSTslibMouseHandlerPrivate::lastdx private
Definition at line 124 of file qmousetslib_qws.cpp.
Referenced by readMouseData(), and resume().
lastdy
int QWSTslibMouseHandlerPrivate::lastdy private
Definition at line 125 of file qmousetslib_qws.cpp.
Referenced by readMouseData(), and resume().
lastSample
struct ts_sample QWSTslibMouseHandlerPrivate::lastSample private
Definition at line 122 of file qmousetslib_qws.cpp.
Referenced by readMouseData(), and resume().
mouseNotifier
QSocketNotifier* QWSTslibMouseHandlerPrivate::mouseNotifier private
Definition at line 119 of file qmousetslib_qws.cpp.
Referenced by QWSTslibMouseHandlerPrivate(), resume(), and suspend().
wasPressed
bool QWSTslibMouseHandlerPrivate::wasPressed private
Definition at line 123 of file qmousetslib_qws.cpp.
Referenced by readMouseData(), and resume().
The documentation for this class was generated from the following file:
/src/gui/embedded/qmousetslib_qws.cpp