Qt 4.8: QSharedMemoryPrivate Class Reference
QSharedMemoryPrivate Class Reference
#include <qsharedmemory_p.h>
Public Functions
bool attach (QSharedMemory::AccessMode mode)
void cleanHandle ()
bool create (int size)
bool detach ()
HANDLE handle ()
If not already made create the handle used for accessing the shared memory.
bool initKey ()
QSharedMemoryPrivate ()
void setErrorString (const QString &function)
bool tryLocker (QSharedMemoryLocker *locker, const QString &function)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static int createUnixKeyFile (const QString &fileName)
Creates the unix file if needed.
static QString makePlatformSafeKey (const QString &key, const QString &prefix=QLatin1String("qipc_sharedmemory_"))
Generate a string from the key which can be any unicode string into the subset that the win/unix kernel allows.
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QSharedMemory::SharedMemoryError error
QString errorString
QString key
bool lockedByMe
void * memory
QString nativeKey
int size
QSystemSemaphore systemSemaphore
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Properties
HANDLE hand
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 115 of file qsharedmemory_p.h.
Constructors and Destructors
QSharedMemoryPrivate()
QSharedMemoryPrivate::QSharedMemoryPrivate ()
Definition at line 72 of file qsharedmemory_unix.cpp.
     : QObjectPrivate(), memory(0), size(0), error(QSharedMemory::NoError),
 #ifndef QT_NO_SYSTEMSEMAPHORE
       systemSemaphore(QString()), lockedByMe(false),
 #endif
 #ifndef QT_POSIX_IPC
       unix_key(0)
 #else
       hand(0)
 #endif
 {
 }
Functions
attach()
bool QSharedMemoryPrivate::attach (QSharedMemory::AccessMode mode)
Definition at line 298 of file qsharedmemory_unix.cpp.
 {
 #ifndef QT_POSIX_IPC
     // grab the shared memory segment id
     int id = shmget(unix_key, 0, (mode == QSharedMemory::ReadOnly ? 0400 : 0600));
     if (-1 == id) {
         setErrorString(QLatin1String("QSharedMemory::attach (shmget)"));
         return false;
     }
     // grab the memory
     memory = shmat(id, 0, (mode == QSharedMemory::ReadOnly ? SHM_RDONLY : 0));
     if ((void*) - 1 == memory) {
         memory = 0;
         setErrorString(QLatin1String("QSharedMemory::attach (shmat)"));
         return false;
     }
     // grab the size
     shmid_ds shmid_ds;
     if (!shmctl(id, IPC_STAT, &shmid_ds)) {
         size = (int)shmid_ds.shm_segsz;
     } else {
         setErrorString(QLatin1String("QSharedMemory::attach (shmctl)"));
         return false;
     }
 #else
     QByteArray shmName = QFile::encodeName(makePlatformSafeKey(key));
     int oflag = (mode == QSharedMemory::ReadOnly ? O_RDONLY : O_RDWR);
     mode_t omode = (mode == QSharedMemory::ReadOnly ? 0444 : 0660);
     EINTR_LOOP(hand, shm_open(shmName.constData(), oflag, omode));
     if (hand == -1) {
         QString function = QLatin1String("QSharedMemory::attach (shm_open)");
         switch (errno) {
         case ENAMETOOLONG:
         case EINVAL:
             errorString = QSharedMemory::tr("%1: bad name").arg(function);
             error = QSharedMemory::KeyError;
             break;
         default:
             setErrorString(function);
         }
         hand = 0;
         return false;
     }
     // grab the size
     QT_STATBUF st;
     if (QT_FSTAT(hand, &st) == -1) {
         setErrorString(QLatin1String("QSharedMemory::attach (fstat)"));
         cleanHandle();
         return false;
     }
     size = st.st_size;
     // grab the memory
     int mprot = (mode == QSharedMemory::ReadOnly ? PROT_READ : PROT_READ | PROT_WRITE);
     memory = mmap(0, size, mprot, MAP_SHARED, hand, 0);
     if (memory == MAP_FAILED || !memory) {
         setErrorString(QLatin1String("QSharedMemory::attach (mmap)"));
         cleanHandle();
         memory = 0;
         size = 0;
         return false;
     }
 #endif // QT_POSIX_IPC
     return true;
 }
cleanHandle()
void QSharedMemoryPrivate::cleanHandle ()
Definition at line 217 of file qsharedmemory_unix.cpp.
Referenced by attach(), and detach().
 {
 #ifndef QT_POSIX_IPC
     unix_key = 0;
 #else
     qt_safe_close(hand);
     hand = 0;
 #endif
 }
create()
bool QSharedMemoryPrivate::create (int size)
Definition at line 227 of file qsharedmemory_unix.cpp.
 {
 #ifndef QT_POSIX_IPC
     // build file if needed
     int built = createUnixKeyFile(nativeKey);
     if (built == -1) {
         errorString = QSharedMemory::tr("%1: unable to make key").arg(QLatin1String("QSharedMemory::create"));
         error = QSharedMemory::KeyError;
         return false;
     }
     bool createdFile = built == 1;
     // get handle
     if (!handle()) {
         if (createdFile)
             QFile::remove(nativeKey);
         return false;
     }
     // create
     if (-1 == shmget(unix_key, size, 0600 | IPC_CREAT | IPC_EXCL)) {
         QString function = QLatin1String("QSharedMemory::create");
         switch (errno) {
         case EINVAL:
             errorString = QSharedMemory::tr("%1: system-imposed size restrictions").arg(function);
             error = QSharedMemory::InvalidSize;
             break;
         default:
             setErrorString(function);
         }
         if (createdFile && error != QSharedMemory::AlreadyExists)
             QFile::remove(nativeKey);
         return false;
     }
 #else
     if (!handle())
         return false;
     QByteArray shmName = QFile::encodeName(makePlatformSafeKey(key));
     int fd;
     EINTR_LOOP(fd, shm_open(shmName.constData(), O_RDWR | O_CREAT | O_EXCL, 0666));
     if (fd == -1) {
         QString function = QLatin1String("QSharedMemory::create");
         switch (errno) {
         case ENAMETOOLONG:
         case EINVAL:
             errorString = QSharedMemory::tr("%1: bad name").arg(function);
             error = QSharedMemory::KeyError;
             break;
         default:
             setErrorString(function);
         }
         return false;
     }
     // the size may only be set once; ignore errors
     int ret;
     EINTR_LOOP(ret, ftruncate(fd, size));
     if (ret == -1) {
         setErrorString(QLatin1String("QSharedMemory::create (ftruncate)"));
         qt_safe_close(fd);
         return false;
     }
     qt_safe_close(fd);
 #endif // QT_POSIX_IPC
     return true;
 }
createUnixKeyFile()
int QSharedMemoryPrivate::createUnixKeyFile (const QString & fileName) static
Creates the unix file if needed.
Warning
This function is not part of the public interface.
returns true if the unix file was created.
-1 error 0 already existed 1 created
Definition at line 191 of file qsharedmemory_unix.cpp.
Referenced by create(), and QSystemSemaphorePrivate::handle().
 {
 #ifndef QT_POSIX_IPC
     if (QFile::exists(fileName))
         return 0;
     int fd = qt_safe_open(QFile::encodeName(fileName).constData(),
                           O_EXCL | O_CREAT | O_RDWR, 0640);
     if (-1 == fd) {
         if (errno == EEXIST)
             return 0;
         return -1;
     } else {
         qt_safe_close(fd);
     }
     return 1;
 #else
     Q_UNUSED(fileName);
     // nothing to do
     return -1;
 #endif
 }
detach()
bool QSharedMemoryPrivate::detach ()
Definition at line 370 of file qsharedmemory_unix.cpp.
 {
 #ifndef QT_POSIX_IPC
     // detach from the memory segment
     if (-1 == shmdt(memory)) {
         QString function = QLatin1String("QSharedMemory::detach");
         switch (errno) {
         case EINVAL:
             errorString = QSharedMemory::tr("%1: not attached").arg(function);
             error = QSharedMemory::NotFound;
             break;
         default:
             setErrorString(function);
         }
         return false;
     }
     memory = 0;
     size = 0;
     // Get the number of current attachments
     int id = shmget(unix_key, 0, 0400);
     cleanHandle();
     struct shmid_ds shmid_ds;
     if (0 != shmctl(id, IPC_STAT, &shmid_ds)) {
         switch (errno) {
         case EINVAL:
             return true;
         default:
             return false;
         }
     }
     // If there are no attachments then remove it.
     if (shmid_ds.shm_nattch == 0) {
         // mark for removal
         if (-1 == shmctl(id, IPC_RMID, &shmid_ds)) {
             setErrorString(QLatin1String("QSharedMemory::detach"));
             switch (errno) {
             case EINVAL:
                 return true;
             default:
                 return false;
             }
         }
         // remove file
         if (!QFile::remove(nativeKey))
             return false;
     }
 #else
     // detach from the memory segment
     if (munmap(memory, size) == -1) {
         setErrorString(QLatin1String("QSharedMemory::detach (munmap)"));
         return false;
     }
     memory = 0;
     size = 0;
     // get the number of current attachments
     int shm_nattch = 0;
     QT_STATBUF st;
     if (QT_FSTAT(hand, &st) == 0) {
         // subtract 2 from linkcount: one for our own open and one for the dir entry
         shm_nattch = st.st_nlink - 2;
     }
     cleanHandle();
     // if there are no attachments then unlink the shared memory
     if (shm_nattch == 0) {
         QByteArray shmName = QFile::encodeName(makePlatformSafeKey(key));
         if (shm_unlink(shmName.constData()) == -1 && errno != ENOENT)
             setErrorString(QLatin1String("QSharedMemory::detach (shm_unlink)"));
     }
 #endif // QT_POSIX_IPC
     return true;
 }
handle()
HANDLE QSharedMemoryPrivate::handle ()
If not already made create the handle used for accessing the shared memory.
Warning
This function is not part of the public interface.
Definition at line 133 of file qsharedmemory_unix.cpp.
Referenced by create().
 {
     // already made
     if (unix_key)
         return unix_key;
     // don't allow making handles on empty keys
     if (nativeKey.isEmpty()) {
         errorString = QSharedMemory::tr("%1: key is empty").arg(QLatin1String("QSharedMemory::handle"));
         error = QSharedMemory::KeyError;
         return 0;
     }
     // ftok requires that an actual file exists somewhere
     if (!QFile::exists(nativeKey)) {
         errorString = QSharedMemory::tr("%1: UNIX key file doesn't exist").arg(QLatin1String("QSharedMemory::handle"));
         error = QSharedMemory::NotFound;
         return 0;
     }
     unix_key = ftok(QFile::encodeName(nativeKey).constData(), 'Q');
     if (-1 == unix_key) {
         errorString = QSharedMemory::tr("%1: ftok failed").arg(QLatin1String("QSharedMemory::handle"));
         error = QSharedMemory::KeyError;
         unix_key = 0;
     }
     return unix_key;
 }
initKey()
bool QSharedMemoryPrivate::initKey ()
Definition at line 271 of file qsharedmemory.cpp.
 {
     cleanHandle();
 #ifndef QT_NO_SYSTEMSEMAPHORE
     systemSemaphore.setKey(QString(), 1);
     systemSemaphore.setKey(key, 1);
     if (systemSemaphore.error() != QSystemSemaphore::NoError) {
         QString function = QLatin1String("QSharedMemoryPrivate::initKey");
         errorString = QSharedMemory::tr("%1: unable to set key on lock").arg(function);
         switch(systemSemaphore.error()) {
         case QSystemSemaphore::PermissionDenied:
             error = QSharedMemory::PermissionDenied;
             break;
         case QSystemSemaphore::KeyError:
             error = QSharedMemory::KeyError;
             break;
         case QSystemSemaphore::AlreadyExists:
             error = QSharedMemory::AlreadyExists;
             break;
         case QSystemSemaphore::NotFound:
             error = QSharedMemory::NotFound;
             break;
         case QSystemSemaphore::OutOfResources:
             error = QSharedMemory::OutOfResources;
             break;
         case QSystemSemaphore::UnknownError:
         default:
             error = QSharedMemory::UnknownError;
             break;
         }
         return false;
     }
 #endif
     errorString.clear();
     error = QSharedMemory::NoError;
     return true;
 }
makePlatformSafeKey()
QString QSharedMemoryPrivate::makePlatformSafeKey (const QString & key, const QString & prefix = QLatin1String("qipc_sharedmemory_")) static
Generate a string from the key which can be any unicode string into the subset that the win/unix kernel allows.
Warning
This function is not part of the public interface.
On Unix this will be a file name On Symbian key will be truncated to 80 characters
Definition at line 68 of file qsharedmemory.cpp.
Referenced by attach(), create(), detach(), handle(), and QSystemSemaphorePrivate::makeKeyFileName().
 {
     if (key.isEmpty())
         return QString();
     QString result = prefix;
     QString part1 = key;
     part1.replace(QRegExp(QLatin1String("[^A-Za-z]")), QString());
     result.append(part1);
     QByteArray hex = QCryptographicHash::hash(key.toUtf8(), QCryptographicHash::Sha1).toHex();
     result.append(QLatin1String(hex));
 #ifdef Q_OS_WIN
     return result;
 #elif defined(Q_OS_SYMBIAN)
     return result.left(KMaxKernelName);
 #elif defined(QT_POSIX_IPC)
     return QLatin1Char('/') + result;
 #else
     return QDir::tempPath() + QLatin1Char('/') + result;
 #endif
 }
setErrorString()
void QSharedMemoryPrivate::setErrorString (const QString & function)
Definition at line 85 of file qsharedmemory_unix.cpp.
Referenced by attach(), create(), and detach().
 {
     // EINVAL is handled in functions so they can give better error strings
     switch (errno) {
     case EACCES:
     case EPERM:
         errorString = QSharedMemory::tr("%1: permission denied").arg(function);
         error = QSharedMemory::PermissionDenied;
         break;
     case EEXIST:
         errorString = QSharedMemory::tr("%1: already exists").arg(function);
         error = QSharedMemory::AlreadyExists;
         break;
     case ENOENT:
         errorString = QSharedMemory::tr("%1: doesn't exist").arg(function);
         error = QSharedMemory::NotFound;
         break;
     case EAGAIN:
     case EMFILE:
     case ENFILE:
     case ENOMEM:
     case ENOSPC:
         errorString = QSharedMemory::tr("%1: out of resources").arg(function);
         error = QSharedMemory::OutOfResources;
         break;
     case EOVERFLOW:
         errorString = QSharedMemory::tr("%1: invalid size").arg(function);
         error = QSharedMemory::InvalidSize;
         break;
     default:
         errorString = QSharedMemory::tr("%1: unknown error %2").arg(function).arg(errno);
         error = QSharedMemory::UnknownError;
 #ifdef QSHAREDMEMORY_DEBUG
         qDebug() << errorString << "key" << key << "errno" << errno << EINVAL;
 #endif
         break;
     }
 }
tryLocker()
bool QSharedMemoryPrivate::tryLocker (QSharedMemoryLocker * locker, const QString & function) inline
Definition at line 156 of file qsharedmemory_p.h.
{
         if (!locker->lock()) {
             errorString = QSharedMemory::tr("%1: unable to lock").arg(function);
             error = QSharedMemory::LockError;
             return false;
         }
         return true;
     }
Properties
error
QSharedMemory::SharedMemoryError QSharedMemoryPrivate::error
Definition at line 126 of file qsharedmemory_p.h.
Referenced by attach(), create(), detach(), handle(), and setErrorString().
errorString
QString QSharedMemoryPrivate::errorString
Definition at line 127 of file qsharedmemory_p.h.
Referenced by attach(), create(), detach(), handle(), and setErrorString().
hand
HANDLE QSharedMemoryPrivate::hand private
Definition at line 168 of file qsharedmemory_p.h.
Referenced by attach(), cleanHandle(), and detach().
key
QString QSharedMemoryPrivate::key
Definition at line 124 of file qsharedmemory_p.h.
Referenced by attach(), create(), detach(), handle(), makePlatformSafeKey(), and setErrorString().
lockedByMe
bool QSharedMemoryPrivate::lockedByMe
Definition at line 130 of file qsharedmemory_p.h.
memory
void* QSharedMemoryPrivate::memory
Definition at line 122 of file qsharedmemory_p.h.
Referenced by attach(), and detach().
nativeKey
QString QSharedMemoryPrivate::nativeKey
Definition at line 125 of file qsharedmemory_p.h.
Referenced by create(), detach(), and handle().
size
int QSharedMemoryPrivate::size
Definition at line 123 of file qsharedmemory_p.h.
Referenced by attach(), and detach().
systemSemaphore
QSystemSemaphore QSharedMemoryPrivate::systemSemaphore
Definition at line 129 of file qsharedmemory_p.h.
The documentation for this class was generated from the following files:
/src/corelib/kernel/qsharedmemory_p.h
/src/corelib/kernel/qsharedmemory.cpp
/src/corelib/kernel/qsharedmemory_unix.cpp
/src/corelib/kernel/qsharedmemory_win.cpp