Qt 4.8: QBitArray Class Reference
QBitArray Class Reference
The QBitArray class provides an array of bits.
#include <qbitarray.h>
Public Types
typedef QByteArray::DataPtr DataPtr
Public Functions
bool at (int i) const
Returns the value of the bit at index position i.
void clear ()
Clears the contents of the bit array and makes it empty.
void clearBit (int i)
Sets the bit at index position i to 0.
int count () const
Same as size().
int count (bool on) const
If on is true, this function returns the number of 1-bits stored in the bit array; otherwise the number of 0-bits is returned.
DataPtr & data_ptr ()
void detach ()
bool fill (bool val, int size=-1)
Sets every bit in the bit array to value, returning true if successful; otherwise returns false.
void fill (bool val, int first, int last)
Sets bits at index positions begin up to and excluding end to value.
bool isDetached () const
bool isEmpty () const
Returns true if this bit array has size 0; otherwise returns false.
bool isNull () const
Returns true if this bit array is null; otherwise returns false.
QBitArray & operator &= (const QBitArray &)
bool operator!= (const QBitArray &a) const
Returns true if other is not equal to this bit array; otherwise returns false.
QBitArray & operator= (const QBitArray &other)
Assigns other to this bit array and returns a reference to this bit array.
bool operator== (const QBitArray &a) const
Returns true if other is equal to this bit array; otherwise returns false.
QBitRef operator[] (int i)
Returns the bit at index position i as a modifiable reference.
bool operator[] (int i) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QBitRef operator[] (uint i)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool operator[] (uint i) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QBitArray & operator^= (const QBitArray &)
Performs the XOR operation between all bits in this bit array and other.
QBitArray & operator|= (const QBitArray &)
Performs the OR operation between all bits in this bit array and other.
QBitArray operator~ () const
Returns a bit array that contains the inverted bits of this bit array.
QBitArray ()
Constructs an empty bit array.
QBitArray (int size, bool val=false)
Constructs a bit array containing size bits.
QBitArray (const QBitArray &other)
Constructs a copy of other.
void resize (int size)
Resizes the bit array to size bits.
void setBit (int i)
Sets the bit at index position i to 1.
void setBit (int i, bool val)
Sets the bit at index position i to value.
int size () const
Returns the number of bits stored in the bit array.
void swap (QBitArray &other)
Swaps bit array other with this bit array.
bool testBit (int i) const
Returns true if the bit at index position i is 1; otherwise returns false.
bool toggleBit (int i)
Inverts the value of the bit at index position i, returning the previous value of that bit as either true (if it was set) or false (if it was unset).
void truncate (int pos)
Truncates the bit array at index position pos.
Properties
QByteArray d
Friends
Q_CORE_EXPORT QDataStream & operator<< (QDataStream &, const QBitArray &)
Writes bit array ba to stream out.
Q_CORE_EXPORT QDataStream & operator>> (QDataStream &, QBitArray &)
Reads a bit array into ba from stream in.
Q_CORE_EXPORT uint qHash (const QBitArray &key)
Related Functions
(Note that these are not member functions.)
QBitArray operator& (const QBitArray &a1, const QBitArray &a2)
Returns a bit array that is the AND of the bit arrays a1 and a2.
QBitArray operator^ (const QBitArray &a1, const QBitArray &a2)
Returns a bit array that is the XOR of the bit arrays a1 and a2.
QBitArray operator| (const QBitArray &a1, const QBitArray &a2)
Returns a bit array that is the OR of the bit arrays a1 and a2.
Detailed Description
The QBitArray class provides an array of bits.
Note
This class or function is reentrant.
A QBitArray is an array that gives access to individual bits and provides operators (AND, OR, XOR, and NOT) that work on entire arrays of bits. It uses implicit sharing (copy-on-write) to reduce memory usage and to avoid the needless copying of data.
The following code constructs a QBitArray containing 200 bits initialized to false (0):
QBitArray ba(200);
To initialize the bits to true, either pass true as second argument to the constructor, or call fill() later on.
QBitArray uses 0-based indexes, just like C++ arrays. To access the bit at a particular index position, you can use operator[](). On non-const bit arrays, operator[]() returns a reference to a bit that can be used on the left side of an assignment. For example:
QBitArray ba;
ba.resize(3);
ba[0] = true;
For technical reasons, it is more efficient to use testBit() and setBit() to access bits in the array than operator[](). For example:
QBitArray supports & (AND), | (OR), ^ (XOR), ~ (NOT), as well as &=, |=, and ^=. These operators work in the same way as the built-in C++ bitwise operators of the same name. For example:
QBitArray x(5);
x.setBit(3, true);
// x: [ 0, 0, 0, 1, 0 ]
QBitArray y(5);
y.setBit(4, true);
// y: [ 0, 0, 0, 0, 1 ]
x |= y;
// x: [ 0, 0, 0, 1, 1 ]
For historical reasons, QBitArray distinguishes between a null bit array and an empty bit array. A null bit array is a bit array that is initialized using QBitArray's default constructor. An empty bit array is any bit array with size 0. A null bit array is always empty, but an empty bit array isn't necessarily null:
QBitArray().isNull();           // returns true
QBitArray().isEmpty();          // returns true
QBitArray(0).isNull();          // returns false
QBitArray(0).isEmpty();         // returns true
QBitArray(3).isNull();          // returns false
QBitArray(3).isEmpty();         // returns false
All functions except isNull() treat null bit arrays the same as empty bit arrays; for example, QBitArray() compares equal to QBitArray(0). We recommend that you always use isEmpty() and avoid isNull().
See also
QByteArray, QVector
Definition at line 54 of file qbitarray.h.
Typedefs
DataPtr
QBitArray::DataPtr
Warning
This function is not part of the public interface.
Definition at line 113 of file qbitarray.h.
Constructors and Destructors
QBitArray() [1/3]
QBitArray::QBitArray () inline
Constructs an empty bit array.
See also
isEmpty()
Definition at line 62 of file qbitarray.h.
 {}
QBitArray() [2/3]
QBitArray::QBitArray (int size, bool value = false) explicit
Constructs a bit array containing size bits.
The bits are initialized with value, which defaults to false (0).
Definition at line 129 of file qbitarray.cpp.
 {
     if (!size) {
         d.resize(0);
         return;
     }
     d.resize(1 + (size+7)/8);
     uchar* c = reinterpret_cast<uchar*>(d.data());
     memset(c, value ? 0xff : 0, d.size());
     *c = d.size()*8 - size;
     if (value && size && size % 8)
         *(c+1+size/8) &= (1 << (size%8)) - 1;
 }
QBitArray() [3/3]
QBitArray::QBitArray (const QBitArray & other) inline
Constructs a copy of other.
This operation takes constant time, because QBitArray is implicitly shared. This makes returning a QBitArray from a function very fast. If a shared instance is modified, it will be copied (copy-on-write), and that takes linear time.
See also
operator=()
Definition at line 64 of file qbitarray.h.
 : d(other.d) {}
Functions
at()
bool QBitArray::at (int i) const inline
Returns the value of the bit at index position i.
i must be a valid index position in the bit array (i.e., 0 <= i < size()).
See also
operator[]()
Definition at line 146 of file qbitarray.h.
Referenced by QHeaderViewPrivate::isVisualIndexHidden().
 { return testBit(i); }
clear()
void QBitArray::clear () inline
Clears the contents of the bit array and makes it empty.
See also
resize(), isEmpty()
Definition at line 85 of file qbitarray.h.
Referenced by QXIMInputContext::ICData::clear(), and QHeaderViewPrivate::prepareSectionSelected().
 { d.clear(); }
clearBit()
void QBitArray::clearBit (int i) inline
Sets the bit at index position i to 0.
i must be a valid index position in the bit array (i.e., 0 <= i < size()).
See also
setBit(), toggleBit()
Definition at line 132 of file qbitarray.h.
Referenced by QLCDNumberPrivate::internalSetString(), and xic_draw_callback().
 { Q_ASSERT(uint(i) < uint(size()));
  *(reinterpret_cast<uchar*>(d.data())+1+(i>>3)) &= ~uchar(1 << (i & 7)); }
count() [1/2]
int QBitArray::count () const inline
Same as size().
Definition at line 74 of file qbitarray.h.
Referenced by QHeaderViewPrivate::_q_layoutChanged(), QHeaderViewPrivate::prepareSectionSelected(), and QHeaderView::sectionsInserted().
 { return (d.size() << 3) - *d.constData(); }
count() [2/2]
int QBitArray::count (bool on) const
If on is true, this function returns the number of 1-bits stored in the bit array; otherwise the number of 0-bits is returned.
Definition at line 166 of file qbitarray.cpp.
 {
     int numBits = 0;
     int len = size();
 #if 0
     for (int i = 0; i < len; ++i)
         numBits += testBit(i);
 #else
     // See http://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetParallel
     const quint8 *bits = reinterpret_cast<const quint8 *>(d.data()) + 1;
     while (len >= 32) {
         quint32 v = quint32(bits[0]) | (quint32(bits[1]) << 8) | (quint32(bits[2]) << 16) | (quint32(bits[3]) << 24);
         quint32 c = ((v & 0xfff) * Q_UINT64_C(0x1001001001001) & Q_UINT64_C(0x84210842108421)) % 0x1f;
         c += (((v & 0xfff000) >> 12) * Q_UINT64_C(0x1001001001001) & Q_UINT64_C(0x84210842108421)) % 0x1f;
         c += ((v >> 24) * Q_UINT64_C(0x1001001001001) & Q_UINT64_C(0x84210842108421)) % 0x1f;
         len -= 32;
         bits += 4;
         numBits += int(c);
     }
     while (len >= 24) {
         quint32 v = quint32(bits[0]) | (quint32(bits[1]) << 8) | (quint32(bits[2]) << 16);
         quint32 c =  ((v & 0xfff) * Q_UINT64_C(0x1001001001001) & Q_UINT64_C(0x84210842108421)) % 0x1f;
         c += (((v & 0xfff000) >> 12) * Q_UINT64_C(0x1001001001001) & Q_UINT64_C(0x84210842108421)) % 0x1f;
         len -= 24;
         bits += 3;
         numBits += int(c);
     }
     while (len >= 0) {
         if (bits[len / 8] & (1 << ((len - 1) & 7)))
             ++numBits;
         --len;
     }
 #endif
     return on ? numBits : size() - numBits;
 }
data_ptr()
DataPtr & QBitArray::data_ptr () inline
Warning
This function is not part of the public interface.
Definition at line 114 of file qbitarray.h.
 { return d.data_ptr(); }
detach()
void QBitArray::detach () inline
Warning
This function is not part of the public interface.
Definition at line 83 of file qbitarray.h.
 { d.detach(); }
fill() [1/2]
bool QBitArray::fill (bool value, int size = -1) inline
Sets every bit in the bit array to value, returning true if successful; otherwise returns false.
If size is different from -1 (the default), the bit array is resized to size beforehand.
Example:
QBitArray ba(8);
ba.fill(true);
// ba: [ 1, 1, 1, 1, 1, 1, 1, 1 ]
ba.fill(false, 2);
// ba: [ 0, 0 ]
See also
resize()
Definition at line 117 of file qbitarray.h.
Referenced by QHeaderViewPrivate::prepareSectionSelected(), and QHeaderView::sectionsInserted().
 { *this = QBitArray((asize < 0 ? this->size() : asize), aval); return true; }
fill() [2/2]
void QBitArray::fill (bool value, int begin, int end)
Sets bits at index positions begin up to and excluding end to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
begin and end must be a valid index position in the bit array (i.e., 0 <= begin <= size() and 0 <= end <= size()).
Definition at line 287 of file qbitarray.cpp.
 {
     while (begin < end && begin & 0x7)
         setBit(begin++, value);
     int len = end - begin;
     if (len <= 0)
         return;
     int s = len & ~0x7;
     uchar *c = reinterpret_cast<uchar*>(d.data());
     memset(c + (begin >> 3) + 1, value ? 0xff : 0, s >> 3);
     begin += s;
     while (begin < end)
         setBit(begin++, value);
 }
isDetached()
bool QBitArray::isDetached () const inline
Warning
This function is not part of the public interface.
Definition at line 84 of file qbitarray.h.
 { return d.isDetached(); }
isEmpty()
bool QBitArray::isEmpty () const inline
Returns true if this bit array has size 0; otherwise returns false.
See also
size()
Definition at line 78 of file qbitarray.h.
Referenced by QHeaderViewPrivate::isVisualIndexHidden(), QDeclarativeVMEMetaObject::metaCall(), QHeaderView::moveSection(), QDeclarativeVMEMetaObject::registerInterceptor(), and QHeaderViewPrivate::setVisualIndexHidden().
 { return d.isEmpty(); }
isNull()
bool QBitArray::isNull () const inline
Returns true if this bit array is null; otherwise returns false.
Example:
QBitArray().isNull();           // returns true
QBitArray(0).isNull();          // returns false
QBitArray(3).isNull();          // returns false
Qt makes a distinction between null bit arrays and empty bit arrays for historical reasons. For most applications, what matters is whether or not a bit array contains any data, and this can be determined using isEmpty().
See also
isEmpty()
Definition at line 79 of file qbitarray.h.
 { return d.isNull(); }
operator &=()
QBitArray& QBitArray::operator&= (const QBitArray &)
Referenced by fill().
operator!=()
bool QBitArray::operator!= (const QBitArray & other) const inline
Returns true if other is not equal to this bit array; otherwise returns false.
See also
operator==()
Definition at line 105 of file qbitarray.h.
 { return d != a.d; }
operator=()
QBitArray & QBitArray::operator= (const QBitArray & other) inline
Assigns other to this bit array and returns a reference to this bit array.
Definition at line 65 of file qbitarray.h.
 { d = other.d; return *this; }
operator==()
bool QBitArray::operator== (const QBitArray & other) const inline
Returns true if other is equal to this bit array; otherwise returns false.
See also
operator!=()
Definition at line 104 of file qbitarray.h.
 { return d == a.d; }
operator[]() [1/4]
QBitRef QBitArray::operator[] (int i) inline
Returns the bit at index position i as a modifiable reference.
i must be a valid index position in the bit array (i.e., 0 <= i < size()).
Example:
QBitArray a(3);
a[0] = false;
a[1] = true;
a[2] = a[0] ^ a[1];
The return value is of type QBitRef, a helper class for QBitArray. When you get an object of type QBitRef, you can assign to it, and the assignment will apply to the bit in the QBitArray from which you got the reference.
The functions testBit(), setBit(), and clearBit() are slightly faster.
See also
at(), testBit(), setBit(), clearBit()
Definition at line 162 of file qbitarray.h.
 { Q_ASSERT(i >= 0); return QBitRef(*this, i); }
operator[]() [2/4]
bool QBitArray::operator[] (int i) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 144 of file qbitarray.h.
 { return testBit(i); }
operator[]() [3/4]
QBitRef QBitArray::operator[] (uint i) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 164 of file qbitarray.h.
 { return QBitRef(*this, i); }
operator[]() [4/4]
bool QBitArray::operator[] (uint i) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 145 of file qbitarray.h.
 { return testBit(i); }
operator^=()
QBitArray & QBitArray::operator^= (const QBitArray & other)
Performs the XOR operation between all bits in this bit array and other.
Assigns the result to this bit array, and returns a reference to it.
The result has the length of the longest of the two bit arrays, with any missing bits (if one array is shorter than the other) taken to be 0.
Example:
QBitArray a(3);
QBitArray b(2);
a[0] = 1; a[1] = 0; a[2] = 1;   // a: [ 1, 0, 1 ]
b[0] = 1; b[1] = 0;             // b: [ 1, 1 ]
a ^= b;                         // a: [ 0, 1, 1 ]
See also
operator^(), operator&=(), operator|=(), operator~()
Definition at line 580 of file qbitarray.cpp.
 {
     resize(qMax(size(), other.size()));
     uchar *a1 = reinterpret_cast<uchar*>(d.data()) + 1;
     const uchar *a2 = reinterpret_cast<const uchar *>(other.d.constData()) + 1;
     int n = other.d.size() - 1;
     while (n-- > 0)
         *a1++ ^= *a2++;
     return *this;
 }
operator|=()
QBitArray & QBitArray::operator|= (const QBitArray & other)
Performs the OR operation between all bits in this bit array and other.
Assigns the result to this bit array, and returns a reference to it.
The result has the length of the longest of the two bit arrays, with any missing bits (if one array is shorter than the other) taken to be 0.
Example:
QBitArray a(3);
QBitArray b(2);
a[0] = 1; a[1] = 0; a[2] = 1;   // a: [ 1, 0, 1 ]
b[0] = 1; b[1] = 0;             // b: [ 1, 1 ]
a |= b;                         // a: [ 1, 1, 1 ]
See also
operator|(), operator&=(), operator^=(), operator~()
Definition at line 554 of file qbitarray.cpp.
 {
     resize(qMax(size(), other.size()));
     uchar *a1 = reinterpret_cast<uchar*>(d.data()) + 1;
     const uchar *a2 = reinterpret_cast<const uchar *>(other.d.constData()) + 1;
     int n = other.d.size() - 1;
     while (n-- > 0)
         *a1++ |= *a2++;
     return *this;
 }
operator~()
QBitArray QBitArray::operator~ () const
Returns a bit array that contains the inverted bits of this bit array.
Example:
QBitArray a(3);
QBitArray b;
a[0] = 1; a[1] = 0; a[2] = 1;   // a: [ 1, 0, 1 ]
b = ~a;                         // b: [ 0, 1, 0 ]
See also
operator&(), operator|(), operator^()
Definition at line 601 of file qbitarray.cpp.
 {
     int sz = size();
     QBitArray a(sz);
     const uchar *a1 = reinterpret_cast<const uchar *>(d.constData()) + 1;
     uchar *a2 = reinterpret_cast<uchar*>(a.d.data()) + 1;
     int n = d.size() - 1;
     while (n-- > 0)
         *a2++ = ~*a1++;
     if (sz && sz%8)
         *(a2-1) &= (1 << (sz%8)) - 1;
     return a;
 }
resize()
void QBitArray::resize (int size)
Resizes the bit array to size bits.
If size is greater than the current size, the bit array is extended to make it size bits with the extra bits added to the end. The new bits are initialized to false (0).
If size is less than the current size, bits are removed from the end.
See also
size()
Definition at line 214 of file qbitarray.cpp.
Referenced by QAbstractItemModel::decodeData(), QStandardItemModel::dropMimeData(), fill(), operator^=(), operator|=(), QDeclarativeVMEMetaObject::QDeclarativeVMEMetaObject(), QDeclarativeVMEMetaObject::registerInterceptor(), registerInterface(), registerType(), QHeaderView::sectionsInserted(), and xic_draw_callback().
 {
     if (!size) {
         d.resize(0);
     } else {
         int s = d.size();
         d.resize(1 + (size+7)/8);
         uchar* c = reinterpret_cast<uchar*>(d.data());
         if (size > (s << 3))
             memset(c + s, 0, d.size() - s);
         else if ( size % 8)
             *(c+1+size/8) &= (1 << (size%8)) - 1;
         *c = d.size()*8 - size;
     }
 }
setBit() [1/2]
void QBitArray::setBit (int i) inline
Sets the bit at index position i to 1.
i must be a valid index position in the bit array (i.e., 0 <= i < size()).
See also
clearBit(), toggleBit()
Definition at line 128 of file qbitarray.h.
Referenced by QHeaderViewPrivate::_q_layoutChanged(), QDeclarativeVMEMetaObject::connectAlias(), QAbstractItemModel::decodeData(), QTableViewPrivate::drawAndClipSpans(), QStandardItemModel::dropMimeData(), fill(), QGridLayoutEngine::fillRowData(), QLCDNumberPrivate::internalSetString(), QRegExpMatchState::matchHere(), QHeaderView::moveSection(), QBitRef::operator=(), QTableView::paintEvent(), QDeclarativeVMEMetaObject::registerInterceptor(), registerInterface(), registerType(), QHeaderView::sectionsInserted(), QHeaderViewPrivate::setVisualIndexHidden(), and xic_draw_callback().
 { Q_ASSERT(uint(i) < uint(size()));
  *(reinterpret_cast<uchar*>(d.data())+1+(i>>3)) |= uchar(1 << (i & 7)); }
setBit() [2/2]
void QBitArray::setBit (int i, bool value) inline
Sets the bit at index position i to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 136 of file qbitarray.h.
 { if (val) setBit(i); else clearBit(i); }
size()
int QBitArray::size () const inline
Returns the number of bits stored in the bit array.
See also
resize()
Definition at line 73 of file qbitarray.h.
Referenced by count(), fill(), QDeclarativeMetaType::isInterface(), QDeclarativeMetaType::isList(), QDeclarativeMetaType::isQObject(), operator^=(), operator|=(), operator~(), QTableView::paintEvent(), QBitArray(), qHash(), registerInterface(), registerType(), resize(), and xic_draw_callback().
 { return (d.size() << 3) - *d.constData(); }
swap()
void QBitArray::swap (QBitArray & other) inline
Swaps bit array other with this bit array.
Since
4.8
This operation is very fast and never fails.
Definition at line 71 of file qbitarray.h.
 { qSwap(d, other.d); }
testBit()
bool QBitArray::testBit (int i) const inline
Returns true if the bit at index position i is 1; otherwise returns false.
i must be a valid index position in the bit array (i.e., 0 <= i < size()).
See also
setBit(), clearBit()
Definition at line 124 of file qbitarray.h.
Referenced by QHeaderViewPrivate::_q_layoutChanged(), QDeclarativeVMEMetaObject::connectAlias(), count(), QAbstractItemModel::decodeData(), QLCDNumberPrivate::drawString(), QStandardItemModel::dropMimeData(), QGridLayoutEngine::fillRowData(), QLCDNumberPrivate::internalSetString(), QDeclarativeMetaType::isInterface(), QDeclarativeMetaType::isList(), QDeclarativeMetaType::isQObject(), QRegExpMatchState::matchHere(), QDeclarativeVMEMetaObject::metaCall(), QHeaderView::moveSection(), QBitRef::operator bool(), QBitRef::operator!(), QTableView::paintEvent(), QLCDNumber::setDigitCount(), QDeclarativeMetaType::typeCategory(), and xic_draw_callback().
 { Q_ASSERT(uint(i) < uint(size()));
  return (*(reinterpret_cast<const uchar*>(d.constData())+1+(i>>3)) & (1 << (i & 7))) != 0; }
toggleBit()
bool QBitArray::toggleBit (int i) inline
Inverts the value of the bit at index position i, returning the previous value of that bit as either true (if it was set) or false (if it was unset).
If the previous value was 0, the new value will be 1. If the previous value was 1, the new value will be 0.
i must be a valid index position in the bit array (i.e., 0 <= i < size()).
See also
setBit(), clearBit()
Definition at line 139 of file qbitarray.h.
 { Q_ASSERT(uint(i) < uint(size()));
  uchar b = uchar(1<<(i&7)); uchar* p = reinterpret_cast<uchar*>(d.data())+1+(i>>3);
  uchar c = uchar(*p&b); *p^=b; return c!=0; }
truncate()
void QBitArray::truncate (int pos) inline
Truncates the bit array at index position pos.
If pos is beyond the end of the array, nothing happens.
See also
resize()
Definition at line 110 of file qbitarray.h.
 { if (pos < size()) resize(pos); }
Friends and Related Functions
operator&()
QBitArray operator & (const QBitArray & a1, const QBitArray & a2) related
Returns a bit array that is the AND of the bit arrays a1 and a2.
The result has the length of the longest of the two bit arrays, with any missing bits (if one array is shorter than the other) taken to be 0.
Example:
QBitArray a(3);
QBitArray b(2);
QBitArray c;
a[0] = 1; a[1] = 0; a[2] = 1;   // a: [ 1, 0, 1 ]
b[0] = 1; b[1] = 0;             // b: [ 1, 1 ]
c = a & b;                      // c: [ 1, 0, 0 ]
See also
QBitArray::operator&=(), operator|(), operator^()
Definition at line 636 of file qbitarray.cpp.
 {
     QBitArray tmp = a1;
     tmp &= a2;
     return tmp;
 }
operator<<
QDataStream & operator<< (QDataStream & out, const QBitArray & ba) friend
Writes bit array ba to stream out.
See also
Format of the QDataStream operators
Definition at line 767 of file qbitarray.cpp.
 {
     quint32 len = ba.size();
     out << len;
     if (len > 0)
         out.writeRawData(ba.d.constData() + 1, ba.d.size() - 1);
     return out;
 }
operator>>
QDataStream & operator>> (QDataStream & in, QBitArray & ba) friend
Reads a bit array into ba from stream in.
See also
Format of the QDataStream operators
Definition at line 787 of file qbitarray.cpp.
 {
     ba.clear();
     quint32 len;
     in >> len;
     if (len == 0) {
     ba.clear();
     return in;
     }
     const quint32 Step = 8 * 1024 * 1024;
     quint32 totalBytes = (len + 7) / 8;
     quint32 allocated = 0;
     while (allocated < totalBytes) {
         int blockSize = qMin(Step, totalBytes - allocated);
         ba.d.resize(allocated + blockSize + 1);
         if (in.readRawData(ba.d.data() + 1 + allocated, blockSize) != blockSize) {
             ba.clear();
             in.setStatus(QDataStream::ReadPastEnd);
             return in;
         }
         allocated += blockSize;
     }
     int paddingMask = ~((0x1 << (len & 0x7)) - 1);
     if (paddingMask != ~0x0 && (ba.d.constData()[ba.d.size() - 1] & paddingMask)) {
         ba.clear();
         in.setStatus(QDataStream::ReadCorruptData);
         return in;
     }
     *ba.d.data() = ba.d.size() * 8 - len;
     return in;
 }
operator^()
QBitArray operator^ (const QBitArray & a1, const QBitArray & a2) related
Returns a bit array that is the XOR of the bit arrays a1 and a2.
The result has the length of the longest of the two bit arrays, with any missing bits (if one array is shorter than the other) taken to be 0.
Example:
QBitArray a(3);
QBitArray b(2);
QBitArray c;
a[0] = 1; a[1] = 0; a[2] = 1;   // a: [ 1, 0, 1 ]
b[0] = 1; b[1] = 0;             // b: [ 1, 1 ]
c = a ^ b;                      // c: [ 0, 1, 1 ]
See also
QBitArray::operator^=(), operator&(), operator|()
Definition at line 688 of file qbitarray.cpp.
 {
     QBitArray tmp = a1;
     tmp ^= a2;
     return tmp;
 }
operator|()
QBitArray operator| (const QBitArray & a1, const QBitArray & a2) related
Returns a bit array that is the OR of the bit arrays a1 and a2.
The result has the length of the longest of the two bit arrays, with any missing bits (if one array is shorter than the other) taken to be 0.
Example:
QBitArray a(3);
QBitArray b(2);
QBitArray c;
a[0] = 1; a[1] = 0; a[2] = 1;   // a: [ 1, 0, 1 ]
b[0] = 1; b[1] = 0;             // b: [ 1, 1 ]
c = a | b;                      // c: [ 1, 1, 1 ]
See also
QBitArray::operator|=(), operator&(), operator^()
Definition at line 662 of file qbitarray.cpp.
Referenced by QRect::QRect().
 {
     QBitArray tmp = a1;
     tmp |= a2;
     return tmp;
 }
qHash
Q_CORE_EXPORT uint qHash (const QBitArray & key) friend
Definition at line 107 of file qhash.cpp.
 {
     int m = bitArray.d.size() - 1;
     uint result = hash(reinterpret_cast<const uchar *>(bitArray.d.constData()), qMax(0, m));
     // deal with the last 0 to 7 bits manually, because we can't trust that
     // the padding is initialized to 0 in bitArray.d
     int n = bitArray.size();
     if (n & 0x7)
         result = ((result << 4) + bitArray.d.at(m)) & ((1 << n) - 1);
     return result;
 }
Properties
d
QByteArray QBitArray::d private
Definition at line 59 of file qbitarray.h.
Referenced by count(), fill(), operator!=(), operator=(), operator==(), operator^=(), operator|=(), operator~(), QBitArray(), qHash(), resize(), and swap().
The documentation for this class was generated from the following files:
/src/corelib/tools/qbitarray.h
/src/corelib/tools/qbitarray.cpp