Qt 4.8: QAxWidget Class Reference
QAxWidget Class Reference
The QAxWidget class is a QWidget that wraps an ActiveX control.
#include <qaxwidget.h>
Public Functions
const char * className () const
void clear ()
Shuts down the ActiveX control.
virtual QAxAggregated * createAggregate ()
Reimplement this function when you want to implement additional COM interfaces for the client site of the ActiveX control, or when you want to provide alternative implementations of COM interfaces.
bool doVerb (const QString &verb)
Requests the ActiveX control to perform the action verb.
const QMetaObject * metaObject () const
QSize minimumSizeHint () const
Reimplemented Function
QAxWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Creates an empty QAxWidget widget and propagates parent and f to the QWidget constructor.
QAxWidget (const QString &c, QWidget *parent=0, Qt::WindowFlags f=0)
Creates an QAxWidget widget and initializes the ActiveX control c.
QAxWidget (IUnknown *iface, QWidget *parent=0, Qt::WindowFlags f=0)
Creates a QAxWidget that wraps the COM object referenced by iface.
QObject * qObject () const
int qt_metacall (QMetaObject::Call, int, void **)
void * qt_metacast (const char *)
QSize sizeHint () const
Reimplemented Function
~QAxWidget ()
Shuts down the ActiveX control and destroys the QAxWidget widget, cleaning up all allocated resources.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Public Functions inherited from QAxBase
QVariant asVariant () const
Returns a QVariant that wraps the COM object.
QString control () const
the name of the COM object wrapped by this QAxBase object.
void disableClassInfo ()
Disables the class info generation for this ActiveX container.
void disableEventSink ()
Disables the event sink implementation for this ActiveX container.
void disableMetaObject ()
Disables the meta object generation for this ActiveX container.
QVariant dynamicCall (const char *name, const QVariant &v1=QVariant(), const QVariant &v2=QVariant(), const QVariant &v3=QVariant(), const QVariant &v4=QVariant(), const QVariant &v5=QVariant(), const QVariant &v6=QVariant(), const QVariant &v7=QVariant(), const QVariant &v8=QVariant())
Calls the COM object's method function, passing the parameters var1, var1, var2, var3, var4, var5, var6, var7 and var8, and returns the value returned by the method, or an invalid QVariant if the method does not return a value or when the function call failed.
QVariant dynamicCall (const char *name, QList< QVariant > &vars)
Calls the COM object's method function, passing the parameters in vars, and returns the value returned by the method.
QString generateDocumentation ()
Returns a rich text string with documentation for the wrapped COM object.
bool isNull () const
Returns true if there is no COM object loaded by this wrapper; otherwise return false.
PropertyBag propertyBag () const
Returns a name:value map of all the properties exposed by the COM object.
virtual bool propertyWritable (const char *) const
Returns true if the property prop is writable; otherwise returns false.
QAxBase (IUnknown *iface=0)
Creates a QAxBase object that wraps the COM object iface.
long queryInterface (const QUuid &, void **) const
Requests the interface uuid from the COM object and sets the value of iface to the provided interface, or to 0 if the requested interface could not be provided.
QAxObject * querySubObject (const char *name, const QVariant &v1=QVariant(), const QVariant &v2=QVariant(), const QVariant &v3=QVariant(), const QVariant &v4=QVariant(), const QVariant &v5=QVariant(), const QVariant &v6=QVariant(), const QVariant &v7=QVariant(), const QVariant &v8=QVariant())
Returns a pointer to a QAxObject wrapping the COM object provided by the method or property name, passing passing the parameters var1, var1, var2, var3, var4, var5, var6, var7 and var8.
QAxObject * querySubObject (const char *name, QList< QVariant > &vars)
The QVariant objects in vars are updated when the method has out-parameters.
bool setControl (const QString &)
void setPropertyBag (const PropertyBag &)
Sets the properties of the COM object to the corresponding values in bag.
virtual void setPropertyWritable (const char *, bool)
Sets the property prop to writable if ok is true, otherwise sets prop to be read-only.
QStringList verbs () const
Returns the list of verbs that the COM object can execute.
virtual ~QAxBase ()
Shuts down the COM object and destroys the QAxBase object.
Protected Functions
void changeEvent (QEvent *e)
Reimplemented Function
void connectNotify (const char *signal)
Reimplemented Function
virtual bool createHostWindow (bool)
Creates the client site for the ActiveX control, and returns true if the control could be embedded successfully, otherwise returns false.
bool createHostWindow (bool, const QByteArray &)
Creates the client site for the ActiveX control, and returns true if the control could be embedded successfully, otherwise returns false.
bool initialize (IUnknown **)
Calls QAxBase::initialize(ptr), and embeds the control in this widget by calling createHostWindow(false) if successful.
void resizeEvent (QResizeEvent *)
Reimplemented Function
virtual bool translateKeyEvent (int message, int keycode) const
Reimplement this function to pass certain key events to the ActiveX control.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool event (QEvent *)
This is the main event handler; it handles event event.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyPressEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key press events for the widget.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Protected Functions inherited from QAxBase
void connectNotify ()
Connects to all event interfaces of the object.
long indexOfVerb (const QString &verb) const
bool initializeActive (IUnknown **ptr)
Connects to an active instance running on the current machine, and returns the IUnknown interface to the running object in ptr.
void initializeFrom (QAxBase *that)
Used by subclasses generated with dumpcpp to implement cast-operators.
bool initializeFromFile (IUnknown **ptr)
Creates the COM object handling the filename in the control property, and returns the IUnknown interface to the object in ptr.
bool initializeLicensed (IUnknown **ptr)
Creates an instance of a licensed control, and returns the IUnknown interface to the object in ptr.
bool initializeRemote (IUnknown **ptr)
Creates the instance on a remote server, and returns the IUnknown interface to the object in ptr.
void internalRelease ()
Used by subclasses generated with dumpcpp to balance reference count.
Private Functions
const QMetaObject * parentMetaObject () const
Properties
QAxClientSite * container
Static Private Attributes
static QMetaObject staticMetaObject
Friends
class QAxClientSite
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Types inherited from QAxBase
typedef QMap< QString, QVariant > PropertyBag
A QMap<QString,QVariant> that can store properties as name:value pairs.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Signals inherited from QAxBase
void exception (int, const QString &, const QString &, const QString &)
This signal is emitted when the COM object throws an exception while called using the OLE automation interface IDispatch.
void propertyChanged (const QString &)
If the COM object supports property notification, this signal gets emitted when the property called name is changed.
void signal (const QString &, int, void *)
This generic signal gets emitted when the COM object issues the event name.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QAxWidget class is a QWidget that wraps an ActiveX control.
Attention
Module: QAxContainer
A QAxWidget can be instantiated as an empty object, with the name of the ActiveX control it should wrap, or with an existing interface pointer to the ActiveX control. The ActiveX control's properties, methods and events which only use QAxBase supported data types, become available as Qt properties, slots and signals. The base class QAxBase provides an API to access the ActiveX directly through the IUnknown pointer.
QAxWidget is a QWidget and can mostly be used as such, e.g. it can be organized in a widget hierarchy and layouts or act as an event filter. Standard widget properties, e.g. enabled are supported, but it depends on the ActiveX control to implement support for ambient properties like e.g. palette or font. QAxWidget tries to provide the necessary hints.
However, you cannot reimplement Qt-specific event handlers like mousePressEvent or keyPressEvent and expect them to be called reliably. The embedded control covers the QAxWidget completely, and usually handles the user interface itself. Use control-specific APIs (i.e. listen to the signals of the control), or use standard COM techniques like window procedure subclassing.
QAxWidget also inherits most of its ActiveX-related functionality from QAxBase, notably dynamicCall() and querySubObject().
Warning
You can subclass QAxWidget, but you cannot use the Q_OBJECT macro in the subclass (the generated moc-file will not compile), so you cannot add further signals, slots or properties. This limitation is due to the metaobject information generated in runtime. To work around this problem, aggregate the QAxWidget as a member of the QObject subclass.
See also
QAxBase, QAxObject, QAxScript, {ActiveQt Framework}
Definition at line 60 of file qaxwidget.h.
Constructors and Destructors
QAxWidget() [1/3]
QAxWidget::QAxWidget (QWidget * parent = 0, Qt::WindowFlags f = 0)
Creates an empty QAxWidget widget and propagates parent and f to the QWidget constructor.
To initialize a control, call setControl().
Definition at line 1891 of file qaxwidget.cpp.
Referenced by qObject().
 : QWidget(parent, f), container(0)
 {
 }
QAxWidget() [2/3]
QAxWidget::QAxWidget (const QString & c, QWidget * parent = 0, Qt::WindowFlags f = 0)
Creates an QAxWidget widget and initializes the ActiveX control c.
parent and f are propagated to the QWidget contructor.
See also
setControl()
Definition at line 1902 of file qaxwidget.cpp.
 : QWidget(parent, f), container(0)
 {
     setControl(c);
 }
QAxWidget() [3/3]
QAxWidget::QAxWidget (IUnknown * iface, QWidget * parent = 0, Qt::WindowFlags f = 0)
Creates a QAxWidget that wraps the COM object referenced by iface.
parent and f are propagated to the QWidget contructor.
Definition at line 1912 of file qaxwidget.cpp.
 : QWidget(parent, f), QAxBase(iface), container(0)
 {
 }
~QAxWidget()
QAxWidget::~QAxWidget ()
Shuts down the ActiveX control and destroys the QAxWidget widget, cleaning up all allocated resources.
See also
clear()
Definition at line 1923 of file qaxwidget.cpp.
Referenced by qObject().
 {
     if (container)
         container->reset(this);
     clear();
 }
Functions
changeEvent()
void QAxWidget::changeEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2164 of file qaxwidget.cpp.
Referenced by qObject().
 {
     if (isNull() || !container)
         return;
     switch (e->type()) {
     case QEvent::EnabledChange:
         container->emitAmbientPropertyChange(DISPID_AMBIENT_UIDEAD);
         break;
     case QEvent::FontChange:
         container->emitAmbientPropertyChange(DISPID_AMBIENT_FONT);
         break;
     case QEvent::PaletteChange:
         container->emitAmbientPropertyChange(DISPID_AMBIENT_BACKCOLOR);
         container->emitAmbientPropertyChange(DISPID_AMBIENT_FORECOLOR);
         break;
     case QEvent::ActivationChange:
         container->windowActivationChange();
         break;
     default:
         break;
     }
 }
className()
const char * QAxWidget::className () const virtual
Warning
This function is not part of the public interface.
Implements QAxBase.
Definition at line 2117 of file qaxwidget.cpp.
Referenced by qObject().
 {
     return "QAxWidget";
 }
clear()
void QAxWidget::clear () virtual
Shuts down the ActiveX control.
Reimplemented Function
Reimplemented from QAxBase.
Definition at line 2030 of file qaxwidget.cpp.
Referenced by qObject(), and ~QAxWidget().
 {
     if (isNull())
         return;
     if (!control().isEmpty()) {
 #if !defined(Q_OS_WINCE)
         ATOM filter_ref = FindAtom(qaxatom);
         if (filter_ref)
             DeleteAtom(filter_ref);
         filter_ref = FindAtom(qaxatom);
         if (!filter_ref) {
 #else
         if (!filter_ref && !--filter_ref) {
 #endif
             QAbstractEventDispatcher::instance()->setEventFilter(previous_filter);
             previous_filter = 0;
         }
     }
     if (container)
         container->deactivate();
     QAxBase::clear();
     setFocusPolicy(Qt::NoFocus);
     if (container) {
         container->releaseAll();
         container->Release();
     }
     container = 0;
 }
connectNotify()
void QAxWidget::connectNotify (const char * signal) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 2200 of file qaxwidget.cpp.
 {
     QAxBase::connectNotify();
 }
createAggregate()
QAxAggregated * QAxWidget::createAggregate () virtual
Reimplement this function when you want to implement additional COM interfaces for the client site of the ActiveX control, or when you want to provide alternative implementations of COM interfaces.
Return a new object of a QAxAggregated subclass.
The default implementation returns the null pointer.
Definition at line 2017 of file qaxwidget.cpp.
Referenced by QAxClientSite::QAxClientSite(), and qObject().
 {
     return 0;
 }
createHostWindow() [1/2]
bool QAxWidget::createHostWindow (bool initialized) protected virtual
Creates the client site for the ActiveX control, and returns true if the control could be embedded successfully, otherwise returns false.
If initialized is true the control has already been initialized.
This function is called by initialize(). If you reimplement initialize to customize the actual control instantiation, call this function in your reimplementation to have the control embedded by the default client side. Creates the client site for the ActiveX control, and returns true if the control could be embedded successfully, otherwise returns false.
Definition at line 1962 of file qaxwidget.cpp.
Referenced by initialize(), and qObject().
 {
     return createHostWindow(initialized, QByteArray());
 }
createHostWindow() [2/2]
bool QAxWidget::createHostWindow (bool initialized, const QByteArray & data) protected
Creates the client site for the ActiveX control, and returns true if the control could be embedded successfully, otherwise returns false.
Since
4.4
If initialized is false the control will be initialized using the data. The control will be initialized through either IPersistStreamInit or IPersistStorage interface.
If the control needs to be initialized using custom data, call this function in your reimplementation of initialize(). This function is not called by the default implementation of initialize().
Definition at line 1983 of file qaxwidget.cpp.
 {
 #ifdef QT3_SUPPORT
     QApplication::sendPostedEvents(0, QEvent::ChildInserted);
 #endif
     container = new QAxClientSite(this);
     container->activateObject(initialized, data);
 #if !defined(Q_OS_WINCE)
     ATOM filter_ref = FindAtom(qaxatom);
 #endif
     if (!filter_ref)
         previous_filter = QAbstractEventDispatcher::instance()->setEventFilter(axc_FilterProc);
 #if !defined(Q_OS_WINCE)
     AddAtom(qaxatom);
 #else
     ++filter_ref;
 #endif
     if (parentWidget())
         QApplication::postEvent(parentWidget(), new QEvent(QEvent::LayoutRequest));
     return true;
 }
doVerb()
bool QAxWidget::doVerb (const QString & verb)
Requests the ActiveX control to perform the action verb.
Since
4.1
The possible verbs are returned by verbs().
The function returns true if the object could perform the action, otherwise returns false.
Definition at line 2073 of file qaxwidget.cpp.
Referenced by qObject().
 {
     if (!verbs().contains(verb))
         return false;
     HRESULT hres = container->doVerb(indexOfVerb(verb));
     return hres == S_OK;
 }
initialize()
bool QAxWidget::initialize (IUnknown ** ptr) protected virtual
Calls QAxBase::initialize(ptr), and embeds the control in this widget by calling createHostWindow(false) if successful.
Since
4.2
To initialize the control before it is activated, reimplement this function and add your initialization code before you call createHostWindow(true).
Reimplemented from QAxBase.
Definition at line 1943 of file qaxwidget.cpp.
Referenced by qObject().
 {
     if (!QAxBase::initialize(ptr))
         return false;
     return createHostWindow(false); // assume that control is not initialized
 }
metaObject()
const QMetaObject * QAxWidget::metaObject () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QAxBase.
Definition at line 2091 of file qaxwidget.cpp.
 {
     return QAxBase::metaObject();
 }
minimumSizeHint()
QSize QAxWidget::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2150 of file qaxwidget.cpp.
Referenced by qObject().
 {
     if (container) {
         QSize sh = container->minimumSizeHint();
         if (sh.isValid())
             return sh;
     }
     return QWidget::minimumSizeHint();
 }
parentMetaObject()
const QMetaObject * QAxWidget::parentMetaObject () const private virtual
Warning
This function is not part of the public interface.
Implements QAxBase.
Definition at line 2099 of file qaxwidget.cpp.
 {
     return &QWidget::staticMetaObject;
 }
qObject()
QObject * QAxWidget::qObject () const inline virtual
Warning
This function is not part of the public interface.
Implements QAxBase.
Definition at line 66 of file qaxwidget.h.
 { return (QWidget*)this; }
qt_metacall()
int QAxWidget::qt_metacall (QMetaObject::Call call, int id, void ** v) virtual
Warning
This function is not part of the public interface.
Reimplemented from QAxBase.
Definition at line 2125 of file qaxwidget.cpp.
 {
     id = QWidget::qt_metacall(call, id, v);
     if (id < 0)
         return id;
     return QAxBase::qt_metacall(call, id, v);
 }
qt_metacast()
void * QAxWidget::qt_metacast (const char * cname)
Warning
This function is not part of the public interface.
Definition at line 2107 of file qaxwidget.cpp.
Referenced by qobject_cast< QAxWidget * >().
 {
     if (!qstrcmp(cname, "QAxWidget")) return (void*)this;
     if (!qstrcmp(cname, "QAxBase")) return (QAxBase*)this;
     return QWidget::qt_metacast(cname);
 }
resizeEvent()
void QAxWidget::resizeEvent (QResizeEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2191 of file qaxwidget.cpp.
Referenced by qObject().
 {
     if (container)
         container->resize(size());
 }
sizeHint()
QSize QAxWidget::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2136 of file qaxwidget.cpp.
Referenced by qObject().
 {
     if (container) {
         QSize sh = container->sizeHint();
         if (sh.isValid())
             return sh;
     }
     return QWidget::sizeHint();
 }
translateKeyEvent()
bool QAxWidget::translateKeyEvent (int message, int keycode) const protected virtual
Reimplement this function to pass certain key events to the ActiveX control.
message is the Window message identifier specifying the message type (ie. WM_KEYDOWN), and keycode is the virtual keycode (ie. VK_TAB).
If the function returns true the key event is passed on to the ActiveX control, which then either processes the event or passes the event on to Qt.
If the function returns false the processing of the key event is ignored by ActiveQt, ie. the ActiveX control might handle it or not.
The default implementation returns true for the following cases:
WM_SYSKEYDOWN WM_SYSKEYUP WM_KEYDOWN
All keycodes VK_MENU VK_TAB, VK_DELETE and all non-arrow-keys in combination with VK_SHIFT, VK_CONTROL or VK_MENU
This table is the result of experimenting with popular ActiveX controls, ie. Internet Explorer and Microsoft Office applications, but for some controls it might require modification.
Definition at line 2238 of file qaxwidget.cpp.
Referenced by qObject().
 {
     bool translate = false;
     switch (message) {
     case WM_SYSKEYDOWN:
         translate = true;
         break;
     case WM_KEYDOWN:
         translate = keycode == VK_TAB
             || keycode == VK_DELETE;
         if (!translate) {
             int state = 0;
             if (GetKeyState(VK_SHIFT) < 0)
                 state |= 0x01;
             if (GetKeyState(VK_CONTROL) < 0)
                 state |= 0x02;
             if (GetKeyState(VK_MENU) < 0)
                 state |= 0x04;
             if (state) {
                 state = keycode < VK_LEFT || keycode > VK_DOWN;
             }
             translate = state;
         }
         break;
     case WM_SYSKEYUP:
         translate = keycode == VK_MENU;
         break;
     }
     return translate;
 }
Friends and Related Functions
QAxClientSite
friend class QAxClientSite friend
Definition at line 94 of file qaxwidget.h.
Referenced by createHostWindow().
Properties
container
QAxClientSite* QAxWidget::container private
Definition at line 95 of file qaxwidget.h.
Referenced by changeEvent(), clear(), createHostWindow(), doVerb(), minimumSizeHint(), resizeEvent(), sizeHint(), and ~QAxWidget().
staticMetaObject
QMetaObject QAxWidget::staticMetaObject static private
Definition at line 98 of file qaxwidget.h.
The documentation for this class was generated from the following files:
/src/activeqt/container/qaxwidget.h
/src/activeqt/container/qaxwidget.cpp