Qt 4.8: QFontEngineFTRawFont Class Reference
QFontEngineFTRawFont Class Reference
Public Functions
bool initFromData (const QByteArray &fontData)
QFontEngineFTRawFont (const QFontDef &fontDef)
void updateFamilyNameAndStyle ()
Public Functions inherited from QFontEngineX11FT
QFontEngine * cloneWithSize (qreal pixelSize) const
QFontEngineX11FT (const QFontDef &fontDef)
QFontEngineX11FT (FcPattern *pattern, const QFontDef &fd, int screen)
~QFontEngineX11FT ()
Public Functions inherited from QFontEngineFT
virtual void addGlyphsToPath (glyph_t *glyphs, QFixedPoint *positions, int nglyphs, QPainterPath *path, QTextItem::RenderFlags flags)
virtual void addOutlineToPath (qreal x, qreal y, const QGlyphLayout &glyphs, QPainterPath *path, QTextItem::RenderFlags flags)
virtual glyph_metrics_t alphaMapBoundingBox (glyph_t glyph, QFixed subPixelPosition, const QTransform &matrix, QFontEngine::GlyphFormat format)
virtual QImage alphaMapForGlyph (glyph_t g)
virtual QImage alphaMapForGlyph (glyph_t, QFixed)
virtual QImage alphaRGBMapForGlyph (glyph_t, QFixed subPixelPosition, int margin, const QTransform &t)
virtual QFixed ascent () const
virtual QFixed averageCharWidth () const
virtual glyph_metrics_t boundingBox (const QGlyphLayout &glyphs)
virtual glyph_metrics_t boundingBox (glyph_t glyph)
virtual glyph_metrics_t boundingBox (glyph_t glyph, const QTransform &matrix)
Glyph * cachedGlyph (glyph_t g) const
virtual bool canRender (const QChar *string, int len)
GlyphFormat defaultGlyphFormat () const
QGlyphSet * defaultGlyphs ()
HintStyle defaultHintStyle () const
virtual QFixed descent () const
void doKerning (QGlyphLayout *, QTextEngine::ShaperFlags) const
virtual void draw (QPaintEngine *, qreal, qreal, const QTextItemInt &)
bool drawAntialiased () const
virtual QFixed emSquareSize () const
virtual QFontEngine::FaceId faceId () const
virtual HB_Error getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed *xpos, HB_Fixed *ypos, hb_uint32 *nPoints)
virtual bool getSfntTableData (uint tag, uchar *buffer, uint *length) const
virtual void getUnscaledGlyph (glyph_t glyph, QPainterPath *path, glyph_metrics_t *metrics)
virtual int glyphCount () const
bool init (FaceId faceId, bool antiaalias, GlyphFormat defaultFormat=Format_None, const QByteArray &fontData=QByteArray())
bool init (FaceId faceId, bool antialias, GlyphFormat format, QFreetypeFace *freetypeFace)
bool initFromFontEngine (const QFontEngineFT *fontEngine)
bool invalid () const
bool isBitmapFont () const
virtual QFixed leading () const
virtual QFixed lineThickness () const
Glyph * loadGlyph (uint glyph, QFixed subPixelPosition, GlyphFormat format=Format_None, bool fetchMetricsOnly=false) const
Glyph * loadGlyph (QGlyphSet *set, uint glyph, QFixed subPixelPosition, GlyphFormat=Format_None, bool fetchMetricsOnly=false) const
bool loadGlyphs (QGlyphSet *gs, const glyph_t *glyphs, int num_glyphs, const QFixedPoint *positions, GlyphFormat format=Format_Render)
QGlyphSet * loadTransformedGlyphSet (const QTransform &matrix)
FT_Face lockFace (Scaling scale=Scaled) const
virtual qreal maxCharWidth () const
virtual qreal minLeftBearing () const
virtual qreal minRightBearing () const
virtual const char * name () const
FT_Face non_locked_face () const
virtual QFontEngine::Properties properties () const
QFontEngineFT (const QFontDef &fd)
virtual void recalcAdvances (QGlyphLayout *glyphs, QTextEngine::ShaperFlags flags) const
virtual void removeGlyphFromCache (glyph_t glyph)
void setDefaultHintStyle (HintStyle style)
virtual bool stringToCMap (const QChar *str, int len, QGlyphLayout *glyphs, int *nglyphs, QTextEngine::ShaperFlags flags) const
QFixed subPixelPositionForX (QFixed x)
virtual bool supportsSubPixelPositions () const
virtual int synthesized () const
virtual Type type () const
virtual QFixed underlinePosition () const
void unlockFace () const
virtual QFixed xHeight () const
virtual ~QFontEngineFT ()
Public Functions inherited from QFontEngine
void addBitmapFontToPath (qreal x, qreal y, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags)
virtual QImage alphaMapForGlyph (glyph_t, const QTransform &t)
virtual QImage alphaMapForGlyph (glyph_t, QFixed subPixelPosition, const QTransform &t)
virtual void getGlyphBearings (glyph_t glyph, qreal *leftBearing=0, qreal *rightBearing=0)
void getGlyphPositions (const QGlyphLayout &glyphs, const QTransform &matrix, QTextItem::RenderFlags flags, QVarLengthArray< glyph_t > &glyphs_out, QVarLengthArray< QFixedPoint > &positions)
QByteArray getSfntTable (uint) const
QFontEngineGlyphCache * glyphCache (void *key, QFontEngineGlyphCache::Type type, const QTransform &transform) const
HB_Face harfbuzzFace () const
HB_Font harfbuzzFont () const
void loadKerningPairs (QFixed scalingFactor)
QFontEngine ()
void setGlyphCache (void *key, QFontEngineGlyphCache *data)
glyph_metrics_t tightBoundingBox (const QGlyphLayout &glyphs)
virtual ~QFontEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Types inherited from QFontEngineFT
typedef XGlyphInfo GlyphInfo
enum HintStyle { HintNone, HintLight, HintMedium, HintFull }
enum Scaling { Scaled, Unscaled }
enum SubpixelAntialiasingType {
Subpixel_None, Subpixel_RGB, Subpixel_BGR, Subpixel_VRGB,
Subpixel_VBGR
}
Public Types inherited from QFontEngine
enum GlyphFormat {
Format_None, Format_Render = Format_None, Format_Mono, Format_A8,
Format_A32
}
enum SynthesizedFlags { SynthesizedItalic = 0x1, SynthesizedBold = 0x2, SynthesizedStretch = 0x4 }
enum Type {
Box, Multi, XLFD, Win,
Mac, Freetype, QPF1, QPF2,
Proxy, S60FontEngine, DirectWrite, TestFontEngine = 0x1000
}
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QFontEngine
static QByteArray convertToPostscriptFontFamilyName (const QByteArray &fontFamily)
static const uchar * getCMap (const uchar *table, uint tableSize, bool *isSymbolFont, int *cmapSize)
static quint32 getTrueTypeGlyphIndex (const uchar *cmap, uint unicode)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables inherited from QFontEngineX11FT
int xglyph_format
Public Variables inherited from QFontEngine
uint cache_cost
int cache_count
QFontDef fontDef
uint fsType: 16
int glyphFormat
HB_Face hbFace
HB_FontRec hbFont
QVector< KernPair > kerning_pairs
QAtomicInt ref
bool symbol
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QFontEngineX11FT
virtual unsigned long allocateServerGlyphSet ()
virtual void freeServerGlyphSet (unsigned long id)
virtual bool uploadGlyphToServer (QGlyphSet *set, uint glyphid, Glyph *g, GlyphInfo *info, int glyphDataSize) const
Protected Functions inherited from QFontEngineFT
void freeGlyphSets ()
Protected Functions inherited from QFontEngine
QFixed lastRightBearing (const QGlyphLayout &glyphs, bool round=false)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Protected Functions inherited from QFontEngine
static const QVector< QRgb > & grayPalette ()
Protected Variables inherited from QFontEngineFT
bool antialias
bool canUploadGlyphsToServer
HintStyle default_hint_style
int default_load_flags
bool embeddedbitmap
bool embolden
QFreetypeFace * freetype
int lcdFilterType
SubpixelAntialiasingType subpixelType
bool transform
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 56 of file qrawfont_ft.cpp.
Constructors and Destructors
QFontEngineFTRawFont()
QFontEngineFTRawFont::QFontEngineFTRawFont (const QFontDef & fontDef) inline
Definition at line 66 of file qrawfont_ft.cpp.
Referenced by QRawFontPrivate::platformLoadFromData().
         : QFontEngineX11FT(fontDef)
 #else
         : QFontEngineFT(fontDef)
 #endif
     {
     }
Functions
initFromData()
bool QFontEngineFTRawFont::initFromData (const QByteArray & fontData) inline
Definition at line 86 of file qrawfont_ft.cpp.
Referenced by QRawFontPrivate::platformLoadFromData().
     {
         FaceId faceId;
         faceId.filename = "";
         faceId.index = 0;
         faceId.uuid = QUuid::createUuid().toByteArray();
         return init(faceId, true, Format_None, fontData);
     }
updateFamilyNameAndStyle()
void QFontEngineFTRawFont::updateFamilyNameAndStyle () inline
Definition at line 75 of file qrawfont_ft.cpp.
Referenced by QRawFontPrivate::platformLoadFromData().
     {
         fontDef.family = QString::fromAscii(freetype->face->family_name);
         if (freetype->face->style_flags & FT_STYLE_FLAG_ITALIC)
             fontDef.style = QFont::StyleItalic;
         if (freetype->face->style_flags & FT_STYLE_FLAG_BOLD)
             fontDef.weight = QFont::Bold;
     }
The documentation for this class was generated from the following file:
/src/gui/text/qrawfont_ft.cpp