Qt 4.8: QThreadData Class Reference
QThreadData Class Reference
#include <qthread_p.h>
Classes
class FlaggedDebugSignatures
Public Functions
bool canWaitLocked ()
void deref ()
QThreadData (int initialRefCount=1)
void ref ()
~QThreadData ()
Static Public Functions
static void clearCurrentThreadData ()
static QThreadData * current ()
static QThreadData * get2 (QThread *thread)
Public Variables
bool canWait
QAbstractEventDispatcher * eventDispatcher
QStack< QEventLoop * > eventLoops
FlaggedDebugSignatures flaggedSignatures
bool isAdopted
int loopLevel
QPostEventList postEventList
bool quitNow
QThread * thread
Qt::HANDLE threadId
QVector< void * > tls
Properties
QAtomicInt _ref
Detailed Description
Definition at line 209 of file qthread_p.h.
Constructors and Destructors
QThreadData()
QThreadData::QThreadData (int initialRefCount = 1)
Definition at line 79 of file qthread.cpp.
Referenced by current(), and qt_free_tls().
     : _ref(initialRefCount), thread(0), threadId(0),
       quitNow(false), loopLevel(0), eventDispatcher(0), canWait(true), isAdopted(false)
 {
     // fprintf(stderr, "QThreadData %p created\n", this);
 }
~QThreadData()
QThreadData::~QThreadData ()
Definition at line 86 of file qthread.cpp.
 {
     Q_ASSERT(_ref == 0);
     // In the odd case that Qt is running on a secondary thread, the main
     // thread instance will have been dereffed asunder because of the deref in
     // QThreadData::current() and the deref in the pthread_destroy. To avoid
     // crashing during QCoreApplicationData's global static cleanup we need to
     // safeguard the main thread here.. This fix is a bit crude, but it solves
     // the problem...
     if (this->thread == QCoreApplicationPrivate::theMainThread) {
        QCoreApplicationPrivate::theMainThread = 0;
        QThreadData::clearCurrentThreadData();
     }
     QThread *t = thread;
     thread = 0;
     delete t;
     for (int i = 0; i < postEventList.size(); ++i) {
         const QPostEvent &pe = postEventList.at(i);
         if (pe.event) {
             --pe.receiver->d_func()->postedEvents;
             pe.event->posted = false;
             delete pe.event;
         }
     }
     // fprintf(stderr, "QThreadData %p destroyed\n", this);
 }
Functions
canWaitLocked()
bool QThreadData::canWaitLocked () inline
Definition at line 226 of file qthread_p.h.
Referenced by postEventSourcePrepare().
     {
         QMutexLocker locker(&postEventList.mutex);
         return canWait;
     }
clearCurrentThreadData()
void QThreadData::clearCurrentThreadData () static
Definition at line 212 of file qthread_unix.cpp.
Referenced by qt_free_tls(), and ~QThreadData().
 {
     clear_thread_data();
 }
current()
QThreadData * QThreadData::current () static
Definition at line 217 of file qthread_unix.cpp.
Referenced by QThread::currentThread(), QCoreApplication::exec(), extract_location(), QThreadStorageData::get(), QCoreApplication::hasPendingEvents(), QAbstractEventDispatcher::instance(), QObject::moveToThread(), QCoreApplication::postEvent(), postEventSourcePrepare(), QThread::priority(), QCoreApplication::processEvents(), qFlagLocation(), qGlobalPostedEventsCount(), QObject::QObject(), qt_free_tls(), QThreadStorageData::QThreadStorageData(), QCoreApplicationPrivate::removePostedEvent(), QCoreApplication::removePostedEvents(), QCoreApplication::sendPostedEvents(), and QThreadStorageData::set().
 {
     QThreadData *data = get_thread_data();
     if (!data) {
         void *a;
         if (QInternal::activateCallbacks(QInternal::AdoptCurrentThread, &a)) {
             QThread *adopted = static_cast<QThread*>(a);
             Q_ASSERT(adopted);
             data = QThreadData::get2(adopted);
             set_thread_data(data);
             adopted->d_func()->running = true;
             adopted->d_func()->finished = false;
             static_cast<QAdoptedThread *>(adopted)->init();
         } else {
             data = new QThreadData;
             QT_TRY {
                 set_thread_data(data);
                 data->thread = new QAdoptedThread(data);
             } QT_CATCH(...) {
                 clear_thread_data();
                 data->deref();
                 data = 0;
                 QT_RETHROW;
             }
             data->deref();
         }
         data->isAdopted = true;
         data->threadId = (Qt::HANDLE)pthread_self();
         if (!QCoreApplicationPrivate::theMainThread)
             QCoreApplicationPrivate::theMainThread = data->thread;
     }
     return data;
 }
deref()
void QThreadData::deref ()
Definition at line 125 of file qthread.cpp.
Referenced by QInternal::callFunction(), current(), destroy_current_thread_data(), QObject::moveToThread(), QObject::QObject(), qt_adopted_thread_watcher_function(), qt_free_tls(), QCoreApplicationData::~QCoreApplicationData(), QObjectPrivate::~QObjectPrivate(), and QThreadPrivate::~QThreadPrivate().
 {
 #ifndef QT_NO_THREAD
     if (!_ref.deref())
         delete this;
 #endif
 }
get2()
static QThreadData* QThreadData::get2 (QThread * thread) inline static
Definition at line 219 of file qthread_p.h.
Referenced by QInternal::callFunction(), current(), QAbstractEventDispatcher::instance(), QObject::moveToThread(), qt_adopted_thread_watcher_function(), qt_free_tls(), QtWndProc(), QThreadPrivate::start(), and QCoreApplicationData::~QCoreApplicationData().
     { Q_ASSERT_X(thread != 0, "QThread", "internal error"); return thread->d_func()->data; }
ref()
void QThreadData::ref ()
Definition at line 117 of file qthread.cpp.
Referenced by QInternal::callFunction(), QObject::moveToThread(), QObject::QObject(), QObjectPrivate::setThreadData_helper(), and QThreadPrivate::start().
 {
 #ifndef QT_NO_THREAD
     (void) _ref.ref();
     Q_ASSERT(_ref != 0);
 #endif
 }
Properties
_ref
QAtomicInt QThreadData::_ref private
Definition at line 211 of file qthread_p.h.
Referenced by deref(), and ~QThreadData().
canWait
bool QThreadData::canWait
Definition at line 267 of file qthread_p.h.
Referenced by processPostedEvents(), QCoreApplicationPrivate::sendPostedEvents(), and QObjectPrivate::setThreadData_helper().
eventDispatcher
QAbstractEventDispatcher* QThreadData::eventDispatcher
Definition at line 264 of file qthread_p.h.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress(), QAbstractSocketPrivate::_q_testConnection(), QThreadPrivate::createEventDispatcher(), QObject::event(), QThreadPrivate::finish(), QAbstractSocketPrivate::initSocketLayer(), QAbstractEventDispatcher::instance(), QObject::killTimer(), QCoreApplication::processEvents(), qt_adopted_thread_watcher_function(), qt_create_commandline(), QCoreApplicationPrivate::sendPostedEvents(), QObjectPrivate::setThreadData_helper(), QObject::startTimer(), and QObjectPrivate::~QObjectPrivate().
eventLoops
QStack<QEventLoop *> QThreadData::eventLoops
Definition at line 265 of file qthread_p.h.
Referenced by QCoreApplication::exec(), QCoreApplication::exit(), and QCoreApplication::hasPendingEvents().
flaggedSignatures
FlaggedDebugSignatures QThreadData::flaggedSignatures
Definition at line 275 of file qthread_p.h.
Referenced by qFlagLocation().
isAdopted
bool QThreadData::isAdopted
Definition at line 269 of file qthread_p.h.
Referenced by current(), destroy_current_thread_data(), qt_adopted_thread_watcher_function(), and qt_free_tls().
loopLevel
int QThreadData::loopLevel
Definition at line 263 of file qthread_p.h.
Referenced by QCoreApplication::notifyInternal(), QScopedLoopLevelCounter::QScopedLoopLevelCounter(), QCoreApplicationPrivate::sendPostedEvents(), and QScopedLoopLevelCounter::~QScopedLoopLevelCounter().
postEventList
QPostEventList QThreadData::postEventList
Definition at line 266 of file qthread_p.h.
Referenced by QObject::moveToThread(), QCoreApplication::postEvent(), qGlobalPostedEventsCount(), QCoreApplicationPrivate::removePostedEvent(), QCoreApplication::removePostedEvents(), QCoreApplicationPrivate::removePostedTimerEvent(), QCoreApplicationPrivate::sendPostedEvents(), QObjectPrivate::setThreadData_helper(), and ~QThreadData().
quitNow
bool QThreadData::quitNow
Definition at line 262 of file qthread_p.h.
Referenced by QCoreApplication::exec(), QCoreApplication::exit(), qt_adopted_thread_watcher_function(), and QThreadPrivate::start().
thread
QThread* QThreadData::thread
Definition at line 260 of file qthread_p.h.
Referenced by check_parent_thread(), current(), QThread::currentThread(), destroy_current_thread_data(), QThreadStorageData::get(), QObject::moveToThread(), QThread::priority(), qt_adopted_thread_watcher_function(), qt_free_tls(), QThreadStorageData::set(), and ~QThreadData().
threadId
Qt::HANDLE QThreadData::threadId
Definition at line 261 of file qthread_p.h.
Referenced by current(), qt_adopted_thread_watcher_function(), qt_free_tls(), and QThreadPrivate::start().
tls
QVector<void *> QThreadData::tls
Definition at line 268 of file qthread_p.h.
Referenced by QThreadPrivate::finish(), QThreadStorageData::get(), QThreadStorageData::QThreadStorageData(), and QThreadStorageData::set().
The documentation for this class was generated from the following files:
/src/corelib/thread/qthread_p.h
/src/corelib/thread/qthread.cpp
/src/corelib/thread/qthread_unix.cpp
/src/corelib/thread/qthread_win.cpp