Qt 4.8: QTreeWidgetItem Class Reference
QTreeWidgetItem Class Reference
The QTreeWidgetItem class provides an item for use with the QTreeWidget convenience class.
#include <qtreewidget.h>
Public Types
enum ChildIndicatorPolicy { ShowIndicator, DontShowIndicator, DontShowIndicatorWhenChildless }
enum ItemType { Type = 0, UserType = 1000 }
This enum describes the types that are used to describe tree widget items.
Public Functions
void addChild (QTreeWidgetItem *child)
Appends the child item to the list of children.
void addChildren (const QList< QTreeWidgetItem *> &children)
Appends the given list of children to the item.
QBrush background (int column) const
Returns the brush used to render the background of the specified column.
QColor backgroundColor (int column) const
This function is deprecated.
Qt::CheckState checkState (int column) const
Returns the check state of the label in the given column.
QTreeWidgetItem * child (int index) const
Returns the item at the given index in the list of the item's children.
int childCount () const
Returns the number of child items.
QTreeWidgetItem::ChildIndicatorPolicy childIndicatorPolicy () const
Returns the item indicator policy.
virtual QTreeWidgetItem * clone () const
Creates a deep copy of the item and of its children.
int columnCount () const
Returns the number of columns in the item.
virtual QVariant data (int column, int role) const
Returns the value for the item's column and role.
Qt::ItemFlags flags () const
Returns the flags used to describe the item.
QFont font (int column) const
Returns the font used to render the text in the specified column.
QBrush foreground (int column) const
Returns the brush used to render the foreground (e.
QIcon icon (int column) const
Returns the icon that is displayed in the specified column.
int indexOfChild (QTreeWidgetItem *child) const
Returns the index of the given child in the item's list of children.
void insertChild (int index, QTreeWidgetItem *child)
Inserts the child item at index in the list of children.
void insertChildren (int index, const QList< QTreeWidgetItem *> &children)
Inserts the given list of children into the list of the item children at index .
bool isDisabled () const
Returns true if the item is disabled; otherwise returns false.
bool isExpanded () const
Returns true if the item is expanded, otherwise returns false.
bool isFirstColumnSpanned () const
Returns true if the item is spanning all the columns in a row; otherwise returns false.
bool isHidden () const
Returns true if the item is hidden, otherwise returns false.
bool isSelected () const
Returns true if the item is selected, otherwise returns false.
virtual bool operator< (const QTreeWidgetItem &other) const
Returns true if the text in the item is less than the text in the other item, otherwise returns false.
QTreeWidgetItem & operator= (const QTreeWidgetItem &other)
Assigns other's data and flags to this item.
QTreeWidgetItem * parent () const
Returns the item's parent.
QTreeWidgetItem (int type=Type)
Constructs a tree widget item of the specified type.
QTreeWidgetItem (const QStringList &strings, int type=Type)
Constructs a tree widget item of the specified type.
QTreeWidgetItem (QTreeWidget *view, int type=Type)
Constructs a tree widget item of the specified type and appends it to the items in the given parent.
QTreeWidgetItem (QTreeWidget *view, const QStringList &strings, int type=Type)
Constructs a tree widget item of the specified type and appends it to the items in the given parent.
QTreeWidgetItem (QTreeWidget *view, QTreeWidgetItem *after, int type=Type)
Constructs a tree widget item of the specified type and inserts it into the given parent after the preceding item.
QTreeWidgetItem (QTreeWidgetItem *parent, int type=Type)
Constructs a tree widget item and append it to the given parent.
QTreeWidgetItem (QTreeWidgetItem *parent, const QStringList &strings, int type=Type)
Constructs a tree widget item and append it to the given parent.
QTreeWidgetItem (QTreeWidgetItem *parent, QTreeWidgetItem *after, int type=Type)
Constructs a tree widget item of the specified type that is inserted into the parent after the preceding child item.
QTreeWidgetItem (const QTreeWidgetItem &other)
Constructs a copy of other.
virtual void read (QDataStream &in)
Reads the item from stream in.
void removeChild (QTreeWidgetItem *child)
Removes the given item indicated by child.
void setBackground (int column, const QBrush &brush)
Sets the background brush of the label in the given column to the specified brush.
void setBackgroundColor (int column, const QColor &color)
This function is deprecated.
void setCheckState (int column, Qt::CheckState state)
Sets the item in the given column check state to be state.
void setChildIndicatorPolicy (QTreeWidgetItem::ChildIndicatorPolicy policy)
Sets the item indicator policy.
virtual void setData (int column, int role, const QVariant &value)
Sets the value for the item's column and role to the given value.
void setDisabled (bool disabled)
Disables the item if disabled is true; otherwise enables the item.
void setExpanded (bool expand)
Expands the item if expand is true, otherwise collapses the item.
void setFirstColumnSpanned (bool span)
Sets the first section to span all columns if span is true; otherwise all item sections are shown.
void setFlags (Qt::ItemFlags flags)
Sets the flags for the item to the given flags.
void setFont (int column, const QFont &font)
Sets the font used to display the text in the given column to the given font.
void setForeground (int column, const QBrush &brush)
Sets the foreground brush of the label in the given column to the specified brush.
void setHidden (bool hide)
Hides the item if hide is true, otherwise shows the item.
void setIcon (int column, const QIcon &icon)
Sets the icon to be displayed in the given column to icon.
void setSelected (bool select)
Sets the selected state of the item to select.
void setSizeHint (int column, const QSize &size)
Sets the size hint for the tree item in the given column to be size.
void setStatusTip (int column, const QString &statusTip)
Sets the status tip for the given column to the given statusTip.
void setText (int column, const QString &text)
Sets the text to be displayed in the given column to the given text.
void setTextAlignment (int column, int alignment)
Sets the text alignment for the label in the given column to the alignment specified (see Qt::AlignmentFlag).
void setTextColor (int column, const QColor &color)
This function is deprecated.
void setToolTip (int column, const QString &toolTip)
Sets the tooltip for the given column to toolTip.
void setWhatsThis (int column, const QString &whatsThis)
Sets the "What's This?" help for the given column to whatsThis.
QSize sizeHint (int column) const
Returns the size hint set for the tree item in the given column (see QSize).
void sortChildren (int column, Qt::SortOrder order)
Sorts the children of the item using the given order, by the values in the given column.
QString statusTip (int column) const
Returns the status tip for the contents of the given column.
QTreeWidgetItem * takeChild (int index)
Removes the item at index and returns it, otherwise return 0.
QList< QTreeWidgetItem * > takeChildren ()
Removes the list of children and returns it, otherwise returns an empty list.
QString text (int column) const
Returns the text in the specified column.
int textAlignment (int column) const
Returns the text alignment for the label in the given column (see Qt::AlignmentFlag).
QColor textColor (int column) const
This function is deprecated.
QString toolTip (int column) const
Returns the tool tip for the given column.
QTreeWidget * treeWidget () const
Returns the tree widget that contains the item.
int type () const
Returns the type passed to the QTreeWidgetItem constructor.
QString whatsThis (int column) const
Returns the "What's This?" help for the contents of the given column.
virtual void write (QDataStream &out) const
Writes the item to stream out.
virtual ~QTreeWidgetItem ()
Destroys this tree widget item.
Protected Functions
void emitDataChanged ()
Causes the model associated with this item to emit a dataChanged() signal for this item.
Private Functions
QVariant childrenCheckState (int column) const
Calculates the checked state of the item based on the checked state of its children.
void executePendingSort () const
void itemChanged ()
void sortChildren (int column, Qt::SortOrder order, bool climb)
Sorts the children by the value in the given column, in the order specified.
Properties
QList< QTreeWidgetItem * > children
QTreeWidgetItemPrivate * d
Qt::ItemFlags itemFlags
QTreeWidgetItem * par
int rtti
QVector< QVector< QWidgetItemData > > values
QTreeWidget * view
Friends
class QTreeModel
class QTreeWidget
class QTreeWidgetItemIterator
class QTreeWidgetItemPrivate
class QTreeWidgetPrivate
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &out, const QTreeWidgetItem &item)
Writes the tree widget item item to stream out.
QDataStream & operator>> (QDataStream &in, QTreeWidgetItem &item)
Reads a tree widget item from stream in into item.
Detailed Description
The QTreeWidgetItem class provides an item for use with the QTreeWidget convenience class.
Tree widget items are used to hold rows of information for tree widgets. Rows usually contain several columns of data, each of which can contain a text label and an icon.
The QTreeWidgetItem class is a convenience class that replaces the QListViewItem class in Qt 3. It provides an item for use with the QTreeWidget class.
Items are usually constructed with a parent that is either a QTreeWidget (for top-level items) or a QTreeWidgetItem (for items on lower levels of the tree). For example, the following code constructs a top-level item to represent cities of the world, and adds a entry for Oslo as a child item:
    QTreeWidgetItem *cities = new QTreeWidgetItem(treeWidget);
    cities->setText(0, tr("Cities"));
    QTreeWidgetItem *osloItem = new QTreeWidgetItem(cities);
    osloItem->setText(0, tr("Oslo"));
    osloItem->setText(1, tr("Yes"));
Items can be added in a particular order by specifying the item they follow when they are constructed:
    QTreeWidgetItem *planets = new QTreeWidgetItem(treeWidget, cities);
    planets->setText(0, tr("Planets"));
Each column in an item can have its own background brush which is set with the setBackground() function. The current background brush can be found with background(). The text label for each column can be rendered with its own font and brush. These are specified with the setFont() and setForeground() functions, and read with font() and foreground().
The main difference between top-level items and those in lower levels of the tree is that a top-level item has no parent(). This information can be used to tell the difference between items, and is useful to know when inserting and removing items from the tree. Children of an item can be removed with takeChild() and inserted at a given index in the list of children with the insertChild() function.
By default, items are enabled, selectable, checkable, and can be the source of a drag and drop operation. Each item's flags can be changed by calling setFlags() with the appropriate value (see Qt::ItemFlags). Checkable items can be checked and unchecked with the setCheckState() function. The corresponding checkState() function indicates whether the item is currently checked.
Subclassing
When subclassing QTreeWidgetItem to provide custom items, it is possible to define new types for them so that they can be distinguished from standard items. The constructors for subclasses that require this feature need to call the base class constructor with a new type value equal to or greater than UserType .
See also
QTreeWidget, QTreeWidgetItemIterator, {Model/View Programming}, QListWidgetItem, QTableWidgetItem
Definition at line 63 of file qtreewidget.h.
Enumerations
ChildIndicatorPolicy
enum QTreeWidgetItem::ChildIndicatorPolicy
Since
4.3
ShowIndicator The controls for expanding and collapsing will be shown for this item even if there are no children.
DontShowIndicator The controls for expanding and collapsing will never be shown even if there are children. If the node is forced open the user will not be able to expand or collapse the item.
DontShowIndicatorWhenChildless The controls for expanding and collapsing will be shown if the item contains children.
Enumerator
ShowIndicator
DontShowIndicator
DontShowIndicatorWhenChildless
Definition at line 102 of file qtreewidget.h.
 { ShowIndicator, DontShowIndicator, DontShowIndicatorWhenChildless };
ItemType
enum QTreeWidgetItem::ItemType
This enum describes the types that are used to describe tree widget items.
Type The default type for tree widget items.
UserType The minimum value for custom types. Values below UserType are reserved by Qt.
You can define new user types in QTreeWidgetItem subclasses to ensure that custom items are treated specially; for example, when items are sorted.
See also
type()
Enumerator
Type
UserType
Definition at line 71 of file qtreewidget.h.
 { Type = 0, UserType = 1000 };
Constructors and Destructors
QTreeWidgetItem() [1/9]
QTreeWidgetItem::QTreeWidgetItem (int type = Type) explicit
Constructs a tree widget item of the specified type.
The item must be inserted into a tree widget.
See also
type()
Definition at line 1489 of file qtreewidget.cpp.
Referenced by clone().
     : rtti(type), view(0), d(new QTreeWidgetItemPrivate(this)), par(0),
       itemFlags(Qt::ItemIsSelectable
                 |Qt::ItemIsUserCheckable
                 |Qt::ItemIsEnabled
                 |Qt::ItemIsDragEnabled
                 |Qt::ItemIsDropEnabled)
 {
 }
QTreeWidgetItem() [2/9]
QTreeWidgetItem::QTreeWidgetItem (const QStringList & strings, int type = Type)
Constructs a tree widget item of the specified type.
The item must be inserted into a tree widget. The given list of strings will be set as the item text for each column in the item.
See also
type()
Definition at line 1508 of file qtreewidget.cpp.
     : rtti(type), view(0), d(new QTreeWidgetItemPrivate(this)), par(0),
       itemFlags(Qt::ItemIsSelectable
                 |Qt::ItemIsUserCheckable
                 |Qt::ItemIsEnabled
                 |Qt::ItemIsDragEnabled
                 |Qt::ItemIsDropEnabled)
 {
     for (int i = 0; i < strings.count(); ++i)
         setText(i, strings.at(i));
 }
QTreeWidgetItem() [3/9]
QTreeWidgetItem::QTreeWidgetItem (QTreeWidget * parent, int type = Type) explicit
Constructs a tree widget item of the specified type and appends it to the items in the given parent.
See also
type()
Definition at line 1529 of file qtreewidget.cpp.
     : rtti(type), view(0), d(new QTreeWidgetItemPrivate(this)), par(0),
       itemFlags(Qt::ItemIsSelectable
                 |Qt::ItemIsUserCheckable
                 |Qt::ItemIsEnabled
                 |Qt::ItemIsDragEnabled
                 |Qt::ItemIsDropEnabled)
 {
     if (view && view->model()) {
         QTreeModel *model = qobject_cast<QTreeModel*>(view->model());
         model->rootItem->addChild(this);
         values.reserve(model->headerItem->columnCount());
     }
 }
QTreeWidgetItem() [4/9]
QTreeWidgetItem::QTreeWidgetItem (QTreeWidget * parent, const QStringList & strings, int type = Type)
Constructs a tree widget item of the specified type and appends it to the items in the given parent.
The given list of strings will be set as the item text for each column in the item.
See also
type()
Definition at line 1554 of file qtreewidget.cpp.
     : rtti(type), view(0), d(new QTreeWidgetItemPrivate(this)), par(0),
       itemFlags(Qt::ItemIsSelectable
                 |Qt::ItemIsUserCheckable
                 |Qt::ItemIsEnabled
                 |Qt::ItemIsDragEnabled
                 |Qt::ItemIsDropEnabled)
 {
     for (int i = 0; i < strings.count(); ++i)
         setText(i, strings.at(i));
     if (view && view->model()) {
         QTreeModel *model = qobject_cast<QTreeModel*>(view->model());
         model->rootItem->addChild(this);
         values.reserve(model->headerItem->columnCount());
     }
 }
QTreeWidgetItem() [5/9]
QTreeWidgetItem::QTreeWidgetItem (QTreeWidget * parent, QTreeWidgetItem * preceding, int type = Type)
Constructs a tree widget item of the specified type and inserts it into the given parent after the preceding item.
See also
type()
Definition at line 1579 of file qtreewidget.cpp.
     : rtti(type), view(0), d(new QTreeWidgetItemPrivate(this)), par(0),
       itemFlags(Qt::ItemIsSelectable
                 |Qt::ItemIsUserCheckable
                 |Qt::ItemIsEnabled
                 |Qt::ItemIsDragEnabled
                 |Qt::ItemIsDropEnabled)
 {
     if (view) {
         QTreeModel *model = qobject_cast<QTreeModel*>(view->model());
         if (model) {
             int i = model->rootItem->children.indexOf(after) + 1;
             model->rootItem->insertChild(i, this);
             values.reserve(model->headerItem->columnCount());
         }
     }
 }
QTreeWidgetItem() [6/9]
QTreeWidgetItem::QTreeWidgetItem (QTreeWidgetItem * parent, int type = Type) explicit
Constructs a tree widget item and append it to the given parent.
See also
type()
Definition at line 1602 of file qtreewidget.cpp.
     : rtti(type), view(0), d(new QTreeWidgetItemPrivate(this)), par(0),
       itemFlags(Qt::ItemIsSelectable
                 |Qt::ItemIsUserCheckable
                 |Qt::ItemIsEnabled
                 |Qt::ItemIsDragEnabled
                 |Qt::ItemIsDropEnabled)
 {
     if (parent)
         parent->addChild(this);
 }
QTreeWidgetItem() [7/9]
QTreeWidgetItem::QTreeWidgetItem (QTreeWidgetItem * parent, const QStringList & strings, int type = Type)
Constructs a tree widget item and append it to the given parent.
The given list of strings will be set as the item text for each column in the item.
See also
type()
Definition at line 1620 of file qtreewidget.cpp.
     : rtti(type), view(0), d(new QTreeWidgetItemPrivate(this)), par(0),
       itemFlags(Qt::ItemIsSelectable
                 |Qt::ItemIsUserCheckable
                 |Qt::ItemIsEnabled
                 |Qt::ItemIsDragEnabled
                 |Qt::ItemIsDropEnabled)
 {
     for (int i = 0; i < strings.count(); ++i)
         setText(i, strings.at(i));
     if (parent)
         parent->addChild(this);
 }
QTreeWidgetItem() [8/9]
QTreeWidgetItem::QTreeWidgetItem (QTreeWidgetItem * parent, QTreeWidgetItem * preceding, int type = Type)
Constructs a tree widget item of the specified type that is inserted into the parent after the preceding child item.
See also
type()
Definition at line 1642 of file qtreewidget.cpp.
     : rtti(type), view(0), d(new QTreeWidgetItemPrivate(this)), par(0),
       itemFlags(Qt::ItemIsSelectable
                 |Qt::ItemIsUserCheckable
                 |Qt::ItemIsEnabled
                 |Qt::ItemIsDragEnabled
                 |Qt::ItemIsDropEnabled)
 {
     if (parent) {
         int i = parent->children.indexOf(after) + 1;
         parent->insertChild(i, this);
     }
 }
QTreeWidgetItem() [9/9]
QTreeWidgetItem::QTreeWidgetItem (const QTreeWidgetItem & other)
Constructs a copy of other.
Since
4.1
Note that type() and treeWidget() are not copied.
This function is useful when reimplementing clone().
See also
data(), flags()
Definition at line 2045 of file qtreewidget.cpp.
     : rtti(Type), values(other.values), view(0),
       d(new QTreeWidgetItemPrivate(this)), par(0),
       itemFlags(other.itemFlags)
 {
     d->display = other.d->display;
 }
~QTreeWidgetItem()
QTreeWidgetItem::~QTreeWidgetItem () virtual
Destroys this tree widget item.
The item will be removed from QTreeWidget to which it has been added. This makes it safe to delete an item at any time.
Definition at line 1664 of file qtreewidget.cpp.
 {
     QTreeModel *model = (view ? qobject_cast<QTreeModel*>(view->model()) : 0);
     bool wasSkipSort = false;
     if (model) {
         wasSkipSort = model->skipPendingSort;
         model->skipPendingSort = true;
     }
     if (par) {
         int i = par->children.indexOf(this);
         if (i >= 0) {
             if (model) model->beginRemoveItems(par, i, 1);
             // users _could_ do changes when connected to rowsAboutToBeRemoved,
             // so we check again to make sure 'i' is valid
             if (!par->children.isEmpty() && par->children.at(i) == this)
                 par->children.takeAt(i);
             if (model) model->endRemoveItems();
         }
     } else if (model) {
         if (this == model->headerItem) {
             model->headerItem = 0;
         } else {
             int i = model->rootItem->children.indexOf(this);
             if (i >= 0) {
                 model->beginRemoveItems(0, i, 1);
                 // users _could_ do changes when connected to rowsAboutToBeRemoved,
                 // so we check again to make sure 'i' is valid
                 if (!model->rootItem->children.isEmpty() && model->rootItem->children.at(i) == this)
                     model->rootItem->children.takeAt(i);
                 model->endRemoveItems();
             }
         }
     }
     // at this point the persistent indexes for the children should also be invalidated
     // since we invalidated the parent
     for (int i = 0; i < children.count(); ++i) {
         QTreeWidgetItem *child = children.at(i);
         // make sure the child does not try to remove itself from our children list
         child->par = 0;
         // make sure the child does not try to remove itself from the top level list
         child->view = 0;
         delete child;
     }
     children.clear();
     delete d;
     if (model) {
         model->skipPendingSort = wasSkipSort;
     }
 }
Functions
addChild()
void QTreeWidgetItem::addChild (QTreeWidgetItem * child)
Appends the child item to the list of children.
See also
insertChild() takeChild()
Definition at line 2075 of file qtreewidget.cpp.
Referenced by QTreeWidgetItem().
 {
     if (child) {
         insertChild(children.count(), child);
         child->d->rowGuess = children.count() - 1;
     }
 }
addChildren()
void QTreeWidgetItem::addChildren (const QList< QTreeWidgetItem *> & children)
Appends the given list of children to the item.
Since
4.1
See also
insertChildren() takeChildren()
Definition at line 2181 of file qtreewidget.cpp.
 {
     insertChildren(this->children.count(), children);
 }
background()
QBrush QTreeWidgetItem::background (int column) const inline
Returns the brush used to render the background of the specified column.
Since
4.2
See also
foreground()
Definition at line 147 of file qtreewidget.h.
         { return qvariant_cast<QBrush>(data(column, Qt::BackgroundRole)); }
backgroundColor()
QColor QTreeWidgetItem::backgroundColor (int column) const inline
This function is deprecated.
Use background() instead.
Definition at line 142 of file qtreewidget.h.
         { return qvariant_cast<QColor>(data(column, Qt::BackgroundColorRole)); }
checkState()
Qt::CheckState QTreeWidgetItem::checkState (int column) const inline
Returns the check state of the label in the given column.
See also
Qt::CheckState
Definition at line 162 of file qtreewidget.h.
Referenced by QTreeWidgetItemIterator::matchesFlags().
         { return static_cast<Qt::CheckState>(data(column, Qt::CheckStateRole).toInt()); }
child()
QTreeWidgetItem * QTreeWidgetItem::child (int index) const inline
Returns the item at the given index in the list of the item's children.
See also
parent()
Definition at line 184 of file qtreewidget.h.
Referenced by addChild(), QTreeModel::beginRemoveItems(), clone(), QTreeModel::index(), insertChildren(), QTreeWidgetItemIteratorPrivate::next(), QTreeWidgetItemIteratorPrivate::nextSibling(), QTreeWidgetItemIteratorPrivate::previous(), QTreeWidgetItemPrivate::propagateDisabled(), QTreeWidgetItemIterator::QTreeWidgetItemIterator(), setData(), setFlags(), and ~QTreeWidgetItem().
{
         if (index < 0 || index >= children.size())
             return 0;
         executePendingSort();
         return children.at(index);
     }
childCount()
int QTreeWidgetItem::childCount () const inline
Returns the number of child items.
Definition at line 190 of file qtreewidget.h.
Referenced by QTreeModel::clear(), clone(), QTreeWidget::dropEvent(), QTreeModel::hasChildren(), insertChildren(), QTreeWidgetItemIterator::matchesFlags(), QTreeWidgetItemIteratorPrivate::next(), QTreeWidgetItemIteratorPrivate::previous(), and QTreeModel::rowCount().
 { return children.count(); }
childIndicatorPolicy()
QTreeWidgetItem::ChildIndicatorPolicy QTreeWidgetItem::childIndicatorPolicy () const
Returns the item indicator policy.
This policy decides when the tree branch expand/collapse indicator is shown.
See also
setChildIndicatorPolicy()
Definition at line 1779 of file qtreewidget.cpp.
 {
     return d->policy;
 }
childrenCheckState()
QVariant QTreeWidgetItem::childrenCheckState (int column) const private
Calculates the checked state of the item based on the checked state of its children.
Warning
This function is not part of the public interface.
E.g. if all children checked => this item is also checked; if some children checked => this item is partially checked; if no children checked => this item is unchecked.
Definition at line 2335 of file qtreewidget.cpp.
Referenced by data().
 {
     if (column < 0)
         return QVariant();
     bool checkedChildren = false;
     bool uncheckedChildren = false;
     for (int i = 0; i < children.count(); ++i) {
         QVariant value = children.at(i)->data(column, Qt::CheckStateRole);
         if (!value.isValid())
             return QVariant();
         switch (static_cast<Qt::CheckState>(value.toInt()))
         {
         case Qt::Unchecked:
             uncheckedChildren = true;
             break;
         case Qt::Checked:
             checkedChildren = true;
             break;
         case Qt::PartiallyChecked:
         default:
             return Qt::PartiallyChecked;
         }
     }
     if (uncheckedChildren && checkedChildren)
         return Qt::PartiallyChecked;
     if (uncheckedChildren)
         return Qt::Unchecked;
     else if (checkedChildren)
         return Qt::Checked;
     else
         return QVariant(); // value was not defined
 }
clone()
QTreeWidgetItem * QTreeWidgetItem::clone () const virtual
Creates a deep copy of the item and of its children.
Definition at line 1718 of file qtreewidget.cpp.
 {
     QTreeWidgetItem *copy = 0;
     QStack<const QTreeWidgetItem*> stack;
     QStack<QTreeWidgetItem*> parentStack;
     stack.push(this);
     parentStack.push(0);
     QTreeWidgetItem *root = 0;
     const QTreeWidgetItem *item = 0;
     QTreeWidgetItem *parent = 0;
     while (!stack.isEmpty()) {
         // get current item, and copied parent
         item = stack.pop();
         parent = parentStack.pop();
         // copy item
         copy = new QTreeWidgetItem(*item);
         if (!root)
             root = copy;
         // set parent and add to parents children list
         if (parent) {
             copy->par = parent;
             parent->children.insert(0, copy);
         }
         for (int i = 0; i < item->childCount(); ++i) {
             stack.push(item->child(i));
             parentStack.push(copy);
         }
     }
     return root;
 }
columnCount()
int QTreeWidgetItem::columnCount () const inline
Returns the number of columns in the item.
Definition at line 191 of file qtreewidget.h.
Referenced by QTreeModel::columnCount(), insertChild(), QTreeModel::itemChanged(), QTreeWidgetItem(), and QTreeWidget::setHeaderItem().
 { return values.count(); }
data()
QVariant QTreeWidgetItem::data (int column, int role) const virtual
Returns the value for the item's column and role.
Definition at line 1956 of file qtreewidget.cpp.
Referenced by childrenCheckState(), QTreeModel::data(), QTreeModel::headerData(), QTreeModel::itemData(), operator<(), and setData().
 {
     switch (role) {
     case Qt::EditRole:
     case Qt::DisplayRole:
         if (column >= 0 && column < d->display.count())
             return d->display.at(column);
         break;
     case Qt::CheckStateRole:
         // special case for check state in tristate
         if (children.count() && (itemFlags & Qt::ItemIsTristate))
             return childrenCheckState(column);
         // fallthrough intended
    default:
         if (column >= 0 && column < values.size()) {
             const QVector<QWidgetItemData> &column_values = values.at(column);
             for (int i = 0; i < column_values.count(); ++i)
                 if (column_values.at(i).role == role)
                     return column_values.at(i).value;
         }
     }
     return QVariant();
 }
emitDataChanged()
void QTreeWidgetItem::emitDataChanged () protected
Causes the model associated with this item to emit a dataChanged() signal for this item.
Since
4.5
You normally only need to call this function if you have subclassed QTreeWidgetItem and reimplemented data() and/or setData().
See also
setData()
Definition at line 2385 of file qtreewidget.cpp.
 {
     itemChanged();
 }
executePendingSort()
void QTreeWidgetItem::executePendingSort () const private
Warning
This function is not part of the public interface.
Definition at line 2402 of file qtreewidget.cpp.
 {
     if (QTreeModel *model = (view ? qobject_cast<QTreeModel*>(view->model()) : 0))
         model->executePendingSort();
 }
flags()
Qt::ItemFlags QTreeWidgetItem::flags () const
Returns the flags used to describe the item.
These determine whether the item can be checked, edited, and selected.
The default value for flags is Qt::ItemIsSelectable | Qt::ItemIsUserCheckable | Qt::ItemIsEnabled | Qt::ItemIsDragEnabled. If the item was constructed with a parent, flags will in addition contain Qt::ItemIsDropEnabled.
See also
setFlags()
Definition at line 1869 of file qtreewidget.cpp.
Referenced by QTreeWidgetItemIteratorPrivate::ensureValidIterator(), QTreeModel::flags(), isDisabled(), QTreeWidgetItemIterator::matchesFlags(), setDisabled(), and setFlags().
 {
     return itemFlags;
 }
font()
QFont QTreeWidgetItem::font (int column) const inline
Returns the font used to render the text in the specified column.
See also
setFont()
Definition at line 133 of file qtreewidget.h.
         { return qvariant_cast<QFont>(data(column, Qt::FontRole)); }
foreground()
QBrush QTreeWidgetItem::foreground (int column) const inline
Returns the brush used to render the foreground (e.
Since
4.2
g. text) of the specified column.
See also
background()
Definition at line 157 of file qtreewidget.h.
         { return qvariant_cast<QBrush>(data(column, Qt::ForegroundRole)); }
icon()
QIcon QTreeWidgetItem::icon (int column) const inline
Returns the icon that is displayed in the specified column.
See also
setIcon(), {QAbstractItemView::iconSize}{iconSize}
Definition at line 113 of file qtreewidget.h.
         { return qvariant_cast<QIcon>(data(column, Qt::DecorationRole)); }
indexOfChild()
int QTreeWidgetItem::indexOfChild (QTreeWidgetItem * child) const inline
Returns the index of the given child in the item's list of children.
Definition at line 250 of file qtreewidget.h.
Referenced by QTreeWidgetItemIteratorPrivate::ensureValidIterator(), and QTreeWidgetItemIteratorPrivate::nextSibling().
 { executePendingSort(); return children.indexOf(achild); }
insertChild()
void QTreeWidgetItem::insertChild (int index, QTreeWidgetItem * child)
Inserts the child item at index in the list of children.
If the child has already been inserted somewhere else it wont be inserted again.
Definition at line 2088 of file qtreewidget.cpp.
Referenced by addChild(), QTreeWidget::dropEvent(), insertChildren(), and QTreeWidgetItem().
 {
     if (index < 0 || index > children.count() || child == 0 || child->view != 0 || child->par != 0)
         return;
     if (QTreeModel *model = (view ? qobject_cast<QTreeModel*>(view->model()) : 0)) {
         const bool wasSkipSort = model->skipPendingSort;
         model->skipPendingSort = true;
         if (model->rootItem == this)
             child->par = 0;
         else
             child->par = this;
         if (view->isSortingEnabled()) {
             // do a delayed sort instead
             if (!model->sortPendingTimer.isActive())
                 model->sortPendingTimer.start(0, model);
         }
         model->beginInsertItems(this, index, 1);
         int cols = model->columnCount();
         QStack<QTreeWidgetItem*> stack;
         stack.push(child);
         while (!stack.isEmpty()) {
             QTreeWidgetItem *i = stack.pop();
             i->view = view;
             i->values.reserve(cols);
             for (int c = 0; c < i->children.count(); ++c)
                 stack.push(i->children.at(c));
         }
         children.insert(index, child);
         model->endInsertItems();
         model->skipPendingSort = wasSkipSort;
     } else {
         child->par = this;
         children.insert(index, child);
     }
     if (child->par)
         d->propagateDisabled(child);
 }
insertChildren()
void QTreeWidgetItem::insertChildren (int index, const QList< QTreeWidgetItem *> & children)
Inserts the given list of children into the list of the item children at index .
Since
4.1
Children that have already been inserted somewhere else wont be inserted.
Definition at line 2196 of file qtreewidget.cpp.
Referenced by addChildren().
 {
     if (view && view->isSortingEnabled()) {
         for (int n = 0; n < children.count(); ++n)
             insertChild(index, children.at(n));
         return;
     }
     QTreeModel *model = (view ? qobject_cast<QTreeModel*>(view->model()) : 0);
     QStack<QTreeWidgetItem*> stack;
     QList<QTreeWidgetItem*> itemsToInsert;
     for (int n = 0; n < children.count(); ++n) {
         QTreeWidgetItem *child = children.at(n);
         if (child->view || child->par)
             continue;
         itemsToInsert.append(child);
         if (view && model) {
             if (child->childCount() == 0)
                 child->view = view;
             else
                 stack.push(child);
         }
         if (model && (model->rootItem == this))
             child->par = 0;
         else
             child->par = this;
     }
     if (!itemsToInsert.isEmpty()) {
         while (!stack.isEmpty()) {
             QTreeWidgetItem *i = stack.pop();
             i->view = view;
             for (int c = 0; c < i->children.count(); ++c)
                 stack.push(i->children.at(c));
         }
         if (model) model->beginInsertItems(this, index, itemsToInsert.count());
         for (int n = 0; n < itemsToInsert.count(); ++n) {
             QTreeWidgetItem *child = itemsToInsert.at(n);
             this->children.insert(index + n, child);
             if (child->par)
                 d->propagateDisabled(child);
         }
         if (model) model->endInsertItems();
     }
 }
isDisabled()
bool QTreeWidgetItem::isDisabled () const inline
Returns true if the item is disabled; otherwise returns false.
Since
4.3
See also
setFlags()
Definition at line 423 of file qtreewidget.h.
 { return !(flags() & Qt::ItemIsEnabled); }
isExpanded()
bool QTreeWidgetItem::isExpanded () const inline
Returns true if the item is expanded, otherwise returns false.
Since
4.2
See also
setExpanded()
Definition at line 411 of file qtreewidget.h.
 { return (view ? view->isItemExpanded(this) : false); }
isFirstColumnSpanned()
bool QTreeWidgetItem::isFirstColumnSpanned () const inline
Returns true if the item is spanning all the columns in a row; otherwise returns false.
Since
4.3
See also
setFirstColumnSpanned()
Definition at line 417 of file qtreewidget.h.
 { return (view ? view->isFirstItemColumnSpanned(this) : false); }
isHidden()
bool QTreeWidgetItem::isHidden () const inline
Returns true if the item is hidden, otherwise returns false.
Since
4.2
See also
setHidden()
Definition at line 405 of file qtreewidget.h.
Referenced by QTreeWidgetItemIterator::matchesFlags().
 { return (view ? view->isItemHidden(this) : false); }
isSelected()
bool QTreeWidgetItem::isSelected () const inline
Returns true if the item is selected, otherwise returns false.
Since
4.2
See also
setSelected()
Definition at line 399 of file qtreewidget.h.
Referenced by QTreeWidgetItemIterator::matchesFlags().
 { return (view ? view->isItemSelected(this) : false); }
itemChanged()
void QTreeWidgetItem::itemChanged () private
Warning
This function is not part of the public interface.
Definition at line 2393 of file qtreewidget.cpp.
Referenced by emitDataChanged(), QTreeWidgetItemPrivate::propagateDisabled(), and setFlags().
 {
     if (QTreeModel *model = (view ? qobject_cast<QTreeModel*>(view->model()) : 0))
         model->itemChanged(this);
 }
operator<()
bool QTreeWidgetItem::operator< (const QTreeWidgetItem & other) const virtual
Returns true if the text in the item is less than the text in the other item, otherwise returns false.
Definition at line 1985 of file qtreewidget.cpp.
 {
     int column = view ? view->sortColumn() : 0;
     const QVariant v1 = data(column, Qt::DisplayRole);
     const QVariant v2 = other.data(column, Qt::DisplayRole);
     return QAbstractItemModelPrivate::variantLessThan(v1, v2);
 }
operator=()
QTreeWidgetItem & QTreeWidgetItem::operator= (const QTreeWidgetItem & other)
Assigns other's data and flags to this item.
Note that type() and treeWidget() are not copied.
This function is useful when reimplementing clone().
See also
data(), flags()
Definition at line 2061 of file qtreewidget.cpp.
 {
     values = other.values;
     d->display = other.d->display;
     d->policy = other.d->policy;
     itemFlags = other.itemFlags;
     return *this;
 }
parent()
QTreeWidgetItem * QTreeWidgetItem::parent () const inline
Returns the item's parent.
See also
child()
Definition at line 183 of file qtreewidget.h.
Referenced by clone(), QTreeWidget::dropEvent(), QTreeWidgetItemIteratorPrivate::ensureValidIterator(), QTreeModel::index(), QTreeWidgetItemIteratorPrivate::next(), QTreeWidgetItemIteratorPrivate::nextSibling(), QTreeModel::parent(), QTreeWidgetItemIteratorPrivate::previous(), QTreeWidgetItemPrivate::propagateDisabled(), QTreeWidgetItemIterator::QTreeWidgetItemIterator(), and setFlags().
 { return par; }
read()
void QTreeWidgetItem::read (QDataStream & in) virtual
Reads the item from stream in.
This only reads data into a single item.
See also
write()
Definition at line 2000 of file qtreewidget.cpp.
Referenced by operator>>().
 {
     // convert from streams written before we introduced display (4.2.0)
     if (in.version() < QDataStream::Qt_4_2) {
         d->display.clear();
         in >> values;
         // move the display value over to the display string list
         for (int column = 0; column < values.count(); ++column) {
             d->display << QVariant();
             for (int i = 0; i < values.at(column).count(); ++i) {
                 if (values.at(column).at(i).role == Qt::DisplayRole) {
                     d->display[column] = values.at(column).at(i).value;
                     values[column].remove(i--);
                 }
             }
         }
     } else {
         in >> values >> d->display;
     }
 }
removeChild()
void QTreeWidgetItem::removeChild (QTreeWidgetItem * child)
Removes the given item indicated by child.
The removed item will not be deleted.
Definition at line 2131 of file qtreewidget.cpp.
 {
     (void)takeChild(children.indexOf(child));
 }
setBackground()
void QTreeWidgetItem::setBackground (int column, const QBrush & brush) inline
Sets the background brush of the label in the given column to the specified brush.
Since
4.2
See also
setForeground()
Definition at line 149 of file qtreewidget.h.
         { setData(column, Qt::BackgroundRole, brush); }
setBackgroundColor()
void QTreeWidgetItem::setBackgroundColor (int column, const QColor & color) inline
This function is deprecated.
Use setBackground() instead.
Definition at line 144 of file qtreewidget.h.
         { setData(column, Qt::BackgroundColorRole, color); }
setCheckState()
void QTreeWidgetItem::setCheckState (int column, Qt::CheckState state) inline
Sets the item in the given column check state to be state.
See also
checkState()
Definition at line 164 of file qtreewidget.h.
         { setData(column, Qt::CheckStateRole, state); }
setChildIndicatorPolicy()
void QTreeWidgetItem::setChildIndicatorPolicy (QTreeWidgetItem::ChildIndicatorPolicy policy)
Sets the item indicator policy.
This policy decides when the tree branch expand/collapse indicator is shown. The default value is ShowForChildren.
See also
childIndicatorPolicy()
Definition at line 1761 of file qtreewidget.cpp.
 {
     if (d->policy == policy)
         return;
     d->policy = policy;
     if (!view)
         return;
     view->scheduleDelayedItemsLayout();
 }
setData()
void QTreeWidgetItem::setData (int column, int role, const QVariant & value) virtual
Sets the value for the item's column and role to the given value.
The role describes the type of data specified by value, and is defined by the Qt::ItemDataRole enum.
Definition at line 1881 of file qtreewidget.cpp.
Referenced by QTreeModel::setData(), setData(), and QTreeModel::setHeaderData().
 {
     if (column < 0)
         return;
     QTreeModel *model = (view ? qobject_cast<QTreeModel*>(view->model()) : 0);
     switch (role) {
     case Qt::EditRole:
     case Qt::DisplayRole: {
         if (values.count() <= column) {
             if (model && this == model->headerItem)
                 model->setColumnCount(column + 1);
             else
                 values.resize(column + 1);
         }
         if (d->display.count() <= column) {
             for (int i = d->display.count() - 1; i < column - 1; ++i)
                 d->display.append(QVariant());
             d->display.append(value);
         } else if (d->display[column] != value) {
             d->display[column] = value;
         } else {
             return; // value is unchanged
         }
     } break;
     case Qt::CheckStateRole:
         if (itemFlags & Qt::ItemIsTristate) {
             for (int i = 0; i < children.count(); ++i) {
                 QTreeWidgetItem *child = children.at(i);
                 if (child->data(column, role).isValid()) {// has a CheckState
                     Qt::ItemFlags f = itemFlags; // a little hack to avoid multiple dataChanged signals
                     itemFlags &= ~Qt::ItemIsTristate;
                     child->setData(column, role, value);
                     itemFlags = f;
                 }
             }
         }
         // Don't break, but fall through
     default:
         if (column < values.count()) {
             bool found = false;
             QVector<QWidgetItemData> column_values = values.at(column);
             for (int i = 0; i < column_values.count(); ++i) {
                 if (column_values.at(i).role == role) {
                     if (column_values.at(i).value == value)
                         return; // value is unchanged
                     values[column][i].value = value;
                     found = true;
                     break;
                 }
             }
             if (!found)
                 values[column].append(QWidgetItemData(role, value));
         } else {
             if (model && this == model->headerItem)
                 model->setColumnCount(column + 1);
             else
                 values.resize(column + 1);
             values[column].append(QWidgetItemData(role, value));
         }
     }
     if (model) {
         model->emitDataChanged(this, column);
         if (role == Qt::CheckStateRole) {
             QTreeWidgetItem *p;
             for (p = par; p && (p->itemFlags & Qt::ItemIsTristate); p = p->par)
                 model->emitDataChanged(p, column);
         }
     }
 }
setDisabled()
void QTreeWidgetItem::setDisabled (bool disabled) inline
Disables the item if disabled is true; otherwise enables the item.
Since
4.3
See also
setFlags()
Definition at line 420 of file qtreewidget.h.
 { setFlags(disabled ? (flags() & ~Qt::ItemIsEnabled) : flags() | Qt::ItemIsEnabled); }
setExpanded()
void QTreeWidgetItem::setExpanded (bool expand) inline
Expands the item if expand is true, otherwise collapses the item.
Since
4.2
Warning
The QTreeWidgetItem must be added to the QTreeWidget before calling this function.
See also
isExpanded()
Definition at line 408 of file qtreewidget.h.
 { if (view) view->setItemExpanded(this, aexpand); }
setFirstColumnSpanned()
void QTreeWidgetItem::setFirstColumnSpanned (bool span) inline
Sets the first section to span all columns if span is true; otherwise all item sections are shown.
Since
4.3
See also
isFirstColumnSpanned()
Definition at line 414 of file qtreewidget.h.
 { if (view) view->setFirstItemColumnSpanned(this, aspan); }
setFlags()
void QTreeWidgetItem::setFlags (Qt::ItemFlags flags)
Sets the flags for the item to the given flags.
These determine whether the item can be selected or modified. This is often used to disable an item.
See also
flags()
Definition at line 1795 of file qtreewidget.cpp.
Referenced by setDisabled().
 {
     const bool enable = (flags & Qt::ItemIsEnabled);
     const bool changedState = bool(itemFlags & Qt::ItemIsEnabled) != enable;
     const bool changedExplicit = d->disabled != !enable;
     d->disabled = !enable;
     if (enable && par && !(par->itemFlags & Qt::ItemIsEnabled)) // inherit from parent
         itemFlags = flags & ~Qt::ItemIsEnabled;
     else // this item is explicitly disabled or has no parent
         itemFlags = flags;
     if (changedState && changedExplicit) { // if the propagate the change to the children
         QStack<QTreeWidgetItem*> parents;
         parents.push(this);
         while (!parents.isEmpty()) {
             QTreeWidgetItem *parent = parents.pop();
             for (int i = 0; i < parent->children.count(); ++i) {
                 QTreeWidgetItem *child = parent->children.at(i);
                 if (!child->d->disabled) { // if not explicitly disabled
                     parents.push(child);
                     if (enable)
                         child->itemFlags = child->itemFlags | Qt::ItemIsEnabled;
                     else
                         child->itemFlags = child->itemFlags & ~Qt::ItemIsEnabled;
                     child->itemChanged(); // ### we may want to optimize this
                 }
             }
         }
     }
     itemChanged();
 }
setFont()
void QTreeWidgetItem::setFont (int column, const QFont & font) inline
Sets the font used to display the text in the given column to the given font.
See also
font() setText() setForeground()
Definition at line 247 of file qtreewidget.h.
 { setData(column, Qt::FontRole, afont); }
setForeground()
void QTreeWidgetItem::setForeground (int column, const QBrush & brush) inline
Sets the foreground brush of the label in the given column to the specified brush.
Since
4.2
See also
setBackground()
Definition at line 159 of file qtreewidget.h.
         { setData(column, Qt::ForegroundRole, brush); }
setHidden()
void QTreeWidgetItem::setHidden (bool hide) inline
Hides the item if hide is true, otherwise shows the item.
Since
4.2
See also
isHidden()
Definition at line 402 of file qtreewidget.h.
 { if (view) view->setItemHidden(this, ahide); }
setIcon()
void QTreeWidgetItem::setIcon (int column, const QIcon & icon) inline
Sets the icon to be displayed in the given column to icon.
See also
icon(), setText(), {QAbstractItemView::iconSize}{iconSize}
Definition at line 229 of file qtreewidget.h.
 { setData(column, Qt::DecorationRole, aicon); }
setSelected()
void QTreeWidgetItem::setSelected (bool select) inline
Sets the selected state of the item to select.
Since
4.2
See also
isSelected()
Definition at line 396 of file qtreewidget.h.
 { if (view) view->setItemSelected(this, aselect); }
setSizeHint()
void QTreeWidgetItem::setSizeHint (int column, const QSize & size) inline
Sets the size hint for the tree item in the given column to be size.
Since
4.1
If no size hint is set, the item delegate will compute the size hint based on the item data.
Definition at line 169 of file qtreewidget.h.
         { setData(column, Qt::SizeHintRole, size); }
setStatusTip()
void QTreeWidgetItem::setStatusTip (int column, const QString & statusTip) inline
Sets the status tip for the given column to the given statusTip.
QTreeWidget mouse tracking needs to be enabled for this feature to work.
See also
statusTip() setToolTip() setWhatsThis()
Definition at line 233 of file qtreewidget.h.
 { setData(column, Qt::StatusTipRole, astatusTip); }
setText()
void QTreeWidgetItem::setText (int column, const QString & text) inline
Sets the text to be displayed in the given column to the given text.
See also
text() setFont() setForeground()
Definition at line 226 of file qtreewidget.h.
Referenced by QTreeWidgetItem(), and QTreeWidget::setHeaderLabels().
 { setData(column, Qt::DisplayRole, atext); }
setTextAlignment()
void QTreeWidgetItem::setTextAlignment (int column, int alignment) inline
Sets the text alignment for the label in the given column to the alignment specified (see Qt::AlignmentFlag).
Definition at line 139 of file qtreewidget.h.
         { setData(column, Qt::TextAlignmentRole, alignment); }
setTextColor()
void QTreeWidgetItem::setTextColor (int column, const QColor & color) inline
This function is deprecated.
Use setForeground() instead.
Definition at line 154 of file qtreewidget.h.
         { setData(column, Qt::TextColorRole, color); }
setToolTip()
void QTreeWidgetItem::setToolTip (int column, const QString & toolTip) inline
Sets the tooltip for the given column to toolTip.
See also
toolTip() setStatusTip() setWhatsThis()
Definition at line 238 of file qtreewidget.h.
 { setData(column, Qt::ToolTipRole, atoolTip); }
setWhatsThis()
void QTreeWidgetItem::setWhatsThis (int column, const QString & whatsThis) inline
Sets the "What's This?" help for the given column to whatsThis.
See also
whatsThis() setStatusTip() setToolTip()
Definition at line 243 of file qtreewidget.h.
 { setData(column, Qt::WhatsThisRole, awhatsThis); }
sizeHint()
QSize QTreeWidgetItem::sizeHint (int column) const inline
Returns the size hint set for the tree item in the given column (see QSize).
Since
4.1
Definition at line 167 of file qtreewidget.h.
         { return qvariant_cast<QSize>(data(column, Qt::SizeHintRole)); }
sortChildren() [1/2]
void QTreeWidgetItem::sortChildren (int column, Qt::SortOrder order) inline
Sorts the children of the item using the given order, by the values in the given column.
Since
4.2
Note
This function does nothing if the item is not associated with a QTreeWidget.
Definition at line 204 of file qtreewidget.h.
Referenced by QTreeModel::sort().
         { sortChildren(column, order, false); }
sortChildren() [2/2]
void QTreeWidgetItem::sortChildren (int column, Qt::SortOrder order, bool climb) private
Sorts the children by the value in the given column, in the order specified.
Warning
This function is not part of the public interface.
If climb is true, the items below each of the children will also be sorted.
Definition at line 2308 of file qtreewidget.cpp.
 {
     QTreeModel *model = (view ? qobject_cast<QTreeModel*>(view->model()) : 0);
     if (!model)
         return;
     if (model->isChanging())
         return;
     QTreeModel::SkipSorting skipSorting(model);
     int oldSortColumn = view->d_func()->explicitSortColumn;
     view->d_func()->explicitSortColumn = column;
     emit model->layoutAboutToBeChanged();
     d->sortChildren(column, order, climb);
     emit model->layoutChanged();
     view->d_func()->explicitSortColumn = oldSortColumn;
 }
statusTip()
QString QTreeWidgetItem::statusTip (int column) const inline
Returns the status tip for the contents of the given column.
See also
setStatusTip()
Definition at line 117 of file qtreewidget.h.
         { return data(column, Qt::StatusTipRole).toString(); }
takeChild()
QTreeWidgetItem * QTreeWidgetItem::takeChild (int index)
Removes the item at index and returns it, otherwise return 0.
Definition at line 2139 of file qtreewidget.cpp.
Referenced by QTreeWidget::dropEvent(), and QTreeModel::removeRows().
 {
     // we move this outside the check of the index to allow executing
     // pending sorts from inline functions, using this function (hack)
     QTreeModel *model = (view ? qobject_cast<QTreeModel*>(view->model()) : 0);
     if (model) {
         // This will trigger a layoutChanged signal, thus we might want to optimize
         // this function by not emitting the rowsRemoved signal etc to the view.
         // On the other hand we also need to make sure that the selectionmodel
         // is updated in case we take an item that is selected.
         model->skipPendingSort = false;
         model->executePendingSort();
     }
     if (index >= 0 && index < children.count()) {
         if (model) model->beginRemoveItems(this, index, 1);
         QTreeWidgetItem *item = children.takeAt(index);
         item->par = 0;
         QStack<QTreeWidgetItem*> stack;
         stack.push(item);
         while (!stack.isEmpty()) {
             QTreeWidgetItem *i = stack.pop();
             i->view = 0;
             for (int c = 0; c < i->children.count(); ++c)
                 stack.push(i->children.at(c));
         }
         d->propagateDisabled(item);
         if (model) model->endRemoveRows();
         return item;
     }
     return 0;
 }
takeChildren()
QList< QTreeWidgetItem * > QTreeWidgetItem::takeChildren ()
Removes the list of children and returns it, otherwise returns an empty list.
Since
4.1
Definition at line 2248 of file qtreewidget.cpp.
 {
     QList<QTreeWidgetItem*> removed;
     if (children.count() > 0) {
         QTreeModel *model = (view ? qobject_cast<QTreeModel*>(view->model()) : 0);
         if (model) {
             // This will trigger a layoutChanged signal, thus we might want to optimize
             // this function by not emitting the rowsRemoved signal etc to the view.
             // On the other hand we also need to make sure that the selectionmodel
             // is updated in case we take an item that is selected.
             model->executePendingSort();
         }
         if (model) model->beginRemoveItems(this, 0, children.count());
         for (int n = 0; n < children.count(); ++n) {
             QTreeWidgetItem *item = children.at(n);
             item->par = 0;
             QStack<QTreeWidgetItem*> stack;
             stack.push(item);
             while (!stack.isEmpty()) {
                 QTreeWidgetItem *i = stack.pop();
                 i->view = 0;
                 for (int c = 0; c < i->children.count(); ++c)
                     stack.push(i->children.at(c));
             }
             d->propagateDisabled(item);
         }
         removed = children;
         children.clear(); // detach
         if (model) model->endRemoveItems();
     }
     return removed;
 }
text()
QString QTreeWidgetItem::text (int column) const inline
Returns the text in the specified column.
See also
setText()
Definition at line 109 of file qtreewidget.h.
         { return data(column, Qt::DisplayRole).toString(); }
textAlignment()
int QTreeWidgetItem::textAlignment (int column) const inline
Returns the text alignment for the label in the given column (see Qt::AlignmentFlag).
Definition at line 137 of file qtreewidget.h.
         { return data(column, Qt::TextAlignmentRole).toInt(); }
textColor()
QColor QTreeWidgetItem::textColor (int column) const inline
This function is deprecated.
Use foreground() instead.
Definition at line 152 of file qtreewidget.h.
         { return qvariant_cast<QColor>(data(column, Qt::TextColorRole)); }
toolTip()
QString QTreeWidgetItem::toolTip (int column) const inline
Returns the tool tip for the given column.
See also
setToolTip()
Definition at line 122 of file qtreewidget.h.
         { return data(column, Qt::ToolTipRole).toString(); }
treeWidget()
QTreeWidget * QTreeWidgetItem::treeWidget () const inline
Returns the tree widget that contains the item.
Definition at line 85 of file qtreewidget.h.
Referenced by QTreeWidgetItemIteratorPrivate::ensureValidIterator(), and QTreeWidgetItemIteratorPrivate::nextSibling().
 { return view; }
type()
int QTreeWidgetItem::type () const inline
Returns the type passed to the QTreeWidgetItem constructor.
Definition at line 203 of file qtreewidget.h.
 { return rtti; }
whatsThis()
QString QTreeWidgetItem::whatsThis (int column) const inline
Returns the "What's This?" help for the contents of the given column.
See also
setWhatsThis()
Definition at line 128 of file qtreewidget.h.
         { return data(column, Qt::WhatsThisRole).toString(); }
write()
void QTreeWidgetItem::write (QDataStream & out) const virtual
Writes the item to stream out.
This only writes data from one single item.
See also
read()
Definition at line 2026 of file qtreewidget.cpp.
Referenced by operator<<().
 {
     out << values << d->display;
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & out, const QTreeWidgetItem & item) related
Writes the tree widget item item to stream out.
This operator uses QTreeWidgetItem::write().
See also
{Serializing Qt Data Types}
Definition at line 2422 of file qtreewidget.cpp.
 {
     item.write(out);
     return out;
 }
operator>>()
QDataStream & operator>> (QDataStream & in, QTreeWidgetItem & item) related
Reads a tree widget item from stream in into item.
This operator uses QTreeWidgetItem::read().
See also
{Serializing Qt Data Types}
Definition at line 2440 of file qtreewidget.cpp.
 {
     item.read(in);
     return in;
 }
QTreeModel
friend class QTreeModel friend
Definition at line 65 of file qtreewidget.h.
QTreeWidget
friend class QTreeWidget friend
Definition at line 66 of file qtreewidget.h.
QTreeWidgetItemIterator
friend class QTreeWidgetItemIterator friend
Definition at line 68 of file qtreewidget.h.
QTreeWidgetItemPrivate
friend class QTreeWidgetItemPrivate friend
Definition at line 69 of file qtreewidget.h.
QTreeWidgetPrivate
friend class QTreeWidgetPrivate friend
Definition at line 67 of file qtreewidget.h.
Properties
children
QList<QTreeWidgetItem*> QTreeWidgetItem::children private
Definition at line 222 of file qtreewidget.h.
Referenced by addChild(), addChildren(), childrenCheckState(), QTreeModel::clear(), clone(), data(), QTreeModel::ensureSorted(), QTreeModel::index(), insertChild(), insertChildren(), QTreeModel::insertColumns(), QTreeModel::insertRows(), QTreeWidgetItemPrivate::propagateDisabled(), QTreeWidgetItem(), QTreeWidgetItemIterator::QTreeWidgetItemIterator(), QTreeModel::removeRows(), setData(), setFlags(), takeChild(), takeChildren(), and ~QTreeWidgetItem().
d
QTreeWidgetItemPrivate* QTreeWidgetItem::d private
Definition at line 220 of file qtreewidget.h.
Referenced by QTreeWidgetPrivate::_q_selectionChanged(), addChild(), childIndicatorPolicy(), data(), QTreeModel::hasChildren(), QTreeModel::index(), insertChild(), insertChildren(), QTreeModel::insertColumns(), QTreeWidget::isItemSelected(), operator=(), QTreeWidgetItemPrivate::propagateDisabled(), QTreeWidgetItem(), read(), setChildIndicatorPolicy(), QTreeModel::setColumnCount(), setData(), setFlags(), QTreeWidget::setItemSelected(), sortChildren(), takeChild(), takeChildren(), write(), and ~QTreeWidgetItem().
itemFlags
Qt::ItemFlags QTreeWidgetItem::itemFlags private
Definition at line 223 of file qtreewidget.h.
Referenced by data(), flags(), operator=(), QTreeWidgetItemPrivate::propagateDisabled(), QTreeModel::QTreeModel(), setData(), and setFlags().
par
QTreeWidgetItem* QTreeWidgetItem::par private
Definition at line 221 of file qtreewidget.h.
Referenced by QTreeModel::clear(), clone(), insertChild(), insertChildren(), QTreeModel::insertRows(), QTreeWidgetItemPrivate::propagateDisabled(), setData(), setFlags(), takeChild(), takeChildren(), and ~QTreeWidgetItem().
rtti
int QTreeWidgetItem::rtti private
Definition at line 216 of file qtreewidget.h.
values
QVector< QVector<QWidgetItemData> > QTreeWidgetItem::values private
Definition at line 218 of file qtreewidget.h.
Referenced by data(), insertChild(), QTreeModel::insertColumns(), QTreeModel::itemData(), QTreeWidget::mimeData(), operator=(), QTreeWidgetItem(), read(), QTreeModel::setColumnCount(), setData(), and write().
view
QTreeWidget* QTreeWidgetItem::view private
Definition at line 219 of file qtreewidget.h.
Referenced by QTreeModel::clear(), executePendingSort(), insertChild(), insertChildren(), QTreeModel::insertRows(), isExpanded(), isFirstColumnSpanned(), isHidden(), isSelected(), itemChanged(), operator<(), QTreeModel::QTreeModel(), QTreeWidgetItemIterator::QTreeWidgetItemIterator(), QTreeModel::removeRows(), setChildIndicatorPolicy(), QTreeModel::setColumnCount(), setData(), setExpanded(), setFirstColumnSpanned(), QTreeWidget::setHeaderItem(), setHidden(), setSelected(), sortChildren(), takeChild(), takeChildren(), QTreeModel::~QTreeModel(), and ~QTreeWidgetItem().
The documentation for this class was generated from the following files:
/src/gui/itemviews/qtreewidget.h
/src/gui/itemviews/qtreewidget.cpp