Qt 4.8: QSvgIconEngine Class Reference
QSvgIconEngine Class Reference
#include <qsvgiconengine.h>
Public Functions
QSize actualSize (const QSize &size, QIcon::Mode mode, QIcon::State state)
Returns the actual size of the icon the engine provides for the requested size, mode and state.
void addFile (const QString &fileName, const QSize &size, QIcon::Mode mode, QIcon::State state)
Called by QIcon::addFile().
void addPixmap (const QPixmap &pixmap, QIcon::Mode mode, QIcon::State state)
Called by QIcon::addPixmap().
QIconEngineV2 * clone () const
Returns a clone of this icon engine.
QString key () const
Returns a key that identifies this icon engine.
void paint (QPainter *painter, const QRect &rect, QIcon::Mode mode, QIcon::State state)
Uses the given painter to paint the icon with the required mode and state into the rectangle rect.
QPixmap pixmap (const QSize &size, QIcon::Mode mode, QIcon::State state)
Returns the icon as a pixmap with the required size, mode, and state.
QSvgIconEngine ()
QSvgIconEngine (const QSvgIconEngine &other)
bool read (QDataStream &in)
Reads icon engine contents from the QDataStream in.
bool write (QDataStream &out) const
Writes the contents of this engine to the QDataStream out.
~QSvgIconEngine ()
Public Functions inherited from QIconEngineV2
QList< QSize > availableSizes (QIcon::Mode mode=QIcon::Normal, QIcon::State state=QIcon::Off)
Returns sizes of all images that are contained in the engine for the specific mode and state.
QString iconName ()
Returns the name used to create the engine, if available.
virtual void virtual_hook (int id, void *data)
Additional method to allow extending QIconEngineV2 without adding new virtual methods (and without breaking binary compatibility).
Public Functions inherited from QIconEngine
virtual ~QIconEngine ()
Destroys the icon engine.
Properties
QSharedDataPointer< QSvgIconEnginePrivate > d
Additional Inherited Members
Public Types inherited from QIconEngineV2
enum IconEngineHook { AvailableSizesHook = 1, IconNameHook }
These enum values are used for virtual_hook() to allow additional queries to icon engine without breaking binary compatibility.
Detailed Description
Definition at line 54 of file qsvgiconengine.h.
Constructors and Destructors
QSvgIconEngine() [1/2]
QSvgIconEngine::QSvgIconEngine ()
Definition at line 95 of file qsvgiconengine.cpp.
Referenced by clone().
     : d(new QSvgIconEnginePrivate)
 {
 }
QSvgIconEngine() [2/2]
QSvgIconEngine::QSvgIconEngine (const QSvgIconEngine & other)
Definition at line 100 of file qsvgiconengine.cpp.
     : QIconEngineV2(other), d(new QSvgIconEnginePrivate)
 {
     d->svgFiles = other.d->svgFiles;
     if (other.d->svgBuffers)
         d->svgBuffers = new QHash<int, QByteArray>(*other.d->svgBuffers);
     if (other.d->addedPixmaps)
         d->addedPixmaps = new QHash<int, QPixmap>(*other.d->addedPixmaps);
 }
~QSvgIconEngine()
QSvgIconEngine::~QSvgIconEngine ()
Definition at line 111 of file qsvgiconengine.cpp.
 {
 }
Functions
actualSize()
QSize QSvgIconEngine::actualSize (const QSize & size, QIcon::Mode mode, QIcon::State state) virtual
Returns the actual size of the icon the engine provides for the requested size, mode and state.
The default implementation returns the given size.
Reimplemented from QIconEngine.
Definition at line 116 of file qsvgiconengine.cpp.
Referenced by pixmap().
 {
     if (d->addedPixmaps) {
         QPixmap pm = d->addedPixmaps->value(d->hashKey(mode, state));
         if (!pm.isNull() && pm.size() == size)
             return size;
     }
     QPixmap pm = pixmap(size, mode, state);
     if (pm.isNull())
         return QSize();
     return pm.size();
 }
addFile()
void QSvgIconEngine::addFile (const QString & fileName, const QSize & size, QIcon::Mode mode, QIcon::State state) virtual
Called by QIcon::addFile().
Adds a specialized pixmap from the file with the given fileName, size, mode and state. The default pixmap-based engine stores any supplied file names, and it loads the pixmaps on demand instead of using scaled pixmaps if the size of a pixmap matches the size of icon requested. Custom icon engines that implement scalable vector formats are free to ignores any extra files.
Reimplemented from QIconEngine.
Definition at line 206 of file qsvgiconengine.cpp.
Referenced by QSvgIconPlugin::create().
 {
     if (!fileName.isEmpty()) {
         QString abs = fileName;
         if (fileName.at(0) != QLatin1Char(':'))
             abs = QFileInfo(fileName).absoluteFilePath();
         if (abs.endsWith(QLatin1String(".svg"), Qt::CaseInsensitive)
 #ifndef QT_NO_COMPRESS
                 || abs.endsWith(QLatin1String(".svgz"), Qt::CaseInsensitive)
                 || abs.endsWith(QLatin1String(".svg.gz"), Qt::CaseInsensitive))
 #endif
         {
             QSvgRenderer renderer(abs);
             if (renderer.isValid()) {
                 d->stepSerialNum();
                 d->svgFiles.insert(d->hashKey(mode, state), abs);
             }
         } else {
             QPixmap pm(abs);
             if (!pm.isNull())
                 addPixmap(pm, mode, state);
         }
     }
 }
addPixmap()
void QSvgIconEngine::addPixmap (const QPixmap & pixmap, QIcon::Mode mode, QIcon::State state) virtual
Called by QIcon::addPixmap().
Adds a specialized pixmap for the given mode and state. The default pixmap-based engine stores any supplied pixmaps, and it uses them instead of scaled pixmaps if the size of a pixmap matches the size of icon requested. Custom icon engines that implement scalable vector formats are free to ignores any extra pixmaps.
Reimplemented from QIconEngine.
Definition at line 196 of file qsvgiconengine.cpp.
Referenced by addFile().
 {
     if (!d->addedPixmaps)
         d->addedPixmaps = new QHash<int, QPixmap>;
     d->stepSerialNum();
     d->addedPixmaps->insert(d->hashKey(mode, state), pixmap);
 }
clone()
QIconEngineV2 * QSvgIconEngine::clone () const virtual
Returns a clone of this icon engine.
Reimplemented from QIconEngineV2.
Definition at line 243 of file qsvgiconengine.cpp.
 {
     return new QSvgIconEngine(*this);
 }
key()
QString QSvgIconEngine::key () const virtual
Returns a key that identifies this icon engine.
Reimplemented from QIconEngineV2.
Definition at line 238 of file qsvgiconengine.cpp.
Referenced by read(), and write().
 {
     return QLatin1String("svg");
 }
paint()
void QSvgIconEngine::paint (QPainter * painter, const QRect & rect, QIcon::Mode mode, QIcon::State state) virtual
Uses the given painter to paint the icon with the required mode and state into the rectangle rect.
Implements QIconEngine.
Definition at line 232 of file qsvgiconengine.cpp.
 {
     painter->drawPixmap(rect, pixmap(rect.size(), mode, state));
 }
pixmap()
QPixmap QSvgIconEngine::pixmap (const QSize & size, QIcon::Mode mode, QIcon::State state) virtual
Returns the icon as a pixmap with the required size, mode, and state.
The default implementation creates a new pixmap and calls paint() to fill it.
Reimplemented from QIconEngine.
Definition at line 153 of file qsvgiconengine.cpp.
Referenced by actualSize(), addPixmap(), paint(), and read().
 {
     QPixmap pm;
     QString pmckey(d->pmcKey(size, mode, state));
     if (QPixmapCache::find(pmckey, pm))
         return pm;
     if (d->addedPixmaps) {
         pm = d->addedPixmaps->value(d->hashKey(mode, state));
         if (!pm.isNull() && pm.size() == size)
             return pm;
     }
     QSvgRenderer renderer;
     d->loadDataForModeAndState(&renderer, mode, state);
     if (!renderer.isValid())
         return pm;
     QSize actualSize = renderer.defaultSize();
     if (!actualSize.isNull())
         actualSize.scale(size, Qt::KeepAspectRatio);
     QImage img(actualSize, QImage::Format_ARGB32_Premultiplied);
     img.fill(0x00000000);
     QPainter p(&img);
     renderer.render(&p);
     p.end();
     pm = QPixmap::fromImage(img);
     QStyleOption opt(0);
     opt.palette = QApplication::palette();
     QPixmap generated = QApplication::style()->generatedIconPixmap(mode, pm, &opt);
     if (!generated.isNull())
         pm = generated;
     if (!pm.isNull())
         QPixmapCache::insert(pmckey, pm);
     return pm;
 }
read()
bool QSvgIconEngine::read (QDataStream & in) virtual
Reads icon engine contents from the QDataStream in.
Returns true if the contents were read; otherwise returns false.
QIconEngineV2's default implementation always return false.
Reimplemented from QIconEngineV2.
Definition at line 249 of file qsvgiconengine.cpp.
 {
     d = new QSvgIconEnginePrivate;
     d->svgBuffers = new QHash<int, QByteArray>;
     if (in.version() >= QDataStream::Qt_4_4) {
         int isCompressed;
         QHash<int, QString> fileNames;  // For memoryoptimization later
         in >> fileNames >> isCompressed >> *d->svgBuffers;
 #ifndef QT_NO_COMPRESS
         if (!isCompressed) {
             foreach(int key, d->svgBuffers->keys())
                 d->svgBuffers->insert(key, qCompress(d->svgBuffers->value(key)));
         }
 #else
         if (isCompressed) {
             qWarning("QSvgIconEngine: Can not decompress SVG data");
             d->svgBuffers->clear();
         }
 #endif
         int hasAddedPixmaps;
         in >> hasAddedPixmaps;
         if (hasAddedPixmaps) {
             d->addedPixmaps = new QHash<int, QPixmap>;
             in >> *d->addedPixmaps;
         }
     }
     else {
         QPixmap pixmap;
         QByteArray data;
         uint mode;
         uint state;
         int num_entries;
         in >> data;
         if (!data.isEmpty()) {
 #ifndef QT_NO_COMPRESS
             data = qUncompress(data);
 #endif
             if (!data.isEmpty())
                 d->svgBuffers->insert(d->hashKey(QIcon::Normal, QIcon::Off), data);
         }
         in >> num_entries;
         for (int i=0; i<num_entries; ++i) {
             if (in.atEnd())
                 return false;
             in >> pixmap;
             in >> mode;
             in >> state;
             // The pm list written by 4.3 is buggy and/or useless, so ignore.
             //addPixmap(pixmap, QIcon::Mode(mode), QIcon::State(state));
         }
     }
     return true;
 }
write()
bool QSvgIconEngine::write (QDataStream & out) const virtual
Writes the contents of this engine to the QDataStream out.
Returns true if the contents were written; otherwise returns false.
QIconEngineV2's default implementation always return false.
Reimplemented from QIconEngineV2.
Definition at line 307 of file qsvgiconengine.cpp.
 {
     if (out.version() >= QDataStream::Qt_4_4) {
         int isCompressed = 0;
 #ifndef QT_NO_COMPRESS
         isCompressed = 1;
 #endif
         QHash<int, QByteArray> svgBuffers;
         if (d->svgBuffers)
             svgBuffers = *d->svgBuffers;
         foreach(int key, d->svgFiles.keys()) {
             QByteArray buf;
             QFile f(d->svgFiles.value(key));
             if (f.open(QIODevice::ReadOnly))
                 buf = f.readAll();
 #ifndef QT_NO_COMPRESS
             buf = qCompress(buf);
 #endif
             svgBuffers.insert(key, buf);
         }
         out << d->svgFiles << isCompressed << svgBuffers;
         if (d->addedPixmaps)
             out << (int)1 << *d->addedPixmaps;
         else
             out << (int)0;
     }
     else {
         QByteArray buf;
         if (d->svgBuffers)
             buf = d->svgBuffers->value(d->hashKey(QIcon::Normal, QIcon::Off));
         if (buf.isEmpty()) {
             QString svgFile = d->svgFiles.value(d->hashKey(QIcon::Normal, QIcon::Off));
             if (!svgFile.isEmpty()) {
                 QFile f(svgFile);
                 if (f.open(QIODevice::ReadOnly))
                     buf = f.readAll();
             }
         }
 #ifndef QT_NO_COMPRESS
         buf = qCompress(buf);
 #endif
         out << buf;
         // 4.3 has buggy handling of added pixmaps, so don't write any
         out << (int)0;
     }
     return true;
 }
Properties
d
QSharedDataPointer<QSvgIconEnginePrivate> QSvgIconEngine::d private
Definition at line 78 of file qsvgiconengine.h.
Referenced by actualSize(), addFile(), addPixmap(), pixmap(), QSvgIconEngine(), read(), and write().
The documentation for this class was generated from the following files:
/src/plugins/iconengines/svgiconengine/qsvgiconengine.h
/src/plugins/iconengines/svgiconengine/qsvgiconengine.cpp