Qt 4.8: QGLTextureGlyphCache Class Reference
QGLTextureGlyphCache Class Reference
#include <qtextureglyphcache_gl_p.h>
Public Types
enum FilterMode { Nearest, Linear }
Public Types inherited from QFontEngineGlyphCache
enum Type { Raster_RGBMask, Raster_A8, Raster_Mono }
Public Functions
void clear ()
const QGLContext * context () const
void contextDeleted (const QGLContext *context)
virtual void createTextureData (int width, int height)
virtual void fillTexture (const Coord &c, glyph_t glyph, QFixed subPixelPosition)
FilterMode filterMode () const
void freeResource (void *)
virtual int glyphPadding () const
int height () const
virtual int maxTextureHeight () const
virtual int maxTextureWidth () const
QGLTextureGlyphCache (const QGLContext *context, QFontEngineGlyphCache::Type type, const QTransform &matrix)
virtual void resizeTextureData (int width, int height)
int serialNumber () const
void setContext (const QGLContext *context)
void setFilterMode (FilterMode m)
void setPaintEnginePrivate (QGL2PaintEngineExPrivate *p)
GLuint texture () const
int width () const
~QGLTextureGlyphCache ()
Public Functions inherited from QImageTextureGlyphCache
virtual int glyphMargin () const
const QImage & image () const
QImageTextureGlyphCache (QFontEngineGlyphCache::Type type, const QTransform &matrix)
Public Functions inherited from QTextureGlyphCache
void createCache (int width, int height)
void fillInPendingGlyphs ()
bool isNull () const
bool populate (QFontEngine *fontEngine, int numGlyphs, const glyph_t *glyphs, const QFixedPoint *positions)
QTextureGlyphCache (QFontEngineGlyphCache::Type type, const QTransform &matrix)
void resizeCache (int width, int height)
QFixed subPixelPositionForX (QFixed x) const
QImage textureMapForGlyph (glyph_t g, QFixed subPixelPosition) const
virtual ~QTextureGlyphCache ()
Public Functions inherited from QFontEngineGlyphCache
Type cacheType () const
QFontEngineGlyphCache (const QTransform &matrix, Type type)
virtual ~QFontEngineGlyphCache ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QGLContextGroupResourceBase
QGLContextGroupResourceBase ()
virtual ~QGLContextGroupResourceBase ()
void insert (const QGLContext *context, void *value)
void * value (const QGLContext *context)
void cleanup (const QGLContext *context)
void cleanup (const QGLContext *context, void *value)
Properties
const QGLContext * ctx
QGLShaderProgram * m_blitProgram
FilterMode m_filterMode
int m_serialNumber
GLfloat m_textureCoordinateArray [8]
QGLContextGroupResource< QGLGlyphTexture > m_textureResource
GLfloat m_vertexCoordinateArray [8]
QGL2PaintEngineExPrivate * pex
Additional Inherited Members
Public Variables inherited from QTextureGlyphCache
QHash< GlyphAndSubPixelPosition, Coord > coords
Public Variables inherited from QFontEngineGlyphCache
QTransform m_transform
QFontEngineGlyphCache::Type m_type
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QTextureGlyphCache
int calculateSubPixelPositionCount (glyph_t) const
Protected Variables inherited from QTextureGlyphCache
QFontEngine * m_current_fontengine
int m_currentRowHeight
int m_cx
int m_cy
int m_h
QHash< GlyphAndSubPixelPosition, Coord > m_pendingGlyphs
int m_subPixelPositionCount
int m_w
Protected Variables inherited from QGLContextGroupResourceBase
QList< QGLContextGroup * > m_groups
Detailed Description
Definition at line 103 of file qtextureglyphcache_gl_p.h.
Enumerations
FilterMode
enum QGLTextureGlyphCache::FilterMode
Enumerator
Nearest
Linear
Definition at line 140 of file qtextureglyphcache_gl_p.h.
                     {
         Nearest,
         Linear
     };
Constructors and Destructors
QGLTextureGlyphCache()
QGLTextureGlyphCache::QGLTextureGlyphCache (const QGLContext * context, QFontEngineGlyphCache::Type type, const QTransform & matrix)
Definition at line 58 of file qtextureglyphcache_gl.cpp.
     : QImageTextureGlyphCache(type, matrix), QGLContextGroupResourceBase()
     , ctx(0)
     , pex(0)
     , m_blitProgram(0)
     , m_filterMode(Nearest)
     , m_serialNumber(qgltextureglyphcache_serial_number.fetchAndAddRelaxed(1))
 {
 #ifdef QT_GL_TEXTURE_GLYPH_CACHE_DEBUG
     qDebug(" -> QGLTextureGlyphCache() %p for context %p.", this, ctx);
 #endif
     setContext(context);
     m_vertexCoordinateArray[0] = -1.0f;
     m_vertexCoordinateArray[1] = -1.0f;
     m_vertexCoordinateArray[2] =  1.0f;
     m_vertexCoordinateArray[3] = -1.0f;
     m_vertexCoordinateArray[4] =  1.0f;
     m_vertexCoordinateArray[5] =  1.0f;
     m_vertexCoordinateArray[6] = -1.0f;
     m_vertexCoordinateArray[7] =  1.0f;
     m_textureCoordinateArray[0] = 0.0f;
     m_textureCoordinateArray[1] = 0.0f;
     m_textureCoordinateArray[2] = 1.0f;
     m_textureCoordinateArray[3] = 0.0f;
     m_textureCoordinateArray[4] = 1.0f;
     m_textureCoordinateArray[5] = 1.0f;
     m_textureCoordinateArray[6] = 0.0f;
     m_textureCoordinateArray[7] = 1.0f;
 }
~QGLTextureGlyphCache()
QGLTextureGlyphCache::~QGLTextureGlyphCache ()
Definition at line 90 of file qtextureglyphcache_gl.cpp.
 {
 #ifdef QT_GL_TEXTURE_GLYPH_CACHE_DEBUG
     qDebug(" -> ~QGLTextureGlyphCache() %p.", this);
 #endif
     delete m_blitProgram;
 }
Functions
clear()
void QGLTextureGlyphCache::clear ()
Definition at line 382 of file qtextureglyphcache_gl.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs().
 {
     if (ctx != 0) {
         m_textureResource.cleanup(ctx);
         m_w = 0;
         m_h = 0;
         m_cx = 0;
         m_cy = 0;
         m_currentRowHeight = 0;
         coords.clear();
     }
 }
context()
const QGLContext* QGLTextureGlyphCache::context () const inline
Definition at line 136 of file qtextureglyphcache_gl_p.h.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs(), and setContext().
 { return ctx; }
contextDeleted()
void QGLTextureGlyphCache::contextDeleted (const QGLContext * context) inline virtual
Reimplemented from QGLContextGroupResourceBase.
Definition at line 149 of file qtextureglyphcache_gl_p.h.
{
         if (ctx == context)
             ctx = 0;
     }
createTextureData()
void QGLTextureGlyphCache::createTextureData (int width, int height) virtual
Reimplemented from QImageTextureGlyphCache.
Definition at line 104 of file qtextureglyphcache_gl.cpp.
Referenced by resizeTextureData().
 {
     if (ctx == 0) {
         qWarning("QGLTextureGlyphCache::createTextureData: Called with no context");
         return;
     }
     // create in QImageTextureGlyphCache baseclass is meant to be called
     // only to create the initial image and does not preserve the content,
     // so we don't call when this function is called from resize.
     if ((!QGLFramebufferObject::hasOpenGLFramebufferObjects() || ctx->d_ptr->workaround_brokenFBOReadBack) && image().isNull())
         QImageTextureGlyphCache::createTextureData(width, height);
     // Make the lower glyph texture size 16 x 16.
     if (width < 16)
         width = 16;
     if (height < 16)
         height = 16;
     QGLGlyphTexture *glyphTexture = m_textureResource.value(ctx);
     glGenTextures(1, &glyphTexture->m_texture);
     glBindTexture(GL_TEXTURE_2D, glyphTexture->m_texture);
     glyphTexture->m_width = width;
     glyphTexture->m_height = height;
     if (m_type == QFontEngineGlyphCache::Raster_RGBMask) {
         QVarLengthArray<uchar> data(width * height * 4);
         for (int i = 0; i < data.size(); ++i)
             data[i] = 0;
         glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, &data[0]);
     } else {
         QVarLengthArray<uchar> data(width * height);
         for (int i = 0; i < data.size(); ++i)
             data[i] = 0;
         glTexImage2D(GL_TEXTURE_2D, 0, GL_ALPHA, width, height, 0, GL_ALPHA, GL_UNSIGNED_BYTE, &data[0]);
     }
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
     m_filterMode = Nearest;
 }
fillTexture()
void QGLTextureGlyphCache::fillTexture (const Coord & c, glyph_t glyph, QFixed subPixelPosition) virtual
Reimplemented from QImageTextureGlyphCache.
Definition at line 281 of file qtextureglyphcache_gl.cpp.
 {
     if (ctx == 0) {
         qWarning("QGLTextureGlyphCache::fillTexture: Called with no context");
         return;
     }
     QGLGlyphTexture *glyphTexture = m_textureResource.value(ctx);
     if (!QGLFramebufferObject::hasOpenGLFramebufferObjects() || ctx->d_ptr->workaround_brokenFBOReadBack) {
         QImageTextureGlyphCache::fillTexture(c, glyph, subPixelPosition);
         glBindTexture(GL_TEXTURE_2D, glyphTexture->m_texture);
         const QImage &texture = image();
         const uchar *bits = texture.constBits();
         bits += c.y * texture.bytesPerLine() + c.x;
         for (int i=0; i<c.h; ++i) {
             glTexSubImage2D(GL_TEXTURE_2D, 0, c.x, c.y + i, c.w, 1, GL_ALPHA, GL_UNSIGNED_BYTE, bits);
             bits += texture.bytesPerLine();
         }
         return;
     }
     QImage mask = textureMapForGlyph(glyph, subPixelPosition);
     const int maskWidth = mask.width();
     const int maskHeight = mask.height();
     if (mask.format() == QImage::Format_Mono) {
         mask = mask.convertToFormat(QImage::Format_Indexed8);
         for (int y = 0; y < maskHeight; ++y) {
             uchar *src = (uchar *) mask.scanLine(y);
             for (int x = 0; x < maskWidth; ++x)
                 src[x] = -src[x]; // convert 0 and 1 into 0 and 255
         }
     } else if (mask.format() == QImage::Format_RGB32) {
         // Make the alpha component equal to the average of the RGB values.
         // This is needed when drawing sub-pixel antialiased text on translucent targets.
         for (int y = 0; y < maskHeight; ++y) {
             quint32 *src = (quint32 *) mask.scanLine(y);
             for (int x = 0; x < maskWidth; ++x) {
                 uchar r = src[x] >> 16;
                 uchar g = src[x] >> 8;
                 uchar b = src[x];
                 quint32 avg = (quint32(r) + quint32(g) + quint32(b) + 1) / 3; // "+1" for rounding.
                 src[x] = (src[x] & 0x00ffffff) | (avg << 24);
             }
         }
     }
     glBindTexture(GL_TEXTURE_2D, glyphTexture->m_texture);
     if (mask.format() == QImage::Format_RGB32) {
         glTexSubImage2D(GL_TEXTURE_2D, 0, c.x, c.y, maskWidth, maskHeight, GL_BGRA, GL_UNSIGNED_BYTE, mask.bits());
     } else {
         // glTexSubImage2D() might cause some garbage to appear in the texture if the mask width is
         // not a multiple of four bytes. The bug appeared on a computer with 32-bit Windows Vista
         // and nVidia GeForce 8500GT. GL_UNPACK_ALIGNMENT is set to four bytes, 'mask' has a
         // multiple of four bytes per line, and most of the glyph shows up correctly in the
         // texture, which makes me think that this is a driver bug.
         // One workaround is to make sure the mask width is a multiple of four bytes, for instance
         // by converting it to a format with four bytes per pixel. Another is to copy one line at a
         // time.
         if (!ctx->d_ptr->workaround_brokenAlphaTexSubImage_init) {
             // don't know which driver versions exhibit this bug, so be conservative for now
             const QByteArray vendorString(reinterpret_cast<const char*>(glGetString(GL_VENDOR)));
             ctx->d_ptr->workaround_brokenAlphaTexSubImage = vendorString.indexOf("NVIDIA") >= 0;
             ctx->d_ptr->workaround_brokenAlphaTexSubImage_init = true;
         }
         if (ctx->d_ptr->workaround_brokenAlphaTexSubImage) {
             for (int i = 0; i < maskHeight; ++i)
                 glTexSubImage2D(GL_TEXTURE_2D, 0, c.x, c.y + i, maskWidth, 1, GL_ALPHA, GL_UNSIGNED_BYTE, mask.scanLine(i));
         } else {
             glTexSubImage2D(GL_TEXTURE_2D, 0, c.x, c.y, maskWidth, maskHeight, GL_ALPHA, GL_UNSIGNED_BYTE, mask.bits());
         }
     }
 }
filterMode()
FilterMode QGLTextureGlyphCache::filterMode () const inline
Definition at line 144 of file qtextureglyphcache_gl_p.h.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs().
 { return m_filterMode; }
freeResource()
void QGLTextureGlyphCache::freeResource (void *) inline virtual
Implements QGLContextGroupResourceBase.
Definition at line 153 of file qtextureglyphcache_gl_p.h.
 { ctx = 0; }
glyphPadding()
int QGLTextureGlyphCache::glyphPadding () const virtual
Reimplemented from QTextureGlyphCache.
Definition at line 358 of file qtextureglyphcache_gl.cpp.
 {
     return 1;
 }
height()
int QGLTextureGlyphCache::height () const inline
Definition at line 127 of file qtextureglyphcache_gl_p.h.
Referenced by createTextureData(), and QGL2PaintEngineExPrivate::drawCachedGlyphs().
{
         QGLTextureGlyphCache *that = const_cast<QGLTextureGlyphCache *>(this);
         QGLGlyphTexture *glyphTexture = that->m_textureResource.value(ctx);
         return glyphTexture ? glyphTexture->m_height : 0;
     }
maxTextureHeight()
int QGLTextureGlyphCache::maxTextureHeight () const virtual
Reimplemented from QTextureGlyphCache.
Definition at line 371 of file qtextureglyphcache_gl.cpp.
 {
     if (ctx == 0)
         return QImageTextureGlyphCache::maxTextureHeight();
     if (ctx->d_ptr->workaround_brokenTexSubImage)
         return qMin(1024, ctx->d_ptr->maxTextureSize());
     else
         return ctx->d_ptr->maxTextureSize();
 }
maxTextureWidth()
int QGLTextureGlyphCache::maxTextureWidth () const virtual
Reimplemented from QTextureGlyphCache.
Definition at line 363 of file qtextureglyphcache_gl.cpp.
 {
     if (ctx == 0)
         return QImageTextureGlyphCache::maxTextureWidth();
     else
         return ctx->d_ptr->maxTextureSize();
 }
resizeTextureData()
void QGLTextureGlyphCache::resizeTextureData (int width, int height) virtual
Reimplemented from QImageTextureGlyphCache.
Definition at line 149 of file qtextureglyphcache_gl.cpp.
 {
     if (ctx == 0) {
         qWarning("QGLTextureGlyphCache::resizeTextureData: Called with no context");
         return;
     }
     QGLGlyphTexture *glyphTexture = m_textureResource.value(ctx);
     int oldWidth = glyphTexture->m_width;
     int oldHeight = glyphTexture->m_height;
     // Make the lower glyph texture size 16 x 16.
     if (width < 16)
         width = 16;
     if (height < 16)
         height = 16;
     GLuint oldTexture = glyphTexture->m_texture;
     createTextureData(width, height);
     if (!QGLFramebufferObject::hasOpenGLFramebufferObjects() || ctx->d_ptr->workaround_brokenFBOReadBack) {
         QImageTextureGlyphCache::resizeTextureData(width, height);
         Q_ASSERT(image().depth() == 8);
         glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, width, oldHeight, GL_ALPHA, GL_UNSIGNED_BYTE, image().constBits());
         glDeleteTextures(1, &oldTexture);
         return;
     }
     // ### the QTextureGlyphCache API needs to be reworked to allow
     // ### resizeTextureData to fail
     glBindFramebuffer(GL_FRAMEBUFFER_EXT, glyphTexture->m_fbo);
     GLuint tmp_texture;
     glGenTextures(1, &tmp_texture);
     glBindTexture(GL_TEXTURE_2D, tmp_texture);
     glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, oldWidth, oldHeight, 0,
                  GL_RGBA, GL_UNSIGNED_BYTE, NULL);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
     m_filterMode = Nearest;
     glBindTexture(GL_TEXTURE_2D, 0);
     glFramebufferTexture2D(GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT,
                            GL_TEXTURE_2D, tmp_texture, 0);
     glActiveTexture(GL_TEXTURE0 + QT_IMAGE_TEXTURE_UNIT);
     glBindTexture(GL_TEXTURE_2D, oldTexture);
     if (pex != 0)
         pex->transferMode(BrushDrawingMode);
     glDisable(GL_STENCIL_TEST);
     glDisable(GL_DEPTH_TEST);
     glDisable(GL_SCISSOR_TEST);
     glDisable(GL_BLEND);
     glViewport(0, 0, oldWidth, oldHeight);
     QGLShaderProgram *blitProgram = 0;
     if (pex == 0) {
         if (m_blitProgram == 0) {
             m_blitProgram = new QGLShaderProgram(ctx);
             {
                 QString source;
                 source.append(QLatin1String(qglslMainWithTexCoordsVertexShader));
                 source.append(QLatin1String(qglslUntransformedPositionVertexShader));
                 QGLShader *vertexShader = new QGLShader(QGLShader::Vertex, m_blitProgram);
                 vertexShader->compileSourceCode(source);
                 m_blitProgram->addShader(vertexShader);
             }
             {
                 QString source;
                 source.append(QLatin1String(qglslMainFragmentShader));
                 source.append(QLatin1String(qglslImageSrcFragmentShader));
                 QGLShader *fragmentShader = new QGLShader(QGLShader::Fragment, m_blitProgram);
                 fragmentShader->compileSourceCode(source);
                 m_blitProgram->addShader(fragmentShader);
             }
             m_blitProgram->bindAttributeLocation("vertexCoordsArray", QT_VERTEX_COORDS_ATTR);
             m_blitProgram->bindAttributeLocation("textureCoordArray", QT_TEXTURE_COORDS_ATTR);
             m_blitProgram->link();
         }
         glVertexAttribPointer(QT_VERTEX_COORDS_ATTR, 2, GL_FLOAT, GL_FALSE, 0, m_vertexCoordinateArray);
         glVertexAttribPointer(QT_TEXTURE_COORDS_ATTR, 2, GL_FLOAT, GL_FALSE, 0, m_textureCoordinateArray);
         m_blitProgram->bind();
         m_blitProgram->enableAttributeArray(int(QT_VERTEX_COORDS_ATTR));
         m_blitProgram->enableAttributeArray(int(QT_TEXTURE_COORDS_ATTR));
         m_blitProgram->disableAttributeArray(int(QT_OPACITY_ATTR));
         blitProgram = m_blitProgram;
     } else {
         pex->setVertexAttributePointer(QT_VERTEX_COORDS_ATTR, m_vertexCoordinateArray);
         pex->setVertexAttributePointer(QT_TEXTURE_COORDS_ATTR, m_textureCoordinateArray);
         pex->shaderManager->useBlitProgram();
         blitProgram = pex->shaderManager->blitProgram();
     }
     blitProgram->setUniformValue("imageTexture", QT_IMAGE_TEXTURE_UNIT);
     glDrawArrays(GL_TRIANGLE_FAN, 0, 4);
     glBindTexture(GL_TEXTURE_2D, glyphTexture->m_texture);
     glCopyTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, 0, 0, oldWidth, oldHeight);
     glFramebufferRenderbuffer(GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT,
                               GL_RENDERBUFFER_EXT, 0);
     glDeleteTextures(1, &tmp_texture);
     glDeleteTextures(1, &oldTexture);
     glBindFramebuffer(GL_FRAMEBUFFER_EXT, ctx->d_ptr->current_fbo);
     if (pex != 0) {
         glViewport(0, 0, pex->width, pex->height);
         pex->updateClipScissorTest();
     }
 }
serialNumber()
int QGLTextureGlyphCache::serialNumber () const inline
Definition at line 138 of file qtextureglyphcache_gl_p.h.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs().
 { return m_serialNumber; }
setContext()
void QGLTextureGlyphCache::setContext (const QGLContext * context)
Definition at line 98 of file qtextureglyphcache_gl.cpp.
Referenced by QGLTextureGlyphCache().
 {
     ctx = context;
     m_h = 0;
 }
setFilterMode()
void QGLTextureGlyphCache::setFilterMode (FilterMode m) inline
Definition at line 145 of file qtextureglyphcache_gl_p.h.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs().
 { m_filterMode = m; }
setPaintEnginePrivate()
void QGLTextureGlyphCache::setPaintEnginePrivate (QGL2PaintEngineExPrivate * p) inline
Definition at line 133 of file qtextureglyphcache_gl_p.h.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs().
 { pex = p; }
texture()
GLuint QGLTextureGlyphCache::texture () const inline
Definition at line 116 of file qtextureglyphcache_gl_p.h.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs(), and fillTexture().
{
         QGLTextureGlyphCache *that = const_cast<QGLTextureGlyphCache *>(this);
         QGLGlyphTexture *glyphTexture = that->m_textureResource.value(ctx);
         return glyphTexture ? glyphTexture->m_texture : 0;
     }
width()
int QGLTextureGlyphCache::width () const inline
Definition at line 122 of file qtextureglyphcache_gl_p.h.
Referenced by createTextureData(), and QGL2PaintEngineExPrivate::drawCachedGlyphs().
{
         QGLTextureGlyphCache *that = const_cast<QGLTextureGlyphCache *>(this);
         QGLGlyphTexture *glyphTexture = that->m_textureResource.value(ctx);
         return glyphTexture ? glyphTexture->m_width : 0;
     }
Properties
ctx
const QGLContext* QGLTextureGlyphCache::ctx private
Definition at line 158 of file qtextureglyphcache_gl_p.h.
Referenced by clear(), createTextureData(), fillTexture(), maxTextureHeight(), maxTextureWidth(), QGLTextureGlyphCache(), resizeTextureData(), and setContext().
m_blitProgram
QGLShaderProgram* QGLTextureGlyphCache::m_blitProgram private
Definition at line 160 of file qtextureglyphcache_gl_p.h.
Referenced by resizeTextureData(), and ~QGLTextureGlyphCache().
m_filterMode
FilterMode QGLTextureGlyphCache::m_filterMode private
Definition at line 161 of file qtextureglyphcache_gl_p.h.
Referenced by createTextureData(), and resizeTextureData().
m_serialNumber
int QGLTextureGlyphCache::m_serialNumber private
Definition at line 166 of file qtextureglyphcache_gl_p.h.
m_textureCoordinateArray
GLfloat QGLTextureGlyphCache::m_textureCoordinateArray[8] private
Definition at line 164 of file qtextureglyphcache_gl_p.h.
Referenced by QGLTextureGlyphCache(), and resizeTextureData().
m_textureResource
QGLContextGroupResource<QGLGlyphTexture> QGLTextureGlyphCache::m_textureResource private
Definition at line 156 of file qtextureglyphcache_gl_p.h.
Referenced by clear(), createTextureData(), fillTexture(), height(), resizeTextureData(), texture(), and width().
m_vertexCoordinateArray
GLfloat QGLTextureGlyphCache::m_vertexCoordinateArray[8] private
Definition at line 163 of file qtextureglyphcache_gl_p.h.
Referenced by QGLTextureGlyphCache(), and resizeTextureData().
pex
QGL2PaintEngineExPrivate* QGLTextureGlyphCache::pex private
Definition at line 159 of file qtextureglyphcache_gl_p.h.
Referenced by resizeTextureData().
The documentation for this class was generated from the following files:
/src/opengl/gl2paintengineex/qtextureglyphcache_gl_p.h
/src/opengl/gl2paintengineex/qtextureglyphcache_gl.cpp