Qt 4.8: QDate Class Reference
QDate Class Reference
The QDate class provides date functions.
#include <qdatetime.h>
Public Types
enum MonthNameType { DateFormat = 0, StandaloneFormat }
This enum describes the types of the string representation used for the month name.
Public Functions
QDate addDays (int days) const
Returns a QDate object containing a date ndays later than the date of this object (or earlier if ndays is negative).
QDate addMonths (int months) const
Returns a QDate object containing a date nmonths later than the date of this object (or earlier if nmonths is negative).
QDate addYears (int years) const
Returns a QDate object containing a date nyears later than the date of this object (or earlier if nyears is negative).
int day () const
Returns the day of the month (1 to 31) of this date.
int dayOfWeek () const
Returns the weekday (1 = Monday to 7 = Sunday) for this date.
int dayOfYear () const
Returns the day of the year (1 to 365 or 366 on leap years) for this date.
int daysInMonth () const
Returns the number of days in the month (28 to 31) for this date.
int daysInYear () const
Returns the number of days in the year (365 or 366) for this date.
int daysTo (const QDate &) const
Returns the number of days from this date to d (which is negative if d is earlier than this date).
void getDate (int *year, int *month, int *day)
bool isNull () const
Returns true if the date is null; otherwise returns false.
bool isValid () const
Returns true if this date is valid; otherwise returns false.
int month () const
Returns the number corresponding to the month of this date, using the following convention:
bool operator!= (const QDate &other) const
Returns true if this date is different from d; otherwise returns false.
bool operator< (const QDate &other) const
Returns true if this date is earlier than d; otherwise returns false.
bool operator<= (const QDate &other) const
Returns true if this date is earlier than or equal to d; otherwise returns false.
bool operator== (const QDate &other) const
Returns true if this date is equal to d; otherwise returns false.
bool operator> (const QDate &other) const
Returns true if this date is later than d; otherwise returns false.
bool operator>= (const QDate &other) const
Returns true if this date is later than or equal to d; otherwise returns false.
QDate ()
Constructs a null date.
QDate (int y, int m, int d)
Constructs a date with year y, month m and day d.
bool setDate (int year, int month, int day)
Sets the date's year, month, and day.
bool setYMD (int y, int m, int d)
Sets the date's year y, month m, and day d.
int toJulianDay () const
Converts the date to a Julian day.
QString toString (Qt::DateFormat f=Qt::TextDate) const
Returns the date as a string.
QString toString (const QString &format) const
Returns the date as a string.
int weekNumber (int *yearNum=0) const
Returns the week number (1 to 53), and stores the year in {yearNumber} unless yearNumber is null (the default).
int year () const
Returns the year of this date.
Static Public Functions
static QDate currentDate ()
Returns the current date, as reported by the system clock.
static QDate fromJulianDay (int jd)
Converts the Julian day jd to a QDate.
static QDate fromString (const QString &s, Qt::DateFormat f=Qt::TextDate)
Returns the QDate represented by the string, using the format given, or an invalid date if the string cannot be parsed.
static QDate fromString (const QString &s, const QString &format)
Returns the QDate represented by the string, using the format given, or an invalid date if the string cannot be parsed.
static uint gregorianToJulian (int y, int m, int d)
This function has a confusing name and shouldn't be part of the API anyway, since we have toJulian() and fromJulian().
static bool isLeapYear (int year)
Returns true if the specified year is a leap year; otherwise returns false.
static bool isValid (int y, int m, int d)
Returns true if the specified date (year, month, and day) is valid; otherwise returns false.
static void julianToGregorian (uint jd, int &y, int &m, int &d)
This function has a confusing name and shouldn't be part of the API anyway, since we have toJulian() and fromJulian().
static QString longDayName (int weekday)
Returns the long version of the name of the weekday.
static QString longDayName (int weekday, MonthNameType type)
Returns the long name of the weekday for the representation specified by type.
static QString longMonthName (int month)
Returns the long version of the name of the month.
static QString longMonthName (int month, MonthNameType type)
Returns the long name of the month for the representation specified by type.
static QString shortDayName (int weekday)
Returns the short version of the name of the weekday.
static QString shortDayName (int weekday, MonthNameType type)
Returns the short name of the weekday for the representation specified by type.
static QString shortMonthName (int month)
Returns the short version of the name of the month.
static QString shortMonthName (int month, MonthNameType type)
Returns the short name of the month for the representation specified by type.
Properties
uint jd
Friends
Q_CORE_EXPORT QDataStream & operator<< (QDataStream &, const QDate &)
Writes the date to stream out.
Q_CORE_EXPORT QDataStream & operator>> (QDataStream &, QDate &)
Reads a date from stream in into the date.
class QDateTime
class QDateTimePrivate
Detailed Description
The QDate class provides date functions.
Note
This class or function is reentrant.
A QDate object contains a calendar date, i.e. year, month, and day numbers, in the Gregorian calendar. (see QDate G and J {Use of Gregorian and Julian Calendars} for dates prior to 15 October 1582). It can read the current date from the system clock. It provides functions for comparing dates, and for manipulating dates. For example, it is possible to add and subtract days, months, and years to dates.
A QDate object is typically created either by giving the year, month, and day numbers explicitly. Note that QDate interprets two digit years as is, i.e., years 0 - 99. A QDate can also be constructed with the static function currentDate(), which creates a QDate object containing the system clock's date. An explicit date can also be set using setDate(). The fromString() function returns a QDate given a string and a date format which is used to interpret the date within the string.
The year(), month(), and day() functions provide access to the year, month, and day numbers. Also, dayOfWeek() and dayOfYear() functions are provided. The same information is provided in textual format by the toString(), shortDayName(), longDayName(), shortMonthName(), and longMonthName() functions.
QDate provides a full set of operators to compare two QDate objects where smaller means earlier, and larger means later.
You can increment (or decrement) a date by a given number of days using addDays(). Similarly you can use addMonths() and addYears(). The daysTo() function returns the number of days between two dates.
The daysInMonth() and daysInYear() functions return how many days there are in this date's month and year, respectively. The isLeapYear() function indicates whether a date is in a leap year.
Definition at line 55 of file qdatetime.h.
Enumerations
MonthNameType
enum QDate::MonthNameType
This enum describes the types of the string representation used for the month name.
Since
4.5
DateFormat This type of name can be used for date-to-string formatting.
StandaloneFormat This type is used when you need to enumerate months or weekdays. Usually standalone names are represented in singular forms with capitalized first letter.
Enumerator
DateFormat
StandaloneFormat
Definition at line 58 of file qdatetime.h.
{
         DateFormat = 0,
         StandaloneFormat
     };
Constructors and Destructors
QDate() [1/2]
QDate::QDate () inline
Constructs a null date.
Null dates are invalid.
See also
isNull(), isValid()
Definition at line 63 of file qdatetime.h.
Referenced by addMonths(), addYears(), and fromString().
 { jd = 0; }
QDate() [2/2]
QDate::QDate (int y, int m, int d)
Constructs a date with year y, month m and day d.
If the specified date is invalid, the date is not set and isValid() returns false. A date before 2 January 4713 B.C. is considered invalid.
Warning
Years 0 to 99 are interpreted as is, i.e., years 0-99.
See also
isValid()
Definition at line 313 of file qdatetime.cpp.
 {
     setDate(y, m, d);
 }
Functions
addDays()
QDate QDate::addDays (int ndays) const
Returns a QDate object containing a date ndays later than the date of this object (or earlier if ndays is negative).
See also
addMonths() addYears() daysTo()
Definition at line 989 of file qdatetime.cpp.
Referenced by QDateTime::addDays(), QPatternist::AbstractDateTime::create(), QCalendarModel::dateForCell(), fromDate(), fromTimeStamp(), QTDSResult::gotoNext(), QCalendarView::moveCursor(), QDateTime::setMSecsSinceEpoch(), and QDateTime::setTime_t().
 {
     QDate d;
     // this is basically "d.jd = jd + ndays" with checks for integer overflow
     if (ndays >= 0)
         d.jd = (jd + ndays >= jd) ? jd + ndays : 0;
     else
         d.jd = (jd + ndays < jd) ? jd + ndays : 0;
     return d;
 }
addMonths()
QDate QDate::addMonths (int nmonths) const
Returns a QDate object containing a date nmonths later than the date of this object (or earlier if nmonths is negative).
Note
If the ending day/month combination does not exist in the resulting month/year, this function will return a date that is the latest valid date.
Warning
QDate has a date hole around the days introducing the Gregorian calendar (the days 5 to 14 October 1582, inclusive, do not exist). If the calculation ends in one of those days, QDate will return either October 4 or October 15.
See also
addDays() addYears()
Definition at line 1016 of file qdatetime.cpp.
Referenced by QCalendarWidgetPrivate::_q_monthChanged(), QCalendarWidgetPrivate::_q_nextMonthClicked(), QCalendarWidgetPrivate::_q_prevMonthClicked(), QDateTime::addMonths(), QCalendarView::moveCursor(), and QCalendarView::wheelEvent().
 {
     if (!isValid())
         return QDate();
     if (!nmonths)
         return *this;
     int old_y, y, m, d;
     getDateFromJulianDay(jd, &y, &m, &d);
     old_y = y;
     bool increasing = nmonths > 0;
     while (nmonths != 0) {
         if (nmonths < 0 && nmonths + 12 <= 0) {
             y--;
             nmonths+=12;
         } else if (nmonths < 0) {
             m+= nmonths;
             nmonths = 0;
             if (m <= 0) {
                 --y;
                 m += 12;
             }
         } else if (nmonths - 12 >= 0) {
             y++;
             nmonths -= 12;
         } else if (m == 12) {
             y++;
             m = 0;
         } else {
             m += nmonths;
             nmonths = 0;
             if (m > 12) {
                 ++y;
                 m -= 12;
             }
         }
     }
     // was there a sign change?
     if ((old_y > 0 && y <= 0) ||
         (old_y < 0 && y >= 0))
         // yes, adjust the date by +1 or -1 years
         y += increasing ? +1 : -1;
     // did we end up in the Gregorian/Julian conversion hole?
     if (y == 1582 && m == 10 && d > 4 && d < 15)
         d = increasing ? 15 : 4;
     return fixedDate(y, m, d);
 }
addYears()
QDate QDate::addYears (int nyears) const
Returns a QDate object containing a date nyears later than the date of this object (or earlier if nyears is negative).
Note
If the ending day/month combination does not exist in the resulting year (i.e., if the date was Feb 29 and the final year is not a leap year), this function will return a date that is the latest valid date (that is, Feb 28).
See also
addDays(), addMonths()
Definition at line 1081 of file qdatetime.cpp.
Referenced by QCalendarWidgetPrivate::_q_yearEditingFinished(), and QDateTime::addYears().
 {
     if (!isValid())
         return QDate();
     int y, m, d;
     getDateFromJulianDay(jd, &y, &m, &d);
     int old_y = y;
     y += nyears;
     // was there a sign change?
     if ((old_y > 0 && y <= 0) ||
         (old_y < 0 && y >= 0))
         // yes, adjust the date by +1 or -1 years
         y += nyears > 0 ? +1 : -1;
     return fixedDate(y, m, d);
 }
currentDate()
QDate QDate::currentDate () static
Returns the current date, as reported by the system clock.
If spec is Qt::LocalTime, use the currentDate() overload that takes no parameters instead; otherwise, use QDateTime::currentDateTime().
See also
QTime::currentTime(), QDateTime::currentDateTime()
QDate localDate = QDate::currentDate(Qt::LocalTime); QDate utcDate = QDate::currentDate(Qt::UTC); QDate localDate = QDate::currentDate(); QDate utcDate = QDateTime::currentDateTime().toUTC().date();
See also
QDateTime::toUTC()
Definition at line 3115 of file qdatetime.cpp.
Referenced by _q_parseUnixDir(), QCalendarTextNavigator::applyDate(), QDateTime::currentMSecsSinceEpoch(), macTimeToString(), QCalendarDateValidator::QCalendarDateValidator(), QCalendarModel::QCalendarModel(), qEncodeNtlmv2Response(), qt_eval_days_left(), and QCalendarWidget::showToday().
 {
     QDate d;
     SYSTEMTIME st;
     memset(&st, 0, sizeof(SYSTEMTIME));
     GetLocalTime(&st);
     d.jd = julianDayFromDate(st.wYear, st.wMonth, st.wDay);
     return d;
 }
day()
int QDate::day () const
Returns the day of the month (1 to 31) of this date.
See also
year(), month(), dayOfWeek()
Definition at line 395 of file qdatetime.cpp.
Referenced by _q_fixupDateTime(), _q_parseDosDir(), _q_parseUnixDir(), adjustDate(), QCalendarMonthValidator::applyToDate(), QCalendarYearValidator::applyToDate(), QCalendarModel::cellForDate(), QCalendarModel::columnForFirstOfMonth(), QCalendarModel::data(), QCalendarModel::dateForCell(), QScript::DateTimeToMs(), QLocalePrivate::dateTimeToString(), QDB2Result::exec(), QODBCResult::exec(), QPatternist::DayFromAbstractDateTimeFN::extract(), QDB2Driver::formatValue(), QIBaseDriver::formatValue(), QOCIDriver::formatValue(), QODBCDriver::formatValue(), QPSQLDriver::formatValue(), QPatternist::GMonthDay::fromDateTime(), QPatternist::GDay::fromDateTime(), fromString(), QDateTimeParser::getDigit(), localToUtc(), macDateToString(), macTimeToString(), operator<<(), QDateTimeToDATE(), qMakeOraDate(), QCalendarWidget::setCurrentPage(), QCalendarDayValidator::setDate(), QDateTimeParser::setDigit(), QDateTimeEditPrivate::stepBy(), QCalendarDayValidator::text(), toString(), QSystemLocalePrivate::toString(), QDateTime::toString(), QMYSQLResult::virtual_hook(), QPdfEnginePrivate::writeInfo(), and writeMSDosDate().
 {
     int d;
     getDateFromJulianDay(jd, 0, 0, &d);
     return d;
 }
dayOfWeek()
int QDate::dayOfWeek () const
Returns the weekday (1 = Monday to 7 = Sunday) for this date.
See also
day(), dayOfYear(), Qt::DayOfWeek
Definition at line 408 of file qdatetime.cpp.
Referenced by QCalendarModel::columnForFirstOfMonth(), QScript::DateTimeToMs(), QLocalePrivate::dateTimeToString(), QDateTimeParser::parse(), QCalendarDayValidator::text(), toString(), QDateTime::toString(), and weekNumber().
 {
     return (jd % 7) + 1;
 }
dayOfYear()
int QDate::dayOfYear () const
Returns the day of the year (1 to 365 or 366 on leap years) for this date.
See also
day(), dayOfWeek()
Definition at line 420 of file qdatetime.cpp.
Referenced by QScript::DateTimeToMs(), and weekNumber().
 {
     return jd - julianDayFromDate(year(), 1, 1) + 1;
 }
daysInMonth()
int QDate::daysInMonth () const
Returns the number of days in the month (28 to 31) for this date.
See also
day(), daysInYear()
Definition at line 431 of file qdatetime.cpp.
Referenced by QDateTimeParser::absoluteMax(), QCalendarDayValidator::applyToDate(), fixedDate(), QCalendarView::moveCursor(), QDateTimeParser::parse(), QCalendarWidget::setCurrentPage(), QDateTimeParser::setDigit(), and QDateTimeEditPrivate::stepBy().
 {
     int y, m, d;
     getDateFromJulianDay(jd, &y, &m, &d);
     if (m == 2 && isLeapYear(y))
         return 29;
     else
         return monthDays[m];
 }
daysInYear()
int QDate::daysInYear () const
Returns the number of days in the year (365 or 366) for this date.
See also
day(), daysInMonth()
Definition at line 447 of file qdatetime.cpp.
 {
     int y, m, d;
     getDateFromJulianDay(jd, &y, &m, &d);
     return isLeapYear(y) ? 366 : 365;
 }
daysTo()
int QDate::daysTo (const QDate & d) const
Returns the number of days from this date to d (which is negative if d is earlier than this date).
Example:
QDate d1(1995, 5, 17);  // May 17, 1995
QDate d2(1995, 5, 20);  // May 20, 1995
d1.daysTo(d2);          // returns 3
d2.daysTo(d1);          // returns -3
See also
addDays()
Definition at line 1111 of file qdatetime.cpp.
Referenced by QCalendarModel::cellForDate(), QDateTime::daysTo(), localToUtc(), QDateTime::msecsTo(), qt_eval_days_left(), QDateTime::secsTo(), toDate(), toTimeStamp(), QCalendarWidgetPrivate::updateCurrentPage(), and utcToLocal().
 {
     return d.jd - jd;
 }
fromJulianDay()
static QDate QDate::fromJulianDay (int jd) inline static
Converts the Julian day jd to a QDate.
See also
toJulianDay()
Definition at line 133 of file qdatetime.h.
Referenced by QCalendarModel::QCalendarModel().
 { QDate d; d.jd = jd; return d; }
fromString() [1/2]
QDate QDate::fromString (const QString & string, Qt::DateFormat format = Qt::TextDate) static
Returns the QDate represented by the string, using the format given, or an invalid date if the string cannot be parsed.
Note for Qt::TextDate: It is recommended that you use the English short month names (e.g. "Jan"). Although localized month names can also be used, they depend on the user's locale settings.
Definition at line 1203 of file qdatetime.cpp.
Referenced by QLibraryInfo::buildDate(), convert(), QPSQLResult::data(), QDeclarativeStringConverters::dateFromString(), QTime::fromString(), QDateTime::fromString(), QTDSResult::gotoNext(), and qDateFromString().
 {
     if (s.isEmpty())
         return QDate();
     switch (f) {
     case Qt::ISODate:
         {
             int year(s.mid(0, 4).toInt());
             int month(s.mid(5, 2).toInt());
             int day(s.mid(8, 2).toInt());
             if (year && month && day)
                 return QDate(year, month, day);
         }
         break;
     case Qt::SystemLocaleDate:
     case Qt::SystemLocaleShortDate:
     case Qt::SystemLocaleLongDate:
         return fromString(s, QLocale::system().dateFormat(f == Qt::SystemLocaleLongDate ? QLocale::LongFormat
                                                                                         : QLocale::ShortFormat));
     case Qt::LocaleDate:
     case Qt::DefaultLocaleShortDate:
     case Qt::DefaultLocaleLongDate:
         return fromString(s, QLocale().dateFormat(f == Qt::DefaultLocaleLongDate ? QLocale::LongFormat
                                                                                  : QLocale::ShortFormat));
     default:
 #ifndef QT_NO_TEXTDATE
     case Qt::TextDate: {
         QStringList parts = s.split(QLatin1Char(' '), QString::SkipEmptyParts);
         if (parts.count() != 4) {
             return QDate();
         }
         QString monthName = parts.at(1);
         int month = -1;
         // Assume that English monthnames are the default
         for (int i = 0; i < 12; ++i) {
             if (monthName == QLatin1String(qt_shortMonthNames[i])) {
                 month = i + 1;
                 break;
             }
         }
         // If English names can't be found, search the localized ones
         if (month == -1) {
             for (int i = 1; i <= 12; ++i) {
                 if (monthName == QDate::shortMonthName(i)) {
                     month = i;
                     break;
                 }
             }
         }
         if (month < 1 || month > 12) {
             return QDate();
         }
         bool ok;
         int day = parts.at(2).toInt(&ok);
         if (!ok) {
             return QDate();
         }
         int year = parts.at(3).toInt(&ok);
         if (!ok) {
             return QDate();
         }
         return QDate(year, month, day);
     }
 #else
         break;
 #endif
     }
     return QDate();
 }
fromString() [2/2]
QDate QDate::fromString (const QString & string, const QString & format) static
Returns the QDate represented by the string, using the format given, or an invalid date if the string cannot be parsed.
These expressions may be used for the format:
Expression Output
d The day as a number without a leading zero (1 to 31)
dd The day as a number with a leading zero (01 to 31)
ddd The abbreviated localized day name (e.g. 'Mon' to 'Sun'). Uses QDate::shortDayName().
dddd The long localized day name (e.g. 'Monday' to 'Sunday'). Uses QDate::longDayName().
M The month as a number without a leading zero (1 to 12)
MM The month as a number with a leading zero (01 to 12)
MMM The abbreviated localized month name (e.g. 'Jan' to 'Dec'). Uses QDate::shortMonthName().
MMMM The long localized month name (e.g. 'January' to 'December'). Uses QDate::longMonthName().
yy The year as two digit number (00 to 99)
yyyy The year as four digit number. If the year is negative, a minus sign is prepended in addition.
All other input characters will be treated as text. Any sequence of characters that are enclosed in single quotes will also be treated as text and will not be used as an expression. For example:
QDate date = QDate::fromString("1MM12car2003", "d'MM'MMcaryyyy");
// date is 1 December 2003
If the format is not satisfied, an invalid QDate is returned. The expressions that don't expect leading zeroes (d, M) will be greedy. This means that they will use two digits even if this will put them outside the accepted range of values and leaves too few digits for other sections. For example, the following format string could have meant January 30 but the M will grab two digits, resulting in an invalid date:
QDate date = QDate::fromString("130", "Md"); // invalid
For any field that is not represented in the format the following defaults are used:
Field Default value
Year 1900
Month 1
Day 1
The following examples demonstrate the default values:
QDate::fromString("1.30", "M.d");           // January 30 1900
QDate::fromString("20000110", "yyyyMMdd");  // January 10, 2000
QDate::fromString("20000110", "yyyyMd");    // January 10, 2000
See also
QDateTime::fromString(), QTime::fromString(), QDate::toString(), QDateTime::toString(), QTime::toString()
Definition at line 1347 of file qdatetime.cpp.
 {
     QDate date;
 #ifndef QT_BOOTSTRAPPED
     QDateTimeParser dt(QVariant::Date, QDateTimeParser::FromString);
     if (dt.parseFormat(format))
         dt.fromString(string, &date, 0);
 #else
     Q_UNUSED(string);
     Q_UNUSED(format);
 #endif
     return date;
 }
getDate()
void QDate::getDate (int * year, int * month, int * day)
Since
4.5
Extracts the date's year, month, and day, and assigns them to year, *month, and *day. The pointers may be null.
See also
year(), month(), day(), isValid()
Definition at line 977 of file qdatetime.cpp.
 {
     getDateFromJulianDay(jd, year, month, day);
 }
gregorianToJulian()
uint QDate::gregorianToJulian (int y, int m, int d) static
This function has a confusing name and shouldn't be part of the API anyway, since we have toJulian() and fromJulian().
Warning
This function is not part of the public interface.
Qt 5: remove it
Definition at line 1426 of file qdatetime.cpp.
 {
     return julianDayFromDate(y, m, d);
 }
isLeapYear()
bool QDate::isLeapYear (int year) static
Returns true if the specified year is a leap year; otherwise returns false.
Definition at line 1404 of file qdatetime.cpp.
Referenced by _q_fixupDateTime(), _q_parseUnixDir(), daysInMonth(), daysInYear(), isValid(), and weekNumber().
 {
     if (y < 1582) {
         if ( y < 1) {  // No year 0 in Julian calendar, so -1, -5, -9 etc are leap years
             ++y;
         }
         return y % 4 == 0;
     } else {
         return (y % 4 == 0 && y % 100 != 0) || y % 400 == 0;
     }
 }
isNull()
bool QDate::isNull () const inline
Returns true if the date is null; otherwise returns false.
A null date is invalid.
Note
The behavior of this function is equivalent to isValid().
See also
isValid()
Definition at line 66 of file qdatetime.h.
Referenced by QDateTime::isNull(), isValid(), QDateTimeToDATE(), and QCalendarWidget::setDateTextFormat().
 { return jd == 0; }
isValid() [1/2]
bool QDate::isValid () const
Returns true if this date is valid; otherwise returns false.
See also
isNull()
Definition at line 340 of file qdatetime.cpp.
Referenced by addMonths(), addYears(), QCalendarModel::cellForDate(), convert(), QPatternist::AbstractDateTime::create(), QCalendarModel::data(), QCalendarModel::dateForCell(), QDeclarativeStringConverters::dateFromString(), QLocalePrivate::dateTimeToString(), QDateTimeEditPrivate::emitSignals(), QCalendarModel::flags(), fmtDateTime(), QSqlDriver::formatValue(), QIBaseDriver::formatValue(), QOCIDriver::formatValue(), QDateTimeParser::fromString(), QCalendarView::handleMouseEvent(), QPatternist::AbstractDateTime::isRangeValid(), QDateTime::isValid(), localToUtc(), QCalendarView::mouseMoveEvent(), QCalendarView::mousePressEvent(), QCalendarView::mouseReleaseEvent(), operator<<(), QCalendarDelegate::paint(), QDateTimeParser::parse(), parseDateString(), QDateTime::QDateTime(), QDateTimeEdit::QDateTimeEdit(), QDateTimeToDATE(), QCalendarModel::referenceDate(), setDate(), QDateTimeEdit::setDate(), QDateTime::setDate(), QDateTimeEdit::setDateRange(), QCalendarWidget::setDateRange(), QDateTimeParser::setDigit(), QTime::setHMS(), QCalendarWidget::setMaximumDate(), QDateTimeEdit::setMaximumDate(), QCalendarModel::setMaximumDate(), QCalendarWidget::setMinimumDate(), QDateTimeEdit::setMinimumDate(), QCalendarModel::setMinimumDate(), QCalendarWidget::setSelectedDate(), toString(), QTest::toString(), QTime::toString(), QLocale::toString(), QCalendarWidget::updateCell(), QCalendarWidgetPrivate::updateCurrentPage(), and weekNumber().
 {
     return !isNull();
 }
isValid() [2/2]
bool QDate::isValid (int year, int month, int day) static
Returns true if the specified date (year, month, and day) is valid; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Example:
QDate::isValid(2002, 5, 17);  // true
QDate::isValid(2002, 2, 30);  // false (Feb 30 does not exist)
QDate::isValid(2004, 2, 29);  // true (2004 is a leap year)
QDate::isValid(2000, 2, 29);  // true (2000 is a leap year)
QDate::isValid(2006, 2, 29);  // false (2006 is not a leap year)
QDate::isValid(2100, 2, 29);  // false (2100 is not a leap year)
QDate::isValid(1202, 6, 6);   // true (even though 1202 is pre-Gregorian)
See also
isNull(), setDate()
Definition at line 1377 of file qdatetime.cpp.
 {
     if (year < FIRST_YEAR
         || (year == FIRST_YEAR &&
             (month < FIRST_MONTH
              || (month == FIRST_MONTH && day < FIRST_DAY)))
         || year == 0) // there is no year 0 in the Julian calendar
         return false;
     // passage from Julian to Gregorian calendar
     if (year == 1582 && month == 10 && day > 4 && day < 15)
         return 0;
     return (day > 0 && month > 0 && month <= 12) &&
            (day <= monthDays[month] || (day == 29 && month == 2 && isLeapYear(year)));
 }
julianToGregorian()
void QDate::julianToGregorian (uint jd, int & y, int & m, int & d) static
This function has a confusing name and shouldn't be part of the API anyway, since we have toJulian() and fromJulian().
Warning
This function is not part of the public interface.
Qt 5: remove it
Definition at line 1441 of file qdatetime.cpp.
 {
     getDateFromJulianDay(jd, &y, &m, &d);
 }
longDayName() [1/2]
QString QDate::longDayName (int weekday) static
Returns the long version of the name of the weekday.
The returned name is in normal type which can be used for date formatting.
See also
toString(), shortDayName(), shortMonthName(), longMonthName()
Definition at line 767 of file qdatetime.cpp.
 {
     if (weekday < 1 || weekday > 7) {
         weekday = 1;
     }
     return QLocale::system().dayName(weekday, QLocale::LongFormat);
 }
longDayName() [2/2]
QString QDate::longDayName (int weekday, MonthNameType type) static
Returns the long name of the weekday for the representation specified by type.
Since
4.5
The days are enumerated using the following convention:
1 = "Monday"
2 = "Tuesday"
3 = "Wednesday"
4 = "Thursday"
5 = "Friday"
6 = "Saturday"
7 = "Sunday"
The day names will be localized according to the system's default locale settings.
See also
toString(), shortDayName(), shortMonthName(), longMonthName()
Definition at line 744 of file qdatetime.cpp.
 {
     if (weekday < 1 || weekday > 7) {
         weekday = 1;
     }
     switch (type) {
     case QDate::DateFormat:
         return QLocale::system().dayName(weekday, QLocale::LongFormat);
     case QDate::StandaloneFormat:
         return QLocale::system().standaloneDayName(weekday, QLocale::LongFormat);
     default:
         break;
     }
     return QLocale::system().dayName(weekday, QLocale::LongFormat);
 }
longMonthName() [1/2]
QString QDate::longMonthName (int month) static
Returns the long version of the name of the month.
The returned name is in normal type which can be used for date formatting.
See also
toString(), shortMonthName(), shortDayName(), longDayName()
Definition at line 651 of file qdatetime.cpp.
 {
     if (month < 1 || month > 12) {
         month = 1;
     }
     return QLocale::system().monthName(month, QLocale::LongFormat);
 }
longMonthName() [2/2]
QString QDate::longMonthName (int month, MonthNameType type) static
Returns the long name of the month for the representation specified by type.
Since
4.5
The months are enumerated using the following convention:
1 = "January"
2 = "February"
3 = "March"
4 = "April"
5 = "May"
6 = "June"
7 = "July"
8 = "August"
9 = "September"
10 = "October"
11 = "November"
12 = "December"
The month names will be localized according to the system's default locale settings.
See also
toString(), shortMonthName(), shortDayName(), longDayName()
Definition at line 628 of file qdatetime.cpp.
 {
     if (month < 1 || month > 12) {
         month = 1;
     }
     switch (type) {
     case QDate::DateFormat:
         return QLocale::system().monthName(month, QLocale::LongFormat);
     case QDate::StandaloneFormat:
         return QLocale::system().standaloneMonthName(month, QLocale::LongFormat);
     default:
         break;
     }
     return QString();
 }
month()
int QDate::month () const
Returns the number corresponding to the month of this date, using the following convention:
1 = "January"
2 = "February"
3 = "March"
4 = "April"
5 = "May"
6 = "June"
7 = "July"
8 = "August"
9 = "September"
10 = "October"
11 = "November"
12 = "December"
See also
year(), day()
Definition at line 382 of file qdatetime.cpp.
Referenced by _q_fixupDateTime(), QCalendarWidgetPrivate::_q_monthChanged(), _q_parseDosDir(), _q_parseUnixDir(), QCalendarWidgetPrivate::_q_slotChangeDate(), adjustDate(), QCalendarDayValidator::applyToDate(), QCalendarYearValidator::applyToDate(), QCalendarWidgetPrivate::createNavigationBar(), QScript::DateTimeToMs(), QLocalePrivate::dateTimeToString(), QDB2Result::exec(), QODBCResult::exec(), QPatternist::MonthFromAbstractDateTimeFN::extract(), QCalendarModel::formatForCell(), QDB2Driver::formatValue(), QIBaseDriver::formatValue(), QOCIDriver::formatValue(), QODBCDriver::formatValue(), QPSQLDriver::formatValue(), QPatternist::GMonthDay::fromDateTime(), QPatternist::GYearMonth::fromDateTime(), QPatternist::GMonth::fromDateTime(), fromString(), QDateTimeParser::getDigit(), isValid(), localToUtc(), macDateToString(), macTimeToString(), QCalendarView::moveCursor(), operator<<(), QDateTimeParser::parse(), QDateTimeParser::parseSection(), QCalendarModel::QCalendarModel(), QDateTimeToDATE(), qMakeOraDate(), QCalendarMonthValidator::setDate(), QCalendarWidget::setDateRange(), QDateTimeParser::setDigit(), QCalendarWidget::setMaximumDate(), QCalendarWidget::setMinimumDate(), QCalendarWidget::setSelectedDate(), QCalendarWidget::showSelectedDate(), QCalendarWidget::showToday(), QCalendarMonthValidator::text(), toString(), QSystemLocalePrivate::toString(), QDateTime::toString(), QCalendarWidgetPrivate::updateCurrentPage(), QCalendarWidgetPrivate::updateMonthMenu(), QMYSQLResult::virtual_hook(), QPdfEnginePrivate::writeInfo(), and writeMSDosDate().
 {
     int m;
     getDateFromJulianDay(jd, 0, &m, 0);
     return m;
 }
operator!=()
bool QDate::operator!= (const QDate & other) const inline
Returns true if this date is different from d; otherwise returns false.
Definition at line 108 of file qdatetime.h.
 { return jd != other.jd; }
operator<()
bool QDate::operator< (const QDate & other) const inline
Returns true if this date is earlier than d; otherwise returns false.
Definition at line 109 of file qdatetime.h.
 { return jd < other.jd; }
operator<=()
bool QDate::operator<= (const QDate & other) const inline
Returns true if this date is earlier than or equal to d; otherwise returns false.
Definition at line 110 of file qdatetime.h.
 { return jd <= other.jd; }
operator==()
bool QDate::operator== (const QDate & other) const inline
Returns true if this date is equal to d; otherwise returns false.
Definition at line 107 of file qdatetime.h.
 { return jd == other.jd; }
operator>()
bool QDate::operator> (const QDate & other) const inline
Returns true if this date is later than d; otherwise returns false.
Definition at line 111 of file qdatetime.h.
 { return jd > other.jd; }
operator>=()
bool QDate::operator>= (const QDate & other) const inline
Returns true if this date is later than or equal to d; otherwise returns false.
Definition at line 112 of file qdatetime.h.
 { return jd >= other.jd; }
setDate()
bool QDate::setDate (int year, int month, int day)
Sets the date's year, month, and day.
Since
4.2
Returns true if the date is valid; otherwise returns false.
If the specified date is invalid, the QDate object is set to be invalid. Any date before 2 January 4713 B.C. is considered invalid.
See also
isValid()
Definition at line 959 of file qdatetime.cpp.
Referenced by adjustDate(), fixedDate(), QDate(), and setYMD().
 {
     if (!isValid(year, month, day)) {
         jd = 0;
     } else {
         jd = julianDayFromDate(year, month, day);
     }
     return jd != 0;
 }
setYMD()
bool QDate::setYMD (int y, int m, int d)
Sets the date's year y, month m, and day d.
If y is in the range 0 to 99, it is interpreted as 1900 to 1999.
Use setDate() instead.
Definition at line 937 of file qdatetime.cpp.
Referenced by _q_fixupDateTime(), and operator>>().
 {
     if (uint(y) <= 99)
         y += 1900;
     return setDate(y, m, d);
 }
shortDayName() [1/2]
QString QDate::shortDayName (int weekday) static
Returns the short version of the name of the weekday.
The returned name is in normal type which can be used for date formatting.
See also
toString(), longDayName(), shortMonthName(), longMonthName()
Definition at line 709 of file qdatetime.cpp.
Referenced by toString(), and QDateTime::toString().
 {
     if (weekday < 1 || weekday > 7) {
         weekday = 1;
     }
     return QLocale::system().dayName(weekday, QLocale::ShortFormat);
 }
shortDayName() [2/2]
QString QDate::shortDayName (int weekday, MonthNameType type) static
Returns the short name of the weekday for the representation specified by type.
Since
4.5
The days are enumerated using the following convention:
1 = "Mon"
2 = "Tue"
3 = "Wed"
4 = "Thu"
5 = "Fri"
6 = "Sat"
7 = "Sun"
The day names will be localized according to the system's default locale settings.
See also
toString(), shortMonthName(), longMonthName(), longDayName()
Definition at line 686 of file qdatetime.cpp.
 {
     if (weekday < 1 || weekday > 7) {
         weekday = 1;
     }
     switch (type) {
     case QDate::DateFormat:
         return QLocale::system().dayName(weekday, QLocale::ShortFormat);
     case QDate::StandaloneFormat:
         return QLocale::system().standaloneDayName(weekday, QLocale::ShortFormat);
     default:
         break;
     }
     return QString();
 }
shortMonthName() [1/2]
QString QDate::shortMonthName (int month) static
Returns the short version of the name of the month.
The returned name is in normal type which can be used for date formatting.
See also
toString(), longMonthName(), shortDayName(), longDayName()
Definition at line 591 of file qdatetime.cpp.
Referenced by fromShortMonthName(), fromString(), toString(), and QDateTime::toString().
 {
     return shortMonthName(month, QDate::DateFormat);
 }
shortMonthName() [2/2]
QString QDate::shortMonthName (int month, QDate::MonthNameType type) static
Returns the short name of the month for the representation specified by type.
Since
4.5
The months are enumerated using the following convention:
1 = "Jan"
2 = "Feb"
3 = "Mar"
4 = "Apr"
5 = "May"
6 = "Jun"
7 = "Jul"
8 = "Aug"
9 = "Sep"
10 = "Oct"
11 = "Nov"
12 = "Dec"
The month names will be localized according to the system's default locale settings.
See also
toString(), longMonthName(), shortDayName(), longDayName()
Definition at line 568 of file qdatetime.cpp.
 {
     if (month < 1 || month > 12) {
         month = 1;
     }
     switch (type) {
     case QDate::DateFormat:
         return QLocale::system().monthName(month, QLocale::ShortFormat);
     case QDate::StandaloneFormat:
         return QLocale::system().standaloneMonthName(month, QLocale::ShortFormat);
     default:
         break;
     }
     return QString();
 }
toJulianDay()
int QDate::toJulianDay () const inline
Converts the date to a Julian day.
See also
fromJulianDay()
Definition at line 134 of file qdatetime.h.
Referenced by QDeclarativeCompiler::genLiteralAssignment(), localToUtc(), QDateTimeParser::parse(), and utcToLocal().
 { return jd; }
toString() [1/2]
QString QDate::toString (Qt::DateFormat format = Qt::TextDate) const
Returns the date as a string.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The format parameter determines the format of the string.
If the format is Qt::TextDate, the string is formatted in the default way. QDate::shortDayName() and QDate::shortMonthName() are used to generate the string, so the day and month names will be localized names using the default locale from the system. An example of this formatting is "Sat May 20 1995".
If the format is Qt::ISODate, the string format corresponds to the ISO 8601 extended specification for representations of dates and times, taking the form YYYY-MM-DD, where YYYY is the year, MM is the month of the year (between 01 and 12), and DD is the day of the month between 01 and 31.
If the format is Qt::SystemLocaleShortDate or Qt::SystemLocaleLongDate, the string format depends on the locale settings of the system. Identical to calling QLocale::system().toString(date, QLocale::ShortFormat) or QLocale::system().toString(date, QLocale::LongFormat).
If the format is Qt::DefaultLocaleShortDate or Qt::DefaultLocaleLongDate, the string format depends on the default application locale. This is the locale set with QLocale::setDefault(), or the system locale if no default locale has been set. Identical to calling QLocale().toString(date, QLocale::ShortFormat) or QLocale().toString(date, QLocale::LongFormat).
If the date is invalid, an empty string will be returned.
Warning
The Qt::ISODate format is only valid for years in the range 0 to 9999. This restriction may apply to locale-aware formats as well, depending on the locale settings.
See also
shortDayName(), shortMonthName()
Definition at line 823 of file qdatetime.cpp.
Referenced by QDeclarativeEnginePrivate::formatDate(), QSqlDriver::formatValue(), operator<<(), QTest::toString(), and QDateTime::toString().
 {
     if (!isValid())
         return QString();
     int y, m, d;
     getDateFromJulianDay(jd, &y, &m, &d);
     switch (f) {
     case Qt::SystemLocaleDate:
     case Qt::SystemLocaleShortDate:
     case Qt::SystemLocaleLongDate:
         return QLocale::system().toString(*this, f == Qt::SystemLocaleLongDate ? QLocale::LongFormat
                                                                                : QLocale::ShortFormat);
     case Qt::LocaleDate:
     case Qt::DefaultLocaleShortDate:
     case Qt::DefaultLocaleLongDate:
         return QLocale().toString(*this, f == Qt::DefaultLocaleLongDate ? QLocale::LongFormat
                                                                         : QLocale::ShortFormat);
     default:
 #ifndef QT_NO_TEXTDATE
     case Qt::TextDate:
         {
             return QString::fromLatin1("%0 %1 %2 %3")
                 .arg(shortDayName(dayOfWeek()))
                 .arg(shortMonthName(m))
                 .arg(d)
                 .arg(y);
         }
 #endif
     case Qt::ISODate:
         {
             if (year() < 0 || year() > 9999)
                 return QString();
             QString month(QString::number(m).rightJustified(2, QLatin1Char('0')));
             QString day(QString::number(d).rightJustified(2, QLatin1Char('0')));
             return QString::number(y) + QLatin1Char('-') + month + QLatin1Char('-') + day;
         }
     }
 }
toString() [2/2]
QString QDate::toString (const QString & format) const
Returns the date as a string.
The format parameter determines the format of the result string.
These expressions may be used:
Expression Output
d the day as number without a leading zero (1 to 31)
dd the day as number with a leading zero (01 to 31)
ddd the abbreviated localized day name (e.g. 'Mon' to 'Sun'). Uses QDate::shortDayName().
dddd the long localized day name (e.g. 'Monday' to 'Sunday'). Uses QDate::longDayName().
M the month as number without a leading zero (1 to 12)
MM the month as number with a leading zero (01 to 12)
MMM the abbreviated localized month name (e.g. 'Jan' to 'Dec'). Uses QDate::shortMonthName().
MMMM the long localized month name (e.g. 'January' to 'December'). Uses QDate::longMonthName().
yy the year as two digit number (00 to 99)
yyyy the year as four digit number. If the year is negative, a minus sign is prepended in addition.
All other input characters will be ignored. Any sequence of characters that are enclosed in singlequotes will be treated as text and not be used as an expression. Two consecutive singlequotes ("''") are replaced by a singlequote in the output.
Example format strings (assuming that the QDate is the 20 July 1969):
Format Result
dd.MM.yyyy 20.07.1969
ddd MMMM d yy Sun July 20 69
'The day is' dddd The day is Sunday
If the datetime is invalid, an empty string will be returned.
Warning
The Qt::ISODate format is only valid for years in the range 0 to 9999. This restriction may apply to locale-aware formats as well, depending on the locale settings.
See also
QDateTime::toString() QTime::toString()
Definition at line 915 of file qdatetime.cpp.
 {
     if (year() > 9999)
         return QString();
     return fmtDateTime(format, 0, this);
 }
weekNumber()
int QDate::weekNumber (int * yearNumber = 0) const
Returns the week number (1 to 53), and stores the year in {yearNumber} unless yearNumber is null (the default).
Returns 0 if the date is invalid.
In accordance with ISO 8601, weeks start on Monday and the first Thursday of a year is always in week 1 of that year. Most years have 52 weeks, but some have 53.
{yearNumber} is not always the same as year(). For example, 1 January 2000 has week number 52 in the year 1999, and 31 December 2002 has week number 1 in the year 2003.
Copyright (c) 1989 The Regents of the University of California. All rights reserved.
Redistribution and use in source and binary forms are permitted provided that the above copyright notice and this paragraph are duplicated in all such forms and that any documentation, advertising materials, and other materials related to such distribution and use acknowledge that the software was developed by the University of California, Berkeley. The name of the University may not be used to endorse or promote products derived from this software without specific prior written permission. THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
See also
isValid()
Definition at line 487 of file qdatetime.cpp.
Referenced by QCalendarModel::data().
 {
     if (!isValid())
         return 0;
     int year = QDate::year();
     int yday = dayOfYear() - 1;
     int wday = dayOfWeek();
     if (wday == 7)
         wday = 0;
     int w;
     for (;;) {
         int len;
         int bot;
         int top;
         len = isLeapYear(year) ? 366 : 365;
         /*
         ** What yday (-3 ... 3) does
         ** the ISO year begin on?
         */
         bot = ((yday + 11 - wday) % 7) - 3;
         /*
         ** What yday does the NEXT
         ** ISO year begin on?
         */
         top = bot - (len % 7);
         if (top < -3)
             top += 7;
         top += len;
         if (yday >= top) {
             ++year;
             w = 1;
             break;
         }
         if (yday >= bot) {
             w = 1 + ((yday - bot) / 7);
             break;
         }
         --year;
         yday += isLeapYear(year) ? 366 : 365;
     }
     if (yearNumber != 0)
         *yearNumber = year;
     return w;
 }
year()
int QDate::year () const
Returns the year of this date.
Negative numbers indicate years before 1 A.D. = 1 C.E., such that year -44 is 44 B.C.
See also
month(), day()
Definition at line 353 of file qdatetime.cpp.
Referenced by _q_fixupDateTime(), _q_parseDosDir(), _q_parseUnixDir(), QCalendarWidgetPrivate::_q_slotChangeDate(), QCalendarWidgetPrivate::_q_yearEditingFinished(), QCalendarDayValidator::applyToDate(), QCalendarMonthValidator::applyToDate(), QCalendarWidgetPrivate::createNavigationBar(), QScript::DateTimeToMs(), QLocalePrivate::dateTimeToString(), dayOfYear(), QDB2Result::exec(), QODBCResult::exec(), QPatternist::YearFromAbstractDateTimeFN::extract(), QDB2Driver::formatValue(), QIBaseDriver::formatValue(), QOCIDriver::formatValue(), QODBCDriver::formatValue(), QPSQLDriver::formatValue(), QPatternist::GYearMonth::fromDateTime(), QPatternist::GYear::fromDateTime(), fromString(), QDateTimeParser::getDigit(), localToUtc(), macDateToString(), macTimeToString(), QCalendarView::moveCursor(), operator<<(), QDateTimeParser::parseSection(), QDateTimeParser::potentialValue(), QCalendarModel::QCalendarModel(), QDateTimeToDATE(), qMakeOraDate(), QCalendarYearValidator::setDate(), QCalendarWidget::setDateRange(), QDateTimeParser::setDigit(), QCalendarWidget::setMaximumDate(), QCalendarWidget::setMinimumDate(), QCalendarWidget::setSelectedDate(), QCalendarWidget::showSelectedDate(), QCalendarWidget::showToday(), QCalendarYearValidator::text(), toString(), QSystemLocalePrivate::toString(), QDateTime::toString(), QCalendarWidgetPrivate::updateCurrentPage(), QCalendarWidgetPrivate::updateMonthMenu(), QMYSQLResult::virtual_hook(), weekNumber(), QPdfEnginePrivate::writeInfo(), and writeMSDosDate().
 {
     int y;
     getDateFromJulianDay(jd, &y, 0, 0);
     return y;
 }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & out, const QDate & date) friend
Writes the date to stream out.
See also
{Serializing Qt Data Types}
Definition at line 3812 of file qdatetime.cpp.
 {
     return out << (quint32)(date.jd);
 }
operator>>
QDataStream & operator>> (QDataStream & in, QDate & date) friend
Reads a date from stream in into the date.
See also
{Serializing Qt Data Types}
Definition at line 3828 of file qdatetime.cpp.
 {
     quint32 jd;
     in >> jd;
     date.jd = jd;
     return in;
 }
QDateTime
friend class QDateTime friend
Definition at line 139 of file qdatetime.h.
QDateTimePrivate
friend class QDateTimePrivate friend
Definition at line 140 of file qdatetime.h.
Properties
jd
uint QDate::jd private
Definition at line 137 of file qdatetime.h.
Referenced by addDays(), addMonths(), QDateTimePrivate::addMSecs(), addYears(), currentDate(), QDateTime::currentDateTime(), QDateTime::currentDateTimeUtc(), QDateTime::currentMSecsSinceEpoch(), day(), dayOfWeek(), dayOfYear(), daysInMonth(), daysInYear(), daysTo(), fromJulianDay(), getDate(), month(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), setDate(), QDateTime::toMSecsSinceEpoch(), toString(), and year().
The documentation for this class was generated from the following files:
/src/corelib/tools/qdatetime.h
/src/corelib/tools/qdatetime.cpp