Qt 4.8: QXmlStreamSimpleStack< T > Class Template Reference
QXmlStreamSimpleStack< T > Class Template Reference
#include <qxmlstream_p.h>
Public Functions
const T & at (int index) const
void clear ()
bool isEmpty () const
T & operator[] (int index)
T & pop ()
T & push ()
QXmlStreamSimpleStack ()
T & rawPush ()
void reserve (int extraCapacity)
void resize (int s)
int size () const
const T & top () const
T & top ()
~QXmlStreamSimpleStack ()
Properties
int cap
T * data
int tos
Detailed Description
template<typename T>
class QXmlStreamSimpleStack< T >
Definition at line 644 of file qxmlstream_p.h.
Constructors and Destructors
QXmlStreamSimpleStack()
template<typename T> QXmlStreamSimpleStack< T >::QXmlStreamSimpleStack () inline
Definition at line 648 of file qxmlstream_p.h.
 :data(0), tos(-1), cap(0){}
~QXmlStreamSimpleStack()
template<typename T> QXmlStreamSimpleStack< T >::~QXmlStreamSimpleStack () inline
Definition at line 649 of file qxmlstream_p.h.
 { if (data) qFree(data); }
Functions
at()
template<typename T> const T& QXmlStreamSimpleStack< T >::at (int index) const inline
Definition at line 665 of file qxmlstream_p.h.
 { return data[index]; }
clear()
template<typename T> void QXmlStreamSimpleStack< T >::clear () inline
Definition at line 669 of file qxmlstream_p.h.
Referenced by QXmlStreamReaderPrivate::init().
 { tos = -1; }
isEmpty()
template<typename T> bool QXmlStreamSimpleStack< T >::isEmpty () const inline
Definition at line 668 of file qxmlstream_p.h.
Referenced by QXmlStreamPrivateTagStack::tagStack_pop().
 { return tos < 0; }
operator[]()
template<typename T> T& QXmlStreamSimpleStack< T >::operator[] (int index) inline
Definition at line 664 of file qxmlstream_p.h.
 { return data[index]; }
pop()
template<typename T> T& QXmlStreamSimpleStack< T >::pop () inline
Definition at line 663 of file qxmlstream_p.h.
Referenced by QXmlStreamReaderPrivate::filterCarriageReturn(), QXmlStreamReaderPrivate::getChar(), QXmlStreamReaderPrivate::parse(), and QXmlStreamPrivateTagStack::tagStack_pop().
 { return data[tos--]; }
push()
template<typename T> T& QXmlStreamSimpleStack< T >::push () inline
Definition at line 659 of file qxmlstream_p.h.
Referenced by QXmlStreamReaderPrivate::parse(), QXmlStreamReaderPrivate::putChar(), QXmlStreamReaderPrivate::referenceEntity(), and QXmlStreamPrivateTagStack::tagStack_push().
 { reserve(1); return data[++tos]; }
rawPush()
template<typename T> T& QXmlStreamSimpleStack< T >::rawPush () inline
Definition at line 660 of file qxmlstream_p.h.
Referenced by QXmlStreamReaderPrivate::putReplacement(), QXmlStreamReaderPrivate::putReplacementInAttributeValue(), QXmlStreamReaderPrivate::putString(), and QXmlStreamReaderPrivate::putStringLiteral().
 { return data[++tos]; }
reserve()
template<typename T> void QXmlStreamSimpleStack< T >::reserve (int extraCapacity) inline
Definition at line 651 of file qxmlstream_p.h.
Referenced by QXmlStreamReaderPrivate::init(), QXmlStreamReaderPrivate::putReplacement(), QXmlStreamReaderPrivate::putReplacementInAttributeValue(), QXmlStreamReaderPrivate::putString(), and QXmlStreamReaderPrivate::putStringLiteral().
{
         if (tos + extraCapacity + 1 > cap) {
             cap = qMax(tos + extraCapacity + 1, cap << 1 );
             data = reinterpret_cast<T *>(qRealloc(data, cap * sizeof(T)));
             Q_CHECK_PTR(data);
         }
     }
resize()
template<typename T> void QXmlStreamSimpleStack< T >::resize (int s) inline
Definition at line 667 of file qxmlstream_p.h.
Referenced by QXmlStreamPrivateTagStack::tagStack_pop().
 { tos = s - 1; }
size()
template<typename T> int QXmlStreamSimpleStack< T >::size () const inline
Definition at line 666 of file qxmlstream_p.h.
Referenced by QXmlStreamReaderPrivate::filterCarriageReturn(), QXmlStreamReaderPrivate::getChar(), QXmlStreamReaderPrivate::parse(), QXmlStreamReaderPrivate::peekChar(), and QXmlStreamPrivateTagStack::tagStack_push().
 { return tos + 1; }
top() [1/2]
template<typename T> const T& QXmlStreamSimpleStack< T >::top () const inline
Definition at line 661 of file qxmlstream_p.h.
Referenced by QXmlStreamReaderPrivate::parse(), and QXmlStreamReaderPrivate::peekChar().
 { return data[tos]; }
top() [2/2]
template<typename T> T& QXmlStreamSimpleStack< T >::top () inline
Definition at line 662 of file qxmlstream_p.h.
 { return data[tos]; }
Properties
cap
template<typename T> int QXmlStreamSimpleStack< T >::cap private
Definition at line 646 of file qxmlstream_p.h.
data
template<typename T> T* QXmlStreamSimpleStack< T >::data private
Definition at line 645 of file qxmlstream_p.h.
tos
template<typename T> int QXmlStreamSimpleStack< T >::tos private
Definition at line 646 of file qxmlstream_p.h.
The documentation for this class was generated from the following file:
/src/corelib/xml/qxmlstream_p.h