Qt 4.8: QGLTextureCache Class Reference
QGLTextureCache Class Reference
#include <qgl_p.h>
Public Functions
QGLTexture * getTexture (QGLContext *ctx, qint64 key)
void insert (QGLContext *ctx, qint64 key, QGLTexture *texture, int cost)
int maxCost ()
QGLTextureCache ()
void remove (qint64 key)
bool remove (QGLContext *ctx, GLuint textureId)
void removeContextTextures (QGLContext *ctx)
void setMaxCost (int newMax)
int size ()
~QGLTextureCache ()
Static Public Functions
static void cleanupBeforePixmapDestruction (QPixmapData *pixmap)
static void cleanupTexturesForCacheKey (qint64 cacheKey)
static void cleanupTexturesForPixampData (QPixmapData *pixmap)
static QGLTextureCache * instance ()
Properties
QCache< QGLTextureCacheKey, QGLTexture > m_cache
QReadWriteLock m_lock
Detailed Description
Definition at line 656 of file qgl_p.h.
Constructors and Destructors
QGLTextureCache()
QGLTextureCache::QGLTextureCache ()
Definition at line 1907 of file qgl.cpp.
     : m_cache(64*1024) // cache ~64 MB worth of textures - this is not accurate though
 {
     QImagePixmapCleanupHooks::instance()->addPixmapDataModificationHook(cleanupTexturesForPixampData);
     QImagePixmapCleanupHooks::instance()->addPixmapDataDestructionHook(cleanupBeforePixmapDestruction);
     QImagePixmapCleanupHooks::instance()->addImageHook(cleanupTexturesForCacheKey);
 }
~QGLTextureCache()
QGLTextureCache::~QGLTextureCache ()
Definition at line 1915 of file qgl.cpp.
 {
     QImagePixmapCleanupHooks::instance()->removePixmapDataModificationHook(cleanupTexturesForPixampData);
     QImagePixmapCleanupHooks::instance()->removePixmapDataDestructionHook(cleanupBeforePixmapDestruction);
     QImagePixmapCleanupHooks::instance()->removeImageHook(cleanupTexturesForCacheKey);
 }
Functions
cleanupBeforePixmapDestruction()
void QGLTextureCache::cleanupBeforePixmapDestruction (QPixmapData * pixmap) static
Definition at line 1982 of file qgl.cpp.
 {
     // Remove any bound textures first:
     cleanupTexturesForPixampData(pmd);
 #if defined(Q_WS_X11)
     if (pmd->classId() == QPixmapData::X11Class) {
         Q_ASSERT(pmd->ref == 0); // Make sure reference counting isn't broken
         QGLContextPrivate::destroyGlSurfaceForPixmap(pmd);
     }
 #endif
 }
cleanupTexturesForCacheKey()
void QGLTextureCache::cleanupTexturesForCacheKey (qint64 cacheKey) static
Definition at line 1971 of file qgl.cpp.
 {
     qt_gl_texture_cache()->remove(cacheKey);
 }
cleanupTexturesForPixampData()
void QGLTextureCache::cleanupTexturesForPixampData (QPixmapData * pixmap) static
Definition at line 1977 of file qgl.cpp.
 {
     cleanupTexturesForCacheKey(pmd->cacheKey());
 }
getTexture()
QGLTexture * QGLTextureCache::getTexture (QGLContext * ctx, qint64 key) inline
Definition at line 697 of file qgl_p.h.
 {
     // Can't be a QReadLocker since QCache::object() modifies the cache (reprioritizes the object)
     QWriteLocker locker(&m_lock);
     const QGLTextureCacheKey cacheKey = {key, QGLContextPrivate::contextGroup(ctx)};
     return m_cache.object(cacheKey);
 }
insert()
void QGLTextureCache::insert (QGLContext * ctx, qint64 key, QGLTexture * texture, int cost)
Definition at line 1922 of file qgl.cpp.
Referenced by QGLContextPrivate::bindTextureFromNativePixmap().
 {
     QWriteLocker locker(&m_lock);
     const QGLTextureCacheKey cacheKey = {key, QGLContextPrivate::contextGroup(ctx)};
     m_cache.insert(cacheKey, texture, cost);
 }
instance()
QGLTextureCache * QGLTextureCache::instance () static
Definition at line 1995 of file qgl.cpp.
Referenced by QGLContextPrivate::bindTextureFromNativePixmap(), QGLTexturePool::hibernate(), QX11GLSharedContexts::QX11GLSharedContexts(), and QGLTexturePool::reclaimSpace().
 {
     return qt_gl_texture_cache();
 }
maxCost()
int QGLTextureCache::maxCost () inline
Definition at line 691 of file qgl_p.h.
 {
     QReadLocker locker(&m_lock);
     return m_cache.maxCost();
 }
remove() [1/2]
void QGLTextureCache::remove (qint64 key)
Definition at line 1929 of file qgl.cpp.
Referenced by QGLTexturePool::hibernate(), and QGLTexturePool::reclaimSpace().
 {
     QWriteLocker locker(&m_lock);
     QMutexLocker groupLocker(&qt_context_groups()->m_mutex);
     QList<QGLContextGroup *>::const_iterator it = qt_context_groups()->m_list.constBegin();
     while (it != qt_context_groups()->m_list.constEnd()) {
         const QGLTextureCacheKey cacheKey = {key, *it};
         m_cache.remove(cacheKey);
         ++it;
     }
 }
remove() [2/2]
bool QGLTextureCache::remove (QGLContext * ctx, GLuint textureId)
Definition at line 1941 of file qgl.cpp.
 {
     QWriteLocker locker(&m_lock);
     QList<QGLTextureCacheKey> keys = m_cache.keys();
     for (int i = 0; i < keys.size(); ++i) {
         QGLTexture *tex = m_cache.object(keys.at(i));
         if (tex->id == textureId && tex->context == ctx) {
             tex->options |= QGLContext::MemoryManagedBindOption; // forces a glDeleteTextures() call
             m_cache.remove(keys.at(i));
             return true;
         }
     }
     return false;
 }
removeContextTextures()
void QGLTextureCache::removeContextTextures (QGLContext * ctx)
Definition at line 1956 of file qgl.cpp.
 {
     QWriteLocker locker(&m_lock);
     QList<QGLTextureCacheKey> keys = m_cache.keys();
     for (int i = 0; i < keys.size(); ++i) {
         const QGLTextureCacheKey &key = keys.at(i);
         if (m_cache.object(key)->context == ctx)
             m_cache.remove(key);
     }
 }
setMaxCost()
void QGLTextureCache::setMaxCost (int newMax) inline
Definition at line 685 of file qgl_p.h.
 {
     QWriteLocker locker(&m_lock);
     m_cache.setMaxCost(newMax);
 }
size()
int QGLTextureCache::size () inline
Definition at line 680 of file qgl_p.h.
{
     QReadLocker locker(&m_lock);
     return m_cache.size();
 }
Properties
m_cache
QCache<QGLTextureCacheKey, QGLTexture> QGLTextureCache::m_cache private
Definition at line 676 of file qgl_p.h.
m_lock
QReadWriteLock QGLTextureCache::m_lock private
Definition at line 677 of file qgl_p.h.
The documentation for this class was generated from the following files:
/src/opengl/qgl_p.h
/src/opengl/qgl.cpp