Qt 4.8: QScriptValueProperty Class Reference
QScriptValueProperty Class Reference
#include <qscriptvalueproperty_p.h>
Public Functions
QScriptValue::PropertyFlags flags () const
Returns the flags of this QScriptValueProperty.
bool isValid () const
Returns true if this QScriptValueProperty is valid, otherwise returns false.
QString name () const
Returns the name of this QScriptValueProperty.
QScriptValueProperty & operator= (const QScriptValueProperty &other)
Assigns the other property to this QScriptValueProperty.
QScriptValueProperty ()
Constructs an invalid QScriptValueProperty.
QScriptValueProperty (const QString &name, const QScriptValue &value, QScriptValue::PropertyFlags flags)
Constructs a QScriptValueProperty with the given name, value and flags.
QScriptValueProperty (const QScriptValueProperty &other)
Constructs a QScriptValueProperty that is a copy of the other property.
QScriptValue value () const
Returns the value of this QScriptValueProperty.
~QScriptValueProperty ()
Destroys this QScriptValueProperty.
Properties
QScopedSharedPointer< QScriptValuePropertyPrivate > d_ptr
Detailed Description
Definition at line 66 of file qscriptvalueproperty_p.h.
Constructors and Destructors
QScriptValueProperty() [1/3]
QScriptValueProperty::QScriptValueProperty ()
Constructs an invalid QScriptValueProperty.
Definition at line 74 of file qscriptvalueproperty.cpp.
     : d_ptr(0)
 {
 }
QScriptValueProperty() [2/3]
QScriptValueProperty::QScriptValueProperty (const QString & name, const QScriptValue & value, QScriptValue::PropertyFlags flags)
Constructs a QScriptValueProperty with the given name, value and flags.
Definition at line 83 of file qscriptvalueproperty.cpp.
     : d_ptr(new QScriptValuePropertyPrivate)
 {
     d_ptr->name = name;
     d_ptr->value = value;
     d_ptr->flags = flags;
     d_ptr->ref.ref();
 }
QScriptValueProperty() [3/3]
QScriptValueProperty::QScriptValueProperty (const QScriptValueProperty & other)
Constructs a QScriptValueProperty that is a copy of the other property.
Definition at line 97 of file qscriptvalueproperty.cpp.
     : d_ptr(other.d_ptr.data())
 {
     if (d_ptr)
         d_ptr->ref.ref();
 }
~QScriptValueProperty()
QScriptValueProperty::~QScriptValueProperty ()
Destroys this QScriptValueProperty.
Definition at line 107 of file qscriptvalueproperty.cpp.
 {
 }
Functions
flags()
QScriptValue::PropertyFlags QScriptValueProperty::flags () const
Returns the flags of this QScriptValueProperty.
Definition at line 145 of file qscriptvalueproperty.cpp.
Referenced by QScriptObjectSnapshot::capture(), QScriptDebuggerCommandExecutor::execute(), and QScriptValueProperty().
 {
     Q_D(const QScriptValueProperty);
     if (!d)
         return 0;
     return d->flags;
 }
isValid()
bool QScriptValueProperty::isValid () const
Returns true if this QScriptValueProperty is valid, otherwise returns false.
Definition at line 157 of file qscriptvalueproperty.cpp.
 {
     Q_D(const QScriptValueProperty);
     return (d != 0);
 }
name()
QString QScriptValueProperty::name () const
Returns the name of this QScriptValueProperty.
Definition at line 123 of file qscriptvalueproperty.cpp.
Referenced by QScriptObjectSnapshot::capture(), QScriptDebuggerCommandExecutor::execute(), QScriptObjectSnapshot::findProperty(), and QScriptValueProperty().
 {
     Q_D(const QScriptValueProperty);
     if (!d)
         return QString();
     return d->name;
 }
operator=()
QScriptValueProperty & QScriptValueProperty::operator= (const QScriptValueProperty & other)
Assigns the other property to this QScriptValueProperty.
Definition at line 114 of file qscriptvalueproperty.cpp.
 {
     d_ptr.assign(other.d_ptr.data());
     return *this;
 }
value()
QScriptValue QScriptValueProperty::value () const
Returns the value of this QScriptValueProperty.
Definition at line 134 of file qscriptvalueproperty.cpp.
Referenced by QScriptObjectSnapshot::capture(), QScriptDebuggerCommandExecutor::execute(), and QScriptValueProperty().
 {
     Q_D(const QScriptValueProperty);
     if (!d)
         return QScriptValue();
     return d->value;
 }
Properties
d_ptr
QScopedSharedPointer<QScriptValuePropertyPrivate> QScriptValueProperty::d_ptr private
Definition at line 85 of file qscriptvalueproperty_p.h.
Referenced by operator=(), and QScriptValueProperty().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptvalueproperty_p.h
/src/scripttools/debugging/qscriptvalueproperty.cpp