Qt 4.8: QOpenGLCoordinateOffset Class Reference
QOpenGLCoordinateOffset Class Reference
Public Functions
QOpenGLCoordinateOffset (QOpenGLPaintEnginePrivate *d)
~QOpenGLCoordinateOffset ()
Static Public Functions
static void disableOffset (QOpenGLPaintEnginePrivate *d)
static void enableOffset (QOpenGLPaintEnginePrivate *d)
Properties
QOpenGLPaintEnginePrivate * d
Detailed Description
Definition at line 852 of file qpaintengine_opengl.cpp.
Constructors and Destructors
QOpenGLCoordinateOffset()
QOpenGLCoordinateOffset::QOpenGLCoordinateOffset (QOpenGLPaintEnginePrivate * d)
Definition at line 865 of file qpaintengine_opengl.cpp.
     : d(d_)
 {
     enableOffset(d);
 }
~QOpenGLCoordinateOffset()
QOpenGLCoordinateOffset::~QOpenGLCoordinateOffset ()
Definition at line 882 of file qpaintengine_opengl.cpp.
 {
     disableOffset(d);
 }
Functions
disableOffset()
void QOpenGLCoordinateOffset::disableOffset (QOpenGLPaintEnginePrivate * d) static
Definition at line 887 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEnginePrivate::drawFastRect(), and ~QOpenGLCoordinateOffset().
 {
     if (!d->has_antialiasing) {
         glMatrixMode(GL_MODELVIEW);
         glPopMatrix();
         d->mv_matrix[3][0] -= 0.5;
         d->mv_matrix[3][1] -= 0.5;
     }
 }
enableOffset()
void QOpenGLCoordinateOffset::enableOffset (QOpenGLPaintEnginePrivate * d) static
Definition at line 871 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEnginePrivate::drawFastRect(), and QOpenGLCoordinateOffset().
 {
     if (!d->has_antialiasing) {
         glMatrixMode(GL_MODELVIEW);
         glPushMatrix();
         d->mv_matrix[3][0] += 0.5;
         d->mv_matrix[3][1] += 0.5;
         d->updateGLMatrix();
     }
 }
Properties
d
QOpenGLPaintEnginePrivate* QOpenGLCoordinateOffset::d private
Definition at line 862 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLCoordinateOffset(), and ~QOpenGLCoordinateOffset().
The documentation for this class was generated from the following file:
/src/opengl/qpaintengine_opengl.cpp