Qt 4.8: QTextLine Class Reference
QTextLine Class Reference
The QTextLine class represents a line of text inside a QTextLayout.
#include <qtextlayout.h>
Public Types
enum CursorPosition { CursorBetweenCharacters, CursorOnCharacter }
enum Edge { Leading, Trailing }
Public Functions
qreal ascent () const
Returns the line's ascent.
qreal cursorToX (int *cursorPos, Edge edge=Leading) const
Converts the cursor position cursorPos to the corresponding x position inside the line, taking account of the edge.
qreal cursorToX (int cursorPos, Edge edge=Leading) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
qreal descent () const
Returns the line's descent.
void draw (QPainter *p, const QPointF &point, const QTextLayout::FormatRange *selection=0) const
Draws a line on the given painter at the specified position.
qreal height () const
Returns the line's height.
qreal horizontalAdvance () const
Returns the horizontal advance of the text.
bool isValid () const
Returns true if this text line is valid; otherwise returns false.
qreal leading () const
Returns the line's leading.
bool leadingIncluded () const
Returns true if positive leading is included into the line's height; otherwise returns false.
int lineNumber () const
Returns the position of the line in the text engine.
QRectF naturalTextRect () const
Returns the rectangle covered by the line.
qreal naturalTextWidth () const
Returns the width of the line that is occupied by text.
QPointF position () const
Returns the line's position relative to the text layout's position.
QTextLine ()
Creates an invalid line.
QRectF rect () const
Returns the line's bounding rectangle.
void setLeadingIncluded (bool included)
Includes positive leading into the line's height if included is true; otherwise does not include leading.
void setLineWidth (qreal width)
Lays out the line with the given width.
void setNumColumns (int columns)
Lays out the line.
void setNumColumns (int columns, qreal alignmentWidth)
Lays out the line.
void setPosition (const QPointF &pos)
Moves the line to position pos.
int textLength () const
Returns the length of the text in the line.
int textStart () const
Returns the start of the line from the beginning of the string passed to the QTextLayout.
qreal width () const
Returns the line's width as specified by the layout() function.
qreal x () const
Returns the line's x position.
int xToCursor (qreal x, CursorPosition=CursorBetweenCharacters) const
Converts the x-coordinate x, to the nearest matching cursor position, depending on the cursor position type, cpos.
qreal y () const
Returns the line's y position.
Private Functions
QList< QGlyphRun > glyphs (int from, int length) const
Returns the glyph indexes and positions for all glyphs in this QTextLine which reside in QScriptItems that overlap with the range defined by from and length.
void layout_helper (int numGlyphs)
QTextLine (int line, QTextEngine *e)
Properties
QTextEngine * eng
int i
Friends
class QTextFragment
class QTextLayout
Detailed Description
The QTextLine class represents a line of text inside a QTextLayout.
Note
This class or function is reentrant.
A text line is usually created by QTextLayout::createLine().
After being created, the line can be filled using the setLineWidth() or setNumColumns() functions. A line has a number of attributes including the rectangle it occupies, rect(), its coordinates, x() and y(), its textLength(), width() and naturalTextWidth(), and its ascent() and decent() relative to the text. The position of the cursor in terms of the line is available from cursorToX() and its inverse from xToCursor(). A line can be moved with setPosition().
Definition at line 197 of file qtextlayout.h.
Enumerations
CursorPosition
enum QTextLine::CursorPosition
CursorBetweenCharacters
CursorOnCharacter
Enumerator
CursorBetweenCharacters
CursorOnCharacter
Definition at line 223 of file qtextlayout.h.
{
         CursorBetweenCharacters,
         CursorOnCharacter
     };
Edge
enum QTextLine::Edge
Leading
Trailing
Enumerator
Leading
Trailing
Definition at line 219 of file qtextlayout.h.
               {
         Leading,
         Trailing
     };
Constructors and Destructors
QTextLine() [1/2]
QTextLine::QTextLine () inline
Creates an invalid line.
Definition at line 200 of file qtextlayout.h.
 : i(0), eng(0) {}
QTextLine() [2/2]
QTextLine::QTextLine (int line, QTextEngine * e) inline private
Warning
This function is not part of the public interface.
Constructs a new text line using the line at position line in the text engine e.
Definition at line 248 of file qtextlayout.h.
 : i(line), eng(e) {}
Functions
ascent()
qreal QTextLine::ascent () const
Returns the line's ascent.
See also
descent(), height()
Definition at line 1461 of file qtextlayout.cpp.
Referenced by QSvgText::draw(), getLineHeightParams(), QLineControl::updateDisplayText(), and QCommonStylePrivate::viewItemDrawText().
 {
     return eng->lines[i].ascent.toReal();
 }
cursorToX() [1/2]
qreal QTextLine::cursorToX (int * cursorPos, Edge edge = Leading) const
Converts the cursor position cursorPos to the corresponding x position inside the line, taking account of the edge.
If cursorPos is not a valid cursor position, the nearest valid cursor position will be used instead, and cpos will be modified to point to this valid cursor position.
See also
xToCursor()
Definition at line 2570 of file qtextlayout.cpp.
Referenced by QAccessibleTextWidget::characterRect(), QLineControl::cursorRect(), QTextLayout::drawCursor(), QTextControlPrivate::extendWordwiseSelection(), QTextControlPrivate::rectForPosition(), and QTextCursorPrivate::setX().
 {
     if (!eng->layoutData)
         eng->itemize();
     const QScriptLine &line = eng->lines[i];
     bool lastLine = i >= eng->lines.size() - 1;
     QFixed x = line.x;
     x += eng->alignLine(line) - eng->leadingSpaceWidth(line);
     if (!i && !eng->layoutData->items.size()) {
         *cursorPos = 0;
         return x.toReal();
     }
     int lineEnd = line.from + line.length + line.trailingSpaces;
     int pos = *cursorPos;
     int itm;
     const HB_CharAttributes *attributes = eng->attributes();
     if (!attributes) {
         *cursorPos = 0;
         return x.toReal();
     }
     while (pos < lineEnd && !attributes[pos].charStop)
         pos++;
     if (pos == lineEnd) {
         // end of line ensure we have the last item on the line
         itm = eng->findItem(pos-1);
     }
     else
         itm = eng->findItem(pos);
     eng->shapeLine(line);
     const QScriptItem *si = &eng->layoutData->items[itm];
     if (!si->num_glyphs)
         eng->shape(itm);
     pos -= si->position;
     QGlyphLayout glyphs = eng->shapedGlyphs(si);
     unsigned short *logClusters = eng->logClusters(si);
     Q_ASSERT(logClusters);
     int l = eng->length(itm);
     if (pos > l)
         pos = l;
     if (pos < 0)
         pos = 0;
     int glyph_pos = pos == l ? si->num_glyphs : logClusters[pos];
     if (edge == Trailing) {
         // trailing edge is leading edge of next cluster
         while (glyph_pos < si->num_glyphs && !glyphs.attributes[glyph_pos].clusterStart)
             glyph_pos++;
     }
     bool reverse = eng->layoutData->items[itm].analysis.bidiLevel % 2;
     // add the items left of the cursor
     int firstItem = eng->findItem(line.from);
     int lastItem = eng->findItem(lineEnd - 1);
     int nItems = (firstItem >= 0 && lastItem >= firstItem)? (lastItem-firstItem+1) : 0;
     QVarLengthArray<int> visualOrder(nItems);
     QVarLengthArray<uchar> levels(nItems);
     for (int i = 0; i < nItems; ++i)
         levels[i] = eng->layoutData->items[i+firstItem].analysis.bidiLevel;
     QTextEngine::bidiReorder(nItems, levels.data(), visualOrder.data());
     for (int i = 0; i < nItems; ++i) {
         int item = visualOrder[i]+firstItem;
         if (item == itm)
             break;
         QScriptItem &si = eng->layoutData->items[item];
         if (!si.num_glyphs)
             eng->shape(item);
         if (si.analysis.flags >= QScriptAnalysis::TabOrObject) {
             x += si.width;
             continue;
         }
         int start = qMax(line.from, si.position);
         int end = qMin(lineEnd, si.position + eng->length(item));
         logClusters = eng->logClusters(&si);
         int gs = logClusters[start-si.position];
         int ge = (end == si.position + eng->length(item)) ? si.num_glyphs-1 : logClusters[end-si.position-1];
         QGlyphLayout glyphs = eng->shapedGlyphs(&si);
         while (gs <= ge) {
             x += glyphs.effectiveAdvance(gs);
             ++gs;
         }
     }
     logClusters = eng->logClusters(si);
     glyphs = eng->shapedGlyphs(si);
     if (si->analysis.flags >= QScriptAnalysis::TabOrObject) {
         if (pos == (reverse ? 0 : l))
             x += si->width;
     } else {
         bool rtl = eng->isRightToLeft();
         bool visual = eng->visualCursorMovement();
         int end = qMin(lineEnd, si->position + l) - si->position;
         if (reverse) {
             int glyph_end = end == l ? si->num_glyphs : logClusters[end];
             int glyph_start = glyph_pos;
             if (visual && !rtl && !(lastLine && itm == (visualOrder[nItems - 1] + firstItem)))
                 glyph_start++;
             for (int i = glyph_end - 1; i >= glyph_start; i--)
                 x += glyphs.effectiveAdvance(i);
         } else {
             int start = qMax(line.from - si->position, 0);
             int glyph_start = logClusters[start];
             int glyph_end = glyph_pos;
             if (!visual || !rtl || (lastLine && itm == visualOrder[0] + firstItem))
                 glyph_end--;
             for (int i = glyph_start; i <= glyph_end; i++)
                 x += glyphs.effectiveAdvance(i);
         }
         x += eng->offsetInLigature(si, pos, end, glyph_pos);
     }
     if (eng->option.wrapMode() != QTextOption::NoWrap && x > line.x + line.width)
         x = line.x + line.width;
     if (eng->option.wrapMode() != QTextOption::NoWrap && x < 0)
         x = 0;
     *cursorPos = pos + si->position;
     return x.toReal();
 }
cursorToX() [2/2]
int QTextLine::cursorToX (int cursorPos, Edge edge = Leading) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 230 of file qtextlayout.h.
Referenced by cursorToX().
 { return cursorToX(&cursorPos, edge); }
descent()
qreal QTextLine::descent () const
Returns the line's descent.
See also
ascent(), height()
Definition at line 1471 of file qtextlayout.cpp.
 {
     return eng->lines[i].descent.toReal();
 }
draw()
void QTextLine::draw (QPainter * painter, const QPointF & position, const QTextLayout::FormatRange * selection = 0) const
Draws a line on the given painter at the specified position.
The selection is reserved for internal use.
Definition at line 2361 of file qtextlayout.cpp.
Referenced by QTextLayout::draw(), qt_format_text(), and QCommonStylePrivate::viewItemDrawText().
 {
     const QScriptLine &line = eng->lines[i];
     QPen pen = p->pen();
     bool noText = (selection && selection->format.property(SuppressText).toBool());
     if (!line.length) {
         if (selection
             && selection->start <= line.from
             && selection->start + selection->length > line.from) {
             const qreal lineHeight = line.height().toReal();
             QRectF r(pos.x() + line.x.toReal(), pos.y() + line.y.toReal(),
                      lineHeight / 2, QFontMetrics(eng->font()).width(QLatin1Char(' ')));
             setPenAndDrawBackground(p, QPen(), selection->format, r);
             p->setPen(pen);
         }
         return;
     }
     QTextLineItemIterator iterator(eng, i, pos, selection);
     QFixed lineBase = line.base();
     const QFixed y = QFixed::fromReal(pos.y()) + line.y + lineBase;
     bool suppressColors = (eng->option.flags() & QTextOption::SuppressColors);
     while (!iterator.atEnd()) {
         QScriptItem &si = iterator.next();
         if (selection && selection->start >= 0 && iterator.isOutsideSelection())
             continue;
         if (si.analysis.flags == QScriptAnalysis::LineOrParagraphSeparator
             && !(eng->option.flags() & QTextOption::ShowLineAndParagraphSeparators))
             continue;
         QFixed itemBaseLine = y;
         QFont f = eng->font(si);
         QTextCharFormat format;
         if (eng->hasFormats() || selection) {
             format = eng->format(&si);
             if (suppressColors) {
                 format.clearForeground();
                 format.clearBackground();
                 format.clearProperty(QTextFormat::TextUnderlineColor);
             }
             if (selection)
                 format.merge(selection->format);
             setPenAndDrawBackground(p, pen, format, QRectF(iterator.x.toReal(), (y - lineBase).toReal(),
                                                            iterator.itemWidth.toReal(), line.height().toReal()));
             QTextCharFormat::VerticalAlignment valign = format.verticalAlignment();
             if (valign == QTextCharFormat::AlignSuperScript || valign == QTextCharFormat::AlignSubScript) {
                 QFontEngine *fe = f.d->engineForScript(si.analysis.script);
                 QFixed height = fe->ascent() + fe->descent();
                 if (valign == QTextCharFormat::AlignSubScript)
                     itemBaseLine += height / 6;
                 else if (valign == QTextCharFormat::AlignSuperScript)
                     itemBaseLine -= height / 2;
             }
         }
         if (si.analysis.flags >= QScriptAnalysis::TabOrObject) {
             if (eng->hasFormats()) {
                 p->save();
                 if (si.analysis.flags == QScriptAnalysis::Object && eng->block.docHandle()) {
                     QFixed itemY = y - si.ascent;
                     if (format.verticalAlignment() == QTextCharFormat::AlignTop) {
                         itemY = y - lineBase;
                     }
                     QRectF itemRect(iterator.x.toReal(), itemY.toReal(), iterator.itemWidth.toReal(), si.height().toReal());
                     eng->docLayout()->drawInlineObject(p, itemRect,
                                                        QTextInlineObject(iterator.item, eng),
                                                        si.position + eng->block.position(),
                                                        format);
                     if (selection) {
                         QBrush bg = format.brushProperty(ObjectSelectionBrush);
                         if (bg.style() != Qt::NoBrush) {
                             QColor c = bg.color();
                             c.setAlpha(128);
                             p->fillRect(itemRect, c);
                         }
                     }
                 } else { // si.isTab
                     QFont f = eng->font(si);
                     QTextItemInt gf(si, &f, format);
                     gf.chars = 0;
                     gf.num_chars = 0;
                     gf.width = iterator.itemWidth;
                     p->drawTextItem(QPointF(iterator.x.toReal(), y.toReal()), gf);
                     if (eng->option.flags() & QTextOption::ShowTabsAndSpaces) {
                         QChar visualTab(0x2192);
                         int w = QFontMetrics(f).width(visualTab);
                         qreal x = iterator.itemWidth.toReal() - w; // Right-aligned
                         if (x < 0)
                              p->setClipRect(QRectF(iterator.x.toReal(), line.y.toReal(),
                                                    iterator.itemWidth.toReal(), line.height().toReal()),
                                             Qt::IntersectClip);
                         else
                              x /= 2; // Centered
                         p->drawText(QPointF(iterator.x.toReal() + x,
                                             y.toReal()), visualTab);
                     }
                 }
                 p->restore();
             }
             continue;
         }
         unsigned short *logClusters = eng->logClusters(&si);
         QGlyphLayout glyphs = eng->shapedGlyphs(&si);
         QTextItemInt gf(glyphs.mid(iterator.glyphsStart, iterator.glyphsEnd - iterator.glyphsStart),
                         &f, eng->layoutData->string.unicode() + iterator.itemStart,
                         iterator.itemEnd - iterator.itemStart, eng->fontEngine(si), format);
         gf.logClusters = logClusters + iterator.itemStart - si.position;
         gf.width = iterator.itemWidth;
         gf.justified = line.justified;
         gf.initWithScriptItem(si);
         Q_ASSERT(gf.fontEngine);
         if (eng->underlinePositions) {
             // can't have selections in this case
             drawMenuText(p, iterator.x, itemBaseLine, si, gf, eng, iterator.itemStart, iterator.glyphsStart);
         } else {
             QPointF pos(iterator.x.toReal(), itemBaseLine.toReal());
             if (format.penProperty(QTextFormat::TextOutline).style() != Qt::NoPen) {
                 QPainterPath path;
                 path.setFillRule(Qt::WindingFill);
                 if (gf.glyphs.numGlyphs)
                     gf.fontEngine->addOutlineToPath(pos.x(), pos.y(), gf.glyphs, &path, gf.flags);
                 if (gf.flags) {
                     const QFontEngine *fe = gf.fontEngine;
                     const qreal lw = fe->lineThickness().toReal();
                     if (gf.flags & QTextItem::Underline) {
                         qreal offs = fe->underlinePosition().toReal();
                         path.addRect(pos.x(), pos.y() + offs, gf.width.toReal(), lw);
                     }
                     if (gf.flags & QTextItem::Overline) {
                         qreal offs = fe->ascent().toReal() + 1;
                         path.addRect(pos.x(), pos.y() - offs, gf.width.toReal(), lw);
                     }
                     if (gf.flags & QTextItem::StrikeOut) {
                         qreal offs = fe->ascent().toReal() / 3;
                         path.addRect(pos.x(), pos.y() - offs, gf.width.toReal(), lw);
                     }
                 }
                 p->save();
                 p->setRenderHint(QPainter::Antialiasing);
                 //Currently QPen with a Qt::NoPen style still returns a default
                 //QBrush which != Qt::NoBrush so we need this specialcase to reset it
                 if (p->pen().style() == Qt::NoPen)
                     p->setBrush(Qt::NoBrush);
                 else
                     p->setBrush(p->pen().brush());
                 p->setPen(format.textOutline());
                 p->drawPath(path);
                 p->restore();
             } else {
                 if (noText)
                     gf.glyphs.numGlyphs = 0; // slightly less elegant than it should be
                 p->drawTextItem(pos, gf);
             }
         }
         if (si.analysis.flags == QScriptAnalysis::Space
             && (eng->option.flags() & QTextOption::ShowTabsAndSpaces)) {
             QBrush c = format.foreground();
             if (c.style() != Qt::NoBrush)
                 p->setPen(c.color());
             QChar visualSpace((ushort)0xb7);
             p->drawText(QPointF(iterator.x.toReal(), itemBaseLine.toReal()), visualSpace);
             p->setPen(pen);
         }
     }
     if (eng->hasFormats())
         p->setPen(pen);
 }
glyphs()
QList< QGlyphRun > QTextLine::glyphs (int from, int length) const private
Returns the glyph indexes and positions for all glyphs in this QTextLine which reside in QScriptItems that overlap with the range defined by from and length.
Warning
This function is not part of the public interface.
The arguments specify characters, relative to the text in the layout. Note that it is not possible to use this function to retrieve a subset of the glyphs in a QScriptItem.
Since
4.8
See also
QTextLayout::glyphRuns()
Definition at line 2197 of file qtextlayout.cpp.
Referenced by QTextLayout::glyphRuns(), and QTextFragment::glyphRuns().
 {
     const QScriptLine &line = eng->lines[i];
     if (line.length == 0)
         return QList<QGlyphRun>();
     QHash<QFontEngine *, GlyphInfo> glyphLayoutHash;
     QTextLineItemIterator iterator(eng, i);
     qreal y = line.y.toReal() + line.base().toReal();
     while (!iterator.atEnd()) {
         QScriptItem &si = iterator.next();
         if (si.analysis.flags >= QScriptAnalysis::TabOrObject)
             continue;
         QPointF pos(iterator.x.toReal(), y);
         if (from >= 0 && length >= 0 &&
             (from >= si.position + eng->length(&si) || from + length <= si.position))
             continue;
         QFont font = eng->font(si);
         QTextItem::RenderFlags flags;
         if (font.overline())
             flags |= QTextItem::Overline;
         if (font.underline())
             flags |= QTextItem::Underline;
         if (font.strikeOut())
             flags |= QTextItem::StrikeOut;
         if (si.analysis.bidiLevel % 2)
             flags |= QTextItem::RightToLeft;
         QGlyphLayout glyphLayout = eng->shapedGlyphs(&si).mid(iterator.glyphsStart,
                                                               iterator.glyphsEnd - iterator.glyphsStart);
         if (glyphLayout.numGlyphs > 0) {
             QFontEngine *mainFontEngine = font.d->engineForScript(si.analysis.script);
             if (mainFontEngine->type() == QFontEngine::Multi) {
                 QFontEngineMulti *multiFontEngine = static_cast<QFontEngineMulti *>(mainFontEngine);
                 int start = 0;
                 int end;
                 int which = glyphLayout.glyphs[0] >> 24;
                 for (end = 0; end < glyphLayout.numGlyphs; ++end) {
                     const int e = glyphLayout.glyphs[end] >> 24;
                     if (e == which)
                         continue;
                     QGlyphLayout subLayout = glyphLayout.mid(start, end - start);
                     glyphLayoutHash.insertMulti(multiFontEngine->engine(which),
                                                 GlyphInfo(subLayout, pos, flags));
                     for (int i = 0; i < subLayout.numGlyphs; i++)
                         pos += QPointF(subLayout.advances_x[i].toReal(),
                                        subLayout.advances_y[i].toReal());
                     start = end;
                     which = e;
                 }
                 QGlyphLayout subLayout = glyphLayout.mid(start, end - start);
                 glyphLayoutHash.insertMulti(multiFontEngine->engine(which),
                                             GlyphInfo(subLayout, pos, flags));
             } else {
                 glyphLayoutHash.insertMulti(mainFontEngine,
                                             GlyphInfo(glyphLayout, pos, flags));
             }
         }
     }
     QHash<QPair<QFontEngine *, int>, QGlyphRun> glyphsHash;
     QList<QFontEngine *> keys = glyphLayoutHash.uniqueKeys();
     for (int i=0; i<keys.size(); ++i) {
         QFontEngine *fontEngine = keys.at(i);
         // Make a font for this particular engine
         QRawFont font;
         QRawFontPrivate *fontD = QRawFontPrivate::get(font);
         fontD->fontEngine = fontEngine;
         fontD->fontEngine->ref.ref();
 #if defined(Q_WS_WIN)
         if (fontEngine->supportsSubPixelPositions())
             fontD->hintingPreference = QFont::PreferVerticalHinting;
         else
             fontD->hintingPreference = QFont::PreferFullHinting;
 #elif defined(Q_WS_MAC)
         fontD->hintingPreference = QFont::PreferNoHinting;
 #elif !defined(QT_NO_FREETYPE)
         if (fontEngine->type() == QFontEngine::Freetype) {
             QFontEngineFT *freeTypeEngine = static_cast<QFontEngineFT *>(fontEngine);
             switch (freeTypeEngine->defaultHintStyle()) {
             case QFontEngineFT::HintNone:
                 fontD->hintingPreference = QFont::PreferNoHinting;
                 break;
             case QFontEngineFT::HintLight:
                 fontD->hintingPreference = QFont::PreferVerticalHinting;
                 break;
             case QFontEngineFT::HintMedium:
             case QFontEngineFT::HintFull:
                 fontD->hintingPreference = QFont::PreferFullHinting;
                 break;
             };
         }
 #endif
         QList<GlyphInfo> glyphLayouts = glyphLayoutHash.values(fontEngine);
         for (int j=0; j<glyphLayouts.size(); ++j) {
             const QPointF &pos = glyphLayouts.at(j).itemPosition;
             const QGlyphLayout &glyphLayout = glyphLayouts.at(j).glyphLayout;
             const QTextItem::RenderFlags &flags = glyphLayouts.at(j).flags;
             QVarLengthArray<glyph_t> glyphsArray;
             QVarLengthArray<QFixedPoint> positionsArray;
             fontEngine->getGlyphPositions(glyphLayout, QTransform(), flags, glyphsArray,
                                           positionsArray);
             Q_ASSERT(glyphsArray.size() == positionsArray.size());
             QVector<quint32> glyphs;
             QVector<QPointF> positions;
             for (int i=0; i<glyphsArray.size(); ++i) {
                 glyphs.append(glyphsArray.at(i) & 0xffffff);
                 positions.append(positionsArray.at(i).toPointF() + pos);
             }
             QGlyphRun glyphIndexes;
             glyphIndexes.setGlyphIndexes(glyphs);
             glyphIndexes.setPositions(positions);
             glyphIndexes.setOverline(flags.testFlag(QTextItem::Overline));
             glyphIndexes.setUnderline(flags.testFlag(QTextItem::Underline));
             glyphIndexes.setStrikeOut(flags.testFlag(QTextItem::StrikeOut));
             glyphIndexes.setRawFont(font);
             QPair<QFontEngine *, int> key(fontEngine, int(flags));
             if (!glyphsHash.contains(key)) {
                 glyphsHash.insert(key, glyphIndexes);
             } else {
                 QGlyphRun &glyphRun = glyphsHash[key];
                 QVector<quint32> indexes = glyphRun.glyphIndexes();
                 QVector<QPointF> positions = glyphRun.positions();
                 indexes += glyphIndexes.glyphIndexes();
                 positions += glyphIndexes.positions();
                 glyphRun.setGlyphIndexes(indexes);
                 glyphRun.setPositions(positions);
             }
         }
     }
     return glyphsHash.values();
 }
height()
qreal QTextLine::height () const
Returns the line's height.
This is equal to ascent() + descent() + 1 if leading is not included. If leading is included, this equals to ascent() + descent() + leading() + 1.
See also
ascent(), descent(), leading(), setLeadingIncluded()
Definition at line 1483 of file qtextlayout.cpp.
Referenced by QAccessibleTextWidget::characterRect(), QLineControl::cursorRect(), QCommandLinkButtonPrivate::descriptionHeight(), QItemDelegatePrivate::doTextLayout(), QSvgText::draw(), getLineHeightParams(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutFlow(), QStaticTextPrivate::paintText(), qt_format_text(), QTextControlPrivate::rectForPosition(), QDeclarativeTextPrivate::setupTextLayout(), setupTextLayout(), QCommonStylePrivate::viewItemDrawText(), QCommonStylePrivate::viewItemSize(), and viewItemTextLayout().
 {
     return eng->lines[i].height().toReal();
 }
horizontalAdvance()
qreal QTextLine::horizontalAdvance () const
Returns the horizontal advance of the text.
Since
4.7 The advance of the text is the distance from its position to the next position at which text would naturally be drawn.
By adding the advance to the position of the text line and using this as the position of a second text line, you will be able to position the two lines side-by-side without gaps in-between.
Definition at line 1567 of file qtextlayout.cpp.
Referenced by qt_format_text().
 {
     return eng->lines[i].textAdvance.toReal();
 }
isValid()
bool QTextLine::isValid () const inline
Returns true if this text line is valid; otherwise returns false.
Definition at line 201 of file qtextlayout.h.
Referenced by QAccessibleTextWidget::characterRect(), QTextCursor::columnNumber(), QTextControlPrivate::cursorMoveKeyEvent(), QCommandLinkButtonPrivate::descriptionHeight(), QItemDelegatePrivate::doTextLayout(), QSvgText::draw(), QTextDocumentLayoutPrivate::drawListItem(), QPlainTextEditPrivate::ensureVisible(), QTextControlPrivate::extendWordwiseSelection(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutBlock(), QTextControlPrivate::mouseDoubleClickEvent(), QTextCursorPrivate::movePosition(), QStaticTextPrivate::paintText(), QTextDocumentLayout::positionInlineObject(), qt_format_text(), QTextControlPrivate::rectForPosition(), QDeclarativeTextPrivate::setupTextLayout(), setupTextLayout(), QTextCursorPrivate::setX(), QCommonStylePrivate::viewItemSize(), and viewItemTextLayout().
 { return eng; }
layout_helper()
void QTextLine::layout_helper (int numGlyphs) private
Definition at line 1782 of file qtextlayout.cpp.
 {
     QScriptLine &line = eng->lines[i];
     line.length = 0;
     line.trailingSpaces = 0;
     line.textWidth = 0;
     line.hasTrailingSpaces = false;
     if (!eng->layoutData->items.size() || line.from >= eng->layoutData->string.length()) {
         line.setDefaultHeight(eng);
         return;
     }
     Q_ASSERT(line.from < eng->layoutData->string.length());
     LineBreakHelper lbh;
     lbh.maxGlyphs = maxGlyphs;
     QTextOption::WrapMode wrapMode = eng->option.wrapMode();
     bool breakany = (wrapMode == QTextOption::WrapAnywhere);
     lbh.manualWrap = (wrapMode == QTextOption::ManualWrap || wrapMode == QTextOption::NoWrap);
     int item = -1;
     int newItem = eng->findItem(line.from);
     LB_DEBUG("from: %d: item=%d, total %d, width available %f", line.from, newItem, eng->layoutData->items.size(), line.width.toReal());
     Qt::Alignment alignment = eng->option.alignment();
     const HB_CharAttributes *attributes = eng->attributes();
     if (!attributes)
         return;
     lbh.currentPosition = line.from;
     int end = 0;
     lbh.logClusters = eng->layoutData->logClustersPtr;
     lbh.resetPreviousGlyph();
     while (newItem < eng->layoutData->items.size()) {
         lbh.resetRightBearing();
         lbh.softHyphenWidth = 0;
         if (newItem != item) {
             item = newItem;
             const QScriptItem &current = eng->layoutData->items[item];
             if (!current.num_glyphs) {
                 eng->shape(item);
                 attributes = eng->attributes();
                 if (!attributes)
                     return;
                 lbh.logClusters = eng->layoutData->logClustersPtr;
             }
             lbh.currentPosition = qMax(line.from, current.position);
             end = current.position + eng->length(item);
             lbh.glyphs = eng->shapedGlyphs(&current);
             QFontEngine *fontEngine = eng->fontEngine(current);
             if (lbh.fontEngine != fontEngine) {
                 lbh.fontEngine = fontEngine;
                 lbh.minimumRightBearing = qMin(QFixed(),
                                                QFixed::fromReal(fontEngine->minRightBearing()));
             }
         }
         const QScriptItem &current = eng->layoutData->items[item];
         lbh.tmpData.leading = qMax(lbh.tmpData.leading + lbh.tmpData.ascent,
                                    current.leading + current.ascent) - qMax(lbh.tmpData.ascent,
                                                                             current.ascent);
         lbh.tmpData.ascent = qMax(lbh.tmpData.ascent, current.ascent);
         lbh.tmpData.descent = qMax(lbh.tmpData.descent, current.descent);
         if (current.analysis.flags == QScriptAnalysis::Tab && (alignment & (Qt::AlignLeft | Qt::AlignRight | Qt::AlignCenter | Qt::AlignJustify))) {
             lbh.whiteSpaceOrObject = true;
             if (lbh.checkFullOtherwiseExtend(line))
                 goto found;
             QFixed x = line.x + line.textWidth + lbh.tmpData.textWidth + lbh.spaceData.textWidth;
             QFixed tabWidth = eng->calculateTabWidth(item, x);
             lbh.spaceData.textWidth += tabWidth;
             lbh.spaceData.length++;
             newItem = item + 1;
             QFixed averageCharWidth = eng->fontEngine(current)->averageCharWidth();
             lbh.glyphCount += qRound(tabWidth / averageCharWidth);
             if (lbh.checkFullOtherwiseExtend(line))
                 goto found;
         } else if (current.analysis.flags == QScriptAnalysis::LineOrParagraphSeparator) {
             lbh.whiteSpaceOrObject = true;
             // if the line consists only of the line separator make sure
             // we have a sane height
             if (!line.length && !lbh.tmpData.length)
                 line.setDefaultHeight(eng);
             if (eng->option.flags() & QTextOption::ShowLineAndParagraphSeparators) {
                 addNextCluster(lbh.currentPosition, end, lbh.tmpData, lbh.glyphCount,
                                current, lbh.logClusters, lbh.glyphs);
             } else {
                 lbh.tmpData.length++;
                 lbh.adjustPreviousRightBearing();
             }
             line += lbh.tmpData;
             goto found;
         } else if (current.analysis.flags == QScriptAnalysis::Object) {
             lbh.whiteSpaceOrObject = true;
             lbh.tmpData.length++;
             QTextFormat format = eng->formats()->format(eng->formatIndex(&eng->layoutData->items[item]));
             if (eng->block.docHandle())
                 eng->docLayout()->positionInlineObject(QTextInlineObject(item, eng), eng->block.position() + current.position, format);
             lbh.tmpData.textWidth += current.width;
             newItem = item + 1;
             ++lbh.glyphCount;
             if (lbh.checkFullOtherwiseExtend(line))
                 goto found;
         } else if (attributes[lbh.currentPosition].whiteSpace) {
             lbh.whiteSpaceOrObject = true;
             while (lbh.currentPosition < end && attributes[lbh.currentPosition].whiteSpace)
                 addNextCluster(lbh.currentPosition, end, lbh.spaceData, lbh.glyphCount,
                                current, lbh.logClusters, lbh.glyphs);
             if (!lbh.manualWrap && lbh.spaceData.textWidth > line.width) {
                 lbh.spaceData.textWidth = line.width; // ignore spaces that fall out of the line.
                 goto found;
             }
         } else {
             lbh.whiteSpaceOrObject = false;
             bool sb_or_ws = false;
             lbh.saveCurrentGlyph();
             do {
                 addNextCluster(lbh.currentPosition, end, lbh.tmpData, lbh.glyphCount,
                                current, lbh.logClusters, lbh.glyphs);
                 if (attributes[lbh.currentPosition].whiteSpace || attributes[lbh.currentPosition-1].lineBreakType != HB_NoBreak) {
                     sb_or_ws = true;
                     break;
                 } else if (breakany && attributes[lbh.currentPosition].charStop) {
                     break;
                 }
             } while (lbh.currentPosition < end);
             lbh.minw = qMax(lbh.tmpData.textWidth, lbh.minw);
             if (lbh.currentPosition && attributes[lbh.currentPosition - 1].lineBreakType == HB_SoftHyphen) {
                 // if we are splitting up a word because of
                 // a soft hyphen then we ...
                 //
                 //  a) have to take the width of the soft hyphen into
                 //     account to see if the first syllable(s) /and/
                 //     the soft hyphen fit into the line
                 //
                 //  b) if we are so short of available width that the
                 //     soft hyphen is the first breakable position, then
                 //     we don't want to show it. However we initially
                 //     have to take the width for it into account so that
                 //     the text document layout sees the overflow and
                 //     switch to break-anywhere mode, in which we
                 //     want the soft-hyphen to slip into the next line
                 //     and thus become invisible again.
                 //
                 if (line.length)
                     lbh.softHyphenWidth = lbh.glyphs.advances_x[lbh.logClusters[lbh.currentPosition - 1]];
                 else if (breakany)
                     lbh.tmpData.textWidth += lbh.glyphs.advances_x[lbh.logClusters[lbh.currentPosition - 1]];
             }
             // The actual width of the text needs to take the right bearing into account. The
             // right bearing is left-ward, which means that if the rightmost pixel is to the right
             // of the advance of the glyph, the bearing will be negative. We flip the sign
             // for the code to be more readable. Logic borrowed from qfontmetrics.cpp.
             // We ignore the right bearing if the minimum negative bearing is too little to
             // expand the text beyond the edge.
             if (sb_or_ws|breakany) {
                 QFixed rightBearing = lbh.rightBearing; // store previous right bearing
 #if !defined(Q_WS_MAC)
                 if (lbh.calculateNewWidth(line) - lbh.minimumRightBearing > line.width)
 #endif
                     lbh.adjustRightBearing();
                 if (lbh.checkFullOtherwiseExtend(line)) {
                     // we are too wide, fix right bearing
                     if (rightBearing <= 0)
                         lbh.rightBearing = rightBearing; // take from cache
                     else
                         lbh.adjustPreviousRightBearing();
                     if (!breakany) {
                         line.textWidth += lbh.softHyphenWidth;
                     }
                     goto found;
                 }
             }
             lbh.saveCurrentGlyph();
         }
         if (lbh.currentPosition == end)
             newItem = item + 1;
     }
     LB_DEBUG("reached end of line");
     lbh.checkFullOtherwiseExtend(line);
 found:
     if (lbh.rightBearing > 0 && !lbh.whiteSpaceOrObject) // If right bearing has not yet been adjusted
         lbh.adjustRightBearing();
     line.textAdvance = line.textWidth;
     line.textWidth -= qMin(QFixed(), lbh.rightBearing);
     if (line.length == 0) {
         LB_DEBUG("no break available in line, adding temp: length %d, width %f, space: length %d, width %f",
                lbh.tmpData.length, lbh.tmpData.textWidth.toReal(),
                lbh.spaceData.length, lbh.spaceData.textWidth.toReal());
         line += lbh.tmpData;
     }
     LB_DEBUG("line length = %d, ascent=%f, descent=%f, textWidth=%f (spacew=%f)", line.length, line.ascent.toReal(),
            line.descent.toReal(), line.textWidth.toReal(), lbh.spaceData.width.toReal());
     LB_DEBUG("        : '%s'", eng->layoutData->string.mid(line.from, line.length).toUtf8().data());
     if (lbh.manualWrap) {
         eng->minWidth = qMax(eng->minWidth, line.textWidth);
         eng->maxWidth = qMax(eng->maxWidth, line.textWidth);
     } else {
         eng->minWidth = qMax(eng->minWidth, lbh.minw);
         eng->maxWidth += line.textWidth;
     }
     if (line.textWidth > 0 && item < eng->layoutData->items.size())
         eng->maxWidth += lbh.spaceData.textWidth;
     if (eng->option.flags() & QTextOption::IncludeTrailingSpaces)
         line.textWidth += lbh.spaceData.textWidth;
     if (lbh.spaceData.length) {
         line.trailingSpaces = lbh.spaceData.length;
         line.hasTrailingSpaces = true;
     }
     line.justified = false;
     line.gridfitted = false;
     if (eng->option.wrapMode() == QTextOption::WrapAtWordBoundaryOrAnywhere) {
         if ((lbh.maxGlyphs != INT_MAX && lbh.glyphCount > lbh.maxGlyphs)
             || (lbh.maxGlyphs == INT_MAX && line.textWidth > line.width)) {
             eng->option.setWrapMode(QTextOption::WrapAnywhere);
             line.length = 0;
             line.textWidth = 0;
             layout_helper(lbh.maxGlyphs);
             eng->option.setWrapMode(QTextOption::WrapAtWordBoundaryOrAnywhere);
         }
     }
 }
leading()
qreal QTextLine::leading () const
Returns the line's leading.
Since
4.6
See also
ascent(), descent(), height()
Definition at line 1498 of file qtextlayout.cpp.
Referenced by QAccessibleTextWidget::characterRect(), and getLineHeightParams().
 {
     return eng->lines[i].leading.toReal();
 }
leadingIncluded()
bool QTextLine::leadingIncluded () const
Returns true if positive leading is included into the line's height; otherwise returns false.
Since
4.6
By default, leading is not included.
See also
setLeadingIncluded()
Definition at line 1539 of file qtextlayout.cpp.
Referenced by QAccessibleTextWidget::characterRect().
 {
     return eng->lines[i].leadingIncluded;
 }
lineNumber()
int QTextLine::lineNumber () const inline
Returns the position of the line in the text engine.
Definition at line 243 of file qtextlayout.h.
Referenced by QTextControlPrivate::cursorMoveKeyEvent(), QPlainTextEditPrivate::ensureVisible(), QTextCursorPrivate::movePosition(), qt_format_text(), and QTextControl::selectionRect().
 { return i; }
naturalTextRect()
QRectF QTextLine::naturalTextRect () const
Returns the rectangle covered by the line.
Definition at line 1413 of file qtextlayout.cpp.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), QTextLayout::draw(), QTextDocumentLayoutPrivate::drawListItem(), QPlainTextEditPrivate::ensureVisible(), QPlainTextEditControl::hitTest(), QTextDocumentLayoutPrivate::hitTest(), QPlainTextEditPrivate::pageUpDown(), QDeclarativeTextPrivate::setupTextLayout(), and QPlainTextEditPrivate::verticalOffset().
 {
     const QScriptLine& sl = eng->lines[i];
     QFixed x = sl.x + eng->alignLine(sl);
     QFixed width = sl.textWidth;
     if (sl.justified)
         width = sl.width;
     return QRectF(x.toReal(), sl.y.toReal(), width.toReal(), sl.height().toReal());
 }
naturalTextWidth()
qreal QTextLine::naturalTextWidth () const
Returns the width of the line that is occupied by text.
This is always <= to width(), and is the minimum width that could be used by layout() without changing the line break position.
Definition at line 1549 of file qtextlayout.cpp.
Referenced by QPlainTextDocumentLayout::blockBoundingRect(), QPlainTextDocumentLayout::blockWidth(), QItemDelegatePrivate::doTextLayout(), QSvgText::draw(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::positionFloat(), qt_format_text(), setupTextLayout(), QCommonStylePrivate::viewItemDrawText(), QCommonStylePrivate::viewItemSize(), and viewItemTextLayout().
 {
     return eng->lines[i].textWidth.toReal();
 }
position()
QPointF QTextLine::position () const
Returns the line's position relative to the text layout's position.
Definition at line 2042 of file qtextlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutBlock(), and QDeclarativeTextPrivate::setupTextLayout().
 {
     return QPointF(eng->lines[i].x.toReal(), eng->lines[i].y.toReal());
 }
rect()
QRectF QTextLine::rect () const
Returns the line's bounding rectangle.
See also
x(), y(), textLength(), width()
Definition at line 1404 of file qtextlayout.cpp.
Referenced by QTextLayout::draw(), and QTextObjectInterface::~QTextObjectInterface().
 {
     const QScriptLine& sl = eng->lines[i];
     return QRectF(sl.x.toReal(), sl.y.toReal(), sl.width.toReal(), sl.height().toReal());
 }
setLeadingIncluded()
void QTextLine::setLeadingIncluded (bool included)
Includes positive leading into the line's height if included is true; otherwise does not include leading.
Since
4.6
By default, leading is not included.
Note that negative leading is ignored, it must be handled in the code using the text lines by letting the lines overlap.
See also
leadingIncluded()
Definition at line 1520 of file qtextlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawListItem(), QPlainTextDocumentLayout::layoutBlock(), and QTextDocumentLayoutPrivate::layoutBlock().
 {
     eng->lines[i].leadingIncluded= included;
 }
setLineWidth()
void QTextLine::setLineWidth (qreal width)
Lays out the line with the given width.
The line is filled from its starting position with as many characters as will fit into the line. In case the text cannot be split at the end of the line, it will be filled with additional characters to the next whitespace or end of the text.
Definition at line 1579 of file qtextlayout.cpp.
Referenced by QCommandLinkButtonPrivate::descriptionHeight(), QItemDelegatePrivate::doTextLayout(), QSvgText::draw(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutBlock(), QStaticTextPrivate::paintText(), qt_format_text(), QDeclarativeTextPrivate::setupTextLayout(), QCommonStylePrivate::viewItemSize(), and viewItemTextLayout().
 {
     QScriptLine &line = eng->lines[i];
     if (!eng->layoutData) {
         qWarning("QTextLine: Can't set a line width while not layouting.");
         return;
     }
     if (width > QFIXED_MAX)
         width = QFIXED_MAX;
     line.width = QFixed::fromReal(width);
     if (line.length
         && line.textWidth <= line.width
         && line.from + line.length == eng->layoutData->string.length())
         // no need to do anything if the line is already layouted and the last one. This optimization helps
         // when using things in a single line layout.
         return;
     line.length = 0;
     line.textWidth = 0;
     layout_helper(INT_MAX);
 }
setNumColumns() [1/2]
void QTextLine::setNumColumns (int numColumns)
Lays out the line.
The line is filled from its starting position with as many characters as are specified by numColumns. In case the text cannot be split until numColumns characters, the line will be filled with as many characters to the next whitespace or end of the text.
Definition at line 1610 of file qtextlayout.cpp.
Referenced by QTextLayout::createLine(), QTextLayout::endLayout(), and QTextDocumentLayoutPrivate::layoutBlock().
 {
     QScriptLine &line = eng->lines[i];
     line.width = QFIXED_MAX;
     line.length = 0;
     line.textWidth = 0;
     layout_helper(numColumns);
 }
setNumColumns() [2/2]
void QTextLine::setNumColumns (int numColumns, qreal alignmentWidth)
Lays out the line.
The line is filled from its starting position with as many characters as are specified by numColumns. In case the text cannot be split until numColumns characters, the line will be filled with as many characters to the next whitespace or end of the text. The provided alignmentWidth is used as reference width for alignment.
Definition at line 1627 of file qtextlayout.cpp.
 {
     QScriptLine &line = eng->lines[i];
     line.width = QFixed::fromReal(alignmentWidth);
     line.length = 0;
     line.textWidth = 0;
     layout_helper(numColumns);
 }
setPosition()
void QTextLine::setPosition (const QPointF & pos)
Moves the line to position pos.
Definition at line 2033 of file qtextlayout.cpp.
Referenced by QCommandLinkButtonPrivate::descriptionHeight(), QItemDelegatePrivate::doTextLayout(), QSvgText::draw(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutFlow(), QStaticTextPrivate::paintText(), qt_format_text(), QDeclarativeTextPrivate::setupTextLayout(), setupTextLayout(), QCommonStylePrivate::viewItemSize(), and viewItemTextLayout().
 {
     eng->lines[i].x = QFixed::fromReal(pos.x());
     eng->lines[i].y = QFixed::fromReal(pos.y());
 }
textLength()
int QTextLine::textLength () const
Returns the length of the text in the line.
See also
naturalTextWidth()
Definition at line 2068 of file qtextlayout.cpp.
Referenced by QAccessibleTextWidget::characterRect(), QTextDocumentLayoutPrivate::drawBlock(), QPlainTextEditControl::hitTest(), QTextDocumentLayoutPrivate::hitTest(), QTextControlPrivate::mouseDoubleClickEvent(), QTextCursorPrivate::movePosition(), QPlainTextEdit::paintEvent(), QTextControlPrivate::rectForPosition(), QDeclarativeTextPrivate::setupTextLayout(), and QCommonStylePrivate::viewItemDrawText().
 {
     if (eng->option.flags() & QTextOption::ShowLineAndParagraphSeparators
         && eng->block.isValid() && i == eng->lines.count()-1) {
         return eng->lines[i].length - 1;
     }
     return eng->lines[i].length + eng->lines[i].trailingSpaces;
 }
textStart()
int QTextLine::textStart () const
Returns the start of the line from the beginning of the string passed to the QTextLayout.
Definition at line 2058 of file qtextlayout.cpp.
Referenced by QAccessibleTextWidget::characterRect(), QTextCursor::columnNumber(), QTextDocumentLayoutPrivate::drawBlock(), QTextControlPrivate::extendWordwiseSelection(), QPlainTextEditControl::hitTest(), QTextDocumentLayoutPrivate::hitTest(), QTextCursorPrivate::movePosition(), QPlainTextEdit::paintEvent(), QTextControlPrivate::rectForPosition(), QDeclarativeTextPrivate::setupTextLayout(), and QCommonStylePrivate::viewItemDrawText().
 {
     return eng->lines[i].from;
 }
width()
qreal QTextLine::width () const
Returns the line's width as specified by the layout() function.
See also
naturalTextWidth(), x(), y(), textLength(), rect()
Definition at line 1450 of file qtextlayout.cpp.
Referenced by QCommonStylePrivate::viewItemDrawText().
 {
     return eng->lines[i].width.toReal();
 }
x()
qreal QTextLine::x () const
Returns the line's x position.
See also
rect(), y(), textLength(), width()
Definition at line 1430 of file qtextlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutBlock(), and QCommonStylePrivate::viewItemDrawText().
 {
     return eng->lines[i].x.toReal();
 }
xToCursor()
int QTextLine::xToCursor (qreal x, CursorPosition cpos = CursorBetweenCharacters) const
Converts the x-coordinate x, to the nearest matching cursor position, depending on the cursor position type, cpos.
See also
cursorToX()
Definition at line 2718 of file qtextlayout.cpp.
Referenced by QPlainTextEditControl::hitTest(), QTextDocumentLayoutPrivate::hitTest(), QTextCursorPrivate::movePosition(), and QLineControl::xToPos().
 {
     QFixed x = QFixed::fromReal(_x);
     const QScriptLine &line = eng->lines[i];
     bool lastLine = i >= eng->lines.size() - 1;
     int lineNum = i;
     if (!eng->layoutData)
         eng->itemize();
     int line_length = textLength();
     if (!line_length)
         return line.from;
     int firstItem = eng->findItem(line.from);
     int lastItem = eng->findItem(line.from + line_length - 1);
     int nItems = (firstItem >= 0 && lastItem >= firstItem)? (lastItem-firstItem+1) : 0;
     if (!nItems)
         return 0;
     x -= line.x;
     x -= eng->alignLine(line);
 //     qDebug("xToCursor: x=%f, cpos=%d", x.toReal(), cpos);
     QVarLengthArray<int> visualOrder(nItems);
     QVarLengthArray<unsigned char> levels(nItems);
     for (int i = 0; i < nItems; ++i)
         levels[i] = eng->layoutData->items[i+firstItem].analysis.bidiLevel;
     QTextEngine::bidiReorder(nItems, levels.data(), visualOrder.data());
     bool visual = eng->visualCursorMovement();
     if (x <= 0) {
         // left of first item
         int item = visualOrder[0]+firstItem;
         QScriptItem &si = eng->layoutData->items[item];
         if (!si.num_glyphs)
             eng->shape(item);
         int pos = si.position;
         if (si.analysis.bidiLevel % 2)
             pos += eng->length(item);
         pos = qMax(line.from, pos);
         pos = qMin(line.from + line_length, pos);
         return pos;
     } else if (x < line.textWidth
                || (line.justified && x < line.width)) {
         // has to be in one of the runs
         QFixed pos;
         bool rtl = eng->isRightToLeft();
         eng->shapeLine(line);
         QVector<int> insertionPoints;
         if (visual && rtl)
             eng->insertionPointsForLine(lineNum, insertionPoints);
         int nchars = 0;
         for (int i = 0; i < nItems; ++i) {
             int item = visualOrder[i]+firstItem;
             QScriptItem &si = eng->layoutData->items[item];
             int item_length = eng->length(item);
 //             qDebug("    item %d, visual %d x_remain=%f", i, item, x.toReal());
             int start = qMax(line.from - si.position, 0);
             int end = qMin(line.from + line_length - si.position, item_length);
             unsigned short *logClusters = eng->logClusters(&si);
             int gs = logClusters[start];
             int ge = (end == item_length ? si.num_glyphs : logClusters[end]) - 1;
             QGlyphLayout glyphs = eng->shapedGlyphs(&si);
             QFixed item_width = 0;
             if (si.analysis.flags >= QScriptAnalysis::TabOrObject) {
                 item_width = si.width;
             } else {
                 int g = gs;
                 while (g <= ge) {
                     item_width += glyphs.effectiveAdvance(g);
                     ++g;
                 }
             }
 //             qDebug("      start=%d, end=%d, gs=%d, ge=%d item_width=%f", start, end, gs, ge, item_width.toReal());
             if (pos + item_width < x) {
                 pos += item_width;
                 nchars += end;
                 continue;
             }
 //             qDebug("      inside run");
             if (si.analysis.flags >= QScriptAnalysis::TabOrObject) {
                 if (cpos == QTextLine::CursorOnCharacter)
                     return si.position;
                 bool left_half = (x - pos) < item_width/2;
                 if (bool(si.analysis.bidiLevel % 2) != left_half)
                     return si.position;
                 return si.position + 1;
             }
             int glyph_pos = -1;
             QFixed edge;
             // has to be inside run
             if (cpos == QTextLine::CursorOnCharacter) {
                 if (si.analysis.bidiLevel % 2) {
                     pos += item_width;
                     glyph_pos = gs;
                     while (gs <= ge) {
                         if (glyphs.attributes[gs].clusterStart) {
                             if (pos < x)
                                 break;
                             glyph_pos = gs;
                             edge = pos;
                             break;
                         }
                         pos -= glyphs.effectiveAdvance(gs);
                         ++gs;
                     }
                 } else {
                     glyph_pos = gs;
                     while (gs <= ge) {
                         if (glyphs.attributes[gs].clusterStart) {
                             if (pos > x)
                                 break;
                             glyph_pos = gs;
                             edge = pos;
                         }
                         pos += glyphs.effectiveAdvance(gs);
                         ++gs;
                     }
                 }
             } else {
                 QFixed dist = INT_MAX/256;
                 if (si.analysis.bidiLevel % 2) {
                     if (!visual || rtl || (lastLine && i == nItems - 1)) {
                         pos += item_width;
                         while (gs <= ge) {
                             if (glyphs.attributes[gs].clusterStart && qAbs(x-pos) < dist) {
                                 glyph_pos = gs;
                                 edge = pos;
                                 dist = qAbs(x-pos);
                             }
                             pos -= glyphs.effectiveAdvance(gs);
                             ++gs;
                         }
                     } else {
                         while (ge >= gs) {
                             if (glyphs.attributes[ge].clusterStart && qAbs(x-pos) < dist) {
                                 glyph_pos = ge;
                                 edge = pos;
                                 dist = qAbs(x-pos);
                             }
                             pos += glyphs.effectiveAdvance(ge);
                             --ge;
                         }
                     }
                 } else {
                     if (!visual || !rtl || (lastLine && i == 0)) {
                         while (gs <= ge) {
                             if (glyphs.attributes[gs].clusterStart && qAbs(x-pos) < dist) {
                                 glyph_pos = gs;
                                 edge = pos;
                                 dist = qAbs(x-pos);
                             }
                             pos += glyphs.effectiveAdvance(gs);
                             ++gs;
                         }
                     } else {
                         QFixed oldPos = pos;
                         while (gs <= ge) {
                             pos += glyphs.effectiveAdvance(gs);
                             if (glyphs.attributes[gs].clusterStart && qAbs(x-pos) < dist) {
                                 glyph_pos = gs;
                                 edge = pos;
                                 dist = qAbs(x-pos);
                             }
                             ++gs;
                         }
                         pos = oldPos;
                     }
                 }
                 if (qAbs(x-pos) < dist) {
                     if (visual) {
                         if (!rtl && i < nItems - 1) {
                             nchars += end;
                             continue;
                         }
                         if (rtl && nchars > 0)
                             return insertionPoints[lastLine ? nchars : nchars - 1];
                     }
                     return eng->positionInLigature(&si, end, x, pos, -1,
                                                    cpos == QTextLine::CursorOnCharacter);
                 }
             }
             Q_ASSERT(glyph_pos != -1);
             return eng->positionInLigature(&si, end, x, edge, glyph_pos,
                                            cpos == QTextLine::CursorOnCharacter);
         }
     }
     // right of last item
 //     qDebug() << "right of last";
     int item = visualOrder[nItems-1]+firstItem;
     QScriptItem &si = eng->layoutData->items[item];
     if (!si.num_glyphs)
         eng->shape(item);
     int pos = si.position;
     if (!(si.analysis.bidiLevel % 2))
         pos += eng->length(item);
     pos = qMax(line.from, pos);
     int maxPos = line.from + line_length;
     // except for the last line we assume that the
     // character between lines is a space and we want
     // to position the cursor to the left of that
     // character.
     // ###### breaks with japanese for example
     if (this->i < eng->lines.count() - 1)
         --maxPos;
     pos = qMin(pos, maxPos);
     return pos;
 }
y()
qreal QTextLine::y () const
Returns the line's y position.
See also
x(), rect(), textLength(), width()
Definition at line 1440 of file qtextlayout.cpp.
Referenced by QAccessibleTextWidget::characterRect(), flowPosition(), QTextControlPrivate::rectForPosition(), and QCommonStylePrivate::viewItemDrawText().
 {
     return eng->lines[i].y.toReal();
 }
Friends and Related Functions
QTextFragment
friend class QTextFragment friend
Definition at line 256 of file qtextlayout.h.
QTextLayout
friend class QTextLayout friend
Definition at line 255 of file qtextlayout.h.
Properties
eng
QTextEngine* QTextLine::eng private
Definition at line 258 of file qtextlayout.h.
i
int QTextLine::i private
Definition at line 257 of file qtextlayout.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextlayout.h
/src/gui/text/qtextlayout.cpp