Qt 4.8: QTextControl Class Reference
QTextControl Class Reference
#include <qtextcontrol_p.h>
Public Slots
void adjustSize ()
void append (const QString &text)
void appendHtml (const QString &html)
void appendPlainText (const QString &text)
void clear ()
void copy ()
void cut ()
void insertHtml (const QString &text)
void insertPlainText (const QString &text)
void paste (QClipboard::Mode mode=QClipboard::Clipboard)
void redo ()
void selectAll ()
void setHtml (const QString &text)
void setPlainText (const QString &text)
void undo ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void blockCountChanged (int newBlockCount)
void copyAvailable (bool b)
void currentCharFormatChanged (const QTextCharFormat &format)
void cursorPositionChanged ()
void documentSizeChanged (const QSizeF &)
void linkActivated (const QString &link)
void linkHovered (const QString &)
void microFocusChanged ()
void modificationChanged (bool m)
void redoAvailable (bool b)
void selectionChanged ()
void textChanged ()
void undoAvailable (bool b)
void updateRequest (const QRectF &rect=QRectF())
void visibilityRequest (const QRectF &rect)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool acceptRichText () const
QString anchorAt (const QPointF &pos) const
QString anchorAtCursor () const
QPointF anchorPosition (const QString &name) const
virtual QRectF blockBoundingRect (const QTextBlock &block) const
virtual bool canInsertFromMimeData (const QMimeData *source) const
bool canPaste () const
virtual QMimeData * createMimeDataFromSelection () const
QMenu * createStandardContextMenu (const QPointF &pos, QWidget *parent)
QTextCharFormat currentCharFormat () const
QTextCursor cursorForPosition (const QPointF &pos) const
bool cursorIsFocusIndicator () const
QRectF cursorRect (const QTextCursor &cursor) const
QRectF cursorRect () const
int cursorWidth () const
QTextDocument * document () const
void drawContents (QPainter *painter, const QRectF &rect=QRectF(), QWidget *widget=0)
virtual void ensureCursorVisible ()
QList< QTextEdit::ExtraSelection > extraSelections () const
bool find (const QString &exp, QTextDocument::FindFlags options=0)
bool findNextPrevAnchor (const QTextCursor &from, bool next, QTextCursor &newAnchor)
QAbstractTextDocumentLayout::PaintContext getPaintContext (QWidget *widget) const
virtual int hitTest (const QPointF &point, Qt::HitTestAccuracy accuracy) const
bool ignoreUnusedNavigationEvents () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery property) const
virtual void insertFromMimeData (const QMimeData *source)
bool isDragEnabled () const
bool isWordSelectionEnabled () const
virtual QVariant loadResource (int type, const QUrl &name)
void mergeCurrentCharFormat (const QTextCharFormat &modifier)
void moveCursor (QTextCursor::MoveOperation op, QTextCursor::MoveMode mode=QTextCursor::MoveAnchor)
bool openExternalLinks () const
bool overwriteMode () const
QPalette palette () const
void print (QPrinter *printer) const
virtual void processEvent (QEvent *e, const QMatrix &matrix, QWidget *contextWidget=0)
void processEvent (QEvent *e, const QPointF &coordinateOffset=QPointF(), QWidget *contextWidget=0)
QTextControl (QObject *parent=0)
QTextControl (const QString &text, QObject *parent=0)
QTextControl (QTextDocument *doc, QObject *parent=0)
QRectF selectionRect (const QTextCursor &cursor) const
QRectF selectionRect () const
void setAcceptRichText (bool accept)
void setCurrentCharFormat (const QTextCharFormat &format)
void setCursorIsFocusIndicator (bool b)
void setCursorWidth (int width)
void setDocument (QTextDocument *document)
void setDragEnabled (bool enabled)
void setExtraSelections (const QList< QTextEdit::ExtraSelection > &selections)
void setFocus (bool focus, Qt::FocusReason=Qt::OtherFocusReason)
bool setFocusToAnchor (const QTextCursor &newCursor)
bool setFocusToNextOrPreviousAnchor (bool next)
void setIgnoreUnusedNavigationEvents (bool ignore)
void setOpenExternalLinks (bool open)
void setOverwriteMode (bool overwrite)
void setPalette (const QPalette &pal)
void setTextCursor (const QTextCursor &cursor)
void setTextInteractionFlags (Qt::TextInteractionFlags flags)
void setTextWidth (qreal width)
void setWordSelectionEnabled (bool enabled)
QSizeF size () const
QTextCursor textCursor () const
Qt::TextInteractionFlags textInteractionFlags () const
qreal textWidth () const
QString toHtml () const
QString toPlainText () const
virtual ~QTextControl ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual bool event (QEvent *e)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual void timerEvent (QTimerEvent *e)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Properties
bool acceptRichText
int cursorWidth
QString html
bool ignoreUnusedNavigationEvents
bool openExternalLinks
bool overwriteMode
Qt::TextInteractionFlags textInteractionFlags
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 87 of file qtextcontrol_p.h.
Constructors and Destructors
QTextControl() [1/3]
QTextControl::QTextControl (QObject * parent = 0) explicit
Definition at line 787 of file qtextcontrol.cpp.
     : QObject(*new QTextControlPrivate, parent)
 {
     Q_D(QTextControl);
     d->init();
 }
QTextControl() [2/3]
QTextControl::QTextControl (const QString & text, QObject * parent = 0) explicit
Definition at line 794 of file qtextcontrol.cpp.
     : QObject(*new QTextControlPrivate, parent)
 {
     Q_D(QTextControl);
     d->init(Qt::RichText, text);
 }
QTextControl() [3/3]
QTextControl::QTextControl (QTextDocument * doc, QObject * parent = 0) explicit
Definition at line 801 of file qtextcontrol.cpp.
     : QObject(*new QTextControlPrivate, parent)
 {
     Q_D(QTextControl);
     d->init(Qt::RichText, QString(), doc);
 }
~QTextControl()
QTextControl::~QTextControl () virtual
Definition at line 808 of file qtextcontrol.cpp.
 {
 }
Functions
acceptRichText()
bool QTextControl::acceptRichText () const
Referenced by setCursorWidth().
adjustSize
void QTextControl::adjustSize () slot
Definition at line 2897 of file qtextcontrol.cpp.
Referenced by QGraphicsTextItem::adjustSize().
 {
     Q_D(QTextControl);
     d->doc->adjustSize();
 }
anchorAt()
QString QTextControl::anchorAt (const QPointF & pos) const
Definition at line 2223 of file qtextcontrol.cpp.
Referenced by createStandardContextMenu().
 {
     Q_D(const QTextControl);
     return d->doc->documentLayout()->anchorAt(pos);
 }
anchorAtCursor()
QString QTextControl::anchorAtCursor () const
Definition at line 2229 of file qtextcontrol.cpp.
Referenced by QTextBrowserPrivate::setSource().
 {
     Q_D(const QTextControl);
     return d->anchorForCursor(d->cursor);
 }
anchorPosition()
QPointF QTextControl::anchorPosition (const QString & name) const
Definition at line 2868 of file qtextcontrol.cpp.
 {
     Q_D(const QTextControl);
     if (name.isEmpty())
         return QPointF();
     QRectF r;
     for (QTextBlock block = d->doc->begin(); block.isValid(); block = block.next()) {
         QTextCharFormat format = block.charFormat();
         if (format.isAnchor() && format.anchorNames().contains(name)) {
             r = d->rectForPosition(block.position());
             break;
         }
         for (QTextBlock::Iterator it = block.begin(); !it.atEnd(); ++it) {
             QTextFragment fragment = it.fragment();
             format = fragment.charFormat();
             if (format.isAnchor() && format.anchorNames().contains(name)) {
                 r = d->rectForPosition(fragment.position());
                 block = QTextBlock();
                 break;
             }
         }
     }
     if (!r.isValid())
         return QPointF();
     return QPointF(0, r.top());
 }
append
void QTextControl::append (const QString & text) slot
Definition at line 2945 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     d->append(text, Qt::AutoText);
 }
appendHtml
void QTextControl::appendHtml (const QString & html) slot
Definition at line 2951 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     d->append(html, Qt::RichText);
 }
appendPlainText
void QTextControl::appendPlainText (const QString & text) slot
Definition at line 2957 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     d->append(text, Qt::PlainText);
 }
blockBoundingRect()
QRectF QTextControl::blockBoundingRect (const QTextBlock & block) const virtual
Reimplemented in QPlainTextEditControl.
Definition at line 3075 of file qtextcontrol.cpp.
Referenced by selectionRect().
 {
     Q_D(const QTextControl);
     return d->doc->documentLayout()->blockBoundingRect(block);
 }
blockCountChanged
void QTextControl::blockCountChanged (int newBlockCount) signal
canInsertFromMimeData()
bool QTextControl::canInsertFromMimeData (const QMimeData * source) const virtual
Reimplemented in QTextEditControl, and QPlainTextEditControl.
Definition at line 2487 of file qtextcontrol.cpp.
Referenced by QPlainTextEditControl::canInsertFromMimeData(), QTextEditControl::canInsertFromMimeData(), and canPaste().
 {
     Q_D(const QTextControl);
     if (d->acceptRichText)
         return (source->hasText() && !source->text().isEmpty())
             || source->hasHtml()
             || source->hasFormat(QLatin1String("application/x-qrichtext"))
             || source->hasFormat(QLatin1String("application/x-qt-richtext"));
     else
         return source->hasText() && !source->text().isEmpty();
 }
canPaste()
bool QTextControl::canPaste () const
Definition at line 2401 of file qtextcontrol.cpp.
Referenced by createStandardContextMenu().
 {
 #ifndef QT_NO_CLIPBOARD
     Q_D(const QTextControl);
     if (d->interactionFlags & Qt::TextEditable) {
         const QMimeData *md = QApplication::clipboard()->mimeData();
         return md && canInsertFromMimeData(md);
     }
 #endif
     return false;
 }
clear
void QTextControl::clear () slot
Definition at line 884 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     // clears and sets empty content
     d->extraSelections.clear();
     d->setContent();
 }
copy
void QTextControl::copy () slot
Definition at line 867 of file qtextcontrol.cpp.
Referenced by createStandardContextMenu(), and cut().
 {
     Q_D(QTextControl);
     if (!d->cursor.hasSelection())
         return;
     QMimeData *data = createMimeDataFromSelection();
     QApplication::clipboard()->setMimeData(data);
 }
copyAvailable
void QTextControl::copyAvailable (bool b) signal
createMimeDataFromSelection()
QMimeData * QTextControl::createMimeDataFromSelection () const virtual
Reimplemented in QTextEditControl, and QPlainTextEditControl.
Definition at line 2480 of file qtextcontrol.cpp.
Referenced by copy(), QPlainTextEditControl::createMimeDataFromSelection(), and QTextEditControl::createMimeDataFromSelection().
 {
     Q_D(const QTextControl);
     const QTextDocumentFragment fragment(d->cursor);
     return new QTextEditMimeData(fragment);
 }
createStandardContextMenu()
QMenu * QTextControl::createStandardContextMenu (const QPointF & pos, QWidget * parent)
Definition at line 2109 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     const bool showTextSelectionActions = d->interactionFlags & (Qt::TextEditable | Qt::TextSelectableByKeyboard | Qt::TextSelectableByMouse);
     d->linkToCopy = QString();
     if (!pos.isNull())
         d->linkToCopy = anchorAt(pos);
     if (d->linkToCopy.isEmpty() && !showTextSelectionActions)
         return 0;
     QMenu *menu = new QMenu(parent);
     QAction *a;
     if (d->interactionFlags & Qt::TextEditable) {
         a = menu->addAction(tr("&Undo") + ACCEL_KEY(QKeySequence::Undo), this, SLOT(undo()));
         a->setEnabled(d->doc->isUndoAvailable());
         a = menu->addAction(tr("&Redo") + ACCEL_KEY(QKeySequence::Redo), this, SLOT(redo()));
         a->setEnabled(d->doc->isRedoAvailable());
         menu->addSeparator();
         a = menu->addAction(tr("Cu&t") + ACCEL_KEY(QKeySequence::Cut), this, SLOT(cut()));
         a->setEnabled(d->cursor.hasSelection());
     }
     if (showTextSelectionActions) {
         a = menu->addAction(tr("&Copy") + ACCEL_KEY(QKeySequence::Copy), this, SLOT(copy()));
         a->setEnabled(d->cursor.hasSelection());
     }
     if ((d->interactionFlags & Qt::LinksAccessibleByKeyboard)
             || (d->interactionFlags & Qt::LinksAccessibleByMouse)) {
         a = menu->addAction(tr("Copy &Link Location"), this, SLOT(_q_copyLink()));
         a->setEnabled(!d->linkToCopy.isEmpty());
     }
     if (d->interactionFlags & Qt::TextEditable) {
 #if !defined(QT_NO_CLIPBOARD)
         a = menu->addAction(tr("&Paste") + ACCEL_KEY(QKeySequence::Paste), this, SLOT(paste()));
         a->setEnabled(canPaste());
 #endif
         a = menu->addAction(tr("Delete"), this, SLOT(_q_deleteSelected()));
         a->setEnabled(d->cursor.hasSelection());
     }
     if (showTextSelectionActions) {
         menu->addSeparator();
         a = menu->addAction(tr("Select All") + ACCEL_KEY(QKeySequence::SelectAll), this, SLOT(selectAll()));
         a->setEnabled(!d->doc->isEmpty());
     }
 #if !defined(QT_NO_IM)
     if (d->contextWidget) {
         QInputContext *qic = d->inputContext();
         if (qic) {
             QList<QAction *> imActions = qic->actions();
             for (int i = 0; i < imActions.size(); ++i)
                 menu->addAction(imActions.at(i));
         }
     }
 #endif
 #if defined(Q_WS_WIN) || defined(Q_WS_X11)
     if ((d->interactionFlags & Qt::TextEditable) && qt_use_rtl_extensions) {
 #else
     if (d->interactionFlags & Qt::TextEditable) {
 #endif
         menu->addSeparator();
         QUnicodeControlCharacterMenu *ctrlCharacterMenu = new QUnicodeControlCharacterMenu(this, menu);
         menu->addMenu(ctrlCharacterMenu);
     }
     return menu;
 }
currentCharFormat()
QTextCharFormat QTextControl::currentCharFormat () const
Definition at line 2848 of file qtextcontrol.cpp.
 {
     Q_D(const QTextControl);
     return d->cursor.charFormat();
 }
currentCharFormatChanged
void QTextControl::currentCharFormatChanged (const QTextCharFormat & format) signal
cursorForPosition()
QTextCursor QTextControl::cursorForPosition (const QPointF & pos) const
Definition at line 2189 of file qtextcontrol.cpp.
Referenced by QTextBrowserPrivate::setSource().
 {
     Q_D(const QTextControl);
     int cursorPos = hitTest(pos, Qt::FuzzyHit);
     if (cursorPos == -1)
         cursorPos = 0;
     QTextCursor c(d->doc);
     c.setPosition(cursorPos);
     return c;
 }
cursorIsFocusIndicator()
bool QTextControl::cursorIsFocusIndicator () const
Definition at line 2420 of file qtextcontrol.cpp.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), QTextBrowserPrivate::createHistoryEntry(), QTextControlPrivate::focusEvent(), QTextControlPrivate::mouseDoubleClickEvent(), and QTextControlPrivate::mousePressEvent().
 {
     Q_D(const QTextControl);
     return d->cursorIsFocusIndicator;
 }
cursorPositionChanged
void QTextControl::cursorPositionChanged () signal
Referenced by moveCursor(), and setTextCursor().
cursorRect() [1/2]
QRectF QTextControl::cursorRect (const QTextCursor & cursor) const
Definition at line 2200 of file qtextcontrol.cpp.
Referenced by QTextEditPrivate::pageUpDown().
 {
     Q_D(const QTextControl);
     if (cursor.isNull())
         return QRectF();
     return d->rectForPosition(cursor.position());
 }
cursorRect() [2/2]
QRectF QTextControl::cursorRect () const
Definition at line 2209 of file qtextcontrol.cpp.
Referenced by QPlainTextEditControl::cursorRect(), and inputMethodQuery().
 {
     Q_D(const QTextControl);
     return cursorRect(d->cursor);
 }
cursorWidth()
int QTextControl::cursorWidth () const
Referenced by QTextControlPrivate::rectForPosition(), and setOverwriteMode().
cut
void QTextControl::cut () slot
Definition at line 858 of file qtextcontrol.cpp.
Referenced by createStandardContextMenu().
 {
     Q_D(QTextControl);
     if (!(d->interactionFlags & Qt::TextEditable) || !d->cursor.hasSelection())
         return;
     copy();
     d->cursor.removeSelectedText();
 }
document()
QTextDocument * QTextControl::document () const
Definition at line 829 of file qtextcontrol.cpp.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), QPlainTextEditControl::blockBoundingRect(), QGraphicsTextItemPrivate::controlOffset(), QGraphicsTextItem::document(), documentSize(), QPlainTextEditControl::firstVisibleBlock(), QGraphicsTextItem::font(), QPlainTextEditControl::hitTest(), QTextEditPrivate::init(), QGraphicsTextItem::paint(), QTextBrowserPrivate::restoreHistoryEntry(), and QGraphicsTextItem::setFont().
 {
     Q_D(const QTextControl);
     return d->doc;
 }
documentSizeChanged
void QTextControl::documentSizeChanged (const QSizeF &) signal
drawContents()
void QTextControl::drawContents (QPainter * painter, const QRectF & rect = QRectF(), QWidget * widget = 0)
Definition at line 3037 of file qtextcontrol.cpp.
Referenced by QGraphicsTextItem::paint().
 {
     Q_D(QTextControl);
     p->save();
     QAbstractTextDocumentLayout::PaintContext ctx = getPaintContext(widget);
     if (rect.isValid())
         p->setClipRect(rect, Qt::IntersectClip);
     ctx.clip = rect;
     d->doc->documentLayout()->draw(p, ctx);
     p->restore();
 }
ensureCursorVisible()
void QTextControl::ensureCursorVisible () virtual
Reimplemented in QPlainTextEditControl.
Definition at line 2964 of file qtextcontrol.cpp.
Referenced by insertFromMimeData(), moveCursor(), and setTextCursor().
 {
     Q_D(QTextControl);
     QRectF crect = d->rectForPosition(d->cursor.position()).adjusted(-5, 0, 5, 0);
     emit visibilityRequest(crect);
     emit microFocusChanged();
 }
event()
bool QTextControl::event (QEvent * e) protected virtual
This virtual function receives events to an object and should return true if the event e was recognized and processed.
The event() function can be reimplemented to customize the behavior of an object.
See also
installEventFilter(), timerEvent(), QApplication::sendEvent(), QApplication::postEvent(), QWidget::event()
Reimplemented from QObject.
Definition at line 1133 of file qtextcontrol.cpp.
 {
     return QObject::event(e);
 }
extraSelections()
QList< QTextEdit::ExtraSelection > QTextControl::extraSelections () const
Definition at line 2332 of file qtextcontrol.cpp.
 {
     Q_D(const QTextControl);
     QList<QTextEdit::ExtraSelection> selections;
     for (int i = 0; i < d->extraSelections.count(); ++i) {
         QTextEdit::ExtraSelection sel;
         sel.cursor = d->extraSelections.at(i).cursor;
         sel.format = d->extraSelections.at(i).format;
         selections.append(sel);
     }
     return selections;
 }
find()
bool QTextControl::find (const QString & exp, QTextDocument::FindFlags options = 0)
Definition at line 2903 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     QTextCursor search = d->doc->find(exp, d->cursor, options);
     if (search.isNull())
         return false;
     setTextCursor(search);
     return true;
 }
findNextPrevAnchor()
bool QTextControl::findNextPrevAnchor (const QTextCursor & from, bool next, QTextCursor & newAnchor)
Definition at line 2533 of file qtextcontrol.cpp.
Referenced by setFocusToNextOrPreviousAnchor(), and QTextBrowserPrivate::setSource().
 {
     Q_D(QTextControl);
     int anchorStart = -1;
     QString anchorHref;
     int anchorEnd = -1;
     if (next) {
         const int startPos = startCursor.selectionEnd();
         QTextBlock block = d->doc->findBlock(startPos);
         QTextBlock::Iterator it = block.begin();
         while (!it.atEnd() && it.fragment().position() < startPos)
             ++it;
         while (block.isValid()) {
             anchorStart = -1;
             // find next anchor
             for (; !it.atEnd(); ++it) {
                 const QTextFragment fragment = it.fragment();
                 const QTextCharFormat fmt = fragment.charFormat();
                 if (fmt.isAnchor() && fmt.hasProperty(QTextFormat::AnchorHref)) {
                     anchorStart = fragment.position();
                     anchorHref = fmt.anchorHref();
                     break;
                 }
             }
             if (anchorStart != -1) {
                 anchorEnd = -1;
                 // find next non-anchor fragment
                 for (; !it.atEnd(); ++it) {
                     const QTextFragment fragment = it.fragment();
                     const QTextCharFormat fmt = fragment.charFormat();
                     if (!fmt.isAnchor() || fmt.anchorHref() != anchorHref) {
                         anchorEnd = fragment.position();
                         break;
                     }
                 }
                 if (anchorEnd == -1)
                     anchorEnd = block.position() + block.length() - 1;
                 // make found selection
                 break;
             }
             block = block.next();
             it = block.begin();
         }
     } else {
         int startPos = startCursor.selectionStart();
         if (startPos > 0)
             --startPos;
         QTextBlock block = d->doc->findBlock(startPos);
         QTextBlock::Iterator blockStart = block.begin();
         QTextBlock::Iterator it = block.end();
         if (startPos == block.position()) {
             it = block.begin();
         } else {
             do {
                 if (it == blockStart) {
                     it = QTextBlock::Iterator();
                     block = QTextBlock();
                 } else {
                     --it;
                 }
             } while (!it.atEnd() && it.fragment().position() + it.fragment().length() - 1 > startPos);
         }
         while (block.isValid()) {
             anchorStart = -1;
             if (!it.atEnd()) {
                 do {
                     const QTextFragment fragment = it.fragment();
                     const QTextCharFormat fmt = fragment.charFormat();
                     if (fmt.isAnchor() && fmt.hasProperty(QTextFormat::AnchorHref)) {
                         anchorStart = fragment.position() + fragment.length();
                         anchorHref = fmt.anchorHref();
                         break;
                     }
                     if (it == blockStart)
                         it = QTextBlock::Iterator();
                     else
                         --it;
                 } while (!it.atEnd());
             }
             if (anchorStart != -1 && !it.atEnd()) {
                 anchorEnd = -1;
                 do {
                     const QTextFragment fragment = it.fragment();
                     const QTextCharFormat fmt = fragment.charFormat();
                     if (!fmt.isAnchor() || fmt.anchorHref() != anchorHref) {
                         anchorEnd = fragment.position() + fragment.length();
                         break;
                     }
                     if (it == blockStart)
                         it = QTextBlock::Iterator();
                     else
                         --it;
                 } while (!it.atEnd());
                 if (anchorEnd == -1)
                     anchorEnd = qMax(0, block.position());
                 break;
             }
             block = block.previous();
             it = block.end();
             if (it != block.begin())
                 --it;
             blockStart = block.begin();
         }
     }
     if (anchorStart != -1 && anchorEnd != -1) {
         newAnchor = d->cursor;
         newAnchor.setPosition(anchorStart);
         newAnchor.setPosition(anchorEnd, QTextCursor::KeepAnchor);
         return true;
     }
     return false;
 }
getPaintContext()
QAbstractTextDocumentLayout::PaintContext QTextControl::getPaintContext (QWidget * widget) const
Definition at line 2984 of file qtextcontrol.cpp.
Referenced by drawContents().
 {
     Q_D(const QTextControl);
     QAbstractTextDocumentLayout::PaintContext ctx;
     ctx.selections = d->extraSelections;
     ctx.palette = d->palette;
     if (d->cursorOn && d->isEnabled) {
         if (d->hideCursor)
             ctx.cursorPosition = -1;
         else if (d->preeditCursor != 0)
             ctx.cursorPosition = - (d->preeditCursor + 2);
         else
             ctx.cursorPosition = d->cursor.position();
     }
     if (!d->dndFeedbackCursor.isNull())
         ctx.cursorPosition = d->dndFeedbackCursor.position();
 #ifdef QT_KEYPAD_NAVIGATION
     if (!QApplication::keypadNavigationEnabled() || d->hasEditFocus)
 #endif
     if (d->cursor.hasSelection()) {
         QAbstractTextDocumentLayout::Selection selection;
         selection.cursor = d->cursor;
         if (d->cursorIsFocusIndicator) {
             QStyleOption opt;
             opt.palette = ctx.palette;
             QStyleHintReturnVariant ret;
             QStyle *style = QApplication::style();
             if (widget)
                 style = widget->style();
             style->styleHint(QStyle::SH_TextControl_FocusIndicatorTextCharFormat, &opt, widget, &ret);
             selection.format = qvariant_cast<QTextFormat>(ret.variant).toCharFormat();
         } else {
             QPalette::ColorGroup cg = d->hasFocus ? QPalette::Active : QPalette::Inactive;
             selection.format.setBackground(ctx.palette.brush(cg, QPalette::Highlight));
             selection.format.setForeground(ctx.palette.brush(cg, QPalette::HighlightedText));
             QStyleOption opt;
             QStyle *style = QApplication::style();
             if (widget) {
                 opt.initFrom(widget);
                 style = widget->style();
             }
             if (style->styleHint(QStyle::SH_RichText_FullWidthSelection, &opt, widget))
                 selection.format.setProperty(QTextFormat::FullWidthSelection, true);
         }
         ctx.selections.append(selection);
     }
     return ctx;
 }
hitTest()
int QTextControl::hitTest (const QPointF & point, Qt::HitTestAccuracy accuracy) const virtual
Reimplemented in QPlainTextEditControl.
Definition at line 3069 of file qtextcontrol.cpp.
Referenced by cursorForPosition().
 {
     Q_D(const QTextControl);
     return d->doc->documentLayout()->hitTest(point, accuracy);
 }
ignoreUnusedNavigationEvents()
bool QTextControl::ignoreUnusedNavigationEvents () const
Referenced by setOpenExternalLinks().
inputMethodQuery()
QVariant QTextControl::inputMethodQuery (Qt::InputMethodQuery property) const virtual
Definition at line 2006 of file qtextcontrol.cpp.
Referenced by QGraphicsTextItem::inputMethodQuery().
 {
     Q_D(const QTextControl);
     QTextBlock block = d->cursor.block();
     switch(property) {
     case Qt::ImMicroFocus:
         return cursorRect();
     case Qt::ImFont:
         return QVariant(d->cursor.charFormat().font());
     case Qt::ImCursorPosition:
         return QVariant(d->cursor.position() - block.position());
     case Qt::ImSurroundingText:
         return QVariant(block.text());
     case Qt::ImCurrentSelection:
         return QVariant(d->cursor.selectedText());
     case Qt::ImMaximumTextLength:
         return QVariant(); // No limit.
     case Qt::ImAnchorPosition:
         return QVariant(qBound(0, d->cursor.anchor() - block.position(), block.length()));
     default:
         return QVariant();
     }
 }
insertFromMimeData()
void QTextControl::insertFromMimeData (const QMimeData * source) virtual
Reimplemented in QTextEditControl, and QPlainTextEditControl.
Definition at line 2499 of file qtextcontrol.cpp.
Referenced by QPlainTextEditControl::insertFromMimeData(), QTextEditControl::insertFromMimeData(), and paste().
 {
     Q_D(QTextControl);
     if (!(d->interactionFlags & Qt::TextEditable) || !source)
         return;
     bool hasData = false;
     QTextDocumentFragment fragment;
 #ifndef QT_NO_TEXTHTMLPARSER
     if (source->hasFormat(QLatin1String("application/x-qrichtext")) && d->acceptRichText) {
         // x-qrichtext is always UTF-8 (taken from Qt3 since we don't use it anymore).
         QString richtext = QString::fromUtf8(source->data(QLatin1String("application/x-qrichtext")));
         richtext.prepend(QLatin1String("<meta name=\"qrichtext\" content=\"1\" />"));
         fragment = QTextDocumentFragment::fromHtml(richtext, d->doc);
         hasData = true;
     } else if (source->hasHtml() && d->acceptRichText) {
         fragment = QTextDocumentFragment::fromHtml(source->html(), d->doc);
         hasData = true;
     } else {
         QString text = source->text();
         if (!text.isNull()) {
             fragment = QTextDocumentFragment::fromPlainText(text);
             hasData = true;
         }
     }
 #else
     fragment = QTextDocumentFragment::fromPlainText(source->text());
 #endif // QT_NO_TEXTHTMLPARSER
     if (hasData)
         d->cursor.insertFragment(fragment);
     ensureCursorVisible();
 }
insertHtml
void QTextControl::insertHtml (const QString & text) slot
Definition at line 2861 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     d->cursor.insertHtml(text);
 }
insertPlainText
void QTextControl::insertPlainText (const QString & text) slot
Definition at line 2854 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     d->cursor.insertText(text);
 }
isDragEnabled()
bool QTextControl::isDragEnabled () const
Definition at line 2433 of file qtextcontrol.cpp.
 {
     Q_D(const QTextControl);
     return d->dragEnabled;
 }
isWordSelectionEnabled()
bool QTextControl::isWordSelectionEnabled () const
Definition at line 2445 of file qtextcontrol.cpp.
 {
     Q_D(const QTextControl);
     return d->wordSelectionEnabled;
 }
linkActivated
void QTextControl::linkActivated (const QString & link) signal
linkHovered
void QTextControl::linkHovered (const QString &) signal
loadResource()
QVariant QTextControl::loadResource (int type, const QUrl & name) virtual
Reimplemented in QPlainTextEditControl.
Definition at line 1325 of file qtextcontrol.cpp.
 {
 #ifdef QT_NO_TEXTEDIT
     Q_UNUSED(type);
     Q_UNUSED(name);
 #else
     if (QTextEdit *textEdit = qobject_cast<QTextEdit *>(parent())) {
         QUrl resolvedName = textEdit->d_func()->resolveUrl(name);
         return textEdit->loadResource(type, resolvedName);
     }
 #endif
     return QVariant();
 }
mergeCurrentCharFormat()
void QTextControl::mergeCurrentCharFormat (const QTextCharFormat & modifier)
Definition at line 2834 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     d->cursor.mergeCharFormat(modifier);
     d->updateCurrentCharFormat();
 }
microFocusChanged
void QTextControl::microFocusChanged () signal
Referenced by QPlainTextEditControl::ensureCursorVisible(), and ensureCursorVisible().
modificationChanged
void QTextControl::modificationChanged (bool m) signal
moveCursor()
void QTextControl::moveCursor (QTextCursor::MoveOperation op, QTextCursor::MoveMode mode = QTextCursor::MoveAnchor)
Definition at line 2389 of file qtextcontrol.cpp.
Referenced by QPlainTextEditPrivate::mapToContents().
 {
     Q_D(QTextControl);
     const QTextCursor oldSelection = d->cursor;
     const bool moved = d->cursor.movePosition(op, mode);
     d->_q_updateCurrentCharFormatAndSelection();
     ensureCursorVisible();
     d->repaintOldAndNewSelection(oldSelection);
     if (moved)
         emit cursorPositionChanged();
 }
openExternalLinks()
bool QTextControl::openExternalLinks () const
Referenced by QTextControlPrivate::activateLinkUnderCursor(), and setOpenExternalLinks().
overwriteMode()
bool QTextControl::overwriteMode () const
Referenced by anchorAtCursor(), QPlainTextEditControl::hitTest(), QTextControlPrivate::keyPressEvent(), and QTextControlPrivate::rectForPosition().
palette()
QPalette QTextControl::palette () const
Definition at line 2972 of file qtextcontrol.cpp.
Referenced by QGraphicsTextItem::defaultTextColor(), and QGraphicsTextItem::setDefaultTextColor().
 {
     Q_D(const QTextControl);
     return d->palette;
 }
paste
void QTextControl::paste (QClipboard::Mode mode = QClipboard::Clipboard) slot
Definition at line 876 of file qtextcontrol.cpp.
Referenced by createStandardContextMenu().
 {
     const QMimeData *md = QApplication::clipboard()->mimeData(mode);
     if (md)
         insertFromMimeData(md);
 }
print()
void QTextControl::print (QPrinter * printer) const
Definition at line 2452 of file qtextcontrol.cpp.
 {
 #ifndef QT_NO_PRINTER
     Q_D(const QTextControl);
     if (!printer || !printer->isValid())
         return;
     QTextDocument *tempDoc = 0;
     const QTextDocument *doc = d->doc;
     if (printer->printRange() == QPrinter::Selection) {
         if (!d->cursor.hasSelection())
             return;
         tempDoc = new QTextDocument(const_cast<QTextDocument *>(doc));
         tempDoc->setMetaInformation(QTextDocument::DocumentTitle, doc->metaInformation(QTextDocument::DocumentTitle));
         tempDoc->setPageSize(doc->pageSize());
         tempDoc->setDefaultFont(doc->defaultFont());
         tempDoc->setUseDesignMetrics(doc->useDesignMetrics());
         QTextCursor(tempDoc).insertFragment(d->cursor.selection());
         doc = tempDoc;
         // copy the custom object handlers
         doc->documentLayout()->d_func()->handlers = d->doc->documentLayout()->d_func()->handlers;
     }
     doc->print(printer);
     delete tempDoc;
 #endif
 }
processEvent() [1/2]
void QTextControl::processEvent (QEvent * e, const QMatrix & matrix, QWidget * contextWidget = 0) virtual
Definition at line 910 of file qtextcontrol.cpp.
Referenced by processEvent(), QTextEditPrivate::sendControlEvent(), QGraphicsTextItemPrivate::sendControlEvent(), and setFocus().
 {
     Q_D(QTextControl);
     if (d->interactionFlags == Qt::NoTextInteraction) {
         e->ignore();
         return;
     }
     d->contextWidget = contextWidget;
     if (!d->contextWidget) {
         switch (e->type()) {
 #ifndef QT_NO_GRAPHICSVIEW
             case QEvent::GraphicsSceneMouseMove:
             case QEvent::GraphicsSceneMousePress:
             case QEvent::GraphicsSceneMouseRelease:
             case QEvent::GraphicsSceneMouseDoubleClick:
             case QEvent::GraphicsSceneContextMenu:
             case QEvent::GraphicsSceneHoverEnter:
             case QEvent::GraphicsSceneHoverMove:
             case QEvent::GraphicsSceneHoverLeave:
             case QEvent::GraphicsSceneHelp:
             case QEvent::GraphicsSceneDragEnter:
             case QEvent::GraphicsSceneDragMove:
             case QEvent::GraphicsSceneDragLeave:
             case QEvent::GraphicsSceneDrop: {
                 QGraphicsSceneEvent *ev = static_cast<QGraphicsSceneEvent *>(e);
                 d->contextWidget = ev->widget();
                 break;
             }
 #endif // QT_NO_GRAPHICSVIEW
             default: break;
         };
     }
     switch (e->type()) {
         case QEvent::KeyPress:
             d->keyPressEvent(static_cast<QKeyEvent *>(e));
             break;
         case QEvent::MouseButtonPress: {
             QMouseEvent *ev = static_cast<QMouseEvent *>(e);
             d->mousePressEvent(ev, ev->button(), matrix.map(ev->pos()), ev->modifiers(),
                                ev->buttons(), ev->globalPos());
             break; }
         case QEvent::MouseMove: {
             QMouseEvent *ev = static_cast<QMouseEvent *>(e);
             d->mouseMoveEvent(ev, ev->button(), matrix.map(ev->pos()), ev->modifiers(),
                               ev->buttons(), ev->globalPos());
             break; }
         case QEvent::MouseButtonRelease: {
             QMouseEvent *ev = static_cast<QMouseEvent *>(e);
             d->mouseReleaseEvent(ev, ev->button(), matrix.map(ev->pos()), ev->modifiers(),
                                  ev->buttons(), ev->globalPos());
             break; }
         case QEvent::MouseButtonDblClick: {
             QMouseEvent *ev = static_cast<QMouseEvent *>(e);
             d->mouseDoubleClickEvent(ev, ev->button(), matrix.map(ev->pos()), ev->modifiers(),
                                      ev->buttons(), ev->globalPos());
             break; }
         case QEvent::InputMethod:
             d->inputMethodEvent(static_cast<QInputMethodEvent *>(e));
             break;
 #ifndef QT_NO_CONTEXTMENU
     case QEvent::ContextMenu: {
             QContextMenuEvent *ev = static_cast<QContextMenuEvent *>(e);
             d->contextMenuEvent(ev->globalPos(), matrix.map(ev->pos()), contextWidget);
             break; }
 #endif // QT_NO_CONTEXTMENU
         case QEvent::FocusIn:
         case QEvent::FocusOut:
             d->focusEvent(static_cast<QFocusEvent *>(e));
             break;
         case QEvent::EnabledChange:
             d->isEnabled = e->isAccepted();
             break;
 #ifndef QT_NO_TOOLTIP
         case QEvent::ToolTip: {
             QHelpEvent *ev = static_cast<QHelpEvent *>(e);
             d->showToolTip(ev->globalPos(), matrix.map(ev->pos()), contextWidget);
             break;
         }
 #endif // QT_NO_TOOLTIP
 #ifndef QT_NO_DRAGANDDROP
         case QEvent::DragEnter: {
             QDragEnterEvent *ev = static_cast<QDragEnterEvent *>(e);
             if (d->dragEnterEvent(e, ev->mimeData()))
                 ev->acceptProposedAction();
             break;
         }
         case QEvent::DragLeave:
             d->dragLeaveEvent();
             break;
         case QEvent::DragMove: {
             QDragMoveEvent *ev = static_cast<QDragMoveEvent *>(e);
             if (d->dragMoveEvent(e, ev->mimeData(), matrix.map(ev->pos())))
                 ev->acceptProposedAction();
             break;
         }
         case QEvent::Drop: {
             QDropEvent *ev = static_cast<QDropEvent *>(e);
             if (d->dropEvent(ev->mimeData(), matrix.map(ev->pos()), ev->dropAction(), ev->source()))
                 ev->acceptProposedAction();
             break;
         }
 #endif
 #ifndef QT_NO_GRAPHICSVIEW
         case QEvent::GraphicsSceneMousePress: {
             QGraphicsSceneMouseEvent *ev = static_cast<QGraphicsSceneMouseEvent *>(e);
             d->mousePressEvent(ev, ev->button(), matrix.map(ev->pos()), ev->modifiers(), ev->buttons(),
                                ev->screenPos());
             break; }
         case QEvent::GraphicsSceneMouseMove: {
             QGraphicsSceneMouseEvent *ev = static_cast<QGraphicsSceneMouseEvent *>(e);
             d->mouseMoveEvent(ev, ev->button(), matrix.map(ev->pos()), ev->modifiers(), ev->buttons(),
                               ev->screenPos());
             break; }
         case QEvent::GraphicsSceneMouseRelease: {
             QGraphicsSceneMouseEvent *ev = static_cast<QGraphicsSceneMouseEvent *>(e);
             d->mouseReleaseEvent(ev, ev->button(), matrix.map(ev->pos()), ev->modifiers(), ev->buttons(),
                                  ev->screenPos());
             break; }
         case QEvent::GraphicsSceneMouseDoubleClick: {
             QGraphicsSceneMouseEvent *ev = static_cast<QGraphicsSceneMouseEvent *>(e);
             d->mouseDoubleClickEvent(ev, ev->button(), matrix.map(ev->pos()), ev->modifiers(), ev->buttons(),
                                      ev->screenPos());
             break; }
         case QEvent::GraphicsSceneContextMenu: {
             QGraphicsSceneContextMenuEvent *ev = static_cast<QGraphicsSceneContextMenuEvent *>(e);
             d->contextMenuEvent(ev->screenPos(), matrix.map(ev->pos()), contextWidget);
             break; }
         case QEvent::GraphicsSceneHoverMove: {
             QGraphicsSceneHoverEvent *ev = static_cast<QGraphicsSceneHoverEvent *>(e);
             d->mouseMoveEvent(ev, Qt::NoButton, matrix.map(ev->pos()), ev->modifiers(),Qt::NoButton,
                               ev->screenPos());
             break; }
         case QEvent::GraphicsSceneDragEnter: {
             QGraphicsSceneDragDropEvent *ev = static_cast<QGraphicsSceneDragDropEvent *>(e);
             if (d->dragEnterEvent(e, ev->mimeData()))
                 ev->acceptProposedAction();
             break; }
         case QEvent::GraphicsSceneDragLeave:
             d->dragLeaveEvent();
             break;
         case QEvent::GraphicsSceneDragMove: {
             QGraphicsSceneDragDropEvent *ev = static_cast<QGraphicsSceneDragDropEvent *>(e);
             if (d->dragMoveEvent(e, ev->mimeData(), matrix.map(ev->pos())))
                 ev->acceptProposedAction();
             break; }
         case QEvent::GraphicsSceneDrop: {
             QGraphicsSceneDragDropEvent *ev = static_cast<QGraphicsSceneDragDropEvent *>(e);
             if (d->dropEvent(ev->mimeData(), matrix.map(ev->pos()), ev->dropAction(), ev->source()))
                 ev->accept();
             break; }
 #endif // QT_NO_GRAPHICSVIEW
 #ifdef QT_KEYPAD_NAVIGATION
         case QEvent::EnterEditFocus:
         case QEvent::LeaveEditFocus:
             if (QApplication::keypadNavigationEnabled())
                 d->editFocusEvent(e);
             break;
 #endif
         case QEvent::ShortcutOverride:
             if (d->interactionFlags & Qt::TextEditable) {
                 QKeyEvent* ke = static_cast<QKeyEvent *>(e);
                 if (ke->modifiers() == Qt::NoModifier
                     || ke->modifiers() == Qt::ShiftModifier
                     || ke->modifiers() == Qt::KeypadModifier) {
                     if (ke->key() < Qt::Key_Escape) {
                         ke->accept();
                     } else {
                         switch (ke->key()) {
                             case Qt::Key_Return:
                             case Qt::Key_Enter:
                             case Qt::Key_Delete:
                             case Qt::Key_Home:
                             case Qt::Key_End:
                             case Qt::Key_Backspace:
                             case Qt::Key_Left:
                             case Qt::Key_Right:
                             case Qt::Key_Up:
                             case Qt::Key_Down:
                             case Qt::Key_Tab:
                             ke->accept();
                         default:
                             break;
                         }
                     }
 #ifndef QT_NO_SHORTCUT
                 } else if (ke == QKeySequence::Copy
                            || ke == QKeySequence::Paste
                            || ke == QKeySequence::Cut
                            || ke == QKeySequence::Redo
                            || ke == QKeySequence::Undo
                            || ke == QKeySequence::MoveToNextWord
                            || ke == QKeySequence::MoveToPreviousWord
                            || ke == QKeySequence::MoveToStartOfDocument
                            || ke == QKeySequence::MoveToEndOfDocument
                            || ke == QKeySequence::SelectNextWord
                            || ke == QKeySequence::SelectPreviousWord
                            || ke == QKeySequence::SelectStartOfLine
                            || ke == QKeySequence::SelectEndOfLine
                            || ke == QKeySequence::SelectStartOfBlock
                            || ke == QKeySequence::SelectEndOfBlock
                            || ke == QKeySequence::SelectStartOfDocument
                            || ke == QKeySequence::SelectEndOfDocument
                            || ke == QKeySequence::SelectAll
                           ) {
                     ke->accept();
 #endif
                 }
             }
             break;
         default:
             break;
     }
 }
processEvent() [2/2]
void QTextControl::processEvent (QEvent * e, const QPointF & coordinateOffset = QPointF(), QWidget * contextWidget = 0)
Definition at line 903 of file qtextcontrol.cpp.
 {
     QMatrix m;
     m.translate(coordinateOffset.x(), coordinateOffset.y());
     processEvent(e, m, contextWidget);
 }
redo
void QTextControl::redo () slot
Definition at line 775 of file qtextcontrol.cpp.
Referenced by createStandardContextMenu().
 {
     Q_D(QTextControl);
     d->repaintSelection();
     const int oldCursorPos = d->cursor.position();
     d->doc->redo(&d->cursor);
         if (d->cursor.position() != oldCursorPos)
         emit cursorPositionChanged();
     emit microFocusChanged();
     ensureCursorVisible();
 }
redoAvailable
void QTextControl::redoAvailable (bool b) signal
selectAll
void QTextControl::selectAll () slot
Definition at line 893 of file qtextcontrol.cpp.
Referenced by createStandardContextMenu().
 {
     Q_D(QTextControl);
     const int selectionLength = qAbs(d->cursor.position() - d->cursor.anchor());
     d->cursor.select(QTextCursor::Document);
     d->selectionChanged(selectionLength != qAbs(d->cursor.position() - d->cursor.anchor()));
     d->cursorIsFocusIndicator = false;
     emit updateRequest();
 }
selectionChanged
void QTextControl::selectionChanged () signal
Referenced by QTextControlPrivate::anchorForCursor(), QTextControlPrivate::keyPressEvent(), QTextControlPrivate::mouseDoubleClickEvent(), QTextControlPrivate::mouseMoveEvent(), QTextControlPrivate::mousePressEvent(), and QTextControlPrivate::mouseReleaseEvent().
selectionRect() [1/2]
QRectF QTextControl::selectionRect (const QTextCursor & cursor) const
Definition at line 1423 of file qtextcontrol.cpp.
Referenced by QTextBrowserPrivate::setSource().
 {
     Q_D(const QTextControl);
     QRectF r = d->rectForPosition(cursor.selectionStart());
     if (cursor.hasComplexSelection() && cursor.currentTable()) {
         QTextTable *table = cursor.currentTable();
         r = d->doc->documentLayout()->frameBoundingRect(table);
         /*
         int firstRow, numRows, firstColumn, numColumns;
         cursor.selectedTableCells(&firstRow, &numRows, &firstColumn, &numColumns);
         const QTextTableCell firstCell = table->cellAt(firstRow, firstColumn);
         const QTextTableCell lastCell = table->cellAt(firstRow + numRows - 1, firstColumn + numColumns - 1);
         const QAbstractTextDocumentLayout * const layout = doc->documentLayout();
         QRectF tableSelRect = layout->blockBoundingRect(firstCell.firstCursorPosition().block());
         for (int col = firstColumn; col < firstColumn + numColumns; ++col) {
             const QTextTableCell cell = table->cellAt(firstRow, col);
             const qreal y = layout->blockBoundingRect(cell.firstCursorPosition().block()).top();
             tableSelRect.setTop(qMin(tableSelRect.top(), y));
         }
         for (int row = firstRow; row < firstRow + numRows; ++row) {
             const QTextTableCell cell = table->cellAt(row, firstColumn);
             const qreal x = layout->blockBoundingRect(cell.firstCursorPosition().block()).left();
             tableSelRect.setLeft(qMin(tableSelRect.left(), x));
         }
         for (int col = firstColumn; col < firstColumn + numColumns; ++col) {
             const QTextTableCell cell = table->cellAt(firstRow + numRows - 1, col);
             const qreal y = layout->blockBoundingRect(cell.lastCursorPosition().block()).bottom();
             tableSelRect.setBottom(qMax(tableSelRect.bottom(), y));
         }
         for (int row = firstRow; row < firstRow + numRows; ++row) {
             const QTextTableCell cell = table->cellAt(row, firstColumn + numColumns - 1);
             const qreal x = layout->blockBoundingRect(cell.lastCursorPosition().block()).right();
             tableSelRect.setRight(qMax(tableSelRect.right(), x));
         }
         r = tableSelRect.toRect();
         */
     } else if (cursor.hasSelection()) {
         const int position = cursor.selectionStart();
         const int anchor = cursor.selectionEnd();
         const QTextBlock posBlock = d->doc->findBlock(position);
         const QTextBlock anchorBlock = d->doc->findBlock(anchor);
         if (posBlock == anchorBlock && posBlock.isValid() && posBlock.layout()->lineCount()) {
             const QTextLine posLine = posBlock.layout()->lineForTextPosition(position - posBlock.position());
             const QTextLine anchorLine = anchorBlock.layout()->lineForTextPosition(anchor - anchorBlock.position());
             const int firstLine = qMin(posLine.lineNumber(), anchorLine.lineNumber());
             const int lastLine = qMax(posLine.lineNumber(), anchorLine.lineNumber());
             const QTextLayout *layout = posBlock.layout();
             r = QRectF();
             for (int i = firstLine; i <= lastLine; ++i) {
                 r |= layout->lineAt(i).rect();
                 r |= layout->lineAt(i).naturalTextRect(); // might be bigger in the case of wrap not enabled
             }
             r.translate(blockBoundingRect(posBlock).topLeft());
         } else {
             QRectF anchorRect = d->rectForPosition(cursor.selectionEnd());
             r |= anchorRect;
             r |= boundingRectOfFloatsInSelection(cursor);
             QRectF frameRect(d->doc->documentLayout()->frameBoundingRect(cursor.currentFrame()));
             r.setLeft(frameRect.left());
             r.setRight(frameRect.right());
         }
         if (r.isValid())
             r.adjust(-1, -1, 1, 1);
     }
     return r;
 }
selectionRect() [2/2]
QRectF QTextControl::selectionRect () const
Definition at line 1507 of file qtextcontrol.cpp.
Referenced by setExtraSelections(), setFocusToAnchor(), and setFocusToNextOrPreviousAnchor().
 {
     Q_D(const QTextControl);
     return selectionRect(d->cursor);
 }
setAcceptRichText()
void QTextControl::setAcceptRichText (bool accept)
Definition at line 2278 of file qtextcontrol.cpp.
Referenced by QPlainTextEditControl::QPlainTextEditControl().
 {
     Q_D(QTextControl);
     d->acceptRichText = accept;
 }
setCurrentCharFormat()
void QTextControl::setCurrentCharFormat (const QTextCharFormat & format)
Definition at line 2841 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     d->cursor.setCharFormat(format);
     d->updateCurrentCharFormat();
 }
setCursorIsFocusIndicator()
void QTextControl::setCursorIsFocusIndicator (bool b)
Definition at line 2413 of file qtextcontrol.cpp.
Referenced by QTextBrowserPrivate::restoreHistoryEntry().
 {
     Q_D(QTextControl);
     d->cursorIsFocusIndicator = b;
     d->repaintCursor();
 }
setCursorWidth()
void QTextControl::setCursorWidth (int width)
Definition at line 2261 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
 #ifdef QT_NO_PROPERTIES
     Q_UNUSED(width);
 #else
     d->doc->documentLayout()->setProperty("cursorWidth", width);
 #endif
     d->repaintCursor();
 }
setDocument()
void QTextControl::setDocument (QTextDocument * document)
Definition at line 812 of file qtextcontrol.cpp.
Referenced by QPlainTextEditPrivate::init(), and QGraphicsTextItem::setDocument().
 {
     Q_D(QTextControl);
     if (d->doc == document)
         return;
     d->doc->disconnect(this);
     d->doc->documentLayout()->disconnect(this);
     d->doc->documentLayout()->setPaintDevice(0);
     if (d->doc->parent() == this)
         delete d->doc;
     d->doc = 0;
     d->setContent(Qt::RichText, QString(), document);
 }
setDragEnabled()
void QTextControl::setDragEnabled (bool enabled)
Definition at line 2427 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     d->dragEnabled = enabled;
 }
setExtraSelections()
void QTextControl::setExtraSelections (const QList< QTextEdit::ExtraSelection > & selections)
Definition at line 2286 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     QHash<int, int> hash;
     for (int i = 0; i < d->extraSelections.count(); ++i) {
         const QAbstractTextDocumentLayout::Selection &esel = d->extraSelections.at(i);
         hash.insertMulti(esel.cursor.anchor(), i);
     }
     for (int i = 0; i < selections.count(); ++i) {
         const QTextEdit::ExtraSelection &sel = selections.at(i);
         QHash<int, int>::iterator it = hash.find(sel.cursor.anchor());
         if (it != hash.end()) {
             const QAbstractTextDocumentLayout::Selection &esel = d->extraSelections.at(it.value());
             if (esel.cursor.position() == sel.cursor.position()
                 && esel.format == sel.format) {
                 hash.erase(it);
                 continue;
             }
         }
         QRectF r = selectionRect(sel.cursor);
         if (sel.format.boolProperty(QTextFormat::FullWidthSelection)) {
             r.setLeft(0);
             r.setWidth(qreal(INT_MAX));
         }
         emit updateRequest(r);
     }
     for (QHash<int, int>::iterator it = hash.begin(); it != hash.end(); ++it) {
         const QAbstractTextDocumentLayout::Selection &esel = d->extraSelections.at(it.value());
         QRectF r = selectionRect(esel.cursor);
         if (esel.format.boolProperty(QTextFormat::FullWidthSelection)) {
             r.setLeft(0);
             r.setWidth(qreal(INT_MAX));
         }
         emit updateRequest(r);
     }
     d->extraSelections.resize(selections.count());
     for (int i = 0; i < selections.count(); ++i) {
         d->extraSelections[i].cursor = selections.at(i).cursor;
         d->extraSelections[i].format = selections.at(i).format;
     }
 }
setFocus()
void QTextControl::setFocus (bool focus, Qt::FocusReason reason = Qt::OtherFocusReason)
Definition at line 2030 of file qtextcontrol.cpp.
 {
     QFocusEvent ev(focus ? QEvent::FocusIn : QEvent::FocusOut,
                    reason);
     processEvent(&ev);
 }
setFocusToAnchor()
bool QTextControl::setFocusToAnchor (const QTextCursor & newCursor)
Definition at line 2791 of file qtextcontrol.cpp.
Referenced by QTextBrowserPrivate::setSource().
 {
     Q_D(QTextControl);
     if (!(d->interactionFlags & Qt::LinksAccessibleByKeyboard))
         return false;
     // Verify that this is an anchor.
     const QString anchorHref = d->anchorForCursor(newCursor);
     if (anchorHref.isEmpty())
         return false;
     // and process it
     QRectF crect = selectionRect();
     emit updateRequest(crect);
     d->cursor.setPosition(newCursor.selectionStart());
     d->cursor.setPosition(newCursor.selectionEnd(), QTextCursor::KeepAnchor);
     d->cursorIsFocusIndicator = true;
     crect = selectionRect();
     emit updateRequest(crect);
     emit visibilityRequest(crect);
     return true;
 }
setFocusToNextOrPreviousAnchor()
bool QTextControl::setFocusToNextOrPreviousAnchor (bool next)
Definition at line 2754 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     if (!(d->interactionFlags & Qt::LinksAccessibleByKeyboard))
         return false;
     QRectF crect = selectionRect();
     emit updateRequest(crect);
     // If we don't have a current anchor, we start from the start/end
     if (!d->cursor.hasSelection()) {
         d->cursor = QTextCursor(d->doc);
         if (next)
             d->cursor.movePosition(QTextCursor::Start);
         else
             d->cursor.movePosition(QTextCursor::End);
     }
     QTextCursor newAnchor;
     if (findNextPrevAnchor(d->cursor, next, newAnchor)) {
         d->cursor = newAnchor;
         d->cursorIsFocusIndicator = true;
     } else {
         d->cursor.clearSelection();
     }
     if (d->cursor.hasSelection()) {
         crect = selectionRect();
         emit updateRequest(crect);
         emit visibilityRequest(crect);
         return true;
     } else {
         return false;
     }
 }
setHtml
void QTextControl::setHtml (const QString & text) slot
Definition at line 1160 of file qtextcontrol.cpp.
Referenced by QTextEditPrivate::init(), and QGraphicsTextItem::setHtml().
 {
     Q_D(QTextControl);
     d->setContent(Qt::RichText, text);
 }
setIgnoreUnusedNavigationEvents()
void QTextControl::setIgnoreUnusedNavigationEvents (bool ignore)
Definition at line 2383 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     d->ignoreUnusedNavigationEvents = ignore;
 }
setOpenExternalLinks()
void QTextControl::setOpenExternalLinks (bool open)
Definition at line 2365 of file qtextcontrol.cpp.
Referenced by QGraphicsTextItem::setOpenExternalLinks().
 {
     Q_D(QTextControl);
     d->openExternalLinks = open;
 }
setOverwriteMode()
void QTextControl::setOverwriteMode (bool overwrite)
Definition at line 2242 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     d->overwriteMode = overwrite;
 }
setPalette()
void QTextControl::setPalette (const QPalette & pal)
Definition at line 2978 of file qtextcontrol.cpp.
Referenced by QTextEditPrivate::init(), QPlainTextEditPrivate::init(), and QGraphicsTextItem::setDefaultTextColor().
 {
     Q_D(QTextControl);
     d->palette = pal;
 }
setPlainText
void QTextControl::setPlainText (const QString & text) slot
Definition at line 1154 of file qtextcontrol.cpp.
Referenced by QPlainTextEditPrivate::init(), and QGraphicsTextItem::setPlainText().
 {
     Q_D(QTextControl);
     d->setContent(Qt::PlainText, text);
 }
setTextCursor()
void QTextControl::setTextCursor (const QTextCursor & cursor)
Definition at line 835 of file qtextcontrol.cpp.
Referenced by QTextEditPrivate::createAutoBulletList(), find(), QTextEditPrivate::pageUpDown(), QPlainTextEditPrivate::pageUpDown(), QTextBrowserPrivate::restoreHistoryEntry(), QTextBrowserPrivate::setSource(), and QGraphicsTextItem::setTextCursor().
 {
     Q_D(QTextControl);
     d->cursorIsFocusIndicator = false;
     const bool posChanged = cursor.position() != d->cursor.position();
     const QTextCursor oldSelection = d->cursor;
     d->cursor = cursor;
     d->cursorOn = d->hasFocus && (d->interactionFlags & Qt::TextEditable);
     d->_q_updateCurrentCharFormatAndSelection();
     ensureCursorVisible();
     d->repaintOldAndNewSelection(oldSelection);
     if (posChanged)
         emit cursorPositionChanged();
 }
setTextInteractionFlags()
void QTextControl::setTextInteractionFlags (Qt::TextInteractionFlags flags)
Definition at line 2817 of file qtextcontrol.cpp.
Referenced by QTextBrowserPrivate::init(), and QGraphicsTextItem::setTextInteractionFlags().
 {
     Q_D(QTextControl);
     if (flags == d->interactionFlags)
         return;
     d->interactionFlags = flags;
     if (d->hasFocus)
         d->setBlinkingCursorEnabled(flags & (Qt::TextEditable | Qt::TextSelectableByKeyboard));
 }
setTextWidth()
void QTextControl::setTextWidth (qreal width)
Definition at line 2347 of file qtextcontrol.cpp.
Referenced by QGraphicsTextItem::setTextWidth().
 {
     Q_D(QTextControl);
     d->doc->setTextWidth(width);
 }
setWordSelectionEnabled()
void QTextControl::setWordSelectionEnabled (bool enabled)
Definition at line 2439 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     d->wordSelectionEnabled = enabled;
 }
size()
QSizeF QTextControl::size () const
Definition at line 2359 of file qtextcontrol.cpp.
Referenced by QGraphicsTextItem::setDocument(), and QTextBrowserPrivate::setSource().
 {
     Q_D(const QTextControl);
     return d->doc->size();
 }
textChanged
void QTextControl::textChanged () signal
textCursor()
QTextCursor QTextControl::textCursor () const
Definition at line 850 of file qtextcontrol.cpp.
Referenced by QTextEditPrivate::createAutoBulletList(), QTextBrowserPrivate::createHistoryEntry(), QPlainTextEditControl::cursorRect(), QTextEditPrivate::pageUpDown(), QPlainTextEditPrivate::pageUpDown(), QTextBrowserPrivate::restoreHistoryEntry(), QTextBrowserPrivate::setSource(), and QGraphicsTextItem::textCursor().
 {
     Q_D(const QTextControl);
     return d->cursor;
 }
textInteractionFlags()
Qt::TextInteractionFlags QTextControl::textInteractionFlags () const
Referenced by setTextInteractionFlags().
textWidth()
qreal QTextControl::textWidth () const
Definition at line 2353 of file qtextcontrol.cpp.
Referenced by QGraphicsTextItem::textWidth().
 {
     Q_D(const QTextControl);
     return d->doc->textWidth();
 }
timerEvent()
void QTextControl::timerEvent (QTimerEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 1138 of file qtextcontrol.cpp.
 {
     Q_D(QTextControl);
     if (e->timerId() == d->cursorBlinkTimer.timerId()) {
         d->cursorOn = !d->cursorOn;
         if (d->cursor.hasSelection())
             d->cursorOn &= (QApplication::style()->styleHint(QStyle::SH_BlinkCursorWhenTextSelected)
                             != 0);
         d->repaintCursor();
     } else if (e->timerId() == d->trippleClickTimer.timerId()) {
         d->trippleClickTimer.stop();
     }
 }
toHtml()
QString QTextControl::toHtml () const inline
Definition at line 125 of file qtextcontrol_p.h.
Referenced by QGraphicsTextItem::toHtml().
     { return document()->toHtml(); }
toPlainText()
QString QTextControl::toPlainText () const inline
Definition at line 122 of file qtextcontrol_p.h.
Referenced by QGraphicsTextItem::toPlainText().
     { return document()->toPlainText(); }
undo
void QTextControl::undo () slot
Definition at line 763 of file qtextcontrol.cpp.
Referenced by createStandardContextMenu().
 {
     Q_D(QTextControl);
     d->repaintSelection();
     const int oldCursorPos = d->cursor.position();
     d->doc->undo(&d->cursor);
     if (d->cursor.position() != oldCursorPos)
         emit cursorPositionChanged();
     emit microFocusChanged();
     ensureCursorVisible();
 }
undoAvailable
void QTextControl::undoAvailable (bool b) signal
updateRequest
void QTextControl::updateRequest (const QRectF & rect = QRectF()) signal
Referenced by selectAll(), setExtraSelections(), setFocusToAnchor(), and setFocusToNextOrPreviousAnchor().
visibilityRequest
void QTextControl::visibilityRequest (const QRectF & rect) signal
Referenced by ensureCursorVisible(), setFocusToAnchor(), and setFocusToNextOrPreviousAnchor().
Properties
acceptRichText
bool QTextControl::acceptRichText private
Definition at line 95 of file qtextcontrol_p.h.
cursorWidth
int QTextControl::cursorWidth private
Definition at line 96 of file qtextcontrol_p.h.
html
QString QTextControl::html private
Definition at line 92 of file qtextcontrol_p.h.
ignoreUnusedNavigationEvents
bool QTextControl::ignoreUnusedNavigationEvents private
Definition at line 99 of file qtextcontrol_p.h.
openExternalLinks
bool QTextControl::openExternalLinks private
Definition at line 98 of file qtextcontrol_p.h.
Referenced by QGraphicsTextItem::openExternalLinks().
overwriteMode
bool QTextControl::overwriteMode private
Definition at line 94 of file qtextcontrol_p.h.
textInteractionFlags
Qt::TextInteractionFlags QTextControl::textInteractionFlags private
Definition at line 97 of file qtextcontrol_p.h.
Referenced by QGraphicsTextItem::mousePressEvent(), QGraphicsTextItem::mouseReleaseEvent(), and QGraphicsTextItem::textInteractionFlags().
The documentation for this class was generated from the following files:
/src/gui/text/qtextcontrol_p.h
/src/gui/text/qtextcontrol.cpp