Qt 4.8: QEventDispatcherGlib Class Reference
QEventDispatcherGlib Class Reference
#include <qeventdispatcher_glib_p.h>
Public Functions
void flush ()
Flushes the event queue.
bool hasPendingEvents ()
Returns true if there is an event waiting; otherwise returns false.
void interrupt ()
Interrupts event dispatching; i.
bool processEvents (QEventLoop::ProcessEventsFlags flags)
Processes pending events that match flags until there are no more events to process.
QEventDispatcherGlib (QObject *parent=0)
QEventDispatcherGlib (GMainContext *context, QObject *parent=0)
QList< TimerInfo > registeredTimers (QObject *object) const
Returns a list of registered timers for object.
void registerSocketNotifier (QSocketNotifier *socketNotifier)
Registers notifier with the event loop.
void registerTimer (int timerId, int interval, QObject *object)
Register a timer with the specified timerId and interval for the given object.
void unregisterSocketNotifier (QSocketNotifier *socketNotifier)
Unregisters notifier from the event dispatcher.
bool unregisterTimer (int timerId)
Unregisters the timer with the given timerId.
bool unregisterTimers (QObject *object)
Unregisters all the timers associated with the given object.
void wakeUp ()
Wakes up the event loop.
~QEventDispatcherGlib ()
Public Functions inherited from QAbstractEventDispatcher
virtual void closingDown ()
bool filterEvent (void *message)
Sends message through the event filter that was set by setEventFilter().
QAbstractEventDispatcher (QObject *parent=0)
Constructs a new event dispatcher with the given parent.
int registerTimer (int interval, QObject *object)
Registers a timer with the specified interval for the given object.
EventFilter setEventFilter (EventFilter filter)
Replaces the event filter function for this QAbstractEventDispatcher with filter and returns the replaced event filter function.
virtual void startingUp ()
~QAbstractEventDispatcher ()
Destroys the event dispatcher.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool versionSupported ()
Static Public Functions inherited from QAbstractEventDispatcher
static QAbstractEventDispatcher * instance (QThread *thread=0)
Returns a pointer to the event dispatcher object for the specified thread.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
QEventDispatcherGlib (QEventDispatcherGlibPrivate &dd, QObject *parent)
Protected Functions inherited from QAbstractEventDispatcher
QAbstractEventDispatcher (QAbstractEventDispatcherPrivate &, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Types inherited from QAbstractEventDispatcher
typedef bool(* EventFilter) (void *message)
Typedef for a function with the signature.
typedef QPair< int, int > TimerInfo
Typedef for QPair<int, int>.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractEventDispatcher
void aboutToBlock ()
This signal is emitted before the event loop calls a function that could block.
void awake ()
This signal is emitted after the event loop returns from a function that could block.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 67 of file qeventdispatcher_glib_p.h.
Constructors and Destructors
QEventDispatcherGlib() [1/3]
QEventDispatcherGlib::QEventDispatcherGlib (QObject * parent = 0) explicit
Definition at line 359 of file qeventdispatcher_glib.cpp.
     : QAbstractEventDispatcher(*(new QEventDispatcherGlibPrivate), parent)
 {
 }
QEventDispatcherGlib() [2/3]
QEventDispatcherGlib::QEventDispatcherGlib (GMainContext * context, QObject * parent = 0) explicit
Definition at line 364 of file qeventdispatcher_glib.cpp.
     : QAbstractEventDispatcher(*(new QEventDispatcherGlibPrivate(mainContext)), parent)
 { }
~QEventDispatcherGlib()
QEventDispatcherGlib::~QEventDispatcherGlib ()
Definition at line 368 of file qeventdispatcher_glib.cpp.
 {
     Q_D(QEventDispatcherGlib);
     // destroy all timer sources
     qDeleteAll(d->timerSource->timerList);
     d->timerSource->timerList.~QTimerInfoList();
     g_source_destroy(&d->timerSource->source);
     g_source_unref(&d->timerSource->source);
     d->timerSource = 0;
     g_source_destroy(&d->idleTimerSource->source);
     g_source_unref(&d->idleTimerSource->source);
     d->idleTimerSource = 0;
     // destroy socket notifier source
     for (int i = 0; i < d->socketNotifierSource->pollfds.count(); ++i) {
         GPollFDWithQSocketNotifier *p = d->socketNotifierSource->pollfds[i];
         g_source_remove_poll(&d->socketNotifierSource->source, &p->pollfd);
         delete p;
     }
     d->socketNotifierSource->pollfds.~QList<GPollFDWithQSocketNotifier *>();
     g_source_destroy(&d->socketNotifierSource->source);
     g_source_unref(&d->socketNotifierSource->source);
     d->socketNotifierSource = 0;
     // destroy post event source
     g_source_destroy(&d->postEventSource->source);
     g_source_unref(&d->postEventSource->source);
     d->postEventSource = 0;
     Q_ASSERT(d->mainContext != 0);
 #if GLIB_CHECK_VERSION (2, 22, 0)
     g_main_context_pop_thread_default (d->mainContext);
 #endif
     g_main_context_unref(d->mainContext);
     d->mainContext = 0;
 }
QEventDispatcherGlib() [3/3]
QEventDispatcherGlib::QEventDispatcherGlib (QEventDispatcherGlibPrivate & dd, QObject * parent) protected
Definition at line 597 of file qeventdispatcher_glib.cpp.
     : QAbstractEventDispatcher(dd, parent)
 {
 }
Functions
flush()
void QEventDispatcherGlib::flush () virtual
Flushes the event queue.
This normally returns almost immediately. Does nothing on platforms other than X11.
Implements QAbstractEventDispatcher.
Reimplemented in QGuiEventDispatcherGlib.
Definition at line 584 of file qeventdispatcher_glib.cpp.
 {
 }
hasPendingEvents()
bool QEventDispatcherGlib::hasPendingEvents () virtual
Returns true if there is an event waiting; otherwise returns false.
Implements QAbstractEventDispatcher.
Definition at line 437 of file qeventdispatcher_glib.cpp.
 {
     Q_D(QEventDispatcherGlib);
     return g_main_context_pending(d->mainContext);
 }
interrupt()
void QEventDispatcherGlib::interrupt () virtual
Interrupts event dispatching; i.
e. the event dispatcher will return from processEvents() as soon as possible.
Implements QAbstractEventDispatcher.
Definition at line 572 of file qeventdispatcher_glib.cpp.
 {
     wakeUp();
 }
processEvents()
bool QEventDispatcherGlib::processEvents (QEventLoop::ProcessEventsFlags flags) virtual
Processes pending events that match flags until there are no more events to process.
Returns true if an event was processed; otherwise returns false.
This function is especially useful if you have a long running operation and want to show its progress without allowing user input; i.e. by using the QEventLoop::ExcludeUserInputEvents flag.
If the QEventLoop::WaitForMoreEvents flag is set in flags, the behavior of this function is as follows:
If events are available, this function returns after processing them.
If no events are available, this function will wait until more are available and return after processing newly available events.
If the QEventLoop::WaitForMoreEvents flag is not set in flags, and no events are available, this function will return immediately.
Note: This function does not process events continuously; it returns after all available events are processed.
See also
hasPendingEvents()
Implements QAbstractEventDispatcher.
Reimplemented in QPAEventDispatcherGlib, QWSEventDispatcherGlib, and QGuiEventDispatcherGlib.
Definition at line 406 of file qeventdispatcher_glib.cpp.
Referenced by QWSEventDispatcherGlib::processEvents(), QGuiEventDispatcherGlib::processEvents(), and QPAEventDispatcherGlib::processEvents().
 {
     Q_D(QEventDispatcherGlib);
     const bool canWait = (flags & QEventLoop::WaitForMoreEvents);
     if (canWait)
         emit aboutToBlock();
     else
         emit awake();
     // tell postEventSourcePrepare() and timerSource about any new flags
     QEventLoop::ProcessEventsFlags savedFlags = d->timerSource->processEventsFlags;
     d->timerSource->processEventsFlags = flags;
     if (!(flags & QEventLoop::EventLoopExec)) {
         // force timers to be sent at normal priority
         d->timerSource->runWithIdlePriority = false;
     }
     bool result = g_main_context_iteration(d->mainContext, canWait);
     while (!result && canWait)
         result = g_main_context_iteration(d->mainContext, canWait);
     d->timerSource->processEventsFlags = savedFlags;
     if (canWait)
         emit awake();
     return result;
 }
registeredTimers()
QList< QEventDispatcherGlib::TimerInfo > QEventDispatcherGlib::registeredTimers (QObject * object) const virtual
Returns a list of registered timers for object.
The timer ID is the first member in each pair; the interval is the second.
Implements QAbstractEventDispatcher.
Definition at line 561 of file qeventdispatcher_glib.cpp.
 {
     if (!object) {
         qWarning("QEventDispatcherUNIX:registeredTimers: invalid argument");
         return QList<TimerInfo>();
     }
     Q_D(const QEventDispatcherGlib);
     return d->timerSource->timerList.registeredTimers(object);
 }
registerSocketNotifier()
void QEventDispatcherGlib::registerSocketNotifier (QSocketNotifier * notifier) virtual
Registers notifier with the event loop.
Subclasses must implement this method to tie a socket notifier into another event loop.
Implements QAbstractEventDispatcher.
Definition at line 443 of file qeventdispatcher_glib.cpp.
 {
     Q_ASSERT(notifier);
     int sockfd = notifier->socket();
     int type = notifier->type();
 #ifndef QT_NO_DEBUG
     if (sockfd < 0) {
         qWarning("QSocketNotifier: Internal error");
         return;
     } else if (notifier->thread() != thread()
                || thread() != QThread::currentThread()) {
         qWarning("QSocketNotifier: socket notifiers cannot be enabled from another thread");
         return;
     }
 #endif
     Q_D(QEventDispatcherGlib);
     GPollFDWithQSocketNotifier *p = new GPollFDWithQSocketNotifier;
     p->pollfd.fd = sockfd;
     switch (type) {
     case QSocketNotifier::Read:
         p->pollfd.events = G_IO_IN | G_IO_HUP | G_IO_ERR;
         break;
     case QSocketNotifier::Write:
         p->pollfd.events = G_IO_OUT | G_IO_ERR;
         break;
     case QSocketNotifier::Exception:
         p->pollfd.events = G_IO_PRI | G_IO_ERR;
         break;
     }
     p->socketNotifier = notifier;
     d->socketNotifierSource->pollfds.append(p);
     g_source_add_poll(&d->socketNotifierSource->source, &p->pollfd);
 }
registerTimer()
void QEventDispatcherGlib::registerTimer (int timerId, int interval, QObject * object) virtual
Register a timer with the specified timerId and interval for the given object.
Implements QAbstractEventDispatcher.
Definition at line 513 of file qeventdispatcher_glib.cpp.
 {
 #ifndef QT_NO_DEBUG
     if (timerId < 1 || interval < 0 || !object) {
         qWarning("QEventDispatcherGlib::registerTimer: invalid arguments");
         return;
     } else if (object->thread() != thread() || thread() != QThread::currentThread()) {
         qWarning("QObject::startTimer: timers cannot be started from another thread");
         return;
     }
 #endif
     Q_D(QEventDispatcherGlib);
     d->timerSource->timerList.registerTimer(timerId, interval, object);
 }
unregisterSocketNotifier()
void QEventDispatcherGlib::unregisterSocketNotifier (QSocketNotifier * notifier) virtual
Unregisters notifier from the event dispatcher.
Subclasses must reimplement this method to tie a socket notifier into another event loop. Reimplementations must call the base implementation.
Implements QAbstractEventDispatcher.
Definition at line 482 of file qeventdispatcher_glib.cpp.
 {
     Q_ASSERT(notifier);
 #ifndef QT_NO_DEBUG
     int sockfd = notifier->socket();
     if (sockfd < 0) {
         qWarning("QSocketNotifier: Internal error");
         return;
     } else if (notifier->thread() != thread()
                || thread() != QThread::currentThread()) {
         qWarning("QSocketNotifier: socket notifiers cannot be disabled from another thread");
         return;
     }
 #endif
     Q_D(QEventDispatcherGlib);
     for (int i = 0; i < d->socketNotifierSource->pollfds.count(); ++i) {
         GPollFDWithQSocketNotifier *p = d->socketNotifierSource->pollfds.at(i);
         if (p->socketNotifier == notifier) {
             // found it
             g_source_remove_poll(&d->socketNotifierSource->source, &p->pollfd);
             d->socketNotifierSource->pollfds.removeAt(i);
             delete p;
             return;
         }
     }
 }
unregisterTimer()
bool QEventDispatcherGlib::unregisterTimer (int timerId) virtual
Unregisters the timer with the given timerId.
Returns true if successful; otherwise returns false.
See also
registerTimer(), unregisterTimers()
Implements QAbstractEventDispatcher.
Definition at line 529 of file qeventdispatcher_glib.cpp.
 {
 #ifndef QT_NO_DEBUG
     if (timerId < 1) {
         qWarning("QEventDispatcherGlib::unregisterTimer: invalid argument");
         return false;
     } else if (thread() != QThread::currentThread()) {
         qWarning("QObject::killTimer: timers cannot be stopped from another thread");
         return false;
     }
 #endif
     Q_D(QEventDispatcherGlib);
     return d->timerSource->timerList.unregisterTimer(timerId);
 }
unregisterTimers()
bool QEventDispatcherGlib::unregisterTimers (QObject * object) virtual
Unregisters all the timers associated with the given object.
Returns true if all timers were successful removed; otherwise returns false.
See also
unregisterTimer(), registeredTimers()
Implements QAbstractEventDispatcher.
Definition at line 545 of file qeventdispatcher_glib.cpp.
 {
 #ifndef QT_NO_DEBUG
     if (!object) {
         qWarning("QEventDispatcherGlib::unregisterTimers: invalid argument");
         return false;
     } else if (object->thread() != thread() || thread() != QThread::currentThread()) {
         qWarning("QObject::killTimers: timers cannot be stopped from another thread");
         return false;
     }
 #endif
     Q_D(QEventDispatcherGlib);
     return d->timerSource->timerList.unregisterTimers(object);
 }
versionSupported()
bool QEventDispatcherGlib::versionSupported () static
Definition at line 588 of file qeventdispatcher_glib.cpp.
Referenced by QCoreApplicationPrivate::createEventDispatcher(), QThreadPrivate::createEventDispatcher(), QETWidget::doDeferredMap(), and QETWidget::raiseOnClick().
 {
 #if !defined(GLIB_MAJOR_VERSION) || !defined(GLIB_MINOR_VERSION) || !defined(GLIB_MICRO_VERSION)
     return false;
 #else
     return ((GLIB_MAJOR_VERSION << 16) + (GLIB_MINOR_VERSION << 8) + GLIB_MICRO_VERSION) >= 0x020301;
 #endif
 }
wakeUp()
void QEventDispatcherGlib::wakeUp () virtual
Wakes up the event loop.
Note
This class or function is threadsafe.
See also
awake()
Implements QAbstractEventDispatcher.
Definition at line 577 of file qeventdispatcher_glib.cpp.
Referenced by interrupt().
 {
     Q_D(QEventDispatcherGlib);
     d->postEventSource->serialNumber.ref();
     g_main_context_wakeup(d->mainContext);
 }
The documentation for this class was generated from the following files:
/src/corelib/kernel/qeventdispatcher_glib_p.h
/src/corelib/kernel/qeventdispatcher_glib.cpp