Qt 4.8: QDeclarativePathViewPrivate Class Reference
QDeclarativePathViewPrivate Class Reference
#include <qdeclarativepathview_p_p.h>
Public Types
enum MovementDirection { Shortest, Negative, Positive }
enum MovementReason { Other, SetIndex, Mouse }
Public Types inherited from QDeclarativeItemPrivate
enum ChangeType {
Geometry = 0x01, SiblingOrder = 0x02, Visibility = 0x04, Opacity = 0x08,
Destroyed = 0x10
}
Public Types inherited from QGraphicsItemPrivate
enum AncestorFlag {
NoFlag = 0, AncestorHandlesChildEvents = 0x1, AncestorClipsChildren = 0x2, AncestorIgnoresTransformations = 0x4,
AncestorFiltersChildEvents = 0x8
}
enum Extra {
ExtraToolTip, ExtraCursor, ExtraCacheData, ExtraMaxDeviceCoordCacheSize,
ExtraBoundingRegionGranularity
}
enum InvalidateReason { OpacityChanged }
Public Functions
QDeclarativePathViewAttached * attached (QDeclarativeItem *item)
int calcCurrentIndex ()
void clear ()
void createHighlight ()
void fixOffset ()
QDeclarativeItem * getItem (int modelIndex)
void handleMouseMoveEvent (QGraphicsSceneMouseEvent *event)
void handleMousePressEvent (QGraphicsSceneMouseEvent *event)
void handleMouseReleaseEvent (QGraphicsSceneMouseEvent *)
void init ()
bool isValid () const
void itemGeometryChanged (QDeclarativeItem *item, const QRectF &newGeometry, const QRectF &oldGeometry)
QPointF pointNear (const QPointF &point, qreal *nearPercent=0) const
qreal positionOfIndex (qreal index) const
QDeclarativePathViewPrivate ()
void regenerate ()
void releaseItem (QDeclarativeItem *item)
void scheduleLayout ()
void setAdjustedOffset (qreal offset)
void setHighlightPosition (qreal pos)
void setOffset (qreal offset)
void snapToCurrent ()
void updateCurrent ()
void updateHighlight ()
void updateItem (QDeclarativeItem *, qreal)
void updateMappedRange ()
Public Functions inherited from QDeclarativeItemPrivate
QDeclarativeStateGroup * _states ()
void addItemChangeListener (QDeclarativeItemChangeListener *listener, ChangeTypes types)
AnchorLines * anchorLines () const
QDeclarativeAnchors * anchors ()
QDeclarativeAnchorLine baseline () const
QDeclarativeAnchorLine bottom () const
QPointF computeTransformOrigin () const
QDeclarativeListProperty< QObject > data ()
virtual void focusChanged (bool)
virtual void focusScopeItemChange (bool isSubFocusItem)
Subclasses can reimplement this function to be notified when an item becomes a focusScopeItem (or is no longer a focusScopeItem).
qreal height () const
QDeclarativeAnchorLine horizontalCenter () const
virtual qreal implicitHeight () const
virtual void implicitHeightChanged ()
virtual qreal implicitWidth () const
virtual void implicitWidthChanged ()
void init (QDeclarativeItem *parent)
bool isMirrored () const
QDeclarativeAnchorLine left () const
virtual void mirrorChange ()
QDeclarativeItemPrivate ()
void removeItemChangeListener (QDeclarativeItemChangeListener *, ChangeTypes types)
void resetHeight ()
void resetWidth ()
void resolveLayoutMirror ()
QDeclarativeListProperty< QObject > resources ()
QDeclarativeAnchorLine right () const
void setHeight (qreal)
void setImplicitLayoutMirror (bool mirror, bool inherit)
void setLayoutMirror (bool mirror)
virtual void setPosHelper (const QPointF &pos)
Sets the position pos.
void setState (const QString &)
void setWidth (qreal)
virtual void siblingOrderChange ()
Subclasses can reimplement this function to be notified when its siblingIndex order is changed.
QString state () const
QDeclarativeListProperty< QDeclarativeState > states ()
QDeclarativeAnchorLine top () const
virtual void transformChanged ()
QDeclarativeListProperty< QDeclarativeTransition > transitions ()
QDeclarativeAnchorLine verticalCenter () const
qreal width () const
Public Functions inherited from QGraphicsItemPrivate
void addChild (QGraphicsItem *child)
QGraphicsScenePrivate::registerTopLevelItem().
void appendGraphicsTransform (QGraphicsTransform *t)
qreal calcEffectiveOpacity () const
void childrenBoundingRectHelper (QTransform *x, QRectF *rect, QGraphicsItem *topMostEffectItem)
Returns the bounding rect of this item's children (excluding itself).
bool childrenClippedToShape () const
bool childrenCombineOpacity () const
QDeclarativeListProperty< QGraphicsObject > childrenList ()
Returns a list of this item's children.
void clearFocusHelper (bool giveFocusToParent)
void clearSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
qreal combineOpacityFromParent (qreal parentOpacity) const
void combineTransformFromParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
void combineTransformToParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
int depth () const
bool discardUpdateRequest (bool ignoreVisibleBit=false, bool ignoreDirtyBit=false, bool ignoreOpacity=false) const
Returns true if we can discard an update request; otherwise false.
QRectF effectiveBoundingRect (QGraphicsItem *topMostEffectItem=0) const
Returns the effective bounding rect of the item.
QRectF effectiveBoundingRect (const QRectF &rect) const
Returns the effective bounding rect of the given item space rect.
qreal effectiveOpacity () const
void ensureSceneTransform ()
void ensureSceneTransformRecursive (QGraphicsItem **topMostDirtyItem)
void ensureSequentialSiblingIndex ()
Ensures that the list of children is sorted by insertion order, and that the siblingIndexes are packed (no gaps), and start at 0.
void ensureSortedChildren ()
QVariant extra (Extra type) const
QGraphicsItemCache * extraItemCache () const
QPointF genericMapFromScene (const QPointF &pos, const QWidget *viewport) const
Maps the point pos from scene to item coordinates.
bool hasTranslateOnlySceneTransform ()
void initStyleOption (QStyleOptionGraphicsItem *option, const QTransform &worldTransform, const QRegion &exposedRegion, bool allItems=false) const
virtual QVariant inputMethodQueryHelper (Qt::InputMethodQuery query) const
This helper function helped us add input method query support in Qt 4.
void invalidateChildGraphicsEffectsRecursively (InvalidateReason reason)
void invalidateChildrenSceneTransform ()
void invalidateDepthRecursively ()
void invalidateParentGraphicsEffectsRecursively ()
bool isFullyTransparent () const
bool isInvisible () const
bool isOpacityNull () const
virtual bool isProxyWidget () const
bool itemIsUntransformable () const
void markParentDirty (bool updateBoundingRect=false)
QGraphicsItemCache * maybeExtraItemCache () const
void prependGraphicsTransform (QGraphicsTransform *t)
QGraphicsItemPrivate ()
void remapItemPos (QEvent *event, QGraphicsItem *item)
Maps any item pos properties of event to item's coordinate system.
void removeChild (QGraphicsItem *child)
QGraphicsScenePrivate::unregisterTopLevelItem().
void removeExtraItemCache ()
void resetFocusProxy ()
Sets the focusProxy pointer to 0 for all items that have this item as their focusProxy.
void resolveDepth ()
Resolves the stacking depth of this object and all its ancestors.
virtual void resolveFont (uint inheritedMask)
virtual void resolvePalette (uint inheritedMask)
QRectF sceneEffectiveBoundingRect () const
Returns the effective bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect(), taking into account the effect that the item might have.
void sendScenePosChange ()
void setEnabledHelper (bool newEnabled, bool explicitly, bool update=true)
Sets this item's visibility to newEnabled.
void setExtra (Extra type, const QVariant &value)
void setFocusHelper (Qt::FocusReason focusReason, bool climb, bool focusFromHide)
void setIsMemberOfGroup (bool enabled)
Propagates item group membership.
void setParentItemHelper (QGraphicsItem *parent, const QVariant *newParentVariant, const QVariant *thisPointerVariant)
Make sure not to trigger any pure virtual function calls (e.
void setSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
void setTransformHelper (const QTransform &transform)
Sets the transform transform.
void setVisibleHelper (bool newVisible, bool explicitly, bool update=true)
Sets this item's visibility to newVisible.
virtual void subFocusItemChange ()
Subclasses can reimplement this function to be notified when subFocusItem changes.
QTransform transformToParent () const
void unsetExtra (Extra type)
void updateAncestorFlag (QGraphicsItem::GraphicsItemFlag childFlag, AncestorFlag flag=NoFlag, bool enabled=false, bool root=true)
Propagates the ancestor flag flag with value enabled to all this item's children.
void updateAncestorFlags ()
void updateChildWithGraphicsEffectFlagRecursively ()
void updatePaintedViewBoundingRects (bool updateChildren)
virtual void updateSceneTransformFromParent ()
virtual ~QGraphicsItemPrivate ()
Public Functions inherited from QDeclarativeItemChangeListener
virtual QDeclarativeAnchorsPrivate * anchorPrivate ()
virtual void itemDestroyed (QDeclarativeItem *)
virtual void itemOpacityChanged (QDeclarativeItem *)
virtual void itemSiblingOrderChanged (QDeclarativeItem *)
virtual void itemVisibilityChanged (QDeclarativeItem *)
Static Public Functions
static void fixOffsetCallback (void *)
Static Public Functions inherited from QDeclarativeItemPrivate
static void data_append (QDeclarativeListProperty< QObject > *, QObject *)
static QObject * data_at (QDeclarativeListProperty< QObject > *, int)
static void data_clear (QDeclarativeListProperty< QObject > *)
static int data_count (QDeclarativeListProperty< QObject > *)
static qint64 elapsed (QElapsedTimer &)
static QDeclarativeItemPrivate * get (QDeclarativeItem *item)
static void parentProperty (QObject *o, void *rv, QDeclarativeNotifierEndpoint *e)
static void resources_append (QDeclarativeListProperty< QObject > *, QObject *)
static QObject * resources_at (QDeclarativeListProperty< QObject > *, int)
static void resources_clear (QDeclarativeListProperty< QObject > *)
static int resources_count (QDeclarativeListProperty< QObject > *)
static qint64 restart (QElapsedTimer &)
static void setConsistentTime (qint64 t)
static void start (QElapsedTimer &)
static void transform_append (QDeclarativeListProperty< QGraphicsTransform > *list, QGraphicsTransform *)
static QGraphicsTransform * transform_at (QDeclarativeListProperty< QGraphicsTransform > *list, int)
static void transform_clear (QDeclarativeListProperty< QGraphicsTransform > *list)
static int transform_count (QDeclarativeListProperty< QGraphicsTransform > *list)
Static Public Functions inherited from QGraphicsItemPrivate
static void children_append (QDeclarativeListProperty< QGraphicsObject > *list, QGraphicsObject *item)
static QGraphicsObject * children_at (QDeclarativeListProperty< QGraphicsObject > *list, int)
static void children_clear (QDeclarativeListProperty< QGraphicsObject > *list)
static int children_count (QDeclarativeListProperty< QGraphicsObject > *list)
static const QGraphicsItemPrivate * get (const QGraphicsItem *item)
static QGraphicsItemPrivate * get (QGraphicsItem *item)
static bool insertionOrder (QGraphicsItem *a, QGraphicsItem *b)
static bool isOpacityNull (qreal opacity)
static bool movableAncestorIsSelected (const QGraphicsItem *item)
Public Variables
QDeclarativeOpenMetaObjectType * attType
bool autoHighlight: 1
int currentIndex
QDeclarativeGuard< QDeclarativeItem > currentItem
qreal currentItemOffset
qreal deceleration
qreal dragMargin
int firstIndex
bool flicking: 1
bool haveHighlightRange: 1
QDeclarativeComponent * highlightComponent
QDeclarativeItem * highlightItem
int highlightMoveDuration
qreal highlightPosition
qreal highlightRangeEnd
QDeclarativePathView::HighlightRangeMode highlightRangeMode
qreal highlightRangeStart
bool highlightUp: 1
bool interactive: 1
QList< QDeclarativeItem * > itemCache
QList< QDeclarativeItem * > items
qreal lastDist
int lastElapsed
QPointF lastPos
QElapsedTimer lastPosTime
bool layoutScheduled: 1
qreal mappedRange
QDeclarativeGuard< QDeclarativeVisualModel > model
int modelCount
QVariant modelVariant
MovementDirection moveDirection
QDeclarativeTimeLineValueProxy< QDeclarativePathViewPrivate > moveHighlight
QDeclarativeTimeLineValueProxy< QDeclarativePathViewPrivate > moveOffset
MovementReason moveReason
bool moving: 1
qreal offset
qreal offsetAdj
bool ownModel: 1
QDeclarativePath * path
int pathItems
int requestedIndex
qreal startPc
QPointF startPoint
bool stealMouse: 1
QDeclarativeTimeLine tl
Public Variables inherited from QDeclarativeItemPrivate
AnchorLines * _anchorLines
QDeclarativeAnchors * _anchors
QDeclarativeContents * _contents
QDeclarativeStateGroup * _stateGroup
QDeclarativeLayoutMirroringAttached * attachedLayoutDirection
QDeclarativeNullableValue< qreal > baselineOffset
QPODVector< ChangeListener, 4 > changeListeners
bool componentComplete:1
bool doneEventPreHandler: 1
bool effectiveLayoutMirror:1
bool hadActiveFocus:1
bool hadFocus:1
bool heightValid:1
bool inheritedLayoutMirror:1
bool inheritMirrorFromItem:1
bool inheritMirrorFromParent:1
bool isMirrorImplicit:1
bool keepMouse:1
QDeclarativeItemKeyFilter * keyHandler
qreal mHeight
qreal mImplicitHeight
qreal mImplicitWidth
qreal mWidth
QDeclarativeItem::TransformOrigin origin:5
QDeclarativeNotifier parentNotifier
bool smooth:1
bool transformOriginDirty: 1
bool widthValid:1
Public Variables inherited from QGraphicsItemPrivate
quint32 acceptDrops: 1
quint32 acceptedMouseButtons: 5
quint32 acceptedTouchBeginEvent: 1
quint32 acceptsHover: 1
quint32 acceptTouchEvents: 1
quint32 allChildrenDirty: 1
quint32 ancestorFlags: 4
quint32 cacheMode: 2
QList< QGraphicsItem * > children
QRectF childrenBoundingRect
quint32 dirty: 1
quint32 dirtyChildren: 1
quint32 dirtyChildrenBoundingRect: 1
quint32 dirtySceneTransform: 1
quint32 enabled: 1
quint32 explicitActivate: 1
quint32 explicitlyDisabled: 1
quint32 explicitlyHidden: 1
QList< ExtraStruct > extras
quint32 filtersDescendantEvents: 1
quint32 flags: 19
QGraphicsItem * focusProxy
QList< QGraphicsItem ** > focusProxyRefs
QGraphicsItem * focusScopeItem
quint32 fullUpdatePending: 1
quint32 geometryChanged: 1
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
int globalStackingOrder
QGraphicsEffect * graphicsEffect
quint32 handlesChildEvents: 1
quint32 hasBoundingRegionGranularity: 1
quint32 hasCursor: 1
quint32 holesInSiblingIndex: 1
quint32 ignoreOpacity: 1
quint32 ignoreVisible: 1
Qt::InputMethodHints imHints
quint32 inDestructor: 1
int index
quint32 inSetPosHelper: 1
quint32 isDeclarativeItem: 1
quint32 isMemberOfGroup: 1
quint32 isObject: 1
quint32 isWidget: 1
int itemDepth
quint32 itemDiscovered: 1
quint32 localCollisionHack: 1
quint32 mayHaveChildWithGraphicsEffect: 1
quint32 mouseSetsFocus: 1
quint32 needSortChildren: 1
QRectF needsRepaint
quint32 notifyBoundingRectChanged: 1
quint32 notifyInvalidated: 1
qreal opacity
quint32 padding: 21
QMap< QWidget *, QRect > paintedViewBoundingRects
quint32 paintedViewBoundingRectsNeedRepaint: 1
QGraphicsItem::PanelModality panelModality
QGraphicsItem * parent
quint32 pendingPolish: 1
QPointF pos
QGraphicsItem * q_ptr
QGraphicsScene * scene
quint32 scenePosDescendants: 1
QTransform sceneTransform
quint32 sceneTransformTranslateOnly: 1
quint32 selected: 1
quint32 sendParentChangeNotification: 1
quint32 sequentialOrdering: 1
int siblingIndex
QGraphicsItem * subFocusItem
TransformData * transformData
quint32 updateDueToGraphicsEffect: 1
quint32 visible: 1
quint32 wantsActive: 1
qreal z
Additional Inherited Members
Static Public Variables inherited from QDeclarativeItemPrivate
static qint64 consistentTime = -1
Detailed Description
Definition at line 71 of file qdeclarativepathview_p_p.h.
Enumerations
MovementDirection
enum QDeclarativePathViewPrivate::MovementDirection
Enumerator
Shortest
Negative
Positive
Definition at line 176 of file qdeclarativepathview_p_p.h.
 { Shortest, Negative, Positive };
MovementReason
enum QDeclarativePathViewPrivate::MovementReason
Enumerator
Other
SetIndex
Mouse
Definition at line 174 of file qdeclarativepathview_p_p.h.
 { Other, SetIndex, Mouse };
Constructors and Destructors
QDeclarativePathViewPrivate()
QDeclarativePathViewPrivate::QDeclarativePathViewPrivate () inline
Definition at line 76 of file qdeclarativepathview_p_p.h.
       : path(0), currentIndex(0), currentItemOffset(0.0), startPc(0), lastDist(0)
         , lastElapsed(0), offset(0.0), offsetAdj(0.0), mappedRange(1.0)
         , stealMouse(false), ownModel(false), interactive(true), haveHighlightRange(true)
         , autoHighlight(true), highlightUp(false), layoutScheduled(false)
         , moving(false), flicking(false)
         , dragMargin(0), deceleration(100)
         , moveOffset(this, &QDeclarativePathViewPrivate::setAdjustedOffset)
         , firstIndex(-1), pathItems(-1), requestedIndex(-1)
         , moveReason(Other), moveDirection(Shortest), attType(0), highlightComponent(0), highlightItem(0)
         , moveHighlight(this, &QDeclarativePathViewPrivate::setHighlightPosition)
         , highlightPosition(0)
         , highlightRangeStart(0), highlightRangeEnd(0)
         , highlightRangeMode(QDeclarativePathView::StrictlyEnforceRange)
         , highlightMoveDuration(300), modelCount(0)
     {
     }
Functions
attached()
QDeclarativePathViewAttached * QDeclarativePathViewPrivate::attached (QDeclarativeItem * item)
Definition at line 153 of file qdeclarativepathview.cpp.
Referenced by itemGeometryChanged(), and scheduleLayout().
 {
     return static_cast<QDeclarativePathViewAttached *>(qmlAttachedPropertiesObject<QDeclarativePathView>(item, false));
 }
calcCurrentIndex()
int QDeclarativePathViewPrivate::calcCurrentIndex ()
Definition at line 1716 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     int current = 0;
     if (modelCount && model && items.count()) {
         offset = qmlMod(offset, modelCount);
         if (offset < 0)
             offset += modelCount;
         current = qRound(qAbs(qmlMod(modelCount - offset, modelCount)));
         current = current % modelCount;
     }
     return current;
 }
clear()
void QDeclarativePathViewPrivate::clear ()
Definition at line 158 of file qdeclarativepathview.cpp.
Referenced by scheduleLayout().
 {
     for (int i=0; i<items.count(); i++){
         QDeclarativeItem *p = items[i];
         releaseItem(p);
     }
     items.clear();
     tl.clear();
 }
createHighlight()
void QDeclarativePathViewPrivate::createHighlight ()
Definition at line 199 of file qdeclarativepathview.cpp.
Referenced by scheduleLayout().
 {
     Q_Q(QDeclarativePathView);
     if (!q->isComponentComplete())
         return;
     bool changed = false;
     if (highlightItem) {
         if (highlightItem->scene())
             highlightItem->scene()->removeItem(highlightItem);
         highlightItem->deleteLater();
         highlightItem = 0;
         changed = true;
     }
     QDeclarativeItem *item = 0;
     if (highlightComponent) {
         QDeclarativeContext *highlightContext = new QDeclarativeContext(qmlContext(q));
         QObject *nobj = highlightComponent->create(highlightContext);
         if (nobj) {
             QDeclarative_setParent_noEvent(highlightContext, nobj);
             item = qobject_cast<QDeclarativeItem *>(nobj);
             if (!item)
                 delete nobj;
         } else {
             delete highlightContext;
         }
     } else {
         item = new QDeclarativeItem;
     }
     if (item) {
         QDeclarative_setParent_noEvent(item, q);
         item->setParentItem(q);
         highlightItem = item;
         changed = true;
     }
     if (changed)
         emit q->highlightItemChanged();
 }
fixOffset()
void QDeclarativePathViewPrivate::fixOffset ()
Definition at line 1767 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     Q_Q(QDeclarativePathView);
     if (model && items.count()) {
         if (haveHighlightRange && highlightRangeMode == QDeclarativePathView::StrictlyEnforceRange) {
             int curr = calcCurrentIndex();
             if (curr != currentIndex)
                 q->setCurrentIndex(curr);
             else
                 snapToCurrent();
         }
     }
 }
fixOffsetCallback()
void QDeclarativePathViewPrivate::fixOffsetCallback (void * d) static
Definition at line 1762 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     ((QDeclarativePathViewPrivate *)d)->fixOffset();
 }
getItem()
QDeclarativeItem * QDeclarativePathViewPrivate::getItem (int modelIndex)
Definition at line 113 of file qdeclarativepathview.cpp.
Referenced by scheduleLayout().
 {
     Q_Q(QDeclarativePathView);
     requestedIndex = modelIndex;
     QDeclarativeItem *item = model->item(modelIndex, false);
     if (item) {
         if (!attType) {
             // pre-create one metatype to share with all attached objects
             attType = new QDeclarativeOpenMetaObjectType(&QDeclarativePathViewAttached::staticMetaObject, qmlEngine(q));
             foreach(const QString &attr, path->attributes())
                 attType->createProperty(attr.toUtf8());
         }
         qPathViewAttachedType = attType;
         QDeclarativePathViewAttached *att = static_cast<QDeclarativePathViewAttached *>(qmlAttachedPropertiesObject<QDeclarativePathView>(item));
         qPathViewAttachedType = 0;
         if (att) {
             att->m_view = q;
             att->setOnPath(true);
         }
         item->setParentItem(q);
         QDeclarativeItemPrivate *itemPrivate = static_cast<QDeclarativeItemPrivate*>(QGraphicsItemPrivate::get(item));
         itemPrivate->addItemChangeListener(this, QDeclarativeItemPrivate::Geometry);
     }
     requestedIndex = -1;
     return item;
 }
handleMouseMoveEvent()
void QDeclarativePathViewPrivate::handleMouseMoveEvent (QGraphicsSceneMouseEvent * event)
Definition at line 1227 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     Q_Q(QDeclarativePathView);
     if (!interactive || !lastPosTime.isValid())
         return;
     qreal newPc;
     QPointF pathPoint = pointNear(event->pos(), &newPc);
     if (!stealMouse) {
         QPointF delta = pathPoint - startPoint;
         if (qAbs(delta.x()) > QApplication::startDragDistance() || qAbs(delta.y()) > QApplication::startDragDistance()) {
             stealMouse = true;
             startPc = newPc;
         }
     }
     if (stealMouse) {
         moveReason = QDeclarativePathViewPrivate::Mouse;
         qreal diff = (newPc - startPc)*modelCount*mappedRange;
         if (diff) {
             q->setOffset(offset + diff);
             if (diff > modelCount/2)
                 diff -= modelCount;
             else if (diff < -modelCount/2)
                 diff += modelCount;
             lastElapsed = QDeclarativeItemPrivate::restart(lastPosTime);
             lastDist = diff;
             startPc = newPc;
         }
         if (!moving) {
             moving = true;
             emit q->movingChanged();
             emit q->movementStarted();
         }
     }
 }
handleMousePressEvent()
void QDeclarativePathViewPrivate::handleMousePressEvent (QGraphicsSceneMouseEvent * event)
Definition at line 1180 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     Q_Q(QDeclarativePathView);
     if (!interactive || !items.count())
         return;
     QPointF scenePoint = q->mapToScene(event->pos());
     int idx = 0;
     for (; idx < items.count(); ++idx) {
         QRectF rect = items.at(idx)->boundingRect();
         rect = items.at(idx)->mapToScene(rect).boundingRect();
         if (rect.contains(scenePoint))
             break;
     }
     if (idx == items.count() && dragMargin == 0.)  // didn't click on an item
         return;
     startPoint = pointNear(event->pos(), &startPc);
     if (idx == items.count()) {
         qreal distance = qAbs(event->pos().x() - startPoint.x()) + qAbs(event->pos().y() - startPoint.y());
         if (distance > dragMargin)
             return;
     }
     if (tl.isActive() && flicking)
         stealMouse = true; // If we've been flicked then steal the click.
     else
         stealMouse = false;
     lastElapsed = 0;
     lastDist = 0;
     QDeclarativeItemPrivate::start(lastPosTime);
     tl.clear();
 }
handleMouseReleaseEvent()
void QDeclarativePathViewPrivate::handleMouseReleaseEvent (QGraphicsSceneMouseEvent *)
Definition at line 1278 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     Q_Q(QDeclarativePathView);
     stealMouse = false;
     q->setKeepMouseGrab(false);
     if (!interactive || !lastPosTime.isValid())
         return;
     qreal elapsed = qreal(lastElapsed + QDeclarativeItemPrivate::elapsed(lastPosTime)) / 1000.;
     qreal velocity = elapsed > 0. ? lastDist / elapsed : 0;
     if (model && modelCount && qAbs(velocity) > qreal(1.)) {
         qreal count = pathItems == -1 ? modelCount : pathItems;
         if (qAbs(velocity) > count * 2) // limit velocity
             velocity = (velocity > 0 ? count : -count) * 2;
         // Calculate the distance to be travelled
         qreal v2 = velocity*velocity;
         qreal accel = deceleration/10;
         // + 0.25 to encourage moving at least one item in the flick direction
         qreal dist = qMin(qreal(modelCount-1), qreal(v2 / (accel * qreal(2.0)) + qreal(0.25)));
         if (haveHighlightRange && highlightRangeMode == QDeclarativePathView::StrictlyEnforceRange) {
             // round to nearest item.
             if (velocity > 0.)
                 dist = qRound(dist + offset) - offset;
             else
                 dist = qRound(dist - offset) + offset;
             // Calculate accel required to stop on item boundary
             if (dist <= 0.) {
                 dist = qreal(0.);
                 accel = qreal(0.);
             } else {
                 accel = v2 / (2.0f * qAbs(dist));
             }
         }
         offsetAdj = qreal(0.0);
         moveOffset.setValue(offset);
         tl.accel(moveOffset, velocity, accel, dist);
         tl.callback(QDeclarativeTimeLineCallback(&moveOffset, fixOffsetCallback, this));
         if (!flicking) {
             flicking = true;
             emit q->flickingChanged();
             emit q->flickStarted();
         }
     } else {
         fixOffset();
     }
     lastPosTime.invalidate();
     if (!tl.isActive())
         q->movementEnding();
 }
init()
void QDeclarativePathViewPrivate::init ()
Definition at line 94 of file qdeclarativepathview.cpp.
Referenced by QDeclarativePathViewPrivate().
 {
     Q_Q(QDeclarativePathView);
     offset = 0;
     q->setAcceptedMouseButtons(Qt::LeftButton);
     q->setFlag(QGraphicsItem::ItemIsFocusScope);
     q->setFiltersChildEvents(true);
     q->connect(&tl, SIGNAL(updated()), q, SLOT(ticked()));
     lastPosTime.invalidate();
     static int timelineCompletedIdx = -1;
     static int movementEndingIdx = -1;
     if (timelineCompletedIdx == -1) {
         timelineCompletedIdx = QDeclarativeTimeLine::staticMetaObject.indexOfSignal("completed()");
         movementEndingIdx = QDeclarativePathView::staticMetaObject.indexOfSlot("movementEnding()");
     }
     QMetaObject::connect(&tl, timelineCompletedIdx,
                          q, movementEndingIdx, Qt::DirectConnection);
 }
isValid()
bool QDeclarativePathViewPrivate::isValid () const inline
Definition at line 122 of file qdeclarativepathview_p_p.h.
{
         return model && model->count() > 0 && model->isValid() && path;
     }
itemGeometryChanged()
void QDeclarativePathViewPrivate::itemGeometryChanged (QDeclarativeItem * item, const QRectF & newGeometry, const QRectF & oldGeometry) inline virtual
Reimplemented from QDeclarativeItemChangeListener.
Definition at line 96 of file qdeclarativepathview_p_p.h.
{
         if ((newGeometry.size() != oldGeometry.size())
             && (!highlightItem || item != highlightItem)) {
             if (QDeclarativePathViewAttached *att = attached(item))
                 att->m_percent = -1;
             scheduleLayout();
         }
     }
pointNear()
QPointF QDeclarativePathViewPrivate::pointNear (const QPointF & point, qreal * nearPercent = 0) const
Definition at line 1146 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     //XXX maybe do recursively at increasing resolution.
     qreal mindist = 1e10; // big number
     QPointF nearPoint = path->pointAt(0);
     qreal nearPc = 0;
     for (qreal i=1; i < 1000; i++) {
         QPointF pt = path->pointAt(i/1000.0);
         QPointF diff = pt - point;
         qreal dist = diff.x()*diff.x() + diff.y()*diff.y();
         if (dist < mindist) {
             nearPoint = pt;
             nearPc = i;
             mindist = dist;
         }
     }
     if (nearPercent)
         *nearPercent = nearPc / 1000.0;
     return nearPoint;
 }
positionOfIndex()
qreal QDeclarativePathViewPrivate::positionOfIndex (qreal index) const
Definition at line 176 of file qdeclarativepathview.cpp.
Referenced by scheduleLayout().
 {
     qreal pos = -1.0;
     if (model && index >= 0 && index < modelCount) {
         qreal start = 0.0;
         if (haveHighlightRange && highlightRangeMode != QDeclarativePathView::NoHighlightRange)
             start = highlightRangeStart;
         qreal globalPos = index + offset;
         globalPos = qmlMod(globalPos, qreal(modelCount)) / modelCount;
         if (pathItems != -1 && pathItems < modelCount) {
             globalPos += start * mappedRange;
             globalPos = qmlMod(globalPos, 1.0);
             if (globalPos < mappedRange)
                 pos = globalPos / mappedRange;
         } else {
             pos = qmlMod(globalPos + start, 1.0);
         }
     }
     return pos;
 }
regenerate()
void QDeclarativePathViewPrivate::regenerate ()
Definition at line 333 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     Q_Q(QDeclarativePathView);
     if (!q->isComponentComplete())
         return;
     clear();
     if (!isValid())
         return;
     firstIndex = -1;
     updateMappedRange();
     q->refill();
 }
releaseItem()
void QDeclarativePathViewPrivate::releaseItem (QDeclarativeItem * item)
Definition at line 140 of file qdeclarativepathview.cpp.
Referenced by scheduleLayout().
 {
     if (!item || !model)
         return;
     QDeclarativeItemPrivate *itemPrivate = static_cast<QDeclarativeItemPrivate*>(QGraphicsItemPrivate::get(item));
     itemPrivate->removeItemChangeListener(this, QDeclarativeItemPrivate::Geometry);
     if (model->release(item) == 0) {
         // item was not destroyed, and we no longer reference it.
         if (QDeclarativePathViewAttached *att = attached(item))
             att->setOnPath(false);
     }
 }
scheduleLayout()
void QDeclarativePathViewPrivate::scheduleLayout () inline
Definition at line 105 of file qdeclarativepathview_p_p.h.
Referenced by itemGeometryChanged().
{
         Q_Q(QDeclarativePathView);
         if (!layoutScheduled) {
             layoutScheduled = true;
             QCoreApplication::postEvent(q, new QEvent(QEvent::User), Qt::HighEventPriority);
         }
     }
setAdjustedOffset()
void QDeclarativePathViewPrivate::setAdjustedOffset (qreal offset)
Definition at line 737 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     setOffset(o+offsetAdj);
 }
setHighlightPosition()
void QDeclarativePathViewPrivate::setHighlightPosition (qreal pos)
Definition at line 276 of file qdeclarativepathview.cpp.
Referenced by scheduleLayout().
 {
     if (pos != highlightPosition) {
         qreal start = 0.0;
         qreal end = 1.0;
         if (haveHighlightRange && highlightRangeMode != QDeclarativePathView::NoHighlightRange) {
             start = highlightRangeStart;
             end = highlightRangeEnd;
         }
         qreal range = qreal(modelCount);
         // calc normalized position of highlight relative to offset
         qreal relativeHighlight = qmlMod(pos + offset, range) / range;
         if (!highlightUp && relativeHighlight > end * mappedRange) {
             qreal diff = qreal(1.0) - relativeHighlight;
             setOffset(offset + diff * range);
         } else if (highlightUp && relativeHighlight >= (end - start) * mappedRange) {
             qreal diff = relativeHighlight - (end - start) * mappedRange;
             setOffset(offset - diff * range - qreal(0.00001));
         }
         highlightPosition = pos;
         qreal pathPos = positionOfIndex(pos);
         updateItem(highlightItem, pathPos);
         if (QDeclarativePathViewAttached *att = attached(highlightItem))
             att->setOnPath(pathPos != qreal(-1.0));
     }
 }
setOffset()
void QDeclarativePathViewPrivate::setOffset (qreal offset)
Definition at line 721 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     Q_Q(QDeclarativePathView);
     if (offset != o) {
         if (isValid() && q->isComponentComplete()) {
             offset = qmlMod(o, qreal(modelCount));
             if (offset < 0)
                 offset += qreal(modelCount);
             q->refill();
         } else {
             offset = o;
         }
         emit q->offsetChanged();
     }
 }
snapToCurrent()
void QDeclarativePathViewPrivate::snapToCurrent ()
Definition at line 1781 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     if (!model || modelCount <= 0)
         return;
     qreal targetOffset = qmlMod(modelCount - currentIndex, modelCount);
     moveReason = Other;
     offsetAdj = 0.0;
     tl.reset(moveOffset);
     moveOffset.setValue(offset);
     const int duration = highlightMoveDuration;
     if (moveDirection == Positive || (moveDirection == Shortest && targetOffset - offset > modelCount/2)) {
         qreal distance = modelCount - targetOffset + offset;
         if (targetOffset > moveOffset) {
             tl.move(moveOffset, 0.0, QEasingCurve(QEasingCurve::InQuad), int(duration * offset / distance));
             tl.set(moveOffset, modelCount);
             tl.move(moveOffset, targetOffset, QEasingCurve(offset == 0.0 ? QEasingCurve::InOutQuad : QEasingCurve::OutQuad), int(duration * (modelCount-targetOffset) / distance));
         } else {
             tl.move(moveOffset, targetOffset, QEasingCurve(QEasingCurve::InOutQuad), duration);
         }
     } else if (moveDirection == Negative || targetOffset - offset <= -modelCount/2) {
         qreal distance = modelCount - offset + targetOffset;
         if (targetOffset < moveOffset) {
             tl.move(moveOffset, modelCount, QEasingCurve(targetOffset == 0 ? QEasingCurve::InOutQuad : QEasingCurve::InQuad), int(duration * (modelCount-offset) / distance));
             tl.set(moveOffset, 0.0);
             tl.move(moveOffset, targetOffset, QEasingCurve(QEasingCurve::OutQuad), int(duration * targetOffset / distance));
         } else {
             tl.move(moveOffset, targetOffset, QEasingCurve(QEasingCurve::InOutQuad), duration);
         }
     } else {
         tl.move(moveOffset, targetOffset, QEasingCurve(QEasingCurve::InOutQuad), duration);
     }
     moveDirection = Shortest;
 }
updateCurrent()
void QDeclarativePathViewPrivate::updateCurrent ()
Definition at line 1730 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     Q_Q(QDeclarativePathView);
     if (moveReason != Mouse)
         return;
     if (!modelCount || !haveHighlightRange || highlightRangeMode != QDeclarativePathView::StrictlyEnforceRange)
         return;
     int idx = calcCurrentIndex();
     if (model && (idx != currentIndex || !currentItem)) {
         int itemIndex = (currentIndex - firstIndex + modelCount) % modelCount;
         if (itemIndex < items.count()) {
             if (QDeclarativeItem *item = items.at(itemIndex)) {
                 if (QDeclarativePathViewAttached *att = attached(item))
                     att->setIsCurrentItem(false);
             }
         }
         int oldCurrentIndex = currentIndex;
         currentIndex = idx;
         currentItem = 0;
         itemIndex = (idx - firstIndex + modelCount) % modelCount;
         if (itemIndex < items.count()) {
             currentItem = items.at(itemIndex);
             currentItem->setFocus(true);
             if (QDeclarativePathViewAttached *att = attached(currentItem))
                 att->setIsCurrentItem(true);
         }
         if (oldCurrentIndex != currentIndex)
             emit q->currentIndexChanged();
     }
 }
updateHighlight()
void QDeclarativePathViewPrivate::updateHighlight ()
Definition at line 239 of file qdeclarativepathview.cpp.
Referenced by scheduleLayout().
 {
     Q_Q(QDeclarativePathView);
     if (!q->isComponentComplete() || !isValid())
         return;
     if (highlightItem) {
         if (haveHighlightRange && highlightRangeMode == QDeclarativePathView::StrictlyEnforceRange) {
             updateItem(highlightItem, highlightRangeStart);
         } else {
             qreal target = currentIndex;
             offsetAdj = qreal(0.0);
             tl.reset(moveHighlight);
             moveHighlight.setValue(highlightPosition);
             const int duration = highlightMoveDuration;
             if (target - highlightPosition > modelCount/2) {
                 highlightUp = false;
                 qreal distance = modelCount - target + highlightPosition;
                 tl.move(moveHighlight, qreal(0.0), QEasingCurve(QEasingCurve::InQuad), int(duration * highlightPosition / distance));
                 tl.set(moveHighlight, modelCount-qreal(0.01));
                 tl.move(moveHighlight, target, QEasingCurve(QEasingCurve::OutQuad), int(duration * (modelCount-target) / distance));
             } else if (target - highlightPosition <= -modelCount/2) {
                 highlightUp = true;
                 qreal distance = modelCount - highlightPosition + target;
                 tl.move(moveHighlight, modelCount-qreal(0.01), QEasingCurve(QEasingCurve::InQuad), int(duration * (modelCount-highlightPosition) / distance));
                 tl.set(moveHighlight, qreal(0.0));
                 tl.move(moveHighlight, target, QEasingCurve(QEasingCurve::OutQuad), int(duration * target / distance));
             } else {
                 highlightUp = highlightPosition - target < 0;
                 tl.move(moveHighlight, target, QEasingCurve(QEasingCurve::InOutQuad), duration);
             }
         }
     }
 }
updateItem()
void QDeclarativePathViewPrivate::updateItem (QDeclarativeItem * item, qreal percent)
Definition at line 319 of file qdeclarativepathview.cpp.
Referenced by isValid().
 {
     if (QDeclarativePathViewAttached *att = attached(item)) {
         if (qFuzzyCompare(att->m_percent, percent))
             return;
         att->m_percent = percent;
         foreach(const QString &attr, path->attributes())
             att->setValue(attr.toUtf8(), path->attributeAt(attr, percent));
     }
     QPointF pf = path->pointAt(percent);
     item->setX(qRound(pf.x() - item->width()/2));
     item->setY(qRound(pf.y() - item->height()/2));
 }
updateMappedRange()
void QDeclarativePathViewPrivate::updateMappedRange ()
Definition at line 168 of file qdeclarativepathview.cpp.
Referenced by scheduleLayout().
 {
     if (model && pathItems != -1 && pathItems < modelCount)
         mappedRange = qreal(pathItems)/modelCount;
     else
         mappedRange = 1.0;
 }
Properties
attType
QDeclarativeOpenMetaObjectType* QDeclarativePathViewPrivate::attType
Definition at line 178 of file qdeclarativepathview_p_p.h.
autoHighlight
bool QDeclarativePathViewPrivate::autoHighlight
Definition at line 156 of file qdeclarativepathview_p_p.h.
currentIndex
int QDeclarativePathViewPrivate::currentIndex
Definition at line 142 of file qdeclarativepathview_p_p.h.
currentItem
QDeclarativeGuard<QDeclarativeItem> QDeclarativePathViewPrivate::currentItem
Definition at line 143 of file qdeclarativepathview_p_p.h.
currentItemOffset
qreal QDeclarativePathViewPrivate::currentItemOffset
Definition at line 144 of file qdeclarativepathview_p_p.h.
deceleration
qreal QDeclarativePathViewPrivate::deceleration
Definition at line 164 of file qdeclarativepathview_p_p.h.
dragMargin
qreal QDeclarativePathViewPrivate::dragMargin
Definition at line 163 of file qdeclarativepathview_p_p.h.
firstIndex
int QDeclarativePathViewPrivate::firstIndex
Definition at line 167 of file qdeclarativepathview_p_p.h.
flicking
bool QDeclarativePathViewPrivate::flicking
Definition at line 160 of file qdeclarativepathview_p_p.h.
haveHighlightRange
bool QDeclarativePathViewPrivate::haveHighlightRange
Definition at line 155 of file qdeclarativepathview_p_p.h.
highlightComponent
QDeclarativeComponent* QDeclarativePathViewPrivate::highlightComponent
Definition at line 179 of file qdeclarativepathview_p_p.h.
highlightItem
QDeclarativeItem* QDeclarativePathViewPrivate::highlightItem
Definition at line 180 of file qdeclarativepathview_p_p.h.
Referenced by itemGeometryChanged().
highlightMoveDuration
int QDeclarativePathViewPrivate::highlightMoveDuration
Definition at line 186 of file qdeclarativepathview_p_p.h.
highlightPosition
qreal QDeclarativePathViewPrivate::highlightPosition
Definition at line 182 of file qdeclarativepathview_p_p.h.
highlightRangeEnd
qreal QDeclarativePathViewPrivate::highlightRangeEnd
Definition at line 184 of file qdeclarativepathview_p_p.h.
highlightRangeMode
QDeclarativePathView::HighlightRangeMode QDeclarativePathViewPrivate::highlightRangeMode
Definition at line 185 of file qdeclarativepathview_p_p.h.
highlightRangeStart
qreal QDeclarativePathViewPrivate::highlightRangeStart
Definition at line 183 of file qdeclarativepathview_p_p.h.
highlightUp
bool QDeclarativePathViewPrivate::highlightUp
Definition at line 157 of file qdeclarativepathview_p_p.h.
interactive
bool QDeclarativePathViewPrivate::interactive
Definition at line 154 of file qdeclarativepathview_p_p.h.
itemCache
QList<QDeclarativeItem *> QDeclarativePathViewPrivate::itemCache
Definition at line 171 of file qdeclarativepathview_p_p.h.
items
QList<QDeclarativeItem *> QDeclarativePathViewPrivate::items
Definition at line 170 of file qdeclarativepathview_p_p.h.
lastDist
qreal QDeclarativePathViewPrivate::lastDist
Definition at line 147 of file qdeclarativepathview_p_p.h.
lastElapsed
int QDeclarativePathViewPrivate::lastElapsed
Definition at line 148 of file qdeclarativepathview_p_p.h.
lastPos
QPointF QDeclarativePathViewPrivate::lastPos
Definition at line 162 of file qdeclarativepathview_p_p.h.
lastPosTime
QElapsedTimer QDeclarativePathViewPrivate::lastPosTime
Definition at line 161 of file qdeclarativepathview_p_p.h.
layoutScheduled
bool QDeclarativePathViewPrivate::layoutScheduled
Definition at line 158 of file qdeclarativepathview_p_p.h.
Referenced by scheduleLayout().
mappedRange
qreal QDeclarativePathViewPrivate::mappedRange
Definition at line 151 of file qdeclarativepathview_p_p.h.
model
QDeclarativeGuard<QDeclarativeVisualModel> QDeclarativePathViewPrivate::model
Definition at line 172 of file qdeclarativepathview_p_p.h.
Referenced by isValid().
modelCount
int QDeclarativePathViewPrivate::modelCount
Definition at line 187 of file qdeclarativepathview_p_p.h.
modelVariant
QVariant QDeclarativePathViewPrivate::modelVariant
Definition at line 173 of file qdeclarativepathview_p_p.h.
moveDirection
MovementDirection QDeclarativePathViewPrivate::moveDirection
Definition at line 177 of file qdeclarativepathview_p_p.h.
moveHighlight
QDeclarativeTimeLineValueProxy<QDeclarativePathViewPrivate> QDeclarativePathViewPrivate::moveHighlight
Definition at line 181 of file qdeclarativepathview_p_p.h.
moveOffset
QDeclarativeTimeLineValueProxy<QDeclarativePathViewPrivate> QDeclarativePathViewPrivate::moveOffset
Definition at line 166 of file qdeclarativepathview_p_p.h.
moveReason
MovementReason QDeclarativePathViewPrivate::moveReason
Definition at line 175 of file qdeclarativepathview_p_p.h.
moving
bool QDeclarativePathViewPrivate::moving
Definition at line 159 of file qdeclarativepathview_p_p.h.
offset
qreal QDeclarativePathViewPrivate::offset
Definition at line 149 of file qdeclarativepathview_p_p.h.
Referenced by isValid().
offsetAdj
qreal QDeclarativePathViewPrivate::offsetAdj
Definition at line 150 of file qdeclarativepathview_p_p.h.
ownModel
bool QDeclarativePathViewPrivate::ownModel
Definition at line 153 of file qdeclarativepathview_p_p.h.
path
QDeclarativePath* QDeclarativePathViewPrivate::path
Definition at line 141 of file qdeclarativepathview_p_p.h.
Referenced by isValid().
pathItems
int QDeclarativePathViewPrivate::pathItems
Definition at line 168 of file qdeclarativepathview_p_p.h.
requestedIndex
int QDeclarativePathViewPrivate::requestedIndex
Definition at line 169 of file qdeclarativepathview_p_p.h.
startPc
qreal QDeclarativePathViewPrivate::startPc
Definition at line 145 of file qdeclarativepathview_p_p.h.
startPoint
QPointF QDeclarativePathViewPrivate::startPoint
Definition at line 146 of file qdeclarativepathview_p_p.h.
stealMouse
bool QDeclarativePathViewPrivate::stealMouse
Definition at line 152 of file qdeclarativepathview_p_p.h.
tl
QDeclarativeTimeLine QDeclarativePathViewPrivate::tl
Definition at line 165 of file qdeclarativepathview_p_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativepathview_p_p.h
/src/declarative/graphicsitems/qdeclarativepathview.cpp