Qt 4.8: QXmlContentHandler Class Reference
QXmlContentHandler Class Reference abstract
The QXmlContentHandler class provides an interface to report the logical content of XML data.
#include <qxml.h>
Public Functions
virtual bool characters (const QString &ch)=0
The reader calls this function when it has parsed a chunk of character data (either normal character data or character data inside a CDATA section; if you need to distinguish between those two types you must use QXmlLexicalHandler::startCDATA() and QXmlLexicalHandler::endCDATA()).
virtual bool endDocument ()=0
The reader calls this function after it has finished parsing.
virtual bool endElement (const QString &namespaceURI, const QString &localName, const QString &qName)=0
The reader calls this function when it has parsed an end element tag with the qualified name qName, the local name localName and the namespace URI namespaceURI.
virtual bool endPrefixMapping (const QString &prefix)=0
The reader calls this function to signal the end of a prefix mapping for the prefix prefix.
virtual QString errorString () const =0
The reader calls this function to get an error string, e.
virtual bool ignorableWhitespace (const QString &ch)=0
Some readers may use this function to report each chunk of whitespace in element content.
virtual bool processingInstruction (const QString &target, const QString &data)=0
The reader calls this function when it has parsed a processing instruction.
virtual void setDocumentLocator (QXmlLocator *locator)=0
The reader calls this function before it starts parsing the document.
virtual bool skippedEntity (const QString &name)=0
Some readers may skip entities if they have not seen the declarations (e.
virtual bool startDocument ()=0
The reader calls this function when it starts parsing the document.
virtual bool startElement (const QString &namespaceURI, const QString &localName, const QString &qName, const QXmlAttributes &atts)=0
The reader calls this function when it has parsed a start element tag.
virtual bool startPrefixMapping (const QString &prefix, const QString &uri)=0
The reader calls this function to signal the begin of a prefix-URI namespace mapping scope.
virtual ~QXmlContentHandler ()
Destroys the content handler.
Detailed Description
The QXmlContentHandler class provides an interface to report the logical content of XML data.
Note
This class or function is reentrant.
Attention
Module: QtXml
If the application needs to be informed of basic parsing events, it can implement this interface and activate it using QXmlReader::setContentHandler(). The reader can then report basic document-related events like the start and end of elements and character data through this interface.
The order of events in this interface is very important, and mirrors the order of information in the document itself. For example, all of an element's content (character data, processing instructions, and sub-elements) appears, in order, between the startElement() event and the corresponding endElement() event.
The class QXmlDefaultHandler provides a default implementation for this interface; subclassing from the QXmlDefaultHandler class is very convenient if you only want to be informed of some parsing events.
The startDocument() function is called at the start of the document, and endDocument() is called at the end. Before parsing begins setDocumentLocator() is called. For each element startElement() is called, with endElement() being called at the end of each element. The characters() function is called with chunks of character data; ignorableWhitespace() is called with chunks of whitespace and processingInstruction() is called with processing instructions. If an entity is skipped skippedEntity() is called. At the beginning of prefix-URI scopes startPrefixMapping() is called.
See also
QXmlDTDHandler, QXmlDeclHandler, QXmlEntityResolver, QXmlErrorHandler, QXmlLexicalHandler, {Introduction to SAX2}
Definition at line 301 of file qxml.h.
Constructors and Destructors
~QXmlContentHandler()
QXmlContentHandler::~QXmlContentHandler () inline virtual
Destroys the content handler.
Definition at line 304 of file qxml.h.
 {}
Functions
characters()
bool QXmlContentHandler::characters (const QString & ch) pure virtual
The reader calls this function when it has parsed a chunk of character data (either normal character data or character data inside a CDATA section; if you need to distinguish between those two types you must use QXmlLexicalHandler::startCDATA() and QXmlLexicalHandler::endCDATA()).
The character data is reported in ch.
Some readers report whitespace in element content using the ignorableWhitespace() function rather than using this one.
A reader may report the character data of an element in more than one chunk; e.g. a reader might want to report "a\<b" in three characters() events ("a ", "\<" and " b").
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
Implemented in QDomHandler, and QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseContent(), QXmlSimpleReaderPrivate::processReference(), and QXmlSimpleReaderPrivate::reportEndEntities().
endDocument()
bool QXmlContentHandler::endDocument () pure virtual
The reader calls this function after it has finished parsing.
It is called just once, and is the last handler function called. It is called after the reader has read all input or has abandoned parsing because of a fatal error.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
See also
startDocument()
Implemented in QDomHandler, and QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseBeginOrContinue().
endElement()
bool QXmlContentHandler::endElement (const QString & namespaceURI, const QString & localName, const QString & qName) pure virtual
The reader calls this function when it has parsed an end element tag with the qualified name qName, the local name localName and the namespace URI namespaceURI.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
See also
startElement(), {Namespace Support via Features}
Implemented in QDomHandler, and QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::processElementEmptyTag(), and QXmlSimpleReaderPrivate::processElementETagBegin2().
endPrefixMapping()
bool QXmlContentHandler::endPrefixMapping (const QString & prefix) pure virtual
The reader calls this function to signal the end of a prefix mapping for the prefix prefix.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
See also
startPrefixMapping(), {Namespace Support via Features}
Implemented in QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::processElementEmptyTag(), and QXmlSimpleReaderPrivate::processElementETagBegin2().
errorString()
QString QXmlContentHandler::errorString () const pure virtual
The reader calls this function to get an error string, e.
g. if any of the handler functions returns false.
Implemented in QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseBeginOrContinue(), QXmlSimpleReaderPrivate::parseContent(), QXmlSimpleReaderPrivate::parseElement(), QXmlSimpleReaderPrivate::parseMarkupdecl(), QXmlSimpleReaderPrivate::parseMisc(), QXmlSimpleReaderPrivate::parsePEReference(), QXmlSimpleReaderPrivate::parseProlog(), QXmlSimpleReaderPrivate::processElementAttribute(), QXmlSimpleReaderPrivate::processElementEmptyTag(), QXmlSimpleReaderPrivate::processElementETagBegin2(), QXmlSimpleReaderPrivate::processReference(), and QXmlSimpleReaderPrivate::reportEndEntities().
ignorableWhitespace()
bool QXmlContentHandler::ignorableWhitespace (const QString & ch) pure virtual
Some readers may use this function to report each chunk of whitespace in element content.
The whitespace is reported in ch.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
Implemented in QXmlDefaultHandler.
processingInstruction()
bool QXmlContentHandler::processingInstruction (const QString & target, const QString & data) pure virtual
The reader calls this function when it has parsed a processing instruction.
target is the target name of the processing instruction and data is the data in the processing instruction.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
Implemented in QDomHandler, and QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseContent(), QXmlSimpleReaderPrivate::parseMarkupdecl(), QXmlSimpleReaderPrivate::parseMisc(), and QXmlSimpleReaderPrivate::parseProlog().
setDocumentLocator()
void QXmlContentHandler::setDocumentLocator (QXmlLocator * locator) pure virtual
The reader calls this function before it starts parsing the document.
The argument locator is a pointer to a QXmlLocator which allows the application to get the parsing position within the document.
Do not destroy the locator; it is destroyed when the reader is destroyed. (Do not use the locator after the reader is destroyed).
Implemented in QDomHandler, and QXmlDefaultHandler.
skippedEntity()
bool QXmlContentHandler::skippedEntity (const QString & name) pure virtual
Some readers may skip entities if they have not seen the declarations (e.
g. because they are in an external DTD). If they do so they report that they skipped the entity called name by calling this function.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
Implemented in QDomHandler, and QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parsePEReference(), and QXmlSimpleReaderPrivate::processReference().
startDocument()
bool QXmlContentHandler::startDocument () pure virtual
The reader calls this function when it starts parsing the document.
The reader calls this function just once, after the call to setDocumentLocator(), and before any other functions in this class or in the QXmlDTDHandler class are called.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
See also
endDocument()
Implemented in QXmlDefaultHandler.
startElement()
bool QXmlContentHandler::startElement (const QString & namespaceURI, const QString & localName, const QString & qName, const QXmlAttributes & atts) pure virtual
The reader calls this function when it has parsed a start element tag.
There is a corresponding endElement() call when the corresponding end element tag is read. The startElement() and endElement() calls are always nested correctly. Empty element tags (e.g. <x>) cause a startElement() call to be immediately followed by an endElement() call.
The attribute list provided only contains attributes with explicit values. The attribute list contains attributes used for namespace declaration (i.e. attributes starting with xmlns) only if the namespace-prefix property of the reader is true.
The argument namespaceURI is the namespace URI, or an empty string if the element has no namespace URI or if no namespace processing is done. localName is the local name (without prefix), or an empty string if no namespace processing is done, qName is the qualified name (with prefix) and atts are the attributes attached to the element. If there are no attributes, atts is an empty attributes object.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
See also
endElement(), {Namespace Support via Features}
Implemented in QDomHandler, and QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseElement(), and QXmlSimpleReaderPrivate::processElementEmptyTag().
startPrefixMapping()
bool QXmlContentHandler::startPrefixMapping (const QString & prefix, const QString & uri) pure virtual
The reader calls this function to signal the begin of a prefix-URI namespace mapping scope.
This information is not necessary for normal namespace processing since the reader automatically replaces prefixes for element and attribute names.
Note that startPrefixMapping() and endPrefixMapping() calls are not guaranteed to be properly nested relative to each other: all startPrefixMapping() events occur before the corresponding startElement() event, and all endPrefixMapping() events occur after the corresponding endElement() event, but their order is not otherwise guaranteed.
The argument prefix is the namespace prefix being declared and the argument uri is the namespace URI the prefix is mapped to.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
See also
endPrefixMapping(), {Namespace Support via Features}
Implemented in QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::processElementAttribute().
The documentation for this class was generated from the following files:
/src/xml/sax/qxml.h
/src/xml/sax/qxml.cpp