Qt 4.8: QGLFramebufferObject Class Reference
QGLFramebufferObject Class Reference
The QGLFramebufferObject class encapsulates an OpenGL framebuffer object.
#include <qglframebufferobject.h>
Public Types
enum Attachment { NoAttachment, CombinedDepthStencil, Depth }
This enum type is used to configure the depth and stencil buffers attached to the framebuffer object when it is created.
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Functions
Attachment attachment () const
Returns the status of the depth and stencil buffers attached to this framebuffer object.
bool bind ()
Switches rendering from the default, windowing system provided framebuffer to this framebuffer object.
void drawTexture (const QRectF &target, GLuint textureId, GLenum textureTarget=GL_TEXTURE_2D)
Draws the given texture, textureId, to the given target rectangle, target, in OpenGL model space.
void drawTexture (const QPointF &point, GLuint textureId, GLenum textureTarget=GL_TEXTURE_2D)
Draws the given texture, textureId, at the given point in OpenGL model space.
QGLFramebufferObjectFormat format () const
Returns the format of this framebuffer object.
GLuint handle () const
Returns the GL framebuffer object handle for this framebuffer object (returned by the glGenFrameBuffersEXT() function).
bool isBound () const
Returns true if the framebuffer object is currently bound to a context, otherwise false is returned.
bool isValid () const
Returns true if the framebuffer object is valid.
QPaintEngine * paintEngine () const
Reimplemented Function
QGLFramebufferObject (const QSize &size, GLenum target=GL_TEXTURE_2D)
Constructs an OpenGL framebuffer object and binds a 2D GL texture to the buffer of the size size.
QGLFramebufferObject (int width, int height, GLenum target=GL_TEXTURE_2D)
Constructs an OpenGL framebuffer object and binds a 2D GL texture to the buffer of the given width and height.
QGLFramebufferObject (const QSize &size, Attachment attachment, GLenum target=GL_TEXTURE_2D, GLenum internal_format=GL_RGBA8)
Constructs an OpenGL framebuffer object and binds a texture to the buffer of the given size.
QGLFramebufferObject (int width, int height, Attachment attachment, GLenum target=GL_TEXTURE_2D, GLenum internal_format=GL_RGBA8)
Constructs an OpenGL framebuffer object and binds a texture to the buffer of the given width and height.
QGLFramebufferObject (const QSize &size, const QGLFramebufferObjectFormat &format)
Constructs an OpenGL framebuffer object of the given size based on the supplied format.
QGLFramebufferObject (int width, int height, const QGLFramebufferObjectFormat &format)
Constructs an OpenGL framebuffer object of the given width and height based on the supplied format.
bool release ()
Switches rendering back to the default, windowing system provided framebuffer.
QSize size () const
Returns the size of the texture attached to this framebuffer object.
GLuint texture () const
Returns the texture id for the texture attached as the default rendering target in this framebuffer object.
QImage toImage () const
Returns the contents of this framebuffer object as a QImage.
virtual ~QGLFramebufferObject ()
Destroys the framebuffer object and frees any allocated resources.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
virtual HDC getDC () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
virtual void releaseDC (HDC hdc) const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static bool bindDefault ()
Switches rendering back to the default, windowing system provided framebuffer.
static void blitFramebuffer (QGLFramebufferObject *target, const QRect &targetRect, QGLFramebufferObject *source, const QRect &sourceRect, GLbitfield buffers=GL_COLOR_BUFFER_BIT, GLenum filter=GL_NEAREST)
Blits from the sourceRect rectangle in the source framebuffer object to the targetRect rectangle in the target framebuffer object.
static bool hasOpenGLFramebufferBlit ()
Returns true if the OpenGL GL_EXT_framebuffer_blit extension is present on this system; otherwise returns false.
static bool hasOpenGLFramebufferObjects ()
Returns true if the OpenGL GL_EXT_framebuffer_object extension is present on this system; otherwise returns false.
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Functions
int devType () const
int metric (PaintDeviceMetric metric) const
Reimplemented Function
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
QScopedPointer< QGLFramebufferObjectPrivate > d_ptr
Friends
class QGLFBOGLPaintDevice
class QGLPaintDevice
Additional Inherited Members
Protected Variables inherited from QPaintDevice
ushort painters
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QGLFramebufferObject class encapsulates an OpenGL framebuffer object.
Since
4.2
The QGLFramebufferObject class encapsulates an OpenGL framebuffer object, defined by the GL_EXT_framebuffer_object extension. In addition it provides a rendering surface that can be painted on with a QPainter, rendered to using native GL calls, or both. This surface can be bound and used as a regular texture in your own GL drawing code. By default, the QGLFramebufferObject class generates a 2D GL texture (using the GL_TEXTURE_2D target), which is used as the internal rendering target.
It is important to have a current GL context when creating a QGLFramebufferObject, otherwise initialization will fail.
OpenGL framebuffer objects and pbuffers (see QGLPixelBuffer) can both be used to render to offscreen surfaces, but there are a number of advantages with using framebuffer objects instead of pbuffers:
A framebuffer object does not require a separate rendering context, so no context switching will occur when switching rendering targets. There is an overhead involved in switching targets, but in general it is cheaper than a context switch to a pbuffer.
Rendering to dynamic textures (i.e. render-to-texture functionality) works on all platforms. No need to do explicit copy calls from a render buffer into a texture, as was necessary on systems that did not support the render_texture extension.
It is possible to attach several rendering buffers (or texture objects) to the same framebuffer object, and render to all of them without doing a context switch.
The OpenGL framebuffer extension is a pure GL extension with no system dependant WGL, CGL, or GLX parts. This makes using framebuffer objects more portable.
When using a QPainter to paint to a QGLFramebufferObject you should take care that the QGLFramebufferObject is created with the CombinedDepthStencil attachment for QPainter to be able to render correctly. Note that you need to create a QGLFramebufferObject with more than one sample per pixel for primitives to be antialiased when drawing using a QPainter. To create a multisample framebuffer object you should use one of the constructors that take a QGLFramebufferObject parameter, and set the QGLFramebufferObject::samples() property to a non-zero value.
When painting to a QGLFramebufferObject using QPainter, the state of the current GL context will be altered by the paint engine to reflect its needs. Applications should not rely upon the GL state being reset to its original conditions, particularly the current shader program, GL viewport, texture units, and drawing modes.
For multisample framebuffer objects a color render buffer is created, otherwise a texture with the specified texture target is created. The color render buffer or texture will have the specified internal format, and will be bound to the GL_COLOR_ATTACHMENT0 attachment in the framebuffer object.
If you want to use a framebuffer object with multisampling enabled as a texture, you first need to copy from it to a regular framebuffer object using QGLContext::blitFramebuffer().
Threading
As of Qt 4.8, it's possible to draw into a QGLFramebufferObject using a QPainter in a separate thread. Note that OpenGL 2.0 or OpenGL ES 2.0 is required for this to work. Also, under X11, it's necessary to set the Qt::AA_X11InitThreads application attribute.
See also
{Framebuffer Object Example}
Definition at line 57 of file qglframebufferobject.h.
Enumerations
Attachment
enum QGLFramebufferObject::Attachment
This enum type is used to configure the depth and stencil buffers attached to the framebuffer object when it is created.
Since
4.3
NoAttachment No attachment is added to the framebuffer object. Note that the OpenGL depth and stencil tests won't work when rendering to a framebuffer object without any depth or stencil buffers. This is the default value.
CombinedDepthStencil If the GL_EXT_packed_depth_stencil extension is present, a combined depth and stencil buffer is attached. If the extension is not present, only a depth buffer is attached.
Depth A depth buffer is attached to the framebuffer object.
See also
attachment()
Enumerator
NoAttachment
CombinedDepthStencil
Depth
Definition at line 61 of file qglframebufferobject.h.
                     {
         NoAttachment,
         CombinedDepthStencil,
         Depth
     };
Constructors and Destructors
QGLFramebufferObject() [1/6]
QGLFramebufferObject::QGLFramebufferObject (const QSize & size, GLenum target = GL_TEXTURE_2D)
Constructs an OpenGL framebuffer object and binds a 2D GL texture to the buffer of the size size.
The texture is bound to the GL_COLOR_ATTACHMENT0 target in the framebuffer object.
The target parameter is used to specify the GL texture target. The default target is GL_TEXTURE_2D. Keep in mind that GL_TEXTURE_2D textures must have a power of 2 width and height (e.g. 256x512), unless you are using OpenGL 2.0 or higher.
By default, no depth and stencil buffers are attached. This behavior can be toggled using one of the overloaded constructors.
The default internal texture format is GL_RGBA8 for desktop OpenGL, and GL_RGBA for OpenGL/ES.
It is important that you have a current GL context set when creating the QGLFramebufferObject, otherwise the initialization will fail.
See also
size(), texture(), attachment()
Definition at line 794 of file qglframebufferobject.cpp.
Referenced by QGLFramebufferObject().
     : d_ptr(new QGLFramebufferObjectPrivate)
 {
     Q_D(QGLFramebufferObject);
     d->init(this, size, NoAttachment, target, DEFAULT_FORMAT);
 }
QGLFramebufferObject() [2/6]
QGLFramebufferObject::QGLFramebufferObject (int width, int height, GLenum target = GL_TEXTURE_2D)
Constructs an OpenGL framebuffer object and binds a 2D GL texture to the buffer of the given width and height.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
size(), texture()
Definition at line 821 of file qglframebufferobject.cpp.
     : d_ptr(new QGLFramebufferObjectPrivate)
 {
     Q_D(QGLFramebufferObject);
     d->init(this, QSize(width, height), NoAttachment, target, DEFAULT_FORMAT);
 }
QGLFramebufferObject() [3/6]
QGLFramebufferObject::QGLFramebufferObject (const QSize & size, Attachment attachment, GLenum target = GL_TEXTURE_2D, GLenum internal_format = GL_RGBA8)
Constructs an OpenGL framebuffer object and binds a texture to the buffer of the given size.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The attachment parameter describes the depth/stencil buffer configuration, target the texture target and internal_format the internal texture format. The default texture target is GL_TEXTURE_2D, while the default internal format is GL_RGBA8 for desktop OpenGL and GL_RGBA for OpenGL/ES.
See also
size(), texture(), attachment()
Definition at line 923 of file qglframebufferobject.cpp.
     : d_ptr(new QGLFramebufferObjectPrivate)
 {
     Q_D(QGLFramebufferObject);
     d->init(this, size, attachment, target, internal_format);
 }
QGLFramebufferObject() [4/6]
QGLFramebufferObject::QGLFramebufferObject (int width, int height, Attachment attachment, GLenum target = GL_TEXTURE_2D, GLenum internal_format = GL_RGBA8)
Constructs an OpenGL framebuffer object and binds a texture to the buffer of the given width and height.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The attachment parameter describes the depth/stencil buffer configuration, target the texture target and internal_format the internal texture format. The default texture target is GL_TEXTURE_2D, while the default internal format is GL_RGBA8 for desktop OpenGL and GL_RGBA for OpenGL/ES.
See also
size(), texture(), attachment()
Definition at line 888 of file qglframebufferobject.cpp.
     : d_ptr(new QGLFramebufferObjectPrivate)
 {
     Q_D(QGLFramebufferObject);
     d->init(this, QSize(width, height), attachment, target, internal_format);
 }
QGLFramebufferObject() [5/6]
QGLFramebufferObject::QGLFramebufferObject (const QSize & size, const QGLFramebufferObjectFormat & format)
Constructs an OpenGL framebuffer object of the given size based on the supplied format.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 837 of file qglframebufferobject.cpp.
     : d_ptr(new QGLFramebufferObjectPrivate)
 {
     Q_D(QGLFramebufferObject);
     d->init(this, size, format.attachment(), format.textureTarget(), format.internalTextureFormat(),
             format.samples(), format.mipmap());
 }
QGLFramebufferObject() [6/6]
QGLFramebufferObject::QGLFramebufferObject (int width, int height, const QGLFramebufferObjectFormat & format)
Constructs an OpenGL framebuffer object of the given width and height based on the supplied format.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 854 of file qglframebufferobject.cpp.
     : d_ptr(new QGLFramebufferObjectPrivate)
 {
     Q_D(QGLFramebufferObject);
     d->init(this, QSize(width, height), format.attachment(), format.textureTarget(),
             format.internalTextureFormat(), format.samples(), format.mipmap());
 }
~QGLFramebufferObject()
QGLFramebufferObject::~QGLFramebufferObject () virtual
Destroys the framebuffer object and frees any allocated resources.
Definition at line 950 of file qglframebufferobject.cpp.
 {
     Q_D(QGLFramebufferObject);
     QGL_FUNC_CONTEXT;
     delete d->engine;
     if (isValid() && ctx) {
         QGLShareContextScope scope(ctx);
         if (d->texture)
             glDeleteTextures(1, &d->texture);
         if (d->color_buffer)
             glDeleteRenderbuffers(1, &d->color_buffer);
         if (d->depth_buffer)
             glDeleteRenderbuffers(1, &d->depth_buffer);
         if (d->stencil_buffer && d->stencil_buffer != d->depth_buffer)
             glDeleteRenderbuffers(1, &d->stencil_buffer);
         GLuint fbo = d->fbo();
         glDeleteFramebuffers(1, &fbo);
     }
 }
Functions
attachment()
QGLFramebufferObject::Attachment QGLFramebufferObject::attachment () const
Returns the status of the depth and stencil buffers attached to this framebuffer object.
Definition at line 1364 of file qglframebufferobject.cpp.
Referenced by QGLFramebufferObject().
 {
     Q_D(const QGLFramebufferObject);
     if (d->valid)
         return d->fbo_attachment;
     return NoAttachment;
 }
bind()
bool QGLFramebufferObject::bind ()
Switches rendering from the default, windowing system provided framebuffer to this framebuffer object.
Returns true upon success, false otherwise.
See also
release()
Definition at line 1011 of file qglframebufferobject.cpp.
Referenced by QGLWindowSurface::beginPaint(), QGLWindowSurface::flush(), and toImage().
 {
     if (!isValid())
     return false;
     Q_D(QGLFramebufferObject);
     QGL_FUNC_CONTEXT;
     if (!ctx)
         return false;   // Context no longer exists.
     const QGLContext *current = QGLContext::currentContext();
 #ifdef QT_DEBUG
     if (!current ||
         QGLContextPrivate::contextGroup(current) != QGLContextPrivate::contextGroup(ctx))
     {
         qWarning("QGLFramebufferObject::bind() called from incompatible context");
     }
 #endif
     glBindFramebuffer(GL_FRAMEBUFFER_EXT, d->fbo());
     d->valid = d->checkFramebufferStatus();
     if (d->valid && current)
         current->d_ptr->current_fbo = d->fbo();
     return d->valid;
 }
bindDefault()
bool QGLFramebufferObject::bindDefault () static
Switches rendering back to the default, windowing system provided framebuffer.
Warning
This function is not part of the public interface.
Returns true upon success, false otherwise.
See also
bind(), release()
Definition at line 1202 of file qglframebufferobject.cpp.
 {
     QGLContext *ctx = const_cast<QGLContext *>(QGLContext::currentContext());
     if (ctx) {
         bool ext_detected = (QGLExtensions::glExtensions() & QGLExtensions::FramebufferObject);
         if (!ext_detected || (ext_detected && !qt_resolve_framebufferobject_extensions(ctx)))
             return false;
         ctx->d_ptr->current_fbo = ctx->d_ptr->default_fbo;
         glBindFramebuffer(GL_FRAMEBUFFER_EXT, ctx->d_ptr->default_fbo);
 #ifdef QT_DEBUG
     } else {
         qWarning("QGLFramebufferObject::bindDefault() called without current context.");
 #endif
     }
     return ctx != 0;
 }
blitFramebuffer()
void QGLFramebufferObject::blitFramebuffer (QGLFramebufferObject * target, const QRect & targetRect, QGLFramebufferObject * source, const QRect & sourceRect, GLbitfield buffers = GL_COLOR_BUFFER_BIT, GLenum filter = GL_NEAREST) static
Blits from the sourceRect rectangle in the source framebuffer object to the targetRect rectangle in the target framebuffer object.
Since
4.6
If source or target is 0, the default framebuffer will be used instead of a framebuffer object as source or target respectively.
The buffers parameter should be a mask consisting of any combination of GL_COLOR_BUFFER_BIT, GL_DEPTH_BUFFER_BIT, and GL_STENCIL_BUFFER_BIT. Any buffer type that is not present both in the source and target buffers is ignored.
The sourceRect and targetRect rectangles may have different sizes; in this case buffers should not contain GL_DEPTH_BUFFER_BIT or GL_STENCIL_BUFFER_BIT. The filter parameter should be set to GL_LINEAR or GL_NEAREST, and specifies whether linear or nearest interpolation should be used when scaling is performed.
If source equals target a copy is performed within the same buffer. Results are undefined if the source and target rectangles overlap and have different sizes. The sizes must also be the same if any of the framebuffer objects are multisample framebuffers.
Note that the scissor test will restrict the blit area if enabled.
This function will have no effect unless hasOpenGLFramebufferBlit() returns true.
See also
hasOpenGLFramebufferBlit()
Definition at line 1442 of file qglframebufferobject.cpp.
Referenced by toImage().
 {
     if (!(QGLExtensions::glExtensions() & QGLExtensions::FramebufferBlit))
         return;
     const QGLContext *ctx = QGLContext::currentContext();
     if (!ctx)
         return;
     const int height = ctx->device()->height();
     const int sh = source ? source->height() : height;
     const int th = target ? target->height() : height;
     const int sx0 = sourceRect.left();
     const int sx1 = sourceRect.left() + sourceRect.width();
     const int sy0 = sh - (sourceRect.top() + sourceRect.height());
     const int sy1 = sh - sourceRect.top();
     const int tx0 = targetRect.left();
     const int tx1 = targetRect.left() + targetRect.width();
     const int ty0 = th - (targetRect.top() + targetRect.height());
     const int ty1 = th - targetRect.top();
     glBindFramebuffer(GL_READ_FRAMEBUFFER_EXT, source ? source->handle() : 0);
     glBindFramebuffer(GL_DRAW_FRAMEBUFFER_EXT, target ? target->handle() : 0);
     glBlitFramebufferEXT(sx0, sy0, sx1, sy1,
                          tx0, ty0, tx1, ty1,
                          buffers, filter);
     glBindFramebuffer(GL_FRAMEBUFFER_EXT, ctx->d_ptr->current_fbo);
 }
devType()
int QGLFramebufferObject::devType () const inline protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QPaintDevice.
Definition at line 130 of file qglframebufferobject.h.
 { return QInternal::FramebufferObject; }
drawTexture() [1/2]
void QGLFramebufferObject::drawTexture (const QRectF & target, GLuint textureId, GLenum textureTarget = GL_TEXTURE_2D)
Draws the given texture, textureId, to the given target rectangle, target, in OpenGL model space.
Since
4.4
The textureTarget should be a 2D texture target.
The framebuffer object should be bound when calling this function.
Equivalent to the corresponding QGLContext::drawTexture().
Definition at line 1250 of file qglframebufferobject.cpp.
Referenced by drawTexture().
 {
     const_cast<QGLContext *>(QGLContext::currentContext())->drawTexture(target, textureId, textureTarget);
 }
drawTexture() [2/2]
void QGLFramebufferObject::drawTexture (const QPointF & point, GLuint textureId, GLenum textureTarget = GL_TEXTURE_2D)
Draws the given texture, textureId, at the given point in OpenGL model space.
Since
4.4
The textureTarget should be a 2D texture target.
The framebuffer object should be bound when calling this function.
Equivalent to the corresponding QGLContext::drawTexture().
Definition at line 1276 of file qglframebufferobject.cpp.
 {
     const_cast<QGLContext *>(QGLContext::currentContext())->drawTexture(point, textureId, textureTarget);
 }
format()
QGLFramebufferObjectFormat QGLFramebufferObject::format () const
Returns the format of this framebuffer object.
Definition at line 1109 of file qglframebufferobject.cpp.
Referenced by QGLFramebufferObjectPool::acquire(), QGLWindowSurface::flush(), QGLFBOGLPaintDevice::setFBO(), toImage(), ShaderEffectSource::updateBackbuffer(), and QGLWindowSurface::updateGeometry().
 {
     Q_D(const QGLFramebufferObject);
     return d->format;
 }
handle()
GLuint QGLFramebufferObject::handle () const
Returns the GL framebuffer object handle for this framebuffer object (returned by the glGenFrameBuffersEXT() function).
This handle can be used to attach new images or buffers to the framebuffer. The user is responsible for cleaning up and destroying these objects.
Definition at line 1348 of file qglframebufferobject.cpp.
Referenced by blitFramebuffer(), QGLPixmapData::copy(), QGLPixmapData::copyBackFromRenderFbo(), and QGLWindowSurface::flush().
 {
     Q_D(const QGLFramebufferObject);
     return d->fbo();
 }
hasOpenGLFramebufferBlit()
bool QGLFramebufferObject::hasOpenGLFramebufferBlit () static
Returns true if the OpenGL GL_EXT_framebuffer_blit extension is present on this system; otherwise returns false.
Since
4.6
See also
blitFramebuffer()
Definition at line 1402 of file qglframebufferobject.cpp.
Referenced by QGLPixmapData::useFramebufferObjects().
 {
     return (QGLExtensions::glExtensions() & QGLExtensions::FramebufferBlit);
 }
hasOpenGLFramebufferObjects()
bool QGLFramebufferObject::hasOpenGLFramebufferObjects () static
Returns true if the OpenGL GL_EXT_framebuffer_object extension is present on this system; otherwise returns false.
Definition at line 1231 of file qglframebufferobject.cpp.
Referenced by QGL2PaintEngineEx::begin(), QGLTextureGlyphCache::createTextureData(), QGL2PaintEngineEx::drawStaticTextItem(), QGL2PaintEngineEx::drawTextItem(), QGLTextureGlyphCache::fillTexture(), QGLGlyphTexture::QGLGlyphTexture(), QGLTextureGlyphCache::resizeTextureData(), and QGLPixmapData::useFramebufferObjects().
 {
     return (QGLExtensions::glExtensions() & QGLExtensions::FramebufferObject);
 }
isBound()
bool QGLFramebufferObject::isBound () const
Returns true if the framebuffer object is currently bound to a context, otherwise false is returned.
Since
4.5
Definition at line 1382 of file qglframebufferobject.cpp.
Referenced by QGLPixmapData::copy(), QGLPixmapData::copyBackFromRenderFbo(), QWaylandGLWindowSurface::flush(), QGLWindowSurface::flush(), and toImage().
 {
     Q_D(const QGLFramebufferObject);
     const QGLContext *current = QGLContext::currentContext();
     return current ? current->d_ptr->current_fbo == d->fbo() : false;
 }
isValid()
bool QGLFramebufferObject::isValid () const
Returns true if the framebuffer object is valid.
The framebuffer can become invalid if the initialization process fails, the user attaches an invalid buffer to the framebuffer object, or a non-power of two width/height is specified as the texture size if the texture target is GL_TEXTURE_2D. The non-power of two limitation does not apply if the OpenGL version is 2.0 or higher, or if the GL_ARB_texture_non_power_of_two extension is present.
The framebuffer can also become invalid if the QGLContext that the framebuffer was created within is destroyed and there are no other shared contexts that can take over ownership of the framebuffer.
Definition at line 993 of file qglframebufferobject.cpp.
Referenced by QGLFramebufferObjectPool::acquire(), bind(), ShaderEffectSource::bind(), release(), ShaderEffectSource::updateBackbuffer(), QGLWindowSurface::updateGeometry(), ShaderEffect::updateRenderTargets(), ShaderEffectSource::updateSizeAndTexture(), and ~QGLFramebufferObject().
 {
     Q_D(const QGLFramebufferObject);
     return d->valid && d->fbo_guard.context();
 }
metric()
int QGLFramebufferObject::metric (PaintDeviceMetric metric) const protected virtual
Reimplemented Function
Reimplemented from QPaintDevice.
Definition at line 1290 of file qglframebufferobject.cpp.
 {
     Q_D(const QGLFramebufferObject);
     float dpmx = qt_defaultDpiX()*100./2.54;
     float dpmy = qt_defaultDpiY()*100./2.54;
     int w = d->size.width();
     int h = d->size.height();
     switch (metric) {
     case PdmWidth:
         return w;
     case PdmHeight:
         return h;
     case PdmWidthMM:
         return qRound(w * 1000 / dpmx);
     case PdmHeightMM:
         return qRound(h * 1000 / dpmy);
     case PdmNumColors:
         return 0;
     case PdmDepth:
         return 32;//d->depth;
     case PdmDpiX:
         return qRound(dpmx * 0.0254);
     case PdmDpiY:
         return qRound(dpmy * 0.0254);
     case PdmPhysicalDpiX:
         return qRound(dpmx * 0.0254);
     case PdmPhysicalDpiY:
         return qRound(dpmy * 0.0254);
     default:
         qWarning("QGLFramebufferObject::metric(), Unhandled metric type: %d.\n", metric);
         break;
     }
     return 0;
 }
paintEngine()
QPaintEngine * QGLFramebufferObject::paintEngine () const virtual
Reimplemented Function
Implements QPaintDevice.
Definition at line 1158 of file qglframebufferobject.cpp.
 {
     Q_D(const QGLFramebufferObject);
     if (d->engine)
         return d->engine;
 #if !defined(QT_OPENGL_ES_1)
 #if !defined (QT_OPENGL_ES_2)
     if (qt_gl_preferGL2Engine()) {
 #endif
         QPaintEngine *engine = qt_buffer_2_engine()->engine();
         if (engine->isActive() && engine->paintDevice() != this) {
             d->engine = new QGL2PaintEngineEx;
             return d->engine;
         }
         return engine;
 #if !defined (QT_OPENGL_ES_2)
     }
 #endif
 #endif
 #if !defined(QT_OPENGL_ES_2)
     QPaintEngine *engine = qt_buffer_engine()->engine();
     if (engine->isActive() && engine->paintDevice() != this) {
         d->engine = new QOpenGLPaintEngine;
         return d->engine;
     }
     return engine;
 #endif
 }
release()
bool QGLFramebufferObject::release ()
Switches rendering back to the default, windowing system provided framebuffer.
Returns true upon success, false otherwise.
See also
bind()
Definition at line 1046 of file qglframebufferobject.cpp.
Referenced by QGLWindowSurface::beginPaint(), QWaylandGLWindowSurface::flush(), QGLWindowSurface::flush(), and toImage().
 {
     if (!isValid())
     return false;
     QGL_FUNC_CONTEXT;
     if (!ctx)
         return false;   // Context no longer exists.
     const QGLContext *current = QGLContext::currentContext();
 #ifdef QT_DEBUG
     if (!current ||
         QGLContextPrivate::contextGroup(current) != QGLContextPrivate::contextGroup(ctx))
     {
         qWarning("QGLFramebufferObject::release() called from incompatible context");
     }
 #endif
     if (current) {
         current->d_ptr->current_fbo = current->d_ptr->default_fbo;
         glBindFramebuffer(GL_FRAMEBUFFER_EXT, current->d_ptr->default_fbo);
     }
     return true;
 }
size()
QSize QGLFramebufferObject::size () const
Returns the size of the texture attached to this framebuffer object.
Definition at line 1100 of file qglframebufferobject.cpp.
Referenced by QGLFramebufferObjectPool::acquire(), QWaylandGLWindowSurface::flush(), QGLWindowSurface::flush(), QGLFramebufferObject(), toImage(), ShaderEffectSource::updateBackbuffer(), ShaderEffect::updateRenderTargets(), and ShaderEffectSource::updateSizeAndTexture().
 {
     Q_D(const QGLFramebufferObject);
     return d->size;
 }
texture()
GLuint QGLFramebufferObject::texture () const
Returns the texture id for the texture attached as the default rendering target in this framebuffer object.
This texture id can be bound as a normal texture in your own GL code.
If a multisample framebuffer object is used then the value returned from this function will be invalid.
Definition at line 1085 of file qglframebufferobject.cpp.
Referenced by ShaderEffectSource::bind(), QWaylandGLWindowSurface::flush(), and QGLWindowSurface::flush().
 {
     Q_D(const QGLFramebufferObject);
     return d->texture;
 }
toImage()
QImage QGLFramebufferObject::toImage () const
Returns the contents of this framebuffer object as a QImage.
Definition at line 1123 of file qglframebufferobject.cpp.
Referenced by QGLWindowSurface::buffer(), and toImage().
 {
     Q_D(const QGLFramebufferObject);
     if (!d->valid)
         return QImage();
     // qt_gl_read_framebuffer doesn't work on a multisample FBO
     if (format().samples() != 0) {
         QGLFramebufferObject temp(size(), QGLFramebufferObjectFormat());
         QRect rect(QPoint(0, 0), size());
         blitFramebuffer(&temp, rect, const_cast<QGLFramebufferObject *>(this), rect);
         return temp.toImage();
     }
     bool wasBound = isBound();
     if (!wasBound)
         const_cast<QGLFramebufferObject *>(this)->bind();
     QImage image = qt_gl_read_framebuffer(d->size, format().internalTextureFormat() != GL_RGB, true);
     if (!wasBound)
         const_cast<QGLFramebufferObject *>(this)->release();
     return image;
 }
Friends and Related Functions
QGLFBOGLPaintDevice
friend class QGLFBOGLPaintDevice friend
Definition at line 136 of file qglframebufferobject.h.
QGLPaintDevice
friend class QGLPaintDevice friend
Definition at line 135 of file qglframebufferobject.h.
Properties
d_ptr
QScopedPointer<QGLFramebufferObjectPrivate> QGLFramebufferObject::d_ptr private
Definition at line 134 of file qglframebufferobject.h.
Referenced by QGLFramebufferObject().
The documentation for this class was generated from the following files:
/src/opengl/qglframebufferobject.h
/src/opengl/qglframebufferobject.cpp