Qt 4.8: QJpUnicodeConv Class Reference
QJpUnicodeConv Class Reference
#include <qjpunicode.h>
Public Types
enum Rules {
Default = 0x0000, Unicode = 0x0001, Unicode_JISX0201 = 0x0001, Unicode_ASCII = 0x0002,
JISX0221_JISX0201 = 0x0003, JISX0221_ASCII = 0x0004, Sun_JDK117 = 0x0005, Microsoft_CP932 = 0x0006,
NEC_VDC = 0x0100, UDC = 0x0200, IBM_VDC = 0x0400
}
Public Functions
virtual uint asciiToUnicode (uint h, uint l) const
uint asciiToUnicode (uint ascii) const
uint cp932ToUnicode (uint h, uint l) const
uint jisx0201KanaToUnicode (uint h, uint l) const
uint jisx0201KanaToUnicode (uint jis) const
virtual uint jisx0201LatinToUnicode (uint h, uint l) const
uint jisx0201LatinToUnicode (uint jis) const
uint jisx0201ToUnicode (uint h, uint l) const
uint jisx0201ToUnicode (uint jis) const
virtual uint jisx0208ToUnicode (uint h, uint l) const
uint jisx0208ToUnicode (uint jis) const
virtual uint jisx0212ToUnicode (uint h, uint l) const
uint jisx0212ToUnicode (uint jis) const
uint sjisibmvdcToUnicode (uint h, uint l) const
uint sjisToUnicode (uint h, uint l) const
uint sjisToUnicode (uint sjis) const
virtual uint unicodeToAscii (uint h, uint l) const
uint unicodeToAscii (uint unicode) const
uint unicodeToCp932 (uint h, uint l) const
uint unicodeToJisx0201 (uint h, uint l) const
uint unicodeToJisx0201 (uint unicode) const
uint unicodeToJisx0201Kana (uint h, uint l) const
uint unicodeToJisx0201Kana (uint unicode) const
virtual uint unicodeToJisx0201Latin (uint h, uint l) const
uint unicodeToJisx0201Latin (uint unicode) const
virtual uint unicodeToJisx0208 (uint h, uint l) const
uint unicodeToJisx0208 (uint unicode) const
virtual uint unicodeToJisx0212 (uint h, uint l) const
uint unicodeToJisx0212 (uint unicode) const
uint unicodeToSjis (uint h, uint l) const
uint unicodeToSjis (uint unicode) const
uint unicodeToSjisibmvdc (uint h, uint l) const
virtual ~QJpUnicodeConv ()
Static Public Functions
static QJpUnicodeConv * newConverter (int rule)
Protected Functions
QJpUnicodeConv (int r)
Properties
int rule
Detailed Description
Note
This class or function is reentrant.
Warning
This function is not part of the public interface.
Definition at line 78 of file qjpunicode.h.
Enumerations
Rules
enum QJpUnicodeConv::Rules
Enumerator
Default
Unicode
Unicode_JISX0201
Unicode_ASCII
JISX0221_JISX0201
JISX0221_ASCII
Sun_JDK117
Microsoft_CP932
NEC_VDC
UDC
IBM_VDC
Definition at line 81 of file qjpunicode.h.
                {
         // "ASCII" is ANSI X.3.4-1986, a.k.a. US-ASCII here.
         Default                        = 0x0000,
         Unicode                        = 0x0001,
         Unicode_JISX0201                = 0x0001,
         Unicode_ASCII                 = 0x0002,
         JISX0221_JISX0201         = 0x0003,
         JISX0221_ASCII                = 0x0004,
         Sun_JDK117                     = 0x0005,
         Microsoft_CP932                = 0x0006,
         NEC_VDC                = 0x0100,                // NEC Vender Defined Char
         UDC                        = 0x0200,                // User Defined Char
         IBM_VDC                = 0x0400                // IBM Vender Defined Char
     };
Constructors and Destructors
~QJpUnicodeConv()
virtual QJpUnicodeConv::~QJpUnicodeConv () inline virtual
Definition at line 80 of file qjpunicode.h.
 {}
QJpUnicodeConv()
QJpUnicodeConv::QJpUnicodeConv (int r) inline explicit protected
Warning
This function is not part of the public interface.
Definition at line 166 of file qjpunicode.h.
 : rule(r) {}
Functions
asciiToUnicode() [1/2]
uint QJpUnicodeConv::asciiToUnicode (uint h, uint l) const virtual
Warning
This function is not part of the public interface.
Reimplemented in QJpUnicodeConv_JISX0221_JISX0201.
Definition at line 103 of file qjpunicode.cpp.
Referenced by asciiToUnicode(), QJpUnicodeConv_JISX0221_ASCII::jisx0201LatinToUnicode(), QJpUnicodeConv_Sun::jisx0201LatinToUnicode(), QJpUnicodeConv_Microsoft::jisx0201LatinToUnicode(), and QJpUnicodeConv_JISX0221_JISX0201::QJpUnicodeConv_JISX0221_JISX0201().
 {
     if ((h == 0) && (l < 0x80)) {
         return l;
     }
     return 0x0000;
 }
asciiToUnicode() [2/2]
uint QJpUnicodeConv::asciiToUnicode (uint ascii) const inline
Warning
This function is not part of the public interface.
Definition at line 106 of file qjpunicode.h.
{
         return asciiToUnicode((ascii & 0xff00) >> 8, (ascii & 0x00ff));
     }
cp932ToUnicode()
uint QJpUnicodeConv::cp932ToUnicode (uint h, uint l) const
Definition at line 10593 of file qjpunicode.cpp.
Referenced by QSjisCodec::convertToUnicode(), and unicodeToJisx0212().
 {
     if (rule & Microsoft_CP932) {
         if (h == 0x0087 && (l >= 0x0040 && l <= 0x009c))
             return cp932_87_unicode[l-0x0040];
         else if ((h == 0x00ed || h == 0x00ee)  && (l >= 0x0040 && l <= 0x00fc))
             return cp932_ed_ee_unicode[((h - 0x00ed)*189 + (l-0x0040))];
     }
     return 0;
 }
jisx0201KanaToUnicode() [1/2]
uint QJpUnicodeConv::jisx0201KanaToUnicode (uint h, uint l) const
Warning
This function is not part of the public interface.
Definition at line 134 of file qjpunicode.cpp.
Referenced by jisx0201KanaToUnicode(), and jisx0201ToUnicode().
 {
     if ((h == 0) && IsKana(l)) {
         return jisx0201ToUnicode11(h, l);
     }
     return 0x0000;
 }
jisx0201KanaToUnicode() [2/2]
uint QJpUnicodeConv::jisx0201KanaToUnicode (uint jis) const inline
Warning
This function is not part of the public interface.
Definition at line 115 of file qjpunicode.h.
{
         return jisx0201KanaToUnicode((jis & 0xff00) >> 8, (jis & 0x00ff));
     }
jisx0201LatinToUnicode() [1/2]
uint QJpUnicodeConv::jisx0201LatinToUnicode (uint h, uint l) const virtual
Warning
This function is not part of the public interface.
Reimplemented in QJpUnicodeConv_Microsoft, QJpUnicodeConv_Sun, and QJpUnicodeConv_JISX0221_ASCII.
Definition at line 125 of file qjpunicode.cpp.
Referenced by QJpUnicodeConv_JISX0221_JISX0201::asciiToUnicode(), jisx0201LatinToUnicode(), jisx0201ToUnicode(), QJpUnicodeConv_JISX0221_ASCII::QJpUnicodeConv_JISX0221_ASCII(), QJpUnicodeConv_Microsoft::QJpUnicodeConv_Microsoft(), and QJpUnicodeConv_Sun::QJpUnicodeConv_Sun().
 {
     if ((h == 0) && IsLatin(l)) {
         return jisx0201ToUnicode11(h, l);
     }
     return 0x0000;
 }
jisx0201LatinToUnicode() [2/2]
uint QJpUnicodeConv::jisx0201LatinToUnicode (uint jis) const inline
Warning
This function is not part of the public interface.
Definition at line 112 of file qjpunicode.h.
{
         return jisx0201LatinToUnicode((jis & 0xff00) >> 8, (jis & 0x00ff));
     }
jisx0201ToUnicode() [1/2]
uint QJpUnicodeConv::jisx0201ToUnicode (uint h, uint l) const
Warning
This function is not part of the public interface.
Definition at line 112 of file qjpunicode.cpp.
Referenced by QEucJpCodec::convertToUnicode(), QSjisCodec::convertToUnicode(), QJisCodec::convertToUnicode(), jisx0201ToUnicode(), and sjisToUnicode().
 {
     if (h == 0) {
         if (IsLatin(l)) {
             return jisx0201LatinToUnicode(h, l);
         } else if (IsKana(l)) {
             return jisx0201KanaToUnicode(h, l);
         }
     }
     return 0x0000;
 }
jisx0201ToUnicode() [2/2]
uint QJpUnicodeConv::jisx0201ToUnicode (uint jis) const inline
Warning
This function is not part of the public interface.
Definition at line 109 of file qjpunicode.h.
{
         return jisx0201ToUnicode((jis & 0xff00) >> 8, (jis & 0x00ff));
     }
jisx0208ToUnicode() [1/2]
uint QJpUnicodeConv::jisx0208ToUnicode (uint h, uint l) const virtual
Warning
This function is not part of the public interface.
Reimplemented in QJpUnicodeConv_Microsoft, QJpUnicodeConv_Sun, QJpUnicodeConv_JISX0221_ASCII, QJpUnicodeConv_JISX0221_JISX0201, and QJpUnicodeConv_Unicode_ASCII.
Definition at line 143 of file qjpunicode.cpp.
Referenced by QEucJpCodec::convertToUnicode(), QJisCodec::convertToUnicode(), jisx0208ToUnicode(), QJpUnicodeConv_Unicode_ASCII::jisx0208ToUnicode(), QJpUnicodeConv_JISX0221_JISX0201::jisx0208ToUnicode(), QJpUnicodeConv_JISX0221_ASCII::jisx0208ToUnicode(), QJpUnicodeConv_Sun::jisx0208ToUnicode(), QJpUnicodeConv_Microsoft::jisx0208ToUnicode(), QJpUnicodeConv_JISX0221_ASCII::QJpUnicodeConv_JISX0221_ASCII(), QJpUnicodeConv_JISX0221_JISX0201::QJpUnicodeConv_JISX0221_JISX0201(), QJpUnicodeConv_Microsoft::QJpUnicodeConv_Microsoft(), QJpUnicodeConv_Sun::QJpUnicodeConv_Sun(), QJpUnicodeConv_Unicode_ASCII::QJpUnicodeConv_Unicode_ASCII(), and sjisToUnicode().
 {
     if (rule & UDC){
         if ((0x75 <= h) && (h <= 0x7e) && IsJisChar(l)/*0x21 - 0x7e*/) {
             // User Defined Char (mapped to Private Use Area)
             return 0xe000 + (h - 0x75) * 0x5e + (l - 0x21);
         }
     }
     if ((rule & NEC_VDC) == 0) {
         if ((h == 0x2d) && (IsJisChar(l)/*0x21 - 0x7c*/)) {
             // NEC Vendor Defined Char
             return 0x0000;
         }
     }
     return jisx0208ToUnicode11(h, l);
 }
jisx0208ToUnicode() [2/2]
uint QJpUnicodeConv::jisx0208ToUnicode (uint jis) const inline
Warning
This function is not part of the public interface.
Definition at line 118 of file qjpunicode.h.
{
         return jisx0208ToUnicode((jis & 0xff00) >> 8, (jis & 0x00ff));
     }
jisx0212ToUnicode() [1/2]
uint QJpUnicodeConv::jisx0212ToUnicode (uint h, uint l) const virtual
Warning
This function is not part of the public interface.
Reimplemented in QJpUnicodeConv_Microsoft, QJpUnicodeConv_Sun, QJpUnicodeConv_JISX0221_ASCII, and QJpUnicodeConv_Unicode_ASCII.
Definition at line 161 of file qjpunicode.cpp.
Referenced by QEucJpCodec::convertToUnicode(), QJisCodec::convertToUnicode(), jisx0212ToUnicode(), QJpUnicodeConv_Unicode_ASCII::jisx0212ToUnicode(), QJpUnicodeConv_JISX0221_ASCII::jisx0212ToUnicode(), QJpUnicodeConv_Sun::jisx0212ToUnicode(), QJpUnicodeConv_Microsoft::jisx0212ToUnicode(), QJpUnicodeConv_JISX0221_ASCII::QJpUnicodeConv_JISX0221_ASCII(), QJpUnicodeConv_Microsoft::QJpUnicodeConv_Microsoft(), QJpUnicodeConv_Sun::QJpUnicodeConv_Sun(), and QJpUnicodeConv_Unicode_ASCII::QJpUnicodeConv_Unicode_ASCII().
 {
     if (rule & UDC){
         if ((0x75 <= h) && (h <= 0x7e) && IsJisChar(l)/*0x21 - 0x7e*/) {
             // User Defined Char (mapped to Private Use Area)
             return 0xe3ac + (h - 0x75) * 0x5e + (l - 0x21);
         }
     }
     if ((rule & IBM_VDC) == 0){
         if (((h == 0x73) && (0x73 <= l) && (l <= 0x7e)) ||
             ((h == 0x74) && (IsJisChar(l)/*0x21 - 0x7e*/))) {
             // IBM Vendor Defined Char
             return 0x0000;
         }
     }
     return jisx0212ToUnicode11(h, l);
 }
jisx0212ToUnicode() [2/2]
uint QJpUnicodeConv::jisx0212ToUnicode (uint jis) const inline
Warning
This function is not part of the public interface.
Definition at line 121 of file qjpunicode.h.
{
         return jisx0212ToUnicode((jis & 0xff00) >> 8, (jis & 0x00ff));
     }
newConverter()
QJpUnicodeConv * QJpUnicodeConv::newConverter (int rule) static
Warning
This function is not part of the public interface.
Definition at line 727 of file qjpunicode.cpp.
Referenced by QFontJis0208Codec::QFontJis0208Codec().
 {
     QByteArray env = qgetenv("UNICODEMAP_JP");
     if (rule == Default && !env.isNull()) {
         for (int i = 0; i < (int)env.length();) {
             int j = env.indexOf(',', i);
             QByteArray s;
             if (j < 0) {
                 s = env.mid(i).trimmed();
                 i = env.length();
             } else {
                 s = env.mid(i, j - i).trimmed();
                 i = j + 1;
             }
             if (qstricmp(s, "unicode-0.9") == 0) {
                 rule = (rule & 0xff00) | Unicode;
             } else if (qstricmp(s, "unicode-0201") == 0) {
                 rule = (rule & 0xff00) | Unicode_JISX0201;
             } else if (qstricmp(s, "unicode-ascii") == 0) {
                 rule = (rule & 0xff00) | Unicode_ASCII;
             } else if (qstricmp(s, "jisx0221-1995") == 0) {
                 rule = (rule & 0xff00) | JISX0221_JISX0201;
             } else if ((qstricmp(s, "open-0201") == 0) ||
                        (qstricmp(s, "open-19970715-0201") == 0)) {
                 rule = (rule & 0xff00) | JISX0221_JISX0201;
             } else if ((qstricmp(s, "open-ascii") == 0) ||
                        (qstricmp(s, "open-19970715-ascii") == 0)) {
                 rule = (rule & 0xff00) | JISX0221_ASCII;
             } else if ((qstricmp(s, "open-ms") == 0) ||
                        (qstricmp(s, "open-19970715-ms") == 0)) {
                 rule = (rule & 0xff00) | Microsoft_CP932;
             } else if (qstricmp(s, "cp932") == 0) {
                 rule = (rule & 0xff00) | Microsoft_CP932;
             } else if (qstricmp(s, "jdk1.1.7") == 0) {
                 rule = (rule & 0xff00) | Sun_JDK117;
             } else if (qstricmp(s, "nec-vdc") == 0) {
                 rule = rule | NEC_VDC;
             } else if (qstricmp(s, "ibm-vdc") == 0) {
                 rule = rule | IBM_VDC;
             } else if (qstricmp(s, "udc") == 0) {
                 rule = rule | UDC;
             }
         }
     }
     switch (rule & 0x00ff) {
     case Unicode_JISX0201:
         return new QJpUnicodeConv_Unicode_JISX0201(rule);
     case Unicode_ASCII:
         return new QJpUnicodeConv_Unicode_ASCII(rule);
     case JISX0221_JISX0201:
         return new QJpUnicodeConv_JISX0221_JISX0201(rule);
     case JISX0221_ASCII:
         return new QJpUnicodeConv_JISX0221_ASCII(rule);
     case Sun_JDK117:
         return new QJpUnicodeConv_Sun(rule);
     case Microsoft_CP932:
         return new QJpUnicodeConv_Microsoft(rule);
     default:
         return new QJpUnicodeConv_Unicode_ASCII(rule);
     }
 }
sjisibmvdcToUnicode()
uint QJpUnicodeConv::sjisibmvdcToUnicode (uint h, uint l) const
Definition at line 10499 of file qjpunicode.cpp.
Referenced by QSjisCodec::convertToUnicode(), and unicodeToJisx0212().
 {
     if (((rule & IBM_VDC) || (rule & Microsoft_CP932))  && IsSjisIBMVDCChar1(h))
           return sjis208ibmvdc_unicode[((h - 0x00fa)*189 + (l-0x0040))];
     else
         return 0;
 }
sjisToUnicode() [1/2]
uint QJpUnicodeConv::sjisToUnicode (uint h, uint l) const
Warning
This function is not part of the public interface.
Definition at line 264 of file qjpunicode.cpp.
Referenced by QSjisCodec::convertToUnicode(), sjisToUnicode(), and unicodeToJisx0212().
 {
     if (h == 0) {
         return jisx0201ToUnicode(h, l);
     } else if (IsSjisChar1(h) && IsSjisChar2(l)) {
         return jisx0208ToUnicode(sjisToJisx0208(h, l));
     }
     return 0x0000;
 }
sjisToUnicode() [2/2]
uint QJpUnicodeConv::sjisToUnicode (uint sjis) const inline
Warning
This function is not part of the public interface.
Definition at line 158 of file qjpunicode.h.
{
         return sjisToUnicode((sjis & 0xff00) >> 8, (sjis & 0x00ff));
     }
unicodeToAscii() [1/2]
uint QJpUnicodeConv::unicodeToAscii (uint h, uint l) const virtual
Warning
This function is not part of the public interface.
Reimplemented in QJpUnicodeConv_Sun, and QJpUnicodeConv_JISX0221_JISX0201.
Definition at line 180 of file qjpunicode.cpp.
Referenced by jisx0212ToUnicode(), QJpUnicodeConv_JISX0221_JISX0201::QJpUnicodeConv_JISX0221_JISX0201(), QJpUnicodeConv_Sun::QJpUnicodeConv_Sun(), unicodeToAscii(), QJpUnicodeConv_Sun::unicodeToAscii(), QJpUnicodeConv_JISX0221_ASCII::unicodeToJisx0201Latin(), QJpUnicodeConv_Sun::unicodeToJisx0201Latin(), and QJpUnicodeConv_Microsoft::unicodeToJisx0201Latin().
 {
     if ((h == 0) && (l < 0x80)) {
         return l;
     }
     return 0x0000;
 }
unicodeToAscii() [2/2]
uint QJpUnicodeConv::unicodeToAscii (uint unicode) const inline
Warning
This function is not part of the public interface.
Definition at line 132 of file qjpunicode.h.
{
         return unicodeToAscii((unicode & 0xff00) >> 8, (unicode & 0x00ff));
     }
unicodeToCp932()
uint QJpUnicodeConv::unicodeToCp932 (uint h, uint l) const
Definition at line 10604 of file qjpunicode.cpp.
Referenced by QSjisCodec::convertFromUnicode(), and unicodeToJisx0212().
 {
     if ((rule & Microsoft_CP932)) {
         uint u = (h<<8) | l;
         //since there is no direct mapping, do a linear search
         for (uint i =0; i<sizeof(cp932_87_unicode)/sizeof(short) ; i++) {
            //the table has zeros for some characters
            if (!cp932_87_unicode[i])
                return 0;
            if (u == cp932_87_unicode[i]){
                return ((0x0087<<8) | (0x0040+i));
            }
         }
        for (uint j =0; j<sizeof(cp932_ed_ee_unicode)/sizeof(short) ; j++) {
            if (!cp932_ed_ee_unicode[j])
                return 0;
            if (u==cp932_ed_ee_unicode[j]){
                return (((0x00ed +(j/189))<<8) | (0x0040+(j%189)));
            }
        }
     }
     return 0;
 }
unicodeToJisx0201() [1/2]
uint QJpUnicodeConv::unicodeToJisx0201 (uint h, uint l) const
Warning
This function is not part of the public interface.
Definition at line 189 of file qjpunicode.cpp.
Referenced by QEucJpCodec::convertFromUnicode(), QJisCodec::convertFromUnicode(), QSjisCodec::convertFromUnicode(), jisx0212ToUnicode(), unicodeToJisx0201(), and unicodeToSjis().
 {
     uint jis;
     if ((jis = unicodeToJisx0201Latin(h, l)) != 0) {
         return jis;
     } else if ((jis = unicodeToJisx0201Kana(h, l)) != 0) {
         return jis;
     }
     return 0x0000;
 }
unicodeToJisx0201() [2/2]
uint QJpUnicodeConv::unicodeToJisx0201 (uint unicode) const inline
Warning
This function is not part of the public interface.
Definition at line 135 of file qjpunicode.h.
{
         return unicodeToJisx0201((unicode & 0xff00) >> 8, (unicode & 0x00ff));
     }
unicodeToJisx0201Kana() [1/2]
uint QJpUnicodeConv::unicodeToJisx0201Kana (uint h, uint l) const
Warning
This function is not part of the public interface.
Definition at line 211 of file qjpunicode.cpp.
Referenced by jisx0212ToUnicode(), unicodeToJisx0201(), and unicodeToJisx0201Kana().
 {
     uint jis = unicode11ToJisx0201(h, l);
     if (IsKana(jis)) {
         return jis;
     }
     return 0x0000;
 }
unicodeToJisx0201Kana() [2/2]
uint QJpUnicodeConv::unicodeToJisx0201Kana (uint unicode) const inline
Warning
This function is not part of the public interface.
Definition at line 141 of file qjpunicode.h.
{
         return unicodeToJisx0201Kana((unicode & 0xff00) >> 8, (unicode & 0x00ff));
     }
unicodeToJisx0201Latin() [1/2]
uint QJpUnicodeConv::unicodeToJisx0201Latin (uint h, uint l) const virtual
Warning
This function is not part of the public interface.
Reimplemented in QJpUnicodeConv_Microsoft, QJpUnicodeConv_Sun, and QJpUnicodeConv_JISX0221_ASCII.
Definition at line 201 of file qjpunicode.cpp.
Referenced by jisx0212ToUnicode(), QJpUnicodeConv_JISX0221_ASCII::QJpUnicodeConv_JISX0221_ASCII(), QJpUnicodeConv_Microsoft::QJpUnicodeConv_Microsoft(), QJpUnicodeConv_Sun::QJpUnicodeConv_Sun(), QJpUnicodeConv_JISX0221_JISX0201::unicodeToAscii(), unicodeToJisx0201(), and unicodeToJisx0201Latin().
 {
     uint jis = unicode11ToJisx0201(h, l);
     if (IsLatin(jis)) {
         return jis;
     }
     return 0x0000;
 }
unicodeToJisx0201Latin() [2/2]
uint QJpUnicodeConv::unicodeToJisx0201Latin (uint unicode) const inline
Warning
This function is not part of the public interface.
Definition at line 138 of file qjpunicode.h.
{
         return unicodeToJisx0201Latin((unicode & 0xff00) >> 8, (unicode & 0x00ff));
     }
unicodeToJisx0208() [1/2]
uint QJpUnicodeConv::unicodeToJisx0208 (uint h, uint l) const virtual
Warning
This function is not part of the public interface.
Reimplemented in QJpUnicodeConv_Microsoft, QJpUnicodeConv_Sun, QJpUnicodeConv_JISX0221_ASCII, QJpUnicodeConv_JISX0221_JISX0201, and QJpUnicodeConv_Unicode_ASCII.
Definition at line 221 of file qjpunicode.cpp.
Referenced by QEucJpCodec::convertFromUnicode(), QJisCodec::convertFromUnicode(), jisx0212ToUnicode(), QJpUnicodeConv_JISX0221_ASCII::QJpUnicodeConv_JISX0221_ASCII(), QJpUnicodeConv_JISX0221_JISX0201::QJpUnicodeConv_JISX0221_JISX0201(), QJpUnicodeConv_Microsoft::QJpUnicodeConv_Microsoft(), QJpUnicodeConv_Sun::QJpUnicodeConv_Sun(), QJpUnicodeConv_Unicode_ASCII::QJpUnicodeConv_Unicode_ASCII(), unicodeToJisx0208(), QJpUnicodeConv_Unicode_ASCII::unicodeToJisx0208(), QJpUnicodeConv_JISX0221_JISX0201::unicodeToJisx0208(), QJpUnicodeConv_JISX0221_ASCII::unicodeToJisx0208(), QJpUnicodeConv_Sun::unicodeToJisx0208(), QJpUnicodeConv_Microsoft::unicodeToJisx0208(), QJpUnicodeConv_Unicode_ASCII::unicodeToJisx0212(), and unicodeToSjis().
 {
     if (rule & UDC){
         uint unicode = (h << 8) | l;
         if ((0xe000 <= unicode) && (unicode <= 0xe3ab)) {
             // User Defined Char (mapped to Private Use Area)
             unicode -= 0xe000;
             return ((0x75 + unicode / 0x5e) << 8) | (0x21 + unicode % 0x5e);
         }
     }
     uint jis = unicode11ToJisx0208(h, l);
     if ((rule & NEC_VDC) == 0) {
         if ((0x2d21 <= jis) && (jis <= 0x2d7c)) {
             // NEC Vendor Defined Char
             return 0x0000;
         }
     }
     return jis;
 }
unicodeToJisx0208() [2/2]
uint QJpUnicodeConv::unicodeToJisx0208 (uint unicode) const inline
Warning
This function is not part of the public interface.
Definition at line 144 of file qjpunicode.h.
{
         return unicodeToJisx0208((unicode & 0xff00) >> 8, (unicode & 0x00ff));
     }
unicodeToJisx0212() [1/2]
uint QJpUnicodeConv::unicodeToJisx0212 (uint h, uint l) const virtual
Warning
This function is not part of the public interface.
Reimplemented in QJpUnicodeConv_Microsoft, QJpUnicodeConv_Sun, QJpUnicodeConv_JISX0221_ASCII, and QJpUnicodeConv_Unicode_ASCII.
Definition at line 242 of file qjpunicode.cpp.
Referenced by QEucJpCodec::convertFromUnicode(), QJisCodec::convertFromUnicode(), QSjisCodec::convertFromUnicode(), jisx0212ToUnicode(), QJpUnicodeConv_JISX0221_ASCII::QJpUnicodeConv_JISX0221_ASCII(), QJpUnicodeConv_Microsoft::QJpUnicodeConv_Microsoft(), QJpUnicodeConv_Sun::QJpUnicodeConv_Sun(), QJpUnicodeConv_Unicode_ASCII::QJpUnicodeConv_Unicode_ASCII(), unicodeToJisx0212(), QJpUnicodeConv_JISX0221_ASCII::unicodeToJisx0212(), QJpUnicodeConv_Sun::unicodeToJisx0212(), QJpUnicodeConv_Microsoft::unicodeToJisx0212(), and unicodeToSjis().
 {
     if (rule & UDC){
         uint unicode = (h << 8) | l;
         if ((0xe3ac <= unicode) && (unicode <= 0xe757)) {
             // User Defined Char (mapped to Private Use Area)
             unicode -= 0xe3ac;
             return ((0x75 + unicode / 0x5e) << 8) | (0x21 + unicode % 0x5e);
         }
     }
     uint jis = unicode11ToJisx0212(h, l);
     if ((rule & IBM_VDC) == 0){
         if (((0x7373 <= jis) && (jis <= 0x737e)) ||
             ((0x7421 <= jis) && (jis <= 0x747e))) {
             // IBM Vendor Defined Char
             return 0x0000;
         }
     }
     return jis;
 }
unicodeToJisx0212() [2/2]
uint QJpUnicodeConv::unicodeToJisx0212 (uint unicode) const inline
Warning
This function is not part of the public interface.
Definition at line 147 of file qjpunicode.h.
{
         return unicodeToJisx0212((unicode & 0xff00) >> 8, (unicode & 0x00ff));
     }
unicodeToSjis() [1/2]
uint QJpUnicodeConv::unicodeToSjis (uint h, uint l) const
Warning
This function is not part of the public interface.
Definition at line 275 of file qjpunicode.cpp.
Referenced by QSjisCodec::convertFromUnicode(), unicodeToJisx0212(), and unicodeToSjis().
 {
     uint jis;
     if ((jis = unicodeToJisx0201(h, l)) != 0x0000) {
         return jis;
     } else if ((jis = unicodeToJisx0208(h, l)) != 0x0000) {
         return jisx0208ToSjis(jis);
     } else if ((jis = unicodeToJisx0212(h, l)) != 0x0000) {
         return 0x0000;
     }
     return 0x0000;
 }
unicodeToSjis() [2/2]
uint QJpUnicodeConv::unicodeToSjis (uint unicode) const inline
Warning
This function is not part of the public interface.
Definition at line 161 of file qjpunicode.h.
{
         return unicodeToSjis((unicode & 0xff00) >> 8, (unicode & 0x00ff));
     }
unicodeToSjisibmvdc()
uint QJpUnicodeConv::unicodeToSjisibmvdc (uint h, uint l) const
Definition at line 10507 of file qjpunicode.cpp.
Referenced by QSjisCodec::convertFromUnicode(), and unicodeToJisx0212().
 {
     if ((rule & IBM_VDC) || (rule & Microsoft_CP932)) {
         uint u = (h<<8) | l;
         //since there is no direct mapping, do a linear search
        for (uint i =0; i<sizeof(sjis208ibmvdc_unicode)/sizeof(short) ; i++) {
            //the table has zeros after 0xfc4b
            if (!sjis208ibmvdc_unicode[i])
                return 0;
            if (u==sjis208ibmvdc_unicode[i]){
                return (((0x00fa +(i/189))<<8) | (0x0040+(i%189)));
            }
        }
     }
     return 0;
 }
Properties
rule
int QJpUnicodeConv::rule private
Definition at line 169 of file qjpunicode.h.
Referenced by cp932ToUnicode(), jisx0208ToUnicode(), jisx0212ToUnicode(), sjisibmvdcToUnicode(), unicodeToCp932(), unicodeToJisx0208(), unicodeToJisx0212(), and unicodeToSjisibmvdc().
The documentation for this class was generated from the following files:
/src/plugins/codecs/jp/qjpunicode.h
/src/plugins/codecs/jp/qjpunicode.cpp