Qt 4.8: QPatternist::QNameValue Class Reference
QPatternist::QNameValue Class Reference
Implements the value instance of the xs:QName type.
#include <qqnamevalue_p.h>
Public Types
typedef QExplicitlySharedDataPointer< QNameValue > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
QXmlName qName () const
virtual QString stringValue () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static QNameValue::Ptr fromValue (const NamePool::Ptr &np, const QXmlName name)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Private Functions
QNameValue (const NamePool::Ptr &np, const QXmlName name)
Properties
const NamePool::Ptr m_namePool
const QXmlName m_qName
Friends
class CommonValues
class QNameComparator
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Detailed Description
Implements the value instance of the xs:QName type.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
See also
QNameConstructor::expandQName()
XPathHelper::isQName()
QXmlUtils
Definition at line 73 of file qqnamevalue_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<QNameValue> QPatternist::QNameValue::Ptr
Definition at line 79 of file qqnamevalue_p.h.
Constructors and Destructors
QNameValue()
QNameValue::QNameValue (const NamePool::Ptr & np, const QXmlName name) private
Definition at line 52 of file qqnamevalue.cpp.
Referenced by fromValue(), and qName().
                                                                  : m_qName(name)
                                                                      , m_namePool(np)
 {
     Q_ASSERT(!name.isNull());
     Q_ASSERT(m_namePool);
 }
Functions
fromValue()
QNameValue::Ptr QNameValue::fromValue (const NamePool::Ptr & np, const QXmlName name) static
Constructs a QNameValue that represents name.
Parameters
name the QName. May not be null.
np the NamePool.
See also
QNameConstructor::expandQName()
XPathHelper::isQName()
QXmlUtils
Definition at line 59 of file qqnamevalue.cpp.
Referenced by QPatternist::CastAs::castToQName(), QPatternist::AttributeNameValidator::evaluateSingleton(), QPatternist::NodeNameFN::evaluateSingleton(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::QNameConstructor::evaluateSingleton(), QPatternist::ResolveQNameFN::evaluateSingleton(), QPatternist::XsdTypeChecker::fromLexical(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), and QPatternist::yyparse().
 {
     Q_ASSERT(!name.isNull());
     return QNameValue::Ptr(new QNameValue(np, name));
 }
qName()
QXmlName QPatternist::QNameValue::qName () const inline
Definition at line 96 of file qqnamevalue_p.h.
Referenced by QPatternist::XsdTypeChecker::checkConstrainingFacets(), QPatternist::AttributeConstructor::evaluateSingleton(), QPatternist::AttributeNameValidator::evaluateSingleton(), QPatternist::ElementConstructor::evaluateSingleton(), QPatternist::AttributeConstructor::evaluateToSequenceReceiver(), QPatternist::ElementConstructor::evaluateToSequenceReceiver(), and QPatternist::AtomicValue::toQt().
         {
             return m_qName;
         }
stringValue()
QString QNameValue::stringValue () const virtual
Implements QPatternist::AtomicValue.
Definition at line 65 of file qqnamevalue.cpp.
 {
     return m_namePool->toLexical(m_qName);
 }
type()
ItemType::Ptr QNameValue::type () const virtual
Implements QPatternist::AtomicValue.
Definition at line 70 of file qqnamevalue.cpp.
 {
     return BuiltinTypes::xsQName;
 }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 76 of file qqnamevalue_p.h.
QNameComparator
friend class QNameComparator friend
Definition at line 77 of file qqnamevalue_p.h.
Properties
m_namePool
const NamePool::Ptr QPatternist::QNameValue::m_namePool private
Definition at line 105 of file qqnamevalue_p.h.
Referenced by QNameValue(), and stringValue().
m_qName
const QXmlName QPatternist::QNameValue::m_qName private
Definition at line 104 of file qqnamevalue_p.h.
Referenced by QPatternist::QNameComparator::equals(), qName(), and stringValue().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qqnamevalue_p.h
/src/xmlpatterns/data/qqnamevalue.cpp