Qt 4.8: QPdfEnginePrivate Class Reference
QPdfEnginePrivate Class Reference
#include <qprintengine_pdf_p.h>
Public Functions
int addBrushPattern (const QTransform &matrix, bool *specifyColor, int *gStateObject)
int addConstantAlphaObject (int brushAlpha, int penAlpha=255)
int addImage (const QImage &image, bool *bitmap, qint64 serial_no)
Adds an image to the pdf and return the pdf-object id.
void drawTextItem (const QPointF &p, const QTextItemInt &ti)
int height () const
void newPage ()
QTransform pageMatrix () const
QPdfEnginePrivate (QPrinter::PrinterMode m)
int width () const
void writeHeader ()
void writeTail ()
~QPdfEnginePrivate ()
Public Functions inherited from QPdfBaseEnginePrivate
void closePrintDevice ()
bool openPrintDevice ()
QRect pageRect () const
QRect paperRect () const
QPdfBaseEnginePrivate (QPrinter::PrinterMode m)
uint requestObject ()
~QPdfBaseEnginePrivate ()
Public Functions inherited from QAlphaPaintEnginePrivate
void addAlphaRect (const QRectF &rect)
QRectF addPenWidth (const QPainterPath &path)
void drawAlphaImage (const QRectF &rect)
bool fullyContained (const QRectF &rect) const
QAlphaPaintEnginePrivate ()
void resetState (QPainter *p)
QRect toRect (const QRectF &rect) const
~QAlphaPaintEnginePrivate ()
Public Functions inherited from QPaintEnginePrivate
void drawBoxTextItem (const QPointF &p, const QTextItemInt &ti)
QPaintEnginePrivate ()
void setSystemTransform (const QTransform &xform)
void setSystemViewport (const QRegion &region)
virtual void systemStateChanged ()
void transformSystemClip ()
virtual ~QPaintEnginePrivate ()
Private Functions
int addXrefEntry (int object, bool printostr=true)
void embedFont (QFontSubset *font)
void printString (const QString &string)
void write (const QByteArray &data)
int writeCompressed (const char *src, int len)
int writeCompressed (const QByteArray &data)
int writeCompressed (QIODevice *dev)
void writeFonts ()
int writeImage (const QByteArray &data, int width, int height, int depth, int maskObject, int softMaskObject, bool dct=false)
void writeInfo ()
void writePage ()
void writePageRoot ()
void xprintf (const char *fmt,...)
Properties
QHash< QPair< uint, uint >, uint > alphaCache
int catalog
int graphicsState
QHash< qint64, uint > imageCache
int info
int pageRoot
QVector< uint > pages
int patternColorSpace
QDataStream * stream
int streampos
QVector< int > xrefPositions
Additional Inherited Members
Public Variables inherited from QPdfBaseEnginePrivate
bool allClipped
qreal bottomMargin
QBrush brush
QPointF brushOrigin
bool clipEnabled
QList< QPainterPath > clips
bool collate
QPrinter::ColorMode colorMode
int copies
QString creator
QStringList cupsOptions
QRect cupsPageRect
QRect cupsPaperRect
QString cupsStringPageSize
QString cupsTempFile
int currentObject
QPdfPage * currentPage
QSizeF customPaperSize
QPrinter::DuplexMode duplex
bool embedFonts
int fd
QHash< QFontEngine::FaceId, QFontSubset * > fonts
bool fullPage
bool hasBrush
bool hasCustomPageMargins
bool hasPen
qreal leftMargin
qreal opacity
QPrinter::Orientation orientation
QIODevice * outDevice
QString outputFileName
QPrinter::PageOrder pageOrder
QPrinter::PaperSize paperSize
QPrinter::PaperSource paperSource
QPaintDevice * pdev
QPen pen
bool postscript
QString printerName
QString printProgram
int resolution
qreal rightMargin
QString selectionOption
bool simplePen
QPdf::Stroker stroker
QString title
qreal topMargin
bool useAlphaEngine
Public Variables inherited from QAlphaPaintEnginePrivate
bool m_advancedBrush
bool m_advancedPen
bool m_alphaBrush
bool m_alphaOpacity
bool m_alphaPen
QRegion m_alphargn
QRegion m_cliprgn
bool m_complexTransform
bool m_continueCall
bool m_emulateProjectiveTransforms
bool m_hasalpha
int m_pass
QPaintDevice * m_pdev
QPen m_pen
QPicture * m_pic
QPaintEngine * m_picengine
QPainter * m_picpainter
QPaintEngine::PaintEngineFeatures m_savedcaps
QTransform m_transform
Public Variables inherited from QPaintEnginePrivate
QWidget * currentClipWidget
uint hasSystemTransform: 1
uint hasSystemViewport: 1
QPaintDevice * pdev
QPaintEngine * q_ptr
QRegion systemClip
QRect systemRect
QTransform systemTransform
QRegion systemViewport
Detailed Description
Definition at line 123 of file qprintengine_pdf_p.h.
Constructors and Destructors
QPdfEnginePrivate()
QPdfEnginePrivate::QPdfEnginePrivate (QPrinter::PrinterMode m)
Definition at line 300 of file qprintengine_pdf.cpp.
     : QPdfBaseEnginePrivate(m)
 {
     streampos = 0;
     stream = new QDataStream;
     pageOrder = QPrinter::FirstPageFirst;
     orientation = QPrinter::Portrait;
     fullPage = false;
 }
~QPdfEnginePrivate()
QPdfEnginePrivate::~QPdfEnginePrivate ()
Definition at line 311 of file qprintengine_pdf.cpp.
 {
     delete stream;
 }
Functions
addBrushPattern()
int QPdfEnginePrivate::addBrushPattern (const QTransform & matrix, bool * specifyColor, int * gStateObject)
Definition at line 437 of file qprintengine_pdf.cpp.
 {
     int paintType = 2; // Uncolored tiling
     int w = 8;
     int h = 8;
     *specifyColor = true;
     *gStateObject = 0;
     QTransform matrix = m;
     matrix.translate(brushOrigin.x(), brushOrigin.y());
     matrix = matrix * pageMatrix();
     //qDebug() << brushOrigin << matrix;
     Qt::BrushStyle style = brush.style();
     if (style == Qt::LinearGradientPattern) {// && style <= Qt::ConicalGradientPattern) {
 #ifdef USE_NATIVE_GRADIENTS
         *specifyColor = false;
         return gradientBrush(b, matrix, gStateObject);
 #else
         return 0;
 #endif
     }
     if ((!brush.isOpaque() && brush.style() < Qt::LinearGradientPattern) || opacity != 1.0)
         *gStateObject = addConstantAlphaObject(qRound(brush.color().alpha() * opacity),
                                                qRound(pen.color().alpha() * opacity));
     int imageObject = -1;
     QByteArray pattern = QPdf::patternForBrush(brush);
     if (pattern.isEmpty()) {
         if (brush.style() != Qt::TexturePattern)
             return 0;
         QImage image = brush.texture().toImage();
         bool bitmap = true;
         imageObject = addImage(image, &bitmap, qt_pixmap_id(brush.texture()));
         if (imageObject != -1) {
             QImage::Format f = image.format();
             if (f != QImage::Format_MonoLSB && f != QImage::Format_Mono) {
                 paintType = 1; // Colored tiling
                 *specifyColor = false;
             }
             w = image.width();
             h = image.height();
             QTransform m(w, 0, 0, -h, 0, h);
             QPdf::ByteStream s(&pattern);
             s << QPdf::generateMatrix(m);
             s << "/Im" << imageObject << " Do\n";
         }
     }
     QByteArray str;
     QPdf::ByteStream s(&str);
     s << "<<\n"
         "/Type /Pattern\n"
         "/PatternType 1\n"
         "/PaintType " << paintType << "\n"
         "/TilingType 1\n"
         "/BBox [0 0 " << w << h << "]\n"
         "/XStep " << w << "\n"
         "/YStep " << h << "\n"
         "/Matrix ["
       << matrix.m11()
       << matrix.m12()
       << matrix.m21()
       << matrix.m22()
       << matrix.dx()
       << matrix.dy() << "]\n"
         "/Resources \n<< "; // open resource tree
     if (imageObject > 0) {
         s << "/XObject << /Im" << imageObject << ' ' << imageObject << "0 R >> ";
     }
     s << ">>\n"
         "/Length " << pattern.length() << "\n"
         ">>\n"
         "stream\n"
       << pattern
       << "endstream\n"
         "endobj\n";
     int patternObj = addXrefEntry(-1);
     write(str);
     currentPage->patterns.append(patternObj);
     return patternObj;
 }
addConstantAlphaObject()
int QPdfEnginePrivate::addConstantAlphaObject (int brushAlpha, int penAlpha = 255)
Definition at line 417 of file qprintengine_pdf.cpp.
Referenced by addBrushPattern(), and ~QPdfEnginePrivate().
 {
     if (brushAlpha == 255 && penAlpha == 255)
         return 0;
     int object = alphaCache.value(QPair<uint, uint>(brushAlpha, penAlpha), 0);
     if (!object) {
         object = addXrefEntry(-1);
         QByteArray alphaDef;
         QPdf::ByteStream s(&alphaDef);
         s << "<<\n/ca " << (brushAlpha/qreal(255.)) << '\n';
         s << "/CA " << (penAlpha/qreal(255.)) << "\n>>";
         xprintf("%s\nendobj\n", alphaDef.constData());
         alphaCache.insert(QPair<uint, uint>(brushAlpha, penAlpha), object);
     }
     if (currentPage->graphicStates.indexOf(object) < 0)
         currentPage->graphicStates.append(object);
     return object;
 }
addImage()
int QPdfEnginePrivate::addImage (const QImage & img, bool * bitmap, qint64 serial_no)
Adds an image to the pdf and return the pdf-object id.
Returns -1 if adding the image failed.
Definition at line 526 of file qprintengine_pdf.cpp.
Referenced by addBrushPattern().
 {
     if (img.isNull())
         return -1;
     int object = imageCache.value(serial_no);
     if(object)
         return object;
     QImage image = img;
     QImage::Format format = image.format();
     if (image.depth() == 1 && *bitmap && img.colorTable().size() == 2
         && img.colorTable().at(0) == QColor(Qt::black).rgba()
         && img.colorTable().at(1) == QColor(Qt::white).rgba())
     {
         if (format == QImage::Format_MonoLSB)
             image = image.convertToFormat(QImage::Format_Mono);
         format = QImage::Format_Mono;
     } else {
         *bitmap = false;
         if (format != QImage::Format_RGB32 && format != QImage::Format_ARGB32) {
             image = image.convertToFormat(QImage::Format_ARGB32);
             format = QImage::Format_ARGB32;
         }
     }
     int w = image.width();
     int h = image.height();
     int d = image.depth();
     if (format == QImage::Format_Mono) {
         int bytesPerLine = (w + 7) >> 3;
         QByteArray data;
         data.resize(bytesPerLine * h);
         char *rawdata = data.data();
         for (int y = 0; y < h; ++y) {
             memcpy(rawdata, image.scanLine(y), bytesPerLine);
             rawdata += bytesPerLine;
         }
         object = writeImage(data, w, h, d, 0, 0);
     } else {
         QByteArray softMaskData;
         bool dct = false;
         QByteArray imageData;
         bool hasAlpha = false;
         bool hasMask = false;
         if (QImageWriter::supportedImageFormats().contains("jpeg") && colorMode != QPrinter::GrayScale) {
             QBuffer buffer(&imageData);
             QImageWriter writer(&buffer, "jpeg");
             writer.setQuality(94);
             writer.write(image);
             dct = true;
             if (format != QImage::Format_RGB32) {
                 softMaskData.resize(w * h);
                 uchar *sdata = (uchar *)softMaskData.data();
                 for (int y = 0; y < h; ++y) {
                     const QRgb *rgb = (const QRgb *)image.scanLine(y);
                     for (int x = 0; x < w; ++x) {
                         uchar alpha = qAlpha(*rgb);
                         *sdata++ = alpha;
                         hasMask |= (alpha < 255);
                         hasAlpha |= (alpha != 0 && alpha != 255);
                         ++rgb;
                     }
                 }
             }
         } else {
             imageData.resize(colorMode == QPrinter::GrayScale ? w * h : 3 * w * h);
             uchar *data = (uchar *)imageData.data();
             softMaskData.resize(w * h);
             uchar *sdata = (uchar *)softMaskData.data();
             for (int y = 0; y < h; ++y) {
                 const QRgb *rgb = (const QRgb *)image.scanLine(y);
                 if (colorMode == QPrinter::GrayScale) {
                     for (int x = 0; x < w; ++x) {
                         *(data++) = qGray(*rgb);
                         uchar alpha = qAlpha(*rgb);
                         *sdata++ = alpha;
                         hasMask |= (alpha < 255);
                         hasAlpha |= (alpha != 0 && alpha != 255);
                         ++rgb;
                     }
                 } else {
                     for (int x = 0; x < w; ++x) {
                         *(data++) = qRed(*rgb);
                         *(data++) = qGreen(*rgb);
                         *(data++) = qBlue(*rgb);
                         uchar alpha = qAlpha(*rgb);
                         *sdata++ = alpha;
                         hasMask |= (alpha < 255);
                         hasAlpha |= (alpha != 0 && alpha != 255);
                         ++rgb;
                     }
                 }
             }
             if (format == QImage::Format_RGB32)
                 hasAlpha = hasMask = false;
         }
         int maskObject = 0;
         int softMaskObject = 0;
         if (hasAlpha) {
             softMaskObject = writeImage(softMaskData, w, h, 8, 0, 0);
         } else if (hasMask) {
             // dither the soft mask to 1bit and add it. This also helps PDF viewers
             // without transparency support
             int bytesPerLine = (w + 7) >> 3;
             QByteArray mask(bytesPerLine * h, 0);
             uchar *mdata = (uchar *)mask.data();
             const uchar *sdata = (const uchar *)softMaskData.constData();
             for (int y = 0; y < h; ++y) {
                 for (int x = 0; x < w; ++x) {
                     if (*sdata)
                         mdata[x>>3] |= (0x80 >> (x&7));
                     ++sdata;
                 }
                 mdata += bytesPerLine;
             }
             maskObject = writeImage(mask, w, h, 1, 0, 0);
         }
         object = writeImage(imageData, w, h, colorMode == QPrinter::GrayScale ? 8 : 32,
                             maskObject, softMaskObject, dct);
     }
     imageCache.insert(serial_no, object);
     return object;
 }
addXrefEntry()
int QPdfEnginePrivate::addXrefEntry (int object, bool printostr = true) private
Definition at line 1212 of file qprintengine_pdf.cpp.
Referenced by addBrushPattern(), addConstantAlphaObject(), drawTextItem(), embedFont(), writeHeader(), writeImage(), writeInfo(), writePage(), writePageRoot(), writeTail(), and ~QPdfEnginePrivate().
 {
     if (object < 0)
         object = requestObject();
     if (object>=xrefPositions.size())
         xrefPositions.resize(object+1);
     xrefPositions[object] = streampos;
     if (printostr)
         xprintf("%d 0 obj\n",object);
     return object;
 }
drawTextItem()
void QPdfEnginePrivate::drawTextItem (const QPointF & p, const QTextItemInt & ti) virtual
Reimplemented from QPdfBaseEnginePrivate.
Definition at line 654 of file qprintengine_pdf.cpp.
 {
     if (ti.charFormat.isAnchor()) {
         qreal size = ti.fontEngine->fontDef.pixelSize;
 #ifdef Q_WS_WIN
         if (ti.fontEngine->type() == QFontEngine::Win) {
             QFontEngineWin *fe = static_cast<QFontEngineWin *>(ti.fontEngine);
             size = fe->tm.tmHeight;
         }
 #endif
         int synthesized = ti.fontEngine->synthesized();
         qreal stretch = synthesized & QFontEngine::SynthesizedStretch ? ti.fontEngine->fontDef.stretch/100. : 1.;
         QTransform trans;
         // Build text rendering matrix (Trm). We need it to map the text area to user
         // space units on the PDF page.
         trans = QTransform(size*stretch, 0, 0, size, 0, 0);
         // Apply text matrix (Tm).
         trans *= QTransform(1,0,0,-1,p.x(),p.y());
         // Apply page displacement (Identity for first page).
         trans *= stroker.matrix;
         // Apply Current Transformation Matrix (CTM)
         trans *= pageMatrix();
         qreal x1, y1, x2, y2;
         trans.map(0, 0, &x1, &y1);
         trans.map(ti.width.toReal()/size, (ti.ascent.toReal()-ti.descent.toReal())/size, &x2, &y2);
         uint annot = addXrefEntry(-1);
         QByteArray x1s, y1s, x2s, y2s;
         x1s.setNum(static_cast<double>(x1), 'f');
         y1s.setNum(static_cast<double>(y1), 'f');
         x2s.setNum(static_cast<double>(x2), 'f');
         y2s.setNum(static_cast<double>(y2), 'f');
         QByteArray rectData = x1s + ' ' + y1s + ' ' + x2s + ' ' + y2s;
         xprintf("<<\n/Type /Annot\n/Subtype /Link\n/Rect [");
         xprintf(rectData.constData());
 #ifdef Q_DEBUG_PDF_LINKS
         xprintf("]\n/Border [16 16 1]\n/A <<\n");
 #else
         xprintf("]\n/Border [0 0 0]\n/A <<\n");
 #endif
         xprintf("/Type /Action\n/S /URI\n/URI (%s)\n",
                 ti.charFormat.anchorHref().toLatin1().constData());
         xprintf(">>\n>>\n");
         xprintf("endobj\n");
         if (!currentPage->annotations.contains(annot)) {
             currentPage->annotations.append(annot);
         }
     }
     QPdfBaseEnginePrivate::drawTextItem(p, ti);
 }
embedFont()
void QPdfEnginePrivate::embedFont (QFontSubset * font) private
Definition at line 983 of file qprintengine_pdf.cpp.
Referenced by writeFonts().
 {
     //qDebug() << "embedFont" << font->object_id;
     int fontObject = font->object_id;
     QByteArray fontData = font->toTruetype();
 #ifdef FONT_DUMP
     static int i = 0;
     QString fileName("font%1.ttf");
     fileName = fileName.arg(i++);
     QFile ff(fileName);
     ff.open(QFile::WriteOnly);
     ff.write(fontData);
     ff.close();
 #endif
     int fontDescriptor = requestObject();
     int fontstream = requestObject();
     int cidfont = requestObject();
     int toUnicode = requestObject();
     QFontEngine::Properties properties = font->fontEngine->properties();
     {
         qreal scale = 1000/properties.emSquare.toReal();
         addXrefEntry(fontDescriptor);
         QByteArray descriptor;
         QPdf::ByteStream s(&descriptor);
         s << "<< /Type /FontDescriptor\n"
             "/FontName /Q";
         int tag = fontDescriptor;
         for (int i = 0; i < 5; ++i) {
             s << (char)('A' + (tag % 26));
             tag /= 26;
         }
         s <<  '+' << properties.postscriptName << "\n"
             "/Flags " << 4 << "\n"
             "/FontBBox ["
           << properties.boundingBox.x()*scale
           << -(properties.boundingBox.y() + properties.boundingBox.height())*scale
           << (properties.boundingBox.x() + properties.boundingBox.width())*scale
           << -properties.boundingBox.y()*scale  << "]\n"
             "/ItalicAngle " << properties.italicAngle.toReal() << "\n"
             "/Ascent " << properties.ascent.toReal()*scale << "\n"
             "/Descent " << -properties.descent.toReal()*scale << "\n"
             "/CapHeight " << properties.capHeight.toReal()*scale << "\n"
             "/StemV " << properties.lineWidth.toReal()*scale << "\n"
             "/FontFile2 " << fontstream << "0 R\n"
             ">> endobj\n";
         write(descriptor);
     }
     {
         addXrefEntry(fontstream);
         QByteArray header;
         QPdf::ByteStream s(&header);
         int length_object = requestObject();
         s << "<<\n"
             "/Length1 " << fontData.size() << "\n"
             "/Length " << length_object << "0 R\n";
         if (do_compress)
             s << "/Filter /FlateDecode\n";
         s << ">>\n"
             "stream\n";
         write(header);
         int len = writeCompressed(fontData);
         write("endstream\n"
               "endobj\n");
         addXrefEntry(length_object);
         xprintf("%d\n"
                 "endobj\n", len);
     }
     {
         addXrefEntry(cidfont);
         QByteArray cid;
         QPdf::ByteStream s(&cid);
         s << "<< /Type /Font\n"
             "/Subtype /CIDFontType2\n"
             "/BaseFont /" << properties.postscriptName << "\n"
             "/CIDSystemInfo << /Registry (Adobe) /Ordering (Identity) /Supplement 0 >>\n"
             "/FontDescriptor " << fontDescriptor << "0 R\n"
             "/CIDToGIDMap /Identity\n"
           << font->widthArray() <<
             ">>\n"
             "endobj\n";
         write(cid);
     }
     {
         addXrefEntry(toUnicode);
         QByteArray touc = font->createToUnicodeMap();
         xprintf("<< /Length %d >>\n"
                 "stream\n", touc.length());
         write(touc);
         write("endstream\n"
               "endobj\n");
     }
     {
         addXrefEntry(fontObject);
         QByteArray font;
         QPdf::ByteStream s(&font);
         s << "<< /Type /Font\n"
             "/Subtype /Type0\n"
             "/BaseFont /" << properties.postscriptName << "\n"
             "/Encoding /Identity-H\n"
             "/DescendantFonts [" << cidfont << "0 R]\n"
             "/ToUnicode " << toUnicode << "0 R"
             ">>\n"
             "endobj\n";
         write(font);
     }
 }
height()
int QPdfEnginePrivate::height () const inline
Definition at line 136 of file qprintengine_pdf_p.h.
Referenced by newPage(), and pageMatrix().
{
         QRect r = paperRect();
         return qRound(r.height()*72./resolution);
     }
newPage()
void QPdfEnginePrivate::newPage ()
Definition at line 719 of file qprintengine_pdf.cpp.
 {
     if (currentPage && currentPage->pageSize.isEmpty())
         currentPage->pageSize = QSize(width(), height());
     writePage();
     delete currentPage;
     currentPage = new QPdfPage;
     currentPage->pageSize = QSize(width(), height());
     stroker.stream = currentPage;
     pages.append(requestObject());
     *currentPage << "/GSa gs /CSp cs /CSp CS\n"
                  << QPdf::generateMatrix(pageMatrix())
                  << "q q\n";
 }
pageMatrix()
QTransform QPdfEnginePrivate::pageMatrix () const
Definition at line 708 of file qprintengine_pdf.cpp.
Referenced by addBrushPattern(), drawTextItem(), and newPage().
 {
     qreal scale = 72./resolution;
     QTransform tmp(scale, 0.0, 0.0, -scale, 0.0, height());
     if (!fullPage) {
         QRect r = pageRect();
         tmp.translate(r.left(), r.top());
     }
     return tmp;
 }
printString()
void QPdfEnginePrivate::printString (const QString & string) private
Definition at line 1227 of file qprintengine_pdf.cpp.
Referenced by writeInfo().
{
     // The 'text string' type in PDF is encoded either as PDFDocEncoding, or
     // Unicode UTF-16 with a Unicode byte order mark as the first character
     // (0xfeff), with the high-order byte first.
     QByteArray array("(\xfe\xff");
     const ushort *utf16 = string.utf16();
     for (int i=0; i < string.size(); ++i) {
         char part[2] = {char((*(utf16 + i)) >> 8), char((*(utf16 + i)) & 0xff)};
         for(int j=0; j < 2; ++j) {
             if (part[j] == '(' || part[j] == ')' || part[j] == '\\')
                 array.append('\\');
             array.append(part[j]);
         }
     }
     array.append(")");
     write(array);
 }
width()
int QPdfEnginePrivate::width () const inline
Definition at line 132 of file qprintengine_pdf_p.h.
Referenced by newPage().
                       {
         QRect r = paperRect();
         return qRound(r.width()*72./resolution);
     }
write()
void QPdfEnginePrivate::write (const QByteArray & data) inline private
Definition at line 175 of file qprintengine_pdf_p.h.
Referenced by addBrushPattern(), embedFont(), printString(), writeImage(), and ~QPdfEnginePrivate().
{
         stream->writeRawData(data.constData(), data.size());
         streampos += data.size();
     }
writeCompressed() [1/3]
int QPdfEnginePrivate::writeCompressed (const char * src, int len) private
Definition at line 832 of file qprintengine_pdf.cpp.
Referenced by embedFont(), writeImage(), and writePage().
 {
 #ifndef QT_NO_COMPRESS
     if(do_compress) {
         uLongf destLen = len + len/100 + 13; // zlib requirement
         Bytef* dest = new Bytef[destLen];
         if (Z_OK == ::compress(dest, &destLen, (const Bytef*) src, (uLongf)len)) {
             stream->writeRawData((const char*)dest, destLen);
         } else {
             qWarning("QPdfStream::writeCompressed: Error in compress()");
             destLen = 0;
         }
         delete [] dest;
         len = destLen;
     } else
 #endif
     {
         stream->writeRawData(src,len);
     }
     streampos += len;
     return len;
 }
writeCompressed() [2/3]
int QPdfEnginePrivate::writeCompressed (const QByteArray & data) inline private
Definition at line 181 of file qprintengine_pdf_p.h.
Referenced by writeCompressed().
 { return writeCompressed(data.constData(), data.length()); }
writeCompressed() [3/3]
int QPdfEnginePrivate::writeCompressed (QIODevice * dev) private
Definition at line 758 of file qprintengine_pdf.cpp.
 {
 #ifndef QT_NO_COMPRESS
     if (do_compress) {
         int size = QPdfPage::chunkSize();
         int sum = 0;
         ::z_stream zStruct;
         zStruct.zalloc = Z_NULL;
         zStruct.zfree = Z_NULL;
         zStruct.opaque = Z_NULL;
         if (::deflateInit(&zStruct, Z_DEFAULT_COMPRESSION) != Z_OK) {
             qWarning("QPdfStream::writeCompressed: Error in deflateInit()");
             return sum;
         }
         zStruct.avail_in = 0;
         QByteArray in, out;
         out.resize(size);
         while (!dev->atEnd() || zStruct.avail_in != 0) {
             if (zStruct.avail_in == 0) {
                 in = dev->read(size);
                 zStruct.avail_in = in.size();
                 zStruct.next_in = reinterpret_cast<unsigned char*>(in.data());
                 if (in.size() <= 0) {
                     qWarning("QPdfStream::writeCompressed: Error in read()");
                     ::deflateEnd(&zStruct);
                     return sum;
                 }
             }
             zStruct.next_out = reinterpret_cast<unsigned char*>(out.data());
             zStruct.avail_out = out.size();
             if (::deflate(&zStruct, 0) != Z_OK) {
                 qWarning("QPdfStream::writeCompressed: Error in deflate()");
                 ::deflateEnd(&zStruct);
                 return sum;
             }
             int written = out.size() - zStruct.avail_out;
             stream->writeRawData(out.constData(), written);
             streampos += written;
             sum += written;
         }
         int ret;
         do {
             zStruct.next_out = reinterpret_cast<unsigned char*>(out.data());
             zStruct.avail_out = out.size();
             ret = ::deflate(&zStruct, Z_FINISH);
             if (ret != Z_OK && ret != Z_STREAM_END) {
                 qWarning("QPdfStream::writeCompressed: Error in deflate()");
                 ::deflateEnd(&zStruct);
                 return sum;
             }
             int written = out.size() - zStruct.avail_out;
             stream->writeRawData(out.constData(), written);
             streampos += written;
             sum += written;
         } while (ret == Z_OK);
         ::deflateEnd(&zStruct);
         return sum;
     } else
 #endif
     {
         QByteArray arr;
         int sum = 0;
         while (!dev->atEnd()) {
             arr = dev->read(QPdfPage::chunkSize());
             stream->writeRawData(arr.constData(), arr.size());
             streampos += arr.size();
             sum += arr.size();
         }
         return sum;
     }
 }
writeFonts()
void QPdfEnginePrivate::writeFonts () private
Definition at line 1095 of file qprintengine_pdf.cpp.
Referenced by writeTail().
 {
     for (QHash<QFontEngine::FaceId, QFontSubset *>::iterator it = fonts.begin(); it != fonts.end(); ++it) {
         embedFont(*it);
         delete *it;
     }
     fonts.clear();
 }
writeHeader()
void QPdfEnginePrivate::writeHeader ()
Definition at line 903 of file qprintengine_pdf.cpp.
 {
     addXrefEntry(0,false);
     xprintf("%%PDF-1.4\n");
     writeInfo();
     catalog = addXrefEntry(-1);
     pageRoot = requestObject();
     xprintf("<<\n"
             "/Type /Catalog\n"
             "/Pages %d 0 R\n"
             ">>\n"
             "endobj\n", pageRoot);
     // graphics state
     graphicsState = addXrefEntry(-1);
     xprintf("<<\n"
             "/Type /ExtGState\n"
             "/SA true\n"
             "/SM 0.02\n"
             "/ca 1.0\n"
             "/CA 1.0\n"
             "/AIS false\n"
             "/SMask /None"
             ">>\n"
             "endobj\n");
     // color space for pattern
     patternColorSpace = addXrefEntry(-1);
     xprintf("[/Pattern /DeviceRGB]\n"
             "endobj\n");
 }
writeImage()
int QPdfEnginePrivate::writeImage (const QByteArray & data, int width, int height, int depth, int maskObject, int softMaskObject, bool dct = false) private
Definition at line 855 of file qprintengine_pdf.cpp.
Referenced by addImage().
 {
     int image = addXrefEntry(-1);
     xprintf("<<\n"
             "/Type /XObject\n"
             "/Subtype /Image\n"
             "/Width %d\n"
             "/Height %d\n", width, height);
     if (depth == 1) {
         xprintf("/ImageMask true\n"
                 "/Decode [1 0]\n");
     } else {
         xprintf("/BitsPerComponent 8\n"
                 "/ColorSpace %s\n", (depth == 32) ? "/DeviceRGB" : "/DeviceGray");
     }
     if (maskObject > 0)
         xprintf("/Mask %d 0 R\n", maskObject);
     if (softMaskObject > 0)
         xprintf("/SMask %d 0 R\n", softMaskObject);
     int lenobj = requestObject();
     xprintf("/Length %d 0 R\n", lenobj);
     if (interpolateImages)
         xprintf("/Interpolate true\n");
     int len = 0;
     if (dct) {
         //qDebug() << "DCT";
         xprintf("/Filter /DCTDecode\n>>\nstream\n");
         write(data);
         len = data.length();
     } else {
         if (do_compress)
             xprintf("/Filter /FlateDecode\n>>\nstream\n");
         else
             xprintf(">>\nstream\n");
         len = writeCompressed(data);
     }
     xprintf("endstream\n"
             "endobj\n");
     addXrefEntry(lenobj);
     xprintf("%d\n"
             "endobj\n", len);
     return image;
 }
writeInfo()
void QPdfEnginePrivate::writeInfo () private
Definition at line 938 of file qprintengine_pdf.cpp.
Referenced by writeHeader().
 {
     info = addXrefEntry(-1);
     xprintf("<<\n/Title ");
     printString(title);
     xprintf("\n/Creator ");
     printString(creator);
     xprintf("\n/Producer ");
     printString(QString::fromLatin1("Qt " QT_VERSION_STR));
     QDateTime now = QDateTime::currentDateTime().toUTC();
     QTime t = now.time();
     QDate d = now.date();
     xprintf("\n/CreationDate (D:%d%02d%02d%02d%02d%02d)\n",
             d.year(),
             d.month(),
             d.day(),
             t.hour(),
             t.minute(),
             t.second());
     xprintf(">>\n"
             "endobj\n");
 }
writePage()
void QPdfEnginePrivate::writePage () private
Definition at line 1104 of file qprintengine_pdf.cpp.
Referenced by newPage(), and writeTail().
 {
     if (pages.empty())
         return;
     *currentPage << "Q Q\n";
     uint pageStream = requestObject();
     uint pageStreamLength = requestObject();
     uint resources = requestObject();
     uint annots = requestObject();
     addXrefEntry(pages.last());
     xprintf("<<\n"
             "/Type /Page\n"
             "/Parent %d 0 R\n"
             "/Contents %d 0 R\n"
             "/Resources %d 0 R\n"
             "/Annots %d 0 R\n"
             "/MediaBox [0 0 %d %d]\n"
             ">>\n"
             "endobj\n",
             pageRoot, pageStream, resources, annots,
             // make sure we use the pagesize from when we started the page, since the user may have changed it
             currentPage->pageSize.width(), currentPage->pageSize.height());
     addXrefEntry(resources);
     xprintf("<<\n"
             "/ColorSpace <<\n"
             "/PCSp %d 0 R\n"
             "/CSp /DeviceRGB\n"
             "/CSpg /DeviceGray\n"
             ">>\n"
             "/ExtGState <<\n"
             "/GSa %d 0 R\n",
             patternColorSpace, graphicsState);
     for (int i = 0; i < currentPage->graphicStates.size(); ++i)
         xprintf("/GState%d %d 0 R\n", currentPage->graphicStates.at(i), currentPage->graphicStates.at(i));
     xprintf(">>\n");
     xprintf("/Pattern <<\n");
     for (int i = 0; i < currentPage->patterns.size(); ++i)
         xprintf("/Pat%d %d 0 R\n", currentPage->patterns.at(i), currentPage->patterns.at(i));
     xprintf(">>\n");
     xprintf("/Font <<\n");
     for (int i = 0; i < currentPage->fonts.size();++i)
         xprintf("/F%d %d 0 R\n", currentPage->fonts[i], currentPage->fonts[i]);
     xprintf(">>\n");
     xprintf("/XObject <<\n");
     for (int i = 0; i<currentPage->images.size(); ++i) {
         xprintf("/Im%d %d 0 R\n", currentPage->images.at(i), currentPage->images.at(i));
     }
     xprintf(">>\n");
     xprintf(">>\n"
             "endobj\n");
     addXrefEntry(annots);
     xprintf("[ ");
     for (int i = 0; i<currentPage->annotations.size(); ++i) {
         xprintf("%d 0 R ", currentPage->annotations.at(i));
     }
     xprintf("]\nendobj\n");
     addXrefEntry(pageStream);
     xprintf("<<\n"
             "/Length %d 0 R\n", pageStreamLength); // object number for stream length object
     if (do_compress)
         xprintf("/Filter /FlateDecode\n");
     xprintf(">>\n");
     xprintf("stream\n");
     QIODevice *content = currentPage->stream();
     int len = writeCompressed(content);
     xprintf("endstream\n"
             "endobj\n");
     addXrefEntry(pageStreamLength);
     xprintf("%d\nendobj\n",len);
 }
writePageRoot()
void QPdfEnginePrivate::writePageRoot () private
Definition at line 961 of file qprintengine_pdf.cpp.
Referenced by writeTail().
 {
     addXrefEntry(pageRoot);
     xprintf("<<\n"
             "/Type /Pages\n"
             "/Kids \n"
             "[\n");
     int size = pages.size();
     for (int i = 0; i < size; ++i)
         xprintf("%d 0 R\n", pages[i]);
     xprintf("]\n");
     //xprintf("/Group <</S /Transparency /I true /K false>>\n");
     xprintf("/Count %d\n", pages.size());
     xprintf("/ProcSet [/PDF /Text /ImageB /ImageC]\n"
             ">>\n"
             "endobj\n");
 }
writeTail()
void QPdfEnginePrivate::writeTail ()
Definition at line 1188 of file qprintengine_pdf.cpp.
 {
     writePage();
     writeFonts();
     writePageRoot();
     addXrefEntry(xrefPositions.size(),false);
     xprintf("xref\n"
             "0 %d\n"
             "%010d 65535 f \n", xrefPositions.size()-1, xrefPositions[0]);
     for (int i = 1; i < xrefPositions.size()-1; ++i)
         xprintf("%010d 00000 n \n", xrefPositions[i]);
     xprintf("trailer\n"
             "<<\n"
             "/Size %d\n"
             "/Info %d 0 R\n"
             "/Root %d 0 R\n"
             ">>\n"
             "startxref\n%d\n"
             "%%%%EOF\n",
             xrefPositions.size()-1, info, catalog, xrefPositions.last());
 }
xprintf()
void QPdfEnginePrivate::xprintf (const char * fmt, ...) private
Definition at line 738 of file qprintengine_pdf.cpp.
Referenced by addConstantAlphaObject(), addXrefEntry(), drawTextItem(), embedFont(), writeHeader(), writeImage(), writeInfo(), writePage(), writePageRoot(), writeTail(), and ~QPdfEnginePrivate().
 {
     if (!stream)
         return;
     const int msize = 10000;
     char buf[msize];
     va_list args;
     va_start(args, fmt);
     int bufsize = qvsnprintf(buf, msize, fmt, args);
     Q_ASSERT(bufsize<msize);
     va_end(args);
     stream->writeRawData(buf, bufsize);
     streampos += bufsize;
 }
Properties
alphaCache
QHash<QPair<uint, uint>, uint > QPdfEnginePrivate::alphaCache private
Definition at line 188 of file qprintengine_pdf_p.h.
Referenced by addConstantAlphaObject().
catalog
int QPdfEnginePrivate::catalog private
Definition at line 185 of file qprintengine_pdf_p.h.
Referenced by writeHeader(), and writeTail().
graphicsState
int QPdfEnginePrivate::graphicsState private
Definition at line 185 of file qprintengine_pdf_p.h.
Referenced by writeHeader(), and writePage().
imageCache
QHash<qint64, uint> QPdfEnginePrivate::imageCache private
Definition at line 187 of file qprintengine_pdf_p.h.
Referenced by addImage().
info
int QPdfEnginePrivate::info private
Definition at line 185 of file qprintengine_pdf_p.h.
Referenced by writeInfo(), and writeTail().
pageRoot
int QPdfEnginePrivate::pageRoot private
Definition at line 185 of file qprintengine_pdf_p.h.
Referenced by writeHeader(), writePage(), and writePageRoot().
pages
QVector<uint> QPdfEnginePrivate::pages private
Definition at line 186 of file qprintengine_pdf_p.h.
Referenced by newPage(), writePage(), and writePageRoot().
patternColorSpace
int QPdfEnginePrivate::patternColorSpace private
Definition at line 185 of file qprintengine_pdf_p.h.
Referenced by writeHeader(), and writePage().
stream
QDataStream* QPdfEnginePrivate::stream private
Definition at line 165 of file qprintengine_pdf_p.h.
Referenced by QPdfEnginePrivate(), writeCompressed(), xprintf(), and ~QPdfEnginePrivate().
streampos
int QPdfEnginePrivate::streampos private
Definition at line 166 of file qprintengine_pdf_p.h.
Referenced by addXrefEntry(), QPdfEnginePrivate(), writeCompressed(), and xprintf().
xrefPositions
QVector<int> QPdfEnginePrivate::xrefPositions private
Definition at line 164 of file qprintengine_pdf_p.h.
Referenced by addXrefEntry(), and writeTail().
The documentation for this class was generated from the following files:
/src/gui/painting/qprintengine_pdf_p.h
/src/gui/painting/qprintengine_pdf.cpp