Qt 4.8: QNetworkCacheMetaData Class Reference
QNetworkCacheMetaData Class Reference
The QNetworkCacheMetaData class provides cache information.
#include <qabstractnetworkcache.h>
Public Types
typedef QHash< QNetworkRequest::Attribute, QVariant > AttributesMap
Synonym for QHash<QNetworkRequest::Attribute, QVariant>
typedef QPair< QByteArray, QByteArray > RawHeader
Synonym for QPair<QByteArray, QByteArray>
typedef QList< RawHeader > RawHeaderList
Synonym for QList<RawHeader>
Public Functions
AttributesMap attributes () const
Returns all the attributes stored with this cache item.
QDateTime expirationDate () const
Returns the date and time when the meta data expires.
bool isValid () const
Returns true if this network cache meta data has attributes that have been set otherwise false.
QDateTime lastModified () const
Returns the date and time when the meta data was last modified.
bool operator!= (const QNetworkCacheMetaData &other) const
Returns true if this meta data is not equal to the other meta data; otherwise returns false.
QNetworkCacheMetaData & operator= (const QNetworkCacheMetaData &other)
Makes a copy of the other QNetworkCacheMetaData and returns a reference to the copy.
bool operator== (const QNetworkCacheMetaData &other) const
Returns true if this meta data is equal to the other meta data; otherwise returns false.
QNetworkCacheMetaData ()
Constructs an invalid network cache meta data.
QNetworkCacheMetaData (const QNetworkCacheMetaData &other)
Constructs a copy of the other QNetworkCacheMetaData.
RawHeaderList rawHeaders () const
Returns a list of all raw headers that are set in this meta data.
bool saveToDisk () const
Returns is this cache should be allowed to be stored on disk.
void setAttributes (const AttributesMap &attributes)
Sets all attributes of this cache item to be the map attributes.
void setExpirationDate (const QDateTime &dateTime)
Sets the date and time when the meta data expires to dateTime.
void setLastModified (const QDateTime &dateTime)
Sets the date and time when the meta data was last modified to dateTime.
void setRawHeaders (const RawHeaderList &headers)
Sets the raw headers to list.
void setSaveToDisk (bool allow)
Sets whether this network cache meta data and associated content should be allowed to be stored on disk to allow.
void setUrl (const QUrl &url)
Sets the URL this network cache meta data to to be url.
QUrl url () const
Returns the URL this network cache meta data is referring to.
~QNetworkCacheMetaData ()
Destroys the network cache meta data.
Properties
QSharedDataPointer< QNetworkCacheMetaDataPrivate > d
Friends
class QNetworkCacheMetaDataPrivate
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &out, const QNetworkCacheMetaData &metaData)
Writes metaData to the out stream.
QDataStream & operator>> (QDataStream &in, QNetworkCacheMetaData &metaData)
Reads a QNetworkCacheMetaData from the stream in into metaData.
Detailed Description
The QNetworkCacheMetaData class provides cache information.
Since
4.5
Attention
Module: QtNetwork
QNetworkCacheMetaData provides information about a cache file including the url, when it was last modified, when the cache file was created, headers for file and if the file should be saved onto a disk.
See also
QAbstractNetworkCache
Definition at line 62 of file qabstractnetworkcache.h.
Typedefs
AttributesMap
QNetworkCacheMetaData::AttributesMap
Synonym for QHash<QNetworkRequest::Attribute, QVariant>
Definition at line 68 of file qabstractnetworkcache.h.
RawHeader
QNetworkCacheMetaData::RawHeader
Synonym for QPair<QByteArray, QByteArray>
Definition at line 66 of file qabstractnetworkcache.h.
RawHeaderList
QNetworkCacheMetaData::RawHeaderList
Synonym for QList<RawHeader>
Definition at line 67 of file qabstractnetworkcache.h.
Constructors and Destructors
QNetworkCacheMetaData() [1/2]
QNetworkCacheMetaData::QNetworkCacheMetaData ()
Constructs an invalid network cache meta data.
See also
isValid()
Definition at line 123 of file qabstractnetworkcache.cpp.
     : d(new QNetworkCacheMetaDataPrivate)
 {
 }
QNetworkCacheMetaData() [2/2]
QNetworkCacheMetaData::QNetworkCacheMetaData (const QNetworkCacheMetaData & other)
Constructs a copy of the other QNetworkCacheMetaData.
Definition at line 139 of file qabstractnetworkcache.cpp.
     : d(other.d)
 {
 }
~QNetworkCacheMetaData()
QNetworkCacheMetaData::~QNetworkCacheMetaData ()
Destroys the network cache meta data.
Definition at line 131 of file qabstractnetworkcache.cpp.
 {
     // QSharedDataPointer takes care of freeing d
 }
Functions
attributes()
QNetworkCacheMetaData::AttributesMap QNetworkCacheMetaData::attributes () const
Returns all the attributes stored with this cache item.
Since
4.6
See also
setAttributes(), QNetworkRequest::Attribute
Definition at line 301 of file qabstractnetworkcache.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData(), QNetworkReplyImplPrivate::initCacheSaveDevice(), QNetworkCacheMetaDataPrivate::save(), QNetworkAccessCacheBackend::sendCacheContents(), QNetworkAccessHttpBackend::sendCacheContents(), and setAttributes().
 {
     return d->attributes;
 }
expirationDate()
QDateTime QNetworkCacheMetaData::expirationDate () const
Returns the date and time when the meta data expires.
Definition at line 278 of file qabstractnetworkcache.cpp.
Referenced by QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), and QNetworkCacheMetaDataPrivate::save().
 {
     return d->expirationDate;
 }
isValid()
bool QNetworkCacheMetaData::isValid () const
Returns true if this network cache meta data has attributes that have been set otherwise false.
Definition at line 181 of file qabstractnetworkcache.cpp.
Referenced by QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QNetworkDiskCache::prepare(), QNetworkAccessCacheBackend::sendCacheContents(), and QNetworkAccessHttpBackend::sendCacheContents().
 {
     return !(*d == *metadata_shared_invalid());
 }
lastModified()
QDateTime QNetworkCacheMetaData::lastModified () const
Returns the date and time when the meta data was last modified.
Definition at line 262 of file qabstractnetworkcache.cpp.
Referenced by QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), and QNetworkCacheMetaDataPrivate::save().
 {
     return d->lastModified;
 }
operator!=()
bool QNetworkCacheMetaData::operator!= (const QNetworkCacheMetaData & other) const inline
Returns true if this meta data is not equal to the other meta data; otherwise returns false.
See also
operator==()
Definition at line 76 of file qabstractnetworkcache.h.
         { return !(*this == other); }
operator=()
QNetworkCacheMetaData & QNetworkCacheMetaData::operator= (const QNetworkCacheMetaData & other)
Makes a copy of the other QNetworkCacheMetaData and returns a reference to the copy.
Definition at line 147 of file qabstractnetworkcache.cpp.
 {
     d = other.d;
     return *this;
 }
operator==()
bool QNetworkCacheMetaData::operator== (const QNetworkCacheMetaData & other) const
Returns true if this meta data is equal to the other meta data; otherwise returns false.
See also
operator!=()
Definition at line 158 of file qabstractnetworkcache.cpp.
 {
     if (d == other.d)
         return true;
     if (d && other.d)
         return *d == *other.d;
     return false;
 }
rawHeaders()
QNetworkCacheMetaData::RawHeaderList QNetworkCacheMetaData::rawHeaders () const
Returns a list of all raw headers that are set in this meta data.
The list is in the same order that the headers were set.
See also
setRawHeaders()
Definition at line 244 of file qabstractnetworkcache.cpp.
Referenced by QCacheItem::canCompress(), QNetworkAccessHttpBackend::fetchCacheMetaData(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QNetworkDiskCache::prepare(), QNetworkAccessHttpBackend::replyDownloadMetaData(), QNetworkCacheMetaDataPrivate::save(), QNetworkAccessCacheBackend::sendCacheContents(), and QNetworkAccessHttpBackend::sendCacheContents().
 {
     return d->headers;
 }
saveToDisk()
bool QNetworkCacheMetaData::saveToDisk () const
Returns is this cache should be allowed to be stored on disk.
Some cache implementations can keep these cache items in memory for performance reasons, but for security reasons they should not be written to disk.
Specifically with http, documents marked with Pragma: no-cache, or have a Cache-control set to no-store or no-cache or any https document that doesn't have "Cache-control: public" set will set the saveToDisk to false.
See also
setSaveToDisk()
Definition at line 198 of file qabstractnetworkcache.cpp.
Referenced by QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QNetworkDiskCache::prepare(), QNetworkCacheMetaDataPrivate::save(), and QNetworkDiskCachePrivate::storeItem().
 {
     return d->saveToDisk;
 }
setAttributes()
void QNetworkCacheMetaData::setAttributes (const AttributesMap & attributes)
Sets all attributes of this cache item to be the map attributes.
Since
4.6
See also
attributes(), QNetworkRequest::setAttribute()
Definition at line 316 of file qabstractnetworkcache.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData(), and QNetworkReplyImplPrivate::initCacheSaveDevice().
 {
     d->attributes = attributes;
 }
setExpirationDate()
void QNetworkCacheMetaData::setExpirationDate (const QDateTime & dateTime)
Sets the date and time when the meta data expires to dateTime.
Definition at line 286 of file qabstractnetworkcache.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData().
 {
     d->expirationDate = dateTime;
 }
setLastModified()
void QNetworkCacheMetaData::setLastModified (const QDateTime & dateTime)
Sets the date and time when the meta data was last modified to dateTime.
Definition at line 270 of file qabstractnetworkcache.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData().
 {
     d->lastModified = dateTime;
 }
setRawHeaders()
void QNetworkCacheMetaData::setRawHeaders (const RawHeaderList & list)
Sets the raw headers to list.
See also
rawHeaders()
Definition at line 254 of file qabstractnetworkcache.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData().
 {
     d->headers = list;
 }
setSaveToDisk()
void QNetworkCacheMetaData::setSaveToDisk (bool allow)
Sets whether this network cache meta data and associated content should be allowed to be stored on disk to allow.
See also
saveToDisk()
Definition at line 209 of file qabstractnetworkcache.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData().
 {
     d->saveToDisk = allow;
 }
setUrl()
void QNetworkCacheMetaData::setUrl (const QUrl & url)
Sets the URL this network cache meta data to to be url.
The password and fragment are removed from the url.
See also
url()
Definition at line 231 of file qabstractnetworkcache.cpp.
Referenced by QNetworkReplyImplPrivate::initCacheSaveDevice().
 {
     d->url = url;
     d->url.setPassword(QString());
     d->url.setFragment(QString());
 }
url()
QUrl QNetworkCacheMetaData::url () const
Returns the URL this network cache meta data is referring to.
See also
setUrl()
Definition at line 219 of file qabstractnetworkcache.cpp.
Referenced by QNetworkDiskCache::prepare(), QNetworkDiskCache::remove(), QNetworkCacheMetaDataPrivate::save(), setUrl(), QNetworkDiskCachePrivate::storeItem(), and QNetworkDiskCache::updateMetaData().
 {
     return d->url;
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & out, const QNetworkCacheMetaData & metaData) related
Writes metaData to the out stream.
Since
4.5
See also
{Serializing Qt Data Types}
Definition at line 332 of file qabstractnetworkcache.cpp.
 {
     QNetworkCacheMetaDataPrivate::save(out, metaData);
     return out;
 }
operator>>()
QDataStream & operator>> (QDataStream & in, QNetworkCacheMetaData & metaData) related
Reads a QNetworkCacheMetaData from the stream in into metaData.
Since
4.5
See also
{Serializing Qt Data Types}
Definition at line 373 of file qabstractnetworkcache.cpp.
 {
     QNetworkCacheMetaDataPrivate::load(in, metaData);
     return in;
 }
QNetworkCacheMetaDataPrivate
friend class QNetworkCacheMetaDataPrivate friend
Definition at line 100 of file qabstractnetworkcache.h.
Properties
d
QSharedDataPointer<QNetworkCacheMetaDataPrivate> QNetworkCacheMetaData::d private
Definition at line 101 of file qabstractnetworkcache.h.
Referenced by attributes(), expirationDate(), isValid(), lastModified(), QNetworkCacheMetaDataPrivate::load(), operator=(), operator==(), rawHeaders(), saveToDisk(), setAttributes(), setExpirationDate(), setLastModified(), setRawHeaders(), setSaveToDisk(), setUrl(), and url().
The documentation for this class was generated from the following files:
/src/network/access/qabstractnetworkcache.h
/src/network/access/qabstractnetworkcache.cpp