Qt 4.8: QXmlStreamNamespaceDeclaration Class Reference
QXmlStreamNamespaceDeclaration Class Reference
The QXmlStreamNamespaceDeclaration class represents a namespace declaration.
#include <qxmlstream.h>
Public Functions
QStringRef namespaceUri () const
Returns the namespaceUri.
bool operator!= (const QXmlStreamNamespaceDeclaration &other) const
Compares this namespace declaration with other and returns true if they are not equal; otherwise returns false.
QXmlStreamNamespaceDeclaration & operator= (const QXmlStreamNamespaceDeclaration &)
Assigns other to this namespace declaration.
bool operator== (const QXmlStreamNamespaceDeclaration &other) const
Compares this namespace declaration with other and returns true if they are equal; otherwise returns false.
QStringRef prefix () const
Returns the prefix.
QXmlStreamNamespaceDeclaration ()
Creates an empty namespace declaration.
QXmlStreamNamespaceDeclaration (const QXmlStreamNamespaceDeclaration &)
Creates a copy of other.
QXmlStreamNamespaceDeclaration (const QString &prefix, const QString &namespaceUri)
Creates a namespace declaration with prefix and namespaceUri.
~QXmlStreamNamespaceDeclaration ()
Destructs this namespace declaration.
Properties
QXmlStreamStringRef m_namespaceUri
QXmlStreamStringRef m_prefix
void * reserved
Friends
class QXmlStreamReaderPrivate
Related Functions
(Note that these are not member functions.)
QXmlStreamNamespaceDeclarations
Synonym for QVector<QXmlStreamNamespaceDeclaration>.
Detailed Description
The QXmlStreamNamespaceDeclaration class represents a namespace declaration.
Since
4.3
Note
This class or function is reentrant.
An namespace declaration consists of a prefix() and a namespaceUri().
Definition at line 204 of file qxmlstream.h.
Constructors and Destructors
QXmlStreamNamespaceDeclaration() [1/3]
QXmlStreamNamespaceDeclaration::QXmlStreamNamespaceDeclaration ()
Creates an empty namespace declaration.
Definition at line 2643 of file qxmlstream.cpp.
 {
 }
QXmlStreamNamespaceDeclaration() [2/3]
QXmlStreamNamespaceDeclaration::QXmlStreamNamespaceDeclaration (const QXmlStreamNamespaceDeclaration & other)
Creates a copy of other.
Definition at line 2664 of file qxmlstream.cpp.
 {
     *this = other;
 }
QXmlStreamNamespaceDeclaration() [3/3]
QXmlStreamNamespaceDeclaration::QXmlStreamNamespaceDeclaration (const QString & prefix, const QString & namespaceUri)
Creates a namespace declaration with prefix and namespaceUri.
Since
4.4
Definition at line 2655 of file qxmlstream.cpp.
 {
     m_prefix = prefix;
     m_namespaceUri = namespaceUri;
 }
~QXmlStreamNamespaceDeclaration()
QXmlStreamNamespaceDeclaration::~QXmlStreamNamespaceDeclaration ()
Destructs this namespace declaration.
Definition at line 2681 of file qxmlstream.cpp.
 {
 }
Functions
namespaceUri()
QStringRef QXmlStreamNamespaceDeclaration::namespaceUri () const inline
Returns the namespaceUri.
Definition at line 216 of file qxmlstream.h.
Referenced by QXmlStreamReader::addExtraNamespaceDeclaration(), operator==(), QPatternist::XSLTTokenizer::queueNamespaceDeclarations(), QPatternist::NamespaceSupport::setPrefixes(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), and QXmlStreamWriter::writeCurrentToken().
 { return m_namespaceUri; }
operator!=()
bool QXmlStreamNamespaceDeclaration::operator!= (const QXmlStreamNamespaceDeclaration & other) const inline
Compares this namespace declaration with other and returns true if they are not equal; otherwise returns false.
Definition at line 220 of file qxmlstream.h.
         { return !operator==(other); }
operator=()
QXmlStreamNamespaceDeclaration & QXmlStreamNamespaceDeclaration::operator= (const QXmlStreamNamespaceDeclaration & other)
Assigns other to this namespace declaration.
Definition at line 2672 of file qxmlstream.cpp.
 {
     m_prefix = other.m_prefix;
     m_namespaceUri = other.m_namespaceUri;
     return *this;
 }
operator==()
bool QXmlStreamNamespaceDeclaration::operator== (const QXmlStreamNamespaceDeclaration & other) const inline
Compares this namespace declaration with other and returns true if they are equal; otherwise returns false.
Definition at line 217 of file qxmlstream.h.
{
         return (prefix() == other.prefix() && namespaceUri() == other.namespaceUri());
     }
prefix()
QStringRef QXmlStreamNamespaceDeclaration::prefix () const inline
Returns the prefix.
Definition at line 215 of file qxmlstream.h.
Referenced by QXmlStreamReader::addExtraNamespaceDeclaration(), operator==(), QPatternist::XSLTTokenizer::queueNamespaceDeclarations(), QPatternist::NamespaceSupport::setPrefixes(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), and QXmlStreamWriter::writeCurrentToken().
 { return m_prefix; }
Friends and Related Functions
QXmlStreamNamespaceDeclarations()
QXmlStreamNamespaceDeclarations related
Synonym for QVector<QXmlStreamNamespaceDeclaration>.
QXmlStreamReaderPrivate
friend class QXmlStreamReaderPrivate friend
Definition at line 208 of file qxmlstream.h.
Properties
m_namespaceUri
QXmlStreamStringRef QXmlStreamNamespaceDeclaration::m_namespaceUri private
Definition at line 205 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolvePublicNamespaces().
m_prefix
QXmlStreamStringRef QXmlStreamNamespaceDeclaration::m_prefix private
Definition at line 205 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolvePublicNamespaces().
reserved
void* QXmlStreamNamespaceDeclaration::reserved private
Definition at line 206 of file qxmlstream.h.
The documentation for this class was generated from the following files:
/src/corelib/xml/qxmlstream.h
/src/corelib/xml/qxmlstream.cpp