Qt 4.8: QGridBox Class Reference
QGridBox Class Reference
Public Functions
Qt::Alignment alignment () const
Qt::Orientations expandingDirections () const
bool hasHeightForWidth () const
int heightForWidth (int w) const
int hStretch ()
bool isEmpty () const
QLayoutItem * item ()
QSize maximumSize () const
QSize minimumSize () const
QGridBox (QLayoutItem *lit)
QGridBox (const QLayout *l, QWidget *wid)
void setAlignment (Qt::Alignment a)
void setGeometry (const QRect &r)
QSize sizeHint () const
QLayoutItem * takeItem ()
int vStretch ()
~QGridBox ()
Private Functions
int toCol (int cc) const
int toRow (int rr) const
Properties
int col
QLayoutItem * item_
int row
int tocol
int torow
Friends
class QGridLayout
class QGridLayoutPrivate
Detailed Description
Definition at line 67 of file qgridlayout.cpp.
Constructors and Destructors
QGridBox() [1/2]
QGridBox::QGridBox (QLayoutItem * lit) inline
Definition at line 70 of file qgridlayout.cpp.
 { item_ = lit; }
QGridBox() [2/2]
QGridBox::QGridBox (const QLayout * l, QWidget * wid) inline
Definition at line 72 of file qgridlayout.cpp.
 { item_ = QLayoutPrivate::createWidgetItem(l, wid); }
~QGridBox()
QGridBox::~QGridBox () inline
Definition at line 73 of file qgridlayout.cpp.
 { delete item_; }
Functions
alignment()
Qt::Alignment QGridBox::alignment () const inline
Definition at line 86 of file qgridlayout.cpp.
 { return item_->alignment(); }
expandingDirections()
Qt::Orientations QGridBox::expandingDirections () const inline
Definition at line 78 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::addData().
 { return item_->expandingDirections(); }
hasHeightForWidth()
bool QGridBox::hasHeightForWidth () const inline
Definition at line 81 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::addHfwData(), QGridLayoutPrivate::setupHfwLayoutData(), and QGridLayoutPrivate::setupLayoutData().
 { return item_->hasHeightForWidth(); }
heightForWidth()
int QGridBox::heightForWidth (int w) const inline
Definition at line 82 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::addHfwData(), and QGridLayoutPrivate::setupHfwLayoutData().
 { return item_->heightForWidth(w); }
hStretch()
int QGridBox::hStretch () inline
Definition at line 90 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::addData(), and QGridLayoutPrivate::setupLayoutData().
                    { return item_->widget() ?
                          item_->widget()->sizePolicy().horizontalStretch() : 0; }
isEmpty()
bool QGridBox::isEmpty () const inline
Definition at line 79 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::addData().
 { return item_->isEmpty(); }
item()
QLayoutItem* QGridBox::item () inline
Definition at line 87 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::addData(), QGridLayoutPrivate::effectiveMargins(), QGridLayout::itemAtPosition(), and QGridLayoutPrivate::setupSpacings().
 { return item_; }
maximumSize()
QSize QGridBox::maximumSize () const inline
Definition at line 77 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::setupLayoutData().
 { return item_->maximumSize(); }
minimumSize()
QSize QGridBox::minimumSize () const inline
Definition at line 76 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::addHfwData(), QGridLayoutPrivate::setupHfwLayoutData(), and QGridLayoutPrivate::setupLayoutData().
 { return item_->minimumSize(); }
setAlignment()
void QGridBox::setAlignment (Qt::Alignment a) inline
Definition at line 84 of file qgridlayout.cpp.
Referenced by QGridLayout::addItem(), QGridLayout::addLayout(), and QGridLayout::addWidget().
 { item_->setAlignment(a); }
setGeometry()
void QGridBox::setGeometry (const QRect & r) inline
Definition at line 85 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::distribute().
 { item_->setGeometry(r); }
sizeHint()
QSize QGridBox::sizeHint () const inline
Definition at line 75 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::addHfwData(), QGridLayoutPrivate::setupHfwLayoutData(), and QGridLayoutPrivate::setupLayoutData().
 { return item_->sizeHint(); }
takeItem()
QLayoutItem* QGridBox::takeItem () inline
Definition at line 88 of file qgridlayout.cpp.
 { QLayoutItem *i = item_; item_ = 0; return i; }
toCol()
int QGridBox::toCol (int cc) const inline private
Definition at line 100 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::distribute(), QGridLayoutPrivate::effectiveMargins(), QGridLayoutPrivate::getItemPosition(), QGridLayoutPrivate::setupHfwLayoutData(), and QGridLayoutPrivate::setupLayoutData().
 { return tocol >= 0 ? tocol : cc - 1; }
toRow()
int QGridBox::toRow (int rr) const inline private
Definition at line 99 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::distribute(), QGridLayoutPrivate::effectiveMargins(), QGridLayoutPrivate::getItemPosition(), QGridLayoutPrivate::setupHfwLayoutData(), and QGridLayoutPrivate::setupLayoutData().
 { return torow >= 0 ? torow : rr - 1; }
vStretch()
int QGridBox::vStretch () inline
Definition at line 92 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::addData(), QGridLayoutPrivate::setupHfwLayoutData(), and QGridLayoutPrivate::setupLayoutData().
                    { return item_->widget() ?
                          item_->widget()->sizePolicy().verticalStretch() : 0; }
Friends and Related Functions
QGridLayout
friend class QGridLayout friend
Definition at line 97 of file qgridlayout.cpp.
QGridLayoutPrivate
friend class QGridLayoutPrivate friend
Definition at line 96 of file qgridlayout.cpp.
Properties
col
int QGridBox::col private
Definition at line 103 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::add(), QGridLayoutPrivate::addData(), QGridLayoutPrivate::distribute(), QGridLayoutPrivate::effectiveMargins(), QGridLayoutPrivate::getItemPosition(), QGridLayout::itemAtPosition(), QGridLayoutPrivate::setupHfwLayoutData(), and QGridLayoutPrivate::setupLayoutData().
item_
QLayoutItem* QGridBox::item_ private
Definition at line 102 of file qgridlayout.cpp.
row
int QGridBox::row private
Definition at line 103 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::add(), QGridLayoutPrivate::addData(), QGridLayoutPrivate::addHfwData(), QGridLayoutPrivate::distribute(), QGridLayoutPrivate::effectiveMargins(), QGridLayoutPrivate::getItemPosition(), QGridLayout::itemAtPosition(), QGridLayoutPrivate::setupHfwLayoutData(), and QGridLayoutPrivate::setupLayoutData().
tocol
int QGridBox::tocol private
Definition at line 104 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::add().
torow
int QGridBox::torow private
Definition at line 104 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::add().
The documentation for this class was generated from the following file:
/src/gui/kernel/qgridlayout.cpp