Qt 4.8: QAxFactory Class Reference
QAxFactory Class Reference abstract
The QAxFactory class defines a factory for the creation of COM components.
#include <qaxfactory.h>
Public Types
enum ServerType { SingleInstance, MultipleInstances }
This enum specifies the different types of servers that can be started with startServer.
Public Functions
virtual QUuid appID () const
Reimplement this function to return the ActiveX server's application identifier.
virtual QUuid classID (const QString &key) const
Reimplement this function to return the class identifier for each key returned by the featureList() implementation, or an empty QUuid if this factory doesn't support the value of key.
virtual QObject * createObject (const QString &key)=0
Reimplement this function to return a new object for key, or 0 if this factory doesn't support the value of key.
virtual bool createObjectWrapper (QObject *object, IDispatch **wrapper)
Reimplement this function to provide the COM object for object in wrapper.
virtual QUuid eventsID (const QString &key) const
Reimplement this function to return the identifier of the event interface for each key returned by the featureList() implementation, or an empty QUuid if this factory doesn't support the value of key.
virtual QString exposeToSuperClass (const QString &key) const
Reimplement this function to return the name of the super class of key up to which methods and properties should be exposed by the ActiveX control.
virtual QStringList featureList () const =0
Reimplement this function to return a list of the widgets (class names) supported by this factory.
virtual bool hasStockEvents (const QString &key) const
Reimplement this function to return true if the ActiveX control key should support the standard ActiveX events.
virtual QUuid interfaceID (const QString &key) const
Reimplement this function to return the interface identifier for each key returned by the featureList() implementation, or an empty QUuid if this factory doesn't support the value of key.
virtual bool isService () const
Reimplement this function to return true if the server is running as a persistent service (e.g.
virtual const QMetaObject * metaObject (const QString &key) const =0
Reimplement this function to return the QMetaObject corresponding to key, or 0 if this factory doesn't support the value of key.
QAxFactory (const QUuid &libId, const QUuid &appId)
Constructs a QAxFactory object that returns libid and appid in the implementation of the respective interface functions.
virtual void registerClass (const QString &key, QSettings *) const
Registers additional values for the class key in the system registry using the settings object.
virtual bool stayTopLevel (const QString &key) const
Reimplement this function to return true if the ActiveX control key should be a top level window, e.g.
virtual QUuid typeLibID () const
Reimplement this function to return the ActiveX server's type library identifier.
virtual void unregisterClass (const QString &key, QSettings *) const
Unregisters any additional values for the class key from the system registry using the settings object.
virtual bool validateLicenseKey (const QString &key, const QString &licenseKey) const
Reimplement this function to return true if licenseKey is a valid license for the class key, or if the current machine is licensed.
virtual ~QAxFactory ()
Destroys the QAxFactory object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool isServer ()
Returns true if the application has been started (by COM) as an ActiveX server, otherwise returns false.
static bool registerActiveObject (QObject *object)
Registers the QObject object with COM as a running object, and returns true if the registration succeeded, otherwise returns false.
static QString serverDirPath ()
Returns the directory that contains the server binary.
static QString serverFilePath ()
Returns the file path of the server binary.
static bool startServer (ServerType type=MultipleInstances)
Starts the COM server with type and returns true if successful, otherwise returns false.
static bool stopServer ()
Stops the COM server and returns true if successful, otherwise returns false.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Properties
QUuid app
QUuid typelib
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAxFactory class defines a factory for the creation of COM components.
Attention
Module: QAxServer
Implement this factory once in your COM server to provide information about the components the server can create. Subclass QAxFactory and implement the pure virtual functions in any implementation file (e.g. main.cpp), and export the factory using the QAXFACTORY_EXPORT() macro.
QStringList ActiveQtFactory::featureList() const
{
    QStringList list;
    list << "ActiveX1";
    list << "ActiveX2";
    return list;
}
QObject *ActiveQtFactory::createObject(const QString &key)
{
    if (key == "ActiveX1")
        return new ActiveX1(parent);
    if (key == "ActiveX2")
        return new ActiveX2(parent);
    return 0;
}
const QMetaObject *ActiveQtFactory::metaObject(const QString &key) const
{
    if (key == "ActiveX1")
        return &ActiveX1::staticMetaObject;
    if (key == "ActiveX2")
        return &ActiveX2::staticMetaObject;
}
QUuid ActiveQtFactory::classID(const QString &key) const
{
    if (key == "ActiveX1")
        return "{01234567-89AB-CDEF-0123-456789ABCDEF}";
    ...
    return QUuid();
}
QUuid ActiveQtFactory::interfaceID(const QString &key) const
{
    if (key == "ActiveX1")
        return "{01234567-89AB-CDEF-0123-456789ABCDEF}";
    ...
    return QUuid();
}
QUuid ActiveQtFactory::eventsID(const QString &key) const
{
    if (key == "ActiveX1")
        return "{01234567-89AB-CDEF-0123-456789ABCDEF}";
    ...
    return QUuid();
}
QAXFACTORY_EXPORT(
    ActiveQtFactory,                  // factory class
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // type library ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}"  // application ID
)
If you use the Q_CLASSINFO() macro to provide the unique identifiers or other attributes for your class you can use the QAXFACTORY_BEGIN(), QAXCLASS() and QAXFACTORY_END() macros to expose one or more classes as COM objects.
QAXFACTORY_BEGIN(
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // type library ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}"  // application ID
)
    QAXCLASS(Class1)
    QAXCLASS(Class2)
QAXFACTORY_END()
If your server supports just a single COM object, you can use a default factory implementation through the QAXFACTORY_DEFAULT() macro.
#include <qapplication.h>
#include <qaxfactory.h>
#include "theactivex.h"
QAXFACTORY_DEFAULT(
    TheActiveX,               // widget class
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // class ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // interface ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // event interface ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // type library ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}"  // application ID
)
Only one QAxFactory implementation may be instantiated and exported by an ActiveX server application. This instance is accessible through the global qAxFactory() function.
A factory can also reimplement the registerClass() and unregisterClass() functions to set additional flags for an ActiveX control in the registry. To limit the number of methods or properties a widget class exposes from its parent classes reimplement exposeToSuperClass().
See also
QAxAggregated, QAxBindable, {ActiveQt Framework}
Definition at line 64 of file qaxfactory.h.
Enumerations
ServerType
enum QAxFactory::ServerType
This enum specifies the different types of servers that can be started with startServer.
SingleInstance The server process can create only one instance of each exported class. COM starts a new process for each request. This is typically used in servers that export only one creatable class.
MultipleInstances The server can create multiple instances of each exported class. This is the default. All instances will live in the same thread, and will share static resources.
Enumerator
SingleInstance
MultipleInstances
Definition at line 93 of file qaxfactory.h.
                     {
         SingleInstance,
         MultipleInstances
     };
Constructors and Destructors
QAxFactory()
QAxFactory::QAxFactory (const QUuid & libId, const QUuid & appId)
Constructs a QAxFactory object that returns libid and appid in the implementation of the respective interface functions.
Definition at line 103 of file qaxfactory.cpp.
 : typelib(libid), app(appid)
 {
 }
~QAxFactory()
QAxFactory::~QAxFactory () virtual
Destroys the QAxFactory object.
Definition at line 111 of file qaxfactory.cpp.
 {
 }
Functions
appID()
QUuid QAxFactory::appID () const virtual
Reimplement this function to return the ActiveX server's application identifier.
Definition at line 138 of file qaxfactory.cpp.
Referenced by DumpIDL(), and UpdateRegistry().
 {
     return app;
 }
classID()
QUuid QAxFactory::classID (const QString & key) const virtual
Reimplement this function to return the class identifier for each key returned by the featureList() implementation, or an empty QUuid if this factory doesn't support the value of key.
The default implementation interprets key as the class name, and returns the value of the Q_CLASSINFO() entry "ClassID".
Definition at line 191 of file qaxfactory.cpp.
Referenced by ActiveObject::ActiveObject(), classIDL(), QAxServerBase::GetClassID(), QAxServerBase::GetUserClassID(), qax_startServer(), and QClassFactory::QClassFactory().
 {
     const QMetaObject *mo = metaObject(key);
     if (!mo)
         return QUuid();
     QString id = QString::fromLatin1(mo->classInfo(mo->indexOfClassInfo("ClassID")).value());
     return QUuid(id);
 }
createObject()
QObject * QAxFactory::createObject (const QString & key) pure virtual
Reimplement this function to return a new object for key, or 0 if this factory doesn't support the value of key.
If the object returned is a QWidget it will be exposed as an ActiveX control, otherwise the returned object will be exposed as a simple COM object.
Implemented in QAxClass< T >.
Referenced by QAxServerBase::internalCreate().
createObjectWrapper()
bool QAxFactory::createObjectWrapper (QObject * object, IDispatch ** wrapper) virtual
Reimplement this function to provide the COM object for object in wrapper.
Return true if the function was successful; otherwise return false.
The default implementation creates a generic automation wrapper based on the meta object information of object.
Definition at line 478 of file qaxserverbase.cpp.
Referenced by ActiveObject::ActiveObject(), qax_create_object_wrapper(), and QVariantToVARIANT().
 {
     *wrapper = 0;
     QAxServerBase *obj = new QAxServerBase(object);
     obj->QueryInterface(IID_IDispatch, (void**)wrapper);
     if (*wrapper)
     return true;
     delete obj;
     return false;
 }
eventsID()
QUuid QAxFactory::eventsID (const QString & key) const virtual
Reimplement this function to return the identifier of the event interface for each key returned by the featureList() implementation, or an empty QUuid if this factory doesn't support the value of key.
The default implementation interprets key as the class name, and returns the value of the Q_CLASSINFO() entry "EventsID".
Definition at line 228 of file qaxfactory.cpp.
Referenced by classIDL(), QAxServerBase::GetGUID(), QAxServerBase::internalConnect(), and QAxServerBase::qt_metacall().
 {
     const QMetaObject *mo = metaObject(key);
     if (!mo)
         return QUuid();
     QString id = QString::fromLatin1(mo->classInfo(mo->indexOfClassInfo("EventsID")).value());
     return QUuid(id);
 }
exposeToSuperClass()
QString QAxFactory::exposeToSuperClass (const QString & key) const virtual
Reimplement this function to return the name of the super class of key up to which methods and properties should be exposed by the ActiveX control.
The default implementation interprets key as the class name, and returns the value of the Q_CLASSINFO() entry "ToSuperClass". If no such value is set the null-string is returned, and the functions and properties of all the super classes including QWidget will be exposed.
To only expose the functions and properties of the class itself, reimplement this function to return key.
Definition at line 317 of file qaxfactory.cpp.
Referenced by classIDL().
 {
     const QMetaObject *mo = metaObject(key);
     if (!mo)
         return QString();
     return QString::fromLatin1(mo->classInfo(mo->indexOfClassInfo("ToSuperClass")).value());
 }
featureList()
QStringList QAxFactory::featureList () const pure virtual
Reimplement this function to return a list of the widgets (class names) supported by this factory.
Implemented in QAxClass< T >.
Referenced by qax_startServer(), qax_stopServer(), qAxFactory(), and QClassFactory::QClassFactory().
hasStockEvents()
bool QAxFactory::hasStockEvents (const QString & key) const virtual
Reimplement this function to return true if the ActiveX control key should support the standard ActiveX events.
Click
DblClick
KeyDown
KeyPress
KeyUp
MouseDown
MouseUp
MouseMove
The default implementation interprets key as the class name, and returns true if the value of the Q_CLASSINFO() entry "StockEvents" is "yes". Otherwise this function returns false.
Definition at line 353 of file qaxfactory.cpp.
Referenced by classIDL(), and QAxServerBase::internalCreate().
 {
     const QMetaObject *mo = metaObject(key);
     if (!mo)
         return false;
     return QString::fromLatin1(mo->classInfo(mo->indexOfClassInfo("StockEvents")).value()) == QLatin1String("yes");
 }
interfaceID()
QUuid QAxFactory::interfaceID (const QString & key) const virtual
Reimplement this function to return the interface identifier for each key returned by the featureList() implementation, or an empty QUuid if this factory doesn't support the value of key.
The default implementation interprets key as the class name, and returns the value of the Q_CLASSINFO() entry "InterfaceID".
Definition at line 209 of file qaxfactory.cpp.
Referenced by classIDL().
 {
     const QMetaObject *mo = metaObject(key);
     if (!mo)
         return QUuid();
     QString id = QString::fromLatin1(mo->classInfo(mo->indexOfClassInfo("InterfaceID")).value());
     return QUuid(id);
 }
isServer()
bool QAxFactory::isServer () static
Returns true if the application has been started (by COM) as an ActiveX server, otherwise returns false.
int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    if (!QAxFactory::isServer()) {
        // initialize for stand-alone execution
    }
    return app.exec();
}
Definition at line 371 of file qaxfactory.cpp.
 {
     return qAxIsServer;
 }
isService()
bool QAxFactory::isService () const virtual
Reimplement this function to return true if the server is running as a persistent service (e.g.
an NT service) and should not terminate even when all objects provided have been released.
The default implementation returns false.
Definition at line 410 of file qaxfactory.cpp.
Referenced by qax_startServer().
 {
     return false;
 }
metaObject()
const QMetaObject * QAxFactory::metaObject (const QString & key) const pure virtual
Reimplement this function to return the QMetaObject corresponding to key, or 0 if this factory doesn't support the value of key.
Implemented in QAxClass< T >.
Referenced by convertTypes(), QClassFactory::CreateInstanceHelper(), QClassFactory::GetLicInfo(), QAxServerBase::InternalQueryInterface(), and QClassFactory::QClassFactory().
registerActiveObject()
bool QAxFactory::registerActiveObject (QObject * object) static
Registers the QObject object with COM as a running object, and returns true if the registration succeeded, otherwise returns false.
The object is unregistered automatically when it is destroyed.
This function should only be called if the application has been started by the user (i.e. not by COM to respond to a request), and only for one object, usually the toplevel object of the application's object hierarchy.
This function does nothing and returns false if the object's class info for "RegisterObject" is not set to "yes", or if the server is an in-process server.
Definition at line 512 of file qaxfactory.cpp.
 {
     if (qstricmp(object->metaObject()->classInfo(object->metaObject()->indexOfClassInfo("RegisterObject")).value(), "yes"))
         return false;
     if (!QString::fromWCharArray(qAxModuleFilename).toLower().endsWith(QLatin1String(".exe")))
     return false;
     ActiveObject *active = new ActiveObject(object, qAxFactory());
     if (!active->wrapper || !active->cookie) {
         delete active;
         return false;
     }
     return true;
 }
registerClass()
void QAxFactory::registerClass (const QString & key, QSettings * settings) const virtual
Registers additional values for the class key in the system registry using the settings object.
The standard values have already been registered by the framework, but additional values, e.g. implemented categories, can be added in an implementation of this function.
settings->setValue("/CLSID/" + classID(key)
                   + "/Implemented Categories/"
                   + "/{00000000-0000-0000-000000000000}/.",
                   QString());
If you reimplement this function you must also reimplement unregisterClass() to remove the additional registry values.
See also
QSettings
Definition at line 252 of file qaxfactory.cpp.
 {
     Q_UNUSED(key);
     Q_UNUSED(settings)
 }
serverDirPath()
QString QAxFactory::serverDirPath () static
Returns the directory that contains the server binary.
For out-of-process servers this is the same as QApplication::applicationDirPath(). For in-process servers that function returns the directory that contains the hosting application.
Definition at line 386 of file qaxfactory.cpp.
 {
     return QFileInfo(QString::fromWCharArray(qAxModuleFilename)).absolutePath();
 }
serverFilePath()
QString QAxFactory::serverFilePath () static
Returns the file path of the server binary.
For out-of-process servers this is the same as QApplication::applicationFilePath(). For in-process servers that function returns the file path of the hosting application.
Definition at line 398 of file qaxfactory.cpp.
 {
     return QString::fromWCharArray(qAxModuleFilename);
 }
startServer()
bool QAxFactory::startServer (ServerType type = MultipleInstances) inline static
Starts the COM server with type and returns true if successful, otherwise returns false.
Calling this function if the server is already running (or for an in-process server) does nothing and returns true.
The server is started automatically with type set to MultipleInstances if the server executable has been started with the -activex command line parameter. To switch to SingleInstance, call
if (QAxFactory::isServer()) {
    QAxFactory::stopServer();
    QAxFactory::startServer(QAxFactory::SingleInstance);
}
in your own main() entry point function.
Definition at line 115 of file qaxfactory.h.
Referenced by main(), and WinMain().
 {
     // implementation in qaxservermain.cpp
     return qax_startServer(type);
 }
stayTopLevel()
bool QAxFactory::stayTopLevel (const QString & key) const virtual
Reimplement this function to return true if the ActiveX control key should be a top level window, e.g.
a dialog. The default implementation returns false.
Definition at line 330 of file qaxfactory.cpp.
Referenced by QAxServerBase::internalCreate().
 {
     return false;
 }
stopServer()
bool QAxFactory::stopServer () inline static
Stops the COM server and returns true if successful, otherwise returns false.
Calling this function if the server is not running (or for an in-process server) does nothing and returns true.
Stopping the server will not invalidate existing objects, but no new objects can be created from the existing server process. Usually COM will start a new server process if additional objects are requested.
The server is stopped automatically when the main() function returns.
Definition at line 123 of file qaxfactory.h.
Referenced by WinMain().
 {
     // implementation in qaxservermain.cpp
     return qax_stopServer();
 }
typeLibID()
QUuid QAxFactory::typeLibID () const virtual
Reimplement this function to return the ActiveX server's type library identifier.
Definition at line 124 of file qaxfactory.cpp.
Referenced by DumpIDL(), and UpdateRegistry().
 {
     return typelib;
 }
unregisterClass()
void QAxFactory::unregisterClass (const QString & key, QSettings * settings) const virtual
Unregisters any additional values for the class key from the system registry using the settings object.
settings->remove("/CLSID/" + classID(key)
                 + "/Implemented Categories"
                 + "/{00000000-0000-0000-000000000000}/.");
See also
registerClass(), QSettings
Definition at line 266 of file qaxfactory.cpp.
 {
     Q_UNUSED(key);
     Q_UNUSED(settings)
 }
validateLicenseKey()
bool QAxFactory::validateLicenseKey (const QString & key, const QString & licenseKey) const virtual
Reimplement this function to return true if licenseKey is a valid license for the class key, or if the current machine is licensed.
The default implementation returns true if the class key is not licensed (ie. no Q_CLASSINFO() attribute "LicenseKey"), or if licenseKey matches the value of the "LicenseKey" attribute, or if the machine is licensed through a .LIC file with the same filename as this COM server.
Definition at line 282 of file qaxfactory.cpp.
Referenced by QClassFactory::GetLicInfo().
 {
     const QMetaObject *mo = metaObject(key);
     if (!mo)
         return true;
     QString classKey = QString::fromLatin1(mo->classInfo(mo->indexOfClassInfo("LicenseKey")).value());
     if (classKey.isEmpty())
         return true;
     if (licenseKey.isEmpty()) {
         QString licFile(QString::fromWCharArray(qAxModuleFilename));
         int lastDot = licFile.lastIndexOf(QLatin1Char('.'));
         licFile = licFile.left(lastDot) + QLatin1String(".lic");
         if (QFile::exists(licFile))
             return true;
         return false;
     }
     return licenseKey == classKey;
 }
Properties
app
QUuid QAxFactory::app private
Definition at line 108 of file qaxfactory.h.
Referenced by appID().
typelib
QUuid QAxFactory::typelib private
Definition at line 107 of file qaxfactory.h.
Referenced by typeLibID().
The documentation for this class was generated from the following files:
/src/activeqt/control/qaxfactory.h
/src/activeqt/control/qaxfactory.cpp
/src/activeqt/control/qaxserverbase.cpp