Qt 4.8: QAxScript Class Reference
QAxScript Class Reference
The QAxScript class provides a wrapper around script code.
#include <qaxscript.h>
Public Types
enum FunctionFlags { FunctionNames = 0, FunctionSignatures }
This FunctionFlags enum describes formatting for function introspection.
Signals
void entered ()
This signal is emitted when a script engine has started executing code.
void error (int code, const QString &description, int sourcePosition, const QString &sourceText)
This signal is emitted when an execution error occurred while running a script.
void finished ()
This signal is emitted when a script engine has finished executing code.
void finished (const QVariant &result)
QVariant if the script has no return value.
void finished (int code, const QString &source, const QString &description, const QString &help)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.code, source, description and help contain exception information when the script terminated.
void stateChanged (int state)
This signal is emitted when a script engine changes state.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QVariant call (const QString &function, const QVariant &v1=QVariant(), const QVariant &v2=QVariant(), const QVariant &v3=QVariant(), const QVariant &v4=QVariant(), const QVariant &v5=QVariant(), const QVariant &v6=QVariant(), const QVariant &v7=QVariant(), const QVariant &v8=QVariant())
Calls function, passing the parameters var1, var1, var2, var3, var4, var5, var6, var7 and var8 as arguments and returns the value returned by the function, or an invalid QVariant if the function does not return a value or when the function call failed.
QVariant call (const QString &function, QList< QVariant > &arguments)
Calls function passing arguments as parameters, and returns the result.
QStringList functions (FunctionFlags=FunctionNames) const
Returns a list of all the functions in this script if the respective script engine supports introspection; otherwise returns an empty list.
bool load (const QString &code, const QString &language=QString())
Loads the script source code written in language language into the script engine.
QAxScript (const QString &name, QAxScriptManager *manager)
Constructs a QAxScript object called name and registers it with the QAxScriptManager manager.
QString scriptCode () const
Returns the script's code, or the null-string if no code has been loaded yet.
QAxScriptEngine * scriptEngine () const
Returns a pointer to the script engine.
QString scriptName () const
Returns the name of the script.
~QAxScript ()
Destroys the object, releasing all allocated resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
QAxBase * findObject (const QString &name)
Returns the object name registered with the manager.
void updateObjects ()
Registers all objects in the manager with the script engine.
Properties
QString script_code
QAxScriptEngine * script_engine
QAxScriptManager * script_manager
QString script_name
QAxScriptSite * script_site
Friends
class QAxScriptEngine
class QAxScriptSite
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAxScript class provides a wrapper around script code.
Attention
Module: QAxContainer
Every instance of the QAxScript class represents a piece of scripting code in a particular scripting language. The code is loaded into the script engine using load(). Functions declared in the code can be called using call().
The script provides scriptEngine() provides feedback to the application through signals. The most important signal is the error() signal. Direct access to the QAxScriptEngine is provided through the scriptEngine() function.
Warning
This class is not available with the bcc5.5 and MingW compilers.
See also
QAxScriptEngine, QAxScriptManager, QAxBase, {ActiveQt Framework}
Definition at line 100 of file qaxscript.h.
Enumerations
FunctionFlags
enum QAxScript::FunctionFlags
This FunctionFlags enum describes formatting for function introspection.
FunctionNames Only function names are returned.
FunctionSignatures Returns the functions with signatures.
Enumerator
FunctionNames
FunctionSignatures
Definition at line 105 of file qaxscript.h.
{
         FunctionNames = 0,
         FunctionSignatures
     };
Constructors and Destructors
QAxScript()
QAxScript::QAxScript (const QString & name, QAxScriptManager * manager)
Constructs a QAxScript object called name and registers it with the QAxScriptManager manager.
This is usually done by the QAxScriptManager class when loading a script.
A script should always have a name. A manager is necessary to allow the script code to reference objects in the application. The manager takes ownership of the object.
Definition at line 676 of file qaxscript.cpp.
 : QObject(manager), script_name(name), script_manager(manager),
 script_engine(0)
 {
     if (manager) {
         manager->d->scriptDict.insert(name, this);
         connect(this, SIGNAL(error(int,QString,int,QString)),
             manager, SLOT(scriptError(int,QString,int,QString)));
     }
 #ifndef QT_NO_QAXSCRIPT
     script_site = new QAxScriptSite(this);
 #else
     script_site = 0;
 #endif
 }
~QAxScript()
QAxScript::~QAxScript ()
Destroys the object, releasing all allocated resources.
Definition at line 696 of file qaxscript.cpp.
 {
     delete script_engine;
     script_engine = 0;
 #ifndef QT_NO_QAXSCRIPT
     script_site->Release();
 #endif
 }
Functions
call() [1/2]
QVariant QAxScript::call (const QString & function, const QVariant & var1 = QVariant(), const QVariant & var2 = QVariant(), const QVariant & var3 = QVariant(), const QVariant & var4 = QVariant(), const QVariant & var5 = QVariant(), const QVariant & var6 = QVariant(), const QVariant & var7 = QVariant(), const QVariant & var8 = QVariant())
Calls function, passing the parameters var1, var1, var2, var3, var4, var5, var6, var7 and var8 as arguments and returns the value returned by the function, or an invalid QVariant if the function does not return a value or when the function call failed.
See QAxScriptManager::call() for more information about how to call script functions.
Definition at line 793 of file qaxscript.cpp.
Referenced by QAxScriptManager::call().
 {
     if (!script_engine)
         return QVariant();
     return script_engine->dynamicCall(function.toLatin1(), var1, var2, var3, var4, var5, var6, var7, var8);
 }
call() [2/2]
QVariant QAxScript::call (const QString & function, QList< QVariant > & arguments)
Calls function passing arguments as parameters, and returns the result.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns when the script's execution has finished.
See QAxScriptManager::call() for more information about how to call script functions.
Definition at line 820 of file qaxscript.cpp.
 {
     if (!script_engine)
         return QVariant();
     return script_engine->dynamicCall(function.toLatin1(), arguments);
 }
entered
void QAxScript::entered () signal
This signal is emitted when a script engine has started executing code.
Referenced by QAxScriptSite::OnEnterScript().
error
void QAxScript::error (int code, const QString & description, int sourcePosition, const QString & sourceText) signal
This signal is emitted when an execution error occurred while running a script.
code, description, sourcePosition and sourceText contain information about the execution error.
Referenced by QAxScriptSite::OnScriptError(), and QAxScript().
findObject()
QAxBase * QAxScript::findObject (const QString & name) private
Returns the object name registered with the manager.
Warning
This function is not part of the public interface.
Definition at line 848 of file qaxscript.cpp.
Referenced by QAxScriptSite::GetItemInfo().
 {
     if (!script_manager)
         return 0;
     return script_manager->d->objectDict.value(name);
 }
finished [1/3]
void QAxScript::finished () signal
This signal is emitted when a script engine has finished executing code.
Referenced by QAxScriptSite::OnLeaveScript(), and QAxScriptSite::OnScriptTerminate().
finished [2/3]
void QAxScript::finished (const QVariant & result) signal
QVariant if the script has no return value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
result contains the script's result. This will be an invalid
finished [3/3]
void QAxScript::finished (int code, const QString & source, const QString & description, const QString & help) signal
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.code, source, description and help contain exception information when the script terminated.
functions()
QStringList QAxScript::functions (FunctionFlags flags = FunctionNames) const
Returns a list of all the functions in this script if the respective script engine supports introspection; otherwise returns an empty list.
The functions are either provided with full prototypes or only as names, depending on the value of flags.
See also
QAxScriptEngine::hasIntrospection()
Definition at line 761 of file qaxscript.cpp.
Referenced by QAxScriptManager::functions(), and QAxScriptManager::scriptForFunction().
 {
     QStringList functions;
     const QMetaObject *mo = script_engine->metaObject();
     for (int i = mo->methodOffset(); i < mo->methodCount(); ++i) {
        const QMetaMethod slot(mo->method(i));
        if (slot.methodType() != QMetaMethod::Slot || slot.access() != QMetaMethod::Public)
             continue;
         QString slotname = QString::fromLatin1(slot.signature());
         if (slotname.contains(QLatin1Char('_')))
             continue;
         if (flags == FunctionSignatures)
             functions << slotname;
         else
             functions << slotname.left(slotname.indexOf(QLatin1Char('(')));
     }
     return functions;
 }
load()
bool QAxScript::load (const QString & code, const QString & language = QString())
Loads the script source code written in language language into the script engine.
Returns true if code was successfully entered into the script engine; otherwise returns false.
If language is empty (the default) it will be determined heuristically. If code contains the string {End Sub} it will be interpreted as VBScript, otherwise as JScript. Additional scripting languages can be registered using QAxScript::registerEngine().
This function can only be called once for each QAxScript object, which is done automatically when using QAxScriptManager::load().
Definition at line 720 of file qaxscript.cpp.
Referenced by QAxScriptManager::load().
 {
     if (script_engine || code.isEmpty())
         return false;
     script_code = code;
     QString lang = language;
     if (lang.isEmpty()) {
         if (code.contains(QLatin1String("End Sub"), Qt::CaseInsensitive))
             lang = QLatin1String("VBScript");
         QList<QAxEngineDescriptor>::ConstIterator it;
         for (it = engines.begin(); it != engines.end(); ++it) {
             QAxEngineDescriptor engine = *it;
             if (engine.code.isEmpty())
                 continue;
             if (code.contains(engine.code)) {
                 lang = engine.name;
                 break;
             }
         }
     }
     if (lang.isEmpty())
         lang = QLatin1String("JScript");
     script_engine = new QAxScriptEngine(lang, this);
     // trigger call to initialize
     script_engine->metaObject();
     return script_engine->isValid();
 }
scriptCode()
QString QAxScript::scriptCode () const inline
Returns the script's code, or the null-string if no code has been loaded yet.
See also
load()
Definition at line 202 of file qaxscript.h.
Referenced by QAxScriptEngine::initialize().
 {
     return script_code;
 }
scriptEngine()
QAxScriptEngine * QAxScript::scriptEngine () const inline
Returns a pointer to the script engine.
You can use the object returned to connect signals to the script functions, or to access the script engine directly.
Definition at line 212 of file qaxscript.h.
Referenced by QAxScriptManager::updateScript().
 {
     return script_engine;
 }
scriptName()
QString QAxScript::scriptName () const inline
Returns the name of the script.
Definition at line 207 of file qaxscript.h.
 {
     return script_name;
 }
stateChanged
void QAxScript::stateChanged (int state) signal
This signal is emitted when a script engine changes state.
state can be any value in the QAxScriptEngineState enumeration.
Referenced by QAxScriptSite::OnStateChange().
updateObjects()
void QAxScript::updateObjects () private
Registers all objects in the manager with the script engine.
Warning
This function is not part of the public interface.
Definition at line 834 of file qaxscript.cpp.
Referenced by QAxScriptEngine::initialize().
 {
     if (!script_manager)
         return;
     script_manager->updateScript(this);
 }
Friends and Related Functions
QAxScriptEngine
friend class QAxScriptEngine friend
Definition at line 141 of file qaxscript.h.
Referenced by load().
QAxScriptSite
friend class QAxScriptSite friend
Definition at line 140 of file qaxscript.h.
Referenced by QAxScript().
Properties
script_code
QString QAxScript::script_code private
Definition at line 147 of file qaxscript.h.
Referenced by load().
script_engine
QAxScriptEngine* QAxScript::script_engine private
Definition at line 149 of file qaxscript.h.
Referenced by call(), functions(), load(), scriptEngine(), and ~QAxScript().
script_manager
QAxScriptManager* QAxScript::script_manager private
Definition at line 148 of file qaxscript.h.
Referenced by findObject(), and updateObjects().
script_name
QString QAxScript::script_name private
Definition at line 146 of file qaxscript.h.
Referenced by scriptName().
script_site
QAxScriptSite* QAxScript::script_site private
Definition at line 150 of file qaxscript.h.
Referenced by QAxScriptEngine::initialize(), QAxScript(), and ~QAxScript().
The documentation for this class was generated from the following files:
/src/activeqt/container/qaxscript.h
/src/activeqt/container/qaxscript.cpp