Qt 4.8: QPatternist::AxisStep Class Reference
QPatternist::AxisStep Class Reference
A step in a path expression that with an axis and a node test evaluates to a sequence of nodes from the context item.
#include <qaxisstep_p.h>
Public Functions
virtual ExpressionVisitorResult::Ptr accept (const ExpressionVisitor::Ptr &visitor) const
QXmlNodeModelIndex::Axis axis () const
AxisStep (const QXmlNodeModelIndex::Axis axis, const ItemType::Ptr &nodeTest)
virtual Item::Iterator::Ptr evaluateSequence (const DynamicContext::Ptr &) const
virtual Item evaluateSingleton (const DynamicContext::Ptr &) const
virtual ItemType::Ptr expectedContextItemType () const
virtual SequenceType::List expectedOperandTypes () const
virtual ID id () const
Item mapToItem (const QXmlNodeModelIndex &node, const DynamicContext::Ptr &context) const
ItemType::Ptr nodeTest () const
virtual PatternPriority patternPriority () const
virtual Properties properties () const
void setAxis (const QXmlNodeModelIndex::Axis newAxis)
void setNodeTest (const ItemType::Ptr &nev)
virtual SequenceType::Ptr staticType () const
virtual Expression::Ptr typeCheck (const StaticContext::Ptr &context, const SequenceType::Ptr &reqType)
Public Functions inherited from QPatternist::EmptyContainer
virtual Expression::List operands () const
virtual void setOperands (const Expression::List &)
Public Functions inherited from QPatternist::Expression
virtual const SourceLocationReflection * actualReflection () const
Returns this.
virtual void announceFocusType (const ItemType::Ptr &itemType)
virtual Expression::Ptr compress (const StaticContext::Ptr &context)
Properties deepProperties () const
Computes the union of properties for this Expression and all its descending children.
virtual Properties dependencies () const
virtual QString description () const
virtual bool evaluateEBV (const DynamicContext::Ptr &context) const
virtual void evaluateToSequenceReceiver (const DynamicContext::Ptr &context) const
Expression ()
bool has (const Property prop) const
bool hasDependency (const Property prop) const
bool is (const ID id) const
bool isEvaluated () const
virtual ItemType::Ptr newFocusType () const
virtual QList< QExplicitlySharedDataPointer< OptimizationPass > > optimizationPasses () const
const Expression::Ptr & rewrite (const Expression::Ptr &to, const StaticContext::Ptr &context) const
Rewrites this Expression to to, and return to.
virtual ~Expression ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< Expression >
const TCastTarget * as () const
TCastTarget * as ()
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Static Public Functions
static QString axisName (const QXmlNodeModelIndex::Axis axis)
Prints the EBNF name corresponding to axis.
Static Public Functions inherited from QPatternist::Expression
static void rewrite (Expression::Ptr &old, const Expression::Ptr &New, const StaticContext::Ptr &context)
Private Types
typedef QExplicitlySharedDataPointer< const AxisStep > ConstPtr
Static Private Functions
static bool isAlwaysEmpty (const QXmlNodeModelIndex::Axis axis, const QXmlNodeModelIndex::NodeKind nodeKind)
Properties
QXmlNodeModelIndex::Axis m_axis
ItemType::Ptr m_nodeTest
Static Private Attributes
static const QXmlNodeModelIndex::NodeKind s_whenAxisNodeKindEmpty []
Additional Inherited Members
Public Types inherited from QPatternist::Expression
typedef QExplicitlySharedDataPointer< const Expression > ConstPtr
A smart pointer wrapping const Expression instances.
enum ID {
IDBooleanValue = 1, IDCountFN, IDEmptyFN, IDExistsFN,
IDExpressionSequence, IDGeneralComparison, IDIfThenClause, IDIgnorableExpression,
IDIntegerValue, IDPositionFN, IDStringValue, IDValueComparison,
IDRangeVariableReference, IDContextItem, IDUserFunctionCallsite, IDExpressionVariableReference,
IDAttributeConstructor, IDUpperCaseFN, IDLowerCaseFN, IDFirstItemPredicate,
IDEmptySequence, IDReturnOrderBy, IDLetClause, IDForClause,
IDPath, IDNamespaceConstructor, IDArgumentReference, IDGenericPredicate,
IDAxisStep, IDFloat, IDCombineNodes, IDUnresolvedVariableReference,
IDCardinalityVerifier
}
typedef QList< Expression::Ptr > List
typedef QFlags< Property > Properties
enum Property {
UseContextItem = 1, DisableElimination = 1 << 1, IsEvaluated = 1 << 2, DisableTypingDeduction = 1 << 3,
EmptynessFollowsChild = 1 << 4, RewriteToEmptyOnEmpty = 1 << 5, RequiresFocus = 1 << 6, AffectsOrderOnly = 1 << 7,
RequiresContextItem = (1 << 8) | RequiresFocus, CreatesFocusForLast = 1 << 9, LastOperandIsCollation = 1 << 10, DependsOnLocalVariable = (1 << 11) | DisableElimination,
EvaluationCacheRedundant = (1 << 12), IsNodeConstructor = 1 << 13, RequiresCurrentItem = 1 << 14
}
typedef QExplicitlySharedDataPointer< Expression > Ptr
A smart pointer wrapping mutable Expression instances.
typedef ::QAbstractXmlForwardIterator< Expression::Ptr > QAbstractXmlForwardIterator
typedef QVector< Expression::Ptr > Vector
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::EmptyContainer
virtual bool compressOperands (const StaticContext::Ptr &context)
Protected Functions inherited from QPatternist::Expression
void typeCheckOperands (const StaticContext::Ptr &context)
Protected Functions inherited from QPatternist::CppCastingHelper< Expression >
CppCastingHelper ()
Detailed Description
A step in a path expression that with an axis and a node test evaluates to a sequence of nodes from the context item.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 71 of file qaxisstep_p.h.
Typedefs
ConstPtr
typedef QExplicitlySharedDataPointer<const AxisStep> QPatternist::AxisStep::ConstPtr private
Definition at line 137 of file qaxisstep_p.h.
Constructors and Destructors
AxisStep()
AxisStep::AxisStep (const QXmlNodeModelIndex::Axis axis, const ItemType::Ptr & nodeTest)
Definition at line 91 of file qaxisstep.cpp.
                                           : m_axis(a),
                                               m_nodeTest(nt)
 {
     Q_ASSERT(m_nodeTest);
     Q_ASSERT_X(BuiltinTypes::node->xdtTypeMatches(m_nodeTest), Q_FUNC_INFO,
                "We assume we're a node type.");
 }
Functions
accept()
ExpressionVisitorResult::Ptr AxisStep::accept (const ExpressionVisitor::Ptr & visitor) const virtual
Implements QPatternist::Expression.
Definition at line 199 of file qaxisstep.cpp.
 {
     return visitor->visit(this);
 }
axis()
QXmlNodeModelIndex::Axis AxisStep::axis () const
Returns
the axis this step is using.
Definition at line 204 of file qaxisstep.cpp.
Referenced by QPatternist::changeToTopAxis().
 {
     return m_axis;
 }
axisName()
QString AxisStep::axisName (const QXmlNodeModelIndex::Axis axis) static
Prints the EBNF name corresponding to axis.
For instance, for QXmlNodeModelIndex::Child, "child" is returned.
Apart from being used in this class, it is used in the SDK.
Definition at line 209 of file qaxisstep.cpp.
Referenced by QPatternist::yyparse().
 {
     const char *result = 0;
     switch(axis)
     {
         /* These must not be translated. */
         case QXmlNodeModelIndex::AxisAncestorOrSelf:    result = "ancestor-or-self";    break;
         case QXmlNodeModelIndex::AxisAncestor:          result = "ancestor";            break;
         case QXmlNodeModelIndex::AxisAttributeOrTop:    result = "attribute-or-top";    break;
         case QXmlNodeModelIndex::AxisAttribute:         result = "attribute";           break;
         case QXmlNodeModelIndex::AxisChildOrTop:        result = "child-or-top";        break;
         case QXmlNodeModelIndex::AxisChild:             result = "child";               break;
         case QXmlNodeModelIndex::AxisDescendantOrSelf:  result = "descendant-or-self";  break;
         case QXmlNodeModelIndex::AxisDescendant:        result = "descendant";          break;
         case QXmlNodeModelIndex::AxisFollowing:         result = "following";           break;
         case QXmlNodeModelIndex::AxisFollowingSibling:  result = "following-sibling";   break;
         case QXmlNodeModelIndex::AxisNamespace:         result = "namespace";           break;
         case QXmlNodeModelIndex::AxisParent:            result = "parent";              break;
         case QXmlNodeModelIndex::AxisPreceding:         result = "preceding";           break;
         case QXmlNodeModelIndex::AxisPrecedingSibling:  result = "preceding-sibling";   break;
         case QXmlNodeModelIndex::AxisSelf:              result = "self";                break;
     }
     Q_ASSERT_X(result, Q_FUNC_INFO, "An unknown axis type was apparently encountered.");
     return QString::fromLatin1(result);
 }
evaluateSequence()
Item::Iterator::Ptr AxisStep::evaluateSequence (const DynamicContext::Ptr & context) const virtual
Evaluate this Expression by iterating over it. This is a central function for evaluating expressions.
Expressions must always always return a valid QAbstractXmlForwardIterator and may never return 0. If an empty result is of interest to be returned, the EmptyIterator should be returned.
The default implementation returns a SingletonIterator over the item returned from evaluateSingleton().
Note
This function may raise an exception when calling, not only when QAbstractXmlForwardIterator::next() is called on the return value. This is because in some cases evaluateSingleton() is called directly.
Reimplemented from QPatternist::Expression.
Definition at line 114 of file qaxisstep.cpp.
 {
     /* If we don't have a focus, it's either a bug or our parent isn't a Path
      * that have advanced the focus iterator. Hence, attempt to advance the focus on our own. */
     if(!context->contextItem())
         context->focusIterator()->next();
     Q_ASSERT(context->contextItem());
     const QXmlNodeModelIndex::Iterator::Ptr source(context->contextItem().asNode().iterate(m_axis));
     return makeItemMappingIterator<Item>(ConstPtr(this), source, context);
 }
evaluateSingleton()
Item AxisStep::evaluateSingleton (const DynamicContext::Ptr & context) const virtual
Reimplemented from QPatternist::Expression.
Definition at line 128 of file qaxisstep.cpp.
 {
     /* If we don't have a focus, it's either a bug or our parent isn't a Path
      * that have advanced the focus iterator. Hence, attempt to advance the focus on our own. */
     if(!context->contextItem())
         context->focusIterator()->next();
     Q_ASSERT(context->contextItem());
     const QXmlNodeModelIndex::Iterator::Ptr it(context->contextItem().asNode().iterate(m_axis));
     QXmlNodeModelIndex next(it->next());
     while(!next.isNull())
     {
         const Item candidate(mapToItem(next, context));
         if(candidate)
             return candidate;
         else
             next = it->next();
     };
     return Item();
 }
expectedContextItemType()
ItemType::Ptr AxisStep::expectedContextItemType () const virtual
Returns
always BuiltinTypes::node;
Reimplemented from QPatternist::Expression.
Definition at line 194 of file qaxisstep.cpp.
 {
     return BuiltinTypes::node;
 }
expectedOperandTypes()
SequenceType::List AxisStep::expectedOperandTypes () const virtual
Returns
always an empty list since it has no operands.
Reimplemented from QPatternist::EmptyContainer.
Definition at line 182 of file qaxisstep.cpp.
 {
     SequenceType::List result;
     result.append(CommonSequenceTypes::ZeroOrMoreNodes);
     return result;
 }
id()
Expression::ID AxisStep::id () const virtual
This property, which has no setter, returns an enum value that uniquely identifies this Expression. Patternist makes no use of C++'s dynamic_cast feature, but uses this polymorphic function instead.
Returns
always IgnorableExpression.
Reimplemented from QPatternist::Expression.
Definition at line 242 of file qaxisstep.cpp.
 {
     return IDAxisStep;
 }
isAlwaysEmpty()
bool AxisStep::isAlwaysEmpty (const QXmlNodeModelIndex::Axis axis, const QXmlNodeModelIndex::NodeKind nodeKind) static private
Returns
true when the axis axis and a node test testing node of type nodeKind always produces an empty sequence. One such example is attribute::comment().
Definition at line 86 of file qaxisstep.cpp.
 {
     return (s_whenAxisNodeKindEmpty[(1 >> axis) - 1] & nodeKind) != 0;
 }
mapToItem()
Item AxisStep::mapToItem (const QXmlNodeModelIndex & node, const DynamicContext::Ptr & context) const inline
Returns node if it matches the node test this step is using, otherwise null.
Definition at line 100 of file qaxisstep.cpp.
Referenced by evaluateSingleton().
 {
     Q_ASSERT(!node.isNull());
     Q_ASSERT(Item(node).isNode());
     Q_ASSERT(Item(node));
     Q_UNUSED(context);
     if(m_nodeTest->itemMatches(Item(node)))
         return Item(node);
     else
         return Item();
 }
nodeTest()
ItemType::Ptr QPatternist::AxisStep::nodeTest () const inline
Returns
the node test this step is using.
Definition at line 112 of file qaxisstep_p.h.
Referenced by QPatternist::yyparse().
         {
             return m_nodeTest;
         }
patternPriority()
PatternPriority AxisStep::patternPriority () const virtual
By default 0.5 is returned.
Reimplemented from QPatternist::Expression.
Definition at line 237 of file qaxisstep.cpp.
 {
     return static_cast<const AnyNodeType *>(m_nodeTest.data())->patternPriority();
 }
properties()
Expression::Properties AxisStep::properties () const virtual
Returns
a bitwise OR'd value of properties, describing the characteristics of the expression. These properties affects how this Expression is treated in for example type checking stages.
The default implementation returns 0. Override and let the function return a different value, if that's of interest.
An important decision when re-implementing properties() is whether to OR in the properties() of ones operands. For instance, if an operand has RequiresFocus set, that flag nost likely applies to the apparent as well, since it depends on its operand.
See also
deepProperties()
Returns
Expression::None, meaning no special properties
Reimplemented from QPatternist::Expression.
Definition at line 189 of file qaxisstep.cpp.
 {
     return RequiresContextItem | DisableElimination;
 }
setAxis()
void QPatternist::AxisStep::setAxis (const QXmlNodeModelIndex::Axis newAxis) inline
Definition at line 157 of file qaxisstep_p.h.
Referenced by QPatternist::changeToTopAxis(), QPatternist::createPatternPath(), and QPatternist::yyparse().
     {
         m_axis = newAxis;
     }
setNodeTest()
void QPatternist::AxisStep::setNodeTest (const ItemType::Ptr & nev) inline
Definition at line 117 of file qaxisstep_p.h.
Referenced by QPatternist::yyparse().
         {
             m_nodeTest = nev;
         }
staticType()
SequenceType::Ptr AxisStep::staticType () const virtual
Returns
the static type of this Expression. For example, an 'and' expression have as static type xs:boolean
Implements QPatternist::Expression.
Definition at line 169 of file qaxisstep.cpp.
 {
     Cardinality cardinality;
     if(m_axis == QXmlNodeModelIndex::AxisSelf || m_axis == QXmlNodeModelIndex::AxisParent)
         cardinality = Cardinality::zeroOrOne();
     else
         cardinality = Cardinality::zeroOrMore();
     return makeGenericSequenceType(m_nodeTest,
                                    cardinality);
 }
typeCheck()
Expression::Ptr AxisStep::typeCheck (const StaticContext::Ptr & context, const SequenceType::Ptr & reqType) virtual
Rewrites to ParentNodeAxis, if possible.
Reimplemented from QPatternist::Expression.
Definition at line 153 of file qaxisstep.cpp.
 {
     if(m_axis == QXmlNodeModelIndex::AxisParent && *m_nodeTest == *BuiltinTypes::node)
     {
         /* We only rewrite parent::node() to ParentNodeAxis. */
         return rewrite(Expression::Ptr(new ParentNodeAxis()), context)->typeCheck(context, reqType);
     }
     /* TODO temporarily disabled
     else if(isAlwaysEmpty(m_axis, static_cast<const AnyNodeType *>(m_nodeTest.data())->nodeKind()))
         return EmptySequence::create(this, context);
         */
     else
         return EmptyContainer::typeCheck(context, reqType);
 }
Properties
m_axis
QXmlNodeModelIndex::Axis QPatternist::AxisStep::m_axis private
The reason this variable is mutable, is that in the case of XSL-T patterns, we do quite some reordering.
Definition at line 153 of file qaxisstep_p.h.
Referenced by axis(), evaluateSequence(), evaluateSingleton(), staticType(), and typeCheck().
m_nodeTest
ItemType::Ptr QPatternist::AxisStep::m_nodeTest private
Definition at line 154 of file qaxisstep_p.h.
Referenced by AxisStep(), mapToItem(), patternPriority(), staticType(), and typeCheck().
s_whenAxisNodeKindEmpty
const QXmlNodeModelIndex::NodeKind AxisStep::s_whenAxisNodeKindEmpty static private
Initial value:
=
{
    QXmlNodeModelIndex::Attribute|QXmlNodeModelIndex::Text|QXmlNodeModelIndex::ProcessingInstruction|QXmlNodeModelIndex::Comment|QXmlNodeModelIndex::Namespace,
    QXmlNodeModelIndex::Attribute|QXmlNodeModelIndex::Text|QXmlNodeModelIndex::ProcessingInstruction|QXmlNodeModelIndex::Comment|QXmlNodeModelIndex::Namespace,
    QXmlNodeModelIndex::Document|QXmlNodeModelIndex::Attribute|QXmlNodeModelIndex::Text|QXmlNodeModelIndex::ProcessingInstruction|QXmlNodeModelIndex::Comment|QXmlNodeModelIndex::Namespace,
    QXmlNodeModelIndex::NodeKind(0),
    QXmlNodeModelIndex::NodeKind(0),
    QXmlNodeModelIndex::Document|QXmlNodeModelIndex::Attribute|QXmlNodeModelIndex::Text|QXmlNodeModelIndex::ProcessingInstruction|QXmlNodeModelIndex::Comment|QXmlNodeModelIndex::Namespace,
    QXmlNodeModelIndex::Document,
    QXmlNodeModelIndex::Document,
    QXmlNodeModelIndex::Document,
    QXmlNodeModelIndex::Document|QXmlNodeModelIndex::Attribute|QXmlNodeModelIndex::Namespace,
    QXmlNodeModelIndex::Document|QXmlNodeModelIndex::Attribute|QXmlNodeModelIndex::Namespace,
    QXmlNodeModelIndex::Document,
    QXmlNodeModelIndex::NodeKind(0)
}
Note
The order is significant. It is of the same order as the values in QXmlNodeModelIndex::Axis is declared.
Definition at line 139 of file qaxisstep_p.h.
Referenced by isAlwaysEmpty(), and QPatternist::operator|().
The documentation for this class was generated from the following files:
/src/xmlpatterns/expr/qaxisstep_p.h
/src/xmlpatterns/expr/qaxisstep.cpp