Qt 4.8: QBBBuffer Class Reference
QBBBuffer Class Reference
#include <qbbbuffer.h>
Public Functions
const QImage * image () const
QImage * image ()
void invalidateInCache ()
screen_buffer_t nativeBuffer () const
QBBBuffer ()
QBBBuffer (screen_buffer_t buffer)
QBBBuffer (const QBBBuffer &other)
QRect rect () const
virtual ~QBBBuffer ()
Properties
screen_buffer_t mBuffer
QImage mImage
Detailed Description
Definition at line 51 of file qbbbuffer.h.
Constructors and Destructors
QBBBuffer() [1/3]
QBBBuffer::QBBBuffer ()
Definition at line 54 of file qbbbuffer.cpp.
     : mBuffer(NULL)
 {
 #if defined(QBBBUFFER_DEBUG)
     qDebug() << "QBBBuffer::QBBBuffer - empty";
 #endif
 }
QBBBuffer() [2/3]
QBBBuffer::QBBBuffer (screen_buffer_t buffer)
Definition at line 62 of file qbbbuffer.cpp.
     : mBuffer(buffer)
 {
 #if defined(QBBBUFFER_DEBUG)
     qDebug() << "QBBBuffer::QBBBuffer - normal";
 #endif
     // get size of buffer
     errno = 0;
     int size[2];
     int result = screen_get_buffer_property_iv(buffer, SCREEN_PROPERTY_BUFFER_SIZE, size);
     if (result != 0) {
         qFatal("QBB: failed to query buffer size, errno=%d", errno);
     }
     // get stride of buffer
     errno = 0;
     int stride;
     result = screen_get_buffer_property_iv(buffer, SCREEN_PROPERTY_STRIDE, &stride);
     if (result != 0) {
         qFatal("QBB: failed to query buffer stride, errno=%d", errno);
     }
     // get access to buffer's data
     errno = 0;
     uchar* dataPtr = NULL;
     result = screen_get_buffer_property_pv(buffer, SCREEN_PROPERTY_POINTER, (void **)&dataPtr);
     if (result != 0) {
         qFatal("QBB: failed to query buffer pointer, errno=%d", errno);
     }
     if (dataPtr == NULL) {
         qFatal("QBB: buffer pointer is NULL, errno=%d", errno);
     }
     // get format of buffer
     errno = 0;
     int screenFormat;
     result = screen_get_buffer_property_iv(buffer, SCREEN_PROPERTY_FORMAT, &screenFormat);
     if (result != 0) {
         qFatal("QBB: failed to query buffer format, errno=%d", errno);
     }
     // convert screen format to QImage format
     QImage::Format imageFormat = QImage::Format_Invalid;
     switch (screenFormat) {
     case SCREEN_FORMAT_RGBX4444:
         imageFormat = QImage::Format_RGB444;
         break;
     case SCREEN_FORMAT_RGBA4444:
         imageFormat = QImage::Format_ARGB4444_Premultiplied;
         break;
     case SCREEN_FORMAT_RGBX5551:
         imageFormat = QImage::Format_RGB555;
         break;
     case SCREEN_FORMAT_RGB565:
         imageFormat = QImage::Format_RGB16;
         break;
     case SCREEN_FORMAT_RGBX8888:
         imageFormat = QImage::Format_RGB32;
         break;
     case SCREEN_FORMAT_RGBA8888:
         imageFormat = QImage::Format_ARGB32_Premultiplied;
         break;
     default:
         qFatal("QBB: unsupported buffer format, format=%d", screenFormat);
     }
     // wrap buffer in an image
     mImage = QImage(dataPtr, size[0], size[1], stride, imageFormat);
 }
QBBBuffer() [3/3]
QBBBuffer::QBBBuffer (const QBBBuffer & other)
Definition at line 133 of file qbbbuffer.cpp.
     : mBuffer(other.mBuffer),
       mImage(other.mImage)
 {
 #if defined(QBBBUFFER_DEBUG)
     qDebug() << "QBBBuffer::QBBBuffer - copy";
 #endif
 }
~QBBBuffer()
QBBBuffer::~QBBBuffer () virtual
Definition at line 142 of file qbbbuffer.cpp.
 {
 #if defined(QBBBUFFER_DEBUG)
     qDebug() << "QBBBuffer::~QBBBuffer";
 #endif
 }
Functions
image() [1/2]
const QImage* QBBBuffer::image () const inline
Definition at line 60 of file qbbbuffer.h.
Referenced by QBBRasterWindowSurface::paintDevice().
 { return (mBuffer != NULL) ? &mImage : NULL; }
image() [2/2]
QImage* QBBBuffer::image () inline
Definition at line 61 of file qbbbuffer.h.
 { return (mBuffer != NULL) ? &mImage : NULL; }
invalidateInCache()
void QBBBuffer::invalidateInCache ()
Definition at line 149 of file qbbbuffer.cpp.
Referenced by QBBWindow::copyBack(), and rect().
 {
 #if defined(QBBBUFFER_DEBUG)
     qDebug() << "QBBBuffer::invalidateInCache";
 #endif
     // verify native buffer exists
     if (mBuffer == NULL) {
         qFatal("QBB: can't invalidate cache for null buffer");
     }
     // evict buffer's data from cache
     errno = 0;
     int result = msync(mImage.bits(), mImage.height() * mImage.bytesPerLine(), MS_INVALIDATE | MS_CACHE_ONLY);
     if (result != 0) {
         qFatal("QBB: failed to invalidate cache, errno=%d", errno);
     }
 }
nativeBuffer()
screen_buffer_t QBBBuffer::nativeBuffer () const inline
Definition at line 59 of file qbbbuffer.h.
Referenced by QBBWindow::copyBack(), and QBBWindow::post().
 { return mBuffer; }
rect()
QRect QBBBuffer::rect () const inline
Definition at line 63 of file qbbbuffer.h.
Referenced by QBBWindow::copyBack().
 { return mImage.rect(); }
Properties
mBuffer
screen_buffer_t QBBBuffer::mBuffer private
Definition at line 68 of file qbbbuffer.h.
Referenced by image(), invalidateInCache(), and nativeBuffer().
mImage
QImage QBBBuffer::mImage private
Definition at line 69 of file qbbbuffer.h.
Referenced by image(), invalidateInCache(), QBBBuffer(), and rect().
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbbuffer.h
/src/plugins/platforms/blackberry/qbbbuffer.cpp