Qt 4.8: QFontEngineQPA Class Reference
QFontEngineQPA Class Reference
#include <qfontengine_qpa_p.h>
Classes
struct Block
struct Glyph
struct Header
struct Tag
Public Types
enum { CurrentMajorVersion = 2, CurrentMinorVersion = 0 }
enum BlockTag { CMapBlock, GMapBlock, GlyphBlock }
enum GlyphFormat { BitmapGlyphs = 1, AlphamapGlyphs = 8 }
enum HeaderTag {
Tag_FontName, Tag_FileName, Tag_FileIndex, Tag_FontRevision,
Tag_FreeText, Tag_Ascent, Tag_Descent, Tag_Leading,
Tag_XHeight, Tag_AverageCharWidth, Tag_MaxCharWidth, Tag_LineThickness,
Tag_MinLeftBearing, Tag_MinRightBearing, Tag_UnderlinePosition, Tag_GlyphFormat,
Tag_PixelSize, Tag_Weight, Tag_Style, Tag_EndOfHeader,
Tag_WritingSystems, NumTags
}
enum TagType {
StringType, FixedType, UInt8Type, UInt32Type,
BitFieldType
}
Public Types inherited from QFontEngine
enum GlyphFormat {
Format_None, Format_Render = Format_None, Format_Mono, Format_A8,
Format_A32
}
enum SynthesizedFlags { SynthesizedItalic = 0x1, SynthesizedBold = 0x2, SynthesizedStretch = 0x4 }
enum Type {
Box, Multi, XLFD, Win,
Mac, Freetype, QPF1, QPF2,
Proxy, S60FontEngine, DirectWrite, TestFontEngine = 0x1000
}
Public Functions
void addOutlineToPath (qreal x, qreal y, const QGlyphLayout &glyphs, QPainterPath *path, QTextItem::RenderFlags flags)
QImage alphaMapForGlyph (glyph_t t)
QFixed ascent () const
glyph_metrics_t boundingBox (const QGlyphLayout &glyphs)
glyph_metrics_t boundingBox (glyph_t glyph)
bool canRender (const QChar *string, int len)
QFixed descent () const
FaceId faceId () const
const Glyph * findGlyph (glyph_t g) const
bool getSfntTableData (uint tag, uchar *buffer, uint *length) const
virtual int glyphCount () const
bool isValid () const
QFixed leading () const
QFixed lineThickness () const
qreal maxCharWidth () const
qreal minLeftBearing () const
qreal minRightBearing () const
const char * name () const
QFontEngineQPA (const QFontDef &def, const QByteArray &data)
void recalcAdvances (QGlyphLayout *, QTextEngine::ShaperFlags) const
bool stringToCMap (const QChar *str, int len, QGlyphLayout *glyphs, int *nglyphs, QTextEngine::ShaperFlags flags) const
Type type () const
QFixed underlinePosition () const
~QFontEngineQPA ()
Public Functions inherited from QFontEngine
void addBitmapFontToPath (qreal x, qreal y, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags)
virtual void addGlyphsToPath (glyph_t *glyphs, QFixedPoint *positions, int nglyphs, QPainterPath *path, QTextItem::RenderFlags flags)
virtual glyph_metrics_t alphaMapBoundingBox (glyph_t glyph, QFixed, const QTransform &matrix, GlyphFormat)
virtual QImage alphaMapForGlyph (glyph_t glyph, QFixed subPixelPosition)
virtual QImage alphaMapForGlyph (glyph_t, const QTransform &t)
virtual QImage alphaMapForGlyph (glyph_t, QFixed subPixelPosition, const QTransform &t)
virtual QImage alphaRGBMapForGlyph (glyph_t, QFixed subPixelPosition, int margin, const QTransform &t)
virtual QFixed averageCharWidth () const
virtual glyph_metrics_t boundingBox (glyph_t glyph, const QTransform &matrix)
virtual QFontEngine * cloneWithSize (qreal) const
virtual void doKerning (QGlyphLayout *, QTextEngine::ShaperFlags) const
virtual QFixed emSquareSize () const
virtual void getGlyphBearings (glyph_t glyph, qreal *leftBearing=0, qreal *rightBearing=0)
void getGlyphPositions (const QGlyphLayout &glyphs, const QTransform &matrix, QTextItem::RenderFlags flags, QVarLengthArray< glyph_t > &glyphs_out, QVarLengthArray< QFixedPoint > &positions)
virtual HB_Error getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed *xpos, HB_Fixed *ypos, hb_uint32 *nPoints)
QByteArray getSfntTable (uint) const
virtual void getUnscaledGlyph (glyph_t glyph, QPainterPath *path, glyph_metrics_t *metrics)
QFontEngineGlyphCache * glyphCache (void *key, QFontEngineGlyphCache::Type type, const QTransform &transform) const
HB_Face harfbuzzFace () const
HB_Font harfbuzzFont () const
void loadKerningPairs (QFixed scalingFactor)
virtual Properties properties () const
QFontEngine ()
virtual void removeGlyphFromCache (glyph_t)
void setGlyphCache (void *key, QFontEngineGlyphCache *data)
virtual bool supportsSubPixelPositions () const
virtual int synthesized () const
glyph_metrics_t tightBoundingBox (const QGlyphLayout &glyphs)
virtual QFixed xHeight () const
virtual ~QFontEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QVariant extractHeaderField (const uchar *data, HeaderTag tag)
static bool verifyHeader (const uchar *data, int size)
Static Public Functions inherited from QFontEngine
static QByteArray convertToPostscriptFontFamilyName (const QByteArray &fontFamily)
static const uchar * getCMap (const uchar *table, uint tableSize, bool *isSymbolFont, int *cmapSize)
static quint32 getTrueTypeGlyphIndex (const uchar *cmap, uint unicode)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Properties
quint32 cmapOffset
int cmapSize
int dataSize
QString encodedFileName
const uchar * externalCMap
FaceId face_id
const uchar * fontData
QByteArray freetypeCMapTable
quint32 glyphDataOffset
quint32 glyphDataSize
quint32 glyphMapEntries
quint32 glyphMapOffset
QString internalFileName
bool kerning_pairs_loaded
bool readOnly
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Variables inherited from QFontEngine
uint cache_cost
int cache_count
QFontDef fontDef
uint fsType: 16
int glyphFormat
HB_Face hbFace
HB_FontRec hbFont
QVector< KernPair > kerning_pairs
QAtomicInt ref
bool symbol
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QFontEngine
QFixed lastRightBearing (const QGlyphLayout &glyphs, bool round=false)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Protected Functions inherited from QFontEngine
static const QVector< QRgb > & grayPalette ()
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 72 of file qfontengine_qpa_p.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
CurrentMajorVersion
CurrentMinorVersion
Definition at line 122 of file qfontengine_qpa_p.h.
          {
         CurrentMajorVersion = 2,
         CurrentMinorVersion = 0
     };
BlockTag
enum QFontEngineQPA::BlockTag
Enumerator
CMapBlock
GMapBlock
GlyphBlock
Definition at line 130 of file qfontengine_qpa_p.h.
                   {
         CMapBlock,
         GMapBlock,
         GlyphBlock
     };
GlyphFormat
enum QFontEngineQPA::GlyphFormat
Enumerator
BitmapGlyphs
AlphamapGlyphs
Definition at line 117 of file qfontengine_qpa_p.h.
                      {
         BitmapGlyphs = 1,
         AlphamapGlyphs = 8
     };
HeaderTag
enum QFontEngineQPA::HeaderTag
Enumerator
Tag_FontName
Tag_FileName
Tag_FileIndex
Tag_FontRevision
Tag_FreeText
Tag_Ascent
Tag_Descent
Tag_Leading
Tag_XHeight
Tag_AverageCharWidth
Tag_MaxCharWidth
Tag_LineThickness
Tag_MinLeftBearing
Tag_MinRightBearing
Tag_UnderlinePosition
Tag_GlyphFormat
Tag_PixelSize
Tag_Weight
Tag_Style
Tag_EndOfHeader
Tag_WritingSystems
NumTags
Definition at line 77 of file qfontengine_qpa_p.h.
                    {
         Tag_FontName,          // 0 string
         Tag_FileName,          // 1 string
         Tag_FileIndex,         // 2 quint32
         Tag_FontRevision,      // 3 quint32
         Tag_FreeText,          // 4 string
         Tag_Ascent,            // 5 QFixed
         Tag_Descent,           // 6 QFixed
         Tag_Leading,           // 7 QFixed
         Tag_XHeight,           // 8 QFixed
         Tag_AverageCharWidth,  // 9 QFixed
         Tag_MaxCharWidth,      // 10 QFixed
         Tag_LineThickness,     // 11 QFixed
         Tag_MinLeftBearing,    // 12 QFixed
         Tag_MinRightBearing,   // 13 QFixed
         Tag_UnderlinePosition, // 14 QFixed
         Tag_GlyphFormat,       // 15 quint8
         Tag_PixelSize,         // 16 quint8
         Tag_Weight,            // 17 quint8
         Tag_Style,             // 18 quint8
         Tag_EndOfHeader,       // 19 string
         Tag_WritingSystems,    // 20 bitfield
         NumTags
     };
TagType
enum QFontEngineQPA::TagType
Enumerator
StringType
FixedType
UInt8Type
UInt32Type
BitFieldType
Definition at line 103 of file qfontengine_qpa_p.h.
                  {
         StringType,
         FixedType,
         UInt8Type,
         UInt32Type,
         BitFieldType
     };
Constructors and Destructors
QFontEngineQPA()
QFontEngineQPA::QFontEngineQPA (const QFontDef & def, const QByteArray & data)
Definition at line 237 of file qfontengine_qpa.cpp.
     : fontData(reinterpret_cast<const uchar *>(data.constData())), dataSize(data.size())
 {
     fontDef = def;
     cache_cost = 100;
     externalCMap = 0;
     cmapOffset = 0;
     cmapSize = 0;
     glyphMapOffset = 0;
     glyphMapEntries = 0;
     glyphDataOffset = 0;
     glyphDataSize = 0;
     kerning_pairs_loaded = false;
     readOnly = true;
 #if defined(DEBUG_FONTENGINE)
     qDebug() << "QFontEngineQPA::QFontEngineQPA( fd =" << fd << ", renderingFontEngine =" << renderingFontEngine << ')';
 #endif
     if (!verifyHeader(fontData, dataSize)) {
 #if defined(DEBUG_FONTENGINE)
         qDebug() << "verifyHeader failed!";
 #endif
         return;
     }
     const Header *header = reinterpret_cast<const Header *>(fontData);
     readOnly = (header->lock == 0xffffffff);
     const uchar *imgData = fontData + sizeof(Header) + qFromBigEndian<quint16>(header->dataSize);
     const uchar *endPtr = fontData + dataSize;
     while (imgData <= endPtr - 8) {
         quint16 blockTag = readValue<quint16>(imgData);
         imgData += 2; // skip padding
         quint32 blockSize = readValue<quint32>(imgData);
         if (blockTag == CMapBlock) {
             cmapOffset = imgData - fontData;
             cmapSize = blockSize;
         } else if (blockTag == GMapBlock) {
             glyphMapOffset = imgData - fontData;
             glyphMapEntries = blockSize / 4;
         } else if (blockTag == GlyphBlock) {
             glyphDataOffset = imgData - fontData;
             glyphDataSize = blockSize;
         }
         imgData += blockSize;
     }
     face_id.filename = QFile::encodeName(extractHeaderField(fontData, Tag_FileName).toString());
     face_id.index = extractHeaderField(fontData, Tag_FileIndex).toInt();
     // get the real cmap
     if (cmapOffset) {
         int tableSize = cmapSize;
         const uchar *cmapPtr = getCMap(fontData + cmapOffset, tableSize, &symbol, &cmapSize);
         if (cmapPtr)
             cmapOffset = cmapPtr - fontData;
         else
             cmapOffset = 0;
     } else if (externalCMap) {
         int tableSize = cmapSize;
         externalCMap = getCMap(externalCMap, tableSize, &symbol, &cmapSize);
     }
     // verify all the positions in the glyphMap
     if (glyphMapOffset) {
         const quint32 *gmapPtr = reinterpret_cast<const quint32 *>(fontData + glyphMapOffset);
         for (uint i = 0; i < glyphMapEntries; ++i) {
             quint32 glyphDataPos = qFromBigEndian<quint32>(gmapPtr[i]);
             if (glyphDataPos == 0xffffffff)
                 continue;
             if (glyphDataPos >= glyphDataSize) {
                 // error
                 glyphMapOffset = 0;
                 glyphMapEntries = 0;
                 break;
             }
         }
     }
 #if defined(DEBUG_FONTENGINE)
     if (!isValid())
         qDebug() << "fontData" <<  fontData << "dataSize" << dataSize
                  << "externalCMap" << externalCMap << "cmapOffset" << cmapOffset
                  << "glyphMapOffset" << glyphMapOffset << "glyphDataOffset" << glyphDataOffset
                  << "fd" << fd << "glyphDataSize" << glyphDataSize;
 #endif
 }
~QFontEngineQPA()
QFontEngineQPA::~QFontEngineQPA ()
Definition at line 329 of file qfontengine_qpa.cpp.
 {
 }
Functions
addOutlineToPath()
void QFontEngineQPA::addOutlineToPath (qreal x, qreal y, const QGlyphLayout & glyphs, QPainterPath * path, QTextItem::RenderFlags flags) virtual
Reimplemented from QFontEngine.
Definition at line 415 of file qfontengine_qpa.cpp.
 {
     addBitmapFontToPath(x, y, glyphs, path, flags);
 }
alphaMapForGlyph()
QImage QFontEngineQPA::alphaMapForGlyph (glyph_t glyph) virtual
Create a qimage with the alpha values for the glyph. Returns an image indexed_8 with index values ranging from 0=fully transparent to 255=opaque
Reimplemented from QFontEngine.
Definition at line 402 of file qfontengine_qpa.cpp.
 {
     const Glyph *glyph = findGlyph(g);
     if (!glyph)
         return QImage();
     const uchar *bits = ((const uchar *) glyph) + sizeof(Glyph);
     QImage image(bits,glyph->width, glyph->height, glyph->bytesPerLine, QImage::Format_Indexed8);
     return image;
 }
ascent()
QFixed QFontEngineQPA::ascent () const virtual
Implements QFontEngine.
Definition at line 462 of file qfontengine_qpa.cpp.
Referenced by boundingBox().
 {
     return QFixed::fromReal(extractHeaderField(fontData, Tag_Ascent).value<qreal>());
 }
boundingBox() [1/2]
glyph_metrics_t QFontEngineQPA::boundingBox (const QGlyphLayout & glyphs) virtual
Implements QFontEngine.
Definition at line 420 of file qfontengine_qpa.cpp.
 {
     glyph_metrics_t overall;
     // initialize with line height, we get the same behaviour on all platforms
     overall.y = -ascent();
     overall.height = ascent() + descent() + 1;
     QFixed ymax = 0;
     QFixed xmax = 0;
     for (int i = 0; i < glyphs.numGlyphs; i++) {
         const Glyph *g = findGlyph(glyphs.glyphs[i]);
         if (!g)
             continue;
         QFixed x = overall.xoff + glyphs.offsets[i].x + g->x;
         QFixed y = overall.yoff + glyphs.offsets[i].y + g->y;
         overall.x = qMin(overall.x, x);
         overall.y = qMin(overall.y, y);
         xmax = qMax(xmax, x + g->width);
         ymax = qMax(ymax, y + g->height);
         overall.xoff += g->advance;
     }
     overall.height = qMax(overall.height, ymax - overall.y);
     overall.width = xmax - overall.x;
     return overall;
 }
boundingBox() [2/2]
glyph_metrics_t QFontEngineQPA::boundingBox (glyph_t glyph) virtual
Implements QFontEngine.
Definition at line 448 of file qfontengine_qpa.cpp.
 {
     glyph_metrics_t overall;
     const Glyph *g = findGlyph(glyph);
     if (!g)
         return overall;
     overall.x = g->x;
     overall.y = g->y;
     overall.width = g->width;
     overall.height = g->height;
     overall.xoff = g->advance;
     return overall;
 }
canRender()
bool QFontEngineQPA::canRender (const QChar * string, int len) virtual
Implements QFontEngine.
Definition at line 507 of file qfontengine_qpa.cpp.
 {
     const uchar *cmap = externalCMap ? externalCMap : (fontData + cmapOffset);
     if (symbol) {
         for (int i = 0; i < len; ++i) {
             unsigned int uc = getChar(string, i, len);
             glyph_t g = getTrueTypeGlyphIndex(cmap, uc);
             if(!g && uc < 0x100)
                 g = getTrueTypeGlyphIndex(cmap, uc + 0xf000);
             if (!g)
                 return false;
         }
     } else {
         for (int i = 0; i < len; ++i) {
             unsigned int uc = getChar(string, i, len);
             if (!getTrueTypeGlyphIndex(cmap, uc))
                 return false;
         }
     }
     return true;
 }
descent()
QFixed QFontEngineQPA::descent () const virtual
Implements QFontEngine.
Definition at line 467 of file qfontengine_qpa.cpp.
Referenced by boundingBox().
 {
     return QFixed::fromReal(extractHeaderField(fontData, Tag_Descent).value<qreal>());
 }
extractHeaderField()
QVariant QFontEngineQPA::extractHeaderField (const uchar * data, HeaderTag tag) static
Definition at line 194 of file qfontengine_qpa.cpp.
Referenced by ascent(), descent(), leading(), lineThickness(), maxCharWidth(), minLeftBearing(), minRightBearing(), QFontEngineQPA(), QPlatformFontDatabase::registerQPF2Font(), and underlinePosition().
 {
     const Header *header = reinterpret_cast<const Header *>(data);
     const uchar *tagPtr = data + sizeof(Header);
     const uchar *endPtr = tagPtr + qFromBigEndian<quint16>(header->dataSize);
     while (tagPtr < endPtr - 3) {
         quint16 tag = readValue<quint16>(tagPtr);
         quint16 length = readValue<quint16>(tagPtr);
         if (tag == requestedTag) {
             switch (tagTypes[requestedTag]) {
                 case StringType:
                     return QVariant(QString::fromUtf8(reinterpret_cast<const char *>(tagPtr), length));
                 case UInt32Type:
                     return QVariant(readValue<quint32>(tagPtr));
                 case UInt8Type:
                     return QVariant(uint(*tagPtr));
                 case FixedType:
                     return QVariant(QFixed::fromFixed(readValue<quint32>(tagPtr)).toReal());
                 case BitFieldType:
                     return QVariant(QByteArray(reinterpret_cast<const char *>(tagPtr), length));
             }
             return QVariant();
         } else if (tag == Tag_EndOfHeader) {
             break;
         }
         tagPtr += length;
     }
     return QVariant();
 }
faceId()
FaceId QFontEngineQPA::faceId () const inline virtual
Reimplemented from QFontEngine.
Definition at line 165 of file qfontengine_qpa_p.h.
 { return face_id; }
findGlyph()
const QFontEngineQPA::Glyph * QFontEngineQPA::findGlyph (glyph_t g) const
Definition at line 151 of file qfontengine_qpa.cpp.
Referenced by alphaMapForGlyph(), boundingBox(), recalcAdvances(), and stringToCMap().
 {
     if (!g || g >= glyphMapEntries)
         return 0;
     const quint32 *gmapPtr = reinterpret_cast<const quint32 *>(fontData + glyphMapOffset);
     quint32 glyphPos = qFromBigEndian<quint32>(gmapPtr[g]);
     if (glyphPos > glyphDataSize) {
         if (glyphPos == 0xffffffff)
             return 0;
 #if defined(DEBUG_FONTENGINE)
         qDebug() << "glyph" << g << "outside of glyphData, remapping font file";
 #endif
         if (glyphPos > glyphDataSize)
             return 0;
     }
     return reinterpret_cast<const Glyph *>(fontData + glyphDataOffset + glyphPos);
 }
getSfntTableData()
bool QFontEngineQPA::getSfntTableData (uint tag, uchar * buffer, uint * length) const virtual
Reimplemented from QFontEngine.
Definition at line 333 of file qfontengine_qpa.cpp.
 {
     Q_UNUSED(tag);
     Q_UNUSED(buffer);
     *length = 0;
     return false;
 }
glyphCount()
virtual int QFontEngineQPA::glyphCount () const inline virtual
Reimplemented from QFontEngine.
Definition at line 191 of file qfontengine_qpa_p.h.
Referenced by QPAGenerator::writeGMap().
 { return glyphMapEntries; }
isValid()
bool QFontEngineQPA::isValid () const
Definition at line 530 of file qfontengine_qpa.cpp.
Referenced by QFontEngineQPA().
 {
     return fontData && dataSize && (cmapOffset || externalCMap)
            && glyphMapOffset && glyphDataOffset && glyphDataSize > 0;
 }
leading()
QFixed QFontEngineQPA::leading () const virtual
Implements QFontEngine.
Definition at line 472 of file qfontengine_qpa.cpp.
 {
     return QFixed::fromReal(extractHeaderField(fontData, Tag_Leading).value<qreal>());
 }
lineThickness()
QFixed QFontEngineQPA::lineThickness () const virtual
Reimplemented from QFontEngine.
Definition at line 497 of file qfontengine_qpa.cpp.
 {
     return QFixed::fromReal(extractHeaderField(fontData, Tag_LineThickness).value<qreal>());
 }
maxCharWidth()
qreal QFontEngineQPA::maxCharWidth () const virtual
Implements QFontEngine.
Definition at line 477 of file qfontengine_qpa.cpp.
 {
     return extractHeaderField(fontData, Tag_MaxCharWidth).value<qreal>();
 }
minLeftBearing()
qreal QFontEngineQPA::minLeftBearing () const virtual
Reimplemented from QFontEngine.
Definition at line 482 of file qfontengine_qpa.cpp.
 {
     return extractHeaderField(fontData, Tag_MinLeftBearing).value<qreal>();
 }
minRightBearing()
qreal QFontEngineQPA::minRightBearing () const virtual
Reimplemented from QFontEngine.
Definition at line 487 of file qfontengine_qpa.cpp.
 {
     return extractHeaderField(fontData, Tag_MinRightBearing).value<qreal>();
 }
name()
const char* QFontEngineQPA::name () const inline virtual
Implements QFontEngine.
Definition at line 189 of file qfontengine_qpa_p.h.
 { return "QPF2"; }
recalcAdvances()
void QFontEngineQPA::recalcAdvances (QGlyphLayout * , QTextEngine::ShaperFlags) const virtual
This is a callback from harfbuzz. The font engine uses the font-system in use to find out the advances of each glyph and set it on the layout.
Reimplemented from QFontEngine.
Definition at line 389 of file qfontengine_qpa.cpp.
Referenced by stringToCMap().
 {
     for (int i = 0; i < glyphs->numGlyphs; ++i) {
         const Glyph *g = findGlyph(glyphs->glyphs[i]);
         if (!g) {
             glyphs->glyphs[i] = 0;
             continue;
         }
         glyphs->advances_x[i] = g->advance;
         glyphs->advances_y[i] = 0;
     }
 }
stringToCMap()
bool QFontEngineQPA::stringToCMap (const QChar * str, int len, QGlyphLayout * glyphs, int * nglyphs, QTextEngine::ShaperFlags flags) const virtual
Implements QFontEngine.
Definition at line 341 of file qfontengine_qpa.cpp.
 {
     if (*nglyphs < len) {
         *nglyphs = len;
         return false;
     }
 #if defined(DEBUG_FONTENGINE)
     QSet<QChar> seenGlyphs;
 #endif
     const uchar *cmap = externalCMap ? externalCMap : (fontData + cmapOffset);
     bool mirrored = flags & QTextEngine::RightToLeft;
     int glyph_pos = 0;
     if (symbol) {
         for (int i = 0; i < len; ++i) {
             unsigned int uc = getChar(str, i, len);
             if (mirrored)
                 uc = QChar::mirroredChar(uc);
             glyphs->glyphs[glyph_pos] = getTrueTypeGlyphIndex(cmap, uc);
             if(!glyphs->glyphs[glyph_pos] && uc < 0x100)
                 glyphs->glyphs[glyph_pos] = getTrueTypeGlyphIndex(cmap, uc + 0xf000);
             ++glyph_pos;
         }
     } else {
         for (int i = 0; i < len; ++i) {
             unsigned int uc = getChar(str, i, len);
             if (mirrored)
                 uc = QChar::mirroredChar(uc);
             glyphs->glyphs[glyph_pos] = getTrueTypeGlyphIndex(cmap, uc);
 #if 0 && defined(DEBUG_FONTENGINE)
             QChar c(uc);
             if (!findGlyph(glyphs[glyph_pos].glyph) && !seenGlyphs.contains(c))
                 qDebug() << "glyph for character" << c << '/' << hex << uc << "is" << dec << glyphs[glyph_pos].glyph;
             seenGlyphs.insert(c);
 #endif
             ++glyph_pos;
         }
     }
     *nglyphs = glyph_pos;
     glyphs->numGlyphs = glyph_pos;
     recalcAdvances(glyphs, flags);
     return true;
 }
type()
QFontEngine::Type QFontEngineQPA::type () const virtual
Implements QFontEngine.
Definition at line 502 of file qfontengine_qpa.cpp.
 {
     return QFontEngine::QPF2;
 }
underlinePosition()
QFixed QFontEngineQPA::underlinePosition () const virtual
Reimplemented from QFontEngine.
Definition at line 492 of file qfontengine_qpa.cpp.
 {
     return QFixed::fromReal(extractHeaderField(fontData, Tag_UnderlinePosition).value<qreal>());
 }
verifyHeader()
bool QFontEngineQPA::verifyHeader (const uchar * data, int size) static
Definition at line 169 of file qfontengine_qpa.cpp.
Referenced by QFontEngineQPA(), and QPlatformFontDatabase::registerQPF2Font().
 {
     VERIFY(size >= int(sizeof(Header)));
     const Header *header = reinterpret_cast<const Header *>(data);
     if (header->magic[0] != 'Q'
         || header->magic[1] != 'P'
         || header->magic[2] != 'F'
         || header->magic[3] != '2')
         return false;
     VERIFY(header->majorVersion <= CurrentMajorVersion);
     const quint16 dataSize = qFromBigEndian<quint16>(header->dataSize);
     VERIFY(size >= int(sizeof(Header)) + dataSize);
     const uchar *tagPtr = data + sizeof(Header);
     const uchar *tagEndPtr = tagPtr + dataSize;
     while (tagPtr < tagEndPtr - 3) {
         tagPtr = verifyTag(tagPtr, tagEndPtr);
         VERIFY(tagPtr);
     }
     VERIFY(tagPtr <= tagEndPtr);
     return true;
 }
Properties
cmapOffset
quint32 QFontEngineQPA::cmapOffset private
Definition at line 205 of file qfontengine_qpa_p.h.
Referenced by canRender(), isValid(), QFontEngineQPA(), and stringToCMap().
cmapSize
int QFontEngineQPA::cmapSize private
Definition at line 206 of file qfontengine_qpa_p.h.
Referenced by QFontEngineQPA().
dataSize
int QFontEngineQPA::dataSize private
Definition at line 203 of file qfontengine_qpa_p.h.
Referenced by isValid(), QFontEngineQPA(), and verifyHeader().
encodedFileName
QString QFontEngineQPA::encodedFileName private
Definition at line 212 of file qfontengine_qpa_p.h.
externalCMap
const uchar* QFontEngineQPA::externalCMap private
Definition at line 204 of file qfontengine_qpa_p.h.
Referenced by canRender(), isValid(), QFontEngineQPA(), and stringToCMap().
face_id
FaceId QFontEngineQPA::face_id private
Definition at line 215 of file qfontengine_qpa_p.h.
Referenced by QFontEngineQPA().
fontData
const uchar* QFontEngineQPA::fontData private
Definition at line 202 of file qfontengine_qpa_p.h.
Referenced by ascent(), canRender(), descent(), findGlyph(), isValid(), leading(), lineThickness(), maxCharWidth(), minLeftBearing(), minRightBearing(), QFontEngineQPA(), stringToCMap(), and underlinePosition().
freetypeCMapTable
QByteArray QFontEngineQPA::freetypeCMapTable private
Definition at line 216 of file qfontengine_qpa_p.h.
glyphDataOffset
quint32 QFontEngineQPA::glyphDataOffset private
Definition at line 209 of file qfontengine_qpa_p.h.
Referenced by findGlyph(), isValid(), and QFontEngineQPA().
glyphDataSize
quint32 QFontEngineQPA::glyphDataSize private
Definition at line 210 of file qfontengine_qpa_p.h.
Referenced by findGlyph(), isValid(), and QFontEngineQPA().
glyphMapEntries
quint32 QFontEngineQPA::glyphMapEntries private
Definition at line 208 of file qfontengine_qpa_p.h.
Referenced by findGlyph(), and QFontEngineQPA().
glyphMapOffset
quint32 QFontEngineQPA::glyphMapOffset private
Definition at line 207 of file qfontengine_qpa_p.h.
Referenced by findGlyph(), isValid(), and QFontEngineQPA().
internalFileName
QString QFontEngineQPA::internalFileName private
Definition at line 211 of file qfontengine_qpa_p.h.
kerning_pairs_loaded
bool QFontEngineQPA::kerning_pairs_loaded mutable private
Definition at line 217 of file qfontengine_qpa_p.h.
Referenced by QFontEngineQPA().
readOnly
bool QFontEngineQPA::readOnly private
Definition at line 213 of file qfontengine_qpa_p.h.
Referenced by QFontEngineQPA().
The documentation for this class was generated from the following files:
/src/gui/text/qfontengine_qpa_p.h
/src/gui/text/qfontengine_qpa.cpp