Qt 4.8: QScript::QMetaObjectWrapperObject Class Reference
QScript::QMetaObjectWrapperObject Class Reference
#include <qscriptqobject_p.h>
Classes
struct Data
Public Functions
virtual const JSC::ClassInfo * classInfo () const
virtual bool deleteProperty (JSC::ExecState *, const JSC::Identifier &propertyName)
JSC::JSValue execute (JSC::ExecState *exec, const JSC::ArgList &args)
virtual JSC::CallType getCallData (JSC::CallData &)
virtual JSC::ConstructType getConstructData (JSC::ConstructData &)
virtual bool getOwnPropertyDescriptor (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertyDescriptor &)
virtual void getOwnPropertyNames (JSC::ExecState *, JSC::PropertyNameArray &, JSC::EnumerationMode mode=JSC::ExcludeDontEnumProperties)
virtual bool getOwnPropertySlot (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertySlot &)
virtual void markChildren (JSC::MarkStack &markStack)
virtual void put (JSC::ExecState *exec, const JSC::Identifier &propertyName, JSC::JSValue, JSC::PutPropertySlot &)
QMetaObjectWrapperObject (JSC::ExecState *, const QMetaObject *metaobject, JSC::JSValue ctor, WTF::PassRefPtr< JSC::Structure > sid)
void setValue (const QMetaObject *value)
const QMetaObject * value () const
~QMetaObjectWrapperObject ()
Static Public Functions
static JSC::JSValue JSC_HOST_CALL call (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSObject * construct (JSC::ExecState *, JSC::JSObject *, const JSC::ArgList &)
static WTF::PassRefPtr< JSC::Structure > createStructure (JSC::JSValue prototype)
Static Public Variables
static const JSC::ClassInfo info = { "QMetaObject", 0, 0, 0 }
Protected Variables
Data * data
Static Protected Variables
static const unsigned StructureFlags = JSC::OverridesGetOwnPropertySlot | JSC::OverridesMarkChildren | JSC::OverridesGetPropertyNames | JSC::ImplementsHasInstance | JSObject::StructureFlags
Detailed Description
Definition at line 252 of file qscriptqobject_p.h.
Constructors and Destructors
QMetaObjectWrapperObject()
QScript::QMetaObjectWrapperObject::QMetaObjectWrapperObject (JSC::ExecState * exec, const QMetaObject * metaobject, JSC::JSValue ctor, WTF::PassRefPtr< JSC::Structure > sid) explicit
Definition at line 1774 of file qscriptqobject.cpp.
     : JSC::JSObject(sid),
       data(new Data(metaObject, ctor))
 {
     if (!ctor)
         data->prototype = new (exec)JSC::JSObject(exec->lexicalGlobalObject()->emptyObjectStructure());
 }
~QMetaObjectWrapperObject()
QScript::QMetaObjectWrapperObject::~QMetaObjectWrapperObject ()
Definition at line 1784 of file qscriptqobject.cpp.
 {
     delete data;
 }
Functions
call()
JSC::JSValue JSC_HOST_CALL QScript::QMetaObjectWrapperObject::call (JSC::ExecState * exec, JSC::JSObject * callee, JSC::JSValue thisValue, const JSC::ArgList & args) static
Definition at line 1933 of file qscriptqobject.cpp.
Referenced by getCallData().
 {
     QScriptEnginePrivate *eng_p = scriptEngineFromExec(exec);
     thisValue = eng_p->toUsableValue(thisValue);
     if (!callee->inherits(&QMetaObjectWrapperObject::info))
         return throwError(exec, JSC::TypeError, "callee is not a QMetaObject");
     QMetaObjectWrapperObject *self =  static_cast<QMetaObjectWrapperObject*>(callee);
     JSC::ExecState *previousFrame = eng_p->currentFrame;
     eng_p->pushContext(exec, thisValue, args, callee);
     JSC::JSValue result = self->execute(eng_p->currentFrame, args);
     eng_p->popContext();
     eng_p->currentFrame = previousFrame;
     return result;
 }
classInfo()
virtual const JSC::ClassInfo* QScript::QMetaObjectWrapperObject::classInfo () const inline virtual
Definition at line 288 of file qscriptqobject_p.h.
 { return &info; }
construct()
JSC::JSObject * QScript::QMetaObjectWrapperObject::construct (JSC::ExecState * exec, JSC::JSObject * callee, const JSC::ArgList & args) static
Definition at line 1950 of file qscriptqobject.cpp.
Referenced by getConstructData().
 {
     QMetaObjectWrapperObject *self = static_cast<QMetaObjectWrapperObject*>(callee);
     QScriptEnginePrivate *eng_p = scriptEngineFromExec(exec);
     JSC::ExecState *previousFrame = eng_p->currentFrame;
     eng_p->pushContext(exec, JSC::JSValue(), args, callee, true);
     JSC::JSValue result = self->execute(eng_p->currentFrame, args);
     eng_p->popContext();
     eng_p->currentFrame = previousFrame;
     if (!result || !result.isObject())
         return 0;
     return JSC::asObject(result);
 }
createStructure()
static WTF::PassRefPtr<JSC::Structure> QScript::QMetaObjectWrapperObject::createStructure (JSC::JSValue prototype) inline static
Definition at line 300 of file qscriptqobject_p.h.
Referenced by QScriptEnginePrivate::QScriptEnginePrivate().
     {
         return JSC::Structure::create(prototype, JSC::TypeInfo(JSC::ObjectType, StructureFlags));
     }
deleteProperty()
bool QScript::QMetaObjectWrapperObject::deleteProperty (JSC::ExecState * exec, const JSC::Identifier & propertyName) virtual
Definition at line 1878 of file qscriptqobject.cpp.
 {
     if (propertyName == exec->propertyNames().prototype)
         return false;
     const QMetaObject *meta = data->value;
     if (meta) {
         QByteArray name = convertToLatin1(propertyName.ustring());
         for (int i = 0; i < meta->enumeratorCount(); ++i) {
             QMetaEnum e = meta->enumerator(i);
             for (int j = 0; j < e.keyCount(); ++j) {
                 if (!qstrcmp(e.key(j), name.constData()))
                     return false;
             }
         }
     }
     return JSC::JSObject::deleteProperty(exec, propertyName);
 }
execute()
JSC::JSValue QScript::QMetaObjectWrapperObject::execute (JSC::ExecState * exec, const JSC::ArgList & args)
Definition at line 1964 of file qscriptqobject.cpp.
Referenced by QScript::QObjectConnectionManager::qt_metacall().
 {
     if (data->ctor) {
         QScriptEnginePrivate *eng_p = QScript::scriptEngineFromExec(exec);
         QScriptContext *ctx = eng_p->contextForFrame(exec);
         JSC::CallData callData;
         JSC::CallType callType = data->ctor.getCallData(callData);
         Q_UNUSED(callType);
         Q_ASSERT_X(callType == JSC::CallTypeHost, Q_FUNC_INFO, "script constructors not supported");
         if (data->ctor.inherits(&FunctionWithArgWrapper::info)) {
             FunctionWithArgWrapper *wrapper = static_cast<FunctionWithArgWrapper*>(JSC::asObject(data->ctor));
             QScriptValue result = wrapper->function()(ctx, QScriptEnginePrivate::get(eng_p), wrapper->arg());
             return eng_p->scriptValueToJSCValue(result);
         } else {
             Q_ASSERT(data->ctor.inherits(&FunctionWrapper::info));
             FunctionWrapper *wrapper = static_cast<FunctionWrapper*>(JSC::asObject(data->ctor));
             QScriptValue result = wrapper->function()(ctx, QScriptEnginePrivate::get(eng_p));
             return eng_p->scriptValueToJSCValue(result);
         }
     } else {
         const QMetaObject *meta = data->value;
         if (meta->constructorCount() > 0) {
             JSC::JSValue result = callQtMethod(exec, QMetaMethod::Constructor, /*thisQObject=*/0,
                                                args, meta, meta->constructorCount()-1, /*maybeOverloaded=*/true);
             if (!exec->hadException()) {
                 Q_ASSERT(result && result.inherits(&QScriptObject::info));
                 QScriptObject *object = static_cast<QScriptObject*>(JSC::asObject(result));
                 QScript::QObjectDelegate *delegate = static_cast<QScript::QObjectDelegate*>(object->delegate());
                 delegate->setOwnership(QScriptEngine::AutoOwnership);
                 if (data->prototype)
                     object->setPrototype(data->prototype);
             }
             return result;
         } else {
             QString message = QString::fromLatin1("no constructor for %0")
                               .arg(QLatin1String(meta->className()));
             return JSC::throwError(exec, JSC::TypeError, message);
         }
     }
 }
getCallData()
JSC::CallType QScript::QMetaObjectWrapperObject::getCallData (JSC::CallData & callData) virtual
Definition at line 1921 of file qscriptqobject.cpp.
 {
     callData.native.function = call;
     return JSC::CallTypeHost;
 }
getConstructData()
JSC::ConstructType QScript::QMetaObjectWrapperObject::getConstructData (JSC::ConstructData & constructData) virtual
Definition at line 1927 of file qscriptqobject.cpp.
 {
     constructData.native.function = construct;
     return JSC::ConstructTypeHost;
 }
getOwnPropertyDescriptor()
bool QScript::QMetaObjectWrapperObject::getOwnPropertyDescriptor (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertyDescriptor & descriptor) virtual
Definition at line 1821 of file qscriptqobject.cpp.
 {
     const QMetaObject *meta = data->value;
     if (!meta)
         return false;
     if (propertyName == exec->propertyNames().prototype) {
         descriptor.setDescriptor(data->ctor
                                  ? data->ctor.get(exec, propertyName)
                                  : data->prototype,
                                  JSC::DontDelete | JSC::DontEnum);
         return true;
     }
     QByteArray name = QString(propertyName.ustring()).toLatin1();
     for (int i = 0; i < meta->enumeratorCount(); ++i) {
         QMetaEnum e = meta->enumerator(i);
         for (int j = 0; j < e.keyCount(); ++j) {
             const char *key = e.key(j);
             if (!qstrcmp(key, name.constData())) {
                 descriptor.setDescriptor(JSC::JSValue(exec, e.value(j)),
                                          JSC::ReadOnly | JSC::DontDelete);
                 return true;
             }
         }
     }
     return JSC::JSObject::getOwnPropertyDescriptor(exec, propertyName, descriptor);
 }
getOwnPropertyNames()
void QScript::QMetaObjectWrapperObject::getOwnPropertyNames (JSC::ExecState * exec, JSC::PropertyNameArray & propertyNames, JSC::EnumerationMode mode = JSC::ExcludeDontEnumProperties) virtual
Definition at line 1897 of file qscriptqobject.cpp.
 {
     const QMetaObject *meta = data->value;
     if (!meta)
         return;
     for (int i = 0; i < meta->enumeratorCount(); ++i) {
         QMetaEnum e = meta->enumerator(i);
         for (int j = 0; j < e.keyCount(); ++j)
             propertyNames.add(JSC::Identifier(exec, e.key(j)));
     }
     JSC::JSObject::getOwnPropertyNames(exec, propertyNames, mode);
 }
getOwnPropertySlot()
bool QScript::QMetaObjectWrapperObject::getOwnPropertySlot (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertySlot & slot) virtual
Definition at line 1789 of file qscriptqobject.cpp.
 {
     const QMetaObject *meta = data->value;
     if (!meta)
         return false;
     if (propertyName == exec->propertyNames().prototype) {
         if (data->ctor)
             slot.setValue(data->ctor.get(exec, propertyName));
         else
             slot.setValue(data->prototype);
         return true;
     }
     QByteArray name = convertToLatin1(propertyName.ustring());
     for (int i = 0; i < meta->enumeratorCount(); ++i) {
         QMetaEnum e = meta->enumerator(i);
         for (int j = 0; j < e.keyCount(); ++j) {
             const char *key = e.key(j);
             if (!qstrcmp(key, name.constData())) {
                 slot.setValue(JSC::JSValue(exec, e.value(j)));
                 return true;
             }
         }
     }
     return JSC::JSObject::getOwnPropertySlot(exec, propertyName, slot);
 }
markChildren()
void QScript::QMetaObjectWrapperObject::markChildren (JSC::MarkStack & markStack) virtual
Definition at line 1912 of file qscriptqobject.cpp.
 {
     if (data->ctor)
         markStack.append(data->ctor);
     if (data->prototype)
         markStack.append(data->prototype);
     JSC::JSObject::markChildren(markStack);
 }
put()
void QScript::QMetaObjectWrapperObject::put (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSValue value, JSC::PutPropertySlot & slot) virtual
Definition at line 1854 of file qscriptqobject.cpp.
 {
     if (propertyName == exec->propertyNames().prototype) {
         if (data->ctor)
             data->ctor.put(exec, propertyName, value, slot);
         else
             data->prototype = value;
         return;
     }
     const QMetaObject *meta = data->value;
     if (meta) {
         QByteArray name = convertToLatin1(propertyName.ustring());
         for (int i = 0; i < meta->enumeratorCount(); ++i) {
             QMetaEnum e = meta->enumerator(i);
             for (int j = 0; j < e.keyCount(); ++j) {
                 if (!qstrcmp(e.key(j), name.constData()))
                     return;
             }
         }
     }
     JSC::JSObject::put(exec, propertyName, value, slot);
 }
setValue()
void QScript::QMetaObjectWrapperObject::setValue (const QMetaObject * value) inline
Definition at line 298 of file qscriptqobject_p.h.
 { data->value = value; }
value()
const QMetaObject* QScript::QMetaObjectWrapperObject::value () const inline
Definition at line 297 of file qscriptqobject_p.h.
Referenced by put(), and QScript::qmetaobjectProtoFuncClassName().
 { return data->value; }
Properties
data
Data* QScript::QMetaObjectWrapperObject::data protected
Definition at line 308 of file qscriptqobject_p.h.
Referenced by deleteProperty(), execute(), getOwnPropertyDescriptor(), getOwnPropertyNames(), getOwnPropertySlot(), markChildren(), put(), QMetaObjectWrapperObject(), and ~QMetaObjectWrapperObject().
info
const JSC::ClassInfo QScript::QMetaObjectWrapperObject::info = { "QMetaObject", 0, 0, 0 } static
Definition at line 289 of file qscriptqobject_p.h.
Referenced by QScriptEnginePrivate::isQMetaObject(), and QScript::QObjectPrototype::QObjectPrototype().
StructureFlags
const unsigned QScript::QMetaObjectWrapperObject::StructureFlags = JSC::OverridesGetOwnPropertySlot | JSC::OverridesMarkChildren | JSC::OverridesGetPropertyNames | JSC::ImplementsHasInstance | JSObject::StructureFlags static protected
Definition at line 306 of file qscriptqobject_p.h.
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptqobject_p.h
/src/script/bridge/qscriptqobject.cpp