Qt 4.8: QAInterface Class Reference
QAInterface Class Reference
#include <qaccessible_mac_p.h>
Public Functions
QString actionText (int action, Text text) const
QObject * cachedObject () const
QAInterface childAt (int x, int y) const
QAInterface childAt (int index) const
int childCount () const
QList< QAInterface > children () const
QString className () const
void doAction (int action, const QVariantList &params=QVariantList()) const
HIObjectRef hiObject () const
int id () const
int indexOfChild (const QAInterface &child) const
QAccessibleInterfaceWrapper interfaceWrapper () const
bool isHIView () const
bool isValid () const
QString name () const
QAInterface navigate (RelationFlag relation, int entry) const
QObject * object () const
QAInterface objectInterface () const
bool operator!= (const QAInterface &other) const
bool operator== (const QAInterface &other) const
QAInterface parent () const
QAInterface ()
QAInterface (QAccessibleInterface *interface, int child=0)
QAInterface (QAccessibleInterfaceWrapper wrapper, int child=0)
QAInterface (const QAInterface &other, int child)
QRect rect () const
Role role () const
void setText (Text t, const QString &text) const
State state () const
QString text (Text text) const
int userActionCount () const
QString value () const
Protected Functions
bool checkValid () const
Protected Variables
QAccessibleInterfaceWrapper base
int child
QObject * m_cachedObject
Additional Inherited Members
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
Definition at line 127 of file qaccessible_mac_p.h.
Constructors and Destructors
QAInterface() [1/4]
QAInterface::QAInterface () inline
Definition at line 130 of file qaccessible_mac_p.h.
Referenced by QAccessibleHierarchyManager::lookup(), navigate(), and QAccessibleHierarchyManager::registerInterface().
     : base(QAccessibleInterfaceWrapper())
     { }
QAInterface() [2/4]
QAInterface::QAInterface (QAccessibleInterface * interface, int child = 0) inline
Definition at line 134 of file qaccessible_mac_p.h.
     {
         if (interface == 0 || child > interface->childCount()) {
            base = QAccessibleInterfaceWrapper();
         } else {
             base = QAccessibleInterfaceWrapper(interface);
             m_cachedObject = interface->object();
             this->child = child;
         }
     }
QAInterface() [3/4]
QAInterface::QAInterface (QAccessibleInterfaceWrapper wrapper, int child = 0) inline
Definition at line 145 of file qaccessible_mac_p.h.
     :base(wrapper), m_cachedObject(wrapper.interface->object()), child(child)
     { }
QAInterface() [4/4]
QAInterface::QAInterface (const QAInterface & other, int child) inline
Definition at line 149 of file qaccessible_mac_p.h.
     {
         if (other.isValid() == false || child > other.childCount()) {
            base = QAccessibleInterfaceWrapper();
         } else {
             base = other.base;
             m_cachedObject = other.m_cachedObject;
             this->child = child;
         }
     }
Functions
actionText()
QString QAInterface::actionText (int action, Text text) const inline
Definition at line 163 of file qaccessible_mac_p.h.
Referenced by getAllActionNames(), and performNamedAction().
     { return base.interface->actionText(action, text, child); }
cachedObject()
QObject* QAInterface::cachedObject () const inline
Definition at line 272 of file qaccessible_mac_p.h.
Referenced by qHash().
     {
         if (!checkValid())
             return 0;
         return m_cachedObject;
     }
checkValid()
bool QAInterface::checkValid () const inline protected
Definition at line 352 of file qaccessible_mac_p.h.
Referenced by navigate().
     {
         const bool valid = isValid();
 #ifdef Q_ACCESSIBLE_MAC_DEBUG
         if (!valid)
             qFatal("QAccessible_mac: tried to use invalid interface.");
 #endif
         return valid;
     }
childAt() [1/2]
QAInterface QAInterface::childAt (int x, int y) const inline
Definition at line 166 of file qaccessible_mac_p.h.
Referenced by getChildAtPoint(), getNamedAttribute(), QItemViewInterfaceFactory::interface(), managesChildren(), scrollAreaGetScrollBarInterface(), tabWidgetGetContents(), and tabWidgetGetTabs().
     {
         if (!checkValid())
             return QAInterface();
         const int foundChild = base.interface->childAt(x, y);
         if (foundChild == -1)
             return QAInterface();
         if (child == 0)
             return navigate(QAccessible::Child, foundChild);
         if (foundChild == child)
             return *this;
         return QAInterface();
     }
childAt() [2/2]
QAInterface QAInterface::childAt (int index) const inline
Definition at line 220 of file qaccessible_mac_p.h.
     {
         return navigate(QAccessible::Child, index);
     }
childCount()
int QAInterface::childCount () const inline
Definition at line 198 of file qaccessible_mac_p.h.
Referenced by QItemViewInterfaceFactory::element(), getNamedAttribute(), managesChildren(), QAInterface(), scrollAreaGetScrollBarInterface(), supportsAttribute(), tabBarGetTabs(), and QAccessible::updateAccessibility().
     {
         if (!checkValid())
             return 0;
         if (child != 0)
             return 0;
         return base.interface->childCount();
     }
children()
QList<QAInterface> QAInterface::children () const inline
Definition at line 208 of file qaccessible_mac_p.h.
Referenced by handleChildrenAttribute(), handleRowsAttribute(), handleSelectedRowsAttribute(), and handleVisibleRowsAttribute().
     {
         if (!checkValid())
             return QList<QAInterface>();
         QList<QAInterface> children;
         for (int i = 1; i <= childCount(); ++i) {
             children.append(navigate(QAccessible::Child, i));
         }
         return children;
     }
className()
QString QAInterface::className () const inline
Definition at line 327 of file qaccessible_mac_p.h.
     {
         if (!checkValid())
             return QString();
         return QLatin1String(base.interface->object()->metaObject()->className());
     }
doAction()
void QAInterface::doAction (int action, const QVariantList & params = QVariantList()) const inline
Definition at line 225 of file qaccessible_mac_p.h.
Referenced by performNamedAction(), and setNamedAttribute().
     {
         if (!checkValid())
             return;
         base.interface->doAction(action, child, params);
     }
hiObject()
HIObjectRef QAInterface::hiObject () const inline
Definition at line 261 of file qaccessible_mac_p.h.
Referenced by QAccessibleHierarchyManager::lookup(), QAccessibleHierarchyManager::objectDestroyed(), and QAccessibleHierarchyManager::registerInterface().
     {
         if (!checkValid())
             return 0;
         QWidget * const widget = qobject_cast<QWidget * const>(object());
         if (widget)
             return (HIObjectRef)widget->winId();
         else
             return 0;
     }
id()
int QAInterface::id () const inline
Definition at line 337 of file qaccessible_mac_p.h.
Referenced by QInterfaceFactory::element(), QStandardInterfaceFactory::element(), indexOfChild(), isTabWidget(), macRole(), managesChildren(), operator<<(), operator==(), qHash(), QAccessibleHierarchyManager::registerInterface(), and subrole().
     { return child; }
indexOfChild()
int QAInterface::indexOfChild (const QAInterface & child) const inline
Definition at line 184 of file qaccessible_mac_p.h.
Referenced by QItemViewInterfaceFactory::element(), and operator==().
     {
         if (!checkValid())
             return -1;
         if (*this != child.parent())
             return -1;
         if (object() == child.object())
             return child.id();
         return base.interface->indexOfChild(child.base.interface);
     }
interfaceWrapper()
QAccessibleInterfaceWrapper QAInterface::interfaceWrapper () const inline
Definition at line 348 of file qaccessible_mac_p.h.
     { return base; }
isHIView()
bool QAInterface::isHIView () const inline
Definition at line 334 of file qaccessible_mac_p.h.
Referenced by handleChildrenAttribute(), handleParentAttribute(), navigateAncestors(), and QAccessible::updateAccessibility().
     { return (child == 0 && object() != 0); }
isValid()
bool QAInterface::isValid () const inline
Definition at line 340 of file qaccessible_mac_p.h.
Referenced by accessibilityEventHandler(), QItemViewInterfaceFactory::element(), getChildAtPoint(), getNamedAttribute(), handleSplitterContentsAttribute(), QAccessibleHierarchyManager::lookup(), lookup(), macRole(), navigateAncestors(), objectInterface(), operator<<(), operator==(), QAInterface(), qHash(), QAccessibleHierarchyManager::registerInterface(), scrollAreaGetScrollBarInterface(), scrollAreaHasScrollBar(), subrole(), tabBarGetTabs(), and QAccessible::updateAccessibility().
     {
         return (base.interface != 0 && base.interface->isValid());
     }
name()
QString QAInterface::name () const inline
Definition at line 317 of file qaccessible_mac_p.h.
     { return text(QAccessible::Name); }
navigate()
QAInterface QAInterface::navigate (RelationFlag relation, int entry) const
Definition at line 449 of file qaccessible_mac.mm.
Referenced by getNamedAttribute(), handleParentAttribute(), scrollAreaGetContents(), tabBarGetTabs(), and QAccessible::updateAccessibility().
 {
         if (!checkValid())
             return QAInterface();
     // On a QAccessibleInterface that handles its own children we can short-circut
     // the navigation if this QAInterface refers to one of the children:
     if (child != 0) {
         // The Ancestor interface will always be the same QAccessibleInterface with
         // a child value of 0.
         if (relation == QAccessible::Ancestor)
             return QAInterface(*this, 0);
         // The child hiearchy is only one level deep, so navigating to a child
         // of a child is not possible.
         if (relation == QAccessible::Child) {
             return QAInterface();
         }
     }
     QAccessibleInterface *child_iface = 0;
     const int status = base.interface->navigate(relation, entry, &child_iface);
     if (status == -1)
         return QAInterface(); // not found;
     // Check if target is a child of this interface.
     if (!child_iface) {
         return QAInterface(*this, status);
     } else {
         // Target is child_iface or a child of that (status decides).
         return QAInterface(child_iface, status);
     }
 }
object()
QObject* QAInterface::object () const inline
Definition at line 235 of file qaccessible_mac_p.h.
Referenced by QStandardInterfaceFactory::element(), QItemViewInterfaceFactory::element(), getNamedAttribute(), handleOrientationAttribute(), handleSplitterContentsAttribute(), handleSplittersAttribute(), indexOfChild(), isEmbeddedTabBar(), isItemView(), isItInteresting(), isStandaloneTabBar(), isTabWidget(), QAccessibleHierarchyManager::lookup(), macRole(), objectInterface(), operator<<(), operator==(), qHash(), QItemViewInterfaceFactory::QItemViewInterfaceFactory(), QAccessibleHierarchyManager::registerChildren(), QAccessibleHierarchyManager::registerInterface(), scrollBarOrientation(), and IsWindowAndNotDrawerOrSheetTest::test().
     {
         if (!checkValid())
             return 0;
         return base.interface->object();
     }
objectInterface()
QAInterface QAInterface::objectInterface () const inline
Definition at line 243 of file qaccessible_mac_p.h.
Referenced by QAccessibleHierarchyManager::lookup(), and QAccessibleHierarchyManager::registerInterface().
     {
         if (!checkValid())
             return QAInterface();
         QObject *obj = object();
         QAInterface current = *this;
         while (obj == 0)
         {
             QAInterface parent = current.parent();
             if (parent.isValid() == false)
                 break;
             obj = parent.object();
             current = parent;
         }
         return current;
     }
operator!=()
bool QAInterface::operator!= (const QAInterface & other) const
Definition at line 436 of file qaccessible_mac.mm.
 {
     return !operator==(other);
 }
operator==()
bool QAInterface::operator== (const QAInterface & other) const
Definition at line 410 of file qaccessible_mac.mm.
 {
     if (isValid() == false || other.isValid() == false)
         return (isValid() && other.isValid());
     // walk up the parent chain, comparing child indexes, until we reach
     // an interface that has a QObject.
     QAInterface currentThis = *this;
     QAInterface currentOther = other;
     while (currentThis.object() == 0) {
         if (currentOther.object() != 0)
             return false;
         // fail if the child indexes in the two hirearchies don't match.
         if (currentThis.parent().indexOfChild(currentThis) !=
             currentOther.parent().indexOfChild(currentOther))
             return false;
         currentThis = currentThis.parent();
         currentOther = currentOther.parent();
     }
     return (currentThis.object() == currentOther.object() && currentThis.id() == currentOther.id());
 }
parent()
QAInterface QAInterface::parent () const inline
Definition at line 345 of file qaccessible_mac_p.h.
Referenced by QItemViewInterfaceFactory::element(), handleSplitterContentsAttribute(), indexOfChild(), macRole(), navigateAncestors(), objectInterface(), operator==(), QItemViewInterfaceFactory::QItemViewInterfaceFactory(), and subrole().
     { return navigate(QAccessible::Ancestor, 1); }
rect()
QRect QAInterface::rect () const inline
Definition at line 279 of file qaccessible_mac_p.h.
Referenced by handlePositionAttribute(), and handleSizeAttribute().
     {
         if (!checkValid())
             return QRect();
         return base.interface->rect(child);
     }
role()
Role QAInterface::role () const inline
Definition at line 286 of file qaccessible_mac_p.h.
Referenced by getAllAttributeNames(), getNamedAttribute(), getValue(), handleOrientationAttribute(), handleSplitterContentsAttribute(), isEmbeddedTabBar(), isItemView(), isItInteresting(), isNamedAttributeSettable(), isStandaloneTabBar(), macRole(), operator<<(), scrollAreaGetScrollBarInterface(), setNamedAttribute(), subrole(), supportedPredefinedActions(), supportsAttribute(), tabBarGetTabs(), IsWindowTest::test(), and IsWindowAndNotDrawerOrSheetTest::test().
     {
         if (!checkValid())
             return QAccessible::NoRole;
         return base.interface->role(child);
     }
setText()
void QAInterface::setText (Text t, const QString & text) const inline
Definition at line 293 of file qaccessible_mac_p.h.
Referenced by setNamedAttribute().
     {
         if (!checkValid())
             return;
         base.interface->setText(t, child, text);
     }
state()
State QAInterface::state () const inline
Definition at line 300 of file qaccessible_mac_p.h.
Referenced by buttonValue(), getNamedAttribute(), handleSelectedRowsAttribute(), handleVisibleRowsAttribute(), and isItInteresting().
     {
         if (!checkValid())
             return 0;
         return base.interface->state(child);
     }
text()
QString QAInterface::text (Text text) const inline
Definition at line 307 of file qaccessible_mac_p.h.
Referenced by getValue(), handleStringAttribute(), and supportsAttribute().
     {
         if (!checkValid())
             return QString();
         return base.interface->text(text, child);
     }
userActionCount()
int QAInterface::userActionCount () const inline
Definition at line 320 of file qaccessible_mac_p.h.
Referenced by getAllActionNames(), and performNamedAction().
     {
         if (!checkValid())
             return 0;
         return base.interface->userActionCount(child);
     }
value()
QString QAInterface::value () const inline
Definition at line 314 of file qaccessible_mac_p.h.
     { return text(QAccessible::Value); }
Properties
base
QAccessibleInterfaceWrapper QAInterface::base protected
Definition at line 362 of file qaccessible_mac_p.h.
Referenced by indexOfChild(), and QAInterface().
child
int QAInterface::child protected
Definition at line 364 of file qaccessible_mac_p.h.
Referenced by navigate().
m_cachedObject
QObject* QAInterface::m_cachedObject protected
Definition at line 363 of file qaccessible_mac_p.h.
Referenced by QAInterface().
The documentation for this class was generated from the following files:
/src/gui/accessible/qaccessible_mac_p.h
/src/gui/accessible/qaccessible_mac.mm