Qt 4.8: QCP949Codec Class Reference
QCP949Codec Class Reference
The QCP949Codec class handles encoding and decoding of text in CP949 encoding.
#include <qeuckrcodec.h>
Public Functions
QList< QByteArray > aliases () const
Subclasses can return a number of aliases for the codec in question.
QByteArray convertFromUnicode (const QChar *, int, ConverterState *) const
Reimplemented Function
QString convertToUnicode (const char *, int, ConverterState *) const
Reimplemented Function
int mibEnum () const
Subclasses of QTextCodec must reimplement this function.
QByteArray name () const
QTextCodec subclasses must reimplement this function.
Public Functions inherited from QTextCodec
bool canEncode (QChar) const
Returns true if the Unicode character ch can be fully encoded with this codec; otherwise returns false.
bool canEncode (const QString &) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.s contains the string being tested for encode-ability.
QByteArray fromUnicode (const QString &uc) const
Converts str from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QByteArray fromUnicode (const QChar *in, int length, ConverterState *state=0) const
Converts the first number of characters from the input array from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QTextDecoder * makeDecoder () const
Creates a QTextDecoder which stores enough state to decode chunks of char * data to create chunks of Unicode data.
QTextDecoder * makeDecoder (ConversionFlags flags) const
QTextEncoder * makeEncoder () const
Creates a QTextEncoder which stores enough state to encode chunks of Unicode data as char * data.
QTextEncoder * makeEncoder (ConversionFlags flags) const
QString toUnicode (const QByteArray &) const
Converts a from the encoding of this codec to Unicode, and returns the result in a QString.
QString toUnicode (const char *chars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.chars contains the source characters.
QString toUnicode (const char *in, int length, ConverterState *state=0) const
Converts the first size characters from the input from the encoding of this codec to Unicode, and returns the result in a QString.
Static Public Functions
static QList< QByteArray > _aliases ()
static int _mibEnum ()
static QByteArray _name ()
Static Public Functions inherited from QTextCodec
static QList< QByteArray > availableCodecs ()
Returns the list of all available codecs, by name.
static QList< int > availableMibs ()
Returns the list of MIBs for all available codecs.
static QTextCodec * codecForCStrings ()
Returns the codec used by QString to convert to and from const char * and QByteArrays.
static QTextCodec * codecForHtml (const QByteArray &ba)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForHtml (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForLocale ()
Returns a pointer to the codec most suitable for this locale.
static QTextCodec * codecForMib (int mib)
Returns the QTextCodec which matches the MIBenum mib.
static QTextCodec * codecForName (const QByteArray &name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForName (const char *name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForTr ()
Returns the codec used by QObject::tr() on its argument.
static QTextCodec * codecForUtfText (const QByteArray &ba)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static QTextCodec * codecForUtfText (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static void setCodecForCStrings (QTextCodec *c)
static void setCodecForLocale (QTextCodec *c)
Set the codec to c; this will be returned by codecForLocale().
static void setCodecForTr (QTextCodec *c)
Additional Inherited Members
Public Types inherited from QTextCodec
enum ConversionFlag { DefaultConversion, ConvertInvalidToNull = 0x80000000, IgnoreHeader = 0x1, FreeFunction = 0x2 }
Protected Functions inherited from QTextCodec
QTextCodec ()
Constructs a QTextCodec, and gives it the highest precedence.
virtual ~QTextCodec ()
Destroys the QTextCodec.
Detailed Description
The QCP949Codec class handles encoding and decoding of text in CP949 encoding.
Warning
This function is not part of the public interface.
CP949 stands for code page 949, default code page for Korean text on Windows.
Definition at line 91 of file qeuckrcodec.h.
Functions
_aliases()
static QList<QByteArray> QCP949Codec::_aliases () inline static
Definition at line 94 of file qeuckrcodec.h.
Referenced by KRTextCodecs::aliases(), and KRTextCodecs::createForName().
 { return QList<QByteArray>(); }
_mibEnum()
int QCP949Codec::_mibEnum () static
Definition at line 3393 of file qeuckrcodec.cpp.
Referenced by KRTextCodecs::createForMib(), and KRTextCodecs::mibEnums().
 {
   return -949; // CP949 has no MIBenum. So we have to use fake value.
 }
_name()
QByteArray QCP949Codec::_name () static
Definition at line 3398 of file qeuckrcodec.cpp.
Referenced by KRTextCodecs::createForName(), and KRTextCodecs::names().
 {
   return "cp949";
 }
aliases()
QList<QByteArray> QCP949Codec::aliases () const inline virtual
Subclasses can return a number of aliases for the codec in question.
Standard aliases for codecs can be found in the IANA character-sets encoding file.
Reimplemented from QTextCodec.
Definition at line 98 of file qeuckrcodec.h.
 { return _aliases(); }
convertFromUnicode()
QByteArray QCP949Codec::convertFromUnicode (const QChar * uc, int len, ConverterState * state) const virtual
Reimplemented Function
Implements QTextCodec.
Definition at line 3406 of file qeuckrcodec.cpp.
 {
     char replacement = '?';
     if (state) {
         if (state->flags & ConvertInvalidToNull)
             replacement = 0;
     }
     int invalid = 0;
     int rlen = 2*len + 1;
     QByteArray rstr;
     rstr.resize(rlen);
     uchar* cursor = (uchar*)rstr.data();
     for (int i = 0; i < len; i++) {
         unsigned short ch = uc[i].unicode();
         uint j;
         if (ch < 0x80) {
             // ASCII
             *cursor++ = ch;
         } else if ((j = qt_UnicodeToKsc5601(ch))) {
             // KSC 5601
             *cursor++ = (j >> 8)   | 0x80;
             *cursor++ = (j & 0xff) | 0x80;
         } else {
             const unsigned short *ptr = qBinaryFind(cp949_icode_to_unicode, cp949_icode_to_unicode + 8822, ch);
             if (ptr == cp949_icode_to_unicode + 8822) {
                 // Error
                 *cursor++ = replacement;
                 ++invalid;
             }
             else {
                 // The table 'cp949_icode_to_unicode' contains following
                 // 1. Elements of row 81-a0 (32 rows) consisting of 178 elements each.
                 // 2. Elements of row a1-fe not in EUC-KR consisting of 84 elements each.
                 // On each row the elements are distributed (41-5A), (61-7A), (81-FE) in order.
                 // http://www.microsoft.com/globaldev/reference/dbcs/949.mspx
                 // find the position of the current unicode in the table.
                 int internal_code = ptr - cp949_icode_to_unicode;
                 int row, column;
                 if(internal_code < 32 * 178) {
                     // code between row 81-a0
                     row = internal_code / 178;
                     column = internal_code % 178;
                 }
                 else {
                     // code between a1-fe
                     internal_code -= 3008;
                     row = internal_code / 84;
                     column = internal_code % 84;
                 }
                 unsigned char first, second;
                 first = row + 0x81;
                 if(column < 26)
                     second = column + 0x41; // between 41-5A
                 else if(column < 52)
                     second = column - 26 + 0x61; // between 61-7A
                 else
                     second = column - 52 + 0x81; // between 81-FE
                 *cursor++ = first;
                 *cursor++ = second;
             }
         }
     }
     rstr.resize(cursor - (uchar*)rstr.constData());
     if (state) {
         state->invalidChars += invalid;
     }
     return rstr;
 }
convertToUnicode()
QString QCP949Codec::convertToUnicode (const char * chars, int len, ConverterState * state) const virtual
Reimplemented Function
Implements QTextCodec.
Definition at line 3485 of file qeuckrcodec.cpp.
 {
     uchar buf[2] = {0, 0};
     int nbuf = 0;
     QChar replacement = QChar::ReplacementCharacter;
     if (state) {
         if (state->flags & ConvertInvalidToNull)
             replacement = QChar::Null;
         nbuf = state->remainingChars;
         buf[0] = state->state_data[0];
         buf[1] = state->state_data[1];
     }
     int invalid = 0;
     QString result;
     for (int i=0; i<len; i++) {
         uchar ch = chars[i];
         if (ch == 0)
             break;
         switch (nbuf) {
         case 0:
             if (ch < 0x80) {
                 // ASCII
                 result += QLatin1Char(ch);
             } else if (IsEucChar(ch)) {
                 // KSC 5601
                 buf[0] = ch;
                 nbuf = 1;
             } else if (IsCP949Char(ch)){
                 buf[0] = ch;
                 nbuf = 1;
             } else {
                 // Invalid
                 result += replacement;
                 ++invalid;
             }
             break;
         case 1:
             // KSC 5601
             if (IsEucChar(ch) && !IsCP949Char(buf[0])) {
                 uint u = qt_Ksc5601ToUnicode((buf[0] << 8) |  ch);
                 result += QValidChar(u);
             } else {
                 // Rest of CP949
                 int row, column;
                 nbuf = 0;
                 row = buf[0] - 0x81;
                 if (0x41 <= ch && ch <= 0x5a)
                    column = ch - 0x41;
                 else if (0x61 <= ch && ch <= 0x7a)
                     column = ch - 0x61 + 26;
                 else if (0x81 <= ch && ch <= 0xfe)
                     column = ch - 0x81 + 52;
                 else {
                     result += replacement;
                     ++invalid;
                     break;
                 }
                 int internal_code;
                 if (row < 32)
                     internal_code = row * 178 + column;
                 else
                     internal_code = 3008 + row * 84 + column;
                 // check whether the conversion avialble in the table.
                 if (internal_code < 0 || internal_code >= 8822) {
                     result += replacement;
                     ++invalid;
                     break;
                 }
                 else
                     result += QValidChar(cp949_icode_to_unicode[internal_code]);
             }
             nbuf = 0;
             break;
         }
     }
     if (state) {
         state->remainingChars = nbuf;
         state->state_data[0] = buf[0];
         state->state_data[1] = buf[1];
         state->invalidChars += invalid;
     }
     return result;
 }
mibEnum()
int QCP949Codec::mibEnum () const inline virtual
Subclasses of QTextCodec must reimplement this function.
It returns the MIBenum (see IANA character-sets encoding file for more information). It is important that each QTextCodec subclass returns the correct unique value for this function.
Implements QTextCodec.
Definition at line 99 of file qeuckrcodec.h.
 { return _mibEnum(); }
name()
QByteArray QCP949Codec::name () const inline virtual
QTextCodec subclasses must reimplement this function.
It returns the name of the encoding supported by the subclass.
If the codec is registered as a character set in the IANA character-sets encoding file this method should return the preferred mime name for the codec if defined, otherwise its name.
Implements QTextCodec.
Definition at line 97 of file qeuckrcodec.h.
 { return _name(); }
The documentation for this class was generated from the following files:
/src/plugins/codecs/kr/qeuckrcodec.h
/src/plugins/codecs/kr/qeuckrcodec.cpp