Qt 4.8: QPatternist::XPathHelper Class Reference
QPatternist::XPathHelper Class Reference
Contains helper and utility functions.
#include <qxpathhelper_p.h>
Static Public Functions
template<const ReportContext::ErrorCode code, typename TReportContext >
static void checkCollationSupport (const QString &collation, const TReportContext &context, const SourceLocationReflection *const r)
static bool isQName (const QString &qName)
static bool isReservedNamespace (const QXmlName::NamespaceCode ns)
static bool isWhitespaceOnly (const QStringRef &string)
Determines whether consists only of whitespace. Characters considered whitespace are the ones for which QChar::isSpace() returns true for.
static bool isWhitespaceOnly (const QString &string)
static QUrl normalizeQueryURI (const QUrl &uri)
static void splitQName (const QString &qName, QString &prefix, QString &localName)
Splits qName into localName and prefix.
static QPatternist::ItemTypePtr typeFromKind (const QXmlNodeModelIndex::NodeKind nodeKind)
Private Functions
XPathHelper ()
This default constructor has no definition, in order to avoid instantiation, since it makes no sense to instantiate this class.
Detailed Description
Contains helper and utility functions.
The common denominator of its functions is that they do not fit in well elsewhere, such as in a particular class. It is preferred if XPathHelper goes away, and that functions are in more specific classes.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 76 of file qxpathhelper_p.h.
Constructors and Destructors
XPathHelper()
QPatternist::XPathHelper::XPathHelper () inline private
This default constructor has no definition, in order to avoid instantiation, since it makes no sense to instantiate this class.
Referenced by isWhitespaceOnly().
Functions
checkCollationSupport()
template<const ReportContext::ErrorCode code, typename TReportContext > static void QPatternist::XPathHelper::checkCollationSupport (const QString & collation, const TReportContext & context, const SourceLocationReflection *const r) inline static
Determines whether collation is a supported string collation. If it is not, error code code is raised via context.
Definition at line 111 of file qxpathhelper_p.h.
         {
             Q_ASSERT(context);
             Q_ASSERT(r);
             if(collation != QLatin1String(CommonNamespaces::UNICODE_COLLATION))
             {
                 context->error(QtXmlPatterns::tr("Only the Unicode Codepoint "
                                   "Collation is supported(%1). %2 is unsupported.")
                                   .arg(formatURI(QLatin1String(CommonNamespaces::UNICODE_COLLATION)))
                                   .arg(formatURI(collation)),
                                code, r);
             }
         }
isQName()
bool XPathHelper::isQName (const QString & qName) static
Determines whether qName is a valid QName. For example, "body" and "xhtml:body" is, but "xhtml::body" or "x:body "(note the whitespace) is not.
See also
QNameConstructor::expandQName()
QNameValue
Definition at line 64 of file qxpathhelper.cpp.
Referenced by QPatternist::XsdTypeChecker::checkConstrainingFacetsQName(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::QNameConstructor::expandQName(), QPatternist::NamePool::fromClarkName(), QPatternist::XsdTypeChecker::isValidString(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdValidatingInstanceReader::qNameAttribute(), QPatternist::XsdSchemaParser::readQNameAttribute(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), and splitQName().
 {
     const QStringList result(qName.split(QLatin1Char(':')));
     const int c = result.count();
     if(c == 2)
     {
         return QXmlUtils::isNCName(result.first()) &&
                QXmlUtils::isNCName(result.last());
     }
     else if(c == 1)
         return QXmlUtils::isNCName(result.first());
     else
         return false;
 }
isReservedNamespace()
bool XPathHelper::isReservedNamespace (const QXmlName::NamespaceCode ns) static
Determines whether ns is a reserved namespace.
See also
XSL Transformations (XSLT) Version 2.0, 3.2 Reserved Namespaces
XQuery 1.0: An XML Query Language, 4.15 Function Declaration
Returns
true if ns is a reserved namespace, otherwise false.
Definition at line 55 of file qxpathhelper.cpp.
Referenced by QPatternist::yyparse().
 {
     /* The order is because of that XFN and WXS are the most common. */
     return ns == StandardNamespaces::fn     ||
            ns == StandardNamespaces::xs     ||
            ns == StandardNamespaces::xml    ||
            ns == StandardNamespaces::xsi;
 }
isWhitespaceOnly() [1/2]
static bool QPatternist::XPathHelper::isWhitespaceOnly (const QStringRef & string) inline static
Determines whether consists only of whitespace. Characters considered whitespace are the ones for which QChar::isSpace() returns true for.
For the empty string, true is returned.
Returns
true if string consists only of whitespace, otherwise false.
Definition at line 143 of file qxpathhelper_p.h.
Referenced by isWhitespaceOnly(), QXmlFormatter::item(), QXmlFormatter::startFormattingContent(), and QPatternist::yyparse().
         {
             const int len = string.length();
             for(int i = 0; i < len; ++i)
             {
                 if(!string.at(i).isSpace()) // TODO and this is wrong, see sdk/TODO
                     return false;
             }
             return true;
         }
isWhitespaceOnly() [2/2]
static bool QPatternist::XPathHelper::isWhitespaceOnly (const QString & string) inline static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 159 of file qxpathhelper_p.h.
         {
             return isWhitespaceOnly(QStringRef(&string));
         }
normalizeQueryURI()
QUrl XPathHelper::normalizeQueryURI (const QUrl & uri) static
Normalizes an uri by resolving it to the application directory if empty.
Definition at line 128 of file qxpathhelper.cpp.
Referenced by checkCollationSupport(), QXmlSchemaPrivate::load(), QXmlQuery::setQuery(), and QXmlSchemaValidator::validate().
 {
     Q_ASSERT_X(uri.isEmpty() || uri.isValid(), Q_FUNC_INFO,
                "The URI passed to QXmlQuery::setQuery() must be valid or empty.");
     if(uri.isEmpty())
         return QUrl::fromLocalFile(QCoreApplication::applicationFilePath());
     else if(uri.isRelative())
         return QUrl::fromLocalFile(QCoreApplication::applicationFilePath()).resolved(uri);
     else
         return uri;
 }
splitQName()
void XPathHelper::splitQName (const QString & qName, QString & prefix, QString & localName) static
Splits qName into localName and prefix.
Note
qName must be a valid QName, and that is not checked.
Definition at line 80 of file qxpathhelper.cpp.
Referenced by QPatternist::ElementAvailableFN::evaluateEBV(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::QNameConstructor::expandQName(), QPatternist::NamePool::fromClarkName(), and QPatternist::yyparse().
 {
     Q_ASSERT_X(isQName(qName), Q_FUNC_INFO,
                "qName must be a valid QName.");
     const QStringList result(qName.split(QLatin1Char(':')));
     if(result.count() == 1)
     {
         Q_ASSERT(QXmlUtils::isNCName(result.first()));
         ncName = result.first();
     }
     else
     {
         Q_ASSERT(result.count() == 2);
         Q_ASSERT(QXmlUtils::isNCName(result.first()));
         Q_ASSERT(QXmlUtils::isNCName(result.last()));
         prefix = result.first();
         ncName = result.last();
     }
 }
typeFromKind()
ItemType::Ptr XPathHelper::typeFromKind (const QXmlNodeModelIndex::NodeKind nodeKind) static
Definition at line 103 of file qxpathhelper.cpp.
Referenced by checkCollationSupport(), and QPatternist::AccelTree::type().
 {
     switch(nodeKind)
     {
         case QXmlNodeModelIndex::Element:
             return BuiltinTypes::element;
         case QXmlNodeModelIndex::Attribute:
             return BuiltinTypes::attribute;
         case QXmlNodeModelIndex::Text:
             return BuiltinTypes::text;
         case QXmlNodeModelIndex::ProcessingInstruction:
             return BuiltinTypes::pi;
         case QXmlNodeModelIndex::Comment:
             return BuiltinTypes::comment;
         case QXmlNodeModelIndex::Document:
             return BuiltinTypes::document;
         default:
         {
             Q_ASSERT_X(false, Q_FUNC_INFO,
                        "A node type that doesn't exist in the XPath Data Model was encountered.");
             return ItemType::Ptr(); /* Dummy, silence compiler warning. */
         }
     }
 }
The documentation for this class was generated from the following files:
/src/xmlpatterns/utils/qxpathhelper_p.h
/src/xmlpatterns/utils/qxpathhelper.cpp