Qt 4.8: QScriptDeclarativeClass Class Reference
QScriptDeclarativeClass Class Reference
#include <qscriptdeclarativeclass_p.h>
Classes
struct Object
class PersistentIdentifier
class Value
The QScriptDeclarativeClass::Value class acts as a container for JavaScript data types.
Public Types
typedef void * Identifier
Public Functions
virtual Value call (Object *, QScriptContext *)
virtual bool compare (Object *, Object *)
QScriptContext * context () const
PersistentIdentifier createPersistentIdentifier (const QString &)
PersistentIdentifier createPersistentIdentifier (const Identifier &)
QScriptEngine * engine () const
virtual bool isQObject () const
virtual Value property (Object *, const Identifier &)
virtual QScriptValue::PropertyFlags propertyFlags (Object *, const Identifier &)
virtual QStringList propertyNames (Object *)
QScriptDeclarativeClass (QScriptEngine *engine)
virtual QScriptClass::QueryFlags queryProperty (Object *, const Identifier &, QScriptClass::QueryFlags flags)
virtual void setProperty (Object *, const Identifier &name, const QScriptValue &)
void setSupportsCall (bool)
bool startsWithUpper (const Identifier &)
bool supportsCall () const
quint32 toArrayIndex (const Identifier &, bool *ok)
virtual QObject * toQObject (Object *, bool *ok=0)
QString toString (const Identifier &)
virtual QVariant toVariant (Object *, bool *ok=0)
virtual ~QScriptDeclarativeClass ()
Static Public Functions
static QScriptValue function (const QScriptValue &, const Identifier &)
static Value functionValue (const QScriptValue &, const Identifier &)
static QScriptValue newObject (QScriptEngine *, QScriptDeclarativeClass *, Object *)
static Value newObjectValue (QScriptEngine *, QScriptDeclarativeClass *, Object *)
static QScriptValue newStaticScopeObject (QScriptEngine *, int propertyCount, const QString *names, const QScriptValue *values, const QScriptValue::PropertyFlags *flags)
Creates a scope object with a fixed set of undeletable properties.
static QScriptValue newStaticScopeObject (QScriptEngine *)
Creates a static scope object that's initially empty, but to which new properties can be added.
static Object * object (const QScriptValue &)
static QScriptValue property (const QScriptValue &, const Identifier &)
static Value propertyValue (const QScriptValue &, const Identifier &)
static QScriptContext * pushCleanContext (QScriptEngine *)
Enters a new execution context and returns the associated QScriptContext object.
static QScriptValue scopeChainValue (QScriptContext *, int index)
static QScriptDeclarativeClass * scriptClass (const QScriptValue &)
Protected Variables
QScopedPointer< QScriptDeclarativeClassPrivate > d_ptr
Friends
class QScriptDeclarativeClassPrivate
Detailed Description
Definition at line 47 of file qscriptdeclarativeclass_p.h.
Typedefs
Identifier
typedef void* QScriptDeclarativeClass::Identifier
Definition at line 78 of file qscriptdeclarativeclass_p.h.
Constructors and Destructors
QScriptDeclarativeClass()
QScriptDeclarativeClass::QScriptDeclarativeClass (QScriptEngine * engine)
Definition at line 190 of file qscriptdeclarativeclass.cpp.
 : d_ptr(new QScriptDeclarativeClassPrivate)
 {
     Q_ASSERT(sizeof(void*) == sizeof(JSC::Identifier));
     d_ptr->q_ptr = this;
     d_ptr->engine = engine;
 }
~QScriptDeclarativeClass()
QScriptDeclarativeClass::~QScriptDeclarativeClass () virtual
Definition at line 426 of file qscriptdeclarativeclass.cpp.
 {
 }
Functions
call()
QScriptDeclarativeClass::Value QScriptDeclarativeClass::call (Object * object, QScriptContext * ctxt) virtual
Reimplemented in QDeclarativeObjectMethodScriptClass.
Definition at line 528 of file qscriptdeclarativeclass.cpp.
Referenced by QScript::DeclarativeObjectDelegate::call().
 {
     Q_UNUSED(object);
     Q_UNUSED(ctxt);
     return Value();
 }
compare()
bool QScriptDeclarativeClass::compare (Object * o, Object * o2) virtual
Reimplemented in QDeclarativeObjectScriptClass, and FlatListScriptClass.
Definition at line 536 of file qscriptdeclarativeclass.cpp.
Referenced by QScript::DeclarativeObjectDelegate::compareToObject().
 {
     return o == o2;
 }
context()
QScriptContext * QScriptDeclarativeClass::context () const
Definition at line 564 of file qscriptdeclarativeclass.cpp.
Referenced by QDeclarativeObjectScriptClass::queryProperty(), QDeclarativeValueTypeScriptClass::setProperty(), QDeclarativeTypeNameScriptClass::setProperty(), QDeclarativeContextScriptClass::setProperty(), and QDeclarativeObjectScriptClass::setProperty().
 {
     return d_ptr->context;
 }
createPersistentIdentifier() [1/2]
QScriptDeclarativeClass::PersistentIdentifier QScriptDeclarativeClass::createPersistentIdentifier (const QString & str)
Definition at line 446 of file qscriptdeclarativeclass.cpp.
Referenced by QDeclarativeTypeNameCache::add(), QDeclarativePropertyCache::append(), QDeclarativeListScriptClass::QDeclarativeListScriptClass(), QDeclarativeObjectMethodScriptClass::QDeclarativeObjectMethodScriptClass(), QDeclarativeObjectScriptClass::QDeclarativeObjectScriptClass(), and QDeclarativeCompiledBindingsPrivate::run().
 {
     QScriptEnginePrivate *p =
         static_cast<QScriptEnginePrivate *>(QObjectPrivate::get(d_ptr->engine));
     QScript::APIShim shim(p);
     JSC::ExecState* exec = p->currentFrame;
     PersistentIdentifier rv(p);
     new (&rv.d) JSC::Identifier(exec, (UChar *)str.constData(), str.size());
     rv.identifier = (void *)((JSC::Identifier &)rv.d).ustring().rep();
     return rv;
 }
createPersistentIdentifier() [2/2]
QScriptDeclarativeClass::PersistentIdentifier QScriptDeclarativeClass::createPersistentIdentifier (const Identifier & id)
Definition at line 460 of file qscriptdeclarativeclass.cpp.
 {
     QScriptEnginePrivate *p =
         static_cast<QScriptEnginePrivate *>(QObjectPrivate::get(d_ptr->engine));
     QScript::APIShim shim(p);
     JSC::ExecState* exec = p->currentFrame;
     PersistentIdentifier rv(p);
     new (&rv.d) JSC::Identifier(exec, (JSC::UString::Rep *)id);
     rv.identifier = (void *)((JSC::Identifier &)rv.d).ustring().rep();
     return rv;
 }
engine()
QScriptEngine * QScriptDeclarativeClass::engine () const
Definition at line 430 of file qscriptdeclarativeclass.cpp.
Referenced by QDeclarativeContextScriptClass::contextFromValue(), QDeclarativeContextScriptClass::newContext(), QDeclarativeListScriptClass::newList(), QDeclarativeObjectMethodScriptClass::newMethod(), QDeclarativeValueTypeScriptClass::newObject(), QDeclarativeTypeNameScriptClass::newObject(), QDeclarativeObjectScriptClass::newQObject(), QDeclarativeContextScriptClass::newSharedContext(), QDeclarativeContextScriptClass::newUrlContext(), QDeclarativeListScriptClass::property(), QDeclarativeValueTypeScriptClass::property(), QDeclarativeTypeNameScriptClass::property(), QDeclarativeObjectMethodScriptClass::property(), QDeclarativeContextScriptClass::property(), QDeclarativeObjectScriptClass::property(), FlatListScriptClass::property(), QDeclarativeObjectScriptClass::propertyNames(), QDeclarativeListScriptClass::QDeclarativeListScriptClass(), QDeclarativeObjectMethodScriptClass::QDeclarativeObjectMethodScriptClass(), QDeclarativeObjectScriptClass::QDeclarativeObjectScriptClass(), QScriptDeclarativeClass(), QDeclarativeTypeNameScriptClass::queryProperty(), QDeclarativeContextScriptClass::queryProperty(), QDeclarativeObjectScriptClass::queryProperty(), scopeChainValue(), QDeclarativeValueTypeScriptClass::setProperty(), QDeclarativeTypeNameScriptClass::setProperty(), QDeclarativeContextScriptClass::setProperty(), QDeclarativeObjectScriptClass::setProperty(), and QDeclarativeListScriptClass::toVariant().
 {
     return d_ptr->engine;
 }
function()
QScriptValue QScriptDeclarativeClass::function (const QScriptValue & v, const Identifier & name) static
Definition at line 247 of file qscriptdeclarativeclass.cpp.
 {
     QScriptValuePrivate *d = QScriptValuePrivate::get(v);
     if (!d->isObject())
         return QScriptValue();
     QScript::APIShim shim(d->engine);
     JSC::ExecState *exec = d->engine->currentFrame;
     JSC::JSObject *object = d->jscValue.getObject();
     JSC::PropertySlot slot(const_cast<JSC::JSObject*>(object));
     JSC::JSValue result;
     JSC::Identifier id(exec, (JSC::UString::Rep *)name);
     if (const_cast<JSC::JSObject*>(object)->getOwnPropertySlot(exec, id, slot)) {
         result = slot.getValue(exec, id);
         if (QScript::isFunction(result))
             return d->engine->scriptValueFromJSCValue(result);
     }
     return QScriptValue();
 }
functionValue()
QScriptDeclarativeClass::Value QScriptDeclarativeClass::functionValue (const QScriptValue & v, const Identifier & name) static
Definition at line 295 of file qscriptdeclarativeclass.cpp.
 {
     QScriptValuePrivate *d = QScriptValuePrivate::get(v);
     if (!d->isObject())
         return Value();
     QScript::APIShim shim(d->engine);
     JSC::ExecState *exec = d->engine->currentFrame;
     JSC::JSObject *object = d->jscValue.getObject();
     JSC::PropertySlot slot(const_cast<JSC::JSObject*>(object));
     JSC::JSValue result;
     JSC::Identifier id(exec, (JSC::UString::Rep *)name);
     if (const_cast<JSC::JSObject*>(object)->getOwnPropertySlot(exec, id, slot)) {
         result = slot.getValue(exec, id);
         if (QScript::isFunction(result))
             return jscToValue(result);
     }
     return Value();
 }
isQObject()
bool QScriptDeclarativeClass::isQObject () const virtual
Reimplemented in QDeclarativeObjectScriptClass.
Definition at line 547 of file qscriptdeclarativeclass.cpp.
 {
     return false;
 }
newObject()
QScriptValue QScriptDeclarativeClass::newObject (QScriptEngine * engine, QScriptDeclarativeClass * scriptClass, Object * object) static
Definition at line 198 of file qscriptdeclarativeclass.cpp.
Referenced by FlatListModel::get(), QDeclarativeContextScriptClass::newContext(), QDeclarativeListScriptClass::newList(), QDeclarativeObjectMethodScriptClass::newMethod(), QDeclarativeValueTypeScriptClass::newObject(), QDeclarativeTypeNameScriptClass::newObject(), QDeclarativeObjectScriptClass::newQObject(), QDeclarativeContextScriptClass::newSharedContext(), and QDeclarativeContextScriptClass::newUrlContext().
 {
     Q_ASSERT(engine);
     Q_ASSERT(scriptClass);
     QScriptEnginePrivate *p = static_cast<QScriptEnginePrivate *>(QObjectPrivate::get(engine));
     QScript::APIShim shim(p);
     JSC::ExecState* exec = p->currentFrame;
     QScriptObject *result = new (exec) QScriptObject(p->scriptObjectStructure);
     result->setDelegate(new QScript::DeclarativeObjectDelegate(scriptClass, object));
     return p->scriptValueFromJSCValue(result);
 }
newObjectValue()
QScriptDeclarativeClass::Value QScriptDeclarativeClass::newObjectValue (QScriptEngine * engine, QScriptDeclarativeClass * scriptClass, Object * object) static
Definition at line 215 of file qscriptdeclarativeclass.cpp.
 {
     Q_ASSERT(engine);
     Q_ASSERT(scriptClass);
     QScriptEnginePrivate *p = static_cast<QScriptEnginePrivate *>(QObjectPrivate::get(engine));
     QScript::APIShim shim(p);
     JSC::ExecState* exec = p->currentFrame;
     QScriptObject *result = new (exec) QScriptObject(p->scriptObjectStructure);
     result->setDelegate(new QScript::DeclarativeObjectDelegate(scriptClass, object));
     return jscToValue(JSC::JSValue(result));
 }
newStaticScopeObject() [1/2]
QScriptValue QScriptDeclarativeClass::newStaticScopeObject (QScriptEngine * engine, int propertyCount, const QString * names, const QScriptValue * values, const QScriptValue::PropertyFlags * flags) static
Creates a scope object with a fixed set of undeletable properties.
Definition at line 572 of file qscriptdeclarativeclass.cpp.
Referenced by QDeclarativeContextData::addImportedScript(), and QDeclarativeGlobalScriptClass::QDeclarativeGlobalScriptClass().
 {
     QScriptEnginePrivate *eng_p = QScriptEnginePrivate::get(engine);
     QScript::APIShim shim(eng_p);
     JSC::ExecState *exec = eng_p->currentFrame;
     QScriptStaticScopeObject::PropertyInfo *props = new QScriptStaticScopeObject::PropertyInfo[propertyCount];
     for (int i = 0; i < propertyCount; ++i) {
         unsigned attribs = QScriptEnginePrivate::propertyFlagsToJSCAttributes(flags[i]);
         Q_ASSERT_X(attribs & JSC::DontDelete, Q_FUNC_INFO, "All properties must be undeletable");
         JSC::Identifier id = JSC::Identifier(exec, names[i]);
         JSC::JSValue jsval = eng_p->scriptValueToJSCValue(values[i]);
         props[i] = QScriptStaticScopeObject::PropertyInfo(id, jsval, attribs);
     }
     QScriptValue result = eng_p->scriptValueFromJSCValue(new (exec)QScriptStaticScopeObject(eng_p->staticScopeObjectStructure,
                                                                                             propertyCount, props));
     delete[] props;
     return result;
 }
newStaticScopeObject() [2/2]
QScriptValue QScriptDeclarativeClass::newStaticScopeObject (QScriptEngine * engine) static
Creates a static scope object that's initially empty, but to which new properties can be added.
Definition at line 597 of file qscriptdeclarativeclass.cpp.
 {
     QScriptEnginePrivate *eng_p = QScriptEnginePrivate::get(engine);
     QScript::APIShim shim(eng_p);
     return eng_p->scriptValueFromJSCValue(new (eng_p->currentFrame)QScriptStaticScopeObject(eng_p->staticScopeObjectStructure));
 }
object()
QScriptDeclarativeClass::Object * QScriptDeclarativeClass::object (const QScriptValue & v) static
Definition at line 239 of file qscriptdeclarativeclass.cpp.
Referenced by QDeclarativeObjectScriptClass::destroy(), QDeclarativeListScriptClass::newList(), QDeclarativeValueTypeScriptClass::newObject(), QDeclarativeObjectScriptClass::objectType(), and scopeChainValue().
 {
     QScriptValuePrivate *d = QScriptValuePrivate::get(v);
     if (!d || !d->isJSC())
         return 0;
     return QScriptEnginePrivate::declarativeObject(d->jscValue);
 }
property() [1/2]
QScriptValue QScriptDeclarativeClass::property (const QScriptValue & v, const Identifier & name) static
Definition at line 271 of file qscriptdeclarativeclass.cpp.
Referenced by QScript::DeclarativeObjectDelegate::getOwnPropertySlot().
 {
     QScriptValuePrivate *d = QScriptValuePrivate::get(v);
     if (!d->isObject())
         return QScriptValue();
     QScript::APIShim shim(d->engine);
     JSC::ExecState *exec = d->engine->currentFrame;
     JSC::JSObject *object = d->jscValue.getObject();
     JSC::PropertySlot slot(const_cast<JSC::JSObject*>(object));
     JSC::JSValue result;
     JSC::Identifier id(exec, (JSC::UString::Rep *)name);
     if (const_cast<JSC::JSObject*>(object)->getOwnPropertySlot(exec, id, slot)) {
         result = slot.getValue(exec, id);
         return d->engine->scriptValueFromJSCValue(result);
     }
     return QScriptValue();
 }
property() [2/2]
QScriptDeclarativeClass::Value QScriptDeclarativeClass::property (Object * object, const Identifier & name) virtual
Reimplemented in QDeclarativeObjectScriptClass, FlatListScriptClass, QDeclarativeContextScriptClass, QDeclarativeObjectMethodScriptClass, QDeclarativeTypeNameScriptClass, QDeclarativeListScriptClass, and QDeclarativeValueTypeScriptClass.
Definition at line 505 of file qscriptdeclarativeclass.cpp.
 {
     Q_UNUSED(object);
     Q_UNUSED(name);
     return Value();
 }
propertyFlags()
QScriptValue::PropertyFlags QScriptDeclarativeClass::propertyFlags (Object * object, const Identifier & name) virtual
Definition at line 521 of file qscriptdeclarativeclass.cpp.
 {
     Q_UNUSED(object);
     Q_UNUSED(name);
     return 0;
 }
propertyNames()
QStringList QScriptDeclarativeClass::propertyNames (Object * object) virtual
Reimplemented in QDeclarativeObjectScriptClass.
Definition at line 541 of file qscriptdeclarativeclass.cpp.
Referenced by QScript::DeclarativeObjectDelegate::getOwnPropertyNames().
 {
     Q_UNUSED(object);
     return QStringList();
 }
propertyValue()
QScriptDeclarativeClass::Value QScriptDeclarativeClass::propertyValue (const QScriptValue & v, const Identifier & name) static
Definition at line 320 of file qscriptdeclarativeclass.cpp.
 {
     QScriptValuePrivate *d = QScriptValuePrivate::get(v);
     if (!d->isObject())
         return Value();
     QScript::APIShim shim(d->engine);
     JSC::ExecState *exec = d->engine->currentFrame;
     JSC::JSObject *object = d->jscValue.getObject();
     JSC::PropertySlot slot(const_cast<JSC::JSObject*>(object));
     JSC::JSValue result;
     JSC::Identifier id(exec, (JSC::UString::Rep *)name);
     if (const_cast<JSC::JSObject*>(object)->getOwnPropertySlot(exec, id, slot)) {
         result = slot.getValue(exec, id);
         return jscToValue(result);
     }
     return Value();
 }
pushCleanContext()
QScriptContext * QScriptDeclarativeClass::pushCleanContext (QScriptEngine * engine) static
Enters a new execution context and returns the associated QScriptContext object.
Once you are done with the context, you should call popContext() to restore the old context.
By default, the `this' object of the new context is the Global Object. The context's callee() will be invalid.
Unlike pushContext(), the default scope chain is reset to include only the global object and the QScriptContext's activation object.
See also
QScriptEngine::popContext()
Definition at line 408 of file qscriptdeclarativeclass.cpp.
Referenced by QDeclarativeContextData::addImportedScript(), QDeclarativeExpressionPrivate::evalInObjectScope(), QDeclarativeInclude::finished(), QDeclarativeInclude::include(), QDeclarativeExpressionPrivate::init(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), QDeclarativeExpressionPrivate::scriptValue(), and QDeclarativeInclude::worker_include().
 {
     if (!engine)
         return 0;
     QScriptEnginePrivate *d = QScriptEnginePrivate::get(engine);
     QScript::APIShim shim(d);
     JSC::CallFrame* newFrame = d->pushContext(d->currentFrame,
                                               d->currentFrame->globalData().dynamicGlobalObject,
                                               JSC::ArgList(), /*callee = */0, false, true);
     if (engine->agent())
         engine->agent()->contextPush();
     return d->contextForFrame(newFrame);
 }
queryProperty()
QScriptClass::QueryFlags QScriptDeclarativeClass::queryProperty (Object * object, const Identifier & name, QScriptClass::QueryFlags flags) virtual
Reimplemented in QDeclarativeObjectScriptClass, FlatListScriptClass, QDeclarativeContextScriptClass, QDeclarativeObjectMethodScriptClass, QDeclarativeTypeNameScriptClass, QDeclarativeListScriptClass, and QDeclarativeValueTypeScriptClass.
Definition at line 495 of file qscriptdeclarativeclass.cpp.
Referenced by QScript::DeclarativeObjectDelegate::getOwnPropertySlot(), and QScript::DeclarativeObjectDelegate::put().
 {
     Q_UNUSED(object);
     Q_UNUSED(name);
     Q_UNUSED(flags);
     return 0;
 }
scopeChainValue()
QScriptValue QScriptDeclarativeClass::scopeChainValue (QScriptContext * context, int index) static
Definition at line 348 of file qscriptdeclarativeclass.cpp.
Referenced by QDeclarativeEnginePrivate::getContext(), QDeclarativeEnginePrivate::getUrl(), QDeclarativeInclude::include(), QDeclarativeInclude::QDeclarativeInclude(), QDeclarativeObjectScriptClass::queryProperty(), QDeclarativeObjectScriptClass::setProperty(), and QDeclarativeInclude::worker_include().
 {
     context->activationObject(); //ensure the creation of the normal scope for native context
     const JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(context);
     QScriptEnginePrivate *engine = QScript::scriptEngineFromExec(frame);
     QScript::APIShim shim(engine);
     JSC::ScopeChainNode *node = frame->scopeChain();
     JSC::ScopeChainIterator it(node);
     if (index < 0) {
         int count = 0;
         for (it = node->begin(); it != node->end(); ++it)
             ++count;
         index = qAbs(index);
         if (index > count)
             return QScriptValue();
         else
             index = count - index;
     }
     for (it = node->begin(); it != node->end(); ++it) {
         if (index == 0) {
             JSC::JSObject *object = *it;
             if (!object) return QScriptValue();
             if (object->inherits(&QScript::QScriptActivationObject::info)
                     && (static_cast<QScript::QScriptActivationObject*>(object)->delegate() != 0)) {
                 // Return the object that property access is being delegated to
                 object = static_cast<QScript::QScriptActivationObject*>(object)->delegate();
             }
             return engine->scriptValueFromJSCValue(object);
         } else {
             --index;
         }
     }
     return QScriptValue();
 }
scriptClass()
QScriptDeclarativeClass * QScriptDeclarativeClass::scriptClass (const QScriptValue & v) static
Definition at line 231 of file qscriptdeclarativeclass.cpp.
Referenced by QDeclarativeObjectMethodScriptClass::connect(), QDeclarativeContextScriptClass::contextFromValue(), QDeclarativeObjectScriptClass::destroy(), QDeclarativeObjectMethodScriptClass::disconnect(), QDeclarativeEnginePrivate::getContext(), QDeclarativeEnginePrivate::getUrl(), QDeclarativeObjectScriptClass::objectType(), QDeclarativeObjectScriptClass::queryProperty(), QDeclarativeEnginePrivate::scriptValueToVariant(), QDeclarativeContextScriptClass::setOverrideObject(), QDeclarativeObjectScriptClass::setProperty(), QDeclarativeValueTypeScriptClass::toVariant(), and QDeclarativeContextScriptClass::urlFromValue().
 {
     QScriptValuePrivate *d = QScriptValuePrivate::get(v);
     if (!d || !d->isJSC())
         return 0;
     return QScriptEnginePrivate::declarativeClass(d->jscValue);
 }
setProperty()
void QScriptDeclarativeClass::setProperty (Object * object, const Identifier & name, const QScriptValue & value) virtual
Reimplemented in QDeclarativeObjectScriptClass, FlatListScriptClass, QDeclarativeContextScriptClass, QDeclarativeTypeNameScriptClass, and QDeclarativeValueTypeScriptClass.
Definition at line 512 of file qscriptdeclarativeclass.cpp.
Referenced by QScript::DeclarativeObjectDelegate::put().
 {
     Q_UNUSED(object);
     Q_UNUSED(name);
     Q_UNUSED(value);
 }
setSupportsCall()
void QScriptDeclarativeClass::setSupportsCall (bool c)
Definition at line 440 of file qscriptdeclarativeclass.cpp.
Referenced by QDeclarativeObjectMethodScriptClass::QDeclarativeObjectMethodScriptClass().
 {
     d_ptr->supportsCall = c;
 }
startsWithUpper()
bool QScriptDeclarativeClass::startsWithUpper (const Identifier & identifier)
Definition at line 479 of file qscriptdeclarativeclass.cpp.
Referenced by QDeclarativeTypeNameScriptClass::queryProperty().
 {
     JSC::UString::Rep *r = (JSC::UString::Rep *)identifier;
     if (r->size() < 1)
         return false;
     return QChar::category((ushort)(r->data()[0])) == QChar::Letter_Uppercase;
 }
supportsCall()
bool QScriptDeclarativeClass::supportsCall () const
Definition at line 435 of file qscriptdeclarativeclass.cpp.
 {
     return d_ptr->supportsCall;
 }
toArrayIndex()
quint32 QScriptDeclarativeClass::toArrayIndex (const Identifier & identifier, bool * ok)
Definition at line 487 of file qscriptdeclarativeclass.cpp.
Referenced by QDeclarativeListScriptClass::queryProperty().
 {
     JSC::UString::Rep *r = (JSC::UString::Rep *)identifier;
     JSC::UString s(r);
     return s.toArrayIndex(ok);
 }
toQObject()
QObject * QScriptDeclarativeClass::toQObject (Object * , bool * ok = 0) virtual
Reimplemented in QDeclarativeObjectScriptClass.
Definition at line 552 of file qscriptdeclarativeclass.cpp.
 {
     if (ok) *ok = false;
     return 0;
 }
toString()
QString QScriptDeclarativeClass::toString (const Identifier & identifier)
Definition at line 473 of file qscriptdeclarativeclass.cpp.
Referenced by FlatListScriptClass::property(), QDeclarativePropertyCache::property(), QDeclarativeValueTypeScriptClass::queryProperty(), QDeclarativeTypeNameScriptClass::queryProperty(), QDeclarativeObjectScriptClass::setProperty(), and FlatListScriptClass::setProperty().
 {
     JSC::UString::Rep *r = (JSC::UString::Rep *)identifier;
     return QString((QChar *)r->data(), r->size());
 }
toVariant()
QVariant QScriptDeclarativeClass::toVariant (Object * , bool * ok = 0) virtual
Reimplemented in QDeclarativeValueTypeScriptClass, and QDeclarativeListScriptClass.
Definition at line 558 of file qscriptdeclarativeclass.cpp.
 {
     if (ok) *ok = false;
     return QVariant();
 }
Friends and Related Functions
QScriptDeclarativeClassPrivate
friend class QScriptDeclarativeClassPrivate friend
Definition at line 150 of file qscriptdeclarativeclass_p.h.
Properties
d_ptr
QScopedPointer<QScriptDeclarativeClassPrivate> QScriptDeclarativeClass::d_ptr protected
Definition at line 151 of file qscriptdeclarativeclass_p.h.
Referenced by context(), createPersistentIdentifier(), engine(), QScriptDeclarativeClass(), setSupportsCall(), and supportsCall().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptdeclarativeclass_p.h
/src/script/bridge/qscriptdeclarativeclass.cpp