Qt 4.8: QLinkedList< T > Class Template Reference
QLinkedList< T > Class Template Reference
The QLinkedList class is a template class that provides linked lists.
#include <qdatastream.h>
Classes
class const_iterator
The QLinkedList::const_iterator class provides an STL-style const iterator for QLinkedList.
class iterator
The QLinkedList::iterator class provides an STL-style non-const iterator for QLinkedList.
Public Types
typedef const value_type * const_pointer
Typedef for const T *.
typedef const value_type & const_reference
Typedef for const T &.
typedef const_iterator ConstIterator
Qt-style synonym for QLinkedList::const_iterator.
typedef qptrdiff difference_type
Typedef for ptrdiff_t.
typedef iterator Iterator
Qt-style synonym for QLinkedList::iterator.
typedef value_type * pointer
Typedef for T *.
typedef value_type & reference
Typedef for T &.
typedef int size_type
Typedef for int.
typedef T value_type
Typedef for T.
Public Functions
void append (const T &)
Inserts value at the end of the list.
T & back ()
This function is provided for STL compatibility.
const T & back () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator begin ()
Returns an STL-style iterator pointing to the first item in the list.
const_iterator begin () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void clear ()
Removes all the items in the list.
const_iterator constBegin () const
Returns a const STL-style iterator pointing to the first item in the list.
const_iterator constEnd () const
Returns a const STL-style iterator pointing to the imaginary item after the last item in the list.
bool contains (const T &t) const
Returns true if the list contains an occurrence of value; otherwise returns false.
int count (const T &t) const
Returns the number of occurrences of value in the list.
int count () const
Same as size().
void detach ()
bool empty () const
This function is provided for STL compatibility.
iterator end ()
Returns an STL-style iterator pointing to the imaginary item after the last item in the list.
const_iterator end () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool endsWith (const T &t) const
Returns true if the list is not empty and its last item is equal to value; otherwise returns false.
iterator erase (iterator pos)
Removes the item pointed to by the iterator pos from the list, and returns an iterator to the next item in the list (which may be end()).
iterator erase (iterator first, iterator last)
Removes all the items from begin up to (but not including) end.
T & first ()
Returns a reference to the first item in the list.
const T & first () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
T & front ()
This function is provided for STL compatibility.
const T & front () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator insert (iterator before, const T &t)
Inserts value in front of the item pointed to by the iterator before.
bool isDetached () const
bool isEmpty () const
Returns true if the list contains no items; otherwise returns false.
bool isSharedWith (const QLinkedList< T > &other) const
T & last ()
Returns a reference to the last item in the list.
const T & last () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool operator!= (const QLinkedList< T > &l) const
Returns true if other is not equal to this list; otherwise returns false.
QLinkedList< T > operator+ (const QLinkedList< T > &l) const
Returns a list that contains all the items in this list followed by all the items in the other list.
QLinkedList< T > & operator+= (const QLinkedList< T > &l)
Appends the items of the other list to this list and returns a reference to this list.
QLinkedList< T > & operator+= (const T &t)
Appends value to the list.
QLinkedList< T > & operator<< (const QLinkedList< T > &l)
Appends the items of the other list to this list and returns a reference to this list.
QLinkedList< T > & operator<< (const T &t)
Appends value to the list.
QLinkedList< T > & operator= (const QLinkedList< T > &)
Assigns other to this list and returns a reference to this list.
bool operator== (const QLinkedList< T > &l) const
Returns true if other is equal to this list; otherwise returns false.
void pop_back ()
This function is provided for STL compatibility.
void pop_front ()
This function is provided for STL compatibility.
void prepend (const T &)
Inserts value at the beginning of the list.
void push_back (const T &t)
This function is provided for STL compatibility.
void push_front (const T &t)
This function is provided for STL compatibility.
QLinkedList ()
Constructs an empty list.
QLinkedList (const QLinkedList< T > &l)
Constructs a copy of other.
int removeAll (const T &t)
Removes all occurrences of value in the list.
void removeFirst ()
Removes the first item in the list.
void removeLast ()
Removes the last item in the list.
bool removeOne (const T &t)
Removes the first occurrences of value in the list.
void setSharable (bool sharable)
int size () const
Returns the number of items in the list.
bool startsWith (const T &t) const
Returns true if the list is not empty and its first item is equal to value; otherwise returns false.
void swap (QLinkedList< T > &other)
Swaps list other with this list.
T takeFirst ()
Removes the first item in the list and returns it.
T takeLast ()
Removes the last item in the list and returns it.
std::list< T > toStdList () const
Returns a std::list object with the data contained in this QLinkedList.
~QLinkedList ()
Destroys the list.
Static Public Functions
static QLinkedList< T > fromStdList (const std::list< T > &list)
Returns a QLinkedList object with the data contained in list.
Private Types
typedef QLinkedListNode< T > Node
Private Functions
void detach_helper ()
void free (QLinkedListData *)
Properties
union {
QLinkedListData * d
QLinkedListNode< T > * e
};
Friends
class const_iterator
class iterator
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &out, const QLinkedList< T > &list)
Writes the linked list list to stream out.
QDataStream & operator>> (QDataStream &in, QLinkedList< T > &list)
Reads a linked list from stream in into list.
Detailed Description
template<class T>
class QLinkedList< T >
The QLinkedList class is a template class that provides linked lists.
Note
This class or function is reentrant.
QLinkedList<T> is one of Qt's generic container classes. It stores a list of values and provides iterator-based access as well as constant time insertions and removals.
QList<T>, QLinkedList<T>, and QVector<T> provide similar functionality. Here's an overview:
For most purposes, QList is the right class to use. Its index-based API is more convenient than QLinkedList's iterator-based API, and it is usually faster than QVector because of the way it stores its items in memory (see Algorithmic Complexity for details). It also expands to less code in your executable.
If you need a real linked list, with guarantees of constant time insertions in the middle of the list and iterators to items rather than indexes, use QLinkedList.
If you want the items to occupy adjacent memory positions, use QVector.
Here's an example of a QLinkedList that stores integers and a QLinkedList that stores QTime values:
QLinkedList<int> integerList;
QLinkedList<QTime> timeList;
QLinkedList stores a list of items. The default constructor creates an empty list. To insert items into the list, you can use operator<<():
QLinkedList<QString> list;
list << "one" << "two" << "three";
// list: ["one", "two", "three"]
If you want to get the first or last item in a linked list, use first() or last(). If you want to remove an item from either end of the list, use removeFirst() or removeLast(). If you want to remove all occurrences of a given value in the list, use removeAll().
A common requirement is to remove the first or last item in the list and do something with it. For this, QLinkedList provides takeFirst() and takeLast(). Here's a loop that removes the items from a list one at a time and calls delete on them:
QLinkedList<QWidget *> list;
...
while (!list.isEmpty())
    delete list.takeFirst();
QLinkedList's value type must be an assignable data type. This covers most data types that are commonly used, but the compiler won't let you, for example, store a QWidget as a value; instead, store a QWidget *. A few functions have additional requirements; for example, contains() and removeAll() expect the value type to support operator==(). These requirements are documented on a per-function basis.
If you want to insert, modify, or remove items in the middle of the list, you must use an iterator. QLinkedList provides both Java-style iterators (QLinkedListIterator and QMutableLinkedListIterator) and STL-style iterators (QLinkedList::const_iterator and QLinkedList::iterator). See the documentation for these classes for details.
See also
QLinkedListIterator, QMutableLinkedListIterator, QList, QVector
Definition at line 63 of file qdatastream.h.
Typedefs
const_pointer
template<class T> QLinkedList< T >::const_pointer
Typedef for const T *.
Provided for STL compatibility.
Definition at line 218 of file qlinkedlist.h.
const_reference
template<class T> QLinkedList< T >::const_reference
Typedef for const T &.
Provided for STL compatibility.
Definition at line 220 of file qlinkedlist.h.
ConstIterator
template<class T> QLinkedList< T >::ConstIterator
Qt-style synonym for QLinkedList::const_iterator.
Definition at line 194 of file qlinkedlist.h.
difference_type
template<class T> QLinkedList< T >::difference_type
Typedef for ptrdiff_t.
Provided for STL compatibility.
Definition at line 221 of file qlinkedlist.h.
Iterator
template<class T> QLinkedList< T >::Iterator
Qt-style synonym for QLinkedList::iterator.
Definition at line 193 of file qlinkedlist.h.
Node
template<class T> typedef QLinkedListNode<T> QLinkedList< T >::Node private
Definition at line 80 of file qlinkedlist.h.
pointer
template<class T> QLinkedList< T >::pointer
Typedef for T *.
Provided for STL compatibility.
Definition at line 217 of file qlinkedlist.h.
reference
template<class T> QLinkedList< T >::reference
Typedef for T &.
Provided for STL compatibility.
Definition at line 219 of file qlinkedlist.h.
size_type
template<class T> QLinkedList< T >::size_type
Typedef for int.
Provided for STL compatibility.
Definition at line 215 of file qlinkedlist.h.
value_type
template<class T> QLinkedList< T >::value_type
Typedef for T.
Provided for STL compatibility.
Definition at line 216 of file qlinkedlist.h.
Constructors and Destructors
QLinkedList() [1/2]
template<class T> QLinkedList< T >::QLinkedList () inline
Constructs an empty list.
Definition at line 84 of file qlinkedlist.h.
 : d(&QLinkedListData::shared_null) { d->ref.ref(); }
QLinkedList() [2/2]
template<class T> QLinkedList< T >::QLinkedList (const QLinkedList< T > & other) inline
Constructs a copy of other.
This operation occurs in constant time, because QLinkedList is implicitly shared. This makes returning a QLinkedList from a function very fast. If a shared instance is modified, it will be copied (copy-on-write), and this takes linear time.
See also
operator=()
Definition at line 85 of file qlinkedlist.h.
 : d(l.d) { d->ref.ref(); if (!d->sharable) detach(); }
~QLinkedList()
template<typename T > QLinkedList< T >::~QLinkedList () inline
Destroys the list.
References to the values in the list, and all iterators over this list, become invalid.
Definition at line 258 of file qlinkedlist.h.
 {
     if (!d)
         return;
     if (!d->ref.deref())
         free(d);
 }
Functions
append()
template<typename T> void QLinkedList< T >::append (const T & value)
Inserts value at the end of the list.
Example:
QLinkedList<QString> list;
list.append("one");
list.append("two");
list.append("three");
// list: ["one", "two", "three"]
This is the same as list.insert(end(), value).
See also
operator<<(), prepend(), insert()
Definition at line 350 of file qlinkedlist.h.
Referenced by QSpanCollection::addSpan(), QScriptValueIteratorPrivate::ensureInitialized(), operator>>(), QSpanCollection::updateRemovedColumns(), and QSpanCollection::updateRemovedRows().
 {
     detach();
     Node *i = new Node(t);
     i->n = e;
     i->p = e->p;
     i->p->n = i;
     e->p = i;
     d->size++;
 }
back() [1/2]
template<class T> T & QLinkedList< T >::back () inline
This function is provided for STL compatibility.
It is equivalent to last().
Definition at line 210 of file qlinkedlist.h.
 { return last(); }
back() [2/2]
template<class T> const T & QLinkedList< T >::back () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 211 of file qlinkedlist.h.
 { return last(); }
begin() [1/2]
template<class T> QLinkedList::iterator QLinkedList< T >::begin () inline
Returns an STL-style iterator pointing to the first item in the list.
See also
constBegin(), end()
Definition at line 182 of file qlinkedlist.h.
Referenced by QScriptValueIteratorPrivate::ensureInitialized(), QGraphicsAnchorLayoutPrivate::getGraphParts(), QMeeGoLivePixmapData::QMeeGoLivePixmapData(), QSpanCollection::updateInsertedColumns(), QSpanCollection::updateInsertedRows(), QSpanCollection::updateRemovedColumns(), and QSpanCollection::updateRemovedRows().
 { detach(); return e->n; }
begin() [2/2]
template<class T> QLinkedList::const_iterator QLinkedList< T >::begin () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 183 of file qlinkedlist.h.
 { return e->n; }
clear()
template<typename T > void QLinkedList< T >::clear ()
Removes all the items in the list.
See also
removeAll()
Definition at line 311 of file qlinkedlist.h.
Referenced by QSpanCollection::clear(), operator>>(), and QScriptValueIteratorPrivate::~QScriptValueIteratorPrivate().
 {
     *this = QLinkedList<T>();
 }
constBegin()
template<class T> QLinkedList::const_iterator QLinkedList< T >::constBegin () const inline
Returns a const STL-style iterator pointing to the first item in the list.
See also
begin(), constEnd()
Definition at line 184 of file qlinkedlist.h.
 { return e->n; }
constEnd()
template<class T> QLinkedList::const_iterator QLinkedList< T >::constEnd () const inline
Returns a const STL-style iterator pointing to the imaginary item after the last item in the list.
See also
constBegin(), end()
Definition at line 187 of file qlinkedlist.h.
 { return e; }
contains()
template<typename T> bool QLinkedList< T >::contains (const T & value) const
Returns true if the list contains an occurrence of value; otherwise returns false.
This function requires the value type to have an implementation of operator==().
See also
QLinkedListIterator::findNext(), QLinkedListIterator::findPrevious()
Definition at line 425 of file qlinkedlist.h.
Referenced by QSpanCollection::updateRemovedColumns().
 {
     Node *i = e;
     while ((i = i->n) != e)
         if (i->t == t)
             return true;
     return false;
 }
count() [1/2]
template<typename T> int QLinkedList< T >::count (const T & value) const
Returns the number of occurrences of value in the list.
This function requires the value type to have an implementation of operator==().
See also
contains()
Definition at line 435 of file qlinkedlist.h.
 {
     Node *i = e;
     int c = 0;
     while ((i = i->n) != e)
         if (i->t == t)
             c++;
     return c;
 }
count() [2/2]
template<class T> int QLinkedList< T >::count () const inline
Same as size().
Definition at line 195 of file qlinkedlist.h.
 { return d->size; }
detach()
template<class T> void QLinkedList< T >::detach () inline
Warning
This function is not part of the public interface.
Definition at line 97 of file qlinkedlist.h.
     { if (d->ref != 1) detach_helper(); }
detach_helper()
template<typename T > void QLinkedList< T >::detach_helper () private
Definition at line 267 of file qlinkedlist.h.
 {
     union { QLinkedListData *d; Node *e; } x;
     x.d = new QLinkedListData;
     x.d->ref = 1;
     x.d->size = d->size;
     x.d->sharable = true;
     Node *original = e->n;
     Node *copy = x.e;
     while (original != e) {
         QT_TRY {
             copy->n = new Node(original->t);
             copy->n->p = copy;
             original = original->n;
             copy = copy->n;
         } QT_CATCH(...) {
             copy->n = x.e;
             free(x.d);
             QT_RETHROW;
         }
     }
     copy->n = x.e;
     x.e->p = copy;
     if (!d->ref.deref())
         free(d);
     d = x.d;
 }
empty()
template<class T> bool QLinkedList< T >::empty () const inline
This function is provided for STL compatibility.
It is equivalent to isEmpty() and returns true if the list is empty.
Definition at line 214 of file qlinkedlist.h.
 { return isEmpty(); }
end() [1/2]
template<class T> QLinkedList::iterator QLinkedList< T >::end () inline
Returns an STL-style iterator pointing to the imaginary item after the last item in the list.
See also
begin(), constEnd()
Definition at line 185 of file qlinkedlist.h.
Referenced by QGraphicsAnchorLayoutPrivate::getGraphParts(), QSpanCollection::updateInsertedColumns(), QSpanCollection::updateInsertedRows(), QSpanCollection::updateRemovedColumns(), and QSpanCollection::updateRemovedRows().
 { detach(); return e; }
end() [2/2]
template<class T> QLinkedList::const_iterator QLinkedList< T >::end () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 186 of file qlinkedlist.h.
 { return e; }
endsWith()
template<class T> bool QLinkedList< T >::endsWith (const T & value) const inline
Returns true if the list is not empty and its last item is equal to value; otherwise returns false.
Since
4.5
See also
isEmpty(), last()
Definition at line 203 of file qlinkedlist.h.
 { return !isEmpty() && last() == t; }
erase() [1/2]
template<typename T > QLinkedList< T >::iterator QLinkedList< T >::erase (iterator pos)
Removes the item pointed to by the iterator pos from the list, and returns an iterator to the next item in the list (which may be end()).
See also
insert()
Definition at line 470 of file qlinkedlist.h.
Referenced by QGraphicsAnchorLayoutPrivate::getGraphParts(), QLinkedList< JSC::Identifier >::insert(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateRemovedRows(), and QMeeGoLivePixmapData::~QMeeGoLivePixmapData().
 {
     detach();
     Node *i = pos.i;
     if (i != e) {
         Node *n = i;
         i->n->p = i->p;
         i->p->n = i->n;
         i = i->n;
         delete n;
         d->size--;
     }
     return i;
 }
erase() [2/2]
template<class T> QLinkedList::iterator QLinkedList< T >::erase (iterator begin, iterator end)
Removes all the items from begin up to (but not including) end.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
first() [1/2]
template<class T> T & QLinkedList< T >::first () inline
Returns a reference to the first item in the list.
This function assumes that the list isn't empty.
See also
last(), isEmpty()
Definition at line 196 of file qlinkedlist.h.
 { Q_ASSERT(!isEmpty()); return *begin(); }
first() [2/2]
template<class T> const T & QLinkedList< T >::first () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 197 of file qlinkedlist.h.
 { Q_ASSERT(!isEmpty()); return *begin(); }
free()
template<typename T > void QLinkedList< T >::free (QLinkedListData * x) private
Definition at line 296 of file qlinkedlist.h.
 {
     Node *y = reinterpret_cast<Node*>(x);
     Node *i = y->n;
     if (x->ref == 0) {
         while(i != y) {
             Node *n = i;
             i = i->n;
             delete n;
         }
         delete x;
     }
 }
fromStdList()
template<class T> QLinkedList< T > QLinkedList< T >::fromStdList (const std::list< T > & list) inline static
Returns a QLinkedList object with the data contained in list.
Since
4.1
The order of the elements in the QLinkedList is the same as in list.
Example:
std::list<double> stdlist;
list.push_back(1.2);
list.push_back(0.5);
list.push_back(3.14);
QLinkedList<double> list = QLinkedList<double>::fromStdList(stdlist);
See also
toStdList()
Definition at line 224 of file qlinkedlist.h.
     { QLinkedList<T> tmp; qCopy(list.begin(), list.end(), std::back_inserter(tmp)); return tmp; }
front() [1/2]
template<class T> T & QLinkedList< T >::front () inline
This function is provided for STL compatibility.
It is equivalent to first().
Definition at line 208 of file qlinkedlist.h.
 { return first(); }
front() [2/2]
template<class T> const T & QLinkedList< T >::front () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 209 of file qlinkedlist.h.
 { return first(); }
insert()
template<typename T> QLinkedList< T >::iterator QLinkedList< T >::insert (iterator before, const T & value)
Inserts value in front of the item pointed to by the iterator before.
Returns an iterator pointing at the inserted item.
See also
erase()
Definition at line 447 of file qlinkedlist.h.
Referenced by QMeeGoLivePixmapData::QMeeGoLivePixmapData().
 {
     Node *i = before.i;
     Node *m = new Node(t);
     m->n = i;
     m->p = i->p;
     m->p->n = m;
     i->p = m;
     d->size++;
     return m;
 }
isDetached()
template<class T> bool QLinkedList< T >::isDetached () const inline
Warning
This function is not part of the public interface.
Definition at line 99 of file qlinkedlist.h.
 { return d->ref == 1; }
isEmpty()
template<class T> bool QLinkedList< T >::isEmpty () const inline
Returns true if the list contains no items; otherwise returns false.
See also
size()
Definition at line 103 of file qlinkedlist.h.
Referenced by QGraphicsAnchorLayoutPrivate::getGraphParts(), QTableViewPrivate::hasSpans(), QSpanCollection::updateInsertedColumns(), QSpanCollection::updateInsertedRows(), QSpanCollection::updateRemovedColumns(), and QSpanCollection::updateRemovedRows().
 { return d->size == 0; }
isSharedWith()
template<class T> bool QLinkedList< T >::isSharedWith (const QLinkedList< T > & other) const inline
Warning
This function is not part of the public interface.
Definition at line 101 of file qlinkedlist.h.
 { return d == other.d; }
last() [1/2]
template<class T> T & QLinkedList< T >::last () inline
Returns a reference to the last item in the list.
This function assumes that the list isn't empty.
See also
first(), isEmpty()
Definition at line 198 of file qlinkedlist.h.
 { Q_ASSERT(!isEmpty()); return *(--end()); }
last() [2/2]
template<class T> const T & QLinkedList< T >::last () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 199 of file qlinkedlist.h.
 { Q_ASSERT(!isEmpty()); return *(--end()); }
operator!=()
template<class T> bool QLinkedList< T >::operator!= (const QLinkedList< T > & other) const inline
Returns true if other is not equal to this list; otherwise returns false.
Two lists are considered equal if they contain the same values in the same order.
This function requires the value type to implement operator==().
See also
operator==()
Definition at line 94 of file qlinkedlist.h.
 { return !(*this == l); }
operator+()
template<typename T> QLinkedList< T > QLinkedList< T >::operator+ (const QLinkedList< T > & other) const
Returns a list that contains all the items in this list followed by all the items in the other list.
See also
operator+=()
Definition at line 511 of file qlinkedlist.h.
 {
     QLinkedList<T> n = *this;
     n += l;
     return n;
 }
operator+=() [1/2]
template<typename T> QLinkedList< T > & QLinkedList< T >::operator+= (const QLinkedList< T > & other)
Appends the items of the other list to this list and returns a reference to this list.
See also
operator+(), append()
Definition at line 486 of file qlinkedlist.h.
 {
     detach();
     int n = l.d->size;
     d->size += n;
     Node *original = l.e->n;
     while (n--) {
         QT_TRY {
             Node *copy = new Node(original->t);
             original = original->n;
             copy->n = e;
             copy->p = e->p;
             copy->p->n = copy;
             e->p = copy;
         } QT_CATCH(...) {
             // restore the original list
             while (n++<d->size)
                 removeLast();
             QT_RETHROW;
         }
     }
     return *this;
 }
operator+=() [2/2]
template<class T> void QLinkedList< T >::operator+= (const T & value) inline
Appends value to the list.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 248 of file qlinkedlist.h.
 { append(t); return *this; }
operator<<() [1/2]
template<class T> QLinkedList< T > & QLinkedList< T >::operator<< (const T & value) inline
Appends value to the list.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 249 of file qlinkedlist.h.
 { append(t); return *this; }
operator<<() [2/2]
template<class T> QLinkedList< T > & QLinkedList< T >::operator<< (const QLinkedList< T > & other) inline
Appends the items of the other list to this list and returns a reference to this list.
See also
operator+=(), append()
Definition at line 250 of file qlinkedlist.h.
 { *this += l; return *this; }
operator=()
template<typename T> QLinkedList< T > & QLinkedList< T >::operator= (const QLinkedList< T > & other)
Assigns other to this list and returns a reference to this list.
Definition at line 317 of file qlinkedlist.h.
 {
     if (d != l.d) {
         QLinkedListData *o = l.d;
         o->ref.ref();
         if (!d->ref.deref())
             free(d);
         d = o;
         if (!d->sharable)
             detach_helper();
     }
     return *this;
 }
operator==()
template<typename T> bool QLinkedList< T >::operator== (const QLinkedList< T > & other) const
Returns true if other is equal to this list; otherwise returns false.
Two lists are considered equal if they contain the same values in the same order.
This function requires the value type to implement operator==().
See also
operator!=()
Definition at line 332 of file qlinkedlist.h.
 {
     if (d->size != l.d->size)
         return false;
     if (e == l.e)
         return true;
     Node *i = e->n;
     Node *il = l.e->n;
     while (i != e) {
         if (! (i->t == il->t))
             return false;
         i = i->n;
         il = il->n;
     }
     return true;
 }
pop_back()
template<class T> void QLinkedList< T >::pop_back () inline
This function is provided for STL compatibility.
It is equivalent to removeLast().
Definition at line 213 of file qlinkedlist.h.
 { removeLast(); }
pop_front()
template<class T> void QLinkedList< T >::pop_front () inline
This function is provided for STL compatibility.
It is equivalent to removeFirst().
Definition at line 212 of file qlinkedlist.h.
 { removeFirst(); }
prepend()
template<typename T> void QLinkedList< T >::prepend (const T & value)
Inserts value at the beginning of the list.
Example:
QLinkedList<QString> list;
list.prepend("one");
list.prepend("two");
list.prepend("three");
// list: ["three", "two", "one"]
This is the same as list.insert(begin(), value).
See also
append(), insert()
Definition at line 362 of file qlinkedlist.h.
 {
     detach();
     Node *i = new Node(t);
     i->n = e->n;
     i->p = e;
     i->n->p = i;
     e->n = i;
     d->size++;
 }
push_back()
template<class T> void QLinkedList< T >::push_back (const T & value) inline
This function is provided for STL compatibility.
It is equivalent to append(value).
Definition at line 206 of file qlinkedlist.h.
 { append(t); }
push_front()
template<class T> void QLinkedList< T >::push_front (const T & value) inline
This function is provided for STL compatibility.
It is equivalent to prepend(value).
Definition at line 207 of file qlinkedlist.h.
 { prepend(t); }
removeAll()
template<typename T> int QLinkedList< T >::removeAll (const T & value)
Removes all occurrences of value in the list.
Example:
QList<QString> list;
list << "sun" << "cloud" << "sun" << "rain";
list.removeAll("sun");
// list: ["cloud", "rain"]
This function requires the value type to have an implementation of operator==().
See also
insert()
Definition at line 374 of file qlinkedlist.h.
 {
     detach();
     const T t = _t;
     Node *i = e->n;
     int c = 0;
     while (i != e) {
         if (i->t == t) {
             Node *n = i;
             i->n->p = i->p;
             i->p->n = i->n;
             i = i->n;
             delete n;
             c++;
         } else {
             i = i->n;
         }
     }
     d->size-=c;
     return c;
 }
removeFirst()
template<class T> void QLinkedList< T >::removeFirst () inline
Removes the first item in the list.
This is the same as erase(begin()).
See also
removeLast(), erase()
Definition at line 200 of file qlinkedlist.h.
 { Q_ASSERT(!isEmpty()); erase(begin()); }
removeLast()
template<class T> void QLinkedList< T >::removeLast () inline
Removes the last item in the list.
See also
removeFirst(), erase()
Definition at line 201 of file qlinkedlist.h.
 { Q_ASSERT(!isEmpty()); erase(--end()); }
removeOne()
template<typename T> bool QLinkedList< T >::removeOne (const T & value)
Removes the first occurrences of value in the list.
Since
4.4
Returns true on success; otherwise returns false.
Example:
QList<QString> list;
list << "sun" << "cloud" << "sun" << "rain";
list.removeOne("sun");
// list: ["cloud", "sun", "rain"]
This function requires the value type to have an implementation of operator==().
See also
insert()
Definition at line 397 of file qlinkedlist.h.
Referenced by QSpanCollection::updateSpan().
 {
     detach();
     iterator it = qFind(begin(), end(), _t);
     if (it != end()) {
         erase(it);
         return true;
     }
     return false;
 }
setSharable()
template<class T> void QLinkedList< T >::setSharable (bool sharable) inline
Warning
This function is not part of the public interface.
Definition at line 100 of file qlinkedlist.h.
 { if (!sharable) detach(); d->sharable = sharable; }
size()
template<class T> int QLinkedList< T >::size () const inline
Returns the number of items in the list.
See also
isEmpty(), count()
Definition at line 96 of file qlinkedlist.h.
 { return d->size; }
startsWith()
template<class T> bool QLinkedList< T >::startsWith (const T & value) const inline
Returns true if the list is not empty and its first item is equal to value; otherwise returns false.
Since
4.5
See also
isEmpty(), first()
Definition at line 202 of file qlinkedlist.h.
 { return !isEmpty() && first() == t; }
swap()
template<class T> void QLinkedList< T >::swap (QLinkedList< T > & other) inline
Swaps list other with this list.
Since
4.8
This operation is very fast and never fails.
Definition at line 92 of file qlinkedlist.h.
 { qSwap(d, other.d); }
takeFirst()
template<typename T > T QLinkedList< T >::takeFirst () inline
Removes the first item in the list and returns it.
If you don't use the return value, removeFirst() is more efficient.
See also
takeLast(), removeFirst()
Definition at line 409 of file qlinkedlist.h.
 {
     T t = first();
     removeFirst();
     return t;
 }
takeLast()
template<typename T > T QLinkedList< T >::takeLast () inline
Removes the last item in the list and returns it.
If you don't use the return value, removeLast() is more efficient.
See also
takeFirst(), removeLast()
Definition at line 417 of file qlinkedlist.h.
 {
     T t = last();
     removeLast();
     return t;
 }
toStdList()
template<class T> std::list< T > QLinkedList< T >::toStdList () const inline
Returns a std::list object with the data contained in this QLinkedList.
Since
4.1
Example:
QLinkedList<double> list;
list << 1.2 << 0.5 << 3.14;
std::list<double> stdlist = list.toStdList();
See also
fromStdList()
Definition at line 226 of file qlinkedlist.h.
     { std::list<T> tmp; qCopy(constBegin(), constEnd(), std::back_inserter(tmp)); return tmp; }
Friends and Related Functions
const_iterator
template<class T> friend class const_iterator friend
Definition at line 179 of file qlinkedlist.h.
iterator
template<class T> friend class iterator friend
Definition at line 149 of file qlinkedlist.h.
operator<<()
template<class T> QDataStream & operator<< (QDataStream & out, const QLinkedList< T > & list) related
Writes the linked list list to stream out.
This function requires the value type to implement operator<<().
See also
Format of the QDataStream operators
Definition at line 287 of file qdatastream.h.
 {
     s << quint32(l.size());
     typename QLinkedList<T>::ConstIterator it = l.constBegin();
     for(; it != l.constEnd(); ++it)
         s << *it;
     return s;
 }
operator>>()
template<class T> QDataStream & operator>> (QDataStream & in, QLinkedList< T > & list) related
Reads a linked list from stream in into list.
This function requires the value type to implement operator>>().
See also
Format of the QDataStream operators
Definition at line 270 of file qdatastream.h.
 {
     l.clear();
     quint32 c;
     s >> c;
     for(quint32 i = 0; i < c; ++i)
     {
         T t;
         s >> t;
         l.append(t);
         if (s.atEnd())
             break;
     }
     return s;
 }
Properties
@57
union { ... }
d
template<class T> QLinkedListData* QLinkedList< T >::d
Definition at line 81 of file qlinkedlist.h.
Referenced by QLinkedList< JSC::Identifier >::isSharedWith(), QLinkedList< JSC::Identifier >::operator+=(), QLinkedList< JSC::Identifier >::operator=(), QLinkedList< JSC::Identifier >::operator==(), and QLinkedList< JSC::Identifier >::swap().
e
template<class T> QLinkedListNode<T>* QLinkedList< T >::e
Definition at line 81 of file qlinkedlist.h.
Referenced by QLinkedList< JSC::Identifier >::operator+=(), and QLinkedList< JSC::Identifier >::operator==().
The documentation for this class was generated from the following files:
/src/corelib/io/qdatastream.h
/src/corelib/tools/qlinkedlist.h
/src/corelib/tools/qlinkedlist.cpp