Qt 4.8: QDynamicBufferResourceRoot Class Reference
QDynamicBufferResourceRoot Class Reference
Public Functions
const uchar * mappingBuffer () const
virtual QString mappingRoot () const
QDynamicBufferResourceRoot (const QString &_root)
bool registerSelf (const uchar *b)
virtual ResourceRootType type () const
~QDynamicBufferResourceRoot ()
Public Functions inherited from QResourceRoot
QStringList children (int node) const
const uchar * data (int node, qint64 *size) const
int findNode (const QString &path, const QLocale &locale=QLocale()) const
bool isCompressed (int node) const
bool isContainer (int node) const
bool mappingRootSubdir (const QString &path, QString *match=0) const
bool operator!= (const QResourceRoot &other) const
bool operator== (const QResourceRoot &other) const
QResourceRoot ()
QResourceRoot (const uchar *t, const uchar *n, const uchar *d)
virtual ~QResourceRoot ()
Properties
const uchar * buffer
QString root
Additional Inherited Members
Public Types inherited from QResourceRoot
enum ResourceRootType { Resource_Builtin, Resource_File, Resource_Buffer }
Public Variables inherited from QResourceRoot
QAtomicInt ref
Protected Functions inherited from QResourceRoot
void setSource (const uchar *t, const uchar *n, const uchar *d)
Detailed Description
Definition at line 895 of file qresource.cpp.
Constructors and Destructors
QDynamicBufferResourceRoot()
QDynamicBufferResourceRoot::QDynamicBufferResourceRoot (const QString & _root) inline
Definition at line 901 of file qresource.cpp.
 : root(_root), buffer(0) { }
~QDynamicBufferResourceRoot()
QDynamicBufferResourceRoot::~QDynamicBufferResourceRoot () inline
Definition at line 902 of file qresource.cpp.
 { }
Functions
mappingBuffer()
const uchar* QDynamicBufferResourceRoot::mappingBuffer () const inline
Definition at line 903 of file qresource.cpp.
Referenced by QResource::unregisterResource().
 { return buffer; }
mappingRoot()
virtual QString QDynamicBufferResourceRoot::mappingRoot () const inline virtual
Reimplemented from QResourceRoot.
Definition at line 904 of file qresource.cpp.
Referenced by QResource::unregisterResource().
 { return root; }
registerSelf()
bool QDynamicBufferResourceRoot::registerSelf (const uchar * b) inline
Definition at line 907 of file qresource.cpp.
Referenced by QResource::registerResource(), and QDynamicFileResourceRoot::registerSelf().
{
         //setup the data now
         int offset = 0;
         //magic number
         if(b[offset+0] != 'q' || b[offset+1] != 'r' ||
            b[offset+2] != 'e' || b[offset+3] != 's') {
             return false;
         }
         offset += 4;
         const int version = (b[offset+0] << 24) + (b[offset+1] << 16) +
                          (b[offset+2] << 8) + (b[offset+3] << 0);
         offset += 4;
         const int tree_offset = (b[offset+0] << 24) + (b[offset+1] << 16) +
                                 (b[offset+2] << 8) + (b[offset+3] << 0);
         offset += 4;
         const int data_offset = (b[offset+0] << 24) + (b[offset+1] << 16) +
                                 (b[offset+2] << 8) + (b[offset+3] << 0);
         offset += 4;
         const int name_offset = (b[offset+0] << 24) + (b[offset+1] << 16) +
                                 (b[offset+2] << 8) + (b[offset+3] << 0);
         offset += 4;
         if(version == 0x01) {
             buffer = b;
             setSource(b+tree_offset, b+name_offset, b+data_offset);
             return true;
         }
         return false;
     }
type()
virtual ResourceRootType QDynamicBufferResourceRoot::type () const inline virtual
Reimplemented from QResourceRoot.
Reimplemented in QDynamicFileResourceRoot.
Definition at line 905 of file qresource.cpp.
 { return Resource_Buffer; }
Properties
buffer
const uchar* QDynamicBufferResourceRoot::buffer private
Definition at line 898 of file qresource.cpp.
root
QString QDynamicBufferResourceRoot::root private
Definition at line 897 of file qresource.cpp.
The documentation for this class was generated from the following file:
/src/corelib/io/qresource.cpp