Qt 4.8: QGuiPlatformPlugin Class Reference
QGuiPlatformPlugin Class Reference
#include <qguiplatformplugin_p.h>
Public Types
enum PlatformHint { PH_ToolButtonStyle, PH_ToolBarIconSize, PH_ItemView_ActivateItemOnSingleClick }
Public Functions
virtual void colorDialogDelete (QColorDialog *)
virtual void colorDialogSetCurrentColor (QColorDialog *, const QColor &)
virtual bool colorDialogSetVisible (QColorDialog *, bool)
virtual void fileDialogDelete (QFileDialog *)
virtual QString fileDialogDirectory (const QFileDialog *) const
virtual QDialog::DialogCode fileDialogResultCode (QFileDialog *)
virtual QStringList fileDialogSelectedFiles (const QFileDialog *) const
virtual QString fileDialogSelectedNameFilter (const QFileDialog *) const
virtual void fileDialogSelectFile (QFileDialog *, const QString &)
virtual void fileDialogSelectNameFilter (QFileDialog *, const QString &)
virtual void fileDialogSetDirectory (QFileDialog *, const QString &)
virtual void fileDialogSetFilter (QFileDialog *)
virtual void fileDialogSetNameFilters (QFileDialog *, const QStringList &)
virtual bool fileDialogSetVisible (QFileDialog *, bool)
virtual QIcon fileSystemIcon (const QFileInfo &)
virtual QStringList iconThemeSearchPaths ()
virtual QStringList keys () const
virtual QPalette palette ()
virtual int platformHint (PlatformHint hint)
QGuiPlatformPlugin (QObject *parent=0)
virtual QString styleName ()
virtual QString systemIconThemeName ()
~QGuiPlatformPlugin ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QFactoryInterface
virtual ~QFactoryInterface ()
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 81 of file qguiplatformplugin_p.h.
Enumerations
PlatformHint
enum QGuiPlatformPlugin::PlatformHint
Enumerator
PH_ToolButtonStyle
PH_ToolBarIconSize
PH_ItemView_ActivateItemOnSingleClick
Definition at line 97 of file qguiplatformplugin_p.h.
 { PH_ToolButtonStyle, PH_ToolBarIconSize, PH_ItemView_ActivateItemOnSingleClick };
Constructors and Destructors
QGuiPlatformPlugin()
QGuiPlatformPlugin::QGuiPlatformPlugin (QObject * parent = 0) explicit
Definition at line 129 of file qguiplatformplugin.cpp.
 : QObject(parent) {}
~QGuiPlatformPlugin()
QGuiPlatformPlugin::~QGuiPlatformPlugin ()
Definition at line 130 of file qguiplatformplugin.cpp.
 {}
Functions
colorDialogDelete()
virtual void QGuiPlatformPlugin::colorDialogDelete (QColorDialog *) inline virtual
Definition at line 113 of file qguiplatformplugin_p.h.
Referenced by QColorDialog::~QColorDialog().
 {}
colorDialogSetCurrentColor()
virtual void QGuiPlatformPlugin::colorDialogSetCurrentColor (QColorDialog * , const QColor &) inline virtual
Definition at line 115 of file qguiplatformplugin_p.h.
Referenced by QColorDialog::setCurrentColor().
 {}
colorDialogSetVisible()
virtual bool QGuiPlatformPlugin::colorDialogSetVisible (QColorDialog * , bool) inline virtual
Definition at line 114 of file qguiplatformplugin_p.h.
 { return false; }
fileDialogDelete()
virtual void QGuiPlatformPlugin::fileDialogDelete (QFileDialog *) inline virtual
Definition at line 101 of file qguiplatformplugin_p.h.
Referenced by QFileDialogPrivate::rootPath().
 {}
fileDialogDirectory()
virtual QString QGuiPlatformPlugin::fileDialogDirectory (const QFileDialog *) const inline virtual
Definition at line 105 of file qguiplatformplugin_p.h.
Referenced by QFileDialogPrivate::rootPath().
 { return QString(); }
fileDialogResultCode()
virtual QDialog::DialogCode QGuiPlatformPlugin::fileDialogResultCode (QFileDialog *) inline virtual
Definition at line 103 of file qguiplatformplugin_p.h.
Referenced by QFileDialogPrivate::rootPath().
 { return QDialog::Rejected; }
fileDialogSelectedFiles()
virtual QStringList QGuiPlatformPlugin::fileDialogSelectedFiles (const QFileDialog *) const inline virtual
Definition at line 107 of file qguiplatformplugin_p.h.
Referenced by QFileDialogPrivate::rootPath().
 { return QStringList(); }
fileDialogSelectedNameFilter()
virtual QString QGuiPlatformPlugin::fileDialogSelectedNameFilter (const QFileDialog *) const inline virtual
Definition at line 111 of file qguiplatformplugin_p.h.
Referenced by QFileDialogPrivate::rootPath().
 { return QString(); }
fileDialogSelectFile()
virtual void QGuiPlatformPlugin::fileDialogSelectFile (QFileDialog * , const QString &) inline virtual
Definition at line 106 of file qguiplatformplugin_p.h.
Referenced by QFileDialogPrivate::rootPath().
 {}
fileDialogSelectNameFilter()
virtual void QGuiPlatformPlugin::fileDialogSelectNameFilter (QFileDialog * , const QString &) inline virtual
Definition at line 110 of file qguiplatformplugin_p.h.
Referenced by QFileDialogPrivate::rootPath().
 {}
fileDialogSetDirectory()
virtual void QGuiPlatformPlugin::fileDialogSetDirectory (QFileDialog * , const QString &) inline virtual
Definition at line 104 of file qguiplatformplugin_p.h.
Referenced by QFileDialogPrivate::rootPath().
 {}
fileDialogSetFilter()
virtual void QGuiPlatformPlugin::fileDialogSetFilter (QFileDialog *) inline virtual
Definition at line 108 of file qguiplatformplugin_p.h.
Referenced by QFileDialogPrivate::rootPath().
 {}
fileDialogSetNameFilters()
virtual void QGuiPlatformPlugin::fileDialogSetNameFilters (QFileDialog * , const QStringList &) inline virtual
Definition at line 109 of file qguiplatformplugin_p.h.
Referenced by QFileDialogPrivate::rootPath().
 {}
fileDialogSetVisible()
virtual bool QGuiPlatformPlugin::fileDialogSetVisible (QFileDialog * , bool) inline virtual
Definition at line 102 of file qguiplatformplugin_p.h.
Referenced by QFileDialogPrivate::rootPath().
 { return false; }
fileSystemIcon()
QIcon QGuiPlatformPlugin::fileSystemIcon (const QFileInfo &) virtual
Definition at line 267 of file qguiplatformplugin.cpp.
Referenced by QFileIconProvider::icon().
 {
     return QIcon();
 }
iconThemeSearchPaths()
QStringList QGuiPlatformPlugin::iconThemeSearchPaths () virtual
Definition at line 227 of file qguiplatformplugin.cpp.
Referenced by QIconLoader::themeSearchPaths().
 {
     QStringList paths;
 #if defined(Q_WS_X11)
     QString xdgDirString = QFile::decodeName(getenv("XDG_DATA_DIRS"));
     if (xdgDirString.isEmpty())
         xdgDirString = QLatin1String("/usr/local/share/:/usr/share/");
     QStringList xdgDirs = xdgDirString.split(QLatin1Char(':'));
     for (int i = 0 ; i < xdgDirs.size() ; ++i) {
         QDir dir(xdgDirs[i]);
         if (dir.exists())
             paths.append(dir.path() + QLatin1String("/icons"));
     }
     if (X11->desktopEnvironment == DE_KDE) {
         paths << QLatin1Char(':') + QKde::kdeHome() + QLatin1String("/share/icons");
         QStringList kdeDirs = QFile::decodeName(getenv("KDEDIRS")).split(QLatin1Char(':'));
         for (int i = 0 ; i< kdeDirs.count() ; ++i) {
             QDir dir(QLatin1Char(':') + kdeDirs.at(i) + QLatin1String("/share/icons"));
             if (dir.exists())
                 paths.append(dir.path());
         }
     }
     // Add home directory first in search path
     QDir homeDir(QDir::homePath() + QLatin1String("/.icons"));
     if (homeDir.exists())
         paths.prepend(homeDir.path());
 #endif
 #if defined(Q_WS_WIN)
     paths.append(qApp->applicationDirPath() + QLatin1String("/icons"));
 #elif defined(Q_WS_MAC)
     paths.append(qApp->applicationDirPath() + QLatin1String("/../Resources/icons"));
 #endif
     return paths;
 }
keys()
virtual QStringList QGuiPlatformPlugin::keys () const inline virtual
Implements QFactoryInterface.
Definition at line 89 of file qguiplatformplugin_p.h.
 {  return QStringList() << QLatin1String("default");  };
palette()
QPalette QGuiPlatformPlugin::palette () virtual
Definition at line 194 of file qguiplatformplugin.cpp.
 {
 #ifdef Q_WS_X11
     if (QApplication::desktopSettingsAware() && X11->desktopEnvironment == DE_KDE)
         return QKde::kdePalette();
 #endif
     return QPalette();
 }
platformHint()
int QGuiPlatformPlugin::platformHint (PlatformHint hint) virtual
Definition at line 273 of file qguiplatformplugin.cpp.
Referenced by QCommonStyle::pixelMetric(), and QCommonStyle::styleHint().
 {
     int ret = 0;
     switch(hint)
     {
         case PH_ToolButtonStyle:
             ret = Qt::ToolButtonIconOnly;
 #ifdef Q_WS_X11
             if (X11->desktopEnvironment == DE_KDE && X11->desktopVersion >= 4
                 && QApplication::desktopSettingsAware()) {
                 ret = QKde::kdeToolButtonStyle();
             }
 #endif
             break;
         case PH_ToolBarIconSize:
 #ifdef Q_WS_X11
             if (X11->desktopEnvironment == DE_KDE && X11->desktopVersion >= 4
                 && QApplication::desktopSettingsAware()) {
                 ret = QKde::kdeToolBarIconSize();
             }
 #endif
             //by default keep ret = 0 so QCommonStyle will use the style default
             break;
         default:
             break;
     }
     return ret;
 }
styleName()
QString QGuiPlatformPlugin::styleName () virtual
Definition at line 134 of file qguiplatformplugin.cpp.
Referenced by QApplicationPrivate::desktopStyleKey(), and QApplicationPrivate::x11_apply_settings().
 {
 #if defined(Q_WS_WIN) && defined(Q_WS_WINCE)
     if (qt_wince_is_smartphone() || qt_wince_is_pocket_pc())
         return QLatin1String("WindowsMobile");
     else
         return QLatin1String("WindowsCE");
 #elif defined(Q_WS_WIN)
     if ((QSysInfo::WindowsVersion >= QSysInfo::WV_VISTA
         && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based)))
         return QLatin1String("WindowsVista");
     else if ((QSysInfo::WindowsVersion >= QSysInfo::WV_XP
         && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based)))
         return QLatin1String("WindowsXP");
     else
         return QLatin1String("Windows");                // default styles for Windows
 #elif defined(Q_WS_X11) && defined(Q_OS_SOLARIS)
     return QLatin1String("CDE");                        // default style for X11 on Solaris
 #elif defined(Q_WS_S60)
     return QLatin1String("S60");                        // default style for Symbian with S60
 #elif defined(Q_OS_SYMBIAN)
     return QLatin1String("Windows");                    // default style for Symbian without S60
 #elif defined(Q_WS_X11) && defined(Q_OS_IRIX)
     return QLatin1String("SGI");                        // default style for X11 on IRIX
 #elif defined(Q_WS_QWS) || defined(Q_WS_QPA)
     return QLatin1String("Plastique");                  // default style for X11 and small devices
 #elif defined(Q_WS_MAC)
     return QLatin1String("Macintosh");              // default style for all Mac's
 #elif defined(Q_WS_X11)
     QString stylename;
     switch(X11->desktopEnvironment) {
     case DE_KDE:
         stylename = QKde::kdeStyle();
         break;
     case DE_GNOME: {
         QStringList availableStyles = QStyleFactory::keys();
         // Set QGtkStyle for GNOME if available
         QString gtkStyleKey = QString::fromLatin1("GTK+");
         if (availableStyles.contains(gtkStyleKey)) {
             stylename = gtkStyleKey;
             break;
         }
         if (X11->use_xrender)
             stylename = QLatin1String("cleanlooks");
         else
             stylename = QLatin1String("windows");
         break;
     }
     case DE_CDE:
         stylename = QLatin1String("cde");
         break;
     default:
         // Don't do anything
         break;
     }
     return stylename;
 #endif
 }
systemIconThemeName()
QString QGuiPlatformPlugin::systemIconThemeName () virtual
Definition at line 205 of file qguiplatformplugin.cpp.
Referenced by QIconLoader::ensureInitialized(), and QIconLoader::updateSystemTheme().
 {
     QString result;
 #ifdef Q_WS_X11
     if (X11->desktopEnvironment == DE_GNOME) {
 #ifndef QT_NO_STYLE_GTK
         result = QGtkStylePrivate::getIconThemeName();
 #endif
         if (result.isEmpty()) {
             result = QString::fromLatin1("gnome");
         }
     } else if (X11->desktopEnvironment == DE_KDE) {
         result =  X11->desktopVersion >= 4 ? QString::fromLatin1("oxygen") : QString::fromLatin1("crystalsvg");
         QSettings settings(QKde::kdeHome() + QLatin1String("/share/config/kdeglobals"), QSettings::IniFormat);
         settings.beginGroup(QLatin1String("Icons"));
         result = settings.value(QLatin1String("Theme"), result).toString();
     }
 #endif
     return result;
 }
The documentation for this class was generated from the following files:
/src/gui/kernel/qguiplatformplugin_p.h
/src/gui/kernel/qguiplatformplugin.cpp