Qt 4.8: QXmlSchemaPrivate Class Reference
QXmlSchemaPrivate Class Reference
#include <qxmlschema_p.h>
Public Functions
QUrl documentUri () const
bool isValid () const
void load (const QUrl &source, const QString &targetNamespace)
void load (QIODevice *source, const QUrl &documentUri, const QString &targetNamespace)
void load (const QByteArray &data, const QUrl &documentUri, const QString &targetNamespace)
QAbstractMessageHandler * messageHandler () const
QXmlNamePool namePool () const
QNetworkAccessManager * networkAccessManager () const
QXmlSchemaPrivate (const QXmlNamePool &namePool)
QXmlSchemaPrivate (const QPatternist::XsdSchemaContext::Ptr &schemaContext)
QXmlSchemaPrivate (const QXmlSchemaPrivate &other)
void setMessageHandler (QAbstractMessageHandler *handler)
void setNetworkAccessManager (QNetworkAccessManager *networkmanager)
void setUriResolver (const QAbstractUriResolver *resolver)
const QAbstractUriResolver * uriResolver () const
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Variables
QUrl m_documentUri
QPatternist::ReferenceCountedValue< QAbstractMessageHandler >::Ptr m_messageHandler
QXmlNamePool m_namePool
QPatternist::ReferenceCountedValue< QNetworkAccessManager >::Ptr m_networkAccessManager
QPatternist::XsdSchemaContext::Ptr m_schemaContext
bool m_schemaIsValid
QPatternist::XsdSchemaParserContext::Ptr m_schemaParserContext
const QAbstractUriResolver * m_uriResolver
QAbstractMessageHandler * m_userMessageHandler
QNetworkAccessManager * m_userNetworkAccessManager
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Definition at line 72 of file qxmlschema_p.h.
Constructors and Destructors
QXmlSchemaPrivate() [1/3]
QXmlSchemaPrivate::QXmlSchemaPrivate (const QXmlNamePool & namePool)
Definition at line 52 of file qxmlschema_p.cpp.
     : m_namePool(namePool)
     , m_userMessageHandler(0)
     , m_uriResolver(0)
     , m_userNetworkAccessManager(0)
     , m_schemaContext(new QPatternist::XsdSchemaContext(m_namePool.d))
     , m_schemaParserContext(new QPatternist::XsdSchemaParserContext(m_namePool.d, m_schemaContext))
     , m_schemaIsValid(false)
 {
     m_networkAccessManager = new QPatternist::ReferenceCountedValue<QNetworkAccessManager>(new QNetworkAccessManager());
     m_messageHandler = new QPatternist::ReferenceCountedValue<QAbstractMessageHandler>(new QPatternist::ColoringMessageHandler());
 }
QXmlSchemaPrivate() [2/3]
QXmlSchemaPrivate::QXmlSchemaPrivate (const QPatternist::XsdSchemaContext::Ptr & schemaContext)
Definition at line 65 of file qxmlschema_p.cpp.
     : m_namePool(QXmlNamePool(schemaContext->namePool().data()))
     , m_userMessageHandler(0)
     , m_uriResolver(0)
     , m_userNetworkAccessManager(0)
     , m_schemaContext(schemaContext)
     , m_schemaParserContext(new QPatternist::XsdSchemaParserContext(m_namePool.d, m_schemaContext))
     , m_schemaIsValid(false)
 {
     m_networkAccessManager = new QPatternist::ReferenceCountedValue<QNetworkAccessManager>(new QNetworkAccessManager());
     m_messageHandler = new QPatternist::ReferenceCountedValue<QAbstractMessageHandler>(new QPatternist::ColoringMessageHandler());
 }
QXmlSchemaPrivate() [3/3]
QXmlSchemaPrivate::QXmlSchemaPrivate (const QXmlSchemaPrivate & other)
Definition at line 78 of file qxmlschema_p.cpp.
     : QSharedData(other)
 {
     m_namePool = other.m_namePool;
     m_userMessageHandler = other.m_userMessageHandler;
     m_uriResolver = other.m_uriResolver;
     m_userNetworkAccessManager = other.m_userNetworkAccessManager;
     m_messageHandler = other.m_messageHandler;
     m_networkAccessManager = other.m_networkAccessManager;
     m_schemaContext = other.m_schemaContext;
     m_schemaParserContext = other.m_schemaParserContext;
     m_schemaIsValid = other.m_schemaIsValid;
     m_documentUri = other.m_documentUri;
 }
Functions
documentUri()
QUrl QXmlSchemaPrivate::documentUri () const
Definition at line 163 of file qxmlschema_p.cpp.
Referenced by QXmlSchema::documentUri().
 {
     return m_documentUri;
 }
isValid()
bool QXmlSchemaPrivate::isValid () const
Definition at line 153 of file qxmlschema_p.cpp.
Referenced by QXmlSchema::isValid(), QXmlSchema::load(), and QPatternist::XsdValidatingInstanceReader::loadSchema().
 {
     return m_schemaIsValid;
 }
load() [1/3]
void QXmlSchemaPrivate::load (const QUrl & source, const QString & targetNamespace)
Definition at line 94 of file qxmlschema_p.cpp.
Referenced by QXmlSchema::load(), load(), and QPatternist::XsdValidatingInstanceReader::loadSchema().
 {
     m_documentUri = QPatternist::XPathHelper::normalizeQueryURI(source);
     m_schemaContext->setMessageHandler(messageHandler());
     m_schemaContext->setUriResolver(uriResolver());
     m_schemaContext->setNetworkAccessManager(networkAccessManager());
     const QPatternist::AutoPtr<QNetworkReply> reply(QPatternist::AccelTreeResourceLoader::load(source, m_schemaContext->networkAccessManager(),
                                                                                                m_schemaContext, QPatternist::AccelTreeResourceLoader::ContinueOnError));
     if (reply)
         load(reply.data(), source, targetNamespace);
 }
load() [2/3]
void QXmlSchemaPrivate::load (QIODevice * source, const QUrl & documentUri, const QString & targetNamespace)
Definition at line 118 of file qxmlschema_p.cpp.
 {
     m_schemaParserContext = QPatternist::XsdSchemaParserContext::Ptr(new QPatternist::XsdSchemaParserContext(m_namePool.d, m_schemaContext));
     m_schemaIsValid = false;
     if (!source) {
         qWarning("A null QIODevice pointer cannot be passed.");
         return;
     }
     if (!source->isReadable()) {
         qWarning("The device must be readable.");
         return;
     }
     m_documentUri = QPatternist::XPathHelper::normalizeQueryURI(documentUri);
     m_schemaContext->setMessageHandler(messageHandler());
     m_schemaContext->setUriResolver(uriResolver());
     m_schemaContext->setNetworkAccessManager(networkAccessManager());
     QPatternist::XsdSchemaParser parser(m_schemaContext, m_schemaParserContext, source);
     parser.setDocumentURI(documentUri);
     parser.setTargetNamespace(targetNamespace);
     try {
         parser.parse();
         m_schemaParserContext->resolver()->resolve();
         m_schemaIsValid = true;
     } catch (QPatternist::Exception exception) {
         Q_UNUSED(exception);
         m_schemaIsValid = false;
     }
 }
load() [3/3]
void QXmlSchemaPrivate::load (const QByteArray & data, const QUrl & documentUri, const QString & targetNamespace)
Definition at line 108 of file qxmlschema_p.cpp.
 {
     QByteArray localData(data);
     QBuffer buffer(&localData);
     buffer.open(QIODevice::ReadOnly);
     load(&buffer, documentUri, targetNamespace);
 }
messageHandler()
QAbstractMessageHandler * QXmlSchemaPrivate::messageHandler () const
Definition at line 173 of file qxmlschema_p.cpp.
Referenced by load(), and QXmlSchema::messageHandler().
 {
     if (m_userMessageHandler)
         return m_userMessageHandler;
     return m_messageHandler.data()->value;
 }
namePool()
QXmlNamePool QXmlSchemaPrivate::namePool () const
Definition at line 158 of file qxmlschema_p.cpp.
Referenced by QXmlSchema::namePool().
 {
     return m_namePool;
 }
networkAccessManager()
QNetworkAccessManager * QXmlSchemaPrivate::networkAccessManager () const
Definition at line 196 of file qxmlschema_p.cpp.
Referenced by load(), and QXmlSchema::networkAccessManager().
 {
     if (m_userNetworkAccessManager)
         return m_userNetworkAccessManager;
     return m_networkAccessManager.data()->value;
 }
setMessageHandler()
void QXmlSchemaPrivate::setMessageHandler (QAbstractMessageHandler * handler)
Definition at line 168 of file qxmlschema_p.cpp.
Referenced by QXmlSchema::setMessageHandler().
 {
     m_userMessageHandler = handler;
 }
setNetworkAccessManager()
void QXmlSchemaPrivate::setNetworkAccessManager (QNetworkAccessManager * networkmanager)
Definition at line 191 of file qxmlschema_p.cpp.
Referenced by QXmlSchema::setNetworkAccessManager().
 {
     m_userNetworkAccessManager = networkmanager;
 }
setUriResolver()
void QXmlSchemaPrivate::setUriResolver (const QAbstractUriResolver * resolver)
Definition at line 181 of file qxmlschema_p.cpp.
Referenced by QXmlSchema::setUriResolver().
 {
     m_uriResolver = resolver;
 }
uriResolver()
const QAbstractUriResolver * QXmlSchemaPrivate::uriResolver () const
Definition at line 186 of file qxmlschema_p.cpp.
Referenced by load(), and QXmlSchema::uriResolver().
 {
     return m_uriResolver;
 }
Properties
m_documentUri
QUrl QXmlSchemaPrivate::m_documentUri
Definition at line 102 of file qxmlschema_p.h.
Referenced by documentUri(), load(), and QXmlSchemaPrivate().
m_messageHandler
QPatternist::ReferenceCountedValue<QAbstractMessageHandler>::Ptr QXmlSchemaPrivate::m_messageHandler
Definition at line 96 of file qxmlschema_p.h.
Referenced by messageHandler(), QXmlSchemaPrivate(), and QXmlSchemaValidatorPrivate::QXmlSchemaValidatorPrivate().
m_namePool
QXmlNamePool QXmlSchemaPrivate::m_namePool
Definition at line 92 of file qxmlschema_p.h.
Referenced by load(), namePool(), and QXmlSchemaPrivate().
m_networkAccessManager
QPatternist::ReferenceCountedValue<QNetworkAccessManager>::Ptr QXmlSchemaPrivate::m_networkAccessManager
Definition at line 97 of file qxmlschema_p.h.
Referenced by networkAccessManager(), QXmlSchemaPrivate(), and QXmlSchemaValidatorPrivate::QXmlSchemaValidatorPrivate().
m_schemaContext
QPatternist::XsdSchemaContext::Ptr QXmlSchemaPrivate::m_schemaContext
Definition at line 99 of file qxmlschema_p.h.
Referenced by load(), QXmlSchemaPrivate(), and QXmlSchemaValidatorPrivate::setSchema().
m_schemaIsValid
bool QXmlSchemaPrivate::m_schemaIsValid
Definition at line 101 of file qxmlschema_p.h.
Referenced by isValid(), load(), and QXmlSchemaPrivate().
m_schemaParserContext
QPatternist::XsdSchemaParserContext::Ptr QXmlSchemaPrivate::m_schemaParserContext
Definition at line 100 of file qxmlschema_p.h.
Referenced by load(), QPatternist::XsdValidatingInstanceReader::loadSchema(), QXmlSchemaPrivate(), and QXmlSchemaValidatorPrivate::setSchema().
m_uriResolver
const QAbstractUriResolver* QXmlSchemaPrivate::m_uriResolver
Definition at line 94 of file qxmlschema_p.h.
Referenced by QXmlSchemaPrivate(), QXmlSchemaValidatorPrivate::QXmlSchemaValidatorPrivate(), setUriResolver(), and uriResolver().
m_userMessageHandler
QAbstractMessageHandler* QXmlSchemaPrivate::m_userMessageHandler
Definition at line 93 of file qxmlschema_p.h.
Referenced by messageHandler(), QXmlSchemaPrivate(), QXmlSchemaValidatorPrivate::QXmlSchemaValidatorPrivate(), and setMessageHandler().
m_userNetworkAccessManager
QNetworkAccessManager* QXmlSchemaPrivate::m_userNetworkAccessManager
Definition at line 95 of file qxmlschema_p.h.
Referenced by networkAccessManager(), QXmlSchemaPrivate(), QXmlSchemaValidatorPrivate::QXmlSchemaValidatorPrivate(), and setNetworkAccessManager().
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qxmlschema_p.h
/src/xmlpatterns/api/qxmlschema_p.cpp