Qt 4.8: QMdi::ControlContainer Class Reference
QMdi::ControlContainer Class Reference
#include <qmdisubwindow_p.h>
Public Functions
ControlContainer (QMdiSubWindow *mdiChild)
QWidget * controllerWidget () const
QMenuBar * menuBar () const
void removeButtonsFromMenuBar (QMenuBar *menuBar=0)
void showButtonsInMenuBar (QMenuBar *menuBar)
QWidget * systemMenuLabel () const
void updateWindowIcon (const QIcon &windowIcon)
~ControlContainer ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QPointer< QWidget > m_controllerWidget
QPointer< QMenuBar > m_menuBar
QPointer< QWidget > m_menuLabel
QPointer< QMdiSubWindow > mdiChild
QPointer< QWidget > previousLeft
QPointer< QWidget > previousRight
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 94 of file qmdisubwindow_p.h.
Constructors and Destructors
ControlContainer()
ControlContainer::ControlContainer (QMdiSubWindow * mdiChild)
Definition at line 719 of file qmdisubwindow.cpp.
     : QObject(mdiChild),
       previousLeft(0),
       previousRight(0),
 #ifndef QT_NO_MENUBAR
       m_menuBar(0),
 #endif
       mdiChild(mdiChild)
 {
     Q_ASSERT(mdiChild);
     m_controllerWidget = new ControlElement<ControllerWidget>(mdiChild);
     connect(m_controllerWidget, SIGNAL(_q_close()), mdiChild, SLOT(close()));
     connect(m_controllerWidget, SIGNAL(_q_restore()), mdiChild, SLOT(showNormal()));
     connect(m_controllerWidget, SIGNAL(_q_minimize()), mdiChild, SLOT(showMinimized()));
     m_menuLabel = new ControlElement<ControlLabel>(mdiChild);
     m_menuLabel->setWindowIcon(mdiChild->windowIcon());
 #ifndef QT_NO_MENU
     connect(m_menuLabel, SIGNAL(_q_clicked()), mdiChild, SLOT(showSystemMenu()));
 #endif
     connect(m_menuLabel, SIGNAL(_q_doubleClicked()), mdiChild, SLOT(close()));
 }
~ControlContainer()
ControlContainer::~ControlContainer ()
Definition at line 743 of file qmdisubwindow.cpp.
 {
 #ifndef QT_NO_MENUBAR
     removeButtonsFromMenuBar();
 #endif
     delete m_menuLabel;
     m_menuLabel = 0;
     delete m_controllerWidget;
     m_controllerWidget = 0;
 }
Functions
controllerWidget()
QWidget* QMdi::ControlContainer::controllerWidget () const inline
Definition at line 106 of file qmdisubwindow_p.h.
Referenced by QMdiSubWindowPrivate::setVisible(), showButtonsInMenuBar(), and QMdiSubWindowPrivate::showButtonsInMenuBar().
 { return m_controllerWidget; }
menuBar()
QMenuBar* QMdi::ControlContainer::menuBar () const inline
Definition at line 103 of file qmdisubwindow_p.h.
Referenced by removeButtonsFromMenuBar(), and showButtonsInMenuBar().
 { return m_menuBar; }
removeButtonsFromMenuBar()
void ControlContainer::removeButtonsFromMenuBar (QMenuBar * menuBar = 0)
Definition at line 810 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindowPrivate::removeButtonsFromMenuBar(), and ~ControlContainer().
 {
     if (menuBar && menuBar != m_menuBar) {
         // m_menubar was deleted while sub-window was maximized
         previousRight = 0;
         previousLeft = 0;
         m_menuBar = menuBar;
     }
     if (!m_menuBar || !mdiChild || qt_widget_private(mdiChild->window())->data.in_destructor)
         return;
     QMdiSubWindow *child = 0;
     if (m_controllerWidget) {
         QWidget *currentRight = m_menuBar->cornerWidget(Qt::TopRightCorner);
         if (currentRight == m_controllerWidget) {
             if (ControlElement<ControllerWidget> *ce = ptr<ControllerWidget>(previousRight)) {
                 if (!ce->mdiChild || !ce->mdiChild->isMaximized())
                     previousRight = 0;
                 else
                     child = ce->mdiChild;
             }
             m_menuBar->setCornerWidget(previousRight, Qt::TopRightCorner);
             if (previousRight) {
                 previousRight->show();
                 previousRight = 0;
             }
         }
         m_controllerWidget->hide();
         m_controllerWidget->setParent(0);
     }
     if (m_menuLabel) {
         QWidget *currentLeft = m_menuBar->cornerWidget(Qt::TopLeftCorner);
         if (currentLeft == m_menuLabel) {
             if (ControlElement<ControlLabel> *ce = ptr<ControlLabel>(previousLeft)) {
                 if (!ce->mdiChild || !ce->mdiChild->isMaximized())
                     previousLeft = 0;
                 else if (!child)
                     child = mdiChild;
             }
             m_menuBar->setCornerWidget(previousLeft, Qt::TopLeftCorner);
             if (previousLeft) {
                 previousLeft->show();
                 previousLeft = 0;
             }
         }
         m_menuLabel->hide();
         m_menuLabel->setParent(0);
     }
     m_menuBar->update();
     if (child)
         child->d_func()->setNewWindowTitle();
     else if (mdiChild)
         mdiChild->window()->setWindowTitle(mdiChild->d_func()->originalWindowTitle());
 }
showButtonsInMenuBar()
void ControlContainer::showButtonsInMenuBar (QMenuBar * menuBar)
Definition at line 777 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindowPrivate::showButtonsInMenuBar().
 {
     if (!menuBar || !mdiChild || mdiChild->windowFlags() & Qt::FramelessWindowHint)
         return;
     m_menuBar = menuBar;
     if (m_menuLabel && mdiChild->windowFlags() & Qt::WindowSystemMenuHint) {
         QWidget *currentLeft = menuBar->cornerWidget(Qt::TopLeftCorner);
         if (currentLeft)
             currentLeft->hide();
         if (currentLeft != m_menuLabel) {
             menuBar->setCornerWidget(m_menuLabel, Qt::TopLeftCorner);
             previousLeft = currentLeft;
         }
         m_menuLabel->show();
     }
     ControllerWidget *controllerWidget = qobject_cast<ControllerWidget *>(m_controllerWidget);
     if (controllerWidget && controllerWidget->hasVisibleControls()) {
         QWidget *currentRight = menuBar->cornerWidget(Qt::TopRightCorner);
         if (currentRight)
             currentRight->hide();
         if (currentRight != m_controllerWidget) {
             menuBar->setCornerWidget(m_controllerWidget, Qt::TopRightCorner);
             previousRight = currentRight;
         }
         m_controllerWidget->show();
     }
     mdiChild->d_func()->setNewWindowTitle();
 }
systemMenuLabel()
QWidget* QMdi::ControlContainer::systemMenuLabel () const inline
Definition at line 107 of file qmdisubwindow_p.h.
Referenced by QMdiSubWindowPrivate::showButtonsInMenuBar().
 { return m_menuLabel; }
updateWindowIcon()
void ControlContainer::updateWindowIcon (const QIcon & windowIcon)
Definition at line 868 of file qmdisubwindow.cpp.
 {
     if (m_menuLabel)
         m_menuLabel->setWindowIcon(windowIcon);
 }
Properties
m_controllerWidget
QPointer<QWidget> QMdi::ControlContainer::m_controllerWidget private
Definition at line 115 of file qmdisubwindow_p.h.
Referenced by ControlContainer(), removeButtonsFromMenuBar(), showButtonsInMenuBar(), and ~ControlContainer().
m_menuBar
QPointer<QMenuBar> QMdi::ControlContainer::m_menuBar private
Definition at line 113 of file qmdisubwindow_p.h.
Referenced by removeButtonsFromMenuBar(), and showButtonsInMenuBar().
m_menuLabel
QPointer<QWidget> QMdi::ControlContainer::m_menuLabel private
Definition at line 116 of file qmdisubwindow_p.h.
Referenced by ControlContainer(), removeButtonsFromMenuBar(), showButtonsInMenuBar(), updateWindowIcon(), and ~ControlContainer().
mdiChild
QPointer<QMdiSubWindow> QMdi::ControlContainer::mdiChild private
Definition at line 117 of file qmdisubwindow_p.h.
Referenced by ControlContainer(), removeButtonsFromMenuBar(), and showButtonsInMenuBar().
previousLeft
QPointer<QWidget> QMdi::ControlContainer::previousLeft private
Definition at line 110 of file qmdisubwindow_p.h.
Referenced by removeButtonsFromMenuBar(), and showButtonsInMenuBar().
previousRight
QPointer<QWidget> QMdi::ControlContainer::previousRight private
Definition at line 111 of file qmdisubwindow_p.h.
Referenced by removeButtonsFromMenuBar(), and showButtonsInMenuBar().
The documentation for this class was generated from the following files:
/src/gui/widgets/qmdisubwindow_p.h
/src/gui/widgets/qmdisubwindow.cpp