Qt 4.8: QMainWindow Class Reference
QMainWindow Class Reference
The QMainWindow class provides a main application window.
#include <qmainwindow.h>
Public Types
enum DockOption {
AnimatedDocks = 0x01, AllowNestedDocks = 0x02, AllowTabbedDocks = 0x04, ForceTabbedDocks = 0x08,
VerticalTabs = 0x10
}
This enum contains flags that specify the docking behavior of QMainWindow.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void setAnimated (bool enabled)
void setDockNestingEnabled (bool enabled)
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void iconSizeChanged (const QSize &iconSize)
This signal is emitted when the size of the icons used in the window is changed.
void toolButtonStyleChanged (Qt::ToolButtonStyle toolButtonStyle)
This signal is emitted when the style used for tool buttons in the window is changed.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addDockWidget (Qt::DockWidgetArea area, QDockWidget *dockwidget)
Adds the given dockwidget to the specified area.
void addDockWidget (Qt::DockWidgetArea area, QDockWidget *dockwidget, Qt::Orientation orientation)
Adds dockwidget into the given area in the direction specified by the orientation.
void addToolBar (Qt::ToolBarArea area, QToolBar *toolbar)
Adds the toolbar into the specified area in this main window.
void addToolBar (QToolBar *toolbar)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Equivalent of calling addToolBar(Qt::TopToolBarArea, toolbar)
QToolBar * addToolBar (const QString &title)
Creates a QToolBar object, setting its window title to title, and inserts it into the top toolbar area.
void addToolBarBreak (Qt::ToolBarArea area=Qt::TopToolBarArea)
Adds a toolbar break to the given area after all the other objects that are present.
QWidget * centralWidget () const
Returns the central widget for the main window.
Qt::DockWidgetArea corner (Qt::Corner corner) const
Returns the dock widget area that occupies the specified corner.
virtual QMenu * createPopupMenu ()
Returns a popup menu containing checkable entries for the toolbars and dock widgets present in the main window.
DockOptions dockOptions () const
Qt::DockWidgetArea dockWidgetArea (QDockWidget *dockwidget) const
Returns the Qt::DockWidgetArea for dockwidget.
bool documentMode () const
QSize iconSize () const
void insertToolBar (QToolBar *before, QToolBar *toolbar)
Inserts the toolbar into the area occupied by the before toolbar so that it appears before it.
void insertToolBarBreak (QToolBar *before)
Inserts a toolbar break before the toolbar specified by before.
bool isAnimated () const
bool isDockNestingEnabled () const
bool isSeparator (const QPoint &pos) const
QMenuBar * menuBar () const
Returns the menu bar for the main window.
QWidget * menuWidget () const
Returns the menu bar for the main window.
QMainWindow (QWidget *parent=0, Qt::WindowFlags flags=0)
Constructs a QMainWindow with the given parent and the specified widget flags.
void removeDockWidget (QDockWidget *dockwidget)
Removes the dockwidget from the main window layout and hides it.
void removeToolBar (QToolBar *toolbar)
Removes the toolbar from the main window layout and hides it.
void removeToolBarBreak (QToolBar *before)
Removes a toolbar break previously inserted before the toolbar specified by before.
bool restoreDockWidget (QDockWidget *dockwidget)
Restores the state of dockwidget if it is created after the call to restoreState().
bool restoreState (const QByteArray &state, int version=0)
Restores the state of this mainwindow's toolbars and dockwidgets.
QByteArray saveState (int version=0) const
Saves the current state of this mainwindow's toolbars and dockwidgets.
void setCentralWidget (QWidget *widget)
Sets the given widget to be the main window's central widget.
void setCorner (Qt::Corner corner, Qt::DockWidgetArea area)
Sets the given dock widget area to occupy the specified corner.
void setDockOptions (DockOptions options)
void setDocumentMode (bool enabled)
void setIconSize (const QSize &iconSize)
void setMenuBar (QMenuBar *menubar)
Sets the menu bar for the main window to menuBar.
void setMenuWidget (QWidget *menubar)
Sets the menu bar for the main window to menuBar.
void setStatusBar (QStatusBar *statusbar)
Sets the status bar for the main window to statusbar.
void setTabPosition (Qt::DockWidgetAreas areas, QTabWidget::TabPosition tabPosition)
Sets the tab position for the given dock widget areas to the specified tabPosition.
void setTabShape (QTabWidget::TabShape tabShape)
void setToolButtonStyle (Qt::ToolButtonStyle toolButtonStyle)
void setUnifiedTitleAndToolBarOnMac (bool set)
void splitDockWidget (QDockWidget *after, QDockWidget *dockwidget, Qt::Orientation orientation)
Splits the space covered by the first dock widget into two parts, moves the first dock widget into the first part, and moves the second dock widget into the second part.
QStatusBar * statusBar () const
Returns the status bar for the main window.
QList< QDockWidget * > tabifiedDockWidgets (QDockWidget *dockwidget) const
Returns the dock widgets that are tabified together with dockwidget.
void tabifyDockWidget (QDockWidget *first, QDockWidget *second)
Moves second dock widget on top of first dock widget, creating a tabbed docked area in the main window.
QTabWidget::TabPosition tabPosition (Qt::DockWidgetArea area) const
Returns the tab position for area.
QTabWidget::TabShape tabShape () const
Qt::ToolBarArea toolBarArea (QToolBar *toolbar) const
Returns the Qt::ToolBarArea for toolbar.
bool toolBarBreak (QToolBar *toolbar) const
Returns whether there is a toolbar break before the toolbar.
Qt::ToolButtonStyle toolButtonStyle () const
bool unifiedTitleAndToolBarOnMac () const
~QMainWindow ()
Destroys the main window.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
virtual QSize minimumSizeHint () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
virtual QSize sizeHint () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void contextMenuEvent (QContextMenuEvent *event)
Reimplemented Function
bool event (QEvent *event)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyPressEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key press events for the widget.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool animated
whether manipulating dock widgets and tool bars is animated
bool dockNestingEnabled
whether docks can be nested
DockOptions dockOptions
the docking behavior of QMainWindow
bool documentMode
whether the tab bar for tabbed dockwidgets is set to document mode.
QSize iconSize
size of toolbar icons in this mainwindow.
QTabWidget::TabShape tabShape
the tab shape used for tabbed dock widgets.
Qt::ToolButtonStyle toolButtonStyle
style of toolbar buttons in this mainwindow.
bool unifiedTitleAndToolBarOnMac
whether the window uses the unified title and toolbar look on Mac OS X
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QMainWindow class provides a main application window.
Qt Main Window Framework
A main window provides a framework for building an application's user interface. Qt has QMainWindow and its Main Window and Related Classes{related classes} for main window management. QMainWindow has its own layout to which you can add QToolBar, QDockWidget, a QMenuBar, and a QStatusBar. The layout has a center area that can be occupied by any kind of widget. You can see an image of the layout below.
Note
Creating a main window without a central widget is not supported. You must have a central widget even if it is just a placeholder.
Creating Main Window Components
A central widget will typically be a standard Qt widget such as a QTextEdit or a QGraphicsView. Custom widgets can also be used for advanced applications. You set the central widget with setCentralWidget().
Main windows have either a single (SDI) or multiple (MDI) document interface. You create MDI applications in Qt by using a QMdiArea as the central widget.
We will now examine each of the other widgets that can be added to a main window. We give examples on how to create and add them.
Creating Menus
Qt implements menus in QMenu and QMainWindow keeps them in a QMenuBar. QActions are added to the menus, which display them as menu items.
You can add new menus to the main window's menu bar by calling menuBar(), which returns the QMenuBar for the window, and then add a menu with QMenuBar::addMenu().
QMainWindow comes with a default menu bar, but you can also set one yourself with setMenuBar(). If you wish to implement a custom menu bar (i.e., not use the QMenuBar widget), you can set it with setMenuWidget().
An example of how to create menus follows:
void MainWindow::createMenus()
{
    fileMenu = menuBar()->addMenu(tr("&File"));
    fileMenu->addAction(newAct);
    fileMenu->addAction(openAct);
    fileMenu->addAction(saveAct);
The createPopupMenu() function creates popup menus when the main window receives context menu events. The default implementation generates a menu with the checkable actions from the dock widgets and toolbars. You can reimplement createPopupMenu() for a custom menu.
Creating Toolbars
Toolbars are implemented in the QToolBar class. You add a toolbar to a main window with addToolBar().
You control the initial position of toolbars by assigning them to a specific Qt::ToolBarArea. You can split an area by inserting a toolbar break - think of this as a line break in text editing - with addToolBarBreak() or insertToolBarBreak(). You can also restrict placement by the user with QToolBar::setAllowedAreas() and QToolBar::setMovable().
The size of toolbar icons can be retrieved with iconSize(). The sizes are platform dependent; you can set a fixed size with setIconSize(). You can alter the appearance of all tool buttons in the toolbars with setToolButtonStyle().
An example of toolbar creation follows:
void MainWindow::createToolBars()
{
    fileToolBar = addToolBar(tr("File"));
    fileToolBar->addAction(newAct);
Creating Dock Widgets
Dock widgets are implemented in the QDockWidget class. A dock widget is a window that can be docked into the main window. You add dock widgets to a main window with addDockWidget().
There are four dock widget areas as given by the Qt::DockWidgetArea enum: left, right, top, and bottom. You can specify which dock widget area that should occupy the corners where the areas overlap with setCorner(). By default each area can only contain one row (vertical or horizontal) of dock widgets, but if you enable nesting with setDockNestingEnabled(), dock widgets can be added in either direction.
Two dock widgets may also be stacked on top of each other. A QTabBar is then used to select which of the widgets that should be displayed.
We give an example of how to create and add dock widgets to a main window:
    QDockWidget *dockWidget = new QDockWidget(tr("Dock Widget"), this);
    dockWidget->setAllowedAreas(Qt::LeftDockWidgetArea |
                Qt::RightDockWidgetArea);
    dockWidget->setWidget(dockWidgetContents);
    addDockWidget(Qt::LeftDockWidgetArea, dockWidget);
The Status Bar
You can set a status bar with setStatusBar(), but one is created the first time statusBar() (which returns the main window's status bar) is called. See QStatusBar for information on how to use it.
Storing State
QMainWindow can store the state of its layout with saveState(); it can later be retrieved with restoreState(). It is the position and size (relative to the size of the main window) of the toolbars and dock widgets that are stored.
See also
QMenuBar, QToolBar, QStatusBar, QDockWidget, {Application Example}, {Dock Widgets Example}, {MDI Example}, {SDI Example}, {Menus Example}
Definition at line 63 of file qmainwindow.h.
Enumerations
DockOption
enum QMainWindow::DockOption
This enum contains flags that specify the docking behavior of QMainWindow.
Since
4.3
AnimatedDocks Identical to the animated property.
AllowNestedDocks Identical to the dockNestingEnabled property.
AllowTabbedDocks The user can drop one dock widget "on top" of another. The two widgets are stacked and a tab bar appears for selecting which one is visible.
ForceTabbedDocks Each dock area contains a single stack of tabbed dock widgets. In other words, dock widgets cannot be placed next to each other in a dock area. If this option is set, AllowNestedDocks has no effect.
VerticalTabs The two vertical dock areas on the sides of the main window show their tabs vertically. If this option is not set, all dock areas show their tabs at the bottom. Implies AllowTabbedDocks. See also setTabPosition() .
These options only control how dock widgets may be dropped in a QMainWindow. They do not re-arrange the dock widgets to conform with the specified options. For this reason they should be set before any dock widgets are added to the main window. Exceptions to this are the AnimatedDocks and VerticalTabs options, which may be set at any time.
Enumerator
AnimatedDocks
AllowNestedDocks
AllowTabbedDocks
ForceTabbedDocks
VerticalTabs
Definition at line 87 of file qmainwindow.h.
                     {
         AnimatedDocks = 0x01,
         AllowNestedDocks = 0x02,
         AllowTabbedDocks = 0x04,
         ForceTabbedDocks = 0x08,  // implies AllowTabbedDocks, !AllowNestedDocks
         VerticalTabs = 0x10       // implies AllowTabbedDocks
     };
Constructors and Destructors
QMainWindow()
QMainWindow::QMainWindow (QWidget * parent = 0, Qt::WindowFlags flags = 0) explicit
Constructs a QMainWindow with the given parent and the specified widget flags.
QMainWindow sets the Qt::Window flag itself, and will hence always be created as a top-level widget.
Definition at line 374 of file qmainwindow.cpp.
     : QWidget(*(new QMainWindowPrivate()), parent, flags | Qt::Window)
 {
     d_func()->init();
 }
~QMainWindow()
QMainWindow::~QMainWindow ()
Destroys the main window.
Definition at line 400 of file qmainwindow.cpp.
 { }
Functions
addDockWidget() [1/2]
void QMainWindow::addDockWidget (Qt::DockWidgetArea area, QDockWidget * dockwidget)
Adds the given dockwidget to the specified area.
Definition at line 1108 of file qmainwindow.cpp.
Referenced by QAxClientSite::qt_metacall(), and QScriptEngineDebugger::standardWindow().
 {
     if (!checkDockWidgetArea(area, "QMainWindow::addDockWidget"))
         return;
     Qt::Orientation orientation = Qt::Vertical;
     switch (area) {
     case Qt::TopDockWidgetArea:
     case Qt::BottomDockWidgetArea:
         orientation = Qt::Horizontal;
         break;
     default:
         break;
     }
     d_func()->layout->removeWidget(dockwidget); // in case it was already in here
     addDockWidget(area, dockwidget, orientation);
 #ifdef Q_WS_MAC     //drawer support
     QMacCocoaAutoReleasePool pool;
     extern bool qt_mac_is_macdrawer(const QWidget *); //qwidget_mac.cpp
     if (qt_mac_is_macdrawer(dockwidget)) {
         extern bool qt_mac_set_drawer_preferred_edge(QWidget *, Qt::DockWidgetArea); //qwidget_mac.cpp
         window()->createWinId();
         dockwidget->window()->createWinId();
         qt_mac_set_drawer_preferred_edge(dockwidget, area);
         if (dockwidget->isVisible()) {
             dockwidget->hide();
             dockwidget->show();
         }
     }
 #endif
 }
addDockWidget() [2/2]
void QMainWindow::addDockWidget (Qt::DockWidgetArea area, QDockWidget * dockwidget, Qt::Orientation orientation)
Adds dockwidget into the given area in the direction specified by the orientation.
Definition at line 1158 of file qmainwindow.cpp.
 {
     if (!checkDockWidgetArea(area, "QMainWindow::addDockWidget"))
         return;
     // add a window to an area, placing done relative to the previous
     d_func()->layout->addDockWidget(area, dockwidget, orientation);
 }
addToolBar() [1/3]
void QMainWindow::addToolBar (Qt::ToolBarArea area, QToolBar * toolbar)
Adds the toolbar into the specified area in this main window.
The toolbar is placed at the end of the current tool bar block (i.e. line). If the main window already manages toolbar then it will only move the toolbar to area.
See also
insertToolBar() addToolBarBreak() insertToolBarBreak()
Definition at line 764 of file qmainwindow.cpp.
Referenced by addToolBar(), QScriptEngineDebugger::standardWindow(), and QMenuBarPrivate::updateCornerWidgetToolBar().
 {
     if (!checkToolBarArea(area, "QMainWindow::addToolBar"))
         return;
     Q_D(QMainWindow);
     disconnect(this, SIGNAL(iconSizeChanged(QSize)),
                toolbar, SLOT(_q_updateIconSize(QSize)));
     disconnect(this, SIGNAL(toolButtonStyleChanged(Qt::ToolButtonStyle)),
                toolbar, SLOT(_q_updateToolButtonStyle(Qt::ToolButtonStyle)));
     if(toolbar->d_func()->state && toolbar->d_func()->state->dragging) {
         //removing a toolbar which is dragging will cause crash
 #ifndef QT_NO_DOCKWIDGET
         bool animated = isAnimated();
         setAnimated(false);
 #endif
         toolbar->d_func()->endDrag();
 #ifndef QT_NO_DOCKWIDGET
         setAnimated(animated);
 #endif
     }
     if (!d->layout->usesHIToolBar(toolbar)) {
         d->layout->removeWidget(toolbar);
     } else {
         d->layout->removeToolBar(toolbar);
     }
     toolbar->d_func()->_q_updateIconSize(d->iconSize);
     toolbar->d_func()->_q_updateToolButtonStyle(d->toolButtonStyle);
     connect(this, SIGNAL(iconSizeChanged(QSize)),
             toolbar, SLOT(_q_updateIconSize(QSize)));
     connect(this, SIGNAL(toolButtonStyleChanged(Qt::ToolButtonStyle)),
             toolbar, SLOT(_q_updateToolButtonStyle(Qt::ToolButtonStyle)));
     d->layout->addToolBar(area, toolbar);
 }
addToolBar() [2/3]
void QMainWindow::addToolBar (QToolBar * toolbar)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Equivalent of calling addToolBar(Qt::TopToolBarArea, toolbar)
Definition at line 807 of file qmainwindow.cpp.
 { addToolBar(Qt::TopToolBarArea, toolbar); }
addToolBar() [3/3]
QToolBar * QMainWindow::addToolBar (const QString & title)
Creates a QToolBar object, setting its window title to title, and inserts it into the top toolbar area.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setWindowTitle()
Definition at line 821 of file qmainwindow.cpp.
 {
     QToolBar *toolBar = new QToolBar(this);
     toolBar->setWindowTitle(title);
     addToolBar(toolBar);
     return toolBar;
 }
addToolBarBreak()
void QMainWindow::addToolBarBreak (Qt::ToolBarArea area = Qt::TopToolBarArea)
Adds a toolbar break to the given area after all the other objects that are present.
Definition at line 733 of file qmainwindow.cpp.
 {
     if (!checkToolBarArea(area, "QMainWindow::addToolBarBreak"))
         return;
     d_func()->layout->addToolBarBreak(area);
 }
centralWidget()
QWidget * QMainWindow::centralWidget () const
Returns the central widget for the main window.
This function returns zero if the central widget has not been set.
See also
setCentralWidget()
Definition at line 651 of file qmainwindow.cpp.
 { return d_func()->layout->centralWidget(); }
contextMenuEvent()
void QMainWindow::contextMenuEvent (QContextMenuEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1631 of file qmainwindow.cpp.
 {
     event->ignore();
     // only show the context menu for direct QDockWidget and QToolBar
     // children and for the menu bar as well
     QWidget *child = childAt(event->pos());
     while (child && child != this) {
 #ifndef QT_NO_MENUBAR
         if (QMenuBar *mb = qobject_cast<QMenuBar *>(child)) {
             if (mb->parentWidget() != this)
                 return;
             break;
         }
 #endif
 #ifndef QT_NO_DOCKWIDGET
         if (QDockWidget *dw = qobject_cast<QDockWidget *>(child)) {
             if (dw->parentWidget() != this)
                 return;
             if (dw->widget()
                 && dw->widget()->geometry().contains(child->mapFrom(this, event->pos()))) {
                 // ignore the event if the mouse is over the QDockWidget contents
                 return;
             }
             break;
         }
 #endif // QT_NO_DOCKWIDGET
 #ifndef QT_NO_TOOLBAR
         if (QToolBar *tb = qobject_cast<QToolBar *>(child)) {
             if (tb->parentWidget() != this)
                 return;
             break;
         }
 #endif
         child = child->parentWidget();
     }
     if (child == this)
         return;
 #ifndef QT_NO_MENU
     QMenu *popup = createPopupMenu();
     if (popup) {
         if (!popup->isEmpty()) {
             popup->setAttribute(Qt::WA_DeleteOnClose);
             popup->popup(event->globalPos());
             event->accept();
         } else {
             delete popup;
         }
     }
 #endif
 }
corner()
Qt::DockWidgetArea QMainWindow::corner (Qt::Corner corner) const
Returns the dock widget area that occupies the specified corner.
See also
setCorner()
Definition at line 708 of file qmainwindow.cpp.
 { return d_func()->layout->corner(corner); }
createPopupMenu()
QMenu * QMainWindow::createPopupMenu () virtual
Returns a popup menu containing checkable entries for the toolbars and dock widgets present in the main window.
If there are no toolbars and dock widgets present, this function returns a null pointer.
By default, this function is called by the main window when the user activates a context menu, typically by right-clicking on a toolbar or a dock widget.
If you want to create a custom popup menu, reimplement this function and return a newly-created popup menu. Ownership of the popup menu is transferred to the caller.
See also
addDockWidget(), addToolBar(), menuBar()
Definition at line 1700 of file qmainwindow.cpp.
Referenced by contextMenuEvent().
 {
     Q_D(QMainWindow);
     QMenu *menu = 0;
 #ifndef QT_NO_DOCKWIDGET
     QList<QDockWidget *> dockwidgets = findChildren<QDockWidget *>();
     if (dockwidgets.size()) {
         menu = new QMenu(this);
         for (int i = 0; i < dockwidgets.size(); ++i) {
             QDockWidget *dockWidget = dockwidgets.at(i);
             if (dockWidget->parentWidget() == this
                 && !d->layout->layoutState.dockAreaLayout.indexOf(dockWidget).isEmpty()) {
                 menu->addAction(dockwidgets.at(i)->toggleViewAction());
             }
         }
         menu->addSeparator();
     }
 #endif // QT_NO_DOCKWIDGET
 #ifndef QT_NO_TOOLBAR
     QList<QToolBar *> toolbars = findChildren<QToolBar *>();
     if (toolbars.size()) {
         if (!menu)
             menu = new QMenu(this);
         for (int i = 0; i < toolbars.size(); ++i) {
             QToolBar *toolBar = toolbars.at(i);
             if (toolBar->parentWidget() == this
                 && (!d->layout->layoutState.toolBarAreaLayout.indexOf(toolBar).isEmpty()
                     || (unifiedTitleAndToolBarOnMac()
                         && toolBarArea(toolBar) == Qt::TopToolBarArea))) {
                 menu->addAction(toolbars.at(i)->toggleViewAction());
             }
         }
     }
 #endif
     Q_UNUSED(d);
     return menu;
 }
dockOptions()
DockOptions QMainWindow::dockOptions () const
Referenced by setDockOptions().
dockWidgetArea()
Qt::DockWidgetArea QMainWindow::dockWidgetArea (QDockWidget * dockwidget) const
Returns the Qt::DockWidgetArea for dockwidget.
If dockwidget has not been added to the main window, this function returns Qt::NoDockWidgetArea.
See also
addDockWidget() splitDockWidget() Qt::DockWidgetArea
Definition at line 1261 of file qmainwindow.cpp.
 { return d_func()->layout->dockWidgetArea(dockwidget); }
documentMode()
bool QMainWindow::documentMode () const
Referenced by checkDockWidgetArea().
event()
bool QMainWindow::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1403 of file qmainwindow.cpp.
 {
     Q_D(QMainWindow);
     switch (event->type()) {
 #ifndef QT_NO_DOCKWIDGET
         case QEvent::Paint: {
             QPainter p(this);
             QRegion r = static_cast<QPaintEvent*>(event)->region();
             d->layout->layoutState.dockAreaLayout.paintSeparators(&p, this, r, d->hoverPos);
             break;
         }
 #ifndef QT_NO_CURSOR
         case QEvent::HoverMove:  {
             d->adjustCursor(static_cast<QHoverEvent*>(event)->pos());
             break;
         }
         // We don't want QWidget to call update() on the entire QMainWindow
         // on HoverEnter and HoverLeave, hence accept the event (return true).
         case QEvent::HoverEnter:
             return true;
         case QEvent::HoverLeave:
             d->adjustCursor(QPoint(0, 0));
             return true;
         case QEvent::ShortcutOverride: // when a menu pops up
             d->adjustCursor(QPoint(0, 0));
             break;
 #endif // QT_NO_CURSOR
         case QEvent::MouseButtonPress: {
             QMouseEvent *e = static_cast<QMouseEvent*>(event);
             if (e->button() == Qt::LeftButton && d->layout->startSeparatorMove(e->pos())) {
                 // The click was on a separator, eat this event
                 e->accept();
                 return true;
             }
             break;
         }
         case QEvent::MouseMove: {
             QMouseEvent *e = static_cast<QMouseEvent*>(event);
 #ifndef QT_NO_CURSOR
             d->adjustCursor(e->pos());
 #endif
             if (e->buttons() & Qt::LeftButton) {
                 if (d->layout->separatorMove(e->pos())) {
                     // We're moving a separator, eat this event
                     e->accept();
                     return true;
                 }
             }
             break;
         }
         case QEvent::MouseButtonRelease: {
             QMouseEvent *e = static_cast<QMouseEvent*>(event);
             if (d->layout->endSeparatorMove(e->pos())) {
                 // We've released a separator, eat this event
                 e->accept();
                 return true;
             }
             break;
         }
 #endif
 #ifndef QT_NO_TOOLBAR
         case QEvent::ToolBarChange: {
             d->layout->toggleToolBarsVisible();
             return true;
         }
 #endif
 #ifndef QT_NO_STATUSTIP
         case QEvent::StatusTip:
 #ifndef QT_NO_STATUSBAR
             if (QStatusBar *sb = d->layout->statusBar())
                 sb->showMessage(static_cast<QStatusTipEvent*>(event)->tip());
             else
 #endif
                 static_cast<QStatusTipEvent*>(event)->ignore();
             return true;
 #endif // QT_NO_STATUSTIP
         case QEvent::StyleChange:
 #ifndef QT_NO_DOCKWIDGET
             d->layout->layoutState.dockAreaLayout.styleChangedEvent();
 #endif
             if (!d->explicitIconSize)
                 setIconSize(QSize());
             break;
 #ifdef Q_WS_MAC
         case QEvent::Show:
             d->layout->blockVisiblityCheck = false;
             if (unifiedTitleAndToolBarOnMac())
                 d->layout->syncUnifiedToolbarVisibility();
             break;
        case QEvent::WindowStateChange:
             {
                 if (isHidden()) {
                     // We are coming out of a minimize, leave things as is.
                     d->layout->blockVisiblityCheck = true;
                 }
 #  ifdef QT_MAC_USE_COCOA
                 // We need to update the HIToolbar status when we go out of or into fullscreen.
                 QWindowStateChangeEvent *wce = static_cast<QWindowStateChangeEvent *>(event);
                 if ((windowState() & Qt::WindowFullScreen) || (wce->oldState() & Qt::WindowFullScreen)) {
                     d->layout->updateHIToolBarStatus();
                 }
 #  endif // Cocoa
             }
             break;
 #endif // Q_WS_MAC
 #if !defined(QT_NO_DOCKWIDGET) && !defined(QT_NO_CURSOR)
        case QEvent::CursorChange:
            if (d->cursorAdjusted) {
                d->oldCursor = cursor();
                d->hasOldCursor = testAttribute(Qt::WA_SetCursor);
            }
            break;
 #endif
         default:
             break;
     }
     return QWidget::event(event);
 }
iconSize()
QSize QMainWindow::iconSize () const
Referenced by setDockOptions(), and setIconSize().
iconSizeChanged
void QMainWindow::iconSizeChanged (const QSize & iconSize) signal
This signal is emitted when the size of the icons used in the window is changed.
The new icon size is passed in iconSize.
You can connect this signal to other components to help maintain a consistent appearance for your application.
See also
setIconSize()
Referenced by addToolBar(), insertToolBar(), and setIconSize().
insertToolBar()
void QMainWindow::insertToolBar (QToolBar * before, QToolBar * toolbar)
Inserts the toolbar into the area occupied by the before toolbar so that it appears before it.
For example, in normal left-to-right layout operation, this means that toolbar will appear to the left of the toolbar specified by before in a horizontal toolbar area.
See also
insertToolBarBreak() addToolBar() addToolBarBreak()
Definition at line 837 of file qmainwindow.cpp.
 {
     Q_D(QMainWindow);
     d->layout->removeToolBar(toolbar);
     toolbar->d_func()->_q_updateIconSize(d->iconSize);
     toolbar->d_func()->_q_updateToolButtonStyle(d->toolButtonStyle);
     connect(this, SIGNAL(iconSizeChanged(QSize)),
             toolbar, SLOT(_q_updateIconSize(QSize)));
     connect(this, SIGNAL(toolButtonStyleChanged(Qt::ToolButtonStyle)),
             toolbar, SLOT(_q_updateToolButtonStyle(Qt::ToolButtonStyle)));
     d->layout->insertToolBar(before, toolbar);
 }
insertToolBarBreak()
void QMainWindow::insertToolBarBreak (QToolBar * before)
Inserts a toolbar break before the toolbar specified by before.
Definition at line 743 of file qmainwindow.cpp.
 { d_func()->layout->insertToolBarBreak(before); }
isAnimated()
bool QMainWindow::isAnimated () const
Definition at line 914 of file qmainwindow.cpp.
Referenced by addToolBar().
 {
     Q_D(const QMainWindow);
     return d->layout->dockOptions & AnimatedDocks;
 }
isDockNestingEnabled()
bool QMainWindow::isDockNestingEnabled () const
Definition at line 956 of file qmainwindow.cpp.
 {
     Q_D(const QMainWindow);
     return d->layout->dockOptions & AllowNestedDocks;
 }
isSeparator()
bool QMainWindow::isSeparator (const QPoint & pos) const
Warning
This function is not part of the public interface.
Definition at line 1616 of file qmainwindow.cpp.
 {
 #ifndef QT_NO_DOCKWIDGET
     Q_D(const QMainWindow);
     return !d->layout->layoutState.dockAreaLayout.findSeparator(pos).isEmpty();
 #else
     Q_UNUSED(pos);
     return false;
 #endif
 }
menuBar()
QMenuBar * QMainWindow::menuBar () const
Returns the menu bar for the main window.
This function creates and returns an empty menu bar if the menu bar does not exist.
If you want all windows in a Mac application to share one menu bar, don't use this function to create it, because the menu bar created here will have this QMainWindow as its parent. Instead, you must create a menu bar that does not have a parent, which you can then share among all the Mac windows. Create a parent-less menu bar this way:
QMenuBar *menuBar = new QMenuBar(0);
See also
setMenuBar()
Definition at line 527 of file qmainwindow.cpp.
Referenced by menuWidget(), setMenuBar(), setMenuWidget(), and QScriptEngineDebugger::standardWindow().
 {
     QMenuBar *menuBar = qobject_cast<QMenuBar *>(layout()->menuBar());
     if (!menuBar) {
         QMainWindow *self = const_cast<QMainWindow *>(this);
         menuBar = new QMenuBar(self);
         self->setMenuBar(menuBar);
     }
     return menuBar;
 }
menuWidget()
QWidget * QMainWindow::menuWidget () const
Returns the menu bar for the main window.
Since
4.2
This function returns null if a menu bar hasn't been constructed yet.
Definition at line 578 of file qmainwindow.cpp.
Referenced by QMdiSubWindowPrivate::drawTitleBarWhenMaximized().
 {
     QWidget *menuBar = d_func()->layout->menuBar();
     return menuBar;
 }
removeDockWidget()
void QMainWindow::removeDockWidget (QDockWidget * dockwidget)
Removes the dockwidget from the main window layout and hides it.
Note that the dockwidget is not deleted.
Definition at line 1246 of file qmainwindow.cpp.
 {
     if (dockwidget) {
         d_func()->layout->removeWidget(dockwidget);
         dockwidget->hide();
     }
 }
removeToolBar()
void QMainWindow::removeToolBar (QToolBar * toolbar)
Removes the toolbar from the main window layout and hides it.
Note that the toolbar is not deleted.
Definition at line 857 of file qmainwindow.cpp.
 {
     if (toolbar) {
         d_func()->layout->removeToolBar(toolbar);
         toolbar->hide();
     }
 }
removeToolBarBreak()
void QMainWindow::removeToolBarBreak (QToolBar * before)
Removes a toolbar break previously inserted before the toolbar specified by before.
Definition at line 750 of file qmainwindow.cpp.
 {
     Q_D(QMainWindow);
     d->layout->removeToolBarBreak(before);
 }
restoreDockWidget()
bool QMainWindow::restoreDockWidget (QDockWidget * dockwidget)
Restores the state of dockwidget if it is created after the call to restoreState().
Returns true if the state was restored; otherwise returns false.
See also
restoreState(), saveState()
Definition at line 1149 of file qmainwindow.cpp.
 {
     return d_func()->layout->restoreDockWidget(dockwidget);
 }
restoreState()
bool QMainWindow::restoreState (const QByteArray & state, int version = 0)
Restores the state of this mainwindow's toolbars and dockwidgets.
The version number is compared with that stored in state. If they do not match, the mainwindow's state is left unchanged, and this function returns false; otherwise, the state is restored, and this function returns true.
To restore geometry saved using QSettings, you can use code like this:
void MainWindow::readSettings()
{
    QSettings settings("MyCompany", "MyApp");
    restoreGeometry(settings.value("myWidget/geometry").toByteArray());
    restoreState(settings.value("myWidget/windowState").toByteArray());
}
See also
saveState(), QWidget::saveGeometry(), QWidget::restoreGeometry(), restoreDockWidget()
Definition at line 1310 of file qmainwindow.cpp.
Referenced by QScriptEngineDebugger::standardWindow().
 {
     if (state.isEmpty())
         return false;
     QByteArray sd = state;
     QDataStream stream(&sd, QIODevice::ReadOnly);
     int marker, v;
     stream >> marker;
     stream >> v;
     if (stream.status() != QDataStream::Ok || marker != QMainWindowLayout::VersionMarker || v != version)
         return false;
     bool restored = d_func()->layout->restoreState(stream);
     return restored;
 }
saveState()
QByteArray QMainWindow::saveState (int version = 0) const
Saves the current state of this mainwindow's toolbars and dockwidgets.
The version number is stored as part of the data.
The objectName property is used to identify each QToolBar and QDockWidget. You should make sure that this property is unique for each QToolBar and QDockWidget you add to the QMainWindow
To restore the saved state, pass the return value and version number to restoreState().
To save the geometry when the window closes, you can implement a close event like this:
void MyMainWindow::closeEvent(QCloseEvent *event)
{
    QSettings settings("MyCompany", "MyApp");
    settings.setValue("geometry", saveGeometry());
    settings.setValue("windowState", saveState());
    QMainWindow::closeEvent(event);
}
See also
restoreState(), QWidget::saveGeometry(), QWidget::restoreGeometry()
Definition at line 1285 of file qmainwindow.cpp.
 {
     QByteArray data;
     QDataStream stream(&data, QIODevice::WriteOnly);
     stream << QMainWindowLayout::VersionMarker;
     stream << version;
     d_func()->layout->saveState(stream);
     return data;
 }
setAnimated
void QMainWindow::setAnimated (bool enabled) slot
Definition at line 920 of file qmainwindow.cpp.
Referenced by addToolBar().
 {
     Q_D(QMainWindow);
     DockOptions opts = d->layout->dockOptions;
     if (enabled)
         opts |= AnimatedDocks;
     else
         opts &= ~AnimatedDocks;
     d->layout->setDockOptions(opts);
 }
setCentralWidget()
void QMainWindow::setCentralWidget (QWidget * widget)
Sets the given widget to be the main window's central widget.
Note: QMainWindow takes ownership of the widget pointer and deletes it at the appropriate time.
See also
centralWidget()
Definition at line 662 of file qmainwindow.cpp.
Referenced by QScriptEngineDebugger::standardWindow().
 {
     Q_D(QMainWindow);
     if (d->layout->centralWidget() && d->layout->centralWidget() != widget) {
         d->layout->centralWidget()->hide();
         d->layout->centralWidget()->deleteLater();
     }
     d->layout->setCentralWidget(widget);
 }
setCorner()
void QMainWindow::setCorner (Qt::Corner corner, Qt::DockWidgetArea area)
Sets the given dock widget area to occupy the specified corner.
See also
corner()
Definition at line 679 of file qmainwindow.cpp.
 {
     bool valid = false;
     switch (corner) {
     case Qt::TopLeftCorner:
         valid = (area == Qt::TopDockWidgetArea || area == Qt::LeftDockWidgetArea);
         break;
     case Qt::TopRightCorner:
         valid = (area == Qt::TopDockWidgetArea || area == Qt::RightDockWidgetArea);
         break;
     case Qt::BottomLeftCorner:
         valid = (area == Qt::BottomDockWidgetArea || area == Qt::LeftDockWidgetArea);
         break;
     case Qt::BottomRightCorner:
         valid = (area == Qt::BottomDockWidgetArea || area == Qt::RightDockWidgetArea);
         break;
     }
     if (!valid)
         qWarning("QMainWindow::setCorner(): 'area' is not valid for 'corner'");
     else
         d_func()->layout->setCorner(corner, area);
 }
setDockNestingEnabled
void QMainWindow::setDockNestingEnabled (bool enabled) slot
Definition at line 962 of file qmainwindow.cpp.
 {
     Q_D(QMainWindow);
     DockOptions opts = d->layout->dockOptions;
     if (enabled)
         opts |= AllowNestedDocks;
     else
         opts &= ~AllowNestedDocks;
     d->layout->setDockOptions(opts);
 }
setDockOptions()
void QMainWindow::setDockOptions (DockOptions options)
Definition at line 460 of file qmainwindow.cpp.
 {
     Q_D(QMainWindow);
     d->layout->setDockOptions(opt);
 }
setDocumentMode()
void QMainWindow::setDocumentMode (bool enabled)
Definition at line 1036 of file qmainwindow.cpp.
 {
     d_func()->layout->setDocumentMode(enabled);
 }
setIconSize()
void QMainWindow::setIconSize (const QSize & iconSize)
Definition at line 475 of file qmainwindow.cpp.
Referenced by event().
 {
     Q_D(QMainWindow);
     QSize sz = iconSize;
     if (!sz.isValid()) {
         const int metric = style()->pixelMetric(QStyle::PM_ToolBarIconSize, 0, this);
         sz = QSize(metric, metric);
     }
     if (d->iconSize != sz) {
         d->iconSize = sz;
         emit iconSizeChanged(d->iconSize);
     }
     d->explicitIconSize = iconSize.isValid();
 }
setMenuBar()
void QMainWindow::setMenuBar (QMenuBar * menuBar)
Sets the menu bar for the main window to menuBar.
Note: QMainWindow takes ownership of the menuBar pointer and deletes it at the appropriate time.
See also
menuBar()
Definition at line 546 of file qmainwindow.cpp.
 {
     QLayout *topLayout = layout();
     if (topLayout->menuBar() && topLayout->menuBar() != menuBar) {
         // Reparent corner widgets before we delete the old menu bar.
         QMenuBar *oldMenuBar = qobject_cast<QMenuBar *>(topLayout->menuBar());
         if (menuBar) {
             // TopLeftCorner widget.
             QWidget *cornerWidget = oldMenuBar->cornerWidget(Qt::TopLeftCorner);
             if (cornerWidget)
                 menuBar->setCornerWidget(cornerWidget, Qt::TopLeftCorner);
             // TopRightCorner widget.
             cornerWidget = oldMenuBar->cornerWidget(Qt::TopRightCorner);
             if (cornerWidget)
                 menuBar->setCornerWidget(cornerWidget, Qt::TopRightCorner);
         }
         oldMenuBar->hide();
         oldMenuBar->deleteLater();
     }
     topLayout->setMenuBar(menuBar);
 }
setMenuWidget()
void QMainWindow::setMenuWidget (QWidget * menuBar)
Sets the menu bar for the main window to menuBar.
Since
4.2
QMainWindow takes ownership of the menuBar pointer and deletes it at the appropriate time.
Definition at line 595 of file qmainwindow.cpp.
 {
     Q_D(QMainWindow);
     if (d->layout->menuBar() && d->layout->menuBar() != menuBar) {
         d->layout->menuBar()->hide();
         d->layout->menuBar()->deleteLater();
     }
     d->layout->setMenuBar(menuBar);
 }
setStatusBar()
void QMainWindow::setStatusBar (QStatusBar * statusbar)
Sets the status bar for the main window to statusbar.
Setting the status bar to 0 will remove it from the main window. Note that QMainWindow takes ownership of the statusbar pointer and deletes it at the appropriate time.
See also
statusBar()
Definition at line 634 of file qmainwindow.cpp.
 {
     Q_D(QMainWindow);
     if (d->layout->statusBar() && d->layout->statusBar() != statusbar) {
         d->layout->statusBar()->hide();
         d->layout->statusBar()->deleteLater();
     }
     d->layout->setStatusBar(statusbar);
 }
setTabPosition()
void QMainWindow::setTabPosition (Qt::DockWidgetAreas areas, QTabWidget::TabPosition tabPosition)
Sets the tab position for the given dock widget areas to the specified tabPosition.
Since
4.5
By default, all dock areas show their tabs at the bottom.
Note
The VerticalTabs dock option overrides the tab positions set by this method.
See also
tabPosition(), setTabShape()
Definition at line 1099 of file qmainwindow.cpp.
 {
     d_func()->layout->setTabPosition(areas, tabPosition);
 }
setTabShape()
void QMainWindow::setTabShape (QTabWidget::TabShape tabShape)
Definition at line 1060 of file qmainwindow.cpp.
 {
     d_func()->layout->setTabShape(tabShape);
 }
setToolButtonStyle()
void QMainWindow::setToolButtonStyle (Qt::ToolButtonStyle toolButtonStyle)
Definition at line 502 of file qmainwindow.cpp.
 {
     Q_D(QMainWindow);
     if (d->toolButtonStyle == toolButtonStyle)
         return;
     d->toolButtonStyle = toolButtonStyle;
     emit toolButtonStyleChanged(d->toolButtonStyle);
 }
setUnifiedTitleAndToolBarOnMac()
void QMainWindow::setUnifiedTitleAndToolBarOnMac (bool set)
Definition at line 1567 of file qmainwindow.cpp.
Referenced by QWidget::showFullScreen(), QWidget::showMaximized(), QWidget::showNormal(), and QScriptEngineDebugger::standardWindow().
 {
 #ifdef Q_WS_MAC
     Q_D(QMainWindow);
     if (!isWindow() || d->useHIToolBar == set || QSysInfo::MacintoshVersion < QSysInfo::MV_10_3)
         return;
     d->useHIToolBar = set;
     createWinId(); // We need the hiview for down below.
 #ifdef QT_MAC_USE_COCOA
     // Activate the unified toolbar with the raster engine.
     if (windowSurface() && set) {
         d->layout->unifiedSurface = new QUnifiedToolbarSurface(this);
     }
 #endif // QT_MAC_USE_COCOA
     d->layout->updateHIToolBarStatus();
 #ifdef QT_MAC_USE_COCOA
     // Deactivate the unified toolbar with the raster engine.
     if (windowSurface() && !set) {
         if (d->layout->unifiedSurface) {
             delete d->layout->unifiedSurface;
             d->layout->unifiedSurface = 0;
         }
     }
 #endif // QT_MAC_USE_COCOA
     // Enabling the unified toolbar clears the opaque size grip setting, update it.
     d->macUpdateOpaqueSizeGrip();
 #else
     Q_UNUSED(set)
 #endif
 }
splitDockWidget()
void QMainWindow::splitDockWidget (QDockWidget * first, QDockWidget * second, Qt::Orientation orientation)
Splits the space covered by the first dock widget into two parts, moves the first dock widget into the first part, and moves the second dock widget into the second part.
The orientation specifies how the space is divided: A Qt::Horizontal split places the second dock widget to the right of the first; a Qt::Vertical split places the second dock widget below the first.
Note: if first is currently in a tabbed docked area, second will be added as a new tab, not as a neighbor of first. This is because a single tab can contain only one dock widget.
Note: The Qt::LayoutDirection influences the order of the dock widgets in the two parts of the divided area. When right-to-left layout direction is enabled, the placing of the dock widgets will be reversed.
See also
tabifyDockWidget(), addDockWidget(), removeDockWidget()
Definition at line 1189 of file qmainwindow.cpp.
 {
     d_func()->layout->splitDockWidget(after, dockwidget, orientation);
 }
statusBar()
QStatusBar * QMainWindow::statusBar () const
Returns the status bar for the main window.
This function creates and returns an empty status bar if the status bar does not exist.
See also
setStatusBar()
Definition at line 613 of file qmainwindow.cpp.
 {
     QStatusBar *statusbar = d_func()->layout->statusBar();
     if (!statusbar) {
         QMainWindow *self = const_cast<QMainWindow *>(this);
         statusbar = new QStatusBar(self);
         statusbar->setSizePolicy(QSizePolicy::Ignored, QSizePolicy::Fixed);
         self->setStatusBar(statusbar);
     }
     return statusbar;
 }
tabifiedDockWidgets()
QList< QDockWidget * > QMainWindow::tabifiedDockWidgets (QDockWidget * dockwidget) const
Returns the dock widgets that are tabified together with dockwidget.
Since
4.5
See also
tabifyDockWidget()
Definition at line 1218 of file qmainwindow.cpp.
 {
     QList<QDockWidget*> ret;
 #if defined(QT_NO_TABBAR)
     Q_UNUSED(dockwidget);
 #else
     const QDockAreaLayoutInfo *info = d_func()->layout->layoutState.dockAreaLayout.info(dockwidget);
     if (info && info->tabbed && info->tabBar) {
         for(int i = 0; i < info->item_list.count(); ++i) {
             const QDockAreaLayoutItem &item = info->item_list.at(i);
             if (item.widgetItem) {
                 if (QDockWidget *dock = qobject_cast<QDockWidget*>(item.widgetItem->widget())) {
                     if (dock != dockwidget) {
                         ret += dock;
                     }
                 }
             }
         }
     }
 #endif
     return ret;
 }
tabifyDockWidget()
void QMainWindow::tabifyDockWidget (QDockWidget * first, QDockWidget * second)
Moves second dock widget on top of first dock widget, creating a tabbed docked area in the main window.
See also
tabifiedDockWidgets()
Definition at line 1203 of file qmainwindow.cpp.
Referenced by QScriptEngineDebugger::standardWindow().
 {
     d_func()->layout->tabifyDockWidget(first, second);
 }
tabPosition()
QTabWidget::TabPosition QMainWindow::tabPosition (Qt::DockWidgetArea area) const
Returns the tab position for area.
Since
4.5
Note
The VerticalTabs dock option overrides the tab positions returned by this function.
See also
setTabPosition(), tabShape()
Definition at line 1078 of file qmainwindow.cpp.
 {
     if (!checkDockWidgetArea(area, "QMainWindow::tabPosition"))
         return QTabWidget::South;
     return d_func()->layout->tabPosition(area);
 }
tabShape()
QTabWidget::TabShape QMainWindow::tabShape () const
Referenced by setDocumentMode().
toolBarArea()
Qt::ToolBarArea QMainWindow::toolBarArea (QToolBar * toolbar) const
Returns the Qt::ToolBarArea for toolbar.
If toolbar has not been added to the main window, this function returns Qt::NoToolBarArea.
See also
addToolBar() addToolBarBreak() Qt::ToolBarArea
Definition at line 872 of file qmainwindow.cpp.
Referenced by createPopupMenu(), and toolbarInUnifiedToolBar().
 { return d_func()->layout->toolBarArea(toolbar); }
toolBarBreak()
bool QMainWindow::toolBarBreak (QToolBar * toolbar) const
Returns whether there is a toolbar break before the toolbar.
See also
addToolBarBreak(), insertToolBarBreak()
Definition at line 882 of file qmainwindow.cpp.
 {
     return d_func()->layout->toolBarBreak(toolbar);
 }
toolButtonStyle()
Qt::ToolButtonStyle QMainWindow::toolButtonStyle () const
Referenced by setIconSize(), and setToolButtonStyle().
toolButtonStyleChanged
void QMainWindow::toolButtonStyleChanged (Qt::ToolButtonStyle toolButtonStyle) signal
This signal is emitted when the style used for tool buttons in the window is changed.
The new style is passed in toolButtonStyle.
You can connect this signal to other components to help maintain a consistent appearance for your application.
See also
setToolButtonStyle()
Referenced by addToolBar(), insertToolBar(), and setToolButtonStyle().
unifiedTitleAndToolBarOnMac()
bool QMainWindow::unifiedTitleAndToolBarOnMac () const
Referenced by createPopupMenu(), event(), and setUnifiedTitleAndToolBarOnMac().
Properties
animated
QMainWindow::animated private
whether manipulating dock widgets and tool bars is animated
Since
4.2
When a dock widget or tool bar is dragged over the main window, the main window adjusts its contents to indicate where the dock widget or tool bar will be docked if it is dropped. Setting this property causes QMainWindow to move its contents in a smooth animation. Clearing this property causes the contents to snap into their new positions.
By default, this property is set. It may be cleared if the main window contains widgets which are slow at resizing or repainting themselves.
Setting this property is identical to setting the AnimatedDocks option using setDockOptions().
Definition at line 72 of file qmainwindow.h.
Referenced by addToolBar().
dockNestingEnabled
QMainWindow::dockNestingEnabled private
whether docks can be nested
Since
4.2
If this property is false, dock areas can only contain a single row (horizontal or vertical) of dock widgets. If this property is true, the area occupied by a dock widget can be split in either direction to contain more dock widgets.
Dock nesting is only necessary in applications that contain a lot of dock widgets. It gives the user greater freedom in organizing their main window. However, dock nesting leads to more complex (and less intuitive) behavior when a dock widget is dragged over the main window, since there are more ways in which a dropped dock widget may be placed in the dock area.
Setting this property is identical to setting the AllowNestedDocks option using setDockOptions().
Definition at line 79 of file qmainwindow.h.
dockOptions
QMainWindow::DockOptions QMainWindow::dockOptions private
the docking behavior of QMainWindow
Since
4.3
The default value is AnimatedDocks | AllowTabbedDocks.
Definition at line 81 of file qmainwindow.h.
Referenced by QDockAreaLayout::gapIndex().
documentMode
bool QMainWindow::documentMode private
whether the tab bar for tabbed dockwidgets is set to document mode.
Since
4.5
The default is false.
See also
QTabBar::documentMode
Definition at line 74 of file qmainwindow.h.
iconSize
QSize QMainWindow::iconSize private
size of toolbar icons in this mainwindow.
The default is the default tool bar icon size of the GUI style. Note that the icons used must be at least of this size as the icons are only scaled down.
Definition at line 69 of file qmainwindow.h.
Referenced by QToolBar::setIconSize().
tabShape
QTabWidget::TabShape QMainWindow::tabShape private
the tab shape used for tabbed dock widgets.
Since
4.5
The default is QTabWidget::Rounded .
See also
setTabPosition()
Definition at line 77 of file qmainwindow.h.
toolButtonStyle
Qt::ToolButtonStyle QMainWindow::toolButtonStyle private
style of toolbar buttons in this mainwindow.
The default is Qt::ToolButtonIconOnly.
Definition at line 70 of file qmainwindow.h.
unifiedTitleAndToolBarOnMac
bool QMainWindow::unifiedTitleAndToolBarOnMac private
whether the window uses the unified title and toolbar look on Mac OS X
Since
4.3
This property is false by default and only has any effect on Mac OS X 10.4 or higher.
If set to true, then the top toolbar area is replaced with a Carbon HIToolbar or a Cocoa NSToolbar (depending on whether Qt was built with Carbon or Cocoa). All toolbars in the top toolbar area and any toolbars added afterwards are moved to that. This means a couple of things.
QToolBars in this toolbar area are not movable and you cannot drag other toolbars to it
Toolbar breaks are not respected or preserved
Any custom widgets in the toolbar will not be shown if the toolbar becomes too small (only actions will be shown)
Before Qt 4.5, if you called showFullScreen() on the main window, the QToolbar would disappear since it is considered to be part of the title bar. Qt 4.5 and up will now work around this by pulling the toolbars out and back into the regular toolbar and vice versa when you swap out.
Setting this back to false will remove these restrictions.
The Qt::WA_MacBrushedMetal attribute takes precedence over this property.
Definition at line 83 of file qmainwindow.h.
Referenced by QToolBar::allowedAreas(), QWidgetPrivate::childAt_helper(), QMacStyle::drawControl(), QToolBarAreaLayout::fitLayout(), qt_mac_unregister_widget(), QToolBarAreaLayout::restoreState(), QWidget::showFullScreen(), toolbarInUnifiedToolBar(), and QMainWindowLayout::usesHIToolBar().
The documentation for this class was generated from the following files:
/src/gui/widgets/qmainwindow.h
/src/gui/widgets/qmainwindow.cpp