Qt 4.8: QSvgRenderer Class Reference
QSvgRenderer Class Reference
The QSvgRenderer class is used to draw the contents of SVG files onto paint devices.
#include <qsvgrenderer.h>
Public Slots
bool load (const QString &filename)
Loads the SVG file specified by filename, returning true if the content was successfully parsed; otherwise returns false.
bool load (const QByteArray &contents)
Loads the specified SVG format contents, returning true if the content was successfully parsed; otherwise returns false.
bool load (QXmlStreamReader *contents)
Loads the specified SVG in contents, returning true if the content was successfully parsed; otherwise returns false.
void render (QPainter *p)
Renders the current document, or the current frame of an animated document, using the given painter.
void render (QPainter *p, const QRectF &bounds)
Renders the current document, or the current frame of an animated document, using the given painter on the specified bounds within the painter.
void render (QPainter *p, const QString &elementId, const QRectF &bounds=QRectF())
Renders the given element with elementId using the given painter on the specified bounds.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void repaintNeeded ()
This signal is emitted whenever the rendering of the document needs to be updated, usually for the purposes of animation.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool animated () const
Returns true if the current document contains animated elements; otherwise returns false.
int animationDuration () const
Returns the number of frames in the animation, or 0 if the current document is not animated.
QRectF boundsOnElement (const QString &id) const
Returns bounding rectangle of the item with the given id.
int currentFrame () const
QSize defaultSize () const
Returns the default size of the document contents.
bool elementExists (const QString &id) const
Returns true if the element with the given id exists in the currently parsed SVG file and is a renderable element.
int framesPerSecond () const
bool isValid () const
Returns true if there is a valid current document; otherwise returns false.
QMatrix matrixForElement (const QString &id) const
Returns the transformation matrix for the element with the given id.
QSvgRenderer (QObject *parent=0)
Constructs a new renderer with the given parent.
QSvgRenderer (const QString &filename, QObject *parent=0)
Constructs a new renderer with the given parent and loads the contents of the SVG file with the specified filename.
QSvgRenderer (const QByteArray &contents, QObject *parent=0)
Constructs a new renderer with the given parent and loads the SVG data from the byte array specified by contents.
QSvgRenderer (QXmlStreamReader *contents, QObject *parent=0)
Constructs a new renderer with the given parent and loads the SVG data using the stream reader specified by contents.
void setCurrentFrame (int)
void setFramesPerSecond (int num)
void setViewBox (const QRect &viewbox)
void setViewBox (const QRectF &viewbox)
QRect viewBox () const
QRectF viewBoxF () const
~QSvgRenderer ()
Destroys the renderer.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
int currentFrame
the current frame of the document's animation, or 0 if the document is not animated
int framesPerSecond
the number of frames per second to be shown
QRectF viewBox
Returns viewBoxF().toRect().
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSvgRenderer class is used to draw the contents of SVG files onto paint devices.
Since
4.1
Note
This class or function is reentrant.
Using QSvgRenderer, Scalable Vector Graphics (SVG) can be rendered onto any QPaintDevice subclass, including QWidget, QImage, and QGLWidget.
QSvgRenderer provides an API that supports basic features of SVG rendering, such as loading and rendering of static drawings, and more interactive features like animation. Since the rendering is performed using QPainter, SVG drawings can be rendered on any subclass of QPaintDevice.
SVG drawings are either loaded when an QSvgRenderer is constructed, or loaded later using the load() functions. Data is either supplied directly as serialized XML, or indirectly using a file name. If a valid file has been loaded, either when the renderer is constructed or at some later time, isValid() returns true; otherwise it returns false. QSvgRenderer provides the render() slot to render the current document, or the current frame of an animated document, using a given painter.
The defaultSize() function provides information about the amount of space that is required to render the currently loaded SVG file. This is useful for paint devices, such as QWidget, that often need to supply a size hint to their parent layout. The default size of a drawing may differ from its visible area, found using the viewBox property.
Animated SVG drawings are supported, and can be controlled with a simple collection of functions and properties:
The animated() function indicates whether a drawing contains animation information.
Warning
This function is not part of the public interface.
The animationDuration() function provides the duration in milliseconds of the animation, without taking any looping into account.
The currentFrame property contains the current frame of the animation.
The framesPerSecond property contains the rate at which the animation plays.
Finally, the QSvgRenderer class provides the repaintNeeded() signal which is emitted whenever the rendering of the document needs to be updated.
See also
QSvgWidget, {QtSvg Module}, {SVG Viewer Example}, QPicture
Definition at line 64 of file qsvgrenderer.h.
Constructors and Destructors
QSvgRenderer() [1/4]
QSvgRenderer::QSvgRenderer (QObject * parent = 0)
Constructs a new renderer with the given parent.
Definition at line 131 of file qsvgrenderer.cpp.
     : QObject(*(new QSvgRendererPrivate), parent)
 {
 }
QSvgRenderer() [2/4]
QSvgRenderer::QSvgRenderer (const QString & filename, QObject * parent = 0)
Constructs a new renderer with the given parent and loads the contents of the SVG file with the specified filename.
Definition at line 140 of file qsvgrenderer.cpp.
     : QObject(*new QSvgRendererPrivate, parent)
 {
     load(filename);
 }
QSvgRenderer() [3/4]
QSvgRenderer::QSvgRenderer (const QByteArray & contents, QObject * parent = 0)
Constructs a new renderer with the given parent and loads the SVG data from the byte array specified by contents.
Definition at line 150 of file qsvgrenderer.cpp.
     : QObject(*new QSvgRendererPrivate, parent)
 {
     load(contents);
 }
QSvgRenderer() [4/4]
QSvgRenderer::QSvgRenderer (QXmlStreamReader * contents, QObject * parent = 0)
Constructs a new renderer with the given parent and loads the SVG data using the stream reader specified by contents.
Since
4.5
Definition at line 165 of file qsvgrenderer.cpp.
     : QObject(*new QSvgRendererPrivate, parent)
 {
     load(contents);
 }
~QSvgRenderer()
QSvgRenderer::~QSvgRenderer ()
Destroys the renderer.
Definition at line 174 of file qsvgrenderer.cpp.
 {
 }
Functions
animated()
bool QSvgRenderer::animated () const
Returns true if the current document contains animated elements; otherwise returns false.
See also
framesPerSecond()
Definition at line 235 of file qsvgrenderer.cpp.
 {
     Q_D(const QSvgRenderer);
     if (d->render)
         return d->render->animated();
     else
         return false;
 }
animationDuration()
int QSvgRenderer::animationDuration () const
Returns the number of frames in the animation, or 0 if the current document is not animated.
Warning
This function is not part of the public interface.
See also
animated(), framesPerSecond
Definition at line 311 of file qsvgrenderer.cpp.
 {
     Q_D(const QSvgRenderer);
     return d->render->animationDuration();
 }
boundsOnElement()
QRectF QSvgRenderer::boundsOnElement (const QString & id) const
Returns bounding rectangle of the item with the given id.
Since
4.2
The transformation matrix of parent elements is not affecting the bounds of the element.
See also
matrixForElement()
Definition at line 467 of file qsvgrenderer.cpp.
Referenced by QGraphicsSvgItemPrivate::updateDefaultSize().
 {
     Q_D(const QSvgRenderer);
     QRectF bounds;
     if (d->render)
         bounds = d->render->boundsOnElement(id);
     return bounds;
 }
currentFrame()
int QSvgRenderer::currentFrame () const
Referenced by setFramesPerSecond().
defaultSize()
QSize QSvgRenderer::defaultSize () const
Returns the default size of the document contents.
Definition at line 191 of file qsvgrenderer.cpp.
Referenced by QSvgIconEngine::pixmap(), and QGraphicsSvgItemPrivate::updateDefaultSize().
 {
     Q_D(const QSvgRenderer);
     if (d->render)
         return d->render->size();
     else
         return QSize();
 }
elementExists()
bool QSvgRenderer::elementExists (const QString & id) const
Returns true if the element with the given id exists in the currently parsed SVG file and is a renderable element.
Since
4.2
Note: this method returns true only for elements that can be rendered. Which implies that elements that are considered part of the fill/stroke style properties, e.g. radialGradients even tough marked with "id" attributes will not be found by this method.
Definition at line 493 of file qsvgrenderer.cpp.
 {
     Q_D(const QSvgRenderer);
     bool exists = false;
     if (d->render)
         exists = d->render->elementExists(id);
     return exists;
 }
framesPerSecond()
int QSvgRenderer::framesPerSecond () const
Referenced by animated().
isValid()
bool QSvgRenderer::isValid () const
Returns true if there is a valid current document; otherwise returns false.
Definition at line 182 of file qsvgrenderer.cpp.
Referenced by QSvgIconEngine::addFile(), and QSvgIconEngine::pixmap().
 {
     Q_D(const QSvgRenderer);
     return d->render;
 }
load [1/3]
bool QSvgRenderer::load (const QString & filename) slot
Loads the SVG file specified by filename, returning true if the content was successfully parsed; otherwise returns false.
Definition at line 358 of file qsvgrenderer.cpp.
Referenced by QSvgIOHandlerPrivate::load(), QSvgIconEnginePrivate::loadDataForModeAndState(), and QSvgRenderer().
 {
     Q_D(QSvgRenderer);
     return loadDocument(this, d, filename);
 }
load [2/3]
bool QSvgRenderer::load (const QByteArray & contents) slot
Loads the specified SVG format contents, returning true if the content was successfully parsed; otherwise returns false.
Definition at line 368 of file qsvgrenderer.cpp.
 {
     Q_D(QSvgRenderer);
     return loadDocument(this, d, contents);
 }
load [3/3]
bool QSvgRenderer::load (QXmlStreamReader * contents) slot
Loads the specified SVG in contents, returning true if the content was successfully parsed; otherwise returns false.
The reader will be used from where it currently is positioned. If contents is null, behavior is undefined.
Since
4.5
Definition at line 383 of file qsvgrenderer.cpp.
 {
     Q_D(QSvgRenderer);
     return loadDocument(this, d, contents);
 }
matrixForElement()
QMatrix QSvgRenderer::matrixForElement (const QString & id) const
Returns the transformation matrix for the element with the given id.
Since
4.2
The matrix is a product of the transformation of the element's parents. The transformation of the element itself is not included.
To find the bounding rectangle of the element in logical coordinates, you can apply the matrix on the rectangle returned from boundsOnElement().
See also
boundsOnElement()
Definition at line 518 of file qsvgrenderer.cpp.
 {
     Q_D(const QSvgRenderer);
     QMatrix mat;
     if (d->render)
         mat = d->render->matrixForElement(id);
     return mat;
 }
render [1/3]
void QSvgRenderer::render (QPainter * p) slot
Renders the current document, or the current frame of an animated document, using the given painter.
Definition at line 393 of file qsvgrenderer.cpp.
Referenced by QSvgIconEngine::pixmap(), and QSvgIOHandler::read().
 {
     Q_D(QSvgRenderer);
     if (d->render) {
         d->render->draw(painter);
     }
 }
render [2/3]
void QSvgRenderer::render (QPainter * painter, const QRectF & bounds) slot
Renders the current document, or the current frame of an animated document, using the given painter on the specified bounds within the painter.
If the bounding rectangle is not specified the SVG file is mapped to the whole paint device.
Definition at line 431 of file qsvgrenderer.cpp.
 {
     Q_D(QSvgRenderer);
     if (d->render) {
         d->render->draw(painter, bounds);
     }
 }
render [3/3]
void QSvgRenderer::render (QPainter * painter, const QString & elementId, const QRectF & bounds = QRectF()) slot
Renders the given element with elementId using the given painter on the specified bounds.
If the bounding rectangle is not specified the SVG element is mapped to the whole paint device.
Definition at line 416 of file qsvgrenderer.cpp.
 {
     Q_D(QSvgRenderer);
     if (d->render) {
         d->render->draw(painter, elementId, bounds);
     }
 }
repaintNeeded
void QSvgRenderer::repaintNeeded () signal
This signal is emitted whenever the rendering of the document needs to be updated, usually for the purposes of animation.
Referenced by QSvgRendererPrivate::callRepaintNeeded(), and loadDocument().
setCurrentFrame()
void QSvgRenderer::setCurrentFrame (int frame)
Warning
This function is not part of the public interface.
Definition at line 294 of file qsvgrenderer.cpp.
 {
     Q_D(QSvgRenderer);
     d->render->setCurrentFrame(frame);
 }
setFramesPerSecond()
void QSvgRenderer::setFramesPerSecond (int num)
Definition at line 261 of file qsvgrenderer.cpp.
 {
     Q_D(QSvgRenderer);
     if (num < 0) {
         qWarning("QSvgRenderer::setFramesPerSecond: Cannot set negative value %d", num);
         return;
     }
     d->fps = num;
 }
setViewBox() [1/2]
void QSvgRenderer::setViewBox (const QRect & viewbox)
Definition at line 222 of file qsvgrenderer.cpp.
 {
     Q_D(QSvgRenderer);
     if (d->render)
         d->render->setViewBox(viewbox);
 }
setViewBox() [2/2]
void QSvgRenderer::setViewBox (const QRectF & viewbox)
Definition at line 448 of file qsvgrenderer.cpp.
 {
     Q_D(QSvgRenderer);
     if (d->render)
         d->render->setViewBox(viewbox);
 }
viewBox()
QRect QSvgRenderer::viewBox () const
Referenced by defaultSize().
viewBoxF()
QRectF QSvgRenderer::viewBoxF () const
Definition at line 439 of file qsvgrenderer.cpp.
 {
     Q_D(const QSvgRenderer);
     if (d->render)
         return d->render->viewBox();
     else
         return QRect();
 }
Properties
currentFrame
int QSvgRenderer::currentFrame private
the current frame of the document's animation, or 0 if the document is not animated
Warning
This function is not part of the public interface.
See also
animationDuration(), framesPerSecond, animated()
Warning
This function is not part of the public interface.
Definition at line 70 of file qsvgrenderer.h.
framesPerSecond
int QSvgRenderer::framesPerSecond private
the number of frames per second to be shown
The number of frames per second is 0 if the current document is not animated.
See also
animated()
Definition at line 69 of file qsvgrenderer.h.
viewBox
QSvgRenderer::viewBox private
Returns viewBoxF().toRect().
the rectangle specifying the visible area of the document in logical coordinates
See also
viewBoxF()
Since
4.2
Definition at line 68 of file qsvgrenderer.h.
Referenced by QSvgIOHandlerPrivate::load().
The documentation for this class was generated from the following files:
/src/svg/qsvgrenderer.h
/src/svg/qsvgrenderer.cpp