Qt 4.8: QJSDebuggerAgentPrivate Class Reference
QJSDebuggerAgentPrivate Class Reference
Public Functions
void continueExec ()
QScriptEngine * engine ()
QList< JSAgentWatchData > getLocals (QScriptContext *)
void positionChange (qint64 scriptId, int lineNumber, int columnNumber)
QJSDebuggerAgentPrivate (QJSDebuggerAgent *q)
void recordKnownObjects (const QList< JSAgentWatchData > &)
void stopped ()
Public Variables
JSAgentBreakpoints breakpoints
bool coverageEnabled
QHash< qint64, QString > filenames
QHash< QString, JSAgentBreakpointData > fileNameToBreakpoints
bool isInitialized
QSet< qint64 > knownObjectIds
QEventLoop loop
QJSDebuggerAgent * q
JSDebuggerState state
int stepCount
int stepDepth
QStringList watchExpressions
Detailed Description
Definition at line 56 of file qjsdebuggeragent.cpp.
Constructors and Destructors
QJSDebuggerAgentPrivate()
QJSDebuggerAgentPrivate::QJSDebuggerAgentPrivate (QJSDebuggerAgent * q) inline
Definition at line 59 of file qjsdebuggeragent.cpp.
         : q(q), state(NoState), isInitialized(false), coverageEnabled(false)
     {}
Functions
continueExec()
void QJSDebuggerAgentPrivate::continueExec ()
Definition at line 609 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::continueExecution(), QJSDebuggerAgentPrivate(), QJSDebuggerAgent::stepInto(), QJSDebuggerAgent::stepOut(), and QJSDebuggerAgent::stepOver().
 {
     loop.quit();
 }
engine()
QScriptEngine* QJSDebuggerAgentPrivate::engine () inline
Definition at line 67 of file qjsdebuggeragent.cpp.
Referenced by getLocals(), and QJSDebugService::statusChanged().
 { return q->engine(); }
getLocals()
QList< JSAgentWatchData > QJSDebuggerAgentPrivate::getLocals (QScriptContext * ctx)
Definition at line 211 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::locals(), QJSDebuggerAgent::localsAtFrame(), and QJSDebuggerAgentPrivate().
 {
     QList<JSAgentWatchData> locals;
     if (ctx) {
         QScriptValue activationObject = ctx->activationObject();
         QScriptValue thisObject = ctx->thisObject();
         locals = expandObject(activationObject);
         if (thisObject.isObject()
                 && thisObject.objectId() != engine()->globalObject().objectId()
                 && QScriptValueIterator(thisObject).hasNext())
             locals.prepend(fromScriptValue(QLatin1String("this"), thisObject));
         recordKnownObjects(locals);
         knownObjectIds << activationObject.objectId();
     }
     return locals;
 }
positionChange()
void QJSDebuggerAgentPrivate::positionChange (qint64 scriptId, int lineNumber, int columnNumber)
Definition at line 505 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::positionChange(), and QJSDebuggerAgentPrivate().
 {
     Q_UNUSED(columnNumber);
     if (state == StoppedState)
         return; //no re-entrency
     // check breakpoints
     if (!breakpoints.isEmpty()) {
         const QScriptContext *ctx = engine()->currentContext();
         const QScriptContextInfo info(ctx);
         if (info.functionType() == QScriptContextInfo::ScriptFunction) {
             QHash<qint64, QString>::const_iterator it = filenames.constFind(scriptId);
             // It is possible that the scripts are loaded before the agent is attached
             if (it == filenames.constEnd()) {
                 it = filenames.insert(scriptId, info.fileName());
             }
             const QString filePath = it.value();
             const JSAgentBreakpoints bps = fileNameToBreakpoints.values(fileName(filePath)).toSet();
             foreach (const JSAgentBreakpointData &bp, bps) {
                 if (bp.lineNumber == lineNumber) {
                     stopped();
                     return;
                 }
             }
         }
     }
     switch (state) {
     case NoState:
     case StoppedState:
         // Do nothing
         break;
     case SteppingOutState:
         if (stepDepth >= 0)
             break;
         //fallthough
     case SteppingOverState:
         if (stepDepth > 0)
             break;
         //fallthough
     case SteppingIntoState:
         stopped();
         break;
     }
 }
recordKnownObjects()
void QJSDebuggerAgentPrivate::recordKnownObjects (const QList< JSAgentWatchData > & list)
Definition at line 205 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::expandObjectById(), getLocals(), QJSDebuggerAgentPrivate(), and QJSDebuggerAgent::watches().
 {
     foreach (const JSAgentWatchData &data, list)
         knownObjectIds << data.objectId;
 }
stopped()
void QJSDebuggerAgentPrivate::stopped ()
Definition at line 596 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::addEngine(), engine(), QJSDebuggerAgent::extension(), and QJSDebugService::statusChanged().
 {
     bool becauseOfException = false;
     const QScriptValue &exception = QScriptValue();
     knownObjectIds.clear();
     state = StoppedState;
     emit q->stopped(becauseOfException, exception.toString());
     loop.exec(QEventLoop::ExcludeUserInputEvents);
 }
Properties
breakpoints
JSAgentBreakpoints QJSDebuggerAgentPrivate::breakpoints
Definition at line 78 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived(), and QJSDebuggerAgent::setBreakpoints().
coverageEnabled
bool QJSDebuggerAgentPrivate::coverageEnabled
Definition at line 84 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::functionEntry(), QJSDebuggerAgent::functionExit(), QJSDebuggerAgent::positionChange(), QJSDebuggerAgent::scriptLoad(), and QJSDebuggerAgent::setCoverageEnabled().
filenames
QHash<qint64, QString> QJSDebuggerAgentPrivate::filenames
Definition at line 77 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::scriptLoad(), and QJSDebuggerAgent::scriptUnload().
fileNameToBreakpoints
QHash<QString, JSAgentBreakpointData> QJSDebuggerAgentPrivate::fileNameToBreakpoints
Definition at line 80 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::setBreakpoints().
isInitialized
bool QJSDebuggerAgentPrivate::isInitialized
Definition at line 83 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::isInitialized(), QJSDebuggerAgent::setBreakpoints(), and QJSDebuggerAgent::setCoverageEnabled().
knownObjectIds
QSet<qint64> QJSDebuggerAgentPrivate::knownObjectIds
Definition at line 82 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::executeExpression(), QJSDebuggerAgent::expandObjectById(), getLocals(), recordKnownObjects(), and QJSDebuggerAgent::setProperty().
loop
QEventLoop QJSDebuggerAgentPrivate::loop
Definition at line 76 of file qjsdebuggeragent.cpp.
q
QJSDebuggerAgent* QJSDebuggerAgentPrivate::q
Definition at line 71 of file qjsdebuggeragent.cpp.
Referenced by engine().
state
JSDebuggerState QJSDebuggerAgentPrivate::state
Definition at line 72 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::continueExecution(), QJSDebuggerAgent::stepInto(), QJSDebuggerAgent::stepOut(), and QJSDebuggerAgent::stepOver().
stepCount
int QJSDebuggerAgentPrivate::stepCount
Definition at line 74 of file qjsdebuggeragent.cpp.
stepDepth
int QJSDebuggerAgentPrivate::stepDepth
Definition at line 73 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::functionEntry(), QJSDebuggerAgent::functionExit(), QJSDebuggerAgent::stepInto(), QJSDebuggerAgent::stepOut(), and QJSDebuggerAgent::stepOver().
watchExpressions
QStringList QJSDebuggerAgentPrivate::watchExpressions
Definition at line 81 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived(), QJSDebuggerAgent::setWatchExpressions(), and QJSDebuggerAgent::watches().
The documentation for this class was generated from the following file:
/src/declarative/debugger/qjsdebuggeragent.cpp