Qt 4.8: QDialogButtonBoxPrivate Class Reference
QDialogButtonBoxPrivate Class Reference
Public Functions
void _q_handleButtonClicked ()
void _q_handleButtonDestroyed ()
void addButton (QAbstractButton *button, QDialogButtonBox::ButtonRole role, bool doLayout=true)
void addButtonsToLayout (const QList< QAbstractButton *> &buttonList, bool reverse)
QPushButton * createButton (QDialogButtonBox::StandardButton button, bool doLayout=true)
void createStandardButtons (QDialogButtonBox::StandardButtons buttons)
void initLayout ()
void layoutButtons ()
QDialogButtonBoxPrivate (Qt::Orientation orient)
void resetLayout ()
void retranslateStrings ()
const char * standardButtonText (QDialogButtonBox::StandardButton sbutton) const
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QBoxLayout * buttonLayout
QList< QAbstractButton * > buttonLists [QDialogButtonBox::NRoles]
bool center
bool internalRemove
QDialogButtonBox::ButtonLayout layoutPolicy
Qt::Orientation orientation
QHash< QPushButton *, QDialogButtonBox::StandardButton > standardButtonHash
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 291 of file qdialogbuttonbox.cpp.
Constructors and Destructors
QDialogButtonBoxPrivate()
QDialogButtonBoxPrivate::QDialogButtonBoxPrivate (Qt::Orientation orient)
Definition at line 327 of file qdialogbuttonbox.cpp.
     : orientation(orient), buttonLayout(0), internalRemove(false), center(false)
 {
 }
Functions
_q_handleButtonClicked()
void QDialogButtonBoxPrivate::_q_handleButtonClicked ()
Definition at line 1162 of file qdialogbuttonbox.cpp.
Referenced by addButton().
 {
     Q_Q(QDialogButtonBox);
     if (QAbstractButton *button = qobject_cast<QAbstractButton *>(q->sender())) {
         emit q->clicked(button);
         switch (q->buttonRole(button)) {
         case AcceptRole:
         case YesRole:
             emit q->accepted();
             break;
         case RejectRole:
         case NoRole:
             emit q->rejected();
             break;
         case HelpRole:
             emit q->helpRequested();
             break;
         default:
             break;
         }
     }
 }
_q_handleButtonDestroyed()
void QDialogButtonBoxPrivate::_q_handleButtonDestroyed ()
Definition at line 1186 of file qdialogbuttonbox.cpp.
Referenced by addButton().
 {
     Q_Q(QDialogButtonBox);
     if (QObject *object = q->sender()) {
         QBoolBlocker skippy(internalRemove);
         q->removeButton(static_cast<QAbstractButton *>(object));
     }
 }
addButton()
void QDialogButtonBoxPrivate::addButton (QAbstractButton * button, QDialogButtonBox::ButtonRole role, bool doLayout = true)
Definition at line 580 of file qdialogbuttonbox.cpp.
Referenced by createButton().
 {
     Q_Q(QDialogButtonBox);
     QObject::connect(button, SIGNAL(clicked()), q, SLOT(_q_handleButtonClicked()));
     QObject::connect(button, SIGNAL(destroyed()), q, SLOT(_q_handleButtonDestroyed()));
     buttonLists[role].append(button);
 #if defined(QT_SOFTKEYS_ENABLED) && !defined(QT_NO_ACTION)
     QAction *action = createSoftKey(button, role);
     softKeyActions.insert(button, action);
     new QDialogButtonEnabledProxy(action, button, action);
 #endif
     if (doLayout)
         layoutButtons();
 }
addButtonsToLayout()
void QDialogButtonBoxPrivate::addButtonsToLayout (const QList< QAbstractButton *> & buttonList, bool reverse)
Definition at line 371 of file qdialogbuttonbox.cpp.
Referenced by layoutButtons().
 {
     int start = reverse ? buttonList.count() - 1 : 0;
     int end = reverse ? -1 : buttonList.count();
     int step = reverse ? -1 : 1;
     for (int i = start; i != end; i += step) {
         QAbstractButton *button = buttonList.at(i);
         buttonLayout->addWidget(button);
         button->show();
     }
 }
createButton()
QPushButton * QDialogButtonBoxPrivate::createButton (QDialogButtonBox::StandardButton button, bool doLayout = true)
Definition at line 502 of file qdialogbuttonbox.cpp.
Referenced by createStandardButtons().
 {
     Q_Q(QDialogButtonBox);
     const char *buttonText = 0;
     int icon = 0;
     switch (sbutton) {
     case QDialogButtonBox::Ok:
         icon = QStyle::SP_DialogOkButton;
         break;
     case QDialogButtonBox::Save:
         icon = QStyle::SP_DialogSaveButton;
         break;
     case QDialogButtonBox::Open:
         icon = QStyle::SP_DialogOpenButton;
         break;
     case QDialogButtonBox::Cancel:
         icon = QStyle::SP_DialogCancelButton;
         break;
     case QDialogButtonBox::Close:
         icon = QStyle::SP_DialogCloseButton;
         break;
     case QDialogButtonBox::Apply:
         icon = QStyle::SP_DialogApplyButton;
         break;
     case QDialogButtonBox::Reset:
         icon = QStyle::SP_DialogResetButton;
         break;
     case QDialogButtonBox::Help:
         icon = QStyle::SP_DialogHelpButton;
         break;
     case QDialogButtonBox::Discard:
         icon = QStyle::SP_DialogDiscardButton;
         break;
     case QDialogButtonBox::Yes:
         icon = QStyle::SP_DialogYesButton;
         break;
     case QDialogButtonBox::No:
         icon = QStyle::SP_DialogNoButton;
         break;
     case QDialogButtonBox::YesToAll:
     case QDialogButtonBox::NoToAll:
     case QDialogButtonBox::SaveAll:
     case QDialogButtonBox::Abort:
     case QDialogButtonBox::Retry:
     case QDialogButtonBox::Ignore:
     case QDialogButtonBox::RestoreDefaults:
         break;
     case QDialogButtonBox::NoButton:
         return 0;
         ;
     }
     buttonText = standardButtonText(sbutton);
     QPushButton *button = new QPushButton(QDialogButtonBox::tr(buttonText), q);
     QStyle *style = q->style();
     if (style->styleHint(QStyle::SH_DialogButtonBox_ButtonsHaveIcons, 0, q) && icon != 0)
         button->setIcon(style->standardIcon(QStyle::StandardPixmap(icon), 0, q));
     if (style != QApplication::style()) // Propagate style
         button->setStyle(style);
     standardButtonHash.insert(button, sbutton);
     if (roleFor(sbutton) != QDialogButtonBox::InvalidRole) {
         addButton(button, roleFor(sbutton), doLayout);
     } else {
         qWarning("QDialogButtonBox::createButton: Invalid ButtonRole, button not added");
     }
 #ifdef Q_WS_MAC
     // Since mnemonics is off by default on Mac, we add a Cmd-D
     // shortcut here to e.g. make the "Don't Save" button work nativly:
     if (sbutton == QDialogButtonBox::Discard)
         button->setShortcut(QKeySequence(QLatin1String("Ctrl+D")));
 #endif
     return button;
 }
createStandardButtons()
void QDialogButtonBoxPrivate::createStandardButtons (QDialogButtonBox::StandardButtons buttons)
Definition at line 643 of file qdialogbuttonbox.cpp.
 {
     uint i = QDialogButtonBox::FirstButton;
     while (i <= QDialogButtonBox::LastButton) {
         if (i & buttons) {
             createButton(QDialogButtonBox::StandardButton(i), false);
         }
         i = i << 1;
     }
     layoutButtons();
 }
initLayout()
void QDialogButtonBoxPrivate::initLayout ()
Definition at line 332 of file qdialogbuttonbox.cpp.
Referenced by resetLayout().
 {
     Q_Q(QDialogButtonBox);
     layoutPolicy = QDialogButtonBox::ButtonLayout(q->style()->styleHint(QStyle::SH_DialogButtonLayout, 0, q));
     bool createNewLayout = buttonLayout == 0
         || (orientation == Qt::Horizontal && qobject_cast<QVBoxLayout *>(buttonLayout) != 0)
         || (orientation == Qt::Vertical && qobject_cast<QHBoxLayout *>(buttonLayout) != 0);
     if (createNewLayout) {
         delete buttonLayout;
         if (orientation == Qt::Horizontal)
             buttonLayout = new QHBoxLayout(q);
         else
             buttonLayout = new QVBoxLayout(q);
     }
     int left, top, right, bottom;
     setLayoutItemMargins(QStyle::SE_PushButtonLayoutItem);
     getLayoutItemMargins(&left, &top, &right, &bottom);
     buttonLayout->setContentsMargins(-left, -top, -right, -bottom);
     if (!q->testAttribute(Qt::WA_WState_OwnSizePolicy)) {
         QSizePolicy sp(QSizePolicy::Expanding, QSizePolicy::Fixed, QSizePolicy::ButtonBox);
         if (orientation == Qt::Vertical)
             sp.transpose();
         q->setSizePolicy(sp);
         q->setAttribute(Qt::WA_WState_OwnSizePolicy, false);
     }
     // ### move to a real init() function
     q->setFocusPolicy(Qt::TabFocus);
 }
layoutButtons()
void QDialogButtonBoxPrivate::layoutButtons ()
Definition at line 385 of file qdialogbuttonbox.cpp.
Referenced by addButton(), createStandardButtons(), and resetLayout().
 {
     Q_Q(QDialogButtonBox);
     const int MacGap = 36 - 8;    // 8 is the default gap between a widget and a spacer item
     for (int i = buttonLayout->count() - 1; i >= 0; --i) {
         QLayoutItem *item = buttonLayout->takeAt(i);
         if (QWidget *widget = item->widget())
             widget->hide();
         delete item;
     }
     int tmpPolicy = layoutPolicy;
     static const int M = 5;
     static const int ModalRoles[M] = { AcceptRole, RejectRole, DestructiveRole, YesRole, NoRole };
     if (tmpPolicy == QDialogButtonBox::MacLayout) {
         bool hasModalButton = false;
         for (int i = 0; i < M; ++i) {
             if (!buttonLists[ModalRoles[i]].isEmpty()) {
                 hasModalButton = true;
                 break;
             }
         }
         if (!hasModalButton)
             tmpPolicy = 4;  // Mac modeless
     }
     const uint *currentLayout = layouts[orientation == Qt::Vertical][tmpPolicy];
     if (center)
         buttonLayout->addStretch();
     QList<QAbstractButton *> acceptRoleList = buttonLists[AcceptRole];
     while (*currentLayout != EOL) {
         int role = (*currentLayout & ~Reverse);
         bool reverse = (*currentLayout & Reverse);
         switch (role) {
         case Stretch:
             if (!center)
                 buttonLayout->addStretch();
             break;
         case AcceptRole: {
             if (acceptRoleList.isEmpty())
                 break;
             // Only the first one
             QAbstractButton *button = acceptRoleList.first();
             buttonLayout->addWidget(button);
             button->show();
         }
             break;
         case AlternateRole:
             {
                 if (acceptRoleList.size() < 2)
                     break;
                 QList<QAbstractButton *> list = acceptRoleList;
                 list.removeFirst();
                 addButtonsToLayout(list, reverse);
             }
             break;
         case DestructiveRole:
             {
                 const QList<QAbstractButton *> &list = buttonLists[role];
                 /*
                     Mac: Insert a gap on the left of the destructive
                     buttons to ensure that they don't get too close to
                     the help and action buttons (but only if there are
                     some buttons to the left of the destructive buttons
                     (and the stretch, whence buttonLayout->count() > 1
                     and not 0)).
                 */
                 if (tmpPolicy == QDialogButtonBox::MacLayout
                         && !list.isEmpty() && buttonLayout->count() > 1)
                     buttonLayout->addSpacing(MacGap);
                 addButtonsToLayout(list, reverse);
                 /*
                     Insert a gap between the destructive buttons and the
                     accept and reject buttons.
                 */
                 if (tmpPolicy == QDialogButtonBox::MacLayout && !list.isEmpty())
                     buttonLayout->addSpacing(MacGap);
             }
             break;
         case RejectRole:
         case ActionRole:
         case HelpRole:
         case YesRole:
         case NoRole:
         case ApplyRole:
         case ResetRole:
             addButtonsToLayout(buttonLists[role], reverse);
         }
         ++currentLayout;
     }
     QWidget *lastWidget = 0;
     q->setFocusProxy(0);
     for (int i = 0; i < buttonLayout->count(); ++i) {
         QLayoutItem *item = buttonLayout->itemAt(i);
         if (QWidget *widget = item->widget()) {
             if (lastWidget)
                 QWidget::setTabOrder(lastWidget, widget);
             else
                 q->setFocusProxy(widget);
             lastWidget = widget;
         }
     }
     if (center)
         buttonLayout->addStretch();
 }
resetLayout()
void QDialogButtonBoxPrivate::resetLayout ()
Definition at line 364 of file qdialogbuttonbox.cpp.
 {
     //delete buttonLayout;
     initLayout();
     layoutButtons();
 }
retranslateStrings()
void QDialogButtonBoxPrivate::retranslateStrings ()
Definition at line 725 of file qdialogbuttonbox.cpp.
 {
     const char *buttonText = 0;
     QHash<QPushButton *, QDialogButtonBox::StandardButton>::iterator it =  standardButtonHash.begin();
     while (it != standardButtonHash.end()) {
         buttonText = standardButtonText(it.value());
         if (buttonText) {
             QPushButton *button = it.key();
             button->setText(QDialogButtonBox::tr(buttonText));
 #if defined(QT_SOFTKEYS_ENABLED) && !defined(QT_NO_ACTION)
             QAction *action = softKeyActions.value(button, 0);
             if (action)
                 action->setText(button->text());
 #endif
         }
         ++it;
     }
 }
standardButtonText()
const char * QDialogButtonBoxPrivate::standardButtonText (QDialogButtonBox::StandardButton sbutton) const
Definition at line 655 of file qdialogbuttonbox.cpp.
Referenced by createButton(), and retranslateStrings().
 {
     const char *buttonText = 0;
     bool gnomeLayout = (layoutPolicy == QDialogButtonBox::GnomeLayout);
     switch (sbutton) {
     case QDialogButtonBox::Ok:
         buttonText = gnomeLayout ? QT_TRANSLATE_NOOP("QDialogButtonBox", "&OK") : QT_TRANSLATE_NOOP("QDialogButtonBox", "OK");
         break;
     case QDialogButtonBox::Save:
         buttonText = gnomeLayout ? QT_TRANSLATE_NOOP("QDialogButtonBox", "&Save") : QT_TRANSLATE_NOOP("QDialogButtonBox", "Save");
         break;
     case QDialogButtonBox::Open:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Open");
         break;
     case QDialogButtonBox::Cancel:
         buttonText = gnomeLayout ? QT_TRANSLATE_NOOP("QDialogButtonBox", "&Cancel") : QT_TRANSLATE_NOOP("QDialogButtonBox", "Cancel");
         break;
     case QDialogButtonBox::Close:
         buttonText = gnomeLayout ? QT_TRANSLATE_NOOP("QDialogButtonBox", "&Close") : QT_TRANSLATE_NOOP("QDialogButtonBox", "Close");
         break;
     case QDialogButtonBox::Apply:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Apply");
         break;
     case QDialogButtonBox::Reset:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Reset");
         break;
     case QDialogButtonBox::Help:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Help");
         break;
     case QDialogButtonBox::Discard:
         if (layoutPolicy == QDialogButtonBox::MacLayout)
             buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Don't Save");
         else if (layoutPolicy == QDialogButtonBox::GnomeLayout)
             buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Close without Saving");
         else
             buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Discard");
         break;
     case QDialogButtonBox::Yes:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "&Yes");
         break;
     case QDialogButtonBox::YesToAll:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Yes to &All");
         break;
     case QDialogButtonBox::No:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "&No");
         break;
     case QDialogButtonBox::NoToAll:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "N&o to All");
         break;
     case QDialogButtonBox::SaveAll:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Save All");
         break;
     case QDialogButtonBox::Abort:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Abort");
         break;
     case QDialogButtonBox::Retry:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Retry");
         break;
     case QDialogButtonBox::Ignore:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Ignore");
         break;
     case QDialogButtonBox::RestoreDefaults:
         buttonText = QT_TRANSLATE_NOOP("QDialogButtonBox", "Restore Defaults");
         break;
     case QDialogButtonBox::NoButton:
         ;
     } // switch
     return buttonText;
 }
Properties
buttonLayout
QBoxLayout* QDialogButtonBoxPrivate::buttonLayout
Definition at line 306 of file qdialogbuttonbox.cpp.
Referenced by addButtonsToLayout(), initLayout(), and layoutButtons().
buttonLists
QList<QAbstractButton *> QDialogButtonBoxPrivate::buttonLists[QDialogButtonBox::NRoles]
Definition at line 298 of file qdialogbuttonbox.cpp.
Referenced by addButton(), and layoutButtons().
center
bool QDialogButtonBoxPrivate::center
Definition at line 308 of file qdialogbuttonbox.cpp.
Referenced by layoutButtons().
internalRemove
bool QDialogButtonBoxPrivate::internalRemove
Definition at line 307 of file qdialogbuttonbox.cpp.
layoutPolicy
QDialogButtonBox::ButtonLayout QDialogButtonBoxPrivate::layoutPolicy
Definition at line 305 of file qdialogbuttonbox.cpp.
Referenced by initLayout(), layoutButtons(), and standardButtonText().
orientation
Qt::Orientation QDialogButtonBoxPrivate::orientation
Definition at line 304 of file qdialogbuttonbox.cpp.
Referenced by initLayout(), and layoutButtons().
standardButtonHash
QHash<QPushButton *, QDialogButtonBox::StandardButton> QDialogButtonBoxPrivate::standardButtonHash
Definition at line 299 of file qdialogbuttonbox.cpp.
Referenced by createButton(), and retranslateStrings().
The documentation for this class was generated from the following file:
/src/gui/widgets/qdialogbuttonbox.cpp