Qt 4.8: QNetworkManagerEngine Class Reference
QNetworkManagerEngine Class Reference
#include <qnetworkmanagerengine.h>
Public Functions
quint64 bytesReceived (const QString &id)
quint64 bytesWritten (const QString &id)
QNetworkConfigurationManager::Capabilities capabilities () const
void connectToId (const QString &id)
QNetworkSessionPrivate * createSessionBackend ()
QNetworkConfigurationPrivatePointer defaultConfiguration ()
void disconnectFromId (const QString &id)
QString getInterfaceFromId (const QString &id)
bool hasIdentifier (const QString &id)
Q_INVOKABLE void initialize ()
bool networkManagerAvailable () const
QNetworkManagerEngine (QObject *parent=0)
Q_INVOKABLE void requestUpdate ()
QNetworkSession::State sessionStateForId (const QString &id)
quint64 startTime (const QString &id)
~QNetworkManagerEngine ()
Public Functions inherited from QBearerEngineImpl
QBearerEngineImpl (QObject *parent=0)
~QBearerEngineImpl ()
Public Functions inherited from QBearerEngine
bool configurationsInUse () const
QBearerEngine (QObject *parent=0)
virtual bool requiresPolling () const
virtual ~QBearerEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void activationFinished (QDBusPendingCallWatcher *watcher)
void activeConnectionPropertiesChanged (const QString &path, const QMap< QString, QVariant > &properties)
void deviceAdded (const QDBusObjectPath &path)
void devicePropertiesChanged (const QString &path, const QMap< QString, QVariant > &properties)
void deviceRemoved (const QDBusObjectPath &path)
void interfacePropertiesChanged (const QString &path, const QMap< QString, QVariant > &properties)
void newAccessPoint (const QString &path, const QDBusObjectPath &objectPath)
void newConnection (const QDBusObjectPath &path, QNetworkManagerSettings *settings=0)
void removeAccessPoint (const QString &path, const QDBusObjectPath &objectPath)
void removeConnection (const QString &path)
void updateAccessPoint (const QMap< QString, QVariant > &map)
void updateConnection (const QNmSettingsMap &settings)
Private Functions
QNetworkManagerSettingsConnection * connectionFromId (const QString &id) const
QNetworkConfigurationPrivate * parseConnection (const QString &service, const QString &settingsPath, const QNmSettingsMap &map)
Properties
QList< QNetworkManagerInterfaceAccessPoint * > accessPoints
QHash< QString, QNetworkManagerConnectionActive * > activeConnections
QList< QNetworkManagerInterfaceAccessPoint * > configuredAccessPoints
QList< QNetworkManagerSettingsConnection * > connections
QNetworkManagerInterface * interface
QNetworkManagerSettings * systemSettings
QNetworkManagerSettings * userSettings
QHash< QString, QNetworkManagerInterfaceDeviceWireless * > wirelessDevices
Additional Inherited Members
Public Types inherited from QBearerEngineImpl
enum ConnectionError { InterfaceLookupError = 0, ConnectError, OperationNotSupported, DisconnectionError }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QBearerEngineImpl
void connectionError (const QString &id, QBearerEngineImpl::ConnectionError error)
Signals inherited from QBearerEngine
void configurationAdded (QNetworkConfigurationPrivatePointer config)
void configurationChanged (QNetworkConfigurationPrivatePointer config)
void configurationRemoved (QNetworkConfigurationPrivatePointer config)
void updateCompleted ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QBearerEngine
QHash< QString, QNetworkConfigurationPrivatePointer > accessPointConfigurations
QMutex mutex
QHash< QString, QNetworkConfigurationPrivatePointer > snapConfigurations
QHash< QString, QNetworkConfigurationPrivatePointer > userChoiceConfigurations
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 68 of file qnetworkmanagerengine.h.
Constructors and Destructors
QNetworkManagerEngine()
QNetworkManagerEngine::QNetworkManagerEngine (QObject * parent = 0)
Definition at line 64 of file qnetworkmanagerengine.cpp.
 :   QBearerEngineImpl(parent),
     interface(new QNetworkManagerInterface(this)),
     systemSettings(new QNetworkManagerSettings(NM_DBUS_SERVICE_SYSTEM_SETTINGS, this)),
     userSettings(new QNetworkManagerSettings(NM_DBUS_SERVICE_USER_SETTINGS, this))
 {
     if (!interface->isValid())
         return;
     interface->setConnections();
     connect(interface, SIGNAL(deviceAdded(QDBusObjectPath)),
             this, SLOT(deviceAdded(QDBusObjectPath)));
     connect(interface, SIGNAL(deviceRemoved(QDBusObjectPath)),
             this, SLOT(deviceRemoved(QDBusObjectPath)));
 #if 0
     connect(interface, SIGNAL(stateChanged(const QString,quint32)),
             this, SIGNAL(configurationsChanged()));
 #endif
     connect(interface, SIGNAL(activationFinished(QDBusPendingCallWatcher*)),
             this, SLOT(activationFinished(QDBusPendingCallWatcher*)));
     connect(interface, SIGNAL(propertiesChanged(QString,QMap<QString,QVariant>)),
             this, SLOT(interfacePropertiesChanged(QString,QMap<QString,QVariant>)));
     qDBusRegisterMetaType<QNmSettingsMap>();
     systemSettings->setConnections();
     connect(systemSettings, SIGNAL(newConnection(QDBusObjectPath)),
             this, SLOT(newConnection(QDBusObjectPath)));
     userSettings->setConnections();
     connect(userSettings, SIGNAL(newConnection(QDBusObjectPath)),
             this, SLOT(newConnection(QDBusObjectPath)));
 }
~QNetworkManagerEngine()
QNetworkManagerEngine::~QNetworkManagerEngine ()
Definition at line 98 of file qnetworkmanagerengine.cpp.
 {
     qDeleteAll(connections);
     qDeleteAll(accessPoints);
     qDeleteAll(wirelessDevices);
     qDeleteAll(activeConnections);
 }
Functions
activationFinished
void QNetworkManagerEngine::activationFinished (QDBusPendingCallWatcher * watcher) private slot
Definition at line 515 of file qnetworkmanagerengine.cpp.
Referenced by QNetworkManagerEngine().
 {
     QMutexLocker locker(&mutex);
     QDBusPendingReply<QDBusObjectPath> reply = *watcher;
     if (!reply.isError()) {
         QDBusObjectPath result = reply.value();
         QNetworkManagerConnectionActive activeConnection(result.path());
         const QString id = QString::number(qHash(activeConnection.serviceName() + ' ' +
                                                  activeConnection.connection().path()));
         QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
         if (ptr) {
             ptr->mutex.lock();
             if (activeConnection.state() == 2 &&
                 ptr->state != QNetworkConfiguration::Active) {
                 ptr->state = QNetworkConfiguration::Active;
                 ptr->mutex.unlock();
                 locker.unlock();
                 emit configurationChanged(ptr);
                 locker.relock();
             } else {
                 ptr->mutex.unlock();
             }
         }
     }
 }
activeConnectionPropertiesChanged
void QNetworkManagerEngine::activeConnectionPropertiesChanged (const QString & path, const QMap< QString, QVariant > & properties) private slot
Definition at line 334 of file qnetworkmanagerengine.cpp.
Referenced by initialize(), and interfacePropertiesChanged().
 {
     QMutexLocker locker(&mutex);
     Q_UNUSED(properties)
     QNetworkManagerConnectionActive *activeConnection = activeConnections.value(path);
     if (!activeConnection)
         return;
     const QString id = QString::number(qHash(activeConnection->serviceName() + ' ' +
                                              activeConnection->connection().path()));
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
     if (ptr) {
         ptr->mutex.lock();
         if (activeConnection->state() == 2 &&
             ptr->state != QNetworkConfiguration::Active) {
             ptr->state = QNetworkConfiguration::Active;
             ptr->mutex.unlock();
             locker.unlock();
             emit configurationChanged(ptr);
             locker.relock();
         } else {
             ptr->mutex.unlock();
         }
     }
 }
bytesReceived()
quint64 QNetworkManagerEngine::bytesReceived (const QString & id) virtual
Reimplemented from QBearerEngineImpl.
Definition at line 853 of file qnetworkmanagerengine.cpp.
 {
     QMutexLocker locker(&mutex);
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
     if (ptr && (ptr->state & QNetworkConfiguration::Active) == QNetworkConfiguration::Active) {
         const QString networkInterface = getInterfaceFromId(id);
         if (!networkInterface.isEmpty()) {
             const QString devFile = QLatin1String("/sys/class/net/") +
                                     networkInterface +
                                     QLatin1String("/statistics/rx_bytes");
             quint64 result = Q_UINT64_C(0);
             QFile tx(devFile);
             if (tx.exists() && tx.open(QIODevice::ReadOnly | QIODevice::Text)) {
                 QTextStream in(&tx);
                 in >> result;
                 tx.close();
             }
             return result;
         }
     }
     return Q_UINT64_C(0);
 }
bytesWritten()
quint64 QNetworkManagerEngine::bytesWritten (const QString & id) virtual
Reimplemented from QBearerEngineImpl.
Definition at line 825 of file qnetworkmanagerengine.cpp.
 {
     QMutexLocker locker(&mutex);
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
     if (ptr && (ptr->state & QNetworkConfiguration::Active) == QNetworkConfiguration::Active) {
         const QString networkInterface = getInterfaceFromId(id);
         if (!networkInterface.isEmpty()) {
             const QString devFile = QLatin1String("/sys/class/net/") +
                                     networkInterface +
                                     QLatin1String("/statistics/tx_bytes");
             quint64 result = Q_UINT64_C(0);
             QFile tx(devFile);
             if (tx.exists() && tx.open(QIODevice::ReadOnly | QIODevice::Text)) {
                 QTextStream in(&tx);
                 in >> result;
                 tx.close();
             }
             return result;
         }
     }
     return Q_UINT64_C(0);
 }
capabilities()
QNetworkConfigurationManager::Capabilities QNetworkManagerEngine::capabilities () const virtual
Implements QBearerEngine.
Definition at line 892 of file qnetworkmanagerengine.cpp.
 {
     return QNetworkConfigurationManager::ForcedRoaming |
            QNetworkConfigurationManager::CanStartAndStopInterfaces;
 }
connectionFromId()
QNetworkManagerSettingsConnection * QNetworkManagerEngine::connectionFromId (const QString & id) const private
Definition at line 769 of file qnetworkmanagerengine.cpp.
Referenced by connectToId(), hasIdentifier(), and startTime().
 {
     for (int i = 0; i < connections.count(); ++i) {
         QNetworkManagerSettingsConnection *connection = connections.at(i);
         const QString service = connection->connectionInterface()->service();
         const QString settingsPath = connection->connectionInterface()->path();
         const QString identifier = QString::number(qHash(service + ' ' + settingsPath));
         if (id == identifier)
             return connection;
     }
     return 0;
 }
connectToId()
void QNetworkManagerEngine::connectToId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 192 of file qnetworkmanagerengine.cpp.
 {
     QMutexLocker locker(&mutex);
     QNetworkManagerSettingsConnection *connection = connectionFromId(id);
     if (!connection)
         return;
     QNmSettingsMap map = connection->getSettings();
     const QString connectionType = map.value("connection").value("type").toString();
     QString dbusDevicePath;
     foreach (const QDBusObjectPath &devicePath, interface->getDevices()) {
         QNetworkManagerInterfaceDevice device(devicePath.path());
         if (device.deviceType() == DEVICE_TYPE_802_3_ETHERNET &&
             connectionType == QLatin1String("802-3-ethernet")) {
             dbusDevicePath = devicePath.path();
             break;
         } else if (device.deviceType() == DEVICE_TYPE_802_11_WIRELESS &&
                    connectionType == QLatin1String("802-11-wireless")) {
             dbusDevicePath = devicePath.path();
             break;
         }
         else if (device.deviceType() == DEVICE_TYPE_GSM &&
                 connectionType == QLatin1String("gsm")) {
             dbusDevicePath = devicePath.path();
             break;
         }
     }
     const QString service = connection->connectionInterface()->service();
     const QString settingsPath = connection->connectionInterface()->path();
     interface->activateConnection(service, QDBusObjectPath(settingsPath),
                                   QDBusObjectPath(dbusDevicePath), QDBusObjectPath("/"));
 }
createSessionBackend()
QNetworkSessionPrivate * QNetworkManagerEngine::createSessionBackend () virtual
Implements QBearerEngine.
Definition at line 898 of file qnetworkmanagerengine.cpp.
 {
     return new QNetworkSessionPrivateImpl;
 }
defaultConfiguration()
QNetworkConfigurationPrivatePointer QNetworkManagerEngine::defaultConfiguration () virtual
Implements QBearerEngine.
Definition at line 903 of file qnetworkmanagerengine.cpp.
 {
     return QNetworkConfigurationPrivatePointer();
 }
deviceAdded
void QNetworkManagerEngine::deviceAdded (const QDBusObjectPath & path) private slot
Definition at line 373 of file qnetworkmanagerengine.cpp.
Referenced by initialize(), and QNetworkManagerEngine().
 {
     QNetworkManagerInterfaceDevice device(path.path());
     if (device.deviceType() == DEVICE_TYPE_802_11_WIRELESS) {
         QNetworkManagerInterfaceDeviceWireless *wirelessDevice =
             new QNetworkManagerInterfaceDeviceWireless(device.connectionInterface()->path());
         wirelessDevice->setConnections();
         connect(wirelessDevice, SIGNAL(accessPointAdded(QString,QDBusObjectPath)),
                 this, SLOT(newAccessPoint(QString,QDBusObjectPath)));
         connect(wirelessDevice, SIGNAL(accessPointRemoved(QString,QDBusObjectPath)),
                 this, SLOT(removeAccessPoint(QString,QDBusObjectPath)));
         connect(wirelessDevice, SIGNAL(propertiesChanged(QString,QMap<QString,QVariant>)),
                 this, SLOT(devicePropertiesChanged(QString,QMap<QString,QVariant>)));
         foreach (const QDBusObjectPath &apPath, wirelessDevice->getAccessPoints())
             newAccessPoint(QString(), apPath);
         mutex.lock();
         wirelessDevices.insert(path.path(), wirelessDevice);
         mutex.unlock();
     }
 }
devicePropertiesChanged
void QNetworkManagerEngine::devicePropertiesChanged (const QString & path, const QMap< QString, QVariant > & properties) private slot
Definition at line 366 of file qnetworkmanagerengine.cpp.
Referenced by deviceAdded().
 {
     Q_UNUSED(path);
     Q_UNUSED(properties);
 }
deviceRemoved
void QNetworkManagerEngine::deviceRemoved (const QDBusObjectPath & path) private slot
Definition at line 397 of file qnetworkmanagerengine.cpp.
Referenced by QNetworkManagerEngine().
 {
     QMutexLocker locker(&mutex);
     delete wirelessDevices.take(path.path());
 }
disconnectFromId()
void QNetworkManagerEngine::disconnectFromId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 230 of file qnetworkmanagerengine.cpp.
 {
     QMutexLocker locker(&mutex);
     foreach (const QDBusObjectPath &acPath, interface->activeConnections()) {
         QNetworkManagerConnectionActive activeConnection(acPath.path());
         const QString identifier = QString::number(qHash(activeConnection.serviceName() + ' ' +
                                                          activeConnection.connection().path()));
         if (id == identifier && accessPointConfigurations.contains(id)) {
             interface->deactivateConnection(acPath);
             break;
         }
     }
 }
getInterfaceFromId()
QString QNetworkManagerEngine::getInterfaceFromId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 148 of file qnetworkmanagerengine.cpp.
Referenced by bytesReceived(), and bytesWritten().
 {
     QMutexLocker locker(&mutex);
     foreach (const QDBusObjectPath &acPath, interface->activeConnections()) {
         QNetworkManagerConnectionActive activeConnection(acPath.path());
         const QString identifier = QString::number(qHash(activeConnection.serviceName() + ' ' +
                                                          activeConnection.connection().path()));
         if (id == identifier) {
             QList<QDBusObjectPath> devices = activeConnection.devices();
             if (devices.isEmpty())
                 continue;
             QNetworkManagerInterfaceDevice device(devices.at(0).path());
             return device.networkInterface();
         }
     }
     return QString();
 }
hasIdentifier()
bool QNetworkManagerEngine::hasIdentifier (const QString & id) virtual
Implements QBearerEngine.
Definition at line 172 of file qnetworkmanagerengine.cpp.
 {
     QMutexLocker locker(&mutex);
     if (connectionFromId(id))
         return true;
     for (int i = 0; i < accessPoints.count(); ++i) {
         QNetworkManagerInterfaceAccessPoint *accessPoint = accessPoints.at(i);
         const QString identifier =
             QString::number(qHash(accessPoint->connectionInterface()->path()));
         if (id == identifier)
             return true;
     }
     return false;
 }
initialize()
void QNetworkManagerEngine::initialize ()
Definition at line 106 of file qnetworkmanagerengine.cpp.
 {
     QMutexLocker locker(&mutex);
     // Get current list of access points.
     foreach (const QDBusObjectPath &devicePath, interface->getDevices()) {
         locker.unlock();
         deviceAdded(devicePath);
         locker.relock();
     }
     // Get connections.
     foreach (const QDBusObjectPath &settingsPath, systemSettings->listConnections()) {
         locker.unlock();
         newConnection(settingsPath, systemSettings);
         locker.relock();
     }
     foreach (const QDBusObjectPath &settingsPath, userSettings->listConnections()) {
         locker.unlock();
         newConnection(settingsPath, userSettings);
         locker.relock();
     }
     // Get active connections.
     foreach (const QDBusObjectPath &acPath, interface->activeConnections()) {
         QNetworkManagerConnectionActive *activeConnection =
             new QNetworkManagerConnectionActive(acPath.path());
         activeConnections.insert(acPath.path(), activeConnection);
         activeConnection->setConnections();
         connect(activeConnection, SIGNAL(propertiesChanged(QString,QMap<QString,QVariant>)),
                 this, SLOT(activeConnectionPropertiesChanged(QString,QMap<QString,QVariant>)));
     }
 }
interfacePropertiesChanged
void QNetworkManagerEngine::interfacePropertiesChanged (const QString & path, const QMap< QString, QVariant > & properties) private slot
Definition at line 252 of file qnetworkmanagerengine.cpp.
Referenced by QNetworkManagerEngine().
 {
     QMutexLocker locker(&mutex);
     Q_UNUSED(path)
     QMapIterator<QString, QVariant> i(properties);
     while (i.hasNext()) {
         i.next();
         if (i.key() == QLatin1String("ActiveConnections")) {
             // Active connections changed, update configurations.
             QList<QDBusObjectPath> activeConnections =
                 qdbus_cast<QList<QDBusObjectPath> >(i.value().value<QDBusArgument>());
             QStringList identifiers = accessPointConfigurations.keys();
             foreach (const QString &id, identifiers)
                 QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
             QStringList priorActiveConnections = this->activeConnections.keys();
             foreach (const QDBusObjectPath &acPath, activeConnections) {
                 priorActiveConnections.removeOne(acPath.path());
                 QNetworkManagerConnectionActive *activeConnection =
                     this->activeConnections.value(acPath.path());
                 if (!activeConnection) {
                     activeConnection = new QNetworkManagerConnectionActive(acPath.path());
                     this->activeConnections.insert(acPath.path(), activeConnection);
                     activeConnection->setConnections();
                     connect(activeConnection, SIGNAL(propertiesChanged(QString,QMap<QString,QVariant>)),
                             this, SLOT(activeConnectionPropertiesChanged(QString,QMap<QString,QVariant>)));
                 }
                 const QString id = QString::number(qHash(activeConnection->serviceName() + ' ' +
                                                          activeConnection->connection().path()));
                 identifiers.removeOne(id);
                 QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
                 if (ptr) {
                     ptr->mutex.lock();
                     if (activeConnection->state() == 2 &&
                         ptr->state != QNetworkConfiguration::Active) {
                         ptr->state = QNetworkConfiguration::Active;
                         ptr->mutex.unlock();
                         locker.unlock();
                         emit configurationChanged(ptr);
                         locker.relock();
                     } else {
                         ptr->mutex.unlock();
                     }
                 }
             }
             while (!priorActiveConnections.isEmpty())
                 delete this->activeConnections.take(priorActiveConnections.takeFirst());
             while (!identifiers.isEmpty()) {
                 // These configurations are not active
                 QNetworkConfigurationPrivatePointer ptr =
                     accessPointConfigurations.value(identifiers.takeFirst());
                 ptr->mutex.lock();
                 if ((ptr->state & QNetworkConfiguration::Active) == QNetworkConfiguration::Active) {
                     ptr->state = QNetworkConfiguration::Discovered;
                     ptr->mutex.unlock();
                     locker.unlock();
                     emit configurationChanged(ptr);
                     locker.relock();
                 } else {
                     ptr->mutex.unlock();
                 }
             }
         }
     }
 }
networkManagerAvailable()
bool QNetworkManagerEngine::networkManagerAvailable () const
Definition at line 141 of file qnetworkmanagerengine.cpp.
Referenced by QNetworkManagerEnginePlugin::create().
 {
     QMutexLocker locker(&mutex);
     return interface->isValid();
 }
newAccessPoint
void QNetworkManagerEngine::newAccessPoint (const QString & path, const QDBusObjectPath & objectPath) private slot
Definition at line 546 of file qnetworkmanagerengine.cpp.
Referenced by deviceAdded().
 {
     QMutexLocker locker(&mutex);
     Q_UNUSED(path)
     QNetworkManagerInterfaceAccessPoint *accessPoint =
         new QNetworkManagerInterfaceAccessPoint(objectPath.path());
     accessPoints.append(accessPoint);
     accessPoint->setConnections();
     connect(accessPoint, SIGNAL(propertiesChanged(QMap<QString,QVariant>)),
             this, SLOT(updateAccessPoint(QMap<QString,QVariant>)));
     // Check if configuration for this SSID already exists.
     for (int i = 0; i < accessPoints.count(); ++i) {
         if (accessPoint != accessPoints.at(i) &&
             accessPoint->ssid() == accessPoints.at(i)->ssid()) {
             return;
         }
     }
     // Check if configuration exists for connection.
     if (!accessPoint->ssid().isEmpty()) {
         for (int i = 0; i < connections.count(); ++i) {
             QNetworkManagerSettingsConnection *connection = connections.at(i);
             if (accessPoint->ssid() == connection->getSsid()) {
                 const QString service = connection->connectionInterface()->service();
                 const QString settingsPath = connection->connectionInterface()->path();
                 const QString connectionId = QString::number(qHash(service + ' ' + settingsPath));
                 QNetworkConfigurationPrivatePointer ptr =
                     accessPointConfigurations.value(connectionId);
                 ptr->mutex.lock();
                 ptr->state = QNetworkConfiguration::Discovered;
                 ptr->mutex.unlock();
                 locker.unlock();
                 emit configurationChanged(ptr);
                 return;
             }
         }
     }
     // New access point.
     QNetworkConfigurationPrivatePointer ptr(new QNetworkConfigurationPrivate);
     ptr->name = accessPoint->ssid();
     ptr->isValid = true;
     ptr->id = QString::number(qHash(objectPath.path()));
     ptr->type = QNetworkConfiguration::InternetAccessPoint;
     if(accessPoint->flags() == NM_802_11_AP_FLAGS_PRIVACY) {
         ptr->purpose = QNetworkConfiguration::PrivatePurpose;
     } else {
         ptr->purpose = QNetworkConfiguration::PublicPurpose;
     }
     ptr->state = QNetworkConfiguration::Undefined;
     ptr->bearerType = QNetworkConfiguration::BearerWLAN;
     accessPointConfigurations.insert(ptr->id, ptr);
     locker.unlock();
     emit configurationAdded(ptr);
 }
newConnection
void QNetworkManagerEngine::newConnection (const QDBusObjectPath & path, QNetworkManagerSettings * settings = 0) private slot
Definition at line 404 of file qnetworkmanagerengine.cpp.
Referenced by initialize(), and QNetworkManagerEngine().
 {
     QMutexLocker locker(&mutex);
     if (!settings)
         settings = qobject_cast<QNetworkManagerSettings *>(sender());
     if (!settings)
         return;
     QNetworkManagerSettingsConnection *connection =
         new QNetworkManagerSettingsConnection(settings->connectionInterface()->service(),
                                               path.path());
     connections.append(connection);
     connect(connection, SIGNAL(removed(QString)), this, SLOT(removeConnection(QString)));
     connect(connection, SIGNAL(updated(const QNmSettingsMap&)),
             this, SLOT(updateConnection(const QNmSettingsMap&)));
     const QString service = connection->connectionInterface()->service();
     const QString settingsPath = connection->connectionInterface()->path();
     QNetworkConfigurationPrivate *cpPriv =
         parseConnection(service, settingsPath, connection->getSettings());
     // Check if connection is active.
     foreach (const QDBusObjectPath &acPath, interface->activeConnections()) {
         QNetworkManagerConnectionActive activeConnection(acPath.path());
         if (activeConnection.serviceName() == service &&
             activeConnection.connection().path() == settingsPath &&
             activeConnection.state() == 2) {
             cpPriv->state |= QNetworkConfiguration::Active;
             break;
         }
     }
     QNetworkConfigurationPrivatePointer ptr(cpPriv);
     accessPointConfigurations.insert(ptr->id, ptr);
     locker.unlock();
     emit configurationAdded(ptr);
 }
parseConnection()
QNetworkConfigurationPrivate * QNetworkManagerEngine::parseConnection (const QString & service, const QString & settingsPath, const QNmSettingsMap & map) private
Definition at line 699 of file qnetworkmanagerengine.cpp.
Referenced by newConnection(), and updateConnection().
 {
     QNetworkConfigurationPrivate *cpPriv = new QNetworkConfigurationPrivate;
     cpPriv->name = map.value("connection").value("id").toString();
     cpPriv->isValid = true;
     cpPriv->id = QString::number(qHash(service + ' ' + settingsPath));
     cpPriv->type = QNetworkConfiguration::InternetAccessPoint;
     cpPriv->purpose = QNetworkConfiguration::PublicPurpose;
     cpPriv->state = QNetworkConfiguration::Defined;
     const QString connectionType = map.value("connection").value("type").toString();
     if (connectionType == QLatin1String("802-3-ethernet")) {
         cpPriv->bearerType = QNetworkConfiguration::BearerEthernet;
         cpPriv->purpose = QNetworkConfiguration::PublicPurpose;
         foreach (const QDBusObjectPath &devicePath, interface->getDevices()) {
             QNetworkManagerInterfaceDevice device(devicePath.path());
             if (device.deviceType() == DEVICE_TYPE_802_3_ETHERNET) {
                 QNetworkManagerInterfaceDeviceWired wiredDevice(device.connectionInterface()->path());
                 if (wiredDevice.carrier()) {
                     cpPriv->state |= QNetworkConfiguration::Discovered;
                     break;
                 }
             }
         }
     } else if (connectionType == QLatin1String("802-11-wireless")) {
         cpPriv->bearerType = QNetworkConfiguration::BearerWLAN;
         const QString connectionSsid = map.value("802-11-wireless").value("ssid").toString();
         const QString connectionSecurity = map.value("802-11-wireless").value("security").toString();
         if(!connectionSecurity.isEmpty()) {
             cpPriv->purpose = QNetworkConfiguration::PrivatePurpose;
         } else {
             cpPriv->purpose = QNetworkConfiguration::PublicPurpose;
         }
         for (int i = 0; i < accessPoints.count(); ++i) {
             if (connectionSsid == accessPoints.at(i)->ssid()) {
                 cpPriv->state |= QNetworkConfiguration::Discovered;
                 if (!configuredAccessPoints.contains(accessPoints.at(i))) {
                     configuredAccessPoints.append(accessPoints.at(i));
                     const QString accessPointId =
                         QString::number(qHash(accessPoints.at(i)->connectionInterface()->path()));
                     QNetworkConfigurationPrivatePointer ptr =
                         accessPointConfigurations.take(accessPointId);
                     if (ptr) {
                         mutex.unlock();
                         emit configurationRemoved(ptr);
                         mutex.lock();
                     }
                 }
                 break;
             }
         }
     } else if (connectionType == "gsm") {
         cpPriv->bearerType = QNetworkConfiguration::Bearer2G;
     } else if (connectionType == "cdma") {
         cpPriv->bearerType = QNetworkConfiguration::BearerCDMA2000;
     }
     return cpPriv;
 }
removeAccessPoint
void QNetworkManagerEngine::removeAccessPoint (const QString & path, const QDBusObjectPath & objectPath) private slot
Definition at line 612 of file qnetworkmanagerengine.cpp.
Referenced by deviceAdded().
 {
     QMutexLocker locker(&mutex);
     Q_UNUSED(path)
     for (int i = 0; i < accessPoints.count(); ++i) {
         QNetworkManagerInterfaceAccessPoint *accessPoint = accessPoints.at(i);
         if (accessPoint->connectionInterface()->path() == objectPath.path()) {
             accessPoints.removeOne(accessPoint);
             if (configuredAccessPoints.contains(accessPoint)) {
                 // find connection and change state to Defined
                 configuredAccessPoints.removeOne(accessPoint);
                 for (int i = 0; i < connections.count(); ++i) {
                     QNetworkManagerSettingsConnection *connection = connections.at(i);
                     if (accessPoint->ssid() == connection->getSsid()) {
                         const QString service = connection->connectionInterface()->service();
                         const QString settingsPath = connection->connectionInterface()->path();
                         const QString connectionId =
                             QString::number(qHash(service + ' ' + settingsPath));
                         QNetworkConfigurationPrivatePointer ptr =
                             accessPointConfigurations.value(connectionId);
                         ptr->mutex.lock();
                         ptr->state = QNetworkConfiguration::Defined;
                         ptr->mutex.unlock();
                         locker.unlock();
                         emit configurationChanged(ptr);
                         locker.relock();
                         break;
                     }
                 }
             } else {
                 QNetworkConfigurationPrivatePointer ptr =
                     accessPointConfigurations.take(QString::number(qHash(objectPath.path())));
                 if (ptr) {
                     locker.unlock();
                     emit configurationRemoved(ptr);
                     locker.relock();
                 }
             }
             delete accessPoint;
             break;
         }
     }
 }
removeConnection
void QNetworkManagerEngine::removeConnection (const QString & path) private slot
Definition at line 449 of file qnetworkmanagerengine.cpp.
Referenced by newConnection().
 {
     QMutexLocker locker(&mutex);
     Q_UNUSED(path)
     QNetworkManagerSettingsConnection *connection =
         qobject_cast<QNetworkManagerSettingsConnection *>(sender());
     if (!connection)
         return;
     connections.removeAll(connection);
     const QString id = QString::number(qHash(connection->connectionInterface()->service() + ' ' +
                                              connection->connectionInterface()->path()));
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.take(id);
     connection->deleteLater();
     locker.unlock();
     emit configurationRemoved(ptr);
 }
requestUpdate()
void QNetworkManagerEngine::requestUpdate ()
Definition at line 247 of file qnetworkmanagerengine.cpp.
 {
     QMetaObject::invokeMethod(this, "updateCompleted", Qt::QueuedConnection);
 }
sessionStateForId()
QNetworkSession::State QNetworkManagerEngine::sessionStateForId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 785 of file qnetworkmanagerengine.cpp.
 {
     QMutexLocker locker(&mutex);
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
     if (!ptr)
         return QNetworkSession::Invalid;
     if (!ptr->isValid)
         return QNetworkSession::Invalid;
     foreach (const QString &acPath, activeConnections.keys()) {
         QNetworkManagerConnectionActive *activeConnection = activeConnections.value(acPath);
         const QString identifier = QString::number(qHash(activeConnection->serviceName() + ' ' +
                                                          activeConnection->connection().path()));
         if (id == identifier) {
             switch (activeConnection->state()) {
             case 0:
                 return QNetworkSession::Disconnected;
             case 1:
                 return QNetworkSession::Connecting;
             case 2:
                 return QNetworkSession::Connected;
             }
         }
     }
     if ((ptr->state & QNetworkConfiguration::Discovered) == QNetworkConfiguration::Discovered)
         return QNetworkSession::Disconnected;
     else if ((ptr->state & QNetworkConfiguration::Defined) == QNetworkConfiguration::Defined)
         return QNetworkSession::NotAvailable;
     else if ((ptr->state & QNetworkConfiguration::Undefined) == QNetworkConfiguration::Undefined)
         return QNetworkSession::NotAvailable;
     return QNetworkSession::Invalid;
 }
startTime()
quint64 QNetworkManagerEngine::startTime (const QString & id) virtual
Reimplemented from QBearerEngineImpl.
Definition at line 881 of file qnetworkmanagerengine.cpp.
 {
     QMutexLocker locker(&mutex);
     QNetworkManagerSettingsConnection *connection = connectionFromId(id);
     if (connection)
         return connection->getTimestamp();
     else
         return Q_UINT64_C(0);
 }
updateAccessPoint
void QNetworkManagerEngine::updateAccessPoint (const QMap< QString, QVariant > & map) private slot
Definition at line 667 of file qnetworkmanagerengine.cpp.
Referenced by newAccessPoint().
 {
     QMutexLocker locker(&mutex);
     Q_UNUSED(map)
     QNetworkManagerInterfaceAccessPoint *accessPoint =
         qobject_cast<QNetworkManagerInterfaceAccessPoint *>(sender());
     if (!accessPoint)
         return;
     for (int i = 0; i < connections.count(); ++i) {
         QNetworkManagerSettingsConnection *connection = connections.at(i);
         if (accessPoint->ssid() == connection->getSsid()) {
             const QString service = connection->connectionInterface()->service();
             const QString settingsPath = connection->connectionInterface()->path();
             const QString connectionId = QString::number(qHash(service + ' ' + settingsPath));
             QNetworkConfigurationPrivatePointer ptr =
                 accessPointConfigurations.value(connectionId);
             ptr->mutex.lock();
             ptr->state = QNetworkConfiguration::Discovered;
             ptr->mutex.unlock();
             locker.unlock();
             emit configurationChanged(ptr);
             return;
         }
     }
 }
updateConnection
void QNetworkManagerEngine::updateConnection (const QNmSettingsMap & settings) private slot
Definition at line 473 of file qnetworkmanagerengine.cpp.
Referenced by newConnection().
 {
     QMutexLocker locker(&mutex);
     QNetworkManagerSettingsConnection *connection =
         qobject_cast<QNetworkManagerSettingsConnection *>(sender());
     if (!connection)
         return;
     const QString service = connection->connectionInterface()->service();
     const QString settingsPath = connection->connectionInterface()->path();
     QNetworkConfigurationPrivate *cpPriv = parseConnection(service, settingsPath, settings);
     // Check if connection is active.
     foreach (const QDBusObjectPath &acPath, interface->activeConnections()) {
         QNetworkManagerConnectionActive activeConnection(acPath.path());
         if (activeConnection.serviceName() == service &&
             activeConnection.connection().path() == settingsPath &&
             activeConnection.state() == NM_ACTIVE_CONNECTION_STATE_ACTIVATED) {
             cpPriv->state |= QNetworkConfiguration::Active;
             break;
         }
     }
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(cpPriv->id);
     ptr->mutex.lock();
     ptr->isValid = cpPriv->isValid;
     ptr->name = cpPriv->name;
     ptr->id = cpPriv->id;
     ptr->state = cpPriv->state;
     ptr->mutex.unlock();
     locker.unlock();
     emit configurationChanged(ptr);
     delete cpPriv;
 }
Properties
accessPoints
QList<QNetworkManagerInterfaceAccessPoint *> QNetworkManagerEngine::accessPoints private
Definition at line 132 of file qnetworkmanagerengine.h.
Referenced by hasIdentifier(), newAccessPoint(), parseConnection(), removeAccessPoint(), and ~QNetworkManagerEngine().
activeConnections
QHash<QString, QNetworkManagerConnectionActive *> QNetworkManagerEngine::activeConnections private
Definition at line 130 of file qnetworkmanagerengine.h.
Referenced by activeConnectionPropertiesChanged(), initialize(), interfacePropertiesChanged(), sessionStateForId(), and ~QNetworkManagerEngine().
configuredAccessPoints
QList<QNetworkManagerInterfaceAccessPoint *> QNetworkManagerEngine::configuredAccessPoints private
Definition at line 133 of file qnetworkmanagerengine.h.
Referenced by parseConnection(), and removeAccessPoint().
connections
QList<QNetworkManagerSettingsConnection *> QNetworkManagerEngine::connections private
Definition at line 131 of file qnetworkmanagerengine.h.
Referenced by connectionFromId(), newAccessPoint(), newConnection(), removeAccessPoint(), removeConnection(), updateAccessPoint(), and ~QNetworkManagerEngine().
interface
QNetworkManagerInterface* QNetworkManagerEngine::interface private
Definition at line 126 of file qnetworkmanagerengine.h.
Referenced by connectToId(), disconnectFromId(), getInterfaceFromId(), initialize(), networkManagerAvailable(), newConnection(), parseConnection(), QNetworkManagerEngine(), and updateConnection().
systemSettings
QNetworkManagerSettings* QNetworkManagerEngine::systemSettings private
Definition at line 127 of file qnetworkmanagerengine.h.
Referenced by initialize(), and QNetworkManagerEngine().
userSettings
QNetworkManagerSettings* QNetworkManagerEngine::userSettings private
Definition at line 128 of file qnetworkmanagerengine.h.
Referenced by initialize(), and QNetworkManagerEngine().
wirelessDevices
QHash<QString, QNetworkManagerInterfaceDeviceWireless *> QNetworkManagerEngine::wirelessDevices private
Definition at line 129 of file qnetworkmanagerengine.h.
Referenced by deviceAdded(), deviceRemoved(), and ~QNetworkManagerEngine().
The documentation for this class was generated from the following files:
/src/plugins/bearer/networkmanager/qnetworkmanagerengine.h
/src/plugins/bearer/networkmanager/qnetworkmanagerengine.cpp