Qt 4.8: QPatternist::AccelTreeResourceLoader Class Reference
QPatternist::AccelTreeResourceLoader Class Reference
Handles requests for documents, and instantiates them as AccelTree instances.
#include <qacceltreeresourceloader_p.h>
Public Types
enum ErrorHandling { FailOnError, ContinueOnError }
Public Types inherited from QPatternist::DeviceResourceLoader
typedef QExplicitlySharedDataPointer< DeviceResourceLoader > Ptr
Public Types inherited from QPatternist::ResourceLoader
typedef QExplicitlySharedDataPointer< ResourceLoader > Ptr
enum Usage { MayUse, WillUse }
Public Functions
AccelTreeResourceLoader (const NamePool::Ptr &np, const NetworkAccessDelegator::Ptr &networkDelegator, AccelTreeBuilder< true >::Features=AccelTreeBuilder< true >::NoneFeature)
virtual SequenceType::Ptr announceDocument (const QUrl &uri, const Usage usageHint)
May be called by the compilation framework at compile time to report that an XML document referenced by uri will be loaded at runtime.
virtual void clear (const QUrl &uri)
Asks to unload uri from its document pool, such that a subsequent request will require a new read.
virtual QSet< QUrl > deviceURIs () const
Returns the URIs this AccelTreeResourceLoader has loaded which are for devices through variable bindings.
virtual bool isDocumentAvailable (const QUrl &uri)
Calls to this function are generated by calls to the fn:doc-available() function.
virtual bool isUnparsedTextAvailable (const QUrl &uri, const QString &encoding)
Calls to this function are generated by calls to the fn:unparsed-text-available() function.
virtual Item openDocument (const QUrl &uri, const ReportContext::Ptr &context)
Calls to this function are generated by calls to the fn:document() or fn:doc() function.
virtual Item openDocument (QIODevice *source, const QUrl &documentUri, const ReportContext::Ptr &context)
virtual Item openUnparsedText (const QUrl &uri, const QString &encoding, const ReportContext::Ptr &context, const SourceLocationReflection *const where)
Calls to this function are generated by calls to the fn:unparsed-text() function.
Public Functions inherited from QPatternist::ResourceLoader
virtual SequenceType::Ptr announceCollection (const QUrl &uri)
May be called by the compilation framework at compile time to report that an node collection referenced by uri will be loaded at runtime.
virtual ItemType::Ptr announceUnparsedText (const QUrl &uri)
May be called by the compilation framework at compile time to report that an unparsed text(plain text) file referenced by uri will be loaded at runtime.
virtual Item::Iterator::Ptr openCollection (const QUrl &uri)
Calls to this function are generated by calls to the fn:collection() function.
ResourceLoader ()
virtual ~ResourceLoader ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Static Public Functions
static QNetworkReply * load (const QUrl &uri, QNetworkAccessManager *const networkManager, const ReportContext::Ptr &context, ErrorHandling handling=FailOnError)
Helper function that do NetworkAccessDelegator::get(), but does it blocked.
static QNetworkReply * load (const QUrl &uri, const NetworkAccessDelegator::Ptr &networkDelegator, const ReportContext::Ptr &context, ErrorHandling handling=FailOnError)
Private Functions
bool retrieveDocument (const QUrl &uri, const ReportContext::Ptr &context)
bool retrieveDocument (QIODevice *source, const QUrl &documentUri, const ReportContext::Ptr &context)
bool retrieveUnparsedText (const QUrl &uri, const QString &encoding, const ReportContext::Ptr &context, const SourceLocationReflection *const where)
Static Private Functions
static bool streamToReceiver (QIODevice *const dev, AccelTreeBuilder< true > *const receiver, const NamePool::Ptr &np, const ReportContext::Ptr &context, const QUrl &uri)
Properties
AccelTreeBuilder< true >::Features m_features
QHash< QUrl, AccelTree::Ptr > m_loadedDocuments
const NamePool::Ptr m_namePool
const NetworkAccessDelegator::Ptr m_networkAccessDelegator
QHash< QPair< QUrl, QString >, QString > m_unparsedTexts
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Handles requests for documents, and instantiates them as AccelTree instances.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 114 of file qacceltreeresourceloader_p.h.
Enumerations
ErrorHandling
enum QPatternist::AccelTreeResourceLoader::ErrorHandling
Describes the behaviour of the resource loader in case of an error.
Enumerator
FailOnError
The resource loader will report the error via the report context.
ContinueOnError
The resource loader will report no error and return an empty QNetworkReply.
Definition at line 121 of file qacceltreeresourceloader_p.h.
         {
             FailOnError,
             ContinueOnError
         };
Constructors and Destructors
AccelTreeResourceLoader()
AccelTreeResourceLoader::AccelTreeResourceLoader (const NamePool::Ptr & np, const NetworkAccessDelegator::Ptr & networkDelegator, AccelTreeBuilder< true >::Features features = AccelTreeBuilder<true>::NoneFeature)
AccelTreeResourceLoader does not own context.
Definition at line 59 of file qacceltreeresourceloader.cpp.
     : m_namePool(np)
     , m_networkAccessDelegator(manager)
     , m_features(features)
 {
     Q_ASSERT(m_namePool);
     Q_ASSERT(m_networkAccessDelegator);
 }
Functions
announceDocument()
SequenceType::Ptr AccelTreeResourceLoader::announceDocument (const QUrl & uri, const Usage usageHint) virtual
May be called by the compilation framework at compile time to report that an XML document referenced by uri will be loaded at runtime.
This function can be called an arbitrary amount of times for the same URI, but different usageHint values. How many times it is called for a URI has no meaning(beyond the first call, that is). For what queries the compilation framework can determine what always will be loaded is generally undefined. It depends on factors such as the complexity of the query, what information that is statically available and subsequently what optimizations that can be applied.
Calls to this function are generated by calls to the fn:document() or fn:doc() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
usageHint A hint to how the URI will be used.
Returns
null if the ResourceLoader can determine at this stage that no document referenced by uri will ever be possible to load.
The appropriate sequence type if loading uri succeeds at runtime. This must be CommonSequenceTypes::zeroOrOneDocument, CommonSequenceTypes::exactlyOneDocument or a sequence type that is a sub type of it.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.4 fn:doc
XSL Transformations (XSLT) Version 2.0, 16.1 Multiple Source Documents
Reimplemented from QPatternist::ResourceLoader.
Definition at line 296 of file qacceltreeresourceloader.cpp.
 {
     // TODO deal with the usage thingy
     Q_ASSERT(uri.isValid());
     Q_ASSERT(!uri.isRelative());
     Q_UNUSED(uri); /* Needed when compiling in release mode. */
     return CommonSequenceTypes::ZeroOrOneDocumentNode;
 }
clear()
void AccelTreeResourceLoader::clear (const QUrl & uri) virtual
Asks to unload uri from its document pool, such that a subsequent request will require a new read.
The default implementation does nothing.
Reimplemented from QPatternist::ResourceLoader.
Definition at line 435 of file qacceltreeresourceloader.cpp.
 {
     m_loadedDocuments.remove(uri);
 }
deviceURIs()
QSet< QUrl > AccelTreeResourceLoader::deviceURIs () const virtual
Returns the URIs this AccelTreeResourceLoader has loaded which are for devices through variable bindings.
Implements QPatternist::DeviceResourceLoader.
Definition at line 418 of file qacceltreeresourceloader.cpp.
 {
      QHash<QUrl, AccelTree::Ptr>::const_iterator it(m_loadedDocuments.constBegin());
      const QHash<QUrl, AccelTree::Ptr>::const_iterator end(m_loadedDocuments.constEnd());
      QSet<QUrl> retval;
      while (it != end)
      {
          if(it.key().toString().startsWith(QLatin1String("tag:trolltech.com,2007:QtXmlPatterns:QIODeviceVariable:")))
              retval.insert(it.key());
          ++it;
      }
      return retval;
 }
isDocumentAvailable()
bool AccelTreeResourceLoader::isDocumentAvailable (const QUrl & uri) virtual
Calls to this function are generated by calls to the fn:doc-available() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
Returns
true if calling openDocument() while passing uri will successfully load the document.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.5 fn:doc-available
XSL Transformations (XSLT) Version 2.0, 16.1 Multiple Source Documents
Reimplemented from QPatternist::ResourceLoader.
Definition at line 306 of file qacceltreeresourceloader.cpp.
 {
     return retrieveDocument(uri, ReportContext::Ptr());
 }
isUnparsedTextAvailable()
bool AccelTreeResourceLoader::isUnparsedTextAvailable (const QUrl & uri, const QString & encoding) virtual
Calls to this function are generated by calls to the fn:unparsed-text-available() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
Returns
true if calling openUnparsedText() while passing uri will successfully load the document.
See also
XSL Transformations (XSLT) Version 2.0, 16.2 Reading Text Files
Reimplemented from QPatternist::ResourceLoader.
Definition at line 394 of file qacceltreeresourceloader.cpp.
 {
     return retrieveUnparsedText(uri, encoding, ReportContext::Ptr(), 0);
 }
load() [1/2]
QNetworkReply * AccelTreeResourceLoader::load (const QUrl & uri, QNetworkAccessManager *const networkManager, const ReportContext::Ptr & context, ErrorHandling handling = FailOnError) static
Helper function that do NetworkAccessDelegator::get(), but does it blocked.
The returned QNetworkReply has emitted QNetworkReply::finished().
The caller owns the return QIODevice instance.
context may be null or valid. If null, no error reporting is done and null is returned.
See also
NetworkAccessDelegator
Definition at line 113 of file qacceltreeresourceloader.cpp.
Referenced by QXmlSchemaPrivate::load(), load(), QPatternist::XsdValidatingInstanceReader::loadSchema(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseRedefine(), retrieveDocument(), retrieveUnparsedText(), QXmlQuery::setQuery(), and QXmlSchemaValidator::validate().
 {
     Q_ASSERT(networkManager);
     Q_ASSERT(uri.isValid());
     NetworkLoop networkLoop;
     QNetworkRequest request(uri);
     QNetworkReply *const reply = networkManager->get(request);
     networkLoop.connect(reply, SIGNAL(error(QNetworkReply::NetworkError)), SLOT(error(QNetworkReply::NetworkError)));
     networkLoop.connect(reply, SIGNAL(finished()), SLOT(finished()));
     if(networkLoop.exec(QEventLoop::ExcludeUserInputEvents))
     {
         const QString errorMessage(escape(reply->errorString()));
         /* Note, we delete reply before we exit this function with error(). */
         delete reply;
         const QSourceLocation location(uri);
         if(context && (errorHandling == FailOnError))
             context->error(errorMessage, ReportContext::FODC0002, location);
         return 0;
     }
     else
         return reply;
 }
load() [2/2]
QNetworkReply * AccelTreeResourceLoader::load (const QUrl & uri, const NetworkAccessDelegator::Ptr & networkDelegator, const ReportContext::Ptr & context, ErrorHandling handling = FailOnError) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 104 of file qacceltreeresourceloader.cpp.
 {
     return load(uri,
                 networkDelegator->managerFor(uri),
                 context, errorHandling);
 }
openDocument() [1/2]
Item AccelTreeResourceLoader::openDocument (const QUrl & uri, const ReportContext::Ptr & context) virtual
Calls to this function are generated by calls to the fn:document() or fn:doc() function.
Note
This function is responsible for execution stability. Subsequent calls to this function with the same URI should result in QXmlNodeModelIndex instances that have the same identity. However, in some cases this stability is not of interest, see the specification for details.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
See also
QXmlNodeModelIndex::identity()
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.4 fn:doc
XSL Transformations (XSLT) Version 2.0, 16.1 Multiple Source Documents
Returns
null if no document can be loaded for uri
A QXmlNodeModelIndex representing the document identified by uri. Remember that the QXmlNodeModelIndex must match the sequence type returned by announceDocument()
Reimplemented from QPatternist::ResourceLoader.
Definition at line 264 of file qacceltreeresourceloader.cpp.
 {
     const AccelTree::Ptr doc(m_loadedDocuments.value(uri));
     if(doc)
         return doc->root(QXmlNodeModelIndex()); /* Pass in dummy object. We know AccelTree doesn't use it. */
     else
     {
         if(retrieveDocument(uri, context))
             return m_loadedDocuments.value(uri)->root(QXmlNodeModelIndex()); /* Pass in dummy object. We know AccelTree doesn't use it. */
         else
             return Item();
     }
 }
openDocument() [2/2]
Item AccelTreeResourceLoader::openDocument (QIODevice * source, const QUrl & documentUri, const ReportContext::Ptr & context) virtual
Definition at line 280 of file qacceltreeresourceloader.cpp.
 {
     const AccelTree::Ptr doc(m_loadedDocuments.value(documentUri));
     if(doc)
         return doc->root(QXmlNodeModelIndex()); /* Pass in dummy object. We know AccelTree doesn't use it. */
     else
     {
         if(retrieveDocument(source, documentUri, context))
             return m_loadedDocuments.value(documentUri)->root(QXmlNodeModelIndex()); /* Pass in dummy object. We know AccelTree doesn't use it. */
         else
             return Item();
     }
 }
openUnparsedText()
Item AccelTreeResourceLoader::openUnparsedText (const QUrl & uri, const QString & encoding, const ReportContext::Ptr & context, const SourceLocationReflection *const where) virtual
Calls to this function are generated by calls to the fn:unparsed-text() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
encoding the encoding to use. If empty, the user hasn't expressed any encoding to use.
See also
XSL Transformations (XSLT) Version 2.0, 16.2 Reading Text Files
Returns
null if no unparsed file can be loaded for uri
An xs:string value(or subtype) containing the content of the file identified by uri as text. Remember that its type must match the sequence type returned by announceUnparsedText()
Reimplemented from QPatternist::ResourceLoader.
Definition at line 400 of file qacceltreeresourceloader.cpp.
 {
     const QString &text = m_unparsedTexts.value(qMakePair(uri, encoding));
     if(text.isNull())
     {
         if(retrieveUnparsedText(uri, encoding, context, where))
             return openUnparsedText(uri, encoding, context, where);
         else
             return Item();
     }
     else
         return AtomicString::fromValue(text);
 }
retrieveDocument() [1/2]
bool AccelTreeResourceLoader::retrieveDocument (const QUrl & uri, const ReportContext::Ptr & context) private
Definition at line 70 of file qacceltreeresourceloader.cpp.
Referenced by isDocumentAvailable(), and openDocument().
 {
     Q_ASSERT(uri.isValid());
     AccelTreeBuilder<true> builder(uri, uri, m_namePool, context.data(), m_features);
     const AutoPtr<QNetworkReply> reply(load(uri, m_networkAccessDelegator, context));
     if(!reply)
         return false;
     bool success = false;
     success = streamToReceiver(reply.data(), &builder, m_namePool, context, uri);
     m_loadedDocuments.insert(uri, builder.builtDocument());
     return success;
 }
retrieveDocument() [2/2]
bool AccelTreeResourceLoader::retrieveDocument (QIODevice * source, const QUrl & documentUri, const ReportContext::Ptr & context) private
Definition at line 88 of file qacceltreeresourceloader.cpp.
 {
     Q_ASSERT(source);
     Q_ASSERT(source->isReadable());
     Q_ASSERT(documentUri.isValid());
     AccelTreeBuilder<true> builder(documentUri, documentUri, m_namePool, context.data(), m_features);
     bool success = false;
     success = streamToReceiver(source, &builder, m_namePool, context, documentUri);
     m_loadedDocuments.insert(documentUri, builder.builtDocument());
     return success;
 }
retrieveUnparsedText()
bool AccelTreeResourceLoader::retrieveUnparsedText (const QUrl & uri, const QString & encoding, const ReportContext::Ptr & context, const SourceLocationReflection *const where) private
If context is null, no error reporting should be done.
Definition at line 317 of file qacceltreeresourceloader.cpp.
Referenced by isUnparsedTextAvailable(), and openUnparsedText().
 {
     const AutoPtr<QNetworkReply> reply(load(uri, m_networkAccessDelegator, context));
     if(!reply)
         return false;
     const QTextCodec * codec;
     if(encoding.isEmpty())
     {
         /* XSL Transformations (XSLT) Version 2.0 16.2 Reading Text Files:
          *
          * "if the media type of the resource is text/xml or application/xml
          * (see [RFC2376]), or if it matches the conventions text/\*+xml or
          * application/\*+xml (see [RFC3023] and/or its successors), then the
          * encoding is recognized as specified in [XML 1.0]"
          */
         codec = QTextCodec::codecForMib(106);
     }
     else
     {
         codec = QTextCodec::codecForName(encoding.toLatin1());
         if(codec && context)
         {
             context->error(QtXmlPatterns::tr("%1 is an unsupported encoding.").arg(formatURI(encoding)),
                            ReportContext::XTDE1190,
                            where);
         }
         else
             return false;
     }
     QTextCodec::ConverterState converterState;
     const QByteArray inData(reply->readAll());
     const QString result(codec->toUnicode(inData.constData(), inData.length(), &converterState));
     if(converterState.invalidChars)
     {
         if(context)
         {
             context->error(QtXmlPatterns::tr("%1 contains octets which are disallowed in "
                                              "the requested encoding %2.").arg(formatURI(uri),
                                                                                formatURI(encoding)),
                            ReportContext::XTDE1190,
                            where);
         }
         else
             return false;
     }
     const int len = result.length();
     /* This code is a candidate for threading. Divide and conqueror. */
     for(int i = 0; i < len; ++i)
     {
         if(!QXmlUtils::isChar(result.at(i)))
         {
             if(context)
             {
                 context->error(QtXmlPatterns::tr("The codepoint %1, occurring in %2 using encoding %3, "
                                                  "is an invalid XML character.").arg(formatData(result.at(i)),
                                                                                      formatURI(uri),
                                                                                      formatURI(encoding)),
                                ReportContext::XTDE1190,
                                where);
             }
             else
                 return false;
         }
     }
     m_unparsedTexts.insert(qMakePair(uri, encoding), result);
     return true;
 }
streamToReceiver()
bool AccelTreeResourceLoader::streamToReceiver (QIODevice *const dev, AccelTreeBuilder< true > *const receiver, const NamePool::Ptr & np, const ReportContext::Ptr & context, const QUrl & uri) static private
Definition at line 146 of file qacceltreeresourceloader.cpp.
Referenced by retrieveDocument().
 {
     Q_ASSERT(dev);
     Q_ASSERT(receiver);
     Q_ASSERT(np);
     QXmlStreamReader reader(dev);
     /* Optimize: change NamePool to take QStringRef such that we don't have to call toString() below. That
      * will save us a gazillion of temporary QStrings. */
     while(!reader.atEnd())
     {
         reader.readNext();
         switch(reader.tokenType())
         {
             case QXmlStreamReader::StartElement:
             {
                 /* Send the name. */
                 receiver->startElement(np->allocateQName(reader.namespaceUri().toString(), reader.name().toString(),
                                                          reader.prefix().toString()), reader.lineNumber(), reader.columnNumber());
                 /* Send namespace declarations. */
                 const QXmlStreamNamespaceDeclarations &nss = reader.namespaceDeclarations();
                 /* The far most common case, is for it to be empty. */
                 if(!nss.isEmpty())
                 {
                     const int len = nss.size();
                     for(int i = 0; i < len; ++i)
                     {
                         const QXmlStreamNamespaceDeclaration &ns = nss.at(i);
                         receiver->namespaceBinding(np->allocateBinding(ns.prefix().toString(), ns.namespaceUri().toString()));
                     }
                 }
                 /* Send attributes. */
                 const QXmlStreamAttributes &attrs = reader.attributes();
                 const int len = attrs.size();
                 for(int i = 0; i < len; ++i)
                 {
                     const QXmlStreamAttribute &attr = attrs.at(i);
                     receiver->attribute(np->allocateQName(attr.namespaceUri().toString(), attr.name().toString(),
                                                           attr.prefix().toString()),
                                         attr.value());
                 }
                 continue;
             }
             case QXmlStreamReader::EndElement:
             {
                 receiver->endElement();
                 continue;
             }
             case QXmlStreamReader::Characters:
             {
                 if(reader.isWhitespace())
                     receiver->whitespaceOnly(reader.text());
                 else
                     receiver->characters(reader.text());
                 continue;
             }
             case QXmlStreamReader::Comment:
             {
                 receiver->comment(reader.text().toString());
                 continue;
             }
             case QXmlStreamReader::ProcessingInstruction:
             {
                 receiver->processingInstruction(np->allocateQName(QString(), reader.processingInstructionTarget().toString()),
                                                 reader.processingInstructionData().toString());
                 continue;
             }
             case QXmlStreamReader::StartDocument:
             {
                 receiver->startDocument();
                 continue;
             }
             case QXmlStreamReader::EndDocument:
             {
                 receiver->endDocument();
                 continue;
             }
             case QXmlStreamReader::EntityReference:
             /* Fallthrough. */
             case QXmlStreamReader::DTD:
             {
                 /* We just ignore any DTD and entity references. */
                 continue;
             }
             case QXmlStreamReader::Invalid:
             {
                 if(context)
                     context->error(escape(reader.errorString()), ReportContext::FODC0002, QSourceLocation(uri, reader.lineNumber(), reader.columnNumber()));
                 return false;
             }
             case QXmlStreamReader::NoToken:
             {
                 Q_ASSERT_X(false, Q_FUNC_INFO,
                            "This token is never expected to be received.");
                 return false;
             }
         }
     }
     return true;
 }
Properties
m_features
AccelTreeBuilder<true>::Features QPatternist::AccelTreeResourceLoader::m_features private
Definition at line 202 of file qacceltreeresourceloader_p.h.
Referenced by retrieveDocument().
m_loadedDocuments
QHash<QUrl, AccelTree::Ptr> QPatternist::AccelTreeResourceLoader::m_loadedDocuments private
Definition at line 198 of file qacceltreeresourceloader_p.h.
Referenced by clear(), deviceURIs(), openDocument(), and retrieveDocument().
m_namePool
const NamePool::Ptr QPatternist::AccelTreeResourceLoader::m_namePool private
Definition at line 199 of file qacceltreeresourceloader_p.h.
Referenced by AccelTreeResourceLoader(), and retrieveDocument().
m_networkAccessDelegator
const NetworkAccessDelegator::Ptr QPatternist::AccelTreeResourceLoader::m_networkAccessDelegator private
Definition at line 200 of file qacceltreeresourceloader_p.h.
Referenced by AccelTreeResourceLoader(), retrieveDocument(), and retrieveUnparsedText().
m_unparsedTexts
QHash<QPair<QUrl, QString>, QString> QPatternist::AccelTreeResourceLoader::m_unparsedTexts private
Definition at line 201 of file qacceltreeresourceloader_p.h.
Referenced by openUnparsedText(), and retrieveUnparsedText().
The documentation for this class was generated from the following files:
/src/xmlpatterns/acceltree/qacceltreeresourceloader_p.h
/src/xmlpatterns/acceltree/qacceltreeresourceloader.cpp