Qt 4.8: QXmlDeclHandler Class Reference
QXmlDeclHandler Class Reference abstract
The QXmlDeclHandler class provides an interface to report declaration content of XML data.
#include <qxml.h>
Public Functions
virtual bool attributeDecl (const QString &eName, const QString &aName, const QString &type, const QString &valueDefault, const QString &value)=0
The reader calls this function to report an attribute type declaration.
virtual QString errorString () const =0
The reader calls this function to get an error string if any of the handler functions returns false.
virtual bool externalEntityDecl (const QString &name, const QString &publicId, const QString &systemId)=0
The reader calls this function to report a parsed external entity declaration.
virtual bool internalEntityDecl (const QString &name, const QString &value)=0
The reader calls this function to report an internal entity declaration.
virtual ~QXmlDeclHandler ()
Destroys the declaration handler.
Detailed Description
The QXmlDeclHandler class provides an interface to report declaration content of XML data.
Note
This class or function is reentrant.
Attention
Module: QtXml
You can set the declaration handler with QXmlReader::setDeclHandler().
This interface is based on the SAX2 extension DeclHandler.
The interface provides attributeDecl(), internalEntityDecl() and externalEntityDecl() functions.
See also
QXmlDTDHandler, QXmlContentHandler, QXmlEntityResolver, QXmlErrorHandler, QXmlLexicalHandler, {Introduction to SAX2}
Definition at line 360 of file qxml.h.
Constructors and Destructors
~QXmlDeclHandler()
QXmlDeclHandler::~QXmlDeclHandler () inline virtual
Destroys the declaration handler.
Definition at line 363 of file qxml.h.
 {}
Functions
attributeDecl()
bool QXmlDeclHandler::attributeDecl (const QString & eName, const QString & aName, const QString & type, const QString & valueDefault, const QString & value) pure virtual
The reader calls this function to report an attribute type declaration.
Only the effective (first) declaration for an attribute is reported.
The reader passes the name of the associated element in eName and the name of the attribute in aName. It passes a string that represents the attribute type in type and a string that represents the attribute default in valueDefault. This string is one of "#IMPLIED", "#REQUIRED", "#FIXED" or an empty string (if none of the others applies). The reader passes the attribute's default value in value. If no default value is specified in the XML file, value is an empty string.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
Implemented in QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseAttlistDecl().
errorString()
QString QXmlDeclHandler::errorString () const pure virtual
The reader calls this function to get an error string if any of the handler functions returns false.
Implemented in QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseAttlistDecl(), and QXmlSimpleReaderPrivate::parseEntityDecl().
externalEntityDecl()
bool QXmlDeclHandler::externalEntityDecl (const QString & name, const QString & publicId, const QString & systemId) pure virtual
The reader calls this function to report a parsed external entity declaration.
Only the effective (first) declaration for each entity is reported.
The reader passes the name of the entity in name, the public identifier in publicId and the system identifier in systemId. If there is no public identifier specified, it passes an empty string in publicId.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
Implemented in QDomHandler, and QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseEntityDecl().
internalEntityDecl()
bool QXmlDeclHandler::internalEntityDecl (const QString & name, const QString & value) pure virtual
The reader calls this function to report an internal entity declaration.
Only the effective (first) declaration is reported.
The reader passes the name of the entity in name and the value of the entity in value.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
Implemented in QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseEntityDecl().
The documentation for this class was generated from the following files:
/src/xml/sax/qxml.h
/src/xml/sax/qxml.cpp