Qt 4.8: QScript::QScriptMetaType Class Reference
QScript::QScriptMetaType Class Reference
Public Types
enum Kind {
Invalid, Variant, MetaType, Unresolved,
MetaEnum
}
Public Functions
int enumeratorIndex () const
bool isMetaEnum () const
bool isMetaType () const
bool isUnresolved () const
bool isValid () const
bool isVariant () const
Kind kind () const
QByteArray name () const
bool operator== (const QScriptMetaType &other) const
QScriptMetaType ()
int typeId () const
Static Public Functions
static QScriptMetaType metaEnum (int enumIndex, const QByteArray &name)
static QScriptMetaType metaType (int typeId, const QByteArray &name)
static QScriptMetaType unresolved (const QByteArray &name)
static QScriptMetaType variant ()
Private Functions
QScriptMetaType (Kind kind, int typeId=0, const QByteArray &name=QByteArray())
Properties
Kind m_kind
QByteArray m_name
int m_typeId
Detailed Description
Definition at line 364 of file qscriptqobject.cpp.
Enumerations
Kind
enum QScript::QScriptMetaType::Kind
Enumerator
Invalid
Variant
MetaType
Unresolved
MetaEnum
Definition at line 367 of file qscriptqobject.cpp.
               {
         Invalid,
         Variant,
         MetaType,
         Unresolved,
         MetaEnum
     };
Constructors and Destructors
QScriptMetaType() [1/2]
QScript::QScriptMetaType::QScriptMetaType () inline
Definition at line 375 of file qscriptqobject.cpp.
         : m_kind(Invalid) { }
QScriptMetaType() [2/2]
QScript::QScriptMetaType::QScriptMetaType (Kind kind, int typeId = 0, const QByteArray & name = QByteArray()) inline private
Definition at line 421 of file qscriptqobject.cpp.
         : m_kind(kind), m_typeId(typeId), m_name(name) { }
Functions
enumeratorIndex()
int QScript::QScriptMetaType::enumeratorIndex () const inline
Definition at line 400 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { Q_ASSERT(isMetaEnum()); return m_typeId; }
isMetaEnum()
bool QScript::QScriptMetaType::isMetaEnum () const inline
Definition at line 395 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return (m_kind == MetaEnum); }
isMetaType()
bool QScript::QScriptMetaType::isMetaType () const inline
Definition at line 389 of file qscriptqobject.cpp.
     { return (m_kind == MetaType); }
isUnresolved()
bool QScript::QScriptMetaType::isUnresolved () const inline
Definition at line 392 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return (m_kind == Unresolved); }
isValid()
bool QScript::QScriptMetaType::isValid () const inline
Definition at line 383 of file qscriptqobject.cpp.
     { return (m_kind != Invalid); }
isVariant()
bool QScript::QScriptMetaType::isVariant () const inline
Definition at line 386 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return (m_kind == Variant); }
kind()
Kind QScript::QScriptMetaType::kind () const inline
Definition at line 378 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return m_kind; }
metaEnum()
static QScriptMetaType QScript::QScriptMetaType::metaEnum (int enumIndex, const QByteArray & name) inline static
Definition at line 414 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return QScriptMetaType(MetaEnum, enumIndex, name); }
metaType()
static QScriptMetaType QScript::QScriptMetaType::metaType (int typeId, const QByteArray & name) inline static
Definition at line 411 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return QScriptMetaType(MetaType, typeId, name); }
name()
QByteArray QScript::QScriptMetaType::name () const
Definition at line 436 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
 {
     if (!m_name.isEmpty())
         return m_name;
     else if (m_kind == Variant)
         return "QVariant";
     return QMetaType::typeName(typeId());
 }
operator==()
bool QScript::QScriptMetaType::operator== (const QScriptMetaType & other) const inline
Definition at line 403 of file qscriptqobject.cpp.
     {
         return (m_kind == other.m_kind) && (m_typeId == other.m_typeId);
     }
typeId()
int QScript::QScriptMetaType::typeId () const
Definition at line 429 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
 {
     if (isVariant())
         return QMetaType::type("QVariant");
     return isMetaEnum() ? 2/*int*/ : m_typeId;
 }
unresolved()
static QScriptMetaType QScript::QScriptMetaType::unresolved (const QByteArray & name) inline static
Definition at line 417 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return QScriptMetaType(Unresolved, /*typeId=*/0, name); }
variant()
static QScriptMetaType QScript::QScriptMetaType::variant () inline static
Definition at line 408 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return QScriptMetaType(Variant); }
Properties
m_kind
Kind QScript::QScriptMetaType::m_kind private
Definition at line 424 of file qscriptqobject.cpp.
Referenced by operator==().
m_name
QByteArray QScript::QScriptMetaType::m_name private
Definition at line 426 of file qscriptqobject.cpp.
m_typeId
int QScript::QScriptMetaType::m_typeId private
Definition at line 425 of file qscriptqobject.cpp.
Referenced by operator==().
The documentation for this class was generated from the following file:
/src/script/bridge/qscriptqobject.cpp