Qt 4.8: QPdf::ByteStream Class Reference
QPdf::ByteStream Class Reference
#include <qpdf_p.h>
Public Functions
ByteStream (bool fileBacking=false)
ByteStream (QByteArray *ba, bool fileBacking=false)
void clear ()
ByteStream & operator<< (char chr)
ByteStream & operator<< (const char *str)
ByteStream & operator<< (const QByteArray &str)
ByteStream & operator<< (const ByteStream &src)
ByteStream & operator<< (qreal val)
ByteStream & operator<< (int val)
ByteStream & operator<< (const QPointF &p)
QIODevice * stream ()
~ByteStream ()
Static Public Functions
static int chunkSize ()
static int maxMemorySize ()
Protected Functions
void constructor_helper (QIODevice *dev)
void constructor_helper (QByteArray *ba)
Private Functions
void prepareBuffer ()
Properties
QByteArray ba
QIODevice * dev
bool fileBackingActive
bool fileBackingEnabled
bool handleDirty
Detailed Description
Definition at line 80 of file qpdf_p.h.
Constructors and Destructors
ByteStream() [1/2]
QPdf::ByteStream::ByteStream (bool fileBacking = false) explicit
Definition at line 150 of file qpdf.cpp.
             : dev(new QBuffer(&ba)),
             fileBackingEnabled(fileBacking),
             fileBackingActive(false),
             handleDirty(false)
     {
         dev->open(QIODevice::ReadWrite);
     }
ByteStream() [2/2]
QPdf::ByteStream::ByteStream (QByteArray * ba, bool fileBacking = false) explicit
Definition at line 141 of file qpdf.cpp.
             : dev(new QBuffer(byteArray)),
             fileBackingEnabled(fileBacking),
             fileBackingActive(false),
             handleDirty(false)
     {
         dev->open(QIODevice::ReadWrite | QIODevice::Append);
     }
~ByteStream()
QPdf::ByteStream::~ByteStream ()
Definition at line 159 of file qpdf.cpp.
     {
         delete dev;
     }
Functions
chunkSize()
static int QPdf::ByteStream::chunkSize () inline static
Definition at line 102 of file qpdf_p.h.
Referenced by QPSPrintEnginePrivate::emitPages(), operator<<(), prepareBuffer(), and QPdfEnginePrivate::writeCompressed().
 { return 10000000; }
clear()
void QPdf::ByteStream::clear ()
Definition at line 232 of file qpdf.cpp.
Referenced by QPSPrintEnginePrivate::emitPages(), and QPSPrintEnginePrivate::flushPage().
     {
         dev->open(QIODevice::ReadWrite | QIODevice::Truncate);
     }
constructor_helper() [1/2]
void QPdf::ByteStream::constructor_helper (QIODevice * dev) protected
Referenced by chunkSize().
constructor_helper() [2/2]
void QPdf::ByteStream::constructor_helper (QByteArray * ba) protected
Definition at line 237 of file qpdf.cpp.
     {
         delete dev;
         dev = new QBuffer(ba);
         dev->open(QIODevice::ReadWrite);
     }
maxMemorySize()
static int QPdf::ByteStream::maxMemorySize () inline static
Definition at line 101 of file qpdf_p.h.
Referenced by prepareBuffer().
 { return 100000000; }
operator<<() [1/7]
ByteStream & QPdf::ByteStream::operator<< (char chr)
Definition at line 164 of file qpdf.cpp.
     {
         if (handleDirty) prepareBuffer();
         dev->write(&chr, 1);
         return *this;
     }
operator<<() [2/7]
ByteStream & QPdf::ByteStream::operator<< (const char * str)
Definition at line 171 of file qpdf.cpp.
     {
         if (handleDirty) prepareBuffer();
         dev->write(str, strlen(str));
         return *this;
     }
operator<<() [3/7]
ByteStream & QPdf::ByteStream::operator<< (const QByteArray & str)
Definition at line 178 of file qpdf.cpp.
     {
         if (handleDirty) prepareBuffer();
         dev->write(str);
         return *this;
     }
operator<<() [4/7]
ByteStream & QPdf::ByteStream::operator<< (const ByteStream & src)
Definition at line 185 of file qpdf.cpp.
     {
         Q_ASSERT(!src.dev->isSequential());
         if (handleDirty) prepareBuffer();
         // We do play nice here, even though it looks ugly.
         // We save the position and restore it afterwards.
         ByteStream &s = const_cast<ByteStream&>(src);
         qint64 pos = s.dev->pos();
         s.dev->reset();
         while (!s.dev->atEnd()) {
             QByteArray buf = s.dev->read(chunkSize());
             dev->write(buf);
         }
         s.dev->seek(pos);
         return *this;
     }
operator<<() [5/7]
ByteStream & QPdf::ByteStream::operator<< (qreal val)
Definition at line 202 of file qpdf.cpp.
{
         char buf[256];
         qt_real_to_string(val, buf);
         *this << buf;
         return *this;
     }
operator<<() [6/7]
ByteStream & QPdf::ByteStream::operator<< (int val)
Definition at line 209 of file qpdf.cpp.
{
         char buf[256];
         qt_int_to_string(val, buf);
         *this << buf;
         return *this;
     }
operator<<() [7/7]
ByteStream & QPdf::ByteStream::operator<< (const QPointF & p)
Definition at line 216 of file qpdf.cpp.
{
         char buf[256];
         qt_real_to_string(p.x(), buf);
         *this << buf;
         qt_real_to_string(p.y(), buf);
         *this << buf;
         return *this;
     }
prepareBuffer()
void QPdf::ByteStream::prepareBuffer () private
Definition at line 244 of file qpdf.cpp.
Referenced by chunkSize(), and operator<<().
     {
         Q_ASSERT(!dev->isSequential());
         qint64 size = dev->size();
         if (fileBackingEnabled && !fileBackingActive
                 && size > maxMemorySize()) {
             // Switch to file backing.
             QTemporaryFile *newFile = new QTemporaryFile;
             newFile->open();
             dev->reset();
             while (!dev->atEnd()) {
                 QByteArray buf = dev->read(chunkSize());
                 newFile->write(buf);
             }
             delete dev;
             dev = newFile;
             ba.clear();
             fileBackingActive = true;
         }
         if (dev->pos() != size) {
             dev->seek(size);
             handleDirty = false;
         }
     }
stream()
QIODevice * QPdf::ByteStream::stream ()
Definition at line 225 of file qpdf.cpp.
Referenced by QPSPrintEnginePrivate::emitPages(), QPSPrintEnginePrivate::flushPage(), and QPdfEnginePrivate::writePage().
     {
         dev->reset();
         handleDirty = true;
         return dev;
     }
Properties
ba
QByteArray QPdf::ByteStream::ba private
Definition at line 113 of file qpdf_p.h.
Referenced by prepareBuffer().
dev
QIODevice* QPdf::ByteStream::dev private
Definition at line 112 of file qpdf_p.h.
Referenced by ByteStream(), chunkSize(), clear(), constructor_helper(), operator<<(), prepareBuffer(), stream(), and ~ByteStream().
fileBackingActive
bool QPdf::ByteStream::fileBackingActive private
Definition at line 115 of file qpdf_p.h.
Referenced by prepareBuffer().
fileBackingEnabled
bool QPdf::ByteStream::fileBackingEnabled private
Definition at line 114 of file qpdf_p.h.
Referenced by prepareBuffer().
handleDirty
bool QPdf::ByteStream::handleDirty private
Definition at line 116 of file qpdf_p.h.
Referenced by operator<<(), prepareBuffer(), and stream().
The documentation for this class was generated from the following files:
/src/gui/painting/qpdf_p.h
/src/gui/painting/qpdf.cpp