Qt 4.8: QOutputStrategy Class Reference
QOutputStrategy Class Reference abstract
Public Functions
virtual void addFile (const QString &fileName, const QString &mimeType, const QByteArray &bytes)=0
QString createUniqueImageName ()
QOutputStrategy ()
virtual ~QOutputStrategy ()
Public Variables
QIODevice * contentStream
int counter
Detailed Description
Definition at line 72 of file qtextodfwriter.cpp.
Constructors and Destructors
QOutputStrategy()
QOutputStrategy::QOutputStrategy () inline
Definition at line 74 of file qtextodfwriter.cpp.
 : contentStream(0), counter(1) { }
~QOutputStrategy()
virtual QOutputStrategy::~QOutputStrategy () inline virtual
Definition at line 75 of file qtextodfwriter.cpp.
 {}
Functions
addFile()
virtual void QOutputStrategy::addFile (const QString & fileName, const QString & mimeType, const QByteArray & bytes) pure virtual
Implemented in QZipStreamStrategy, and QXmlStreamStrategy.
Referenced by QZipStreamStrategy::addFile(), QZipStreamStrategy::QZipStreamStrategy(), and ~QOutputStrategy().
createUniqueImageName()
QString QOutputStrategy::createUniqueImageName () inline
Definition at line 78 of file qtextodfwriter.cpp.
     {
         return QString::fromLatin1("Pictures/Picture%1").arg(counter++);
     }
Properties
contentStream
QIODevice* QOutputStrategy::contentStream
Definition at line 83 of file qtextodfwriter.cpp.
Referenced by QXmlStreamStrategy::QXmlStreamStrategy(), QZipStreamStrategy::QZipStreamStrategy(), QTextOdfWriter::writeAll(), and QXmlStreamStrategy::~QXmlStreamStrategy().
counter
int QOutputStrategy::counter
Definition at line 84 of file qtextodfwriter.cpp.
Referenced by createUniqueImageName().
The documentation for this class was generated from the following file:
/src/gui/text/qtextodfwriter.cpp