Qt 4.8: QApplicationPrivate Class Reference
QApplicationPrivate Class Reference
#include <qapplication_p.h>
Public Types
enum KeyPlatform {
KB_Win = 1, KB_Mac = 2, KB_X11 = 4, KB_KDE = 8,
KB_Gnome = 16, KB_CDE = 32, KB_S60 = 64, KB_All = 0xffff
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
void _q_alertTimeOut ()
void appendTouchPoint (const QTouchEvent::TouchPoint &touchPoint)
QString appName () const
bool canQuit ()
void cleanupMultitouch ()
void cleanupMultitouch_sys ()
void closePopup (QWidget *popup)
void construct (Display *dpy=0, Qt::HANDLE visual=0, Qt::HANDLE cmap=0)
void createEventDispatcher ()
int findClosestTouchPointId (const QPointF &screenPos)
QPixmap getPixmapCursor (Qt::CursorShape cshape)
void initialize ()
Initializes the QApplication object, called from the constructors.
void initializeMultitouch ()
void initializeMultitouch_sys ()
bool inPopupMode () const
QRect maxWindowRect (const QScreen *screen) const
bool notify_helper (QObject *receiver, QEvent *e)
void openPopup (QWidget *popup)
void process_cmdline ()
QApplicationPrivate (int &argc, char **argv, QApplication::Type type, int flags)
void removeTouchPoint (int touchPointId)
void sendSyntheticEnterLeave (QWidget *widget)
void setMaxWindowRect (const QScreen *screen, int screenNo, const QRect &rect)
void setScreenTransformation (QScreen *screen, int screenNo, int transformation)
bool translateTouchEvent (const MSG &msg)
~QApplicationPrivate ()
Public Functions inherited from QCoreApplicationPrivate
void appendApplicationPathToLibraryPaths (void)
void checkReceiverThread (QObject *receiver)
bool notify_helper (QObject *, QEvent *)
void processCommandLineArguments ()
QCoreApplicationPrivate (int &aargc, char **aargv, uint flags)
bool sendThroughApplicationEventFilters (QObject *, QEvent *)
bool sendThroughObjectEventFilters (QObject *, QEvent *)
~QCoreApplicationPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static void applyX11SpecificCommandLineArguments (QWidget *main_widget)
static uint currentPlatform ()
static QString desktopStyleKey ()
static void dispatchEnterLeave (QWidget *enter, QWidget *leave)
static void emitLastWindowClosed ()
static void enterModal (QWidget *)
static void enterModal_sys (QWidget *)
static QWidget * focusNextPrevChild_helper (QWidget *toplevel, bool next)
internal Helper function that returns the new focus widget, but does not set the focus reason.
static OSStatus globalAppleEventProcessor (const AppleEvent *, AppleEvent *, long)
static OSStatus globalEventProcessor (EventHandlerCallRef, EventRef, void *)
static QGraphicsSystem * graphicsSystem ()
static void initializeWidgetPaletteHash ()
static QApplicationPrivate * instance ()
static bool isBlockedByModal (QWidget *widget)
Returns true if widget is blocked by a modal window.
static void leaveModal (QWidget *)
static void leaveModal_sys (QWidget *)
static bool modalState ()
static QWidget * pickMouseReceiver (QWidget *candidate, const QPoint &globalPos, QPoint &pos, QEvent::Type type, Qt::MouseButtons buttons, QWidget *buttonDown, QWidget *alienWidget)
static bool qt_mac_apply_settings ()
static void reset_instance_pointer ()
static bool sendMouseEvent (QWidget *receiver, QMouseEvent *event, QWidget *alienWidget, QWidget *native, QWidget **buttonDown, QPointer< QWidget > &lastMouseReceiver, bool spontaneous=true)
static void setFocusWidget (QWidget *focus, Qt::FocusReason reason)
static void setPalette_helper (const QPalette &palette, const char *className, bool clearWidgetPaletteHash)
static void setSystemFont (const QFont &font)
static void setSystemPalette (const QPalette &pal)
static OSStatus tabletProximityCallback (EventHandlerCallRef, EventRef, void *)
static void translateRawTouchEvent (QWidget *widget, QTouchEvent::DeviceType deviceType, const QList< QTouchEvent::TouchPoint > &touchPoints)
static bool tryModalHelper (QWidget *widget, QWidget **rettop=0)
static QWidget * tryModalHelper_sys (QWidget *top)
static void updateTouchPointsForWidget (QWidget *widget, QTouchEvent *touchEvent)
static bool x11_apply_settings ()
static void x11_initialize_style ()
Static Public Functions inherited from QCoreApplicationPrivate
static bool checkInstance (const char *method)
static bool isTranslatorInstalled (QTranslator *translator)
static QString macMenuBarName ()
static QThread * mainThread ()
static QString qmljsDebugArguments ()
static void removePostedEvent (QEvent *)
Removes event from the queue of posted events, and emits a warning message if appropriate.
static void removePostedTimerEvent (QObject *object, int timerId)
static void sendPostedEvents (QObject *receiver, int event_type, QThreadData *data)
static bool testAttribute (uint flag)
static QSettings * trolltechConf ()
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QHash< QWidget *, QTimer * > alertTimerHash
QMap< int, QTouchEvent::TouchPoint > appCurrentTouchPoints
PtrBeginPanningFeedback BeginPanningFeedback
PtrCloseGestureInfoHandle CloseGestureInfoHandle
QPixmap * copy_cursor
QList< QCursor > cursor_list
QMap< WId, QDirectPainter * > * directPainters
PtrEndPanningFeedback EndPanningFeedback
QGestureManager * gestureManager
QWidget * gestureWidget
PtrGetGestureConfig GetGestureConfig
PtrGetGestureExtraArgs GetGestureExtraArgs
PtrGetGestureInfo GetGestureInfo
QPoint hoverGlobalPos
QPixmap * ignore_cursor
bool is_session_restored
QPointer< QWSManager > last_manager
QPixmap * link_cursor
QPixmap * move_cursor
QWSServerCleaner qwsServerCleaner
QList< QGraphicsScene * > scene_list
QString session_id
QString session_key
QSessionManager * session_manager
PtrSetGestureConfig SetGestureConfig
QShortcutMap shortcutMap
QBasicTimer toolTipFallAsleep
QPoint toolTipGlobalPos
QPoint toolTipPos
QBasicTimer toolTipWakeUp
QPointer< QWidget > toolTipWidget
QHash< DWORD, int > touchInputIDToTouchPointID
PtrUpdatePanningFeedback UpdatePanningFeedback
QMap< int, QWeakPointer< QWidget > > widgetForTouchPointId
Public Variables inherited from QCoreApplicationPrivate
bool aboutToQuitEmitted
uint application_type
QString applicationName
int & argc
char ** argv
QString cachedApplicationDirPath
QString cachedApplicationFilePath
QCoreApplication::EventFilter eventFilter
bool in_exec
QTranslatorList translators
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Static Public Variables
static QWidget * active_window = 0
static bool animate_combo = false
static bool animate_menu = false
static bool animate_toolbox = false
static bool animate_tooltip = false
static bool animate_ui = true
static int app_cspec = QApplication::NormalColor
static QIcon * app_icon = 0
static QPalette * app_pal = 0
static QSize app_strut = QSize(0,0)
static QStyle * app_style = 0
static int autoMaximizeThreshold = -1
static bool autoSipEnabled = false
static PtrCloseTouchInputHandle CloseTouchInputHandle = 0
static int cursor_flash_time = 1000
static bool fade_menu = false
static bool fade_tooltip = false
static QWidget * focus_widget = 0
static PtrGetTouchInputInfo GetTouchInputInfo = 0
static QGraphicsSystem * graphics_system = 0
static QString graphics_system_name
static bool HasTouchSupport = false
static QWidget * hidden_focus_widget = 0
static QInputContext * inputContext = 0
static int keyboard_input_time = 400
static QPointer< QWidget > leaveAfterRelease = 0
static bool load_testability = false
static QWidget * main_widget = 0
static Qt::KeyboardModifiers modifier_buttons = Qt::NoModifier
static Qt::MouseButtons mouse_buttons = Qt::NoButton
static int mouse_double_click_time = 400
static bool native_modal_dialog_active
static bool obey_desktop_settings = true
static QWidgetList * popupWidgets = 0
static bool quitOnLastWindowClosed = true
static PtrRegisterTouchWindow RegisterTouchWindow = 0
static bool runtime_graphics_system = false
static QFont * set_font = 0
static QPalette * set_pal = 0
static QString styleOverride
static QString styleSheet
static QFont * sys_font = 0
static QPalette * sys_pal = 0
static int wheel_scroll_lines
static bool widgetCount = false
Static Public Variables inherited from QCoreApplicationPrivate
static int app_compile_version = 0x040000
static uint attribs
static QAbstractEventDispatcher * eventDispatcher = 0
static bool is_app_closing = false
static bool is_app_running = false
static QThread * theMainThread = 0
Static Private Functions
static void giveFocusAccordingToFocusPolicy (QWidget *w, Qt::FocusPolicy focusPolicy, Qt::FocusReason focusReason)
static bool isAlien (QWidget *)
static bool shouldSetFocus (QWidget *w, Qt::FocusPolicy policy)
Properties
QMap< const QScreen *, QRect > maxWindowRects
Static Private Attributes
static QFont * app_font = 0
static QApplicationPrivate * self = 0
Detailed Description
Definition at line 286 of file qapplication_p.h.
Enumerations
KeyPlatform
enum QApplicationPrivate::KeyPlatform
Enumerator
KB_Win
KB_Mac
KB_X11
KB_KDE
KB_Gnome
KB_CDE
KB_S60
KB_All
Definition at line 356 of file qapplication_p.h.
                      {
         KB_Win = 1,
         KB_Mac = 2,
         KB_X11 = 4,
         KB_KDE = 8,
         KB_Gnome = 16,
         KB_CDE = 32,
         KB_S60 = 64,
         KB_All = 0xffff
     };
Constructors and Destructors
QApplicationPrivate()
QApplicationPrivate::QApplicationPrivate (int & argc, char ** argv, QApplication::Type type, int flags)
Definition at line 181 of file qapplication.cpp.
     : QCoreApplicationPrivate(argc, argv, flags)
 {
     application_type = type;
     qt_appType = type;
 #ifndef QT_NO_SESSIONMANAGER
     is_session_restored = false;
 #endif
     quitOnLastWindowClosed = true;
 #ifdef QT3_SUPPORT
     qt_compat_used = 0;
     qt_compat_resolved = 0;
     qt_tryAccelEvent = 0;
     qt_tryComposeUnicode = 0;
     qt_dispatchAccelEvent = 0;
 #endif
 #if defined(Q_WS_QWS) && !defined(QT_NO_DIRECTPAINTER)
     directPainters = 0;
 #endif
 #ifndef QT_NO_GESTURES
     gestureManager = 0;
     gestureWidget = 0;
 #endif // QT_NO_GESTURES
 #if defined(Q_WS_X11) || defined(Q_WS_WIN)
     move_cursor = 0;
     copy_cursor = 0;
     link_cursor = 0;
 #endif
 #if defined(Q_WS_WIN)
     ignore_cursor = 0;
 #endif
     if (!self)
         self = this;
 }
~QApplicationPrivate()
QApplicationPrivate::~QApplicationPrivate ()
Definition at line 222 of file qapplication.cpp.
 {
     if (self == this)
         self = 0;
 }
Functions
_q_alertTimeOut()
void QApplicationPrivate::_q_alertTimeOut ()
Definition at line 2774 of file qapplication_mac.mm.
Referenced by QApplication::syncX().
 {
     if (QTimer *timer = qobject_cast<QTimer *>(q_func()->sender())) {
         QHash<QWidget *, QTimer *>::iterator it = alertTimerHash.begin();
         while (it != alertTimerHash.end()) {
             if (it.value() == timer) {
                 alertTimerHash.erase(it);
                 timer->deleteLater();
                 break;
             }
             ++it;
         }
         if (alertTimerHash.isEmpty()) {
             qt_mac_cancel_notification();
         }
     }
 }
appendTouchPoint()
void QApplicationPrivate::appendTouchPoint (const QTouchEvent::TouchPoint & touchPoint)
applyX11SpecificCommandLineArguments()
void QApplicationPrivate::applyX11SpecificCommandLineArguments (QWidget * main_widget) static
Definition at line 2856 of file qapplication_x11.cpp.
Referenced by qt_nograb(), and QWidget::setVisible().
 {
     static bool beenHereDoneThat = false;
     if (beenHereDoneThat)
         return;
     beenHereDoneThat = true;
     Q_ASSERT(main_widget->testAttribute(Qt::WA_WState_Created));
     if (mwTitle) {
         XStoreName(X11->display, main_widget->effectiveWinId(), (char*)mwTitle);
         QByteArray net_wm_name = QString::fromLocal8Bit(mwTitle).toUtf8();
         XChangeProperty(X11->display, main_widget->effectiveWinId(), ATOM(_NET_WM_NAME), ATOM(UTF8_STRING), 8,
                         PropModeReplace, (unsigned char *)net_wm_name.data(), net_wm_name.size());
     }
     if (mwGeometry) { // parse geometry
         int x, y;
         int w, h;
         int m = XParseGeometry((char*)mwGeometry, &x, &y, (uint*)&w, (uint*)&h);
         QSize minSize = main_widget->minimumSize();
         QSize maxSize = main_widget->maximumSize();
         if ((m & XValue) == 0)
             x = main_widget->geometry().x();
         if ((m & YValue) == 0)
             y = main_widget->geometry().y();
         if ((m & WidthValue) == 0)
             w = main_widget->width();
         if ((m & HeightValue) == 0)
             h = main_widget->height();
         w = qMin(w,maxSize.width());
         h = qMin(h,maxSize.height());
         w = qMax(w,minSize.width());
         h = qMax(h,minSize.height());
         if ((m & XNegative)) {
             x = QApplication::desktop()->width()  + x - w;
         }
         if ((m & YNegative)) {
             y = QApplication::desktop()->height() + y - h;
         }
         main_widget->setGeometry(x, y, w, h);
     }
 }
appName()
QString QApplicationPrivate::appName () const virtual
Reimplemented from QCoreApplicationPrivate.
Definition at line 1097 of file qapplication_mac.mm.
Referenced by alert_widget(), qt_cleanup(), qt_init(), and qt_wstate_iconified().
 {
     static QString applName;
     if (applName.isEmpty()) {
         applName = QCoreApplicationPrivate::macMenuBarName();
         ProcessSerialNumber psn;
         if (applName.isEmpty() && qt_is_gui_used && GetCurrentProcess(&psn) == noErr) {
             QCFString cfstr;
             CopyProcessName(&psn, &cfstr);
             applName = cfstr;
         }
     }
     return applName;
 }
canQuit()
bool QApplicationPrivate::canQuit ()
Definition at line 3067 of file qapplication_mac.mm.
 {
 #ifndef QT_MAC_USE_COCOA
     return true;
 #else
     Q_Q(QApplication);
 #ifdef QT_MAC_USE_COCOA
     [[NSApp mainMenu] cancelTracking];
 #else
     HiliteMenu(0);
 #endif
     bool handle_quit = true;
     if (QApplicationPrivate::modalState() && [[[[QT_MANGLE_NAMESPACE(QCocoaApplicationDelegate) sharedDelegate]
                                                    menuLoader] quitMenuItem] isEnabled]) {
         int visible = 0;
         const QWidgetList tlws = QApplication::topLevelWidgets();
         for(int i = 0; i < tlws.size(); ++i) {
             if (tlws.at(i)->isVisible())
                 ++visible;
         }
         handle_quit = (visible <= 1);
     }
     if (handle_quit) {
         QCloseEvent ev;
         QApplication::sendSpontaneousEvent(q, &ev);
         if (ev.isAccepted()) {
             return true;
         }
     }
     return false;
 #endif
 }
cleanupMultitouch()
void QApplicationPrivate::cleanupMultitouch ()
Definition at line 6009 of file qapplication.cpp.
 {
     cleanupMultitouch_sys();
     widgetForTouchPointId.clear();
     appCurrentTouchPoints.clear();
 }
cleanupMultitouch_sys()
void QApplicationPrivate::cleanupMultitouch_sys ()
Definition at line 3172 of file qapplication_mac.mm.
Referenced by QSessionManager::cancel(), and QApplication::setArgs().
 { }
closePopup()
void QApplicationPrivate::closePopup (QWidget * popup)
Warning
This function is not part of the public interface.
Definition at line 2697 of file qapplication_mac.mm.
Referenced by qt_try_modal().
 {
     Q_Q(QApplication);
     if (!QApplicationPrivate::popupWidgets)
         return;
     QApplicationPrivate::popupWidgets->removeAll(popup);
     if (popup == qt_button_down)
         qt_button_down = 0;
     if (QApplicationPrivate::popupWidgets->isEmpty()) {  // this was the last popup
         delete QApplicationPrivate::popupWidgets;
         QApplicationPrivate::popupWidgets = 0;
         // Special case for Tool windows: since they are activated and deactived together
         // with a normal window they never become the QApplicationPrivate::active_window.
         QWidget *appFocusWidget = QApplication::focusWidget();
         if (appFocusWidget && appFocusWidget->window()->windowType() == Qt::Tool) {
             appFocusWidget->setFocus(Qt::PopupFocusReason);
         } else if (QApplicationPrivate::active_window) {
             if (QWidget *fw = QApplicationPrivate::active_window->focusWidget()) {
                 if (fw != QApplication::focusWidget()) {
                     fw->setFocus(Qt::PopupFocusReason);
                 } else {
                     QFocusEvent e(QEvent::FocusIn, Qt::PopupFocusReason);
                     q->sendEvent(fw, &e);
                 }
             }
         }
     } else {
         // popups are not focus-handled by the window system (the
         // first popup grabbed the keyboard), so we have to do that
         // manually: A popup was closed, so the previous popup gets
         // the focus.
         QWidget* aw = QApplicationPrivate::popupWidgets->last();
         if (QWidget *fw = aw->focusWidget())
             fw->setFocus(Qt::PopupFocusReason);
     }
 }
construct()
void QApplicationPrivate::construct (Display * dpy = 0, Qt::HANDLE visual = 0, Qt::HANDLE cmap = 0)
Warning
This function is not part of the public interface.
Definition at line 815 of file qapplication.cpp.
 {
     initResources();
     qt_is_gui_used = (qt_appType != QApplication::Tty);
     process_cmdline();
     // the environment variable has the lowest precedence of runtime graphicssystem switches
     if (graphics_system_name.isEmpty())
         graphics_system_name = QString::fromLocal8Bit(qgetenv("QT_GRAPHICSSYSTEM"));
 #if defined(Q_WS_X11) && !defined(QT_NO_EGL)
     if (graphics_system_name.isEmpty()) {
         bool linksWithMeeGoTouch = dl_iterate_phdr(qt_matchLibraryName, const_cast<char *>("libmeegotouchcore"));
         bool linksWithMeeGoGraphicsSystemHelper = dl_iterate_phdr(qt_matchLibraryName, const_cast<char *>("libQtMeeGoGraphicsSystemHelper"));
         if (linksWithMeeGoTouch && !linksWithMeeGoGraphicsSystemHelper) {
             qWarning("Running non-meego graphics system enabled  MeeGo touch, forcing native graphicssystem\n");
             graphics_system_name = QLatin1String("native");
         }
     }
 #endif
     // Must be called before initialize()
     qt_init(this, qt_appType
 #ifdef Q_WS_X11
             , dpy, visual, cmap
 #endif
             );
     initialize();
     eventDispatcher->startingUp();
 #ifdef QT_EVAL
     extern void qt_gui_eval_init(uint);
     qt_gui_eval_init(application_type);
 #endif
 #if defined(Q_OS_SYMBIAN) && !defined(QT_NO_SYSTEMLOCALE)
     symbianInit();
 #endif
 #ifndef QT_NO_LIBRARY
     if(load_testability) {
         QLibrary testLib(QLatin1String("qttestability"));
         if (testLib.load()) {
             typedef void (*TasInitialize)(void);
             TasInitialize initFunction = (TasInitialize)testLib.resolve("qt_testability_init");
 #ifdef Q_OS_SYMBIAN
             // resolving method by name does not work on Symbian OS so need to use ordinal
             if(!initFunction) {
                 initFunction = (TasInitialize)testLib.resolve("1");
             }
 #endif
             if (initFunction) {
                 initFunction();
             } else {
                 qCritical("Library qttestability resolve failed!");
             }
         } else {
             qCritical("Library qttestability load failed!");
         }
     }
     //make sure the plugin is loaded
     if (qt_is_gui_used)
         qt_guiPlatformPlugin();
 #endif
 #ifdef Q_OS_SYMBIAN
     symbianHandleLiteModeStartup();
 #endif
 }
createEventDispatcher()
void QApplicationPrivate::createEventDispatcher () virtual
Reimplemented from QCoreApplicationPrivate.
Definition at line 968 of file qapplication_mac.mm.
Referenced by QETWidget::doDeferredMap(), QGuiEventDispatcherWin32::processEvents(), and QETWidget::raiseOnClick().
 {
     Q_Q(QApplication);
     if (q->type() != QApplication::Tty)
         eventDispatcher = new QEventDispatcherMac(q);
     else
         eventDispatcher = new QEventDispatcherUNIX(q);
 }
currentPlatform()
uint QApplicationPrivate::currentPlatform () static
Definition at line 5761 of file qapplication.cpp.
Referenced by QKeySequence::keyBindings(), and QKeyEvent::matches().
{
     uint platform = KB_Win;
 #ifdef Q_WS_MAC
     platform = KB_Mac;
 #elif defined Q_WS_X11
     platform = KB_X11;
     if (X11->desktopEnvironment == DE_KDE)
         platform |= KB_KDE;
     if (X11->desktopEnvironment == DE_GNOME)
         platform |= KB_Gnome;
     if (X11->desktopEnvironment == DE_CDE)
         platform |= KB_CDE;
 #elif defined(Q_OS_SYMBIAN)
     platform = KB_S60;
 #endif
     return platform;
 }
desktopStyleKey()
QString QApplicationPrivate::desktopStyleKey () static
Warning
This function is not part of the public interface.
Definition at line 2136 of file qapplication.cpp.
Referenced by QProxyStylePrivate::ensureBaseStyle(), and QApplication::style().
 {
     return qt_guiPlatformPlugin()->styleName();
 }
dispatchEnterLeave()
void QApplicationPrivate::dispatchEnterLeave (QWidget * enter, QWidget * leave) static
Warning
This function is not part of the public interface.
Creates the proper Enter/Leave event when widget enter is entered and widget leave is left.
Definition at line 2778 of file qapplication.cpp.
Referenced by flipPoint(), globalEventProcessor(), QWidgetPrivate::hide_sys(), QGraphicsProxyWidget::hoverLeaveEvent(), QGraphicsProxyWidget::hoverMoveEvent(), qt_cleanup(), QtWndProc(), QApplication::qwsProcessEvent(), QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent(), QWidgetPrivate::show_sys(), QETWidget::translateMouseEvent(), QApplication::x11EventFilter(), and QApplication::x11ProcessEvent().
{
 #if 0
     if (leave) {
         QEvent e(QEvent::Leave);
         QApplication::sendEvent(leave, & e);
     }
     if (enter) {
         QEvent e(QEvent::Enter);
         QApplication::sendEvent(enter, & e);
     }
     return;
 #endif
     QWidget* w ;
     if ((!enter && !leave) || (enter == leave))
         return;
 #ifdef ALIEN_DEBUG
     qDebug() << "QApplicationPrivate::dispatchEnterLeave, ENTER:" << enter << "LEAVE:" << leave;
 #endif
     QWidgetList leaveList;
     QWidgetList enterList;
     bool sameWindow = leave && enter && leave->window() == enter->window();
     if (leave && !sameWindow) {
         w = leave;
         do {
             leaveList.append(w);
         } while (!w->isWindow() && (w = w->parentWidget()));
     }
     if (enter && !sameWindow) {
         w = enter;
         do {
             enterList.prepend(w);
         } while (!w->isWindow() && (w = w->parentWidget()));
     }
     if (sameWindow) {
         int enterDepth = 0;
         int leaveDepth = 0;
         w = enter;
         while (!w->isWindow() && (w = w->parentWidget()))
             enterDepth++;
         w = leave;
         while (!w->isWindow() && (w = w->parentWidget()))
             leaveDepth++;
         QWidget* wenter = enter;
         QWidget* wleave = leave;
         while (enterDepth > leaveDepth) {
             wenter = wenter->parentWidget();
             enterDepth--;
         }
         while (leaveDepth > enterDepth) {
             wleave = wleave->parentWidget();
             leaveDepth--;
         }
         while (!wenter->isWindow() && wenter != wleave) {
             wenter = wenter->parentWidget();
             wleave = wleave->parentWidget();
         }
         w = leave;
         while (w != wleave) {
             leaveList.append(w);
             w = w->parentWidget();
         }
         w = enter;
         while (w != wenter) {
             enterList.prepend(w);
             w = w->parentWidget();
         }
     }
     QEvent leaveEvent(QEvent::Leave);
     for (int i = 0; i < leaveList.size(); ++i) {
         w = leaveList.at(i);
         if (!QApplication::activeModalWidget() || QApplicationPrivate::tryModalHelper(w, 0)) {
 #if defined(Q_WS_WIN) || defined(Q_WS_X11) || defined(Q_WS_MAC)
             if (leaveAfterRelease == w)
                 leaveAfterRelease = 0;
 #endif
             QApplication::sendEvent(w, &leaveEvent);
             if (w->testAttribute(Qt::WA_Hover) &&
                 (!QApplication::activePopupWidget() || QApplication::activePopupWidget() == w->window())) {
                 Q_ASSERT(instance());
                 QHoverEvent he(QEvent::HoverLeave, QPoint(-1, -1), w->mapFromGlobal(QApplicationPrivate::instance()->hoverGlobalPos));
                 qApp->d_func()->notify_helper(w, &he);
             }
         }
     }
     QPoint posEnter = QCursor::pos();
     QEvent enterEvent(QEvent::Enter);
     for (int i = 0; i < enterList.size(); ++i) {
         w = enterList.at(i);
         if (!QApplication::activeModalWidget() || QApplicationPrivate::tryModalHelper(w, 0)) {
             QApplication::sendEvent(w, &enterEvent);
             if (w->testAttribute(Qt::WA_Hover) &&
                 (!QApplication::activePopupWidget() || QApplication::activePopupWidget() == w->window())) {
                 QHoverEvent he(QEvent::HoverEnter, w->mapFromGlobal(posEnter), QPoint(-1, -1));
                 qApp->d_func()->notify_helper(w, &he);
             }
         }
     }
 #ifndef QT_NO_CURSOR
     // Update cursor for alien/graphics widgets.
     const bool enterOnAlien = (enter && (isAlien(enter) || enter->testAttribute(Qt::WA_DontShowOnScreen)));
 #if defined(Q_WS_X11) || defined(Q_WS_QPA)
     //Whenever we leave an alien widget on X11, we need to reset its nativeParentWidget()'s cursor.
     // This is not required on Windows as the cursor is reset on every single mouse move.
     QWidget *parentOfLeavingCursor = 0;
     for (int i = 0; i < leaveList.size(); ++i) {
         w = leaveList.at(i);
         if (!isAlien(w))
             break;
         if (w->testAttribute(Qt::WA_SetCursor)) {
             QWidget *parent = w->parentWidget();
             while (parent && parent->d_func()->data.in_destructor)
                 parent = parent->parentWidget();
             parentOfLeavingCursor = parent;
             //continue looping, we need to find the downest alien widget with a cursor.
             // (downest on the screen)
         }
     }
     //check that we will not call qt_x11_enforce_cursor twice with the same native widget
     if (parentOfLeavingCursor && (!enterOnAlien
         || parentOfLeavingCursor->effectiveWinId() != enter->effectiveWinId())) {
 #ifndef QT_NO_GRAPHICSVIEW
         if (!parentOfLeavingCursor->window()->graphicsProxyWidget())
 #endif
         {
 #if defined(Q_WS_X11)
             qt_x11_enforce_cursor(parentOfLeavingCursor,true);
 #elif defined(Q_WS_QPA)
             if (enter == QApplication::desktop()) {
                 qt_qpa_set_cursor(enter, true);
             } else {
                 qt_qpa_set_cursor(parentOfLeavingCursor, true);
             }
 #endif
         }
     }
 #endif
     if (enterOnAlien) {
         QWidget *cursorWidget = enter;
         while (!cursorWidget->isWindow() && !cursorWidget->isEnabled())
             cursorWidget = cursorWidget->parentWidget();
         if (!cursorWidget)
             return;
 #ifndef QT_NO_GRAPHICSVIEW
         if (cursorWidget->window()->graphicsProxyWidget()) {
             QWidgetPrivate::nearestGraphicsProxyWidget(cursorWidget)->setCursor(cursorWidget->cursor());
         } else
 #endif
         {
 #if defined(Q_WS_WIN)
             qt_win_set_cursor(cursorWidget, true);
 #elif defined(Q_WS_X11)
             qt_x11_enforce_cursor(cursorWidget, true);
 #elif defined(Q_OS_SYMBIAN)
             qt_symbian_set_cursor(cursorWidget, true);
 #elif defined(Q_WS_QPA)
             qt_qpa_set_cursor(cursorWidget, true);
 #endif
         }
     }
 #endif
 }
emitLastWindowClosed()
void QApplicationPrivate::emitLastWindowClosed () static
Definition at line 5338 of file qapplication.cpp.
Referenced by QWidgetPrivate::close_helper().
 {
     if (qApp && qApp->d_func()->in_exec) {
         if (QApplicationPrivate::quitOnLastWindowClosed) {
             // get ready to quit, this event might be removed if the
             // event loop is re-entered, however
             QApplication::postEvent(qApp, new QEvent(QEvent::Quit));
         }
         emit qApp->lastWindowClosed();
     }
 }
enterModal()
void QApplicationPrivate::enterModal (QWidget * widget) static
Warning
This function is not part of the public interface.
Definition at line 3051 of file qapplication.cpp.
Referenced by QPageSetupDialogPrivate::openCarbonPageLayout(), QPrintDialogPrivate::openCarbonPrintPanel(), QGtkStylePrivate::openDirectory(), QGtkStylePrivate::openFilename(), QGtkStylePrivate::openFilenames(), QPrintDialogPrivate::openWindowsPrintDialogModally(), QAxClientSite::qt_metacall(), qt_win_get_existing_directory(), qt_win_get_open_file_name(), qt_win_get_open_file_names(), qt_win_get_save_file_name(), QGtkStylePrivate::saveFilename(), and QWidgetPrivate::show_helper().
 {
     QSet<QWidget*> blocked;
     QList<QWidget*> windows = QApplication::topLevelWidgets();
     for (int i = 0; i < windows.count(); ++i) {
         QWidget *window = windows.at(i);
         if (window->windowType() != Qt::Tool && isBlockedByModal(window))
             blocked.insert(window);
     }
     enterModal_sys(widget);
     windows = QApplication::topLevelWidgets();
     QEvent e(QEvent::WindowBlocked);
     for (int i = 0; i < windows.count(); ++i) {
         QWidget *window = windows.at(i);
         if (!blocked.contains(window) && window->windowType() != Qt::Tool && isBlockedByModal(window))
             QApplication::sendEvent(window, &e);
     }
 }
enterModal_sys()
void QApplicationPrivate::enterModal_sys (QWidget * widget) static
Definition at line 1511 of file qapplication_mac.mm.
Referenced by qt_try_modal(), QtWndProc(), QApplication::qwsSetCustomColors(), and QApplication::x11EventFilter().
 {
 #ifdef DEBUG_MODAL_EVENTS
     Q_ASSERT(widget);
     qDebug("Entering modal state with %s::%s::%p (%d)", widget->metaObject()->className(), widget->objectName().toLocal8Bit().constData(),
             widget, qt_modal_stack ? (int)qt_modal_stack->count() : -1);
 #endif
     if (!qt_modal_stack)
         qt_modal_stack = new QWidgetList;
     dispatchEnterLeave(0, qt_last_mouse_receiver);
     qt_last_mouse_receiver = 0;
     qt_modal_stack->insert(0, widget);
     if (!app_do_modal)
         qt_event_request_menubarupdate();
     app_do_modal = true;
     qt_button_down = 0;
 #ifdef QT_MAC_USE_COCOA
     if (!qt_mac_is_macsheet(widget))
         QEventDispatcherMacPrivate::beginModalSession(widget);
 #endif
 }
findClosestTouchPointId()
int QApplicationPrivate::findClosestTouchPointId (const QPointF & screenPos)
Definition at line 6017 of file qapplication.cpp.
Referenced by translateRawTouchEvent().
 {
     int closestTouchPointId = -1;
     qreal closestDistance = qreal(0.);
     foreach (const QTouchEvent::TouchPoint &touchPoint, appCurrentTouchPoints) {
         qreal distance = QLineF(screenPos, touchPoint.screenPos()).length();
         if (closestTouchPointId == -1 || distance < closestDistance) {
             closestTouchPointId = touchPoint.id();
             closestDistance = distance;
         }
     }
     return closestTouchPointId;
 }
focusNextPrevChild_helper()
QWidget * QApplicationPrivate::focusNextPrevChild_helper (QWidget * toplevel, bool next) static
internal Helper function that returns the new focus widget, but does not set the focus reason.
Returns 0 if a new focus widget could not be found. Shared with QGraphicsProxyWidgetPrivate::findFocusChild()
Definition at line 2739 of file qapplication.cpp.
Referenced by QWidget::focusNextPrevChild(), and QApplication::setActiveWindow().
 {
     uint focus_flag = qt_tab_all_widgets ? Qt::TabFocus : Qt::StrongFocus;
     QWidget *f = toplevel->focusWidget();
     if (!f)
         f = toplevel;
     QWidget *w = f;
     QWidget *test = f->d_func()->focus_next;
     while (test && test != f) {
         if ((test->focusPolicy() & focus_flag) == focus_flag
             && !(test->d_func()->extra && test->d_func()->extra->focus_proxy)
             && test->isVisibleTo(toplevel) && test->isEnabled()
             && !(w->windowType() == Qt::SubWindow && !w->isAncestorOf(test))
             && (toplevel->windowType() != Qt::SubWindow || toplevel->isAncestorOf(test))) {
             w = test;
             if (next)
                 break;
         }
         test = test->d_func()->focus_next;
     }
     if (w == f) {
         if (qt_in_tab_key_event) {
             w->window()->setAttribute(Qt::WA_KeyboardFocusChange);
             w->update();
         }
         return 0;
     }
     return w;
 }
getPixmapCursor()
QPixmap QApplicationPrivate::getPixmapCursor (Qt::CursorShape cshape)
Definition at line 6404 of file qapplication.cpp.
Referenced by create32BitCursor(), QDragManager::dragCursor(), and QCursor::QCursor().
 {
 #if defined(Q_WS_X11) || defined(Q_WS_WIN)
     if (!move_cursor) {
         move_cursor = new QPixmap((const char **)move_xpm);
         copy_cursor = new QPixmap((const char **)copy_xpm);
         link_cursor = new QPixmap((const char **)link_xpm);
 #ifdef Q_WS_WIN
         ignore_cursor = new QPixmap((const char **)ignore_xpm);
 #endif
     }
     switch (cshape) {
     case Qt::DragMoveCursor:
         return *move_cursor;
     case Qt::DragCopyCursor:
         return *copy_cursor;
     case Qt::DragLinkCursor:
         return *link_cursor;
 #ifdef Q_WS_WIN
     case Qt::ForbiddenCursor:
         return *ignore_cursor;
 #endif
     default:
         break;
     }
 #else
     Q_UNUSED(cshape);
 #endif
     return QPixmap();
 }
giveFocusAccordingToFocusPolicy()
void QApplicationPrivate::giveFocusAccordingToFocusPolicy (QWidget * w, Qt::FocusPolicy focusPolicy, Qt::FocusReason focusReason) static private
Definition at line 5815 of file qapplication.cpp.
Referenced by QApplication::notify().
 {
     QWidget *focusWidget = widget;
     while (focusWidget) {
         if (focusWidget->isEnabled()
             && QApplicationPrivate::shouldSetFocus(focusWidget, focusPolicy)) {
             focusWidget->setFocus(focusReason);
             break;
         }
         if (focusWidget->isWindow())
             break;
         focusWidget = focusWidget->parentWidget();
     }
 }
globalAppleEventProcessor()
OSStatus QApplicationPrivate::globalAppleEventProcessor (const AppleEvent * ae, AppleEvent * , long handlerRefcon) static
Definition at line 2575 of file qapplication_mac.mm.
Referenced by qt_init().
 {
     QApplication *app = (QApplication *)handlerRefcon;
     bool handled_event=false;
     OSType aeID=typeWildCard, aeClass=typeWildCard;
     AEGetAttributePtr(ae, keyEventClassAttr, typeType, 0, &aeClass, sizeof(aeClass), 0);
     AEGetAttributePtr(ae, keyEventIDAttr, typeType, 0, &aeID, sizeof(aeID), 0);
     if(aeClass == kCoreEventClass) {
         switch(aeID) {
         case kAEQuitApplication: {
             extern bool qt_mac_quit_menu_item_enabled; // qmenu_mac.cpp
             if (qt_mac_quit_menu_item_enabled) {
                 QCloseEvent ev;
                 QApplication::sendSpontaneousEvent(app, &ev);
                 if(ev.isAccepted()) {
                     handled_event = true;
                     app->quit();
                 }
             } else {
                 QApplication::beep();  // Sorry, you can't quit right now.
             }
             break; }
         case kAEOpenDocuments: {
             AEDescList docs;
             if(AEGetParamDesc(ae, keyDirectObject, typeAEList, &docs) == noErr) {
                 long cnt = 0;
                 AECountItems(&docs, &cnt);
                 UInt8 *str_buffer = NULL;
                 for(int i = 0; i < cnt; i++) {
                     FSRef ref;
                     if(AEGetNthPtr(&docs, i+1, typeFSRef, 0, 0, &ref, sizeof(ref), 0) != noErr)
                         continue;
                     if(!str_buffer)
                         str_buffer = (UInt8 *)malloc(1024);
                     FSRefMakePath(&ref, str_buffer, 1024);
                     QFileOpenEvent ev(QString::fromUtf8((const char *)str_buffer));
                     QApplication::sendSpontaneousEvent(app, &ev);
                 }
                 if(str_buffer)
                     free(str_buffer);
             }
             break; }
         default:
             break;
         }
     } else if (aeClass == kInternetEventClass) {
         switch (aeID) {
         case kAEGetURL: {
             char urlData[1024];
             Size actualSize;
             if (AEGetParamPtr(ae, keyDirectObject, typeChar, 0, urlData,
                     sizeof(urlData) - 1, &actualSize) == noErr) {
                 urlData[actualSize] = 0;
                 QFileOpenEvent ev(QUrl(QString::fromUtf8(urlData)));
                 QApplication::sendSpontaneousEvent(app, &ev);
             }
             break;
         }
         default:
             break;
         }
     }
 #ifdef DEBUG_EVENTS
     qDebug("Qt: internal: %shandled Apple event! %c%c%c%c %c%c%c%c", handled_event ? "(*)" : "",
            char(aeID >> 24), char((aeID >> 16) & 255), char((aeID >> 8) & 255),char(aeID & 255),
            char(aeClass >> 24), char((aeClass >> 16) & 255), char((aeClass >> 8) & 255),char(aeClass & 255));
 #else
     if(!handled_event) //let the event go through
         return eventNotHandledErr;
     return noErr; //we eat the event
 #endif
 }
globalEventProcessor()
OSStatus QApplicationPrivate::globalEventProcessor (EventHandlerCallRef er, EventRef event, void * data) static
Definition at line 1635 of file qapplication_mac.mm.
Referenced by qt_init().
 {
 #ifndef QT_MAC_USE_COCOA
     QApplication *app = (QApplication *)data;
     QScopedLoopLevelCounter loopLevelCounter(app->d_func()->threadData);
     long result;
     if (app->filterEvent(&event, &result))
         return result;
     if(app->macEventFilter(er, event)) //someone else ate it
         return noErr;
     QPointer<QWidget> widget;
     /*We assume all events are handled and in
       the code below we set it to false when we know we didn't handle it, this
       will let rogue events through (shouldn't really happen, but better safe
       than sorry) */
     bool handled_event=true;
     UInt32 ekind = GetEventKind(event), eclass = GetEventClass(event);
     switch(eclass)
     {
     case kEventClassQt:
         if(ekind == kEventQtRequestShowSheet) {
             request_showsheet_pending = 0;
             QWidget *widget = 0;
             GetEventParameter(event, kEventParamQWidget, typeQWidget, 0,
                               sizeof(widget), 0, &widget);
             if(widget) {
                 if (widget->macEvent(er, event))
                     return noErr;
                 WindowPtr window = qt_mac_window_for(widget);
                 bool just_show = !qt_mac_is_macsheet(widget);
                 if(!just_show) {
                     OSStatus err = ShowSheetWindow(window, qt_mac_window_for(widget->parentWidget()));
                     if(err != noErr)
                         qWarning("Qt: QWidget: Unable to show as sheet %s::%s [%ld]", widget->metaObject()->className(),
                                  widget->objectName().toLocal8Bit().constData(), long(err));
                     just_show = true;
                 }
                 if(just_show) //at least the window will be visible, but the sheet flag doesn't work sadly (probalby too many sheets)
                     ShowHide(window, true);
             }
         } else if(ekind == kEventQtRequestWindowChange) {
             qt_mac_event_release(request_window_change_pending);
         } else if(ekind == kEventQtRequestMenubarUpdate) {
             qt_mac_event_release(request_menubarupdate_pending);
             QMenuBar::macUpdateMenuBar();
         } else if(ekind == kEventQtRequestActivate) {
             qt_mac_event_release(request_activate_pending.event);
             if(request_activate_pending.widget) {
                 QWidget *tlw = request_activate_pending.widget->window();
                 if (tlw->macEvent(er, event))
                     return noErr;
                 request_activate_pending.widget = 0;
                 tlw->activateWindow();
                 SelectWindow(qt_mac_window_for(tlw));
             }
         } else if(ekind == kEventQtRequestContext) {
             bool send = false;
             if ((send = (event == request_context_pending)))
                 qt_mac_event_release(request_context_pending);
             if(send) {
                 //figure out which widget to send it to
                 QPoint where = QCursor::pos();
                 QWidget *widget = 0;
                 GetEventParameter(event, kEventParamQWidget, typeQWidget, 0,
                                   sizeof(widget), 0, &widget);
                 if(!widget) {
                     if(qt_button_down)
                         widget = qt_button_down;
                     else
                         widget = QApplication::widgetAt(where.x(), where.y());
                 }
                 if(widget && !isBlockedByModal(widget)) {
                     if (widget->macEvent(er, event))
                         return noErr;
                     QPoint plocal(widget->mapFromGlobal(where));
                     const Qt::KeyboardModifiers keyboardModifiers = qt_mac_get_modifiers(GetCurrentEventKeyModifiers());
                     QContextMenuEvent qme(QContextMenuEvent::Mouse, plocal, where, keyboardModifiers);
                     QApplication::sendEvent(widget, &qme);
                     if(qme.isAccepted()) { //once this happens the events before are pitched
                         qt_button_down = 0;
                         qt_mac_dblclick.last_widget = 0;
                     }
                 } else {
                     handled_event = false;
                 }
             }
         } else {
             handled_event = false;
         }
         break;
     case kEventClassTablet:
         switch (ekind) {
         case kEventTabletProximity:
             // Get the current point of the device and its unique ID.
             ::TabletProximityRec proxRec;
             GetEventParameter(event, kEventParamTabletProximityRec, typeTabletProximityRec, 0,
                               sizeof(proxRec), 0, &proxRec);
             qt_dispatchTabletProximityEvent(proxRec);
         }
         break;
     case kEventClassMouse:
     {
         static const int kEventParamQAppSeenMouseEvent = 'QASM';
         // Check if we've seen the event, if we have we shouldn't process
         // it again as it may lead to spurious "double events"
         bool seenEvent;
         if (GetEventParameter(event, kEventParamQAppSeenMouseEvent,
                               typeBoolean, 0, sizeof(bool), 0, &seenEvent) == noErr) {
             if (seenEvent)
                 return eventNotHandledErr;
         }
         seenEvent = true;
         SetEventParameter(event, kEventParamQAppSeenMouseEvent, typeBoolean,
                           sizeof(bool), &seenEvent);
         Point where;
         bool inNonClientArea = false;
         GetEventParameter(event, kEventParamMouseLocation, typeQDPoint, 0,
                           sizeof(where), 0, &where);
 #if defined(DEBUG_MOUSE_MAPS)
         const char *edesc = 0;
         switch(ekind) {
         case kEventMouseDown: edesc = "MouseButtonPress"; break;
         case kEventMouseUp: edesc = "MouseButtonRelease"; break;
         case kEventMouseDragged: case kEventMouseMoved: edesc = "MouseMove"; break;
         case kEventMouseScroll: edesc = "MouseWheelScroll"; break;
         case kEventMouseWheelMoved: edesc = "MouseWheelMove"; break;
         }
         if(ekind == kEventMouseDown || ekind == kEventMouseUp)
             qDebug("Handling mouse: %s", edesc);
 #endif
         QEvent::Type etype = QEvent::None;
         Qt::KeyboardModifiers modifiers;
         {
             UInt32 mac_modifiers = 0;
             GetEventParameter(event, kEventParamKeyModifiers, typeUInt32, 0,
                               sizeof(mac_modifiers), 0, &mac_modifiers);
             modifiers = qt_mac_get_modifiers(mac_modifiers);
         }
         Qt::MouseButtons buttons;
         {
             UInt32 mac_buttons = 0;
             GetEventParameter(event, kEventParamMouseChord, typeUInt32, 0,
                               sizeof(mac_buttons), 0, &mac_buttons);
             if (ekind != kEventMouseWheelMoved)
                 buttons = qt_mac_get_buttons(mac_buttons);
             else
                 buttons = QApplication::mouseButtons();
         }
         int wheel_deltaX = 0;
         int wheel_deltaY = 0;
         static EventRef compatibilityEvent = 0;
         if (ekind == kEventMouseScroll) {
             // kEventMouseScroll is the new way of dealing with mouse wheel
             // events (kEventMouseWheelMoved was the old). kEventMouseScroll results
             // in much smoother scrolling when using Mighty Mouse or TrackPad. For
             // compatibility with older applications, carbon will also send us
             // kEventMouseWheelMoved events if we dont eat this event
             // (actually two events; one for horizontal and one for vertical).
             // As a results of this, and to make sure we dont't receive duplicate events,
             // we try to detect when this happend by checking the 'compatibilityEvent'.
             // Since delta is delivered as pixels rather than degrees, we need to
             // convert from pixels to degrees in a sensible manner.
             // It looks like 1/4 degrees per pixel behaves most native.
             // (NB: Qt expects the unit for delta to be 8 per degree):
             const int pixelsToDegrees = 2;
             SInt32 mdelt = 0;
             GetEventParameter(event, kEventParamMouseWheelSmoothHorizontalDelta, typeSInt32, 0,
                               sizeof(mdelt), 0, &mdelt);
             wheel_deltaX = mdelt * pixelsToDegrees;
             mdelt = 0;
             GetEventParameter(event, kEventParamMouseWheelSmoothVerticalDelta, typeSInt32, 0,
                               sizeof(mdelt), 0, &mdelt);
             wheel_deltaY = mdelt * pixelsToDegrees;
             GetEventParameter(event, kEventParamEventRef, typeEventRef, 0,
                               sizeof(compatibilityEvent), 0, &compatibilityEvent);
         } else if (ekind == kEventMouseWheelMoved) {
             if (event != compatibilityEvent) {
                 compatibilityEvent = 0;
                 int mdelt = 0;
                 GetEventParameter(event, kEventParamMouseWheelDelta, typeSInt32, 0,
                         sizeof(mdelt), 0, &mdelt);
                 EventMouseWheelAxis axis;
                 GetEventParameter(event, kEventParamMouseWheelAxis, typeMouseWheelAxis, 0,
                         sizeof(axis), 0, &axis);
                 // Remove acceleration, and use either -120 or 120 as delta:
                 if (axis == kEventMouseWheelAxisX)
                     wheel_deltaX = qBound(-120, int(mdelt * 10000), 120);
                 else
                     wheel_deltaY = qBound(-120, int(mdelt * 10000), 120);
             }
         }
         Qt::MouseButton button = Qt::NoButton;
         if(ekind == kEventMouseDown || ekind == kEventMouseUp) {
             EventMouseButton mac_button = 0;
             GetEventParameter(event, kEventParamMouseButton, typeMouseButton, 0,
                               sizeof(mac_button), 0, &mac_button);
             button = qt_mac_get_button(mac_button);
         }
         switch(ekind) {
         case kEventMouseDown:
             etype = QEvent::MouseButtonPress;
             break;
         case kEventMouseUp:
             etype = QEvent::MouseButtonRelease;
             break;
         case kEventMouseDragged:
         case kEventMouseMoved:
             etype = QEvent::MouseMove;
             break;
         }
         const bool inPopupMode = app->d_func()->inPopupMode();
         // A click outside a popup closes the popup. Make sure
         // that no events are generated for the release part of that click.
         // (The press goes to the popup and closes it.)
         if (etype == QEvent::MouseButtonPress) {
             qt_mac_previous_press_in_popup_mode = inPopupMode;
         } else if (qt_mac_previous_press_in_popup_mode && !inPopupMode && etype == QEvent::MouseButtonRelease) {
             qt_mac_previous_press_in_popup_mode = false;
             handled_event = true;
 #if defined(DEBUG_MOUSE_MAPS)
             qDebug("Bail out early due to qt_mac_previous_press_in_popup_mode");
 #endif
             break; // break from case kEventClassMouse
         }
         //figure out which widget to send it to
         if(inPopupMode) {
             QWidget *popup = qApp->activePopupWidget();
             if (qt_button_down && qt_button_down->window() == popup) {
                 widget = qt_button_down;
             } else {
                 QPoint pos = popup->mapFromGlobal(QPoint(where.h, where.v));
                 widget = popup->childAt(pos);
             }
             if(!widget)
                 widget = popup;
         } else {
             if(mac_mouse_grabber) {
                 widget = mac_mouse_grabber;
             } else if (qt_button_down) {
                 widget = qt_button_down;
             } else {
                 {
                     WindowPtr window = 0;
                     if(GetEventParameter(event, kEventParamWindowRef, typeWindowRef, 0,
                                          sizeof(window), 0, &window) != noErr)
                         FindWindowOfClass(&where, kAllWindowClasses, &window, 0);
                     if(window) {
                         HIViewRef hiview;
                         if(HIViewGetViewForMouseEvent(HIViewGetRoot(window), event, &hiview) == noErr) {
                             widget = QWidget::find((WId)hiview);
                             if (widget) {
                                 // Make sure we didn't pass over a widget with a "fake hole" in it.
                                 QWidget *otherWidget = QApplication::widgetAt(where.h, where.v);
                                 if (otherWidget && otherWidget->testAttribute(Qt::WA_MouseNoMask))
                                     widget = otherWidget;
                             }
                         }
                     }
                 }
                 if(!widget) //fallback
                     widget = QApplication::widgetAt(where.h, where.v);
                 if(ekind == kEventMouseUp && widget) {
                     short part = qt_mac_window_at(where.h, where.v);
                     if(part == inDrag) {
                         UInt32 count = 0;
                         GetEventParameter(event, kEventParamClickCount, typeUInt32, NULL,
                                           sizeof(count), NULL, &count);
                         if(count == 2 && qt_mac_collapse_on_dblclick) {
                             if (widget->macEvent(er, event))
                                 return noErr;
                             widget->setWindowState(widget->windowState() | Qt::WindowMinimized);
                             //we send a hide to be like X11/Windows
                             QEvent e(QEvent::Hide);
                             QApplication::sendSpontaneousEvent(widget, &e);
                             break;
                         }
                     }
                 }
             }
         }
         if (widget && widget->macEvent(er, event))
             return noErr;
         WindowPartCode wpc = qt_mac_window_at(where.h, where.v, 0);
         if (wpc == inProxyIcon && modifiers == Qt::ControlModifier && buttons != Qt::NoButton) {
             QIconDragEvent e;
             QApplication::sendSpontaneousEvent(widget, &e);
             if (e.isAccepted()) {
                 return noErr; // IconDrag ate it.
             }
         }
         if (inPopupMode == false
                 && (qt_button_down == 0 || qt_button_down_in_content == false)
                 && (wpc != inContent && wpc != inStructure)) {
             inNonClientArea = true;
             switch (etype) {
             case QEvent::MouseButtonPress: {
                 UInt32 count = 0;
                 GetEventParameter(event, kEventParamClickCount, typeUInt32, 0,
                                       sizeof(count), 0, &count);
                 if(count % 2 || count == 0) {
                     etype = QEvent::NonClientAreaMouseButtonPress;
                 } else {
                     etype = QEvent::NonClientAreaMouseButtonDblClick;
                 }} break;
             case QEvent::MouseButtonRelease:
                 etype = QEvent::NonClientAreaMouseButtonRelease;
                 break;
             case QEvent::MouseMove:
                 if (widget == 0 || widget->hasMouseTracking())
                     etype = QEvent::NonClientAreaMouseMove;
                 break;
             default:
                 break;
             }
         }
         if(qt_mac_find_window((FrontWindow()))) { //set the cursor up
             QCursor cursor(Qt::ArrowCursor);
             QWidget *cursor_widget = widget;
             if(cursor_widget && cursor_widget == qt_button_down && ekind == kEventMouseUp)
                 cursor_widget = QApplication::widgetAt(where.h, where.v);
             if(cursor_widget) { //only over the app, do we set a cursor..
                 if(!qApp->d_func()->cursor_list.isEmpty()) {
                     cursor = qApp->d_func()->cursor_list.first();
                 } else {
                     for(; cursor_widget; cursor_widget = cursor_widget->parentWidget()) {
                         QWExtra *extra = cursor_widget->d_func()->extraData();
                         if(extra && extra->curs && cursor_widget->isEnabled()) {
                             cursor = *extra->curs;
                             break;
                         }
                     }
                 }
             }
             qt_mac_set_cursor(&cursor);
         }
         //This mouse button state stuff looks like this on purpose
         //although it looks hacky it is VERY intentional..
         if(widget && app_do_modal && !qt_try_modal(widget, event)) {
             if(ekind == kEventMouseDown && qt_mac_is_macsheet(QApplication::activeModalWidget()))
                 QApplication::activeModalWidget()->parentWidget()->activateWindow(); //sheets have a parent
             handled_event = false;
 #if defined(DEBUG_MOUSE_MAPS)
             qDebug("Bail out early due to qt_try_modal");
 #endif
             break;
         }
         UInt32 tabletEventType = 0;
         GetEventParameter(event, kEventParamTabletEventType, typeUInt32, 0,
                           sizeof(tabletEventType), 0, &tabletEventType);
         if (tabletEventType == kEventTabletPoint) {
             TabletPointRec tabletPointRec;
             GetEventParameter(event, kEventParamTabletPointRec, typeTabletPointRec, 0,
                               sizeof(tabletPointRec), 0, &tabletPointRec);
             QEvent::Type t = QEvent::TabletMove; //default
             int new_tablet_button_state = tabletPointRec.buttons ? 1 : 0;
             if (new_tablet_button_state != tablet_button_state)
                 if (new_tablet_button_state)
                     t = QEvent::TabletPress;
                 else
                     t = QEvent::TabletRelease;
             tablet_button_state = new_tablet_button_state;
             QMacTabletHash *tabletHash = qt_mac_tablet_hash();
             if (!tabletHash->contains(tabletPointRec.deviceID) && t != QEvent::TabletRelease) {
                 // Never discard TabletRelease events as they may be delivered *after* TabletLeaveProximity events
                 qWarning("handleTabletEvent: This tablet device is unknown"
                          " (received no proximity event for it). Discarding event.");
                 return false;
             }
             QTabletDeviceData &deviceData = tabletHash->operator[](tabletPointRec.deviceID);
             if (t == QEvent::TabletPress) {
                 deviceData.widgetToGetPress = widget;
             } else if (t == QEvent::TabletRelease && deviceData.widgetToGetPress) {
                 widget = deviceData.widgetToGetPress;
                 deviceData.widgetToGetPress = 0;
             }
             if (widget) {
                 int tiltX = ((int)tabletPointRec.tiltX)/(32767/64); // 32K -> 60
                 int tiltY = ((int)tabletPointRec.tiltY)/(-32767/64); // 32K -> 60
                 HIPoint hiPoint;
                 GetEventParameter(event, kEventParamMouseLocation, typeHIPoint, 0, sizeof(HIPoint), 0, &hiPoint);
                 QPointF hiRes(hiPoint.x, hiPoint.y);
                 QPoint global(where.h, where.v);
                 QPoint local(widget->mapFromGlobal(global));
                 int z = 0;
                 qreal rotation = 0.0;
                 qreal tp = 0.0;
                 // Again from the Wacom.h header
                 if (deviceData.capabilityMask & 0x0200)     // Z-axis
                     z = tabletPointRec.absZ;
                 if (deviceData.capabilityMask & 0x0800)  // Tangential pressure
                     tp = tabletPointRec.tangentialPressure / 32767.0;
                 if (deviceData.capabilityMask & 0x2000) // Rotation
                     rotation = qreal(tabletPointRec.rotation) / 64.0;
                 QTabletEvent e(t, local, global, hiRes, deviceData.tabletDeviceType,
                                deviceData.tabletPointerType,
                                qreal(tabletPointRec.pressure / qreal(0xffff)), tiltX, tiltY,
                                tp, rotation, z, modifiers, deviceData.tabletUniqueID);
                 QApplication::sendSpontaneousEvent(widget, &e);
                 if (e.isAccepted()) {
                     if (t == QEvent::TabletPress) {
                         qt_button_down = widget;
                     } else if (t == QEvent::TabletRelease) {
                         qt_button_down = 0;
                     }
 #if defined(DEBUG_MOUSE_MAPS)
                     qDebug("Bail out early due to tablet acceptance");
 #endif
                     break;
                 }
             }
         }
         if(ekind == kEventMouseDown) {
             qt_mac_no_click_through_mode = false;
             const short windowPart = qt_mac_window_at(where.h, where.v, 0);
             // Menubar almost always wins.
             if (!inPopupMode && windowPart == inMenuBar) {
                 MenuSelect(where); //allow menu tracking
                 return noErr;
             }
             if (widget && !(GetCurrentKeyModifiers() & cmdKey)) {
                 extern bool qt_isGenuineQWidget(const QWidget *); // qwidget_mac.cpp
                 QWidget *window = widget->window();
                 bool genuineQtWidget = qt_isGenuineQWidget(widget);  // the widget, not the window.
                 window->raise();
                 bool needActivate = (window->windowType() != Qt::Desktop)
                                      && (window->windowType() != Qt::Popup)
                                      && !qt_mac_is_macsheet(window);
                 if (needActivate && (!window->isModal() && qobject_cast<QDockWidget *>(window)))
                     needActivate = false;
                 if (genuineQtWidget && needActivate)
                     needActivate = !window->isActiveWindow()
                                     || !IsWindowActive(qt_mac_window_for(window));
                 if (needActivate) {
                     window->activateWindow();
                     if (!qt_mac_can_clickThrough(widget)) {
                         qt_mac_no_click_through_mode = true;
                         handled_event = false;
 #if defined(DEBUG_MOUSE_MAPS)
                         qDebug("Bail out early due to qt_mac_canClickThrough %s::%s", widget->metaObject()->className(),
                                 widget->objectName().toLocal8Bit().constData());
 #endif
                         break;
                     }
                 }
             }
             if(qt_mac_dblclick.last_widget &&
                qt_mac_dblclick.last_x != -1 && qt_mac_dblclick.last_y != -1 &&
                QRect(qt_mac_dblclick.last_x-2, qt_mac_dblclick.last_y-2, 4, 4).contains(QPoint(where.h, where.v))) {
                 if(qt_mac_dblclick.use_qt_time_limit) {
                     EventTime now = GetEventTime(event);
                     if(qt_mac_dblclick.last_time != -2 && qt_mac_dblclick.last_widget == widget &&
                        now - qt_mac_dblclick.last_time <= ((double)QApplicationPrivate::mouse_double_click_time)/1000 &&
                        qt_mac_dblclick.last_button == button)
                         etype = QEvent::MouseButtonDblClick;
                 } else {
                     UInt32 count = 0;
                     GetEventParameter(event, kEventParamClickCount, typeUInt32, 0,
                                       sizeof(count), 0, &count);
                     if(!(count % 2) && qt_mac_dblclick.last_modifiers == modifiers &&
                        qt_mac_dblclick.last_widget == widget && qt_mac_dblclick.last_button == button)
                         etype = QEvent::MouseButtonDblClick;
                 }
                 if(etype == QEvent::MouseButtonDblClick)
                     qt_mac_dblclick.last_widget = 0;
             }
             if(etype != QEvent::MouseButtonDblClick) {
                 qt_mac_dblclick.last_x = where.h;
                 qt_mac_dblclick.last_y = where.v;
             } else {
                 qt_mac_dblclick.last_x = qt_mac_dblclick.last_y = -1;
             }
         } else if(qt_mac_no_click_through_mode) {
             if(ekind == kEventMouseUp)
                 qt_mac_no_click_through_mode = false;
             handled_event = false;
 #if defined(DEBUG_MOUSE_MAPS)
             qDebug("Bail out early due to qt_mac_no_click_through_mode");
 #endif
             break;
         }
         QPointer<QWidget> leaveAfterRelease = 0;
         switch(ekind) {
         case kEventMouseUp:
             if (!buttons) {
                 if (!inPopupMode && !QWidget::mouseGrabber())
                     leaveAfterRelease = qt_button_down;
                 qt_button_down = 0;
             }
             break;
         case kEventMouseDown: {
             if (!qt_button_down)
                 qt_button_down = widget;
             WindowPartCode wpc = qt_mac_window_at(where.h, where.v, 0);
             qt_button_down_in_content = (wpc == inContent || wpc == inStructure);
             break;  }
         }
         // Check if we should send enter/leave events:
         switch(ekind) {
         case kEventMouseDragged:
         case kEventMouseMoved:
         case kEventMouseUp:
         case kEventMouseDown: {
             // If we are in popup mode, widget will point to the current popup no matter
             // where the mouse cursor is. In that case find out if the mouse cursor is
             // really over the popup in order to send correct enter / leave envents.
             QWidget * const enterLeaveWidget = (inPopupMode || ekind == kEventMouseUp) ?
                     QApplication::widgetAt(where.h, where.v) :  static_cast<QWidget*>(widget);
             if ((QWidget *) qt_last_mouse_receiver != enterLeaveWidget || inNonClientArea) {
 #ifdef DEBUG_MOUSE_MAPS
                 qDebug("Entering: %p - %s (%s), Leaving %s (%s)", (QWidget*)enterLeaveWidget,
                        enterLeaveWidget ? enterLeaveWidget->metaObject()->className() : "none",
                        enterLeaveWidget ? enterLeaveWidget->objectName().toLocal8Bit().constData() : "",
                        qt_last_mouse_receiver ? qt_last_mouse_receiver->metaObject()->className() : "none",
                        qt_last_mouse_receiver ? qt_last_mouse_receiver->objectName().toLocal8Bit().constData() : "");
 #endif
                 QWidget * const mouseGrabber = QWidget::mouseGrabber();
                 if (inPopupMode) {
                     QWidget *enter = enterLeaveWidget;
                     QWidget *leave = qt_last_mouse_receiver;
                     if (mouseGrabber) {
                         QWidget * const popupWidget = qApp->activePopupWidget();
                         if (leave == popupWidget)
                             enter = mouseGrabber;
                         if (enter == popupWidget)
                             leave = mouseGrabber;
                         if ((enter == mouseGrabber && leave == popupWidget)
                             || (leave == mouseGrabber  && enter == popupWidget)) {
                             QApplicationPrivate::dispatchEnterLeave(enter, leave);
                             qt_last_mouse_receiver = enter;
                         }
                     } else {
                         QApplicationPrivate::dispatchEnterLeave(enter, leave);
                         qt_last_mouse_receiver = enter;
                     }
                 } else if ((!qt_button_down || !qt_last_mouse_receiver) && !mouseGrabber && !leaveAfterRelease) {
                     QApplicationPrivate::dispatchEnterLeave(enterLeaveWidget, qt_last_mouse_receiver);
                     qt_last_mouse_receiver = enterLeaveWidget;
                 }
             }
             break; }
         }
         if(widget) {
             QPoint p(where.h, where.v);
             QPoint plocal(widget->mapFromGlobal(p));
             if(etype == QEvent::MouseButtonPress) {
                 qt_mac_dblclick.last_widget = widget;
                 qt_mac_dblclick.last_modifiers = modifiers;
                 qt_mac_dblclick.last_button = button;
                 qt_mac_dblclick.last_time = GetEventTime(event);
             }
             if (wheel_deltaX || wheel_deltaY) {
 #ifndef QT_NO_WHEELEVENT
                 if (wheel_deltaX) {
                     QWheelEvent qwe(plocal, p, wheel_deltaX, buttons, modifiers, Qt::Horizontal);
                     QApplication::sendSpontaneousEvent(widget, &qwe);
                     if (!qwe.isAccepted() && QApplicationPrivate::focus_widget && QApplicationPrivate::focus_widget != widget) {
                         QWheelEvent qwe2(QApplicationPrivate::focus_widget->mapFromGlobal(p), p,
                                 wheel_deltaX, buttons, modifiers, Qt::Horizontal);
                         QApplication::sendSpontaneousEvent(QApplicationPrivate::focus_widget, &qwe2);
                         if (!qwe2.isAccepted())
                             handled_event = false;
                     }
                 }
                 if (wheel_deltaY) {
                     QWheelEvent qwe(plocal, p, wheel_deltaY, buttons, modifiers, Qt::Vertical);
                     QApplication::sendSpontaneousEvent(widget, &qwe);
                     if (!qwe.isAccepted() && QApplicationPrivate::focus_widget && QApplicationPrivate::focus_widget != widget) {
                         QWheelEvent qwe2(QApplicationPrivate::focus_widget->mapFromGlobal(p), p,
                                 wheel_deltaY, buttons, modifiers, Qt::Vertical);
                         QApplication::sendSpontaneousEvent(QApplicationPrivate::focus_widget, &qwe2);
                         if (!qwe2.isAccepted())
                             handled_event = false;
                     }
                 }
 #endif // QT_NO_WHEELEVENT
             } else {
 #ifdef QMAC_SPEAK_TO_ME
                 const int speak_keys = Qt::AltModifier | Qt::ShiftModifier;
         if(etype == QMouseEvent::MouseButtonDblClick && ((modifiers & speak_keys) == speak_keys)) {
                     QVariant v = widget->property("displayText");
                     if(!v.isValid()) v = widget->property("text");
                     if(!v.isValid()) v = widget->property("windowTitle");
                     if(v.isValid()) {
                         QString s = v.toString();
                         s.replace(QRegExp(QString::fromLatin1("(\\&|\\<[^\\>]*\\>)")), QLatin1String(""));
                         SpeechChannel ch;
                         NewSpeechChannel(0, &ch);
                         SpeakText(ch, s.toLatin1().constData(), s.length());
                         DisposeSpeechChannel(ch);
                     }
                 }
 #endif
                 Qt::MouseButton buttonToSend = button;
                 static bool lastButtonTranslated = false;
                 if(ekind == kEventMouseDown &&
                    button == Qt::LeftButton && (modifiers & Qt::MetaModifier)) {
                     buttonToSend = Qt::RightButton;
                     lastButtonTranslated = true;
                 } else if(ekind == kEventMouseUp && lastButtonTranslated) {
                     buttonToSend = Qt::RightButton;
                     lastButtonTranslated = false;
                 }
                 QMouseEvent qme(etype, plocal, p, buttonToSend, buttons, modifiers);
                 QApplication::sendSpontaneousEvent(widget, &qme);
                 if(!qme.isAccepted() || inNonClientArea)
                     handled_event = false;
             }
             if (leaveAfterRelease) {
                 QWidget *enter = QApplication::widgetAt(where.h, where.v);
                 QApplicationPrivate::dispatchEnterLeave(enter, leaveAfterRelease);
                 qt_last_mouse_receiver = enter;
                 leaveAfterRelease = 0;
             }
             if(ekind == kEventMouseDown &&
                ((button == Qt::RightButton) ||
                 (button == Qt::LeftButton && (modifiers & Qt::MetaModifier))))
                 qt_event_request_context();
 #ifdef DEBUG_MOUSE_MAPS
             const char *event_desc = edesc;
             if(etype == QEvent::MouseButtonDblClick)
                 event_desc = "Double Click";
             else if(etype == QEvent::NonClientAreaMouseButtonPress)
                 event_desc = "NonClientMousePress";
             else if(etype == QEvent::NonClientAreaMouseButtonRelease)
                 event_desc = "NonClientMouseRelease";
             else if(etype == QEvent::NonClientAreaMouseMove)
                 event_desc = "NonClientMouseMove";
             else if(etype == QEvent::NonClientAreaMouseButtonDblClick)
                 event_desc = "NonClientMouseDblClick";
             qDebug("%d %d (%d %d) - Would send (%s) event to %p %s %s (%d 0x%08x 0x%08x %d)", p.x(), p.y(),
                    plocal.x(), plocal.y(), event_desc, (QWidget*)widget,
                    widget ? widget->objectName().toLocal8Bit().constData() : "*Unknown*",
                    widget ? widget->metaObject()->className() : "*Unknown*",
                    button, (int)buttons, (int)modifiers, wheel_deltaX);
 #endif
         } else {
             handled_event = false;
         }
         break;
     }
     case kEventClassTextInput:
     case kEventClassKeyboard: {
         EventRef key_event = event;
         if(eclass == kEventClassTextInput) {
             Q_ASSERT(ekind == kEventTextInputUnicodeForKeyEvent);
             OSStatus err = GetEventParameter(event, kEventParamTextInputSendKeyboardEvent, typeEventRef, 0,
                                              sizeof(key_event), 0, &key_event);
             Q_ASSERT(err == noErr);
             Q_UNUSED(err);
         }
         const UInt32 key_ekind = GetEventKind(key_event);
         Q_ASSERT(GetEventClass(key_event) == kEventClassKeyboard);
         if(key_ekind == kEventRawKeyDown)
             qt_keymapper_private()->updateKeyMap(er, key_event, data);
         if(mac_keyboard_grabber)
             widget = mac_keyboard_grabber;
         else if (app->activePopupWidget())
             widget = (app->activePopupWidget()->focusWidget() ?
                       app->activePopupWidget()->focusWidget() : app->activePopupWidget());
         else if(QApplication::focusWidget())
             widget = QApplication::focusWidget();
         else
             widget = app->activeWindow();
         if (widget) {
             if (widget->macEvent(er, event))
                 return noErr;
         } else {
             // Darn, I need to update tho modifier state, even though
             // Qt itself isn't getting them, otherwise the keyboard state get inconsistent.
             if (key_ekind == kEventRawKeyModifiersChanged) {
                 UInt32 modifiers = 0;
                 GetEventParameter(key_event, kEventParamKeyModifiers, typeUInt32, 0,
                                   sizeof(modifiers), 0, &modifiers);
                 extern void qt_mac_send_modifiers_changed(quint32 modifiers, QObject *object); // qkeymapper_mac.cpp
                 // Just send it to the qApp for the time being.
                 qt_mac_send_modifiers_changed(modifiers, qApp);
             }
             handled_event = false;
             break;
         }
         if(app_do_modal && !qt_try_modal(widget, key_event))
             break;
         if (eclass == kEventClassTextInput) {
             handled_event = false;
         } else {
             handled_event = qt_keymapper_private()->translateKeyEvent(widget, er, key_event, data,
                                                                       widget == mac_keyboard_grabber);
         }
         break; }
     case kEventClassWindow: {
         WindowRef wid = 0;
         GetEventParameter(event, kEventParamDirectObject, typeWindowRef, 0,
                           sizeof(WindowRef), 0, &wid);
         widget = qt_mac_find_window(wid);
         if (widget && widget->macEvent(er, event))
             return noErr;
         if(ekind == kEventWindowActivated) {
             if(QApplicationPrivate::app_style) {
                 QEvent ev(QEvent::Style);
                 QApplication::sendSpontaneousEvent(QApplicationPrivate::app_style, &ev);
             }
             if(widget && app_do_modal && !qt_try_modal(widget, event))
                 break;
             if(widget && widget->window()->isVisible()) {
                 QWidget *tlw = widget->window();
         if(tlw->isWindow() && !(tlw->windowType() == Qt::Popup)
                    && !qt_mac_is_macdrawer(tlw)
                    && (!tlw->parentWidget() || tlw->isModal()
                        || !(tlw->windowType() == Qt::Tool))) {
                     bool just_send_event = false;
                     {
                         WindowActivationScope scope;
                         if(GetWindowActivationScope((WindowRef)wid, &scope) == noErr &&
                            scope == kWindowActivationScopeIndependent) {
                             if(GetFrontWindowOfClass(kAllWindowClasses, true) != wid)
                                 just_send_event = true;
                         }
                     }
                     if(just_send_event) {
                         QEvent e(QEvent::WindowActivate);
                         QApplication::sendSpontaneousEvent(widget, &e);
                     } else {
                         app->setActiveWindow(tlw);
                     }
                 }
                 QMenuBar::macUpdateMenuBar();
             }
         } else if(ekind == kEventWindowDeactivated) {
             if(widget && QApplicationPrivate::active_window == widget)
                 app->setActiveWindow(0);
         } else {
             handled_event = false;
         }
         break; }
     case kEventClassApplication:
         if(ekind == kEventAppActivated) {
             if(QApplication::desktopSettingsAware())
                 qt_mac_update_os_settings();
             if(qt_clipboard) { //manufacture an event so the clipboard can see if it has changed
                 QEvent ev(QEvent::Clipboard);
                 QApplication::sendSpontaneousEvent(qt_clipboard, &ev);
             }
             if(app) {
                 QEvent ev(QEvent::ApplicationActivate);
                 QApplication::sendSpontaneousEvent(app, &ev);
             }
             if(!app->activeWindow()) {
                 WindowPtr wp = ActiveNonFloatingWindow();
                 if(QWidget *tmp_w = qt_mac_find_window(wp))
                     app->setActiveWindow(tmp_w);
             }
             QMenuBar::macUpdateMenuBar();
         } else if(ekind == kEventAppDeactivated) {
             //qt_mac_no_click_through_mode = false;
             while(app->d_func()->inPopupMode())
                 app->activePopupWidget()->close();
             if(app) {
                 QEvent ev(QEvent::ApplicationDeactivate);
                 QApplication::sendSpontaneousEvent(app, &ev);
             }
             app->setActiveWindow(0);
         } else if(ekind == kEventAppAvailableWindowBoundsChanged) {
             QDesktopWidgetImplementation::instance()->onResize();
         } else {
             handled_event = false;
         }
         break;
     case kAppearanceEventClass:
         if(ekind == kAEAppearanceChanged) {
             if(QApplication::desktopSettingsAware())
                 qt_mac_update_os_settings();
             if(QApplicationPrivate::app_style) {
                 QEvent ev(QEvent::Style);
                 QApplication::sendSpontaneousEvent(QApplicationPrivate::app_style, &ev);
             }
         } else {
             handled_event = false;
         }
         break;
     case kEventClassAppleEvent:
         if(ekind == kEventAppleEvent) {
             EventRecord erec;
             if(!ConvertEventRefToEventRecord(event, &erec))
                 qDebug("Qt: internal: WH0A, unexpected condition reached. %s:%d", __FILE__, __LINE__);
             else if(AEProcessAppleEvent(&erec) != noErr)
                 handled_event = false;
         } else {
             handled_event = false;
         }
         break;
     case kEventClassCommand:
         if(ekind == kEventCommandProcess) {
             HICommand cmd;
             GetEventParameter(event, kEventParamDirectObject, typeHICommand,
                               0, sizeof(cmd), 0, &cmd);
             handled_event = false;
             if(!cmd.menu.menuRef && GetApplicationDockTileMenu()) {
                 EventRef copy = CopyEvent(event);
                 HICommand copy_cmd;
                 GetEventParameter(event, kEventParamDirectObject, typeHICommand,
                                   0, sizeof(copy_cmd), 0, &copy_cmd);
                 copy_cmd.menu.menuRef = GetApplicationDockTileMenu();
                 SetEventParameter(copy, kEventParamDirectObject, typeHICommand, sizeof(copy_cmd), &copy_cmd);
                 if(SendEventToMenu(copy, copy_cmd.menu.menuRef) == noErr)
                     handled_event = true;
             }
             if(!handled_event) {
                 if(cmd.commandID == kHICommandQuit) {
                     // Quitting the application is not Qt's responsibility if
                     // used in a plugin or just embedded into a native application.
                     // In that case, let the event pass down to the native apps event handler.
                     if (!QApplication::testAttribute(Qt::AA_MacPluginApplication)) {
                         handled_event = true;
                         HiliteMenu(0);
                         bool handle_quit = true;
                         if(QApplicationPrivate::modalState()) {
                             int visible = 0;
                             const QWidgetList tlws = QApplication::topLevelWidgets();
                             for(int i = 0; i < tlws.size(); ++i) {
                                 if(tlws.at(i)->isVisible())
                                     ++visible;
                             }
                             handle_quit = (visible <= 1);
                         }
                         if(handle_quit) {
                             QCloseEvent ev;
                             QApplication::sendSpontaneousEvent(app, &ev);
                             if(ev.isAccepted())
                                 app->quit();
                         } else {
                             QApplication::beep();
                         }
                     }
                 } else if(cmd.commandID == kHICommandSelectWindow) {
                     if((GetCurrentKeyModifiers() & cmdKey))
                         handled_event = true;
                 } else if(cmd.commandID == kHICommandAbout) {
                     QMessageBox::aboutQt(0);
                     HiliteMenu(0);
                     handled_event = true;
                 }
             }
         }
         break;
     }
 #ifdef DEBUG_EVENTS
     qDebug("%shandled event %c%c%c%c %d", handled_event ? "(*) " : "",
            char(eclass >> 24), char((eclass >> 16) & 255), char((eclass >> 8) & 255),
            char(eclass & 255), (int)ekind);
 #endif
     if(!handled_event) //let the event go through
         return eventNotHandledErr;
     return noErr; //we eat the event
 #else
     Q_UNUSED(er);
     Q_UNUSED(event);
     Q_UNUSED(data);
     return eventNotHandledErr;
 #endif
 }
graphicsSystem()
static QGraphicsSystem* QApplicationPrivate::graphicsSystem () inline static
Definition at line 310 of file qapplication_p.h.
Referenced by QPixmapData::create(), QPixmapData::createCompatiblePixmapData(), QWidgetPrivate::createDefaultWindowSurface(), QBitmap::fromImage(), QPixmap::fromImage(), QPixmap::fromImageReader(), hasBackingStoreSupport(), make_widget_eventUPP(), qt_mac_update_widget_position(), QWidgetPrivate::scroll_sys(), and QWidgetPrivate::setGeometry_sys().
     { return QScreen::instance()->graphicsSystem(); }
initialize()
void QApplicationPrivate::initialize ()
Initializes the QApplication object, called from the constructors.
Definition at line 984 of file qapplication.cpp.
 {
     QWidgetPrivate::mapper = new QWidgetMapper;
     QWidgetPrivate::allWidgets = new QWidgetSet;
 #if !defined(Q_WS_X11) && !defined(Q_WS_QWS) && !defined(Q_WS_QPA)
     // initialize the graphics system - on X11 this is initialized inside
     // qt_init() in qapplication_x11.cpp because of several reasons.
     // On QWS, the graphics system is set by the QScreen plugin.
     // We don't use graphics systems in Qt QPA
     graphics_system = QGraphicsSystemFactory::create(graphics_system_name);
 #endif
     if (qt_appType != QApplication::Tty)
         (void) QApplication::style();  // trigger creation of application style
     // trigger registering of QVariant's GUI types
     qRegisterGuiVariant();
 #ifndef QT_NO_STATEMACHINE
     // trigger registering of QStateMachine's GUI types
     qRegisterGuiStateMachine();
 #endif
     is_app_running = true; // no longer starting up
     Q_Q(QApplication);
 #ifndef QT_NO_SESSIONMANAGER
     // connect to the session manager
     session_manager = new QSessionManager(q, session_id, session_key);
 #endif
     if (qgetenv("QT_USE_NATIVE_WINDOWS").toInt() > 0)
         q->setAttribute(Qt::AA_NativeWindows);
 #ifdef Q_WS_WINCE
 #ifdef QT_AUTO_MAXIMIZE_THRESHOLD
     autoMaximizeThreshold = QT_AUTO_MAXIMIZE_THRESHOLD;
 #else
     if (qt_wince_is_mobile())
         autoMaximizeThreshold = 50;
     else
         autoMaximizeThreshold = -1;
 #endif //QT_AUTO_MAXIMIZE_THRESHOLD
 #endif //Q_WS_WINCE
     // Set up which span functions should be used in raster engine...
     qInitDrawhelperAsm();
     // and QImage conversion functions
     qInitImageConversions();
 #ifndef QT_NO_WHEELEVENT
     QApplicationPrivate::wheel_scroll_lines = 3;
 #endif
 #ifdef Q_WS_S60
     q->setAttribute(Qt::AA_S60DisablePartialScreenInputMode);
 #endif
     if (qt_is_gui_used)
         initializeMultitouch();
 }
initializeMultitouch()
void QApplicationPrivate::initializeMultitouch ()
Definition at line 6001 of file qapplication.cpp.
 {
     widgetForTouchPointId.clear();
     appCurrentTouchPoints.clear();
     initializeMultitouch_sys();
 }
initializeMultitouch_sys()
void QApplicationPrivate::initializeMultitouch_sys ()
Definition at line 3170 of file qapplication_mac.mm.
Referenced by QSessionManager::cancel(), and QApplication::setArgs().
 { }
initializeWidgetPaletteHash()
void QApplicationPrivate::initializeWidgetPaletteHash () static
Definition at line 617 of file qapplication_mac.mm.
Referenced by qt_set_windows_color_resources(), and QApplication::setStyle().
 {
     { //setup the palette
         struct PaletteMap {
             inline PaletteMap(const char *qc, ThemeBrush a, ThemeBrush i) :
                 qt_class(qc), active(a), inactive(i) { }
             const char *const qt_class;
             ThemeBrush active, inactive;
         } mac_widget_colors[] = {
             PaletteMap("QToolButton", kThemeTextColorBevelButtonActive, kThemeTextColorBevelButtonInactive),
             PaletteMap("QAbstractButton", kThemeTextColorPushButtonActive, kThemeTextColorPushButtonInactive),
             PaletteMap("QHeaderView", kThemeTextColorPushButtonActive, kThemeTextColorPushButtonInactive),
             PaletteMap("Q3Header", kThemeTextColorPushButtonActive, kThemeTextColorPushButtonInactive),
             PaletteMap("QComboBox", kThemeTextColorPopupButtonActive, kThemeTextColorPopupButtonInactive),
             PaletteMap("QAbstractItemView", kThemeTextColorListView, kThemeTextColorDialogInactive),
             PaletteMap("QMessageBoxLabel", kThemeTextColorAlertActive, kThemeTextColorAlertInactive),
             PaletteMap("QTabBar", kThemeTextColorTabFrontActive, kThemeTextColorTabFrontInactive),
             PaletteMap("QLabel", kThemeTextColorPlacardActive, kThemeTextColorPlacardInactive),
             PaletteMap("QGroupBox", kThemeTextColorPlacardActive, kThemeTextColorPlacardInactive),
             PaletteMap("QMenu", kThemeTextColorPopupLabelActive, kThemeTextColorPopupLabelInactive),
             PaletteMap("QTextEdit", 0, 0),
             PaletteMap("QTextControl", 0, 0),
             PaletteMap("QLineEdit", 0, 0),
             PaletteMap(0, 0, 0) };
         QColor qc;
         for(int i = 0; mac_widget_colors[i].qt_class; i++) {
             QPalette pal;
             if (mac_widget_colors[i].active != 0) {
                 qc = qcolorForThemeTextColor(mac_widget_colors[i].active);
                 pal.setColor(QPalette::Active, QPalette::Text, qc);
                 pal.setColor(QPalette::Active, QPalette::WindowText, qc);
                 pal.setColor(QPalette::Active, QPalette::HighlightedText, qc);
                 qc = qcolorForThemeTextColor(mac_widget_colors[i].inactive);
                 pal.setColor(QPalette::Inactive, QPalette::Text, qc);
                 pal.setColor(QPalette::Disabled, QPalette::Text, qc);
                 pal.setColor(QPalette::Inactive, QPalette::WindowText, qc);
                 pal.setColor(QPalette::Disabled, QPalette::WindowText, qc);
                 pal.setColor(QPalette::Inactive, QPalette::HighlightedText, qc);
                 pal.setColor(QPalette::Disabled, QPalette::HighlightedText, qc);
             }
             if (!strcmp(mac_widget_colors[i].qt_class, "QMenu")) {
                 qc = qcolorForThemeTextColor(kThemeTextColorMenuItemActive);
                 pal.setBrush(QPalette::ButtonText, qc);
                 qc = qcolorForThemeTextColor(kThemeTextColorMenuItemSelected);
                 pal.setBrush(QPalette::HighlightedText, qc);
                 qc = qcolorForThemeTextColor(kThemeTextColorMenuItemDisabled);
                 pal.setBrush(QPalette::Disabled, QPalette::Text, qc);
             } else if (!strcmp(mac_widget_colors[i].qt_class, "QAbstractButton")
                       || !strcmp(mac_widget_colors[i].qt_class, "QHeaderView")
                       || !strcmp(mac_widget_colors[i].qt_class, "Q3Header")) { //special
                 pal.setColor(QPalette::Disabled, QPalette::ButtonText,
                              pal.color(QPalette::Disabled, QPalette::Text));
                 pal.setColor(QPalette::Inactive, QPalette::ButtonText,
                              pal.color(QPalette::Inactive, QPalette::Text));
                 pal.setColor(QPalette::Active, QPalette::ButtonText,
                              pal.color(QPalette::Active, QPalette::Text));
             } else if (!strcmp(mac_widget_colors[i].qt_class, "QAbstractItemView")) {
                 pal.setBrush(QPalette::Active, QPalette::Highlight,
                              qcolorForTheme(kThemeBrushAlternatePrimaryHighlightColor));
                 qc = qcolorForThemeTextColor(kThemeTextColorMenuItemSelected);
                 pal.setBrush(QPalette::Active, QPalette::HighlightedText, qc);
 #if 1
                 pal.setBrush(QPalette::Inactive, QPalette::Text,
                               pal.brush(QPalette::Active, QPalette::Text));
                 pal.setBrush(QPalette::Inactive, QPalette::HighlightedText,
                               pal.brush(QPalette::Active, QPalette::Text));
 #endif
             } else if (!strcmp(mac_widget_colors[i].qt_class, "QTextEdit")
                        || !strcmp(mac_widget_colors[i].qt_class, "QTextControl")) {
                 pal.setBrush(QPalette::Inactive, QPalette::Text,
                               pal.brush(QPalette::Active, QPalette::Text));
                 pal.setBrush(QPalette::Inactive, QPalette::HighlightedText,
                               pal.brush(QPalette::Active, QPalette::Text));
             } else if (!strcmp(mac_widget_colors[i].qt_class, "QLineEdit")) {
                 pal.setBrush(QPalette::Disabled, QPalette::Base,
                              pal.brush(QPalette::Active, QPalette::Base));
             }
             bool set_palette = true;
             PaletteHash *phash = qt_app_palettes_hash();
             if (!phash->isEmpty()) {
                 PaletteHash::const_iterator it
                                     = phash->constFind(mac_widget_colors[i].qt_class);
                 if (it != phash->constEnd())
                     set_palette = (pal != *it);
             }
             if (set_palette) {
                 QApplication::setPalette(pal, mac_widget_colors[i].qt_class);
 #ifdef DEBUG_PLATFORM_SETTINGS
                 qt_mac_debug_palette(pal, QApplication::palette(), QLatin1String("Palette for ") + QString::fromLatin1(mac_widget_colors[i].qt_class));
 #endif
             }
         }
     }
 }
inPopupMode()
bool QApplicationPrivate::inPopupMode () const
Definition at line 5303 of file qapplication.cpp.
Referenced by onApplicationChangedActivation(), and qt_cleanup().
 {
     return QApplicationPrivate::popupWidgets != 0;
 }
instance()
static QApplicationPrivate* QApplicationPrivate::instance () inline static
Definition at line 524 of file qapplication_p.h.
Referenced by QWSServerPrivate::_q_newConnection(), QGraphicsScenePrivate::cancelGesturesForChildren(), create32BitCursor(), QMeeGoGraphicsSystem::createWindowSurface(), QVGGraphicsSystem::createWindowSurface(), QGLGraphicsSystem::createWindowSurface(), dispatchEnterLeave(), QDragManager::dragCursor(), QWSServer::endDisplayReconfigure(), QMacInputContext::globalEventProcessor(), QGestureManager::instance(), QKeyMapperPrivate::isADeadKey(), make_widget_eventUPP(), QCursor::QCursor(), qt_keyrelease_scanner(), qt_mac_constructQIconFromIconRef(), qt_mac_menu_event(), QtWndProc(), QMeeGoGraphicsSystem::runningGraphicsSystemName(), QGraphicsScenePrivate::sendEvent(), QKeyMapper::sendKeyEvent(), setMaxWindowRect(), QWSServer::setMaxWindowRect(), setScreenTransformation(), QMeeGoGraphicsSystem::switchToMeeGo(), QMeeGoGraphicsSystem::switchToRaster(), and QMeeGoGraphicsSystem::wrapPixmapData().
 { return self; }
isAlien()
bool QApplicationPrivate::isAlien (QWidget * widget) inline static private
Definition at line 529 of file qapplication.cpp.
 {
     if (!widget)
         return false;
 #if defined(Q_WS_QWS) || defined(Q_WS_QPA)
     return !widget->isWindow()
 # ifdef Q_BACKINGSTORE_SUBSURFACES
         && !(widget->d_func()->maybeTopData() && widget->d_func()->maybeTopData()->windowSurface)
 # endif
         ;
 #else
     return !widget->internalWinId();
 #endif
 }
isBlockedByModal()
bool QApplicationPrivate::isBlockedByModal (QWidget * widget) static
Returns true if widget is blocked by a modal window.
Warning
This function is not part of the public interface.
Definition at line 2960 of file qapplication.cpp.
Referenced by flipPoint(), QAxClientSite::qt_metacall(), qt_try_modal(), QWidget::setForegroundRole(), QWidget::setVisible(), and QETWidget::translateMouseEvent().
 {
     widget = widget->window();
     if (!modalState())
         return false;
     if (QApplication::activePopupWidget() == widget)
         return false;
     for (int i = 0; i < qt_modal_stack->size(); ++i) {
         QWidget *modalWidget = qt_modal_stack->at(i);
         {
             // check if the active modal widget is our widget or a parent of our widget
             QWidget *w = widget;
             while (w) {
                 if (w == modalWidget)
                     return false;
                 w = w->parentWidget();
             }
 #ifdef Q_WS_WIN
             if ((widget->testAttribute(Qt::WA_WState_Created) || widget->data->winid)
                 && (modalWidget->testAttribute(Qt::WA_WState_Created) || modalWidget->data->winid)
                 && IsChild(modalWidget->data->winid, widget->data->winid))
                 return false;
 #endif
         }
         Qt::WindowModality windowModality = modalWidget->windowModality();
         if (windowModality == Qt::NonModal) {
             // determine the modality type if it hasn't been set on the
             // modalWidget, this normally happens when waiting for a
             // native dialog. use WindowModal if we are the child of a
             // group leader; otherwise use ApplicationModal.
             QWidget *m = modalWidget;
             while (m && !m->testAttribute(Qt::WA_GroupLeader)) {
                 m = m->parentWidget();
                 if (m)
                     m = m->window();
             }
             windowModality = (m && m->testAttribute(Qt::WA_GroupLeader))
                              ? Qt::WindowModal
                              : Qt::ApplicationModal;
         }
         switch (windowModality) {
         case Qt::ApplicationModal:
             {
                 QWidget *groupLeaderForWidget = widget;
                 while (groupLeaderForWidget && !groupLeaderForWidget->testAttribute(Qt::WA_GroupLeader))
                     groupLeaderForWidget = groupLeaderForWidget->parentWidget();
                 if (groupLeaderForWidget) {
                     // if \a widget has WA_GroupLeader, it can only be blocked by ApplicationModal children
                     QWidget *m = modalWidget;
                     while (m && m != groupLeaderForWidget && !m->testAttribute(Qt::WA_GroupLeader))
                         m = m->parentWidget();
                     if (m == groupLeaderForWidget)
                         return true;
                 } else if (modalWidget != widget) {
                     return true;
                 }
                 break;
             }
         case Qt::WindowModal:
             {
                 QWidget *w = widget;
                 do {
                     QWidget *m = modalWidget;
                     do {
                         if (m == w)
                             return true;
                         m = m->parentWidget();
                         if (m)
                             m = m->window();
                     } while (m);
                     w = w->parentWidget();
                     if (w)
                         w = w->window();
                 } while (w);
                 break;
             }
         default:
             Q_ASSERT_X(false, "QApplication", "internal error, a modal widget cannot be modeless");
             break;
         }
     }
     return false;
 }
leaveModal()
void QApplicationPrivate::leaveModal (QWidget * widget) static
Warning
This function is not part of the public interface.
Definition at line 3074 of file qapplication.cpp.
Referenced by QWidget::destroy(), QWidgetPrivate::hide_helper(), QWidgetPrivate::isBackgroundInherited(), isServerProcess(), QPageSetupDialogPrivate::openCarbonPageLayout(), QPrintDialogPrivate::openCarbonPrintPanel(), QGtkStylePrivate::openDirectory(), QGtkStylePrivate::openFilename(), QGtkStylePrivate::openFilenames(), QPrintDialogPrivate::openWindowsPrintDialogModally(), QAxClientSite::qt_metacall(), qt_win_get_existing_directory(), qt_win_get_open_file_name(), qt_win_get_open_file_names(), qt_win_get_save_file_name(), QGtkStylePrivate::saveFilename(), and QWidget::setAttribute().
 {
     QSet<QWidget*> blocked;
     QList<QWidget*> windows = QApplication::topLevelWidgets();
     for (int i = 0; i < windows.count(); ++i) {
         QWidget *window = windows.at(i);
         if (window->windowType() != Qt::Tool && isBlockedByModal(window))
             blocked.insert(window);
     }
     leaveModal_sys(widget);
     windows = QApplication::topLevelWidgets();
     QEvent e(QEvent::WindowUnblocked);
     for (int i = 0; i < windows.count(); ++i) {
         QWidget *window = windows.at(i);
         if(blocked.contains(window) && window->windowType() != Qt::Tool && !isBlockedByModal(window))
             QApplication::sendEvent(window, &e);
     }
 }
leaveModal_sys()
void QApplicationPrivate::leaveModal_sys (QWidget * widget) static
Definition at line 1536 of file qapplication_mac.mm.
Referenced by qt_try_modal(), QtWndProc(), QApplication::qwsSetCustomColors(), and QApplication::x11EventFilter().
 {
     if (qt_modal_stack && qt_modal_stack->removeAll(widget)) {
 #ifdef DEBUG_MODAL_EVENTS
         qDebug("Leaving modal state with %s::%s::%p (%d)", widget->metaObject()->className(), widget->objectName().toLocal8Bit().constData(),
                widget, qt_modal_stack->count());
 #endif
         if (qt_modal_stack->isEmpty()) {
             delete qt_modal_stack;
             qt_modal_stack = 0;
             QPoint p(QCursor::pos());
             app_do_modal = false;
             QWidget* w = 0;
             if (QWidget *grabber = QWidget::mouseGrabber())
                 w = grabber;
             else
                 w = QApplication::widgetAt(p.x(), p.y());
             dispatchEnterLeave(w, qt_last_mouse_receiver); // send synthetic enter event
             qt_last_mouse_receiver = w;
         }
 #ifdef QT_MAC_USE_COCOA
         if (!qt_mac_is_macsheet(widget))
             QEventDispatcherMacPrivate::endModalSession(widget);
 #endif
     }
 #ifdef DEBUG_MODAL_EVENTS
     else qDebug("Failure to remove %s::%s::%p -- %p", widget->metaObject()->className(), widget->objectName().toLocal8Bit().constData(), widget, qt_modal_stack);
 #endif
     app_do_modal = (qt_modal_stack != 0);
     if (!app_do_modal)
         qt_event_request_menubarupdate();
 }
maxWindowRect()
QRect QApplicationPrivate::maxWindowRect (const QScreen * screen) const inline
Definition at line 519 of file qapplication_p.h.
Referenced by QWSServerPrivate::_q_newConnection(), QWSServer::setMaxWindowRect(), and setScreenTransformation().
 { return maxWindowRects[screen]; }
modalState()
bool QApplicationPrivate::modalState () static
Definition at line 1503 of file qapplication_mac.mm.
Referenced by QMenuPrivate::QMacMenuPrivate::addAction(), canQuit(), globalEventProcessor(), QMenuBarPrivate::macUpdateMenuBarImmediatly(), qt_mac_mouse_inside_answer_rect(), qt_try_modal(), QtWndProc(), QApplication::qwsSetCustomColors(), and QApplication::x11EventFilter().
 {
     return app_do_modal;
 }
notify_helper()
bool QApplicationPrivate::notify_helper (QObject * receiver, QEvent * e)
Definition at line 4635 of file qapplication.cpp.
 {
     // send to all application event filters
     if (sendThroughApplicationEventFilters(receiver, e))
         return true;
     if (receiver->isWidgetType()) {
         QWidget *widget = static_cast<QWidget *>(receiver);
 #if !defined(Q_WS_WINCE) || (defined(GWES_ICONCURS) && !defined(QT_NO_CURSOR))
         // toggle HasMouse widget state on enter and leave
         if ((e->type() == QEvent::Enter || e->type() == QEvent::DragEnter) &&
             (!QApplication::activePopupWidget() || QApplication::activePopupWidget() == widget->window()))
             widget->setAttribute(Qt::WA_UnderMouse, true);
         else if (e->type() == QEvent::Leave || e->type() == QEvent::DragLeave)
             widget->setAttribute(Qt::WA_UnderMouse, false);
 #endif
         if (QLayout *layout=widget->d_func()->layout) {
             layout->widgetEvent(e);
         }
     }
     // send to all receiver event filters
     if (sendThroughObjectEventFilters(receiver, e))
         return true;
     // deliver the event
     bool consumed = receiver->event(e);
     e->spont = false;
     return consumed;
 }
openPopup()
void QApplicationPrivate::openPopup (QWidget * popup)
Warning
This function is not part of the public interface.
Definition at line 2678 of file qapplication_mac.mm.
Referenced by qt_try_modal().
 {
     if (!QApplicationPrivate::popupWidgets)                        // create list
         QApplicationPrivate::popupWidgets = new QWidgetList;
     QApplicationPrivate::popupWidgets->append(popup);                // add to end of list
     // popups are not focus-handled by the window system (the first
     // popup grabbed the keyboard), so we have to do that manually: A
     // new popup gets the focus
     if (popup->focusWidget()) {
         popup->focusWidget()->setFocus(Qt::PopupFocusReason);
     } else if (QApplicationPrivate::popupWidgets->count() == 1) { // this was the first popup
         popup->setFocus(Qt::PopupFocusReason);
     }
 }
pickMouseReceiver()
QWidget * QApplicationPrivate::pickMouseReceiver (QWidget * candidate, const QPoint & globalPos, QPoint & pos, QEvent::Type type, Qt::MouseButtons buttons, QWidget * buttonDown, QWidget * alienWidget) static
Definition at line 3124 of file qapplication.cpp.
Referenced by QETWidget::translateMouseEvent().
 {
     Q_ASSERT(candidate);
     QWidget *mouseGrabber = QWidget::mouseGrabber();
     if (((type == QEvent::MouseMove && buttons) || (type == QEvent::MouseButtonRelease))
             && !buttonDown && !mouseGrabber) {
         return 0;
     }
     if (alienWidget && alienWidget->internalWinId())
         alienWidget = 0;
     QWidget *receiver = candidate;
     if (!mouseGrabber)
         mouseGrabber = (buttonDown && !isBlockedByModal(buttonDown)) ? buttonDown : alienWidget;
     if (mouseGrabber && mouseGrabber != candidate) {
         receiver = mouseGrabber;
         pos = receiver->mapFromGlobal(globalPos);
 #ifdef ALIEN_DEBUG
         qDebug() << "  ** receiver adjusted to:" << receiver << "pos:" << pos;
 #endif
     }
     return receiver;
 }
process_cmdline()
void QApplicationPrivate::process_cmdline ()
Warning
This function is not part of the public interface.
Definition at line 569 of file qapplication.cpp.
 {
     // process platform-indep command line
     if (!qt_is_gui_used || !argc)
         return;
     int i, j;
     j = 1;
     for (i=1; i<argc; i++) { // if you add anything here, modify QCoreApplication::arguments()
         if (argv[i] && *argv[i] != '-') {
             argv[j++] = argv[i];
             continue;
         }
         QByteArray arg = argv[i];
         arg = arg;
         QString s;
         if (arg == "-qdevel" || arg == "-qdebug") {
             // obsolete argument
         } else if (arg.indexOf("-style=", 0) != -1) {
             s = QString::fromLocal8Bit(arg.right(arg.length() - 7).toLower());
         } else if (arg == "-style" && i < argc-1) {
             s = QString::fromLocal8Bit(argv[++i]).toLower();
 #ifndef QT_NO_SESSIONMANAGER
         } else if (arg == "-session" && i < argc-1) {
             ++i;
             if (argv[i] && *argv[i]) {
                 session_id = QString::fromLatin1(argv[i]);
                 int p = session_id.indexOf(QLatin1Char('_'));
                 if (p >= 0) {
                     session_key = session_id.mid(p +1);
                     session_id = session_id.left(p);
                 }
                 is_session_restored = true;
             }
 #endif
 #ifndef QT_NO_STYLE_STYLESHEET
         } else if (arg == "-stylesheet" && i < argc -1) {
             styleSheet = QLatin1String("file:///");
             styleSheet.append(QString::fromLocal8Bit(argv[++i]));
         } else if (arg.indexOf("-stylesheet=") != -1) {
             styleSheet = QLatin1String("file:///");
             styleSheet.append(QString::fromLocal8Bit(arg.right(arg.length() - 12)));
 #endif
         } else if (qstrcmp(arg, "-reverse") == 0) {
             force_reverse = true;
             QApplication::setLayoutDirection(Qt::RightToLeft);
         } else if (qstrcmp(arg, "-widgetcount") == 0) {
             widgetCount = true;
         } else if (qstrcmp(arg, "-testability") == 0) {
             load_testability = true;
         } else if (arg == "-graphicssystem" && i < argc-1) {
             graphics_system_name = QString::fromLocal8Bit(argv[++i]);
         } else {
             argv[j++] = argv[i];
         }
         if (!s.isEmpty()) {
             if (app_style) {
                 delete app_style;
                 app_style = 0;
             }
             styleOverride = s;
         }
     }
     if(j < argc) {
         argv[j] = 0;
         argc = j;
     }
 }
qt_mac_apply_settings()
bool QApplicationPrivate::qt_mac_apply_settings () static
Warning
This function is not part of the public interface.
Definition at line 2902 of file qapplication_mac.mm.
Referenced by qt_init().
 {
     QSettings settings(QSettings::UserScope, QLatin1String("Trolltech"));
     settings.beginGroup(QLatin1String("Qt"));
     /*
       Qt settings.  This is how they are written into the datastream.
       Palette/ *             - QPalette
       font                   - QFont
       libraryPath            - QStringList
       style                  - QString
       doubleClickInterval    - int
       cursorFlashTime        - int
       wheelScrollLines       - int
       colorSpec              - QString
       defaultCodec           - QString
       globalStrut/width      - int
       globalStrut/height     - int
       GUIEffects             - QStringList
       Font Substitutions/ *  - QStringList
       Font Substitutions/... - QStringList
     */
     // read library (ie. plugin) path list
     QString libpathkey =
         QString::fromLatin1("%1.%2/libraryPath")
                     .arg(QT_VERSION >> 16)
                     .arg((QT_VERSION & 0xff00) >> 8);
     QStringList pathlist = settings.value(libpathkey).toString().split(QLatin1Char(':'));
     if (!pathlist.isEmpty()) {
         QStringList::ConstIterator it = pathlist.begin();
         while(it != pathlist.end())
             QApplication::addLibraryPath(*it++);
     }
     QString defaultcodec = settings.value(QLatin1String("defaultCodec"), QVariant(QLatin1String("none"))).toString();
     if (defaultcodec != QLatin1String("none")) {
         QTextCodec *codec = QTextCodec::codecForName(defaultcodec.toLatin1().constData());
         if (codec)
             QTextCodec::setCodecForTr(codec);
     }
     if (qt_is_gui_used) {
         QString str;
         QStringList strlist;
         int num;
         // read new palette
         int i;
         QPalette pal(QApplication::palette());
         strlist = settings.value(QLatin1String("Palette/active")).toStringList();
         if (strlist.count() == QPalette::NColorRoles) {
             for (i = 0; i < QPalette::NColorRoles; i++)
                 pal.setColor(QPalette::Active, (QPalette::ColorRole) i,
                             QColor(strlist[i]));
         }
         strlist = settings.value(QLatin1String("Palette/inactive")).toStringList();
         if (strlist.count() == QPalette::NColorRoles) {
             for (i = 0; i < QPalette::NColorRoles; i++)
                 pal.setColor(QPalette::Inactive, (QPalette::ColorRole) i,
                             QColor(strlist[i]));
         }
         strlist = settings.value(QLatin1String("Palette/disabled")).toStringList();
         if (strlist.count() == QPalette::NColorRoles) {
             for (i = 0; i < QPalette::NColorRoles; i++)
                 pal.setColor(QPalette::Disabled, (QPalette::ColorRole) i,
                             QColor(strlist[i]));
         }
         if (pal != QApplication::palette())
             QApplication::setPalette(pal);
         // read new font
         QFont font(QApplication::font());
         str = settings.value(QLatin1String("font")).toString();
         if (!str.isEmpty()) {
             font.fromString(str);
             if (font != QApplication::font())
                 QApplication::setFont(font);
         }
         // read new QStyle
         QString stylename = settings.value(QLatin1String("style")).toString();
         if (! stylename.isNull() && ! stylename.isEmpty()) {
             QStyle *style = QStyleFactory::create(stylename);
             if (style)
                 QApplication::setStyle(style);
             else
                 stylename = QLatin1String("default");
         } else {
             stylename = QLatin1String("default");
         }
         num = settings.value(QLatin1String("doubleClickInterval"),
                             QApplication::doubleClickInterval()).toInt();
         QApplication::setDoubleClickInterval(num);
         num = settings.value(QLatin1String("cursorFlashTime"),
                             QApplication::cursorFlashTime()).toInt();
         QApplication::setCursorFlashTime(num);
 #ifndef QT_NO_WHEELEVENT
         num = settings.value(QLatin1String("wheelScrollLines"),
                             QApplication::wheelScrollLines()).toInt();
         QApplication::setWheelScrollLines(num);
 #endif
         QString colorspec = settings.value(QLatin1String("colorSpec"),
                                             QVariant(QLatin1String("default"))).toString();
         if (colorspec == QLatin1String("normal"))
             QApplication::setColorSpec(QApplication::NormalColor);
         else if (colorspec == QLatin1String("custom"))
             QApplication::setColorSpec(QApplication::CustomColor);
         else if (colorspec == QLatin1String("many"))
             QApplication::setColorSpec(QApplication::ManyColor);
         else if (colorspec != QLatin1String("default"))
             colorspec = QLatin1String("default");
         int w = settings.value(QLatin1String("globalStrut/width")).toInt();
         int h = settings.value(QLatin1String("globalStrut/height")).toInt();
         QSize strut(w, h);
         if (strut.isValid())
             QApplication::setGlobalStrut(strut);
         QStringList effects = settings.value(QLatin1String("GUIEffects")).toStringList();
         if (!effects.isEmpty()) {
             if (effects.contains(QLatin1String("none")))
                 QApplication::setEffectEnabled(Qt::UI_General, false);
             if (effects.contains(QLatin1String("general")))
                 QApplication::setEffectEnabled(Qt::UI_General, true);
             if (effects.contains(QLatin1String("animatemenu")))
                 QApplication::setEffectEnabled(Qt::UI_AnimateMenu, true);
             if (effects.contains(QLatin1String("fademenu")))
                 QApplication::setEffectEnabled(Qt::UI_FadeMenu, true);
             if (effects.contains(QLatin1String("animatecombo")))
                 QApplication::setEffectEnabled(Qt::UI_AnimateCombo, true);
             if (effects.contains(QLatin1String("animatetooltip")))
                 QApplication::setEffectEnabled(Qt::UI_AnimateTooltip, true);
             if (effects.contains(QLatin1String("fadetooltip")))
                 QApplication::setEffectEnabled(Qt::UI_FadeTooltip, true);
             if (effects.contains(QLatin1String("animatetoolbox")))
                 QApplication::setEffectEnabled(Qt::UI_AnimateToolBox, true);
         } else {
             QApplication::setEffectEnabled(Qt::UI_General, true);
         }
         settings.beginGroup(QLatin1String("Font Substitutions"));
         QStringList fontsubs = settings.childKeys();
         if (!fontsubs.isEmpty()) {
             QStringList::Iterator it = fontsubs.begin();
             for (; it != fontsubs.end(); ++it) {
                 QString fam = QString::fromLatin1((*it).toLatin1().constData());
                 QStringList subs = settings.value(fam).toStringList();
                 QFont::insertSubstitutions(fam, subs);
             }
         }
         settings.endGroup();
     }
     settings.endGroup();
     return true;
 }
removeTouchPoint()
void QApplicationPrivate::removeTouchPoint (int touchPointId)
reset_instance_pointer()
void QApplicationPrivate::reset_instance_pointer () static
Warning
This function is not part of the public interface. Resets the QApplication::instance() pointer to zero
Definition at line 1086 of file qapplication_x11.cpp.
Referenced by qt_init(), and qt_xio_errhandler().
 { QApplication::self = 0; }
sendMouseEvent()
bool QApplicationPrivate::sendMouseEvent (QWidget * receiver, QMouseEvent * event, QWidget * alienWidget, QWidget * native, QWidget ** buttonDown, QPointer< QWidget > & lastMouseReceiver, bool spontaneous = true) static
Definition at line 3160 of file qapplication.cpp.
Referenced by flipPoint(), QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent(), and QETWidget::translateMouseEvent().
 {
     Q_ASSERT(receiver);
     Q_ASSERT(event);
     Q_ASSERT(nativeWidget);
     Q_ASSERT(buttonDown);
     if (alienWidget && !isAlien(alienWidget))
         alienWidget = 0;
     QPointer<QWidget> receiverGuard = receiver;
     QPointer<QWidget> nativeGuard = nativeWidget;
     QPointer<QWidget> alienGuard = alienWidget;
     QPointer<QWidget> activePopupWidget = QApplication::activePopupWidget();
     const bool graphicsWidget = nativeWidget->testAttribute(Qt::WA_DontShowOnScreen);
     if (*buttonDown) {
         if (!graphicsWidget) {
             // Register the widget that shall receive a leave event
             // after the last button is released.
             if ((alienWidget || !receiver->internalWinId()) && !leaveAfterRelease && !QWidget::mouseGrabber())
                 leaveAfterRelease = *buttonDown;
             if (event->type() == QEvent::MouseButtonRelease && !event->buttons())
                 *buttonDown = 0;
         }
     } else if (lastMouseReceiver) {
         // Dispatch enter/leave if we move:
         // 1) from an alien widget to another alien widget or
         //    from a native widget to an alien widget (first OR case)
         // 2) from an alien widget to a native widget (second OR case)
         if ((alienWidget && alienWidget != lastMouseReceiver)
             || (isAlien(lastMouseReceiver) && !alienWidget)) {
             if (activePopupWidget) {
                 if (!QWidget::mouseGrabber())
                     dispatchEnterLeave(alienWidget ? alienWidget : nativeWidget, lastMouseReceiver);
             } else {
                 dispatchEnterLeave(receiver, lastMouseReceiver);
             }
         }
     }
 #ifdef ALIEN_DEBUG
     qDebug() << "QApplicationPrivate::sendMouseEvent: receiver:" << receiver
              << "pos:" << event->pos() << "alien" << alienWidget << "button down"
              << *buttonDown << "last" << lastMouseReceiver << "leave after release"
              << leaveAfterRelease;
 #endif
     // We need this quard in case someone opens a modal dialog / popup. If that's the case
     // leaveAfterRelease is set to null, but we shall not update lastMouseReceiver.
     const bool wasLeaveAfterRelease = leaveAfterRelease != 0;
     bool result;
     if (spontaneous)
         result = QApplication::sendSpontaneousEvent(receiver, event);
     else
         result = QApplication::sendEvent(receiver, event);
     if (!graphicsWidget && leaveAfterRelease && event->type() == QEvent::MouseButtonRelease
         && !event->buttons() && QWidget::mouseGrabber() != leaveAfterRelease) {
         // Dispatch enter/leave if:
         // 1) the mouse grabber is an alien widget
         // 2) the button is released on an alien widget
         QWidget *enter = 0;
         if (nativeGuard)
             enter = alienGuard ? alienWidget : nativeWidget;
         else // The receiver is typically deleted on mouse release with drag'n'drop.
             enter = QApplication::widgetAt(event->globalPos());
         dispatchEnterLeave(enter, leaveAfterRelease);
         leaveAfterRelease = 0;
         lastMouseReceiver = enter;
     } else if (!wasLeaveAfterRelease) {
         if (activePopupWidget) {
             if (!QWidget::mouseGrabber())
                 lastMouseReceiver = alienGuard ? alienWidget : (nativeGuard ? nativeWidget : 0);
         } else {
             lastMouseReceiver = receiverGuard ? receiver : QApplication::widgetAt(event->globalPos());
         }
     }
     return result;
 }
sendSyntheticEnterLeave()
void QApplicationPrivate::sendSyntheticEnterLeave (QWidget * widget)
Definition at line 3256 of file qapplication.cpp.
 {
 #ifndef QT_NO_CURSOR
 #if defined(Q_WS_QWS) || defined(Q_WS_QPA)
     if (!widget || widget->isWindow())
         return;
 #else
     if (!widget || widget->internalWinId() || widget->isWindow())
         return;
 #endif
     const bool widgetInShow = widget->isVisible() && !widget->data->in_destructor;
     if (!widgetInShow && widget != qt_last_mouse_receiver)
         return; // Widget was not under the cursor when it was hidden/deleted.
     if (widgetInShow && widget->parentWidget()->data->in_show)
         return; // Ingore recursive show.
     QWidget *mouseGrabber = QWidget::mouseGrabber();
     if (mouseGrabber && mouseGrabber != widget)
         return; // Someone else has the grab; enter/leave should not occur.
     QWidget *tlw = widget->window();
     if (tlw->data->in_destructor || tlw->data->is_closing)
         return; // Closing down the business.
     if (widgetInShow && (!qt_last_mouse_receiver || qt_last_mouse_receiver->window() != tlw))
         return; // Mouse cursor not inside the widget's top-level.
     const QPoint globalPos(QCursor::pos());
     QPoint pos = tlw->mapFromGlobal(globalPos);
     // Find the current widget under the mouse. If this function was called from
     // the widget's destructor, we have to make sure childAt() doesn't take into
     // account widgets that are about to be destructed.
     QWidget *widgetUnderCursor = tlw->d_func()->childAt_helper(pos, widget->data->in_destructor);
     if (!widgetUnderCursor)
         widgetUnderCursor = tlw;
     else
         pos = widgetUnderCursor->mapFrom(tlw, pos);
     if (widgetInShow && widgetUnderCursor != widget && !widget->isAncestorOf(widgetUnderCursor))
         return; // Mouse cursor not inside the widget or any of its children.
     if (widget->data->in_destructor && qt_button_down == widget)
         qt_button_down = 0;
     // Send enter/leave events followed by a mouse move on the entered widget.
     QMouseEvent e(QEvent::MouseMove, pos, globalPos, Qt::NoButton, Qt::NoButton, Qt::NoModifier);
     sendMouseEvent(widgetUnderCursor, &e, widgetUnderCursor, tlw, &qt_button_down, qt_last_mouse_receiver);
 #endif // QT_NO_CURSOR
 }
setFocusWidget()
void QApplicationPrivate::setFocusWidget (QWidget * focus, Qt::FocusReason reason) static
Definition at line 2233 of file qapplication.cpp.
Referenced by QWidget::clearFocus(), make_widget_eventUPP(), QApplication::setActiveWindow(), and QWidget::setFocus().
 {
 #ifndef QT_NO_GRAPHICSVIEW
     if (focus && focus->window()->graphicsProxyWidget())
         return;
 #endif
     hidden_focus_widget = 0;
     if (focus != focus_widget) {
         if (focus && focus->isHidden()) {
             hidden_focus_widget = focus;
             return;
         }
         if (focus && (reason == Qt::BacktabFocusReason || reason == Qt::TabFocusReason)
             && qt_in_tab_key_event)
             focus->window()->setAttribute(Qt::WA_KeyboardFocusChange);
         else if (focus && reason == Qt::ShortcutFocusReason) {
             focus->window()->setAttribute(Qt::WA_KeyboardFocusChange);
         }
         QWidget *prev = focus_widget;
         focus_widget = focus;
 #ifndef QT_NO_IM
         if (prev && ((reason != Qt::PopupFocusReason && reason != Qt::MenuBarFocusReason
             && prev->testAttribute(Qt::WA_InputMethodEnabled))
             // Do reset the input context, in case the new focus widget won't accept keyboard input
             // or it is not created fully yet.
             || (focus_widget && (!focus_widget->testAttribute(Qt::WA_InputMethodEnabled)
             || !focus_widget->testAttribute(Qt::WA_WState_Created))))) {
              QInputContext *qic = prev->inputContext();
             if(qic) {
                 qic->reset();
                 qic->setFocusWidget(0);
             }
         }
 #endif //QT_NO_IM
         if(focus_widget)
             focus_widget->d_func()->setFocus_sys();
         if (reason != Qt::NoFocusReason) {
             //send events
             if (prev) {
 #ifdef QT_KEYPAD_NAVIGATION
                 if (QApplication::keypadNavigationEnabled()) {
                     if (prev->hasEditFocus() && reason != Qt::PopupFocusReason
 #ifdef Q_OS_SYMBIAN
                             && reason != Qt::ActiveWindowFocusReason
 #endif
                             )
                         prev->setEditFocus(false);
                 }
 #endif
 #ifndef QT_NO_IM
                 if (focus) {
                     QInputContext *prevIc;
                     prevIc = prev->inputContext();
                     if (prevIc && prevIc != focus->inputContext()) {
                         QEvent closeSIPEvent(QEvent::CloseSoftwareInputPanel);
                         QApplication::sendEvent(prev, &closeSIPEvent);
                     }
                 }
 #endif
                 QFocusEvent out(QEvent::FocusOut, reason);
                 QPointer<QWidget> that = prev;
                 QApplication::sendEvent(prev, &out);
                 if (that)
                     QApplication::sendEvent(that->style(), &out);
             }
             if(focus && QApplicationPrivate::focus_widget == focus) {
 #ifndef QT_NO_IM
                 if (focus->testAttribute(Qt::WA_InputMethodEnabled)) {
                     QInputContext *qic = focus->inputContext();
                     if (qic && focus->testAttribute(Qt::WA_WState_Created)
                         && focus->isEnabled())
                         qic->setFocusWidget(focus);
                 }
 #endif //QT_NO_IM
                 QFocusEvent in(QEvent::FocusIn, reason);
                 QPointer<QWidget> that = focus;
                 QApplication::sendEvent(focus, &in);
                 if (that)
                     QApplication::sendEvent(that->style(), &in);
             }
             emit qApp->focusChanged(prev, focus_widget);
         }
     }
 }
setMaxWindowRect()
void QApplicationPrivate::setMaxWindowRect (const QScreen * screen, int screenNo, const QRect & rect)
Definition at line 243 of file qapplication_qws.cpp.
Referenced by QWSServer::endDisplayReconfigure(), QWSDisplay::Data::fillQueue(), QApplication::qwsProcessEvent(), setMaxWindowRect(), and QWSServer::setMaxWindowRect().
 {
     if (maxWindowRects.value(screen) == rect)
         return;
     maxWindowRects[screen] = rect;
     // Re-resize any maximized windows
     QWidgetList l = QApplication::topLevelWidgets();
     for (int i = 0; i < l.size(); ++i) {
         QWidget *w = l.at(i);
         QScreen *s = w->d_func()->getScreen();
         if (s == screen) {
             if (w->isMaximized())
                 w->d_func()->setMaxWindowState_helper();
             else if (w->isFullScreen())
                 w->d_func()->setFullScreenSize_helper();
         }
     }
     if ( qt_desktopWidget ) // XXX workaround crash
         emit QApplication::desktop()->workAreaResized(screenNo);
 }
setPalette_helper()
void QApplicationPrivate::setPalette_helper (const QPalette & palette, const char * className, bool clearWidgetPaletteHash) static
Definition at line 1864 of file qapplication.cpp.
Referenced by QApplication::setPalette(), and QApplication::setStyle().
 {
     QPalette pal = palette;
     if (QApplicationPrivate::app_style)
         QApplicationPrivate::app_style->polish(pal); // NB: non-const reference
     bool all = false;
     PaletteHash *hash = app_palettes();
     if (!className) {
         if (QApplicationPrivate::app_pal && pal.isCopyOf(*QApplicationPrivate::app_pal))
             return;
         if (!QApplicationPrivate::app_pal)
             QApplicationPrivate::app_pal = new QPalette(pal);
         else
             *QApplicationPrivate::app_pal = pal;
         if (hash && hash->size()) {
             all = true;
             if (clearWidgetPaletteHash)
                 hash->clear();
         }
     } else if (hash) {
         hash->insert(className, pal);
     }
     if (QApplicationPrivate::is_app_running && !QApplicationPrivate::is_app_closing) {
         // Send ApplicationPaletteChange to qApp itself, and to the widgets.
         QEvent e(QEvent::ApplicationPaletteChange);
         QApplication::sendEvent(QApplication::instance(), &e);
         QWidgetList wids = QApplication::allWidgets();
         for (QWidgetList::ConstIterator it = wids.constBegin(); it != wids.constEnd(); ++it) {
             register QWidget *w = *it;
             if (all || (!className && w->isWindow()) || w->inherits(className)) // matching class
                 QApplication::sendEvent(w, &e);
         }
         // Send to all scenes as well.
 #ifndef QT_NO_GRAPHICSVIEW
         QList<QGraphicsScene *> &scenes = qApp->d_func()->scene_list;
         for (QList<QGraphicsScene *>::ConstIterator it = scenes.constBegin();
              it != scenes.constEnd(); ++it) {
             QApplication::sendEvent(*it, &e);
         }
 #endif //QT_NO_GRAPHICSVIEW
     }
     if (!className && (!QApplicationPrivate::sys_pal || !palette.isCopyOf(*QApplicationPrivate::sys_pal))) {
         if (!QApplicationPrivate::set_pal)
             QApplicationPrivate::set_pal = new QPalette(palette);
         else
             *QApplicationPrivate::set_pal = palette;
     }
 }
setScreenTransformation()
void QApplicationPrivate::setScreenTransformation (QScreen * screen, int screenNo, int transformation)
Definition at line 329 of file qapplication_qws.cpp.
Referenced by QWSDisplay::Data::fillQueue(), QApplication::qwsProcessEvent(), and setScreenTransformation().
 {
     QScreen *transformed = screen;
     while (transformed->classId() == QScreen::ProxyClass)
         transformed = static_cast<QProxyScreen*>(transformed)->screen();
     if (transformed->classId() != QScreen::TransformedClass)
         return;
     TransformFunc setScreenTransformation = getTransformationFunction();
     if (!setScreenTransformation)
         return;
     setScreenTransformation(transformed, transformation);
     // need to re-configure() proxies bottom-up
     if (screen->classId() == QScreen::ProxyClass) {
         QList<QProxyScreen*> proxies;
         QScreen *s = screen;
         do {
             QProxyScreen *proxy = static_cast<QProxyScreen*>(s);
             proxies.append(proxy);
             s = proxy->screen();
         } while (s->classId() == QScreen::ProxyClass);
         do {
             QProxyScreen *proxy = proxies.takeLast();
             proxy->setScreen(proxy->screen()); // triggers configure()
         } while (!proxies.isEmpty());
     }
     if (qt_desktopWidget) { // XXX workaround crash for early screen transform events
         QDesktopWidget *desktop = QApplication::desktop();
         emit desktop->resized(screenNo);
         if (maxWindowRect(screen).isEmpty()) // not explicitly set
             emit desktop->workAreaResized(screenNo);
     }
     QWSServer *server = QWSServer::instance();
     if (server) {
         server->updateWindowRegions();
         QRegion r = screen->region();
         server->refresh(r);
     }
     // make sure maximized and fullscreen windows are updated
     QWidgetList list = QApplication::topLevelWidgets();
     for (int i = list.size() - 1; i >= 0; --i) {
         QWidget *w = list.at(i);
         if (w->isFullScreen())
             w->d_func()->setFullScreenSize_helper();
         else if (w->isMaximized())
             w->d_func()->setMaxWindowState_helper();
     }
 }
setSystemFont()
void QApplicationPrivate::setSystemFont (const QFont & font) static
Warning
This function is not part of the public interface.
Definition at line 2123 of file qapplication.cpp.
Referenced by init_display(), QGtkStyle::polish(), qt_init(), qt_set_windows_font_resources(), qt_set_x11_resources(), and x11_apply_settings().
 {
      if (!sys_font)
         sys_font = new QFont(font);
     else
         *sys_font = font;
     if (!QApplicationPrivate::set_font)
         QApplication::setFont(*sys_font);
 }
setSystemPalette()
void QApplicationPrivate::setSystemPalette (const QPalette & pal) static
Definition at line 1948 of file qapplication.cpp.
Referenced by QGtkStyle::polish(), qt_set_windows_color_resources(), QApplication::setStyle(), QApplication::style(), QGtkStyleUpdateScheduler::updateTheme(), and x11_apply_settings().
 {
     QPalette adjusted;
 #if 0
     // adjust the system palette to avoid dithering
     QColormap cmap = QColormap::instance();
     if (cmap.depths() > 4 && cmap.depths() < 24) {
         for (int g = 0; g < QPalette::NColorGroups; g++)
             for (int i = 0; i < QPalette::NColorRoles; i++) {
                 QColor color = pal.color((QPalette::ColorGroup)g, (QPalette::ColorRole)i);
                 color = cmap.colorAt(cmap.pixel(color));
                 adjusted.setColor((QPalette::ColorGroup)g, (QPalette::ColorRole) i, color);
             }
     }
 #else
     adjusted = pal;
 #endif
     if (!sys_pal)
         sys_pal = new QPalette(adjusted);
     else
         *sys_pal = adjusted;
     if (!QApplicationPrivate::set_pal)
         QApplication::setPalette(*sys_pal);
 }
shouldSetFocus()
bool QApplicationPrivate::shouldSetFocus (QWidget * w, Qt::FocusPolicy policy) static private
Definition at line 5832 of file qapplication.cpp.
Referenced by giveFocusAccordingToFocusPolicy().
 {
     QWidget *f = w;
     while (f->d_func()->extra && f->d_func()->extra->focus_proxy)
         f = f->d_func()->extra->focus_proxy;
     if ((w->focusPolicy() & policy) != policy)
         return false;
     if (w != f && (f->focusPolicy() & policy) != policy)
         return false;
     return true;
 }
tabletProximityCallback()
OSStatus QApplicationPrivate::tabletProximityCallback (EventHandlerCallRef , EventRef carbonEvent, void *) static
Definition at line 1618 of file qapplication_mac.mm.
Referenced by qt_init().
 {
     OSType eventClass = GetEventClass(carbonEvent);
     UInt32 eventKind = GetEventKind(carbonEvent);
     if (eventClass != kEventClassTablet || eventKind != kEventTabletProximity)
         return eventNotHandledErr;
     // Get the current point of the device and its unique ID.
     ::TabletProximityRec proxRec;
     GetEventParameter(carbonEvent, kEventParamTabletProximityRec, typeTabletProximityRec, 0,
                       sizeof(proxRec), 0, &proxRec);
     qt_dispatchTabletProximityEvent(proxRec);
     return noErr;
 }
translateRawTouchEvent()
void QApplicationPrivate::translateRawTouchEvent (QWidget * widget, QTouchEvent::DeviceType deviceType, const QList< QTouchEvent::TouchPoint > & touchPoints) static
Definition at line 6031 of file qapplication.cpp.
Referenced by qt_cleanup(), and qt_translateRawTouchEvent().
 {
     QApplicationPrivate *d = self;
     typedef QPair<Qt::TouchPointStates, QList<QTouchEvent::TouchPoint> > StatesAndTouchPoints;
     QHash<QWidget *, StatesAndTouchPoints> widgetsNeedingEvents;
     for (int i = 0; i < touchPoints.count(); ++i) {
         QTouchEvent::TouchPoint touchPoint = touchPoints.at(i);
         // explicitly detach from the original touch point that we got, so even
         // if the touchpoint structs are reused, we will make a copy that we'll
         // deliver to the user (which might want to store the struct for later use).
         touchPoint.d = touchPoint.d->detach();
         // update state
         QWeakPointer<QWidget> widget;
         switch (touchPoint.state()) {
         case Qt::TouchPointPressed:
         {
             if (deviceType == QTouchEvent::TouchPad) {
                 // on touch-pads, send all touch points to the same widget
                 widget = d->widgetForTouchPointId.isEmpty()
                          ? QWeakPointer<QWidget>()
                          : d->widgetForTouchPointId.constBegin().value();
             }
             if (!widget) {
                 // determine which widget this event will go to
                 if (!window)
                     window = QApplication::topLevelAt(touchPoint.screenPos().toPoint());
                 if (!window)
                     continue;
                 widget = window->childAt(window->mapFromGlobal(touchPoint.screenPos().toPoint()));
                 if (!widget)
                     widget = window;
             }
             if (deviceType == QTouchEvent::TouchScreen) {
                 int closestTouchPointId = d->findClosestTouchPointId(touchPoint.screenPos());
                 QWidget *closestWidget = d->widgetForTouchPointId.value(closestTouchPointId).data();
                 if (closestWidget
                     && (widget.data()->isAncestorOf(closestWidget) || closestWidget->isAncestorOf(widget.data()))) {
                     widget = closestWidget;
                 }
             }
             d->widgetForTouchPointId[touchPoint.id()] = widget;
             touchPoint.d->startScreenPos = touchPoint.screenPos();
             touchPoint.d->lastScreenPos = touchPoint.screenPos();
             touchPoint.d->startNormalizedPos = touchPoint.normalizedPos();
             touchPoint.d->lastNormalizedPos = touchPoint.normalizedPos();
             if (touchPoint.pressure() < qreal(0.))
                 touchPoint.d->pressure = qreal(1.);
             d->appCurrentTouchPoints.insert(touchPoint.id(), touchPoint);
             break;
         }
         case Qt::TouchPointReleased:
         {
             widget = d->widgetForTouchPointId.take(touchPoint.id());
             if (!widget)
                 continue;
             QTouchEvent::TouchPoint previousTouchPoint = d->appCurrentTouchPoints.take(touchPoint.id());
             touchPoint.d->startScreenPos = previousTouchPoint.startScreenPos();
             touchPoint.d->lastScreenPos = previousTouchPoint.screenPos();
             touchPoint.d->startPos = previousTouchPoint.startPos();
             touchPoint.d->lastPos = previousTouchPoint.pos();
             touchPoint.d->startNormalizedPos = previousTouchPoint.startNormalizedPos();
             touchPoint.d->lastNormalizedPos = previousTouchPoint.normalizedPos();
             if (touchPoint.pressure() < qreal(0.))
                 touchPoint.d->pressure = qreal(0.);
             break;
         }
         default:
             widget = d->widgetForTouchPointId.value(touchPoint.id());
             if (!widget)
                 continue;
             Q_ASSERT(d->appCurrentTouchPoints.contains(touchPoint.id()));
             QTouchEvent::TouchPoint previousTouchPoint = d->appCurrentTouchPoints.value(touchPoint.id());
             touchPoint.d->startScreenPos = previousTouchPoint.startScreenPos();
             touchPoint.d->lastScreenPos = previousTouchPoint.screenPos();
             touchPoint.d->startPos = previousTouchPoint.startPos();
             touchPoint.d->lastPos = previousTouchPoint.pos();
             touchPoint.d->startNormalizedPos = previousTouchPoint.startNormalizedPos();
             touchPoint.d->lastNormalizedPos = previousTouchPoint.normalizedPos();
             if (touchPoint.pressure() < qreal(0.))
                 touchPoint.d->pressure = qreal(1.);
             d->appCurrentTouchPoints[touchPoint.id()] = touchPoint;
             break;
         }
         Q_ASSERT(widget.data() != 0);
         // make the *scene* functions return the same as the *screen* functions
         touchPoint.d->sceneRect = touchPoint.screenRect();
         touchPoint.d->startScenePos = touchPoint.startScreenPos();
         touchPoint.d->lastScenePos = touchPoint.lastScreenPos();
         StatesAndTouchPoints &maskAndPoints = widgetsNeedingEvents[widget.data()];
         maskAndPoints.first |= touchPoint.state();
         if (touchPoint.isPrimary())
             maskAndPoints.first |= Qt::TouchPointPrimary;
         maskAndPoints.second.append(touchPoint);
     }
     if (widgetsNeedingEvents.isEmpty())
         return;
     QHash<QWidget *, StatesAndTouchPoints>::ConstIterator it = widgetsNeedingEvents.constBegin();
     const QHash<QWidget *, StatesAndTouchPoints>::ConstIterator end = widgetsNeedingEvents.constEnd();
     for (; it != end; ++it) {
         QWidget *widget = it.key();
         if (!QApplicationPrivate::tryModalHelper(widget, 0))
             continue;
         QEvent::Type eventType;
         switch (it.value().first & Qt::TouchPointStateMask) {
         case Qt::TouchPointPressed:
             eventType = QEvent::TouchBegin;
             break;
         case Qt::TouchPointReleased:
             eventType = QEvent::TouchEnd;
             break;
         case Qt::TouchPointStationary:
             // don't send the event if nothing changed
             continue;
         default:
             eventType = QEvent::TouchUpdate;
             break;
         }
         QTouchEvent touchEvent(eventType,
                                deviceType,
                                QApplication::keyboardModifiers(),
                                it.value().first,
                                it.value().second);
         updateTouchPointsForWidget(widget, &touchEvent);
         switch (touchEvent.type()) {
         case QEvent::TouchBegin:
         {
             // if the TouchBegin handler recurses, we assume that means the event
             // has been implicitly accepted and continue to send touch events
             widget->setAttribute(Qt::WA_WState_AcceptedTouchBeginEvent);
             (void ) QApplication::sendSpontaneousEvent(widget, &touchEvent);
             break;
         }
         default:
             if (widget->testAttribute(Qt::WA_WState_AcceptedTouchBeginEvent)) {
                 if (touchEvent.type() == QEvent::TouchEnd)
                     widget->setAttribute(Qt::WA_WState_AcceptedTouchBeginEvent, false);
                 (void) QApplication::sendSpontaneousEvent(widget, &touchEvent);
             }
             break;
         }
     }
 }
translateTouchEvent()
bool QApplicationPrivate::translateTouchEvent (const MSG & msg)
Definition at line 4222 of file qapplication_win.cpp.
Referenced by QtWndProc().
 {
     QWidget *widgetForHwnd = QWidget::find(msg.hwnd);
     if (!widgetForHwnd)
         return false;
     QRect screenGeometry = QApplication::desktop()->screenGeometry(widgetForHwnd);
     QList<QTouchEvent::TouchPoint> touchPoints;
     QVector<TOUCHINPUT> winTouchInputs(msg.wParam);
     memset(winTouchInputs.data(), 0, sizeof(TOUCHINPUT) * winTouchInputs.count());
     Qt::TouchPointStates allStates = 0;
     QApplicationPrivate::GetTouchInputInfo((HANDLE) msg.lParam, msg.wParam, winTouchInputs.data(), sizeof(TOUCHINPUT));
     for (int i = 0; i < winTouchInputs.count(); ++i) {
         const TOUCHINPUT &touchInput = winTouchInputs.at(i);
         int touchPointID = touchInputIDToTouchPointID.value(touchInput.dwID, -1);
         if (touchPointID == -1) {
             touchPointID = touchInputIDToTouchPointID.count();
             touchInputIDToTouchPointID.insert(touchInput.dwID, touchPointID);
         }
         QTouchEvent::TouchPoint touchPoint(touchPointID);
         // update state
         QPointF screenPos(qreal(touchInput.x) / qreal(100.), qreal(touchInput.y) / qreal(100.));
         QRectF screenRect;
         if (touchInput.dwMask & TOUCHINPUTMASKF_CONTACTAREA)
             screenRect.setSize(QSizeF(qreal(touchInput.cxContact) / qreal(100.),
                                       qreal(touchInput.cyContact) / qreal(100.)));
         screenRect.moveCenter(screenPos);
         Qt::TouchPointStates state;
         if (touchInput.dwFlags & TOUCHEVENTF_DOWN) {
             state = Qt::TouchPointPressed;
         } else if (touchInput.dwFlags & TOUCHEVENTF_UP) {
             state = Qt::TouchPointReleased;
         } else {
             state = (screenPos == touchPoint.screenPos()
                      ? Qt::TouchPointStationary
                      : Qt::TouchPointMoved);
         }
         if (touchInput.dwFlags & TOUCHEVENTF_PRIMARY)
             state |= Qt::TouchPointPrimary;
         touchPoint.setState(state);
         touchPoint.setScreenRect(screenRect);
         touchPoint.setNormalizedPos(QPointF(screenPos.x() / screenGeometry.width(),
                                             screenPos.y() / screenGeometry.height()));
         allStates |= state;
         touchPoints.append(touchPoint);
     }
     QApplicationPrivate::CloseTouchInputHandle((HANDLE) msg.lParam);
     if ((allStates & Qt::TouchPointStateMask) == Qt::TouchPointReleased) {
         // all touch points released, forget the ids we've seen, they may not be reused
         touchInputIDToTouchPointID.clear();
     }
     translateRawTouchEvent(widgetForHwnd, QTouchEvent::TouchScreen, touchPoints);
     return true;
 }
tryModalHelper()
bool QApplicationPrivate::tryModalHelper (QWidget * widget, QWidget ** rettop = 0) static
Warning
This function is not part of the public interface.
Called from qapplication_platform.cpp, returns true if the widget should accept the event.
Definition at line 3102 of file qapplication.cpp.
Referenced by QShortcutMap::correctGraphicsWidgetContext(), QShortcutMap::correctWidgetContext(), dispatchEnterLeave(), QOleDropTarget::DragEnter(), QOleDropTarget::DragLeave(), QOleDropTarget::DragOver(), QOleDropTarget::Drop(), qt_try_modal(), qt_tryModalHelper(), QtWndProc(), QWidgetPrivate::show_sys(), translateRawTouchEvent(), QApplication::x11ClientMessage(), and QApplication::x11ProcessEvent().
 {
     QWidget *top = QApplication::activeModalWidget();
     if (rettop)
         *rettop = top;
     // the active popup widget always gets the input event
     if (QApplication::activePopupWidget())
         return true;
 #if defined(Q_WS_MAC) && defined(QT_MAC_USE_COCOA)
     top = QApplicationPrivate::tryModalHelper_sys(top);
     if (rettop)
         *rettop = top;
 #endif
     return !isBlockedByModal(widget->window());
 }
tryModalHelper_sys()
QWidget * QApplicationPrivate::tryModalHelper_sys (QWidget * top) static
Definition at line 1569 of file qapplication_mac.mm.
Referenced by tryModalHelper().
 {
 #ifndef QT_MAC_USE_COCOA
     if(top && qt_mac_is_macsheet(top) && !IsWindowVisible(qt_mac_window_for(top))) {
         if(OSWindowRef wp = GetFrontWindowOfClass(kSheetWindowClass, true)) {
             if(QWidget *sheet = qt_mac_find_window(wp))
                 top = sheet;
         }
     }
 #endif
     return top;
 }
updateTouchPointsForWidget()
void QApplicationPrivate::updateTouchPointsForWidget (QWidget * widget, QTouchEvent * touchEvent) static
Definition at line 5982 of file qapplication.cpp.
 {
     for (int i = 0; i < touchEvent->touchPoints().count(); ++i) {
         QTouchEvent::TouchPoint &touchPoint = touchEvent->_touchPoints[i];
         // preserve the sub-pixel resolution
         QRectF rect = touchPoint.screenRect();
         const QPointF screenPos = rect.center();
         const QPointF delta = screenPos - screenPos.toPoint();
         rect.moveCenter(widget->mapFromGlobal(screenPos.toPoint()) + delta);
         touchPoint.d->rect = rect;
         if (touchPoint.state() == Qt::TouchPointPressed) {
             touchPoint.d->startPos = widget->mapFromGlobal(touchPoint.startScreenPos().toPoint()) + delta;
             touchPoint.d->lastPos = widget->mapFromGlobal(touchPoint.lastScreenPos().toPoint()) + delta;
         }
     }
 }
x11_apply_settings()
bool QApplicationPrivate::x11_apply_settings () static
Warning
This function is not part of the public interface. apply the settings to the application
Definition at line 867 of file qapplication_x11.cpp.
Referenced by qt_set_x11_resources().
 {
     QSettings settings(QSettings::UserScope, QLatin1String("Trolltech"));
     settings.beginGroup(QLatin1String("Qt"));
     /*
       Qt settings. This is now they are written into the datastream.
       Palette / *                - QPalette
       font                       - QFont
       libraryPath                - QStringList
       style                      - QString
       doubleClickInterval        - int
       keyboardInputInterval  - int
       cursorFlashTime            - int
       wheelScrollLines           - int
       colorSpec                  - QString
       defaultCodec               - QString
       globalStrut/width          - int
       globalStrut/height         - int
       GUIEffects                 - QStringList
       Font Substitutions/ *      - QStringList
       Font Substitutions/...     - QStringList
     */
     QStringList strlist;
     int i;
     QPalette pal(Qt::black);
     int groupCount = 0;
     strlist = settings.value(QLatin1String("Palette/active")).toStringList();
     if (!strlist.isEmpty()) {
         ++groupCount;
         for (i = 0; i < qMin(strlist.count(), int(QPalette::NColorRoles)); i++)
             pal.setColor(QPalette::Active, (QPalette::ColorRole) i,
                          QColor(strlist[i]));
     }
     strlist = settings.value(QLatin1String("Palette/inactive")).toStringList();
     if (!strlist.isEmpty()) {
         ++groupCount;
         for (i = 0; i < qMin(strlist.count(), int(QPalette::NColorRoles)); i++)
             pal.setColor(QPalette::Inactive, (QPalette::ColorRole) i,
                          QColor(strlist[i]));
     }
     strlist = settings.value(QLatin1String("Palette/disabled")).toStringList();
     if (!strlist.isEmpty()) {
         ++groupCount;
         for (i = 0; i < qMin(strlist.count(), int(QPalette::NColorRoles)); i++)
             pal.setColor(QPalette::Disabled, (QPalette::ColorRole) i,
                          QColor(strlist[i]));
     }
     // ### Fix properly for 4.6
     bool usingGtkSettings = QApplicationPrivate::app_style && QApplicationPrivate::app_style->inherits("QGtkStyle");
     if (!usingGtkSettings) {
         if (groupCount == QPalette::NColorGroups)
             QApplicationPrivate::setSystemPalette(pal);
     }
     if (!appFont) {
         // ### Fix properly for 4.6
         if (!usingGtkSettings) {
             QFont font(QApplication::font());
             QString fontDescription;
             // Override Qt font if KDE4 settings can be used
             if (X11->desktopVersion == 4) {
                 QSettings kdeSettings(QKde::kdeHome() + QLatin1String("/share/config/kdeglobals"), QSettings::IniFormat);
                 fontDescription = kdeSettings.value(QLatin1String("font")).toString();
                 if (fontDescription.isEmpty()) {
                     // KDE stores fonts without quotes
                     fontDescription = kdeSettings.value(QLatin1String("font")).toStringList().join(QLatin1String(","));
                 }
             }
             if (fontDescription.isEmpty())
                 fontDescription = settings.value(QLatin1String("font")).toString();
             if (!fontDescription .isEmpty()) {
                 font.fromString(fontDescription );
                 QApplicationPrivate::setSystemFont(font);
             }
         }
     }
     // read library (ie. plugin) path list
     QString libpathkey =
         QString::fromLatin1("%1.%2/libraryPath")
         .arg(QT_VERSION >> 16)
         .arg((QT_VERSION & 0xff00) >> 8);
     QStringList pathlist = settings.value(libpathkey).toString().split(QLatin1Char(':'));
     if (! pathlist.isEmpty()) {
         QStringList::ConstIterator it = pathlist.constBegin();
         while (it != pathlist.constEnd())
             QApplication::addLibraryPath(*it++);
     }
     // read new QStyle
     QString stylename = settings.value(QLatin1String("style")).toString();
     if (stylename.isEmpty() && QApplicationPrivate::styleOverride.isNull() && X11->use_xrender) {
         stylename = qt_guiPlatformPlugin()->styleName();
     }
     static QString currentStyleName = stylename;
     if (QCoreApplication::startingUp()) {
         if (!stylename.isEmpty() && QApplicationPrivate::styleOverride.isNull())
             QApplicationPrivate::styleOverride = stylename;
     } else {
         if (currentStyleName != stylename) {
             currentStyleName = stylename;
             QApplication::setStyle(stylename);
         }
     }
     int num =
         settings.value(QLatin1String("doubleClickInterval"),
                        QApplication::doubleClickInterval()).toInt();
     QApplication::setDoubleClickInterval(num);
     num =
         settings.value(QLatin1String("cursorFlashTime"),
                        QApplication::cursorFlashTime()).toInt();
     QApplication::setCursorFlashTime(num);
 #ifndef QT_NO_WHEELEVENT
     num =
         settings.value(QLatin1String("wheelScrollLines"),
                        QApplication::wheelScrollLines()).toInt();
     QApplication::setWheelScrollLines(num);
 #endif
     QString colorspec = settings.value(QLatin1String("colorSpec"),
                                        QVariant(QLatin1String("default"))).toString();
     if (colorspec == QLatin1String("normal"))
         QApplication::setColorSpec(QApplication::NormalColor);
     else if (colorspec == QLatin1String("custom"))
         QApplication::setColorSpec(QApplication::CustomColor);
     else if (colorspec == QLatin1String("many"))
         QApplication::setColorSpec(QApplication::ManyColor);
     else if (colorspec != QLatin1String("default"))
         colorspec = QLatin1String("default");
     QString defaultcodec = settings.value(QLatin1String("defaultCodec"),
                                           QVariant(QLatin1String("none"))).toString();
     if (defaultcodec != QLatin1String("none")) {
         QTextCodec *codec = QTextCodec::codecForName(defaultcodec.toLatin1());
         if (codec)
             QTextCodec::setCodecForTr(codec);
     }
     int w = settings.value(QLatin1String("globalStrut/width")).toInt();
     int h = settings.value(QLatin1String("globalStrut/height")).toInt();
     QSize strut(w, h);
     if (strut.isValid())
         QApplication::setGlobalStrut(strut);
     QStringList effects = settings.value(QLatin1String("GUIEffects")).toStringList();
     QApplication::setEffectEnabled(Qt::UI_General,
                                    effects.contains(QLatin1String("general")));
     QApplication::setEffectEnabled(Qt::UI_AnimateMenu,
                                    effects.contains(QLatin1String("animatemenu")));
     QApplication::setEffectEnabled(Qt::UI_FadeMenu,
                                    effects.contains(QLatin1String("fademenu")));
     QApplication::setEffectEnabled(Qt::UI_AnimateCombo,
                                    effects.contains(QLatin1String("animatecombo")));
     QApplication::setEffectEnabled(Qt::UI_AnimateTooltip,
                                    effects.contains(QLatin1String("animatetooltip")));
     QApplication::setEffectEnabled(Qt::UI_FadeTooltip,
                                    effects.contains(QLatin1String("fadetooltip")));
     QApplication::setEffectEnabled(Qt::UI_AnimateToolBox,
                                    effects.contains(QLatin1String("animatetoolbox")));
     if (!X11->has_fontconfig) {
         settings.beginGroup(QLatin1String("Font Substitutions"));
         QStringList fontsubs = settings.childKeys();
         if (!fontsubs.isEmpty()) {
             QStringList::Iterator it = fontsubs.begin();
             for (; it != fontsubs.end(); ++it) {
                 QString fam = *it;
                 QStringList subs = settings.value(fam).toStringList();
                 QFont::insertSubstitutions(fam, subs);
             }
         }
         settings.endGroup();
     }
     qt_use_rtl_extensions =
         settings.value(QLatin1String("useRtlExtensions"), false).toBool();
 #ifndef QT_NO_IM
 #ifndef QT_NO_XIM
     if (qt_xim_preferred_style == 0) {
         QString ximInputStyle = settings.value(QLatin1String("XIMInputStyle"),
                                                QVariant(QLatin1String("on the spot"))).toString().toLower();
         if (ximInputStyle == QLatin1String("on the spot"))
             qt_xim_preferred_style = XIMPreeditCallbacks | XIMStatusNothing;
         else if (ximInputStyle == QLatin1String("over the spot"))
             qt_xim_preferred_style = XIMPreeditPosition | XIMStatusNothing;
         else if (ximInputStyle == QLatin1String("off the spot"))
             qt_xim_preferred_style = XIMPreeditArea | XIMStatusArea;
         else if (ximInputStyle == QLatin1String("root"))
             qt_xim_preferred_style = XIMPreeditNothing | XIMStatusNothing;
     }
 #endif // QT_NO_XIM
     QStringList inputMethods = QInputContextFactory::keys();
     if (inputMethods.size() > 2 && inputMethods.contains(QLatin1String("imsw-multi"))) {
         X11->default_im = QLatin1String("imsw-multi");
     } else {
         X11->default_im = settings.value(QLatin1String("DefaultInputMethod"),
                                          QLatin1String("xim")).toString();
     }
 #endif //QT_NO_IM
     settings.endGroup(); // Qt
     return true;
 }
x11_initialize_style()
static void QApplicationPrivate::x11_initialize_style () static
Properties
active_window
QWidget * QApplicationPrivate::active_window = 0 static
Definition at line 439 of file qapplication_p.h.
Referenced by QApplication::activeWindow(), closePopup(), globalEventProcessor(), onApplicationWindowChangedActivation(), q_createNativeChildrenAndSetParent(), qt_cleanup(), qt_try_modal(), QApplication::qwsProcessEvent(), QApplication::setActiveWindow(), QApplication::winFocus(), QApplication::x11ProcessEvent(), and ~QApplicationPrivate().
alertTimerHash
QHash<QWidget *, QTimer *> QApplicationPrivate::alertTimerHash
Definition at line 535 of file qapplication_p.h.
animate_combo
bool QApplicationPrivate::animate_combo = false static
Definition at line 452 of file qapplication_p.h.
Referenced by QApplication::isEffectEnabled(), QApplication::setEffectEnabled(), QETWidget::translateCloseEvent(), QETWidget::updateRegion(), and QApplication::~QApplication().
animate_menu
bool QApplicationPrivate::animate_menu = false static
Definition at line 450 of file qapplication_p.h.
Referenced by QApplication::isEffectEnabled(), QApplication::setEffectEnabled(), QETWidget::translateCloseEvent(), QETWidget::updateRegion(), and QApplication::~QApplication().
animate_toolbox
bool QApplicationPrivate::animate_toolbox = false static
Definition at line 455 of file qapplication_p.h.
Referenced by QApplication::isEffectEnabled(), QApplication::setEffectEnabled(), QETWidget::translateCloseEvent(), and QETWidget::updateRegion().
animate_tooltip
bool QApplicationPrivate::animate_tooltip = false static
Definition at line 451 of file qapplication_p.h.
Referenced by QApplication::isEffectEnabled(), QApplication::setEffectEnabled(), QETWidget::translateCloseEvent(), QETWidget::updateRegion(), and QApplication::~QApplication().
animate_ui
bool QApplicationPrivate::animate_ui = true static
Definition at line 449 of file qapplication_p.h.
Referenced by QApplication::isEffectEnabled(), QApplication::setEffectEnabled(), QETWidget::translateCloseEvent(), QETWidget::updateRegion(), and QApplication::~QApplication().
app_cspec
int QApplicationPrivate::app_cspec = QApplication::NormalColor static
Definition at line 420 of file qapplication_p.h.
Referenced by QApplication::colorSpec(), QApplication::setColorSpec(), and ~QApplicationPrivate().
app_font
QFont * QApplicationPrivate::app_font = 0 static private
Definition at line 432 of file qapplication_p.h.
Referenced by QApplication::font(), QApplication::~QApplication(), and ~QApplicationPrivate().
app_icon
QIcon * QApplicationPrivate::app_icon = 0 static
Definition at line 440 of file qapplication_p.h.
Referenced by desktopStyleKey(), QApplication::~QApplication(), and ~QApplicationPrivate().
app_pal
QPalette * QApplicationPrivate::app_pal = 0 static
Definition at line 421 of file qapplication_p.h.
Referenced by QApplication::palette(), QApplication::~QApplication(), and ~QApplicationPrivate().
app_strut
QSize QApplicationPrivate::app_strut = QSize(0,0) static
Definition at line 417 of file qapplication_p.h.
Referenced by QApplication::setColorSpec().
app_style
QStyle * QApplicationPrivate::app_style = 0 static
Definition at line 419 of file qapplication_p.h.
Referenced by globalEventProcessor(), onApplicationWindowChangedActivation(), process_cmdline(), qt_init(), qt_set_x11_resources(), QApplication::setStyle(), QApplication::setStyleSheet(), QApplication::style(), x11_apply_settings(), QApplication::~QApplication(), and ~QApplicationPrivate().
appCurrentTouchPoints
QMap<int, QTouchEvent::TouchPoint> QApplicationPrivate::appCurrentTouchPoints
Definition at line 581 of file qapplication_p.h.
Referenced by translateRawTouchEvent().
autoMaximizeThreshold
int QApplicationPrivate::autoMaximizeThreshold = -1 static
Definition at line 305 of file qapplication_p.h.
Referenced by QApplication::setAutoMaximizeThreshold().
autoSipEnabled
bool QApplicationPrivate::autoSipEnabled = false static
Definition at line 307 of file qapplication_p.h.
Referenced by QApplication::setAutoSipEnabled().
BeginPanningFeedback
PtrBeginPanningFeedback QApplicationPrivate::BeginPanningFeedback
Definition at line 609 of file qapplication_p.h.
Referenced by qt_init().
CloseGestureInfoHandle
PtrCloseGestureInfoHandle QApplicationPrivate::CloseGestureInfoHandle
Definition at line 606 of file qapplication_p.h.
Referenced by qt_init(), and QtWndProc().
CloseTouchInputHandle
PtrCloseTouchInputHandle QApplicationPrivate::CloseTouchInputHandle = 0 static
Definition at line 598 of file qapplication_p.h.
Referenced by QSessionManager::cancel(), and translateTouchEvent().
copy_cursor
QPixmap* QApplicationPrivate::copy_cursor
Definition at line 572 of file qapplication_p.h.
Referenced by QApplicationPrivate().
cursor_flash_time
int QApplicationPrivate::cursor_flash_time = 1000 static
Definition at line 442 of file qapplication_p.h.
Referenced by QApplication::setCursorFlashTime(), QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), QETWidget::updateRegion(), QApplication::~QApplication(), and ~QApplicationPrivate().
cursor_list
QList<QCursor> QApplicationPrivate::cursor_list
Definition at line 382 of file qapplication_p.h.
directPainters
QMap<WId, QDirectPainter *>* QApplicationPrivate::directPainters
Definition at line 517 of file qapplication_p.h.
Referenced by QApplicationPrivate(), and QDirectPainter::QDirectPainter().
EndPanningFeedback
PtrEndPanningFeedback QApplicationPrivate::EndPanningFeedback
Definition at line 611 of file qapplication_p.h.
Referenced by qt_init().
fade_menu
bool QApplicationPrivate::fade_menu = false static
Definition at line 453 of file qapplication_p.h.
Referenced by QApplication::isEffectEnabled(), QApplication::setEffectEnabled(), QETWidget::translateCloseEvent(), QETWidget::updateRegion(), and QApplication::~QApplication().
fade_tooltip
bool QApplicationPrivate::fade_tooltip = false static
Definition at line 454 of file qapplication_p.h.
Referenced by QApplication::isEffectEnabled(), QApplication::setEffectEnabled(), QETWidget::translateCloseEvent(), QETWidget::updateRegion(), and QApplication::~QApplication().
focus_widget
QWidget * QApplicationPrivate::focus_widget = 0 static
Definition at line 437 of file qapplication_p.h.
Referenced by QApplication::focusWidget(), QMacInputContext::globalEventProcessor(), globalEventProcessor(), qt_mac_menu_event(), QApplication::qwsProcessEvent(), QApplication::setActiveWindow(), QApplication::x11ProcessEvent(), and ~QApplicationPrivate().
gestureManager
QGestureManager* QApplicationPrivate::gestureManager
Definition at line 567 of file qapplication_p.h.
Referenced by QGraphicsScenePrivate::cancelGesturesForChildren(), QGestureManager::instance(), QApplicationPrivate(), and QGraphicsScenePrivate::sendEvent().
gestureWidget
QWidget* QApplicationPrivate::gestureWidget
Definition at line 568 of file qapplication_p.h.
Referenced by QApplicationPrivate(), and QtWndProc().
GetGestureConfig
PtrGetGestureConfig QApplicationPrivate::GetGestureConfig
Definition at line 608 of file qapplication_p.h.
Referenced by qt_init().
GetGestureExtraArgs
PtrGetGestureExtraArgs QApplicationPrivate::GetGestureExtraArgs
Definition at line 605 of file qapplication_p.h.
Referenced by qt_init().
GetGestureInfo
PtrGetGestureInfo QApplicationPrivate::GetGestureInfo
Definition at line 604 of file qapplication_p.h.
Referenced by qt_init(), and QtWndProc().
GetTouchInputInfo
PtrGetTouchInputInfo QApplicationPrivate::GetTouchInputInfo = 0 static
Definition at line 597 of file qapplication_p.h.
Referenced by QSessionManager::cancel(), and translateTouchEvent().
graphics_system
QGraphicsSystem * QApplicationPrivate::graphics_system = 0 static
Definition at line 424 of file qapplication_p.h.
Referenced by qt_init(), QMeeGoGraphicsSystem::runningGraphicsSystemName(), QApplication::setGraphicsSystem(), QMeeGoGraphicsSystem::wrapPixmapData(), QApplication::~QApplication(), ~QApplicationPrivate(), QRuntimePixmapData::~QRuntimePixmapData(), and QRuntimeWindowSurface::~QRuntimeWindowSurface().
graphics_system_name
QString QApplicationPrivate::graphics_system_name static
Definition at line 425 of file qapplication_p.h.
Referenced by QMeeGoGraphicsSystem::createWindowSurface(), QGraphicsViewPrivate::dispatchPendingUpdateRequests(), process_cmdline(), QRuntimeGraphicsSystem::QRuntimeGraphicsSystem(), qt_init(), qt_mac_pixmap_get_base(), qt_mac_pixmap_get_bytes_per_line(), qt_pixmap_thread_test(), QVGGraphicsSystem::QVGGraphicsSystem(), QMeeGoGraphicsSystem::runningGraphicsSystemName(), QMeeGoGraphicsSystem::wrapPixmapData(), and ~QApplicationPrivate().
HasTouchSupport
bool QApplicationPrivate::HasTouchSupport = false static
Definition at line 595 of file qapplication_p.h.
Referenced by QSessionManager::cancel(), and QGestureManager::QGestureManager().
hidden_focus_widget
QWidget * QApplicationPrivate::hidden_focus_widget = 0 static
Definition at line 438 of file qapplication_p.h.
Referenced by QWidget::setVisible(), QWidgetPrivate::show_helper(), and ~QApplicationPrivate().
hoverGlobalPos
QPoint QApplicationPrivate::hoverGlobalPos
Definition at line 391 of file qapplication_p.h.
Referenced by dispatchEnterLeave().
ignore_cursor
QPixmap* QApplicationPrivate::ignore_cursor
Definition at line 576 of file qapplication_p.h.
Referenced by QApplicationPrivate().
inputContext
QInputContext * QApplicationPrivate::inputContext = 0 static
Definition at line 410 of file qapplication_p.h.
Referenced by QWidgetPrivate::isBackgroundInherited(), isServerProcess(), qt_cleanup(), qt_init(), and QApplication::setInputContext().
is_session_restored
bool QApplicationPrivate::is_session_restored
Definition at line 378 of file qapplication_p.h.
Referenced by process_cmdline(), and QApplicationPrivate().
keyboard_input_time
int QApplicationPrivate::keyboard_input_time = 400 static
Definition at line 444 of file qapplication_p.h.
Referenced by QApplication::setKeyboardInputInterval(), QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), QETWidget::updateRegion(), QApplication::~QApplication(), and ~QApplicationPrivate().
last_manager
QPointer<QWSManager> QApplicationPrivate::last_manager
Definition at line 514 of file qapplication_p.h.
leaveAfterRelease
QPointer< QWidget > QApplicationPrivate::leaveAfterRelease = 0 static
Definition at line 540 of file qapplication_p.h.
Referenced by QETWidget::translateMouseEvent(), and ~QApplicationPrivate().
link_cursor
QPixmap* QApplicationPrivate::link_cursor
Definition at line 573 of file qapplication_p.h.
Referenced by QApplicationPrivate().
load_testability
bool QApplicationPrivate::load_testability = false static
Definition at line 457 of file qapplication_p.h.
Referenced by process_cmdline().
main_widget
QWidget * QApplicationPrivate::main_widget = 0 static
Definition at line 436 of file qapplication_p.h.
Referenced by QWidgetPrivate::close_helper(), parseGeometry(), QGuiEventDispatcherWin32::processEvents(), qt_cleanup(), qt_nograb(), qt_wstate_iconified(), QSessionManager::requestPhase2(), ~QApplicationPrivate(), and QWidget::~QWidget().
maxWindowRects
QMap<const QScreen*, QRect> QApplicationPrivate::maxWindowRects private
Definition at line 643 of file qapplication_p.h.
Referenced by setMaxWindowRect().
modifier_buttons
Qt::KeyboardModifiers QApplicationPrivate::modifier_buttons = Qt::NoModifier static
Definition at line 415 of file qapplication_p.h.
Referenced by QApplication::keyboardModifiers(), QApplication::notify(), QX11Data::xdndHandleDrop(), and ~QApplicationPrivate().
mouse_buttons
Qt::MouseButtons QApplicationPrivate::mouse_buttons = Qt::NoButton static
Definition at line 414 of file qapplication_p.h.
Referenced by QApplication::mouseButtons(), QApplication::notify(), QETWidget::translateMouseEvent(), and ~QApplicationPrivate().
mouse_double_click_time
int QApplicationPrivate::mouse_double_click_time = 400 static
Definition at line 443 of file qapplication_p.h.
Referenced by globalEventProcessor(), QApplication::setDoubleClickInterval(), QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), QETWidget::updateRegion(), QApplication::~QApplication(), and ~QApplicationPrivate().
move_cursor
QPixmap* QApplicationPrivate::move_cursor
Definition at line 571 of file qapplication_p.h.
Referenced by QApplicationPrivate().
native_modal_dialog_active
bool QApplicationPrivate::native_modal_dialog_active static
Definition at line 460 of file qapplication_p.h.
Referenced by QFileDialogPrivate::_q_macRunNativeAppModalPanel(), QPrintDialogPrivate::closeCarbonPrintPanel(), QPageSetupDialogPrivate::openCarbonPageLayout(), QPrintDialogPrivate::openCarbonPrintPanel(), qt_init(), qt_mac_menu_event(), and qt_try_modal().
obey_desktop_settings
bool QApplicationPrivate::obey_desktop_settings = true static
Definition at line 441 of file qapplication_p.h.
Referenced by QApplication::desktopSettingsAware(), QApplication::setDesktopSettingsAware(), QApplication::x11ProcessEvent(), QApplication::~QApplication(), and ~QApplicationPrivate().
popupWidgets
QWidgetList * QApplicationPrivate::popupWidgets = 0 static
Definition at line 418 of file qapplication_p.h.
Referenced by closePopup(), openPopup(), qt_app_fonts_hash(), qt_try_modal(), and QETWidget::translateMouseEvent().
quitOnLastWindowClosed
bool QApplicationPrivate::quitOnLastWindowClosed = true static
Definition at line 302 of file qapplication_p.h.
Referenced by emitLastWindowClosed(), QApplicationPrivate(), and QApplication::setQuitOnLastWindowClosed().
qwsServerCleaner
QWSServerCleaner QApplicationPrivate::qwsServerCleaner
Definition at line 515 of file qapplication_p.h.
RegisterTouchWindow
PtrRegisterTouchWindow QApplicationPrivate::RegisterTouchWindow = 0 static
Definition at line 596 of file qapplication_p.h.
Referenced by QSessionManager::cancel().
runtime_graphics_system
bool QApplicationPrivate::runtime_graphics_system = false static
Definition at line 426 of file qapplication_p.h.
Referenced by QRuntimeGraphicsSystem::QRuntimeGraphicsSystem(), QWindowSurface::QWindowSurface(), and ~QApplicationPrivate().
scene_list
QList<QGraphicsScene *> QApplicationPrivate::scene_list
Definition at line 387 of file qapplication_p.h.
self
QApplicationPrivate * QApplicationPrivate::self = 0 static private
Definition at line 650 of file qapplication_p.h.
Referenced by qt_cleanup().
session_id
QString QApplicationPrivate::session_id
Definition at line 376 of file qapplication_p.h.
Referenced by process_cmdline().
session_key
QString QApplicationPrivate::session_key
Definition at line 377 of file qapplication_p.h.
Referenced by process_cmdline().
session_manager
QSessionManager* QApplicationPrivate::session_manager
Definition at line 375 of file qapplication_p.h.
set_font
QFont * QApplicationPrivate::set_font = 0 static
Definition at line 435 of file qapplication_p.h.
Referenced by QApplication::~QApplication(), and ~QApplicationPrivate().
set_pal
QPalette * QApplicationPrivate::set_pal = 0 static
Definition at line 423 of file qapplication_p.h.
Referenced by QApplication::~QApplication(), and ~QApplicationPrivate().
SetGestureConfig
PtrSetGestureConfig QApplicationPrivate::SetGestureConfig
Definition at line 607 of file qapplication_p.h.
Referenced by qt_init().
shortcutMap
QShortcutMap QApplicationPrivate::shortcutMap
Definition at line 394 of file qapplication_p.h.
styleOverride
QString QApplicationPrivate::styleOverride static
Definition at line 526 of file qapplication_p.h.
Referenced by QProxyStylePrivate::ensureBaseStyle(), process_cmdline(), QApplication::style(), x11_apply_settings(), and ~QApplicationPrivate().
styleSheet
QString QApplicationPrivate::styleSheet static
Definition at line 538 of file qapplication_p.h.
Referenced by process_cmdline(), QApplication::setAutoSipEnabled(), and ~QApplicationPrivate().
sys_font
QFont * QApplicationPrivate::sys_font = 0 static
Definition at line 434 of file qapplication_p.h.
Referenced by init_display(), qt_set_x11_resources(), QApplication::~QApplication(), and ~QApplicationPrivate().
sys_pal
QPalette * QApplicationPrivate::sys_pal = 0 static
Definition at line 422 of file qapplication_p.h.
Referenced by qt_set_x11_resources(), QWindowsXPStyle::standardPalette(), QApplication::~QApplication(), and ~QApplicationPrivate().
toolTipFallAsleep
QBasicTimer QApplicationPrivate::toolTipFallAsleep
Definition at line 390 of file qapplication_p.h.
toolTipGlobalPos
QPoint QApplicationPrivate::toolTipGlobalPos
Definition at line 391 of file qapplication_p.h.
toolTipPos
QPoint QApplicationPrivate::toolTipPos
Definition at line 391 of file qapplication_p.h.
toolTipWakeUp
QBasicTimer QApplicationPrivate::toolTipWakeUp
Definition at line 390 of file qapplication_p.h.
toolTipWidget
QPointer<QWidget> QApplicationPrivate::toolTipWidget
Definition at line 392 of file qapplication_p.h.
touchInputIDToTouchPointID
QHash<DWORD, int> QApplicationPrivate::touchInputIDToTouchPointID
Definition at line 600 of file qapplication_p.h.
UpdatePanningFeedback
PtrUpdatePanningFeedback QApplicationPrivate::UpdatePanningFeedback
Definition at line 610 of file qapplication_p.h.
Referenced by qt_init().
wheel_scroll_lines
int QApplicationPrivate::wheel_scroll_lines static
Definition at line 446 of file qapplication_p.h.
Referenced by QApplication::setWheelScrollLines(), QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), QETWidget::updateRegion(), and ~QApplicationPrivate().
widgetCount
bool QApplicationPrivate::widgetCount = false static
Definition at line 456 of file qapplication_p.h.
Referenced by process_cmdline(), and QApplication::~QApplication().
widgetForTouchPointId
QMap<int, QWeakPointer<QWidget> > QApplicationPrivate::widgetForTouchPointId
Definition at line 580 of file qapplication_p.h.
Referenced by translateRawTouchEvent().
The documentation for this class was generated from the following files:
/src/gui/kernel/qapplication_p.h
/src/gui/kernel/qapplication.cpp
/src/gui/kernel/qapplication_mac.mm
/src/gui/kernel/qapplication_qpa.cpp
/src/gui/kernel/qapplication_qws.cpp
/src/gui/kernel/qapplication_win.cpp
/src/gui/kernel/qapplication_x11.cpp