Qt 4.8: QTextCodec Class Reference
QTextCodec Class Reference abstract
The QTextCodec class provides conversions between text encodings.
#include <qtextcodec.h>
Classes
struct ConverterState
Public Types
enum ConversionFlag { DefaultConversion, ConvertInvalidToNull = 0x80000000, IgnoreHeader = 0x1, FreeFunction = 0x2 }
Public Functions
virtual QList< QByteArray > aliases () const
Subclasses can return a number of aliases for the codec in question.
bool canEncode (QChar) const
Returns true if the Unicode character ch can be fully encoded with this codec; otherwise returns false.
bool canEncode (const QString &) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.s contains the string being tested for encode-ability.
QByteArray fromUnicode (const QString &uc) const
Converts str from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QByteArray fromUnicode (const QChar *in, int length, ConverterState *state=0) const
Converts the first number of characters from the input array from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QTextDecoder * makeDecoder () const
Creates a QTextDecoder which stores enough state to decode chunks of char * data to create chunks of Unicode data.
QTextDecoder * makeDecoder (ConversionFlags flags) const
QTextEncoder * makeEncoder () const
Creates a QTextEncoder which stores enough state to encode chunks of Unicode data as char * data.
QTextEncoder * makeEncoder (ConversionFlags flags) const
virtual int mibEnum () const =0
Subclasses of QTextCodec must reimplement this function.
virtual QByteArray name () const =0
QTextCodec subclasses must reimplement this function.
QString toUnicode (const QByteArray &) const
Converts a from the encoding of this codec to Unicode, and returns the result in a QString.
QString toUnicode (const char *chars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.chars contains the source characters.
QString toUnicode (const char *in, int length, ConverterState *state=0) const
Converts the first size characters from the input from the encoding of this codec to Unicode, and returns the result in a QString.
Static Public Functions
static QList< QByteArray > availableCodecs ()
Returns the list of all available codecs, by name.
static QList< int > availableMibs ()
Returns the list of MIBs for all available codecs.
static QTextCodec * codecForCStrings ()
Returns the codec used by QString to convert to and from const char * and QByteArrays.
static QTextCodec * codecForHtml (const QByteArray &ba)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForHtml (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForLocale ()
Returns a pointer to the codec most suitable for this locale.
static QTextCodec * codecForMib (int mib)
Returns the QTextCodec which matches the MIBenum mib.
static QTextCodec * codecForName (const QByteArray &name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForName (const char *name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForTr ()
Returns the codec used by QObject::tr() on its argument.
static QTextCodec * codecForUtfText (const QByteArray &ba)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static QTextCodec * codecForUtfText (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static void setCodecForCStrings (QTextCodec *c)
static void setCodecForLocale (QTextCodec *c)
Set the codec to c; this will be returned by codecForLocale().
static void setCodecForTr (QTextCodec *c)
Protected Functions
virtual QByteArray convertFromUnicode (const QChar *in, int length, ConverterState *state) const =0
QTextCodec subclasses must reimplement this function.
virtual QString convertToUnicode (const char *in, int length, ConverterState *state) const =0
QTextCodec subclasses must reimplement this function.
QTextCodec ()
Constructs a QTextCodec, and gives it the highest precedence.
virtual ~QTextCodec ()
Destroys the QTextCodec.
Static Private Functions
static bool validCodecs ()
Static Private Attributes
static QTextCodec * cftr = 0
Friends
class QTextCodecCleanup
Detailed Description
The QTextCodec class provides conversions between text encodings.
Note
This class or function is reentrant.
Qt uses Unicode to store, draw and manipulate strings. In many situations you may wish to deal with data that uses a different encoding. For example, most Japanese documents are still stored in Shift-JIS or ISO 2022-JP, while Russian users often have their documents in KOI8-R or Windows-1251.
Qt provides a set of QTextCodec classes to help with converting non-Unicode formats to and from Unicode. You can also create your own codec classes.
The supported encodings are:
Apple Roman
Big5 Text Codec{Big5}
Big5-HKSCS Text Codec{Big5-HKSCS}
CP949
EUC-JP Text Codec{EUC-JP}
EUC-KR Text Codec{EUC-KR}
GBK Text Codec{GB18030-0}
IBM 850
IBM 866
IBM 874
ISO 2022-JP (JIS) Text Codec{ISO 2022-JP}
ISO 8859-1 to 10
ISO 8859-13 to 16
Iscii-Bng, Dev, Gjr, Knd, Mlm, Ori, Pnj, Tlg, and Tml
JIS X 0201
JIS X 0208
KOI8-R
KOI8-U
MuleLao-1
ROMAN8
Shift-JIS Text Codec{Shift-JIS}
TIS-620
TSCII Text Codec{TSCII}
UTF-8
UTF-16
UTF-16BE
UTF-16LE
UTF-32
UTF-32BE
UTF-32LE
Windows-1250 to 1258
WINSAMI2
QTextCodecs can be used as follows to convert some locally encoded string to Unicode. Suppose you have some string encoded in Russian KOI8-R encoding, and want to convert it to Unicode. The simple way to do it is like this:
QByteArray encodedString = "...";
QTextCodec *codec = QTextCodec::codecForName("KOI8-R");
QString string = codec->toUnicode(encodedString);
After this, string holds the text converted to Unicode. Converting a string from Unicode to the local encoding is just as easy:
QString string = "...";
QTextCodec *codec = QTextCodec::codecForName("KOI8-R");
QByteArray encodedString = codec->fromUnicode(string);
To read or write files in various encodings, use QTextStream and its setCodec() function. See the Codecs example for an application of QTextCodec to file I/O.
Some care must be taken when trying to convert the data in chunks, for example, when receiving it over a network. In such cases it is possible that a multi-byte character will be split over two chunks. At best this might result in the loss of a character and at worst cause the entire conversion to fail.
The approach to use in these situations is to create a QTextDecoder object for the codec and use this QTextDecoder for the whole decoding process, as shown below:
QTextCodec *codec = QTextCodec::codecForName("Shift-JIS");
QTextDecoder *decoder = codec->makeDecoder();
QString string;
while (new_data_available()) {
    QByteArray chunk = get_new_data();
    string += decoder->toUnicode(chunk);
}
delete decoder;
The QTextDecoder object maintains state between chunks and therefore works correctly even if a multi-byte character is split between chunks.
Creating Your Own Codec Class
Support for new text encodings can be added to Qt by creating QTextCodec subclasses.
The pure virtual functions describe the encoder to the system and the coder is used as required in the different text file formats supported by QTextStream, and under X11, for the locale-specific character input and output.
To add support for another encoding to Qt, make a subclass of QTextCodec and implement the functions listed in the table below.
Function
Description
name()
Returns the official name for the encoding. If the encoding is listed in the IANA character-sets encoding file, the name should be the preferred MIME name for the encoding.
aliases()
Returns a list of alternative names for the encoding. QTextCodec provides a default implementation that returns an empty list. For example, "ISO-8859-1" has "latin1", "CP819", "IBM819", and "iso-ir-100" as aliases.
mibEnum()
Return the MIB enum for the encoding if it is listed in the IANA character-sets encoding file.
convertToUnicode()
Converts an 8-bit character string to Unicode.
convertFromUnicode() Converts a Unicode string to an 8-bit character string.
You may find it more convenient to make your codec class available as a plugin; see How to Create Qt Plugins for details.
See also
QTextStream, QTextDecoder, QTextEncoder, {Codecs Example}
Definition at line 62 of file qtextcodec.h.
Enumerations
ConversionFlag
enum QTextCodec::ConversionFlag
DefaultConversion No flag is set.
ConvertInvalidToNull If this flag is set, each invalid input character is output as a null character.
IgnoreHeader Ignore any Unicode byte-order mark and don't generate any.
FreeFunction
Enumerator
DefaultConversion
ConvertInvalidToNull
IgnoreHeader
FreeFunction
Definition at line 94 of file qtextcodec.h.
{
         DefaultConversion,
         ConvertInvalidToNull = 0x80000000,
         IgnoreHeader = 0x1,
         FreeFunction = 0x2
     };
Constructors and Destructors
QTextCodec()
QTextCodec::QTextCodec () protected
Constructs a QTextCodec, and gives it the highest precedence.
The QTextCodec should always be constructed on the heap (i.e. with new). Qt takes ownership and will delete it when the application terminates.
Definition at line 985 of file qtextcodec.cpp.
 {
 #ifndef QT_NO_THREAD
     QMutexLocker locker(textCodecsMutex());
 #endif
     setup();
     all->prepend(this);
 }
~QTextCodec()
QTextCodec::~QTextCodec () protected virtual
Destroys the QTextCodec.
Note
This class or function is not reentrant.
Note that you should not delete codecs yourself: once created they become Qt's responsibility.
Definition at line 1004 of file qtextcodec.cpp.
 {
 #ifdef Q_DEBUG_TEXTCODEC
     if (!destroying_is_ok)
         qWarning("QTextCodec::~QTextCodec: Called by application");
 #endif
     if (all) {
 #ifndef QT_NO_THREAD
         QMutexLocker locker(textCodecsMutex());
 #endif
         all->removeAll(this);
         QTextCodecCache *cache = qTextCodecCache();
         if (cache)
             cache->clear();
     }
 }
Functions
aliases()
QList< QByteArray > QTextCodec::aliases () const virtual
Subclasses can return a number of aliases for the codec in question.
Standard aliases for codecs can be found in the IANA character-sets encoding file.
Reimplemented in QUtf32LECodec, QUtf32BECodec, QFontGb18030_0Codec, QUtf32Codec, QFontGbkCodec, QUtf16LECodec, QUtf16BECodec, QFontKsc5601Codec, QFontBig5hkscsCodec, QUtf16Codec, QCP949Codec, QFontBig5Codec, QEucJpCodec, QJisCodec, QSjisCodec, QLatin15Codec, QEucKrCodec, QFontJis0208Codec, QSimpleTextCodec, QGbkCodec, QBig5hkscsCodec, QLatin1Codec, QGb18030Codec, QFontJis0201Codec, and QBig5Codec.
Definition at line 1287 of file qtextcodec.cpp.
Referenced by codecForName().
 {
     return QList<QByteArray>();
 }
availableCodecs()
QList< QByteArray > QTextCodec::availableCodecs () static
Returns the list of all available codecs, by name.
Call QTextCodec::codecForName() to obtain the QTextCodec for the name.
The list may contain many mentions of the same codec if the codec has aliases.
See also
availableMibs(), name(), aliases()
Definition at line 1132 of file qtextcodec.cpp.
 {
 #ifndef QT_NO_THREAD
     QMutexLocker locker(textCodecsMutex());
 #endif
     setup();
     QList<QByteArray> codecs;
     if (!validCodecs())
         return codecs;
     for (int i = 0; i < all->size(); ++i) {
         codecs += all->at(i)->name();
         codecs += all->at(i)->aliases();
     }
 #ifndef QT_NO_THREAD
     locker.unlock();
 #endif
 #if !defined(QT_NO_LIBRARY) && !defined(QT_NO_TEXTCODECPLUGIN)
     QFactoryLoader *l = loader();
     QStringList keys = l->keys();
     for (int i = 0; i < keys.size(); ++i) {
         if (!keys.at(i).startsWith(QLatin1String("MIB: "))) {
             QByteArray name = keys.at(i).toLatin1();
             if (!codecs.contains(name))
                 codecs += name;
         }
     }
 #endif
     return codecs;
 }
availableMibs()
QList< int > QTextCodec::availableMibs () static
Returns the list of MIBs for all available codecs.
Call QTextCodec::codecForMib() to obtain the QTextCodec for the MIB.
See also
availableCodecs(), mibEnum()
Definition at line 1174 of file qtextcodec.cpp.
 {
 #ifndef QT_NO_THREAD
     QMutexLocker locker(textCodecsMutex());
 #endif
     setup();
     QList<int> codecs;
     if (!validCodecs())
         return codecs;
     for (int i = 0; i < all->size(); ++i)
         codecs += all->at(i)->mibEnum();
 #ifndef QT_NO_THREAD
     locker.unlock();
 #endif
 #if !defined(QT_NO_LIBRARY) && !defined(QT_NO_TEXTCODECPLUGIN)
     QFactoryLoader *l = loader();
     QStringList keys = l->keys();
     for (int i = 0; i < keys.size(); ++i) {
         if (keys.at(i).startsWith(QLatin1String("MIB: "))) {
             int mib = keys.at(i).mid(5).toInt();
             if (!codecs.contains(mib))
                 codecs += mib;
         }
     }
 #endif
     return codecs;
 }
canEncode() [1/2]
bool QTextCodec::canEncode (QChar ch) const
Returns true if the Unicode character ch can be fully encoded with this codec; otherwise returns false.
Definition at line 1417 of file qtextcodec.cpp.
Referenced by encodeText().
 {
     ConverterState state;
     state.flags = ConvertInvalidToNull;
     convertFromUnicode(&ch, 1, &state);
     return (state.invalidChars == 0);
 }
canEncode() [2/2]
bool QTextCodec::canEncode (const QString & s) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.s contains the string being tested for encode-ability.
Definition at line 1430 of file qtextcodec.cpp.
 {
     ConverterState state;
     state.flags = ConvertInvalidToNull;
     convertFromUnicode(s.constData(), s.length(), &state);
     return (state.invalidChars == 0);
 }
codecForCStrings()
QTextCodec * QTextCodec::codecForCStrings () inline static
Returns the codec used by QString to convert to and from const char * and QByteArrays.
If this function returns 0 (the default), QString assumes Latin-1.
See also
setCodecForCStrings()
Definition at line 157 of file qtextcodec.h.
Referenced by QChar::fromAscii(), QChar::QChar(), and QChar::toAscii().
 { return validCodecs() ? QString::codecForCStrings : 0; }
codecForHtml() [1/2]
QTextCodec * QTextCodec::codecForHtml (const QByteArray & ba) static
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the codec cannot be detected, this overload returns a Latin-1 QTextCodec.
Definition at line 1807 of file qtextcodec.cpp.
Referenced by Qt::codecForHtml(), QDeclarativeXMLHttpRequest::findTextCodec(), QMimeDataPrivate::retrieveTypedData(), and QClipboard::text().
 {
     return codecForHtml(ba, QTextCodec::codecForMib(/*Latin 1*/ 4));
 }
codecForHtml() [2/2]
QTextCodec * QTextCodec::codecForHtml (const QByteArray & ba, QTextCodec * defaultCodec) static
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
Since
4.4
If the codec cannot be detected from the content provided, defaultCodec is returned.
See also
codecForUtfText()
Definition at line 1768 of file qtextcodec.cpp.
 {
     // determine charset
     int pos;
     QTextCodec *c = 0;
     c = QTextCodec::codecForUtfText(ba, c);
     if (!c) {
         QByteArray header = ba.left(512).toLower();
         if ((pos = header.indexOf("http-equiv=")) != -1) {
             if ((pos = header.lastIndexOf("meta ", pos)) != -1) {
                 pos = header.indexOf("charset=", pos) + int(strlen("charset="));
                 if (pos != -1) {
                     int pos2 = header.indexOf('\"', pos+1);
                     QByteArray cs = header.mid(pos, pos2-pos);
                     //            qDebug("found charset: %s", cs.data());
                     c = QTextCodec::codecForName(cs);
                 }
             }
         }
     }
     if (!c)
         c = defaultCodec;
     return c;
 }
codecForLocale()
QTextCodec * QTextCodec::codecForLocale () static
Returns a pointer to the codec most suitable for this locale.
On Windows, the codec will be based on a system locale. On Unix systems, starting with Qt 4.2, the codec will be using the iconv library. Note that in both cases the codec's name will be "System".
Definition at line 1237 of file qtextcodec.cpp.
Referenced by codec(), QTextStreamPrivate::fillReadBuffer(), QTextStreamPrivate::flushWriteBuffer(), QString::fromLocal8Bit(), QTextStream::locale(), QX11Data::motifdndFormat(), QX11Data::motifdndObtainData(), QCUPSSupport::QCUPSSupport(), qstring_to_xtp(), qt_set_input_encoding(), qt_x11_set_fallback_font_family(), QTextStreamPrivate::reset(), QString::toAscii(), QString::toLocal8Bit(), QStringRef::toLocal8Bit(), QXlibKeyboard::translateKeySym(), and QXcbKeyboard::translateKeySym().
 {
     if (!validCodecs())
         return 0;
     if (localeMapper)
         return localeMapper;
 #ifndef QT_NO_THREAD
     QMutexLocker locker(textCodecsMutex());
 #endif
     setup();
     return localeMapper;
 }
codecForMib()
QTextCodec * QTextCodec::codecForMib (int mib) static
Returns the QTextCodec which matches the MIBenum mib.
Definition at line 1082 of file qtextcodec.cpp.
Referenced by codecForHtml(), codecForUtfText(), QXmlInputSource::fromRawData(), QXmlStreamReaderPrivate::getChar_helper(), QXmlStreamReaderPrivate::init(), QFontEngineXLFD::QFontEngineXLFD(), QIconvCodec::QIconvCodec(), QXmlStreamWriterPrivate::QXmlStreamWriterPrivate(), QPatternist::AccelTreeResourceLoader::retrieveUnparsedText(), QClipboard::text(), QXlibKeyboard::translateKeySym(), QXcbKeyboard::translateKeySym(), and translateKeySym().
 {
 #ifndef QT_NO_THREAD
     QMutexLocker locker(textCodecsMutex());
 #endif
     setup();
     if (!validCodecs())
         return 0;
     QByteArray key = "MIB: " + QByteArray::number(mib);
     QTextCodecCache *cache = qTextCodecCache();
     QTextCodec *codec;
     if (cache) {
         codec = cache->value(key);
         if (codec)
             return codec;
     }
     QList<QTextCodec*>::ConstIterator i;
     for (int i = 0; i < all->size(); ++i) {
         QTextCodec *cursor = all->at(i);
         if (cursor->mibEnum() == mib) {
             if (cache)
                 cache->insert(key, cursor);
             return cursor;
         }
     }
     codec = createForMib(mib);
     // Qt 3 used 1000 (mib for UCS2) as its identifier for the utf16 codec. Map
     // this correctly for compatibility.
     if (!codec && mib == 1000)
         return codecForMib(1015);
     if (codec && cache)
         cache->insert(key, codec);
     return codec;
 }
codecForName() [1/2]
QTextCodec * QTextCodec::codecForName (const QByteArray & name) static
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
Returns 0 if no codec matching the name name could be found.
Definition at line 1034 of file qtextcodec.cpp.
Referenced by codec(), codecForHtml(), QSvgPaintEngine::end(), QDeclarativeXMLHttpRequest::findTextCodec(), QXmlInputSource::fromRawData(), QTextStream::locale(), QWindowsLocalCodec::mibEnum(), QXlibMime::mimeConvertToFormat(), QIBaseDriver::open(), QCUPSSupport::QCUPSSupport(), QApplicationPrivate::qt_mac_apply_settings(), qt_set_input_encoding(), QMimeDataPrivate::retrieveTypedData(), QPatternist::AccelTreeResourceLoader::retrieveUnparsedText(), QDomDocumentPrivate::saveDocument(), QTextDocumentWriter::setCodec(), QTextStream::setCodec(), QXmlStreamWriter::setCodec(), QSettings::setIniCodec(), setupLocaleMapper(), QXmlStreamReaderPrivate::startDocument(), translateKeyEventInternal(), QKeyMapperPrivate::updateKeyMap(), QApplicationPrivate::x11_apply_settings(), and QX11Data::xdndMimeConvertToFormat().
 {
     if (name.isEmpty())
         return 0;
 #ifndef QT_NO_THREAD
     QMutexLocker locker(textCodecsMutex());
 #endif
     setup();
     if (!validCodecs())
         return 0;
     QTextCodecCache *cache = qTextCodecCache();
     QTextCodec *codec;
     if (cache) {
         codec = cache->value(name);
         if (codec)
             return codec;
     }
     for (int i = 0; i < all->size(); ++i) {
         QTextCodec *cursor = all->at(i);
         if (nameMatch(cursor->name(), name)) {
             if (cache)
                 cache->insert(name, cursor);
             return cursor;
         }
         QList<QByteArray> aliases = cursor->aliases();
         for (int y = 0; y < aliases.size(); ++y)
             if (nameMatch(aliases.at(y), name)) {
                 if (cache)
                     cache->insert(name, cursor);
                 return cursor;
             }
     }
     codec = createForName(name);
     if (codec && cache)
         cache->insert(name, codec);
     return codec;
 }
codecForName() [2/2]
QTextCodec * QTextCodec::codecForName (const char * name) inline static
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
Returns 0 if no codec matching the name name could be found.
Definition at line 67 of file qtextcodec.h.
Referenced by codecForName().
 { return codecForName(QByteArray(name)); }
codecForTr()
QTextCodec * QTextCodec::codecForTr () inline static
Returns the codec used by QObject::tr() on its argument.
If this function returns 0 (the default), tr() assumes Latin-1.
See also
setCodecForTr()
Definition at line 155 of file qtextcodec.h.
Referenced by QCoreApplication::translate().
 { return validCodecs() ? cftr : 0; }
codecForUtfText() [1/2]
QTextCodec * QTextCodec::codecForUtfText (const QByteArray & ba) static
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the codec cannot be detected, this overload returns a Latin-1 QTextCodec.
See also
codecForHtml()
Definition at line 1873 of file qtextcodec.cpp.
Referenced by codecForHtml(), QTextStreamPrivate::fillReadBuffer(), QDeclarativeXMLHttpRequest::findTextCodec(), and QClipboard::text().
 {
     return codecForUtfText(ba, QTextCodec::codecForMib(/*Latin 1*/ 4));
 }
codecForUtfText() [2/2]
QTextCodec * QTextCodec::codecForUtfText (const QByteArray & ba, QTextCodec * defaultCodec) static
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
Since
4.6
If the codec cannot be detected from the content provided, defaultCodec is returned.
See also
codecForHtml()
Definition at line 1826 of file qtextcodec.cpp.
 {
     const int arraySize = ba.size();
     if (arraySize > 3) {
         if ((uchar)ba[0] == 0x00
             && (uchar)ba[1] == 0x00
             && (uchar)ba[2] == 0xFE
             && (uchar)ba[3] == 0xFF)
             return QTextCodec::codecForMib(1018); // utf-32 be
         else if ((uchar)ba[0] == 0xFF
                  && (uchar)ba[1] == 0xFE
                  && (uchar)ba[2] == 0x00
                  && (uchar)ba[3] == 0x00)
             return QTextCodec::codecForMib(1019); // utf-32 le
     }
     if (arraySize < 2)
         return defaultCodec;
     if ((uchar)ba[0] == 0xfe && (uchar)ba[1] == 0xff)
         return QTextCodec::codecForMib(1013); // utf16 be
     else if ((uchar)ba[0] == 0xff && (uchar)ba[1] == 0xfe)
         return QTextCodec::codecForMib(1014); // utf16 le
     if (arraySize < 3)
         return defaultCodec;
     if ((uchar)ba[0] == 0xef
         && (uchar)ba[1] == 0xbb
         && (uchar)ba[2] == 0xbf)
         return QTextCodec::codecForMib(106); // utf-8
     return defaultCodec;
 }
convertFromUnicode()
QByteArray QTextCodec::convertFromUnicode (const QChar * input, int number, ConverterState * state) const protected pure virtual
QTextCodec subclasses must reimplement this function.
Converts the first number of characters from the input array from Unicode to the encoding of the subclass, and returns the result in a QByteArray.
state can be 0 in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implemented in QWindowsLocalCodec, QFontGb18030_0Codec, QUtf32Codec, QFontGbkCodec, QFontKsc5601Codec, QFontGb2312Codec, QFontBig5hkscsCodec, QUtf16Codec, QCP949Codec, QTsciiCodec, QFontBig5Codec, QGb2312Codec, QUtf8Codec, QEucJpCodec, QJisCodec, QSjisCodec, QEucKrCodec, QFontJis0208Codec, QLatin15Codec, QGbkCodec, QBig5hkscsCodec, QIconvCodec, QSimpleTextCodec, QFontLaoCodec, QIsciiCodec, QLatin1Codec, QGb18030Codec, QBig5Codec, and QFontJis0201Codec.
convertToUnicode()
QString QTextCodec::convertToUnicode (const char * chars, int len, ConverterState * state) const protected pure virtual
QTextCodec subclasses must reimplement this function.
Converts the first len characters of chars from the encoding of the subclass to Unicode, and returns the result in a QString.
state can be 0, in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implemented in QWindowsLocalCodec, QFontGb18030_0Codec, QUtf32Codec, QFontGbkCodec, QFontKsc5601Codec, QFontGb2312Codec, QFontBig5hkscsCodec, QUtf16Codec, QCP949Codec, QTsciiCodec, QFontBig5Codec, QGb2312Codec, QUtf8Codec, QEucJpCodec, QJisCodec, QSjisCodec, QEucKrCodec, QFontJis0208Codec, QLatin15Codec, QGbkCodec, QBig5hkscsCodec, QIconvCodec, QSimpleTextCodec, QFontLaoCodec, QIsciiCodec, QLatin1Codec, QFontJis0201Codec, QGb18030Codec, and QBig5Codec.
fromUnicode() [1/2]
QByteArray QTextCodec::fromUnicode (const QString & uc) const
Converts str from Unicode to the encoding of this codec, and returns the result in a QByteArray.
Definition at line 1388 of file qtextcodec.cpp.
Referenced by canEncode(), QAbstractConcatenable::convertToAscii(), encodeString(), QTextStreamPrivate::flushWriteBuffer(), fromUnicode(), QTextEncoder::fromUnicode(), QSettingsPrivate::iniEscapedString(), qstring_to_xtp(), QFontEngineXLFD::stringToCMap(), QChar::toAscii(), QString::toAscii(), QStringRef::toAscii(), QString::toLocal8Bit(), and QStringRef::toLocal8Bit().
 {
     return convertFromUnicode(str.constData(), str.length(), 0);
 }
fromUnicode() [2/2]
QByteArray QTextCodec::fromUnicode (const QChar * input, int number, ConverterState * state = 0) const inline
Converts the first number of characters from the input array from Unicode to the encoding of this codec, and returns the result in a QByteArray.
The state of the convertor used is updated.
Definition at line 117 of file qtextcodec.h.
         { return convertFromUnicode(in, length, state); }
makeDecoder() [1/2]
QTextDecoder * QTextCodec::makeDecoder () const
Creates a QTextDecoder which stores enough state to decode chunks of char * data to create chunks of Unicode data.
The caller is responsible for deleting the returned object.
Definition at line 1330 of file qtextcodec.cpp.
Referenced by QXmlInputSource::fromRawData(), QXmlStreamReaderPrivate::getChar_helper(), and QXmlStreamReaderPrivate::startDocument().
 {
     return new QTextDecoder(this);
 }
makeDecoder() [2/2]
QTextDecoder* QTextCodec::makeDecoder (ConversionFlags flags) const
makeEncoder() [1/2]
QTextEncoder * QTextCodec::makeEncoder () const
Creates a QTextEncoder which stores enough state to encode chunks of Unicode data as char * data.
The caller is responsible for deleting the returned object.
Definition at line 1355 of file qtextcodec.cpp.
Referenced by QXmlStreamWriterPrivate::QXmlStreamWriterPrivate(), and QXmlStreamWriter::setCodec().
 {
     return new QTextEncoder(this);
 }
makeEncoder() [2/2]
QTextEncoder* QTextCodec::makeEncoder (ConversionFlags flags) const
mibEnum()
int QTextCodec::mibEnum () const pure virtual
Subclasses of QTextCodec must reimplement this function.
It returns the MIBenum (see IANA character-sets encoding file for more information). It is important that each QTextCodec subclass returns the correct unique value for this function.
Implemented in QWindowsLocalCodec, QUtf32LECodec, QUtf32BECodec, QFontGb18030_0Codec, QUtf32Codec, QFontGbkCodec, QUtf16LECodec, QUtf16BECodec, QFontKsc5601Codec, QFontGb2312Codec, QFontBig5hkscsCodec, QUtf16Codec, QCP949Codec, QTsciiCodec, QFontBig5Codec, QGb2312Codec, QUtf8Codec, QEucJpCodec, QJisCodec, QSjisCodec, QLatin15Codec, QEucKrCodec, QFontJis0208Codec, QIconvCodec, QSimpleTextCodec, QGbkCodec, QBig5hkscsCodec, QLatin1Codec, QFontLaoCodec, QIsciiCodec, QGb18030Codec, QFontJis0201Codec, and QBig5Codec.
Referenced by codecForMib(), QFontEngineXLFD::faceId(), QXmlInputSource::fromRawData(), qt_set_input_encoding(), qt_x11_set_fallback_font_family(), QTextDecoder::toUnicode(), QXlibKeyboard::translateKeySym(), QXcbKeyboard::translateKeySym(), and translateKeySym().
name()
QByteArray QTextCodec::name () const pure virtual
QTextCodec subclasses must reimplement this function.
It returns the name of the encoding supported by the subclass.
If the codec is registered as a character set in the IANA character-sets encoding file this method should return the preferred mime name for the codec if defined, otherwise its name.
Implemented in QWindowsLocalCodec, QUtf32LECodec, QUtf32BECodec, QFontGb18030_0Codec, QUtf32Codec, QFontGbkCodec, QUtf16LECodec, QUtf16BECodec, QFontKsc5601Codec, QFontGb2312Codec, QFontBig5hkscsCodec, QUtf16Codec, QCP949Codec, QTsciiCodec, QGb2312Codec, QFontBig5Codec, QUtf8Codec, QEucJpCodec, QJisCodec, QSjisCodec, QLatin15Codec, QEucKrCodec, QIconvCodec, QFontJis0208Codec, QSimpleTextCodec, QGbkCodec, QBig5hkscsCodec, QLatin1Codec, QFontLaoCodec, QIsciiCodec, QGb18030Codec, QFontJis0201Codec, and QBig5Codec.
Referenced by codecForName(), QTextStreamPrivate::fillReadBuffer(), QTextStreamPrivate::flushWriteBuffer(), QX11Data::motifdndFormat(), qToField(), QDomDocumentPrivate::saveDocument(), and QTextDocumentWriter::write().
setCodecForCStrings()
void QTextCodec::setCodecForCStrings (QTextCodec * codec) inline static
Note
This class or function is not reentrant.
Sets the codec used by QString to convert to and from const char * and QByteArrays. If the codec is 0 (the default), QString assumes Latin-1.
Warning
Some codecs do not preserve the characters in the ASCII range (0x00 to 0x7F). For example, the Japanese Shift-JIS encoding maps the backslash character (0x5A) to the Yen character. To avoid undesirable side-effects, we recommend avoiding such codecs with setCodecsForCString().
See also
codecForCStrings(), setCodecForTr()
Definition at line 158 of file qtextcodec.h.
 { QString::codecForCStrings = c; }
setCodecForLocale()
void QTextCodec::setCodecForLocale (QTextCodec * c) static
Set the codec to c; this will be returned by codecForLocale().
If c is a null pointer, the codec is reset to the default.
This might be needed for some applications that want to use their own mechanism for setting the locale.
See also
codecForLocale()
Definition at line 1218 of file qtextcodec.cpp.
 {
 #ifndef QT_NO_THREAD
     QMutexLocker locker(textCodecsMutex());
 #endif
     localeMapper = c;
     if (!localeMapper)
         setupLocaleMapper();
 }
setCodecForTr()
void QTextCodec::setCodecForTr (QTextCodec * c) inline static
Note
This class or function is not reentrant.
Sets the codec used by QObject::tr() on its argument to c. If c is 0 (the default), tr() assumes Latin-1.
If the literal quoted text in the program is not in the Latin-1 encoding, this function can be used to set the appropriate encoding. For example, software developed by Korean programmers might use eucKR for all the text in the program, in which case the main() function might look like this:
int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    QTextCodec::setCodecForTr(QTextCodec::codecForName("eucKR"));
    ...
}
Note that this is not the way to select the encoding that the user has chosen. For example, to convert an application containing literal English strings to Korean, all that is needed is for the English strings to be passed through tr() and for translation files to be loaded. For details of internationalization, see Internationalization with Qt.
See also
codecForTr(), setCodecForCStrings()
Definition at line 156 of file qtextcodec.h.
Referenced by QApplicationPrivate::qt_mac_apply_settings(), and QApplicationPrivate::x11_apply_settings().
 { cftr = c; }
toUnicode() [1/3]
QString QTextCodec::toUnicode (const QByteArray & a) const
Converts a from the encoding of this codec to Unicode, and returns the result in a QString.
Definition at line 1408 of file qtextcodec.cpp.
Referenced by canEncode(), QIconvCodec::convertToUnicode(), QTextStreamPrivate::fillReadBuffer(), QChar::fromAscii(), QString::fromAscii_helper(), QString::fromLocal8Bit(), getIBaseError(), QIBaseResult::gotoNext(), QSettingsPrivate::iniUnescapedStringList(), QXlibMime::mimeConvertToFormat(), QChar::QChar(), readArrayBuffer(), QDeclarativeXMLHttpRequest::responseBody(), QMimeDataPrivate::retrieveTypedData(), QPatternist::AccelTreeResourceLoader::retrieveUnparsedText(), QTextBrowserPrivate::setSource(), QClipboard::text(), toUnicode(), QFontEngineXLFD::toUnicode(), QTextDecoder::toUnicode(), QCoreApplication::translate(), translateKeyEventInternal(), QXlibKeyboard::translateKeySym(), QXcbKeyboard::translateKeySym(), translateKeySym(), QCUPSSupport::unicodeString(), QKeyMapperPrivate::updateKeyMap(), QString::vsprintf(), QXIMInputContext::x11FilterEvent(), and QX11Data::xdndMimeConvertToFormat().
 {
     return convertToUnicode(a.constData(), a.length(), 0);
 }
toUnicode() [2/3]
QString QTextCodec::toUnicode (const char * chars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.chars contains the source characters.
Definition at line 1485 of file qtextcodec.cpp.
 {
     int len = qstrlen(chars);
     return convertToUnicode(chars, len, 0);
 }
toUnicode() [3/3]
QString QTextCodec::toUnicode (const char * input, int size, ConverterState * state = 0) const inline
Converts the first size characters from the input from the encoding of this codec to Unicode, and returns the result in a QString.
The state of the convertor used is updated.
Definition at line 115 of file qtextcodec.h.
         { return convertToUnicode(in, length, state); }
validCodecs()
bool QTextCodec::validCodecs () static private
Definition at line 233 of file qtextcodec.cpp.
 {
 #ifdef Q_OS_SYMBIAN
     // If we don't have a trap handler, we're outside of the main() function,
     // ie. in global constructors or destructors. Don't use codecs in this
     // case as it would lead to crashes because we don't have a cleanup stack on Symbian
     return (User::TrapHandler() != NULL);
 #else
     return true;
 #endif
 }
Friends and Related Functions
QTextCodecCleanup
friend class QTextCodecCleanup friend
Definition at line 149 of file qtextcodec.h.
Properties
cftr
QTextCodec * QTextCodec::cftr = 0 static private
Definition at line 150 of file qtextcodec.h.
The documentation for this class was generated from the following files:
/src/corelib/codecs/qtextcodec.h
/src/corelib/codecs/qtextcodec.cpp