Qt 4.8: QPainterPathStroker Class Reference
QPainterPathStroker Class Reference
The QPainterPathStroker class is used to generate fillable outlines for a given painter path.
#include <qpainterpath.h>
Public Functions
Qt::PenCapStyle capStyle () const
Returns the cap style of the generated outlines.
QPainterPath createStroke (const QPainterPath &path) const
Generates a new path that is a fillable area representing the outline of the given path.
qreal curveThreshold () const
Returns the curve flattening threshold for the generated outlines.
qreal dashOffset () const
Returns the dash offset for the generated outlines.
QVector< qreal > dashPattern () const
Returns the dash pattern for the generated outlines.
Qt::PenJoinStyle joinStyle () const
Returns the join style of the generated outlines.
qreal miterLimit () const
Returns the miter limit for the generated outlines.
QPainterPathStroker ()
Creates a new stroker.
void setCapStyle (Qt::PenCapStyle style)
Sets the cap style of the generated outlines to style.
void setCurveThreshold (qreal threshold)
Specifies the curve flattening threshold, controlling the granularity with which the generated outlines' curve is drawn.
void setDashOffset (qreal offset)
Sets the dash offset for the generated outlines to offset.
void setDashPattern (Qt::PenStyle)
Sets the dash pattern for the generated outlines to style.
void setDashPattern (const QVector< qreal > &dashPattern)
Sets the dash pattern for the generated outlines to dashPattern.
void setJoinStyle (Qt::PenJoinStyle style)
Sets the join style of the generated outlines to style.
void setMiterLimit (qreal length)
Sets the miter limit of the generated outlines to limit.
void setWidth (qreal width)
Sets the width of the generated outline painter path to width.
qreal width () const
Returns the width of the generated outlines.
~QPainterPathStroker ()
Destroys the stroker.
Properties
QScopedPointer< QPainterPathStrokerPrivate > d_ptr
Friends
class QX11PaintEngine
Detailed Description
The QPainterPathStroker class is used to generate fillable outlines for a given painter path.
Since
4.1
By calling the createStroke() function, passing a given QPainterPath as argument, a new painter path representing the outline of the given path is created. The newly created painter path can then be filled to draw the original painter path's outline.
You can control the various design aspects (width, cap styles, join styles and dash pattern) of the outlining using the following functions:
setWidth()
setCapStyle()
setJoinStyle()
setDashPattern()
The setDashPattern() function accepts both a Qt::PenStyle object and a vector representation of the pattern as argument.
In addition you can specify a curve's threshold, controlling the granularity with which a curve is drawn, using the setCurveThreshold() function. The default threshold is a well adjusted value (0.25), and normally you should not need to modify it. However, you can make the curve's appearance smoother by decreasing its value.
You can also control the miter limit for the generated outline using the setMiterLimit() function. The miter limit describes how far from each join the miter join can extend. The limit is specified in the units of width so the pixelwise miter limit will be {miterlimit * width}. This value is only used if the join style is Qt::MiterJoin.
The painter path generated by the createStroke() function should only be used for outlining the given painter path. Otherwise it may cause unexpected behavior. Generated outlines also require the Qt::WindingFill rule which is set by default.
See also
QPen, QBrush
Definition at line 264 of file qpainterpath.h.
Constructors and Destructors
QPainterPathStroker()
QPainterPathStroker::QPainterPathStroker ()
Creates a new stroker.
Definition at line 2669 of file qpainterpath.cpp.
     : d_ptr(new QPainterPathStrokerPrivate)
 {
 }
~QPainterPathStroker()
QPainterPathStroker::~QPainterPathStroker ()
Destroys the stroker.
Definition at line 2677 of file qpainterpath.cpp.
 {
 }
Functions
capStyle()
Qt::PenCapStyle QPainterPathStroker::capStyle () const
Returns the cap style of the generated outlines.
Definition at line 2751 of file qpainterpath.cpp.
 {
     return d_func()->stroker.capStyle();
 }
createStroke()
QPainterPath QPainterPathStroker::createStroke (const QPainterPath & path) const
Generates a new path that is a fillable area representing the outline of the given path.
The various design aspects of the outline are based on the stroker's properties: width(), capStyle(), joinStyle(), dashPattern(), curveThreshold() and miterLimit().
The generated path should only be used for outlining the given painter path. Otherwise it may cause unexpected behavior. Generated outlines also require the Qt::WindingFill rule which is set by default.
Definition at line 2695 of file qpainterpath.cpp.
Referenced by QAlphaPaintEnginePrivate::addPenWidth(), boundsOnStroke(), QPainterPrivate::draw_helper(), QX11PaintEngine::drawPath(), QMacStyle::drawPrimitive(), QPainterPrivate::drawStretchedGradient(), qt_graphicsItem_shapeFromPath(), strokeForPath(), and QWin32PrintEnginePrivate::strokePath().
 {
     QPainterPathStrokerPrivate *d = const_cast<QPainterPathStrokerPrivate *>(d_func());
     QPainterPath stroke;
     if (path.isEmpty())
         return path;
     if (d->dashPattern.isEmpty()) {
         d->stroker.strokePath(path, &stroke, QTransform());
     } else {
         QDashStroker dashStroker(&d->stroker);
         dashStroker.setDashPattern(d->dashPattern);
         dashStroker.setDashOffset(d->dashOffset);
         dashStroker.setClipRect(d->stroker.clipRect());
         dashStroker.strokePath(path, &stroke, QTransform());
     }
     stroke.setFillRule(Qt::WindingFill);
     return stroke;
 }
curveThreshold()
qreal QPainterPathStroker::curveThreshold () const
Returns the curve flattening threshold for the generated outlines.
Definition at line 2813 of file qpainterpath.cpp.
 {
     return qt_fixed_to_real(d_func()->stroker.curveThreshold());
 }
dashOffset()
qreal QPainterPathStroker::dashOffset () const
Returns the dash offset for the generated outlines.
Definition at line 2863 of file qpainterpath.cpp.
 {
     return d_func()->dashOffset;
 }
dashPattern()
QVector< qreal > QPainterPathStroker::dashPattern () const
Returns the dash pattern for the generated outlines.
Definition at line 2855 of file qpainterpath.cpp.
 {
     return d_func()->dashPattern;
 }
joinStyle()
Qt::PenJoinStyle QPainterPathStroker::joinStyle () const
Returns the join style of the generated outlines.
Definition at line 2767 of file qpainterpath.cpp.
 {
     return d_func()->stroker.joinStyle();
 }
miterLimit()
qreal QPainterPathStroker::miterLimit () const
Returns the miter limit for the generated outlines.
Definition at line 2790 of file qpainterpath.cpp.
 {
     return qt_fixed_to_real(d_func()->stroker.miterLimit());
 }
setCapStyle()
void QPainterPathStroker::setCapStyle (Qt::PenCapStyle style)
Sets the cap style of the generated outlines to style.
If a dash pattern is set, each segment of the pattern is subject to the cap style.
Definition at line 2742 of file qpainterpath.cpp.
Referenced by QAlphaPaintEnginePrivate::addPenWidth(), QPainterPrivate::draw_helper(), QX11PaintEngine::drawPath(), QMacStyle::drawPrimitive(), QPainterPrivate::drawStretchedGradient(), qt_graphicsItem_shapeFromPath(), strokeForPath(), and QWin32PrintEnginePrivate::strokePath().
 {
     d_func()->stroker.setCapStyle(style);
 }
setCurveThreshold()
void QPainterPathStroker::setCurveThreshold (qreal threshold)
Specifies the curve flattening threshold, controlling the granularity with which the generated outlines' curve is drawn.
The default threshold is a well adjusted value (0.25), and normally you should not need to modify it. However, you can make the curve's appearance smoother by decreasing its value.
Definition at line 2804 of file qpainterpath.cpp.
 {
     d_func()->stroker.setCurveThreshold(qt_real_to_fixed(threshold));
 }
setDashOffset()
void QPainterPathStroker::setDashOffset (qreal offset)
Sets the dash offset for the generated outlines to offset.
See the documentation for QPen::setDashOffset() for a description of the dash offset.
Definition at line 2874 of file qpainterpath.cpp.
Referenced by QX11PaintEngine::drawPath(), strokeForPath(), and QWin32PrintEnginePrivate::strokePath().
 {
     d_func()->dashOffset = offset;
 }
setDashPattern() [1/2]
void QPainterPathStroker::setDashPattern (Qt::PenStyle style)
Sets the dash pattern for the generated outlines to style.
Definition at line 2821 of file qpainterpath.cpp.
Referenced by QX11PaintEngine::drawPath(), QMacStyle::drawPrimitive(), QPainterPrivate::drawStretchedGradient(), strokeForPath(), and QWin32PrintEnginePrivate::strokePath().
 {
     d_func()->dashPattern = QDashStroker::patternForStyle(style);
 }
setDashPattern() [2/2]
void QPainterPathStroker::setDashPattern (const QVector< qreal > & dashPattern)
Sets the dash pattern for the generated outlines to dashPattern.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function makes it possible to specify custom dash patterns.
Each element in the vector contains the lengths of the dashes and spaces in the stroke, beginning with the first dash in the first element, the first space in the second element, and alternating between dashes and spaces for each following pair of elements.
The vector can contain an odd number of elements, in which case the last element will be extended by the length of the first element when the pattern repeats.
Definition at line 2845 of file qpainterpath.cpp.
 {
     d_func()->dashPattern.clear();
     for (int i=0; i<dashPattern.size(); ++i)
         d_func()->dashPattern << qt_real_to_fixed(dashPattern.at(i));
 }
setJoinStyle()
void QPainterPathStroker::setJoinStyle (Qt::PenJoinStyle style)
Sets the join style of the generated outlines to style.
Definition at line 2759 of file qpainterpath.cpp.
Referenced by QAlphaPaintEnginePrivate::addPenWidth(), QPainterPrivate::draw_helper(), QX11PaintEngine::drawPath(), QPainterPrivate::drawStretchedGradient(), qt_graphicsItem_shapeFromPath(), strokeForPath(), and QWin32PrintEnginePrivate::strokePath().
 {
     d_func()->stroker.setJoinStyle(style);
 }
setMiterLimit()
void QPainterPathStroker::setMiterLimit (qreal limit)
Sets the miter limit of the generated outlines to limit.
The miter limit describes how far from each join the miter join can extend. The limit is specified in units of the currently set width. So the pixelwise miter limit will be { miterlimit * width}.
This value is only used if the join style is Qt::MiterJoin.
Definition at line 2782 of file qpainterpath.cpp.
Referenced by QPainterPrivate::drawStretchedGradient(), qt_graphicsItem_shapeFromPath(), strokeForPath(), and QWin32PrintEnginePrivate::strokePath().
 {
     d_func()->stroker.setMiterLimit(qt_real_to_fixed(limit));
 }
setWidth()
void QPainterPathStroker::setWidth (qreal width)
Sets the width of the generated outline painter path to width.
The generated outlines will extend approximately 50% of width to each side of the given input path's original outline.
Definition at line 2720 of file qpainterpath.cpp.
Referenced by QAlphaPaintEnginePrivate::addPenWidth(), boundsOnStroke(), QPainterPrivate::draw_helper(), QX11PaintEngine::drawPath(), QPainterPrivate::drawStretchedGradient(), qt_graphicsItem_shapeFromPath(), strokeForPath(), and QWin32PrintEnginePrivate::strokePath().
 {
     Q_D(QPainterPathStroker);
     if (width <= 0)
         width = 1;
     d->stroker.setStrokeWidth(qt_real_to_fixed(width));
 }
width()
qreal QPainterPathStroker::width () const
Returns the width of the generated outlines.
Definition at line 2731 of file qpainterpath.cpp.
 {
     return qt_fixed_to_real(d_func()->stroker.strokeWidth());
 }
Friends and Related Functions
QX11PaintEngine
friend class QX11PaintEngine friend
Definition at line 298 of file qpainterpath.h.
Properties
d_ptr
QScopedPointer<QPainterPathStrokerPrivate> QPainterPathStroker::d_ptr private
Definition at line 300 of file qpainterpath.h.
Referenced by QPainterPath::computeBoundingRect(), QPainterPath::computeControlPointRect(), QX11PaintEngine::drawPath(), and QPainterPath::pointAtPercent().
The documentation for this class was generated from the following files:
/src/gui/painting/qpainterpath.h
/src/gui/painting/qpainterpath.cpp