Qt 4.8: QAbstractScrollArea Class Reference
QAbstractScrollArea Class Reference
The QAbstractScrollArea widget provides a scrolling area with on-demand scroll bars.
#include <qabstractscrollarea.h>
Public Functions
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Slots
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Functions
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
virtual void scrollContentsBy (int dx, int dy)
This virtual handler is called when the scroll bars are moved by dx, dy, and consequently the viewport's contents should be scrolled accordingly.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
virtual bool viewportEvent (QEvent *)
The main event handler for the scrolling area (the viewport() widget).
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
Qt::ScrollBarPolicy horizontalScrollBarPolicy
the policy for the horizontal scroll bar
Qt::ScrollBarPolicy verticalScrollBarPolicy
the policy for the vertical scroll bar
Friends
class QStyleSheetStyle
class QWidgetPrivate
Additional Inherited Members
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QAbstractScrollArea widget provides a scrolling area with on-demand scroll bars.
QAbstractScrollArea is a low-level abstraction of a scrolling area. The area provides a central widget called the viewport, in which the contents of the area is to be scrolled (i.e, the visible parts of the contents are rendered in the viewport).
Next to the viewport is a vertical scroll bar, and below is a horizontal scroll bar. When all of the area contents fits in the viewport, each scroll bar can be either visible or hidden depending on the scroll bar's Qt::ScrollBarPolicy. When a scroll bar is hidden, the viewport expands in order to cover all available space. When a scroll bar becomes visible again, the viewport shrinks in order to make room for the scroll bar.
It is possible to reserve a margin area around the viewport, see setViewportMargins(). The feature is mostly used to place a QHeaderView widget above or beside the scrolling area. Subclasses of QAbstractScrollArea should implement margins.
When inheriting QAbstractScrollArea, you need to do the following:
Control the scroll bars by setting their range, value, page step, and tracking their movements.
Draw the contents of the area in the viewport according to the values of the scroll bars.
Handle events received by the viewport in viewportEvent() - notably resize events.
Use viewport->update() to update the contents of the viewport instead of update() as all painting operations take place on the viewport.
With a scroll bar policy of Qt::ScrollBarAsNeeded (the default), QAbstractScrollArea shows scroll bars when they provide a non-zero scrolling range, and hides them otherwise.
The scroll bars and viewport should be updated whenever the viewport receives a resize event or the size of the contents changes. The viewport also needs to be updated when the scroll bars values change. The initial values of the scroll bars are often set when the area receives new contents.
We give a simple example, in which we have implemented a scroll area that can scroll any QWidget. We make the widget a child of the viewport; this way, we do not have to calculate which part of the widget to draw but can simply move the widget with QWidget::move(). When the area contents or the viewport size changes, we do the following:
    QSize areaSize = viewport()->size();
    QSize  widgetSize = widget->size();
    verticalScrollBar()->setPageStep(areaSize.height());
    horizontalScrollBar()->setPageStep(areaSize.width());
    verticalScrollBar()->setRange(0, widgetSize.height() - areaSize.height());
    horizontalScrollBar()->setRange(0, widgetSize.width() - areaSize.width());
    updateWidgetPosition();
When the scroll bars change value, we need to update the widget position, i.e., find the part of the widget that is to be drawn in the viewport:
    int hvalue = horizontalScrollBar()->value();
    int vvalue = verticalScrollBar()->value();
    QPoint topLeft = viewport()->rect().topLeft();
    widget->move(topLeft.x() - hvalue, topLeft.y() - vvalue);
In order to track scroll bar movements, reimplement the virtual function scrollContentsBy(). In order to fine-tune scrolling behavior, connect to a scroll bar's QAbstractSlider::actionTriggered() signal and adjust the QAbstractSlider::sliderPosition as you wish.
For convenience, QAbstractScrollArea makes all viewport events available in the virtual viewportEvent() handler. QWidget's specialized handlers are remapped to viewport events in the cases where this makes sense. The remapped specialized handlers are: paintEvent(), mousePressEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), wheelEvent(), dragEnterEvent(), dragMoveEvent(), dragLeaveEvent(), dropEvent(), contextMenuEvent(), and resizeEvent().
QScrollArea, which inherits QAbstractScrollArea, provides smooth scrolling for any QWidget (i.e., the widget is scrolled pixel by pixel). You only need to subclass QAbstractScrollArea if you need more specialized behavior. This is, for instance, true if the entire contents of the area is not suitable for being drawn on a QWidget or if you do not want smooth scrolling.
See also
QScrollArea
Definition at line 59 of file qabstractscrollarea.h.
Constructors and Destructors
QAbstractScrollArea() [1/2]
QAbstractScrollArea::QAbstractScrollArea (QWidget * parent = 0) explicit
Constructs a viewport.
The parent argument is sent to the QWidget constructor.
Definition at line 519 of file qabstractscrollarea.cpp.
Referenced by QTextEdit::QTextEdit().
     :QFrame(*new QAbstractScrollAreaPrivate, parent)
 {
     Q_D(QAbstractScrollArea);
     QT_TRY {
         d->init();
     } QT_CATCH(...) {
         d->viewportFilter.reset();
         QT_RETHROW;
     }
 }
~QAbstractScrollArea()
QAbstractScrollArea::~QAbstractScrollArea ()
Destroys the viewport.
Definition at line 535 of file qabstractscrollarea.cpp.
 {
     Q_D(QAbstractScrollArea);
     // reset it here, otherwise we'll have a dangling pointer in ~QWidget
     d->viewportFilter.reset();
 }
QAbstractScrollArea() [2/2]
QAbstractScrollArea::QAbstractScrollArea (QAbstractScrollAreaPrivate & dd, QWidget * parent = 0) protected
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
Warning
This function is not part of the public interface.
Definition at line 502 of file qabstractscrollarea.cpp.
     :QFrame(dd, parent)
 {
     Q_D(QAbstractScrollArea);
     QT_TRY {
         d->init();
     } QT_CATCH(...) {
         d->viewportFilter.reset();
         QT_RETHROW;
     }
 }
Functions
addScrollBarWidget()
void QAbstractScrollArea::addScrollBarWidget (QWidget * widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
Since
4.2
Scroll bar widgets are shown next to the horizontal or vertical scroll bar, and can be placed on either side of it. If you want the scroll bar widgets to be always visible, set the scrollBarPolicy for the corresponding scroll bar to AlwaysOn.
alignment must be one of Qt::Alignleft and Qt::AlignRight, which maps to the horizontal scroll bar, or Qt::AlignTop and Qt::AlignBottom, which maps to the vertical scroll bar.
A scroll bar widget can be removed by either re-parenting the widget or deleting it. It's also possible to hide a widget with QWidget::hide()
The scroll bar widget will be resized to fit the scroll bar geometry for the current style. The following describes the case for scroll bar widgets on the horizontal scroll bar:
The height of the widget will be set to match the height of the scroll bar. To control the width of the widget, use QWidget::setMinimumWidth and QWidget::setMaximumWidth, or implement QWidget::sizeHint() and set a horizontal size policy. If you want a square widget, call QStyle::pixelMetric(QStyle::PM_ScrollBarExtent) and set the width to this value.
See also
scrollBarWidgets()
Definition at line 850 of file qabstractscrollarea.cpp.
 {
     Q_D(QAbstractScrollArea);
     if (widget == 0)
         return;
     const Qt::Orientation scrollBarOrientation
         = ((alignment & Qt::AlignLeft) || (alignment & Qt::AlignRight)) ? Qt::Horizontal : Qt::Vertical;
     const QAbstractScrollAreaScrollBarContainer::LogicalPosition position
         = ((alignment & Qt::AlignRight) || (alignment & Qt::AlignBottom))
           ? QAbstractScrollAreaScrollBarContainer::LogicalRight : QAbstractScrollAreaScrollBarContainer::LogicalLeft;
     d->scrollBarContainers[scrollBarOrientation]->addWidget(widget, position);
     d->layoutChildren();
     if (isHidden() == false)
         widget->show();
 }
contextMenuEvent()
void QAbstractScrollArea::contextMenuEvent (QContextMenuEvent * e) protected virtual
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
The event is passed in e.
See also
QWidget::contextMenuEvent()
Reimplemented from QWidget.
Reimplemented in QTextEdit, and QPlainTextEdit.
Definition at line 1205 of file qabstractscrollarea.cpp.
Referenced by QPlainTextEdit::toPlainText().
 {
     e->ignore();
 }
cornerWidget()
QWidget * QAbstractScrollArea::cornerWidget () const
Returns the widget in the corner between the two scroll bars.
Since
4.2
By default, no corner widget is present.
Definition at line 759 of file qabstractscrollarea.cpp.
Referenced by QAccessibleAbstractScrollArea::accessibleChildren(), QAccessibleAbstractScrollArea::elementType(), QAccessibleAbstractScrollArea::navigate(), and QColumnView::setResizeGripsVisible().
 {
     Q_D(const QAbstractScrollArea);
     return d->cornerWidget;
 }
dragEnterEvent()
void QAbstractScrollArea::dragEnterEvent (QDragEnterEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
See also
QWidget::dragEnterEvent()
Reimplemented from QWidget.
Reimplemented in QTextEdit, and QPlainTextEdit.
Definition at line 1284 of file qabstractscrollarea.cpp.
Referenced by QPlainTextEdit::toPlainText().
 {
 }
dragLeaveEvent()
void QAbstractScrollArea::dragLeaveEvent (QDragLeaveEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
See also
QWidget::dragLeaveEvent()
Reimplemented from QWidget.
Reimplemented in QTextEdit, and QPlainTextEdit.
Definition at line 1308 of file qabstractscrollarea.cpp.
Referenced by QPlainTextEdit::toPlainText().
 {
 }
dragMoveEvent()
void QAbstractScrollArea::dragMoveEvent (QDragMoveEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
See also
QWidget::dragMoveEvent()
Reimplemented from QWidget.
Reimplemented in QTextEdit, and QPlainTextEdit.
Definition at line 1296 of file qabstractscrollarea.cpp.
Referenced by QPlainTextEdit::toPlainText().
 {
 }
dropEvent()
void QAbstractScrollArea::dropEvent (QDropEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
See also
QWidget::dropEvent()
Reimplemented from QWidget.
Reimplemented in QTextEdit, and QPlainTextEdit.
Definition at line 1320 of file qabstractscrollarea.cpp.
Referenced by QPlainTextEdit::toPlainText().
 {
 }
event()
bool QAbstractScrollArea::event (QEvent * event) protected virtual
Reimplemented Function
This is the main event handler for the QAbstractScrollArea widget (not the scrolling area viewport()). The specified event is a general event object that may need to be cast to the appropriate class depending on its type.
See also
QEvent::type()
Reimplemented from QWidget.
Reimplemented in QCalendarView, QTextEdit, QPlainTextEdit, QMdiArea, QTextBrowser, and QScrollArea.
Definition at line 951 of file qabstractscrollarea.cpp.
Referenced by QScrollArea::event(), QMdiArea::event(), QPlainTextEdit::event(), QGraphicsView::event(), QTextEdit::event(), QAbstractItemView::event(), QPlainTextEdit::toPlainText(), and viewportEvent().
 {
     Q_D(QAbstractScrollArea);
     switch (e->type()) {
     case QEvent::AcceptDropsChange:
         // There was a chance that with accessibility client we get an
         // event before the viewport was created.
         // Also, in some cases we might get here from QWidget::event() virtual function which is (indirectly) called
         // from the viewport constructor at the time when the d->viewport is not yet initialized even without any
         // accessibility client. See qabstractscrollarea autotest for a test case.
         if (d->viewport)
             d->viewport->setAcceptDrops(acceptDrops());
         break;
     case QEvent::MouseTrackingChange:
         d->viewport->setMouseTracking(hasMouseTracking());
         break;
     case QEvent::Resize:
             d->layoutChildren();
             break;
     case QEvent::Paint: {
         QStyleOption option;
         option.initFrom(this);
         if (d->cornerPaintingRect.isValid()) {
             option.rect = d->cornerPaintingRect;
             QPainter p(this);
             style()->drawPrimitive(QStyle::PE_PanelScrollAreaCorner, &option, &p, this);
         }
 #ifdef Q_WS_MAC
         if (d->reverseCornerPaintingRect.isValid()) {
             option.rect = d->reverseCornerPaintingRect;
             QPainter p(this);
             style()->drawPrimitive(QStyle::PE_PanelScrollAreaCorner, &option, &p, this);
         }
 #endif
         }
         QFrame::paintEvent((QPaintEvent*)e);
         break;
 #ifndef QT_NO_CONTEXTMENU
     case QEvent::ContextMenu:
         if (static_cast<QContextMenuEvent *>(e)->reason() == QContextMenuEvent::Keyboard)
            return QFrame::event(e);
         e->ignore();
         break;
 #endif // QT_NO_CONTEXTMENU
     case QEvent::MouseButtonPress:
     case QEvent::MouseButtonRelease:
     case QEvent::MouseButtonDblClick:
     case QEvent::MouseMove:
     case QEvent::Wheel:
 #ifndef QT_NO_DRAGANDDROP
     case QEvent::Drop:
     case QEvent::DragEnter:
     case QEvent::DragMove:
     case QEvent::DragLeave:
 #endif
         // ignore touch events in case they have been propagated from the viewport
     case QEvent::TouchBegin:
     case QEvent::TouchUpdate:
     case QEvent::TouchEnd:
         return false;
 #ifndef QT_NO_GESTURES
     case QEvent::Gesture:
     {
         QGestureEvent *ge = static_cast<QGestureEvent *>(e);
         QPanGesture *g = static_cast<QPanGesture *>(ge->gesture(Qt::PanGesture));
         if (g) {
             QScrollBar *hBar = horizontalScrollBar();
             QScrollBar *vBar = verticalScrollBar();
             QPointF delta = g->delta();
             if (!delta.isNull()) {
                 if (QApplication::isRightToLeft())
                     delta.rx() *= -1;
                 int newX = hBar->value() - delta.x();
                 int newY = vBar->value() - delta.y();
                 hBar->setValue(newX);
                 vBar->setValue(newY);
             }
             return true;
         }
         return false;
     }
 #endif // QT_NO_GESTURES
     case QEvent::StyleChange:
     case QEvent::LayoutDirectionChange:
     case QEvent::ApplicationLayoutDirectionChange:
     case QEvent::LayoutRequest:
         d->layoutChildren();
         // fall through
     default:
         return QFrame::event(e);
     }
     return true;
 }
horizontalScrollBar()
QScrollBar * QAbstractScrollArea::horizontalScrollBar () const
Returns the horizontal scroll bar.
See also
horizontalScrollBarPolicy, verticalScrollBar()
Definition at line 716 of file qabstractscrollarea.cpp.
Referenced by QAccessibleAbstractScrollArea::accessibleChildren(), QGraphicsView::centerOn(), QTableView::columnCountChanged(), QAbstractItemView::doAutoScroll(), QGraphicsView::ensureVisible(), event(), QPlainTextEdit::event(), QAbstractItemView::horizontalScrollbarValueChanged(), QGraphicsView::mouseMoveEvent(), QTreeView::moveCursor(), QAccessibleAbstractScrollArea::navigate(), QAccessibleTextEdit::rect(), QAccessibleItemView::rect(), QColumnViewPreviewColumn::resizeEvent(), QColumnView::resizeEvent(), QTableView::scrollContentsBy(), QTreeView::scrollContentsBy(), QColumnView::scrollTo(), QTableView::scrollTo(), QListView::scrollTo(), QTreeView::scrollTo(), QAccessibleTextEdit::scrollToSubstring(), QMdiSubWindowPrivate::setMaximizeMode(), QCompleterPrivate::showPopup(), QComboBox::showPopup(), QTableView::updateGeometries(), and QListView::updateGeometries().
 {
     Q_D(const QAbstractScrollArea);
     return d->hbar;
 }
horizontalScrollBarPolicy()
Qt::ScrollBarPolicy QAbstractScrollArea::horizontalScrollBarPolicy () const
Referenced by setVerticalScrollBar(), QComboBox::showPopup(), and QListView::updateGeometries().
keyPressEvent()
void QAbstractScrollArea::keyPressEvent (QKeyEvent * e) protected virtual
This function is called with key event e when key presses occur.
It handles PageUp, PageDown, Up, Down, Left, and Right, and ignores all other key presses.
Reimplemented from QWidget.
Reimplemented in QCalendarView, QTextEdit, QPlainTextEdit, and QTextBrowser.
Definition at line 1216 of file qabstractscrollarea.cpp.
Referenced by QPlainTextEdit::keyPressEvent(), QGraphicsView::keyPressEvent(), QTextEdit::keyPressEvent(), and QPlainTextEdit::toPlainText().
 {
     Q_D(QAbstractScrollArea);
     if (false){
 #ifndef QT_NO_SHORTCUT
     } else if (e == QKeySequence::MoveToPreviousPage) {
         d->vbar->triggerAction(QScrollBar::SliderPageStepSub);
     } else if (e == QKeySequence::MoveToNextPage) {
         d->vbar->triggerAction(QScrollBar::SliderPageStepAdd);
 #endif
     } else {
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled() && !hasEditFocus()) {
             e->ignore();
             return;
         }
 #endif
         switch (e->key()) {
         case Qt::Key_Up:
             d->vbar->triggerAction(QScrollBar::SliderSingleStepSub);
             break;
         case Qt::Key_Down:
             d->vbar->triggerAction(QScrollBar::SliderSingleStepAdd);
             break;
         case Qt::Key_Left:
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled() && hasEditFocus()
             && (!d->hbar->isVisible() || d->hbar->value() == d->hbar->minimum())) {
             //if we aren't using the hbar or we are already at the leftmost point ignore
             e->ignore();
             return;
         }
 #endif
             d->hbar->triggerAction(
                 layoutDirection() == Qt::LeftToRight
                 ? QScrollBar::SliderSingleStepSub : QScrollBar::SliderSingleStepAdd);
             break;
         case Qt::Key_Right:
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled() && hasEditFocus()
             && (!d->hbar->isVisible() || d->hbar->value() == d->hbar->maximum())) {
             //if we aren't using the hbar or we are already at the rightmost point ignore
             e->ignore();
             return;
         }
 #endif
             d->hbar->triggerAction(
                 layoutDirection() == Qt::LeftToRight
                 ? QScrollBar::SliderSingleStepAdd : QScrollBar::SliderSingleStepSub);
             break;
         default:
             e->ignore();
             return;
         }
     }
     e->accept();
 }
maximumViewportSize()
QSize QAbstractScrollArea::maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
Definition at line 600 of file qabstractscrollarea.cpp.
Referenced by QTableView::updateGeometries().
 {
     Q_D(const QAbstractScrollArea);
     int hsbExt = d->hbar->sizeHint().height();
     int vsbExt = d->vbar->sizeHint().width();
     int f = 2 * d->frameWidth;
     QSize max = size() - QSize(f + d->left + d->right, f + d->top + d->bottom);
     if (d->vbarpolicy == Qt::ScrollBarAlwaysOn)
         max.rwidth() -= vsbExt;
     if (d->hbarpolicy == Qt::ScrollBarAlwaysOn)
         max.rheight() -= hsbExt;
     return max;
 }
minimumSizeHint()
QSize QAbstractScrollArea::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QMdiArea.
Definition at line 1397 of file qabstractscrollarea.cpp.
Referenced by QMdiArea::minimumSizeHint().
 {
     Q_D(const QAbstractScrollArea);
     int hsbExt = d->hbar->sizeHint().height();
     int vsbExt = d->vbar->sizeHint().width();
     int extra = 2 * d->frameWidth;
     QStyleOption opt;
     opt.initFrom(this);
     if ((d->frameStyle != QFrame::NoFrame)
         && style()->styleHint(QStyle::SH_ScrollView_FrameOnlyAroundContents, &opt, this)) {
         extra += style()->pixelMetric(QStyle::PM_ScrollView_ScrollBarSpacing, &opt, this);
     }
     return QSize(d->scrollBarContainers[Qt::Horizontal]->sizeHint().width() + vsbExt + extra,
                  d->scrollBarContainers[Qt::Vertical]->sizeHint().height() + hsbExt + extra);
 }
mouseDoubleClickEvent()
void QAbstractScrollArea::mouseDoubleClickEvent (QMouseEvent * e) protected virtual
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
The event is passed in e.
See also
QWidget::mouseDoubleClickEvent()
Reimplemented from QWidget.
Reimplemented in QCalendarView, QTextEdit, and QPlainTextEdit.
Definition at line 1162 of file qabstractscrollarea.cpp.
Referenced by QPlainTextEdit::toPlainText().
 {
     e->ignore();
 }
mouseMoveEvent()
void QAbstractScrollArea::mouseMoveEvent (QMouseEvent * e) protected virtual
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
The event is passed in e.
See also
QWidget::mouseMoveEvent()
Reimplemented from QWidget.
Reimplemented in QCalendarView, QTextEdit, QPlainTextEdit, and QTextBrowser.
Definition at line 1174 of file qabstractscrollarea.cpp.
Referenced by QPlainTextEdit::toPlainText().
 {
     e->ignore();
 }
mousePressEvent()
void QAbstractScrollArea::mousePressEvent (QMouseEvent * e) protected virtual
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
The event is passed in e.
See also
QWidget::mousePressEvent()
Reimplemented from QWidget.
Reimplemented in QCalendarView, QTextEdit, QPlainTextEdit, and QTextBrowser.
Definition at line 1138 of file qabstractscrollarea.cpp.
Referenced by QPlainTextEdit::toPlainText().
 {
     e->ignore();
 }
mouseReleaseEvent()
void QAbstractScrollArea::mouseReleaseEvent (QMouseEvent * e) protected virtual
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
The event is passed in e.
See also
QWidget::mouseReleaseEvent()
Reimplemented from QWidget.
Reimplemented in QCalendarView, QTextEdit, QPlainTextEdit, and QTextBrowser.
Definition at line 1150 of file qabstractscrollarea.cpp.
Referenced by QPlainTextEdit::toPlainText().
 {
     e->ignore();
 }
paintEvent()
void QAbstractScrollArea::paintEvent (QPaintEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
Note
If you open a painter, make sure to open it on the viewport().
See also
QWidget::paintEvent()
Reimplemented from QWidget.
Reimplemented in QTextEdit, QPlainTextEdit, QMdiArea, QTextBrowser, QComboBoxListView, and QScriptEdit.
Definition at line 1127 of file qabstractscrollarea.cpp.
Referenced by QGraphicsView::paintEvent(), and QPlainTextEdit::toPlainText().
 {
 }
resizeEvent()
void QAbstractScrollArea::resizeEvent (QResizeEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
When resizeEvent() is called, the viewport already has its new geometry: Its new size is accessible through the QResizeEvent::size() function, and the old size through QResizeEvent::oldSize().
See also
QWidget::resizeEvent()
Reimplemented from QWidget.
Reimplemented in QTextEdit, QPlainTextEdit, QMdiArea, QScriptEdit, QComboBoxListView, and QScrollArea.
Definition at line 1113 of file qabstractscrollarea.cpp.
Referenced by QColumnViewPreviewColumn::resizeEvent(), QGraphicsView::resizeEvent(), QAbstractItemView::resizeEvent(), and QPlainTextEdit::toPlainText().
 {
 }
scrollBarWidgets()
QWidgetList QAbstractScrollArea::scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
Since
4.2 alignment can be any combination of the four location flags.
See also
addScrollBarWidget()
Definition at line 878 of file qabstractscrollarea.cpp.
 {
     Q_D(QAbstractScrollArea);
     QWidgetList list;
     if (alignment & Qt::AlignLeft)
         list += d->scrollBarContainers[Qt::Horizontal]->widgets(QAbstractScrollAreaScrollBarContainer::LogicalLeft);
     if (alignment & Qt::AlignRight)
         list += d->scrollBarContainers[Qt::Horizontal]->widgets(QAbstractScrollAreaScrollBarContainer::LogicalRight);
     if (alignment & Qt::AlignTop)
         list += d->scrollBarContainers[Qt::Vertical]->widgets(QAbstractScrollAreaScrollBarContainer::LogicalLeft);
     if (alignment & Qt::AlignBottom)
         list += d->scrollBarContainers[Qt::Vertical]->widgets(QAbstractScrollAreaScrollBarContainer::LogicalRight);
     return list;
 }
scrollContentsBy()
void QAbstractScrollArea::scrollContentsBy (int dx, int dy) protected virtual
This virtual handler is called when the scroll bars are moved by dx, dy, and consequently the viewport's contents should be scrolled accordingly.
The default implementation simply calls update() on the entire viewport(), subclasses can reimplement this handler for optimization purposes, or - like QScrollArea - to move a contents widget. The parameters dx and dy are there for convenience, so that the class knows how much should be scrolled (useful e.g. when doing pixel-shifts). You may just as well ignore these values and scroll directly to the position the scroll bars indicate.
Calling this function in order to scroll programmatically is an error, use the scroll bars instead (e.g. by calling QScrollBar::setValue() directly).
Reimplemented in QTextEdit, QGraphicsView, QPlainTextEdit, QHeaderView, QTreeView, QMdiArea, QTableView, QListView, QColumnView, and QScrollArea.
Definition at line 1345 of file qabstractscrollarea.cpp.
Referenced by QColumnView::scrollContentsBy(), and QPlainTextEdit::toPlainText().
 {
     viewport()->update();
 }
setCornerWidget()
void QAbstractScrollArea::setCornerWidget (QWidget * widget)
Sets the widget in the corner between the two scroll bars to be widget.
Since
4.2
You will probably also want to set at least one of the scroll bar modes to AlwaysOn.
Passing 0 shows no widget in the corner.
Any previous corner widget is hidden.
You may call setCornerWidget() with the same widget at different times.
All widgets set here will be deleted by the scroll area when it is destroyed unless you separately reparent the widget after setting some other corner widget (or 0).
Any newly set widget should have no current parent.
By default, no corner widget is present.
See also
horizontalScrollBarPolicy, horizontalScrollBarPolicy
Definition at line 794 of file qabstractscrollarea.cpp.
Referenced by QColumnViewPrivate::createColumn(), and QColumnView::setResizeGripsVisible().
 {
     Q_D(QAbstractScrollArea);
     QWidget* oldWidget = d->cornerWidget;
     if (oldWidget != widget) {
         if (oldWidget)
             oldWidget->hide();
         d->cornerWidget = widget;
         if (widget && widget->parentWidget() != this)
             widget->setParent(this);
         d->layoutChildren();
         if (widget)
             widget->show();
     } else {
         d->cornerWidget = widget;
         d->layoutChildren();
     }
 }
setHorizontalScrollBar()
void QAbstractScrollArea::setHorizontalScrollBar (QScrollBar * scrollBar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
Since
4.2
The former scroll bar is then deleted.
QAbstractScrollArea already provides horizontal and vertical scroll bars by default. You can call this function to replace the default horizontal scroll bar with your own custom scroll bar.
See also
horizontalScrollBar(), setVerticalScrollBar()
Definition at line 738 of file qabstractscrollarea.cpp.
 {
     Q_D(QAbstractScrollArea);
     if (!scrollBar) {
         qWarning("QAbstractScrollArea::setHorizontalScrollBar: Cannot set a null scroll bar");
         return;
     }
     d->replaceScrollBar(scrollBar, Qt::Horizontal);
 }
setHorizontalScrollBarPolicy()
void QAbstractScrollArea::setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy policy)
Definition at line 700 of file qabstractscrollarea.cpp.
Referenced by QHeaderView::initialize(), QColumnView::initializeColumn(), QCompleter::popup(), QCalendarView::QCalendarView(), QMdiArea::QMdiArea(), and QComboBoxPrivateContainer::setItemView().
 {
     Q_D(QAbstractScrollArea);
     const Qt::ScrollBarPolicy oldPolicy = d->hbarpolicy;
     d->hbarpolicy = policy;
     if (isVisible())
         d->layoutChildren();
     if (oldPolicy != d->hbarpolicy)
         d->scrollBarPolicyChanged(Qt::Horizontal, d->hbarpolicy);
 }
setupViewport
void QAbstractScrollArea::setupViewport (QWidget * viewport) protected slot
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Reimplement this function in a subclass of QAbstractScrollArea to initialize the new viewport before it is used.
See also
setViewport()
Definition at line 1435 of file qabstractscrollarea.cpp.
 {
     Q_UNUSED(viewport);
 }
setVerticalScrollBar()
void QAbstractScrollArea::setVerticalScrollBar (QScrollBar * scrollBar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
Since
4.2 The former scroll bar is then deleted.
QAbstractScrollArea already provides vertical and horizontal scroll bars by default. You can call this function to replace the default vertical scroll bar with your own custom scroll bar.
See also
verticalScrollBar(), setHorizontalScrollBar()
Definition at line 671 of file qabstractscrollarea.cpp.
 {
     Q_D(QAbstractScrollArea);
     if (!scrollBar) {
         qWarning("QAbstractScrollArea::setVerticalScrollBar: Cannot set a null scroll bar");
         return;
     }
     d->replaceScrollBar(scrollBar, Qt::Vertical);
 }
setVerticalScrollBarPolicy()
void QAbstractScrollArea::setVerticalScrollBarPolicy (Qt::ScrollBarPolicy policy)
Definition at line 633 of file qabstractscrollarea.cpp.
Referenced by QHeaderView::initialize(), QColumnView::initializeColumn(), QCalendarView::QCalendarView(), QMdiArea::QMdiArea(), QComboBox::setEditable(), and QComboBoxPrivateContainer::setItemView().
 {
     Q_D(QAbstractScrollArea);
     const Qt::ScrollBarPolicy oldPolicy = d->vbarpolicy;
     d->vbarpolicy = policy;
     if (isVisible())
         d->layoutChildren();
     if (oldPolicy != d->vbarpolicy)
         d->scrollBarPolicyChanged(Qt::Vertical, d->vbarpolicy);
 }
setViewport()
void QAbstractScrollArea::setViewport (QWidget * widget)
Sets the viewport to be the given widget.
Since
4.2
The QAbstractScrollArea will take ownership of the given widget.
If widget is 0, QAbstractScrollArea will assign a new QWidget instance for the viewport.
See also
viewport()
Definition at line 556 of file qabstractscrollarea.cpp.
Referenced by QGraphicsView::QGraphicsView(), and QMdiArea::QMdiArea().
 {
     Q_D(QAbstractScrollArea);
     if (widget != d->viewport) {
         QWidget *oldViewport = d->viewport;
         if (!widget)
             widget = new QWidget;
         d->viewport = widget;
         d->viewport->setParent(this);
         d->viewport->setFocusProxy(this);
         d->viewport->installEventFilter(d->viewportFilter.data());
 #ifndef Q_WS_MAC
 #ifndef QT_NO_GESTURES
         d->viewport->grabGesture(Qt::PanGesture);
 #endif
 #endif
         d->layoutChildren();
         if (isVisible())
             d->viewport->show();
         QMetaObject::invokeMethod(this, "setupViewport", Q_ARG(QWidget *, widget));
         delete oldViewport;
     }
 }
setViewportMargins() [1/2]
void QAbstractScrollArea::setViewportMargins (int left, int top, int right, int bottom) protected
Sets the margins around the scrolling area to left, top, right and bottom.
This is useful for applications such as spreadsheets with "locked" rows and columns. The marginal space is is left blank; put widgets in the unused area.
Note that this function is frequently called by QTreeView and QTableView, so margins must be implemented by QAbstractScrollArea subclasses. Also, if the subclasses are to be used in item views, they should not call this function.
By default all margins are zero.
Definition at line 910 of file qabstractscrollarea.cpp.
Referenced by setViewportMargins(), QScriptEdit::updateExtraAreaWidth(), QTableView::updateGeometries(), and QTreeView::updateGeometries().
 {
     Q_D(QAbstractScrollArea);
     d->left = left;
     d->top = top;
     d->right = right;
     d->bottom = bottom;
     d->layoutChildren();
 }
setViewportMargins() [2/2]
void QAbstractScrollArea::setViewportMargins (const QMargins & margins) protected
Sets margins around the scrolling area.
Since
4.6 This is useful for applications such as spreadsheets with "locked" rows and columns. The marginal space is is left blank; put widgets in the unused area.
By default all margins are zero.
Definition at line 933 of file qabstractscrollarea.cpp.
 {
     setViewportMargins(margins.left(), margins.top(),
                        margins.right(), margins.bottom());
 }
sizeHint()
QSize QAbstractScrollArea::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QMdiArea, and QScrollArea.
Definition at line 1416 of file qabstractscrollarea.cpp.
Referenced by QColumnViewPrivate::createColumn(), QColumnView::sizeHint(), QGraphicsView::sizeHint(), QSidebar::sizeHint(), QFileDialogListView::sizeHint(), QTableView::sizeHintForColumn(), and QTableView::sizeHintForRow().
 {
     return QSize(256, 192);
 #if 0
     Q_D(const QAbstractScrollArea);
     int h = qMax(10, fontMetrics().height());
     int f = 2 * d->frameWidth;
     return QSize((6 * h) + f, (4 * h) + f);
 #endif
 }
verticalScrollBar()
QScrollBar * QAbstractScrollArea::verticalScrollBar () const
Returns the vertical scroll bar.
See also
verticalScrollBarPolicy, horizontalScrollBar()
Definition at line 650 of file qabstractscrollarea.cpp.
Referenced by QAccessibleAbstractScrollArea::accessibleChildren(), QGraphicsView::centerOn(), QAbstractItemView::doAutoScroll(), QTableView::doItemsLayout(), QGraphicsView::ensureVisible(), event(), QPlainTextEdit::event(), QGraphicsView::mouseMoveEvent(), QAccessibleAbstractScrollArea::navigate(), QPlainTextEdit::paintEvent(), QAccessibleTextEdit::rect(), QAccessibleItemView::rect(), QColumnViewPreviewColumn::resizeEvent(), QTableView::scrollContentsBy(), QTreeView::scrollContentsBy(), QComboBoxPrivateContainer::scrollItemView(), QTableView::scrollTo(), QListView::scrollTo(), QTreeView::scrollTo(), QAbstractItemView::scrollToBottom(), QAccessibleTextEdit::scrollToSubstring(), QAbstractItemView::scrollToTop(), QComboBoxPrivateContainer::setItemView(), QMdiSubWindowPrivate::setMaximizeMode(), QTableView::updateGeometries(), QListView::updateGeometries(), QComboBoxPrivateContainer::updateScrollers(), QTreeView::verticalOffset(), and QAbstractItemView::verticalScrollbarValueChanged().
 {
     Q_D(const QAbstractScrollArea);
     return d->vbar;
 }
verticalScrollBarPolicy()
Qt::ScrollBarPolicy QAbstractScrollArea::verticalScrollBarPolicy () const
Referenced by maximumViewportSize(), and QListView::updateGeometries().
viewport()
QWidget * QAbstractScrollArea::viewport () const
Returns the viewport widget.
Use the QScrollArea::widget() function to retrieve the contents of the viewport widget.
See also
QScrollArea::widget()
Definition at line 588 of file qabstractscrollarea.cpp.
Referenced by QTreeViewPrivate::_q_endAnimatedOperation(), QHeaderViewPrivate::_q_layoutChanged(), QHeaderViewPrivate::_q_sectionsRemoved(), QFileDialogPrivate::_q_showContextMenu(), QAbstractScrollAreaPrivate::_q_showOrHideScrollBars(), QAccessibleAbstractScrollArea::accessibleChildren(), QMdiArea::addSubWindow(), QGraphicsScenePrivate::addView(), QPlainTextEditPrivate::append(), QTreeViewPrivate::beginAnimatedOperation(), QPlainTextEditControl::blockBoundingRect(), QHeaderViewPrivate::cascadingResize(), QGraphicsView::centerOn(), QAccessibleTable2::childAt(), QAccessibleTextEdit::childAt(), QAccessibleTree::childAt(), QTreeView::collapse(), QTreeView::columnCountChanged(), QGraphicsView::contextMenuEvent(), QColumnView::createColumn(), QColumnViewPrivate::createColumn(), QTableView::currentChanged(), QTreeView::currentChanged(), QAbstractItemViewPrivate::draggablePaintPairs(), QListViewPrivate::draggablePaintPairs(), QGraphicsView::drawItems(), QAbstractItemViewPrivate::dropOn(), QAbstractItemViewPrivate::editor(), QGraphicsScenePrivate::enableMouseTrackingOnViews(), QGraphicsScenePrivate::enableTouchEventsOnViews(), QPlainTextEditPrivate::ensureCursorVisible(), QGraphicsView::ensureVisible(), QAbstractItemView::event(), QTreeViewPrivate::expandOrCollapseItemAtPos(), QAbstractItemViewPrivate::fetchMore(), QGraphicsView::fitInView(), QSidebar::focusInEvent(), QAbstractItemView::horizontalScrollbarValueChanged(), QListViewPrivate::horizontalScrollToValue(), QGraphicsView::invalidateScene(), QTreeView::mouseDoubleClickEvent(), QGraphicsView::mouseDoubleClickEvent(), QGraphicsView::mouseMoveEvent(), QGraphicsView::mousePressEvent(), QGraphicsView::mouseReleaseEvent(), QTreeView::moveCursor(), QAccessibleAbstractScrollArea::navigate(), QAccessibleItemRow::navigate(), QTreeViewPrivate::pageDown(), QTreeViewPrivate::pageUp(), QTextEditPrivate::paint(), QTreeViewPrivate::paintAlternatingRowColors(), QWidgetPrivate::paintBackground(), QComboBoxListView::paintEvent(), QTableView::paintEvent(), QListView::paintEvent(), QTreeView::paintEvent(), QPlainTextEdit::paintEvent(), QGraphicsView::paintEvent(), QTreeViewPrivate::prepareAnimatedOperation(), QGraphicsView::QGraphicsView(), QAccessibleItemRow::rect(), QAccessibleTextEdit::rect(), QAccessibleTable2Cell::rect(), QTextEditPrivate::relayoutDocument(), QPlainTextEditPrivate::relayoutDocument(), QGraphicsView::render(), QColumnViewPreviewColumn::resizeEvent(), QComboBoxListView::resizeEvent(), QHeaderViewPrivate::resizeSections(), QTreeView::rowsInserted(), QWidgetPrivate::screenGeometry(), scrollContentsBy(), QMdiArea::scrollContentsBy(), QGraphicsView::scrollContentsBy(), QColumnView::scrollTo(), QTableView::selectionChanged(), QTreeView::selectionChanged(), QTableViewPrivate::selectRow(), QDeclarativeTextInputPrivate::sendMouseEventToInputContext(), QGraphicsScene::setBackgroundBrush(), QGraphicsItem::setCursor(), QGraphicsView::setDragMode(), QGraphicsScene::setForegroundBrush(), QAbstractItemView::setIndexWidget(), QAbstractItemView::setItemDelegate(), QAbstractItemView::setItemDelegateForColumn(), QAbstractItemView::setItemDelegateForRow(), QComboBoxPrivateContainer::setItemView(), QMdiSubWindowPrivate::setMaximizeMode(), QHeaderView::setOffsetToLastSection(), QTableView::setRootIndex(), QHeaderViewPrivate::setupSectionIndicator(), QAbstractItemViewPrivate::shouldAutoScroll(), QMdiArea::showEvent(), QGraphicsScenePrivate::ungrabGesture(), QScriptEdit::updateExtraArea(), QListView::updateGeometries(), QGraphicsView::updateScene(), QScrollAreaPrivate::updateScrollBars(), QColumnViewPrivate::updateScrollbars(), QTreeViewPrivate::updateScrollBars(), QScrollAreaPrivate::updateWidgetPosition(), QAbstractItemView::verticalScrollbarValueChanged(), QListViewPrivate::verticalScrollToValue(), QAccessiblePlainTextEdit::viewport(), QAccessibleTextEdit::viewport(), QMdiArea::viewportEvent(), QHeaderView::viewportEvent(), QTreeView::viewportEvent(), QGraphicsView::viewportEvent(), and QGraphicsView::wheelEvent().
 {
     Q_D(const QAbstractScrollArea);
     return d->viewport;
 }
viewportEvent()
bool QAbstractScrollArea::viewportEvent (QEvent * event) protected virtual
The main event handler for the scrolling area (the viewport() widget).
It handles the event specified, and can be called by subclasses to provide reasonable default behavior.
Returns true to indicate to the event system that the event has been handled, and needs no further processing; otherwise returns false to indicate that the event should be propagated further.
You can reimplement this function in a subclass, but we recommend using one of the specialized event handlers instead.
Specialized handlers for viewport events are: paintEvent(), mousePressEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), wheelEvent(), dragEnterEvent(), dragMoveEvent(), dragLeaveEvent(), dropEvent(), contextMenuEvent(), and resizeEvent().
Reimplemented in QAbstractItemView, QGraphicsView, QTreeView, QHeaderView, and QMdiArea.
Definition at line 1065 of file qabstractscrollarea.cpp.
Referenced by QMdiArea::viewportEvent(), QGraphicsView::viewportEvent(), and QAbstractItemView::viewportEvent().
 {
     switch (e->type()) {
     case QEvent::Resize:
     case QEvent::Paint:
     case QEvent::MouseButtonPress:
     case QEvent::MouseButtonRelease:
     case QEvent::MouseButtonDblClick:
     case QEvent::TouchBegin:
     case QEvent::TouchUpdate:
     case QEvent::TouchEnd:
     case QEvent::MouseMove:
     case QEvent::ContextMenu:
 #ifndef QT_NO_WHEELEVENT
     case QEvent::Wheel:
 #endif
 #ifndef QT_NO_DRAGANDDROP
     case QEvent::Drop:
     case QEvent::DragEnter:
     case QEvent::DragMove:
     case QEvent::DragLeave:
 #endif
         return QFrame::event(e);
     case QEvent::LayoutRequest:
 #ifndef QT_NO_GESTURES
     case QEvent::Gesture:
     case QEvent::GestureOverride:
         return event(e);
 #endif
     default:
         break;
     }
     return false; // let the viewport widget handle the event
 }
wheelEvent()
void QAbstractScrollArea::wheelEvent (QWheelEvent * e) protected virtual
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
The event is passed in e.
See also
QWidget::wheelEvent()
Reimplemented from QWidget.
Reimplemented in QCalendarView, QTextEdit, and QPlainTextEdit.
Definition at line 1187 of file qabstractscrollarea.cpp.
Referenced by QPlainTextEdit::toPlainText(), QPlainTextEdit::wheelEvent(), QGraphicsView::wheelEvent(), and QTextEdit::wheelEvent().
 {
     Q_D(QAbstractScrollArea);
     if (static_cast<QWheelEvent*>(e)->orientation() == Qt::Horizontal)
         QApplication::sendEvent(d->hbar, e);
     else
         QApplication::sendEvent(d->vbar, e);
 }
Friends and Related Functions
QStyleSheetStyle
friend class QStyleSheetStyle friend
Definition at line 134 of file qabstractscrollarea.h.
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 135 of file qabstractscrollarea.h.
Properties
horizontalScrollBarPolicy
Qt::ScrollBarPolicy QAbstractScrollArea::horizontalScrollBarPolicy private
the policy for the horizontal scroll bar
The default policy is Qt::ScrollBarAsNeeded.
See also
verticalScrollBarPolicy
Definition at line 63 of file qabstractscrollarea.h.
Referenced by QSizeGrip::mousePressEvent().
verticalScrollBarPolicy
Qt::ScrollBarPolicy QAbstractScrollArea::verticalScrollBarPolicy private
the policy for the vertical scroll bar
The default policy is Qt::ScrollBarAsNeeded.
See also
horizontalScrollBarPolicy
Definition at line 62 of file qabstractscrollarea.h.
Referenced by QSizeGrip::mousePressEvent().
The documentation for this class was generated from the following files:
/src/gui/widgets/qabstractscrollarea.h
/src/gui/widgets/qabstractscrollarea.cpp