Qt 4.8: QDeclarativeEngineDebugService Class Reference
QDeclarativeEngineDebugService Class Reference
#include <qdeclarativeenginedebugservice_p.h>
Classes
struct QDeclarativeObjectData
struct QDeclarativeObjectProperty
Public Functions
void addEngine (QDeclarativeEngine *)
void objectCreated (QDeclarativeEngine *, QObject *)
QDeclarativeEngineDebugService (QObject *=0)
void remEngine (QDeclarativeEngine *)
Public Functions inherited from QDeclarativeDebugService
QString name () const
QDeclarativeDebugService (const QString &, QObject *parent=0)
void sendMessage (const QByteArray &)
Status status () const
bool waitForMessage ()
~QDeclarativeDebugService ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QDeclarativeEngineDebugService * instance ()
Static Public Functions inherited from QDeclarativeDebugService
static bool hasDebuggingClient ()
static int idForObject (QObject *)
Returns a unique id for object.
static bool isDebuggingEnabled ()
static QObject * objectForId (int)
Returns the object for unique id.
static QString objectToString (QObject *obj)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
virtual void messageReceived (const QByteArray &)
Protected Functions inherited from QDeclarativeDebugService
virtual void statusChanged (Status)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void propertyChanged (int id, int objectId, const QMetaProperty &property, const QVariant &value)
Private Functions
void buildObjectDump (QDataStream &, QObject *, bool, bool)
void buildObjectList (QDataStream &, QDeclarativeContext *)
void buildStatesList (QDeclarativeContext *, bool)
void buildStatesList (QObject *obj)
QDeclarativeObjectData objectData (QObject *)
void prepareDeferredObjects (QObject *)
QDeclarativeObjectProperty propertyData (QObject *, int)
void resetBinding (int objectId, const QString &propertyName)
void setBinding (int objectId, const QString &propertyName, const QVariant &expression, bool isLiteralValue, QString filename=QString(), int line=-1)
void setMethodBody (int objectId, const QString &method, const QString &body)
QVariant valueContents (const QVariant &defaultValue) const
Properties
QList< QWeakPointer< QDeclarativeState > > m_allStates
QList< QDeclarativeEngine * > m_engines
QDeclarativeWatcher * m_watch
Additional Inherited Members
Public Types inherited from QDeclarativeDebugService
enum Status { NotConnected, Unavailable, Enabled }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 70 of file qdeclarativeenginedebugservice_p.h.
Constructors and Destructors
QDeclarativeEngineDebugService()
QDeclarativeEngineDebugService::QDeclarativeEngineDebugService (QObject * parent = 0)
Definition at line 69 of file qdeclarativeenginedebugservice.cpp.
 : QDeclarativeDebugService(QLatin1String("DeclarativeDebugger"), parent),
     m_watch(new QDeclarativeWatcher(this))
 {
     QObject::connect(m_watch, SIGNAL(propertyChanged(int,int,QMetaProperty,QVariant)),
                      this, SLOT(propertyChanged(int,int,QMetaProperty,QVariant)));
 }
Functions
addEngine()
void QDeclarativeEngineDebugService::addEngine (QDeclarativeEngine * engine)
Definition at line 718 of file qdeclarativeenginedebugservice.cpp.
Referenced by QDeclarativeEnginePrivate::init().
 {
     Q_ASSERT(engine);
     Q_ASSERT(!m_engines.contains(engine));
     m_engines.append(engine);
 }
buildObjectDump()
void QDeclarativeEngineDebugService::buildObjectDump (QDataStream & message, QObject * object, bool recur, bool dumpProperties) private
Definition at line 210 of file qdeclarativeenginedebugservice.cpp.
Referenced by messageReceived().
 {
     message << objectData(object);
     QObjectList children = object->children();
     int childrenCount = children.count();
     for (int ii = 0; ii < children.count(); ++ii) {
         if (qobject_cast<QDeclarativeContext*>(children[ii]) || QDeclarativeBoundSignal::cast(children[ii]))
             --childrenCount;
     }
     message << childrenCount << recur;
     QList<QDeclarativeObjectProperty> fakeProperties;
     for (int ii = 0; ii < children.count(); ++ii) {
         QObject *child = children.at(ii);
         if (qobject_cast<QDeclarativeContext*>(child))
             continue;
         if (!QDeclarativeBoundSignal::cast(child)) {
             if (recur)
                 buildObjectDump(message, child, recur, dumpProperties);
             else
                 message << objectData(child);
         }
     }
     if (!dumpProperties) {
         message << 0;
         return;
     }
     QList<int> propertyIndexes;
     for (int ii = 0; ii < object->metaObject()->propertyCount(); ++ii) {
         if (object->metaObject()->property(ii).isScriptable())
             propertyIndexes << ii;
     }
     for (int ii = 0; ii < children.count(); ++ii) {
         QObject *child = children.at(ii);
         if (qobject_cast<QDeclarativeContext*>(child))
             continue;
         QDeclarativeBoundSignal *signal = QDeclarativeBoundSignal::cast(child);
         if (signal) {
             QDeclarativeObjectProperty prop;
             prop.type = QDeclarativeObjectProperty::SignalProperty;
             prop.hasNotifySignal = false;
             QDeclarativeExpression *expr = signal->expression();
             if (expr) {
                 prop.value = expr->expression();
                 QObject *scope = expr->scopeObject();
                 if (scope) {
                     QString sig = QLatin1String(scope->metaObject()->method(signal->index()).signature());
                     int lparen = sig.indexOf(QLatin1Char('('));
                     if (lparen >= 0) {
                         QString methodName = sig.mid(0, lparen);
                         prop.name = QLatin1String("on") + methodName[0].toUpper()
                                 + methodName.mid(1);
                     }
                 }
             }
             fakeProperties << prop;
         }
     }
     message << propertyIndexes.size() + fakeProperties.count();
     for (int ii = 0; ii < propertyIndexes.size(); ++ii)
         message << propertyData(object, propertyIndexes.at(ii));
     for (int ii = 0; ii < fakeProperties.count(); ++ii)
         message << fakeProperties[ii];
 }
buildObjectList()
void QDeclarativeEngineDebugService::buildObjectList (QDataStream & message, QDeclarativeContext * ctxt) private
Definition at line 298 of file qdeclarativeenginedebugservice.cpp.
Referenced by messageReceived().
 {
     QDeclarativeContextData *p = QDeclarativeContextData::get(ctxt);
     QString ctxtName = ctxt->objectName();
     int ctxtId = QDeclarativeDebugService::idForObject(ctxt);
     message << ctxtName << ctxtId;
     int count = 0;
     QDeclarativeContextData *child = p->childContexts;
     while (child) {
         ++count;
         child = child->nextChild;
     }
     message << count;
     child = p->childContexts;
     while (child) {
         buildObjectList(message, child->asQDeclarativeContext());
         child = child->nextChild;
     }
     // Clean deleted objects
     QDeclarativeContextPrivate *ctxtPriv = QDeclarativeContextPrivate::get(ctxt);
     for (int ii = 0; ii < ctxtPriv->instances.count(); ++ii) {
         if (!ctxtPriv->instances.at(ii)) {
             ctxtPriv->instances.removeAt(ii);
             --ii;
         }
     }
     message << ctxtPriv->instances.count();
     for (int ii = 0; ii < ctxtPriv->instances.count(); ++ii) {
         message << objectData(ctxtPriv->instances.at(ii));
     }
 }
buildStatesList() [1/2]
void QDeclarativeEngineDebugService::buildStatesList (QDeclarativeContext * ctxt, bool cleanList = false) private
Definition at line 338 of file qdeclarativeenginedebugservice.cpp.
Referenced by buildStatesList(), and messageReceived().
 {
     if (cleanList)
         m_allStates.clear();
     QDeclarativeContextPrivate *ctxtPriv = QDeclarativeContextPrivate::get(ctxt);
     for (int ii = 0; ii < ctxtPriv->instances.count(); ++ii) {
         buildStatesList(ctxtPriv->instances.at(ii));
     }
     QDeclarativeContextData *child = QDeclarativeContextData::get(ctxt)->childContexts;
     while (child) {
         buildStatesList(child->asQDeclarativeContext());
         child = child->nextChild;
     }
 }
buildStatesList() [2/2]
void QDeclarativeEngineDebugService::buildStatesList (QObject * obj) private
Definition at line 355 of file qdeclarativeenginedebugservice.cpp.
 {
     if (QDeclarativeState *state = qobject_cast<QDeclarativeState *>(obj)) {
             m_allStates.append(state);
     }
     QObjectList children = obj->children();
     for (int ii = 0; ii < children.count(); ++ii) {
         buildStatesList(children.at(ii));
     }
 }
instance()
QDeclarativeEngineDebugService * QDeclarativeEngineDebugService::instance () static
Definition at line 64 of file qdeclarativeenginedebugservice.cpp.
Referenced by QDeclarativeComponentPrivate::begin(), QDeclarativeEnginePrivate::init(), and QDeclarativeEngine::~QDeclarativeEngine().
 {
     return qmlEngineDebugService();
 }
messageReceived()
void QDeclarativeEngineDebugService::messageReceived (const QByteArray & message) protected virtual
Reimplemented from QDeclarativeDebugService.
Definition at line 408 of file qdeclarativeenginedebugservice.cpp.
 {
     QDataStream ds(message);
     int queryId;
     QByteArray type;
     ds >> type >> queryId;
     QByteArray reply;
     QDataStream rs(&reply, QIODevice::WriteOnly);
     if (type == "LIST_ENGINES") {
         rs << QByteArray("LIST_ENGINES_R");
         rs << queryId << m_engines.count();
         for (int ii = 0; ii < m_engines.count(); ++ii) {
             QDeclarativeEngine *engine = m_engines.at(ii);
             QString engineName = engine->objectName();
             int engineId = QDeclarativeDebugService::idForObject(engine);
             rs << engineName << engineId;
         }
     } else if (type == "LIST_OBJECTS") {
         int engineId = -1;
         ds >> engineId;
         QDeclarativeEngine *engine =
             qobject_cast<QDeclarativeEngine *>(QDeclarativeDebugService::objectForId(engineId));
         rs << QByteArray("LIST_OBJECTS_R") << queryId;
         if (engine) {
             buildObjectList(rs, engine->rootContext());
             buildStatesList(engine->rootContext(), true);
         }
     } else if (type == "FETCH_OBJECT") {
         int objectId;
         bool recurse;
         bool dumpProperties = true;
         ds >> objectId >> recurse >> dumpProperties;
         QObject *object = QDeclarativeDebugService::objectForId(objectId);
         rs << QByteArray("FETCH_OBJECT_R") << queryId;
         if (object) {
             if (recurse)
                 prepareDeferredObjects(object);
             buildObjectDump(rs, object, recurse, dumpProperties);
         }
     } else if (type == "WATCH_OBJECT") {
         int objectId;
         ds >> objectId;
         bool ok = m_watch->addWatch(queryId, objectId);
         rs << QByteArray("WATCH_OBJECT_R") << queryId << ok;
     } else if (type == "WATCH_PROPERTY") {
         int objectId;
         QByteArray property;
         ds >> objectId >> property;
         bool ok = m_watch->addWatch(queryId, objectId, property);
         rs << QByteArray("WATCH_PROPERTY_R") << queryId << ok;
     } else if (type == "WATCH_EXPR_OBJECT") {
         int debugId;
         QString expr;
         ds >> debugId >> expr;
         bool ok = m_watch->addWatch(queryId, debugId, expr);
         rs << QByteArray("WATCH_EXPR_OBJECT_R") << queryId << ok;
     } else if (type == "NO_WATCH") {
         m_watch->removeWatch(queryId);
     } else if (type == "EVAL_EXPRESSION") {
         int objectId;
         QString expr;
         ds >> objectId >> expr;
         QObject *object = QDeclarativeDebugService::objectForId(objectId);
         QDeclarativeContext *context = qmlContext(object);
         QVariant result;
         if (object && context) {
             QDeclarativeExpression exprObj(context, object, expr);
             bool undefined = false;
             QVariant value = exprObj.evaluate(&undefined);
             if (undefined)
                 result = QLatin1String("<undefined>");
             else
                 result = valueContents(value);
         } else {
             result = QLatin1String("<unknown context>");
         }
         rs << QByteArray("EVAL_EXPRESSION_R") << queryId << result;
     } else if (type == "SET_BINDING") {
         int objectId;
         QString propertyName;
         QVariant expr;
         bool isLiteralValue;
         QString filename;
         int line;
         ds >> objectId >> propertyName >> expr >> isLiteralValue;
         if (!ds.atEnd()) { // backward compatibility from 2.1, 2.2
             ds >> filename >> line;
         }
         setBinding(objectId, propertyName, expr, isLiteralValue, filename, line);
         rs << QByteArray("SET_BINDING_R") << queryId;
     } else if (type == "RESET_BINDING") {
         int objectId;
         QString propertyName;
         ds >> objectId >> propertyName;
         resetBinding(objectId, propertyName);
         rs << QByteArray("SET_BINDING_R") << queryId;
     } else if (type == "SET_METHOD_BODY") {
         int objectId;
         QString methodName;
         QString methodBody;
         ds >> objectId >> methodName >> methodBody;
         setMethodBody(objectId, methodName, methodBody);
         rs << QByteArray("SET_BINDING_R") << queryId;
     }
     sendMessage(reply);
 }
objectCreated()
void QDeclarativeEngineDebugService::objectCreated (QDeclarativeEngine * engine, QObject * object)
Definition at line 734 of file qdeclarativeenginedebugservice.cpp.
Referenced by QDeclarativeComponentPrivate::begin().
 {
     Q_ASSERT(engine);
     Q_ASSERT(m_engines.contains(engine));
     int engineId = QDeclarativeDebugService::idForObject(engine);
     int objectId = QDeclarativeDebugService::idForObject(object);
     int parentId = QDeclarativeDebugService::idForObject(object->parent());
     QByteArray reply;
     QDataStream rs(&reply, QIODevice::WriteOnly);
     rs << QByteArray("OBJECT_CREATED") << -1 << engineId << objectId << parentId;
     sendMessage(reply);
 }
objectData()
QDeclarativeEngineDebugService::QDeclarativeObjectData QDeclarativeEngineDebugService::objectData (QObject * object) private
Definition at line 368 of file qdeclarativeenginedebugservice.cpp.
Referenced by buildObjectDump(), and buildObjectList().
 {
     QDeclarativeData *ddata = QDeclarativeData::get(object);
     QDeclarativeObjectData rv;
     if (ddata && ddata->outerContext) {
         rv.url = ddata->outerContext->url;
         rv.lineNumber = ddata->lineNumber;
         rv.columnNumber = ddata->columnNumber;
     } else {
         rv.lineNumber = -1;
         rv.columnNumber = -1;
     }
     QDeclarativeContext *context = qmlContext(object);
     if (context) {
         QDeclarativeContextData *cdata = QDeclarativeContextData::get(context);
         if (cdata)
             rv.idString = cdata->findObjectId(object);
     }
     rv.objectName = object->objectName();
     rv.objectId = QDeclarativeDebugService::idForObject(object);
     rv.contextId = QDeclarativeDebugService::idForObject(qmlContext(object));
     rv.parentId = QDeclarativeDebugService::idForObject(object->parent());
     QDeclarativeType *type = QDeclarativeMetaType::qmlType(object->metaObject());
     if (type) {
         QString typeName = QLatin1String(type->qmlTypeName());
         int lastSlash = typeName.lastIndexOf(QLatin1Char('/'));
         rv.objectType = lastSlash < 0 ? typeName : typeName.mid(lastSlash+1);
     } else {
         rv.objectType = QString::fromUtf8(object->metaObject()->className());
         int marker = rv.objectType.indexOf(QLatin1String("_QMLTYPE_"));
         if (marker != -1)
             rv.objectType = rv.objectType.left(marker);
     }
     return rv;
 }
prepareDeferredObjects()
void QDeclarativeEngineDebugService::prepareDeferredObjects (QObject * obj) private
Definition at line 286 of file qdeclarativeenginedebugservice.cpp.
Referenced by messageReceived().
 {
     qmlExecuteDeferred(obj);
     QObjectList children = obj->children();
     for (int ii = 0; ii < children.count(); ++ii) {
         QObject *child = children.at(ii);
         prepareDeferredObjects(child);
     }
 }
propertyChanged
void QDeclarativeEngineDebugService::propertyChanged (int id, int objectId, const QMetaProperty & property, const QVariant & value) private slot
Definition at line 708 of file qdeclarativeenginedebugservice.cpp.
Referenced by QDeclarativeEngineDebugService().
 {
     QByteArray reply;
     QDataStream rs(&reply, QIODevice::WriteOnly);
     rs << QByteArray("UPDATE_WATCH") << id << objectId << QByteArray(property.name()) << valueContents(value);
     sendMessage(reply);
 }
propertyData()
QDeclarativeEngineDebugService::QDeclarativeObjectProperty QDeclarativeEngineDebugService::propertyData (QObject * obj, int propIdx) private
Definition at line 137 of file qdeclarativeenginedebugservice.cpp.
Referenced by buildObjectDump().
 {
     QDeclarativeObjectProperty rv;
     QMetaProperty prop = obj->metaObject()->property(propIdx);
     rv.type = QDeclarativeObjectProperty::Unknown;
     rv.valueTypeName = QString::fromUtf8(prop.typeName());
     rv.name = QString::fromUtf8(prop.name());
     rv.hasNotifySignal = prop.hasNotifySignal();
     QDeclarativeAbstractBinding *binding =
         QDeclarativePropertyPrivate::binding(QDeclarativeProperty(obj, rv.name));
     if (binding)
         rv.binding = binding->expression();
     if (QDeclarativeValueTypeFactory::isValueType(prop.userType())) {
         rv.type = QDeclarativeObjectProperty::Basic;
     } else if (QDeclarativeMetaType::isQObject(prop.userType()))  {
         rv.type = QDeclarativeObjectProperty::Object;
     } else if (QDeclarativeMetaType::isList(prop.userType())) {
         rv.type = QDeclarativeObjectProperty::List;
     } else if (prop.userType() == QMetaType::QVariant) {
         rv.type = QDeclarativeObjectProperty::Variant;
     }
     QVariant value;
     if (rv.type != QDeclarativeObjectProperty::Unknown && prop.userType() != 0) {
         value = prop.read(obj);
     }
     rv.value = valueContents(value);
     return rv;
 }
remEngine()
void QDeclarativeEngineDebugService::remEngine (QDeclarativeEngine * engine)
Definition at line 726 of file qdeclarativeenginedebugservice.cpp.
Referenced by QDeclarativeEngine::~QDeclarativeEngine().
 {
     Q_ASSERT(engine);
     Q_ASSERT(m_engines.contains(engine));
     m_engines.removeAll(engine);
 }
resetBinding()
void QDeclarativeEngineDebugService::resetBinding (int objectId, const QString & propertyName) private
Definition at line 624 of file qdeclarativeenginedebugservice.cpp.
Referenced by messageReceived().
 {
     QObject *object = objectForId(objectId);
     QDeclarativeContext *context = qmlContext(object);
     if (object && context) {
         if (object->property(propertyName.toLatin1()).isValid()) {
             QDeclarativeProperty property(object, propertyName);
             QDeclarativeAbstractBinding *oldBinding = QDeclarativePropertyPrivate::binding(property);
             if (oldBinding) {
                 QDeclarativeAbstractBinding *oldBinding = QDeclarativePropertyPrivate::setBinding(property, 0);
                 if (oldBinding)
                     oldBinding->destroy();
             }
             if (property.isResettable()) {
                 // Note: this will reset the property in any case, without regard to states
                 // Right now almost no QDeclarativeItem has reset methods for its properties (with the
                 // notable exception of QDeclarativeAnchors), so this is not a big issue
                 // later on, setBinding does take states into account
                 property.reset();
             } else {
                 // overwrite with default value
                 if (QDeclarativeType *objType = QDeclarativeMetaType::qmlType(object->metaObject())) {
                     if (QObject *emptyObject = objType->create()) {
                         if (emptyObject->property(propertyName.toLatin1()).isValid()) {
                             QVariant defaultValue = QDeclarativeProperty(emptyObject, propertyName).read();
                             if (defaultValue.isValid()) {
                                 setBinding(objectId, propertyName, defaultValue, true);
                             }
                         }
                         delete emptyObject;
                     }
                 }
             }
         } else if (hasValidSignal(object, propertyName)) {
             QDeclarativeProperty property(object, propertyName, context);
             QDeclarativePropertyPrivate::setSignalExpression(property, 0);
     } else {
             if (QDeclarativePropertyChanges *propertyChanges = qobject_cast<QDeclarativePropertyChanges *>(object)) {
                 propertyChanges->removeProperty(propertyName);
             }
         }
     }
 }
setBinding()
void QDeclarativeEngineDebugService::setBinding (int objectId, const QString & propertyName, const QVariant & expression, bool isLiteralValue, QString filename = QString(), int line = -1) private
Definition at line 550 of file qdeclarativeenginedebugservice.cpp.
Referenced by messageReceived(), and resetBinding().
 {
     QObject *object = objectForId(objectId);
     QDeclarativeContext *context = qmlContext(object);
     if (object && context) {
         QDeclarativeProperty property(object, propertyName, context);
         if (property.isValid()) {
             bool inBaseState = true;
             foreach(QWeakPointer<QDeclarativeState> statePointer, m_allStates) {
                 if (QDeclarativeState *state = statePointer.data()) {
                     // here we assume that the revert list on itself defines the base state
                     if (state->isStateActive() && state->containsPropertyInRevertList(object, propertyName)) {
                         inBaseState = false;
                         QDeclarativeBinding *newBinding = 0;
                         if (!isLiteralValue) {
                             newBinding = new QDeclarativeBinding(expression.toString(), object, context);
                             newBinding->setTarget(property);
                             newBinding->setNotifyOnValueChanged(true);
                             newBinding->setSourceLocation(filename, line);
                         }
                         state->changeBindingInRevertList(object, propertyName, newBinding);
                         if (isLiteralValue)
                             state->changeValueInRevertList(object, propertyName, expression);
                     }
                 }
             }
             if (inBaseState) {
                 if (isLiteralValue) {
                     property.write(expression);
                 } else if (hasValidSignal(object, propertyName)) {
                     QDeclarativeExpression *declarativeExpression = new QDeclarativeExpression(context, object, expression.toString());
                     QDeclarativePropertyPrivate::setSignalExpression(property, declarativeExpression);
                     declarativeExpression->setSourceLocation(filename, line);
                 } else if (property.isProperty()) {
                     QDeclarativeBinding *binding = new QDeclarativeBinding(expression.toString(), object, context);
                     binding->setTarget(property);
                     binding->setSourceLocation(filename, line);
                     binding->setNotifyOnValueChanged(true);
                     QDeclarativeAbstractBinding *oldBinding = QDeclarativePropertyPrivate::setBinding(property, binding);
                     if (oldBinding)
                         oldBinding->destroy();
                     binding->update();
                 } else {
                     qWarning() << "QDeclarativeEngineDebugService::setBinding: unable to set property" << propertyName << "on object" << object;
                 }
             }
         } else {
             // not a valid property
             if (QDeclarativePropertyChanges *propertyChanges = qobject_cast<QDeclarativePropertyChanges *>(object)) {
                 if (isLiteralValue) {
                     propertyChanges->changeValue(propertyName, expression);
                 } else {
                     propertyChanges->changeExpression(propertyName, expression.toString());
                 }
             } else {
                 qWarning() << "QDeclarativeEngineDebugService::setBinding: unable to set property" << propertyName << "on object" << object;
             }
         }
     }
 }
setMethodBody()
void QDeclarativeEngineDebugService::setMethodBody (int objectId, const QString & method, const QString & body) private
Definition at line 669 of file qdeclarativeenginedebugservice.cpp.
Referenced by messageReceived().
 {
     QObject *object = objectForId(objectId);
     QDeclarativeContext *context = qmlContext(object);
     if (!object || !context || !context->engine())
         return;
     QDeclarativeContextData *contextData = QDeclarativeContextData::get(context);
     if (!contextData)
         return;
     QDeclarativePropertyCache::Data dummy;
     QDeclarativePropertyCache::Data *prop =
         QDeclarativePropertyCache::property(context->engine(), object, method, dummy);
     if (!prop || !(prop->flags & QDeclarativePropertyCache::Data::IsVMEFunction))
         return;
     QMetaMethod metaMethod = object->metaObject()->method(prop->coreIndex);
     QList<QByteArray> paramNames = metaMethod.parameterNames();
     QString paramStr;
     for (int ii = 0; ii < paramNames.count(); ++ii) {
         if (ii != 0) paramStr.append(QLatin1String(","));
         paramStr.append(QString::fromUtf8(paramNames.at(ii)));
     }
     QString jsfunction = QLatin1String("(function ") + method + QLatin1String("(") + paramStr +
                          QLatin1String(") {");
     jsfunction += body;
     jsfunction += QLatin1String("\n})");
     QDeclarativeVMEMetaObject *vmeMetaObject =
         static_cast<QDeclarativeVMEMetaObject*>(QObjectPrivate::get(object)->metaObject);
     Q_ASSERT(vmeMetaObject); // the fact we found the property above should guarentee this
     int lineNumber = vmeMetaObject->vmeMethodLineNumber(prop->coreIndex);
     vmeMetaObject->setVmeMethod(prop->coreIndex, QDeclarativeExpressionPrivate::evalInObjectScope(contextData, object, jsfunction, contextData->url.toString(), lineNumber, 0));
 }
valueContents()
QVariant QDeclarativeEngineDebugService::valueContents (const QVariant & defaultValue) const private
Definition at line 171 of file qdeclarativeenginedebugservice.cpp.
Referenced by messageReceived(), propertyChanged(), and propertyData().
 {
     int userType = value.userType();
     if (value.type() == QVariant::List) {
         QVariantList contents;
         QVariantList list = value.toList();
         int count = list.size();
         for (int i = 0; i < count; i++)
             contents << valueContents(list.at(i));
         return contents;
     }
     if (value.type() == QVariant::Map) {
         QVariantMap contents;
         QMapIterator<QString, QVariant> i(value.toMap());
          while (i.hasNext()) {
              i.next();
              contents.insert(i.key(), valueContents(i.value()));
          }
         return contents;
     }
     if (QDeclarativeValueTypeFactory::isValueType(userType))
         return value;
     if (QDeclarativeMetaType::isQObject(userType)) {
         QObject *o = QDeclarativeMetaType::toQObject(value);
         if (o) {
             QString name = o->objectName();
             if (name.isEmpty())
                 name = QLatin1String("<unnamed object>");
             return name;
         }
     }
     return QLatin1String("<unknown value>");
 }
Properties
m_allStates
QList<QWeakPointer<QDeclarativeState> > QDeclarativeEngineDebugService::m_allStates private
Definition at line 125 of file qdeclarativeenginedebugservice_p.h.
Referenced by buildStatesList(), and setBinding().
m_engines
QList<QDeclarativeEngine *> QDeclarativeEngineDebugService::m_engines private
Definition at line 123 of file qdeclarativeenginedebugservice_p.h.
Referenced by addEngine(), messageReceived(), objectCreated(), and remEngine().
m_watch
QDeclarativeWatcher* QDeclarativeEngineDebugService::m_watch private
Definition at line 124 of file qdeclarativeenginedebugservice_p.h.
Referenced by messageReceived(), and QDeclarativeEngineDebugService().
The documentation for this class was generated from the following files:
/src/declarative/debugger/qdeclarativeenginedebugservice_p.h
/src/declarative/debugger/qdeclarativeenginedebugservice.cpp