Qt 4.8: QTtfStream Class Reference
QTtfStream Class Reference
Public Functions
void align4 ()
int offset () const
QTtfStream & operator<< (quint8 v)
QTtfStream & operator<< (quint16 v)
QTtfStream & operator<< (quint32 v)
QTtfStream & operator<< (qint8 v)
QTtfStream & operator<< (qint16 v)
QTtfStream & operator<< (qint32 v)
QTtfStream & operator<< (qint64 v)
QTtfStream (QByteArray &ba)
void setOffset (int o)
Properties
uchar * data
uchar * start
Detailed Description
Definition at line 550 of file qfontsubset.cpp.
Constructors and Destructors
QTtfStream()
QTtfStream::QTtfStream (QByteArray & ba) inline
Definition at line 552 of file qfontsubset.cpp.
 : data((uchar *)ba.data()) { start = data; }
Functions
align4()
void QTtfStream::align4 () inline
Definition at line 563 of file qfontsubset.cpp.
 { while (offset() & 3) { *data = '\0'; ++data; } }
offset()
int QTtfStream::offset () const inline
Definition at line 561 of file qfontsubset.cpp.
Referenced by generateGlyphTables(), generateHead(), generateHhea(), generateMaxp(), and getGlyphData().
 { return data - start; }
operator<<() [1/7]
QTtfStream& QTtfStream::operator<< (quint8 v) inline
Definition at line 553 of file qfontsubset.cpp.
 { *data = v; ++data; return *this; }
operator<<() [2/7]
QTtfStream& QTtfStream::operator<< (quint16 v) inline
Definition at line 554 of file qfontsubset.cpp.
 { qToBigEndian(v, data); data += sizeof(v); return *this; }
operator<<() [3/7]
QTtfStream& QTtfStream::operator<< (quint32 v) inline
Definition at line 555 of file qfontsubset.cpp.
 { qToBigEndian(v, data); data += sizeof(v); return *this; }
operator<<() [4/7]
QTtfStream& QTtfStream::operator<< (qint8 v) inline
Definition at line 556 of file qfontsubset.cpp.
 { *data = quint8(v); ++data; return *this; }
operator<<() [5/7]
QTtfStream& QTtfStream::operator<< (qint16 v) inline
Definition at line 557 of file qfontsubset.cpp.
 { qToBigEndian(v, data); data += sizeof(v); return *this; }
operator<<() [6/7]
QTtfStream& QTtfStream::operator<< (qint32 v) inline
Definition at line 558 of file qfontsubset.cpp.
 { qToBigEndian(v, data); data += sizeof(v); return *this; }
operator<<() [7/7]
QTtfStream& QTtfStream::operator<< (qint64 v) inline
Definition at line 559 of file qfontsubset.cpp.
 { qToBigEndian(v, data); data += sizeof(v); return *this; }
setOffset()
void QTtfStream::setOffset (int o) inline
Definition at line 562 of file qfontsubset.cpp.
 { data = start + o; }
Properties
data
uchar* QTtfStream::data private
Definition at line 565 of file qfontsubset.cpp.
start
uchar* QTtfStream::start private
Definition at line 566 of file qfontsubset.cpp.
The documentation for this class was generated from the following file:
/src/gui/text/qfontsubset.cpp