Qt 4.8: QPatternist::ReplaceFN Class Reference
QPatternist::ReplaceFN Class Reference
Implements the function fn:replace().
#include <qpatternmatchingfns_p.h>
Public Functions
virtual Expression::Ptr compress (const StaticContext::Ptr &context)
virtual Item evaluateSingleton (const DynamicContext::Ptr &context) const
ReplaceFN ()
Public Functions inherited from QPatternist::PatternPlatform
int captureCount () const
const QRegExp pattern (const DynamicContext::Ptr &context) const
Public Functions inherited from QPatternist::FunctionCall
virtual ExpressionVisitorResult::Ptr accept (const ExpressionVisitor::Ptr &visitor) const
virtual SequenceType::List expectedOperandTypes () const
virtual ID id () const
virtual Expression::Properties properties () const
virtual void setSignature (const FunctionSignature::Ptr &sign)
virtual FunctionSignature::Ptr signature () const
virtual SequenceType::Ptr staticType () const
virtual Expression::Ptr typeCheck (const StaticContext::Ptr &context, const SequenceType::Ptr &reqType)
Public Functions inherited from QPatternist::UnlimitedContainer
virtual bool compressOperands (const StaticContext::Ptr &)
virtual Expression::List operands () const
virtual void setOperands (const Expression::List &list)
UnlimitedContainer (const Expression::List &operands=Expression::List())
Public Functions inherited from QPatternist::Expression
virtual const SourceLocationReflection * actualReflection () const
Returns this.
virtual void announceFocusType (const ItemType::Ptr &itemType)
Properties deepProperties () const
Computes the union of properties for this Expression and all its descending children.
virtual Properties dependencies () const
virtual QString description () const
virtual bool evaluateEBV (const DynamicContext::Ptr &context) const
virtual Item::Iterator::Ptr evaluateSequence (const DynamicContext::Ptr &context) const
virtual void evaluateToSequenceReceiver (const DynamicContext::Ptr &context) const
virtual ItemType::Ptr expectedContextItemType () const
Expression ()
bool has (const Property prop) const
bool hasDependency (const Property prop) const
bool is (const ID id) const
bool isEvaluated () const
virtual ItemType::Ptr newFocusType () const
virtual QList< QExplicitlySharedDataPointer< OptimizationPass > > optimizationPasses () const
virtual PatternPriority patternPriority () const
const Expression::Ptr & rewrite (const Expression::Ptr &to, const StaticContext::Ptr &context) const
Rewrites this Expression to to, and return to.
virtual ~Expression ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< Expression >
const TCastTarget * as () const
TCastTarget * as ()
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Private Functions
QString parseReplacement (const int captureCount, const DynamicContext::Ptr &context) const
Static Private Functions
static QString errorAtEnd (const char ch)
Centralizes the translation string.
Properties
QString m_replacementString
Additional Inherited Members
Public Types inherited from QPatternist::PatternPlatform
enum Flag {
NoFlags = 0, DotAllMode = 1, MultiLineMode = 2, CaseInsensitive = 4,
SimplifyWhitespace = 8
}
typedef QFlags< Flag > Flags
Public Types inherited from QPatternist::FunctionCall
typedef QExplicitlySharedDataPointer< FunctionCall > Ptr
Public Types inherited from QPatternist::UnlimitedContainer
enum CardinalityComputation { ProductOfCardinality, UnionOfCardinality }
Public Types inherited from QPatternist::Expression
typedef QExplicitlySharedDataPointer< const Expression > ConstPtr
A smart pointer wrapping const Expression instances.
enum ID {
IDBooleanValue = 1, IDCountFN, IDEmptyFN, IDExistsFN,
IDExpressionSequence, IDGeneralComparison, IDIfThenClause, IDIgnorableExpression,
IDIntegerValue, IDPositionFN, IDStringValue, IDValueComparison,
IDRangeVariableReference, IDContextItem, IDUserFunctionCallsite, IDExpressionVariableReference,
IDAttributeConstructor, IDUpperCaseFN, IDLowerCaseFN, IDFirstItemPredicate,
IDEmptySequence, IDReturnOrderBy, IDLetClause, IDForClause,
IDPath, IDNamespaceConstructor, IDArgumentReference, IDGenericPredicate,
IDAxisStep, IDFloat, IDCombineNodes, IDUnresolvedVariableReference,
IDCardinalityVerifier
}
typedef QList< Expression::Ptr > List
typedef QFlags< Property > Properties
enum Property {
UseContextItem = 1, DisableElimination = 1 << 1, IsEvaluated = 1 << 2, DisableTypingDeduction = 1 << 3,
EmptynessFollowsChild = 1 << 4, RewriteToEmptyOnEmpty = 1 << 5, RequiresFocus = 1 << 6, AffectsOrderOnly = 1 << 7,
RequiresContextItem = (1 << 8) | RequiresFocus, CreatesFocusForLast = 1 << 9, LastOperandIsCollation = 1 << 10, DependsOnLocalVariable = (1 << 11) | DisableElimination,
EvaluationCacheRedundant = (1 << 12), IsNodeConstructor = 1 << 13, RequiresCurrentItem = 1 << 14
}
typedef QExplicitlySharedDataPointer< Expression > Ptr
A smart pointer wrapping mutable Expression instances.
typedef ::QAbstractXmlForwardIterator< Expression::Ptr > QAbstractXmlForwardIterator
typedef QVector< Expression::Ptr > Vector
Static Public Functions inherited from QPatternist::PatternPlatform
static QRegExp parsePattern (const QString &pattern, const ReportContext::Ptr &context, const SourceLocationReflection *const location)
Parses pattern.
Static Public Functions inherited from QPatternist::Expression
static void rewrite (Expression::Ptr &old, const Expression::Ptr &New, const StaticContext::Ptr &context)
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::PatternPlatform
PatternPlatform (const qint8 flagsPosition)
This constructor is protected, because this class is supposed to be sub-classed.
Protected Functions inherited from QPatternist::UnlimitedContainer
template<CardinalityComputation suppliedCard>
SequenceType::Ptr operandsUnionType () const
Protected Functions inherited from QPatternist::Expression
void typeCheckOperands (const StaticContext::Ptr &context)
Protected Functions inherited from QPatternist::CppCastingHelper< Expression >
CppCastingHelper ()
Protected Variables inherited from QPatternist::UnlimitedContainer
Expression::List m_operands
Detailed Description
Implements the function fn:replace().
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 91 of file qpatternmatchingfns_p.h.
Constructors and Destructors
ReplaceFN()
ReplaceFN::ReplaceFN ()
Definition at line 72 of file qpatternmatchingfns.cpp.
                      : PatternPlatform(3)
 {
 }
Functions
compress()
Expression::Ptr ReplaceFN::compress (const StaticContext::Ptr & context) virtual
Overridden to attempt to pre-compile the replacement string.
Reimplemented from QPatternist::PatternPlatform.
Definition at line 176 of file qpatternmatchingfns.cpp.
 {
     const Expression::Ptr me(PatternPlatform::compress(context));
     if(me != this)
         return me;
     if(m_operands.at(2)->is(IDStringValue))
     {
         const int capt = captureCount();
         if(capt == -1)
             return me;
         else
             m_replacementString = parseReplacement(captureCount(), context->dynamicContext());
     }
     return me;
 }
errorAtEnd()
QString ReplaceFN::errorAtEnd (const char ch) inline static private
Centralizes the translation string.
Definition at line 92 of file qpatternmatchingfns.cpp.
Referenced by parseReplacement().
 {
     return QtXmlPatterns::tr("%1 must be followed by %2 or %3, not at "
                              "the end of the replacement string.")
                              .arg(formatKeyword(QLatin1Char(ch)))
                              .arg(formatKeyword(QLatin1Char('\\')))
                              .arg(formatKeyword(QLatin1Char('$')));
 }
evaluateSingleton()
Item ReplaceFN::evaluateSingleton (const DynamicContext::Ptr & context) const virtual
Reimplemented from QPatternist::Expression.
Definition at line 76 of file qpatternmatchingfns.cpp.
 {
     const QRegExp regexp(pattern(context));
     QString input;
     const Item arg(m_operands.first()->evaluateSingleton(context));
     if(arg)
         input = arg.stringValue();
     const QString replacement(m_replacementString.isNull() ? parseReplacement(regexp.captureCount(), context)
                                                            : m_replacementString);
     return AtomicString::fromValue(input.replace(regexp, replacement));
 }
parseReplacement()
QString ReplaceFN::parseReplacement (const int captureCount, const DynamicContext::Ptr & context) const private
Reads the string in the third argument and converts it to a a QRegExp compatible replacement string, containing sub-group references and so forth.
Definition at line 101 of file qpatternmatchingfns.cpp.
Referenced by compress(), and evaluateSingleton().
 {
     // TODO what if there is no groups, can one rewrite to the replacement then?
     const QString input(m_operands.at(2)->evaluateSingleton(context).stringValue());
     QString retval;
     retval.reserve(input.size());
     const int len = input.length();
     for(int i = 0; i < len; ++i)
     {
         const QChar ch(input.at(i));
         switch(ch.toAscii())
         {
             case '$':
             {
                 /* QRegExp uses '\' as opposed to '$' for marking sub groups. */
                 retval.append(QLatin1Char('\\'));
                 ++i;
                 if(i == len)
                 {
                     context->error(errorAtEnd('$'), ReportContext::FORX0004, this);
                     return QString();
                 }
                 const QChar nextCh(input.at(i));
                 if(nextCh.isDigit())
                     retval.append(nextCh);
                 else
                 {
                     context->error(QtXmlPatterns::tr("In the replacement string, %1 must be "
                                                      "followed by at least one digit when not escaped.")
                                                      .arg(formatKeyword(QLatin1Char('$'))),
                                                 ReportContext::FORX0004, this);
                     return QString();
                 }
                 break;
             }
             case '\\':
             {
                 ++i;
                 if(i == len)
                 {
                     /* error, we've reached the end. */;
                     context->error(errorAtEnd('\\'), ReportContext::FORX0004, this);
                 }
                 const QChar nextCh(input.at(i));
                 if(nextCh == QLatin1Char('\\') || nextCh == QLatin1Char('$'))
                 {
                     retval.append(ch);
                     break;
                 }
                 else
                 {
                     context->error(QtXmlPatterns::tr("In the replacement string, %1 can only be used to "
                                                      "escape itself or %2, not %3")
                                                      .arg(formatKeyword(QLatin1Char('\\')))
                                                      .arg(formatKeyword(QLatin1Char('$')))
                                                      .arg(formatKeyword(nextCh)),
                                                ReportContext::FORX0004, this);
                     return QString();
                 }
             }
             default:
                 retval.append(ch);
         }
     }
     return retval;
 }
Properties
m_replacementString
QString QPatternist::ReplaceFN::m_replacementString private
Definition at line 114 of file qpatternmatchingfns_p.h.
Referenced by compress(), and evaluateSingleton().
The documentation for this class was generated from the following files:
/src/xmlpatterns/functions/qpatternmatchingfns_p.h
/src/xmlpatterns/functions/qpatternmatchingfns.cpp