Qt 4.8: QDeclarativeCustomParser Class Reference
QDeclarativeCustomParser Class Reference abstract
The QDeclarativeCustomParser class allows you to add new arbitrary types to QML.
#include <qdeclarativecustomparser_p.h>
Public Types
enum Flag { NoFlag = 0x00000000, AcceptsAttachedProperties = 0x00000001 }
Public Functions
void clearErrors ()
virtual QByteArray compile (const QList< QDeclarativeCustomParserProperty > &)=0
QList< QDeclarativeError > errors () const
Flags flags () const
QDeclarativeCustomParser ()
QDeclarativeCustomParser (Flags f)
virtual void setCustomData (QObject *, const QByteArray &)=0
virtual ~QDeclarativeCustomParser ()
Protected Functions
void error (const QString &description)
Reports an error with the given description.
void error (const QDeclarativeCustomParserProperty &, const QString &description)
Reports an error in parsing prop, with the given description.
void error (const QDeclarativeCustomParserNode &, const QString &description)
Reports an error in parsing node, with the given description.
int evaluateEnum (const QByteArray &) const
If script is a simply enum expression (eg.
const QMetaObject * resolveType (const QByteArray &) const
Resolves name to a type, or 0 if it is not a type.
QDeclarativeBinding::Identifier rewriteBinding (const QString &, const QByteArray &)
Rewrites expression and returns an identifier that can be used to construct the binding later.
Properties
QDeclarativeCompiler * compiler
QList< QDeclarativeError > exceptions
Flags m_flags
QDeclarativeParser::Object * object
Friends
class QDeclarativeCompiler
Detailed Description
The QDeclarativeCustomParser class allows you to add new arbitrary types to QML.
Warning
This function is not part of the public interface.
By subclassing QDeclarativeCustomParser, you can add a parser for building a particular type.
The subclass must implement compile() and setCustomData(), and register itself in the meta type system by calling the macro:
QML_REGISTER_CUSTOM_TYPE(Module, MajorVersion, MinorVersion, Name, TypeClass, ParserClass)
Definition at line 114 of file qdeclarativecustomparser_p.h.
Enumerations
Flag
enum QDeclarativeCustomParser::Flag
Enumerator
NoFlag
AcceptsAttachedProperties
Definition at line 117 of file qdeclarativecustomparser_p.h.
               {
         NoFlag                    = 0x00000000,
         AcceptsAttachedProperties = 0x00000001
     };
Constructors and Destructors
QDeclarativeCustomParser() [1/2]
QDeclarativeCustomParser::QDeclarativeCustomParser () inline
Definition at line 123 of file qdeclarativecustomparser_p.h.
 : compiler(0), object(0), m_flags(NoFlag) {}
QDeclarativeCustomParser() [2/2]
QDeclarativeCustomParser::QDeclarativeCustomParser (Flags f) inline
Definition at line 124 of file qdeclarativecustomparser_p.h.
 : compiler(0), object(0), m_flags(f) {}
~QDeclarativeCustomParser()
virtual QDeclarativeCustomParser::~QDeclarativeCustomParser () inline virtual
Definition at line 125 of file qdeclarativecustomparser_p.h.
 {}
Functions
clearErrors()
void QDeclarativeCustomParser::clearErrors ()
Definition at line 237 of file qdeclarativecustomparser.cpp.
Referenced by QDeclarativeCompiler::buildObject().
 {
     exceptions.clear();
 }
compile()
virtual QByteArray QDeclarativeCustomParser::compile (const QList< QDeclarativeCustomParserProperty > &) pure virtual
Implemented in QDeclarativeListModelParser, QDeclarativePropertyChangesParser, QDeclarativeConnectionsParser, and QDeclarativeGestureAreaParser.
Referenced by QDeclarativeCompiler::buildObject().
error() [1/3]
void QDeclarativeCustomParser::error (const QString & description) protected
Reports an error with the given description.
This can only be used during the compile() step. For errors during setCustomData(), use qmlInfo().
An error is generated referring to the position of the element in the source file.
Definition at line 249 of file qdeclarativecustomparser.cpp.
 {
     Q_ASSERT(object);
     QDeclarativeError error;
     QString exceptionDescription;
     error.setLine(object->location.start.line);
     error.setColumn(object->location.start.column);
     error.setDescription(description);
     exceptions << error;
 }
error() [2/3]
void QDeclarativeCustomParser::error (const QDeclarativeCustomParserProperty & prop, const QString & description) protected
Reports an error in parsing prop, with the given description.
An error is generated referring to the position of node in the source file.
Definition at line 265 of file qdeclarativecustomparser.cpp.
 {
     QDeclarativeError error;
     QString exceptionDescription;
     error.setLine(prop.location().line);
     error.setColumn(prop.location().column);
     error.setDescription(description);
     exceptions << error;
 }
error() [3/3]
void QDeclarativeCustomParser::error (const QDeclarativeCustomParserNode & node, const QString & description) protected
Reports an error in parsing node, with the given description.
An error is generated referring to the position of node in the source file.
Definition at line 280 of file qdeclarativecustomparser.cpp.
 {
     QDeclarativeError error;
     QString exceptionDescription;
     error.setLine(node.location().line);
     error.setColumn(node.location().column);
     error.setDescription(description);
     exceptions << error;
 }
errors()
QList<QDeclarativeError> QDeclarativeCustomParser::errors () const inline
Definition at line 133 of file qdeclarativecustomparser_p.h.
Referenced by QDeclarativeCompiler::buildObject().
 { return exceptions; }
evaluateEnum()
int QDeclarativeCustomParser::evaluateEnum (const QByteArray & script) const protected
If script is a simply enum expression (eg.
Text.AlignLeft), returns the integer equivalent (eg. 1).
Otherwise, returns -1.
Definition at line 296 of file qdeclarativecustomparser.cpp.
 {
     return compiler->evaluateEnum(script);
 }
flags()
Flags QDeclarativeCustomParser::flags () const inline
Definition at line 128 of file qdeclarativecustomparser_p.h.
Referenced by QDeclarativeCompiler::buildObject().
 { return m_flags; }
resolveType()
const QMetaObject * QDeclarativeCustomParser::resolveType (const QByteArray & name) const protected
Resolves name to a type, or 0 if it is not a type.
This can be used to type-check object nodes.
Definition at line 305 of file qdeclarativecustomparser.cpp.
 {
     return compiler->resolveType(name);
 }
rewriteBinding()
QDeclarativeBinding::Identifier QDeclarativeCustomParser::rewriteBinding (const QString & expression, const QByteArray & name) protected
Rewrites expression and returns an identifier that can be used to construct the binding later.
name is used as the name of the rewritten function.
Definition at line 315 of file qdeclarativecustomparser.cpp.
 {
     return compiler->rewriteBinding(expression, name);
 }
setCustomData()
virtual void QDeclarativeCustomParser::setCustomData (QObject * , const QByteArray &) pure virtual
Implemented in QDeclarativeListModelParser, QDeclarativePropertyChangesParser, QDeclarativeConnectionsParser, and QDeclarativeGestureAreaParser.
Referenced by QDeclarativeVME::run().
Friends and Related Functions
QDeclarativeCompiler
friend class QDeclarativeCompiler friend
Definition at line 151 of file qdeclarativecustomparser_p.h.
Properties
compiler
QDeclarativeCompiler* QDeclarativeCustomParser::compiler private
Definition at line 148 of file qdeclarativecustomparser_p.h.
Referenced by QDeclarativeCompiler::buildObject().
exceptions
QList<QDeclarativeError> QDeclarativeCustomParser::exceptions private
Definition at line 147 of file qdeclarativecustomparser_p.h.
m_flags
Flags QDeclarativeCustomParser::m_flags private
Definition at line 150 of file qdeclarativecustomparser_p.h.
object
QDeclarativeParser::Object* QDeclarativeCustomParser::object private
Definition at line 149 of file qdeclarativecustomparser_p.h.
Referenced by QDeclarativeCompiler::buildObject().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativecustomparser_p.h
/src/declarative/qml/qdeclarativecustomparser.cpp