Qt 4.8: QMenuBarPrivate Class Reference
QMenuBarPrivate Class Reference
#include <qmenubar_p.h>
Classes
struct QMacMenuBarPrivate
struct QWceMenuBarPrivate
Public Functions
void _q_actionHovered ()
void _q_actionTriggered ()
void _q_internalShortcutActivated (int)
void _q_updateDefaultAction ()
void _q_updateLayout ()
QAction * actionAt (QPoint p) const
QRect actionRect (QAction *) const
void activateAction (QAction *, QAction::ActionEvent)
void calcActionRects (int max_width, int start) const
void focusFirstAction ()
QAction * getNextAction (const int start, const int increment) const
void handleReparent ()
void init ()
bool isVisible (QAction *action)
void macCreateMenuBar (QWidget *)
void macDestroyMenuBar ()
OSMenuRef macMenu ()
bool macWidgetHasNativeMenubar (QWidget *widget)
QRect menuRect (bool) const
void popupAction (QAction *, bool)
QMenuBarPrivate ()
void setCurrentAction (QAction *, bool=false, bool=false)
void setKeyboardMode (bool)
void updateCornerWidgetToolBar ()
void updateGeometries ()
void wceCommands (uint command)
void wceCreateMenuBar (QWidget *)
void wceDestroyMenuBar ()
bool wceEmitSignals (QList< QWceMenuAction *> actions, uint command)
void wceRefresh ()
~QMenuBarPrivate ()
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static bool macUpdateMenuBarImmediatly ()
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QVector< QRect > actionRects
QPointer< QMenu > activeMenu
uint altPressed: 1
QBasicTimer autoReleaseTimer
uint closePopupMode: 1
QWidget * cornerWidgetContainer
QToolBar * cornerWidgetToolBar
QPointer< QAction > currentAction
QPointer< QAction > defaultAction
uint defaultPopDown
bool doChildEffects
QMenuBarExtension * extension
QList< QAction * > hiddenActions
uint itemsDirty: 1
QPointer< QWidget > keyboardFocusWidget
uint keyboardState: 1
QPointer< QWidget > leftWidget
struct QMenuBarPrivate::QMacMenuBarPrivate * mac_menubar
uint mouseDown: 1
QWidget * oldParent
QWidget * oldWindow
QAbstractPlatformMenuBar * platformMenuBar
uint popupState: 1
QPointer< QWidget > rightWidget
QVector< int > shortcutIndexMap
struct QMenuBarPrivate::QWceMenuBarPrivate * wce_menubar
bool wceClassicMenu
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 80 of file qmenubar_p.h.
Constructors and Destructors
QMenuBarPrivate()
QMenuBarPrivate::QMenuBarPrivate () inline
Definition at line 84 of file qmenubar_p.h.
                       : itemsDirty(0), currentAction(0), mouseDown(0),
                          closePopupMode(0), defaultPopDown(1), popupState(0), keyboardState(0), altPressed(0)
 #ifndef Q_WS_X11
                          , nativeMenuBar(-1)
 #endif
                          , doChildEffects(false)
 #ifdef QT3_SUPPORT
                          , doAutoResize(false)
 #endif
 #ifdef Q_WS_MAC
                          , mac_menubar(0)
 #endif
 #ifdef Q_WS_X11
                          , platformMenuBar(0)
 #endif
 #ifdef Q_WS_WINCE
                          , wce_menubar(0), wceClassicMenu(false)
 #endif
 #ifdef Q_WS_S60
                          , symbian_menubar(0)
 #endif
         { }
~QMenuBarPrivate()
QMenuBarPrivate::~QMenuBarPrivate () inline
Definition at line 107 of file qmenubar_p.h.
         {
 #ifdef Q_WS_X11
             delete platformMenuBar;
 #endif
 #ifdef Q_WS_MAC
             delete mac_menubar;
 #endif
 #ifdef Q_WS_WINCE
             delete wce_menubar;
 #endif
 #ifdef Q_WS_S60
             delete symbian_menubar;
 #endif
         }
Functions
_q_actionHovered()
void QMenuBarPrivate::_q_actionHovered ()
Definition at line 557 of file qmenubar.cpp.
 {
     Q_Q(QMenuBar);
     if (QAction *action = qobject_cast<QAction *>(q->sender())) {
         emit q->hovered(action);
 #ifndef QT_NO_ACCESSIBILITY
         if (QAccessible::isActive()) {
             int actionIndex = actions.indexOf(action);
             ++actionIndex;
             QAccessible::updateAccessibility(q, actionIndex, QAccessible::Focus);
             QAccessible::updateAccessibility(q, actionIndex, QAccessible::Selection);
         }
 #endif //QT_NO_ACCESSIBILITY
 #ifdef QT3_SUPPORT
         emit q->highlighted(q->findIdForAction(action));
 #endif
     }
 }
_q_actionTriggered()
void QMenuBarPrivate::_q_actionTriggered ()
Definition at line 546 of file qmenubar.cpp.
 {
     Q_Q(QMenuBar);
     if (QAction *action = qobject_cast<QAction *>(q->sender())) {
         emit q->triggered(action);
 #ifdef QT3_SUPPORT
         emit q->activated(q->findIdForAction(action));
 #endif
     }
 }
_q_internalShortcutActivated()
void QMenuBarPrivate::_q_internalShortcutActivated (int id)
Warning
This function is not part of the public interface.
Definition at line 1901 of file qmenubar.cpp.
 {
     Q_Q(QMenuBar);
     QAction *act = actions.at(id);
 #ifdef Q_WS_X11
     if (q->isNativeMenuBar()) {
         platformMenuBar->popupAction(act);
     } else {
 #endif
         setCurrentAction(act, true, true);
 #ifdef Q_WS_X11
     }
 #endif
     if (act && !act->menu()) {
         activateAction(act, QAction::Trigger);
         //100 is the same as the default value in QPushButton::animateClick
         autoReleaseTimer.start(100, q);
     } else if (act && q->style()->styleHint(QStyle::SH_MenuBar_AltKeyNavigation, 0, q)) {
         // When we open a menu using a shortcut, we should end up in keyboard state
         setKeyboardMode(true);
     }
 }
_q_updateDefaultAction()
void QMenuBarPrivate::_q_updateDefaultAction ()
Definition at line 553 of file qmenu_wince.cpp.
 {
     if (wce_menubar)
         wce_menubar->rebuild();
 }
_q_updateLayout()
void QMenuBarPrivate::_q_updateLayout ()
Definition at line 1924 of file qmenubar.cpp.
 {
     Q_Q(QMenuBar);
     itemsDirty = true;
     if (q->isVisible()) {
         updateGeometries();
         q->update();
     }
 }
actionAt()
QAction * QMenuBarPrivate::actionAt (QPoint p) const
Warning
This function is not part of the public interface.
Definition at line 127 of file qmenubar.cpp.
 {
     for(int i = 0; i < actions.size(); ++i) {
         if(actionRect(actions.at(i)).contains(p))
             return actions.at(i);
     }
     return 0;
 }
actionRect()
QRect QMenuBarPrivate::actionRect (QAction * act) const
Definition at line 289 of file qmenubar.cpp.
 {
     const int index = actions.indexOf(act);
     //makes sure the geometries are up-to-date
     const_cast<QMenuBarPrivate*>(this)->updateGeometries();
     if (index < 0 || index >= actionRects.count())
         return QRect(); // that can happen in case of native menubar
     return actionRects.at(index);
 }
activateAction()
void QMenuBarPrivate::activateAction (QAction * action, QAction::ActionEvent action_e)
Definition at line 530 of file qmenubar.cpp.
 {
     Q_Q(QMenuBar);
     if (!action || !action->isEnabled())
         return;
     action->activate(action_e);
     if (action_e == QAction::Hover)
         action->showStatusText(q);
 //     if(action_e == QAction::Trigger)
 //         emit q->activated(action);
 //     else if(action_e == QAction::Hover)
 //         emit q->highlighted(action);
 }
calcActionRects()
void QMenuBarPrivate::calcActionRects (int max_width, int start) const
Definition at line 434 of file qmenubar.cpp.
 {
     Q_Q(const QMenuBar);
     if(!itemsDirty)
         return;
     //let's reinitialize the buffer
     actionRects.resize(actions.count());
     actionRects.fill(QRect());
     const QStyle *style = q->style();
     const int itemSpacing = style->pixelMetric(QStyle::PM_MenuBarItemSpacing, 0, q);
     int max_item_height = 0, separator = -1, separator_start = 0, separator_len = 0;
     //calculate size
     const QFontMetrics fm = q->fontMetrics();
     const int hmargin = style->pixelMetric(QStyle::PM_MenuBarHMargin, 0, q),
               vmargin = style->pixelMetric(QStyle::PM_MenuBarVMargin, 0, q),
                 icone = style->pixelMetric(QStyle::PM_SmallIconSize, 0, q);
     for(int i = 0; i < actions.count(); i++) {
         QAction *action = actions.at(i);
         if(!action->isVisible())
             continue;
         QSize sz;
         //calc what I think the size is..
         if(action->isSeparator()) {
             if (style->styleHint(QStyle::SH_DrawMenuBarSeparator, 0, q))
                 separator = i;
             continue; //we don't really position these!
         } else {
             const QString s = action->text();
             QIcon is = action->icon();
             // If an icon is set, only the icon is visible
             if (!is.isNull())
                 sz = sz.expandedTo(QSize(icone, icone));
             else if (!s.isEmpty())
                 sz = fm.size(Qt::TextShowMnemonic, s);
         }
         //let the style modify the above size..
         QStyleOptionMenuItem opt;
         q->initStyleOption(&opt, action);
         sz = q->style()->sizeFromContents(QStyle::CT_MenuBarItem, &opt, sz, q);
         if(!sz.isEmpty()) {
             { //update the separator state
                 int iWidth = sz.width() + itemSpacing;
                 if(separator == -1)
                     separator_start += iWidth;
                 else
                     separator_len += iWidth;
             }
             //maximum height
             max_item_height = qMax(max_item_height, sz.height());
             //append
             actionRects[i] = QRect(0, 0, sz.width(), sz.height());
         }
     }
     //calculate position
     const int fw = q->style()->pixelMetric(QStyle::PM_MenuBarPanelWidth, 0, q);
     int x = fw + ((start == -1) ? hmargin : start) + itemSpacing;
     int y = fw + vmargin;
     for(int i = 0; i < actions.count(); i++) {
         QRect &rect = actionRects[i];
         if (rect.isNull())
             continue;
         //resize
         rect.setHeight(max_item_height);
         //move
         if(separator != -1 && i >= separator) { //after the separator
             int left = (max_width - separator_len - hmargin - itemSpacing) + (x - separator_start - hmargin);
             if(left < separator_start) { //wrap
                 separator_start = x = hmargin;
                 y += max_item_height;
             }
             rect.moveLeft(left);
         } else {
             rect.moveLeft(x);
         }
         rect.moveTop(y);
         //keep moving along..
         x += rect.width() + itemSpacing;
         //make sure we follow the layout direction
         rect = QStyle::visualRect(q->layoutDirection(), q->rect(), rect);
     }
 }
focusFirstAction()
void QMenuBarPrivate::focusFirstAction ()
Definition at line 302 of file qmenubar.cpp.
 {
     if(!currentAction) {
         updateGeometries();
         int index = 0;
         while (index < actions.count() && actionRects.at(index).isNull()) ++index;
         if (index < actions.count())
             setCurrentAction(actions.at(index));
     }
 }
getNextAction()
QAction * QMenuBarPrivate::getNextAction (const int start, const int increment) const
Definition at line 795 of file qmenubar.cpp.
Referenced by ~QMenuBarPrivate().
 {
     Q_Q(const QMenuBar);
     const_cast<QMenuBarPrivate*>(this)->updateGeometries();
     bool allowActiveAndDisabled = q->style()->styleHint(QStyle::SH_Menu_AllowActiveAndDisabled, 0, q);
     const int start = (_start == -1 && increment == -1) ? actions.count() : _start;
     const int end =  increment == -1 ? 0 : actions.count() - 1;
     for (int i = start; i != end;) {
         i += increment;
         QAction *current = actions.at(i);
         if (!actionRects.at(i).isNull() && (allowActiveAndDisabled || current->isEnabled()))
             return current;
     }
     if (_start != -1) //let's try from the beginning or the end
         return getNextAction(-1, increment);
     return 0;
 }
handleReparent()
void QMenuBarPrivate::handleReparent ()
Definition at line 1404 of file qmenubar.cpp.
 {
     Q_Q(QMenuBar);
     QWidget *newParent = q->parentWidget();
     //Note: if parent is reparented, then window may change even if parent doesn't
     // we need to install an event filter on parent, and remove the old one
     if (oldParent != newParent) {
         if (oldParent)
             oldParent->removeEventFilter(q);
         if (newParent)
             newParent->installEventFilter(q);
     }
     //we also need event filter on top-level (for shortcuts)
     QWidget *newWindow = newParent ? newParent->window() : 0;
     if (oldWindow != newWindow) {
         if (oldParent && oldParent != oldWindow)
             oldWindow->removeEventFilter(q);
         if (newParent && newParent != newWindow)
             newWindow->installEventFilter(q);
     }
 #ifdef Q_WS_X11
     platformMenuBar->handleReparent(oldParent, newParent, oldWindow, newWindow);
 #endif
     oldParent = newParent;
     oldWindow = newWindow;
 #ifdef Q_WS_MAC
     if (q->isNativeMenuBar() && !macWidgetHasNativeMenubar(newParent)) {
         // If the new parent got a native menubar from before, keep that
         // menubar rather than replace it with this one (because a parents
         // menubar has precedence over children menubars).
         macDestroyMenuBar();
         macCreateMenuBar(newParent);
     }
 #endif
 #ifdef Q_WS_WINCE
     if (qt_wince_is_mobile() && wce_menubar)
         wce_menubar->rebuild();
 #endif
 #ifdef Q_WS_S60
     // Construct symbian_menubar when this code path is entered first time
     // and when newParent != NULL
     if (!symbian_menubar)
         symbianCreateMenuBar(newParent);
     // Reparent and rebuild menubar when parent is changed
     if (symbian_menubar) {
         if (oldParent != newParent)
             reparentMenuBar(oldParent, newParent);
         q->hide();
         symbian_menubar->rebuild();
     }
 #ifdef QT_SOFTKEYS_ENABLED
     // Constuct menuBarAction when this code path is entered first time
     if (!menuBarAction) {
         if (newParent) {
             menuBarAction = QSoftKeyManager::createAction(QSoftKeyManager::MenuSoftKey, newParent);
             newParent->addAction(menuBarAction);
         }
     } else {
         // If reparenting i.e. we already have menuBarAction, remove it from old parent
         // and add for a new parent
         if (oldParent)
             oldParent->removeAction(menuBarAction);
         if (newParent)
             newParent->addAction(menuBarAction);
     }
 #endif // QT_SOFTKEYS_ENABLED
 #endif // Q_WS_S60
 }
init()
void QMenuBarPrivate::init ()
Definition at line 749 of file qmenubar.cpp.
Referenced by ~QMenuBarPrivate().
 {
     Q_Q(QMenuBar);
     q->setSizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::Minimum);
     q->setAttribute(Qt::WA_CustomWhatsThis);
 #ifdef Q_WS_MAC
     macCreateMenuBar(q->parentWidget());
     if(mac_menubar)
         q->hide();
 #endif
 #ifdef Q_WS_WINCE
     if (qt_wince_is_mobile()) {
         wceCreateMenuBar(q->parentWidget());
         if(wce_menubar)
             q->hide();
     }
     else {
         QApplication::setAttribute(Qt::AA_DontUseNativeMenuBar, true);
     }
 #endif
 #ifdef Q_WS_X11
     platformMenuBar = qt_guiPlatformMenuBarFactory()->create();
     platformMenuBar->init(q);
 #endif
     q->setBackgroundRole(QPalette::Button);
     oldWindow = oldParent = 0;
 #ifdef QT3_SUPPORT
     doAutoResize = false;
 #endif
 #ifdef QT_SOFTKEYS_ENABLED
     menuBarAction = 0;
 #endif
 #ifdef Q_WS_X11
     cornerWidgetToolBar = 0;
     cornerWidgetContainer = 0;
 #endif
     handleReparent();
     q->setMouseTracking(q->style()->styleHint(QStyle::SH_MenuBar_MouseTracking, 0, q));
     extension = new QMenuBarExtension(q);
     extension->setFocusPolicy(Qt::NoFocus);
     extension->hide();
 }
isVisible()
bool QMenuBarPrivate::isVisible (QAction * action)
Definition at line 170 of file qmenubar.cpp.
 {
     return !hiddenActions.contains(action);
 }
macCreateMenuBar()
void QMenuBarPrivate::macCreateMenuBar (QWidget * parent)
Definition at line 1790 of file qmenu_mac.mm.
Referenced by QMenuBarPrivate::QMacMenuBarPrivate::findAction().
 {
     Q_Q(QMenuBar);
     static int dontUseNativeMenuBar = -1;
     // We call the isNativeMenuBar function here
     // because that will make sure that local overrides
     // are dealt with correctly. q->isNativeMenuBar() will, if not
     // overridden, depend on the attribute Qt::AA_DontUseNativeMenuBar:
     bool qt_mac_no_native_menubar = !q->isNativeMenuBar();
     if (qt_mac_no_native_menubar == false && dontUseNativeMenuBar < 0) {
         // The menubar is set to be native. Let's check (one time only
         // for all menubars) if this is OK with the rest of the environment.
         // As a result, Qt::AA_DontUseNativeMenuBar is set. NB: the application
         // might still choose to not respect, or change, this flag.
         bool isPlugin = QApplication::testAttribute(Qt::AA_MacPluginApplication);
         bool environmentSaysNo = !qgetenv("QT_MAC_NO_NATIVE_MENUBAR").isEmpty();
         dontUseNativeMenuBar = isPlugin || environmentSaysNo;
         QApplication::instance()->setAttribute(Qt::AA_DontUseNativeMenuBar, dontUseNativeMenuBar);
         qt_mac_no_native_menubar = !q->isNativeMenuBar();
     }
     if (qt_mac_no_native_menubar == false) {
         // INVARIANT: Use native menubar.
         extern void qt_event_request_menubarupdate(); //qapplication_mac.cpp
         qt_event_request_menubarupdate();
         if (!parent && !fallback) {
             fallback = q;
             mac_menubar = new QMacMenuBarPrivate;
         } else if (parent && parent->isWindow()) {
             menubars()->insert(q->window(), q);
             mac_menubar = new QMacMenuBarPrivate;
         }
     }
 }
macDestroyMenuBar()
void QMenuBarPrivate::macDestroyMenuBar ()
Definition at line 1824 of file qmenu_mac.mm.
Referenced by QMenuBarPrivate::QMacMenuBarPrivate::findAction().
 {
     Q_Q(QMenuBar);
     QMacCocoaAutoReleasePool pool;
     if (fallback == q)
         fallback = 0;
     delete mac_menubar;
     QWidget *tlw = q->window();
     menubars()->remove(tlw);
     mac_menubar = 0;
     if (!qt_mac_current_menubar.qmenubar || qt_mac_current_menubar.qmenubar == q) {
 #ifdef QT_MAC_USE_COCOA
         QT_MANGLE_NAMESPACE(QCocoaMenuLoader) *loader = getMenuLoader();
         [loader removeActionsFromAppMenu];
 #else
         cancelAllMenuTracking();
 #endif
         extern void qt_event_request_menubarupdate(); //qapplication_mac.cpp
         qt_event_request_menubarupdate();
     }
 }
macMenu()
OSMenuRef QMenuBarPrivate::macMenu ()
Definition at line 1847 of file qmenu_mac.mm.
Referenced by QMenuBarPrivate::QMacMenuBarPrivate::findAction().
 {
     Q_Q(QMenuBar);
     if (!q->isNativeMenuBar() || !mac_menubar) {
         return 0;
     } else if (!mac_menubar->menu) {
         mac_menubar->menu = qt_mac_create_menu(q);
 #ifdef QT_MAC_USE_COCOA
         [mac_menubar->menu setAutoenablesItems:NO];
 #endif
         ProcessSerialNumber mine, front;
         if (GetCurrentProcess(&mine) == noErr && GetFrontProcess(&front) == noErr) {
             if (!qt_mac_no_menubar_merge && !mac_menubar->apple_menu) {
                 mac_menubar->apple_menu = qt_mac_create_menu(q);
 #ifndef QT_MAC_USE_COCOA
                 MenuItemIndex index;
                 AppendMenuItemTextWithCFString(mac_menubar->menu, 0, 0, 0, &index);
                 SetMenuTitleWithCFString(mac_menubar->apple_menu, QCFString(QString(QChar(0x14))));
                 SetMenuItemHierarchicalMenu(mac_menubar->menu, index, mac_menubar->apple_menu);
                 SetMenuItemProperty(mac_menubar->apple_menu, 0, kMenuCreatorQt, kMenuPropertyQWidget, sizeof(q), &q);
 #else
                 [mac_menubar->apple_menu setTitle:qt_mac_QStringToNSString(QString(QChar(0x14)))];
                 NSMenuItem *apple_menuItem = [[NSMenuItem alloc] init];
                 [apple_menuItem setSubmenu:mac_menubar->menu];
                 [mac_menubar->apple_menu addItem:apple_menuItem];
                 [apple_menuItem release];
 #endif
             }
             if (mac_menubar->apple_menu) {
 #ifndef QT_MAC_USE_COCOA
                 SetMenuItemProperty(mac_menubar->menu, 0, kMenuCreatorQt, kMenuPropertyMergeMenu,
                                     sizeof(mac_menubar->apple_menu), &mac_menubar->apple_menu);
 #else
                 QMenuPrivate::mergeMenuHash.insert(mac_menubar->menu, mac_menubar->apple_menu);
 #endif
             }
             QList<QAction*> items = q->actions();
             for(int i = 0; i < items.count(); i++)
                 mac_menubar->addAction(items[i]);
         }
     }
     return mac_menubar->menu;
 }
macUpdateMenuBarImmediatly()
bool QMenuBarPrivate::macUpdateMenuBarImmediatly () static
Definition at line 2066 of file qmenu_mac.mm.
Referenced by QMenuBarPrivate::QMacMenuBarPrivate::findAction(), and QMenuBar::macUpdateMenuBar().
 {
     bool ret = false;
     cancelAllMenuTracking();
     QWidget *w = findWindowThatShouldDisplayMenubar();
     QMenuBar *mb = findMenubarForWindow(w);
     extern bool qt_mac_app_fullscreen; //qapplication_mac.mm
     // We need to see if we are in full screen mode, if so we need to
     // switch the full screen mode to be able to show or hide the menubar.
     if(w && mb) {
         // This case means we are creating a menubar, check if full screen
         if(w->isFullScreen()) {
             // Ok, switch to showing the menubar when hovering over it.
             SetSystemUIMode(kUIModeAllHidden, kUIOptionAutoShowMenuBar);
             qt_mac_app_fullscreen = true;
         }
     } else if(w) {
         // Removing a menubar
         if(w->isFullScreen()) {
             // Ok, switch to not showing the menubar when hovering on it
             SetSystemUIMode(kUIModeAllHidden, 0);
             qt_mac_app_fullscreen = true;
         }
     }
     if (mb && mb->isNativeMenuBar()) {
         bool modal = QApplicationPrivate::modalState();
 #ifdef QT_MAC_USE_COCOA
         QMacCocoaAutoReleasePool pool;
 #endif
         if (OSMenuRef menu = mb->macMenu()) {
 #ifndef QT_MAC_USE_COCOA
             SetRootMenu(menu);
 #else
             QT_MANGLE_NAMESPACE(QCocoaMenuLoader) *loader = getMenuLoader();
             [loader ensureAppMenuInMenu:menu];
             [NSApp setMainMenu:menu];
             syncMenuBarItemsVisiblity(mb->d_func()->mac_menubar);
             if (OSMenuRef tmpMerge = QMenuPrivate::mergeMenuHash.value(menu)) {
                 if (QMenuMergeList *mergeList
                         = QMenuPrivate::mergeMenuItemsHash.value(tmpMerge)) {
                     const int mergeListSize = mergeList->size();
                     for (int i = 0; i < mergeListSize; ++i) {
                         const QMenuMergeItem &mergeItem = mergeList->at(i);
                         // Ideally we would call QMenuPrivate::syncAction, but that requires finding
                         // the original QMen and likely doing more work than we need.
                         // For example, enabled is handled below.
                         [mergeItem.menuItem setTag:reinterpret_cast<long>(
                                                     static_cast<QAction *>(mergeItem.action->action))];
                         [mergeItem.menuItem setHidden:!(mergeItem.action->action->isVisible())];
                     }
                 }
             }
 #endif
             // Check if menu is modally shaddowed and should  be disabled:
             modal = qt_mac_should_disable_menu(mb);
             if (mb != qt_mac_current_menubar.qmenubar || modal != qt_mac_current_menubar.modal)
                 qt_mac_set_modal_state(menu, modal);
         }
         qt_mac_current_menubar.qmenubar = mb;
         qt_mac_current_menubar.modal = modal;
         ret = true;
     } else if (qt_mac_current_menubar.qmenubar && qt_mac_current_menubar.qmenubar->isNativeMenuBar()) {
         // INVARIANT: The currently active menu bar (if any) is not native. But we do have a
         // native menu bar from before. So we need to decide whether or not is should be enabled:
         const bool modal = qt_mac_should_disable_menu(qt_mac_current_menubar.qmenubar);
         if (modal != qt_mac_current_menubar.modal) {
             ret = true;
             if (OSMenuRef menu = qt_mac_current_menubar.qmenubar->macMenu()) {
 #ifndef QT_MAC_USE_COCOA
                 SetRootMenu(menu);
 #else
                 QT_MANGLE_NAMESPACE(QCocoaMenuLoader) *loader = getMenuLoader();
                 [loader ensureAppMenuInMenu:menu];
                 [NSApp setMainMenu:menu];
                 syncMenuBarItemsVisiblity(qt_mac_current_menubar.qmenubar->d_func()->mac_menubar);
 #endif
                 qt_mac_set_modal_state(menu, modal);
             }
             qt_mac_current_menubar.modal = modal;
         }
     }
     if (!ret) {
         qt_mac_clear_menubar();
     }
     return ret;
 }
macWidgetHasNativeMenubar()
bool QMenuBarPrivate::macWidgetHasNativeMenubar (QWidget * widget)
Definition at line 1779 of file qmenu_mac.mm.
Referenced by QMenuBarPrivate::QMacMenuBarPrivate::findAction().
 {
     // This function is different from q->isNativeMenuBar(), as
     // it returns true only if a native menu bar is actually
     // _created_.
     if (!widget)
         return false;
     return menubars()->contains(widget->window());
 }
menuRect()
QRect QMenuBarPrivate::menuRect (bool extVisible) const
Definition at line 136 of file qmenubar.cpp.
 {
     Q_Q(const QMenuBar);
     int hmargin = q->style()->pixelMetric(QStyle::PM_MenuBarPanelWidth, 0, q);
     QRect result = q->rect();
     result.adjust(hmargin, 0, -hmargin, 0);
     if (extVisible) {
         if (q->isRightToLeft())
             result.setLeft(result.left() + extension->sizeHint().width());
         else
             result.setWidth(result.width() - extension->sizeHint().width());
     }
     if (leftWidget && leftWidget->isVisible()) {
         QSize sz = leftWidget->sizeHint();
         if (q->isRightToLeft())
             result.setRight(result.right() - sz.width());
         else
             result.setLeft(result.left() + sz.width());
     }
     if (rightWidget && rightWidget->isVisible()) {
         QSize sz = rightWidget->sizeHint();
         if (q->isRightToLeft())
             result.setLeft(result.left() + sz.width());
         else
             result.setRight(result.right() - sz.width());
     }
     return result;
 }
popupAction()
void QMenuBarPrivate::popupAction (QAction * action, bool activateFirst)
Definition at line 339 of file qmenubar.cpp.
 {
     Q_Q(QMenuBar);
     if(!action || !action->menu() || closePopupMode)
         return;
     popupState = true;
     if (action->isEnabled() && action->menu()->isEnabled()) {
         closePopupMode = 0;
         activeMenu = action->menu();
         activeMenu->d_func()->causedPopup.widget = q;
         activeMenu->d_func()->causedPopup.action = action;
         QRect adjustedActionRect = actionRect(action);
         QPoint pos(q->mapToGlobal(QPoint(adjustedActionRect.left(), adjustedActionRect.bottom() + 1)));
         QSize popup_size = activeMenu->sizeHint();
         //we put the popup menu on the screen containing the bottom-center of the action rect
         QRect screenRect = QApplication::desktop()->screenGeometry(pos + QPoint(adjustedActionRect.width() / 2, 0));
         pos = QPoint(qMax(pos.x(), screenRect.x()), qMax(pos.y(), screenRect.y()));
         const bool fitUp = (q->mapToGlobal(adjustedActionRect.topLeft()).y() >= popup_size.height());
         const bool fitDown = (pos.y() + popup_size.height() <= screenRect.bottom());
         const bool rtl = q->isRightToLeft();
         const int actionWidth = adjustedActionRect.width();
         if (!fitUp && !fitDown) { //we should shift the menu
             bool shouldShiftToRight = !rtl;
             if (rtl && popup_size.width() > pos.x())
                 shouldShiftToRight = true;
             else if (actionWidth + popup_size.width() + pos.x() > screenRect.right())
                 shouldShiftToRight = false;
             if (shouldShiftToRight) {
                 pos.rx() += actionWidth + (rtl ? popup_size.width() : 0);
             } else {
                 //shift to left
                 if (!rtl)
                     pos.rx() -= popup_size.width();
             }
         } else if (rtl) {
             pos.rx() += actionWidth;
         }
         if(!defaultPopDown || (fitUp && !fitDown))
             pos.setY(qMax(screenRect.y(), q->mapToGlobal(QPoint(0, adjustedActionRect.top()-popup_size.height())).y()));
         activeMenu->popup(pos);
         if(activateFirst)
             activeMenu->d_func()->setFirstActionActive();
     }
     q->update(actionRect(action));
 }
setCurrentAction()
void QMenuBarPrivate::setCurrentAction (QAction * action, bool popup = false, bool activateFirst = false)
Definition at line 391 of file qmenubar.cpp.
 {
     if(currentAction == action && popup == popupState)
         return;
     autoReleaseTimer.stop();
     doChildEffects = (popup && !activeMenu);
     Q_Q(QMenuBar);
     QWidget *fw = 0;
     if(QMenu *menu = activeMenu) {
         activeMenu = 0;
         if (popup) {
             fw = q->window()->focusWidget();
             q->setFocus(Qt::NoFocusReason);
         }
         menu->hide();
     }
     if(currentAction)
         q->update(actionRect(currentAction));
     popupState = popup;
 #ifndef QT_NO_STATUSTIP
     QAction *previousAction = currentAction;
 #endif
     currentAction = action;
     if (action) {
         activateAction(action, QAction::Hover);
         if(popup)
             popupAction(action, activateFirst);
         q->update(actionRect(action));
 #ifndef QT_NO_STATUSTIP
     }  else if (previousAction) {
         QString empty;
         QStatusTipEvent tip(empty);
         QApplication::sendEvent(q, &tip);
 #endif
     }
     if (fw)
         fw->setFocus(Qt::NoFocusReason);
 }
setKeyboardMode()
void QMenuBarPrivate::setKeyboardMode (bool b)
Definition at line 313 of file qmenubar.cpp.
 {
     Q_Q(QMenuBar);
     if (b && !q->style()->styleHint(QStyle::SH_MenuBar_AltKeyNavigation, 0, q)) {
         setCurrentAction(0);
         return;
     }
     keyboardState = b;
     if(b) {
         QWidget *fw = QApplication::focusWidget();
         if (fw != q)
             keyboardFocusWidget = fw;
         focusFirstAction();
         q->setFocus(Qt::MenuBarFocusReason);
     } else {
         if(!popupState)
             setCurrentAction(0);
         if(keyboardFocusWidget) {
             if (QApplication::focusWidget() == q)
                 keyboardFocusWidget->setFocus(Qt::MenuBarFocusReason);
             keyboardFocusWidget = 0;
         }
     }
     q->update();
 }
updateCornerWidgetToolBar()
void QMenuBarPrivate::updateCornerWidgetToolBar ()
Definition at line 1935 of file qmenubar.cpp.
 {
     Q_Q(QMenuBar);
     if (!cornerWidgetToolBar) {
         QMainWindow *window = qobject_cast<QMainWindow *>(q->window());
         if (!window) {
             qWarning() << "Menubar parent is not a QMainWindow, not showing corner widgets";
             return;
         }
         cornerWidgetToolBar = window->addToolBar(QApplication::translate("QMenuBar", "Corner Toolbar"));
         cornerWidgetToolBar->setObjectName(QLatin1String("CornerToolBar"));
         cornerWidgetContainer = new QWidget;
         cornerWidgetToolBar->addWidget(cornerWidgetContainer);
         new QHBoxLayout(cornerWidgetContainer);
     } else {
         QLayout *layout = cornerWidgetContainer->layout();
         while (layout->count() > 0) {
             layout->takeAt(0);
         }
     }
     if (leftWidget) {
         leftWidget->setParent(cornerWidgetContainer);
         cornerWidgetContainer->layout()->addWidget(leftWidget);
     }
     if (rightWidget) {
         rightWidget->setParent(cornerWidgetContainer);
         cornerWidgetContainer->layout()->addWidget(rightWidget);
     }
 }
updateGeometries()
void QMenuBarPrivate::updateGeometries ()
Definition at line 175 of file qmenubar.cpp.
 {
     Q_Q(QMenuBar);
     if(!itemsDirty)
         return;
     int q_width = q->width()-(q->style()->pixelMetric(QStyle::PM_MenuBarPanelWidth, 0, q)*2);
     int q_start = -1;
     if(
 #ifdef Q_WS_X11
         platformMenuBar->allowCornerWidgets() &&
 #endif
         (leftWidget || rightWidget)) {
         int vmargin = q->style()->pixelMetric(QStyle::PM_MenuBarVMargin, 0, q)
                       + q->style()->pixelMetric(QStyle::PM_MenuBarPanelWidth, 0, q);
         int hmargin = q->style()->pixelMetric(QStyle::PM_MenuBarHMargin, 0, q)
                       + q->style()->pixelMetric(QStyle::PM_MenuBarPanelWidth, 0, q);
         if (leftWidget && leftWidget->isVisible()) {
             QSize sz = leftWidget->sizeHint();
             q_width -= sz.width();
             q_start = sz.width();
             QPoint pos(hmargin, (q->height() - leftWidget->height()) / 2);
             QRect vRect = QStyle::visualRect(q->layoutDirection(), q->rect(), QRect(pos, sz));
             leftWidget->setGeometry(vRect);
         }
         if (rightWidget && rightWidget->isVisible()) {
             QSize sz = rightWidget->sizeHint();
             q_width -= sz.width();
             QPoint pos(q->width() - sz.width() - hmargin, vmargin);
             QRect vRect = QStyle::visualRect(q->layoutDirection(), q->rect(), QRect(pos, sz));
             rightWidget->setGeometry(vRect);
         }
     }
 #ifdef Q_WS_MAC
     if(q->isNativeMenuBar()) {//nothing to see here folks, move along..
         itemsDirty = false;
         return;
     }
 #endif
     calcActionRects(q_width, q_start);
     currentAction = 0;
 #ifndef QT_NO_SHORTCUT
     if(
 #ifdef Q_WS_X11
         !platformMenuBar->shortcutsHandledByNativeMenuBar() &&
 #endif
         itemsDirty) {
         for(int j = 0; j < shortcutIndexMap.size(); ++j)
             q->releaseShortcut(shortcutIndexMap.value(j));
         shortcutIndexMap.resize(0); // faster than clear
         for(int i = 0; i < actions.count(); i++)
             shortcutIndexMap.append(q->grabShortcut(QKeySequence::mnemonic(actions.at(i)->text())));
     }
 #endif
 #ifdef Q_WS_X11
     if(q->isNativeMenuBar()) {//nothing to see here folks, move along..
         itemsDirty = false;
         return;
     }
 #endif
     itemsDirty = false;
     hiddenActions.clear();
     //this is the menu rectangle without any extension
     QRect menuRect = this->menuRect(false);
     //we try to see if the actions will fit there
     bool hasHiddenActions = false;
     for (int i = 0; i < actions.count(); ++i) {
         const QRect &rect = actionRects.at(i);
         if (rect.isValid() && !menuRect.contains(rect)) {
             hasHiddenActions = true;
             break;
         }
     }
     //...and if not, determine the ones that fit on the menu with the extension visible
     if (hasHiddenActions) {
         menuRect = this->menuRect(true);
         for (int i = 0; i < actions.count(); ++i) {
             const QRect &rect = actionRects.at(i);
             if (rect.isValid() && !menuRect.contains(rect)) {
                 hiddenActions.append(actions.at(i));
             }
         }
     }
     if (hiddenActions.count() > 0) {
         QMenu *pop = extension->menu();
         if (!pop) {
             pop = new QMenu(q);
             extension->setMenu(pop);
         }
         pop->clear();
         pop->addActions(hiddenActions);
         int vmargin = q->style()->pixelMetric(QStyle::PM_MenuBarVMargin, 0, q);
         int x = q->isRightToLeft()
                 ? menuRect.left() - extension->sizeHint().width() + 1
                 : menuRect.right();
         extension->setGeometry(x, vmargin, extension->sizeHint().width(), menuRect.height() - vmargin*2);
         extension->show();
     } else {
         extension->hide();
     }
     q->updateGeometry();
 #ifdef QT3_SUPPORT
     if (parent) {
         QMenubarUpdatedEvent menubarUpdated(q);
         QApplication::sendEvent(parent, &menubarUpdated);
     }
 #endif
 }
wceCommands()
void QMenuBarPrivate::wceCommands (uint command)
Definition at line 345 of file qmenu_wince.cpp.
Referenced by QMenuBar::wceCommands().
 {
     if (wceClassicMenu) {
         for (int i = 0; i < wce_menubar->actionItemsClassic.size(); ++i)
             wceEmitSignals(wce_menubar->actionItemsClassic.at(i), command);
     } else {
         if (wceEmitSignals(wce_menubar->actionItems, command)) {
             return;
         }
         else if (wce_menubar->leftButtonIsMenu) {//check if command is on the left quick button
             wceEmitSignals(wce_menubar->actionItemsLeftButton, command);
         }
         else if ((wce_menubar->leftButtonAction) && (command == wce_menubar->leftButtonCommand)) {
             emit q_func()->triggered(wce_menubar->leftButtonAction);
             wce_menubar->leftButtonAction->activate(QAction::Trigger);
         }
     }
 }
wceCreateMenuBar()
void QMenuBarPrivate::wceCreateMenuBar (QWidget * parent)
Definition at line 384 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QMacMenuBarPrivate::findAction().
 {
     Q_Q(QMenuBar);
     wce_menubar = new QWceMenuBarPrivate(this);
     wce_menubar->parentWindowHandle = parent ? parent->winId() : q->winId();
     wce_menubar->leftButtonAction = defaultAction;
     wce_menubar->menubarHandle = qt_wce_create_menubar(wce_menubar->parentWindowHandle, (HINSTANCE)qWinAppInst(), 0, SHCMBF_EMPTYBAR);
     Q_ASSERT_X(wce_menubar->menubarHandle, "wceCreateMenuBar", "cannot create empty menu bar");
     DrawMenuBar(wce_menubar->menubarHandle);
     nativeMenuBars.append(q);
     wceClassicMenu = (!qt_wince_is_smartphone() && !qt_wince_is_pocket_pc());
 }
wceDestroyMenuBar()
void QMenuBarPrivate::wceDestroyMenuBar ()
Definition at line 399 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QMacMenuBarPrivate::findAction().
 {
     Q_Q(QMenuBar);
     int index = nativeMenuBars.indexOf(q);
     nativeMenuBars.removeAt(index);
     if (wce_menubar) {
         delete wce_menubar;
         wce_menubar = 0;
     }
 }
wceEmitSignals()
bool QMenuBarPrivate::wceEmitSignals (QList< QWceMenuAction *> actions, uint command)
Definition at line 323 of file qmenu_wince.cpp.
 {
     QAction *foundAction = 0;
     for (int i = 0; i < actions.size(); ++i) {
         QWceMenuAction *action = actions.at(i);
         if (action->action->menu()) {
             foundAction = action->action->menu()->wceCommands(command);
             if (foundAction)
                 break;
         }
         else if (action->command == command) {
             action->action->activate(QAction::Trigger);
             return true;
         }
     }
     if (foundAction) {
         emit q_func()->triggered(foundAction);
         return true;
     }
     return false;
 }
wceRefresh()
void QMenuBarPrivate::wceRefresh ()
Definition at line 283 of file qmenu_wince.cpp.
 {
     DrawMenuBar(wce_menubar->menubarHandle);
 }
Properties
actionRects
QVector<QRect> QMenuBarPrivate::actionRects mutable
Definition at line 130 of file qmenubar_p.h.
activeMenu
QPointer<QMenu> QMenuBarPrivate::activeMenu
Definition at line 144 of file qmenubar_p.h.
altPressed
uint QMenuBarPrivate::altPressed
Definition at line 149 of file qmenubar_p.h.
autoReleaseTimer
QBasicTimer QMenuBarPrivate::autoReleaseTimer
Definition at line 186 of file qmenubar_p.h.
closePopupMode
uint QMenuBarPrivate::closePopupMode
Definition at line 137 of file qmenubar_p.h.
cornerWidgetContainer
QWidget* QMenuBarPrivate::cornerWidgetContainer
Definition at line 297 of file qmenubar_p.h.
cornerWidgetToolBar
QToolBar* QMenuBarPrivate::cornerWidgetToolBar
Definition at line 296 of file qmenubar_p.h.
currentAction
QPointer<QAction> QMenuBarPrivate::currentAction
Definition at line 136 of file qmenubar_p.h.
defaultAction
QPointer<QAction> QMenuBarPrivate::defaultAction
Definition at line 184 of file qmenubar_p.h.
defaultPopDown
uint QMenuBarPrivate::defaultPopDown
Definition at line 137 of file qmenubar_p.h.
doChildEffects
bool QMenuBarPrivate::doChildEffects
Definition at line 173 of file qmenubar_p.h.
extension
QMenuBarExtension* QMenuBarPrivate::extension
Definition at line 169 of file qmenubar_p.h.
hiddenActions
QList<QAction*> QMenuBarPrivate::hiddenActions
Definition at line 182 of file qmenubar_p.h.
itemsDirty
uint QMenuBarPrivate::itemsDirty
Definition at line 127 of file qmenubar_p.h.
keyboardFocusWidget
QPointer<QWidget> QMenuBarPrivate::keyboardFocusWidget
Definition at line 150 of file qmenubar_p.h.
keyboardState
uint QMenuBarPrivate::keyboardState
Definition at line 149 of file qmenubar_p.h.
leftWidget
QPointer<QWidget> QMenuBarPrivate::leftWidget
Definition at line 168 of file qmenubar_p.h.
mac_menubar
struct QMenuBarPrivate::QMacMenuBarPrivate * QMenuBarPrivate::mac_menubar
Referenced by QMenuBarPrivate::QMacMenuBarPrivate::findAction(), and ~QMenuBarPrivate().
mouseDown
uint QMenuBarPrivate::mouseDown
Definition at line 137 of file qmenubar_p.h.
oldParent
QWidget* QMenuBarPrivate::oldParent
Definition at line 179 of file qmenubar_p.h.
oldWindow
QWidget* QMenuBarPrivate::oldWindow
Definition at line 180 of file qmenubar_p.h.
platformMenuBar
QAbstractPlatformMenuBar* QMenuBarPrivate::platformMenuBar
Definition at line 191 of file qmenubar_p.h.
Referenced by ~QMenuBarPrivate().
popupState
uint QMenuBarPrivate::popupState
Definition at line 143 of file qmenubar_p.h.
rightWidget
QPointer<QWidget> QMenuBarPrivate::rightWidget
Definition at line 168 of file qmenubar_p.h.
shortcutIndexMap
QVector<int> QMenuBarPrivate::shortcutIndexMap
Definition at line 129 of file qmenubar_p.h.
wce_menubar
struct QMenuBarPrivate::QWceMenuBarPrivate * QMenuBarPrivate::wce_menubar
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::findAction(), QMenuBar::wceCommands(), and ~QMenuBarPrivate().
wceClassicMenu
bool QMenuBarPrivate::wceClassicMenu
Definition at line 256 of file qmenubar_p.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qmenubar_p.h
/src/gui/widgets/qmenu_mac.mm
/src/gui/widgets/qmenu_wince.cpp
/src/gui/widgets/qmenubar.cpp