Qt 4.8: QDeclarativePathCubic Class Reference
QDeclarativePathCubic Class Reference
#include <qdeclarativepath_p.h>
Signals
void control1XChanged ()
void control1YChanged ()
void control2XChanged ()
void control2YChanged ()
Signals inherited from QDeclarativeCurve
void xChanged ()
void yChanged ()
Signals inherited from QDeclarativePathElement
void changed ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addToPath (QPainterPath &path)
qreal control1X () const
qreal control1Y () const
qreal control2X () const
qreal control2Y () const
QDeclarativePathCubic (QObject *parent=0)
void setControl1X (qreal x)
void setControl1Y (qreal y)
void setControl2X (qreal x)
void setControl2Y (qreal y)
Public Functions inherited from QDeclarativeCurve
QDeclarativeCurve (QObject *parent=0)
void setX (qreal x)
void setY (qreal y)
qreal x () const
qreal y () const
Public Functions inherited from QDeclarativePathElement
QDeclarativePathElement (QObject *parent=0)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
qreal _control1X
qreal _control1Y
qreal _control2X
qreal _control2Y
qreal control1X
qreal control1Y
qreal control2X
qreal control2Y
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 152 of file qdeclarativepath_p.h.
Constructors and Destructors
QDeclarativePathCubic()
QDeclarativePathCubic::QDeclarativePathCubic (QObject * parent = 0) inline
Definition at line 161 of file qdeclarativepath_p.h.
 : QDeclarativeCurve(parent), _control1X(0), _control1Y(0), _control2X(0), _control2Y(0) {}
Functions
addToPath()
void QDeclarativePathCubic::addToPath (QPainterPath & path) virtual
Reimplemented from QDeclarativeCurve.
Definition at line 867 of file qdeclarativepath.cpp.
 {
     path.cubicTo(control1X(), control1Y(), control2X(), control2Y(), x(), y());
 }
control1X()
qreal QDeclarativePathCubic::control1X () const
Referenced by QDeclarativePathQuad::addToPath().
control1XChanged
void QDeclarativePathCubic::control1XChanged () signal
control1Y()
qreal QDeclarativePathCubic::control1Y () const
Referenced by setControl1X().
control1YChanged
void QDeclarativePathCubic::control1YChanged () signal
control2X()
qreal QDeclarativePathCubic::control2X () const
Referenced by setControl1Y().
control2XChanged
void QDeclarativePathCubic::control2XChanged () signal
control2Y()
qreal QDeclarativePathCubic::control2Y () const
Referenced by setControl2X().
control2YChanged
void QDeclarativePathCubic::control2YChanged () signal
setControl1X()
void QDeclarativePathCubic::setControl1X (qreal x)
Definition at line 807 of file qdeclarativepath.cpp.
 {
     if (_control1X != x) {
         _control1X = x;
         emit control1XChanged();
         emit changed();
     }
 }
setControl1Y()
void QDeclarativePathCubic::setControl1Y (qreal y)
Definition at line 821 of file qdeclarativepath.cpp.
 {
     if (_control1Y != y) {
         _control1Y = y;
         emit control1YChanged();
         emit changed();
     }
 }
setControl2X()
void QDeclarativePathCubic::setControl2X (qreal x)
Definition at line 844 of file qdeclarativepath.cpp.
 {
     if (_control2X != x) {
         _control2X = x;
         emit control2XChanged();
         emit changed();
     }
 }
setControl2Y()
void QDeclarativePathCubic::setControl2Y (qreal y)
Definition at line 858 of file qdeclarativepath.cpp.
 {
     if (_control2Y != y) {
         _control2Y = y;
         emit control2YChanged();
         emit changed();
     }
 }
Properties
_control1X
qreal QDeclarativePathCubic::_control1X private
Definition at line 184 of file qdeclarativepath_p.h.
_control1Y
qreal QDeclarativePathCubic::_control1Y private
Definition at line 185 of file qdeclarativepath_p.h.
_control2X
qreal QDeclarativePathCubic::_control2X private
Definition at line 186 of file qdeclarativepath_p.h.
_control2Y
qreal QDeclarativePathCubic::_control2Y private
Definition at line 187 of file qdeclarativepath_p.h.
control1X
qreal QDeclarativePathCubic::control1X private
Definition at line 156 of file qdeclarativepath_p.h.
control1Y
qreal QDeclarativePathCubic::control1Y private
Definition at line 157 of file qdeclarativepath_p.h.
control2X
qreal QDeclarativePathCubic::control2X private
Definition at line 158 of file qdeclarativepath_p.h.
control2Y
qreal QDeclarativePathCubic::control2Y private
Definition at line 159 of file qdeclarativepath_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativepath_p.h
/src/declarative/graphicsitems/qdeclarativepath.cpp