Qt 4.8: QDeclarativePropertyAnimation Class Reference
QDeclarativePropertyAnimation Class Reference
#include <qdeclarativeanimation_p.h>
Signals
void durationChanged (int)
void easingChanged (const QEasingCurve &)
void fromChanged (QVariant)
void propertiesChanged (const QString &)
void propertyChanged ()
void targetChanged ()
void toChanged (QVariant)
Signals inherited from QDeclarativeAbstractAnimation
void alwaysRunToEndChanged (bool)
void completed ()
void loopCountChanged (int)
void pausedChanged (bool)
void runningChanged (bool)
void started ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual int duration () const
QEasingCurve easing () const
QDeclarativeListProperty< QObject > exclude ()
QVariant from () const
QString properties () const
QString property () const
QDeclarativePropertyAnimation (QObject *parent=0)
virtual void setDuration (int)
void setEasing (const QEasingCurve &)
void setFrom (const QVariant &)
void setProperties (const QString &)
void setProperty (const QString &)
void setTarget (QObject *)
void setTo (const QVariant &)
QObject * target () const
QDeclarativeListProperty< QObject > targets ()
QVariant to () const
virtual ~QDeclarativePropertyAnimation ()
Public Functions inherited from QDeclarativeAbstractAnimation
bool alwaysRunToEnd () const
void classBegin ()
Invoked after class creation, but before any properties have been set.
void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
int currentTime ()
QDeclarativeAnimationGroup * group () const
bool isPaused () const
bool isRunning () const
int loops () const
QDeclarativeAbstractAnimation (QObject *parent=0)
void setAlwaysRunToEnd (bool)
void setCurrentTime (int)
void setDefaultTarget (const QDeclarativeProperty &)
void setDisableUserControl ()
void setGroup (QDeclarativeAnimationGroup *)
void setLoops (int)
void setPaused (bool)
void setRunning (bool)
virtual ~QDeclarativeAbstractAnimation ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativePropertyValueSource
QDeclarativePropertyValueSource ()
Constructs a QDeclarativePropertyValueSource.
virtual ~QDeclarativePropertyValueSource ()
Destroys the value source.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
QDeclarativePropertyAnimation (QDeclarativePropertyAnimationPrivate &dd, QObject *parent)
virtual QAbstractAnimation * qtAnimation ()
virtual void transition (QDeclarativeStateActions &actions, QDeclarativeProperties &modified, TransitionDirection direction)
Protected Functions inherited from QDeclarativeAbstractAnimation
QDeclarativeAbstractAnimation (QDeclarativeAbstractAnimationPrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
int duration
QEasingCurve easing
QDeclarativeListProperty< QObject > exclude
QVariant from
QString properties
QString property
QObject * target
QDeclarativeListProperty< QObject > targets
QVariant to
Additional Inherited Members
Public Types inherited from QDeclarativeAbstractAnimation
enum Loops { Infinite = -2 }
enum TransitionDirection { Forward, Backward }
Public Slots inherited from QDeclarativeAbstractAnimation
void complete ()
void pause ()
void restart ()
void resume ()
void start ()
void stop ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 240 of file qdeclarativeanimation_p.h.
Constructors and Destructors
QDeclarativePropertyAnimation() [1/2]
QDeclarativePropertyAnimation::QDeclarativePropertyAnimation (QObject * parent = 0)
Definition at line 1915 of file qdeclarativeanimation.cpp.
 : QDeclarativeAbstractAnimation(*(new QDeclarativePropertyAnimationPrivate), parent)
 {
     Q_D(QDeclarativePropertyAnimation);
     d->init();
 }
~QDeclarativePropertyAnimation()
QDeclarativePropertyAnimation::~QDeclarativePropertyAnimation () virtual
Definition at line 1929 of file qdeclarativeanimation.cpp.
 {
 }
QDeclarativePropertyAnimation() [2/2]
QDeclarativePropertyAnimation::QDeclarativePropertyAnimation (QDeclarativePropertyAnimationPrivate & dd, QObject * parent) protected
Definition at line 1922 of file qdeclarativeanimation.cpp.
 : QDeclarativeAbstractAnimation(dd, parent)
 {
     Q_D(QDeclarativePropertyAnimation);
     d->init();
 }
Functions
duration()
virtual int QDeclarativePropertyAnimation::duration () const virtual
Reimplemented in QDeclarativeSmoothedAnimation.
Referenced by QDeclarativePropertyAnimationPrivate::init(), and setDuration().
durationChanged
void QDeclarativePropertyAnimation::durationChanged (int) signal
Referenced by setDuration().
easing()
QEasingCurve QDeclarativePropertyAnimation::easing () const
Referenced by setTo().
easingChanged
void QDeclarativePropertyAnimation::easingChanged (const QEasingCurve &) signal
Referenced by setEasing().
exclude()
QDeclarativeListProperty<QObject> QDeclarativePropertyAnimation::exclude ()
Referenced by setProperties().
from()
QVariant QDeclarativePropertyAnimation::from () const
Referenced by setDuration().
fromChanged
void QDeclarativePropertyAnimation::fromChanged (QVariant) signal
Referenced by setFrom().
properties()
QString QDeclarativePropertyAnimation::properties () const
Referenced by setProperty().
propertiesChanged
void QDeclarativePropertyAnimation::propertiesChanged (const QString &) signal
Referenced by setProperties().
property()
QString QDeclarativePropertyAnimation::property () const
Referenced by setTarget(), and QDeclarativeSpringAnimation::transition().
propertyChanged
void QDeclarativePropertyAnimation::propertyChanged () signal
Referenced by setProperty().
qtAnimation()
QAbstractAnimation * QDeclarativePropertyAnimation::qtAnimation () protected virtual
Implements QDeclarativeAbstractAnimation.
Reimplemented in QDeclarativeSpringAnimation, and QDeclarativeSmoothedAnimation.
Definition at line 2406 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativePropertyAnimation);
     return d->va;
 }
setDuration()
void QDeclarativePropertyAnimation::setDuration (int duration) virtual
Reimplemented in QDeclarativeSmoothedAnimation.
Definition at line 1955 of file qdeclarativeanimation.cpp.
Referenced by QDeclarativeSmoothedAnimation::setDuration().
 {
     if (duration < 0) {
         qmlInfo(this) << tr("Cannot set a duration of < 0");
         return;
     }
     Q_D(QDeclarativePropertyAnimation);
     if (d->va->duration() == duration)
         return;
     d->va->setDuration(duration);
     emit durationChanged(duration);
 }
setEasing()
void QDeclarativePropertyAnimation::setEasing (const QEasingCurve & e)
Definition at line 2237 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativePropertyAnimation);
     if (d->va->easingCurve() == e)
         return;
     d->va->setEasingCurve(e);
     emit easingChanged(e);
 }
setFrom()
void QDeclarativePropertyAnimation::setFrom (const QVariant & f)
Definition at line 1989 of file qdeclarativeanimation.cpp.
Referenced by QDeclarativeColorAnimation::setFrom(), QDeclarativeNumberAnimation::setFrom(), QDeclarativeVector3dAnimation::setFrom(), and QDeclarativeRotationAnimation::setFrom().
 {
     Q_D(QDeclarativePropertyAnimation);
     if (d->fromIsDefined && f == d->from)
         return;
     d->from = f;
     d->fromIsDefined = f.isValid();
     emit fromChanged(f);
 }
setProperties()
void QDeclarativePropertyAnimation::setProperties (const QString & prop)
Definition at line 2283 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativePropertyAnimation);
     if (d->properties == prop)
         return;
     d->properties = prop;
     emit propertiesChanged(prop);
 }
setProperty()
void QDeclarativePropertyAnimation::setProperty (const QString & n)
Definition at line 2268 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativePropertyAnimation);
     if (d->propertyName == n)
         return;
     d->propertyName = n;
     emit propertyChanged();
 }
setTarget()
void QDeclarativePropertyAnimation::setTarget (QObject * o)
Definition at line 2253 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativePropertyAnimation);
     if (d->target == o)
         return;
     d->target = o;
     emit targetChanged();
 }
setTo()
void QDeclarativePropertyAnimation::setTo (const QVariant & t)
Definition at line 2019 of file qdeclarativeanimation.cpp.
Referenced by QDeclarativeColorAnimation::setTo(), QDeclarativeNumberAnimation::setTo(), QDeclarativeVector3dAnimation::setTo(), and QDeclarativeRotationAnimation::setTo().
 {
     Q_D(QDeclarativePropertyAnimation);
     if (d->toIsDefined && t == d->to)
         return;
     d->to = t;
     d->toIsDefined = t.isValid();
     emit toChanged(t);
 }
target()
QObject* QDeclarativePropertyAnimation::target () const
Referenced by setEasing().
targetChanged
void QDeclarativePropertyAnimation::targetChanged () signal
Referenced by setTarget().
targets()
QDeclarativeListProperty<QObject> QDeclarativePropertyAnimation::targets ()
Referenced by setProperties(), and transition().
to()
QVariant QDeclarativePropertyAnimation::to () const
Referenced by setFrom().
toChanged
void QDeclarativePropertyAnimation::toChanged (QVariant) signal
Referenced by setTo().
transition()
void QDeclarativePropertyAnimation::transition (QDeclarativeStateActions & actions, QDeclarativeProperties & modified, TransitionDirection direction) protected virtual
Reimplemented from QDeclarativeAbstractAnimation.
Reimplemented in QDeclarativeSpringAnimation, and QDeclarativeSmoothedAnimation.
Definition at line 2446 of file qdeclarativeanimation.cpp.
Referenced by QDeclarativeSmoothedAnimation::transition(), and QDeclarativeSpringAnimation::transition().
 {
     Q_D(QDeclarativePropertyAnimation);
     QStringList props = d->properties.isEmpty() ? QStringList() : d->properties.split(QLatin1Char(','));
     for (int ii = 0; ii < props.count(); ++ii)
         props[ii] = props.at(ii).trimmed();
     if (!d->propertyName.isEmpty())
         props << d->propertyName;
     QList<QObject*> targets = d->targets;
     if (d->target)
         targets.append(d->target);
     bool hasSelectors = !props.isEmpty() || !targets.isEmpty() || !d->exclude.isEmpty();
     bool useType = (props.isEmpty() && d->defaultToInterpolatorType) ? true : false;
     if (d->defaultProperty.isValid() && !hasSelectors) {
         props << d->defaultProperty.name();
         targets << d->defaultProperty.object();
     }
     if (props.isEmpty() && !d->defaultProperties.isEmpty()) {
         props << d->defaultProperties.split(QLatin1Char(','));
     }
     QDeclarativeAnimationPropertyUpdater *data = new QDeclarativeAnimationPropertyUpdater;
     data->interpolatorType = d->interpolatorType;
     data->interpolator = d->interpolator;
     data->reverse = direction == Backward ? true : false;
     data->fromSourced = false;
     data->fromDefined = d->fromIsDefined;
     bool hasExplicit = false;
     //an explicit animation has been specified
     if (d->toIsDefined) {
         for (int i = 0; i < props.count(); ++i) {
             for (int j = 0; j < targets.count(); ++j) {
                 QDeclarativeAction myAction;
                 myAction.property = d->createProperty(targets.at(j), props.at(i), this);
                 if (myAction.property.isValid()) {
                     if (d->fromIsDefined) {
                         myAction.fromValue = d->from;
                         d->convertVariant(myAction.fromValue, d->interpolatorType ? d->interpolatorType : myAction.property.propertyType());
                     }
                     myAction.toValue = d->to;
                     d->convertVariant(myAction.toValue, d->interpolatorType ? d->interpolatorType : myAction.property.propertyType());
                     data->actions << myAction;
                     hasExplicit = true;
                     for (int ii = 0; ii < actions.count(); ++ii) {
                         QDeclarativeAction &action = actions[ii];
                         if (action.property.object() == myAction.property.object() &&
                             myAction.property.name() == action.property.name()) {
                             modified << action.property;
                             break;  //### any chance there could be multiples?
                         }
                     }
                 }
             }
         }
     }
     if (!hasExplicit)
     for (int ii = 0; ii < actions.count(); ++ii) {
         QDeclarativeAction &action = actions[ii];
         QObject *obj = action.property.object();
         QString propertyName = action.property.name();
         QObject *sObj = action.specifiedObject;
         QString sPropertyName = action.specifiedProperty;
         bool same = (obj == sObj);
         if ((targets.isEmpty() || targets.contains(obj) || (!same && targets.contains(sObj))) &&
            (!d->exclude.contains(obj)) && (same || (!d->exclude.contains(sObj))) &&
            (props.contains(propertyName) || (!same && props.contains(sPropertyName))
                || (useType && action.property.propertyType() == d->interpolatorType))) {
             QDeclarativeAction myAction = action;
             if (d->fromIsDefined)
                 myAction.fromValue = d->from;
             else
                 myAction.fromValue = QVariant();
             if (d->toIsDefined)
                 myAction.toValue = d->to;
             d->convertVariant(myAction.fromValue, d->interpolatorType ? d->interpolatorType : myAction.property.propertyType());
             d->convertVariant(myAction.toValue, d->interpolatorType ? d->interpolatorType : myAction.property.propertyType());
             modified << action.property;
             data->actions << myAction;
             action.fromValue = myAction.toValue;
         }
     }
     if (data->actions.count()) {
         if (!d->rangeIsSet) {
             d->va->setStartValue(qreal(0));
             d->va->setEndValue(qreal(1));
             d->rangeIsSet = true;
         }
         d->va->setAnimValue(data, QAbstractAnimation::DeleteWhenStopped);
         d->va->setFromSourcedValue(&data->fromSourced);
         d->actions = &data->actions;
     } else {
         delete data;
         d->va->setFromSourcedValue(0);  //clear previous data
         d->va->setAnimValue(0, QAbstractAnimation::DeleteWhenStopped);  //clear previous data
         d->actions = 0;
     }
 }
Properties
duration
int QDeclarativePropertyAnimation::duration private
Definition at line 245 of file qdeclarativeanimation_p.h.
easing
QEasingCurve QDeclarativePropertyAnimation::easing private
Definition at line 248 of file qdeclarativeanimation_p.h.
exclude
QDeclarativeListProperty< QObject > QDeclarativePropertyAnimation::exclude private
Definition at line 253 of file qdeclarativeanimation_p.h.
from
QVariant QDeclarativePropertyAnimation::from private
Definition at line 246 of file qdeclarativeanimation_p.h.
properties
QString QDeclarativePropertyAnimation::properties private
Definition at line 251 of file qdeclarativeanimation_p.h.
property
QString QDeclarativePropertyAnimation::property private
Definition at line 250 of file qdeclarativeanimation_p.h.
target
QObject * QDeclarativePropertyAnimation::target private
Definition at line 249 of file qdeclarativeanimation_p.h.
targets
QDeclarativeListProperty< QObject > QDeclarativePropertyAnimation::targets private
Definition at line 252 of file qdeclarativeanimation_p.h.
to
QVariant QDeclarativePropertyAnimation::to private
Definition at line 247 of file qdeclarativeanimation_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativeanimation_p.h
/src/declarative/util/qdeclarativeanimation.cpp