Qt 4.8: QDeclarativeContents Class Reference
QDeclarativeContents Class Reference
#include <qdeclarativeitem_p.h>
Signals
void rectChanged (QRectF)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void calcGeometry ()
void childAdded (QDeclarativeItem *item)
void childRemoved (QDeclarativeItem *item)
void complete ()
QDeclarativeContents (QDeclarativeItem *item)
QRectF rectF () const
~QDeclarativeContents ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeItemChangeListener
virtual QDeclarativeAnchorsPrivate * anchorPrivate ()
virtual void itemOpacityChanged (QDeclarativeItem *)
virtual void itemSiblingOrderChanged (QDeclarativeItem *)
virtual void itemVisibilityChanged (QDeclarativeItem *)
Protected Functions
void itemDestroyed (QDeclarativeItem *item)
void itemGeometryChanged (QDeclarativeItem *item, const QRectF &newGeometry, const QRectF &oldGeometry)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void calcHeight (QDeclarativeItem *changed=0)
void calcWidth (QDeclarativeItem *changed=0)
Properties
qreal m_height
QDeclarativeItem * m_item
qreal m_width
qreal m_x
qreal m_y
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 83 of file qdeclarativeitem_p.h.
Constructors and Destructors
QDeclarativeContents()
QDeclarativeContents::QDeclarativeContents (QDeclarativeItem * item)
Definition at line 268 of file qdeclarativeitem.cpp.
                                                                  : m_item(item), m_x(0), m_y(0), m_width(0), m_height(0)
 {
     //### optimize
     connect(this, SIGNAL(rectChanged(QRectF)), m_item, SIGNAL(childrenRectChanged(QRectF)));
 }
~QDeclarativeContents()
QDeclarativeContents::~QDeclarativeContents ()
Definition at line 274 of file qdeclarativeitem.cpp.
 {
     QList<QGraphicsItem *> children = m_item->childItems();
     for (int i = 0; i < children.count(); ++i) {
         QDeclarativeItem *child = qobject_cast<QDeclarativeItem *>(children.at(i));
         if(!child)//### Should this be ignoring non-QDeclarativeItem graphicsobjects?
             continue;
         QDeclarativeItemPrivate::get(child)->removeItemChangeListener(this, QDeclarativeItemPrivate::Geometry | QDeclarativeItemPrivate::Destroyed);
     }
 }
Functions
calcGeometry()
void QDeclarativeContents::calcGeometry () inline
Definition at line 95 of file qdeclarativeitem_p.h.
Referenced by childRemoved(), complete(), and itemDestroyed().
 { calcWidth(); calcHeight(); }
calcHeight()
void QDeclarativeContents::calcHeight (QDeclarativeItem * changed = 0) private
Definition at line 290 of file qdeclarativeitem.cpp.
Referenced by calcGeometry(), childAdded(), and itemGeometryChanged().
 {
     qreal oldy = m_y;
     qreal oldheight = m_height;
     if (changed) {
         qreal top = oldy;
         qreal bottom = oldy + oldheight;
         qreal y = changed->y();
         if (y + changed->height() > bottom)
             bottom = y + changed->height();
         if (y < top)
             top = y;
         m_y = top;
         m_height = bottom - top;
     } else {
         qreal top = FLT_MAX;
         qreal bottom = 0;
         QList<QGraphicsItem *> children = m_item->childItems();
         for (int i = 0; i < children.count(); ++i) {
             QDeclarativeItem *child = qobject_cast<QDeclarativeItem *>(children.at(i));
             if(!child)//### Should this be ignoring non-QDeclarativeItem graphicsobjects?
                 continue;
             qreal y = child->y();
             if (y + child->height() > bottom)
                 bottom = y + child->height();
             if (y < top)
                 top = y;
         }
         if (!children.isEmpty())
             m_y = top;
         m_height = qMax(bottom - top, qreal(0.0));
     }
     if (m_height != oldheight || m_y != oldy)
         emit rectChanged(rectF());
 }
calcWidth()
void QDeclarativeContents::calcWidth (QDeclarativeItem * changed = 0) private
Definition at line 328 of file qdeclarativeitem.cpp.
Referenced by calcGeometry(), childAdded(), and itemGeometryChanged().
 {
     qreal oldx = m_x;
     qreal oldwidth = m_width;
     if (changed) {
         qreal left = oldx;
         qreal right = oldx + oldwidth;
         qreal x = changed->x();
         if (x + changed->width() > right)
             right = x + changed->width();
         if (x < left)
             left = x;
         m_x = left;
         m_width = right - left;
     } else {
         qreal left = FLT_MAX;
         qreal right = 0;
         QList<QGraphicsItem *> children = m_item->childItems();
         for (int i = 0; i < children.count(); ++i) {
             QDeclarativeItem *child = qobject_cast<QDeclarativeItem *>(children.at(i));
             if(!child)//### Should this be ignoring non-QDeclarativeItem graphicsobjects?
                 continue;
             qreal x = child->x();
             if (x + child->width() > right)
                 right = x + child->width();
             if (x < left)
                 left = x;
         }
         if (!children.isEmpty())
             m_x = left;
         m_width = qMax(right - left, qreal(0.0));
     }
     if (m_width != oldwidth || m_x != oldx)
         emit rectChanged(rectF());
 }
childAdded()
void QDeclarativeContents::childAdded (QDeclarativeItem * item)
Definition at line 404 of file qdeclarativeitem.cpp.
 {
     if (item)
         QDeclarativeItemPrivate::get(item)->addItemChangeListener(this, QDeclarativeItemPrivate::Geometry | QDeclarativeItemPrivate::Destroyed);
     calcWidth(item);
     calcHeight(item);
 }
childRemoved()
void QDeclarativeContents::childRemoved (QDeclarativeItem * item)
Definition at line 397 of file qdeclarativeitem.cpp.
 {
     if (item)
         QDeclarativeItemPrivate::get(item)->removeItemChangeListener(this, QDeclarativeItemPrivate::Geometry | QDeclarativeItemPrivate::Destroyed);
     calcGeometry();
 }
complete()
void QDeclarativeContents::complete ()
Definition at line 366 of file qdeclarativeitem.cpp.
Referenced by calcGeometry().
 {
     QList<QGraphicsItem *> children = m_item->childItems();
     for (int i = 0; i < children.count(); ++i) {
         QDeclarativeItem *child = qobject_cast<QDeclarativeItem *>(children.at(i));
         if(!child)//### Should this be ignoring non-QDeclarativeItem graphicsobjects?
             continue;
         QDeclarativeItemPrivate::get(child)->addItemChangeListener(this, QDeclarativeItemPrivate::Geometry | QDeclarativeItemPrivate::Destroyed);
         //###what about changes to visibility?
     }
     calcGeometry();
 }
itemDestroyed()
void QDeclarativeContents::itemDestroyed (QDeclarativeItem * item) protected virtual
Reimplemented from QDeclarativeItemChangeListener.
Definition at line 390 of file qdeclarativeitem.cpp.
Referenced by calcGeometry().
 {
     if (item)
         QDeclarativeItemPrivate::get(item)->removeItemChangeListener(this, QDeclarativeItemPrivate::Geometry | QDeclarativeItemPrivate::Destroyed);
     calcGeometry();
 }
itemGeometryChanged()
void QDeclarativeContents::itemGeometryChanged (QDeclarativeItem * item, const QRectF & newGeometry, const QRectF & oldGeometry) protected virtual
Reimplemented from QDeclarativeItemChangeListener.
Definition at line 380 of file qdeclarativeitem.cpp.
Referenced by calcGeometry().
 {
     Q_UNUSED(changed)
     //### we can only pass changed if the left edge has moved left, or the right edge has moved right
     if (newGeometry.width() != oldGeometry.width() || newGeometry.x() != oldGeometry.x())
         calcWidth(/*changed*/);
     if (newGeometry.height() != oldGeometry.height() || newGeometry.y() != oldGeometry.y())
         calcHeight(/*changed*/);
 }
rectChanged
void QDeclarativeContents::rectChanged (QRectF) signal
Referenced by calcGeometry(), calcHeight(), calcWidth(), and QDeclarativeContents().
rectF()
QRectF QDeclarativeContents::rectF () const
Definition at line 285 of file qdeclarativeitem.cpp.
Referenced by calcHeight(), and calcWidth().
 {
     return QRectF(m_x, m_y, m_width, m_height);
 }
Properties
m_height
qreal QDeclarativeContents::m_height private
Definition at line 114 of file qdeclarativeitem_p.h.
Referenced by calcHeight(), and rectF().
m_item
QDeclarativeItem* QDeclarativeContents::m_item private
Definition at line 110 of file qdeclarativeitem_p.h.
Referenced by calcHeight(), calcWidth(), complete(), QDeclarativeContents(), and ~QDeclarativeContents().
m_width
qreal QDeclarativeContents::m_width private
Definition at line 113 of file qdeclarativeitem_p.h.
Referenced by calcWidth(), and rectF().
m_x
qreal QDeclarativeContents::m_x private
Definition at line 111 of file qdeclarativeitem_p.h.
Referenced by calcWidth(), and rectF().
m_y
qreal QDeclarativeContents::m_y private
Definition at line 112 of file qdeclarativeitem_p.h.
Referenced by calcHeight(), and rectF().
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativeitem_p.h
/src/declarative/graphicsitems/qdeclarativeitem.cpp