Qt 4.8: QPatternist::XsdUserSchemaType< TSuperClass > Class Template Reference
QPatternist::XsdUserSchemaType< TSuperClass > Class Template Reference
XML Schema Processing
A base class for all user defined simple and complex types.
#include <qxsduserschematype_p.h>
Public Types
typedef QExplicitlySharedDataPointer< XsdUserSchemaType > Ptr
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
SchemaType::DerivationConstraints derivationConstraints () const
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
void setDerivationConstraints (const SchemaType::DerivationConstraints &constraints)
void setName (const QXmlName &name)
Public Functions inherited from QPatternist::NamedSchemaComponent
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Properties
SchemaType::DerivationConstraints m_derivationConstraints
QXmlName m_name
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
template<typename TSuperClass>
class QPatternist::XsdUserSchemaType< TSuperClass >
A base class for all user defined simple and complex types.
This class was introduced to combine the SchemaType class and the NamedSchemaComponent class without explicit inheritance.
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 78 of file qxsduserschematype_p.h.
Typedefs
Ptr
template<typename TSuperClass> typedef QExplicitlySharedDataPointer<XsdUserSchemaType> QPatternist::XsdUserSchemaType< TSuperClass >::Ptr
Definition at line 81 of file qxsduserschematype_p.h.
Functions
derivationConstraints()
template<typename TSuperClass > SchemaType::DerivationConstraints QPatternist::XsdUserSchemaType< TSuperClass >::derivationConstraints () const
Returns the derivation constraints of the type.
Definition at line 72 of file qxsduserschematype.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkSimpleDerivationRestrictions(), and QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints().
 {
     return m_derivationConstraints;
 }
displayName()
template<typename TSuperClass > QString QPatternist::XsdUserSchemaType< TSuperClass >::displayName (const NamePool::Ptr & namePool) const virtual
Returns the display name of the type.
Parameters
namePool The pool the name belongs to.
Reimplemented from QPatternist::NamedSchemaComponent.
Reimplemented in QPatternist::XsdComplexType, and QPatternist::XsdSimpleType.
Definition at line 60 of file qxsduserschematype.cpp.
 {
     return np->displayName(m_name);
 }
name()
template<typename TSuperClass > QXmlName QPatternist::XsdUserSchemaType< TSuperClass >::name (const NamePool::Ptr & namePool) const virtual
Returns the name of the type.
Parameters
namePool The pool the name belongs to.
Reimplemented from QPatternist::NamedSchemaComponent.
Definition at line 54 of file qxsduserschematype.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkBasicSimpleTypeConstraints(), QPatternist::XsdSchemaChecker::checkSimpleDerivationRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), and QPatternist::XsdSchemaParser::parseRedefine().
 {
     return m_name;
 }
setDerivationConstraints()
template<typename TSuperClass > void QPatternist::XsdUserSchemaType< TSuperClass >::setDerivationConstraints (const SchemaType::DerivationConstraints & constraints)
Sets the derivation constraints of the type.
Definition at line 66 of file qxsduserschematype.cpp.
Referenced by QPatternist::XsdSchemaParser::parseGlobalComplexType(), and QPatternist::XsdSchemaParser::parseGlobalSimpleType().
 {
     m_derivationConstraints = constraints;
 }
setName()
template<typename TSuperClass > void QPatternist::XsdUserSchemaType< TSuperClass >::setName (const QXmlName & name)
Sets the name of the type.
Definition at line 48 of file qxsduserschematype.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::anyType(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalSimpleType(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalSimpleType(), QPatternist::XsdSchemaParser::parseRedefine(), and QPatternist::XsdSchemaTypesFactory::XsdSchemaTypesFactory().
 {
     m_name = name;
 }
Properties
m_derivationConstraints
template<typename TSuperClass> SchemaType::DerivationConstraints QPatternist::XsdUserSchemaType< TSuperClass >::m_derivationConstraints private
Definition at line 114 of file qxsduserschematype_p.h.
m_name
template<typename TSuperClass> QXmlName QPatternist::XsdUserSchemaType< TSuperClass >::m_name private
Definition at line 113 of file qxsduserschematype_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsduserschematype_p.h
/src/xmlpatterns/schema/qxsduserschematype.cpp