Qt 4.8: QPaintDevice Class Reference
QPaintDevice Class Reference abstract
#include <qpaintdevice.h>
Public Types
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Functions
int colorCount () const
int depth () const
virtual int devType () const
virtual HDC getDC () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
virtual QPaintEngine * paintEngine () const =0
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
virtual void releaseDC (HDC hdc) const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static QWSDisplay * qwsDisplay ()
Protected Functions
virtual int metric (PaintDeviceMetric metric) const
QPaintDevice ()
Protected Variables
ushort painters
Friends
class QFontEngineMac
class QPainter
Q_GUI_EXPORT int qt_paint_device_metric (const QPaintDevice *device, PaintDeviceMetric metric)
class QX11PaintEngine
Related Functions
(Note that these are not member functions.)
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
Definition at line 60 of file qpaintdevice.h.
Enumerations
PaintDeviceMetric
enum QPaintDevice::PaintDeviceMetric
Enumerator
PdmWidth
PdmHeight
PdmWidthMM
PdmHeightMM
PdmNumColors
PdmDepth
PdmDpiX
PdmDpiY
PdmPhysicalDpiX
PdmPhysicalDpiY
Definition at line 63 of file qpaintdevice.h.
{
         PdmWidth = 1,
         PdmHeight,
         PdmWidthMM,
         PdmHeightMM,
         PdmNumColors,
         PdmDepth,
         PdmDpiX,
         PdmDpiY,
         PdmPhysicalDpiX,
         PdmPhysicalDpiY
     };
Constructors and Destructors
~QPaintDevice()
QPaintDevice::~QPaintDevice () virtual
Definition at line 53 of file qpaintdevice.cpp.
 {
     if (paintingActive())
         qWarning("QPaintDevice: Cannot destroy paint device that is being "
                   "painted");
     qt_painter_removePaintDevice(this);
 }
QPaintDevice()
QPaintDevice::QPaintDevice () protected
Definition at line 48 of file qpaintdevice.cpp.
Referenced by QPixmap::handle(), QImage::QImage(), and QWidget::QWidget().
 {
     painters = 0;
 }
Functions
colorCount()
int QPaintDevice::colorCount () const inline
Definition at line 102 of file qpaintdevice.h.
Referenced by QImage::copy().
 { return metric(PdmNumColors); }
depth()
int QPaintDevice::depth () const inline
Definition at line 103 of file qpaintdevice.h.
Referenced by QImage::copy(), QGLOverlayWidget::paintGL(), QRasterBuffer::prepare(), QPaintBuffer::processCommands(), QPixmap::swap(), and QETWidget::updateRegion().
 { return metric(PdmDepth); }
devType()
int QPaintDevice::devType () const inline virtual
Reimplemented in QCustomRasterPaintDevice, QWidget, QMacQuartzPaintDevice, QImage, QGLFramebufferObject, QGLPixelBuffer, QPixmap, QPaintBuffer, EAGLPaintDevice, QPrinter, QGLPaintDevice, and QPicture.
Definition at line 167 of file qpaintdevice.h.
Referenced by QPainterPrivate::attachPainterPrivate(), QDirectFBPaintEngine::begin(), QMacPrintEngine::begin(), QOpenGLPaintEngine::begin(), QX11PaintEngine::begin(), QGL2PaintEngineEx::begin(), QPainter::begin(), QRasterPaintEngine::begin(), QWindowSurface::buffer(), buildSpec(), QGLGlyphCache::cacheGlyphs(), QX11Info::cloneX11Data(), QX11Info::copyX11Data(), QEgl::createSurface(), QPixmapConvolutionFilter::draw(), QWindowsXPStylePrivate::drawBackground(), QRasterPaintEngine::drawCachedGlyphs(), QWidgetPrivate::drawWidget(), QEgl::eglSwapBuffersRegion2NOK(), QGLPaintDevice::getDevice(), glScreenForDevice(), QPainterState::init(), QFont::QFont(), QMacCGContext::QMacCGContext(), qt_egl_create_surface(), qt_mac_cg_context(), qt_mac_colorSpaceForDeviceType(), qt_mac_qd_context(), qt_x11Handle(), qt_x11Info(), QPainter::redirected(), QGraphicsScene::render(), QGraphicsView::render(), QWidget::render(), QWidgetPrivate::render(), screenForDevice(), QGLOffscreen::setDevice(), QEglProperties::setPaintDeviceFormat(), QEglProperties::setVisualFormat(), QPixmap::swap(), and QImage::swap().
 { return QInternal::UnknownDevice; }
getDC()
HDC QPaintDevice::getDC () const virtual
Warning
This function is not part of the public interface.
Reimplemented in QWidget, and QPrinter.
Definition at line 53 of file qpaintdevice_win.cpp.
Referenced by QFont::QFont().
 {
     return 0;
 }
height()
int QPaintDevice::height () const inline
Definition at line 92 of file qpaintdevice.h.
Referenced by areaDiff(), QX11PaintEngine::begin(), QGLFramebufferObject::blitFramebuffer(), QVGPaintEngine::clearRect(), QVGPaintEngine::clip(), QImage::copy(), QVGPaintEngine::defaultClipRegion(), QPainterPrivate::draw_helper(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QPainterPrivate::drawStretchedGradient(), QEmulationPaintEngine::drawTextItem(), QCoreGraphicsPaintEngine::drawTextItem(), QPSPrintEnginePrivate::emitHeader(), QEmulationPaintEngine::fill(), fillRegion(), QGLWindowSurface::flush(), QVGPaintEngine::isDefaultClipRect(), QVGPaintEngine::isDefaultClipRegion(), QSvgTinyDocument::mapSourceToTarget(), QDirectFBPaintDevice::metric(), QVGPaintEnginePrivate::modifyMask(), QDeclarativePaintedItem::paint(), QRasterBuffer::prepare(), QGLFramebufferObject::QGLFramebufferObject(), QGraphicsScene::render(), QGraphicsView::render(), QWidgetPrivate::render_helper(), ShaderEffectItem::renderEffect(), QGLWindowSurface::scroll(), QEmulationPaintEngine::stroke(), QPixmap::swap(), QGLWindowSurface::updateGeometry(), ShaderEffect::updateRenderTargets(), QVGPaintEngine::updateScissor(), and QVGPaintEnginePrivate::updateTransform().
 { return metric(PdmHeight); }
heightMM()
int QPaintDevice::heightMM () const inline
Definition at line 94 of file qpaintdevice.h.
Referenced by QPSPrintEnginePrivate::emitHeader().
 { return metric(PdmHeightMM); }
logicalDpiX()
int QPaintDevice::logicalDpiX () const inline
Definition at line 95 of file qpaintdevice.h.
Referenced by QAxClientSite::activateObject(), QAlphaPaintEnginePrivate::drawAlphaImage(), QPicture::exec(), menuItemEntry(), QAxClientSite::minimumSizeHint(), QAxHostWidget::resizeObject(), QPainterReplayer::setupTransform(), and QTiffHandler::write().
 { return metric(PdmDpiX); }
logicalDpiY()
int QPaintDevice::logicalDpiY () const inline
Definition at line 96 of file qpaintdevice.h.
Referenced by QAxClientSite::activateObject(), QTextDocumentLayoutPrivate::blockIndent(), QTextEngine::calculateTabWidth(), QAlphaPaintEnginePrivate::drawAlphaImage(), QPicture::exec(), getImageSize(), getPixmapSize(), menuItemEntry(), QAxClientSite::minimumSizeHint(), QFont::QFont(), QFontMetrics::QFontMetrics(), QFontMetricsF::QFontMetricsF(), QAxHostWidget::resizeObject(), QTextDocumentLayoutPrivate::scaleToDevice(), QPainterReplayer::setupTransform(), QPrintPreviewWidget::setViewMode(), and QTiffHandler::write().
 { return metric(PdmDpiY); }
metric()
int QPaintDevice::metric (PaintDeviceMetric metric) const protected virtual
Reimplemented in QFakeDevice, QWidget, QCustomRasterPaintDevice, QFakeDevice, QImage, QPrinter, QPixmap, QMacQuartzPaintDevice, QGLFramebufferObject, QPicture, QGLPixelBuffer, QSvgGenerator, QPaintBuffer, QVGWindowSurface, QDirectFBPixmapData, QGLPaintDevice, QGLWindowSurfaceGLPaintDevice, QDirectFBPaintDevice, and ShivaVGWindowSurface.
Definition at line 63 of file qpaintdevice.cpp.
Referenced by QPainter::begin(), QGLPaintDevice::devType(), effectiveState(), QImage::fromData(), QPaintBuffer::metric(), QFakeDevice::metric(), QWidget::metric(), QPixmap::operator!(), qt_paint_device_metric(), and QPicture::swap().
 {
     qWarning("QPaintDevice::metrics: Device has no metric information");
     return 0;
 }
numColors()
QT_DEPRECATED int QPaintDevice::numColors () const inline
Definition at line 100 of file qpaintdevice.h.
Referenced by QImage::copy(), QDirectFBPaintDevice::metric(), and QApplication::qwsSetCustomColors().
 { return metric(PdmNumColors); }
paintEngine()
virtual QPaintEngine* QPaintDevice::paintEngine () const pure virtual
Implemented in QFakeDevice, QWidget, QGLWidget, QFakeDevice, QImage, QMacQuartzPaintDevice, QPrinter, QPixmap, QGLPBufferGLPaintDevice, QAxHostWidget, QGLFBOGLPaintDevice, QGLFramebufferObject, QPicture, QSvgGenerator, QGLPixelBuffer, QGLWidgetGLPaintDevice, QGLPixmapGLPaintDevice, QPaintBuffer, EAGLPaintDevice, QVGWindowSurface, QX11GLPixmapData, QDirectFBPixmapData, QGLWindowSurfaceGLPaintDevice, QDirectFBPaintDevice, ShivaVGWindowSurface, QEglFSPaintDevice, and QBBGLPaintDevice.
Referenced by QPainter::begin(), QWidgetPrivate::drawWidget(), QImage::fromData(), QWidgetBackingStore::removeDirtyWidget(), QWidgetPrivate::render(), and QPicture::swap().
paintingActive()
bool QPaintDevice::paintingActive () const inline
Definition at line 170 of file qpaintdevice.h.
Referenced by QPixmap::fill(), make_widget_eventUPP(), QPixmap::operator=(), QImage::operator=(), QImage::QImage(), QPixmap::QPixmap(), QPicture::save(), QPixmap::setAlphaChannel(), QPixmap::setMask(), ~QPaintDevice(), and QWidget::~QWidget().
 { return painters != 0; }
physicalDpiX()
int QPaintDevice::physicalDpiX () const inline
Definition at line 97 of file qpaintdevice.h.
 { return metric(PdmPhysicalDpiX); }
physicalDpiY()
int QPaintDevice::physicalDpiY () const inline
Definition at line 98 of file qpaintdevice.h.
 { return metric(PdmPhysicalDpiY); }
qwsDisplay()
QWSDisplay * QPaintDevice::qwsDisplay () static
Warning
This function is not part of the public interface.
Definition at line 51 of file qpaintdevice_qws.cpp.
Referenced by effectiveState(), QWSDisplay::Data::fillQueue(), QWSWindowSurface::flush(), QWSYellowSurface::flush(), isServerProcess(), QDirectPainter::lower(), QWSInputContext::mouseHandler(), parseGeometry(), qwsClipboardText(), QWSDirectPainterSurface::QWSDirectPainterSurface(), qwsInitClipboard(), QApplication::qwsProcessEvent(), qwsSetClipboardText(), QWSYellowSurface::QWSYellowSurface(), QDirectPainter::raise(), QWSInputContext::reset(), QWidget::setAttribute(), QWSInputContext::setFocusWidget(), QWSWindowSurface::setGeometry(), QWSDirectPainterSurface::setRegion(), QWSInputContext::translateIMQueryEvent(), QWSInputContext::update(), QDirectPainterPrivate::~QDirectPainterPrivate(), and QWSDirectPainterSurface::~QWSDirectPainterSurface().
 {
     return qt_fbdpy;
 }
releaseDC()
void QPaintDevice::releaseDC (HDC hdc) const virtual
Warning
This function is not part of the public interface.
Reimplemented in QWidget, and QPrinter.
Definition at line 58 of file qpaintdevice_win.cpp.
 {
 }
width()
int QPaintDevice::width () const inline
Definition at line 91 of file qpaintdevice.h.
Referenced by areaDiff(), QX11PaintEngine::begin(), QVGPaintEngine::clip(), QImage::copy(), QVGPaintEngine::defaultClipRegion(), QPainterPrivate::draw_helper(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QPainterPrivate::drawStretchedGradient(), QEmulationPaintEngine::drawTextItem(), QPSPrintEnginePrivate::emitHeader(), QEmulationPaintEngine::fill(), fillRegion(), QGLWindowSurface::flush(), QVGPaintEngine::isDefaultClipRect(), QVGPaintEngine::isDefaultClipRegion(), QSvgTinyDocument::mapSourceToTarget(), QDirectFBPaintDevice::metric(), QVGPaintEnginePrivate::modifyMask(), QDeclarativePaintedItem::paint(), QRasterBuffer::prepare(), QGLFramebufferObject::QGLFramebufferObject(), QGraphicsScene::render(), QGraphicsView::render(), QWidgetPrivate::render_helper(), ShaderEffectItem::renderEffect(), QEmulationPaintEngine::stroke(), QPixmap::swap(), QGLWindowSurface::updateGeometry(), ShaderEffect::updateRenderTargets(), and QVGPaintEngine::updateScissor().
 { return metric(PdmWidth); }
widthMM()
int QPaintDevice::widthMM () const inline
Definition at line 93 of file qpaintdevice.h.
Referenced by QPSPrintEnginePrivate::emitHeader().
 { return metric(PdmWidthMM); }
Friends and Related Functions
QFontEngineMac
friend class QFontEngineMac friend
Definition at line 141 of file qpaintdevice.h.
QPainter
friend class QPainter friend
Definition at line 140 of file qpaintdevice.h.
qt_paint_device_metric
Q_GUI_EXPORT int qt_paint_device_metric (const QPaintDevice * device, QPaintDevice::PaintDeviceMetric metric) friend
Definition at line 70 of file qpaintdevice.cpp.
Referenced by ShivaVGWindowSurface::metric(), and QVGWindowSurface::metric().
 {
     return device->metric(metric);
 }
qt_x11Info()
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice * pd) related
Returns the QX11Info structure for the pd paint device.
0 is returned if it can't be obtained.
Definition at line 80 of file qpaintdevice_x11.cpp.
 {
     if (!pd) return 0;
     if (pd->devType() == QInternal::Widget)
         return &static_cast<const QWidget *>(pd)->x11Info();
     else if (pd->devType() == QInternal::Pixmap)
         return &static_cast<const QPixmap *>(pd)->x11Info();
     return 0;
 }
QX11PaintEngine
friend class QX11PaintEngine friend
Definition at line 142 of file qpaintdevice.h.
Properties
painters
ushort QPaintDevice::painters protected
Definition at line 109 of file qpaintdevice.h.
Referenced by QPainter::begin(), and QPaintDevice().
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintdevice.h
/src/gui/painting/qpaintdevice.cpp
/src/gui/painting/qpaintdevice_qpa.cpp
/src/gui/painting/qpaintdevice_qws.cpp
/src/gui/painting/qpaintdevice_win.cpp
/src/gui/painting/qpaintdevice_x11.cpp
/src/gui/painting/qpainter.cpp