Qt 4.8: QStateMachine Class Reference
QStateMachine Class Reference
The QStateMachine class provides a hierarchical finite state machine.
#include <qstatemachine.h>
Classes
class SignalEvent
The SignalEvent class represents a Qt signal event.
class WrappedEvent
The WrappedEvent class inherits QEvent and holds a clone of an event associated with a QObject.
Public Types
enum Error { NoError, NoInitialStateError, NoDefaultStateInHistoryStateError, NoCommonAncestorForTransitionError }
This enum type defines errors that can occur in the state machine at run time.
enum EventPriority { NormalPriority, HighPriority }
This enum type specifies the priority of an event posted to the state machine using postEvent().
enum RestorePolicy { DontRestoreProperties, RestoreProperties }
This enum specifies the restore policy type.
Public Types inherited from QState
enum ChildMode { ExclusiveStates, ParallelStates }
This enum specifies how a state's child states are treated.
Public Slots
void start ()
Starts this state machine.
void stop ()
Stops this state machine.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void started ()
This signal is emitted when the state machine has entered its initial state (QStateMachine::initialState).
void stopped ()
This signal is emitted when the state machine has stopped.
Signals inherited from QState
void finished ()
This signal is emitted when a final child state of this state is entered.
void propertiesAssigned ()
This signal is emitted when all properties have been assigned their final value.
Signals inherited from QAbstractState
void entered ()
This signal is emitted when the state has been entered (after onEntry() has been called).
void exited ()
This signal is emitted when the state has been exited (after onExit() has been called).
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addDefaultAnimation (QAbstractAnimation *animation)
Adds a default animation to be considered for any transition.
void addState (QAbstractState *state)
Adds the given state to this state machine.
bool cancelDelayedEvent (int id)
Cancels the delayed event identified by the given id.
void clearError ()
Clears the error string and error code of the state machine.
QSet< QAbstractState * > configuration () const
Returns the maximal consistent set of states (including parallel and final states) that this state machine is currently in.
QList< QAbstractAnimation * > defaultAnimations () const
Returns the list of default animations that will be considered for any transition.
Error error () const
Returns the error code of the last error that occurred in the state machine.
QString errorString () const
bool eventFilter (QObject *watched, QEvent *event)
Reimplemented Function
QStateMachine::RestorePolicy globalRestorePolicy () const
bool isAnimated () const
Returns whether animations are enabled for this state machine.
bool isRunning () const
Returns whether this state machine is running.
int postDelayedEvent (QEvent *event, int delay)
Posts the given event for processing by this state machine, with the given delay in milliseconds.
void postEvent (QEvent *event, EventPriority priority=NormalPriority)
Posts the given event of the given priority for processing by this state machine.
QStateMachine (QObject *parent=0)
Constructs a new state machine with the given parent.
void removeDefaultAnimation (QAbstractAnimation *animation)
Removes animation from the list of default animations.
void removeState (QAbstractState *state)
Removes the given state from this state machine.
void setAnimated (bool enabled)
Sets whether animations are enabled for this state machine.
void setGlobalRestorePolicy (QStateMachine::RestorePolicy restorePolicy)
Sets the restore policy of the state machine to restorePolicy.
~QStateMachine ()
Destroys this state machine.
Public Functions inherited from QState
void addTransition (QAbstractTransition *transition)
Adds the given transition.
QSignalTransition * addTransition (QObject *sender, const char *signal, QAbstractState *target)
Adds a transition associated with the given signal of the given sender object, and returns the new QSignalTransition object.
QAbstractTransition * addTransition (QAbstractState *target)
Adds an unconditional transition from this state to the given target state, and returns then new transition object.
void assignProperty (QObject *object, const char *name, const QVariant &value)
Instructs this state to set the property with the given name of the given object to the given value when the state is entered.
ChildMode childMode () const
QAbstractState * errorState () const
QAbstractState * initialState () const
QState (QState *parent=0)
Constructs a new state with the given parent state.
QState (ChildMode childMode, QState *parent=0)
Constructs a new state with the given childMode and the given parent state.
void removeTransition (QAbstractTransition *transition)
Removes the given transition from this state.
void setChildMode (ChildMode mode)
Sets the child mode of this state.
void setErrorState (QAbstractState *state)
Sets this state's error state to be the given state.
void setInitialState (QAbstractState *state)
Sets this state's initial state to be the given state.
QList< QAbstractTransition * > transitions () const
Returns this state's outgoing transitions (i.
~QState ()
Destroys this state.
Public Functions inherited from QAbstractState
QStateMachine * machine () const
Returns the state machine that this state is part of, or 0 if the state is not part of a state machine.
QState * parentState () const
Returns this state's parent state, or 0 if the state has no parent state.
~QAbstractState ()
Destroys this state.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual void beginMicrostep (QEvent *event)
This function is called when the state machine is about to do a microstep.
virtual void beginSelectTransitions (QEvent *event)
This function is called when the state machine is about to select transitions based on the given event.
virtual void endMicrostep (QEvent *event)
This function is called when the state machine has finished doing a microstep.
virtual void endSelectTransitions (QEvent *event)
This function is called when the state machine has finished selecting transitions based on the given event.
bool event (QEvent *e)
Reimplemented Function
void onEntry (QEvent *event)
This function will call start() to start the state machine.
void onExit (QEvent *event)
This function will call stop() to stop the state machine and subsequently emit the stopped() signal.
QStateMachine (QStateMachinePrivate &dd, QObject *parent)
Protected Functions inherited from QState
QState (QStatePrivate &dd, QState *parent)
Protected Functions inherited from QAbstractState
QAbstractState (QState *parent=0)
Constructs a new state with the given parent state.
QAbstractState (QAbstractStatePrivate &dd, QState *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
bool animated
whether animations are enabled
QString errorString
the error string of this state machine
RestorePolicy globalRestorePolicy
the restore policy for states of this state machine.
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QStateMachine class provides a hierarchical finite state machine.
Note
This class or function is reentrant.
Since
4.6
QStateMachine is based on the concepts and notation of Statecharts: A visual formalism for complex systems{Statecharts}. QStateMachine is part of The State Machine Framework.
A state machine manages a set of states (classes that inherit from QAbstractState) and transitions (descendants of QAbstractTransition) between those states; these states and transitions define a state graph. Once a state graph has been built, the state machine can execute it. QStateMachine's execution algorithm is based on the State Chart XML: State Machine Notation for Control Abstraction{State Chart XML (SCXML)} algorithm. The framework's The State Machine Framework{overview} gives several state graphs and the code to build them.
Use the addState() function to add a top-level state to the state machine. States are removed with the removeState() function. Removing states while the machine is running is discouraged.
Before the machine can be started, the initial state must be set. The initial state is the state that the machine enters when started. You can then start() the state machine. The started() signal is emitted when the initial state is entered.
The machine is event driven and keeps its own event loop. Events are posted to the machine through postEvent(). Note that this means that it executes asynchronously, and that it will not progress without a running event loop. You will normally not have to post events to the machine directly as Qt's transitions, e.g., QEventTransition and its subclasses, handle this. But for custom transitions triggered by events, postEvent() is useful.
The state machine processes events and takes transitions until a top-level final state is entered; the state machine then emits the finished() signal. You can also stop() the state machine explicitly. The stopped() signal is emitted in this case.
The following snippet shows a state machine that will finish when a button is clicked:
QPushButton button;
QStateMachine machine;
QState *s1 = new QState();
s1->assignProperty(&button, "text", "Click me");
QFinalState *s2 = new QFinalState();
s1->addTransition(&button, SIGNAL(clicked()), s2);
machine.addState(s1);
machine.addState(s2);
machine.setInitialState(s1);
machine.start();
This code example uses QState, which inherits QAbstractState. The QState class provides a state that you can use to set properties and invoke methods on QObject when the state is entered or exited. It also contains convenience functions for adding transitions, e.g., QSignalTransition as in this example. See the QState class description for further details.
If an error is encountered, the machine will look for an error state, and if one is available, it will enter this state. The types of errors possible are described by the QStateMachine::Error enum. After the error state is entered, the type of the error can be retrieved with error(). The execution of the state graph will not stop when the error state is entered. If no error state applies to the erroneous state, the machine will stop executing and an error message will be printed to the console.
See also
QAbstractState, QAbstractTransition, QState, {The State Machine Framework}
Definition at line 63 of file qstatemachine.h.
Enumerations
Error
enum QStateMachine::Error
This enum type defines errors that can occur in the state machine at run time.
When the state machine encounters an unrecoverable error at run time, it will set the error code returned by error(), the error message returned by errorString(), and enter an error state based on the context of the error.
NoError No error has occurred.
NoInitialStateError The machine has entered a QState with children which does not have an initial state set. The context of this error is the state which is missing an initial state.
NoDefaultStateInHistoryStateError The machine has entered a QHistoryState which does not have a default state set. The context of this error is the QHistoryState which is missing a default state.
NoCommonAncestorForTransitionError The machine has selected a transition whose source and targets are not part of the same tree of states, and thus are not part of the same state machine. Commonly, this could mean that one of the states has not been given any parent or added to any machine. The context of this error is the source state of the transition.
See also
setErrorState()
Enumerator
NoError
NoInitialStateError
NoDefaultStateInHistoryStateError
NoCommonAncestorForTransitionError
Definition at line 116 of file qstatemachine.h.
                {
         NoError,
         NoInitialStateError,
         NoDefaultStateInHistoryStateError,
         NoCommonAncestorForTransitionError
     };
EventPriority
enum QStateMachine::EventPriority
This enum type specifies the priority of an event posted to the state machine using postEvent().
Events of high priority are processed before events of normal priority.
NormalPriority The event has normal priority.
HighPriority The event has high priority.
Enumerator
NormalPriority
HighPriority
Definition at line 106 of file qstatemachine.h.
{
         NormalPriority,
         HighPriority
     };
RestorePolicy
enum QStateMachine::RestorePolicy
This enum specifies the restore policy type.
The restore policy takes effect when the machine enters a state which sets one or more properties. If the restore policy is set to RestoreProperties, the state machine will save the original value of the property before the new value is set.
Later, when the machine either enters a state which does not set a value for the given property, the property will automatically be restored to its initial value.
Only one initial value will be saved for any given property. If a value for a property has already been saved by the state machine, it will not be overwritten until the property has been successfully restored.
DontRestoreProperties The state machine should not save the initial values of properties and restore them later.
RestoreProperties The state machine should save the initial values of properties and restore them later.
See also
QStateMachine::globalRestorePolicy QState::assignProperty()
Enumerator
DontRestoreProperties
RestoreProperties
Definition at line 111 of file qstatemachine.h.
{
         DontRestoreProperties,
         RestoreProperties
     };
Constructors and Destructors
QStateMachine() [1/2]
QStateMachine::QStateMachine (QObject * parent = 0)
Constructs a new state machine with the given parent.
Definition at line 1685 of file qstatemachine.cpp.
     : QState(*new QStateMachinePrivate, /*parentState=*/0)
 {
     // Can't pass the parent to the QState constructor, as it expects a QState
     // But this works as expected regardless of whether parent is a QState or not
     setParent(parent);
 }
~QStateMachine()
QStateMachine::~QStateMachine ()
Destroys this state machine.
Definition at line 1705 of file qstatemachine.cpp.
 {
 }
QStateMachine() [2/2]
QStateMachine::QStateMachine (QStateMachinePrivate & dd, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 1696 of file qstatemachine.cpp.
     : QState(dd, /*parentState=*/0)
 {
     setParent(parent);
 }
Functions
addDefaultAnimation()
void QStateMachine::addDefaultAnimation (QAbstractAnimation * animation)
Adds a default animation to be considered for any transition.
Definition at line 2244 of file qstatemachine.cpp.
 {
     Q_D(QStateMachine);
     d->defaultAnimations.append(animation);
 }
addState()
void QStateMachine::addState (QAbstractState * state)
Adds the given state to this state machine.
The state becomes a top-level state.
If the state is already in a different machine, it will first be removed from its old machine, and then added to this machine.
See also
removeState(), setInitialState()
Definition at line 1839 of file qstatemachine.cpp.
 {
     if (!state) {
         qWarning("QStateMachine::addState: cannot add null state");
         return;
     }
     if (QAbstractStatePrivate::get(state)->machine() == this) {
         qWarning("QStateMachine::addState: state has already been added to this machine");
         return;
     }
     state->setParent(this);
 }
beginMicrostep()
void QStateMachine::beginMicrostep (QEvent * event) protected virtual
This function is called when the state machine is about to do a microstep.
Warning
This function is not part of the public interface.
The default implementation does nothing.
Definition at line 2173 of file qstatemachine.cpp.
 {
     Q_UNUSED(event);
 }
beginSelectTransitions()
void QStateMachine::beginSelectTransitions (QEvent * event) protected virtual
This function is called when the state machine is about to select transitions based on the given event.
Warning
This function is not part of the public interface.
The default implementation does nothing.
Definition at line 2142 of file qstatemachine.cpp.
 {
     Q_UNUSED(event);
 }
cancelDelayedEvent()
bool QStateMachine::cancelDelayedEvent (int id)
Cancels the delayed event identified by the given id.
Note
This class or function is threadsafe.
The id should be a value returned by a call to postDelayedEvent(). Returns true if the event was successfully cancelled, otherwise returns false.
See also
postDelayedEvent()
Definition at line 2037 of file qstatemachine.cpp.
 {
     Q_D(QStateMachine);
     if (d->state != QStateMachinePrivate::Running) {
         qWarning("QStateMachine::cancelDelayedEvent: the machine is not running");
         return false;
     }
     QMutexLocker locker(&d->delayedEventsMutex);
     QEvent *e = d->delayedEvents.take(id);
     if (!e)
         return false;
     killTimer(id);
     delete e;
     return true;
 }
clearError()
void QStateMachine::clearError ()
Clears the error string and error code of the state machine.
Definition at line 1800 of file qstatemachine.cpp.
 {
     Q_D(QStateMachine);
     d->errorString.clear();
     d->error = NoError;
 }
configuration()
QSet< QAbstractState * > QStateMachine::configuration () const
Returns the maximal consistent set of states (including parallel and final states) that this state machine is currently in.
If a state s is in the configuration, it is always the case that the parent of s is also in c. Note, however, that the machine itself is not an explicit member of the configuration.
Definition at line 2060 of file qstatemachine.cpp.
 {
     Q_D(const QStateMachine);
     return d->configuration;
 }
defaultAnimations()
QList< QAbstractAnimation * > QStateMachine::defaultAnimations () const
Returns the list of default animations that will be considered for any transition.
Definition at line 2253 of file qstatemachine.cpp.
 {
     Q_D(const QStateMachine);
     return d->defaultAnimations;
 }
endMicrostep()
void QStateMachine::endMicrostep (QEvent * event) protected virtual
This function is called when the state machine has finished doing a microstep.
Warning
This function is not part of the public interface.
The default implementation does nothing.
Definition at line 2189 of file qstatemachine.cpp.
 {
     Q_UNUSED(event);
 }
endSelectTransitions()
void QStateMachine::endSelectTransitions (QEvent * event) protected virtual
This function is called when the state machine has finished selecting transitions based on the given event.
Warning
This function is not part of the public interface.
The default implementation does nothing.
Definition at line 2158 of file qstatemachine.cpp.
 {
     Q_UNUSED(event);
 }
error()
QStateMachine::Error QStateMachine::error () const
Returns the error code of the last error that occurred in the state machine.
Definition at line 1782 of file qstatemachine.cpp.
 {
     Q_D(const QStateMachine);
     return d->error;
 }
errorString()
QString QStateMachine::errorString () const
Referenced by error().
event()
bool QStateMachine::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QState.
Definition at line 2092 of file qstatemachine.cpp.
Referenced by postDelayedEvent(), and postEvent().
 {
     Q_D(QStateMachine);
     if (e->type() == QEvent::Timer) {
         QTimerEvent *te = static_cast<QTimerEvent*>(e);
         int tid = te->timerId();
         if (d->state != QStateMachinePrivate::Running) {
             // This event has been cancelled already
             QMutexLocker locker(&d->delayedEventsMutex);
             Q_ASSERT(!d->delayedEvents.contains(tid));
             return true;
         }
         d->delayedEventsMutex.lock();
         QEvent *ee = d->delayedEvents.take(tid);
         if (ee != 0) {
             killTimer(tid);
             d->delayedEventsMutex.unlock();
             d->postExternalEvent(ee);
             d->processEvents(QStateMachinePrivate::DirectProcessing);
             return true;
         } else {
             d->delayedEventsMutex.unlock();
         }
     }
     return QState::event(e);
 }
eventFilter()
bool QStateMachine::eventFilter (QObject * watched, QEvent * event) virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 2123 of file qstatemachine.cpp.
 {
     Q_D(QStateMachine);
     d->handleFilteredEvent(watched, event);
     return false;
 }
globalRestorePolicy()
QStateMachine::RestorePolicy QStateMachine::globalRestorePolicy () const
Referenced by clearError().
isAnimated()
bool QStateMachine::isAnimated () const
Returns whether animations are enabled for this state machine.
Definition at line 2226 of file qstatemachine.cpp.
 {
     Q_D(const QStateMachine);
     return d->animated;
 }
isRunning()
bool QStateMachine::isRunning () const
Returns whether this state machine is running.
start(), stop()
Definition at line 1878 of file qstatemachine.cpp.
 {
     Q_D(const QStateMachine);
     return (d->state == QStateMachinePrivate::Running);
 }
onEntry()
void QStateMachine::onEntry (QEvent * event) protected virtual
This function will call start() to start the state machine.
Reimplemented Function
Reimplemented from QState.
Definition at line 2201 of file qstatemachine.cpp.
 {
     start();
     QState::onEntry(event);
 }
onExit()
void QStateMachine::onExit (QEvent * event) protected virtual
This function will call stop() to stop the state machine and subsequently emit the stopped() signal.
Reimplemented Function
Reimplemented from QState.
Definition at line 2215 of file qstatemachine.cpp.
 {
     stop();
     QState::onExit(event);
 }
postDelayedEvent()
int QStateMachine::postDelayedEvent (QEvent * event, int delay)
Posts the given event for processing by this state machine, with the given delay in milliseconds.
Note
This class or function is threadsafe.
Returns an identifier associated with the delayed event, or -1 if the event could not be posted.
This function returns immediately. When the delay has expired, the event will be added to the state machine's event queue for processing. The state machine takes ownership of the event and deletes it once it has been processed.
You can only post events when the state machine is running.
See also
cancelDelayedEvent(), postEvent()
Definition at line 2001 of file qstatemachine.cpp.
 {
     Q_D(QStateMachine);
     if (d->state != QStateMachinePrivate::Running) {
         qWarning("QStateMachine::postDelayedEvent: cannot post event when the state machine is not running");
         return -1;
     }
     if (!event) {
         qWarning("QStateMachine::postDelayedEvent: cannot post null event");
         return -1;
     }
     if (delay < 0) {
         qWarning("QStateMachine::postDelayedEvent: delay cannot be negative");
         return -1;
     }
 #ifdef QSTATEMACHINE_DEBUG
     qDebug() << this << ": posting event" << event << "with delay" << delay;
 #endif
     QMutexLocker locker(&d->delayedEventsMutex);
     int tid = startTimer(delay);
     d->delayedEvents[tid] = event;
     return tid;
 }
postEvent()
void QStateMachine::postEvent (QEvent * event, EventPriority priority = NormalPriority)
Posts the given event of the given priority for processing by this state machine.
Note
This class or function is threadsafe.
This function returns immediately. The event is added to the state machine's event queue. Events are processed in the order posted. The state machine takes ownership of the event and deletes it once it has been processed.
You can only post events when the state machine is running.
See also
postDelayedEvent()
Definition at line 1957 of file qstatemachine.cpp.
 {
     Q_D(QStateMachine);
     if (d->state != QStateMachinePrivate::Running) {
         qWarning("QStateMachine::postEvent: cannot post event when the state machine is not running");
         return;
     }
     if (!event) {
         qWarning("QStateMachine::postEvent: cannot post null event");
         return;
     }
 #ifdef QSTATEMACHINE_DEBUG
     qDebug() << this << ": posting event" << event;
 #endif
     switch (priority) {
     case NormalPriority:
         d->postExternalEvent(event);
         break;
     case HighPriority:
         d->postInternalEvent(event);
         break;
     }
     d->processEvents(QStateMachinePrivate::QueuedProcessing);
 }
removeDefaultAnimation()
void QStateMachine::removeDefaultAnimation (QAbstractAnimation * animation)
Removes animation from the list of default animations.
Definition at line 2262 of file qstatemachine.cpp.
 {
     Q_D(QStateMachine);
     d->defaultAnimations.removeAll(animation);
 }
removeState()
void QStateMachine::removeState (QAbstractState * state)
Removes the given state from this state machine.
The state machine releases ownership of the state.
See also
addState()
Definition at line 1858 of file qstatemachine.cpp.
 {
     if (!state) {
         qWarning("QStateMachine::removeState: cannot remove null state");
         return;
     }
     if (QAbstractStatePrivate::get(state)->machine() != this) {
         qWarning("QStateMachine::removeState: state %p's machine (%p)"
                  " is different from this machine (%p)",
                  state, QAbstractStatePrivate::get(state)->machine(), this);
         return;
     }
     state->setParent(0);
 }
setAnimated()
void QStateMachine::setAnimated (bool enabled)
Sets whether animations are enabled for this state machine.
Definition at line 2235 of file qstatemachine.cpp.
 {
     Q_D(QStateMachine);
     d->animated = enabled;
 }
setGlobalRestorePolicy()
void QStateMachine::setGlobalRestorePolicy (QStateMachine::RestorePolicy restorePolicy)
Sets the restore policy of the state machine to restorePolicy.
The default restore policy is QAbstractState::DontRestoreProperties.
See also
globalRestorePolicy()
Definition at line 1824 of file qstatemachine.cpp.
 {
     Q_D(QStateMachine);
     d->globalRestorePolicy = restorePolicy;
 }
start
void QStateMachine::start () slot
Starts this state machine.
The machine will reset its configuration and transition to the initial state. When a final top-level state (QFinalState) is entered, the machine will emit the finished() signal.
Note
A state machine will not run without a running event loop, such as the main application event loop started with QCoreApplication::exec() or QApplication::exec().
See also
started(), finished(), stop(), initialState()
Definition at line 1895 of file qstatemachine.cpp.
Referenced by onEntry().
 {
     Q_D(QStateMachine);
     if (initialState() == 0) {
         qWarning("QStateMachine::start: No initial state set for machine. Refusing to start.");
         return;
     }
     switch (d->state) {
     case QStateMachinePrivate::NotRunning:
         d->state = QStateMachinePrivate::Starting;
         QMetaObject::invokeMethod(this, "_q_start", Qt::QueuedConnection);
         break;
     case QStateMachinePrivate::Starting:
         break;
     case QStateMachinePrivate::Running:
         qWarning("QStateMachine::start(): already running");
         break;
     }
 }
started
QStateMachine::started () signal
This signal is emitted when the state machine has entered its initial state (QStateMachine::initialState).
See also
QStateMachine::finished(), QStateMachine::start()
stop
void QStateMachine::stop () slot
Stops this state machine.
The state machine will stop processing events and then emit the stopped() signal.
See also
stopped(), start()
Definition at line 1923 of file qstatemachine.cpp.
Referenced by onExit().
 {
     Q_D(QStateMachine);
     switch (d->state) {
     case QStateMachinePrivate::NotRunning:
         break;
     case QStateMachinePrivate::Starting:
         // the machine will exit as soon as it enters the event processing loop
         d->stop = true;
         break;
     case QStateMachinePrivate::Running:
         d->stop = true;
         d->processEvents(QStateMachinePrivate::QueuedProcessing);
         break;
     }
 }
stopped
QStateMachine::stopped () signal
This signal is emitted when the state machine has stopped.
See also
QStateMachine::stop(), QStateMachine::finished()
Properties
animated
QStateMachine::animated private
whether animations are enabled
The default value of this property is true.
See also
QAbstractTransition::addAnimation()
Definition at line 70 of file qstatemachine.h.
errorString
QString QStateMachine::errorString private
the error string of this state machine
Returns the error string of the last error that occurred in the state machine.
Definition at line 66 of file qstatemachine.h.
globalRestorePolicy
QStateMachine::RestorePolicy QStateMachine::globalRestorePolicy private
the restore policy for states of this state machine.
Returns the restore policy of the state machine.
The default value of this property is QStateMachine::DontRestoreProperties.
See also
setGlobalRestorePolicy()
Definition at line 67 of file qstatemachine.h.
The documentation for this class was generated from the following files:
/src/corelib/statemachine/qstatemachine.h
/src/corelib/statemachine/qstatemachine.cpp