Qt 4.8: QBearerEngineImpl Class Reference
QBearerEngineImpl Class Reference abstract
#include <qbearerengine_impl.h>
Public Types
enum ConnectionError { InterfaceLookupError = 0, ConnectError, OperationNotSupported, DisconnectionError }
Signals
void connectionError (const QString &id, QBearerEngineImpl::ConnectionError error)
Signals inherited from QBearerEngine
void configurationAdded (QNetworkConfigurationPrivatePointer config)
void configurationChanged (QNetworkConfigurationPrivatePointer config)
void configurationRemoved (QNetworkConfigurationPrivatePointer config)
void updateCompleted ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual quint64 bytesReceived (const QString &)
virtual quint64 bytesWritten (const QString &)
virtual void connectToId (const QString &id)=0
virtual void disconnectFromId (const QString &id)=0
virtual QString getInterfaceFromId (const QString &id)=0
QBearerEngineImpl (QObject *parent=0)
virtual QNetworkSession::State sessionStateForId (const QString &id)=0
virtual quint64 startTime (const QString &)
~QBearerEngineImpl ()
Public Functions inherited from QBearerEngine
virtual QNetworkConfigurationManager::Capabilities capabilities () const =0
bool configurationsInUse () const
virtual QNetworkSessionPrivate * createSessionBackend ()=0
virtual QNetworkConfigurationPrivatePointer defaultConfiguration ()=0
virtual bool hasIdentifier (const QString &id)=0
QBearerEngine (QObject *parent=0)
virtual bool requiresPolling () const
virtual ~QBearerEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QBearerEngine
QHash< QString, QNetworkConfigurationPrivatePointer > accessPointConfigurations
QMutex mutex
QHash< QString, QNetworkConfigurationPrivatePointer > snapConfigurations
QHash< QString, QNetworkConfigurationPrivatePointer > userChoiceConfigurations
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 51 of file qbearerengine_impl.h.
Enumerations
ConnectionError
enum QBearerEngineImpl::ConnectionError
Enumerator
InterfaceLookupError
ConnectError
OperationNotSupported
DisconnectionError
Definition at line 56 of file qbearerengine_impl.h.
{
         InterfaceLookupError = 0,
         ConnectError,
         OperationNotSupported,
         DisconnectionError,
     };
Constructors and Destructors
QBearerEngineImpl()
QBearerEngineImpl::QBearerEngineImpl (QObject * parent = 0) inline
Definition at line 63 of file qbearerengine_impl.h.
 : QBearerEngine(parent) {}
~QBearerEngineImpl()
QBearerEngineImpl::~QBearerEngineImpl () inline
Definition at line 64 of file qbearerengine_impl.h.
 {}
Functions
bytesReceived()
virtual quint64 QBearerEngineImpl::bytesReceived (const QString &) inline virtual
Reimplemented in QConnmanEngine, QNetworkManagerEngine, and QCoreWlanEngine.
Definition at line 74 of file qbearerengine_impl.h.
 { return Q_UINT64_C(0); }
bytesWritten()
virtual quint64 QBearerEngineImpl::bytesWritten (const QString &) inline virtual
Reimplemented in QConnmanEngine, QNetworkManagerEngine, and QCoreWlanEngine.
Definition at line 73 of file qbearerengine_impl.h.
 { return Q_UINT64_C(0); }
connectionError
void QBearerEngineImpl::connectionError (const QString & id, QBearerEngineImpl::ConnectionError error) signal
Referenced by QGenericEngine::connectToId(), QBBEngine::connectToId(), QCoreWlanEngine::connectToId(), QNativeWifiEngine::connectToId(), QConnmanEngine::connectToId(), QNlaEngine::connectToId(), QGenericEngine::disconnectFromId(), QBBEngine::disconnectFromId(), QCoreWlanEngine::disconnectFromId(), QNativeWifiEngine::disconnectFromId(), QConnmanEngine::disconnectFromId(), QNlaEngine::disconnectFromId(), QConnmanEngine::servicePropertyChangedContext(), and startTime().
connectToId()
virtual void QBearerEngineImpl::connectToId (const QString & id) pure virtual
Implemented in QNlaEngine, QConnmanEngine, QNetworkManagerEngine, QNativeWifiEngine, QCoreWlanEngine, QBBEngine, and QGenericEngine.
Referenced by ~QBearerEngineImpl().
disconnectFromId()
virtual void QBearerEngineImpl::disconnectFromId (const QString & id) pure virtual
Implemented in QNlaEngine, QConnmanEngine, QNetworkManagerEngine, QNativeWifiEngine, QCoreWlanEngine, QBBEngine, and QGenericEngine.
Referenced by ~QBearerEngineImpl().
getInterfaceFromId()
virtual QString QBearerEngineImpl::getInterfaceFromId (const QString & id) pure virtual
Implemented in QNlaEngine, QConnmanEngine, QNetworkManagerEngine, QNativeWifiEngine, QCoreWlanEngine, QBBEngine, and QGenericEngine.
Referenced by ~QBearerEngineImpl().
sessionStateForId()
virtual QNetworkSession::State QBearerEngineImpl::sessionStateForId (const QString & id) pure virtual
Implemented in QNlaEngine, QConnmanEngine, QNetworkManagerEngine, QNativeWifiEngine, QCoreWlanEngine, QBBEngine, and QGenericEngine.
Referenced by ~QBearerEngineImpl().
startTime()
virtual quint64 QBearerEngineImpl::startTime (const QString &) inline virtual
Reimplemented in QConnmanEngine, QNetworkManagerEngine, and QCoreWlanEngine.
Definition at line 75 of file qbearerengine_impl.h.
 { return Q_UINT64_C(0); }
The documentation for this class was generated from the following file:
/src/plugins/bearer/qbearerengine_impl.h