Qt 4.8: QMatrix4x4 Class Reference
QMatrix4x4 Class Reference
The QMatrix4x4 class represents a 4x4 transformation matrix in 3D space.
#include <qmatrix4x4.h>
Public Functions
QVector4D column (int index) const
Returns the elements of column index as a 4D vector.
const qreal * constData () const
Returns a constant pointer to the raw data of this matrix.
void copyDataTo (qreal *values) const
Retrieves the 16 items in this matrix and copies them to values in row-major order.
qreal * data ()
Returns a pointer to the raw data of this matrix.
const qreal * data () const
Returns a constant pointer to the raw data of this matrix.
qreal determinant () const
Returns the determinant of this matrix.
void fill (qreal value)
Fills all elements of this matrx with value.
void flipCoordinates ()
Flips between right-handed and left-handed coordinate systems by multiplying the y and z co-ordinates by -1.
void frustum (qreal left, qreal right, qreal bottom, qreal top, qreal nearPlane, qreal farPlane)
Multiplies this matrix by another that applies a perspective frustum projection for a window with lower-left corner (left, bottom), upper-right corner (right, top), and the specified nearPlane and farPlane clipping planes.
QMatrix4x4 inverted (bool *invertible=0) const
Returns the inverse of this matrix.
bool isIdentity () const
Returns true if this matrix is the identity; false otherwise.
void lookAt (const QVector3D &eye, const QVector3D &center, const QVector3D &up)
Multiplies this matrix by another that applies an eye position transformation.
QPoint map (const QPoint &point) const
Maps point by multiplying this matrix by point.
QPointF map (const QPointF &point) const
Maps point by multiplying this matrix by point.
QVector3D map (const QVector3D &point) const
Maps point by multiplying this matrix by point.
QVector4D map (const QVector4D &point) const
Maps point by multiplying this matrix by point.
QRect mapRect (const QRect &rect) const
Maps rect by multiplying this matrix by the corners of rect and then forming a new rectangle from the results.
QRectF mapRect (const QRectF &rect) const
Maps rect by multiplying this matrix by the corners of rect and then forming a new rectangle from the results.
QVector3D mapVector (const QVector3D &vector) const
Maps vector by multiplying the top 3x3 portion of this matrix by vector.
QMatrix3x3 normalMatrix () const
Returns the normal matrix corresponding to this 4x4 transformation.
operator QVariant () const
Returns the matrix as a QVariant.
bool operator!= (const QMatrix4x4 &other) const
Returns true if this matrix is not identical to other; false otherwise.
const qreal & operator() (int row, int column) const
Returns a constant reference to the element at position (row, column) in this matrix.
qreal & operator() (int row, int column)
Returns a reference to the element at position (row, column) in this matrix so that the element can be assigned to.
QMatrix4x4 & operator*= (const QMatrix4x4 &other)
Multiplies the contents of other by this matrix.
QMatrix4x4 & operator*= (qreal factor)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Multiplies all elements of this matrix by factor.
QMatrix4x4 & operator+= (const QMatrix4x4 &other)
Adds the contents of other to this matrix.
QMatrix4x4 & operator-= (const QMatrix4x4 &other)
Subtracts the contents of other from this matrix.
QMatrix4x4 & operator/= (qreal divisor)
Divides all elements of this matrix by divisor.
bool operator== (const QMatrix4x4 &other) const
Returns true if this matrix is identical to other; false otherwise.
void optimize ()
Optimize the usage of this matrix from its current elements.
void ortho (const QRect &rect)
Multiplies this matrix by another that applies an orthographic projection for a window with boundaries specified by rect.
void ortho (const QRectF &rect)
Multiplies this matrix by another that applies an orthographic projection for a window with boundaries specified by rect.
void ortho (qreal left, qreal right, qreal bottom, qreal top, qreal nearPlane, qreal farPlane)
Multiplies this matrix by another that applies an orthographic projection for a window with lower-left corner (left, bottom), upper-right corner (right, top), and the specified nearPlane and farPlane clipping planes.
void perspective (qreal angle, qreal aspect, qreal nearPlane, qreal farPlane)
Multiplies this matrix by another that applies a perspective projection.
QMatrix4x4 ()
Constructs an identity matrix.
QMatrix4x4 (const qreal *values)
Constructs a matrix from the given 16 floating-point values.
QMatrix4x4 (qreal m11, qreal m12, qreal m13, qreal m14, qreal m21, qreal m22, qreal m23, qreal m24, qreal m31, qreal m32, qreal m33, qreal m34, qreal m41, qreal m42, qreal m43, qreal m44)
Constructs a matrix from the 16 elements m11, m12, m13, m14, m21, m22, m23, m24, m31, m32, m33, m34, m41, m42, m43, and m44.
template<int N, int M>
QMatrix4x4 (const QGenericMatrix< N, M, qreal > &matrix)
Constructs a 4x4 matrix from the left-most 4 columns and top-most 4 rows of matrix.
QMatrix4x4 (const qreal *values, int cols, int rows)
QMatrix4x4 (const QTransform &transform)
Constructs a 4x4 matrix from the conventional Qt 2D transformation matrix transform.
QMatrix4x4 (const QMatrix &matrix)
Constructs a 4x4 matrix from a conventional Qt 2D affine transformation matrix.
template<int N, int M>
Q_INLINE_TEMPLATE QMatrix4x4 (const QGenericMatrix< N, M, qreal > &matrix)
void rotate (qreal angle, const QVector3D &vector)
Multiples this matrix by another that rotates coordinates through angle degrees about vector.
void rotate (qreal angle, qreal x, qreal y, qreal z=0.0f)
Multiplies this matrix by another that rotates coordinates through angle degrees about the vector (x, y, z).
void rotate (const QQuaternion &quaternion)
Multiples this matrix by another that rotates coordinates according to a specified quaternion.
QVector4D row (int index) const
Returns the elements of row index as a 4D vector.
void scale (const QVector3D &vector)
Multiplies this matrix by another that scales coordinates by the components of vector.
void scale (qreal x, qreal y)
Multiplies this matrix by another that scales coordinates by the components x, and y.
void scale (qreal x, qreal y, qreal z)
Multiplies this matrix by another that scales coordinates by the components x, y, and z.
void scale (qreal factor)
Multiplies this matrix by another that scales coordinates by the given factor.
void setColumn (int index, const QVector4D &value)
Sets the elements of column index to the components of value.
void setRow (int index, const QVector4D &value)
Sets the elements of row index to the components of value.
void setToIdentity ()
Sets this matrix to the identity.
QMatrix toAffine () const
Returns the conventional Qt 2D affine transformation matrix that corresponds to this matrix.
template<int N, int M>
QGenericMatrix< N, M, qreal > toGenericMatrix () const
Constructs a NxM generic matrix from the left-most N columns and top-most M rows of this 4x4 matrix.
QTransform toTransform () const
Returns the conventional Qt 2D transformation matrix that corresponds to this matrix.
QTransform toTransform (qreal distanceToPlane) const
Returns the conventional Qt 2D transformation matrix that corresponds to this matrix.
void translate (const QVector3D &vector)
Multiplies this matrix by another that translates coordinates by the components of vector.
void translate (qreal x, qreal y)
Multiplies this matrix by another that translates coordinates by the components x, and y.
void translate (qreal x, qreal y, qreal z)
Multiplies this matrix by another that translates coordinates by the components x, y, and z.
QMatrix4x4 transposed () const
Returns this matrix, transposed about its diagonal.
Private Types
enum {
Identity = 0x0001, General = 0x0002, Translation = 0x0004, Scale = 0x0008,
Rotation = 0x0010
}
Private Functions
QMatrix4x4 orthonormalInverse () const
void projectedRotate (qreal angle, qreal x, qreal y, qreal z)
QMatrix4x4 (int)
Properties
int flagBits
qreal m [4][4]
Friends
QMatrix4x4 operator* (const QMatrix4x4 &m1, const QMatrix4x4 &m2)
QVector3D operator* (const QMatrix4x4 &matrix, const QVector3D &vector)
QVector3D operator* (const QVector3D &vector, const QMatrix4x4 &matrix)
QVector4D operator* (const QVector4D &vector, const QMatrix4x4 &matrix)
QVector4D operator* (const QMatrix4x4 &matrix, const QVector4D &vector)
QPoint operator* (const QPoint &point, const QMatrix4x4 &matrix)
QPointF operator* (const QPointF &point, const QMatrix4x4 &matrix)
QPoint operator* (const QMatrix4x4 &matrix, const QPoint &point)
QPointF operator* (const QMatrix4x4 &matrix, const QPointF &point)
QMatrix4x4 operator* (qreal factor, const QMatrix4x4 &matrix)
QMatrix4x4 operator* (const QMatrix4x4 &matrix, qreal factor)
QMatrix4x4 operator+ (const QMatrix4x4 &m1, const QMatrix4x4 &m2)
Returns the sum of m1 and m2.
QMatrix4x4 operator- (const QMatrix4x4 &m1, const QMatrix4x4 &m2)
Returns the difference of m1 and m2.
QMatrix4x4 operator- (const QMatrix4x4 &matrix)
Returns the negation of matrix.
Q_GUI_EXPORT QMatrix4x4 operator/ (const QMatrix4x4 &matrix, qreal divisor)
Returns the result of dividing all elements of matrix by divisor.
Q_GUI_EXPORT QDebug operator<< (QDebug dbg, const QMatrix4x4 &m)
bool qFuzzyCompare (const QMatrix4x4 &m1, const QMatrix4x4 &m2)
Returns true if m1 and m2 are equal, allowing for a small fuzziness factor for floating-point comparisons; false otherwise.
class QGraphicsRotation
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QMatrix4x4 &matrix)
Writes the given matrix to the given stream and returns a reference to the stream.
QDataStream & operator>> (QDataStream &stream, QMatrix4x4 &matrix)
Reads a 4x4 matrix from the given stream into the given matrix and returns a reference to the stream.
QGenericMatrix< N, M, qreal > qGenericMatrixFromMatrix4x4 (const QMatrix4x4 &matrix)
Returns a NxM generic matrix constructed from the left-most N columns and top-most M rows of matrix.
QMatrix4x4 qGenericMatrixToMatrix4x4 (const QGenericMatrix< N, M, qreal > &matrix)
Returns a 4x4 matrix constructed from the left-most 4 columns and top-most 4 rows of matrix.
Detailed Description
The QMatrix4x4 class represents a 4x4 transformation matrix in 3D space.
Since
4.6
See also
QVector3D, QGenericMatrix
Definition at line 63 of file qmatrix4x4.h.
Enumerations
anonymous enum
anonymous enum private
Enumerator
Identity
General
Translation
Scale
Rotation
Definition at line 191 of file qmatrix4x4.h.
          {
         Identity        = 0x0001,   // Identity matrix
         General         = 0x0002,   // General matrix, unknown contents
         Translation     = 0x0004,   // Contains a simple translation
         Scale           = 0x0008,   // Contains a simple scale
         Rotation        = 0x0010    // Contains a simple rotation
     };
Constructors and Destructors
QMatrix4x4() [1/9]
QMatrix4x4::QMatrix4x4 () inline
Constructs an identity matrix.
Definition at line 66 of file qmatrix4x4.h.
Referenced by inverted(), and QMatrix4x4().
 { setToIdentity(); }
QMatrix4x4() [2/9]
QMatrix4x4::QMatrix4x4 (const qreal * values) explicit
Constructs a matrix from the given 16 floating-point values.
The contents of the array values is assumed to be in row-major order.
If the matrix has a special type (identity, translate, scale, etc), the programmer should follow this constructor with a call to optimize() if they wish QMatrix4x4 to optimize further calls to translate(), scale(), etc.
See also
copyDataTo(), optimize()
Definition at line 87 of file qmatrix4x4.cpp.
 {
     for (int row = 0; row < 4; ++row)
         for (int col = 0; col < 4; ++col)
             m[col][row] = values[row * 4 + col];
     flagBits = General;
 }
QMatrix4x4() [3/9]
QMatrix4x4::QMatrix4x4 (qreal m11, qreal m12, qreal m13, qreal m14, qreal m21, qreal m22, qreal m23, qreal m24, qreal m31, qreal m32, qreal m33, qreal m34, qreal m41, qreal m42, qreal m43, qreal m44) inline
Constructs a matrix from the 16 elements m11, m12, m13, m14, m21, m22, m23, m24, m31, m32, m33, m34, m41, m42, m43, and m44.
The elements are specified in row-major order.
If the matrix has a special type (identity, translate, scale, etc), the programmer should follow this constructor with a call to optimize() if they wish QMatrix4x4 to optimize further calls to translate(), scale(), etc.
See also
optimize()
Definition at line 212 of file qmatrix4x4.h.
 {
     m[0][0] = m11; m[0][1] = m21; m[0][2] = m31; m[0][3] = m41;
     m[1][0] = m12; m[1][1] = m22; m[1][2] = m32; m[1][3] = m42;
     m[2][0] = m13; m[2][1] = m23; m[2][2] = m33; m[2][3] = m43;
     m[3][0] = m14; m[3][1] = m24; m[3][2] = m34; m[3][3] = m44;
     flagBits = General;
 }
QMatrix4x4() [4/9]
template<int N, int M> QMatrix4x4::QMatrix4x4 (const QGenericMatrix< N, M, qreal > & matrix) explicit
Constructs a 4x4 matrix from the left-most 4 columns and top-most 4 rows of matrix.
If matrix has less than 4 columns or rows, the remaining elements are filled with elements from the identity matrix.
See also
toGenericMatrix()
QMatrix4x4() [5/9]
QMatrix4x4::QMatrix4x4 (const qreal * values, int cols, int rows)
Warning
This function is not part of the public interface.
Definition at line 175 of file qmatrix4x4.cpp.
 {
     for (int col = 0; col < 4; ++col) {
         for (int row = 0; row < 4; ++row) {
             if (col < cols && row < rows)
                 m[col][row] = values[col * rows + row];
             else if (col == row)
                 m[col][row] = 1.0f;
             else
                 m[col][row] = 0.0f;
         }
     }
     flagBits = General;
 }
QMatrix4x4() [6/9]
QMatrix4x4::QMatrix4x4 (const QTransform & transform)
Constructs a 4x4 matrix from the conventional Qt 2D transformation matrix transform.
If transform has a special type (identity, translate, scale, etc), the programmer should follow this constructor with a call to optimize() if they wish QMatrix4x4 to optimize further calls to translate(), scale(), etc.
See also
toTransform(), optimize()
Definition at line 233 of file qmatrix4x4.cpp.
 {
     m[0][0] = transform.m11();
     m[0][1] = transform.m12();
     m[0][2] = 0.0f;
     m[0][3] = transform.m13();
     m[1][0] = transform.m21();
     m[1][1] = transform.m22();
     m[1][2] = 0.0f;
     m[1][3] = transform.m23();
     m[2][0] = 0.0f;
     m[2][1] = 0.0f;
     m[2][2] = 1.0f;
     m[2][3] = 0.0f;
     m[3][0] = transform.dx();
     m[3][1] = transform.dy();
     m[3][2] = 0.0f;
     m[3][3] = transform.m33();
     flagBits = General;
 }
QMatrix4x4() [7/9]
QMatrix4x4::QMatrix4x4 (const QMatrix & matrix)
Constructs a 4x4 matrix from a conventional Qt 2D affine transformation matrix.
If matrix has a special type (identity, translate, scale, etc), the programmer should follow this constructor with a call to optimize() if they wish QMatrix4x4 to optimize further calls to translate(), scale(), etc.
See also
toAffine(), optimize()
Definition at line 201 of file qmatrix4x4.cpp.
 {
     m[0][0] = matrix.m11();
     m[0][1] = matrix.m12();
     m[0][2] = 0.0f;
     m[0][3] = 0.0f;
     m[1][0] = matrix.m21();
     m[1][1] = matrix.m22();
     m[1][2] = 0.0f;
     m[1][3] = 0.0f;
     m[2][0] = 0.0f;
     m[2][1] = 0.0f;
     m[2][2] = 1.0f;
     m[2][3] = 0.0f;
     m[3][0] = matrix.dx();
     m[3][1] = matrix.dy();
     m[3][2] = 0.0f;
     m[3][3] = 1.0f;
     flagBits = General;
 }
QMatrix4x4() [8/9]
QMatrix4x4::QMatrix4x4 (int) inline private
Definition at line 200 of file qmatrix4x4.h.
 { flagBits = General; }
QMatrix4x4() [9/9]
template<int N, int M> Q_INLINE_TEMPLATE QMatrix4x4::QMatrix4x4 (const QGenericMatrix< N, M, qreal > & matrix)
Definition at line 226 of file qmatrix4x4.h.
 {
     const qreal *values = matrix.constData();
     for (int matrixCol = 0; matrixCol < 4; ++matrixCol) {
         for (int matrixRow = 0; matrixRow < 4; ++matrixRow) {
             if (matrixCol < N && matrixRow < M)
                 m[matrixCol][matrixRow] = values[matrixCol * M + matrixRow];
             else if (matrixCol == matrixRow)
                 m[matrixCol][matrixRow] = 1.0f;
             else
                 m[matrixCol][matrixRow] = 0.0f;
         }
     }
     flagBits = General;
 }
Functions
column()
QVector4D QMatrix4x4::column (int index) const inline
Returns the elements of column index as a 4D vector.
See also
setColumn(), row()
Definition at line 273 of file qmatrix4x4.h.
 {
     Q_ASSERT(index >= 0 && index < 4);
     return QVector4D(m[index][0], m[index][1], m[index][2], m[index][3]);
 }
constData()
const qreal * QMatrix4x4::constData () const inline
Returns a constant pointer to the raw data of this matrix.
See also
data()
Definition at line 177 of file qmatrix4x4.h.
Referenced by qGenericMatrixFromMatrix4x4().
 { return *m; }
copyDataTo()
void QMatrix4x4::copyDataTo (qreal * values) const
Retrieves the 16 items in this matrix and copies them to values in row-major order.
Definition at line 1599 of file qmatrix4x4.cpp.
 {
     for (int row = 0; row < 4; ++row)
         for (int col = 0; col < 4; ++col)
             values[row * 4 + col] = qreal(m[col][row]);
 }
data() [1/2]
qreal * QMatrix4x4::data () inline
Returns a pointer to the raw data of this matrix.
See also
constData(), optimize()
Definition at line 972 of file qmatrix4x4.h.
 {
     // We have to assume that the caller will modify the matrix elements,
     // so we flip it over to "General" mode.
     flagBits = General;
     return *m;
 }
data() [2/2]
const qreal * QMatrix4x4::data () const inline
Returns a constant pointer to the raw data of this matrix.
See also
constData()
Definition at line 176 of file qmatrix4x4.h.
 { return *m; }
determinant()
qreal QMatrix4x4::determinant () const
Returns the determinant of this matrix.
Definition at line 391 of file qmatrix4x4.cpp.
 {
     return qreal(matrixDet4(m));
 }
fill()
void QMatrix4x4::fill (qreal value) inline
Fills all elements of this matrx with value.
Definition at line 345 of file qmatrix4x4.h.
 {
     m[0][0] = value;
     m[0][1] = value;
     m[0][2] = value;
     m[0][3] = value;
     m[1][0] = value;
     m[1][1] = value;
     m[1][2] = value;
     m[1][3] = value;
     m[2][0] = value;
     m[2][1] = value;
     m[2][2] = value;
     m[2][3] = value;
     m[3][0] = value;
     m[3][1] = value;
     m[3][2] = value;
     m[3][3] = value;
     flagBits = General;
 }
flipCoordinates()
void QMatrix4x4::flipCoordinates ()
Flips between right-handed and left-handed coordinate systems by multiplying the y and z co-ordinates by -1.
This is normally used to create a left-handed orthographic view without scaling the viewport as ortho() does.
See also
ortho()
Definition at line 1569 of file qmatrix4x4.cpp.
 {
     if (flagBits == Scale || flagBits == (Scale | Translation)) {
         m[1][1] = -m[1][1];
         m[2][2] = -m[2][2];
     } else if (flagBits == Translation) {
         m[1][1] = -m[1][1];
         m[2][2] = -m[2][2];
         flagBits |= Scale;
     } else if (flagBits == Identity) {
         m[1][1] = -1.0f;
         m[2][2] = -1.0f;
         flagBits = Scale;
     } else {
         m[1][0] = -m[1][0];
         m[1][1] = -m[1][1];
         m[1][2] = -m[1][2];
         m[1][3] = -m[1][3];
         m[2][0] = -m[2][0];
         m[2][1] = -m[2][1];
         m[2][2] = -m[2][2];
         m[2][3] = -m[2][3];
         flagBits = General;
     }
 }
frustum()
void QMatrix4x4::frustum (qreal left, qreal right, qreal bottom, qreal top, qreal nearPlane, qreal farPlane)
Multiplies this matrix by another that applies a perspective frustum projection for a window with lower-left corner (left, bottom), upper-right corner (right, top), and the specified nearPlane and farPlane clipping planes.
See also
ortho(), perspective()
Definition at line 1447 of file qmatrix4x4.cpp.
 {
     // Bail out if the projection volume is zero-sized.
     if (left == right || bottom == top || nearPlane == farPlane)
         return;
     // Construct the projection.
     QMatrix4x4 m(1);
     qreal width = right - left;
     qreal invheight = top - bottom;
     qreal clip = farPlane - nearPlane;
     m.m[0][0] = 2.0f * nearPlane / width;
     m.m[1][0] = 0.0f;
     m.m[2][0] = (left + right) / width;
     m.m[3][0] = 0.0f;
     m.m[0][1] = 0.0f;
     m.m[1][1] = 2.0f * nearPlane / invheight;
     m.m[2][1] = (top + bottom) / invheight;
     m.m[3][1] = 0.0f;
     m.m[0][2] = 0.0f;
     m.m[1][2] = 0.0f;
     m.m[2][2] = -(nearPlane + farPlane) / clip;
     m.m[3][2] = -2.0f * nearPlane * farPlane / clip;
     m.m[0][3] = 0.0f;
     m.m[1][3] = 0.0f;
     m.m[2][3] = -1.0f;
     m.m[3][3] = 0.0f;
     // Apply the projection.
     *this *= m;
 }
inverted()
QMatrix4x4 QMatrix4x4::inverted (bool * invertible = 0) const
Returns the inverse of this matrix.
Returns the identity if this matrix cannot be inverted; i.e. determinant() is zero. If invertible is not null, then true will be written to that location if the matrix can be inverted; false otherwise.
If the matrix is recognized as the identity or an orthonormal matrix, then this function will quickly invert the matrix using optimized routines.
See also
determinant(), normalMatrix()
Definition at line 408 of file qmatrix4x4.cpp.
 {
     // Handle some of the easy cases first.
     if (flagBits == Identity) {
         if (invertible)
             *invertible = true;
         return QMatrix4x4();
     } else if (flagBits == Translation) {
         QMatrix4x4 inv;
         inv.m[3][0] = -m[3][0];
         inv.m[3][1] = -m[3][1];
         inv.m[3][2] = -m[3][2];
         inv.flagBits = Translation;
         if (invertible)
             *invertible = true;
         return inv;
     } else if (flagBits == Rotation || flagBits == (Rotation | Translation)) {
         if (invertible)
             *invertible = true;
         return orthonormalInverse();
     }
     QMatrix4x4 inv(1); // The "1" says to not load the identity.
     qreal det = matrixDet4(m);
     if (det == 0.0f) {
         if (invertible)
             *invertible = false;
         return QMatrix4x4();
     }
     det = 1.0f / det;
     inv.m[0][0] =  matrixDet3(m, 1, 2, 3, 1, 2, 3) * det;
     inv.m[0][1] = -matrixDet3(m, 0, 2, 3, 1, 2, 3) * det;
     inv.m[0][2] =  matrixDet3(m, 0, 1, 3, 1, 2, 3) * det;
     inv.m[0][3] = -matrixDet3(m, 0, 1, 2, 1, 2, 3) * det;
     inv.m[1][0] = -matrixDet3(m, 1, 2, 3, 0, 2, 3) * det;
     inv.m[1][1] =  matrixDet3(m, 0, 2, 3, 0, 2, 3) * det;
     inv.m[1][2] = -matrixDet3(m, 0, 1, 3, 0, 2, 3) * det;
     inv.m[1][3] =  matrixDet3(m, 0, 1, 2, 0, 2, 3) * det;
     inv.m[2][0] =  matrixDet3(m, 1, 2, 3, 0, 1, 3) * det;
     inv.m[2][1] = -matrixDet3(m, 0, 2, 3, 0, 1, 3) * det;
     inv.m[2][2] =  matrixDet3(m, 0, 1, 3, 0, 1, 3) * det;
     inv.m[2][3] = -matrixDet3(m, 0, 1, 2, 0, 1, 3) * det;
     inv.m[3][0] = -matrixDet3(m, 1, 2, 3, 0, 1, 2) * det;
     inv.m[3][1] =  matrixDet3(m, 0, 2, 3, 0, 1, 2) * det;
     inv.m[3][2] = -matrixDet3(m, 0, 1, 3, 0, 1, 2) * det;
     inv.m[3][3] =  matrixDet3(m, 0, 1, 2, 0, 1, 2) * det;
     if (invertible)
         *invertible = true;
     return inv;
 }
isIdentity()
bool QMatrix4x4::isIdentity () const inline
Returns true if this matrix is the identity; false otherwise.
See also
setToIdentity()
Definition at line 307 of file qmatrix4x4.h.
 {
     if (flagBits == Identity)
         return true;
     if (m[0][0] != 1.0f || m[0][1] != 0.0f || m[0][2] != 0.0f)
         return false;
     if (m[0][3] != 0.0f || m[1][0] != 0.0f || m[1][1] != 1.0f)
         return false;
     if (m[1][2] != 0.0f || m[1][3] != 0.0f || m[2][0] != 0.0f)
         return false;
     if (m[2][1] != 0.0f || m[2][2] != 1.0f || m[2][3] != 0.0f)
         return false;
     if (m[3][0] != 0.0f || m[3][1] != 0.0f || m[3][2] != 0.0f)
         return false;
     return (m[3][3] == 1.0f);
 }
lookAt()
void QMatrix4x4::lookAt (const QVector3D & eye, const QVector3D & center, const QVector3D & up)
Multiplies this matrix by another that applies an eye position transformation.
The center value indicates the center of the view that the eye is looking at. The up value indicates which direction should be considered up with respect to the eye.
Definition at line 1530 of file qmatrix4x4.cpp.
 {
     QVector3D forward = (center - eye).normalized();
     QVector3D side = QVector3D::crossProduct(forward, up).normalized();
     QVector3D upVector = QVector3D::crossProduct(side, forward);
     QMatrix4x4 m(1);
     m.m[0][0] = side.x();
     m.m[1][0] = side.y();
     m.m[2][0] = side.z();
     m.m[3][0] = 0.0f;
     m.m[0][1] = upVector.x();
     m.m[1][1] = upVector.y();
     m.m[2][1] = upVector.z();
     m.m[3][1] = 0.0f;
     m.m[0][2] = -forward.x();
     m.m[1][2] = -forward.y();
     m.m[2][2] = -forward.z();
     m.m[3][2] = 0.0f;
     m.m[0][3] = 0.0f;
     m.m[1][3] = 0.0f;
     m.m[2][3] = 0.0f;
     m.m[3][3] = 1.0f;
     *this *= m;
     translate(-eye);
 }
map() [1/4]
QPoint QMatrix4x4::map (const QPoint & point) const inline
Maps point by multiplying this matrix by point.
See also
mapRect()
Definition at line 923 of file qmatrix4x4.h.
Referenced by mapRect().
 {
     return *this * point;
 }
map() [2/4]
QPointF QMatrix4x4::map (const QPointF & point) const inline
Maps point by multiplying this matrix by point.
See also
mapRect()
Definition at line 928 of file qmatrix4x4.h.
 {
     return *this * point;
 }
map() [3/4]
QVector3D QMatrix4x4::map (const QVector3D & point) const inline
Maps point by multiplying this matrix by point.
See also
mapRect(), mapVector()
Definition at line 935 of file qmatrix4x4.h.
 {
     return *this * point;
 }
map() [4/4]
QVector4D QMatrix4x4::map (const QVector4D & point) const inline
Maps point by multiplying this matrix by point.
See also
mapRect()
Definition at line 965 of file qmatrix4x4.h.
 {
     return *this * point;
 }
mapRect() [1/2]
QRect QMatrix4x4::mapRect (const QRect & rect) const
Maps rect by multiplying this matrix by the corners of rect and then forming a new rectangle from the results.
The returned rectangle will be an ordinary 2D rectangle with sides parallel to the horizontal and vertical axes.
See also
map()
Definition at line 1758 of file qmatrix4x4.cpp.
 {
     if (flagBits == (Translation | Scale) || flagBits == Scale) {
         qreal x = rect.x() * m[0][0] + m[3][0];
         qreal y = rect.y() * m[1][1] + m[3][1];
         qreal w = rect.width() * m[0][0];
         qreal h = rect.height() * m[1][1];
         if (w < 0) {
             w = -w;
             x -= w;
         }
         if (h < 0) {
             h = -h;
             y -= h;
         }
         return QRect(qRound(x), qRound(y), qRound(w), qRound(h));
     } else if (flagBits == Translation) {
         return QRect(qRound(rect.x() + m[3][0]),
                      qRound(rect.y() + m[3][1]),
                      rect.width(), rect.height());
     }
     QPoint tl = map(rect.topLeft());
     QPoint tr = map(QPoint(rect.x() + rect.width(), rect.y()));
     QPoint bl = map(QPoint(rect.x(), rect.y() + rect.height()));
     QPoint br = map(QPoint(rect.x() + rect.width(),
                            rect.y() + rect.height()));
     int xmin = qMin(qMin(tl.x(), tr.x()), qMin(bl.x(), br.x()));
     int xmax = qMax(qMax(tl.x(), tr.x()), qMax(bl.x(), br.x()));
     int ymin = qMin(qMin(tl.y(), tr.y()), qMin(bl.y(), br.y()));
     int ymax = qMax(qMax(tl.y(), tr.y()), qMax(bl.y(), br.y()));
     return QRect(xmin, ymin, xmax - xmin, ymax - ymin);
 }
mapRect() [2/2]
QRectF QMatrix4x4::mapRect (const QRectF & rect) const
Maps rect by multiplying this matrix by the corners of rect and then forming a new rectangle from the results.
The returned rectangle will be an ordinary 2D rectangle with sides parallel to the horizontal and vertical axes.
See also
map()
Definition at line 1802 of file qmatrix4x4.cpp.
 {
     if (flagBits == (Translation | Scale) || flagBits == Scale) {
         qreal x = rect.x() * m[0][0] + m[3][0];
         qreal y = rect.y() * m[1][1] + m[3][1];
         qreal w = rect.width() * m[0][0];
         qreal h = rect.height() * m[1][1];
         if (w < 0) {
             w = -w;
             x -= w;
         }
         if (h < 0) {
             h = -h;
             y -= h;
         }
         return QRectF(x, y, w, h);
     } else if (flagBits == Translation) {
         return rect.translated(m[3][0], m[3][1]);
     }
     QPointF tl = map(rect.topLeft()); QPointF tr = map(rect.topRight());
     QPointF bl = map(rect.bottomLeft()); QPointF br = map(rect.bottomRight());
     qreal xmin = qMin(qMin(tl.x(), tr.x()), qMin(bl.x(), br.x()));
     qreal xmax = qMax(qMax(tl.x(), tr.x()), qMax(bl.x(), br.x()));
     qreal ymin = qMin(qMin(tl.y(), tr.y()), qMin(bl.y(), br.y()));
     qreal ymax = qMax(qMax(tl.y(), tr.y()), qMax(bl.y(), br.y()));
     return QRectF(QPointF(xmin, ymin), QPointF(xmax, ymax));
 }
mapVector()
QVector3D QMatrix4x4::mapVector (const QVector3D & vector) const inline
Maps vector by multiplying the top 3x3 portion of this matrix by vector.
The translation and projection components of this matrix are ignored.
See also
map()
Definition at line 940 of file qmatrix4x4.h.
 {
     if (flagBits == Identity || flagBits == Translation) {
         return vector;
     } else if (flagBits == Scale || flagBits == (Translation | Scale)) {
         return QVector3D(vector.x() * m[0][0],
                          vector.y() * m[1][1],
                          vector.z() * m[2][2]);
     } else {
         return QVector3D(vector.x() * m[0][0] +
                          vector.y() * m[1][0] +
                          vector.z() * m[2][0],
                          vector.x() * m[0][1] +
                          vector.y() * m[1][1] +
                          vector.z() * m[2][1],
                          vector.x() * m[0][2] +
                          vector.y() * m[1][2] +
                          vector.z() * m[2][2]);
     }
 }
normalMatrix()
QMatrix3x3 QMatrix4x4::normalMatrix () const
Returns the normal matrix corresponding to this 4x4 transformation.
The normal matrix is the transpose of the inverse of the top-left 3x3 part of this 4x4 matrix. If the 3x3 sub-matrix is not invertible, this function returns the identity.
See also
inverted()
Definition at line 470 of file qmatrix4x4.cpp.
 {
     QMatrix3x3 inv;
     // Handle the simple cases first.
     if (flagBits == Identity || flagBits == Translation) {
         return inv;
     } else if (flagBits == Scale || flagBits == (Translation | Scale)) {
         if (m[0][0] == 0.0f || m[1][1] == 0.0f || m[2][2] == 0.0f)
             return inv;
         inv.data()[0] = 1.0f / m[0][0];
         inv.data()[4] = 1.0f / m[1][1];
         inv.data()[8] = 1.0f / m[2][2];
         return inv;
     }
     qreal det = matrixDet3(m, 0, 1, 2, 0, 1, 2);
     if (det == 0.0f)
         return inv;
     det = 1.0f / det;
     qreal *invm = inv.data();
     // Invert and transpose in a single step.
     invm[0 + 0 * 3] =  (m[1][1] * m[2][2] - m[2][1] * m[1][2]) * det;
     invm[1 + 0 * 3] = -(m[1][0] * m[2][2] - m[1][2] * m[2][0]) * det;
     invm[2 + 0 * 3] =  (m[1][0] * m[2][1] - m[1][1] * m[2][0]) * det;
     invm[0 + 1 * 3] = -(m[0][1] * m[2][2] - m[2][1] * m[0][2]) * det;
     invm[1 + 1 * 3] =  (m[0][0] * m[2][2] - m[0][2] * m[2][0]) * det;
     invm[2 + 1 * 3] = -(m[0][0] * m[2][1] - m[0][1] * m[2][0]) * det;
     invm[0 + 2 * 3] =  (m[0][1] * m[1][2] - m[0][2] * m[1][1]) * det;
     invm[1 + 2 * 3] = -(m[0][0] * m[1][2] - m[0][2] * m[1][0]) * det;
     invm[2 + 2 * 3] =  (m[0][0] * m[1][1] - m[1][0] * m[0][1]) * det;
     return inv;
 }
operator QVariant()
QMatrix4x4::operator QVariant () const
Returns the matrix as a QVariant.
Definition at line 1948 of file qmatrix4x4.cpp.
 {
     return QVariant(QVariant::Matrix4x4, this);
 }
operator!=()
bool QMatrix4x4::operator!= (const QMatrix4x4 & other) const inline
Returns true if this matrix is not identical to other; false otherwise.
This operator uses an exact floating-point comparison.
Definition at line 465 of file qmatrix4x4.h.
 {
     return m[0][0] != other.m[0][0] ||
            m[0][1] != other.m[0][1] ||
            m[0][2] != other.m[0][2] ||
            m[0][3] != other.m[0][3] ||
            m[1][0] != other.m[1][0] ||
            m[1][1] != other.m[1][1] ||
            m[1][2] != other.m[1][2] ||
            m[1][3] != other.m[1][3] ||
            m[2][0] != other.m[2][0] ||
            m[2][1] != other.m[2][1] ||
            m[2][2] != other.m[2][2] ||
            m[2][3] != other.m[2][3] ||
            m[3][0] != other.m[3][0] ||
            m[3][1] != other.m[3][1] ||
            m[3][2] != other.m[3][2] ||
            m[3][3] != other.m[3][3];
 }
operator()() [1/2]
const qreal & QMatrix4x4::operator() (int row, int column) const inline
Returns a constant reference to the element at position (row, column) in this matrix.
See also
column(), row()
Definition at line 260 of file qmatrix4x4.h.
 {
     Q_ASSERT(aRow >= 0 && aRow < 4 && aColumn >= 0 && aColumn < 4);
     return m[aColumn][aRow];
 }
operator()() [2/2]
qreal & QMatrix4x4::operator() (int row, int column) inline
Returns a reference to the element at position (row, column) in this matrix so that the element can be assigned to.
See also
optimize(), setColumn(), setRow()
Definition at line 266 of file qmatrix4x4.h.
 {
     Q_ASSERT(aRow >= 0 && aRow < 4 && aColumn >= 0 && aColumn < 4);
     flagBits = General;
     return m[aColumn][aRow];
 }
operator*=() [1/2]
QMatrix4x4 & QMatrix4x4::operator*= (const QMatrix4x4 & other) inline
Multiplies the contents of other by this matrix.
Definition at line 410 of file qmatrix4x4.h.
 {
     if (flagBits == Identity) {
         *this = other;
         return *this;
     } else if (other.flagBits == Identity) {
         return *this;
     } else {
         *this = *this * other;
         return *this;
     }
 }
operator*=() [2/2]
QMatrix4x4 & QMatrix4x4::operator*= (qreal factor) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Multiplies all elements of this matrix by factor.
Definition at line 423 of file qmatrix4x4.h.
 {
     m[0][0] *= factor;
     m[0][1] *= factor;
     m[0][2] *= factor;
     m[0][3] *= factor;
     m[1][0] *= factor;
     m[1][1] *= factor;
     m[1][2] *= factor;
     m[1][3] *= factor;
     m[2][0] *= factor;
     m[2][1] *= factor;
     m[2][2] *= factor;
     m[2][3] *= factor;
     m[3][0] *= factor;
     m[3][1] *= factor;
     m[3][2] *= factor;
     m[3][3] *= factor;
     flagBits = General;
     return *this;
 }
operator+=()
QMatrix4x4 & QMatrix4x4::operator+= (const QMatrix4x4 & other) inline
Adds the contents of other to this matrix.
Definition at line 366 of file qmatrix4x4.h.
 {
     m[0][0] += other.m[0][0];
     m[0][1] += other.m[0][1];
     m[0][2] += other.m[0][2];
     m[0][3] += other.m[0][3];
     m[1][0] += other.m[1][0];
     m[1][1] += other.m[1][1];
     m[1][2] += other.m[1][2];
     m[1][3] += other.m[1][3];
     m[2][0] += other.m[2][0];
     m[2][1] += other.m[2][1];
     m[2][2] += other.m[2][2];
     m[2][3] += other.m[2][3];
     m[3][0] += other.m[3][0];
     m[3][1] += other.m[3][1];
     m[3][2] += other.m[3][2];
     m[3][3] += other.m[3][3];
     flagBits = General;
     return *this;
 }
operator-=()
QMatrix4x4 & QMatrix4x4::operator-= (const QMatrix4x4 & other) inline
Subtracts the contents of other from this matrix.
Definition at line 388 of file qmatrix4x4.h.
 {
     m[0][0] -= other.m[0][0];
     m[0][1] -= other.m[0][1];
     m[0][2] -= other.m[0][2];
     m[0][3] -= other.m[0][3];
     m[1][0] -= other.m[1][0];
     m[1][1] -= other.m[1][1];
     m[1][2] -= other.m[1][2];
     m[1][3] -= other.m[1][3];
     m[2][0] -= other.m[2][0];
     m[2][1] -= other.m[2][1];
     m[2][2] -= other.m[2][2];
     m[2][3] -= other.m[2][3];
     m[3][0] -= other.m[3][0];
     m[3][1] -= other.m[3][1];
     m[3][2] -= other.m[3][2];
     m[3][3] -= other.m[3][3];
     flagBits = General;
     return *this;
 }
operator/=()
QMatrix4x4 & QMatrix4x4::operator/= (qreal divisor)
Divides all elements of this matrix by divisor.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 560 of file qmatrix4x4.cpp.
 {
     m[0][0] /= divisor;
     m[0][1] /= divisor;
     m[0][2] /= divisor;
     m[0][3] /= divisor;
     m[1][0] /= divisor;
     m[1][1] /= divisor;
     m[1][2] /= divisor;
     m[1][3] /= divisor;
     m[2][0] /= divisor;
     m[2][1] /= divisor;
     m[2][2] /= divisor;
     m[2][3] /= divisor;
     m[3][0] /= divisor;
     m[3][1] /= divisor;
     m[3][2] /= divisor;
     m[3][3] /= divisor;
     flagBits = General;
     return *this;
 }
operator==()
bool QMatrix4x4::operator== (const QMatrix4x4 & other) const inline
Returns true if this matrix is identical to other; false otherwise.
This operator uses an exact floating-point comparison.
Definition at line 445 of file qmatrix4x4.h.
 {
     return m[0][0] == other.m[0][0] &&
            m[0][1] == other.m[0][1] &&
            m[0][2] == other.m[0][2] &&
            m[0][3] == other.m[0][3] &&
            m[1][0] == other.m[1][0] &&
            m[1][1] == other.m[1][1] &&
            m[1][2] == other.m[1][2] &&
            m[1][3] == other.m[1][3] &&
            m[2][0] == other.m[2][0] &&
            m[2][1] == other.m[2][1] &&
            m[2][2] == other.m[2][2] &&
            m[2][3] == other.m[2][3] &&
            m[3][0] == other.m[3][0] &&
            m[3][1] == other.m[3][1] &&
            m[3][2] == other.m[3][2] &&
            m[3][3] == other.m[3][3];
 }
optimize()
void QMatrix4x4::optimize ()
Optimize the usage of this matrix from its current elements.
Some operations such as translate(), scale(), and rotate() can be performed more efficiently if the matrix being modified is already known to be the identity, a previous translate(), a previous scale(), etc.
Normally the QMatrix4x4 class keeps track of this special type internally as operations are performed. However, if the matrix is modified directly with operator()() or data(), then QMatrix4x4 will lose track of the special type and will revert to the safest but least efficient operations thereafter.
By calling optimize() after directly modifying the matrix, the programmer can force QMatrix4x4 to recover the special type if the elements appear to conform to one of the known optimized types.
See also
operator()(), data(), translate()
Definition at line 1907 of file qmatrix4x4.cpp.
Referenced by operator>>().
 {
     // If the last element is not 1, then it can never be special.
     if (m[3][3] != 1.0f) {
         flagBits = General;
         return;
     }
     // If the upper three elements m12, m13, and m21 are not all zero,
     // or the lower elements below the diagonal are not all zero, then
     // the matrix can never be special.
     if (m[1][0] != 0.0f || m[2][0] != 0.0f || m[2][1] != 0.0f) {
         flagBits = General;
         return;
     }
     if (m[0][1] != 0.0f || m[0][2] != 0.0f || m[0][3] != 0.0f ||
         m[1][2] != 0.0f || m[1][3] != 0.0f || m[2][3] != 0.0f) {
         flagBits = General;
         return;
     }
     // Determine what we have in the remaining regions of the matrix.
     bool identityAlongDiagonal
         = (m[0][0] == 1.0f && m[1][1] == 1.0f && m[2][2] == 1.0f);
     bool translationPresent
         = (m[3][0] != 0.0f || m[3][1] != 0.0f || m[3][2] != 0.0f);
     // Now determine the special matrix type.
     if (translationPresent && identityAlongDiagonal)
         flagBits = Translation;
     else if (translationPresent)
         flagBits = (Translation | Scale);
     else if (identityAlongDiagonal)
         flagBits = Identity;
     else
         flagBits = Scale;
 }
ortho() [1/3]
void QMatrix4x4::ortho (const QRect & rect)
Multiplies this matrix by another that applies an orthographic projection for a window with boundaries specified by rect.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The near and far clipping planes will be -1 and 1 respectively.
See also
frustum(), perspective()
Definition at line 1356 of file qmatrix4x4.cpp.
Referenced by ortho().
 {
     // Note: rect.right() and rect.bottom() subtract 1 in QRect,
     // which gives the location of a pixel within the rectangle,
     // instead of the extent of the rectangle.  We want the extent.
     // QRectF expresses the extent properly.
     ortho(rect.x(), rect.x() + rect.width(), rect.y() + rect.height(), rect.y(), -1.0f, 1.0f);
 }
ortho() [2/3]
void QMatrix4x4::ortho (const QRectF & rect)
Multiplies this matrix by another that applies an orthographic projection for a window with boundaries specified by rect.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The near and far clipping planes will be -1 and 1 respectively.
See also
frustum(), perspective()
Definition at line 1377 of file qmatrix4x4.cpp.
 {
     ortho(rect.left(), rect.right(), rect.bottom(), rect.top(), -1.0f, 1.0f);
 }
ortho() [3/3]
void QMatrix4x4::ortho (qreal left, qreal right, qreal bottom, qreal top, qreal nearPlane, qreal farPlane)
Multiplies this matrix by another that applies an orthographic projection for a window with lower-left corner (left, bottom), upper-right corner (right, top), and the specified nearPlane and farPlane clipping planes.
See also
frustum(), perspective()
Definition at line 1390 of file qmatrix4x4.cpp.
 {
     // Bail out if the projection volume is zero-sized.
     if (left == right || bottom == top || nearPlane == farPlane)
         return;
     // Construct the projection.
     qreal width = right - left;
     qreal invheight = top - bottom;
     qreal clip = farPlane - nearPlane;
 #ifndef QT_NO_VECTOR3D
     if (clip == 2.0f && (nearPlane + farPlane) == 0.0f) {
         // We can express this projection as a translate and scale
         // which will be more efficient to modify with further
         // transformations than producing a "General" matrix.
         translate(QVector3D
             (-(left + right) / width,
              -(top + bottom) / invheight,
              0.0f));
         scale(QVector3D
             (2.0f / width,
              2.0f / invheight,
              -1.0f));
         return;
     }
 #endif
     QMatrix4x4 m(1);
     m.m[0][0] = 2.0f / width;
     m.m[1][0] = 0.0f;
     m.m[2][0] = 0.0f;
     m.m[3][0] = -(left + right) / width;
     m.m[0][1] = 0.0f;
     m.m[1][1] = 2.0f / invheight;
     m.m[2][1] = 0.0f;
     m.m[3][1] = -(top + bottom) / invheight;
     m.m[0][2] = 0.0f;
     m.m[1][2] = 0.0f;
     m.m[2][2] = -2.0f / clip;
     m.m[3][2] = -(nearPlane + farPlane) / clip;
     m.m[0][3] = 0.0f;
     m.m[1][3] = 0.0f;
     m.m[2][3] = 0.0f;
     m.m[3][3] = 1.0f;
     // Apply the projection.
     *this *= m;
     return;
 }
orthonormalInverse()
QMatrix4x4 QMatrix4x4::orthonormalInverse () const private
Definition at line 1859 of file qmatrix4x4.cpp.
Referenced by inverted().
 {
     QMatrix4x4 result(1);  // The '1' says not to load identity
     result.m[0][0] = m[0][0];
     result.m[1][0] = m[0][1];
     result.m[2][0] = m[0][2];
     result.m[0][1] = m[1][0];
     result.m[1][1] = m[1][1];
     result.m[2][1] = m[1][2];
     result.m[0][2] = m[2][0];
     result.m[1][2] = m[2][1];
     result.m[2][2] = m[2][2];
     result.m[0][3] = 0.0f;
     result.m[1][3] = 0.0f;
     result.m[2][3] = 0.0f;
     result.m[3][0] = -(result.m[0][0] * m[3][0] + result.m[1][0] * m[3][1] + result.m[2][0] * m[3][2]);
     result.m[3][1] = -(result.m[0][1] * m[3][0] + result.m[1][1] * m[3][1] + result.m[2][1] * m[3][2]);
     result.m[3][2] = -(result.m[0][2] * m[3][0] + result.m[1][2] * m[3][1] + result.m[2][2] * m[3][2]);
     result.m[3][3] = 1.0f;
     return result;
 }
perspective()
void QMatrix4x4::perspective (qreal angle, qreal aspect, qreal nearPlane, qreal farPlane)
Multiplies this matrix by another that applies a perspective projection.
The field of view will be angle degrees within a window with a given aspect ratio. The projection will have the specified nearPlane and farPlane clipping planes.
See also
ortho(), frustum()
Definition at line 1487 of file qmatrix4x4.cpp.
 {
     // Bail out if the projection volume is zero-sized.
     if (nearPlane == farPlane || aspect == 0.0f)
         return;
     // Construct the projection.
     QMatrix4x4 m(1);
     qreal radians = (angle / 2.0f) * M_PI / 180.0f;
     qreal sine = qSin(radians);
     if (sine == 0.0f)
         return;
     qreal cotan = qCos(radians) / sine;
     qreal clip = farPlane - nearPlane;
     m.m[0][0] = cotan / aspect;
     m.m[1][0] = 0.0f;
     m.m[2][0] = 0.0f;
     m.m[3][0] = 0.0f;
     m.m[0][1] = 0.0f;
     m.m[1][1] = cotan;
     m.m[2][1] = 0.0f;
     m.m[3][1] = 0.0f;
     m.m[0][2] = 0.0f;
     m.m[1][2] = 0.0f;
     m.m[2][2] = -(nearPlane + farPlane) / clip;
     m.m[3][2] = -(2.0f * nearPlane * farPlane) / clip;
     m.m[0][3] = 0.0f;
     m.m[1][3] = 0.0f;
     m.m[2][3] = -1.0f;
     m.m[3][3] = 0.0f;
     // Apply the projection.
     *this *= m;
 }
projectedRotate()
void QMatrix4x4::projectedRotate (qreal angle, qreal x, qreal y, qreal z) private
Warning
This function is not part of the public interface.
Definition at line 1195 of file qmatrix4x4.cpp.
Referenced by QGraphicsRotation::applyTo().
 {
     // Used by QGraphicsRotation::applyTo() to perform a rotation
     // and projection back to 2D in a single step.
     if (angle == 0.0f)
         return;
     QMatrix4x4 m(1); // The "1" says to not load the identity.
     qreal c, s, ic;
     if (angle == 90.0f || angle == -270.0f) {
         s = 1.0f;
         c = 0.0f;
     } else if (angle == -90.0f || angle == 270.0f) {
         s = -1.0f;
         c = 0.0f;
     } else if (angle == 180.0f || angle == -180.0f) {
         s = 0.0f;
         c = -1.0f;
     } else {
         qreal a = angle * M_PI / 180.0f;
         c = qCos(a);
         s = qSin(a);
     }
     bool quick = false;
     if (x == 0.0f) {
         if (y == 0.0f) {
             if (z != 0.0f) {
                 // Rotate around the Z axis.
                 m.setToIdentity();
                 m.m[0][0] = c;
                 m.m[1][1] = c;
                 if (z < 0.0f) {
                     m.m[1][0] = s;
                     m.m[0][1] = -s;
                 } else {
                     m.m[1][0] = -s;
                     m.m[0][1] = s;
                 }
                 m.flagBits = General;
                 quick = true;
             }
         } else if (z == 0.0f) {
             // Rotate around the Y axis.
             m.setToIdentity();
             m.m[0][0] = c;
             m.m[2][2] = 1.0f;
             if (y < 0.0f) {
                 m.m[0][3] = -s * inv_dist_to_plane;
             } else {
                 m.m[0][3] = s * inv_dist_to_plane;
             }
             m.flagBits = General;
             quick = true;
         }
     } else if (y == 0.0f && z == 0.0f) {
         // Rotate around the X axis.
         m.setToIdentity();
         m.m[1][1] = c;
         m.m[2][2] = 1.0f;
         if (x < 0.0f) {
             m.m[1][3] = s * inv_dist_to_plane;
         } else {
             m.m[1][3] = -s * inv_dist_to_plane;
         }
         m.flagBits = General;
         quick = true;
     }
     if (!quick) {
         qreal len = x * x + y * y + z * z;
         if (!qFuzzyIsNull(len - 1.0f) && !qFuzzyIsNull(len)) {
             len = qSqrt(len);
             x /= len;
             y /= len;
             z /= len;
         }
         ic = 1.0f - c;
         m.m[0][0] = x * x * ic + c;
         m.m[1][0] = x * y * ic - z * s;
         m.m[2][0] = 0.0f;
         m.m[3][0] = 0.0f;
         m.m[0][1] = y * x * ic + z * s;
         m.m[1][1] = y * y * ic + c;
         m.m[2][1] = 0.0f;
         m.m[3][1] = 0.0f;
         m.m[0][2] = 0.0f;
         m.m[1][2] = 0.0f;
         m.m[2][2] = 1.0f;
         m.m[3][2] = 0.0f;
         m.m[0][3] = (x * z * ic - y * s) * -inv_dist_to_plane;
         m.m[1][3] = (y * z * ic + x * s) * -inv_dist_to_plane;
         m.m[2][3] = 0.0f;
         m.m[3][3] = 1.0f;
     }
     int flags = flagBits;
     *this *= m;
     if (flags != Identity)
         flagBits = flags | Rotation;
     else
         flagBits = Rotation;
 }
rotate() [1/3]
void QMatrix4x4::rotate (qreal angle, const QVector3D & vector)
Multiples this matrix by another that rotates coordinates through angle degrees about vector.
See also
scale(), translate()
Definition at line 1072 of file qmatrix4x4.cpp.
 {
     rotate(angle, vector.x(), vector.y(), vector.z());
 }
rotate() [2/3]
void QMatrix4x4::rotate (qreal angle, qreal x, qreal y, qreal z = 0.0f)
Multiplies this matrix by another that rotates coordinates through angle degrees about the vector (x, y, z).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
scale(), translate()
Definition at line 1090 of file qmatrix4x4.cpp.
 {
     if (angle == 0.0f)
         return;
     QMatrix4x4 m(1); // The "1" says to not load the identity.
     qreal c, s, ic;
     if (angle == 90.0f || angle == -270.0f) {
         s = 1.0f;
         c = 0.0f;
     } else if (angle == -90.0f || angle == 270.0f) {
         s = -1.0f;
         c = 0.0f;
     } else if (angle == 180.0f || angle == -180.0f) {
         s = 0.0f;
         c = -1.0f;
     } else {
         qreal a = angle * M_PI / 180.0f;
         c = qCos(a);
         s = qSin(a);
     }
     bool quick = false;
     if (x == 0.0f) {
         if (y == 0.0f) {
             if (z != 0.0f) {
                 // Rotate around the Z axis.
                 m.setToIdentity();
                 m.m[0][0] = c;
                 m.m[1][1] = c;
                 if (z < 0.0f) {
                     m.m[1][0] = s;
                     m.m[0][1] = -s;
                 } else {
                     m.m[1][0] = -s;
                     m.m[0][1] = s;
                 }
                 m.flagBits = General;
                 quick = true;
             }
         } else if (z == 0.0f) {
             // Rotate around the Y axis.
             m.setToIdentity();
             m.m[0][0] = c;
             m.m[2][2] = c;
             if (y < 0.0f) {
                 m.m[2][0] = -s;
                 m.m[0][2] = s;
             } else {
                 m.m[2][0] = s;
                 m.m[0][2] = -s;
             }
             m.flagBits = General;
             quick = true;
         }
     } else if (y == 0.0f && z == 0.0f) {
         // Rotate around the X axis.
         m.setToIdentity();
         m.m[1][1] = c;
         m.m[2][2] = c;
         if (x < 0.0f) {
             m.m[2][1] = s;
             m.m[1][2] = -s;
         } else {
             m.m[2][1] = -s;
             m.m[1][2] = s;
         }
         m.flagBits = General;
         quick = true;
     }
     if (!quick) {
         qreal len = x * x + y * y + z * z;
         if (!qFuzzyIsNull(len - 1.0f) && !qFuzzyIsNull(len)) {
             len = qSqrt(len);
             x /= len;
             y /= len;
             z /= len;
         }
         ic = 1.0f - c;
         m.m[0][0] = x * x * ic + c;
         m.m[1][0] = x * y * ic - z * s;
         m.m[2][0] = x * z * ic + y * s;
         m.m[3][0] = 0.0f;
         m.m[0][1] = y * x * ic + z * s;
         m.m[1][1] = y * y * ic + c;
         m.m[2][1] = y * z * ic - x * s;
         m.m[3][1] = 0.0f;
         m.m[0][2] = x * z * ic - y * s;
         m.m[1][2] = y * z * ic + x * s;
         m.m[2][2] = z * z * ic + c;
         m.m[3][2] = 0.0f;
         m.m[0][3] = 0.0f;
         m.m[1][3] = 0.0f;
         m.m[2][3] = 0.0f;
         m.m[3][3] = 1.0f;
     }
     int flags = flagBits;
     *this *= m;
     if (flags != Identity)
         flagBits = flags | Rotation;
     else
         flagBits = Rotation;
 }
rotate() [3/3]
void QMatrix4x4::rotate (const QQuaternion & quaternion)
Multiples this matrix by another that rotates coordinates according to a specified quaternion.
The quaternion is assumed to have been normalized.
See also
scale(), translate(), QQuaternion
Definition at line 1304 of file qmatrix4x4.cpp.
 {
     // Algorithm from:
     // http://www.j3d.org/matrix_faq/matrfaq_latest.html#Q54
     QMatrix4x4 m(1);
     qreal xx = quaternion.x() * quaternion.x();
     qreal xy = quaternion.x() * quaternion.y();
     qreal xz = quaternion.x() * quaternion.z();
     qreal xw = quaternion.x() * quaternion.scalar();
     qreal yy = quaternion.y() * quaternion.y();
     qreal yz = quaternion.y() * quaternion.z();
     qreal yw = quaternion.y() * quaternion.scalar();
     qreal zz = quaternion.z() * quaternion.z();
     qreal zw = quaternion.z() * quaternion.scalar();
     m.m[0][0] = 1.0f - 2 * (yy + zz);
     m.m[1][0] =        2 * (xy - zw);
     m.m[2][0] =        2 * (xz + yw);
     m.m[3][0] = 0.0f;
     m.m[0][1] =        2 * (xy + zw);
     m.m[1][1] = 1.0f - 2 * (xx + zz);
     m.m[2][1] =        2 * (yz - xw);
     m.m[3][1] = 0.0f;
     m.m[0][2] =        2 * (xz - yw);
     m.m[1][2] =        2 * (yz + xw);
     m.m[2][2] = 1.0f - 2 * (xx + yy);
     m.m[3][2] = 0.0f;
     m.m[0][3] = 0.0f;
     m.m[1][3] = 0.0f;
     m.m[2][3] = 0.0f;
     m.m[3][3] = 1.0f;
     int flags = flagBits;
     *this *= m;
     if (flags != Identity)
         flagBits = flags | Rotation;
     else
         flagBits = Rotation;
 }
row()
QVector4D QMatrix4x4::row (int index) const inline
Returns the elements of row index as a 4D vector.
See also
setRow(), column()
Definition at line 289 of file qmatrix4x4.h.
Referenced by copyDataTo(), operator<<(), operator>>(), QMatrix4x4(), and transposed().
 {
     Q_ASSERT(index >= 0 && index < 4);
     return QVector4D(m[0][index], m[1][index], m[2][index], m[3][index]);
 }
scale() [1/4]
void QMatrix4x4::scale (const QVector3D & vector)
Multiplies this matrix by another that scales coordinates by the components of vector.
See also
translate(), rotate()
Definition at line 775 of file qmatrix4x4.cpp.
Referenced by QGraphicsScale::applyTo(), ortho(), and ShaderEffectItem::renderEffect().
 {
     qreal vx = vector.x();
     qreal vy = vector.y();
     qreal vz = vector.z();
     if (flagBits == Identity) {
         m[0][0] = vx;
         m[1][1] = vy;
         m[2][2] = vz;
         flagBits = Scale;
     } else if (flagBits == Scale || flagBits == (Scale | Translation)) {
         m[0][0] *= vx;
         m[1][1] *= vy;
         m[2][2] *= vz;
     } else if (flagBits == Translation) {
         m[0][0] = vx;
         m[1][1] = vy;
         m[2][2] = vz;
         flagBits |= Scale;
     } else {
         m[0][0] *= vx;
         m[0][1] *= vx;
         m[0][2] *= vx;
         m[0][3] *= vx;
         m[1][0] *= vy;
         m[1][1] *= vy;
         m[1][2] *= vy;
         m[1][3] *= vy;
         m[2][0] *= vz;
         m[2][1] *= vz;
         m[2][2] *= vz;
         m[2][3] *= vz;
         flagBits = General;
     }
 }
scale() [2/4]
void QMatrix4x4::scale (qreal x, qreal y)
Multiplies this matrix by another that scales coordinates by the components x, and y.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
translate(), rotate()
Definition at line 823 of file qmatrix4x4.cpp.
 {
     if (flagBits == Identity) {
         m[0][0] = x;
         m[1][1] = y;
         flagBits = Scale;
     } else if (flagBits == Scale || flagBits == (Scale | Translation)) {
         m[0][0] *= x;
         m[1][1] *= y;
     } else if (flagBits == Translation) {
         m[0][0] = x;
         m[1][1] = y;
         flagBits |= Scale;
     } else {
         m[0][0] *= x;
         m[0][1] *= x;
         m[0][2] *= x;
         m[0][3] *= x;
         m[1][0] *= y;
         m[1][1] *= y;
         m[1][2] *= y;
         m[1][3] *= y;
         flagBits = General;
     }
 }
scale() [3/4]
void QMatrix4x4::scale (qreal x, qreal y, qreal z)
Multiplies this matrix by another that scales coordinates by the components x, y, and z.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
translate(), rotate()
Definition at line 860 of file qmatrix4x4.cpp.
 {
     if (flagBits == Identity) {
         m[0][0] = x;
         m[1][1] = y;
         m[2][2] = z;
         flagBits = Scale;
     } else if (flagBits == Scale || flagBits == (Scale | Translation)) {
         m[0][0] *= x;
         m[1][1] *= y;
         m[2][2] *= z;
     } else if (flagBits == Translation) {
         m[0][0] = x;
         m[1][1] = y;
         m[2][2] = z;
         flagBits |= Scale;
     } else {
         m[0][0] *= x;
         m[0][1] *= x;
         m[0][2] *= x;
         m[0][3] *= x;
         m[1][0] *= y;
         m[1][1] *= y;
         m[1][2] *= y;
         m[1][3] *= y;
         m[2][0] *= z;
         m[2][1] *= z;
         m[2][2] *= z;
         m[2][3] *= z;
         flagBits = General;
     }
 }
scale() [4/4]
void QMatrix4x4::scale (qreal factor)
Multiplies this matrix by another that scales coordinates by the given factor.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
translate(), rotate()
Definition at line 904 of file qmatrix4x4.cpp.
 {
     if (flagBits == Identity) {
         m[0][0] = factor;
         m[1][1] = factor;
         m[2][2] = factor;
         flagBits = Scale;
     } else if (flagBits == Scale || flagBits == (Scale | Translation)) {
         m[0][0] *= factor;
         m[1][1] *= factor;
         m[2][2] *= factor;
     } else if (flagBits == Translation) {
         m[0][0] = factor;
         m[1][1] = factor;
         m[2][2] = factor;
         flagBits |= Scale;
     } else {
         m[0][0] *= factor;
         m[0][1] *= factor;
         m[0][2] *= factor;
         m[0][3] *= factor;
         m[1][0] *= factor;
         m[1][1] *= factor;
         m[1][2] *= factor;
         m[1][3] *= factor;
         m[2][0] *= factor;
         m[2][1] *= factor;
         m[2][2] *= factor;
         m[2][3] *= factor;
         flagBits = General;
     }
 }
setColumn()
void QMatrix4x4::setColumn (int index, const QVector4D & value) inline
Sets the elements of column index to the components of value.
See also
column(), setRow()
Definition at line 279 of file qmatrix4x4.h.
 {
     Q_ASSERT(index >= 0 && index < 4);
     m[index][0] = value.x();
     m[index][1] = value.y();
     m[index][2] = value.z();
     m[index][3] = value.w();
     flagBits = General;
 }
setRow()
void QMatrix4x4::setRow (int index, const QVector4D & value) inline
Sets the elements of row index to the components of value.
See also
row(), setColumn()
Definition at line 295 of file qmatrix4x4.h.
 {
     Q_ASSERT(index >= 0 && index < 4);
     m[0][index] = value.x();
     m[1][index] = value.y();
     m[2][index] = value.z();
     m[3][index] = value.w();
     flagBits = General;
 }
setToIdentity()
void QMatrix4x4::setToIdentity () inline
Sets this matrix to the identity.
See also
isIdentity()
Definition at line 324 of file qmatrix4x4.h.
Referenced by projectedRotate(), and rotate().
 {
     m[0][0] = 1.0f;
     m[0][1] = 0.0f;
     m[0][2] = 0.0f;
     m[0][3] = 0.0f;
     m[1][0] = 0.0f;
     m[1][1] = 1.0f;
     m[1][2] = 0.0f;
     m[1][3] = 0.0f;
     m[2][0] = 0.0f;
     m[2][1] = 0.0f;
     m[2][2] = 1.0f;
     m[2][3] = 0.0f;
     m[3][0] = 0.0f;
     m[3][1] = 0.0f;
     m[3][2] = 0.0f;
     m[3][3] = 1.0f;
     flagBits = Identity;
 }
toAffine()
QMatrix QMatrix4x4::toAffine () const
Returns the conventional Qt 2D affine transformation matrix that corresponds to this matrix.
It is assumed that this matrix only contains 2D affine transformation elements.
See also
toTransform()
Definition at line 1613 of file qmatrix4x4.cpp.
 {
     return QMatrix(m[0][0], m[0][1],
                    m[1][0], m[1][1],
                    m[3][0], m[3][1]);
 }
toGenericMatrix()
template<int N, int M> QGenericMatrix< N, M, qreal > QMatrix4x4::toGenericMatrix () const
Constructs a NxM generic matrix from the left-most N columns and top-most M rows of this 4x4 matrix.
If N or M is greater than 4, then the remaining elements are filled with elements from the identity matrix.
Definition at line 243 of file qmatrix4x4.h.
 {
     QGenericMatrix<N, M, qreal> result;
     qreal *values = result.data();
     for (int matrixCol = 0; matrixCol < N; ++matrixCol) {
         for (int matrixRow = 0; matrixRow < M; ++matrixRow) {
             if (matrixCol < 4 && matrixRow < 4)
                 values[matrixCol * M + matrixRow] = m[matrixCol][matrixRow];
             else if (matrixCol == matrixRow)
                 values[matrixCol * M + matrixRow] = 1.0f;
             else
                 values[matrixCol * M + matrixRow] = 0.0f;
         }
     }
     return result;
 }
toTransform() [1/2]
QTransform QMatrix4x4::toTransform () const
Returns the conventional Qt 2D transformation matrix that corresponds to this matrix.
The returned QTransform is formed by simply dropping the third row and third column of the QMatrix4x4. This is suitable for implementing orthographic projections where the z co-ordinate should be dropped rather than projected.
See also
toAffine()
Definition at line 1631 of file qmatrix4x4.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QGraphicsItemPrivate::TransformData::computedFullTransform(), and QGraphicsItemGroup::removeFromGroup().
 {
     return QTransform(m[0][0], m[0][1], m[0][3],
                       m[1][0], m[1][1], m[1][3],
                       m[3][0], m[3][1], m[3][3]);
 }
toTransform() [2/2]
QTransform QMatrix4x4::toTransform (qreal distanceToPlane) const
Returns the conventional Qt 2D transformation matrix that corresponds to this matrix.
If distanceToPlane is non-zero, it indicates a projection factor to use to adjust for the z co-ordinate. The value of 1024 corresponds to the projection factor used by QTransform::rotate() for the x and y axes.
If distanceToPlane is zero, then the returned QTransform is formed by simply dropping the third row and third column of the QMatrix4x4. This is suitable for implementing orthographic projections where the z co-ordinate should be dropped rather than projected.
See also
toAffine()
Definition at line 1655 of file qmatrix4x4.cpp.
 {
     if (distanceToPlane == 1024.0f) {
         // Optimize the common case with constants.
         return QTransform(m[0][0], m[0][1],
                                 m[0][3] - m[0][2] * inv_dist_to_plane,
                           m[1][0], m[1][1],
                                 m[1][3] - m[1][2] * inv_dist_to_plane,
                           m[3][0], m[3][1],
                                 m[3][3] - m[3][2] * inv_dist_to_plane);
     } else if (distanceToPlane != 0.0f) {
         // The following projection matrix is pre-multiplied with "matrix":
         //      | 1 0 0 0 |
         //      | 0 1 0 0 |
         //      | 0 0 1 0 |
         //      | 0 0 d 1 |
         // where d = -1 / distanceToPlane.  After projection, row 3 and
         // column 3 are dropped to form the final QTransform.
         qreal d = 1.0f / distanceToPlane;
         return QTransform(m[0][0], m[0][1], m[0][3] - m[0][2] * d,
                           m[1][0], m[1][1], m[1][3] - m[1][2] * d,
                           m[3][0], m[3][1], m[3][3] - m[3][2] * d);
     } else {
         // Orthographic projection: drop row 3 and column 3.
         return QTransform(m[0][0], m[0][1], m[0][3],
                           m[1][0], m[1][1], m[1][3],
                           m[3][0], m[3][1], m[3][3]);
     }
 }
translate() [1/3]
void QMatrix4x4::translate (const QVector3D & vector)
Multiplies this matrix by another that translates coordinates by the components of vector.
See also
scale(), rotate()
Definition at line 944 of file qmatrix4x4.cpp.
Referenced by QDeclarativeTranslate::applyTo(), QGraphicsScale::applyTo(), QGraphicsRotation::applyTo(), lookAt(), ortho(), and ShaderEffectItem::renderEffect().
 {
     qreal vx = vector.x();
     qreal vy = vector.y();
     qreal vz = vector.z();
     if (flagBits == Identity) {
         m[3][0] = vx;
         m[3][1] = vy;
         m[3][2] = vz;
         flagBits = Translation;
     } else if (flagBits == Translation) {
         m[3][0] += vx;
         m[3][1] += vy;
         m[3][2] += vz;
     } else if (flagBits == Scale) {
         m[3][0] = m[0][0] * vx;
         m[3][1] = m[1][1] * vy;
         m[3][2] = m[2][2] * vz;
         flagBits |= Translation;
     } else if (flagBits == (Scale | Translation)) {
         m[3][0] += m[0][0] * vx;
         m[3][1] += m[1][1] * vy;
         m[3][2] += m[2][2] * vz;
     } else {
         m[3][0] += m[0][0] * vx + m[1][0] * vy + m[2][0] * vz;
         m[3][1] += m[0][1] * vx + m[1][1] * vy + m[2][1] * vz;
         m[3][2] += m[0][2] * vx + m[1][2] * vy + m[2][2] * vz;
         m[3][3] += m[0][3] * vx + m[1][3] * vy + m[2][3] * vz;
         if (flagBits == Rotation)
             flagBits |= Translation;
         else if (flagBits != (Rotation | Translation))
             flagBits = General;
     }
 }
translate() [2/3]
void QMatrix4x4::translate (qreal x, qreal y)
Multiplies this matrix by another that translates coordinates by the components x, and y.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
scale(), rotate()
Definition at line 992 of file qmatrix4x4.cpp.
 {
     if (flagBits == Identity) {
         m[3][0] = x;
         m[3][1] = y;
         flagBits = Translation;
     } else if (flagBits == Translation) {
         m[3][0] += x;
         m[3][1] += y;
     } else if (flagBits == Scale) {
         m[3][0] = m[0][0] * x;
         m[3][1] = m[1][1] * y;
         m[3][2] = 0.;
         flagBits |= Translation;
     } else if (flagBits == (Scale | Translation)) {
         m[3][0] += m[0][0] * x;
         m[3][1] += m[1][1] * y;
     } else {
         m[3][0] += m[0][0] * x + m[1][0] * y;
         m[3][1] += m[0][1] * x + m[1][1] * y;
         m[3][2] += m[0][2] * x + m[1][2] * y;
         m[3][3] += m[0][3] * x + m[1][3] * y;
         if (flagBits == Rotation)
             flagBits |= Translation;
         else if (flagBits != (Rotation | Translation))
             flagBits = General;
     }
 }
translate() [3/3]
void QMatrix4x4::translate (qreal x, qreal y, qreal z)
Multiplies this matrix by another that translates coordinates by the components x, y, and z.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
scale(), rotate()
Definition at line 1032 of file qmatrix4x4.cpp.
 {
     if (flagBits == Identity) {
         m[3][0] = x;
         m[3][1] = y;
         m[3][2] = z;
         flagBits = Translation;
     } else if (flagBits == Translation) {
         m[3][0] += x;
         m[3][1] += y;
         m[3][2] += z;
     } else if (flagBits == Scale) {
         m[3][0] = m[0][0] * x;
         m[3][1] = m[1][1] * y;
         m[3][2] = m[2][2] * z;
         flagBits |= Translation;
     } else if (flagBits == (Scale | Translation)) {
         m[3][0] += m[0][0] * x;
         m[3][1] += m[1][1] * y;
         m[3][2] += m[2][2] * z;
     } else {
         m[3][0] += m[0][0] * x + m[1][0] * y + m[2][0] * z;
         m[3][1] += m[0][1] * x + m[1][1] * y + m[2][1] * z;
         m[3][2] += m[0][2] * x + m[1][2] * y + m[2][2] * z;
         m[3][3] += m[0][3] * x + m[1][3] * y + m[2][3] * z;
         if (flagBits == Rotation)
             flagBits |= Translation;
         else if (flagBits != (Rotation | Translation))
             flagBits = General;
     }
 }
transposed()
QMatrix4x4 QMatrix4x4::transposed () const
Returns this matrix, transposed about its diagonal.
Definition at line 510 of file qmatrix4x4.cpp.
 {
     QMatrix4x4 result(1); // The "1" says to not load the identity.
     for (int row = 0; row < 4; ++row) {
         for (int col = 0; col < 4; ++col) {
             result.m[col][row] = m[row][col];
         }
     }
     return result;
 }
Friends and Related Functions
operator* [1/11]
QMatrix4x4 operator* (const QMatrix4x4 & m1, const QMatrix4x4 & m2) friend
Returns the product of m1 and m2.
Definition at line 529 of file qmatrix4x4.h.
 {
     if (m1.flagBits == QMatrix4x4::Identity)
         return m2;
     else if (m2.flagBits == QMatrix4x4::Identity)
         return m1;
     QMatrix4x4 m(1);
     m.m[0][0] = m1.m[0][0] * m2.m[0][0] +
                 m1.m[1][0] * m2.m[0][1] +
                 m1.m[2][0] * m2.m[0][2] +
                 m1.m[3][0] * m2.m[0][3];
     m.m[0][1] = m1.m[0][1] * m2.m[0][0] +
                 m1.m[1][1] * m2.m[0][1] +
                 m1.m[2][1] * m2.m[0][2] +
                 m1.m[3][1] * m2.m[0][3];
     m.m[0][2] = m1.m[0][2] * m2.m[0][0] +
                 m1.m[1][2] * m2.m[0][1] +
                 m1.m[2][2] * m2.m[0][2] +
                 m1.m[3][2] * m2.m[0][3];
     m.m[0][3] = m1.m[0][3] * m2.m[0][0] +
                 m1.m[1][3] * m2.m[0][1] +
                 m1.m[2][3] * m2.m[0][2] +
                 m1.m[3][3] * m2.m[0][3];
     m.m[1][0] = m1.m[0][0] * m2.m[1][0] +
                 m1.m[1][0] * m2.m[1][1] +
                 m1.m[2][0] * m2.m[1][2] +
                 m1.m[3][0] * m2.m[1][3];
     m.m[1][1] = m1.m[0][1] * m2.m[1][0] +
                 m1.m[1][1] * m2.m[1][1] +
                 m1.m[2][1] * m2.m[1][2] +
                 m1.m[3][1] * m2.m[1][3];
     m.m[1][2] = m1.m[0][2] * m2.m[1][0] +
                 m1.m[1][2] * m2.m[1][1] +
                 m1.m[2][2] * m2.m[1][2] +
                 m1.m[3][2] * m2.m[1][3];
     m.m[1][3] = m1.m[0][3] * m2.m[1][0] +
                 m1.m[1][3] * m2.m[1][1] +
                 m1.m[2][3] * m2.m[1][2] +
                 m1.m[3][3] * m2.m[1][3];
     m.m[2][0] = m1.m[0][0] * m2.m[2][0] +
                 m1.m[1][0] * m2.m[2][1] +
                 m1.m[2][0] * m2.m[2][2] +
                 m1.m[3][0] * m2.m[2][3];
     m.m[2][1] = m1.m[0][1] * m2.m[2][0] +
                 m1.m[1][1] * m2.m[2][1] +
                 m1.m[2][1] * m2.m[2][2] +
                 m1.m[3][1] * m2.m[2][3];
     m.m[2][2] = m1.m[0][2] * m2.m[2][0] +
                 m1.m[1][2] * m2.m[2][1] +
                 m1.m[2][2] * m2.m[2][2] +
                 m1.m[3][2] * m2.m[2][3];
     m.m[2][3] = m1.m[0][3] * m2.m[2][0] +
                 m1.m[1][3] * m2.m[2][1] +
                 m1.m[2][3] * m2.m[2][2] +
                 m1.m[3][3] * m2.m[2][3];
     m.m[3][0] = m1.m[0][0] * m2.m[3][0] +
                 m1.m[1][0] * m2.m[3][1] +
                 m1.m[2][0] * m2.m[3][2] +
                 m1.m[3][0] * m2.m[3][3];
     m.m[3][1] = m1.m[0][1] * m2.m[3][0] +
                 m1.m[1][1] * m2.m[3][1] +
                 m1.m[2][1] * m2.m[3][2] +
                 m1.m[3][1] * m2.m[3][3];
     m.m[3][2] = m1.m[0][2] * m2.m[3][0] +
                 m1.m[1][2] * m2.m[3][1] +
                 m1.m[2][2] * m2.m[3][2] +
                 m1.m[3][2] * m2.m[3][3];
     m.m[3][3] = m1.m[0][3] * m2.m[3][0] +
                 m1.m[1][3] * m2.m[3][1] +
                 m1.m[2][3] * m2.m[3][2] +
                 m1.m[3][3] * m2.m[3][3];
     return m;
 }
operator* [2/11]
QVector3D operator* (const QMatrix4x4 & matrix, const QVector3D & vector) friend
Returns the result of transforming vector according to matrix, with the matrix applied pre-vector.
Definition at line 631 of file qmatrix4x4.h.
 {
     qreal x, y, z, w;
     if (matrix.flagBits == QMatrix4x4::Identity) {
         return vector;
     } else if (matrix.flagBits == QMatrix4x4::Translation) {
         return QVector3D(vector.x() + matrix.m[3][0],
                          vector.y() + matrix.m[3][1],
                          vector.z() + matrix.m[3][2]);
     } else if (matrix.flagBits ==
                     (QMatrix4x4::Translation | QMatrix4x4::Scale)) {
         return QVector3D(vector.x() * matrix.m[0][0] + matrix.m[3][0],
                          vector.y() * matrix.m[1][1] + matrix.m[3][1],
                          vector.z() * matrix.m[2][2] + matrix.m[3][2]);
     } else if (matrix.flagBits == QMatrix4x4::Scale) {
         return QVector3D(vector.x() * matrix.m[0][0],
                          vector.y() * matrix.m[1][1],
                          vector.z() * matrix.m[2][2]);
     } else {
         x = vector.x() * matrix.m[0][0] +
             vector.y() * matrix.m[1][0] +
             vector.z() * matrix.m[2][0] +
             matrix.m[3][0];
         y = vector.x() * matrix.m[0][1] +
             vector.y() * matrix.m[1][1] +
             vector.z() * matrix.m[2][1] +
             matrix.m[3][1];
         z = vector.x() * matrix.m[0][2] +
             vector.y() * matrix.m[1][2] +
             vector.z() * matrix.m[2][2] +
             matrix.m[3][2];
         w = vector.x() * matrix.m[0][3] +
             vector.y() * matrix.m[1][3] +
             vector.z() * matrix.m[2][3] +
             matrix.m[3][3];
         if (w == 1.0f)
             return QVector3D(x, y, z);
         else
             return QVector3D(x / w, y / w, z / w);
     }
 }
operator* [3/11]
QVector3D operator* (const QVector3D & vector, const QMatrix4x4 & matrix) friend
Returns the result of transforming vector according to matrix, with the matrix applied post-vector.
Definition at line 606 of file qmatrix4x4.h.
 {
     qreal x, y, z, w;
     x = vector.x() * matrix.m[0][0] +
         vector.y() * matrix.m[0][1] +
         vector.z() * matrix.m[0][2] +
         matrix.m[0][3];
     y = vector.x() * matrix.m[1][0] +
         vector.y() * matrix.m[1][1] +
         vector.z() * matrix.m[1][2] +
         matrix.m[1][3];
     z = vector.x() * matrix.m[2][0] +
         vector.y() * matrix.m[2][1] +
         vector.z() * matrix.m[2][2] +
         matrix.m[2][3];
     w = vector.x() * matrix.m[3][0] +
         vector.y() * matrix.m[3][1] +
         vector.z() * matrix.m[3][2] +
         matrix.m[3][3];
     if (w == 1.0f)
         return QVector3D(x, y, z);
     else
         return QVector3D(x / w, y / w, z / w);
 }
operator* [4/11]
QVector4D operator* (const QVector4D & vector, const QMatrix4x4 & matrix) friend
Returns the result of transforming vector according to matrix, with the matrix applied post-vector.
Definition at line 677 of file qmatrix4x4.h.
 {
     qreal x, y, z, w;
     x = vector.x() * matrix.m[0][0] +
         vector.y() * matrix.m[0][1] +
         vector.z() * matrix.m[0][2] +
         vector.w() * matrix.m[0][3];
     y = vector.x() * matrix.m[1][0] +
         vector.y() * matrix.m[1][1] +
         vector.z() * matrix.m[1][2] +
         vector.w() * matrix.m[1][3];
     z = vector.x() * matrix.m[2][0] +
         vector.y() * matrix.m[2][1] +
         vector.z() * matrix.m[2][2] +
         vector.w() * matrix.m[2][3];
     w = vector.x() * matrix.m[3][0] +
         vector.y() * matrix.m[3][1] +
         vector.z() * matrix.m[3][2] +
         vector.w() * matrix.m[3][3];
     return QVector4D(x, y, z, w);
 }
operator* [5/11]
QVector4D operator* (const QMatrix4x4 & matrix, const QVector4D & vector) friend
Returns the result of transforming vector according to matrix, with the matrix applied pre-vector.
Definition at line 699 of file qmatrix4x4.h.
 {
     qreal x, y, z, w;
     x = vector.x() * matrix.m[0][0] +
         vector.y() * matrix.m[1][0] +
         vector.z() * matrix.m[2][0] +
         vector.w() * matrix.m[3][0];
     y = vector.x() * matrix.m[0][1] +
         vector.y() * matrix.m[1][1] +
         vector.z() * matrix.m[2][1] +
         vector.w() * matrix.m[3][1];
     z = vector.x() * matrix.m[0][2] +
         vector.y() * matrix.m[1][2] +
         vector.z() * matrix.m[2][2] +
         vector.w() * matrix.m[3][2];
     w = vector.x() * matrix.m[0][3] +
         vector.y() * matrix.m[1][3] +
         vector.z() * matrix.m[2][3] +
         vector.w() * matrix.m[3][3];
     return QVector4D(x, y, z, w);
 }
operator* [6/11]
QPoint operator* (const QPoint & point, const QMatrix4x4 & matrix) friend
Returns the result of transforming point according to matrix, with the matrix applied post-point.
Definition at line 723 of file qmatrix4x4.h.
 {
     qreal xin, yin;
     qreal x, y, w;
     xin = point.x();
     yin = point.y();
     x = xin * matrix.m[0][0] +
         yin * matrix.m[0][1] +
         matrix.m[0][3];
     y = xin * matrix.m[1][0] +
         yin * matrix.m[1][1] +
         matrix.m[1][3];
     w = xin * matrix.m[3][0] +
         yin * matrix.m[3][1] +
         matrix.m[3][3];
     if (w == 1.0f)
         return QPoint(qRound(x), qRound(y));
     else
         return QPoint(qRound(x / w), qRound(y / w));
 }
operator* [7/11]
QPointF operator* (const QPointF & point, const QMatrix4x4 & matrix) friend
Returns the result of transforming point according to matrix, with the matrix applied post-point.
Definition at line 744 of file qmatrix4x4.h.
 {
     qreal xin, yin;
     qreal x, y, w;
     xin = point.x();
     yin = point.y();
     x = xin * matrix.m[0][0] +
         yin * matrix.m[0][1] +
         matrix.m[0][3];
     y = xin * matrix.m[1][0] +
         yin * matrix.m[1][1] +
         matrix.m[1][3];
     w = xin * matrix.m[3][0] +
         yin * matrix.m[3][1] +
         matrix.m[3][3];
     if (w == 1.0f) {
         return QPointF(qreal(x), qreal(y));
     } else {
         return QPointF(qreal(x / w), qreal(y / w));
     }
 }
operator* [8/11]
QPoint operator* (const QMatrix4x4 & matrix, const QPoint & point) friend
Returns the result of transforming point according to matrix, with the matrix applied pre-point.
Definition at line 766 of file qmatrix4x4.h.
 {
     qreal xin, yin;
     qreal x, y, w;
     xin = point.x();
     yin = point.y();
     if (matrix.flagBits == QMatrix4x4::Identity) {
         return point;
     } else if (matrix.flagBits == QMatrix4x4::Translation) {
         return QPoint(qRound(xin + matrix.m[3][0]),
                       qRound(yin + matrix.m[3][1]));
     } else if (matrix.flagBits ==
                     (QMatrix4x4::Translation | QMatrix4x4::Scale)) {
         return QPoint(qRound(xin * matrix.m[0][0] + matrix.m[3][0]),
                       qRound(yin * matrix.m[1][1] + matrix.m[3][1]));
     } else if (matrix.flagBits == QMatrix4x4::Scale) {
         return QPoint(qRound(xin * matrix.m[0][0]),
                       qRound(yin * matrix.m[1][1]));
     } else {
         x = xin * matrix.m[0][0] +
             yin * matrix.m[1][0] +
             matrix.m[3][0];
         y = xin * matrix.m[0][1] +
             yin * matrix.m[1][1] +
             matrix.m[3][1];
         w = xin * matrix.m[0][3] +
             yin * matrix.m[1][3] +
             matrix.m[3][3];
         if (w == 1.0f)
             return QPoint(qRound(x), qRound(y));
         else
             return QPoint(qRound(x / w), qRound(y / w));
     }
 }
operator* [9/11]
QPointF operator* (const QMatrix4x4 & matrix, const QPointF & point) friend
Returns the result of transforming point according to matrix, with the matrix applied pre-point.
Definition at line 801 of file qmatrix4x4.h.
 {
     qreal xin, yin;
     qreal x, y, w;
     xin = point.x();
     yin = point.y();
     if (matrix.flagBits == QMatrix4x4::Identity) {
         return point;
     } else if (matrix.flagBits == QMatrix4x4::Translation) {
         return QPointF(xin + matrix.m[3][0],
                        yin + matrix.m[3][1]);
     } else if (matrix.flagBits ==
                     (QMatrix4x4::Translation | QMatrix4x4::Scale)) {
         return QPointF(xin * matrix.m[0][0] + matrix.m[3][0],
                        yin * matrix.m[1][1] + matrix.m[3][1]);
     } else if (matrix.flagBits == QMatrix4x4::Scale) {
         return QPointF(xin * matrix.m[0][0],
                        yin * matrix.m[1][1]);
     } else {
         x = xin * matrix.m[0][0] +
             yin * matrix.m[1][0] +
             matrix.m[3][0];
         y = xin * matrix.m[0][1] +
             yin * matrix.m[1][1] +
             matrix.m[3][1];
         w = xin * matrix.m[0][3] +
             yin * matrix.m[1][3] +
             matrix.m[3][3];
         if (w == 1.0f) {
             return QPointF(qreal(x), qreal(y));
         } else {
             return QPointF(qreal(x / w), qreal(y / w));
         }
     }
 }
operator* [10/11]
QMatrix4x4 operator* (qreal factor, const QMatrix4x4 & matrix) friend
Returns the result of multiplying all elements of matrix by factor.
Definition at line 859 of file qmatrix4x4.h.
 {
     QMatrix4x4 m(1);
     m.m[0][0] = matrix.m[0][0] * factor;
     m.m[0][1] = matrix.m[0][1] * factor;
     m.m[0][2] = matrix.m[0][2] * factor;
     m.m[0][3] = matrix.m[0][3] * factor;
     m.m[1][0] = matrix.m[1][0] * factor;
     m.m[1][1] = matrix.m[1][1] * factor;
     m.m[1][2] = matrix.m[1][2] * factor;
     m.m[1][3] = matrix.m[1][3] * factor;
     m.m[2][0] = matrix.m[2][0] * factor;
     m.m[2][1] = matrix.m[2][1] * factor;
     m.m[2][2] = matrix.m[2][2] * factor;
     m.m[2][3] = matrix.m[2][3] * factor;
     m.m[3][0] = matrix.m[3][0] * factor;
     m.m[3][1] = matrix.m[3][1] * factor;
     m.m[3][2] = matrix.m[3][2] * factor;
     m.m[3][3] = matrix.m[3][3] * factor;
     return m;
 }
operator* [11/11]
QMatrix4x4 operator* (const QMatrix4x4 & matrix, qreal factor) friend
Returns the result of multiplying all elements of matrix by factor.
Definition at line 881 of file qmatrix4x4.h.
 {
     QMatrix4x4 m(1);
     m.m[0][0] = matrix.m[0][0] * factor;
     m.m[0][1] = matrix.m[0][1] * factor;
     m.m[0][2] = matrix.m[0][2] * factor;
     m.m[0][3] = matrix.m[0][3] * factor;
     m.m[1][0] = matrix.m[1][0] * factor;
     m.m[1][1] = matrix.m[1][1] * factor;
     m.m[1][2] = matrix.m[1][2] * factor;
     m.m[1][3] = matrix.m[1][3] * factor;
     m.m[2][0] = matrix.m[2][0] * factor;
     m.m[2][1] = matrix.m[2][1] * factor;
     m.m[2][2] = matrix.m[2][2] * factor;
     m.m[2][3] = matrix.m[2][3] * factor;
     m.m[3][0] = matrix.m[3][0] * factor;
     m.m[3][1] = matrix.m[3][1] * factor;
     m.m[3][2] = matrix.m[3][2] * factor;
     m.m[3][3] = matrix.m[3][3] * factor;
     return m;
 }
operator+
QMatrix4x4 operator+ (const QMatrix4x4 & m1, const QMatrix4x4 & m2) friend
Returns the sum of m1 and m2.
Definition at line 485 of file qmatrix4x4.h.
 {
     QMatrix4x4 m(1);
     m.m[0][0] = m1.m[0][0] + m2.m[0][0];
     m.m[0][1] = m1.m[0][1] + m2.m[0][1];
     m.m[0][2] = m1.m[0][2] + m2.m[0][2];
     m.m[0][3] = m1.m[0][3] + m2.m[0][3];
     m.m[1][0] = m1.m[1][0] + m2.m[1][0];
     m.m[1][1] = m1.m[1][1] + m2.m[1][1];
     m.m[1][2] = m1.m[1][2] + m2.m[1][2];
     m.m[1][3] = m1.m[1][3] + m2.m[1][3];
     m.m[2][0] = m1.m[2][0] + m2.m[2][0];
     m.m[2][1] = m1.m[2][1] + m2.m[2][1];
     m.m[2][2] = m1.m[2][2] + m2.m[2][2];
     m.m[2][3] = m1.m[2][3] + m2.m[2][3];
     m.m[3][0] = m1.m[3][0] + m2.m[3][0];
     m.m[3][1] = m1.m[3][1] + m2.m[3][1];
     m.m[3][2] = m1.m[3][2] + m2.m[3][2];
     m.m[3][3] = m1.m[3][3] + m2.m[3][3];
     return m;
 }
operator- [1/2]
QMatrix4x4 operator- (const QMatrix4x4 & m1, const QMatrix4x4 & m2) friend
Returns the difference of m1 and m2.
Definition at line 507 of file qmatrix4x4.h.
 {
     QMatrix4x4 m(1);
     m.m[0][0] = m1.m[0][0] - m2.m[0][0];
     m.m[0][1] = m1.m[0][1] - m2.m[0][1];
     m.m[0][2] = m1.m[0][2] - m2.m[0][2];
     m.m[0][3] = m1.m[0][3] - m2.m[0][3];
     m.m[1][0] = m1.m[1][0] - m2.m[1][0];
     m.m[1][1] = m1.m[1][1] - m2.m[1][1];
     m.m[1][2] = m1.m[1][2] - m2.m[1][2];
     m.m[1][3] = m1.m[1][3] - m2.m[1][3];
     m.m[2][0] = m1.m[2][0] - m2.m[2][0];
     m.m[2][1] = m1.m[2][1] - m2.m[2][1];
     m.m[2][2] = m1.m[2][2] - m2.m[2][2];
     m.m[2][3] = m1.m[2][3] - m2.m[2][3];
     m.m[3][0] = m1.m[3][0] - m2.m[3][0];
     m.m[3][1] = m1.m[3][1] - m2.m[3][1];
     m.m[3][2] = m1.m[3][2] - m2.m[3][2];
     m.m[3][3] = m1.m[3][3] - m2.m[3][3];
     return m;
 }
operator- [2/2]
QMatrix4x4 operator- (const QMatrix4x4 & matrix) friend
Returns the negation of matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 837 of file qmatrix4x4.h.
 {
     QMatrix4x4 m(1);
     m.m[0][0] = -matrix.m[0][0];
     m.m[0][1] = -matrix.m[0][1];
     m.m[0][2] = -matrix.m[0][2];
     m.m[0][3] = -matrix.m[0][3];
     m.m[1][0] = -matrix.m[1][0];
     m.m[1][1] = -matrix.m[1][1];
     m.m[1][2] = -matrix.m[1][2];
     m.m[1][3] = -matrix.m[1][3];
     m.m[2][0] = -matrix.m[2][0];
     m.m[2][1] = -matrix.m[2][1];
     m.m[2][2] = -matrix.m[2][2];
     m.m[2][3] = -matrix.m[2][3];
     m.m[3][0] = -matrix.m[3][0];
     m.m[3][1] = -matrix.m[3][1];
     m.m[3][2] = -matrix.m[3][2];
     m.m[3][3] = -matrix.m[3][3];
     return m;
 }
operator/
QMatrix4x4 operator/ (const QMatrix4x4 & matrix, qreal divisor) friend
Returns the result of dividing all elements of matrix by divisor.
Definition at line 734 of file qmatrix4x4.cpp.
 {
     QMatrix4x4 m(1); // The "1" says to not load the identity.
     m.m[0][0] = matrix.m[0][0] / divisor;
     m.m[0][1] = matrix.m[0][1] / divisor;
     m.m[0][2] = matrix.m[0][2] / divisor;
     m.m[0][3] = matrix.m[0][3] / divisor;
     m.m[1][0] = matrix.m[1][0] / divisor;
     m.m[1][1] = matrix.m[1][1] / divisor;
     m.m[1][2] = matrix.m[1][2] / divisor;
     m.m[1][3] = matrix.m[1][3] / divisor;
     m.m[2][0] = matrix.m[2][0] / divisor;
     m.m[2][1] = matrix.m[2][1] / divisor;
     m.m[2][2] = matrix.m[2][2] / divisor;
     m.m[2][3] = matrix.m[2][3] / divisor;
     m.m[3][0] = matrix.m[3][0] / divisor;
     m.m[3][1] = matrix.m[3][1] / divisor;
     m.m[3][2] = matrix.m[3][2] / divisor;
     m.m[3][3] = matrix.m[3][3] / divisor;
     return m;
 }
operator<< [1/2]
Q_GUI_EXPORT QDebug operator<< (QDebug dbg, const QMatrix4x4 & m) friend
Definition at line 1955 of file qmatrix4x4.cpp.
 {
     // Create a string that represents the matrix type.
     QByteArray bits;
     if ((m.flagBits & QMatrix4x4::Identity) != 0)
         bits += "Identity,";
     if ((m.flagBits & QMatrix4x4::General) != 0)
         bits += "General,";
     if ((m.flagBits & QMatrix4x4::Translation) != 0)
         bits += "Translation,";
     if ((m.flagBits & QMatrix4x4::Scale) != 0)
         bits += "Scale,";
     if ((m.flagBits & QMatrix4x4::Rotation) != 0)
         bits += "Rotation,";
     if (bits.size() > 0)
         bits = bits.left(bits.size() - 1);
     // Output in row-major order because it is more human-readable.
     dbg.nospace() << "QMatrix4x4(type:" << bits.constData() << endl
         << qSetFieldWidth(10)
         << m(0, 0) << m(0, 1) << m(0, 2) << m(0, 3) << endl
         << m(1, 0) << m(1, 1) << m(1, 2) << m(1, 3) << endl
         << m(2, 0) << m(2, 1) << m(2, 2) << m(2, 3) << endl
         << m(3, 0) << m(3, 1) << m(3, 2) << m(3, 3) << endl
         << qSetFieldWidth(0) << ')';
     return dbg.space();
 }
operator<<() [2/2]
QDataStream & operator<< (QDataStream & stream, const QMatrix4x4 & matrix) related
Writes the given matrix to the given stream and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 2000 of file qmatrix4x4.cpp.
 {
     for (int row = 0; row < 4; ++row)
         for (int col = 0; col < 4; ++col)
             stream << double(matrix(row, col));
     return stream;
 }
operator>>()
QDataStream & operator>> (QDataStream & stream, QMatrix4x4 & matrix) related
Reads a 4x4 matrix from the given stream into the given matrix and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 2021 of file qmatrix4x4.cpp.
 {
     double x;
     for (int row = 0; row < 4; ++row) {
         for (int col = 0; col < 4; ++col) {
             stream >> x;
             matrix(row, col) = qreal(x);
         }
     }
     matrix.optimize();
     return stream;
 }
qFuzzyCompare
bool qFuzzyCompare (const QMatrix4x4 & m1, const QMatrix4x4 & m2) friend
Returns true if m1 and m2 are equal, allowing for a small fuzziness factor for floating-point comparisons; false otherwise.
Definition at line 903 of file qmatrix4x4.h.
 {
     return qFuzzyCompare(m1.m[0][0], m2.m[0][0]) &&
            qFuzzyCompare(m1.m[0][1], m2.m[0][1]) &&
            qFuzzyCompare(m1.m[0][2], m2.m[0][2]) &&
            qFuzzyCompare(m1.m[0][3], m2.m[0][3]) &&
            qFuzzyCompare(m1.m[1][0], m2.m[1][0]) &&
            qFuzzyCompare(m1.m[1][1], m2.m[1][1]) &&
            qFuzzyCompare(m1.m[1][2], m2.m[1][2]) &&
            qFuzzyCompare(m1.m[1][3], m2.m[1][3]) &&
            qFuzzyCompare(m1.m[2][0], m2.m[2][0]) &&
            qFuzzyCompare(m1.m[2][1], m2.m[2][1]) &&
            qFuzzyCompare(m1.m[2][2], m2.m[2][2]) &&
            qFuzzyCompare(m1.m[2][3], m2.m[2][3]) &&
            qFuzzyCompare(m1.m[3][0], m2.m[3][0]) &&
            qFuzzyCompare(m1.m[3][1], m2.m[3][1]) &&
            qFuzzyCompare(m1.m[3][2], m2.m[3][2]) &&
            qFuzzyCompare(m1.m[3][3], m2.m[3][3]);
 }
qGenericMatrixFromMatrix4x4()
QGenericMatrix< N, M, qreal > qGenericMatrixFromMatrix4x4 (const QMatrix4x4 & matrix) related
Returns a NxM generic matrix constructed from the left-most N columns and top-most M rows of matrix.
If N or M is greater than 4, then the remaining elements are filled with elements from the identity matrix.
See also
QMatrix4x4::toGenericMatrix()
Definition at line 997 of file qmatrix4x4.h.
 {
     QGenericMatrix<N, M, qreal> result;
     const qreal *m = matrix.constData();
     qreal *values = result.data();
     for (int col = 0; col < N; ++col) {
         for (int row = 0; row < M; ++row) {
             if (col < 4 && row < 4)
                 values[col * M + row] = m[col * 4 + row];
             else if (col == row)
                 values[col * M + row] = 1.0f;
             else
                 values[col * M + row] = 0.0f;
         }
     }
     return result;
 }
qGenericMatrixToMatrix4x4()
QMatrix4x4 qGenericMatrixToMatrix4x4 (const QGenericMatrix< N, M, qreal > & matrix) related
Returns a 4x4 matrix constructed from the left-most 4 columns and top-most 4 rows of matrix.
If matrix has less than 4 columns or rows, the remaining elements are filled with elements from the identity matrix.
See also
QMatrix4x4(const QGenericMatrix &)
Definition at line 991 of file qmatrix4x4.h.
 {
     return QMatrix4x4(matrix.constData(), N, M);
 }
QGraphicsRotation
friend class QGraphicsRotation friend
Definition at line 206 of file qmatrix4x4.h.
Properties
flagBits
int QMatrix4x4::flagBits private
Definition at line 189 of file qmatrix4x4.h.
Referenced by flipCoordinates(), inverted(), mapRect(), normalMatrix(), operator*(), operator*=(), operator/=(), operator<<(), optimize(), projectedRotate(), QMatrix4x4(), rotate(), scale(), and translate().
m
qreal QMatrix4x4::m[4][4] private
Definition at line 188 of file qmatrix4x4.h.
Referenced by frustum(), inverted(), lookAt(), operator!=(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator<<(), operator==(), ortho(), orthonormalInverse(), perspective(), projectedRotate(), qFuzzyCompare(), QMatrix4x4(), rotate(), and transposed().
The documentation for this class was generated from the following files:
/src/gui/math3d/qmatrix4x4.h
/src/gui/math3d/qmatrix4x4.cpp