Qt 4.8: QMetaMethodBuilder Class Reference
QMetaMethodBuilder Class Reference
The QMetaMethodBuilder class enables modifications to a method definition on a meta object builder.
#include <qmetaobjectbuilder_p.h>
Public Functions
QMetaMethod::Access access () const
Returns the access specification of this method (private, protected, or public).
int attributes () const
Returns the additional attributes for this method.
int index () const
Returns the index of this method within its QMetaObjectBuilder.
QMetaMethod::MethodType methodType () const
Returns the type of this method (signal, slot, method, or constructor).
QList< QByteArray > parameterNames () const
Returns the list of parameter names for this method.
QMetaMethodBuilder ()
QByteArray returnType () const
Returns the return type for this method; empty if the method's return type is void.
void setAccess (QMetaMethod::Access value)
Sets the access specification of this method (private, protected, or public) to value.
void setAttributes (int value)
Sets the additional attributes for this method to value.
void setParameterNames (const QList< QByteArray > &value)
Sets the list of parameter names for this method to value.
void setReturnType (const QByteArray &value)
Sets the return type for this method to value.
void setTag (const QByteArray &value)
Sets the tag associated with this method to value.
QByteArray signature () const
Returns the signature of this method.
QByteArray tag () const
Returns the tag associated with this method.
Private Functions
QMetaMethodBuilderPrivate * d_func () const
QMetaMethodBuilder (const QMetaObjectBuilder *mobj, int index)
Properties
int _index
const QMetaObjectBuilder * _mobj
Friends
class QMetaObjectBuilder
class QMetaPropertyBuilder
Detailed Description
The QMetaMethodBuilder class enables modifications to a method definition on a meta object builder.
Warning
This function is not part of the public interface.
Definition at line 198 of file qmetaobjectbuilder_p.h.
Constructors and Destructors
QMetaMethodBuilder() [1/2]
QMetaMethodBuilder::QMetaMethodBuilder () inline
Warning
This function is not part of the public interface.
Definition at line 201 of file qmetaobjectbuilder_p.h.
 : _mobj(0), _index(0) {}
QMetaMethodBuilder() [2/2]
QMetaMethodBuilder::QMetaMethodBuilder (const QMetaObjectBuilder * mobj, int index) inline private
Definition at line 230 of file qmetaobjectbuilder_p.h.
         : _mobj(mobj), _index(index) {}
Functions
access()
QMetaMethod::Access QMetaMethodBuilder::access () const
Returns the access specification of this method (private, protected, or public).
The default value is QMetaMethod::Public for methods, slots, and constructors. The default value is QMetaMethod::Protected for signals.
See also
setAccess()
Definition at line 1977 of file qmetaobjectbuilder.cpp.
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d)
         return d->access();
     else
         return QMetaMethod::Public;
 }
attributes()
int QMetaMethodBuilder::attributes () const
Returns the additional attributes for this method.
See also
setAttributes()
Definition at line 2005 of file qmetaobjectbuilder.cpp.
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d)
         return (d->attributes >> 4);
     else
         return 0;
 }
d_func()
QMetaMethodBuilderPrivate * QMetaMethodBuilder::d_func () const private
Definition at line 1835 of file qmetaobjectbuilder.cpp.
 {
     // Positive indices indicate methods, negative indices indicate constructors.
     if (_mobj && _index >= 0 && _index < _mobj->d->methods.size())
         return &(_mobj->d->methods[_index]);
     else if (_mobj && -_index >= 1 && -_index <= _mobj->d->constructors.size())
         return &(_mobj->d->constructors[(-_index) - 1]);
     else
         return 0;
 }
index()
int QMetaMethodBuilder::index () const
Returns the index of this method within its QMetaObjectBuilder.
Definition at line 1854 of file qmetaobjectbuilder.cpp.
 {
     if (_index >= 0)
         return _index;          // Method, signal, or slot
     else
         return (-_index) - 1;   // Constructor
 }
methodType()
QMetaMethod::MethodType QMetaMethodBuilder::methodType () const
Returns the type of this method (signal, slot, method, or constructor).
Definition at line 1865 of file qmetaobjectbuilder.cpp.
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d)
         return d->methodType();
     else
         return QMetaMethod::Method;
 }
parameterNames()
QList< QByteArray > QMetaMethodBuilder::parameterNames () const
Returns the list of parameter names for this method.
See also
setParameterNames()
Definition at line 1922 of file qmetaobjectbuilder.cpp.
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d)
         return d->parameterNames;
     else
         return QList<QByteArray>();
 }
returnType()
QByteArray QMetaMethodBuilder::returnType () const
Returns the return type for this method; empty if the method's return type is void.
See also
setReturnType(), signature()
Definition at line 1894 of file qmetaobjectbuilder.cpp.
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d)
         return d->returnType;
     else
         return QByteArray();
 }
setAccess()
void QMetaMethodBuilder::setAccess (QMetaMethod::Access value)
Sets the access specification of this method (private, protected, or public) to value.
If the method is a signal, this function will be ignored.
See also
access()
Definition at line 1993 of file qmetaobjectbuilder.cpp.
Referenced by QMetaObjectBuilder::addMethod(), and for().
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d && d->methodType() != QMetaMethod::Signal)
         d->setAccess(value);
 }
setAttributes()
void QMetaMethodBuilder::setAttributes (int value)
Sets the additional attributes for this method to value.
See also
attributes()
Definition at line 2019 of file qmetaobjectbuilder.cpp.
Referenced by QMetaObjectBuilder::addMethod().
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d)
         d->attributes = ((d->attributes & 0x0f) | (value << 4));
 }
setParameterNames()
void QMetaMethodBuilder::setParameterNames (const QList< QByteArray > & value)
Sets the list of parameter names for this method to value.
See also
parameterNames()
Definition at line 1936 of file qmetaobjectbuilder.cpp.
Referenced by QMetaObjectBuilder::addMethod(), and QDeclarativeCompiler::buildDynamicMeta().
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d)
         d->parameterNames = value;
 }
setReturnType()
void QMetaMethodBuilder::setReturnType (const QByteArray & value)
Sets the return type for this method to value.
If value is empty, then the method's return type is void. The value will be normalized before it is added to the method.
See also
returnType(), signature()
Definition at line 1910 of file qmetaobjectbuilder.cpp.
Referenced by QMetaObjectBuilder::addConstructor(), QMetaObjectBuilder::addMethod(), and QDeclarativeCompiler::buildDynamicMeta().
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d)
         d->returnType = QMetaObject::normalizedType(value);
 }
setTag()
void QMetaMethodBuilder::setTag (const QByteArray & value)
Sets the tag associated with this method to value.
See also
setTag()
Definition at line 1962 of file qmetaobjectbuilder.cpp.
Referenced by QMetaObjectBuilder::addMethod().
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d)
         d->tag = value;
 }
signature()
QByteArray QMetaMethodBuilder::signature () const
Returns the signature of this method.
See also
parameterNames(), returnType()
Definition at line 1879 of file qmetaobjectbuilder.cpp.
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d)
         return d->signature;
     else
         return QByteArray();
 }
tag()
QByteArray QMetaMethodBuilder::tag () const
Returns the tag associated with this method.
See also
setTag()
Definition at line 1948 of file qmetaobjectbuilder.cpp.
 {
     QMetaMethodBuilderPrivate *d = d_func();
     if (d)
         return d->tag;
     else
         return QByteArray();
 }
Friends and Related Functions
QMetaObjectBuilder
friend class QMetaObjectBuilder friend
Definition at line 227 of file qmetaobjectbuilder_p.h.
QMetaPropertyBuilder
friend class QMetaPropertyBuilder friend
Definition at line 228 of file qmetaobjectbuilder_p.h.
Properties
_index
int QMetaMethodBuilder::_index private
Definition at line 225 of file qmetaobjectbuilder_p.h.
Referenced by QMetaPropertyBuilder::setNotifySignal().
_mobj
const QMetaObjectBuilder* QMetaMethodBuilder::_mobj private
Definition at line 224 of file qmetaobjectbuilder_p.h.
Referenced by QMetaPropertyBuilder::setNotifySignal().
The documentation for this class was generated from the following files:
/src/declarative/qml/qmetaobjectbuilder_p.h
/src/declarative/qml/qmetaobjectbuilder.cpp