Qt 4.8: QPainter Class Reference
QPainter Class Reference
The QPainter class performs low-level painting on widgets and other paint devices.
#include <qpainter.h>
Classes
class PixmapFragment
This class is used in conjunction with the QPainter::drawPixmapFragments() function to specify how a pixmap, or sub-rect of a pixmap, is drawn.
Public Types
enum CompositionMode {
CompositionMode_SourceOver, CompositionMode_DestinationOver, CompositionMode_Clear, CompositionMode_Source,
CompositionMode_Destination, CompositionMode_SourceIn, CompositionMode_DestinationIn, CompositionMode_SourceOut,
CompositionMode_DestinationOut, CompositionMode_SourceAtop, CompositionMode_DestinationAtop, CompositionMode_Xor,
CompositionMode_Plus, CompositionMode_Multiply, CompositionMode_Screen, CompositionMode_Overlay,
CompositionMode_Darken, CompositionMode_Lighten, CompositionMode_ColorDodge, CompositionMode_ColorBurn,
CompositionMode_HardLight, CompositionMode_SoftLight, CompositionMode_Difference, CompositionMode_Exclusion,
RasterOp_SourceOrDestination, RasterOp_SourceAndDestination, RasterOp_SourceXorDestination, RasterOp_NotSourceAndNotDestination,
RasterOp_NotSourceOrNotDestination, RasterOp_NotSourceXorDestination, RasterOp_NotSource, RasterOp_NotSourceAndDestination,
RasterOp_SourceAndNotDestination
}
Defines the modes supported for digital image compositing.
enum PixmapFragmentHint { OpaqueHint = 0x01 }
enum RenderHint {
Antialiasing = 0x01, TextAntialiasing = 0x02, SmoothPixmapTransform = 0x04, HighQualityAntialiasing = 0x08,
NonCosmeticDefaultPen = 0x10
}
Renderhints are used to specify flags to QPainter that may or may not be respected by any given engine.
Public Functions
const QBrush & background () const
Returns the current background brush.
Qt::BGMode backgroundMode () const
Returns the current background mode.
bool begin (QPaintDevice *)
Begins painting the paint device and returns true if successful; otherwise returns false.
void beginNativePainting ()
Flushes the painting pipeline and prepares for the user issuing commands directly to the underlying graphics context.
QRectF boundingRect (const QRectF &rect, int flags, const QString &text)
Returns the bounding rectangle of the text as it will appear when drawn inside the given rectangle with the specified flags using the currently set font(); i.
QRect boundingRect (const QRect &rect, int flags, const QString &text)
Returns the bounding rectangle of the text as it will appear when drawn inside the given rectangle with the specified flags using the currently set font().
QRect boundingRect (int x, int y, int w, int h, int flags, const QString &text)
Returns the bounding rectangle of the given text as it will appear when drawn inside the rectangle beginning at the point ({x}, {y}) with width w and height h.
QRectF boundingRect (const QRectF &rect, const QString &text, const QTextOption &o=QTextOption())
Instead of specifying flags as a bitwise OR of the Qt::AlignmentFlag and Qt::TextFlag, this overloaded function takes an option argument.
const QBrush & brush () const
Returns the painter's current brush.
QPoint brushOrigin () const
Returns the currently set brush origin.
QRectF clipBoundingRect () const
Returns the bounding rectangle of the current clip if there is a clip; otherwise returns an empty rectangle.
QPainterPath clipPath () const
Returns the currently clip as a path.
QRegion clipRegion () const
Returns the currently set clip region.
QMatrix combinedMatrix () const
Returns the transformation matrix combining the current window/viewport and world transformation.
QTransform combinedTransform () const
Returns the transformation matrix combining the current window/viewport and world transformation.
CompositionMode compositionMode () const
Returns the current composition mode.
QPaintDevice * device () const
Returns the paint device on which this painter is currently painting, or 0 if the painter is not active.
const QMatrix & deviceMatrix () const
Returns the matrix that transforms from logical coordinates to device coordinates of the platform dependent paint device.
const QTransform & deviceTransform () const
Returns the matrix that transforms from logical coordinates to device coordinates of the platform dependent paint device.
void drawArc (const QRectF &rect, int a, int alen)
Draws the arc defined by the given rectangle, startAngle and spanAngle.
void drawArc (const QRect &, int a, int alen)
Draws the arc defined by the given rectangle, startAngle and spanAngle.
void drawArc (int x, int y, int w, int h, int a, int alen)
Draws the arc defined by the rectangle beginning at (x, y) with the specified width and height, and the given startAngle and spanAngle.
void drawChord (const QRectF &rect, int a, int alen)
Draws the chord defined by the given rectangle, startAngle and spanAngle.
void drawChord (int x, int y, int w, int h, int a, int alen)
Draws the chord defined by the rectangle beginning at (x, y) with the specified width and height, and the given startAngle and spanAngle.
void drawChord (const QRect &, int a, int alen)
Draws the chord defined by the given rectangle, startAngle and spanAngle.
void drawConvexPolygon (const QPointF *points, int pointCount)
Draws the convex polygon defined by the first pointCount points in the array points using the current pen.
void drawConvexPolygon (const QPolygonF &polygon)
Draws the convex polygon defined by polygon using the current pen and brush.
void drawConvexPolygon (const QPoint *points, int pointCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the convex polygon defined by the first pointCount points in the array points using the current pen.
void drawConvexPolygon (const QPolygon &polygon)
Draws the convex polygon defined by polygon using the current pen and brush.
void drawEllipse (const QRectF &r)
Draws the ellipse defined by the given rectangle.
void drawEllipse (const QRect &r)
Draws the ellipse defined by the given rectangle.
void drawEllipse (int x, int y, int w, int h)
Draws the ellipse defined by the rectangle beginning at ({x}, {y}) with the given width and height.
void drawEllipse (const QPointF &center, qreal rx, qreal ry)
Draws the ellipse positioned at {center} with radii {rx} and {ry}.
void drawEllipse (const QPoint &center, int rx, int ry)
Draws the ellipse positioned at {center} with radii {rx} and {ry}.
void drawGlyphRun (const QPointF &position, const QGlyphRun &glyphRun)
Draws the specified glyphs at the given position.
void drawImage (const QRectF &targetRect, const QImage &image, const QRectF &sourceRect, Qt::ImageConversionFlags flags=Qt::AutoColor)
void drawImage (const QRect &targetRect, const QImage &image, const QRect &sourceRect, Qt::ImageConversionFlags flags=Qt::AutoColor)
void drawImage (const QPointF &p, const QImage &image, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
void drawImage (const QPoint &p, const QImage &image, const QRect &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
void drawImage (const QRectF &r, const QImage &image)
Draws the given image into the given rectangle.
void drawImage (const QRect &r, const QImage &image)
Draws the given image into the given rectangle.
void drawImage (const QPointF &p, const QImage &image)
Draws the given image at the given point.
void drawImage (const QPoint &p, const QImage &image)
Draws the given image at the given point.
void drawImage (int x, int y, const QImage &image, int sx=0, int sy=0, int sw=-1, int sh=-1, Qt::ImageConversionFlags flags=Qt::AutoColor)
void drawLine (const QLineF &line)
Draws a line defined by line.
void drawLine (const QLine &line)
Draws a line defined by line.
void drawLine (int x1, int y1, int x2, int y2)
Draws a line from (x1, y1) to (x2, y2) and sets the current pen position to (x2, y2).
void drawLine (const QPoint &p1, const QPoint &p2)
Draws a line from p1 to p2.
void drawLine (const QPointF &p1, const QPointF &p2)
Draws a line from p1 to p2.
void drawLines (const QLineF *lines, int lineCount)
Draws the first lineCount lines in the array lines using the current pen.
void drawLines (const QVector< QLineF > &lines)
Draws the set of lines defined by the list lines using the current pen and brush.
void drawLines (const QPointF *pointPairs, int lineCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the first lineCount lines in the array pointPairs using the current pen.
void drawLines (const QVector< QPointF > &pointPairs)
Draws a line for each pair of points in the vector pointPairs using the current pen.
void drawLines (const QLine *lines, int lineCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the first lineCount lines in the array lines using the current pen.
void drawLines (const QVector< QLine > &lines)
Draws the set of lines defined by the list lines using the current pen and brush.
void drawLines (const QPoint *pointPairs, int lineCount)
Draws the first lineCount lines in the array pointPairs using the current pen.
void drawLines (const QVector< QPoint > &pointPairs)
Draws a line for each pair of points in the vector pointPairs using the current pen.
void drawPath (const QPainterPath &path)
Draws the given painter path using the current pen for outline and the current brush for filling.
void drawPicture (const QPointF &p, const QPicture &picture)
Replays the given picture at the given point.
void drawPicture (int x, int y, const QPicture &picture)
Draws the given picture at point (x, y).
void drawPicture (const QPoint &p, const QPicture &picture)
Replays the given picture at the given point.
void drawPie (const QRectF &rect, int a, int alen)
Draws a pie defined by the given rectangle, startAngle and and spanAngle.
void drawPie (int x, int y, int w, int h, int a, int alen)
void drawPie (const QRect &, int a, int alen)
Draws a pie defined by the given rectangle, startAngle and and spanAngle.
void drawPixmap (const QRectF &targetRect, const QPixmap &pixmap, const QRectF &sourceRect)
Draws the rectangular portion source of the given pixmap into the given target in the paint device.
void drawPixmap (const QRect &targetRect, const QPixmap &pixmap, const QRect &sourceRect)
Draws the rectangular portion source of the given pixmap into the given target in the paint device.
void drawPixmap (int x, int y, int w, int h, const QPixmap &pm, int sx, int sy, int sw, int sh)
Draws the rectangular portion with the origin ({sx}, {sy}), width sw and height sh, of the given pixmap , at the point ({x}, {y}), with a width of w and a height of h.
void drawPixmap (int x, int y, const QPixmap &pm, int sx, int sy, int sw, int sh)
Draws a pixmap at ({x}, {y}) by copying a part of the given pixmap into the paint device.
void drawPixmap (const QPointF &p, const QPixmap &pm, const QRectF &sr)
Draws the rectangular portion source of the given pixmap with its origin at the given point.
void drawPixmap (const QPoint &p, const QPixmap &pm, const QRect &sr)
Draws the rectangular portion source of the given pixmap with its origin at the given point.
void drawPixmap (const QPointF &p, const QPixmap &pm)
Draws the given pixmap with its origin at the given point.
void drawPixmap (const QPoint &p, const QPixmap &pm)
Draws the given pixmap with its origin at the given point.
void drawPixmap (int x, int y, const QPixmap &pm)
Draws the given pixmap at position ({x}, {y}).
void drawPixmap (const QRect &r, const QPixmap &pm)
Draws the given pixmap into the given rectangle.
void drawPixmap (int x, int y, int w, int h, const QPixmap &pm)
Draws the pixmap into the rectangle at position ({x}, {y}) with the given width and height.
void drawPixmapFragments (const PixmapFragment *fragments, int fragmentCount, const QPixmap &pixmap, PixmapFragmentHints hints=0)
This function is used to draw pixmap, or a sub-rectangle of pixmap, at multiple positions with different scale, rotation and opacity.
void drawPixmapFragments (const QRectF *targetRects, const QRectF *sourceRects, int fragmentCount, const QPixmap &pixmap, PixmapFragmentHints hints=0)
This function is used to draw the same pixmap with multiple target and source rectangles specified by targetRects.
void drawPoint (const QPointF &pt)
Draws a single point at the given position using the current pen's color.
void drawPoint (const QPoint &p)
Draws a single point at the given position using the current pen's color.
void drawPoint (int x, int y)
Draws a single point at position (x, y).
void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the array points using the current pen's color.
void drawPoints (const QPolygonF &points)
Draws the points in the vector points.
void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the array points using the current pen's color.
void drawPoints (const QPolygon &points)
Draws the points in the vector points.
void drawPolygon (const QPointF *points, int pointCount, Qt::FillRule fillRule=Qt::OddEvenFill)
Draws the polygon defined by the first pointCount points in the array points using the current pen and brush.
void drawPolygon (const QPolygonF &polygon, Qt::FillRule fillRule=Qt::OddEvenFill)
Draws the polygon defined by the given points using the fill rule fillRule.
void drawPolygon (const QPoint *points, int pointCount, Qt::FillRule fillRule=Qt::OddEvenFill)
Draws the polygon defined by the first pointCount points in the array points.
void drawPolygon (const QPolygon &polygon, Qt::FillRule fillRule=Qt::OddEvenFill)
Draws the polygon defined by the given points using the fill rule fillRule.
void drawPolyline (const QPointF *points, int pointCount)
Draws the polyline defined by the first pointCount points in points using the current pen.
void drawPolyline (const QPolygonF &polyline)
Draws the polyline defined by the given points using the current pen.
void drawPolyline (const QPoint *points, int pointCount)
Draws the polyline defined by the first pointCount points in points using the current pen.
void drawPolyline (const QPolygon &polygon)
Draws the polyline defined by the given points using the current pen.
void drawRect (const QRectF &rect)
Draws the current rectangle with the current pen and brush.
void drawRect (int x1, int y1, int w, int h)
Draws a rectangle with upper left corner at ({x}, {y}) and with the given width and height.
void drawRect (const QRect &rect)
Draws the current rectangle with the current pen and brush.
void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount of the given rectangles using the current pen and brush.
void drawRects (const QVector< QRectF > &rectangles)
Draws the given rectangles using the current pen and brush.
void drawRects (const QRect *rects, int rectCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the first rectCount of the given rectangles using the current pen and brush.
void drawRects (const QVector< QRect > &rectangles)
Draws the given rectangles using the current pen and brush.
void drawRoundedRect (const QRectF &rect, qreal xRadius, qreal yRadius, Qt::SizeMode mode=Qt::AbsoluteSize)
Draws the given rectangle rect with rounded corners.
void drawRoundedRect (int x, int y, int w, int h, qreal xRadius, qreal yRadius, Qt::SizeMode mode=Qt::AbsoluteSize)
void drawRoundedRect (const QRect &rect, qreal xRadius, qreal yRadius, Qt::SizeMode mode=Qt::AbsoluteSize)
void drawRoundRect (const QRectF &r, int xround=25, int yround=25)
Draws a rectangle r with rounded corners.
void drawRoundRect (int x, int y, int w, int h, int=25, int=25)
Draws the rectangle x, y, w, h with rounded corners.
void drawRoundRect (const QRect &r, int xround=25, int yround=25)
Draws the rectangle r with rounded corners.
void drawStaticText (const QPointF &topLeftPosition, const QStaticText &staticText)
Draws the given staticText at the given topLeftPosition.
void drawStaticText (const QPoint &topLeftPosition, const QStaticText &staticText)
Draws the staticText at the topLeftPosition.
void drawStaticText (int left, int top, const QStaticText &staticText)
Draws the staticText at coordinates left and top.
void drawText (const QPointF &p, const QString &s)
Draws the given text with the currently defined text direction, beginning at the given position.
void drawText (const QPoint &p, const QString &s)
Draws the given text with the currently defined text direction, beginning at the given position.
void drawText (int x, int y, const QString &s)
Draws the given text at position ({x}, {y}), using the painter's currently defined text direction.
void drawText (const QPointF &p, const QString &str, int tf, int justificationPadding)
void drawText (const QRectF &r, int flags, const QString &text, QRectF *br=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the given text within the provided rectangle.
void drawText (const QRect &r, int flags, const QString &text, QRect *br=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the given text within the provided rectangle according to the specified flags.
void drawText (int x, int y, int w, int h, int flags, const QString &text, QRect *br=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the given text within the rectangle with origin ({x}, {y}), width and height.
void drawText (const QRectF &r, const QString &text, const QTextOption &o=QTextOption())
Draws the given text in the rectangle specified using the option to control its positioning and orientation.
void drawTextItem (const QPointF &p, const QTextItem &ti)
Draws the text item ti at position p.
void drawTextItem (int x, int y, const QTextItem &ti)
void drawTextItem (const QPoint &p, const QTextItem &ti)
Draws the text item ti at position p.
void drawTiledPixmap (const QRectF &rect, const QPixmap &pm, const QPointF &offset=QPointF())
Draws a tiled pixmap, inside the given rectangle with its origin at the given position.
void drawTiledPixmap (int x, int y, int w, int h, const QPixmap &, int sx=0, int sy=0)
void drawTiledPixmap (const QRect &, const QPixmap &, const QPoint &=QPoint())
Draws a tiled pixmap, inside the given rectangle with its origin at the given position.
bool end ()
Ends painting.
void endNativePainting ()
Restores the painter after manually issuing native painting commands.
void eraseRect (const QRectF &)
Erases the area inside the given rectangle.
void eraseRect (int x, int y, int w, int h)
Erases the area inside the rectangle beginning at (x, y) with the given width and height.
void eraseRect (const QRect &)
Erases the area inside the given rectangle.
void fillPath (const QPainterPath &path, const QBrush &brush)
Fills the given path using the given brush.
void fillRect (const QRectF &, const QBrush &)
Fills the given rectangle with the brush specified.
void fillRect (int x, int y, int w, int h, const QBrush &)
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the given brush.
void fillRect (const QRect &, const QBrush &)
Fills the given rectangle with the specified brush.
void fillRect (const QRectF &, const QColor &color)
Fills the given rectangle with the color specified.
void fillRect (int x, int y, int w, int h, const QColor &color)
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the given color.
void fillRect (const QRect &, const QColor &color)
Fills the given rectangle with the color specified.
void fillRect (int x, int y, int w, int h, Qt::GlobalColor c)
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the given color.
void fillRect (const QRect &r, Qt::GlobalColor c)
Fills the given rectangle with the specified color.
void fillRect (const QRectF &r, Qt::GlobalColor c)
Fills the given rectangle with the specified color.
void fillRect (int x, int y, int w, int h, Qt::BrushStyle style)
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the brush style specified.
void fillRect (const QRect &r, Qt::BrushStyle style)
Fills the given rectangle with the brush style specified.
void fillRect (const QRectF &r, Qt::BrushStyle style)
Fills the given rectangle with the brush style specified.
const QFont & font () const
Returns the currently set font used for drawing text.
QFontInfo fontInfo () const
Returns the font info for the painter if the painter is active.
QFontMetrics fontMetrics () const
Returns the font metrics for the painter if the painter is active.
bool hasClipping () const
Returns true if clipping has been set; otherwise returns false.
void initFrom (const QWidget *widget)
Initializes the painters pen, background and font to the same as the given widget.
bool isActive () const
Returns true if begin() has been called and end() has not yet been called; otherwise returns false.
Qt::LayoutDirection layoutDirection () const
Returns the layout direction used by the painter when drawing text.
const QMatrix & matrix () const
Use worldTransform() instead.
bool matrixEnabled () const
qreal opacity () const
Returns the opacity of the painter.
QPaintEngine * paintEngine () const
Returns the paint engine that the painter is currently operating on if the painter is active; otherwise 0.
const QPen & pen () const
Returns the painter's current pen.
QPainter ()
Constructs a painter.
QPainter (QPaintDevice *)
Constructs a painter that begins painting the paint device immediately.
RenderHints renderHints () const
Returns a flag that specifies the rendering hints that are set for this painter.
void resetMatrix ()
Resets any transformations that were made using translate(), scale(), shear(), rotate(), setWorldMatrix(), setViewport() and setWindow().
void resetTransform ()
Resets any transformations that were made using translate(), scale(), shear(), rotate(), setWorldTransform(), setViewport() and setWindow().
void restore ()
Restores the current painter state (pops a saved state off the stack).
void rotate (qreal a)
Rotates the coordinate system the given angle clockwise.
void save ()
Saves the current painter state (pushes the state onto a stack).
void scale (qreal sx, qreal sy)
Scales the coordinate system by ({sx}, {sy}).
void setBackground (const QBrush &bg)
Sets the background brush of the painter to the given brush.
void setBackgroundMode (Qt::BGMode mode)
Sets the background mode of the painter to the given mode.
void setBrush (const QBrush &brush)
Sets the painter's brush to the given brush.
void setBrush (Qt::BrushStyle style)
Sets the painter's brush to black color and the specified style.
void setBrushOrigin (int x, int y)
Sets the brush's origin to point (x, y).
void setBrushOrigin (const QPoint &)
Sets the brush's origin to the given position.
void setBrushOrigin (const QPointF &)
Sets the brush origin to position.
void setClipPath (const QPainterPath &path, Qt::ClipOperation op=Qt::ReplaceClip)
Enables clipping, and sets the clip path for the painter to the given path, with the clip operation.
void setClipping (bool enable)
Enables clipping if enable is true, or disables clipping if enable is false.
void setClipRect (const QRectF &, Qt::ClipOperation op=Qt::ReplaceClip)
Enables clipping, and sets the clip region to the given rectangle using the given clip operation.
void setClipRect (const QRect &, Qt::ClipOperation op=Qt::ReplaceClip)
Enables clipping, and sets the clip region to the given rectangle using the given clip operation.
void setClipRect (int x, int y, int w, int h, Qt::ClipOperation op=Qt::ReplaceClip)
Enables clipping, and sets the clip region to the rectangle beginning at (x, y) with the given width and height.
void setClipRegion (const QRegion &, Qt::ClipOperation op=Qt::ReplaceClip)
Sets the clip region to the given region using the specified clip operation.
void setCompositionMode (CompositionMode mode)
Sets the composition mode to the given mode.
void setFont (const QFont &f)
Sets the painter's font to the given font.
void setLayoutDirection (Qt::LayoutDirection direction)
Sets the layout direction used by the painter when drawing text, to the specified direction.
void setMatrix (const QMatrix &matrix, bool combine=false)
Use setWorldTransform() instead.
void setMatrixEnabled (bool enabled)
Use setWorldMatrixEnabled() instead.
void setOpacity (qreal opacity)
Sets the opacity of the painter to opacity.
void setPen (const QColor &color)
Sets the painter's pen to have style Qt::SolidLine, width 0 and the specified color.
void setPen (const QPen &pen)
Sets the painter's pen to be the given pen.
void setPen (Qt::PenStyle style)
Sets the painter's pen to have the given style, width 0 and black color.
void setRenderHint (RenderHint hint, bool on=true)
Sets the given render hint on the painter if on is true; otherwise clears the render hint.
void setRenderHints (RenderHints hints, bool on=true)
Sets the given render hints on the painter if on is true; otherwise clears the render hints.
void setTransform (const QTransform &transform, bool combine=false)
Sets the world transformation matrix.
void setViewport (const QRect &viewport)
Sets the painter's viewport rectangle to the given rectangle, and enables view transformations.
void setViewport (int x, int y, int w, int h)
Sets the painter's viewport rectangle to be the rectangle beginning at (x, y) with the given width and height.
void setViewTransformEnabled (bool enable)
Enables view transformations if enable is true, or disables view transformations if enable is false.
void setWindow (const QRect &window)
Sets the painter's window to the given rectangle, and enables view transformations.
void setWindow (int x, int y, int w, int h)
Sets the painter's window to the rectangle beginning at (x, y) and the given width and height.
void setWorldMatrix (const QMatrix &matrix, bool combine=false)
Sets the transformation matrix to matrix and enables transformations.
void setWorldMatrixEnabled (bool enabled)
Enables transformations if enable is true, or disables transformations if enable is false.
void setWorldTransform (const QTransform &matrix, bool combine=false)
Sets the world transformation matrix.
void shear (qreal sh, qreal sv)
Shears the coordinate system by ({sh}, {sv}).
void strokePath (const QPainterPath &path, const QPen &pen)
Draws the outline (strokes) the path path with the pen specified by pen.
bool testRenderHint (RenderHint hint) const
Returns true if hint is set; otherwise returns false.
const QTransform & transform () const
Returns the world transformation matrix.
void translate (const QPointF &offset)
Translates the coordinate system by the given offset; i.e.
void translate (const QPoint &offset)
Translates the coordinate system by the given offset.
void translate (qreal dx, qreal dy)
Translates the coordinate system by the vector (dx, dy).
QRect viewport () const
Returns the viewport rectangle.
bool viewTransformEnabled () const
Returns true if view transformation is enabled; otherwise returns false.
QRect window () const
Returns the window rectangle.
const QMatrix & worldMatrix () const
Returns the world transformation matrix.
bool worldMatrixEnabled () const
Returns true if world transformation is enabled; otherwise returns false.
const QTransform & worldTransform () const
Returns the world transformation matrix.
~QPainter ()
Destroys the painter.
Static Public Functions
static QPaintDevice * redirected (const QPaintDevice *device, QPoint *offset=0)
Using QWidget::render() obsoletes the use of this function.
static void restoreRedirected (const QPaintDevice *device)
Using QWidget::render() obsoletes the use of this function.
static void setRedirected (const QPaintDevice *device, QPaintDevice *replacement, const QPoint &offset=QPoint())
Please use QWidget::render() instead.
Properties
QScopedPointer< QPainterPrivate > d_ptr
Friends
class Q3Painter
class QAlphaPaintEngine
class QFontEngine
class QFontEngineBox
class QFontEngineFT
class QFontEngineMac
class QFontEngineWin
class QFontEngineXLFD
class QOpenGLPaintEngine
class QPaintEngine
class QPaintEngineExPrivate
class QPreviewPaintEngine
class QRasterPaintEngine
class QVGPaintEngine
class QWin32PaintEngine
class QWin32PaintEnginePrivate
class QWSManager
class QX11PaintEngine
class QX11PaintEnginePrivate
Detailed Description
The QPainter class performs low-level painting on widgets and other paint devices.
Note
This class or function is reentrant.
QPainter provides highly optimized functions to do most of the drawing GUI programs require. It can draw everything from simple lines to complex shapes like pies and chords. It can also draw aligned text and pixmaps. Normally, it draws in a "natural" coordinate system, but it can also do view and world transformation. QPainter can operate on any object that inherits the QPaintDevice class.
The common use of QPainter is inside a widget's paint event: Construct and customize (e.g. set the pen or the brush) the painter. Then draw. Remember to destroy the QPainter object after drawing. For example:
void SimpleExampleWidget::paintEvent(QPaintEvent *)
{
    QPainter painter(this);
    painter.setPen(Qt::blue);
    painter.setFont(QFont("Arial", 30));
    painter.drawText(rect(), Qt::AlignCenter, "Qt");
}
The core functionality of QPainter is drawing, but the class also provide several functions that allows you to customize QPainter's settings and its rendering quality, and others that enable clipping. In addition you can control how different shapes are merged together by specifying the painter's composition mode.
The isActive() function indicates whether the painter is active. A painter is activated by the begin() function and the constructor that takes a QPaintDevice argument. The end() function, and the destructor, deactivates it.
Together with the QPaintDevice and QPaintEngine classes, QPainter form the basis for Qt's paint system. QPainter is the class used to perform drawing operations. QPaintDevice represents a device that can be painted on using a QPainter. QPaintEngine provides the interface that the painter uses to draw onto different types of devices. If the painter is active, device() returns the paint device on which the painter paints, and paintEngine() returns the paint engine that the painter is currently operating on. For more information, see the Paint System.
Sometimes it is desirable to make someone else paint on an unusual QPaintDevice. QPainter supports a static function to do this, setRedirected().
Warning
When the paintdevice is a widget, QPainter can only be used inside a paintEvent() function or in a function called by paintEvent(); that is unless the Qt::WA_PaintOutsidePaintEvent widget attribute is set. On Mac OS X and Windows, you can only paint in a paintEvent() function regardless of this attribute's setting.
Settings
There are several settings that you can customize to make QPainter draw according to your preferences:
font() is the font used for drawing text. If the painter isActive(), you can retrieve information about the currently set font, and its metrics, using the fontInfo() and fontMetrics() functions respectively.
brush() defines the color or pattern that is used for filling shapes.
pen() defines the color or stipple that is used for drawing lines or boundaries.
backgroundMode() defines whether there is a background() or not, i.e it is either Qt::OpaqueMode or Qt::TransparentMode.
background() only applies when backgroundMode() is Qt::OpaqueMode and pen() is a stipple. In that case, it describes the color of the background pixels in the stipple.
brushOrigin() defines the origin of the tiled brushes, normally the origin of widget's background.
viewport(), window(), worldTransform() make up the painter's coordinate transformation system. For more information, see the Coordinate Transformations section and the Coordinate System documentation.
hasClipping() tells whether the painter clips at all. (The paint device clips, too.) If the painter clips, it clips to clipRegion().
layoutDirection() defines the layout direction used by the painter when drawing text.
worldMatrixEnabled() tells whether world transformation is enabled.
viewTransformEnabled() tells whether view transformation is enabled.
Note that some of these settings mirror settings in some paint devices, e.g. QWidget::font(). The QPainter::begin() function (or equivalently the QPainter constructor) copies these attributes from the paint device.
You can at any time save the QPainter's state by calling the save() function which saves all the available settings on an internal stack. The restore() function pops them back.
Drawing
QPainter provides functions to draw most primitives: drawPoint(), drawPoints(), drawLine(), drawRect(), drawRoundedRect(), drawEllipse(), drawArc(), drawPie(), drawChord(), drawPolyline(), drawPolygon(), drawConvexPolygon() and drawCubicBezier(). The two convenience functions, drawRects() and drawLines(), draw the given number of rectangles or lines in the given array of QRects or QLine using the current pen and brush.
The QPainter class also provides the fillRect() function which fills the given QRect, with the given QBrush, and the eraseRect() function that erases the area inside the given rectangle.
All of these functions have both integer and floating point versions.
Basic Drawing Example
The painting/basicdrawing{Basic Drawing} example shows how to display basic graphics primitives in a variety of styles using the QPainter class.
If you need to draw a complex shape, especially if you need to do so repeatedly, consider creating a QPainterPath and drawing it using drawPath().
Painter Paths example
The QPainterPath class provides a container for painting operations, enabling graphical shapes to be constructed and reused.
The painting/painterpaths{Painter Paths} example shows how painter paths can be used to build complex shapes for rendering.
QPainter also provides the fillPath() function which fills the given QPainterPath with the given QBrush, and the strokePath() function that draws the outline of the given path (i.e. strokes the path).
See also the demos/deform{Vector Deformation} demo which shows how to use advanced vector techniques to draw text using a QPainterPath, the demos/gradients{Gradients} demo which shows the different types of gradients that are available in Qt, and the Path Stroking demo which shows Qt's built-in dash patterns and shows how custom patterns can be used to extend the range of available patterns.
demos/deform{Vector Deformation} demos/gradients{Gradients} demos/pathstroke{Path Stroking}
There are functions to draw pixmaps/images, namely drawPixmap(), drawImage() and drawTiledPixmap(). Both drawPixmap() and drawImage() produce the same result, except that drawPixmap() is faster on-screen while drawImage() may be faster on a QPrinter or other devices.
Text drawing is done using drawText(). When you need fine-grained positioning, boundingRect() tells you where a given drawText() command will draw.
There is a drawPicture() function that draws the contents of an entire QPicture. The drawPicture() function is the only function that disregards all the painter's settings as QPicture has its own settings.
Rendering Quality
To get the optimal rendering result using QPainter, you should use the platform independent QImage as paint device; i.e. using QImage will ensure that the result has an identical pixel representation on any platform.
The QPainter class also provides a means of controlling the rendering quality through its RenderHint enum and the support for floating point precision: All the functions for drawing primitives has a floating point version. These are often used in combination with the RenderHint{QPainter::Antialiasing} render hint.
Concentric Circles Example
The painting/concentriccircles{Concentric Circles} example shows the improved rendering quality that can be obtained using floating point precision and anti-aliasing when drawing custom widgets.
The application's main window displays several widgets which are drawn using the various combinations of precision and anti-aliasing.
The RenderHint enum specifies flags to QPainter that may or may not be respected by any given engine. QPainter::Antialiasing indicates that the engine should antialias edges of primitives if possible, QPainter::TextAntialiasing indicates that the engine should antialias text if possible, and the QPainter::SmoothPixmapTransform indicates that the engine should use a smooth pixmap transformation algorithm. RenderHint {HighQualityAntialiasing} is an OpenGL-specific rendering hint indicating that the engine should use fragment programs and offscreen rendering for antialiasing.
The renderHints() function returns a flag that specifies the rendering hints that are set for this painter. Use the setRenderHint() function to set or clear the currently set RenderHints.
Coordinate Transformations
Normally, the QPainter operates on the device's own coordinate system (usually pixels), but QPainter has good support for coordinate transformations.
nop rotate() scale() translate()
The most commonly used transformations are scaling, rotation, translation and shearing. Use the scale() function to scale the coordinate system by a given offset, the rotate() function to rotate it clockwise and translate() to translate it (i.e. adding a given offset to the points). You can also twist the coordinate system around the origin using the shear() function. See the Affine Transformations demo for a visualization of a sheared coordinate system.
See also the painting/transformations{Transformations} example which shows how transformations influence the way that QPainter renders graphics primitives. In particular it shows how the order of transformations affects the result.
Affine Transformations Demo
The demos/affine{Affine Transformations} demo show Qt's ability to perform affine transformations on painting operations. The demo also allows the user to experiment with the transformation operations and see the results immediately.
All the tranformation operations operate on the transformation worldTransform(). A matrix transforms a point in the plane to another point. For more information about the transformation matrix, see the Coordinate System and QTransform documentation.
The setWorldTransform() function can replace or add to the currently set worldTransform(). The resetTransform() function resets any transformations that were made using translate(), scale(), shear(), rotate(), setWorldTransform(), setViewport() and setWindow() functions. The deviceTransform() returns the matrix that transforms from logical coordinates to device coordinates of the platform dependent paint device. The latter function is only needed when using platform painting commands on the platform dependent handle, and the platform does not do transformations nativly.
When drawing with QPainter, we specify points using logical coordinates which then are converted into the physical coordinates of the paint device. The mapping of the logical coordinates to the physical coordinates are handled by QPainter's combinedTransform(), a combination of viewport() and window() and worldTransform(). The viewport() represents the physical coordinates specifying an arbitrary rectangle, the window() describes the same rectangle in logical coordinates, and the worldTransform() is identical with the transformation matrix.
See also Coordinate System
Clipping
QPainter can clip any drawing operation to a rectangle, a region, or a vector path. The current clip is available using the functions clipRegion() and clipPath(). Whether paths or regions are preferred (faster) depends on the underlying paintEngine(). For example, the QImage paint engine prefers paths while the X11 paint engine prefers regions. Setting a clip is done in the painters logical coordinates.
After QPainter's clipping, the paint device may also clip. For example, most widgets clip away the pixels used by child widgets, and most printers clip away an area near the edges of the paper. This additional clipping is not reflected by the return value of clipRegion() or hasClipping().
Composition Modes
QPainter provides the CompositionMode enum which defines the Porter-Duff rules for digital image compositing; it describes a model for combining the pixels in one image, the source, with the pixels in another image, the destination.
The two most common forms of composition are QPainter::CompositionMode and QPainter::CompositionMode . QPainter::CompositionMode is used to draw opaque objects onto a paint device. In this mode, each pixel in the source replaces the corresponding pixel in the destination. In QPainter::CompositionMode composition mode, the source object is transparent and is drawn on top of the destination.
Note that composition transformation operates pixelwise. For that reason, there is a difference between using the graphic primitive itself and its bounding rectangle: The bounding rect contains pixels with alpha == 0 (i.e the pixels surrounding the primitive). These pixels will overwrite the other image's pixels, affectively clearing those, while the primitive only overwrites its own area.
Composition Modes Demo
The demos/composition{Composition Modes} demo, available in Qt's demo directory, allows you to experiment with the various composition modes and see the results immediately.
Limitations
If you are using coordinates with Qt's raster-based paint engine, it is important to note that, while coordinates greater than +/- 2 15 can be used, any painting performed with coordinates outside this range is not guaranteed to be shown; the drawing may be clipped. This is due to the use of short int in the implementation.
The outlines generated by Qt's stroker are only an approximation when dealing with curved shapes. It is in most cases impossible to represent the outline of a bezier curve segment using another bezier curve segment, and so Qt approximates the curve outlines by using several smaller curves. For performance reasons there is a limit to how many curves Qt uses for these outlines, and thus when using large pen widths or scales the outline error increases. To generate outlines with smaller errors it is possible to use the QPainterPathStroker class, which has the setCurveThreshold member function which let's the user specify the error tolerance. Another workaround is to convert the paths to polygons first and then draw the polygons instead.
Performance
QPainter is a rich framework that allows developers to do a great variety of graphical operations, such as gradients, composition modes and vector graphics. And QPainter can do this across a variety of different hardware and software stacks. Naturally the underlying combination of hardware and software has some implications for performance, and ensuring that every single operation is fast in combination with all the various combinations of composition modes, brushes, clipping, transformation, etc, is close to an impossible task because of the number of permutations. As a compromise we have selected a subset of the QPainter API and backends, where performance is guaranteed to be as good as we can sensibly get it for the given combination of hardware and software.
The backends we focus on as high-performance engines are:
Raster - This backend implements all rendering in pure software and is always used to render into QImages. For optimal performance only use the format types QImage::Format_ARGB32_Premultiplied, QImage::Format_RGB32 or QImage::Format_RGB16. Any other format, including QImage::Format_ARGB32, has significantly worse performance. This engine is also used by default on Windows and on QWS. It can be used as default graphics system on any OS/hardware/software combination by passing {-graphicssystem raster} on the command line
OpenGL 2.0 (ES) - This backend is the primary backend for hardware accelerated graphics. It can be run on desktop machines and embedded devices supporting the OpenGL 2.0 or OpenGL/ES 2.0 specification. This includes most graphics chips produced in the last couple of years. The engine can be enabled by using QPainter onto a QGLWidget or by passing {-graphicssystem opengl} on the command line when the underlying system supports it.
OpenVG - This backend implements the Khronos standard for 2D and Vector Graphics. It is primarily for embedded devices with hardware support for OpenVG. The engine can be enabled by passing {-graphicssystem openvg} on the command line when the underlying system supports it.
These operations are:
Simple transformations, meaning translation and scaling, pluss 0, 90, 180, 270 degree rotations.
drawPixmap() in combination with simple transformations and opacity with non-smooth transformation mode (QPainter::SmoothPixmapTransform not enabled as a render hint).
Rectangle fills with solid color, two-color linear gradients and simple transforms.
Rectangular clipping with simple transformations and intersect clip.
Composition Modes QPainter::CompositionMode_Source and QPainter::CompositionMode_SourceOver
Rounded rectangle filling using solid color and two-color linear gradients fills.
3x3 patched pixmaps, via qDrawBorderPixmap.
This list gives an indication of which features to safely use in an application where performance is critical. For certain setups, other operations may be fast too, but before making extensive use of them, it is recommended to benchmark and verify them on the system where the software will run in the end. There are also cases where expensive operations are ok to use, for instance when the result is cached in a QPixmap.
See also
QPaintDevice, QPaintEngine, {QtSvg Module}, {Basic Drawing Example}, {Drawing Utility Functions}
Definition at line 86 of file qpainter.h.
Enumerations
CompositionMode
enum QPainter::CompositionMode
Defines the modes supported for digital image compositing.
Composition modes are used to specify how the pixels in one image, the source, are merged with the pixel in another image, the destination.
Please note that the bitwise raster operation modes, denoted with a RasterOp prefix, are only natively supported in the X11 and raster paint engines. This means that the only way to utilize these modes on the Mac is via a QImage. The RasterOp denoted blend modes are not supported for pens and brushes with alpha components. Also, turning on the QPainter::Antialiasing render hint will effectively disable the RasterOp modes.
The most common type is SourceOver (often referred to as just alpha blending) where the source pixel is blended on top of the destination pixel in such a way that the alpha component of the source defines the translucency of the pixel.
When the paint device is a QImage, the image format must be set to QImage::Format{Format_ARGB32Premultiplied} or QImage::Format{Format_ARGB32} for the composition modes to have any effect. For performance the premultiplied version is the preferred format.
When a composition mode is set it applies to all painting operator, pens, brushes, gradients and pixmap/image drawing.
CompositionMode_SourceOver This is the default mode. The alpha of the source is used to blend the pixel on top of the destination.
CompositionMode_DestinationOver The alpha of the destination is used to blend it on top of the source pixels. This mode is the inverse of CompositionMode_SourceOver.
CompositionMode_Clear The pixels in the destination are cleared (set to fully transparent) independent of the source.
CompositionMode_Source The output is the source pixel. (This means a basic copy operation and is identical to SourceOver when the source pixel is opaque).
CompositionMode_Destination The output is the destination pixel. This means that the blending has no effect. This mode is the inverse of CompositionMode_Source.
CompositionMode_SourceIn The output is the source, where the alpha is reduced by that of the destination.
CompositionMode_DestinationIn The output is the destination, where the alpha is reduced by that of the source. This mode is the inverse of CompositionMode_SourceIn.
CompositionMode_SourceOut The output is the source, where the alpha is reduced by the inverse of destination.
CompositionMode_DestinationOut The output is the destination, where the alpha is reduced by the inverse of the source. This mode is the inverse of CompositionMode_SourceOut.
CompositionMode_SourceAtop The source pixel is blended on top of the destination, with the alpha of the source pixel reduced by the alpha of the destination pixel.
CompositionMode_DestinationAtop The destination pixel is blended on top of the source, with the alpha of the destination pixel is reduced by the alpha of the destination pixel. This mode is the inverse of CompositionMode_SourceAtop.
CompositionMode_Xor The source, whose alpha is reduced with the inverse of the destination alpha, is merged with the destination, whose alpha is reduced by the inverse of the source alpha. CompositionMode_Xor is not the same as the bitwise Xor.
CompositionMode_Plus Both the alpha and color of the source and destination pixels are added together.
CompositionMode_Multiply The output is the source color multiplied by the destination. Multiplying a color with white leaves the color unchanged, while multiplying a color with black produces black.
CompositionMode_Screen The source and destination colors are inverted and then multiplied. Screening a color with white produces white, whereas screening a color with black leaves the color unchanged.
CompositionMode_Overlay Multiplies or screens the colors depending on the destination color. The destination color is mixed with the source color to reflect the lightness or darkness of the destination.
CompositionMode_Darken The darker of the source and destination colors is selected.
CompositionMode_Lighten The lighter of the source and destination colors is selected.
CompositionMode_ColorDodge The destination color is brightened to reflect the source color. A black source color leaves the destination color unchanged.
CompositionMode_ColorBurn The destination color is darkened to reflect the source color. A white source color leaves the destination color unchanged.
CompositionMode_HardLight Multiplies or screens the colors depending on the source color. A light source color will lighten the destination color, whereas a dark source color will darken the destination color.
CompositionMode_SoftLight Darkens or lightens the colors depending on the source color. Similar to CompositionMode_HardLight.
CompositionMode_Difference Subtracts the darker of the colors from the lighter. Painting with white inverts the destination color, whereas painting with black leaves the destination color unchanged.
CompositionMode_Exclusion Similar to CompositionMode_Difference, but with a lower contrast. Painting with white inverts the destination color, whereas painting with black leaves the destination color unchanged.
RasterOp_SourceOrDestination Does a bitwise OR operation on the source and destination pixels (src OR dst).
RasterOp_SourceAndDestination Does a bitwise AND operation on the source and destination pixels (src AND dst).
RasterOp_SourceXorDestination Does a bitwise XOR operation on the source and destination pixels (src XOR dst).
RasterOp_NotSourceAndNotDestination Does a bitwise NOR operation on the source and destination pixels ((NOT src) AND (NOT dst)).
RasterOp_NotSourceOrNotDestination Does a bitwise NAND operation on the source and destination pixels ((NOT src) OR (NOT dst)).
RasterOp_NotSourceXorDestination Does a bitwise operation where the source pixels are inverted and then XOR'ed with the destination ((NOT src) XOR dst).
RasterOp_NotSource Does a bitwise operation where the source pixels are inverted (NOT src).
RasterOp_NotSourceAndDestination Does a bitwise operation where the source is inverted and then AND'ed with the destination ((NOT src) AND dst).
RasterOp_SourceAndNotDestination Does a bitwise operation where the source is AND'ed with the inverted destination pixels (src AND (NOT dst)).
See also
compositionMode(), setCompositionMode(), {QPainter::Composition Modes}{Composition Modes}, {Image Composition Example}
Enumerator
CompositionMode_SourceOver
CompositionMode_DestinationOver
CompositionMode_Clear
CompositionMode_Source
CompositionMode_Destination
CompositionMode_SourceIn
CompositionMode_DestinationIn
CompositionMode_SourceOut
CompositionMode_DestinationOut
CompositionMode_SourceAtop
CompositionMode_DestinationAtop
CompositionMode_Xor
CompositionMode_Plus
CompositionMode_Multiply
CompositionMode_Screen
CompositionMode_Overlay
CompositionMode_Darken
CompositionMode_Lighten
CompositionMode_ColorDodge
CompositionMode_ColorBurn
CompositionMode_HardLight
CompositionMode_SoftLight
CompositionMode_Difference
CompositionMode_Exclusion
RasterOp_SourceOrDestination
RasterOp_SourceAndDestination
RasterOp_SourceXorDestination
RasterOp_NotSourceAndNotDestination
RasterOp_NotSourceOrNotDestination
RasterOp_NotSourceXorDestination
RasterOp_NotSource
RasterOp_NotSourceAndDestination
RasterOp_SourceAndNotDestination
Definition at line 138 of file qpainter.h.
{
         CompositionMode_SourceOver,
         CompositionMode_DestinationOver,
         CompositionMode_Clear,
         CompositionMode_Source,
         CompositionMode_Destination,
         CompositionMode_SourceIn,
         CompositionMode_DestinationIn,
         CompositionMode_SourceOut,
         CompositionMode_DestinationOut,
         CompositionMode_SourceAtop,
         CompositionMode_DestinationAtop,
         CompositionMode_Xor,
         //svg 1.2 blend modes
         CompositionMode_Plus,
         CompositionMode_Multiply,
         CompositionMode_Screen,
         CompositionMode_Overlay,
         CompositionMode_Darken,
         CompositionMode_Lighten,
         CompositionMode_ColorDodge,
         CompositionMode_ColorBurn,
         CompositionMode_HardLight,
         CompositionMode_SoftLight,
         CompositionMode_Difference,
         CompositionMode_Exclusion,
         // ROPs
         RasterOp_SourceOrDestination,
         RasterOp_SourceAndDestination,
         RasterOp_SourceXorDestination,
         RasterOp_NotSourceAndNotDestination,
         RasterOp_NotSourceOrNotDestination,
         RasterOp_NotSourceXorDestination,
         RasterOp_NotSource,
         RasterOp_NotSourceAndDestination,
         RasterOp_SourceAndNotDestination
     };
PixmapFragmentHint
enum QPainter::PixmapFragmentHint
Since
4.7
OpaqueHint Indicates that the pixmap fragments to be drawn are opaque. Opaque fragments are potentially faster to draw.
See also
QPainter::drawPixmapFragments(), QPainter::PixmapFragment
Enumerator
OpaqueHint
Definition at line 120 of file qpainter.h.
{
         OpaqueHint = 0x01
     };
RenderHint
enum QPainter::RenderHint
Renderhints are used to specify flags to QPainter that may or may not be respected by any given engine.
Antialiasing Indicates that the engine should antialias edges of primitives if possible.
TextAntialiasing Indicates that the engine should antialias text if possible. To forcibly disable antialiasing for text, do not use this hint. Instead, set QFont::NoAntialias on your font's style strategy.
SmoothPixmapTransform Indicates that the engine should use a smooth pixmap transformation algorithm (such as bilinear) rather than nearest neighbor.
HighQualityAntialiasing An OpenGL-specific rendering hint indicating that the engine should use fragment programs and offscreen rendering for antialiasing.
NonCosmeticDefaultPen The engine should interpret pens with a width of 0 (which otherwise enables QPen::isCosmetic()) as being a non-cosmetic pen with a width of 1.
See also
renderHints(), setRenderHint(), {QPainter::Rendering Quality}{Rendering Quality}, {Concentric Circles Example}
Enumerator
Antialiasing
TextAntialiasing
SmoothPixmapTransform
HighQualityAntialiasing
NonCosmeticDefaultPen
Definition at line 93 of file qpainter.h.
                     {
         Antialiasing = 0x01,
         TextAntialiasing = 0x02,
         SmoothPixmapTransform = 0x04,
         HighQualityAntialiasing = 0x08,
         NonCosmeticDefaultPen = 0x10
     };
Constructors and Destructors
QPainter() [1/2]
QPainter::QPainter ()
Constructs a painter.
See also
begin(), end()
Definition at line 1459 of file qpainter.cpp.
     : d_ptr(new QPainterPrivate(this))
 {
 }
QPainter() [2/2]
QPainter::QPainter (QPaintDevice * device) explicit
Constructs a painter that begins painting the paint device immediately.
This constructor is convenient for short-lived painters, e.g. in a QWidget::paintEvent() and should be used only once. The constructor calls begin() for you and the QPainter destructor automatically calls end().
Here's an example using begin() and end():
void MyWidget::paintEvent(QPaintEvent *)
{
    QPainter p;
    p.begin(this);
    p.drawLine(...);        // drawing code
    p.end();
}
The same example using this constructor:
void MyWidget::paintEvent(QPaintEvent *)
{
    QPainter p(this);
    p.drawLine(...);        // drawing code
}
Since the constructor cannot provide feedback when the initialization of the painter failed you should rather use begin() and end() to paint on external devices, e.g. printers.
See also
begin(), end()
Definition at line 1488 of file qpainter.cpp.
     : d_ptr(0)
 {
     Q_ASSERT(pd != 0);
     if (!QPainterPrivate::attachPainterPrivate(this, pd)) {
         d_ptr.reset(new QPainterPrivate(this));
         begin(pd);
     }
     Q_ASSERT(d_ptr);
 }
~QPainter()
QPainter::~QPainter ()
Destroys the painter.
Definition at line 1502 of file qpainter.cpp.
 {
     d_ptr->inDestructor = true;
     QT_TRY {
         if (isActive())
             end();
         else if (d_ptr->refcount > 1)
             d_ptr->detachPainterPrivate(this);
     } QT_CATCH(...) {
         // don't throw anything in the destructor.
     }
     if (d_ptr) {
         // Make sure we haven't messed things up.
         Q_ASSERT(d_ptr->inDestructor);
         d_ptr->inDestructor = false;
         Q_ASSERT(d_ptr->refcount == 1);
         if (d_ptr->d_ptrs)
             free(d_ptr->d_ptrs);
     }
 }
Functions
background()
const QBrush & QPainter::background () const
Returns the current background brush.
See also
setBackground(), {QPainter::Settings}{Settings}
Definition at line 2482 of file qpainter.cpp.
Referenced by QMotifStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QStyle::drawItemText(), QWindowsMobileStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), and QMotifStyle::drawPrimitive().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::background: Painter not active");
         return d->fakeState()->brush;
     }
     return d->state->bgBrush;
 }
backgroundMode()
Qt::BGMode QPainter::backgroundMode () const
Returns the current background mode.
See also
setBackgroundMode(), {QPainter::Settings}{Settings}
Definition at line 4026 of file qpainter.cpp.
Referenced by QWindowsCEStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), and QWindowsStyle::drawControl().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::backgroundMode: Painter not active");
         return Qt::TransparentMode;
     }
     return d->state->bgMode;
 }
begin()
bool QPainter::begin (QPaintDevice * device)
Begins painting the paint device and returns true if successful; otherwise returns false.
Use begin() instead.
Notice that all painter settings (setPen(), setBrush() etc.) are reset to default values when begin() is called.
The errors that can occur are serious problems, such as these:
painter->begin(0); // impossible - paint device cannot be 0
QPixmap image(0, 0);
painter->begin(&image); // impossible - image.isNull() == true;
painter->begin(myWidget);
painter2->begin(myWidget); // impossible - only one painter at a time
Note that most of the time, you can use one of the constructors instead of begin(), and that end() is automatically done at destruction.
Warning
A paint device can only be painted by one painter at a time.
Painting on a QImage with the format QImage::Format_Indexed8 is not supported.
See also
end(), QPainter()
If the paint device is a QWidget, QPainter is initialized after the widget's settings automatically. Otherwise, you must call the initFrom() function to initialize the painters pen, background and font to the same as any given widget.
QPainter painter(this); painter.begin(device, init); QPainter painter(this); painter.begin(device); painter.initFrom(init);
Definition at line 1723 of file qpainter.cpp.
Referenced by _q_paintIntoCache(), QStylePainter::begin(), QWindowsStyle::drawComplexControl(), QPainter(), toVGImageWithOpacity(), and toVGImageWithOpacitySubRect().
 {
     Q_ASSERT(pd);
     if (pd->painters > 0) {
         qWarning("QPainter::begin: A paint device can only be painted by one painter at a time.");
         return false;
     }
     if (d_ptr->engine) {
         qWarning("QPainter::begin: Painter already active");
         return false;
     }
     if (QPainterPrivate::attachPainterPrivate(this, pd))
         return true;
     Q_D(QPainter);
     d->helper_device = pd;
     d->original_device = pd;
     QPaintDevice *rpd = 0;
     QPoint redirectionOffset;
     // We know for sure that redirection is broken when the widget is inside
     // its paint event, so it's safe to use our hard-coded redirection. However,
     // there IS one particular case we still need to support, and that's
     // when people call QPainter::setRedirected in the widget's paint event right
     // before any painter is created (or QPainter::begin is called). In that
     // particular case our hard-coded redirection is restored and the redirection
     // is retrieved from QPainter::redirected (as before).
     if (pd->devType() == QInternal::Widget)
         rpd = static_cast<QWidget *>(pd)->d_func()->redirected(&redirectionOffset);
     if (!rpd)
         rpd = redirected(pd, &redirectionOffset);
     if (rpd)
         pd = rpd;
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::begin(), device=%p, type=%d\n", pd, pd->devType());
 #endif
     if (pd->devType() == QInternal::Pixmap)
         static_cast<QPixmap *>(pd)->detach();
     else if (pd->devType() == QInternal::Image)
         static_cast<QImage *>(pd)->detach();
     d->engine = pd->paintEngine();
     if (!d->engine) {
         qWarning("QPainter::begin: Paint device returned engine == 0, type: %d", pd->devType());
         return false;
     }
     d->device = pd;
     d->extended = d->engine->isExtended() ? static_cast<QPaintEngineEx *>(d->engine) : 0;
     if (d->emulationEngine)
         d->emulationEngine->real_engine = d->extended;
     // Setup new state...
     Q_ASSERT(!d->state);
     d->state = d->extended ? d->extended->createState(0) : new QPainterState;
     d->state->painter = this;
     d->states.push_back(d->state);
     d->state->redirectionMatrix.translate(-redirectionOffset.x(), -redirectionOffset.y());
     d->state->brushOrigin = QPointF();
     // Slip a painter state into the engine before we do any other operations
     if (d->extended)
         d->extended->setState(d->state);
     else
         d->engine->state = d->state;
     switch (pd->devType()) {
         case QInternal::Widget:
         {
             const QWidget *widget = static_cast<const QWidget *>(pd);
             Q_ASSERT(widget);
             const bool paintOutsidePaintEvent = widget->testAttribute(Qt::WA_PaintOutsidePaintEvent);
             const bool inPaintEvent = widget->testAttribute(Qt::WA_WState_InPaintEvent);
             if(!d->engine->hasFeature(QPaintEngine::PaintOutsidePaintEvent)
                 && !paintOutsidePaintEvent && !inPaintEvent) {
                 qWarning("QPainter::begin: Widget painting can only begin as a "
                          "result of a paintEvent");
                 qt_cleanup_painter_state(d);
                 return false;
             }
             // Adjust offset for alien widgets painting outside the paint event.
             if (!inPaintEvent && paintOutsidePaintEvent && !widget->internalWinId()
                 && widget->testAttribute(Qt::WA_WState_Created)) {
                 const QPoint offset = widget->mapTo(widget->nativeParentWidget(), QPoint());
                 d->state->redirectionMatrix.translate(offset.x(), offset.y());
             }
             break;
         }
         case QInternal::Pixmap:
         {
             QPixmap *pm = static_cast<QPixmap *>(pd);
             Q_ASSERT(pm);
             if (pm->isNull()) {
                 qWarning("QPainter::begin: Cannot paint on a null pixmap");
                 qt_cleanup_painter_state(d);
                 return false;
             }
             if (pm->depth() == 1) {
                 d->state->pen = QPen(Qt::color1);
                 d->state->brush = QBrush(Qt::color0);
             }
             break;
         }
         case QInternal::Image:
         {
             QImage *img = static_cast<QImage *>(pd);
             Q_ASSERT(img);
             if (img->isNull()) {
                 qWarning("QPainter::begin: Cannot paint on a null image");
                 qt_cleanup_painter_state(d);
                 return false;
             } else if (img->format() == QImage::Format_Indexed8) {
                 // Painting on indexed8 images is not supported.
                 qWarning("QPainter::begin: Cannot paint on an image with the QImage::Format_Indexed8 format");
                 qt_cleanup_painter_state(d);
                 return false;
             }
             if (img->depth() == 1) {
                 d->state->pen = QPen(Qt::color1);
                 d->state->brush = QBrush(Qt::color0);
             }
             break;
         }
         default:
             break;
     }
     if (d->state->ww == 0) // For compat with 3.x painter defaults
         d->state->ww = d->state->wh = d->state->vw = d->state->vh = 1024;
     d->engine->setPaintDevice(pd);
     bool begun = d->engine->begin(pd);
     if (!begun) {
         qWarning("QPainter::begin(): Returned false");
         if (d->engine->isActive()) {
             end();
         } else {
             qt_cleanup_painter_state(d);
         }
         return false;
     } else {
         d->engine->setActive(begun);
     }
     // Copy painter properties from original paint device,
     // required for QPixmap::grabWidget()
     if (d->original_device->devType() == QInternal::Widget) {
         QWidget *widget = static_cast<QWidget *>(d->original_device);
         initFrom(widget);
     } else {
         d->state->layoutDirection = Qt::LayoutDirectionAuto;
         // make sure we have a font compatible with the paintdevice
         d->state->deviceFont = d->state->font = QFont(d->state->deviceFont, device());
     }
     QRect systemRect = d->engine->systemRect();
     if (!systemRect.isEmpty()) {
         d->state->ww = d->state->vw = systemRect.width();
         d->state->wh = d->state->vh = systemRect.height();
     } else {
         d->state->ww = d->state->vw = pd->metric(QPaintDevice::PdmWidth);
         d->state->wh = d->state->vh = pd->metric(QPaintDevice::PdmHeight);
     }
     const QPoint coordinateOffset = d->engine->coordinateOffset();
     d->state->redirectionMatrix.translate(-coordinateOffset.x(), -coordinateOffset.y());
     Q_ASSERT(d->engine->isActive());
     if (!d->state->redirectionMatrix.isIdentity())
         d->updateMatrix();
     Q_ASSERT(d->engine->isActive());
     d->state->renderHints = QPainter::TextAntialiasing;
     ++d->device->painters;
     d->state->emulationSpecifier = 0;
     return true;
 }
beginNativePainting()
void QPainter::beginNativePainting ()
Flushes the painting pipeline and prepares for the user issuing commands directly to the underlying graphics context.
Since
4.6
Must be followed by a call to endNativePainting().
Note that only the states the underlying paint engine changes will be reset to their respective default states. The states we reset may change from release to release. The following states are currently reset in the OpenGL 2 engine:
blending is disabled
the depth, stencil and scissor tests are disabled
the active texture unit is reset to 0
the depth mask, depth function and the clear depth are reset to their default values
the stencil mask, stencil operation and stencil function are reset to their default values
the current color is reset to solid white
If, for example, the OpenGL polygon mode is changed by the user inside a beginNativePaint()/endNativePainting() block, it will not be reset to the default state by endNativePainting(). Here is an example that shows intermixing of painter commands and raw OpenGL commands:
QPainter painter(this);
painter.fillRect(0, 0, 128, 128, Qt::green);
painter.beginNativePainting();
glEnable(GL_SCISSOR_TEST);
glScissor(0, 0, 64, 64);
glClearColor(1, 0, 0, 1);
glClear(GL_COLOR_BUFFER_BIT);
glDisable(GL_SCISSOR_TEST);
painter.endNativePainting();
See also
endNativePainting()
Definition at line 2032 of file qpainter.cpp.
Referenced by ShaderEffectItem::paint().
 {
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::beginNativePainting: Painter not active");
         return;
     }
     if (d->extended)
         d->extended->beginNativePainting();
 }
boundingRect() [1/4]
QRectF QPainter::boundingRect (const QRectF & rectangle, int flags, const QString & text)
Returns the bounding rectangle of the text as it will appear when drawn inside the given rectangle with the specified flags using the currently set font(); i.
e the function tells you where the drawText() function will draw when given the same arguments.
If the text does not fit within the given rectangle using the specified flags, the function returns the required rectangle.
The flags argument is a bitwise OR of the following flags:
Qt::AlignLeft
Qt::AlignRight
Qt::AlignHCenter
Qt::AlignTop
Qt::AlignBottom
Qt::AlignVCenter
Qt::AlignCenter
Qt::TextSingleLine
Qt::TextExpandTabs
Qt::TextShowMnemonic
Qt::TextWordWrap
Qt::TextIncludeTrailingSpaces
If several of the horizontal or several of the vertical alignment flags are set, the resulting alignment is undefined.
See also
drawText(), Qt::Alignment, Qt::TextFlag
Definition at line 7093 of file qpainter.cpp.
Referenced by qDrawPlainRect().
 {
     if (str.isEmpty())
         return QRectF(rect.x(),rect.y(), 0,0);
     QRectF brect;
     drawText(rect, flags | Qt::TextDontPrint, str, &brect);
     return brect;
 }
boundingRect() [2/4]
QRect QPainter::boundingRect (const QRect & rectangle, int flags, const QString & text)
Returns the bounding rectangle of the text as it will appear when drawn inside the given rectangle with the specified flags using the currently set font().
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 7082 of file qpainter.cpp.
 {
     if (str.isEmpty())
         return QRect(rect.x(),rect.y(), 0,0);
     QRect brect;
     drawText(rect, flags | Qt::TextDontPrint, str, &brect);
     return brect;
 }
boundingRect() [3/4]
QRect QPainter::boundingRect (int x, int y, int w, int h, int flags, const QString & text) inline
Returns the bounding rectangle of the given text as it will appear when drawn inside the rectangle beginning at the point ({x}, {y}) with width w and height h.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 970 of file qpainter.h.
 {
     return boundingRect(QRect(x, y, w, h), flags, text);
 }
boundingRect() [4/4]
QRectF QPainter::boundingRect (const QRectF & rectangle, const QString & text, const QTextOption & option = QTextOption())
Instead of specifying flags as a bitwise OR of the Qt::AlignmentFlag and Qt::TextFlag, this overloaded function takes an option argument.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The QTextOption class provides a description of general rich text properties.
See also
QTextOption
Definition at line 7118 of file qpainter.cpp.
 {
     Q_D(QPainter);
     if (!d->engine || text.length() == 0)
         return QRectF(r.x(),r.y(), 0,0);
     QRectF br;
     qt_format_text(d->state->font, r, Qt::TextDontPrint, &o, text, &br, 0, 0, 0, this);
     return br;
 }
brush()
const QBrush & QPainter::brush () const
Returns the painter's current brush.
See also
QPainter::setBrush(), {QPainter::Settings}{Settings}
Definition at line 4232 of file qpainter.cpp.
Referenced by QSvgFillStyle::apply(), QSvgViewportFillStyle::apply(), QSvgAnimateColor::apply(), QSvgPolyline::draw(), QTextLayout::draw(), QSvgText::draw(), QGraphicsScenePrivate::draw(), QWindowsCEStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QCommonStyle::drawControl(), QMacStyle::drawControl(), drawImage(), drawPixmap(), QCommonStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QTextDocumentLayoutPrivate::drawTableCell(), QCoreGraphicsPaintEngine::drawTextItem(), drawTextItemDecoration(), QVGPaintEngine::fill(), QOpenGLPaintEngine::fill(), fillRect(), qDrawPlainRect(), qDrawShadeRect(), and setBrush().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::brush: Painter not active");
         return d->fakeState()->brush;
     }
     return d->state->brush;
 }
brushOrigin()
QPoint QPainter::brushOrigin () const
Returns the currently set brush origin.
See also
setBrushOrigin(), {QPainter::Settings}{Settings}
Definition at line 2168 of file qpainter.cpp.
Referenced by QItemDelegate::drawBackground(), QTreeView::drawBranches(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QCommonStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QTextDocumentLayoutPrivate::drawTableCell(), QCoreGraphicsPaintEngine::drawTextItem(), drawTextItemDecoration(), QWidgetPrivate::paintBackground(), QHeaderView::paintSection(), and qDrawPlainRect().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::brushOrigin: Painter not active");
         return QPoint();
     }
     return QPointF(d->state->brushOrigin).toPoint();
 }
clipBoundingRect()
QRectF QPainter::clipBoundingRect () const
Returns the bounding rectangle of the current clip if there is a clip; otherwise returns an empty rectangle.
Note that the clip region is given in logical coordinates.
The bounding rectangle is not guaranteed to be tight.
See also
setClipRect(), setClipPath(), setClipRegion()
Since
4.8
Definition at line 2741 of file qpainter.cpp.
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::clipBoundingRect: Painter not active");
         return QRectF();
     }
     // Accumulate the bounding box in device space. This is not 100%
     // precise, but it fits within the guarantee and it is reasonably
     // fast.
     QRectF bounds;
     for (int i=0; i<d->state->clipInfo.size(); ++i) {
          QRectF r;
          const QPainterClipInfo &info = d->state->clipInfo.at(i);
          if (info.clipType == QPainterClipInfo::RectClip)
              r = info.rect;
          else if (info.clipType == QPainterClipInfo::RectFClip)
              r = info.rectf;
          else if (info.clipType == QPainterClipInfo::RegionClip)
              r = info.region.boundingRect();
          else
              r = info.path.boundingRect();
          r = info.matrix.mapRect(r);
          if (i == 0)
              bounds = r;
          else if (info.operation == Qt::IntersectClip)
              bounds &= r;
          else if (info.operation == Qt::UniteClip)
              bounds |= r;
     }
     // Map the rectangle back into logical space using the inverse
     // matrix.
     if (!d->txinv)
         const_cast<QPainter *>(this)->d_ptr->updateInvMatrix();
     return d->invMatrix.mapRect(bounds);
 }
clipPath()
QPainterPath QPainter::clipPath () const
Returns the currently clip as a path.
Note that the clip path is given in logical coordinates.
Warning
QPainter does not store the combined clip explicitly as this is handled by the underlying QPaintEngine, so the path is recreated on demand and transformed to the current logical coordinate system. This is potentially an expensive operation.
See also
setClipPath(), clipRegion(), setClipping()
Definition at line 2690 of file qpainter.cpp.
Referenced by QX11PaintEnginePrivate::systemStateChanged(), QPdfBaseEngine::updateClipPath(), QWin32PrintEngine::updateState(), and QCoreGraphicsPaintEngine::updateState().
 {
     Q_D(const QPainter);
     // ### Since we do not support path intersections and path unions yet,
     // we just use clipRegion() here...
     if (!d->engine) {
         qWarning("QPainter::clipPath: Painter not active");
         return QPainterPath();
     }
     // No clip, return empty
     if (d->state->clipInfo.size() == 0) {
         return QPainterPath();
     } else {
         // Update inverse matrix, used below.
         if (!d->txinv)
             const_cast<QPainter *>(this)->d_ptr->updateInvMatrix();
         // For the simple case avoid conversion.
         if (d->state->clipInfo.size() == 1
             && d->state->clipInfo.at(0).clipType == QPainterClipInfo::PathClip) {
             QTransform matrix = (d->state->clipInfo.at(0).matrix * d->invMatrix);
             return d->state->clipInfo.at(0).path * matrix;
         } else if (d->state->clipInfo.size() == 1
                    && d->state->clipInfo.at(0).clipType == QPainterClipInfo::RectClip) {
             QTransform matrix = (d->state->clipInfo.at(0).matrix * d->invMatrix);
             QPainterPath path;
             path.addRect(d->state->clipInfo.at(0).rect);
             return path * matrix;
         } else {
             // Fallback to clipRegion() for now, since we don't have isect/unite for paths
             return qt_regionToPath(clipRegion());
         }
     }
 }
clipRegion()
QRegion QPainter::clipRegion () const
Returns the currently set clip region.
Note that the clip region is given in logical coordinates.
Warning
QPainter does not store the combined clip explicitly as this is handled by the underlying QPaintEngine, so the path is recreated on demand and transformed to the current logical coordinate system. This is potentially an expensive operation.
See also
setClipRegion(), clipPath(), setClipping()
Definition at line 2562 of file qpainter.cpp.
Referenced by clipPath(), QWindowsXPStylePrivate::drawBackgroundDirectly(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QMacStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsMobileStyle::drawControl(), QDecorationStyled::paint(), QDecorationWindows::paint(), QDecorationDefault::paint(), QDeclarativePaintedItem::paint(), QMacCGContext::QMacCGContext(), QWidget::render(), QOpenGLPaintEngine::updateState(), and QPicturePaintEngine::writeCmdLength().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::clipRegion: Painter not active");
         return QRegion();
     }
     QRegion region;
     bool lastWasNothing = true;
     if (!d->txinv)
         const_cast<QPainter *>(this)->d_ptr->updateInvMatrix();
     // ### Falcon: Use QPainterPath
     for (int i=0; i<d->state->clipInfo.size(); ++i) {
         const QPainterClipInfo &info = d->state->clipInfo.at(i);
         switch (info.clipType) {
         case QPainterClipInfo::RegionClip: {
             QTransform matrix = (info.matrix * d->invMatrix);
             if (lastWasNothing) {
                 region = info.region * matrix;
                 lastWasNothing = false;
                 continue;
             }
             if (info.operation == Qt::IntersectClip)
                 region &= info.region * matrix;
             else if (info.operation == Qt::UniteClip)
                 region |= info.region * matrix;
             else if (info.operation == Qt::NoClip) {
                 lastWasNothing = true;
                 region = QRegion();
             } else
                 region = info.region * matrix;
             break;
         }
         case QPainterClipInfo::PathClip: {
             QTransform matrix = (info.matrix * d->invMatrix);
             if (lastWasNothing) {
                 region = QRegion((info.path * matrix).toFillPolygon().toPolygon(),
                                  info.path.fillRule());
                 lastWasNothing = false;
                 continue;
             }
             if (info.operation == Qt::IntersectClip) {
                 region &= QRegion((info.path * matrix).toFillPolygon().toPolygon(),
                                   info.path.fillRule());
             } else if (info.operation == Qt::UniteClip) {
                 region |= QRegion((info.path * matrix).toFillPolygon().toPolygon(),
                                   info.path.fillRule());
             } else if (info.operation == Qt::NoClip) {
                 lastWasNothing = true;
                 region = QRegion();
             } else {
                 region = QRegion((info.path * matrix).toFillPolygon().toPolygon(),
                                  info.path.fillRule());
             }
             break;
         }
         case QPainterClipInfo::RectClip: {
             QTransform matrix = (info.matrix * d->invMatrix);
             if (lastWasNothing) {
                 region = QRegion(info.rect) * matrix;
                 lastWasNothing = false;
                 continue;
             }
             if (info.operation == Qt::IntersectClip) {
                 // Use rect intersection if possible.
                 if (matrix.type() <= QTransform::TxScale)
                     region &= matrix.mapRect(info.rect);
                 else
                     region &= matrix.map(QRegion(info.rect));
             } else if (info.operation == Qt::UniteClip) {
                 region |= QRegion(info.rect) * matrix;
             } else if (info.operation == Qt::NoClip) {
                 lastWasNothing = true;
                 region = QRegion();
             } else {
                 region = QRegion(info.rect) * matrix;
             }
             break;
         }
         case QPainterClipInfo::RectFClip: {
             QTransform matrix = (info.matrix * d->invMatrix);
             if (lastWasNothing) {
                 region = QRegion(info.rectf.toRect()) * matrix;
                 lastWasNothing = false;
                 continue;
             }
             if (info.operation == Qt::IntersectClip) {
                 // Use rect intersection if possible.
                 if (matrix.type() <= QTransform::TxScale)
                     region &= matrix.mapRect(info.rectf.toRect());
                 else
                     region &= matrix.map(QRegion(info.rectf.toRect()));
             } else if (info.operation == Qt::UniteClip) {
                 region |= QRegion(info.rectf.toRect()) * matrix;
             } else if (info.operation == Qt::NoClip) {
                 lastWasNothing = true;
                 region = QRegion();
             } else {
                 region = QRegion(info.rectf.toRect()) * matrix;
             }
             break;
         }
         }
     }
     return region;
 }
combinedMatrix()
QMatrix QPainter::combinedMatrix () const
Returns the transformation matrix combining the current window/viewport and world transformation.
Since
4.2
It is advisable to use combinedTransform() instead of this function to preserve the properties of perspective transformations.
See also
setWorldTransform(), setWindow(), setViewport()
Definition at line 3082 of file qpainter.cpp.
Referenced by setViewTransformEnabled().
 {
     return combinedTransform().toAffine();
 }
combinedTransform()
QTransform QPainter::combinedTransform () const
Returns the transformation matrix combining the current window/viewport and world transformation.
See also
setWorldTransform(), setWindow(), setViewport()
Definition at line 9669 of file qpainter.cpp.
Referenced by combinedMatrix(), QPixmapConvolutionFilter::draw(), qDrawBorderPixmap(), and QMacCGContext::QMacCGContext().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::combinedTransform: Painter not active");
         return QTransform();
     }
     return d->state->worldMatrix * d->viewTransform();
 }
compositionMode()
QPainter::CompositionMode QPainter::compositionMode () const
Returns the current composition mode.
See also
CompositionMode, setCompositionMode()
Definition at line 2466 of file qpainter.cpp.
Referenced by QSvgCompOpStyle::apply(), QDeclarativePaintedItem::paint(), and QWidgetPrivate::paintBackground().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::compositionMode: Painter not active");
         return QPainter::CompositionMode_SourceOver;
     }
     return d->state->composition_mode;
 }
device()
QPaintDevice * QPainter::device () const
Returns the paint device on which this painter is currently painting, or 0 if the painter is not active.
See also
isActive()
Definition at line 1530 of file qpainter.cpp.
Referenced by begin(), QWindowsXPStylePrivate::drawBackground(), QRasterPaintEngine::drawCachedGlyphs(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QGraphicsView::drawItems(), QEmulationPaintEngine::drawTextItem(), QPicture::exec(), QEmulationPaintEngine::fill(), fillRegion(), QSvgTinyDocument::mapSourceToTarget(), QDeclarativePaintedItem::paint(), ShaderEffect::prepareBufferedDraw(), QMacCGContext::QMacCGContext(), qt_mac_fill_background(), redirected(), QGraphicsScene::render(), QGraphicsView::render(), QWidgetPrivate::render_helper(), ShaderEffectItem::renderEffect(), restoreRedirected(), setFont(), QPainterReplayer::setupTransform(), and QEmulationPaintEngine::stroke().
 {
     Q_D(const QPainter);
     if (isActive() && d->engine->d_func()->currentClipWidget)
         return d->engine->d_func()->currentClipWidget;
     return d->original_device;
 }
deviceMatrix()
const QMatrix & QPainter::deviceMatrix () const
Returns the matrix that transforms from logical coordinates to device coordinates of the platform dependent paint device.
Note
It is advisable to use deviceTransform() instead of this function to preserve the properties of perspective transformations.
This function is only needed when using platform painting commands on the platform dependent handle (Qt::HANDLE), and the platform does not do transformations nativly.
The QPaintEngine::PaintEngineFeature enum can be queried to determine whether the platform performs the transformations or not.
See also
worldMatrix(), QPaintEngine::hasFeature(),
Definition at line 3110 of file qpainter.cpp.
Referenced by QWindowsXPStylePrivate::drawBackgroundDirectly().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::deviceMatrix: Painter not active");
         return d->fakeState()->transform.toAffine();
     }
     return d->state->matrix.toAffine();
 }
deviceTransform()
const QTransform & QPainter::deviceTransform () const
Returns the matrix that transforms from logical coordinates to device coordinates of the platform dependent paint device.
This function is only needed when using platform painting commands on the platform dependent handle (Qt::HANDLE), and the platform does not do transformations nativly.
The QPaintEngine::PaintEngineFeature enum can be queried to determine whether the platform performs the transformations or not.
See also
worldTransform(), QPaintEngine::hasFeature(),
Definition at line 9579 of file qpainter.cpp.
Referenced by QPixmapConvolutionFilter::draw(), QWindowsXPStylePrivate::drawBackground(), QDeclarativePaintedItem::paint(), QMacCGContext::QMacCGContext(), qt_plastique_draw_gradient(), and QWidget::render().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::deviceTransform: Painter not active");
         return d->fakeState()->transform;
     }
     return d->state->matrix;
 }
drawArc() [1/3]
void QPainter::drawArc (const QRectF & rectangle, int startAngle, int spanAngle)
Draws the arc defined by the given rectangle, startAngle and spanAngle.
The startAngle and spanAngle must be specified in 1/16th of a degree, i.e. a full circle equals 5760 (16 * 360). Positive values for the angles mean counter-clockwise while negative values mean the clockwise direction. Zero degrees is at the 3 o'clock position.
QRectF rectangle(10.0, 20.0, 80.0, 60.0);
int startAngle = 30 * 16;
int spanAngle = 120 * 16;
QPainter painter(this);
painter.drawArc(rectangle, startAngle, spanAngle);
See also
drawPie(), drawChord(), {Coordinate System}
Definition at line 4602 of file qpainter.cpp.
Referenced by QCommonStyle::drawComplexControl(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), drawTabShape(), QPicture::exec(), and qDrawRoundedCorners().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawArc(), [%.2f,%.2f,%.2f,%.2f], angle=%d, sweep=%d\n",
            r.x(), r.y(), r.width(), r.height(), a/16, alen/16);
 #endif
     Q_D(QPainter);
     if (!d->engine)
         return;
     QRectF rect = r.normalized();
     QPainterPath path;
     path.arcMoveTo(rect, a/qreal(16.0));
     path.arcTo(rect, a/qreal(16.0), alen/qreal(16.0));
     strokePath(path, d->state->pen);
 }
drawArc() [2/3]
void QPainter::drawArc (const QRect & rectangle, int startAngle, int spanAngle) inline
Draws the arc defined by the given rectangle, startAngle and spanAngle.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 739 of file qpainter.h.
 {
     drawArc(QRectF(r), a, alen);
 }
drawArc() [3/3]
void QPainter::drawArc (int x, int y, int width, int height, int startAngle, int spanAngle) inline
Draws the arc defined by the rectangle beginning at (x, y) with the specified width and height, and the given startAngle and spanAngle.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 744 of file qpainter.h.
 {
     drawArc(QRectF(x, y, w, h), a, alen);
 }
drawChord() [1/3]
void QPainter::drawChord (const QRectF & rectangle, int startAngle, int spanAngle)
Draws the chord defined by the given rectangle, startAngle and spanAngle.
The chord is filled with the current brush().
The startAngle and spanAngle must be specified in 1/16th of a degree, i.e. a full circle equals 5760 (16 * 360). Positive values for the angles mean counter-clockwise while negative values mean the clockwise direction. Zero degrees is at the 3 o'clock position.
QRectF rectangle(10.0, 20.0, 80.0, 60.0);
int startAngle = 30 * 16;
int spanAngle = 120 * 16;
QPainter painter(this);
painter.drawChord(rect, startAngle, spanAngle);
See also
drawArc(), drawPie(), {Coordinate System}
Definition at line 4744 of file qpainter.cpp.
Referenced by QPicture::exec().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawChord(), [%.2f,%.2f,%.2f,%.2f], angle=%d, sweep=%d\n",
            r.x(), r.y(), r.width(), r.height(), a/16, alen/16);
 #endif
     Q_D(QPainter);
     if (!d->engine)
         return;
     QRectF rect = r.normalized();
     QPainterPath path;
     path.arcMoveTo(rect, a/qreal(16.0));
     path.arcTo(rect, a/qreal(16.0), alen/qreal(16.0));
     path.closeSubpath();
     drawPath(path);
 }
drawChord() [2/3]
void QPainter::drawChord (int x, int y, int width, int height, int startAngle, int spanAngle) inline
Draws the chord defined by the rectangle beginning at (x, y) with the specified width and height, and the given startAngle and spanAngle.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 764 of file qpainter.h.
 {
     drawChord(QRectF(x, y, w, h), a, alen);
 }
drawChord() [3/3]
void QPainter::drawChord (const QRect & rectangle, int startAngle, int spanAngle) inline
Draws the chord defined by the given rectangle, startAngle and spanAngle.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 759 of file qpainter.h.
 {
     drawChord(QRectF(rect), a, alen);
 }
drawConvexPolygon() [1/4]
void QPainter::drawConvexPolygon (const QPointF * points, int pointCount)
Draws the convex polygon defined by the first pointCount points in the array points using the current pen.
static const QPointF points[4] = {
    QPointF(10.0, 80.0),
    QPointF(20.0, 10.0),
    QPointF(80.0, 30.0),
    QPointF(90.0, 70.0)
};
QPainter painter(this);
painter.drawConvexPolygon(points, 4);
The first point is implicitly connected to the last point, and the polygon is filled with the current brush(). If the supplied polygon is not convex, i.e. it contains at least one angle larger than 180 degrees, the results are undefined.
On some platforms (e.g. X11), the drawConvexPolygon() function can be faster than the drawPolygon() function.
See also
drawPolygon(), drawPolyline(), {Coordinate System}
Definition at line 5484 of file qpainter.cpp.
Referenced by QPainterReplayer::process(), and qDrawEdge().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawConvexPolygon(), count=%d\n", pointCount);
 #endif
     Q_D(QPainter);
     if (!d->engine || pointCount < 2)
         return;
     if (d->extended) {
         d->extended->drawPolygon(points, pointCount, QPaintEngine::ConvexMode);
         return;
     }
     d->updateState(d->state);
     uint emulationSpecifier = d->state->emulationSpecifier;
     if (emulationSpecifier) {
         QPainterPath polygonPath(points[0]);
         for (int i=1; i<pointCount; ++i)
             polygonPath.lineTo(points[i]);
         polygonPath.closeSubpath();
         polygonPath.setFillRule(Qt::WindingFill);
         d->draw_helper(polygonPath);
         return;
     }
     d->engine->drawPolygon(points, pointCount, QPaintEngine::ConvexMode);
 }
drawConvexPolygon() [2/4]
void QPainter::drawConvexPolygon (const QPolygonF & polygon) inline
Draws the convex polygon defined by polygon using the current pen and brush.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 640 of file qpainter.h.
 {
     drawConvexPolygon(poly.constData(), poly.size());
 }
drawConvexPolygon() [3/4]
void QPainter::drawConvexPolygon (const QPoint * points, int pointCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the convex polygon defined by the first pointCount points in the array points using the current pen.
Definition at line 5450 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawConvexPolygon(), count=%d\n", pointCount);
 #endif
     Q_D(QPainter);
     if (!d->engine || pointCount < 2)
         return;
     if (d->extended) {
         d->extended->drawPolygon(points, pointCount, QPaintEngine::ConvexMode);
         return;
     }
     d->updateState(d->state);
     uint emulationSpecifier = d->state->emulationSpecifier;
     if (emulationSpecifier) {
         QPainterPath polygonPath(points[0]);
         for (int i=1; i<pointCount; ++i)
             polygonPath.lineTo(points[i]);
         polygonPath.closeSubpath();
         polygonPath.setFillRule(Qt::WindingFill);
         d->draw_helper(polygonPath);
         return;
     }
     d->engine->drawPolygon(points, pointCount, QPaintEngine::ConvexMode);
 }
drawConvexPolygon() [4/4]
void QPainter::drawConvexPolygon (const QPolygon & polygon) inline
Draws the convex polygon defined by polygon using the current pen and brush.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 645 of file qpainter.h.
 {
     drawConvexPolygon(poly.constData(), poly.size());
 }
drawEllipse() [1/5]
void QPainter::drawEllipse (const QRectF & rectangle)
Draws the ellipse defined by the given rectangle.
A filled ellipse has a size of {rectangle}.QRect::size() . A stroked ellipse has a size of {rectangle}.QRect::size(){size()} plus the pen width.
QRectF rectangle(10.0, 20.0, 80.0, 60.0);
QPainter painter(this);
painter.drawEllipse(rectangle);
See also
drawPie(), {Coordinate System}
Definition at line 4464 of file qpainter.cpp.
Referenced by QSvgEllipse::draw(), QCommonStyle::drawComplexControl(), QCleanlooksStyle::drawControl(), QStyleHelper::drawDial(), QTextDocumentLayoutPrivate::drawListItem(), QPaintEngine::drawPoints(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), drawTabCloseButton(), QPicture::exec(), QGraphicsEllipseItem::paint(), and QPainterReplayer::process().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawEllipse(), [%.2f,%.2f,%.2f,%.2f]\n", r.x(), r.y(), r.width(), r.height());
 #endif
     Q_D(QPainter);
     if (!d->engine)
         return;
     QRectF rect(r.normalized());
     if (d->extended) {
         d->extended->drawEllipse(rect);
         return;
     }
     d->updateState(d->state);
     if (d->state->emulationSpecifier) {
         if (d->state->emulationSpecifier == QPaintEngine::PrimitiveTransform
             && d->state->matrix.type() == QTransform::TxTranslate) {
             rect.translate(QPointF(d->state->matrix.dx(), d->state->matrix.dy()));
         } else {
             QPainterPath path;
             path.addEllipse(rect);
             d->draw_helper(path, QPainterPrivate::StrokeAndFillDraw);
             return;
         }
     }
     d->engine->drawEllipse(rect);
 }
drawEllipse() [2/5]
void QPainter::drawEllipse (const QRect & rectangle)
Draws the ellipse defined by the given rectangle.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4508 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawEllipse(), [%d,%d,%d,%d]\n", r.x(), r.y(), r.width(), r.height());
 #endif
     Q_D(QPainter);
     if (!d->engine)
         return;
     QRect rect(r.normalized());
     if (d->extended) {
         d->extended->drawEllipse(rect);
         return;
     }
     d->updateState(d->state);
     if (d->state->emulationSpecifier) {
         if (d->state->emulationSpecifier == QPaintEngine::PrimitiveTransform
             && d->state->matrix.type() == QTransform::TxTranslate) {
             rect.translate(QPoint(qRound(d->state->matrix.dx()), qRound(d->state->matrix.dy())));
         } else {
             QPainterPath path;
             path.addEllipse(rect);
             d->draw_helper(path, QPainterPrivate::StrokeAndFillDraw);
             return;
         }
     }
     d->engine->drawEllipse(rect);
 }
drawEllipse() [3/5]
void QPainter::drawEllipse (int x, int y, int width, int height) inline
Draws the ellipse defined by the rectangle beginning at ({x}, {y}) with the given width and height.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 724 of file qpainter.h.
 {
     drawEllipse(QRect(x, y, w, h));
 }
drawEllipse() [4/5]
void QPainter::drawEllipse (const QPointF & center, qreal rx, qreal ry) inline
Draws the ellipse positioned at {center} with radii {rx} and {ry}.
Since
4.4
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 729 of file qpainter.h.
 {
     drawEllipse(QRectF(center.x() - rx, center.y() - ry, 2 * rx, 2 * ry));
 }
drawEllipse() [5/5]
void QPainter::drawEllipse (const QPoint & center, int rx, int ry) inline
Draws the ellipse positioned at {center} with radii {rx} and {ry}.
Since
4.4
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 734 of file qpainter.h.
 {
     drawEllipse(QRect(center.x() - rx, center.y() - ry, 2 * rx, 2 * ry));
 }
drawGlyphRun()
void QPainter::drawGlyphRun (const QPointF & position, const QGlyphRun & glyphs)
Draws the specified glyphs at the given position.
The position gives the edge of the baseline for the string of glyphs. The glyphs will be retrieved from the font selected by glyphs and at offsets given by the positions in glyphs.
Since
4.8
See also
QGlyphRun::setRawFont(), QGlyphRun::setPositions(), QGlyphRun::setGlyphIndexes()
Definition at line 6064 of file qpainter.cpp.
Referenced by QPainterReplayer::process().
 {
     Q_D(QPainter);
     QRawFont font = glyphRun.rawFont();
     if (!font.isValid())
         return;
     QGlyphRunPrivate *glyphRun_d = QGlyphRunPrivate::get(glyphRun);
     const quint32 *glyphIndexes = glyphRun_d->glyphIndexData;
     const QPointF *glyphPositions = glyphRun_d->glyphPositionData;
     int count = qMin(glyphRun_d->glyphIndexDataSize, glyphRun_d->glyphPositionDataSize);
     QVarLengthArray<QFixedPoint, 128> fixedPointPositions(count);
     QRawFontPrivate *fontD = QRawFontPrivate::get(font);
     bool supportsTransformations;
     if (d->extended != 0) {
         supportsTransformations = d->extended->supportsTransformations(fontD->fontEngine->fontDef.pixelSize,
                                                                        d->state->matrix);
     } else {
         supportsTransformations = d->engine->type() == QPaintEngine::CoreGraphics
                                   || d->state->matrix.isAffine();
     }
     for (int i=0; i<count; ++i) {
         QPointF processedPosition = position + glyphPositions[i];
         if (!supportsTransformations)
             processedPosition = d->state->transform().map(processedPosition);
         fixedPointPositions[i] = QFixedPoint::fromPointF(processedPosition);
     }
     d->drawGlyphs(glyphIndexes, fixedPointPositions.data(), count, font, glyphRun.overline(),
                   glyphRun.underline(), glyphRun.strikeOut());
 }
drawImage() [1/9]
void QPainter::drawImage (const QRectF & targetRect, const QImage & image, const QRectF & sourceRect, Qt::ImageConversionFlags flags = Qt::AutoColor)
Definition at line 5936 of file qpainter.cpp.
Referenced by blendCursor(), buttonChange(), QLinuxFbScreen::doRedraw(), QFbScreen::doRedraw(), QSvgImage::draw(), QPixmapConvolutionFilter::draw(), QPixmapColorizeFilter::draw(), QPixmapDropShadowFilter::draw(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QWindowsVistaAnimation::drawBlendedImage(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QPlatformSoftwareCursor::drawCursor(), QTextImageHandler::drawObject(), QWindowsMobileStylePrivate::drawPanelItemViewSelected(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsMobileStylePrivate::drawScrollbarGrip(), QWindowsMobileStylePrivate::drawScrollbarHandleDown(), QWindowsMobileStylePrivate::drawScrollbarHandleUp(), QWindowsMobileStylePrivate::drawTabBarTab(), QPicture::exec(), operator>>(), QBlittablePixmapData::paintEngine(), QPainterReplayer::process(), qt_blurImage(), qt_plastique_draw_handle(), toVGImageWithOpacity(), toVGImageWithOpacitySubRect(), and QImage::transformed().
 {
     Q_D(QPainter);
     if (!d->engine || image.isNull())
         return;
     qreal x = targetRect.x();
     qreal y = targetRect.y();
     qreal w = targetRect.width();
     qreal h = targetRect.height();
     qreal sx = sourceRect.x();
     qreal sy = sourceRect.y();
     qreal sw = sourceRect.width();
     qreal sh = sourceRect.height();
     // Sanity-check clipping
     if (sw <= 0)
         sw = image.width() - sx;
     if (sh <= 0)
         sh = image.height() - sy;
     if (w < 0)
         w = sw;
     if (h < 0)
         h = sh;
     if (sx < 0) {
         qreal w_ratio = sx * w/sw;
         x -= w_ratio;
         w += w_ratio;
         sw += sx;
         sx = 0;
     }
     if (sy < 0) {
         qreal h_ratio = sy * h/sh;
         y -= h_ratio;
         h += h_ratio;
         sh += sy;
         sy = 0;
     }
     if (sw + sx > image.width()) {
         qreal delta = sw - (image.width() - sx);
         qreal w_ratio = delta * w/sw;
         sw -= delta;
         w -= w_ratio;
     }
     if (sh + sy > image.height()) {
         qreal delta = sh - (image.height() - sy);
         qreal h_ratio = delta * h/sh;
         sh -= delta;
         h -= h_ratio;
     }
     if (w == 0 || h == 0 || sw <= 0 || sh <= 0)
         return;
     if (d->extended) {
         d->extended->drawImage(QRectF(x, y, w, h), image, QRectF(sx, sy, sw, sh), flags);
         return;
     }
     d->updateState(d->state);
     if (((d->state->matrix.type() > QTransform::TxTranslate || (sw != w || sh != h))
          && !d->engine->hasFeature(QPaintEngine::PixmapTransform))
         || (!d->state->matrix.isAffine() && !d->engine->hasFeature(QPaintEngine::PerspectiveTransform))
         || (d->state->opacity != 1.0 && !d->engine->hasFeature(QPaintEngine::ConstantOpacity)))
     {
         save();
         // If there is no rotation involved we have to make sure we use the
         // antialiased and not the aliased coordinate system by rounding the coordinates.
         if (d->state->matrix.type() <= QTransform::TxScale) {
             const QPointF p = roundInDeviceCoordinates(QPointF(x, y), d->state->matrix);
             x = p.x();
             y = p.y();
         }
         if (d->state->matrix.type() <= QTransform::TxTranslate && sw == w && sh == h) {
             sx = qRound(sx);
             sy = qRound(sy);
             sw = qRound(sw);
             sh = qRound(sh);
         }
         translate(x, y);
         scale(w / sw, h / sh);
         setBackgroundMode(Qt::TransparentMode);
         setRenderHint(Antialiasing, renderHints() & SmoothPixmapTransform);
         QBrush brush(image);
         setBrush(brush);
         setPen(Qt::NoPen);
         setBrushOrigin(QPointF(-sx, -sy));
         drawRect(QRectF(0, 0, sw, sh));
         restore();
         return;
     }
     if (d->state->matrix.type() == QTransform::TxTranslate
         && !d->engine->hasFeature(QPaintEngine::PixmapTransform)) {
         x += d->state->matrix.dx();
         y += d->state->matrix.dy();
     }
     d->engine->drawImage(QRectF(x, y, w, h), image, QRectF(sx, sy, sw, sh), flags);
 }
drawImage() [2/9]
void QPainter::drawImage (const QRect & targetRect, const QImage & image, const QRect & sourceRect, Qt::ImageConversionFlags flags = Qt::AutoColor) inline
Definition at line 897 of file qpainter.h.
 {
     drawImage(QRectF(targetRect), image, QRectF(sourceRect), flags);
 }
drawImage() [3/9]
void QPainter::drawImage (const QPointF & p, const QImage & image, const QRectF & sr, Qt::ImageConversionFlags flags = Qt::AutoColor) inline
Definition at line 903 of file qpainter.h.
 {
     drawImage(QRectF(p.x(), p.y(), -1, -1), image, sr, flags);
 }
drawImage() [4/9]
void QPainter::drawImage (const QPoint & p, const QImage & image, const QRect & sr, Qt::ImageConversionFlags flags = Qt::AutoColor) inline
Definition at line 909 of file qpainter.h.
 {
     drawImage(QRect(p.x(), p.y(), -1, -1), image, sr, flags);
 }
drawImage() [5/9]
void QPainter::drawImage (const QRectF & rectangle, const QImage & image) inline
Draws the given image into the given rectangle.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note
The image is scaled to fit the rectangle, if both the image and rectangle size disagree.
Definition at line 916 of file qpainter.h.
 {
     drawImage(r, image, QRect(0, 0, image.width(), image.height()));
 }
drawImage() [6/9]
void QPainter::drawImage (const QRect & rectangle, const QImage & image) inline
Draws the given image into the given rectangle.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note
The image is scaled to fit the rectangle, if both the image and rectangle size disagree.
Definition at line 921 of file qpainter.h.
 {
     drawImage(r, image, QRectF(0, 0, image.width(), image.height()));
 }
drawImage() [7/9]
void QPainter::drawImage (const QPointF & point, const QImage & image)
Draws the given image at the given point.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 5881 of file qpainter.cpp.
 {
     Q_D(QPainter);
     if (!d->engine || image.isNull())
         return;
     if (d->extended) {
         d->extended->drawImage(p, image);
         return;
     }
     qreal x = p.x();
     qreal y = p.y();
     int w = image.width();
     int h = image.height();
     d->updateState(d->state);
     if (((d->state->matrix.type() > QTransform::TxTranslate)
          && !d->engine->hasFeature(QPaintEngine::PixmapTransform))
         || (!d->state->matrix.isAffine() && !d->engine->hasFeature(QPaintEngine::PerspectiveTransform))
         || (d->state->opacity != 1.0 && !d->engine->hasFeature(QPaintEngine::ConstantOpacity)))
     {
         save();
         // If there is no rotation involved we have to make sure we use the
         // antialiased and not the aliased coordinate system by rounding the coordinates.
         if (d->state->matrix.type() <= QTransform::TxScale) {
             const QPointF p = roundInDeviceCoordinates(QPointF(x, y), d->state->matrix);
             x = p.x();
             y = p.y();
         }
         translate(x, y);
         setBackgroundMode(Qt::TransparentMode);
         setRenderHint(Antialiasing, renderHints() & SmoothPixmapTransform);
         QBrush brush(image);
         setBrush(brush);
         setPen(Qt::NoPen);
         setBrushOrigin(QPointF(0, 0));
         drawRect(image.rect());
         restore();
         return;
     }
     if (d->state->matrix.type() == QTransform::TxTranslate
         && !d->engine->hasFeature(QPaintEngine::PixmapTransform)) {
         x += d->state->matrix.dx();
         y += d->state->matrix.dy();
     }
     d->engine->drawImage(QRectF(x, y, w, h), image, QRectF(0, 0, w, h), Qt::AutoColor);
 }
drawImage() [8/9]
void QPainter::drawImage (const QPoint & point, const QImage & image) inline
Draws the given image at the given point.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 926 of file qpainter.h.
 {
     drawImage(QPointF(p), image);
 }
drawImage() [9/9]
void QPainter::drawImage (int x, int y, const QImage & image, int sx = 0, int sy = 0, int sw = -1, int sh = -1, Qt::ImageConversionFlags flags = Qt::AutoColor) inline
Definition at line 931 of file qpainter.h.
 {
     if (sx == 0 && sy == 0 && sw == -1 && sh == -1 && flags == Qt::AutoColor)
         drawImage(QPointF(x, y), image);
     else
         drawImage(QRectF(x, y, -1, -1), image, QRectF(sx, sy, sw, sh), flags);
 }
drawLine() [1/5]
void QPainter::drawLine (const QLineF & line) inline
Draws a line defined by line.
QLineF line(10.0, 80.0, 90.0, 20.0);
QPainter(this);
painter.drawLine(line);
See also
drawLines(), drawPolyline(), {Coordinate System}
Definition at line 573 of file qpainter.h.
Referenced by QSvgLine::draw(), QPainterPrivate::draw_helper(), QTextDocumentLayoutPrivate::drawBlock(), QCommonStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QTextLayout::drawCursor(), QStyleHelper::drawDial(), QPlastiqueStylePrivate::drawPartialFrame(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QWindowsMobileStylePrivate::drawScrollbarGrip(), QWindowsMobileStylePrivate::drawScrollbarHandleDown(), QWindowsMobileStylePrivate::drawScrollbarHandleUp(), QWindowsMobileStylePrivate::drawTabBarTab(), drawTabBase(), drawTabCloseButton(), drawTabShape(), drawTextItemDecoration(), QPicture::exec(), QScriptEdit::extraAreaPaintEvent(), QTriangulator< T >::ComplexToSimple::Event::operator<(), QGraphicsLineItem::paint(), QWellArray::paintCellContents(), QTableView::paintEvent(), QPagePreview::paintEvent(), QWhatsThat::paintEvent(), QWizardHeader::paintEvent(), QWizardAntiFlickerWidget::paintEvent(), qDrawEdge(), qDrawPlainRect(), qDrawShadeLine(), and qt_cleanlooks_draw_mdibutton().
 {
     drawLines(&l, 1);
 }
drawLine() [2/5]
void QPainter::drawLine (const QLine & line) inline
Draws a line defined by line.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 578 of file qpainter.h.
 {
     drawLines(&line, 1);
 }
drawLine() [3/5]
void QPainter::drawLine (int x1, int y1, int x2, int y2) inline
Draws a line from (x1, y1) to (x2, y2) and sets the current pen position to (x2, y2).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 583 of file qpainter.h.
 {
     QLine l(x1, y1, x2, y2);
     drawLines(&l, 1);
 }
drawLine() [4/5]
void QPainter::drawLine (const QPoint & p1, const QPoint & p2) inline
Draws a line from p1 to p2.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 589 of file qpainter.h.
 {
     QLine l(p1, p2);
     drawLines(&l, 1);
 }
drawLine() [5/5]
void QPainter::drawLine (const QPointF & p1, const QPointF & p2) inline
Draws a line from p1 to p2.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 595 of file qpainter.h.
 {
     drawLine(QLineF(p1, p2));
 }
drawLines() [1/8]
void QPainter::drawLines (const QLineF * lines, int lineCount)
Draws the first lineCount lines in the array lines using the current pen.
See also
drawLine(), drawPolyline()
Definition at line 4873 of file qpainter.cpp.
Referenced by QCommonStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QStyleHelper::drawDial(), drawLines(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QPicture::exec(), QPainterReplayer::process(), qDrawPlainRect(), qDrawShadePanel(), qDrawShadeRect(), qt_cleanlooks_draw_mdibutton(), qt_plastique_draw_frame(), qt_plastique_draw_mdibutton(), and qt_plastique_drawFrame().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawLines(), line count=%d\n", lineCount);
 #endif
     Q_D(QPainter);
     if (!d->engine || lineCount < 1)
         return;
     if (d->extended) {
         d->extended->drawLines(lines, lineCount);
         return;
     }
     d->updateState(d->state);
     uint lineEmulation = line_emulation(d->state->emulationSpecifier);
     if (lineEmulation) {
         if (lineEmulation == QPaintEngine::PrimitiveTransform
             && d->state->matrix.type() == QTransform::TxTranslate) {
             for (int i = 0; i < lineCount; ++i) {
                 QLineF line = lines[i];
                 line.translate(d->state->matrix.dx(), d->state->matrix.dy());
                 d->engine->drawLines(&line, 1);
             }
         } else {
             QPainterPath linePath;
             for (int i = 0; i < lineCount; ++i) {
                 linePath.moveTo(lines[i].p1());
                 linePath.lineTo(lines[i].p2());
             }
             d->draw_helper(linePath, QPainterPrivate::StrokeDraw);
         }
         return;
     }
     d->engine->drawLines(lines, lineCount);
 }
drawLines() [2/8]
void QPainter::drawLines (const QVector< QLineF > & lines) inline
Draws the set of lines defined by the list lines using the current pen and brush.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 600 of file qpainter.h.
 {
     drawLines(lines.constData(), lines.size());
 }
drawLines() [3/8]
void QPainter::drawLines (const QPointF * pointPairs, int lineCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the first lineCount lines in the array pointPairs using the current pen.
The lines are specified as pairs of points so the number of entries in pointPairs must be at least lineCount * 2.
Definition at line 4972 of file qpainter.cpp.
 {
     Q_ASSERT(sizeof(QLineF) == 2*sizeof(QPointF));
     drawLines((QLineF*)pointPairs, lineCount);
 }
drawLines() [4/8]
void QPainter::drawLines (const QVector< QPointF > & pointPairs) inline
Draws a line for each pair of points in the vector pointPairs using the current pen.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If there is an odd number of points in the array, the last point will be ignored.
Definition at line 610 of file qpainter.h.
 {
     drawLines(pointPairs.constData(), pointPairs.size() / 2);
 }
drawLines() [5/8]
void QPainter::drawLines (const QLine * lines, int lineCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the first lineCount lines in the array lines using the current pen.
Definition at line 4922 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawLine(), line count=%d\n", lineCount);
 #endif
     Q_D(QPainter);
     if (!d->engine || lineCount < 1)
         return;
     if (d->extended) {
         d->extended->drawLines(lines, lineCount);
         return;
     }
     d->updateState(d->state);
     uint lineEmulation = line_emulation(d->state->emulationSpecifier);
     if (lineEmulation) {
         if (lineEmulation == QPaintEngine::PrimitiveTransform
             && d->state->matrix.type() == QTransform::TxTranslate) {
             for (int i = 0; i < lineCount; ++i) {
                 QLineF line = lines[i];
                 line.translate(d->state->matrix.dx(), d->state->matrix.dy());
                 d->engine->drawLines(&line, 1);
             }
         } else {
             QPainterPath linePath;
             for (int i = 0; i < lineCount; ++i) {
                 linePath.moveTo(lines[i].p1());
                 linePath.lineTo(lines[i].p2());
             }
             d->draw_helper(linePath, QPainterPrivate::StrokeDraw);
         }
         return;
     }
     d->engine->drawLines(lines, lineCount);
 }
drawLines() [6/8]
void QPainter::drawLines (const QVector< QLine > & lines) inline
Draws the set of lines defined by the list lines using the current pen and brush.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 605 of file qpainter.h.
 {
     drawLines(lines.constData(), lines.size());
 }
drawLines() [7/8]
void QPainter::drawLines (const QPoint * pointPairs, int lineCount)
Draws the first lineCount lines in the array pointPairs using the current pen.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4988 of file qpainter.cpp.
 {
     Q_ASSERT(sizeof(QLine) == 2*sizeof(QPoint));
     drawLines((QLine*)pointPairs, lineCount);
 }
drawLines() [8/8]
void QPainter::drawLines (const QVector< QPoint > & pointPairs) inline
Draws a line for each pair of points in the vector pointPairs using the current pen.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 615 of file qpainter.h.
 {
     drawLines(pointPairs.constData(), pointPairs.size() / 2);
 }
drawPath()
void QPainter::drawPath (const QPainterPath & path)
Draws the given painter path using the current pen for outline and the current brush for filling.
QPainterPath path;
path.moveTo(20, 80);
path.lineTo(20, 30);
path.cubicTo(80, 0, 50, 50, 80, 80);
QPainter painter(this);
painter.drawPath(path);
See also
{painting/painterpaths}{the Painter Paths example},{demos/deform}{the Vector Deformation demo}
Definition at line 3502 of file qpainter.cpp.
Referenced by QFontEngine::alphaMapForGlyph(), alphaMapFromPath(), QBalloonTip::balloon(), QSvgArc::draw(), QSvgFont::draw(), QSvgPath::draw(), QTextLayout::draw(), QTextLine::draw(), QPainterPrivate::draw_helper(), drawChord(), QPlastiqueStyle::drawComplexControl(), QCommonStyle::drawControl(), QX11PaintEngine::drawFreetype(), drawPie(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QMacStyle::drawPrimitive(), drawRoundedRect(), QPicture::exec(), fillPath(), generateWavyPixmap(), QGraphicsPathItem::paint(), QPainterReplayer::process(), and strokePath().
 {
 #ifdef QT_DEBUG_DRAW
     QRectF pathBounds = path.boundingRect();
     if (qt_show_painter_debug_output)
         printf("QPainter::drawPath(), size=%d, [%.2f,%.2f,%.2f,%.2f]\n",
                path.elementCount(),
                pathBounds.x(), pathBounds.y(), pathBounds.width(), pathBounds.height());
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::drawPath: Painter not active");
         return;
     }
     if (d->extended) {
         d->extended->drawPath(path);
         return;
     }
     d->updateState(d->state);
     if (d->engine->hasFeature(QPaintEngine::PainterPaths) && d->state->emulationSpecifier == 0) {
         d->engine->drawPath(path);
     } else {
         d->draw_helper(path);
     }
 }
drawPicture() [1/3]
void QPainter::drawPicture (const QPointF & point, const QPicture & picture)
Replays the given picture at the given point.
The QPicture class is a paint device that records and replays QPainter commands. A picture serializes the painter commands to an IO device in a platform-independent format. Everything that can be painted on a widget or pixmap can also be stored in a picture.
This function does exactly the same as QPicture::play() when called with point = QPoint(0, 0).
QPicture picture;
QPointF point(10.0, 20.0)
picture.load("drawing.pic");
QPainter painter(this);
painter.drawPicture(0, 0, picture);
See also
QPicture::play()
Definition at line 7282 of file qpainter.cpp.
Referenced by QAlphaPaintEnginePrivate::drawAlphaImage(), QAlphaPaintEngine::flushAndInit(), and QLabel::paintEvent().
 {
     Q_D(QPainter);
     if (!d->engine)
         return;
     if (!d->extended)
         d->updateState(d->state);
     save();
     translate(p);
     const_cast<QPicture *>(&picture)->play(this);
     restore();
 }
drawPicture() [2/3]
void QPainter::drawPicture (int x, int y, const QPicture & picture) inline
Draws the given picture at point (x, y).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 996 of file qpainter.h.
 {
     drawPicture(QPoint(x, y), p);
 }
drawPicture() [3/3]
void QPainter::drawPicture (const QPoint & point, const QPicture & picture) inline
Replays the given picture at the given point.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1001 of file qpainter.h.
 {
     drawPicture(QPointF(pt), p);
 }
drawPie() [1/3]
void QPainter::drawPie (const QRectF & rectangle, int startAngle, int spanAngle)
Draws a pie defined by the given rectangle, startAngle and and spanAngle.
The pie is filled with the current brush().
The startAngle and spanAngle must be specified in 1/16th of a degree, i.e. a full circle equals 5760 (16 * 360). Positive values for the angles mean counter-clockwise while negative values mean the clockwise direction. Zero degrees is at the 3 o'clock position.
QRectF rectangle(10.0, 20.0, 80.0, 60.0);
int startAngle = 30 * 16;
int spanAngle = 120 * 16;
QPainter painter(this);
painter.drawPie(rectangle, startAngle, spanAngle);
See also
drawEllipse(), drawChord(), {Coordinate System}
Definition at line 4670 of file qpainter.cpp.
Referenced by QPicture::exec(), and QGraphicsEllipseItem::paint().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawPie(), [%.2f,%.2f,%.2f,%.2f], angle=%d, sweep=%d\n",
            r.x(), r.y(), r.width(), r.height(), a/16, alen/16);
 #endif
     Q_D(QPainter);
     if (!d->engine)
         return;
     if (a > (360*16)) {
         a = a % (360*16);
     } else if (a < 0) {
         a = a % (360*16);
         if (a < 0) a += (360*16);
     }
     QRectF rect = r.normalized();
     QPainterPath path;
     path.moveTo(rect.center());
     path.arcTo(rect.x(), rect.y(), rect.width(), rect.height(), a/qreal(16.0), alen/qreal(16.0));
     path.closeSubpath();
     drawPath(path);
 }
drawPie() [2/3]
void QPainter::drawPie (int x, int y, int w, int h, int a, int alen) inline
Definition at line 754 of file qpainter.h.
 {
     drawPie(QRectF(x, y, w, h), a, alen);
 }
drawPie() [3/3]
void QPainter::drawPie (const QRect & rectangle, int startAngle, int spanAngle) inline
Draws a pie defined by the given rectangle, startAngle and and spanAngle.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 749 of file qpainter.h.
 {
     drawPie(QRectF(rect), a, alen);
 }
drawPixmap() [1/11]
void QPainter::drawPixmap (const QRectF & target, const QPixmap & pixmap, const QRectF & source)
Draws the rectangular portion source of the given pixmap into the given target in the paint device.
Note
The pixmap is scaled to fit the rectangle, if both the pixmap and rectangle size disagree.
QRectF target(10.0, 20.0, 80.0, 60.0);
QRectF source(0.0, 0.0, 70.0, 40.0);
QPixmap pixmap(":myPixmap.png");
QPainter(this);
painter.drawPixmap(target, image, source);
If pixmap is a QBitmap it is drawn with the bits that are "set" using the pens color. If backgroundMode is Qt::OpaqueMode, the "unset" bits are drawn using the color of the background brush; if backgroundMode is Qt::TransparentMode, the "unset" bits are transparent. Drawing bitmaps with gradient or texture colors is not supported.
See also
drawImage()
Definition at line 5619 of file qpainter.cpp.
Referenced by _q_paintIntoCache(), QOleDropSource::createCursors(), QPixmap::depth(), QGraphicsEffectSource::draw(), QGraphicsShaderEffect::draw(), QVGPixmapDropShadowFilter::draw(), QPixmapBlurFilter::draw(), QPixmapColorizeFilter::draw(), QPixmapDropShadowFilter::draw(), QGraphicsOpacityEffect::draw(), QTreeViewPrivate::drawAnimatedOperation(), QRenderRule::drawBackgroundImage(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QStyleHelper::drawBorderPixmap(), QMacStylePrivate::drawColorlessButton(), QMacStylePrivate::drawCombobox(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), QItemDelegate::drawDecoration(), QGraphicsScenePrivate::drawItemHelper(), QStyle::drawItemPixmap(), QTextImageHandler::drawObject(), QDeclarativeTextPrivate::drawOutline(), QOpenGLPaintEngine::drawPixmap(), QCommonStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QMacStylePrivate::drawTableHeader(), QPSPrintEngine::drawTiledPixmap(), QOpenGLPaintEngine::drawTiledPixmap(), QSplashScreen::event(), QPicture::exec(), QPainterState::init(), QMacPixmapData::macCreatePixels(), QSvgIconEngine::paint(), QDeclarativeImage::paint(), QDeclarativePaintedItem::paint(), QPixmapIconEngine::paint(), QIconLoaderEngine::paint(), QDeclarativeText::paint(), QGraphicsPixmapItem::paint(), QGtkPainter::paintArrow(), QGtkPainter::paintBox(), QGtkPainter::paintBoxGap(), QDecorationWindows::paintButton(), QDecorationDefault::paintButton(), QGtkPainter::paintCheckbox(), QAlphaWidget::paintEvent(), QCommandLinkButton::paintEvent(), QShapedPixmapWidget::paintEvent(), QBalloonTip::paintEvent(), QAxHostWidget::paintEvent(), QWhatsThat::paintEvent(), QWizard::paintEvent(), QGraphicsView::paintEvent(), QWizardHeader::paintEvent(), QRollEffect::paintEvent(), QMdi::ControlLabel::paintEvent(), QColorPicker::paintEvent(), QColorLuminancePicker::paintEvent(), QGtkPainter::paintExpander(), QGtkPainter::paintExtention(), QGtkPainter::paintFlatBox(), QGtkPainter::paintFocus(), QGtkPainter::paintHandle(), QGtkPainter::paintHline(), QGtkPainter::paintOption(), QGtkPainter::paintResizeGrip(), QGtkPainter::paintShadow(), QGtkPainter::paintSlider(), QGtkPainter::paintVline(), QGraphicsWidget::paintWindowFrame(), QPainterReplayer::process(), QGLPixmapColorizeFilter::processGL(), QGLPixmapConvolutionFilter::processGL(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), qDrawPlainRect(), qt_fill_tile(), qt_mac_constructQIconFromIconRef(), qt_mac_grabDisplayRect(), qt_plastique_draw_gradient(), QWidgetPrivate::render_helper(), QPixmap::scroll(), QWindowsStyle::standardIconImplementation(), QCommonStyle::standardIconImplementation(), QMacStyle::standardIconImplementation(), QCommonStyle::standardPixmap(), and QWindowsStyle::standardPixmap().
 {
 #if defined QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawPixmap(), target=[%.2f,%.2f,%.2f,%.2f], pix=[%d,%d], source=[%.2f,%.2f,%.2f,%.2f]\n",
                r.x(), r.y(), r.width(), r.height(),
                pm.width(), pm.height(),
                sr.x(), sr.y(), sr.width(), sr.height());
 #endif
     Q_D(QPainter);
     if (!d->engine || pm.isNull())
         return;
 #ifndef QT_NO_DEBUG
     qt_painter_thread_test(d->device->devType(), "drawPixmap()", true);
 #endif
     qreal x = r.x();
     qreal y = r.y();
     qreal w = r.width();
     qreal h = r.height();
     qreal sx = sr.x();
     qreal sy = sr.y();
     qreal sw = sr.width();
     qreal sh = sr.height();
     // Sanity-check clipping
     if (sw <= 0)
         sw = pm.width() - sx;
     if (sh <= 0)
         sh = pm.height() - sy;
     if (w < 0)
         w = sw;
     if (h < 0)
         h = sh;
     if (sx < 0) {
         qreal w_ratio = sx * w/sw;
         x -= w_ratio;
         w += w_ratio;
         sw += sx;
         sx = 0;
     }
     if (sy < 0) {
         qreal h_ratio = sy * h/sh;
         y -= h_ratio;
         h += h_ratio;
         sh += sy;
         sy = 0;
     }
     if (sw + sx > pm.width()) {
         qreal delta = sw - (pm.width() - sx);
         qreal w_ratio = delta * w/sw;
         sw -= delta;
         w -= w_ratio;
     }
     if (sh + sy > pm.height()) {
         qreal delta = sh - (pm.height() - sy);
         qreal h_ratio = delta * h/sh;
         sh -= delta;
         h -= h_ratio;
     }
     if (w == 0 || h == 0 || sw <= 0 || sh <= 0)
         return;
     if (d->extended) {
         d->extended->drawPixmap(QRectF(x, y, w, h), pm, QRectF(sx, sy, sw, sh));
         return;
     }
     // Emulate opaque background for bitmaps
     if (d->state->bgMode == Qt::OpaqueMode && pm.isQBitmap())
         fillRect(QRectF(x, y, w, h), d->state->bgBrush.color());
     d->updateState(d->state);
     if ((d->state->matrix.type() > QTransform::TxTranslate
          && !d->engine->hasFeature(QPaintEngine::PixmapTransform))
         || (!d->state->matrix.isAffine() && !d->engine->hasFeature(QPaintEngine::PerspectiveTransform))
         || (d->state->opacity != 1.0 && !d->engine->hasFeature(QPaintEngine::ConstantOpacity))
         || ((sw != w || sh != h) && !d->engine->hasFeature(QPaintEngine::PixmapTransform)))
     {
         save();
         // If there is no rotation involved we have to make sure we use the
         // antialiased and not the aliased coordinate system by rounding the coordinates.
         if (d->state->matrix.type() <= QTransform::TxScale) {
             const QPointF p = roundInDeviceCoordinates(QPointF(x, y), d->state->matrix);
             x = p.x();
             y = p.y();
         }
         if (d->state->matrix.type() <= QTransform::TxTranslate && sw == w && sh == h) {
             sx = qRound(sx);
             sy = qRound(sy);
             sw = qRound(sw);
             sh = qRound(sh);
         }
         translate(x, y);
         scale(w / sw, h / sh);
         setBackgroundMode(Qt::TransparentMode);
         setRenderHint(Antialiasing, renderHints() & SmoothPixmapTransform);
         QBrush brush;
         if (sw == pm.width() && sh == pm.height())
             brush = QBrush(d->state->pen.color(), pm);
         else
             brush = QBrush(d->state->pen.color(), pm.copy(sx, sy, sw, sh));
         setBrush(brush);
         setPen(Qt::NoPen);
         drawRect(QRectF(0, 0, sw, sh));
         restore();
     } else {
         if (!d->engine->hasFeature(QPaintEngine::PixmapTransform)) {
             x += d->state->matrix.dx();
             y += d->state->matrix.dy();
         }
         d->engine->drawPixmap(QRectF(x, y, w, h), pm, QRectF(sx, sy, sw, sh));
     }
 }
drawPixmap() [2/11]
void QPainter::drawPixmap (const QRect & target, const QPixmap & pixmap, const QRect & source) inline
Draws the rectangular portion source of the given pixmap into the given target in the paint device.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note
The pixmap is scaled to fit the rectangle, if both the pixmap and rectangle size disagree.
Definition at line 845 of file qpainter.h.
 {
     drawPixmap(QRectF(targetRect), pixmap, QRectF(sourceRect));
 }
drawPixmap() [3/11]
void QPainter::drawPixmap (int x, int y, int w, int h, const QPixmap & pixmap, int sx, int sy, int sw, int sh) inline
Draws the rectangular portion with the origin ({sx}, {sy}), width sw and height sh, of the given pixmap , at the point ({x}, {y}), with a width of w and a height of h.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If sw or sh are equal to zero the width/height of the pixmap is used and adjusted by the offset sx/sy;
Definition at line 870 of file qpainter.h.
 {
     drawPixmap(QRectF(x, y, w, h), pm, QRectF(sx, sy, sw, sh));
 }
drawPixmap() [4/11]
void QPainter::drawPixmap (int x, int y, const QPixmap & pixmap, int sx, int sy, int sw, int sh) inline
Draws a pixmap at ({x}, {y}) by copying a part of the given pixmap into the paint device.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
({x}, {y}) specifies the top-left point in the paint device that is to be drawn onto. ({sx}, {sy}) specifies the top-left point in pixmap that is to be drawn. The default is (0, 0).
({sw}, {sh}) specifies the size of the pixmap that is to be drawn. The default, (0, 0) (and negative) means all the way to the bottom-right of the pixmap.
Definition at line 876 of file qpainter.h.
 {
     drawPixmap(QRectF(x, y, -1, -1), pm, QRectF(sx, sy, sw, sh));
 }
drawPixmap() [5/11]
void QPainter::drawPixmap (const QPointF & point, const QPixmap & pixmap, const QRectF & source) inline
Draws the rectangular portion source of the given pixmap with its origin at the given point.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 882 of file qpainter.h.
 {
     drawPixmap(QRectF(p.x(), p.y(), -1, -1), pm, sr);
 }
drawPixmap() [6/11]
void QPainter::drawPixmap (const QPoint & point, const QPixmap & pixmap, const QRect & source) inline
Draws the rectangular portion source of the given pixmap with its origin at the given point.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 887 of file qpainter.h.
 {
     drawPixmap(QRectF(p.x(), p.y(), -1, -1), pm, sr);
 }
drawPixmap() [7/11]
void QPainter::drawPixmap (const QPointF & point, const QPixmap & pixmap)
Draws the given pixmap with its origin at the given point.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 5548 of file qpainter.cpp.
 {
 #if defined QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawPixmap(), p=[%.2f,%.2f], pix=[%d,%d]\n",
                p.x(), p.y(),
                pm.width(), pm.height());
 #endif
     Q_D(QPainter);
     if (!d->engine || pm.isNull())
         return;
 #ifndef QT_NO_DEBUG
     qt_painter_thread_test(d->device->devType(), "drawPixmap()", true);
 #endif
     if (d->extended) {
         d->extended->drawPixmap(p, pm);
         return;
     }
     qreal x = p.x();
     qreal y = p.y();
     int w = pm.width();
     int h = pm.height();
     if (w <= 0)
         return;
     // Emulate opaque background for bitmaps
     if (d->state->bgMode == Qt::OpaqueMode && pm.isQBitmap()) {
         fillRect(QRectF(x, y, w, h), d->state->bgBrush.color());
     }
     d->updateState(d->state);
     if ((d->state->matrix.type() > QTransform::TxTranslate
          && !d->engine->hasFeature(QPaintEngine::PixmapTransform))
         || (!d->state->matrix.isAffine() && !d->engine->hasFeature(QPaintEngine::PerspectiveTransform))
         || (d->state->opacity != 1.0 && !d->engine->hasFeature(QPaintEngine::ConstantOpacity)))
     {
         save();
         // If there is no rotation involved we have to make sure we use the
         // antialiased and not the aliased coordinate system by rounding the coordinates.
         if (d->state->matrix.type() <= QTransform::TxScale) {
             const QPointF p = roundInDeviceCoordinates(QPointF(x, y), d->state->matrix);
             x = p.x();
             y = p.y();
         }
         translate(x, y);
         setBackgroundMode(Qt::TransparentMode);
         setRenderHint(Antialiasing, renderHints() & SmoothPixmapTransform);
         QBrush brush(d->state->pen.color(), pm);
         setBrush(brush);
         setPen(Qt::NoPen);
         setBrushOrigin(QPointF(0, 0));
         drawRect(pm.rect());
         restore();
     } else {
         if (!d->engine->hasFeature(QPaintEngine::PixmapTransform)) {
             x += d->state->matrix.dx();
             y += d->state->matrix.dy();
         }
         d->engine->drawPixmap(QRectF(x, y, w, h), pm, QRectF(0, 0, w, h));
     }
 }
drawPixmap() [8/11]
void QPainter::drawPixmap (const QPoint & point, const QPixmap & pixmap) inline
Draws the given pixmap with its origin at the given point.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 850 of file qpainter.h.
 {
     drawPixmap(QPointF(p), pm);
 }
drawPixmap() [9/11]
void QPainter::drawPixmap (int x, int y, const QPixmap & pixmap) inline
Draws the given pixmap at position ({x}, {y}).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 860 of file qpainter.h.
 {
     drawPixmap(QPointF(x, y), pm);
 }
drawPixmap() [10/11]
void QPainter::drawPixmap (const QRect & rectangle, const QPixmap & pixmap) inline
Draws the given pixmap into the given rectangle.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note
The pixmap is scaled to fit the rectangle, if both the pixmap and rectangle size disagree.
Definition at line 855 of file qpainter.h.
 {
     drawPixmap(QRectF(r), pm, QRectF());
 }
drawPixmap() [11/11]
void QPainter::drawPixmap (int x, int y, int width, int height, const QPixmap & pixmap) inline
Draws the pixmap into the rectangle at position ({x}, {y}) with the given width and height.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 865 of file qpainter.h.
 {
     drawPixmap(QRectF(x, y, w, h), pm, QRectF());
 }
drawPixmapFragments() [1/2]
void QPainter::drawPixmapFragments (const PixmapFragment * fragments, int fragmentCount, const QPixmap & pixmap, PixmapFragmentHints hints = 0)
This function is used to draw pixmap, or a sub-rectangle of pixmap, at multiple positions with different scale, rotation and opacity.
Since
4.7
fragments is an array of fragmentCount elements specifying the parameters used to draw each pixmap fragment. The hints parameter can be used to pass in drawing hints.
This function is potentially faster than multiple calls to drawPixmap(), since the backend can optimize state changes.
See also
QPainter::PixmapFragment, QPainter::PixmapFragmentHint
Definition at line 9697 of file qpainter.cpp.
Referenced by QDeclarativeParticlesPainter::paint(), and qDrawBorderPixmap().
 {
     Q_D(QPainter);
     if (!d->engine || pixmap.isNull())
         return;
 #ifndef QT_NO_DEBUG
     for (int i = 0; i < fragmentCount; ++i) {
         QRectF sourceRect(fragments[i].sourceLeft, fragments[i].sourceTop,
                           fragments[i].width, fragments[i].height);
         if (!(QRectF(pixmap.rect()).contains(sourceRect)))
             qWarning("QPainter::drawPixmapFragments - the source rect is not contained by the pixmap's rectangle");
     }
 #endif
     if (d->engine->isExtended()) {
         d->extended->drawPixmapFragments(fragments, fragmentCount, pixmap, hints);
     } else {
         qreal oldOpacity = opacity();
         QTransform oldTransform = transform();
         for (int i = 0; i < fragmentCount; ++i) {
             QTransform transform = oldTransform;
             qreal xOffset = 0;
             qreal yOffset = 0;
             if (fragments[i].rotation == 0) {
                 xOffset = fragments[i].x;
                 yOffset = fragments[i].y;
             } else {
                 transform.translate(fragments[i].x, fragments[i].y);
                 transform.rotate(fragments[i].rotation);
             }
             setOpacity(oldOpacity * fragments[i].opacity);
             setTransform(transform);
             qreal w = fragments[i].scaleX * fragments[i].width;
             qreal h = fragments[i].scaleY * fragments[i].height;
             QRectF sourceRect(fragments[i].sourceLeft, fragments[i].sourceTop,
                               fragments[i].width, fragments[i].height);
             drawPixmap(QRectF(qreal(-0.5) * w + xOffset, qreal(-0.5) * h + yOffset, w, h), pixmap, sourceRect);
         }
         setOpacity(oldOpacity);
         setTransform(oldTransform);
     }
 }
drawPixmapFragments() [2/2]
void QPainter::drawPixmapFragments (const QRectF * targetRects, const QRectF * sourceRects, int fragmentCount, const QPixmap & pixmap, PixmapFragmentHints hints = 0)
This function is used to draw the same pixmap with multiple target and source rectangles specified by targetRects.
Since
4.8
If sourceRects is 0, the whole pixmap will be rendered at each of the target rectangles. The hints parameter can be used to pass in drawing hints.
This function is potentially faster than multiple calls to drawPixmap(), since the backend can optimize state changes.
See also
QPainter::PixmapFragmentHint
Definition at line 9763 of file qpainter.cpp.
 {
     Q_D(QPainter);
     if (!d->engine || pixmap.isNull())
         return;
 #ifndef QT_NO_DEBUG
     if (sourceRects) {
         for (int i = 0; i < fragmentCount; ++i) {
             QRectF sourceRect = sourceRects[i];
             if (!(QRectF(pixmap.rect()).contains(sourceRect)))
                 qWarning("QPainter::drawPixmapFragments - the source rect is not contained by the pixmap's rectangle");
         }
     }
 #endif
     if (d->engine->isExtended()) {
         d->extended->drawPixmapFragments(targetRects, sourceRects, fragmentCount, pixmap, hints);
     } else {
         if (sourceRects) {
             for (int i = 0; i < fragmentCount; ++i)
                 drawPixmap(targetRects[i], pixmap, sourceRects[i]);
         } else {
             QRectF sourceRect = pixmap.rect();
             for (int i = 0; i < fragmentCount; ++i)
                 drawPixmap(targetRects[i], pixmap, sourceRect);
         }
     }
 }
drawPoint() [1/3]
void QPainter::drawPoint (const QPointF & position) inline
Draws a single point at the given position using the current pen's color.
See also
{Coordinate System}
Definition at line 676 of file qpainter.h.
Referenced by QPlastiqueStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QWindowsCEStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QPicture::exec(), QWhatsThat::paintEvent(), QWizardHeader::paintEvent(), qDrawPlainRect(), and qt_cleanlooks_draw_mdibutton().
 {
     drawPoints(&p, 1);
 }
drawPoint() [2/3]
void QPainter::drawPoint (const QPoint & position) inline
Draws a single point at the given position using the current pen's color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 687 of file qpainter.h.
 {
     drawPoints(&p, 1);
 }
drawPoint() [3/3]
void QPainter::drawPoint (int x, int y) inline
Draws a single point at position (x, y).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 681 of file qpainter.h.
 {
     QPoint p(x, y);
     drawPoints(&p, 1);
 }
drawPoints() [1/4]
void QPainter::drawPoints (const QPointF * points, int pointCount)
Draws the first pointCount points in the array points using the current pen's color.
See also
{Coordinate System}
Definition at line 3816 of file qpainter.cpp.
Referenced by QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QPainterReplayer::process(), qt_cleanlooks_draw_mdibutton(), qt_plastique_draw_frame(), qt_plastique_draw_mdibutton(), and qt_plastique_drawFrame().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawPoints(), count=%d\n", pointCount);
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::drawPoints: Painter not active");
         return;
     }
     if (pointCount <= 0)
         return;
     if (d->extended) {
         d->extended->drawPoints(points, pointCount);
         return;
     }
     d->updateState(d->state);
     if (!d->state->emulationSpecifier) {
         d->engine->drawPoints(points, pointCount);
         return;
     }
     if (d->state->emulationSpecifier == QPaintEngine::PrimitiveTransform
         && d->state->matrix.type() == QTransform::TxTranslate) {
         // ### use drawPoints function
         for (int i=0; i<pointCount; ++i) {
             QPointF pt(points[i].x() + d->state->matrix.dx(),
                        points[i].y() + d->state->matrix.dy());
             d->engine->drawPoints(&pt, 1);
         }
     } else {
         QPen pen = d->state->pen;
         bool flat_pen = pen.capStyle() == Qt::FlatCap;
         if (flat_pen) {
             save();
             pen.setCapStyle(Qt::SquareCap);
             setPen(pen);
         }
         QPainterPath path;
         for (int i=0; i<pointCount; ++i) {
             path.moveTo(points[i].x(), points[i].y());
             path.lineTo(points[i].x() + 0.0001, points[i].y());
         }
         d->draw_helper(path, QPainterPrivate::StrokeDraw);
         if (flat_pen)
             restore();
     }
 }
drawPoints() [2/4]
void QPainter::drawPoints (const QPolygonF & points) inline
Draws the points in the vector points.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 692 of file qpainter.h.
 {
     drawPoints(points.constData(), points.size());
 }
drawPoints() [3/4]
void QPainter::drawPoints (const QPoint * points, int pointCount)
Draws the first pointCount points in the array points using the current pen's color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 3881 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawPoints(), count=%d\n", pointCount);
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::drawPoints: Painter not active");
         return;
     }
     if (pointCount <= 0)
         return;
     if (d->extended) {
         d->extended->drawPoints(points, pointCount);
         return;
     }
     d->updateState(d->state);
     if (!d->state->emulationSpecifier) {
         d->engine->drawPoints(points, pointCount);
         return;
     }
     if (d->state->emulationSpecifier == QPaintEngine::PrimitiveTransform
         && d->state->matrix.type() == QTransform::TxTranslate) {
         // ### use drawPoints function
         for (int i=0; i<pointCount; ++i) {
             QPointF pt(points[i].x() + d->state->matrix.dx(),
                        points[i].y() + d->state->matrix.dy());
             d->engine->drawPoints(&pt, 1);
         }
     } else {
         QPen pen = d->state->pen;
         bool flat_pen = (pen.capStyle() == Qt::FlatCap);
         if (flat_pen) {
             save();
             pen.setCapStyle(Qt::SquareCap);
             setPen(pen);
         }
         QPainterPath path;
         for (int i=0; i<pointCount; ++i) {
             path.moveTo(points[i].x(), points[i].y());
             path.lineTo(points[i].x() + 0.0001, points[i].y());
         }
         d->draw_helper(path, QPainterPrivate::StrokeDraw);
         if (flat_pen)
             restore();
     }
 }
drawPoints() [4/4]
void QPainter::drawPoints (const QPolygon & points) inline
Draws the points in the vector points.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 697 of file qpainter.h.
 {
     drawPoints(points.constData(), points.size());
 }
drawPolygon() [1/4]
void QPainter::drawPolygon (const QPointF * points, int pointCount, Qt::FillRule fillRule = Qt::OddEvenFill)
Draws the polygon defined by the first pointCount points in the array points using the current pen and brush.
static const QPointF points[4] = {
    QPointF(10.0, 80.0),
    QPointF(20.0, 10.0),
    QPointF(80.0, 30.0),
    QPointF(90.0, 70.0)
};
QPainter painter(this);
painter.drawPolygon(points, 4);
The first point is implicitly connected to the last point, and the polygon is filled with the current brush().
If fillRule is Qt::WindingFill, the polygon is filled using the winding fill algorithm. If fillRule is Qt::OddEvenFill, the polygon is filled using the odd-even fill algorithm. See Qt::FillRule for a more detailed description of these fill rules.
See also
drawConvexPolygon(), drawPolyline(), {Coordinate System}
Definition at line 5205 of file qpainter.cpp.
Referenced by QSvgPolygon::draw(), QSvgPolyline::draw(), QCommonStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QCommonStyle::drawControl(), QMotifStyle::drawControl(), QCommonStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QLCDNumberPrivate::drawSegment(), QPicture::exec(), QX11PaintEnginePrivate::fillPolygon_dev(), QGraphicsPolygonItem::paint(), QColorLuminancePicker::paintEvent(), QPainterReplayer::process(), and qDrawPlainRect().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawPolygon(), count=%d\n", pointCount);
 #endif
     Q_D(QPainter);
     if (!d->engine || pointCount < 2)
         return;
     if (d->extended) {
         d->extended->drawPolygon(points, pointCount, QPaintEngine::PolygonDrawMode(fillRule));
         return;
     }
     d->updateState(d->state);
     uint emulationSpecifier = d->state->emulationSpecifier;
     if (emulationSpecifier) {
         QPainterPath polygonPath(points[0]);
         for (int i=1; i<pointCount; ++i)
             polygonPath.lineTo(points[i]);
         polygonPath.closeSubpath();
         polygonPath.setFillRule(fillRule);
         d->draw_helper(polygonPath);
         return;
     }
     d->engine->drawPolygon(points, pointCount, QPaintEngine::PolygonDrawMode(fillRule));
 }
drawPolygon() [2/4]
void QPainter::drawPolygon (const QPolygonF & points, Qt::FillRule fillRule = Qt::OddEvenFill) inline
Draws the polygon defined by the given points using the fill rule fillRule.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 630 of file qpainter.h.
 {
     drawPolygon(polygon.constData(), polygon.size(), fillRule);
 }
drawPolygon() [3/4]
void QPainter::drawPolygon (const QPoint * points, int pointCount, Qt::FillRule fillRule = Qt::OddEvenFill)
Draws the polygon defined by the first pointCount points in the array points.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 5247 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawPolygon(), count=%d\n", pointCount);
 #endif
     Q_D(QPainter);
     if (!d->engine || pointCount < 2)
         return;
     if (d->extended) {
         d->extended->drawPolygon(points, pointCount, QPaintEngine::PolygonDrawMode(fillRule));
         return;
     }
     d->updateState(d->state);
     uint emulationSpecifier = d->state->emulationSpecifier;
     if (emulationSpecifier) {
         QPainterPath polygonPath(points[0]);
         for (int i=1; i<pointCount; ++i)
             polygonPath.lineTo(points[i]);
         polygonPath.closeSubpath();
         polygonPath.setFillRule(fillRule);
         d->draw_helper(polygonPath);
         return;
     }
     d->engine->drawPolygon(points, pointCount, QPaintEngine::PolygonDrawMode(fillRule));
 }
drawPolygon() [4/4]
void QPainter::drawPolygon (const QPolygon & points, Qt::FillRule fillRule = Qt::OddEvenFill) inline
Draws the polygon defined by the given points using the fill rule fillRule.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 635 of file qpainter.h.
 {
     drawPolygon(polygon.constData(), polygon.size(), fillRule);
 }
drawPolyline() [1/4]
void QPainter::drawPolyline (const QPointF * points, int pointCount)
Draws the polyline defined by the first pointCount points in points using the current pen.
Note that unlike the drawPolygon() function the last point is not connected to the first, neither is the polyline filled.
static const QPointF points[3] = {
    QPointF(10.0, 80.0),
    QPointF(20.0, 10.0),
    QPointF(80.0, 30.0),
};
QPainter painter(this);
painter.drawPolyline(points, 3);
See also
drawLines(), drawPolygon(), {Coordinate System}
Definition at line 5055 of file qpainter.cpp.
Referenced by QSvgPolyline::draw(), QCommonStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QWindowsCEStylePrivate::drawWinCEShades(), QWindowsCEStylePrivate::drawWinCEShadesSunken(), QWindowsCEStylePrivate::drawWinShades(), QPicture::exec(), QPainterReplayer::process(), qDrawShadeLine(), and qDrawWinShades().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawPolyline(), count=%d\n", pointCount);
 #endif
     Q_D(QPainter);
     if (!d->engine || pointCount < 2)
         return;
     if (d->extended) {
         d->extended->drawPolygon(points, pointCount, QPaintEngine::PolylineMode);
         return;
     }
     d->updateState(d->state);
     uint lineEmulation = line_emulation(d->state->emulationSpecifier);
     if (lineEmulation) {
         // ###
 //         if (lineEmulation == QPaintEngine::PrimitiveTransform
 //             && d->state->matrix.type() == QTransform::TxTranslate) {
 //         } else {
         QPainterPath polylinePath(points[0]);
         for (int i=1; i<pointCount; ++i)
             polylinePath.lineTo(points[i]);
         d->draw_helper(polylinePath, QPainterPrivate::StrokeDraw);
 //         }
     } else {
         d->engine->drawPolygon(points, pointCount, QPaintEngine::PolylineMode);
     }
 }
drawPolyline() [2/4]
void QPainter::drawPolyline (const QPolygonF & points) inline
Draws the polyline defined by the given points using the current pen.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 620 of file qpainter.h.
 {
     drawPolyline(polyline.constData(), polyline.size());
 }
drawPolyline() [3/4]
void QPainter::drawPolyline (const QPoint * points, int pointCount)
Draws the polyline defined by the first pointCount points in points using the current pen.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 5099 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawPolyline(), count=%d\n", pointCount);
 #endif
     Q_D(QPainter);
     if (!d->engine || pointCount < 2)
         return;
     if (d->extended) {
         d->extended->drawPolygon(points, pointCount, QPaintEngine::PolylineMode);
         return;
     }
     d->updateState(d->state);
     uint lineEmulation = line_emulation(d->state->emulationSpecifier);
     if (lineEmulation) {
         // ###
 //         if (lineEmulation == QPaintEngine::PrimitiveTransform
 //             && d->state->matrix.type() == QTransform::TxTranslate) {
 //         } else {
         QPainterPath polylinePath(points[0]);
         for (int i=1; i<pointCount; ++i)
             polylinePath.lineTo(points[i]);
         d->draw_helper(polylinePath, QPainterPrivate::StrokeDraw);
 //         }
     } else {
         d->engine->drawPolygon(points, pointCount, QPaintEngine::PolylineMode);
     }
 }
drawPolyline() [4/4]
void QPainter::drawPolyline (const QPolygon & points) inline
Draws the polyline defined by the given points using the current pen.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 625 of file qpainter.h.
 {
     drawPolyline(polyline.constData(), polyline.size());
 }
drawRect() [1/3]
void QPainter::drawRect (const QRectF & rectangle) inline
Draws the current rectangle with the current pen and brush.
A filled rectangle has a size of {rectangle}.size(). A stroked rectangle has a size of {rectangle}.size() plus the pen width.
QRectF rectangle(10.0, 20.0, 80.0, 60.0);
QPainter painter(this);
painter.drawRect(rectangle);
See also
drawRects(), drawPolygon(), {Coordinate System}
Definition at line 650 of file qpainter.h.
Referenced by QFontEngineBox::boundingBox(), QmlJSDebugger::ToolBarColorBox::createDragPixmap(), QSvgRect::draw(), QGraphicsScenePrivate::draw(), QTextDocumentLayoutPrivate::drawBorder(), QPaintEnginePrivate::drawBoxTextItem(), QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QItemDelegate::drawDisplay(), drawImage(), drawPixmap(), QPaintEngine::drawPoints(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QDeclarativeRectangle::drawRect(), drawRoundedRect(), QWindowsMobileStylePrivate::drawScrollbarGrip(), drawTiledPixmap(), QPicture::exec(), fillRect(), QDeclarativeRectangle::generateBorderedRect(), QColorWell::mouseMoveEvent(), QColorShowLabel::mouseMoveEvent(), QFontFamilyDelegate::paint(), QGraphicsRectItem::paint(), QGraphicsItemGroup::paint(), QPagePreview::paintEvent(), QWhatsThat::paintEvent(), qDrawEdge(), qDrawPlainRect(), qDrawShadeRect(), and qt_graphicsItem_highlightSelected().
 {
     drawRects(&rect, 1);
 }
drawRect() [2/3]
void QPainter::drawRect (int x, int y, int width, int height) inline
Draws a rectangle with upper left corner at ({x}, {y}) and with the given width and height.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 655 of file qpainter.h.
 {
     QRect r(x, y, w, h);
     drawRects(&r, 1);
 }
drawRect() [3/3]
void QPainter::drawRect (const QRect & rectangle) inline
Draws the current rectangle with the current pen and brush.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 661 of file qpainter.h.
 {
     drawRects(&r, 1);
 }
drawRects() [1/4]
void QPainter::drawRects (const QRectF * rectangles, int rectCount)
Draws the first rectCount of the given rectangles using the current pen and brush.
See also
drawRect()
Definition at line 3641 of file qpainter.cpp.
Referenced by QCleanlooksStyle::drawPrimitive(), QPainterReplayer::process(), and QWidgetPrivate::setWindowOpacity_sys().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawRects(), count=%d\n", rectCount);
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::drawRects: Painter not active");
         return;
     }
     if (rectCount <= 0)
         return;
     if (d->extended) {
         d->extended->drawRects(rects, rectCount);
         return;
     }
     d->updateState(d->state);
     if (!d->state->emulationSpecifier) {
         d->engine->drawRects(rects, rectCount);
         return;
     }
     if (d->state->emulationSpecifier == QPaintEngine::PrimitiveTransform
         && d->state->matrix.type() == QTransform::TxTranslate) {
         for (int i=0; i<rectCount; ++i) {
             QRectF r(rects[i].x() + d->state->matrix.dx(),
                      rects[i].y() + d->state->matrix.dy(),
                      rects[i].width(),
                      rects[i].height());
             d->engine->drawRects(&r, 1);
         }
     } else {
         if (d->state->brushNeedsResolving() || d->state->penNeedsResolving()) {
             for (int i=0; i<rectCount; ++i) {
                 QPainterPath rectPath;
                 rectPath.addRect(rects[i]);
                 d->draw_helper(rectPath, QPainterPrivate::StrokeAndFillDraw);
             }
         } else {
             QPainterPath rectPath;
             for (int i=0; i<rectCount; ++i)
                 rectPath.addRect(rects[i]);
             d->draw_helper(rectPath, QPainterPrivate::StrokeAndFillDraw);
         }
     }
 }
drawRects() [2/4]
void QPainter::drawRects (const QVector< QRectF > & rectangles) inline
Draws the given rectangles using the current pen and brush.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 666 of file qpainter.h.
 {
     drawRects(rects.constData(), rects.size());
 }
drawRects() [3/4]
void QPainter::drawRects (const QRect * rects, int rectCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the first rectCount of the given rectangles using the current pen and brush.
Definition at line 3701 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawRects(), count=%d\n", rectCount);
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::drawRects: Painter not active");
         return;
     }
     if (rectCount <= 0)
         return;
     if (d->extended) {
         d->extended->drawRects(rects, rectCount);
         return;
     }
     d->updateState(d->state);
     if (!d->state->emulationSpecifier) {
         d->engine->drawRects(rects, rectCount);
         return;
     }
     if (d->state->emulationSpecifier == QPaintEngine::PrimitiveTransform
         && d->state->matrix.type() == QTransform::TxTranslate) {
         for (int i=0; i<rectCount; ++i) {
             QRectF r(rects[i].x() + d->state->matrix.dx(),
                      rects[i].y() + d->state->matrix.dy(),
                      rects[i].width(),
                      rects[i].height());
             d->engine->drawRects(&r, 1);
         }
     } else {
         if (d->state->brushNeedsResolving() || d->state->penNeedsResolving()) {
             for (int i=0; i<rectCount; ++i) {
                 QPainterPath rectPath;
                 rectPath.addRect(rects[i]);
                 d->draw_helper(rectPath, QPainterPrivate::StrokeAndFillDraw);
             }
         } else {
             QPainterPath rectPath;
             for (int i=0; i<rectCount; ++i)
                 rectPath.addRect(rects[i]);
             d->draw_helper(rectPath, QPainterPrivate::StrokeAndFillDraw);
         }
     }
 }
drawRects() [4/4]
void QPainter::drawRects (const QVector< QRect > & rectangles) inline
Draws the given rectangles using the current pen and brush.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 671 of file qpainter.h.
 {
     drawRects(rects.constData(), rects.size());
 }
drawRoundedRect() [1/3]
void QPainter::drawRoundedRect (const QRectF & rect, qreal xRadius, qreal yRadius, Qt::SizeMode mode = Qt::AbsoluteSize)
Draws the given rectangle rect with rounded corners.
Since
4.4
The xRadius and yRadius arguments specify the radii of the ellipses defining the corners of the rounded rectangle. When mode is Qt::RelativeSize, xRadius and yRadius are specified in percentage of half the rectangle's width and height respectively, and should be in the range 0.0 to 100.0.
A filled rectangle has a size of rect.size(). A stroked rectangle has a size of rect.size() plus the pen width.
QRectF rectangle(10.0, 20.0, 80.0, 60.0);
QPainter painter(this);
painter.drawRoundedRect(rectangle, 20.0, 15.0);
See also
drawRect(), QPen
Definition at line 4348 of file qpainter.cpp.
Referenced by QSvgRect::draw(), QDeclarativeRectangle::drawRect(), drawRoundRect(), QPicture::exec(), and QDeclarativeRectangle::generateRoundedRect().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawRoundedRect(), [%.2f,%.2f,%.2f,%.2f]\n", rect.x(), rect.y(), rect.width(), rect.height());
 #endif
     Q_D(QPainter);
     if (!d->engine)
         return;
     if (xRadius <= 0 || yRadius <= 0) {             // draw normal rectangle
         drawRect(rect);
         return;
     }
     if (d->extended) {
         d->extended->drawRoundedRect(rect, xRadius, yRadius, mode);
         return;
     }
     QPainterPath path;
     path.addRoundedRect(rect, xRadius, yRadius, mode);
     drawPath(path);
 }
drawRoundedRect() [2/3]
void QPainter::drawRoundedRect (int x, int y, int w, int h, qreal xRadius, qreal yRadius, Qt::SizeMode mode = Qt::AbsoluteSize) inline
Definition at line 712 of file qpainter.h.
 {
     drawRoundedRect(QRectF(x, y, w, h), xRadius, yRadius, mode);
 }
drawRoundedRect() [3/3]
void QPainter::drawRoundedRect (const QRect & rect, qreal xRadius, qreal yRadius, Qt::SizeMode mode = Qt::AbsoluteSize) inline
Definition at line 718 of file qpainter.h.
 {
     drawRoundedRect(QRectF(rect), xRadius, yRadius, mode);
 }
drawRoundRect() [1/3]
void QPainter::drawRoundRect (const QRectF & r, int xRnd = 25, int yRnd = 25)
Draws a rectangle r with rounded corners.
The xRnd and yRnd arguments specify how rounded the corners should be. 0 is angled corners, 99 is maximum roundedness.
A filled rectangle has a size of r.size(). A stroked rectangle has a size of r.size() plus the pen width.
See also
drawRoundedRect()
Definition at line 4414 of file qpainter.cpp.
 {
     drawRoundedRect(r, xRnd, yRnd, Qt::RelativeSize);
 }
drawRoundRect() [2/3]
void QPainter::drawRoundRect (int x, int y, int w, int h, int xRnd = 25, int yRnd = 25) inline
Draws the rectangle x, y, w, h with rounded corners.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 702 of file qpainter.h.
 {
     drawRoundRect(QRectF(x, y, w, h), xRnd, yRnd);
 }
drawRoundRect() [3/3]
void QPainter::drawRoundRect (const QRect & r, int xRnd = 25, int yRnd = 25) inline
Draws the rectangle r with rounded corners.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 707 of file qpainter.h.
 {
     drawRoundRect(QRectF(rect), xRnd, yRnd);
 }
drawStaticText() [1/3]
void QPainter::drawStaticText (const QPointF & topLeftPosition, const QStaticText & staticText)
Draws the given staticText at the given topLeftPosition.
Since
4.7
The text will be drawn using the font and the transformation set on the painter. If the font and/or transformation set on the painter are different from the ones used to initialize the layout of the QStaticText, then the layout will have to be recalculated. Use QStaticText::prepare() to initialize staticText with the font and transformation with which it will later be drawn.
If topLeftPosition is not the same as when staticText was initialized, or when it was last drawn, then there will be a slight overhead when translating the text to its new position.
Note
If the painter's transformation is not affine, then staticText will be drawn using regular calls to drawText(), losing any potential for performance improvement.
The y-position is used as the top of the font.
See also
QStaticText
Definition at line 6260 of file qpainter.cpp.
 {
     Q_D(QPainter);
     if (!d->engine || staticText.text().isEmpty() || pen().style() == Qt::NoPen)
         return;
     QStaticTextPrivate *staticText_d =
             const_cast<QStaticTextPrivate *>(QStaticTextPrivate::get(&staticText));
     if (font() != staticText_d->font) {
         staticText_d->font = font();
         staticText_d->needsRelayout = true;
     }
     // If we don't have an extended paint engine, or if the painter is projected,
     // we go through standard code path
     if (d->extended == 0 || !d->state->matrix.isAffine()) {
         staticText_d->paintText(topLeftPosition, this);
         return;
     }
     bool supportsTransformations = d->extended->supportsTransformations(staticText_d->font.pixelSize(),
                                                                         d->state->matrix);
     if (supportsTransformations && !staticText_d->untransformedCoordinates) {
         staticText_d->untransformedCoordinates = true;
         staticText_d->needsRelayout = true;
     } else if (!supportsTransformations && staticText_d->untransformedCoordinates) {
         staticText_d->untransformedCoordinates = false;
         staticText_d->needsRelayout = true;
     }
     // Don't recalculate entire layout because of translation, rather add the dx and dy
     // into the position to move each text item the correct distance.
     QPointF transformedPosition = topLeftPosition;
     if (!staticText_d->untransformedCoordinates)
         transformedPosition = transformedPosition * d->state->matrix;
     QTransform oldMatrix;
     // The translation has been applied to transformedPosition. Remove translation
     // component from matrix.
     if (d->state->matrix.isTranslating() && !staticText_d->untransformedCoordinates) {
         qreal m11 = d->state->matrix.m11();
         qreal m12 = d->state->matrix.m12();
         qreal m13 = d->state->matrix.m13();
         qreal m21 = d->state->matrix.m21();
         qreal m22 = d->state->matrix.m22();
         qreal m23 = d->state->matrix.m23();
         qreal m33 = d->state->matrix.m33();
         oldMatrix = d->state->matrix;
         d->state->matrix.setMatrix(m11, m12, m13,
                                    m21, m22, m23,
                                    0.0, 0.0, m33);
     }
     // If the transform is not identical to the text transform,
     // we have to relayout the text (for other transformations than plain translation)
     bool staticTextNeedsReinit = staticText_d->needsRelayout;
     if (!staticText_d->untransformedCoordinates && staticText_d->matrix != d->state->matrix) {
         staticText_d->matrix = d->state->matrix;
         staticTextNeedsReinit = true;
     }
     // Recreate the layout of the static text because the matrix or font has changed
     if (staticTextNeedsReinit)
         staticText_d->init();
     if (transformedPosition != staticText_d->position) { // Translate to actual position
         QFixed fx = QFixed::fromReal(transformedPosition.x());
         QFixed fy = QFixed::fromReal(transformedPosition.y());
         QFixed oldX = QFixed::fromReal(staticText_d->position.x());
         QFixed oldY = QFixed::fromReal(staticText_d->position.y());
         for (int item=0; item<staticText_d->itemCount;++item) {
             QStaticTextItem *textItem = staticText_d->items + item;
             for (int i=0; i<textItem->numGlyphs; ++i) {
                 textItem->glyphPositions[i].x += fx - oldX;
                 textItem->glyphPositions[i].y += fy - oldY;
             }
             textItem->userDataNeedsUpdate = true;
         }
         staticText_d->position = transformedPosition;
     }
     QPen oldPen = d->state->pen;
     QColor currentColor = oldPen.color();
     for (int i=0; i<staticText_d->itemCount; ++i) {
         QStaticTextItem *item = staticText_d->items + i;
         if (item->color.isValid() && currentColor != item->color) {
             setPen(item->color);
             currentColor = item->color;
         }
         d->extended->drawStaticTextItem(item);
         qt_draw_decoration_for_glyphs(this, item->glyphs, item->glyphPositions,
                                       item->numGlyphs, item->fontEngine(), staticText_d->font,
                                       QTextCharFormat());
     }
     if (currentColor != oldPen.color())
         setPen(oldPen);
     if (!staticText_d->untransformedCoordinates && oldMatrix.isTranslating())
         d->state->matrix = oldMatrix;
 }
drawStaticText() [2/3]
void QPainter::drawStaticText (const QPoint & topLeftPosition, const QStaticText & staticText) inline
Draws the staticText at the topLeftPosition.
Since
4.7 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note
The y-position is used as the top of the font.
Definition at line 940 of file qpainter.h.
 {
     drawStaticText(QPointF(p), staticText);
 }
drawStaticText() [3/3]
void QPainter::drawStaticText (int left, int top, const QStaticText & staticText) inline
Draws the staticText at coordinates left and top.
Since
4.7 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note
The y-position is used as the top of the font.
Definition at line 945 of file qpainter.h.
 {
     drawStaticText(QPointF(x, y), staticText);
 }
drawText() [1/8]
void QPainter::drawText (const QPointF & position, const QString & text)
Draws the given text with the currently defined text direction, beginning at the given position.
This function does not handle the newline character (
), as it cannot break text into multiple lines, and it cannot display the newline character. Use the QPainter::drawText() overload that takes a rectangle instead if you want to draw multiple lines of text with the newline character, or if you want the text to be wrapped.
By default, QPainter draws text anti-aliased.
Note
The y-position is used as the baseline of the font.
Definition at line 6231 of file qpainter.cpp.
Referenced by boundingRect(), QDragManager::drag(), QTextLine::draw(), QCommonStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QStyleSheetStyle::drawComplexControl(), QSplashScreen::drawContents(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), QWindowsCEStyle::drawItemText(), QCleanlooksStyle::drawItemText(), QStyle::drawItemText(), QDeclarativeTextPrivate::drawTextLayout(), QVistaHelper::drawTitleText(), QPicture::exec(), QScriptEdit::extraAreaPaintEvent(), QDecorationWindows::paint(), QDecorationDefault::paint(), QFontFamilyDelegate::paint(), QStatusBar::paintEvent(), QPagePreview::paintEvent(), QWhatsThat::paintEvent(), QLineEdit::paintEvent(), printPage(), QPainterReplayer::process(), qDrawPlainRect(), qt_mac_read_fontsmoothing_settings(), QWidget::update(), and QCommonStylePrivate::viewItemDrawText().
 {
     drawText(p, str, 0, 0);
 }
drawText() [2/8]
void QPainter::drawText (const QPoint & position, const QString & text) inline
Draws the given text with the currently defined text direction, beginning at the given position.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
By default, QPainter draws text anti-aliased.
Note
The y-position is used as the baseline of the font.
Definition at line 955 of file qpainter.h.
 {
     drawText(QPointF(p), s);
 }
drawText() [3/8]
void QPainter::drawText (int x, int y, const QString & text) inline
Draws the given text at position ({x}, {y}), using the painter's currently defined text direction.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
By default, QPainter draws text anti-aliased.
Note
The y-position is used as the baseline of the font.
Definition at line 965 of file qpainter.h.
 {
     drawText(QPointF(x, y), s);
 }
drawText() [4/8]
void QPainter::drawText (const QPointF & p, const QString & str, int tf, int justificationPadding)
Warning
This function is not part of the public interface.
Definition at line 6368 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawText(), pos=[%.2f,%.2f], str='%s'\n", p.x(), p.y(), str.toLatin1().constData());
 #endif
     Q_D(QPainter);
     if (!d->engine || str.isEmpty() || pen().style() == Qt::NoPen)
         return;
     if (tf & Qt::TextBypassShaping) {
         // Skip harfbuzz complex shaping, shape using glyph advances only
         int len = str.length();
         int numGlyphs = len;
         QVarLengthGlyphLayoutArray glyphs(len);
         QFontEngine *fontEngine = d->state->font.d->engineForScript(QUnicodeTables::Common);
         if (!fontEngine->stringToCMap(str.data(), len, &glyphs, &numGlyphs, 0)) {
             glyphs.resize(numGlyphs);
             if (!fontEngine->stringToCMap(str.data(), len, &glyphs, &numGlyphs, 0))
                 Q_ASSERT_X(false, Q_FUNC_INFO, "stringToCMap shouldn't fail twice");
         }
         QTextItemInt gf(glyphs, &d->state->font, str.data(), len, fontEngine);
         drawTextItem(p, gf);
         return;
     }
     QStackTextEngine engine(str, d->state->font);
     engine.option.setTextDirection(d->state->layoutDirection);
     if (tf & (Qt::TextForceLeftToRight|Qt::TextForceRightToLeft)) {
         engine.ignoreBidi = true;
         engine.option.setTextDirection((tf & Qt::TextForceLeftToRight) ? Qt::LeftToRight : Qt::RightToLeft);
     }
     engine.itemize();
     QScriptLine line;
     line.length = str.length();
     engine.shapeLine(line);
     int nItems = engine.layoutData->items.size();
     QVarLengthArray<int> visualOrder(nItems);
     QVarLengthArray<uchar> levels(nItems);
     for (int i = 0; i < nItems; ++i)
         levels[i] = engine.layoutData->items[i].analysis.bidiLevel;
     QTextEngine::bidiReorder(nItems, levels.data(), visualOrder.data());
     if (justificationPadding > 0) {
         engine.option.setAlignment(Qt::AlignJustify);
         engine.forceJustification = true;
         // this works because justify() is only interested in the difference between width and textWidth
         line.width = justificationPadding;
         engine.justify(line);
     }
     QFixed x = QFixed::fromReal(p.x());
     for (int i = 0; i < nItems; ++i) {
         int item = visualOrder[i];
         const QScriptItem &si = engine.layoutData->items.at(item);
         if (si.analysis.flags >= QScriptAnalysis::TabOrObject) {
             x += si.width;
             continue;
         }
         QFont f = engine.font(si);
         QTextItemInt gf(si, &f);
         gf.glyphs = engine.shapedGlyphs(&si);
         gf.chars = engine.layoutData->string.unicode() + si.position;
         gf.num_chars = engine.length(item);
         if (engine.forceJustification) {
             for (int j=0; j<gf.glyphs.numGlyphs; ++j)
                 gf.width += gf.glyphs.effectiveAdvance(j);
         } else {
             gf.width = si.width;
         }
         gf.logClusters = engine.logClusters(&si);
         drawTextItem(QPointF(x.toReal(), p.y()), gf);
         x += gf.width;
     }
 }
drawText() [5/8]
void QPainter::drawText (const QRectF & rectangle, int flags, const QString & text, QRectF * boundingRect = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the given text within the provided rectangle.
QPainter painter(this);
painter.drawText(rect, Qt::AlignCenter, tr("Qt by\nNokia"));
The boundingRect (if not null) is set to the what the bounding rectangle should be in order to enclose the whole text. The flags argument is a bitwise OR of the following flags:
Qt::AlignLeft
Qt::AlignRight
Qt::AlignHCenter
Qt::AlignJustify
Qt::AlignTop
Qt::AlignBottom
Qt::AlignVCenter
Qt::AlignCenter
Qt::TextDontClip
Qt::TextSingleLine
Qt::TextExpandTabs
Qt::TextShowMnemonic
Qt::TextWordWrap
Qt::TextIncludeTrailingSpaces
See also
Qt::AlignmentFlag, Qt::TextFlag, boundingRect(), layoutDirection()
By default, QPainter draws text anti-aliased.
Note
The y-coordinate of rectangle is used as the top of the font.
Definition at line 6528 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawText(), r=[%.2f,%.2f,%.2f,%.2f], flags=%d, str='%s'\n",
            r.x(), r.y(), r.width(), r.height(), flags, str.toLatin1().constData());
 #endif
     Q_D(QPainter);
     if (!d->engine || str.length() == 0 || pen().style() == Qt::NoPen)
         return;
     if (!d->extended)
         d->updateState(d->state);
     qt_format_text(d->state->font, r, flags, 0, str, br, 0, 0, 0, this);
 }
drawText() [6/8]
void QPainter::drawText (const QRect & rectangle, int flags, const QString & text, QRect * boundingRect = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the given text within the provided rectangle according to the specified flags.
The boundingRect (if not null) is set to the what the bounding rectangle should be in order to enclose the whole text.
By default, QPainter draws text anti-aliased.
Note
The y-coordinate of rectangle is used as the top of the font.
Definition at line 6450 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawText(), r=[%d,%d,%d,%d], flags=%d, str='%s'\n",
            r.x(), r.y(), r.width(), r.height(), flags, str.toLatin1().constData());
 #endif
     Q_D(QPainter);
     if (!d->engine || str.length() == 0 || pen().style() == Qt::NoPen)
         return;
     if (!d->extended)
         d->updateState(d->state);
     QRectF bounds;
     qt_format_text(d->state->font, r, flags, 0, str, br ? &bounds : 0, 0, 0, 0, this);
     if (br)
         *br = bounds.toAlignedRect();
 }
drawText() [7/8]
void QPainter::drawText (int x, int y, int width, int height, int flags, const QString & text, QRect * boundingRect = 0) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the given text within the rectangle with origin ({x}, {y}), width and height.
The boundingRect (if not null) is set to the actual bounding rectangle of the output. The flags argument is a bitwise OR of the following flags:
Qt::AlignLeft
Qt::AlignRight
Qt::AlignHCenter
Qt::AlignJustify
Qt::AlignTop
Qt::AlignBottom
Qt::AlignVCenter
Qt::AlignCenter
Qt::TextSingleLine
Qt::TextExpandTabs
Qt::TextShowMnemonic
Qt::TextWordWrap
By default, QPainter draws text anti-aliased.
Note
The y-position is used as the top of the font.
See also
Qt::AlignmentFlag, Qt::TextFlag
Definition at line 960 of file qpainter.h.
 {
     drawText(QRect(x, y, w, h), flags, str, br);
 }
drawText() [8/8]
void QPainter::drawText (const QRectF & rectangle, const QString & text, const QTextOption & option = QTextOption())
Draws the given text in the rectangle specified using the option to control its positioning and orientation.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
By default, QPainter draws text anti-aliased.
Note
The y-coordinate of rectangle is used as the top of the font.
Definition at line 6627 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawText(), r=[%.2f,%.2f,%.2f,%.2f], str='%s'\n",
            r.x(), r.y(), r.width(), r.height(), text.toLatin1().constData());
 #endif
     Q_D(QPainter);
     if (!d->engine || text.length() == 0 || pen().style() == Qt::NoPen)
         return;
     if (!d->extended)
         d->updateState(d->state);
     qt_format_text(d->state->font, r, 0, &o, text, 0, 0, 0, 0, this);
 }
drawTextItem() [1/3]
void QPainter::drawTextItem (const QPointF & p, const QTextItem & ti)
Draws the text item ti at position p.
Warning
This function is not part of the public interface.
Since
4.1
This method ignores the painters background mode and color. drawText and qt_format_text have to do it themselves, as only they know the extents of the complete string.
It ignores the font set on the painter as the text item has one of its own.
The underline and strikeout parameters of the text items font are ignored aswell. You'll need to pass in the correct flags to get underlining and strikeout.
Definition at line 6864 of file qpainter.cpp.
Referenced by QFontEngineXLFD::bitmapForGlyphs(), QTextLine::draw(), drawMenuText(), and drawText().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawTextItem(), pos=[%.f,%.f], str='%s'\n",
                p.x(), p.y(), qPrintable(_ti.text()));
 #endif
     Q_D(QPainter);
     if (!d->engine)
         return;
 #ifndef QT_NO_DEBUG
     qt_painter_thread_test(d->device->devType(),
                            "text and fonts",
                            QFontDatabase::supportsThreadedFontRendering());
 #endif
     QTextItemInt &ti = const_cast<QTextItemInt &>(static_cast<const QTextItemInt &>(_ti));
     if (!d->extended && d->state->bgMode == Qt::OpaqueMode) {
         QRectF rect(p.x(), p.y() - ti.ascent.toReal(), ti.width.toReal(), (ti.ascent + ti.descent + 1).toReal());
         fillRect(rect, d->state->bgBrush);
     }
     if (pen().style() == Qt::NoPen)
         return;
     const RenderHints oldRenderHints = d->state->renderHints;
     if (!d->state->renderHints & QPainter::Antialiasing && d->state->matrix.type() >= QTransform::TxScale) {
         // draw antialias decoration (underline/overline/strikeout) with
         // transformed text
         bool aa = true;
         const QTransform &m = d->state->matrix;
         if (d->state->matrix.type() < QTransform::TxShear) {
             bool isPlain90DegreeRotation =
                 (qFuzzyIsNull(m.m11())
                  && qFuzzyIsNull(m.m12() - qreal(1))
                  && qFuzzyIsNull(m.m21() + qreal(1))
                  && qFuzzyIsNull(m.m22())
                     )
                 ||
                 (qFuzzyIsNull(m.m11() + qreal(1))
                  && qFuzzyIsNull(m.m12())
                  && qFuzzyIsNull(m.m21())
                  && qFuzzyIsNull(m.m22() + qreal(1))
                     )
                 ||
                 (qFuzzyIsNull(m.m11())
                  && qFuzzyIsNull(m.m12() + qreal(1))
                  && qFuzzyIsNull(m.m21() - qreal(1))
                  && qFuzzyIsNull(m.m22())
                     )
                 ;
             aa = !isPlain90DegreeRotation;
         }
         if (aa)
             setRenderHint(QPainter::Antialiasing, true);
     }
     if (!d->extended)
         d->updateState(d->state);
     if (!ti.glyphs.numGlyphs) {
         // nothing to do
     } else if (ti.fontEngine->type() == QFontEngine::Multi) {
         QFontEngineMulti *multi = static_cast<QFontEngineMulti *>(ti.fontEngine);
         const QGlyphLayout &glyphs = ti.glyphs;
         int which = glyphs.glyphs[0] >> 24;
         qreal x = p.x();
         qreal y = p.y();
         bool rtl = ti.flags & QTextItem::RightToLeft;
         if (rtl)
             x += ti.width.toReal();
         int start = 0;
         int end, i;
         for (end = 0; end < ti.glyphs.numGlyphs; ++end) {
             const int e = glyphs.glyphs[end] >> 24;
             if (e == which)
                 continue;
             QTextItemInt ti2 = ti.midItem(multi->engine(which), start, end - start);
             ti2.width = 0;
             // set the high byte to zero and calc the width
             for (i = start; i < end; ++i) {
                 glyphs.glyphs[i] = glyphs.glyphs[i] & 0xffffff;
                 ti2.width += ti.glyphs.effectiveAdvance(i);
             }
             if (rtl)
                 x -= ti2.width.toReal();
             d->engine->drawTextItem(QPointF(x, y), ti2);
             if (!rtl)
                 x += ti2.width.toReal();
             // reset the high byte for all glyphs and advance to the next sub-string
             const int hi = which << 24;
             for (i = start; i < end; ++i) {
                 glyphs.glyphs[i] = hi | glyphs.glyphs[i];
             }
             // change engine
             start = end;
             which = e;
         }
         QTextItemInt ti2 = ti.midItem(multi->engine(which), start, end - start);
         ti2.width = 0;
         // set the high byte to zero and calc the width
         for (i = start; i < end; ++i) {
             glyphs.glyphs[i] = glyphs.glyphs[i] & 0xffffff;
             ti2.width += ti.glyphs.effectiveAdvance(i);
         }
         if (rtl)
             x -= ti2.width.toReal();
         if (d->extended)
             d->extended->drawTextItem(QPointF(x, y), ti2);
         else
             d->engine->drawTextItem(QPointF(x,y), ti2);
         // reset the high byte for all glyphs
         const int hi = which << 24;
         for (i = start; i < end; ++i)
             glyphs.glyphs[i] = hi | glyphs.glyphs[i];
     } else {
         if (d->extended)
             d->extended->drawTextItem(p, ti);
         else
             d->engine->drawTextItem(p, ti);
     }
     drawTextItemDecoration(this, p, ti.fontEngine, ti.underlineStyle, ti.flags, ti.width.toReal(),
                            ti.charFormat);
     if (d->state->renderHints != oldRenderHints) {
         d->state->renderHints = oldRenderHints;
         if (d->extended)
             d->extended->renderHintsChanged();
         else
             d->state->dirtyFlags |= QPaintEngine::DirtyHints;
     }
 }
drawTextItem() [2/3]
void QPainter::drawTextItem (int x, int y, const QTextItem & ti) inline
Warning
This function is not part of the public interface. This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 892 of file qpainter.h.
 {
     drawTextItem(QPointF(x, y), ti);
 }
drawTextItem() [3/3]
void QPainter::drawTextItem (const QPoint & p, const QTextItem & ti) inline
Draws the text item ti at position p.
Warning
This function is not part of the public interface. This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 950 of file qpainter.h.
 {
     drawTextItem(QPointF(p), ti);
 }
drawTiledPixmap() [1/3]
void QPainter::drawTiledPixmap (const QRectF & rectangle, const QPixmap & pixmap, const QPointF & position = QPointF())
Draws a tiled pixmap, inside the given rectangle with its origin at the given position.
Calling drawTiledPixmap() is similar to calling drawPixmap() several times to fill (tile) an area with a pixmap, but is potentially much more efficient depending on the underlying window system.
See also
drawPixmap()
Definition at line 7146 of file qpainter.cpp.
Referenced by QRenderRule::drawBackgroundImage(), QCommonStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QWidgetPrivate::drawWidget(), QPicture::exec(), fillRegion(), QDeclarativeImage::paint(), QGtkPainter::paintBox(), QGtkPainter::paintBoxGap(), QPainterReplayer::process(), and qt_mac_fill_background().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::drawTiledPixmap(), target=[%.2f,%.2f,%.2f,%.2f], pix=[%d,%d], offset=[%.2f,%.2f]\n",
                r.x(), r.y(), r.width(), r.height(),
                pixmap.width(), pixmap.height(),
                sp.x(), sp.y());
 #endif
     Q_D(QPainter);
     if (!d->engine || pixmap.isNull() || r.isEmpty())
         return;
 #ifndef QT_NO_DEBUG
     qt_painter_thread_test(d->device->devType(), "drawTiledPixmap()", true);
 #endif
     qreal sw = pixmap.width();
     qreal sh = pixmap.height();
     qreal sx = sp.x();
     qreal sy = sp.y();
     if (sx < 0)
         sx = qRound(sw) - qRound(-sx) % qRound(sw);
     else
         sx = qRound(sx) % qRound(sw);
     if (sy < 0)
         sy = qRound(sh) - -qRound(sy) % qRound(sh);
     else
         sy = qRound(sy) % qRound(sh);
     if (d->extended) {
         d->extended->drawTiledPixmap(r, pixmap, QPointF(sx, sy));
         return;
     }
     if (d->state->bgMode == Qt::OpaqueMode && pixmap.isQBitmap())
         fillRect(r, d->state->bgBrush);
     d->updateState(d->state);
     if ((d->state->matrix.type() > QTransform::TxTranslate
         && !d->engine->hasFeature(QPaintEngine::PixmapTransform))
         || (d->state->opacity != 1.0 && !d->engine->hasFeature(QPaintEngine::ConstantOpacity)))
     {
         save();
         setBackgroundMode(Qt::TransparentMode);
         setRenderHint(Antialiasing, renderHints() & SmoothPixmapTransform);
         setBrush(QBrush(d->state->pen.color(), pixmap));
         setPen(Qt::NoPen);
         // If there is no rotation involved we have to make sure we use the
         // antialiased and not the aliased coordinate system by rounding the coordinates.
         if (d->state->matrix.type() <= QTransform::TxScale) {
             const QPointF p = roundInDeviceCoordinates(r.topLeft(), d->state->matrix);
             if (d->state->matrix.type() <= QTransform::TxTranslate) {
                 sx = qRound(sx);
                 sy = qRound(sy);
             }
             setBrushOrigin(QPointF(r.x()-sx, r.y()-sy));
             drawRect(QRectF(p, r.size()));
         } else {
             setBrushOrigin(QPointF(r.x()-sx, r.y()-sy));
             drawRect(r);
         }
         restore();
         return;
     }
     qreal x = r.x();
     qreal y = r.y();
     if (d->state->matrix.type() == QTransform::TxTranslate
         && !d->engine->hasFeature(QPaintEngine::PixmapTransform)) {
         x += d->state->matrix.dx();
         y += d->state->matrix.dy();
     }
     d->engine->drawTiledPixmap(QRectF(x, y, r.width(), r.height()), pixmap, QPointF(sx, sy));
 }
drawTiledPixmap() [2/3]
void QPainter::drawTiledPixmap (int x, int y, int w, int h, const QPixmap & pm, int sx = 0, int sy = 0) inline
Definition at line 840 of file qpainter.h.
 {
     drawTiledPixmap(QRectF(x, y, w, h), pm, QPointF(sx, sy));
 }
drawTiledPixmap() [3/3]
void QPainter::drawTiledPixmap (const QRect & rectangle, const QPixmap & pixmap, const QPoint & position = QPoint()) inline
Draws a tiled pixmap, inside the given rectangle with its origin at the given position.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 835 of file qpainter.h.
 {
     drawTiledPixmap(QRectF(rect), pm, QPointF(offset));
 }
end()
bool QPainter::end ()
Ends painting.
Any resources used while painting are released. You don't normally need to call this since it is called by the destructor.
Returns true if the painter is no longer active; otherwise returns false.
See also
begin(), isActive()
Definition at line 1929 of file qpainter.cpp.
Referenced by _q_paintIntoCache(), QFontEngine::alphaMapForGlyph(), alphaMapFromPath(), begin(), QFontEngineXLFD::bitmapForGlyphs(), blendCursor(), QGraphicsItem::boundingRegion(), buttonChange(), QDragManager::drag(), QPixmapColorizeFilter::draw(), QPixmapDropShadowFilter::draw(), QPainterPrivate::draw_helper(), QAlphaPaintEnginePrivate::drawAlphaImage(), QMacStylePrivate::drawCombobox(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QGraphicsScenePrivate::drawItemHelper(), QDeclarativeTextPrivate::drawOutline(), QOpenGLPaintEngine::drawPixmap(), QPlastiqueStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMacStylePrivate::drawTableHeader(), drawTextItem(), QOpenGLPaintEngine::drawTiledPixmap(), QTraceWindowSurface::endPaint(), QX11PaintEnginePrivate::fillPolygon_dev(), QDeclarativeRectangle::generateBorderedRect(), QCommonStyle::generatedIconPixmap(), QDeclarativeRectangle::generateRoundedRect(), make_widget_eventUPP(), QColorWell::mouseMoveEvent(), QColorShowLabel::mouseMoveEvent(), QBlittablePixmapData::paintEngine(), QTipLabel::paintEvent(), QGraphicsView::paintEvent(), QSvgIconEngine::pixmap(), QGraphicsItemEffectSourcePrivate::pixmap(), qt_mac_read_fontsmoothing_settings(), qt_plastique_draw_gradient(), QSvgIOHandler::read(), QWidgetPrivate::render_helper(), QTreeViewPrivate::renderTreeToPixmapForAnimation(), QPixmap::scroll(), QItemDelegate::selected(), QTabBarPrivate::setupMovableTab(), QHeaderViewPrivate::setupSectionIndicator(), QWidgetPrivate::setWindowOpacity_sys(), QWidgetBackingStore::showYellowThing(), QMacStyle::styleHint(), toVGImageWithOpacity(), toVGImageWithOpacitySubRect(), ShaderEffect::updateRenderTargets(), and ~QPainter().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::end()\n");
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::end: Painter not active, aborted");
         qt_cleanup_painter_state(d);
         return false;
     }
     if (d->refcount > 1) {
         d->detachPainterPrivate(this);
         return true;
     }
     bool ended = true;
     if (d->engine->isActive()) {
         ended = d->engine->end();
         d->updateState(0);
         --d->device->painters;
         if (d->device->painters == 0) {
             d->engine->setPaintDevice(0);
             d->engine->setActive(false);
         }
     }
     if (d->states.size() > 1) {
         qWarning("QPainter::end: Painter ended with %d saved states",
                  d->states.size());
     }
     if (d->engine->autoDestruct()) {
         delete d->engine;
     }
     if (d->emulationEngine) {
         delete d->emulationEngine;
         d->emulationEngine = 0;
     }
     if (d->extended) {
         d->extended = 0;
     }
     qt_cleanup_painter_state(d);
     return ended;
 }
endNativePainting()
void QPainter::endNativePainting ()
Restores the painter after manually issuing native painting commands.
Since
4.6
Lets the painter restore any native state that it relies on before calling any other painter commands.
See also
beginNativePainting()
Definition at line 2056 of file qpainter.cpp.
Referenced by ShaderEffectItem::paint().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::beginNativePainting: Painter not active");
         return;
     }
     if (d->extended)
         d->extended->endNativePainting();
     else
         d->engine->syncState();
 }
eraseRect() [1/3]
void QPainter::eraseRect (const QRectF & rectangle)
Erases the area inside the given rectangle.
Equivalent to calling
fillRect(rectangle, background()).
See also
fillRect()
Definition at line 7332 of file qpainter.cpp.
Referenced by QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QComboBoxPrivateScroller::paintEvent(), QColorLuminancePicker::paintEvent(), and QWidget::update().
 {
     Q_D(QPainter);
     fillRect(r, d->state->bgBrush);
 }
eraseRect() [2/3]
void QPainter::eraseRect (int x, int y, int width, int height) inline
Erases the area inside the rectangle beginning at (x, y) with the given width and height.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 779 of file qpainter.h.
 {
     eraseRect(QRectF(x, y, w, h));
 }
eraseRect() [3/3]
void QPainter::eraseRect (const QRect & rectangle) inline
Erases the area inside the given rectangle.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 774 of file qpainter.h.
 {
     eraseRect(QRectF(rect));
 }
fillPath()
void QPainter::fillPath (const QPainterPath & path, const QBrush & brush)
Fills the given path using the given brush.
The outline is not drawn.
Alternatively, you can specify a QColor instead of a QBrush; the QBrush constructor (taking a QColor argument) will automatically create a solid pattern brush.
See also
drawPath()
Definition at line 3456 of file qpainter.cpp.
Referenced by QRenderRule::drawBackground(), QCDEStyle::drawControl(), QMacStyle::drawPrimitive(), QPaintEngine::drawTextItem(), QGraphicsWidget::paintWindowFrame(), and QPainterReplayer::process().
 {
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::fillPath: Painter not active");
         return;
     }
     if (path.isEmpty())
         return;
     if (d->extended) {
         const QGradient *g = brush.gradient();
         if (!g || g->coordinateMode() == QGradient::LogicalMode) {
             d->extended->fill(qtVectorPathForPath(path), brush);
             return;
         }
     }
     QBrush oldBrush = d->state->brush;
     QPen oldPen = d->state->pen;
     setPen(Qt::NoPen);
     setBrush(brush);
     drawPath(path);
     // Reset old state
     setPen(oldPen);
     setBrush(oldBrush);
 }
fillRect() [1/12]
void QPainter::fillRect (const QRectF & rectangle, const QBrush & brush)
Fills the given rectangle with the brush specified.
Alternatively, you can specify a QColor instead of a QBrush; the QBrush constructor (taking a QColor argument) will automatically create a solid pattern brush.
See also
drawRect()
Definition at line 7420 of file qpainter.cpp.
Referenced by _q_paintItem(), QXlibWindowSurface::beginPaint(), QRasterWindowSurface::beginPaint(), QWSMemorySurface::beginPaint(), QFontEngineXLFD::bitmapForGlyphs(), QmlJSDebugger::ToolBarColorBox::createDragPixmap(), QFbScreen::doRedraw(), QDragManager::drag(), QPixmapDropShadowFilter::draw(), QTextLine::draw(), QGraphicsOpacityEffect::draw(), QPainterPrivate::draw_helper(), QItemDelegate::drawBackground(), QGraphicsView::drawBackground(), QGraphicsScene::drawBackground(), QRenderRule::drawBackground(), QWindowsCEStyle::drawComplexControl(), QCommonStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QStyleSheetStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QCDEStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QTextLayout::drawCursor(), QItemDelegate::drawDisplay(), QGraphicsView::drawForeground(), QGraphicsScene::drawForeground(), QStyle::drawItemText(), QTextDocumentLayoutPrivate::drawListItem(), QWindowsMobileStylePrivate::drawPanelItemViewSelected(), drawPixmap(), QWindowsCEStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QStyleSheetStyle::drawPrimitive(), QWindowsMobileStylePrivate::drawScrollbarGrip(), QWindowsMobileStylePrivate::drawScrollbarGroove(), QWindowsMobileStylePrivate::drawScrollbarHandleDown(), QWindowsMobileStylePrivate::drawScrollbarHandleUp(), QWindowsMobileStylePrivate::drawTabBarTab(), drawTabBase(), drawTabShape(), drawTextItem(), drawTextItemDecoration(), drawTiledPixmap(), QWidgetPrivate::drawWidget(), QWindowsCEStylePrivate::drawWinCEShades(), QWindowsCEStylePrivate::drawWinCEShadesSunken(), QWindowsCEStylePrivate::drawWinShades(), eraseRect(), QScriptEdit::extraAreaPaintEvent(), QImage::fill(), fillBackground(), fillRect(), fillRegion(), QCommonStyle::generatedIconPixmap(), make_widget_eventUPP(), QTriangulator< T >::ComplexToSimple::Event::operator<(), QDecorationWindows::paint(), QDecorationStyled::paint(), QDeclarativePaintedItem::paint(), QDeclarativeRectangle::paint(), QComboMenuDelegate::paint(), QDecorationWindows::paintButton(), QDecorationDefault::paintButton(), QWellArray::paintCellContents(), QColorWell::paintCellContents(), QBlittablePixmapData::paintEngine(), QWorkspace::paintEvent(), QToolBar::paintEvent(), QMdiArea::paintEvent(), QPagePreview::paintEvent(), QSystemTrayIconSys::paintEvent(), QWizard::paintEvent(), QHeaderView::paintEvent(), QPlainTextEdit::paintEvent(), QGraphicsView::paintEvent(), QWizardAntiFlickerWidget::paintEvent(), QColorPicker::paintEvent(), QColorShowLabel::paintEvent(), QGraphicsWidget::paintWindowFrame(), QPainterReplayer::process(), qDrawPlainRect(), qDrawShadePanel(), qDrawWinShades(), qt_cleanlooks_draw_buttongradient(), qt_cleanlooks_draw_gradient(), qt_cleanlooks_draw_mdibutton(), qt_plastique_draw_gradient(), QTreeViewPrivate::renderTreeToPixmapForAnimation(), QItemDelegate::selected(), setPenAndDrawBackground(), QWidgetBackingStore::showYellowThing(), and ShaderEffect::updateRenderTargets().
 {
     Q_D(QPainter);
     if (!d->engine)
         return;
     if (d->extended) {
         const QGradient *g = brush.gradient();
         if (!g || g->coordinateMode() == QGradient::LogicalMode) {
             d->extended->fillRect(r, brush);
             return;
         }
     }
     QPen oldPen = pen();
     QBrush oldBrush = this->brush();
     setPen(Qt::NoPen);
     if (brush.style() == Qt::SolidPattern) {
         d->colorBrush.setStyle(Qt::SolidPattern);
         d->colorBrush.setColor(brush.color());
         setBrush(d->colorBrush);
     } else {
         setBrush(brush);
     }
     drawRect(r);
     setBrush(oldBrush);
     setPen(oldPen);
 }
fillRect() [2/12]
void QPainter::fillRect (int x, int y, int width, int height, const QBrush & brush) inline
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the given brush.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 784 of file qpainter.h.
 {
     fillRect(QRect(x, y, w, h), b);
 }
fillRect() [3/12]
void QPainter::fillRect (const QRect & rectangle, const QBrush & brush)
Fills the given rectangle with the specified brush.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 7461 of file qpainter.cpp.
 {
     Q_D(QPainter);
     if (!d->engine)
         return;
     if (d->extended) {
         const QGradient *g = brush.gradient();
         if (!g || g->coordinateMode() == QGradient::LogicalMode) {
             d->extended->fillRect(r, brush);
             return;
         }
     }
     QPen oldPen = pen();
     QBrush oldBrush = this->brush();
     setPen(Qt::NoPen);
     if (brush.style() == Qt::SolidPattern) {
         d->colorBrush.setStyle(Qt::SolidPattern);
         d->colorBrush.setColor(brush.color());
         setBrush(d->colorBrush);
     } else {
         setBrush(brush);
     }
     drawRect(r);
     setBrush(oldBrush);
     setPen(oldPen);
 }
fillRect() [4/12]
void QPainter::fillRect (const QRectF & rectangle, const QColor & color)
Fills the given rectangle with the color specified.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Definition at line 7532 of file qpainter.cpp.
 {
     Q_D(QPainter);
     if (!d->engine)
         return;
     if (d->extended) {
         d->extended->fillRect(r, color);
         return;
     }
     fillRect(r, QBrush(color));
 }
fillRect() [5/12]
void QPainter::fillRect (int x, int y, int width, int height, const QColor & color) inline
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the given color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Definition at line 789 of file qpainter.h.
 {
     fillRect(QRect(x, y, w, h), b);
 }
fillRect() [6/12]
void QPainter::fillRect (const QRect & rectangle, const QColor & color)
Fills the given rectangle with the color specified.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Definition at line 7505 of file qpainter.cpp.
 {
     Q_D(QPainter);
     if (!d->engine)
         return;
     if (d->extended) {
         d->extended->fillRect(r, color);
         return;
     }
     fillRect(r, QBrush(color));
 }
fillRect() [7/12]
void QPainter::fillRect (int x, int y, int width, int height, Qt::GlobalColor color) inline
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the given color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Definition at line 794 of file qpainter.h.
 {
     fillRect(QRect(x, y, w, h), QColor(c));
 }
fillRect() [8/12]
void QPainter::fillRect (const QRect & rectangle, Qt::GlobalColor color) inline
Fills the given rectangle with the specified color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Definition at line 799 of file qpainter.h.
 {
     fillRect(r, QColor(c));
 }
fillRect() [9/12]
void QPainter::fillRect (const QRectF & rectangle, Qt::GlobalColor color) inline
Fills the given rectangle with the specified color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Definition at line 804 of file qpainter.h.
 {
     fillRect(r, QColor(c));
 }
fillRect() [10/12]
void QPainter::fillRect (int x, int y, int width, int height, Qt::BrushStyle style) inline
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the brush style specified.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Definition at line 809 of file qpainter.h.
 {
     fillRect(QRectF(x, y, w, h), QBrush(style));
 }
fillRect() [11/12]
void QPainter::fillRect (const QRect & rectangle, Qt::BrushStyle style) inline
Fills the given rectangle with the brush style specified.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Definition at line 814 of file qpainter.h.
 {
     fillRect(QRectF(r), QBrush(style));
 }
fillRect() [12/12]
void QPainter::fillRect (const QRectF & rectangle, Qt::BrushStyle style) inline
Fills the given rectangle with the brush style specified.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Definition at line 819 of file qpainter.h.
 {
     fillRect(r, QBrush(style));
 }
font()
const QFont & QPainter::font () const
Returns the currently set font used for drawing text.
See also
setFont(), drawText(), {QPainter::Settings}{Settings}
Definition at line 4312 of file qpainter.cpp.
Referenced by QSvgFontStyle::apply(), QDeclarativeTextLayout::draw(), QSvgText::draw(), QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), drawGlyphRun(), drawStaticText(), and QFontFamilyDelegate::paint().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::font: Painter not active");
         return d->fakeState()->font;
     }
     return d->state->font;
 }
fontInfo()
QFontInfo QPainter::fontInfo () const
Returns the font info for the painter if the painter is active.
Otherwise, the return value is undefined.
See also
font(), isActive(), {QPainter::Settings}{Settings}
Definition at line 2095 of file qpainter.cpp.
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::fontInfo: Painter not active");
         return QFontInfo(QFont());
     }
     return QFontInfo(d->state->font);
 }
fontMetrics()
QFontMetrics QPainter::fontMetrics () const
Returns the font metrics for the painter if the painter is active.
Otherwise, the return value is undefined.
See also
font(), isActive(), {QPainter::Settings}{Settings}
Definition at line 2077 of file qpainter.cpp.
Referenced by QWindowsStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsVistaStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QGtkStyle::drawControl(), QMacStyle::drawControl(), QFontFamilyDelegate::paint(), and printPage().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::fontMetrics: Painter not active");
         return QFontMetrics(QFont());
     }
     return QFontMetrics(d->state->font);
 }
hasClipping()
bool QPainter::hasClipping () const
Returns true if clipping has been set; otherwise returns false.
See also
setClipping(), {QPainter::Clipping}{Clipping}
Definition at line 2499 of file qpainter.cpp.
Referenced by QWindowsXPStylePrivate::drawBackgroundDirectly(), QMacPrintEnginePrivate::newPage_helper(), QMacCGContext::QMacCGContext(), QWidget::render(), setClipping(), and QX11PaintEnginePrivate::systemStateChanged().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::hasClipping: Painter not active");
         return false;
     }
     return d->state->clipEnabled && d->state->clipOperation != Qt::NoClip;
 }
initFrom()
void QPainter::initFrom (const QWidget * widget)
Initializes the painters pen, background and font to the same as the given widget.
This function is called automatically when the painter is opened on a QWidget.
See also
begin(), {QPainter::Settings}{Settings}
Definition at line 1558 of file qpainter.cpp.
Referenced by QPainterPrivate::attachPainterPrivate(), begin(), and QTabBarPrivate::setupMovableTab().
 {
     Q_ASSERT_X(widget, "QPainter::initFrom(const QWidget *widget)", "Widget cannot be 0");
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::initFrom: Painter not active, aborted");
         return;
     }
     const QPalette &pal = widget->palette();
     d->state->pen = QPen(pal.brush(widget->foregroundRole()), 0);
     d->state->bgBrush = pal.brush(widget->backgroundRole());
     d->state->deviceFont = QFont(widget->font(), const_cast<QWidget*> (widget));
     d->state->font = d->state->deviceFont;
     if (d->extended) {
         d->extended->penChanged();
     } else if (d->engine) {
         d->engine->setDirty(QPaintEngine::DirtyPen);
         d->engine->setDirty(QPaintEngine::DirtyBrush);
         d->engine->setDirty(QPaintEngine::DirtyFont);
     }
 }
isActive()
bool QPainter::isActive () const
Returns true if begin() has been called and end() has not yet been called; otherwise returns false.
See also
begin(), QPaintDevice::paintingActive()
Definition at line 1545 of file qpainter.cpp.
Referenced by QPainterPrivate::attachPainterPrivate(), device(), QPixmapConvolutionFilter::draw(), QPixmapBlurFilter::draw(), QWindowsXPStylePrivate::drawBackground(), QWidgetPrivate::drawWidget(), QTextDocument::print(), QPaintBuffer::processCommands(), qDrawBorderPixmap(), QGraphicsView::render(), QWidget::render(), QWidgetPrivate::render(), and ~QPainter().
 {
     Q_D(const QPainter);
     return d->engine;
 }
layoutDirection()
Qt::LayoutDirection QPainter::layoutDirection () const
Returns the layout direction used by the painter when drawing text.
See also
QTextOption::textDirection(), setLayoutDirection(), drawText(), {QPainter::Settings}{Settings}
Definition at line 8729 of file qpainter.cpp.
Referenced by _q_paintItem(), QIcon::paint(), and qt_format_text().
 {
     Q_D(const QPainter);
     return d->state ? d->state->layoutDirection : Qt::LayoutDirectionAuto;
 }
matrix()
const QMatrix & QPainter::matrix () const
Use worldTransform() instead.
See also
worldTransform()
Definition at line 3061 of file qpainter.cpp.
Referenced by clipPath(), and clipRegion().
 {
     return worldMatrix();
 }
matrixEnabled()
bool QPainter::matrixEnabled () const
Use worldMatrixEnabled() instead
See also
worldMatrixEnabled()
Definition at line 3222 of file qpainter.cpp.
 {
     return worldMatrixEnabled();
 }
opacity()
qreal QPainter::opacity () const
Returns the opacity of the painter.
Since
4.2
The default value is 1.
Definition at line 2115 of file qpainter.cpp.
Referenced by _q_paintItem(), QSvgOpacityStyle::apply(), QSvgArc::draw(), QSvgLine::draw(), QSvgPolyline::draw(), QSvgText::draw(), QWindowsXPStylePrivate::drawBackground(), QGraphicsScenePrivate::drawItemHelper(), QGraphicsScene::drawItems(), QWidget::render(), and setOpacity().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::opacity: Painter not active");
         return 1.0;
     }
     return d->state->opacity;
 }
paintEngine()
QPaintEngine * QPainter::paintEngine () const
Returns the paint engine that the painter is currently operating on if the painter is active; otherwise 0.
See also
isActive()
Definition at line 1991 of file qpainter.cpp.
Referenced by QPainterPrivate::attachPainterPrivate(), QPixmapConvolutionFilter::draw(), QPixmapBlurFilter::draw(), QPixmapColorizeFilter::draw(), QPixmapDropShadowFilter::draw(), QGraphicsBlurEffect::draw(), QGraphicsDropShadowEffect::draw(), QWindowsXPStylePrivate::drawBackground(), QWindowsXPStylePrivate::drawBackgroundDirectly(), QCommonStyle::drawComplexControl(), QMacStyle::drawComplexControl(), drawTextItemDecoration(), QVistaHelper::drawTitleBar(), XPThemeData::mask(), QPreviewPaintEngine::newPage(), QDecorationStyled::paint(), QDecorationDefault::paint(), QDeclarativePaintedItem::paint(), QDecorationDefault::paintButton(), QVistaBackButton::paintEvent(), QSystemTrayIconSys::paintEvent(), QPainterReplayer::process(), QPaintEngineExReplayer::process(), QPaintBuffer::processCommands(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), qDrawBorderPixmap(), QMacCGContext::QMacCGContext(), qt_vg_drawVGImage(), qt_vg_drawVGImageStencil(), qt_x11_get_brush_gc(), qt_x11_get_pen_gc(), QGLCustomShaderStage::removeFromPainter(), QWidget::render(), and QGLCustomShaderStage::setOnPainter().
 {
     Q_D(const QPainter);
     return d->engine;
 }
pen()
const QPen & QPainter::pen () const
Returns the painter's current pen.
See also
setPen(), {QPainter::Settings}{Settings}
Definition at line 4152 of file qpainter.cpp.
Referenced by QSvgStrokeStyle::apply(), QSvgAnimateColor::apply(), QFontEngineBox::boundingBox(), QSvgArc::draw(), QSvgFont::draw(), QSvgLine::draw(), QSvgPolyline::draw(), QTextLayout::draw(), QSvgText::draw(), QGraphicsScenePrivate::draw(), QTextLine::draw(), QTextDocumentLayoutPrivate::drawBlock(), QPaintEnginePrivate::drawBoxTextItem(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QMacStyle::drawControl(), QTextLayout::drawCursor(), QTextDocumentLayoutPrivate::drawFrame(), QWindowsCEStyle::drawItemText(), QCleanlooksStyle::drawItemText(), QStyle::drawItemText(), QPaintEngine::drawPoints(), drawPoints(), QWindowsVistaStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), drawStaticText(), QWindowsMobileStylePrivate::drawTabBarTab(), QTextDocumentLayoutPrivate::drawTableCell(), drawText(), QCoreGraphicsPaintEngine::drawTextItem(), drawTextItem(), drawTextItemDecoration(), QWindowsCEStylePrivate::drawWinCEShades(), QWindowsCEStylePrivate::drawWinCEShadesSunken(), QWindowsCEStylePrivate::drawWinShades(), QPicture::exec(), fillRect(), generateWavyPixmap(), QTableView::paintEvent(), QLineEdit::paintEvent(), QStaticTextPrivate::paintText(), qDrawPlainRect(), qDrawShadeLine(), qDrawShadePanel(), qDrawShadeRect(), qDrawWinShades(), qt_plastique_draw_frame(), qt_plastique_drawFrame(), qt_plastique_drawShadedPanel(), setPen(), QSvgNode::strokeWidth(), and QPicturePaintEngine::writeCmdLength().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::pen: Painter not active");
         return d->fakeState()->pen;
     }
     return d->state->pen;
 }
redirected()
QPaintDevice * QPainter::redirected (const QPaintDevice * device, QPoint * offset = 0) static
Using QWidget::render() obsoletes the use of this function.
Note
This class or function is threadsafe.
Returns the replacement for given device. The optional out parameter offset returns the offset within the replaced device.
Warning
Making use of redirections in the QPainter API implies that QPainter::begin() and QPaintDevice destructors need to hold a mutex for a short period. This can impact performance. Use of QWidget::render is strongly encouraged.
See also
setRedirected(), restoreRedirected()
Definition at line 8391 of file qpainter.cpp.
Referenced by begin(), QAxHostWidget::paintEvent(), qt_mac_fill_background(), and QWidgetPrivate::render().
 {
     Q_ASSERT(device != 0);
     if (device->devType() == QInternal::Widget) {
         const QWidgetPrivate *widgetPrivate = static_cast<const QWidget *>(device)->d_func();
         if (widgetPrivate->redirectDev)
             return widgetPrivate->redirected(offset);
     }
     if (!globalRedirectionAtomic() || *globalRedirectionAtomic() == 0)
         return 0;
     QMutexLocker locker(globalRedirectionsMutex());
     QPaintDeviceRedirectionList *redirections = globalRedirections();
     Q_ASSERT(redirections != 0);
     for (int i = redirections->size()-1; i >= 0; --i)
         if (redirections->at(i) == device) {
             if (offset)
                 *offset = redirections->at(i).offset;
             return redirections->at(i).replacement;
         }
     if (offset)
         *offset = QPoint(0, 0);
     return 0;
 }
renderHints()
QPainter::RenderHints QPainter::renderHints () const
Returns a flag that specifies the rendering hints that are set for this painter.
See also
testRenderHint(), {QPainter::Rendering Quality}{Rendering Quality}
Definition at line 7675 of file qpainter.cpp.
Referenced by _q_paintIntoCache(), QGraphicsOpacityEffect::draw(), QRenderRule::drawBackground(), QTextDocumentLayoutPrivate::drawBorder(), QRenderRule::drawBorder(), QRenderRule::drawBorderImage(), QTextLayout::drawCursor(), drawImage(), QGraphicsScenePrivate::drawItemHelper(), QRenderRule::drawOutline(), drawPixmap(), QPlastiqueStyle::drawPrimitive(), drawTiledPixmap(), QGraphicsProxyWidget::paint(), QGraphicsView::paintEvent(), QPainterReplayer::process(), and QWidgetPrivate::render_helper().
 {
     Q_D(const QPainter);
     if (!d->engine)
         return 0;
     return d->state->renderHints;
 }
resetMatrix()
void QPainter::resetMatrix ()
Resets any transformations that were made using translate(), scale(), shear(), rotate(), setWorldMatrix(), setViewport() and setWindow().
It is advisable to use resetTransform() instead of this function to preserve the properties of perspective transformations.
See also
{QPainter::Coordinate Transformations}{Coordinate Transformations}
Definition at line 3137 of file qpainter.cpp.
 {
     resetTransform();
 }
resetTransform()
void QPainter::resetTransform ()
Resets any transformations that were made using translate(), scale(), shear(), rotate(), setWorldTransform(), setViewport() and setWindow().
See also
{Coordinate Transformations}
Definition at line 9598 of file qpainter.cpp.
Referenced by QPainterPrivate::draw_helper(), and resetMatrix().
 {
      Q_D(QPainter);
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::resetMatrix()\n");
 #endif
     if (!d->engine) {
         qWarning("QPainter::resetMatrix: Painter not active");
         return;
     }
     d->state->wx = d->state->wy = d->state->vx = d->state->vy = 0;                        // default view origins
     d->state->ww = d->state->vw = d->device->metric(QPaintDevice::PdmWidth);
     d->state->wh = d->state->vh = d->device->metric(QPaintDevice::PdmHeight);
     d->state->worldMatrix = QTransform();
     setMatrixEnabled(false);
     setViewTransformEnabled(false);
     if (d->extended)
         d->extended->transformChanged();
     else
         d->state->dirtyFlags |= QPaintEngine::DirtyTransform;
 }
restore()
void QPainter::restore ()
Restores the current painter state (pops a saved state off the stack).
See also
save()
Definition at line 1620 of file qpainter.cpp.
Referenced by _q_paintItem(), QFontEngineBox::boundingBox(), QPainterPrivate::detachPainterPrivate(), QSvgFont::draw(), QSvgTinyDocument::draw(), QTextLayout::draw(), QGraphicsScenePrivate::draw(), QTextLine::draw(), QGraphicsOpacityEffect::draw(), QGraphicsScene::drawBackground(), QWindowsXPStylePrivate::drawBackground(), QRenderRule::drawBackgroundImage(), QTextDocumentLayoutPrivate::drawBorder(), QPaintEnginePrivate::drawBoxTextItem(), QWindowsVistaStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QCommonStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QStyleSheetStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QSplashScreen::drawContents(), QDeclarativeTextInput::drawContents(), QTextDocument::drawContents(), QTextControl::drawContents(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QCDEStyle::drawControl(), QWindowsMobileStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), QStyleHelper::drawDial(), QItemDelegate::drawDisplay(), QGraphicsScene::drawForeground(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QX11PaintEngine::drawFreetype(), drawImage(), QTextDocumentLayoutPrivate::drawListItem(), QPlastiqueStylePrivate::drawPartialFrame(), drawPicture(), drawPixmap(), QPaintEngine::drawPoints(), drawPoints(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QTreeView::drawRow(), QWindowsMobileStylePrivate::drawTabBarTab(), QPaintEngine::drawTextItem(), drawTextItemDecoration(), drawTiledPixmap(), QWidgetPrivate::drawWidget(), QPaintBufferEngine::end(), QPicture::exec(), fillBackground(), fillRegion(), QAlphaPaintEngine::flushAndInit(), QDecorationStyled::paint(), ShaderEffectItem::paint(), QItemDelegate::paint(), QDeclarativeImage::paint(), QFontFamilyDelegate::paint(), QDeclarativeText::paint(), QGraphicsTextItem::paint(), QCommandLinkButton::paintEvent(), QLabel::paintEvent(), QListView::paintEvent(), QHeaderView::paintEvent(), QGraphicsView::paintEvent(), QStaticTextPrivate::paintText(), QGraphicsWidget::paintWindowFrame(), printPage(), QPainterReplayer::process(), qDrawEdge(), qDrawRoundedCorners(), qt_format_text(), QGraphicsScene::render(), QGraphicsView::render(), QRenderRule::unsetClip(), and QCommonStylePrivate::viewItemDrawText().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::restore()\n");
 #endif
     Q_D(QPainter);
     if (d->states.size()<=1) {
         qWarning("QPainter::restore: Unbalanced save/restore");
         return;
     } else if (!d->engine) {
         qWarning("QPainter::restore: Painter not active");
         return;
     }
     QPainterState *tmp = d->state;
     d->states.pop_back();
     d->state = d->states.back();
     d->txinv = false;
     if (d->extended) {
         d->checkEmulation();
         d->extended->setState(d->state);
         delete tmp;
         return;
     }
     // trigger clip update if the clip path/region has changed since
     // last save
     if (!d->state->clipInfo.isEmpty()
         && (tmp->changeFlags & (QPaintEngine::DirtyClipRegion | QPaintEngine::DirtyClipPath))) {
         // reuse the tmp state to avoid any extra allocs...
         tmp->dirtyFlags = QPaintEngine::DirtyClipPath;
         tmp->clipOperation = Qt::NoClip;
         tmp->clipPath = QPainterPath();
         d->engine->updateState(*tmp);
         // replay the list of clip states,
         for (int i=0; i<d->state->clipInfo.size(); ++i) {
             const QPainterClipInfo &info = d->state->clipInfo.at(i);
             tmp->matrix = info.matrix;
             tmp->matrix *= d->state->redirectionMatrix;
             tmp->clipOperation = info.operation;
             if (info.clipType == QPainterClipInfo::RectClip) {
                 tmp->dirtyFlags = QPaintEngine::DirtyClipRegion | QPaintEngine::DirtyTransform;
                 tmp->clipRegion = info.rect;
             } else if (info.clipType == QPainterClipInfo::RegionClip) {
                 tmp->dirtyFlags = QPaintEngine::DirtyClipRegion | QPaintEngine::DirtyTransform;
                 tmp->clipRegion = info.region;
             } else { // clipType == QPainterClipInfo::PathClip
                 tmp->dirtyFlags = QPaintEngine::DirtyClipPath | QPaintEngine::DirtyTransform;
                 tmp->clipPath = info.path;
             }
             d->engine->updateState(*tmp);
         }
         //Since we've updated the clip region anyway, pretend that the clip path hasn't changed:
         d->state->dirtyFlags &= ~(QPaintEngine::DirtyClipPath | QPaintEngine::DirtyClipRegion);
         tmp->changeFlags &= ~(QPaintEngine::DirtyClipPath | QPaintEngine::DirtyClipRegion);
         tmp->changeFlags |= QPaintEngine::DirtyTransform;
     }
     d->updateState(d->state);
     delete tmp;
 }
restoreRedirected()
void QPainter::restoreRedirected (const QPaintDevice * device) static
Using QWidget::render() obsoletes the use of this function.
Note
This class or function is threadsafe.
Restores the previous redirection for the given device after a call to setRedirected().
Warning
Making use of redirections in the QPainter API implies that QPainter::begin() and QPaintDevice destructors need to hold a mutex for a short period. This can impact performance. Use of QWidget::render is strongly encouraged.
See also
redirected()
Definition at line 8344 of file qpainter.cpp.
 {
     Q_ASSERT(device != 0);
     QMutexLocker locker(globalRedirectionsMutex());
     QPaintDeviceRedirectionList *redirections = globalRedirections();
     Q_ASSERT(redirections != 0);
     for (int i = redirections->size()-1; i >= 0; --i) {
         if (redirections->at(i) == device) {
             globalRedirectionAtomic()->deref();
             const int internalWidgetRedirectionIndex = redirections->at(i).internalWidgetRedirectionIndex;
             redirections->removeAt(i);
             // Restore the internal widget redirection, i.e. remove it from the global
             // redirection list and put it back into QWidgetPrivate. The index is only set when
             // someone call QPainter::setRedirected in a widget's paint event and we internally
             // have a redirection set (typically set in QWidgetPrivate::drawWidget).
             if (internalWidgetRedirectionIndex >= 0) {
                 Q_ASSERT(internalWidgetRedirectionIndex < redirections->size());
                 const QPaintDeviceRedirection &redirectionDevice = redirections->at(internalWidgetRedirectionIndex);
                 QWidget *widget = static_cast<QWidget *>(const_cast<QPaintDevice *>(device));
                 widget->d_func()->setRedirected(redirectionDevice.replacement, redirectionDevice.offset);
                 redirections->removeAt(internalWidgetRedirectionIndex);
             }
             return;
         }
     }
 }
rotate()
void QPainter::rotate (qreal angle)
Rotates the coordinate system the given angle clockwise.
See also
setWorldTransform(), {QPainter::Coordinate Transformations}{Coordinate Transformations}
Definition at line 3287 of file qpainter.cpp.
Referenced by QCommonStyle::drawControl(), QWindowsVistaStyle::drawControl(), QWindowsMobileStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), and QMacStyle::standardIconImplementation().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::rotate(), angle=%f\n", a);
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::rotate: Painter not active");
         return;
     }
     d->state->worldMatrix.rotate(a);
     d->state->WxF = true;
     d->updateMatrix();
 }
save()
void QPainter::save ()
Saves the current painter state (pushes the state onto a stack).
A save() must be followed by a corresponding restore(); the end() function unwinds the stack.
See also
restore()
Definition at line 1590 of file qpainter.cpp.
Referenced by _q_paintItem(), QPainterPrivate::attachPainterPrivate(), QPaintBufferEngine::begin(), QFontEngineBox::boundingBox(), QSvgFont::draw(), QSvgTinyDocument::draw(), QTextLayout::draw(), QGraphicsScenePrivate::draw(), QTextLine::draw(), QGraphicsOpacityEffect::draw(), QGraphicsScene::drawBackground(), QWindowsXPStylePrivate::drawBackground(), QRenderRule::drawBackgroundImage(), QTextDocumentLayoutPrivate::drawBorder(), QPaintEnginePrivate::drawBoxTextItem(), QWindowsVistaStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QCommonStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QStyleSheetStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QSplashScreen::drawContents(), QDeclarativeTextInput::drawContents(), QTextDocument::drawContents(), QTextControl::drawContents(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QCDEStyle::drawControl(), QWindowsMobileStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), QStyleHelper::drawDial(), QItemDelegate::drawDisplay(), QGraphicsScene::drawForeground(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QX11PaintEngine::drawFreetype(), drawImage(), QTextDocumentLayoutPrivate::drawListItem(), QPlastiqueStylePrivate::drawPartialFrame(), drawPicture(), drawPixmap(), QPaintEngine::drawPoints(), drawPoints(), QWindowsCEStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QTreeView::drawRow(), QWindowsMobileStylePrivate::drawTabBarTab(), QPaintEngine::drawTextItem(), drawTextItemDecoration(), drawTiledPixmap(), QWidgetPrivate::drawWidget(), QPicture::exec(), fillBackground(), fillRegion(), QAlphaPaintEngine::flushAndInit(), QDecorationStyled::paint(), ShaderEffectItem::paint(), QItemDelegate::paint(), QDeclarativeImage::paint(), QFontFamilyDelegate::paint(), QDeclarativeText::paint(), QGraphicsTextItem::paint(), QCommandLinkButton::paintEvent(), QLabel::paintEvent(), QListView::paintEvent(), QHeaderView::paintEvent(), QGraphicsView::paintEvent(), QStaticTextPrivate::paintText(), QGraphicsWidget::paintWindowFrame(), printPage(), QPainterReplayer::process(), qDrawEdge(), qDrawRoundedCorners(), qt_format_text(), QGraphicsScene::render(), QGraphicsView::render(), QRenderRule::setClip(), setClip(), and QCommonStylePrivate::viewItemDrawText().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::save()\n");
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::save: Painter not active");
         return;
     }
     if (d->extended) {
         d->state = d->extended->createState(d->states.back());
         d->extended->setState(d->state);
     } else {
         d->updateState(d->state);
         d->state = new QPainterState(d->states.back());
         d->engine->state = d->state;
     }
     d->states.push_back(d->state);
 }
scale()
void QPainter::scale (qreal sx, qreal sy)
Scales the coordinate system by ({sx}, {sy}).
See also
setWorldTransform() {QPainter::Coordinate Transformations}{Coordinate Transformations}
Definition at line 3234 of file qpainter.cpp.
Referenced by QGraphicsItem::boundingRegion(), QSvgFont::draw(), QSvgText::draw(), drawImage(), drawPixmap(), QSvgTinyDocument::mapSourceToTarget(), QDeclarativePaintedItem::paint(), QLabel::paintEvent(), qt_blurImage(), qt_format_text(), and ShaderEffect::updateRenderTargets().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::scale(), sx=%f, sy=%f\n", sx, sy);
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::scale: Painter not active");
         return;
     }
     d->state->worldMatrix.scale(sx,sy);
     d->state->WxF = true;
     d->updateMatrix();
 }
setBackground()
void QPainter::setBackground (const QBrush & brush)
Sets the background brush of the painter to the given brush.
The background brush is the brush that is filled in when drawing opaque text, stippled lines and bitmaps. The background brush has no effect in transparent background mode (which is the default).
See also
background(), setBackgroundMode(), {QPainter::Settings}{Settings}
Definition at line 4258 of file qpainter.cpp.
Referenced by QPainterPrivate::draw_helper(), QWindowsCEStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QPicture::exec(), and QAlphaPaintEnginePrivate::resetState().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setBackground(), color=%04x, style=%d\n", bg.color().rgb(), bg.style());
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setBackground: Painter not active");
         return;
     }
     d->state->bgBrush = bg;
     if (!d->extended)
         d->state->dirtyFlags |= QPaintEngine::DirtyBackground;
 }
setBackgroundMode()
void QPainter::setBackgroundMode (Qt::BGMode mode)
Sets the background mode of the painter to the given mode.
Qt::TransparentMode (the default) draws stippled lines and text without setting the background pixels. Qt::OpaqueMode fills these space with the current background color.
Note that in order to draw a bitmap or pixmap transparently, you must use QPixmap::setMask().
See also
backgroundMode(), setBackground(), {QPainter::Settings}{Settings}
Definition at line 3998 of file qpainter.cpp.
Referenced by QPainterPrivate::draw_helper(), QWindowsCEStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), drawImage(), drawPixmap(), QWindowsMobileStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), drawTiledPixmap(), QPicture::exec(), and QPainterReplayer::process().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setBackgroundMode(), mode=%d\n", mode);
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setBackgroundMode: Painter not active");
         return;
     }
     if (d->state->bgMode == mode)
         return;
     d->state->bgMode = mode;
     if (d->extended) {
         d->checkEmulation();
     } else {
         d->state->dirtyFlags |= QPaintEngine::DirtyBackgroundMode;
     }
 }
setBrush() [1/2]
void QPainter::setBrush (const QBrush & brush)
Sets the painter's brush to the given brush.
The painter's brush defines how shapes are filled.
See also
brush(), {QPainter::Settings}{Settings}
Definition at line 4171 of file qpainter.cpp.
Referenced by QFontEngine::alphaMapForGlyph(), alphaMapFromPath(), QSvgFillStyle::apply(), QSvgViewportFillStyle::apply(), QSvgAnimateColor::apply(), QBalloonTip::balloon(), QFontEngineBox::boundingBox(), QmlJSDebugger::ToolBarColorBox::createDragPixmap(), QSvgTinyDocument::draw(), QTextLayout::draw(), QGraphicsScenePrivate::draw(), QTextLine::draw(), QPainterPrivate::draw_helper(), QTextDocumentLayoutPrivate::drawBorder(), QPaintEnginePrivate::drawBoxTextItem(), QCommonStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleHelper::drawDial(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QX11PaintEngine::drawFreetype(), drawImage(), QTextDocumentLayoutPrivate::drawListItem(), drawPixmap(), QPaintEngine::drawPoints(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QDeclarativeRectangle::drawRect(), QLCDNumberPrivate::drawSegment(), drawTabCloseButton(), QTextDocumentLayoutPrivate::drawTableCell(), drawTextItemDecoration(), drawTiledPixmap(), QPicture::exec(), QVGPaintEngine::fill(), QOpenGLPaintEngine::fill(), fillPath(), QX11PaintEnginePrivate::fillPolygon_dev(), fillRect(), QDeclarativeRectangle::generateBorderedRect(), QDeclarativeRectangle::generateRoundedRect(), QFontFamilyDelegate::paint(), QGraphicsPathItem::paint(), QGraphicsRectItem::paint(), QGraphicsEllipseItem::paint(), QGraphicsPolygonItem::paint(), QGraphicsSimpleTextItem::paint(), QGraphicsItemGroup::paint(), QBlittablePixmapData::paintEngine(), QWhatsThat::paintEvent(), QColorLuminancePicker::paintEvent(), QPainterReplayer::process(), qDrawEdge(), qDrawPlainRect(), qDrawRoundedCorners(), qDrawShadeRect(), qt_graphicsItem_highlightSelected(), QAlphaPaintEnginePrivate::resetState(), QSvgFillStyle::revert(), QSvgViewportFillStyle::revert(), QSvgAnimateColor::revert(), QWidgetPrivate::setWindowOpacity_sys(), and strokePath().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setBrush(), color=%04x, style=%d\n", brush.color().rgb(), brush.style());
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setBrush: Painter not active");
         return;
     }
     if (d->state->brush.d == brush.d)
         return;
     if (d->extended) {
         d->state->brush = brush;
         d->checkEmulation();
         d->extended->brushChanged();
         return;
     }
     d->state->brush = brush;
     d->state->dirtyFlags |= QPaintEngine::DirtyBrush;
 }
setBrush() [2/2]
void QPainter::setBrush (Qt::BrushStyle style)
Sets the painter's brush to black color and the specified style.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4208 of file qpainter.cpp.
 {
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setBrush: Painter not active");
         return;
     }
     if (d->state->brush.style() == style &&
         (style == Qt::NoBrush
          || (style == Qt::SolidPattern && d->state->brush.color() == QColor(0, 0, 0))))
         return;
     d->state->brush = QBrush(Qt::black, style);
     if (d->extended)
         d->extended->brushChanged();
     else
         d->state->dirtyFlags |= QPaintEngine::DirtyBrush;
 }
setBrushOrigin() [1/3]
void QPainter::setBrushOrigin (int x, int y) inline
Sets the brush's origin to point (x, y).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 825 of file qpainter.h.
Referenced by QPainterPrivate::draw_helper(), QItemDelegate::drawBackground(), QGraphicsScene::drawBackground(), QTreeView::drawBranches(), QPlastiqueStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QGraphicsScene::drawForeground(), drawImage(), drawPixmap(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QTextDocumentLayoutPrivate::drawTableCell(), drawTextItemDecoration(), drawTiledPixmap(), QPicture::exec(), fillBackground(), QX11PaintEnginePrivate::fillPolygon_dev(), QWidgetPrivate::paintBackground(), QPlainTextEdit::paintEvent(), QHeaderView::paintSection(), QPainterReplayer::process(), qDrawPlainRect(), and QAlphaPaintEnginePrivate::resetState().
 {
     setBrushOrigin(QPoint(x, y));
 }
setBrushOrigin() [2/3]
void QPainter::setBrushOrigin (const QPoint & position) inline
Sets the brush's origin to the given position.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 830 of file qpainter.h.
 {
     setBrushOrigin(QPointF(p));
 }
setBrushOrigin() [3/3]
void QPainter::setBrushOrigin (const QPointF & position)
Sets the brush origin to position.
The brush origin specifies the (0, 0) coordinate of the painter's brush.
Note that while the brushOrigin() was necessary to adopt the parent's background for a widget in Qt 3, this is no longer the case since the Qt 4 painter doesn't paint the background unless you explicitly tell it to do so by setting the widget's QWidget::autoFillBackground property to true.
See also
brushOrigin(), {QPainter::Settings}{Settings}
Definition at line 2198 of file qpainter.cpp.
 {
     Q_D(QPainter);
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setBrushOrigin(), (%.2f,%.2f)\n", p.x(), p.y());
 #endif
     if (!d->engine) {
         qWarning("QPainter::setBrushOrigin: Painter not active");
         return;
     }
     d->state->brushOrigin = p;
     if (d->extended) {
         d->extended->brushOriginChanged();
         return;
     }
     d->state->dirtyFlags |= QPaintEngine::DirtyBrushOrigin;
 }
setClipPath()
void QPainter::setClipPath (const QPainterPath & path, Qt::ClipOperation operation = Qt::ReplaceClip)
Enables clipping, and sets the clip path for the painter to the given path, with the clip operation.
Note that the clip path is specified in logical (painter) coordinates.
See also
clipPath(), clipRegion(), {QPainter::Clipping}{Clipping}
Definition at line 3365 of file qpainter.cpp.
Referenced by QTextLayout::draw(), QPicture::exec(), QPainterReplayer::process(), QGraphicsView::render(), QAlphaPaintEnginePrivate::resetState(), QRenderRule::setClip(), setClip(), and setClipRect().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output) {
         QRectF b = path.boundingRect();
         printf("QPainter::setClipPath(), size=%d, op=%d, bounds=[%.2f,%.2f,%.2f,%.2f]\n",
                path.elementCount(), op, b.x(), b.y(), b.width(), b.height());
     }
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setClipPath: Painter not active");
         return;
     }
     if ((!d->state->clipEnabled && op != Qt::NoClip) || (d->state->clipOperation == Qt::NoClip && op == Qt::UniteClip))
         op = Qt::ReplaceClip;
     if (d->extended) {
         d->state->clipEnabled = true;
         d->extended->clip(path, op);
         if (op == Qt::NoClip || op == Qt::ReplaceClip)
             d->state->clipInfo.clear();
         d->state->clipInfo << QPainterClipInfo(path, op, d->state->matrix);
         d->state->clipOperation = op;
         return;
     }
     if (d->state->clipOperation == Qt::NoClip && op == Qt::IntersectClip)
         op = Qt::ReplaceClip;
     d->state->clipPath = path;
     d->state->clipOperation = op;
     if (op == Qt::NoClip || op == Qt::ReplaceClip)
         d->state->clipInfo.clear();
     d->state->clipInfo << QPainterClipInfo(path, op, d->state->matrix);
     d->state->clipEnabled = true;
     d->state->dirtyFlags |= QPaintEngine::DirtyClipPath | QPaintEngine::DirtyClipEnabled;
     d->updateState(d->state);
 }
setClipping()
void QPainter::setClipping (bool enable)
Enables clipping if enable is true, or disables clipping if enable is false.
See also
hasClipping(), {QPainter::Clipping}{Clipping}
Definition at line 2517 of file qpainter.cpp.
Referenced by QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QWindowsMobileStyle::drawComplexControl(), QCDEStyle::drawControl(), QWindowsMobileStyle::drawControl(), QWindowsMobileStyle::drawPrimitive(), QPicture::exec(), make_widget_eventUPP(), printPage(), QPainterReplayer::process(), qDrawPlainRect(), and QAlphaPaintEnginePrivate::resetState().
 {
     Q_D(QPainter);
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setClipping(), enable=%s, was=%s\n",
                enable ? "on" : "off",
                hasClipping() ? "on" : "off");
 #endif
     if (!d->engine) {
         qWarning("QPainter::setClipping: Painter not active, state will be reset by begin");
         return;
     }
     if (hasClipping() == enable)
         return;
     // we can't enable clipping if we don't have a clip
     if (enable
         && (d->state->clipInfo.isEmpty() || d->state->clipInfo.last().operation == Qt::NoClip))
         return;
     d->state->clipEnabled = enable;
     if (d->extended) {
         d->extended->clipEnabledChanged();
         return;
     }
     d->state->dirtyFlags |= QPaintEngine::DirtyClipEnabled;
     d->updateState(d->state);
 }
setClipRect() [1/3]
void QPainter::setClipRect (const QRectF & rectangle, Qt::ClipOperation operation = Qt::ReplaceClip)
Enables clipping, and sets the clip region to the given rectangle using the given clip operation.
The default operation is to replace the current clip rectangle.
Note that the clip rectangle is specified in logical (painter) coordinates.
See also
clipRegion(), setClipping(), {QPainter::Clipping}{Clipping}
Definition at line 2801 of file qpainter.cpp.
Referenced by QTextLine::draw(), QRenderRule::drawBackgroundImage(), QCleanlooksStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QTextDocument::drawContents(), QTextControl::drawContents(), QCommonStyle::drawControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QStyleSheetStyle::drawControl(), QItemDelegate::drawDisplay(), QPlastiqueStylePrivate::drawPartialFrame(), QWindowsXPStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QTreeView::drawRow(), QItemDelegate::paint(), QDeclarativeImage::paint(), QDeclarativePaintedItem::paint(), QDeclarativeText::paint(), QFocusFrame::paintEvent(), QMdiSubWindow::paintEvent(), QMenuBar::paintEvent(), QLabel::paintEvent(), QPagePreview::paintEvent(), QWhatsThat::paintEvent(), QMenu::paintEvent(), QLineEdit::paintEvent(), QPlainTextEdit::paintEvent(), QGraphicsWidget::paintWindowFrame(), printPage(), QPainterReplayer::process(), qDrawPlainRect(), qt_format_text(), QGraphicsScene::render(), QGraphicsView::render(), and setClip().
 {
     Q_D(QPainter);
     if (d->extended) {
         if ((!d->state->clipEnabled && op != Qt::NoClip) || (d->state->clipOperation == Qt::NoClip && op == Qt::UniteClip))
             op = Qt::ReplaceClip;
         if (!d->engine) {
             qWarning("QPainter::setClipRect: Painter not active");
             return;
         }
         qreal right = rect.x() + rect.width();
         qreal bottom = rect.y() + rect.height();
         qreal pts[] = { rect.x(), rect.y(),
                         right, rect.y(),
                         right, bottom,
                         rect.x(), bottom };
         QVectorPath vp(pts, 4, 0, QVectorPath::RectangleHint);
         d->state->clipEnabled = true;
         d->extended->clip(vp, op);
         if (op == Qt::ReplaceClip || op == Qt::NoClip)
             d->state->clipInfo.clear();
         d->state->clipInfo << QPainterClipInfo(rect, op, d->state->matrix);
         d->state->clipOperation = op;
         return;
     }
     if (qreal(int(rect.top())) == rect.top()
         && qreal(int(rect.bottom())) == rect.bottom()
         && qreal(int(rect.left())) == rect.left()
         && qreal(int(rect.right())) == rect.right())
     {
         setClipRect(rect.toRect(), op);
         return;
     }
     if (rect.isEmpty()) {
         setClipRegion(QRegion(), op);
         return;
     }
     QPainterPath path;
     path.addRect(rect);
     setClipPath(path, op);
 }
setClipRect() [2/3]
void QPainter::setClipRect (const QRect & rectangle, Qt::ClipOperation operation = Qt::ReplaceClip)
Enables clipping, and sets the clip region to the given rectangle using the given clip operation.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2858 of file qpainter.cpp.
 {
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setClipRect: Painter not active");
         return;
     }
     if ((!d->state->clipEnabled && op != Qt::NoClip) || (d->state->clipOperation == Qt::NoClip && op == Qt::UniteClip))
         op = Qt::ReplaceClip;
     if (d->extended) {
         d->state->clipEnabled = true;
         d->extended->clip(rect, op);
         if (op == Qt::ReplaceClip || op == Qt::NoClip)
             d->state->clipInfo.clear();
         d->state->clipInfo << QPainterClipInfo(rect, op, d->state->matrix);
         d->state->clipOperation = op;
         return;
     }
     if (d->state->clipOperation == Qt::NoClip && op == Qt::IntersectClip)
         op = Qt::ReplaceClip;
     d->state->clipRegion = rect;
     d->state->clipOperation = op;
     if (op == Qt::NoClip || op == Qt::ReplaceClip)
         d->state->clipInfo.clear();
     d->state->clipInfo << QPainterClipInfo(rect, op, d->state->matrix);
     d->state->clipEnabled = true;
     d->state->dirtyFlags |= QPaintEngine::DirtyClipRegion | QPaintEngine::DirtyClipEnabled;
     d->updateState(d->state);
 }
setClipRect() [3/3]
void QPainter::setClipRect (int x, int y, int w, int h, Qt::ClipOperation op = Qt::ReplaceClip) inline
Enables clipping, and sets the clip region to the rectangle beginning at (x, y) with the given width and height.
Definition at line 769 of file qpainter.h.
 {
     setClipRect(QRect(x, y, w, h), op);
 }
setClipRegion()
void QPainter::setClipRegion (const QRegion & region, Qt::ClipOperation operation = Qt::ReplaceClip)
Sets the clip region to the given region using the specified clip operation.
The default clip operation is to replace the current clip region.
Note that the clip region is given in logical coordinates.
See also
clipRegion(), setClipRect(), {QPainter::Clipping}{Clipping}
Definition at line 2917 of file qpainter.cpp.
Referenced by _q_paintIntoCache(), QTableViewPrivate::drawAndClipSpans(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QWindowsVistaStyle::drawComplexControl(), QCommonStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QStyleSheetStyle::drawComplexControl(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QWindowsVistaStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QWidgetPrivate::drawWidget(), QPicture::exec(), fillRegion(), QDecorationStyled::paint(), QDecorationWindows::paint(), QDecorationDefault::paint(), QWidgetPrivate::paintBackground(), QMenuBar::paintEvent(), QMenu::paintEvent(), QGraphicsView::paintEvent(), QGraphicsWidget::paintWindowFrame(), QPainterReplayer::process(), qt_mac_fill_background(), QAlphaPaintEnginePrivate::resetState(), setClipRect(), QWidgetBackingStore::showYellowThing(), and QWidget::update().
 {
     Q_D(QPainter);
 #ifdef QT_DEBUG_DRAW
     QRect rect = r.boundingRect();
     if (qt_show_painter_debug_output)
         printf("QPainter::setClipRegion(), size=%d, [%d,%d,%d,%d]\n",
            r.rects().size(), rect.x(), rect.y(), rect.width(), rect.height());
 #endif
     if (!d->engine) {
         qWarning("QPainter::setClipRegion: Painter not active");
         return;
     }
     if ((!d->state->clipEnabled && op != Qt::NoClip) || (d->state->clipOperation == Qt::NoClip && op == Qt::UniteClip))
         op = Qt::ReplaceClip;
     if (d->extended) {
         d->state->clipEnabled = true;
         d->extended->clip(r, op);
         if (op == Qt::NoClip || op == Qt::ReplaceClip)
             d->state->clipInfo.clear();
         d->state->clipInfo << QPainterClipInfo(r, op, d->state->matrix);
         d->state->clipOperation = op;
         return;
     }
     if (d->state->clipOperation == Qt::NoClip && op == Qt::IntersectClip)
         op = Qt::ReplaceClip;
     d->state->clipRegion = r;
     d->state->clipOperation = op;
     if (op == Qt::NoClip || op == Qt::ReplaceClip)
         d->state->clipInfo.clear();
     d->state->clipInfo << QPainterClipInfo(r, op, d->state->matrix);
     d->state->clipEnabled = true;
     d->state->dirtyFlags |= QPaintEngine::DirtyClipRegion | QPaintEngine::DirtyClipEnabled;
     d->updateState(d->state);
 }
setCompositionMode()
void QPainter::setCompositionMode (CompositionMode mode)
Sets the composition mode to the given mode.
Warning
Only a QPainter operating on a QImage fully supports all composition modes. The RasterOp modes are supported for X11 as described in compositionMode().
See also
compositionMode()
Definition at line 2422 of file qpainter.cpp.
Referenced by _q_paintIntoCache(), QSvgCompOpStyle::apply(), QXcbWindowSurface::beginPaint(), QXlibWindowSurface::beginPaint(), QRasterWindowSurface::beginPaint(), QWSMemorySurface::beginPaint(), QPixmapDropShadowFilter::draw(), QGraphicsOpacityEffect::draw(), QPainterPrivate::draw_helper(), QWindowsVistaStyle::drawControl(), QPicture::exec(), QImage::fill(), QCommonStyle::generatedIconPixmap(), QDecorationStyled::paint(), QDecorationDefault::paint(), QDeclarativePaintedItem::paint(), QWidgetPrivate::paintBackground(), QDecorationDefault::paintButton(), QBlittablePixmapData::paintEngine(), QSystemTrayIconSys::paintEvent(), QPainterReplayer::process(), QSvgCompOpStyle::revert(), QPixmap::scroll(), QItemDelegate::selected(), and ShaderEffect::updateRenderTargets().
 {
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setCompositionMode: Painter not active");
         return;
     }
     if (d->state->composition_mode == mode)
         return;
     if (d->extended) {
         d->state->composition_mode = mode;
         d->extended->compositionModeChanged();
         return;
     }
     if (mode >= QPainter::RasterOp_SourceOrDestination) {
         if (!d->engine->hasFeature(QPaintEngine::RasterOpModes)) {
             qWarning("QPainter::setCompositionMode: "
                      "Raster operation modes not supported on device");
             return;
         }
     } else if (mode >= QPainter::CompositionMode_Plus) {
         if (!d->engine->hasFeature(QPaintEngine::BlendModes)) {
             qWarning("QPainter::setCompositionMode: "
                      "Blend modes not supported on device");
             return;
         }
     } else if (!d->engine->hasFeature(QPaintEngine::PorterDuff)) {
         if (mode != CompositionMode_Source && mode != CompositionMode_SourceOver) {
             qWarning("QPainter::setCompositionMode: "
                      "PorterDuff modes not supported on device");
             return;
         }
     }
     d->state->composition_mode = mode;
     d->state->dirtyFlags |= QPaintEngine::DirtyCompositionMode;
 }
setFont()
void QPainter::setFont (const QFont & font)
Sets the painter's font to the given font.
This font is used by subsequent drawText() functions. The text color is the same as the pen color.
If you set a font that isn't available, Qt finds a close match. font() will return what you set using setFont() and fontInfo() returns the font actually being used (which may be the same).
See also
font(), drawText(), {QPainter::Settings}{Settings}
Definition at line 4288 of file qpainter.cpp.
Referenced by QSvgFontStyle::apply(), QDragManager::drag(), QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), QDeclarativeTextPrivate::drawTextLayout(), QPicture::exec(), QStaticTextPrivate::init(), QFontFamilyDelegate::paint(), QGraphicsSimpleTextItem::paint(), QCommandLinkButton::paintEvent(), QMdiSubWindow::paintEvent(), QPagePreview::paintEvent(), QHeaderView::paintEvent(), QGraphicsWidget::paintWindowFrame(), printPage(), QPainterReplayer::process(), QWidgetBackingStore::removeDirtyWidget(), QAlphaPaintEnginePrivate::resetState(), QSvgFontStyle::revert(), and QCommonStylePrivate::viewItemDrawText().
 {
     Q_D(QPainter);
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setFont(), family=%s, pointSize=%d\n", font.family().toLatin1().constData(), font.pointSize());
 #endif
     if (!d->engine) {
         qWarning("QPainter::setFont: Painter not active");
         return;
     }
     d->state->font = QFont(font.resolve(d->state->deviceFont), device());
     if (!d->extended)
         d->state->dirtyFlags |= QPaintEngine::DirtyFont;
 }
setLayoutDirection()
void QPainter::setLayoutDirection (Qt::LayoutDirection direction)
Sets the layout direction used by the painter when drawing text, to the specified direction.
The default is Qt::LayoutDirectionAuto, which will implicitly determine the direction from the text drawn.
See also
QTextOption::setTextDirection(), layoutDirection(), drawText(), {QPainter::Settings}{Settings}
Definition at line 8717 of file qpainter.cpp.
Referenced by _q_paintItem().
 {
     Q_D(QPainter);
     if (d->state)
         d->state->layoutDirection = direction;
 }
setMatrix()
void QPainter::setMatrix (const QMatrix & matrix, bool combine = false)
Use setWorldTransform() instead.
See also
setWorldTransform()
Definition at line 3045 of file qpainter.cpp.
Referenced by QMacStyle::drawPrimitive(), and rotateTabPainter().
 {
     setWorldTransform(QTransform(matrix), combine);
 }
setMatrixEnabled()
void QPainter::setMatrixEnabled (bool enable)
Use setWorldMatrixEnabled() instead.
See also
setWorldMatrixEnabled()
Definition at line 3209 of file qpainter.cpp.
Referenced by QPicture::exec().
 {
     setWorldMatrixEnabled(enable);
 }
setOpacity()
void QPainter::setOpacity (qreal opacity)
Sets the opacity of the painter to opacity.
Since
4.2
The value should be in the range 0.0 to 1.0, where 0.0 is fully transparent and 1.0 is fully opaque.
Opacity set on the painter will apply to all drawing operations individually.
Definition at line 2139 of file qpainter.cpp.
Referenced by _q_paintItem(), QSvgOpacityStyle::apply(), QSvgArc::draw(), QSvgLine::draw(), QSvgPolyline::draw(), QPixmapColorizeFilter::draw(), QSvgText::draw(), QGraphicsScenePrivate::draw(), QGraphicsOpacityEffect::draw(), QPainterPrivate::draw_helper(), QGraphicsScenePrivate::drawItemHelper(), QGraphicsScene::drawItems(), QGraphicsScenePrivate::drawSubtreeRecursive(), QPicture::exec(), QTriangulator< T >::ComplexToSimple::Event::operator<(), QGraphicsView::paintEvent(), QPainterReplayer::process(), QAlphaPaintEnginePrivate::resetState(), QSvgOpacityStyle::revert(), QHeaderViewPrivate::setupSectionIndicator(), toVGImageWithOpacity(), and toVGImageWithOpacitySubRect().
 {
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setOpacity: Painter not active");
         return;
     }
     opacity = qMin(qreal(1), qMax(qreal(0), opacity));
     if (opacity == d->state->opacity)
         return;
     d->state->opacity = opacity;
     if (d->extended)
         d->extended->opacityChanged();
     else
         d->state->dirtyFlags |= QPaintEngine::DirtyOpacity;
 }
setPen() [1/3]
void QPainter::setPen (const QColor & color)
Sets the painter's pen to have style Qt::SolidLine, width 0 and the specified color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4047 of file qpainter.cpp.
Referenced by QFontEngine::alphaMapForGlyph(), alphaMapFromPath(), QSvgStrokeStyle::apply(), QSvgAnimateColor::apply(), QBalloonTip::balloon(), QFontEngineXLFD::bitmapForGlyphs(), QFontEngineBox::boundingBox(), QmlJSDebugger::ToolBarColorBox::createDragPixmap(), QDragManager::drag(), QDeclarativeTextLayout::draw(), QSvgFont::draw(), QSvgTinyDocument::draw(), QSvgPolyline::draw(), QTextLayout::draw(), QGraphicsScenePrivate::draw(), QTextLine::draw(), QPainterPrivate::draw_helper(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawBorder(), QPaintEnginePrivate::drawBoxTextItem(), QWindowsCEStyle::drawComplexControl(), QCommonStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QStyleSheetStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QSplashScreen::drawContents(), QDeclarativeTextInput::drawContents(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), QStyleHelper::drawDial(), QItemDelegate::drawDisplay(), QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QX11PaintEngine::drawFreetype(), drawImage(), QWindowsCEStyle::drawItemText(), QCleanlooksStyle::drawItemText(), QStyle::drawItemText(), QTextDocumentLayoutPrivate::drawListItem(), QWindowsMobileStylePrivate::drawPanelItemViewSelected(), QPlastiqueStylePrivate::drawPartialFrame(), QOpenGLPaintEngine::drawPixmap(), drawPixmap(), QPaintEngine::drawPoints(), drawPoints(), QWindowsCEStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QDeclarativeRectangle::drawRect(), QLCDNumberPrivate::drawSegment(), drawStaticText(), QWindowsMobileStylePrivate::drawTabBarTab(), drawTabBase(), drawTabCloseButton(), QTextDocumentLayoutPrivate::drawTableCell(), drawTabShape(), drawTextItemDecoration(), QDeclarativeTextPrivate::drawTextLayout(), QOpenGLPaintEngine::drawTiledPixmap(), drawTiledPixmap(), QWindowsCEStylePrivate::drawWinCEShades(), QWindowsCEStylePrivate::drawWinCEShadesSunken(), QWindowsCEStylePrivate::drawWinShades(), QPicture::exec(), QScriptEdit::extraAreaPaintEvent(), fillPath(), QX11PaintEnginePrivate::fillPolygon_dev(), fillRect(), QDeclarativeRectangle::generateBorderedRect(), QDeclarativeRectangle::generateRoundedRect(), generateWavyPixmap(), QTriangulator< T >::ComplexToSimple::Event::operator<(), QDecorationWindows::paint(), QDecorationDefault::paint(), QFontFamilyDelegate::paint(), QGraphicsPathItem::paint(), QGraphicsRectItem::paint(), QGraphicsEllipseItem::paint(), QGraphicsPolygonItem::paint(), QGraphicsLineItem::paint(), QGraphicsSimpleTextItem::paint(), QWellArray::paintCellContents(), QStatusBar::paintEvent(), QTableView::paintEvent(), QPagePreview::paintEvent(), QWhatsThat::paintEvent(), QLineEdit::paintEvent(), QComboBox::paintEvent(), QWizardHeader::paintEvent(), QFileDialogComboBox::paintEvent(), QWizardAntiFlickerWidget::paintEvent(), QColorPicker::paintEvent(), QColorLuminancePicker::paintEvent(), QPainterReplayer::process(), qDrawEdge(), qDrawPlainRect(), qDrawRoundedCorners(), qDrawShadeLine(), qDrawShadePanel(), qDrawShadeRect(), qDrawWinShades(), qt_cleanlooks_draw_mdibutton(), qt_graphicsItem_highlightSelected(), qt_plastique_draw_frame(), qt_plastique_draw_mdibutton(), qt_plastique_drawFrame(), qt_plastique_drawShadedPanel(), QAlphaPaintEnginePrivate::resetState(), QSvgStrokeStyle::revert(), QSvgAnimateColor::revert(), setPenAndDrawBackground(), QWidgetPrivate::setWindowOpacity_sys(), strokePath(), and QSvgNode::transformedBounds().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setPen(), color=%04x\n", color.rgb());
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setPen: Painter not active");
         return;
     }
     if (d->state->pen.style() == Qt::SolidLine
         && d->state->pen.widthF() == 0
         && d->state->pen.isSolid()
         && d->state->pen.color() == color)
         return;
     QPen pen(color.isValid() ? color : QColor(Qt::black), 0, Qt::SolidLine);
     d->state->pen = pen;
     if (d->extended)
         d->extended->penChanged();
     else
         d->state->dirtyFlags |= QPaintEngine::DirtyPen;
 }
setPen() [2/3]
void QPainter::setPen (const QPen & pen)
Sets the painter's pen to be the given pen.
The pen defines how to draw lines and outlines, and it also defines the text color.
See also
pen(), {QPainter::Settings}{Settings}
Definition at line 4083 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setPen(), color=%04x, (brushStyle=%d) style=%d, cap=%d, join=%d\n",
            pen.color().rgb(), pen.brush().style(), pen.style(), pen.capStyle(), pen.joinStyle());
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setPen: Painter not active");
         return;
     }
     if (d->state->pen == pen)
         return;
     d->state->pen = pen;
     if (d->extended) {
         d->checkEmulation();
         d->extended->penChanged();
         return;
     }
     d->state->dirtyFlags |= QPaintEngine::DirtyPen;
 }
setPen() [3/3]
void QPainter::setPen (Qt::PenStyle style)
Sets the painter's pen to have the given style, width 0 and black color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4121 of file qpainter.cpp.
 {
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setPen: Painter not active");
         return;
     }
     if (d->state->pen.style() == style
         && (style == Qt::NoPen || (d->state->pen.widthF() == 0
                                    && d->state->pen.isSolid()
                                    && d->state->pen.color() == QColor(Qt::black))))
         return;
     // QPen(Qt::NoPen) is to avoid creating QPenData, including its brush (from the color)
     // Note that this works well as long as QPen(Qt::NoPen) returns a black, zero-width pen
     d->state->pen = (style == Qt::NoPen) ? QPen(Qt::NoPen) : QPen(Qt::black, 0, style);
     if (d->extended)
         d->extended->penChanged();
     else
         d->state->dirtyFlags |= QPaintEngine::DirtyPen;
 }
setRedirected()
void QPainter::setRedirected (const QPaintDevice * device, QPaintDevice * replacement, const QPoint & offset = QPoint()) static
Please use QWidget::render() instead.
Note
This class or function is threadsafe.
Redirects all paint commands for the given paint device, to the replacement device. The optional point offset defines an offset within the source device.
The redirection will not be effective until the begin() function has been called; make sure to call end() for the given device's painter (if any) before redirecting. Call restoreRedirected() to restore the previous redirection.
Warning
Making use of redirections in the QPainter API implies that QPainter::begin() and QPaintDevice destructors need to hold a mutex for a short period. This can impact performance. Use of QWidget::render is strongly encouraged.
See also
redirected(), restoreRedirected()
Definition at line 8293 of file qpainter.cpp.
 {
     Q_ASSERT(device != 0);
     bool hadInternalWidgetRedirection = false;
     if (device->devType() == QInternal::Widget) {
         const QWidgetPrivate *widgetPrivate = static_cast<const QWidget *>(device)->d_func();
         // This is the case when the widget is in a paint event.
         if (widgetPrivate->redirectDev) {
             // Remove internal redirection and put it back into the global redirection list.
             QPoint oldOffset;
             QPaintDevice *oldReplacement = widgetPrivate->redirected(&oldOffset);
             const_cast<QWidgetPrivate *>(widgetPrivate)->restoreRedirected();
             setRedirected(device, oldReplacement, oldOffset);
             hadInternalWidgetRedirection = true;
         }
     }
     QPoint roffset;
     QPaintDevice *rdev = redirected(replacement, &roffset);
     QMutexLocker locker(globalRedirectionsMutex());
     QPaintDeviceRedirectionList *redirections = globalRedirections();
     Q_ASSERT(redirections != 0);
     *redirections += QPaintDeviceRedirection(device, rdev ? rdev : replacement, offset + roffset,
                                              hadInternalWidgetRedirection ? redirections->size() - 1 : -1);
     globalRedirectionAtomic()->ref();
 }
setRenderHint()
void QPainter::setRenderHint (RenderHint hint, bool on = true)
Sets the given render hint on the painter if on is true; otherwise clears the render hint.
See also
setRenderHints(), renderHints(), {QPainter::Rendering Quality}{Rendering Quality}
Definition at line 7620 of file qpainter.cpp.
Referenced by QFontEngine::alphaMapForGlyph(), alphaMapFromPath(), QSvgTinyDocument::draw(), QTextLine::draw(), QPainterPrivate::draw_helper(), QRenderRule::drawBackground(), QTextDocumentLayoutPrivate::drawBorder(), QRenderRule::drawBorder(), QRenderRule::drawBorderImage(), QCommonStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QDeclarativeTextInput::drawContents(), QDeclarativeTextEdit::drawContents(), QCommonStyle::drawControl(), QCleanlooksStyle::drawControl(), QMacStyle::drawControl(), QTextLayout::drawCursor(), QStyleHelper::drawDial(), drawImage(), QTextDocumentLayoutPrivate::drawListItem(), QRenderRule::drawOutline(), drawPixmap(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QDeclarativeRectangle::drawRect(), drawTabShape(), QPaintEngine::drawTextItem(), drawTextItem(), drawTiledPixmap(), QPicture::exec(), QScriptEdit::extraAreaPaintEvent(), QDeclarativeRectangle::generateBorderedRect(), QDeclarativeRectangle::generateRoundedRect(), generateWavyPixmap(), QMacPixmapData::macCreatePixels(), QTriangulator< T >::ComplexToSimple::Event::operator<(), QDeclarativeImage::paint(), QDeclarativeBorderImage::paint(), QDeclarativeRectangle::paint(), QDeclarativeText::paint(), QGraphicsPixmapItem::paint(), QLCDNumber::paintEvent(), QGraphicsWidget::paintWindowFrame(), QPainterReplayer::process(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), qDrawBorderPixmap(), qt_blurImage(), and QImage::transformed().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setRenderHint: hint=%x, %s\n", hint, on ? "on" : "off");
 #endif
 #ifndef QT_NO_DEBUG
     static const bool antialiasingDisabled = qgetenv("QT_NO_ANTIALIASING").toInt();
     if (hint == QPainter::Antialiasing && antialiasingDisabled)
         return;
 #endif
     setRenderHints(hint, on);
 }
setRenderHints()
void QPainter::setRenderHints (RenderHints hints, bool on = true)
Sets the given render hints on the painter if on is true; otherwise clears the render hints.
Since
4.2
See also
setRenderHint(), renderHints(), {QPainter::Rendering Quality}{Rendering Quality}
Definition at line 7649 of file qpainter.cpp.
Referenced by _q_paintIntoCache(), QGraphicsItem::boundingRegion(), QGraphicsOpacityEffect::draw(), QDeclarativeRectangle::drawRect(), drawTabCloseButton(), QGraphicsProxyWidget::paint(), QDeclarativeImage::paint(), QDeclarativeBorderImage::paint(), QDeclarativePaintedItem::paint(), QDeclarativeRectangle::paint(), QDeclarativeText::paint(), QGraphicsView::paintEvent(), QGraphicsItemEffectSourcePrivate::pixmap(), QWidgetPrivate::render_helper(), and setRenderHint().
 {
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setRenderHint: Painter must be active to set rendering hints");
         return;
     }
     if (on)
         d->state->renderHints |= hints;
     else
         d->state->renderHints &= ~hints;
     if (d->extended)
         d->extended->renderHintsChanged();
     else
         d->state->dirtyFlags |= QPaintEngine::DirtyHints;
 }
setTransform()
void QPainter::setTransform (const QTransform & transform, bool combine = false)
Sets the world transformation matrix.
Since
4.3
If combine is true, the specified transform is combined with the current matrix; otherwise it replaces the current matrix.
See also
transform() setWorldTransform()
Definition at line 9547 of file qpainter.cpp.
Referenced by QPainterPrivate::draw_helper(), QAlphaPaintEnginePrivate::drawAlphaImage(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QPaintEngine::drawPoints(), QPicture::exec(), QAlphaPaintEngine::flushAndInit(), QStaticTextPrivate::init(), QMacPixmapData::macCreatePixels(), QGraphicsView::paintEvent(), QPainterReplayer::process(), qDrawPlainRect(), QGraphicsView::render(), QWidgetPrivate::render_helper(), QAlphaPaintEnginePrivate::resetState(), QPainterReplayer::setupTransform(), and QImage::transformed().
 {
     setWorldTransform(transform, combine);
 }
setViewport() [1/2]
void QPainter::setViewport (const QRect & rectangle)
Sets the painter's viewport rectangle to the given rectangle, and enables view transformations.
The viewport rectangle is part of the view transformation. The viewport specifies the device coordinate system. Its sister, the window(), specifies the logical coordinate system.
The default viewport rectangle is the same as the device's rectangle.
See also
viewport(), viewTransformEnabled() {Coordinate System::Window-Viewport Conversion}{Window-Viewport Conversion}
Definition at line 7815 of file qpainter.cpp.
Referenced by QPicture::exec().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setViewport(), [%d,%d,%d,%d]\n", r.x(), r.y(), r.width(), r.height());
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setViewport: Painter not active");
         return;
     }
     d->state->vx = r.x();
     d->state->vy = r.y();
     d->state->vw = r.width();
     d->state->vh = r.height();
     d->state->VxF = true;
     d->updateMatrix();
 }
setViewport() [2/2]
void QPainter::setViewport (int x, int y, int width, int height) inline
Sets the painter's viewport rectangle to be the rectangle beginning at (x, y) with the given width and height.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 985 of file qpainter.h.
 {
     setViewport(QRect(x, y, w, h));
 }
setViewTransformEnabled()
void QPainter::setViewTransformEnabled (bool enable)
Enables view transformations if enable is true, or disables view transformations if enable is false.
See also
viewTransformEnabled(), {Coordinate System::Window-Viewport Conversion}{Window-Viewport Conversion}
Definition at line 7906 of file qpainter.cpp.
Referenced by QPicture::exec(), and QAlphaPaintEnginePrivate::resetState().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setViewTransformEnabled(), enable=%d\n", enable);
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setViewTransformEnabled: Painter not active");
         return;
     }
     if (enable == d->state->VxF)
         return;
     d->state->VxF = enable;
     d->updateMatrix();
 }
setWindow() [1/2]
void QPainter::setWindow (const QRect & rectangle)
Sets the painter's window to the given rectangle, and enables view transformations.
The window rectangle is part of the view transformation. The window specifies the logical coordinate system. Its sister, the viewport(), specifies the device coordinate system.
The default window rectangle is the same as the device's rectangle.
See also
window(), viewTransformEnabled(), {Coordinate System::Window-Viewport Conversion}{Window-Viewport Conversion}
Definition at line 7745 of file qpainter.cpp.
Referenced by QPicture::exec(), and QTriangulator< T >::ComplexToSimple::Event::operator<().
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setWindow(), [%d,%d,%d,%d]\n", r.x(), r.y(), r.width(), r.height());
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setWindow: Painter not active");
         return;
     }
     d->state->wx = r.x();
     d->state->wy = r.y();
     d->state->ww = r.width();
     d->state->wh = r.height();
     d->state->VxF = true;
     d->updateMatrix();
 }
setWindow() [2/2]
void QPainter::setWindow (int x, int y, int width, int height) inline
Sets the painter's window to the rectangle beginning at (x, y) and the given width and height.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 990 of file qpainter.h.
 {
     setWindow(QRect(x, y, w, h));
 }
setWorldMatrix()
void QPainter::setWorldMatrix (const QMatrix & matrix, bool combine = false)
Sets the transformation matrix to matrix and enables transformations.
Since
4.2
Note
It is advisable to use setWorldTransform() instead of this function to preserve the properties of perspective transformations.
If combine is true, then matrix is combined with the current transformation matrix; otherwise matrix replaces the current transformation matrix.
If matrix is the identity matrix and combine is false, this function calls setWorldMatrixEnabled(false). (The identity matrix is the matrix where QMatrix::m11() and QMatrix::m22() are 1.0 and the rest are 0.0.)
The following functions can transform the coordinate system without using a QMatrix:
translate()
scale()
shear()
rotate()
They operate on the painter's worldMatrix() and are implemented like this:
void QPainter::rotate(qreal angle)
{
    QMatrix matrix;
    matrix.rotate(angle);
    setWorldMatrix(matrix, true);
}
Note that when using setWorldMatrix() function you should always have combine be true when you are drawing into a QPicture. Otherwise it may not be possible to replay the picture with additional transformations; using the translate(), scale(), etc. convenience functions is safe.
For more information about the coordinate system, transformations and window-viewport conversion, see Coordinate System.
See also
setWorldTransform(), QTransform
Definition at line 3003 of file qpainter.cpp.
 {
     setWorldTransform(QTransform(matrix), combine);
 }
setWorldMatrixEnabled()
void QPainter::setWorldMatrixEnabled (bool enable)
Enables transformations if enable is true, or disables transformations if enable is false.
Since
4.2
The world transformation matrix is not changed.
See also
worldMatrixEnabled(), worldTransform(), {QPainter::Coordinate Transformations}{Coordinate Transformations}
Definition at line 3157 of file qpainter.cpp.
Referenced by setMatrixEnabled().
 {
     Q_D(QPainter);
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::setMatrixEnabled(), enable=%d\n", enable);
 #endif
     if (!d->engine) {
         qWarning("QPainter::setMatrixEnabled: Painter not active");
         return;
     }
     if (enable == d->state->WxF)
         return;
     d->state->WxF = enable;
     d->updateMatrix();
 }
setWorldTransform()
void QPainter::setWorldTransform (const QTransform & matrix, bool combine = false)
Sets the world transformation matrix.
If combine is true, the specified matrix is combined with the current matrix; otherwise it replaces the current matrix.
See also
transform(), setTransform()
Definition at line 9630 of file qpainter.cpp.
Referenced by _q_paintIntoCache(), QSvgTransformStyle::apply(), QSvgAnimateTransform::apply(), QGraphicsItem::boundingRegion(), QGraphicsEffectSource::draw(), QGraphicsShaderEffect::draw(), QSvgTinyDocument::draw(), QPixmapBlurFilter::draw(), QGraphicsColorizeEffect::draw(), QSvgText::draw(), QGraphicsDropShadowEffect::draw(), QGraphicsOpacityEffect::draw(), QGraphicsScenePrivate::drawItemHelper(), QGraphicsScene::drawItems(), QGraphicsScenePrivate::drawSubtreeRecursive(), QDeclarativeImage::paint(), QDeclarativeBorderImage::paint(), QGraphicsView::paintEvent(), ShaderEffect::prepareBufferedDraw(), QGraphicsScene::render(), QSvgTransformStyle::revert(), QSvgAnimateTransform::revert(), setMatrix(), setWorldMatrix(), setWorldTransform(), and QSvgNode::transformedBounds().
 {
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::setWorldTransform: Painter not active");
         return;
     }
     if (combine)
         d->state->worldMatrix = matrix * d->state->worldMatrix;                        // combines
     else
         d->state->worldMatrix = matrix;                                // set new matrix
     d->state->WxF = true;
     d->updateMatrix();
 }
shear()
void QPainter::shear (qreal sh, qreal sv)
Shears the coordinate system by ({sh}, {sv}).
See also
setWorldTransform(), {QPainter::Coordinate Transformations}{Coordinate Transformations}
Definition at line 3258 of file qpainter.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::shear(), sh=%f, sv=%f\n", sh, sv);
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::shear: Painter not active");
         return;
     }
     d->state->worldMatrix.shear(sh, sv);
     d->state->WxF = true;
     d->updateMatrix();
 }
strokePath()
void QPainter::strokePath (const QPainterPath & path, const QPen & pen)
Draws the outline (strokes) the path path with the pen specified by pen.
See also
fillPath(), {QPainter::Drawing}{Drawing}
Definition at line 3413 of file qpainter.cpp.
Referenced by drawArc(), QPicture::exec(), QPainterReplayer::process(), and setViewTransformEnabled().
 {
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::strokePath: Painter not active");
         return;
     }
     if (path.isEmpty())
         return;
     if (d->extended) {
         const QGradient *g = qpen_brush(pen).gradient();
         if (!g || g->coordinateMode() == QGradient::LogicalMode) {
             d->extended->stroke(qtVectorPathForPath(path), pen);
             return;
         }
     }
     QBrush oldBrush = d->state->brush;
     QPen oldPen = d->state->pen;
     setPen(pen);
     setBrush(Qt::NoBrush);
     drawPath(path);
     // Reset old state
     setPen(oldPen);
     setBrush(oldBrush);
 }
testRenderHint()
bool QPainter::testRenderHint (RenderHint hint) const inline
Returns true if hint is set; otherwise returns false.
Since
4.3
See also
renderHints(), setRenderHint()
Definition at line 457 of file qpainter.h.
Referenced by QDeclarativeRectangle::drawRect(), QDeclarativeImage::paint(), QDeclarativeBorderImage::paint(), QDeclarativeRectangle::paint(), QDeclarativeText::paint(), and qDrawBorderPixmap().
 { return renderHints() & hint; }
transform()
const QTransform & QPainter::transform () const
Returns the world transformation matrix.
See also
worldTransform()
Definition at line 9558 of file qpainter.cpp.
Referenced by QSvgArc::bounds(), QSvgEllipse::bounds(), QSvgImage::bounds(), QSvgLine::bounds(), QSvgPath::bounds(), QSvgPolygon::bounds(), QSvgPolyline::bounds(), QSvgRect::bounds(), boundsOnStroke(), QPixmapBlurFilter::draw(), QMotifStyle::drawControl(), QTextLayout::drawCursor(), QPaintEngine::drawPoints(), QPicture::exec(), ShaderEffectItem::paint(), QDeclarativeImage::paint(), QDeclarativeBorderImage::paint(), QPaintBufferEngine::penChanged(), qDrawPlainRect(), qt_format_text(), qt_graphicsItem_highlightSelected(), QPainterReplayer::setupTransform(), and QPicturePaintEngine::writeCmdLength().
 {
     return worldTransform();
 }
translate() [1/3]
void QPainter::translate (const QPointF & offset)
Translates the coordinate system by the given offset; i.e.
the given offset is added to points.
See also
setWorldTransform(), {QPainter::Coordinate Transformations}{Coordinate Transformations}
Definition at line 3311 of file qpainter.cpp.
Referenced by _q_paintIntoCache(), QGraphicsItem::boundingRegion(), QSvgUse::bounds(), QSvgFont::draw(), QPixmapBlurFilter::draw(), QSvgUse::draw(), QGraphicsOpacityEffect::draw(), QPainterPrivate::draw_helper(), QCommonStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QSplashScreen::drawContents(), QDeclarativeTextEdit::drawContents(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), drawImage(), drawPicture(), drawPixmap(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QMacStylePrivate::drawTableHeader(), drawTabShape(), QPaintEngine::drawTextItem(), drawTextItemDecoration(), QWidgetPrivate::drawWidget(), QPixmap::fill(), QX11PaintEnginePrivate::fillPolygon_dev(), generateWavyPixmap(), QSvgTinyDocument::mapSourceToTarget(), QTextEditPrivate::paint(), QDeclarativePaintedItem::paint(), QDeclarativeText::paint(), QGraphicsTextItem::paint(), QLCDNumber::paintEvent(), QLabel::paintEvent(), QWhatsThat::paintEvent(), QStaticTextPrivate::paintText(), QGraphicsWidget::paintWindowFrame(), printPage(), QPainterReplayer::process(), QTreeViewPrivate::renderTreeToPixmapForAnimation(), QMacStyle::standardIconImplementation(), and ShaderEffect::updateRenderTargets().
 {
     qreal dx = offset.x();
     qreal dy = offset.y();
 #ifdef QT_DEBUG_DRAW
     if (qt_show_painter_debug_output)
         printf("QPainter::translate(), dx=%f, dy=%f\n", dx, dy);
 #endif
     Q_D(QPainter);
     if (!d->engine) {
         qWarning("QPainter::translate: Painter not active");
         return;
     }
     d->state->worldMatrix.translate(dx, dy);
     d->state->WxF = true;
     d->updateMatrix();
 }
translate() [2/3]
void QPainter::translate (const QPoint & offset) inline
Translates the coordinate system by the given offset.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 980 of file qpainter.h.
 {
     translate(offset.x(), offset.y());
 }
translate() [3/3]
void QPainter::translate (qreal dx, qreal dy) inline
Translates the coordinate system by the vector (dx, dy).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 975 of file qpainter.h.
 {
     translate(QPointF(dx, dy));
 }
viewport()
QRect QPainter::viewport () const
Returns the viewport rectangle.
See also
setViewport(), setViewTransformEnabled()
Definition at line 7844 of file qpainter.cpp.
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::viewport: Painter not active");
         return QRect();
     }
     return QRect(d->state->vx, d->state->vy, d->state->vw, d->state->vh);
 }
viewTransformEnabled()
bool QPainter::viewTransformEnabled () const
Returns true if view transformation is enabled; otherwise returns false.
See also
setViewTransformEnabled(), worldTransform()
Definition at line 7704 of file qpainter.cpp.
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::viewTransformEnabled: Painter not active");
         return false;
     }
     return d->state->VxF;
 }
window()
QRect QPainter::window () const
Returns the window rectangle.
See also
setWindow(), setViewTransformEnabled()
Definition at line 7774 of file qpainter.cpp.
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::window: Painter not active");
         return QRect();
     }
     return QRect(d->state->wx, d->state->wy, d->state->ww, d->state->wh);
 }
worldMatrix()
const QMatrix & QPainter::worldMatrix () const
Returns the world transformation matrix.
Since
4.2
It is advisable to use worldTransform() because worldMatrix() does not preserve the properties of perspective transformations.
See also
{QPainter::Coordinate Transformations}{Coordinate Transformations}, {Coordinate System}
Definition at line 3024 of file qpainter.cpp.
Referenced by matrix(), and qt_plastique_draw_gradient().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::worldMatrix: Painter not active");
         return d->fakeState()->transform.toAffine();
     }
     return d->state->worldMatrix.toAffine();
 }
worldMatrixEnabled()
bool QPainter::worldMatrixEnabled () const
Returns true if world transformation is enabled; otherwise returns false.
Since
4.2
See also
setWorldMatrixEnabled(), worldTransform(), {Coordinate System}
Definition at line 3188 of file qpainter.cpp.
Referenced by matrixEnabled().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::worldMatrixEnabled: Painter not active");
         return false;
     }
     return d->state->WxF;
 }
worldTransform()
const QTransform & QPainter::worldTransform () const
Returns the world transformation matrix.
Definition at line 9652 of file qpainter.cpp.
Referenced by QSvgTransformStyle::apply(), QSvgAnimateTransform::apply(), QGraphicsEffectSource::draw(), QGraphicsShaderEffect::draw(), QSvgTinyDocument::draw(), QPixmapBlurFilter::draw(), QGraphicsColorizeEffect::draw(), QSvgText::draw(), QGraphicsDropShadowEffect::draw(), QGraphicsOpacityEffect::draw(), QGraphicsItemEffectSourcePrivate::draw(), QGraphicsScenePrivate::drawItemHelper(), QGraphicsScene::drawItems(), QGraphicsScenePrivate::drawSubtreeRecursive(), QWidgetPrivate::drawWidget(), QGraphicsView::paintEvent(), ShaderEffect::prepareBufferedDraw(), and QWidgetPrivate::render_helper().
 {
     Q_D(const QPainter);
     if (!d->engine) {
         qWarning("QPainter::worldTransform: Painter not active");
         return d->fakeState()->transform;
     }
     return d->state->worldMatrix;
 }
Friends and Related Functions
Q3Painter
friend class Q3Painter friend
Definition at line 544 of file qpainter.h.
QAlphaPaintEngine
friend class QAlphaPaintEngine friend
Definition at line 564 of file qpainter.h.
QFontEngine
friend class QFontEngine friend
Definition at line 548 of file qpainter.h.
QFontEngineBox
friend class QFontEngineBox friend
Definition at line 549 of file qpainter.h.
QFontEngineFT
friend class QFontEngineFT friend
Definition at line 550 of file qpainter.h.
QFontEngineMac
friend class QFontEngineMac friend
Definition at line 551 of file qpainter.h.
QFontEngineWin
friend class QFontEngineWin friend
Definition at line 552 of file qpainter.h.
QFontEngineXLFD
friend class QFontEngineXLFD friend
Definition at line 553 of file qpainter.h.
QOpenGLPaintEngine
friend class QOpenGLPaintEngine friend
Definition at line 557 of file qpainter.h.
QPaintEngine
friend class QPaintEngine friend
Definition at line 555 of file qpainter.h.
QPaintEngineExPrivate
friend class QPaintEngineExPrivate friend
Definition at line 556 of file qpainter.h.
QPreviewPaintEngine
friend class QPreviewPaintEngine friend
Definition at line 565 of file qpainter.h.
QRasterPaintEngine
friend class QRasterPaintEngine friend
Definition at line 563 of file qpainter.h.
QVGPaintEngine
friend class QVGPaintEngine friend
Definition at line 558 of file qpainter.h.
QWin32PaintEngine
friend class QWin32PaintEngine friend
Definition at line 561 of file qpainter.h.
QWin32PaintEnginePrivate
friend class QWin32PaintEnginePrivate friend
Definition at line 562 of file qpainter.h.
QWSManager
friend class QWSManager friend
Definition at line 554 of file qpainter.h.
QX11PaintEngine
friend class QX11PaintEngine friend
Definition at line 559 of file qpainter.h.
QX11PaintEnginePrivate
friend class QX11PaintEnginePrivate friend
Definition at line 560 of file qpainter.h.
Properties
d_ptr
QScopedPointer<QPainterPrivate> QPainter::d_ptr private
Definition at line 546 of file qpainter.h.
Referenced by QPainterPrivate::attachPainterPrivate(), begin(), clipBoundingRect(), clipPath(), clipRegion(), QPainterPrivate::detachPainterPrivate(), QPainterPrivate::draw_helper(), QVGPaintEngine::fill(), QOpenGLPaintEngine::fill(), QPaintEngineExPrivate::hasClipOperations(), QPainter(), QPaintEngineExPrivate::replayClipOperations(), and ~QPainter().
The documentation for this class was generated from the following files:
/src/gui/painting/qpainter.h
/src/gui/painting/qpainter.cpp