Qt 4.8: QSvgStyleProperty Class Reference
QSvgStyleProperty Class Reference abstract
#include <qsvgstyle_p.h>
Public Types
enum Type {
QUALITY, FILL, VIEWPORT_FILL, FONT,
STROKE, SOLID_COLOR, GRADIENT, TRANSFORM,
ANIMATE_TRANSFORM, ANIMATE_COLOR, OPACITY, COMP_OP
}
Public Functions
virtual void apply (QPainter *p, const QSvgNode *node, QSvgExtraStates &states)=0
virtual void revert (QPainter *p, QSvgExtraStates &states)=0
virtual Type type () const =0
virtual ~QSvgStyleProperty ()
Public Functions inherited from QSvgRefCounted
void deref ()
QSvgRefCounted ()
void ref ()
virtual ~QSvgRefCounted ()
Detailed Description
Definition at line 155 of file qsvgstyle_p.h.
Enumerations
Type
enum QSvgStyleProperty::Type
Enumerator
QUALITY
FILL
VIEWPORT_FILL
FONT
STROKE
SOLID_COLOR
GRADIENT
TRANSFORM
ANIMATE_TRANSFORM
ANIMATE_COLOR
OPACITY
COMP_OP
Definition at line 158 of file qsvgstyle_p.h.
     {
         QUALITY,
         FILL,
         VIEWPORT_FILL,
         FONT,
         STROKE,
         SOLID_COLOR,
         GRADIENT,
         TRANSFORM,
         ANIMATE_TRANSFORM,
         ANIMATE_COLOR,
         OPACITY,
         COMP_OP
     };
Constructors and Destructors
~QSvgStyleProperty()
QSvgStyleProperty::~QSvgStyleProperty () virtual
Definition at line 72 of file qsvgstyle.cpp.
 {
 }
Functions
apply()
virtual void QSvgStyleProperty::apply (QPainter * p, const QSvgNode * node, QSvgExtraStates & states) pure virtual
Implemented in QSvgCompOpStyle, QSvgAnimateColor, QSvgAnimateTransform, QSvgTransformStyle, QSvgStrokeStyle, QSvgFontStyle, QSvgViewportFillStyle, QSvgFillStyle, QSvgOpacityStyle, QSvgQualityStyle, and QSvgFillStyleProperty.
revert()
virtual void QSvgStyleProperty::revert (QPainter * p, QSvgExtraStates & states) pure virtual
Implemented in QSvgCompOpStyle, QSvgAnimateColor, QSvgAnimateTransform, QSvgTransformStyle, QSvgStrokeStyle, QSvgFontStyle, QSvgViewportFillStyle, QSvgFillStyle, QSvgOpacityStyle, QSvgQualityStyle, and QSvgFillStyleProperty.
type()
virtual Type QSvgStyleProperty::type () const pure virtual
Implemented in QSvgCompOpStyle, QSvgAnimateColor, QSvgAnimateTransform, QSvgTransformStyle, QSvgGradientStyle, QSvgSolidColorStyle, QSvgStrokeStyle, QSvgFontStyle, QSvgViewportFillStyle, QSvgFillStyle, QSvgOpacityStyle, and QSvgQualityStyle.
Referenced by QSvgNode::appendStyleProperty(), parseBaseGradient(), parseBrush(), parseFontFaceNameNode(), parseFontFaceNode(), parseGlyphNode(), parseMissingGlyphNode(), parsePen(), parseStopNode(), and QSvgGradientStyle::resolveStops().
The documentation for this class was generated from the following files:
/src/svg/qsvgstyle_p.h
/src/svg/qsvgstyle.cpp