Qt 4.8: QRadialGradient Class Reference
QRadialGradient Class Reference
The QRadialGradient class is used in combination with QBrush to specify a radial gradient brush.
#include <qbrush.h>
Public Functions
QPointF center () const
Returns the center of this radial gradient in logical coordinates.
qreal centerRadius () const
Returns the center radius of this radial gradient in logical coordinates.
QPointF focalPoint () const
Returns the focal point of this radial gradient in logical coordinates.
qreal focalRadius () const
Returns the focal radius of this radial gradient in logical coordinates.
QRadialGradient ()
Constructs a simple radial gradient with the center and focal point at (0, 0) with a radius of 1.
QRadialGradient (const QPointF &center, qreal radius, const QPointF &focalPoint)
Constructs a simple radial gradient with the given center, radius and focalPoint.
QRadialGradient (qreal cx, qreal cy, qreal radius, qreal fx, qreal fy)
Constructs a simple radial gradient with the given center (cx, cy), radius and focal point (fx, fy).
QRadialGradient (const QPointF &center, qreal radius)
Constructs a simple radial gradient with the given center, radius and the focal point in the circle center.
QRadialGradient (qreal cx, qreal cy, qreal radius)
Constructs a simple radial gradient with the center at (cx, cy) and the specified radius.
QRadialGradient (const QPointF &center, qreal centerRadius, const QPointF &focalPoint, qreal focalRadius)
Constructs an extended radial gradient with the given center, centerRadius, focalPoint, and focalRadius.
QRadialGradient (qreal cx, qreal cy, qreal centerRadius, qreal fx, qreal fy, qreal focalRadius)
Constructs an extended radial gradient with the given center (cx, cy), center radius, centerRadius, focal point, (fx, fy), and focal radius focalRadius.
qreal radius () const
Returns the radius of this radial gradient in logical coordinates.
void setCenter (const QPointF &center)
Sets the center of this radial gradient in logical coordinates to center.
void setCenter (qreal x, qreal y)
Sets the center of this radial gradient in logical coordinates to (x, y).
void setCenterRadius (qreal radius)
void setFocalPoint (const QPointF &focalPoint)
Sets the focal point of this radial gradient in logical coordinates to focalPoint.
void setFocalPoint (qreal x, qreal y)
Sets the focal point of this radial gradient in logical coordinates to (x, y).
void setFocalRadius (qreal radius)
void setRadius (qreal radius)
Public Functions inherited from QGradient
CoordinateMode coordinateMode () const
Returns the coordinate mode of this gradient.
InterpolationMode interpolationMode () const
Returns the interpolation mode of this gradient.
bool operator!= (const QGradient &other) const
Returns true if the gradient is the same as the other gradient specified; otherwise returns false.
bool operator== (const QGradient &gradient) const
Returns true if the gradient is the same as the other gradient specified; otherwise returns false.
bool operator== (const QGradient &gradient)
QGradient ()
void setColorAt (qreal pos, const QColor &color)
Creates a stop point at the given position with the given color.
void setCoordinateMode (CoordinateMode mode)
Sets the coordinate mode of this gradient to mode.
void setInterpolationMode (InterpolationMode mode)
Sets the interpolation mode of this gradient to mode.
void setSpread (Spread spread)
Specifies the spread method that should be used for this gradient.
void setStops (const QGradientStops &stops)
Replaces the current set of stop points with the given stopPoints.
Spread spread () const
Returns the spread method use by this gradient.
QGradientStops stops () const
Returns the stop points for this gradient.
Type type () const
Returns the type of gradient.
Additional Inherited Members
Public Types inherited from QGradient
enum CoordinateMode { LogicalMode, StretchToDeviceMode, ObjectBoundingMode }
This enum specifies how gradient coordinates map to the paint device on which the gradient is used.
enum InterpolationMode { ColorInterpolation, ComponentInterpolation }
enum Spread { PadSpread, ReflectSpread, RepeatSpread }
Specifies how the area outside the gradient area should be filled.
enum Type { LinearGradient, RadialGradient, ConicalGradient, NoGradient }
Specifies the type of gradient.
Related Functions inherited from QGradient
QGradientStop
Typedef for QPair<qreal , QColor>.
QGradientStops
Typedef for QVector<QGradientStop>.
Detailed Description
The QRadialGradient class is used in combination with QBrush to specify a radial gradient brush.
Qt supports both simple and extended radial gradients.
Simple radial gradients interpolate colors between a focal point and end points on a circle surrounding it. Extended radial gradients interpolate colors between a focal circle and a center circle. Points outside the cone defined by the two circles will be transparent. For simple radial gradients the focal point is adjusted to lie inside the center circle, whereas the focal point can have any position in an extended radial gradient.
Outside the end points the gradient is either padded, reflected or repeated depending on the currently set QGradient::Spread{spread} method:
QGradient::PadSpread{PadSpread} (default) QGradient::ReflectSpread{ReflectSpread} QGradient::RepeatSpread{RepeatSpread}
The colors in a gradient is defined using stop points of the QGradientStop type, i.e. a position and a color. Use the QGradient::setColorAt() or the QGradient::setStops() function to define the stop points. It is the gradient's complete set of stop points that describes how the gradient area should be filled. If no stop points have been specified, a gradient of black at 0 to white at 1 is used.
In addition to the functions inherited from QGradient, the QRadialGradient class provides the center(), focalPoint() and radius() functions returning the gradient's center, focal point and radius respectively.
See also
QLinearGradient, QConicalGradient, {demos/gradients}{The Gradients Demo}
Definition at line 297 of file qbrush.h.
Constructors and Destructors
QRadialGradient() [1/7]
QRadialGradient::QRadialGradient ()
Constructs a simple radial gradient with the center and focal point at (0, 0) with a radius of 1.
Definition at line 2040 of file qbrush.cpp.
 {
     m_type = RadialGradient;
     m_spread = PadSpread;
     m_data.radial.cx = 0;
     m_data.radial.cy = 0;
     m_data.radial.cradius = 1;
     m_data.radial.fx = 0;
     m_data.radial.fy = 0;
 }
QRadialGradient() [2/7]
QRadialGradient::QRadialGradient (const QPointF & center, qreal radius, const QPointF & focalPoint)
Constructs a simple radial gradient with the given center, radius and focalPoint.
Note
If the given focal point is outside the circle defined by the center point and radius, it will be re-adjusted to lie at a point on the circle where it intersects with the line from center to focalPoint.
See also
QGradient::setColorAt(), QGradient::setStops()
Definition at line 1959 of file qbrush.cpp.
 {
     m_type = RadialGradient;
     m_spread = PadSpread;
     m_data.radial.cx = center.x();
     m_data.radial.cy = center.y();
     m_data.radial.cradius = radius;
     QPointF adapted_focal = qt_radial_gradient_adapt_focal_point(center, radius, focalPoint);
     m_data.radial.fx = adapted_focal.x();
     m_data.radial.fy = adapted_focal.y();
 }
QRadialGradient() [3/7]
QRadialGradient::QRadialGradient (qreal cx, qreal cy, qreal radius, qreal fx, qreal fy)
Constructs a simple radial gradient with the given center (cx, cy), radius and focal point (fx, fy).
Note
If the given focal point is outside the circle defined by the center (cx, cy) and the radius it will be re-adjusted to the intersection between the line from the center to the focal point and the circle.
See also
QGradient::setColorAt(), QGradient::setStops()
Definition at line 2002 of file qbrush.cpp.
 {
     m_type = RadialGradient;
     m_spread = PadSpread;
     m_data.radial.cx = cx;
     m_data.radial.cy = cy;
     m_data.radial.cradius = radius;
     QPointF adapted_focal = qt_radial_gradient_adapt_focal_point(QPointF(cx, cy),
                                                                  radius,
                                                                  QPointF(fx, fy));
     m_data.radial.fx = adapted_focal.x();
     m_data.radial.fy = adapted_focal.y();
 }
QRadialGradient() [4/7]
QRadialGradient::QRadialGradient (const QPointF & center, qreal radius)
Constructs a simple radial gradient with the given center, radius and the focal point in the circle center.
See also
QGradient::setColorAt(), QGradient::setStops()
Definition at line 1978 of file qbrush.cpp.
 {
     m_type = RadialGradient;
     m_spread = PadSpread;
     m_data.radial.cx = center.x();
     m_data.radial.cy = center.y();
     m_data.radial.cradius = radius;
     m_data.radial.fx = center.x();
     m_data.radial.fy = center.y();
 }
QRadialGradient() [5/7]
QRadialGradient::QRadialGradient (qreal cx, qreal cy, qreal radius)
Constructs a simple radial gradient with the center at (cx, cy) and the specified radius.
The focal point lies at the center of the circle.
See also
QGradient::setColorAt(), QGradient::setStops()
Definition at line 2024 of file qbrush.cpp.
 {
     m_type = RadialGradient;
     m_spread = PadSpread;
     m_data.radial.cx = cx;
     m_data.radial.cy = cy;
     m_data.radial.cradius = radius;
     m_data.radial.fx = cx;
     m_data.radial.fy = cy;
 }
QRadialGradient() [6/7]
QRadialGradient::QRadialGradient (const QPointF & center, qreal centerRadius, const QPointF & focalPoint, qreal focalRadius)
Constructs an extended radial gradient with the given center, centerRadius, focalPoint, and focalRadius.
Since
4.8
Definition at line 2060 of file qbrush.cpp.
 {
     m_type = RadialGradient;
     m_spread = PadSpread;
     m_data.radial.cx = center.x();
     m_data.radial.cy = center.y();
     m_data.radial.cradius = centerRadius;
     m_data.radial.fx = focalPoint.x();
     m_data.radial.fy = focalPoint.y();
     setFocalRadius(focalRadius);
 }
QRadialGradient() [7/7]
QRadialGradient::QRadialGradient (qreal cx, qreal cy, qreal centerRadius, qreal fx, qreal fy, qreal focalRadius)
Constructs an extended radial gradient with the given center (cx, cy), center radius, centerRadius, focal point, (fx, fy), and focal radius focalRadius.
Since
4.8
Definition at line 2083 of file qbrush.cpp.
 {
     m_type = RadialGradient;
     m_spread = PadSpread;
     m_data.radial.cx = cx;
     m_data.radial.cy = cy;
     m_data.radial.cradius = centerRadius;
     m_data.radial.fx = fx;
     m_data.radial.fy = fy;
     setFocalRadius(focalRadius);
 }
Functions
center()
QPointF QRadialGradient::center () const
Returns the center of this radial gradient in logical coordinates.
See also
QGradient::stops()
Definition at line 2102 of file qbrush.cpp.
Referenced by qt_isExtendedRadialGradient(), QSvgPaintEngine::saveRadialGradientBrush(), QVGPaintEnginePrivate::setBrush(), QCoreGraphicsPaintEnginePrivate::setFillBrush(), QSpanData::setup(), QGL2PaintEngineExPrivate::updateBrushUniforms(), and QOpenGLPaintEnginePrivate::updateGradient().
 {
     Q_ASSERT(m_type == RadialGradient);
     return QPointF(m_data.radial.cx, m_data.radial.cy);
 }
centerRadius()
qreal QRadialGradient::centerRadius () const
Returns the center radius of this radial gradient in logical coordinates.
Since
4.8
See also
QGradient::stops()
Definition at line 2182 of file qbrush.cpp.
Referenced by QSpanData::setup(), and QGL2PaintEngineExPrivate::updateBrushUniforms().
 {
     Q_ASSERT(m_type == RadialGradient);
     return m_data.radial.cradius;
 }
focalPoint()
QPointF QRadialGradient::focalPoint () const
Returns the focal point of this radial gradient in logical coordinates.
See also
QGradient::stops()
Definition at line 2251 of file qbrush.cpp.
Referenced by qt_isExtendedRadialGradient(), QSvgPaintEngine::saveRadialGradientBrush(), QCoreGraphicsPaintEnginePrivate::setFillBrush(), QSpanData::setup(), QGL2PaintEngineExPrivate::updateBrushUniforms(), and QOpenGLPaintEnginePrivate::updateGradient().
 {
     Q_ASSERT(m_type == RadialGradient);
     return QPointF(m_data.radial.fx, m_data.radial.fy);
 }
focalRadius()
qreal QRadialGradient::focalRadius () const
Returns the focal radius of this radial gradient in logical coordinates.
Since
4.8
See also
QGradient::stops()
Definition at line 2211 of file qbrush.cpp.
Referenced by qt_isExtendedRadialGradient(), QCoreGraphicsPaintEnginePrivate::setFillBrush(), QSpanData::setup(), and QGL2PaintEngineExPrivate::updateBrushUniforms().
 {
     Q_ASSERT(m_type == RadialGradient);
     Q_DUMMY_ACCESSOR
     // mask away low three bits
     union { float f; quint32 i; } u;
     u.i = i & ~0x07;
     return u.f;
 }
radius()
qreal QRadialGradient::radius () const
Returns the radius of this radial gradient in logical coordinates.
Equivalent to centerRadius()
See also
QGradient::stops()
Definition at line 2150 of file qbrush.cpp.
Referenced by qt_isExtendedRadialGradient(), QSvgPaintEngine::saveRadialGradientBrush(), QCoreGraphicsPaintEnginePrivate::setFillBrush(), and QOpenGLPaintEnginePrivate::updateGradient().
 {
     Q_ASSERT(m_type == RadialGradient);
     return m_data.radial.cradius;
 }
setCenter() [1/2]
void QRadialGradient::setCenter (const QPointF & center)
Sets the center of this radial gradient in logical coordinates to center.
Since
4.2
See also
center()
Definition at line 2134 of file qbrush.cpp.
 {
     Q_ASSERT(m_type == RadialGradient);
     m_data.radial.cx = center.x();
     m_data.radial.cy = center.y();
 }
setCenter() [2/2]
void QRadialGradient::setCenter (qreal x, qreal y) inline
Sets the center of this radial gradient in logical coordinates to (x, y).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.2
See also
center()
Definition at line 312 of file qbrush.h.
Referenced by setCenter().
 { setCenter(QPointF(x, y)); }
setCenterRadius()
void QRadialGradient::setCenterRadius (qreal radius)
Since
4.8
Sets the center radius of this radial gradient in logical coordinates to radius
Definition at line 2194 of file qbrush.cpp.
 {
     Q_ASSERT(m_type == RadialGradient);
     m_data.radial.cradius = radius;
 }
setFocalPoint() [1/2]
void QRadialGradient::setFocalPoint (const QPointF & focalPoint)
Sets the focal point of this radial gradient in logical coordinates to focalPoint.
Since
4.2
See also
focalPoint()
Definition at line 2283 of file qbrush.cpp.
 {
     Q_ASSERT(m_type == RadialGradient);
     m_data.radial.fx = focalPoint.x();
     m_data.radial.fy = focalPoint.y();
 }
setFocalPoint() [2/2]
void QRadialGradient::setFocalPoint (qreal x, qreal y) inline
Sets the focal point of this radial gradient in logical coordinates to (x, y).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.2
See also
focalPoint()
Definition at line 316 of file qbrush.h.
Referenced by setFocalPoint().
 { setFocalPoint(QPointF(x, y)); }
setFocalRadius()
void QRadialGradient::setFocalRadius (qreal radius)
Since
4.8
Sets the focal radius of this radial gradient in logical coordinates to radius
Definition at line 2228 of file qbrush.cpp.
 {
     Q_ASSERT(m_type == RadialGradient);
     Q_DUMMY_ACCESSOR
     // Since there's no QGradientData, we only have the dummy void * to
     // store additional data in. The three lowest bits are already
     // taken, thus we cut the three lowest bits from the significand
     // and store the radius as a float.
     union { float f; quint32 i; } u;
     u.f = float(radius);
     // add 0x04 to round up when we drop the three lowest bits
     i |= (u.i + 0x04) & ~0x07;
     dummy = p;
 }
setRadius()
void QRadialGradient::setRadius (qreal radius)
Since
4.2
Sets the radius of this radial gradient in logical coordinates to radius
Equivalent to setCenterRadius()
Definition at line 2165 of file qbrush.cpp.
 {
     Q_ASSERT(m_type == RadialGradient);
     m_data.radial.cradius = radius;
 }
The documentation for this class was generated from the following files:
/src/gui/painting/qbrush.h
/src/gui/painting/qbrush.cpp