Qt 4.8: QDeclarativePropertyChanges Class Reference
QDeclarativePropertyChanges Class Reference
#include <qdeclarativepropertychanges_p.h>
Public Functions
virtual ActionList actions ()
void attachToState ()
void changeExpression (const QString &name, const QString &expression)
void changeValue (const QString &name, const QVariant &value)
bool containsExpression (const QString &name) const
bool containsProperty (const QString &name) const
bool containsValue (const QString &name) const
void detachFromState ()
QString expression (const QString &name) const
bool isExplicit () const
QObject * object () const
QVariant property (const QString &name) const
QDeclarativePropertyChanges ()
void removeProperty (const QString &name)
bool restoreEntryValues () const
void setIsExplicit (bool)
void setObject (QObject *)
void setRestoreEntryValues (bool)
QVariant value (const QString &name) const
~QDeclarativePropertyChanges ()
Public Functions inherited from QDeclarativeStateOperation
QDeclarativeStateOperation (QObject *parent=0)
void setState (QDeclarativeState *state)
QDeclarativeState * state () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
bool explicit
bool restoreEntryValues
QObject * target
Additional Inherited Members
Public Types inherited from QDeclarativeStateOperation
typedef QList< QDeclarativeAction > ActionList
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QDeclarativeStateOperation
QDeclarativeStateOperation (QObjectPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 55 of file qdeclarativepropertychanges_p.h.
Constructors and Destructors
QDeclarativePropertyChanges()
QDeclarativePropertyChanges::QDeclarativePropertyChanges ()
Definition at line 377 of file qdeclarativepropertychanges.cpp.
 : QDeclarativeStateOperation(*(new QDeclarativePropertyChangesPrivate))
 {
 }
~QDeclarativePropertyChanges()
QDeclarativePropertyChanges::~QDeclarativePropertyChanges ()
Definition at line 382 of file qdeclarativepropertychanges.cpp.
 {
     Q_D(QDeclarativePropertyChanges);
     for(int ii = 0; ii < d->expressions.count(); ++ii)
         delete d->expressions.at(ii).expression;
     for(int ii = 0; ii < d->signalReplacements.count(); ++ii)
         delete d->signalReplacements.at(ii);
 }
Functions
actions()
QDeclarativePropertyChanges::ActionList QDeclarativePropertyChanges::actions () virtual
Reimplemented from QDeclarativeStateOperation.
Definition at line 442 of file qdeclarativepropertychanges.cpp.
Referenced by attachToState().
 {
     Q_D(QDeclarativePropertyChanges);
     d->decode();
     ActionList list;
     for (int ii = 0; ii < d->properties.count(); ++ii) {
         QDeclarativeAction a(d->object, d->properties.at(ii).first,
                  qmlContext(this), d->properties.at(ii).second);
         if (a.property.isValid()) {
             a.restore = restoreEntryValues();
             list << a;
         }
     }
     for (int ii = 0; ii < d->signalReplacements.count(); ++ii) {
         QDeclarativeReplaceSignalHandler *handler = d->signalReplacements.at(ii);
         if (handler->property.isValid()) {
             QDeclarativeAction a;
             a.event = handler;
             list << a;
         }
     }
     for (int ii = 0; ii < d->expressions.count(); ++ii) {
         const QString &property = d->expressions.at(ii).name;
         QDeclarativeProperty prop = d->property(property);
         if (prop.isValid()) {
             QDeclarativeAction a;
             a.restore = restoreEntryValues();
             a.property = prop;
             a.fromValue = a.property.read();
             a.specifiedObject = d->object;
             a.specifiedProperty = property;
             if (d->isExplicit) {
                 a.toValue = d->expressions.at(ii).expression->evaluate();
             } else {
                 QDeclarativeExpression *e = d->expressions.at(ii).expression;
                 QDeclarativeBinding::Identifier id = d->expressions.at(ii).id;
                 QDeclarativeBinding *newBinding = id != QDeclarativeBinding::Invalid ? QDeclarativeBinding::createBinding(id, object(), qmlContext(this), e->sourceFile(), e->lineNumber()) : 0;
                 if (!newBinding) {
                     newBinding = new QDeclarativeBinding(e->expression(), object(), qmlContext(this));
                     newBinding->setSourceLocation(e->sourceFile(), e->lineNumber());
                 }
                 newBinding->setTarget(prop);
                 a.toBinding = newBinding;
                 a.deletableToBinding = true;
             }
             list << a;
         }
     }
     return list;
 }
attachToState()
void QDeclarativePropertyChanges::attachToState ()
Definition at line 804 of file qdeclarativepropertychanges.cpp.
 {
     if (state())
         state()->addEntriesToRevertList(actions());
 }
changeExpression()
void QDeclarativePropertyChanges::changeExpression (const QString & name, const QString & expression)
Definition at line 633 of file qdeclarativepropertychanges.cpp.
 {
     Q_D(QDeclarativePropertyChanges);
     typedef QPair<QString, QVariant> PropertyEntry;
     typedef QDeclarativePropertyChangesPrivate::ExpressionChange ExpressionEntry;
     bool hadValue = false;
     QMutableListIterator<PropertyEntry> propertyIterator(d->properties);
     while (propertyIterator.hasNext()) {
         PropertyEntry &entry = propertyIterator.next();
         if (entry.first == name) {
             propertyIterator.remove();
             hadValue = true;
             break;
         }
     }
     QMutableListIterator<ExpressionEntry> expressionIterator(d->expressions);
     while (expressionIterator.hasNext()) {
         const ExpressionEntry &entry = expressionIterator.next();
         if (entry.name == name) {
             entry.expression->setExpression(expression);
             if (state() && state()->isStateActive()) {
                 QDeclarativeAbstractBinding *oldBinding = QDeclarativePropertyPrivate::binding(d->property(name));
                 if (oldBinding) {
                        QDeclarativePropertyPrivate::setBinding(d->property(name), 0);
                        oldBinding->destroy();
                 }
                 QDeclarativeBinding *newBinding = new QDeclarativeBinding(expression, object(), qmlContext(this));
                 newBinding->setTarget(d->property(name));
                 QDeclarativePropertyPrivate::setBinding(d->property(name), newBinding, QDeclarativePropertyPrivate::DontRemoveBinding | QDeclarativePropertyPrivate::BypassInterceptor);
             }
             return;
         }
     }
     QDeclarativeExpression *newExpression = new QDeclarativeExpression(qmlContext(this), d->object, expression);
     expressionIterator.insert(ExpressionEntry(name, QDeclarativeBinding::Invalid, newExpression));
     if (state() && state()->isStateActive()) {
         if (hadValue) {
             QDeclarativeAbstractBinding *oldBinding = QDeclarativePropertyPrivate::binding(d->property(name));
             if (oldBinding) {
                 oldBinding->setEnabled(false, QDeclarativePropertyPrivate::DontRemoveBinding | QDeclarativePropertyPrivate::BypassInterceptor);
                 state()->changeBindingInRevertList(object(), name, oldBinding);
             }
             QDeclarativeBinding *newBinding = new QDeclarativeBinding(expression, object(), qmlContext(this));
             newBinding->setTarget(d->property(name));
             QDeclarativePropertyPrivate::setBinding(d->property(name), newBinding, QDeclarativePropertyPrivate::DontRemoveBinding | QDeclarativePropertyPrivate::BypassInterceptor);
         } else {
             QDeclarativeAction action;
             action.restore = restoreEntryValues();
             action.property = d->property(name);
             action.fromValue = action.property.read();
             action.specifiedObject = object();
             action.specifiedProperty = name;
             if (d->isExplicit) {
                 action.toValue = newExpression->evaluate();
             } else {
                 QDeclarativeBinding *newBinding = new QDeclarativeBinding(newExpression->expression(), object(), qmlContext(this));
                 newBinding->setTarget(d->property(name));
                 action.toBinding = newBinding;
                 action.deletableToBinding = true;
                 state()->addEntryToRevertList(action);
                 QDeclarativeAbstractBinding *oldBinding = QDeclarativePropertyPrivate::binding(action.property);
                 if (oldBinding)
                     oldBinding->setEnabled(false, QDeclarativePropertyPrivate::DontRemoveBinding | QDeclarativePropertyPrivate::BypassInterceptor);
                 QDeclarativePropertyPrivate::setBinding(action.property, newBinding, QDeclarativePropertyPrivate::DontRemoveBinding | QDeclarativePropertyPrivate::BypassInterceptor);
             }
         }
     }
     // what about the signal handler?
 }
changeValue()
void QDeclarativePropertyChanges::changeValue (const QString & name, const QVariant & value)
Definition at line 579 of file qdeclarativepropertychanges.cpp.
 {
     Q_D(QDeclarativePropertyChanges);
     typedef QPair<QString, QVariant> PropertyEntry;
     typedef QDeclarativePropertyChangesPrivate::ExpressionChange ExpressionEntry;
     QMutableListIterator<ExpressionEntry> expressionIterator(d->expressions);
     while (expressionIterator.hasNext()) {
         const ExpressionEntry &entry = expressionIterator.next();
         if (entry.name == name) {
             expressionIterator.remove();
             if (state() && state()->isStateActive()) {
                 QDeclarativeAbstractBinding *oldBinding = QDeclarativePropertyPrivate::binding(d->property(name));
                 if (oldBinding) {
                     QDeclarativePropertyPrivate::setBinding(d->property(name), 0);
                     oldBinding->destroy();
                 }
                 d->property(name).write(value);
             }
             d->properties.append(PropertyEntry(name, value));
             return;
         }
     }
     QMutableListIterator<PropertyEntry> propertyIterator(d->properties);
     while (propertyIterator.hasNext()) {
         PropertyEntry &entry = propertyIterator.next();
         if (entry.first == name) {
             entry.second = value;
             if (state() && state()->isStateActive())
                 d->property(name).write(value);
             return;
         }
     }
     QDeclarativeAction action;
     action.restore = restoreEntryValues();
     action.property = d->property(name);
     action.fromValue = action.property.read();
     action.specifiedObject = object();
     action.specifiedProperty = name;
     action.toValue = value;
     propertyIterator.insert(PropertyEntry(name, value));
     if (state() && state()->isStateActive()) {
         state()->addEntryToRevertList(action);
         QDeclarativeAbstractBinding *oldBinding = QDeclarativePropertyPrivate::binding(action.property);
         if (oldBinding)
             oldBinding->setEnabled(false, QDeclarativePropertyPrivate::DontRemoveBinding | QDeclarativePropertyPrivate::BypassInterceptor);
         d->property(name).write(value);
     }
 }
containsExpression()
bool QDeclarativePropertyChanges::containsExpression (const QString & name) const
Definition at line 558 of file qdeclarativepropertychanges.cpp.
Referenced by containsProperty().
 {
     Q_D(const QDeclarativePropertyChanges);
     typedef QDeclarativePropertyChangesPrivate::ExpressionChange ExpressionEntry;
     QListIterator<ExpressionEntry> expressionIterator(d->expressions);
     while (expressionIterator.hasNext()) {
         const ExpressionEntry &entry = expressionIterator.next();
         if (entry.name == name) {
             return true;
         }
     }
     return false;
 }
containsProperty()
bool QDeclarativePropertyChanges::containsProperty (const QString & name) const
Definition at line 574 of file qdeclarativepropertychanges.cpp.
 {
     return containsValue(name) || containsExpression(name);
 }
containsValue()
bool QDeclarativePropertyChanges::containsValue (const QString & name) const
Definition at line 542 of file qdeclarativepropertychanges.cpp.
Referenced by containsProperty().
 {
     Q_D(const QDeclarativePropertyChanges);
     typedef QPair<QString, QVariant> PropertyEntry;
     QListIterator<PropertyEntry> propertyIterator(d->properties);
     while (propertyIterator.hasNext()) {
         const PropertyEntry &entry = propertyIterator.next();
         if (entry.first == name) {
             return true;
         }
     }
     return false;
 }
detachFromState()
void QDeclarativePropertyChanges::detachFromState ()
Definition at line 798 of file qdeclarativepropertychanges.cpp.
 {
     if (state())
         state()->removeAllEntriesFromRevertList(object());
 }
expression()
QString QDeclarativePropertyChanges::expression (const QString & name) const
Definition at line 782 of file qdeclarativepropertychanges.cpp.
 {
     Q_D(const QDeclarativePropertyChanges);
     typedef QDeclarativePropertyChangesPrivate::ExpressionChange ExpressionEntry;
     QListIterator<ExpressionEntry> expressionIterator(d->expressions);
     while (expressionIterator.hasNext()) {
         const ExpressionEntry &entry = expressionIterator.next();
         if (entry.name == name) {
             return entry.expression->expression();
         }
     }
     return QString();
 }
isExplicit()
bool QDeclarativePropertyChanges::isExplicit () const
Definition at line 530 of file qdeclarativepropertychanges.cpp.
 {
     Q_D(const QDeclarativePropertyChanges);
     return d->isExplicit;
 }
object()
QObject * QDeclarativePropertyChanges::object () const
Definition at line 391 of file qdeclarativepropertychanges.cpp.
Referenced by actions(), changeExpression(), and changeValue().
 {
     Q_D(const QDeclarativePropertyChanges);
     return d->object;
 }
property()
QVariant QDeclarativePropertyChanges::property (const QString & name) const
Definition at line 714 of file qdeclarativepropertychanges.cpp.
Referenced by actions().
 {
     Q_D(const QDeclarativePropertyChanges);
     typedef QPair<QString, QVariant> PropertyEntry;
     typedef QDeclarativePropertyChangesPrivate::ExpressionChange ExpressionEntry;
     QListIterator<PropertyEntry> propertyIterator(d->properties);
     while (propertyIterator.hasNext()) {
         const PropertyEntry &entry = propertyIterator.next();
         if (entry.first == name) {
             return entry.second;
         }
     }
     QListIterator<ExpressionEntry> expressionIterator(d->expressions);
     while (expressionIterator.hasNext()) {
         const ExpressionEntry &entry = expressionIterator.next();
         if (entry.name == name) {
             return QVariant(entry.expression->expression());
         }
     }
     return QVariant();
 }
removeProperty()
void QDeclarativePropertyChanges::removeProperty (const QString & name)
Definition at line 739 of file qdeclarativepropertychanges.cpp.
 {
     Q_D(QDeclarativePropertyChanges);
     typedef QPair<QString, QVariant> PropertyEntry;
     typedef QDeclarativePropertyChangesPrivate::ExpressionChange ExpressionEntry;
     QMutableListIterator<ExpressionEntry> expressionIterator(d->expressions);
     while (expressionIterator.hasNext()) {
         const ExpressionEntry &entry = expressionIterator.next();
         if (entry.name == name) {
             expressionIterator.remove();
             state()->removeEntryFromRevertList(object(), name);
             return;
         }
     }
     QMutableListIterator<PropertyEntry> propertyIterator(d->properties);
     while (propertyIterator.hasNext()) {
         const PropertyEntry &entry = propertyIterator.next();
         if (entry.first == name) {
             propertyIterator.remove();
             state()->removeEntryFromRevertList(object(), name);
             return;
         }
     }
 }
restoreEntryValues()
bool QDeclarativePropertyChanges::restoreEntryValues () const
Referenced by actions(), changeExpression(), changeValue(), and setObject().
setIsExplicit()
void QDeclarativePropertyChanges::setIsExplicit (bool e)
Definition at line 536 of file qdeclarativepropertychanges.cpp.
 {
     Q_D(QDeclarativePropertyChanges);
     d->isExplicit = e;
 }
setObject()
void QDeclarativePropertyChanges::setObject (QObject * o)
Definition at line 397 of file qdeclarativepropertychanges.cpp.
 {
     Q_D(QDeclarativePropertyChanges);
     d->object = o;
 }
setRestoreEntryValues()
void QDeclarativePropertyChanges::setRestoreEntryValues (bool v)
Definition at line 421 of file qdeclarativepropertychanges.cpp.
 {
     Q_D(QDeclarativePropertyChanges);
     d->restore = v;
 }
value()
QVariant QDeclarativePropertyChanges::value (const QString & name) const
Definition at line 766 of file qdeclarativepropertychanges.cpp.
Referenced by changeValue().
 {
     Q_D(const QDeclarativePropertyChanges);
     typedef QPair<QString, QVariant> PropertyEntry;
     QListIterator<PropertyEntry> propertyIterator(d->properties);
     while (propertyIterator.hasNext()) {
         const PropertyEntry &entry = propertyIterator.next();
         if (entry.first == name) {
             return entry.second;
         }
     }
     return QVariant();
 }
Properties
explicit
bool QDeclarativePropertyChanges::explicit private
Definition at line 62 of file qdeclarativepropertychanges_p.h.
restoreEntryValues
bool QDeclarativePropertyChanges::restoreEntryValues private
Definition at line 61 of file qdeclarativepropertychanges_p.h.
target
QObject* QDeclarativePropertyChanges::target private
Definition at line 60 of file qdeclarativepropertychanges_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativepropertychanges_p.h
/src/declarative/util/qdeclarativepropertychanges.cpp