Qt 4.8: QFontEngineWin Class Reference
QFontEngineWin Class Reference
#include <qfontengine_win_p.h>
Public Functions
virtual void addGlyphsToPath (glyph_t *glyphs, QFixedPoint *positions, int nglyphs, QPainterPath *path, QTextItem::RenderFlags flags)
virtual void addOutlineToPath (qreal x, qreal y, const QGlyphLayout &glyphs, QPainterPath *path, QTextItem::RenderFlags flags)
virtual QImage alphaMapForGlyph (glyph_t t)
virtual QImage alphaMapForGlyph (glyph_t, const QTransform &xform)
virtual QImage alphaRGBMapForGlyph (glyph_t t, QFixed subPixelPosition, int margin, const QTransform &xform)
virtual QFixed ascent () const
virtual QFixed averageCharWidth () const
virtual glyph_metrics_t boundingBox (const QGlyphLayout &glyphs)
virtual glyph_metrics_t boundingBox (glyph_t g)
virtual glyph_metrics_t boundingBox (glyph_t g, const QTransform &t)
bool canRender (const QChar *string, int len)
virtual QFontEngine * cloneWithSize (qreal pixelSize) const
virtual QFixed descent () const
virtual QFixed emSquareSize () const
virtual FaceId faceId () const
void getCMap ()
virtual void getGlyphBearings (glyph_t glyph, qreal *leftBearing=0, qreal *rightBearing=0)
int getGlyphIndexes (const QChar *ch, int numChars, QGlyphLayout *glyphs, bool mirrored) const
virtual bool getSfntTableData (uint tag, uchar *buffer, uint *length) const
virtual void getUnscaledGlyph (glyph_t glyph, QPainterPath *path, glyph_metrics_t *metrics)
virtual QFixed leading () const
virtual QFixed lineThickness () const
virtual qreal maxCharWidth () const
virtual qreal minLeftBearing () const
virtual qreal minRightBearing () const
virtual const char * name () const
virtual Properties properties () const
QFontEngineWin (const QString &name, HFONT, bool, LOGFONT)
virtual void recalcAdvances (QGlyphLayout *glyphs, QTextEngine::ShaperFlags) const
HGDIOBJ selectDesignFont () const
virtual bool stringToCMap (const QChar *str, int len, QGlyphLayout *glyphs, int *nglyphs, QTextEngine::ShaperFlags flags) const
virtual int synthesized () const
Type type () const
virtual QFixed xHeight () const
~QFontEngineWin ()
Public Functions inherited from QFontEngine
void addBitmapFontToPath (qreal x, qreal y, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags)
virtual glyph_metrics_t alphaMapBoundingBox (glyph_t glyph, QFixed, const QTransform &matrix, GlyphFormat)
virtual QImage alphaMapForGlyph (glyph_t glyph, QFixed subPixelPosition)
virtual QImage alphaMapForGlyph (glyph_t, QFixed subPixelPosition, const QTransform &t)
virtual void doKerning (QGlyphLayout *, QTextEngine::ShaperFlags) const
void getGlyphPositions (const QGlyphLayout &glyphs, const QTransform &matrix, QTextItem::RenderFlags flags, QVarLengthArray< glyph_t > &glyphs_out, QVarLengthArray< QFixedPoint > &positions)
virtual HB_Error getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed *xpos, HB_Fixed *ypos, hb_uint32 *nPoints)
QByteArray getSfntTable (uint) const
QFontEngineGlyphCache * glyphCache (void *key, QFontEngineGlyphCache::Type type, const QTransform &transform) const
virtual int glyphCount () const
HB_Face harfbuzzFace () const
HB_Font harfbuzzFont () const
void loadKerningPairs (QFixed scalingFactor)
QFontEngine ()
virtual void removeGlyphFromCache (glyph_t)
void setGlyphCache (void *key, QFontEngineGlyphCache *data)
virtual bool supportsSubPixelPositions () const
glyph_metrics_t tightBoundingBox (const QGlyphLayout &glyphs)
virtual QFixed underlinePosition () const
virtual ~QFontEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
FaceId _faceId
QString _name
const unsigned char * cmap
QByteArray cmapTable
QFixed * designAdvances
int designAdvancesSize
QFixed designToDevice
uint hasOutline: 1
HFONT hfont
qreal lbearing
QFixed lineWidth
LOGFONT logfont
int lw
qreal rbearing
uint stockFont: 1
int synthesized_flags
TEXTMETRIC tm
uint ttf: 1
QString uniqueFamilyName
int unitsPerEm
unsigned char * widthCache
uint widthCacheSize
QFixed x_height
Public Variables inherited from QFontEngine
uint cache_cost
int cache_count
QFontDef fontDef
uint fsType: 16
int glyphFormat
HB_Face hbFace
HB_FontRec hbFont
QVector< KernPair > kerning_pairs
QAtomicInt ref
bool symbol
Private Functions
QNativeImage * drawGDIGlyph (HFONT font, glyph_t, int margin, const QTransform &xform, QImage::Format mask_format)
Additional Inherited Members
Public Types inherited from QFontEngine
enum GlyphFormat {
Format_None, Format_Render = Format_None, Format_Mono, Format_A8,
Format_A32
}
enum SynthesizedFlags { SynthesizedItalic = 0x1, SynthesizedBold = 0x2, SynthesizedStretch = 0x4 }
enum Type {
Box, Multi, XLFD, Win,
Mac, Freetype, QPF1, QPF2,
Proxy, S60FontEngine, DirectWrite, TestFontEngine = 0x1000
}
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QFontEngine
static QByteArray convertToPostscriptFontFamilyName (const QByteArray &fontFamily)
static const uchar * getCMap (const uchar *table, uint tableSize, bool *isSymbolFont, int *cmapSize)
static quint32 getTrueTypeGlyphIndex (const uchar *cmap, uint unicode)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QFontEngine
QFixed lastRightBearing (const QGlyphLayout &glyphs, bool round=false)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Protected Functions inherited from QFontEngine
static const QVector< QRgb > & grayPalette ()
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 62 of file qfontengine_win_p.h.
Constructors and Destructors
QFontEngineWin()
QFontEngineWin::QFontEngineWin (const QString & name, HFONT _hfont, bool stockFont, LOGFONT lf)
Definition at line 314 of file qfontengine_win.cpp.
 {
     //qDebug("regular windows font engine created: font='%s', size=%d", name, lf.lfHeight);
     _name = name;
     cmap = 0;
     hfont = _hfont;
     logfont = lf;
     HDC hdc = shared_dc();
     SelectObject(hdc, hfont);
     this->stockFont = stockFont;
     fontDef.pixelSize = -lf.lfHeight;
     lbearing = SHRT_MIN;
     rbearing = SHRT_MIN;
     synthesized_flags = -1;
     lineWidth = -1;
     x_height = -1;
     BOOL res = GetTextMetrics(hdc, &tm);
     fontDef.fixedPitch = !(tm.tmPitchAndFamily & TMPF_FIXED_PITCH);
     if (!res) {
         qErrnoWarning("QFontEngineWin: GetTextMetrics failed");
         ZeroMemory(&tm, sizeof(TEXTMETRIC));
     }
     cache_cost = tm.tmHeight * tm.tmAveCharWidth * 2000;
     getCMap();
     widthCache = 0;
     widthCacheSize = 0;
     designAdvances = 0;
     designAdvancesSize = 0;
 #ifndef Q_WS_WINCE
     if (!resolvedGetCharWidthI)
         resolveGetCharWidthI();
 #endif
 }
~QFontEngineWin()
QFontEngineWin::~QFontEngineWin ()
Definition at line 355 of file qfontengine_win.cpp.
 {
     if (designAdvances)
         free(designAdvances);
     if (widthCache)
         free(widthCache);
     // make sure we aren't by accident still selected
     SelectObject(shared_dc(), (HFONT)GetStockObject(SYSTEM_FONT));
     if (!stockFont) {
         if (!DeleteObject(hfont))
             qErrnoWarning("QFontEngineWin: failed to delete non-stock font...");
     }
 }
Functions
addGlyphsToPath()
void QFontEngineWin::addGlyphsToPath (glyph_t * glyphs, QFixedPoint * positions, int nglyphs, QPainterPath * path, QTextItem::RenderFlags flags) virtual
Reimplemented from QFontEngine.
Definition at line 944 of file qfontengine_win.cpp.
 {
     LOGFONT lf = logfont;
     // The sign must be negative here to make sure we match against character height instead of
     // hinted cell height. This ensures that we get linear matching, and we need this for
     // paths since we later on apply a scaling transform to the glyph outline to get the
     // font at the correct pixel size.
     lf.lfHeight = -unitsPerEm;
     lf.lfWidth = 0;
     HFONT hf = CreateFontIndirect(&lf);
     HDC hdc = shared_dc();
     HGDIOBJ oldfont = SelectObject(hdc, hf);
     for(int i = 0; i < nglyphs; ++i) {
         if (!addGlyphToPath(glyphs[i], positions[i], hdc, path, ttf, /*metric*/0,
                             qreal(fontDef.pixelSize) / unitsPerEm)) {
             // Some windows fonts, like "Modern", are vector stroke
             // fonts, which are reported as TMPF_VECTOR but do not
             // support GetGlyphOutline, and thus we set this bit so
             // that addOutLineToPath can check it and return safely...
             hasOutline = false;
             break;
         }
     }
     DeleteObject(SelectObject(hdc, oldfont));
 }
addOutlineToPath()
void QFontEngineWin::addOutlineToPath (qreal x, qreal y, const QGlyphLayout & glyphs, QPainterPath * path, QTextItem::RenderFlags flags) virtual
Reimplemented from QFontEngine.
Definition at line 972 of file qfontengine_win.cpp.
 {
 #if !defined(Q_WS_WINCE)
     if(tm.tmPitchAndFamily & (TMPF_TRUETYPE | TMPF_VECTOR)) {
         hasOutline = true;
         QFontEngine::addOutlineToPath(x, y, glyphs, path, flags);
         if (hasOutline)  {
             // has_outline is set to false if addGlyphToPath gets
             // false from GetGlyphOutline, meaning its not an outline
             // font.
             return;
         }
     }
 #endif
     QFontEngine::addBitmapFontToPath(x, y, glyphs, path, flags);
 }
alphaMapForGlyph() [1/2]
virtual QImage QFontEngineWin::alphaMapForGlyph (glyph_t glyph) inline virtual
Create a qimage with the alpha values for the glyph. Returns an image indexed_8 with index values ranging from 0=fully transparent to 255=opaque
Reimplemented from QFontEngine.
Definition at line 105 of file qfontengine_win_p.h.
Referenced by alphaMapForGlyph().
 { return alphaMapForGlyph(t, QTransform()); }
alphaMapForGlyph() [2/2]
QImage QFontEngineWin::alphaMapForGlyph (glyph_t glyph, const QTransform & xform) virtual
Reimplemented from QFontEngine.
Definition at line 1193 of file qfontengine_win.cpp.
 {
     HFONT font = hfont;
     if (qt_cleartype_enabled) {
         LOGFONT lf = logfont;
         lf.lfQuality = ANTIALIASED_QUALITY;
         font = CreateFontIndirect(&lf);
     }
     QImage::Format mask_format = QNativeImage::systemFormat();
 #ifndef Q_OS_WINCE
     mask_format = QImage::Format_RGB32;
 #endif
     QNativeImage *mask = drawGDIGlyph(font, glyph, 0, xform, mask_format);
     if (mask == 0)
         return QImage();
     QImage indexed(mask->width(), mask->height(), QImage::Format_Indexed8);
     // ### This part is kinda pointless, but we'll crash later if we don't because some
     // code paths expects there to be colortables for index8-bit...
     QVector<QRgb> colors(256);
     for (int i=0; i<256; ++i)
         colors[i] = qRgba(0, 0, 0, i);
     indexed.setColorTable(colors);
     // Copy data... Cannot use QPainter here as GDI has messed up the
     // Alpha channel of the ni.image pixels...
     for (int y=0; y<mask->height(); ++y) {
         uchar *dest = indexed.scanLine(y);
         if (mask->image.format() == QImage::Format_RGB16) {
             const qint16 *src = (qint16 *) ((const QImage &) mask->image).scanLine(y);
             for (int x=0; x<mask->width(); ++x)
                 dest[x] = 255 - qGray(src[x]);
         } else {
             const uint *src = (uint *) ((const QImage &) mask->image).scanLine(y);
             for (int x=0; x<mask->width(); ++x) {
 #ifdef Q_OS_WINCE
                 dest[x] = 255 - qGray(src[x]);
 #else
                 if (QNativeImage::systemFormat() == QImage::Format_RGB16)
                     dest[x] = 255 - qGray(src[x]);
                 else
                     dest[x] = 255 - (qt_pow_gamma[qGray(src[x])] * 255. / 2047.);
 #endif
             }
         }
     }
     // Cleanup...
     delete mask;
     if (qt_cleartype_enabled) {
         DeleteObject(font);
     }
     return indexed;
 }
alphaRGBMapForGlyph()
QImage QFontEngineWin::alphaRGBMapForGlyph (glyph_t t, QFixed subPixelPosition, int margin, const QTransform & xform) virtual
Reimplemented from QFontEngine.
Definition at line 1254 of file qfontengine_win.cpp.
Referenced by alphaMapForGlyph().
 {
     HFONT font = hfont;
     int contrast;
     SystemParametersInfo(SPI_GETFONTSMOOTHINGCONTRAST, 0, &contrast, 0);
     SystemParametersInfo(SPI_SETFONTSMOOTHINGCONTRAST, 0, (void *) 1000, 0);
     QNativeImage *mask = drawGDIGlyph(font, glyph, margin, t, QImage::Format_RGB32);
     SystemParametersInfo(SPI_SETFONTSMOOTHINGCONTRAST, 0, (void *) contrast, 0);
     if (mask == 0)
         return QImage();
     // Gracefully handle the odd case when the display is 16-bit
     const QImage source = mask->image.depth() == 32
                           ? mask->image
                           : mask->image.convertToFormat(QImage::Format_RGB32);
     QImage rgbMask(mask->width(), mask->height(), QImage::Format_RGB32);
     for (int y=0; y<mask->height(); ++y) {
         uint *dest = (uint *) rgbMask.scanLine(y);
         const uint *src = (uint *) source.scanLine(y);
         for (int x=0; x<mask->width(); ++x) {
             dest[x] = 0xffffffff - (0x00ffffff & src[x]);
         }
     }
     delete mask;
     return rgbMask;
 }
ascent()
QFixed QFontEngineWin::ascent () const virtual
Implements QFontEngine.
Definition at line 596 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
     return tm.tmAscent;
 }
averageCharWidth()
QFixed QFontEngineWin::averageCharWidth () const virtual
Reimplemented from QFontEngine.
Definition at line 621 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
     return tm.tmAveCharWidth;
 }
boundingBox() [1/3]
glyph_metrics_t QFontEngineWin::boundingBox (const QGlyphLayout & glyphs) virtual
Implements QFontEngine.
Definition at line 480 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
     if (glyphs.numGlyphs == 0)
         return glyph_metrics_t();
     QFixed w = 0;
     for (int i = 0; i < glyphs.numGlyphs; ++i)
         w += glyphs.effectiveAdvance(i);
     return glyph_metrics_t(0, -tm.tmAscent, w - lastRightBearing(glyphs), tm.tmHeight, w, 0);
 }
boundingBox() [2/3]
virtual glyph_metrics_t QFontEngineWin::boundingBox (glyph_t g) inline virtual
Implements QFontEngine.
Definition at line 86 of file qfontengine_win_p.h.
Referenced by boundingBox().
 { return boundingBox(g, QTransform()); }
boundingBox() [3/3]
glyph_metrics_t QFontEngineWin::boundingBox (glyph_t g, const QTransform & t) virtual
Reimplemented from QFontEngine.
Definition at line 546 of file qfontengine_win.cpp.
 {
 #ifndef Q_WS_WINCE
     HDC hdc = shared_dc();
     SelectObject(hdc, hfont);
     glyph_metrics_t glyphMetrics;
     bool success = getOutlineMetrics(glyph, t, &glyphMetrics);
     if (!ttf && !success) {
         // Bitmap fonts
         wchar_t ch = glyph;
         ABCFLOAT abc;
         GetCharABCWidthsFloat(hdc, ch, ch, &abc);
         int width = qRound(abc.abcfB);
         return glyph_metrics_t(QFixed::fromReal(abc.abcfA), -tm.tmAscent, width, tm.tmHeight, width, 0).transformed(t);
     }
     return glyphMetrics;
 #else
     HDC hdc = shared_dc();
     HGDIOBJ oldFont = SelectObject(hdc, hfont);
     ABC abc;
     int width;
     int advance;
 #ifdef GWES_MGTT    // true type fonts
     if (GetCharABCWidths(hdc, glyph, glyph, &abc)) {
         width = qAbs(abc.abcA) + abc.abcB + qAbs(abc.abcC);
         advance = abc.abcA + abc.abcB + abc.abcC;
     }
     else
 #endif
 #if defined(GWES_MGRAST) || defined(GWES_MGRAST2)   // raster fonts
     if (GetCharWidth32(hdc, glyph, glyph, &width)) {
         advance = width;
     }
     else
 #endif
     {   // fallback
         width = tm.tmMaxCharWidth;
         advance = width;
     }
     SelectObject(hdc, oldFont);
     return glyph_metrics_t(0, -tm.tmAscent, width, tm.tmHeight, advance, 0).transformed(t);
 #endif
 }
canRender()
bool QFontEngineWin::canRender (const QChar * string, int len) virtual
Implements QFontEngine.
Definition at line 791 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
     if (symbol) {
         for (int i = 0; i < len; ++i) {
             unsigned int uc = getChar(string, i, len);
             if (getTrueTypeGlyphIndex(cmap, uc) == 0) {
                 if (uc < 0x100) {
                     if (getTrueTypeGlyphIndex(cmap, uc + 0xf000) == 0)
                         return false;
                 } else {
                     return false;
                 }
             }
         }
     } else if (ttf) {
         for (int i = 0; i < len; ++i) {
             unsigned int uc = getChar(string, i, len);
             if (getTrueTypeGlyphIndex(cmap, uc) == 0)
                 return false;
         }
     } else {
         while(len--) {
             if (tm.tmFirstChar > string->unicode() || tm.tmLastChar < string->unicode())
                 return false;
         }
     }
     return true;
 }
cloneWithSize()
QFontEngine * QFontEngineWin::cloneWithSize (qreal pixelSize) const virtual
Reimplemented from QFontEngine.
Definition at line 1289 of file qfontengine_win.cpp.
Referenced by alphaMapForGlyph().
 {
     QFontDef request = fontDef;
     QString actualFontName = request.family;
     if (!uniqueFamilyName.isEmpty())
         request.family = uniqueFamilyName;
     request.pixelSize = pixelSize;
     QFontEngine *fontEngine = qt_load_font_engine_win(request);
     if (fontEngine != NULL)
         fontEngine->fontDef.family = actualFontName;
     return fontEngine;
 }
descent()
QFixed QFontEngineWin::descent () const virtual
Implements QFontEngine.
Definition at line 601 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
     // ### we substract 1 to even out the historical +1 in QFontMetrics's
     // ### height=asc+desc+1 equation. Fix in Qt5.
     return tm.tmDescent - 1;
 }
drawGDIGlyph()
QNativeImage * QFontEngineWin::drawGDIGlyph (HFONT font, glyph_t glyph, int margin, const QTransform & xform, QImage::Format mask_format) private
Definition at line 1090 of file qfontengine_win.cpp.
 {
     Q_UNUSED(mask_format)
     glyph_metrics_t gm = boundingBox(glyph);
 //     printf(" -> for glyph %4x\n", glyph);
     int gx = gm.x.toInt();
     int gy = gm.y.toInt();
     int iw = gm.width.toInt();
     int ih = gm.height.toInt();
     if (iw <= 0 || iw <= 0)
         return 0;
     bool has_transformation = t.type() > QTransform::TxTranslate;
 #ifndef Q_WS_WINCE
     unsigned int options = ttf ? ETO_GLYPH_INDEX : 0;
     XFORM xform;
     if (has_transformation) {
         xform.eM11 = t.m11();
         xform.eM12 = t.m12();
         xform.eM21 = t.m21();
         xform.eM22 = t.m22();
         xform.eDx = margin;
         xform.eDy = margin;
         QtHDC qthdc;
         HDC hdc = qthdc.hdc();
         SetGraphicsMode(hdc, GM_ADVANCED);
         SetWorldTransform(hdc, &xform);
         HGDIOBJ old_font = SelectObject(hdc, font);
         int ggo_options = GGO_METRICS | (ttf ? GGO_GLYPH_INDEX : 0);
         GLYPHMETRICS tgm;
         MAT2 mat;
         memset(&mat, 0, sizeof(mat));
         mat.eM11.value = mat.eM22.value = 1;
         if (GetGlyphOutline(hdc, glyph, ggo_options, &tgm, 0, 0, &mat) == GDI_ERROR) {
             qWarning("QWinFontEngine: unable to query transformed glyph metrics...");
             return 0;
         }
         iw = tgm.gmBlackBoxX;
         ih = tgm.gmBlackBoxY;
         xform.eDx -= tgm.gmptGlyphOrigin.x;
         xform.eDy += tgm.gmptGlyphOrigin.y;
         SetGraphicsMode(hdc, GM_COMPATIBLE);
         SelectObject(hdc, old_font);
     }
 #else // else winc
     unsigned int options = 0;
 #ifdef DEBUG
     Q_ASSERT(!has_transformation);
 #else
     Q_UNUSED(has_transformation);
 #endif
 #endif
     QNativeImage *ni = new QNativeImage(iw + 2 * margin + 4,
                                         ih + 2 * margin + 4,
                                         QNativeImage::systemFormat(), !qt_cleartype_enabled);
     /*If cleartype is enabled we use the standard system format even on Windows CE
       and not the special textbuffer format we have to use if cleartype is disabled*/
     ni->image.fill(0xffffffff);
     HDC hdc = ni->hdc;
     SelectObject(hdc, GetStockObject(NULL_BRUSH));
     SelectObject(hdc, GetStockObject(BLACK_PEN));
     SetTextColor(hdc, RGB(0,0,0));
     SetBkMode(hdc, TRANSPARENT);
     SetTextAlign(hdc, TA_BASELINE);
     HGDIOBJ old_font = SelectObject(hdc, font);
 #ifndef Q_OS_WINCE
     if (has_transformation) {
         SetGraphicsMode(hdc, GM_ADVANCED);
         SetWorldTransform(hdc, &xform);
         ExtTextOut(hdc, 0, 0, options, 0, (LPCWSTR) &glyph, 1, 0);
     } else
 #endif
     {
         ExtTextOut(hdc, -gx + margin, -gy + margin, options, 0, (LPCWSTR) &glyph, 1, 0);
     }
     SelectObject(hdc, old_font);
     return ni;
 }
emSquareSize()
QFixed QFontEngineWin::emSquareSize () const virtual
Reimplemented from QFontEngine.
Definition at line 1023 of file qfontengine_win.cpp.
 {
     return unitsPerEm;
 }
faceId()
QFontEngine::FaceId QFontEngineWin::faceId () const virtual
Reimplemented from QFontEngine.
Definition at line 990 of file qfontengine_win.cpp.
 {
     return _faceId;
 }
getCMap()
void QFontEngineWin::getCMap ()
Definition at line 193 of file qfontengine_win.cpp.
Referenced by alphaMapForGlyph().
 {
     ttf = (bool)(tm.tmPitchAndFamily & TMPF_TRUETYPE);
     HDC hdc = shared_dc();
     SelectObject(hdc, hfont);
     bool symb = false;
     if (ttf) {
         cmapTable = getSfntTable(qbswap<quint32>(MAKE_TAG('c', 'm', 'a', 'p')));
         int size = 0;
         cmap = QFontEngine::getCMap(reinterpret_cast<const uchar *>(cmapTable.constData()),
                        cmapTable.size(), &symb, &size);
     }
     if (!cmap) {
         ttf = false;
         symb = false;
     }
     symbol = symb;
     designToDevice = 1;
     _faceId.index = 0;
     if(cmap) {
         OUTLINETEXTMETRIC *otm = getOutlineTextMetric(hdc);
         designToDevice = QFixed((int)otm->otmEMSquare)/int(otm->otmTextMetrics.tmHeight);
         unitsPerEm = otm->otmEMSquare;
         x_height = (int)otm->otmsXHeight;
         loadKerningPairs(designToDevice);
         _faceId.filename = QString::fromWCharArray((wchar_t *)((char *)otm + (quintptr)otm->otmpFullName)).toLatin1();
         lineWidth = otm->otmsUnderscoreSize;
         fsType = otm->otmfsType;
         free(otm);
     } else {
         unitsPerEm = tm.tmHeight;
     }
 }
getGlyphBearings()
void QFontEngineWin::getGlyphBearings (glyph_t glyph, qreal * leftBearing = 0, qreal * rightBearing = 0) virtual
Reimplemented from QFontEngine.
Definition at line 657 of file qfontengine_win.cpp.
Referenced by alphaMapForGlyph().
 {
     HDC hdc = shared_dc();
     SelectObject(hdc, hfont);
 #ifndef Q_WS_WINCE
     if (ttf)
 #endif
     {
         ABC abcWidths;
         GetCharABCWidthsI(hdc, glyph, 1, 0, &abcWidths);
         if (leftBearing)
             *leftBearing = abcWidths.abcA;
         if (rightBearing)
             *rightBearing = abcWidths.abcC;
     }
 #ifndef Q_WS_WINCE
     else {
         QFontEngine::getGlyphBearings(glyph, leftBearing, rightBearing);
     }
 #endif
 }
getGlyphIndexes()
int QFontEngineWin::getGlyphIndexes (const QChar * ch, int numChars, QGlyphLayout * glyphs, bool mirrored) const
Definition at line 238 of file qfontengine_win.cpp.
Referenced by alphaMapForGlyph().
 {
     int i = 0;
     int glyph_pos = 0;
     if (mirrored) {
 #if defined(Q_WS_WINCE)
         {
 #else
         if (symbol) {
             for (; i < numChars; ++i, ++glyph_pos) {
                 unsigned int uc = getChar(str, i, numChars);
                 glyphs->glyphs[glyph_pos] = getTrueTypeGlyphIndex(cmap, uc);
                 if (!glyphs->glyphs[glyph_pos] && uc < 0x100)
                     glyphs->glyphs[glyph_pos] = getTrueTypeGlyphIndex(cmap, uc + 0xf000);
             }
         } else if (ttf) {
             for (; i < numChars; ++i, ++glyph_pos) {
                 unsigned int uc = getChar(str, i, numChars);
                 glyphs->glyphs[glyph_pos] = getTrueTypeGlyphIndex(cmap, QChar::mirroredChar(uc));
             }
         } else {
 #endif
             wchar_t first = tm.tmFirstChar;
             wchar_t last = tm.tmLastChar;
             for (; i < numChars; ++i, ++glyph_pos) {
                 uint ucs = QChar::mirroredChar(getChar(str, i, numChars));
                 if (
 #ifdef Q_WS_WINCE
                     tm.tmFirstChar > 60000 || // see line 375
 #endif
                         ucs >= first && ucs <= last)
                     glyphs->glyphs[glyph_pos] = ucs;
                 else
                     glyphs->glyphs[glyph_pos] = 0;
             }
         }
     } else {
 #if defined(Q_WS_WINCE)
         {
 #else
         if (symbol) {
             for (; i < numChars; ++i, ++glyph_pos) {
                 unsigned int uc = getChar(str, i, numChars);
                 glyphs->glyphs[i] = getTrueTypeGlyphIndex(cmap, uc);
                 if(!glyphs->glyphs[glyph_pos] && uc < 0x100)
                     glyphs->glyphs[glyph_pos] = getTrueTypeGlyphIndex(cmap, uc + 0xf000);
             }
         } else if (ttf) {
             for (; i < numChars; ++i, ++glyph_pos) {
                 unsigned int uc = getChar(str, i, numChars);
                 glyphs->glyphs[glyph_pos] = getTrueTypeGlyphIndex(cmap, uc);
             }
         } else {
 #endif
             wchar_t first = tm.tmFirstChar;
             wchar_t last = tm.tmLastChar;
             for (; i < numChars; ++i, ++glyph_pos) {
                 uint uc = getChar(str, i, numChars);
                 if (
 #ifdef Q_WS_WINCE
                     tm.tmFirstChar > 60000 || // see comment in QFontEngineWin
 #endif
                         uc >= first && uc <= last)
                     glyphs->glyphs[glyph_pos] = uc;
                 else
                     glyphs->glyphs[glyph_pos] = 0;
             }
         }
     }
     glyphs->numGlyphs = glyph_pos;
     return glyph_pos;
 }
getSfntTableData()
bool QFontEngineWin::getSfntTableData (uint tag, uchar * buffer, uint * length) const virtual
Reimplemented from QFontEngine.
Definition at line 1073 of file qfontengine_win.cpp.
 {
     if (!ttf)
         return false;
     HDC hdc = shared_dc();
     SelectObject(hdc, hfont);
     DWORD t = qbswap<quint32>(tag);
     *length = GetFontData(hdc, t, 0, buffer, *length);
     return *length != GDI_ERROR;
 }
getUnscaledGlyph()
void QFontEngineWin::getUnscaledGlyph (glyph_t glyph, QPainterPath * path, glyph_metrics_t * metrics) virtual
Reimplemented from QFontEngine.
Definition at line 1055 of file qfontengine_win.cpp.
 {
     LOGFONT lf = logfont;
     lf.lfHeight = unitsPerEm;
     int flags = synthesized();
     if(flags & SynthesizedItalic)
         lf.lfItalic = false;
     lf.lfWidth = 0;
     HFONT hf = CreateFontIndirect(&lf);
     HDC hdc = shared_dc();
     HGDIOBJ oldfont = SelectObject(hdc, hf);
     QFixedPoint p;
     p.x = 0;
     p.y = 0;
     addGlyphToPath(glyph, p, hdc, path, ttf, metrics);
     DeleteObject(SelectObject(hdc, oldfont));
 }
leading()
QFixed QFontEngineWin::leading () const virtual
Implements QFontEngine.
Definition at line 608 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
     return tm.tmExternalLeading;
 }
lineThickness()
QFixed QFontEngineWin::lineThickness () const virtual
Reimplemented from QFontEngine.
Definition at line 176 of file qfontengine_win.cpp.
 {
     if(lineWidth > 0)
         return lineWidth;
     return QFontEngine::lineThickness();
 }
maxCharWidth()
qreal QFontEngineWin::maxCharWidth () const virtual
Implements QFontEngine.
Definition at line 626 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
     return tm.tmMaxCharWidth;
 }
minLeftBearing()
qreal QFontEngineWin::minLeftBearing () const virtual
Reimplemented from QFontEngine.
Definition at line 683 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
     if (lbearing == SHRT_MIN)
         minRightBearing(); // calculates both
     return lbearing;
 }
minRightBearing()
qreal QFontEngineWin::minRightBearing () const virtual
Reimplemented from QFontEngine.
Definition at line 691 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
 #ifdef Q_WS_WINCE
     if (rbearing == SHRT_MIN) {
         int ml = 0;
         int mr = 0;
         HDC hdc = shared_dc();
         SelectObject(hdc, hfont);
         if (ttf) {
             ABC *abc = 0;
             int n = tm.tmLastChar - tm.tmFirstChar;
             if (n <= max_font_count) {
                 abc = new ABC[n+1];
                 GetCharABCWidths(hdc, tm.tmFirstChar, tm.tmLastChar, abc);
             } else {
                 abc = new ABC[char_table_entries+1];
                 for(int i = 0; i < char_table_entries; i++)
                     GetCharABCWidths(hdc, char_table[i], char_table[i], abc+i);
                 n = char_table_entries;
             }
             ml = abc[0].abcA;
             mr = abc[0].abcC;
             for (int i = 1; i < n; i++) {
                 if (abc[i].abcA + abc[i].abcB + abc[i].abcC != 0) {
                     ml = qMin(ml,abc[i].abcA);
                     mr = qMin(mr,abc[i].abcC);
                 }
             }
             delete [] abc;
         }
         lbearing = ml;
         rbearing = mr;
     }
     return rbearing;
 #else
     if (rbearing == SHRT_MIN) {
         int ml = 0;
         int mr = 0;
         HDC hdc = shared_dc();
         SelectObject(hdc, hfont);
         if (ttf) {
             ABC *abc = 0;
             int n = tm.tmLastChar - tm.tmFirstChar;
             if (n <= max_font_count) {
                 abc = new ABC[n+1];
                 GetCharABCWidths(hdc, tm.tmFirstChar, tm.tmLastChar, abc);
             } else {
                 abc = new ABC[char_table_entries+1];
                 for(int i = 0; i < char_table_entries; i++)
                     GetCharABCWidths(hdc, char_table[i], char_table[i], abc + i);
                 n = char_table_entries;
             }
             ml = abc[0].abcA;
             mr = abc[0].abcC;
             for (int i = 1; i < n; i++) {
                 if (abc[i].abcA + abc[i].abcB + abc[i].abcC != 0) {
                     ml = qMin(ml,abc[i].abcA);
                     mr = qMin(mr,abc[i].abcC);
                 }
             }
             delete [] abc;
         } else {
             ABCFLOAT *abc = 0;
             int n = tm.tmLastChar - tm.tmFirstChar+1;
             if (n <= max_font_count) {
                 abc = new ABCFLOAT[n];
                 GetCharABCWidthsFloat(hdc, tm.tmFirstChar, tm.tmLastChar, abc);
             } else {
                 abc = new ABCFLOAT[char_table_entries];
                 for(int i = 0; i < char_table_entries; i++)
                     GetCharABCWidthsFloat(hdc, char_table[i], char_table[i], abc+i);
                 n = char_table_entries;
             }
             float fml = abc[0].abcfA;
             float fmr = abc[0].abcfC;
             for (int i=1; i<n; i++) {
                 if (abc[i].abcfA + abc[i].abcfB + abc[i].abcfC != 0) {
                     fml = qMin(fml,abc[i].abcfA);
                     fmr = qMin(fmr,abc[i].abcfC);
                 }
             }
             ml = int(fml - 0.9999);
             mr = int(fmr - 0.9999);
             delete [] abc;
         }
         lbearing = ml;
         rbearing = mr;
     }
     return rbearing;
 #endif
 }
name()
const char * QFontEngineWin::name () const virtual
Implements QFontEngine.
Definition at line 786 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
     return 0;
 }
properties()
QFontEngine::Properties QFontEngineWin::properties () const virtual
Reimplemented from QFontEngine.
Definition at line 1028 of file qfontengine_win.cpp.
 {
     LOGFONT lf = logfont;
     lf.lfHeight = unitsPerEm;
     HFONT hf = CreateFontIndirect(&lf);
     HDC hdc = shared_dc();
     HGDIOBJ oldfont = SelectObject(hdc, hf);
     OUTLINETEXTMETRIC *otm = getOutlineTextMetric(hdc);
     Properties p;
     p.emSquare = unitsPerEm;
     p.italicAngle = otm->otmItalicAngle;
     p.postscriptName = QString::fromWCharArray((wchar_t *)((char *)otm + (quintptr)otm->otmpFamilyName)).toLatin1();
     p.postscriptName += QString::fromWCharArray((wchar_t *)((char *)otm + (quintptr)otm->otmpStyleName)).toLatin1();
     p.postscriptName = QFontEngine::convertToPostscriptFontFamilyName(p.postscriptName);
     p.boundingBox = QRectF(otm->otmrcFontBox.left, -otm->otmrcFontBox.top,
                            otm->otmrcFontBox.right - otm->otmrcFontBox.left,
                            otm->otmrcFontBox.top - otm->otmrcFontBox.bottom);
     p.ascent = otm->otmAscent;
     p.descent = -otm->otmDescent;
     p.leading = (int)otm->otmLineGap;
     p.capHeight = 0;
     p.lineWidth = otm->otmsUnderscoreSize;
     free(otm);
     DeleteObject(SelectObject(hdc, oldfont));
     return p;
 }
recalcAdvances()
void QFontEngineWin::recalcAdvances (QGlyphLayout * , QTextEngine::ShaperFlags) const virtual
This is a callback from harfbuzz. The font engine uses the font-system in use to find out the advances of each glyph and set it on the layout.
Reimplemented from QFontEngine.
Definition at line 406 of file qfontengine_win.cpp.
 {
     HGDIOBJ oldFont = 0;
     HDC hdc = shared_dc();
     if (ttf && (flags & QTextEngine::DesignMetrics)) {
         for(int i = 0; i < glyphs->numGlyphs; i++) {
             unsigned int glyph = glyphs->glyphs[i];
             if(int(glyph) >= designAdvancesSize) {
                 int newSize = (glyph + 256) >> 8 << 8;
                 designAdvances = q_check_ptr((QFixed *)realloc(designAdvances,
                             newSize*sizeof(QFixed)));
                 for(int i = designAdvancesSize; i < newSize; ++i)
                     designAdvances[i] = -1000000;
                 designAdvancesSize = newSize;
             }
             if (designAdvances[glyph] < -999999) {
                 if (!oldFont)
                     oldFont = selectDesignFont();
                 int width = 0;
                 calculateTTFGlyphWidth(hdc, glyph, width);
                 designAdvances[glyph] = QFixed(width) / designToDevice;
             }
             glyphs->advances_x[i] = designAdvances[glyph];
             glyphs->advances_y[i] = 0;
         }
         if(oldFont)
             DeleteObject(SelectObject(hdc, oldFont));
     } else {
         for(int i = 0; i < glyphs->numGlyphs; i++) {
             unsigned int glyph = glyphs->glyphs[i];
             glyphs->advances_y[i] = 0;
             if (glyph >= widthCacheSize) {
                 int newSize = (glyph + 256) >> 8 << 8;
                 widthCache = q_check_ptr((unsigned char *)realloc(widthCache,
                             newSize*sizeof(QFixed)));
                 memset(widthCache + widthCacheSize, 0, newSize - widthCacheSize);
                 widthCacheSize = newSize;
             }
             glyphs->advances_x[i] = widthCache[glyph];
             // font-width cache failed
             if (glyphs->advances_x[i] == 0) {
                 int width = 0;
                 if (!oldFont)
                     oldFont = SelectObject(hdc, hfont);
                 if (!ttf) {
                     QChar ch[2] = { ushort(glyph), 0 };
                     int chrLen = 1;
                     if (glyph > 0xffff) {
                         ch[0] = QChar::highSurrogate(glyph);
                         ch[1] = QChar::lowSurrogate(glyph);
                         ++chrLen;
                     }
                     SIZE size = {0, 0};
                     GetTextExtentPoint32(hdc, (wchar_t *)ch, chrLen, &size);
                     width = size.cx;
                 } else {
                     calculateTTFGlyphWidth(hdc, glyph, width);
                 }
                 glyphs->advances_x[i] = width;
                 // if glyph's within cache range, store it for later
                 if (width > 0 && width < 0x100)
                     widthCache[glyph] = width;
             }
         }
         if (oldFont)
             SelectObject(hdc, oldFont);
     }
 }
selectDesignFont()
HGDIOBJ QFontEngineWin::selectDesignFont () const
Definition at line 372 of file qfontengine_win.cpp.
 {
     LOGFONT f = logfont;
     f.lfHeight = unitsPerEm;
     HFONT designFont = CreateFontIndirect(&f);
     return SelectObject(shared_dc(), designFont);
 }
stringToCMap()
bool QFontEngineWin::stringToCMap (const QChar * str, int len, QGlyphLayout * glyphs, int * nglyphs, QTextEngine::ShaperFlags flags) const virtual
Implements QFontEngine.
Definition at line 380 of file qfontengine_win.cpp.
 {
     if (*nglyphs < len) {
         *nglyphs = len;
         return false;
     }
     *nglyphs = getGlyphIndexes(str, len, glyphs, flags & QTextEngine::RightToLeft);
     if (flags & QTextEngine::GlyphIndicesOnly)
         return true;
     recalcAdvances(glyphs, flags);
     return true;
 }
synthesized()
int QFontEngineWin::synthesized () const virtual
Reimplemented from QFontEngine.
Definition at line 999 of file qfontengine_win.cpp.
 {
     if(synthesized_flags == -1) {
         synthesized_flags = 0;
         if(ttf) {
             const DWORD HEAD = MAKE_TAG('h', 'e', 'a', 'd');
             HDC hdc = shared_dc();
             SelectObject(hdc, hfont);
             uchar data[4];
             GetFontData(hdc, HEAD, 44, &data, 4);
             USHORT macStyle = getUShort(data);
             if (tm.tmItalic && !(macStyle & 2))
                 synthesized_flags = SynthesizedItalic;
             if (fontDef.stretch != 100 && ttf)
                 synthesized_flags |= SynthesizedStretch;
             if (tm.tmWeight >= 500 && !(macStyle & 1))
                 synthesized_flags |= SynthesizedBold;
             //qDebug() << "font is" << _name <<
             //    "it=" << (macStyle & 2) << fontDef.style << "flags=" << synthesized_flags;
         }
     }
     return synthesized_flags;
 }
type()
QFontEngine::Type QFontEngineWin::type () const virtual
Implements QFontEngine.
Definition at line 820 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
     return QFontEngine::Win;
 }
xHeight()
QFixed QFontEngineWin::xHeight () const virtual
Reimplemented from QFontEngine.
Definition at line 614 of file qfontengine_win.cpp.
Referenced by boundingBox().
 {
     if(x_height >= 0)
         return x_height;
     return QFontEngine::xHeight();
 }
Properties
_faceId
FaceId QFontEngineWin::_faceId
Definition at line 138 of file qfontengine_win_p.h.
_name
QString QFontEngineWin::_name
Definition at line 122 of file qfontengine_win_p.h.
cmap
const unsigned char* QFontEngineWin::cmap
Definition at line 131 of file qfontengine_win_p.h.
cmapTable
QByteArray QFontEngineWin::cmapTable
Definition at line 132 of file qfontengine_win_p.h.
designAdvances
QFixed* QFontEngineWin::designAdvances mutable
Definition at line 144 of file qfontengine_win_p.h.
designAdvancesSize
int QFontEngineWin::designAdvancesSize mutable
Definition at line 145 of file qfontengine_win_p.h.
designToDevice
QFixed QFontEngineWin::designToDevice
Definition at line 135 of file qfontengine_win_p.h.
hasOutline
uint QFontEngineWin::hasOutline
Definition at line 128 of file qfontengine_win_p.h.
hfont
HFONT QFontEngineWin::hfont
Definition at line 124 of file qfontengine_win_p.h.
Referenced by draw_text_item_win(), QWin32PrintEngine::drawTextItem(), and initFontInfo().
lbearing
qreal QFontEngineWin::lbearing mutable
Definition at line 133 of file qfontengine_win_p.h.
lineWidth
QFixed QFontEngineWin::lineWidth mutable
Definition at line 141 of file qfontengine_win_p.h.
logfont
LOGFONT QFontEngineWin::logfont
Definition at line 125 of file qfontengine_win_p.h.
Referenced by QWin32PrintEngine::drawTextItem().
lw
int QFontEngineWin::lw
Definition at line 130 of file qfontengine_win_p.h.
rbearing
qreal QFontEngineWin::rbearing mutable
Definition at line 134 of file qfontengine_win_p.h.
stockFont
uint QFontEngineWin::stockFont
Definition at line 126 of file qfontengine_win_p.h.
synthesized_flags
int QFontEngineWin::synthesized_flags mutable
Definition at line 140 of file qfontengine_win_p.h.
tm
TEXTMETRIC QFontEngineWin::tm
Definition at line 129 of file qfontengine_win_p.h.
Referenced by QPdfEnginePrivate::drawTextItem(), QPdfBaseEnginePrivate::drawTextItem(), and initFontInfo().
ttf
uint QFontEngineWin::ttf
Definition at line 127 of file qfontengine_win_p.h.
Referenced by draw_text_item_win().
uniqueFamilyName
QString QFontEngineWin::uniqueFamilyName
Definition at line 123 of file qfontengine_win_p.h.
unitsPerEm
int QFontEngineWin::unitsPerEm
Definition at line 136 of file qfontengine_win_p.h.
widthCache
unsigned char* QFontEngineWin::widthCache mutable
Definition at line 142 of file qfontengine_win_p.h.
widthCacheSize
uint QFontEngineWin::widthCacheSize mutable
Definition at line 143 of file qfontengine_win_p.h.
x_height
QFixed QFontEngineWin::x_height
Definition at line 137 of file qfontengine_win_p.h.
The documentation for this class was generated from the following files:
/src/gui/text/qfontengine_win_p.h
/src/gui/text/qfontengine_win.cpp