Qt 4.8: QWinInputContext Class Reference
QWinInputContext Class Reference
#include <qwininputcontext_p.h>
Public Functions
bool composition (LPARAM lparam)
bool endComposition ()
virtual QString identifierName ()
This function must be implemented in any subclasses to return the identifier name of the input method.
virtual bool isComposing () const
This function indicates whether InputMethodStart event had been sent to the current focus widget.
virtual QString language ()
This function must be implemented in any subclasses to return a language code (e.
virtual void mouseHandler (int x, QMouseEvent *event)
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
QWinInputContext (QObject *parent=0)
int reconvertString (RECONVERTSTRING *reconv)
virtual void reset ()
This function can be reimplemented in a subclass to reset the state of the input method.
virtual void setFocusWidget (QWidget *w)
Sets the widget that has an input focus for this input context.
bool startComposition ()
virtual void update ()
This virtual function is called when a state in the focus widget has changed.
virtual ~QWinInputContext ()
Public Functions inherited from QInputContext
virtual QList< QAction * > actions ()
This is a preliminary interface for Qt 4.
virtual bool filterEvent (const QEvent *event)
This function can be reimplemented in a subclass to filter input events.
QWidget * focusWidget () const
Returns the widget that has an input focus for this input context.
virtual QFont font () const
Returns the font of the current input widget.
QInputContext (QObject *parent=0)
Constructs an input context with the given parent.
void sendEvent (const QInputMethodEvent &event)
Sends an input method event specified by event to the current focus widget.
QTextFormat standardFormat (StandardFormat s) const
Returns a QTextFormat object that specifies the format for component s.
virtual void widgetDestroyed (QWidget *w)
This virtual function is called when the specified widget is destroyed.
virtual bool x11FilterEvent (QWidget *keywidget, XEvent *event)
This function may be overridden only if input method is depending on X11 and you need raw XEvent.
virtual ~QInputContext ()
Destroys the input context.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static LRESULT DefWindowProc (HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
static void enable (QWidget *w, bool e)
static void enablePopupChild (QWidget *w, bool e)
static void TranslateMessage (const MSG *msg)
static void updateImeStatus (QWidget *w, bool hasFocus)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Private Functions
void init ()
Properties
bool recursionGuard
Additional Inherited Members
Public Types inherited from QInputContext
enum StandardFormat { PreeditFormat, SelectionFormat }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 76 of file qwininputcontext_p.h.
Constructors and Destructors
QWinInputContext()
QWinInputContext::QWinInputContext (QObject * parent = 0) explicit
Definition at line 215 of file qwininputcontext_win.cpp.
     : QInputContext(parent), recursionGuard(false)
 {
 #ifndef Q_WS_WINCE
     QSysInfo::WinVersion ver = QSysInfo::windowsVersion();
     if (ver & QSysInfo::WV_NT_based  && ver >= QSysInfo::WV_VISTA) {
         // Since the IsValidLanguageGroup/IsValidLocale functions always return true on
         // Vista, check the Keyboard Layouts for enabling RTL.
         UINT nLayouts = GetKeyboardLayoutList(0, 0);
         if (nLayouts) {
             HKL *lpList = new HKL[nLayouts];
             GetKeyboardLayoutList(nLayouts, lpList);
             for (int i = 0; i<(int)nLayouts; i++) {
                 WORD plangid = PRIMARYLANGID((quintptr)lpList[i]);
                 if (plangid == LANG_ARABIC
                     || plangid ==  LANG_HEBREW
                     || plangid ==  LANG_FARSI
 #ifdef LANG_SYRIAC
                     || plangid ==  LANG_SYRIAC
 #endif
                     ) {
                         qt_use_rtl_extensions = true;
                         break;
                 }
             }
             delete []lpList;
         }
     } else {
         // figure out whether a RTL language is installed
         qt_use_rtl_extensions = IsValidLanguageGroup(LGRPID_ARABIC, LGRPID_INSTALLED)
                                 || IsValidLanguageGroup(LGRPID_HEBREW, LGRPID_INSTALLED)
                                 || IsValidLocale(MAKELCID(MAKELANGID(LANG_ARABIC, SUBLANG_DEFAULT), SORT_DEFAULT), LCID_INSTALLED)
                                 || IsValidLocale(MAKELCID(MAKELANGID(LANG_HEBREW, SUBLANG_DEFAULT), SORT_DEFAULT), LCID_INSTALLED)
 #ifdef LANG_SYRIAC
                                 || IsValidLocale(MAKELCID(MAKELANGID(LANG_SYRIAC, SUBLANG_DEFAULT), SORT_DEFAULT), LCID_INSTALLED)
 #endif
                                 || IsValidLocale(MAKELCID(MAKELANGID(LANG_FARSI, SUBLANG_DEFAULT), SORT_DEFAULT), LCID_INSTALLED);
     }
 #else
     qt_use_rtl_extensions = false;
 #endif
     WM_MSIME_MOUSE = RegisterWindowMessage(L"MSIMEMouseOperation");
 }
~QWinInputContext()
QWinInputContext::~QWinInputContext () virtual
Definition at line 260 of file qwininputcontext_win.cpp.
 {
     // release active input method if we have one
     if (aimm) {
         aimmpump->End();
         aimmpump->Release();
         aimm->Deactivate();
         aimm->Release();
         aimm = 0;
         aimmpump = 0;
     }
     delete imeComposition;
     imeComposition = 0;
 }
Functions
composition()
bool QWinInputContext::composition (LPARAM lparam)
Definition at line 536 of file qwininputcontext_win.cpp.
Referenced by QtWndProc().
 {
 #ifdef Q_IME_DEBUG
     QString str;
     if (lParam & GCS_RESULTSTR)
         str += "RESULTSTR ";
     if (lParam & GCS_COMPSTR)
         str += "COMPSTR ";
     if (lParam & GCS_COMPATTR)
         str += "COMPATTR ";
     if (lParam & GCS_CURSORPOS)
         str += "CURSORPOS ";
     if (lParam & GCS_COMPCLAUSE)
         str += "COMPCLAUSE ";
     if (lParam & CS_INSERTCHAR)
        str += "INSERTCHAR ";
     if (lParam & CS_NOMOVECARET)
        str += "NOMOVECARET ";
     qDebug("composition, lParam=(%x) %s imePosition=%d", lParam, str.latin1(), imePosition);
 #endif
     bool result = true;
     if(!lParam)
         // bogus event
         return true;
     QWidget *fw = QApplication::focusWidget();
     if (fw) {
         Q_ASSERT(fw->testAttribute(Qt::WA_WState_Created));
         HIMC imc = getContext(fw->effectiveWinId());
         QInputMethodEvent e;
         if (lParam & (GCS_COMPSTR | GCS_COMPATTR | GCS_CURSORPOS)) {
             if (imePosition == -1)
                 // need to send a start event
                 startComposition();
             // some intermediate composition result
             int selStart, selLength;
             *imeComposition = getString(imc, GCS_COMPSTR, &selStart, &selLength);
             imePosition = getCursorPosition(imc);
             if (lParam & CS_INSERTCHAR  && lParam & CS_NOMOVECARET) {
                 // make korean work correctly. Hope this is correct for all IMEs
                 selStart = 0;
                 selLength = imeComposition->length();
             }
             if(selLength == 0)
                 selStart = 0;
            QList<QInputMethodEvent::Attribute> attrs;
            if (selStart > 0)
                attrs << QInputMethodEvent::Attribute(QInputMethodEvent::TextFormat, 0, selStart,
                                             standardFormat(PreeditFormat));
            if (selLength)
                attrs << QInputMethodEvent::Attribute(QInputMethodEvent::TextFormat, selStart, selLength,
                                             standardFormat(SelectionFormat));
            if (selStart + selLength < imeComposition->length())
                attrs << QInputMethodEvent::Attribute(QInputMethodEvent::TextFormat, selStart + selLength,
                                             imeComposition->length() - selStart - selLength,
                                             standardFormat(PreeditFormat));
            if(imePosition >= 0)
                attrs << QInputMethodEvent::Attribute(QInputMethodEvent::Cursor, imePosition, selLength ? 0 : 1, QVariant());
            e = QInputMethodEvent(*imeComposition, attrs);
         }
         if (lParam & GCS_RESULTSTR) {
             if(imePosition == -1)
                 startComposition();
             // a fixed result, return the converted string
             *imeComposition = getString(imc, GCS_RESULTSTR);
             imePosition = -1;
             e.setCommitString(*imeComposition);
             imeComposition->clear();
         }
         result = qt_sendSpontaneousEvent(fw, &e);
         update();
         releaseContext(fw->effectiveWinId(), imc);
     }
 #ifdef Q_IME_DEBUG
     qDebug("imecomposition: cursor pos at %d, str=%x", imePosition, str[0].unicode());
 #endif
     return result;
 }
DefWindowProc()
LRESULT QWinInputContext::DefWindowProc (HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) static
Definition at line 361 of file qwininputcontext_win.cpp.
Referenced by QtWndProc().
 {
     LRESULT retval;
     if (!aimm || aimm->OnDefWindowProc(hwnd, msg, wParam, lParam, &retval) != S_OK)
     {
         retval = ::DefWindowProc(hwnd, msg, wParam, lParam);
     }
     return retval;
 }
enable()
void QWinInputContext::enable (QWidget * w, bool e) static
Definition at line 727 of file qwininputcontext_win.cpp.
Referenced by enablePopupChild(), and updateImeStatus().
 {
     if(w) {
 #ifdef Q_IME_DEBUG
         qDebug("enable: w=%s, enable = %s", w ? w->className() : "(null)" , e ? "true" : "false");
 #endif
         if (!w->testAttribute(Qt::WA_WState_Created))
             return;
         if(aimm) {
             HIMC oldimc;
             if (!e) {
                 aimm->AssociateContext(w->effectiveWinId(), 0, &oldimc);
                 if (!defaultContext)
                     defaultContext = oldimc;
             } else if (defaultContext) {
                 aimm->AssociateContext(w->effectiveWinId(), defaultContext, &oldimc);
             }
         } else {
             // update ime status on the widget
             QWidget *p = QWidget::find(w->effectiveWinId());
             if (p)
                 enableIme(p, e);
         }
     }
 }
enablePopupChild()
void QWinInputContext::enablePopupChild (QWidget * w, bool e) static
Definition at line 703 of file qwininputcontext_win.cpp.
Referenced by updateImeStatus().
 {
     if (aimm) {
         enable(w, e);
         return;
     }
     if (!w || !isInPopup(w))
         return;
 #ifdef Q_IME_DEBUG
     qDebug("enablePopupChild: w=%s, enable = %s", w ? w->className() : "(null)" , e ? "true" : "false");
 #endif
     QWidget *parent = findParentforPopup(w);
     if (parent) {
         // update ime status of the normal toplevel parent of the popup
         enableIme(parent, e);
     }
     QWidget *toplevel = w->window();
     if (toplevel) {
         // update ime status of the toplevel popup
         enableIme(toplevel, e);
     }
 }
endComposition()
bool QWinInputContext::endComposition ()
Definition at line 438 of file qwininputcontext_win.cpp.
Referenced by QtWndProc().
 {
     QWidget *fw = focusWidget();
 #ifdef Q_IME_DEBUG
     qDebug("endComposition! fw = %s", fw ? fw->className() : "(null)");
 #endif
     bool result = true;
     if(imePosition == -1 || recursionGuard)
         return result;
     // Googles Pinyin Input Method likes to call endComposition again
     // when we call notifyIME with CPS_CANCEL, so protect ourselves
     // against that.
     recursionGuard = true;
     if (fw) {
         Q_ASSERT(fw->testAttribute(Qt::WA_WState_Created));
         HIMC imc = getContext(fw->effectiveWinId());
         notifyIME(imc, NI_COMPOSITIONSTR, CPS_CANCEL, 0);
         releaseContext(fw->effectiveWinId(), imc);
         if(haveCaret) {
             DestroyCaret();
             haveCaret = false;
         }
     }
     if (!fw)
         fw = QApplication::focusWidget();
     if (fw) {
         QInputMethodEvent e;
         result = qt_sendSpontaneousEvent(fw, &e);
     }
     if (imeComposition)
         imeComposition->clear();
     imePosition = -1;
     recursionGuard = false;
     return result;
 }
identifierName()
virtual QString QWinInputContext::identifierName () inline virtual
This function must be implemented in any subclasses to return the identifier name of the input method.
Return value is the name to identify and specify input methods for the input method switching mechanism and so on. The name has to be consistent with QInputContextPlugin::keys(). The name has to consist of ASCII characters only.
There are two different names with different responsibility in the input method domain. This function returns one of them. Another name is called 'display name' that stands for the name for endusers appeared in a menu and so on.
See also
QInputContextPlugin::keys(), QInputContextPlugin::displayName()
Implements QInputContext.
Definition at line 83 of file qwininputcontext_p.h.
 { return QLatin1String("win"); }
init()
void QWinInputContext::init () private
isComposing()
bool QWinInputContext::isComposing () const virtual
This function indicates whether InputMethodStart event had been sent to the current focus widget.
It is ensured that an input context can send InputMethodCompose or InputMethodEnd event safely if this function returned true.
The state is automatically being tracked through sendEvent().
See also
sendEvent()
Implements QInputContext.
Definition at line 768 of file qwininputcontext_win.cpp.
 {
     return imeComposition && !imeComposition->isEmpty();
 }
language()
QString QWinInputContext::language () virtual
This function must be implemented in any subclasses to return a language code (e.
g. "zh_CN", "zh_TW", "zh_HK", "ja", "ko", ...) of the input context. If the input context can handle multiple languages, return the currently used one. The name has to be consistent with QInputContextPlugin::language().
This information will be used by language tagging feature in QInputMethodEvent. It is required to distinguish unified han characters correctly. It enables proper font and character code handling. Suppose CJK-awared multilingual web browser (that automatically modifies fonts in CJK-mixed text) and XML editor (that automatically inserts lang attr).
Implements QInputContext.
Definition at line 795 of file qwininputcontext_win.cpp.
 {
     return QString();
 }
mouseHandler()
void QWinInputContext::mouseHandler (int x, QMouseEvent * event) virtual
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
You can use the function to implement mouse-oriented user interface such as text selection or popup menu for candidate selection.
The x parameter is the offset within the string that was sent with the InputMethodCompose event. The alteration boundary of x is ensured as character boundary of preedit string accurately.
The event parameter is the event that was sent to the editor widget. The event type is QEvent::MouseButtonPress, QEvent::MouseButtonRelease, QEvent::MouseButtonDblClick or QEvent::MouseMove. The event's button and state indicate the kind of operation that was performed.
Reimplemented from QInputContext.
Definition at line 773 of file qwininputcontext_win.cpp.
 {
     if(e->type() != QEvent::MouseButtonPress)
         return;
     if (pos < 0 || pos > imeComposition->length())
         reset();
     // Probably should pass the correct button, but it seems to work fine like this.
     DWORD button = MK_LBUTTON;
     QWidget *fw = focusWidget();
     if (fw) {
         Q_ASSERT(fw->testAttribute(Qt::WA_WState_Created));
         HIMC himc = getContext(fw->effectiveWinId());
         HWND ime_wnd = getDefaultIMEWnd(fw->effectiveWinId());
         SendMessage(ime_wnd, WM_MSIME_MOUSE, MAKELONG(MAKEWORD(button, pos == 0 ? 2 : 1), pos), (LPARAM)himc);
         releaseContext(fw->effectiveWinId(), himc);
     }
     //qDebug("mouseHandler: got value %d pos=%d", ret,pos);
 }
reconvertString()
int QWinInputContext::reconvertString (RECONVERTSTRING * reconv)
Definition at line 800 of file qwininputcontext_win.cpp.
Referenced by QtWndProc().
 {
     QWidget *w = focusWidget();
     if(!w)
         return -1;
     Q_ASSERT(w->testAttribute(Qt::WA_WState_Created));
     QString surroundingText = qvariant_cast<QString>(w->inputMethodQuery(Qt::ImSurroundingText));
     int memSize = sizeof(RECONVERTSTRING)+(surroundingText.length()+1)*sizeof(ushort);
     // If memory is not allocated, return the required size.
     if (!reconv) {
         if (surroundingText.isEmpty())
             return -1;
         else
             return memSize;
     }
     int pos = qvariant_cast<int>(w->inputMethodQuery(Qt::ImCursorPosition));
     // find the word in the surrounding text.
     QTextBoundaryFinder bounds(QTextBoundaryFinder::Word, surroundingText);
     bounds.setPosition(pos);
     if (bounds.isAtBoundary()) {
         if (QTextBoundaryFinder::EndWord == bounds.boundaryReasons())
             bounds.toPreviousBoundary();
     } else {
         bounds.toPreviousBoundary();
     }
     int startPos = bounds.position();
     bounds.toNextBoundary();
     int endPos = bounds.position();
     // select the text, this will be overwritten by following ime events.
     QList<QInputMethodEvent::Attribute> attrs;
     attrs << QInputMethodEvent::Attribute(QInputMethodEvent::Selection, startPos, endPos-startPos, QVariant());
     QInputMethodEvent e(QString(), attrs);
     qt_sendSpontaneousEvent(w, &e);
     reconv->dwSize = memSize;
     reconv->dwVersion = 0;
     reconv->dwStrLen = surroundingText.length();
     reconv->dwStrOffset = sizeof(RECONVERTSTRING);
     reconv->dwCompStrLen = endPos-startPos;
     reconv->dwCompStrOffset = startPos*sizeof(ushort);
     reconv->dwTargetStrLen = reconv->dwCompStrLen;
     reconv->dwTargetStrOffset = reconv->dwCompStrOffset;
     memcpy((char*)(reconv+1), surroundingText.utf16(), surroundingText.length()*sizeof(ushort));
     return memSize;
 }
reset()
void QWinInputContext::reset () virtual
This function can be reimplemented in a subclass to reset the state of the input method.
This function is called by several widgets to reset input state. For example, a text widget call this function before inserting a text to make widget ready to accept a text.
Default implementation is sufficient for simple input method. You can override this function to reset external input method engines in complex input method. In the case, call QInputContext::reset() to ensure proper termination of inputting.
In a reimplementation of reset(), you must not send any QInputMethodEvent containing preedit text. You can only commit string and attributes; otherwise, you risk breaking input state consistency.
Implements QInputContext.
Definition at line 481 of file qwininputcontext_win.cpp.
Referenced by mouseHandler().
 {
     QWidget *fw = focusWidget();
 #ifdef Q_IME_DEBUG
     qDebug("sending accept to focus widget %s", fw ? fw->className() : "(null)");
 #endif
     if (fw && imePosition != -1) {
         QInputMethodEvent e;
         if (imeComposition)
             e.setCommitString(*imeComposition);
          imePosition = -1;
          qt_sendSpontaneousEvent(fw, &e);
     }
     if (imeComposition)
         imeComposition->clear();
     imePosition = -1;
     if (fw) {
         Q_ASSERT(fw->testAttribute(Qt::WA_WState_Created));
         HIMC imc = getContext(fw->effectiveWinId());
         notifyIME(imc, NI_COMPOSITIONSTR, CPS_CANCEL, 0);
         releaseContext(fw->effectiveWinId(), imc);
     }
 }
setFocusWidget()
void QWinInputContext::setFocusWidget (QWidget * widget) virtual
Sets the widget that has an input focus for this input context.
Warning
Ordinary input methods must not call this function directly.
See also
focusWidget()
Reimplemented from QInputContext.
Definition at line 753 of file qwininputcontext_win.cpp.
 {
     QWidget *oldFocus = focusWidget();
     if (oldFocus == w)
         return;
     if (w) {
         QWinInputContext::updateImeStatus(w, true);
     } else {
         if (oldFocus)
             QWinInputContext::updateImeStatus(oldFocus , false);
     }
     QInputContext::setFocusWidget(w);
     update();
 }
startComposition()
bool QWinInputContext::startComposition ()
Definition at line 511 of file qwininputcontext_win.cpp.
Referenced by composition(), and QtWndProc().
 {
 #ifdef Q_IME_DEBUG
     qDebug("startComposition");
 #endif
     if (!imeComposition)
         imeComposition = new QString();
     QWidget *fw = focusWidget();
     if (fw) {
         Q_ASSERT(fw->testAttribute(Qt::WA_WState_Created));
         imePosition = 0;
         haveCaret = CreateCaret(fw->effectiveWinId(), 0, 1, 1);
         HideCaret(fw->effectiveWinId());
         update();
     }
     return fw != 0;
 }
TranslateMessage()
void QWinInputContext::TranslateMessage (const MSG * msg) static
Definition at line 355 of file qwininputcontext_win.cpp.
 {
     if (!aimmpump || aimmpump->OnTranslateMessage(msg) != S_OK)
         ::TranslateMessage(msg);
 }
update()
void QWinInputContext::update () virtual
This virtual function is called when a state in the focus widget has changed.
QInputContext can then use QWidget::inputMethodQuery() to query the new state of the widget.
Reimplemented from QInputContext.
Definition at line 372 of file qwininputcontext_win.cpp.
Referenced by composition(), setFocusWidget(), and startComposition().
 {
     QWidget *w = focusWidget();
     if(!w)
         return;
     Q_ASSERT(w->testAttribute(Qt::WA_WState_Created));
     HIMC imc = getContext(w->effectiveWinId());
     if (!imc)
         return;
     QFont f = qvariant_cast<QFont>(w->inputMethodQuery(Qt::ImFont));
     HFONT hf;
     hf = f.handle();
     LOGFONT lf;
     if (GetObject(hf, sizeof(lf), &lf)) {
         if (aimm)
             aimm->SetCompositionFontW(imc, &lf);
         else
             ImmSetCompositionFont(imc, &lf);
     }
     QRect r = w->inputMethodQuery(Qt::ImMicroFocus).toRect();
     // The ime window positions are based on the WinId with active focus.
     QWidget *imeWnd = QWidget::find(::GetFocus());
     if (imeWnd && !aimm) {
         QPoint pt (r.topLeft());
         pt = w->mapToGlobal(pt);
         pt = imeWnd->mapFromGlobal(pt);
         r.moveTo(pt);
     }
     COMPOSITIONFORM cf;
     // ### need X-like inputStyle config settings
     cf.dwStyle = CFS_FORCE_POSITION;
     cf.ptCurrentPos.x = r.x();
     cf.ptCurrentPos.y = r.y();
     CANDIDATEFORM candf;
     candf.dwIndex = 0;
     candf.dwStyle = CFS_EXCLUDE;
     candf.ptCurrentPos.x = r.x();
     candf.ptCurrentPos.y = r.y() + r.height();
     candf.rcArea.left = r.x();
     candf.rcArea.top = r.y();
     candf.rcArea.right = r.x() + r.width();
     candf.rcArea.bottom = r.y() + r.height();
     if(haveCaret)
         SetCaretPos(r.x(), r.y());
     if (aimm) {
         aimm->SetCompositionWindow(imc, &cf);
         aimm->SetCandidateWindow(imc, &candf);
     } else {
         ImmSetCompositionWindow(imc, &cf);
         ImmSetCandidateWindow(imc, &candf);
     }
     releaseContext(w->effectiveWinId(), imc);
 }
updateImeStatus()
void QWinInputContext::updateImeStatus (QWidget * w, bool hasFocus) static
Definition at line 681 of file qwininputcontext_win.cpp.
Referenced by setFocusWidget().
 {
     if (!w)
         return;
     // It's always the proxy that carries the hints.
     QWidget *focusProxyWidget = w->focusProxy();
     if (!focusProxyWidget)
         focusProxyWidget = w;
     bool e = w->testAttribute(Qt::WA_InputMethodEnabled) && w->isEnabled()
             && !(focusProxyWidget->inputMethodHints() & (Qt::ImhExclusiveInputMask | Qt::ImhHiddenText));
     bool hasIme = e && hasFocus;
 #ifdef Q_IME_DEBUG
     qDebug("%s HasFocus = %d hasIme = %d e = %d ", w->className(), hasFocus, hasIme, e);
 #endif
     if (hasFocus || e) {
         if (isInPopup(w))
             QWinInputContext::enablePopupChild(w, hasIme);
         else
             QWinInputContext::enable(w, hasIme);
     }
 }
Properties
recursionGuard
bool QWinInputContext::recursionGuard private
Definition at line 108 of file qwininputcontext_p.h.
Referenced by endComposition().
The documentation for this class was generated from the following files:
/src/gui/inputmethod/qwininputcontext_p.h
/src/gui/inputmethod/qwininputcontext_win.cpp