Qt 4.8: QDBusAbstractInterface Class Reference
QDBusAbstractInterface Class Reference
The QDBusAbstractInterface class is the base class for all D-Bus interfaces in the QtDBus binding, allowing access to remote interfaces.
#include <qdbusabstractinterface.h>
Public Functions
QDBusPendingCall asyncCall (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusPendingCall asyncCallWithArgumentList (const QString &method, const QList< QVariant > &args)
Places a call to the remote method specified by method on this interface, using args as arguments.
QDBusMessage call (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusMessage call (QDBus::CallMode mode, const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusMessage callWithArgumentList (QDBus::CallMode mode, const QString &method, const QList< QVariant > &args)
Places a call to the remote method specified by method on this interface, using args as arguments.
bool callWithCallback (const QString &method, const QList< QVariant > &args, QObject *receiver, const char *member, const char *errorSlot)
Places a call to the remote method specified by method on this interface, using args as arguments.
bool callWithCallback (const QString &method, const QList< QVariant > &args, QObject *receiver, const char *member)
This function is deprecated.
QDBusConnection connection () const
Returns the connection this interface is assocated with.
QString interface () const
Returns the name of this interface.
bool isValid () const
Returns true if this is a valid reference to a remote object.
QDBusError lastError () const
Returns the error the last operation produced, or an invalid error if the last operation did not produce an error.
QString path () const
Returns the object path that this interface is associated with.
QString service () const
Returns the name of the service this interface is associated with.
void setTimeout (int timeout)
Sets the timeout in milliseconds for all future DBus calls to timeout.
int timeout () const
Returns the current value of the timeout in milliseconds.
virtual ~QDBusAbstractInterface ()
Releases this object's resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void connectNotify (const char *signal)
Catch signal connections.
void disconnectNotify (const char *signal)
Catch signal disconnections.
QDBusMessage internalConstCall (QDBus::CallMode mode, const QString &method, const QList< QVariant > &args=QList< QVariant >()) const
QVariant internalPropGet (const char *propname) const
Get the value of the property propname.
void internalPropSet (const char *propname, const QVariant &value)
Set the value of the property propname to value.
QDBusAbstractInterface (const QString &service, const QString &path, const char *interface, const QDBusConnection &connection, QObject *parent)
This is the constructor called from static classes derived from QDBusAbstractInterface (i.
QDBusAbstractInterface (QDBusAbstractInterfacePrivate &, QObject *parent)
This is the constructor called from QDBusInterface::QDBusInterface.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QDBusAbstractInterface class is the base class for all D-Bus interfaces in the QtDBus binding, allowing access to remote interfaces.
Attention
Module: QtDBus
Since
4.2
Generated-code classes also derive from QDBusAbstractInterface, all methods described here are also valid for generated-code classes. In addition to those described here, generated-code classes provide member functions for the remote methods, which allow for compile-time checking of the correct parameters and return values, as well as property type-matching and signal parameter-matching.
See also
{qdbusxml2cpp.html}{The QDBus compiler}, QDBusInterface
Definition at line 77 of file qdbusabstractinterface.h.
Constructors and Destructors
~QDBusAbstractInterface()
QDBusAbstractInterface::~QDBusAbstractInterface () virtual
Releases this object's resources.
Definition at line 338 of file qdbusabstractinterface.cpp.
 {
 }
QDBusAbstractInterface() [1/2]
QDBusAbstractInterface::QDBusAbstractInterface (const QString & service, const QString & path, const char * interface, const QDBusConnection & con, QObject * parent) protected
This is the constructor called from static classes derived from QDBusAbstractInterface (i.
Warning
This function is not part of the public interface. e., those generated by dbusxml2cpp).
Definition at line 315 of file qdbusabstractinterface.cpp.
     : QDBusAbstractInterfaceBase(*new QDBusAbstractInterfacePrivate(service, path, QString::fromLatin1(interface),
                                                  con, false), parent)
 {
     // keep track of the service owner
     if (d_func()->isValid &&
         d_func()->connection.isConnected()
         && !service.isEmpty()
         && !service.startsWith(QLatin1Char(':')))
         d_func()->connection.connect(QLatin1String(DBUS_SERVICE_DBUS), // service
                                      QString(), // path
                                      QLatin1String(DBUS_INTERFACE_DBUS), // interface
                                      QLatin1String("NameOwnerChanged"),
                                      QStringList() << service,
                                      QString(), //signature
                                      this, SLOT(_q_serviceOwnerChanged(QString,QString,QString)));
 }
QDBusAbstractInterface() [2/2]
QDBusAbstractInterface::QDBusAbstractInterface (QDBusAbstractInterfacePrivate & d, QObject * parent) protected
This is the constructor called from QDBusInterface::QDBusInterface.
Warning
This function is not part of the public interface.
Definition at line 290 of file qdbusabstractinterface.cpp.
     : QDBusAbstractInterfaceBase(d, parent)
 {
     // keep track of the service owner
     if (d.isValid &&
         d.connection.isConnected()
         && !d.service.isEmpty()
         && !d.service.startsWith(QLatin1Char(':')))
         d_func()->connection.connect(QLatin1String(DBUS_SERVICE_DBUS), // service
                                      QString(), // path
                                      QLatin1String(DBUS_INTERFACE_DBUS), // interface
                                      QLatin1String("NameOwnerChanged"),
                                      QStringList() << d.service,
                                      QString(), // signature
                                      this, SLOT(_q_serviceOwnerChanged(QString,QString,QString)));
 }
Functions
asyncCall()
QDBusPendingCall QDBusAbstractInterface::asyncCall (const QString & method, const QVariant & arg1 = QVariant(), const QVariant & arg2 = QVariant(), const QVariant & arg3 = QVariant(), const QVariant & arg4 = QVariant(), const QVariant & arg5 = QVariant(), const QVariant & arg6 = QVariant(), const QVariant & arg7 = QVariant(), const QVariant & arg8 = QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
Since
4.5
The parameters to call are passed on to the remote function via D-Bus as input arguments. The returned QDBusPendingCall object can be used to find out information about the reply.
This function can be used with up to 8 parameters, passed in arguments arg1, arg2, arg3, arg4, arg5, arg6, arg7 and arg8. If you need more than 8 parameters or if you have a variable number of parameters to be passed, use asyncCallWithArgumentList().
It can be used the following way:
QString value = retrieveValue();
QDBusPendingCall pcall = interface->asyncCall(QLatin1String("Process"), value);
QDBusPendingCallWatcher *watcher = new QDBusPendingCallWatcher(pcall, this);
QObject::connect(watcher, SIGNAL(finished(QDBusPendingCallWatcher*)),
                 this, SLOT(callFinishedSlot(QDBusPendingCallWatcher*)));
This example illustrates function calling with 0, 1 and 2 parameters and illustrates different parameter types passed in each (the first call to "ProcessWorkUnicode" will contain one Unicode string, the second call to "ProcessWork" will contain one string and one byte array).
Definition at line 783 of file qdbusabstractinterface.cpp.
Referenced by QNetworkManagerInterface::activateConnection(), QConnmanServiceInterface::connect(), and QNetworkSessionPrivateImpl::do_open().
 {
     QList<QVariant> argList;
     int count = 0 + arg1.isValid() + arg2.isValid() + arg3.isValid() + arg4.isValid() +
                 arg5.isValid() + arg6.isValid() + arg7.isValid() + arg8.isValid();
     switch (count) {
     case 8:
         argList.prepend(arg8);
     case 7:
         argList.prepend(arg7);
     case 6:
         argList.prepend(arg6);
     case 5:
         argList.prepend(arg5);
     case 4:
         argList.prepend(arg4);
     case 3:
         argList.prepend(arg3);
     case 2:
         argList.prepend(arg2);
     case 1:
         argList.prepend(arg1);
     }
     return asyncCallWithArgumentList(method, argList);
 }
asyncCallWithArgumentList()
QDBusPendingCall QDBusAbstractInterface::asyncCallWithArgumentList (const QString & method, const QList< QVariant > & args)
Places a call to the remote method specified by method on this interface, using args as arguments.
Since
4.5 This function returns a QDBusPendingCall object that can be used to track the status of the reply and access its contents once it has arrived.
Normally, you should place calls using asyncCall().
Note
This class or function is threadsafe.
Definition at line 502 of file qdbusabstractinterface.cpp.
Referenced by asyncCall(), QOfonoManagerInterface::getModems(), QOfonoNetworkRegistrationInterface::getOperators(), and QOfonoDataConnectionManagerInterface::getPrimaryContexts().
 {
     Q_D(QDBusAbstractInterface);
     if (!d->isValid || !d->canMakeCalls())
         return QDBusPendingCall::fromError(d->lastError);
     QDBusMessage msg = QDBusMessage::createMethodCall(service(), path(), interface(), method);
     QDBusMessagePrivate::setParametersValidated(msg, true);
     msg.setArguments(args);
     return d->connection.asyncCall(msg, d->timeout);
 }
call() [1/2]
QDBusMessage QDBusAbstractInterface::call (const QString & method, const QVariant & arg1 = QVariant(), const QVariant & arg2 = QVariant(), const QVariant & arg3 = QVariant(), const QVariant & arg4 = QVariant(), const QVariant & arg5 = QVariant(), const QVariant & arg6 = QVariant(), const QVariant & arg7 = QVariant(), const QVariant & arg8 = QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
The parameters to call are passed on to the remote function via D-Bus as input arguments. Output arguments are returned in the QDBusMessage reply. If the reply is an error reply, lastError() will also be set to the contents of the error message.
This function can be used with up to 8 parameters, passed in arguments arg1, arg2, arg3, arg4, arg5, arg6, arg7 and arg8. If you need more than 8 parameters or if you have a variable number of parameters to be passed, use callWithArgumentList().
It can be used the following way:
QString value = retrieveValue();
QDBusMessage reply;
QDBusReply<int> api = interface->call(QLatin1String("GetAPIVersion"));
if (api >= 14)
  reply = interface->call(QLatin1String("ProcessWorkUnicode"), value);
else
  reply = interface->call(QLatin1String("ProcessWork"), QLatin1String("UTF-8"), value.toUtf8());
This example illustrates function calling with 0, 1 and 2 parameters and illustrates different parameter types passed in each (the first call to "ProcessWorkUnicode" will contain one Unicode string, the second call to "ProcessWork" will contain one string and one byte array).
Definition at line 685 of file qdbusabstractinterface.cpp.
Referenced by QIcdEngine::cancelAsyncConfigurationUpdate(), QIcdEngine::cleanup(), QNetworkSessionPrivateImpl::close(), QConnmanManagerInterface::connectService(), QNetworkManagerInterface::deactivateConnection(), QConnmanManagerInterface::disableTechnology(), QConnmanServiceInterface::disconnect(), QConnmanManagerInterface::enableTechnology(), QNetworkManagerInterfaceDeviceWireless::getAccessPoints(), QNetworkManagerInterface::getDevices(), QOfonoManagerInterface::getProperties(), QConnmanManagerInterface::getProperties(), QOfonoModemInterface::getProperties(), QConnmanProfileInterface::getProperties(), QOfonoNetworkRegistrationInterface::getProperties(), QConnmanServiceInterface::getProperties(), QOfonoNetworkOperatorInterface::getProperties(), QOfonoSimInterface::getProperties(), QConnmanTechnologyInterface::getProperties(), QOfonoDataConnectionManagerInterface::getProperties(), QOfonoPrimaryDataContextInterface::getProperties(), QOfonoSmsInterface::getProperties(), QConnmanManagerInterface::getServices(), QNetworkManagerSettingsConnection::getSettings(), QConnmanManagerInterface::getState(), QConnmanManagerInterface::getTechnologies(), QNetworkManagerSettings::listConnections(), QConnmanManagerInterface::lookupService(), QConnmanManagerInterface::registerCounter(), QDBusConnectionInterface::registerService(), QConnmanManagerInterface::releaseSession(), QConnmanServiceInterface::remove(), QConnmanManagerInterface::requestScan(), QConnmanManagerInterface::requestSession(), QIcdEngine::requestUpdate(), QOfonoSmsInterface::sendMessage(), QDBusConnectionInterface::startService(), QNetworkSessionPrivateImpl::stop(), QConnmanManagerInterface::unregisterCounter(), and QDBusConnectionInterface::unregisterService().
 {
     return call(QDBus::AutoDetect, method, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
 }
call() [2/2]
QDBusMessage QDBusAbstractInterface::call (QDBus::CallMode mode, const QString & method, const QVariant & arg1 = QVariant(), const QVariant & arg2 = QVariant(), const QVariant & arg3 = QVariant(), const QVariant & arg4 = QVariant(), const QVariant & arg5 = QVariant(), const QVariant & arg6 = QVariant(), const QVariant & arg7 = QVariant(), const QVariant & arg8 = QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If mode is NoWaitForReply, then this function will return immediately after placing the call, without waiting for a reply from the remote method. Otherwise, mode indicates whether this function should activate the Qt Event Loop while waiting for the reply to arrive.
This function can be used with up to 8 parameters, passed in arguments arg1, arg2, arg3, arg4, arg5, arg6, arg7 and arg8. If you need more than 8 parameters or if you have a variable number of parameters to be passed, use callWithArgumentList().
If this function reenters the Qt event loop in order to wait for the reply, it will exclude user input. During the wait, it may deliver signals and other method calls to your application. Therefore, it must be prepared to handle a reentrancy whenever a call is placed with call().
Definition at line 721 of file qdbusabstractinterface.cpp.
 {
     QList<QVariant> argList;
     int count = 0 + arg1.isValid() + arg2.isValid() + arg3.isValid() + arg4.isValid() +
                 arg5.isValid() + arg6.isValid() + arg7.isValid() + arg8.isValid();
     switch (count) {
     case 8:
         argList.prepend(arg8);
     case 7:
         argList.prepend(arg7);
     case 6:
         argList.prepend(arg6);
     case 5:
         argList.prepend(arg5);
     case 4:
         argList.prepend(arg4);
     case 3:
         argList.prepend(arg3);
     case 2:
         argList.prepend(arg2);
     case 1:
         argList.prepend(arg1);
     }
     return callWithArgumentList(mode, method, argList);
 }
callWithArgumentList()
QDBusMessage QDBusAbstractInterface::callWithArgumentList (QDBus::CallMode mode, const QString & method, const QList< QVariant > & args)
Places a call to the remote method specified by method on this interface, using args as arguments.
This function returns the message that was received as a reply, which can be a normal QDBusMessage::ReplyMessage (indicating success) or QDBusMessage::ErrorMessage (if the call failed). The mode parameter specifies how this call should be placed.
If the call succeeds, lastError() will be cleared; otherwise, it will contain the error this call produced.
Normally, you should place calls using call().
Warning
If you use UseEventLoop, your code must be prepared to deal with any reentrancy: other method calls and signals may be delivered before this function returns, as well as other Qt queued signals and events.
Note
This class or function is threadsafe.
Definition at line 435 of file qdbusabstractinterface.cpp.
Referenced by call(), internalConstCall(), and QOfonoPrimaryDataContextInterface::setProp().
 {
     Q_D(QDBusAbstractInterface);
     if (!d->isValid || !d->canMakeCalls())
         return QDBusMessage::createError(d->lastError);
     QString m = method;
     // split out the signature from the method
     int pos = method.indexOf(QLatin1Char('.'));
     if (pos != -1)
         m.truncate(pos);
     if (mode == QDBus::AutoDetect) {
         // determine if this a sync or async call
         mode = QDBus::Block;
         const QMetaObject *mo = metaObject();
         QByteArray match = m.toLatin1() + '(';
         for (int i = staticMetaObject.methodCount(); i < mo->methodCount(); ++i) {
             QMetaMethod mm = mo->method(i);
             if (QByteArray(mm.signature()).startsWith(match)) {
                 // found a method with the same name as what we're looking for
                 // hopefully, nobody is overloading asynchronous and synchronous methods with
                 // the same name
                 QList<QByteArray> tags = QByteArray(mm.tag()).split(' ');
                 if (tags.contains("Q_NOREPLY"))
                     mode = QDBus::NoBlock;
                 break;
             }
         }
     }
 //    qDebug() << "QDBusAbstractInterface" << "Service" << service() << "Path:" << path();
     QDBusMessage msg = QDBusMessage::createMethodCall(service(), path(), interface(), m);
     QDBusMessagePrivate::setParametersValidated(msg, true);
     msg.setArguments(args);
     QDBusMessage reply = d->connection.call(msg, mode, d->timeout);
     if (thread() == QThread::currentThread())
         d->lastError = reply;       // will clear if reply isn't an error
     // ensure that there is at least one element
     if (reply.arguments().isEmpty())
         reply << QVariant();
     return reply;
 }
callWithCallback() [1/2]
bool QDBusAbstractInterface::callWithCallback (const QString & method, const QList< QVariant > & args, QObject * receiver, const char * returnMethod, const char * errorMethod)
Places a call to the remote method specified by method on this interface, using args as arguments.
This function returns immediately after queueing the call. The reply from the remote function is delivered to the returnMethod on object receiver. If an error occurs, the errorMethod on object receiver is called instead.
This function returns true if the queueing succeeds. It does not indicate that the executed call succeeded. If it fails, the errorMethod is called. If the queueing failed, this function returns false and no slot will be called.
The returnMethod must have as its parameters the types returned by the function call. Optionally, it may have a QDBusMessage parameter as its last or only parameter. The errorMethod must have a QDBusError as its only parameter.
Since
4.3
See also
QDBusError, QDBusMessage
Definition at line 537 of file qdbusabstractinterface.cpp.
Referenced by callWithCallback().
 {
     Q_D(QDBusAbstractInterface);
     if (!d->isValid || !d->canMakeCalls())
         return false;
     QDBusMessage msg = QDBusMessage::createMethodCall(service(),
                                                       path(),
                                                       interface(),
                                                       method);
     QDBusMessagePrivate::setParametersValidated(msg, true);
     msg.setArguments(args);
     d->lastError = 0;
     return d->connection.callWithCallback(msg,
                                           receiver,
                                           returnMethod,
                                           errorMethod,
                                           d->timeout);
 }
callWithCallback() [2/2]
bool QDBusAbstractInterface::callWithCallback (const QString & method, const QList< QVariant > & args, QObject * receiver, const char * slot)
This function is deprecated.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Please use the overloaded version.
Places a call to the remote method specified by method on this interface, using args as arguments. This function returns immediately after queueing the call. The reply from the remote function or any errors emitted by it are delivered to the slot slot on object receiver.
This function returns true if the queueing succeeded: it does not indicate that the call succeeded. If it failed, the slot will be called with an error message. lastError() will not be set under those circumstances.
See also
QDBusError, QDBusMessage
Definition at line 584 of file qdbusabstractinterface.cpp.
 {
     return callWithCallback(method, args, receiver, slot, 0);
 }
connection()
QDBusConnection QDBusAbstractInterface::connection () const
Returns the connection this interface is assocated with.
Definition at line 358 of file qdbusabstractinterface.cpp.
Referenced by QIcdEngine::cancelAsyncConfigurationUpdate(), QOfonoManagerInterface::connectNotify(), QConnmanManagerInterface::connectNotify(), QOfonoModemInterface::connectNotify(), QOfonoNetworkRegistrationInterface::connectNotify(), QOfonoNetworkOperatorInterface::connectNotify(), QOfonoSimInterface::connectNotify(), QOfonoDataConnectionManagerInterface::connectNotify(), QOfonoPrimaryDataContextInterface::connectNotify(), QOfonoSmsInterface::connectNotify(), do_dbus_call(), QDBusAbstractInterface(), QIcdEngine::requestUpdate(), setupDBusInterface(), and QIcdEngine::startListeningStateSignalsForAllConnections().
 {
     return d_func()->connection;
 }
connectNotify()
void QDBusAbstractInterface::connectNotify (const char * signal) protected virtual
Catch signal connections.
Warning
This function is not part of the public interface.
Reimplemented from QObject.
Reimplemented in QOfonoSmsInterface, QOfonoPrimaryDataContextInterface, QConnmanAgentInterface, QOfonoDataConnectionManagerInterface, QConnmanTechnologyInterface, QOfonoSimInterface, QConnmanServiceInterface, QOfonoNetworkOperatorInterface, QOfonoNetworkRegistrationInterface, QConnmanProfileInterface, QOfonoModemInterface, QConnmanManagerInterface, and QOfonoManagerInterface.
Definition at line 599 of file qdbusabstractinterface.cpp.
Referenced by QDBusConnectionInterface::unregisterService().
 {
     // someone connecting to one of our signals
     Q_D(QDBusAbstractInterface);
     if (!d->isValid)
         return;
     // we end up recursing here, so optimize away
     if (qstrcmp(signal + 1, "destroyed(QObject*)") == 0)
         return;
     QDBusConnectionPrivate *conn = d->connectionPrivate();
     if (conn) {
         conn->connectRelay(d->service, d->path, d->interface,
                            this, signal);
     }
 }
disconnectNotify()
void QDBusAbstractInterface::disconnectNotify (const char * signal) protected virtual
Catch signal disconnections.
Warning
This function is not part of the public interface.
Reimplemented from QObject.
Reimplemented in QOfonoSmsInterface, QOfonoPrimaryDataContextInterface, QConnmanAgentInterface, QOfonoDataConnectionManagerInterface, QConnmanTechnologyInterface, QOfonoSimInterface, QConnmanServiceInterface, QOfonoNetworkOperatorInterface, QOfonoNetworkRegistrationInterface, QConnmanProfileInterface, QOfonoModemInterface, QConnmanManagerInterface, and QOfonoManagerInterface.
Definition at line 624 of file qdbusabstractinterface.cpp.
Referenced by QDBusConnectionInterface::unregisterService().
 {
     // someone disconnecting from one of our signals
     Q_D(QDBusAbstractInterface);
     if (!d->isValid)
         return;
     QDBusConnectionPrivate *conn = d->connectionPrivate();
     if (conn)
         conn->disconnectRelay(d->service, d->path, d->interface,
                               this, signal);
 }
interface()
QString QDBusAbstractInterface::interface () const
Returns the name of this interface.
Definition at line 382 of file qdbusabstractinterface.cpp.
Referenced by asyncCallWithArgumentList(), callWithArgumentList(), callWithCallback(), do_dbus_call(), and setupDBusInterface().
 {
     return d_func()->interface;
 }
internalConstCall()
QDBusMessage QDBusAbstractInterface::internalConstCall (QDBus::CallMode mode, const QString & method, const QList< QVariant > & args = QList<QVariant>()) const protected
Warning
This function is not part of the public interface.
Definition at line 821 of file qdbusabstractinterface.cpp.
Referenced by QDBusConnectionInterface::isServiceRegistered(), QDBusConnectionInterface::serviceOwner(), QDBusConnectionInterface::servicePid(), and QDBusConnectionInterface::serviceUid().
 {
     // ### move the code here, and make the other functions call this
     return const_cast<QDBusAbstractInterface*>(this)->callWithArgumentList(mode, method, args);
 }
internalPropGet()
QVariant QDBusAbstractInterface::internalPropGet (const char * propname) const protected
Get the value of the property propname.
Warning
This function is not part of the public interface.
Definition at line 644 of file qdbusabstractinterface.cpp.
 {
     // assume this property exists and is readable
     // we're only called from generated code anyways
     return property(propname);
 }
internalPropSet()
void QDBusAbstractInterface::internalPropSet (const char * propname, const QVariant & value) protected
Set the value of the property propname to value.
Warning
This function is not part of the public interface.
Definition at line 659 of file qdbusabstractinterface.cpp.
 {
     setProperty(propname, value);
 }
isValid()
bool QDBusAbstractInterface::isValid () const
Returns true if this is a valid reference to a remote object.
It returns false if there was an error during the creation of this interface (for instance, if the remote application does not exist).
Note: when dealing with remote objects, it is not always possible to determine if it exists when creating a QDBusInterface.
Definition at line 350 of file qdbusabstractinterface.cpp.
Referenced by QConnmanEngine::connectToId(), QConnmanEngine::connmanAvailable(), QConnmanEngine::disconnectFromId(), QIcdEngine::ensureDBusConnection(), QConnmanManagerInterface::getProperties(), QConnmanServiceInterface::getProperties(), QDBusAbstractInterface(), QNetworkManagerConnectionActive::QNetworkManagerConnectionActive(), QNetworkManagerInterface::QNetworkManagerInterface(), QNetworkManagerInterfaceAccessPoint::QNetworkManagerInterfaceAccessPoint(), QNetworkManagerInterfaceDevice::QNetworkManagerInterfaceDevice(), QNetworkManagerInterfaceDeviceWired::QNetworkManagerInterfaceDeviceWired(), QNetworkManagerInterfaceDeviceWireless::QNetworkManagerInterfaceDeviceWireless(), QNetworkManagerIp4Config::QNetworkManagerIp4Config(), QNetworkManagerSettings::QNetworkManagerSettings(), QDBusInterface::qt_metacall(), and setupDBusInterface().
 {
     return !d_func()->currentOwner.isEmpty();
 }
lastError()
QDBusError QDBusAbstractInterface::lastError () const
Returns the error the last operation produced, or an invalid error if the last operation did not produce an error.
Definition at line 391 of file qdbusabstractinterface.cpp.
Referenced by QDBusInterfacePrivate::metacall().
 {
     return d_func()->lastError;
 }
path()
QString QDBusAbstractInterface::path () const
Returns the object path that this interface is associated with.
Definition at line 374 of file qdbusabstractinterface.cpp.
Referenced by asyncCallWithArgumentList(), callWithArgumentList(), callWithCallback(), QNetworkManagerEngine::connectionFromId(), QOfonoModemInterface::connectNotify(), QConnmanProfileInterface::connectNotify(), QOfonoNetworkRegistrationInterface::connectNotify(), QOfonoNetworkOperatorInterface::connectNotify(), QConnmanServiceInterface::connectNotify(), QOfonoSimInterface::connectNotify(), QConnmanTechnologyInterface::connectNotify(), QOfonoDataConnectionManagerInterface::connectNotify(), QOfonoPrimaryDataContextInterface::connectNotify(), QOfonoSmsInterface::connectNotify(), QNetworkManagerEngine::connectToId(), do_dbus_call(), QNetworkManagerSettingsConnection::getUuid(), QNetworkManagerEngine::hasIdentifier(), QNetworkManagerEngine::newAccessPoint(), QNetworkManagerEngine::newConnection(), QNetworkManagerEngine::parseConnection(), QNetworkManagerEngine::removeAccessPoint(), QNetworkManagerEngine::removeConnection(), setupDBusInterface(), QNetworkManagerEngine::updateAccessPoint(), and QNetworkManagerEngine::updateConnection().
 {
     return d_func()->path;
 }
service()
QString QDBusAbstractInterface::service () const
Returns the name of the service this interface is associated with.
Definition at line 366 of file qdbusabstractinterface.cpp.
Referenced by asyncCallWithArgumentList(), callWithArgumentList(), callWithCallback(), QNetworkManagerEngine::connectionFromId(), QNetworkManagerEngine::connectToId(), do_dbus_call(), QNetworkManagerEngine::newAccessPoint(), QNetworkManagerEngine::newConnection(), QNetworkManagerEngine::removeAccessPoint(), QNetworkManagerEngine::removeConnection(), setupDBusInterface(), QNetworkManagerEngine::updateAccessPoint(), and QNetworkManagerEngine::updateConnection().
 {
     return d_func()->service;
 }
setTimeout()
void QDBusAbstractInterface::setTimeout (int timeout)
Sets the timeout in milliseconds for all future DBus calls to timeout.
-1 means the default DBus timeout (usually 25 seconds).
Since
4.8
Definition at line 402 of file qdbusabstractinterface.cpp.
 {
     d_func()->timeout = timeout;
 }
timeout()
int QDBusAbstractInterface::timeout () const
Returns the current value of the timeout in milliseconds.
-1 means the default DBus timeout (usually 25 seconds).
Since
4.8
Definition at line 413 of file qdbusabstractinterface.cpp.
Referenced by setTimeout().
 {
     return d_func()->timeout;
 }
The documentation for this class was generated from the following files:
/src/dbus/qdbusabstractinterface.h
/src/dbus/qdbusabstractinterface.cpp