Qt 4.8: QStyleSheetStyle Class Reference
QStyleSheetStyle Class Reference
#include <qstylesheetstyle_p.h>
Public Functions
QStyle * baseStyle () const
void clearWidgetFont (QWidget *w) const
void deref ()
void drawComplexControl (ComplexControl cc, const QStyleOptionComplex *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
void drawControl (ControlElement element, const QStyleOption *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
void drawItemPixmap (QPainter *painter, const QRect &rect, int alignment, const QPixmap &pixmap) const
Draws the given pixmap in the specified rectangle, according to the specified alignment, using the provided painter.
void drawItemText (QPainter *painter, const QRect &rect, int alignment, const QPalette &pal, bool enabled, const QString &text, QPalette::ColorRole textRole=QPalette::NoRole) const
Draws the given text in the specified rectangle using the provided painter and palette.
void drawPrimitive (PrimitiveElement pe, const QStyleOption *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
QPixmap generatedIconPixmap (QIcon::Mode iconMode, const QPixmap &pixmap, const QStyleOption *option) const
Reimplemented Function
SubControl hitTestComplexControl (ComplexControl cc, const QStyleOptionComplex *opt, const QPoint &pt, const QWidget *w=0) const
Reimplemented Function
QRect itemPixmapRect (const QRect &rect, int alignment, const QPixmap &pixmap) const
Returns the area within the given rectangle in which to draw the specified pixmap according to the defined alignment.
QRect itemTextRect (const QFontMetrics &metrics, const QRect &rect, int alignment, bool enabled, const QString &text) const
Returns the area within the given rectangle in which to draw the provided text according to the specified font metrics and alignment.
int layoutSpacing (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption *option=0, const QWidget *widget=0) const
int pixelMetric (PixelMetric metric, const QStyleOption *option=0, const QWidget *widget=0) const
Reimplemented Function
void polish (QWidget *widget)
Reimplemented Function
void polish (QApplication *app)
Reimplemented Function
void polish (QPalette &pal)
Reimplemented Function
QStyleSheetStyle (QStyle *baseStyle)
void ref ()
void repolish (QWidget *widget)
void repolish (QApplication *app)
void saveWidgetFont (QWidget *w, const QFont &font) const
QSize sizeFromContents (ContentsType ct, const QStyleOption *opt, const QSize &contentsSize, const QWidget *widget=0) const
Reimplemented Function
QPalette standardPalette () const
Returns the style's standard palette.
QPixmap standardPixmap (StandardPixmap standardPixmap, const QStyleOption *option=0, const QWidget *w=0) const
Reimplemented Function
int styleHint (StyleHint sh, const QStyleOption *opt=0, const QWidget *w=0, QStyleHintReturn *shret=0) const
Reimplemented Function
bool styleSheetPalette (const QWidget *w, const QStyleOption *opt, QPalette *pal)
QRect subControlRect (ComplexControl cc, const QStyleOptionComplex *opt, SubControl sc, const QWidget *w=0) const
Reimplemented Function
QRect subElementRect (SubElement r, const QStyleOption *opt, const QWidget *widget=0) const
Reimplemented Function
void unpolish (QWidget *widget)
Reimplemented Function
void unpolish (QApplication *app)
Reimplemented Function
void updateStyleSheetFont (QWidget *w) const
~QStyleSheetStyle ()
Public Functions inherited from QWindowsStyle
void drawComplexControl (ComplexControl cc, const QStyleOptionComplex *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
void drawControl (ControlElement element, const QStyleOption *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
void drawPrimitive (PrimitiveElement pe, const QStyleOption *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
int pixelMetric (PixelMetric pm, const QStyleOption *option=0, const QWidget *widget=0) const
Reimplemented Function
void polish (QApplication *)
Reimplemented Function
void polish (QWidget *)
Reimplemented Function
void polish (QPalette &)
Reimplemented Function
QWindowsStyle ()
Constructs a QWindowsStyle object.
QSize sizeFromContents (ContentsType ct, const QStyleOption *opt, const QSize &contentsSize, const QWidget *widget=0) const
Reimplemented Function
QPixmap standardPixmap (StandardPixmap standardPixmap, const QStyleOption *opt, const QWidget *widget=0) const
Reimplemented Function
int styleHint (StyleHint hint, const QStyleOption *opt=0, const QWidget *widget=0, QStyleHintReturn *returnData=0) const
Reimplemented Function
QRect subElementRect (SubElement r, const QStyleOption *opt, const QWidget *widget=0) const
Reimplemented Function
void unpolish (QApplication *)
Reimplemented Function
void unpolish (QWidget *)
Reimplemented Function
~QWindowsStyle ()
Destroys the QWindowsStyle object.
Public Functions inherited from QCommonStyle
QCommonStyle ()
Constructs a QCommonStyle.
~QCommonStyle ()
Destroys the style.
Public Functions inherited from QStyle
int combinedLayoutSpacing (QSizePolicy::ControlTypes controls1, QSizePolicy::ControlTypes controls2, Qt::Orientation orientation, QStyleOption *option=0, QWidget *widget=0) const
Returns the spacing that should be used between controls1 and controls2 in a layout.
int layoutSpacing (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption *option=0, const QWidget *widget=0) const
Returns the spacing that should be used between control1 and control2 in a layout.
const QStyle * proxy () const
QStyle ()
Constructs a style object.
QIcon standardIcon (StandardPixmap standardIcon, const QStyleOption *option=0, const QWidget *widget=0) const
Returns an icon for the given standardIcon.
virtual ~QStyle ()
Destroys the style object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
QStyle * base
Static Public Variables
static int numinstances = 0
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots
int layoutSpacingImplementation (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption *option=0, const QWidget *widget=0) const
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *opt=0, const QWidget *widget=0) const
Protected Slots inherited from QWindowsStyle
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *option, const QWidget *widget=0) const
Protected Slots inherited from QCommonStyle
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *opt=0, const QWidget *widget=0) const
Protected Slots inherited from QStyle
int layoutSpacingImplementation (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption *option=0, const QWidget *widget=0) const
This slot is called by layoutSpacing() to determine the spacing that should be used between control1 and control2 in a layout.
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *opt=0, const QWidget *widget=0) const
Returns an icon for the given standardIcon.
Protected Functions
bool event (QEvent *e)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
Protected Functions inherited from QWindowsStyle
bool eventFilter (QObject *o, QEvent *e)
Reimplemented Function
QWindowsStyle (QWindowsStylePrivate &dd)
Constructs a QWindowsStyle object.
void timerEvent (QTimerEvent *event)
Reimplemented Function
Protected Functions inherited from QCommonStyle
QCommonStyle (QCommonStylePrivate &dd)
Protected Functions inherited from QStyle
QStyle (QStylePrivate &dd)
Constructs a style object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Private Types
typedef QWindowsStyle ParentStyle
Private Functions
QSize defaultSize (const QWidget *, QSize, const QRect &, int) const
QCss::StyleSheet getDefaultStyleSheet () const
bool hasStyleRule (const QWidget *w, int part) const
bool initWidget (const QWidget *w) const
Make sure that the cache will be clean by connecting destroyed if needed.
int nativeFrameWidth (const QWidget *)
QRect positionRect (const QWidget *, const QRenderRule &, const QRenderRule &, int, const QRect &, Qt::LayoutDirection) const
QRect positionRect (const QWidget *w, const QRenderRule &rule2, int pe, const QRect &originRect, Qt::LayoutDirection dir) const
QRenderRule renderRule (const QWidget *, int, quint64=0) const
QRenderRule renderRule (const QWidget *, const QStyleOption *, int=0) const
void setGeometry (QWidget *)
void setPalette (QWidget *)
void setProperties (QWidget *)
QVector< QCss::StyleRule > styleRules (const QWidget *w) const
QHash< QStyle::SubControl, QRect > titleBarLayout (const QWidget *w, const QStyleOptionTitleBar *tb) const
void unsetPalette (QWidget *)
Static Private Functions
static bool isNaturalChild (const QWidget *w)
static Qt::Alignment resolveAlignment (Qt::LayoutDirection, Qt::Alignment)
Properties
QCss::Parser parser
int refcount
Friends
class QRenderRule
Additional Inherited Members
Public Types inherited from QStyle
enum ComplexControl {
CC_SpinBox, CC_ComboBox, CC_ScrollBar, CC_Slider,
CC_ToolButton, CC_TitleBar, CC_Q3ListView, CC_Dial,
CC_GroupBox, CC_MdiControls, CC_CustomBase = 0xf0000000
}
This enum describes the available complex controls.
enum ContentsType {
CT_PushButton, CT_CheckBox, CT_RadioButton, CT_ToolButton,
CT_ComboBox, CT_Splitter, CT_Q3DockWindow, CT_ProgressBar,
CT_MenuItem, CT_MenuBarItem, CT_MenuBar, CT_Menu,
CT_TabBarTab, CT_Slider, CT_ScrollBar, CT_Q3Header,
CT_LineEdit, CT_SpinBox, CT_SizeGrip, CT_TabWidget,
CT_DialogButtons, CT_HeaderSection, CT_GroupBox, CT_MdiControls,
CT_ItemViewItem, CT_CustomBase = 0xf0000000
}
This enum describes the available contents types.
enum ControlElement {
CE_PushButton, CE_PushButtonBevel, CE_PushButtonLabel, CE_CheckBox,
CE_CheckBoxLabel, CE_RadioButton, CE_RadioButtonLabel, CE_TabBarTab,
CE_TabBarTabShape, CE_TabBarTabLabel, CE_ProgressBar, CE_ProgressBarGroove,
CE_ProgressBarContents, CE_ProgressBarLabel, CE_MenuItem, CE_MenuScroller,
CE_MenuVMargin, CE_MenuHMargin, CE_MenuTearoff, CE_MenuEmptyArea,
CE_MenuBarItem, CE_MenuBarEmptyArea, CE_ToolButtonLabel, CE_Header,
CE_HeaderSection, CE_HeaderLabel, CE_Q3DockWindowEmptyArea, CE_ToolBoxTab,
CE_SizeGrip, CE_Splitter, CE_RubberBand, CE_DockWidgetTitle,
CE_ScrollBarAddLine, CE_ScrollBarSubLine, CE_ScrollBarAddPage, CE_ScrollBarSubPage,
CE_ScrollBarSlider, CE_ScrollBarFirst, CE_ScrollBarLast, CE_FocusFrame,
CE_ComboBoxLabel, CE_ToolBar, CE_ToolBoxTabShape, CE_ToolBoxTabLabel,
CE_HeaderEmptyArea, CE_ColumnViewGrip, CE_ItemViewItem, CE_ShapedFrame,
CE_CustomBase = 0xf0000000
}
This enum represents a control element.
enum PixelMetric {
PM_ButtonMargin, PM_ButtonDefaultIndicator, PM_MenuButtonIndicator, PM_ButtonShiftHorizontal,
PM_ButtonShiftVertical, PM_DefaultFrameWidth, PM_SpinBoxFrameWidth, PM_ComboBoxFrameWidth,
PM_MaximumDragDistance, PM_ScrollBarExtent, PM_ScrollBarSliderMin, PM_SliderThickness,
PM_SliderControlThickness, PM_SliderLength, PM_SliderTickmarkOffset, PM_SliderSpaceAvailable,
PM_DockWidgetSeparatorExtent, PM_DockWidgetHandleExtent, PM_DockWidgetFrameWidth, PM_TabBarTabOverlap,
PM_TabBarTabHSpace, PM_TabBarTabVSpace, PM_TabBarBaseHeight, PM_TabBarBaseOverlap,
PM_ProgressBarChunkWidth, PM_SplitterWidth, PM_TitleBarHeight, PM_MenuScrollerHeight,
PM_MenuHMargin, PM_MenuVMargin, PM_MenuPanelWidth, PM_MenuTearoffHeight,
PM_MenuDesktopFrameWidth, PM_MenuBarPanelWidth, PM_MenuBarItemSpacing, PM_MenuBarVMargin,
PM_MenuBarHMargin, PM_IndicatorWidth, PM_IndicatorHeight, PM_ExclusiveIndicatorWidth,
PM_ExclusiveIndicatorHeight, PM_CheckListButtonSize, PM_CheckListControllerSize, PM_DialogButtonsSeparator,
PM_DialogButtonsButtonWidth, PM_DialogButtonsButtonHeight, PM_MdiSubWindowFrameWidth, PM_MDIFrameWidth = PM_MdiSubWindowFrameWidth,
PM_MdiSubWindowMinimizedWidth, PM_MDIMinimizedWidth = PM_MdiSubWindowMinimizedWidth, PM_HeaderMargin, PM_HeaderMarkSize,
PM_HeaderGripMargin, PM_TabBarTabShiftHorizontal, PM_TabBarTabShiftVertical, PM_TabBarScrollButtonWidth,
PM_ToolBarFrameWidth, PM_ToolBarHandleExtent, PM_ToolBarItemSpacing, PM_ToolBarItemMargin,
PM_ToolBarSeparatorExtent, PM_ToolBarExtensionExtent, PM_SpinBoxSliderHeight, PM_DefaultTopLevelMargin,
PM_DefaultChildMargin, PM_DefaultLayoutSpacing, PM_ToolBarIconSize, PM_ListViewIconSize,
PM_IconViewIconSize, PM_SmallIconSize, PM_LargeIconSize, PM_FocusFrameVMargin,
PM_FocusFrameHMargin, PM_ToolTipLabelFrameWidth, PM_CheckBoxLabelSpacing, PM_TabBarIconSize,
PM_SizeGripSize, PM_DockWidgetTitleMargin, PM_MessageBoxIconSize, PM_ButtonIconSize,
PM_DockWidgetTitleBarButtonMargin, PM_RadioButtonLabelSpacing, PM_LayoutLeftMargin, PM_LayoutTopMargin,
PM_LayoutRightMargin, PM_LayoutBottomMargin, PM_LayoutHorizontalSpacing, PM_LayoutVerticalSpacing,
PM_TabBar_ScrollButtonOverlap, PM_TextCursorWidth, PM_TabCloseIndicatorWidth, PM_TabCloseIndicatorHeight,
PM_ScrollView_ScrollBarSpacing, PM_SubMenuOverlap, PM_CustomBase = 0xf0000000
}
This enum describes the various available pixel metrics.
enum PrimitiveElement {
PE_Q3CheckListController, PE_Q3CheckListExclusiveIndicator, PE_Q3CheckListIndicator, PE_Q3DockWindowSeparator,
PE_Q3Separator, PE_Frame, PE_FrameDefaultButton, PE_FrameDockWidget,
PE_FrameFocusRect, PE_FrameGroupBox, PE_FrameLineEdit, PE_FrameMenu,
PE_FrameStatusBar, PE_FrameStatusBarItem = PE_FrameStatusBar, PE_FrameTabWidget, PE_FrameWindow,
PE_FrameButtonBevel, PE_FrameButtonTool, PE_FrameTabBarBase, PE_PanelButtonCommand,
PE_PanelButtonBevel, PE_PanelButtonTool, PE_PanelMenuBar, PE_PanelToolBar,
PE_PanelLineEdit, PE_IndicatorArrowDown, PE_IndicatorArrowLeft, PE_IndicatorArrowRight,
PE_IndicatorArrowUp, PE_IndicatorBranch, PE_IndicatorButtonDropDown, PE_IndicatorViewItemCheck,
PE_IndicatorItemViewItemCheck = PE_IndicatorViewItemCheck, PE_IndicatorCheckBox, PE_IndicatorDockWidgetResizeHandle, PE_IndicatorHeaderArrow,
PE_IndicatorMenuCheckMark, PE_IndicatorProgressChunk, PE_IndicatorRadioButton, PE_IndicatorSpinDown,
PE_IndicatorSpinMinus, PE_IndicatorSpinPlus, PE_IndicatorSpinUp, PE_IndicatorToolBarHandle,
PE_IndicatorToolBarSeparator, PE_PanelTipLabel, PE_IndicatorTabTear, PE_PanelScrollAreaCorner,
PE_Widget, PE_IndicatorColumnViewArrow, PE_IndicatorItemViewItemDrop, PE_PanelItemViewItem,
PE_PanelItemViewRow, PE_PanelStatusBar, PE_IndicatorTabClose, PE_PanelMenu,
PE_CustomBase = 0xf000000
}
This enum describes the various primitive elements.
enum RequestSoftwareInputPanel { RSIP_OnMouseClickAndAlreadyFocused, RSIP_OnMouseClick }
This enum describes under what circumstances a software input panel will be requested by input capable widgets.
enum StandardPixmap {
SP_TitleBarMenuButton, SP_TitleBarMinButton, SP_TitleBarMaxButton, SP_TitleBarCloseButton,
SP_TitleBarNormalButton, SP_TitleBarShadeButton, SP_TitleBarUnshadeButton, SP_TitleBarContextHelpButton,
SP_DockWidgetCloseButton, SP_MessageBoxInformation, SP_MessageBoxWarning, SP_MessageBoxCritical,
SP_MessageBoxQuestion, SP_DesktopIcon, SP_TrashIcon, SP_ComputerIcon,
SP_DriveFDIcon, SP_DriveHDIcon, SP_DriveCDIcon, SP_DriveDVDIcon,
SP_DriveNetIcon, SP_DirOpenIcon, SP_DirClosedIcon, SP_DirLinkIcon,
SP_FileIcon, SP_FileLinkIcon, SP_ToolBarHorizontalExtensionButton, SP_ToolBarVerticalExtensionButton,
SP_FileDialogStart, SP_FileDialogEnd, SP_FileDialogToParent, SP_FileDialogNewFolder,
SP_FileDialogDetailedView, SP_FileDialogInfoView, SP_FileDialogContentsView, SP_FileDialogListView,
SP_FileDialogBack, SP_DirIcon, SP_DialogOkButton, SP_DialogCancelButton,
SP_DialogHelpButton, SP_DialogOpenButton, SP_DialogSaveButton, SP_DialogCloseButton,
SP_DialogApplyButton, SP_DialogResetButton, SP_DialogDiscardButton, SP_DialogYesButton,
SP_DialogNoButton, SP_ArrowUp, SP_ArrowDown, SP_ArrowLeft,
SP_ArrowRight, SP_ArrowBack, SP_ArrowForward, SP_DirHomeIcon,
SP_CommandLink, SP_VistaShield, SP_BrowserReload, SP_BrowserStop,
SP_MediaPlay, SP_MediaStop, SP_MediaPause, SP_MediaSkipForward,
SP_MediaSkipBackward, SP_MediaSeekForward, SP_MediaSeekBackward, SP_MediaVolume,
SP_MediaVolumeMuted, SP_CustomBase = 0xf0000000
}
This enum describes the available standard pixmaps.
enum StateFlag {
State_None = 0x00000000, State_Enabled = 0x00000001, State_Raised = 0x00000002, State_Sunken = 0x00000004,
State_Off = 0x00000008, State_NoChange = 0x00000010, State_On = 0x00000020, State_DownArrow = 0x00000040,
State_Horizontal = 0x00000080, State_HasFocus = 0x00000100, State_Top = 0x00000200, State_Bottom = 0x00000400,
State_FocusAtBorder = 0x00000800, State_AutoRaise = 0x00001000, State_MouseOver = 0x00002000, State_UpArrow = 0x00004000,
State_Selected = 0x00008000, State_Active = 0x00010000, State_Window = 0x00020000, State_Open = 0x00040000,
State_Children = 0x00080000, State_Item = 0x00100000, State_Sibling = 0x00200000, State_Editing = 0x00400000,
State_KeyboardFocusChange = 0x00800000, State_ReadOnly = 0x02000000, State_Small = 0x04000000, State_Mini = 0x08000000
}
This enum describes flags that are used when drawing primitive elements.
enum StyleHint {
SH_EtchDisabledText, SH_DitherDisabledText, SH_ScrollBar_MiddleClickAbsolutePosition, SH_ScrollBar_ScrollWhenPointerLeavesControl,
SH_TabBar_SelectMouseType, SH_TabBar_Alignment, SH_Header_ArrowAlignment, SH_Slider_SnapToValue,
SH_Slider_SloppyKeyEvents, SH_ProgressDialog_CenterCancelButton, SH_ProgressDialog_TextLabelAlignment, SH_PrintDialog_RightAlignButtons,
SH_MainWindow_SpaceBelowMenuBar, SH_FontDialog_SelectAssociatedText, SH_Menu_AllowActiveAndDisabled, SH_Menu_SpaceActivatesItem,
SH_Menu_SubMenuPopupDelay, SH_ScrollView_FrameOnlyAroundContents, SH_MenuBar_AltKeyNavigation, SH_ComboBox_ListMouseTracking,
SH_Menu_MouseTracking, SH_MenuBar_MouseTracking, SH_ItemView_ChangeHighlightOnFocus, SH_Widget_ShareActivation,
SH_Workspace_FillSpaceOnMaximize, SH_ComboBox_Popup, SH_TitleBar_NoBorder, SH_Slider_StopMouseOverSlider,
SH_ScrollBar_StopMouseOverSlider = SH_Slider_StopMouseOverSlider, SH_BlinkCursorWhenTextSelected, SH_RichText_FullWidthSelection, SH_Menu_Scrollable,
SH_GroupBox_TextLabelVerticalAlignment, SH_GroupBox_TextLabelColor, SH_Menu_SloppySubMenus, SH_Table_GridLineColor,
SH_LineEdit_PasswordCharacter, SH_DialogButtons_DefaultButton, SH_ToolBox_SelectedPageTitleBold, SH_TabBar_PreferNoArrows,
SH_ScrollBar_LeftClickAbsolutePosition, SH_Q3ListViewExpand_SelectMouseType, SH_UnderlineShortcut, SH_SpinBox_AnimateButton,
SH_SpinBox_KeyPressAutoRepeatRate, SH_SpinBox_ClickAutoRepeatRate, SH_Menu_FillScreenWithScroll, SH_ToolTipLabel_Opacity,
SH_DrawMenuBarSeparator, SH_TitleBar_ModifyNotification, SH_Button_FocusPolicy, SH_MenuBar_DismissOnSecondClick,
SH_MessageBox_UseBorderForButtonSpacing, SH_TitleBar_AutoRaise, SH_ToolButton_PopupDelay, SH_FocusFrame_Mask,
SH_RubberBand_Mask, SH_WindowFrame_Mask, SH_SpinControls_DisableOnBounds, SH_Dial_BackgroundRole,
SH_ComboBox_LayoutDirection, SH_ItemView_EllipsisLocation, SH_ItemView_ShowDecorationSelected, SH_ItemView_ActivateItemOnSingleClick,
SH_ScrollBar_ContextMenu, SH_ScrollBar_RollBetweenButtons, SH_Slider_AbsoluteSetButtons, SH_Slider_PageSetButtons,
SH_Menu_KeyboardSearch, SH_TabBar_ElideMode, SH_DialogButtonLayout, SH_ComboBox_PopupFrameStyle,
SH_MessageBox_TextInteractionFlags, SH_DialogButtonBox_ButtonsHaveIcons, SH_SpellCheckUnderlineStyle, SH_MessageBox_CenterButtons,
SH_Menu_SelectionWrap, SH_ItemView_MovementWithoutUpdatingSelection, SH_ToolTip_Mask, SH_FocusFrame_AboveWidget,
SH_TextControl_FocusIndicatorTextCharFormat, SH_WizardStyle, SH_ItemView_ArrowKeysNavigateIntoChildren, SH_Menu_Mask,
SH_Menu_FlashTriggeredItem, SH_Menu_FadeOutOnHide, SH_SpinBox_ClickAutoRepeatThreshold, SH_ItemView_PaintAlternatingRowColorsForEmptyArea,
SH_FormLayoutWrapPolicy, SH_TabWidget_DefaultTabPosition, SH_ToolBar_Movable, SH_FormLayoutFieldGrowthPolicy,
SH_FormLayoutFormAlignment, SH_FormLayoutLabelAlignment, SH_ItemView_DrawDelegateFrame, SH_TabBar_CloseButtonPosition,
SH_DockWidget_ButtonsHaveFrame, SH_ToolButtonStyle, SH_RequestSoftwareInputPanel, SH_CustomBase = 0xf0000000
}
This enum describes the available style hints.
enum SubControl {
SC_None = 0x00000000, SC_ScrollBarAddLine = 0x00000001, SC_ScrollBarSubLine = 0x00000002, SC_ScrollBarAddPage = 0x00000004,
SC_ScrollBarSubPage = 0x00000008, SC_ScrollBarFirst = 0x00000010, SC_ScrollBarLast = 0x00000020, SC_ScrollBarSlider = 0x00000040,
SC_ScrollBarGroove = 0x00000080, SC_SpinBoxUp = 0x00000001, SC_SpinBoxDown = 0x00000002, SC_SpinBoxFrame = 0x00000004,
SC_SpinBoxEditField = 0x00000008, SC_ComboBoxFrame = 0x00000001, SC_ComboBoxEditField = 0x00000002, SC_ComboBoxArrow = 0x00000004,
SC_ComboBoxListBoxPopup = 0x00000008, SC_SliderGroove = 0x00000001, SC_SliderHandle = 0x00000002, SC_SliderTickmarks = 0x00000004,
SC_ToolButton = 0x00000001, SC_ToolButtonMenu = 0x00000002, SC_TitleBarSysMenu = 0x00000001, SC_TitleBarMinButton = 0x00000002,
SC_TitleBarMaxButton = 0x00000004, SC_TitleBarCloseButton = 0x00000008, SC_TitleBarNormalButton = 0x00000010, SC_TitleBarShadeButton = 0x00000020,
SC_TitleBarUnshadeButton = 0x00000040, SC_TitleBarContextHelpButton = 0x00000080, SC_TitleBarLabel = 0x00000100, SC_Q3ListView = 0x00000001,
SC_Q3ListViewBranch = 0x00000002, SC_Q3ListViewExpand = 0x00000004, SC_DialGroove = 0x00000001, SC_DialHandle = 0x00000002,
SC_DialTickmarks = 0x00000004, SC_GroupBoxCheckBox = 0x00000001, SC_GroupBoxLabel = 0x00000002, SC_GroupBoxContents = 0x00000004,
SC_GroupBoxFrame = 0x00000008, SC_MdiMinButton = 0x00000001, SC_MdiNormalButton = 0x00000002, SC_MdiCloseButton = 0x00000004,
SC_CustomBase = 0xf0000000, SC_All = 0xffffffff
}
This enum describes the available sub controls.
enum SubElement {
SE_PushButtonContents, SE_PushButtonFocusRect, SE_CheckBoxIndicator, SE_CheckBoxContents,
SE_CheckBoxFocusRect, SE_CheckBoxClickRect, SE_RadioButtonIndicator, SE_RadioButtonContents,
SE_RadioButtonFocusRect, SE_RadioButtonClickRect, SE_ComboBoxFocusRect, SE_SliderFocusRect,
SE_Q3DockWindowHandleRect, SE_ProgressBarGroove, SE_ProgressBarContents, SE_ProgressBarLabel,
SE_DialogButtonAccept, SE_DialogButtonReject, SE_DialogButtonApply, SE_DialogButtonHelp,
SE_DialogButtonAll, SE_DialogButtonAbort, SE_DialogButtonIgnore, SE_DialogButtonRetry,
SE_DialogButtonCustom, SE_ToolBoxTabContents, SE_HeaderLabel, SE_HeaderArrow,
SE_TabWidgetTabBar, SE_TabWidgetTabPane, SE_TabWidgetTabContents, SE_TabWidgetLeftCorner,
SE_TabWidgetRightCorner, SE_ViewItemCheckIndicator, SE_ItemViewItemCheckIndicator = SE_ViewItemCheckIndicator, SE_TabBarTearIndicator,
SE_TreeViewDisclosureItem, SE_LineEditContents, SE_FrameContents, SE_DockWidgetCloseButton,
SE_DockWidgetFloatButton, SE_DockWidgetTitleBarText, SE_DockWidgetIcon, SE_CheckBoxLayoutItem,
SE_ComboBoxLayoutItem, SE_DateTimeEditLayoutItem, SE_DialogButtonBoxLayoutItem, SE_LabelLayoutItem,
SE_ProgressBarLayoutItem, SE_PushButtonLayoutItem, SE_RadioButtonLayoutItem, SE_SliderLayoutItem,
SE_SpinBoxLayoutItem, SE_ToolButtonLayoutItem, SE_FrameLayoutItem, SE_GroupBoxLayoutItem,
SE_TabWidgetLayoutItem, SE_ItemViewItemDecoration, SE_ItemViewItemText, SE_ItemViewItemFocusRect,
SE_TabBarTabLeftButton, SE_TabBarTabRightButton, SE_TabBarTabText, SE_ShapedFrameContents,
SE_ToolBarHandle, SE_CustomBase = 0xf0000000
}
This enum represents a sub-area of a widget.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QStyle
static QRect alignedRect (Qt::LayoutDirection direction, Qt::Alignment alignment, const QSize &size, const QRect &rectangle)
Returns a new rectangle of the specified size that is aligned to the given rectangle according to the specified alignment and direction.
static int sliderPositionFromValue (int min, int max, int val, int space, bool upsideDown=false)
Converts the given logicalValue to a pixel position.
static int sliderValueFromPosition (int min, int max, int pos, int space, bool upsideDown=false)
Converts the given pixel position to a logical value.
static Qt::Alignment visualAlignment (Qt::LayoutDirection direction, Qt::Alignment alignment)
Transforms an alignment of Qt::AlignLeft or Qt::AlignRight without Qt::AlignAbsolute into Qt::AlignLeft or Qt::AlignRight with Qt::AlignAbsolute according to the layout direction.
static QPoint visualPos (Qt::LayoutDirection direction, const QRect &boundingRect, const QPoint &logicalPos)
Returns the given logicalPosition converted to screen coordinates based on the specified direction.
static QRect visualRect (Qt::LayoutDirection direction, const QRect &boundingRect, const QRect &logicalRect)
Returns the given logicalRectangle converted to screen coordinates based on the specified direction.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 75 of file qstylesheetstyle_p.h.
Typedefs
ParentStyle
typedef QWindowsStyle QStyleSheetStyle::ParentStyle private
Definition at line 77 of file qstylesheetstyle_p.h.
Constructors and Destructors
QStyleSheetStyle()
QStyleSheetStyle::QStyleSheetStyle (QStyle * baseStyle)
Definition at line 2613 of file qstylesheetstyle.cpp.
     : QWindowsStyle(*new QStyleSheetStylePrivate), base(base), refcount(1)
 {
     ++numinstances;
     if (numinstances == 1) {
         styleSheetCaches = new QStyleSheetStyleCaches;
     }
 }
~QStyleSheetStyle()
QStyleSheetStyle::~QStyleSheetStyle ()
Definition at line 2622 of file qstylesheetstyle.cpp.
 {
     --numinstances;
     if (numinstances == 0) {
         delete styleSheetCaches;
     }
 }
Functions
baseStyle()
QStyle * QStyleSheetStyle::baseStyle () const
Definition at line 2629 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyleSelector::attribute(), drawComplexControl(), drawControl(), drawItemPixmap(), drawItemText(), drawPrimitive(), event(), generatedIconPixmap(), hitTestComplexControl(), itemPixmapRect(), itemTextRect(), layoutSpacing(), layoutSpacingImplementation(), pixelMetric(), polish(), sizeFromContents(), standardIconImplementation(), standardPalette(), standardPixmap(), styleHint(), subControlRect(), subElementRect(), and unpolish().
 {
     if (base)
         return base;
     if (QStyleSheetStyle *me = qobject_cast<QStyleSheetStyle *>(QApplication::style()))
         return me->base;
     return QApplication::style();
 }
clearWidgetFont()
void QStyleSheetStyle::clearWidgetFont (QWidget * w) const
Definition at line 5846 of file qstylesheetstyle.cpp.
 {
     w->setProperty("_q_styleSheetWidgetFont", QVariant(QVariant::Invalid));
 }
defaultSize()
QSize QStyleSheetStyle::defaultSize (const QWidget * w, QSize sz, const QRect & rect, int pe) const private
Definition at line 2160 of file qstylesheetstyle.cpp.
 {
     QStyle *base = baseStyle();
     switch (pe) {
     case PseudoElement_Indicator:
     case PseudoElement_MenuCheckMark:
         if (sz.width() == -1)
             sz.setWidth(base->pixelMetric(PM_IndicatorWidth, 0, w));
         if (sz.height() == -1)
             sz.setHeight(base->pixelMetric(PM_IndicatorHeight, 0, w));
         break;
     case PseudoElement_ExclusiveIndicator:
     case PseudoElement_GroupBoxIndicator:
         if (sz.width() == -1)
             sz.setWidth(base->pixelMetric(PM_ExclusiveIndicatorWidth, 0, w));
         if (sz.height() == -1)
             sz.setHeight(base->pixelMetric(PM_ExclusiveIndicatorHeight, 0, w));
         break;
     case PseudoElement_PushButtonMenuIndicator: {
         int pm = base->pixelMetric(PM_MenuButtonIndicator, 0, w);
         if (sz.width() == -1)
             sz.setWidth(pm);
         if (sz.height() == -1)
             sz.setHeight(pm);
                                       }
         break;
     case PseudoElement_ComboBoxDropDown:
         if (sz.width() == -1)
             sz.setWidth(16);
         break;
     case PseudoElement_ComboBoxArrow:
     case PseudoElement_DownArrow:
     case PseudoElement_ToolButtonMenuArrow:
     case PseudoElement_ToolButtonDownArrow:
     case PseudoElement_MenuRightArrow:
         if (sz.width() == -1)
             sz.setWidth(13);
         if (sz.height() == -1)
             sz.setHeight(13);
         break;
     case PseudoElement_SpinBoxUpButton:
     case PseudoElement_SpinBoxDownButton:
         if (sz.width() == -1)
             sz.setWidth(16);
         if (sz.height() == -1)
             sz.setHeight(rect.height()/2);
         break;
     case PseudoElement_ToolButtonMenu:
         if (sz.width() == -1)
             sz.setWidth(base->pixelMetric(PM_MenuButtonIndicator, 0, w));
         break;
     case PseudoElement_HeaderViewUpArrow:
     case PseudoElement_HeaderViewDownArrow: {
         int pm = base->pixelMetric(PM_HeaderMargin, 0, w);
         if (sz.width() == -1)
             sz.setWidth(pm);
         if (sz.height() == 1)
             sz.setHeight(pm);
         break;
                                             }
     case PseudoElement_ScrollBarFirst:
     case PseudoElement_ScrollBarLast:
     case PseudoElement_ScrollBarAddLine:
     case PseudoElement_ScrollBarSubLine:
     case PseudoElement_ScrollBarSlider: {
         int pm = pixelMetric(QStyle::PM_ScrollBarExtent, 0, w);
         if (sz.width() == -1)
             sz.setWidth(pm);
         if (sz.height() == -1)
             sz.setHeight(pm);
         break;
                                         }
     case PseudoElement_DockWidgetCloseButton:
     case PseudoElement_DockWidgetFloatButton: {
         int iconSize = pixelMetric(PM_SmallIconSize, 0, w);
         return QSize(iconSize, iconSize);
                                               }
     default:
         break;
     }
     // expand to rectangle
     if (sz.height() == -1)
         sz.setHeight(rect.height());
     if (sz.width() == -1)
         sz.setWidth(rect.width());
     return sz;
 }
deref()
void QStyleSheetStyle::deref () inline
Definition at line 128 of file qstylesheetstyle_p.h.
 { Q_ASSERT(refcount > 0); if (!--refcount) delete this; }
drawComplexControl()
void QStyleSheetStyle::drawComplexControl (ComplexControl cc, const QStyleOptionComplex * opt, QPainter * p, const QWidget * w = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2845 of file qstylesheetstyle.cpp.
 {
     RECURSION_GUARD(baseStyle()->drawComplexControl(cc, opt, p, w); return)
     QRenderRule rule = renderRule(w, opt);
     switch (cc) {
     case CC_ComboBox:
         if (const QStyleOptionComboBox *cmb = qstyleoption_cast<const QStyleOptionComboBox *>(opt)) {
             QStyleOptionComboBox cmbOpt(*cmb);
             cmbOpt.rect = rule.borderRect(opt->rect);
             if (rule.hasNativeBorder()) {
                 rule.drawBackgroundImage(p, cmbOpt.rect);
                 rule.configurePalette(&cmbOpt.palette, QPalette::ButtonText, QPalette::Button);
                 bool customDropDown = (opt->subControls & QStyle::SC_ComboBoxArrow)
                                 && (hasStyleRule(w, PseudoElement_ComboBoxDropDown) || hasStyleRule(w, PseudoElement_ComboBoxArrow));
                 if (customDropDown)
                     cmbOpt.subControls &= ~QStyle::SC_ComboBoxArrow;
                 if (rule.baseStyleCanDraw()) {
                     baseStyle()->drawComplexControl(cc, &cmbOpt, p, w);
                 } else {
                     QWindowsStyle::drawComplexControl(cc, &cmbOpt, p, w);
                 }
                 if (!customDropDown)
                     return;
             } else {
                 rule.drawRule(p, opt->rect);
             }
             if (opt->subControls & QStyle::SC_ComboBoxArrow) {
                 QRenderRule subRule = renderRule(w, opt, PseudoElement_ComboBoxDropDown);
                 if (subRule.hasDrawable()) {
                     QRect r = subControlRect(CC_ComboBox, opt, SC_ComboBoxArrow, w);
                     subRule.drawRule(p, r);
                     QRenderRule subRule2 = renderRule(w, opt, PseudoElement_ComboBoxArrow);
                     r = positionRect(w, subRule, subRule2, PseudoElement_ComboBoxArrow, r, opt->direction);
                     subRule2.drawRule(p, r);
                 } else {
                     cmbOpt.subControls = QStyle::SC_ComboBoxArrow;
                     QWindowsStyle::drawComplexControl(cc, &cmbOpt, p, w);
                 }
             }
             return;
         }
         break;
 #ifndef QT_NO_SPINBOX
     case CC_SpinBox:
         if (const QStyleOptionSpinBox *spin = qstyleoption_cast<const QStyleOptionSpinBox *>(opt)) {
             QStyleOptionSpinBox spinOpt(*spin);
             rule.configurePalette(&spinOpt.palette, QPalette::ButtonText, QPalette::Button);
             rule.configurePalette(&spinOpt.palette, QPalette::Text, QPalette::Base);
             spinOpt.rect = rule.borderRect(opt->rect);
             bool customUp = true, customDown = true;
             QRenderRule upRule = renderRule(w, opt, PseudoElement_SpinBoxUpButton);
             QRenderRule downRule = renderRule(w, opt, PseudoElement_SpinBoxDownButton);
             bool upRuleMatch = upRule.hasGeometry() || upRule.hasPosition();
             bool downRuleMatch = downRule.hasGeometry() || downRule.hasPosition();
             if (rule.hasNativeBorder() && !upRuleMatch && !downRuleMatch) {
                 rule.drawBackgroundImage(p, spinOpt.rect);
                 customUp = (opt->subControls & QStyle::SC_SpinBoxUp)
                         && (hasStyleRule(w, PseudoElement_SpinBoxUpButton) || hasStyleRule(w, PseudoElement_UpArrow));
                 if (customUp)
                     spinOpt.subControls &= ~QStyle::SC_SpinBoxUp;
                 customDown = (opt->subControls & QStyle::SC_SpinBoxDown)
                         && (hasStyleRule(w, PseudoElement_SpinBoxDownButton) || hasStyleRule(w, PseudoElement_DownArrow));
                 if (customDown)
                     spinOpt.subControls &= ~QStyle::SC_SpinBoxDown;
                 if (rule.baseStyleCanDraw()) {
                     baseStyle()->drawComplexControl(cc, &spinOpt, p, w);
                 } else {
                     QWindowsStyle::drawComplexControl(cc, &spinOpt, p, w);
                 }
                 if (!customUp && !customDown)
                     return;
             } else {
                 rule.drawRule(p, opt->rect);
             }
             if ((opt->subControls & QStyle::SC_SpinBoxUp) && customUp) {
                 QRenderRule subRule = renderRule(w, opt, PseudoElement_SpinBoxUpButton);
                 if (subRule.hasDrawable()) {
                     QRect r = subControlRect(CC_SpinBox, opt, SC_SpinBoxUp, w);
                     subRule.drawRule(p, r);
                     QRenderRule subRule2 = renderRule(w, opt, PseudoElement_SpinBoxUpArrow);
                     r = positionRect(w, subRule, subRule2, PseudoElement_SpinBoxUpArrow, r, opt->direction);
                     subRule2.drawRule(p, r);
                 } else {
                     spinOpt.subControls = QStyle::SC_SpinBoxUp;
                     QWindowsStyle::drawComplexControl(cc, &spinOpt, p, w);
                 }
             }
             if ((opt->subControls & QStyle::SC_SpinBoxDown) && customDown) {
                 QRenderRule subRule = renderRule(w, opt, PseudoElement_SpinBoxDownButton);
                 if (subRule.hasDrawable()) {
                     QRect r = subControlRect(CC_SpinBox, opt, SC_SpinBoxDown, w);
                     subRule.drawRule(p, r);
                     QRenderRule subRule2 = renderRule(w, opt, PseudoElement_SpinBoxDownArrow);
                     r = positionRect(w, subRule, subRule2, PseudoElement_SpinBoxDownArrow, r, opt->direction);
                     subRule2.drawRule(p, r);
                 } else {
                     spinOpt.subControls = QStyle::SC_SpinBoxDown;
                     QWindowsStyle::drawComplexControl(cc, &spinOpt, p, w);
                 }
             }
             return;
         }
         break;
 #endif // QT_NO_SPINBOX
     case CC_GroupBox:
         if (const QStyleOptionGroupBox *gb = qstyleoption_cast<const QStyleOptionGroupBox *>(opt)) {
             QRect labelRect, checkBoxRect, titleRect, frameRect;
             bool hasTitle = (gb->subControls & QStyle::SC_GroupBoxCheckBox) || !gb->text.isEmpty();
             if (!rule.hasDrawable() && (!hasTitle || !hasStyleRule(w, PseudoElement_GroupBoxTitle))
                 && !hasStyleRule(w, PseudoElement_Indicator) && !rule.hasBox() && !rule.hasFont && !rule.hasPalette()) {
                 // let the native style draw the combobox if there is no style for it.
                 break;
             }
             rule.drawBackground(p, opt->rect);
             QRenderRule titleRule = renderRule(w, opt, PseudoElement_GroupBoxTitle);
             bool clipSet = false;
             if (hasTitle) {
                 labelRect = subControlRect(CC_GroupBox, opt, SC_GroupBoxLabel, w);
                 //Some native style (such as mac) may return a too small rectangle (because they use smaller fonts),  so we may need to expand it a little bit.
                 labelRect.setSize(labelRect.size().expandedTo(ParentStyle::subControlRect(CC_GroupBox, opt, SC_GroupBoxLabel, w).size()));
                 if (gb->subControls & QStyle::SC_GroupBoxCheckBox) {
                     checkBoxRect = subControlRect(CC_GroupBox, opt, SC_GroupBoxCheckBox, w);
                     titleRect = titleRule.boxRect(checkBoxRect.united(labelRect));
                 } else {
                     titleRect = titleRule.boxRect(labelRect);
                 }
                 if (!titleRule.hasBackground() || !titleRule.background()->isTransparent()) {
                     clipSet = true;
                     p->save();
                     p->setClipRegion(QRegion(opt->rect) - titleRect);
                 }
             }
             frameRect = subControlRect(CC_GroupBox, opt, SC_GroupBoxFrame, w);
             QStyleOptionFrameV2 frame;
             frame.QStyleOption::operator=(*gb);
             frame.features = gb->features;
             frame.lineWidth = gb->lineWidth;
             frame.midLineWidth = gb->midLineWidth;
             frame.rect = frameRect;
             drawPrimitive(PE_FrameGroupBox, &frame, p, w);
             if (clipSet)
                 p->restore();
             // draw background and frame of the title
             if (hasTitle)
                 titleRule.drawRule(p, titleRect);
             // draw the indicator
             if (gb->subControls & QStyle::SC_GroupBoxCheckBox) {
                 QStyleOptionButton box;
                 box.QStyleOption::operator=(*gb);
                 box.rect = checkBoxRect;
                 drawPrimitive(PE_IndicatorCheckBox, &box, p, w);
             }
             // draw the text
             if (!gb->text.isEmpty()) {
                 int alignment = int(Qt::AlignCenter | Qt::TextShowMnemonic);
                 if (!styleHint(QStyle::SH_UnderlineShortcut, opt, w)) {
                     alignment |= Qt::TextHideMnemonic;
                 }
                 QPalette pal = gb->palette;
                 if (gb->textColor.isValid())
                     pal.setColor(QPalette::WindowText, gb->textColor);
                 titleRule.configurePalette(&pal, QPalette::WindowText, QPalette::Window);
                 drawItemText(p, labelRect,  alignment, pal, gb->state & State_Enabled,
                              gb->text, QPalette::WindowText);
                 if (gb->state & State_HasFocus) {
                     QStyleOptionFocusRect fropt;
                     fropt.QStyleOption::operator=(*gb);
                     fropt.rect = labelRect;
                     drawPrimitive(PE_FrameFocusRect, &fropt, p, w);
                 }
             }
                         return;
         }
         break;
     case CC_ToolButton:
         if (const QStyleOptionToolButton *tool = qstyleoption_cast<const QStyleOptionToolButton *>(opt)) {
             QStyleOptionToolButton toolOpt(*tool);
             rule.configurePalette(&toolOpt.palette, QPalette::ButtonText, QPalette::Button);
             toolOpt.font = rule.font.resolve(toolOpt.font);
             toolOpt.rect = rule.borderRect(opt->rect);
             bool customArrow = (tool->features & (QStyleOptionToolButton::HasMenu | QStyleOptionToolButton::MenuButtonPopup));
             bool customDropDown = tool->features & QStyleOptionToolButton::MenuButtonPopup;
             if (rule.hasNativeBorder()) {
                 if (tool->subControls & SC_ToolButton) {
                     //in some case (eg. the button is "auto raised") the style doesn't draw the background
                     //so we need to draw the background.
                     // use the same condition as in QCommonStyle
                     State bflags = tool->state & ~State_Sunken;
                     if (bflags & State_AutoRaise && (!(bflags & State_MouseOver) || !(bflags & State_Enabled)))
                             bflags &= ~State_Raised;
                     if (tool->state & State_Sunken && tool->activeSubControls & SC_ToolButton)
                             bflags |= State_Sunken;
                     if (!(bflags & (State_Sunken | State_On | State_Raised)))
                         rule.drawBackground(p, toolOpt.rect);
                 }
                 customArrow = customArrow && hasStyleRule(w, PseudoElement_ToolButtonDownArrow);
                 if (customArrow)
                     toolOpt.features &= ~QStyleOptionToolButton::HasMenu;
                 customDropDown = customDropDown && hasStyleRule(w, PseudoElement_ToolButtonMenu);
                 if (customDropDown)
                     toolOpt.subControls &= ~QStyle::SC_ToolButtonMenu;
                 if (rule.baseStyleCanDraw() && !(tool->features & QStyleOptionToolButton::Arrow)) {
                     baseStyle()->drawComplexControl(cc, &toolOpt, p, w);
                 } else {
                     QWindowsStyle::drawComplexControl(cc, &toolOpt, p, w);
                 }
                 if (!customArrow && !customDropDown)
                     return;
             } else {
                 rule.drawRule(p, opt->rect);
                 toolOpt.rect = rule.contentsRect(opt->rect);
                 if (rule.hasFont)
                     toolOpt.font = rule.font;
                 drawControl(CE_ToolButtonLabel, &toolOpt, p, w);
             }
             QRenderRule subRule = renderRule(w, opt, PseudoElement_ToolButtonMenu);
             QRect r = subControlRect(CC_ToolButton, opt, QStyle::SC_ToolButtonMenu, w);
             if (customDropDown) {
                 if (opt->subControls & QStyle::SC_ToolButtonMenu) {
                     if (subRule.hasDrawable()) {
                         subRule.drawRule(p, r);
                     } else {
                         toolOpt.rect = r;
                         baseStyle()->drawPrimitive(PE_IndicatorButtonDropDown, &toolOpt, p, w);
                     }
                 }
             }
             if (customArrow) {
                 QRenderRule subRule2 = customDropDown ? renderRule(w, opt, PseudoElement_ToolButtonMenuArrow)
                                                       : renderRule(w, opt, PseudoElement_ToolButtonDownArrow);
                 QRect r2 = customDropDown
                           ? positionRect(w, subRule, subRule2, PseudoElement_ToolButtonMenuArrow, r, opt->direction)
                           : positionRect(w, rule, subRule2, PseudoElement_ToolButtonDownArrow, opt->rect, opt->direction);
                 if (subRule2.hasDrawable()) {
                     subRule2.drawRule(p, r2);
                 } else {
                     toolOpt.rect = r2;
                     baseStyle()->drawPrimitive(QStyle::PE_IndicatorArrowDown, &toolOpt, p, w);
                 }
             }
             return;
         }
         break;
 #ifndef QT_NO_SCROLLBAR
     case CC_ScrollBar:
         if (const QStyleOptionSlider *sb = qstyleoption_cast<const QStyleOptionSlider *>(opt)) {
             QStyleOptionSlider sbOpt(*sb);
             if (!rule.hasDrawable()) {
                 sbOpt.rect = rule.borderRect(opt->rect);
                 rule.drawBackgroundImage(p, opt->rect);
                 baseStyle()->drawComplexControl(cc, &sbOpt, p, w);
             } else {
                 rule.drawRule(p, opt->rect);
                 QWindowsStyle::drawComplexControl(cc, opt, p, w);
             }
             return;
         }
         break;
 #endif // QT_NO_SCROLLBAR
 #ifndef QT_NO_SLIDER
     case CC_Slider:
         if (const QStyleOptionSlider *slider = qstyleoption_cast<const QStyleOptionSlider *>(opt)) {
             rule.drawRule(p, opt->rect);
             QRenderRule grooveSubRule = renderRule(w, opt, PseudoElement_SliderGroove);
             QRenderRule handleSubRule = renderRule(w, opt, PseudoElement_SliderHandle);
             if (!grooveSubRule.hasDrawable()) {
                 QStyleOptionSlider slOpt(*slider);
                 bool handleHasRule = handleSubRule.hasDrawable();
                 // If the style specifies a different handler rule, draw the groove without the handler.
                 if (handleHasRule)
                     slOpt.subControls &= ~SC_SliderHandle;
                 baseStyle()->drawComplexControl(cc, &slOpt, p, w);
                 if (!handleHasRule)
                     return;
             }
             QRect gr = subControlRect(cc, opt, SC_SliderGroove, w);
             if (slider->subControls & SC_SliderGroove) {
                 grooveSubRule.drawRule(p, gr);
             }
             if (slider->subControls & SC_SliderHandle) {
                 QRect hr = subControlRect(cc, opt, SC_SliderHandle, w);
                 QRenderRule subRule1 = renderRule(w, opt, PseudoElement_SliderSubPage);
                 if (subRule1.hasDrawable()) {
                     QRect r(gr.topLeft(),
                             slider->orientation == Qt::Horizontal
                                 ? QPoint(hr.x()+hr.width()/2, gr.y()+gr.height() - 1)
                                 : QPoint(gr.x()+gr.width() - 1, hr.y()+hr.height()/2));
                     subRule1.drawRule(p, r);
                 }
                 QRenderRule subRule2 = renderRule(w, opt, PseudoElement_SliderAddPage);
                 if (subRule2.hasDrawable()) {
                     QRect r(slider->orientation == Qt::Horizontal
                                 ? QPoint(hr.x()+hr.width()/2+1, gr.y())
                                 : QPoint(gr.x(), hr.y()+hr.height()/2+1),
                             gr.bottomRight());
                     subRule2.drawRule(p, r);
                 }
                 handleSubRule.drawRule(p, handleSubRule.boxRect(hr, Margin));
             }
             if (slider->subControls & SC_SliderTickmarks) {
                 // TODO...
             }
             return;
         }
         break;
 #endif // QT_NO_SLIDER
     case CC_MdiControls:
         if (hasStyleRule(w, PseudoElement_MdiCloseButton)
             || hasStyleRule(w, PseudoElement_MdiNormalButton)
             || hasStyleRule(w, PseudoElement_MdiMinButton)) {
             QList<QVariant> layout = rule.styleHint(QLatin1String("button-layout")).toList();
             if (layout.isEmpty())
                 layout = subControlLayout(QLatin1String("mNX"));
             QStyleOptionComplex optCopy(*opt);
             optCopy.subControls = 0;
             for (int i = 0; i < layout.count(); i++) {
                 int layoutButton = layout[i].toInt();
                 if (layoutButton < PseudoElement_MdiCloseButton
                     || layoutButton > PseudoElement_MdiNormalButton)
                     continue;
                 QStyle::SubControl control = knownPseudoElements[layoutButton].subControl;
                 if (!(opt->subControls & control))
                     continue;
                 QRenderRule subRule = renderRule(w, opt, layoutButton);
                 if (subRule.hasDrawable()) {
                     QRect rect = subRule.boxRect(subControlRect(CC_MdiControls, opt, control, w), Margin);
                     subRule.drawRule(p, rect);
                     QIcon icon = standardIcon(subControlIcon(layoutButton), opt);
                     icon.paint(p, subRule.contentsRect(rect), Qt::AlignCenter);
                 } else {
                     optCopy.subControls |= control;
                 }
             }
             if (optCopy.subControls)
                 baseStyle()->drawComplexControl(CC_MdiControls, &optCopy, p, w);
             return;
         }
         break;
     case CC_TitleBar:
         if (const QStyleOptionTitleBar *tb = qstyleoption_cast<const QStyleOptionTitleBar *>(opt)) {
             QRenderRule subRule = renderRule(w, opt, PseudoElement_TitleBar);
             if (!subRule.hasDrawable() && !subRule.hasBox() && !subRule.hasBorder())
                 break;
             subRule.drawRule(p, opt->rect);
             QHash<QStyle::SubControl, QRect> layout = titleBarLayout(w, tb);
             QRect ir;
             ir = layout[SC_TitleBarLabel];
             if (ir.isValid()) {
                 if (subRule.hasPalette())
                     p->setPen(subRule.palette()->foreground.color());
                 p->fillRect(ir, Qt::white);
                 p->drawText(ir.x(), ir.y(), ir.width(), ir.height(), Qt::AlignLeft | Qt::AlignVCenter | Qt::TextSingleLine, tb->text);
             }
             QPixmap pm;
             ir = layout[SC_TitleBarSysMenu];
             if (ir.isValid()) {
                 QRenderRule subSubRule = renderRule(w, opt, PseudoElement_TitleBarSysMenu);
                 subSubRule.drawRule(p, ir);
                 ir = subSubRule.contentsRect(ir);
                 if (!tb->icon.isNull()) {
                     tb->icon.paint(p, ir);
                 } else {
                     int iconSize = pixelMetric(PM_SmallIconSize, tb, w);
                     pm = standardIcon(SP_TitleBarMenuButton, 0, w).pixmap(iconSize, iconSize);
                     drawItemPixmap(p, ir, Qt::AlignCenter, pm);
                 }
             }
             ir = layout[SC_TitleBarCloseButton];
             if (ir.isValid()) {
                 QRenderRule subSubRule = renderRule(w, opt, PseudoElement_TitleBarCloseButton);
                 subSubRule.drawRule(p, ir);
                 QSize sz = subSubRule.contentsRect(ir).size();
                 if ((tb->titleBarFlags & Qt::WindowType_Mask) == Qt::Tool)
                     pm = standardIcon(SP_DockWidgetCloseButton, 0, w).pixmap(sz);
                 else
                     pm = standardIcon(SP_TitleBarCloseButton, 0, w).pixmap(sz);
                 drawItemPixmap(p, ir, Qt::AlignCenter, pm);
             }
             int pes[] = {
                 PseudoElement_TitleBarMaxButton,
                 PseudoElement_TitleBarMinButton,
                 PseudoElement_TitleBarNormalButton,
                 PseudoElement_TitleBarShadeButton,
                 PseudoElement_TitleBarUnshadeButton,
                 PseudoElement_TitleBarContextHelpButton
             };
             for (unsigned int i = 0; i < sizeof(pes)/sizeof(int); i++) {
                 int pe = pes[i];
                 QStyle::SubControl sc = knownPseudoElements[pe].subControl;
                 ir = layout[sc];
                 if (!ir.isValid())
                     continue;
                 QRenderRule subSubRule = renderRule(w, opt, pe);
                 subSubRule.drawRule(p, ir);
                 pm = standardIcon(subControlIcon(pe), 0, w).pixmap(subSubRule.contentsRect(ir).size());
                 drawItemPixmap(p, ir, Qt::AlignCenter, pm);
             }
             return;
         }
         break;
     default:
         break;
     }
     baseStyle()->drawComplexControl(cc, opt, p, w);
 }
drawControl()
void QStyleSheetStyle::drawControl (ControlElement element, const QStyleOption * opt, QPainter * p, const QWidget * w = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 3303 of file qstylesheetstyle.cpp.
Referenced by drawComplexControl().
 {
     RECURSION_GUARD(baseStyle()->drawControl(ce, opt, p, w); return)
     QRenderRule rule = renderRule(w, opt);
     int pe1 = PseudoElement_None, pe2 = PseudoElement_None;
     bool fallback = false;
     switch (ce) {
     case CE_ToolButtonLabel:
         if (const QStyleOptionToolButton *btn = qstyleoption_cast<const QStyleOptionToolButton *>(opt)) {
             if (rule.hasBox() || btn->features & QStyleOptionToolButton::Arrow) {
                 QCommonStyle::drawControl(ce, opt, p, w);
             } else {
                 QStyleOptionToolButton butOpt(*btn);
                 rule.configurePalette(&butOpt.palette, QPalette::ButtonText, QPalette::Button);
                 baseStyle()->drawControl(ce, &butOpt, p, w);
             }
             return;
         }
         break;
     case CE_FocusFrame:
         if (!rule.hasNativeBorder()) {
             rule.drawBorder(p, opt->rect);
             return;
         }
         break;
     case CE_PushButton:
         if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(opt)) {
             if (rule.hasDrawable() || rule.hasBox() || rule.hasPosition() || rule.hasPalette() ||
                     ((btn->features & QStyleOptionButton::HasMenu) && hasStyleRule(w, PseudoElement_PushButtonMenuIndicator))) {
                 ParentStyle::drawControl(ce, opt, p, w);
                 return;
             }
         }
         break;
     case CE_PushButtonBevel:
         if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(opt)) {
             QStyleOptionButton btnOpt(*btn);
             btnOpt.rect = rule.borderRect(opt->rect);
             if (rule.hasNativeBorder()) {
                 rule.drawBackgroundImage(p, btnOpt.rect);
                 rule.configurePalette(&btnOpt.palette, QPalette::ButtonText, QPalette::Button);
                 bool customMenu = (btn->features & QStyleOptionButton::HasMenu
                                    && hasStyleRule(w, PseudoElement_PushButtonMenuIndicator));
                 if (customMenu)
                     btnOpt.features &= ~QStyleOptionButton::HasMenu;
                 if (rule.baseStyleCanDraw()) {
                     baseStyle()->drawControl(ce, &btnOpt, p, w);
                 } else {
                     QWindowsStyle::drawControl(ce, &btnOpt, p, w);
                 }
                 if (!customMenu)
                     return;
             } else {
                 rule.drawRule(p, opt->rect);
             }
             if (btn->features & QStyleOptionButton::HasMenu) {
                 QRenderRule subRule = renderRule(w, opt, PseudoElement_PushButtonMenuIndicator);
                 QRect ir = positionRect(w, rule, subRule, PseudoElement_PushButtonMenuIndicator, opt->rect, opt->direction);
                 if (subRule.hasDrawable()) {
                     subRule.drawRule(p, ir);
                 } else {
                     btnOpt.rect = ir;
                     baseStyle()->drawPrimitive(PE_IndicatorArrowDown, &btnOpt, p, w);
                 }
             }
         }
         return;
     case CE_PushButtonLabel:
         if (const QStyleOptionButton *button = qstyleoption_cast<const QStyleOptionButton *>(opt)) {
             QStyleOptionButton butOpt(*button);
             rule.configurePalette(&butOpt.palette, QPalette::ButtonText, QPalette::Button);
             const QFont oldFont = p->font();
             if (rule.hasFont)
                 p->setFont(rule.font);
             if (rule.hasPosition() && rule.position()->textAlignment != 0) {
                 Qt::Alignment textAlignment = rule.position()->textAlignment;
                 QRect textRect = button->rect;
                 uint tf = Qt::TextShowMnemonic;
                 const uint verticalAlignMask = Qt::AlignVCenter | Qt::AlignTop | Qt::AlignLeft;
                 tf |= (textAlignment & verticalAlignMask) ? (textAlignment & verticalAlignMask) : Qt::AlignVCenter;
                 if (!styleHint(SH_UnderlineShortcut, button, w))
                     tf |= Qt::TextHideMnemonic;
                 if (!button->icon.isNull()) {
                     //Group both icon and text
                     QRect iconRect;
                     QIcon::Mode mode = button->state & State_Enabled ? QIcon::Normal : QIcon::Disabled;
                     if (mode == QIcon::Normal && button->state & State_HasFocus)
                         mode = QIcon::Active;
                     QIcon::State state = QIcon::Off;
                     if (button->state & State_On)
                         state = QIcon::On;
                     QPixmap pixmap = button->icon.pixmap(button->iconSize, mode, state);
                     int labelWidth = pixmap.width();
                     int labelHeight = pixmap.height();
                     int iconSpacing = 4;//### 4 is currently hardcoded in QPushButton::sizeHint()
                     int textWidth = button->fontMetrics.boundingRect(opt->rect, tf, button->text).width();
                     if (!button->text.isEmpty())
                         labelWidth += (textWidth + iconSpacing);
                     //Determine label alignment:
                     if (textAlignment & Qt::AlignLeft) { /*left*/
                         iconRect = QRect(textRect.x(), textRect.y() + (textRect.height() - labelHeight) / 2,
                                          pixmap.width(), pixmap.height());
                     } else if (textAlignment & Qt::AlignHCenter) { /* center */
                         iconRect = QRect(textRect.x() + (textRect.width() - labelWidth) / 2,
                                          textRect.y() + (textRect.height() - labelHeight) / 2,
                                          pixmap.width(), pixmap.height());
                     } else { /*right*/
                         iconRect = QRect(textRect.x() + textRect.width() - labelWidth,
                                          textRect.y() + (textRect.height() - labelHeight) / 2,
                                          pixmap.width(), pixmap.height());
                     }
                     iconRect = visualRect(button->direction, textRect, iconRect);
                     tf |= Qt::AlignLeft; //left align, we adjust the text-rect instead
                     if (button->direction == Qt::RightToLeft)
                         textRect.setRight(iconRect.left() - iconSpacing);
                     else
                         textRect.setLeft(iconRect.left() + iconRect.width() + iconSpacing);
                     if (button->state & (State_On | State_Sunken))
                         iconRect.translate(pixelMetric(PM_ButtonShiftHorizontal, opt, w),
                                            pixelMetric(PM_ButtonShiftVertical, opt, w));
                     p->drawPixmap(iconRect, pixmap);
                 } else {
                     tf |= textAlignment;
                 }
                 if (button->state & (State_On | State_Sunken))
                     textRect.translate(pixelMetric(PM_ButtonShiftHorizontal, opt, w),
                                  pixelMetric(PM_ButtonShiftVertical, opt, w));
                 if (button->features & QStyleOptionButton::HasMenu) {
                     int indicatorSize = pixelMetric(PM_MenuButtonIndicator, button, w);
                     if (button->direction == Qt::LeftToRight)
                         textRect = textRect.adjusted(0, 0, -indicatorSize, 0);
                     else
                         textRect = textRect.adjusted(indicatorSize, 0, 0, 0);
                 }
                 drawItemText(p, textRect, tf, butOpt.palette, (button->state & State_Enabled),
                              button->text, QPalette::ButtonText);
             } else {
                 ParentStyle::drawControl(ce, &butOpt, p, w);
             }
             if (rule.hasFont)
                 p->setFont(oldFont);
         }
         return;
     case CE_RadioButton:
     case CE_CheckBox:
         if (rule.hasBox() || !rule.hasNativeBorder() || rule.hasDrawable() || hasStyleRule(w, PseudoElement_Indicator)) {
             rule.drawRule(p, opt->rect);
             ParentStyle::drawControl(ce, opt, p, w);
             return;
         } else if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(opt)) {
             QStyleOptionButton butOpt(*btn);
             rule.configurePalette(&butOpt.palette, QPalette::ButtonText, QPalette::Button);
             baseStyle()->drawControl(ce, &butOpt, p, w);
             return;
         }
         break;
     case CE_RadioButtonLabel:
     case CE_CheckBoxLabel:
         if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(opt)) {
             QStyleOptionButton butOpt(*btn);
             rule.configurePalette(&butOpt.palette, QPalette::ButtonText, QPalette::Button);
             ParentStyle::drawControl(ce, &butOpt, p, w);
         }
         return;
     case CE_Splitter:
         pe1 = PseudoElement_SplitterHandle;
         break;
     case CE_ToolBar:
         if (rule.hasBackground()) {
             rule.drawBackground(p, opt->rect);
         }
         if (rule.hasBorder()) {
             rule.drawBorder(p, rule.borderRect(opt->rect));
         } else {
 #ifndef QT_NO_TOOLBAR
             if (const QStyleOptionToolBar *tb = qstyleoption_cast<const QStyleOptionToolBar *>(opt)) {
                 QStyleOptionToolBar newTb(*tb);
                 newTb.rect = rule.borderRect(opt->rect);
                 baseStyle()->drawControl(ce, &newTb, p, w);
             }
 #endif // QT_NO_TOOLBAR
         }
         return;
     case CE_MenuEmptyArea:
     case CE_MenuBarEmptyArea:
         if (rule.hasDrawable()) {
             // Drawn by PE_Widget
             return;
         }
         break;
     case CE_MenuTearoff:
     case CE_MenuScroller:
         if (const QStyleOptionMenuItem *m = qstyleoption_cast<const QStyleOptionMenuItem *>(opt)) {
             QStyleOptionMenuItem mi(*m);
             int pe = ce == CE_MenuTearoff ? PseudoElement_MenuTearoff : PseudoElement_MenuScroller;
             QRenderRule subRule = renderRule(w, opt, pe);
             mi.rect = subRule.contentsRect(opt->rect);
             rule.configurePalette(&mi.palette, QPalette::ButtonText, QPalette::Button);
             subRule.configurePalette(&mi.palette, QPalette::ButtonText, QPalette::Button);
             if (subRule.hasDrawable()) {
                 subRule.drawRule(p, opt->rect);
             } else {
                 baseStyle()->drawControl(ce, &mi, p, w);
             }
         }
         return;
     case CE_MenuItem:
         if (const QStyleOptionMenuItem *m = qstyleoption_cast<const QStyleOptionMenuItem *>(opt)) {
             QStyleOptionMenuItem mi(*m);
             int pseudo = (mi.menuItemType == QStyleOptionMenuItem::Separator) ? PseudoElement_MenuSeparator : PseudoElement_Item;
             QRenderRule subRule = renderRule(w, opt, pseudo);
             mi.rect = subRule.contentsRect(opt->rect);
             rule.configurePalette(&mi.palette, QPalette::ButtonText, QPalette::Button);
             rule.configurePalette(&mi.palette, QPalette::HighlightedText, QPalette::Highlight);
             subRule.configurePalette(&mi.palette, QPalette::ButtonText, QPalette::Button);
             subRule.configurePalette(&mi.palette, QPalette::HighlightedText, QPalette::Highlight);
             QFont oldFont = p->font();
             if (subRule.hasFont)
                 p->setFont(subRule.font.resolve(p->font()));
             // We fall back to drawing with the style sheet code whenever at least one of the
             // items are styled in an incompatible way, such as having a background image.
             QRenderRule allRules = renderRule(w, PseudoElement_Item, PseudoClass_Any);
             if ((pseudo == PseudoElement_MenuSeparator) && subRule.hasDrawable()) {
                 subRule.drawRule(p, opt->rect);
             } else if ((pseudo == PseudoElement_Item)
                         && (allRules.hasBox() || allRules.hasBorder()
                             || (allRules.background() && !allRules.background()->pixmap.isNull()))) {
                 subRule.drawRule(p, opt->rect);
                 if (subRule.hasBackground()) {
                     mi.palette.setBrush(QPalette::Highlight, Qt::NoBrush);
                     mi.palette.setBrush(QPalette::Button, Qt::NoBrush);
                 } else {
                     mi.palette.setBrush(QPalette::Highlight, mi.palette.brush(QPalette::Button));
                 }
                 mi.palette.setBrush(QPalette::HighlightedText, mi.palette.brush(QPalette::ButtonText));
                 bool checkable = mi.checkType != QStyleOptionMenuItem::NotCheckable;
                 bool checked = checkable ? mi.checked : false;
                 bool dis = !(opt->state & QStyle::State_Enabled),
                      act = opt->state & QStyle::State_Selected;
                 if (!mi.icon.isNull()) {
                     QIcon::Mode mode = dis ? QIcon::Disabled : QIcon::Normal;
                     if (act && !dis)
                         mode = QIcon::Active;
                     QPixmap pixmap;
                     if (checked)
                         pixmap = mi.icon.pixmap(pixelMetric(PM_SmallIconSize), mode, QIcon::On);
                     else
                         pixmap = mi.icon.pixmap(pixelMetric(PM_SmallIconSize), mode);
                     int pixw = pixmap.width();
                     int pixh = pixmap.height();
                     QRenderRule iconRule = renderRule(w, opt, PseudoElement_MenuIcon);
                     if (!iconRule.hasGeometry()) {
                         iconRule.geo = new QStyleSheetGeometryData(pixw, pixh, pixw, pixh, -1, -1);
                     } else {
                         iconRule.geo->width = pixw;
                         iconRule.geo->height = pixh;
                     }
                     QRect iconRect = positionRect(w, subRule, iconRule, PseudoElement_MenuIcon, opt->rect, opt->direction);
                     iconRule.drawRule(p, iconRect);
                     QRect pmr(0, 0, pixw, pixh);
                     pmr.moveCenter(iconRect.center());
                     p->drawPixmap(pmr.topLeft(), pixmap);
                 } else if (checkable) {
                     QRenderRule subSubRule = renderRule(w, opt, PseudoElement_MenuCheckMark);
                     if (subSubRule.hasDrawable() || checked) {
                         QStyleOptionMenuItem newMi = mi;
                         newMi.rect = positionRect(w, subRule, subSubRule, PseudoElement_MenuCheckMark, opt->rect, opt->direction);
                         drawPrimitive(PE_IndicatorMenuCheckMark, &newMi, p, w);
                     }
                 }
                 QRect textRect = subRule.contentsRect(opt->rect);
                 textRect.setWidth(textRect.width() - mi.tabWidth);
                 QString s = mi.text;
                 p->setPen(mi.palette.buttonText().color());
                 if (!s.isEmpty()) {
                     int text_flags = Qt::AlignLeft | Qt::AlignVCenter | Qt::TextShowMnemonic | Qt::TextDontClip | Qt::TextSingleLine;
                     if (!styleHint(SH_UnderlineShortcut, &mi, w))
                         text_flags |= Qt::TextHideMnemonic;
                     int t = s.indexOf(QLatin1Char('\t'));
                     if (t >= 0) {
                         QRect vShortcutRect = visualRect(opt->direction, mi.rect,
                             QRect(textRect.topRight(), QPoint(mi.rect.right(), textRect.bottom())));
                         p->drawText(vShortcutRect, text_flags, s.mid(t + 1));
                         s = s.left(t);
                     }
                     p->drawText(textRect, text_flags, s.left(t));
                 }
                 if (mi.menuItemType == QStyleOptionMenuItem::SubMenu) {// draw sub menu arrow
                     PrimitiveElement arrow = (opt->direction == Qt::RightToLeft) ? PE_IndicatorArrowLeft : PE_IndicatorArrowRight;
                     QRenderRule subRule2 = renderRule(w, opt, PseudoElement_MenuRightArrow);
                     mi.rect = positionRect(w, subRule, subRule2, PseudoElement_MenuRightArrow, opt->rect, mi.direction);
                     drawPrimitive(arrow, &mi, p, w);
                 }
             } else if (hasStyleRule(w, PseudoElement_MenuCheckMark) || hasStyleRule(w, PseudoElement_MenuRightArrow)) {
                 QWindowsStyle::drawControl(ce, &mi, p, w);
                 if (mi.checkType != QStyleOptionMenuItem::NotCheckable && !mi.checked) {
                     // We have a style defined, but QWindowsStyle won't draw anything if not checked.
                     // So we mimick what QWindowsStyle would do.
                     int checkcol = qMax<int>(mi.maxIconWidth, QWindowsStylePrivate::windowsCheckMarkWidth);
                     QRect vCheckRect = visualRect(opt->direction, mi.rect, QRect(mi.rect.x(), mi.rect.y(), checkcol, mi.rect.height()));
                     if (mi.state.testFlag(State_Enabled) && mi.state.testFlag(State_Selected)) {
                         qDrawShadePanel(p, vCheckRect, mi.palette, true, 1, &mi.palette.brush(QPalette::Button));
                     } else {
                         QBrush fill(mi.palette.light().color(), Qt::Dense4Pattern);
                         qDrawShadePanel(p, vCheckRect, mi.palette, true, 1, &fill);
                     }
                     QRenderRule subSubRule = renderRule(w, opt, PseudoElement_MenuCheckMark);
                     if (subSubRule.hasDrawable()) {
                         QStyleOptionMenuItem newMi(mi);
                         newMi.rect = visualRect(opt->direction, mi.rect, QRect(mi.rect.x() + QWindowsStylePrivate::windowsItemFrame,
                                                                                mi.rect.y() + QWindowsStylePrivate::windowsItemFrame,
                                                                                checkcol - 2 * QWindowsStylePrivate::windowsItemFrame,
                                                                                mi.rect.height() - 2 * QWindowsStylePrivate::windowsItemFrame));
                         drawPrimitive(PE_IndicatorMenuCheckMark, &newMi, p, w);
                     }
                 }
             } else {
                 if (rule.hasDrawable() && !subRule.hasDrawable() && !(opt->state & QStyle::State_Selected)) {
                     mi.palette.setColor(QPalette::Window, Qt::transparent);
                     mi.palette.setColor(QPalette::Button, Qt::transparent);
                 }
                 if (rule.baseStyleCanDraw() && subRule.baseStyleCanDraw()) {
                     baseStyle()->drawControl(ce, &mi, p, w);
                 } else {
                     ParentStyle::drawControl(ce, &mi, p, w);
                 }
             }
             if (subRule.hasFont)
                 p->setFont(oldFont);
             return;
         }
         return;
     case CE_MenuBarItem:
         if (const QStyleOptionMenuItem *m = qstyleoption_cast<const QStyleOptionMenuItem *>(opt)) {
             QStyleOptionMenuItem mi(*m);
             QRenderRule subRule = renderRule(w, opt, PseudoElement_Item);
             mi.rect = subRule.contentsRect(opt->rect);
             rule.configurePalette(&mi.palette, QPalette::ButtonText, QPalette::Button);
             subRule.configurePalette(&mi.palette, QPalette::ButtonText, QPalette::Button);
             if (subRule.hasDrawable()) {
                 subRule.drawRule(p, opt->rect);
                 QCommonStyle::drawControl(ce, &mi, p, w);
             } else {
                 if (rule.hasDrawable() && !(opt->state & QStyle::State_Selected)) {
                     // So that the menu bar background is not hidden by the items
                     mi.palette.setColor(QPalette::Window, Qt::transparent);
                     mi.palette.setColor(QPalette::Button, Qt::transparent);
                 }
                 baseStyle()->drawControl(ce, &mi, p, w);
             }
         }
         return;
 #ifndef QT_NO_COMBOBOX
     case CE_ComboBoxLabel:
         if (!rule.hasBox())
             break;
         if (const QStyleOptionComboBox *cb = qstyleoption_cast<const QStyleOptionComboBox *>(opt)) {
             QRect editRect = subControlRect(CC_ComboBox, cb, SC_ComboBoxEditField, w);
             p->save();
             p->setClipRect(editRect);
             if (!cb->currentIcon.isNull()) {
                 int spacing = rule.hasBox() ? rule.box()->spacing : -1;
                 if (spacing == -1)
                     spacing = 6;
                 QIcon::Mode mode = cb->state & State_Enabled ? QIcon::Normal : QIcon::Disabled;
                 QPixmap pixmap = cb->currentIcon.pixmap(cb->iconSize, mode);
                 QRect iconRect(editRect);
                 iconRect.setWidth(cb->iconSize.width());
                 iconRect = alignedRect(cb->direction,
                                        Qt::AlignLeft | Qt::AlignVCenter,
                                        iconRect.size(), editRect);
                 drawItemPixmap(p, iconRect, Qt::AlignCenter, pixmap);
                 if (cb->direction == Qt::RightToLeft)
                         editRect.translate(-spacing - cb->iconSize.width(), 0);
                 else
                         editRect.translate(cb->iconSize.width() + spacing, 0);
             }
             if (!cb->currentText.isEmpty() && !cb->editable) {
                 QPalette styledPalette(cb->palette);
                 rule.configurePalette(&styledPalette, QPalette::Text, QPalette::Base);
                 drawItemText(p, editRect.adjusted(0, 0, 0, 0), Qt::AlignLeft | Qt::AlignVCenter, styledPalette,
                              cb->state & State_Enabled, cb->currentText, QPalette::Text);
             }
             p->restore();
             return;
         }
         break;
 #endif // QT_NO_COMBOBOX
     case CE_Header:
         if (hasStyleRule(w, PseudoElement_HeaderViewUpArrow)
             || hasStyleRule(w, PseudoElement_HeaderViewDownArrow)) {
             ParentStyle::drawControl(ce, opt, p, w);
             return;
         }
         if(hasStyleRule(w, PseudoElement_HeaderViewSection)) {
             QRenderRule subRule = renderRule(w, opt, PseudoElement_HeaderViewSection);
             if (!subRule.hasNativeBorder() || !subRule.baseStyleCanDraw()
                 || subRule.hasBackground() || subRule.hasPalette()) {
                 ParentStyle::drawControl(ce, opt, p, w);
                 return;
             }
         }
         break;
     case CE_HeaderSection:
         if (const QStyleOptionHeader *header = qstyleoption_cast<const QStyleOptionHeader *>(opt)) {
             QRenderRule subRule = renderRule(w, opt, PseudoElement_HeaderViewSection);
             if (subRule.hasNativeBorder()) {
                 QStyleOptionHeader hdr(*header);
                 subRule.configurePalette(&hdr.palette, QPalette::ButtonText, QPalette::Button);
                 if (subRule.baseStyleCanDraw()) {
                     baseStyle()->drawControl(CE_HeaderSection, &hdr, p, w);
                 } else {
                     QWindowsStyle::drawControl(CE_HeaderSection, &hdr, p, w);
                 }
             } else {
                 subRule.drawRule(p, opt->rect);
             }
             return;
         }
         break;
     case CE_HeaderLabel:
         if (const QStyleOptionHeader *header = qstyleoption_cast<const QStyleOptionHeader *>(opt)) {
             QStyleOptionHeader hdr(*header);
             QRenderRule subRule = renderRule(w, opt, PseudoElement_HeaderViewSection);
             subRule.configurePalette(&hdr.palette, QPalette::ButtonText, QPalette::Button);
             QFont oldFont = p->font();
             if (subRule.hasFont)
                 p->setFont(subRule.font.resolve(p->font()));
             baseStyle()->drawControl(ce, &hdr, p, w);
             if (subRule.hasFont)
                 p->setFont(oldFont);
             return;
         }
         break;
     case CE_HeaderEmptyArea:
         if (rule.hasDrawable()) {
             return;
         }
         break;
     case CE_ProgressBar:
         QWindowsStyle::drawControl(ce, opt, p, w);
         return;
     case CE_ProgressBarGroove:
         if (!rule.hasNativeBorder()) {
             rule.drawRule(p, rule.boxRect(opt->rect, Margin));
             return;
         }
         break;
     case CE_ProgressBarContents: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_ProgressBarChunk);
         if (subRule.hasDrawable()) {
             if (const QStyleOptionProgressBarV2 *pb = qstyleoption_cast<const QStyleOptionProgressBarV2 *>(opt)) {
                 p->save();
                 p->setClipRect(pb->rect);
                 qint64 minimum = qint64(pb->minimum);
                 qint64 maximum = qint64(pb->maximum);
                 qint64 progress = qint64(pb->progress);
                 bool vertical = (pb->orientation == Qt::Vertical);
                 bool inverted = pb->invertedAppearance;
                 QTransform m;
                 QRect rect = pb->rect;
                 if (vertical) {
                     rect = QRect(rect.y(), rect.x(), rect.height(), rect.width());
                     m.rotate(90);
                     m.translate(0, -(rect.height() + rect.y()*2));
                 }
                 bool reverse = ((!vertical && (pb->direction == Qt::RightToLeft)) || vertical);
                 if (inverted)
                     reverse = !reverse;
                 const bool indeterminate = pb->minimum == pb->maximum;
                 qreal fillRatio = indeterminate ? qreal(0.50) : qreal(progress - minimum)/(maximum - minimum);
                 int fillWidth = int(rect.width() * fillRatio);
                 int chunkWidth = fillWidth;
                 if (subRule.hasContentsSize()) {
                     QSize sz = subRule.size();
                     chunkWidth = (opt->state & QStyle::State_Horizontal) ? sz.width() : sz.height();
                 }
                 QRect r = rect;
                 if (pb->minimum == 0 && pb->maximum == 0) {
                     Q_D(const QWindowsStyle);
                     int chunkCount = fillWidth/chunkWidth;
                     int offset = (d->animateStep*8%rect.width());
                     int x = reverse ? r.left() + r.width() - offset - chunkWidth : r.x() + offset;
                     while (chunkCount > 0) {
                         r.setRect(x, rect.y(), chunkWidth, rect.height());
                         r = m.mapRect(QRectF(r)).toRect();
                         subRule.drawRule(p, r);
                         x += reverse ? -chunkWidth : chunkWidth;
                         if (reverse ? x < rect.left() : x > rect.right())
                             break;
                         --chunkCount;
                     }
                     r = rect;
                     x = reverse ? r.right() - (r.left() - x - chunkWidth)
                                 : r.left() + (x - r.right() - chunkWidth);
                     while (chunkCount > 0) {
                         r.setRect(x, rect.y(), chunkWidth, rect.height());
                         r = m.mapRect(QRectF(r)).toRect();
                         subRule.drawRule(p, r);
                         x += reverse ? -chunkWidth : chunkWidth;
                         --chunkCount;
                     };
                 } else {
                     int x = reverse ? r.left() + r.width() - chunkWidth : r.x();
                     for (int i = 0; i < ceil(qreal(fillWidth)/chunkWidth); ++i) {
                         r.setRect(x, rect.y(), chunkWidth, rect.height());
                         r = m.mapRect(QRectF(r)).toRect();
                         subRule.drawRule(p, r);
                         x += reverse ? -chunkWidth : chunkWidth;
                     }
                 }
                 p->restore();
                 return;
             }
         }
                                }
         break;
     case CE_ProgressBarLabel:
         if (const QStyleOptionProgressBarV2 *pb = qstyleoption_cast<const QStyleOptionProgressBarV2 *>(opt)) {
             if (rule.hasBox() || rule.hasBorder() || hasStyleRule(w, PseudoElement_ProgressBarChunk)) {
                 drawItemText(p, pb->rect, pb->textAlignment | Qt::TextSingleLine, pb->palette,
                              pb->state & State_Enabled, pb->text, QPalette::Text);
             } else {
                 QStyleOptionProgressBarV2 pbCopy(*pb);
                 rule.configurePalette(&pbCopy.palette, QPalette::HighlightedText, QPalette::Highlight);
                 baseStyle()->drawControl(ce, &pbCopy, p, w);
             }
             return;
         }
         break;
     case CE_SizeGrip:
         if (const QStyleOptionSizeGrip *sgOpt = qstyleoption_cast<const QStyleOptionSizeGrip *>(opt)) {
             if (rule.hasDrawable()) {
                 rule.drawFrame(p, opt->rect);
                 p->save();
                 switch (sgOpt->corner) {
                 case Qt::BottomRightCorner: break;
                 case Qt::BottomLeftCorner: p->rotate(90); break;
                 case Qt::TopLeftCorner: p->rotate(180); break;
                 case Qt::TopRightCorner: p->rotate(270); break;
                 default: break;
                 }
                 rule.drawImage(p, opt->rect);
                 p->restore();
             } else {
                 QStyleOptionSizeGrip sg(*sgOpt);
                 sg.rect = rule.contentsRect(opt->rect);
                 baseStyle()->drawControl(CE_SizeGrip, &sg, p, w);
             }
             return;
         }
         break;
     case CE_ToolBoxTab:
         QWindowsStyle::drawControl(ce, opt, p, w);
         return;
     case CE_ToolBoxTabShape: {
             QRenderRule subRule = renderRule(w, opt, PseudoElement_ToolBoxTab);
             if (subRule.hasDrawable()) {
                 subRule.drawRule(p, opt->rect);
                 return;
             }
                             }
         break;
     case CE_ToolBoxTabLabel:
         if (const QStyleOptionToolBox *box = qstyleoption_cast<const QStyleOptionToolBox *>(opt)) {
             QStyleOptionToolBox boxCopy(*box);
             QRenderRule subRule = renderRule(w, opt, PseudoElement_ToolBoxTab);
             subRule.configurePalette(&boxCopy.palette, QPalette::ButtonText, QPalette::Button);
             QFont oldFont = p->font();
             if (subRule.hasFont)
                 p->setFont(subRule.font);
             boxCopy.rect = subRule.contentsRect(opt->rect);
             QWindowsStyle::drawControl(ce, &boxCopy, p , w);
             if (subRule.hasFont)
                 p->setFont(oldFont);
             return;
         }
         break;
     case CE_ScrollBarAddPage:
         pe1 = PseudoElement_ScrollBarAddPage;
         break;
     case CE_ScrollBarSubPage:
         pe1 = PseudoElement_ScrollBarSubPage;
         break;
     case CE_ScrollBarAddLine:
         pe1 = PseudoElement_ScrollBarAddLine;
         pe2 = (opt->state & QStyle::State_Horizontal) ? PseudoElement_ScrollBarRightArrow : PseudoElement_ScrollBarDownArrow;
         fallback = true;
         break;
     case CE_ScrollBarSubLine:
         pe1 = PseudoElement_ScrollBarSubLine;
         pe2 = (opt->state & QStyle::State_Horizontal) ? PseudoElement_ScrollBarLeftArrow : PseudoElement_ScrollBarUpArrow;
         fallback = true;
         break;
     case CE_ScrollBarFirst:
         pe1 = PseudoElement_ScrollBarFirst;
         break;
     case CE_ScrollBarLast:
         pe1 = PseudoElement_ScrollBarLast;
         break;
     case CE_ScrollBarSlider:
         pe1 = PseudoElement_ScrollBarSlider;
         fallback = true;
         break;
 #ifndef QT_NO_ITEMVIEWS
     case CE_ItemViewItem:
         if (const QStyleOptionViewItemV4 *vopt = qstyleoption_cast<const QStyleOptionViewItemV4 *>(opt)) {
             QRenderRule subRule = renderRule(w, opt, PseudoElement_ViewItem);
             if (subRule.hasDrawable() || hasStyleRule(w, PseudoElement_Indicator)) {
                 QStyleOptionViewItemV4 optCopy(*vopt);
                 subRule.configurePalette(&optCopy.palette, vopt->state & QStyle::State_Selected ? QPalette::HighlightedText : QPalette::Text,
                                                            vopt->state & QStyle::State_Selected ? QPalette::Highlight : QPalette::Base);
                 QWindowsStyle::drawControl(ce, &optCopy, p, w);
             } else {
                 QStyleOptionViewItemV4 voptCopy(*vopt);
                 subRule.configurePalette(&voptCopy.palette, QPalette::Text, QPalette::NoRole);
                 baseStyle()->drawControl(ce, &voptCopy, p, w);
             }
             return;
         }
         break;
 #endif // QT_NO_ITEMVIEWS
 #ifndef QT_NO_TABBAR
     case CE_TabBarTab:
         if (hasStyleRule(w, PseudoElement_TabBarTab)) {
             QWindowsStyle::drawControl(ce, opt, p, w);
             return;
         }
         break;
     case CE_TabBarTabLabel:
     case CE_TabBarTabShape:
         if (const QStyleOptionTab *tab = qstyleoption_cast<const QStyleOptionTab *>(opt)) {
             QStyleOptionTabV3 tabCopy(*tab);
             QRenderRule subRule = renderRule(w, opt, PseudoElement_TabBarTab);
             QRect r = positionRect(w, subRule, PseudoElement_TabBarTab, opt->rect, opt->direction);
             if (ce == CE_TabBarTabShape && subRule.hasDrawable()) {
                 subRule.drawRule(p, r);
                 return;
             }
             subRule.configurePalette(&tabCopy.palette, QPalette::WindowText, QPalette::Window);
             QFont oldFont = p->font();
             if (subRule.hasFont)
                 p->setFont(subRule.font);
             if (subRule.hasBox() || !subRule.hasNativeBorder()) {
                 tabCopy.rect = ce == CE_TabBarTabShape ? subRule.borderRect(r)
                                                        : subRule.contentsRect(r);
                 QWindowsStyle::drawControl(ce, &tabCopy, p, w);
             } else {
                 baseStyle()->drawControl(ce, &tabCopy, p, w);
             }
             if (subRule.hasFont)
                 p->setFont(oldFont);
             return;
         }
        break;
 #endif // QT_NO_TABBAR
     case CE_ColumnViewGrip:
        if (rule.hasDrawable()) {
            rule.drawRule(p, opt->rect);
            return;
        }
        break;
     case CE_DockWidgetTitle:
        if (const QStyleOptionDockWidgetV2 *dwOpt = qstyleoption_cast<const QStyleOptionDockWidgetV2 *>(opt)) {
            QRenderRule subRule = renderRule(w, opt, PseudoElement_DockWidgetTitle);
            if (!subRule.hasDrawable() && !subRule.hasPosition())
                break;
            if (subRule.hasDrawable()) {
                subRule.drawRule(p, opt->rect);
            } else {
                QStyleOptionDockWidgetV2 dwCopy(*dwOpt);
                dwCopy.title = QString();
                baseStyle()->drawControl(ce, &dwCopy, p, w);
            }
            if (!dwOpt->title.isEmpty()) {
                QRect r = opt->rect;
                if (dwOpt->verticalTitleBar) {
                    QSize s = r.size();
                    s.transpose();
                    r.setSize(s);
                    p->save();
                    p->translate(r.left(), r.top() + r.width());
                    p->rotate(-90);
                    p->translate(-r.left(), -r.top());
                 }
                 Qt::Alignment alignment = 0;
                 if (subRule.hasPosition())
                     alignment = subRule.position()->textAlignment;
                 if (alignment == 0)
                     alignment = Qt::AlignLeft;
                 drawItemText(p, subRule.contentsRect(opt->rect),
                              alignment | Qt::TextShowMnemonic, dwOpt->palette,
                              dwOpt->state & State_Enabled, dwOpt->title,
                              QPalette::WindowText);
                 if (dwOpt->verticalTitleBar)
                     p->restore();
             }
            return;
         }
         break;
     case CE_ShapedFrame:
         if (const QStyleOptionFrame *frm = qstyleoption_cast<const QStyleOptionFrame *>(opt)) {
             if (rule.hasNativeBorder()) {
                 QStyleOptionFrameV3 frmOpt(*frm);
                 rule.configurePalette(&frmOpt.palette, QPalette::Text, QPalette::Base);
                 frmOpt.rect = rule.borderRect(frmOpt.rect);
                 baseStyle()->drawControl(ce, &frmOpt, p, w);
             }
             // else, borders are already drawn in PE_Widget
         }
         return;
     default:
         break;
     }
     if (pe1 != PseudoElement_None) {
         QRenderRule subRule = renderRule(w, opt, pe1);
         if (subRule.bg != 0 || subRule.hasDrawable()) {
             //We test subRule.bg directly because hasBackground() would return false for background:none.
             //But we still don't want the default drawning in that case (example for QScrollBar::add-page) (task 198926)
             subRule.drawRule(p, opt->rect);
         } else if (fallback) {
             QWindowsStyle::drawControl(ce, opt, p, w);
             pe2 = PseudoElement_None;
         } else {
             baseStyle()->drawControl(ce, opt, p, w);
         }
         if (pe2 != PseudoElement_None) {
             QRenderRule subSubRule = renderRule(w, opt, pe2);
             QRect r = positionRect(w, subRule, subSubRule, pe2, opt->rect, opt->direction);
             subSubRule.drawRule(p, r);
         }
         return;
     }
     baseStyle()->drawControl(ce, opt, p, w);
 }
drawItemPixmap()
void QStyleSheetStyle::drawItemPixmap (QPainter * painter, const QRect & rectangle, int alignment, const QPixmap & pixmap) const virtual
Draws the given pixmap in the specified rectangle, according to the specified alignment, using the provided painter.
See also
drawItemText()
Reimplemented from QStyle.
Definition at line 4118 of file qstylesheetstyle.cpp.
Referenced by drawComplexControl(), and drawControl().
 {
     baseStyle()->drawItemPixmap(p, rect, alignment, pixmap);
 }
drawItemText()
void QStyleSheetStyle::drawItemText (QPainter * painter, const QRect & rectangle, int alignment, const QPalette & palette, bool enabled, const QString & text, QPalette::ColorRole textRole = QPalette::NoRole) const virtual
Draws the given text in the specified rectangle using the provided painter and palette.
The text is drawn using the painter's pen, and aligned and wrapped according to the specified alignment. If an explicit textRole is specified, the text is drawn using the palette's color for the given role. The enabled parameter indicates whether or not the item is enabled; when reimplementing this function, the enabled parameter should influence how the item is drawn.
See also
Qt::Alignment, drawItemPixmap()
Reimplemented from QStyle.
Definition at line 4124 of file qstylesheetstyle.cpp.
Referenced by drawComplexControl(), and drawControl().
 {
     baseStyle()->drawItemText(painter, rect, alignment, pal, enabled, text, textRole);
 }
drawPrimitive()
void QStyleSheetStyle::drawPrimitive (PrimitiveElement pe, const QStyleOption * opt, QPainter * p, const QWidget * w = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 4130 of file qstylesheetstyle.cpp.
Referenced by drawComplexControl(), and drawControl().
 {
     RECURSION_GUARD(baseStyle()->drawPrimitive(pe, opt, p, w); return)
     int pseudoElement = PseudoElement_None;
     QRenderRule rule = renderRule(w, opt);
     QRect rect = opt->rect;
     switch (pe) {
     case PE_FrameStatusBar: {
         QRenderRule subRule = renderRule(w->parentWidget(), opt, PseudoElement_Item);
         if (subRule.hasDrawable()) {
             subRule.drawRule(p, opt->rect);
             return;
         }
         break;
                             }
     case PE_IndicatorArrowDown:
         pseudoElement = PseudoElement_DownArrow;
         break;
     case PE_IndicatorArrowUp:
         pseudoElement = PseudoElement_UpArrow;
         break;
     case PE_IndicatorRadioButton:
         pseudoElement = PseudoElement_ExclusiveIndicator;
         break;
     case PE_IndicatorViewItemCheck:
         pseudoElement = PseudoElement_ViewItemIndicator;
         break;
     case PE_IndicatorCheckBox:
         pseudoElement = PseudoElement_Indicator;
         break;
     case PE_IndicatorHeaderArrow:
         if (const QStyleOptionHeader *hdr = qstyleoption_cast<const QStyleOptionHeader *>(opt)) {
             pseudoElement = hdr->sortIndicator == QStyleOptionHeader::SortUp
                 ? PseudoElement_HeaderViewUpArrow
                 : PseudoElement_HeaderViewDownArrow;
         }
         break;
     case PE_PanelButtonTool:
     case PE_PanelButtonCommand:
         if (qobject_cast<const QAbstractButton *>(w) && rule.hasBackground() && rule.hasNativeBorder()) {
             //the window style will draw the borders
             ParentStyle::drawPrimitive(pe, opt, p, w);
             if (!rule.background()->pixmap.isNull() || rule.hasImage()) {
                 rule.drawRule(p, rule.boxRect(opt->rect, QRenderRule::Margin).adjusted(1,1,-1,-1));
             }
             return;
         }
         if (!rule.hasNativeBorder()) {
             rule.drawRule(p, rule.boxRect(opt->rect, QRenderRule::Margin));
             return;
         }
         break;
     case PE_IndicatorButtonDropDown: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_ToolButtonMenu);
         if (!subRule.hasNativeBorder()) {
             rule.drawBorder(p, opt->rect);
             return;
         }
         break;
                                      }
     case PE_FrameDefaultButton:
         if (rule.hasNativeBorder()) {
             if (rule.baseStyleCanDraw())
                 break;
             QWindowsStyle::drawPrimitive(pe, opt, p, w);
         }
         return;
     case PE_FrameWindow:
     case PE_FrameDockWidget:
     case PE_Frame:
         if (const QStyleOptionFrame *frm = qstyleoption_cast<const QStyleOptionFrame *>(opt)) {
             if (rule.hasNativeBorder()) {
                 QStyleOptionFrameV2 frmOpt(*frm);
                 rule.configurePalette(&frmOpt.palette, QPalette::Text, QPalette::Base);
                 if (!qstyleoption_cast<const QStyleOptionFrameV3 *>(opt)) //if it comes from  CE_ShapedFrame, the margins are already sustracted
                     frmOpt.rect = rule.borderRect(frmOpt.rect);
                 baseStyle()->drawPrimitive(pe, &frmOpt, p, w);
             } else {
                 rule.drawBorder(p, rule.borderRect(opt->rect));
             }
         }
         return;
     case PE_PanelLineEdit:
         if (const QStyleOptionFrame *frm = qstyleoption_cast<const QStyleOptionFrame *>(opt)) {
 #ifndef QT_NO_SPINBOX
             if (w && qobject_cast<const QAbstractSpinBox *>(w->parentWidget())) {
                 QRenderRule spinboxRule = renderRule(w->parentWidget(), opt);
                 if (!spinboxRule.hasNativeBorder() || !spinboxRule.baseStyleCanDraw())
                     return;
                 rule = spinboxRule;
             }
 #endif
             if (rule.hasNativeBorder()) {
                 QStyleOptionFrame frmOpt(*frm);
                 rule.configurePalette(&frmOpt.palette, QPalette::Text, QPalette::Base);
                 frmOpt.rect = rule.borderRect(frmOpt.rect);
                 if (rule.baseStyleCanDraw()) {
                     rule.drawBackgroundImage(p, opt->rect);
                     baseStyle()->drawPrimitive(pe, &frmOpt, p, w);
                 } else {
                     rule.drawBackground(p, opt->rect);
                     if (frmOpt.lineWidth > 0)
                         baseStyle()->drawPrimitive(PE_FrameLineEdit, &frmOpt, p, w);
                 }
             } else {
                 rule.drawRule(p, opt->rect);
             }
         }
         return;
     case PE_Widget:
         if (w && !rule.hasDrawable()) {
             QWidget *container = containerWidget(w);
             if (styleSheetCaches->autoFillDisabledWidgets.contains(container)
                 && (container == w || !renderRule(container, opt).hasBackground())) {
                 //we do not have a background, but we disabled the autofillbackground anyway. so fill the background now.
                 // (this may happen if we have rules like :focus)
                 p->fillRect(opt->rect, opt->palette.brush(w->backgroundRole()));
             }
             break;
         }
 #ifndef QT_NO_SCROLLAREA
         if (const QAbstractScrollArea *sa = qobject_cast<const QAbstractScrollArea *>(w)) {
             const QAbstractScrollAreaPrivate *sap = sa->d_func();
             rule.drawBackground(p, opt->rect, sap->contentsOffset());
             if (rule.hasBorder()) {
                 QRect brect = rule.borderRect(opt->rect);
                 if (styleHint(QStyle::SH_ScrollView_FrameOnlyAroundContents, opt, w)) {
                     QRect r = brect.adjusted(0, 0, sa->verticalScrollBar()->isVisible() ? -sa->verticalScrollBar()->width() : 0,
                                              sa->horizontalScrollBar()->isVisible() ? -sa->horizontalScrollBar()->height() : 0);
                     brect = QStyle::visualRect(opt->direction, brect, r);
                 }
                 rule.drawBorder(p, brect);
             }
             break;
         }
 #endif
     //fall tghought
     case PE_PanelMenu:
     case PE_PanelStatusBar:
         if(rule.hasDrawable()) {
             rule.drawRule(p, opt->rect);
             return;
         }
     break;
     case PE_FrameMenu:
         if (rule.hasDrawable()) {
             // Drawn by PE_PanelMenu
             return;
         }
         break;
     case PE_PanelMenuBar:
     if (rule.hasDrawable()) {
         // Drawn by PE_Widget
         return;
     }
     break;
     case PE_IndicatorToolBarSeparator:
     case PE_IndicatorToolBarHandle: {
         PseudoElement ps = pe == PE_IndicatorToolBarHandle ? PseudoElement_ToolBarHandle : PseudoElement_ToolBarSeparator;
         QRenderRule subRule = renderRule(w, opt, ps);
         if (subRule.hasDrawable()) {
             subRule.drawRule(p, opt->rect);
             return;
         }
                                     }
         break;
     case PE_IndicatorMenuCheckMark:
         pseudoElement = PseudoElement_MenuCheckMark;
         break;
     case PE_IndicatorArrowLeft:
         pseudoElement = PseudoElement_LeftArrow;
         break;
     case PE_IndicatorArrowRight:
         pseudoElement = PseudoElement_RightArrow;
         break;
     case PE_IndicatorColumnViewArrow:
         if (const QStyleOptionViewItem *viewOpt = qstyleoption_cast<const QStyleOptionViewItem *>(opt)) {
             bool reverse = (viewOpt->direction == Qt::RightToLeft);
             pseudoElement = reverse ? PseudoElement_LeftArrow : PseudoElement_RightArrow;
         } else {
             pseudoElement = PseudoElement_RightArrow;
         }
         break;
     case PE_IndicatorBranch:
         if (const QStyleOptionViewItemV2 *v2 = qstyleoption_cast<const QStyleOptionViewItemV2 *>(opt)) {
             QRenderRule subRule = renderRule(w, opt, PseudoElement_TreeViewBranch);
             if (subRule.hasDrawable()) {
                 if ((v2->state & QStyle::State_Selected) && v2->showDecorationSelected)
                     p->fillRect(v2->rect, v2->palette.highlight());
                 else if (v2->features & QStyleOptionViewItemV2::Alternate)
                     p->fillRect(v2->rect, v2->palette.alternateBase());
                 subRule.drawRule(p, opt->rect);
             } else {
                 baseStyle()->drawPrimitive(pe, v2, p, w);
             }
         }
         return;
     case PE_PanelTipLabel:
         if (!rule.hasDrawable())
             break;
         if (const QStyleOptionFrame *frmOpt = qstyleoption_cast<const QStyleOptionFrame *>(opt)) {
             if (rule.hasNativeBorder()) {
                 rule.drawBackground(p, opt->rect);
                 QStyleOptionFrame optCopy(*frmOpt);
                 optCopy.rect = rule.borderRect(opt->rect);
                 optCopy.palette.setBrush(QPalette::Window, Qt::NoBrush); // oh dear
                 baseStyle()->drawPrimitive(pe, &optCopy, p, w);
             } else {
                 rule.drawRule(p, opt->rect);
             }
         }
         return;
     case PE_FrameGroupBox:
         if (rule.hasNativeBorder())
             break;
         rule.drawBorder(p, opt->rect);
         return;
 #ifndef QT_NO_TABWIDGET
     case PE_FrameTabWidget:
         if (const QStyleOptionTabWidgetFrame *frm = qstyleoption_cast<const QStyleOptionTabWidgetFrame *>(opt)) {
             QRenderRule subRule = renderRule(w, opt, PseudoElement_TabWidgetPane);
             if (subRule.hasNativeBorder()) {
                 subRule.drawBackground(p, opt->rect);
                 QStyleOptionTabWidgetFrameV2 frmCopy(*frm);
                 subRule.configurePalette(&frmCopy.palette, QPalette::WindowText, QPalette::Window);
                 baseStyle()->drawPrimitive(pe, &frmCopy, p, w);
             } else {
                 subRule.drawRule(p, opt->rect);
             }
             return;
         }
         break;
 #endif // QT_NO_TABWIDGET
     case PE_IndicatorProgressChunk:
         pseudoElement = PseudoElement_ProgressBarChunk;
         break;
     case PE_IndicatorTabTear:
         pseudoElement = PseudoElement_TabBarTear;
         break;
     case PE_FrameFocusRect:
         if (!rule.hasNativeOutline()) {
             rule.drawOutline(p, opt->rect);
             return;
         }
         break;
     case PE_IndicatorDockWidgetResizeHandle:
         pseudoElement = PseudoElement_DockWidgetSeparator;
         break;
     case PE_PanelItemViewItem:
         pseudoElement = PseudoElement_ViewItem;
         break;
     case PE_PanelScrollAreaCorner:
         pseudoElement = PseudoElement_ScrollAreaCorner;
         break;
     case PE_IndicatorSpinDown:
     case PE_IndicatorSpinMinus:
         pseudoElement = PseudoElement_SpinBoxDownArrow;
         break;
     case PE_IndicatorSpinUp:
     case PE_IndicatorSpinPlus:
         pseudoElement = PseudoElement_SpinBoxUpArrow;
         break;
 #ifndef QT_NO_TABBAR
     case PE_IndicatorTabClose:
         if (w)
             w = w->parentWidget(); //match on the QTabBar instead of the CloseButton
         pseudoElement = PseudoElement_TabBarTabCloseButton;
 #endif
     default:
         break;
     }
     if (pseudoElement != PseudoElement_None) {
         QRenderRule subRule = renderRule(w, opt, pseudoElement);
         if (subRule.hasDrawable()) {
             subRule.drawRule(p, rect);
         } else {
             baseStyle()->drawPrimitive(pe, opt, p, w);
         }
     } else {
         baseStyle()->drawPrimitive(pe, opt, p, w);
     }
 }
event()
bool QStyleSheetStyle::event (QEvent * e) protected virtual
This virtual function receives events to an object and should return true if the event e was recognized and processed.
The event() function can be reimplemented to customize the behavior of an object.
See also
installEventFilter(), timerEvent(), QApplication::sendEvent(), QApplication::postEvent(), QWidget::event()
Reimplemented from QObject.
Definition at line 5804 of file qstylesheetstyle.cpp.
 {
     return (baseStyle()->event(e) && e->isAccepted()) || ParentStyle::event(e);
 }
generatedIconPixmap()
QPixmap QStyleSheetStyle::generatedIconPixmap (QIcon::Mode iconMode, const QPixmap & pixmap, const QStyleOption * opt) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 4451 of file qstylesheetstyle.cpp.
 {
     return baseStyle()->generatedIconPixmap(iconMode, pixmap, option);
 }
getDefaultStyleSheet()
StyleSheet QStyleSheetStyle::getDefaultStyleSheet () const private
Definition at line 147 of file qstylesheetstyle_default.cpp.
 {
     StyleSheet sheet;
     StyleRule styleRule;
     BasicSelector bSelector;
     Selector selector;
     Declaration decl;
     QCss::Value value;
     Pseudo pseudo;
     AttributeSelector attr;
     // pixmap based style doesn't support any features
     bool styleIsPixmapBased = baseStyle()->inherits("QMacStyle")
                            || baseStyle()->inherits("QWindowsXPStyle")
                            || baseStyle()->inherits("QGtkStyle")
                            || baseStyle()->inherits("QS60Style");
     /*QLineEdit {
         -qt-background-role: base;
         border: native;
         -qt-style-features: background-color;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QLineEdit"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("-qt-background-role"), QtBackgroundRole);
         ADD_VALUE(Value::KnownIdentifier, Value_Base);
         ADD_DECLARATION;
         SET_PROPERTY(QLatin1String("border"), Border);
         ADD_VALUE(Value::KnownIdentifier, Value_Native);
         ADD_DECLARATION;
         SET_PROPERTY(QLatin1String("-qt-style-features"), QtStyleFeatures);
         ADD_VALUE(Value::Identifier, QString::fromLatin1("background-color"));
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QLineEdit:no-frame {
         border: none;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QLineEdit"));
         ADD_PSEUDO(QLatin1String("no-frame"), PseudoClass_Frameless);
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("border"), Border);
         ADD_VALUE(Value::KnownIdentifier, Value_None);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QFrame {
         border: native;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QFrame"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("border"), Border);
         ADD_VALUE(Value::KnownIdentifier, Value_Native);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QLabel, QToolBox {
         background: none;
         border-image: none;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QLabel"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_ELEMENT_NAME(QLatin1String("QToolBox"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("background"), Background);
         ADD_VALUE(Value::KnownIdentifier, Value_None);
         ADD_DECLARATION;
         SET_PROPERTY(QLatin1String("border-image"), BorderImage);
         ADD_VALUE(Value::KnownIdentifier, Value_None);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QGroupBox {
         border: native;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QGroupBox"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("border"), Border);
         ADD_VALUE(Value::KnownIdentifier, Value_Native);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QToolTip {
         -qt-background-role: window;
         border: native;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QToolTip"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("-qt-background-role"), QtBackgroundRole);
         ADD_VALUE(Value::KnownIdentifier, Value_Window);
         ADD_DECLARATION;
         SET_PROPERTY(QLatin1String("border"), Border);
         ADD_VALUE(Value::KnownIdentifier, Value_Native);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QPushButton, QToolButton {
         border-style: native;
         -qt-style-features: background-color;  //only for not pixmap based styles
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QPushButton"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_ELEMENT_NAME(QLatin1String("QToolButton"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("border-style"), BorderStyles);
         ADD_VALUE(Value::KnownIdentifier, Value_Native);
         ADD_DECLARATION;
         if (!styleIsPixmapBased) {
             SET_PROPERTY(QLatin1String("-qt-style-features"), QtStyleFeatures);
             ADD_VALUE(Value::Identifier, QString::fromLatin1("background-color"));
             ADD_DECLARATION;
         }
         ADD_STYLE_RULE;
     }
     /*QComboBox {
         border: native;
         -qt-style-features: background-color background-gradient;   //only for not pixmap based styles
         -qt-background-role: base;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QComboBox"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("border"), Border);
         ADD_VALUE(Value::KnownIdentifier, Value_Native);
         ADD_DECLARATION;
         if (!styleIsPixmapBased) {
             SET_PROPERTY(QLatin1String("-qt-style-features"), QtStyleFeatures);
             ADD_VALUE(Value::Identifier, QString::fromLatin1("background-color"));
             ADD_VALUE(Value::Identifier, QString::fromLatin1("background-gradient"));
             ADD_DECLARATION;
         }
         SET_PROPERTY(QLatin1String("-qt-background-role"), QtBackgroundRole);
         ADD_VALUE(Value::KnownIdentifier, Value_Base);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QComboBox[style="QPlastiqueStyle"][readOnly="true"],
     QComboBox[style="QCleanlooksStyle"][readOnly="true"]
     {
         -qt-background-role: button;
     }*/
     if (baseStyle()->inherits("QPlastiqueStyle")  || baseStyle()->inherits("QCleanlooksStyle"))
     {
         SET_ELEMENT_NAME(QLatin1String("QComboBox"));
         ADD_ATTRIBUTE_SELECTOR(QLatin1String("readOnly"), QLatin1String("true"), AttributeSelector::MatchEqual);
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("-qt-background-role"), QtBackgroundRole);
         ADD_VALUE(Value::KnownIdentifier, Value_Button);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QAbstractSpinBox {
         border: native;
         -qt-style-features: background-color;
         -qt-background-role: base;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QAbstractSpinBox"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("border"), Border);
         ADD_VALUE(Value::KnownIdentifier, Value_Native);
         ADD_DECLARATION;
         SET_PROPERTY(QLatin1String("-qt-style-features"), QtStyleFeatures);
         ADD_VALUE(Value::Identifier, QString::fromLatin1("background-color"));
         ADD_DECLARATION;
         SET_PROPERTY(QLatin1String("-qt-background-role"), QtBackgroundRole);
         ADD_VALUE(Value::KnownIdentifier, Value_Base);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QMenu {
         -qt-background-role: window;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QMenu"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("-qt-background-role"), QtBackgroundRole);
         ADD_VALUE(Value::KnownIdentifier, Value_Window);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QMenu::item {
         -qt-style-features: background-color;
     }*/
     if (!styleIsPixmapBased) {
         SET_ELEMENT_NAME(QLatin1String("QMenu"));
         ADD_PSEUDO(QLatin1String("item"), PseudoClass_Unknown);
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("-qt-style-features"), QtStyleFeatures);
         ADD_VALUE(Value::Identifier, QString::fromLatin1("background-color"));
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QHeaderView {
         -qt-background-role: window;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QHeaderView"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("-qt-background-role"), QtBackgroundRole);
         ADD_VALUE(Value::KnownIdentifier, Value_Window);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QTableCornerButton::section, QHeaderView::section {
         -qt-background-role: button;
         -qt-style-features: background-color; //if style is not pixmap based
         border: native;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QTableCornerButton"));
         ADD_PSEUDO(QLatin1String("section"), PseudoClass_Unknown);
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_ELEMENT_NAME(QLatin1String("QHeaderView"));
         ADD_PSEUDO(QLatin1String("section"), PseudoClass_Unknown);
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("-qt-background-role"), QtBackgroundRole);
         ADD_VALUE(Value::KnownIdentifier, Value_Button);
         ADD_DECLARATION;
         if (!styleIsPixmapBased) {
             SET_PROPERTY(QLatin1String("-qt-style-features"), QtStyleFeatures);
             ADD_VALUE(Value::Identifier, QString::fromLatin1("background-color"));
             ADD_DECLARATION;
         }
         SET_PROPERTY(QLatin1String("border"), Border);
         ADD_VALUE(Value::KnownIdentifier, Value_Native);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QProgressBar {
         -qt-background-role: base;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QProgressBar"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("-qt-background-role"), QtBackgroundRole);
         ADD_VALUE(Value::KnownIdentifier, Value_Base);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QScrollBar {
         -qt-background-role: window;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QScrollBar"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("-qt-background-role"), QtBackgroundRole);
         ADD_VALUE(Value::KnownIdentifier, Value_Window);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     /*QDockWidget {
         border: native;
     }*/
     {
         SET_ELEMENT_NAME(QLatin1String("QDockWidget"));
         ADD_BASIC_SELECTOR;
         ADD_SELECTOR;
         SET_PROPERTY(QLatin1String("border"), Border);
         ADD_VALUE(Value::KnownIdentifier, Value_Native);
         ADD_DECLARATION;
         ADD_STYLE_RULE;
     }
     sheet.origin = StyleSheetOrigin_UserAgent;
     sheet.buildIndexes();
     return sheet;
 }
hasStyleRule()
bool QStyleSheetStyle::hasStyleRule (const QWidget * w, int part) const private
Definition at line 2029 of file qstylesheetstyle.cpp.
Referenced by drawComplexControl(), drawControl(), hitTestComplexControl(), pixelMetric(), sizeFromContents(), subControlRect(), and subElementRect().
 {
     QHash<int, bool> &cache = styleSheetCaches->hasStyleRuleCache[w];
     QHash<int, bool>::const_iterator cacheIt = cache.constFind(part);
     if (cacheIt != cache.constEnd())
         return cacheIt.value();
     if (!initWidget(w))
         return false;
     const QVector<StyleRule> &rules = styleRules(w);
     if (part == PseudoElement_None) {
         bool result = w && !rules.isEmpty();
         cache[part] = result;
         return result;
     }
     QString pseudoElement = QLatin1String(knownPseudoElements[part].name);
     QVector<Declaration> declarations;
     for (int i = 0; i < rules.count(); i++) {
         const Selector& selector = rules.at(i).selectors.at(0);
         if (pseudoElement.compare(selector.pseudoElement(), Qt::CaseInsensitive) == 0) {
             cache[part] = true;
             return true;
         }
     }
     cache[part] = false;
     return false;
 }
hitTestComplexControl()
QStyle::SubControl QStyleSheetStyle::hitTestComplexControl (ComplexControl cc, const QStyleOptionComplex * opt, const QPoint & pt, const QWidget * w = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 4457 of file qstylesheetstyle.cpp.
 {
     RECURSION_GUARD(return baseStyle()->hitTestComplexControl(cc, opt, pt, w))
     switch (cc) {
     case CC_TitleBar:
         if (const QStyleOptionTitleBar *tb = qstyleoption_cast<const QStyleOptionTitleBar *>(opt)) {
             QRenderRule rule = renderRule(w, opt, PseudoElement_TitleBar);
             if (rule.hasDrawable() || rule.hasBox() || rule.hasBorder()) {
                 QHash<QStyle::SubControl, QRect> layout = titleBarLayout(w, tb);
                 QRect r;
                 QStyle::SubControl sc = QStyle::SC_None;
                 uint ctrl = SC_TitleBarSysMenu;
                 while (ctrl <= SC_TitleBarLabel) {
                     r = layout[QStyle::SubControl(ctrl)];
                     if (r.isValid() && r.contains(pt)) {
                         sc = QStyle::SubControl(ctrl);
                         break;
                     }
                     ctrl <<= 1;
                 }
                 return sc;
             }
         }
         break;
     case CC_MdiControls:
         if (hasStyleRule(w, PseudoElement_MdiCloseButton)
             || hasStyleRule(w, PseudoElement_MdiNormalButton)
             || hasStyleRule(w, PseudoElement_MdiMinButton))
             return QWindowsStyle::hitTestComplexControl(cc, opt, pt, w);
         break;
     case CC_ScrollBar: {
         QRenderRule rule = renderRule(w, opt);
         if (!rule.hasDrawable() && !rule.hasBox())
             break;
                        }
         // intentionally falls through
     case CC_SpinBox:
     case CC_GroupBox:
     case CC_ComboBox:
     case CC_Slider:
     case CC_ToolButton:
         return QWindowsStyle::hitTestComplexControl(cc, opt, pt, w);
     default:
         break;
     }
     return baseStyle()->hitTestComplexControl(cc, opt, pt, w);
 }
initWidget()
bool QStyleSheetStyle::initWidget (const QWidget * w) const private
Make sure that the cache will be clean by connecting destroyed if needed.
return false if the widget is not stylable;
Definition at line 2657 of file qstylesheetstyle.cpp.
Referenced by polish().
 {
     if (!w)
         return false;
     if(w->testAttribute(Qt::WA_StyleSheet))
         return true;
     if(unstylable(w))
         return false;
     const_cast<QWidget *>(w)->setAttribute(Qt::WA_StyleSheet, true);
     QObject::connect(w, SIGNAL(destroyed(QObject*)), styleSheetCaches, SLOT(widgetDestroyed(QObject*)), Qt::UniqueConnection);
     return true;
 }
isNaturalChild()
bool QStyleSheetStyle::isNaturalChild (const QWidget * w) static private
Definition at line 5894 of file qstylesheetstyle.cpp.
Referenced by updateStyleSheetFont().
 {
     if (w->objectName().startsWith(QLatin1String("qt_")))
         return true;
     return false;
 }
itemPixmapRect()
QRect QStyleSheetStyle::itemPixmapRect (const QRect & r, int flags, const QPixmap & pixmap) const virtual
Returns the area within the given rectangle in which to draw the specified pixmap according to the defined alignment.
Reimplemented from QStyle.
Definition at line 4509 of file qstylesheetstyle.cpp.
 {
     return baseStyle()->itemPixmapRect(rect, alignment, pixmap);
 }
itemTextRect()
QRect QStyleSheetStyle::itemTextRect (const QFontMetrics & metrics, const QRect & rectangle, int alignment, bool enabled, const QString & text) const virtual
Returns the area within the given rectangle in which to draw the provided text according to the specified font metrics and alignment.
The enabled parameter indicates whether or not the associated item is enabled.
If the given rectangle is larger than the area needed to render the text, the rectangle that is returned will be offset within rectangle according to the specified alignment. For example, if alignment is Qt::AlignCenter, the returned rectangle will be centered within rectangle. If the given rectangle is smaller than the area needed, the returned rectangle will be the smallest rectangle large enough to render the text.
See also
Qt::Alignment
Reimplemented from QStyle.
Definition at line 4514 of file qstylesheetstyle.cpp.
 {
     return baseStyle()->itemTextRect(metrics, rect, alignment, enabled, text);
 }
layoutSpacing()
int QStyleSheetStyle::layoutSpacing (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption * option = 0, const QWidget * widget = 0) const
Definition at line 5107 of file qstylesheetstyle.cpp.
 {
     return baseStyle()->layoutSpacing(control1, control2, orientation, option, widget);
 }
layoutSpacingImplementation
int QStyleSheetStyle::layoutSpacingImplementation (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption * option = 0, const QWidget * widget = 0) const protected slot
Definition at line 5114 of file qstylesheetstyle.cpp.
 {
     return baseStyle()->layoutSpacing(control1, control2, orientation, option, widget);
 }
nativeFrameWidth()
int QStyleSheetStyle::nativeFrameWidth (const QWidget * w) private
Definition at line 1615 of file qstylesheetstyle.cpp.
Referenced by QRenderRule::QRenderRule().
 {
     QStyle *base = baseStyle();
 #ifndef QT_NO_SPINBOX
     if (qobject_cast<const QAbstractSpinBox *>(w))
         return base->pixelMetric(QStyle::PM_SpinBoxFrameWidth, 0, w);
 #endif
 #ifndef QT_NO_COMBOBOX
     if (qobject_cast<const QComboBox *>(w))
         return base->pixelMetric(QStyle::PM_ComboBoxFrameWidth, 0, w);
 #endif
 #ifndef QT_NO_MENU
     if (qobject_cast<const QMenu *>(w))
         return base->pixelMetric(QStyle::PM_MenuPanelWidth, 0, w);
 #endif
 #ifndef QT_NO_MENUBAR
     if (qobject_cast<const QMenuBar *>(w))
         return base->pixelMetric(QStyle::PM_MenuBarPanelWidth, 0, w);
 #endif
 #ifndef QT_NO_FRAME
     if (const QFrame *frame = qobject_cast<const QFrame *>(w)) {
         if (frame->frameShape() == QFrame::NoFrame)
             return 0;
     }
 #endif
     if (qstrcmp(w->metaObject()->className(), "QTipLabel") == 0)
         return base->pixelMetric(QStyle::PM_ToolTipLabelFrameWidth, 0, w);
     return base->pixelMetric(QStyle::PM_DefaultFrameWidth, 0, w);
 }
pixelMetric()
int QStyleSheetStyle::pixelMetric (PixelMetric m, const QStyleOption * opt = 0, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 4520 of file qstylesheetstyle.cpp.
Referenced by drawComplexControl(), drawControl(), sizeFromContents(), subControlRect(), and subElementRect().
 {
     RECURSION_GUARD(return baseStyle()->pixelMetric(m, opt, w))
     QRenderRule rule = renderRule(w, opt);
     QRenderRule subRule;
     switch (m) {
     case PM_MenuButtonIndicator:
 #ifndef QT_NO_TOOLBUTTON
         // QToolButton adds this directly to the width
         if (qobject_cast<const QToolButton *>(w) && (rule.hasBox() || !rule.hasNativeBorder()))
             return 0;
 #endif
         subRule = renderRule(w, opt, PseudoElement_PushButtonMenuIndicator);
         if (subRule.hasContentsSize())
             return subRule.size().width();
         break;
     case PM_ButtonShiftHorizontal:
     case PM_ButtonShiftVertical:
     case PM_ButtonMargin:
     case PM_ButtonDefaultIndicator:
         if (rule.hasBox())
             return 0;
         break;
     case PM_DefaultFrameWidth:
         if (!rule.hasNativeBorder())
             return rule.border()->borders[LeftEdge];
         break;
     case PM_ExclusiveIndicatorWidth:
     case PM_IndicatorWidth:
     case PM_ExclusiveIndicatorHeight:
     case PM_IndicatorHeight:
         subRule = renderRule(w, opt, PseudoElement_Indicator);
         if (subRule.hasContentsSize()) {
             return (m == PM_ExclusiveIndicatorWidth) || (m == PM_IndicatorWidth)
                         ? subRule.size().width() : subRule.size().height();
         }
         break;
     case PM_DockWidgetFrameWidth:
     case PM_ToolTipLabelFrameWidth: // border + margin + padding (support only one width)
         if (!rule.hasDrawable())
             break;
         return (rule.border() ? rule.border()->borders[LeftEdge] : 0)
                 + (rule.hasBox() ? rule.box()->margins[LeftEdge] + rule.box()->paddings[LeftEdge]: 0);
     case PM_ToolBarFrameWidth:
         if (rule.hasBorder() || rule.hasBox())
             return (rule.border() ? rule.border()->borders[LeftEdge] : 0)
                    + (rule.hasBox() ? rule.box()->paddings[LeftEdge]: 0);
         break;
     case PM_MenuPanelWidth:
     case PM_MenuBarPanelWidth:
         if (rule.hasBorder() || rule.hasBox())
             return (rule.border() ? rule.border()->borders[LeftEdge] : 0)
                    + (rule.hasBox() ? rule.box()->margins[LeftEdge]: 0);
         break;
     case PM_MenuHMargin:
     case PM_MenuBarHMargin:
         if (rule.hasBox())
             return rule.box()->paddings[LeftEdge];
         break;
     case PM_MenuVMargin:
     case PM_MenuBarVMargin:
         if (rule.hasBox())
             return rule.box()->paddings[TopEdge];
         break;
     case PM_DockWidgetTitleBarButtonMargin:
     case PM_ToolBarItemMargin:
         if (rule.hasBox())
             return rule.box()->margins[TopEdge];
         break;
     case PM_ToolBarItemSpacing:
     case PM_MenuBarItemSpacing:
         if (rule.hasBox() && rule.box()->spacing != -1)
             return rule.box()->spacing;
         break;
     case PM_MenuTearoffHeight:
     case PM_MenuScrollerHeight: {
         PseudoElement ps = m == PM_MenuTearoffHeight ? PseudoElement_MenuTearoff : PseudoElement_MenuScroller;
         subRule = renderRule(w, opt, ps);
         if (subRule.hasContentsSize())
             return subRule.size().height();
         break;
                                 }
     case PM_ToolBarExtensionExtent:
         break;
     case PM_SplitterWidth:
     case PM_ToolBarSeparatorExtent:
     case PM_ToolBarHandleExtent: {
         PseudoElement ps;
         if (m == PM_ToolBarHandleExtent) ps = PseudoElement_ToolBarHandle;
         else if (m == PM_SplitterWidth) ps = PseudoElement_SplitterHandle;
         else ps = PseudoElement_ToolBarSeparator;
         subRule = renderRule(w, opt, ps);
         if (subRule.hasContentsSize()) {
             QSize sz = subRule.size();
             return (opt && opt->state & QStyle::State_Horizontal) ? sz.width() : sz.height();
         }
         break;
                                  }
     case PM_RadioButtonLabelSpacing:
         if (rule.hasBox() && rule.box()->spacing != -1)
             return rule.box()->spacing;
         break;
     case PM_CheckBoxLabelSpacing:
         if (qobject_cast<const QCheckBox *>(w)) {
             if (rule.hasBox() && rule.box()->spacing != -1)
                 return rule.box()->spacing;
         }
         // assume group box
         subRule = renderRule(w, opt, PseudoElement_GroupBoxTitle);
         if (subRule.hasBox() && subRule.box()->spacing != -1)
             return subRule.box()->spacing;
         break;
 #ifndef QT_NO_SCROLLBAR
     case PM_ScrollBarExtent:
         if (rule.hasContentsSize()) {
             QSize sz = rule.size();
             if (const QStyleOptionSlider *sb = qstyleoption_cast<const QStyleOptionSlider *>(opt))
                 return sb->orientation == Qt::Horizontal ? sz.height() : sz.width();
             return sz.width() == -1 ? sz.height() : sz.width();
         }
         break;
     case PM_ScrollBarSliderMin:
         if (hasStyleRule(w, PseudoElement_ScrollBarSlider)) {
             subRule = renderRule(w, opt, PseudoElement_ScrollBarSlider);
             QSize msz = subRule.minimumSize();
             if (const QStyleOptionSlider *sb = qstyleoption_cast<const QStyleOptionSlider *>(opt))
                 return sb->orientation == Qt::Horizontal ? msz.width() : msz.height();
             return msz.width() == -1 ? msz.height() : msz.width();
         }
         break;
     case PM_ScrollView_ScrollBarSpacing:
         if(!rule.hasNativeBorder() || rule.hasBox())
             return 0;
         break;
 #endif // QT_NO_SCROLLBAR
     case PM_ProgressBarChunkWidth:
         subRule = renderRule(w, opt, PseudoElement_ProgressBarChunk);
         if (subRule.hasContentsSize()) {
             QSize sz = subRule.size();
             return (opt->state & QStyle::State_Horizontal)
                    ? sz.width() : sz.height();
         }
         break;
 #ifndef QT_NO_TABWIDGET
     case PM_TabBarTabHSpace:
     case PM_TabBarTabVSpace:
         subRule = renderRule(w, opt, PseudoElement_TabBarTab);
         if (subRule.hasBox() || subRule.hasBorder())
             return 0;
         break;
     case PM_TabBarScrollButtonWidth:   {
         subRule = renderRule(w, opt, PseudoElement_TabBarScroller);
         if (subRule.hasContentsSize()) {
             QSize sz = subRule.size();
             return sz.width() != -1 ? sz.width() : sz.height();
         }
                                         }
         break;
     case PM_TabBarTabShiftHorizontal:
     case PM_TabBarTabShiftVertical:
         subRule = renderRule(w, opt, PseudoElement_TabBarTab);
         if (subRule.hasBox())
             return 0;
         break;
     case PM_TabBarBaseOverlap: {
         const QWidget *tabWidget = qobject_cast<const QTabWidget *>(w) ? w : w->parentWidget();
         if (hasStyleRule(tabWidget, PseudoElement_TabWidgetPane)) {
             return 0;
         }
         break;
     }
 #endif // QT_NO_TABWIDGET
     case PM_SliderThickness: // horizontal slider's height (sizeHint)
     case PM_SliderLength: // minimum length of slider
         if (rule.hasContentsSize()) {
             bool horizontal = opt->state & QStyle::State_Horizontal;
             if (m == PM_SliderThickness) {
                 QSize sz = rule.size();
                 return horizontal ? sz.height() : sz.width();
             } else {
                 QSize msz = rule.minimumContentsSize();
                 return horizontal ? msz.width() : msz.height();
             }
         }
         break;
     case PM_SliderControlThickness: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_SliderHandle);
         if (!subRule.hasContentsSize())
             break;
         QSize size = subRule.size();
         return (opt->state & QStyle::State_Horizontal) ? size.height() : size.width();
                                     }
     case PM_ToolBarIconSize:
     case PM_ListViewIconSize:
     case PM_IconViewIconSize:
     case PM_TabBarIconSize:
     case PM_MessageBoxIconSize:
     case PM_ButtonIconSize:
     case PM_SmallIconSize:
         if (rule.hasStyleHint(QLatin1String("icon-size"))) {
             return rule.styleHint(QLatin1String("icon-size")).toSize().width();
         }
         break;
     case PM_DockWidgetTitleMargin: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_DockWidgetTitle);
         if (!subRule.hasBox())
             break;
         return (subRule.border() ? subRule.border()->borders[TopEdge] : 0)
                 + (subRule.hasBox() ? subRule.box()->margins[TopEdge] + subRule.box()->paddings[TopEdge]: 0);
                                    }
     case PM_DockWidgetSeparatorExtent: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_DockWidgetSeparator);
         if (!subRule.hasContentsSize())
             break;
         QSize sz = subRule.size();
         return qMax(sz.width(), sz.height());
                                         }
     case PM_TitleBarHeight: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_TitleBar);
         if (subRule.hasContentsSize())
             return subRule.size().height();
         else if (subRule.hasBox() || subRule.hasBorder()) {
             QFontMetrics fm = opt ?  opt->fontMetrics : w->fontMetrics();
             return subRule.size(QSize(0, fm.height())).height();
         }
         break;
                             }
     case PM_MdiSubWindowFrameWidth:
         if (rule.hasBox() || rule.hasBorder()) {
             return (rule.border() ? rule.border()->borders[LeftEdge] : 0)
                    + (rule.hasBox() ? rule.box()->paddings[LeftEdge]+rule.box()->margins[LeftEdge]: 0);
         }
         break;
     case PM_MdiSubWindowMinimizedWidth: {
         QRenderRule subRule = renderRule(w, PseudoElement_None, PseudoClass_Minimized);
         int width = subRule.size().width();
         if (width != -1)
             return width;
         break;
                                      }
     default:
         break;
     }
     return baseStyle()->pixelMetric(m, opt, w);
 }
polish() [1/3]
void QStyleSheetStyle::polish (QWidget * widget) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2672 of file qstylesheetstyle.cpp.
 {
     baseStyle()->polish(w);
     RECURSION_GUARD(return)
     if (!initWidget(w))
         return;
     if (styleSheetCaches->styleRulesCache.contains(w)) {
         // the widget accessed its style pointer before polish (or repolish)
         // (exemple: the QAbstractSpinBox constructor ask for the stylehint)
         styleSheetCaches->styleRulesCache.remove(w);
         styleSheetCaches->hasStyleRuleCache.remove(w);
         styleSheetCaches->renderRulesCache.remove(w);
     }
     setGeometry(w);
     setProperties(w);
     unsetPalette(w);
     setPalette(w);
     //set the WA_Hover attribute if one of the selector depends of the hover state
     QVector<StyleRule> rules = styleRules(w);
     for (int i = 0; i < rules.count(); i++) {
         const Selector& selector = rules.at(i).selectors.at(0);
         quint64 negated = 0;
         quint64 cssClass = selector.pseudoClass(&negated);
         if ( cssClass & PseudoClass_Hover || negated & PseudoClass_Hover) {
             w->setAttribute(Qt::WA_Hover);
             embeddedWidget(w)->setAttribute(Qt::WA_Hover);
         }
     }
 #ifndef QT_NO_SCROLLAREA
     if (QAbstractScrollArea *sa = qobject_cast<QAbstractScrollArea *>(w)) {
         QRenderRule rule = renderRule(sa, PseudoElement_None, PseudoClass_Enabled);
         if ((rule.hasBorder() && rule.border()->hasBorderImage())
             || (rule.hasBackground() && !rule.background()->pixmap.isNull())) {
             QObject::connect(sa->horizontalScrollBar(), SIGNAL(valueChanged(int)),
                              sa, SLOT(update()), Qt::UniqueConnection);
             QObject::connect(sa->verticalScrollBar(), SIGNAL(valueChanged(int)),
                              sa, SLOT(update()), Qt::UniqueConnection);
         }
     }
 #endif
 #ifndef QT_NO_PROGRESSBAR
     if (QProgressBar *pb = qobject_cast<QProgressBar *>(w)) {
         QWindowsStyle::polish(pb);
     }
 #endif
     QRenderRule rule = renderRule(w, PseudoElement_None, PseudoClass_Any);
     if (rule.hasDrawable() || rule.hasBox()) {
         if (w->metaObject() == &QWidget::staticMetaObject
 #ifndef QT_NO_ITEMVIEWS
               || qobject_cast<QHeaderView *>(w)
 #endif
 #ifndef QT_NO_TABBAR
               || qobject_cast<QTabBar *>(w)
 #endif
 #ifndef QT_NO_FRAME
               || qobject_cast<QFrame *>(w)
 #endif
 #ifndef QT_NO_MAINWINDOW
               || qobject_cast<QMainWindow *>(w)
 #endif
 #ifndef QT_NO_MDIAREA
               || qobject_cast<QMdiSubWindow *>(w)
 #endif
 #ifndef QT_NO_MENUBAR
               || qobject_cast<QMenuBar *>(w)
 #endif
               || qobject_cast<QDialog *>(w)) {
             w->setAttribute(Qt::WA_StyledBackground, true);
         }
         QWidget *ew = embeddedWidget(w);
         if (ew->autoFillBackground()) {
             ew->setAutoFillBackground(false);
             styleSheetCaches->autoFillDisabledWidgets.insert(w);
             if (ew != w) { //eg. viewport of a scrollarea
                 //(in order to draw the background anyway in case we don't.)
                 ew->setAttribute(Qt::WA_StyledBackground, true);
             }
         }
         if (!rule.hasBackground() || rule.background()->isTransparent() || rule.hasBox()
             || (!rule.hasNativeBorder() && !rule.border()->isOpaque()))
             w->setAttribute(Qt::WA_OpaquePaintEvent, false);
     }
 }
polish() [2/3]
void QStyleSheetStyle::polish (QApplication * app) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2763 of file qstylesheetstyle.cpp.
 {
     baseStyle()->polish(app);
 }
polish() [3/3]
void QStyleSheetStyle::polish (QPalette & pal) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2768 of file qstylesheetstyle.cpp.
 {
     baseStyle()->polish(pal);
 }
positionRect() [1/2]
QRect QStyleSheetStyle::positionRect (const QWidget * w, const QRenderRule & rule1, const QRenderRule & rule2, int pe, const QRect & rect, Qt::LayoutDirection dir) const private
Definition at line 2311 of file qstylesheetstyle.cpp.
Referenced by drawComplexControl(), drawControl(), sizeFromContents(), subControlRect(), and subElementRect().
 {
     const QStyleSheetPositionData *p = rule2.position();
     Origin origin = (p && p->origin != Origin_Unknown) ? p->origin : defaultOrigin(pe);
     QRect originRect = rule1.originRect(rect, origin);
     return positionRect(w, rule2, pe, originRect, dir);
 }
positionRect() [2/2]
QRect QStyleSheetStyle::positionRect (const QWidget * w, const QRenderRule & rule2, int pe, const QRect & originRect, Qt::LayoutDirection dir) const private
Definition at line 2280 of file qstylesheetstyle.cpp.
 {
     const QStyleSheetPositionData *p = rule2.position();
     PositionMode mode = (p && p->mode != PositionMode_Unknown) ? p->mode : defaultPositionMode(pe);
     Qt::Alignment position = (p && p->position != 0) ? p->position : defaultPosition(pe);
     QRect r;
     if (mode != PositionMode_Absolute) {
         QSize sz = defaultSize(w, rule2.size(), originRect, pe);
         sz = sz.expandedTo(rule2.minimumContentsSize());
         r = QStyle::alignedRect(dir, position, sz, originRect);
         if (p) {
             int left = p->left ? p->left : -p->right;
             int top = p->top ? p->top : -p->bottom;
             r.translate(dir == Qt::LeftToRight ? left : -left, top);
         }
     } else {
         r = p ? originRect.adjusted(dir == Qt::LeftToRight ? p->left : p->right, p->top,
                                    dir == Qt::LeftToRight ? -p->right : -p->left, -p->bottom)
               : originRect;
         if (rule2.hasContentsSize()) {
             QSize sz = rule2.size().expandedTo(rule2.minimumContentsSize());
             if (sz.width() == -1) sz.setWidth(r.width());
             if (sz.height() == -1) sz.setHeight(r.height());
             r = QStyle::alignedRect(dir, position, sz, r);
         }
     }
     return r;
 }
ref()
void QStyleSheetStyle::ref () inline
Definition at line 127 of file qstylesheetstyle_p.h.
 { ++refcount; }
renderRule() [1/2]
QRenderRule QStyleSheetStyle::renderRule (const QWidget * w, int element, quint64 state = 0) const private
Definition at line 1717 of file qstylesheetstyle.cpp.
Referenced by drawComplexControl(), drawControl(), drawPrimitive(), hitTestComplexControl(), pixelMetric(), polish(), sizeFromContents(), standardIconImplementation(), standardPixmap(), styleHint(), styleSheetPalette(), subControlRect(), subElementRect(), and updateStyleSheetFont().
 {
     qt_check_if_internal_widget(&w, &element);
     QHash<quint64, QRenderRule> &cache = styleSheetCaches->renderRulesCache[w][element];
     QHash<quint64, QRenderRule>::const_iterator cacheIt = cache.constFind(state);
     if (cacheIt != cache.constEnd())
         return cacheIt.value();
     if (!initWidget(w))
         return QRenderRule();
     quint64 stateMask = 0;
     const QVector<StyleRule> rules = styleRules(w);
     for (int i = 0; i < rules.count(); i++) {
         const Selector& selector = rules.at(i).selectors.at(0);
         quint64 negated = 0;
         stateMask |= selector.pseudoClass(&negated);
         stateMask |= negated;
     }
     cacheIt = cache.constFind(state & stateMask);
     if (cacheIt != cache.constEnd()) {
         const QRenderRule &newRule = cacheIt.value();
         cache[state] = newRule;
         return newRule;
     }
     const QString part = QLatin1String(knownPseudoElements[element].name);
     QVector<Declaration> decls = declarations(rules, part, state);
     QRenderRule newRule(decls, w);
     cache[state] = newRule;
     if ((state & stateMask) != state)
         cache[state&stateMask] = newRule;
     return newRule;
 }
renderRule() [2/2]
QRenderRule QStyleSheetStyle::renderRule (const QWidget * w, const QStyleOption * opt, int pseudoElement = 0) const private
Definition at line 1754 of file qstylesheetstyle.cpp.
 {
     quint64 extraClass = 0;
     QStyle::State state = opt ? opt->state : QStyle::State(QStyle::State_None);
     if (const QStyleOptionComplex *complex = qstyleoption_cast<const QStyleOptionComplex *>(opt)) {
         if (pseudoElement != PseudoElement_None) {
             // if not an active subcontrol, just pass enabled/disabled
             QStyle::SubControl subControl = knownPseudoElements[pseudoElement].subControl;
             if (!(complex->activeSubControls & subControl))
                 state &= (QStyle::State_Enabled | QStyle::State_Horizontal | QStyle::State_HasFocus);
         }
         switch (pseudoElement) {
         case PseudoElement_ComboBoxDropDown:
         case PseudoElement_ComboBoxArrow:
             state |= (complex->state & (QStyle::State_On|QStyle::State_ReadOnly));
             break;
         case PseudoElement_SpinBoxUpButton:
         case PseudoElement_SpinBoxDownButton:
         case PseudoElement_SpinBoxUpArrow:
         case PseudoElement_SpinBoxDownArrow:
 #ifndef QT_NO_SPINBOX
             if (const QStyleOptionSpinBox *sb = qstyleoption_cast<const QStyleOptionSpinBox *>(opt)) {
                 bool on = false;
                 bool up = pseudoElement == PseudoElement_SpinBoxUpButton
                           || pseudoElement == PseudoElement_SpinBoxUpArrow;
                 if ((sb->stepEnabled & QAbstractSpinBox::StepUpEnabled) && up)
                     on = true;
                 else if ((sb->stepEnabled & QAbstractSpinBox::StepDownEnabled) && !up)
                     on = true;
                 state |= (on ? QStyle::State_On : QStyle::State_Off);
             }
 #endif // QT_NO_SPINBOX
             break;
         case PseudoElement_GroupBoxTitle:
             state |= (complex->state & (QStyle::State_MouseOver | QStyle::State_Sunken));
             break;
         case PseudoElement_ToolButtonMenu:
         case PseudoElement_ToolButtonMenuArrow:
         case PseudoElement_ToolButtonDownArrow:
             state |= complex->state & QStyle::State_MouseOver;
             if (complex->state & QStyle::State_Sunken ||
                 complex->activeSubControls & QStyle::SC_ToolButtonMenu)
                 state |= QStyle::State_Sunken;
             break;
         case PseudoElement_SliderGroove:
             state |= complex->state & QStyle::State_MouseOver;
             break;
         default:
             break;
         }
         if (const QStyleOptionComboBox *combo = qstyleoption_cast<const QStyleOptionComboBox *>(opt)) {
             // QStyle::State_On is set when the popup is being shown
             // Propagate EditField Pressed state
             if (pseudoElement == PseudoElement_None
                 && (complex->activeSubControls & QStyle::SC_ComboBoxEditField)
                 && (!(state & QStyle::State_MouseOver))) {
                 state |= QStyle::State_Sunken;
             }
             if (!combo->frame)
                 extraClass |= PseudoClass_Frameless;
             if (!combo->editable)
                 extraClass |= PseudoClass_ReadOnly;
             else
                 extraClass |= PseudoClass_Editable;
 #ifndef QT_NO_SPINBOX
         } else if (const QStyleOptionSpinBox *spin = qstyleoption_cast<const QStyleOptionSpinBox *>(opt)) {
             if (!spin->frame)
                 extraClass |= PseudoClass_Frameless;
 #endif // QT_NO_SPINBOX
         } else if (const QStyleOptionGroupBox *gb = qstyleoption_cast<const QStyleOptionGroupBox *>(opt)) {
             if (gb->features & QStyleOptionFrameV2::Flat)
                 extraClass |= PseudoClass_Flat;
             if (gb->lineWidth == 0)
                 extraClass |= PseudoClass_Frameless;
         } else if (const QStyleOptionTitleBar *tb = qstyleoption_cast<const QStyleOptionTitleBar *>(opt)) {
             if (tb->titleBarState & Qt::WindowMinimized) {
                 extraClass |= PseudoClass_Minimized;
             }
             else if (tb->titleBarState & Qt::WindowMaximized)
                 extraClass |= PseudoClass_Maximized;
         }
     } else {
         // handle simple style options
         if (const QStyleOptionMenuItem *mi = qstyleoption_cast<const QStyleOptionMenuItem *>(opt)) {
             if (mi->menuItemType == QStyleOptionMenuItem::DefaultItem)
                 extraClass |= PseudoClass_Default;
             if (mi->checkType == QStyleOptionMenuItem::Exclusive)
                 extraClass |= PseudoClass_Exclusive;
             else if (mi->checkType == QStyleOptionMenuItem::NonExclusive)
                 extraClass |= PseudoClass_NonExclusive;
             if (mi->checkType != QStyleOptionMenuItem::NotCheckable)
                 extraClass |= (mi->checked) ? (PseudoClass_On|PseudoClass_Checked)
                                             : (PseudoClass_Off|PseudoClass_Unchecked);
         } else if (const QStyleOptionHeader *hdr = qstyleoption_cast<const QStyleOptionHeader *>(opt)) {
             if (hdr->position == QStyleOptionHeader::OnlyOneSection)
                 extraClass |= PseudoClass_OnlyOne;
             else if (hdr->position == QStyleOptionHeader::Beginning)
                 extraClass |= PseudoClass_First;
             else if (hdr->position == QStyleOptionHeader::End)
                 extraClass |= PseudoClass_Last;
             else if (hdr->position == QStyleOptionHeader::Middle)
                 extraClass |= PseudoClass_Middle;
             if (hdr->selectedPosition == QStyleOptionHeader::NextAndPreviousAreSelected)
                 extraClass |= (PseudoClass_NextSelected | PseudoClass_PreviousSelected);
             else if (hdr->selectedPosition == QStyleOptionHeader::NextIsSelected)
                 extraClass |= PseudoClass_NextSelected;
             else if (hdr->selectedPosition == QStyleOptionHeader::PreviousIsSelected)
                 extraClass |= PseudoClass_PreviousSelected;
 #ifndef QT_NO_TABWIDGET
         } else if (const QStyleOptionTabWidgetFrame *tab = qstyleoption_cast<const QStyleOptionTabWidgetFrame *>(opt)) {
             switch (tab->shape) {
                 case QTabBar::RoundedNorth:
                 case QTabBar::TriangularNorth:
                     extraClass |= PseudoClass_Top;
                     break;
                 case QTabBar::RoundedSouth:
                 case QTabBar::TriangularSouth:
                     extraClass |= PseudoClass_Bottom;
                     break;
                 case QTabBar::RoundedEast:
                 case QTabBar::TriangularEast:
                     extraClass |= PseudoClass_Left;
                     break;
                 case QTabBar::RoundedWest:
                 case QTabBar::TriangularWest:
                     extraClass |= PseudoClass_Right;
                     break;
                 default:
                     break;
             }
 #endif
 #ifndef QT_NO_TABBAR
         } else if (const QStyleOptionTab *tab = qstyleoption_cast<const QStyleOptionTab *>(opt)) {
             if (tab->position == QStyleOptionTab::OnlyOneTab)
                 extraClass |= PseudoClass_OnlyOne;
             else if (tab->position == QStyleOptionTab::Beginning)
                 extraClass |= PseudoClass_First;
             else if (tab->position == QStyleOptionTab::End)
                 extraClass |= PseudoClass_Last;
             else if (tab->position == QStyleOptionTab::Middle)
                 extraClass |= PseudoClass_Middle;
             if (tab->selectedPosition == QStyleOptionTab::NextIsSelected)
                 extraClass |= PseudoClass_NextSelected;
             else if (tab->selectedPosition == QStyleOptionTab::PreviousIsSelected)
                 extraClass |= PseudoClass_PreviousSelected;
             switch (tab->shape) {
                 case QTabBar::RoundedNorth:
                 case QTabBar::TriangularNorth:
                     extraClass |= PseudoClass_Top;
                     break;
                 case QTabBar::RoundedSouth:
                 case QTabBar::TriangularSouth:
                     extraClass |= PseudoClass_Bottom;
                     break;
                 case QTabBar::RoundedEast:
                 case QTabBar::TriangularEast:
                     extraClass |= PseudoClass_Left;
                     break;
                 case QTabBar::RoundedWest:
                 case QTabBar::TriangularWest:
                     extraClass |= PseudoClass_Right;
                     break;
                 default:
                     break;
             }
 #endif // QT_NO_TABBAR
         } else if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(opt)) {
             if (btn->features & QStyleOptionButton::Flat)
                 extraClass |= PseudoClass_Flat;
             if (btn->features & QStyleOptionButton::DefaultButton)
                 extraClass |= PseudoClass_Default;
         } else if (const QStyleOptionFrame *frm = qstyleoption_cast<const QStyleOptionFrame *>(opt)) {
             if (frm->lineWidth == 0)
                 extraClass |= PseudoClass_Frameless;
             if (const QStyleOptionFrameV2 *frame2 = qstyleoption_cast<const QStyleOptionFrameV2 *>(opt)) {
                 if (frame2->features & QStyleOptionFrameV2::Flat)
                     extraClass |= PseudoClass_Flat;
             }
         }
 #ifndef QT_NO_TOOLBAR
         else if (const QStyleOptionToolBar *tb = qstyleoption_cast<const QStyleOptionToolBar *>(opt)) {
             if (tb->toolBarArea == Qt::LeftToolBarArea)
                 extraClass |= PseudoClass_Left;
             else if (tb->toolBarArea == Qt::RightToolBarArea)
                 extraClass |= PseudoClass_Right;
             else if (tb->toolBarArea == Qt::TopToolBarArea)
                 extraClass |= PseudoClass_Top;
             else if (tb->toolBarArea == Qt::BottomToolBarArea)
                 extraClass |= PseudoClass_Bottom;
             if (tb->positionWithinLine == QStyleOptionToolBar::Beginning)
                 extraClass |= PseudoClass_First;
             else if (tb->positionWithinLine == QStyleOptionToolBar::Middle)
                 extraClass |= PseudoClass_Middle;
             else if (tb->positionWithinLine == QStyleOptionToolBar::End)
                 extraClass |= PseudoClass_Last;
             else if (tb->positionWithinLine == QStyleOptionToolBar::OnlyOne)
                 extraClass |= PseudoClass_OnlyOne;
         }
 #endif // QT_NO_TOOLBAR
 #ifndef QT_NO_TOOLBOX
         else if (const QStyleOptionToolBoxV2 *tab = qstyleoption_cast<const QStyleOptionToolBoxV2 *>(opt)) {
             if (tab->position == QStyleOptionToolBoxV2::OnlyOneTab)
                 extraClass |= PseudoClass_OnlyOne;
             else if (tab->position == QStyleOptionToolBoxV2::Beginning)
                 extraClass |= PseudoClass_First;
             else if (tab->position == QStyleOptionToolBoxV2::End)
                 extraClass |= PseudoClass_Last;
             else if (tab->position == QStyleOptionToolBoxV2::Middle)
                 extraClass |= PseudoClass_Middle;
             if (tab->selectedPosition == QStyleOptionToolBoxV2::NextIsSelected)
                 extraClass |= PseudoClass_NextSelected;
             else if (tab->selectedPosition == QStyleOptionToolBoxV2::PreviousIsSelected)
                 extraClass |= PseudoClass_PreviousSelected;
         }
 #endif // QT_NO_TOOLBOX
 #ifndef QT_NO_DOCKWIDGET
         else if (const QStyleOptionDockWidgetV2 *dw = qstyleoption_cast<const QStyleOptionDockWidgetV2 *>(opt)) {
             if (dw->verticalTitleBar)
                 extraClass |= PseudoClass_Vertical;
             else
                 extraClass |= PseudoClass_Horizontal;
             if (dw->closable)
                 extraClass |= PseudoClass_Closable;
             if (dw->floatable)
                 extraClass |= PseudoClass_Floatable;
             if (dw->movable)
                 extraClass |= PseudoClass_Movable;
         }
 #endif // QT_NO_DOCKWIDGET
 #ifndef QT_NO_ITEMVIEWS
         else if (const QStyleOptionViewItemV2 *v2 = qstyleoption_cast<const QStyleOptionViewItemV2 *>(opt)) {
             if (v2->features & QStyleOptionViewItemV2::Alternate)
                 extraClass |= PseudoClass_Alternate;
             if (const QStyleOptionViewItemV4 *v4 = qstyleoption_cast<const QStyleOptionViewItemV4 *>(opt)) {
                 if (v4->viewItemPosition == QStyleOptionViewItemV4::OnlyOne)
                     extraClass |= PseudoClass_OnlyOne;
                 else if (v4->viewItemPosition == QStyleOptionViewItemV4::Beginning)
                     extraClass |= PseudoClass_First;
                 else if (v4->viewItemPosition == QStyleOptionViewItemV4::End)
                     extraClass |= PseudoClass_Last;
                 else if (v4->viewItemPosition == QStyleOptionViewItemV4::Middle)
                     extraClass |= PseudoClass_Middle;
             }
         }
 #endif
 #ifndef QT_NO_LINEEDIT
         // LineEdit sets Sunken flag to indicate Sunken frame (argh)
         if (const QLineEdit *lineEdit = qobject_cast<const QLineEdit *>(w)) {
             state &= ~QStyle::State_Sunken;
             if (lineEdit->hasFrame()) {
                 extraClass &= ~PseudoClass_Frameless;
             } else {
                 extraClass |= PseudoClass_Frameless;
             }
         } else
 #endif
         if (const QFrame *frm = qobject_cast<const QFrame *>(w)) {
             if (frm->lineWidth() == 0)
                 extraClass |= PseudoClass_Frameless;
         }
     }
     return renderRule(w, pseudoElement, pseudoClass(state) | extraClass);
 }
repolish() [1/2]
void QStyleSheetStyle::repolish (QWidget * widget)
Definition at line 2773 of file qstylesheetstyle.cpp.
Referenced by QWidgetPrivate::inheritStyle(), QApplication::setStyleSheet(), and QWidget::setStyleSheet().
 {
     QList<const QWidget *> children = w->findChildren<const QWidget *>(QString());
     children.append(w);
     styleSheetCaches->styleSheetCache.remove(w);
     updateWidgets(children);
 }
repolish() [2/2]
void QStyleSheetStyle::repolish (QApplication * app)
Definition at line 2781 of file qstylesheetstyle.cpp.
 {
     Q_UNUSED(app);
     const QList<const QWidget*> allWidgets = styleSheetCaches->styleRulesCache.keys();
     styleSheetCaches->styleSheetCache.remove(qApp);
     styleSheetCaches->styleRulesCache.clear();
     styleSheetCaches->hasStyleRuleCache.clear();
     styleSheetCaches->renderRulesCache.clear();
     updateWidgets(allWidgets);
 }
resolveAlignment()
Qt::Alignment QStyleSheetStyle::resolveAlignment (Qt::LayoutDirection layDir, Qt::Alignment src) static private
Definition at line 5872 of file qstylesheetstyle.cpp.
Referenced by subControlRect().
 {
     if (layDir == Qt::LeftToRight || src & Qt::AlignAbsolute)
         return src;
     if (src & Qt::AlignLeft) {
         src &= ~Qt::AlignLeft;
         src |= Qt::AlignRight;
     } else if (src & Qt::AlignRight) {
         src &= ~Qt::AlignRight;
         src |= Qt::AlignLeft;
     }
     src |= Qt::AlignAbsolute;
     return src;
 }
saveWidgetFont()
void QStyleSheetStyle::saveWidgetFont (QWidget * w, const QFont & font) const
Definition at line 5841 of file qstylesheetstyle.cpp.
Referenced by QWidget::setFont().
 {
     w->setProperty("_q_styleSheetWidgetFont", font);
 }
setGeometry()
void QStyleSheetStyle::setGeometry (QWidget * w) private
Definition at line 2437 of file qstylesheetstyle.cpp.
Referenced by polish().
 {
     QRenderRule rule = renderRule(w, PseudoElement_None, PseudoClass_Enabled | extendedPseudoClass(w));
     const QStyleSheetGeometryData *geo = rule.geometry();
     if (w->property("_q_stylesheet_minw").toBool()
         && ((!rule.hasGeometry() || geo->minWidth == -1))) {
             w->setMinimumWidth(0);
             w->setProperty("_q_stylesheet_minw", QVariant());
     }
     if (w->property("_q_stylesheet_minh").toBool()
         && ((!rule.hasGeometry() || geo->minHeight == -1))) {
             w->setMinimumHeight(0);
             w->setProperty("_q_stylesheet_minh", QVariant());
     }
     if (w->property("_q_stylesheet_maxw").toBool()
         && ((!rule.hasGeometry() || geo->maxWidth == -1))) {
             w->setMaximumWidth(QWIDGETSIZE_MAX);
             w->setProperty("_q_stylesheet_maxw", QVariant());
     }
    if (w->property("_q_stylesheet_maxh").toBool()
         && ((!rule.hasGeometry() || geo->maxHeight == -1))) {
             w->setMaximumHeight(QWIDGETSIZE_MAX);
             w->setProperty("_q_stylesheet_maxh", QVariant());
     }
     if (rule.hasGeometry()) {
         if (geo->minWidth != -1) {
             w->setProperty("_q_stylesheet_minw", true);
             w->setMinimumWidth(rule.boxSize(QSize(qMax(geo->width, geo->minWidth), 0)).width());
         }
         if (geo->minHeight != -1) {
             w->setProperty("_q_stylesheet_minh", true);
             w->setMinimumHeight(rule.boxSize(QSize(0, qMax(geo->height, geo->minHeight))).height());
         }
         if (geo->maxWidth != -1) {
             w->setProperty("_q_stylesheet_maxw", true);
             w->setMaximumWidth(rule.boxSize(QSize(qMin(geo->width == -1 ? QWIDGETSIZE_MAX : geo->width,
                                                        geo->maxWidth == -1 ? QWIDGETSIZE_MAX : geo->maxWidth), 0)).width());
         }
         if (geo->maxHeight != -1) {
             w->setProperty("_q_stylesheet_maxh", true);
             w->setMaximumHeight(rule.boxSize(QSize(0, qMin(geo->height == -1 ? QWIDGETSIZE_MAX : geo->height,
                                                        geo->maxHeight == -1 ? QWIDGETSIZE_MAX : geo->maxHeight))).height());
         }
     }
 }
setPalette()
void QStyleSheetStyle::setPalette (QWidget * w) private
Definition at line 2533 of file qstylesheetstyle.cpp.
Referenced by polish().
 {
     struct RuleRoleMap {
         int state;
         QPalette::ColorGroup group;
     } map[3] = {
         { int(PseudoClass_Active | PseudoClass_Enabled), QPalette::Active },
         { PseudoClass_Disabled, QPalette::Disabled },
         { PseudoClass_Enabled, QPalette::Inactive }
     };
     QPalette p = w->palette();
     QWidget *ew = embeddedWidget(w);
     for (int i = 0; i < 3; i++) {
         QRenderRule rule = renderRule(w, PseudoElement_None, map[i].state | extendedPseudoClass(w));
         if (i == 0) {
             if (!w->property("_q_styleSheetWidgetFont").isValid()) {
                 saveWidgetFont(w, w->font());
             }
             updateStyleSheetFont(w);
             if (ew != w)
                 updateStyleSheetFont(ew);
         }
         rule.configurePalette(&p, map[i].group, ew, ew != w);
     }
     styleSheetCaches->customPaletteWidgets.insert(w, w->palette());
     w->setPalette(p);
     if (ew != w)
         ew->setPalette(p);
 }
setProperties()
void QStyleSheetStyle::setProperties (QWidget * w) private
Definition at line 2485 of file qstylesheetstyle.cpp.
Referenced by polish().
 {
     QHash<QString, QVariant> propertyHash;
     QVector<Declaration> decls = declarations(styleRules(w), QString());
     // run through the declarations in order
     for (int i = 0; i < decls.count(); i++) {
         const Declaration &decl = decls.at(i);
         QString property = decl.d->property;
         if (!property.startsWith(QLatin1String("qproperty-"), Qt::CaseInsensitive))
             continue;
         property.remove(0, 10); // strip "qproperty-"
         const QVariant value = w->property(property.toLatin1());
         const QMetaObject *metaObject = w->metaObject();
         int index = metaObject->indexOfProperty(property.toLatin1());
         if (index == -1) {
             qWarning() << w << " does not have a property named " << property;
             continue;
         }
         QMetaProperty metaProperty = metaObject->property(index);
         if (!metaProperty.isWritable() || !metaProperty.isDesignable()) {
             qWarning() << w << " cannot design property named " << property;
             continue;
         }
         QVariant v;
         switch (value.type()) {
         case QVariant::Icon: v = decl.iconValue(); break;
         case QVariant::Image: v = QImage(decl.uriValue()); break;
         case QVariant::Pixmap: v = QPixmap(decl.uriValue()); break;
         case QVariant::Rect: v = decl.rectValue(); break;
         case QVariant::Size: v = decl.sizeValue(); break;
         case QVariant::Color: v = decl.colorValue(); break;
         case QVariant::Brush: v = decl.brushValue(); break;
 #ifndef QT_NO_SHORTCUT
         case QVariant::KeySequence: v = QKeySequence(decl.d->values.at(0).variant.toString()); break;
 #endif
         default: v = decl.d->values.at(0).variant; break;
         }
         propertyHash[property] = v;
     }
     // apply the values
     const QList<QString> properties = propertyHash.keys();
     for (int i = 0; i < properties.count(); i++) {
         const QString &property = properties.at(i);
         w->setProperty(property.toLatin1(), propertyHash[property]);
     }
 }
sizeFromContents()
QSize QStyleSheetStyle::sizeFromContents (ContentsType ct, const QStyleOption * opt, const QSize & contentsSize, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 4801 of file qstylesheetstyle.cpp.
 {
     RECURSION_GUARD(return baseStyle()->sizeFromContents(ct, opt, csz, w))
     QRenderRule rule = renderRule(w, opt);
     QSize sz = rule.adjustSize(csz);
     switch (ct) {
     case CT_SpinBox: // ### hopelessly broken QAbstractSpinBox (part 1)
         if (rule.hasBox() || !rule.hasNativeBorder())
             return csz;
         return rule.baseStyleCanDraw() ? baseStyle()->sizeFromContents(ct, opt, sz, w)
                                        : QWindowsStyle::sizeFromContents(ct, opt, sz, w);
     case CT_ToolButton:
         if (rule.hasBox() || !rule.hasNativeBorder() || !rule.baseStyleCanDraw())
             sz += QSize(3, 3); // ### broken QToolButton
         //fall thought
     case CT_ComboBox:
     case CT_PushButton:
         if (rule.hasBox() || !rule.hasNativeBorder()) {
             if(ct == CT_ComboBox) {
                 //add some space for the drop down.
                 QRenderRule subRule = renderRule(w, opt, PseudoElement_ComboBoxDropDown);
                 QRect comboRect = positionRect(w, rule, subRule, PseudoElement_ComboBoxDropDown, opt->rect, opt->direction);
                 //+2 because there is hardcoded margins in QCommonStyle::drawControl(CE_ComboBoxLabel)
                 sz += QSize(comboRect.width() + 2, 0);
             }
             return rule.boxSize(sz);
         }
         sz = rule.baseStyleCanDraw() ? baseStyle()->sizeFromContents(ct, opt, sz, w)
                                      : QWindowsStyle::sizeFromContents(ct, opt, sz, w);
         return rule.boxSize(sz, Margin);
     case CT_HeaderSection: {
             if (const QStyleOptionHeader *hdr = qstyleoption_cast<const QStyleOptionHeader *>(opt)) {
                 QRenderRule subRule = renderRule(w, opt, PseudoElement_HeaderViewSection);
                 if (subRule.hasGeometry() || subRule.hasBox() || !subRule.hasNativeBorder()) {
                     sz = subRule.adjustSize(csz);
                     if (!subRule.hasGeometry()) {
                         QSize nativeContentsSize;
                         bool nullIcon = hdr->icon.isNull();
                         int iconSize = nullIcon ? 0 : pixelMetric(QStyle::PM_SmallIconSize, hdr, w);
                         QSize txt = hdr->fontMetrics.size(0, hdr->text);
                         nativeContentsSize.setHeight(qMax(iconSize, txt.height()));
                         nativeContentsSize.setWidth(iconSize + txt.width());
                         sz = sz.expandedTo(nativeContentsSize);
                     }
                     return subRule.size(sz);
                 }
                 return subRule.baseStyleCanDraw() ? baseStyle()->sizeFromContents(ct, opt, sz, w)
                                                   : QWindowsStyle::sizeFromContents(ct, opt, sz, w);
             }
         }
         break;
     case CT_GroupBox:
     case CT_LineEdit:
 #ifndef QT_NO_SPINBOX
         // ### hopelessly broken QAbstractSpinBox (part 2)
         if (QAbstractSpinBox *spinBox = qobject_cast<QAbstractSpinBox *>(w ? w->parentWidget() : 0)) {
             QRenderRule rule = renderRule(spinBox, opt);
             if (rule.hasBox() || !rule.hasNativeBorder())
                 return csz;
             return rule.baseStyleCanDraw() ? baseStyle()->sizeFromContents(ct, opt, sz, w)
                                            : QWindowsStyle::sizeFromContents(ct, opt, sz, w);
         }
 #endif
         if (rule.hasBox() || !rule.hasNativeBorder()) {
             return rule.boxSize(sz);
         }
         break;
     case CT_CheckBox:
     case CT_RadioButton:
         if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(opt)) {
             if (rule.hasBox() || rule.hasBorder() || hasStyleRule(w, PseudoElement_Indicator)) {
                 bool isRadio = (ct == CT_RadioButton);
                 int iw = pixelMetric(isRadio ? PM_ExclusiveIndicatorWidth
                                              : PM_IndicatorWidth, btn, w);
                 int ih = pixelMetric(isRadio ? PM_ExclusiveIndicatorHeight
                                              : PM_IndicatorHeight, btn, w);
                 int spacing = pixelMetric(isRadio ? PM_RadioButtonLabelSpacing
                                                   : PM_CheckBoxLabelSpacing, btn, w);
                 sz.setWidth(sz.width() + iw + spacing);
                 sz.setHeight(qMax(sz.height(), ih));
                 return rule.boxSize(sz);
             }
         }
         break;
     case CT_Menu:
     case CT_MenuBar: // already has everything!
     case CT_ScrollBar:
         if (rule.hasBox() || rule.hasBorder())
             return sz;
         break;
     case CT_MenuItem:
         if (const QStyleOptionMenuItem *mi = qstyleoption_cast<const QStyleOptionMenuItem *>(opt)) {
             PseudoElement pe = (mi->menuItemType == QStyleOptionMenuItem::Separator)
                                     ? PseudoElement_MenuSeparator : PseudoElement_Item;
             QRenderRule subRule = renderRule(w, opt, pe);
             if ((pe == PseudoElement_MenuSeparator) && subRule.hasContentsSize()) {
                 return QSize(sz.width(), subRule.size().height());
             } else if ((pe == PseudoElement_Item) && (subRule.hasBox() || subRule.hasBorder())) {
                 int width = csz.width();
                 if (mi->text.contains(QLatin1Char('\t')))
                     width += 12; //as in QCommonStyle
                 return subRule.boxSize(subRule.adjustSize(QSize(width, csz.height())));
             }
         }
         break;
     case CT_Splitter:
     case CT_MenuBarItem: {
         PseudoElement pe = (ct == CT_Splitter) ? PseudoElement_SplitterHandle : PseudoElement_Item;
         QRenderRule subRule = renderRule(w, opt, pe);
         if (subRule.hasBox() || subRule.hasBorder())
             return subRule.boxSize(sz);
         break;
                         }
     case CT_ProgressBar:
     case CT_SizeGrip:
         return (rule.hasContentsSize())
             ? rule.size(sz)
             : rule.boxSize(baseStyle()->sizeFromContents(ct, opt, sz, w));
         break;
     case CT_Slider:
         if (rule.hasBorder() || rule.hasBox() || rule.hasGeometry())
             return rule.boxSize(sz);
         break;
 #ifndef QT_NO_TABBAR
     case CT_TabBarTab: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_TabBarTab);
         if (subRule.hasBox() || !subRule.hasNativeBorder()) {
             int spaceForIcon = 0;
             bool vertical = false;
             if (const QStyleOptionTab *tab = qstyleoption_cast<const QStyleOptionTab *>(opt)) {
                 if (!tab->icon.isNull())
                     spaceForIcon = 6 /* icon offset */ + 4 /* spacing */ + 2 /* magic */; // ###: hardcoded to match with common style
                 vertical = verticalTabs(tab->shape);
             }
             sz = csz + QSize(vertical ? 0 : spaceForIcon, vertical ? spaceForIcon : 0);
             return subRule.boxSize(subRule.adjustSize(sz));
         }
 #ifdef Q_WS_MAC
         if (baseStyle()->inherits("QMacStyle")) {
             //adjust the size after the call to the style because the mac style ignore the size arguments anyway.
             //this might cause the (max-){width,height} property to include the native style border while they should not.
             return subRule.adjustSize(baseStyle()->sizeFromContents(ct, opt, csz, w));
         }
 #endif
         sz = subRule.adjustSize(csz);
         break;
     }
 #endif // QT_NO_TABBAR
     case CT_MdiControls:
         if (const QStyleOptionComplex *ccOpt = qstyleoption_cast<const QStyleOptionComplex *>(opt)) {
             if (!hasStyleRule(w, PseudoElement_MdiCloseButton)
                 && !hasStyleRule(w, PseudoElement_MdiNormalButton)
                 && !hasStyleRule(w, PseudoElement_MdiMinButton))
                 break;
             QList<QVariant> layout = rule.styleHint(QLatin1String("button-layout")).toList();
             if (layout.isEmpty())
                 layout = subControlLayout(QLatin1String("mNX"));
             int width = 0, height = 0;
             for (int i = 0; i < layout.count(); i++) {
                 int layoutButton = layout[i].toInt();
                 if (layoutButton < PseudoElement_MdiCloseButton
                     || layoutButton > PseudoElement_MdiNormalButton)
                     continue;
                 QStyle::SubControl sc = knownPseudoElements[layoutButton].subControl;
                 if (!(ccOpt->subControls & sc))
                     continue;
                 QRenderRule subRule = renderRule(w, opt, layoutButton);
                 QSize sz = subRule.size();
                 width += sz.width();
                 height = qMax(height, sz.height());
             }
             return QSize(width, height);
         }
         break;
 #ifndef QT_NO_ITEMVIEWS
     case CT_ItemViewItem: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_ViewItem);
         sz = baseStyle()->sizeFromContents(ct, opt, csz, w);
         sz = subRule.adjustSize(sz);
         if (subRule.hasBox() || subRule.hasBorder())
             sz = subRule.boxSize(sz);
         return sz;
                       }
 #endif // QT_NO_ITEMVIEWS
     default:
         break;
     }
     return baseStyle()->sizeFromContents(ct, opt, sz, w);
 }
standardIconImplementation
QIcon QStyleSheetStyle::standardIconImplementation (StandardPixmap standardIcon, const QStyleOption * opt = 0, const QWidget * widget = 0) const protected slot
Definition at line 5074 of file qstylesheetstyle.cpp.
 {
     RECURSION_GUARD(return baseStyle()->standardIcon(standardIcon, opt, w))
     QString s = propertyNameForStandardPixmap(standardIcon);
     if (!s.isEmpty()) {
         QRenderRule rule = renderRule(w, opt);
         if (rule.hasStyleHint(s))
             return qvariant_cast<QIcon>(rule.styleHint(s));
     }
     return baseStyle()->standardIcon(standardIcon, opt, w);
 }
standardPalette()
QPalette QStyleSheetStyle::standardPalette () const virtual
Returns the style's standard palette.
Note that on systems that support system colors, the style's standard palette is not used. In particular, the Windows XP, Vista, and Mac styles do not use the standard palette, but make use of native theme engines. With these styles, you should not set the palette with QApplication::setStandardPalette().
Reimplemented from QStyle.
Definition at line 5087 of file qstylesheetstyle.cpp.
 {
     return baseStyle()->standardPalette();
 }
standardPixmap()
QPixmap QStyleSheetStyle::standardPixmap (StandardPixmap sp, const QStyleOption * opt = 0, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 5092 of file qstylesheetstyle.cpp.
 {
     RECURSION_GUARD(return baseStyle()->standardPixmap(standardPixmap, opt, w))
     QString s = propertyNameForStandardPixmap(standardPixmap);
     if (!s.isEmpty()) {
         QRenderRule rule = renderRule(w, opt);
         if (rule.hasStyleHint(s)) {
             QIcon icon = qvariant_cast<QIcon>(rule.styleHint(s));
             return icon.pixmap(16, 16); // ###: unhard-code this if someone complains
         }
     }
     return baseStyle()->standardPixmap(standardPixmap, opt, w);
 }
styleHint()
int QStyleSheetStyle::styleHint (StyleHint sh, const QStyleOption * opt = 0, const QWidget * w = 0, QStyleHintReturn * shret = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 5123 of file qstylesheetstyle.cpp.
Referenced by drawComplexControl(), drawControl(), and drawPrimitive().
 {
     RECURSION_GUARD(return baseStyle()->styleHint(sh, opt, w, shret))
     // Prevent endless loop if somebody use isActiveWindow property as selector.
     // QWidget::isActiveWindow uses this styleHint to determine if the window is active or not
     if (sh == SH_Widget_ShareActivation)
         return baseStyle()->styleHint(sh, opt, w, shret);
     QRenderRule rule = renderRule(w, opt);
     QString s;
     switch (sh) {
         case SH_LineEdit_PasswordCharacter: s = QLatin1String("lineedit-password-character"); break;
         case SH_DitherDisabledText: s = QLatin1String("dither-disabled-text"); break;
         case SH_EtchDisabledText: s = QLatin1String("etch-disabled-text"); break;
         case SH_ItemView_ActivateItemOnSingleClick: s = QLatin1String("activate-on-singleclick"); break;
         case SH_ItemView_ShowDecorationSelected: s = QLatin1String("show-decoration-selected"); break;
         case SH_Table_GridLineColor: s = QLatin1String("gridline-color"); break;
         case SH_DialogButtonLayout: s = QLatin1String("button-layout"); break;
         case SH_ToolTipLabel_Opacity: s = QLatin1String("opacity"); break;
         case SH_ComboBox_Popup: s = QLatin1String("combobox-popup"); break;
         case SH_ComboBox_ListMouseTracking: s = QLatin1String("combobox-list-mousetracking"); break;
         case SH_MenuBar_AltKeyNavigation: s = QLatin1String("menubar-altkey-navigation"); break;
         case SH_Menu_Scrollable: s = QLatin1String("menu-scrollable"); break;
         case SH_DrawMenuBarSeparator: s = QLatin1String("menubar-separator"); break;
         case SH_MenuBar_MouseTracking: s = QLatin1String("mouse-tracking"); break;
         case SH_SpinBox_ClickAutoRepeatRate: s = QLatin1String("spinbox-click-autorepeat-rate"); break;
         case SH_SpinControls_DisableOnBounds: s = QLatin1String("spincontrol-disable-on-bounds"); break;
         case SH_MessageBox_TextInteractionFlags: s = QLatin1String("messagebox-text-interaction-flags"); break;
         case SH_ToolButton_PopupDelay: s = QLatin1String("toolbutton-popup-delay"); break;
         case SH_ToolBox_SelectedPageTitleBold:
             if (renderRule(w, opt, PseudoElement_ToolBoxTab).hasFont)
                 return 0;
             break;
         case SH_GroupBox_TextLabelColor:
             if (rule.hasPalette() && rule.palette()->foreground.style() != Qt::NoBrush)
                 return rule.palette()->foreground.color().rgba();
             break;
         case SH_ScrollView_FrameOnlyAroundContents: s = QLatin1String("scrollview-frame-around-contents"); break;
         case SH_ScrollBar_ContextMenu: s = QLatin1String("scrollbar-contextmenu"); break;
         case SH_ScrollBar_LeftClickAbsolutePosition: s = QLatin1String("scrollbar-leftclick-absolute-position"); break;
         case SH_ScrollBar_MiddleClickAbsolutePosition: s = QLatin1String("scrollbar-middleclick-absolute-position"); break;
         case SH_ScrollBar_RollBetweenButtons: s = QLatin1String("scrollbar-roll-between-buttons"); break;
         case SH_ScrollBar_ScrollWhenPointerLeavesControl: s = QLatin1String("scrollbar-scroll-when-pointer-leaves-control"); break;
         case SH_TabBar_Alignment:
 #ifndef QT_NO_TABWIDGET
             if (qobject_cast<const QTabWidget *>(w)) {
                 rule = renderRule(w, opt, PseudoElement_TabWidgetTabBar);
                 if (rule.hasPosition())
                     return rule.position()->position;
             }
 #endif // QT_NO_TABWIDGET
             s = QLatin1String("alignment");
             break;
 #ifndef QT_NO_TABBAR
         case SH_TabBar_CloseButtonPosition:
             rule = renderRule(w, opt, PseudoElement_TabBarTabCloseButton);
             if (rule.hasPosition()) {
                 Qt::Alignment align = rule.position()->position;
                 if (align & Qt::AlignLeft || align & Qt::AlignTop)
                     return QTabBar::LeftSide;
                 if (align & Qt::AlignRight || align & Qt::AlignBottom)
                     return QTabBar::RightSide;
             }
             break;
 #endif
         case SH_TabBar_ElideMode: s = QLatin1String("tabbar-elide-mode"); break;
         case SH_TabBar_PreferNoArrows: s = QLatin1String("tabbar-prefer-no-arrows"); break;
         case SH_ComboBox_PopupFrameStyle:
 #ifndef QT_NO_COMBOBOX
             if (qobject_cast<const QComboBox *>(w)) {
                 QAbstractItemView *view = w->findChild<QAbstractItemView *>();
                 if (view) {
                     view->ensurePolished();
                     QRenderRule subRule = renderRule(view, PseudoElement_None);
                     if (subRule.hasBox() || !subRule.hasNativeBorder())
                         return QFrame::NoFrame;
                 }
             }
 #endif // QT_NO_COMBOBOX
             break;
         case SH_DialogButtonBox_ButtonsHaveIcons: s = QLatin1String("dialogbuttonbox-buttons-have-icons"); break;
         case SH_Workspace_FillSpaceOnMaximize: s = QLatin1String("mdi-fill-space-on-maximize"); break;
         case SH_TitleBar_NoBorder:
             if (rule.hasBorder())
                 return !rule.border()->borders[LeftEdge];
             break;
         case SH_TitleBar_AutoRaise: { // plain absurd
             QRenderRule subRule = renderRule(w, opt, PseudoElement_TitleBar);
             if (subRule.hasDrawable())
                 return 1;
             break;
                                    }
         case SH_ItemView_ArrowKeysNavigateIntoChildren: s = QLatin1String("arrow-keys-navigate-into-children"); break;
         case SH_ItemView_PaintAlternatingRowColorsForEmptyArea: s = QLatin1String("paint-alternating-row-colors-for-empty-area"); break;
         default: break;
     }
     if (!s.isEmpty() && rule.hasStyleHint(s)) {
         return rule.styleHint(s).toInt();
     }
     return baseStyle()->styleHint(sh, opt, w, shret);
 }
styleRules()
QVector< QCss::StyleRule > QStyleSheetStyle::styleRules (const QWidget * w) const private
Definition at line 1519 of file qstylesheetstyle.cpp.
Referenced by polish().
 {
     QHash<const QWidget *, QVector<StyleRule> >::const_iterator cacheIt = styleSheetCaches->styleRulesCache.constFind(w);
     if (cacheIt != styleSheetCaches->styleRulesCache.constEnd())
         return cacheIt.value();
     if (!initWidget(w)) {
         return QVector<StyleRule>();
     }
     QStyleSheetStyleSelector styleSelector;
     StyleSheet defaultSs;
     QHash<const void *, StyleSheet>::const_iterator defaultCacheIt = styleSheetCaches->styleSheetCache.constFind(baseStyle());
     if (defaultCacheIt == styleSheetCaches->styleSheetCache.constEnd()) {
         defaultSs = getDefaultStyleSheet();
         QStyle *bs = baseStyle();
         styleSheetCaches->styleSheetCache.insert(bs, defaultSs);
         QObject::connect(bs, SIGNAL(destroyed(QObject*)), styleSheetCaches, SLOT(styleDestroyed(QObject*)), Qt::UniqueConnection);
     } else {
         defaultSs = defaultCacheIt.value();
     }
     styleSelector.styleSheets += defaultSs;
     if (!qApp->styleSheet().isEmpty()) {
         StyleSheet appSs;
         QHash<const void *, StyleSheet>::const_iterator appCacheIt = styleSheetCaches->styleSheetCache.constFind(qApp);
         if (appCacheIt == styleSheetCaches->styleSheetCache.constEnd()) {
             QString ss = qApp->styleSheet();
             if (ss.startsWith(QLatin1String("file:///")))
                 ss.remove(0, 8);
             parser.init(ss, qApp->styleSheet() != ss);
             if (!parser.parse(&appSs))
                 qWarning("Could not parse application stylesheet");
             appSs.origin = StyleSheetOrigin_Inline;
             appSs.depth = 1;
             styleSheetCaches->styleSheetCache.insert(qApp, appSs);
         } else {
             appSs = appCacheIt.value();
         }
         styleSelector.styleSheets += appSs;
     }
     QVector<QCss::StyleSheet> widgetSs;
     for (const QWidget *wid = w; wid; wid = parentWidget(wid)) {
         if (wid->styleSheet().isEmpty())
             continue;
         StyleSheet ss;
         QHash<const void *, StyleSheet>::const_iterator widCacheIt = styleSheetCaches->styleSheetCache.constFind(wid);
         if (widCacheIt == styleSheetCaches->styleSheetCache.constEnd()) {
             parser.init(wid->styleSheet());
             if (!parser.parse(&ss)) {
                 parser.init(QLatin1String("* {") + wid->styleSheet() + QLatin1Char('}'));
                 if (!parser.parse(&ss))
                    qWarning("Could not parse stylesheet of widget %p", wid);
             }
             ss.origin = StyleSheetOrigin_Inline;
             styleSheetCaches->styleSheetCache.insert(wid, ss);
         } else {
             ss = widCacheIt.value();
         }
         widgetSs.append(ss);
     }
     for (int i = 0; i < widgetSs.count(); i++)
         widgetSs[i].depth = widgetSs.count() - i + 2;
     styleSelector.styleSheets += widgetSs;
     StyleSelector::NodePtr n;
     n.ptr = (void *)w;
     QVector<QCss::StyleRule> rules = styleSelector.styleRulesForNode(n);
     styleSheetCaches->styleRulesCache.insert(w, rules);
     return rules;
 }
styleSheetPalette()
bool QStyleSheetStyle::styleSheetPalette (const QWidget * w, const QStyleOption * opt, QPalette * pal)
Definition at line 5855 of file qstylesheetstyle.cpp.
 {
     if (!w || !opt || !pal)
         return false;
     RECURSION_GUARD(return false)
     w = containerWidget(w);
     QRenderRule rule = renderRule(w, PseudoElement_None, pseudoClass(opt->state) | extendedPseudoClass(w));
     if (!rule.hasPalette())
         return false;
     rule.configurePalette(pal, QPalette::NoRole, QPalette::NoRole);
     return true;
 }
subControlRect()
QRect QStyleSheetStyle::subControlRect (ComplexControl cc, const QStyleOptionComplex * opt, SubControl sc, const QWidget * w = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 5227 of file qstylesheetstyle.cpp.
Referenced by drawComplexControl(), and drawControl().
 {
     RECURSION_GUARD(return baseStyle()->subControlRect(cc, opt, sc, w))
     QRenderRule rule = renderRule(w, opt);
     switch (cc) {
     case CC_ComboBox:
         if (const QStyleOptionComboBox *cb = qstyleoption_cast<const QStyleOptionComboBox *>(opt)) {
             if (rule.hasBox() || !rule.hasNativeBorder()) {
                 switch (sc) {
                 case SC_ComboBoxFrame: return rule.borderRect(opt->rect);
                 case SC_ComboBoxEditField:
                     {
                         QRenderRule subRule = renderRule(w, opt, PseudoElement_ComboBoxDropDown);
                         QRect r = rule.contentsRect(opt->rect);
                         QRect r2 = positionRect(w, rule, subRule, PseudoElement_ComboBoxDropDown,
                                 opt->rect, opt->direction);
                         if (subRule.hasPosition() && subRule.position()->position & Qt::AlignLeft) {
                             return visualRect(opt->direction, r, r.adjusted(r2.width(),0,0,0));
                         } else {
                             return visualRect(opt->direction, r, r.adjusted(0,0,-r2.width(),0));
                         }
                     }
                 case SC_ComboBoxArrow: {
                     QRenderRule subRule = renderRule(w, opt, PseudoElement_ComboBoxDropDown);
                     return positionRect(w, rule, subRule, PseudoElement_ComboBoxDropDown, opt->rect, opt->direction);
                                                                            }
                 case SC_ComboBoxListBoxPopup:
                 default:
                     return baseStyle()->subControlRect(cc, opt, sc, w);
                 }
             }
             QStyleOptionComboBox comboBox(*cb);
             comboBox.rect = rule.borderRect(opt->rect);
             return rule.baseStyleCanDraw() ? baseStyle()->subControlRect(cc, &comboBox, sc, w)
                                            : QWindowsStyle::subControlRect(cc, &comboBox, sc, w);
         }
         break;
 #ifndef QT_NO_SPINBOX
     case CC_SpinBox:
         if (const QStyleOptionSpinBox *spin = qstyleoption_cast<const QStyleOptionSpinBox *>(opt)) {
             QRenderRule upRule = renderRule(w, opt, PseudoElement_SpinBoxUpButton);
             QRenderRule downRule = renderRule(w, opt, PseudoElement_SpinBoxDownButton);
             bool ruleMatch = rule.hasBox() || !rule.hasNativeBorder();
             bool upRuleMatch = upRule.hasGeometry() || upRule.hasPosition();
             bool downRuleMatch = downRule.hasGeometry() || upRule.hasPosition();
             if (ruleMatch || upRuleMatch || downRuleMatch) {
                 switch (sc) {
                 case SC_SpinBoxFrame:
                     return rule.borderRect(opt->rect);
                 case SC_SpinBoxEditField:
                     {
                         QRect r = rule.contentsRect(opt->rect);
                         // Use the widest button on each side to determine edit field size.
                         Qt::Alignment upAlign, downAlign;
                         upAlign = upRule.hasPosition() ? upRule.position()->position
                                 : Qt::Alignment(Qt::AlignRight);
                         upAlign = resolveAlignment(opt->direction, upAlign);
                         downAlign = downRule.hasPosition() ? downRule.position()->position
                                 : Qt::Alignment(Qt::AlignRight);
                         downAlign = resolveAlignment(opt->direction, downAlign);
                         int upSize = subControlRect(CC_SpinBox, opt, SC_SpinBoxUp, w).width();
                         int downSize = subControlRect(CC_SpinBox, opt, SC_SpinBoxDown, w).width();
                         int widestL = qMax((upAlign & Qt::AlignLeft) ? upSize : 0,
                                 (downAlign & Qt::AlignLeft) ? downSize : 0);
                         int widestR = qMax((upAlign & Qt::AlignRight) ? upSize : 0,
                                 (downAlign & Qt::AlignRight) ? downSize : 0);
                         r.setRight(r.right() - widestR);
                         r.setLeft(r.left() + widestL);
                         return r;
                     }
                 case SC_SpinBoxDown:
                     if (downRuleMatch)
                         return positionRect(w, rule, downRule, PseudoElement_SpinBoxDownButton,
                                 opt->rect, opt->direction);
                     break;
                 case SC_SpinBoxUp:
                     if (upRuleMatch)
                         return positionRect(w, rule, upRule, PseudoElement_SpinBoxUpButton,
                                 opt->rect, opt->direction);
                     break;
                 default:
                     break;
                 }
                 return baseStyle()->subControlRect(cc, opt, sc, w);
             }
             QStyleOptionSpinBox spinBox(*spin);
             spinBox.rect = rule.borderRect(opt->rect);
             return rule.baseStyleCanDraw() ? baseStyle()->subControlRect(cc, &spinBox, sc, w)
                                            : QWindowsStyle::subControlRect(cc, &spinBox, sc, w);
         }
         break;
 #endif // QT_NO_SPINBOX
     case CC_GroupBox:
         if (const QStyleOptionGroupBox *gb = qstyleoption_cast<const QStyleOptionGroupBox *>(opt)) {
             switch (sc) {
             case SC_GroupBoxFrame:
             case SC_GroupBoxContents: {
                 if (rule.hasBox() || !rule.hasNativeBorder()) {
                     return sc == SC_GroupBoxFrame ? rule.borderRect(opt->rect)
                                                   : rule.contentsRect(opt->rect);
                 }
                 QStyleOptionGroupBox groupBox(*gb);
                 groupBox.rect = rule.borderRect(opt->rect);
                 return baseStyle()->subControlRect(cc, &groupBox, sc, w);
             }
             default:
             case SC_GroupBoxLabel:
             case SC_GroupBoxCheckBox: {
                 QRenderRule indRule = renderRule(w, opt, PseudoElement_GroupBoxIndicator);
                 QRenderRule labelRule = renderRule(w, opt, PseudoElement_GroupBoxTitle);
                 if (!labelRule.hasPosition() && !labelRule.hasGeometry() && !labelRule.hasBox()
                     && !labelRule.hasBorder() && !indRule.hasContentsSize()) {
                     QStyleOptionGroupBox groupBox(*gb);
                     groupBox.rect = rule.borderRect(opt->rect);
                     return baseStyle()->subControlRect(cc, &groupBox, sc, w);
                 }
                 int tw = opt->fontMetrics.width(gb->text);
                 int th = opt->fontMetrics.height();
                 int spacing = pixelMetric(QStyle::PM_CheckBoxLabelSpacing, opt, w);
                 int iw = pixelMetric(QStyle::PM_IndicatorWidth, opt, w);
                 int ih = pixelMetric(QStyle::PM_IndicatorHeight, opt, w);
                 if (gb->subControls & QStyle::SC_GroupBoxCheckBox) {
                     tw = tw + iw + spacing;
                     th = qMax(th, ih);
                 }
                 if (!labelRule.hasGeometry()) {
                     labelRule.geo = new QStyleSheetGeometryData(tw, th, tw, th, -1, -1);
                 } else {
                     labelRule.geo->width = tw;
                     labelRule.geo->height = th;
                 }
                 if (!labelRule.hasPosition()) {
                     labelRule.p = new QStyleSheetPositionData(0, 0, 0, 0, defaultOrigin(PseudoElement_GroupBoxTitle),
                                                               gb->textAlignment, PositionMode_Static);
                 }
                 QRect r = positionRect(w, rule, labelRule, PseudoElement_GroupBoxTitle,
                                       opt->rect, opt->direction);
                 if (gb->subControls & SC_GroupBoxCheckBox) {
                     r = labelRule.contentsRect(r);
                     if (sc == SC_GroupBoxLabel) {
                         r.setLeft(r.left() + iw + spacing);
                         r.setTop(r.center().y() - th/2);
                     } else {
                         r = QRect(r.left(), r.center().y() - ih/2, iw, ih);
                     }
                     return r;
                 } else {
                     return labelRule.contentsRect(r);
                 }
             }
             } // switch
         }
         break;
     case CC_ToolButton:
         if (const QStyleOptionToolButton *tb = qstyleoption_cast<const QStyleOptionToolButton *>(opt)) {
             if (rule.hasBox() || !rule.hasNativeBorder()) {
                 switch (sc) {
                 case SC_ToolButton: return rule.borderRect(opt->rect);
                 case SC_ToolButtonMenu: {
                     QRenderRule subRule = renderRule(w, opt, PseudoElement_ToolButtonMenu);
                     return positionRect(w, rule, subRule, PseudoElement_ToolButtonMenu, opt->rect, opt->direction);
                                                                             }
                 default:
                     break;
                 }
             }
             QStyleOptionToolButton tool(*tb);
             tool.rect = rule.borderRect(opt->rect);
             return rule.baseStyleCanDraw() ? baseStyle()->subControlRect(cc, &tool, sc, w)
                                            : QWindowsStyle::subControlRect(cc, &tool, sc, w);
             }
             break;
 #ifndef QT_NO_SCROLLBAR
     case CC_ScrollBar:
         if (const QStyleOptionSlider *sb = qstyleoption_cast<const QStyleOptionSlider *>(opt)) {
             QStyleOptionSlider styleOptionSlider(*sb);
             styleOptionSlider.rect = rule.borderRect(opt->rect);
             if (rule.hasDrawable() || rule.hasBox()) {
                 QRect grooveRect;
                 if (!rule.hasBox()) {
                     grooveRect = rule.baseStyleCanDraw() ? baseStyle()->subControlRect(cc, sb, SC_ScrollBarGroove, w)
                                  : QWindowsStyle::subControlRect(cc, sb, SC_ScrollBarGroove, w);
                 } else {
                     grooveRect = rule.contentsRect(opt->rect);
                 }
                 PseudoElement pe = PseudoElement_None;
                 switch (sc) {
                 case SC_ScrollBarGroove:
                     return grooveRect;
                 case SC_ScrollBarAddPage:
                 case SC_ScrollBarSubPage:
                 case SC_ScrollBarSlider: {
                     QRect contentRect = grooveRect;
                     if (hasStyleRule(w, PseudoElement_ScrollBarSlider)) {
                         QRenderRule sliderRule = renderRule(w, opt, PseudoElement_ScrollBarSlider);
                         Origin origin = sliderRule.hasPosition() ? sliderRule.position()->origin : defaultOrigin(PseudoElement_ScrollBarSlider);
                         contentRect = rule.originRect(opt->rect, origin);
                     }
                     int maxlen = (styleOptionSlider.orientation == Qt::Horizontal) ? contentRect.width() : contentRect.height();
                     int sliderlen;
                     if (sb->maximum != sb->minimum) {
                         uint range = sb->maximum - sb->minimum;
                         sliderlen = (qint64(sb->pageStep) * maxlen) / (range + sb->pageStep);
                         int slidermin = pixelMetric(PM_ScrollBarSliderMin, sb, w);
                         if (sliderlen < slidermin || range > INT_MAX / 2)
                             sliderlen = slidermin;
                         if (sliderlen > maxlen)
                             sliderlen = maxlen;
                     } else {
                         sliderlen = maxlen;
                     }
                     int sliderstart = (styleOptionSlider.orientation == Qt::Horizontal ? contentRect.left() : contentRect.top())
                         + sliderPositionFromValue(sb->minimum, sb->maximum, sb->sliderPosition,
                                                   maxlen - sliderlen, sb->upsideDown);
                     QRect sr = (sb->orientation == Qt::Horizontal)
                                ? QRect(sliderstart, contentRect.top(), sliderlen, contentRect.height())
                                : QRect(contentRect.left(), sliderstart, contentRect.width(), sliderlen);
                     if (sc == SC_ScrollBarSlider) {
                         return sr;
                     } else if (sc == SC_ScrollBarSubPage) {
                         return QRect(contentRect.topLeft(), sb->orientation == Qt::Horizontal ? sr.bottomLeft() : sr.topRight());
                     } else { // SC_ScrollBarAddPage
                         return QRect(sb->orientation == Qt::Horizontal ? sr.topRight() : sr.bottomLeft(), contentRect.bottomRight());
                     }
                     break;
                 }
                 case SC_ScrollBarAddLine: pe = PseudoElement_ScrollBarAddLine; break;
                 case SC_ScrollBarSubLine: pe = PseudoElement_ScrollBarSubLine; break;
                 case SC_ScrollBarFirst: pe = PseudoElement_ScrollBarFirst;  break;
                 case SC_ScrollBarLast: pe = PseudoElement_ScrollBarLast; break;
                 default: break;
                 }
                 if (hasStyleRule(w,pe)) {
                     QRenderRule subRule = renderRule(w, opt, pe);
                     if (subRule.hasPosition() || subRule.hasGeometry() || subRule.hasBox()) {
                         const QStyleSheetPositionData *pos = subRule.position();
                         QRect originRect = grooveRect;
                         if (rule.hasBox()) {
                             Origin origin = (pos && pos->origin != Origin_Unknown) ? pos->origin : defaultOrigin(pe);
                             originRect = rule.originRect(opt->rect, origin);
                         }
                         return positionRect(w, subRule, pe, originRect, styleOptionSlider.direction);
                     }
                 }
             }
             return rule.baseStyleCanDraw() ? baseStyle()->subControlRect(cc, &styleOptionSlider, sc, w)
                                            : QWindowsStyle::subControlRect(cc, &styleOptionSlider, sc, w);
         }
         break;
 #endif // QT_NO_SCROLLBAR
 #ifndef QT_NO_SLIDER
     case CC_Slider:
         if (const QStyleOptionSlider *slider = qstyleoption_cast<const QStyleOptionSlider *>(opt)) {
             QRenderRule subRule = renderRule(w, opt, PseudoElement_SliderGroove);
             if (!subRule.hasDrawable())
                 break;
             subRule.img = 0;
             QRect gr = positionRect(w, rule, subRule, PseudoElement_SliderGroove, opt->rect, opt->direction);
             switch (sc) {
             case SC_SliderGroove:
                 return gr;
             case SC_SliderHandle: {
                 bool horizontal = slider->orientation & Qt::Horizontal;
                 QRect cr = subRule.contentsRect(gr);
                 QRenderRule subRule2 = renderRule(w, opt, PseudoElement_SliderHandle);
                 int len = horizontal ? subRule2.size().width() : subRule2.size().height();
                 subRule2.img = 0;
                 subRule2.geo = 0;
                 cr = positionRect(w, subRule2, PseudoElement_SliderHandle, cr, opt->direction);
                 int thickness = horizontal ? cr.height() : cr.width();
                 int sliderPos = sliderPositionFromValue(slider->minimum, slider->maximum, slider->sliderPosition,
                                                         (horizontal ? cr.width() : cr.height()) - len, slider->upsideDown);
                 cr = horizontal ? QRect(cr.x() + sliderPos, cr.y(), len, thickness)
                                   : QRect(cr.x(), cr.y() + sliderPos, thickness, len);
                 return subRule2.borderRect(cr);
                 break; }
             case SC_SliderTickmarks:
                 // TODO...
             default:
                 break;
             }
         }
         break;
 #endif // QT_NO_SLIDER
     case CC_MdiControls:
         if (hasStyleRule(w, PseudoElement_MdiCloseButton)
             || hasStyleRule(w, PseudoElement_MdiNormalButton)
             || hasStyleRule(w, PseudoElement_MdiMinButton)) {
             QList<QVariant> layout = rule.styleHint(QLatin1String("button-layout")).toList();
             if (layout.isEmpty())
                 layout = subControlLayout(QLatin1String("mNX"));
             int x = 0, width = 0;
             QRenderRule subRule;
             for (int i = 0; i < layout.count(); i++) {
                 int layoutButton = layout[i].toInt();
                 if (layoutButton < PseudoElement_MdiCloseButton
                     || layoutButton > PseudoElement_MdiNormalButton)
                     continue;
                 QStyle::SubControl control = knownPseudoElements[layoutButton].subControl;
                 if (!(opt->subControls & control))
                     continue;
                 subRule = renderRule(w, opt, layoutButton);
                 width = subRule.size().width();
                 if (sc == control)
                     break;
                 x += width;
             }
             return subRule.borderRect(QRect(x, opt->rect.top(), width, opt->rect.height()));
         }
         break;
     case CC_TitleBar:
         if (const QStyleOptionTitleBar *tb = qstyleoption_cast<const QStyleOptionTitleBar *>(opt)) {
             QRenderRule subRule = renderRule(w, opt, PseudoElement_TitleBar);
             if (!subRule.hasDrawable() && !subRule.hasBox() && !subRule.hasBorder())
                 break;
             QHash<QStyle::SubControl, QRect> layoutRects = titleBarLayout(w, tb);
             return layoutRects.value(sc);
         }
         break;
     default:
         break;
     }
     return baseStyle()->subControlRect(cc, opt, sc, w);
 }
subElementRect()
QRect QStyleSheetStyle::subElementRect (SubElement r, const QStyleOption * opt, const QWidget * widget = 0) const virtual
Reimplemented Function
we need to access the widget here because the style option doesn't
Reimplemented from QCommonStyle.
Definition at line 5578 of file qstylesheetstyle.cpp.
 {
     RECURSION_GUARD(return baseStyle()->subElementRect(se, opt, w))
     QRenderRule rule = renderRule(w, opt);
 #ifndef QT_NO_TABBAR
     int pe = PseudoElement_None;
 #endif
     switch (se) {
     case SE_PushButtonContents:
     case SE_PushButtonFocusRect:
         if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(opt)) {
             QStyleOptionButton btnOpt(*btn);
             if (rule.hasBox() || !rule.hasNativeBorder())
                 return visualRect(opt->direction, opt->rect, rule.contentsRect(opt->rect));
             return rule.baseStyleCanDraw() ? baseStyle()->subElementRect(se, &btnOpt, w)
                                            : QWindowsStyle::subElementRect(se, &btnOpt, w);
         }
         break;
     case SE_LineEditContents:
     case SE_FrameContents:
     case SE_ShapedFrameContents:
         if (rule.hasBox() || !rule.hasNativeBorder()) {
             return visualRect(opt->direction, opt->rect, rule.contentsRect(opt->rect));
         }
         break;
     case SE_CheckBoxIndicator:
     case SE_RadioButtonIndicator:
         if (rule.hasBox() || rule.hasBorder() || hasStyleRule(w, PseudoElement_Indicator)) {
             PseudoElement pe = se == SE_CheckBoxIndicator ? PseudoElement_Indicator : PseudoElement_ExclusiveIndicator;
             QRenderRule subRule = renderRule(w, opt, pe);
             return positionRect(w, rule, subRule, pe, opt->rect, opt->direction);
         }
         break;
     case SE_CheckBoxContents:
     case SE_RadioButtonContents:
         if (rule.hasBox() || rule.hasBorder() || hasStyleRule(w, PseudoElement_Indicator)) {
             bool isRadio = se == SE_RadioButtonContents;
             QRect ir = subElementRect(isRadio ? SE_RadioButtonIndicator : SE_CheckBoxIndicator,
                                       opt, w);
             ir = visualRect(opt->direction, opt->rect, ir);
             int spacing = pixelMetric(isRadio ? PM_RadioButtonLabelSpacing : PM_CheckBoxLabelSpacing, 0, w);
             QRect cr = rule.contentsRect(opt->rect);
             ir.setRect(ir.left() + ir.width() + spacing, cr.y(),
                        cr.width() - ir.width() - spacing, cr.height());
             return visualRect(opt->direction, opt->rect, ir);
         }
         break;
     case SE_ToolBoxTabContents:
         if (w && hasStyleRule(w->parentWidget(), PseudoElement_ToolBoxTab)) {
             QRenderRule subRule = renderRule(w->parentWidget(), opt, PseudoElement_ToolBoxTab);
             return visualRect(opt->direction, opt->rect, subRule.contentsRect(opt->rect));
         }
         break;
     case SE_RadioButtonFocusRect:
     case SE_RadioButtonClickRect: // focusrect | indicator
         if (rule.hasBox() || rule.hasBorder() || hasStyleRule(w, PseudoElement_Indicator)) {
             return opt->rect;
         }
         break;
     case SE_CheckBoxFocusRect:
     case SE_CheckBoxClickRect: // relies on indicator and contents
         return ParentStyle::subElementRect(se, opt, w);
 #ifndef QT_NO_ITEMVIEWS
     case SE_ViewItemCheckIndicator:
         if (!qstyleoption_cast<const QStyleOptionViewItemV4 *>(opt)) {
             return subElementRect(SE_CheckBoxIndicator, opt, w);
         }
         // intentionally falls through
     case SE_ItemViewItemText:
     case SE_ItemViewItemDecoration:
     case SE_ItemViewItemFocusRect:
         if (const QStyleOptionViewItemV4 *vopt = qstyleoption_cast<const QStyleOptionViewItemV4 *>(opt)) {
             QRenderRule subRule = renderRule(w, opt, PseudoElement_ViewItem);
             PseudoElement pe = PseudoElement_None;
             if (se == SE_ItemViewItemText || se == SE_ItemViewItemFocusRect)
                 pe = PseudoElement_ViewItemText;
             else if (se == SE_ItemViewItemDecoration && vopt->features & QStyleOptionViewItemV2::HasDecoration)
                 pe = PseudoElement_ViewItemIcon;
             else if (se == SE_ItemViewItemCheckIndicator && vopt->features & QStyleOptionViewItemV2::HasCheckIndicator)
                 pe = PseudoElement_ViewItemIndicator;
             else
                 break;
             if (subRule.hasGeometry() || subRule.hasBox() || !subRule.hasNativeBorder() || hasStyleRule(w, pe)) {
                 QRenderRule subRule2 = renderRule(w, opt, pe);
                 QStyleOptionViewItemV4 optCopy(*vopt);
                 optCopy.rect = subRule.contentsRect(vopt->rect);
                 QRect rect = ParentStyle::subElementRect(se, &optCopy, w);
                 return positionRect(w, subRule2, pe, rect, opt->direction);
             }
          }
         break;
 #endif // QT_NO_ITEMVIEWS
     case SE_HeaderArrow: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_HeaderViewUpArrow);
         if (subRule.hasPosition() || subRule.hasGeometry())
             return positionRect(w, rule, subRule, PseudoElement_HeaderViewUpArrow, opt->rect, opt->direction);
                          }
         break;
     case SE_HeaderLabel: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_HeaderViewSection);
         if (subRule.hasBox() || !subRule.hasNativeBorder())
             return subRule.contentsRect(opt->rect);
                          }
         break;
     case SE_ProgressBarGroove:
     case SE_ProgressBarContents:
     case SE_ProgressBarLabel:
         if (const QStyleOptionProgressBarV2 *pb = qstyleoption_cast<const QStyleOptionProgressBarV2 *>(opt)) {
             if (rule.hasBox() || !rule.hasNativeBorder() || rule.hasPosition() || hasStyleRule(w, PseudoElement_ProgressBarChunk)) {
                 if (se == SE_ProgressBarGroove)
                     return rule.borderRect(pb->rect);
                 else if (se == SE_ProgressBarContents)
                     return rule.contentsRect(pb->rect);
                 QSize sz = pb->fontMetrics.size(0, pb->text);
                 return QStyle::alignedRect(Qt::LeftToRight, rule.hasPosition() ? rule.position()->textAlignment : pb->textAlignment,
                                            sz, pb->rect);
             }
         }
         break;
 #ifndef QT_NO_TABBAR
     case SE_TabWidgetLeftCorner:
         pe = PseudoElement_TabWidgetLeftCorner;
         // intentionally falls through
     case SE_TabWidgetRightCorner:
         if (pe == PseudoElement_None)
             pe = PseudoElement_TabWidgetRightCorner;
         // intentionally falls through
     case SE_TabWidgetTabBar:
         if (pe == PseudoElement_None)
             pe = PseudoElement_TabWidgetTabBar;
         // intentionally falls through
     case SE_TabWidgetTabPane:
     case SE_TabWidgetTabContents:
         if (pe == PseudoElement_None)
             pe = PseudoElement_TabWidgetPane;
         if (hasStyleRule(w, pe)) {
             QRect r = QWindowsStyle::subElementRect(pe == PseudoElement_TabWidgetPane ? SE_TabWidgetTabPane : se, opt, w);
             QRenderRule subRule = renderRule(w, opt, pe);
             r = positionRect(w, subRule, pe, r, opt->direction);
             if (pe == PseudoElement_TabWidgetTabBar) {
                 Q_ASSERT(opt);
                 r = opt->rect.intersected(r);
             }
             if (se == SE_TabWidgetTabContents)
                 r = subRule.contentsRect(r);
             return r;
         }
         break;
     case SE_TabBarTearIndicator: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_TabBarTear);
         if (subRule.hasContentsSize()) {
             QRect r;
             if (const QStyleOptionTab *tab = qstyleoption_cast<const QStyleOptionTab *>(opt)) {
                 switch (tab->shape) {
                 case QTabBar::RoundedNorth:
                 case QTabBar::TriangularNorth:
                 case QTabBar::RoundedSouth:
                 case QTabBar::TriangularSouth:
                     r.setRect(tab->rect.left(), tab->rect.top(), subRule.size().width(), opt->rect.height());
                     break;
                 case QTabBar::RoundedWest:
                 case QTabBar::TriangularWest:
                 case QTabBar::RoundedEast:
                 case QTabBar::TriangularEast:
                     r.setRect(tab->rect.left(), tab->rect.top(), opt->rect.width(), subRule.size().height());
                     break;
                 default:
                     break;
                 }
                 r = visualRect(opt->direction, opt->rect, r);
             }
             return r;
         }
         break;
     }
     case SE_TabBarTabText:
     case SE_TabBarTabLeftButton:
     case SE_TabBarTabRightButton: {
         QRenderRule subRule = renderRule(w, opt, PseudoElement_TabBarTab);
         if (subRule.hasBox() || !subRule.hasNativeBorder()) {
             return ParentStyle::subElementRect(se, opt, w);
         }
         break;
     }
 #endif // QT_NO_TABBAR
     case SE_DockWidgetCloseButton:
     case SE_DockWidgetFloatButton: {
         PseudoElement pe = (se == SE_DockWidgetCloseButton) ? PseudoElement_DockWidgetCloseButton : PseudoElement_DockWidgetFloatButton;
         QRenderRule subRule2 = renderRule(w, opt, pe);
         if (!subRule2.hasPosition())
             break;
         QRenderRule subRule = renderRule(w, opt, PseudoElement_DockWidgetTitle);
         return positionRect(w, subRule, subRule2, pe, opt->rect, opt->direction);
                                    }
 #ifndef QT_NO_TOOLBAR
     case SE_ToolBarHandle:
         if (hasStyleRule(w, PseudoElement_ToolBarHandle))
             return ParentStyle::subElementRect(se, opt, w);
         break;
 #endif //QT_NO_TOOLBAR
     default:
         break;
     }
     return baseStyle()->subElementRect(se, opt, w);
 }
titleBarLayout()
QHash< QStyle::SubControl, QRect > QStyleSheetStyle::titleBarLayout (const QWidget * w, const QStyleOptionTitleBar * tb) const private
Definition at line 741 of file qstylesheetstyle.cpp.
Referenced by drawComplexControl(), hitTestComplexControl(), and subControlRect().
 {
     QHash<QStyle::SubControl, QRect> layoutRects;
     const bool isMinimized = tb->titleBarState & Qt::WindowMinimized;
     const bool isMaximized = tb->titleBarState & Qt::WindowMaximized;
     QRenderRule subRule = renderRule(w, tb);
     QRect cr = subRule.contentsRect(tb->rect);
     QList<QVariant> layout = subRule.styleHint(QLatin1String("button-layout")).toList();
     if (layout.isEmpty())
         layout = subControlLayout(QLatin1String("I(T)HSmMX"));
     int offsets[3] = { 0, 0, 0 };
     enum Where { Left, Right, Center, NoWhere } where = Left;
     QList<ButtonInfo> infos;
     for (int i = 0; i < layout.count(); i++) {
         ButtonInfo info;
         info.element = layout[i].toInt();
         if (info.element == '(') {
             where = Center;
         } else if (info.element == ')') {
             where = Right;
         } else {
             switch (info.element) {
             case PseudoElement_TitleBar:
                 if (!(tb->titleBarFlags & (Qt::WindowTitleHint | Qt::WindowSystemMenuHint)))
                     continue;
                 break;
             case PseudoElement_TitleBarContextHelpButton:
                 if (!(tb->titleBarFlags & Qt::WindowContextHelpButtonHint))
                     continue;
                 break;
             case PseudoElement_TitleBarMinButton:
                 if (!(tb->titleBarFlags & Qt::WindowMinimizeButtonHint))
                     continue;
                 if (isMinimized)
                     info.element = PseudoElement_TitleBarNormalButton;
                 break;
             case PseudoElement_TitleBarMaxButton:
                 if (!(tb->titleBarFlags & Qt::WindowMaximizeButtonHint))
                     continue;
                 if (isMaximized)
                     info.element = PseudoElement_TitleBarNormalButton;
                 break;
             case PseudoElement_TitleBarShadeButton:
                 if (!(tb->titleBarFlags & Qt::WindowShadeButtonHint))
                     continue;
                 if (isMinimized)
                     info.element = PseudoElement_TitleBarUnshadeButton;
                 break;
             case PseudoElement_TitleBarCloseButton:
             case PseudoElement_TitleBarSysMenu:
                 if (!(tb->titleBarFlags & Qt::WindowSystemMenuHint))
                     continue;
                 break;
             default:
                 continue;
             }
             if (info.element == PseudoElement_TitleBar) {
                 info.width = tb->fontMetrics.width(tb->text) + 6;
                 subRule.geo = new QStyleSheetGeometryData(info.width, tb->fontMetrics.height(), -1, -1, -1, -1);
             } else {
                 subRule = renderRule(w, tb, info.element);
                 info.width = subRule.size().width();
             }
             info.rule = subRule;
             info.offset = offsets[where];
             info.where = where;
             infos.append(info);
             offsets[where] += info.width;
         }
     }
     for (int i = 0; i < infos.count(); i++) {
         ButtonInfo info = infos[i];
         QRect lr = cr;
         switch (info.where) {
         case Center: {
             lr.setLeft(cr.left() + offsets[Left]);
             lr.setRight(cr.right() - offsets[Right]);
             QRect r(0, 0, offsets[Center], lr.height());
             r.moveCenter(lr.center());
             r.setLeft(r.left()+info.offset);
             r.setWidth(info.width);
             lr = r;
             break; }
         case Left:
             lr.translate(info.offset, 0);
             lr.setWidth(info.width);
             break;
         case Right:
             lr.moveLeft(cr.right() + 1 - offsets[Right] + info.offset);
             lr.setWidth(info.width);
             break;
         default:
             break;
         }
         QStyle::SubControl control = knownPseudoElements[info.element].subControl;
         layoutRects[control] = positionRect(w, info.rule, info.element, lr, tb->direction);
     }
     return layoutRects;
 }
unpolish() [1/2]
void QStyleSheetStyle::unpolish (QWidget * widget) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2792 of file qstylesheetstyle.cpp.
 {
     if (!w || !w->testAttribute(Qt::WA_StyleSheet)) {
         baseStyle()->unpolish(w);
         return;
     }
     styleSheetCaches->styleRulesCache.remove(w);
     styleSheetCaches->hasStyleRuleCache.remove(w);
     styleSheetCaches->renderRulesCache.remove(w);
     styleSheetCaches->styleSheetCache.remove(w);
     unsetPalette(w);
     w->setProperty("_q_stylesheet_minw", QVariant());
     w->setProperty("_q_stylesheet_minh", QVariant());
     w->setProperty("_q_stylesheet_maxw", QVariant());
     w->setProperty("_q_stylesheet_maxh", QVariant());
     w->setAttribute(Qt::WA_StyleSheet, false);
     QObject::disconnect(w, 0, this, 0);
 #ifndef QT_NO_SCROLLAREA
     if (QAbstractScrollArea *sa = qobject_cast<QAbstractScrollArea *>(w)) {
         QObject::disconnect(sa->horizontalScrollBar(), SIGNAL(valueChanged(int)),
                             sa, SLOT(update()));
         QObject::disconnect(sa->verticalScrollBar(), SIGNAL(valueChanged(int)),
                             sa, SLOT(update()));
     }
 #endif
 #ifndef QT_NO_PROGRESSBAR
     if (QProgressBar *pb = qobject_cast<QProgressBar *>(w))
         QWindowsStyle::unpolish(pb);
 #endif
     baseStyle()->unpolish(w);
 }
unpolish() [2/2]
void QStyleSheetStyle::unpolish (QApplication * application) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2825 of file qstylesheetstyle.cpp.
 {
     baseStyle()->unpolish(app);
     RECURSION_GUARD(return)
     styleSheetCaches->styleRulesCache.clear();
     styleSheetCaches->hasStyleRuleCache.clear();
     styleSheetCaches->renderRulesCache.clear();
     styleSheetCaches->styleSheetCache.remove(qApp);
 }
unsetPalette()
void QStyleSheetStyle::unsetPalette (QWidget * w) private
Definition at line 2567 of file qstylesheetstyle.cpp.
Referenced by polish(), and unpolish().
 {
     if (styleSheetCaches->customPaletteWidgets.contains(w)) {
         QPalette p = styleSheetCaches->customPaletteWidgets.value(w);
         w->setPalette(p);
         QWidget *ew = embeddedWidget(w);
         if (ew != w)
             ew->setPalette(p);
         styleSheetCaches->customPaletteWidgets.remove(w);
     }
     QVariant oldFont = w->property("_q_styleSheetWidgetFont");
     if (oldFont.isValid()) {
         w->setFont(qvariant_cast<QFont>(oldFont));
     }
     if (styleSheetCaches->autoFillDisabledWidgets.contains(w)) {
         embeddedWidget(w)->setAutoFillBackground(true);
         styleSheetCaches->autoFillDisabledWidgets.remove(w);
     }
 }
updateStyleSheetFont()
void QStyleSheetStyle::updateStyleSheetFont (QWidget * w) const
Definition at line 5809 of file qstylesheetstyle.cpp.
Referenced by QWidgetPrivate::updateFont().
 {
     QWidget *container = containerWidget(w);
     QRenderRule rule = renderRule(container, PseudoElement_None,
             PseudoClass_Active | PseudoClass_Enabled | extendedPseudoClass(container));
     QFont font = rule.font.resolve(w->font());
     if ((!w->isWindow() || w->testAttribute(Qt::WA_WindowPropagation))
         && isNaturalChild(w) && qobject_cast<QWidget *>(w->parent())) {
         font = font.resolve(static_cast<QWidget *>(w->parent())->font());
     }
     if (w->data->fnt == font)
         return;
 #ifdef QT3_SUPPORT
     QFont old = w->data->fnt;
 #endif
     w->data->fnt = font;
 #if defined(Q_WS_X11)
     // make sure the font set on this widget is associated with the correct screen
     //w->data->fnt.x11SetScreen(w->d_func()->xinfo.screen());
 #endif
     QEvent e(QEvent::FontChange);
     QApplication::sendEvent(w, &e);
 #ifdef QT3_SUPPORT
     w->fontChange(old);
 #endif
 }
Friends and Related Functions
QRenderRule
friend class QRenderRule friend
Definition at line 151 of file qstylesheetstyle_p.h.
Properties
base
QStyle* QStyleSheetStyle::base
Definition at line 126 of file qstylesheetstyle_p.h.
Referenced by baseStyle(), QWidgetPrivate::inheritStyle(), and QApplication::setStyleSheet().
numinstances
int QStyleSheetStyle::numinstances = 0 static
Definition at line 178 of file qstylesheetstyle_p.h.
Referenced by QStyleSheetStyle(), updateWidgets(), and ~QStyleSheetStyle().
parser
QCss::Parser QStyleSheetStyle::parser mutable private
Definition at line 161 of file qstylesheetstyle_p.h.
refcount
int QStyleSheetStyle::refcount private
Definition at line 149 of file qstylesheetstyle_p.h.
The documentation for this class was generated from the following files:
/src/gui/styles/qstylesheetstyle_p.h
/src/gui/styles/qstylesheetstyle.cpp
/src/gui/styles/qstylesheetstyle_default.cpp