Qt 4.8: QLayout Class Reference
QLayout Class Reference abstract
The QLayout class is the base class of geometry managers.
#include <qlayout.h>
Public Types
enum SizeConstraint {
SetDefaultConstraint, SetNoConstraint, SetMinimumSize, SetFixedSize,
SetMaximumSize, SetMinAndMaxSize
}
The possible values are:
Public Functions
bool activate ()
Redoes the layout for parentWidget() if necessary.
virtual void addItem (QLayoutItem *)=0
Implemented in subclasses to add an item.
void addWidget (QWidget *w)
Adds widget w to this layout in a manner specific to the layout.
QMargins contentsMargins () const
Returns the margins used around the layout.
QRect contentsRect () const
Returns the layout's geometry() rectangle, but taking into account the contents margins.
virtual int count () const =0
Must be implemented in subclasses to return the number of items in the layout.
Qt::Orientations expandingDirections () const
Returns whether this layout can make use of more space than sizeHint().
QRect geometry () const
Reimplemented Function
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
virtual int indexOf (QWidget *) const
Searches for widget widget in this layout (not including child layouts).
void invalidate ()
Reimplemented Function
bool isEmpty () const
Reimplemented Function
bool isEnabled () const
Returns true if the layout is enabled; otherwise returns false.
virtual QLayoutItem * itemAt (int index) const =0
Must be implemented in subclasses to return the layout item at index.
QLayout * layout ()
Reimplemented Function
int margin () const
QSize maximumSize () const
Returns the maximum size of this layout.
QWidget * menuBar () const
Returns the menu bar set for this layout, or 0 if no menu bar is set.
QSize minimumSize () const
Returns the minimum size of this layout.
QWidget * parentWidget () const
Returns the parent widget of this layout, or 0 if this layout is not installed on any widget.
QLayout (QWidget *parent)
Constructs a new top-level QLayout, with parent parent.
QLayout ()
Constructs a new child QLayout.
void removeItem (QLayoutItem *)
Removes the layout item item from the layout.
void removeWidget (QWidget *w)
Removes the widget widget from the layout.
bool setAlignment (QWidget *w, Qt::Alignment alignment)
Sets the alignment for widget w to alignment and returns true if w is found in this layout (not including child layouts); otherwise returns false.
bool setAlignment (QLayout *l, Qt::Alignment alignment)
Sets the alignment for the layout l to alignment and returns true if l is found in this layout (not including child layouts); otherwise returns false.
void setContentsMargins (int left, int top, int right, int bottom)
Sets the left, top, right, and bottom margins to use around the layout.
void setContentsMargins (const QMargins &margins)
Sets the margins to use around the layout.
void setEnabled (bool)
Enables this layout if enable is true, otherwise disables it.
virtual void setGeometry (const QRect &)
Reimplemented Function
void setMargin (int)
void setMenuBar (QWidget *w)
Tells the geometry manager to place the menu bar widget at the top of parentWidget(), outside QWidget::contentsMargins().
void setSizeConstraint (SizeConstraint)
void setSpacing (int)
SizeConstraint sizeConstraint () const
int spacing () const
virtual QLayoutItem * takeAt (int index)=0
Must be implemented in subclasses to remove the layout item at index from the layout, and return the item.
int totalHeightForWidth (int w) const
Also takes contentsMargins and menu bar into account.
QSize totalMaximumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalMinimumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalSizeHint () const
Also takes contentsMargins and menu bar into account.
void update ()
Updates the layout for parentWidget().
~QLayout ()
Destroys the layout, deleting all child layouts.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QLayoutItem
Qt::Alignment alignment () const
Returns the alignment of this item.
QSizePolicy::ControlTypes controlTypes () const
Returns the control type(s) for the layout item.
virtual bool hasHeightForWidth () const
Returns true if this layout's preferred height depends on its width; otherwise returns false.
virtual int heightForWidth (int) const
Returns the preferred height for this layout item, given the width w.
virtual int minimumHeightForWidth (int) const
Returns the minimum height this widget needs for the given width, w.
QLayoutItem (Qt::Alignment alignment=0)
Constructs a layout item with an alignment.
void setAlignment (Qt::Alignment a)
Sets the alignment of this item to alignment.
virtual QSize sizeHint () const =0
Implemented in subclasses to return the preferred size of this item.
virtual QSpacerItem * spacerItem ()
If this item is a QSpacerItem, it is returned as a QSpacerItem; otherwise 0 is returned.
virtual QWidget * widget ()
If this item is a QWidget, it is returned as a QWidget; otherwise 0 is returned.
virtual ~QLayoutItem ()
Destroys the QLayoutItem.
Static Public Functions
static QSize closestAcceptableSize (const QWidget *w, const QSize &s)
Returns a size that satisfies all size constraints on widget, including heightForWidth() and that is as close as possible to size.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
void addChildLayout (QLayout *l)
This function is called from addLayout() or insertLayout() functions in subclasses to add layout l as a sub-layout.
void addChildWidget (QWidget *w)
This function is called from addWidget() functions in subclasses to add w as a managed widget of a layout.
bool adoptLayout (QLayout *layout)
QRect alignmentRect (const QRect &) const
Returns the rectangle that should be covered when the geometry of this layout is set to r, provided that this layout supports setAlignment().
void childEvent (QChildEvent *e)
Reimplemented Function
QLayout (QLayoutPrivate &d, QLayout *, QWidget *)
void widgetEvent (QEvent *)
Performs child widget layout when the parent widget is resized.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Private Functions
static void activateRecursiveHelper (QLayoutItem *item)
Properties
int margin
the width of the outside border of the layout
SizeConstraint sizeConstraint
the resize mode of the layout
int spacing
the spacing between widgets inside the layout
Friends
class QApplicationPrivate
class QWidget
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QLayoutItem
Qt::Alignment align
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QLayout class is the base class of geometry managers.
This is an abstract base class inherited by the concrete classes QBoxLayout, QGridLayout, QFormLayout, and QStackedLayout.
For users of QLayout subclasses or of QMainWindow there is seldom any need to use the basic functions provided by QLayout, such as setSizeConstraint() or setMenuBar(). See Layout Management for more information.
To make your own layout manager, implement the functions addItem(), sizeHint(), setGeometry(), itemAt() and takeAt(). You should also implement minimumSize() to ensure your layout isn't resized to zero size if there is too little space. To support children whose heights depend on their widths, implement hasHeightForWidth() and heightForWidth(). See the Border Layout and Flow Layout examples for more information about implementing custom layout managers.
Geometry management stops when the layout manager is deleted.
See also
QLayoutItem, {Layout Management}, {Basic Layouts Example}, {Border Layout Example}, {Flow Layout Example}
Definition at line 90 of file qlayout.h.
Enumerations
SizeConstraint
enum QLayout::SizeConstraint
The possible values are:
SetDefaultConstraint The main widget's minimum size is set to minimumSize(), unless the widget already has a minimum size.
SetFixedSize The main widget's size is set to sizeHint(); it cannot be resized at all.
SetMinimumSize The main widget's minimum size is set to minimumSize(); it cannot be smaller.
SetMaximumSize The main widget's maximum size is set to maximumSize(); it cannot be larger.
SetMinAndMaxSize The main widget's minimum size is set to minimumSize() and its maximum size is set to maximumSize().
SetNoConstraint The widget is not constrained.
Auto
FreeResize
Minimum
Fixed
See also
setSizeConstraint()
Enumerator
SetDefaultConstraint
SetNoConstraint
SetMinimumSize
SetFixedSize
SetMaximumSize
SetMinAndMaxSize
Definition at line 100 of file qlayout.h.
{
         SetDefaultConstraint,
         SetNoConstraint,
         SetMinimumSize,
         SetFixedSize,
         SetMaximumSize,
         SetMinAndMaxSize
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         , Auto = SetDefaultConstraint,
         FreeResize = SetNoConstraint,
         Minimum = SetMinimumSize,
         Fixed = SetFixedSize
 #endif
     };
Constructors and Destructors
QLayout() [1/3]
QLayout::QLayout (QWidget * parent)
Constructs a new top-level QLayout, with parent parent.
parent may not be 0.
There can be only one top-level layout for a widget. It is returned by QWidget::layout().
Definition at line 113 of file qlayout.cpp.
     : QObject(*new QLayoutPrivate, parent)
 {
     if (!parent)
         return;
     parent->setLayout(this);
 }
QLayout() [2/3]
QLayout::QLayout ()
Constructs a new child QLayout.
This layout has to be inserted into another layout before geometry management will work.
Definition at line 127 of file qlayout.cpp.
Referenced by QLayoutPrivate::createSpacerItem(), QBoxLayout::QBoxLayout(), and QGridLayout::QGridLayout().
     : QObject(*new QLayoutPrivate, 0)
 {
 }
~QLayout()
QLayout::~QLayout ()
Destroys the layout, deleting all child layouts.
Warning
This function is not part of the public interface.
Geometry management stops when a top-level layout is deleted.
The layout classes will probably be fatally confused if you delete a sublayout.
Definition at line 936 of file qlayout.cpp.
 {
     Q_D(QLayout);
     /*
       This function may be called during the QObject destructor,
       when the parent no longer is a QWidget.
     */
     if (d->topLevel && parent() && parent()->isWidgetType() &&
          ((QWidget*)parent())->layout() == this)
         ((QWidget*)parent())->d_func()->layout = 0;
 }
QLayout() [3/3]
QLayout::QLayout (QLayoutPrivate & dd, QLayout * lay, QWidget * w) protected
Warning
This function is not part of the public interface.
Definition at line 135 of file qlayout.cpp.
     : QObject(dd, lay ? static_cast<QObject*>(lay) : static_cast<QObject*>(w))
 {
     Q_D(QLayout);
     if (lay) {
         lay->addItem(this);
     } else if (w) {
         if (w->layout()) {
             qWarning("QLayout: Attempting to add QLayout \"%s\" to %s \"%s\", which"
                      " already has a layout",
                      qPrintable(QObject::objectName()), w->metaObject()->className(),
                      w->objectName().toLocal8Bit().data());
             setParent(0);
         } else {
             d->topLevel = true;
             w->d_func()->layout = this;
             QT_TRY {
                 invalidate();
             } QT_CATCH(...) {
                 w->d_func()->layout = 0;
                 QT_RETHROW;
             }
         }
     }
 }
Functions
activate()
bool QLayout::activate ()
Redoes the layout for parentWidget() if necessary.
You should generally not need to call this because it is automatically called at the most appropriate times. It returns true if the layout was redone.
See also
update(), QWidget::updateGeometry()
Definition at line 1249 of file qlayout.cpp.
Referenced by QWidgetPrivate::activateChildLayoutsRecursively(), QMessageBoxPrivate::layoutMinimumWidth(), QWidget::setVisible(), QWidgetPrivate::show_recursive(), QComboBox::showPopup(), and QMessageBoxPrivate::updateSize().
 {
     Q_D(QLayout);
     if (!d->enabled || !parent())
         return false;
     if (!d->topLevel)
         return static_cast<QLayout*>(parent())->activate();
     if (d->activated)
         return false;
     QWidget *mw = static_cast<QWidget*>(parent());
     if (mw == 0) {
         qWarning("QLayout::activate: %s \"%s\" does not have a main widget",
                  QObject::metaObject()->className(), QObject::objectName().toLocal8Bit().data());
         return false;
     }
     activateRecursiveHelper(this);
     QWidgetPrivate *md = mw->d_func();
     uint explMin = md->extra ? md->extra->explicitMinSize : 0;
     uint explMax = md->extra ? md->extra->explicitMaxSize : 0;
     switch (d->constraint) {
     case SetFixedSize:
         // will trigger resize
         mw->setFixedSize(totalSizeHint());
         break;
     case SetMinimumSize:
         mw->setMinimumSize(totalMinimumSize());
         break;
     case SetMaximumSize:
         mw->setMaximumSize(totalMaximumSize());
         break;
     case SetMinAndMaxSize:
         mw->setMinimumSize(totalMinimumSize());
         mw->setMaximumSize(totalMaximumSize());
         break;
     case SetDefaultConstraint: {
         bool widthSet = explMin & Qt::Horizontal;
         bool heightSet = explMin & Qt::Vertical;
         if (mw->isWindow()) {
             QSize ms = totalMinimumSize();
             if (widthSet)
                 ms.setWidth(mw->minimumSize().width());
             if (heightSet)
                 ms.setHeight(mw->minimumSize().height());
             if ((!heightSet || !widthSet) && hasHeightForWidth()) {
                 int h = minimumHeightForWidth(ms.width());
                 if (h > ms.height()) {
                     if (!heightSet)
                         ms.setHeight(0);
                     if (!widthSet)
                         ms.setWidth(0);
                 }
             }
             mw->setMinimumSize(ms);
         } else if (!widthSet || !heightSet) {
             QSize ms = mw->minimumSize();
             if (!widthSet)
                 ms.setWidth(0);
             if (!heightSet)
                 ms.setHeight(0);
             mw->setMinimumSize(ms);
         }
         break;
     }
     case SetNoConstraint:
         break;
     }
     d->doResize(mw->size());
     if (md->extra) {
         md->extra->explicitMinSize = explMin;
         md->extra->explicitMaxSize = explMax;
     }
     // ideally only if sizeHint() or sizePolicy() has changed
     mw->updateGeometry();
     return true;
 }
activateRecursiveHelper()
void QLayout::activateRecursiveHelper (QLayoutItem * item) static private
Definition at line 1203 of file qlayout.cpp.
 {
     item->invalidate();
     QLayout *layout = item->layout();
     if (layout) {
         QLayoutItem *child;
         int i=0;
         while ((child = layout->itemAt(i++)))
             activateRecursiveHelper(child);
         layout->d_func()->activated = true;
     }
 }
addChildLayout()
void QLayout::addChildLayout (QLayout * l) protected
This function is called from addLayout() or insertLayout() functions in subclasses to add layout l as a sub-layout.
The only scenario in which you need to call it directly is if you implement a custom layout that supports nested layouts.
See also
QBoxLayout::addLayout(), QBoxLayout::insertLayout(), QGridLayout::addLayout()
Definition at line 969 of file qlayout.cpp.
 {
     if (l->parent()) {
         qWarning("QLayout::addChildLayout: layout \"%s\" already has a parent",
                  l->objectName().toLocal8Bit().data());
         return;
     }
     l->setParent(this);
     if (QWidget *mw = parentWidget()) {
         l->d_func()->reparentChildWidgets(mw);
     }
 }
addChildWidget()
void QLayout::addChildWidget (QWidget * w) protected
This function is called from addWidget() functions in subclasses to add w as a managed widget of a layout.
If w is already managed by a layout, this function will give a warning and remove w from that layout. This function must therefore be called before adding w to the layout's data structure.
Definition at line 1045 of file qlayout.cpp.
Referenced by QGridLayout::addWidget(), QStackedLayout::insertWidget(), QBoxLayout::insertWidget(), QMainWindowLayout::setCentralWidget(), QMainWindowLayout::setStatusBar(), and QDockWidgetLayout::setWidgetForRole().
 {
     QWidget *mw = parentWidget();
     QWidget *pw = w->parentWidget();
     //Qt::WA_LaidOut is never reset. It only means that the widget at some point has
     //been in a layout.
     if (pw && w->testAttribute(Qt::WA_LaidOut)) {
         QLayout *l = pw->layout();
         if (l && removeWidgetRecursively(l, w)) {
 #ifdef QT_DEBUG
             if (layoutDebug())
                 qWarning("QLayout::addChildWidget: %s \"%s\" is already in a layout; moved to new layout",
                          w->metaObject()->className(), w->objectName().toLocal8Bit().data());
 #endif
         }
     }
     if (pw && mw && pw != mw) {
 #ifdef QT_DEBUG
             if (layoutDebug())
                 qWarning("QLayout::addChildWidget: %s \"%s\" in wrong parent; moved to correct parent",
                          w->metaObject()->className(), w->objectName().toLocal8Bit().data());
 #endif
         pw = 0;
     }
     bool needShow = mw && mw->isVisible() && !(w->isHidden() && w->testAttribute(Qt::WA_WState_ExplicitShowHide));
     if (!pw && mw)
         w->setParent(mw);
     w->setAttribute(Qt::WA_LaidOut);
     if (needShow)
         QMetaObject::invokeMethod(w, "_q_showIfNotHidden", Qt::QueuedConnection); //show later
 }
addItem()
void QLayout::addItem (QLayoutItem * item) pure virtual
Implemented in subclasses to add an item.
How it is added is specific to each subclass.
This function is not usually called in application code. To add a widget to a layout, use the addWidget() function; to add a child layout, use the addLayout() function provided by the relevant QLayout subclass.
Note: The ownership of item is transferred to the layout, and it's the layout's responsibility to delete it.
See also
addWidget(), QBoxLayout::addLayout(), QGridLayout::addLayout()
Implemented in QMainWindowLayout, QGridLayout, QDockWidgetLayout, QFormLayout, QStackedLayout, QBoxLayout, and QToolBarLayout.
Referenced by QGridLayout::addWidget(), QLayoutPrivate::createSpacerItem(), QHBoxLayout::QHBoxLayout(), QLayout(), and QVBoxLayout::QVBoxLayout().
addWidget()
void QLayout::addWidget (QWidget * w)
Adds widget w to this layout in a manner specific to the layout.
This function uses addItem().
Definition at line 319 of file qlayout.cpp.
Referenced by QGridLayout::addWidget(), QAbstractScrollAreaScrollBarContainer::QAbstractScrollAreaScrollBarContainer(), QWizardHeader::QWizardHeader(), QToolBoxPrivate::relayout(), QMdiSubWindowPrivate::setSizeGrip(), QMdiSubWindow::setWidget(), and QMenuBarPrivate::updateCornerWidgetToolBar().
 {
     addChildWidget(w);
     addItem(QLayoutPrivate::createWidgetItem(this, w));
 }
adoptLayout()
bool QLayout::adoptLayout (QLayout * layout) protected
Warning
This function is not part of the public interface.
Definition at line 987 of file qlayout.cpp.
Referenced by QGridLayout::addLayout(), and QBoxLayout::insertLayout().
 {
     const bool ok = !layout->parent();
     addChildLayout(layout);
     return ok;
 }
alignmentRect()
QRect QLayout::alignmentRect (const QRect & r) const protected
Returns the rectangle that should be covered when the geometry of this layout is set to r, provided that this layout supports setAlignment().
The result is derived from sizeHint() and expanding(). It is never larger than r.
Definition at line 1459 of file qlayout.cpp.
Referenced by QBoxLayout::setGeometry(), and QGridLayout::setGeometry().
 {
     QSize s = sizeHint();
     Qt::Alignment a = alignment();
     /*
       This is a hack to obtain the real maximum size, not
       QSize(QLAYOUTSIZE_MAX, QLAYOUTSIZE_MAX), the value consistently
       returned by QLayoutItems that have an alignment.
     */
     QLayout *that = const_cast<QLayout *>(this);
     that->setAlignment(0);
     QSize ms = that->maximumSize();
     that->setAlignment(a);
     if ((expandingDirections() & Qt::Horizontal) ||
          !(a & Qt::AlignHorizontal_Mask)) {
         s.setWidth(qMin(r.width(), ms.width()));
     }
     if ((expandingDirections() & Qt::Vertical) ||
          !(a & Qt::AlignVertical_Mask)) {
         s.setHeight(qMin(r.height(), ms.height()));
     } else if (hasHeightForWidth()) {
         int hfw = heightForWidth(s.width());
         if (hfw < s.height())
             s.setHeight(qMin(hfw, ms.height()));
     }
     s = s.boundedTo(r.size());
     int x = r.x();
     int y = r.y();
     if (a & Qt::AlignBottom)
         y += (r.height() - s.height());
     else if (!(a & Qt::AlignTop))
         y += (r.height() - s.height()) / 2;
     QWidget *parent = parentWidget();
     a = QStyle::visualAlignment(parent ? parent->layoutDirection() : QApplication::layoutDirection(), a);
     if (a & Qt::AlignRight)
         x += (r.width() - s.width());
     else if (!(a & Qt::AlignLeft))
         x += (r.width() - s.width()) / 2;
     return QRect(x, y, s.width(), s.height());
 }
childEvent()
void QLayout::childEvent (QChildEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 793 of file qlayout.cpp.
 {
     Q_D(QLayout);
     if (!d->enabled)
         return;
     if (e->type() == QEvent::ChildRemoved) {
         QChildEvent *c = (QChildEvent*)e;
         int i = 0;
         QLayoutItem *item;
         while ((item = itemAt(i))) {
             if (item == static_cast<QLayout*>(c->child())) {
                 takeAt(i);
                 invalidate();
                 break;
             } else {
                 ++i;
             }
         }
     }
 }
closestAcceptableSize()
QSize QLayout::closestAcceptableSize (const QWidget * w, const QSize & s) static
Returns a size that satisfies all size constraints on widget, including heightForWidth() and that is as close as possible to size.
Definition at line 1586 of file qlayout.cpp.
Referenced by make_win_eventUPP(), QSizeGrip::mouseMoveEvent(), and QtWndProc().
 {
     QSize result = size.boundedTo(qSmartMaxSize(widget));
     result = result.expandedTo(qSmartMinSize(widget));
     QLayout *l = widget->layout();
     if (l && l->hasHeightForWidth() && result.height() < l->minimumHeightForWidth(result.width()) ) {
         QSize current = widget->size();
         int currentHfw =  l->minimumHeightForWidth(current.width());
         int newHfw = l->minimumHeightForWidth(result.width());
         if (current.height() < currentHfw || currentHfw == newHfw) {
             //handle the constant hfw case and the vertical-only case, as well as the
             // current-size-is-not-correct case
             result.setHeight(newHfw);
         } else {
             // binary search; assume hfw is decreasing ###
             int maxw = qMax(widget->width(),result.width());
             int maxh = qMax(widget->height(), result.height());
             int minw = qMin(widget->width(),result.width());
             int minh = qMin(widget->height(), result.height());
             int minhfw = l->minimumHeightForWidth(minw);
             int maxhfw = l->minimumHeightForWidth(maxw);
             while (minw < maxw) {
                 if (minhfw > maxh) { //assume decreasing
                     minw = maxw - (maxw-minw)/2;
                     minhfw = l->minimumHeightForWidth(minw);
                 } else if (maxhfw < minh ) { //assume decreasing
                     maxw = minw + (maxw-minw)/2;
                     maxhfw = l->minimumHeightForWidth(maxw);
                 } else  {
                     break;
                 }
             }
             result = result.expandedTo(QSize(minw, minhfw));
         }
     }
     return result;
 }
contentsMargins()
QMargins QLayout::contentsMargins () const
Returns the margins used around the layout.
Since
4.6
By default, QLayout uses the values provided by the style. On most platforms, the margin is 11 pixels in all directions.
See also
setContentsMargins()
Definition at line 573 of file qlayout.cpp.
 {
     int left, top, right, bottom;
     getContentsMargins(&left, &top, &right, &bottom);
     return QMargins(left, top, right, bottom);
 }
contentsRect()
QRect QLayout::contentsRect () const
Returns the layout's geometry() rectangle, but taking into account the contents margins.
Since
4.3
See also
setContentsMargins(), getContentsMargins()
Definition at line 591 of file qlayout.cpp.
 {
     Q_D(const QLayout);
     int left, top, right, bottom;
     getContentsMargins(&left, &top, &right, &bottom);
     return d->rect.adjusted(+left, +top, -right, -bottom);
 }
count()
int * QLayout::count () const pure virtual
Must be implemented in subclasses to return the number of items in the layout.
See also
itemAt()
Implemented in QMainWindowLayout, QFormLayout, QDockWidgetLayout, QGridLayout, QBoxLayout, QToolBarLayout, and QStackedLayout.
Referenced by QGridLayout::addWidget(), QLayoutItem::controlTypes(), QAbstractScrollAreaScrollBarContainer::scrollBarLayoutIndex(), QMenuBarPrivate::updateCornerWidgetToolBar(), and QAbstractScrollAreaScrollBarContainer::widgets().
expandingDirections()
Qt::Orientations QLayout::expandingDirections () const virtual
Returns whether this layout can make use of more space than sizeHint().
A value of Qt::Vertical or Qt::Horizontal means that it wants to grow in only one dimension, whereas Qt::Vertical | Qt::Horizontal means that it wants to grow in both dimensions.
The default implementation returns Qt::Horizontal | Qt::Vertical. Subclasses reimplement it to return a meaningful value based on their child widgets's size policies.
See also
sizeHint()
Implements QLayoutItem.
Reimplemented in QToolBarLayout.
Definition at line 1198 of file qlayout.cpp.
Referenced by QWidgetPrivate::adjustedSize().
 {
     return Qt::Horizontal | Qt::Vertical;
 }
geometry()
QRect QLayout::geometry () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 664 of file qlayout.cpp.
Referenced by QDockWidgetPrivate::endDrag(), QBoxLayout::setGeometry(), QGridLayout::setGeometry(), QFormLayout::setGeometry(), QDockWidgetLayout::setGeometry(), and QStackedLayout::setStackingMode().
 {
     Q_D(const QLayout);
     return d->rect;
 }
getContentsMargins()
void QLayout::getContentsMargins (int * left, int * top, int * right, int * bottom) const
Since
4.3
Extracts the left, top, right, and bottom margins used around the layout, and assigns them to *left, *top, *right, and *bottom (unless they are null pointers).
By default, QLayout uses the values provided by the style. On most platforms, the margin is 11 pixels in all directions.
See also
setContentsMargins(), QStyle::pixelMetric(), {QStyle::}{PM_LayoutLeftMargin}, {QStyle::}{PM_LayoutTopMargin}, {QStyle::}{PM_LayoutRightMargin}, {QStyle::}{PM_LayoutBottomMargin}
Definition at line 551 of file qlayout.cpp.
Referenced by QFormLayout::heightForWidth(), QFontDialogPrivate::init(), and QFormLayout::setGeometry().
 {
     Q_D(const QLayout);
     d->getMargin(left, d->userLeftMargin, QStyle::PM_LayoutLeftMargin);
     d->getMargin(top, d->userTopMargin, QStyle::PM_LayoutTopMargin);
     d->getMargin(right, d->userRightMargin, QStyle::PM_LayoutRightMargin);
     d->getMargin(bottom, d->userBottomMargin, QStyle::PM_LayoutBottomMargin);
 }
indexOf()
int QLayout::indexOf (QWidget * widget) const virtual
Searches for widget widget in this layout (not including child layouts).
Returns the index of widget, or -1 if widget is not found.
The default implementation iterates over all items using itemAt()
Reimplemented in QToolBarLayout.
Definition at line 1378 of file qlayout.cpp.
Referenced by QFormLayout::getWidgetPosition(), QToolBarLayout::indexOf(), QGridLayout::minimumHeightForWidth(), QStackedLayout::setCurrentWidget(), and QMdiSubWindowPrivate::setSizeGrip().
 {
     int i = 0;
     QLayoutItem *item = itemAt(i);
     while (item) {
         if (item->widget() == widget)
             return i;
         ++i;
         item = itemAt(i);
     }
     return -1;
 }
invalidate()
void QLayout::invalidate () virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Reimplemented in QMainWindowLayout, and QToolBarLayout.
Definition at line 673 of file qlayout.cpp.
Referenced by QStackedLayout::insertWidget(), QToolBarLayout::invalidate(), QBoxLayout::invalidate(), QGridLayout::invalidate(), QFormLayout::invalidate(), QMainWindowLayout::invalidate(), QLayout(), removeWidgetRecursively(), QWidget::setLayout(), QDockWidgetLayout::setVerticalTitleBar(), QWidget::setVisible(), QDockWidgetLayout::setWidgetForRole(), QDockWidgetLayout::takeAt(), QDockWidgetPrivate::updateButtons(), and QWidgetPrivate::updateGeometry_helper().
 {
     Q_D(QLayout);
     d->rect = QRect();
     update();
 }
isEmpty()
bool QLayout::isEmpty () const virtual
Reimplemented Function
Implements QLayoutItem.
Reimplemented in QToolBarLayout.
Definition at line 639 of file qlayout.cpp.
 {
     int i = 0;
     QLayoutItem *item = itemAt(i);
     while (item) {
         if (!item->isEmpty())
             return false;
         ++i;
         item = itemAt(i);
     }
     return true;
 }
isEnabled()
bool QLayout::isEnabled () const
Returns true if the layout is enabled; otherwise returns false.
See also
setEnabled()
Definition at line 1574 of file qlayout.cpp.
 {
     Q_D(const QLayout);
     return d->enabled;
 }
itemAt()
QLayoutItem * QLayout::itemAt (int index) const pure virtual
Must be implemented in subclasses to return the layout item at index.
If there is no such item, the function must return 0. Items are numbered consecutively from 0. If an item is deleted, other items will be renumbered.
This function can be used to iterate over a layout. The following code will draw a rectangle for each layout item in the layout structure of the widget.
static void paintLayout(QPainter *painter, QLayoutItem *item)
{
    QLayout *layout = item->layout();
    if (layout) {
        for (int i = 0; i < layout->count(); ++i)
            paintLayout(painter, layout->itemAt(i));
    }
    painter->drawRect(item->geometry());
}
void MyWidget::paintEvent(QPaintEvent *)
{
    QPainter painter(this);
    if (layout())
        paintLayout(&painter, layout());
}
See also
count(), takeAt()
Implemented in QMainWindowLayout, QDockWidgetLayout, QFormLayout, QGridLayout, QBoxLayout, QStackedLayout, and QToolBarLayout.
Referenced by activateRecursiveHelper(), QGridLayout::addWidget(), changeSpacerSize(), QLayoutItem::controlTypes(), removeWidgetRecursively(), QAbstractScrollAreaScrollBarContainer::scrollBarLayoutIndex(), QToolBar::setIconSize(), QDeclarativeView::setRootObject(), and QAbstractScrollAreaScrollBarContainer::widgets().
layout()
QLayout * QLayout::layout () virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 360 of file qlayoutitem.cpp.
Referenced by QFormLayoutItem::layout(), QWidget::layout(), QToolBarLayout::setExpanded(), QBoxLayout::setStretchFactor(), and QMenuBarPrivate::updateCornerWidgetToolBar().
 {
     return this;
 }
margin()
int QLayout::margin () const
Referenced by QToolBarLayout::expandedSize(), QToolBarLayout::layoutActions(), QBoxLayout::QBoxLayout(), QGridLayout::QGridLayout(), QHBoxLayout::QHBoxLayout(), QVBoxLayout::QVBoxLayout(), setAlignment(), QToolBarLayout::setGeometry(), and QToolBarLayout::updateGeomArray().
maximumSize()
QSize QLayout::maximumSize () const virtual
Returns the maximum size of this layout.
This is the largest size that the layout can have while still respecting the specifications.
The returned value doesn't include the space required by QWidget::setContentsMargins() or menuBar().
The default implementation allows unlimited resizing.
Implements QLayoutItem.
Reimplemented in QDockWidgetLayout.
Definition at line 1181 of file qlayout.cpp.
Referenced by alignmentRect(), and QToolBarLayout::layoutActions().
 {
     return QSize(QLAYOUTSIZE_MAX, QLAYOUTSIZE_MAX);
 }
menuBar()
QWidget * QLayout::menuBar () const
Returns the menu bar set for this layout, or 0 if no menu bar is set.
Definition at line 1149 of file qlayout.cpp.
Referenced by QMainWindow::menuBar(), QMainWindow::menuWidget(), and QMainWindow::setMenuBar().
 {
     Q_D(const QLayout);
     return d->menubar;
 }
minimumSize()
QSize QLayout::minimumSize () const virtual
Returns the minimum size of this layout.
This is the smallest size that the layout can have while still respecting the specifications.
The returned value doesn't include the space required by QWidget::setContentsMargins() or menuBar().
The default implementation allows unlimited resizing.
Implements QLayoutItem.
Reimplemented in QMainWindowLayout, QDockWidgetLayout, QToolBarLayout, and QStackedLayout.
Definition at line 1166 of file qlayout.cpp.
Referenced by QMdiSubWindow::minimumSizeHint().
 {
     return QSize(0, 0);
 }
parentWidget()
QWidget * QLayout::parentWidget () const
Returns the parent widget of this layout, or 0 if this layout is not installed on any widget.
If the layout is a sub-layout, this function returns the parent widget of the parent layout.
See also
parent()
Definition at line 616 of file qlayout.cpp.
Referenced by QToolBarLayout::createItem(), QToolBarLayout::expandedSize(), QToolBarLayout::expandingDirections(), QMainWindowLayout::hover(), QToolBarLayout::layoutActions(), QDockWidgetLayout::maximumSize(), QDockWidgetLayout::minimumSize(), QDockWidgetLayout::minimumTitleWidth(), QToolBarLayout::movable(), QDockWidgetLayout::nativeWindowDeco(), parentWidget(), QMainWindowLayout::restoreState(), QStackedLayout::setCurrentIndex(), QToolBarLayout::setExpanded(), QToolBarLayout::setGeometry(), QBoxLayout::setGeometry(), QDockWidgetLayout::setGeometry(), QDockWidgetLayout::setVerticalTitleBar(), QDockWidgetLayout::sizeFromContent(), QDockWidgetLayout::sizeHint(), QMainWindowLayout::timerEvent(), QDockWidgetLayout::titleHeight(), QToolBarLayout::updateGeomArray(), and QToolBarLayout::updateMarginAndSpacing().
 {
     Q_D(const QLayout);
     if (!d->topLevel) {
         if (parent()) {
             QLayout *parentLayout = qobject_cast<QLayout*>(parent());
             if (!parentLayout) {
                 qWarning("QLayout::parentWidget: A layout can only have another layout as a parent.");
                 return 0;
             }
             return parentLayout->parentWidget();
         } else {
             return 0;
         }
     } else {
         Q_ASSERT(parent() && parent()->isWidgetType());
         return static_cast<QWidget *>(parent());
     }
 }
removeItem()
void QLayout::removeItem (QLayoutItem * item)
Removes the layout item item from the layout.
It is the caller's responsibility to delete the item.
Notice that item can be a layout (since QLayout inherits QLayoutItem).
See also
removeWidget(), addItem()
Definition at line 1539 of file qlayout.cpp.
 {
     int i = 0;
     QLayoutItem *child;
     while ((child = itemAt(i))) {
         if (child == item) {
             takeAt(i);
             invalidate();
         } else {
             ++i;
         }
     }
 }
removeWidget()
void QLayout::removeWidget (QWidget * widget)
Removes the widget widget from the layout.
After this call, it is the caller's responsibility to give the widget a reasonable geometry or to put the widget back into a layout.
Note: The ownership of widget remains the same as when it was added.
See also
removeItem(), QWidget::setGeometry(), addWidget()
Definition at line 1516 of file qlayout.cpp.
Referenced by QToolBoxPrivate::_q_widgetDestroyed(), QMdiSubWindowPrivate::removeBaseWidget(), QAbstractScrollAreaPrivate::replaceScrollBar(), QMessageBox::setInformativeText(), QInputDialogPrivate::setInputWidget(), and QDockWidgetLayout::setWidgetForRole().
 {
     int i = 0;
     QLayoutItem *child;
     while ((child = itemAt(i))) {
         if (child->widget() == widget) {
             delete takeAt(i);
             invalidate();
         } else {
             ++i;
         }
     }
 }
setAlignment() [1/2]
bool QLayout::setAlignment (QWidget * w, Qt::Alignment alignment)
Sets the alignment for widget w to alignment and returns true if w is found in this layout (not including child layouts); otherwise returns false.
Definition at line 332 of file qlayout.cpp.
Referenced by alignmentRect(), QPrintPreviewDialogPrivate::init(), and QMdiSubWindowPrivate::setSizeGrip().
 {
     int i = 0;
     QLayoutItem *item = itemAt(i);
     while (item) {
         if (item->widget() == w) {
             item->setAlignment(alignment);
             invalidate();
             return true;
         }
         ++i;
         item = itemAt(i);
     }
     return false;
 }
setAlignment() [2/2]
bool QLayout::setAlignment (QLayout * l, Qt::Alignment alignment)
Sets the alignment for the layout l to alignment and returns true if l is found in this layout (not including child layouts); otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 358 of file qlayout.cpp.
 {
     int i = 0;
     QLayoutItem *item = itemAt(i);
     while (item) {
         if (item->layout() == l) {
             item->setAlignment(alignment);
             invalidate();
             return true;
         }
         ++i;
         item = itemAt(i);
     }
     return false;
 }
setContentsMargins() [1/2]
void QLayout::setContentsMargins (int left, int top, int right, int bottom)
Sets the left, top, right, and bottom margins to use around the layout.
Since
4.3
By default, QLayout uses the values provided by the style. On most platforms, the margin is 11 pixels in all directions.
See also
getContentsMargins(), QStyle::pixelMetric(), {QStyle::}{PM_LayoutLeftMargin}, {QStyle::}{PM_LayoutTopMargin}, {QStyle::}{PM_LayoutRightMargin}, {QStyle::}{PM_LayoutBottomMargin}
Definition at line 502 of file qlayout.cpp.
Referenced by QMainWindowPrivate::init(), QPrintPreviewDialogPrivate::init(), QPrintPreviewWidgetPrivate::init(), and QDialogButtonBoxPrivate::initLayout().
 {
     Q_D(QLayout);
     if (d->userLeftMargin == left && d->userTopMargin == top &&
         d->userRightMargin == right && d->userBottomMargin == bottom)
         return;
     d->userLeftMargin = left;
     d->userTopMargin = top;
     d->userRightMargin = right;
     d->userBottomMargin = bottom;
     invalidate();
 }
setContentsMargins() [2/2]
void QLayout::setContentsMargins (const QMargins & margins)
Sets the margins to use around the layout.
Since
4.6
By default, QLayout uses the values provided by the style. On most platforms, the margin is 11 pixels in all directions.
See also
contentsMargins()
Definition at line 530 of file qlayout.cpp.
 {
     setContentsMargins(margins.left(), margins.top(), margins.right(), margins.bottom());
 }
setEnabled()
void QLayout::setEnabled (bool enable)
Enables this layout if enable is true, otherwise disables it.
An enabled layout adjusts dynamically to changes; a disabled layout acts as if it did not exist.
By default all layouts are enabled.
See also
isEnabled()
Definition at line 1563 of file qlayout.cpp.
Referenced by QDialog::showExtension().
 {
     Q_D(QLayout);
     d->enabled = enable;
 }
setGeometry()
void QLayout::setGeometry (const QRect & r) virtual
Reimplemented Function
Implements QLayoutItem.
Reimplemented in QMainWindowLayout, QDockWidgetLayout, QFormLayout, QGridLayout, QBoxLayout, QStackedLayout, and QToolBarLayout.
Definition at line 655 of file qlayout.cpp.
Referenced by QGridLayout::addWidget(), QToolBarLayout::setGeometry(), QBoxLayout::setGeometry(), QGridLayout::setGeometry(), QFormLayout::setGeometry(), and QMainWindowLayout::setGeometry().
 {
     Q_D(QLayout);
     d->rect = r;
 }
setMargin()
void QLayout::setMargin (int margin)
Definition at line 464 of file qlayout.cpp.
Referenced by QCalendarWidgetPrivate::createNavigationBar(), QWorkspaceChild::iconWidget(), QPrintPreviewDialogPrivate::init(), QMessageBoxPrivate::init(), QAbstractScrollAreaScrollBarContainer::QAbstractScrollAreaScrollBarContainer(), QBalloonTip::QBalloonTip(), QBoxLayout::QBoxLayout(), QCalendarWidget::QCalendarWidget(), QColorShower::QColorShower(), QComboBoxPrivateContainer::QComboBoxPrivateContainer(), QGridLayout::QGridLayout(), QHBoxLayout::QHBoxLayout(), QMdiSubWindow::QMdiSubWindow(), QMessageBoxDetailsText::QMessageBoxDetailsText(), QScriptBreakpointsWidget::QScriptBreakpointsWidget(), QScriptDebuggerCodeFinderWidget::QScriptDebuggerCodeFinderWidget(), QScriptDebuggerCodeView::QScriptDebuggerCodeView(), QScriptDebuggerCodeWidget::QScriptDebuggerCodeWidget(), QScriptDebuggerConsoleWidget::QScriptDebuggerConsoleWidget(), QScriptDebuggerLocalsWidget::QScriptDebuggerLocalsWidget(), QScriptDebuggerScriptsWidget::QScriptDebuggerScriptsWidget(), QScriptDebuggerStackWidget::QScriptDebuggerStackWidget(), QScriptDebugOutputWidget::QScriptDebugOutputWidget(), QScriptErrorLogWidget::QScriptErrorLogWidget(), QScriptNewBreakpointWidget::QScriptNewBreakpointWidget(), QVBoxLayout::QVBoxLayout(), QWizardHeader::QWizardHeader(), QToolBoxPrivate::relayout(), QCalendarPopup::setCalendarWidget(), QScriptEngineDebugger::standardWindow(), QCoreFuriCuri::timerEvent(), and QToolBarLayout::updateMarginAndSpacing().
 {
     setContentsMargins(margin, margin, margin, margin);
 }
setMenuBar()
void QLayout::setMenuBar (QWidget * widget)
Tells the geometry manager to place the menu bar widget at the top of parentWidget(), outside QWidget::contentsMargins().
All child widgets are placed below the bottom edge of the menu bar.
Definition at line 1131 of file qlayout.cpp.
Referenced by QMainWindow::setMenuBar().
 {
     Q_D(QLayout);
 #ifdef Q_OS_WINCE_WM
     if (widget && widget->size().height() > 0)
 #else
         if (widget)
 #endif
             addChildWidget(widget);
     d->menubar = widget;
 }
setSizeConstraint()
void QLayout::setSizeConstraint (SizeConstraint constraint)
Definition at line 1435 of file qlayout.cpp.
Referenced by QInputDialogPrivate::ensureLayout(), QColorDialogPrivate::init(), QDockWidgetPrivate::init(), QMessageBoxPrivate::init(), and QBalloonTip::QBalloonTip().
 {
     Q_D(QLayout);
     if (constraint == d->constraint)
         return;
     d->constraint = constraint;
     invalidate();
 }
setSpacing()
void QLayout::setSpacing (int spacing)
Definition at line 469 of file qlayout.cpp.
Referenced by QAbstractScrollAreaScrollBarContainer::QAbstractScrollAreaScrollBarContainer(), QWizardHeader::QWizardHeader(), and QToolBarLayout::updateMarginAndSpacing().
 {
     if (QBoxLayout* boxlayout = qobject_cast<QBoxLayout*>(this)) {
         boxlayout->setSpacing(spacing);
     } else if (QGridLayout* gridlayout = qobject_cast<QGridLayout*>(this)) {
         gridlayout->setSpacing(spacing);
     } else if (QFormLayout* formlayout = qobject_cast<QFormLayout*>(this)) {
         formlayout->setSpacing(spacing);
     } else {
         Q_D(QLayout);
         d->insideSpacing = spacing;
         invalidate();
     }
 }
sizeConstraint()
SizeConstraint QLayout::sizeConstraint () const
Referenced by setSizeConstraint().
spacing()
int QLayout::spacing () const
Referenced by QToolBarLayout::expandedSize(), QToolBarLayout::layoutActions(), setAlignment(), and QToolBarLayout::updateGeomArray().
takeAt()
QLayoutItem * QLayout::takeAt (int index) pure virtual
Must be implemented in subclasses to remove the layout item at index from the layout, and return the item.
If there is no such item, the function must do nothing and return 0. Items are numbered consecutively from 0. If an item is removed, other items will be renumbered.
The following code fragment shows a safe way to remove all items from a layout:
QLayoutItem *child;
while ((child = layout->takeAt(0)) != 0) {
    ...
    delete child;
}
See also
itemAt(), count()
Implemented in QMainWindowLayout, QDockWidgetLayout, QFormLayout, QGridLayout, QBoxLayout, QStackedLayout, and QToolBarLayout.
Referenced by QGridLayout::addWidget(), removeWidgetRecursively(), and QMenuBarPrivate::updateCornerWidgetToolBar().
totalHeightForWidth()
int QLayout::totalHeightForWidth (int w) const
Also takes contentsMargins and menu bar into account.
Warning
This function is not part of the public interface.
Definition at line 823 of file qlayout.cpp.
Referenced by QWidgetPrivate::adjustedSize(), QWidget::heightForWidth(), and QMessageBoxPrivate::updateSize().
 {
     Q_D(const QLayout);
     int side=0, top=0;
     if (d->topLevel) {
         QWidget *parent = parentWidget();
         parent->ensurePolished();
         QWidgetPrivate *wd = parent->d_func();
         side += wd->leftmargin + wd->rightmargin;
         top += wd->topmargin + wd->bottommargin;
     }
     int h = heightForWidth(w - side) + top;
 #ifndef QT_NO_MENUBAR
     h += menuBarHeightForWidth(d->menubar, w);
 #endif
     return h;
 }
totalMaximumSize()
QSize QLayout::totalMaximumSize () const
Also takes contentsMargins and menu bar into account.
Warning
This function is not part of the public interface.
Definition at line 902 of file qlayout.cpp.
 {
     Q_D(const QLayout);
     int side=0, top=0;
     if (d->topLevel) {
         QWidget *pw = parentWidget();
         pw->ensurePolished();
         QWidgetPrivate *wd = pw->d_func();
         side += wd->leftmargin + wd->rightmargin;
         top += wd->topmargin + wd->bottommargin;
     }
     QSize s = maximumSize();
 #ifndef QT_NO_MENUBAR
     top += menuBarHeightForWidth(d->menubar, s.width());
 #endif
     if (d->topLevel)
         s = QSize(qMin(s.width() + side, QLAYOUTSIZE_MAX),
                    qMin(s.height() + top, QLAYOUTSIZE_MAX));
     return s;
 }
totalMinimumSize()
QSize QLayout::totalMinimumSize () const
Also takes contentsMargins and menu bar into account.
Warning
This function is not part of the public interface.
Definition at line 848 of file qlayout.cpp.
Referenced by QMessageBoxPrivate::layoutMinimumWidth(), QWizardHeader::setup(), and QMessageBoxPrivate::updateSize().
 {
     Q_D(const QLayout);
     int side=0, top=0;
     if (d->topLevel) {
         QWidget *pw = parentWidget();
         pw->ensurePolished();
         QWidgetPrivate *wd = pw->d_func();
         side += wd->leftmargin + wd->rightmargin;
         top += wd->topmargin + wd->bottommargin;
     }
     QSize s = minimumSize();
 #ifndef QT_NO_MENUBAR
     top += menuBarHeightForWidth(d->menubar, s.width() + side);
 #endif
     return s + QSize(side, top);
 }
totalSizeHint()
QSize QLayout::totalSizeHint () const
Also takes contentsMargins and menu bar into account.
Warning
This function is not part of the public interface.
Definition at line 874 of file qlayout.cpp.
 {
     Q_D(const QLayout);
     int side=0, top=0;
     if (d->topLevel) {
         QWidget *pw = parentWidget();
         pw->ensurePolished();
         QWidgetPrivate *wd = pw->d_func();
         side += wd->leftmargin + wd->rightmargin;
         top += wd->topmargin + wd->bottommargin;
     }
     QSize s = sizeHint();
     if (hasHeightForWidth())
         s.setHeight(heightForWidth(s.width() + side));
 #ifndef QT_NO_MENUBAR
     top += menuBarHeightForWidth(d->menubar, s.width());
 #endif
     return s + QSize(side, top);
 }
update()
void QLayout::update ()
Updates the layout for parentWidget().
You should generally not need to call this because it is automatically called at the most appropriate times.
See also
activate(), invalidate()
Definition at line 1225 of file qlayout.cpp.
Referenced by QMainWindowPrivate::adjustCursor(), and QX11EmbedWidget::resizeEvent().
 {
     QLayout *layout = this;
     while (layout && layout->d_func()->activated) {
         layout->d_func()->activated = false;
         if (layout->d_func()->topLevel) {
             Q_ASSERT(layout->parent()->isWidgetType());
             QWidget *mw = static_cast<QWidget*>(layout->parent());
             QApplication::postEvent(mw, new QEvent(QEvent::LayoutRequest));
             break;
         }
         layout = static_cast<QLayout*>(layout->parent());
     }
 }
widgetEvent()
void QLayout::widgetEvent (QEvent * e) protected
Performs child widget layout when the parent widget is resized.
Warning
This function is not part of the public interface. Also handles removal of widgets. e is the event
Definition at line 726 of file qlayout.cpp.
 {
     Q_D(QLayout);
     if (!d->enabled)
         return;
     switch (e->type()) {
     case QEvent::Resize:
         if (d->activated) {
             QResizeEvent *r = (QResizeEvent *)e;
             d->doResize(r->size());
         } else {
             activate();
         }
         break;
     case QEvent::ChildRemoved:
         {
             QChildEvent *c = (QChildEvent *)e;
             if (c->child()->isWidgetType()) {
                 QWidget *w = (QWidget *)c->child();
 #ifndef QT_NO_MENUBAR
                 if (w == d->menubar)
                     d->menubar = 0;
 #endif
                 removeWidgetRecursively(this, w);
             }
         }
         break;
 #ifdef QT3_SUPPORT
     case QEvent::ChildInserted:
         if (d->topLevel && d->autoNewChild) {
             QChildEvent *c = (QChildEvent *)e;
             if (c->child()->isWidgetType()) {
                 QWidget *w = (QWidget *)c->child();
                 if (!w->isWindow()) {
 #if !defined(QT_NO_MENUBAR) && !defined(QT_NO_TOOLBAR)
                     if (qobject_cast<QMenuBar*>(w) && !qobject_cast<QToolBar*>(w->parentWidget())) {
                         d->menubar = (QMenuBar *)w;
                         invalidate();
                     } else
 #endif
 #ifndef QT_NO_SIZEGRIP
                     if (qobject_cast<QSizeGrip*>(w) ) {
                         //SizeGrip is handled by the dialog itself.
                     } else
 #endif
                         addItem(QLayoutPrivate::createWidgetItem(this, w));
                 }
             }
         }
         break;
     case QEvent::LayoutHint:
         d->activated = false;
         // fall through
 #endif
     case QEvent::LayoutRequest:
         if (static_cast<QWidget *>(parent())->isVisible())
             activate();
         break;
     default:
         break;
     }
 }
Friends and Related Functions
QApplicationPrivate
friend class QApplicationPrivate friend
Definition at line 206 of file qlayout.h.
QWidget
friend class QWidget friend
Definition at line 207 of file qlayout.h.
Properties
margin
int QLayout::margin private
the width of the outside border of the layout
Use setContentsMargins() and getContentsMargins() instead.
See also
contentsRect(), spacing
Definition at line 96 of file qlayout.h.
Referenced by QCommonStyle::subElementRect().
sizeConstraint
QLayout::SizeConstraint QLayout::sizeConstraint private
the resize mode of the layout
The default mode is QLayout::SetDefaultConstraint {SetDefaultConstraint}.
Definition at line 98 of file qlayout.h.
spacing
int QLayout::spacing private
the spacing between widgets inside the layout
If no value is explicitly set, the layout's spacing is inherited from the parent layout, or from the style settings for the parent widget.
For QGridLayout and QFormLayout, it is possible to set different horizontal and vertical spacings using QGridLayout::setHorizontalSpacing() and QGridLayout::setVerticalSpacing(). In that case, spacing() returns -1.
See also
contentsRect(), getContentsMargins(), QStyle::layoutSpacing(), QStyle::pixelMetric()
Definition at line 97 of file qlayout.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qlayout.h
/src/gui/kernel/qlayout.cpp
/src/gui/kernel/qlayoutitem.cpp