Qt 4.8: QEglContext Class Reference
QEglContext Class Reference
#include <qeglcontext_p.h>
Public Functions
QEgl::API api () const
bool chooseConfig (const QEglProperties &properties, QEgl::PixelFormatMatch match=QEgl::ExactPixelFormat)
EGLConfig config () const
int configAttrib (int name) const
EGLContext context () const
bool createContext (QEglContext *shareContext=0, const QEglProperties *properties=0)
EGLSurface createSurface (QPaintDevice *device, const QEglProperties *properties=0)
void destroyContext ()
void destroySurface (EGLSurface surface)
EGLDisplay display ()
bool doneCurrent ()
bool isCurrent () const
bool isSharing () const
bool isValid () const
bool lazyDoneCurrent ()
bool makeCurrent (EGLSurface surface)
QEglContext ()
void setApi (QEgl::API api)
void setConfig (EGLConfig config)
void setContext (EGLContext context)
bool swapBuffers (EGLSurface surface)
bool swapBuffersRegion2NOK (EGLSurface surface, const QRegion *region)
~QEglContext ()
Static Private Functions
static QEglContext * currentContext (QEgl::API api)
static void setCurrentContext (QEgl::API api, QEglContext *context)
Properties
bool apiChanged
QEgl::API apiType
EGLConfig cfg
EGLContext ctx
bool current
EGLSurface currentSurface
bool ownsContext
bool sharing
Friends
class QMeeGoGraphicsSystem
class QMeeGoPixmapData
Detailed Description
Definition at line 64 of file qeglcontext_p.h.
Constructors and Destructors
QEglContext()
QEglContext::QEglContext ()
Definition at line 92 of file qegl.cpp.
     : apiType(QEgl::OpenGL)
     , ctx(EGL_NO_CONTEXT)
     , cfg(QEGL_NO_CONFIG)
     , currentSurface(EGL_NO_SURFACE)
     , current(false)
     , ownsContext(true)
     , sharing(false)
     , apiChanged(false)
 {
     QEglContextTracker::ref();
 }
~QEglContext()
QEglContext::~QEglContext ()
Definition at line 105 of file qegl.cpp.
 {
     destroyContext();
     if (currentGLContext == this)
         currentGLContext = 0;
     if (currentVGContext == this)
         currentVGContext = 0;
     QEglContextTracker::deref();
 }
Functions
api()
QEgl::API QEglContext::api () const inline
Definition at line 74 of file qeglcontext_p.h.
 { return apiType; }
chooseConfig()
bool QEglContext::chooseConfig (const QEglProperties & properties, QEgl::PixelFormatMatch match = QEgl::ExactPixelFormat)
Definition at line 348 of file qegl.cpp.
Referenced by createContext(), and QEgl::defaultConfig().
 {
     cfg = QEgl::chooseConfig(&properties, match);
     return cfg != QEGL_NO_CONFIG;
 }
config()
EGLConfig QEglContext::config () const inline
Definition at line 96 of file qeglcontext_p.h.
Referenced by QGLPixelBufferPrivate::init(), qt_egl_create_surface(), qt_vg_shared_surface(), and QVGEGLWindowSurfacePrivate::windowSurfaceSize().
 { return cfg; }
configAttrib()
int QEglContext::configAttrib (int name) const
Definition at line 568 of file qegl.cpp.
Referenced by qt_vg_config_to_image_format(), and qt_vg_unregister_pixmap().
 {
     EGLint value;
     EGLBoolean success = eglGetConfigAttrib(QEgl::display(), cfg, name, &value);
     if (success)
         return value;
     else
         return EGL_DONT_CARE;
 }
context()
EGLContext QEglContext::context () const inline
Definition at line 91 of file qeglcontext_p.h.
Referenced by QVGEGLWindowSurfaceDirect::ensureContext(), and setCurrentContext().
 { return ctx; }
createContext()
bool QEglContext::createContext (QEglContext * shareContext = 0, const QEglProperties * properties = 0)
Definition at line 361 of file qegl.cpp.
Referenced by createContext(), and QX11GLSharedContexts::QX11GLSharedContexts().
 {
     // We need to select the correct API before calling eglCreateContext().
 #ifdef QT_OPENGL_ES
 #ifdef EGL_OPENGL_ES_API
     if (apiType == QEgl::OpenGL)
         eglBindAPI(EGL_OPENGL_ES_API);
 #endif
 #else
 #ifdef EGL_OPENGL_API
     if (apiType == QEgl::OpenGL)
         eglBindAPI(EGL_OPENGL_API);
 #endif
 #endif //defined(QT_OPENGL_ES)
 #ifdef EGL_OPENVG_API
     if (apiType == QEgl::OpenVG)
         eglBindAPI(EGL_OPENVG_API);
 #endif
     // Create a new context for the configuration.
     QEglProperties contextProps;
     if (properties)
         contextProps = *properties;
 #ifdef QT_OPENGL_ES_2
     if (apiType == QEgl::OpenGL)
         contextProps.setValue(EGL_CONTEXT_CLIENT_VERSION, 2);
 #endif
     sharing = false;
     if (shareContext && shareContext->ctx == EGL_NO_CONTEXT)
         shareContext = 0;
     if (shareContext) {
         ctx = eglCreateContext(QEgl::display(), cfg, shareContext->ctx, contextProps.properties());
         if (ctx == EGL_NO_CONTEXT) {
             qWarning() << "QEglContext::createContext(): Could not share context:" << QEgl::errorString();
             shareContext = 0;
         } else {
             sharing = true;
         }
     }
     if (ctx == EGL_NO_CONTEXT) {
         ctx = eglCreateContext(display(), cfg, EGL_NO_CONTEXT, contextProps.properties());
         if (ctx == EGL_NO_CONTEXT) {
             qWarning() << "QEglContext::createContext(): Unable to create EGL context:" << QEgl::errorString();
 #ifdef Q_OS_SYMBIAN
             S60->eglSurfaceCreationError = true;
 #endif
             return false;
         }
     }
     return true;
 }
createSurface()
EGLSurface QEglContext::createSurface (QPaintDevice * device, const QEglProperties * properties = 0)
Definition at line 354 of file qegl.cpp.
Referenced by QVGEGLWindowSurfaceDirect::ensureContext().
 {
     return QEgl::createSurface(device, cfg, properties);
 }
currentContext()
QEglContext * QEglContext::currentContext (QEgl::API api) static private
Definition at line 799 of file qegl.cpp.
Referenced by QMeeGoPixmapData::imageToEGLSharedImage(), makeCurrent(), and QMeeGoGraphicsSystem::setSurfaceScaling().
 {
     if (api == QEgl::OpenGL)
         return currentGLContext;
     else
         return currentVGContext;
 }
destroyContext()
void QEglContext::destroyContext ()
Definition at line 425 of file qegl.cpp.
Referenced by ~QEglContext().
 {
     if (ctx != EGL_NO_CONTEXT && ownsContext)
         eglDestroyContext(display(), ctx);
     ctx = EGL_NO_CONTEXT;
     cfg = 0;
 }
destroySurface()
void QEglContext::destroySurface (EGLSurface surface)
Definition at line 415 of file qegl.cpp.
Referenced by QVGEGLWindowSurfaceDirect::ensureContext(), QVGEGLWindowSurfacePrivate::windowSurfaceSize(), QVGEGLWindowSurfaceDirect::~QVGEGLWindowSurfaceDirect(), and QVGSharedContext::~QVGSharedContext().
 {
     if (surface != EGL_NO_SURFACE) {
         if (surface == currentSurface)
             doneCurrent();
         eglDestroySurface(display(), surface);
     }
 }
display()
EGLDisplay QEglContext::display () inline
Definition at line 94 of file qeglcontext_p.h.
Referenced by QEgl::chooseConfig(), createContext(), QEgl::defaultConfig(), destroyContext(), destroySurface(), QEgl::dumpAllConfigs(), and qt_egl_create_surface().
 {return QEgl::display();}
doneCurrent()
bool QEglContext::doneCurrent ()
Definition at line 485 of file qegl.cpp.
Referenced by destroySurface(), QVGEGLWindowSurfaceDirect::ensureContext(), qt_vg_destroy_shared_context(), QX11GLSharedContexts::QX11GLSharedContexts(), QVGEGLWindowSurfacePrivate::windowSurfaceSize(), and QVGSharedContext::~QVGSharedContext().
 {
     // If the context is invalid, we assume that an error was reported
     // when makeCurrent() was called.
     if (ctx == EGL_NO_CONTEXT)
         return false;
     current = false;
     currentSurface = EGL_NO_SURFACE;
     setCurrentContext(apiType, 0);
     // We need to select the correct API before calling eglMakeCurrent()
     // with EGL_NO_CONTEXT because threads can have both OpenGL and OpenVG
     // contexts active at the same time.
 #ifdef EGL_OPENGL_ES_API
     if (apiType == QEgl::OpenGL)
         eglBindAPI(EGL_OPENGL_ES_API);
 #endif
 #ifdef EGL_OPENVG_API
     if (apiType == QEgl::OpenVG)
         eglBindAPI(EGL_OPENVG_API);
 #endif
     bool ok = eglMakeCurrent(QEgl::display(), EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
     if (!ok)
         qWarning() << "QEglContext::doneCurrent():" << QEgl::errorString();
     return ok;
 }
isCurrent()
bool QEglContext::isCurrent () const
Definition at line 121 of file qegl.cpp.
Referenced by QVGPixmapData::destroyImageAndContext().
 {
     return current;
 }
isSharing()
bool QEglContext::isSharing () const inline
Definition at line 72 of file qeglcontext_p.h.
 { return sharing; }
isValid()
bool QEglContext::isValid () const
Definition at line 116 of file qegl.cpp.
Referenced by QX11GLSharedContexts::QX11GLSharedContexts().
 {
     return (ctx != EGL_NO_CONTEXT);
 }
lazyDoneCurrent()
bool QEglContext::lazyDoneCurrent ()
Definition at line 519 of file qegl.cpp.
Referenced by QVGPixmapData::destroyImageAndContext(), QVGEGLWindowSurfaceDirect::endPaint(), qt_vg_hibernate_pixmaps(), QVGEGLWindowSurfaceDirect::scroll(), and QVGEGLWindowSurfacePrivate::windowSurfaceSize().
 {
     current = false;
     return true;
 }
makeCurrent()
bool QEglContext::makeCurrent (EGLSurface surface)
Definition at line 433 of file qegl.cpp.
Referenced by QVGEGLWindowSurfaceDirect::beginPaint(), QVGPixmapData::destroyImageAndContext(), QVGEGLWindowSurfaceDirect::endPaint(), qt_vg_destroy_shared_context(), qt_vg_hibernate_pixmaps(), QX11GLSharedContexts::QX11GLSharedContexts(), QVGEGLWindowSurfaceDirect::scroll(), QVGEGLWindowSurfacePrivate::windowSurfaceSize(), and QVGSharedContext::~QVGSharedContext().
 {
     if (ctx == EGL_NO_CONTEXT) {
         qWarning() << "QEglContext::makeCurrent(): Cannot make invalid context current";
         return false;
     }
     if (surface == EGL_NO_SURFACE) {
         qWarning() << "QEglContext::makeCurrent(): Cannot make invalid surface current";
         return false;
     }
 #ifdef Q_OS_SYMBIAN
     apiChanged = false;
     if (currentContext(apiType)
             && currentContext(apiType)->ctx != eglGetCurrentContext()) {
         // some other EGL based API active. Complete its rendering
         eglWaitClient();
         apiChanged = true;
     }
 #endif
     // If lazyDoneCurrent() was called on the surface, then we may be able
     // to assume that it is still current within the thread.
     if (surface == currentSurface && currentContext(apiType) == this
             && !apiChanged) {
         current = true;
         return true;
     }
     current = true;
     currentSurface = surface;
     setCurrentContext(apiType, this);
     // Force the right API to be bound before making the context current.
     // The EGL implementation should be able to figure this out from ctx,
     // but some systems require the API to be explicitly set anyway.
 #ifdef EGL_OPENGL_ES_API
     if (apiType == QEgl::OpenGL)
         eglBindAPI(EGL_OPENGL_ES_API);
 #endif
 #ifdef EGL_OPENVG_API
     if (apiType == QEgl::OpenVG)
         eglBindAPI(EGL_OPENVG_API);
 #endif
     bool ok = eglMakeCurrent(QEgl::display(), surface, surface, ctx);
     if (!ok)
         qWarning() << "QEglContext::makeCurrent(" << surface << "):" << QEgl::errorString();
     return ok;
 }
setApi()
void QEglContext::setApi (QEgl::API api) inline
Definition at line 75 of file qeglcontext_p.h.
Referenced by createContext().
 { apiType = api; }
setConfig()
void QEglContext::setConfig (EGLConfig config) inline
Definition at line 97 of file qeglcontext_p.h.
Referenced by createContext(), and QX11GLSharedContexts::QX11GLSharedContexts().
 { cfg = config; }
setContext()
void QEglContext::setContext (EGLContext context) inline
Definition at line 92 of file qeglcontext_p.h.
 { ctx = context; ownsContext = false;}
setCurrentContext()
void QEglContext::setCurrentContext (QEgl::API api, QEglContext * context) static private
Definition at line 807 of file qegl.cpp.
Referenced by doneCurrent(), and makeCurrent().
 {
     if (api == QEgl::OpenGL)
         currentGLContext = context;
     else
         currentVGContext = context;
 }
swapBuffers()
bool QEglContext::swapBuffers (EGLSurface surface)
Definition at line 525 of file qegl.cpp.
Referenced by QVGEGLWindowSurfaceDirect::endPaint().
 {
     if(ctx == EGL_NO_CONTEXT)
         return false;
     bool ok = eglSwapBuffers(QEgl::display(), surface);
     if (!ok)
         qWarning() << "QEglContext::swapBuffers():" << QEgl::errorString();
 #ifdef Q_OS_SYMBIAN
     if (apiChanged) {
         eglWaitClient();
         apiChanged = false;
     }
 #endif
     return ok;
 }
swapBuffersRegion2NOK()
bool QEglContext::swapBuffersRegion2NOK (EGLSurface surface, const QRegion * region)
Definition at line 543 of file qegl.cpp.
{
     QVector<QRect> qrects = region->rects();
     EGLint *gl_rects;
     uint count;
     uint i;
     count = qrects.size();
     QVarLengthArray <EGLint> arr(4 * count);
     gl_rects = arr.data();
     for (i = 0; i < count; i++) {
       QRect qrect = qrects[i];
       gl_rects[4 * i + 0] = qrect.x();
       gl_rects[4 * i + 1] = qrect.y();
       gl_rects[4 * i + 2] = qrect.width();
       gl_rects[4 * i + 3] = qrect.height();
     }
     bool ok = QEgl::eglSwapBuffersRegion2NOK(QEgl::display(), surface, count, gl_rects);
     if (!ok)
         qWarning() << "QEglContext::swapBuffersRegion2NOK():" << QEgl::errorString();
     return ok;
 }
Friends and Related Functions
QMeeGoGraphicsSystem
friend class QMeeGoGraphicsSystem friend
Definition at line 112 of file qeglcontext_p.h.
QMeeGoPixmapData
friend class QMeeGoPixmapData friend
Definition at line 113 of file qeglcontext_p.h.
Properties
apiChanged
bool QEglContext::apiChanged private
Definition at line 107 of file qeglcontext_p.h.
Referenced by makeCurrent(), and swapBuffers().
apiType
QEgl::API QEglContext::apiType private
Definition at line 100 of file qeglcontext_p.h.
Referenced by createContext(), doneCurrent(), and makeCurrent().
cfg
EGLConfig QEglContext::cfg private
Definition at line 102 of file qeglcontext_p.h.
Referenced by chooseConfig(), QEgl::chooseConfig(), configAttrib(), createContext(), createSurface(), destroyContext(), and QEgl::eglSwapBuffersRegion2NOK().
ctx
EGLContext QEglContext::ctx private
Definition at line 101 of file qeglcontext_p.h.
Referenced by createContext(), destroyContext(), doneCurrent(), isValid(), makeCurrent(), and swapBuffers().
current
bool QEglContext::current private
Definition at line 104 of file qeglcontext_p.h.
Referenced by doneCurrent(), isCurrent(), lazyDoneCurrent(), and makeCurrent().
currentSurface
EGLSurface QEglContext::currentSurface private
Definition at line 103 of file qeglcontext_p.h.
Referenced by destroySurface(), doneCurrent(), and makeCurrent().
ownsContext
bool QEglContext::ownsContext private
Definition at line 105 of file qeglcontext_p.h.
Referenced by destroyContext().
sharing
bool QEglContext::sharing private
Definition at line 106 of file qeglcontext_p.h.
Referenced by createContext().
The documentation for this class was generated from the following files:
/src/gui/egl/qeglcontext_p.h
/src/gui/egl/qegl.cpp
/src/gui/egl/qegl_stub.cpp