Qt 4.8: QPatternist::Template Class Reference
QPatternist::Template Class Reference
Contains data related to a template.
#include <qtemplate_p.h>
Public Types
typedef QExplicitlySharedDataPointer< Template > Ptr
typedef QVector< Template::Ptr > Vector
Public Functions
virtual const SourceLocationReflection * actualReflection () const
void compileParameters (const StaticContext::Ptr &context)
DynamicContext::Ptr createContext (const TemplateInvoker *const invoker, const DynamicContext::Ptr &context, const bool isCallTemplate) const
Expression::Properties dependencies () const
Expression::Properties properties () const
Template (const ImportPrecedence ip, const SequenceType::Ptr &reqType)
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QString description () const
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Static Public Functions
static void raiseXTSE0680 (const ReportContext::Ptr &context, const QXmlName &name, const SourceLocationReflection *const reflection)
Public Variables
Expression::Ptr body
const ImportPrecedence importPrecedence
VariableDeclaration::List templateParameters
Public Variables inherited from QSharedData
QAtomicInt ref
Private Functions
DynamicContext::TemplateParameterHash parametersAsHash () const
Properties
const SequenceType::Ptr m_reqType
Detailed Description
Contains data related to a template.
A Template is associated with a mode, by being housed inside a TemplateMode instance.
Template has role very similar to UserFunction.
See also
TemplateMode
TemplatePattern
UserFunction
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Since
4.5
Definition at line 84 of file qtemplate_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<Template> QPatternist::Template::Ptr
Definition at line 89 of file qtemplate_p.h.
Vector
typedef QVector<Template::Ptr> QPatternist::Template::Vector
Definition at line 90 of file qtemplate_p.h.
Constructors and Destructors
Template()
QPatternist::Template::Template (const ImportPrecedence ip, const SequenceType::Ptr & reqType) inline
Definition at line 92 of file qtemplate_p.h.
                                                         : importPrecedence(ip)
                                                           , m_reqType(reqType)
         {
         }
Functions
actualReflection()
const SourceLocationReflection * Template::actualReflection () const virtual
Returns this.
Implements QPatternist::SourceLocationReflection.
Definition at line 51 of file qtemplate.cpp.
 {
     return this;
 }
compileParameters()
void Template::compileParameters (const StaticContext::Ptr & context)
Since we have our template parameters in templateParameters, we need this separate step to do the regular phases: Expression::typeCheck(), and Expression::compress().
Definition at line 172 of file qtemplate.cpp.
 {
     Q_ASSERT(context);
     const int len = templateParameters.count();
     for(int i = 0; i < len; ++i)
     {
         const VariableDeclaration::Ptr &at = templateParameters.at(i);
         /* If our value is required, we don't have a default value. */
         if(at->expression())
         {
             // TODO why do we pass in its own type here?
             at->setExpression(at->expression()->typeCheck(context, at->expression()->staticType()));
             at->setExpression(at->expression()->compress(context));
         }
     }
 }
createContext()
DynamicContext::Ptr Template::createContext (const TemplateInvoker *const invoker, const DynamicContext::Ptr & context, const bool isCallTemplate) const
If isCallTemplate, the caller is xsl:call-template, as opposed to for instance xsl:apply-templates. This affects error reporting.
Parameters or not, we must in any case create a new stack frame for the template invocation since otherwise we will trash our existing variables. Hence it's as with calling user functions.
This is especially reproducible with recursive functions.
Definition at line 81 of file qtemplate.cpp.
Referenced by QPatternist::CallTemplate::evaluateEBV(), QPatternist::CallTemplate::evaluateSequence(), QPatternist::ApplyTemplate::evaluateSequence(), and QPatternist::CallTemplate::evaluateToSequenceReceiver().
 {
     Q_ASSERT(invoker);
     Q_ASSERT(context);
     /* We have:
      * - xsl:params in the target template (if any) which may provide
      *   default values.
      * - xsl:with-params in the caller (if any) which provides values.
      *
      * We need to, for each parameter:
      * - If the called template provides no default value and the caller
      *   has no value, it's an error
      * - If the called template has a default value and the caller provides
      *   none, it should be used
      * - In any case the caller provides a value, it needs to be used.
      *
      * Problems to look out for:
      *
      * - Each xsl:param is in scope for the subsequent xsl:params. Hence,
      *   the evaluation of one xsl:param can depend on another xsl:param,
      *   and so on
      * - The focus for xsl:params is different from the focus for
      *   the xsl:with-params
      * - The xsl:with-params are not in scope for the xsl:params.
      */
     WithParam::Hash withParams(invoker->withParams());
     DynamicContext::Ptr newStack(context->createStack());
     /* We have no parameters, and we have no further error checking to
      * do in the case of not being xsl:apply-templates, so we need to do nothing. */
     if(templateParameters.isEmpty() && (!isCallTemplate || withParams.isEmpty()))
         return newStack;
     const DynamicContext::TemplateParameterHash hashedParams(parametersAsHash());
     DynamicContext::TemplateParameterHash sewnTogether(hashedParams);
     const DynamicContext::TemplateParameterHash::iterator end(sewnTogether.end());
     for(DynamicContext::TemplateParameterHash::iterator it(sewnTogether.begin());
         it != end;
         ++it)
     {
         Expression::Ptr &param = it.value();
         WithParam::Ptr &withParam = withParams[it.key()];
         if(withParam)
             param = Expression::Ptr(new DynamicContextStore(withParam->sourceExpression(), context));
         else if(!param)
         {
             /* Ops, no xsl:with-param and no default value to cover up for it.
              */
             context->error(QtXmlPatterns::tr("The parameter %1 is required, but no corresponding %2 is supplied.")
                                              .arg(formatKeyword(context->namePool(), it.key()),
                                                   formatKeyword(QLatin1String("xsl:with-param"))),
                            ReportContext::XTSE0690,
                            this);
         }
     }
     if(isCallTemplate)
     {
         /* Find xsl:with-param that has no corresponding xsl:param. */
         /* Optimization: candidate for threading? */
         const WithParam::Hash::const_iterator end(withParams.constEnd());
         for(WithParam::Hash::const_iterator it(withParams.constBegin()); it != end; ++it)
         {
             if(!hashedParams.contains(it.key()))
                 raiseXTSE0680(context, it.key(), this);
         }
     }
     newStack->templateParameterStore() = sewnTogether;
     return newStack;
 }
dependencies()
Expression::Properties Template::dependencies () const
Definition at line 213 of file qtemplate.cpp.
Referenced by QPatternist::CallTemplate::dependencies().
 {
     return Expression::DisableElimination; /* We're having issues with recursion detection, so this path currently loops infintely. */
     Expression::Properties collect(body->dependencies());
     VariableDeclaration::List::const_iterator end(templateParameters.constEnd());
     for(VariableDeclaration::List::const_iterator it(templateParameters.constBegin());
         it != end;
         ++it)
     {
         if((*it)->expression())
             collect |= (*it)->expression()->dependencies();
     }
     return collect & (Expression::RequiresFocus | Expression::IsEvaluated | Expression::DisableElimination);
 }
parametersAsHash()
DynamicContext::TemplateParameterHash Template::parametersAsHash () const private
Definition at line 56 of file qtemplate.cpp.
Referenced by createContext().
 {
     DynamicContext::TemplateParameterHash retval;
     const int len = templateParameters.count();
     for(int i = 0; i < len; ++i)
     {
         const VariableDeclaration::Ptr &at = templateParameters.at(i);
         retval.insert(at->name, at->expression());
     }
     return retval;
 }
properties()
Expression::Properties Template::properties () const
A value which takes into account the body and its template parameters.
Definition at line 193 of file qtemplate.cpp.
Referenced by QPatternist::CallTemplate::properties().
 {
     return Expression::DisableElimination; /* We're having issues with recursion detection, so this path currently loops infintely. */
     Expression::Properties collect(body->properties());
     VariableDeclaration::List::const_iterator end(templateParameters.constEnd());
     for(VariableDeclaration::List::const_iterator it(templateParameters.constBegin());
         it != end;
         ++it)
     {
         if((*it)->expression())
             collect |= (*it)->expression()->properties();
     }
     // TODO simplify.
     return collect & (Expression::RequiresFocus | Expression::IsEvaluated | Expression::DisableElimination);
 }
raiseXTSE0680()
void Template::raiseXTSE0680 (const ReportContext::Ptr & context, const QXmlName & name, const SourceLocationReflection *const reflection) static
Definition at line 70 of file qtemplate.cpp.
Referenced by createContext(), and QPatternist::CallTemplate::typeCheck().
 {
     context->error(QtXmlPatterns::tr("The parameter %1 is passed, but no corresponding %2 exists.")
                                      .arg(formatKeyword(context->namePool(), name),
                                           formatKeyword(QLatin1String("xsl:param"))),
                    ReportContext::XTSE0680,
                    reflection);
 }
Properties
body
Expression::Ptr QPatternist::Template::body
Definition at line 98 of file qtemplate_p.h.
Referenced by QPatternist::CallTemplate::body(), dependencies(), QPatternist::CallTemplate::evaluateEBV(), QPatternist::CallTemplate::evaluateSequence(), QPatternist::ApplyTemplate::evaluateSequence(), QPatternist::CallTemplate::evaluateToSequenceReceiver(), QPatternist::CallTemplate::properties(), and properties().
importPrecedence
const ImportPrecedence QPatternist::Template::importPrecedence
Definition at line 105 of file qtemplate_p.h.
Referenced by QPatternist::ApplyTemplate::findTemplate().
m_reqType
const SequenceType::Ptr QPatternist::Template::m_reqType private
Definition at line 139 of file qtemplate_p.h.
templateParameters
VariableDeclaration::List QPatternist::Template::templateParameters
Definition at line 107 of file qtemplate_p.h.
Referenced by compileParameters(), createContext(), dependencies(), parametersAsHash(), properties(), and QPatternist::CallTemplate::typeCheck().
The documentation for this class was generated from the following files:
/src/xmlpatterns/expr/qtemplate_p.h
/src/xmlpatterns/expr/qtemplate.cpp