Qt 4.8: QDeclarativeDirParser Class Reference
QDeclarativeDirParser Class Reference
#include <qdeclarativedirparser_p.h>
Classes
struct Component
struct Plugin
Public Functions
QList< Component > components () const
QList< QDeclarativeError > errors (const QString &uri) const
QString fileSource () const
bool hasError () const
bool isParsed () const
bool parse ()
QList< Plugin > plugins () const
QDeclarativeDirParser ()
void setFileSource (const QString &filePath)
void setSource (const QString &source)
void setUrl (const QUrl &url)
QString source () const
QUrl url () const
~QDeclarativeDirParser ()
Private Functions
void reportError (int line, int column, const QString &message)
Properties
QList< Component > _components
QList< QDeclarativeError > _errors
QString _filePathSouce
unsigned _isParsed: 1
QList< Plugin > _plugins
QString _source
QUrl _url
Detailed Description
Definition at line 62 of file qdeclarativedirparser_p.h.
Constructors and Destructors
QDeclarativeDirParser()
QDeclarativeDirParser::QDeclarativeDirParser ()
Definition at line 52 of file qdeclarativedirparser.cpp.
     : _isParsed(false)
 {
 }
~QDeclarativeDirParser()
QDeclarativeDirParser::~QDeclarativeDirParser ()
Definition at line 57 of file qdeclarativedirparser.cpp.
 {
 }
Functions
components()
QList< QDeclarativeDirParser::Component > QDeclarativeDirParser::components () const
Definition at line 273 of file qdeclarativedirparser.cpp.
Referenced by QDeclarativeQmldirData::dataReceived(), and QDeclarativeImportsPrivate::importExtension().
 {
     return _components;
 }
errors()
QList< QDeclarativeError > QDeclarativeDirParser::errors (const QString & uri) const
Definition at line 256 of file qdeclarativedirparser.cpp.
Referenced by QDeclarativeImportsPrivate::importExtension().
 {
     QList<QDeclarativeError> errors = _errors;
     for (int i = 0; i < errors.size(); ++i) {
         QDeclarativeError &e = errors[i];
         QString description = e.description();
         description.replace(QLatin1String("$$URI$$"), uri);
         e.setDescription(description);
     }
     return errors;
 }
fileSource()
QString QDeclarativeDirParser::fileSource () const
Definition at line 71 of file qdeclarativedirparser.cpp.
 {
     return _filePathSouce;
 }
hasError()
bool QDeclarativeDirParser::hasError () const
Definition at line 248 of file qdeclarativedirparser.cpp.
Referenced by QDeclarativeImportsPrivate::importExtension(), and parse().
 {
     if (! _errors.isEmpty())
         return true;
     return false;
 }
isParsed()
bool QDeclarativeDirParser::isParsed () const
Definition at line 92 of file qdeclarativedirparser.cpp.
 {
     return _isParsed;
 }
parse()
bool QDeclarativeDirParser::parse ()
Definition at line 97 of file qdeclarativedirparser.cpp.
Referenced by QDeclarativeQmldirData::dataReceived(), and QDeclarativeTypeLoader::qmlDirParser().
 {
     if (_isParsed)
         return true;
     _isParsed = true;
     _errors.clear();
     _plugins.clear();
     _components.clear();
     if (_source.isEmpty() && !_filePathSouce.isEmpty()) {
         QFile file(_filePathSouce);
         if (!QDeclarative_isFileCaseCorrect(_filePathSouce)) {
             QDeclarativeError error;
             error.setDescription(QString::fromUtf8("cannot load module \"$$URI$$\": File name case mismatch for \"%1\"").arg(_filePathSouce));
             _errors.prepend(error);
             return false;
         } else if (file.open(QFile::ReadOnly)) {
             _source = QString::fromUtf8(file.readAll());
         } else {
             QDeclarativeError error;
             error.setDescription(QString::fromUtf8("module \"$$URI$$\" definition \"%1\" not readable").arg(_filePathSouce));
             _errors.prepend(error);
             return false;
         }
     }
     QTextStream stream(&_source);
     int lineNumber = 0;
     forever {
         ++lineNumber;
         const QString line = stream.readLine();
         if (line.isNull())
             break;
         QString sections[3];
         int sectionCount = 0;
         int index = 0;
         const int length = line.length();
         while (index != length) {
             const QChar ch = line.at(index);
             if (ch.isSpace()) {
                 do { ++index; }
                 while (index != length && line.at(index).isSpace());
             } else if (ch == QLatin1Char('#')) {
                 // recognized a comment
                 break;
             } else {
                 const int start = index;
                 do { ++index; }
                 while (index != length && !line.at(index).isSpace());
                 const QString lexeme = line.mid(start, index - start);
                 if (sectionCount >= 3) {
                     reportError(lineNumber, start, QLatin1String("unexpected token"));
                 } else {
                     sections[sectionCount++] = lexeme;
                 }
             }
         }
         if (sectionCount == 0) {
             continue; // no sections, no party.
         } else if (sections[0] == QLatin1String("plugin")) {
             if (sectionCount < 2) {
                 reportError(lineNumber, -1,
                             QString::fromUtf8("plugin directive requires 2 arguments, but %1 were provided").arg(sectionCount + 1));
                 continue;
             }
             const Plugin entry(sections[1], sections[2]);
             _plugins.append(entry);
         } else if (sections[0] == QLatin1String("internal")) {
             if (sectionCount != 3) {
                 reportError(lineNumber, -1,
                             QString::fromUtf8("internal types require 2 arguments, but %1 were provided").arg(sectionCount + 1));
                 continue;
             }
             Component entry(sections[1], sections[2], -1, -1);
             entry.internal = true;
             _components.append(entry);
         } else if (sections[0] == QLatin1String("typeinfo")) {
             if (sectionCount != 2) {
                 reportError(lineNumber, -1,
                             QString::fromUtf8("typeinfo requires 1 argument, but %1 were provided").arg(sectionCount - 1));
                 continue;
             }
 #ifdef QT_CREATOR
             TypeInfo typeInfo(sections[1]);
             _typeInfos.append(typeInfo);
 #endif
         } else if (sectionCount == 2) {
             // No version specified (should only be used for relative qmldir files)
             const Component entry(sections[0], sections[1], -1, -1);
             _components.append(entry);
         } else if (sectionCount == 3) {
             const QString &version = sections[1];
             const int dotIndex = version.indexOf(QLatin1Char('.'));
             if (dotIndex == -1) {
                 reportError(lineNumber, -1, QLatin1String("expected '.'"));
             } else if (version.indexOf(QLatin1Char('.'), dotIndex + 1) != -1) {
                 reportError(lineNumber, -1, QLatin1String("unexpected '.'"));
             } else {
                 bool validVersionNumber = false;
                 const int majorVersion = version.left(dotIndex).toInt(&validVersionNumber);
                 if (validVersionNumber) {
                     const int minorVersion = version.mid(dotIndex + 1).toInt(&validVersionNumber);
                     if (validVersionNumber) {
                         const Component entry(sections[0], sections[2], majorVersion, minorVersion);
                         _components.append(entry);
                     }
                 }
             }
         } else {
             reportError(lineNumber, -1,
                         QString::fromUtf8("a component declaration requires 3 arguments, but %1 were provided").arg(sectionCount + 1));
         }
     }
     return hasError();
 }
plugins()
QList< QDeclarativeDirParser::Plugin > QDeclarativeDirParser::plugins () const
Definition at line 268 of file qdeclarativedirparser.cpp.
Referenced by QDeclarativeImportsPrivate::importExtension().
 {
     return _plugins;
 }
reportError()
void QDeclarativeDirParser::reportError (int line, int column, const QString & message) private
Definition at line 238 of file qdeclarativedirparser.cpp.
Referenced by parse().
 {
     QDeclarativeError error;
     error.setUrl(_url);
     error.setLine(line);
     error.setColumn(column);
     error.setDescription(description);
     _errors.append(error);
 }
setFileSource()
void QDeclarativeDirParser::setFileSource (const QString & filePath)
Definition at line 76 of file qdeclarativedirparser.cpp.
Referenced by QDeclarativeTypeLoader::qmlDirParser().
 {
     _filePathSouce = filePath;
 }
setSource()
void QDeclarativeDirParser::setSource (const QString & source)
Definition at line 86 of file qdeclarativedirparser.cpp.
Referenced by QDeclarativeQmldirData::dataReceived().
 {
     _isParsed = false;
     _source = source;
 }
setUrl()
void QDeclarativeDirParser::setUrl (const QUrl & url)
Definition at line 66 of file qdeclarativedirparser.cpp.
Referenced by QDeclarativeTypeLoader::qmlDirParser().
 {
     _url = url;
 }
source()
QString QDeclarativeDirParser::source () const
Definition at line 81 of file qdeclarativedirparser.cpp.
Referenced by setSource().
 {
     return _source;
 }
url()
QUrl QDeclarativeDirParser::url () const
Definition at line 61 of file qdeclarativedirparser.cpp.
Referenced by setUrl().
 {
     return _url;
 }
Properties
_components
QList<Component> QDeclarativeDirParser::_components private
Definition at line 136 of file qdeclarativedirparser_p.h.
Referenced by components(), and parse().
_errors
QList<QDeclarativeError> QDeclarativeDirParser::_errors private
Definition at line 132 of file qdeclarativedirparser_p.h.
Referenced by errors(), hasError(), parse(), and reportError().
_filePathSouce
QString QDeclarativeDirParser::_filePathSouce private
Definition at line 135 of file qdeclarativedirparser_p.h.
Referenced by fileSource(), parse(), and setFileSource().
_isParsed
unsigned QDeclarativeDirParser::_isParsed private
Definition at line 141 of file qdeclarativedirparser_p.h.
Referenced by isParsed(), parse(), and setSource().
_plugins
QList<Plugin> QDeclarativeDirParser::_plugins private
Definition at line 137 of file qdeclarativedirparser_p.h.
Referenced by parse(), and plugins().
_source
QString QDeclarativeDirParser::_source private
Definition at line 134 of file qdeclarativedirparser_p.h.
Referenced by parse(), setSource(), and source().
_url
QUrl QDeclarativeDirParser::_url private
Definition at line 133 of file qdeclarativedirparser_p.h.
Referenced by reportError(), setUrl(), and url().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativedirparser_p.h
/src/declarative/qml/qdeclarativedirparser.cpp