Qt 4.8: QDeclarativeListAccessor Class Reference
QDeclarativeListAccessor Class Reference
#include <qdeclarativelistaccessor_p.h>
Public Types
enum Type {
Invalid, StringList, VariantList, ListProperty,
Instance, Integer
}
Public Functions
QVariant at (int) const
int count () const
bool isValid () const
QVariant list () const
QDeclarativeListAccessor ()
void setList (const QVariant &, QDeclarativeEngine *=0)
Type type () const
~QDeclarativeListAccessor ()
Properties
QVariant d
Type m_type
Detailed Description
Definition at line 54 of file qdeclarativelistaccessor_p.h.
Enumerations
Type
enum QDeclarativeListAccessor::Type
Enumerator
Invalid
StringList
VariantList
ListProperty
Instance
Integer
Definition at line 68 of file qdeclarativelistaccessor_p.h.
 { Invalid, StringList, VariantList, ListProperty, Instance, Integer };
Constructors and Destructors
QDeclarativeListAccessor()
QDeclarativeListAccessor::QDeclarativeListAccessor ()
Definition at line 54 of file qdeclarativelistaccessor.cpp.
 : m_type(Invalid)
 {
 }
~QDeclarativeListAccessor()
QDeclarativeListAccessor::~QDeclarativeListAccessor ()
Definition at line 59 of file qdeclarativelistaccessor.cpp.
 {
 }
Functions
at()
QVariant QDeclarativeListAccessor::at (int idx) const
Definition at line 113 of file qdeclarativelistaccessor.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::initialValue().
 {
     Q_ASSERT(idx >= 0 && idx < count());
     switch(m_type) {
     case StringList:
         return QVariant::fromValue(qvariant_cast<QStringList>(d).at(idx));
     case VariantList:
         return qvariant_cast<QVariantList>(d).at(idx);
     case ListProperty:
         return QVariant::fromValue(((QDeclarativeListReference *)d.constData())->at(idx));
     case Instance:
         return d;
     case Integer:
         return QVariant(idx);
     default:
     case Invalid:
         return QVariant();
     }
 }
count()
int QDeclarativeListAccessor::count () const
Definition at line 94 of file qdeclarativelistaccessor.cpp.
Referenced by at().
 {
     switch(m_type) {
     case StringList:
         return qvariant_cast<QStringList>(d).count();
     case VariantList:
         return qvariant_cast<QVariantList>(d).count();
     case ListProperty:
         return ((QDeclarativeListReference *)d.constData())->count();
     case Instance:
         return 1;
     case Integer:
         return d.toInt();
     default:
     case Invalid:
         return 0;
     }
 }
isValid()
bool QDeclarativeListAccessor::isValid () const
Definition at line 133 of file qdeclarativelistaccessor.cpp.
 {
     return m_type != Invalid;
 }
list()
QVariant QDeclarativeListAccessor::list () const
Definition at line 63 of file qdeclarativelistaccessor.cpp.
 {
     return d;
 }
setList()
void QDeclarativeListAccessor::setList (const QVariant & v, QDeclarativeEngine * engine = 0)
Definition at line 68 of file qdeclarativelistaccessor.cpp.
 {
     d = v;
     QDeclarativeEnginePrivate *enginePrivate = engine?QDeclarativeEnginePrivate::get(engine):0;
     if (!d.isValid()) {
         m_type = Invalid;
     } else if (d.userType() == QVariant::StringList) {
         m_type = StringList;
     } else if (d.userType() == QMetaType::QVariantList) {
         m_type = VariantList;
     } else if (d.canConvert(QVariant::Int)) {
         m_type = Integer;
     } else if ((!enginePrivate && QDeclarativeMetaType::isQObject(d.userType())) ||
                (enginePrivate && enginePrivate->isQObject(d.userType()))) {
         QObject *data = enginePrivate?enginePrivate->toQObject(v):QDeclarativeMetaType::toQObject(v);
         d = QVariant::fromValue(data);
         m_type = Instance;
     } else if (d.userType() == qMetaTypeId<QDeclarativeListReference>()) {
         m_type = ListProperty;
     } else {
         m_type = Instance;
     }
 }
type()
Type QDeclarativeListAccessor::type () const inline
Definition at line 69 of file qdeclarativelistaccessor_p.h.
Referenced by QDeclarativeVisualDataModelDataMetaObject::createProperty(), and QDeclarativeVisualDataModelDataMetaObject::initialValue().
 { return m_type; }
Properties
d
QVariant QDeclarativeListAccessor::d private
Definition at line 73 of file qdeclarativelistaccessor_p.h.
Referenced by at(), count(), list(), and setList().
m_type
Type QDeclarativeListAccessor::m_type private
Definition at line 72 of file qdeclarativelistaccessor_p.h.
Referenced by at(), count(), isValid(), and setList().
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativelistaccessor_p.h
/src/declarative/util/qdeclarativelistaccessor.cpp