Qt 4.8: QSqlDatabase Class Reference
QSqlDatabase Class Reference
The QSqlDatabase class represents a connection to a database.
#include <qsqldatabase.h>
Public Functions
void close ()
Closes the database connection, freeing any resources acquired, and invalidating any existing QSqlQuery objects that are used with the database.
bool commit ()
Commits a transaction to the database if the driver supports transactions and a transaction() has been started.
QString connectionName () const
Returns the connection name, which may be empty.
QString connectOptions () const
Returns the connection options string used for this connection.
QString databaseName () const
Returns the connection's database name, which may be empty.
QSqlDriver * driver () const
Returns the database driver used to access the database connection.
QString driverName () const
Returns the connection's driver name.
QSqlQuery exec (const QString &query=QString()) const
Executes a SQL statement on the database and returns a QSqlQuery object.
QString hostName () const
Returns the connection's host name; it may be empty.
bool isOpen () const
Returns true if the database connection is currently open; otherwise returns false.
bool isOpenError () const
Returns true if there was an error opening the database connection; otherwise returns false.
bool isValid () const
Returns true if the QSqlDatabase has a valid driver.
QSqlError lastError () const
Returns information about the last error that occurred on the database.
QSql::NumericalPrecisionPolicy numericalPrecisionPolicy () const
Returns the current default precision policy for the database connection.
bool open ()
Opens the database connection using the current connection values.
bool open (const QString &user, const QString &password)
Opens the database connection using the given user name and password.
QSqlDatabase & operator= (const QSqlDatabase &other)
Assigns other to this object.
QString password () const
Returns the connection's password.
int port () const
Returns the connection's port number.
QSqlIndex primaryIndex (const QString &tablename) const
Returns the primary index for table tablename.
QSqlDatabase ()
Creates an empty, invalid QSqlDatabase object.
QSqlDatabase (const QSqlDatabase &other)
Creates a copy of other.
QSqlRecord record (const QString &tablename) const
Returns a QSqlRecord populated with the names of all the fields in the table (or view) called tablename.
bool rollback ()
Rolls back a transaction on the database, if the driver supports transactions and a transaction() has been started.
void setConnectOptions (const QString &options=QString())
Sets database-specific options.
void setDatabaseName (const QString &name)
Sets the connection's database name to name.
void setHostName (const QString &host)
Sets the connection's host name to host.
void setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy precisionPolicy)
Sets the default numerical precision policy used by queries created on this database connection to precisionPolicy.
void setPassword (const QString &password)
Sets the connection's password to password.
void setPort (int p)
Sets the connection's port number to port.
void setUserName (const QString &name)
Sets the connection's user name to name.
QStringList tables (QSql::TableType type=QSql::Tables) const
Returns a list of the database's tables, system tables and views, as specified by the parameter type.
bool transaction ()
Begins a transaction on the database if the driver supports transactions.
QString userName () const
Returns the connection's user name; it may be empty.
~QSqlDatabase ()
Destroys the object and frees any allocated resources.
Static Public Functions
static QSqlDatabase addDatabase (const QString &type, const QString &connectionName=QLatin1String(defaultConnection))
Adds a database to the list of database connections using the driver type and the connection name connectionName.
static QSqlDatabase addDatabase (QSqlDriver *driver, const QString &connectionName=QLatin1String(defaultConnection))
This overload is useful when you want to create a database connection with a driver you instantiated yourself.
static QSqlDatabase cloneDatabase (const QSqlDatabase &other, const QString &connectionName)
Clones the database connection other and and stores it as connectionName.
static QStringList connectionNames ()
Returns a list containing the names of all connections.
static bool contains (const QString &connectionName=QLatin1String(defaultConnection))
Returns true if the list of database connections contains connectionName; otherwise returns false.
static QSqlDatabase database (const QString &connectionName=QLatin1String(defaultConnection), bool open=true)
Returns the database connection called connectionName.
static QStringList drivers ()
Returns a list of all the available database drivers.
static bool isDriverAvailable (const QString &name)
Returns true if a driver called name is available; otherwise returns false.
static void registerSqlDriver (const QString &name, QSqlDriverCreatorBase *creator)
This function registers a new SQL driver called name, within the SQL framework.
static void removeDatabase (const QString &connectionName)
Removes the database connection connectionName from the list of database connections.
Public Variables
QT_STATIC_CONST char * defaultConnection
Protected Functions
QSqlDatabase (const QString &type)
Creates a QSqlDatabase connection that uses the driver referred to by type.
QSqlDatabase (QSqlDriver *driver)
Creates a database connection using the given driver.
Properties
QSqlDatabasePrivate * d
Friends
class QSqlDatabasePrivate
Detailed Description
The QSqlDatabase class represents a connection to a database.
Attention
Module: QtSql
The QSqlDatabase class provides an interface for accessing a database through a connection. An instance of QSqlDatabase represents the connection. The connection provides access to the database via one of the SQL Database Drivers::Supported Databases {supported database drivers}, which are derived from QSqlDriver. Alternatively, you can subclass your own database driver from QSqlDriver. See How to Write Your Own Database Driver for more information.
Create a connection (i.e., an instance of QSqlDatabase) by calling one of the static addDatabase() functions, where you specify SQL Database Drivers::Supported Databases {the driver or type of driver} to use (i.e., what kind of database will you access?) and a connection name. A connection is known by its own name, not by the name of the database it connects to. You can have multiple connections to one database. QSqlDatabase also supports the concept of a default connection, which is the unnamed connection. To create the default connection, don't pass the connection name argument when you call addDatabase(). Subsequently, when you call any static member function that takes the connection name argument, if you don't pass the connection name argument, the default connection is assumed. The following snippet shows how to create and open a default connection to a PostgreSQL database:
    QSqlDatabase db = QSqlDatabase::addDatabase("QPSQL");
    db.setHostName("acidalia");
    db.setDatabaseName("customdb");
    db.setUserName("mojito");
    db.setPassword("J0a1m8");
    bool ok = db.open();
Once the QSqlDatabase object has been created, set the connection parameters with setDatabaseName(), setUserName(), setPassword(), setHostName(), setPort(), and setConnectOptions(). Then call open() to activate the physical connection to the database. The connection is not usable until you open it.
The connection defined above will be the default connection, because we didn't give a connection name to QSqlDatabase::addDatabase() . Subsequently, you can get the default connection by calling database() without the connection name argument:
    QSqlDatabase db = QSqlDatabase::database();
QSqlDatabase is a value class. Changes made to a database connection via one instance of QSqlDatabase will affect other instances of QSqlDatabase that represent the same connection. Use cloneDatabase() to create an independent database connection based on an existing one.
If you create multiple database connections, specify a unique connection name for each one, when you call addDatabase(). Use database() with a connection name to get that connection. Use removeDatabase() with a connection name to remove a connection. QSqlDatabase outputs a warning if you try to remove a connection referenced by other QSqlDatabase objects. Use contains() to see if a given connection name is in the list of connections.
Once a connection is established, you can call tables() to get the list of tables in the database, call primaryIndex() to get a table's primary index, and call record() to get meta-information about a table's fields (e.g., field names).
Note
QSqlDatabase::exec() is deprecated. Use QSqlQuery::exec() instead.
If the driver supports transactions, use transaction() to start a transaction, and commit() or rollback() to complete it. Use QSqlDriver::hasFeature() to ask if the driver supports transactions.
Note
When using transactions, you must start the transaction before you create your query.
If an error occurrs, lastError() will return information about it.
Get the names of the available SQL drivers with drivers(). Check for the presence of a particular driver with isDriverAvailable(). If you have created your own custom driver, you must register it with registerSqlDriver().
See also
QSqlDriver, QSqlQuery, {QtSql Module}, {Threads and the SQL Module}
Definition at line 78 of file qsqldatabase.h.
Constructors and Destructors
QSqlDatabase() [1/4]
QSqlDatabase::QSqlDatabase ()
Creates an empty, invalid QSqlDatabase object.
Use addDatabase(), removeDatabase(), and database() to get valid QSqlDatabase objects.
Definition at line 729 of file qsqldatabase.cpp.
 {
     d = QSqlDatabasePrivate::shared_null();
     d->ref.ref();
 }
QSqlDatabase() [2/4]
QSqlDatabase::QSqlDatabase (const QSqlDatabase & other)
Creates a copy of other.
Definition at line 738 of file qsqldatabase.cpp.
 {
     d = other.d;
     d->ref.ref();
 }
~QSqlDatabase()
QSqlDatabase::~QSqlDatabase ()
Destroys the object and frees any allocated resources.
See also
close()
Definition at line 838 of file qsqldatabase.cpp.
 {
     if (!d->ref.deref()) {
         close();
         delete d;
     }
 }
QSqlDatabase() [3/4]
QSqlDatabase::QSqlDatabase (const QString & type) explicit protected
Creates a QSqlDatabase connection that uses the driver referred to by type.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the type is not recognized, the database connection will have no functionality.
The currently available driver types are:
Driver Type Description
QDB2 IBM DB2
QIBASE Borland InterBase Driver
QMYSQL MySQL Driver
QOCI Oracle Call Interface Driver
QODBC ODBC Driver (includes Microsoft SQL Server)
QPSQL PostgreSQL Driver
QSQLITE SQLite version 3 or above
QSQLITE2 SQLite version 2
QTDS Sybase Adaptive Server
Additional third party drivers, including your own custom drivers, can be loaded dynamically.
See also
{SQL Database Drivers}, registerSqlDriver(), drivers()
Definition at line 704 of file qsqldatabase.cpp.
 {
     d = new QSqlDatabasePrivate(this);
     d->init(type);
 }
QSqlDatabase() [4/4]
QSqlDatabase::QSqlDatabase (QSqlDriver * driver) explicit protected
Creates a database connection using the given driver.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 719 of file qsqldatabase.cpp.
 {
     d = new QSqlDatabasePrivate(this, driver);
 }
Functions
addDatabase() [1/2]
QSqlDatabase QSqlDatabase::addDatabase (const QString & type, const QString & connectionName = QLatin1String(defaultConnection)) static
Adds a database to the list of database connections using the driver type and the connection name connectionName.
Note
This class or function is threadsafe.
If there already exists a database connection called connectionName, that connection is removed.
The database connection is referred to by connectionName. The newly added database connection is returned.
If type is not available or could not be loaded, isValid() returns false.
If connectionName is not specified, the new connection becomes the default connection for the application, and subsequent calls to database() without the connection name argument will return the default connection. If a connectionName is provided here, use database(connectionName) to retrieve the connection.
Warning
If you add a connection with the same name as an existing connection, the new connection replaces the old one. If you call this function more than once without specifying connectionName, the default connection will be the one replaced.
Before using the connection, it must be initialized. e.g., call some or all of setDatabaseName(), setUserName(), setPassword(), setHostName(), setPort(), and setConnectOptions(), and, finally, open().
See also
database() removeDatabase() {Threads and the SQL Module}
Definition at line 495 of file qsqldatabase.cpp.
Referenced by qmlsqldatabase_open_sync().
 {
     QSqlDatabase db(type);
     QSqlDatabasePrivate::addDatabase(db, connectionName);
     return db;
 }
addDatabase() [2/2]
QSqlDatabase QSqlDatabase::addDatabase (QSqlDriver * driver, const QString & connectionName = QLatin1String(defaultConnection)) static
This overload is useful when you want to create a database connection with a driver you instantiated yourself.
It might be your own database driver, or you might just need to instantiate one of the Qt drivers yourself. If you do this, it is recommended that you include the driver code in your application. For example, you can create a PostgreSQL connection with your own QPSQL driver like this:
#include "qtdir/src/sql/drivers/psql/qsql_psql.cpp"
PGconn *con = PQconnectdb("host=server user=bart password=simpson dbname=springfield");
QPSQLDriver *drv =  new QPSQLDriver(con);
QSqlDatabase db = QSqlDatabase::addDatabase(drv); // becomes the new default connection
QSqlQuery query;
query.exec("SELECT NAME, ID FROM STAFF");
...
The above code sets up a PostgreSQL connection and instantiates a QPSQLDriver object. Next, addDatabase() is called to add the connection to the known connections so that it can be used by the Qt SQL classes. When a driver is instantiated with a connection handle (or set of handles), Qt assumes that you have already opened the database connection.
Note
We assume that qtdir is the directory where Qt is installed. This will pull in the code that is needed to use the PostgreSQL client library and to instantiate a QPSQLDriver object, assuming that you have the PostgreSQL headers somewhere in your include search path.
Remember that you must link your application against the database client library. Make sure the client library is in your linker's search path, and add lines like these to your .pro file:
unix:LIBS += -lpq
win32:LIBS += libpqdll.lib
The method described works for all the supplied drivers. The only difference will be in the driver constructor arguments. Here is a table of the drivers included with Qt, their source code files, and their constructor arguments:
Driver Class name Constructor arguments File to include
QPSQL QPSQLDriver PGconn *connection qsql_psql.cpp
QMYSQL QMYSQLDriver MYSQL *connection qsql_mysql.cpp
QOCI QOCIDriver OCIEnv *environment, OCISvcCtx *serviceContext qsql_oci.cpp
QODBC QODBCDriver SQLHANDLE environment, SQLHANDLE connection qsql_odbc.cpp
QDB2 QDB2 SQLHANDLE environment, SQLHANDLE connection qsql_db2.cpp
QTDS QTDSDriver LOGINREC *loginRecord, DBPROCESS *dbProcess, const QString &hostName qsql_tds.cpp
QSQLITE QSQLiteDriver sqlite *connection qsql_sqlite.cpp
QIBASE QIBaseDriver isc_db_handle connection qsql_ibase.cpp
The host name (or service name) is needed when constructing the QTDSDriver for creating new connections for internal queries. This is to prevent blocking when several QSqlQuery objects are used simultaneously.
Warning
Adding a database connection with the same connection name as an existing connection, causes the existing connection to be replaced by the new one.
The SQL framework takes ownership of the driver. It must not be deleted. To remove the connection, use removeDatabase().
See also
drivers()
Definition at line 1441 of file qsqldatabase.cpp.
 {
     QSqlDatabase db(driver);
     QSqlDatabasePrivate::addDatabase(db, connectionName);
     return db;
 }
cloneDatabase()
QSqlDatabase QSqlDatabase::cloneDatabase (const QSqlDatabase & other, const QString & connectionName) static
Clones the database connection other and and stores it as connectionName.
All the settings from the original database, e.g. databaseName(), hostName(), etc., are copied across. Does nothing if other is an invalid database. Returns the newly created database connection.
Note
The new connection has not been opened. Before using the new connection, you must call open().
Definition at line 1492 of file qsqldatabase.cpp.
 {
     if (!other.isValid())
         return QSqlDatabase();
     QSqlDatabase db(other.driverName());
     db.d->copy(other.d);
     QSqlDatabasePrivate::addDatabase(db, connectionName);
     return db;
 }
close()
void QSqlDatabase::close ()
Closes the database connection, freeing any resources acquired, and invalidating any existing QSqlQuery objects that are used with the database.
This will also affect copies of this QSqlDatabase object.
See also
removeDatabase()
Definition at line 914 of file qsqldatabase.cpp.
 {
     d->driver->close();
 }
commit()
bool QSqlDatabase::commit ()
Commits a transaction to the database if the driver supports transactions and a transaction() has been started.
Returns true if the operation succeeded. Otherwise it returns false.
Note
For some databases, the commit will fail and return false if there is an active query using the database for a SELECT. Make the query inactive before doing the commit.
Call lastError() to get information about errors.
See also
QSqlQuery::isActive() QSqlDriver::hasFeature() rollback()
Definition at line 967 of file qsqldatabase.cpp.
Referenced by qmlsqldatabase_change_version(), and qmlsqldatabase_transaction_shared().
 {
     if (!d->driver->hasFeature(QSqlDriver::Transactions))
         return false;
     return d->driver->commitTransaction();
 }
connectionName()
QString QSqlDatabase::connectionName () const
Returns the connection name, which may be empty.
Since
4.4
Note
The connection name is not the database name.
See also
addDatabase()
Definition at line 1514 of file qsqldatabase.cpp.
Referenced by qmlsqldatabase_change_version().
 {
     return d->connName;
 }
connectionNames()
QStringList QSqlDatabase::connectionNames () static
Returns a list containing the names of all connections.
Note
This class or function is threadsafe.
See also
contains(), database(), {Threads and the SQL Module}
Definition at line 668 of file qsqldatabase.cpp.
Referenced by qmlsqldatabase_open_sync().
 {
     return dbDict()->keys_ts();
 }
connectOptions()
QString QSqlDatabase::connectOptions () const
Returns the connection options string used for this connection.
The string may be empty.
See also
setConnectOptions()
Definition at line 1327 of file qsqldatabase.cpp.
 {
     return d->connOptions;
 }
contains()
bool QSqlDatabase::contains (const QString & connectionName = QLatin1String(defaultConnection)) static
Returns true if the list of database connections contains connectionName; otherwise returns false.
Note
This class or function is threadsafe.
See also
connectionNames(), database(), {Threads and the SQL Module}
Definition at line 653 of file qsqldatabase.cpp.
 {
     return dbDict()->contains_ts(connectionName);
 }
database()
QSqlDatabase QSqlDatabase::database (const QString & connectionName = QLatin1String(defaultConnection), bool open = true) static
Returns the database connection called connectionName.
Note
This class or function is threadsafe.
The database connection must have been previously added with addDatabase(). If open is true (the default) and the database connection is not already open it is opened now. If no connectionName is specified the default connection is used. If connectionName does not exist in the list of databases, an invalid connection is returned.
See also
isOpen() {Threads and the SQL Module}
Definition at line 519 of file qsqldatabase.cpp.
Referenced by qInit(), qmlsqldatabase_open_sync(), and QSqlTableModel::QSqlTableModel().
 {
     return QSqlDatabasePrivate::database(connectionName, open);
 }
databaseName()
QString QSqlDatabase::databaseName () const
Returns the connection's database name, which may be empty.
Note
The database name is not the connection name.
See also
setDatabaseName()
Definition at line 1107 of file qsqldatabase.cpp.
Referenced by operator<<().
 {
     return d->dbname;
 }
driver()
QSqlDriver * QSqlDatabase::driver () const
Returns the database driver used to access the database connection.
See also
addDatabase() drivers()
Definition at line 1170 of file qsqldatabase.cpp.
Referenced by QSqlTableModelPrivate::exec(), QSqlTableModelPrivate::nameToIndex(), QRelation::populateDictionary(), and qInit().
 {
     return d->driver;
 }
driverName()
QString QSqlDatabase::driverName () const
Returns the connection's driver name.
See also
addDatabase(), driver()
Definition at line 1147 of file qsqldatabase.cpp.
Referenced by cloneDatabase(), and operator<<().
 {
     return d->drvName;
 }
drivers()
QStringList QSqlDatabase::drivers () static
Returns a list of all the available database drivers.
See also
registerSqlDriver()
Definition at line 565 of file qsqldatabase.cpp.
Referenced by QSqlDatabasePrivate::init().
 {
     QStringList list;
 #ifdef QT_SQL_PSQL
     list << QLatin1String("QPSQL7");
     list << QLatin1String("QPSQL");
 #endif
 #ifdef QT_SQL_MYSQL
     list << QLatin1String("QMYSQL3");
     list << QLatin1String("QMYSQL");
 #endif
 #ifdef QT_SQL_ODBC
     list << QLatin1String("QODBC3");
     list << QLatin1String("QODBC");
 #endif
 #ifdef QT_SQL_OCI
     list << QLatin1String("QOCI8");
     list << QLatin1String("QOCI");
 #endif
 #ifdef QT_SQL_TDS
     list << QLatin1String("QTDS7");
     list << QLatin1String("QTDS");
 #endif
 #ifdef QT_SQL_DB2
     list << QLatin1String("QDB2");
 #endif
 #ifdef QT_SQL_SQLITE
     list << QLatin1String("QSQLITE");
 #endif
 #ifdef QT_SQL_SQLITE2
     list << QLatin1String("QSQLITE2");
 #endif
 #ifdef QT_SQL_IBASE
     list << QLatin1String("QIBASE");
 #endif
 #ifndef QT_NO_LIBRARY
     if (QFactoryLoader *fl = loader()) {
         QStringList keys = fl->keys();
         for (QStringList::const_iterator i = keys.constBegin(); i != keys.constEnd(); ++i) {
             if (!list.contains(*i))
                 list << *i;
         }
     }
 #endif
     DriverDict dict = QSqlDatabasePrivate::driverDict();
     for (DriverDict::const_iterator i = dict.constBegin(); i != dict.constEnd(); ++i) {
         if (!list.contains(i.key()))
             list << i.key();
     }
     return list;
 }
exec()
QSqlQuery QSqlDatabase::exec (const QString & query = QString()) const
Executes a SQL statement on the database and returns a QSqlQuery object.
Use lastError() to retrieve error information. If query is empty, an empty, invalid query is returned and lastError() is not affected.
See also
QSqlQuery, lastError()
Definition at line 855 of file qsqldatabase.cpp.
 {
     QSqlQuery r(d->driver->createResult());
     if (!query.isEmpty()) {
         r.exec(query);
         d->driver->setLastError(r.lastError());
     }
     return r;
 }
hostName()
QString QSqlDatabase::hostName () const
Returns the connection's host name; it may be empty.
See also
setHostName()
Definition at line 1137 of file qsqldatabase.cpp.
Referenced by operator<<().
 {
     return d->hname;
 }
isDriverAvailable()
bool QSqlDatabase::isDriverAvailable (const QString & name) static
Returns true if a driver called name is available; otherwise returns false.
See also
drivers()
Definition at line 1339 of file qsqldatabase.cpp.
 {
     return drivers().contains(name);
 }
isOpen()
bool QSqlDatabase::isOpen () const
Returns true if the database connection is currently open; otherwise returns false.
Definition at line 924 of file qsqldatabase.cpp.
Referenced by QSqlDatabasePrivate::database(), operator<<(), and qmlsqldatabase_open_sync().
 {
     return d->driver->isOpen();
 }
isOpenError()
bool QSqlDatabase::isOpenError () const
Returns true if there was an error opening the database connection; otherwise returns false.
Error information can be retrieved using the lastError() function.
Definition at line 935 of file qsqldatabase.cpp.
 {
     return d->driver->isOpenError();
 }
isValid()
bool QSqlDatabase::isValid () const
Returns true if the QSqlDatabase has a valid driver.
Example:
QSqlDatabase db;
qDebug() << db.isValid();    // Returns false
db = QSqlDatabase::database("sales");
qDebug() << db.isValid();    // Returns true if "sales" connection exists
QSqlDatabase::removeDatabase("sales");
qDebug() << db.isValid();    // Returns false
Definition at line 1454 of file qsqldatabase.cpp.
Referenced by cloneDatabase(), QSqlDatabasePrivate::database(), operator<<(), qInit(), and QSqlTableModel::QSqlTableModel().
 {
     return d->driver && d->driver != d->shared_null()->driver;
 }
lastError()
QSqlError QSqlDatabase::lastError () const
Returns information about the last error that occurred on the database.
Failures that occur in conjunction with an individual query are reported by QSqlQuery::lastError().
See also
QSqlError, QSqlQuery::lastError()
Definition at line 1185 of file qsqldatabase.cpp.
Referenced by QSqlDatabasePrivate::database().
 {
     return d->driver->lastError();
 }
numericalPrecisionPolicy()
QSql::NumericalPrecisionPolicy QSqlDatabase::numericalPrecisionPolicy () const
Returns the current default precision policy for the database connection.
Since
4.6
See also
QSql::NumericalPrecisionPolicy, setNumericalPrecisionPolicy(), QSqlQuery::numericalPrecisionPolicy(), QSqlQuery::setNumericalPrecisionPolicy()
Definition at line 1557 of file qsqldatabase.cpp.
 {
     if(driver())
         return driver()->numericalPrecisionPolicy();
     else
         return d->precisionPolicy;
 }
open() [1/2]
bool QSqlDatabase::open ()
Opens the database connection using the current connection values.
Returns true on success; otherwise returns false. Error information can be retrieved using lastError().
See also
lastError() setDatabaseName() setUserName() setPassword()
setHostName() setPort() setConnectOptions()
Definition at line 874 of file qsqldatabase.cpp.
Referenced by QSqlDatabasePrivate::database(), and qmlsqldatabase_open_sync().
 {
     return d->driver->open(d->dbname, d->uname, d->pword, d->hname,
                             d->port, d->connOptions);
 }
open() [2/2]
bool QSqlDatabase::open (const QString & user, const QString & password)
Opens the database connection using the given user name and password.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true on success; otherwise returns false. Error information can be retrieved using the lastError() function.
This function does not store the password it is given. Instead, the password is passed directly to the driver for opening the connection and it is then discarded.
See also
lastError()
Definition at line 897 of file qsqldatabase.cpp.
 {
     setUserName(user);
     return d->driver->open(d->dbname, user, password, d->hname,
                             d->port, d->connOptions);
 }
operator=()
QSqlDatabase & QSqlDatabase::operator= (const QSqlDatabase & other)
Assigns other to this object.
Definition at line 747 of file qsqldatabase.cpp.
 {
     qAtomicAssign(d, other.d);
     return *this;
 }
password()
QString QSqlDatabase::password () const
Returns the connection's password.
If the password was not set with setPassword(), and if the password was given in the open() call, or if no password was used, an empty string is returned.
Definition at line 1127 of file qsqldatabase.cpp.
 {
     return d->pword;
 }
port()
int QSqlDatabase::port () const
Returns the connection's port number.
The value is undefined if the port number has not been set.
See also
setPort()
Definition at line 1158 of file qsqldatabase.cpp.
Referenced by operator<<().
 {
     return d->port;
 }
primaryIndex()
QSqlIndex QSqlDatabase::primaryIndex (const QString & tablename) const
Returns the primary index for table tablename.
If no primary index exists an empty QSqlIndex is returned.
See also
tables(), record()
Definition at line 1210 of file qsqldatabase.cpp.
Referenced by QSqlTableModelPrivate::initRecordAndPrimaryIndex().
 {
     return d->driver->primaryIndex(tablename);
 }
record()
QSqlRecord QSqlDatabase::record (const QString & tablename) const
Returns a QSqlRecord populated with the names of all the fields in the table (or view) called tablename.
The order in which the fields appear in the record is undefined. If no such table (or view) exists, an empty record is returned.
Definition at line 1223 of file qsqldatabase.cpp.
Referenced by QSqlTableModelPrivate::initRecordAndPrimaryIndex(), isValid(), and QSqlRelationalTableModel::selectStatement().
 {
     return d->driver->record(tablename);
 }
registerSqlDriver()
void QSqlDatabase::registerSqlDriver (const QString & name, QSqlDriverCreatorBase * creator) static
This function registers a new SQL driver called name, within the SQL framework.
This is useful if you have a custom SQL driver and don't want to compile it as a plugin.
Example:
QSqlDatabase::registerSqlDriver("MYDRIVER",
                                new QSqlDriverCreator<MyDatabaseDriver>);
QSqlDatabase db = QSqlDatabase::addDatabase("MYDRIVER");
QSqlDatabase takes ownership of the creator pointer, so you mustn't delete it yourself.
See also
drivers()
Definition at line 634 of file qsqldatabase.cpp.
 {
     delete QSqlDatabasePrivate::driverDict().take(name);
     if (creator)
         QSqlDatabasePrivate::driverDict().insert(name, creator);
 }
removeDatabase()
void QSqlDatabase::removeDatabase (const QString & connectionName) static
Removes the database connection connectionName from the list of database connections.
Note
This class or function is threadsafe.
Warning
There should be no open queries on the database connection when this function is called, otherwise a resource leak will occur.
Example:
// WRONG
QSqlDatabase db = QSqlDatabase::database("sales");
QSqlQuery query("SELECT NAME, DOB FROM EMPLOYEES", db);
QSqlDatabase::removeDatabase("sales"); // will output a warning
// "db" is now a dangling invalid database connection,
// "query" contains an invalid result set
The correct way to do it:
{
    QSqlDatabase db = QSqlDatabase::database("sales");
    QSqlQuery query("SELECT NAME, DOB FROM EMPLOYEES", db);
}
// Both "db" and "query" are destroyed because they are out of scope
QSqlDatabase::removeDatabase("sales"); // correct
To remove the default connection, which may have been created with a call to addDatabase() not specifying a connection name, you can retrieve the default connection name by calling connectionName() on the database returned by database(). Note that if a default database hasn't been created an invalid database will be returned.
See also
database() connectionName() {Threads and the SQL Module}
Definition at line 554 of file qsqldatabase.cpp.
 {
     QSqlDatabasePrivate::removeDatabase(connectionName);
 }
rollback()
bool QSqlDatabase::rollback ()
Rolls back a transaction on the database, if the driver supports transactions and a transaction() has been started.
Returns true if the operation succeeded. Otherwise it returns false.
Note
For some databases, the rollback will fail and return false if there is an active query using the database for a SELECT. Make the query inactive before doing the rollback.
Call lastError() to get information about errors.
See also
QSqlQuery::isActive() QSqlDriver::hasFeature() commit()
Definition at line 988 of file qsqldatabase.cpp.
Referenced by qmlsqldatabase_change_version(), and qmlsqldatabase_transaction_shared().
 {
     if (!d->driver->hasFeature(QSqlDriver::Transactions))
         return false;
     return d->driver->rollbackTransaction();
 }
setConnectOptions()
void QSqlDatabase::setConnectOptions (const QString & options = QString())
Sets database-specific options.
This must be done before the connection is opened or it has no effect (or you can close() the connection, call this function and open() the connection again).
The format of the options string is a semicolon separated list of option names or option=value pairs. The options depend on the database client used:
ODBC MySQL PostgreSQL
SQL_ATTR_ACCESS_MODE SQL_ATTR_LOGIN_TIMEOUT SQL_ATTR_CONNECTION_TIMEOUT SQL_ATTR_CURRENT_CATALOG SQL_ATTR_METADATA_ID SQL_ATTR_PACKET_SIZE SQL_ATTR_TRACEFILE SQL_ATTR_TRACE SQL_ATTR_CONNECTION_POOLING
SQL_ATTR_ODBC_VERSION
CLIENT_COMPRESS CLIENT_FOUND_ROWS CLIENT_IGNORE_SPACE CLIENT_SSL CLIENT_ODBC CLIENT_NO_SCHEMA CLIENT_INTERACTIVE UNIX_SOCKET
MYSQL_OPT_RECONNECT
connect_timeout options tty requiressl
service
DB2 OCI TDS
SQL_ATTR_ACCESS_MODE
SQL_ATTR_LOGIN_TIMEOUT
OCI_ATTR_PREFETCH_ROWS
OCI_ATTR_PREFETCH_MEMORY
none
SQLite Interbase
QSQLITE_BUSY_TIMEOUT QSQLITE_OPEN_READONLY
QSQLITE_ENABLE_SHARED_CACHE
ISC_DPB_LC_CTYPE
ISC_DPB_SQL_ROLE_NAME
Examples:
...
// MySQL connection
db.setConnectOptions("CLIENT_SSL=1;CLIENT_IGNORE_SPACE=1"); // use an SSL connection to the server
if (!db.open()) {
    db.setConnectOptions(); // clears the connect option string
    ...
}
...
// PostgreSQL connection
db.setConnectOptions("requiressl=1"); // enable PostgreSQL SSL connections
if (!db.open()) {
    db.setConnectOptions(); // clear options
    ...
}
...
// ODBC connection
db.setConnectOptions("SQL_ATTR_ACCESS_MODE=SQL_MODE_READ_ONLY;SQL_ATTR_TRACE=SQL_OPT_TRACE_ON"); // set ODBC options
if (!db.open()) {
    db.setConnectOptions(); // don't try to set this option
    ...
}
Refer to the client library documentation for more information about the different options.
See also
connectOptions()
Definition at line 1315 of file qsqldatabase.cpp.
 {
     if (isValid())
         d->connOptions = options;
 }
setDatabaseName()
void QSqlDatabase::setDatabaseName (const QString & name)
Sets the connection's database name to name.
To have effect, the database name must be set before the connection is opened. Alternatively, you can close() the connection, set the database name, and call open() again.
Note
The database name is not the connection name. The connection name must be passed to addDatabase() at connection object create time.
For the QOCI (Oracle) driver, the database name is the TNS Service Name.
For the QODBC driver, the name can either be a DSN, a DSN filename (in which case the file must have a .dsn extension), or a connection string.
For example, Microsoft Access users can use the following connection string to open an .mdb file directly, instead of having to create a DSN entry in the ODBC manager:
...
db = QSqlDatabase::addDatabase("QODBC");
db.setDatabaseName("DRIVER={Microsoft Access Driver (*.mdb)};FIL={MS Access};DBQ=myaccessfile.mdb");
if (db.open()) {
    // success!
}
...
There is no default value.
See also
databaseName() setUserName() setPassword() setHostName()
setPort() setConnectOptions() open()
Definition at line 1023 of file qsqldatabase.cpp.
Referenced by qmlsqldatabase_open_sync().
 {
     if (isValid())
         d->dbname = name;
 }
setHostName()
void QSqlDatabase::setHostName (const QString & host)
Sets the connection's host name to host.
To have effect, the host name must be set before the connection is opened. Alternatively, you can close() the connection, set the host name, and call open() again.
There is no default value.
See also
hostName() setUserName() setPassword() setDatabaseName()
setPort() setConnectOptions() open()
Definition at line 1078 of file qsqldatabase.cpp.
 {
     if (isValid())
         d->hname = host;
 }
setNumericalPrecisionPolicy()
void QSqlDatabase::setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy precisionPolicy)
Sets the default numerical precision policy used by queries created on this database connection to precisionPolicy.
Since
4.6
Note: Drivers that don't support fetching numerical values with low precision will ignore the precision policy. You can use QSqlDriver::hasFeature() to find out whether a driver supports this feature.
Note: Setting the default precision policy to precisionPolicy doesn't affect any currently active queries.
See also
QSql::NumericalPrecisionPolicy, numericalPrecisionPolicy(), QSqlQuery::setNumericalPrecisionPolicy(), QSqlQuery::numericalPrecisionPolicy()
Definition at line 1539 of file qsqldatabase.cpp.
 {
     if(driver())
         driver()->setNumericalPrecisionPolicy(precisionPolicy);
     d->precisionPolicy = precisionPolicy;
 }
setPassword()
void QSqlDatabase::setPassword (const QString & password)
Sets the connection's password to password.
To have effect, the password must be set before the connection is opened. Alternatively, you can close() the connection, set the password, and call open() again.
There is no default value.
Warning
This function stores the password in plain text within Qt. Use the open() call that takes a password as parameter to avoid this behavior.
See also
password() setUserName() setDatabaseName() setHostName()
setPort() setConnectOptions() open()
Definition at line 1061 of file qsqldatabase.cpp.
 {
     if (isValid())
         d->pword = password;
 }
setPort()
void QSqlDatabase::setPort (int port)
Sets the connection's port number to port.
To have effect, the port number must be set before the connection is opened. Alternatively, you can close() the connection, set the port number, and call open() again..
There is no default value.
See also
port() setUserName() setPassword() setHostName()
setDatabaseName() setConnectOptions() open()
Definition at line 1095 of file qsqldatabase.cpp.
 {
     if (isValid())
         d->port = port;
 }
setUserName()
void QSqlDatabase::setUserName (const QString & name)
Sets the connection's user name to name.
To have effect, the user name must be set before the connection is opened. Alternatively, you can close() the connection, set the user name, and call open() again.
There is no default value.
See also
userName() setDatabaseName() setPassword() setHostName()
setPort() setConnectOptions() open()
Definition at line 1040 of file qsqldatabase.cpp.
 {
     if (isValid())
         d->uname = name;
 }
tables()
QStringList QSqlDatabase::tables (QSql::TableType type = QSql::Tables) const
Returns a list of the database's tables, system tables and views, as specified by the parameter type.
See also
primaryIndex(), record()
Definition at line 1198 of file qsqldatabase.cpp.
 {
     return d->driver->tables(type);
 }
transaction()
bool QSqlDatabase::transaction ()
Begins a transaction on the database if the driver supports transactions.
Returns true if the operation succeeded. Otherwise it returns false.
See also
QSqlDriver::hasFeature(), commit(), rollback()
Definition at line 947 of file qsqldatabase.cpp.
Referenced by qmlsqldatabase_change_version(), and qmlsqldatabase_transaction_shared().
 {
     if (!d->driver->hasFeature(QSqlDriver::Transactions))
         return false;
     return d->driver->beginTransaction();
 }
userName()
QString QSqlDatabase::userName () const
Returns the connection's user name; it may be empty.
See also
setUserName()
Definition at line 1117 of file qsqldatabase.cpp.
Referenced by operator<<().
 {
     return d->uname;
 }
Friends and Related Functions
QSqlDatabasePrivate
friend class QSqlDatabasePrivate friend
Definition at line 149 of file qsqldatabase.h.
Properties
d
QSqlDatabasePrivate* QSqlDatabase::d private
Definition at line 150 of file qsqldatabase.h.
Referenced by QSqlDatabasePrivate::addDatabase(), cloneDatabase(), QSqlDatabasePrivate::invalidateDb(), operator=(), and QSqlDatabase().
defaultConnection
QT_STATIC_CONST char* QSqlDatabase::defaultConnection
Definition at line 128 of file qsqldatabase.h.
Referenced by qInit().
The documentation for this class was generated from the following files:
/src/sql/kernel/qsqldatabase.h
/src/sql/kernel/qsqldatabase.cpp