Qt 4.8: QFileInfo Class Reference
QFileInfo Class Reference
The QFileInfo class provides system-independent file information.
#include <qfileinfo.h>
Public Functions
QDir absoluteDir () const
Returns the file's absolute path as a QDir object.
QString absoluteFilePath () const
Returns an absolute path including the file name.
QString absolutePath () const
Returns a file's path absolute path.
QString baseName () const
Returns the base name of the file without the path.
QString bundleName () const
Returns the name of the bundle.
bool caching () const
Returns true if caching is enabled; otherwise returns false.
QString canonicalFilePath () const
Returns the canonical path including the file name, i.e.
QString canonicalPath () const
Returns the file's path canonical path (excluding the file name), i.e.
QString completeBaseName () const
Returns the complete base name of the file without the path.
QString completeSuffix () const
Returns the complete suffix of the file.
QDateTime created () const
Returns the date and time when the file was created.
void detach ()
Detaches all internal data.
QDir dir () const
Returns the path of the object's parent directory as a QDir object.
bool exists () const
Returns true if the file exists; otherwise returns false.
QString fileName () const
Returns the name of the file, excluding the path.
QString filePath () const
Returns the file name, including the path (which may be absolute or relative).
QString group () const
Returns the group of the file.
uint groupId () const
Returns the id of the group the file belongs to.
bool isAbsolute () const
Returns true if the file path name is absolute, otherwise returns false if the path is relative.
bool isBundle () const
Returns true if this object points to a bundle or to a symbolic link to a bundle on Mac OS X; otherwise returns false.
bool isDir () const
Returns true if this object points to a directory or to a symbolic link to a directory; otherwise returns false.
bool isExecutable () const
Returns true if the file is executable; otherwise returns false.
bool isFile () const
Returns true if this object points to a file or to a symbolic link to a file.
bool isHidden () const
Returns true if this is a `hidden' file; otherwise returns false.
bool isReadable () const
Returns true if the user can read the file; otherwise returns false.
bool isRelative () const
Returns true if the file path name is relative, otherwise returns false if the path is absolute (e.g.
bool isRoot () const
Returns true if the object points to a directory or to a symbolic link to a directory, and that directory is the root directory; otherwise returns false.
bool isSymLink () const
Returns true if this object points to a symbolic link (or to a shortcut on Windows); otherwise returns false.
bool isWritable () const
Returns true if the user can write to the file; otherwise returns false.
QDateTime lastModified () const
Returns the date and time when the file was last modified.
QDateTime lastRead () const
Returns the date and time when the file was last read (accessed).
bool makeAbsolute ()
Converts the file's path to an absolute path if it is not already in that form.
bool operator!= (const QFileInfo &fileinfo)
Returns true if this QFileInfo object refers to a different file than the one specified by fileinfo; otherwise returns false.
bool operator!= (const QFileInfo &fileinfo) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QFileInfo & operator= (const QFileInfo &fileinfo)
Makes a copy of the given fileinfo and assigns it to this QFileInfo.
bool operator== (const QFileInfo &fileinfo)
Returns true if this QFileInfo object refers to a file in the same location as fileinfo; otherwise returns false.
bool operator== (const QFileInfo &fileinfo) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QString owner () const
Returns the owner of the file.
uint ownerId () const
Returns the id of the owner of the file.
QString path () const
Returns the file's path.
bool permission (QFile::Permissions permissions) const
Tests for file permissions.
QFile::Permissions permissions () const
Returns the complete OR-ed together combination of QFile::Permissions for the file.
QFileInfo (QFileInfoPrivate *d)
QFileInfo ()
Constructs an empty QFileInfo object.
QFileInfo (const QString &file)
Constructs a new QFileInfo that gives information about the given file.
QFileInfo (const QFile &file)
Constructs a new QFileInfo that gives information about file file.
QFileInfo (const QDir &dir, const QString &file)
Constructs a new QFileInfo that gives information about the given file in the directory dir.
QFileInfo (const QFileInfo &fileinfo)
Constructs a new QFileInfo that is a copy of the given fileinfo.
QString readLink () const
Use symLinkTarget() instead.
void refresh ()
Refreshes the information about the file, i.e.
void setCaching (bool on)
If enable is true, enables caching of file information.
void setFile (const QString &file)
Sets the file that the QFileInfo provides information about to file.
void setFile (const QFile &file)
Sets the file that the QFileInfo provides information about to file.
void setFile (const QDir &dir, const QString &file)
Sets the file that the QFileInfo provides information about to file in directory dir.
qint64 size () const
Returns the file size in bytes.
QString suffix () const
Returns the suffix of the file.
QString symLinkTarget () const
Returns the absolute path to the file or directory a symlink (or shortcut on Windows) points to, or a an empty string if the object isn't a symbolic link.
~QFileInfo ()
Destroys the QFileInfo and frees its resources.
Protected Variables
QSharedDataPointer< QFileInfoPrivate > d_ptr
Private Functions
QFileInfoPrivate * d_func ()
const QFileInfoPrivate * d_func () const
Friends
class QDirIteratorPrivate
Related Functions
(Note that these are not member functions.)
QFileInfoList
Synonym for QList<QFileInfo>.
Detailed Description
The QFileInfo class provides system-independent file information.
Note
This class or function is reentrant.
QFileInfo provides information about a file's name and position (path) in the file system, its access rights and whether it is a directory or symbolic link, etc. The file's size and last modified/read times are also available. QFileInfo can also be used to obtain information about a Qt resource system{resource}.
A QFileInfo can point to a file with either a relative or an absolute file path. Absolute file paths begin with the directory separator "/" (or with a drive specification on Windows). Relative file names begin with a directory name or a file name and specify a path relative to the current working directory. An example of an absolute path is the string "/tmp/quartz". A relative path might look like "src/fatlib". You can use the function isRelative() to check whether a QFileInfo is using a relative or an absolute file path. You can call the function makeAbsolute() to convert a relative QFileInfo's path to an absolute path.
The file that the QFileInfo works on is set in the constructor or later with setFile(). Use exists() to see if the file exists and size() to get its size.
The file's type is obtained with isFile(), isDir() and isSymLink(). The symLinkTarget() function provides the name of the file the symlink points to.
On Unix (including Mac OS X), the symlink has the same size() has the file it points to, because Unix handles symlinks transparently; similarly, opening a symlink using QFile effectively opens the link's target. For example:
#ifdef Q_OS_UNIX
QFileInfo info1("/home/bob/bin/untabify");
info1.isSymLink();          // returns true
info1.absoluteFilePath();   // returns "/home/bob/bin/untabify"
info1.size();               // returns 56201
info1.symLinkTarget();      // returns "/opt/pretty++/bin/untabify"
QFileInfo info2(info1.symLinkTarget());
info2.isSymLink();          // returns false
info2.absoluteFilePath();   // returns "/opt/pretty++/bin/untabify"
info2.size();               // returns 56201
#endif
On Windows, symlinks (shortcuts) are .lnk files. The reported size() is that of the symlink (not the link's target), and opening a symlink using QFile opens the .lnk file. For example:
#ifdef Q_OS_WIN
QFileInfo info1("C:\\Documents and Settings\\Bob\\untabify.lnk");
info1.isSymLink();          // returns true
info1.absoluteFilePath();   // returns "C:/Documents and Settings/Bob/untabify.lnk"
info1.size();               // returns 743
info1.symLinkTarget();      // returns "C:/Pretty++/untabify"
QFileInfo info2(info1.symLinkTarget());
info2.isSymLink();          // returns false
info2.absoluteFilePath();   // returns "C:/Pretty++/untabify"
info2.size();               // returns 63942
#endif
Elements of the file's name can be extracted with path() and fileName(). The fileName()'s parts can be extracted with baseName(), suffix() or completeSuffix(). QFileInfo objects to directories created by Qt classes will not have a trailing file separator. If you wish to use trailing separators in your own file info objects, just append one to the file name given to the constructors or setFile().
The file's dates are returned by created(), lastModified() and lastRead(). Information about the file's access permissions is obtained with isReadable(), isWritable() and isExecutable(). The file's ownership is available from owner(), ownerId(), group() and groupId(). You can examine a file's permissions and ownership in a single statement using the permission() function.
Performance Issues
Some of QFileInfo's functions query the file system, but for performance reasons, some functions only operate on the file name itself. For example: To return the absolute path of a relative file name, absolutePath() has to query the file system. The path() function, however, can work on the file name directly, and so it is faster.
Note
To speed up performance, QFileInfo caches information about the file.
To speed up performance, QFileInfo caches information about the file. Because files can be changed by other users or programs, or even by other parts of the same program, there is a function that refreshes the file information: refresh(). If you want to switch off a QFileInfo's caching and force it to access the file system every time you request information from it call setCaching(false).
See also
QDir, QFile
Definition at line 60 of file qfileinfo.h.
Constructors and Destructors
QFileInfo() [1/6]
QFileInfo::QFileInfo (QFileInfoPrivate * p) explicit
Warning
This function is not part of the public interface.
Definition at line 299 of file qfileinfo.cpp.
                                         : d_ptr(p)
 {
 }
QFileInfo() [2/6]
QFileInfo::QFileInfo ()
Constructs an empty QFileInfo object.
Note that an empty QFileInfo object contain no file reference.
See also
setFile()
Definition at line 310 of file qfileinfo.cpp.
Referenced by setFile().
                      : d_ptr(new QFileInfoPrivate())
 {
 }
QFileInfo() [3/6]
QFileInfo::QFileInfo (const QString & file)
Constructs a new QFileInfo that gives information about the given file.
The file can also include an absolute or relative path.
See also
setFile(), isRelative(), QDir::setCurrent(), QDir::isRelativePath()
Definition at line 320 of file qfileinfo.cpp.
                                         : d_ptr(new QFileInfoPrivate(file))
 {
 }
QFileInfo() [4/6]
QFileInfo::QFileInfo (const QFile & file)
Constructs a new QFileInfo that gives information about file file.
If the file has a relative path, the QFileInfo will also have a relative path.
See also
isRelative()
Definition at line 333 of file qfileinfo.cpp.
                                       : d_ptr(new QFileInfoPrivate(file.fileName()))
 {
 }
QFileInfo() [5/6]
QFileInfo::QFileInfo (const QDir & dir, const QString & file)
Constructs a new QFileInfo that gives information about the given file in the directory dir.
If dir has a relative path, the QFileInfo will also have a relative path.
If file is an absolute path, then the directory specified by dir will be disregarded.
See also
isRelative()
Definition at line 349 of file qfileinfo.cpp.
     : d_ptr(new QFileInfoPrivate(dir.filePath(file)))
 {
 }
QFileInfo() [6/6]
QFileInfo::QFileInfo (const QFileInfo & fileinfo)
Constructs a new QFileInfo that is a copy of the given fileinfo.
Definition at line 357 of file qfileinfo.cpp.
     : d_ptr(fileinfo.d_ptr)
 {
 }
~QFileInfo()
QFileInfo::~QFileInfo ()
Destroys the QFileInfo and frees its resources.
Definition at line 367 of file qfileinfo.cpp.
 {
 }
Functions
absoluteDir()
QDir QFileInfo::absoluteDir () const
Returns the file's absolute path as a QDir object.
See also
dir(), filePath(), fileName(), isRelative()
Definition at line 873 of file qfileinfo.cpp.
Referenced by QPollingFileSystemWatcherEngine::FileInfo::FileInfo(), QPollingFileSystemWatcherEngine::FileInfo::operator!=(), and QFileDialog::selectFile().
 {
     return QDir(absolutePath());
 }
absoluteFilePath()
QString QFileInfo::absoluteFilePath () const
Returns an absolute path including the file name.
The absolute path name consists of the full path and the file name. On Unix this will always begin with the root, '/', directory. On Windows this will always begin 'D:/' where D is a drive letter, except for network shares that are not mapped to a drive letter, in which case the path will begin '//sharename/'. QFileInfo will uppercase drive letters. Note that QDir does not do this. The code snippet below shows this.
    QFileInfo fi("c:/temp/foo"); => fi.absoluteFilePath() => "C:/temp/foo"
This function returns the same as filePath(), unless isRelative() is true. In contrast to canonicalFilePath(), symbolic links or redundant "." or ".." elements are not necessarily removed.
If the QFileInfo is empty it returns QDir::currentPath().
See also
filePath(), canonicalFilePath(), isRelative()
Definition at line 534 of file qfileinfo.cpp.
Referenced by _qt_get_directory(), QDeclarativeTypeLoader::absoluteFilePath(), QFileDialog::accept(), QSvgIconEngine::addFile(), QPixmapIconEngine::addFile(), QCoreApplication::applicationFilePath(), QDir::cd(), QDirModelPrivate::children(), QFontEngineQPF::cleanUpAfterClientCrash(), QWSSoundServerPrivate::feedDevice(), QDirModel::fileName(), QDirModel::filePath(), QConfFile::fromName(), QGtkStylePrivate::getFilesystemIcon(), QFileInfoGatherer::getInfo(), QFileIconProvider::icon(), QDeclarativeImportDatabase::importPlugin(), QDirModel::index(), QExtendedInformation::isCaseSensitive(), QFile::link(), QTranslator::load(), QPixmap::load(), makeAbsolute(), QDirModel::mkdir(), QDirModelPrivate::name(), QSvgHandler::processingInstruction(), QDeclarative_isFileCaseCorrect(), qt_create_commandline(), qt_win_get_open_file_name(), qt_win_get_open_file_names(), qt_win_get_save_file_name(), registerFont(), QDirModel::remove(), QDirModelPrivate::resolvedInfo(), QDeclarativeImportDatabase::resolvePlugin(), QDirModel::rmdir(), QPluginLoader::setFileName(), QProcessPrivate::startProcess(), and QFileInfoGatherer::translateDriveName().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->getFileName(QAbstractFileEngine::AbsoluteName);
 }
absolutePath()
QString QFileInfo::absolutePath () const
Returns a file's path absolute path.
This doesn't include the file name.
On Unix the absolute path will always begin with the root, '/', directory. On Windows this will always begin 'D:/' where D is a drive letter, except for network shares that are not mapped to a drive letter, in which case the path will begin '//sharename/'.
In contrast to canonicalPath() symbolic links or redundant "." or ".." elements are not necessarily removed.
Warning
If the QFileInfo object was created with an empty QString, the behavior of this function is undefined.
See also
absoluteFilePath(), path(), canonicalPath(), fileName(), isRelative()
Definition at line 577 of file qfileinfo.cpp.
Referenced by _qt_get_directory(), absoluteDir(), dlIterateCallback(), QZipReader::extractAll(), QCss::Parser::init(), QUrl::isParentOf(), QConfFile::isWritable(), QLibraryInfo::location(), qt_win_get_open_file_name(), qt_win_get_open_file_names(), qt_win_get_save_file_name(), QDirModelPrivate::resolvedInfo(), QAxFactory::serverDirPath(), QPluginLoader::setFileName(), QGtkStylePrivate::setupGtkFileChooser(), and QFileSystemEngine::slowCanonicalized().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed) {
         return QLatin1String("");
     } else if (d->fileEntry.isEmpty()) {
         qWarning("QFileInfo::absolutePath: Constructed with empty filename");
         return QLatin1String("");
     }
     return d->getFileName(QAbstractFileEngine::AbsolutePathName);
 }
baseName()
QString QFileInfo::baseName () const
Returns the base name of the file without the path.
Use completeBaseName() or the baseName() overload that takes no parameters instead.
The base name consists of all characters in the file up to (but not including) the first '.' character.
Example:
QFileInfo fi("/tmp/archive.tar.gz");
QString base = fi.baseName();  // base = "archive"
The base name of a file is computed equally on all platforms, independent of file naming conventions (e.g., ".bashrc" on Unix has an empty base name, and the suffix is "bashrc").
See also
fileName(), suffix(), completeSuffix(), completeBaseName()
Definition at line 773 of file qfileinfo.cpp.
Referenced by QCoreApplicationPrivate::appName(), and QScriptEnginePrivate::translationContextFromUrl().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->fileEntry.baseName();
 }
bundleName()
QString QFileInfo::bundleName () const
Returns the name of the bundle.
Since
4.3
On Mac OS X this returns the proper localized name for a bundle if the path isBundle(). On all other platforms an empty QString is returned.
Example:
QFileInfo fi("/Applications/Safari.app");
QString bundle = fi.bundleName();                // name = "Safari"
See also
isBundle(), filePath(), baseName(), extension()
Definition at line 749 of file qfileinfo.cpp.
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->getFileName(QAbstractFileEngine::BundleName);
 }
caching()
bool QFileInfo::caching () const
Returns true if caching is enabled; otherwise returns false.
See also
setCaching(), refresh()
Definition at line 1346 of file qfileinfo.cpp.
Referenced by setFile().
 {
     Q_D(const QFileInfo);
     return d->cache_enabled;
 }
canonicalFilePath()
QString QFileInfo::canonicalFilePath () const
Returns the canonical path including the file name, i.e.
an absolute path without symbolic links or redundant "." or ".." elements.
If the file does not exist, canonicalFilePath() returns an empty string.
See also
filePath(), absoluteFilePath(), dir()
Definition at line 551 of file qfileinfo.cpp.
Referenced by QFileDialogPrivate::_q_updateOkButton(), QFSEventsFileSystemWatcherEngine::addPaths(), QCoreApplication::applicationFilePath(), QScriptEngine::availableExtensions(), QDirIteratorPrivate::checkAndPushDirectory(), QFileSystemModel::filePath(), QFileInfoGatherer::getInfo(), QFileIconProviderPrivate::getWinIcon(), QScriptEngine::importExtension(), QTranslator::load(), operator==(), QDirIteratorPrivate::pushDirectory(), QDeclarative_isFileCaseCorrect(), QFSEventsFileSystemWatcherEngine::removePaths(), QPluginLoader::setFileName(), and QSslSocketPrivate::systemCaCertificates().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->getFileName(QAbstractFileEngine::CanonicalName);
 }
canonicalPath()
QString QFileInfo::canonicalPath () const
Returns the file's path canonical path (excluding the file name), i.e.
an absolute path without symbolic links or redundant "." or ".." elements.
If the file does not exist, canonicalPath() returns an empty string.
See also
path(), absolutePath()
Definition at line 598 of file qfileinfo.cpp.
Referenced by QDnotifyFileSystemWatcherEngine::addPaths(), QFSEventsFileSystemWatcherEngine::addPaths(), and QFSEventsFileSystemWatcherEngine::removePaths().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->getFileName(QAbstractFileEngine::CanonicalPathName);
 }
completeBaseName()
QString QFileInfo::completeBaseName () const
Returns the complete base name of the file without the path.
The complete base name consists of all characters in the file up to (but not including) the last '.' character.
Example:
QFileInfo fi("/tmp/archive.tar.gz");
QString base = fi.completeBaseName();  // base = "archive.tar"
See also
fileName(), suffix(), completeSuffix(), baseName()
Definition at line 792 of file qfileinfo.cpp.
Referenced by QFileDialogPrivate::qt_mac_filedialog_event_proc().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->fileEntry.completeBaseName();
 }
completeSuffix()
QString QFileInfo::completeSuffix () const
Returns the complete suffix of the file.
The complete suffix consists of all characters in the file after (but not including) the first '.'.
Example:
QFileInfo fi("/tmp/archive.tar.gz");
QString ext = fi.completeSuffix();  // ext = "tar.gz"
See also
fileName(), suffix(), baseName(), completeBaseName()
Definition at line 811 of file qfileinfo.cpp.
Referenced by QLibrary::isLibrary(), QPixmap::load(), and loadOpenSslWin32().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->fileEntry.completeSuffix();
 }
created()
QDateTime QFileInfo::created () const
Returns the date and time when the file was created.
On most Unix systems, this function returns the time of the last status change. A status change occurs when the file is created, but it also occurs whenever the user writes or sets inode information (for example, changing the file permissions).
If neither creation time nor "last status change" time are not available, returns the same as lastModified().
See also
lastModified() lastRead()
Definition at line 1278 of file qfileinfo.cpp.
Referenced by QNetworkDiskCache::expire(), and qt_CoCreateGuid().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QDateTime();
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::CreationTime))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::CreationTime);
         return d->metaData.creationTime();
     }
     return d->getFileTime(QAbstractFileEngine::CreationTime);
 }
d_func() [1/2]
QFileInfoPrivate* QFileInfo::d_func () inline private
Definition at line 179 of file qfileinfo.h.
     {
         detach();
         return const_cast<QFileInfoPrivate *>(d_ptr.constData());
     }
d_func() [2/2]
const QFileInfoPrivate* QFileInfo::d_func () const inline private
Definition at line 185 of file qfileinfo.h.
     {
         return d_ptr.constData();
     }
detach()
void QFileInfo::detach ()
Detaches all internal data.
Warning
This function is not part of the public interface.
Definition at line 1336 of file qfileinfo.cpp.
 {
     d_ptr.detach();
 }
dir()
QDir QFileInfo::dir () const
Returns the path of the object's parent directory as a QDir object.
Note: The QDir returned always corresponds to the object's parent directory, even if the QFileInfo represents a directory.
For each of the following, dir() returns a QDir for "~/examples/191697".
    QFileInfo fileInfo1("~/examples/191697/.");
    QFileInfo fileInfo2("~/examples/191697/..");
    QFileInfo fileInfo3("~/examples/191697/main.cpp");
For each of the following, dir() returns a QDir for ".".
    QFileInfo fileInfo4(".");
    QFileInfo fileInfo5("..");
    QFileInfo fileInfo6("main.cpp");
See also
absolutePath(), filePath(), fileName(), isRelative(), absoluteDir()
Definition at line 861 of file qfileinfo.cpp.
Referenced by absoluteDir(), QDeclarativeImportsPrivate::importExtension(), QDirModel::remove(), QDirModel::rmdir(), and QDirModel::setData().
 {
     Q_D(const QFileInfo);
     // ### Qt5: Maybe rename this to parentDirectory(), considering what it actually do?
     return QDir(d->fileEntry.path());
 }
exists()
bool QFileInfo::exists () const
Returns true if the file exists; otherwise returns false.
Note
If the file is a symlink that points to a non existing file, false is returned.
Definition at line 675 of file qfileinfo.cpp.
Referenced by _qt_get_directory(), QFileDialog::accept(), QDnotifyFileSystemWatcherEngine::addPaths(), QFSEventsFileSystemWatcherEngine::addPaths(), QPollingFileSystemWatcherEngine::addPaths(), QmlApplicationViewerPrivate::adjustPath(), QCoreApplication::applicationFilePath(), QUnixPrintWidgetPrivate::checkFields(), QFile::exists(), QFileSystemModel::filePath(), QFileInfoGatherer::getInfo(), QDirModel::index(), QLibraryPrivate::isPlugin(), QConfFile::isWritable(), QPixmap::load(), QDirIteratorPrivate::matchesFilters(), QFileSystemModelPrivate::node(), QSvgHandler::processingInstruction(), qt_win_get_open_file_name(), qt_win_get_open_file_names(), qt_win_get_save_file_name(), QDnotifyFileSystemWatcherEngine::refresh(), QDeclarativeImportDatabase::resolvePlugin(), resolveScheme(), QWidgetPrivate::setWindowTitle_sys(), QExtendedInformation::size(), QPollingFileSystemWatcherEngine::timeout(), and QExtendedInformation::type().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return false;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::ExistsAttribute))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::ExistsAttribute);
         return d->metaData.exists();
     }
     return d->getFileFlags(QAbstractFileEngine::ExistsFlag);
 }
fileName()
QString QFileInfo::fileName () const
Returns the name of the file, excluding the path.
Example:
QFileInfo fi("/tmp/archive.tar.gz");
QString name = fi.fileName();                // name = "archive.tar.gz"
Note that, if this QFileInfo object is given a path ending in a slash, the name of the file is considered empty.
See also
isRelative(), filePath(), baseName(), extension()
Definition at line 726 of file qfileinfo.cpp.
Referenced by QFileDialogPrivate::_q_updateOkButton(), QFileDialog::accept(), QDirIteratorPrivate::checkAndPushDirectory(), QBenchmarkValgrindUtils::cleanup(), constructWindowTitleFromFilePath(), QFSFileEngineIterator::currentFileName(), QNetworkDiskCache::expire(), QFileInfoGatherer::fetch(), QDirIterator::fileName(), QDirModel::fileName(), QFileInfoGatherer::getFileInfos(), QBenchmarkValgrindUtils::getNewestFileName(), QDirModel::index(), QFileDialogPrivate::initialSelection(), QUrl::isParentOf(), QDeclarativeDebugServerPrivate::loadConnectionPlugin(), QScriptDebuggerConsolePrivate::loadScriptedCommands(), QDirModelPrivate::name(), QDirSortItemComparator::operator()(), QNSOpenSavePanelDelegate::panel:shouldShowFilename:, QFontEngineQPF::QFontEngineQPF(), qt_parseEtcLpMember(), qt_parseEtcLpPrinters(), qt_parseSpoolInterface(), qt_win_get_open_file_name(), qt_win_get_save_file_name(), QNetworkDiskCachePrivate::removeFile(), QNSOpenSavePanelDelegate::runApplicationModalPanel, QDirModel::setData(), QPluginLoader::setFileName(), QGtkStylePrivate::setupGtkFileChooser(), QDirPrivate::sortFileList(), and QFileInfoGatherer::translateDriveName().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->fileEntry.fileName();
 }
filePath()
QString QFileInfo::filePath () const
Returns the file name, including the path (which may be absolute or relative).
See also
absoluteFilePath(), canonicalFilePath(), isRelative()
Definition at line 707 of file qfileinfo.cpp.
Referenced by QDnotifyFileSystemWatcherEngine::addPaths(), QCoreApplication::applicationFilePath(), QAbstractFileEngineIterator::currentFileInfo(), QDirIterator::filePath(), QFileSystemModel::filePath(), QFileInfoGatherer::getInfo(), QFileIconProviderPrivate::getWinIcon(), QUrl::isParentOf(), QDirIteratorPrivate::pushDirectory(), qt_parseSpoolInterface(), QNSOpenSavePanelDelegate::runApplicationModalPanel, and QFileDialogPrivate::selectFile_sys().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->fileEntry.filePath();
 }
group()
QString QFileInfo::group () const
Returns the group of the file.
On Windows, on systems where files do not have groups, or if an error occurs, an empty string is returned.
This function can be time consuming under Unix (in the order of milliseconds).
See also
groupId(), owner(), ownerId()
Definition at line 1167 of file qfileinfo.cpp.
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->getFileOwner(QAbstractFileEngine::OwnerGroup);
 }
groupId()
uint QFileInfo::groupId () const
Returns the id of the group the file belongs to.
On Windows and on systems where files do not have groups this function always returns (uint) -2.
See also
group(), owner(), ownerId()
Definition at line 1183 of file qfileinfo.cpp.
Referenced by QPollingFileSystemWatcherEngine::FileInfo::operator!=(), QWindowsFileSystemWatcherEngine::PathInfo::operator!=(), QWindowsFileSystemWatcherEngine::PathInfo::operator=(), and QDnotifyFileSystemWatcherEngine::Directory::File::updateInfo().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return 0;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::GroupId))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::GroupId);
         return d->metaData.groupId();
     }
     return d->fileEngine->ownerId(QAbstractFileEngine::OwnerGroup);
 }
isAbsolute()
bool QFileInfo::isAbsolute () const inline
Returns true if the file path name is absolute, otherwise returns false if the path is relative.
See also
isRelative()
Definition at line 111 of file qfileinfo.h.
Referenced by QUrl::isParentOf(), and QFileDialog::selectFile().
 { return !isRelative(); }
isBundle()
bool QFileInfo::isBundle () const
Returns true if this object points to a bundle or to a symbolic link to a bundle on Mac OS X; otherwise returns false.
Since
4.3
See also
isDir(), isSymLink(), isFile()
Definition at line 1014 of file qfileinfo.cpp.
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return false;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::BundleType))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::BundleType);
         return d->metaData.isBundle();
     }
     return d->getFileFlags(QAbstractFileEngine::BundleType);
 }
isDir()
bool QFileInfo::isDir () const
Returns true if this object points to a directory or to a symbolic link to a directory; otherwise returns false.
See also
isFile(), isSymLink(), isBundle()
Definition at line 990 of file qfileinfo.cpp.
Referenced by QCompleterPrivate::_q_complete(), QFileDialogPrivate::_q_updateOkButton(), _qt_get_directory(), QFileDialog::accept(), QInotifyFileSystemWatcherEngine::addPaths(), QDnotifyFileSystemWatcherEngine::addPaths(), QWindowsFileSystemWatcherEngine::addPaths(), QFSEventsFileSystemWatcherEngine::addPaths(), QPollingFileSystemWatcherEngine::addPaths(), QCoreApplication::applicationFilePath(), QDirIteratorPrivate::checkAndPushDirectory(), QUnixPrintWidgetPrivate::checkFields(), QDirModelPrivate::children(), QPollingFileSystemWatcherEngine::FileInfo::FileInfo(), QDirModel::flags(), QFileIconProviderPrivate::getWinIcon(), QDirModel::hasChildren(), QFileIconProvider::icon(), QFileDialogPrivate::initialSelection(), QFileSystemModel::isDir(), QNetworkAccessFileBackend::loadFileInfo(), QDirIteratorPrivate::matchesFilters(), QDirModelPrivate::node(), QPollingFileSystemWatcherEngine::FileInfo::operator!=(), QDirSortItemComparator::operator()(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), qt_getLprPrinters(), qt_parseEtcLpPrinters(), qt_win_get_open_file_name(), qt_win_get_open_file_names(), qt_win_get_save_file_name(), QDirModel::remove(), QDirModel::rmdir(), QDirModel::rowCount(), QGtkStylePrivate::setupGtkFileChooser(), QDirModelPrivate::size(), QFileSystemEngine::slowCanonicalized(), QProcessPrivate::startProcess(), QFileIconProvider::type(), and QExtendedInformation::type().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return false;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::DirectoryType))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::DirectoryType);
         return d->metaData.isDirectory();
     }
     return d->getFileFlags(QAbstractFileEngine::DirectoryType);
 }
isExecutable()
bool QFileInfo::isExecutable () const
Returns true if the file is executable; otherwise returns false.
See also
isReadable(), isWritable(), permission()
Definition at line 932 of file qfileinfo.cpp.
Referenced by QFileIconProviderPrivate::getWinIcon(), and QDirIteratorPrivate::matchesFilters().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return false;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::UserExecutePermission))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::UserExecutePermission);
         return (d->metaData.permissions() & QFile::ExeUser) != 0;
     }
     return d->getFileFlags(QAbstractFileEngine::ExeUserPerm);
 }
isFile()
bool QFileInfo::isFile () const
Returns true if this object points to a file or to a symbolic link to a file.
Returns false if the object points to something which isn't a file, such as a directory.
See also
isDir(), isSymLink(), isBundle()
Definition at line 971 of file qfileinfo.cpp.
Referenced by QDeclarativeTypeLoader::absoluteFilePath(), find_translation(), QFileIconProviderPrivate::getWinIcon(), QFileIconProvider::icon(), isCacheable(), QTranslator::load(), QDirIteratorPrivate::matchesFilters(), qt_getLprPrinters(), qt_parseEtcLpMember(), qt_parseSpoolInterface(), QFileIconProvider::type(), and QExtendedInformation::type().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return false;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::FileType))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::FileType);
         return d->metaData.isFile();
     }
     return d->getFileFlags(QAbstractFileEngine::FileType);
 }
isHidden()
bool QFileInfo::isHidden () const
Returns true if this is a `hidden' file; otherwise returns false.
Note: This function returns true for the special entries "." and ".." on Unix, even though QDir::entryList threats them as shown.
Definition at line 951 of file qfileinfo.cpp.
Referenced by QDirIteratorPrivate::checkAndPushDirectory(), QExtendedInformation::isHidden(), and QDirIteratorPrivate::matchesFilters().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return false;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::HiddenAttribute))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::HiddenAttribute);
         return d->metaData.isHidden();
     }
     return d->getFileFlags(QAbstractFileEngine::HiddenFlag);
 }
isReadable()
bool QFileInfo::isReadable () const
Returns true if the user can read the file; otherwise returns false.
See also
isWritable(), isExecutable(), permission()
Definition at line 896 of file qfileinfo.cpp.
Referenced by find_translation(), QFileInfoGatherer::getInfo(), QTranslator::load(), and QDirIteratorPrivate::matchesFilters().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return false;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::UserReadPermission))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::UserReadPermission);
         return (d->metaData.permissions() & QFile::ReadUser) != 0;
     }
     return d->getFileFlags(QAbstractFileEngine::ReadUserPerm);
 }
isRelative()
bool QFileInfo::isRelative () const
Returns true if the file path name is relative, otherwise returns false if the path is absolute (e.g.
under Unix a path is absolute if it begins with a "/").
See also
isAbsolute()
Definition at line 642 of file qfileinfo.cpp.
Referenced by QDir::isRelativePath().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return true;
     if (d->fileEngine == 0)
         return d->fileEntry.isRelative();
     return d->fileEngine->isRelativePath();
 }
isRoot()
bool QFileInfo::isRoot () const
Returns true if the object points to a directory or to a symbolic link to a directory, and that directory is the root directory; otherwise returns false.
Definition at line 1062 of file qfileinfo.cpp.
Referenced by QDirModel::fileName(), QFileIconProviderPrivate::getWinIcon(), QFileIconProvider::icon(), QDirModel::index(), QDirModelPrivate::name(), and QFileIconProvider::type().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return true;
     if (d->fileEngine == 0) {
         if (d->fileEntry.isRoot()) {
 #if defined(Q_OS_WIN) || defined(Q_OS_SYMBIAN)
             //the path is a drive root, but the drive may not exist
             //for backward compatibility, return true only if the drive exists
             if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::ExistsAttribute))
                 QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::ExistsAttribute);
             return d->metaData.exists();
 #else
             return true;
 #endif
         }
         return false;
     }
     return d->getFileFlags(QAbstractFileEngine::RootFlag);
 }
isSymLink()
bool QFileInfo::isSymLink () const
Returns true if this object points to a symbolic link (or to a shortcut on Windows); otherwise returns false.
On Unix (including Mac OS X), opening a symlink effectively opens the link's target. On Windows, it opens the .lnk file itself.
Example:
QFileInfo info(fileName);
if (info.isSymLink())
    fileName = info.symLinkTarget();
Note
If the symlink points to a non existing file, exists() returns false.
See also
isFile(), isDir(), symLinkTarget()
Definition at line 1044 of file qfileinfo.cpp.
Referenced by QCoreApplication::applicationFilePath(), QDirIteratorPrivate::checkAndPushDirectory(), QDirModelPrivate::children(), QDirModel::fileName(), QDirModel::filePath(), QFileInfoGatherer::getInfo(), QFileIconProviderPrivate::getWinIcon(), QFileIconProvider::icon(), QExtendedInformation::isSymLink(), QDirIteratorPrivate::matchesFilters(), QDirIteratorPrivate::pushDirectory(), QDirModelPrivate::resolvedInfo(), runningUnderDebugger(), QExtendedInformation::size(), QFileSystemEngine::slowCanonicalized(), QFileIconProvider::type(), and QExtendedInformation::type().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return false;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::LegacyLinkType))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::LegacyLinkType);
         return d->metaData.isLegacyLink();
     }
     return d->getFileFlags(QAbstractFileEngine::LinkType);
 }
isWritable()
bool QFileInfo::isWritable () const
Returns true if the user can write to the file; otherwise returns false.
See also
isReadable(), isExecutable(), permission()
Definition at line 914 of file qfileinfo.cpp.
Referenced by QUnixPrintWidgetPrivate::checkFields(), QDirModel::flags(), and QDirIteratorPrivate::matchesFilters().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return false;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::UserWritePermission))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::UserWritePermission);
         return (d->metaData.permissions() & QFile::WriteUser) != 0;
     }
     return d->getFileFlags(QAbstractFileEngine::WriteUserPerm);
 }
lastModified()
QDateTime QFileInfo::lastModified () const
Returns the date and time when the file was last modified.
See also
created() lastRead()
Definition at line 1296 of file qfileinfo.cpp.
Referenced by QDnotifyFileSystemWatcherEngine::addPaths(), QMacPasteboardMimeVCard::convertFromMime(), QLibraryPrivate::isPlugin(), QExtendedInformation::lastModified(), QPixmap::load(), QNetworkAccessFileBackend::loadFileInfo(), QFontDatabasePrivate::loadFromCache(), QPollingFileSystemWatcherEngine::FileInfo::operator!=(), QWindowsFileSystemWatcherEngine::PathInfo::operator!=(), QDirSortItemComparator::operator()(), QWindowsFileSystemWatcherEngine::PathInfo::operator=(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), QConfFileSettingsPrivate::syncConfFile(), and QDnotifyFileSystemWatcherEngine::Directory::File::updateInfo().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QDateTime();
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::ModificationTime))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::ModificationTime);
         return d->metaData.modificationTime();
     }
     return d->getFileTime(QAbstractFileEngine::ModificationTime);
 }
lastRead()
QDateTime QFileInfo::lastRead () const
Returns the date and time when the file was last read (accessed).
On platforms where this information is not available, returns the same as lastModified().
See also
created() lastModified()
Definition at line 1317 of file qfileinfo.cpp.
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QDateTime();
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::AccessTime))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::AccessTime);
         return d->metaData.accessTime();
     }
     return d->getFileTime(QAbstractFileEngine::AccessTime);
 }
makeAbsolute()
bool QFileInfo::makeAbsolute ()
Converts the file's path to an absolute path if it is not already in that form.
Returns true to indicate that the path was converted; otherwise returns false to indicate that the path was already absolute.
See also
filePath(), isRelative()
Definition at line 659 of file qfileinfo.cpp.
Referenced by QGtkStylePrivate::setupGtkFileChooser().
 {
     if (d_ptr.constData()->isDefaultConstructed
             || !d_ptr.constData()->fileEntry.isRelative())
         return false;
     setFile(absoluteFilePath());
     return true;
 }
operator!=() [1/2]
bool QFileInfo::operator!= (const QFileInfo & fileinfo) inline
Returns true if this QFileInfo object refers to a different file than the one specified by fileinfo; otherwise returns false.
See also
operator==()
Definition at line 80 of file qfileinfo.h.
 { return !(operator==(fileinfo)); } // 5.0 - remove me
operator!=() [2/2]
bool QFileInfo::operator!= (const QFileInfo & fileinfo) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 81 of file qfileinfo.h.
 { return !(operator==(fileinfo)); }
operator=()
QFileInfo & QFileInfo::operator= (const QFileInfo & fileinfo)
Makes a copy of the given fileinfo and assigns it to this QFileInfo.
Definition at line 447 of file qfileinfo.cpp.
 {
     d_ptr = fileinfo.d_ptr;
     return *this;
 }
operator==() [1/2]
bool QFileInfo::operator== (const QFileInfo & fileinfo)
Returns true if this QFileInfo object refers to a file in the same location as fileinfo; otherwise returns false.
Note that the result of comparing two empty QFileInfo objects, containing no file references, is undefined.
Warning
This will not compare two different symbolic links pointing to the same file.
Long and short file names that refer to the same file on Windows are treated as if they referred to different files.
See also
operator!=()
Definition at line 439 of file qfileinfo.cpp.
 {
     return const_cast<const QFileInfo *>(this)->operator==(fileinfo);
 }
operator==() [2/2]
bool QFileInfo::operator== (const QFileInfo & fileinfo) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 391 of file qfileinfo.cpp.
 {
     Q_D(const QFileInfo);
     // ### Qt 5: understand long and short file names on Windows
     // ### (GetFullPathName()).
     if (fileinfo.d_ptr == d_ptr)
         return true;
     if (d->isDefaultConstructed || fileinfo.d_ptr->isDefaultConstructed)
         return false;
     // Assume files are the same if path is the same
     if (d->fileEntry.filePath() == fileinfo.d_ptr->fileEntry.filePath())
         return true;
     Qt::CaseSensitivity sensitive;
     if (d->fileEngine == 0 || fileinfo.d_ptr->fileEngine == 0) {
         if (d->fileEngine != fileinfo.d_ptr->fileEngine) // one is native, the other is a custom file-engine
             return false;
         sensitive = QFileSystemEngine::isCaseSensitive() ? Qt::CaseSensitive : Qt::CaseInsensitive;
     } else {
         if (d->fileEngine->caseSensitive() != fileinfo.d_ptr->fileEngine->caseSensitive())
             return false;
         sensitive = d->fileEngine->caseSensitive() ? Qt::CaseSensitive : Qt::CaseInsensitive;
     }
     if (fileinfo.size() != size()) //if the size isn't the same...
         return false;
    // Fallback to expensive canonical path computation
    return canonicalFilePath().compare(fileinfo.canonicalFilePath(), sensitive) == 0;
 }
owner()
QString QFileInfo::owner () const
Returns the owner of the file.
On systems where files do not have owners, or if an error occurs, an empty string is returned.
This function can be time consuming under Unix (in the order of milliseconds).
See also
ownerId(), group(), groupId()
Definition at line 1128 of file qfileinfo.cpp.
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->getFileOwner(QAbstractFileEngine::OwnerUser);
 }
ownerId()
uint QFileInfo::ownerId () const
Returns the id of the owner of the file.
On Windows and on systems where files do not have owners this function returns ((uint) -2).
See also
owner(), group(), groupId()
Definition at line 1144 of file qfileinfo.cpp.
Referenced by QPollingFileSystemWatcherEngine::FileInfo::operator!=(), QWindowsFileSystemWatcherEngine::PathInfo::operator!=(), QWindowsFileSystemWatcherEngine::PathInfo::operator=(), and QDnotifyFileSystemWatcherEngine::Directory::File::updateInfo().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return 0;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::UserId))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::UserId);
         return d->metaData.userId();
     }
     return d->fileEngine->ownerId(QAbstractFileEngine::OwnerUser);
 }
path()
QString QFileInfo::path () const
Returns the file's path.
This doesn't include the file name.
Note that, if this QFileInfo object is given a path ending in a slash, the name of the file is considered empty and this function will return the entire path.
See also
filePath(), absolutePath(), canonicalPath(), dir(), fileName(), isRelative()
Definition at line 615 of file qfileinfo.cpp.
Referenced by QFileDialog::accept(), QCoreApplication::applicationDirPath(), QUrl::isParentOf(), QSystemLibrary::load(), qt_win_get_open_file_name(), qt_win_get_open_file_names(), and qt_win_get_save_file_name().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->fileEntry.path();
 }
permission()
bool QFileInfo::permission (QFile::Permissions permissions) const
Tests for file permissions.
Use permission() instead.
The permissions argument can be several flags of type QFile::Permissions OR-ed together to check for permission combinations.
On systems where files do not have permissions this function always returns true.
Example:
QFileInfo fi("/tmp/archive.tar.gz");
if (fi.permission(QFile::WriteUser | QFile::ReadGroup))
    qWarning("I can change the file; my group can read the file");
if (fi.permission(QFile::WriteGroup | QFile::WriteOther))
    qWarning("The group or others can change the file");
See also
isReadable(), isWritable(), isExecutable()
Definition at line 1209 of file qfileinfo.cpp.
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return false;
     if (d->fileEngine == 0) {
         // the QFileSystemMetaData::MetaDataFlag and QFile::Permissions overlap, so just static cast.
         QFileSystemMetaData::MetaDataFlag permissionFlags = static_cast<QFileSystemMetaData::MetaDataFlag>((int)permissions);
         if (!d->cache_enabled || !d->metaData.hasFlags(permissionFlags))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, permissionFlags);
         return (d->metaData.permissions() & permissions) == permissions;
     }
     return d->getFileFlags(QAbstractFileEngine::FileFlags((int)permissions)) == (uint)permissions;
 }
permissions()
QFile::Permissions QFileInfo::permissions () const
Returns the complete OR-ed together combination of QFile::Permissions for the file.
Definition at line 1228 of file qfileinfo.cpp.
Referenced by QPollingFileSystemWatcherEngine::FileInfo::operator!=(), QWindowsFileSystemWatcherEngine::PathInfo::operator!=(), QWindowsFileSystemWatcherEngine::PathInfo::operator=(), permission(), QExtendedInformation::permissions(), and QDnotifyFileSystemWatcherEngine::Directory::File::updateInfo().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return 0;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::Permissions))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::Permissions);
         return d->metaData.permissions();
     }
     return QFile::Permissions(d->getFileFlags(QAbstractFileEngine::PermsMask) & QAbstractFileEngine::PermsMask);
 }
readLink()
QString QFileInfo::readLink () const
Use symLinkTarget() instead.
Definition at line 1110 of file qfileinfo.cpp.
Referenced by QFile::readLink().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->getFileName(QAbstractFileEngine::LinkName);
 }
refresh()
void QFileInfo::refresh ()
Refreshes the information about the file, i.e.
reads in information from the file system the next time a cached property is fetched.
Note
On Windows CE, there might be a delay for the file system driver to detect changes on the file.
Definition at line 695 of file qfileinfo.cpp.
Referenced by QPollingFileSystemWatcherEngine::timeout().
 {
     Q_D(QFileInfo);
     d->clear();
 }
setCaching()
void QFileInfo::setCaching (bool enable)
If enable is true, enables caching of file information.
If enable is false caching is disabled.
When caching is enabled, QFileInfo reads the file information from the file system the first time it's needed, but generally not later.
Caching is enabled by default.
See also
refresh(), caching()
Definition at line 1364 of file qfileinfo.cpp.
Referenced by QDirModelPrivate::appendChild().
 {
     Q_D(QFileInfo);
     d->cache_enabled = enable;
 }
setFile() [1/3]
void QFileInfo::setFile (const QString & file)
Sets the file that the QFileInfo provides information about to file.
The file can also include an absolute or relative file path. Absolute paths begin with the directory separator (e.g. "/" under Unix) or a drive specification (under Windows). Relative file names begin with a directory name or a file name and specify a path relative to the current directory.
Example:
QString absolute = "/local/bin";
QString relative = "local/bin";
QFileInfo absFile(absolute);
QFileInfo relFile(relative);
QDir::setCurrent(QDir::rootPath());
// absFile and relFile now point to the same file
QDir::setCurrent("/tmp");
// absFile now points to "/local/bin",
// while relFile points to "/tmp/local/bin"
See also
isRelative(), QDir::setCurrent(), QDir::isRelativePath()
Definition at line 468 of file qfileinfo.cpp.
Referenced by _qt_get_directory(), QAbstractFileEngineIterator::currentFileInfo(), find_translation(), QFileInfoGatherer::getFileInfos(), QUrl::isParentOf(), QTranslator::load(), makeAbsolute(), qt_getLprPrinters(), qt_win_get_open_file_names(), QDirModelPrivate::resolvedInfo(), setFile(), QGtkStylePrivate::setupGtkFileChooser(), and QFileSystemEngine::slowCanonicalized().
 {
     bool caching = d_ptr.constData()->cache_enabled;
     *this = QFileInfo(file);
     d_ptr->cache_enabled = caching;
 }
setFile() [2/3]
void QFileInfo::setFile (const QFile & file)
Sets the file that the QFileInfo provides information about to file.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If file includes a relative path, the QFileInfo will also have a relative path.
See also
isRelative()
Definition at line 489 of file qfileinfo.cpp.
 {
     setFile(file.fileName());
 }
setFile() [3/3]
void QFileInfo::setFile (const QDir & dir, const QString & file)
Sets the file that the QFileInfo provides information about to file in directory dir.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If file includes a relative path, the QFileInfo will also have a relative path.
See also
isRelative()
Definition at line 508 of file qfileinfo.cpp.
 {
     setFile(dir.filePath(file));
 }
size()
qint64 QFileInfo::size () const
Returns the file size in bytes.
If the file does not exist or cannot be fetched, 0 is returned.
See also
exists()
Definition at line 1248 of file qfileinfo.cpp.
Referenced by QNetworkDiskCache::expire(), QPixmap::load(), QNetworkAccessFileBackend::loadFileInfo(), QDirSortItemComparator::operator()(), operator==(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), QNetworkDiskCachePrivate::removeFile(), QDirModelPrivate::size(), QExtendedInformation::size(), and QConfFileSettingsPrivate::syncConfFile().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return 0;
     if (d->fileEngine == 0) {
         if (!d->cache_enabled || !d->metaData.hasFlags(QFileSystemMetaData::SizeAttribute))
             QFileSystemEngine::fillMetaData(d->fileEntry, d->metaData, QFileSystemMetaData::SizeAttribute);
         return d->metaData.size();
     }
     if (!d->getCachedFlag(QFileInfoPrivate::CachedSize)) {
         d->setCachedFlag(QFileInfoPrivate::CachedSize);
         d->fileSize = d->fileEngine->size();
     }
     return d->fileSize;
 }
suffix()
QString QFileInfo::suffix () const
Returns the suffix of the file.
The suffix consists of all characters in the file after (but not including) the last '.'.
Example:
QFileInfo fi("/tmp/archive.tar.gz");
QString ext = fi.suffix();  // ext = "gz"
The suffix of a file is computed equally on all platforms, independent of file naming conventions (e.g., ".bashrc" on Unix has an empty base name, and the suffix is "bashrc").
See also
fileName(), completeSuffix(), baseName(), completeBaseName()
Definition at line 834 of file qfileinfo.cpp.
Referenced by QPrintPreviewDialogPrivate::_q_print(), QUnixPrintWidgetPrivate::_q_printerChanged(), QFileDialogPrivate::_q_useNameFilter(), QIcon::addFile(), QFileIconProviderPrivate::getWinIcon(), isCacheable(), QExtendedInformation::isSymLink(), QDirSortItemComparator::operator()(), QPluginLoader::setFileName(), QPrinter::setOutputFileName(), and QFileIconProvider::type().
 {
     Q_D(const QFileInfo);
     if (d->isDefaultConstructed)
         return QLatin1String("");
     return d->fileEntry.suffix();
 }
symLinkTarget()
QString QFileInfo::symLinkTarget () const inline
Returns the absolute path to the file or directory a symlink (or shortcut on Windows) points to, or a an empty string if the object isn't a symbolic link.
Since
4.2
This name may not represent an existing file; it is only a string. QFileInfo::exists() returns true if the symlink points to an existing file.
See also
exists(), isSymLink(), isDir(), isFile()
Definition at line 121 of file qfileinfo.h.
Referenced by QDirModelPrivate::children(), QFileInfoGatherer::getInfo(), QDirModelPrivate::resolvedInfo(), runningUnderDebugger(), and QFileSystemEngine::slowCanonicalized().
 { return readLink(); }
Friends and Related Functions
QDirIteratorPrivate
friend class QDirIteratorPrivate friend
Definition at line 62 of file qfileinfo.h.
QFileInfoList()
QFileInfoList related
Synonym for QList<QFileInfo>.
Properties
d_ptr
QSharedDataPointer<QFileInfoPrivate> QFileInfo::d_ptr protected
Definition at line 177 of file qfileinfo.h.
Referenced by detach(), makeAbsolute(), operator=(), operator==(), QDirIteratorPrivate::pushDirectory(), and setFile().
The documentation for this class was generated from the following files:
/src/corelib/io/qfileinfo.h
/src/corelib/io/qfileinfo.cpp