Qt 4.8: QTextTable Class Reference
QTextTable Class Reference
The QTextTable class represents a table in a QTextDocument.
#include <qtexttable.h>
Public Functions
void appendColumns (int count)
Appends count columns at the right side of the table.
void appendRows (int count)
Appends count rows at the bottom of the table.
QTextTableCell cellAt (int row, int col) const
Returns the table cell at the given row and column in the table.
QTextTableCell cellAt (int position) const
Returns the table cell that contains the character at the given position in the document.
QTextTableCell cellAt (const QTextCursor &c) const
Returns the table cell containing the given cursor.
int columns () const
Returns the number of columns in the table.
QTextTableFormat format () const
Returns the table's format.
void insertColumns (int pos, int num)
Inserts a number of columns before the column with the specified index.
void insertRows (int pos, int num)
Inserts a number of rows before the row with the specified index.
void mergeCells (int row, int col, int numRows, int numCols)
Merges the cell at the specified row and column with the adjacent cells into one cell.
void mergeCells (const QTextCursor &cursor)
Merges the cells selected by the provided cursor.
QTextTable (QTextDocument *doc)
void removeColumns (int pos, int num)
Removes a number of columns starting with the column at the specified index.
void removeRows (int pos, int num)
Removes a number of rows starting with the row at the specified index.
void resize (int rows, int cols)
Resizes the table to contain the required number of rows and columns.
QTextCursor rowEnd (const QTextCursor &c) const
Returns a cursor pointing to the end of the row that contains the given cursor.
int rows () const
Returns the number of rows in the table.
QTextCursor rowStart (const QTextCursor &c) const
Returns a cursor pointing to the start of the row that contains the given cursor.
void setFormat (const QTextTableFormat &format)
Sets the table's format.
void splitCell (int row, int col, int numRows, int numCols)
Splits the specified cell at row and column into an array of multiple cells with dimensions specified by numRows and numCols.
~QTextTable ()
Public Functions inherited from QTextFrame
iterator begin () const
Returns an iterator pointing to the first document element inside the frame.
QList< QTextFrame * > childFrames () const
Returns a (possibly empty) list of the frame's child frames.
iterator end () const
Returns an iterator pointing to the position past the last document element inside the frame.
QTextCursor firstCursorPosition () const
Returns the first cursor position inside the frame.
int firstPosition () const
Returns the first document position inside the frame.
QTextFrameFormat frameFormat () const
Returns the frame's format.
QTextCursor lastCursorPosition () const
Returns the last cursor position inside the frame.
int lastPosition () const
Returns the last document position inside the frame.
QTextFrameLayoutData * layoutData () const
QTextFrame * parentFrame () const
Returns the frame's parent frame.
QTextFrame (QTextDocument *doc)
Creates a new empty frame for the text document.
void setFrameFormat (const QTextFrameFormat &format)
Sets the frame's format.
void setLayoutData (QTextFrameLayoutData *data)
~QTextFrame ()
Destroys the frame, and removes it from the document's layout.
Public Functions inherited from QTextObject
QTextDocumentPrivate * docHandle () const
QTextDocument * document () const
Returns the document this object belongs to.
QTextFormat format () const
Returns the text object's format.
int formatIndex () const
Returns the index of the object's format in the document's internal list of formats.
int objectIndex () const
Returns the object index of this object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Friends
class QTextTableCell
Additional Inherited Members
Public Types inherited from QTextFrame
typedef iterator Iterator
Qt-style synonym for QTextFrame::iterator.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QTextFrame
QTextFrame (QTextFramePrivate &p, QTextDocument *doc)
Protected Functions inherited from QTextObject
QTextObject (QTextDocument *doc)
Creates a new QTextObject for the given document.
QTextObject (QTextObjectPrivate &p, QTextDocument *doc)
void setFormat (const QTextFormat &format)
Sets the text object's format.
~QTextObject ()
Destroys the text object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QTextTable class represents a table in a QTextDocument.
Note
This class or function is reentrant.
A table is a group of cells ordered into rows and columns. Each table contains at least one row and one column. Each cell contains a block, and is surrounded by a frame.
Tables are usually created and inserted into a document with the QTextCursor::insertTable() function. For example, we can insert a table with three rows and two columns at the current cursor position in an editor using the following lines of code:
    QTextCursor cursor(editor->textCursor());
    cursor.movePosition(QTextCursor::Start);
    QTextTable *table = cursor.insertTable(rows, columns, tableFormat);
The table format is either defined when the table is created or changed later with setFormat().
The table currently being edited by the cursor is found with QTextCursor::currentTable(). This allows its format or dimensions to be changed after it has been inserted into a document.
A table's size can be changed with resize(), or by using insertRows(), insertColumns(), removeRows(), or removeColumns(). Use cellAt() to retrieve table cells.
The starting and ending positions of table rows can be found by moving a cursor within a table, and using the rowStart() and rowEnd() functions to obtain cursors at the start and end of each row.
Rows and columns within a QTextTable can be merged and split using the mergeCells() and splitCell() functions. However, only cells that span multiple rows or columns can be split. (Merging or splitting does not increase or decrease the number of rows and columns.)
Note that if you have merged multiple columns and rows into one cell, you will not be able to split the merged cell into new cells spanning over more than one row or column. To be able to split cells spanning over several rows and columns you need to do this over several iterations.
Original Table
Suppose we have a 2x3 table of names and addresses. To merge both columns in the first row we invoke mergeCells() with row = 0, column = 0, numRows = 1 and numColumns = 2.
    table->mergeCells(0, 0, 1, 2);
This gives us the following table. To split the first row of the table back into two cells, we invoke the splitCell() function with numRows and numCols = 1.
    table->splitCell(0, 0, 1, 1);
Split Table
This results in the original table.
See also
QTextTableFormat
Definition at line 103 of file qtexttable.h.
Constructors and Destructors
QTextTable()
QTextTable::QTextTable (QTextDocument * doc) explicit
Warning
This function is not part of the public interface.
Definition at line 606 of file qtexttable.cpp.
     : QTextFrame(*new QTextTablePrivate(doc), doc)
 {
 }
~QTextTable()
QTextTable::~QTextTable ()
Warning
This function is not part of the public interface.
Destroys the table.
Definition at line 615 of file qtexttable.cpp.
 {
 }
Functions
appendColumns()
void QTextTable::appendColumns (int count)
Appends count columns at the right side of the table.
Since
4.5
See also
insertColumns() insertRows() resize() removeRows() removeColumns() appendRows()
Definition at line 915 of file qtexttable.cpp.
 {
     insertColumns(columns(), count);
 }
appendRows()
void QTextTable::appendRows (int count)
Appends count rows at the bottom of the table.
Since
4.5
See also
insertColumns() insertRows() resize() removeRows() removeColumns() appendColumns()
Definition at line 901 of file qtexttable.cpp.
 {
     insertRows(rows(), count);
 }
cellAt() [1/3]
QTextTableCell QTextTable::cellAt (int row, int column) const
Returns the table cell at the given row and column in the table.
See also
columns() rows()
Definition at line 630 of file qtexttable.cpp.
Referenced by QTextCursorPrivate::aboutToRemoveCell(), QTextCursorPrivate::adjustCursor(), cellAt(), QTextCursorPrivate::clearCells(), QTextCursorPrivate::complexSelectionTable(), QTextCopyHelper::copy(), QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitTable(), QTextControlPrivate::gotoNextTableCell(), QTextControlPrivate::gotoPreviousTableCell(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutTable(), mergeCells(), QTextCursorPrivate::movePosition(), removeColumns(), removeRows(), rowEnd(), rowStart(), QTextCursorPrivate::selectedTableCells(), QTextCursor::selectedText(), QTextCursorPrivate::setBlockCharFormat(), QTextCursorPrivate::setBlockFormat(), QTextCursorPrivate::setCharFormat(), splitCell(), and QTextOdfWriter::writeFrame().
 {
     Q_D(const QTextTable);
     if (d->dirty)
         d->update();
     if (row < 0 || row >= d->nRows || col < 0 || col >= d->nCols)
         return QTextTableCell();
     return QTextTableCell(this, d->grid[row*d->nCols + col]);
 }
cellAt() [2/3]
QTextTableCell QTextTable::cellAt (int position) const
Returns the table cell that contains the character at the given position in the document.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 651 of file qtexttable.cpp.
 {
     Q_D(const QTextTable);
     if (d->dirty)
         d->update();
     uint pos = (uint)position;
     const QTextDocumentPrivate::FragmentMap &map = d->pieceTable->fragmentMap();
     if (position < 0 || map.position(d->fragment_start) >= pos || map.position(d->fragment_end) < pos)
         return QTextTableCell();
     QFragmentFindHelper helper(position, map);
     QList<int>::ConstIterator it = qLowerBound(d->cells.begin(), d->cells.end(), helper);
     if (it != d->cells.begin())
         --it;
     return QTextTableCell(this, *it);
 }
cellAt() [3/3]
QTextTableCell QTextTable::cellAt (const QTextCursor & cursor) const
Returns the table cell containing the given cursor.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 680 of file qtexttable.cpp.
 {
     return cellAt(c.position());
 }
columns()
int QTextTable::columns () const
Returns the number of columns in the table.
See also
rows()
Definition at line 1340 of file qtexttable.cpp.
Referenced by QTextCursorPrivate::aboutToRemoveCell(), appendColumns(), QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitTable(), QTextControlPrivate::gotoNextTableCell(), QTextControlPrivate::gotoPreviousTableCell(), QTextDocumentLayoutPrivate::layoutTable(), mergeCells(), QTextCursorPrivate::movePosition(), resize(), setFormat(), and QTextOdfWriter::writeFrame().
 {
     Q_D(const QTextTable);
     if (d->dirty)
         d->update();
     return d->nCols;
 }
format()
QTextTableFormat QTextTable::format () const inline
Returns the table's format.
See also
setFormat()
Definition at line 133 of file qtexttable.h.
Referenced by QTextCopyHelper::copy(), QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitTable(), insertColumns(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutTable(), removeColumns(), and setFormat().
 { return QTextObject::format().toTableFormat(); }
insertColumns()
void QTextTable::insertColumns (int index, int columns)
Inserts a number of columns before the column with the specified index.
See also
insertRows() resize() removeRows() removeColumns() appendRows() appendColumns()
Definition at line 797 of file qtexttable.cpp.
Referenced by appendColumns(), and resize().
 {
     Q_D(QTextTable);
     if (num <= 0)
     return;
     if (d->dirty)
         d->update();
     if (pos > d->nCols || pos < 0)
         pos = d->nCols;
 //     qDebug() << "-------- insertCols" << pos << num;
     QTextDocumentPrivate *p = d->pieceTable;
     QTextFormatCollection *c = p->formatCollection();
     p->beginEditBlock();
     QList<int> extendedSpans;
     for (int i = 0; i < d->nRows; ++i) {
         int cell;
         if (i == d->nRows - 1 && pos == d->nCols) {
             cell = d->fragment_end;
         } else {
             int logicalGridIndexBeforePosition = pos > 0
                                                  ? d->findCellIndex(d->grid[i*d->nCols + pos - 1])
                                                  : -1;
             // Search for the logical insertion point by skipping past cells which are not the first
             // cell in a rowspan. This means any cell for which the logical grid index is
             // less than the logical cell index of the cell before the insertion.
             int logicalGridIndex;
             int gridArrayOffset = i*d->nCols + pos;
             do {
                 cell = d->grid[gridArrayOffset];
                 logicalGridIndex = d->findCellIndex(cell);
                 gridArrayOffset++;
             } while (logicalGridIndex < logicalGridIndexBeforePosition
                      && gridArrayOffset < d->nRows*d->nCols);
             if (logicalGridIndex < logicalGridIndexBeforePosition
                 && gridArrayOffset == d->nRows*d->nCols)
                 cell = d->fragment_end;
         }
         if (pos > 0 && pos < d->nCols && cell == d->grid[i*d->nCols + pos - 1]) {
             // cell spans the insertion place, extend it
             if (!extendedSpans.contains(cell)) {
                 QTextDocumentPrivate::FragmentIterator it(&p->fragmentMap(), cell);
                 QTextCharFormat fmt = c->charFormat(it->format);
                 fmt.setTableCellColumnSpan(fmt.tableCellColumnSpan() + num);
                 p->setCharFormat(it.position(), 1, fmt);
                 d->dirty = true;
                 extendedSpans << cell;
             }
         } else {
             /* If the next cell is spanned from the row above, we need to find the right position
             to insert to */
             if (i > 0 && pos < d->nCols && cell == d->grid[(i-1) * d->nCols + pos]) {
                 int gridIndex = i*d->nCols + pos;
                 const int gridEnd = d->nRows * d->nCols - 1;
                 while (gridIndex < gridEnd && cell == d->grid[gridIndex]) {
                     ++gridIndex;
                 }
                 if (gridIndex == gridEnd)
                     cell = d->fragment_end;
                 else
                     cell = d->grid[gridIndex];
             }
             QTextDocumentPrivate::FragmentIterator it(&p->fragmentMap(), cell);
             QTextCharFormat fmt = c->charFormat(it->format);
             fmt.setTableCellRowSpan(1);
             fmt.setTableCellColumnSpan(1);
             Q_ASSERT(fmt.objectIndex() == objectIndex());
             int position = it.position();
             int cfmt = p->formatCollection()->indexForFormat(fmt);
             int bfmt = p->formatCollection()->indexForFormat(QTextBlockFormat());
             for (int i = 0; i < num; ++i)
                 p->insertBlock(QTextBeginningOfFrame, position, bfmt, cfmt, QTextUndoCommand::MoveCursor);
         }
     }
     QTextTableFormat tfmt = format();
     tfmt.setColumns(tfmt.columns()+num);
     QVector<QTextLength> columnWidths = tfmt.columnWidthConstraints();
     if (! columnWidths.isEmpty()) {
         for (int i = num; i > 0; --i)
             columnWidths.insert(pos, columnWidths[qMax(0, pos-1)]);
     }
     tfmt.setColumnWidthConstraints (columnWidths);
     QTextObject::setFormat(tfmt);
 //     qDebug() << "-------- end insertCols" << pos << num;
     p->endEditBlock();
 }
insertRows()
void QTextTable::insertRows (int index, int rows)
Inserts a number of rows before the row with the specified index.
See also
resize() insertColumns() removeRows() removeColumns() appendRows() appendColumns()
Definition at line 732 of file qtexttable.cpp.
Referenced by appendRows(), QTextControlPrivate::gotoNextTableCell(), and resize().
 {
     Q_D(QTextTable);
     if (num <= 0)
     return;
     if (d->dirty)
         d->update();
     if (pos > d->nRows || pos < 0)
         pos = d->nRows;
 //     qDebug() << "-------- insertRows" << pos << num;
     QTextDocumentPrivate *p = d->pieceTable;
     QTextFormatCollection *c = p->formatCollection();
     p->beginEditBlock();
     int extended = 0;
     int insert_before = 0;
     if (pos > 0 && pos < d->nRows) {
         for (int i = 0; i < d->nCols; ++i) {
             int cell = d->grid[pos*d->nCols + i];
             if (cell == d->grid[(pos-1)*d->nCols+i]) {
                 // cell spans the insertion place, extend it
                 QTextDocumentPrivate::FragmentIterator it(&p->fragmentMap(), cell);
                 QTextCharFormat fmt = c->charFormat(it->format);
                 fmt.setTableCellRowSpan(fmt.tableCellRowSpan() + num);
                 p->setCharFormat(it.position(), 1, fmt);
                 extended++;
             } else if (!insert_before) {
                 insert_before = cell;
             }
         }
     } else {
         insert_before = (pos == 0 ? d->grid[0] : d->fragment_end);
     }
     if (extended < d->nCols) {
         Q_ASSERT(insert_before);
         QTextDocumentPrivate::FragmentIterator it(&p->fragmentMap(), insert_before);
         QTextCharFormat fmt = c->charFormat(it->format);
         fmt.setTableCellRowSpan(1);
         fmt.setTableCellColumnSpan(1);
         Q_ASSERT(fmt.objectIndex() == objectIndex());
         int pos = it.position();
         int cfmt = p->formatCollection()->indexForFormat(fmt);
         int bfmt = p->formatCollection()->indexForFormat(QTextBlockFormat());
 //         qDebug("inserting %d cells, nCols=%d extended=%d", num*(d->nCols-extended), d->nCols, extended);
         for (int i = 0; i < num*(d->nCols-extended); ++i)
             p->insertBlock(QTextBeginningOfFrame, pos, bfmt, cfmt, QTextUndoCommand::MoveCursor);
     }
 //     qDebug() << "-------- end insertRows" << pos << num;
     p->endEditBlock();
 }
mergeCells() [1/2]
void QTextTable::mergeCells (int row, int column, int numRows, int numCols)
Merges the cell at the specified row and column with the adjacent cells into one cell.
Since
4.1
The new cell will span numRows rows and numCols columns. If numRows or numCols is less than the current number of rows or columns the cell spans then this method does nothing.
See also
splitCell()
Definition at line 1072 of file qtexttable.cpp.
Referenced by columns(), mergeCells(), and QTextHtmlImporter::scanTable().
 {
     Q_D(QTextTable);
     if (d->dirty)
         d->update();
     QTextDocumentPrivate *p = d->pieceTable;
     QTextFormatCollection *fc = p->formatCollection();
     const QTextTableCell cell = cellAt(row, column);
     if (!cell.isValid() || row != cell.row() || column != cell.column())
         return;
     QTextCharFormat fmt = cell.format();
     const int rowSpan = fmt.tableCellRowSpan();
     const int colSpan = fmt.tableCellColumnSpan();
     numRows = qMin(numRows, rows() - cell.row());
     numCols = qMin(numCols, columns() - cell.column());
     // nothing to merge?
     if (numRows < rowSpan || numCols < colSpan)
         return;
     // check the edges of the merge rect to make sure no cell spans the edge
     for (int r = row; r < row + numRows; ++r) {
         if (cellAt(r, column) == cellAt(r, column - 1))
             return;
         if (cellAt(r, column + numCols) == cellAt(r, column + numCols - 1))
             return;
     }
     for (int c = column; c < column + numCols; ++c) {
         if (cellAt(row, c) == cellAt(row - 1, c))
             return;
         if (cellAt(row + numRows, c) == cellAt(row + numRows - 1, c))
             return;
     }
     p->beginEditBlock();
     const int origCellPosition = cell.firstPosition() - 1;
     const int cellFragment = d->grid[row * d->nCols + column];
     // find the position at which to insert the contents of the merged cells
     QFragmentFindHelper helper(origCellPosition, p->fragmentMap());
     QList<int>::Iterator it = qBinaryFind(d->cells.begin(), d->cells.end(), helper);
     Q_ASSERT(it != d->cells.end());
     Q_ASSERT(*it == cellFragment);
     const int insertCellIndex = it - d->cells.begin();
     int insertFragment = d->cells.value(insertCellIndex + 1, d->fragment_end);
     uint insertPos = p->fragmentMap().position(insertFragment);
     d->blockFragmentUpdates = true;
     bool rowHasText = cell.firstCursorPosition().block().length();
     bool needsParagraph = rowHasText && colSpan == numCols;
     // find all cells that will be erased by the merge
     for (int r = row; r < row + numRows; ++r) {
         int firstColumn = r < row + rowSpan ? column + colSpan : column;
         // don't recompute the cell index for the first row
         int firstCellIndex = r == row ? insertCellIndex + 1 : -1;
         int cellIndex = firstCellIndex;
         for (int c = firstColumn; c < column + numCols; ++c) {
             const int fragment = d->grid[r * d->nCols + c];
             // already handled?
             if (fragment == cellFragment)
                 continue;
             QTextDocumentPrivate::FragmentIterator it(&p->fragmentMap(), fragment);
             uint pos = it.position();
             if (firstCellIndex == -1) {
                 QFragmentFindHelper helper(pos, p->fragmentMap());
                 QList<int>::Iterator it = qBinaryFind(d->cells.begin(), d->cells.end(), helper);
                 Q_ASSERT(it != d->cells.end());
                 Q_ASSERT(*it == fragment);
                 firstCellIndex = cellIndex = it - d->cells.begin();
             }
             ++cellIndex;
             QTextCharFormat fmt = fc->charFormat(it->format);
             const int cellRowSpan = fmt.tableCellRowSpan();
             const int cellColSpan = fmt.tableCellColumnSpan();
             // update the grid for this cell
             for (int i = r; i < r + cellRowSpan; ++i)
                 for (int j = c; j < c + cellColSpan; ++j)
                     d->grid[i * d->nCols + j] = cellFragment;
             // erase the cell marker
             p->remove(pos, 1);
             const int nextFragment = d->cells.value(cellIndex, d->fragment_end);
             const uint nextPos = p->fragmentMap().position(nextFragment);
             Q_ASSERT(nextPos >= pos);
             // merge the contents of the cell (if not empty)
             if (nextPos > pos) {
                 if (needsParagraph) {
                     needsParagraph = false;
                     QTextCursor(p, insertPos++).insertBlock();
                     p->move(pos + 1, insertPos, nextPos - pos);
                 } else if (rowHasText) {
                     QTextCursor(p, insertPos++).insertText(QLatin1String(" "));
                     p->move(pos + 1, insertPos, nextPos - pos);
                 } else {
                     p->move(pos, insertPos, nextPos - pos);
                 }
                 insertPos += nextPos - pos;
                 rowHasText = true;
             }
         }
         if (rowHasText) {
             needsParagraph = true;
             rowHasText = false;
         }
         // erase cells from last row
         if (firstCellIndex >= 0) {
             d->cellIndices.remove(firstCellIndex, cellIndex - firstCellIndex);
             d->cells.erase(d->cells.begin() + firstCellIndex, d->cells.begin() + cellIndex);
         }
     }
     d->fragment_start = d->cells.first();
     fmt.setTableCellRowSpan(numRows);
     fmt.setTableCellColumnSpan(numCols);
     p->setCharFormat(origCellPosition, 1, fmt);
     d->blockFragmentUpdates = false;
     d->dirty = false;
     p->endEditBlock();
 }
mergeCells() [2/2]
void QTextTable::mergeCells (const QTextCursor & cursor)
Merges the cells selected by the provided cursor.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.1
See also
splitCell()
Definition at line 1231 of file qtexttable.cpp.
 {
     if (!cursor.hasComplexSelection())
         return;
     int firstRow, numRows, firstColumn, numColumns;
     cursor.selectedTableCells(&firstRow, &numRows, &firstColumn, &numColumns);
     mergeCells(firstRow, firstColumn, numRows, numColumns);
 }
removeColumns()
void QTextTable::removeColumns (int index, int columns)
Removes a number of columns starting with the column at the specified index.
See also
insertRows() insertColumns() removeRows() resize() appendRows() appendColumns()
Definition at line 995 of file qtexttable.cpp.
Referenced by resize().
 {
     Q_D(QTextTable);
 //     qDebug() << "-------- removeCols" << pos << num;
     if (num <= 0 || pos < 0)
     return;
     if (d->dirty)
         d->update();
     if (pos >= d->nCols)
         return;
     if (pos + num > d->nCols)
         pos = d->nCols - num;
     QTextDocumentPrivate *p = d->pieceTable;
     QTextFormatCollection *collection = p->formatCollection();
     p->beginEditBlock();
     // delete whole table?
     if (pos == 0 && num == d->nCols) {
         const int pos = p->fragmentMap().position(d->fragment_start);
         p->remove(pos, p->fragmentMap().position(d->fragment_end) - pos + 1);
         p->endEditBlock();
         return;
     }
     p->aboutToRemoveCell(cellAt(0, pos).firstPosition(), cellAt(d->nRows - 1, pos + num - 1).lastPosition());
     QList<int> touchedCells;
     for (int r = 0; r < d->nRows; ++r) {
         for (int c = pos; c < pos + num; ++c) {
             int cell = d->grid[r*d->nCols + c];
             QTextDocumentPrivate::FragmentIterator it(&p->fragmentMap(), cell);
             QTextCharFormat fmt = collection->charFormat(it->format);
             int span = fmt.tableCellColumnSpan();
             if (touchedCells.contains(cell) && span <= 1)
                 continue;
             touchedCells << cell;
             if (span > 1) {
                 fmt.setTableCellColumnSpan(span - 1);
                 p->setCharFormat(it.position(), 1, fmt);
             } else {
                 // remove cell
                 int index = d->cells.indexOf(cell) + 1;
                 int f_end = index < d->cells.size() ? d->cells.at(index) : d->fragment_end;
                 p->remove(it.position(), p->fragmentMap().position(f_end) - it.position());
             }
         }
     }
     QTextTableFormat tfmt = format();
     tfmt.setColumns(tfmt.columns()-num);
     QVector<QTextLength> columnWidths = tfmt.columnWidthConstraints();
     if (columnWidths.count() > pos) {
         columnWidths.remove(pos, num);
         tfmt.setColumnWidthConstraints (columnWidths);
     }
     QTextObject::setFormat(tfmt);
     p->endEditBlock();
 //     qDebug() << "-------- end removeCols" << pos << num;
 }
removeRows()
void QTextTable::removeRows (int index, int rows)
Removes a number of rows starting with the row at the specified index.
See also
insertRows(), insertColumns(), resize(), removeColumns() appendRows() appendColumns()
Definition at line 930 of file qtexttable.cpp.
Referenced by resize().
 {
     Q_D(QTextTable);
 //     qDebug() << "-------- removeRows" << pos << num;
     if (num <= 0 || pos < 0)
         return;
     if (d->dirty)
         d->update();
     if (pos >= d->nRows)
         return;
     if (pos+num > d->nRows)
         num = d->nRows - pos;
     QTextDocumentPrivate *p = d->pieceTable;
     QTextFormatCollection *collection = p->formatCollection();
     p->beginEditBlock();
     // delete whole table?
     if (pos == 0 && num == d->nRows) {
         const int pos = p->fragmentMap().position(d->fragment_start);
         p->remove(pos, p->fragmentMap().position(d->fragment_end) - pos + 1);
         p->endEditBlock();
         return;
     }
     p->aboutToRemoveCell(cellAt(pos, 0).firstPosition(), cellAt(pos + num - 1, d->nCols - 1).lastPosition());
     QList<int> touchedCells;
     for (int r = pos; r < pos + num; ++r) {
         for (int c = 0; c < d->nCols; ++c) {
             int cell = d->grid[r*d->nCols + c];
             if (touchedCells.contains(cell))
                 continue;
             touchedCells << cell;
             QTextDocumentPrivate::FragmentIterator it(&p->fragmentMap(), cell);
             QTextCharFormat fmt = collection->charFormat(it->format);
             int span = fmt.tableCellRowSpan();
             if (span > 1) {
                 fmt.setTableCellRowSpan(span - 1);
                 p->setCharFormat(it.position(), 1, fmt);
             } else {
                 // remove cell
                 int index = d->cells.indexOf(cell) + 1;
                 int f_end = index < d->cells.size() ? d->cells.at(index) : d->fragment_end;
                 p->remove(it.position(), p->fragmentMap().position(f_end) - it.position());
             }
         }
     }
     p->endEditBlock();
 //     qDebug() << "-------- end removeRows" << pos << num;
 }
resize()
void QTextTable::resize (int rows, int columns)
Resizes the table to contain the required number of rows and columns.
See also
insertRows() insertColumns() removeRows() removeColumns()
Definition at line 695 of file qtexttable.cpp.
 {
     Q_D(QTextTable);
     if (d->dirty)
         d->update();
     int nRows = this->rows();
     int nCols = this->columns();
     if (rows == nRows && cols == nCols)
     return;
     d->pieceTable->beginEditBlock();
     if (nCols < cols)
         insertColumns(nCols, cols - nCols);
     else if (nCols > cols)
         removeColumns(cols, nCols - cols);
     if (nRows < rows)
         insertRows(nRows, rows-nRows);
     else if (nRows > rows)
         removeRows(rows, nRows-rows);
     d->pieceTable->endEditBlock();
 }
rowEnd()
QTextCursor QTextTable::rowEnd (const QTextCursor & cursor) const
Returns a cursor pointing to the end of the row that contains the given cursor.
See also
rowStart()
Definition at line 1390 of file qtexttable.cpp.
 {
     Q_D(const QTextTable);
     QTextTableCell cell = cellAt(c);
     if (!cell.isValid())
         return QTextCursor();
     int row = cell.row() + 1;
     int fragment = row < d->nRows ? d->grid[row*d->nCols] : d->fragment_end;
     QTextDocumentPrivate *p = d->pieceTable;
     QTextDocumentPrivate::FragmentIterator it(&p->fragmentMap(), fragment);
     return QTextCursor(p, it.position() - 1);
 }
rows()
int QTextTable::rows () const
Returns the number of rows in the table.
See also
columns()
Definition at line 1326 of file qtexttable.cpp.
Referenced by QTextCursorPrivate::aboutToRemoveCell(), appendRows(), QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitTable(), QTextControlPrivate::gotoNextTableCell(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutTable(), mergeCells(), and resize().
 {
     Q_D(const QTextTable);
     if (d->dirty)
         d->update();
     return d->nRows;
 }
rowStart()
QTextCursor QTextTable::rowStart (const QTextCursor & cursor) const
Returns a cursor pointing to the start of the row that contains the given cursor.
See also
rowEnd()
Definition at line 1366 of file qtexttable.cpp.
 {
     Q_D(const QTextTable);
     QTextTableCell cell = cellAt(c);
     if (!cell.isValid())
         return QTextCursor();
     int row = cell.row();
     QTextDocumentPrivate *p = d->pieceTable;
     QTextDocumentPrivate::FragmentIterator it(&p->fragmentMap(), d->grid[row*d->nCols]);
     return QTextCursor(p, it.position());
 }
setFormat()
void QTextTable::setFormat (const QTextTableFormat & format)
Sets the table's format.
See also
format()
Definition at line 1414 of file qtexttable.cpp.
 {
     QTextTableFormat fmt = format;
     // don't try to change the number of table columns from here
     fmt.setColumns(columns());
     QTextObject::setFormat(fmt);
 }
splitCell()
void QTextTable::splitCell (int row, int column, int numRows, int numCols)
Splits the specified cell at row and column into an array of multiple cells with dimensions specified by numRows and numCols.
Since
4.1
Note
It is only possible to split cells that span multiple rows or columns, such as rows that have been merged using mergeCells().
See also
mergeCells()
Definition at line 1255 of file qtexttable.cpp.
 {
     Q_D(QTextTable);
     if (d->dirty)
         d->update();
     QTextDocumentPrivate *p = d->pieceTable;
     QTextFormatCollection *c = p->formatCollection();
     const QTextTableCell cell = cellAt(row, column);
     if (!cell.isValid())
         return;
     row = cell.row();
     column = cell.column();
     QTextCharFormat fmt = cell.format();
     const int rowSpan = fmt.tableCellRowSpan();
     const int colSpan = fmt.tableCellColumnSpan();
     // nothing to split?
     if (numRows > rowSpan || numCols > colSpan)
         return;
     p->beginEditBlock();
     const int origCellPosition = cell.firstPosition() - 1;
     QVarLengthArray<int> rowPositions(rowSpan);
     rowPositions[0] = cell.lastPosition();
     for (int r = row + 1; r < row + rowSpan; ++r) {
         // find the cell before which to insert the new cell markers
         int gridIndex = r * d->nCols + column;
         QVector<int>::iterator it = qUpperBound(d->cellIndices.begin(), d->cellIndices.end(), gridIndex);
         int cellIndex = it - d->cellIndices.begin();
         int fragment = d->cells.value(cellIndex, d->fragment_end);
         rowPositions[r - row] = p->fragmentMap().position(fragment);
     }
     fmt.setTableCellColumnSpan(1);
     fmt.setTableCellRowSpan(1);
     const int fmtIndex = c->indexForFormat(fmt);
     const int blockIndex = p->blockMap().find(cell.lastPosition())->format;
     int insertAdjustement = 0;
     for (int i = 0; i < numRows; ++i) {
         for (int c = 0; c < colSpan - numCols; ++c)
             p->insertBlock(QTextBeginningOfFrame, rowPositions[i] + insertAdjustement + c, blockIndex, fmtIndex);
         insertAdjustement += colSpan - numCols;
     }
     for (int i = numRows; i < rowSpan; ++i) {
         for (int c = 0; c < colSpan; ++c)
             p->insertBlock(QTextBeginningOfFrame, rowPositions[i] + insertAdjustement + c, blockIndex, fmtIndex);
         insertAdjustement += colSpan;
     }
     fmt.setTableCellRowSpan(numRows);
     fmt.setTableCellColumnSpan(numCols);
     p->setCharFormat(origCellPosition, 1, fmt);
     p->endEditBlock();
 }
Friends and Related Functions
QTextTableCell
friend class QTextTableCell friend
Definition at line 138 of file qtexttable.h.
Referenced by cellAt().
The documentation for this class was generated from the following files:
/src/gui/text/qtexttable.h
/src/gui/text/qtexttable.cpp