Qt 4.8: QProxyScreen Class Reference
QProxyScreen Class Reference
The QProxyScreen class provides a generic interface to QScreen implementations.
#include <qscreenproxy_qws.h>
Public Functions
void blank (bool on)
Reimplemented Function
void blit (const QImage &img, const QPoint &topLeft, const QRegion &region)
Reimplemented Function
bool connect (const QString &displaySpec)
Reimplemented Function
QWSWindowSurface * createSurface (QWidget *widget) const
Reimplemented Function
QWSWindowSurface * createSurface (const QString &key) const
Reimplemented Function
void disconnect ()
Reimplemented Function
void exposeRegion (QRegion r, int changing)
Reimplemented Function
void haltUpdates ()
bool initDevice ()
This function is called by the Qt for Embedded Linux server to initialize the framebuffer.
bool isInterlaced () const
Reimplemented Function
bool isTransformed () const
Reimplemented Function
QSize mapFromDevice (const QSize &s) const
Reimplemented Function
QPoint mapFromDevice (const QPoint &, const QSize &) const
Reimplemented Function
QRect mapFromDevice (const QRect &, const QSize &) const
Reimplemented Function
QRegion mapFromDevice (const QRegion &, const QSize &) const
Reimplemented Function
QSize mapToDevice (const QSize &s) const
Reimplemented Function
QPoint mapToDevice (const QPoint &, const QSize &) const
Reimplemented Function
QRect mapToDevice (const QRect &, const QSize &) const
Reimplemented Function
QRegion mapToDevice (const QRegion &, const QSize &) const
Reimplemented Function
int memoryNeeded (const QString &)
bool onCard (const unsigned char *) const
Reimplemented Function
bool onCard (const unsigned char *, ulong &out_offset) const
Reimplemented Function
QProxyScreen (int display_id, ClassId=ProxyClass)
Constructs a proxy screen with the given displayId and classId.
QRegion region () const
Reimplemented Function
void restore ()
Reimplemented Function
void resumeUpdates ()
void save ()
Reimplemented Function
QScreen * screen () const
Returns the real screen used by the proxy screen.
void setDirty (const QRect &)
Reimplemented Function
void setMode (int width, int height, int depth)
Reimplemented Function
void setScreen (QScreen *screen)
Sets the real screen to be used by the proxy screen.
int sharedRamSize (void *)
void shutdownDevice ()
Reimplemented Function
void solidFill (const QColor &color, const QRegion &region)
Reimplemented Function
QList< QScreen * > subScreens () const
Reimplemented Function
bool supportsDepth (int) const
Reimplemented Function
int transformOrientation () const
Reimplemented Function
~QProxyScreen ()
Destroys the proxy screen.
Public Functions inherited from QScreen
virtual int alloc (unsigned int, unsigned int, unsigned int)
Returns the index in the screen's palette which is the closest match to the given RGB value (red, green, blue).
uchar * base () const
Returns a pointer to the beginning of the framebuffer.
void blit (QWSWindow *bs, const QRegion &clip)
virtual uchar * cache (int)
ClassId classId () const
Returns the class identifier for the screen object.
QRgb * clut ()
Returns a pointer to the screen's color lookup table (i.
int colorCount ()
Returns the number of entries in the screen's color lookup table (i.
int depth () const
Returns the depth of the framebuffer, in bits per pixel.
int deviceHeight () const
Returns the full height of the framebuffer device in pixels.
int deviceWidth () const
Returns the physical width of the framebuffer device in pixels.
QGraphicsSystem * graphicsSystem () const
int height () const
Returns the logical height of the framebuffer in pixels.
int linestep () const
Returns the length of each scanline of the framebuffer in bytes.
virtual QImage mapFromDevice (const QImage &) const
Maps the given image from the framebuffer coordinate system to the coordinate space used by the application.
virtual QImage mapToDevice (const QImage &) const
Maps the given image from the coordinate space used by the application to the framebuffer coordinate system.
QT_DEPRECATED int numCols ()
QPoint offset () const
Returns the logical offset of the screen, i.
int physicalHeight () const
Returns the physical height of the screen in millimeters.
int physicalWidth () const
Returns the physical width of the screen in millimeters.
QImage::Format pixelFormat () const
Returns the pixel format of the screen, or QImage::Format_Invalid if the pixel format is not a supported image format.
PixelType pixelType () const
Returns the pixel storage format of the screen.
QPixmapDataFactory * pixmapDataFactory () const
virtual int pixmapDepth () const
Returns the preferred depth for pixmaps, in bits per pixel.
virtual int pixmapLinestepAlignment ()
Returns the value (in bits) to which individual scanlines of pixmaps held in the graphics card's memory, should be aligned.
virtual int pixmapOffsetAlignment ()
Returns the value (in bits) to which the start address of pixmaps held in the graphics card's memory, should be aligned.
QScreen (int display_id, ClassId classId)
Constructs a new screen driver.
QScreen (int display_id)
Constructs a new screen driver.
int screenSize () const
Returns the size of the screen in bytes.
virtual void set (unsigned int, unsigned int, unsigned int, unsigned int)
void setOffset (const QPoint &p)
int subScreenIndexAt (const QPoint &p) const
Returns the index of the subscreen at the given position; returns -1 if no screen is found.
int totalSize () const
Returns the size of the available graphics card memory (including the screen) in bytes.
virtual void uncache (uchar *)
int width () const
Returns the logical width of the framebuffer in pixels.
virtual ~QScreen ()
Destroys this screen driver.
Private Functions
void configure ()
Properties
QProxyScreenPrivate * d_ptr
QScreen * realScreen
Additional Inherited Members
Public Types inherited from QScreen
enum ClassId {
LinuxFBClass, TransformedClass, VNCClass, MultiClass,
VFbClass, DirectFBClass, SvgalibClass, ProxyClass,
GLClass, IntfbClass, CustomClass = 1024
}
This enum defines the class identifiers for the known screen subclasses.
enum PixelType { NormalPixel, BGRPixel }
This enum describes the pixel storage format of the screen, i.
Static Public Functions inherited from QScreen
static QScreen * instance ()
Returns a pointer to the application's QScreen instance.
Protected Functions inherited from QScreen
void setGraphicsSystem (QGraphicsSystem *system)
void setPixelFormat (QImage::Format format)
Sets the screen's pixel format to format.
void setPixmapDataFactory (QPixmapDataFactory *factory)
Protected Variables inherited from QScreen
int d
the pixel depth
uchar * data
points to the first visible pixel in the frame buffer.
int dh
the device height
int displayId
int dw
the device width
QPoolEntry * entries
int * entryp
bool grayscale
the gray scale screen mode flag
int h
the logical height of the screen.
unsigned int * lowest
int lstep
the number of bytes representing a line in the frame buffer.
int mapsize
the total number of bytes in the frame buffer
int physHeight
the physical height of the screen in millimeters.
int physWidth
the physical width of the screen in millimeters.
PixelType pixeltype
set to BGRPixel
QRgb screenclut [256]
the color table
int screencols
the number of entries in the color table
int size
the number of bytes in the visible region of the frame buffer
int w
the logical width of the screen.
Static Protected Variables inherited from QScreen
static ClearCacheFunc clearCacheFunc = 0
Related Functions inherited from QScreen
void setTransformation (int transformation, int screenNo)
Here it is.
Detailed Description
The QProxyScreen class provides a generic interface to QScreen implementations.
Definition at line 84 of file qscreenproxy_qws.h.
Constructors and Destructors
QProxyScreen()
QProxyScreen::QProxyScreen (int display_id, QScreen::ClassId classId = ProxyClass)
Constructs a proxy screen with the given displayId and classId.
Definition at line 189 of file qscreenproxy_qws.cpp.
     : QScreen(displayId, classId), realScreen(0), d_ptr(0)
 {
 }
~QProxyScreen()
QProxyScreen::~QProxyScreen ()
Destroys the proxy screen.
Definition at line 197 of file qscreenproxy_qws.cpp.
 {
 }
Functions
blank()
void QProxyScreen::blank (bool on) virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 496 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         realScreen->blank(on);
 }
blit()
void QProxyScreen::blit (const QImage & img, const QPoint & topLeft, const QRegion & region) virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 305 of file qscreenproxy_qws.cpp.
Referenced by QTransformedScreen::blit(), and QTransformedScreen::isTransformed().
 {
     if (!realScreen) {
         QScreen::blit(image, topLeft, region);
         return;
     }
     realScreen->blit(image, topLeft, region);
 }
configure()
void QProxyScreen::configure () private
Warning
This function is not part of the public interface.
Definition at line 226 of file qscreenproxy_qws.cpp.
Referenced by connect(), setMode(), and setScreen().
 {
     if (!realScreen)
         return;
     d = realScreen->depth();
     w = realScreen->width();
     h = realScreen->height();
     dw = realScreen->deviceWidth();
     dh = realScreen->deviceHeight();
     lstep = realScreen->linestep();
     data = realScreen->base();
     lstep = realScreen->linestep();
     size = realScreen->screenSize();
     physWidth = realScreen->physicalWidth();
     physHeight = realScreen->physicalHeight();
     pixeltype = realScreen->pixelType();
 #if Q_BYTE_ORDER == Q_BIG_ENDIAN
     setFrameBufferLittleEndian(realScreen->frameBufferLittleEndian());
 #endif
     setOffset(realScreen->offset());
     setPixelFormat(realScreen->pixelFormat());
 #ifdef QT_QWS_CLIENTBLIT
     setSupportsBlitInClients(realScreen->supportsBlitInClients());
 #endif
 }
connect()
bool QProxyScreen::connect (const QString & displaySpec) virtual
Reimplemented Function
Implements QScreen.
Reimplemented in QTransformedScreen, and QVNCScreen.
Definition at line 275 of file qscreenproxy_qws.cpp.
 {
     const int id = getDisplayId(displaySpec);
     realScreen = qt_get_screen(id, displaySpec.toLatin1().constData());
     configure();
     return true;
 }
createSurface() [1/2]
QWSWindowSurface * QProxyScreen::createSurface (QWidget * widget) const virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 604 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         return realScreen->createSurface(widget);
     return QScreen::createSurface(widget);
 }
createSurface() [2/2]
QWSWindowSurface * QProxyScreen::createSurface (const QString & key) const virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 615 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         return realScreen->createSurface(key);
     return QScreen::createSurface(key);
 }
disconnect()
void QProxyScreen::disconnect () virtual
Reimplemented Function
Implements QScreen.
Reimplemented in QVNCScreen.
Definition at line 419 of file qscreenproxy_qws.cpp.
Referenced by QVNCScreen::disconnect().
 {
     if (realScreen) {
         realScreen->disconnect();
         delete realScreen;
         realScreen = 0;
     }
 }
exposeRegion()
void QProxyScreen::exposeRegion (QRegion r, int changing) virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 287 of file qscreenproxy_qws.cpp.
Referenced by QTransformedScreen::exposeRegion(), QTransformedScreen::isTransformed(), and setMode().
 {
     if (!realScreen) {
         QScreen::exposeRegion(r, changing);
         return;
     }
     realScreen->exposeRegion(r, changing);
     r &= realScreen->region();
     const QVector<QRect> rects = r.rects();
     for (int i = 0; i < rects.size(); ++i)
         setDirty(rects.at(i));
 }
haltUpdates()
void QProxyScreen::haltUpdates () virtual
Warning
This function is not part of the public interface.
Reimplemented from QScreen.
Definition at line 577 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         realScreen->haltUpdates();
 }
initDevice()
bool QProxyScreen::initDevice () virtual
This function is called by the Qt for Embedded Linux server to initialize the framebuffer.
Note that a server application will call the connect() function prior to this function.
Implement this function to make accelerated drivers set up the graphics card. Return true to indicate success and false to indicate failure.
See also
shutdownDevice(), connect()
Implements QScreen.
Reimplemented in QVNCScreen.
Definition at line 430 of file qscreenproxy_qws.cpp.
Referenced by QVNCScreen::initDevice().
 {
     if (realScreen)
         return realScreen->initDevice();
     return false;
 }
isInterlaced()
bool QProxyScreen::isInterlaced () const virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 525 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         return realScreen->isInterlaced();
     return false;
 }
isTransformed()
bool QProxyScreen::isTransformed () const virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 535 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         return realScreen->isTransformed();
     return QScreen::isTransformed();
 }
mapFromDevice() [1/4]
QSize QProxyScreen::mapFromDevice (const QSize & s) const virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 342 of file qscreenproxy_qws.cpp.
Referenced by QTransformedScreen::mapFromDevice().
 {
     if (!realScreen)
         return QScreen::mapFromDevice(s);
     return realScreen->mapFromDevice(s);
 }
mapFromDevice() [2/4]
QPoint QProxyScreen::mapFromDevice (const QPoint & p, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 364 of file qscreenproxy_qws.cpp.
 {
     if (!realScreen)
         return QScreen::mapFromDevice(p, s);
     return realScreen->mapFromDevice(p, s);
 }
mapFromDevice() [3/4]
QRect QProxyScreen::mapFromDevice (const QRect & r, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 386 of file qscreenproxy_qws.cpp.
 {
     if (!realScreen)
         return QScreen::mapFromDevice(r, s);
     return realScreen->mapFromDevice(r, s);
 }
mapFromDevice() [4/4]
QRegion QProxyScreen::mapFromDevice (const QRegion & r, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 408 of file qscreenproxy_qws.cpp.
 {
     if (!realScreen)
         return QScreen::mapFromDevice(r, s);
     return realScreen->mapFromDevice(r, s);
 }
mapToDevice() [1/4]
QSize QProxyScreen::mapToDevice (const QSize & s) const virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 331 of file qscreenproxy_qws.cpp.
Referenced by QTransformedScreen::mapToDevice().
 {
     if (!realScreen)
         return QScreen::mapToDevice(s);
     return realScreen->mapToDevice(s);
 }
mapToDevice() [2/4]
QPoint QProxyScreen::mapToDevice (const QPoint & p, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 353 of file qscreenproxy_qws.cpp.
 {
     if (!realScreen)
         return QScreen::mapToDevice(p, s);
     return realScreen->mapToDevice(p, s);
 }
mapToDevice() [3/4]
QRect QProxyScreen::mapToDevice (const QRect & r, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 375 of file qscreenproxy_qws.cpp.
 {
     if (!realScreen)
         return QScreen::mapToDevice(r, s);
     return realScreen->mapToDevice(r, s);
 }
mapToDevice() [4/4]
QRegion QProxyScreen::mapToDevice (const QRegion & r, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 397 of file qscreenproxy_qws.cpp.
 {
     if (!realScreen)
         return QScreen::mapToDevice(r, s);
     return realScreen->mapToDevice(r, s);
 }
memoryNeeded()
int QProxyScreen::memoryNeeded (const QString & str) virtual
Warning
This function is not part of the public interface.
Reimplemented from QScreen.
Definition at line 555 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         return realScreen->memoryNeeded(str);
     else
         return QScreen::memoryNeeded(str);
 }
onCard() [1/2]
bool QProxyScreen::onCard (const unsigned char * ptr) const virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 505 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         return realScreen->onCard(ptr);
     return false;
 }
onCard() [2/2]
bool QProxyScreen::onCard (const unsigned char * ptr, ulong & out_offset) const virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 515 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         return realScreen->onCard(ptr, offset);
     return false;
 }
region()
QRegion QProxyScreen::region () const virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 637 of file qscreenproxy_qws.cpp.
Referenced by QTransformedScreen::isTransformed(), QTransformedScreen::region(), and setMode().
 {
     if (realScreen)
         return realScreen->region();
     else
         return QScreen::region();
 }
restore()
void QProxyScreen::restore () virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 486 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         realScreen->restore();
     QScreen::restore();
 }
resumeUpdates()
void QProxyScreen::resumeUpdates () virtual
Warning
This function is not part of the public interface.
Reimplemented from QScreen.
Definition at line 586 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         realScreen->resumeUpdates();
 }
save()
void QProxyScreen::save () virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 476 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         realScreen->save();
     QScreen::save();
 }
screen()
QScreen * QProxyScreen::screen () const
Returns the real screen used by the proxy screen.
See also
setScreen()
Definition at line 217 of file qscreenproxy_qws.cpp.
Referenced by QVNCScreenPrivate::configure(), QVNCScreen::initDevice(), QVNCIntegration::isVirtualDesktop(), QVNCServer::newConnection(), QVNCServer::setEncodings(), setScreen(), QApplicationPrivate::setScreenTransformation(), QTransformedScreen::setTransformation(), and QVNCScreenPrivate::~QVNCScreenPrivate().
 {
     return realScreen;
 }
setDirty()
void QProxyScreen::setDirty (const QRect & rect) virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen, and QVNCScreen.
Definition at line 595 of file qscreenproxy_qws.cpp.
Referenced by exposeRegion(), QTransformedScreen::isTransformed(), and QTransformedScreen::setDirty().
 {
     if (realScreen)
         realScreen->setDirty(rect);
 }
setMode()
void QProxyScreen::setMode (int width, int height, int depth) virtual
Reimplemented Function
Implements QScreen.
Definition at line 450 of file qscreenproxy_qws.cpp.
 {
     if (realScreen) {
         realScreen->setMode(w, h, d);
     } else {
         QScreen::dw = QScreen::w = w;
         QScreen::dh = QScreen::h = h;
         QScreen::d = d;
     }
     configure();
     exposeRegion(region(), 0);
 }
setScreen()
void QProxyScreen::setScreen (QScreen * screen)
Sets the real screen to be used by the proxy screen.
See also
screen()
Definition at line 206 of file qscreenproxy_qws.cpp.
Referenced by QVNCScreen::connect(), QTransformedScreen::connect(), and QApplicationPrivate::setScreenTransformation().
 {
     realScreen = screen;
     configure();
 }
sharedRamSize()
int QProxyScreen::sharedRamSize (void * ptr) virtual
Warning
This function is not part of the public interface.
Reimplemented from QScreen.
Definition at line 566 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         return realScreen->sharedRamSize(ptr);
     else
         return QScreen::sharedRamSize(ptr);
 }
shutdownDevice()
void QProxyScreen::shutdownDevice () virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QVNCScreen.
Definition at line 441 of file qscreenproxy_qws.cpp.
Referenced by QVNCScreen::shutdownDevice().
 {
     if (realScreen)
         realScreen->shutdownDevice();
 }
solidFill()
void QProxyScreen::solidFill (const QColor & color, const QRegion & region) virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 319 of file qscreenproxy_qws.cpp.
Referenced by QTransformedScreen::isTransformed(), and QTransformedScreen::solidFill().
 {
     if (!realScreen) {
         QScreen::solidFill(color, region);
         return;
     }
     realScreen->solidFill(color, region);
 }
subScreens()
QList< QScreen * > QProxyScreen::subScreens () const virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 626 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         return realScreen->subScreens();
     return QScreen::subScreens();
 }
supportsDepth()
bool QProxyScreen::supportsDepth (int depth) const virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 466 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         return realScreen->supportsDepth(depth);
     return false;
 }
transformOrientation()
int QProxyScreen::transformOrientation () const virtual
Reimplemented Function
Reimplemented from QScreen.
Reimplemented in QTransformedScreen.
Definition at line 545 of file qscreenproxy_qws.cpp.
 {
     if (realScreen)
         return realScreen->transformOrientation();
     return QScreen::transformOrientation();
 }
Properties
d_ptr
QProxyScreenPrivate* QProxyScreen::d_ptr private
Definition at line 145 of file qscreenproxy_qws.h.
realScreen
QScreen* QProxyScreen::realScreen private
Definition at line 144 of file qscreenproxy_qws.h.
Referenced by blank(), blit(), configure(), connect(), createSurface(), disconnect(), exposeRegion(), haltUpdates(), initDevice(), isInterlaced(), isTransformed(), mapFromDevice(), mapToDevice(), memoryNeeded(), onCard(), region(), restore(), resumeUpdates(), save(), screen(), setDirty(), setMode(), setScreen(), sharedRamSize(), shutdownDevice(), solidFill(), subScreens(), supportsDepth(), and transformOrientation().
The documentation for this class was generated from the following files:
/src/gui/embedded/qscreenproxy_qws.h
/src/gui/embedded/qscreenproxy_qws.cpp