Qt 4.8: QDeclarativeMetaType Class Reference
QDeclarativeMetaType Class Reference
#include <qdeclarativemetatype_p.h>
Public Types
typedef QVariant(* StringConverter) (const QString &)
enum TypeCategory { Unknown, Object, List }
Static Public Functions
static QDeclarativeAttachedPropertiesFunc attachedPropertiesFuncById (int)
static int attachedPropertiesFuncId (const QMetaObject *)
static bool canCopy (int type)
static bool copy (int type, void *data, const void *copy=0)
Copies copy into data, assuming they both are of type type.
static StringConverter customStringConverter (int)
Return the custom string converter for type, previously installed through registerCustomStringConverter()
static QMetaMethod defaultMethod (const QMetaObject *)
static QMetaMethod defaultMethod (QObject *)
static QMetaProperty defaultProperty (const QMetaObject *)
static QMetaProperty defaultProperty (QObject *)
static const char * interfaceIId (int)
static bool isInterface (int)
static bool isList (int)
static bool isModule (const QByteArray &module, int versionMajor, int versionMinor)
static bool isQObject (int)
static int listType (int)
static QList< QDeclarativePrivate::AutoParentFunction > parentFunctions ()
static QDeclarativeDirComponents qmlComponents (const QByteArray &module, int version_major, int version_minor)
Returns the component(s) that have been registered for the module specified by uri and the version specified by version_major and version_minor.
static QDeclarativeType * qmlType (const QByteArray &, int, int)
Returns the type (if any) of URI-qualified named name in version specified by version_major and version_minor.
static QDeclarativeType * qmlType (const QMetaObject *)
Returns the type (if any) that corresponds to the metaObject.
static QDeclarativeType * qmlType (const QMetaObject *metaObject, const QByteArray &module, int version_major, int version_minor)
Returns the type (if any) that corresponds to the metaObject in version specified by version_major and version_minor in module specified by uri.
static QDeclarativeType * qmlType (int)
Returns the type (if any) that corresponds to the QVariant::Type userType.
static QList< QByteArray > qmlTypeNames ()
Returns the list of registered QML type names.
static QList< QDeclarativeType * > qmlTypes ()
Returns the list of registered QML types.
static void registerCustomStringConverter (int, StringConverter)
A custom string convertor allows you to specify a function pointer that returns a variant of type.
static QObject * toQObject (const QVariant &, bool *ok=0)
static TypeCategory typeCategory (int)
Detailed Description
Definition at line 70 of file qdeclarativemetatype_p.h.
Typedefs
StringConverter
typedef QVariant(* QDeclarativeMetaType::StringConverter) (const QString &)
Definition at line 105 of file qdeclarativemetatype_p.h.
Enumerations
TypeCategory
enum QDeclarativeMetaType::TypeCategory
Enumerator
Unknown
Object
List
Definition at line 98 of file qdeclarativemetatype_p.h.
 { Unknown, Object, List };
Functions
attachedPropertiesFuncById()
QDeclarativeAttachedPropertiesFunc QDeclarativeMetaType::attachedPropertiesFuncById (int id) static
Definition at line 828 of file qdeclarativemetatype.cpp.
Referenced by qmlAttachedPropertiesObjectById().
 {
     if (id < 0)
         return 0;
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     return data->types.at(id)->attachedPropertiesFunction();
 }
attachedPropertiesFuncId()
int QDeclarativeMetaType::attachedPropertiesFuncId (const QMetaObject * mo) static
Definition at line 816 of file qdeclarativemetatype.cpp.
Referenced by qmlAttachedPropertiesObject().
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     QDeclarativeType *type = data->metaObjectToType.value(mo);
     if (type && type->attachedPropertiesFunction())
         return type->attachedPropertiesId();
     else
         return -1;
 }
canCopy()
bool QDeclarativeMetaType::canCopy (int type) static
Definition at line 1112 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters().
 {
     switch(type) {
     case QMetaType::VoidStar:
     case QMetaType::QObjectStar:
     case QMetaType::QWidgetStar:
     case QMetaType::Long:
     case QMetaType::Int:
     case QMetaType::Short:
     case QMetaType::Char:
     case QMetaType::ULong:
     case QMetaType::UInt:
     case QMetaType::LongLong:
     case QMetaType::ULongLong:
     case QMetaType::UShort:
     case QMetaType::UChar:
     case QMetaType::Bool:
     case QMetaType::Float:
     case QMetaType::Double:
     case QMetaType::QChar:
     case QMetaType::QVariantMap:
     case QMetaType::QVariantHash:
     case QMetaType::QVariantList:
     case QMetaType::QByteArray:
     case QMetaType::QString:
     case QMetaType::QStringList:
     case QMetaType::QBitArray:
     case QMetaType::QDate:
     case QMetaType::QTime:
     case QMetaType::QDateTime:
     case QMetaType::QUrl:
     case QMetaType::QLocale:
     case QMetaType::QRect:
     case QMetaType::QRectF:
     case QMetaType::QSize:
     case QMetaType::QSizeF:
     case QMetaType::QLine:
     case QMetaType::QLineF:
     case QMetaType::QPoint:
     case QMetaType::QPointF:
     case QMetaType::QVector3D:
 #ifndef QT_NO_REGEXP
     case QMetaType::QRegExp:
 #endif
     case QMetaType::Void:
 #ifdef QT3_SUPPORT
     case QMetaType::QColorGroup:
 #endif
     case QMetaType::QFont:
     case QMetaType::QPixmap:
     case QMetaType::QBrush:
     case QMetaType::QColor:
     case QMetaType::QPalette:
     case QMetaType::QIcon:
     case QMetaType::QImage:
     case QMetaType::QPolygon:
     case QMetaType::QRegion:
     case QMetaType::QBitmap:
 #ifndef QT_NO_CURSOR
     case QMetaType::QCursor:
 #endif
     case QMetaType::QSizePolicy:
     case QMetaType::QKeySequence:
     case QMetaType::QPen:
     case QMetaType::QTextLength:
     case QMetaType::QTextFormat:
     case QMetaType::QMatrix:
     case QMetaType::QTransform:
     case QMetaType::QMatrix4x4:
     case QMetaType::QVector2D:
     case QMetaType::QVector4D:
     case QMetaType::QQuaternion:
         return true;
     default:
         if (type == qMetaTypeId<QVariant>() ||
             type == qMetaTypeId<QScriptValue>() ||
             typeCategory(type) != Unknown) {
             return true;
         }
         break;
     }
     return false;
 }
copy()
bool QDeclarativeMetaType::copy (int type, void * data, const void * copy = 0) static
Copies copy into data, assuming they both are of type type.
If copy is zero, a default type is copied. Returns true if the copy was successful and false if not.
Note
This should move into QMetaType once complete
Definition at line 1206 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeBoundSignalParameters::metaCall().
 {
     if (copy) {
         switch(type) {
         case QMetaType::VoidStar:
         case QMetaType::QObjectStar:
         case QMetaType::QWidgetStar:
             *static_cast<void **>(data) = *static_cast<void* const *>(copy);
             return true;
         case QMetaType::Long:
             *static_cast<long *>(data) = *static_cast<const long*>(copy);
             return true;
         case QMetaType::Int:
             *static_cast<int *>(data) = *static_cast<const int*>(copy);
             return true;
         case QMetaType::Short:
             *static_cast<short *>(data) = *static_cast<const short*>(copy);
             return true;
         case QMetaType::Char:
             *static_cast<char *>(data) = *static_cast<const char*>(copy);
             return true;
         case QMetaType::ULong:
             *static_cast<ulong *>(data) = *static_cast<const ulong*>(copy);
             return true;
         case QMetaType::UInt:
             *static_cast<uint *>(data) = *static_cast<const uint*>(copy);
             return true;
         case QMetaType::LongLong:
             *static_cast<qlonglong *>(data) = *static_cast<const qlonglong*>(copy);
             return true;
         case QMetaType::ULongLong:
             *static_cast<qulonglong *>(data) = *static_cast<const qulonglong*>(copy);
             return true;
         case QMetaType::UShort:
             *static_cast<ushort *>(data) = *static_cast<const ushort*>(copy);
             return true;
         case QMetaType::UChar:
             *static_cast<uchar *>(data) = *static_cast<const uchar*>(copy);
             return true;
         case QMetaType::Bool:
             *static_cast<bool *>(data) = *static_cast<const bool*>(copy);
             return true;
         case QMetaType::Float:
             *static_cast<float *>(data) = *static_cast<const float*>(copy);
             return true;
         case QMetaType::Double:
             *static_cast<double *>(data) = *static_cast<const double*>(copy);
             return true;
         case QMetaType::QChar:
             *static_cast<NS(QChar) *>(data) = *static_cast<const NS(QChar)*>(copy);
             return true;
         case QMetaType::QVariantMap:
             *static_cast<NS(QVariantMap) *>(data) = *static_cast<const NS(QVariantMap)*>(copy);
             return true;
         case QMetaType::QVariantHash:
             *static_cast<NS(QVariantHash) *>(data) = *static_cast<const NS(QVariantHash)*>(copy);
             return true;
         case QMetaType::QVariantList:
             *static_cast<NS(QVariantList) *>(data) = *static_cast<const NS(QVariantList)*>(copy);
             return true;
         case QMetaType::QByteArray:
             *static_cast<NS(QByteArray) *>(data) = *static_cast<const NS(QByteArray)*>(copy);
             return true;
         case QMetaType::QString:
             *static_cast<NS(QString) *>(data) = *static_cast<const NS(QString)*>(copy);
             return true;
         case QMetaType::QStringList:
             *static_cast<NS(QStringList) *>(data) = *static_cast<const NS(QStringList)*>(copy);
             return true;
         case QMetaType::QBitArray:
             *static_cast<NS(QBitArray) *>(data) = *static_cast<const NS(QBitArray)*>(copy);
             return true;
         case QMetaType::QDate:
             *static_cast<NS(QDate) *>(data) = *static_cast<const NS(QDate)*>(copy);
             return true;
         case QMetaType::QTime:
             *static_cast<NS(QTime) *>(data) = *static_cast<const NS(QTime)*>(copy);
             return true;
         case QMetaType::QDateTime:
             *static_cast<NS(QDateTime) *>(data) = *static_cast<const NS(QDateTime)*>(copy);
             return true;
         case QMetaType::QUrl:
             *static_cast<NS(QUrl) *>(data) = *static_cast<const NS(QUrl)*>(copy);
             return true;
         case QMetaType::QLocale:
             *static_cast<NS(QLocale) *>(data) = *static_cast<const NS(QLocale)*>(copy);
             return true;
         case QMetaType::QRect:
             *static_cast<NS(QRect) *>(data) = *static_cast<const NS(QRect)*>(copy);
             return true;
         case QMetaType::QRectF:
             *static_cast<NS(QRectF) *>(data) = *static_cast<const NS(QRectF)*>(copy);
             return true;
         case QMetaType::QSize:
             *static_cast<NS(QSize) *>(data) = *static_cast<const NS(QSize)*>(copy);
             return true;
         case QMetaType::QSizeF:
             *static_cast<NS(QSizeF) *>(data) = *static_cast<const NS(QSizeF)*>(copy);
             return true;
         case QMetaType::QLine:
             *static_cast<NS(QLine) *>(data) = *static_cast<const NS(QLine)*>(copy);
             return true;
         case QMetaType::QLineF:
             *static_cast<NS(QLineF) *>(data) = *static_cast<const NS(QLineF)*>(copy);
             return true;
         case QMetaType::QPoint:
             *static_cast<NS(QPoint) *>(data) = *static_cast<const NS(QPoint)*>(copy);
             return true;
         case QMetaType::QPointF:
             *static_cast<NS(QPointF) *>(data) = *static_cast<const NS(QPointF)*>(copy);
             return true;
         case QMetaType::QVector3D:
             *static_cast<NS(QVector3D) *>(data) = *static_cast<const NS(QVector3D)*>(copy);
             return true;
 #ifndef QT_NO_REGEXP
         case QMetaType::QRegExp:
             *static_cast<NS(QRegExp) *>(data) = *static_cast<const NS(QRegExp)*>(copy);
             return true;
 #endif
         case QMetaType::Void:
             return true;
 #ifdef QT3_SUPPORT
         case QMetaType::QColorGroup:
             *static_cast<NS(QColorGroup) *>(data) = *static_cast<const NS(QColorGroup)*>(copy);
             return true;
 #endif
         case QMetaType::QFont:
             *static_cast<NS(QFont) *>(data) = *static_cast<const NS(QFont)*>(copy);
             return true;
         case QMetaType::QPixmap:
             *static_cast<NS(QPixmap) *>(data) = *static_cast<const NS(QPixmap)*>(copy);
             return true;
         case QMetaType::QBrush:
             *static_cast<NS(QBrush) *>(data) = *static_cast<const NS(QBrush)*>(copy);
             return true;
         case QMetaType::QColor:
             *static_cast<NS(QColor) *>(data) = *static_cast<const NS(QColor)*>(copy);
             return true;
         case QMetaType::QPalette:
             *static_cast<NS(QPalette) *>(data) = *static_cast<const NS(QPalette)*>(copy);
             return true;
         case QMetaType::QIcon:
             *static_cast<NS(QIcon) *>(data) = *static_cast<const NS(QIcon)*>(copy);
             return true;
         case QMetaType::QImage:
             *static_cast<NS(QImage) *>(data) = *static_cast<const NS(QImage)*>(copy);
             return true;
         case QMetaType::QPolygon:
             *static_cast<NS(QPolygon) *>(data) = *static_cast<const NS(QPolygon)*>(copy);
             return true;
         case QMetaType::QRegion:
             *static_cast<NS(QRegion) *>(data) = *static_cast<const NS(QRegion)*>(copy);
             return true;
         case QMetaType::QBitmap:
             *static_cast<NS(QBitmap) *>(data) = *static_cast<const NS(QBitmap)*>(copy);
             return true;
 #ifndef QT_NO_CURSOR
         case QMetaType::QCursor:
             *static_cast<NS(QCursor) *>(data) = *static_cast<const NS(QCursor)*>(copy);
             return true;
 #endif
         case QMetaType::QSizePolicy:
             *static_cast<NS(QSizePolicy) *>(data) = *static_cast<const NS(QSizePolicy)*>(copy);
             return true;
         case QMetaType::QKeySequence:
             *static_cast<NS(QKeySequence) *>(data) = *static_cast<const NS(QKeySequence)*>(copy);
             return true;
         case QMetaType::QPen:
             *static_cast<NS(QPen) *>(data) = *static_cast<const NS(QPen)*>(copy);
             return true;
         case QMetaType::QTextLength:
             *static_cast<NS(QTextLength) *>(data) = *static_cast<const NS(QTextLength)*>(copy);
             return true;
         case QMetaType::QTextFormat:
             *static_cast<NS(QTextFormat) *>(data) = *static_cast<const NS(QTextFormat)*>(copy);
             return true;
         case QMetaType::QMatrix:
             *static_cast<NS(QMatrix) *>(data) = *static_cast<const NS(QMatrix)*>(copy);
             return true;
         case QMetaType::QTransform:
             *static_cast<NS(QTransform) *>(data) = *static_cast<const NS(QTransform)*>(copy);
             return true;
         case QMetaType::QMatrix4x4:
             *static_cast<NS(QMatrix4x4) *>(data) = *static_cast<const NS(QMatrix4x4)*>(copy);
             return true;
         case QMetaType::QVector2D:
             *static_cast<NS(QVector2D) *>(data) = *static_cast<const NS(QVector2D)*>(copy);
             return true;
         case QMetaType::QVector4D:
             *static_cast<NS(QVector4D) *>(data) = *static_cast<const NS(QVector4D)*>(copy);
             return true;
         case QMetaType::QQuaternion:
             *static_cast<NS(QQuaternion) *>(data) = *static_cast<const NS(QQuaternion)*>(copy);
             return true;
         default:
             if (type == qMetaTypeId<QVariant>()) {
                 *static_cast<NS(QVariant) *>(data) = *static_cast<const NS(QVariant)*>(copy);
                 return true;
             } else if (type == qMetaTypeId<QScriptValue>()) {
                 *static_cast<NS(QScriptValue) *>(data) = *static_cast<const NS(QScriptValue)*>(copy);
                 return true;
             } else if (typeCategory(type) != Unknown) {
                 *static_cast<void **>(data) = *static_cast<void* const *>(copy);
                 return true;
             }
             break;
         }
     } else {
         switch(type) {
         case QMetaType::VoidStar:
         case QMetaType::QObjectStar:
         case QMetaType::QWidgetStar:
             *static_cast<void **>(data) = 0;
             return true;
         case QMetaType::Long:
             *static_cast<long *>(data) = long(0);
             return true;
         case QMetaType::Int:
             *static_cast<int *>(data) = int(0);
             return true;
         case QMetaType::Short:
             *static_cast<short *>(data) = short(0);
             return true;
         case QMetaType::Char:
             *static_cast<char *>(data) = char(0);
             return true;
         case QMetaType::ULong:
             *static_cast<ulong *>(data) = ulong(0);
             return true;
         case QMetaType::UInt:
             *static_cast<uint *>(data) = uint(0);
             return true;
         case QMetaType::LongLong:
             *static_cast<qlonglong *>(data) = qlonglong(0);
             return true;
         case QMetaType::ULongLong:
             *static_cast<qulonglong *>(data) = qulonglong(0);
             return true;
         case QMetaType::UShort:
             *static_cast<ushort *>(data) = ushort(0);
             return true;
         case QMetaType::UChar:
             *static_cast<uchar *>(data) = uchar(0);
             return true;
         case QMetaType::Bool:
             *static_cast<bool *>(data) = bool(false);
             return true;
         case QMetaType::Float:
             *static_cast<float *>(data) = float(0);
             return true;
         case QMetaType::Double:
             *static_cast<double *>(data) = double(0);
             return true;
         case QMetaType::QChar:
             *static_cast<NS(QChar) *>(data) = NS(QChar)();
             return true;
         case QMetaType::QVariantMap:
             *static_cast<NS(QVariantMap) *>(data) = NS(QVariantMap)();
             return true;
         case QMetaType::QVariantHash:
             *static_cast<NS(QVariantHash) *>(data) = NS(QVariantHash)();
             return true;
         case QMetaType::QVariantList:
             *static_cast<NS(QVariantList) *>(data) = NS(QVariantList)();
             return true;
         case QMetaType::QByteArray:
             *static_cast<NS(QByteArray) *>(data) = NS(QByteArray)();
             return true;
         case QMetaType::QString:
             *static_cast<NS(QString) *>(data) = NS(QString)();
             return true;
         case QMetaType::QStringList:
             *static_cast<NS(QStringList) *>(data) = NS(QStringList)();
             return true;
         case QMetaType::QBitArray:
             *static_cast<NS(QBitArray) *>(data) = NS(QBitArray)();
             return true;
         case QMetaType::QDate:
             *static_cast<NS(QDate) *>(data) = NS(QDate)();
             return true;
         case QMetaType::QTime:
             *static_cast<NS(QTime) *>(data) = NS(QTime)();
             return true;
         case QMetaType::QDateTime:
             *static_cast<NS(QDateTime) *>(data) = NS(QDateTime)();
             return true;
         case QMetaType::QUrl:
             *static_cast<NS(QUrl) *>(data) = NS(QUrl)();
             return true;
         case QMetaType::QLocale:
             *static_cast<NS(QLocale) *>(data) = NS(QLocale)();
             return true;
         case QMetaType::QRect:
             *static_cast<NS(QRect) *>(data) = NS(QRect)();
             return true;
         case QMetaType::QRectF:
             *static_cast<NS(QRectF) *>(data) = NS(QRectF)();
             return true;
         case QMetaType::QSize:
             *static_cast<NS(QSize) *>(data) = NS(QSize)();
             return true;
         case QMetaType::QSizeF:
             *static_cast<NS(QSizeF) *>(data) = NS(QSizeF)();
             return true;
         case QMetaType::QLine:
             *static_cast<NS(QLine) *>(data) = NS(QLine)();
             return true;
         case QMetaType::QLineF:
             *static_cast<NS(QLineF) *>(data) = NS(QLineF)();
             return true;
         case QMetaType::QPoint:
             *static_cast<NS(QPoint) *>(data) = NS(QPoint)();
             return true;
         case QMetaType::QPointF:
             *static_cast<NS(QPointF) *>(data) = NS(QPointF)();
             return true;
         case QMetaType::QVector3D:
             *static_cast<NS(QVector3D) *>(data) = NS(QVector3D)();
             return true;
 #ifndef QT_NO_REGEXP
         case QMetaType::QRegExp:
             *static_cast<NS(QRegExp) *>(data) = NS(QRegExp)();
             return true;
 #endif
         case QMetaType::Void:
             return true;
 #ifdef QT3_SUPPORT
         case QMetaType::QColorGroup:
             *static_cast<NS(QColorGroup) *>(data) = NS(QColorGroup)();
             return true;
 #endif
         case QMetaType::QFont:
             *static_cast<NS(QFont) *>(data) = NS(QFont)();
             return true;
         case QMetaType::QPixmap:
             *static_cast<NS(QPixmap) *>(data) = NS(QPixmap)();
             return true;
         case QMetaType::QBrush:
             *static_cast<NS(QBrush) *>(data) = NS(QBrush)();
             return true;
         case QMetaType::QColor:
             *static_cast<NS(QColor) *>(data) = NS(QColor)();
             return true;
         case QMetaType::QPalette:
             *static_cast<NS(QPalette) *>(data) = NS(QPalette)();
             return true;
         case QMetaType::QIcon:
             *static_cast<NS(QIcon) *>(data) = NS(QIcon)();
             return true;
         case QMetaType::QImage:
             *static_cast<NS(QImage) *>(data) = NS(QImage)();
             return true;
         case QMetaType::QPolygon:
             *static_cast<NS(QPolygon) *>(data) = NS(QPolygon)();
             return true;
         case QMetaType::QRegion:
             *static_cast<NS(QRegion) *>(data) = NS(QRegion)();
             return true;
         case QMetaType::QBitmap:
             *static_cast<NS(QBitmap) *>(data) = NS(QBitmap)();
             return true;
 #ifndef QT_NO_CURSOR
         case QMetaType::QCursor:
             *static_cast<NS(QCursor) *>(data) = NS(QCursor)();
             return true;
 #endif
         case QMetaType::QSizePolicy:
             *static_cast<NS(QSizePolicy) *>(data) = NS(QSizePolicy)();
             return true;
         case QMetaType::QKeySequence:
             *static_cast<NS(QKeySequence) *>(data) = NS(QKeySequence)();
             return true;
         case QMetaType::QPen:
             *static_cast<NS(QPen) *>(data) = NS(QPen)();
             return true;
         case QMetaType::QTextLength:
             *static_cast<NS(QTextLength) *>(data) = NS(QTextLength)();
             return true;
         case QMetaType::QTextFormat:
             *static_cast<NS(QTextFormat) *>(data) = NS(QTextFormat)();
             return true;
         case QMetaType::QMatrix:
             *static_cast<NS(QMatrix) *>(data) = NS(QMatrix)();
             return true;
         case QMetaType::QTransform:
             *static_cast<NS(QTransform) *>(data) = NS(QTransform)();
             return true;
         case QMetaType::QMatrix4x4:
             *static_cast<NS(QMatrix4x4) *>(data) = NS(QMatrix4x4)();
             return true;
         case QMetaType::QVector2D:
             *static_cast<NS(QVector2D) *>(data) = NS(QVector2D)();
             return true;
         case QMetaType::QVector4D:
             *static_cast<NS(QVector4D) *>(data) = NS(QVector4D)();
             return true;
         case QMetaType::QQuaternion:
             *static_cast<NS(QQuaternion) *>(data) = NS(QQuaternion)();
             return true;
         default:
             if (type == qMetaTypeId<QVariant>()) {
                 *static_cast<NS(QVariant) *>(data) = NS(QVariant)();
                 return true;
             } else if (type == qMetaTypeId<QScriptValue>()) {
                 *static_cast<NS(QScriptValue) *>(data) = NS(QScriptValue)();
                 return true;
             } else if (typeCategory(type) != Unknown) {
                 *static_cast<void **>(data) = 0;
                 return true;
             }
             break;
         }
     }
     return false;
 }
customStringConverter()
QDeclarativeMetaType::StringConverter QDeclarativeMetaType::customStringConverter (int type) static
Return the custom string converter for type, previously installed through registerCustomStringConverter()
Definition at line 961 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativePropertyAnimationPrivate::convertVariant(), QDeclarativeCompiler::testLiteralAssignment(), and QDeclarativePropertyPrivate::write().
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     return data->stringConverters.value(type);
 }
defaultMethod() [1/2]
QMetaMethod QDeclarativeMetaType::defaultMethod (const QMetaObject * metaObject) static
Definition at line 863 of file qdeclarativemetatype.cpp.
 {
     int idx = metaObject->indexOfClassInfo("DefaultMethod");
     if (-1 == idx)
         return QMetaMethod();
     QMetaClassInfo info = metaObject->classInfo(idx);
     if (!info.value())
         return QMetaMethod();
     idx = metaObject->indexOfMethod(info.value());
     if (-1 == idx)
         return QMetaMethod();
     return metaObject->method(idx);
 }
defaultMethod() [2/2]
QMetaMethod QDeclarativeMetaType::defaultMethod (QObject * obj) static
Definition at line 880 of file qdeclarativemetatype.cpp.
 {
     if (!obj)
         return QMetaMethod();
     const QMetaObject *metaObject = obj->metaObject();
     return defaultMethod(metaObject);
 }
defaultProperty() [1/2]
QMetaProperty QDeclarativeMetaType::defaultProperty (const QMetaObject * metaObject) static
Definition at line 837 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::buildObject(), QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::doesPropertyExist(), and QDeclarativePropertyPrivate::initDefault().
 {
     int idx = metaObject->indexOfClassInfo("DefaultProperty");
     if (-1 == idx)
         return QMetaProperty();
     QMetaClassInfo info = metaObject->classInfo(idx);
     if (!info.value())
         return QMetaProperty();
     idx = metaObject->indexOfProperty(info.value());
     if (-1 == idx)
         return QMetaProperty();
     return metaObject->property(idx);
 }
defaultProperty() [2/2]
QMetaProperty QDeclarativeMetaType::defaultProperty (QObject * obj) static
Definition at line 854 of file qdeclarativemetatype.cpp.
 {
     if (!obj)
         return QMetaProperty();
     const QMetaObject *metaObject = obj->metaObject();
     return defaultProperty(metaObject);
 }
interfaceIId()
const char * QDeclarativeMetaType::interfaceIId (int userType) static
Definition at line 913 of file qdeclarativemetatype.cpp.
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     QDeclarativeType *type = data->idToType.value(userType);
     lock.unlock();
     if (type && type->isInterface() && type->typeId() == userType)
         return type->interfaceIId();
     else
         return 0;
 }
isInterface()
bool QDeclarativeMetaType::isInterface (int userType) static
Definition at line 906 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::buildListProperty(), QDeclarativeCompiler::buildPropertyObjectAssignment(), QDeclarativeCompiler::genListProperty(), and QDeclarativeCompiler::genPropertyAssignment().
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     return userType >= 0 && userType < data->interfaces.size() && data->interfaces.testBit(userType);
 }
isList()
bool QDeclarativeMetaType::isList (int userType) static
Definition at line 925 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::buildBinding(), QDeclarativeEnginePrivate::isList(), QDeclarativeEngineDebugService::propertyData(), and QDeclarativeDomValue::type().
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     return userType >= 0 && userType < data->lists.size() && data->lists.testBit(userType);
 }
isModule()
bool QDeclarativeMetaType::isModule (const QByteArray & module, int versionMajor, int versionMinor) static
Definition at line 744 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeImportsPrivate::add().
 {
 #ifndef QT_NO_IMPORT_QT47_QML
     // "import Qt 4.7" should have died off, but unfortunately, it was in a
     // major release. We don't register 4.7 types by default, as it's a
     // performance penalty. Instead, register them on-demand.
     if (strcmp(module.constData(), "Qt") == 0 && versionMajor == 4 && versionMinor == 7) {
         static bool qt47Registered = false;
         if (!qt47Registered) {
             qWarning() << Q_FUNC_INFO << "Qt 4.7 import detected; please note that Qt 4.7 is directly reusable as QtQuick 1.x with no code changes. Continuing, but startup time will be slower.";
             qt47Registered = true;
             QDeclarativeEnginePrivate::defineModuleCompat();
             QDeclarativeItemModule::defineModuleCompat();
             QDeclarativeValueTypeFactory::registerValueTypesCompat();
             QDeclarativeUtilModule::defineModuleCompat();
         }
     }
 #endif
     QDeclarativeMetaTypeData *data = metaTypeData();
     QDeclarativeMetaTypeData::ModuleInfoHash::Iterator it = data->modules.find(module);
     return it != data->modules.end()
         && ((versionMajor<0 && versionMinor<0) ||
                 (((*it).vmajor_max > versionMajor ||
                     ((*it).vmajor_max == versionMajor && (*it).vminor_max >= versionMinor))
                 && ((*it).vmajor_min < versionMajor ||
                     ((*it).vmajor_min == versionMajor && (*it).vminor_min <= versionMinor))));
 }
isQObject()
bool QDeclarativeMetaType::isQObject (int userType) static
Definition at line 792 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeEnginePrivate::isQObject(), QDeclarativeEngineDebugService::propertyData(), QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters(), QDeclarativeListAccessor::setList(), and QDeclarativeEngineDebugService::valueContents().
 {
     if (userType == QMetaType::QObjectStar)
         return true;
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     return userType >= 0 && userType < data->objects.size() && data->objects.testBit(userType);
 }
listType()
int QDeclarativeMetaType::listType (int id) static
Definition at line 805 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeListReferencePrivate::init(), QDeclarativeEnginePrivate::listType(), QDeclarativeListReference::QDeclarativeListReference(), and QDeclarativePropertyPrivate::write().
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     QDeclarativeType *type = data->idToType.value(id);
     if (type && type->qListTypeId() == id)
         return type->typeId();
     else
         return 0;
 }
parentFunctions()
QList< QDeclarativePrivate::AutoParentFunction > QDeclarativeMetaType::parentFunctions () static
Definition at line 773 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeComponentPrivate::createObject(), and QDeclarativeEnginePrivate::createQmlObject().
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     return data->parentFunctions;
 }
qmlComponents()
QDeclarativeDirComponents QDeclarativeMetaType::qmlComponents (const QByteArray & module, int version_major, int version_minor) static
Returns the component(s) that have been registered for the module specified by uri and the version specified by version_major and version_minor.
Returns an empty list if no such components were registered.
Definition at line 1040 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeImportsPrivate::add().
 {
     QReadLocker lock(registeredComponentDataLock());
     QDeclarativeRegisteredComponentData *data = registeredComponentData();
     QDeclarativeDirComponents* comps = data->registeredComponents.value(module, 0);
     if (!comps)
         return QDeclarativeDirComponents();
     QDeclarativeDirComponents ret = *comps;
     for (int i = ret.count() - 1; i >= 0; i--) {
         QDeclarativeDirParser::Component &c = ret[i];
         if (version_major >= 0 && (c.majorVersion != version_major || c.minorVersion > version_minor))
             ret.removeAt(i);
     }
     return ret;
 }
qmlType() [1/4]
QDeclarativeType * QDeclarativeMetaType::qmlType (const QByteArray & name, int version_major, int version_minor) static
Returns the type (if any) of URI-qualified named name in version specified by version_major and version_minor.
Definition at line 973 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::componentTypeRef(), QDeclarativeEnginePrivate::createCache(), QDeclarativeImportedNamespace::find_helper(), QDeclarativeListReferencePrivate::init(), QDeclarativeEnginePrivate::metaObjectForType(), QDeclarativeEngineDebugService::objectData(), QDeclarativeListReference::QDeclarativeListReference(), qmlExecuteDeferred(), QDeclarativePropertyPrivate::rawMetaObjectForType(), QDeclarativeEnginePrivate::rawMetaObjectForType(), QDeclarativeEngineDebugService::resetBinding(), QDeclarativeType::superType(), QDeclarativeCompiler::toQmlType(), QDeclarativePropertyPrivate::write(), and QDeclarativeInfo::~QDeclarativeInfo().
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     QList<QDeclarativeType*> types = data->nameToType.values(name);
     foreach (QDeclarativeType *t, types) {
         // XXX version_major<0 just a kludge for QDeclarativePropertyPrivate::initProperty
         if (version_major<0 || t->availableInVersion(version_major,version_minor))
             return t;
     }
     return 0;
 }
qmlType() [2/4]
QDeclarativeType * QDeclarativeMetaType::qmlType (const QMetaObject * metaObject) static
Returns the type (if any) that corresponds to the metaObject.
Returns null if no type is registered.
Definition at line 991 of file qdeclarativemetatype.cpp.
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     return data->metaObjectToType.value(metaObject);
 }
qmlType() [3/4]
QDeclarativeType * QDeclarativeMetaType::qmlType (const QMetaObject * metaObject, const QByteArray & module, int version_major, int version_minor) static
Returns the type (if any) that corresponds to the metaObject in version specified by version_major and version_minor in module specified by uri.
Returns null if no type is registered.
Definition at line 1004 of file qdeclarativemetatype.cpp.
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     QDeclarativeMetaTypeData::MetaObjects::const_iterator it = data->metaObjectToType.find(metaObject);
     while (it != data->metaObjectToType.end() && it.key() == metaObject) {
         QDeclarativeType *t = *it;
         if (version_major < 0 || t->availableInVersion(module, version_major,version_minor))
             return t;
         ++it;
     }
     return 0;
 }
qmlType() [4/4]
QDeclarativeType * QDeclarativeMetaType::qmlType (int userType) static
Returns the type (if any) that corresponds to the QVariant::Type userType.
Returns null if no type is registered.
Definition at line 1024 of file qdeclarativemetatype.cpp.
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     QDeclarativeType *type = data->idToType.value(userType);
     if (type && type->typeId() == userType)
         return type;
     else
         return 0;
 }
qmlTypeNames()
QList< QByteArray > QDeclarativeMetaType::qmlTypeNames () static
Returns the list of registered QML type names.
Definition at line 1062 of file qdeclarativemetatype.cpp.
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     return data->nameToType.keys();
 }
qmlTypes()
QList< QDeclarativeType * > QDeclarativeMetaType::qmlTypes () static
Returns the list of registered QML types.
Definition at line 1073 of file qdeclarativemetatype.cpp.
Referenced by cacheForNamespace().
 {
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     return data->nameToType.values();
 }
registerCustomStringConverter()
void QDeclarativeMetaType::registerCustomStringConverter (int type, StringConverter converter) static
A custom string convertor allows you to specify a function pointer that returns a variant of type.
For example, if you have written your own icon class that you want to support as an object property assignable in QML:
int type = qRegisterMetaType<SuperIcon>("SuperIcon");
QML::addCustomStringConvertor(type, &SuperIcon::pixmapFromString);
The function pointer must be of the form:
QVariant (*StringConverter)(const QString &);
Definition at line 947 of file qdeclarativemetatype.cpp.
 {
     QWriteLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     if (data->stringConverters.contains(type))
         return;
     data->stringConverters.insert(type, converter);
 }
toQObject()
QObject * QDeclarativeMetaType::toQObject (const QVariant & v, bool * ok = 0) static
Definition at line 780 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeEnginePrivate::scriptValueFromVariant(), QDeclarativeListAccessor::setList(), QDeclarativeEnginePrivate::toQObject(), QDeclarativeEngineDebugService::valueContents(), and QDeclarativePropertyPrivate::write().
 {
     if (!isQObject(v.userType())) {
         if (ok) *ok = false;
         return 0;
     }
     if (ok) *ok = true;
     return *(QObject **)v.constData();
 }
typeCategory()
QDeclarativeMetaType::TypeCategory QDeclarativeMetaType::typeCategory (int userType) static
Definition at line 889 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativePropertyCache::Data::flagsForProperty(), and QDeclarativeEnginePrivate::typeCategory().
 {
     if (userType < 0)
         return Unknown;
     if (userType == QMetaType::QObjectStar)
         return Object;
     QReadLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     if (userType < data->objects.size() && data->objects.testBit(userType))
         return Object;
     else if (userType < data->lists.size() && data->lists.testBit(userType))
         return List;
     else
         return Unknown;
 }
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativemetatype_p.h
/src/declarative/qml/qdeclarativemetatype.cpp