Qt 4.8: ShaderEffectItem Class Reference
ShaderEffectItem Class Reference
The ShaderEffectItem object alters the output of given item with OpenGL shaders.
#include <shadereffectitem.h>
Classes
struct SourceData
Signals
void activeChanged ()
void blendingChanged ()
void fragmentShaderChanged ()
void meshResolutionChanged ()
void vertexShaderChanged ()
Signals inherited from QDeclarativeItem
void activeFocusChanged (bool)
void baselineOffsetChanged (qreal)
void childrenRectChanged (const QRectF &)
void clipChanged (bool)
void focusChanged (bool)
void implicitHeightChanged ()
void implicitWidthChanged ()
void parentChanged (QDeclarativeItem *)
void smoothChanged (bool)
void stateChanged (const QString &)
void transformOriginChanged (TransformOrigin)
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool blending () const
virtual void componentComplete ()
QString fragmentShader () const
QSize meshResolution () const
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
void preprocess ()
void setBlending (bool enable)
void setFragmentShader (const QString &code)
void setMeshResolution (const QSize &size)
void setVertexShader (const QString &code)
ShaderEffectItem (QDeclarativeItem *parent=0)
QString vertexShader () const
~ShaderEffectItem ()
Public Functions inherited from QDeclarativeItem
qreal baselineOffset () const
QRectF boundingRect () const
Q_INVOKABLE QDeclarativeItem * childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
QRectF childrenRect ()
bool clip () const
Q_INVOKABLE void forceActiveFocus ()
Forces active focus on the item.
bool hasActiveFocus () const
bool hasFocus () const
qreal height () const
qreal implicitHeight () const
qreal implicitWidth () const
bool keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
Q_INVOKABLE QScriptValue mapFromItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
Q_INVOKABLE QScriptValue mapToItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
QDeclarativeItem * parentItem () const
Returns the QDeclarativeItem parent of this item.
QDeclarativeItem (QDeclarativeItem *parent=0)
Constructs a QDeclarativeItem with the given parent.
void resetHeight ()
void resetWidth ()
void setBaselineOffset (qreal)
void setClip (bool)
void setFocus (bool)
void setHeight (qreal)
void setKeepMouseGrab (bool)
The flag indicating whether the mouse should remain with this item is set to keep.
void setParentItem (QDeclarativeItem *parent)
void setSize (const QSizeF &size)
void setSmooth (bool)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
void setTransformOrigin (TransformOrigin)
Set the transform origin.
void setWidth (qreal)
bool smooth () const
QDeclarativeListProperty< QGraphicsTransform > transform ()
TransformOrigin transformOrigin () const
qreal width () const
virtual ~QDeclarativeItem ()
Destroys the QDeclarativeItem.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
Protected Functions inherited from QDeclarativeItem
virtual void classBegin ()
virtual bool event (QEvent *)
bool heightValid () const
Returns whether the height property has been set explicitly.
virtual void inputMethodEvent (QInputMethodEvent *)
void inputMethodPreHandler (QInputMethodEvent *)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
bool isComponentComplete () const
Returns true if construction of the QML component is complete; otherwise returns false.
virtual QVariant itemChange (GraphicsItemChange, const QVariant &)
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
virtual void keyPressEvent (QKeyEvent *event)
void keyPressPreHandler (QKeyEvent *)
virtual void keyReleaseEvent (QKeyEvent *event)
void keyReleasePreHandler (QKeyEvent *)
QDeclarativeItem (QDeclarativeItemPrivate &dd, QDeclarativeItem *parent=0)
virtual bool sceneEvent (QEvent *)
void setImplicitHeight (qreal)
Sets the implied height of the item to h.
void setImplicitWidth (qreal)
Sets the implied width of the item to w.
bool widthValid () const
Returns whether the width property has been set explicitly.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
Filters events for the item watched.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
Private Slots
void changeSource (int index)
void handleVisibilityChange ()
void markDirty ()
Private Functions
bool active () const
void bindGeometry ()
void checkViewportUpdateMode ()
void connectPropertySignals ()
void disconnectPropertySignals ()
void lookThroughShaderCode (const QString &code)
void renderEffect (QPainter *painter, const QMatrix4x4 &matrix)
void reset ()
void setActive (bool enable)
void setSource (const QVariant &var, int index)
void updateEffectState (const QMatrix4x4 &matrix)
void updateGeometry ()
void updateProperties ()
void updateShaderProgram ()
Properties
bool blending
This property defines whether item is drawn using blending.
QString fragmentShader
This property holds the OpenGL fragment shader code.
bool m_active: 1
QVector< const char * > m_attributeNames
bool m_blending: 1
bool m_changed: 1
bool m_checkedOpenGL: 1
bool m_checkedShaderPrograms: 1
bool m_checkedViewportUpdateMode: 1
bool m_defaultVertexShader: 1
QString m_fragment_code
QSGGeometry m_geometry
bool m_hasShaderPrograms: 1
QSize m_meshResolution
bool m_mirrored: 1
QGLShaderProgram * m_program
bool m_program_dirty: 1
bool m_respectsMatrix: 1
bool m_respectsOpacity: 1
QVector< SourceData > m_sources
QSet< QByteArray > m_uniformNames
QString m_vertex_code
QSize meshResolution
This property defines to how many triangles the item is divided into before its vertices are passed to the vertex shader.
QString vertexShader
This property holds the OpenGL vertex shader code.
Additional Inherited Members
Public Types inherited from QDeclarativeItem
enum TransformOrigin {
TopLeft, Top, TopRight, Left,
Center, Right, BottomLeft, Bottom,
BottomRight
}
Controls the point about which simple transforms like scale apply.
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
The ShaderEffectItem object alters the output of given item with OpenGL shaders.
ShaderEffectItem is available in the Qt.labs.shaders 1.0 module. {Elements in the Qt.labs module are not guaranteed to remain compatible in future versions.}
This element provides preliminary support for embedding OpenGL shader code into QML, and may be heavily changed or removed in later versions.
Requirement for the use of shaders is that the application is either using Qt OpenGL graphicssystem or is using OpenGL by setting QGLWidget as the viewport to QDeclarativeView (depending on which one is the recommened way in the targeted platform).
ShaderEffectItem internal behaviour is such that during the paint event it first renders its ShaderEffectSource items into a OpenGL framebuffer object which can be used as a texture. If the ShaderEffectSource is defined to be an image, it is directly uploaded as a texture. The texture(s) containing the source pixelcontent are then bound to graphics pipeline texture units. Finally a textured mesh is passed to the vertex- and fragmentshaders which then produce the final output for the ShaderEffectItem. It is possible to alter the mesh structure by defining the amount vertices it contains, but currently it is not possible to import complex 3D-models to be used as the mesh.
It is possible to define one or more ShaderEffectItems to be a ShaderEffectSource for other ShaderEffectItems, but ShaderEffectItem should never be declared as a child element of its source item(s) because it would cause circular loop in the painting.
A standard set of vertex attributes are provided for the shaders:
qt_Vertex - The primary position of the vertex.
qt_MultiTexCoord0 - The texture co-ordinate at each vertex for texture unit 0.
Additionally following uniforms are available for shaders:
qt_Opacity - Effective opacity of the item.
qt_ModelViewProjectionMatrix - current 4x4 transformation matrix of the item.
Furthermore, it is possible to utilize automatic QML propertybinding into vertex- and fragment shader uniforms. Conversions are done according to the table below:
QML property GLSL uniform
property double foo: 1.0 uniform highp float foo
property real foo: 1.0 uniform highp float foo
property bool foo: true uniform bool foo
property int foo: 1 uniform int foo
property variant foo: Qt.point(1,1) uniform highp vec2 foo
property variant foo: Qt.size(1, 1) uniform highp vec2 foo
property variant foo: Qt.rect(1, 1, 2, 2) uniform highp vec4 foo
property color foo: "#00000000" uniform lowp vec4 foo
property variant foo: Qt.vector3d(1.0, 2.0, 0.0) uniform highp vec3 foo
property variant foo: ShaderEffectSource { SourceItem: bar } uniform lowp sampler2D foo
Note
The uniform precision definitions in the above table are not strict, it is possible to choose the uniform precision based on what is the most suitable for the shader code for that particular uniform.
The below example uses fragment shader to create simple wiggly effect to a text label.
Automatic property binding takes care of binding the properties to the uniforms if their
names are identical. ShaderEffectSource referring to textLabel is bound to sampler2D uniform inside the fragment
shader code.
import QtQuick 1.0
import Qt.labs.shaders 1.0
Rectangle {
    width: 300
    height: 300
    color: "black"
    Text {
        id: textLabel
        text: "Hello World"
        anchors.centerIn: parent
        font.pixelSize: 32
        color: "white"
    }
    ShaderEffectItem {
        property variant source: ShaderEffectSource { sourceItem: textLabel; hideSource: true }
        property real wiggleAmount: 0.005
        anchors.fill: textLabel
        fragmentShader: "
        varying highp vec2 qt_TexCoord0;
        uniform sampler2D source;
        uniform highp float wiggleAmount;
        void main(void)
        {
            highp vec2 wiggledTexCoord = qt_TexCoord0;
            wiggledTexCoord.s += sin(4.0 * 3.141592653589 * wiggledTexCoord.t) * wiggleAmount;
            gl_FragColor = texture2D(source, wiggledTexCoord.st);
        }
        "
    }
}
Definition at line 54 of file shadereffectitem.h.
Constructors and Destructors
ShaderEffectItem()
ShaderEffectItem::ShaderEffectItem (QDeclarativeItem * parent = 0)
Definition at line 205 of file shadereffectitem.cpp.
     : QDeclarativeItem(parent)
     , m_program(0)
     , m_meshResolution(1, 1)
     , m_geometry(QSGGeometry::defaultAttributes_TexturedPoint2D(), 4)
     , m_blending(true)
     , m_program_dirty(true)
     , m_active(true)
     , m_respectsMatrix(false)
     , m_respectsOpacity(false)
     , m_checkedViewportUpdateMode(false)
     , m_checkedOpenGL(false)
     , m_checkedShaderPrograms(false)
     , m_hasShaderPrograms(false)
     , m_mirrored(false)
     , m_defaultVertexShader(true)
 {
     setFlag(QGraphicsItem::ItemHasNoContents, false);
     connect(this, SIGNAL(visibleChanged()), this, SLOT(handleVisibilityChange()));
     m_active = isVisible();
 }
~ShaderEffectItem()
ShaderEffectItem::~ShaderEffectItem ()
Definition at line 227 of file shadereffectitem.cpp.
 {
     reset();
 }
Functions
active()
bool ShaderEffectItem::active () const inline private
Definition at line 112 of file shadereffectitem.h.
 { return m_active; }
activeChanged
void ShaderEffectItem::activeChanged () signal
Referenced by meshResolution(), and setActive().
bindGeometry()
void ShaderEffectItem::bindGeometry () private
Definition at line 568 of file shadereffectitem.cpp.
Referenced by meshResolution(), and renderEffect().
 {
     if (!m_program)
         return;
     char const *const *attrNames = m_attributeNames.constData();
     int offset = 0;
         for (int j = 0; j < m_attributeNames.size(); ++j) {
         if (!*attrNames[j])
             continue;
         Q_ASSERT_X(j < m_geometry.attributeCount(), "ShaderEffectItem::bindGeometry()", "Geometry lacks attribute required by material");
         const QSGGeometry::Attribute &a = m_geometry.attributes()[j];
         Q_ASSERT_X(j == a.position, "ShaderEffectItem::bindGeometry()", "Geometry does not have continuous attribute positions");
 #if defined(QT_OPENGL_ES_2)
         GLboolean normalize = a.type != GL_FLOAT;
 #else
         GLboolean normalize = a.type != GL_FLOAT && a.type != GL_DOUBLE;
 #endif
         if (normalize)
             qWarning() << "ShaderEffectItem::bindGeometry() - non supported attribute type!";
         m_program->setAttributeArray(a.position, (GLfloat*) (((char*) m_geometry.vertexData()) + offset), a.tupleSize, m_geometry.stride());
         //glVertexAttribPointer(a.position, a.tupleSize, a.type, normalize, m_geometry.stride(), (char *) m_geometry.vertexData() + offset);
         offset += a.tupleSize * size_of_type(a.type);
     }
 }
blending()
bool ShaderEffectItem::blending () const inline
Definition at line 76 of file shadereffectitem.h.
 { return m_blending; }
blendingChanged
void ShaderEffectItem::blendingChanged () signal
Referenced by meshResolution(), and setBlending().
changeSource
void ShaderEffectItem::changeSource (int index) private slot
Definition at line 698 of file shadereffectitem.cpp.
Referenced by connectPropertySignals(), and meshResolution().
 {
     Q_ASSERT(index >= 0 && index < m_sources.size());
     QVariant v = property(m_sources.at(index).name.constData());
     setSource(v, index);
 }
checkViewportUpdateMode()
void ShaderEffectItem::checkViewportUpdateMode () private
Definition at line 364 of file shadereffectitem.cpp.
Referenced by meshResolution(), and paint().
 {
     if (!m_checkedViewportUpdateMode) {
         QGraphicsScene *s = scene();
         if (s){
             QList<QGraphicsView*> views = s->views();
             for (int i = 0; i < views.count(); i++) {
                 if (views[i]->viewportUpdateMode() != QGraphicsView::FullViewportUpdate) {
                     qWarning() << "ShaderEffectItem::checkViewportUpdateMode - consider setting QGraphicsView::FullViewportUpdate mode with OpenGL!";
                 }
             }
         }
         m_checkedViewportUpdateMode = true;
     }
 }
componentComplete()
void ShaderEffectItem::componentComplete () virtual
Warning
This function is not part of the public interface.
componentComplete() is called when all items in the component have been constructed. It is often desirable to delay some processing until the component is complete an all bindings in the component have been resolved.
Reimplemented from QDeclarativeItem.
Definition at line 358 of file shadereffectitem.cpp.
 {
     updateProperties();
     QDeclarativeItem::componentComplete();
 }
connectPropertySignals()
void ShaderEffectItem::connectPropertySignals () private
Definition at line 761 of file shadereffectitem.cpp.
Referenced by meshResolution(), and updateProperties().
 {
     QSet<QByteArray>::const_iterator it;
     for (it = m_uniformNames.begin(); it != m_uniformNames.end(); ++it) {
         int pi = metaObject()->indexOfProperty(it->constData());
         if (pi >= 0) {
             QMetaProperty mp = metaObject()->property(pi);
             if (!mp.hasNotifySignal())
                 qWarning("ShaderEffectItem: property '%s' does not have notification method!", it->constData());
             QByteArray signalName("2");
             signalName.append(mp.notifySignal().signature());
             connect(this, signalName, this, SLOT(markDirty()));
         } else {
             qWarning("ShaderEffectItem: '%s' does not have a matching property!", it->constData());
         }
     }
     for (int i = 0; i < m_sources.size(); ++i) {
         SourceData &source = m_sources[i];
         int pi = metaObject()->indexOfProperty(source.name.constData());
         if (pi >= 0) {
             QMetaProperty mp = metaObject()->property(pi);
             QByteArray signalName("2");
             signalName.append(mp.notifySignal().signature());
             connect(this, signalName, source.mapper, SLOT(map()));
             source.mapper->setMapping(this, i);
             connect(source.mapper, SIGNAL(mapped(int)), this, SLOT(changeSource(int)));
         } else {
             qWarning("ShaderEffectItem: '%s' does not have a matching source!", source.name.constData());
         }
     }
 }
disconnectPropertySignals()
void ShaderEffectItem::disconnectPropertySignals () private
Definition at line 751 of file shadereffectitem.cpp.
Referenced by meshResolution(), and reset().
 {
     disconnect(this, 0, this, SLOT(markDirty()));
     for (int i = 0; i < m_sources.size(); ++i) {
         SourceData &source = m_sources[i];
         disconnect(this, 0, source.mapper, 0);
         disconnect(source.mapper, 0, this, 0);
     }
 }
fragmentShader()
QString ShaderEffectItem::fragmentShader () const inline
Definition at line 70 of file shadereffectitem.h.
 { return m_fragment_code; }
fragmentShaderChanged
void ShaderEffectItem::fragmentShaderChanged () signal
Referenced by meshResolution(), and setFragmentShader().
geometryChanged()
void ShaderEffectItem::geometryChanged (const QRectF & newGeometry, const QRectF & oldGeometry) protected virtual
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
If the two geometries are the same, it doesn't do anything.
Reimplemented from QDeclarativeItem.
Definition at line 691 of file shadereffectitem.cpp.
Referenced by meshResolution().
 {
     if (newGeometry.size() != oldGeometry.size())
         updateGeometry();
     QDeclarativeItem::geometryChanged(newGeometry, oldGeometry);
 }
handleVisibilityChange
void ShaderEffectItem::handleVisibilityChange () private slot
Definition at line 935 of file shadereffectitem.cpp.
Referenced by meshResolution(), and ShaderEffectItem().
 {
     setActive(isVisible());
 }
lookThroughShaderCode()
void ShaderEffectItem::lookThroughShaderCode (const QString & code) private
Definition at line 884 of file shadereffectitem.cpp.
Referenced by meshResolution(), and updateProperties().
 {
     // Regexp for matching attributes and uniforms.
     // In human readable form: attribute|uniform [lowp|mediump|highp] <type> <name>
     static QRegExp re(QLatin1String("\\b(attribute|uniform)\\b\\s*\\b(?:lowp|mediump|highp)?\\b\\s*\\b(\\w+)\\b\\s*\\b(\\w+)"));
     Q_ASSERT(re.isValid());
     int pos = -1;
     //QString wideCode = QString::fromLatin1(code.constData(), code.size());
     QString wideCode = code;
     while ((pos = re.indexIn(wideCode, pos + 1)) != -1) {
         QByteArray decl = re.cap(1).toLatin1(); // uniform or attribute
         QByteArray type = re.cap(2).toLatin1(); // type
         QByteArray name = re.cap(3).toLatin1(); // variable name
         if (decl == "attribute") {
             if (name == qt_postion_attribute_name) {
                 m_attributeNames.insert(0, qt_postion_attribute_name);
             } else if (name == "qt_MultiTexCoord0") {
                 if (m_attributeNames.at(0) == 0) {
                     m_attributeNames.insert(0, qt_emptyAttributeName);
                 }
                 m_attributeNames.insert(1, qt_texcoord_attribute_name);
             } else {
                 // TODO: Support user defined attributes.
                 qWarning("ShaderEffectItem: Attribute \'%s\' not recognized.", name.constData());
             }
         } else {
             Q_ASSERT(decl == "uniform");
             if (name == "qt_ModelViewProjectionMatrix") {
                 m_respectsMatrix = true;
             } else if (name == "qt_Opacity") {
                 m_respectsOpacity = true;
             } else {
                 m_uniformNames.insert(name);
                 if (type == "sampler2D") {
                     SourceData d;
                     d.mapper = new QSignalMapper;
                     d.source = 0;
                     d.name = name;
                     d.item = 0;
                     m_sources.append(d);
                 }
             }
         }
     }
 }
markDirty
void ShaderEffectItem::markDirty () private slot
Definition at line 705 of file shadereffectitem.cpp.
Referenced by connectPropertySignals(), disconnectPropertySignals(), meshResolution(), setActive(), and setSource().
{
     update();
 }
meshResolution()
QSize ShaderEffectItem::meshResolution () const inline
Definition at line 79 of file shadereffectitem.h.
 { return m_meshResolution; }
meshResolutionChanged
void ShaderEffectItem::meshResolutionChanged () signal
Referenced by meshResolution(), and setMeshResolution().
paint()
void ShaderEffectItem::paint (QPainter * , const QStyleOptionGraphicsItem * , QWidget * = 0) virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 380 of file shadereffectitem.cpp.
 {
     if (!m_active) return;
     const QGLContext *context = QGLContext::currentContext();
     if (context) {
         if (!m_checkedShaderPrograms) {
             m_hasShaderPrograms = QGLShaderProgram::hasOpenGLShaderPrograms(context);
             m_checkedShaderPrograms = true;
             if (!m_hasShaderPrograms)
                 qWarning() << "ShaderEffectItem::paint - Shader programs are not supported";
         }
         if ( !m_hasShaderPrograms )
             return;
         checkViewportUpdateMode();
         painter->save();
         painter->beginNativePainting();
         QMatrix4x4 combinedMatrix = QMatrix4x4(painter->transform());
         renderEffect(painter, combinedMatrix);
         painter->endNativePainting();
         painter->restore();
     } else {
         if (!m_checkedOpenGL) {
             qWarning() << "ShaderEffectItem::paint - OpenGL not available";
             m_checkedOpenGL = true;
         }
     }
 }
preprocess()
void ShaderEffectItem::preprocess ()
Definition at line 682 of file shadereffectitem.cpp.
Referenced by meshResolution().
 {
     for (int i = 0; i < m_sources.size(); ++i) {
         ShaderEffectSource *source = m_sources.at(i).source;
         if (source)
             source->updateBackbuffer();
     }
 }
renderEffect()
void ShaderEffectItem::renderEffect (QPainter * painter, const QMatrix4x4 & matrix) private
Definition at line 413 of file shadereffectitem.cpp.
Referenced by meshResolution(), and paint().
 {
     if (!painter || !painter->device())
         return;
     if (!m_program || !m_program->programId()) {
         // Deleted due to deactivation, to save GPU memory,
         // or invalidated due to GL context change.
         delete m_program;
         if (QGLContext::currentContext())
             m_program = new QGLShaderProgram(this);
         if (!m_program)
             qWarning() << "ShaderEffectItem::renderEffect - Creating QGLShaderProgram failed!";
     }
     if (!m_program)
         return;
     if (!m_program->isLinked() || m_program_dirty)
         updateShaderProgram();
     m_program->bind();
     QMatrix4x4 combinedMatrix;
     combinedMatrix.scale(2.0 / painter->device()->width(), -2.0 / painter->device()->height(), 1.0);
     combinedMatrix.translate(-painter->device()->width() / 2.0, -painter->device()->height() / 2.0 );
     combinedMatrix *= matrix;
     updateEffectState(combinedMatrix);
     for (int i = 0; i < m_attributeNames.size(); ++i) {
         m_program->enableAttributeArray(m_geometry.attributes()[i].position);
     }
     bindGeometry();
     // Optimization, disable depth test when we know we don't need it.
     if (m_defaultVertexShader) {
         glDepthMask(false);
         glDisable(GL_DEPTH_TEST);
     } else {
         glEnable(GL_DEPTH_TEST);
         glDepthFunc(GL_GREATER);
         glDepthMask(true);
 #if defined(QT_OPENGL_ES)
         glClearDepthf(0);
 #else
         glClearDepth(0);
 #endif
         glClearColor(0, 0, 0, 0);
         glClear(GL_DEPTH_BUFFER_BIT);
     }
     if (m_blending){
         glEnable(GL_BLEND);
         glBlendFunc (GL_ONE, GL_ONE_MINUS_SRC_ALPHA);
     } else {
         glDisable(GL_BLEND);
     }
     if (m_geometry.indexCount())
         glDrawElements(m_geometry.drawingMode(), m_geometry.indexCount(), m_geometry.indexType(), m_geometry.indexData());
     else
         glDrawArrays(m_geometry.drawingMode(), 0, m_geometry.vertexCount());
     glDepthMask(false);
     glDisable(GL_DEPTH_TEST);
    for (int i = 0; i < m_attributeNames.size(); ++i)
         m_program->disableAttributeArray(m_geometry.attributes()[i].position);
 }
reset()
void ShaderEffectItem::reset () private
Definition at line 793 of file shadereffectitem.cpp.
Referenced by meshResolution(), setFragmentShader(), setVertexShader(), and ~ShaderEffectItem().
 {
     disconnectPropertySignals();
     if (m_program)
         m_program->removeAllShaders();
     m_attributeNames.clear();
     m_uniformNames.clear();
     for (int i = 0; i < m_sources.size(); ++i) {
         const SourceData &source = m_sources.at(i);
         if (m_active && source.source)
             source.source->derefFromEffectItem();
         delete source.mapper;
     }
     m_sources.clear();
     m_program_dirty = true;
 }
setActive()
void ShaderEffectItem::setActive (bool enable) private
Definition at line 645 of file shadereffectitem.cpp.
Referenced by active(), and handleVisibilityChange().
 {
     if (m_active == enable)
         return;
     if (m_active) {
         for (int i = 0; i < m_sources.size(); ++i) {
             ShaderEffectSource *source = m_sources.at(i).source;
             if (!source)
                 continue;
             disconnect(source, SIGNAL(repaintRequired()), this, SLOT(markDirty()));
             source->derefFromEffectItem();
         }
     }
     m_active = enable;
     if (m_active) {
         for (int i = 0; i < m_sources.size(); ++i) {
             ShaderEffectSource *source = m_sources.at(i).source;
             if (!source)
                 continue;
             source->refFromEffectItem();
             connect(source, SIGNAL(repaintRequired()), this, SLOT(markDirty()));
         }
     }
     // QGLShaderProgram is deleted when not active (to minimize GPU memory usage).
     if (!m_active && m_program) {
         delete m_program;
         m_program = 0;
     }
     emit activeChanged();
     markDirty();
 }
setBlending()
void ShaderEffectItem::setBlending (bool enable)
Definition at line 323 of file shadereffectitem.cpp.
Referenced by blending().
 {
     if (m_blending == enable)
         return;
     m_blending = enable;
     m_changed = true;
     emit blendingChanged();
 }
setFragmentShader()
void ShaderEffectItem::setFragmentShader (const QString & code)
Definition at line 253 of file shadereffectitem.cpp.
Referenced by fragmentShader().
 {
     if (m_fragment_code.constData() == code.constData())
         return;
     m_fragment_code = code;
     if (isComponentComplete()) {
         reset();
         updateProperties();
     }
     emit fragmentShaderChanged();
 }
setMeshResolution()
void ShaderEffectItem::setMeshResolution (const QSize & size)
Definition at line 348 of file shadereffectitem.cpp.
Referenced by meshResolution().
 {
     if (size == m_meshResolution)
         return;
     m_meshResolution = size;
     emit meshResolutionChanged();
     updateGeometry();
 }
setSource()
void ShaderEffectItem::setSource (const QVariant & var, int index) private
Definition at line 709 of file shadereffectitem.cpp.
Referenced by changeSource(), meshResolution(), and updateProperties().
 {
     Q_ASSERT(index >= 0 && index < m_sources.size());
     SourceData &source = m_sources[index];
     source.source = 0;
     source.item = 0;
     if (var.isNull()) {
         return;
     } else if (!qVariantCanConvert<QObject *>(var)) {
         qWarning("Could not assign source of type '%s' to property '%s'.", var.typeName(), source.name.constData());
         return;
     }
     QObject *obj = qVariantValue<QObject *>(var);
     source.source = qobject_cast<ShaderEffectSource *>(obj);
     source.item = qobject_cast<QDeclarativeItem *>(obj);
     if (!source.item)
         qWarning("Could not assign property '%s', did not implement QDeclarativeItem.", source.name.constData());
     if (!source.source)
         qWarning("Could not assign property '%s', did not implement ShaderEffectSource.", source.name.constData());
     // TODO: Find better solution.
     // 'source.item' needs a canvas to get a scenegraph node.
     // The easiest way to make sure it gets a canvas is to
     // make it a part of the same item tree as 'this'.
     if (source.item && source.item->parentItem() == 0) {
         source.item->setParentItem(this);
         // Unlike in scenegraph, we cannot set item invisible here because qgraphicsview would optimize it away.
     }
     // Unlike in scenegraph, ref counting is used to optimize memory consumption. Sources themself may free fbos when not referenced.
     if (m_active && source.source) {
         source.source->refFromEffectItem();
         connect(source.source, SIGNAL(repaintRequired()), this, SLOT(markDirty()));
      }
 }
setVertexShader()
void ShaderEffectItem::setVertexShader (const QString & code)
Definition at line 286 of file shadereffectitem.cpp.
Referenced by vertexShader().
 {
     if (m_vertex_code.constData() == code.constData())
         return;
     m_vertex_code = code;
     m_defaultVertexShader = false;
     if (isComponentComplete()) {
         reset();
         updateProperties();
     }
     emit vertexShaderChanged();
 }
updateEffectState()
void ShaderEffectItem::updateEffectState (const QMatrix4x4 & matrix) private
Definition at line 484 of file shadereffectitem.cpp.
Referenced by meshResolution(), and renderEffect().
 {
     if (!m_program)
         return;
     for (int i = m_sources.size() - 1; i >= 0; --i) {
         const ShaderEffectItem::SourceData &source = m_sources.at(i);
         if (!source.source)
             continue;
         glActiveTexture(GL_TEXTURE0 + i);
         source.source->bind();
     }
     if (m_respectsOpacity)
         m_program->setUniformValue("qt_Opacity", static_cast<float> (effectiveOpacity()));
     if (m_respectsMatrix){
         m_program->setUniformValue("qt_ModelViewProjectionMatrix", matrix);
     }
     QSet<QByteArray>::const_iterator it;
     for (it = m_uniformNames.begin(); it != m_uniformNames.end(); ++it) {
         const QByteArray &name = *it;
         QVariant v = property(name.constData());
         switch (v.type()) {
         case QVariant::Color:
             m_program->setUniformValue(name.constData(), qvariant_cast<QColor>(v));
             break;
         case QVariant::Double:
             m_program->setUniformValue(name.constData(), (float) qvariant_cast<double>(v));
             break;
         case QVariant::Transform:
             m_program->setUniformValue(name.constData(), qvariant_cast<QTransform>(v));
             break;
         case QVariant::Int:
             m_program->setUniformValue(name.constData(), GLint(v.toInt()));
             break;
         case QVariant::Bool:
             m_program->setUniformValue(name.constData(), GLint(v.toBool()));
             break;
         case QVariant::Size:
         case QVariant::SizeF:
             m_program->setUniformValue(name.constData(), v.toSizeF());
             break;
         case QVariant::Point:
         case QVariant::PointF:
             m_program->setUniformValue(name.constData(), v.toPointF());
             break;
         case QVariant::Rect:
         case QVariant::RectF:
         {
             QRectF r = v.toRectF();
             m_program->setUniformValue(name.constData(), r.x(), r.y(), r.width(), r.height());
         }
             break;
         case QVariant::Vector3D:
             m_program->setUniformValue(name.constData(), qvariant_cast<QVector3D>(v));
             break;
         default:
             break;
         }
     }
 }
updateGeometry()
void ShaderEffectItem::updateGeometry () private
Definition at line 595 of file shadereffectitem.cpp.
Referenced by geometryChanged(), meshResolution(), and setMeshResolution().
 {
     QRectF srcRect(0, 1, 1, -1);
     if (m_mirrored)
         srcRect = QRectF(0, 0, 1, 1);
     QRectF dstRect = QRectF(0,0, width(), height());
     int vmesh = m_meshResolution.height();
     int hmesh = m_meshResolution.width();
     QSGGeometry *g = &m_geometry;
     if (vmesh == 1 && hmesh == 1) {
         if (g->vertexCount() != 4)
             g->allocate(4);
         QSGGeometry::updateTexturedRectGeometry(g, dstRect, srcRect);
         return;
     }
     g->allocate((vmesh + 1) * (hmesh + 1), vmesh * 2 * (hmesh + 2));
     QSGGeometry::TexturedPoint2D *vdata = g->vertexDataAsTexturedPoint2D();
     for (int iy = 0; iy <= vmesh; ++iy) {
         float fy = iy / float(vmesh);
         float y = float(dstRect.top()) + fy * float(dstRect.height());
         float ty = float(srcRect.top()) + fy * float(srcRect.height());
         for (int ix = 0; ix <= hmesh; ++ix) {
             float fx = ix / float(hmesh);
             vdata->x = float(dstRect.left()) + fx * float(dstRect.width());
             vdata->y = y;
             vdata->tx = float(srcRect.left()) + fx * float(srcRect.width());
             vdata->ty = ty;
             ++vdata;
         }
     }
     quint16 *indices = (quint16 *)g->indexDataAsUShort();
     int i = 0;
     for (int iy = 0; iy < vmesh; ++iy) {
         *(indices++) = i + hmesh + 1;
         for (int ix = 0; ix <= hmesh; ++ix, ++i) {
             *(indices++) = i + hmesh + 1;
             *(indices++) = i;
         }
         *(indices++) = i - 1;
     }
 }
updateProperties()
void ShaderEffectItem::updateProperties () private
Definition at line 813 of file shadereffectitem.cpp.
Referenced by componentComplete(), meshResolution(), setFragmentShader(), and setVertexShader().
 {
     QString vertexCode = m_vertex_code;
     QString fragmentCode = m_fragment_code;
     if (vertexCode.isEmpty())
         vertexCode = qt_default_vertex_code;
     if (fragmentCode.isEmpty())
         fragmentCode = qt_default_fragment_code;
     lookThroughShaderCode(vertexCode);
     lookThroughShaderCode(fragmentCode);
     if (!m_attributeNames.contains(qt_postion_attribute_name))
         qWarning("ShaderEffectItem: Missing reference to \'%s\'.", qt_postion_attribute_name);
     if (!m_attributeNames.contains(qt_texcoord_attribute_name))
         qWarning("ShaderEffectItem: Missing reference to \'%s\'.", qt_texcoord_attribute_name);
     if (!m_respectsMatrix)
         qWarning("ShaderEffectItem: Missing reference to \'qt_ModelViewProjectionMatrix\'.");
     for (int i = 0; i < m_sources.size(); ++i) {
         QVariant v = property(m_sources.at(i).name);
         setSource(v, i); // Property exists.
     }
     connectPropertySignals();
 }
updateShaderProgram()
void ShaderEffectItem::updateShaderProgram () private
Definition at line 842 of file shadereffectitem.cpp.
Referenced by meshResolution(), and renderEffect().
 {
     if (!m_program)
         return;
     QString vertexCode = m_vertex_code;
     QString fragmentCode = m_fragment_code;
     if (vertexCode.isEmpty())
         vertexCode = QString::fromLatin1(qt_default_vertex_code);
     if (fragmentCode.isEmpty())
         fragmentCode = QString::fromLatin1(qt_default_fragment_code);
     m_program->addShaderFromSourceCode(QGLShader::Vertex, vertexCode);
     m_program->addShaderFromSourceCode(QGLShader::Fragment, fragmentCode);
     for (int i = 0; i < m_attributeNames.size(); ++i) {
         m_program->bindAttributeLocation(m_attributeNames.at(i), m_geometry.attributes()[i].position);
     }
     if (!m_program->link()) {
         qWarning("ShaderEffectItem: Shader compilation failed:");
         qWarning() << m_program->log();
     }
     if (!m_attributeNames.contains(qt_postion_attribute_name))
         qWarning("ShaderEffectItem: Missing reference to \'qt_Vertex\'.");
     if (!m_attributeNames.contains(qt_texcoord_attribute_name))
         qWarning("ShaderEffectItem: Missing reference to \'qt_MultiTexCoord0\'.");
     if (!m_respectsMatrix)
         qWarning("ShaderEffectItem: Missing reference to \'qt_ModelViewProjectionMatrix\'.");
     if (m_program->isLinked()) {
         m_program->bind();
         for (int i = 0; i < m_sources.size(); ++i)
             m_program->setUniformValue(m_sources.at(i).name.constData(), (GLint) i);
     }
     m_program_dirty = false;
 }
vertexShader()
QString ShaderEffectItem::vertexShader () const inline
Definition at line 73 of file shadereffectitem.h.
 { return m_vertex_code; }
vertexShaderChanged
void ShaderEffectItem::vertexShaderChanged () signal
Referenced by meshResolution(), and setVertexShader().
Properties
blending
bool ShaderEffectItem::blending private
This property defines whether item is drawn using blending.
If true, the RGBA pixel output from the fragment shader is blended with the pixel RGBA-values already in the framebuffer.
If false, fragment shader output is written to framebuffer as such.
Usually drawing without blending is slightly faster, thus disabling blending might be a good choice when item is used as a background element.
Note
By default the pixel data in textures is stored in 32-bit premultiplied alpha format. This should be taken into account when blending or reading the pixel values in the fragment shader code.
The default value is true.
Definition at line 60 of file shadereffectitem.h.
fragmentShader
string ShaderEffectItem::fragmentShader private
This property holds the OpenGL fragment shader code.
The default fragment shader is following:
varying highp vec2 qt_TexCoord0;
uniform sampler2D source;
void main(void)
{
    gl_FragColor = texture2D(source, qt_TexCoord0.st);
}
Definition at line 58 of file shadereffectitem.h.
m_active
bool ShaderEffectItem::m_active private
Definition at line 137 of file shadereffectitem.h.
Referenced by active(), paint(), reset(), setActive(), setSource(), and ShaderEffectItem().
m_attributeNames
QVector<const char *> ShaderEffectItem::m_attributeNames private
Definition at line 119 of file shadereffectitem.h.
Referenced by bindGeometry(), lookThroughShaderCode(), renderEffect(), reset(), updateProperties(), and updateShaderProgram().
m_blending
bool ShaderEffectItem::m_blending private
Definition at line 135 of file shadereffectitem.h.
Referenced by blending(), renderEffect(), and setBlending().
m_changed
bool ShaderEffectItem::m_changed private
Definition at line 134 of file shadereffectitem.h.
Referenced by setBlending().
m_checkedOpenGL
bool ShaderEffectItem::m_checkedOpenGL private
Definition at line 141 of file shadereffectitem.h.
Referenced by paint().
m_checkedShaderPrograms
bool ShaderEffectItem::m_checkedShaderPrograms private
Definition at line 142 of file shadereffectitem.h.
Referenced by paint().
m_checkedViewportUpdateMode
bool ShaderEffectItem::m_checkedViewportUpdateMode private
Definition at line 140 of file shadereffectitem.h.
Referenced by checkViewportUpdateMode().
m_defaultVertexShader
bool ShaderEffectItem::m_defaultVertexShader private
Definition at line 145 of file shadereffectitem.h.
Referenced by renderEffect(), and setVertexShader().
m_fragment_code
QString ShaderEffectItem::m_fragment_code private
Definition at line 116 of file shadereffectitem.h.
Referenced by fragmentShader(), setFragmentShader(), updateProperties(), and updateShaderProgram().
m_geometry
QSGGeometry ShaderEffectItem::m_geometry private
Definition at line 122 of file shadereffectitem.h.
Referenced by bindGeometry(), renderEffect(), updateGeometry(), and updateShaderProgram().
m_hasShaderPrograms
bool ShaderEffectItem::m_hasShaderPrograms private
Definition at line 143 of file shadereffectitem.h.
Referenced by paint().
m_meshResolution
QSize ShaderEffectItem::m_meshResolution private
Definition at line 121 of file shadereffectitem.h.
Referenced by meshResolution(), setMeshResolution(), and updateGeometry().
m_mirrored
bool ShaderEffectItem::m_mirrored private
Definition at line 144 of file shadereffectitem.h.
Referenced by updateGeometry().
m_program
QGLShaderProgram* ShaderEffectItem::m_program private
Definition at line 118 of file shadereffectitem.h.
Referenced by bindGeometry(), renderEffect(), reset(), setActive(), updateEffectState(), and updateShaderProgram().
m_program_dirty
bool ShaderEffectItem::m_program_dirty private
Definition at line 136 of file shadereffectitem.h.
Referenced by renderEffect(), reset(), and updateShaderProgram().
m_respectsMatrix
bool ShaderEffectItem::m_respectsMatrix private
Definition at line 138 of file shadereffectitem.h.
Referenced by lookThroughShaderCode(), updateEffectState(), updateProperties(), and updateShaderProgram().
m_respectsOpacity
bool ShaderEffectItem::m_respectsOpacity private
Definition at line 139 of file shadereffectitem.h.
Referenced by lookThroughShaderCode(), and updateEffectState().
m_sources
QVector<SourceData> ShaderEffectItem::m_sources private
Definition at line 132 of file shadereffectitem.h.
Referenced by changeSource(), connectPropertySignals(), disconnectPropertySignals(), lookThroughShaderCode(), preprocess(), reset(), setActive(), setSource(), updateEffectState(), updateProperties(), and updateShaderProgram().
m_uniformNames
QSet<QByteArray> ShaderEffectItem::m_uniformNames private
Definition at line 120 of file shadereffectitem.h.
Referenced by connectPropertySignals(), lookThroughShaderCode(), reset(), and updateEffectState().
m_vertex_code
QString ShaderEffectItem::m_vertex_code private
Definition at line 117 of file shadereffectitem.h.
Referenced by setVertexShader(), updateProperties(), updateShaderProgram(), and vertexShader().
meshResolution
QSize ShaderEffectItem::meshResolution private
This property defines to how many triangles the item is divided into before its vertices are passed to the vertex shader.
Triangles are defined as triangle strips and the amount of triangles can be controlled separately for x and y-axis.
The default value is QSize(1,1).
Definition at line 61 of file shadereffectitem.h.
vertexShader
string ShaderEffectItem::vertexShader private
This property holds the OpenGL vertex shader code.
The default vertex shader is following:
uniform highp mat4 qt_ModelViewProjectionMatrix;
attribute highp vec4 qt_Vertex;
attribute highp vec2 qt_MultiTexCoord0;
varying highp vec2 qt_TexCoord0;
void main(void)
{
    qt_TexCoord0 = qt_MultiTexCoord0;
    gl_Position = qt_ModelViewProjectionMatrix * qt_Vertex;
}
Definition at line 59 of file shadereffectitem.h.
The documentation for this class was generated from the following files:
/src/imports/shaders/shadereffectitem.h
/src/imports/shaders/shadereffectitem.cpp