Qt 4.8: QGLShaderProgram Class Reference
QGLShaderProgram Class Reference
The QGLShaderProgram class allows OpenGL shader programs to be linked and used.
#include <qglshaderprogram.h>
Public Functions
bool addShader (QGLShader *shader)
Adds a compiled shader to this shader program.
bool addShaderFromSourceCode (QGLShader::ShaderType type, const char *source)
Compiles source as a shader of the specified type and adds it to this shader program.
bool addShaderFromSourceCode (QGLShader::ShaderType type, const QByteArray &source)
Compiles source as a shader of the specified type and adds it to this shader program.
bool addShaderFromSourceCode (QGLShader::ShaderType type, const QString &source)
Compiles source as a shader of the specified type and adds it to this shader program.
bool addShaderFromSourceFile (QGLShader::ShaderType type, const QString &fileName)
Compiles the contents of fileName as a shader of the specified type and adds it to this shader program.
int attributeLocation (const char *name) const
Returns the location of the attribute name within this shader program's parameter list.
int attributeLocation (const QByteArray &name) const
Returns the location of the attribute name within this shader program's parameter list.
int attributeLocation (const QString &name) const
Returns the location of the attribute name within this shader program's parameter list.
bool bind ()
Binds this shader program to the active QGLContext and makes it the current shader program.
void bindAttributeLocation (const char *name, int location)
Binds the attribute name to the specified location.
void bindAttributeLocation (const QByteArray &name, int location)
Binds the attribute name to the specified location.
void bindAttributeLocation (const QString &name, int location)
Binds the attribute name to the specified location.
void disableAttributeArray (int location)
Disables the vertex array at location in this shader program that was enabled by a previous call to enableAttributeArray().
void disableAttributeArray (const char *name)
Disables the vertex array called name in this shader program that was enabled by a previous call to enableAttributeArray().
void enableAttributeArray (int location)
Enables the vertex array at location in this shader program so that the value set by setAttributeArray() on location will be used by the shader program.
void enableAttributeArray (const char *name)
Enables the vertex array called name in this shader program so that the value set by setAttributeArray() on name will be used by the shader program.
GLenum geometryInputType () const
Returns the geometry shader input type, if active.
GLenum geometryOutputType () const
Returns the geometry shader output type, if active.
int geometryOutputVertexCount () const
Returns the maximum number of vertices the current geometry shader program will produce, if active.
bool isLinked () const
Returns true if this shader program has been linked; false otherwise.
virtual bool link ()
Links together the shaders that were added to this program with addShader().
QString log () const
Returns the errors and warnings that occurred during the last link() or addShader() with explicitly specified source code.
int maxGeometryOutputVertices () const
Returns the hardware limit for how many vertices a geometry shader can output.
GLuint programId () const
Returns the OpenGL identifier associated with this shader program.
QGLShaderProgram (QObject *parent=0)
Constructs a new shader program and attaches it to parent.
QGLShaderProgram (const QGLContext *context, QObject *parent=0)
Constructs a new shader program and attaches it to parent.
void release ()
Releases the active shader program from the current QGLContext.
void removeAllShaders ()
Removes all of the shaders that were added to this program previously.
void removeShader (QGLShader *shader)
Removes shader from this shader program.
void setAttributeArray (int location, const GLfloat *values, int tupleSize, int stride=0)
Sets an array of vertex values on the attribute at location in this shader program.
void setAttributeArray (int location, const QVector2D *values, int stride=0)
Sets an array of 2D vertex values on the attribute at location in this shader program.
void setAttributeArray (int location, const QVector3D *values, int stride=0)
Sets an array of 3D vertex values on the attribute at location in this shader program.
void setAttributeArray (int location, const QVector4D *values, int stride=0)
Sets an array of 4D vertex values on the attribute at location in this shader program.
void setAttributeArray (int location, GLenum type, const void *values, int tupleSize, int stride=0)
Sets an array of vertex values on the attribute at location in this shader program.
void setAttributeArray (const char *name, const GLfloat *values, int tupleSize, int stride=0)
Sets an array of vertex values on the attribute called name in this shader program.
void setAttributeArray (const char *name, const QVector2D *values, int stride=0)
Sets an array of 2D vertex values on the attribute called name in this shader program.
void setAttributeArray (const char *name, const QVector3D *values, int stride=0)
Sets an array of 3D vertex values on the attribute called name in this shader program.
void setAttributeArray (const char *name, const QVector4D *values, int stride=0)
Sets an array of 4D vertex values on the attribute called name in this shader program.
void setAttributeArray (const char *name, GLenum type, const void *values, int tupleSize, int stride=0)
Sets an array of vertex values on the attribute called name in this shader program.
void setAttributeBuffer (int location, GLenum type, int offset, int tupleSize, int stride=0)
Sets an array of vertex values on the attribute at location in this shader program, starting at a specific offset in the currently bound vertex buffer.
void setAttributeBuffer (const char *name, GLenum type, int offset, int tupleSize, int stride=0)
Sets an array of vertex values on the attribute called name in this shader program, starting at a specific offset in the currently bound vertex buffer.
void setAttributeValue (int location, GLfloat value)
Sets the attribute at location in the current context to value.
void setAttributeValue (int location, GLfloat x, GLfloat y)
Sets the attribute at location in the current context to the 2D vector (x, y).
void setAttributeValue (int location, GLfloat x, GLfloat y, GLfloat z)
Sets the attribute at location in the current context to the 3D vector (x, y, z).
void setAttributeValue (int location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Sets the attribute at location in the current context to the 4D vector (x, y, z, w).
void setAttributeValue (int location, const QVector2D &value)
Sets the attribute at location in the current context to value.
void setAttributeValue (int location, const QVector3D &value)
Sets the attribute at location in the current context to value.
void setAttributeValue (int location, const QVector4D &value)
Sets the attribute at location in the current context to value.
void setAttributeValue (int location, const QColor &value)
Sets the attribute at location in the current context to value.
void setAttributeValue (int location, const GLfloat *values, int columns, int rows)
Sets the attribute at location in the current context to the contents of values, which contains columns elements, each consisting of rows elements.
void setAttributeValue (const char *name, GLfloat value)
Sets the attribute called name in the current context to value.
void setAttributeValue (const char *name, GLfloat x, GLfloat y)
Sets the attribute called name in the current context to the 2D vector (x, y).
void setAttributeValue (const char *name, GLfloat x, GLfloat y, GLfloat z)
Sets the attribute called name in the current context to the 3D vector (x, y, z).
void setAttributeValue (const char *name, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Sets the attribute called name in the current context to the 4D vector (x, y, z, w).
void setAttributeValue (const char *name, const QVector2D &value)
Sets the attribute called name in the current context to value.
void setAttributeValue (const char *name, const QVector3D &value)
Sets the attribute called name in the current context to value.
void setAttributeValue (const char *name, const QVector4D &value)
Sets the attribute called name in the current context to value.
void setAttributeValue (const char *name, const QColor &value)
Sets the attribute called name in the current context to value.
void setAttributeValue (const char *name, const GLfloat *values, int columns, int rows)
Sets the attribute called name in the current context to the contents of values, which contains columns elements, each consisting of rows elements.
void setGeometryInputType (GLenum inputType)
Sets the input type from inputType.
void setGeometryOutputType (GLenum outputType)
Sets the output type from the geometry shader, if active, to outputType.
void setGeometryOutputVertexCount (int count)
Sets the maximum number of vertices the current geometry shader program will produce, if active, to count.
void setUniformValue (int location, GLfloat value)
Sets the uniform variable at location in the current context to value.
void setUniformValue (int location, GLint value)
Sets the uniform variable at location in the current context to value.
void setUniformValue (int location, GLuint value)
Sets the uniform variable at location in the current context to value.
void setUniformValue (int location, GLfloat x, GLfloat y)
Sets the uniform variable at location in the current context to the 2D vector (x, y).
void setUniformValue (int location, GLfloat x, GLfloat y, GLfloat z)
Sets the uniform variable at location in the current context to the 3D vector (x, y, z).
void setUniformValue (int location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Sets the uniform variable at location in the current context to the 4D vector (x, y, z, w).
void setUniformValue (int location, const QVector2D &value)
Sets the uniform variable at location in the current context to value.
void setUniformValue (int location, const QVector3D &value)
Sets the uniform variable at location in the current context to value.
void setUniformValue (int location, const QVector4D &value)
Sets the uniform variable at location in the current context to value.
void setUniformValue (int location, const QColor &color)
Sets the uniform variable at location in the current context to the red, green, blue, and alpha components of color.
void setUniformValue (int location, const QPoint &point)
Sets the uniform variable at location in the current context to the x and y coordinates of point.
void setUniformValue (int location, const QPointF &point)
Sets the uniform variable at location in the current context to the x and y coordinates of point.
void setUniformValue (int location, const QSize &size)
Sets the uniform variable at location in the current context to the width and height of the given size.
void setUniformValue (int location, const QSizeF &size)
Sets the uniform variable at location in the current context to the width and height of the given size.
void setUniformValue (int location, const QMatrix2x2 &value)
Sets the uniform variable at location in the current context to a 2x2 matrix value.
void setUniformValue (int location, const QMatrix2x3 &value)
Sets the uniform variable at location in the current context to a 2x3 matrix value.
void setUniformValue (int location, const QMatrix2x4 &value)
Sets the uniform variable at location in the current context to a 2x4 matrix value.
void setUniformValue (int location, const QMatrix3x2 &value)
Sets the uniform variable at location in the current context to a 3x2 matrix value.
void setUniformValue (int location, const QMatrix3x3 &value)
Sets the uniform variable at location in the current context to a 3x3 matrix value.
void setUniformValue (int location, const QMatrix3x4 &value)
Sets the uniform variable at location in the current context to a 3x4 matrix value.
void setUniformValue (int location, const QMatrix4x2 &value)
Sets the uniform variable at location in the current context to a 4x2 matrix value.
void setUniformValue (int location, const QMatrix4x3 &value)
Sets the uniform variable at location in the current context to a 4x3 matrix value.
void setUniformValue (int location, const QMatrix4x4 &value)
Sets the uniform variable at location in the current context to a 4x4 matrix value.
void setUniformValue (int location, const GLfloat value[2][2])
Sets the uniform variable at location in the current context to a 2x2 matrix value.
void setUniformValue (int location, const GLfloat value[3][3])
Sets the uniform variable at location in the current context to a 3x3 matrix value.
void setUniformValue (int location, const GLfloat value[4][4])
Sets the uniform variable at location in the current context to a 4x4 matrix value.
void setUniformValue (int location, const QTransform &value)
Sets the uniform variable at location in the current context to a 3x3 transformation matrix value that is specified as a QTransform value.
void setUniformValue (const char *name, GLfloat value)
Sets the uniform variable called name in the current context to value.
void setUniformValue (const char *name, GLint value)
Sets the uniform variable called name in the current context to value.
void setUniformValue (const char *name, GLuint value)
Sets the uniform variable called name in the current context to value.
void setUniformValue (const char *name, GLfloat x, GLfloat y)
Sets the uniform variable called name in the current context to the 2D vector (x, y).
void setUniformValue (const char *name, GLfloat x, GLfloat y, GLfloat z)
Sets the uniform variable called name in the current context to the 3D vector (x, y, z).
void setUniformValue (const char *name, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Sets the uniform variable called name in the current context to the 4D vector (x, y, z, w).
void setUniformValue (const char *name, const QVector2D &value)
Sets the uniform variable called name in the current context to value.
void setUniformValue (const char *name, const QVector3D &value)
Sets the uniform variable called name in the current context to value.
void setUniformValue (const char *name, const QVector4D &value)
Sets the uniform variable called name in the current context to value.
void setUniformValue (const char *name, const QColor &color)
Sets the uniform variable called name in the current context to the red, green, blue, and alpha components of color.
void setUniformValue (const char *name, const QPoint &point)
Sets the uniform variable associated with name in the current context to the x and y coordinates of point.
void setUniformValue (const char *name, const QPointF &point)
Sets the uniform variable associated with name in the current context to the x and y coordinates of point.
void setUniformValue (const char *name, const QSize &size)
Sets the uniform variable associated with name in the current context to the width and height of the given size.
void setUniformValue (const char *name, const QSizeF &size)
Sets the uniform variable associated with name in the current context to the width and height of the given size.
void setUniformValue (const char *name, const QMatrix2x2 &value)
Sets the uniform variable called name in the current context to a 2x2 matrix value.
void setUniformValue (const char *name, const QMatrix2x3 &value)
Sets the uniform variable called name in the current context to a 2x3 matrix value.
void setUniformValue (const char *name, const QMatrix2x4 &value)
Sets the uniform variable called name in the current context to a 2x4 matrix value.
void setUniformValue (const char *name, const QMatrix3x2 &value)
Sets the uniform variable called name in the current context to a 3x2 matrix value.
void setUniformValue (const char *name, const QMatrix3x3 &value)
Sets the uniform variable called name in the current context to a 3x3 matrix value.
void setUniformValue (const char *name, const QMatrix3x4 &value)
Sets the uniform variable called name in the current context to a 3x4 matrix value.
void setUniformValue (const char *name, const QMatrix4x2 &value)
Sets the uniform variable called name in the current context to a 4x2 matrix value.
void setUniformValue (const char *name, const QMatrix4x3 &value)
Sets the uniform variable called name in the current context to a 4x3 matrix value.
void setUniformValue (const char *name, const QMatrix4x4 &value)
Sets the uniform variable called name in the current context to a 4x4 matrix value.
void setUniformValue (const char *name, const GLfloat value[2][2])
Sets the uniform variable called name in the current context to a 2x2 matrix value.
void setUniformValue (const char *name, const GLfloat value[3][3])
Sets the uniform variable called name in the current context to a 3x3 matrix value.
void setUniformValue (const char *name, const GLfloat value[4][4])
Sets the uniform variable called name in the current context to a 4x4 matrix value.
void setUniformValue (const char *name, const QTransform &value)
Sets the uniform variable called name in the current context to a 3x3 transformation matrix value that is specified as a QTransform value.
void setUniformValueArray (int location, const GLfloat *values, int count, int tupleSize)
Sets the uniform variable array at location in the current context to the count elements of values.
void setUniformValueArray (int location, const GLint *values, int count)
Sets the uniform variable array at location in the current context to the count elements of values.
void setUniformValueArray (int location, const GLuint *values, int count)
Sets the uniform variable array at location in the current context to the count elements of values.
void setUniformValueArray (int location, const QVector2D *values, int count)
Sets the uniform variable array at location in the current context to the count 2D vector elements of values.
void setUniformValueArray (int location, const QVector3D *values, int count)
Sets the uniform variable array at location in the current context to the count 3D vector elements of values.
void setUniformValueArray (int location, const QVector4D *values, int count)
Sets the uniform variable array at location in the current context to the count 4D vector elements of values.
void setUniformValueArray (int location, const QMatrix2x2 *values, int count)
Sets the uniform variable array at location in the current context to the count 2x2 matrix elements of values.
void setUniformValueArray (int location, const QMatrix2x3 *values, int count)
Sets the uniform variable array at location in the current context to the count 2x3 matrix elements of values.
void setUniformValueArray (int location, const QMatrix2x4 *values, int count)
Sets the uniform variable array at location in the current context to the count 2x4 matrix elements of values.
void setUniformValueArray (int location, const QMatrix3x2 *values, int count)
Sets the uniform variable array at location in the current context to the count 3x2 matrix elements of values.
void setUniformValueArray (int location, const QMatrix3x3 *values, int count)
Sets the uniform variable array at location in the current context to the count 3x3 matrix elements of values.
void setUniformValueArray (int location, const QMatrix3x4 *values, int count)
Sets the uniform variable array at location in the current context to the count 3x4 matrix elements of values.
void setUniformValueArray (int location, const QMatrix4x2 *values, int count)
Sets the uniform variable array at location in the current context to the count 4x2 matrix elements of values.
void setUniformValueArray (int location, const QMatrix4x3 *values, int count)
Sets the uniform variable array at location in the current context to the count 4x3 matrix elements of values.
void setUniformValueArray (int location, const QMatrix4x4 *values, int count)
Sets the uniform variable array at location in the current context to the count 4x4 matrix elements of values.
void setUniformValueArray (const char *name, const GLfloat *values, int count, int tupleSize)
Sets the uniform variable array called name in the current context to the count elements of values.
void setUniformValueArray (const char *name, const GLint *values, int count)
Sets the uniform variable array called name in the current context to the count elements of values.
void setUniformValueArray (const char *name, const GLuint *values, int count)
Sets the uniform variable array called name in the current context to the count elements of values.
void setUniformValueArray (const char *name, const QVector2D *values, int count)
Sets the uniform variable array called name in the current context to the count 2D vector elements of values.
void setUniformValueArray (const char *name, const QVector3D *values, int count)
Sets the uniform variable array called name in the current context to the count 3D vector elements of values.
void setUniformValueArray (const char *name, const QVector4D *values, int count)
Sets the uniform variable array called name in the current context to the count 4D vector elements of values.
void setUniformValueArray (const char *name, const QMatrix2x2 *values, int count)
Sets the uniform variable array called name in the current context to the count 2x2 matrix elements of values.
void setUniformValueArray (const char *name, const QMatrix2x3 *values, int count)
Sets the uniform variable array called name in the current context to the count 2x3 matrix elements of values.
void setUniformValueArray (const char *name, const QMatrix2x4 *values, int count)
Sets the uniform variable array called name in the current context to the count 2x4 matrix elements of values.
void setUniformValueArray (const char *name, const QMatrix3x2 *values, int count)
Sets the uniform variable array called name in the current context to the count 3x2 matrix elements of values.
void setUniformValueArray (const char *name, const QMatrix3x3 *values, int count)
Sets the uniform variable array called name in the current context to the count 3x3 matrix elements of values.
void setUniformValueArray (const char *name, const QMatrix3x4 *values, int count)
Sets the uniform variable array called name in the current context to the count 3x4 matrix elements of values.
void setUniformValueArray (const char *name, const QMatrix4x2 *values, int count)
Sets the uniform variable array called name in the current context to the count 4x2 matrix elements of values.
void setUniformValueArray (const char *name, const QMatrix4x3 *values, int count)
Sets the uniform variable array called name in the current context to the count 4x3 matrix elements of values.
void setUniformValueArray (const char *name, const QMatrix4x4 *values, int count)
Sets the uniform variable array called name in the current context to the count 4x4 matrix elements of values.
QList< QGLShader * > shaders () const
Returns a list of all shaders that have been added to this shader program using addShader().
int uniformLocation (const char *name) const
Returns the location of the uniform variable name within this shader program's parameter list.
int uniformLocation (const QByteArray &name) const
Returns the location of the uniform variable name within this shader program's parameter list.
int uniformLocation (const QString &name) const
Returns the location of the uniform variable name within this shader program's parameter list.
virtual ~QGLShaderProgram ()
Deletes this shader program.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool hasOpenGLShaderPrograms (const QGLContext *context=0)
Returns true if shader programs written in the OpenGL Shading Language (GLSL) are supported on this system; false otherwise.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Private Slots
void shaderDestroyed ()
Private Functions
bool init ()
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGLShaderProgram class allows OpenGL shader programs to be linked and used.
Since
4.6
Introduction
This class supports shader programs written in the OpenGL Shading Language (GLSL) and in the OpenGL/ES Shading Language (GLSL/ES).
QGLShader and QGLShaderProgram shelter the programmer from the details of compiling and linking vertex and fragment shaders.
The following example creates a vertex shader program using the supplied source code. Once compiled and linked, the shader program is activated in the current QGLContext by calling QGLShaderProgram::bind():
QGLShader shader(QGLShader::Vertex);
shader.compileSourceCode(code);
QGLShaderProgram program(context);
program.addShader(shader);
program.link();
program.bind();
Writing portable shaders
Shader programs can be difficult to reuse across OpenGL implementations because of varying levels of support for standard vertex attributes and uniform variables. In particular, GLSL/ES lacks all of the standard variables that are present on desktop OpenGL systems: gl_Vertex, gl_Normal, gl_Color, and so on. Desktop OpenGL lacks the variable qualifiers highp, mediump, and lowp.
The QGLShaderProgram class makes the process of writing portable shaders easier by prefixing all shader programs with the following lines on desktop OpenGL:
#define highp
#define mediump
#define lowp
This makes it possible to run most GLSL/ES shader programs on desktop systems. The programmer should restrict themselves to just features that are present in GLSL/ES, and avoid standard variable names that only work on the desktop.
Simple shader example
program.addShaderFromSourceCode(QGLShader::Vertex,
    "attribute highp vec4 vertex;\n"
    "uniform highp mat4 matrix;\n"
    "void main(void)\n"
    "{\n"
    "   gl_Position = matrix * vertex;\n"
    "}");
program.addShaderFromSourceCode(QGLShader::Fragment,
    "uniform mediump vec4 color;\n"
    "void main(void)\n"
    "{\n"
    "   gl_FragColor = color;\n"
    "}");
program.link();
program.bind();
int vertexLocation = program.attributeLocation("vertex");
int matrixLocation = program.uniformLocation("matrix");
int colorLocation = program.uniformLocation("color");
With the above shader program active, we can draw a green triangle as follows:
static GLfloat const triangleVertices[] = {
    60.0f,  10.0f,  0.0f,
    110.0f, 110.0f, 0.0f,
    10.0f,  110.0f, 0.0f
};
QColor color(0, 255, 0, 255);
QMatrix4x4 pmvMatrix;
pmvMatrix.ortho(rect());
program.enableAttributeArray(vertexLocation);
program.setAttributeArray(vertexLocation, triangleVertices, 3);
program.setUniformValue(matrixLocation, pmvMatrix);
program.setUniformValue(colorLocation, color);
glDrawArrays(GL_TRIANGLES, 0, 3);
program.disableAttributeArray(vertexLocation);
Binary shaders and programs
Binary shaders may be specified using glShaderBinary() on the return value from QGLShader::shaderId(). The QGLShader instance containing the binary can then be added to the shader program with addShader() and linked in the usual fashion with link().
Binary programs may be specified using glProgramBinaryOES() on the return value from programId(). Then the application should call link(), which will notice that the program has already been specified and linked, allowing other operations to be performed on the shader program.
See also
QGLShader
Definition at line 114 of file qglshaderprogram.h.
Constructors and Destructors
QGLShaderProgram() [1/2]
QGLShaderProgram::QGLShaderProgram (QObject * parent = 0) explicit
Constructs a new shader program and attaches it to parent.
The program will be invalid until addShader() is called.
The shader program will be associated with the current QGLContext.
See also
addShader()
Definition at line 615 of file qglshaderprogram.cpp.
     : QObject(*new QGLShaderProgramPrivate(QGLContext::currentContext()), parent)
 {
 }
QGLShaderProgram() [2/2]
QGLShaderProgram::QGLShaderProgram (const QGLContext * context, QObject * parent = 0) explicit
Constructs a new shader program and attaches it to parent.
The program will be invalid until addShader() is called.
The shader program will be associated with context.
See also
addShader()
Definition at line 628 of file qglshaderprogram.cpp.
     : QObject(*new QGLShaderProgramPrivate(context), parent)
 {
 }
~QGLShaderProgram()
QGLShaderProgram::~QGLShaderProgram () virtual
Deletes this shader program.
Definition at line 636 of file qglshaderprogram.cpp.
 {
 }
Functions
addShader()
bool QGLShaderProgram::addShader (QGLShader * shader)
Adds a compiled shader to this shader program.
Returns true if the shader could be added, or false otherwise.
Ownership of the shader object remains with the caller. It will not be deleted when this QGLShaderProgram instance is deleted. This allows the caller to add the same shader to multiple shader programs.
See also
addShaderFromSourceCode(), addShaderFromSourceFile()
removeShader(), link(), removeAllShaders()
Definition at line 680 of file qglshaderprogram.cpp.
Referenced by addShaderFromSourceCode(), addShaderFromSourceFile(), QGLEngineSharedShaders::findProgramInCache(), QGLEngineSharedShaders::QGLEngineSharedShaders(), and QGLTextureGlyphCache::resizeTextureData().
 {
     Q_D(QGLShaderProgram);
     if (!init())
         return false;
     if (d->shaders.contains(shader))
         return true;    // Already added to this shader program.
     if (d->programGuard.id() && shader) {
         if (!QGLContext::areSharing(shader->d_func()->shaderGuard.context(),
                                     d->programGuard.context())) {
             qWarning("QGLShaderProgram::addShader: Program and shader are not associated with same context.");
             return false;
         }
         if (!shader->d_func()->shaderGuard.id())
             return false;
         glAttachShader(d->programGuard.id(), shader->d_func()->shaderGuard.id());
         d->linked = false;  // Program needs to be relinked.
         d->shaders.append(shader);
         connect(shader, SIGNAL(destroyed()), this, SLOT(shaderDestroyed()));
         return true;
     } else {
         return false;
     }
 }
addShaderFromSourceCode() [1/3]
bool QGLShaderProgram::addShaderFromSourceCode (QGLShader::ShaderType type, const char * source)
Compiles source as a shader of the specified type and adds it to this shader program.
Returns true if compilation was successful, false otherwise. The compilation errors and warnings will be made available via log().
This function is intended to be a short-cut for quickly adding vertex and fragment shaders to a shader program without creating an instance of QGLShader first.
See also
addShader(), addShaderFromSourceFile()
removeShader(), link(), log(), removeAllShaders()
Definition at line 718 of file qglshaderprogram.cpp.
Referenced by addShaderFromSourceCode(), and ShaderEffectItem::updateShaderProgram().
 {
     Q_D(QGLShaderProgram);
     if (!init())
         return false;
     QGLShader *shader = new QGLShader(type, this);
     if (!shader->compileSourceCode(source)) {
         d->log = shader->log();
         delete shader;
         return false;
     }
     d->anonShaders.append(shader);
     return addShader(shader);
 }
addShaderFromSourceCode() [2/3]
bool QGLShaderProgram::addShaderFromSourceCode (QGLShader::ShaderType type, const QByteArray & source)
Compiles source as a shader of the specified type and adds it to this shader program.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if compilation was successful, false otherwise. The compilation errors and warnings will be made available via log().
This function is intended to be a short-cut for quickly adding vertex and fragment shaders to a shader program without creating an instance of QGLShader first.
See also
addShader(), addShaderFromSourceFile()
removeShader(), link(), log(), removeAllShaders()
Definition at line 751 of file qglshaderprogram.cpp.
 {
     return addShaderFromSourceCode(type, source.constData());
 }
addShaderFromSourceCode() [3/3]
bool QGLShaderProgram::addShaderFromSourceCode (QGLShader::ShaderType type, const QString & source)
Compiles source as a shader of the specified type and adds it to this shader program.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if compilation was successful, false otherwise. The compilation errors and warnings will be made available via log().
This function is intended to be a short-cut for quickly adding vertex and fragment shaders to a shader program without creating an instance of QGLShader first.
See also
addShader(), addShaderFromSourceFile()
removeShader(), link(), log(), removeAllShaders()
Definition at line 774 of file qglshaderprogram.cpp.
 {
     return addShaderFromSourceCode(type, source.toLatin1().constData());
 }
addShaderFromSourceFile()
bool QGLShaderProgram::addShaderFromSourceFile (QGLShader::ShaderType type, const QString & fileName)
Compiles the contents of fileName as a shader of the specified type and adds it to this shader program.
Returns true if compilation was successful, false otherwise. The compilation errors and warnings will be made available via log().
This function is intended to be a short-cut for quickly adding vertex and fragment shaders to a shader program without creating an instance of QGLShader first.
See also
addShader(), addShaderFromSourceCode()
Definition at line 792 of file qglshaderprogram.cpp.
Referenced by addShaderFromSourceCode().
 {
     Q_D(QGLShaderProgram);
     if (!init())
         return false;
     QGLShader *shader = new QGLShader(type, this);
     if (!shader->compileSourceFile(fileName)) {
         d->log = shader->log();
         delete shader;
         return false;
     }
     d->anonShaders.append(shader);
     return addShader(shader);
 }
attributeLocation() [1/3]
int QGLShaderProgram::attributeLocation (const char * name) const
Returns the location of the attribute name within this shader program's parameter list.
Returns -1 if name is not a valid attribute for this shader program.
See also
uniformLocation(), bindAttributeLocation()
Definition at line 1103 of file qglshaderprogram.cpp.
Referenced by attributeLocation(), disableAttributeArray(), enableAttributeArray(), setAttributeArray(), setAttributeBuffer(), and setAttributeValue().
 {
     Q_D(const QGLShaderProgram);
     if (d->linked) {
         return glGetAttribLocation(d->programGuard.id(), name);
     } else {
         qWarning() << "QGLShaderProgram::attributeLocation(" << name
                    << "): shader program is not linked";
         return -1;
     }
 }
attributeLocation() [2/3]
int QGLShaderProgram::attributeLocation (const QByteArray & name) const
Returns the location of the attribute name within this shader program's parameter list.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns -1 if name is not a valid attribute for this shader program.
See also
uniformLocation(), bindAttributeLocation()
Definition at line 1127 of file qglshaderprogram.cpp.
 {
     return attributeLocation(name.constData());
 }
attributeLocation() [3/3]
int QGLShaderProgram::attributeLocation (const QString & name) const
Returns the location of the attribute name within this shader program's parameter list.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns -1 if name is not a valid attribute for this shader program.
See also
uniformLocation(), bindAttributeLocation()
Definition at line 1144 of file qglshaderprogram.cpp.
 {
     return attributeLocation(name.toLatin1().constData());
 }
bind()
bool QGLShaderProgram::bind ()
Binds this shader program to the active QGLContext and makes it the current shader program.
Any previously bound shader program is released. This is equivalent to calling glUseProgram() on programId(). Returns true if the program was successfully bound; false otherwise. If the shader program has not yet been linked, or it needs to be re-linked, this function will call link().
See also
link(), release()
Definition at line 969 of file qglshaderprogram.cpp.
Referenced by blitTexture(), QGLEngineSharedShaders::findProgramInCache(), ShaderEffectItem::renderEffect(), QGLTextureGlyphCache::resizeTextureData(), ShaderEffectItem::updateShaderProgram(), QGLEngineShaderManager::useBlitProgram(), and QGLEngineShaderManager::useSimpleProgram().
 {
     Q_D(QGLShaderProgram);
     GLuint program = d->programGuard.id();
     if (!program)
         return false;
     if (!d->linked && !link())
         return false;
 #ifndef QT_NO_DEBUG
     if (!QGLContext::areSharing(d->programGuard.context(), QGLContext::currentContext())) {
         qWarning("QGLShaderProgram::bind: program is not valid in the current context.");
         return false;
     }
 #endif
     glUseProgram(program);
     return true;
 }
bindAttributeLocation() [1/3]
void QGLShaderProgram::bindAttributeLocation (const char * name, int location)
Binds the attribute name to the specified location.
This function can be called before or after the program has been linked. Any attributes that have not been explicitly bound when the program is linked will be assigned locations automatically.
When this function is called after the program has been linked, the program will need to be relinked for the change to take effect.
See also
attributeLocation()
Definition at line 1045 of file qglshaderprogram.cpp.
Referenced by bindAttributeLocation(), QGLEngineSharedShaders::findProgramInCache(), QGLEngineSharedShaders::QGLEngineSharedShaders(), QGLTextureGlyphCache::resizeTextureData(), and ShaderEffectItem::updateShaderProgram().
 {
     Q_D(QGLShaderProgram);
     if (!init())
         return;
     glBindAttribLocation(d->programGuard.id(), location, name);
     d->linked = false;  // Program needs to be relinked.
 }
bindAttributeLocation() [2/3]
void QGLShaderProgram::bindAttributeLocation (const QByteArray & name, int location)
Binds the attribute name to the specified location.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function can be called before or after the program has been linked. Any attributes that have not been explicitly bound when the program is linked will be assigned locations automatically.
When this function is called after the program has been linked, the program will need to be relinked for the change to take effect.
See also
attributeLocation()
Definition at line 1070 of file qglshaderprogram.cpp.
 {
     bindAttributeLocation(name.constData(), location);
 }
bindAttributeLocation() [3/3]
void QGLShaderProgram::bindAttributeLocation (const QString & name, int location)
Binds the attribute name to the specified location.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function can be called before or after the program has been linked. Any attributes that have not been explicitly bound when the program is linked will be assigned locations automatically.
When this function is called after the program has been linked, the program will need to be relinked for the change to take effect.
See also
attributeLocation()
Definition at line 1091 of file qglshaderprogram.cpp.
 {
     bindAttributeLocation(name.toLatin1().constData(), location);
 }
disableAttributeArray() [1/2]
void QGLShaderProgram::disableAttributeArray (int location)
Disables the vertex array at location in this shader program that was enabled by a previous call to enableAttributeArray().
See also
enableAttributeArray(), setAttributeArray(), setAttributeValue()
setUniformValue()
Definition at line 1805 of file qglshaderprogram.cpp.
Referenced by disableAttributeArray(), ShaderEffectItem::renderEffect(), and QGLTextureGlyphCache::resizeTextureData().
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glDisableVertexAttribArray(location);
 }
disableAttributeArray() [2/2]
void QGLShaderProgram::disableAttributeArray (const char * name)
Disables the vertex array called name in this shader program that was enabled by a previous call to enableAttributeArray().
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
enableAttributeArray(), setAttributeArray(), setAttributeValue()
setUniformValue()
Definition at line 1825 of file qglshaderprogram.cpp.
 {
     disableAttributeArray(attributeLocation(name));
 }
enableAttributeArray() [1/2]
void QGLShaderProgram::enableAttributeArray (int location)
Enables the vertex array at location in this shader program so that the value set by setAttributeArray() on location will be used by the shader program.
See also
disableAttributeArray(), setAttributeArray(), setAttributeValue()
setUniformValue()
Definition at line 1772 of file qglshaderprogram.cpp.
Referenced by enableAttributeArray(), ShaderEffectItem::renderEffect(), and QGLTextureGlyphCache::resizeTextureData().
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glEnableVertexAttribArray(location);
 }
enableAttributeArray() [2/2]
void QGLShaderProgram::enableAttributeArray (const char * name)
Enables the vertex array called name in this shader program so that the value set by setAttributeArray() on name will be used by the shader program.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
disableAttributeArray(), setAttributeArray(), setAttributeValue()
setUniformValue()
Definition at line 1793 of file qglshaderprogram.cpp.
 {
     enableAttributeArray(attributeLocation(name));
 }
geometryInputType()
GLenum QGLShaderProgram::geometryInputType () const
Returns the geometry shader input type, if active.
This parameter takes effect the next time the program is linked.
Since
4.7
Definition at line 3399 of file qglshaderprogram.cpp.
 {
     return d_func()->geometryInputType;
 }
geometryOutputType()
GLenum QGLShaderProgram::geometryOutputType () const
Returns the geometry shader output type, if active.
This parameter takes effect the next time the program is linked.
Since
4.7
Definition at line 3426 of file qglshaderprogram.cpp.
 {
     return d_func()->geometryOutputType;
 }
geometryOutputVertexCount()
int QGLShaderProgram::geometryOutputVertexCount () const
Returns the maximum number of vertices the current geometry shader program will produce, if active.
Since
4.7
This parameter takes effect the ntext time the program is linked.
Definition at line 3374 of file qglshaderprogram.cpp.
 {
     return d_func()->geometryVertexCount;
 }
hasOpenGLShaderPrograms()
bool QGLShaderProgram::hasOpenGLShaderPrograms (const QGLContext * context = 0) static
Returns true if shader programs written in the OpenGL Shading Language (GLSL) are supported on this system; false otherwise.
The context is used to resolve the GLSL extensions. If context is null, then QGLContext::currentContext() is used.
Definition at line 3439 of file qglshaderprogram.cpp.
Referenced by ShaderEffectItem::paint().
 {
 #if !defined(QT_OPENGL_ES_2)
     if (!context)
         context = QGLContext::currentContext();
     if (!context)
         return false;
     return qt_resolve_glsl_extensions(const_cast<QGLContext *>(context));
 #else
     Q_UNUSED(context);
     return true;
 #endif
 }
init()
bool QGLShaderProgram::init () private
Definition at line 640 of file qglshaderprogram.cpp.
Referenced by addShader(), addShaderFromSourceCode(), addShaderFromSourceFile(), bindAttributeLocation(), and programId().
 {
     Q_D(QGLShaderProgram);
     if (d->programGuard.id() || d->inited)
         return true;
     d->inited = true;
     const QGLContext *context = d->programGuard.context();
     if (!context) {
         context = QGLContext::currentContext();
         d->programGuard.setContext(context);
     }
     if (!context)
         return false;
     if (qt_resolve_glsl_extensions(const_cast<QGLContext *>(context))) {
         GLuint program = glCreateProgram();
         if (!program) {
             qWarning() << "QGLShaderProgram: could not create shader program";
             return false;
         }
         d->programGuard.setId(program);
         return true;
     } else {
         qWarning() << "QGLShaderProgram: shader programs are not supported";
         return false;
     }
 }
isLinked()
bool QGLShaderProgram::isLinked () const
Returns true if this shader program has been linked; false otherwise.
See also
link()
Definition at line 941 of file qglshaderprogram.cpp.
Referenced by QGLEngineSharedShaders::findProgramInCache(), QGLEngineSharedShaders::QGLEngineSharedShaders(), ShaderEffectItem::renderEffect(), and ShaderEffectItem::updateShaderProgram().
 {
     Q_D(const QGLShaderProgram);
     return d->linked;
 }
link()
bool QGLShaderProgram::link () virtual
Links together the shaders that were added to this program with addShader().
Returns true if the link was successful or false otherwise. If the link failed, the error messages can be retrieved with log().
Subclasses can override this function to initialize attributes and uniform variables for use in specific shader programs.
If the shader program was already linked, calling this function again will force it to be re-linked.
See also
addShader(), log()
Definition at line 879 of file qglshaderprogram.cpp.
Referenced by bind(), QGLEngineSharedShaders::findProgramInCache(), QGLEngineSharedShaders::QGLEngineSharedShaders(), QGLTextureGlyphCache::resizeTextureData(), and ShaderEffectItem::updateShaderProgram().
 {
     Q_D(QGLShaderProgram);
     GLuint program = d->programGuard.id();
     if (!program)
         return false;
     GLint value;
     if (d->shaders.isEmpty()) {
         // If there are no explicit shaders, then it is possible that the
         // application added a program binary with glProgramBinaryOES(),
         // or otherwise populated the shaders itself.  Check to see if the
         // program is already linked and bail out if so.
         value = 0;
         glGetProgramiv(program, GL_LINK_STATUS, &value);
         d->linked = (value != 0);
         if (d->linked)
             return true;
     }
     // Set up the geometry shader parameters
     if (glProgramParameteriEXT) {
         foreach (QGLShader *shader, d->shaders) {
             if (shader->shaderType() & QGLShader::Geometry) {
                 glProgramParameteriEXT(program, GL_GEOMETRY_INPUT_TYPE_EXT,
                                        d->geometryInputType);
                 glProgramParameteriEXT(program, GL_GEOMETRY_OUTPUT_TYPE_EXT,
                                        d->geometryOutputType);
                 glProgramParameteriEXT(program, GL_GEOMETRY_VERTICES_OUT_EXT,
                                        d->geometryVertexCount);
                 break;
             }
         }
     }
     glLinkProgram(program);
     value = 0;
     glGetProgramiv(program, GL_LINK_STATUS, &value);
     d->linked = (value != 0);
     value = 0;
     glGetProgramiv(program, GL_INFO_LOG_LENGTH, &value);
     d->log = QString();
     if (value > 1) {
         char *logbuf = new char [value];
         GLint len;
         glGetProgramInfoLog(program, value, &len, logbuf);
         d->log = QString::fromLatin1(logbuf);
         QString name = objectName();
         if (name.isEmpty())
             qWarning() << "QGLShader::link:" << d->log;
         else
             qWarning() << "QGLShader::link[" << name << "]:" << d->log;
         delete [] logbuf;
     }
     return d->linked;
 }
log()
QString QGLShaderProgram::log () const
Returns the errors and warnings that occurred during the last link() or addShader() with explicitly specified source code.
See also
link()
Definition at line 953 of file qglshaderprogram.cpp.
Referenced by QGLEngineSharedShaders::findProgramInCache(), QGLEngineSharedShaders::QGLEngineSharedShaders(), and ShaderEffectItem::updateShaderProgram().
 {
     Q_D(const QGLShaderProgram);
     return d->log;
 }
maxGeometryOutputVertices()
int QGLShaderProgram::maxGeometryOutputVertices () const
Returns the hardware limit for how many vertices a geometry shader can output.
Since
4.7
See also
setGeometryOutputVertexCount()
Definition at line 3338 of file qglshaderprogram.cpp.
Referenced by setGeometryOutputVertexCount().
 {
     GLint n;
     glGetIntegerv(GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT, &n);
     return n;
 }
programId()
GLuint QGLShaderProgram::programId () const
Returns the OpenGL identifier associated with this shader program.
See also
QGLShader::shaderId()
Definition at line 1019 of file qglshaderprogram.cpp.
Referenced by ShaderEffectItem::renderEffect().
 {
     Q_D(const QGLShaderProgram);
     GLuint id = d->programGuard.id();
     if (id)
         return id;
     // Create the identifier if we don't have one yet.  This is for
     // applications that want to create the attached shader configuration
     // themselves, particularly those using program binaries.
     if (!const_cast<QGLShaderProgram *>(this)->init())
         return 0;
     return d->programGuard.id();
 }
release()
void QGLShaderProgram::release ()
Releases the active shader program from the current QGLContext.
This is equivalent to calling glUseProgram(0).
See also
bind()
Definition at line 996 of file qglshaderprogram.cpp.
 {
 #ifndef QT_NO_DEBUG
     Q_D(QGLShaderProgram);
     if (!QGLContext::areSharing(d->programGuard.context(), QGLContext::currentContext()))
         qWarning("QGLShaderProgram::release: program is not valid in the current context.");
 #endif
 #if defined(QT_OPENGL_ES_2)
     glUseProgram(0);
 #else
     if (glUseProgram)
         glUseProgram(0);
 #endif
 }
removeAllShaders()
void QGLShaderProgram::removeAllShaders ()
Removes all of the shaders that were added to this program previously.
The QGLShader objects for the shaders will not be deleted if they were constructed externally. QGLShader objects that are constructed internally by QGLShaderProgram will be deleted.
See also
addShader(), removeShader()
Definition at line 847 of file qglshaderprogram.cpp.
Referenced by ShaderEffectItem::reset().
 {
     Q_D(QGLShaderProgram);
     d->removingShaders = true;
     foreach (QGLShader *shader, d->shaders) {
         if (d->programGuard.id() && shader && shader->d_func()->shaderGuard.id())
             glDetachShader(d->programGuard.id(), shader->d_func()->shaderGuard.id());
     }
     foreach (QGLShader *shader, d->anonShaders) {
         // Delete shader objects that were created anonymously.
         delete shader;
     }
     d->shaders.clear();
     d->anonShaders.clear();
     d->linked = false;  // Program needs to be relinked.
     d->removingShaders = false;
 }
removeShader()
void QGLShaderProgram::removeShader (QGLShader * shader)
Removes shader from this shader program.
The object is not deleted.
See also
addShader(), link(), removeAllShaders()
Definition at line 812 of file qglshaderprogram.cpp.
Referenced by shaderDestroyed().
 {
     Q_D(QGLShaderProgram);
     if (d->programGuard.id() && shader && shader->d_func()->shaderGuard.id()) {
         QGLShareContextScope scope(d->programGuard.context());
         glDetachShader(d->programGuard.id(), shader->d_func()->shaderGuard.id());
     }
     d->linked = false;  // Program needs to be relinked.
     if (shader) {
         d->shaders.removeAll(shader);
         d->anonShaders.removeAll(shader);
         disconnect(shader, SIGNAL(destroyed()), this, SLOT(shaderDestroyed()));
     }
 }
setAttributeArray() [1/10]
void QGLShaderProgram::setAttributeArray (int location, const GLfloat * values, int tupleSize, int stride = 0)
Sets an array of vertex values on the attribute at location in this shader program.
The tupleSize indicates the number of components per vertex (1, 2, 3, or 4), and the stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in values.
The array will become active when enableAttributeArray() is called on the location. Otherwise the value specified with setAttributeValue() for location will be used.
See also
setAttributeValue(), setUniformValue(), enableAttributeArray()
disableAttributeArray()
Definition at line 1461 of file qglshaderprogram.cpp.
Referenced by ShaderEffectItem::bindGeometry(), QGLShader::hasOpenGLShaders(), setAttributeArray(), and setAttributeValue().
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         glVertexAttribPointer(location, tupleSize, GL_FLOAT, GL_FALSE,
                               stride, values);
     }
 }
setAttributeArray() [2/10]
void QGLShaderProgram::setAttributeArray (int location, const QVector2D * values, int stride = 0)
Sets an array of 2D vertex values on the attribute at location in this shader program.
The stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in values.
The array will become active when enableAttributeArray() is called on the location. Otherwise the value specified with setAttributeValue() for location will be used.
See also
setAttributeValue(), setUniformValue(), enableAttributeArray()
disableAttributeArray()
Definition at line 1485 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         glVertexAttribPointer(location, 2, GL_FLOAT, GL_FALSE,
                               stride, values);
     }
 }
setAttributeArray() [3/10]
void QGLShaderProgram::setAttributeArray (int location, const QVector3D * values, int stride = 0)
Sets an array of 3D vertex values on the attribute at location in this shader program.
The stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in values.
The array will become active when enableAttributeArray() is called on the location. Otherwise the value specified with setAttributeValue() for location will be used.
See also
setAttributeValue(), setUniformValue(), enableAttributeArray()
disableAttributeArray()
Definition at line 1509 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         glVertexAttribPointer(location, 3, GL_FLOAT, GL_FALSE,
                               stride, values);
     }
 }
setAttributeArray() [4/10]
void QGLShaderProgram::setAttributeArray (int location, const QVector4D * values, int stride = 0)
Sets an array of 4D vertex values on the attribute at location in this shader program.
The stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in values.
The array will become active when enableAttributeArray() is called on the location. Otherwise the value specified with setAttributeValue() for location will be used.
See also
setAttributeValue(), setUniformValue(), enableAttributeArray()
disableAttributeArray()
Definition at line 1533 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         glVertexAttribPointer(location, 4, GL_FLOAT, GL_FALSE,
                               stride, values);
     }
 }
setAttributeArray() [5/10]
void QGLShaderProgram::setAttributeArray (int location, GLenum type, const void * values, int tupleSize, int stride = 0)
Sets an array of vertex values on the attribute at location in this shader program.
The stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in values.
The type indicates the type of elements in the values array, usually GL_FLOAT, GL_UNSIGNED_BYTE, etc. The tupleSize indicates the number of components per vertex: 1, 2, 3, or 4.
The array will become active when enableAttributeArray() is called on the location. Otherwise the value specified with setAttributeValue() for location will be used.
The setAttributeBuffer() function can be used to set the attribute array to an offset within a vertex buffer.
See also
setAttributeValue(), setUniformValue(), enableAttributeArray()
disableAttributeArray(), setAttributeBuffer()
Since
4.7
Definition at line 1565 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         glVertexAttribPointer(location, tupleSize, type, GL_TRUE,
                               stride, values);
     }
 }
setAttributeArray() [6/10]
void QGLShaderProgram::setAttributeArray (const char * name, const GLfloat * values, int tupleSize, int stride = 0)
Sets an array of vertex values on the attribute called name in this shader program.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The tupleSize indicates the number of components per vertex (1, 2, 3, or 4), and the stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in values.
The array will become active when enableAttributeArray() is called on name. Otherwise the value specified with setAttributeValue() for name will be used.
See also
setAttributeValue(), setUniformValue(), enableAttributeArray()
disableAttributeArray()
Definition at line 1595 of file qglshaderprogram.cpp.
 {
     setAttributeArray(attributeLocation(name), values, tupleSize, stride);
 }
setAttributeArray() [7/10]
void QGLShaderProgram::setAttributeArray (const char * name, const QVector2D * values, int stride = 0)
Sets an array of 2D vertex values on the attribute called name in this shader program.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in values.
The array will become active when enableAttributeArray() is called on name. Otherwise the value specified with setAttributeValue() for name will be used.
See also
setAttributeValue(), setUniformValue(), enableAttributeArray()
disableAttributeArray()
Definition at line 1619 of file qglshaderprogram.cpp.
 {
     setAttributeArray(attributeLocation(name), values, stride);
 }
setAttributeArray() [8/10]
void QGLShaderProgram::setAttributeArray (const char * name, const QVector3D * values, int stride = 0)
Sets an array of 3D vertex values on the attribute called name in this shader program.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in values.
The array will become active when enableAttributeArray() is called on name. Otherwise the value specified with setAttributeValue() for name will be used.
See also
setAttributeValue(), setUniformValue(), enableAttributeArray()
disableAttributeArray()
Definition at line 1643 of file qglshaderprogram.cpp.
 {
     setAttributeArray(attributeLocation(name), values, stride);
 }
setAttributeArray() [9/10]
void QGLShaderProgram::setAttributeArray (const char * name, const QVector4D * values, int stride = 0)
Sets an array of 4D vertex values on the attribute called name in this shader program.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in values.
The array will become active when enableAttributeArray() is called on name. Otherwise the value specified with setAttributeValue() for name will be used.
See also
setAttributeValue(), setUniformValue(), enableAttributeArray()
disableAttributeArray()
Definition at line 1667 of file qglshaderprogram.cpp.
 {
     setAttributeArray(attributeLocation(name), values, stride);
 }
setAttributeArray() [10/10]
void QGLShaderProgram::setAttributeArray (const char * name, GLenum type, const void * values, int tupleSize, int stride = 0)
Sets an array of vertex values on the attribute called name in this shader program.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in values.
The type indicates the type of elements in the values array, usually GL_FLOAT, GL_UNSIGNED_BYTE, etc. The tupleSize indicates the number of components per vertex: 1, 2, 3, or 4.
The array will become active when enableAttributeArray() is called on the name. Otherwise the value specified with setAttributeValue() for name will be used.
The setAttributeBuffer() function can be used to set the attribute array to an offset within a vertex buffer.
See also
setAttributeValue(), setUniformValue(), enableAttributeArray()
disableAttributeArray(), setAttributeBuffer()
Since
4.7
Definition at line 1699 of file qglshaderprogram.cpp.
 {
     setAttributeArray(attributeLocation(name), type, values, tupleSize, stride);
 }
setAttributeBuffer() [1/2]
void QGLShaderProgram::setAttributeBuffer (int location, GLenum type, int offset, int tupleSize, int stride = 0)
Sets an array of vertex values on the attribute at location in this shader program, starting at a specific offset in the currently bound vertex buffer.
The stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in the value array.
The type indicates the type of elements in the vertex value array, usually GL_FLOAT, GL_UNSIGNED_BYTE, etc. The tupleSize indicates the number of components per vertex: 1, 2, 3, or 4.
The array will become active when enableAttributeArray() is called on the location. Otherwise the value specified with setAttributeValue() for location will be used.
See also
setAttributeArray()
Since
4.7
Definition at line 1724 of file qglshaderprogram.cpp.
Referenced by QGLShader::hasOpenGLShaders(), setAttributeArray(), and setAttributeBuffer().
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         glVertexAttribPointer(location, tupleSize, type, GL_TRUE, stride,
                               reinterpret_cast<const void *>(offset));
     }
 }
setAttributeBuffer() [2/2]
void QGLShaderProgram::setAttributeBuffer (const char * name, GLenum type, int offset, int tupleSize, int stride = 0)
Sets an array of vertex values on the attribute called name in this shader program, starting at a specific offset in the currently bound vertex buffer.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The stride indicates the number of bytes between vertices. A default stride value of zero indicates that the vertices are densely packed in the value array.
The type indicates the type of elements in the vertex value array, usually GL_FLOAT, GL_UNSIGNED_BYTE, etc. The tupleSize indicates the number of components per vertex: 1, 2, 3, or 4.
The array will become active when enableAttributeArray() is called on the name. Otherwise the value specified with setAttributeValue() for name will be used.
See also
setAttributeArray()
Since
4.7
Definition at line 1759 of file qglshaderprogram.cpp.
 {
     setAttributeBuffer(attributeLocation(name), type, offset, tupleSize, stride);
 }
setAttributeValue() [1/18]
void QGLShaderProgram::setAttributeValue (int location, GLfloat value)
Sets the attribute at location in the current context to value.
See also
setUniformValue()
Definition at line 1154 of file qglshaderprogram.cpp.
Referenced by setAttributeValue().
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glVertexAttrib1fv(location, &value);
 }
setAttributeValue() [2/18]
void QGLShaderProgram::setAttributeValue (int location, GLfloat x, GLfloat y)
Sets the attribute at location in the current context to the 2D vector (x, y).
See also
setUniformValue()
Definition at line 1183 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[2] = {x, y};
         glVertexAttrib2fv(location, values);
     }
 }
setAttributeValue() [3/18]
void QGLShaderProgram::setAttributeValue (int location, GLfloat x, GLfloat y, GLfloat z)
Sets the attribute at location in the current context to the 3D vector (x, y, z).
See also
setUniformValue()
Definition at line 1216 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[3] = {x, y, z};
         glVertexAttrib3fv(location, values);
     }
 }
setAttributeValue() [4/18]
void QGLShaderProgram::setAttributeValue (int location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Sets the attribute at location in the current context to the 4D vector (x, y, z, w).
See also
setUniformValue()
Definition at line 1250 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[4] = {x, y, z, w};
         glVertexAttrib4fv(location, values);
     }
 }
setAttributeValue() [5/18]
void QGLShaderProgram::setAttributeValue (int location, const QVector2D & value)
Sets the attribute at location in the current context to value.
See also
setUniformValue()
Definition at line 1282 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glVertexAttrib2fv(location, reinterpret_cast<const GLfloat *>(&value));
 }
setAttributeValue() [6/18]
void QGLShaderProgram::setAttributeValue (int location, const QVector3D & value)
Sets the attribute at location in the current context to value.
See also
setUniformValue()
Definition at line 1310 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glVertexAttrib3fv(location, reinterpret_cast<const GLfloat *>(&value));
 }
setAttributeValue() [7/18]
void QGLShaderProgram::setAttributeValue (int location, const QVector4D & value)
Sets the attribute at location in the current context to value.
See also
setUniformValue()
Definition at line 1338 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glVertexAttrib4fv(location, reinterpret_cast<const GLfloat *>(&value));
 }
setAttributeValue() [8/18]
void QGLShaderProgram::setAttributeValue (int location, const QColor & value)
Sets the attribute at location in the current context to value.
See also
setUniformValue()
Definition at line 1366 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[4] = {GLfloat(value.redF()), GLfloat(value.greenF()),
                              GLfloat(value.blueF()), GLfloat(value.alphaF())};
         glVertexAttrib4fv(location, values);
     }
 }
setAttributeValue() [9/18]
void QGLShaderProgram::setAttributeValue (int location, const GLfloat * values, int columns, int rows)
Sets the attribute at location in the current context to the contents of values, which contains columns elements, each consisting of rows elements.
The rows value should be 1, 2, 3, or 4. This function is typically used to set matrix values and column vectors.
See also
setUniformValue()
Definition at line 1402 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (rows < 1 || rows > 4) {
         qWarning() << "QGLShaderProgram::setAttributeValue: rows" << rows << "not supported";
         return;
     }
     if (location != -1) {
         while (columns-- > 0) {
             if (rows == 1)
                 glVertexAttrib1fv(location, values);
             else if (rows == 2)
                 glVertexAttrib2fv(location, values);
             else if (rows == 3)
                 glVertexAttrib3fv(location, values);
             else
                 glVertexAttrib4fv(location, values);
             values += rows;
             ++location;
         }
     }
 }
setAttributeValue() [10/18]
void QGLShaderProgram::setAttributeValue (const char * name, GLfloat value)
Sets the attribute called name in the current context to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setUniformValue()
Definition at line 1172 of file qglshaderprogram.cpp.
 {
     setAttributeValue(attributeLocation(name), value);
 }
setAttributeValue() [11/18]
void QGLShaderProgram::setAttributeValue (const char * name, GLfloat x, GLfloat y)
Sets the attribute called name in the current context to the 2D vector (x, y).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setUniformValue()
Definition at line 1204 of file qglshaderprogram.cpp.
 {
     setAttributeValue(attributeLocation(name), x, y);
 }
setAttributeValue() [12/18]
void QGLShaderProgram::setAttributeValue (const char * name, GLfloat x, GLfloat y, GLfloat z)
Sets the attribute called name in the current context to the 3D vector (x, y, z).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setUniformValue()
Definition at line 1238 of file qglshaderprogram.cpp.
 {
     setAttributeValue(attributeLocation(name), x, y, z);
 }
setAttributeValue() [13/18]
void QGLShaderProgram::setAttributeValue (const char * name, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Sets the attribute called name in the current context to the 4D vector (x, y, z, w).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setUniformValue()
Definition at line 1272 of file qglshaderprogram.cpp.
 {
     setAttributeValue(attributeLocation(name), x, y, z, w);
 }
setAttributeValue() [14/18]
void QGLShaderProgram::setAttributeValue (const char * name, const QVector2D & value)
Sets the attribute called name in the current context to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setUniformValue()
Definition at line 1300 of file qglshaderprogram.cpp.
 {
     setAttributeValue(attributeLocation(name), value);
 }
setAttributeValue() [15/18]
void QGLShaderProgram::setAttributeValue (const char * name, const QVector3D & value)
Sets the attribute called name in the current context to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setUniformValue()
Definition at line 1328 of file qglshaderprogram.cpp.
 {
     setAttributeValue(attributeLocation(name), value);
 }
setAttributeValue() [16/18]
void QGLShaderProgram::setAttributeValue (const char * name, const QVector4D & value)
Sets the attribute called name in the current context to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setUniformValue()
Definition at line 1356 of file qglshaderprogram.cpp.
 {
     setAttributeValue(attributeLocation(name), value);
 }
setAttributeValue() [17/18]
void QGLShaderProgram::setAttributeValue (const char * name, const QColor & value)
Sets the attribute called name in the current context to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setUniformValue()
Definition at line 1387 of file qglshaderprogram.cpp.
 {
     setAttributeValue(attributeLocation(name), value);
 }
setAttributeValue() [18/18]
void QGLShaderProgram::setAttributeValue (const char * name, const GLfloat * values, int columns, int rows)
Sets the attribute called name in the current context to the contents of values, which contains columns elements, each consisting of rows elements.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The rows value should be 1, 2, 3, or 4. This function is typically used to set matrix values and column vectors.
See also
setUniformValue()
Definition at line 1441 of file qglshaderprogram.cpp.
 {
     setAttributeValue(attributeLocation(name), values, columns, rows);
 }
setGeometryInputType()
void QGLShaderProgram::setGeometryInputType (GLenum inputType)
Sets the input type from inputType.
This parameter takes effect the next time the program is linked.
Definition at line 3385 of file qglshaderprogram.cpp.
 {
     d_func()->geometryInputType = inputType;
 }
setGeometryOutputType()
void QGLShaderProgram::setGeometryOutputType (GLenum outputType)
Sets the output type from the geometry shader, if active, to outputType.
This parameter takes effect the next time the program is linked.
Since
4.7
Definition at line 3413 of file qglshaderprogram.cpp.
 {
     d_func()->geometryOutputType = outputType;
 }
setGeometryOutputVertexCount()
void QGLShaderProgram::setGeometryOutputVertexCount (int count)
Sets the maximum number of vertices the current geometry shader program will produce, if active, to count.
Since
4.7
This parameter takes effect the next time the program is linked.
Definition at line 3353 of file qglshaderprogram.cpp.
 {
 #ifndef QT_NO_DEBUG
     int max = maxGeometryOutputVertices();
     if (count > max) {
         qWarning("QGLShaderProgram::setGeometryOutputVertexCount: count: %d higher than maximum: %d",
                  count, max);
     }
 #endif
     d_func()->geometryVertexCount = count;
 }
setUniformValue() [1/54]
void QGLShaderProgram::setUniformValue (int location, GLfloat value)
Sets the uniform variable at location in the current context to value.
See also
setAttributeValue()
Definition at line 1889 of file qglshaderprogram.cpp.
Referenced by QGL2PaintEngineExPrivate::drawTexture(), QGLEngineSharedShaders::findProgramInCache(), QGLShader::hasOpenGLShaders(), QGL2PaintEngineExPrivate::prepareForDraw(), QGLTextureGlyphCache::resizeTextureData(), QGLPixmapColorizeFilter::setUniforms(), QGLPixmapConvolutionFilter::setUniforms(), QGLPixmapDropShadowFilter::setUniforms(), setUniformValue(), QGL2PaintEngineExPrivate::updateBrushUniforms(), ShaderEffectItem::updateEffectState(), and ShaderEffectItem::updateShaderProgram().
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniform1fv(location, 1, &value);
 }
setUniformValue() [2/54]
void QGLShaderProgram::setUniformValue (int location, GLint value)
Sets the uniform variable at location in the current context to value.
See also
setAttributeValue()
Definition at line 1918 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniform1i(location, value);
 }
setUniformValue() [3/54]
void QGLShaderProgram::setUniformValue (int location, GLuint value)
Sets the uniform variable at location in the current context to value.
This function should be used when setting sampler values.
See also
setAttributeValue()
Definition at line 1948 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniform1i(location, value);
 }
setUniformValue() [4/54]
void QGLShaderProgram::setUniformValue (int location, GLfloat x, GLfloat y)
Sets the uniform variable at location in the current context to the 2D vector (x, y).
See also
setAttributeValue()
Definition at line 1978 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[2] = {x, y};
         glUniform2fv(location, 1, values);
     }
 }
setUniformValue() [5/54]
void QGLShaderProgram::setUniformValue (int location, GLfloat x, GLfloat y, GLfloat z)
Sets the uniform variable at location in the current context to the 3D vector (x, y, z).
See also
setAttributeValue()
Definition at line 2011 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[3] = {x, y, z};
         glUniform3fv(location, 1, values);
     }
 }
setUniformValue() [6/54]
void QGLShaderProgram::setUniformValue (int location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Sets the uniform variable at location in the current context to the 4D vector (x, y, z, w).
See also
setAttributeValue()
Definition at line 2045 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[4] = {x, y, z, w};
         glUniform4fv(location, 1, values);
     }
 }
setUniformValue() [7/54]
void QGLShaderProgram::setUniformValue (int location, const QVector2D & value)
Sets the uniform variable at location in the current context to value.
See also
setAttributeValue()
Definition at line 2077 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniform2fv(location, 1, reinterpret_cast<const GLfloat *>(&value));
 }
setUniformValue() [8/54]
void QGLShaderProgram::setUniformValue (int location, const QVector3D & value)
Sets the uniform variable at location in the current context to value.
See also
setAttributeValue()
Definition at line 2106 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniform3fv(location, 1, reinterpret_cast<const GLfloat *>(&value));
 }
setUniformValue() [9/54]
void QGLShaderProgram::setUniformValue (int location, const QVector4D & value)
Sets the uniform variable at location in the current context to value.
See also
setAttributeValue()
Definition at line 2135 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniform4fv(location, 1, reinterpret_cast<const GLfloat *>(&value));
 }
setUniformValue() [10/54]
void QGLShaderProgram::setUniformValue (int location, const QColor & color)
Sets the uniform variable at location in the current context to the red, green, blue, and alpha components of color.
See also
setAttributeValue()
Definition at line 2165 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[4] = {GLfloat(color.redF()), GLfloat(color.greenF()),
                              GLfloat(color.blueF()), GLfloat(color.alphaF())};
         glUniform4fv(location, 1, values);
     }
 }
setUniformValue() [11/54]
void QGLShaderProgram::setUniformValue (int location, const QPoint & point)
Sets the uniform variable at location in the current context to the x and y coordinates of point.
See also
setAttributeValue()
Definition at line 2198 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[4] = {GLfloat(point.x()), GLfloat(point.y())};
         glUniform2fv(location, 1, values);
     }
 }
setUniformValue() [12/54]
void QGLShaderProgram::setUniformValue (int location, const QPointF & point)
Sets the uniform variable at location in the current context to the x and y coordinates of point.
See also
setAttributeValue()
Definition at line 2230 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[4] = {GLfloat(point.x()), GLfloat(point.y())};
         glUniform2fv(location, 1, values);
     }
 }
setUniformValue() [13/54]
void QGLShaderProgram::setUniformValue (int location, const QSize & size)
Sets the uniform variable at location in the current context to the width and height of the given size.
See also
setAttributeValue()
Definition at line 2262 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[4] = {GLfloat(size.width()), GLfloat(size.height())};
         glUniform2fv(location, 1, values);
     }
 }
setUniformValue() [14/54]
void QGLShaderProgram::setUniformValue (int location, const QSizeF & size)
Sets the uniform variable at location in the current context to the width and height of the given size.
See also
setAttributeValue()
Definition at line 2294 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat values[4] = {GLfloat(size.width()), GLfloat(size.height())};
         glUniform2fv(location, 1, values);
     }
 }
setUniformValue() [15/54]
void QGLShaderProgram::setUniformValue (int location, const QMatrix2x2 & value)
Sets the uniform variable at location in the current context to a 2x2 matrix value.
See also
setAttributeValue()
Definition at line 2378 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformMatrix(glUniformMatrix2fv, location, value, 2, 2);
 }
setUniformValue() [16/54]
void QGLShaderProgram::setUniformValue (int location, const QMatrix2x3 & value)
Sets the uniform variable at location in the current context to a 2x3 matrix value.
See also
setAttributeValue()
Definition at line 2407 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrix
         (glUniformMatrix2x3fv, glUniform3fv, location, value, 2, 3);
 }
setUniformValue() [17/54]
void QGLShaderProgram::setUniformValue (int location, const QMatrix2x4 & value)
Sets the uniform variable at location in the current context to a 2x4 matrix value.
See also
setAttributeValue()
Definition at line 2437 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrix
         (glUniformMatrix2x4fv, glUniform4fv, location, value, 2, 4);
 }
setUniformValue() [18/54]
void QGLShaderProgram::setUniformValue (int location, const QMatrix3x2 & value)
Sets the uniform variable at location in the current context to a 3x2 matrix value.
See also
setAttributeValue()
Definition at line 2467 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrix
         (glUniformMatrix3x2fv, glUniform2fv, location, value, 3, 2);
 }
setUniformValue() [19/54]
void QGLShaderProgram::setUniformValue (int location, const QMatrix3x3 & value)
Sets the uniform variable at location in the current context to a 3x3 matrix value.
See also
setAttributeValue()
Definition at line 2497 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformMatrix(glUniformMatrix3fv, location, value, 3, 3);
 }
setUniformValue() [20/54]
void QGLShaderProgram::setUniformValue (int location, const QMatrix3x4 & value)
Sets the uniform variable at location in the current context to a 3x4 matrix value.
See also
setAttributeValue()
Definition at line 2526 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrix
         (glUniformMatrix3x4fv, glUniform4fv, location, value, 3, 4);
 }
setUniformValue() [21/54]
void QGLShaderProgram::setUniformValue (int location, const QMatrix4x2 & value)
Sets the uniform variable at location in the current context to a 4x2 matrix value.
See also
setAttributeValue()
Definition at line 2556 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrix
         (glUniformMatrix4x2fv, glUniform2fv, location, value, 4, 2);
 }
setUniformValue() [22/54]
void QGLShaderProgram::setUniformValue (int location, const QMatrix4x3 & value)
Sets the uniform variable at location in the current context to a 4x3 matrix value.
See also
setAttributeValue()
Definition at line 2586 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrix
         (glUniformMatrix4x3fv, glUniform3fv, location, value, 4, 3);
 }
setUniformValue() [23/54]
void QGLShaderProgram::setUniformValue (int location, const QMatrix4x4 & value)
Sets the uniform variable at location in the current context to a 4x4 matrix value.
See also
setAttributeValue()
Definition at line 2616 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformMatrix(glUniformMatrix4fv, location, value, 4, 4);
 }
setUniformValue() [24/54]
void QGLShaderProgram::setUniformValue (int location, const GLfloat value[2][2])
Sets the uniform variable at location in the current context to a 2x2 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The matrix elements must be specified in column-major order.
See also
setAttributeValue()
Since
4.7
Definition at line 2652 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniformMatrix2fv(location, 1, GL_FALSE, value[0]);
 }
setUniformValue() [25/54]
void QGLShaderProgram::setUniformValue (int location, const GLfloat value[3][3])
Sets the uniform variable at location in the current context to a 3x3 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The matrix elements must be specified in column-major order.
See also
setAttributeValue()
Since
4.7
Definition at line 2673 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniformMatrix3fv(location, 1, GL_FALSE, value[0]);
 }
setUniformValue() [26/54]
void QGLShaderProgram::setUniformValue (int location, const GLfloat value[4][4])
Sets the uniform variable at location in the current context to a 4x4 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The matrix elements must be specified in column-major order.
See also
setAttributeValue()
Definition at line 2693 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniformMatrix4fv(location, 1, GL_FALSE, value[0]);
 }
setUniformValue() [27/54]
void QGLShaderProgram::setUniformValue (int location, const QTransform & value)
Sets the uniform variable at location in the current context to a 3x3 transformation matrix value that is specified as a QTransform value.
To set a QTransform value as a 4x4 matrix in a shader, use setUniformValue(location, QMatrix4x4(value)).
Definition at line 2762 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         GLfloat mat[3][3] = {
             {GLfloat(value.m11()), GLfloat(value.m12()), GLfloat(value.m13())},
             {GLfloat(value.m21()), GLfloat(value.m22()), GLfloat(value.m23())},
             {GLfloat(value.m31()), GLfloat(value.m32()), GLfloat(value.m33())}
         };
         glUniformMatrix3fv(location, 1, GL_FALSE, mat[0]);
     }
 }
setUniformValue() [28/54]
void QGLShaderProgram::setUniformValue (const char * name, GLfloat value)
Sets the uniform variable called name in the current context to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 1908 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [29/54]
void QGLShaderProgram::setUniformValue (const char * name, GLint value)
Sets the uniform variable called name in the current context to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 1937 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [30/54]
void QGLShaderProgram::setUniformValue (const char * name, GLuint value)
Sets the uniform variable called name in the current context to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function should be used when setting sampler values.
See also
setAttributeValue()
Definition at line 1967 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [31/54]
void QGLShaderProgram::setUniformValue (const char * name, GLfloat x, GLfloat y)
Sets the uniform variable called name in the current context to the 2D vector (x, y).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 1999 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), x, y);
 }
setUniformValue() [32/54]
void QGLShaderProgram::setUniformValue (const char * name, GLfloat x, GLfloat y, GLfloat z)
Sets the uniform variable called name in the current context to the 3D vector (x, y, z).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2033 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), x, y, z);
 }
setUniformValue() [33/54]
void QGLShaderProgram::setUniformValue (const char * name, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Sets the uniform variable called name in the current context to the 4D vector (x, y, z, w).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2067 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), x, y, z, w);
 }
setUniformValue() [34/54]
void QGLShaderProgram::setUniformValue (const char * name, const QVector2D & value)
Sets the uniform variable called name in the current context to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2096 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [35/54]
void QGLShaderProgram::setUniformValue (const char * name, const QVector3D & value)
Sets the uniform variable called name in the current context to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2125 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [36/54]
void QGLShaderProgram::setUniformValue (const char * name, const QVector4D & value)
Sets the uniform variable called name in the current context to value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2154 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [37/54]
void QGLShaderProgram::setUniformValue (const char * name, const QColor & color)
Sets the uniform variable called name in the current context to the red, green, blue, and alpha components of color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2187 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), color);
 }
setUniformValue() [38/54]
void QGLShaderProgram::setUniformValue (const char * name, const QPoint & point)
Sets the uniform variable associated with name in the current context to the x and y coordinates of point.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2219 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), point);
 }
setUniformValue() [39/54]
void QGLShaderProgram::setUniformValue (const char * name, const QPointF & point)
Sets the uniform variable associated with name in the current context to the x and y coordinates of point.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2251 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), point);
 }
setUniformValue() [40/54]
void QGLShaderProgram::setUniformValue (const char * name, const QSize & size)
Sets the uniform variable associated with name in the current context to the width and height of the given size.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2283 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), size);
 }
setUniformValue() [41/54]
void QGLShaderProgram::setUniformValue (const char * name, const QSizeF & size)
Sets the uniform variable associated with name in the current context to the width and height of the given size.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2315 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), size);
 }
setUniformValue() [42/54]
void QGLShaderProgram::setUniformValue (const char * name, const QMatrix2x2 & value)
Sets the uniform variable called name in the current context to a 2x2 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2396 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [43/54]
void QGLShaderProgram::setUniformValue (const char * name, const QMatrix2x3 & value)
Sets the uniform variable called name in the current context to a 2x3 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2426 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [44/54]
void QGLShaderProgram::setUniformValue (const char * name, const QMatrix2x4 & value)
Sets the uniform variable called name in the current context to a 2x4 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2456 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [45/54]
void QGLShaderProgram::setUniformValue (const char * name, const QMatrix3x2 & value)
Sets the uniform variable called name in the current context to a 3x2 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2486 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [46/54]
void QGLShaderProgram::setUniformValue (const char * name, const QMatrix3x3 & value)
Sets the uniform variable called name in the current context to a 3x3 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2515 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [47/54]
void QGLShaderProgram::setUniformValue (const char * name, const QMatrix3x4 & value)
Sets the uniform variable called name in the current context to a 3x4 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2545 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [48/54]
void QGLShaderProgram::setUniformValue (const char * name, const QMatrix4x2 & value)
Sets the uniform variable called name in the current context to a 4x2 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2575 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [49/54]
void QGLShaderProgram::setUniformValue (const char * name, const QMatrix4x3 & value)
Sets the uniform variable called name in the current context to a 4x3 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2605 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [50/54]
void QGLShaderProgram::setUniformValue (const char * name, const QMatrix4x4 & value)
Sets the uniform variable called name in the current context to a 4x4 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2634 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [51/54]
void QGLShaderProgram::setUniformValue (const char * name, const GLfloat value[2][2])
Sets the uniform variable called name in the current context to a 2x2 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The matrix elements must be specified in column-major order.
See also
setAttributeValue()
Since
4.7
Definition at line 2715 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [52/54]
void QGLShaderProgram::setUniformValue (const char * name, const GLfloat value[3][3])
Sets the uniform variable called name in the current context to a 3x3 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The matrix elements must be specified in column-major order.
See also
setAttributeValue()
Since
4.7
Definition at line 2733 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [53/54]
void QGLShaderProgram::setUniformValue (const char * name, const GLfloat value[4][4])
Sets the uniform variable called name in the current context to a 4x4 matrix value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The matrix elements must be specified in column-major order.
See also
setAttributeValue()
Definition at line 2750 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValue() [54/54]
void QGLShaderProgram::setUniformValue (const char * name, const QTransform & value)
Sets the uniform variable called name in the current context to a 3x3 transformation matrix value that is specified as a QTransform value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
To set a QTransform value as a 4x4 matrix in a shader, use setUniformValue(name, QMatrix4x4(value)).
Definition at line 2789 of file qglshaderprogram.cpp.
 {
     setUniformValue(uniformLocation(name), value);
 }
setUniformValueArray() [1/30]
void QGLShaderProgram::setUniformValueArray (int location, const GLfloat * values, int count, int tupleSize)
Sets the uniform variable array at location in the current context to the count elements of values.
Each element has tupleSize components. The tupleSize must be 1, 2, 3, or 4.
See also
setAttributeValue()
Definition at line 2865 of file qglshaderprogram.cpp.
Referenced by QGLShader::hasOpenGLShaders(), QGLPixmapConvolutionFilter::setUniforms(), and setUniformValueArray().
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1) {
         if (tupleSize == 1)
             glUniform1fv(location, count, values);
         else if (tupleSize == 2)
             glUniform2fv(location, count, values);
         else if (tupleSize == 3)
             glUniform3fv(location, count, values);
         else if (tupleSize == 4)
             glUniform4fv(location, count, values);
         else
             qWarning() << "QGLShaderProgram::setUniformValue: size" << tupleSize << "not supported";
     }
 }
setUniformValueArray() [2/30]
void QGLShaderProgram::setUniformValueArray (int location, const GLint * values, int count)
Sets the uniform variable array at location in the current context to the count elements of values.
See also
setAttributeValue()
Definition at line 2800 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniform1iv(location, count, values);
 }
setUniformValueArray() [3/30]
void QGLShaderProgram::setUniformValueArray (int location, const GLuint * values, int count)
Sets the uniform variable array at location in the current context to the count elements of values.
This overload should be used when setting an array of sampler values.
See also
setAttributeValue()
Definition at line 2832 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniform1iv(location, count, reinterpret_cast<const GLint *>(values));
 }
setUniformValueArray() [4/30]
void QGLShaderProgram::setUniformValueArray (int location, const QVector2D * values, int count)
Sets the uniform variable array at location in the current context to the count 2D vector elements of values.
See also
setAttributeValue()
Definition at line 2907 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniform2fv(location, count, reinterpret_cast<const GLfloat *>(values));
 }
setUniformValueArray() [5/30]
void QGLShaderProgram::setUniformValueArray (int location, const QVector3D * values, int count)
Sets the uniform variable array at location in the current context to the count 3D vector elements of values.
See also
setAttributeValue()
Definition at line 2937 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniform3fv(location, count, reinterpret_cast<const GLfloat *>(values));
 }
setUniformValueArray() [6/30]
void QGLShaderProgram::setUniformValueArray (int location, const QVector4D * values, int count)
Sets the uniform variable array at location in the current context to the count 4D vector elements of values.
See also
setAttributeValue()
Definition at line 2967 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     if (location != -1)
         glUniform4fv(location, count, reinterpret_cast<const GLfloat *>(values));
 }
setUniformValueArray() [7/30]
void QGLShaderProgram::setUniformValueArray (int location, const QMatrix2x2 * values, int count)
Sets the uniform variable array at location in the current context to the count 2x2 matrix elements of values.
See also
setAttributeValue()
Definition at line 3058 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformMatrixArray
         (glUniformMatrix2fv, location, values, count, QMatrix2x2, 2, 2);
 }
setUniformValueArray() [8/30]
void QGLShaderProgram::setUniformValueArray (int location, const QMatrix2x3 * values, int count)
Sets the uniform variable array at location in the current context to the count 2x3 matrix elements of values.
See also
setAttributeValue()
Definition at line 3088 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrixArray
         (glUniformMatrix2x3fv, glUniform3fv, location, values, count,
          QMatrix2x3, 2, 3);
 }
setUniformValueArray() [9/30]
void QGLShaderProgram::setUniformValueArray (int location, const QMatrix2x4 * values, int count)
Sets the uniform variable array at location in the current context to the count 2x4 matrix elements of values.
See also
setAttributeValue()
Definition at line 3119 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrixArray
         (glUniformMatrix2x4fv, glUniform4fv, location, values, count,
          QMatrix2x4, 2, 4);
 }
setUniformValueArray() [10/30]
void QGLShaderProgram::setUniformValueArray (int location, const QMatrix3x2 * values, int count)
Sets the uniform variable array at location in the current context to the count 3x2 matrix elements of values.
See also
setAttributeValue()
Definition at line 3150 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrixArray
         (glUniformMatrix3x2fv, glUniform2fv, location, values, count,
          QMatrix3x2, 3, 2);
 }
setUniformValueArray() [11/30]
void QGLShaderProgram::setUniformValueArray (int location, const QMatrix3x3 * values, int count)
Sets the uniform variable array at location in the current context to the count 3x3 matrix elements of values.
See also
setAttributeValue()
Definition at line 3181 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformMatrixArray
         (glUniformMatrix3fv, location, values, count, QMatrix3x3, 3, 3);
 }
setUniformValueArray() [12/30]
void QGLShaderProgram::setUniformValueArray (int location, const QMatrix3x4 * values, int count)
Sets the uniform variable array at location in the current context to the count 3x4 matrix elements of values.
See also
setAttributeValue()
Definition at line 3211 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrixArray
         (glUniformMatrix3x4fv, glUniform4fv, location, values, count,
          QMatrix3x4, 3, 4);
 }
setUniformValueArray() [13/30]
void QGLShaderProgram::setUniformValueArray (int location, const QMatrix4x2 * values, int count)
Sets the uniform variable array at location in the current context to the count 4x2 matrix elements of values.
See also
setAttributeValue()
Definition at line 3242 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrixArray
         (glUniformMatrix4x2fv, glUniform2fv, location, values, count,
          QMatrix4x2, 4, 2);
 }
setUniformValueArray() [14/30]
void QGLShaderProgram::setUniformValueArray (int location, const QMatrix4x3 * values, int count)
Sets the uniform variable array at location in the current context to the count 4x3 matrix elements of values.
See also
setAttributeValue()
Definition at line 3273 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformGenericMatrixArray
         (glUniformMatrix4x3fv, glUniform3fv, location, values, count,
          QMatrix4x3, 4, 3);
 }
setUniformValueArray() [15/30]
void QGLShaderProgram::setUniformValueArray (int location, const QMatrix4x4 * values, int count)
Sets the uniform variable array at location in the current context to the count 4x4 matrix elements of values.
See also
setAttributeValue()
Definition at line 3304 of file qglshaderprogram.cpp.
 {
     Q_D(QGLShaderProgram);
     Q_UNUSED(d);
     setUniformMatrixArray
         (glUniformMatrix4fv, location, values, count, QMatrix4x4, 4, 4);
 }
setUniformValueArray() [16/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const GLfloat * values, int count, int tupleSize)
Sets the uniform variable array called name in the current context to the count elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Each element has tupleSize components. The tupleSize must be 1, 2, 3, or 4.
See also
setAttributeValue()
Definition at line 2896 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count, tupleSize);
 }
setUniformValueArray() [17/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const GLint * values, int count)
Sets the uniform variable array called name in the current context to the count elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2820 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [18/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const GLuint * values, int count)
Sets the uniform variable array called name in the current context to the count elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This overload should be used when setting an array of sampler values.
See also
setAttributeValue()
Definition at line 2853 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [19/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QVector2D * values, int count)
Sets the uniform variable array called name in the current context to the count 2D vector elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2926 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [20/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QVector3D * values, int count)
Sets the uniform variable array called name in the current context to the count 3D vector elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2956 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [21/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QVector4D * values, int count)
Sets the uniform variable array called name in the current context to the count 4D vector elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 2986 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [22/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QMatrix2x2 * values, int count)
Sets the uniform variable array called name in the current context to the count 2x2 matrix elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 3077 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [23/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QMatrix2x3 * values, int count)
Sets the uniform variable array called name in the current context to the count 2x3 matrix elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 3108 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [24/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QMatrix2x4 * values, int count)
Sets the uniform variable array called name in the current context to the count 2x4 matrix elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 3139 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [25/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QMatrix3x2 * values, int count)
Sets the uniform variable array called name in the current context to the count 3x2 matrix elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 3170 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [26/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QMatrix3x3 * values, int count)
Sets the uniform variable array called name in the current context to the count 3x3 matrix elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 3200 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [27/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QMatrix3x4 * values, int count)
Sets the uniform variable array called name in the current context to the count 3x4 matrix elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 3231 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [28/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QMatrix4x2 * values, int count)
Sets the uniform variable array called name in the current context to the count 4x2 matrix elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 3262 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [29/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QMatrix4x3 * values, int count)
Sets the uniform variable array called name in the current context to the count 4x3 matrix elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 3293 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
setUniformValueArray() [30/30]
void QGLShaderProgram::setUniformValueArray (const char * name, const QMatrix4x4 * values, int count)
Sets the uniform variable array called name in the current context to the count 4x4 matrix elements of values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setAttributeValue()
Definition at line 3323 of file qglshaderprogram.cpp.
 {
     setUniformValueArray(uniformLocation(name), values, count);
 }
shaderDestroyed
void QGLShaderProgram::shaderDestroyed () private slot
Warning
This function is not part of the public interface.
Definition at line 3456 of file qglshaderprogram.cpp.
Referenced by addShader(), and removeShader().
 {
     Q_D(QGLShaderProgram);
     QGLShader *shader = qobject_cast<QGLShader *>(sender());
     if (shader && !d->removingShaders)
         removeShader(shader);
 }
shaders()
QList< QGLShader * > QGLShaderProgram::shaders () const
Returns a list of all shaders that have been added to this shader program using addShader().
See also
addShader(), removeShader()
Definition at line 833 of file qglshaderprogram.cpp.
Referenced by QGLEngineSharedShaders::findProgramInCache().
 {
     Q_D(const QGLShaderProgram);
     return d->shaders;
 }
uniformLocation() [1/3]
int QGLShaderProgram::uniformLocation (const char * name) const
Returns the location of the uniform variable name within this shader program's parameter list.
Returns -1 if name is not a valid uniform variable for this shader program.
See also
attributeLocation()
Definition at line 1837 of file qglshaderprogram.cpp.
Referenced by QGLEngineSharedShaders::findProgramInCache(), QGLEngineShaderManager::getUniformLocation(), setUniformValue(), setUniformValueArray(), and uniformLocation().
 {
     Q_D(const QGLShaderProgram);
     Q_UNUSED(d);
     if (d->linked) {
         return glGetUniformLocation(d->programGuard.id(), name);
     } else {
         qWarning() << "QGLShaderProgram::uniformLocation(" << name
                    << "): shader program is not linked";
         return -1;
     }
 }
uniformLocation() [2/3]
int QGLShaderProgram::uniformLocation (const QByteArray & name) const
Returns the location of the uniform variable name within this shader program's parameter list.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns -1 if name is not a valid uniform variable for this shader program.
See also
attributeLocation()
Definition at line 1862 of file qglshaderprogram.cpp.
 {
     return uniformLocation(name.constData());
 }
uniformLocation() [3/3]
int QGLShaderProgram::uniformLocation (const QString & name) const
Returns the location of the uniform variable name within this shader program's parameter list.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns -1 if name is not a valid uniform variable for this shader program.
See also
attributeLocation()
Definition at line 1879 of file qglshaderprogram.cpp.
 {
     return uniformLocation(name.toLatin1().constData());
 }
The documentation for this class was generated from the following files:
/src/opengl/qglshaderprogram.h
/src/opengl/qglshaderprogram.cpp