Qt 4.8: QWaylandShmBuffer Class Reference
QWaylandShmBuffer Class Reference
#include <qwaylandshmsurface.h>
Public Functions
QImage * image ()
QWaylandShmBuffer (QWaylandDisplay *display, const QSize &size, QImage::Format format)
QSize size () const
~QWaylandShmBuffer ()
Public Functions inherited from QWaylandBuffer
wl_buffer * buffer ()
QWaylandBuffer ()
virtual ~QWaylandBuffer ()
Properties
QImage mImage
Additional Inherited Members
Protected Variables inherited from QWaylandBuffer
struct wl_buffer * mBuffer
Detailed Description
Definition at line 54 of file qwaylandshmsurface.h.
Constructors and Destructors
QWaylandShmBuffer()
QWaylandShmBuffer::QWaylandShmBuffer (QWaylandDisplay * display, const QSize & size, QImage::Format format)
Definition at line 58 of file qwaylandshmsurface.cpp.
 {
     int stride = size.width() * 4;
     int alloc = stride * size.height();
     char filename[] = "/tmp/wayland-shm-XXXXXX";
     int fd = mkstemp(filename);
     if (fd < 0)
     qWarning("open %s failed: %s", filename, strerror(errno));
     if (ftruncate(fd, alloc) < 0) {
     qWarning("ftruncate failed: %s", strerror(errno));
     close(fd);
     return;
     }
     uchar *data = (uchar *)
     mmap(NULL, alloc, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
     unlink(filename);
     if (data == (uchar *) MAP_FAILED) {
     qWarning("mmap /dev/zero failed: %s", strerror(errno));
     close(fd);
     return;
     }
     mImage = QImage(data, size.width(), size.height(), stride, format);
     mBuffer = display->createShmBuffer(fd, size.width(), size.height(),
                        stride, display->argbVisual());
     close(fd);
 }
~QWaylandShmBuffer()
QWaylandShmBuffer::~QWaylandShmBuffer (void)
Definition at line 88 of file qwaylandshmsurface.cpp.
 {
     munmap((void *) mImage.constBits(), mImage.byteCount());
     wl_buffer_destroy(mBuffer);
 }
Functions
image()
QImage* QWaylandShmBuffer::image () inline
Definition at line 60 of file qwaylandshmsurface.h.
Referenced by QWaylandCursor::changeCursor(), QWaylandShmWindowSurface::paintDevice(), QWaylandReadbackEglContext::swapBuffers(), and QWaylandReadbackGlxContext::swapBuffers().
 { return &mImage; }
size()
QSize QWaylandShmBuffer::size () const inline virtual
Implements QWaylandBuffer.
Definition at line 59 of file qwaylandshmsurface.h.
Referenced by QWaylandCursor::changeCursor(), and QWaylandShmWindowSurface::resize().
 { return mImage.size(); }
Properties
mImage
QImage QWaylandShmBuffer::mImage private
Definition at line 62 of file qwaylandshmsurface.h.
Referenced by image(), QWaylandShmBuffer(), size(), and ~QWaylandShmBuffer().
The documentation for this class was generated from the following files:
/src/plugins/platforms/wayland/qwaylandshmsurface.h
/src/plugins/platforms/wayland/qwaylandshmsurface.cpp