Qt 4.8: QmlJSDebugger::LiveSelectionRectangle Class Reference
QmlJSDebugger::LiveSelectionRectangle Class Reference
#include <liveselectionrectangle.h>
Public Functions
void clear ()
void hide ()
LiveSelectionRectangle (QGraphicsObject *layerItem)
QRectF rect () const
void setRect (const QPointF &firstPoint, const QPointF &secondPoint)
void show ()
~LiveSelectionRectangle ()
Properties
QGraphicsRectItem * m_controlShape
QWeakPointer< QGraphicsObject > m_layerItem
Detailed Description
Definition at line 54 of file liveselectionrectangle.h.
Constructors and Destructors
LiveSelectionRectangle()
QmlJSDebugger::LiveSelectionRectangle::LiveSelectionRectangle (QGraphicsObject * layerItem)
Definition at line 68 of file liveselectionrectangle.cpp.
     : m_controlShape(new SelectionRectShape(layerItem)),
       m_layerItem(layerItem)
 {
     m_controlShape->setPen(QPen(Qt::black));
     m_controlShape->setBrush(QColor(128, 128, 128, 50));
 }
~LiveSelectionRectangle()
QmlJSDebugger::LiveSelectionRectangle::~LiveSelectionRectangle ()
Definition at line 76 of file liveselectionrectangle.cpp.
 {
     if (m_layerItem)
         m_layerItem.data()->scene()->removeItem(m_controlShape);
 }
Functions
clear()
void QmlJSDebugger::LiveSelectionRectangle::clear (void)
Definition at line 82 of file liveselectionrectangle.cpp.
Referenced by QmlJSDebugger::LiveRubberBandSelectionManipulator::clear().
 {
     hide();
 }
hide()
void QmlJSDebugger::LiveSelectionRectangle::hide ()
Definition at line 91 of file liveselectionrectangle.cpp.
Referenced by clear(), QmlJSDebugger::LiveRubberBandSelectionManipulator::end(), and QmlJSDebugger::LiveRubberBandSelectionManipulator::LiveRubberBandSelectionManipulator().
 {
     m_controlShape->hide();
 }
rect()
QRectF QmlJSDebugger::LiveSelectionRectangle::rect () const
Definition at line 96 of file liveselectionrectangle.cpp.
Referenced by QmlJSDebugger::LiveRubberBandSelectionManipulator::select(), and setRect().
 {
     return m_controlShape->mapFromScene(m_controlShape->rect()).boundingRect();
 }
setRect()
void QmlJSDebugger::LiveSelectionRectangle::setRect (const QPointF & firstPoint, const QPointF & secondPoint)
Definition at line 101 of file liveselectionrectangle.cpp.
Referenced by QmlJSDebugger::LiveRubberBandSelectionManipulator::begin(), and QmlJSDebugger::LiveRubberBandSelectionManipulator::update().
 {
     double firstX = std::floor(firstPoint.x()) + 0.5;
     double firstY = std::floor(firstPoint.y()) + 0.5;
     double secondX = std::floor(secondPoint.x()) + 0.5;
     double secondY = std::floor(secondPoint.y()) + 0.5;
     QPointF topLeftPoint(firstX < secondX ? firstX : secondX,
                          firstY < secondY ? firstY : secondY);
     QPointF bottomRightPoint(firstX > secondX ? firstX : secondX,
                              firstY > secondY ? firstY : secondY);
     QRectF rect(topLeftPoint, bottomRightPoint);
     m_controlShape->setRect(rect);
 }
show()
void QmlJSDebugger::LiveSelectionRectangle::show ()
Definition at line 86 of file liveselectionrectangle.cpp.
Referenced by QmlJSDebugger::LiveRubberBandSelectionManipulator::begin().
 {
     m_controlShape->show();
 }
Properties
m_controlShape
QGraphicsRectItem* QmlJSDebugger::LiveSelectionRectangle::m_controlShape private
Definition at line 71 of file liveselectionrectangle.h.
Referenced by hide(), LiveSelectionRectangle(), rect(), setRect(), show(), and ~LiveSelectionRectangle().
m_layerItem
QWeakPointer<QGraphicsObject> QmlJSDebugger::LiveSelectionRectangle::m_layerItem private
Definition at line 72 of file liveselectionrectangle.h.
Referenced by ~LiveSelectionRectangle().
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_inspector/editor/liveselectionrectangle.h
/src/plugins/qmltooling/qmldbg_inspector/editor/liveselectionrectangle.cpp