Qt 4.8: QEglContextTracker Class Reference
QEglContextTracker Class Reference
Static Public Functions
static void deref ()
static bool displayOpened ()
static void ref ()
static void setDisplayOpened ()
Static Private Attributes
static QBasicAtomicInt contexts = Q_BASIC_ATOMIC_INITIALIZER(0)
static QBasicAtomicInt displayOpen = Q_BASIC_ATOMIC_INITIALIZER(0)
Detailed Description
Definition at line 64 of file qegl.cpp.
Functions
deref()
static void QEglContextTracker::deref () inline static
Definition at line 68 of file qegl.cpp.
Referenced by QEglContext::~QEglContext().
{
         if (!contexts.deref()) {
             eglTerminate(QEgl::display());
             displayOpen = 0;
         }
     }
displayOpened()
static bool QEglContextTracker::displayOpened () inline static
Definition at line 75 of file qegl.cpp.
Referenced by QEgl::display().
 { return displayOpen; }
ref()
static void QEglContextTracker::ref () inline static
Definition at line 67 of file qegl.cpp.
Referenced by QEglContext::QEglContext().
 { contexts.ref(); }
setDisplayOpened()
static void QEglContextTracker::setDisplayOpened () inline static
Definition at line 74 of file qegl.cpp.
Referenced by QEgl::display().
 { displayOpen = 1; }
Properties
contexts
QBasicAtomicInt QEglContextTracker::contexts = Q_BASIC_ATOMIC_INITIALIZER(0) static private
Definition at line 78 of file qegl.cpp.
Referenced by deref(), and ref().
displayOpen
QBasicAtomicInt QEglContextTracker::displayOpen = Q_BASIC_ATOMIC_INITIALIZER(0) static private
Definition at line 79 of file qegl.cpp.
Referenced by deref(), displayOpened(), and setDisplayOpened().
The documentation for this class was generated from the following file:
/src/gui/egl/qegl.cpp