Qt 4.8: QToolBarLayout Class Reference
QToolBarLayout Class Reference
#include <qtoolbarlayout_p.h>
Public Slots
void setExpanded (bool b)
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
void addItem (QLayoutItem *item)
Implemented in subclasses to add an item.
void checkUsePopupMenu ()
int count () const
Must be implemented in subclasses to return the number of items in the layout.
QSize expandedSize (const QSize &size) const
Qt::Orientations expandingDirections () const
Returns whether this layout can make use of more space than sizeHint().
bool hasExpandFlag () const
int indexOf (QAction *action) const
int indexOf (QWidget *widget) const
Searches for widget widget in this layout (not including child layouts).
void insertAction (int index, QAction *action)
void invalidate ()
Reimplemented Function
bool isEmpty () const
Reimplemented Function
QLayoutItem * itemAt (int index) const
Must be implemented in subclasses to return the layout item at index.
bool layoutActions (const QSize &size)
QSize minimumSize () const
Returns the minimum size of this layout.
bool movable () const
QToolBarLayout (QWidget *parent=0)
void setGeometry (const QRect &r)
Reimplemented Function
void setUsePopupMenu (bool set)
QSize sizeHint () const
Implemented in subclasses to return the preferred size of this item.
QLayoutItem * takeAt (int index)
Must be implemented in subclasses to remove the layout item at index from the layout, and return the item.
void updateMarginAndSpacing ()
~QToolBarLayout ()
Public Functions inherited from QLayout
bool activate ()
Redoes the layout for parentWidget() if necessary.
void addWidget (QWidget *w)
Adds widget w to this layout in a manner specific to the layout.
QMargins contentsMargins () const
Returns the margins used around the layout.
QRect contentsRect () const
Returns the layout's geometry() rectangle, but taking into account the contents margins.
QRect geometry () const
Reimplemented Function
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
bool isEnabled () const
Returns true if the layout is enabled; otherwise returns false.
QLayout * layout ()
Reimplemented Function
int margin () const
QSize maximumSize () const
Returns the maximum size of this layout.
QWidget * menuBar () const
Returns the menu bar set for this layout, or 0 if no menu bar is set.
QWidget * parentWidget () const
Returns the parent widget of this layout, or 0 if this layout is not installed on any widget.
QLayout (QWidget *parent)
Constructs a new top-level QLayout, with parent parent.
QLayout ()
Constructs a new child QLayout.
void removeItem (QLayoutItem *)
Removes the layout item item from the layout.
void removeWidget (QWidget *w)
Removes the widget widget from the layout.
bool setAlignment (QWidget *w, Qt::Alignment alignment)
Sets the alignment for widget w to alignment and returns true if w is found in this layout (not including child layouts); otherwise returns false.
bool setAlignment (QLayout *l, Qt::Alignment alignment)
Sets the alignment for the layout l to alignment and returns true if l is found in this layout (not including child layouts); otherwise returns false.
void setContentsMargins (int left, int top, int right, int bottom)
Sets the left, top, right, and bottom margins to use around the layout.
void setContentsMargins (const QMargins &margins)
Sets the margins to use around the layout.
void setEnabled (bool)
Enables this layout if enable is true, otherwise disables it.
void setMargin (int)
void setMenuBar (QWidget *w)
Tells the geometry manager to place the menu bar widget at the top of parentWidget(), outside QWidget::contentsMargins().
void setSizeConstraint (SizeConstraint)
void setSpacing (int)
SizeConstraint sizeConstraint () const
int spacing () const
int totalHeightForWidth (int w) const
Also takes contentsMargins and menu bar into account.
QSize totalMaximumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalMinimumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalSizeHint () const
Also takes contentsMargins and menu bar into account.
void update ()
Updates the layout for parentWidget().
~QLayout ()
Destroys the layout, deleting all child layouts.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QLayoutItem
Qt::Alignment alignment () const
Returns the alignment of this item.
QSizePolicy::ControlTypes controlTypes () const
Returns the control type(s) for the layout item.
virtual bool hasHeightForWidth () const
Returns true if this layout's preferred height depends on its width; otherwise returns false.
virtual int heightForWidth (int) const
Returns the preferred height for this layout item, given the width w.
virtual int minimumHeightForWidth (int) const
Returns the minimum height this widget needs for the given width, w.
QLayoutItem (Qt::Alignment alignment=0)
Constructs a layout item with an alignment.
void setAlignment (Qt::Alignment a)
Sets the alignment of this item to alignment.
virtual QSpacerItem * spacerItem ()
If this item is a QSpacerItem, it is returned as a QSpacerItem; otherwise 0 is returned.
virtual QWidget * widget ()
If this item is a QWidget, it is returned as a QWidget; otherwise 0 is returned.
virtual ~QLayoutItem ()
Destroys the QLayoutItem.
Public Variables
bool animating
bool expanded
Private Functions
QToolBarItem * createItem (QAction *action)
void updateGeomArray () const
Properties
bool dirty
bool empty
bool expandFlag
bool expanding
QToolBarExtension * extension
QVector< QLayoutStruct > geomArray
QRect handRect
QSize hint
QList< QToolBarItem * > items
QSize minSize
QMenu * popupMenu
Additional Inherited Members
Public Types inherited from QLayout
enum SizeConstraint {
SetDefaultConstraint, SetNoConstraint, SetMinimumSize, SetFixedSize,
SetMaximumSize, SetMinAndMaxSize
}
The possible values are:
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QLayout
static QSize closestAcceptableSize (const QWidget *w, const QSize &s)
Returns a size that satisfies all size constraints on widget, including heightForWidth() and that is as close as possible to size.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QLayout
void addChildLayout (QLayout *l)
This function is called from addLayout() or insertLayout() functions in subclasses to add layout l as a sub-layout.
void addChildWidget (QWidget *w)
This function is called from addWidget() functions in subclasses to add w as a managed widget of a layout.
bool adoptLayout (QLayout *layout)
QRect alignmentRect (const QRect &) const
Returns the rectangle that should be covered when the geometry of this layout is set to r, provided that this layout supports setAlignment().
void childEvent (QChildEvent *e)
Reimplemented Function
QLayout (QLayoutPrivate &d, QLayout *, QWidget *)
void widgetEvent (QEvent *)
Performs child widget layout when the parent widget is resized.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QLayoutItem
Qt::Alignment align
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 78 of file qtoolbarlayout_p.h.
Constructors and Destructors
QToolBarLayout()
QToolBarLayout::QToolBarLayout (QWidget * parent = 0)
Definition at line 81 of file qtoolbarlayout.cpp.
     : QLayout(parent), expanded(false), animating(false), dirty(true),
         expanding(false), empty(true), expandFlag(false), popupMenu(0)
 {
     QToolBar *tb = qobject_cast<QToolBar*>(parent);
     if (!tb)
         return;
     extension = new QToolBarExtension(tb);
     extension->setFocusPolicy(Qt::NoFocus);
     extension->hide();
     QObject::connect(tb, SIGNAL(orientationChanged(Qt::Orientation)),
                      extension, SLOT(setOrientation(Qt::Orientation)));
     setUsePopupMenu(qobject_cast<QMainWindow*>(tb->parentWidget()) == 0);
 }
~QToolBarLayout()
QToolBarLayout::~QToolBarLayout ()
Definition at line 98 of file qtoolbarlayout.cpp.
 {
     while (!items.isEmpty()) {
         QToolBarItem *item = items.takeFirst();
         if (QWidgetAction *widgetAction = qobject_cast<QWidgetAction*>(item->action)) {
             if (item->customWidget)
                 widgetAction->releaseWidget(item->widget());
         }
         delete item;
     }
 }
Functions
addItem()
void QToolBarLayout::addItem (QLayoutItem * item) virtual
Implemented in subclasses to add an item.
How it is added is specific to each subclass.
This function is not usually called in application code. To add a widget to a layout, use the addWidget() function; to add a child layout, use the addLayout() function provided by the relevant QLayout subclass.
Note: The ownership of item is transferred to the layout, and it's the layout's responsibility to delete it.
See also
addWidget(), QBoxLayout::addLayout(), QGridLayout::addLayout()
Implements QLayout.
Definition at line 158 of file qtoolbarlayout.cpp.
 {
     qWarning() << "QToolBarLayout::addItem(): please use addAction() instead";
     return;
 }
checkUsePopupMenu()
void QToolBarLayout::checkUsePopupMenu ()
Definition at line 150 of file qtoolbarlayout.cpp.
Referenced by QToolBarPrivate::setWindowState().
 {
     QToolBar *tb = static_cast<QToolBar *>(parent());
     QMainWindow *mw = qobject_cast<QMainWindow *>(tb->parent());
     Qt::Orientation o = tb->orientation();
     setUsePopupMenu(!mw || tb->isFloating() || perp(o, expandedSize(mw->size())) >= perp(o, mw->size()));
 }
count()
int QToolBarLayout::count () const virtual
Must be implemented in subclasses to return the number of items in the layout.
See also
itemAt()
Implements QLayout.
Definition at line 214 of file qtoolbarlayout.cpp.
Referenced by expandedSize(), layoutActions(), and updateGeomArray().
 {
     return items.count();
 }
createItem()
QToolBarItem * QToolBarLayout::createItem (QAction * action) private
Definition at line 693 of file qtoolbarlayout.cpp.
Referenced by insertAction().
 {
     bool customWidget = false;
     bool standardButtonWidget = false;
     QWidget *widget = 0;
     QToolBar *tb = qobject_cast<QToolBar*>(parentWidget());
     if (!tb)
         return (QToolBarItem *)0;
     if (QWidgetAction *widgetAction = qobject_cast<QWidgetAction *>(action)) {
         widget = widgetAction->requestWidget(tb);
         if (widget != 0) {
             widget->setAttribute(Qt::WA_LayoutUsesWidgetRect);
             customWidget = true;
         }
     } else if (action->isSeparator()) {
         QToolBarSeparator *sep = new QToolBarSeparator(tb);
         connect(tb, SIGNAL(orientationChanged(Qt::Orientation)),
                 sep, SLOT(setOrientation(Qt::Orientation)));
         widget = sep;
     }
     if (!widget) {
         QToolButton *button = new QToolButton(tb);
         button->setAutoRaise(true);
         button->setFocusPolicy(Qt::NoFocus);
         button->setIconSize(tb->iconSize());
         button->setToolButtonStyle(tb->toolButtonStyle());
         QObject::connect(tb, SIGNAL(iconSizeChanged(QSize)),
                          button, SLOT(setIconSize(QSize)));
         QObject::connect(tb, SIGNAL(toolButtonStyleChanged(Qt::ToolButtonStyle)),
                          button, SLOT(setToolButtonStyle(Qt::ToolButtonStyle)));
         button->setDefaultAction(action);
         QObject::connect(button, SIGNAL(triggered(QAction*)), tb, SIGNAL(actionTriggered(QAction*)));
         widget = button;
         standardButtonWidget = true;
     }
     widget->hide();
     QToolBarItem *result = new QToolBarItem(widget);
     if (standardButtonWidget)
         result->setAlignment(Qt::AlignJustify);
     result->customWidget = customWidget;
     result->action = action;
     return result;
 }
expandedSize()
QSize QToolBarLayout::expandedSize (const QSize & size) const
Definition at line 566 of file qtoolbarlayout.cpp.
Referenced by QToolBarAreaLayout::apply(), and checkUsePopupMenu().
 {
     if (dirty)
         updateGeomArray();
     QToolBar *tb = qobject_cast<QToolBar*>(parentWidget());
     if (!tb)
         return QSize(0, 0);
     QMainWindow *win = qobject_cast<QMainWindow*>(tb->parentWidget());
     Qt::Orientation o = tb->orientation();
     QStyle *style = tb->style();
     QStyleOptionToolBar opt;
     tb->initStyleOption(&opt);
     const int handleExtent = movable()
             ? style->pixelMetric(QStyle::PM_ToolBarHandleExtent, &opt, tb) : 0;
     const int margin = this->margin();
     const int spacing = this->spacing();
     const int extensionExtent = style->pixelMetric(QStyle::PM_ToolBarExtensionExtent, &opt, tb);
     int total_w = 0;
     int count = 0;
     for (int x = 0; x < items.count(); ++x) {
         if (!geomArray[x].empty) {
             total_w += (count == 0 ? 0 : spacing) + geomArray[x].minimumSize;
             ++count;
         }
     }
     if (count == 0)
         return QSize(0, 0);
     int min_w = pick(o, size);
     int rows = (int)qSqrt(qreal(count));
     if (rows == 1)
         ++rows;      // we want to expand to at least two rows
     int space = total_w/rows + spacing + extensionExtent;
     space = qMax(space, min_w - 2*margin - handleExtent);
     if (win != 0)
         space = qMin(space, pick(o, win->size()) - 2*margin - handleExtent);
     int w = 0;
     int h = 0;
     int i = 0;
     while (i < items.count()) {
         int count = 0;
         int size = 0;
         int prev = -1;
         int rowHeight = 0;
         for (; i < items.count(); ++i) {
             if (geomArray[i].empty)
                 continue;
             int newSize = size + (count == 0 ? 0 : spacing) + geomArray[i].minimumSize;
             rowHeight = qMax(rowHeight, perp(o, items.at(i)->sizeHint()));
             if (prev != -1 && newSize > space) {
                 if (count > 1 && size + spacing + extensionExtent > space) {
                     size -= spacing + geomArray[prev].minimumSize;
                     i = prev;
                 }
                 break;
             }
             size = newSize;
             prev = i;
             ++count;
         }
         w = qMax(size, w);
         h += rowHeight + spacing;
     }
     w += 2*margin + handleExtent + spacing + extensionExtent;
     w = qMax(w, min_w);
     if (win != 0)
         w = qMin(w, pick(o, win->size()));
     h += 2*margin - spacing; //there is no spacing before the first row
     QSize result;
     rpick(o, result) = w;
     rperp(o, result) = h;
     return result;
 }
expandingDirections()
Qt::Orientations QToolBarLayout::expandingDirections () const virtual
Returns whether this layout can make use of more space than sizeHint().
A value of Qt::Vertical or Qt::Horizontal means that it wants to grow in only one dimension, whereas Qt::Vertical | Qt::Horizontal means that it wants to grow in both dimensions.
The default implementation returns Qt::Horizontal | Qt::Vertical. Subclasses reimplement it to return a meaningful value based on their child widgets's size policies.
See also
sizeHint()
Reimplemented from QLayout.
Definition at line 232 of file qtoolbarlayout.cpp.
 {
     if (dirty)
         updateGeomArray();
     QToolBar *tb = qobject_cast<QToolBar*>(parentWidget());
     if (!tb)
         return Qt::Orientations(0);
     Qt::Orientation o = tb->orientation();
     return expanding ? Qt::Orientations(o) : Qt::Orientations(0);
 }
hasExpandFlag()
bool QToolBarLayout::hasExpandFlag () const
Definition at line 123 of file qtoolbarlayout.cpp.
Referenced by QMainWindowLayout::insertIntoMacToolbar().
 {
     return expandFlag;
 }
indexOf() [1/2]
int QToolBarLayout::indexOf (QAction * action) const
Definition at line 205 of file qtoolbarlayout.cpp.
 {
     for (int i = 0; i < items.count(); ++i) {
         if (items.at(i)->action == action)
             return i;
     }
     return -1;
 }
indexOf() [2/2]
int QToolBarLayout::indexOf (QWidget * widget) const inline virtual
Searches for widget widget in this layout (not including child layouts).
Returns the index of widget, or -1 if widget is not found.
The default implementation iterates over all items using itemAt()
Reimplemented from QLayout.
Definition at line 101 of file qtoolbarlayout_p.h.
 { return QLayout::indexOf(widget); }
insertAction()
void QToolBarLayout::insertAction (int index, QAction * action)
Definition at line 193 of file qtoolbarlayout.cpp.
 {
     index = qMax(0, index);
     index = qMin(items.count(), index);
     QToolBarItem *item = createItem(action);
     if (item) {
         items.insert(index, item);
         invalidate();
     }
 }
invalidate()
void QToolBarLayout::invalidate () virtual
Reimplemented Function
Reimplemented from QLayout.
Definition at line 226 of file qtoolbarlayout.cpp.
Referenced by insertAction(), setUsePopupMenu(), and takeAt().
 {
     dirty = true;
     QLayout::invalidate();
 }
isEmpty()
bool QToolBarLayout::isEmpty () const virtual
Reimplemented Function
Reimplemented from QLayout.
Definition at line 219 of file qtoolbarlayout.cpp.
 {
     if (dirty)
         updateGeomArray();
     return empty;
 }
itemAt()
QLayoutItem * QToolBarLayout::itemAt (int index) const virtual
Must be implemented in subclasses to return the layout item at index.
If there is no such item, the function must return 0. Items are numbered consecutively from 0. If an item is deleted, other items will be renumbered.
This function can be used to iterate over a layout. The following code will draw a rectangle for each layout item in the layout structure of the widget.
static void paintLayout(QPainter *painter, QLayoutItem *item)
{
    QLayout *layout = item->layout();
    if (layout) {
        for (int i = 0; i < layout->count(); ++i)
            paintLayout(painter, layout->itemAt(i));
    }
    painter->drawRect(item->geometry());
}
void MyWidget::paintEvent(QPaintEvent *)
{
    QPainter painter(this);
    if (layout())
        paintLayout(&painter, layout());
}
See also
count(), takeAt()
Implements QLayout.
Definition at line 164 of file qtoolbarlayout.cpp.
 {
     if (index < 0 || index >= items.count())
         return 0;
     return items.at(index);
 }
layoutActions()
bool QToolBarLayout::layoutActions (const QSize & size)
Definition at line 418 of file qtoolbarlayout.cpp.
Referenced by QMainWindowLayout::animationFinished(), setExpanded(), and setGeometry().
 {
     if (dirty)
         updateGeomArray();
     QRect rect(0, 0, size.width(), size.height());
     QList<QWidget*> showWidgets, hideWidgets;
     QToolBar *tb = qobject_cast<QToolBar*>(parentWidget());
     if (!tb)
         return false;
     QStyle *style = tb->style();
     QStyleOptionToolBar opt;
     tb->initStyleOption(&opt);
     const int handleExtent = movable()
             ? style->pixelMetric(QStyle::PM_ToolBarHandleExtent, &opt, tb) : 0;
     const int margin = this->margin();
     const int spacing = this->spacing();
     const int extensionExtent = style->pixelMetric(QStyle::PM_ToolBarExtensionExtent, &opt, tb);
     Qt::Orientation o = tb->orientation();
     bool extensionMenuContainsOnlyWidgetActions = true;
     int space = pick(o, rect.size()) - 2*margin - handleExtent;
     if (space <= 0)
         return false;  // nothing to do.
     if(popupMenu)
         popupMenu->clear();
     bool ranOutOfSpace = false;
     int rows = 0;
     int rowPos = perp(o, rect.topLeft()) + margin;
     int i = 0;
     while (i < items.count()) {
         QVector<QLayoutStruct> a = geomArray;
         int start = i;
         int size = 0;
         int prev = -1;
         int rowHeight = 0;
         int count = 0;
         int maximumSize = 0;
         bool expansiveRow = false;
         for (; i < items.count(); ++i) {
             if (a[i].empty)
                 continue;
             int newSize = size + (count == 0 ? 0 : spacing) + a[i].minimumSize;
             if (prev != -1 && newSize > space) {
                 if (rows == 0)
                     ranOutOfSpace = true;
                 // do we have to move the previous item to the next line to make space for
                 // the extension button?
                 if (count > 1 && size + spacing + extensionExtent > space)
                     i = prev;
                 break;
             }
             if (expanded)
                 rowHeight = qMax(rowHeight, perp(o, items.at(i)->sizeHint()));
             expansiveRow = expansiveRow || a[i].expansive;
             size = newSize;
             maximumSize += spacing + (a[i].expansive ? a[i].maximumSize : a[i].smartSizeHint());
             prev = i;
             ++count;
         }
         // stretch at the end
         a[i].sizeHint = 0;
         a[i].maximumSize = QWIDGETSIZE_MAX;
         a[i].minimumSize = 0;
         a[i].expansive = true;
         a[i].stretch = 0;
         a[i].empty = true;
         if (expansiveRow && maximumSize < space) {
             expansiveRow = false;
             a[i].maximumSize = space - maximumSize;
         }
         qGeomCalc(a, start, i - start + (expansiveRow ? 0 : 1), 0,
                     space - (ranOutOfSpace ? (extensionExtent + spacing) : 0),
                     spacing);
         for (int j = start; j < i; ++j) {
             QToolBarItem *item = items.at(j);
             if (a[j].empty) {
                 if (!item->widget()->isHidden())
                     hideWidgets << item->widget();
                 continue;
             }
             QPoint pos;
             rpick(o, pos) = margin + handleExtent + a[j].pos;
             rperp(o, pos) = rowPos;
             QSize size;
             rpick(o, size) = a[j].size;
             if (expanded)
                 rperp(o, size) = rowHeight;
             else
                 rperp(o, size) = perp(o, rect.size()) - 2*margin;
             QRect r(pos, size);
             if (o == Qt::Horizontal)
                 r = QStyle::visualRect(parentWidget()->layoutDirection(), rect, r);
             item->setGeometry(r);
             if (item->widget()->isHidden())
                 showWidgets << item->widget();
         }
         if (!expanded) {
             for (int j = i; j < items.count(); ++j) {
                 QToolBarItem *item = items.at(j);
                 if (!item->widget()->isHidden())
                     hideWidgets << item->widget();
                 if (popupMenu) {
                     if (!defaultWidgetAction(item)) {
                         popupMenu->addAction(item->action);
                         extensionMenuContainsOnlyWidgetActions = false;
                     }
                 }
             }
             break;
         }
         rowPos += rowHeight + spacing;
         ++rows;
     }
     // if we are using a popup menu, not the expadning toolbar effect, we cannot move custom
     // widgets into the menu. If only custom widget actions are chopped off, the popup menu
     // is empty. So we show the little extension button to show something is chopped off,
     // but we make it disabled.
     extension->setEnabled(popupMenu == 0 || !extensionMenuContainsOnlyWidgetActions);
     // we have to do the show/hide here, because it triggers more calls to setGeometry :(
     for (int i = 0; i < showWidgets.count(); ++i)
         showWidgets.at(i)->show();
     for (int i = 0; i < hideWidgets.count(); ++i)
         hideWidgets.at(i)->hide();
     return ranOutOfSpace;
 }
minimumSize()
QSize QToolBarLayout::minimumSize () const virtual
Returns the minimum size of this layout.
This is the smallest size that the layout can have while still respecting the specifications.
The returned value doesn't include the space required by QWidget::setContentsMargins() or menuBar().
The default implementation allows unlimited resizing.
Reimplemented from QLayout.
Definition at line 679 of file qtoolbarlayout.cpp.
Referenced by expandedSize(), and layoutActions().
 {
     if (dirty)
         updateGeomArray();
     return minSize;
 }
movable()
bool QToolBarLayout::movable () const
Definition at line 243 of file qtoolbarlayout.cpp.
Referenced by expandedSize(), layoutActions(), QToolBarPrivate::mousePressEvent(), and updateGeomArray().
 {
     QToolBar *tb = qobject_cast<QToolBar*>(parentWidget());
     if (!tb)
         return false;
     QMainWindow *win = qobject_cast<QMainWindow*>(tb->parentWidget());
     return tb->isMovable() && win != 0;
 }
setExpanded
void QToolBarLayout::setExpanded (bool b) slot
Definition at line 648 of file qtoolbarlayout.cpp.
Referenced by setUsePopupMenu(), and QToolBarPrivate::unplug().
 {
     QWidget *tb = qobject_cast<QToolBar*>(parentWidget());
     if (!tb)
         return;
     if (exp == expanded && !tb->isWindow())
         return;
     expanded = exp;
     extension->setChecked(expanded);
     if (QMainWindow *win = qobject_cast<QMainWindow*>(tb->parentWidget())) {
 #ifdef QT_NO_DOCKWIDGET
         animating = false;
 #else
         animating = !tb->isWindow() && win->isAnimated();
 #endif
         QMainWindowLayout *layout = qt_mainwindow_layout(win);
         if (expanded) {
             tb->raise();
         } else {
             QList<int> path = layout->layoutState.indexOf(tb);
             if (!path.isEmpty()) {
                 QRect rect = layout->layoutState.itemRect(path);
                 layoutActions(rect.size());
             }
         }
         layout->layoutState.toolBarAreaLayout.apply(animating);
     }
 }
setGeometry()
void QToolBarLayout::setGeometry (const QRect & r) virtual
Reimplemented Function
Reimplemented from QLayout.
Definition at line 358 of file qtoolbarlayout.cpp.
 {
     QToolBar *tb = qobject_cast<QToolBar*>(parentWidget());
     if (!tb)
         return;
     QStyle *style = tb->style();
     QStyleOptionToolBar opt;
     tb->initStyleOption(&opt);
     const int margin = this->margin();
     const int extensionExtent = style->pixelMetric(QStyle::PM_ToolBarExtensionExtent, &opt, tb);
     Qt::Orientation o = tb->orientation();
     QLayout::setGeometry(rect);
     bool ranOutOfSpace = false;
     if (!animating)
         ranOutOfSpace = layoutActions(rect.size());
     if (expanded || animating || ranOutOfSpace) {
         Qt::ToolBarArea area = Qt::TopToolBarArea;
         if (QMainWindow *win = qobject_cast<QMainWindow*>(tb->parentWidget()))
             area = win->toolBarArea(tb);
         QSize hint = sizeHint();
         QPoint pos;
         rpick(o, pos) = pick(o, rect.bottomRight()) - margin - extensionExtent + 2;
         if (area == Qt::LeftToolBarArea || area == Qt::TopToolBarArea)
             rperp(o, pos) = perp(o, rect.topLeft()) + margin;
         else
             rperp(o, pos) = perp(o, rect.bottomRight()) - margin - (perp(o, hint) - 2*margin) + 1;
         QSize size;
         rpick(o, size) = extensionExtent;
         rperp(o, size) = perp(o, hint) - 2*margin;
         QRect r(pos, size);
         if (o == Qt::Horizontal)
             r = QStyle::visualRect(parentWidget()->layoutDirection(), rect, r);
         extension->setGeometry(r);
         if (extension->isHidden())
             extension->show();
     } else {
         if (!extension->isHidden())
             extension->hide();
     }
 #ifdef Q_WS_MAC
     // Nothing to do for Carbon... probably
 #  ifdef QT_MAC_USE_COCOA
     if (QMainWindow *win = qobject_cast<QMainWindow*>(tb->parentWidget())) {
         Qt::ToolBarArea area = win->toolBarArea(tb);
         if (win->unifiedTitleAndToolBarOnMac() && area == Qt::TopToolBarArea) {
             qt_mainwindow_layout(win)->fixSizeInUnifiedToolbar(tb);
         }
     }
 #  endif
 #endif
 }
setUsePopupMenu()
void QToolBarLayout::setUsePopupMenu (bool set)
Definition at line 128 of file qtoolbarlayout.cpp.
Referenced by checkUsePopupMenu(), QMainWindowLayout::insertIntoMacToolbar(), and QToolBarLayout().
 {
     if (!dirty && ((popupMenu == 0) == set))
         invalidate();
     if (!set) {
         QObject::connect(extension, SIGNAL(clicked(bool)),
                         this, SLOT(setExpanded(bool)), Qt::UniqueConnection);
         extension->setPopupMode(QToolButton::DelayedPopup);
         extension->setMenu(0);
         delete popupMenu;
         popupMenu = 0;
     } else {
         QObject::disconnect(extension, SIGNAL(clicked(bool)),
                             this, SLOT(setExpanded(bool)));
         extension->setPopupMode(QToolButton::InstantPopup);
         if (!popupMenu) {
             popupMenu = new QMenu(extension);
         }
         extension->setMenu(popupMenu);
     }
 }
sizeHint()
QSize QToolBarLayout::sizeHint () const virtual
Implemented in subclasses to return the preferred size of this item.
Implements QLayoutItem.
Definition at line 686 of file qtoolbarlayout.cpp.
Referenced by setGeometry().
 {
     if (dirty)
         updateGeomArray();
     return hint;
 }
takeAt()
QLayoutItem * QToolBarLayout::takeAt (int index) virtual
Must be implemented in subclasses to remove the layout item at index from the layout, and return the item.
If there is no such item, the function must do nothing and return 0. Items are numbered consecutively from 0. If an item is removed, other items will be renumbered.
The following code fragment shows a safe way to remove all items from a layout:
QLayoutItem *child;
while ((child = layout->takeAt(0)) != 0) {
    ...
    delete child;
}
See also
itemAt(), count()
Implements QLayout.
Definition at line 171 of file qtoolbarlayout.cpp.
 {
     if (index < 0 || index >= items.count())
         return 0;
     QToolBarItem *item = items.takeAt(index);
     if (popupMenu)
         popupMenu->removeAction(item->action);
     QWidgetAction *widgetAction = qobject_cast<QWidgetAction*>(item->action);
     if (widgetAction != 0 && item->customWidget) {
         widgetAction->releaseWidget(item->widget());
     } else {
         // destroy the QToolButton/QToolBarSeparator
         item->widget()->hide();
         item->widget()->deleteLater();
     }
     invalidate();
     return item;
 }
updateGeomArray()
void QToolBarLayout::updateGeomArray () const private
Definition at line 252 of file qtoolbarlayout.cpp.
Referenced by expandedSize(), expandingDirections(), isEmpty(), layoutActions(), minimumSize(), and sizeHint().
 {
     if (!dirty)
         return;
     QToolBarLayout *that = const_cast<QToolBarLayout*>(this);
     QToolBar *tb = qobject_cast<QToolBar*>(parentWidget());
     if (!tb)
         return;
     QStyle *style = tb->style();
     QStyleOptionToolBar opt;
     tb->initStyleOption(&opt);
     const int handleExtent = movable()
             ? style->pixelMetric(QStyle::PM_ToolBarHandleExtent, &opt, tb) : 0;
     const int margin = this->margin();
     const int spacing = this->spacing();
     const int extensionExtent = style->pixelMetric(QStyle::PM_ToolBarExtensionExtent, &opt, tb);
     Qt::Orientation o = tb->orientation();
     that->minSize = QSize(0, 0);
     that->hint = QSize(0, 0);
     rperp(o, that->minSize) = style->pixelMetric(QStyle::PM_ToolBarHandleExtent, &opt, tb);
     rperp(o, that->hint) = style->pixelMetric(QStyle::PM_ToolBarHandleExtent, &opt, tb);
     that->expanding = false;
     that->empty = false;
     QVector<QLayoutStruct> a(items.count() + 1); // + 1 for the stretch
     int count = 0;
     for (int i = 0; i < items.count(); ++i) {
         QToolBarItem *item = items.at(i);
         QSize max = item->maximumSize();
         QSize min = item->minimumSize();
         QSize hint = item->sizeHint();
         Qt::Orientations exp = item->expandingDirections();
         bool empty = item->isEmpty();
         that->expanding = expanding || exp & o;
         if (item->widget()) {
             if ((item->widget()->sizePolicy().horizontalPolicy() & QSizePolicy::ExpandFlag)) {
                 that->expandFlag = true;
             }
         }
         if (!empty) {
             if (count == 0) // the minimum size only displays one widget
                 rpick(o, that->minSize) += pick(o, min);
             int s = perp(o, minSize);
             rperp(o, that->minSize) = qMax(s, perp(o, min));
             //we only add spacing before item (ie never before the first one)
             rpick(o, that->hint) += (count == 0 ? 0 : spacing) + pick(o, hint);
             s = perp(o, that->hint);
             rperp(o, that->hint) = qMax(s, perp(o, hint));
             ++count;
         }
         a[i].sizeHint = pick(o, hint);
         a[i].maximumSize = pick(o, max);
         a[i].minimumSize = pick(o, min);
         a[i].expansive = exp & o;
         if (o == Qt::Horizontal)
             a[i].stretch = item->widget()->sizePolicy().horizontalStretch();
         else
             a[i].stretch = item->widget()->sizePolicy().verticalStretch();
         a[i].empty = empty;
     }
     that->geomArray = a;
     that->empty = count == 0;
     rpick(o, that->minSize) += handleExtent;
     that->minSize += QSize(2*margin, 2*margin);
     if (items.count() > 1)
         rpick(o, that->minSize) += spacing + extensionExtent;
     rpick(o, that->hint) += handleExtent;
     that->hint += QSize(2*margin, 2*margin);
     that->dirty = false;
 #ifdef Q_WS_MAC
     if (QMainWindow *mw = qobject_cast<QMainWindow *>(parentWidget()->parentWidget())) {
         if (mw->unifiedTitleAndToolBarOnMac()
                 && mw->toolBarArea(static_cast<QToolBar *>(parentWidget())) == Qt::TopToolBarArea) {
             if (expandFlag) {
                 tb->setMaximumSize(0xFFFFFF, 0xFFFFFF);
             } else {
                tb->setMaximumSize(hint);
             }
         }
     }
 #endif
     that->dirty = false;
 }
updateMarginAndSpacing()
void QToolBarLayout::updateMarginAndSpacing ()
Definition at line 110 of file qtoolbarlayout.cpp.
Referenced by QToolBarPrivate::init().
 {
     QToolBar *tb = qobject_cast<QToolBar*>(parentWidget());
     if (!tb)
         return;
     QStyle *style = tb->style();
     QStyleOptionToolBar opt;
     tb->initStyleOption(&opt);
     setMargin(style->pixelMetric(QStyle::PM_ToolBarItemMargin, &opt, tb)
                 + style->pixelMetric(QStyle::PM_ToolBarFrameWidth, &opt, tb));
     setSpacing(style->pixelMetric(QStyle::PM_ToolBarItemSpacing, &opt, tb));
 }
Properties
animating
bool QToolBarLayout::animating
Definition at line 105 of file qtoolbarlayout_p.h.
Referenced by QMainWindowLayout::animationFinished(), setExpanded(), and setGeometry().
dirty
bool QToolBarLayout::dirty private
Definition at line 120 of file qtoolbarlayout_p.h.
Referenced by expandedSize(), expandingDirections(), invalidate(), isEmpty(), layoutActions(), minimumSize(), setUsePopupMenu(), sizeHint(), and updateGeomArray().
empty
bool QToolBarLayout::empty private
Definition at line 120 of file qtoolbarlayout_p.h.
Referenced by expandedSize(), isEmpty(), layoutActions(), and updateGeomArray().
expanded
bool QToolBarLayout::expanded
Definition at line 105 of file qtoolbarlayout_p.h.
Referenced by QMainWindowLayout::animationFinished(), QToolBarAreaLayout::apply(), layoutActions(), setExpanded(), and setGeometry().
expandFlag
bool QToolBarLayout::expandFlag private
Definition at line 120 of file qtoolbarlayout_p.h.
Referenced by hasExpandFlag(), and updateGeomArray().
expanding
bool QToolBarLayout::expanding private
Definition at line 120 of file qtoolbarlayout_p.h.
Referenced by expandingDirections(), and updateGeomArray().
extension
QToolBarExtension* QToolBarLayout::extension private
Definition at line 123 of file qtoolbarlayout_p.h.
Referenced by layoutActions(), QToolBarLayout(), setExpanded(), setGeometry(), and setUsePopupMenu().
geomArray
QVector<QLayoutStruct> QToolBarLayout::geomArray private
Definition at line 121 of file qtoolbarlayout_p.h.
Referenced by expandedSize(), layoutActions(), and updateGeomArray().
handRect
QRect QToolBarLayout::handRect private
Definition at line 122 of file qtoolbarlayout_p.h.
hint
QSize QToolBarLayout::hint private
Definition at line 119 of file qtoolbarlayout_p.h.
Referenced by setGeometry(), sizeHint(), and updateGeomArray().
items
QList<QToolBarItem*> QToolBarLayout::items private
Definition at line 118 of file qtoolbarlayout_p.h.
Referenced by count(), expandedSize(), indexOf(), insertAction(), itemAt(), layoutActions(), takeAt(), updateGeomArray(), and ~QToolBarLayout().
minSize
QSize QToolBarLayout::minSize private
Definition at line 119 of file qtoolbarlayout_p.h.
Referenced by minimumSize(), and updateGeomArray().
popupMenu
QMenu* QToolBarLayout::popupMenu private
Definition at line 127 of file qtoolbarlayout_p.h.
Referenced by layoutActions(), setUsePopupMenu(), and takeAt().
The documentation for this class was generated from the following files:
/src/gui/widgets/qtoolbarlayout_p.h
/src/gui/widgets/qtoolbarlayout.cpp