Qt 4.8: QDomNodeList Class Reference
QDomNodeList Class Reference
The QDomNodeList class is a list of QDomNode objects.
#include <qdom.h>
Public Functions
QDomNode at (int index) const
This function is provided for Qt API consistency.
int count () const
This function is provided for Qt API consistency.
bool isEmpty () const
Returns true if the list contains no items; otherwise returns false.
QDomNode item (int index) const
Returns the node at position index.
uint length () const
Returns the number of nodes in the list.
bool operator!= (const QDomNodeList &) const
Returns true the node list n and this node list are not equal; otherwise returns false.
QDomNodeList & operator= (const QDomNodeList &)
Assigns n to this node list.
bool operator== (const QDomNodeList &) const
Returns true if the node list n and this node list are equal; otherwise returns false.
QDomNodeList ()
Creates an empty node list.
QDomNodeList (const QDomNodeList &)
Constructs a copy of n.
int size () const
This function is provided for Qt API consistency.
~QDomNodeList ()
Destroys the object and frees its resources.
Private Functions
QDomNodeList (QDomNodeListPrivate *)
Properties
QDomNodeListPrivate * impl
Friends
class QDomDocument
class QDomElement
class QDomNode
Detailed Description
The QDomNodeList class is a list of QDomNode objects.
Note
This class or function is reentrant.
Attention
Module: QtXml
Lists can be obtained by QDomDocument::elementsByTagName() and QDomNode::childNodes(). The Document Object Model (DOM) requires these lists to be "live": whenever you change the underlying document, the contents of the list will get updated.
You can get a particular node from the list with item(). The number of items in the list is returned by length().
For further information about the Document Object Model see Level 1 and Level 2 Core. For a more general introduction of the DOM implementation see the QDomDocument documentation.
See also
QDomNode::childNodes() QDomDocument::elementsByTagName()
Definition at line 253 of file qdom.h.
Constructors and Destructors
QDomNodeList() [1/3]
QDomNodeList::QDomNodeList ()
Creates an empty node list.
Definition at line 1337 of file qdom.cpp.
 {
     impl = 0;
 }
QDomNodeList() [2/3]
QDomNodeList::QDomNodeList (const QDomNodeList & n)
Constructs a copy of n.
Definition at line 1350 of file qdom.cpp.
 {
     impl = n.impl;
     if (impl)
         impl->ref.ref();
 }
~QDomNodeList()
QDomNodeList::~QDomNodeList ()
Destroys the object and frees its resources.
Definition at line 1395 of file qdom.cpp.
 {
     if (impl && !impl->ref.deref())
         delete impl;
 }
QDomNodeList() [3/3]
QDomNodeList::QDomNodeList (QDomNodeListPrivate * p) private
Definition at line 1342 of file qdom.cpp.
 {
     impl = p;
 }
Functions
at()
QDomNode QDomNodeList::at (int index) const inline
This function is provided for Qt API consistency.
It is equivalent to item().
If index is negative or if index >= length() then a null node is returned (i.e. a node for which QDomNode::isNull() returns true).
Definition at line 265 of file qdom.h.
 { return item(index); } // Qt API consistency
count()
int QDomNodeList::count () const inline
This function is provided for Qt API consistency.
It is equivalent to length().
Definition at line 269 of file qdom.h.
Referenced by QDBusXmlParser::interfaces(), QDBusXmlParser::object(), QDBusXmlParser::objectTree(), parseAnnotations(), and parseArgs().
 { return length(); } // Qt API consitancy
isEmpty()
bool QDomNodeList::isEmpty () const inline
Returns true if the list contains no items; otherwise returns false.
This function is provided for Qt API consistency.
Definition at line 271 of file qdom.h.
 { return length() == 0; } // Qt API consistency
item()
QDomNode QDomNodeList::item (int index) const
Returns the node at position index.
If index is negative or if index >= length() then a null node is returned (i.e. a node for which QDomNode::isNull() returns true).
See also
length()
Definition at line 1410 of file qdom.cpp.
Referenced by QDBusXmlParser::interfaces(), QDBusXmlParser::object(), QDBusXmlParser::objectTree(), parseAnnotations(), and parseArgs().
 {
     if (!impl)
         return QDomNode();
     return QDomNode(impl->item(index));
 }
length()
uint QDomNodeList::length () const
Returns the number of nodes in the list.
Definition at line 1421 of file qdom.cpp.
 {
     if (!impl)
         return 0;
     return impl->length();
 }
operator!=()
bool QDomNodeList::operator!= (const QDomNodeList & n) const
Returns true the node list n and this node list are not equal; otherwise returns false.
Definition at line 1387 of file qdom.cpp.
 {
     return !operator==(n);
 }
operator=()
QDomNodeList & QDomNodeList::operator= (const QDomNodeList & n)
Assigns n to this node list.
Definition at line 1360 of file qdom.cpp.
 {
     if (n.impl)
         n.impl->ref.ref();
     if (impl && !impl->ref.deref())
         delete impl;
     impl = n.impl;
     return *this;
 }
operator==()
bool QDomNodeList::operator== (const QDomNodeList & n) const
Returns true if the node list n and this node list are equal; otherwise returns false.
Definition at line 1374 of file qdom.cpp.
 {
     if (impl == n.impl)
         return true;
     if (!impl || !n.impl)
         return false;
     return (*impl == *n.impl);
 }
size()
int QDomNodeList::size () const inline
This function is provided for Qt API consistency.
It is equivalent to length().
Definition at line 270 of file qdom.h.
 { return length(); } // Qt API consistency
Friends and Related Functions
QDomDocument
friend class QDomDocument friend
Definition at line 279 of file qdom.h.
QDomElement
friend class QDomElement friend
Definition at line 278 of file qdom.h.
QDomNode
friend class QDomNode friend
Definition at line 277 of file qdom.h.
Properties
impl
QDomNodeListPrivate* QDomNodeList::impl private
Definition at line 274 of file qdom.h.
Referenced by operator=(), operator==(), and QDomNodeList().
The documentation for this class was generated from the following files:
/src/xml/dom/qdom.h
/src/xml/dom/qdom.cpp