Qt 4.8: QDeclarativeBoundSignal Class Reference
QDeclarativeBoundSignal Class Reference
#include <qdeclarativeboundsignal_p.h>
Classes
class ScopeGuard
Public Functions
void disconnect ()
QDeclarativeExpression * expression () const
Returns the signal expression.
int index () const
bool isEvaluating () const
QDeclarativeBoundSignal (QObject *scope, const QMetaMethod &signal, QObject *parent)
QDeclarativeBoundSignal (QDeclarativeContext *ctxt, const QString &val, QObject *scope, const QMetaMethod &signal, QObject *parent)
QDeclarativeExpression * setExpression (QDeclarativeExpression *)
Sets the signal expression to e.
virtual ~QDeclarativeBoundSignal ()
Public Functions inherited from QDeclarativeAbstractBoundSignal
QDeclarativeAbstractBoundSignal (QObject *parent=0)
virtual ~QDeclarativeAbstractBoundSignal ()=0
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QDeclarativeBoundSignal * cast (QObject *)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
virtual int qt_metacall (QMetaObject::Call c, int id, void **a)
void unregisterScopeObject ()
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void init (QObject *parent)
Properties
QDeclarativeExpression * m_expression
bool m_isEvaluating: 1
QDeclarativeBoundSignalParameters * m_params
bool m_paramsValid: 1
ScopeGuard m_scope
QMetaMethod m_signal
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QDeclarativeAbstractBoundSignal
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 78 of file qdeclarativeboundsignal_p.h.
Constructors and Destructors
QDeclarativeBoundSignal() [1/2]
QDeclarativeBoundSignal::QDeclarativeBoundSignal (QObject * scope, const QMetaMethod & signal, QObject * parent)
Definition at line 98 of file qdeclarativeboundsignal.cpp.
 : m_expression(0), m_signal(signal), m_paramsValid(false), m_isEvaluating(false), m_params(0),
   m_scope(scope, this)
 {
     init(parent);
 }
QDeclarativeBoundSignal() [2/2]
QDeclarativeBoundSignal::QDeclarativeBoundSignal (QDeclarativeContext * ctxt, const QString & val, QObject * scope, const QMetaMethod & signal, QObject * parent)
Definition at line 106 of file qdeclarativeboundsignal.cpp.
 : m_expression(0), m_signal(signal), m_paramsValid(false), m_isEvaluating(false), m_params(0),
   m_scope(scope, this)
 {
     init(parent);
     m_expression = new QDeclarativeExpression(ctxt, scope, val);
 }
~QDeclarativeBoundSignal()
QDeclarativeBoundSignal::~QDeclarativeBoundSignal () virtual
Definition at line 130 of file qdeclarativeboundsignal.cpp.
 {
     unregisterScopeObject();
     delete m_expression;
     m_expression = 0;
 }
Functions
cast()
QDeclarativeBoundSignal * QDeclarativeBoundSignal::cast (QObject * o) static
Definition at line 174 of file qdeclarativeboundsignal.cpp.
Referenced by QDeclarativeEngineDebugService::buildObjectDump(), QDeclarativePropertyPrivate::setSignalExpression(), and QDeclarativePropertyPrivate::signalExpression().
 {
     QDeclarativeAbstractBoundSignal *s = qobject_cast<QDeclarativeAbstractBoundSignal*>(o);
     return static_cast<QDeclarativeBoundSignal *>(s);
 }
disconnect()
void QDeclarativeBoundSignal::disconnect () virtual
Implements QDeclarativeAbstractBoundSignal.
Definition at line 137 of file qdeclarativeboundsignal.cpp.
 {
     QMetaObject::disconnect(m_scope, m_signal.methodIndex(), this, evaluateIdx);
     QObjectPrivate * const priv = QObjectPrivate::get(m_scope);
     QVarLengthArray<char> signalSignature;
     QObjectPrivate::signalSignature(m_signal, &signalSignature);
     priv->disconnectNotify(signalSignature.constData());
 }
expression()
QDeclarativeExpression * QDeclarativeBoundSignal::expression () const
Returns the signal expression.
Definition at line 154 of file qdeclarativeboundsignal.cpp.
Referenced by QDeclarativeEngineDebugService::buildObjectDump(), and QDeclarativePropertyPrivate::signalExpression().
 {
     return m_expression;
 }
index()
int QDeclarativeBoundSignal::index () const
Definition at line 146 of file qdeclarativeboundsignal.cpp.
Referenced by QDeclarativeEngineDebugService::buildObjectDump(), QDeclarativePropertyPrivate::setSignalExpression(), and QDeclarativePropertyPrivate::signalExpression().
 {
     return m_signal.methodIndex();
 }
init()
void QDeclarativeBoundSignal::init (QObject * parent) private
Definition at line 116 of file qdeclarativeboundsignal.cpp.
Referenced by QDeclarativeBoundSignal().
 {
     // This is thread safe.  Although it may be updated by two threads, they
     // will both set it to the same value - so the worst thing that can happen
     // is that they both do the work to figure it out.  Boo hoo.
     if (evaluateIdx == -1) evaluateIdx = metaObject()->methodCount();
     QDeclarative_setParent_noEvent(this, parent);
     QDeclarativePropertyPrivate::connect(m_scope, m_signal.methodIndex(), this, evaluateIdx);
     QDeclarativeData * const data = QDeclarativeData::get(m_scope, true);
     data->addBoundSignal(this);
 }
isEvaluating()
bool QDeclarativeBoundSignal::isEvaluating () const inline
Definition at line 93 of file qdeclarativeboundsignal_p.h.
Referenced by QDeclarativeConnections::setTarget().
 { return m_isEvaluating; }
qt_metacall()
int QDeclarativeBoundSignal::qt_metacall (QMetaObject::Call c, int id, void ** a) protected virtual
Definition at line 180 of file qdeclarativeboundsignal.cpp.
 {
     if (c == QMetaObject::InvokeMetaMethod && id == evaluateIdx) {
         if (!m_expression)
             return -1;
         if (QDeclarativeDebugService::isDebuggingEnabled()) {
             QDeclarativeDebugTrace::startRange(QDeclarativeDebugTrace::HandlingSignal);
             QDeclarativeDebugTrace::rangeData(QDeclarativeDebugTrace::HandlingSignal, QLatin1String(m_signal.signature()) % QLatin1String(": ") % m_expression->expression());
             QDeclarativeDebugTrace::rangeLocation(QDeclarativeDebugTrace::HandlingSignal, m_expression->sourceFile(), m_expression->lineNumber());
         }
         m_isEvaluating = true;
         if (!m_paramsValid) {
             if (!m_signal.parameterTypes().isEmpty())
                 m_params = new QDeclarativeBoundSignalParameters(m_signal, this);
             m_paramsValid = true;
         }
         if (m_params) m_params->setValues(a);
         if (m_expression && m_expression->engine()) {
             QDeclarativeExpressionPrivate::get(m_expression)->value(m_params);
             if (m_expression && m_expression->hasError())
                 QDeclarativeEnginePrivate::warning(m_expression->engine(), m_expression->error());
         }
         if (m_params) m_params->clearValues();
         m_isEvaluating = false;
         QDeclarativeDebugTrace::endRange(QDeclarativeDebugTrace::HandlingSignal);
         return -1;
     } else {
         return QObject::qt_metacall(c, id, a);
     }
 }
setExpression()
QDeclarativeExpression * QDeclarativeBoundSignal::setExpression (QDeclarativeExpression * e)
Sets the signal expression to e.
Returns the current signal expression, or null if there is no signal expression.
The QDeclarativeBoundSignal instance takes ownership of e. The caller is assumes ownership of the returned QDeclarativeExpression.
Definition at line 166 of file qdeclarativeboundsignal.cpp.
Referenced by QDeclarativeConnections::connectSignals(), and QDeclarativePropertyPrivate::setSignalExpression().
 {
     QDeclarativeExpression *rv = m_expression;
     m_expression = e;
     if (m_expression) m_expression->setNotifyOnValueChanged(false);
     return rv;
 }
unregisterScopeObject()
void QDeclarativeBoundSignal::unregisterScopeObject () protected virtual
Implements QDeclarativeAbstractBoundSignal.
Definition at line 212 of file qdeclarativeboundsignal.cpp.
Referenced by ~QDeclarativeBoundSignal().
 {
     if (m_scope) {
         QDeclarativeData * const data = QDeclarativeData::get(m_scope, false);
         if (data)
             data->removeBoundSignal(this);
     }
 }
Properties
m_expression
QDeclarativeExpression* QDeclarativeBoundSignal::m_expression private
Definition at line 121 of file qdeclarativeboundsignal_p.h.
Referenced by expression(), QDeclarativeBoundSignal(), qt_metacall(), setExpression(), and ~QDeclarativeBoundSignal().
m_isEvaluating
bool QDeclarativeBoundSignal::m_isEvaluating private
Definition at line 124 of file qdeclarativeboundsignal_p.h.
Referenced by qt_metacall().
m_params
QDeclarativeBoundSignalParameters* QDeclarativeBoundSignal::m_params private
Definition at line 125 of file qdeclarativeboundsignal_p.h.
Referenced by qt_metacall().
m_paramsValid
bool QDeclarativeBoundSignal::m_paramsValid private
Definition at line 123 of file qdeclarativeboundsignal_p.h.
Referenced by qt_metacall().
m_scope
ScopeGuard QDeclarativeBoundSignal::m_scope private
Definition at line 126 of file qdeclarativeboundsignal_p.h.
Referenced by disconnect(), init(), and unregisterScopeObject().
m_signal
QMetaMethod QDeclarativeBoundSignal::m_signal private
Definition at line 122 of file qdeclarativeboundsignal_p.h.
Referenced by disconnect(), index(), init(), and qt_metacall().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeboundsignal_p.h
/src/declarative/qml/qdeclarativeboundsignal.cpp