Qt 4.8: QPixmap Class Reference
QPixmap Class Reference
The QPixmap class is an off-screen image representation that can be used as a paint device.
#include <qpixmap.h>
Public Types
typedef QExplicitlySharedDataPointer< QPixmapData > DataPtr
enum HBitmapFormat { NoAlpha, PremultipliedAlpha, Alpha }
HBITMAP and QPixmap is performed.
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Functions
QT_DEPRECATED QPixmap alphaChannel () const
Returns the alpha channel of the pixmap as a new grayscale QPixmap in which each pixel's red, green, and blue values are given the alpha value of the original pixmap.
qint64 cacheKey () const
Returns a number that identifies this QPixmap.
QRgb * clut () const
int colorCount () const
bool convertFromImage (const QImage &img, Qt::ImageConversionFlags flags=Qt::AutoColor)
Replaces this pixmap's data with the given image using the specified flags to control the conversion.
QPixmap copy (int x, int y, int width, int height) const
Returns a deep copy of the subset of the pixmap that is specified by the rectangle QRect(x, y, width, height).
QPixmap copy (const QRect &rect=QRect()) const
Returns a deep copy of the subset of the pixmap that is specified by the given rectangle.
QBitmap createHeuristicMask (bool clipTight=true) const
Creates and returns a heuristic mask for this pixmap.
QBitmap createMaskFromColor (const QColor &maskColor) const
Creates and returns a mask for this pixmap based on the given maskColor.
QBitmap createMaskFromColor (const QColor &maskColor, Qt::MaskMode mode) const
Creates and returns a mask for this pixmap based on the given maskColor.
DataPtr & data_ptr ()
int depth () const
Returns the depth of the pixmap.
void detach ()
Detaches the pixmap from shared pixmap data.
int devType () const
void fill (const QColor &fillColor=Qt::white)
Fills the pixmap with the given color.
void fill (const QWidget *widget, const QPoint &ofs)
Fills the pixmap with the widget's background color or pixmap according to the given offset.
void fill (const QWidget *widget, int xofs, int yofs)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Fills the pixmap with the widget's background color or pixmap.
Qt::HANDLE handle () const
Returns the pixmap's handle to the device context.
bool hasAlpha () const
Returns true if this pixmap has an alpha channel, or has a mask, otherwise returns false.
bool hasAlphaChannel () const
Returns true if the pixmap has a format that respects the alpha channel, otherwise returns false.
int height () const
Returns the height of the pixmap.
bool isDetached () const
bool isNull () const
Returns true if this is a null pixmap; otherwise returns false.
bool isQBitmap () const
Returns true if this is a QBitmap; otherwise returns false.
bool load (const QString &fileName, const char *format=0, Qt::ImageConversionFlags flags=Qt::AutoColor)
Loads a pixmap from the file with the given fileName.
bool loadFromData (const uchar *buf, uint len, const char *format=0, Qt::ImageConversionFlags flags=Qt::AutoColor)
Loads a pixmap from the len first bytes of the given binary data.
bool loadFromData (const QByteArray &data, const char *format=0, Qt::ImageConversionFlags flags=Qt::AutoColor)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Loads a pixmap from the binary data using the specified format and conversion flags.
QBitmap mask () const
Extracts a bitmap mask from the pixmap's alpha channel.
QT_DEPRECATED int numCols () const
operator QVariant () const
Returns the pixmap as a QVariant.
bool operator! () const
Returns true if this is a null pixmap; otherwise returns false.
QPixmap & operator= (const QPixmap &)
Assigns the given pixmap to this pixmap and returns a reference to this pixmap.
QPaintEngine * paintEngine () const
QPixmapData * pixmapData () const
QPixmap ()
Constructs a null pixmap.
QPixmap (QPixmapData *data)
QPixmap (int w, int h)
Constructs a pixmap with the given width and height.
QPixmap (const QSize &)
Constructs a pixmap of the given size.
QPixmap (const QString &fileName, const char *format=0, Qt::ImageConversionFlags flags=Qt::AutoColor)
Constructs a pixmap from the file with the given fileName.
QPixmap (const char *const xpm[])
Constructs a pixmap from the given xpm data, which must be a valid XPM image.
QPixmap (const QPixmap &)
Constructs a pixmap that is a copy of the given pixmap.
const uchar * qwsBits () const
int qwsBytesPerLine () const
QRect rect () const
Returns the pixmap's enclosing rectangle.
bool save (const QString &fileName, const char *format=0, int quality=-1) const
Saves the pixmap to the file with the given fileName using the specified image file format and quality factor.
bool save (QIODevice *device, const char *format=0, int quality=-1) const
This function writes a QPixmap to the given device using the specified image file format and quality factor.
QPixmap scaled (int w, int h, Qt::AspectRatioMode aspectMode=Qt::IgnoreAspectRatio, Qt::TransformationMode mode=Qt::FastTransformation) const
QPixmap scaled (const QSize &s, Qt::AspectRatioMode aspectMode=Qt::IgnoreAspectRatio, Qt::TransformationMode mode=Qt::FastTransformation) const
QPixmap scaledToHeight (int h, Qt::TransformationMode mode=Qt::FastTransformation) const
QPixmap scaledToWidth (int w, Qt::TransformationMode mode=Qt::FastTransformation) const
Returns a scaled copy of the image.
void scroll (int dx, int dy, int x, int y, int width, int height, QRegion *exposed=0)
void scroll (int dx, int dy, const QRect &rect, QRegion *exposed=0)
Scrolls the area rect of this pixmap by (dx, dy).
QT_DEPRECATED int serialNumber () const
Returns a number that identifies the contents of this QPixmap object.
QT_DEPRECATED void setAlphaChannel (const QPixmap &)
Sets the alpha channel of this pixmap to the given alphaChannel by converting the alphaChannel into 32 bit and using the intensity of the RGB pixel values.
void setMask (const QBitmap &)
Sets a mask bitmap.
QSize size () const
Returns the size of the pixmap.
void swap (QPixmap &other)
Swaps pixmap other with this pixmap.
QImage toImage () const
Converts the pixmap to a QImage.
CGImageRef toMacCGImageRef () const
Creates a CGImageRef equivalent to the QPixmap.
HBITMAP toWinHBITMAP (HBitmapFormat format=NoAlpha) const
It is the caller's responsibility to free the HBITMAP data after use.
HICON toWinHICON () const
Returns the HICON handle.
QPixmap transformed (const QMatrix &, Qt::TransformationMode mode=Qt::FastTransformation) const
This convenience function loads the matrix into a QTransform and calls the overloaded function.
QPixmap transformed (const QTransform &, Qt::TransformationMode mode=Qt::FastTransformation) const
Returns a copy of the pixmap that is transformed using the given transformation transform and transformation mode.
int width () const
Returns the width of the pixmap.
~QPixmap ()
Destroys the pixmap.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
virtual HDC getDC () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
virtual void releaseDC (HDC hdc) const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static int defaultDepth ()
Returns the default pixmap depth used by the application.
static QPixmap fromImage (const QImage &image, Qt::ImageConversionFlags flags=Qt::AutoColor)
Converts the given image to a pixmap using the specified flags to control the conversion.
static QPixmap fromImageReader (QImageReader *imageReader, Qt::ImageConversionFlags flags=Qt::AutoColor)
Create a QPixmap from an image read directly from an imageReader.
static QPixmap fromMacCGImageRef (CGImageRef image)
Returns a QPixmap that is equivalent to the given image.
static QPixmap fromWinHBITMAP (HBITMAP hbitmap, HBitmapFormat format=NoAlpha)
Win32 only: Returns a QPixmap that is equivalent to the given bitmap.
static QPixmap fromWinHICON (HICON hicon)
static QPixmap grabWidget (QWidget *widget, const QRect &rect)
Creates a pixmap and paints the given widget, restricted by the given rectangle, in it.
static QPixmap grabWidget (QWidget *widget, int x=0, int y=0, int w=-1, int h=-1)
static QPixmap grabWindow (WId, int x=0, int y=0, int w=-1, int h=-1)
Creates and returns a pixmap constructed by grabbing the contents of the given window restricted by QRect(x, y, width, height).
static QMatrix trueMatrix (const QMatrix &m, int w, int h)
This convenience function loads the matrix m into a QTransform and calls the overloaded function with the QTransform and the width w and the height h.
static QTransform trueMatrix (const QTransform &m, int w, int h)
Returns the actual matrix used for transforming a pixmap with the given width, height and matrix.
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Functions
int metric (PaintDeviceMetric) const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Types
enum Type { PixmapType, BitmapType }
Private Functions
void deref ()
bool doImageIO (QImageWriter *io, int quality) const
void init (int, int, Type=PixmapType)
void init (int, int, int)
void initAlphaPixmap (uchar *bytes, int length, struct tagBITMAPINFO *bmi)
QPixmap (const QSize &s, Type)
QPixmap (const QSize &s, int type)
Properties
QExplicitlySharedDataPointer< QPixmapData > data
Friends
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QPixmap &)
Reads an image from the given stream into the given pixmap.
class QBitmap
class QCoreGraphicsPaintEngine
class QGLWidget
class QMacPixmapData
class QPaintDevice
class QPainter
class QPixmapData
class QRasterBuffer
class QSymbianRasterPixmapData
CGContextRef qt_mac_cg_context (const QPaintDevice *)
Returns the CoreGraphics CGContextRef of the paint device.
IconRef qt_mac_create_iconref (const QPixmap &)
CGImageRef qt_mac_create_imagemask (const QPixmap &, const QRectF &)
quint32 * qt_mac_pixmap_get_base (const QPixmap *)
int qt_mac_pixmap_get_bytes_per_line (const QPixmap *)
Q_GUI_EXPORT qint64 qt_pixmap_id (const QPixmap &pixmap)
class QWidgetPrivate
class QX11PaintEngine
class QX11PixmapData
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QPixmap &pixmap)
Writes the given pixmap to the given stream as a PNG image.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Additional Inherited Members
Protected Variables inherited from QPaintDevice
ushort painters
Detailed Description
The QPixmap class is an off-screen image representation that can be used as a paint device.
Qt provides four classes for handling image data: QImage, QPixmap, QBitmap and QPicture. QImage is designed and optimized for I/O, and for direct pixel access and manipulation, while QPixmap is designed and optimized for showing images on screen. QBitmap is only a convenience class that inherits QPixmap, ensuring a depth of 1. The isQBitmap() function returns true if a QPixmap object is really a bitmap, otherwise returns false. Finally, the QPicture class is a paint device that records and replays QPainter commands.
A QPixmap can easily be displayed on the screen using QLabel or one of QAbstractButton's subclasses (such as QPushButton and QToolButton). QLabel has a pixmap property, whereas QAbstractButton has an icon property.
In addition to the ordinary constructors, a QPixmap can be constructed using the static grabWidget() and grabWindow() functions which creates a QPixmap and paints the given widget, or window, into it.
QPixmap objects can be passed around by value since the QPixmap class uses implicit data sharing. For more information, see the Implicit Data Sharing documentation. QPixmap objects can also be streamed.
Note that the pixel data in a pixmap is internal and is managed by the underlying window system. Because QPixmap is a QPaintDevice subclass, QPainter can be used to draw directly onto pixmaps. Pixels can only be accessed through QPainter functions or by converting the QPixmap to a QImage. However, the fill() function is available for initializing the entire pixmap with a given color.
There are functions to convert between QImage and QPixmap. Typically, the QImage class is used to load an image file, optionally manipulating the image data, before the QImage object is converted into a QPixmap to be shown on screen. Alternatively, if no manipulation is desired, the image file can be loaded directly into a QPixmap. On Windows, the QPixmap class also supports conversion between HBITMAP and QPixmap. On Symbian, the QPixmap class also supports conversion between CFbsBitmap and QPixmap.
QPixmap provides a collection of functions that can be used to obtain a variety of information about the pixmap. In addition, there are several functions that enables transformation of the pixmap.
Reading and Writing Image Files
QPixmap provides several ways of reading an image file: The file can be loaded when constructing the QPixmap object, or by using the load() or loadFromData() functions later on. When loading an image, the file name can either refer to an actual file on disk or to one of the application's embedded resources. See The Qt Resource System overview for details on how to embed images and other resource files in the application's executable.
Simply call the save() function to save a QPixmap object.
The complete list of supported file formats are available through the QImageReader::supportedImageFormats() and QImageWriter::supportedImageFormats() functions. New file formats can be added as plugins. By default, Qt supports the following formats:
Format Description Qt's support
BMP Windows Bitmap Read/write
GIF Graphic Interchange Format (optional) Read
JPG Joint Photographic Experts Group Read/write
JPEG Joint Photographic Experts Group Read/write
PNG Portable Network Graphics Read/write
PBM Portable Bitmap Read
PGM Portable Graymap Read
PPM Portable Pixmap Read/write
XBM X11 Bitmap Read/write
XPM X11 Pixmap Read/write
Pixmap Information
QPixmap provides a collection of functions that can be used to obtain a variety of information about the pixmap:
Available Functions
Geometry
The size(), width() and height() functions provide information about the pixmap's size. The rect() function returns the image's enclosing rectangle.
Alpha component
The hasAlphaChannel() returns true if the pixmap has a format that respects the alpha channel, otherwise returns false. The hasAlpha(), setMask() and mask() functions are legacy and should not be used. They are potentially very slow.
The createHeuristicMask() function creates and returns a 1-bpp heuristic mask (i.e. a QBitmap) for this pixmap. It works by selecting a color from one of the corners and then chipping away pixels of that color, starting at all the edges. The createMaskFromColor() function creates and returns a mask (i.e. a QBitmap) for the pixmap based on a given color.
Low-level information
The depth() function returns the depth of the pixmap. The defaultDepth() function returns the default depth, i.e. the depth used by the application on the given screen.
The cacheKey() function returns a number that uniquely identifies the contents of the QPixmap object.
The x11Info() function returns information about the configuration of the X display used by the screen to which the pixmap currently belongs. The x11PictureHandle() function returns the X11 Picture handle of the pixmap for XRender support. Note that the two latter functions are only available on x11.
Pixmap Conversion
A QPixmap object can be converted into a QImage using the toImage() function. Likewise, a QImage can be converted into a QPixmap using the fromImage(). If this is too expensive an operation, you can use QBitmap::fromImage() instead.
In addition, on Windows, the QPixmap class supports conversion to and from HBITMAP: the toWinHBITMAP() function creates a HBITMAP equivalent to the QPixmap, based on the given HBitmapFormat, and returns the HBITMAP handle. The fromWinHBITMAP() function returns a QPixmap that is equivalent to the given bitmap which has the specified format. The QPixmap class also supports conversion to and from HICON: the toWinHICON() function creates a HICON equivalent to the QPixmap, and returns the HICON handle. The fromWinHICON() function returns a QPixmap that is equivalent to the given icon.
In addition, on Symbian, the QPixmap class supports conversion to and from CFbsBitmap: the toSymbianCFbsBitmap() function creates CFbsBitmap equivalent to the QPixmap, based on given mode and returns a CFbsBitmap object. The fromSymbianCFbsBitmap() function returns a QPixmap that is equivalent to the given bitmap and given mode.
Pixmap Transformations
QPixmap supports a number of functions for creating a new pixmap that is a transformed version of the original:
The scaled(), scaledToWidth() and scaledToHeight() functions return scaled copies of the pixmap, while the copy() function creates a QPixmap that is a plain copy of the original one.
The transformed() function returns a copy of the pixmap that is transformed with the given transformation matrix and transformation mode: Internally, the transformation matrix is adjusted to compensate for unwanted translation, i.e. transformed() returns the smallest pixmap containing all transformed points of the original pixmap. The static trueMatrix() function returns the actual matrix used for transforming the pixmap.
Note
When using the native X11 graphics system, the pixmap becomes invalid when the QApplication instance is destroyed.
See also
QBitmap, QImage, QImageReader, QImageWriter
Definition at line 71 of file qpixmap.h.
Typedefs
DataPtr
QPixmap::DataPtr
Warning
This function is not part of the public interface.
Definition at line 296 of file qpixmap.h.
Enumerations
HBitmapFormat
enum QPixmap::HBitmapFormat
HBITMAP and QPixmap is performed.
Win32 only: This enum defines how the conversion between
Warning
This enum is only available on Windows.
NoAlpha The alpha channel is ignored and always treated as being set to fully opaque. This is preferred if the HBITMAP is used with standard GDI calls, such as BitBlt().
PremultipliedAlpha The HBITMAP is treated as having an alpha channel and premultiplied colors. This is preferred if the HBITMAP is accessed through the AlphaBlend() GDI function.
Alpha The HBITMAP is treated as having a plain alpha channel. This is the preferred format if the HBITMAP is going to be used as an application icon or systray icon.
See also
fromWinHBITMAP(), toWinHBITMAP()
Enumerator
NoAlpha
PremultipliedAlpha
Alpha
Definition at line 157 of file qpixmap.h.
{
         NoAlpha,
         PremultipliedAlpha,
         Alpha
     };
Type
enum QPixmap::Type private
Enumerator
PixmapType
BitmapType
Definition at line 257 of file qpixmap.h.
 { PixmapType, BitmapType }; // must match QPixmapData::PixelType
Constructors and Destructors
QPixmap() [1/9]
QPixmap::QPixmap ()
Constructs a null pixmap.
See also
isNull()
Definition at line 174 of file qpixmap.cpp.
Referenced by alphaChannel(), copy(), depth(), QBitmap::fromImage(), fromImage(), fromImageReader(), fromWinHBITMAP(), fromWinHICON(), grabWidget(), handle(), scaled(), scaledToHeight(), scaledToWidth(), and toWinHBITMAP().
     : QPaintDevice()
 {
     (void) qt_pixmap_thread_test();
     init(0, 0, QPixmapData::PixmapType);
 }
QPixmap() [2/9]
QPixmap::QPixmap (QPixmapData * d) explicit
Warning
This function is not part of the public interface.
Definition at line 254 of file qpixmap.cpp.
     : QPaintDevice(), data(d)
 {
 }
QPixmap() [3/9]
QPixmap::QPixmap (int width, int height)
Constructs a pixmap with the given width and height.
If either width or height is zero, a null pixmap is constructed.
Warning
This will create a QPixmap with uninitialized data. Call fill() to fill the pixmap with an appropriate color before drawing onto it with QPainter.
See also
isNull()
Definition at line 198 of file qpixmap.cpp.
     : QPaintDevice()
 {
     if (!qt_pixmap_thread_test())
         init(0, 0, QPixmapData::PixmapType);
     else
         init(w, h, QPixmapData::PixmapType);
 }
QPixmap() [4/9]
QPixmap::QPixmap (const QSize & size)
Constructs a pixmap of the given size.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Warning
This will create a QPixmap with uninitialized data. Call fill() to fill the pixmap with an appropriate color before drawing onto it with QPainter.
Definition at line 220 of file qpixmap.cpp.
     : QPaintDevice()
 {
     if (!qt_pixmap_thread_test())
         init(0, 0, QPixmapData::PixmapType);
     else
         init(size.width(), size.height(), QPixmapData::PixmapType);
 }
QPixmap() [5/9]
QPixmap::QPixmap (const QString & fileName, const char * format = 0, Qt::ImageConversionFlags flags = Qt::AutoColor)
Constructs a pixmap from the file with the given fileName.
If the file does not exist or is of an unknown format, the pixmap becomes a null pixmap.
The loader attempts to read the pixmap using the specified format. If the format is not specified (which is the default), the loader probes the file for a header to guess the file format.
The file name can either refer to an actual file on disk or to one of the application's embedded resources. See the Resource System overview for details on how to embed images and other resource files in the application's executable.
If the image needs to be modified to fit in a lower-resolution result (e.g. converting from 32-bit to 8-bit), use the flags to control the conversion.
The fileName, format and flags parameters are passed on to load(). This means that the data in fileName is not compiled into the binary. If fileName contains a relative path (e.g. the filename only) the relevant file must be found relative to the runtime working directory.
See also
{QPixmap::Reading and Writing Image Files}{Reading and Writing Image Files}
Definition at line 287 of file qpixmap.cpp.
     : QPaintDevice()
 {
     init(0, 0, QPixmapData::PixmapType);
     if (!qt_pixmap_thread_test())
         return;
     load(fileName, format, flags);
 }
QPixmap() [6/9]
QPixmap::QPixmap (const char *const xpm[])
Constructs a pixmap from the given xpm data, which must be a valid XPM image.
Errors are silently ignored.
Note that it's possible to squeeze the XPM variable a little bit by using an unusual declaration:
static const char * const start_xpm[]={
    "16 15 8 1",
    "a c #cec6bd",
....
The extra const makes the entire definition read-only, which is slightly more efficient (for example, when the code is in a shared library) and ROMable when the application is to be stored in ROM.
Definition at line 333 of file qpixmap.cpp.
     : QPaintDevice()
 {
     init(0, 0, QPixmapData::PixmapType);
     if (!xpm)
         return;
     QImage image(xpm);
     if (!image.isNull()) {
         if (data && data->pixelType() == QPixmapData::BitmapType)
             *this = QBitmap::fromImage(image);
         else
             *this = fromImage(image);
     }
 }
QPixmap() [7/9]
QPixmap::QPixmap (const QPixmap & pixmap)
Constructs a pixmap that is a copy of the given pixmap.
See also
copy()
Definition at line 303 of file qpixmap.cpp.
     : QPaintDevice()
 {
     if (!qt_pixmap_thread_test()) {
         init(0, 0, QPixmapData::PixmapType);
         return;
     }
     if (pixmap.paintingActive()) {                // make a deep copy
         operator=(pixmap.copy());
     } else {
         data = pixmap.data;
     }
 }
~QPixmap()
QPixmap::~QPixmap ()
Destroys the pixmap.
Definition at line 355 of file qpixmap.cpp.
 {
     Q_ASSERT(!data || data->ref >= 1); // Catch if ref-counting changes again
 }
QPixmap() [8/9]
QPixmap::QPixmap (const QSize & s, Type type) private
Warning
This function is not part of the public interface.
Definition at line 232 of file qpixmap.cpp.
 {
     if (!qt_pixmap_thread_test())
         init(0, 0, type);
     else
         init(s.width(), s.height(), type);
 }
QPixmap() [9/9]
QPixmap::QPixmap (const QSize & s, int type) private
Warning
This function is not part of the public interface.
Definition at line 243 of file qpixmap.cpp.
 {
     if (!qt_pixmap_thread_test())
         init(0, 0, static_cast<QPixmapData::PixelType>(type));
     else
         init(s.width(), s.height(), static_cast<QPixmapData::PixelType>(type));
 }
Functions
alphaChannel()
QPixmap QPixmap::alphaChannel () const
Returns the alpha channel of the pixmap as a new grayscale QPixmap in which each pixel's red, green, and blue values are given the alpha value of the original pixmap.
The color depth of the returned pixmap is the system depth on X11 and 8-bit on Windows and Mac OS X.
You can use this function while debugging to get a visible image of the alpha channel. If the pixmap doesn't have an alpha channel, i.e., the alpha channel's value for all pixels equals 0xff), a null pixmap is returned. You can check this with the isNull() function.
We show an example:
    pixmap = QPixmap(100, 100);
    pixmap.fill(Qt::transparent);
    QRadialGradient gradient(50, 50, 50, 50, 50);
    gradient.setColorAt(0, QColor::fromRgbF(1, 0, 0, 1));
    gradient.setColorAt(1, QColor::fromRgbF(0, 0, 0, 0));
    QPainter painter(&pixmap);
    painter.fillRect(0, 0, 100, 100, gradient);
    channelImage = pixmap.alphaChannel();
    update();
The pixmap and channelImage QPixmaps
Warning
This is an expensive operation. The alpha channel of the pixmap is extracted dynamically from the pixeldata. Most usecases of this function are covered by QPainter and compositionModes which will normally execute faster.
See also
setAlphaChannel(), {QPixmap::Pixmap Information}{Pixmap Information}
Definition at line 2051 of file qpixmap.cpp.
 {
     return data ? data->alphaChannel() : QPixmap();
 }
cacheKey()
qint64 QPixmap::cacheKey () const
Returns a number that identifies this QPixmap.
Distinct QPixmap objects can only have the same cache key if they refer to the same contents.
The cacheKey() will change when the pixmap is altered.
Definition at line 1136 of file qpixmap.cpp.
Referenced by QPdfEngine::drawPixmap(), QTextHtmlExporter::emitBackgroundAttribute(), QGLBlurTextureCache::insertBlurTextureInfo(), operator<<(), QBrush::operator==(), QPixmapIconEngine::pixmap(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), qDrawPlainRect(), qt_mac_fill_background(), qt_pixmap_id(), QLabel::setPixmap(), and QGLBlurTextureCache::takeBlurTextureInfo().
 {
     if (isNull())
         return 0;
     Q_ASSERT(data);
     return data->cacheKey();
 }
clut()
QRgb * QPixmap::clut () const
Warning
This function is not part of the public interface.
Definition at line 115 of file qpixmap_qws.cpp.
 {
     if (data && data->classId() == QPixmapData::RasterClass) {
         const QRasterPixmapData *d = static_cast<const QRasterPixmapData*>(data.data());
         return d->image.colorTable().data();
     }
     return 0;
 }
colorCount()
int QPixmap::colorCount () const
Since
4.6
Warning
This function is not part of the public interface.
Definition at line 130 of file qpixmap_qws.cpp.
Referenced by numCols().
 {
     if (data && data->classId() == QPixmapData::RasterClass) {
         const QRasterPixmapData *d = static_cast<const QRasterPixmapData*>(data.data());
         return d->image.colorCount();
     }
     return 0;
 }
convertFromImage()
bool QPixmap::convertFromImage (const QImage & image, Qt::ImageConversionFlags flags = Qt::AutoColor)
Replaces this pixmap's data with the given image using the specified flags to control the conversion.
The flags argument is a bitwise-OR of the Qt::ImageConversionFlags. Passing 0 for flags sets all the default options. Returns true if the result is that this pixmap is not null.
Note: this function was part of Qt 3 support in Qt 4.6 and earlier. It has been promoted to official API status in 4.7 to support updating the pixmap's image without creating a new QPixmap as fromImage() would.
See also
fromImage()
Since
4.7
Definition at line 1531 of file qpixmap.cpp.
Referenced by handle().
 {
     if (image.isNull() || !data)
         *this = QPixmap::fromImage(image, flags);
     else
         data->fromImage(image, flags);
     return !isNull();
 }
copy() [1/2]
QPixmap QPixmap::copy (int x, int y, int width, int height) const inline
Returns a deep copy of the subset of the pixmap that is specified by the rectangle QRect(x, y, width, height).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 302 of file qpixmap.h.
Referenced by detach(), QPixmapBlurFilter::draw(), QPixmapColorizeFilter::draw(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QPSPrintEngine::drawPixmap(), QWin32PrintEngine::drawPixmap(), QPdfEngine::drawPixmap(), QPainter::drawPixmap(), QOpenGLPaintEngine::drawTiledPixmap(), operator=(), QPixmap(), scaledToHeight(), and scaledToWidth().
 {
     return copy(QRect(ax, ay, awidth, aheight));
 }
copy() [2/2]
QPixmap QPixmap::copy (const QRect & rectangle = QRect()) const
Returns a deep copy of the subset of the pixmap that is specified by the given rectangle.
For more information on deep copies, see the Implicit Data Sharing documentation.
If the given rectangle is empty, the whole image is copied.
See also
operator=(), QPixmap(), {QPixmap::Pixmap Transformations}{Pixmap Transformations}
Definition at line 394 of file qpixmap.cpp.
 {
     if (isNull())
         return QPixmap();
     QRect r(0, 0, width(), height());
     if (!rect.isEmpty())
         r = r.intersected(rect);
     QPixmapData *d = data->createCompatiblePixmapData();
     d->copy(data.data(), r);
     return QPixmap(d);
 }
createHeuristicMask()
QBitmap QPixmap::createHeuristicMask (bool clipTight = true) const
Creates and returns a heuristic mask for this pixmap.
The function works by selecting a color from one of the corners and then chipping away pixels of that color, starting at all the edges. If clipTight is true (the default) the mask is just large enough to cover the pixels; otherwise, the mask is larger than the data pixels.
The mask may not be perfect but it should be reasonable, so you can do things such as the following:
QPixmap myPixmap;
myPixmap->setMask(myPixmap->createHeuristicMask());
This function is slow because it involves converting to/from a QImage, and non-trivial computations.
See also
QImage::createHeuristicMask(), createMaskFromColor()
Definition at line 864 of file qpixmap.cpp.
Referenced by isServerProcess(), qDrawPlainRect(), and QGraphicsPixmapItemPrivate::updateShape().
 {
     QBitmap m = QBitmap::fromImage(toImage().createHeuristicMask(clipTight));
     return m;
 }
createMaskFromColor() [1/2]
QBitmap QPixmap::createMaskFromColor (const QColor & maskColor) const
Creates and returns a mask for this pixmap based on the given maskColor.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Same as calling createMaskFromColor(maskColor, Qt::MaskInColor)
See also
createHeuristicMask(), QImage::createMaskFromColor()
Definition at line 899 of file qpixmap.cpp.
 {
     return createMaskFromColor(maskColor, Qt::MaskInColor);
 }
createMaskFromColor() [2/2]
QBitmap QPixmap::createMaskFromColor (const QColor & maskColor, Qt::MaskMode mode) const
Creates and returns a mask for this pixmap based on the given maskColor.
If the mode is Qt::MaskInColor, all pixels matching the maskColor will be transparent. If mode is Qt::MaskOutColor, all pixels matching the maskColor will be opaque.
This function is slow because it involves converting to/from a QImage.
See also
createHeuristicMask(), QImage::createMaskFromColor()
Definition at line 882 of file qpixmap.cpp.
 {
     QImage image = toImage().convertToFormat(QImage::Format_ARGB32);
     return QBitmap::fromImage(image.createMaskFromColor(maskColor.rgba(), mode));
 }
data_ptr()
DataPtr & QPixmap::data_ptr () inline
Warning
This function is not part of the public interface.
Definition at line 297 of file qpixmap.h.
Referenced by QX11WindowSurface::beginPaint(), QGLContextPrivate::bindTextureFromNativePixmap(), QX11GLWindowSurface::flush(), QMeeGoGraphicsSystem::getLiveTextureHandle(), QMeeGoLivePixmapData::getSurfaceForBackingPixmap(), QMeeGoLivePixmapData::invalidateSurfaces(), QMeeGoGraphicsSystem::lockLiveTexture(), qt_toRasterPixmap(), qt_toX11Pixmap(), QMeeGoGraphicsSystem::releaseLiveTexture(), and QX11GLWindowSurface::scroll().
 { return data; }
defaultDepth()
int QPixmap::defaultDepth () static
Returns the default pixmap depth used by the application.
On Windows and Mac, the default depth is always 32. On X11 and embedded, the depth of the screen will be returned by this function.
See also
depth(), QColormap::depth(), {QPixmap::Pixmap Information}{Pixmap Information}
Definition at line 2092 of file qpixmap.cpp.
Referenced by QMacPixmapData::fromImage().
 {
 #if defined(Q_WS_QWS)
     return QScreen::instance()->depth();
 #elif defined(Q_WS_X11)
     return QX11Info::appDepth();
 #elif defined(Q_WS_WINCE)
     return QColormap::instance().depth();
 #elif defined(Q_WS_WIN)
     return 32; // XXX
 #elif defined(Q_WS_MAC)
     return 32;
 #elif defined(Q_OS_SYMBIAN)
     return S60->screenDepth;
 #elif defined(Q_WS_QPA)
     return 32; //LITE: use graphicssystem (we should do that in general)
 #endif
 }
depth()
int QPixmap::depth () const
Returns the depth of the pixmap.
The pixmap depth is also called bits per pixel (bpp) or bit planes of a pixmap. A null pixmap has depth 0.
See also
defaultDepth(), {QPixmap::Pixmap Information}{Pixmap Information}
Definition at line 695 of file qpixmap.cpp.
Referenced by QPainter::begin(), QX11WindowSurface::beginPaint(), QCoreGraphicsPaintEngine::drawPixmap(), QOpenGLPaintEngine::drawPixmap(), QRasterPaintEngine::drawPixmap(), QPdfEngine::drawTiledPixmap(), QX11PaintEngine::drawTiledPixmap(), QOpenGLPaintEngine::drawTiledPixmap(), QPaintEngine::drawTiledPixmap(), QX11PaintEnginePrivate::fillPolygon_dev(), QPixmapCache::insert(), QMeeGoLivePixmapData::lock(), QBitmap::operator=(), QGLOverlayWidget::paintGL(), QCursor::QCursor(), qDrawPlainRect(), qt_mac_draw_pattern(), QPixmapCache::replace(), QCursorData::setBitmap(), toWinHBITMAP(), QPainterPrivate::updateEmulationSpecifier(), and QX11Data::xdndMimeDataForAtom().
 {
     return data ? data->depth() : 0;
 }
deref()
void QPixmap::deref () private
Warning
This function is not part of the public interface.
Qt5 - remove me.
Definition at line 1503 of file qpixmap.cpp.
 {
     Q_ASSERT_X(false, "QPixmap::deref()", "Do not call this function anymore!");
 }
detach()
void QPixmap::detach ()
Detaches the pixmap from shared pixmap data.
A pixmap is automatically detached by Qt whenever its contents are about to change. This is done in almost all QPixmap member functions that modify the pixmap (fill(), fromImage(), load(), etc.), and in QPainter::begin() on a pixmap.
There are two exceptions in which detach() must be called explicitly, that is when calling the handle() or the x11PictureHandle() function (only available on X11). Otherwise, any modifications done using system calls, will be performed on the shared data.
The detach() function returns immediately if there is just a single reference or if the pixmap has not been initialized yet.
Definition at line 2128 of file qpixmap.cpp.
Referenced by fill(), scroll(), setAlphaChannel(), and setMask().
 {
     if (!data)
         return;
     // QPixmap.data member may be QRuntimePixmapData so use pixmapData() function to get
     // the actual underlaying runtime pixmap data.
     QPixmapData *pd = pixmapData();
     QPixmapData::ClassId id = pd->classId();
     if (id == QPixmapData::RasterClass) {
         QRasterPixmapData *rasterData = static_cast<QRasterPixmapData*>(pd);
         rasterData->image.detach();
     }
     if (data->is_cached && data->ref == 1)
         QImagePixmapCleanupHooks::executePixmapDataModificationHooks(data.data());
 #if defined(Q_WS_MAC)
     QMacPixmapData *macData = id == QPixmapData::MacClass ? static_cast<QMacPixmapData*>(pd) : 0;
     if (macData) {
         if (macData->cg_mask) {
             CGImageRelease(macData->cg_mask);
             macData->cg_mask = 0;
         }
     }
 #endif
     if (data->ref != 1) {
         *this = copy();
     }
     ++data->detach_no;
 #if defined(Q_WS_X11)
     if (pd->classId() == QPixmapData::X11Class) {
         QX11PixmapData *d = static_cast<QX11PixmapData*>(pd);
         d->flags &= ~QX11PixmapData::Uninitialized;
         // reset the cache data
         if (d->hd2) {
             XFreePixmap(X11->display, d->hd2);
             d->hd2 = 0;
         }
     }
 #elif defined(Q_WS_MAC)
     if (macData) {
         macData->macReleaseCGImageRef();
         macData->uninit = false;
     }
 #endif
 }
devType()
int QPixmap::devType () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QPaintDevice.
Definition at line 363 of file qpixmap.cpp.
 {
     return QInternal::Pixmap;
 }
doImageIO()
bool QPixmap::doImageIO (QImageWriter * writer, int quality) const private
Warning
This function is not part of the public interface.
Definition at line 1047 of file qpixmap.cpp.
Referenced by save().
 {
     if (quality > 100  || quality < -1)
         qWarning("QPixmap::save: quality out of range [-1,100]");
     if (quality >= 0)
         writer->setQuality(qMin(quality,100));
     return writer->write(toImage());
 }
fill() [1/3]
void QPixmap::fill (const QColor & color = Qt::white)
Fills the pixmap with the given color.
The effect of this function is undefined when the pixmap is being painted on.
See also
{QPixmap::Pixmap Transformations}{Pixmap Transformations}
Definition at line 1080 of file qpixmap.cpp.
Referenced by _q_paintIntoCache(), QX11PixmapData::alphaChannel(), QBalloonTip::balloon(), QBitmap::clear(), create32BitCursor(), QOleDropSource::createCursors(), QItemDelegate::decoration(), depth(), QMacStylePrivate::drawColorlessButton(), QMacStylePrivate::drawCombobox(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QGtkStyle::drawControl(), QMacStyle::drawControl(), QGraphicsScenePrivate::drawItemHelper(), QDeclarativeTextPrivate::drawOutline(), QOpenGLPaintEngine::drawPixmap(), QWindowsVistaStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QMacStylePrivate::drawTableHeader(), QX11PaintEngine::drawTiledPixmap(), QOpenGLPaintEngine::drawTiledPixmap(), QPaintEngine::drawTiledPixmap(), fromMacCGImageRef(), QComboMenuDelegate::getStyleOption(), grabWidget(), QStyledItemDelegate::initStyleOption(), QColorWell::mouseMoveEvent(), QColorShowLabel::mouseMoveEvent(), QDeclarativePaintedItem::paint(), QAxHostWidget::paintEvent(), QGraphicsItemEffectSourcePrivate::pixmap(), QWidgetEffectSourcePrivate::pixmap(), QMacStyle::polish(), QCursor::QCursor(), qt_mac_convert_iconref(), qt_mac_draw_pattern(), QWidgetPrivate::render_helper(), QAbstractItemViewPrivate::renderToPixmap(), QTreeViewPrivate::renderTreeToPixmapForAnimation(), QX11GLWindowSurface::setGeometry(), QTabBarPrivate::setupMovableTab(), QHeaderViewPrivate::setupSectionIndicator(), QWorkspacePrivate::showMaximizeControls(), QWindowsVistaStyle::standardIconImplementation(), QMacStyle::standardIconImplementation(), QMacStyle::styleHint(), QDeclarativeTextPrivate::textDocumentImage(), QDeclarativeTextPrivate::textLayoutImage(), toWinHICON(), QX11PixmapData::transformed(), and QCursorData::update().
 {
     if (isNull())
         return;
     // Some people are probably already calling fill while a painter is active, so to not break
     // their programs, only print a warning and return when the fill operation could cause a crash.
     if (paintingActive() && (color.alpha() != 255) && !hasAlphaChannel()) {
         qWarning("QPixmap::fill: Cannot fill while pixmap is being painted on");
         return;
     }
     if (data->ref == 1) {
         // detach() will also remove this pixmap from caches, so
         // it has to be called even when ref == 1.
         detach();
     } else {
         // Don't bother to make a copy of the data object, since
         // it will be filled with new pixel data anyway.
         QPixmapData *d = data->createCompatiblePixmapData();
         d->resize(data->width(), data->height());
         data = d;
     }
     data->fill(color);
 }
fill() [2/3]
void QPixmap::fill (const QWidget * widget, const QPoint & offset)
Fills the pixmap with the widget's background color or pixmap according to the given offset.
The QPoint offset defines a point in widget coordinates to which the pixmap's top-left pixel will be mapped to. This is only significant if the widget has a background pixmap; otherwise the pixmap will simply be filled with the background color of the widget.
Definition at line 2385 of file qwidget.cpp.
 {
     QPainter p(this);
     p.translate(-off);
     widget->d_func()->paintBackground(&p, QRect(off, size()));
 }
fill() [3/3]
void QPixmap::fill (const QWidget * widget, int x, int y) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Fills the pixmap with the widget's background color or pixmap.
The given point, (x, y), defines an offset in widget coordinates to which the pixmap's top-left pixel will be mapped to.
Definition at line 107 of file qpixmap.h.
Referenced by fill().
 { fill(widget, QPoint(xofs, yofs)); }
fromImage()
QPixmap QPixmap::fromImage (const QImage & image, Qt::ImageConversionFlags flags = Qt::AutoColor) static
Converts the given image to a pixmap using the specified flags to control the conversion.
The flags argument is a bitwise-OR of the Qt::ImageConversionFlags. Passing 0 for flags sets all the default options.
In case of monochrome and 8-bit images, the image is first converted to a 32-bit pixmap and then filled with the colors in the color table. If this is too expensive an operation, you can use QBitmap::fromImage() instead.
See also
fromImageReader(), toImage(), {QPixmap::Pixmap Conversion}{Pixmap Conversion}
Definition at line 2197 of file qpixmap.cpp.
Referenced by QX11PixmapData::alphaChannel(), QPixmapData::alphaChannel(), QDirectFBCursor::changeCursor(), QBitmap::clear(), convert(), convertFromImage(), createPixmapDataSync(), darkenPixmap(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QMacStylePrivate::drawColorlessButton(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QPaintEngine::drawImage(), QWindowsStyle::drawPrimitive(), QDeclarativePixmapReply::event(), fromWinHBITMAP(), fromWinHICON(), QWindowsMobileStyle::generatedIconPixmap(), QCommonStyle::generatedIconPixmap(), QMacStyle::generatedIconPixmap(), QGtkPainter::getIcon(), getPixmap(), QWindowSurface::grabWidget(), QXlibIntegration::grabWindow(), QVNCIntegration::grabWindow(), handle(), QPainterState::init(), QStyledItemDelegate::initStyleOption(), isServerProcess(), QMoviePrivate::next(), QLabel::paintEvent(), QColorLuminancePicker::paintEvent(), QSvgIconEngine::pixmap(), QTexturedBrushData::pixmap(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), QPixmap(), QAlphaWidget::render(), QGtkPainter::renderTheme(), QColorPicker::resizeEvent(), QAlphaWidget::run(), QItemDelegate::selected(), QWSServer::setBackground(), QCursor::setPos(), QCommonStyle::standardPixmap(), QWindowsMobileStyle::standardPixmap(), QMotifStyle::standardPixmap(), QGtkStyle::standardPixmap(), toWinHICON(), QX11PixmapData::transformed(), QPixmapData::transformed(), and QX11Data::xdndMimeDataForAtom().
 {
     if (image.isNull())
         return QPixmap();
     QGraphicsSystem* gs = QApplicationPrivate::graphicsSystem();
     QScopedPointer<QPixmapData> data(gs ? gs->createPixmapData(QPixmapData::PixmapType)
             : QGraphicsSystem::createDefaultPixmapData(QPixmapData::PixmapType));
     data->fromImage(image, flags);
     return QPixmap(data.take());
 }
fromImageReader()
QPixmap QPixmap::fromImageReader (QImageReader * imageReader, Qt::ImageConversionFlags flags = Qt::AutoColor) static
Create a QPixmap from an image read directly from an imageReader.
The flags argument is a bitwise-OR of the Qt::ImageConversionFlags. Passing 0 for flags sets all the default options.
On some systems, reading an image directly to QPixmap can use less memory than reading a QImage to convert it to QPixmap.
See also
fromImage(), toImage(), {QPixmap::Pixmap Conversion}{Pixmap Conversion}
Definition at line 2221 of file qpixmap.cpp.
 {
     QGraphicsSystem *gs = QApplicationPrivate::graphicsSystem();
     QScopedPointer<QPixmapData> data(gs ? gs->createPixmapData(QPixmapData::PixmapType)
             : QGraphicsSystem::createDefaultPixmapData(QPixmapData::PixmapType));
     data->fromImageReader(imageReader, flags);
     return QPixmap(data.take());
 }
fromMacCGImageRef()
QPixmap QPixmap::fromMacCGImageRef (CGImageRef image) static
Returns a QPixmap that is equivalent to the given image.
Since
4.2
Warning
This function is only available on Mac OS X.
See also
toMacCGImageRef(), {QPixmap::Pixmap Conversion}{Pixmap Conversion}
Definition at line 1271 of file qpixmap_mac.cpp.
Referenced by QMacPasteboardMimeHTMLText::convertFromMime(), QMacPasteboardMimeTiff::convertToMime(), QWizardPrivate::findDefaultBackgroundPixmap(), qt_mac_grabDisplayRect(), and qt_mac_grabScreenRect().
 {
     const size_t w = CGImageGetWidth(image),
                  h = CGImageGetHeight(image);
     QPixmap ret(w, h);
     ret.fill(Qt::transparent);
     CGRect rect = CGRectMake(0, 0, w, h);
     CGContextRef ctx = qt_mac_cg_context(&ret);
     qt_mac_drawCGImage(ctx, &rect, image);
     CGContextRelease(ctx);
     return ret;
 }
fromWinHBITMAP()
QPixmap QPixmap::fromWinHBITMAP (HBITMAP bitmap, HBitmapFormat format = NoAlpha) static
Win32 only: Returns a QPixmap that is equivalent to the given bitmap.
The conversion is based on the specified format.
Warning
This function is only available on Windows.
See also
toWinHBITMAP(), {QPixmap::Pixmap Conversion}{Pixmap Conversion}
Definition at line 179 of file qpixmap_win.cpp.
Referenced by QGLContext::choosePixelFormat(), IPictureToQPixmap(), and QAxHostWidget::paintEvent().
 {
     // Verify size
     BITMAP bitmap_info;
     memset(&bitmap_info, 0, sizeof(BITMAP));
     int res = GetObject(bitmap, sizeof(BITMAP), &bitmap_info);
     if (!res) {
         qErrnoWarning("QPixmap::fromWinHBITMAP(), failed to get bitmap info");
         return QPixmap();
     }
     int w = bitmap_info.bmWidth;
     int h = bitmap_info.bmHeight;
     BITMAPINFO bmi;
     memset(&bmi, 0, sizeof(bmi));
     bmi.bmiHeader.biSize        = sizeof(BITMAPINFOHEADER);
     bmi.bmiHeader.biWidth       = w;
     bmi.bmiHeader.biHeight      = -h;
     bmi.bmiHeader.biPlanes      = 1;
     bmi.bmiHeader.biBitCount    = 32;
     bmi.bmiHeader.biCompression = BI_RGB;
     bmi.bmiHeader.biSizeImage   = w * h * 4;
     QImage result;
     // Get bitmap bits
     uchar *data = (uchar *) qMalloc(bmi.bmiHeader.biSizeImage);
     HDC display_dc = GetDC(0);
     if (GetDIBits(display_dc, bitmap, 0, h, data, &bmi, DIB_RGB_COLORS)) {
         QImage::Format imageFormat = QImage::Format_ARGB32_Premultiplied;
         uint mask = 0;
         if (format == NoAlpha) {
             imageFormat = QImage::Format_RGB32;
             mask = 0xff000000;
         }
         // Create image and copy data into image.
         QImage image(w, h, imageFormat);
         if (!image.isNull()) { // failed to alloc?
             int bytes_per_line = w * sizeof(QRgb);
             for (int y=0; y<h; ++y) {
                 QRgb *dest = (QRgb *) image.scanLine(y);
                 const QRgb *src = (const QRgb *) (data + y * bytes_per_line);
                 for (int x=0; x<w; ++x) {
                     const uint pixel = src[x];
                     if ((pixel & 0xff000000) == 0 && (pixel & 0x00ffffff) != 0)
                         dest[x] = pixel | 0xff000000;
                     else
                         dest[x] = pixel | mask;
                 }
             }
         }
         result = image;
     } else {
         qWarning("QPixmap::fromWinHBITMAP(), failed to get bitmap bits");
     }
     ReleaseDC(0, display_dc);
     qFree(data);
     return fromImage(result);
 }
fromWinHICON()
QPixmap QPixmap::fromWinHICON (HICON icon) static
Since
4.6
Win32 only: Returns a QPixmap that is equivalent to the given icon.
Warning
This function is only available on Windows.
See also
toWinHICON(), {QPixmap::Pixmap Conversion}{Pixmap Conversion}
Definition at line 386 of file qpixmap_win.cpp.
Referenced by QFileIconProviderPrivate::getWinIcon(), loadIconFromShell32(), QWindowsStyle::standardIconImplementation(), QWindowsStyle::standardPixmap(), and toWinHICON().
 {
     HDC screenDevice = GetDC(0);
     HDC hdc = CreateCompatibleDC(screenDevice);
     ReleaseDC(0, screenDevice);
     ICONINFO iconinfo;
     bool result = GetIconInfo(icon, &iconinfo);
     if (!result)
         qWarning("QPixmap::fromWinHICON(), failed to GetIconInfo()");
     int w = 0;
     int h = 0;
     if (!iconinfo.xHotspot || !iconinfo.yHotspot) {
         // We could not retrieve the icon size via GetIconInfo,
         // so we try again using the icon bitmap.
         BITMAP bm;
         int result = GetObject(iconinfo.hbmColor, sizeof(BITMAP), &bm);
         if (!result) result = GetObject(iconinfo.hbmMask, sizeof(BITMAP), &bm);
         if (!result) {
             qWarning("QPixmap::fromWinHICON(), failed to retrieve icon size");
             return QPixmap();
         }
         w = bm.bmWidth;
         h = bm.bmHeight;
     } else {
         // x and y Hotspot describes the icon center
         w = iconinfo.xHotspot * 2;
         h = iconinfo.yHotspot * 2;
     }
     const DWORD dwImageSize = w * h * 4;
     BITMAPINFO bmi;
     memset(&bmi, 0, sizeof(bmi));
     bmi.bmiHeader.biSize        = sizeof(BITMAPINFO);
     bmi.bmiHeader.biWidth       = w;
     bmi.bmiHeader.biHeight      = -h;
     bmi.bmiHeader.biPlanes      = 1;
     bmi.bmiHeader.biBitCount    = 32;
     bmi.bmiHeader.biCompression = BI_RGB;
     bmi.bmiHeader.biSizeImage   = dwImageSize;
     uchar* bits;
     HBITMAP winBitmap = CreateDIBSection(hdc, &bmi, DIB_RGB_COLORS, (void**) &bits, 0, 0);
     if (winBitmap )
         memset(bits, 0xff, dwImageSize);
     if (!winBitmap) {
         qWarning("QPixmap::fromWinHICON(), failed to CreateDIBSection()");
         return QPixmap();
     }
     HGDIOBJ oldhdc = (HBITMAP)SelectObject(hdc, winBitmap);
     if (!DrawIconEx( hdc, 0, 0, icon, w, h, 0, 0, DI_NORMAL))
         qWarning("QPixmap::fromWinHICON(), failed to DrawIcon()");
     uint mask = 0xff000000;
     // Create image and copy data into image.
     QImage image(w, h, QImage::Format_ARGB32);
     if (!image.isNull()) { // failed to alloc?
         int bytes_per_line = w * sizeof(QRgb);
         for (int y=0; y < h; ++y) {
             QRgb *dest = (QRgb *) image.scanLine(y);
             const QRgb *src = (const QRgb *) (bits + y * bytes_per_line);
             for (int x=0; x < w; ++x) {
                 dest[x] = src[x];
             }
         }
     }
     if (!DrawIconEx( hdc, 0, 0, icon, w, h, 0, 0, DI_MASK))
         qWarning("QPixmap::fromWinHICON(), failed to DrawIcon()");
     if (!image.isNull()) { // failed to alloc?
         int bytes_per_line = w * sizeof(QRgb);
         for (int y=0; y < h; ++y) {
             QRgb *dest = (QRgb *) image.scanLine(y);
             const QRgb *src = (const QRgb *) (bits + y * bytes_per_line);
             for (int x=0; x < w; ++x) {
                 if (!src[x])
                     dest[x] = dest[x] | mask;
             }
         }
     }
     SelectObject(hdc, oldhdc); //restore state
     DeleteObject(winBitmap);
     DeleteDC(hdc);
     return QPixmap::fromImage(image);
 }
grabWidget() [1/2]
QPixmap QPixmap::grabWidget (QWidget * widget, const QRect & rectangle) static
Creates a pixmap and paints the given widget, restricted by the given rectangle, in it.
If the widget has any children, then they are also painted in the appropriate positions.
If no rectangle is specified (the default) the entire widget is painted.
If widget is 0, the specified rectangle doesn't overlap the widget's rectangle, or an error occurs, the function will return a null QPixmap. If the rectangle is a superset of the given widget, the areas outside the widget are covered with the widget's background.
This function actually asks widget to paint itself (and its children to paint themselves) by calling paintEvent() with painter redirection turned on. But QPixmap also provides the grabWindow() function which is a bit faster by grabbing pixels directly off the screen. In addition, if there are overlaying windows, grabWindow(), unlike grabWidget(), will see them.
Warning
Do not grab a widget from its QWidget::paintEvent(). However, it is safe to grab a widget from another widget's QWidget::paintEvent() .
See also
grabWindow()
Definition at line 1188 of file qpixmap.cpp.
Referenced by QAxServerBase::Draw(), QRollEffect::QRollEffect(), and QAlphaWidget::run().
 {
     if (!widget)
         return QPixmap();
     if (widget->testAttribute(Qt::WA_PendingResizeEvent) || !widget->testAttribute(Qt::WA_WState_Created))
         sendResizeEvents(widget);
     widget->d_func()->prepareToRender(QRegion(),
         QWidget::DrawWindowBackground | QWidget::DrawChildren | QWidget::IgnoreMask);
     QRect r(rect);
     if (r.width() < 0)
         r.setWidth(widget->width() - rect.x());
     if (r.height() < 0)
         r.setHeight(widget->height() - rect.y());
     if (!r.intersects(widget->rect()))
         return QPixmap();
     QPixmap res(r.size());
     if (!qt_widget_private(widget)->isOpaque)
         res.fill(Qt::transparent);
     widget->d_func()->render(&res, QPoint(), r, QWidget::DrawWindowBackground
                              | QWidget::DrawChildren | QWidget::IgnoreMask, true);
     return res;
 }
grabWidget() [2/2]
static QPixmap QPixmap::grabWidget (QWidget * widget, int x = 0, int y = 0, int w = -1, int h = -1) inline static
Definition at line 128 of file qpixmap.h.
     { return grabWidget(widget, QRect(x, y, w, h)); }
grabWindow()
QPixmap QPixmap::grabWindow (WId window, int x = 0, int y = 0, int w = -1, int h = -1) static
Creates and returns a pixmap constructed by grabbing the contents of the given window restricted by QRect(x, y, width, height).
The arguments ({x}, {y}) specify the offset in the window, whereas ({width}, {height}) specify the area to be copied. If width is negative, the function copies everything to the right border of the window. If height is negative, the function copies everything to the bottom of the window.
The window system identifier (WId) can be retrieved using the QWidget::winId() function. The rationale for using a window identifier and not a QWidget, is to enable grabbing of windows that are not part of the application, window system frames, and so on.
The grabWindow() function grabs pixels from the screen, not from the window, i.e. if there is another window partially or entirely over the one you grab, you get pixels from the overlying window, too. The mouse cursor is generally not grabbed.
Note on X11 that if the given window doesn't have the same depth as the root window, and another window partially or entirely obscures the one you grab, you will not get pixels from the overlying window. The contents of the obscured areas in the pixmap will be undefined and uninitialized.
On Windows Vista and above grabbing a layered window, which is created by setting the Qt::WA_TranslucentBackground attribute, will not work. Instead grabbing the desktop widget should work.
Warning
In general, grabbing an area outside the screen is not safe. This depends on the underlying window system.
See also
grabWidget(), {Screenshot Example}
Definition at line 972 of file qpixmap_mac.cpp.
Referenced by QWindowsVistaStyle::drawComplexControl(), QAlphaWidget::run(), QWhatsThat::showEvent(), and QX11PixmapData::transformed().
 {
     QWidget *widget = QWidget::find(window);
     if (widget == 0)
         return QPixmap();
     if(w == -1)
         w = widget->width() - x;
     if(h == -1)
         h = widget->height() - y;
     QPoint globalCoord(0, 0);
     globalCoord = widget->mapToGlobal(globalCoord);
     QRect rect(globalCoord.x() + x, globalCoord.y() + y, w, h);
 #ifdef QT_MAC_USE_COCOA
 #if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_6)
     if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_6)
         return qt_mac_grabScreenRect_10_6(rect);
     else
 #endif
         return qt_mac_grabScreenRect(rect);
 #else
 #if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_4)
     if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_4) {
         return qt_mac_grabScreenRect(rect);
     } else
 #endif
    {
         return qt_mac_grabScreenRect_10_3(x, y, w, h, widget);
    }
 #endif // ifdef Q_WS_MAC64
 }
handle()
Qt::HANDLE QPixmap::handle () const
Returns the pixmap's handle to the device context.
Note that, since QPixmap make use of Implicit {Data Sharing}{implicit data sharing}, the detach() function must be called explicitly to ensure that only this pixmap's data is modified if the pixmap data is shared.
Warning
This function is X11 specific; using it is non-portable.
Since 4.8, pixmaps do not have an X11 handle unless created with QPixmap::fromX11Pixmap() , or if the native graphics system is explicitly enabled.
See also
detach()
QApplication::setGraphicsSystem()
Definition at line 1299 of file qpixmap.cpp.
Referenced by QX11PixmapData::bitmap_to_mask(), QX11PaintEngine::drawPixmap(), QX11PaintEngine::drawTiledPixmap(), QX11GLWindowSurface::flush(), QX11WindowSurface::flush(), QRasterWindowSurface::flush(), QX11GLWindowSurface::grabWidget(), QX11WindowSurface::grabWidget(), QMeeGoLivePixmapData::handle(), QMeeGoLivePixmapData::initializeThroughEGLImage(), QX11PixmapData::mask_to_bitmap(), menuItemEntry(), QGLOverlayWidget::paintGL(), QCursor::QCursor(), qstring_to_xtp(), QX11GLWindowSurface::scroll(), QX11WindowSurface::scroll(), QX11WindowSurface::setGeometry(), QX11PixmapData::setMask(), QX11PixmapData::transformed(), QX11PaintEngine::updateBrush(), and QX11Data::xdndMimeDataForAtom().
 {
 #if defined(Q_WS_X11)
     const QPixmapData *pd = pixmapData();
     if (pd && pd->classId() == QPixmapData::X11Class)
         return static_cast<const QX11PixmapData*>(pd)->handle();
 #endif
     return 0;
 }
hasAlpha()
bool QPixmap::hasAlpha () const
Returns true if this pixmap has an alpha channel, or has a mask, otherwise returns false.
See also
hasAlphaChannel(), mask()
Definition at line 1938 of file qpixmap.cpp.
Referenced by QAlphaPaintEngine::drawPixmap(), QGL2PaintEngineEx::drawPixmap(), QGL2PaintEngineExPrivate::drawPixmapFragments(), QAlphaPaintEngine::drawTiledPixmap(), QX11PaintEngine::drawTiledPixmap(), QX11PaintEnginePrivate::fillPolygon_dev(), QStyleSheetBorderData::isOpaque(), QSplashScreen::setPixmap(), and QPainterPrivate::updateEmulationSpecifier().
 {
 #if defined(Q_WS_X11)
     if (data && data->hasAlphaChannel())
         return true;
     QPixmapData *pd = pixmapData();
     if (pd && pd->classId() == QPixmapData::X11Class) {
         QX11PixmapData *x11Data = static_cast<QX11PixmapData*>(pd);
 #ifndef QT_NO_XRENDER
         if (x11Data->picture && x11Data->d == 32)
             return true;
 #endif
         if (x11Data->d == 1 || x11Data->x11_mask)
             return true;
     }
     return false;
 #else
     return data && data->hasAlphaChannel();
 #endif
 }
hasAlphaChannel()
bool QPixmap::hasAlphaChannel () const
Returns true if the pixmap has a format that respects the alpha channel, otherwise returns false.
See also
hasAlpha()
Definition at line 1965 of file qpixmap.cpp.
Referenced by CapabilitiesToStateMask::canBlitterDrawPixmap(), depth(), QDirectFBPaintEngine::drawPixmap(), QPaintEngine::drawTiledPixmap(), fill(), QMeeGoLivePixmapData::initializeThroughEGLImage(), QBrush::isOpaque(), and qDrawPlainRect().
 {
     return data && data->hasAlphaChannel();
 }
height()
int QPixmap::height () const
Returns the height of the pixmap.
See also
size(), {QPixmap::Pixmap Information}{Pixmap Information}
Definition at line 645 of file qpixmap.cpp.
Referenced by QX11WindowSurface::beginPaint(), QX11PixmapData::bitmap_to_mask(), copy(), QXlibCursor::createCursorBitmap(), QOleDropSource::createCursors(), QWSDisplay::defineCursor(), depth(), QDragManager::drag(), QAxServerBase::Draw(), QTreeViewPrivate::drawAnimatedOperation(), QRenderRule::drawBackgroundImage(), QMacStylePrivate::drawCombobox(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), QDeclarativeTextPrivate::drawOutline(), QWin32PrintEngine::drawPixmap(), QCoreGraphicsPaintEngine::drawPixmap(), QGL2PaintEngineEx::drawPixmap(), QOpenGLPaintEngine::drawPixmap(), QPainter::drawPixmap(), QMacStylePrivate::drawTableHeader(), drawTextItemDecoration(), QPSPrintEngine::drawTiledPixmap(), QWin32PrintEngine::drawTiledPixmap(), QX11PaintEngine::drawTiledPixmap(), QOpenGLPaintEngine::drawTiledPixmap(), QPaintEngine::drawTiledPixmap(), QPainter::drawTiledPixmap(), QBlitterPaintEngine::fillRect(), QMacStylePrivate::generateBackgroundPattern(), getPixmapSize(), QDeclarativePixmap::height(), QMeeGoLivePixmapData::initializeThroughEGLImage(), QPixmapCache::insert(), QGLBlurTextureCache::insertBlurTextureInfo(), QStyle::itemPixmapRect(), QX11PixmapData::mask_to_bitmap(), menuItemEntry(), QColorWell::mouseMoveEvent(), QColorShowLabel::mouseMoveEvent(), QAxHostWidget::paintEvent(), QWizard::paintEvent(), QColorLuminancePicker::paintEvent(), QGLOverlayWidget::paintGL(), QMacStyle::polish(), QCursor::QCursor(), qDrawPlainRect(), qt_draw_tile(), qt_fill_tile(), qt_mac_cg_context(), qt_mac_draw_pattern(), QPixmapCache::replace(), scaled(), scaledToHeight(), setAlphaChannel(), QCursorData::setBitmap(), QShapedPixmapWidget::setPixmap(), QMacStyle::standardIconImplementation(), QWindowsMobileStyle::standardPixmap(), QGL2PaintEngineExPrivate::updateBrushTexture(), QGL2PaintEngineExPrivate::updateBrushUniforms(), QGLContextPrivate::updateFormatVersion(), QGLContext::updatePaintDevice(), and QGraphicsPixmapItemPrivate::updateShape().
 {
     return data ? data->height() : 0;
 }
init() [1/2]
void QPixmap::init (int w, int h, Type type = PixmapType) private
Definition at line 128 of file qpixmap.cpp.
Referenced by handle(), and QPixmap().
 {
     init(w, h, int(type));
 }
init() [2/2]
void QPixmap::init (int w, int h, int type) private
Definition at line 135 of file qpixmap.cpp.
 {
     if (qt_appType == QApplication::Tty) {
         qWarning("QPixmap: Cannot create a QPixmap when no GUI is being used");
         data = 0;
         return;
     }
     if ((w > 0 && h > 0) || type == QPixmapData::BitmapType)
         data = QPixmapData::create(w, h, (QPixmapData::PixelType) type);
     else
         data = 0;
 }
initAlphaPixmap()
void QPixmap::initAlphaPixmap (uchar * bytes, int length, struct tagBITMAPINFO * bmi) private
isDetached()
bool QPixmap::isDetached () const
Warning
This function is not part of the public interface.
Definition at line 1495 of file qpixmap.cpp.
Referenced by qIsDetached().
 {
     return data && data->ref == 1;
 }
isNull()
bool QPixmap::isNull () const
Returns true if this is a null pixmap; otherwise returns false.
A null pixmap has zero width, zero height and no contents. You cannot draw in a null pixmap.
Definition at line 615 of file qpixmap.cpp.
Referenced by _q_paintIntoCache(), QMessageBox::aboutQt(), QSvgIconEngine::actualSize(), QSvgIconEngine::addFile(), QPixmapIconEngine::addFile(), QIcon::addPixmap(), QPixmapIconEngine::addPixmap(), QCoreGraphicsPaintEngine::begin(), QPainter::begin(), QX11WindowSurface::beginPaint(), QPixmapIconEngine::bestMatch(), bestSizeMatch(), QX11PixmapData::bitmap_to_mask(), cacheKey(), convertFromImage(), copy(), create32BitCursor(), QOleDropSource::createCursors(), QSystemTrayIconSys::createIcon(), createPixmapDataSync(), depth(), QDragManager::drag(), QVGPixmapConvolutionFilter::draw(), QVGPixmapColorizeFilter::draw(), QVGPixmapDropShadowFilter::draw(), QVGPixmapBlurFilter::draw(), QPixmapConvolutionFilter::draw(), QPixmapBlurFilter::draw(), QGraphicsColorizeEffect::draw(), QPixmapColorizeFilter::draw(), QPixmapDropShadowFilter::draw(), QGraphicsBlurEffect::draw(), QGraphicsDropShadowEffect::draw(), QGraphicsOpacityEffect::draw(), QRenderRule::drawBackgroundImage(), QPlastiqueStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QStyleSheetStyle::drawControl(), QItemDelegate::drawDecoration(), QGraphicsScenePrivate::drawItemHelper(), QPdfEngine::drawPixmap(), QCoreGraphicsPaintEngine::drawPixmap(), QPainter::drawPixmap(), QPaintEngineEx::drawPixmapFragments(), QPainter::drawPixmapFragments(), QPlastiqueStyle::drawPrimitive(), QPainter::drawTiledPixmap(), fill(), QSystemTrayIconSys::findTrayGeometry(), QRenderRule::fixupBorder(), QX11GLWindowSurface::flush(), QX11WindowSurface::flush(), getPixmap(), getPixmapSize(), QFileIconProviderPrivate::getWinIcon(), QX11GLWindowSurface::grabWidget(), QX11WindowSurface::grabWidget(), handle(), QPixmapIconEngineEntry::isNull(), QFrameInfo::isValid(), QWizardPrivate::layoutInfoForCurrentPage(), QTextDocument::loadResource(), menuItemEntry(), operator<<(), QBitmap::operator=(), QBrush::operator==(), QDecorationWindows::paintButton(), QDecorationDefault::paintButton(), QWizard::paintEvent(), QSvgIconEngine::pixmap(), QGraphicsEffectSource::pixmap(), QPixmapIconEngine::pixmap(), QWizardPage::pixmap(), pixmapsAreEqual(), QStyleSheetStyle::polish(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), QCursor::QCursor(), QPixmapToIPicture(), QRegion::QRegion(), qstring_to_xtp(), qt_bitmapToRegion(), qt_createIcon(), qt_mac_create_iconref(), qt_mac_display_change_callbk(), qt_mac_set_app_icon(), qt_toRasterPixmap(), qt_toX11Pixmap(), save(), scaled(), scaledToHeight(), scaledToWidth(), QX11GLWindowSurface::scroll(), QX11WindowSurface::scroll(), scroll(), serialNumber(), setAlphaChannel(), QGL2PaintEngineExPrivate::setBrush(), QBrush::setColor(), QDrag::setDragCursor(), QX11WindowSurface::setGeometry(), QMacPixmapData::setMask(), QX11PixmapData::setMask(), setMask(), QDeclarativePixmap::setPixmap(), QShapedPixmapWidget::setPixmap(), QTexturedBrushData::setPixmap(), QBrush::setTexture(), QWizardHeader::setup(), QWorkspacePrivate::showMaximizeControls(), QSystemTrayIconPrivate::showMessage_sys(), QLabelPrivate::sizeForWidth(), QWindowsStyle::standardIconImplementation(), QCommonStyle::standardPixmap(), QWindowsStyle::standardPixmap(), toImage(), toWinHBITMAP(), toWinHICON(), transformed(), QCursorData::update(), QGraphicsPixmapItemPrivate::updateShape(), QPixmapIconEngine::virtual_hook(), and QPixmapIconEngine::write().
 {
     return !data || data->isNull();
 }
isQBitmap()
bool QPixmap::isQBitmap () const
Returns true if this is a QBitmap; otherwise returns false.
Definition at line 599 of file qpixmap.cpp.
Referenced by QAlphaPaintEngine::drawPixmap(), QEmulationPaintEngine::drawPixmap(), QGL2PaintEngineEx::drawPixmap(), QPainter::drawPixmap(), QEmulationPaintEngine::drawPixmapFragments(), QGL2PaintEngineExPrivate::drawPixmapFragments(), QAlphaPaintEngine::drawTiledPixmap(), QEmulationPaintEngine::drawTiledPixmap(), QPainter::drawTiledPixmap(), is_brush_transparent(), QBrush::isOpaque(), QGL2PaintEngineExPrivate::setBrush(), QCoreGraphicsPaintEnginePrivate::setFillBrush(), QOpenGLPaintEnginePrivate::setGradientOps(), QSpanData::setup(), and QGL2PaintEngineExPrivate::updateBrushUniforms().
 {
     return data->type == QPixmapData::BitmapType;
 }
load()
bool QPixmap::load (const QString & fileName, const char * format = 0, Qt::ImageConversionFlags flags = Qt::AutoColor)
Loads a pixmap from the file with the given fileName.
Returns true if the pixmap was successfully loaded; otherwise returns false.
The loader attempts to read the pixmap using the specified format. If the format is not specified (which is the default), the loader probes the file for a header to guess the file format.
The file name can either refer to an actual file on disk or to one of the application's embedded resources. See the Resource System overview for details on how to embed pixmaps and other resource files in the application's executable.
If the data needs to be modified to fit in a lower-resolution result (e.g. converting from 32-bit to 8-bit), use the flags to control the conversion.
Note that QPixmaps are automatically added to the QPixmapCache when loaded from a file; the key used is internal and can not be acquired.
See also
loadFromData(), {QPixmap::Reading and Writing Image Files}{Reading and Writing Image Files}
Definition at line 930 of file qpixmap.cpp.
Referenced by handle(), QBitmap::QBitmap(), and QPixmap().
 {
     if (fileName.isEmpty())
         return false;
     QFileInfo info(fileName);
     QString key = QLatin1Literal("qt_pixmap")
                   % info.absoluteFilePath()
                   % HexString<uint>(info.lastModified().toTime_t())
                   % HexString<quint64>(info.size())
                   % HexString<uint>(data ? data->pixelType() : QPixmapData::PixmapType);
     // Note: If no extension is provided, we try to match the
     // file against known plugin extensions
     if (!info.completeSuffix().isEmpty() && !info.exists())
         return false;
     if (QPixmapCache::find(key, *this))
         return true;
     QScopedPointer<QPixmapData> tmp(QPixmapData::create(0, 0, data ? data->type : QPixmapData::PixmapType));
     if (tmp->fromFile(fileName, format, flags)) {
         data = tmp.take();
         QPixmapCache::insert(key, *this);
         return true;
     }
     return false;
 }
loadFromData() [1/2]
bool QPixmap::loadFromData (const uchar * data, uint len, const char * format = 0, Qt::ImageConversionFlags flags = Qt::AutoColor)
Loads a pixmap from the len first bytes of the given binary data.
Returns true if the pixmap was loaded successfully; otherwise returns false.
The loader attempts to read the pixmap using the specified format. If the format is not specified (which is the default), the loader probes the file for a header to guess the file format.
If the data needs to be modified to fit in a lower-resolution result (e.g. converting from 32-bit to 8-bit), use the flags to control the conversion.
See also
load(), {QPixmap::Reading and Writing Image Files}{Reading and Writing Image Files}
Definition at line 979 of file qpixmap.cpp.
Referenced by QTextHtmlParserNode::applyBackgroundImage(), getPixmap(), handle(), and QTextDocument::loadResource().
 {
     if (len == 0 || buf == 0)
         return false;
     if (!data)
         data = QPixmapData::create(0, 0, QPixmapData::PixmapType);
     return data->fromData(buf, len, format, flags);
 }
loadFromData() [2/2]
bool QPixmap::loadFromData (const QByteArray & data, const char * format = 0, Qt::ImageConversionFlags flags = Qt::AutoColor) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Loads a pixmap from the binary data using the specified format and conversion flags.
Definition at line 312 of file qpixmap.h.
 {
     return loadFromData(reinterpret_cast<const uchar *>(buf.constData()), buf.size(), format, flags);
 }
mask()
QBitmap QPixmap::mask () const
Extracts a bitmap mask from the pixmap's alpha channel.
Warning
This is potentially an expensive operation. The mask of the pixmap is extracted dynamically from the pixeldata.
See also
setMask(), {QPixmap::Pixmap Information}{Pixmap Information}
Definition at line 2077 of file qpixmap.cpp.
Referenced by create32BitCursor(), fromWinHBITMAP(), fromWinHICON(), isServerProcess(), QCursor::QCursor(), qDrawPlainRect(), QShapedPixmapWidget::setPixmap(), toWinHICON(), and QGraphicsPixmapItemPrivate::updateShape().
 {
     return data ? data->mask() : QBitmap();
 }
metric()
int QPixmap::metric (PaintDeviceMetric metric) const protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QPaintDevice.
Definition at line 1973 of file qpixmap.cpp.
 {
     return data ? data->metric(metric) : 0;
 }
numCols()
int QPixmap::numCols () const
Warning
This function is not part of the public interface.
See also
colorCount()
Definition at line 125 of file qpixmap_qws.cpp.
 {
     return colorCount();
 }
operator QVariant()
QPixmap::operator QVariant () const
Returns the pixmap as a QVariant.
Definition at line 499 of file qpixmap.cpp.
 {
     return QVariant(QVariant::Pixmap, this);
 }
operator!()
bool QPixmap::operator! () const inline
Returns true if this is a null pixmap; otherwise returns false.
See also
isNull()
Definition at line 226 of file qpixmap.h.
 { return isNull(); }
operator=()
QPixmap & QPixmap::operator= (const QPixmap & pixmap)
Assigns the given pixmap to this pixmap and returns a reference to this pixmap.
See also
copy(), QPixmap()
Definition at line 471 of file qpixmap.cpp.
Referenced by QBitmap::clear(), handle(), QBitmap::operator=(), and QPixmap().
 {
     if (paintingActive()) {
         qWarning("QPixmap::operator=: Cannot assign to pixmap during painting");
         return *this;
     }
     if (pixmap.paintingActive()) {                // make a deep copy
         *this = pixmap.copy();
     } else {
         data = pixmap.data;
     }
     return *this;
 }
paintEngine()
QPaintEngine * QPixmap::paintEngine () const virtual
Warning
This function is not part of the public interface.
Implements QPaintDevice.
Definition at line 2059 of file qpixmap.cpp.
 {
     return data ? data->paintEngine() : 0;
 }
pixmapData()
QPixmapData * QPixmap::pixmapData () const
Warning
This function is not part of the public interface.
Definition at line 2277 of file qpixmap.cpp.
Referenced by QRasterPaintEngine::begin(), CapabilitiesToStateMask::canBlitterDrawPixmap(), CapabilitiesToStateMask::canBlitterDrawPixmapOpacity(), QDirectFBCursor::changeCursor(), depth(), detach(), QVGPixmapConvolutionFilter::draw(), QVGPixmapColorizeFilter::draw(), QVGPixmapDropShadowFilter::draw(), QVGPixmapBlurFilter::draw(), QVGCompositionHelper::drawCursorPixmap(), QVolatileImagePaintEngine::drawPixmap(), QDirectFBPaintEngine::drawPixmap(), QVGPaintEngine::drawPixmap(), QRasterPaintEngine::drawPixmap(), QVGPaintEngine::drawPixmapFragments(), QDirectFbBlitter::drawPixmapOpacity(), QDirectFBPaintEngine::drawTiledPixmap(), QDirectFBPaintEnginePrivate::drawTiledPixmap(), QRasterPaintEngine::drawTiledPixmap(), QDirectFBPaintEngine::fillRect(), QX11GLWindowSurface::grabWidget(), handle(), hasAlpha(), qPixmapToVGImage(), qt_directfb_surface_for_pixmap(), QVGPaintEnginePrivate::setBrush(), QX11WindowSurface::setGeometry(), and QMeeGoGraphicsSystem::updateEGLSharedImagePixmap().
 {
     if (data) {
         QPixmapData* pm = data.data();
         return pm->runtimeData() ? pm->runtimeData() : pm;
     }
     return 0;
 }
qwsBits()
const uchar * QPixmap::qwsBits () const
Warning
This function is not part of the public interface.
Since
4.1
Definition at line 140 of file qpixmap_qws.cpp.
 {
     if (data && data->classId() == QPixmapData::RasterClass) {
         const QRasterPixmapData *d = static_cast<const QRasterPixmapData*>(data.data());
         return d->image.bits();
     }
     return 0;
 }
qwsBytesPerLine()
int QPixmap::qwsBytesPerLine () const
Warning
This function is not part of the public interface.
Since
4.1
Definition at line 150 of file qpixmap_qws.cpp.
 {
     if (data && data->classId() == QPixmapData::RasterClass) {
         const QRasterPixmapData *d = static_cast<const QRasterPixmapData*>(data.data());
         return d->image.bytesPerLine();
     }
     return 0;
 }
rect()
QRect QPixmap::rect () const
Returns the pixmap's enclosing rectangle.
See also
{QPixmap::Pixmap Information}{Pixmap Information}
Definition at line 676 of file qpixmap.cpp.
Referenced by QMoviePrivate::_q_loadNextFrame(), _q_paintIntoCache(), QOleDropSource::createCursors(), QGLPixmapFilter< QPixmapBlurFilter >::draw(), QPixmapConvolutionFilter::draw(), QPixmapBlurFilter::draw(), QPixmapColorizeFilter::draw(), QGraphicsOpacityEffect::draw(), QTextImageHandler::drawObject(), QBlitterPaintEngine::drawPixmap(), QDirectFBPaintEngine::drawPixmap(), QPdfEngine::drawPixmap(), QRasterPaintEngine::drawPixmap(), QPaintEngineEx::drawPixmap(), QPainter::drawPixmap(), QPaintEngineEx::drawPixmapFragments(), QPainter::drawPixmapFragments(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), qDrawBorderPixmap(), qt_mac_draw_pattern(), QDeclarativePixmap::rect(), scroll(), and QLabelPrivate::sizeForWidth().
 {
     return data ? QRect(0, 0, data->width(), data->height()) : QRect();
 }
save() [1/2]
bool QPixmap::save (const QString & fileName, const char * format = 0, int quality = -1) const
Saves the pixmap to the file with the given fileName using the specified image file format and quality factor.
Returns true if successful; otherwise returns false.
The quality factor must be in the range [0,100] or -1. Specify 0 to obtain small compressed files, 100 for large uncompressed files, and -1 to use the default settings.
If format is 0, an image format will be chosen from fileName's suffix.
See also
{QPixmap::Reading and Writing Image Files}{Reading and Writing Image Files}
Definition at line 1016 of file qpixmap.cpp.
 {
     if (isNull())
         return false;                                // nothing to save
     QImageWriter writer(fileName, format);
     return doImageIO(&writer, quality);
 }
save() [2/2]
bool QPixmap::save (QIODevice * device, const char * format = 0, int quality = -1) const
This function writes a QPixmap to the given device using the specified image file format and quality factor.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This can be used, for example, to save a pixmap directly into a QByteArray:
        QPixmap pixmap;
        QByteArray bytes;
        QBuffer buffer(&bytes);
        buffer.open(QIODevice::WriteOnly);
        pixmap.save(&buffer, "PNG"); // writes pixmap into bytes in PNG format
Definition at line 1037 of file qpixmap.cpp.
 {
     if (isNull())
         return false;                                // nothing to save
     QImageWriter writer(device, format);
     return doImageIO(&writer, quality);
 }
scaled() [1/2]
QPixmap QPixmap::scaled (int w, int h, Qt::AspectRatioMode aspectMode = Qt::IgnoreAspectRatio, Qt::TransformationMode mode = Qt::FastTransformation) const inline
Definition at line 132 of file qpixmap.h.
Referenced by QGL2PaintEngineEx::drawPixmap(), QOpenGLPaintEngine::drawPixmap(), QGL2PaintEngineEx::drawPixmapFragments(), QPixmapIconEngine::pixmap(), QWidgetPrivate::setWindowIcon_sys(), and QGL2PaintEngineExPrivate::updateBrushTexture().
         { return scaled(QSize(w, h), aspectMode, mode); }
scaled() [2/2]
QPixmap QPixmap::scaled (const QSize & s, Qt::AspectRatioMode aspectMode = Qt::IgnoreAspectRatio, Qt::TransformationMode mode = Qt::FastTransformation) const
Definition at line 1603 of file qpixmap.cpp.
 {
     if (isNull()) {
         qWarning("QPixmap::scaled: Pixmap is a null pixmap");
         return QPixmap();
     }
     if (s.isEmpty())
         return QPixmap();
     QSize newSize = size();
     newSize.scale(s, aspectMode);
     newSize.rwidth() = qMax(newSize.width(), 1);
     newSize.rheight() = qMax(newSize.height(), 1);
     if (newSize == size())
         return *this;
     QTransform wm = QTransform::fromScale((qreal)newSize.width() / width(),
                                           (qreal)newSize.height() / height());
     QPixmap pix = transformed(wm, mode);
     return pix;
 }
scaledToHeight()
QPixmap QPixmap::scaledToHeight (int h, Qt::TransformationMode mode = Qt::FastTransformation) const
Definition at line 1673 of file qpixmap.cpp.
Referenced by QWindowsMobileStyle::standardPixmap().
 {
     if (isNull()) {
         qWarning("QPixmap::scaleHeight: Pixmap is a null pixmap");
         return copy();
     }
     if (h <= 0)
         return QPixmap();
     qreal factor = (qreal) h / height();
     QTransform wm = QTransform::fromScale(factor, factor);
     return transformed(wm, mode);
 }
scaledToWidth()
QPixmap QPixmap::scaledToWidth (int width, Qt::TransformationMode mode = Qt::FastTransformation) const
Returns a scaled copy of the image.
The returned image is scaled to the given width using the specified transformation mode. The height of the pixmap is automatically calculated so that the aspect ratio of the pixmap is preserved.
If width is 0 or negative, a null pixmap is returned.
See also
isNull(), {QPixmap::Pixmap Transformations}{Pixmap Transformations}
Definition at line 1642 of file qpixmap.cpp.
Referenced by QUrlModel::setUrl().
 {
     if (isNull()) {
         qWarning("QPixmap::scaleWidth: Pixmap is a null pixmap");
         return copy();
     }
     if (w <= 0)
         return QPixmap();
     qreal factor = (qreal) w / width();
     QTransform wm = QTransform::fromScale(factor, factor);
     return transformed(wm, mode);
 }
scroll() [1/2]
void QPixmap::scroll (int dx, int dy, int x, int y, int width, int height, QRegion * exposed = 0) inline
Since
4.6
This convenience function is equivalent to calling QPixmap::scroll(dx, dy, QRect(x, y, width, height), exposed).
See also
QWidget::scroll(), QGraphicsItem::scroll()
Definition at line 307 of file qpixmap.h.
Referenced by QGraphicsItem::scroll().
 {
     scroll(dx, dy, QRect(ax, ay, awidth, aheight), exposed);
 }
scroll() [2/2]
void QPixmap::scroll (int dx, int dy, const QRect & rect, QRegion * exposed = 0)
Scrolls the area rect of this pixmap by (dx, dy).
Since
4.6
The exposed region is left unchanged. You can optionally pass a pointer to an empty QRegion to get the region that is exposed by the scroll operation.
QPixmap pixmap("background.png");
QRegion exposed;
pixmap.scroll(10, 10, pixmap.rect(), &exposed);
You cannot scroll while there is an active painter on the pixmap.
See also
QWidget::scroll(), QGraphicsItem::scroll()
Definition at line 434 of file qpixmap.cpp.
 {
     if (isNull() || (dx == 0 && dy == 0))
         return;
     QRect dest = rect & this->rect();
     QRect src = dest.translated(-dx, -dy) & dest;
     if (src.isEmpty()) {
         if (exposed)
             *exposed += dest;
         return;
     }
     detach();
     if (!data->scroll(dx, dy, src)) {
         // Fallback
         QPixmap pix = *this;
         QPainter painter(&pix);
         painter.setCompositionMode(QPainter::CompositionMode_Source);
         painter.drawPixmap(src.translated(dx, dy), *this, src);
         painter.end();
         *this = pix;
     }
     if (exposed) {
         *exposed += dest;
         *exposed -= src.translated(dx, dy);
     }
 }
serialNumber()
int QPixmap::serialNumber () const
Returns a number that identifies the contents of this QPixmap object.
Use cacheKey() instead.
Warning
The serial number doesn't necessarily change when the pixmap is altered. This means that it may be dangerous to use it as a cache key. For caching pixmaps, we recommend using the QPixmapCache class whenever possible.
Definition at line 1122 of file qpixmap.cpp.
 {
     if (isNull())
         return 0;
     return data->serialNumber();
 }
setAlphaChannel()
void QPixmap::setAlphaChannel (const QPixmap & alphaChannel)
Sets the alpha channel of this pixmap to the given alphaChannel by converting the alphaChannel into 32 bit and using the intensity of the RGB pixel values.
The effect of this function is undefined when the pixmap is being painted on.
Warning
This is potentially an expensive operation. Most usecases for this function are covered by QPainter and compositionModes which will normally execute faster.
See also
alphaChannel(), {QPixmap::Pixmap Transformations}{Pixmap Transformations}
Definition at line 1999 of file qpixmap.cpp.
 {
     if (alphaChannel.isNull())
         return;
     if (paintingActive()) {
         qWarning("QPixmap::setAlphaChannel: "
                  "Cannot set alpha channel while pixmap is being painted on");
         return;
     }
     if (width() != alphaChannel.width() && height() != alphaChannel.height()) {
         qWarning("QPixmap::setAlphaChannel: "
                  "The pixmap and the alpha channel pixmap must have the same size");
         return;
     }
     detach();
     data->setAlphaChannel(alphaChannel);
 }
setMask()
void QPixmap::setMask (const QBitmap & mask)
Sets a mask bitmap.
This function merges the mask with the pixmap's alpha channel. A pixel value of 1 on the mask means the pixmap's pixel is unchanged; a value of 0 means the pixel is transparent. The mask must have the same size as this pixmap.
Setting a null mask resets the mask, leaving the previously transparent pixels black. The effect of this function is undefined when the pixmap is being painted on.
Warning
This is potentially an expensive operation.
See also
mask(), {QPixmap::Pixmap Transformations}{Pixmap Transformations}, QBitmap
Definition at line 822 of file qpixmap.cpp.
Referenced by QWindowsStyle::drawComplexControl(), QCursor::QCursor(), qDrawPlainRect(), and QX11PixmapData::transformed().
 {
     if (paintingActive()) {
         qWarning("QPixmap::setMask: Cannot set mask while pixmap is being painted on");
         return;
     }
     if (!mask.isNull() && mask.size() != size()) {
         qWarning("QPixmap::setMask() mask size differs from pixmap size");
         return;
     }
     if (isNull())
         return;
     if (static_cast<const QPixmap &>(mask).data == data) // trying to selfmask
        return;
     detach();
     data->setMask(mask);
 }
size()
QSize QPixmap::size () const
Returns the size of the pixmap.
See also
width(), height(), {QPixmap::Pixmap Information}{Pixmap Information}
Definition at line 661 of file qpixmap.cpp.
Referenced by QLabelPrivate::_q_movieUpdated(), QSvgIconEngine::actualSize(), QPixmapIconEngine::addFile(), QPixmapIconEngine::addPixmap(), QPixmapIconEngine::bestMatch(), bestSizeMatch(), QPaintBuffer::commandDescription(), QMdi::ControlLabel::ControlLabel(), create32BitCursor(), depth(), QPixmapDropShadowFilter::draw(), QRenderRule::drawBackgroundImage(), QRenderRule::drawBorderImage(), QStyleHelper::drawBorderPixmap(), QCommonStyle::drawControl(), QMacStyle::drawControl(), QItemDelegate::drawDecoration(), QPaintEngine::drawImage(), QGraphicsScenePrivate::drawItemHelper(), QStyle::drawItemPixmap(), QBlitterPaintEngine::drawPixmap(), QDirectFBPaintEngine::drawPixmap(), QWin32PrintEngine::drawPixmap(), QGL2PaintEngineEx::drawPixmap(), QOpenGLPaintEngine::drawPixmap(), QRasterPaintEngine::drawPixmap(), QPaintEngineEx::drawPixmap(), QPaintBufferEngine::drawPixmap(), QGL2PaintEngineEx::drawPixmapFragments(), QDirectFBPaintEngine::drawTiledPixmap(), QOpenGLPaintEngine::drawTiledPixmap(), QRasterPaintEngine::drawTiledPixmap(), QX11GLWindowSurface::flush(), QAccessibleDisplay::imageSize(), QStyledItemDelegate::initStyleOption(), QMoviePrivate::next(), QBitmap::operator=(), QItemDelegate::paint(), QGtkPainter::paintBox(), QGtkPainter::paintBoxGap(), QSvgIconEngine::pixmap(), QPixmapIconEngine::pixmap(), pixmapsAreEqual(), QGLPixmapConvolutionFilter::processGL(), QCursor::QCursor(), scaled(), QMacWindowSurface::scroll(), QCursorData::setBitmap(), QX11GLWindowSurface::setGeometry(), QMacWindowSurface::setGeometry(), QX11WindowSurface::setGeometry(), QRasterPixmapData::setMask(), QPixmapData::setMask(), setMask(), QCursor::setPos(), QWizardHeader::setup(), QMdi::ControlLabel::sizeHint(), toWinHICON(), QOpenGLPaintEnginePrivate::updateFragmentProgramData(), and QPixmapIconEngine::virtual_hook().
 {
     return data ? QSize(data->width(), data->height()) : QSize(0, 0);
 }
swap()
void QPixmap::swap (QPixmap & other) inline
Swaps pixmap other with this pixmap.
Since
4.8
This operation is very fast and never fails.
Definition at line 90 of file qpixmap.h.
Referenced by QBitmap::swap().
 { qSwap(data, other.data); }
toImage()
QImage QPixmap::toImage () const
Converts the pixmap to a QImage.
Returns a null image if the conversion fails.
If the pixmap has 1-bit depth, the returned image will also be 1 bit deep. Images with more bits will be returned in a format closely represents the underlying system. Usually this will be QImage::Format_ARGB32_Premultiplied for pixmaps with an alpha and QImage::Format_RGB32 or QImage::Format_RGB16 for pixmaps without alpha.
Note that for the moment, alpha masks on monochrome images are ignored.
See also
fromImage(), {QImage::Image Formats}{Image Formats}
Definition at line 542 of file qpixmap.cpp.
Referenced by QPdfEnginePrivate::addBrushPattern(), QFontEngineXLFD::addOutlineToPath(), QFontEngineXLFD::alphaMapForGlyph(), QPlatformSoftwareCursor::changeCursor(), create32BitCursor(), QXlibCursor::createCursorBitmap(), createHeuristicMask(), createMaskFromColor(), darkenPixmap(), QWSDisplay::defineCursor(), doImageIO(), QPixmapConvolutionFilter::draw(), QPixmapBlurFilter::draw(), QPixmapColorizeFilter::draw(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QMacStylePrivate::drawColorlessButton(), QCommonStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QVGCompositionHelper::drawCursorPixmap(), QPdfEngine::drawPixmap(), QOpenGLPaintEngine::drawPixmap(), QSvgPaintEngine::drawPixmap(), QRasterPaintEngine::drawPixmap(), QOpenGLPaintEngine::drawTiledPixmap(), QRasterPaintEngine::drawTiledPixmap(), QWindowsMobileStyle::generatedIconPixmap(), QCommonStyle::generatedIconPixmap(), QMacStyle::generatedIconPixmap(), QMoviePrivate::next(), operator<<(), QBitmap::operator=(), pixmapsAreEqual(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), QTest::qCompare(), QCursor::QCursor(), qstring_to_xtp(), qt_bitmapToRegion(), qt_createIconMask(), qt_mac_create_iconref(), qt_toRasterPixmap(), qt_toX11Pixmap(), QAlphaWidget::run(), QItemDelegate::selected(), QRasterPixmapData::setAlphaChannel(), QX11PixmapData::setAlphaChannel(), QVolatileImage::setAlphaChannel(), QPixmapData::setAlphaChannel(), QRasterPixmapData::setMask(), QPixmapData::setMask(), QCursor::setPos(), QSystemTrayIconPrivate::showMessage_sys(), QMacStyle::styleHint(), QX11PixmapData::toImage(), toWinHBITMAP(), QX11Data::xdndMimeConvertToFormat(), and QX11Data::xdndMimeDataForAtom().
 {
     if (isNull())
         return QImage();
     return data->toImage();
 }
toMacCGImageRef()
CGImageRef QPixmap::toMacCGImageRef () const
Creates a CGImageRef equivalent to the QPixmap.
Since
4.2
Returns the CGImageRef handle.
It is the caller's responsibility to release the CGImageRef data after use.
Warning
This function is only available on Mac OS X.
See also
fromMacCGImageRef()
Definition at line 1254 of file qpixmap_mac.cpp.
Referenced by QCoreGraphicsPaintEngine::drawPixmap(), QMacWindowSurface::flush(), qt_mac_create_nsimage(), and QMacWindowSurface::scroll().
 {
     return (CGImageRef)macCGHandle();
 }
toWinHBITMAP()
HBITMAP QPixmap::toWinHBITMAP (HBitmapFormat format = NoAlpha) const
It is the caller's responsibility to free the HBITMAP data after use.
Win32 only: Creates a HBITMAP equivalent to the QPixmap, based on the given format. Returns the HBITMAP handle.
Warning
This function is only available on Windows.
See also
fromWinHBITMAP(), {QPixmap::Pixmap Conversion}{Pixmap Conversion}
Definition at line 122 of file qpixmap_win.cpp.
Referenced by create32BitCursor(), QAxServerBase::Draw(), QWin32PrintEngine::drawPixmap(), QWin32PrintEngine::drawTiledPixmap(), QAxHostWidget::paintEvent(), QPixmapToIPicture(), and toWinHICON().
 {
     if (isNull())
         return 0;
     HBITMAP bitmap = 0;
     if (data->classId() == QPixmapData::RasterClass) {
         QRasterPixmapData* d = static_cast<QRasterPixmapData*>(data.data());
         int w = d->image.width();
         int h = d->image.height();
         HDC display_dc = GetDC(0);
         // Define the header
         BITMAPINFO bmi;
         memset(&bmi, 0, sizeof(bmi));
         bmi.bmiHeader.biSize        = sizeof(BITMAPINFOHEADER);
         bmi.bmiHeader.biWidth       = w;
         bmi.bmiHeader.biHeight      = -h;
         bmi.bmiHeader.biPlanes      = 1;
         bmi.bmiHeader.biBitCount    = 32;
         bmi.bmiHeader.biCompression = BI_RGB;
         bmi.bmiHeader.biSizeImage   = w * h * 4;
         // Create the pixmap
         uchar *pixels = 0;
         bitmap = CreateDIBSection(display_dc, &bmi, DIB_RGB_COLORS, (void **) &pixels, 0, 0);
         ReleaseDC(0, display_dc);
         if (!bitmap) {
             qErrnoWarning("QPixmap::toWinHBITMAP(), failed to create dibsection");
             return 0;
         }
         if (!pixels) {
             qErrnoWarning("QPixmap::toWinHBITMAP(), did not allocate pixel data");
             return 0;
         }
         // Copy over the data
         QImage::Format imageFormat = QImage::Format_ARGB32;
         if (format == NoAlpha)
             imageFormat = QImage::Format_RGB32;
         else if (format == PremultipliedAlpha)
             imageFormat = QImage::Format_ARGB32_Premultiplied;
         const QImage image = d->image.convertToFormat(imageFormat);
         int bytes_per_line = w * 4;
         for (int y=0; y<h; ++y)
             memcpy(pixels + y * bytes_per_line, image.scanLine(y), bytes_per_line);
     } else {
         QPixmapData *data = new QRasterPixmapData(depth() == 1 ?
                                                   QPixmapData::BitmapType : QPixmapData::PixmapType);
         data->fromImage(toImage(), Qt::AutoColor);
         return QPixmap(data).toWinHBITMAP(format);
     }
     return bitmap;
 }
toWinHICON()
HICON QPixmap::toWinHICON () const
Returns the HICON handle.
Since
4.6
Win32 only: Creates a HICON equivalent to the QPixmap.
It is the caller's responsibility to free the HICON data after use.
Warning
This function is only available on Windows.
See also
fromWinHICON(), {QPixmap::Pixmap Conversion}{Pixmap Conversion}
Definition at line 257 of file qpixmap_win.cpp.
Referenced by QSystemTrayIconSys::createIcon(), QVistaHelper::drawTitleBar(), QSystemTrayIconSys::findTrayGeometry(), and qt_createIcon().
 {
     QBitmap maskBitmap = mask();
     if (maskBitmap.isNull()) {
         maskBitmap= QBitmap(size());
         maskBitmap.fill(Qt::color1);
     }
     ICONINFO ii;
     ii.fIcon    = true;
     ii.hbmMask  = qt_createIconMask(maskBitmap);
     ii.hbmColor = toWinHBITMAP(QPixmap::Alpha);
     ii.xHotspot = 0;
     ii.yHotspot = 0;
     HICON hIcon = CreateIconIndirect(&ii);
     DeleteObject(ii.hbmColor);
     DeleteObject(ii.hbmMask);
     return hIcon;
 }
transformed() [1/2]
QPixmap QPixmap::transformed (const QMatrix & matrix, Qt::TransformationMode mode = Qt::FastTransformation) const
This convenience function loads the matrix into a QTransform and calls the overloaded function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1723 of file qpixmap.cpp.
Referenced by QBitmap::clear(), QWin32PrintEngine::drawPixmap(), scaled(), scaledToHeight(), scaledToWidth(), and QBitmap::transformed().
 {
     return transformed(QTransform(matrix), mode);
 }
transformed() [2/2]
QPixmap QPixmap::transformed (const QTransform & transform, Qt::TransformationMode mode = Qt::FastTransformation) const
Returns a copy of the pixmap that is transformed using the given transformation transform and transformation mode.
The original pixmap is not changed.
The transformation transform is internally adjusted to compensate for unwanted translation; i.e. the pixmap produced is the smallest pixmap that contains all the transformed points of the original pixmap. Use the trueMatrix() function to retrieve the actual matrix used for transforming the pixmap.
This function is slow because it involves transformation to a QImage, non-trivial computations and a transformation back to a QPixmap.
See also
trueMatrix(), {QPixmap::Pixmap Transformations}{Pixmap Transformations}
Definition at line 1705 of file qpixmap.cpp.
 {
     if (isNull() || transform.type() <= QTransform::TxTranslate)
         return *this;
     return data->transformed(transform, mode);
 }
trueMatrix() [1/2]
QMatrix QPixmap::trueMatrix (const QMatrix & m, int w, int h) static
This convenience function loads the matrix m into a QTransform and calls the overloaded function with the QTransform and the width w and the height h.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 584 of file qpixmap.cpp.
Referenced by QWin32PrintEngine::drawPixmap(), QMacPixmapData::macCreatePixels(), and QX11PixmapData::transformed().
 {
     return trueMatrix(QTransform(m), w, h).toAffine();
 }
trueMatrix() [2/2]
QTransform QPixmap::trueMatrix (const QTransform & matrix, int width, int height) static
Returns the actual matrix used for transforming a pixmap with the given width, height and matrix.
When transforming a pixmap using the transformed() function, the transformation matrix is internally adjusted to compensate for unwanted translation, i.e. transformed() returns the smallest pixmap containing all transformed points of the original pixmap. This function returns the modified matrix, which maps points correctly from the original pixmap into the new pixmap.
See also
transformed(), {QPixmap::Pixmap Transformations}{Pixmap Transformations}
Definition at line 569 of file qpixmap.cpp.
 {
     return QImage::trueMatrix(m, w, h);
 }
width()
int QPixmap::width () const
Returns the width of the pixmap.
See also
size(), {QPixmap::Pixmap Information}{Pixmap Information}
Definition at line 630 of file qpixmap.cpp.
Referenced by QX11WindowSurface::beginPaint(), QX11PixmapData::bitmap_to_mask(), copy(), QXlibCursor::createCursorBitmap(), QOleDropSource::createCursors(), QWSDisplay::defineCursor(), depth(), QDragManager::drag(), QAxServerBase::Draw(), QTreeViewPrivate::drawAnimatedOperation(), QRenderRule::drawBackgroundImage(), QMacStylePrivate::drawCombobox(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), QDeclarativeTextPrivate::drawOutline(), QWin32PrintEngine::drawPixmap(), QCoreGraphicsPaintEngine::drawPixmap(), QGL2PaintEngineEx::drawPixmap(), QOpenGLPaintEngine::drawPixmap(), QPainter::drawPixmap(), QMacStylePrivate::drawTableHeader(), QPSPrintEngine::drawTiledPixmap(), QWin32PrintEngine::drawTiledPixmap(), QX11PaintEngine::drawTiledPixmap(), QOpenGLPaintEngine::drawTiledPixmap(), QPaintEngine::drawTiledPixmap(), QPainter::drawTiledPixmap(), QBlitterPaintEngine::fillRect(), QMacStylePrivate::generateBackgroundPattern(), getPixmapSize(), QMeeGoLivePixmapData::initializeThroughEGLImage(), QPixmapCache::insert(), QGLBlurTextureCache::insertBlurTextureInfo(), QStyle::itemPixmapRect(), QX11PixmapData::mask_to_bitmap(), menuItemEntry(), QColorWell::mouseMoveEvent(), QColorShowLabel::mouseMoveEvent(), QGtkPainter::paintBox(), QGtkPainter::paintBoxGap(), QAxHostWidget::paintEvent(), QColorLuminancePicker::paintEvent(), QGLOverlayWidget::paintGL(), QMacStyle::polish(), QCursor::QCursor(), qDrawPlainRect(), qt_draw_tile(), qt_fill_tile(), qt_mac_draw_pattern(), QPixmapCache::replace(), scaled(), scaledToWidth(), setAlphaChannel(), QCursorData::setBitmap(), QShapedPixmapWidget::setPixmap(), QMacStyle::standardIconImplementation(), QGL2PaintEngineExPrivate::updateBrushTexture(), QGL2PaintEngineExPrivate::updateBrushUniforms(), QGLContextPrivate::updateFormatVersion(), QGLContext::updatePaintDevice(), QGraphicsPixmapItemPrivate::updateShape(), and QDeclarativePixmap::width().
 {
     return data ? data->width() : 0;
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & stream, const QPixmap & pixmap) related
Writes the given pixmap to the given stream as a PNG image.
Note that writing the stream to a file will not produce a valid image file.
See also
QPixmap::save(), {Serializing Qt Data Types}
Definition at line 1430 of file qpixmap.cpp.
 {
     return stream << pixmap.toImage();
 }
operator>>
QDataStream & operator>> (QDataStream & stream, QPixmap & pixmap) friend
Reads an image from the given stream into the given pixmap.
See also
QPixmap::load(), {Serializing Qt Data Types}
Definition at line 1446 of file qpixmap.cpp.
 {
     QImage image;
     stream >> image;
     if (image.isNull()) {
         pixmap = QPixmap();
     } else if (image.depth() == 1) {
         pixmap = QBitmap::fromImage(image);
     } else {
         pixmap = QPixmap::fromImage(image);
     }
     return stream;
 }
QBitmap
friend class QBitmap friend
Definition at line 279 of file qpixmap.h.
Referenced by QBitmap::clear(), mask(), and toWinHICON().
QCoreGraphicsPaintEngine
friend class QCoreGraphicsPaintEngine friend
Definition at line 284 of file qpixmap.h.
QGLWidget
friend class QGLWidget friend
Definition at line 282 of file qpixmap.h.
QMacPixmapData
friend class QMacPixmapData friend
Definition at line 277 of file qpixmap.h.
QPaintDevice
friend class QPaintDevice friend
Definition at line 280 of file qpixmap.h.
QPainter
friend class QPainter friend
Definition at line 281 of file qpixmap.h.
QPixmapData
friend class QPixmapData friend
Definition at line 275 of file qpixmap.h.
QRasterBuffer
friend class QRasterBuffer friend
Definition at line 286 of file qpixmap.h.
QSymbianRasterPixmapData
friend class QSymbianRasterPixmapData friend
Definition at line 278 of file qpixmap.h.
qt_mac_cg_context
CGContextRef qt_mac_cg_context (const QPaintDevice *) friend
Returns the CoreGraphics CGContextRef of the paint device.
Warning
This function is not part of the public interface.
0 is returned if it can't be obtained. It is the caller's responsiblity to CGContextRelease the context when finished using it.
Warning
This function is only available on Mac OS X.
Definition at line 118 of file qpaintdevice_mac.cpp.
 {
     if (pdev->devType() == QInternal::Pixmap) {
         const QPixmap *pm = static_cast<const QPixmap*>(pdev);
         CGColorSpaceRef colorspace = qt_mac_colorSpaceForDeviceType(pdev);
         uint flags = kCGImageAlphaPremultipliedFirst;
 #ifdef kCGBitmapByteOrder32Host //only needed because CGImage.h added symbols in the minor version
         flags |= kCGBitmapByteOrder32Host;
 #endif
         CGContextRef ret = 0;
         // It would make sense to put this into a mac #ifdef'ed
         // virtual function in the QPixmapData at some point
         if (pm->data->classId() == QPixmapData::MacClass) {
             const QMacPixmapData *pmData = static_cast<const QMacPixmapData*>(pm->data.data());
             ret = CGBitmapContextCreate(pmData->pixels, pmData->w, pmData->h,
                                                      8, pmData->bytesPerRow, colorspace,
                                                      flags);
             if(!ret)
                 qWarning("QPaintDevice: Unable to create context for pixmap (%d/%d/%d)",
                          pmData->w, pmData->h, (pmData->bytesPerRow * pmData->h));
         } else if (pm->data->classId() == QPixmapData::RasterClass) {
             QImage *image = pm->data->buffer();
             ret = CGBitmapContextCreate(image->bits(), image->width(), image->height(),
                                         8, image->bytesPerLine(), colorspace, flags);
         }
         CGContextTranslateCTM(ret, 0, pm->height());
         CGContextScaleCTM(ret, 1, -1);
         return ret;
     } else if (pdev->devType() == QInternal::Widget) {
         CGContextRef ret = static_cast<CGContextRef>(static_cast<const QWidget *>(pdev)->macCGHandle());
         CGContextRetain(ret);
         return ret;
     } else if (pdev->devType() == QInternal::MacQuartz) {
         return static_cast<const QMacQuartzPaintDevice *>(pdev)->cgContext();
     }
     return 0;
 }
qt_mac_create_iconref
IconRef qt_mac_create_iconref (const QPixmap &) friend
Definition at line 1109 of file qpixmap_mac.cpp.
 {
     if (px.isNull())
         return 0;
     //create icon
     IconFamilyHandle iconFamily = reinterpret_cast<IconFamilyHandle>(NewHandle(0));
     //create data
     {
         struct {
             OSType mac_type;
             int width, height, depth;
             bool mask;
         } images[] = {
             { kThumbnail32BitData, 128, 128, 32, false },
             { kThumbnail8BitMask, 128, 128, 8, true },
             { 0, 0, 0, 0, false } //end marker
         };
         for(int i = 0; images[i].mac_type; i++) {
             //get QPixmap data
             QImage scaled_px = px.toImage().scaled(images[i].width, images[i].height);
             quint32 *sptr = (quint32 *) scaled_px.bits();
             quint32 *srow;
             uint sbpr = scaled_px.bytesPerLine();
             //get Handle data
             const int dbpr = images[i].width * (images[i].depth/8);
             Handle hdl = NewHandle(dbpr*images[i].height);
             if(!sptr) { //handle null pixmap
                 memset((*hdl), '\0', dbpr*images[i].height);
             } else if(images[i].mask) {
                 if(images[i].mac_type == kThumbnail8BitMask) {
                     for(int y = 0, hindex = 0; y < images[i].height; ++y) {
                         srow = sptr + (y * (sbpr/4));
                         for(int x = 0; x < images[i].width; ++x)
                             *((*hdl)+(hindex++)) = qAlpha(*(srow+x));
                     }
                 }
             } else {
                 char *dest = (*hdl);
 #if defined(__i386__)
                 if(images[i].depth == 32) {
                     for(int y = 0; y < images[i].height; ++y) {
                         uint *source = (uint*)((const uchar*)sptr+(sbpr*y));
                         for(int x = 0; x < images[i].width; ++x, dest += 4)
                             *((uint*)dest) = CFSwapInt32(*(source + x));
                     }
                 } else
 #endif
                 {
                     for(int y = 0; y < images[i].height; ++y)
                         memcpy(dest+(y*dbpr), ((const uchar*)sptr+(sbpr*y)), dbpr);
                 }
             }
             //set the family data to the Handle
             OSStatus set = SetIconFamilyData(iconFamily, images[i].mac_type, hdl);
             if(set != noErr)
                 qWarning("%s: %d -- Unable to create icon data[%d]!! %ld",
                          __FILE__, __LINE__, i, long(set));
             DisposeHandle(hdl);
         }
     }
     //acquire and cleanup
     IconRef ret;
     static int counter = 0;
     const OSType kQtCreator = 'CUTE';
     RegisterIconRefFromIconFamily(kQtCreator, (OSType)counter, iconFamily, &ret);
     AcquireIconRef(ret);
     UnregisterIconRef(kQtCreator, (OSType)counter);
     DisposeHandle(reinterpret_cast<Handle>(iconFamily));
     counter++;
     return ret;
 }
qt_mac_create_imagemask
CGImageRef qt_mac_create_imagemask (const QPixmap & , const QRectF &) friend
Definition at line 1077 of file qpixmap_mac.cpp.
 {
     QMacPixmapData *px = static_cast<QMacPixmapData*>(pixmap.data.data());
     if (px->cg_mask) {
         if (px->cg_mask_rect == sr) {
             CGImageRetain(px->cg_mask); //reference for the caller
             return px->cg_mask;
         }
         CGImageRelease(px->cg_mask);
         px->cg_mask = 0;
     }
     const int sx = qRound(sr.x()), sy = qRound(sr.y()), sw = qRound(sr.width()), sh = qRound(sr.height());
     const int sbpr = px->bytesPerRow;
     const uint nbytes = sw * sh;
     //  alpha is always 255 for bitmaps, ignore it in this case.
     const quint32 mask = px->depth() == 1 ? 0x00ffffff : 0xffffffff;
     quint8 *dptr = static_cast<quint8 *>(malloc(nbytes));
     quint32 *sptr = px->pixels, *srow;
     for(int y = sy, offset=0; y < sh; ++y) {
         srow = sptr + (y * (sbpr / 4));
         for(int x = sx; x < sw; ++x)
             *(dptr+(offset++)) = (*(srow+x) & mask) ? 255 : 0;
     }
     QCFType<CGDataProviderRef> provider = CGDataProviderCreateWithData(0, dptr, nbytes, qt_mac_cgimage_data_free);
     px->cg_mask = CGImageMaskCreate(sw, sh, 8, 8, nbytes / sh, provider, 0, 0);
     px->cg_mask_rect = sr;
     CGImageRetain(px->cg_mask); //reference for the caller
     return px->cg_mask;
 }
qt_mac_pixmap_get_base
quint32* qt_mac_pixmap_get_base (const QPixmap *) friend
Definition at line 75 of file qpixmap_mac.cpp.
 {
     if (QApplicationPrivate::graphics_system_name == QLatin1String("raster"))
         return reinterpret_cast<quint32 *>(static_cast<QRasterPixmapData*>(pix->data.data())->buffer()->bits());
     else
         return static_cast<QMacPixmapData*>(pix->data.data())->pixels;
 }
qt_mac_pixmap_get_bytes_per_line
int qt_mac_pixmap_get_bytes_per_line (const QPixmap *) friend
Definition at line 83 of file qpixmap_mac.cpp.
 {
     if (QApplicationPrivate::graphics_system_name == QLatin1String("raster"))
         return static_cast<QRasterPixmapData*>(pix->data.data())->buffer()->bytesPerLine();
     else
         return static_cast<QMacPixmapData*>(pix->data.data())->bytesPerRow;
 }
qt_pixmap_id
Q_GUI_EXPORT qint64 qt_pixmap_id (const QPixmap & pixmap) friend
Definition at line 94 of file qpixmap.cpp.
 {
     return pixmap.cacheKey();
 }
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 285 of file qpixmap.h.
QX11PaintEngine
friend class QX11PaintEngine friend
Definition at line 283 of file qpixmap.h.
QX11PixmapData
friend class QX11PixmapData friend
Definition at line 276 of file qpixmap.h.
Properties
data
QExplicitlySharedDataPointer<QPixmapData> QPixmap::data private
Definition at line 252 of file qpixmap.h.
Referenced by alphaChannel(), QX11PaintEngine::begin(), cacheKey(), clut(), colorCount(), convertFromImage(), copy(), depth(), detach(), QX11PaintEngine::drawPixmap(), QX11PaintEngine::drawTiledPixmap(), fill(), QBitmap::fromImage(), fromImage(), fromImageReader(), fromWinHBITMAP(), handle(), hasAlpha(), hasAlphaChannel(), height(), init(), isDetached(), isNull(), isQBitmap(), load(), loadFromData(), mask(), metric(), operator=(), paintEngine(), pixmapData(), QPixmap(), qstring_to_xtp(), qt_mac_cg_context(), qt_mac_create_imagemask(), qt_mac_pixmap_get_base(), qt_mac_pixmap_get_bytes_per_line(), qwsBits(), qwsBytesPerLine(), rect(), scroll(), serialNumber(), QMacPixmapData::setAlphaChannel(), setAlphaChannel(), setMask(), size(), swap(), toImage(), toWinHBITMAP(), toWinHICON(), transformed(), width(), and ~QPixmap().
The documentation for this class was generated from the following files:
/src/gui/image/qpixmap.h
/src/gui/image/qpixmap.cpp
/src/gui/image/qpixmap_mac.cpp
/src/gui/image/qpixmap_qpa.cpp
/src/gui/image/qpixmap_qws.cpp
/src/gui/image/qpixmap_win.cpp
/src/gui/image/qpixmap_x11.cpp
/src/gui/kernel/qwidget.cpp