Qt 4.8: QAxBindable Class Reference
QAxBindable Class Reference
The QAxBindable class provides an interface between a QWidget and an ActiveX client.
#include <qaxbindable.h>
Public Functions
virtual QAxAggregated * createAggregate ()
Reimplement this function when you want to implement additional COM interfaces in the ActiveX control, or when you want to provide alternative implementations of COM interfaces.
QAxBindable ()
Constructs an empty QAxBindable object.
virtual bool readData (QIODevice *source, const QString &format)
If the COM object supports a MIME type then this function is called to initialize the COM object from the data source in format.
void reportError (int code, const QString &src, const QString &desc, const QString &help=QString())
Reports an error to the client application.
virtual bool writeData (QIODevice *sink)
If the COM object supports a MIME type then this function is called to store the COM object into sink.
virtual ~QAxBindable ()
Destroys the QAxBindable object.
Protected Functions
IUnknown * clientSite () const
Returns a pointer to the client site interface for this ActiveX object, or null if no client site has been set.
void propertyChanged (const char *property)
Call this function to notify the client that is hosting this ActiveX control that the property property has been changed.
bool requestPropertyChange (const char *property)
Call this function to request permission to change the property property from the client that is hosting this ActiveX control.
Properties
IAxServerBase * activex
Friends
class QAxServerBase
Detailed Description
The QAxBindable class provides an interface between a QWidget and an ActiveX client.
Attention
Module: QAxServer
The functions provided by this class allow an ActiveX control to communicate property changes to a client application. Inherit your control class from both QWidget (directly or indirectly) and this class to get access to this class's functions. The meta-object compiler requires you to inherit from QWidget first.
class MyActiveX : public QWidget, public QAxBindable
{
    Q_OBJECT
    Q_PROPERTY(int value READ value WRITE setValue)
public:
    MyActiveX(QWidget *parent = 0);
    ...
    int value() const;
    void setValue(int);
};
When implementing the property write function, use requestPropertyChange() to get permission from the ActiveX client application to change this property. When the property changes, call propertyChanged() to notify the ActiveX client application about the change. If a fatal error occurs in the control, use the static reportError() function to notify the client.
Use the interface returned by clientSite() to call the ActiveX client. To implement additional COM interfaces in your ActiveX control, reimplement createAggregate() to return a new object of a QAxAggregated subclass.
The ActiveQt OpenGL example shows how to use QAxBindable to implement additional COM interfaces.
See also
QAxAggregated, QAxFactory, {ActiveQt Framework}
Definition at line 60 of file qaxbindable.h.
Constructors and Destructors
QAxBindable()
QAxBindable::QAxBindable ()
Constructs an empty QAxBindable object.
Definition at line 92 of file qaxbindable.cpp.
 :activex(0)
 {
 }
~QAxBindable()
QAxBindable::~QAxBindable () virtual
Destroys the QAxBindable object.
Definition at line 100 of file qaxbindable.cpp.
 {
 }
Functions
clientSite()
IUnknown * QAxBindable::clientSite () const protected
Returns a pointer to the client site interface for this ActiveX object, or null if no client site has been set.
Call QueryInterface() on the returned interface to get the interface you want to call.
Definition at line 149 of file qaxbindable.cpp.
 {
     if (!activex)
         return 0;
     return activex->clientSite();
 }
createAggregate()
QAxAggregated * QAxBindable::createAggregate () virtual
Reimplement this function when you want to implement additional COM interfaces in the ActiveX control, or when you want to provide alternative implementations of COM interfaces.
Return a new object of a QAxAggregated subclass.
The default implementation returns the null pointer.
Definition at line 165 of file qaxbindable.cpp.
Referenced by QAxServerBase::internalBind().
 {
     return 0;
 }
propertyChanged()
void QAxBindable::propertyChanged (const char * property) protected
Call this function to notify the client that is hosting this ActiveX control that the property property has been changed.
This function is usually called at the end of the property's write function.
See also
requestPropertyChange()
Definition at line 134 of file qaxbindable.cpp.
 {
     if (!activex)
         return;
     activex->emitPropertyChanged(property);
 }
readData()
bool QAxBindable::readData (QIODevice * source, const QString & format) virtual
If the COM object supports a MIME type then this function is called to initialize the COM object from the data source in format.
Since
4.1
You have to open source for reading before you can read from it.
Returns true to indicate success. If the function returns false, then ActiveQt will process the data by setting the properties through the meta object system.
If you reimplement this function you also have to implement writeData(). The default implementation does nothing and returns false.
Warning
ActiveX controls embedded in HTML can use either the type and data attribute of the object tag to read data, or use a list of param tags to initialize properties. If param tags are used, then Internet Explorer will ignore the data attribute, and readData will not be called.
See also
writeData()
Definition at line 214 of file qaxbindable.cpp.
Referenced by QAxServerBase::Load().
 {
     Q_UNUSED(source);
     Q_UNUSED(format);
     return false;
 }
reportError()
void QAxBindable::reportError (int code, const QString & src, const QString & desc, const QString & context = QString())
Reports an error to the client application.
code is a control-defined error code. desc is a human-readable description of the error intended for the application user. src is the name of the source for the error, typically the ActiveX server name. context can be the location of a help file with more information about the error. If context ends with a number in brackets, e.g. [12], this number will be interpreted as the context ID in the help file.
Definition at line 180 of file qaxbindable.cpp.
 {
     if (!activex)
         return;
     activex->reportError(code, src, desc, context);
 }
requestPropertyChange()
bool QAxBindable::requestPropertyChange (const char * property) protected
Call this function to request permission to change the property property from the client that is hosting this ActiveX control.
Returns true if the client allows the change; otherwise returns false.
This function is usually called first in the write function for property, and writing is abandoned if the function returns false.
void MyActiveQt::setText(const QString &text)
{
    if (!requestPropertyChange("text"))
        return;
    // update property
    propertyChanged("text");
}
See also
propertyChanged()
Definition at line 117 of file qaxbindable.cpp.
 {
     if (!activex)
         return true;
     return activex->emitRequestPropertyChange(property);
 }
writeData()
bool QAxBindable::writeData (QIODevice * sink) virtual
If the COM object supports a MIME type then this function is called to store the COM object into sink.
Since
4.1
You have to open sink for writing before you can write to it.
Returns true to indicate success. If the function returns false, then ActiveQt will serialize the object by storing the property values.
If you reimplement this function you also have to implement readData(). The default implementation does nothing and returns false.
See also
readData()
Definition at line 241 of file qaxbindable.cpp.
Referenced by QAxServerBase::Save().
 {
     Q_UNUSED(sink);
     return false;
 }
Friends and Related Functions
QAxServerBase
friend class QAxServerBase friend
Definition at line 62 of file qaxbindable.h.
Properties
activex
IAxServerBase* QAxBindable::activex private
Definition at line 80 of file qaxbindable.h.
Referenced by clientSite(), QAxServerBase::internalBind(), propertyChanged(), reportError(), and requestPropertyChange().
The documentation for this class was generated from the following files:
/src/activeqt/control/qaxbindable.h
/src/activeqt/control/qaxbindable.cpp