Qt 4.8: QLinearGradient Class Reference
QLinearGradient Class Reference
The QLinearGradient class is used in combination with QBrush to specify a linear gradient brush.
#include <qbrush.h>
Public Functions
QPointF finalStop () const
Returns the final stop point of this linear gradient in logical coordinates.
QLinearGradient ()
Constructs a default linear gradient with interpolation area between (0, 0) and (1, 1).
QLinearGradient (const QPointF &start, const QPointF &finalStop)
Constructs a linear gradient with interpolation area between the given start point and finalStop.
QLinearGradient (qreal xStart, qreal yStart, qreal xFinalStop, qreal yFinalStop)
Constructs a linear gradient with interpolation area between (x1, y1) and (x2, y2).
void setFinalStop (const QPointF &stop)
Sets the final stop point of this linear gradient in logical coordinates to stop.
void setFinalStop (qreal x, qreal y)
Sets the final stop point of this linear gradient in logical coordinates to x, y.
void setStart (const QPointF &start)
Sets the start point of this linear gradient in logical coordinates to start.
void setStart (qreal x, qreal y)
Sets the start point of this linear gradient in logical coordinates to x, y.
QPointF start () const
Returns the start point of this linear gradient in logical coordinates.
Public Functions inherited from QGradient
CoordinateMode coordinateMode () const
Returns the coordinate mode of this gradient.
InterpolationMode interpolationMode () const
Returns the interpolation mode of this gradient.
bool operator!= (const QGradient &other) const
Returns true if the gradient is the same as the other gradient specified; otherwise returns false.
bool operator== (const QGradient &gradient) const
Returns true if the gradient is the same as the other gradient specified; otherwise returns false.
bool operator== (const QGradient &gradient)
QGradient ()
void setColorAt (qreal pos, const QColor &color)
Creates a stop point at the given position with the given color.
void setCoordinateMode (CoordinateMode mode)
Sets the coordinate mode of this gradient to mode.
void setInterpolationMode (InterpolationMode mode)
Sets the interpolation mode of this gradient to mode.
void setSpread (Spread spread)
Specifies the spread method that should be used for this gradient.
void setStops (const QGradientStops &stops)
Replaces the current set of stop points with the given stopPoints.
Spread spread () const
Returns the spread method use by this gradient.
QGradientStops stops () const
Returns the stop points for this gradient.
Type type () const
Returns the type of gradient.
Additional Inherited Members
Public Types inherited from QGradient
enum CoordinateMode { LogicalMode, StretchToDeviceMode, ObjectBoundingMode }
This enum specifies how gradient coordinates map to the paint device on which the gradient is used.
enum InterpolationMode { ColorInterpolation, ComponentInterpolation }
enum Spread { PadSpread, ReflectSpread, RepeatSpread }
Specifies how the area outside the gradient area should be filled.
enum Type { LinearGradient, RadialGradient, ConicalGradient, NoGradient }
Specifies the type of gradient.
Related Functions inherited from QGradient
QGradientStop
Typedef for QPair<qreal , QColor>.
QGradientStops
Typedef for QVector<QGradientStop>.
Detailed Description
The QLinearGradient class is used in combination with QBrush to specify a linear gradient brush.
Linear gradients interpolate colors between start and end points. Outside these points the gradient is either padded, reflected or repeated depending on the currently set QGradient::Spread method:
QGradient::PadSpread{PadSpread} (default) QGradient::ReflectSpread{ReflectSpread} QGradient::RepeatSpread{RepeatSpread}
The colors in a gradient is defined using stop points of the QGradientStop type, i.e. a position and a color. Use the QGradient::setColorAt() or the QGradient::setStops() function to define the stop points. It is the gradient's complete set of stop points that describes how the gradient area should be filled. If no stop points have been specified, a gradient of black at 0 to white at 1 is used.
In addition to the functions inherited from QGradient, the QLinearGradient class provides the finalStop() function which returns the final stop point of the gradient, and the start() function returning the start point of the gradient.
See also
QRadialGradient, QConicalGradient, {demos/gradients}{The Gradients Demo}
Definition at line 280 of file qbrush.h.
Constructors and Destructors
QLinearGradient() [1/3]
QLinearGradient::QLinearGradient ()
Constructs a default linear gradient with interpolation area between (0, 0) and (1, 1).
See also
QGradient::setColorAt(), setStart(), setFinalStop()
Definition at line 1737 of file qbrush.cpp.
 {
     m_type = LinearGradient;
     m_spread = PadSpread;
     m_data.linear.x1 = 0;
     m_data.linear.y1 = 0;
     m_data.linear.x2 = 1;
     m_data.linear.y2 = 1;
 }
QLinearGradient() [2/3]
QLinearGradient::QLinearGradient (const QPointF & start, const QPointF & finalStop)
Constructs a linear gradient with interpolation area between the given start point and finalStop.
Note
The expected parameter values are in pixels.
See also
QGradient::setColorAt(), QGradient::setStops()
Definition at line 1756 of file qbrush.cpp.
 {
     m_type = LinearGradient;
     m_spread = PadSpread;
     m_data.linear.x1 = start.x();
     m_data.linear.y1 = start.y();
     m_data.linear.x2 = finalStop.x();
     m_data.linear.y2 = finalStop.y();
 }
QLinearGradient() [3/3]
QLinearGradient::QLinearGradient (qreal x1, qreal y1, qreal x2, qreal y2)
Constructs a linear gradient with interpolation area between (x1, y1) and (x2, y2).
Note
The expected parameter values are in pixels.
See also
QGradient::setColorAt(), QGradient::setStops()
Definition at line 1779 of file qbrush.cpp.
 {
     m_type = LinearGradient;
     m_spread = PadSpread;
     m_data.linear.x1 = xStart;
     m_data.linear.y1 = yStart;
     m_data.linear.x2 = xFinalStop;
     m_data.linear.y2 = yFinalStop;
 }
Functions
finalStop()
QPointF QLinearGradient::finalStop () const
Returns the final stop point of this linear gradient in logical coordinates.
See also
QGradient::stops()
Definition at line 1856 of file qbrush.cpp.
Referenced by QPdf::patternForBrush(), QSvgPaintEngine::saveLinearGradientBrush(), QCoreGraphicsPaintEnginePrivate::setFillBrush(), QSpanData::setup(), QGL2PaintEngineExPrivate::updateBrushUniforms(), and QOpenGLPaintEnginePrivate::updateGradient().
 {
     Q_ASSERT(m_type == LinearGradient);
     return QPointF(m_data.linear.x2, m_data.linear.y2);
 }
setFinalStop() [1/2]
void QLinearGradient::setFinalStop (const QPointF & stop)
Sets the final stop point of this linear gradient in logical coordinates to stop.
Since
4.2
See also
finalStop()
Definition at line 1875 of file qbrush.cpp.
Referenced by QCleanlooksStyle::drawComplexControl().
 {
     Q_ASSERT(m_type == LinearGradient);
     m_data.linear.x2 = stop.x();
     m_data.linear.y2 = stop.y();
 }
setFinalStop() [2/2]
void QLinearGradient::setFinalStop (qreal x, qreal y) inline
Sets the final stop point of this linear gradient in logical coordinates to x, y.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.2
See also
start()
Definition at line 293 of file qbrush.h.
Referenced by setFinalStop().
 { setFinalStop(QPointF(x, y)); }
setStart() [1/2]
void QLinearGradient::setStart (const QPointF & start)
Sets the start point of this linear gradient in logical coordinates to start.
Since
4.2
See also
start()
Definition at line 1828 of file qbrush.cpp.
Referenced by QCleanlooksStyle::drawComplexControl().
 {
     Q_ASSERT(m_type == LinearGradient);
     m_data.linear.x1 = start.x();
     m_data.linear.y1 = start.y();
 }
setStart() [2/2]
void QLinearGradient::setStart (qreal x, qreal y) inline
Sets the start point of this linear gradient in logical coordinates to x, y.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.2
See also
start()
Definition at line 289 of file qbrush.h.
Referenced by setStart().
 { setStart(QPointF(x, y)); }
start()
QPointF QLinearGradient::start () const
Returns the start point of this linear gradient in logical coordinates.
See also
QGradient::stops()
Definition at line 1796 of file qbrush.cpp.
Referenced by QPdf::patternForBrush(), QSvgPaintEngine::saveLinearGradientBrush(), QVGPaintEnginePrivate::setBrush(), QCoreGraphicsPaintEnginePrivate::setFillBrush(), QSpanData::setup(), QGL2PaintEngineExPrivate::updateBrushUniforms(), and QOpenGLPaintEnginePrivate::updateGradient().
 {
     Q_ASSERT(m_type == LinearGradient);
     return QPointF(m_data.linear.x1, m_data.linear.y1);
 }
The documentation for this class was generated from the following files:
/src/gui/painting/qbrush.h
/src/gui/painting/qbrush.cpp