Qt 4.8: QSvgFontStyle Class Reference
QSvgFontStyle Class Reference
#include <qsvgstyle_p.h>
Public Functions
virtual void apply (QPainter *p, const QSvgNode *node, QSvgExtraStates &states)
QSvgTinyDocument * doc () const
const QFont & qfont () const
QSvgFontStyle (QSvgFont *font, QSvgTinyDocument *doc)
QSvgFontStyle ()
virtual void revert (QPainter *p, QSvgExtraStates &states)
void setFamily (const QString &family)
void setSize (qreal size)
void setStyle (QFont::Style fontStyle)
void setTextAnchor (Qt::Alignment anchor)
void setVariant (QFont::Capitalization fontVariant)
void setWeight (int weight)
QSvgFont * svgFont () const
virtual Type type () const
Public Functions inherited from QSvgStyleProperty
virtual ~QSvgStyleProperty ()
Public Functions inherited from QSvgRefCounted
void deref ()
QSvgRefCounted ()
void ref ()
virtual ~QSvgRefCounted ()
Static Public Functions
static int SVGToQtWeight (int weight)
Static Public Variables
static const int BOLDER = 1
static const int LIGHTER = -1
Properties
QSvgTinyDocument * m_doc
uint m_familySet: 1
QFont m_oldQFont
QSvgFont * m_oldSvgFont
Qt::Alignment m_oldTextAnchor
int m_oldWeight
QFont m_qfont
uint m_sizeSet: 1
uint m_styleSet: 1
QSvgFont * m_svgFont
Qt::Alignment m_textAnchor
uint m_textAnchorSet: 1
uint m_variantSet: 1
int m_weight
uint m_weightSet: 1
Additional Inherited Members
Public Types inherited from QSvgStyleProperty
enum Type {
QUALITY, FILL, VIEWPORT_FILL, FONT,
STROKE, SOLID_COLOR, GRADIENT, TRANSFORM,
ANIMATE_TRANSFORM, ANIMATE_COLOR, OPACITY, COMP_OP
}
Detailed Description
Definition at line 325 of file qsvgstyle_p.h.
Constructors and Destructors
QSvgFontStyle() [1/2]
QSvgFontStyle::QSvgFontStyle (QSvgFont * font, QSvgTinyDocument * doc)
Definition at line 183 of file qsvgstyle.cpp.
     : m_svgFont(font)
     , m_doc(doc)
     , m_familySet(0)
     , m_sizeSet(0)
     , m_styleSet(0)
     , m_variantSet(0)
     , m_weightSet(0)
     , m_textAnchorSet(0)
 {
 }
QSvgFontStyle() [2/2]
QSvgFontStyle::QSvgFontStyle ()
Definition at line 195 of file qsvgstyle.cpp.
     : m_svgFont(0)
     , m_doc(0)
     , m_familySet(0)
     , m_sizeSet(0)
     , m_styleSet(0)
     , m_variantSet(0)
     , m_weightSet(0)
     , m_textAnchorSet(0)
 {
 }
Functions
apply()
void QSvgFontStyle::apply (QPainter * p, const QSvgNode * node, QSvgExtraStates & states) virtual
Implements QSvgStyleProperty.
Definition at line 227 of file qsvgstyle.cpp.
 {
     m_oldQFont = p->font();
     m_oldSvgFont = states.svgFont;
     m_oldTextAnchor = states.textAnchor;
     m_oldWeight = states.fontWeight;
     if (m_textAnchorSet)
         states.textAnchor = m_textAnchor;
     QFont font = m_oldQFont;
     if (m_familySet) {
         states.svgFont = m_svgFont;
         font.setFamily(m_qfont.family());
     }
     if (m_sizeSet)
         font.setPointSizeF(m_qfont.pointSizeF());
     if (m_styleSet)
         font.setStyle(m_qfont.style());
     if (m_variantSet)
         font.setCapitalization(m_qfont.capitalization());
     if (m_weightSet) {
         if (m_weight == BOLDER) {
             states.fontWeight = qMin(states.fontWeight + 100, 900);
         } else if (m_weight == LIGHTER) {
             states.fontWeight = qMax(states.fontWeight - 100, 100);
         } else {
             states.fontWeight = m_weight;
         }
         font.setWeight(SVGToQtWeight(states.fontWeight));
     }
     p->setFont(font);
 }
doc()
QSvgTinyDocument* QSvgFontStyle::doc () const inline
Definition at line 386 of file qsvgstyle_p.h.
Referenced by parseFontFaceNameNode(), and parseFontFaceNode().
 {return m_doc;}
qfont()
const QFont& QSvgFontStyle::qfont () const inline
Definition at line 381 of file qsvgstyle_p.h.
     {
         return m_qfont;
     }
revert()
void QSvgFontStyle::revert (QPainter * p, QSvgExtraStates & states) virtual
Implements QSvgStyleProperty.
Definition at line 266 of file qsvgstyle.cpp.
 {
     p->setFont(m_oldQFont);
     states.svgFont = m_oldSvgFont;
     states.textAnchor = m_oldTextAnchor;
     states.fontWeight = m_oldWeight;
 }
setFamily()
void QSvgFontStyle::setFamily (const QString & family) inline
Definition at line 351 of file qsvgstyle_p.h.
Referenced by parseFont().
     {
         m_qfont.setFamily(family);
         m_familySet = 1;
     }
setSize()
void QSvgFontStyle::setSize (qreal size) inline
Definition at line 337 of file qsvgstyle_p.h.
Referenced by parseFont().
     {
         // Store the _pixel_ size in the font. Since QFont::setPixelSize() only takes an int, call
         // QFont::SetPointSize() instead. Set proper font size just before rendering.
         m_qfont.setPointSizeF(size);
         m_sizeSet = 1;
     }
setStyle()
void QSvgFontStyle::setStyle (QFont::Style fontStyle) inline
Definition at line 357 of file qsvgstyle_p.h.
Referenced by parseFont().
{
         m_qfont.setStyle(fontStyle);
         m_styleSet = 1;
     }
setTextAnchor()
void QSvgFontStyle::setTextAnchor (Qt::Alignment anchor) inline
Definition at line 345 of file qsvgstyle_p.h.
Referenced by parseFont().
     {
         m_textAnchor = anchor;
         m_textAnchorSet = 1;
     }
setVariant()
void QSvgFontStyle::setVariant (QFont::Capitalization fontVariant) inline
Definition at line 362 of file qsvgstyle_p.h.
Referenced by parseFont().
     {
         m_qfont.setCapitalization(fontVariant);
         m_variantSet = 1;
     }
setWeight()
void QSvgFontStyle::setWeight (int weight) inline
Definition at line 370 of file qsvgstyle_p.h.
Referenced by parseFont().
     {
         m_weight = weight;
         m_weightSet = 1;
     }
svgFont()
QSvgFont* QSvgFontStyle::svgFont () const inline
Definition at line 376 of file qsvgstyle_p.h.
Referenced by parseFontFaceNameNode(), parseFontFaceNode(), parseGlyphNode(), and parseMissingGlyphNode().
     {
         return m_svgFont;
     }
SVGToQtWeight()
int QSvgFontStyle::SVGToQtWeight (int weight) static
Definition at line 207 of file qsvgstyle.cpp.
Referenced by apply().
{
     switch (weight) {
     case 100:
     case 200:
         return QFont::Light;
     case 300:
     case 400:
         return QFont::Normal;
     case 500:
     case 600:
         return QFont::DemiBold;
     case 700:
     case 800:
         return QFont::Bold;
     case 900:
         return QFont::Black;
     }
     return QFont::Normal;
 }
type()
QSvgStyleProperty::Type QSvgFontStyle::type () const virtual
Implements QSvgStyleProperty.
Definition at line 472 of file qsvgstyle.cpp.
 {
     return FONT;
 }
Properties
BOLDER
const int QSvgFontStyle::BOLDER = 1 static
Definition at line 329 of file qsvgstyle_p.h.
Referenced by apply(), and parseFont().
LIGHTER
const int QSvgFontStyle::LIGHTER = -1 static
Definition at line 328 of file qsvgstyle_p.h.
Referenced by apply(), and parseFont().
m_doc
QSvgTinyDocument* QSvgFontStyle::m_doc private
Definition at line 390 of file qsvgstyle_p.h.
m_familySet
uint QSvgFontStyle::m_familySet private
Definition at line 401 of file qsvgstyle_p.h.
Referenced by apply().
m_oldQFont
QFont QSvgFontStyle::m_oldQFont private
Definition at line 397 of file qsvgstyle_p.h.
Referenced by apply(), and revert().
m_oldSvgFont
QSvgFont* QSvgFontStyle::m_oldSvgFont private
Definition at line 396 of file qsvgstyle_p.h.
Referenced by apply(), and revert().
m_oldTextAnchor
Qt::Alignment QSvgFontStyle::m_oldTextAnchor private
Definition at line 398 of file qsvgstyle_p.h.
Referenced by apply(), and revert().
m_oldWeight
int QSvgFontStyle::m_oldWeight private
Definition at line 399 of file qsvgstyle_p.h.
Referenced by apply(), and revert().
m_qfont
QFont QSvgFontStyle::m_qfont private
Definition at line 391 of file qsvgstyle_p.h.
Referenced by apply().
m_sizeSet
uint QSvgFontStyle::m_sizeSet private
Definition at line 402 of file qsvgstyle_p.h.
Referenced by apply().
m_styleSet
uint QSvgFontStyle::m_styleSet private
Definition at line 403 of file qsvgstyle_p.h.
Referenced by apply().
m_svgFont
QSvgFont* QSvgFontStyle::m_svgFont private
Definition at line 389 of file qsvgstyle_p.h.
Referenced by apply().
m_textAnchor
Qt::Alignment QSvgFontStyle::m_textAnchor private
Definition at line 394 of file qsvgstyle_p.h.
Referenced by apply().
m_textAnchorSet
uint QSvgFontStyle::m_textAnchorSet private
Definition at line 406 of file qsvgstyle_p.h.
Referenced by apply().
m_variantSet
uint QSvgFontStyle::m_variantSet private
Definition at line 404 of file qsvgstyle_p.h.
Referenced by apply().
m_weight
int QSvgFontStyle::m_weight private
Definition at line 393 of file qsvgstyle_p.h.
Referenced by apply().
m_weightSet
uint QSvgFontStyle::m_weightSet private
Definition at line 405 of file qsvgstyle_p.h.
Referenced by apply().
The documentation for this class was generated from the following files:
/src/svg/qsvgstyle_p.h
/src/svg/qsvgstyle.cpp