Qt 4.8: QDeclarativeNotifierEndpoint Class Reference
QDeclarativeNotifierEndpoint Class Reference
#include <qdeclarativenotifier_p.h>
Classes
struct Notifier
struct Signal
Public Functions
void connect (QObject *source, int sourceSignal)
void connect (QDeclarativeNotifier *)
void copyAndClear (QDeclarativeNotifierEndpoint &other)
void deref ()
void disconnect ()
bool isConnected ()
bool isConnected (QObject *source, int sourceSignal)
bool isConnected (QDeclarativeNotifier *)
QDeclarativeNotifierEndpoint ()
QDeclarativeNotifierEndpoint (QObject *t, int m)
~QDeclarativeNotifierEndpoint ()
Public Variables
QObject * target
int targetMethod
Notifier notifier
qint64 q_for_alignment_1
double q_for_alignment_2
Signal * signal
struct {
union {
qint64 q_for_alignment_1
double q_for_alignment_2
char signalData [sizeof(Signal)]
}
Signal * signal
} signal
Private Types
enum { InvalidType, SignalType, NotifierType }
Private Functions
Notifier * asNotifier ()
Signal * asSignal ()
Notifier * toNotifier ()
Signal * toSignal ()
Properties
union {
Notifier notifier
struct {
union {
qint64 q_for_alignment_1
double q_for_alignment_2
char signalData [sizeof(Signal)]
}
Signal * signal
} signal
};
quint16 refCount
enum QDeclarativeNotifierEndpoint:: { ... } type
Friends
class QDeclarativeNotifier
Detailed Description
Definition at line 65 of file qdeclarativenotifier_p.h.
Enumerations
anonymous enum
anonymous enum private
Enumerator
InvalidType
SignalType
NotifierType
Definition at line 106 of file qdeclarativenotifier_p.h.
 { InvalidType, SignalType, NotifierType } type;
Constructors and Destructors
QDeclarativeNotifierEndpoint() [1/2]
QDeclarativeNotifierEndpoint::QDeclarativeNotifierEndpoint () inline
Definition at line 153 of file qdeclarativenotifier_p.h.
     : target(0), targetMethod(0), type(InvalidType), refCount(0)
 {
 }
QDeclarativeNotifierEndpoint() [2/2]
QDeclarativeNotifierEndpoint::QDeclarativeNotifierEndpoint (QObject * t, int m) inline
Definition at line 158 of file qdeclarativenotifier_p.h.
 : target(t), targetMethod(m), type(InvalidType), refCount(0)
 {
 }
~QDeclarativeNotifierEndpoint()
QDeclarativeNotifierEndpoint::~QDeclarativeNotifierEndpoint () inline
Definition at line 163 of file qdeclarativenotifier_p.h.
 {
     disconnect();
     if (SignalType == type) {
         Signal *s = asSignal();
         s->~Signal();
     }
 }
Functions
asNotifier()
QDeclarativeNotifierEndpoint::Notifier * QDeclarativeNotifierEndpoint::asNotifier () inline private
Definition at line 266 of file qdeclarativenotifier_p.h.
Referenced by connect(), copyAndClear(), disconnect(), QDeclarativeNotifier::emitNotify(), isConnected(), toNotifier(), and QDeclarativeNotifier::~QDeclarativeNotifier().
 {
     Q_ASSERT(type == NotifierType);
     return &notifier;
 }
asSignal()
QDeclarativeNotifierEndpoint::Signal * QDeclarativeNotifierEndpoint::asSignal () inline private
Definition at line 283 of file qdeclarativenotifier_p.h.
Referenced by disconnect(), isConnected(), toNotifier(), toSignal(), and ~QDeclarativeNotifierEndpoint().
 {
     Q_ASSERT(type == SignalType);
     return signal.signal;
 }
connect() [1/2]
void QDeclarativeNotifierEndpoint::connect (QObject * source, int sourceSignal)
Definition at line 70 of file qdeclarativenotifier.cpp.
Referenced by QDeclarativeItemPrivate::parentProperty(), QObject_objectName(), QDeclarativeCompiledBindingsPrivate::subscribe(), QDeclarativeCompiledBindingsPrivate::subscribeId(), and QDeclarativeQtScriptExpression::updateGuards().
 {
     Signal *s = toSignal();
     if (s->source == source && s->sourceSignal == sourceSignal) {
         refCount++;
         return;
     }
     disconnect();
     QDeclarativePropertyPrivate::connect(source, sourceSignal, target, targetMethod);
     s->source = source;
     s->sourceSignal = sourceSignal;
     refCount++;
 }
connect() [2/2]
void QDeclarativeNotifierEndpoint::connect (QDeclarativeNotifier * notifier) inline
Definition at line 193 of file qdeclarativenotifier_p.h.
 {
     Notifier *n = toNotifier();
     if (n->notifier == notifier) {
         refCount++;
         return;
     }
     disconnect();
     n->next = notifier->endpoints;
     if (n->next) { n->next->asNotifier()->prev = &n->next; }
     notifier->endpoints = this;
     n->prev = &notifier->endpoints;
     n->notifier = notifier;
     refCount++;
 }
copyAndClear()
void QDeclarativeNotifierEndpoint::copyAndClear (QDeclarativeNotifierEndpoint & other)
Definition at line 88 of file qdeclarativenotifier.cpp.
 {
     other.disconnect();
     other.target = target;
     other.targetMethod = targetMethod;
     if (!isConnected())
         return;
     if (SignalType == type) {
         Signal *other_s = other.toSignal();
         Signal *s = asSignal();
         other_s->source = s->source;
         other_s->sourceSignal = s->sourceSignal;
         s->source = 0;
     } else if(NotifierType == type) {
         Notifier *other_n = other.toNotifier();
         Notifier *n = asNotifier();
         other_n->notifier = n->notifier;
         other_n->disconnected = n->disconnected;
         if (other_n->disconnected) *other_n->disconnected = &other;
         if (n->next) {
             other_n->next = n->next;
             n->next->asNotifier()->prev = &other_n->next;
         }
         other_n->prev = n->prev;
         *other_n->prev = &other;
         n->prev = 0;
         n->next = 0;
         n->disconnected = 0;
         n->notifier = 0;
     }
 }
deref()
void QDeclarativeNotifierEndpoint::deref () inline
Definition at line 239 of file qdeclarativenotifier_p.h.
Referenced by QDeclarativeCompiledBindingsPrivate::disconnectOne().
 {
     refCount--;
     if (refCount <= 0)
         disconnect();
 }
disconnect()
void QDeclarativeNotifierEndpoint::disconnect () inline
Definition at line 212 of file qdeclarativenotifier_p.h.
Referenced by connect(), copyAndClear(), deref(), QDeclarativeCompiledBindingsPrivate::disconnectAll(), QDeclarativeCompiledBindingsPrivate::subscribe(), QDeclarativeCompiledBindingsPrivate::subscribeId(), toNotifier(), toSignal(), QDeclarativeQtScriptExpression::updateGuards(), and ~QDeclarativeNotifierEndpoint().
 {
     if (type == SignalType) {
         Signal *s = asSignal();
         if (s->source) {
             QMetaObject::disconnectOne(s->source, s->sourceSignal, target, targetMethod);
             QObjectPrivate * const priv = QObjectPrivate::get(s->source);
             const QMetaMethod signal = s->source->metaObject()->method(s->sourceSignal);
             QVarLengthArray<char> signalSignature;
             QObjectPrivate::signalSignature(signal, &signalSignature);
             priv->disconnectNotify(signalSignature.constData());
             s->source = 0;
         }
     } else if (type == NotifierType) {
         Notifier *n = asNotifier();
         if (n->next) n->next->asNotifier()->prev = n->prev;
         if (n->prev) *n->prev = n->next;
         if (n->disconnected) *n->disconnected = 0;
         n->next = 0;
         n->prev = 0;
         n->disconnected = 0;
         n->notifier = 0;
     }
     refCount = 0;
 }
isConnected() [1/3]
bool QDeclarativeNotifierEndpoint::isConnected () inline
Definition at line 172 of file qdeclarativenotifier_p.h.
Referenced by QDeclarativeCompiledBindingsPrivate::disconnectAll(), and QDeclarativeQtScriptExpression::updateGuards().
 {
     if (SignalType == type) {
         return asSignal()->source;
     } else if (NotifierType == type) {
         return asNotifier()->notifier;
     } else {
         return false;
     }
 }
isConnected() [2/3]
bool QDeclarativeNotifierEndpoint::isConnected (QObject * source, int sourceSignal) inline
Definition at line 183 of file qdeclarativenotifier_p.h.
 {
     return SignalType == type && asSignal()->source == source && asSignal()->sourceSignal == sourceSignal;
 }
isConnected() [3/3]
bool QDeclarativeNotifierEndpoint::isConnected (QDeclarativeNotifier * notifier) inline
Definition at line 188 of file qdeclarativenotifier_p.h.
 {
     return NotifierType == type && asNotifier()->notifier == notifier;
 }
toNotifier()
QDeclarativeNotifierEndpoint::Notifier * QDeclarativeNotifierEndpoint::toNotifier () inline private
Definition at line 246 of file qdeclarativenotifier_p.h.
Referenced by connect(), and copyAndClear().
 {
     if (NotifierType == type)
         return asNotifier();
     if (SignalType == type) {
         disconnect();
         Signal *s = asSignal();
         s->~Signal();
     }
     type = NotifierType;
     Notifier *n = asNotifier();
     n->next = 0;
     n->prev = 0;
     n->disconnected = 0;
     n->notifier = 0;
     return n;
 }
toSignal()
QDeclarativeNotifierEndpoint::Signal * QDeclarativeNotifierEndpoint::toSignal () inline private
Definition at line 272 of file qdeclarativenotifier_p.h.
Referenced by copyAndClear().
 {
     if (SignalType == type)
         return asSignal();
     disconnect();
     signal.signal = new (&signal.signalData) Signal;
     type = SignalType;
     return signal.signal;
 }
Friends and Related Functions
QDeclarativeNotifier
friend class QDeclarativeNotifier friend
Definition at line 91 of file qdeclarativenotifier_p.h.
Properties
@139
union { ... }
notifier
Notifier QDeclarativeNotifierEndpoint::notifier
Definition at line 116 of file qdeclarativenotifier_p.h.
Referenced by asNotifier(), connect(), and isConnected().
q_for_alignment_1
qint64 QDeclarativeNotifierEndpoint::q_for_alignment_1
Definition at line 112 of file qdeclarativenotifier_p.h.
q_for_alignment_2
double QDeclarativeNotifierEndpoint::q_for_alignment_2
Definition at line 113 of file qdeclarativenotifier_p.h.
refCount
quint16 QDeclarativeNotifierEndpoint::refCount private
Definition at line 119 of file qdeclarativenotifier_p.h.
Referenced by connect(), deref(), and disconnect().
signal [1/2]
Signal* QDeclarativeNotifierEndpoint::signal
Definition at line 109 of file qdeclarativenotifier_p.h.
Referenced by asSignal(), disconnect(), and toSignal().
signal [2/2]
struct { ... } QDeclarativeNotifierEndpoint::signal
signalData
char QDeclarativeNotifierEndpoint::signalData[sizeof(Signal)]
Definition at line 111 of file qdeclarativenotifier_p.h.
target
QObject* QDeclarativeNotifierEndpoint::target
Definition at line 72 of file qdeclarativenotifier_p.h.
Referenced by copyAndClear(), disconnect(), QDeclarativeNotifier::emitNotify(), QDeclarativeCompiledBindingsPrivate::run(), QDeclarativeCompiledBindingsPrivate::subscribe(), QDeclarativeCompiledBindingsPrivate::subscribeId(), and QDeclarativeQtScriptExpression::updateGuards().
targetMethod
int QDeclarativeNotifierEndpoint::targetMethod
Definition at line 73 of file qdeclarativenotifier_p.h.
Referenced by copyAndClear(), disconnect(), QDeclarativeNotifier::emitNotify(), QDeclarativeCompiledBindingsPrivate::run(), QDeclarativeCompiledBindingsPrivate::subscribe(), QDeclarativeCompiledBindingsPrivate::subscribeId(), and QDeclarativeQtScriptExpression::updateGuards().
type
enum { ... } QDeclarativeNotifierEndpoint::type
Referenced by asNotifier(), asSignal(), disconnect(), isConnected(), toNotifier(), toSignal(), and ~QDeclarativeNotifierEndpoint().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativenotifier_p.h
/src/declarative/qml/qdeclarativenotifier.cpp