Qt 4.8: QSocks5Authenticator Class Reference
QSocks5Authenticator Class Reference
#include <qsocks5socketengine_p.h>
Public Functions
virtual bool beginAuthenticate (QTcpSocket *socket, bool *completed)
virtual bool continueAuthenticate (QTcpSocket *socket, bool *completed)
virtual QString errorString ()
virtual char methodId ()
QSocks5Authenticator ()
virtual bool seal (const QByteArray buf, QByteArray *sealedBuf)
virtual bool unSeal (const QByteArray sealedBuf, QByteArray *buf)
virtual bool unSeal (QTcpSocket *sealedSocket, QByteArray *buf)
virtual ~QSocks5Authenticator ()
Detailed Description
Definition at line 151 of file qsocks5socketengine_p.h.
Constructors and Destructors
QSocks5Authenticator()
QSocks5Authenticator::QSocks5Authenticator ()
Definition at line 424 of file qsocks5socketengine.cpp.
 {
 }
~QSocks5Authenticator()
QSocks5Authenticator::~QSocks5Authenticator () virtual
Definition at line 428 of file qsocks5socketengine.cpp.
 {
 }
Functions
beginAuthenticate()
bool QSocks5Authenticator::beginAuthenticate (QTcpSocket * socket, bool * completed) virtual
Reimplemented in QSocks5PasswordAuthenticator.
Definition at line 437 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::parseAuthenticationMethodReply().
 {
     Q_UNUSED(socket);
     *completed = true;
     return true;
 }
continueAuthenticate()
bool QSocks5Authenticator::continueAuthenticate (QTcpSocket * socket, bool * completed) virtual
Reimplemented in QSocks5PasswordAuthenticator.
Definition at line 444 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::parseAuthenticatingReply().
 {
     Q_UNUSED(socket);
     *completed = true;
     return true;
 }
errorString()
virtual QString QSocks5Authenticator::errorString () inline virtual
Reimplemented in QSocks5PasswordAuthenticator.
Definition at line 164 of file qsocks5socketengine_p.h.
 { return QString(); }
methodId()
char QSocks5Authenticator::methodId () virtual
Reimplemented in QSocks5PasswordAuthenticator.
Definition at line 432 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::parseAuthenticationMethodReply().
 {
     return 0x00;
 }
seal()
bool QSocks5Authenticator::seal (const QByteArray buf, QByteArray * sealedBuf) virtual
Definition at line 451 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::sendRequestMethod().
 {
     *sealedBuf = buf;
     return true;
 }
unSeal() [1/2]
bool QSocks5Authenticator::unSeal (const QByteArray sealedBuf, QByteArray * buf) virtual
Definition at line 457 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::parseRequestMethodReply().
 {
     *buf = sealedBuf;
     return true;
 }
unSeal() [2/2]
bool QSocks5Authenticator::unSeal (QTcpSocket * sealedSocket, QByteArray * buf) virtual
Definition at line 463 of file qsocks5socketengine.cpp.
 {
     return unSeal(sealedSocket->readAll(), buf);
 }
The documentation for this class was generated from the following files:
/src/network/socket/qsocks5socketengine_p.h
/src/network/socket/qsocks5socketengine.cpp