Qt 4.8: QDialogButtonBox Class Reference
QDialogButtonBox Class Reference
The QDialogButtonBox class is a widget that presents buttons in a layout that is appropriate to the current widget style.
#include <qdialogbuttonbox.h>
Public Types
enum ButtonLayout { WinLayout, MacLayout, KdeLayout, GnomeLayout }
This enum describes the layout policy to be used when arranging the buttons contained in the button box.
enum ButtonRole {
InvalidRole = -1, AcceptRole, RejectRole, DestructiveRole,
ActionRole, HelpRole, YesRole, NoRole,
ResetRole, ApplyRole, NRoles
}
This enum describes the roles that can be used to describe buttons in the button box.
enum StandardButton {
NoButton = 0x00000000, Ok = 0x00000400, Save = 0x00000800, SaveAll = 0x00001000,
Open = 0x00002000, Yes = 0x00004000, YesToAll = 0x00008000, No = 0x00010000,
NoToAll = 0x00020000, Abort = 0x00040000, Retry = 0x00080000, Ignore = 0x00100000,
Close = 0x00200000, Cancel = 0x00400000, Discard = 0x00800000, Help = 0x01000000,
Apply = 0x02000000, Reset = 0x04000000, RestoreDefaults = 0x08000000, FirstButton = Ok,
LastButton = RestoreDefaults
}
These enums describe flags for standard buttons.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Signals
void accepted ()
This signal is emitted when a button inside the button box is clicked, as long as it was defined with the AcceptRole or YesRole .
void clicked (QAbstractButton *button)
This signal is emitted when a button inside the button box is clicked.
void helpRequested ()
This signal is emitted when a button inside the button box is clicked, as long as it was defined with the HelpRole .
void rejected ()
This signal is emitted when a button inside the button box is clicked, as long as it was defined with the RejectRole or NoRole .
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addButton (QAbstractButton *button, ButtonRole role)
Adds the given button to the button box with the specified role.
QPushButton * addButton (const QString &text, ButtonRole role)
Creates a push button with the given text, adds it to the button box for the specified role, and returns the corresponding push button.
QPushButton * addButton (StandardButton button)
Adds a standard button to the button box if it is valid to do so, and returns a push button.
QPushButton * button (StandardButton which) const
Returns the QPushButton corresponding to the standard button which, or 0 if the standard button doesn't exist in this button box.
ButtonRole buttonRole (QAbstractButton *button) const
Returns the button role for the specified button.
QList< QAbstractButton * > buttons () const
Returns a list of all the buttons that have been added to the button box.
bool centerButtons () const
void clear ()
Clears the button box, deleting all buttons within it.
Qt::Orientation orientation () const
QDialogButtonBox (QWidget *parent=0)
Constructs an empty, horizontal button box with the given parent.
QDialogButtonBox (Qt::Orientation orientation, QWidget *parent=0)
Constructs an empty button box with the given orientation and parent.
QDialogButtonBox (StandardButtons buttons, Qt::Orientation orientation=Qt::Horizontal, QWidget *parent=0)
Constructs a button box with the given orientation and parent, containing the standard buttons specified by buttons.
void removeButton (QAbstractButton *button)
Removes button from the button box without deleting it and sets its parent to zero.
void setCenterButtons (bool center)
void setOrientation (Qt::Orientation orientation)
void setStandardButtons (StandardButtons buttons)
StandardButton standardButton (QAbstractButton *button) const
Returns the standard button enum value corresponding to the given button, or NoButton if the given button isn't a standard button.
StandardButtons standardButtons () const
~QDialogButtonBox ()
Destroys the button box.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
virtual QSize minimumSizeHint () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
virtual QSize sizeHint () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *event)
Reimplemented Function
bool event (QEvent *event)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyPressEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key press events for the widget.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool centerButtons
whether the buttons in the button box are centered
Qt::Orientation orientation
the orientation of the button box
StandardButtons standardButtons
collection of standard buttons in the button box
Additional Inherited Members
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QDialogButtonBox class is a widget that presents buttons in a layout that is appropriate to the current widget style.
Since
4.2
Dialogs and message boxes typically present buttons in a layout that conforms to the interface guidelines for that platform. Invariably, different platforms have different layouts for their dialogs. QDialogButtonBox allows a developer to add buttons to it and will automatically use the appropriate layout for the user's desktop environment.
Most buttons for a dialog follow certain roles. Such roles include:
Accepting or rejecting the dialog.
Asking for help.
Performing actions on the dialog itself (such as resetting fields or applying changes).
There can also be alternate ways of dismissing the dialog which may cause destructive results.
Most dialogs have buttons that can almost be considered standard (e.g. OK and Cancel buttons). It is sometimes convenient to create these buttons in a standard way.
There are a couple ways of using QDialogButtonBox. One ways is to create the buttons (or button texts) yourself and add them to the button box, specifying their role.
    findButton = new QPushButton(tr("&Find"));
    findButton->setDefault(true);
    moreButton = new QPushButton(tr("&More"));
    moreButton->setCheckable(true);
    moreButton->setAutoDefault(false);
    buttonBox = new QDialogButtonBox(Qt::Vertical);
    buttonBox->addButton(findButton, QDialogButtonBox::ActionRole);
    buttonBox->addButton(moreButton, QDialogButtonBox::ActionRole);
Alternatively, QDialogButtonBox provides several standard buttons (e.g. OK, Cancel, Save) that you can use. They exist as flags so you can OR them together in the constructor.
    buttonBox = new QDialogButtonBox(QDialogButtonBox::Ok
                                     | QDialogButtonBox::Cancel);
    connect(buttonBox, SIGNAL(accepted()), this, SLOT(accept()));
    connect(buttonBox, SIGNAL(rejected()), this, SLOT(reject()));
You can mix and match normal buttons and standard buttons.
Currently the buttons are laid out in the following way if the button box is horizontal:
GnomeLayout Horizontal
Button box laid out in horizontal GnomeLayout
KdeLayout Horizontal
Button box laid out in horizontal KdeLayout
MacLayout Horizontal
Button box laid out in horizontal MacLayout
WinLayout Horizontal
Button box laid out in horizontal WinLayout
The buttons are laid out the following way if the button box is vertical:
GnomeLayout KdeLayout MacLayout WinLayout
GnomeLayout Vertical
KdeLayout Vertical
MacLayout Vertical
WinLayout Vertical
Additionally, button boxes that contain only buttons with ActionRole or HelpRole can be considered modeless and have an alternate look on Mac OS X:
modeless horizontal MacLayout
Screenshot of modeless horizontal MacLayout
When a button is clicked in the button box, the clicked() signal is emitted for the actual button is that is pressed. For convenience, if the button has an AcceptRole, RejectRole, or HelpRole, the accepted(), rejected(), or helpRequested() signals are emitted respectively.
If you want a specific button to be default you need to call QPushButton::setDefault() on it yourself. However, if there is no default button set and to preserve which button is the default button across platforms when using the QPushButton::autoDefault property, the first push button with the accept role is made the default button when the QDialogButtonBox is shown,
See also
QMessageBox, QPushButton, QDialog
Definition at line 57 of file qdialogbuttonbox.h.
Enumerations
ButtonLayout
enum QDialogButtonBox::ButtonLayout
This enum describes the layout policy to be used when arranging the buttons contained in the button box.
WinLayout Use a policy appropriate for applications on Windows.
MacLayout Use a policy appropriate for applications on Mac OS X.
KdeLayout Use a policy appropriate for applications on KDE.
GnomeLayout Use a policy appropriate for applications on GNOME.
The button layout is specified by the current style. However, on the X11 platform, it may be influenced by the desktop environment.
Enumerator
WinLayout
MacLayout
KdeLayout
GnomeLayout
Definition at line 112 of file qdialogbuttonbox.h.
                       {
         WinLayout,
         MacLayout,
         KdeLayout,
         GnomeLayout
     };
ButtonRole
enum QDialogButtonBox::ButtonRole
This enum describes the roles that can be used to describe buttons in the button box.
Enumerator
InvalidRole
AcceptRole
RejectRole
DestructiveRole
ActionRole
HelpRole
YesRole
NoRole
ResetRole
ApplyRole
NRoles
Definition at line 66 of file qdialogbuttonbox.h.
                     {
         // keep this in sync with QMessageBox::ButtonRole
         InvalidRole = -1,
         AcceptRole,
         RejectRole,
         DestructiveRole,
         ActionRole,
         HelpRole,
         YesRole,
         NoRole,
         ResetRole,
         ApplyRole,
         NRoles
     };
StandardButton
enum QDialogButtonBox::StandardButton
These enums describe flags for standard buttons.
Each button has a defined ButtonRole .
Ok An "OK" button defined with the AcceptRole .
Open A "Open" button defined with the AcceptRole .
Save A "Save" button defined with the AcceptRole .
Cancel A "Cancel" button defined with the RejectRole .
Close A "Close" button defined with the RejectRole .
Discard A "Discard" or "Don't Save" button, depending on the platform, defined with the DestructiveRole .
Apply An "Apply" button defined with the ApplyRole .
Reset A "Reset" button defined with the ResetRole .
RestoreDefaults A "Restore Defaults" button defined with the ResetRole .
Help A "Help" button defined with the HelpRole .
SaveAll A "Save All" button defined with the AcceptRole .
Yes A "Yes" button defined with the YesRole .
YesToAll A "Yes to All" button defined with the YesRole .
No A "No" button defined with the NoRole .
NoToAll A "No to All" button defined with the NoRole .
Abort An "Abort" button defined with the RejectRole .
Retry A "Retry" button defined with the AcceptRole .
Ignore An "Ignore" button defined with the AcceptRole .
NoButton An invalid button.
FirstButton
LastButton
See also
ButtonRole, standardButtons
Enumerator
NoButton
Ok
Save
SaveAll
Open
Yes
YesToAll
No
NoToAll
Abort
Retry
Ignore
Close
Cancel
Discard
Apply
Reset
RestoreDefaults
FirstButton
LastButton
Definition at line 82 of file qdialogbuttonbox.h.
{
         // keep this in sync with QMessageBox::StandardButton
         NoButton           = 0x00000000,
         Ok                 = 0x00000400,
         Save               = 0x00000800,
         SaveAll            = 0x00001000,
         Open               = 0x00002000,
         Yes                = 0x00004000,
         YesToAll           = 0x00008000,
         No                 = 0x00010000,
         NoToAll            = 0x00020000,
         Abort              = 0x00040000,
         Retry              = 0x00080000,
         Ignore             = 0x00100000,
         Close              = 0x00200000,
         Cancel             = 0x00400000,
         Discard            = 0x00800000,
         Help               = 0x01000000,
         Apply              = 0x02000000,
         Reset              = 0x04000000,
         RestoreDefaults    = 0x08000000,
 #ifndef Q_MOC_RUN
         FirstButton        = Ok,
         LastButton         = RestoreDefaults
 #endif
     };
Constructors and Destructors
QDialogButtonBox() [1/3]
QDialogButtonBox::QDialogButtonBox (QWidget * parent = 0)
Constructs an empty, horizontal button box with the given parent.
See also
orientation, addButton()
Definition at line 749 of file qdialogbuttonbox.cpp.
     : QWidget(*new QDialogButtonBoxPrivate(Qt::Horizontal), parent, 0)
 {
     d_func()->initLayout();
 }
QDialogButtonBox() [2/3]
QDialogButtonBox::QDialogButtonBox (Qt::Orientation orientation, QWidget * parent = 0)
Constructs an empty button box with the given orientation and parent.
See also
orientation, addButton()
Definition at line 760 of file qdialogbuttonbox.cpp.
     : QWidget(*new QDialogButtonBoxPrivate(orientation), parent, 0)
 {
     d_func()->initLayout();
 }
QDialogButtonBox() [3/3]
QDialogButtonBox::QDialogButtonBox (StandardButtons buttons, Qt::Orientation orientation = Qt::Horizontal, QWidget * parent = 0)
Constructs a button box with the given orientation and parent, containing the standard buttons specified by buttons.
See also
orientation, addButton()
Definition at line 772 of file qdialogbuttonbox.cpp.
     : QWidget(*new QDialogButtonBoxPrivate(orientation), parent, 0)
 {
     d_func()->initLayout();
     d_func()->createStandardButtons(buttons);
 }
~QDialogButtonBox()
QDialogButtonBox::~QDialogButtonBox ()
Destroys the button box.
Definition at line 783 of file qdialogbuttonbox.cpp.
 {
 }
Functions
accepted
void QDialogButtonBox::accepted () signal
This signal is emitted when a button inside the button box is clicked, as long as it was defined with the AcceptRole or YesRole .
See also
rejected(), clicked() helpRequested()
addButton() [1/3]
void QDialogButtonBox::addButton (QAbstractButton * button, ButtonRole role)
Adds the given button to the button box with the specified role.
If the role is invalid, the button is not added.
If the button has already been added, it is removed and added again with the new role.
Note
The button box takes ownership of the button.
See also
removeButton(), clear()
Definition at line 1056 of file qdialogbuttonbox.cpp.
 {
     Q_D(QDialogButtonBox);
     if (role <= InvalidRole || role >= NRoles) {
         qWarning("QDialogButtonBox::addButton: Invalid ButtonRole, button not added");
         return;
     }
     removeButton(button);
     button->setParent(this);
     d->addButton(button, role);
 }
addButton() [2/3]
QPushButton * QDialogButtonBox::addButton (const QString & text, ButtonRole role)
Creates a push button with the given text, adds it to the button box for the specified role, and returns the corresponding push button.
If role is invalid, no button is created, and zero is returned.
See also
removeButton(), clear()
Definition at line 1075 of file qdialogbuttonbox.cpp.
 {
     Q_D(QDialogButtonBox);
     if (role <= InvalidRole || role >= NRoles) {
         qWarning("QDialogButtonBox::addButton: Invalid ButtonRole, button not added");
         return 0;
     }
     QPushButton *button = new QPushButton(text, this);
     d->addButton(button, role);
     return button;
 }
addButton() [3/3]
QPushButton * QDialogButtonBox::addButton (StandardButton button)
Adds a standard button to the button box if it is valid to do so, and returns a push button.
If button is invalid, it is not added to the button box, and zero is returned.
See also
removeButton(), clear()
Definition at line 1094 of file qdialogbuttonbox.cpp.
 {
     Q_D(QDialogButtonBox);
     return d->createButton(button);
 }
button()
QPushButton * QDialogButtonBox::button (StandardButton which) const
Returns the QPushButton corresponding to the standard button which, or 0 if the standard button doesn't exist in this button box.
See also
standardButton(), standardButtons(), buttons()
Definition at line 1144 of file qdialogbuttonbox.cpp.
Referenced by QInputDialogPrivate::_q_currentRowChanged(), addButton(), buttonRole(), clear(), QInputDialogPrivate::ensureEnabledConnection(), QPrintPropertiesDialog::QPrintPropertiesDialog(), removeButton(), and QInputDialogPrivate::setInputWidget().
 {
     Q_D(const QDialogButtonBox);
     return d->standardButtonHash.key(which);
 }
buttonRole()
QDialogButtonBox::ButtonRole QDialogButtonBox::buttonRole (QAbstractButton * button) const
Returns the button role for the specified button.
This function returns InvalidRole if button is 0 or has not been added to the button box.
See also
buttons(), addButton()
Definition at line 993 of file qdialogbuttonbox.cpp.
Referenced by showNewMessageBox().
 {
     Q_D(const QDialogButtonBox);
     for (int i = 0; i < NRoles; ++i) {
         const QList<QAbstractButton *> &list = d->buttonLists[i];
         for (int j = 0; j < list.count(); ++j) {
             if (list.at(j) == button)
                 return ButtonRole(i);
         }
     }
     return InvalidRole;
 }
buttons()
QList< QAbstractButton * > QDialogButtonBox::buttons () const
Returns a list of all the buttons that have been added to the button box.
See also
buttonRole(), addButton(), removeButton()
Definition at line 975 of file qdialogbuttonbox.cpp.
 {
     Q_D(const QDialogButtonBox);
     QList<QAbstractButton *> finalList;
     for (int i = 0; i < NRoles; ++i) {
         const QList<QAbstractButton *> &list = d->buttonLists[i];
         for (int j = 0; j < list.count(); ++j)
             finalList.append(list.at(j));
     }
     return finalList;
 }
centerButtons()
bool QDialogButtonBox::centerButtons () const
Referenced by setCenterButtons().
changeEvent()
void QDialogButtonBox::changeEvent (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1227 of file qdialogbuttonbox.cpp.
 {
     typedef QHash<QPushButton *, QDialogButtonBox::StandardButton> StandardButtonHash;
     Q_D(QDialogButtonBox);
     switch (event->type()) {
     case QEvent::StyleChange:  // Propagate style
         if (!d->standardButtonHash.empty()) {
             QStyle *newStyle = style();
             const StandardButtonHash::iterator end = d->standardButtonHash.end();
             for (StandardButtonHash::iterator it = d->standardButtonHash.begin(); it != end; ++it)
                 it.key()->setStyle(newStyle);
         }
         // fallthrough intended
 #ifdef Q_WS_MAC
     case QEvent::MacSizeChange:
 #endif
         d->resetLayout();
         QWidget::changeEvent(event);
         break;
     default:
         QWidget::changeEvent(event);
         break;
     }
 }
clear()
void QDialogButtonBox::clear ()
Clears the button box, deleting all buttons within it.
See also
removeButton(), addButton()
Definition at line 949 of file qdialogbuttonbox.cpp.
 {
     Q_D(QDialogButtonBox);
 #ifdef QT_SOFTKEYS_ENABLED
     // Delete softkey actions as they have the buttons as parents
     qDeleteAll(d->softKeyActions.values());
     d->softKeyActions.clear();
 #endif
     // Remove the created standard buttons, they should be in the other lists, which will
     // do the deletion
     d->standardButtonHash.clear();
     for (int i = 0; i < NRoles; ++i) {
         QList<QAbstractButton *> &list = d->buttonLists[i];
         while (list.count()) {
             QAbstractButton *button = list.takeAt(0);
             QObject::disconnect(button, SIGNAL(destroyed()), this, SLOT(_q_handleButtonDestroyed()));
             delete button;
         }
     }
 }
clicked
void QDialogButtonBox::clicked (QAbstractButton * button) signal
This signal is emitted when a button inside the button box is clicked.
The specific button that was pressed is specified by button.
See also
accepted(), rejected(), helpRequested()
Referenced by removeButton().
event()
bool QDialogButtonBox::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1256 of file qdialogbuttonbox.cpp.
 {
     Q_D(QDialogButtonBox);
     if (event->type() == QEvent::Show) {
         QList<QAbstractButton *> acceptRoleList = d->buttonLists[AcceptRole];
         QPushButton *firstAcceptButton = acceptRoleList.isEmpty() ? 0 : qobject_cast<QPushButton *>(acceptRoleList.at(0));
         bool hasDefault = false;
         QWidget *dialog = 0;
         QWidget *p = this;
         while (p && !p->isWindow()) {
             p = p->parentWidget();
             if ((dialog = qobject_cast<QDialog *>(p)))
                 break;
         }
         foreach (QPushButton *pb, (dialog ? dialog : this)->findChildren<QPushButton *>()) {
             if (pb->isDefault() && pb != firstAcceptButton) {
                 hasDefault = true;
                 break;
             }
         }
         if (!hasDefault && firstAcceptButton)
             firstAcceptButton->setDefault(true);
 #ifdef QT_SOFTKEYS_ENABLED
         if (dialog)
             setFixedSize(0,0);
 #endif
     }else if (event->type() == QEvent::LanguageChange) {
         d->retranslateStrings();
     }
 #if defined(QT_SOFTKEYS_ENABLED) && !defined(QT_NO_ACTION)
     else if (event->type() == QEvent::ParentChange) {
         QWidget *dialog = 0;
         QWidget *p = this;
         while (p && !p->isWindow()) {
             p = p->parentWidget();
             if ((dialog = qobject_cast<QDialog *>(p)))
                 break;
         }
         // If the parent changes, then move the softkeys
         for (QHash<QAbstractButton *, QAction *>::const_iterator it = d->softKeyActions.constBegin();
             it != d->softKeyActions.constEnd(); ++it) {
             QAction *current = it.value();
             QList<QWidget *> widgets = current->associatedWidgets();
             foreach (QWidget *w, widgets)
                 w->removeAction(current);
             if (dialog)
                 dialog->addAction(current);
             else
                 addAction(current);
         }
     }
 #endif
     return QWidget::event(event);
 }
helpRequested
void QDialogButtonBox::helpRequested () signal
This signal is emitted when a button inside the button box is clicked, as long as it was defined with the HelpRole .
See also
accepted() rejected() clicked()
orientation()
Qt::Orientation QDialogButtonBox::orientation () const
Referenced by setOrientation(), and ~QDialogButtonBox().
rejected
void QDialogButtonBox::rejected () signal
This signal is emitted when a button inside the button box is clicked, as long as it was defined with the RejectRole or NoRole .
See also
accepted() helpRequested() clicked()
removeButton()
void QDialogButtonBox::removeButton (QAbstractButton * button)
Removes button from the button box without deleting it and sets its parent to zero.
See also
clear(), buttons(), addButton()
Definition at line 1011 of file qdialogbuttonbox.cpp.
Referenced by addButton().
 {
     Q_D(QDialogButtonBox);
     if (!button)
         return;
     // Remove it from the standard button hash first and then from the roles
     if (QPushButton *pushButton = qobject_cast<QPushButton *>(button))
         d->standardButtonHash.remove(pushButton);
     for (int i = 0; i < NRoles; ++i) {
         QList<QAbstractButton *> &list = d->buttonLists[i];
         for (int j = 0; j < list.count(); ++j) {
             if (list.at(j) == button) {
                 list.takeAt(j);
                 if (!d->internalRemove) {
                     disconnect(button, SIGNAL(clicked()), this, SLOT(_q_handleButtonClicked()));
                     disconnect(button, SIGNAL(destroyed()), this, SLOT(_q_handleButtonDestroyed()));
                 }
                 break;
             }
         }
     }
 #if defined(QT_SOFTKEYS_ENABLED) && !defined(QT_NO_ACTION)
     QAction *action = d->softKeyActions.value(button, 0);
     if (action) {
         d->softKeyActions.remove(button);
         delete action;
     }
 #endif
     if (!d->internalRemove)
         button->setParent(0);
 }
setCenterButtons()
void QDialogButtonBox::setCenterButtons (bool center)
Definition at line 1209 of file qdialogbuttonbox.cpp.
 {
     Q_D(QDialogButtonBox);
     if (d->center != center) {
         d->center = center;
         d->resetLayout();
     }
 }
setOrientation()
void QDialogButtonBox::setOrientation (Qt::Orientation orientation)
Definition at line 934 of file qdialogbuttonbox.cpp.
 {
     Q_D(QDialogButtonBox);
     if (orientation == d->orientation)
         return;
     d->orientation = orientation;
     d->resetLayout();
 }
setStandardButtons()
void QDialogButtonBox::setStandardButtons (StandardButtons buttons)
Definition at line 1111 of file qdialogbuttonbox.cpp.
 {
     Q_D(QDialogButtonBox);
 #ifdef QT_SOFTKEYS_ENABLED
     // Delete softkey actions since they have the buttons as parents
     qDeleteAll(d->softKeyActions.values());
     d->softKeyActions.clear();
 #endif
     // Clear out all the old standard buttons, then recreate them.
     qDeleteAll(d->standardButtonHash.keys());
     d->standardButtonHash.clear();
     d->createStandardButtons(buttons);
 }
standardButton()
QDialogButtonBox::StandardButton QDialogButtonBox::standardButton (QAbstractButton * button) const
Returns the standard button enum value corresponding to the given button, or NoButton if the given button isn't a standard button.
See also
button(), buttons(), standardButtons()
Definition at line 1156 of file qdialogbuttonbox.cpp.
 {
     Q_D(const QDialogButtonBox);
     return d->standardButtonHash.value(static_cast<QPushButton *>(button));
 }
standardButtons()
StandardButtons QDialogButtonBox::standardButtons () const
Referenced by setStandardButtons().
Properties
centerButtons
bool QDialogButtonBox::centerButtons private
whether the buttons in the button box are centered
By default, this property is false. This behavior is appopriate for most types of dialogs. A notable exception is message boxes on most platforms (e.g. Windows), where the button box is centered horizontally.
See also
QMessageBox
Definition at line 63 of file qdialogbuttonbox.h.
orientation
Qt::Orientation QDialogButtonBox::orientation private
the orientation of the button box
By default, the orientation is horizontal (i.e. the buttons are laid out side by side). The possible orientations are Qt::Horizontal and Qt::Vertical.
Definition at line 61 of file qdialogbuttonbox.h.
standardButtons
QDialogButtonBox::StandardButtons QDialogButtonBox::standardButtons private
collection of standard buttons in the button box
This property controls which standard buttons are used by the button box.
See also
addButton()
Definition at line 62 of file qdialogbuttonbox.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qdialogbuttonbox.h
/src/gui/widgets/qdialogbuttonbox.cpp