Qt 4.8: QVarLengthGlyphLayoutArray Class Reference
QVarLengthGlyphLayoutArray Class Reference
#include <qtextengine_p.h>
Public Functions
QVarLengthGlyphLayoutArray (int totalGlyphs)
void resize (int totalGlyphs)
Public Functions inherited from QGlyphLayout
void clear (int first=0, int last=-1)
char * data ()
QFixed effectiveAdvance (int item) const
void grow (char *address, int totalGlyphs)
QGlyphLayoutInstance instance (int position) const
QGlyphLayout mid (int position, int n=-1) const
QGlyphLayout ()
QGlyphLayout (char *address, int totalGlyphs)
void setInstance (int position, const QGlyphLayoutInstance &g)
Private Types
typedef QVarLengthArray< void * > Array
Additional Inherited Members
Static Public Functions inherited from QGlyphLayout
static int spaceNeededForGlyphLayout (int totalGlyphs)
Public Variables inherited from QGlyphLayout
QFixed * advances_x
QFixed * advances_y
HB_GlyphAttributes * attributes
HB_Glyph * glyphs
QGlyphJustification * justifications
int numGlyphs
QFixedPoint * offsets
Detailed Description
Definition at line 268 of file qtextengine_p.h.
Typedefs
Array
typedef QVarLengthArray<void *> QVarLengthGlyphLayoutArray::Array private
Definition at line 271 of file qtextengine_p.h.
Constructors and Destructors
QVarLengthGlyphLayoutArray()
QVarLengthGlyphLayoutArray::QVarLengthGlyphLayoutArray (int totalGlyphs) inline
Definition at line 273 of file qtextengine_p.h.
         : Array(spaceNeededForGlyphLayout(totalGlyphs) / sizeof(void *) + 1)
         , QGlyphLayout(reinterpret_cast<char *>(Array::data()), totalGlyphs)
     {
         memset(Array::data(), 0, Array::size() * sizeof(void *));
     }
Functions
resize()
void QVarLengthGlyphLayoutArray::resize (int totalGlyphs) inline
Definition at line 280 of file qtextengine_p.h.
Referenced by QFontEngineXLFD::canRender(), QFontEngineMulti::canRender(), and QRawFont::glyphIndexesForString().
     {
         Array::resize(spaceNeededForGlyphLayout(totalGlyphs) / sizeof(void *) + 1);
         *((QGlyphLayout *)this) = QGlyphLayout(reinterpret_cast<char *>(Array::data()), totalGlyphs);
         memset(Array::data(), 0, Array::size() * sizeof(void *));
     }
The documentation for this class was generated from the following file:
/src/gui/text/qtextengine_p.h