Qt 4.8: QScriptSyntaxCheckResult Class Reference
QScriptSyntaxCheckResult Class Reference
The QScriptSyntaxCheckResult class provides the result of a script syntax check.
#include <qscriptengine.h>
Public Types
enum State { Error, Intermediate, Valid }
This enum specifies the state of a syntax check.
Public Functions
int errorColumnNumber () const
Returns the error column number of this QScriptSyntaxCheckResult, or -1 if there is no error.
int errorLineNumber () const
Returns the error line number of this QScriptSyntaxCheckResult, or -1 if there is no error.
QString errorMessage () const
Returns the error message of this QScriptSyntaxCheckResult, or an empty string if there is no error.
QScriptSyntaxCheckResult & operator= (const QScriptSyntaxCheckResult &other)
Assigns the other result to this QScriptSyntaxCheckResult, and returns a reference to this QScriptSyntaxCheckResult.
QScriptSyntaxCheckResult (const QScriptSyntaxCheckResult &other)
Constructs a new QScriptSyntaxCheckResult from the other result.
State state () const
Returns the state of this QScriptSyntaxCheckResult.
~QScriptSyntaxCheckResult ()
Destroys this QScriptSyntaxCheckResult.
Private Functions
QScriptSyntaxCheckResult ()
QScriptSyntaxCheckResult (QScriptSyntaxCheckResultPrivate *d)
Properties
QExplicitlySharedDataPointer< QScriptSyntaxCheckResultPrivate > d_ptr
Friends
class QScriptEngine
class QScriptEnginePrivate
Detailed Description
The QScriptSyntaxCheckResult class provides the result of a script syntax check.
Since
4.5
QScriptSyntaxCheckResult is returned by QScriptEngine::checkSyntax() to provide information about the syntactical (in)correctness of a script.
Definition at line 75 of file qscriptengine.h.
Enumerations
State
enum QScriptSyntaxCheckResult::State
This enum specifies the state of a syntax check.
Error The program contains a syntax error.
Intermediate The program is incomplete.
Valid The program is a syntactically correct Qt Script program.
Enumerator
Error
Intermediate
Valid
Definition at line 78 of file qscriptengine.h.
                {
         Error,
         Intermediate,
         Valid
     };
Constructors and Destructors
QScriptSyntaxCheckResult() [1/3]
QScriptSyntaxCheckResult::QScriptSyntaxCheckResult (const QScriptSyntaxCheckResult & other)
Constructs a new QScriptSyntaxCheckResult from the other result.
Definition at line 4463 of file qscriptengine.cpp.
     : d_ptr(other.d_ptr)
 {
 }
~QScriptSyntaxCheckResult()
QScriptSyntaxCheckResult::~QScriptSyntaxCheckResult ()
Destroys this QScriptSyntaxCheckResult.
Definition at line 4487 of file qscriptengine.cpp.
 {
 }
QScriptSyntaxCheckResult() [2/3]
QScriptSyntaxCheckResult::QScriptSyntaxCheckResult () private
Warning
This function is not part of the public interface.
Definition at line 4479 of file qscriptengine.cpp.
     : d_ptr(0)
 {
 }
QScriptSyntaxCheckResult() [3/3]
QScriptSyntaxCheckResult::QScriptSyntaxCheckResult (QScriptSyntaxCheckResultPrivate * d) private
Warning
This function is not part of the public interface.
Definition at line 4471 of file qscriptengine.cpp.
     : d_ptr(d)
 {
 }
Functions
errorColumnNumber()
int QScriptSyntaxCheckResult::errorColumnNumber () const
Returns the error column number of this QScriptSyntaxCheckResult, or -1 if there is no error.
See also
state(), errorLineNumber()
Definition at line 4522 of file qscriptengine.cpp.
 {
     Q_D(const QScriptSyntaxCheckResult);
     if (!d)
         return -1;
     return d->errorColumnNumber;
 }
errorLineNumber()
int QScriptSyntaxCheckResult::errorLineNumber () const
Returns the error line number of this QScriptSyntaxCheckResult, or -1 if there is no error.
See also
state(), errorMessage()
Definition at line 4508 of file qscriptengine.cpp.
 {
     Q_D(const QScriptSyntaxCheckResult);
     if (!d)
         return -1;
     return d->errorLineNumber;
 }
errorMessage()
QString QScriptSyntaxCheckResult::errorMessage () const
Returns the error message of this QScriptSyntaxCheckResult, or an empty string if there is no error.
See also
state(), errorLineNumber()
Definition at line 4536 of file qscriptengine.cpp.
 {
     Q_D(const QScriptSyntaxCheckResult);
     if (!d)
         return QString();
     return d->errorMessage;
 }
operator=()
QScriptSyntaxCheckResult & QScriptSyntaxCheckResult::operator= (const QScriptSyntaxCheckResult & other)
Assigns the other result to this QScriptSyntaxCheckResult, and returns a reference to this QScriptSyntaxCheckResult.
Definition at line 4548 of file qscriptengine.cpp.
 {
     d_ptr = other.d_ptr;
     return *this;
 }
state()
QScriptSyntaxCheckResult::State QScriptSyntaxCheckResult::state () const
Returns the state of this QScriptSyntaxCheckResult.
Definition at line 4494 of file qscriptengine.cpp.
Referenced by QScriptDebuggerConsole::consumeInput(), QScriptDebuggerLocalsItemDelegate::validateInput(), and QScriptBreakpointsItemDelegate::validateInput().
 {
     Q_D(const QScriptSyntaxCheckResult);
     if (!d)
         return Valid;
     return d->state;
 }
Friends and Related Functions
QScriptEngine
friend class QScriptEngine friend
Definition at line 100 of file qscriptengine.h.
QScriptEnginePrivate
friend class QScriptEnginePrivate friend
Definition at line 101 of file qscriptengine.h.
Properties
d_ptr
QExplicitlySharedDataPointer<QScriptSyntaxCheckResultPrivate> QScriptSyntaxCheckResult::d_ptr private
Definition at line 97 of file qscriptengine.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
/src/script/api/qscriptengine.h
/src/script/api/qscriptengine.cpp