Qt 4.8: QMultiScreenCursor Class Reference
QMultiScreenCursor Class Reference
Public Functions
void addCursor (QScreenCursor *cursor)
void hide ()
Hides the cursor from the screen.
void move (int x, int y)
Moves the mouse cursor to the given position, i.e., (x, y).
QMultiScreenCursor ()
void set (const QImage &image, int hotx, int hoty)
Sets the cursor's image to be the given image.
void show ()
Shows the mouse cursor.
~QMultiScreenCursor ()
Public Functions inherited from QScreenCursor
QRect boundingRect () const
Returns the cursor's bounding rectangle.
QImage image () const
Returns the cursor's image.
bool isAccelerated () const
Returns true if the cursor is accelerated; otherwise false.
bool isVisible () const
Returns true if the cursor is visible; otherwise false.
QScreenCursor ()
Constructs a screen cursor.
bool supportsAlphaCursor () const
virtual ~QScreenCursor ()
Destroys the screen cursor.
Private Functions
void setCurrentCursor (QScreenCursor *newCursor)
Properties
QScreenCursor * currentCursor
QList< QScreenCursor * > cursors
Additional Inherited Members
Static Public Functions inherited from QScreenCursor
static bool enabled ()
static void initSoftwareCursor ()
Initializes the screen cursor.
static QScreenCursor * instance ()
Protected Variables inherited from QScreenCursor
QImage cursor
uint enable: 1
QPoint hotspot
uint hwaccel: 1
QPoint pos
QSize size
uint supportsAlpha: 1
Detailed Description
Definition at line 55 of file qscreenmulti_qws.cpp.
Constructors and Destructors
QMultiScreenCursor()
QMultiScreenCursor::QMultiScreenCursor () inline
Definition at line 58 of file qscreenmulti_qws.cpp.
 : currentCursor(qt_screencursor) { enable = false; }
~QMultiScreenCursor()
QMultiScreenCursor::~QMultiScreenCursor () inline
Definition at line 59 of file qscreenmulti_qws.cpp.
 { qt_screencursor = 0; }
Functions
addCursor()
void QMultiScreenCursor::addCursor (QScreenCursor * cursor)
Definition at line 135 of file qscreenmulti_qws.cpp.
Referenced by QMultiScreen::initDevice(), and ~QMultiScreenCursor().
 {
     cursors.append(cursor);
 }
hide()
void QMultiScreenCursor::hide () virtual
Hides the cursor from the screen.
See also
show()
Reimplemented from QScreenCursor.
Definition at line 129 of file qscreenmulti_qws.cpp.
Referenced by ~QMultiScreenCursor().
 {
     if (currentCursor)
         currentCursor->hide();
 }
move()
void QMultiScreenCursor::move (int x, int y) virtual
Moves the mouse cursor to the given position, i.e., (x, y).
Note that the given position defines the top-left corner of the cursor's image, i.e., not the cursor's hot spot (the position of the associated mouse events).
See also
set()
Reimplemented from QScreenCursor.
Definition at line 89 of file qscreenmulti_qws.cpp.
Referenced by ~QMultiScreenCursor().
 {
     const int oldIndex = qt_screen->subScreenIndexAt(pos);
     QScreenCursor::move(x, y); // updates pos
     const int newIndex = qt_screen->subScreenIndexAt(pos);
     if (!currentCursor && oldIndex != -1)
         setCurrentCursor(cursors.at(oldIndex));
     QScreenCursor *oldCursor = currentCursor;
     if (oldIndex != -1) {
         const QScreen *oldScreen = qt_screen->subScreens().at(oldIndex);
         if (newIndex == -1 || oldScreen->region().contains(pos)) {
             oldCursor->move(x, y);
             return;
         }
     }
     if (newIndex != -1) {
         QScreenCursor *newCursor = cursors.at(newIndex);
         newCursor->set(cursor, hotspot.x(), hotspot.y());
         if (oldCursor) {
             if (oldCursor->isVisible())
                 newCursor->show();
             oldCursor->hide();
         }
         newCursor->move(x, y);
         setCurrentCursor(newCursor);
     }
 }
set()
void QMultiScreenCursor::set (const QImage & image, int hotx, int hoty) virtual
Sets the cursor's image to be the given image.
The hotx and hoty parameters define the cursor's hot spot, i.e., the point within the cursor's image that will be the position of the associated mouse events.
See also
move()
Reimplemented from QScreenCursor.
Definition at line 75 of file qscreenmulti_qws.cpp.
 {
     QScreenCursor::set(image, hotx, hoty);
     if (currentCursor)
         currentCursor->set(image, hotx, hoty);
 }
setCurrentCursor()
void QMultiScreenCursor::setCurrentCursor (QScreenCursor * newCursor) private
Definition at line 82 of file qscreenmulti_qws.cpp.
Referenced by move(), and ~QMultiScreenCursor().
 {
     *((QScreenCursor*)this) = *newCursor;
     currentCursor = newCursor;
 }
show()
void QMultiScreenCursor::show () virtual
Shows the mouse cursor.
See also
hide()
Reimplemented from QScreenCursor.
Definition at line 123 of file qscreenmulti_qws.cpp.
Referenced by ~QMultiScreenCursor().
 {
     if (currentCursor)
         currentCursor->show();
 }
Properties
currentCursor
QScreenCursor* QMultiScreenCursor::currentCursor private
Definition at line 71 of file qscreenmulti_qws.cpp.
Referenced by hide(), move(), set(), setCurrentCursor(), and show().
cursors
QList<QScreenCursor*> QMultiScreenCursor::cursors private
Definition at line 72 of file qscreenmulti_qws.cpp.
Referenced by addCursor(), and move().
The documentation for this class was generated from the following file:
/src/gui/embedded/qscreenmulti_qws.cpp