Qt 4.8: QExtendedInformation Class Reference
QExtendedInformation Class Reference
#include <qfileinfogatherer_p.h>
Public Types
enum Type { Dir, File, System }
Public Functions
QFileInfo fileInfo () const
bool isCaseSensitive () const
bool isDir ()
bool isFile ()
bool isHidden () const
bool isSymLink (bool ignoreNtfsSymLinks=false) const
bool isSystem ()
QDateTime lastModified () const
bool operator== (const QExtendedInformation &fileInfo) const
QFile::Permissions permissions () const
QExtendedInformation ()
QExtendedInformation (const QFileInfo &info)
qint64 size () const
Type type () const
Public Variables
QString displayType
QIcon icon
Properties
QFileInfo mFileInfo
Detailed Description
Definition at line 70 of file qfileinfogatherer_p.h.
Enumerations
Type
enum QExtendedInformation::Type
Enumerator
Dir
File
System
Definition at line 72 of file qfileinfogatherer_p.h.
 { Dir, File, System };
Constructors and Destructors
QExtendedInformation() [1/2]
QExtendedInformation::QExtendedInformation () inline
Definition at line 74 of file qfileinfogatherer_p.h.
 {}
QExtendedInformation() [2/2]
QExtendedInformation::QExtendedInformation (const QFileInfo & info) inline
Definition at line 75 of file qfileinfogatherer_p.h.
 : mFileInfo(info) {}
Functions
fileInfo()
QFileInfo QExtendedInformation::fileInfo () const inline
Definition at line 125 of file qfileinfogatherer_p.h.
Referenced by QFileSystemModelPrivate::QFileSystemNode::populate(), and QFileSystemModel::setData().
{
         return mFileInfo;
     }
isCaseSensitive()
bool QExtendedInformation::isCaseSensitive () const inline
Definition at line 88 of file qfileinfogatherer_p.h.
{
         QFSFileEngine fe(mFileInfo.absoluteFilePath());
         return fe.caseSensitive();
     }
isDir()
bool QExtendedInformation::isDir () inline
Definition at line 77 of file qfileinfogatherer_p.h.
 { return type() == Dir; }
isFile()
bool QExtendedInformation::isFile () inline
Definition at line 78 of file qfileinfogatherer_p.h.
 { return type() == File; }
isHidden()
bool QExtendedInformation::isHidden () const inline
Definition at line 121 of file qfileinfogatherer_p.h.
{
         return mFileInfo.isHidden();
     }
isSymLink()
bool QExtendedInformation::isSymLink (bool ignoreNtfsSymLinks = false) const inline
Definition at line 111 of file qfileinfogatherer_p.h.
Referenced by QFileInfoGatherer::getInfo().
     {
         if (ignoreNtfsSymLinks) {
 #ifdef Q_WS_WIN
             return !mFileInfo.suffix().compare(QLatin1String("lnk"), Qt::CaseInsensitive);
 #endif
         }
         return mFileInfo.isSymLink();
     }
isSystem()
bool QExtendedInformation::isSystem () inline
Definition at line 79 of file qfileinfogatherer_p.h.
 { return type() == System; }
lastModified()
QDateTime QExtendedInformation::lastModified () const inline
Definition at line 129 of file qfileinfogatherer_p.h.
{
         return mFileInfo.lastModified();
     }
operator==()
bool QExtendedInformation::operator== (const QExtendedInformation & fileInfo) const inline
Definition at line 81 of file qfileinfogatherer_p.h.
{
        return mFileInfo == fileInfo.mFileInfo
        && displayType == fileInfo.displayType
        && permissions() == fileInfo.permissions();
     }
permissions()
QFile::Permissions QExtendedInformation::permissions () const inline
Definition at line 94 of file qfileinfogatherer_p.h.
Referenced by operator==().
{
         return mFileInfo.permissions();
     }
size()
qint64 QExtendedInformation::size () const inline
Definition at line 133 of file qfileinfogatherer_p.h.
Referenced by QFileInfoGatherer::getInfo().
{
         qint64 size = -1;
         if (type() == QExtendedInformation::Dir)
             size = 0;
         if (type() == QExtendedInformation::File)
             size = mFileInfo.size();
         if (!mFileInfo.exists() && !mFileInfo.isSymLink())
             size = -1;
         return size;
     }
type()
Type QExtendedInformation::type () const inline
Definition at line 98 of file qfileinfogatherer_p.h.
Referenced by isDir(), isFile(), isSystem(), and size().
                       {
         if (mFileInfo.isDir()) {
             return QExtendedInformation::Dir;
         }
         if (mFileInfo.isFile()) {
             return QExtendedInformation::File;
         }
         if (!mFileInfo.exists() && mFileInfo.isSymLink()) {
             return QExtendedInformation::System;
         }
         return QExtendedInformation::System;
     }
Properties
displayType
QString QExtendedInformation::displayType
Definition at line 144 of file qfileinfogatherer_p.h.
Referenced by QFileInfoGatherer::getInfo(), and operator==().
icon
QIcon QExtendedInformation::icon
Definition at line 145 of file qfileinfogatherer_p.h.
Referenced by QFileInfoGatherer::getInfo().
mFileInfo
QFileInfo QExtendedInformation::mFileInfo private
Definition at line 148 of file qfileinfogatherer_p.h.
Referenced by fileInfo(), isCaseSensitive(), isHidden(), isSymLink(), lastModified(), operator==(), permissions(), size(), and type().
The documentation for this class was generated from the following file:
/src/gui/dialogs/qfileinfogatherer_p.h