Qt 4.8: QPatternist::ResourceDelegator Class Reference
QPatternist::ResourceDelegator Class Reference
Delegates to another ResourceLoader, but in case a URI is in an exception list, it delegates to a different loader.
#include <qresourcedelegator_p.h>
Public Functions
virtual SequenceType::Ptr announceCollection (const QUrl &uri)
May be called by the compilation framework at compile time to report that an node collection referenced by uri will be loaded at runtime.
virtual SequenceType::Ptr announceDocument (const QUrl &uri, const Usage usageHint)
May be called by the compilation framework at compile time to report that an XML document referenced by uri will be loaded at runtime.
virtual ItemType::Ptr announceUnparsedText (const QUrl &uri)
May be called by the compilation framework at compile time to report that an unparsed text(plain text) file referenced by uri will be loaded at runtime.
virtual QSet< QUrl > deviceURIs () const
virtual bool isDocumentAvailable (const QUrl &uri)
Calls to this function are generated by calls to the fn:doc-available() function.
virtual bool isUnparsedTextAvailable (const QUrl &uri, const QString &encoding)
Calls to this function are generated by calls to the fn:unparsed-text-available() function.
virtual Item::Iterator::Ptr openCollection (const QUrl &uri)
Calls to this function are generated by calls to the fn:collection() function.
virtual Item openDocument (const QUrl &uri, const ReportContext::Ptr &context)
Calls to this function are generated by calls to the fn:document() or fn:doc() function.
virtual Item openUnparsedText (const QUrl &uri, const QString &encoding, const ReportContext::Ptr &context, const SourceLocationReflection *const where)
Calls to this function are generated by calls to the fn:unparsed-text() function.
ResourceDelegator (const QSet< QUrl > &needsOverride, const ResourceLoader::Ptr &parentLoader, const ResourceLoader::Ptr &forDeviceLoader)
Public Functions inherited from QPatternist::ResourceLoader
virtual void clear (const QUrl &uri)
Asks to unload uri from its document pool, such that a subsequent request will require a new read.
ResourceLoader ()
virtual ~ResourceLoader ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Properties
const ResourceDelegator::Ptr m_forDeviceLoader
const QSet< QUrl > m_needsOverride
const ResourceLoader::Ptr m_parentLoader
Additional Inherited Members
Public Types inherited from QPatternist::DeviceResourceLoader
typedef QExplicitlySharedDataPointer< DeviceResourceLoader > Ptr
Public Types inherited from QPatternist::ResourceLoader
typedef QExplicitlySharedDataPointer< ResourceLoader > Ptr
enum Usage { MayUse, WillUse }
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Delegates to another ResourceLoader, but in case a URI is in an exception list, it delegates to a different loader.
This is used for handling device variables, since when a device variable is rebound, a resource loader needs to carry that binding, while the resource loader for the other query remains as is.
Since
4.5
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 76 of file qresourcedelegator_p.h.
Constructors and Destructors
ResourceDelegator()
QPatternist::ResourceDelegator::ResourceDelegator (const QSet< QUrl > & needsOverride, const ResourceLoader::Ptr & parentLoader, const ResourceLoader::Ptr & forDeviceLoader) inline
Definition at line 79 of file qresourcedelegator_p.h.
                                                                     : m_needsOverride(needsOverride)
                                                                       , m_parentLoader(parentLoader)
                                                                       , m_forDeviceLoader(forDeviceLoader)
         {
             Q_ASSERT(m_parentLoader);
         }
Functions
announceCollection()
SequenceType::Ptr ResourceDelegator::announceCollection (const QUrl & uri) virtual
May be called by the compilation framework at compile time to report that an node collection referenced by uri will be loaded at runtime.
This function can be called an arbitrary amount of times for the same URI. How many times it is called for a URI has no meaning(beyond the first call, that is). For what queries the compilation framework can determine what always will be loaded is generally undefined. It depends on factors such as how simple the query is what information that is statically available and subsequently what optimizations that can apply.
Calls to this function are generated by calls to the fn:collection() function.
Note
This function is responsible for execution stability. Subsequent calls to this function with the same URI should result in QXmlNodeModelIndex instances that have the same identity. However, in some cases this stability is not of interest, see the specification for details.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
Returns
null if the ResourceLoader can determine at this stage that no document referenced by uri will ever be possible to load.
The appropriate sequence type if loading uri succeeds at runtime. This must be CommonSequenceTypes::zeroOrMoreNodes or a sequence type that is a sub type of it.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.6 fn:collection
Reimplemented from QPatternist::ResourceLoader.
Definition at line 91 of file qresourcedelegator.cpp.
Referenced by ResourceDelegator().
 {
     return m_parentLoader->announceCollection(uri);
 }
announceDocument()
SequenceType::Ptr ResourceDelegator::announceDocument (const QUrl & uri, const Usage usageHint) virtual
May be called by the compilation framework at compile time to report that an XML document referenced by uri will be loaded at runtime.
This function can be called an arbitrary amount of times for the same URI, but different usageHint values. How many times it is called for a URI has no meaning(beyond the first call, that is). For what queries the compilation framework can determine what always will be loaded is generally undefined. It depends on factors such as the complexity of the query, what information that is statically available and subsequently what optimizations that can be applied.
Calls to this function are generated by calls to the fn:document() or fn:doc() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
usageHint A hint to how the URI will be used.
Returns
null if the ResourceLoader can determine at this stage that no document referenced by uri will ever be possible to load.
The appropriate sequence type if loading uri succeeds at runtime. This must be CommonSequenceTypes::zeroOrOneDocument, CommonSequenceTypes::exactlyOneDocument or a sequence type that is a sub type of it.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.4 fn:doc
XSL Transformations (XSLT) Version 2.0, 16.1 Multiple Source Documents
Reimplemented from QPatternist::ResourceLoader.
Definition at line 76 of file qresourcedelegator.cpp.
Referenced by ResourceDelegator().
 {
     return m_parentLoader->announceDocument(uri, usageHint);
 }
announceUnparsedText()
ItemType::Ptr ResourceDelegator::announceUnparsedText (const QUrl & uri) virtual
May be called by the compilation framework at compile time to report that an unparsed text(plain text) file referenced by uri will be loaded at runtime.
This function can be called an arbitrary amount of times for the same URI. How many times it is called for a URI has no meaning(beyond the first call, that is). For what queries the compilation framework can determine what always will be loaded is generally undefined. It depends on factors such as how simple the query is what information that is statically available and subsequently what optimizations that can apply.
Calls to this function are generated by calls to the fn:unparsed-text() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
See also
XSL Transformations (XSLT) Version 2.0, 16.2 Reading Text Files
Returns
null if no unparsed file can be loaded for uri
The item type that the value loaded by uri will be an instance of. This is typically xs:string
Reimplemented from QPatternist::ResourceLoader.
Definition at line 54 of file qresourcedelegator.cpp.
Referenced by ResourceDelegator().
 {
     return m_parentLoader->announceUnparsedText(uri);
 }
deviceURIs()
QSet< QUrl > ResourceDelegator::deviceURIs () const virtual
Returns the union of the deviceURIs() that ResourceDelegator's two resource loaders has.
Implements QPatternist::DeviceResourceLoader.
Definition at line 96 of file qresourcedelegator.cpp.
Referenced by ResourceDelegator().
 {
     QSet<QUrl> uris(m_needsOverride);
     uris |= m_forDeviceLoader->deviceURIs();
     return uris;
 }
isDocumentAvailable()
bool ResourceDelegator::isDocumentAvailable (const QUrl & uri) virtual
Calls to this function are generated by calls to the fn:doc-available() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
Returns
true if calling openDocument() while passing uri will successfully load the document.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.5 fn:doc-available
XSL Transformations (XSLT) Version 2.0, 16.1 Multiple Source Documents
Reimplemented from QPatternist::ResourceLoader.
Definition at line 81 of file qresourcedelegator.cpp.
Referenced by ResourceDelegator().
 {
     return m_parentLoader->isDocumentAvailable(uri);
 }
isUnparsedTextAvailable()
bool ResourceDelegator::isUnparsedTextAvailable (const QUrl & uri, const QString & encoding) virtual
Calls to this function are generated by calls to the fn:unparsed-text-available() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
Returns
true if calling openUnparsedText() while passing uri will successfully load the document.
See also
XSL Transformations (XSLT) Version 2.0, 16.2 Reading Text Files
Reimplemented from QPatternist::ResourceLoader.
Definition at line 48 of file qresourcedelegator.cpp.
Referenced by ResourceDelegator().
 {
     return m_parentLoader->isUnparsedTextAvailable(uri, encoding);
 }
openCollection()
Item::Iterator::Ptr ResourceDelegator::openCollection (const QUrl & uri) virtual
Calls to this function are generated by calls to the fn:collection() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.6 fn:collection
Returns
null if no node collection can be loaded for uri
An QAbstractXmlForwardIterator representing the content identified by uri. Remember that the content of the QAbstractXmlForwardIterator must match the sequence type returned by announceCollection()
Reimplemented from QPatternist::ResourceLoader.
Definition at line 86 of file qresourcedelegator.cpp.
Referenced by ResourceDelegator().
 {
     return m_parentLoader->openCollection(uri);
 }
openDocument()
Item ResourceDelegator::openDocument (const QUrl & uri, const ReportContext::Ptr & context) virtual
Calls to this function are generated by calls to the fn:document() or fn:doc() function.
Note
This function is responsible for execution stability. Subsequent calls to this function with the same URI should result in QXmlNodeModelIndex instances that have the same identity. However, in some cases this stability is not of interest, see the specification for details.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
See also
QXmlNodeModelIndex::identity()
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.4 fn:doc
XSL Transformations (XSLT) Version 2.0, 16.1 Multiple Source Documents
Returns
null if no document can be loaded for uri
A QXmlNodeModelIndex representing the document identified by uri. Remember that the QXmlNodeModelIndex must match the sequence type returned by announceDocument()
Reimplemented from QPatternist::ResourceLoader.
Definition at line 67 of file qresourcedelegator.cpp.
Referenced by ResourceDelegator().
 {
     if(m_needsOverride.contains(uri))
         return m_forDeviceLoader->openDocument(uri, context);
     else
         return m_parentLoader->openDocument(uri, context);
 }
openUnparsedText()
Item ResourceDelegator::openUnparsedText (const QUrl & uri, const QString & encoding, const ReportContext::Ptr & context, const SourceLocationReflection *const where) virtual
Calls to this function are generated by calls to the fn:unparsed-text() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
encoding the encoding to use. If empty, the user hasn't expressed any encoding to use.
See also
XSL Transformations (XSLT) Version 2.0, 16.2 Reading Text Files
Returns
null if no unparsed file can be loaded for uri
An xs:string value(or subtype) containing the content of the file identified by uri as text. Remember that its type must match the sequence type returned by announceUnparsedText()
Reimplemented from QPatternist::ResourceLoader.
Definition at line 59 of file qresourcedelegator.cpp.
Referenced by ResourceDelegator().
 {
     return m_parentLoader->openUnparsedText(uri, encoding, context, where);
 }
Properties
m_forDeviceLoader
const ResourceDelegator::Ptr QPatternist::ResourceDelegator::m_forDeviceLoader private
Definition at line 112 of file qresourcedelegator_p.h.
Referenced by deviceURIs(), and openDocument().
m_needsOverride
const QSet<QUrl> QPatternist::ResourceDelegator::m_needsOverride private
Definition at line 110 of file qresourcedelegator_p.h.
Referenced by deviceURIs(), and openDocument().
m_parentLoader
const ResourceLoader::Ptr QPatternist::ResourceDelegator::m_parentLoader private
Definition at line 111 of file qresourcedelegator_p.h.
Referenced by announceCollection(), announceDocument(), announceUnparsedText(), isDocumentAvailable(), isUnparsedTextAvailable(), openCollection(), openDocument(), openUnparsedText(), and ResourceDelegator().
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qresourcedelegator_p.h
/src/xmlpatterns/api/qresourcedelegator.cpp