Qt 4.8: QWaylandGLContext Class Reference
QWaylandGLContext Class Reference
#include <qwaylandglcontext.h>
Public Functions
void doneCurrent ()
Reimplement in subclass to release current context.
EGLConfig eglConfig () const
void * getProcAddress (const QString &)
Reimplement in subclass to native getProcAddr calls.
void makeCurrent ()
Reimplement in subclass to do makeCurrent on native GL context.
QPlatformWindowFormat platformWindowFormat () const
QWidget has the function qplatformWindowFormat().
QWaylandGLContext (EGLDisplay eglDisplay, const QPlatformWindowFormat &format)
void setEglSurface (EGLSurface surface)
void swapBuffers ()
Reimplement in subclass to native swap buffers calls.
~QWaylandGLContext ()
Public Functions inherited from QPlatformGLContext
QPlatformGLContext ()
All subclasses needs to specify the platformWindow.
virtual ~QPlatformGLContext ()
If this is the current context for the thread, doneCurrent is called.
Private Functions
QWaylandGLContext ()
Properties
EGLConfig mConfig
EGLContext mContext
EGLDisplay mEglDisplay
QPlatformWindowFormat mFormat
EGLSurface mSurface
Additional Inherited Members
Static Public Functions inherited from QPlatformGLContext
static const QPlatformGLContext * currentContext ()
Returns the last context which called makeCurrent.
Protected Variables inherited from QPlatformGLContext
QScopedPointer< QPlatformGLContextPrivate > d_ptr
Detailed Description
Definition at line 54 of file qwaylandglcontext.h.
Constructors and Destructors
QWaylandGLContext() [1/2]
QWaylandGLContext::QWaylandGLContext (EGLDisplay eglDisplay, const QPlatformWindowFormat & format)
Definition at line 53 of file qwaylandglcontext.cpp.
     : QPlatformGLContext()
     , mEglDisplay(eglDisplay)
     , mSurface(EGL_NO_SURFACE)
     , mConfig(q_configFromQPlatformWindowFormat(mEglDisplay,format,true))
     , mFormat(qt_qPlatformWindowFormatFromConfig(mEglDisplay,mConfig))
 {
     QPlatformGLContext *sharePlatformContext = 0;
     sharePlatformContext = format.sharedGLContext();
     mFormat.setSharedContext(sharePlatformContext);
     EGLContext shareEGLContext = EGL_NO_CONTEXT;
     if (sharePlatformContext)
         shareEGLContext = static_cast<const QWaylandGLContext*>(sharePlatformContext)->mContext;
     eglBindAPI(EGL_OPENGL_ES_API);
     QVector<EGLint> eglContextAttrs;
     eglContextAttrs.append(EGL_CONTEXT_CLIENT_VERSION);
     eglContextAttrs.append(2);
     eglContextAttrs.append(EGL_NONE);
     mContext = eglCreateContext(mEglDisplay, mConfig,
                                 shareEGLContext, eglContextAttrs.constData());
 }
~QWaylandGLContext()
QWaylandGLContext::~QWaylandGLContext ()
Definition at line 86 of file qwaylandglcontext.cpp.
 {
     eglDestroyContext(mEglDisplay,mContext);
 }
QWaylandGLContext() [2/2]
QWaylandGLContext::QWaylandGLContext () private
Definition at line 78 of file qwaylandglcontext.cpp.
     : QPlatformGLContext()
     , mEglDisplay(0)
     , mContext(EGL_NO_CONTEXT)
     , mSurface(EGL_NO_SURFACE)
     , mConfig(0)
 { }
Functions
doneCurrent()
void QWaylandGLContext::doneCurrent () virtual
Reimplement in subclass to release current context.
Typically this is calling makeCurrent with 0 "surface"
Reimplemented from QPlatformGLContext.
Definition at line 100 of file qwaylandglcontext.cpp.
Referenced by setEglSurface().
 {
     QPlatformGLContext::doneCurrent();
     eglMakeCurrent(mEglDisplay, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
 }
eglConfig()
EGLConfig QWaylandGLContext::eglConfig () const
Definition at line 129 of file qwaylandglcontext.cpp.
Referenced by QWaylandEglWindow::glContext(), QWaylandEglWindow::newSurfaceCreated(), and platformWindowFormat().
 {
     return mConfig;
 }
getProcAddress()
void * QWaylandGLContext::getProcAddress (const QString & procName) virtual
Reimplement in subclass to native getProcAddr calls.
Note: its convenient to use qPrintable(const QString &str) to get the const char * pointer
Implements QPlatformGLContext.
Definition at line 111 of file qwaylandglcontext.cpp.
 {
     return (void *) eglGetProcAddress(string.toLatin1().data());
 }
makeCurrent()
void QWaylandGLContext::makeCurrent () virtual
Reimplement in subclass to do makeCurrent on native GL context.
Reimplemented from QPlatformGLContext.
Definition at line 91 of file qwaylandglcontext.cpp.
Referenced by setEglSurface().
 {
     QPlatformGLContext::makeCurrent();
     if (mSurface == EGL_NO_SURFACE) {
         qWarning("makeCurrent with EGL_NO_SURFACE");
     }
     eglMakeCurrent(mEglDisplay, mSurface, mSurface, mContext);
 }
platformWindowFormat()
QPlatformWindowFormat QWaylandGLContext::platformWindowFormat () const inline virtual
QWidget has the function qplatformWindowFormat().
That function is for the application programmer to request the format of the window and the context that he wants.
Reimplement this function in a subclass to indicate what format the glContext actually has.
Implements QPlatformGLContext.
Definition at line 63 of file qwaylandglcontext.h.
 { return mFormat; }
setEglSurface()
void QWaylandGLContext::setEglSurface (EGLSurface surface)
Definition at line 116 of file qwaylandglcontext.cpp.
Referenced by QWaylandEglWindow::glContext(), QWaylandEglWindow::newSurfaceCreated(), and platformWindowFormat().
 {
     bool wasCurrent = false;
     if (QPlatformGLContext::currentContext() == this) {
         wasCurrent = true;
         doneCurrent();
     }
     mSurface = surface;
     if (wasCurrent) {
         makeCurrent();
     }
 }
swapBuffers()
void QWaylandGLContext::swapBuffers () virtual
Reimplement in subclass to native swap buffers calls.
Implements QPlatformGLContext.
Definition at line 106 of file qwaylandglcontext.cpp.
 {
     eglSwapBuffers(mEglDisplay,mSurface);
 }
Properties
mConfig
EGLConfig QWaylandGLContext::mConfig private
Definition at line 72 of file qwaylandglcontext.h.
Referenced by eglConfig(), and QWaylandGLContext().
mContext
EGLContext QWaylandGLContext::mContext private
Definition at line 70 of file qwaylandglcontext.h.
Referenced by makeCurrent(), QWaylandGLContext(), and ~QWaylandGLContext().
mEglDisplay
EGLDisplay QWaylandGLContext::mEglDisplay private
Definition at line 68 of file qwaylandglcontext.h.
Referenced by doneCurrent(), makeCurrent(), QWaylandGLContext(), swapBuffers(), and ~QWaylandGLContext().
mFormat
QPlatformWindowFormat QWaylandGLContext::mFormat private
Definition at line 73 of file qwaylandglcontext.h.
Referenced by platformWindowFormat(), and QWaylandGLContext().
mSurface
EGLSurface QWaylandGLContext::mSurface private
Definition at line 71 of file qwaylandglcontext.h.
Referenced by makeCurrent(), setEglSurface(), and swapBuffers().
The documentation for this class was generated from the following files:
/src/plugins/platforms/wayland/gl_integration/wayland_egl/qwaylandglcontext.h
/src/plugins/platforms/wayland/gl_integration/wayland_egl/qwaylandglcontext.cpp