Qt 4.8: QNetworkManagerInterfaceDeviceWireless Class Reference
QNetworkManagerInterfaceDeviceWireless Class Reference
#include <qnetworkmanagerservice.h>
Public Types
enum DeviceCapability {
None = 0x0, Wep40 = 0x1, Wep104 = 0x2, Tkip = 0x4,
Ccmp = 0x8, Wpa = 0x10, Rsn = 0x20
}
Signals
void accessPointAdded (const QString &, QDBusObjectPath)
void accessPointRemoved (const QString &, QDBusObjectPath)
void propertiesChanged (const QString &, QMap< QString, QVariant >)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDBusObjectPath activeAccessPoint () const
quint32 bitrate () const
QDBusInterface * connectionInterface () const
QList< QDBusObjectPath > getAccessPoints ()
QString hwAddress () const
bool isValid ()
quint32 mode () const
QDBusObjectPath path () const
QNetworkManagerInterfaceDeviceWireless (const QString &ifaceDevicePath, QObject *parent=0)
bool setConnections ()
quint32 wirelessCapabilities () const
~QNetworkManagerInterfaceDeviceWireless ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QNetworkManagerInterfaceDeviceWirelessPrivate * d
QNmDBusHelper * nmDBusHelper
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 299 of file qnetworkmanagerservice.h.
Enumerations
DeviceCapability
enum QNetworkManagerInterfaceDeviceWireless::DeviceCapability
Enumerator
None
Wep40
Wep104
Tkip
Ccmp
Wpa
Rsn
Definition at line 305 of file qnetworkmanagerservice.h.
{
         None = 0x0,
         Wep40 = 0x1,
         Wep104 = 0x2,
         Tkip = 0x4,
         Ccmp = 0x8,
         Wpa = 0x10,
         Rsn = 0x20
        };
Constructors and Destructors
QNetworkManagerInterfaceDeviceWireless()
QNetworkManagerInterfaceDeviceWireless::QNetworkManagerInterfaceDeviceWireless (const QString & ifaceDevicePath, QObject * parent = 0) explicit
Definition at line 469 of file qnetworkmanagerservice.cpp.
     : QObject(parent), nmDBusHelper(0)
 {
     d = new QNetworkManagerInterfaceDeviceWirelessPrivate();
     d->path = ifaceDevicePath;
     d->connectionInterface = new QDBusInterface(QLatin1String(NM_DBUS_SERVICE),
                                                 d->path,
                                                 QLatin1String(NM_DBUS_INTERFACE_DEVICE_WIRELESS),
                                                 dbusConnection, parent);
     if (!d->connectionInterface->isValid()) {
         d->valid = false;
         return;
     }
     d->valid = true;
 }
~QNetworkManagerInterfaceDeviceWireless()
QNetworkManagerInterfaceDeviceWireless::~QNetworkManagerInterfaceDeviceWireless ()
Definition at line 485 of file qnetworkmanagerservice.cpp.
 {
     delete d->connectionInterface;
     delete d;
 }
Functions
accessPointAdded
void QNetworkManagerInterfaceDeviceWireless::accessPointAdded (const QString & , QDBusObjectPath) signal
Referenced by setConnections().
accessPointRemoved
void QNetworkManagerInterfaceDeviceWireless::accessPointRemoved (const QString & , QDBusObjectPath) signal
Referenced by setConnections().
activeAccessPoint()
QDBusObjectPath QNetworkManagerInterfaceDeviceWireless::activeAccessPoint () const
Definition at line 568 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("ActiveAccessPoint").value<QDBusObjectPath>();
 }
bitrate()
quint32 QNetworkManagerInterfaceDeviceWireless::bitrate () const
Definition at line 563 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("Bitrate").toUInt();
 }
connectionInterface()
QDBusInterface * QNetworkManagerInterfaceDeviceWireless::connectionInterface () const
Definition at line 542 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface;
 }
getAccessPoints()
QList< QDBusObjectPath > QNetworkManagerInterfaceDeviceWireless::getAccessPoints ()
Definition at line 547 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::deviceAdded().
 {
     QDBusReply<QList<QDBusObjectPath> > reply = d->connectionInterface->call(QLatin1String("GetAccessPoints"));
     return reply.value();
 }
hwAddress()
QString QNetworkManagerInterfaceDeviceWireless::hwAddress () const
Definition at line 553 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("HwAddress").toString();
 }
isValid()
bool QNetworkManagerInterfaceDeviceWireless::isValid ()
Definition at line 491 of file qnetworkmanagerservice.cpp.
Referenced by setConnections().
 {
     return d->valid;
 }
mode()
quint32 QNetworkManagerInterfaceDeviceWireless::mode () const
Definition at line 558 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("Mode").toUInt();
 }
path()
QDBusObjectPath QNetworkManagerInterfaceDeviceWireless::path () const
propertiesChanged
void QNetworkManagerInterfaceDeviceWireless::propertiesChanged (const QString & , QMap< QString, QVariant >) signal
Referenced by setConnections().
setConnections()
bool QNetworkManagerInterfaceDeviceWireless::setConnections ()
Definition at line 496 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::deviceAdded().
 {
     if(!isValid() )
         return false;
     bool allOk = false;
     delete nmDBusHelper;
     nmDBusHelper = new QNmDBusHelper(this);
     connect(nmDBusHelper, SIGNAL(pathForPropertiesChanged(const QString &,QMap<QString,QVariant>)),
             this,SIGNAL(propertiesChanged( const QString &, QMap<QString,QVariant>)));
     connect(nmDBusHelper, SIGNAL(pathForAccessPointAdded(const QString &,QDBusObjectPath)),
             this,SIGNAL(accessPointAdded(const QString &,QDBusObjectPath)));
     connect(nmDBusHelper, SIGNAL(pathForAccessPointRemoved(const QString &,QDBusObjectPath)),
             this,SIGNAL(accessPointRemoved(const QString &,QDBusObjectPath)));
     if(!dbusConnection.connect(QLatin1String(NM_DBUS_SERVICE),
                               d->path,
                               QLatin1String(NM_DBUS_INTERFACE_DEVICE_WIRELESS),
                               QLatin1String("AccessPointAdded"),
                               nmDBusHelper, SLOT(slotAccessPointAdded( QDBusObjectPath )))) {
         allOk = true;
     }
     if(!dbusConnection.connect(QLatin1String(NM_DBUS_SERVICE),
                               d->path,
                               QLatin1String(NM_DBUS_INTERFACE_DEVICE_WIRELESS),
                               QLatin1String("AccessPointRemoved"),
                               nmDBusHelper, SLOT(slotAccessPointRemoved( QDBusObjectPath )))) {
         allOk = true;
     }
     if(!dbusConnection.connect(QLatin1String(NM_DBUS_SERVICE),
                               d->path,
                               QLatin1String(NM_DBUS_INTERFACE_DEVICE_WIRELESS),
                               QLatin1String("PropertiesChanged"),
                               nmDBusHelper,SLOT(slotPropertiesChanged( QMap<QString,QVariant>)))) {
         allOk = true;
     }
     return allOk;
 }
wirelessCapabilities()
quint32 QNetworkManagerInterfaceDeviceWireless::wirelessCapabilities () const
Definition at line 573 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("WirelelessCapabilities").toUInt();
 }
Properties
d
QNetworkManagerInterfaceDeviceWirelessPrivate* QNetworkManagerInterfaceDeviceWireless::d private
Definition at line 336 of file qnetworkmanagerservice.h.
Referenced by activeAccessPoint(), bitrate(), connectionInterface(), getAccessPoints(), hwAddress(), isValid(), mode(), QNetworkManagerInterfaceDeviceWireless(), setConnections(), wirelessCapabilities(), and ~QNetworkManagerInterfaceDeviceWireless().
nmDBusHelper
QNmDBusHelper* QNetworkManagerInterfaceDeviceWireless::nmDBusHelper private
Definition at line 337 of file qnetworkmanagerservice.h.
Referenced by setConnections().
The documentation for this class was generated from the following files:
/src/plugins/bearer/networkmanager/qnetworkmanagerservice.h
/src/plugins/bearer/networkmanager/qnetworkmanagerservice.cpp