Qt 4.8: QAbstractFontEngine Class Reference
QAbstractFontEngine Class Reference abstract
The QAbstractFontEngine class is the base class for font engine plugins in Qt for Embedded Linux.
#include <qabstractfontengine_qws.h>
Classes
class FixedPoint
QAbstractFontEngine::FixedPoint defines a point in the place using 26.6 fixed point precision.
class GlyphMetrics
QAbstractFontEngine::GlyphMetrics defines the metrics of a single glyph.
Public Types
enum Capability { CanOutlineGlyphs = 1, CanRenderGlyphs_Mono = 2, CanRenderGlyphs_Gray = 4, CanRenderGlyphs = CanRenderGlyphs_Mono | CanRenderGlyphs_Gray }
This enum describes the capabilities of a font engine.
typedef int Fixed
This type is int, interpreted as a 26.
enum FontProperty {
Ascent, Descent, Leading, XHeight,
AverageCharWidth, LineThickness, UnderlinePosition, MaxCharWidth,
MinLeftBearing, MinRightBearing, GlyphCount, CacheGlyphsHint,
OutlineGlyphsHint
}
This enum describes the properties of a font provided by a font engine.
enum TextShapingFlag { RightToLeft = 0x0001, ReturnDesignMetrics = 0x0002 }
This enum describes flags controlling conversion of characters to glyphs and their metrics.
Public Functions
virtual void addGlyphOutlinesToPath (uint *glyphs, int numGlyphs, FixedPoint *positions, QPainterPath *path)
Implemented in subclasses to add the outline of the glyphs specified by glyphs and numGlyphs at the specified positions to the painter path path.
virtual Capabilities capabilities () const =0
Implemented in subclasses to specify the font engine's capabilities.
virtual bool convertStringToGlyphIndices (const QChar *string, int length, uint *glyphs, int *numGlyphs, TextShapingFlags flags) const =0
Implemented in subclasses to convert the characters specified by string and length to glyph indicies, using flags.
virtual QVariant fontProperty (FontProperty property) const =0
Implemented in subclasses to return the value of the font attribute property.
virtual void getGlyphAdvances (const uint *glyphs, int numGlyphs, Fixed *advances, TextShapingFlags flags) const =0
Implemented in subclasses to retrieve the advances of the array specified by glyphs and numGlyphs, using flags.
virtual GlyphMetrics glyphMetrics (uint glyph) const =0
Implemented in subclass to return the metrics for glyph.
QAbstractFontEngine (QObject *parent=0)
Constructs a new QAbstractFontEngine with the given parent.
virtual bool renderGlyph (uint glyph, int depth, int bytesPerLine, int height, uchar *buffer)
Implemented in subclasses to render the specified glyph into a buffer with the given depth , bytesPerLine and height.
~QAbstractFontEngine ()
Destroys this QAbstractFontEngine object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAbstractFontEngine class is the base class for font engine plugins in Qt for Embedded Linux.
This function is under development and subject to change.
Since
4.3
QAbstractFontEngine is implemented by font engine plugins through QFontEnginePlugin.
See also
QFontEnginePlugin, QFontEngineInfo
Definition at line 127 of file qabstractfontengine_qws.h.
Typedefs
Fixed
QAbstractFontEngine::Fixed
This type is int, interpreted as a 26.
6 fixed point value.
Definition at line 142 of file qabstractfontengine_qws.h.
Enumerations
Capability
enum QAbstractFontEngine::Capability
This enum describes the capabilities of a font engine.
CanRenderGlyphs_Gray The font engine can render individual glyphs into 8 bpp images.
CanRenderGlyphs_Mono The font engine can render individual glyphs into 1 bpp images.
CanRenderGlyphs The font engine can render individual glyphs into images.
CanOutlineGlyphs The font engine can convert glyphs to painter paths.
Enumerator
CanOutlineGlyphs
CanRenderGlyphs_Mono
CanRenderGlyphs_Gray
CanRenderGlyphs
Definition at line 131 of file qabstractfontengine_qws.h.
                     {
         CanOutlineGlyphs = 1,
         CanRenderGlyphs_Mono = 2,
         CanRenderGlyphs_Gray = 4,
         CanRenderGlyphs = CanRenderGlyphs_Mono | CanRenderGlyphs_Gray
     };
FontProperty
enum QAbstractFontEngine::FontProperty
This enum describes the properties of a font provided by a font engine.
Ascent The ascent of the font, specified as a 26.6 fixed point value.
Descent The descent of the font, specified as a 26.6 fixed point value.
Leading The leading of the font, specified as a 26.6 fixed point value.
XHeight The 'x' height of the font, specified as a 26.6 fixed point value.
AverageCharWidth The average character width of the font, specified as a 26.6 fixed point value.
LineThickness The thickness of the underline and strikeout lines for the font, specified as a 26.6 fixed point value.
UnderlinePosition The distance from the base line to the underline position for the font, specified as a 26.6 fixed point value.
MaxCharWidth The width of the widest character in the font, specified as a 26.6 fixed point value.
MinLeftBearing The minimum left bearing of the font, specified as a 26.6 fixed point value.
MinRightBearing The maximum right bearing of the font, specified as a 26.6 fixed point value.
GlyphCount The number of glyphs in the font, specified as an integer value.
CacheGlyphsHint A boolean value specifying whether rendered glyphs should be cached by Qt.
OutlineGlyphsHint A boolean value specifying whether the font engine prefers outline drawing over image rendering for uncached glyphs.
Enumerator
Ascent
Descent
Leading
XHeight
AverageCharWidth
LineThickness
UnderlinePosition
MaxCharWidth
MinLeftBearing
MinRightBearing
GlyphCount
CacheGlyphsHint
OutlineGlyphsHint
Definition at line 162 of file qabstractfontengine_qws.h.
                       {
         Ascent,
         Descent,
         Leading,
         XHeight,
         AverageCharWidth,
         LineThickness,
         UnderlinePosition,
         MaxCharWidth,
         MinLeftBearing,
         MinRightBearing,
         GlyphCount,
         // hints
         CacheGlyphsHint,
         OutlineGlyphsHint
     };
TextShapingFlag
enum QAbstractFontEngine::TextShapingFlag
This enum describes flags controlling conversion of characters to glyphs and their metrics.
RightToLeft The text is used in a right-to-left context.
ReturnDesignMetrics Return font design metrics instead of pixel metrics.
Enumerator
RightToLeft
ReturnDesignMetrics
Definition at line 181 of file qabstractfontengine_qws.h.
{
         RightToLeft         = 0x0001,
         ReturnDesignMetrics = 0x0002
     };
Constructors and Destructors
QAbstractFontEngine()
QAbstractFontEngine::QAbstractFontEngine (QObject * parent = 0) explicit
Constructs a new QAbstractFontEngine with the given parent.
Definition at line 471 of file qabstractfontengine_qws.cpp.
     : QObject(*new QAbstractFontEnginePrivate, parent)
 {
 }
~QAbstractFontEngine()
QAbstractFontEngine::~QAbstractFontEngine ()
Destroys this QAbstractFontEngine object.
Definition at line 479 of file qabstractfontengine_qws.cpp.
 {
 }
Functions
addGlyphOutlinesToPath()
void QAbstractFontEngine::addGlyphOutlinesToPath (uint * glyphs, int numGlyphs, FixedPoint * positions, QPainterPath * path) virtual
Implemented in subclasses to add the outline of the glyphs specified by glyphs and numGlyphs at the specified positions to the painter path path.
Definition at line 555 of file qabstractfontengine_qws.cpp.
Referenced by QProxyFontEngine::addGlyphsToPath().
 {
     Q_UNUSED(glyphs)
     Q_UNUSED(numGlyphs)
     Q_UNUSED(positions)
     Q_UNUSED(path)
     qWarning("QAbstractFontEngine: addGlyphOutlinesToPath is not implemented in font plugin!");
 }
capabilities()
QAbstractFontEngine::Capabilities QAbstractFontEngine::capabilities () const pure virtual
Implemented in subclasses to specify the font engine's capabilities.
The return value may be cached by the caller and is expected not to change during the lifetime of the font engine.
Referenced by QProxyFontEngine::QProxyFontEngine().
convertStringToGlyphIndices()
bool QAbstractFontEngine::convertStringToGlyphIndices (const QChar * string, int length, uint * glyphs, int * numGlyphs, TextShapingFlags flags) const pure virtual
Implemented in subclasses to convert the characters specified by string and length to glyph indicies, using flags.
The glyph indicies should be returned in the glyphs array provided by the caller. The maximum size of glyphs is specified by the value pointed to by numGlyphs. If successful, the subclass implementation sets the value pointed to by numGlyphs to the actual number of glyph indices generated, and returns true. Otherwise, e.g. if there is not enough space in the provided glyphs array, it should set numGlyphs to the number of glyphs needed for the conversion and return false.
Referenced by QProxyFontEngine::canRender(), and QProxyFontEngine::stringToCMap().
fontProperty()
QVariant QAbstractFontEngine::fontProperty (FontProperty property) const pure virtual
Implemented in subclasses to return the value of the font attribute property.
The return value may be cached by the caller and is expected not to change during the lifetime of the font engine.
Referenced by QProxyFontEngine::ascent(), QProxyFontEngine::averageCharWidth(), QProxyFontEngine::descent(), QProxyFontEngine::drawAsOutline(), QProxyFontEngine::glyphCount(), QProxyFontEngine::leading(), QProxyFontEngine::lineThickness(), loadSingleEngine(), QProxyFontEngine::maxCharWidth(), QProxyFontEngine::minLeftBearing(), QProxyFontEngine::minRightBearing(), QProxyFontEngine::underlinePosition(), and QProxyFontEngine::xHeight().
getGlyphAdvances()
void QAbstractFontEngine::getGlyphAdvances (const uint * glyphs, int numGlyphs, Fixed * advances, TextShapingFlags flags) const pure virtual
Implemented in subclasses to retrieve the advances of the array specified by glyphs and numGlyphs, using flags.
The result is returned in advances, which is allocated by the caller and contains numGlyphs elements.
Referenced by QProxyFontEngine::recalcAdvances().
glyphMetrics()
QAbstractFontEngine::GlyphMetrics QAbstractFontEngine::glyphMetrics (uint glyph) const pure virtual
Implemented in subclass to return the metrics for glyph.
Referenced by QProxyFontEngine::alphaMapForGlyph(), QProxyFontEngine::boundingBox(), and QProxyFontEngine::canRender().
renderGlyph()
bool QAbstractFontEngine::renderGlyph (uint glyph, int depth, int bytesPerLine, int height, uchar * buffer) virtual
Implemented in subclasses to render the specified glyph into a buffer with the given depth , bytesPerLine and height.
Returns true if rendering succeeded, false otherwise.
Definition at line 540 of file qabstractfontengine_qws.cpp.
Referenced by QProxyFontEngine::alphaMapForGlyph().
 {
     Q_UNUSED(glyph)
     Q_UNUSED(depth)
     Q_UNUSED(bytesPerLine)
     Q_UNUSED(height)
     Q_UNUSED(buffer)
     qWarning("QAbstractFontEngine: renderGlyph is not implemented in font plugin!");
     return false;
 }
The documentation for this class was generated from the following files:
/src/gui/text/qabstractfontengine_qws.h
/src/gui/text/qabstractfontengine_qws.cpp