Qt 4.8: QGraphicsSceneWheelEvent Class Reference
QGraphicsSceneWheelEvent Class Reference
The QGraphicsSceneWheelEvent class provides wheel events in the graphics view framework.
#include <qgraphicssceneevent.h>
Public Functions
Qt::MouseButtons buttons () const
Returns the mouse buttons that were pressed when the wheel event occurred.
int delta () const
Returns the distance that the wheel is rotated, in eighths (1/8s) of a degree.
Qt::KeyboardModifiers modifiers () const
Returns the keyboard modifiers that were active when the wheel event occurred.
Qt::Orientation orientation () const
Returns the wheel orientation.
QPointF pos () const
Returns the position of the cursor in item coordinates when the wheel event occurred.
QGraphicsSceneWheelEvent (Type type=None)
Constructs a QGraphicsSceneWheelEvent of type type, which is always QEvent::GraphicsSceneWheel.
QPointF scenePos () const
Returns the position of the cursor in scene coordinates when the wheel event occurred.
QPoint screenPos () const
Returns the position of the cursor in screen coordinates when the wheel event occurred.
void setButtons (Qt::MouseButtons buttons)
void setDelta (int delta)
void setModifiers (Qt::KeyboardModifiers modifiers)
void setOrientation (Qt::Orientation orientation)
void setPos (const QPointF &pos)
void setScenePos (const QPointF &pos)
void setScreenPos (const QPoint &pos)
~QGraphicsSceneWheelEvent ()
Destroys the QGraphicsSceneWheelEvent.
Public Functions inherited from QGraphicsSceneEvent
QGraphicsSceneEvent (Type type)
Constructs a generic graphics scene event of the specified type.
void setWidget (QWidget *widget)
Sets the widget related to this event.
QWidget * widget () const
Returns the widget where the event originated, or 0 if the event originates from another application.
~QGraphicsSceneEvent ()
Destroys the event.
Public Functions inherited from QEvent
void accept ()
Sets the accept flag of the event object, the equivalent of calling setAccepted(true).
void ignore ()
Clears the accept flag parameter of the event object, the equivalent of calling setAccepted(false).
bool isAccepted () const
QEvent (Type type)
Contructs an event object of type type.
void setAccepted (bool accepted)
bool spontaneous () const
Returns true if the event originated outside the application (a system event); otherwise returns false.
Type type () const
Returns the event type.
virtual ~QEvent ()
Destroys the event.
Additional Inherited Members
Public Types inherited from QEvent
enum Type {
None = 0, Timer = 1, MouseButtonPress = 2, MouseButtonRelease = 3,
MouseButtonDblClick = 4, MouseMove = 5, KeyPress = 6, KeyRelease = 7,
FocusIn = 8, FocusOut = 9, Enter = 10, Leave = 11,
Paint = 12, Move = 13, Resize = 14, Create = 15,
Destroy = 16, Show = 17, Hide = 18, Close = 19,
Quit = 20, ParentChange = 21, ParentAboutToChange = 131, ThreadChange = 22,
WindowActivate = 24, WindowDeactivate = 25, ShowToParent = 26, HideToParent = 27,
Wheel = 31, WindowTitleChange = 33, WindowIconChange = 34, ApplicationWindowIconChange = 35,
ApplicationFontChange = 36, ApplicationLayoutDirectionChange = 37, ApplicationPaletteChange = 38, PaletteChange = 39,
Clipboard = 40, Speech = 42, MetaCall = 43, SockAct = 50,
WinEventAct = 132, DeferredDelete = 52, DragEnter = 60, DragMove = 61,
DragLeave = 62, Drop = 63, DragResponse = 64, ChildAdded = 68,
ChildPolished = 69, ChildRemoved = 71, ShowWindowRequest = 73, PolishRequest = 74,
Polish = 75, LayoutRequest = 76, UpdateRequest = 77, UpdateLater = 78,
EmbeddingControl = 79, ActivateControl = 80, DeactivateControl = 81, ContextMenu = 82,
InputMethod = 83, AccessibilityPrepare = 86, TabletMove = 87, LocaleChange = 88,
LanguageChange = 89, LayoutDirectionChange = 90, Style = 91, TabletPress = 92,
TabletRelease = 93, OkRequest = 94, HelpRequest = 95, IconDrag = 96,
FontChange = 97, EnabledChange = 98, ActivationChange = 99, StyleChange = 100,
IconTextChange = 101, ModifiedChange = 102, MouseTrackingChange = 109, WindowBlocked = 103,
WindowUnblocked = 104, WindowStateChange = 105, ToolTip = 110, WhatsThis = 111,
StatusTip = 112, ActionChanged = 113, ActionAdded = 114, ActionRemoved = 115,
FileOpen = 116, Shortcut = 117, ShortcutOverride = 51, WhatsThisClicked = 118,
ToolBarChange = 120, ApplicationActivate = 121, ApplicationActivated = ApplicationActivate, ApplicationDeactivate = 122,
ApplicationDeactivated = ApplicationDeactivate, QueryWhatsThis = 123, EnterWhatsThisMode = 124, LeaveWhatsThisMode = 125,
ZOrderChange = 126, HoverEnter = 127, HoverLeave = 128, HoverMove = 129,
AccessibilityHelp = 119, AccessibilityDescription = 130, AcceptDropsChange = 152, MenubarUpdated = 153,
ZeroTimerEvent = 154, GraphicsSceneMouseMove = 155, GraphicsSceneMousePress = 156, GraphicsSceneMouseRelease = 157,
GraphicsSceneMouseDoubleClick = 158, GraphicsSceneContextMenu = 159, GraphicsSceneHoverEnter = 160, GraphicsSceneHoverMove = 161,
GraphicsSceneHoverLeave = 162, GraphicsSceneHelp = 163, GraphicsSceneDragEnter = 164, GraphicsSceneDragMove = 165,
GraphicsSceneDragLeave = 166, GraphicsSceneDrop = 167, GraphicsSceneWheel = 168, KeyboardLayoutChange = 169,
DynamicPropertyChange = 170, TabletEnterProximity = 171, TabletLeaveProximity = 172, NonClientAreaMouseMove = 173,
NonClientAreaMouseButtonPress = 174, NonClientAreaMouseButtonRelease = 175, NonClientAreaMouseButtonDblClick = 176, MacSizeChange = 177,
ContentsRectChange = 178, MacGLWindowChange = 179, FutureCallOut = 180, GraphicsSceneResize = 181,
GraphicsSceneMove = 182, CursorChange = 183, ToolTipChange = 184, NetworkReplyUpdated = 185,
GrabMouse = 186, UngrabMouse = 187, GrabKeyboard = 188, UngrabKeyboard = 189,
MacGLClearDrawable = 191, StateMachineSignal = 192, StateMachineWrapped = 193, TouchBegin = 194,
TouchUpdate = 195, TouchEnd = 196, NativeGesture = 197, RequestSoftwareInputPanel = 199,
CloseSoftwareInputPanel = 200, UpdateSoftKeys = 201, WinIdChange = 203, Gesture = 198,
GestureOverride = 202, PlatformPanel = 212, User = 1000, MaxUser = 65535
}
This enum type defines the valid event types in Qt.
Static Public Functions inherited from QEvent
static int registerEventType (int hint=-1)
Registers and returns a custom event type.
Protected Functions inherited from QGraphicsSceneEvent
QGraphicsSceneEvent (QGraphicsSceneEventPrivate &dd, Type type=None)
Constructs a generic graphics scene event.
Protected Variables inherited from QGraphicsSceneEvent
QScopedPointer< QGraphicsSceneEventPrivate > d_ptr
Protected Variables inherited from QEvent
QEventPrivate * d
ushort t
Detailed Description
The QGraphicsSceneWheelEvent class provides wheel events in the graphics view framework.
Note
The QGraphicsSceneWheelEvent class provides wheel events in the graphics view framework.
Since
4.2
QWheelEvents received by a QGraphicsView are translated into QGraphicsSceneWheelEvents; it translates the QWheelEvent::globalPos() into item, scene, and screen coordinates (pos(), scenePos(), and screenPos()).
See also
QGraphicsSceneMouseEvent, QGraphicsSceneContextMenuEvent, QGraphicsSceneHoverEvent, QWheelEvent
Definition at line 133 of file qgraphicssceneevent.h.
Constructors and Destructors
QGraphicsSceneWheelEvent()
QGraphicsSceneWheelEvent::QGraphicsSceneWheelEvent (Type type = None)
Constructs a QGraphicsSceneWheelEvent of type type, which is always QEvent::GraphicsSceneWheel.
Warning
This function is not part of the public interface.
Definition at line 696 of file qgraphicssceneevent.cpp.
     : QGraphicsSceneEvent(*new QGraphicsSceneWheelEventPrivate, type)
 {
 }
~QGraphicsSceneWheelEvent()
QGraphicsSceneWheelEvent::~QGraphicsSceneWheelEvent ()
Destroys the QGraphicsSceneWheelEvent.
Definition at line 704 of file qgraphicssceneevent.cpp.
 {
 }
Functions
buttons()
Qt::MouseButtons QGraphicsSceneWheelEvent::buttons () const
Returns the mouse buttons that were pressed when the wheel event occurred.
See also
modifiers()
Definition at line 776 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and setButtons().
 {
     Q_D(const QGraphicsSceneWheelEvent);
     return d->buttons;
 }
delta()
int QGraphicsSceneWheelEvent::delta () const
Returns the distance that the wheel is rotated, in eighths (1/8s) of a degree.
A positive value indicates that the wheel was rotated forwards away from the user; a negative value indicates that the wheel was rotated backwards toward the user.
Most mouse types work in steps of 15 degrees, in which case the delta value is a multiple of 120 (== 15 * 8).
Definition at line 821 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), setDelta(), and QDeclarativeFlickable::wheelEvent().
 {
     Q_D(const QGraphicsSceneWheelEvent);
     return d->delta;
 }
modifiers()
Qt::KeyboardModifiers QGraphicsSceneWheelEvent::modifiers () const
Returns the keyboard modifiers that were active when the wheel event occurred.
See also
buttons()
Definition at line 797 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and setModifiers().
 {
     Q_D(const QGraphicsSceneWheelEvent);
     return d->modifiers;
 }
orientation()
Qt::Orientation QGraphicsSceneWheelEvent::orientation () const
Returns the wheel orientation.
Definition at line 839 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), setOrientation(), and QDeclarativeFlickable::wheelEvent().
 {
     Q_D(const QGraphicsSceneWheelEvent);
     return d->orientation;
 }
pos()
QPointF QGraphicsSceneWheelEvent::pos () const
Returns the position of the cursor in item coordinates when the wheel event occurred.
See also
scenePos(), screenPos()
Definition at line 714 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsItemPrivate::remapItemPos(), setPos(), setScenePos(), and setScreenPos().
 {
     Q_D(const QGraphicsSceneWheelEvent);
     return d->pos;
 }
scenePos()
QPointF QGraphicsSceneWheelEvent::scenePos () const
Returns the position of the cursor in scene coordinates when the wheel event occurred.
See also
pos(), screenPos()
Definition at line 735 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and QGraphicsScene::wheelEvent().
 {
     Q_D(const QGraphicsSceneWheelEvent);
     return d->scenePos;
 }
screenPos()
QPoint QGraphicsSceneWheelEvent::screenPos () const
Returns the position of the cursor in screen coordinates when the wheel event occurred.
See also
pos(), scenePos()
Definition at line 756 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and QGraphicsScene::wheelEvent().
 {
     Q_D(const QGraphicsSceneWheelEvent);
     return d->screenPos;
 }
setButtons()
void QGraphicsSceneWheelEvent::setButtons (Qt::MouseButtons buttons)
Warning
This function is not part of the public interface.
Definition at line 785 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and QGraphicsView::wheelEvent().
 {
     Q_D(QGraphicsSceneWheelEvent);
     d->buttons = buttons;
 }
setDelta()
void QGraphicsSceneWheelEvent::setDelta (int delta)
Warning
This function is not part of the public interface.
Definition at line 830 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and QGraphicsView::wheelEvent().
 {
     Q_D(QGraphicsSceneWheelEvent);
     d->delta = delta;
 }
setModifiers()
void QGraphicsSceneWheelEvent::setModifiers (Qt::KeyboardModifiers modifiers)
Warning
This function is not part of the public interface.
Definition at line 806 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and QGraphicsView::wheelEvent().
 {
     Q_D(QGraphicsSceneWheelEvent);
     d->modifiers = modifiers;
 }
setOrientation()
void QGraphicsSceneWheelEvent::setOrientation (Qt::Orientation orientation)
Warning
This function is not part of the public interface.
Definition at line 848 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and QGraphicsView::wheelEvent().
 {
     Q_D(QGraphicsSceneWheelEvent);
     d->orientation = orientation;
 }
setPos()
void QGraphicsSceneWheelEvent::setPos (const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 723 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsItemPrivate::remapItemPos(), and QGraphicsScene::wheelEvent().
 {
     Q_D(QGraphicsSceneWheelEvent);
     d->pos = pos;
 }
setScenePos()
void QGraphicsSceneWheelEvent::setScenePos (const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 744 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and QGraphicsView::wheelEvent().
 {
     Q_D(QGraphicsSceneWheelEvent);
     d->scenePos = pos;
 }
setScreenPos()
void QGraphicsSceneWheelEvent::setScreenPos (const QPoint & pos)
Warning
This function is not part of the public interface.
Definition at line 765 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and QGraphicsView::wheelEvent().
 {
     Q_D(QGraphicsSceneWheelEvent);
     d->screenPos = pos;
 }
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicssceneevent.h
/src/gui/graphicsview/qgraphicssceneevent.cpp