Qt 4.8: QDeclarativeCustomParserNode Class Reference
QDeclarativeCustomParserNode Class Reference
#include <qdeclarativecustomparser_p.h>
Public Functions
QDeclarativeParser::Location location () const
QByteArray name () const
QDeclarativeCustomParserNode & operator= (const QDeclarativeCustomParserNode &)
QList< QDeclarativeCustomParserProperty > properties () const
QDeclarativeCustomParserNode ()
QDeclarativeCustomParserNode (const QDeclarativeCustomParserNode &)
~QDeclarativeCustomParserNode ()
Properties
QDeclarativeCustomParserNodePrivate * d
Friends
class QDeclarativeCustomParserNodePrivate
Detailed Description
Definition at line 96 of file qdeclarativecustomparser_p.h.
Constructors and Destructors
QDeclarativeCustomParserNode() [1/2]
QDeclarativeCustomParserNode::QDeclarativeCustomParserNode ()
Definition at line 153 of file qdeclarativecustomparser.cpp.
 : d(new QDeclarativeCustomParserNodePrivate)
 {
 }
QDeclarativeCustomParserNode() [2/2]
QDeclarativeCustomParserNode::QDeclarativeCustomParserNode (const QDeclarativeCustomParserNode & other)
Definition at line 158 of file qdeclarativecustomparser.cpp.
 : d(new QDeclarativeCustomParserNodePrivate)
 {
     *this = other;
 }
~QDeclarativeCustomParserNode()
QDeclarativeCustomParserNode::~QDeclarativeCustomParserNode ()
Definition at line 172 of file qdeclarativecustomparser.cpp.
 {
     delete d; d = 0;
 }
Functions
location()
QDeclarativeParser::Location QDeclarativeCustomParserNode::location () const
Definition at line 187 of file qdeclarativecustomparser.cpp.
Referenced by QDeclarativeCustomParser::error().
 {
     return d->location;
 }
name()
QByteArray QDeclarativeCustomParserNode::name () const
Definition at line 177 of file qdeclarativecustomparser.cpp.
Referenced by QDeclarativeListModelParser::compileProperty().
 {
     return d->name;
 }
operator=()
QDeclarativeCustomParserNode & QDeclarativeCustomParserNode::operator= (const QDeclarativeCustomParserNode & other)
Definition at line 164 of file qdeclarativecustomparser.cpp.
 {
     d->name = other.d->name;
     d->properties = other.d->properties;
     d->location = other.d->location;
     return *this;
 }
properties()
QList< QDeclarativeCustomParserProperty > QDeclarativeCustomParserNode::properties () const
Definition at line 182 of file qdeclarativecustomparser.cpp.
Referenced by QDeclarativeListModelParser::compileProperty(), and QDeclarativeCustomParserNodePrivate::fromProperty().
 {
     return d->properties;
 }
Friends and Related Functions
QDeclarativeCustomParserNodePrivate
friend class QDeclarativeCustomParserNodePrivate friend
Definition at line 110 of file qdeclarativecustomparser_p.h.
Properties
d
QDeclarativeCustomParserNodePrivate* QDeclarativeCustomParserNode::d private
Definition at line 111 of file qdeclarativecustomparser_p.h.
Referenced by QDeclarativeCustomParserNodePrivate::fromObject(), location(), name(), operator=(), properties(), and ~QDeclarativeCustomParserNode().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativecustomparser_p.h
/src/declarative/qml/qdeclarativecustomparser.cpp