Qt 4.8: QWSClient Class Reference
QWSClient Class Reference
The QWSClient class encapsulates a client process in Qt for Embedded Linux.
#include <qwindowsystem_qws.h>
Signals
void connectionClosed ()
void readyRead ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int clientId () const
Returns an integer uniquely identfying this client.
QString identity () const
Returns the name of this client's running application.
QWSClient (QObject *parent, QWS_SOCK_BASE *, int id)
QWSCommand * readMoreCommand ()
void sendConnectedEvent (const char *display_spec)
void sendEmbedEvent (int winid, QWSEmbedEvent::Type type, const QRegion &region=QRegion())
void sendEvent (QWSEvent *event)
void sendMaxWindowRectEvent (const QRect &rect)
void sendPropertyNotifyEvent (int property, int state)
void sendPropertyReplyEvent (int property, int len, const char *data)
void sendRegionEvent (int winid, QRegion rgn, int type)
void sendSelectionClearEvent (int windowid)
void sendSelectionRequestEvent (QWSConvertSelectionCommand *cmd, int windowid)
void setIdentity (const QString &)
int socket () const
~QWSClient ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
QWSCursorMap cursors
Private Slots
void closeHandler ()
void errorHandler ()
Private Functions
void addUnbufferedSurface ()
void removeUnbufferedSurface ()
Properties
int cid
QWSCommand * command
QWSSocket * csocket
QString id
uint isClosed: 1
int socketDescriptor
Friends
class QWSServerPrivate
class QWSWindow
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QWSClient class encapsulates a client process in Qt for Embedded Linux.
When you run a Qt for Embedded Linux application, it either runs as a server or connects to an existing server. The server and client processes have different responsibilities: The client process performs all application specific operations. The server process is responsible for managing the clients as well as taking care of the pointer handling, character input, and screen output. In addition, the server provides functionality to handle input methods.
As applications add and remove windows, the server process maintains information about each window. In Qt for Embedded Linux, top-level windows are encapsulated as QWSWindow objects. A list of the current windows can be retrieved using the QWSServer::clientWindows() function, and each window can tell which client that owns it through its QWSWindow::client() function.
A QWSClient object has an unique ID that can be retrieved using its clientId() function. QWSClient also provides the identity() function which typically returns the name of this client's running application.
See also
QWSServer, QWSWindow, {Qt for Embedded Linux Architecture}
Definition at line 443 of file qwindowsystem_qws.h.
Constructors and Destructors
QWSClient()
QWSClient::QWSClient (QObject * parent, QWS_SOCK_BASE * sock, int id)
Warning
This function is not part of the public interface.
Definition at line 814 of file qwindowsystem_qws.cpp.
     : QObject(*new QWSClientPrivate, parent), command(0), cid(id)
 {
 #ifdef QT_NO_QWS_MULTIPROCESS
     Q_UNUSED(sock);
     isClosed = false;
 #else
     csocket = 0;
     if (!sock) {
         socketDescriptor = -1;
         isClosed = false;
     } else {
         csocket = static_cast<QWSSocket*>(sock); //###
         isClosed = false;
         csocket->flush();
         socketDescriptor = csocket->socketDescriptor();
         connect(csocket, SIGNAL(readyRead()), this, SIGNAL(readyRead()));
         connect(csocket, SIGNAL(disconnected()), this, SLOT(closeHandler()));
         connect(csocket, SIGNAL(error(QAbstractSocket::SocketError)), this, SLOT(errorHandler()));
     }
 #endif //QT_NO_QWS_MULTIPROCESS
 }
~QWSClient()
QWSClient::~QWSClient ()
Warning
This function is not part of the public interface.
Definition at line 841 of file qwindowsystem_qws.cpp.
 {
     qDeleteAll(cursors);
     delete command;
 #ifndef QT_NO_QWS_MULTIPROCESS
     delete csocket;
 #endif
 }
Functions
addUnbufferedSurface()
void QWSClient::addUnbufferedSurface () private
Definition at line 857 of file qwindowsystem_qws.cpp.
Referenced by QWSWindow::createSurface().
 {
     Q_D(QWSClient);
     ++d->numUnbufferedSurfaces;
 }
clientId()
int QWSClient::clientId () const inline
Returns an integer uniquely identfying this client.
Definition at line 474 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::_q_clientClosed(), QWSServerPrivate::invokeIdentify(), and QWSServer::windowList().
 { return cid; }
closeHandler
void QWSClient::closeHandler () private slot
Definition at line 872 of file qwindowsystem_qws.cpp.
Referenced by QWSClient().
 {
     isClosed = true;
     emit connectionClosed();
 }
connectionClosed
void QWSClient::connectionClosed () signal
Warning
This function is not part of the public interface.
Referenced by closeHandler(), and errorHandler().
errorHandler
void QWSClient::errorHandler () private slot
Definition at line 878 of file qwindowsystem_qws.cpp.
Referenced by QWSClient().
 {
 #if defined(QWS_SOCKET_DEBUG)
     qDebug("Client %p error %s", this, csocket ? csocket->errorString().toLatin1().constData() : "(no socket)");
 #endif
     isClosed = true;
 //####Do we need to clean out the pipes?
     emit connectionClosed();
 }
identity()
QString QWSClient::identity () const inline
Returns the name of this client's running application.
Definition at line 454 of file qwindowsystem_qws.h.
Referenced by QScreen::exposeRegion().
 { return id; }
readMoreCommand()
QWSCommand * QWSClient::readMoreCommand ()
Warning
This function is not part of the public interface.
Definition at line 1910 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::doClient().
 {
 #ifndef QT_NO_QWS_MULTIPROCESS
     QIODevice *socket = 0;
 #endif
 #ifndef QT_NO_SXE
     if (socketDescriptor != -1)  // not server socket
         socket = QTransportAuth::getInstance()->passThroughByClient( this );
 #if QTRANSPORTAUTH_DEBUG
     if (socket) {
         char displaybuf[1024];
         qint64 bytes = socket->bytesAvailable();
         if ( bytes > 511 ) bytes = 511;
         hexstring( displaybuf, ((unsigned char *)(reinterpret_cast<QAuthDevice*>(socket)->buffer().constData())), bytes );
         qDebug( "readMoreCommand: %lli bytes - %s", socket->bytesAvailable(), displaybuf );
     }
 #endif
 #endif // QT_NO_SXE
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (!socket)
         socket = csocket;   // server socket
     if (socket) {
         // read next command
         if (!command) {
             int command_type = qws_read_uint(socket);
             if (command_type >= 0)
                 command = QWSCommand::factory(command_type);
         }
         if (command) {
             if (command->read(socket)) {
                 // Finished reading a whole command.
                 QWSCommand* result = command;
                 command = 0;
                 return result;
             }
         }
         // Not finished reading a whole command.
         return 0;
     } else
 #endif // QT_NO_QWS_MULTIPROCESS
     {
         QList<QWSCommand*> *serverQueue = qt_get_server_queue();
         return serverQueue->isEmpty() ? 0 : serverQueue->takeFirst();
     }
 }
readyRead
void QWSClient::readyRead () signal
Warning
This function is not part of the public interface.
Referenced by QWSClient().
removeUnbufferedSurface()
void QWSClient::removeUnbufferedSurface () private
Definition at line 851 of file qwindowsystem_qws.cpp.
Referenced by QWSWindow::createSurface(), and QWSWindow::~QWSWindow().
 {
     Q_D(QWSClient);
     --d->numUnbufferedSurfaces;
 }
sendConnectedEvent()
void QWSClient::sendConnectedEvent (const char * display_spec)
Warning
This function is not part of the public interface.
Definition at line 947 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::_q_newConnection().
 {
     QWSConnectedEvent event;
     event.simpleData.window = 0;
     event.simpleData.len = strlen(display_spec) + 1;
     event.simpleData.clientId = cid;
     event.simpleData.servershmid = qt_servershmid;
     char * tmp=(char *)display_spec;
     event.setData(tmp, event.simpleData.len);
     sendEvent(&event);
 }
sendEmbedEvent()
void QWSClient::sendEmbedEvent (int windowid, QWSEmbedEvent::Type type, const QRegion & region = QRegion())
Warning
This function is not part of the public interface.
Definition at line 1024 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeEmbed(), and QWSWindow::stopEmbed().
 {
     QWSEmbedEvent event;
     event.setData(windowid, type, region);
     sendEvent(&event);
 }
sendEvent()
void QWSClient::sendEvent (QWSEvent * event)
Warning
This function is not part of the public interface.
Definition at line 900 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::_q_newConnection(), QWSWindow::focus(), QWSServerPrivate::invokeCreate(), QWSWindow::operation(), sendConnectedEvent(), sendEmbedEvent(), QWSServer::sendIMEvent(), QWSServer::sendIMQuery(), QWSServerPrivate::sendKeyEventUnfiltered(), sendMaxWindowRectEvent(), QWSServerPrivate::sendMouseEventUnfiltered(), sendPropertyNotifyEvent(), sendPropertyReplyEvent(), QWSServerPrivate::sendQCopEvent(), sendRegionEvent(), sendSelectionClearEvent(), and sendSelectionRequestEvent().
 {
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (csocket) {
         // qDebug() << "QWSClient::sendEvent type " << event->type << " socket state " << csocket->state();
         if ((QAbstractSocket::SocketState)(csocket->state()) == QAbstractSocket::ConnectedState) {
             event->write(csocket);
         }
     }
     else
 #endif
     {
         qt_client_enqueue(event);
     }
 }
sendMaxWindowRectEvent()
void QWSClient::sendMaxWindowRectEvent (const QRect & rect)
Warning
This function is not part of the public interface.
Definition at line 962 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::_q_newConnection().
 {
     QWSMaxWindowRectEvent event;
     event.simpleData.window = 0;
     event.simpleData.rect = rect;
     sendEvent(&event);
 }
sendPropertyNotifyEvent()
void QWSClient::sendPropertyNotifyEvent (int property, int state)
Warning
This function is not part of the public interface.
Definition at line 974 of file qwindowsystem_qws.cpp.
Referenced by QWSServer::sendPropertyNotifyEvent().
 {
     QWSPropertyNotifyEvent event;
     event.simpleData.window = 0; // not used yet
     event.simpleData.property = property;
     event.simpleData.state = state;
     sendEvent(&event);
 }
sendPropertyReplyEvent()
void QWSClient::sendPropertyReplyEvent (int property, int len, const char * data)
Warning
This function is not part of the public interface.
Definition at line 986 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeGetProperty().
 {
     QWSPropertyReplyEvent event;
     event.simpleData.window = 0; // not used yet
     event.simpleData.property = property;
     event.simpleData.len = len;
     event.setData(data, len);
     sendEvent(&event);
 }
sendRegionEvent()
void QWSClient::sendRegionEvent (int winid, QRegion rgn, int type)
Warning
This function is not part of the public interface.
Definition at line 919 of file qwindowsystem_qws.cpp.
Referenced by QWSServer::enablePainting(), QWSServerPrivate::request_region(), and QWSServerPrivate::update_regions().
 {
 #ifndef QT_NO_QWS_MULTIPROCESS
     Q_D(QWSClient);
     if (d->clientLock)
         d->clientLock->lock(QWSLock::RegionEvent);
 #endif
     QWSRegionEvent event;
     event.setData(winid, rgn, type);
 #ifdef QT_QWS_CLIENTBLIT
     event.simpleData.id = id;
 #endif
 //    qDebug() << "Sending Region event to" << winid << "rgn" << rgn << "type" << type;
     sendEvent(&event);
 }
sendSelectionClearEvent()
void QWSClient::sendSelectionClearEvent (int windowid)
Warning
This function is not part of the public interface.
Definition at line 1000 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeSetSelectionOwner().
 {
     QWSSelectionClearEvent event;
     event.simpleData.window = windowid;
     sendEvent(&event);
 }
sendSelectionRequestEvent()
void QWSClient::sendSelectionRequestEvent (QWSConvertSelectionCommand * cmd, int windowid)
Warning
This function is not part of the public interface.
Definition at line 1010 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeConvertSelection().
 {
     QWSSelectionRequestEvent event;
     event.simpleData.window = windowid;
     event.simpleData.requestor = cmd->simpleData.requestor;
     event.simpleData.property = cmd->simpleData.selection;
     event.simpleData.mimeTypes = cmd->simpleData.mimeTypes;
     sendEvent(&event);
 }
setIdentity()
void QWSClient::setIdentity (const QString & i)
Warning
This function is not part of the public interface.
Definition at line 867 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeIdentify().
 {
     id = i;
 }
socket()
int QWSClient::socket () const
Warning
This function is not part of the public interface.
Definition at line 892 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::_q_clientClosed().
 {
     return socketDescriptor;
 }
Friends and Related Functions
QWSServerPrivate
friend class QWSServerPrivate friend
Definition at line 501 of file qwindowsystem_qws.h.
QWSWindow
friend class QWSWindow friend
Definition at line 486 of file qwindowsystem_qws.h.
Properties
cid
int QWSClient::cid private
Definition at line 499 of file qwindowsystem_qws.h.
Referenced by sendConnectedEvent().
command
QWSCommand* QWSClient::command private
Definition at line 496 of file qwindowsystem_qws.h.
Referenced by ~QWSClient(), and QWSCommandStruct::~QWSCommandStruct().
csocket
QWSSocket* QWSClient::csocket private
Definition at line 494 of file qwindowsystem_qws.h.
Referenced by errorHandler(), QWSClient(), sendEvent(), and ~QWSClient().
cursors
QWSCursorMap QWSClient::cursors
Definition at line 476 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::invokeDefineCursor(), QWSServerPrivate::invokeSelectCursor(), and ~QWSClient().
id
QString QWSClient::id private
Definition at line 498 of file qwindowsystem_qws.h.
Referenced by sendRegionEvent().
isClosed
uint QWSClient::isClosed private
Definition at line 497 of file qwindowsystem_qws.h.
Referenced by closeHandler(), errorHandler(), and QWSClient().
socketDescriptor
int QWSClient::socketDescriptor private
Definition at line 492 of file qwindowsystem_qws.h.
Referenced by QWSClient(), and socket().
The documentation for this class was generated from the following files:
/src/gui/embedded/qwindowsystem_qws.h
/src/gui/embedded/qwindowsystem_qws.cpp