Qt 4.8: QDeclarativeKeyNavigationAttached Class Reference
QDeclarativeKeyNavigationAttached Class Reference
#include <qdeclarativeitem_p.h>
Public Types
enum Priority { BeforeItem, AfterItem }
Signals
void backtabChanged ()
void downChanged ()
void leftChanged ()
void priorityChanged ()
void rightChanged ()
void tabChanged ()
void upChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDeclarativeItem * backtab () const
QDeclarativeItem * down () const
QDeclarativeItem * left () const
Priority priority () const
QDeclarativeKeyNavigationAttached (QObject *=0)
QDeclarativeItem * right () const
void setBacktab (QDeclarativeItem *)
void setDown (QDeclarativeItem *)
void setLeft (QDeclarativeItem *)
void setPriority (Priority)
void setRight (QDeclarativeItem *)
void setTab (QDeclarativeItem *)
void setUp (QDeclarativeItem *)
QDeclarativeItem * tab () const
QDeclarativeItem * up () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeItemKeyFilter
virtual void componentComplete ()
virtual void inputMethodEvent (QInputMethodEvent *event, bool post)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
QDeclarativeItemKeyFilter (QDeclarativeItem *=0)
virtual ~QDeclarativeItemKeyFilter ()
Static Public Functions
static QDeclarativeKeyNavigationAttached * qmlAttachedProperties (QObject *)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Private Functions
virtual void keyPressed (QKeyEvent *event, bool post)
virtual void keyReleased (QKeyEvent *event, bool post)
void setFocusNavigation (QDeclarativeItem *currentItem, const char *dir)
Properties
QDeclarativeItem * backtab
QDeclarativeItem * down
QDeclarativeItem * left
Priority priority
QDeclarativeItem * right
QDeclarativeItem * tab
QDeclarativeItem * up
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Variables inherited from QDeclarativeItemKeyFilter
bool m_processPost
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 388 of file qdeclarativeitem_p.h.
Enumerations
Priority
enum QDeclarativeKeyNavigationAttached::Priority
Enumerator
BeforeItem
AfterItem
Definition at line 419 of file qdeclarativeitem_p.h.
 { BeforeItem, AfterItem };
Constructors and Destructors
QDeclarativeKeyNavigationAttached()
QDeclarativeKeyNavigationAttached::QDeclarativeKeyNavigationAttached (QObject * parent = 0)
Definition at line 521 of file qdeclarativeitem.cpp.
Referenced by qmlAttachedProperties().
 : QObject(*(new QDeclarativeKeyNavigationAttachedPrivate), parent),
   QDeclarativeItemKeyFilter(qobject_cast<QDeclarativeItem*>(parent))
 {
     m_processPost = true;
 }
Functions
backtab()
QDeclarativeItem* QDeclarativeKeyNavigationAttached::backtab () const
Referenced by setTab().
backtabChanged
void QDeclarativeKeyNavigationAttached::backtabChanged () signal
Referenced by setBacktab().
down()
QDeclarativeItem* QDeclarativeKeyNavigationAttached::down () const
Referenced by setUp().
downChanged
void QDeclarativeKeyNavigationAttached::downChanged () signal
Referenced by setDown().
keyPressed()
void QDeclarativeKeyNavigationAttached::keyPressed (QKeyEvent * event, bool post) private virtual
Reimplemented from QDeclarativeItemKeyFilter.
Definition at line 656 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeyNavigationAttached);
     event->ignore();
     if (post != m_processPost) {
         QDeclarativeItemKeyFilter::keyPressed(event, post);
         return;
     }
     bool mirror = false;
     switch(event->key()) {
     case Qt::Key_Left: {
         if (QDeclarativeItem *parentItem = qobject_cast<QDeclarativeItem*>(parent()))
             mirror = QDeclarativeItemPrivate::get(parentItem)->effectiveLayoutMirror;
         QDeclarativeItem* leftItem = mirror ? d->right : d->left;
         if (leftItem) {
             setFocusNavigation(leftItem, mirror ? "right" : "left");
             event->accept();
         }
         break;
     }
     case Qt::Key_Right: {
         if (QDeclarativeItem *parentItem = qobject_cast<QDeclarativeItem*>(parent()))
             mirror = QDeclarativeItemPrivate::get(parentItem)->effectiveLayoutMirror;
         QDeclarativeItem* rightItem = mirror ? d->left : d->right;
         if (rightItem) {
             setFocusNavigation(rightItem, mirror ? "left" : "right");
             event->accept();
         }
         break;
     }
     case Qt::Key_Up:
         if (d->up) {
             setFocusNavigation(d->up, "up");
             event->accept();
         }
         break;
     case Qt::Key_Down:
         if (d->down) {
             setFocusNavigation(d->down, "down");
             event->accept();
         }
         break;
     case Qt::Key_Tab:
         if (d->tab) {
             setFocusNavigation(d->tab, "tab");
             event->accept();
         }
         break;
     case Qt::Key_Backtab:
         if (d->backtab) {
             setFocusNavigation(d->backtab, "backtab");
             event->accept();
         }
         break;
     default:
         break;
     }
     if (!event->isAccepted()) QDeclarativeItemKeyFilter::keyPressed(event, post);
 }
keyReleased()
void QDeclarativeKeyNavigationAttached::keyReleased (QKeyEvent * event, bool post) private virtual
Reimplemented from QDeclarativeItemKeyFilter.
Definition at line 719 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeyNavigationAttached);
     event->ignore();
     if (post != m_processPost) {
         QDeclarativeItemKeyFilter::keyReleased(event, post);
         return;
     }
     bool mirror = false;
     switch(event->key()) {
     case Qt::Key_Left:
         if (QDeclarativeItem *parentItem = qobject_cast<QDeclarativeItem*>(parent()))
             mirror = QDeclarativeItemPrivate::get(parentItem)->effectiveLayoutMirror;
         if (mirror ? d->right : d->left)
             event->accept();
         break;
     case Qt::Key_Right:
         if (QDeclarativeItem *parentItem = qobject_cast<QDeclarativeItem*>(parent()))
             mirror = QDeclarativeItemPrivate::get(parentItem)->effectiveLayoutMirror;
         if (mirror ? d->left : d->right)
             event->accept();
         break;
     case Qt::Key_Up:
         if (d->up) {
             event->accept();
         }
         break;
     case Qt::Key_Down:
         if (d->down) {
             event->accept();
         }
         break;
     case Qt::Key_Tab:
         if (d->tab) {
             event->accept();
         }
         break;
     case Qt::Key_Backtab:
         if (d->backtab) {
             event->accept();
         }
         break;
     default:
         break;
     }
     if (!event->isAccepted()) QDeclarativeItemKeyFilter::keyReleased(event, post);
 }
left()
QDeclarativeItem* QDeclarativeKeyNavigationAttached::left () const
Referenced by qmlAttachedProperties().
leftChanged
void QDeclarativeKeyNavigationAttached::leftChanged () signal
Referenced by setLeft().
priority()
Priority QDeclarativeKeyNavigationAttached::priority () const
Referenced by setBacktab().
priorityChanged
void QDeclarativeKeyNavigationAttached::priorityChanged () signal
Referenced by setPriority().
qmlAttachedProperties()
QDeclarativeKeyNavigationAttached * QDeclarativeKeyNavigationAttached::qmlAttachedProperties (QObject * obj) static
Definition at line 529 of file qdeclarativeitem.cpp.
 {
     return new QDeclarativeKeyNavigationAttached(obj);
 }
right()
QDeclarativeItem* QDeclarativeKeyNavigationAttached::right () const
Referenced by setLeft().
rightChanged
void QDeclarativeKeyNavigationAttached::rightChanged () signal
Referenced by setRight().
setBacktab()
void QDeclarativeKeyNavigationAttached::setBacktab (QDeclarativeItem * i)
Definition at line 615 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeyNavigationAttached);
     if (d->backtab == i)
         return;
     d->backtab = i;
     emit backtabChanged();
 }
setDown()
void QDeclarativeKeyNavigationAttached::setDown (QDeclarativeItem * i)
Definition at line 585 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeyNavigationAttached);
     if (d->down == i)
         return;
     d->down = i;
     emit downChanged();
 }
setFocusNavigation()
void QDeclarativeKeyNavigationAttached::setFocusNavigation (QDeclarativeItem * currentItem, const char * dir) private
Definition at line 770 of file qdeclarativeitem.cpp.
Referenced by keyPressed().
 {
     QDeclarativeItem *initialItem = currentItem;
     bool isNextItem = false;
     do {
         isNextItem = false;
         if (currentItem->isVisible() && currentItem->isEnabled()) {
             currentItem->setFocus(true);
         } else {
             QObject *attached =
                 qmlAttachedPropertiesObject<QDeclarativeKeyNavigationAttached>(currentItem, false);
             if (attached) {
                 QDeclarativeItem *tempItem = qvariant_cast<QDeclarativeItem*>(attached->property(dir));
                 if (tempItem) {
                     currentItem = tempItem;
                     isNextItem = true;
                 }
             }
         }
     }
     while (currentItem != initialItem && isNextItem);
 }
setLeft()
void QDeclarativeKeyNavigationAttached::setLeft (QDeclarativeItem * i)
Definition at line 540 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeyNavigationAttached);
     if (d->left == i)
         return;
     d->left = i;
     emit leftChanged();
 }
setPriority()
void QDeclarativeKeyNavigationAttached::setPriority (Priority order)
Definition at line 647 of file qdeclarativeitem.cpp.
 {
     bool processPost = order == AfterItem;
     if (processPost != m_processPost) {
         m_processPost = processPost;
         emit priorityChanged();
     }
 }
setRight()
void QDeclarativeKeyNavigationAttached::setRight (QDeclarativeItem * i)
Definition at line 555 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeyNavigationAttached);
     if (d->right == i)
         return;
     d->right = i;
     emit rightChanged();
 }
setTab()
void QDeclarativeKeyNavigationAttached::setTab (QDeclarativeItem * i)
Definition at line 600 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeyNavigationAttached);
     if (d->tab == i)
         return;
     d->tab = i;
     emit tabChanged();
 }
setUp()
void QDeclarativeKeyNavigationAttached::setUp (QDeclarativeItem * i)
Definition at line 570 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeyNavigationAttached);
     if (d->up == i)
         return;
     d->up = i;
     emit upChanged();
 }
tab()
QDeclarativeItem* QDeclarativeKeyNavigationAttached::tab () const
Referenced by setDown().
tabChanged
void QDeclarativeKeyNavigationAttached::tabChanged () signal
Referenced by setTab().
up()
QDeclarativeItem* QDeclarativeKeyNavigationAttached::up () const
Referenced by setRight().
upChanged
void QDeclarativeKeyNavigationAttached::upChanged () signal
Referenced by setUp().
Properties
backtab
QDeclarativeItem * QDeclarativeKeyNavigationAttached::backtab private
Definition at line 398 of file qdeclarativeitem_p.h.
down
QDeclarativeItem * QDeclarativeKeyNavigationAttached::down private
Definition at line 396 of file qdeclarativeitem_p.h.
left
QDeclarativeItem * QDeclarativeKeyNavigationAttached::left private
Definition at line 393 of file qdeclarativeitem_p.h.
priority
QDeclarativeKeyNavigationAttached::Priority QDeclarativeKeyNavigationAttached::priority private
Definition at line 399 of file qdeclarativeitem_p.h.
right
QDeclarativeItem * QDeclarativeKeyNavigationAttached::right private
Definition at line 394 of file qdeclarativeitem_p.h.
tab
QDeclarativeItem * QDeclarativeKeyNavigationAttached::tab private
Definition at line 397 of file qdeclarativeitem_p.h.
up
QDeclarativeItem * QDeclarativeKeyNavigationAttached::up private
Definition at line 395 of file qdeclarativeitem_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativeitem_p.h
/src/declarative/graphicsitems/qdeclarativeitem.cpp