Qt 4.8: QWindowsMimeList Class Reference
QWindowsMimeList Class Reference
Public Functions
void addWindowsMime (QWindowsMime *mime)
QWindowsMimeList ()
void removeWindowsMime (QWindowsMime *mime)
QList< QWindowsMime * > windowsMimes ()
~QWindowsMimeList ()
Private Functions
void init ()
Properties
bool initialized
QList< QWindowsMime * > mimes
Detailed Description
Definition at line 201 of file qmime_win.cpp.
Constructors and Destructors
QWindowsMimeList()
QWindowsMimeList::QWindowsMimeList ()
Definition at line 1339 of file qmime_win.cpp.
     : initialized(false)
 {
 }
~QWindowsMimeList()
QWindowsMimeList::~QWindowsMimeList ()
Definition at line 1344 of file qmime_win.cpp.
 {
     while (mimes.size())
         delete mimes.first();
 }
Functions
addWindowsMime()
void QWindowsMimeList::addWindowsMime (QWindowsMime * mime)
Definition at line 1367 of file qmime_win.cpp.
 {
     init();
     mimes.append(mime);
 }
init()
void QWindowsMimeList::init () private
Definition at line 1351 of file qmime_win.cpp.
Referenced by addWindowsMime(), removeWindowsMime(), and windowsMimes().
 {
     if (!initialized) {
         initialized = true;
 #ifndef QT_NO_IMAGEFORMAT_BMP
         new QWindowsMimeImage;
 #endif
         new QLastResortMimes;
         new QWindowsMimeText;
         new QWindowsMimeURI;
         new QWindowsMimeHtml;
         new QBuiltInMimes;
     }
 }
removeWindowsMime()
void QWindowsMimeList::removeWindowsMime (QWindowsMime * mime)
Definition at line 1373 of file qmime_win.cpp.
 {
     init();
     mimes.removeAll(mime);
 }
windowsMimes()
QList< QWindowsMime * > QWindowsMimeList::windowsMimes ()
Definition at line 1379 of file qmime_win.cpp.
 {
     init();
     return mimes;
 }
Properties
initialized
bool QWindowsMimeList::initialized private
Definition at line 212 of file qmime_win.cpp.
Referenced by init().
mimes
QList<QWindowsMime*> QWindowsMimeList::mimes private
Definition at line 213 of file qmime_win.cpp.
Referenced by addWindowsMime(), removeWindowsMime(), windowsMimes(), and ~QWindowsMimeList().
The documentation for this class was generated from the following file:
/src/gui/kernel/qmime_win.cpp