Qt 4.8: QSqlQueryModel Class Reference
QSqlQueryModel Class Reference
The QSqlQueryModel class provides a read-only data model for SQL result sets.
#include <qsqlquerymodel.h>
Public Functions
bool canFetchMore (const QModelIndex &parent=QModelIndex()) const
Returns true if it is possible to read more rows from the database.
virtual void clear ()
Clears the model and releases any acquired resource.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant data (const QModelIndex &item, int role=Qt::DisplayRole) const
Returns the value for the specified item and role.
void fetchMore (const QModelIndex &parent=QModelIndex())
Fetches more rows from a database.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Returns the header data for the given role in the section of the header with the specified orientation.
bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Inserts count columns into the model at position column.
QSqlError lastError () const
Returns information about the last error that occurred on the database.
QSqlQueryModel (QObject *parent=0)
Creates an empty QSqlQueryModel with the given parent.
QSqlQuery query () const
Returns the QSqlQuery associated with this model.
QSqlRecord record (int row) const
Returns the record containing information about the fields of the current query.
QSqlRecord record () const
Returns an empty record containing information about the fields of the current query.
bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Removes count columns from the model starting from position column.
int rowCount (const QModelIndex &parent=QModelIndex()) const
If the database supports returning the size of a query (see QSqlDriver::hasFeature()), the number of rows of the current query is returned.
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the caption for a horizontal header for the specified role to value.
void setQuery (const QSqlQuery &query)
Resets the model and sets the data provider to be the given query.
void setQuery (const QString &query, const QSqlDatabase &db=QSqlDatabase())
Executes the query query for the given database connection db.
virtual ~QSqlQueryModel ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QAbstractTableModel
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns the index of the data in row and column with parent.
QAbstractTableModel (QObject *parent=0)
Constructs an abstract table model for the given parent.
~QAbstractTableModel ()
Destroys the abstract table model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Returns the item flags for the given index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count rows into the model before the given row.
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
virtual QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
virtual QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of model indexes.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
virtual bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Sets the role data for the item at index to value.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Sorts the model by column in the given order.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QModelIndex indexInQuery (const QModelIndex &item) const
Returns the index of the value in the database result set for the given item in the model.
QSqlQueryModel (QSqlQueryModelPrivate &dd, QObject *parent=0)
virtual void queryChange ()
This virtual function is called whenever the query changes.
void setLastError (const QSqlError &error)
Protected function which allows derived classes to set the value of the last error that occurred on the database to error.
Protected Functions inherited from QAbstractTableModel
QAbstractTableModel (QAbstractItemModelPrivate &dd, QObject *parent)
Constructs an abstract table model with dd and the given parent.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSqlQueryModel class provides a read-only data model for SQL result sets.
Attention
Module: QtSql
QSqlQueryModel is a high-level interface for executing SQL statements and traversing the result set. It is built on top of the lower-level QSqlQuery and can be used to provide data to view classes such as QTableView. For example:
    QSqlQueryModel *model = new QSqlQueryModel;
    model->setQuery("SELECT name, salary FROM employee");
    model->setHeaderData(0, Qt::Horizontal, tr("Name"));
    model->setHeaderData(1, Qt::Horizontal, tr("Salary"));
    QTableView *view = new QTableView;
    view->setModel(model);
    view->show();
We set the model's query, then we set up the labels displayed in the view header.
QSqlQueryModel can also be used to access a database programmatically, without binding it to a view:
    QSqlQueryModel model;
    model.setQuery("SELECT * FROM employee");
    int salary = model.record(4).value("salary").toInt();
The code snippet above extracts the salary field from record 4 in the result set of the query SELECT * from employee. Assuming that salary is column 2, we can rewrite the last line as follows:
    int salary = model.data(model.index(4, 2)).toInt();
The model is read-only by default. To make it read-write, you must subclass it and reimplement setData() and flags(). Another option is to use QSqlTableModel, which provides a read-write model based on a single database table.
The sql/querymodel example illustrates how to use QSqlQueryModel to display the result of a query. It also shows how to subclass QSqlQueryModel to customize the contents of the data before showing it to the user, and how to create a read-write model based on QSqlQueryModel.
If the database doesn't return the number of selected rows in a query, the model will fetch rows incrementally. See fetchMore() for more information.
See also
QSqlTableModel, QSqlRelationalTableModel, QSqlQuery, {Model/View Programming}, {Query Model Example}
Definition at line 59 of file qsqlquerymodel.h.
Constructors and Destructors
QSqlQueryModel() [1/2]
QSqlQueryModel::QSqlQueryModel (QObject * parent = 0) explicit
Creates an empty QSqlQueryModel with the given parent.
Definition at line 153 of file qsqlquerymodel.cpp.
     : QAbstractTableModel(*new QSqlQueryModelPrivate, parent)
 {
 }
~QSqlQueryModel()
QSqlQueryModel::~QSqlQueryModel () virtual
Destroys the object and frees any allocated resources.
See also
clear()
Definition at line 170 of file qsqlquerymodel.cpp.
 {
 }
QSqlQueryModel() [2/2]
QSqlQueryModel::QSqlQueryModel (QSqlQueryModelPrivate & dd, QObject * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 160 of file qsqlquerymodel.cpp.
     : QAbstractTableModel(dd, parent)
 {
 }
Functions
canFetchMore()
bool QSqlQueryModel::canFetchMore (const QModelIndex & parent = QModelIndex()) const virtual
Returns true if it is possible to read more rows from the database.
Since
4.1
This only affects databases that don't report back the size of a query (see QSqlDriver::hasFeature()).
parent should always be an invalid QModelIndex.
See also
fetchMore()
Reimplemented from QAbstractItemModel.
Definition at line 214 of file qsqlquerymodel.cpp.
 {
     Q_D(const QSqlQueryModel);
     return (!parent.isValid() && !d->atEnd);
 }
clear()
void QSqlQueryModel::clear (void) virtual
Clears the model and releases any acquired resource.
Reimplemented in QSqlRelationalTableModel, and QSqlTableModel.
Definition at line 413 of file qsqlquerymodel.cpp.
Referenced by QSqlTableModel::clear().
 {
     Q_D(QSqlQueryModel);
     d->error = QSqlError();
     d->atEnd = true;
     d->query.clear();
     d->rec.clear();
     d->colOffsets.clear();
     d->bottom = QModelIndex();
     d->headers.clear();
 }
columnCount()
int QSqlQueryModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 243 of file qsqlquerymodel.cpp.
Referenced by QSqlTableModel::revertRow(), setHeaderData(), and QSqlTableModel::setRecord().
 {
     Q_D(const QSqlQueryModel);
     return index.isValid() ? 0 : d->rec.count();
 }
data()
QVariant QSqlQueryModel::data (const QModelIndex & item, int role = Qt::DisplayRole) const virtual
Returns the value for the specified item and role.
If item is out of bounds or if an error occurred, an invalid QVariant is returned.
See also
lastError()
Implements QAbstractItemModel.
Reimplemented in QSqlRelationalTableModel, and QSqlTableModel.
Definition at line 257 of file qsqlquerymodel.cpp.
Referenced by QSqlTableModel::data(), and record().
 {
     Q_D(const QSqlQueryModel);
     if (!item.isValid())
         return QVariant();
     QVariant v;
     if (role & ~(Qt::DisplayRole | Qt::EditRole))
         return v;
     if (!d->rec.isGenerated(item.column()))
         return v;
     QModelIndex dItem = indexInQuery(item);
     if (dItem.row() > d->bottom.row())
         const_cast<QSqlQueryModelPrivate *>(d)->prefetch(dItem.row());
     if (!d->query.seek(dItem.row())) {
         d->error = d->query.lastError();
         return v;
     }
     return d->query.value(dItem.column());
 }
fetchMore()
void QSqlQueryModel::fetchMore (const QModelIndex & parent = QModelIndex()) virtual
Fetches more rows from a database.
Since
4.1
This only affects databases that don't report back the size of a query (see QSqlDriver::hasFeature()).
To force fetching of the entire result set, you can use the following:
while (myModel->canFetchMore())
    myModel->fetchMore();
parent should always be an invalid QModelIndex.
See also
canFetchMore()
Reimplemented from QAbstractItemModel.
Definition at line 192 of file qsqlquerymodel.cpp.
Referenced by setQuery().
 {
     Q_D(QSqlQueryModel);
     if (parent.isValid())
         return;
     d->prefetch(qMax(d->bottom.row(), 0) + QSQL_PREFETCH);
 }
headerData()
QVariant QSqlQueryModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Returns the header data for the given role in the section of the header with the specified orientation.
Reimplemented from QAbstractItemModel.
Reimplemented in QSqlTableModel.
Definition at line 285 of file qsqlquerymodel.cpp.
Referenced by QSqlTableModel::headerData().
 {
     Q_D(const QSqlQueryModel);
     if (orientation == Qt::Horizontal) {
         QVariant val = d->headers.value(section).value(role);
         if (role == Qt::DisplayRole && !val.isValid())
             val = d->headers.value(section).value(Qt::EditRole);
         if (val.isValid())
             return val;
         // See if it's an inserted column (iiq.column() != -1)
         QModelIndex dItem = indexInQuery(createIndex(0, section));
         if (role == Qt::DisplayRole && d->rec.count() > section && dItem.column() != -1)
             return d->rec.fieldName(section);
     }
     return QAbstractItemModel::headerData(section, orientation, role);
 }
indexInQuery()
QModelIndex QSqlQueryModel::indexInQuery (const QModelIndex & item) const protected
Returns the index of the value in the database result set for the given item in the model.
The return value is identical to item if no columns or rows have been inserted, removed, or moved around.
Returns an invalid model index if item is out of bounds or if item does not point to a value in the result set.
See also
QSqlTableModel::indexInQuery(), insertColumns(), removeColumns()
Definition at line 608 of file qsqlquerymodel.cpp.
Referenced by data(), headerData(), and QSqlTableModel::indexInQuery().
 {
     Q_D(const QSqlQueryModel);
     if (item.column() < 0 || item.column() >= d->rec.count()
         || !d->rec.isGenerated(item.column()))
         return QModelIndex();
     return createIndex(item.row(), item.column() - d->colOffsets[item.column()],
                        item.internalPointer());
 }
insertColumns()
bool QSqlQueryModel::insertColumns (int column, int count, const QModelIndex & parent = QModelIndex()) virtual
Inserts count columns into the model at position column.
The parent parameter must always be an invalid QModelIndex, since the model does not support parent-child relationships.
Returns true if column is within bounds; otherwise returns false.
By default, inserted columns are empty. To fill them with data, reimplement data() and handle any inserted column separately:
QVariant MyModel::data(const QModelIndex &item, int role) const
{
    if (item.column() == m_specialColumnNo) {
        // handle column separately
    }
    return QSqlQueryModel::data(item, role);
}
See also
removeColumns()
Reimplemented from QAbstractItemModel.
Definition at line 543 of file qsqlquerymodel.cpp.
 {
     Q_D(QSqlQueryModel);
     if (count <= 0 || parent.isValid() || column < 0 || column > d->rec.count())
         return false;
     beginInsertColumns(parent, column, column + count - 1);
     for (int c = 0; c < count; ++c) {
         QSqlField field;
         field.setReadOnly(true);
         field.setGenerated(false);
         d->rec.insert(column, field);
         if (d->colOffsets.size() < d->rec.count()) {
             int nVal = d->colOffsets.isEmpty() ? 0 : d->colOffsets[d->colOffsets.size() - 1];
             d->colOffsets.append(nVal);
             Q_ASSERT(d->colOffsets.size() >= d->rec.count());
         }
         for (int i = column + 1; i < d->colOffsets.count(); ++i)
             ++d->colOffsets[i];
     }
     endInsertColumns();
     return true;
 }
lastError()
QSqlError QSqlQueryModel::lastError () const
Returns information about the last error that occurred on the database.
See also
query()
Definition at line 470 of file qsqlquerymodel.cpp.
Referenced by QSqlTableModel::select().
 {
     Q_D(const QSqlQueryModel);
     return d->error;
 }
query()
QSqlQuery QSqlQueryModel::query () const
Returns the QSqlQuery associated with this model.
See also
setQuery()
Definition at line 458 of file qsqlquerymodel.cpp.
Referenced by QSqlTableModel::select(), QSqlRelationalTableModel::selectStatement(), QSqlTableModel::selectStatement(), and setQuery().
 {
     Q_D(const QSqlQueryModel);
     return d->query;
 }
queryChange()
void QSqlQueryModel::queryChange () protected virtual
This virtual function is called whenever the query changes.
The default implementation does nothing.
query() returns the new query.
See also
query(), setQuery()
Definition at line 312 of file qsqlquerymodel.cpp.
Referenced by setQuery().
 {
     // do nothing
 }
record() [1/2]
QSqlRecord QSqlQueryModel::record (int row) const
Returns the record containing information about the fields of the current query.
If row is the index of a valid row, the record will be populated with values from that row.
If the model is not initialized, an empty record will be returned.
See also
QSqlRecord::isEmpty()
Definition at line 498 of file qsqlquerymodel.cpp.
Referenced by QRelation::populateDictionary().
 {
     Q_D(const QSqlQueryModel);
     if (row < 0)
         return d->rec;
     QSqlRecord rec = d->rec;
     for (int i = 0; i < rec.count(); ++i)
         rec.setValue(i, data(createIndex(row, i), Qt::EditRole));
     return rec;
 }
record() [2/2]
QSqlRecord QSqlQueryModel::record () const
Returns an empty record containing information about the fields of the current query.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the model is not initialized, an empty record will be returned.
See also
QSqlRecord::isEmpty()
Definition at line 523 of file qsqlquerymodel.cpp.
 {
     Q_D(const QSqlQueryModel);
     return d->rec;
 }
removeColumns()
bool QSqlQueryModel::removeColumns (int column, int count, const QModelIndex & parent = QModelIndex()) virtual
Removes count columns from the model starting from position column.
The parent parameter must always be an invalid QModelIndex, since the model does not support parent-child relationships.
Removing columns effectively hides them. It does not affect the underlying QSqlQuery.
Returns true if the columns were removed; otherwise returns false.
Reimplemented from QAbstractItemModel.
Reimplemented in QSqlTableModel, and QSqlRelationalTableModel.
Definition at line 578 of file qsqlquerymodel.cpp.
 {
     Q_D(QSqlQueryModel);
     if (count <= 0 || parent.isValid() || column < 0 || column >= d->rec.count())
         return false;
     beginRemoveColumns(parent, column, column + count - 1);
     int i;
     for (i = 0; i < count; ++i)
         d->rec.remove(column);
     for (i = column; i < d->colOffsets.count(); ++i)
         d->colOffsets[i] -= count;
     endRemoveColumns();
     return true;
 }
rowCount()
int QSqlQueryModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
If the database supports returning the size of a query (see QSqlDriver::hasFeature()), the number of rows of the current query is returned.
Since
4.1
Otherwise, returns the number of rows currently cached on the client.
parent should always be an invalid QModelIndex.
See also
canFetchMore(), QSqlDriver::hasFeature()
Implements QAbstractItemModel.
Reimplemented in QSqlTableModel.
Definition at line 235 of file qsqlquerymodel.cpp.
Referenced by QSqlTableModel::rowCount().
 {
     Q_D(const QSqlQueryModel);
     return index.isValid() ? 0 : d->bottom.row() + 1;
 }
setHeaderData()
bool QSqlQueryModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole) virtual
Sets the caption for a horizontal header for the specified role to value.
This is useful if the model is used to display data in a view (e.g., QTableView).
Returns true if orientation is Qt::Horizontal and the section refers to a valid section; otherwise returns false.
Note that this function cannot be used to modify values in the database since the model is read-only.
See also
data()
Reimplemented from QAbstractItemModel.
Definition at line 439 of file qsqlquerymodel.cpp.
 {
     Q_D(QSqlQueryModel);
     if (orientation != Qt::Horizontal || section < 0 || columnCount() <= section)
         return false;
     if (d->headers.size() <= section)
         d->headers.resize(qMax(section + 1, 16));
     d->headers[section][role] = value;
     emit headerDataChanged(orientation, section, section);
     return true;
 }
setLastError()
void QSqlQueryModel::setLastError (const QSqlError & error) protected
Protected function which allows derived classes to set the value of the last error that occurred on the database to error.
See also
lastError()
Definition at line 482 of file qsqlquerymodel.cpp.
 {
     Q_D(QSqlQueryModel);
     d->error = error;
 }
setQuery() [1/2]
void QSqlQueryModel::setQuery (const QSqlQuery & query)
Resets the model and sets the data provider to be the given query.
Note that the query must be active and must not be isForwardOnly().
lastError() can be used to retrieve verbose information if there was an error setting the query.
Note
Calling setQuery() will remove any inserted columns.
See also
query(), QSqlQuery::isActive(), QSqlQuery::setForwardOnly(), lastError()
Definition at line 329 of file qsqlquerymodel.cpp.
Referenced by setQuery(), and QSqlTableModel::setQuery().
 {
     Q_D(QSqlQueryModel);
     QSqlRecord newRec = query.record();
     bool columnsChanged = (newRec != d->rec);
     bool hasQuerySize = query.driver()->hasFeature(QSqlDriver::QuerySize);
     bool hasNewData = (newRec != QSqlRecord()) || !query.lastError().isValid();
     if (d->colOffsets.size() != newRec.count() || columnsChanged)
         d->initColOffsets(newRec.count());
     bool mustClearModel = d->bottom.isValid();
     if (mustClearModel) {
         d->atEnd = true;
         beginRemoveRows(QModelIndex(), 0, qMax(d->bottom.row(), 0));
         d->bottom = QModelIndex();
     }
     d->error = QSqlError();
     d->query = query;
     d->rec = newRec;
     if (mustClearModel)
         endRemoveRows();
     d->atEnd = false;
     if (columnsChanged && hasNewData)
         reset();
     if (!query.isActive() || query.isForwardOnly()) {
         d->atEnd = true;
         d->bottom = QModelIndex();
         if (query.isForwardOnly())
             d->error = QSqlError(QLatin1String("Forward-only queries "
                                                "cannot be used in a data model"),
                                  QString(), QSqlError::ConnectionError);
         else
             d->error = query.lastError();
         return;
     }
     QModelIndex newBottom;
     if (hasQuerySize && d->query.size() > 0) {
         newBottom = createIndex(d->query.size() - 1, d->rec.count() - 1);
         beginInsertRows(QModelIndex(), 0, qMax(0, newBottom.row()));
         d->bottom = createIndex(d->query.size() - 1, columnsChanged ? 0 : d->rec.count() - 1);
         d->atEnd = true;
         endInsertRows();
     } else {
         newBottom = createIndex(-1, d->rec.count() - 1);
     }
     d->bottom = newBottom;
     queryChange();
     // fetchMore does the rowsInserted stuff for incremental models
     fetchMore();
 }
setQuery() [2/2]
void QSqlQueryModel::setQuery (const QString & query, const QSqlDatabase & db = QSqlDatabase())
Executes the query query for the given database connection db.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If no database (or an invalid database) is specified, the default connection is used.
lastError() can be used to retrieve verbose information if there was an error setting the query.
Example:
QSqlQueryModel model;
model.setQuery("select * from MyTable");
if (model.lastError().isValid())
    qDebug() << model.lastError();
See also
query(), queryChange(), lastError()
Definition at line 405 of file qsqlquerymodel.cpp.
 {
     setQuery(QSqlQuery(query, db));
 }
The documentation for this class was generated from the following files:
/src/sql/models/qsqlquerymodel.h
/src/sql/models/qsqlquerymodel.cpp