Qt 4.8: QWSInputMethod Class Reference
QWSInputMethod Class Reference
The QWSInputMethod class provides international input methods in Qt for Embedded Linux.
#include <qwindowsystem_qws.h>
Public Types
enum UpdateType {
Update, FocusIn, FocusOut, Reset,
Destroyed
}
This enum describes the various types of update events recognized by the input method.
Public Functions
virtual bool filter (int unicode, int keycode, int modifiers, bool isPress, bool autoRepeat)
Filters the key input identified by the given unicode, keycode, modifiers, isPress and autoRepeat parameters.
virtual bool filter (const QPoint &, int state, int wheel)
Filters the mouse input identified by the given position, state, and wheel parameters.
virtual void mouseHandler (int pos, int state)
Handles mouse events within the preedit text.
virtual void queryResponse (int property, const QVariant &)
Receive replies to an input method query.
QWSInputMethod ()
Constructs a new input method.
virtual void reset ()
Resets the state of the input method.
virtual void updateHandler (int type)
Handles update events including resets and focus changes.
virtual ~QWSInputMethod ()
Destroys this input method, uninstalling it if it is installed.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
uint inputResolutionShift () const
Returns the number of bits shifted to go from pointer resolution to screen resolution when filtering mouse input.
void sendCommitString (const QString &commitString, int replaceFrom=0, int replaceLength=0)
Sends an event encapsulating the given commitString, to the focus widget.
void sendEvent (const QInputMethodEvent *)
Sends the given event to the focus widget.
void sendMouseEvent (const QPoint &pos, int state, int wheel)
Sends a mouse event specified by the given position, state and wheel parameters.
void sendPreeditString (const QString &preeditString, int cursorPosition, int selectionLength=0)
Sends an event encapsulating the given preeditString, to the focus widget.
void sendQuery (int property)
Sends an input method query (internally encapsulated by a QWSEvent of the QWSEvent::IMQuery{IMQuery} type) for the specified property.
uint setInputResolution (bool isHigh)
Sets and returns the number of bits shifted to go from pointer resolution to screen resolution when filtering mouse input.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
bool mIResolution
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QWSInputMethod class provides international input methods in Qt for Embedded Linux.
This function is under development and subject to change.
Note that this class is only available in Qt for Embedded Linux.
A Qt for Embedded Linux application requires a server application to be running, or to be the server application itself. All system generated events, including keyboard and mouse events, are passed to the server application which then propagates the event to the appropriate client.
An input method consists of a filter and optionally a graphical interface, and is used to filter input events between the server and the client application.
Creating Custom Input Methods
To implement a custom input method, derive from the QWSInputMethod class, and use the server's QWSServer::setCurrentInputMethod() function to install it.
When subclassing QWSInputMethod, you can reimplement the filter() functions to handle input from both physical and virtual keyboards as well as mouse devices. Note that the default implementations do nothing. Use the setInputResolution() function to control the number of bits shifted when filtering mouse input, i.e., when going from pointer resolution to screen resolution (the current resolution can be retrieved using the inputResolutionShift() function).
Reimplement the reset() function to restore the state of the input method. Note that the default implementation calls the sendEvent() function with empty preedit and commit strings if the input method is in compose mode (i.e., if the input method is actively composing a preedit string).
To receive replies to an input method query (sent using the sendQuery() function), you must reimplement the queryResponse() function, while the mouseHandler() function must be reimplemented if you want to handle mouse events within the preedit text. Reimplement the updateHandler() function to handle update events including resets and focus changes. The UpdateType enum describes the various types of update events recognized by the input method.
Using Input Methods
In addition to the filter(), reset(), queryResponse(), mouseHandler() and updateHandler() function mentioned in the previous section, the QWSInputMethod provides several other functions helping the window system to manage the installed input methods.
The sendEvent() function sends the given event to the focus widget, while the sendPreeditString() function sends the given preedit text (encapsulated by an event). QWSInputMethod also provides the sendCommitString() convenience function which sends an event encapsulating the given commit string to the current focus widget, and the sendMouseEvent() function which sends the given mouse event.
Finally, the QWSInputMethod class provides the sendQuery() function for sending input method queries. This function encapsulates the event with a QWSEvent instance of the QWSEvent::IMQuery type.
See also
QWSServer, {Qt for Embedded Linux Architecture}
Definition at line 371 of file qwindowsystem_qws.h.
Enumerations
UpdateType
enum QWSInputMethod::UpdateType
This enum describes the various types of update events recognized by the input method.
Update The input widget is updated in some way; use sendQuery() with Qt::ImMicroFocus as an argument for more information.
FocusIn A new input widget receives focus.
FocusOut The input widget loses focus.
Reset The input method should be reset.
Destroyed The input widget is destroyed.
See also
updateHandler()
Enumerator
Update
FocusIn
FocusOut
Reset
Destroyed
Definition at line 378 of file qwindowsystem_qws.h.
 {Update, FocusIn, FocusOut, Reset, Destroyed};
Constructors and Destructors
QWSInputMethod()
QWSInputMethod::QWSInputMethod ()
Constructs a new input method.
Use the QWSServer::setCurrentInputMethod() function to install it.
Definition at line 4672 of file qwindowsystem_qws.cpp.
 {
 }
~QWSInputMethod()
QWSInputMethod::~QWSInputMethod () virtual
Destroys this input method, uninstalling it if it is installed.
Definition at line 4680 of file qwindowsystem_qws.cpp.
 {
     if (current_IM == this)
         current_IM = 0;
 }
Functions
filter() [1/2]
bool QWSInputMethod::filter (int unicode, int keycode, int modifiers, bool isPress, bool autoRepeat) virtual
Filters the key input identified by the given unicode, keycode, modifiers, isPress and autoRepeat parameters.
Note that the default implementation does nothing; reimplement this function to handle input from both physical and virtual devices.
The keycode is a Qt::Key value, and the modifiers is an OR combination of Qt::KeyboardModifiers. The isPress parameter is telling whether the input is a key press or key release, and the autoRepeat parameter determines whether the input is autorepeated (i.e., in which case the QWSKeyboardHandler::beginAutoRepeat() function has been called).
To block the event from further processing, return true when reimplementing this function; the default implementation returns false.
See also
setInputResolution(), inputResolutionShift()
Definition at line 4707 of file qwindowsystem_qws.cpp.
Referenced by QWSServer::sendKeyEvent(), and QWSServer::sendMouseEvent().
 {
     Q_UNUSED(unicode);
     Q_UNUSED(keycode);
     Q_UNUSED(modifiers);
     Q_UNUSED(isPress);
     Q_UNUSED(autoRepeat);
     return false;
 }
filter() [2/2]
bool QWSInputMethod::filter (const QPoint & position, int state, int wheel) virtual
Filters the mouse input identified by the given position, state, and wheel parameters.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4726 of file qwindowsystem_qws.cpp.
 {
     Q_UNUSED(position);
     Q_UNUSED(state);
     Q_UNUSED(wheel);
     return false;
 }
inputResolutionShift()
uint QWSInputMethod::inputResolutionShift () const protected
Returns the number of bits shifted to go from pointer resolution to screen resolution when filtering mouse input.
See also
setInputResolution(), filter()
Definition at line 5002 of file qwindowsystem_qws.cpp.
 {
     return 0; // default for devices with single resolution.
 }
mouseHandler()
void QWSInputMethod::mouseHandler (int offset, int state) virtual
Handles mouse events within the preedit text.
Note that the default implementation resets the input method on all mouse presses; reimplement this function to alter this behavior.
The offset parameter specifies the position of the mouse event within the string, and state specifies the type of the mouse event as described by the QWSServer::IMMouse enum. If state is less than 0, the mouse event is inside the associated widget, but outside the preedit text. When clicking in a different widget, the state is QWSServer::MouseOutside.
See also
sendPreeditString(), reset()
Definition at line 4836 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::doClient(), QWSServerPrivate::send_im_mouse(), and QWSServerPrivate::sendMouseEventUnfiltered().
 {
     if (state == QWSServer::MousePress || state == QWSServer::MouseOutside)
         reset();
 }
queryResponse()
void QWSInputMethod::queryResponse (int property, const QVariant & result) virtual
Receive replies to an input method query.
Note that the default implementation does nothing; reimplement this function to receive such replies.
Internally, an input method query is passed encapsulated by an QWSEvent::IMQuery event generated by the sendQuery() function. The queried property and the result is passed in the property and result parameters.
See also
sendQuery(), QWSServer::sendIMQuery()
Definition at line 4807 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeIMResponse().
 {
     Q_UNUSED(property);
     Q_UNUSED(result);
 }
reset()
void QWSInputMethod::reset () virtual
Resets the state of the input method.
If the input method is in compose mode, i.e., the input method is actively composing a preedit string, the default implementation calls sendEvent() with empty preedit and commit strings; otherwise it does nothing. Reimplement this function to alter this behavior.
See also
sendEvent()
Definition at line 4744 of file qwindowsystem_qws.cpp.
Referenced by QWSServer::resetInputMethod(), and QWSServer::setCurrentInputMethod().
 {
     if (current_IM_composing_win) {
         QInputMethodEvent ime;
         sendEvent(&ime);
     }
 }
sendCommitString()
void QWSInputMethod::sendCommitString (const QString & commitString, int replaceFromPosition = 0, int replaceLength = 0) protected
Sends an event encapsulating the given commitString, to the focus widget.
Note that this will cause the input method to leave compose mode, i.e., the input method will no longer be actively composing the preedit string.
If the specified replaceLength is greater than 0, the commit string will replace the given number of characters of the receiving widget's previous text, starting at the given replaceFromPosition relative to the start of the current preedit string.
Internally, the event is represented by a QWSEvent object of the QWSEvent::IMEvent{IMEvent} type.
See also
sendEvent(), sendPreeditString()
Definition at line 4923 of file qwindowsystem_qws.cpp.
 {
     QInputMethodEvent ime;
     ime.setCommitString(commitString, replaceFrom, replaceLength);
     qwsServer->sendIMEvent(&ime);
 }
sendEvent()
void QWSInputMethod::sendEvent (const QInputMethodEvent * event) inline protected
Sends the given event to the focus widget.
The QInputMethodEvent class is derived from QWSEvent, i.e., the given event is a QWSEvent object of the QWSEvent::IMEvent type.
See also
sendPreeditString(), sendCommitString(), reset()
Definition at line 408 of file qwindowsystem_qws.h.
 {
     qwsServer->sendIMEvent(ime);
 }
sendMouseEvent()
void QWSInputMethod::sendMouseEvent (const QPoint & position, int state, int wheel) protected
Sends a mouse event specified by the given position, state and wheel parameters.
The given position will be transformed if the screen coordinates do not match the pointer device coordinates.
Note that the event will be not be tested by the active input method, but calling the QWSServer::sendMouseEvent() function will make the current input method filter the event.
See also
mouseHandler(), sendEvent()
Definition at line 5025 of file qwindowsystem_qws.cpp.
 {
         if (qt_last_x) {
          *qt_last_x = pos.x();
          *qt_last_y = pos.y();
     }
     QWSServer::mousePosition = pos;
     qwsServerPrivate->mouseState = state;
     QWSServerPrivate::sendMouseEventUnfiltered(pos, state, wheel);
 }
sendPreeditString()
void QWSInputMethod::sendPreeditString (const QString & preeditString, int cursorPosition, int selectionLength = 0) protected
Sends an event encapsulating the given preeditString, to the focus widget.
The specified selectionLength is the number of characters to be marked as selected (starting at the given cursorPosition). If selectionLength is negative, the text before cursorPosition is marked.
The preedit string is marked with QInputContext::PreeditFormat, and the selected part is marked with QInputContext::SelectionFormat.
Sending an input method event with a non-empty preedit string will cause the input method to enter compose mode. Sending an input method event with an empty preedit string will cause the input method to leave compose mode, i.e., the input method will no longer be actively composing the preedit string.
Internally, the event is represented by a QWSEvent object of the QWSEvent::IMEvent{IMEvent} type.
See also
sendEvent(), sendCommitString()
Definition at line 4868 of file qwindowsystem_qws.cpp.
 {
     QList<QInputMethodEvent::Attribute> attributes;
     int selPos = cursorPosition;
     if (selectionLength == 0) {
         selPos = 0;
     } else if (selectionLength < 0) {
         selPos += selectionLength;
         selectionLength = -selectionLength;
     }
     if (selPos > 0)
         attributes += QInputMethodEvent::Attribute(QInputMethodEvent::TextFormat, 0, selPos,
                                                    QVariant(int(QInputContext::PreeditFormat)));
     if (selectionLength)
         attributes += QInputMethodEvent::Attribute(QInputMethodEvent::TextFormat, selPos, selectionLength,
                                                    QVariant(int(QInputContext::SelectionFormat)));
     if (selPos + selectionLength < preeditString.length())
         attributes += QInputMethodEvent::Attribute(QInputMethodEvent::TextFormat,
                                                    selPos + selectionLength,
                                                    preeditString.length() - selPos - selectionLength,
                                                    QVariant(int(QInputContext::PreeditFormat)));
     attributes += QInputMethodEvent::Attribute(QInputMethodEvent::Cursor, cursorPosition,  0, QVariant());
     QInputMethodEvent ime(preeditString, attributes);
     qwsServer->sendIMEvent(&ime);
 }
sendQuery()
void QWSInputMethod::sendQuery (int property) inline protected
Sends an input method query (internally encapsulated by a QWSEvent of the QWSEvent::IMQuery{IMQuery} type) for the specified property.
To receive responses to input method queries, the virtual queryResponse() function must be reimplemented.
See also
queryResponse(), QWSServer::sendIMQuery()
Definition at line 419 of file qwindowsystem_qws.h.
 {
     qwsServer->sendIMQuery(property);
 }
setInputResolution()
uint QWSInputMethod::setInputResolution (bool isHigh) protected
Sets and returns the number of bits shifted to go from pointer resolution to screen resolution when filtering mouse input.
If isHigh is true and the device has a pointer device resolution twice or more of the screen resolution, the positions passed to the filter() function will be presented at the higher resolution; otherwise the resolution will be equal to that of the screen resolution.
See also
inputResolutionShift(), filter()
Definition at line 4990 of file qwindowsystem_qws.cpp.
 {
     mIResolution = isHigh;
     return inputResolutionShift();
 }
updateHandler()
void QWSInputMethod::updateHandler (int type) virtual
Handles update events including resets and focus changes.
The update events are specified by the given type which is one of the UpdateType enum values.
Note that reimplementations of this function must call the base implementation for all cases that it does not handle itself.
See also
UpdateType
Definition at line 4781 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeIMUpdate(), and QWSServerPrivate::setFocus().
 {
     switch (type) {
     case FocusOut:
     case Reset:
         reset();
         break;
     default:
         break;
     }
 }
Properties
mIResolution
bool QWSInputMethod::mIResolution private
Definition at line 405 of file qwindowsystem_qws.h.
The documentation for this class was generated from the following files:
/src/gui/embedded/qwindowsystem_qws.h
/src/gui/embedded/qwindowsystem_qws.cpp