Qt 4.8: QPolygon Class Reference
QPolygon Class Reference
The QPolygon class provides a vector of points using integer precision.
#include <qpolygon.h>
Public Functions
QRect boundingRect () const
Returns the bounding rectangle of the polygon, or QRect(0, 0, 0, 0) if the polygon is empty.
bool containsPoint (const QPoint &pt, Qt::FillRule fillRule) const
Returns true if the given point is inside the polygon according to the specified fillRule; otherwise returns false.
QPolygon intersected (const QPolygon &r) const
Returns a polygon which is the intersection of this polygon and r.
operator QVariant () const
Returns the polygon as a QVariant.
void point (int i, int *x, int *y) const
Extracts the coordinates of the point at the given index to {x} and *{y} (if they are valid pointers).
QPoint point (int i) const
Returns the point at the given index.
void putPoints (int index, int nPoints, const int *points)
Copies nPoints points from the points coord array into this point array, and resizes the point array if index+nPoints exceeds the size of the array.
void putPoints (int index, int nPoints, int firstx, int firsty,...)
Copies nPoints points from the variable argument list into this polygon from the given index.
void putPoints (int index, int nPoints, const QPolygon &from, int fromIndex=0)
Copies nPoints points from the given fromIndex (0 by default) in fromPolygon into this polygon, starting at the specified index.
QPolygon ()
Constructs a polygon with no points.
QPolygon (int size)
Constructs a polygon of the given size.
QPolygon (const QPolygon &a)
Constructs a copy of the given polygon.
QPolygon (const QVector< QPoint > &v)
Constructs a polygon containing the specified points.
QPolygon (const QRect &r, bool closed=false)
Constructs a polygon from the given rectangle.
QPolygon (int nPoints, const int *points)
Constructs a point array with nPoints points, taken from the points array.
void setPoint (int index, int x, int y)
Sets the point at the given index to the point specified by ({x}, {y}).
void setPoint (int index, const QPoint &p)
Sets the point at the given index to the given point.
void setPoints (int nPoints, const int *points)
Resizes the polygon to nPoints and populates it with the given points.
void setPoints (int nPoints, int firstx, int firsty,...)
Resizes the polygon to nPoints and populates it with the points specified by the variable argument list.
QPolygon subtracted (const QPolygon &r) const
Returns a polygon which is r subtracted from this polygon.
void swap (QPolygon &other)
Swaps polygon other with this polygon.
void translate (int dx, int dy)
Translates all points in the polygon by ({dx}, {dy}).
void translate (const QPoint &offset)
Translates all points in the polygon by the given offset.
QPolygon translated (int dx, int dy) const
Returns a copy of the polygon that is translated by ({dx}, {dy}).
QPolygon translated (const QPoint &offset) const
Returns a copy of the polygon that is translated by the given offset.
QPolygon united (const QPolygon &r) const
Returns a polygon which is the union of this polygon and r.
~QPolygon ()
Destroys the polygon.
Public Functions inherited from QVector< QPoint >
void append (const QPoint &t)
Inserts value at the end of the vector.
const QPoint & at (int i) const
Returns the item at index position i in the vector.
reference back ()
This function is provided for STL compatibility.
const_reference back () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator begin ()
Returns an STL-style iterator pointing to the first item in the vector.
const_iterator begin () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int capacity () const
Returns the maximum number of items that can be stored in the vector without forcing a reallocation.
void clear ()
Removes all the elements from the vector and releases the memory used by the vector.
const_iterator constBegin () const
Returns a const STL-style iterator pointing to the first item in the vector.
const QPoint * constData () const
Returns a const pointer to the data stored in the vector.
const_iterator constEnd () const
Returns a const STL-style iterator pointing to the imaginary item after the last item in the vector.
bool contains (const QPoint &t) const
Returns true if the vector contains an occurrence of value; otherwise returns false.
int count (const QPoint &t) const
Returns the number of occurrences of value in the vector.
int count () const
Same as size().
QPoint * data ()
Returns a pointer to the data stored in the vector.
const QPoint * data () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void detach ()
bool empty () const
This function is provided for STL compatibility.
iterator end ()
Returns an STL-style iterator pointing to the imaginary item after the last item in the vector.
const_iterator end () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool endsWith (const QPoint &t) const
Returns true if this vector is not empty and its last item is equal to value; otherwise returns false.
iterator erase (iterator begin, iterator end)
Removes all the items from begin up to (but not including) end.
iterator erase (iterator pos)
Removes the item pointed to by the iterator pos from the vector, and returns an iterator to the next item in the vector (which may be end()).
QVector< QPoint > & fill (const QPoint &t, int size=-1)
Assigns value to all items in the vector.
QPoint & first ()
Returns a reference to the first item in the vector.
const QPoint & first () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QPoint & front ()
This function is provided for STL compatibility.
const_reference front () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int indexOf (const QPoint &t, int from=0) const
Returns the index position of the first occurrence of value in the vector, searching forward from index position from.
void insert (int i, const QPoint &t)
Inserts value at index position i in the vector.
void insert (int i, int n, const QPoint &t)
Inserts count copies of value at index position i in the vector.
iterator insert (iterator before, int n, const QPoint &x)
Inserts count copies of value in front of the item pointed to by the iterator before.
iterator insert (iterator before, const QPoint &x)
Inserts value in front of the item pointed to by the iterator before.
bool isDetached () const
bool isEmpty () const
Returns true if the vector has size 0; otherwise returns false.
bool isSharedWith (const QVector< QPoint > &other) const
QPoint & last ()
Returns a reference to the last item in the vector.
const QPoint & last () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int lastIndexOf (const QPoint &t, int from=-1) const
Returns the index position of the last occurrence of the value value in the vector, searching backward from index position from.
QVector< QPoint > mid (int pos, int length=-1) const
Returns a vector whose elements are copied from this vector, starting at position pos.
bool operator!= (const QVector< QPoint > &v) const
Returns true if other is not equal to this vector; otherwise returns false.
QVector< QPoint > operator+ (const QVector< QPoint > &l) const
Returns a vector that contains all the items in this vector followed by all the items in the other vector.
QVector< QPoint > & operator+= (const QVector< QPoint > &l)
Appends the items of the other vector to this vector and returns a reference to this vector.
QVector< QPoint > & operator+= (const QPoint &t)
Appends value to the vector.
QVector< QPoint > & operator<< (const QVector< QPoint > &l)
Appends other to the vector and returns a reference to the vector.
QVector< QPoint > & operator<< (const QPoint &t)
Appends value to the vector and returns a reference to this vector.
QVector< QPoint > & operator= (const QVector< QPoint > &v)
Assigns other to this vector and returns a reference to this vector.
bool operator== (const QVector< QPoint > &v) const
Returns true if other is equal to this vector; otherwise returns false.
QPoint & operator[] (int i)
Returns the item at index position i as a modifiable reference.
const QPoint & operator[] (int i) const
Same as at(i).
void pop_back ()
This function is provided for STL compatibility.
void pop_front ()
This function is provided for STL compatibility.
void prepend (const QPoint &t)
Inserts value at the beginning of the vector.
void push_back (const QPoint &t)
This function is provided for STL compatibility.
void push_front (const QPoint &t)
This function is provided for STL compatibility.
QVector ()
Constructs an empty vector.
QVector (int size)
Constructs a vector with an initial size of size elements.
QVector (int size, const QPoint &t)
Constructs a vector with an initial size of size elements.
QVector (const QVector< QPoint > &v)
Constructs a copy of other.
void remove (int i)
Removes the element at index position i.
void remove (int i, int n)
Removes count elements from the middle of the vector, starting at index position i.
void replace (int i, const QPoint &t)
Replaces the item at index position i with value.
void reserve (int size)
Attempts to allocate memory for at least size elements.
void resize (int size)
Sets the size of the vector to size.
void setSharable (bool sharable)
int size () const
Returns the number of items in the vector.
void squeeze ()
Releases any memory not required to store the items.
bool startsWith (const QPoint &t) const
Returns true if this vector is not empty and its first item is equal to value; otherwise returns false.
void swap (QVector< QPoint > &other)
Swaps vector other with this vector.
QList< QPoint > toList () const
Returns a QList object with the data contained in this QVector.
std::vector< QPoint > toStdVector () const
Returns a std::vector object with the data contained in this QVector.
QPoint value (int i) const
Returns the value at index position i in the vector.
QPoint value (int i, const QPoint &defaultValue) const
If the index i is out of bounds, the function returns defaultValue.
~QVector ()
Destroys the vector.
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QPolygon &polygon)
Writes the given polygon to the given stream, and returns a reference to the stream.
QDataStream & operator>> (QDataStream &stream, QPolygon &polygon)
Reads a polygon from the given stream into the given polygon, and returns a reference to the stream.
Related Functions inherited from QVector< QPoint >
QDataStream & operator<< (QDataStream &out, const QVector< QPoint > &vector)
Writes the vector vector to stream out.
QDataStream & operator>> (QDataStream &in, QVector< QPoint > &vector)
Reads a vector from stream in into vector.
Additional Inherited Members
Public Types inherited from QVector< QPoint >
typedef const QPoint * const_iterator
The QVector::const_iterator typedef provides an STL-style const iterator for QVector and QStack.
typedef const value_type * const_pointer
Typedef for const T *.
typedef const value_type & const_reference
Typedef for T &.
typedef const_iterator ConstIterator
Qt-style synonym for QVector::const_iterator.
typedef qptrdiff difference_type
Typedef for ptrdiff_t.
typedef QPoint * iterator
The QVector::iterator typedef provides an STL-style non-const iterator for QVector and QStack.
typedef iterator Iterator
Qt-style synonym for QVector::iterator.
typedef value_type * pointer
Typedef for T *.
typedef value_type & reference
Typedef for T &.
typedef int size_type
Typedef for int.
typedef QPoint value_type
Typedef for T.
Static Public Functions inherited from QVector< QPoint >
static QVector< QPoint > fromList (const QList< QPoint > &list)
Returns a QVector object with the data contained in list.
static QVector< QPoint > fromStdVector (const std::vector< QPoint > &vector)
Returns a QVector object with the data contained in vector.
Public Variables inherited from QVector< QPoint >
QVectorData * d
Data * p
Detailed Description
The QPolygon class provides a vector of points using integer precision.
Note
This class or function is reentrant.
A QPolygon object is a QVector<QPoint>. The easiest way to add points to a QPolygon is to use QVector's streaming operator, as illustrated below:
        QPolygon polygon;
        polygon << QPoint(10, 20) << QPoint(20, 30);
In addition to the functions provided by QVector, QPolygon provides some point-specific functions.
Each point in a polygon can be retrieved by passing its index to the point() function. To populate the polygon, QPolygon provides the setPoint() function to set the point at a given index, the setPoints() function to set all the points in the polygon (resizing it to the given number of points), and the putPoints() function which copies a number of given points into the polygon from a specified index (resizing the polygon if necessary).
QPolygon provides the boundingRect() and translate() functions for geometry functions. Use the QMatrix::map() function for more general transformations of QPolygons.
The QPolygon class is Implicit Data Sharing.
See also
QVector, QPolygonF, QLine
Definition at line 60 of file qpolygon.h.
Constructors and Destructors
QPolygon() [1/6]
QPolygon::QPolygon () inline
Constructs a polygon with no points.
See also
QVector::isEmpty()
Definition at line 63 of file qpolygon.h.
 {}
~QPolygon()
QPolygon::~QPolygon () inline
Destroys the polygon.
Definition at line 64 of file qpolygon.h.
 {}
QPolygon() [2/6]
QPolygon::QPolygon (int size) inline
Constructs a polygon of the given size.
Creates an empty polygon if size == 0.
See also
QVector::isEmpty()
Definition at line 99 of file qpolygon.h.
 : QVector<QPoint>(asize) {}
QPolygon() [3/6]
QPolygon::QPolygon (const QPolygon & polygon) inline
Constructs a copy of the given polygon.
See also
setPoints()
Definition at line 66 of file qpolygon.h.
 : QVector<QPoint>(a) {}
QPolygon() [4/6]
QPolygon::QPolygon (const QVector< QPoint > & points) inline
Constructs a polygon containing the specified points.
See also
setPoints()
Definition at line 67 of file qpolygon.h.
 : QVector<QPoint>(v) {}
QPolygon() [5/6]
QPolygon::QPolygon (const QRect & rectangle, bool closed = false)
Constructs a polygon from the given rectangle.
If closed is false, the polygon just contains the four points of the rectangle ordered clockwise, otherwise the polygon's fifth point is set to {rectangle}.topLeft().
Note that the bottom-right corner of the rectangle is located at (rectangle.x() + rectangle.width(), rectangle.y() + rectangle.height()).
See also
setPoints()
Definition at line 194 of file qpolygon.cpp.
 {
     reserve(closed ? 5 : 4);
     *this << QPoint(r.x(), r.y())
           << QPoint(r.x() + r.width(), r.y())
           << QPoint(r.x() + r.width(), r.y() + r.height())
           << QPoint(r.x(), r.y() + r.height());
     if (closed)
         *this << QPoint(r.left(), r.top());
 }
QPolygon() [6/6]
QPolygon::QPolygon (int nPoints, const int * points)
Constructs a point array with nPoints points, taken from the points array.
Warning
This function is not part of the public interface.
Equivalent to setPoints(nPoints, points).
Definition at line 216 of file qpolygon.cpp.
 {
     setPoints(nPoints, points);
 }
Functions
boundingRect()
QRect QPolygon::boundingRect () const
Returns the bounding rectangle of the polygon, or QRect(0, 0, 0, 0) if the polygon is empty.
See also
QVector::isEmpty()
Definition at line 492 of file qpolygon.cpp.
Referenced by QWindowsStyle::drawPrimitive(), QX11PaintEnginePrivate::fillPolygon_dev(), and QPolygonF::isClosed().
 {
     if (isEmpty())
         return QRect(0, 0, 0, 0);
     register const QPoint *pd = constData();
     int minx, maxx, miny, maxy;
     minx = maxx = pd->x();
     miny = maxy = pd->y();
     ++pd;
     for (int i = 1; i < size(); ++i) {
         if (pd->x() < minx)
             minx = pd->x();
         else if (pd->x() > maxx)
             maxx = pd->x();
         if (pd->y() < miny)
             miny = pd->y();
         else if (pd->y() > maxy)
             maxy = pd->y();
         ++pd;
     }
     return QRect(QPoint(minx,miny), QPoint(maxx,maxy));
 }
containsPoint()
bool QPolygon::containsPoint (const QPoint & point, Qt::FillRule fillRule) const
Returns true if the given point is inside the polygon according to the specified fillRule; otherwise returns false.
Since
4.3
Definition at line 974 of file qpolygon.cpp.
Referenced by QPolygonF::isClosed().
 {
     if (isEmpty())
         return false;
     int winding_number = 0;
     QPoint last_pt = at(0);
     QPoint last_start = at(0);
     for (int i = 1; i < size(); ++i) {
         const QPoint &e = at(i);
         qt_polygon_isect_line(last_pt, e, pt, &winding_number);
         last_pt = e;
     }
     // implicitly close last subpath
     if (last_pt != last_start)
         qt_polygon_isect_line(last_pt, last_start, pt, &winding_number);
     return (fillRule == Qt::WindingFill
             ? (winding_number != 0)
             : ((winding_number % 2) != 0));
 }
intersected()
QPolygon QPolygon::intersected (const QPolygon & r) const
Returns a polygon which is the intersection of this polygon and r.
Since
4.3
Set operations on polygons will treat the polygons as areas. Non-closed polygons will be treated as implicitly closed.
Definition at line 1032 of file qpolygon.cpp.
Referenced by QPolygonF::isClosed().
 {
     QPainterPath subject; subject.addPolygon(*this);
     QPainterPath clip; clip.addPolygon(r);
     return subject.intersected(clip).toFillPolygon().toPolygon();
 }
operator QVariant()
QPolygon::operator QVariant () const
Returns the polygon as a QVariant.
Definition at line 806 of file qpolygon.cpp.
 {
     return QVariant(QVariant::Polygon, this);
 }
point() [1/2]
void QPolygon::point (int index, int * x, int * y) const
Extracts the coordinates of the point at the given index to {x} and *{y} (if they are valid pointers).
See also
setPoint()
Definition at line 297 of file qpolygon.cpp.
Referenced by QCommonStyle::drawControl().
 {
     QPoint p = at(index);
     if (x)
         *x = (int)p.x();
     if (y)
         *y = (int)p.y();
 }
point() [2/2]
QPoint QPolygon::point (int index) const inline
Returns the point at the given index.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 123 of file qpolygon.h.
 { return at(index); }
putPoints() [1/3]
void QPolygon::putPoints (int index, int nPoints, const int * points)
Copies nPoints points from the points coord array into this point array, and resizes the point array if index+nPoints exceeds the size of the array.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Warning
This function is not part of the public interface.
See also
setPoint()
Definition at line 406 of file qpolygon.cpp.
Referenced by QMotifStyle::drawPrimitive(), and qDrawPlainRect().
 {
     if (index + nPoints > size())
         resize(index + nPoints);
     int i = index;
     while (nPoints--) {
         setPoint(i++, *points, *(points+1));
         points += 2;
     }
 }
putPoints() [2/3]
void QPolygon::putPoints (int index, int nPoints, int firstx, int firsty, ...)
Copies nPoints points from the variable argument list into this polygon from the given index.
The points are given as a sequence of integers, starting with firstx then firsty, and so on. The polygon is resized if index+nPoints exceeds its current size.
The example code creates a polygon with three points (4,5), (6,7) and (8,9), by expanding the polygon from 1 to 3 points:
        QPolygon polygon(1);
        polygon[0] = QPoint(4, 5);
        polygon.putPoints(1, 2, 6,7, 8,9);
The following code has the same result, but here the putPoints() function overwrites rather than extends:
        QPolygon polygon(3);
        polygon.putPoints(0, 3, 4,5, 0,0, 8,9);
        polygon.putPoints(1, 1, 6,7);
See also
setPoints()
Definition at line 438 of file qpolygon.cpp.
 {
     va_list ap;
     if (index + nPoints > size())
         resize(index + nPoints);
     if (nPoints <= 0)
         return;
     setPoint(index, firstx, firsty);
     int i = index, x, y;
     va_start(ap, firsty);
     while (--nPoints) {
         x = va_arg(ap, int);
         y = va_arg(ap, int);
         setPoint(++i, x, y);
     }
     va_end(ap);
 }
putPoints() [3/3]
void QPolygon::putPoints (int index, int nPoints, const QPolygon & fromPolygon, int fromIndex = 0)
Copies nPoints points from the given fromIndex (0 by default) in fromPolygon into this polygon, starting at the specified index.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
For example:
        QPolygon polygon1;
        polygon1.putPoints(0, 3, 1,2, 0,0, 5,6);
        // polygon1 is now the three-point polygon(1,2, 0,0, 5,6);
        QPolygon polygon2;
        polygon2.putPoints(0, 3, 4,4, 5,5, 6,6);
        // polygon2 is now (4,4, 5,5, 6,6);
        polygon1.putPoints(2, 3, polygon2);
        // polygon1 is now the five-point polygon(1,2, 0,0, 4,4, 5,5, 6,6);
Definition at line 471 of file qpolygon.cpp.
 {
     if (index + nPoints > size())
         resize(index + nPoints);
     if (nPoints <= 0)
         return;
     int n = 0;
     while(n < nPoints) {
         setPoint(index + n, from[fromIndex+n]);
         ++n;
     }
 }
setPoint() [1/2]
void QPolygon::setPoint (int index, int x, int y) inline
Sets the point at the given index to the point specified by ({x}, {y}).
See also
point(), putPoints(), setPoints(),
Definition at line 120 of file qpolygon.h.
Referenced by addPoint(), QWindowsStyle::drawComplexControl(), QCommonStyle::drawControl(), QCommonStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), putPoints(), qDrawPlainRect(), rot(), and setPoints().
 { (*this)[index] = QPoint(x, y); }
setPoint() [2/2]
void QPolygon::setPoint (int index, const QPoint & point) inline
Sets the point at the given index to the given point.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 117 of file qpolygon.h.
 { (*this)[index] = pt; }
setPoints() [1/2]
void QPolygon::setPoints (int nPoints, const int * points)
Resizes the polygon to nPoints and populates it with the given points.
The example code creates a polygon with two points (10, 20) and (30, 40):
        static const int points[] = { 10, 20, 30, 40 };
        QPolygon polygon;
        polygon.setPoints(2, points);
See also
setPoint() putPoints()
Definition at line 350 of file qpolygon.cpp.
Referenced by QWindowsCEStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QMotifStyle::drawControl(), QCommonStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMatrix::mapToPolygon(), QTransform::mapToPolygon(), QColorLuminancePicker::paintEvent(), qDrawPlainRect(), qDrawShadeLine(), and QPolygon().
 {
     resize(nPoints);
     int i = 0;
     while (nPoints--) {
         setPoint(i++, *points, *(points+1));
         points += 2;
     }
 }
setPoints() [2/2]
void QPolygon::setPoints (int nPoints, int firstx, int firsty, ...)
Resizes the polygon to nPoints and populates it with the points specified by the variable argument list.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The points are given as a sequence of integers, starting with firstx then firsty, and so on.
The example code creates a polygon with two points (10, 20) and (30, 40):
        QPolygon polygon;
        polygon.setPoints(2, 10, 20, 30, 40);
Definition at line 377 of file qpolygon.cpp.
 {
     va_list ap;
     resize(nPoints);
     setPoint(0, firstx, firsty);
     int i = 0, x, y;
     va_start(ap, firsty);
     while (--nPoints) {
         x = va_arg(ap, int);
         y = va_arg(ap, int);
         setPoint(++i, x, y);
     }
     va_end(ap);
 }
subtracted()
QPolygon QPolygon::subtracted (const QPolygon & r) const
Returns a polygon which is r subtracted from this polygon.
Since
4.3
Set operations on polygons will treat the polygons as areas. Non-closed polygons will be treated as implicitly closed.
Definition at line 1053 of file qpolygon.cpp.
Referenced by QPolygonF::isClosed().
 {
     QPainterPath subject; subject.addPolygon(*this);
     QPainterPath clip; clip.addPolygon(r);
     return subject.subtracted(clip).toFillPolygon().toPolygon();
 }
swap()
void QPolygon::swap (QPolygon & other) inline
Swaps polygon other with this polygon.
Since
4.8
This operation is very fast and never fails.
Definition at line 70 of file qpolygon.h.
 { QVector<QPoint>::swap(other); } // prevent QVector<QPoint><->QPolygon swaps
translate() [1/2]
void QPolygon::translate (int dx, int dy)
Translates all points in the polygon by ({dx}, {dy}).
See also
translated()
Definition at line 238 of file qpolygon.cpp.
Referenced by QCommonStyle::drawControl(), QCommonStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), qDrawPlainRect(), QPolygonF::swap(), translate(), and translated().
 {
     if (dx == 0 && dy == 0)
         return;
     register QPoint *p = data();
     register int i = size();
     QPoint pt(dx, dy);
     while (i--) {
         *p += pt;
         ++p;
     }
 }
translate() [2/2]
void QPolygon::translate (const QPoint & offset) inline
Translates all points in the polygon by the given offset.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
translated()
Definition at line 126 of file qpolygon.h.
 { translate(offset.x(), offset.y()); }
translated() [1/2]
QPolygon QPolygon::translated (int dx, int dy) const
Returns a copy of the polygon that is translated by ({dx}, {dy}).
Since
4.6
See also
translate()
Definition at line 270 of file qpolygon.cpp.
Referenced by QTransform::map(), QPolygonF::swap(), and translated().
 {
     QPolygon copy(*this);
     copy.translate(dx, dy);
     return copy;
 }
translated() [2/2]
QPolygon QPolygon::translated (const QPoint & offset) const inline
Returns a copy of the polygon that is translated by the given offset.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.6
See also
translate()
Definition at line 129 of file qpolygon.h.
 { return translated(offset.x(), offset.y()); }
united()
QPolygon QPolygon::united (const QPolygon & r) const
Returns a polygon which is the union of this polygon and r.
Since
4.3
Set operations on polygons, will treat the polygons as areas, and implicitly close the polygon.
See also
intersected(), subtracted()
Definition at line 1012 of file qpolygon.cpp.
Referenced by QPolygonF::isClosed().
 {
     QPainterPath subject; subject.addPolygon(*this);
     QPainterPath clip; clip.addPolygon(r);
     return subject.united(clip).toFillPolygon().toPolygon();
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & stream, const QPolygon & polygon) related
Writes the given polygon to the given stream, and returns a reference to the stream.
Since
4.4
See also
{Serializing Qt Data Types}
Definition at line 828 of file qpolygon.cpp.
Referenced by QPolygon().
 {
     const QVector<QPoint> &v = a;
     return s << v;
 }
operator>>()
QDataStream & operator>> (QDataStream & stream, QPolygon & polygon) related
Reads a polygon from the given stream into the given polygon, and returns a reference to the stream.
Since
4.4
See also
{Serializing Qt Data Types}
Definition at line 847 of file qpolygon.cpp.
Referenced by QPolygon().
 {
     QVector<QPoint> &v = a;
     return s >> v;
 }
The documentation for this class was generated from the following files:
/src/gui/painting/qpolygon.h
/src/gui/painting/qpolygon.cpp