Qt 4.8: QHostInfoAgent Class Reference
QHostInfoAgent Class Reference
#include <qhostinfo_p.h>
Static Public Functions
static QHostInfo fromName (const QString &hostName)
static QHostInfo fromName (const QString &hostName, QSharedPointer< QNetworkSession > networkSession)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 99 of file qhostinfo_p.h.
Functions
fromName() [1/2]
QHostInfo QHostInfoAgent::fromName (const QString & hostName) static
Definition at line 124 of file qhostinfo_unix.cpp.
Referenced by QHostInfo::fromName(), fromName(), QHostInfoPrivate::fromName(), QHostInfoRunnable::run(), and translateWSAError().
 {
     QHostInfo results;
 #if defined(QHOSTINFO_DEBUG)
     qDebug("QHostInfoAgent::fromName(%s) looking up...",
            hostName.toLatin1().constData());
 #endif
     // Load res_init on demand.
     static volatile bool triedResolve = false;
     if (!triedResolve) {
         QMutexLocker locker(QMutexPool::globalInstanceGet(&local_res_init));
         if (!triedResolve) {
             resolveLibrary();
             triedResolve = true;
         }
     }
     // If res_init is available, poll it.
     if (local_res_init)
         local_res_init();
     QHostAddress address;
     if (address.setAddress(hostName)) {
         // Reverse lookup
 // Reverse lookups using getnameinfo are broken on darwin, use gethostbyaddr instead.
 #if !defined (QT_NO_GETADDRINFO) && !defined (Q_OS_DARWIN)
         sockaddr_in sa4;
 #ifndef QT_NO_IPV6
         sockaddr_in6 sa6;
 #endif
         sockaddr *sa = 0;
         QT_SOCKLEN_T saSize = 0;
         if (address.protocol() == QAbstractSocket::IPv4Protocol) {
             sa = (sockaddr *)&sa4;
             saSize = sizeof(sa4);
             memset(&sa4, 0, sizeof(sa4));
             sa4.sin_family = AF_INET;
             sa4.sin_addr.s_addr = htonl(address.toIPv4Address());
         }
 #ifndef QT_NO_IPV6
         else {
             sa = (sockaddr *)&sa6;
             saSize = sizeof(sa6);
             memset(&sa6, 0, sizeof(sa6));
             sa6.sin6_family = AF_INET6;
             memcpy(sa6.sin6_addr.s6_addr, address.toIPv6Address().c, sizeof(sa6.sin6_addr.s6_addr));
         }
 #endif
         char hbuf[NI_MAXHOST];
         if (sa && getnameinfo(sa, saSize, hbuf, sizeof(hbuf), 0, 0, 0) == 0)
             results.setHostName(QString::fromLatin1(hbuf));
 #else
         in_addr_t inetaddr = qt_safe_inet_addr(hostName.toLatin1().constData());
         struct hostent *ent = gethostbyaddr((const char *)&inetaddr, sizeof(inetaddr), AF_INET);
         if (ent)
             results.setHostName(QString::fromLatin1(ent->h_name));
 #endif
         if (results.hostName().isEmpty())
             results.setHostName(address.toString());
         results.setAddresses(QList<QHostAddress>() << address);
         return results;
     }
     // IDN support
     QByteArray aceHostname = QUrl::toAce(hostName);
     results.setHostName(hostName);
     if (aceHostname.isEmpty()) {
         results.setError(QHostInfo::HostNotFound);
         results.setErrorString(hostName.isEmpty() ?
                                QCoreApplication::translate("QHostInfoAgent", "No host name given") :
                                QCoreApplication::translate("QHostInfoAgent", "Invalid hostname"));
         return results;
     }
 #if !defined (QT_NO_GETADDRINFO)
     // Call getaddrinfo, and place all IPv4 addresses at the start and
     // the IPv6 addresses at the end of the address list in results.
     addrinfo *res = 0;
     struct addrinfo hints;
     memset(&hints, 0, sizeof(hints));
     hints.ai_family = PF_UNSPEC;
 #ifdef Q_ADDRCONFIG
     hints.ai_flags = Q_ADDRCONFIG;
 #endif
     int result = getaddrinfo(aceHostname.constData(), 0, &hints, &res);
 # ifdef Q_ADDRCONFIG
     if (result == EAI_BADFLAGS) {
         // if the lookup failed with AI_ADDRCONFIG set, try again without it
         hints.ai_flags = 0;
         result = getaddrinfo(aceHostname.constData(), 0, &hints, &res);
     }
 # endif
     if (result == 0) {
         addrinfo *node = res;
         QList<QHostAddress> addresses;
         while (node) {
 #ifdef QHOSTINFO_DEBUG
                 qDebug() << "getaddrinfo node: flags:" << node->ai_flags << "family:" << node->ai_family << "ai_socktype:" << node->ai_socktype << "ai_protocol:" << node->ai_protocol << "ai_addrlen:" << node->ai_addrlen;
 #endif
             if (node->ai_family == AF_INET) {
                 QHostAddress addr;
                 addr.setAddress(ntohl(((sockaddr_in *) node->ai_addr)->sin_addr.s_addr));
                 if (!addresses.contains(addr))
                     addresses.append(addr);
             }
 #ifndef QT_NO_IPV6
             else if (node->ai_family == AF_INET6) {
                 QHostAddress addr;
                 sockaddr_in6 *sa6 = (sockaddr_in6 *) node->ai_addr;
                 addr.setAddress(sa6->sin6_addr.s6_addr);
                 if (sa6->sin6_scope_id)
                     addr.setScopeId(QString::number(sa6->sin6_scope_id));
                 if (!addresses.contains(addr))
                     addresses.append(addr);
             }
 #endif
             node = node->ai_next;
         }
         if (addresses.isEmpty() && node == 0) {
             // Reached the end of the list, but no addresses were found; this
             // means the list contains one or more unknown address types.
             results.setError(QHostInfo::UnknownError);
             results.setErrorString(tr("Unknown address type"));
         }
         results.setAddresses(addresses);
         freeaddrinfo(res);
     } else if (result == EAI_NONAME
                || result ==  EAI_FAIL
 #ifdef EAI_NODATA
            // EAI_NODATA is deprecated in RFC 3493
            || result == EAI_NODATA
 #endif
            ) {
         results.setError(QHostInfo::HostNotFound);
         results.setErrorString(tr("Host not found"));
     } else {
         results.setError(QHostInfo::UnknownError);
         results.setErrorString(QString::fromLocal8Bit(gai_strerror(result)));
     }
 #else
     // Fall back to gethostbyname for platforms that don't define
     // getaddrinfo. gethostbyname does not support IPv6, and it's not
     // reentrant on all platforms. For now this is okay since we only
     // use one QHostInfoAgent, but if more agents are introduced, locking
     // must be provided.
     QMutexLocker locker(::getHostByNameMutex());
     hostent *result = gethostbyname(aceHostname.constData());
     if (result) {
         if (result->h_addrtype == AF_INET) {
             QList<QHostAddress> addresses;
             for (char **p = result->h_addr_list; *p != 0; p++) {
                 QHostAddress addr;
                 addr.setAddress(ntohl(*((quint32 *)*p)));
                 if (!addresses.contains(addr))
                     addresses.prepend(addr);
             }
             results.setAddresses(addresses);
         } else {
             results.setError(QHostInfo::UnknownError);
             results.setErrorString(tr("Unknown address type"));
         }
 #if !defined(Q_OS_VXWORKS)
     } else if (h_errno == HOST_NOT_FOUND || h_errno == NO_DATA
                || h_errno == NO_ADDRESS) {
         results.setError(QHostInfo::HostNotFound);
         results.setErrorString(tr("Host not found"));
 #endif
     } else {
         results.setError(QHostInfo::UnknownError);
         results.setErrorString(tr("Unknown error"));
     }
 #endif //  !defined (QT_NO_GETADDRINFO)
 #if defined(QHOSTINFO_DEBUG)
     if (results.error() != QHostInfo::NoError) {
         qDebug("QHostInfoAgent::fromName(): error #%d %s",
                h_errno, results.errorString().toLatin1().constData());
     } else {
         QString tmp;
         QList<QHostAddress> addresses = results.addresses();
         for (int i = 0; i < addresses.count(); ++i) {
             if (i != 0) tmp += ", ";
             tmp += addresses.at(i).toString();
         }
         qDebug("QHostInfoAgent::fromName(): found %i entries for \"%s\": {%s}",
                addresses.count(), hostName.toLatin1().constData(),
                tmp.toLatin1().constData());
     }
 #endif
     return results;
 }
fromName() [2/2]
QHostInfo QHostInfoAgent::fromName (const QString & hostName, QSharedPointer< QNetworkSession > networkSession) static
Definition at line 302 of file qhostinfo.cpp.
 {
     return QHostInfoAgent::fromName(hostName);
 }
The documentation for this class was generated from the following files:
/src/network/kernel/qhostinfo_p.h
/src/network/kernel/qhostinfo.cpp
/src/network/kernel/qhostinfo_unix.cpp
/src/network/kernel/qhostinfo_win.cpp