Qt 4.8: QTestTable Class Reference
QTestTable Class Reference
#include <qtesttable_p.h>
Public Functions
void addColumn (int elementType, const char *elementName)
int dataCount () const
const char * dataTag (int index) const
int elementCount () const
int elementTypeId (int index) const
int indexOf (const char *elementName) const
bool isEmpty () const
QTestData * newData (const char *tag)
QTestTable ()
QTestData * testData (int index) const
~QTestTable ()
Static Public Functions
static void clearGlobalTestTable ()
static QTestTable * currentTestTable ()
static QTestTable * globalTestTable ()
Properties
QTestTablePrivate * d
Detailed Description
Definition at line 63 of file qtesttable_p.h.
Constructors and Destructors
QTestTable()
QTestTable::QTestTable ()
Definition at line 200 of file qtesttable.cpp.
 {
     d = new QTestTablePrivate;
     QTestTablePrivate::currentTestTable = this;
 }
~QTestTable()
QTestTable::~QTestTable ()
Definition at line 206 of file qtesttable.cpp.
 {
     QTestTablePrivate::currentTestTable = 0;
     delete d;
 }
Functions
addColumn()
void QTestTable::addColumn (int elementType, const char * elementName)
Definition at line 157 of file qtesttable.cpp.
Referenced by QTest::addColumnInternal().
 {
     QTEST_ASSERT(type);
     QTEST_ASSERT(name);
     d->append(type, name);
 }
clearGlobalTestTable()
void QTestTable::clearGlobalTestTable () static
Definition at line 255 of file qtesttable.cpp.
Referenced by QTest::qInvokeTestMethods().
 {
     delete QTestTablePrivate::gTable;
     QTestTablePrivate::gTable = 0;
 }
currentTestTable()
QTestTable * QTestTable::currentTestTable () static
Definition at line 261 of file qtesttable.cpp.
Referenced by QTest::addColumnInternal(), and QTest::newRow().
 {
     return QTestTablePrivate::currentTestTable;
 }
dataCount()
int QTestTable::dataCount () const
Definition at line 177 of file qtesttable.cpp.
Referenced by QTest::qInvokeTestMethod(), and QTest::qPrintDataTags().
 {
     QTestTablePrivate::DataList *item = d->dataList;
     int count = 0;
     while (item) {
         ++count;
         item = item->next;
     }
     return count;
 }
dataTag()
const char * QTestTable::dataTag (int index) const
Definition at line 220 of file qtesttable.cpp.
 {
     QTestTablePrivate::ElementList *item = d->elementAt(index);
     if (!item)
         return 0;
     return item->elementName;
 }
elementCount()
int QTestTable::elementCount () const
Definition at line 165 of file qtesttable.cpp.
Referenced by QTestData::data(), and QTestData::QTestData().
 {
     QTestTablePrivate::ElementList *item = d->list;
     int count = 0;
     while (item) {
         ++count;
         item = item->next;
     }
     return count;
 }
elementTypeId()
int QTestTable::elementTypeId (int index) const
Definition at line 212 of file qtesttable.cpp.
Referenced by QTest::fetchData(), and QTest::qElementData().
 {
     QTestTablePrivate::ElementList *item = d->elementAt(index);
     if (!item)
         return -1;
     return item->elementType;
 }
globalTestTable()
QTestTable * QTestTable::globalTestTable () static
Definition at line 248 of file qtesttable.cpp.
Referenced by QTest::qInvokeTestMethod(), QTest::qInvokeTestMethods(), and QTest::qPrintDataTags().
 {
     if (!QTestTablePrivate::gTable)
         QTestTablePrivate::gTable = new QTestTable();
     return QTestTablePrivate::gTable;
 }
indexOf()
int QTestTable::indexOf (const char * elementName) const
Definition at line 233 of file qtesttable.cpp.
Referenced by QTest::fetchData(), and QTest::qElementData().
 {
     QTEST_ASSERT(elementName);
     QTestTablePrivate::ElementList *item = d->list;
     int i = 0;
     while (item) {
         if (strcmp(elementName, item->elementName) == 0)
             return i;
         item = item->next;
         ++i;
     }
     return -1;
 }
isEmpty()
bool QTestTable::isEmpty () const
Definition at line 188 of file qtesttable.cpp.
Referenced by QTest::qInvokeTestMethod().
 {
     return !d->list;
 }
newData()
QTestData * QTestTable::newData (const char * tag)
Definition at line 193 of file qtesttable.cpp.
Referenced by QTest::newRow().
 {
     QTestData *dt = new QTestData(tag, this);
     d->append(dt);
     return dt;
 }
testData()
QTestData * QTestTable::testData (int index) const
Definition at line 228 of file qtesttable.cpp.
Referenced by QTest::qInvokeTestMethod(), and QTest::qPrintDataTags().
 {
     return d->dataAt(index);
 }
Properties
d
QTestTablePrivate* QTestTable::d private
Definition at line 88 of file qtesttable_p.h.
The documentation for this class was generated from the following files:
/src/testlib/qtesttable_p.h
/src/testlib/qtesttable.cpp