Qt 4.8: QPatternist::XsdAnnotated Class Reference
QPatternist::XsdAnnotated Class Reference
XML Schema Processing
Base class for all XSD components with annotation content.
#include <qxsdannotated_p.h>
Public Functions
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Properties
XsdAnnotation::List m_annotations
Detailed Description
Base class for all XSD components with annotation content.
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 69 of file qxsdannotated_p.h.
Functions
addAnnotation()
void XsdAnnotated::addAnnotation (const XsdAnnotation::Ptr & annotation)
Adds a new annotation to the component.
Definition at line 48 of file qxsdannotated.cpp.
Referenced by QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseChoice(), QPatternist::XsdSchemaParser::parseComplexContent(), QPatternist::XsdSchemaParser::parseComplexContentExtension(), QPatternist::XsdSchemaParser::parseComplexContentRestriction(), QPatternist::XsdSchemaParser::parseField(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseGlobalSimpleType(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseKey(), QPatternist::XsdSchemaParser::parseKeyRef(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseLocalSequence(), QPatternist::XsdSchemaParser::parseLocalSimpleType(), QPatternist::XsdSchemaParser::parseNamedAttributeGroup(), QPatternist::XsdSchemaParser::parseNamedGroup(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseSchema(), QPatternist::XsdSchemaParser::parseSelector(), QPatternist::XsdSchemaParser::parseSequence(), QPatternist::XsdSchemaParser::parseSimpleContent(), QPatternist::XsdSchemaParser::parseSimpleContentExtension(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseUnion(), and QPatternist::XsdSchemaParser::parseUnique().
 {
     m_annotations.append(annotation);
 }
addAnnotations()
void XsdAnnotated::addAnnotations (const XsdAnnotation::List & annotations)
Adds a list of new annotations to the component.
Definition at line 53 of file qxsdannotated.cpp.
 {
     m_annotations << annotations;
 }
annotations()
XsdAnnotation::List XsdAnnotated::annotations () const
Returns the list of all annotations of the component.
Definition at line 58 of file qxsdannotated.cpp.
Referenced by addAnnotations().
 {
     return m_annotations;
 }
Properties
m_annotations
XsdAnnotation::List QPatternist::XsdAnnotated::m_annotations private
Definition at line 88 of file qxsdannotated_p.h.
Referenced by addAnnotation(), addAnnotations(), and annotations().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdannotated_p.h
/src/xmlpatterns/schema/qxsdannotated.cpp