Qt 4.8: QDeclarativeGlobalScriptClass Class Reference
QDeclarativeGlobalScriptClass Class Reference
#include <qdeclarativeglobalscriptclass_p.h>
Public Functions
void explicitSetProperty (const QStringList &, const QList< QScriptValue > &)
const QSet< QString > & illegalNames () const
QDeclarativeGlobalScriptClass (QScriptEngine *)
virtual QueryFlags queryProperty (const QScriptValue &object, const QScriptString &name, QueryFlags flags, uint *id)
Queries this script class for how access to the property with the given name of the given object should be handled.
virtual void setProperty (QScriptValue &object, const QScriptString &name, uint id, const QScriptValue &value)
Sets the property with the given name of the given object to the given value.
const QScriptValue & staticGlobalObject () const
Public Functions inherited from QScriptClass
QScriptEngine * engine () const
Returns the engine that this QScriptClass is associated with.
virtual QVariant extension (Extension extension, const QVariant &argument=QVariant())
This virtual function can be reimplemented in a QScriptClass subclass to provide support for extensions.
virtual QString name () const
Returns the name of the script class.
virtual QScriptClassPropertyIterator * newIterator (const QScriptValue &object)
Returns an iterator for traversing custom properties of the given object.
virtual QScriptValue property (const QScriptValue &object, const QScriptString &name, uint id)
Returns the value of the property with the given name of the given object.
virtual QScriptValue::PropertyFlags propertyFlags (const QScriptValue &object, const QScriptString &name, uint id)
Returns the flags of the property with the given name of the given object.
virtual QScriptValue prototype () const
Returns the object to be used as the prototype of new instances of this class (created with QScriptEngine::newObject()).
QScriptClass (QScriptEngine *engine)
Constructs a QScriptClass object to be used in the given engine.
virtual bool supportsExtension (Extension extension) const
Returns true if the QScriptClass supports the given extension; otherwise, false is returned.
virtual ~QScriptClass ()
Destroys the QScriptClass object.
Properties
QSet< QString > m_illegalNames
QScriptValue m_staticGlobalObject
Additional Inherited Members
Public Types inherited from QScriptClass
enum Extension { Callable, HasInstance }
This enum specifies the possible extensions to a QScriptClass.
enum QueryFlag { HandlesReadAccess = 0x01, HandlesWriteAccess = 0x02 }
This enum describes flags that are used to query a QScriptClass regarding how access to a property should be handled.
Protected Functions inherited from QScriptClass
QScriptClass (QScriptEngine *engine, QScriptClassPrivate &dd)
Protected Variables inherited from QScriptClass
QScopedPointer< QScriptClassPrivate > d_ptr
Detailed Description
Definition at line 61 of file qdeclarativeglobalscriptclass_p.h.
Constructors and Destructors
QDeclarativeGlobalScriptClass()
QDeclarativeGlobalScriptClass::QDeclarativeGlobalScriptClass (QScriptEngine * engine)
Definition at line 57 of file qdeclarativeglobalscriptclass.cpp.
 : QScriptClass(engine)
 {
     QString eval = QLatin1String("eval");
     QString version = QLatin1String("version");
     QScriptValue originalGlobalObject = engine->globalObject();
     QScriptValue newGlobalObject = engine->newObject();
     {
         QScriptValueIterator iter(originalGlobalObject);
         QVector<QString> names;
         QVector<QScriptValue> values;
         QVector<QScriptValue::PropertyFlags> flags;
         while (iter.hasNext()) {
             iter.next();
             QString name = iter.name();
             if (name == version)
                 continue;
             if (name != eval) {
                 names.append(name);
                 values.append(iter.value());
                 flags.append(iter.flags() | QScriptValue::Undeletable);
             }
             newGlobalObject.setProperty(iter.scriptName(), iter.value());
             m_illegalNames.insert(name);
         }
         m_staticGlobalObject = QScriptDeclarativeClass::newStaticScopeObject(
             engine, names.size(), names.constData(), values.constData(), flags.constData());
     }
     newGlobalObject.setScriptClass(this);
     engine->setGlobalObject(newGlobalObject);
 }
Functions
explicitSetProperty()
void QDeclarativeGlobalScriptClass::explicitSetProperty (const QStringList & names, const QList< QScriptValue > & values)
Definition at line 122 of file qdeclarativeglobalscriptclass.cpp.
 {
     Q_ASSERT(names.count() == values.count());
     QScriptValue globalObject = engine()->globalObject();
     QScriptValue v = engine()->newObject();
     QScriptValueIterator iter(v);
     while (iter.hasNext()) {
         iter.next();
         v.setProperty(iter.scriptName(), iter.value());
     }
     for (int ii = 0; ii < names.count(); ++ii) {
         const QString &name = names.at(ii);
         const QScriptValue &value = values.at(ii);
         v.setProperty(name, value);
     }
     v.setScriptClass(this);
     engine()->setGlobalObject(v);
 }
illegalNames()
const QSet<QString>& QDeclarativeGlobalScriptClass::illegalNames () const inline
Definition at line 77 of file qdeclarativeglobalscriptclass_p.h.
Referenced by QDeclarativeCompiler::checkDynamicMeta(), and QDeclarativeCompiler::checkValidId().
 { return m_illegalNames; }
queryProperty()
QScriptClass::QueryFlags QDeclarativeGlobalScriptClass::queryProperty (const QScriptValue & object, const QScriptString & name, QueryFlags flags, uint * id) virtual
Queries this script class for how access to the property with the given name of the given object should be handled.
The given flags specify the aspects of interest. This function should return a subset of flags to indicate which aspects of property access should be further handled by the script class.
For example, if the flags contain HandlesReadAccess, and you would like your class to handle the reading of the property (through the property() function), the returned flags should include HandlesReadAccess. If the returned flags do not contain HandlesReadAccess, the property will be handled as a normal script object property.
You can optionally use the id argument to store a value that will subsequently be passed on to functions such as property() and setProperty().
The default implementation of this function returns 0.
Note: This function is only called if the given property isn't already a normal property of the object. For example, say you advertise that you want to handle read access to property foo, but not write access; if foo is then assigned a value, it will become a normal script object property, and subsequently you will no longer be queried regarding read access to foo.
See also
property()
Reimplemented from QScriptClass.
Definition at line 98 of file qdeclarativeglobalscriptclass.cpp.
 {
     Q_UNUSED(object);
     Q_UNUSED(name);
     Q_UNUSED(flags);
     Q_UNUSED(id);
     return HandlesWriteAccess;
 }
setProperty()
void QDeclarativeGlobalScriptClass::setProperty (QScriptValue & object, const QScriptString & name, uint id, const QScriptValue & value) virtual
Sets the property with the given name of the given object to the given value.
The id argument is only useful if you assigned a value to it in queryProperty().
The default implementation does nothing.
An invalid value represents a request to remove the property.
See also
property()
Reimplemented from QScriptClass.
Definition at line 109 of file qdeclarativeglobalscriptclass.cpp.
 {
     Q_UNUSED(object);
     Q_UNUSED(id);
     Q_UNUSED(value);
     QString error = QLatin1String("Invalid write to global property \"") +
                     name.toString() + QLatin1Char('\"');
     engine()->currentContext()->throwError(error);
 }
staticGlobalObject()
const QScriptValue& QDeclarativeGlobalScriptClass::staticGlobalObject () const inline
Definition at line 75 of file qdeclarativeglobalscriptclass_p.h.
Referenced by QDeclarativeContextData::addImportedScript(), QDeclarativeExpressionPrivate::evalInObjectScope(), QDeclarativeInclude::include(), QDeclarativeExpressionPrivate::init(), and QDeclarativeExpressionPrivate::scriptValue().
 { return m_staticGlobalObject; }
Properties
m_illegalNames
QSet<QString> QDeclarativeGlobalScriptClass::m_illegalNames private
Definition at line 80 of file qdeclarativeglobalscriptclass_p.h.
Referenced by QDeclarativeGlobalScriptClass().
m_staticGlobalObject
QScriptValue QDeclarativeGlobalScriptClass::m_staticGlobalObject private
Definition at line 81 of file qdeclarativeglobalscriptclass_p.h.
Referenced by QDeclarativeGlobalScriptClass().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeglobalscriptclass_p.h
/src/declarative/qml/qdeclarativeglobalscriptclass.cpp