Qt 4.8: QDockWidgetLayout Class Reference
QDockWidgetLayout Class Reference
#include <qdockwidget_p.h>
Public Types
enum Role {
Content, CloseButton, FloatButton, TitleBar,
RoleCount
}
Public Types inherited from QLayout
enum SizeConstraint {
SetDefaultConstraint, SetNoConstraint, SetMinimumSize, SetFixedSize,
SetMaximumSize, SetMinAndMaxSize
}
The possible values are:
Public Functions
void addItem (QLayoutItem *item)
Implemented in subclasses to add an item.
int count () const
Must be implemented in subclasses to return the number of items in the layout.
QLayoutItem * itemAt (int index) const
Must be implemented in subclasses to return the layout item at index.
QLayoutItem * itemForRole (Role r) const
QSize maximumSize () const
Returns the maximum size of this layout.
QSize minimumSize () const
Returns the minimum size of this layout.
int minimumTitleWidth () const
bool nativeWindowDeco () const
bool nativeWindowDeco (bool floating) const
QDockWidgetLayout (QWidget *parent=0)
void setGeometry (const QRect &r)
Reimplemented Function
void setVerticalTitleBar (bool b)
void setWidgetForRole (Role r, QWidget *w)
QSize sizeFromContent (const QSize &content, bool floating) const
QSize sizeHint () const
Implemented in subclasses to return the preferred size of this item.
QLayoutItem * takeAt (int index)
Must be implemented in subclasses to remove the layout item at index from the layout, and return the item.
QRect titleArea () const
int titleHeight () const
void updateMaxSize ()
QWidget * widgetForRole (Role r) const
~QDockWidgetLayout ()
Public Functions inherited from QLayout
bool activate ()
Redoes the layout for parentWidget() if necessary.
void addWidget (QWidget *w)
Adds widget w to this layout in a manner specific to the layout.
QMargins contentsMargins () const
Returns the margins used around the layout.
QRect contentsRect () const
Returns the layout's geometry() rectangle, but taking into account the contents margins.
Qt::Orientations expandingDirections () const
Returns whether this layout can make use of more space than sizeHint().
QRect geometry () const
Reimplemented Function
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
virtual int indexOf (QWidget *) const
Searches for widget widget in this layout (not including child layouts).
void invalidate ()
Reimplemented Function
bool isEmpty () const
Reimplemented Function
bool isEnabled () const
Returns true if the layout is enabled; otherwise returns false.
QLayout * layout ()
Reimplemented Function
int margin () const
QWidget * menuBar () const
Returns the menu bar set for this layout, or 0 if no menu bar is set.
QWidget * parentWidget () const
Returns the parent widget of this layout, or 0 if this layout is not installed on any widget.
QLayout (QWidget *parent)
Constructs a new top-level QLayout, with parent parent.
QLayout ()
Constructs a new child QLayout.
void removeItem (QLayoutItem *)
Removes the layout item item from the layout.
void removeWidget (QWidget *w)
Removes the widget widget from the layout.
bool setAlignment (QWidget *w, Qt::Alignment alignment)
Sets the alignment for widget w to alignment and returns true if w is found in this layout (not including child layouts); otherwise returns false.
bool setAlignment (QLayout *l, Qt::Alignment alignment)
Sets the alignment for the layout l to alignment and returns true if l is found in this layout (not including child layouts); otherwise returns false.
void setContentsMargins (int left, int top, int right, int bottom)
Sets the left, top, right, and bottom margins to use around the layout.
void setContentsMargins (const QMargins &margins)
Sets the margins to use around the layout.
void setEnabled (bool)
Enables this layout if enable is true, otherwise disables it.
void setMargin (int)
void setMenuBar (QWidget *w)
Tells the geometry manager to place the menu bar widget at the top of parentWidget(), outside QWidget::contentsMargins().
void setSizeConstraint (SizeConstraint)
void setSpacing (int)
SizeConstraint sizeConstraint () const
int spacing () const
int totalHeightForWidth (int w) const
Also takes contentsMargins and menu bar into account.
QSize totalMaximumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalMinimumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalSizeHint () const
Also takes contentsMargins and menu bar into account.
void update ()
Updates the layout for parentWidget().
~QLayout ()
Destroys the layout, deleting all child layouts.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QLayoutItem
Qt::Alignment alignment () const
Returns the alignment of this item.
QSizePolicy::ControlTypes controlTypes () const
Returns the control type(s) for the layout item.
virtual bool hasHeightForWidth () const
Returns true if this layout's preferred height depends on its width; otherwise returns false.
virtual int heightForWidth (int) const
Returns the preferred height for this layout item, given the width w.
virtual int minimumHeightForWidth (int) const
Returns the minimum height this widget needs for the given width, w.
QLayoutItem (Qt::Alignment alignment=0)
Constructs a layout item with an alignment.
void setAlignment (Qt::Alignment a)
Sets the alignment of this item to alignment.
virtual QSpacerItem * spacerItem ()
If this item is a QSpacerItem, it is returned as a QSpacerItem; otherwise 0 is returned.
virtual QWidget * widget ()
If this item is a QWidget, it is returned as a QWidget; otherwise 0 is returned.
virtual ~QLayoutItem ()
Destroys the QLayoutItem.
Public Variables
bool verticalTitleBar
Properties
QRect _titleArea
QVector< QLayoutItem * > item_list
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QLayout
static QSize closestAcceptableSize (const QWidget *w, const QSize &s)
Returns a size that satisfies all size constraints on widget, including heightForWidth() and that is as close as possible to size.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QLayout
void addChildLayout (QLayout *l)
This function is called from addLayout() or insertLayout() functions in subclasses to add layout l as a sub-layout.
void addChildWidget (QWidget *w)
This function is called from addWidget() functions in subclasses to add w as a managed widget of a layout.
bool adoptLayout (QLayout *layout)
QRect alignmentRect (const QRect &) const
Returns the rectangle that should be covered when the geometry of this layout is set to r, provided that this layout supports setAlignment().
void childEvent (QChildEvent *e)
Reimplemented Function
QLayout (QLayoutPrivate &d, QLayout *, QWidget *)
void widgetEvent (QEvent *)
Performs child widget layout when the parent widget is resized.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QLayoutItem
Qt::Alignment align
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 131 of file qdockwidget_p.h.
Enumerations
Role
enum QDockWidgetLayout::Role
Enumerator
Content
CloseButton
FloatButton
TitleBar
RoleCount
Definition at line 150 of file qdockwidget_p.h.
 { Content, CloseButton, FloatButton, TitleBar, RoleCount };
Constructors and Destructors
QDockWidgetLayout()
QDockWidgetLayout::QDockWidgetLayout (QWidget * parent = 0)
Definition at line 193 of file qdockwidget.cpp.
     : QLayout(parent), verticalTitleBar(false), item_list(RoleCount, 0)
 {
 }
~QDockWidgetLayout()
QDockWidgetLayout::~QDockWidgetLayout ()
Definition at line 198 of file qdockwidget.cpp.
 {
     qDeleteAll(item_list);
 }
Functions
addItem()
void QDockWidgetLayout::addItem (QLayoutItem * item) virtual
Implemented in subclasses to add an item.
How it is added is specific to each subclass.
This function is not usually called in application code. To add a widget to a layout, use the addWidget() function; to add a child layout, use the addLayout() function provided by the relevant QLayout subclass.
Note: The ownership of item is transferred to the layout, and it's the layout's responsibility to delete it.
See also
addWidget(), QBoxLayout::addLayout(), QGridLayout::addLayout()
Implements QLayout.
Definition at line 219 of file qdockwidget.cpp.
 {
     qWarning() << "QDockWidgetLayout::addItem(): please use QDockWidgetLayout::setWidget()";
     return;
 }
count()
int QDockWidgetLayout::count () const virtual
Must be implemented in subclasses to return the number of items in the layout.
See also
itemAt()
Implements QLayout.
Definition at line 255 of file qdockwidget.cpp.
 {
     int result = 0;
     for (int i = 0; i < item_list.count(); ++i) {
         if (item_list.at(i))
             ++result;
     }
     return result;
 }
itemAt()
QLayoutItem * QDockWidgetLayout::itemAt (int index) const virtual
Must be implemented in subclasses to return the layout item at index.
If there is no such item, the function must return 0. Items are numbered consecutively from 0. If an item is deleted, other items will be renumbered.
This function can be used to iterate over a layout. The following code will draw a rectangle for each layout item in the layout structure of the widget.
static void paintLayout(QPainter *painter, QLayoutItem *item)
{
    QLayout *layout = item->layout();
    if (layout) {
        for (int i = 0; i < layout->count(); ++i)
            paintLayout(painter, layout->itemAt(i));
    }
    painter->drawRect(item->geometry());
}
void MyWidget::paintEvent(QPaintEvent *)
{
    QPainter painter(this);
    if (layout())
        paintLayout(&painter, layout());
}
See also
count(), takeAt()
Implements QLayout.
Definition at line 225 of file qdockwidget.cpp.
 {
     int cnt = 0;
     for (int i = 0; i < item_list.count(); ++i) {
         QLayoutItem *item = item_list.at(i);
         if (item == 0)
             continue;
         if (index == cnt++)
             return item;
     }
     return 0;
 }
itemForRole()
QLayoutItem * QDockWidgetLayout::itemForRole (Role r) const
Definition at line 371 of file qdockwidget.cpp.
 {
     return item_list.at(r);
 }
maximumSize()
QSize QDockWidgetLayout::maximumSize () const virtual
Returns the maximum size of this layout.
This is the largest size that the layout can have while still respecting the specifications.
The returned value doesn't include the space required by QWidget::setContentsMargins() or menuBar().
The default implementation allows unlimited resizing.
Reimplemented from QLayout.
Definition at line 343 of file qdockwidget.cpp.
 {
     if (item_list[Content] != 0) {
         const QSize content = item_list[Content]->maximumSize();
         return sizeFromContent(content, parentWidget()->isWindow());
     } else {
         return parentWidget()->maximumSize();
     }
 }
minimumSize()
QSize QDockWidgetLayout::minimumSize () const virtual
Returns the minimum size of this layout.
This is the smallest size that the layout can have while still respecting the specifications.
The returned value doesn't include the space required by QWidget::setContentsMargins() or menuBar().
The default implementation allows unlimited resizing.
Reimplemented from QLayout.
Definition at line 354 of file qdockwidget.cpp.
 {
     QDockWidget *w = qobject_cast<QDockWidget*>(parentWidget());
     QSize content(0, 0);
     if (item_list[Content] != 0)
         content = item_list[Content]->minimumSize();
     return sizeFromContent(content, w->isFloating());
 }
minimumTitleWidth()
int QDockWidgetLayout::minimumTitleWidth () const
Definition at line 405 of file qdockwidget.cpp.
Referenced by sizeFromContent().
 {
     QDockWidget *q = qobject_cast<QDockWidget*>(parentWidget());
     if (QWidget *title = widgetForRole(TitleBar))
         return pick(verticalTitleBar, title->minimumSizeHint());
     QSize closeSize(0, 0);
     QSize floatSize(0, 0);
     if (hasFeature(q, QDockWidget::DockWidgetClosable)) {
         if (QLayoutItem *item = item_list[CloseButton])
             closeSize = item->widget()->sizeHint();
     }
     if (hasFeature(q, QDockWidget::DockWidgetFloatable)) {
         if (QLayoutItem *item = item_list[FloatButton])
             floatSize = item->widget()->sizeHint();
     }
     int titleHeight = this->titleHeight();
     int mw = q->style()->pixelMetric(QStyle::PM_DockWidgetTitleMargin, 0, q);
     int fw = q->style()->pixelMetric(QStyle::PM_DockWidgetFrameWidth, 0, q);
     return pick(verticalTitleBar, closeSize)
             + pick(verticalTitleBar, floatSize)
             + titleHeight + 2*fw + 3*mw;
 }
nativeWindowDeco() [1/2]
bool QDockWidgetLayout::nativeWindowDeco () const
Definition at line 203 of file qdockwidget.cpp.
Referenced by dockedGeometry(), QDockWidgetPrivate::mouseDoubleClickEvent(), QDockWidgetPrivate::mouseMoveEvent(), QDockWidgetPrivate::mousePressEvent(), QDockWidget::paintEvent(), QMainWindowLayout::plug(), QDockWidget::setFeatures(), setGeometry(), QDockWidgetPrivate::setWindowState(), sizeFromContent(), QDockWidgetPrivate::unplug(), and QDockWidgetPrivate::updateButtons().
 {
     return nativeWindowDeco(parentWidget()->isWindow());
 }
nativeWindowDeco() [2/2]
bool QDockWidgetLayout::nativeWindowDeco (bool floating) const
Definition at line 208 of file qdockwidget.cpp.
 {
 #if defined(Q_WS_X11) || defined(Q_WS_QWS) || defined(Q_WS_WINCE)
     Q_UNUSED(floating);
     return false;
 #else
     return floating && item_list[QDockWidgetLayout::TitleBar] == 0;
 #endif
 }
setGeometry()
void QDockWidgetLayout::setGeometry (const QRect & r) virtual
Reimplemented Function
Reimplemented from QLayout.
Definition at line 464 of file qdockwidget.cpp.
 {
     QDockWidget *q = qobject_cast<QDockWidget*>(parentWidget());
     bool nativeDeco = nativeWindowDeco();
     int fw = q->isFloating() && !nativeDeco
             ? q->style()->pixelMetric(QStyle::PM_DockWidgetFrameWidth, 0, q)
             : 0;
     if (nativeDeco) {
         if (QLayoutItem *item = item_list[Content])
             item->setGeometry(geometry);
     } else {
         int titleHeight = this->titleHeight();
         if (verticalTitleBar) {
             _titleArea = QRect(QPoint(fw, fw),
                                 QSize(titleHeight, geometry.height() - (fw * 2)));
         } else {
             _titleArea = QRect(QPoint(fw, fw),
                                 QSize(geometry.width() - (fw * 2), titleHeight));
         }
         if (QLayoutItem *item = item_list[TitleBar]) {
             item->setGeometry(_titleArea);
         } else {
             QStyleOptionDockWidgetV2 opt;
             q->initStyleOption(&opt);
             if (QLayoutItem *item = item_list[CloseButton]) {
                 if (!item->isEmpty()) {
                     QRect r = q->style()
                         ->subElementRect(QStyle::SE_DockWidgetCloseButton,
                                             &opt, q);
                     if (!r.isNull())
                         item->setGeometry(r);
                 }
             }
             if (QLayoutItem *item = item_list[FloatButton]) {
                 if (!item->isEmpty()) {
                     QRect r = q->style()
                         ->subElementRect(QStyle::SE_DockWidgetFloatButton,
                                             &opt, q);
                     if (!r.isNull())
                         item->setGeometry(r);
                 }
             }
         }
         if (QLayoutItem *item = item_list[Content]) {
             QRect r = geometry;
             if (verticalTitleBar) {
                 r.setLeft(_titleArea.right() + 1);
                 r.adjust(0, fw, -fw, -fw);
             } else {
                 r.setTop(_titleArea.bottom() + 1);
                 r.adjust(fw, 0, -fw, -fw);
             }
             item->setGeometry(r);
         }
     }
 }
setVerticalTitleBar()
void QDockWidgetLayout::setVerticalTitleBar (bool b)
Definition at line 529 of file qdockwidget.cpp.
Referenced by QDockWidget::setFeatures().
 {
     if (b == verticalTitleBar)
         return;
     verticalTitleBar = b;
     invalidate();
     parentWidget()->update();
 }
setWidgetForRole()
void QDockWidgetLayout::setWidgetForRole (Role r, QWidget * w)
Definition at line 376 of file qdockwidget.cpp.
Referenced by QDockWidgetPrivate::init(), QDockWidget::setTitleBarWidget(), and QDockWidget::setWidget().
 {
     QWidget *old = widgetForRole(r);
     if (old != 0) {
         old->hide();
         removeWidget(old);
     }
     if (w != 0) {
         addChildWidget(w);
         item_list[r] = new QWidgetItemV2(w);
         w->show();
     } else {
         item_list[r] = 0;
     }
     invalidate();
 }
sizeFromContent()
QSize QDockWidgetLayout::sizeFromContent (const QSize & content, bool floating) const
Definition at line 265 of file qdockwidget.cpp.
Referenced by maximumSize(), QDockWidgetItem::maximumSize(), minimumSize(), QDockWidgetItem::minimumSize(), sizeHint(), and QDockWidgetItem::sizeHint().
 {
     QSize result = content;
     if (verticalTitleBar) {
         result.setHeight(qMax(result.height(), minimumTitleWidth()));
         result.setWidth(qMax(content.width(), 0));
     } else {
         result.setHeight(qMax(result.height(), 0));
         result.setWidth(qMax(content.width(), minimumTitleWidth()));
     }
     QDockWidget *w = qobject_cast<QDockWidget*>(parentWidget());
     const bool nativeDeco = nativeWindowDeco(floating);
     int fw = floating && !nativeDeco
             ? w->style()->pixelMetric(QStyle::PM_DockWidgetFrameWidth, 0, w)
             : 0;
     const int th = titleHeight();
     if (!nativeDeco) {
         if (verticalTitleBar)
             result += QSize(th + 2*fw, 2*fw);
         else
             result += QSize(2*fw, th + 2*fw);
     }
     result.setHeight(qMin(result.height(), (int) QWIDGETSIZE_MAX));
     result.setWidth(qMin(result.width(), (int) QWIDGETSIZE_MAX));
     if (content.width() < 0)
         result.setWidth(-1);
     if (content.height() < 0)
         result.setHeight(-1);
     int left, top, right, bottom;
     w->getContentsMargins(&left, &top, &right, &bottom);
     //we need to substract the contents margin (it will be added by the caller)
     QSize min = w->minimumSize() - QSize(left + right, top + bottom);
     QSize max = w->maximumSize() - QSize(left + right, top + bottom);
     /* A floating dockwidget will automatically get its minimumSize set to the layout's
        minimum size + deco. We're *not* interested in this, we only take minimumSize()
        into account if the user set it herself. Otherwise we end up expanding the result
        of a calculation for a non-floating dock widget to a floating dock widget's
        minimum size + window decorations. */
     uint explicitMin = 0;
     uint explicitMax = 0;
     if (w->d_func()->extra != 0) {
         explicitMin = w->d_func()->extra->explicitMinSize;
         explicitMax = w->d_func()->extra->explicitMaxSize;
     }
     if (!(explicitMin & Qt::Horizontal) || min.width() == 0)
         min.setWidth(-1);
     if (!(explicitMin & Qt::Vertical) || min.height() == 0)
         min.setHeight(-1);
     if (!(explicitMax & Qt::Horizontal))
         max.setWidth(QWIDGETSIZE_MAX);
     if (!(explicitMax & Qt::Vertical))
         max.setHeight(QWIDGETSIZE_MAX);
     return result.boundedTo(max).expandedTo(min);
 }
sizeHint()
QSize QDockWidgetLayout::sizeHint () const virtual
Implemented in subclasses to return the preferred size of this item.
Implements QLayoutItem.
Definition at line 332 of file qdockwidget.cpp.
 {
     QDockWidget *w = qobject_cast<QDockWidget*>(parentWidget());
     QSize content(-1, -1);
     if (item_list[Content] != 0)
         content = item_list[Content]->sizeHint();
     return sizeFromContent(content, w->isFloating());
 }
takeAt()
QLayoutItem * QDockWidgetLayout::takeAt (int index) virtual
Must be implemented in subclasses to remove the layout item at index from the layout, and return the item.
If there is no such item, the function must do nothing and return 0. Items are numbered consecutively from 0. If an item is removed, other items will be renumbered.
The following code fragment shows a safe way to remove all items from a layout:
QLayoutItem *child;
while ((child = layout->takeAt(0)) != 0) {
    ...
    delete child;
}
See also
itemAt(), count()
Implements QLayout.
Definition at line 238 of file qdockwidget.cpp.
 {
     int j = 0;
     for (int i = 0; i < item_list.count(); ++i) {
         QLayoutItem *item = item_list.at(i);
         if (item == 0)
             continue;
         if (index == j) {
             item_list[i] = 0;
             invalidate();
             return item;
         }
         ++j;
     }
     return 0;
 }
titleArea()
QRect QDockWidgetLayout::titleArea () const inline
Definition at line 155 of file qdockwidget_p.h.
Referenced by QDockWidget::changeEvent(), QDockWidgetPrivate::initDrag(), QDockWidget::initStyleOption(), QDockWidgetPrivate::mouseDoubleClickEvent(), QDockWidgetPrivate::mousePressEvent(), QAccessibleDockWidget::rect(), and QAccessibleTitleBar::rect().
 { return _titleArea; }
titleHeight()
int QDockWidgetLayout::titleHeight () const
Definition at line 433 of file qdockwidget.cpp.
Referenced by dockedGeometry(), minimumTitleWidth(), QMainWindowLayout::plug(), setGeometry(), sizeFromContent(), and QDockWidgetPrivate::unplug().
 {
     QDockWidget *q = qobject_cast<QDockWidget*>(parentWidget());
     if (QWidget *title = widgetForRole(TitleBar))
         return perp(verticalTitleBar, title->sizeHint());
     QSize closeSize(0, 0);
     QSize floatSize(0, 0);
     if (QLayoutItem *item = item_list[CloseButton])
         closeSize = item->widget()->sizeHint();
     if (QLayoutItem *item = item_list[FloatButton])
         floatSize = item->widget()->sizeHint();
     int buttonHeight = qMax(perp(verticalTitleBar, closeSize),
                             perp(verticalTitleBar, floatSize));
     QFontMetrics titleFontMetrics = q->fontMetrics();
 #ifdef Q_WS_MAC
     if (qobject_cast<QMacStyle *>(q->style())) {
         //### this breaks on proxy styles.  (But is this code still called?)
         QFont font = qt_app_fonts_hash()->value("QToolButton", q->font());
         titleFontMetrics = QFontMetrics(font);
     }
 #endif
     int mw = q->style()->pixelMetric(QStyle::PM_DockWidgetTitleMargin, 0, q);
     return qMax(buttonHeight + 2, titleFontMetrics.height() + 2*mw);
 }
updateMaxSize()
void QDockWidgetLayout::updateMaxSize ()
widgetForRole()
QWidget * QDockWidgetLayout::widgetForRole (Role r) const
Definition at line 365 of file qdockwidget.cpp.
Referenced by QAccessibleTitleBar::childCount(), QAccessibleTitleBar::doAction(), QDockWidgetPrivate::endDrag(), minimumTitleWidth(), QAccessibleTitleBar::navigate(), QDockWidget::paintEvent(), QAccessibleTitleBar::rect(), setWidgetForRole(), QAccessibleTitleBar::state(), QDockWidget::titleBarWidget(), titleHeight(), QDockWidgetPrivate::updateButtons(), and QDockWidget::widget().
 {
     QLayoutItem *item = item_list.at(r);
     return item == 0 ? 0 : item->widget();
 }
Properties
_titleArea
QRect QDockWidgetLayout::_titleArea private
Definition at line 169 of file qdockwidget_p.h.
Referenced by setGeometry().
item_list
QVector<QLayoutItem*> QDockWidgetLayout::item_list private
Definition at line 168 of file qdockwidget_p.h.
Referenced by count(), itemAt(), itemForRole(), maximumSize(), minimumSize(), minimumTitleWidth(), nativeWindowDeco(), setGeometry(), setWidgetForRole(), sizeHint(), takeAt(), titleHeight(), widgetForRole(), and ~QDockWidgetLayout().
verticalTitleBar
bool QDockWidgetLayout::verticalTitleBar
Definition at line 165 of file qdockwidget_p.h.
Referenced by QDockWidget::initStyleOption(), minimumTitleWidth(), setGeometry(), setVerticalTitleBar(), sizeFromContent(), and titleHeight().
The documentation for this class was generated from the following files:
/src/gui/widgets/qdockwidget_p.h
/src/gui/widgets/qdockwidget.cpp