Qt 4.8: QVistaHelper Class Reference
QVistaHelper Class Reference
#include <qwizard_win_p.h>
Public Types
enum TitleBarChangeType { NormalTitleBar, ExtendedTitleBar }
enum VistaState { VistaAero, VistaBasic, Classic, Dirty }
Public Functions
QVistaBackButton * backButton () const
QColor basicWindowFrameColor ()
void disconnectBackButton ()
bool handleWinEvent (MSG *message, long *result)
void hideBackButton ()
void mouseEvent (QEvent *event)
void paintEvent (QPaintEvent *event)
QVistaHelper (QWizard *wizard)
void resizeEvent (QResizeEvent *event)
bool setDWMTitleBar (TitleBarChangeType type)
void setTitleBarIconAndCaptionVisible (bool visible)
void setWindowPosHack ()
~QVistaHelper ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static int titleBarSize ()
static int topOffset ()
static int topPadding ()
static VistaState vistaState ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Private Types
enum Changes { resizeTop, movePosition, noChange }
Private Functions
void collapseTopFrameStrut ()
void drawTitleBar (QPainter *painter)
bool drawTitleText (QPainter *painter, const QString &text, const QRect &rect, HDC hdc)
bool eventFilter (QObject *obj, QEvent *event)
Filters events if this object has been installed as an event filter for the watched object.
int leftMargin ()
void mouseMoveEvent (QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
bool resolveSymbols ()
void setMouseCursor (QPoint pos)
int titleOffset ()
bool winEvent (MSG *message, long *result)
Static Private Functions
static int backButtonSize ()
static int captionSize ()
static bool drawBlackRect (const QRect &rect, HDC hdc)
static int frameSize ()
static HFONT getCaptionFont (HANDLE hTheme)
static int glowSize ()
static int iconSize ()
static bool isCompositionEnabled ()
static bool isThemeActive ()
Properties
QVistaBackButton * backButton_
enum QVistaHelper::Changes change
int iconSpacing
bool pressed
QPoint pressedPos
QRect rtTitle
QRect rtTop
int textSpacing
int titleBarOffset
QWizard * wizard
Static Private Attributes
static VistaState cachedVistaState = QVistaHelper::Dirty
static int instanceCount = 0
static bool is_vista = false
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 84 of file qwizard_win_p.h.
Enumerations
Changes
enum QVistaHelper::Changes private
Enumerator
resizeTop
movePosition
noChange
Definition at line 139 of file qwizard_win_p.h.
 { resizeTop, movePosition, noChange } change;
TitleBarChangeType
enum QVistaHelper::TitleBarChangeType
Enumerator
NormalTitleBar
ExtendedTitleBar
Definition at line 89 of file qwizard_win_p.h.
 { NormalTitleBar, ExtendedTitleBar };
VistaState
enum QVistaHelper::VistaState
Enumerator
VistaAero
VistaBasic
Classic
Dirty
Definition at line 101 of file qwizard_win_p.h.
 { VistaAero, VistaBasic, Classic, Dirty };
Constructors and Destructors
QVistaHelper()
QVistaHelper::QVistaHelper (QWizard * wizard)
Definition at line 245 of file qwizard_win.cpp.
     : QObject(wizard)
     , pressed(false)
     , wizard(wizard)
     , backButton_(0)
 {
     is_vista = QSysInfo::WindowsVersion >= QSysInfo::WV_VISTA && resolveSymbols();
     if (instanceCount++ == 0)
         cachedVistaState = Dirty;
     if (is_vista)
         backButton_ = new QVistaBackButton(wizard);
     // Handle diff between Windows 7 and Vista
     iconSpacing = QStyleHelper::dpiScaled(7);
     textSpacing = QSysInfo::WindowsVersion >= QSysInfo::WV_WINDOWS7 ?
                   iconSpacing : QStyleHelper::dpiScaled(20);
 }
~QVistaHelper()
QVistaHelper::~QVistaHelper ()
Definition at line 263 of file qwizard_win.cpp.
 {
     --instanceCount;
 }
Functions
backButton()
QVistaBackButton* QVistaHelper::backButton () const inline
Definition at line 96 of file qwizard_win_p.h.
 { return backButton_; }
backButtonSize()
static int QVistaHelper::backButtonSize () inline static private
Definition at line 118 of file qwizard_win_p.h.
 { return int(QStyleHelper::dpiScaled(30)); }
basicWindowFrameColor()
QColor QVistaHelper::basicWindowFrameColor ()
Definition at line 300 of file qwizard_win.cpp.
 {
     DWORD rgb;
     HANDLE hTheme = pOpenThemeData(QApplication::desktop()->winId(), L"WINDOW");
     pGetThemeColor(
         hTheme, WIZ_WP_CAPTION, WIZ_CS_ACTIVE,
         wizard->isActiveWindow() ? WIZ_TMT_FILLCOLORHINT : WIZ_TMT_BORDERCOLORHINT,
         &rgb);
     BYTE r = GetRValue(rgb);
     BYTE g = GetGValue(rgb);
     BYTE b = GetBValue(rgb);
     return QColor(r, g, b);
 }
captionSize()
int QVistaHelper::captionSize () static private
Definition at line 762 of file qwizard_win.cpp.
Referenced by resizeEvent().
 {
     return GetSystemMetrics(SM_CYCAPTION);
 }
collapseTopFrameStrut()
void QVistaHelper::collapseTopFrameStrut () private
Definition at line 483 of file qwizard_win.cpp.
Referenced by handleWinEvent().
 {
     QTLWExtra *top = ((QHackWidget *)wizard)->d_func()->topData();
     int x1, y1, x2, y2;
     top->frameStrut.getCoords(&x1, &y1, &x2, &y2);
     top->frameStrut.setCoords(x1, 0, x2, y2);
 }
disconnectBackButton()
void QVistaHelper::disconnectBackButton ()
Definition at line 294 of file qwizard_win.cpp.
 {
     if (backButton_) // Leave QStyleSheetStyle's connections on destroyed() intact.
         backButton_->disconnect(SIGNAL(clicked()));
 }
drawBlackRect()
bool QVistaHelper::drawBlackRect (const QRect & rect, HDC hdc) static private
Definition at line 711 of file qwizard_win.cpp.
Referenced by drawTitleBar().
 {
     bool value = false;
     if (vistaState() == VistaAero) {
         // Set up a memory DC and bitmap that we'll draw into
         HDC dcMem;
         HBITMAP bmp;
         BITMAPINFO dib = {{0}};
         dcMem = CreateCompatibleDC(hdc);
         dib.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
         dib.bmiHeader.biWidth = rect.width();
         dib.bmiHeader.biHeight = -rect.height();
         dib.bmiHeader.biPlanes = 1;
         dib.bmiHeader.biBitCount = 32;
         dib.bmiHeader.biCompression = BI_RGB;
         bmp = CreateDIBSection(hdc, &dib, DIB_RGB_COLORS, NULL, NULL, 0);
         HBITMAP hOldBmp = (HBITMAP)SelectObject(dcMem, (HGDIOBJ) bmp);
         BitBlt(hdc, rect.left(), rect.top(), rect.width(), rect.height(), dcMem, 0, 0, SRCCOPY);
         SelectObject(dcMem, (HGDIOBJ) hOldBmp);
         DeleteObject(bmp);
         DeleteDC(dcMem);
     }
     return value;
 }
drawTitleBar()
void QVistaHelper::drawTitleBar (QPainter * painter) private
Definition at line 329 of file qwizard_win.cpp.
Referenced by paintEvent().
 {
     HDC hdc = painter->paintEngine()->getDC();
     if (vistaState() == VistaAero)
         drawBlackRect(QRect(0, 0, wizard->width(),
                             titleBarSize() + topOffset()), hdc);
     Q_ASSERT(backButton_);
     const int btnTop = backButton_->mapToParent(QPoint()).y();
     const int btnHeight = backButton_->size().height();
     const int verticalCenter = (btnTop + btnHeight / 2) - 1;
     const QString text = wizard->window()->windowTitle();
     const QFont font = QApplication::font("QWorkspaceTitleBar");
     const QFontMetrics fontMetrics(font);
     const QRect brect = fontMetrics.boundingRect(text);
     int textHeight = brect.height();
     int textWidth = brect.width();
     int glowOffset = 0;
     if (vistaState() == VistaAero) {
         textHeight += 2 * glowSize();
         textWidth += 2 * glowSize();
         glowOffset = glowSize();
     }
     const int titleLeft = (wizard->layoutDirection() == Qt::LeftToRight
                            ? titleOffset() - glowOffset
                            : wizard->width() - titleOffset() - textWidth + glowOffset);
     drawTitleText(
         painter, text,
         QRect(titleLeft, verticalCenter - textHeight / 2, textWidth, textHeight),
         hdc);
     if (!wizard->windowIcon().isNull()) {
         const int iconLeft = (wizard->layoutDirection() == Qt::LeftToRight
                               ? leftMargin()
                               : wizard->width() - leftMargin() - iconSize());
         QRect rect(iconLeft, verticalCenter - iconSize() / 2, iconSize(), iconSize());
         HICON hIcon = wizard->windowIcon().pixmap(iconSize()).toWinHICON();
         DrawIconEx(hdc, rect.left(), rect.top(), hIcon, 0, 0, 0, NULL, DI_NORMAL | DI_COMPAT);
         DestroyIcon(hIcon);
     }
 }
drawTitleText()
bool QVistaHelper::drawTitleText (QPainter * painter, const QString & text, const QRect & rect, HDC hdc) private
Definition at line 663 of file qwizard_win.cpp.
Referenced by drawTitleBar().
 {
     bool value = false;
     if (vistaState() == VistaAero) {
         HANDLE hTheme = pOpenThemeData(QApplication::desktop()->winId(), L"WINDOW");
         if (!hTheme) return false;
         // Set up a memory DC and bitmap that we'll draw into
         HDC dcMem;
         HBITMAP bmp;
         BITMAPINFO dib = {{0}};
         dcMem = CreateCompatibleDC(hdc);
         dib.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
         dib.bmiHeader.biWidth = rect.width();
         dib.bmiHeader.biHeight = -rect.height();
         dib.bmiHeader.biPlanes = 1;
         dib.bmiHeader.biBitCount = 32;
         dib.bmiHeader.biCompression = BI_RGB;
         bmp = CreateDIBSection(hdc, &dib, DIB_RGB_COLORS, NULL, NULL, 0);
         // Set up the DC
         HFONT hCaptionFont = getCaptionFont(hTheme);
         HBITMAP hOldBmp = (HBITMAP)SelectObject(dcMem, (HGDIOBJ) bmp);
         HFONT hOldFont = (HFONT)SelectObject(dcMem, (HGDIOBJ) hCaptionFont);
         // Draw the text!
         WIZ_DTTOPTS dto = { sizeof(WIZ_DTTOPTS) };
         const UINT uFormat = WIZ_DT_SINGLELINE|WIZ_DT_CENTER|WIZ_DT_VCENTER|WIZ_DT_NOPREFIX;
         RECT rctext ={0,0, rect.width(), rect.height()};
         dto.dwFlags = WIZ_DTT_COMPOSITED|WIZ_DTT_GLOWSIZE;
         dto.iGlowSize = glowSize();
         pDrawThemeTextEx(hTheme, dcMem, 0, 0, (LPCWSTR)text.utf16(), -1, uFormat, &rctext, &dto );
         BitBlt(hdc, rect.left(), rect.top(), rect.width(), rect.height(), dcMem, 0, 0, SRCCOPY);
         SelectObject(dcMem, (HGDIOBJ) hOldBmp);
         SelectObject(dcMem, (HGDIOBJ) hOldFont);
         DeleteObject(bmp);
         DeleteObject(hCaptionFont);
         DeleteDC(dcMem);
         //ReleaseDC(hwnd, hdc);
     } else if (vistaState() == VistaBasic) {
         painter->drawText(rect, text);
     }
     return value;
 }
eventFilter()
bool QVistaHelper::eventFilter (QObject * , QEvent *) private virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QObject.
Definition at line 596 of file qwizard_win.cpp.
 {
     if (obj != wizard)
         return QObject::eventFilter(obj, event);
     if (event->type() == QEvent::MouseMove) {
         QMouseEvent *mouseEvent = static_cast<QMouseEvent*>(event);
         long result;
         MSG msg;
         msg.message = WM_NCHITTEST;
         msg.wParam  = 0;
         msg.lParam = MAKELPARAM(mouseEvent->globalX(), mouseEvent->globalY());
         msg.hwnd = wizard->winId();
         winEvent(&msg, &result);
         msg.wParam = result;
         msg.message = WM_NCMOUSEMOVE;
         winEvent(&msg, &result);
      } else if (event->type() == QEvent::MouseButtonPress) {
         QMouseEvent *mouseEvent = static_cast<QMouseEvent*>(event);
         if (mouseEvent->button() == Qt::LeftButton) {
             long result;
             MSG msg;
             msg.message = WM_NCHITTEST;
             msg.wParam  = 0;
             msg.lParam = MAKELPARAM(mouseEvent->globalX(), mouseEvent->globalY());
             msg.hwnd = wizard->winId();
             winEvent(&msg, &result);
             msg.wParam = result;
             msg.message = WM_NCLBUTTONDOWN;
             winEvent(&msg, &result);
         }
      } else if (event->type() == QEvent::MouseButtonRelease) {
         QMouseEvent *mouseEvent = static_cast<QMouseEvent*>(event);
         if (mouseEvent->button() == Qt::LeftButton) {
             long result;
             MSG msg;
             msg.message = WM_NCHITTEST;
             msg.wParam  = 0;
             msg.lParam = MAKELPARAM(mouseEvent->globalX(), mouseEvent->globalY());
             msg.hwnd = wizard->winId();
             winEvent(&msg, &result);
             msg.wParam = result;
             msg.message = WM_NCLBUTTONUP;
             winEvent(&msg, &result);
         }
      }
      return false;
 }
frameSize()
int QVistaHelper::frameSize () static private
Definition at line 757 of file qwizard_win.cpp.
Referenced by resizeEvent().
 {
     return getWindowBottomMargin();
 }
getCaptionFont()
HFONT QVistaHelper::getCaptionFont (HANDLE hTheme) static private
Definition at line 648 of file qwizard_win.cpp.
Referenced by drawTitleText().
 {
     LOGFONT lf = {0};
     if (!hTheme)
         pGetThemeSysFont(hTheme, WIZ_TMT_CAPTIONFONT, &lf);
     else
     {
         NONCLIENTMETRICS ncm = {sizeof(NONCLIENTMETRICS)};
         SystemParametersInfo(SPI_GETNONCLIENTMETRICS, sizeof(NONCLIENTMETRICS), &ncm, false);
         lf = ncm.lfMessageFont;
     }
     return CreateFontIndirect(&lf);
 }
glowSize()
static int QVistaHelper::glowSize () inline static private
Definition at line 120 of file qwizard_win_p.h.
Referenced by drawTitleBar(), and drawTitleText().
 { return 10; }
handleWinEvent()
bool QVistaHelper::handleWinEvent (MSG * message, long * result)
Definition at line 491 of file qwizard_win.cpp.
 {
     if (message->message == WIZ_WM_THEMECHANGED || message->message == WIZ_WM_DWMCOMPOSITIONCHANGED)
         cachedVistaState = Dirty;
     bool status = false;
     if (wizard->wizardStyle() == QWizard::AeroStyle && vistaState() == VistaAero) {
         status = winEvent(message, result);
         if (message->message == WM_NCCALCSIZE) {
             if (status)
                 collapseTopFrameStrut();
         } else if (message->message == WM_NCPAINT) {
             wizard->update();
         }
     }
     return status;
 }
hideBackButton()
void QVistaHelper::hideBackButton () inline
Definition at line 98 of file qwizard_win_p.h.
 { if (backButton_) backButton_->hide(); }
iconSize()
static int QVistaHelper::iconSize () inline static private
Definition at line 119 of file qwizard_win_p.h.
Referenced by drawTitleBar(), and titleOffset().
 { return 16; } // Standard Aero
isCompositionEnabled()
bool QVistaHelper::isCompositionEnabled () static private
Definition at line 268 of file qwizard_win.cpp.
Referenced by vistaState().
 {
     bool value = is_vista;
     if (is_vista) {
         HRESULT hr;
         BOOL bEnabled;
         hr = pDwmIsCompositionEnabled(&bEnabled);
         value = (SUCCEEDED(hr) && bEnabled);
     }
     return value;
 }
isThemeActive()
bool QVistaHelper::isThemeActive () static private
Definition at line 281 of file qwizard_win.cpp.
Referenced by vistaState().
 {
     return is_vista && pIsThemeActive();
 }
leftMargin()
int QVistaHelper::leftMargin () inline private
Definition at line 121 of file qwizard_win_p.h.
Referenced by drawTitleBar(), and titleOffset().
 { return backButton_->isVisible() ? backButtonSize() + iconSpacing : 0; }
mouseEvent()
void QVistaHelper::mouseEvent (QEvent * event)
Definition at line 443 of file qwizard_win.cpp.
Referenced by eventFilter().
 {
     switch (event->type()) {
     case QEvent::MouseMove:
         mouseMoveEvent(static_cast<QMouseEvent *>(event));
         break;
     case QEvent::MouseButtonPress:
         mousePressEvent(static_cast<QMouseEvent *>(event));
         break;
     case QEvent::MouseButtonRelease:
         mouseReleaseEvent(static_cast<QMouseEvent *>(event));
         break;
     default:
         break;
     }
 }
mouseMoveEvent()
void QVistaHelper::mouseMoveEvent (QMouseEvent * event) private
Definition at line 526 of file qwizard_win.cpp.
Referenced by mouseEvent().
 {
     if (wizard->windowState() & Qt::WindowMaximized) {
         event->ignore();
         return;
     }
     QRect rect = wizard->geometry();
     if (pressed) {
         switch (change) {
         case resizeTop:
             {
                 const int dy = event->pos().y() - pressedPos.y();
                 if ((dy > 0 && rect.height() > wizard->minimumHeight())
                     || (dy < 0 && rect.height() < wizard->maximumHeight()))
                     rect.setTop(rect.top() + dy);
             }
             break;
         case movePosition: {
             QPoint newPos = event->pos() - pressedPos;
             rect.moveLeft(rect.left() + newPos.x());
             rect.moveTop(rect.top() + newPos.y());
             break; }
         default:
             break;
         }
         wizard->setGeometry(rect);
     } else if (vistaState() == VistaAero) {
         setMouseCursor(event->pos());
     }
     event->ignore();
 }
mousePressEvent()
void QVistaHelper::mousePressEvent (QMouseEvent * event) private
Definition at line 560 of file qwizard_win.cpp.
Referenced by mouseEvent().
 {
     change = noChange;
     if (event->button() != Qt::LeftButton || wizard->windowState() & Qt::WindowMaximized) {
         event->ignore();
         return;
     }
     if (rtTitle.contains(event->pos())) {
         change = movePosition;
     } else if (rtTop.contains(event->pos()))
         change = (vistaState() == VistaAero) ? resizeTop : movePosition;
     if (change != noChange) {
         if (vistaState() == VistaAero)
             setMouseCursor(event->pos());
         pressed = true;
         pressedPos = event->pos();
     } else {
         event->ignore();
     }
 }
mouseReleaseEvent()
void QVistaHelper::mouseReleaseEvent (QMouseEvent * event) private
Definition at line 584 of file qwizard_win.cpp.
Referenced by mouseEvent().
 {
     change = noChange;
     if (pressed) {
         pressed = false;
         wizard->releaseMouse();
         if (vistaState() == VistaAero)
             setMouseCursor(event->pos());
     }
     event->ignore();
 }
paintEvent()
void QVistaHelper::paintEvent (QPaintEvent * event)
Definition at line 519 of file qwizard_win.cpp.
 {
     Q_UNUSED(event);
     QPainter painter(wizard);
     drawTitleBar(&painter);
 }
resizeEvent()
void QVistaHelper::resizeEvent (QResizeEvent * event)
Definition at line 509 of file qwizard_win.cpp.
 {
     Q_UNUSED(event);
     rtTop = QRect (0, 0, wizard->width(), frameSize());
     int height = captionSize() + topOffset();
     if (vistaState() == VistaBasic)
         height -= titleBarSize();
     rtTitle = QRect (0, frameSize(), wizard->width(), height);
 }
resolveSymbols()
bool QVistaHelper::resolveSymbols () private
Definition at line 767 of file qwizard_win.cpp.
Referenced by QVistaHelper().
 {
     static bool tried = false;
     if (!tried) {
         QSystemLibrary dwmLib(L"dwmapi");
         pDwmIsCompositionEnabled =
             (PtrDwmIsCompositionEnabled)dwmLib.resolve("DwmIsCompositionEnabled");
         if (pDwmIsCompositionEnabled) {
             pDwmDefWindowProc = (PtrDwmDefWindowProc)dwmLib.resolve("DwmDefWindowProc");
             pDwmExtendFrameIntoClientArea =
                 (PtrDwmExtendFrameIntoClientArea)dwmLib.resolve("DwmExtendFrameIntoClientArea");
         }
         QSystemLibrary themeLib(L"uxtheme");
         pIsAppThemed = (PtrIsAppThemed)themeLib.resolve("IsAppThemed");
         if (pIsAppThemed) {
             pDrawThemeBackground = (PtrDrawThemeBackground)themeLib.resolve("DrawThemeBackground");
             pGetThemePartSize = (PtrGetThemePartSize)themeLib.resolve("GetThemePartSize");
             pGetThemeColor = (PtrGetThemeColor)themeLib.resolve("GetThemeColor");
             pIsThemeActive = (PtrIsThemeActive)themeLib.resolve("IsThemeActive");
             pOpenThemeData = (PtrOpenThemeData)themeLib.resolve("OpenThemeData");
             pCloseThemeData = (PtrCloseThemeData)themeLib.resolve("CloseThemeData");
             pGetThemeSysFont = (PtrGetThemeSysFont)themeLib.resolve("GetThemeSysFont");
             pDrawThemeTextEx = (PtrDrawThemeTextEx)themeLib.resolve("DrawThemeTextEx");
             pSetWindowThemeAttribute = (PtrSetWindowThemeAttribute)themeLib.resolve("SetWindowThemeAttribute");
         }
         tried = true;
     }
     return (
         pDwmIsCompositionEnabled != 0
         && pDwmDefWindowProc != 0
         && pDwmExtendFrameIntoClientArea != 0
         && pIsAppThemed != 0
         && pDrawThemeBackground != 0
         && pGetThemePartSize != 0
         && pGetThemeColor != 0
         && pIsThemeActive != 0
         && pOpenThemeData != 0
         && pCloseThemeData != 0
         && pGetThemeSysFont != 0
         && pDrawThemeTextEx != 0
         && pSetWindowThemeAttribute != 0
         );
 }
setDWMTitleBar()
bool QVistaHelper::setDWMTitleBar (TitleBarChangeType type)
Definition at line 314 of file qwizard_win.cpp.
 {
     bool value = false;
     if (vistaState() == VistaAero) {
         WIZ_MARGINS mar = {0};
         if (type == NormalTitleBar)
             mar.cyTopHeight = 0;
         else
             mar.cyTopHeight = titleBarSize() + topOffset();
         HRESULT hr = pDwmExtendFrameIntoClientArea(wizard->winId(), &mar);
         value = SUCCEEDED(hr);
     }
     return value;
 }
setMouseCursor()
void QVistaHelper::setMouseCursor (QPoint pos) private
Definition at line 433 of file qwizard_win.cpp.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
 {
 #ifndef QT_NO_CURSOR
     if (rtTop.contains(pos))
         wizard->setCursor(Qt::SizeVerCursor);
     else
         wizard->setCursor(Qt::ArrowCursor);
 #endif
 }
setTitleBarIconAndCaptionVisible()
void QVistaHelper::setTitleBarIconAndCaptionVisible (bool visible)
Definition at line 376 of file qwizard_win.cpp.
 {
     if (is_vista) {
         WIZ_WTA_OPTIONS opt;
         opt.dwFlags = WIZ_WTNCA_NODRAWICON | WIZ_WTNCA_NODRAWCAPTION;
         if (visible)
             opt.dwMask = 0;
         else
             opt.dwMask = WIZ_WTNCA_NODRAWICON | WIZ_WTNCA_NODRAWCAPTION;
         pSetWindowThemeAttribute(wizard->winId(), WIZ_WTA_NONCLIENT, &opt, sizeof(WIZ_WTA_OPTIONS));
     }
 }
setWindowPosHack()
void QVistaHelper::setWindowPosHack ()
Definition at line 464 of file qwizard_win.cpp.
 {
     const int x = wizard->geometry().x(); // ignored by SWP_NOMOVE
     const int y = wizard->geometry().y(); // ignored by SWP_NOMOVE
     const int w = wizard->width();
     const int h = wizard->height();
     SetWindowPos(wizard->winId(), 0, x, y, w, h, SWP_NOMOVE | SWP_NOZORDER | SWP_FRAMECHANGED);
 }
titleBarSize()
static int QVistaHelper::titleBarSize () inline static
Definition at line 103 of file qwizard_win_p.h.
Referenced by drawTitleBar(), resizeEvent(), setDWMTitleBar(), topOffset(), and winEvent().
 { return frameSize() + captionSize(); }
titleOffset()
int QVistaHelper::titleOffset () private
Definition at line 812 of file qwizard_win.cpp.
Referenced by drawTitleBar().
 {
     int iconOffset = wizard ->windowIcon().isNull() ? 0 : iconSize() + textSpacing;
     return leftMargin() + iconOffset;
 }
topOffset()
int QVistaHelper::topOffset () static
Definition at line 818 of file qwizard_win.cpp.
Referenced by drawTitleBar(), QWizard::paintEvent(), resizeEvent(), and setDWMTitleBar().
 {
     if (vistaState() != VistaAero)
         return titleBarSize() + 3;
     static const int aeroOffset =
         QSysInfo::WindowsVersion == QSysInfo::WV_WINDOWS7 ?
         QStyleHelper::dpiScaled(4) : QStyleHelper::dpiScaled(13);
     return aeroOffset + titleBarSize();
 }
topPadding()
static int QVistaHelper::topPadding () inline static
Definition at line 104 of file qwizard_win_p.h.
                             { // padding under text
         return int(QStyleHelper::dpiScaled(
                 QSysInfo::WindowsVersion >= QSysInfo::WV_WINDOWS7 ? 4 : 6));
     }
vistaState()
QVistaHelper::VistaState QVistaHelper::vistaState () static
Definition at line 286 of file qwizard_win.cpp.
Referenced by drawBlackRect(), drawTitleBar(), drawTitleText(), handleWinEvent(), QWizardPrivate::isVistaThemeEnabled(), QWizardPrivate::layoutInfoForCurrentPage(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), resizeEvent(), setDWMTitleBar(), QWizardHeader::setup(), topOffset(), winEvent(), and QWizard::winEvent().
 {
     if (instanceCount == 0 || cachedVistaState == Dirty)
         cachedVistaState =
             isCompositionEnabled() ? VistaAero : isThemeActive() ? VistaBasic : Classic;
     return cachedVistaState;
 }
winEvent()
bool QVistaHelper::winEvent (MSG * message, long * result) private
Definition at line 389 of file qwizard_win.cpp.
Referenced by eventFilter(), and handleWinEvent().
 {
     switch (msg->message) {
     case WM_NCHITTEST: {
         LRESULT lResult;
         // Perform hit testing using DWM
         if (pDwmDefWindowProc(msg->hwnd, msg->message, msg->wParam, msg->lParam, &lResult)) {
             // DWM returned a hit, no further processing necessary
             *result = lResult;
         } else {
             // DWM didn't return a hit, process using DefWindowProc
             lResult = DefWindowProc(msg->hwnd, msg->message, msg->wParam, msg->lParam);
             // If DefWindowProc returns a window caption button, just return HTCLIENT (client area).
             // This avoid unnecessary hits to Windows NT style caption buttons which aren't visible but are
             // located just under the Aero style window close button.
             if (lResult == HTCLOSE || lResult == HTMAXBUTTON || lResult == HTMINBUTTON || lResult == HTHELP)
                 *result = HTCLIENT;
             else
                 *result = lResult;
         }
         break;
     }
     case WM_NCCALCSIZE:
         if (vistaState() == VistaAero) {
             NCCALCSIZE_PARAMS* lpncsp = (NCCALCSIZE_PARAMS*)msg->lParam;
             *result = DefWindowProc(msg->hwnd, msg->message, msg->wParam, msg->lParam);
             lpncsp->rgrc[0].top -= titleBarSize();
         } else {
             return false;
         }
         break;
     default:
         LRESULT lResult;
         // Pass to DWM to handle
         if (pDwmDefWindowProc(msg->hwnd, msg->message, msg->wParam, msg->lParam, &lResult))
             *result = lResult;
         // If the message wasn't handled by DWM, continue processing it as normal
         else
             return false;
     }
     return true;
 }
Properties
backButton_
QVistaBackButton* QVistaHelper::backButton_ private
Definition at line 145 of file qwizard_win_p.h.
Referenced by disconnectBackButton(), drawTitleBar(), and QVistaHelper().
cachedVistaState
QVistaHelper::VistaState QVistaHelper::cachedVistaState = QVistaHelper::Dirty static private
Definition at line 136 of file qwizard_win_p.h.
Referenced by handleWinEvent(), QVistaHelper(), and vistaState().
change
enum QVistaHelper::Changes QVistaHelper::change private
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
iconSpacing
int QVistaHelper::iconSpacing private
Definition at line 148 of file qwizard_win_p.h.
Referenced by QVistaHelper().
instanceCount
int QVistaHelper::instanceCount = 0 static private
Definition at line 134 of file qwizard_win_p.h.
Referenced by QVistaHelper(), vistaState(), and ~QVistaHelper().
is_vista
bool QVistaHelper::is_vista = false static private
Definition at line 135 of file qwizard_win_p.h.
Referenced by isCompositionEnabled(), isThemeActive(), QVistaHelper(), and setTitleBarIconAndCaptionVisible().
pressed
bool QVistaHelper::pressed private
Definition at line 141 of file qwizard_win_p.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
pressedPos
QPoint QVistaHelper::pressedPos private
Definition at line 140 of file qwizard_win_p.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
rtTitle
QRect QVistaHelper::rtTitle private
Definition at line 143 of file qwizard_win_p.h.
Referenced by mousePressEvent(), and resizeEvent().
rtTop
QRect QVistaHelper::rtTop private
Definition at line 142 of file qwizard_win_p.h.
Referenced by mousePressEvent(), resizeEvent(), and setMouseCursor().
textSpacing
int QVistaHelper::textSpacing private
Definition at line 149 of file qwizard_win_p.h.
Referenced by QVistaHelper(), and titleOffset().
titleBarOffset
int QVistaHelper::titleBarOffset private
Definition at line 147 of file qwizard_win_p.h.
wizard
QWizard* QVistaHelper::wizard private
Definition at line 144 of file qwizard_win_p.h.
Referenced by basicWindowFrameColor(), collapseTopFrameStrut(), drawTitleBar(), eventFilter(), handleWinEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), resizeEvent(), setDWMTitleBar(), setMouseCursor(), setTitleBarIconAndCaptionVisible(), setWindowPosHack(), and titleOffset().
The documentation for this class was generated from the following files:
/src/gui/dialogs/qwizard_win_p.h
/src/gui/dialogs/qwizard_win.cpp