Qt 4.8: QHttpNetworkRequest Class Reference
QHttpNetworkRequest Class Reference
#include <qhttpnetworkrequest_p.h>
Public Types
enum Operation {
Options, Get, Head, Post,
Put, Delete, Trace, Connect,
Custom
}
enum Priority { HighPriority, NormalPriority, LowPriority }
Public Functions
qint64 contentLength () const
QByteArray customVerb () const
QList< QPair< QByteArray, QByteArray > > header () const
QByteArray headerField (const QByteArray &name, const QByteArray &defaultValue=QByteArray()) const
bool isPipeliningAllowed () const
bool isSsl () const
int majorVersion () const
int minorVersion () const
Operation operation () const
QHttpNetworkRequest & operator= (const QHttpNetworkRequest &other)
bool operator== (const QHttpNetworkRequest &other) const
Priority priority () const
QHttpNetworkRequest (const QUrl &url=QUrl(), Operation operation=Get, Priority priority=NormalPriority)
QHttpNetworkRequest (const QHttpNetworkRequest &other)
void setContentLength (qint64 length)
void setCustomVerb (const QByteArray &customOperation)
void setHeaderField (const QByteArray &name, const QByteArray &data)
void setOperation (Operation operation)
void setPipeliningAllowed (bool b)
void setPriority (Priority priority)
void setSsl (bool)
void setUploadByteDevice (QNonContiguousByteDevice *bd)
void setUrl (const QUrl &url)
void setWithCredentials (bool b)
QNonContiguousByteDevice * uploadByteDevice () const
QUrl url () const
bool withCredentials () const
virtual ~QHttpNetworkRequest ()
Public Functions inherited from QHttpNetworkHeader
virtual ~QHttpNetworkHeader ()
Properties
QSharedDataPointer< QHttpNetworkRequestPrivate > d
Friends
class QHttpNetworkConnectionChannel
class QHttpNetworkConnectionPrivate
class QHttpNetworkRequestPrivate
Detailed Description
Definition at line 64 of file qhttpnetworkrequest_p.h.
Enumerations
Operation
enum QHttpNetworkRequest::Operation
Enumerator
Options
Get
Head
Post
Put
Delete
Trace
Connect
Custom
Definition at line 67 of file qhttpnetworkrequest_p.h.
                    {
         Options,
         Get,
         Head,
         Post,
         Put,
         Delete,
         Trace,
         Connect,
         Custom
     };
Priority
enum QHttpNetworkRequest::Priority
Enumerator
HighPriority
NormalPriority
LowPriority
Definition at line 79 of file qhttpnetworkrequest_p.h.
                   {
         HighPriority,
         NormalPriority,
         LowPriority
     };
Constructors and Destructors
QHttpNetworkRequest() [1/2]
QHttpNetworkRequest::QHttpNetworkRequest (const QUrl & url = QUrl(), Operation operation = Get, Priority priority = NormalPriority)
Definition at line 186 of file qhttpnetworkrequest.cpp.
     : d(new QHttpNetworkRequestPrivate(operation, priority, url))
 {
 }
QHttpNetworkRequest() [2/2]
QHttpNetworkRequest::QHttpNetworkRequest (const QHttpNetworkRequest & other)
Definition at line 191 of file qhttpnetworkrequest.cpp.
     : QHttpNetworkHeader(other), d(other.d)
 {
 }
~QHttpNetworkRequest()
QHttpNetworkRequest::~QHttpNetworkRequest () virtual
Definition at line 196 of file qhttpnetworkrequest.cpp.
 {
 }
Functions
contentLength()
qint64 QHttpNetworkRequest::contentLength () const virtual
Implements QHttpNetworkHeader.
Definition at line 218 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkConnectionPrivate::prepareRequest(), and QHttpNetworkConnectionChannel::sendRequest().
 {
     return d->contentLength();
 }
customVerb()
QByteArray QHttpNetworkRequest::customVerb () const
Definition at line 264 of file qhttpnetworkrequest.cpp.
Referenced by setCustomVerb().
 {
     return d->customVerb;
 }
header()
QList< QPair< QByteArray, QByteArray > > QHttpNetworkRequest::header () const virtual
Implements QHttpNetworkHeader.
Definition at line 228 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkRequestPrivate::header().
 {
     return d->fields;
 }
headerField()
QByteArray QHttpNetworkRequest::headerField (const QByteArray & name, const QByteArray & defaultValue = QByteArray()) const virtual
Implements QHttpNetworkHeader.
Definition at line 233 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkConnectionChannel::ensureConnection(), QHttpNetworkRequestPrivate::header(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), and QHttpNetworkConnectionPrivate::prepareRequest().
 {
     return d->headerField(name, defaultValue);
 }
isPipeliningAllowed()
bool QHttpNetworkRequest::isPipeliningAllowed () const
Definition at line 284 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkConnectionPrivate::fillPipeline().
 {
     return d->pipeliningAllowed;
 }
isSsl()
bool QHttpNetworkRequest::isSsl () const
Definition at line 209 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkReply::setRequest().
 {
     return d->ssl;
 }
majorVersion()
int QHttpNetworkRequest::majorVersion () const virtual
Implements QHttpNetworkHeader.
Definition at line 314 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkRequestPrivate::header().
 {
     return 1;
 }
minorVersion()
int QHttpNetworkRequest::minorVersion () const virtual
Implements QHttpNetworkHeader.
Definition at line 319 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkRequestPrivate::header().
 {
     return 1;
 }
operation()
QHttpNetworkRequest::Operation QHttpNetworkRequest::operation () const
Definition at line 254 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkReplyPrivate::expectContent(), QNetworkAccessHttpBackend::fetchCacheMetaData(), QHttpNetworkConnectionPrivate::fillPipeline(), and setOperation().
 {
     return d->operation;
 }
operator=()
QHttpNetworkRequest & QHttpNetworkRequest::operator= (const QHttpNetworkRequest & other)
Definition at line 243 of file qhttpnetworkrequest.cpp.
 {
     d = other.d;
     return *this;
 }
operator==()
bool QHttpNetworkRequest::operator== (const QHttpNetworkRequest & other) const
Definition at line 249 of file qhttpnetworkrequest.cpp.
 {
     return d->operator==(*other.d);
 }
priority()
QHttpNetworkRequest::Priority QHttpNetworkRequest::priority () const
Definition at line 274 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkConnectionPrivate::queueRequest(), QHttpNetworkConnectionPrivate::requeueRequest(), and setPriority().
 {
     return d->priority;
 }
setContentLength()
void QHttpNetworkRequest::setContentLength (qint64 length) virtual
Implements QHttpNetworkHeader.
Definition at line 223 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkConnectionPrivate::prepareRequest().
 {
     d->setContentLength(length);
 }
setCustomVerb()
void QHttpNetworkRequest::setCustomVerb (const QByteArray & customOperation)
Definition at line 269 of file qhttpnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest().
 {
     d->customVerb = customVerb;
 }
setHeaderField()
void QHttpNetworkRequest::setHeaderField (const QByteArray & name, const QByteArray & data) virtual
Implements QHttpNetworkHeader.
Definition at line 238 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkConnectionPrivate::createAuthorization(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QNetworkAccessHttpBackend::postRequest(), and QHttpNetworkConnectionPrivate::prepareRequest().
 {
     d->setHeaderField(name, data);
 }
setOperation()
void QHttpNetworkRequest::setOperation (Operation operation)
Definition at line 259 of file qhttpnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest().
 {
     d->operation = operation;
 }
setPipeliningAllowed()
void QHttpNetworkRequest::setPipeliningAllowed (bool b)
Definition at line 289 of file qhttpnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest().
 {
     d->pipeliningAllowed = b;
 }
setPriority()
void QHttpNetworkRequest::setPriority (Priority priority)
Definition at line 279 of file qhttpnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest().
 {
     d->priority = priority;
 }
setSsl()
void QHttpNetworkRequest::setSsl (bool s)
Definition at line 213 of file qhttpnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest().
 {
     d->ssl = s;
 }
setUploadByteDevice()
void QHttpNetworkRequest::setUploadByteDevice (QNonContiguousByteDevice * bd)
Definition at line 304 of file qhttpnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest().
 {
     d->uploadByteDevice = bd;
 }
setUrl()
void QHttpNetworkRequest::setUrl (const QUrl & url) virtual
Implements QHttpNetworkHeader.
Definition at line 204 of file qhttpnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest(), and QHttpNetworkConnectionChannel::sendRequest().
 {
     d->url = url;
 }
setWithCredentials()
void QHttpNetworkRequest::setWithCredentials (bool b)
Definition at line 299 of file qhttpnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest().
 {
     d->withCredentials = b;
 }
uploadByteDevice()
QNonContiguousByteDevice * QHttpNetworkRequest::uploadByteDevice () const
Definition at line 309 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkConnectionPrivate::prepareRequest(), QHttpNetworkConnectionChannel::resetUploadData(), and QHttpNetworkConnectionChannel::sendRequest().
 {
     return d->uploadByteDevice;
 }
url()
QUrl QHttpNetworkRequest::url () const virtual
Implements QHttpNetworkHeader.
Definition at line 200 of file qhttpnetworkrequest.cpp.
Referenced by QHttpThreadDelegate::cacheCredentialsSlot(), QHttpNetworkConnectionChannel::ensureConnection(), QHttpNetworkConnectionPrivate::fillPipeline(), QHttpThreadDelegate::finishedSlot(), QHttpNetworkConnectionPrivate::prepareRequest(), QHttpNetworkConnectionPrivate::queueRequest(), QHttpNetworkConnectionChannel::sendRequest(), setUrl(), QHttpThreadDelegate::startRequest(), QHttpThreadDelegate::synchronousAuthenticationRequiredSlot(), and QHttpThreadDelegate::synchronousFinishedSlot().
 {
     return d->url;
 }
withCredentials()
bool QHttpNetworkRequest::withCredentials () const
Definition at line 294 of file qhttpnetworkrequest.cpp.
Referenced by QHttpNetworkConnectionPrivate::handleAuthenticateChallenge(), and QHttpNetworkConnectionChannel::sendRequest().
 {
     return d->withCredentials;
 }
Friends and Related Functions
QHttpNetworkConnectionChannel
friend class QHttpNetworkConnectionChannel friend
Definition at line 129 of file qhttpnetworkrequest_p.h.
QHttpNetworkConnectionPrivate
friend class QHttpNetworkConnectionPrivate friend
Definition at line 128 of file qhttpnetworkrequest_p.h.
QHttpNetworkRequestPrivate
friend class QHttpNetworkRequestPrivate friend
Definition at line 127 of file qhttpnetworkrequest_p.h.
Properties
d
QSharedDataPointer<QHttpNetworkRequestPrivate> QHttpNetworkRequest::d private
Definition at line 126 of file qhttpnetworkrequest_p.h.
Referenced by contentLength(), QHttpNetworkConnectionPrivate::createAuthorization(), customVerb(), header(), QHttpNetworkRequestPrivate::header(), headerField(), isPipeliningAllowed(), isSsl(), operation(), operator=(), operator==(), QHttpNetworkConnectionChannel::pipelineInto(), QHttpNetworkConnectionPrivate::prepareRequest(), priority(), QHttpNetworkConnectionChannel::sendRequest(), setContentLength(), setCustomVerb(), setHeaderField(), setOperation(), setPipeliningAllowed(), setPriority(), setSsl(), setUploadByteDevice(), setUrl(), setWithCredentials(), uploadByteDevice(), url(), and withCredentials().
The documentation for this class was generated from the following files:
/src/network/access/qhttpnetworkrequest_p.h
/src/network/access/qhttpnetworkrequest.cpp