Qt 4.8: QPatternist::NamespaceBinding Class Reference
QPatternist::NamespaceBinding Class Reference
Represents a namespace binding: a prefix, and a namespace URI.
#include <qnamespacebinding_p.h>
Public Types
enum { InvalidCode = -1 }
typedef QVector< NamespaceBinding > Vector
Public Functions
bool isNull () const
NamespaceBinding ()
NamespaceBinding (const QXmlName::PrefixCode p, const QXmlName::NamespaceCode n)
QXmlName::NamespaceCode namespaceURI () const
bool operator== (const NamespaceBinding &other) const
QXmlName::PrefixCode prefix () const
Static Public Functions
static NamespaceBinding fromQXmlName (const QXmlName qName)
Constructs a NamespaceBinding whose prefix and namespace is taken from qName.
Properties
QXmlName::NamespaceCode m_namespace
QXmlName::PrefixCode m_prefix
Related Functions
(Note that these are not member functions.)
static uint qHash (const NamespaceBinding nb)
Detailed Description
Represents a namespace binding: a prefix, and a namespace URI.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 70 of file qnamespacebinding_p.h.
Typedefs
Vector
typedef QVector<NamespaceBinding> QPatternist::NamespaceBinding::Vector
Definition at line 78 of file qnamespacebinding_p.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
InvalidCode
Definition at line 73 of file qnamespacebinding_p.h.
         {
             InvalidCode = -1
         };
Constructors and Destructors
NamespaceBinding() [1/2]
QPatternist::NamespaceBinding::NamespaceBinding () inline
Definition at line 80 of file qnamespacebinding_p.h.
Referenced by fromQXmlName().
                                   : m_prefix(InvalidCode),
                                     m_namespace(InvalidCode)
         {
         }
NamespaceBinding() [2/2]
QPatternist::NamespaceBinding::NamespaceBinding (const QXmlName::PrefixCode p, const QXmlName::NamespaceCode n) inline
Definition at line 85 of file qnamespacebinding_p.h.
                                                                : m_prefix(p),
                                                                 m_namespace(n)
         {
         }
Functions
fromQXmlName()
static NamespaceBinding QPatternist::NamespaceBinding::fromQXmlName (const QXmlName qName) inline static
Constructs a NamespaceBinding whose prefix and namespace is taken from qName.
The local name in qName is ignored. qName may not be null.
Definition at line 118 of file qnamespacebinding_p.h.
         {
             Q_ASSERT(!qName.isNull());
             return NamespaceBinding(qName.prefix(), qName.namespaceURI());
         }
isNull()
bool QPatternist::NamespaceBinding::isNull () const inline
Definition at line 107 of file qnamespacebinding_p.h.
         {
             return m_prefix == InvalidCode;
         }
namespaceURI()
QXmlName::NamespaceCode QPatternist::NamespaceBinding::namespaceURI () const inline
Definition at line 102 of file qnamespacebinding_p.h.
Referenced by qHash().
         {
             return m_namespace;
         }
operator==()
bool QPatternist::NamespaceBinding::operator== (const NamespaceBinding & other) const inline
Definition at line 91 of file qnamespacebinding_p.h.
         {
             return m_prefix == other.m_prefix &&
                    m_namespace == other.m_namespace;
         }
prefix()
QXmlName::PrefixCode QPatternist::NamespaceBinding::prefix () const inline
Definition at line 97 of file qnamespacebinding_p.h.
Referenced by qHash().
         {
             return m_prefix;
         }
Friends and Related Functions
qHash()
static uint qHash (const NamespaceBinding nb) related
Definition at line 132 of file qnamespacebinding_p.h.
     {
         return (nb.prefix() << 16) + nb.namespaceURI();
     }
Properties
m_namespace
QXmlName::NamespaceCode QPatternist::NamespaceBinding::m_namespace private
Definition at line 126 of file qnamespacebinding_p.h.
Referenced by namespaceURI(), and operator==().
m_prefix
QXmlName::PrefixCode QPatternist::NamespaceBinding::m_prefix private
Definition at line 125 of file qnamespacebinding_p.h.
Referenced by isNull(), operator==(), and prefix().
The documentation for this class was generated from the following file:
/src/xmlpatterns/utils/qnamespacebinding_p.h