Qt 4.8: QSqlTableModelPrivate Class Reference
QSqlTableModelPrivate Class Reference
#include <qsqltablemodel_p.h>
Classes
struct ModifiedRow
Public Types
typedef QMap< int, ModifiedRow > CacheMap
enum Op { None, Insert, Update, Delete }
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
void clear ()
virtual void clearCache ()
virtual void clearEditBuffer ()
bool exec (const QString &stmt, bool prepStatement, const QSqlRecord &rec, const QSqlRecord &whereValues)
void initRecordAndPrimaryIndex ()
virtual int nameToIndex (const QString &name) const
QSqlRecord primaryValues (int index)
QSqlTableModelPrivate ()
QSqlRecord record (const QVector< QVariant > &values) const
Populates our record with values.
virtual void revertCachedRow (int row)
void revertInsertedRow ()
bool setRecord (int row, const QSqlRecord &record)
Set a record for OnFieldChange and OnRowChange.
Public Functions inherited from QSqlQueryModelPrivate
void initColOffsets (int size)
void prefetch (int)
QSqlQueryModelPrivate ()
~QSqlQueryModelPrivate ()
Public Functions inherited from QAbstractItemModelPrivate
bool allowMove (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation orientation)
Returns whether a move operation is valid.
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
QModelIndex createIndex (int row, int column, void *data=0) const
QModelIndex createIndex (int row, int column, int id) const
bool indexValid (const QModelIndex &index) const
void invalidatePersistentIndex (const QModelIndex &index)
void invalidatePersistentIndexes ()
void itemsAboutToBeMoved (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation)
void itemsMoved (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation orientation)
void movePersistentIndexes (QVector< QPersistentModelIndexData *> indexes, int change, const QModelIndex &parent, Qt::Orientation orientation)
Moves persistent indexes indexes by amount change.
QAbstractItemModelPrivate ()
void removePersistentIndexData (QPersistentModelIndexData *data)
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static void clearGenerated (QSqlRecord &rec)
static void setGeneratedValue (QSqlRecord &rec, int c, QVariant v)
Static Public Functions inherited from QAbstractItemModelPrivate
static const QHash< int, QByteArray > & defaultRoleNames ()
static QAbstractItemModel * staticEmptyModel ()
static bool variantLessThan (const QVariant &v1, const QVariant &v2)
This function is used by our Q{Tree,Widget,Table}WidgetModel classes to sort.
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
CacheMap cache
QSqlDatabase db
QSqlRecord editBuffer
int editIndex
QSqlQuery editQuery
QString filter
int insertIndex
QSqlIndex primaryIndex
int sortColumn
Qt::SortOrder sortOrder
QSqlTableModel::EditStrategy strategy
QString tableName
Public Variables inherited from QSqlQueryModelPrivate
uint atEnd: 1
QModelIndex bottom
QVarLengthArray< int, 56 > colOffsets
QSqlError error
QVector< QHash< int, QVariant > > headers
QSqlQuery query
QSqlRecord rec
Public Variables inherited from QAbstractItemModelPrivate
QStack< Change > changes
struct QAbstractItemModelPrivate::Persistent persistent
QHash< int, QByteArray > roleNames
Qt::DropActions supportedDragActions
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Detailed Description
Definition at line 61 of file qsqltablemodel_p.h.
Typedefs
CacheMap
typedef QMap<int, ModifiedRow> QSqlTableModelPrivate::CacheMap
Definition at line 114 of file qsqltablemodel_p.h.
Enumerations
Op
enum QSqlTableModelPrivate::Op
Enumerator
None
Insert
Update
Delete
Definition at line 101 of file qsqltablemodel_p.h.
 { None, Insert, Update, Delete };
Constructors and Destructors
QSqlTableModelPrivate()
QSqlTableModelPrivate::QSqlTableModelPrivate () inline
Definition at line 66 of file qsqltablemodel_p.h.
         : editIndex(-1), insertIndex(-1), sortColumn(-1),
           sortOrder(Qt::AscendingOrder),
           strategy(QSqlTableModel::OnRowChange)
     {}
Functions
clear()
void QSqlTableModelPrivate::clear (void)
Definition at line 121 of file qsqltablemodel.cpp.
Referenced by QSqlTableModelPrivate().
 {
     editIndex = -1;
     sortColumn = -1;
     sortOrder = Qt::AscendingOrder;
     tableName.clear();
     editQuery.clear();
     editBuffer.clear();
     cache.clear();
     primaryIndex.clear();
     rec.clear();
     filter.clear();
 }
clearCache()
void QSqlTableModelPrivate::clearCache () virtual
Reimplemented in QSqlRelationalTableModelPrivate.
Definition at line 152 of file qsqltablemodel.cpp.
Referenced by QSqlRelationalTableModelPrivate::clearCache(), and QSqlTableModelPrivate().
 {
     cache.clear();
 }
clearEditBuffer()
void QSqlTableModelPrivate::clearEditBuffer () virtual
Reimplemented in QSqlRelationalTableModelPrivate.
Definition at line 146 of file qsqltablemodel.cpp.
Referenced by QSqlTableModelPrivate().
 {
     editBuffer = rec;
     clearGenerated(editBuffer);
 }
clearGenerated()
void QSqlTableModelPrivate::clearGenerated (QSqlRecord & rec) static
Definition at line 157 of file qsqltablemodel.cpp.
Referenced by clearEditBuffer(), QSqlTableModelPrivate::ModifiedRow::ModifiedRow(), QSqlTableModelPrivate(), QSqlTableModel::setData(), and QSqlTableModel::setRecord().
 {
     for (int i = rec.count() - 1; i >= 0; i--)
         rec.setGenerated(i, false);
 }
exec()
bool QSqlTableModelPrivate::exec (const QString & stmt, bool prepStatement, const QSqlRecord & rec, const QSqlRecord & whereValues)
Definition at line 201 of file qsqltablemodel.cpp.
Referenced by QSqlTableModelPrivate().
 {
     if (stmt.isEmpty())
         return false;
     // lazy initialization of editQuery
     if (editQuery.driver() != db.driver())
         editQuery = QSqlQuery(db);
     // workaround for In-Process databases - remove all read locks
     // from the table to make sure the editQuery succeeds
     if (db.driver()->hasFeature(QSqlDriver::SimpleLocking))
         const_cast<QSqlResult *>(query.result())->detachFromResultSet();
     if (prepStatement) {
         if (editQuery.lastQuery() != stmt) {
             if (!editQuery.prepare(stmt)) {
                 error = editQuery.lastError();
                 return false;
             }
         }
         int i;
         for (i = 0; i < rec.count(); ++i) {
             if (rec.isGenerated(i))
                 editQuery.addBindValue(rec.value(i));
         }
         for (i = 0; i < whereValues.count(); ++i) {
             if (whereValues.isGenerated(i) && !whereValues.isNull(i))
                 editQuery.addBindValue(whereValues.value(i));
         }
         if (!editQuery.exec()) {
             error = editQuery.lastError();
             return false;
         }
     } else {
         if (!editQuery.exec(stmt)) {
             error = editQuery.lastError();
             return false;
         }
     }
     return true;
 }
initRecordAndPrimaryIndex()
void QSqlTableModelPrivate::initRecordAndPrimaryIndex ()
Definition at line 115 of file qsqltablemodel.cpp.
Referenced by QSqlTableModelPrivate().
 {
     rec = db.record(tableName);
     primaryIndex = db.primaryIndex(tableName);
 }
nameToIndex()
int QSqlTableModelPrivate::nameToIndex (const QString & name) const virtual
Reimplemented in QSqlRelationalTableModelPrivate.
Definition at line 107 of file qsqltablemodel.cpp.
Referenced by QSqlTableModelPrivate(), and setRecord().
 {
     QString fieldname = name;
     if (db.driver()->isIdentifierEscaped(fieldname, QSqlDriver::FieldName))
         fieldname = db.driver()->stripDelimiters(fieldname, QSqlDriver::FieldName);
     return rec.indexOf(fieldname);
 }
primaryValues()
QSqlRecord QSqlTableModelPrivate::primaryValues (int index)
Definition at line 246 of file qsqltablemodel.cpp.
Referenced by QSqlTableModelPrivate().
 {
     QSqlRecord record;
     if (!query.seek(row)) {
         error = query.lastError();
         return record;
     }
     if (primaryIndex.isEmpty()) {
         record = rec;
         for (int i = 0; i < record.count(); ++i)
             record.setValue(i, query.value(i));
     } else {
         record = primaryIndex;
         for (int i = 0; i < record.count(); ++i)
             record.setValue(i, query.value(rec.indexOf(record.fieldName(i))));
     }
     return record;
 }
record()
QSqlRecord QSqlTableModelPrivate::record (const QVector< QVariant > & values) const
Populates our record with values.
Warning
This function is not part of the public interface.
Definition at line 64 of file qsqltablemodel.cpp.
Referenced by primaryValues(), and QSqlTableModelPrivate().
 {
     QSqlRecord r = rec;
     for (int i = 0; i < r.count() && i < values.count(); ++i)
         r.setValue(i, values.at(i));
     return r;
 }
revertCachedRow()
void QSqlTableModelPrivate::revertCachedRow (int row) virtual
Reimplemented in QSqlRelationalTableModelPrivate.
Definition at line 169 of file qsqltablemodel.cpp.
Referenced by QSqlTableModelPrivate(), and QSqlRelationalTableModelPrivate::revertCachedRow().
 {
     Q_Q(QSqlTableModel);
     ModifiedRow r = cache.value(row);
     switch (r.op) {
     case QSqlTableModelPrivate::None:
         Q_ASSERT_X(false, "QSqlTableModelPrivate::revertCachedRow()", "Invalid entry in cache map");
         return;
     case QSqlTableModelPrivate::Update:
     case QSqlTableModelPrivate::Delete:
         cache.remove(row);
         emit q->dataChanged(q->createIndex(row, 0),
                             q->createIndex(row, q->columnCount() - 1));
         break;
     case QSqlTableModelPrivate::Insert: {
             QMap<int, QSqlTableModelPrivate::ModifiedRow>::Iterator it = cache.find(row);
             if (it == cache.end())
                 return;
             q->beginRemoveRows(QModelIndex(), row, row);
             it = cache.erase(it);
             while (it != cache.end()) {
                 int oldKey = it.key();
                 const QSqlTableModelPrivate::ModifiedRow oldValue = it.value();
                 cache.erase(it);
                 it = cache.insert(oldKey - 1, oldValue);
                 ++it;
             }
             q->endRemoveRows();
         break; }
     }
 }
revertInsertedRow()
void QSqlTableModelPrivate::revertInsertedRow ()
Definition at line 135 of file qsqltablemodel.cpp.
Referenced by QSqlTableModelPrivate().
 {
     Q_Q(QSqlTableModel);
     if (insertIndex == -1)
         return;
     q->beginRemoveRows(QModelIndex(), insertIndex, insertIndex);
     insertIndex = -1;
     q->endRemoveRows();
 }
setGeneratedValue()
void QSqlTableModelPrivate::setGeneratedValue (QSqlRecord & rec, int c, QVariant v) static
Definition at line 163 of file qsqltablemodel.cpp.
Referenced by QSqlTableModelPrivate(), and QSqlTableModel::setData().
 {
     rec.setValue(c, v);
     rec.setGenerated(c, true);
 }
setRecord()
bool QSqlTableModelPrivate::setRecord (int row, const QSqlRecord & record)
Set a record for OnFieldChange and OnRowChange.
Warning
This function is not part of the public interface.
Definition at line 78 of file qsqltablemodel.cpp.
Referenced by QSqlTableModelPrivate().
 {
     Q_Q(QSqlTableModel);
     bool isOk = true;
     QSqlTableModel::EditStrategy oldStrategy = strategy;
     // FieldChange strategy makes no sense when setting an entire row
     if (strategy == QSqlTableModel::OnFieldChange)
         strategy = QSqlTableModel::OnRowChange;
     for (int i = 0; i < record.count(); ++i) {
         if (!record.isGenerated(i))
             continue;
         int idx = nameToIndex(record.fieldName(i));
         if (idx == -1)
             continue;
         QModelIndex cIndex = q->createIndex(row, idx);
         QVariant value = record.value(i);
         QVariant oldValue = q->data(cIndex);
         if (oldValue.isNull() || oldValue != value)
             isOk &= q->setData(cIndex, value, Qt::EditRole);
     }
     if (isOk && oldStrategy == QSqlTableModel::OnFieldChange)
         q->submitAll();
     strategy = oldStrategy;
     return isOk;
 }
Properties
cache
CacheMap QSqlTableModelPrivate::cache
Definition at line 115 of file qsqltablemodel_p.h.
Referenced by clear(), clearCache(), and revertCachedRow().
db
QSqlDatabase QSqlTableModelPrivate::db
Definition at line 87 of file qsqltablemodel_p.h.
Referenced by exec(), initRecordAndPrimaryIndex(), and nameToIndex().
editBuffer
QSqlRecord QSqlTableModelPrivate::editBuffer
Definition at line 112 of file qsqltablemodel_p.h.
Referenced by clear(), and clearEditBuffer().
editIndex
int QSqlTableModelPrivate::editIndex
Definition at line 88 of file qsqltablemodel_p.h.
Referenced by clear().
editQuery
QSqlQuery QSqlTableModelPrivate::editQuery
Definition at line 96 of file qsqltablemodel_p.h.
Referenced by clear(), and exec().
filter
QString QSqlTableModelPrivate::filter
Definition at line 99 of file qsqltablemodel_p.h.
Referenced by clear().
insertIndex
int QSqlTableModelPrivate::insertIndex
Definition at line 89 of file qsqltablemodel_p.h.
Referenced by revertInsertedRow().
primaryIndex
QSqlIndex QSqlTableModelPrivate::primaryIndex
Definition at line 97 of file qsqltablemodel_p.h.
Referenced by clear(), initRecordAndPrimaryIndex(), and primaryValues().
sortColumn
int QSqlTableModelPrivate::sortColumn
Definition at line 91 of file qsqltablemodel_p.h.
Referenced by clear().
sortOrder
Qt::SortOrder QSqlTableModelPrivate::sortOrder
Definition at line 92 of file qsqltablemodel_p.h.
Referenced by clear().
strategy
QSqlTableModel::EditStrategy QSqlTableModelPrivate::strategy
Definition at line 94 of file qsqltablemodel_p.h.
Referenced by setRecord().
tableName
QString QSqlTableModelPrivate::tableName
Definition at line 98 of file qsqltablemodel_p.h.
Referenced by clear(), and initRecordAndPrimaryIndex().
The documentation for this class was generated from the following files:
/src/sql/models/qsqltablemodel_p.h
/src/sql/models/qsqltablemodel.cpp