Qt 4.8: QGraphicsTransform Class Reference
QGraphicsTransform Class Reference abstract
The QGraphicsTransform class is an abstract base class for building advanced transformations on QGraphicsItems.
#include <qgraphicstransform.h>
Public Functions
virtual void applyTo (QMatrix4x4 *matrix) const =0
This pure virtual method has to be reimplemented in derived classes.
QGraphicsTransform (QObject *parent=0)
Constructs a new QGraphicsTransform with the given parent.
~QGraphicsTransform ()
Destroys the graphics transform.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Slots
void update ()
Notifies that this transform operation has changed its parameters in such a way that applyTo() will return a different result than before.
Protected Functions
QGraphicsTransform (QGraphicsTransformPrivate &p, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Friends
class QGraphicsItem
class QGraphicsItemPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGraphicsTransform class is an abstract base class for building advanced transformations on QGraphicsItems.
Since
4.6
As an alternative to QGraphicsItem::transform, QGraphicsTransform lets you create and control advanced transformations that can be configured independently using specialized properties.
QGraphicsItem allows you to assign any number of QGraphicsTransform instances to one QGraphicsItem. Each QGraphicsTransform is applied in order, one at a time, to the QGraphicsItem it's assigned to.
QGraphicsTransform is particularly useful for animations. Whereas QGraphicsItem::setTransform() lets you assign any transform directly to an item, there is no direct way to interpolate between two different transformations (e.g., when transitioning between two states, each for which the item has a different arbitrary transform assigned). Using QGraphicsTransform you can interpolate the property values of each independent transformation. The resulting operation is then combined into a single transform which is applied to QGraphicsItem.
Transformations are computed in true 3D space using QMatrix4x4. When the transformation is applied to a QGraphicsItem, it will be projected back to a 2D QTransform. When multiple QGraphicsTransform objects are applied to a QGraphicsItem, all of the transformations are computed in true 3D space, with the projection back to 2D only occurring after the last QGraphicsTransform is applied. The exception to this is QGraphicsRotation, which projects back to 2D after each rotation to preserve the perspective effect around the X and Y axes.
If you want to create your own configurable transformation, you can create a subclass of QGraphicsTransform (or any or the existing subclasses), and reimplement the pure virtual applyTo() function, which takes a pointer to a QMatrix4x4. Each operation you would like to apply should be exposed as properties (e.g., customTransform->setVerticalShear(2.5)). Inside you reimplementation of applyTo(), you can modify the provided transform respectively.
QGraphicsTransform can be used together with QGraphicsItem::setTransform(), QGraphicsItem::setRotation(), and QGraphicsItem::setScale().
See also
QGraphicsItem::transform(), QGraphicsScale, QGraphicsRotation
Definition at line 60 of file qgraphicstransform.h.
Constructors and Destructors
QGraphicsTransform() [1/2]
QGraphicsTransform::QGraphicsTransform (QObject * parent = 0)
Constructs a new QGraphicsTransform with the given parent.
Definition at line 130 of file qgraphicstransform.cpp.
     : QObject(*new QGraphicsTransformPrivate, parent)
 {
 }
~QGraphicsTransform()
QGraphicsTransform::~QGraphicsTransform ()
Destroys the graphics transform.
Definition at line 138 of file qgraphicstransform.cpp.
 {
     Q_D(QGraphicsTransform);
     d->setItem(0);
 }
QGraphicsTransform() [2/2]
QGraphicsTransform::QGraphicsTransform (QGraphicsTransformPrivate & p, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 147 of file qgraphicstransform.cpp.
     : QObject(p, parent)
 {
 }
Functions
applyTo()
void QGraphicsTransform::applyTo (QMatrix4x4 * matrix) const pure virtual
This pure virtual method has to be reimplemented in derived classes.
It applies this transformation to matrix.
See also
QGraphicsItem::transform(), QMatrix4x4::toTransform()
Implemented in QGraphicsRotation, QGraphicsScale, and QDeclarativeTranslate.
Referenced by QGraphicsItemGroup::addToGroup(), QGraphicsItemPrivate::TransformData::computedFullTransform(), and QGraphicsItemGroup::removeFromGroup().
update
void QGraphicsTransform::update () protected slot
Notifies that this transform operation has changed its parameters in such a way that applyTo() will return a different result than before.
When implementing you own custom graphics transform, you must call this function every time you change a parameter, to let QGraphicsItem know that its transformation needs to be updated.
See also
applyTo()
Definition at line 172 of file qgraphicstransform.cpp.
Referenced by QGraphicsRotation::setAngle(), QGraphicsRotation::setAxis(), QGraphicsScale::setOrigin(), QGraphicsRotation::setOrigin(), QDeclarativeTranslate::setX(), QGraphicsScale::setXScale(), QDeclarativeTranslate::setY(), QGraphicsScale::setYScale(), and QGraphicsScale::setZScale().
 {
     Q_D(QGraphicsTransform);
     if (d->item)
         d->updateItem(d->item);
 }
Friends and Related Functions
QGraphicsItem
friend class QGraphicsItem friend
Definition at line 76 of file qgraphicstransform.h.
QGraphicsItemPrivate
friend class QGraphicsItemPrivate friend
Definition at line 77 of file qgraphicstransform.h.
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicstransform.h
/src/gui/graphicsview/qgraphicstransform.cpp