Qt 4.8: QBasicMouseEventTransition Class Reference
QBasicMouseEventTransition Class Reference
The QBasicMouseEventTransition class provides a transition for Qt mouse events.
#include <qbasicmouseeventtransition_p.h>
Public Functions
Qt::MouseButton button () const
Returns the button that this mouse event transition checks for.
QEvent::Type eventType () const
Returns the event type that this mouse event transition is associated with.
QPainterPath hitTestPath () const
Returns the hit test path for this mouse event transition.
Qt::KeyboardModifiers modifierMask () const
Returns the keyboard modifier mask that this mouse event transition checks for.
QBasicMouseEventTransition (QState *sourceState=0)
Constructs a new mouse event transition with the given sourceState.
QBasicMouseEventTransition (QEvent::Type type, Qt::MouseButton button, QState *sourceState=0)
Constructs a new mouse event transition for events of the given type.
void setButton (Qt::MouseButton button)
Sets the button that this mouse event transition will check for.
void setEventType (QEvent::Type type)
Sets the event type that this mouse event transition is associated with.
void setHitTestPath (const QPainterPath &path)
Sets the hit test path for this mouse event transition.
void setModifierMask (Qt::KeyboardModifiers modifiers)
Sets the keyboard modifier mask that this mouse event transition will check for.
~QBasicMouseEventTransition ()
Destroys this mouse event transition.
Public Functions inherited from QAbstractTransition
void addAnimation (QAbstractAnimation *animation)
Adds the given animation to this transition.
QList< QAbstractAnimation * > animations () const
Returns the list of animations associated with this transition, or an empty list if it has no animations.
QStateMachine * machine () const
Returns the state machine that this transition is part of, or 0 if the transition is not part of a state machine.
QAbstractTransition (QState *sourceState=0)
Constructs a new QAbstractTransition object with the given sourceState.
void removeAnimation (QAbstractAnimation *animation)
Removes the given animation from this transition.
void setTargetState (QAbstractState *target)
Sets the target state of this transition.
void setTargetStates (const QList< QAbstractState *> &targets)
Sets the target states of this transition to be the given targets.
QState * sourceState () const
QAbstractState * targetState () const
QList< QAbstractState * > targetStates () const
virtual ~QAbstractTransition ()
Destroys this transition.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool eventTest (QEvent *event)
Reimplemented Function
void onTransition (QEvent *)
Reimplemented Function
Protected Functions inherited from QAbstractTransition
bool event (QEvent *e)
Reimplemented Function
QAbstractTransition (QAbstractTransitionPrivate &dd, QState *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractTransition
void triggered ()
This signal is emitted when the transition has been triggered (after onTransition() has been called).
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QBasicMouseEventTransition class provides a transition for Qt mouse events.
Warning
This function is not part of the public interface.
Since
4.6
Definition at line 67 of file qbasicmouseeventtransition_p.h.
Constructors and Destructors
QBasicMouseEventTransition() [1/2]
QBasicMouseEventTransition::QBasicMouseEventTransition (QState * sourceState = 0)
Constructs a new mouse event transition with the given sourceState.
Definition at line 93 of file qbasicmouseeventtransition.cpp.
     : QAbstractTransition(*new QBasicMouseEventTransitionPrivate, sourceState)
 {
 }
QBasicMouseEventTransition() [2/2]
QBasicMouseEventTransition::QBasicMouseEventTransition (QEvent::Type type, Qt::MouseButton button, QState * sourceState = 0)
Constructs a new mouse event transition for events of the given type.
Definition at line 101 of file qbasicmouseeventtransition.cpp.
     : QAbstractTransition(*new QBasicMouseEventTransitionPrivate, sourceState)
 {
     Q_D(QBasicMouseEventTransition);
     d->eventType = type;
     d->button = button;
 }
~QBasicMouseEventTransition()
QBasicMouseEventTransition::~QBasicMouseEventTransition ()
Destroys this mouse event transition.
Definition at line 114 of file qbasicmouseeventtransition.cpp.
 {
 }
Functions
button()
Qt::MouseButton QBasicMouseEventTransition::button () const
Returns the button that this mouse event transition checks for.
Definition at line 139 of file qbasicmouseeventtransition.cpp.
Referenced by QBasicMouseEventTransition(), and setButton().
 {
     Q_D(const QBasicMouseEventTransition);
     return d->button;
 }
eventTest()
bool QBasicMouseEventTransition::eventTest (QEvent * event) protected virtual
Reimplemented Function
Implements QAbstractTransition.
Definition at line 195 of file qbasicmouseeventtransition.cpp.
 {
     Q_D(const QBasicMouseEventTransition);
     if (event->type() == d->eventType) {
         QMouseEvent *me = static_cast<QMouseEvent*>(event);
         return (me->button() == d->button)
             && ((me->modifiers() & d->modifierMask) == d->modifierMask)
             && (d->path.isEmpty() || d->path.contains(me->pos()));
     }
     return false;
 }
eventType()
QEvent::Type QBasicMouseEventTransition::eventType () const
Returns the event type that this mouse event transition is associated with.
Definition at line 121 of file qbasicmouseeventtransition.cpp.
 {
     Q_D(const QBasicMouseEventTransition);
     return d->eventType;
 }
hitTestPath()
QPainterPath QBasicMouseEventTransition::hitTestPath () const
Returns the hit test path for this mouse event transition.
Definition at line 177 of file qbasicmouseeventtransition.cpp.
 {
     Q_D(const QBasicMouseEventTransition);
     return d->path;
 }
modifierMask()
Qt::KeyboardModifiers QBasicMouseEventTransition::modifierMask () const
Returns the keyboard modifier mask that this mouse event transition checks for.
Definition at line 158 of file qbasicmouseeventtransition.cpp.
Referenced by setModifierMask().
 {
     Q_D(const QBasicMouseEventTransition);
     return d->modifierMask;
 }
onTransition()
void QBasicMouseEventTransition::onTransition (QEvent *) protected virtual
Reimplemented Function
Implements QAbstractTransition.
Definition at line 210 of file qbasicmouseeventtransition.cpp.
 {
 }
setButton()
void QBasicMouseEventTransition::setButton (Qt::MouseButton button)
Sets the button that this mouse event transition will check for.
Definition at line 148 of file qbasicmouseeventtransition.cpp.
 {
     Q_D(QBasicMouseEventTransition);
     d->button = button;
 }
setEventType()
void QBasicMouseEventTransition::setEventType (QEvent::Type type)
Sets the event type that this mouse event transition is associated with.
Definition at line 130 of file qbasicmouseeventtransition.cpp.
 {
     Q_D(QBasicMouseEventTransition);
     d->eventType = type;
 }
setHitTestPath()
void QBasicMouseEventTransition::setHitTestPath (const QPainterPath & path)
Sets the hit test path for this mouse event transition.
Definition at line 186 of file qbasicmouseeventtransition.cpp.
 {
     Q_D(QBasicMouseEventTransition);
     d->path = path;
 }
setModifierMask()
void QBasicMouseEventTransition::setModifierMask (Qt::KeyboardModifiers modifiers)
Sets the keyboard modifier mask that this mouse event transition will check for.
Definition at line 168 of file qbasicmouseeventtransition.cpp.
 {
     Q_D(QBasicMouseEventTransition);
     d->modifierMask = modifierMask;
 }
The documentation for this class was generated from the following files:
/src/gui/statemachine/qbasicmouseeventtransition_p.h
/src/gui/statemachine/qbasicmouseeventtransition.cpp