Qt 4.8: QCoreTextFontEngine Class Reference
QCoreTextFontEngine Class Reference
#include <qfontengine_coretext_p.h>
Public Functions
virtual void addGlyphsToPath (glyph_t *glyphs, QFixedPoint *positions, int numGlyphs, QPainterPath *path, QTextItem::RenderFlags)
virtual QImage alphaMapForGlyph (glyph_t, QFixed subPixelPosition)
virtual QImage alphaRGBMapForGlyph (glyph_t, QFixed subPixelPosition, int margin, const QTransform &t)
virtual QFixed ascent () const
virtual QFixed averageCharWidth () const
virtual glyph_metrics_t boundingBox (const QGlyphLayout &glyphs)
virtual glyph_metrics_t boundingBox (glyph_t glyph)
virtual bool canRender (const QChar *string, int len)
virtual QFontEngine * cloneWithSize (qreal pixelSize) const
virtual QFixed descent () const
void draw (CGContextRef ctx, qreal x, qreal y, const QTextItemInt &ti, int paintDeviceHeight)
virtual QFixed emSquareSize () const
virtual FaceId faceId () const
virtual bool getSfntTableData (uint, uchar *, uint *) const
virtual void getUnscaledGlyph (glyph_t glyph, QPainterPath *path, glyph_metrics_t *metrics)
virtual QFixed leading () const
virtual qreal maxCharWidth () const
virtual qreal minLeftBearing () const
virtual qreal minRightBearing () const
virtual const char * name () const
QCoreTextFontEngine (CTFontRef font, const QFontDef &def)
QCoreTextFontEngine (CGFontRef font, const QFontDef &def)
virtual void recalcAdvances (QGlyphLayout *, QTextEngine::ShaperFlags) const
virtual bool stringToCMap (const QChar *str, int len, QGlyphLayout *glyphs, int *nglyphs, QTextEngine::ShaperFlags flags) const
virtual bool supportsSubPixelPositions () const
virtual int synthesized () const
virtual Type type () const
virtual QFixed xHeight () const
~QCoreTextFontEngine ()
Public Functions inherited from QFontEngine
void addBitmapFontToPath (qreal x, qreal y, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags)
virtual void addOutlineToPath (qreal, qreal, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags flags)
virtual glyph_metrics_t alphaMapBoundingBox (glyph_t glyph, QFixed, const QTransform &matrix, GlyphFormat)
virtual QImage alphaMapForGlyph (glyph_t)
virtual QImage alphaMapForGlyph (glyph_t, const QTransform &t)
virtual QImage alphaMapForGlyph (glyph_t, QFixed subPixelPosition, const QTransform &t)
virtual glyph_metrics_t boundingBox (glyph_t glyph, const QTransform &matrix)
virtual void doKerning (QGlyphLayout *, QTextEngine::ShaperFlags) const
virtual void getGlyphBearings (glyph_t glyph, qreal *leftBearing=0, qreal *rightBearing=0)
void getGlyphPositions (const QGlyphLayout &glyphs, const QTransform &matrix, QTextItem::RenderFlags flags, QVarLengthArray< glyph_t > &glyphs_out, QVarLengthArray< QFixedPoint > &positions)
virtual HB_Error getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed *xpos, HB_Fixed *ypos, hb_uint32 *nPoints)
QByteArray getSfntTable (uint) const
QFontEngineGlyphCache * glyphCache (void *key, QFontEngineGlyphCache::Type type, const QTransform &transform) const
virtual int glyphCount () const
HB_Face harfbuzzFace () const
HB_Font harfbuzzFont () const
virtual QFixed lineThickness () const
void loadKerningPairs (QFixed scalingFactor)
virtual Properties properties () const
QFontEngine ()
virtual void removeGlyphFromCache (glyph_t)
void setGlyphCache (void *key, QFontEngineGlyphCache *data)
glyph_metrics_t tightBoundingBox (const QGlyphLayout &glyphs)
virtual QFixed underlinePosition () const
virtual ~QFontEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
QImage imageForGlyph (glyph_t glyph, QFixed subPixelPosition, int margin, bool colorful)
void init ()
Properties
QFixed avgCharWidth
CGFontRef cgFont
CTFontRef ctfont
int synthesisFlags
CGAffineTransform transform
Friends
class QCoreTextFontEngineMulti
class QRawFontPrivate
Additional Inherited Members
Public Types inherited from QFontEngine
enum GlyphFormat {
Format_None, Format_Render = Format_None, Format_Mono, Format_A8,
Format_A32
}
enum SynthesizedFlags { SynthesizedItalic = 0x1, SynthesizedBold = 0x2, SynthesizedStretch = 0x4 }
enum Type {
Box, Multi, XLFD, Win,
Mac, Freetype, QPF1, QPF2,
Proxy, S60FontEngine, DirectWrite, TestFontEngine = 0x1000
}
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QFontEngine
static QByteArray convertToPostscriptFontFamilyName (const QByteArray &fontFamily)
static const uchar * getCMap (const uchar *table, uint tableSize, bool *isSymbolFont, int *cmapSize)
static quint32 getTrueTypeGlyphIndex (const uchar *cmap, uint unicode)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables inherited from QFontEngine
uint cache_cost
int cache_count
QFontDef fontDef
uint fsType: 16
int glyphFormat
HB_Face hbFace
HB_FontRec hbFont
QVector< KernPair > kerning_pairs
QAtomicInt ref
bool symbol
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QFontEngine
QFixed lastRightBearing (const QGlyphLayout &glyphs, bool round=false)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Protected Functions inherited from QFontEngine
static const QVector< QRgb > & grayPalette ()
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 61 of file qfontengine_coretext_p.h.
Constructors and Destructors
QCoreTextFontEngine() [1/2]
QCoreTextFontEngine::QCoreTextFontEngine (CTFontRef font, const QFontDef & def)
QCoreTextFontEngine() [2/2]
QCoreTextFontEngine::QCoreTextFontEngine (CGFontRef font, const QFontDef & def)
~QCoreTextFontEngine()
QCoreTextFontEngine::~QCoreTextFontEngine ()
Functions
addGlyphsToPath()
virtual void QCoreTextFontEngine::addGlyphsToPath (glyph_t * glyphs, QFixedPoint * positions, int numGlyphs, QPainterPath * path, QTextItem::RenderFlags) virtual
Reimplemented from QFontEngine.
alphaMapForGlyph()
virtual QImage QCoreTextFontEngine::alphaMapForGlyph (glyph_t , QFixed subPixelPosition) virtual
Reimplemented from QFontEngine.
Referenced by type().
alphaRGBMapForGlyph()
virtual QImage QCoreTextFontEngine::alphaRGBMapForGlyph (glyph_t , QFixed subPixelPosition, int margin, const QTransform & t) virtual
Reimplemented from QFontEngine.
Referenced by type().
ascent()
virtual QFixed QCoreTextFontEngine::ascent () const virtual
Implements QFontEngine.
averageCharWidth()
virtual QFixed QCoreTextFontEngine::averageCharWidth () const virtual
Reimplemented from QFontEngine.
boundingBox() [1/2]
virtual glyph_metrics_t QCoreTextFontEngine::boundingBox (const QGlyphLayout & glyphs) virtual
Implements QFontEngine.
boundingBox() [2/2]
virtual glyph_metrics_t QCoreTextFontEngine::boundingBox (glyph_t glyph) virtual
Implements QFontEngine.
canRender()
virtual bool QCoreTextFontEngine::canRender (const QChar * string, int len) virtual
Implements QFontEngine.
Referenced by name().
cloneWithSize()
virtual QFontEngine* QCoreTextFontEngine::cloneWithSize (qreal pixelSize) const virtual
Reimplemented from QFontEngine.
Referenced by type().
descent()
virtual QFixed QCoreTextFontEngine::descent () const virtual
Implements QFontEngine.
draw()
void QCoreTextFontEngine::draw (CGContextRef ctx, qreal x, qreal y, const QTextItemInt & ti, int paintDeviceHeight)
Referenced by type().
emSquareSize()
virtual QFixed QCoreTextFontEngine::emSquareSize () const virtual
Reimplemented from QFontEngine.
Referenced by type().
faceId()
virtual FaceId QCoreTextFontEngine::faceId () const virtual
Reimplemented from QFontEngine.
Referenced by type().
getSfntTableData()
virtual bool QCoreTextFontEngine::getSfntTableData (uint , uchar * , uint *) const virtual
Reimplemented from QFontEngine.
Referenced by type().
getUnscaledGlyph()
virtual void QCoreTextFontEngine::getUnscaledGlyph (glyph_t glyph, QPainterPath * path, glyph_metrics_t * metrics) virtual
Reimplemented from QFontEngine.
Referenced by type().
imageForGlyph()
QImage QCoreTextFontEngine::imageForGlyph (glyph_t glyph, QFixed subPixelPosition, int margin, bool colorful) private
init()
void QCoreTextFontEngine::init () private
Referenced by QCoreTextFontEngineMulti::macFontID().
leading()
virtual QFixed QCoreTextFontEngine::leading () const virtual
Implements QFontEngine.
maxCharWidth()
virtual qreal QCoreTextFontEngine::maxCharWidth () const virtual
Implements QFontEngine.
minLeftBearing()
virtual qreal QCoreTextFontEngine::minLeftBearing () const virtual
Reimplemented from QFontEngine.
Referenced by type().
minRightBearing()
virtual qreal QCoreTextFontEngine::minRightBearing () const virtual
Reimplemented from QFontEngine.
Referenced by type().
name()
virtual const char* QCoreTextFontEngine::name () const inline virtual
Implements QFontEngine.
Definition at line 84 of file qfontengine_coretext_p.h.
 { return "QCoreTextFontEngine"; }
recalcAdvances()
virtual void QCoreTextFontEngine::recalcAdvances (QGlyphLayout * , QTextEngine::ShaperFlags) const virtual
This is a callback from harfbuzz. The font engine uses the font-system in use to find out the advances of each glyph and set it on the layout.
Reimplemented from QFontEngine.
stringToCMap()
virtual bool QCoreTextFontEngine::stringToCMap (const QChar * str, int len, QGlyphLayout * glyphs, int * nglyphs, QTextEngine::ShaperFlags flags) const virtual
Implements QFontEngine.
supportsSubPixelPositions()
virtual bool QCoreTextFontEngine::supportsSubPixelPositions () const inline virtual
Reimplemented from QFontEngine.
Definition at line 89 of file qfontengine_coretext_p.h.
 { return true; }
synthesized()
virtual int QCoreTextFontEngine::synthesized () const inline virtual
Reimplemented from QFontEngine.
Definition at line 88 of file qfontengine_coretext_p.h.
 { return synthesisFlags; }
type()
virtual Type QCoreTextFontEngine::type () const inline virtual
Implements QFontEngine.
Definition at line 91 of file qfontengine_coretext_p.h.
 { return QFontEngine::Mac; }
xHeight()
virtual QFixed QCoreTextFontEngine::xHeight () const virtual
Reimplemented from QFontEngine.
Friends and Related Functions
QCoreTextFontEngineMulti
friend class QCoreTextFontEngineMulti friend
Definition at line 116 of file qfontengine_coretext_p.h.
QRawFontPrivate
friend class QRawFontPrivate friend
Definition at line 107 of file qfontengine_coretext_p.h.
Properties
avgCharWidth
QFixed QCoreTextFontEngine::avgCharWidth private
Definition at line 115 of file qfontengine_coretext_p.h.
cgFont
CGFontRef QCoreTextFontEngine::cgFont private
Definition at line 112 of file qfontengine_coretext_p.h.
ctfont
CTFontRef QCoreTextFontEngine::ctfont private
Definition at line 111 of file qfontengine_coretext_p.h.
Referenced by QCoreTextFontEngineMulti::macFontID().
synthesisFlags
int QCoreTextFontEngine::synthesisFlags private
Definition at line 113 of file qfontengine_coretext_p.h.
Referenced by synthesized().
transform
CGAffineTransform QCoreTextFontEngine::transform private
Definition at line 114 of file qfontengine_coretext_p.h.
The documentation for this class was generated from the following file:
/src/gui/text/qfontengine_coretext_p.h