Qt 4.8: QNetworkManagerInterfaceAccessPoint Class Reference
QNetworkManagerInterfaceAccessPoint Class Reference
#include <qnetworkmanagerservice.h>
Public Types
enum ApFlag { ApNone = 0x0, Privacy = 0x1 }
enum ApSecurityFlag {
ApSecurityNone = 0x0, PairWep40 = 0x1, PairWep104 = 0x2, PairTkip = 0x4,
PairCcmp = 0x8, GroupWep40 = 0x10, GroupWep104 = 0x20, GroupTkip = 0x40,
GroupCcmp = 0x80, KeyPsk = 0x100, Key8021x = 0x200
}
enum DeviceState {
Unknown = 0, Unmanaged, Unavailable, Disconnected,
Prepare, Config, NeedAuthentication, IpConfig,
Activated, Failed
}
Signals
void propertiesChanged (QMap< QString, QVariant >)
void propertiesChanged (const QString &, QMap< QString, QVariant >)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDBusInterface * connectionInterface () const
quint32 flags () const
quint32 frequency () const
QString hwAddress () const
bool isValid ()
quint32 maxBitrate () const
quint32 mode () const
Q_DECLARE_FLAGS (ApFlags, ApFlag)
Q_DECLARE_FLAGS (ApSecurityFlags, ApSecurityFlag)
QNetworkManagerInterfaceAccessPoint (const QString &dbusPathName, QObject *parent=0)
quint32 rsnFlags () const
bool setConnections ()
QString ssid () const
quint32 strength () const
quint32 wpaFlags () const
~QNetworkManagerInterfaceAccessPoint ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QNetworkManagerInterfaceAccessPointPrivate * d
QNmDBusHelper * nmDBusHelper
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 176 of file qnetworkmanagerservice.h.
Enumerations
ApFlag
enum QNetworkManagerInterfaceAccessPoint::ApFlag
Enumerator
ApNone
Privacy
Definition at line 195 of file qnetworkmanagerservice.h.
                 {
         ApNone = 0x0,
         Privacy = 0x1
     };
ApSecurityFlag
enum QNetworkManagerInterfaceAccessPoint::ApSecurityFlag
Enumerator
ApSecurityNone
PairWep40
PairWep104
PairTkip
PairCcmp
GroupWep40
GroupWep104
GroupTkip
GroupCcmp
KeyPsk
Key8021x
Definition at line 202 of file qnetworkmanagerservice.h.
{
         ApSecurityNone = 0x0,
         PairWep40 = 0x1,
         PairWep104 = 0x2,
         PairTkip = 0x4,
         PairCcmp = 0x8,
         GroupWep40 = 0x10,
         GroupWep104 = 0x20,
         GroupTkip = 0x40,
         GroupCcmp = 0x80,
         KeyPsk = 0x100,
         Key8021x = 0x200
     };
DeviceState
enum QNetworkManagerInterfaceAccessPoint::DeviceState
Enumerator
Unknown
Unmanaged
Unavailable
Disconnected
Prepare
Config
NeedAuthentication
IpConfig
Activated
Failed
Definition at line 182 of file qnetworkmanagerservice.h.
                      {
         Unknown = 0,
         Unmanaged,
         Unavailable,
         Disconnected,
         Prepare,
         Config,
         NeedAuthentication,
         IpConfig,
         Activated,
         Failed
     };
Constructors and Destructors
QNetworkManagerInterfaceAccessPoint()
QNetworkManagerInterfaceAccessPoint::QNetworkManagerInterfaceAccessPoint (const QString & dbusPathName, QObject * parent = 0) explicit
Definition at line 193 of file qnetworkmanagerservice.cpp.
         : QObject(parent), nmDBusHelper(0)
 {
     d = new QNetworkManagerInterfaceAccessPointPrivate();
     d->path = dbusPathName;
     d->connectionInterface = new QDBusInterface(QLatin1String(NM_DBUS_SERVICE),
                                                 d->path,
                                                 QLatin1String(NM_DBUS_INTERFACE_ACCESS_POINT),
                                                 dbusConnection);
     if (!d->connectionInterface->isValid()) {
         d->valid = false;
         return;
     }
     d->valid = true;
 }
~QNetworkManagerInterfaceAccessPoint()
QNetworkManagerInterfaceAccessPoint::~QNetworkManagerInterfaceAccessPoint ()
Definition at line 210 of file qnetworkmanagerservice.cpp.
 {
     delete d->connectionInterface;
     delete d;
 }
Functions
connectionInterface()
QDBusInterface * QNetworkManagerInterfaceAccessPoint::connectionInterface () const
Definition at line 243 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::hasIdentifier(), QNetworkManagerEngine::parseConnection(), and QNetworkManagerEngine::removeAccessPoint().
 {
     return d->connectionInterface;
 }
flags()
quint32 QNetworkManagerInterfaceAccessPoint::flags () const
Definition at line 248 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::newAccessPoint().
 {
     return d->connectionInterface->property("Flags").toUInt();
 }
frequency()
quint32 QNetworkManagerInterfaceAccessPoint::frequency () const
Definition at line 268 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("Frequency").toUInt();
 }
hwAddress()
QString QNetworkManagerInterfaceAccessPoint::hwAddress () const
Definition at line 273 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("HwAddress").toString();
 }
isValid()
bool QNetworkManagerInterfaceAccessPoint::isValid ()
Definition at line 216 of file qnetworkmanagerservice.cpp.
Referenced by setConnections().
 {
     return d->valid;
 }
maxBitrate()
quint32 QNetworkManagerInterfaceAccessPoint::maxBitrate () const
Definition at line 283 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("MaxBitrate").toUInt();
 }
mode()
quint32 QNetworkManagerInterfaceAccessPoint::mode () const
Definition at line 278 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("Mode").toUInt();
 }
propertiesChanged [1/2]
void QNetworkManagerInterfaceAccessPoint::propertiesChanged (QMap< QString, QVariant >) signal
Referenced by setConnections().
propertiesChanged [2/2]
void QNetworkManagerInterfaceAccessPoint::propertiesChanged (const QString & , QMap< QString, QVariant >) signal
Q_DECLARE_FLAGS() [1/2]
QNetworkManagerInterfaceAccessPoint::Q_DECLARE_FLAGS (ApFlags , ApFlag)
Q_DECLARE_FLAGS() [2/2]
QNetworkManagerInterfaceAccessPoint::Q_DECLARE_FLAGS (ApSecurityFlags , ApSecurityFlag)
rsnFlags()
quint32 QNetworkManagerInterfaceAccessPoint::rsnFlags () const
Definition at line 258 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("RsnFlags").toUInt();
 }
setConnections()
bool QNetworkManagerInterfaceAccessPoint::setConnections ()
Definition at line 221 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::newAccessPoint().
 {
     if(!isValid() )
         return false;
     bool allOk = false;
     delete nmDBusHelper;
     nmDBusHelper = new QNmDBusHelper(this);
     connect(nmDBusHelper, SIGNAL(pathForPropertiesChanged(const QString &,QMap<QString,QVariant>)),
             this,SIGNAL(propertiesChanged( const QString &, QMap<QString,QVariant>)));
     if(dbusConnection.connect(QLatin1String(NM_DBUS_SERVICE),
                               d->path,
                               QLatin1String(NM_DBUS_INTERFACE_ACCESS_POINT),
                               QLatin1String("PropertiesChanged"),
                               nmDBusHelper,SLOT(slotPropertiesChanged( QMap<QString,QVariant>))) ) {
         allOk = true;
     }
     return allOk;
 }
ssid()
QString QNetworkManagerInterfaceAccessPoint::ssid () const
Definition at line 263 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::newAccessPoint(), QNetworkManagerEngine::parseConnection(), QNetworkManagerEngine::removeAccessPoint(), and QNetworkManagerEngine::updateAccessPoint().
 {
     return d->connectionInterface->property("Ssid").toString();
 }
strength()
quint32 QNetworkManagerInterfaceAccessPoint::strength () const
Definition at line 288 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("Strength").toUInt();
 }
wpaFlags()
quint32 QNetworkManagerInterfaceAccessPoint::wpaFlags () const
Definition at line 253 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("WpaFlags").toUInt();
 }
Properties
d
QNetworkManagerInterfaceAccessPointPrivate* QNetworkManagerInterfaceAccessPoint::d private
Definition at line 239 of file qnetworkmanagerservice.h.
Referenced by connectionInterface(), flags(), frequency(), hwAddress(), isValid(), maxBitrate(), mode(), QNetworkManagerInterfaceAccessPoint(), rsnFlags(), setConnections(), ssid(), strength(), wpaFlags(), and ~QNetworkManagerInterfaceAccessPoint().
nmDBusHelper
QNmDBusHelper* QNetworkManagerInterfaceAccessPoint::nmDBusHelper private
Definition at line 240 of file qnetworkmanagerservice.h.
Referenced by setConnections().
The documentation for this class was generated from the following files:
/src/plugins/bearer/networkmanager/qnetworkmanagerservice.h
/src/plugins/bearer/networkmanager/qnetworkmanagerservice.cpp