Qt 4.8: QSQLiteDriver Class Reference
QSQLiteDriver Class Reference
#include <qsql_sqlite.h>
Public Functions
bool beginTransaction ()
This function is called to begin a transaction.
void close ()
Derived classes must reimplement this pure virtual function in order to close the database connection.
bool commitTransaction ()
This function is called to commit a transaction.
QSqlResult * createResult () const
Creates an empty SQL result on the database.
QString escapeIdentifier (const QString &identifier, IdentifierType) const
Returns the identifier escaped according to the database rules.
QVariant handle () const
Returns the low-level database handle wrapped in a QVariant or an invalid variant if there is no handle.
bool hasFeature (DriverFeature f) const
Returns true if the driver supports feature feature; otherwise returns false.
bool open (const QString &db, const QString &user, const QString &password, const QString &host, int port, const QString &connOpts)
Derived classes must reimplement this pure virtual function to open a database connection on database db, using user name user, password password, host host, port port and connection options options.
QSqlIndex primaryIndex (const QString &table) const
Returns the primary index for table tableName.
QSQLiteDriver (QObject *parent=0)
QSQLiteDriver (sqlite3 *connection, QObject *parent=0)
QSqlRecord record (const QString &tablename) const
Returns a QSqlRecord populated with the names of the fields in table tableName.
bool rollbackTransaction ()
This function is called to rollback a transaction.
QStringList tables (QSql::TableType) const
Returns a list of the names of the tables in the database.
~QSQLiteDriver ()
Public Functions inherited from QSqlDriver
virtual QString formatValue (const QSqlField &field, bool trimStrings=false) const
Returns a string representation of the field value for the database.
bool isIdentifierEscaped (const QString &identifier, IdentifierType type) const
Returns whether identifier is escaped according to the database rules.
virtual bool isOpen () const
Returns true if the database connection is open; otherwise returns false.
bool isOpenError () const
Returns true if the there was an error opening the database connection; otherwise returns false.
QSqlError lastError () const
Returns a QSqlError object which contains information about the last error that occurred on the database.
QSql::NumericalPrecisionPolicy numericalPrecisionPolicy () const
Returns the current default precision policy for the database connection.
QSqlDriver (QObject *parent=0)
Constructs a new driver with the given parent.
void setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy precisionPolicy)
Sets the default numerical precision policy used by queries created by this driver to precisionPolicy.
virtual QString sqlStatement (StatementType type, const QString &tableName, const QSqlRecord &rec, bool preparedStatement) const
Returns a SQL statement of type type for the table tableName with the values from rec.
QString stripDelimiters (const QString &identifier, IdentifierType type) const
Returns the identifier with the leading and trailing delimiters removed, identifier can either be a table name or field name, dependent on type.
QStringList subscribedToNotifications () const
Returns a list of the names of the event notifications that are currently subscribed to.
bool subscribeToNotification (const QString &name)
This function is called to subscribe to event notifications from the database.
bool unsubscribeFromNotification (const QString &name)
This function is called to unsubscribe from event notifications from the database.
~QSqlDriver ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QSQLiteDriverPrivate * d
Friends
class QSQLiteResult
Additional Inherited Members
Public Types inherited from QSqlDriver
enum DriverFeature {
Transactions, QuerySize, BLOB, Unicode,
PreparedQueries, NamedPlaceholders, PositionalPlaceholders, LastInsertId,
BatchOperations, SimpleLocking, LowPrecisionNumbers, EventNotifications,
FinishQuery, MultipleResultSets
}
This enum contains a list of features a driver might support.
enum IdentifierType { FieldName, TableName }
This enum contains a list of SQL identifier types.
enum StatementType {
WhereStatement, SelectStatement, UpdateStatement, InsertStatement,
DeleteStatement
}
This enum contains a list of SQL statement (or clause) types the driver can create.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QSqlDriver
void notification (const QString &name)
This signal is emitted when the database posts an event notification that the driver subscribes to.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QSqlDriver
bool isIdentifierEscapedImplementation (const QString &identifier, IdentifierType type) const
This slot returns whether identifier is escaped according to the database rules.
QString stripDelimitersImplementation (const QString &identifier, IdentifierType type) const
This slot returns identifier with the leading and trailing delimiters removed, identifier can either be a tablename or field name, dependent on type.
QStringList subscribedToNotificationsImplementation () const
Returns a list of the names of the event notifications that are currently subscribed to.
bool subscribeToNotificationImplementation (const QString &name)
This slot is called to subscribe to event notifications from the database.
bool unsubscribeFromNotificationImplementation (const QString &name)
This slot is called to unsubscribe from event notifications from the database.
Protected Functions inherited from QSqlDriver
virtual void setLastError (const QSqlError &e)
This function is used to set the value of the last error, error, that occurred on the database.
virtual void setOpen (bool o)
This function sets the open state of the database to open.
virtual void setOpenError (bool e)
This function sets the open error state of the database to error.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 88 of file qsql_sqlite.h.
Constructors and Destructors
QSQLiteDriver() [1/2]
QSQLiteDriver::QSQLiteDriver (QObject * parent = 0) explicit
Definition at line 497 of file qsql_sqlite.cpp.
     : QSqlDriver(parent)
 {
     d = new QSQLiteDriverPrivate();
 }
QSQLiteDriver() [2/2]
QSQLiteDriver::QSQLiteDriver (sqlite3 * connection, QObject * parent = 0) explicit
Definition at line 503 of file qsql_sqlite.cpp.
     : QSqlDriver(parent)
 {
     d = new QSQLiteDriverPrivate();
     d->access = connection;
     setOpen(true);
     setOpenError(false);
 }
~QSQLiteDriver()
QSQLiteDriver::~QSQLiteDriver ()
Definition at line 513 of file qsql_sqlite.cpp.
 {
     delete d;
 }
Functions
beginTransaction()
bool QSQLiteDriver::beginTransaction () virtual
This function is called to begin a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
commitTransaction(), rollbackTransaction()
Reimplemented from QSqlDriver.
Definition at line 603 of file qsql_sqlite.cpp.
 {
     if (!isOpen() || isOpenError())
         return false;
     QSqlQuery q(createResult());
     if (!q.exec(QLatin1String("BEGIN"))) {
         setLastError(QSqlError(tr("Unable to begin transaction"),
                                q.lastError().databaseText(), QSqlError::TransactionError));
         return false;
     }
     return true;
 }
close()
void QSQLiteDriver::close () virtual
Derived classes must reimplement this pure virtual function in order to close the database connection.
Return true on success, false on failure.
See also
open(), setOpen()
Implements QSqlDriver.
Definition at line 583 of file qsql_sqlite.cpp.
Referenced by open().
 {
     if (isOpen()) {
         foreach (QSQLiteResult *result, d->results)
             result->d->finalize();
         if (sqlite3_close(d->access) != SQLITE_OK)
             setLastError(qMakeError(d->access, tr("Error closing database"),
                                     QSqlError::ConnectionError));
         d->access = 0;
         setOpen(false);
         setOpenError(false);
     }
 }
commitTransaction()
bool QSQLiteDriver::commitTransaction () virtual
This function is called to commit a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
beginTransaction(), rollbackTransaction()
Reimplemented from QSqlDriver.
Definition at line 618 of file qsql_sqlite.cpp.
 {
     if (!isOpen() || isOpenError())
         return false;
     QSqlQuery q(createResult());
     if (!q.exec(QLatin1String("COMMIT"))) {
         setLastError(QSqlError(tr("Unable to commit transaction"),
                                q.lastError().databaseText(), QSqlError::TransactionError));
         return false;
     }
     return true;
 }
createResult()
QSqlResult * QSQLiteDriver::createResult () const virtual
Creates an empty SQL result on the database.
Derived classes must reimplement this function and return a QSqlResult object appropriate for their database to the caller.
Implements QSqlDriver.
Definition at line 598 of file qsql_sqlite.cpp.
Referenced by beginTransaction(), commitTransaction(), primaryIndex(), record(), rollbackTransaction(), and tables().
 {
     return new QSQLiteResult(this);
 }
escapeIdentifier()
QString QSQLiteDriver::escapeIdentifier (const QString & identifier, IdentifierType type) const virtual
Returns the identifier escaped according to the database rules.
identifier can either be a table name or field name, dependent on type.
The default implementation does nothing.
See also
isIdentifierEscaped()
Reimplemented from QSqlDriver.
Definition at line 743 of file qsql_sqlite.cpp.
 {
     Q_UNUSED(type);
     return _q_escapeIdentifier(identifier);
 }
handle()
QVariant QSQLiteDriver::handle () const virtual
Returns the low-level database handle wrapped in a QVariant or an invalid variant if there is no handle.
Warning
Use this with uttermost care and only if you know what you're doing.
The handle returned here can become a stale pointer if the connection is modified (for example, if you close the connection).
The handle can be NULL if the connection is not open yet.
The handle returned here is database-dependent, you should query the type name of the variant before accessing it.
This example retrieves the handle for a connection to sqlite:
QSqlDatabase db = ...;
QVariant v = db.driver()->handle();
if (v.isValid() && qstrcmp(v.typeName(), "sqlite3*") == 0) {
    // v.data() returns a pointer to the handle
    sqlite3 *handle = *static_cast<sqlite3 **>(v.data());
    if (handle != 0) { // check that it is not NULL
        ...
    }
}
This snippet returns the handle for PostgreSQL or MySQL:
if (qstrcmp(v.typeName(), "PGconn*") == 0) {
    PGconn *handle = *static_cast<PGconn **>(v.data());
    if (handle != 0) ...
}
if (qstrcmp(v.typeName(), "MYSQL*") == 0) {
    MYSQL *handle = *static_cast<MYSQL **>(v.data());
    if (handle != 0) ...
}
See also
QSqlResult::handle()
Reimplemented from QSqlDriver.
Definition at line 738 of file qsql_sqlite.cpp.
 {
     return QVariant::fromValue(d->access);
 }
hasFeature()
bool QSQLiteDriver::hasFeature (DriverFeature feature) const virtual
Returns true if the driver supports feature feature; otherwise returns false.
Note that some databases need to be open() before this can be determined.
See also
DriverFeature
Implements QSqlDriver.
Definition at line 518 of file qsql_sqlite.cpp.
 {
     switch (f) {
     case BLOB:
     case Transactions:
     case Unicode:
     case LastInsertId:
     case PreparedQueries:
     case PositionalPlaceholders:
     case SimpleLocking:
     case FinishQuery:
     case LowPrecisionNumbers:
         return true;
     case QuerySize:
     case NamedPlaceholders:
     case BatchOperations:
     case EventNotifications:
     case MultipleResultSets:
         return false;
     }
     return false;
 }
open()
bool QSQLiteDriver::open (const QString & db, const QString & user, const QString & password, const QString & host, int port, const QString & options) virtual
Derived classes must reimplement this pure virtual function to open a database connection on database db, using user name user, password password, host host, port port and connection options options.
The function must return true on success and false on failure.
See also
setOpen()
Implements QSqlDriver.
Definition at line 545 of file qsql_sqlite.cpp.
 {
     if (isOpen())
         close();
     if (db.isEmpty())
         return false;
     bool sharedCache = false;
     int openMode = SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, timeOut=5000;
     QStringList opts=QString(conOpts).remove(QLatin1Char(' ')).split(QLatin1Char(';'));
     foreach(const QString &option, opts) {
         if (option.startsWith(QLatin1String("QSQLITE_BUSY_TIMEOUT="))) {
             bool ok;
             int nt = option.mid(21).toInt(&ok);
             if (ok)
                 timeOut = nt;
         }
         if (option == QLatin1String("QSQLITE_OPEN_READONLY"))
             openMode = SQLITE_OPEN_READONLY;
         if (option == QLatin1String("QSQLITE_ENABLE_SHARED_CACHE"))
             sharedCache = true;
     }
     sqlite3_enable_shared_cache(sharedCache);
     if (sqlite3_open_v2(db.toUtf8().constData(), &d->access, openMode, NULL) == SQLITE_OK) {
         sqlite3_busy_timeout(d->access, timeOut);
         setOpen(true);
         setOpenError(false);
         return true;
     } else {
         setLastError(qMakeError(d->access, tr("Error opening database"),
                      QSqlError::ConnectionError));
         setOpenError(true);
         return false;
     }
 }
primaryIndex()
QSqlIndex QSQLiteDriver::primaryIndex (const QString & tableName) const virtual
Returns the primary index for table tableName.
Returns an empty QSqlIndex if the table doesn't have a primary index. The default implementation returns an empty index.
Reimplemented from QSqlDriver.
Definition at line 710 of file qsql_sqlite.cpp.
 {
     if (!isOpen())
         return QSqlIndex();
     QString table = tblname;
     if (isIdentifierEscaped(table, QSqlDriver::TableName))
         table = stripDelimiters(table, QSqlDriver::TableName);
     QSqlQuery q(createResult());
     q.setForwardOnly(true);
     return qGetTableInfo(q, table, true);
 }
record()
QSqlRecord QSQLiteDriver::record (const QString & tableName) const virtual
Returns a QSqlRecord populated with the names of the fields in table tableName.
Use query.
If no such table exists, an empty record is returned. The default implementation returns an empty record.
record() instead.
Reimplemented from QSqlDriver.
Definition at line 724 of file qsql_sqlite.cpp.
 {
     if (!isOpen())
         return QSqlRecord();
     QString table = tbl;
     if (isIdentifierEscaped(table, QSqlDriver::TableName))
         table = stripDelimiters(table, QSqlDriver::TableName);
     QSqlQuery q(createResult());
     q.setForwardOnly(true);
     return qGetTableInfo(q, table);
 }
rollbackTransaction()
bool QSQLiteDriver::rollbackTransaction () virtual
This function is called to rollback a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
beginTransaction(), commitTransaction()
Reimplemented from QSqlDriver.
Definition at line 633 of file qsql_sqlite.cpp.
 {
     if (!isOpen() || isOpenError())
         return false;
     QSqlQuery q(createResult());
     if (!q.exec(QLatin1String("ROLLBACK"))) {
         setLastError(QSqlError(tr("Unable to rollback transaction"),
                                q.lastError().databaseText(), QSqlError::TransactionError));
         return false;
     }
     return true;
 }
tables()
QStringList QSQLiteDriver::tables (QSql::TableType tableType) const virtual
Returns a list of the names of the tables in the database.
The default implementation returns an empty list.
The tableType argument describes what types of tables should be returned. Due to binary compatibility, the string contains the value of the enum QSql::TableTypes as text. An empty string should be treated as QSql::Tables for backward compatibility.
Reimplemented from QSqlDriver.
Definition at line 648 of file qsql_sqlite.cpp.
 {
     QStringList res;
     if (!isOpen())
         return res;
     QSqlQuery q(createResult());
     q.setForwardOnly(true);
     QString sql = QLatin1String("SELECT name FROM sqlite_master WHERE %1 "
                                 "UNION ALL SELECT name FROM sqlite_temp_master WHERE %1");
     if ((type & QSql::Tables) && (type & QSql::Views))
         sql = sql.arg(QLatin1String("type='table' OR type='view'"));
     else if (type & QSql::Tables)
         sql = sql.arg(QLatin1String("type='table'"));
     else if (type & QSql::Views)
         sql = sql.arg(QLatin1String("type='view'"));
     else
         sql.clear();
     if (!sql.isEmpty() && q.exec(sql)) {
         while(q.next())
             res.append(q.value(0).toString());
     }
     if (type & QSql::SystemTables) {
         // there are no internal tables beside this one:
         res.append(QLatin1String("sqlite_master"));
     }
     return res;
 }
Friends and Related Functions
QSQLiteResult
friend class QSQLiteResult friend
Definition at line 91 of file qsql_sqlite.h.
Referenced by createResult().
Properties
d
QSQLiteDriverPrivate* QSQLiteDriver::d private
Definition at line 116 of file qsql_sqlite.h.
Referenced by close(), handle(), open(), QSQLiteDriver(), QSQLiteResult::QSQLiteResult(), ~QSQLiteDriver(), and QSQLiteResult::~QSQLiteResult().
The documentation for this class was generated from the following files:
/src/sql/drivers/sqlite/qsql_sqlite.h
/src/sql/drivers/sqlite/qsql_sqlite.cpp