Qt 4.8: QDeclarativeJS::AST::Visitor Class Reference
QDeclarativeJS::AST::Visitor Class Reference
#include <qdeclarativejsastvisitor_p.h>
Public Functions
virtual void endVisit (UiProgram *)
virtual void endVisit (UiImportList *)
virtual void endVisit (UiImport *)
virtual void endVisit (UiPublicMember *)
virtual void endVisit (UiSourceElement *)
virtual void endVisit (UiObjectDefinition *)
virtual void endVisit (UiObjectInitializer *)
virtual void endVisit (UiObjectBinding *)
virtual void endVisit (UiScriptBinding *)
virtual void endVisit (UiArrayBinding *)
virtual void endVisit (UiObjectMemberList *)
virtual void endVisit (UiArrayMemberList *)
virtual void endVisit (UiQualifiedId *)
virtual void endVisit (UiSignature *)
virtual void endVisit (UiFormalList *)
virtual void endVisit (UiFormal *)
virtual void endVisit (ThisExpression *)
virtual void endVisit (IdentifierExpression *)
virtual void endVisit (NullExpression *)
virtual void endVisit (TrueLiteral *)
virtual void endVisit (FalseLiteral *)
virtual void endVisit (StringLiteral *)
virtual void endVisit (NumericLiteral *)
virtual void endVisit (RegExpLiteral *)
virtual void endVisit (ArrayLiteral *)
virtual void endVisit (ObjectLiteral *)
virtual void endVisit (ElementList *)
virtual void endVisit (Elision *)
virtual void endVisit (PropertyNameAndValueList *)
virtual void endVisit (NestedExpression *)
virtual void endVisit (IdentifierPropertyName *)
virtual void endVisit (StringLiteralPropertyName *)
virtual void endVisit (NumericLiteralPropertyName *)
virtual void endVisit (ArrayMemberExpression *)
virtual void endVisit (FieldMemberExpression *)
virtual void endVisit (NewMemberExpression *)
virtual void endVisit (NewExpression *)
virtual void endVisit (CallExpression *)
virtual void endVisit (ArgumentList *)
virtual void endVisit (PostIncrementExpression *)
virtual void endVisit (PostDecrementExpression *)
virtual void endVisit (DeleteExpression *)
virtual void endVisit (VoidExpression *)
virtual void endVisit (TypeOfExpression *)
virtual void endVisit (PreIncrementExpression *)
virtual void endVisit (PreDecrementExpression *)
virtual void endVisit (UnaryPlusExpression *)
virtual void endVisit (UnaryMinusExpression *)
virtual void endVisit (TildeExpression *)
virtual void endVisit (NotExpression *)
virtual void endVisit (BinaryExpression *)
virtual void endVisit (ConditionalExpression *)
virtual void endVisit (Expression *)
virtual void endVisit (Block *)
virtual void endVisit (StatementList *)
virtual void endVisit (VariableStatement *)
virtual void endVisit (VariableDeclarationList *)
virtual void endVisit (VariableDeclaration *)
virtual void endVisit (EmptyStatement *)
virtual void endVisit (ExpressionStatement *)
virtual void endVisit (IfStatement *)
virtual void endVisit (DoWhileStatement *)
virtual void endVisit (WhileStatement *)
virtual void endVisit (ForStatement *)
virtual void endVisit (LocalForStatement *)
virtual void endVisit (ForEachStatement *)
virtual void endVisit (LocalForEachStatement *)
virtual void endVisit (ContinueStatement *)
virtual void endVisit (BreakStatement *)
virtual void endVisit (ReturnStatement *)
virtual void endVisit (WithStatement *)
virtual void endVisit (SwitchStatement *)
virtual void endVisit (CaseBlock *)
virtual void endVisit (CaseClauses *)
virtual void endVisit (CaseClause *)
virtual void endVisit (DefaultClause *)
virtual void endVisit (LabelledStatement *)
virtual void endVisit (ThrowStatement *)
virtual void endVisit (TryStatement *)
virtual void endVisit (Catch *)
virtual void endVisit (Finally *)
virtual void endVisit (FunctionDeclaration *)
virtual void endVisit (FunctionExpression *)
virtual void endVisit (FormalParameterList *)
virtual void endVisit (FunctionBody *)
virtual void endVisit (Program *)
virtual void endVisit (SourceElements *)
virtual void endVisit (FunctionSourceElement *)
virtual void endVisit (StatementSourceElement *)
virtual void endVisit (DebuggerStatement *)
virtual void postVisit (Node *)
virtual bool preVisit (Node *)
virtual bool visit (UiProgram *)
virtual bool visit (UiImportList *)
virtual bool visit (UiImport *)
virtual bool visit (UiPublicMember *)
virtual bool visit (UiSourceElement *)
virtual bool visit (UiObjectDefinition *)
virtual bool visit (UiObjectInitializer *)
virtual bool visit (UiObjectBinding *)
virtual bool visit (UiScriptBinding *)
virtual bool visit (UiArrayBinding *)
virtual bool visit (UiObjectMemberList *)
virtual bool visit (UiArrayMemberList *)
virtual bool visit (UiQualifiedId *)
virtual bool visit (UiSignature *)
virtual bool visit (UiFormalList *)
virtual bool visit (UiFormal *)
virtual bool visit (ThisExpression *)
virtual bool visit (IdentifierExpression *)
virtual bool visit (NullExpression *)
virtual bool visit (TrueLiteral *)
virtual bool visit (FalseLiteral *)
virtual bool visit (StringLiteral *)
virtual bool visit (NumericLiteral *)
virtual bool visit (RegExpLiteral *)
virtual bool visit (ArrayLiteral *)
virtual bool visit (ObjectLiteral *)
virtual bool visit (ElementList *)
virtual bool visit (Elision *)
virtual bool visit (PropertyNameAndValueList *)
virtual bool visit (NestedExpression *)
virtual bool visit (IdentifierPropertyName *)
virtual bool visit (StringLiteralPropertyName *)
virtual bool visit (NumericLiteralPropertyName *)
virtual bool visit (ArrayMemberExpression *)
virtual bool visit (FieldMemberExpression *)
virtual bool visit (NewMemberExpression *)
virtual bool visit (NewExpression *)
virtual bool visit (CallExpression *)
virtual bool visit (ArgumentList *)
virtual bool visit (PostIncrementExpression *)
virtual bool visit (PostDecrementExpression *)
virtual bool visit (DeleteExpression *)
virtual bool visit (VoidExpression *)
virtual bool visit (TypeOfExpression *)
virtual bool visit (PreIncrementExpression *)
virtual bool visit (PreDecrementExpression *)
virtual bool visit (UnaryPlusExpression *)
virtual bool visit (UnaryMinusExpression *)
virtual bool visit (TildeExpression *)
virtual bool visit (NotExpression *)
virtual bool visit (BinaryExpression *)
virtual bool visit (ConditionalExpression *)
virtual bool visit (Expression *)
virtual bool visit (Block *)
virtual bool visit (StatementList *)
virtual bool visit (VariableStatement *)
virtual bool visit (VariableDeclarationList *)
virtual bool visit (VariableDeclaration *)
virtual bool visit (EmptyStatement *)
virtual bool visit (ExpressionStatement *)
virtual bool visit (IfStatement *)
virtual bool visit (DoWhileStatement *)
virtual bool visit (WhileStatement *)
virtual bool visit (ForStatement *)
virtual bool visit (LocalForStatement *)
virtual bool visit (ForEachStatement *)
virtual bool visit (LocalForEachStatement *)
virtual bool visit (ContinueStatement *)
virtual bool visit (BreakStatement *)
virtual bool visit (ReturnStatement *)
virtual bool visit (WithStatement *)
virtual bool visit (SwitchStatement *)
virtual bool visit (CaseBlock *)
virtual bool visit (CaseClauses *)
virtual bool visit (CaseClause *)
virtual bool visit (DefaultClause *)
virtual bool visit (LabelledStatement *)
virtual bool visit (ThrowStatement *)
virtual bool visit (TryStatement *)
virtual bool visit (Catch *)
virtual bool visit (Finally *)
virtual bool visit (FunctionDeclaration *)
virtual bool visit (FunctionExpression *)
virtual bool visit (FormalParameterList *)
virtual bool visit (FunctionBody *)
virtual bool visit (Program *)
virtual bool visit (SourceElements *)
virtual bool visit (FunctionSourceElement *)
virtual bool visit (StatementSourceElement *)
virtual bool visit (DebuggerStatement *)
Visitor ()
virtual ~Visitor ()
Detailed Description
Definition at line 63 of file qdeclarativejsastvisitor_p.h.
Constructors and Destructors
Visitor()
QDeclarativeJS::AST::Visitor::Visitor ()
Definition at line 48 of file qdeclarativejsastvisitor.cpp.
 {
 }
~Visitor()
QDeclarativeJS::AST::Visitor::~Visitor () virtual
Definition at line 52 of file qdeclarativejsastvisitor.cpp.
 {
 }
Functions
endVisit() [1/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiProgram *) inline virtual
Definition at line 90 of file qdeclarativejsastvisitor_p.h.
Referenced by QDeclarativeJS::AST::UiFormal::accept0(), QDeclarativeJS::AST::UiFormalList::accept0(), QDeclarativeJS::AST::UiSignature::accept0(), QDeclarativeJS::AST::NestedExpression::accept0(), QDeclarativeJS::AST::ThisExpression::accept0(), QDeclarativeJS::AST::IdentifierExpression::accept0(), QDeclarativeJS::AST::NullExpression::accept0(), QDeclarativeJS::AST::TrueLiteral::accept0(), QDeclarativeJS::AST::FalseLiteral::accept0(), QDeclarativeJS::AST::NumericLiteral::accept0(), QDeclarativeJS::AST::StringLiteral::accept0(), QDeclarativeJS::AST::RegExpLiteral::accept0(), QDeclarativeJS::AST::ArrayLiteral::accept0(), QDeclarativeJS::AST::ObjectLiteral::accept0(), QDeclarativeJS::AST::ElementList::accept0(), QDeclarativeJS::AST::Elision::accept0(), QDeclarativeJS::AST::PropertyNameAndValueList::accept0(), QDeclarativeJS::AST::IdentifierPropertyName::accept0(), QDeclarativeJS::AST::StringLiteralPropertyName::accept0(), QDeclarativeJS::AST::NumericLiteralPropertyName::accept0(), QDeclarativeJS::AST::ArrayMemberExpression::accept0(), QDeclarativeJS::AST::FieldMemberExpression::accept0(), QDeclarativeJS::AST::NewMemberExpression::accept0(), QDeclarativeJS::AST::NewExpression::accept0(), QDeclarativeJS::AST::CallExpression::accept0(), QDeclarativeJS::AST::ArgumentList::accept0(), QDeclarativeJS::AST::PostIncrementExpression::accept0(), QDeclarativeJS::AST::PostDecrementExpression::accept0(), QDeclarativeJS::AST::DeleteExpression::accept0(), QDeclarativeJS::AST::VoidExpression::accept0(), QDeclarativeJS::AST::TypeOfExpression::accept0(), QDeclarativeJS::AST::PreIncrementExpression::accept0(), QDeclarativeJS::AST::PreDecrementExpression::accept0(), QDeclarativeJS::AST::UnaryPlusExpression::accept0(), QDeclarativeJS::AST::UnaryMinusExpression::accept0(), QDeclarativeJS::AST::TildeExpression::accept0(), QDeclarativeJS::AST::NotExpression::accept0(), QDeclarativeJS::AST::BinaryExpression::accept0(), QDeclarativeJS::AST::ConditionalExpression::accept0(), QDeclarativeJS::AST::Expression::accept0(), QDeclarativeJS::AST::Block::accept0(), QDeclarativeJS::AST::StatementList::accept0(), QDeclarativeJS::AST::VariableStatement::accept0(), QDeclarativeJS::AST::VariableDeclaration::accept0(), QDeclarativeJS::AST::VariableDeclarationList::accept0(), QDeclarativeJS::AST::EmptyStatement::accept0(), QDeclarativeJS::AST::ExpressionStatement::accept0(), QDeclarativeJS::AST::IfStatement::accept0(), QDeclarativeJS::AST::DoWhileStatement::accept0(), QDeclarativeJS::AST::WhileStatement::accept0(), QDeclarativeJS::AST::ForStatement::accept0(), QDeclarativeJS::AST::LocalForStatement::accept0(), QDeclarativeJS::AST::ForEachStatement::accept0(), QDeclarativeJS::AST::LocalForEachStatement::accept0(), QDeclarativeJS::AST::ContinueStatement::accept0(), QDeclarativeJS::AST::BreakStatement::accept0(), QDeclarativeJS::AST::ReturnStatement::accept0(), QDeclarativeJS::AST::WithStatement::accept0(), QDeclarativeJS::AST::CaseBlock::accept0(), QDeclarativeJS::AST::SwitchStatement::accept0(), QDeclarativeJS::AST::CaseClauses::accept0(), QDeclarativeJS::AST::CaseClause::accept0(), QDeclarativeJS::AST::DefaultClause::accept0(), QDeclarativeJS::AST::LabelledStatement::accept0(), QDeclarativeJS::AST::ThrowStatement::accept0(), QDeclarativeJS::AST::Catch::accept0(), QDeclarativeJS::AST::Finally::accept0(), QDeclarativeJS::AST::TryStatement::accept0(), QDeclarativeJS::AST::FunctionExpression::accept0(), QDeclarativeJS::AST::FunctionDeclaration::accept0(), QDeclarativeJS::AST::FormalParameterList::accept0(), QDeclarativeJS::AST::FunctionBody::accept0(), QDeclarativeJS::AST::Program::accept0(), QDeclarativeJS::AST::SourceElements::accept0(), QDeclarativeJS::AST::FunctionSourceElement::accept0(), QDeclarativeJS::AST::StatementSourceElement::accept0(), QDeclarativeJS::AST::DebuggerStatement::accept0(), QDeclarativeJS::AST::UiProgram::accept0(), QDeclarativeJS::AST::UiQualifiedId::accept0(), QDeclarativeJS::AST::UiImport::accept0(), QDeclarativeJS::AST::UiImportList::accept0(), QDeclarativeJS::AST::UiObjectMemberList::accept0(), QDeclarativeJS::AST::UiArrayMemberList::accept0(), QDeclarativeJS::AST::UiObjectInitializer::accept0(), QDeclarativeJS::AST::UiPublicMember::accept0(), QDeclarativeJS::AST::UiObjectDefinition::accept0(), QDeclarativeJS::AST::UiSourceElement::accept0(), QDeclarativeJS::AST::UiObjectBinding::accept0(), QDeclarativeJS::AST::UiScriptBinding::accept0(), and QDeclarativeJS::AST::UiArrayBinding::accept0().
 {}
endVisit() [2/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiImportList *) inline virtual
Definition at line 91 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [3/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiImport *) inline virtual
Definition at line 92 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [4/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiPublicMember *) inline virtual
Definition at line 93 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [5/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiSourceElement *) inline virtual
Definition at line 94 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [6/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiObjectDefinition *) inline virtual
Definition at line 95 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [7/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiObjectInitializer *) inline virtual
Definition at line 96 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [8/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiObjectBinding *) inline virtual
Definition at line 97 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [9/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiScriptBinding *) inline virtual
Definition at line 98 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [10/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiArrayBinding *) inline virtual
Definition at line 99 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [11/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiObjectMemberList *) inline virtual
Definition at line 100 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [12/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiArrayMemberList *) inline virtual
Definition at line 101 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [13/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiQualifiedId *) inline virtual
Definition at line 102 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [14/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiSignature *) inline virtual
Definition at line 103 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [15/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiFormalList *) inline virtual
Definition at line 104 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [16/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UiFormal *) inline virtual
Definition at line 105 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [17/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ThisExpression *) inline virtual
Definition at line 109 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [18/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (IdentifierExpression *) inline virtual
Definition at line 112 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [19/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (NullExpression *) inline virtual
Definition at line 115 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [20/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (TrueLiteral *) inline virtual
Definition at line 118 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [21/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (FalseLiteral *) inline virtual
Definition at line 121 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [22/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (StringLiteral *) inline virtual
Definition at line 124 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [23/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (NumericLiteral *) inline virtual
Definition at line 127 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [24/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (RegExpLiteral *) inline virtual
Definition at line 130 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [25/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ArrayLiteral *) inline virtual
Definition at line 133 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [26/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ObjectLiteral *) inline virtual
Definition at line 136 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [27/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ElementList *) inline virtual
Definition at line 139 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [28/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (Elision *) inline virtual
Definition at line 142 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [29/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (PropertyNameAndValueList *) inline virtual
Definition at line 145 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [30/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (NestedExpression *) inline virtual
Definition at line 148 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [31/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (IdentifierPropertyName *) inline virtual
Definition at line 151 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [32/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (StringLiteralPropertyName *) inline virtual
Definition at line 154 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [33/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (NumericLiteralPropertyName *) inline virtual
Definition at line 157 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [34/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ArrayMemberExpression *) inline virtual
Definition at line 160 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [35/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (FieldMemberExpression *) inline virtual
Definition at line 163 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [36/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (NewMemberExpression *) inline virtual
Definition at line 166 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [37/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (NewExpression *) inline virtual
Definition at line 169 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [38/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (CallExpression *) inline virtual
Definition at line 172 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [39/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ArgumentList *) inline virtual
Definition at line 175 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [40/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (PostIncrementExpression *) inline virtual
Definition at line 178 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [41/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (PostDecrementExpression *) inline virtual
Definition at line 181 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [42/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (DeleteExpression *) inline virtual
Definition at line 184 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [43/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (VoidExpression *) inline virtual
Definition at line 187 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [44/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (TypeOfExpression *) inline virtual
Definition at line 190 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [45/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (PreIncrementExpression *) inline virtual
Definition at line 193 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [46/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (PreDecrementExpression *) inline virtual
Definition at line 196 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [47/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UnaryPlusExpression *) inline virtual
Definition at line 199 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [48/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (UnaryMinusExpression *) inline virtual
Definition at line 202 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [49/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (TildeExpression *) inline virtual
Definition at line 205 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [50/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (NotExpression *) inline virtual
Definition at line 208 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [51/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (BinaryExpression *) inline virtual
Definition at line 211 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [52/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ConditionalExpression *) inline virtual
Definition at line 214 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [53/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (Expression *) inline virtual
Definition at line 217 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [54/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (Block *) inline virtual
Definition at line 220 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [55/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (StatementList *) inline virtual
Definition at line 223 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [56/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (VariableStatement *) inline virtual
Definition at line 226 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [57/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (VariableDeclarationList *) inline virtual
Definition at line 229 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [58/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (VariableDeclaration *) inline virtual
Definition at line 232 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [59/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (EmptyStatement *) inline virtual
Definition at line 235 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [60/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ExpressionStatement *) inline virtual
Definition at line 238 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [61/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (IfStatement *) inline virtual
Definition at line 241 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [62/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (DoWhileStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 244 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [63/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (WhileStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 247 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [64/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ForStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 250 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [65/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (LocalForStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 253 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [66/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ForEachStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 256 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [67/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (LocalForEachStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 259 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [68/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ContinueStatement *) inline virtual
Definition at line 262 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [69/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (BreakStatement *) inline virtual
Definition at line 265 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [70/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ReturnStatement *) inline virtual
Definition at line 268 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [71/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (WithStatement *) inline virtual
Definition at line 271 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [72/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (SwitchStatement *) inline virtual
Definition at line 274 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [73/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (CaseBlock *) inline virtual
Definition at line 277 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [74/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (CaseClauses *) inline virtual
Definition at line 280 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [75/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (CaseClause *) inline virtual
Definition at line 283 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [76/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (DefaultClause *) inline virtual
Definition at line 286 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [77/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (LabelledStatement *) inline virtual
Definition at line 289 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [78/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (ThrowStatement *) inline virtual
Definition at line 292 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [79/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (TryStatement *) inline virtual
Definition at line 295 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [80/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (Catch *) inline virtual
Definition at line 298 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [81/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (Finally *) inline virtual
Definition at line 301 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [82/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (FunctionDeclaration *) inline virtual
Definition at line 304 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [83/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (FunctionExpression *) inline virtual
Definition at line 307 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [84/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (FormalParameterList *) inline virtual
Definition at line 310 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [85/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (FunctionBody *) inline virtual
Definition at line 313 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [86/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (Program *) inline virtual
Definition at line 316 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [87/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (SourceElements *) inline virtual
Definition at line 319 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [88/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (FunctionSourceElement *) inline virtual
Definition at line 322 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [89/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (StatementSourceElement *) inline virtual
Definition at line 325 of file qdeclarativejsastvisitor_p.h.
 {}
endVisit() [90/90]
virtual void QDeclarativeJS::AST::Visitor::endVisit (DebuggerStatement *) inline virtual
Definition at line 328 of file qdeclarativejsastvisitor_p.h.
 {}
postVisit()
virtual void QDeclarativeJS::AST::Visitor::postVisit (Node *) inline virtual
Definition at line 70 of file qdeclarativejsastvisitor_p.h.
Referenced by QDeclarativeJS::AST::Node::accept().
 {}
preVisit()
virtual bool QDeclarativeJS::AST::Visitor::preVisit (Node *) inline virtual
Definition at line 69 of file qdeclarativejsastvisitor_p.h.
Referenced by QDeclarativeJS::AST::Node::accept().
 { return true; }
visit() [1/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiProgram *) inline virtual
Definition at line 73 of file qdeclarativejsastvisitor_p.h.
Referenced by QDeclarativeJS::AST::UiFormal::accept0(), QDeclarativeJS::AST::UiFormalList::accept0(), QDeclarativeJS::AST::UiSignature::accept0(), QDeclarativeJS::AST::NestedExpression::accept0(), QDeclarativeJS::AST::ThisExpression::accept0(), QDeclarativeJS::AST::IdentifierExpression::accept0(), QDeclarativeJS::AST::NullExpression::accept0(), QDeclarativeJS::AST::TrueLiteral::accept0(), QDeclarativeJS::AST::FalseLiteral::accept0(), QDeclarativeJS::AST::NumericLiteral::accept0(), QDeclarativeJS::AST::StringLiteral::accept0(), QDeclarativeJS::AST::RegExpLiteral::accept0(), QDeclarativeJS::AST::ArrayLiteral::accept0(), QDeclarativeJS::AST::ObjectLiteral::accept0(), QDeclarativeJS::AST::ElementList::accept0(), QDeclarativeJS::AST::Elision::accept0(), QDeclarativeJS::AST::PropertyNameAndValueList::accept0(), QDeclarativeJS::AST::IdentifierPropertyName::accept0(), QDeclarativeJS::AST::StringLiteralPropertyName::accept0(), QDeclarativeJS::AST::NumericLiteralPropertyName::accept0(), QDeclarativeJS::AST::ArrayMemberExpression::accept0(), QDeclarativeJS::AST::FieldMemberExpression::accept0(), QDeclarativeJS::AST::NewMemberExpression::accept0(), QDeclarativeJS::AST::NewExpression::accept0(), QDeclarativeJS::AST::CallExpression::accept0(), QDeclarativeJS::AST::ArgumentList::accept0(), QDeclarativeJS::AST::PostIncrementExpression::accept0(), QDeclarativeJS::AST::PostDecrementExpression::accept0(), QDeclarativeJS::AST::DeleteExpression::accept0(), QDeclarativeJS::AST::VoidExpression::accept0(), QDeclarativeJS::AST::TypeOfExpression::accept0(), QDeclarativeJS::AST::PreIncrementExpression::accept0(), QDeclarativeJS::AST::PreDecrementExpression::accept0(), QDeclarativeJS::AST::UnaryPlusExpression::accept0(), QDeclarativeJS::AST::UnaryMinusExpression::accept0(), QDeclarativeJS::AST::TildeExpression::accept0(), QDeclarativeJS::AST::NotExpression::accept0(), QDeclarativeJS::AST::BinaryExpression::accept0(), QDeclarativeJS::AST::ConditionalExpression::accept0(), QDeclarativeJS::AST::Expression::accept0(), QDeclarativeJS::AST::Block::accept0(), QDeclarativeJS::AST::StatementList::accept0(), QDeclarativeJS::AST::VariableStatement::accept0(), QDeclarativeJS::AST::VariableDeclaration::accept0(), QDeclarativeJS::AST::VariableDeclarationList::accept0(), QDeclarativeJS::AST::EmptyStatement::accept0(), QDeclarativeJS::AST::ExpressionStatement::accept0(), QDeclarativeJS::AST::IfStatement::accept0(), QDeclarativeJS::AST::DoWhileStatement::accept0(), QDeclarativeJS::AST::WhileStatement::accept0(), QDeclarativeJS::AST::ForStatement::accept0(), QDeclarativeJS::AST::LocalForStatement::accept0(), QDeclarativeJS::AST::ForEachStatement::accept0(), QDeclarativeJS::AST::LocalForEachStatement::accept0(), QDeclarativeJS::AST::ContinueStatement::accept0(), QDeclarativeJS::AST::BreakStatement::accept0(), QDeclarativeJS::AST::ReturnStatement::accept0(), QDeclarativeJS::AST::WithStatement::accept0(), QDeclarativeJS::AST::CaseBlock::accept0(), QDeclarativeJS::AST::SwitchStatement::accept0(), QDeclarativeJS::AST::CaseClauses::accept0(), QDeclarativeJS::AST::CaseClause::accept0(), QDeclarativeJS::AST::DefaultClause::accept0(), QDeclarativeJS::AST::LabelledStatement::accept0(), QDeclarativeJS::AST::ThrowStatement::accept0(), QDeclarativeJS::AST::Catch::accept0(), QDeclarativeJS::AST::Finally::accept0(), QDeclarativeJS::AST::TryStatement::accept0(), QDeclarativeJS::AST::FunctionExpression::accept0(), QDeclarativeJS::AST::FunctionDeclaration::accept0(), QDeclarativeJS::AST::FormalParameterList::accept0(), QDeclarativeJS::AST::FunctionBody::accept0(), QDeclarativeJS::AST::Program::accept0(), QDeclarativeJS::AST::SourceElements::accept0(), QDeclarativeJS::AST::FunctionSourceElement::accept0(), QDeclarativeJS::AST::StatementSourceElement::accept0(), QDeclarativeJS::AST::DebuggerStatement::accept0(), QDeclarativeJS::AST::UiProgram::accept0(), QDeclarativeJS::AST::UiQualifiedId::accept0(), QDeclarativeJS::AST::UiImport::accept0(), QDeclarativeJS::AST::UiImportList::accept0(), QDeclarativeJS::AST::UiObjectMemberList::accept0(), QDeclarativeJS::AST::UiArrayMemberList::accept0(), QDeclarativeJS::AST::UiObjectInitializer::accept0(), QDeclarativeJS::AST::UiPublicMember::accept0(), QDeclarativeJS::AST::UiObjectDefinition::accept0(), QDeclarativeJS::AST::UiSourceElement::accept0(), QDeclarativeJS::AST::UiObjectBinding::accept0(), QDeclarativeJS::AST::UiScriptBinding::accept0(), QDeclarativeJS::AST::UiArrayBinding::accept0(), and QDeclarativeRewrite::RewriteBinding::setName().
 { return true; }
visit() [2/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiImportList *) inline virtual
Definition at line 74 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [3/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiImport *) inline virtual
Definition at line 75 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [4/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiPublicMember *) inline virtual
Definition at line 76 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [5/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiSourceElement *) inline virtual
Definition at line 77 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [6/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiObjectDefinition *) inline virtual
Definition at line 78 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [7/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiObjectInitializer *) inline virtual
Definition at line 79 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [8/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiObjectBinding *) inline virtual
Definition at line 80 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [9/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiScriptBinding *) inline virtual
Definition at line 81 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [10/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiArrayBinding *) inline virtual
Definition at line 82 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [11/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiObjectMemberList *) inline virtual
Definition at line 83 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [12/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiArrayMemberList *) inline virtual
Definition at line 84 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [13/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiQualifiedId *) inline virtual
Definition at line 85 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [14/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiSignature *) inline virtual
Definition at line 86 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [15/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiFormalList *) inline virtual
Definition at line 87 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [16/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UiFormal *) inline virtual
Definition at line 88 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [17/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ThisExpression *) inline virtual
Definition at line 108 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [18/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (IdentifierExpression *) inline virtual
Definition at line 111 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [19/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (NullExpression *) inline virtual
Definition at line 114 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [20/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (TrueLiteral *) inline virtual
Definition at line 117 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [21/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (FalseLiteral *) inline virtual
Definition at line 120 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [22/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (StringLiteral *) inline virtual
Definition at line 123 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [23/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (NumericLiteral *) inline virtual
Definition at line 126 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [24/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (RegExpLiteral *) inline virtual
Definition at line 129 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [25/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ArrayLiteral *) inline virtual
Definition at line 132 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [26/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ObjectLiteral *) inline virtual
Definition at line 135 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [27/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ElementList *) inline virtual
Definition at line 138 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [28/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (Elision *) inline virtual
Definition at line 141 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [29/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (PropertyNameAndValueList *) inline virtual
Definition at line 144 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [30/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (NestedExpression *) inline virtual
Definition at line 147 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [31/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (IdentifierPropertyName *) inline virtual
Definition at line 150 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [32/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (StringLiteralPropertyName *) inline virtual
Definition at line 153 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [33/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (NumericLiteralPropertyName *) inline virtual
Definition at line 156 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [34/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ArrayMemberExpression *) inline virtual
Definition at line 159 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [35/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (FieldMemberExpression *) inline virtual
Definition at line 162 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [36/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (NewMemberExpression *) inline virtual
Definition at line 165 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [37/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (NewExpression *) inline virtual
Definition at line 168 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [38/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (CallExpression *) inline virtual
Reimplemented in QDeclarativeRewrite::SharedBindingTester.
Definition at line 171 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [39/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ArgumentList *) inline virtual
Definition at line 174 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [40/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (PostIncrementExpression *) inline virtual
Definition at line 177 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [41/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (PostDecrementExpression *) inline virtual
Definition at line 180 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [42/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (DeleteExpression *) inline virtual
Definition at line 183 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [43/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (VoidExpression *) inline virtual
Definition at line 186 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [44/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (TypeOfExpression *) inline virtual
Definition at line 189 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [45/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (PreIncrementExpression *) inline virtual
Definition at line 192 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [46/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (PreDecrementExpression *) inline virtual
Definition at line 195 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [47/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UnaryPlusExpression *) inline virtual
Definition at line 198 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [48/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (UnaryMinusExpression *) inline virtual
Definition at line 201 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [49/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (TildeExpression *) inline virtual
Definition at line 204 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [50/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (NotExpression *) inline virtual
Definition at line 207 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [51/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (BinaryExpression *) inline virtual
Definition at line 210 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [52/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ConditionalExpression *) inline virtual
Definition at line 213 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [53/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (Expression *) inline virtual
Definition at line 216 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [54/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (Block *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 219 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [55/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (StatementList *) inline virtual
Definition at line 222 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [56/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (VariableStatement *) inline virtual
Definition at line 225 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [57/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (VariableDeclarationList *) inline virtual
Definition at line 228 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [58/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (VariableDeclaration *) inline virtual
Definition at line 231 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [59/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (EmptyStatement *) inline virtual
Definition at line 234 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [60/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ExpressionStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 237 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [61/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (IfStatement *) inline virtual
Definition at line 240 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [62/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (DoWhileStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 243 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [63/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (WhileStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 246 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [64/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ForStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 249 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [65/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (LocalForStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 252 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [66/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ForEachStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 255 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [67/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (LocalForEachStatement *) inline virtual
Reimplemented in QDeclarativeRewrite::RewriteBinding.
Definition at line 258 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [68/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ContinueStatement *) inline virtual
Definition at line 261 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [69/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (BreakStatement *) inline virtual
Definition at line 264 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [70/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ReturnStatement *) inline virtual
Definition at line 267 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [71/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (WithStatement *) inline virtual
Definition at line 270 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [72/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (SwitchStatement *) inline virtual
Definition at line 273 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [73/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (CaseBlock *) inline virtual
Definition at line 276 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [74/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (CaseClauses *) inline virtual
Definition at line 279 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [75/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (CaseClause *) inline virtual
Definition at line 282 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [76/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (DefaultClause *) inline virtual
Definition at line 285 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [77/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (LabelledStatement *) inline virtual
Definition at line 288 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [78/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (ThrowStatement *) inline virtual
Definition at line 291 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [79/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (TryStatement *) inline virtual
Definition at line 294 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [80/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (Catch *) inline virtual
Definition at line 297 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [81/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (Finally *) inline virtual
Definition at line 300 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [82/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (FunctionDeclaration *) inline virtual
Reimplemented in QDeclarativeRewrite::SharedBindingTester.
Definition at line 303 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [83/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (FunctionExpression *) inline virtual
Reimplemented in QDeclarativeRewrite::SharedBindingTester.
Definition at line 306 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [84/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (FormalParameterList *) inline virtual
Definition at line 309 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [85/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (FunctionBody *) inline virtual
Definition at line 312 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [86/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (Program *) inline virtual
Definition at line 315 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [87/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (SourceElements *) inline virtual
Definition at line 318 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [88/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (FunctionSourceElement *) inline virtual
Definition at line 321 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [89/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (StatementSourceElement *) inline virtual
Definition at line 324 of file qdeclarativejsastvisitor_p.h.
 { return true; }
visit() [90/90]
virtual bool QDeclarativeJS::AST::Visitor::visit (DebuggerStatement *) inline virtual
Definition at line 327 of file qdeclarativejsastvisitor_p.h.
 { return true; }
The documentation for this class was generated from the following files:
/src/declarative/qml/parser/qdeclarativejsastvisitor_p.h
/src/declarative/qml/parser/qdeclarativejsastvisitor.cpp