Qt 4.8: QOrderedMutexLocker Class Reference
QOrderedMutexLocker Class Reference
#include <qorderedmutexlocker_p.h>
Public Functions
QOrderedMutexLocker (QMutex *m1, QMutex *m2)
void relock ()
void unlock ()
~QOrderedMutexLocker ()
Static Public Functions
static bool relock (QMutex *mtx1, QMutex *mtx2)
Properties
bool locked
QMutex * mtx1
QMutex * mtx2
Detailed Description
Definition at line 64 of file qorderedmutexlocker_p.h.
Constructors and Destructors
QOrderedMutexLocker()
QOrderedMutexLocker::QOrderedMutexLocker (QMutex * m1, QMutex * m2) inline
Definition at line 67 of file qorderedmutexlocker_p.h.
         : mtx1((m1 == m2) ? m1 : (m1 < m2 ? m1 : m2)),
           mtx2((m1 == m2) ?  0 : (m1 < m2 ? m2 : m1)),
           locked(false)
     {
         relock();
     }
~QOrderedMutexLocker()
QOrderedMutexLocker::~QOrderedMutexLocker () inline
Definition at line 74 of file qorderedmutexlocker_p.h.
     {
         unlock();
     }
Functions
relock() [1/2]
void QOrderedMutexLocker::relock () inline
Definition at line 79 of file qorderedmutexlocker_p.h.
Referenced by QMetaObjectPrivate::disconnectHelper(), QOrderedMutexLocker(), and QObject::~QObject().
     {
         if (!locked) {
             if (mtx1) mtx1->lockInline();
             if (mtx2) mtx2->lockInline();
             locked = true;
         }
     }
relock() [2/2]
static bool QOrderedMutexLocker::relock (QMutex * mtx1, QMutex * mtx2) inline static
Definition at line 97 of file qorderedmutexlocker_p.h.
     {
         // mtx1 is already locked, mtx2 not... do we need to unlock and relock?
         if (mtx1 == mtx2)
             return false;
         if (mtx1 < mtx2) {
             mtx2->lockInline();
             return true;
         }
         if (!mtx2->tryLockInline()) {
             mtx1->unlock();
             mtx2->lock();
             mtx1->lock();
         }
         return true;
     }
unlock()
void QOrderedMutexLocker::unlock () inline
Definition at line 88 of file qorderedmutexlocker_p.h.
Referenced by QObject::moveToThread(), and ~QOrderedMutexLocker().
     {
         if (locked) {
             if (mtx1) mtx1->unlockInline();
             if (mtx2) mtx2->unlockInline();
             locked = false;
         }
     }
Properties
locked
bool QOrderedMutexLocker::locked private
Definition at line 116 of file qorderedmutexlocker_p.h.
Referenced by relock(), and unlock().
mtx1
QMutex* QOrderedMutexLocker::mtx1 private
Definition at line 115 of file qorderedmutexlocker_p.h.
Referenced by relock(), and unlock().
mtx2
QMutex * QOrderedMutexLocker::mtx2 private
Definition at line 115 of file qorderedmutexlocker_p.h.
Referenced by relock(), and unlock().
The documentation for this class was generated from the following file:
/src/corelib/thread/qorderedmutexlocker_p.h