Qt 4.8: QDeclarativeDataBlob Class Reference
QDeclarativeDataBlob Class Reference abstract
The QDeclarativeDataBlob encapsulates a data request that can be issued to a QDeclarativeDataLoader.
#include <qdeclarativetypeloader_p.h>
Public Types
enum Status {
Null, Loading, WaitingForDependencies, Complete,
Error
}
This enum describes the status of the data blob.
enum Type { QmlFile, JavaScriptFile, QmldirFile }
This enum describes the type of the data blob.
Public Functions
void addDependency (QDeclarativeDataBlob *)
Wait for blob to become complete or to error.
QList< QDeclarativeError > errors () const
Return the errors on this blob.
QUrl finalUrl () const
Returns the final url of the data.
bool isComplete () const
Returns true if the status is Complete.
bool isCompleteOrError () const
Returns true if the status is Complete or Error.
bool isError () const
Returns true if the status is Error.
bool isLoading () const
Returns true if the status is Loading.
bool isNull () const
Returns true if the status is Null.
bool isWaiting () const
Returns true if the status is WaitingForDependencies.
qreal progress () const
Returns the data download progress from 0 to 1.
QDeclarativeDataBlob (const QUrl &, Type)
Create a new QDeclarativeDataBlob for url and of the provided type.
void setError (const QDeclarativeError &)
Mark this blob as having errors.
void setError (const QList< QDeclarativeError > &errors)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Status status () const
Returns the blob's status.
Type type () const
Returns the type provided to the constructor.
QUrl url () const
Returns the blob url passed to the constructor.
virtual ~QDeclarativeDataBlob ()
Public Functions inherited from QDeclarativeRefCount
void addref ()
QDeclarativeRefCount ()
void release ()
virtual ~QDeclarativeRefCount ()
Protected Functions
virtual void allDependenciesDone ()
Called when all blobs waited for have completed.
virtual void dataReceived (const QByteArray &)=0
Invoked when data for the blob is received.
virtual void dependencyComplete (QDeclarativeDataBlob *)
Called if blob, which was previously waited for, has completed.
virtual void dependencyError (QDeclarativeDataBlob *)
Called if blob, which was previously waited for, has an error.
virtual void done ()
Invoked once data has either been received or a network error occurred, and all dependencies are complete.
virtual void downloadProgressChanged (qreal)
Called when the download progress of this blob changes.
virtual void networkError (QNetworkReply::NetworkError)
Invoked if there is a network error while fetching this blob.
Private Functions
void cancelAllWaitingFor ()
void notifyAllWaitingOnMe ()
void notifyComplete (QDeclarativeDataBlob *)
void tryDone ()
Properties
QList< QDeclarativeError > m_errors
QUrl m_finalUrl
bool m_inCallback:1
bool m_isDone:1
QDeclarativeDataLoader * m_manager
qreal m_progress
int m_redirectCount:30
Status m_status
Type m_type
QUrl m_url
QList< QDeclarativeDataBlob * > m_waitingFor
QList< QDeclarativeDataBlob * > m_waitingOnMe
Friends
class QDeclarativeDataLoader
Detailed Description
The QDeclarativeDataBlob encapsulates a data request that can be issued to a QDeclarativeDataLoader.
Warning
This function is not part of the public interface.
QDeclarativeDataBlob's are loaded by a QDeclarativeDataLoader. The user creates the QDeclarativeDataBlob and then calls QDeclarativeDataLoader::load() or QDeclarativeDataLoader::loadWithStaticData() to load it. The QDeclarativeDataLoader invokes callbacks on the QDeclarativeDataBlob as data becomes available.
Definition at line 74 of file qdeclarativetypeloader_p.h.
Enumerations
Status
enum QDeclarativeDataBlob::Status
This enum describes the status of the data blob.
Null The blob has not yet been loaded by a QDeclarativeDataLoader
Loading The blob is loading network data. The QDeclarativeDataBlob::setData() callback has not yet been invoked or has not yet returned.
WaitingForDependencies The blob is waiting for dependencies to be done before continueing. This status only occurs after the QDeclarativeDataBlob::setData() callback has been made, and when the blob has outstanding dependencies.
Complete The blob's data has been loaded and all dependencies are done.
Error An error has been set on this blob.
Enumerator
Null
Loading
WaitingForDependencies
Complete
Error
Definition at line 77 of file qdeclarativetypeloader_p.h.
                 {
         Null,                    // Prior to QDeclarativeDataLoader::load()
         Loading,                 // Prior to data being received and dataReceived() being called
         WaitingForDependencies,  // While there are outstanding addDependency()s
         Complete,                // Finished
         Error                    // Error
     };
Type
enum QDeclarativeDataBlob::Type
This enum describes the type of the data blob.
QmlFile This is a QDeclarativeTypeData
JavaScriptFile This is a QDeclarativeScriptData
QmldirFile This is a QDeclarativeQmldirData
Enumerator
QmlFile
JavaScriptFile
QmldirFile
Definition at line 85 of file qdeclarativetypeloader_p.h.
               {
         QmlFile,
         JavaScriptFile,
         QmldirFile
     };
Constructors and Destructors
QDeclarativeDataBlob()
QDeclarativeDataBlob::QDeclarativeDataBlob (const QUrl & url, Type type)
Create a new QDeclarativeDataBlob for url and of the provided type.
Definition at line 134 of file qdeclarativetypeloader.cpp.
 : m_type(type), m_status(Null), m_progress(0), m_url(url), m_finalUrl(url), m_manager(0),
   m_redirectCount(0), m_inCallback(false), m_isDone(false)
 {
 }
~QDeclarativeDataBlob()
QDeclarativeDataBlob::~QDeclarativeDataBlob () virtual
Warning
This function is not part of the public interface.
Definition at line 141 of file qdeclarativetypeloader.cpp.
 {
     Q_ASSERT(m_waitingOnMe.isEmpty());
     cancelAllWaitingFor();
 }
Functions
addDependency()
void QDeclarativeDataBlob::addDependency (QDeclarativeDataBlob * blob)
Wait for blob to become complete or to error.
If blob is already complete or in error, or this blob is already complete, this has no effect.
Definition at line 281 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeData::dataReceived(), and QDeclarativeTypeData::resolveTypes().
 {
     Q_ASSERT(status() != Null);
     if (!blob ||
         blob->status() == Error || blob->status() == Complete ||
         status() == Error || status() == Complete ||
         m_waitingFor.contains(blob))
         return;
     blob->addref();
     m_status = WaitingForDependencies;
     m_waitingFor.append(blob);
     blob->m_waitingOnMe.append(this);
 }
allDependenciesDone()
void QDeclarativeDataBlob::allDependenciesDone () protected virtual
Called when all blobs waited for have completed.
This occurs regardless of whether they are in error, or complete state.
The default implementation does nothing.
Reimplemented in QDeclarativeTypeData.
Definition at line 397 of file qdeclarativetypeloader.cpp.
Referenced by notifyComplete(), and QDeclarativeDataLoader::setData().
 {
 }
cancelAllWaitingFor()
void QDeclarativeDataBlob::cancelAllWaitingFor () private
Definition at line 422 of file qdeclarativetypeloader.cpp.
Referenced by setError(), and ~QDeclarativeDataBlob().
 {
     while (m_waitingFor.count()) {
         QDeclarativeDataBlob *blob = m_waitingFor.takeLast();
         Q_ASSERT(blob->m_waitingOnMe.contains(this));
         blob->m_waitingOnMe.removeOne(this);
         blob->release();
     }
 }
dataReceived()
void QDeclarativeDataBlob::dataReceived (const QByteArray & data) protected pure virtual
Invoked when data for the blob is received.
Implementors should use this callback to determine a blob's dependencies. Within this callback you may call setError() or addDependency().
Implemented in QDeclarativeQmldirData, QDeclarativeScriptData, and QDeclarativeTypeData.
Referenced by QDeclarativeDataLoader::setData().
dependencyComplete()
void QDeclarativeDataBlob::dependencyComplete (QDeclarativeDataBlob * blob) protected virtual
Called if blob, which was previously waited for, has completed.
The default implementation does nothing.
Definition at line 386 of file qdeclarativetypeloader.cpp.
Referenced by notifyComplete().
 {
     Q_UNUSED(blob);
 }
dependencyError()
void QDeclarativeDataBlob::dependencyError (QDeclarativeDataBlob * blob) protected virtual
Called if blob, which was previously waited for, has an error.
The default implementation does nothing.
Definition at line 376 of file qdeclarativetypeloader.cpp.
Referenced by notifyComplete().
 {
     Q_UNUSED(blob);
 }
done()
void QDeclarativeDataBlob::done () protected virtual
Invoked once data has either been received or a network error occurred, and all dependencies are complete.
You can set an error in this method, but you cannot add new dependencies. Implementors should use this callback to finalize processing of data.
The default implementation does nothing.
Reimplemented in QDeclarativeTypeData.
Definition at line 314 of file qdeclarativetypeloader.cpp.
Referenced by tryDone().
 {
 }
downloadProgressChanged()
void QDeclarativeDataBlob::downloadProgressChanged (qreal progress) protected virtual
Called when the download progress of this blob changes.
progress goes from 0 to 1.
Reimplemented in QDeclarativeTypeData.
Definition at line 405 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeDataLoader::load(), and QDeclarativeDataLoader::networkReplyProgress().
 {
     Q_UNUSED(progress);
 }
errors()
QList< QDeclarativeError > QDeclarativeDataBlob::errors () const
Return the errors on this blob.
Definition at line 244 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeData::done(), QDeclarativeComponentPrivate::fromTypeData(), QDeclarativeDomDocument::load(), and setError().
 {
     return m_errors;
 }
finalUrl()
QUrl QDeclarativeDataBlob::finalUrl () const
Returns the final url of the data.
Initially this is the same as url(), but if a network redirect happens while fetching the data, this url is updated to reflect the new location.
Definition at line 236 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeCompiler::compileTree(), QDeclarativeTypeData::dataReceived(), QDeclarativeTypeData::done(), QDeclarativeComponentPrivate::fromTypeData(), and QDeclarativeTypeData::resolveTypes().
 {
     return m_finalUrl;
 }
isComplete()
bool QDeclarativeDataBlob::isComplete () const
Returns true if the status is Complete.
Definition at line 191 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), and isCompleteOrError().
 {
     return m_status == Complete;
 }
isCompleteOrError()
bool QDeclarativeDataBlob::isCompleteOrError () const
Returns true if the status is Complete or Error.
Definition at line 207 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeData::done(), QDeclarativeDomDocument::load(), QDeclarativeComponent::loadUrl(), and QDeclarativeComponent::setData().
 {
     return isComplete() || isError();
 }
isError()
bool QDeclarativeDataBlob::isError () const
Returns true if the status is Error.
Definition at line 199 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeData::done(), QDeclarativeComponentPrivate::fromTypeData(), isCompleteOrError(), QDeclarativeDomDocument::load(), notifyComplete(), and QDeclarativeDataLoader::setData().
 {
     return m_status == Error;
 }
isLoading()
bool QDeclarativeDataBlob::isLoading () const
Returns true if the status is Loading.
Definition at line 175 of file qdeclarativetypeloader.cpp.
 {
     return m_status == Loading;
 }
isNull()
bool QDeclarativeDataBlob::isNull () const
Returns true if the status is Null.
Definition at line 167 of file qdeclarativetypeloader.cpp.
 {
     return m_status == Null;
 }
isWaiting()
bool QDeclarativeDataBlob::isWaiting () const
Returns true if the status is WaitingForDependencies.
Definition at line 183 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeDataLoader::setData().
 {
     return m_status == WaitingForDependencies;
 }
networkError()
void QDeclarativeDataBlob::networkError (QNetworkReply::NetworkError networkError) protected virtual
Invoked if there is a network error while fetching this blob.
The default implementation sets an appropriate QDeclarativeError.
Definition at line 323 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeDataLoader::load(), and QDeclarativeDataLoader::networkReplyFinished().
 {
     Q_UNUSED(networkError);
     QDeclarativeError error;
     error.setUrl(m_finalUrl);
     const char *errorString = 0;
     switch (networkError) {
         default:
             errorString = "Network error";
             break;
         case QNetworkReply::ConnectionRefusedError:
             errorString = "Connection refused";
             break;
         case QNetworkReply::RemoteHostClosedError:
             errorString = "Remote host closed the connection";
             break;
         case QNetworkReply::HostNotFoundError:
             errorString = "Host not found";
             break;
         case QNetworkReply::TimeoutError:
             errorString = "Timeout";
             break;
         case QNetworkReply::ProxyConnectionRefusedError:
         case QNetworkReply::ProxyConnectionClosedError:
         case QNetworkReply::ProxyNotFoundError:
         case QNetworkReply::ProxyTimeoutError:
         case QNetworkReply::ProxyAuthenticationRequiredError:
         case QNetworkReply::UnknownProxyError:
             errorString = "Proxy error";
             break;
         case QNetworkReply::ContentAccessDenied:
             errorString = "Access denied";
             break;
         case QNetworkReply::ContentNotFoundError:
             errorString = "File not found";
             break;
         case QNetworkReply::AuthenticationRequiredError:
             errorString = "Authentication required";
             break;
     };
     error.setDescription(QLatin1String(errorString));
     setError(error);
 }
notifyAllWaitingOnMe()
void QDeclarativeDataBlob::notifyAllWaitingOnMe () private
Definition at line 435 of file qdeclarativetypeloader.cpp.
Referenced by tryDone().
 {
     while (m_waitingOnMe.count()) {
         QDeclarativeDataBlob *blob = m_waitingOnMe.takeLast();
         Q_ASSERT(blob->m_waitingFor.contains(this));
         blob->notifyComplete(this);
     }
 }
notifyComplete()
void QDeclarativeDataBlob::notifyComplete (QDeclarativeDataBlob * blob) private
Definition at line 446 of file qdeclarativetypeloader.cpp.
Referenced by notifyAllWaitingOnMe().
 {
     Q_ASSERT(m_waitingFor.contains(blob));
     Q_ASSERT(blob->status() == Error || blob->status() == Complete);
     m_inCallback = true;
     if (blob->status() == Error) {
         dependencyError(blob);
     } else if (blob->status() == Complete) {
         dependencyComplete(blob);
     }
     m_waitingFor.removeOne(blob);
     blob->release();
     if (!isError() && m_waitingFor.isEmpty())
         allDependenciesDone();
     m_inCallback = false;
     tryDone();
 }
progress()
qreal QDeclarativeDataBlob::progress () const
Returns the data download progress from 0 to 1.
Definition at line 215 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeComponent::loadUrl().
 {
     return m_progress;
 }
setError() [1/2]
void QDeclarativeDataBlob::setError (const QDeclarativeError & errors)
Mark this blob as having errors.
All outstanding dependencies will be cancelled. Requests to add new dependencies will be ignored. Entry into the Error state is irreversable, although you can change the specific errors by additional calls to setError.
Definition at line 256 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeData::compile(), QDeclarativeTypeData::dataReceived(), QDeclarativeTypeData::done(), QDeclarativeDataLoader::load(), networkError(), and QDeclarativeTypeData::resolveTypes().
 {
     QList<QDeclarativeError> l;
     l << errors;
     setError(l);
 }
setError() [2/2]
void QDeclarativeDataBlob::setError (const QList< QDeclarativeError > & errors)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 266 of file qdeclarativetypeloader.cpp.
 {
     m_status = Error;
     m_errors = errors;
     cancelAllWaitingFor();
     if (!m_inCallback)
         tryDone();
 }
status()
QDeclarativeDataBlob::Status QDeclarativeDataBlob::status () const
Returns the blob's status.
Definition at line 159 of file qdeclarativetypeloader.cpp.
Referenced by addDependency(), QDeclarativeDataLoader::load(), QDeclarativeDataLoader::loadWithStaticData(), notifyComplete(), QDeclarativeDataLoader::setData(), and tryDone().
 {
     return m_status;
 }
tryDone()
void QDeclarativeDataBlob::tryDone () private
Definition at line 410 of file qdeclarativetypeloader.cpp.
Referenced by notifyComplete(), QDeclarativeDataLoader::setData(), and setError().
 {
     if (status() != Loading && m_waitingFor.isEmpty() && !m_isDone) {
         if (status() != Error)
             m_status = Complete;
         m_isDone = true;
         done();
         notifyAllWaitingOnMe();
     }
 }
type()
QDeclarativeDataBlob::Type QDeclarativeDataBlob::type () const
Returns the type provided to the constructor.
Definition at line 151 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeData::dataReceived(), QDeclarativeTypeData::done(), and QDeclarativeTypeData::resolveTypes().
 {
     return m_type;
 }
url()
QUrl QDeclarativeDataBlob::url () const
Returns the blob url passed to the constructor.
If a network redirect happens while fetching the data, this url remains the same.
See also
finalUrl()
Definition at line 226 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeData::done(), QDeclarativeTypeData::qmldirForUrl(), and QDeclarativeTypeData::resolveTypes().
 {
     return m_url;
 }
Friends and Related Functions
QDeclarativeDataLoader
friend class QDeclarativeDataLoader friend
Definition at line 129 of file qdeclarativetypeloader_p.h.
Properties
m_errors
QList<QDeclarativeError> QDeclarativeDataBlob::m_errors private
Definition at line 154 of file qdeclarativetypeloader_p.h.
Referenced by errors(), and setError().
m_finalUrl
QUrl QDeclarativeDataBlob::m_finalUrl private
Definition at line 140 of file qdeclarativetypeloader_p.h.
Referenced by finalUrl(), networkError(), and QDeclarativeDataLoader::networkReplyFinished().
m_inCallback
bool QDeclarativeDataBlob::m_inCallback private
Definition at line 151 of file qdeclarativetypeloader_p.h.
Referenced by notifyComplete(), QDeclarativeDataLoader::setData(), and setError().
m_isDone
bool QDeclarativeDataBlob::m_isDone private
Definition at line 152 of file qdeclarativetypeloader_p.h.
Referenced by tryDone().
m_manager
QDeclarativeDataLoader* QDeclarativeDataBlob::m_manager private
Definition at line 149 of file qdeclarativetypeloader_p.h.
Referenced by QDeclarativeDataLoader::load(), and QDeclarativeDataLoader::loadWithStaticData().
m_progress
qreal QDeclarativeDataBlob::m_progress private
Definition at line 137 of file qdeclarativetypeloader_p.h.
Referenced by QDeclarativeDataLoader::load(), QDeclarativeDataLoader::networkReplyProgress(), and progress().
m_redirectCount
int QDeclarativeDataBlob::m_redirectCount private
Definition at line 150 of file qdeclarativetypeloader_p.h.
Referenced by QDeclarativeDataLoader::networkReplyFinished().
m_status
Status QDeclarativeDataBlob::m_status private
Definition at line 136 of file qdeclarativetypeloader_p.h.
Referenced by addDependency(), isComplete(), isError(), isLoading(), isNull(), isWaiting(), QDeclarativeDataLoader::load(), QDeclarativeDataLoader::loadWithStaticData(), QDeclarativeDataLoader::setData(), setError(), status(), and tryDone().
m_type
Type QDeclarativeDataBlob::m_type private
Definition at line 135 of file qdeclarativetypeloader_p.h.
Referenced by type().
m_url
QUrl QDeclarativeDataBlob::m_url private
Definition at line 139 of file qdeclarativetypeloader_p.h.
Referenced by QDeclarativeDataLoader::load(), and url().
m_waitingFor
QList<QDeclarativeDataBlob *> QDeclarativeDataBlob::m_waitingFor private
Definition at line 146 of file qdeclarativetypeloader_p.h.
Referenced by addDependency(), cancelAllWaitingFor(), notifyAllWaitingOnMe(), notifyComplete(), and tryDone().
m_waitingOnMe
QList<QDeclarativeDataBlob *> QDeclarativeDataBlob::m_waitingOnMe private
Definition at line 143 of file qdeclarativetypeloader_p.h.
Referenced by addDependency(), cancelAllWaitingFor(), notifyAllWaitingOnMe(), and ~QDeclarativeDataBlob().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativetypeloader_p.h
/src/declarative/qml/qdeclarativetypeloader.cpp