Qt 4.8: QPatternist::NamespaceSupport Class Reference
QPatternist::NamespaceSupport Class Reference
XML Schema Processing
A helper class for handling nested namespace declarations.
#include <qnamespacesupport_p.h>
Public Types
enum NameType { AttributeName, ElementName }
Public Functions
QList< QXmlName > namespaceBindings () const
NamespaceSupport ()
NamespaceSupport (NamePool &namePool)
void popContext ()
QXmlName::PrefixCode prefix (const QXmlName::NamespaceCode code) const
bool processName (const QString &qualifiedName, NameType type, QXmlName &name) const
void pushContext ()
void setPrefix (const QXmlName::PrefixCode prefixCode, const QXmlName::NamespaceCode namespaceCode)
void setPrefixes (const QXmlStreamNamespaceDeclarations &declarations)
void setTargetNamespace (const QXmlName::NamespaceCode code)
QXmlName::NamespaceCode uri (const QXmlName::PrefixCode code) const
Private Types
typedef QHash< QXmlName::PrefixCode, QXmlName::NamespaceCode > NamespaceHash
Properties
NamePool * m_namePool
NamespaceHash m_ns
QStack< NamespaceHash > m_nsStack
Detailed Description
A helper class for handling nested namespace declarations.
This class is mostly an adaption of QXmlNamespaceSupport to the NamePool mechanism used in XmlPatterns.
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 78 of file qnamespacesupport_p.h.
Typedefs
NamespaceHash
typedef QHash<QXmlName::PrefixCode, QXmlName::NamespaceCode> QPatternist::NamespaceSupport::NamespaceHash private
Definition at line 161 of file qnamespacesupport_p.h.
Enumerations
NameType
enum QPatternist::NamespaceSupport::NameType
Describes whether the name to process is an attribute or element.
Enumerator
AttributeName
An attribute name to process.
ElementName
An element name to process.
Definition at line 84 of file qnamespacesupport_p.h.
             {
                 AttributeName,
                 ElementName
             };
Constructors and Destructors
NamespaceSupport() [1/2]
NamespaceSupport::NamespaceSupport ()
Creates an empty namespace support object.
Definition at line 58 of file qnamespacesupport.cpp.
 {
 }
NamespaceSupport() [2/2]
NamespaceSupport::NamespaceSupport (NamePool & namePool)
Creates a new namespace support object.
Parameters
namePool The name pool where all processed names are stored in.
Definition at line 62 of file qnamespacesupport.cpp.
     : m_namePool(&namePool)
 {
     // the XML namespace
     m_ns.insert(StandardPrefixes::xml, StandardNamespaces::xml);
 }
Functions
namespaceBindings()
QList< QXmlName > NamespaceSupport::namespaceBindings () const
Returns the list of namespace bindings.
Definition at line 147 of file qnamespacesupport.cpp.
Referenced by QPatternist::XsdSchemaParser::readXPathAttribute(), and QPatternist::XsdSchemaParser::readXPathExpression().
 {
     QList<QXmlName> bindings;
     QHashIterator<QXmlName::PrefixCode, QXmlName::NamespaceCode> it(m_ns);
     while (it.hasNext()) {
         it.next();
         bindings.append(QXmlName(it.value(), StandardLocalNames::empty, it.key()));
     }
     return bindings;
 }
popContext()
void NamespaceSupport::popContext ()
Pops the current namespace mapping from the stack.
Definition at line 140 of file qnamespacesupport.cpp.
Referenced by QPatternist::XsdSchemaParser::parseUnknown(), QPatternist::XsdSchemaParser::parseUnknownDocumentation(), and QPatternist::ElementNamespaceHandler::~ElementNamespaceHandler().
 {
     m_ns.clear();
     if(!m_nsStack.isEmpty())
         m_ns = m_nsStack.pop();
 }
prefix()
QXmlName::PrefixCode NamespaceSupport::prefix (const QXmlName::NamespaceCode code) const
Returns the prefix code for the given namespace code.
Definition at line 90 of file qnamespacesupport.cpp.
 {
     NamespaceHash::const_iterator itc, it = m_ns.constBegin();
     while ((itc=it) != m_ns.constEnd()) {
         ++it;
         if (*itc == namespaceCode)
             return itc.key();
     }
     return 0;
 }
processName()
bool NamespaceSupport::processName (const QString & qualifiedName, NameType type, QXmlName & name) const
Converts the given qualifiedName to a resolved QXmlName name according to the current namespace mapping.
Parameters
qualifiedName The full qualified name.
type The type of name processing.
name The resolved QXmlName.
Returns
true if the name could be processed correctly or false if the namespace prefix is unknown.
Definition at line 106 of file qnamespacesupport.cpp.
Referenced by QPatternist::XsdSchemaParser::convertName().
 {
     int len = qname.size();
     const QChar *data = qname.constData();
     for (int pos = 0; pos < len; ++pos) {
         if (data[pos] == QLatin1Char(':')) {
             const QXmlName::PrefixCode prefixCode = m_namePool->allocatePrefix(qname.left(pos));
             if (!m_ns.contains(prefixCode))
                 return false;
             const QXmlName::NamespaceCode namespaceCode = uri(prefixCode);
             const QXmlName::LocalNameCode localNameCode = m_namePool->allocateLocalName(qname.mid(pos + 1));
             name = QXmlName(namespaceCode, localNameCode, prefixCode);
             return true;
         }
     }
     // there was no ':'
     QXmlName::NamespaceCode namespaceCode = 0;
     // attributes don't take default namespace
     if (type == ElementName && !m_ns.isEmpty()) {
         namespaceCode = m_ns.value(0);   // get default namespace
     }
     const QXmlName::LocalNameCode localNameCode = m_namePool->allocateLocalName(qname);
     name = QXmlName(namespaceCode, localNameCode, 0);
     return true;
 }
pushContext()
void NamespaceSupport::pushContext ()
Pushes the current namespace mapping onto the stack.
Definition at line 135 of file qnamespacesupport.cpp.
Referenced by QPatternist::ElementNamespaceHandler::ElementNamespaceHandler(), QPatternist::XsdSchemaParser::parseUnknown(), and QPatternist::XsdSchemaParser::parseUnknownDocumentation().
 {
     m_nsStack.push(m_ns);
 }
setPrefix()
void NamespaceSupport::setPrefix (const QXmlName::PrefixCode prefixCode, const QXmlName::NamespaceCode namespaceCode)
Adds a new prefix-to-namespace binding.
Parameters
prefixCode The name pool code for the prefix.
namespaceCode The name pool code for the namespace.
Definition at line 69 of file qnamespacesupport.cpp.
 {
     m_ns.insert(prefixCode, namespaceCode);
 }
setPrefixes()
void NamespaceSupport::setPrefixes (const QXmlStreamNamespaceDeclarations & declarations)
Adds the prefix-to-namespace bindings from declarations to the namespace support.
Definition at line 74 of file qnamespacesupport.cpp.
Referenced by QPatternist::ElementNamespaceHandler::ElementNamespaceHandler(), QPatternist::XsdSchemaParser::parseUnknown(), and QPatternist::XsdSchemaParser::parseUnknownDocumentation().
 {
     for (int i = 0; i < declarations.count(); i++) {
         const QXmlStreamNamespaceDeclaration declaration = declarations.at(i);
         const QXmlName::PrefixCode prefixCode = m_namePool->allocatePrefix(declaration.prefix().toString());
         const QXmlName::NamespaceCode namespaceCode = m_namePool->allocateNamespace(declaration.namespaceUri().toString());
         m_ns.insert(prefixCode, namespaceCode);
     }
 }
setTargetNamespace()
void NamespaceSupport::setTargetNamespace (const QXmlName::NamespaceCode code)
Sets the name pool code of the target namespace of the schema the namespace support works on.
Definition at line 85 of file qnamespacesupport.cpp.
Referenced by QPatternist::XsdSchemaParser::setTargetNamespaceExtended().
 {
     m_ns.insert(0, namespaceCode);
 }
uri()
QXmlName::NamespaceCode NamespaceSupport::uri (const QXmlName::PrefixCode code) const
Returns the namespace code for the given prefix code.
Definition at line 101 of file qnamespacesupport.cpp.
Referenced by processName().
 {
     return m_ns.value(prefixCode);
 }
Properties
m_namePool
NamePool* QPatternist::NamespaceSupport::m_namePool private
Definition at line 163 of file qnamespacesupport_p.h.
Referenced by processName(), and setPrefixes().
m_ns
NamespaceHash QPatternist::NamespaceSupport::m_ns private
Definition at line 165 of file qnamespacesupport_p.h.
Referenced by namespaceBindings(), NamespaceSupport(), popContext(), prefix(), processName(), pushContext(), setPrefix(), setPrefixes(), setTargetNamespace(), and uri().
m_nsStack
QStack<NamespaceHash> QPatternist::NamespaceSupport::m_nsStack private
Definition at line 164 of file qnamespacesupport_p.h.
Referenced by popContext(), and pushContext().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qnamespacesupport_p.h
/src/xmlpatterns/schema/qnamespacesupport.cpp