Qt 4.8: QTextLength Class Reference
QTextLength Class Reference
The QTextLength class encapsulates the different types of length used in a QTextDocument.
#include <qtextformat.h>
Public Types
enum Type { VariableLength = 0, FixedLength, PercentageLength }
This enum describes the different types a length object can have.
Public Functions
operator QVariant () const
Returns the text length as a QVariant.
bool operator!= (const QTextLength &other) const
Returns true if this text length is different from the other text length.
bool operator== (const QTextLength &other) const
Returns true if this text length is the same as the other text length.
QTextLength ()
Constructs a new length object which represents a variable size.
QTextLength (Type type, qreal value)
Constructs a new length object of the given type and value.
qreal rawValue () const
Returns the constraint value that is specific for the type of the length.
Type type () const
Returns the type of this length object.
qreal value (qreal maximumLength) const
Returns the effective length, constrained by the type of the length object and the specified maximumLength.
Properties
qreal fixedValueOrPercentage
Type lengthType
Friends
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QTextLength &)
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QTextLength &)
Detailed Description
The QTextLength class encapsulates the different types of length used in a QTextDocument.
Note
This class or function is reentrant.
When we specify a value for the length of an element in a text document, we often need to provide some other information so that the length is used in the way we expect. For example, when we specify a table width, the value can represent a fixed number of pixels, or it can be a percentage value. This information changes both the meaning of the value and the way it is used.
Generally, this class is used to specify table widths. These can be specified either as a fixed amount of pixels, as a percentage of the containing frame's width, or by a variable width that allows it to take up just the space it requires.
See also
QTextTable
Definition at line 84 of file qtextformat.h.
Enumerations
Type
enum QTextLength::Type
This enum describes the different types a length object can have.
VariableLength The width of the object is variable
FixedLength The width of the object is fixed
PercentageLength The width of the object is in percentage of the maximum width
See also
type()
Enumerator
VariableLength
FixedLength
PercentageLength
Definition at line 87 of file qtextformat.h.
 { VariableLength = 0, FixedLength, PercentageLength };
Constructors and Destructors
QTextLength() [1/2]
QTextLength::QTextLength () inline explicit
Constructs a new length object which represents a variable size.
Definition at line 89 of file qtextformat.h.
Referenced by QTextFrameFormat::setHeight(), and QTextFrameFormat::setWidth().
 : lengthType(VariableLength), fixedValueOrPercentage(0) {}
QTextLength() [2/2]
QTextLength::QTextLength (Type type, qreal value) inline explicit
Constructs a new length object of the given type and value.
Definition at line 121 of file qtextformat.h.
     : lengthType(atype), fixedValueOrPercentage(avalue) {}
Functions
operator QVariant()
QTextLength::operator QVariant () const
Returns the text length as a QVariant.
Definition at line 173 of file qtextformat.cpp.
 {
     return QVariant(QVariant::TextLength, this);
 }
operator!=()
bool QTextLength::operator!= (const QTextLength & other) const inline
Returns true if this text length is different from the other text length.
Definition at line 109 of file qtextformat.h.
     { return lengthType != other.lengthType
              || !qFuzzyCompare(fixedValueOrPercentage, other.fixedValueOrPercentage); }
operator==()
bool QTextLength::operator== (const QTextLength & other) const inline
Returns true if this text length is the same as the other text length.
Definition at line 106 of file qtextformat.h.
Referenced by QTextFormat::isTableCellFormat(), and QTextFormat::operator!=().
     { return lengthType == other.lengthType
              && qFuzzyCompare(fixedValueOrPercentage, other.fixedValueOrPercentage); }
rawValue()
qreal QTextLength::rawValue () const inline
Returns the constraint value that is specific for the type of the length.
If the length is QTextLength::PercentageLength then the raw value is in percent, in the range of 0 to 100. If the length is QTextLength::FixedLength then that fixed amount is returned. For variable lengths, zero is returned.
Definition at line 104 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitTextLength(), and QTextDocumentLayoutPrivate::layoutTable().
 { return fixedValueOrPercentage; }
type()
Type QTextLength::type () const inline
Returns the type of this length object.
See also
QTextLength::Type
Definition at line 93 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitBlock(), QTextHtmlExporter::emitTextLength(), QTextFormat::isBlockFormat(), QTextFormat::isCharFormat(), QTextFormat::isFrameFormat(), QTextFormat::isImageFormat(), QTextFormat::isListFormat(), QTextFormat::isTableCellFormat(), QTextFormat::isTableFormat(), QTextFormat::isValid(), QTextDocumentLayoutPrivate::layoutFrame(), QTextDocumentLayoutPrivate::layoutTable(), and QTextHtmlImporter::scanTable().
 { return lengthType; }
value()
qreal QTextLength::value (qreal maximumLength) const inline
Returns the effective length, constrained by the type of the length object and the specified maximumLength.
See also
type()
Definition at line 94 of file qtextformat.h.
Referenced by QTextDocumentLayoutPrivate::drawBlock(), QTextFormat::isValid(), QTextDocumentLayoutPrivate::layoutFrame(), and QTextHtmlImporter::scanTable().
     {
         switch (lengthType) {
             case FixedLength: return fixedValueOrPercentage;
             case VariableLength: return maximumLength;
             case PercentageLength: return fixedValueOrPercentage * maximumLength / qreal(100);
         }
         return -1;
     }
Friends and Related Functions
operator<<
Q_GUI_EXPORT QDataStream& operator<< (QDataStream & , const QTextLength &) friend
Definition at line 179 of file qtextformat.cpp.
Referenced by QTextLength().
 {
     return stream << qint32(length.lengthType) << double(length.fixedValueOrPercentage);
 }
operator>>
Q_GUI_EXPORT QDataStream& operator>> (QDataStream & , QTextLength &) friend
Definition at line 184 of file qtextformat.cpp.
Referenced by QTextLength().
 {
     qint32 type;
     double fixedValueOrPercentage;
     stream >> type >> fixedValueOrPercentage;
     length.fixedValueOrPercentage = fixedValueOrPercentage;
     length.lengthType = QTextLength::Type(type);
     return stream;
 }
Properties
fixedValueOrPercentage
qreal QTextLength::fixedValueOrPercentage private
Definition at line 116 of file qtextformat.h.
Referenced by operator!=(), operator<<(), operator==(), and operator>>().
lengthType
Type QTextLength::lengthType private
Definition at line 115 of file qtextformat.h.
Referenced by operator!=(), operator<<(), operator==(), and operator>>().
The documentation for this class was generated from the following files:
/src/gui/text/qtextformat.h
/src/gui/text/qtextformat.cpp