Qt 4.8: QDesktopServices Class Reference
QDesktopServices Class Reference
The QDesktopServices class provides methods for accessing common desktop services.
#include <qdesktopservices.h>
Public Types
enum StandardLocation {
DesktopLocation, DocumentsLocation, FontsLocation, ApplicationsLocation,
MusicLocation, MoviesLocation, PicturesLocation, TempLocation,
HomeLocation, DataLocation, CacheLocation
}
This enum describes the different locations that can be queried by QDesktopServices::storageLocation and QDesktopServices::displayName.
Static Public Functions
static QString displayName (StandardLocation type)
Returns a localized display name for the given location type or an empty QString if no relevant location can be found.
static bool openUrl (const QUrl &url)
Opens the given url in the appropriate Web browser for the user's desktop environment, and returns true if successful; otherwise returns false.
static void setUrlHandler (const QString &scheme, QObject *receiver, const char *method)
Sets the handler for the given scheme to be the handler method provided by the receiver object.
static QString storageLocation (StandardLocation type)
Returns the default system directory where files of type belong, or an empty string if the location cannot be determined.
static void unsetUrlHandler (const QString &scheme)
Removes a previously set URL handler for the specified scheme.
Detailed Description
The QDesktopServices class provides methods for accessing common desktop services.
Since
4.2
Many desktop environments provide services that can be used by applications to perform common tasks, such as opening a web page, in a way that is both consistent and takes into account the user's application preferences.
This class contains functions that provide simple interfaces to these services that indicate whether they succeeded or failed.
The openUrl() function is used to open files located at arbitrary URLs in external applications. For URLs that correspond to resources on the local filing system (where the URL scheme is "file"), a suitable application will be used to open the file; otherwise, a web browser will be used to fetch and display the file.
The user's desktop settings control whether certain executable file types are opened for browsing, or if they are executed instead. Some desktop environments are configured to prevent users from executing files obtained from non-local URLs, or to ask the user's permission before doing so.
URL Handlers
The behavior of the openUrl() function can be customized for individual URL schemes to allow applications to override the default handling behavior for certain types of URLs.
The dispatch mechanism allows only one custom handler to be used for each URL scheme; this is set using the setUrlHandler() function. Each handler is implemented as a slot which accepts only a single QUrl argument.
The existing handlers for each scheme can be removed with the unsetUrlHandler() function. This returns the handling behavior for the given scheme to the default behavior.
This system makes it easy to implement a help system, for example. Help could be provided in labels and text browsers using help://myapplication/mytopic URLs, and by registering a handler it becomes possible to display the help text inside the application:
class MyHelpHandler : public QObject
{
    Q_OBJECT
public:
    ...
public slots:
    void showHelp(const QUrl &url);
};
QDesktopServices::setUrlHandler("help", helpInstance, "showHelp");
If inside the handler you decide that you can't open the requested URL, you can just call QDesktopServices::openUrl() again with the same argument, and it will try to open the URL using the appropriate mechanism for the user's desktop environment.
See also
QSystemTrayIcon, QProcess
Definition at line 59 of file qdesktopservices.h.
Enumerations
StandardLocation
enum QDesktopServices::StandardLocation
This enum describes the different locations that can be queried by QDesktopServices::storageLocation and QDesktopServices::displayName.
Since
4.4
DesktopLocation Returns the user's desktop directory.
DocumentsLocation Returns the user's document.
FontsLocation Returns the user's fonts.
ApplicationsLocation Returns the user's applications.
MusicLocation Returns the users music.
MoviesLocation Returns the user's movies.
PicturesLocation Returns the user's pictures.
TempLocation Returns the system's temporary directory.
HomeLocation Returns the user's home directory.
DataLocation Returns a directory location where persistent application data can be stored. QCoreApplication::applicationName and QCoreApplication::organizationName should work on all platforms.
CacheLocation Returns a directory location where user-specific non-essential (cached) data should be written.
See also
storageLocation() displayName()
Enumerator
DesktopLocation
DocumentsLocation
FontsLocation
ApplicationsLocation
MusicLocation
MoviesLocation
PicturesLocation
TempLocation
HomeLocation
DataLocation
CacheLocation
Definition at line 66 of file qdesktopservices.h.
{
         DesktopLocation,
         DocumentsLocation,
         FontsLocation,
         ApplicationsLocation,
         MusicLocation,
         MoviesLocation,
         PicturesLocation,
         TempLocation,
         HomeLocation,
         DataLocation,
         CacheLocation
     };
Functions
displayName()
QString QDesktopServices::displayName (StandardLocation type) static
Returns a localized display name for the given location type or an empty QString if no relevant location can be found.
Definition at line 109 of file qdesktopservices_blackberry.cpp.
Referenced by getFullPath(), launchWebBrowser(), and openDocument().
 {
     return storageLocation(type);
 }
openUrl()
bool QDesktopServices::openUrl (const QUrl & url) static
Opens the given url in the appropriate Web browser for the user's desktop environment, and returns true if successful; otherwise returns false.
If the URL is a reference to a local file (i.e., the URL scheme is "file") then it will be opened with a suitable application instead of a Web browser.
The following example opens a file on the Windows file system residing on a path that contains spaces:
QDesktopServices::openUrl(QUrl("file:///C:/Documents and Settings/All Users/Desktop", QUrl::TolerantMode));
If a mailto URL is specified, the user's e-mail client will be used to open a composer window containing the options specified in the URL, similar to the way mailto links are handled by a Web browser.
For example, the following URL contains a recipient (user@.nosp@m.foo..nosp@m.com), a subject (Test), and a message body (Just a test):
mailto:user@foo.com?subject=Test&body=Just a test
Warning
Although many e-mail clients can send attachments and are Unicode-aware, the user may have configured their client without these features. Also, certain e-mail clients (e.g., Lotus Notes) have problems with long URLs.
Note
On Symbian OS, SwEvent capability is required to open the given url if the Web browser is already running.
See also
setUrlHandler()
Definition at line 190 of file qdesktopservices.cpp.
Referenced by QTextBrowserPrivate::_q_activateAnchor(), QTextControlPrivate::activateLinkUnderCursor(), and QDeclarativeEnginePrivate::desktopOpenUrl().
 {
     QOpenUrlHandlerRegistry *registry = handlerRegistry();
     QMutexLocker locker(&registry->mutex);
     static bool insideOpenUrlHandler = false;
     if (!insideOpenUrlHandler) {
         QOpenUrlHandlerRegistry::HandlerHash::ConstIterator handler = registry->handlers.constFind(url.scheme());
         if (handler != registry->handlers.constEnd()) {
             insideOpenUrlHandler = true;
             bool result = QMetaObject::invokeMethod(handler->receiver, handler->name.constData(), Qt::DirectConnection, Q_ARG(QUrl, url));
             insideOpenUrlHandler = false;
             return result; // ### support bool slot return type
         }
     }
     bool result;
     if (url.scheme() == QLatin1String("file"))
         result = openDocument(url);
     else
         result = launchWebBrowser(url);
     return result;
 }
setUrlHandler()
void QDesktopServices::setUrlHandler (const QString & scheme, QObject * receiver, const char * method) static
Sets the handler for the given scheme to be the handler method provided by the receiver object.
This function provides a way to customize the behavior of openUrl(). If openUrl() is called with a URL with the specified scheme then the given method on the receiver object is called instead of QDesktopServices launching an external application.
The provided method must be implemented as a slot that only accepts a single QUrl argument.
If setUrlHandler() is used to set a new handler for a scheme which already has a handler, the existing handler is simply replaced with the new one. Since QDesktopServices does not take ownership of handlers, no objects are deleted when a handler is replaced.
Note that the handler will always be called from within the same thread that calls QDesktopServices::openUrl().
See also
openUrl(), unsetUrlHandler()
Definition at line 237 of file qdesktopservices.cpp.
 {
     QOpenUrlHandlerRegistry *registry = handlerRegistry();
     QMutexLocker locker(&registry->mutex);
     if (!receiver) {
         registry->handlers.remove(scheme);
         return;
     }
     QOpenUrlHandlerRegistry::Handler h;
     h.receiver = receiver;
     h.name = method;
     registry->handlers.insert(scheme, h);
     QObject::connect(receiver, SIGNAL(destroyed(QObject*)),
                      registry, SLOT(handlerDestroyed(QObject*)));
 }
storageLocation()
QString QDesktopServices::storageLocation (StandardLocation type) static
Returns the default system directory where files of type belong, or an empty string if the location cannot be determined.
Since
4.4
Note
The storage location returned can be a directory that does not exist; i.e., it may need to be created by the system or the user.
On Symbian OS, ApplicationsLocation always point /sys/bin folder on the same drive with executable. FontsLocation always points to folder on ROM drive. Symbian OS does not have desktop concept, DesktopLocation returns same path as DocumentsLocation. Rest of the standard locations point to folder on same drive with executable, except that if executable is in ROM the folder from C drive is returned.
Definition at line 70 of file qdesktopservices_blackberry.cpp.
Referenced by displayName(), getFullPath(), launchWebBrowser(), openDocument(), and QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if (type == QDesktopServices::TempLocation)
         return QDir::tempPath();
     if (type == QDesktopServices::CacheLocation)
         return QDir::homePath() + QLatin1String("/Cache");
     QString path;
     const int index = QDir::homePath().lastIndexOf("/data");
     const QString sharedRoot = QDir::homePath().replace(index,
             QDir::homePath().length() - index, "/shared");
     switch (type) {
     case DataLocation:
     case DesktopLocation:
     case HomeLocation:
         path = QDir::homePath();
         break;
     case DocumentsLocation:
         path = sharedRoot + QLatin1String("/documents");
        break;
     case PicturesLocation:
         path = sharedRoot + QLatin1String("/photos");
         break;
     case MusicLocation:
         path = sharedRoot + QLatin1String("/music");
         break;
     case MoviesLocation:
         path = sharedRoot + QLatin1String("/videos");
         break;
     default:
         break;
     }
     return path;
 }
unsetUrlHandler()
void QDesktopServices::unsetUrlHandler (const QString & scheme) static
Removes a previously set URL handler for the specified scheme.
See also
setUrlHandler()
Definition at line 258 of file qdesktopservices.cpp.
 {
     setUrlHandler(scheme, 0, 0);
 }
The documentation for this class was generated from the following files:
/src/gui/util/qdesktopservices.h
/src/gui/util/qdesktopservices.cpp
/src/gui/util/qdesktopservices_blackberry.cpp
/src/gui/util/qdesktopservices_mac.cpp
/src/gui/util/qdesktopservices_qws.cpp
/src/gui/util/qdesktopservices_win.cpp
/src/gui/util/qdesktopservices_x11.cpp