Qt 4.8: QDeclarativeScaleGrid Class Reference
QDeclarativeScaleGrid Class Reference
The QDeclarativeScaleGrid class allows you to specify a 3x3 grid to use in scaling an image.
#include <qdeclarativescalegrid_p_p.h>
Signals
void borderChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int bottom () const
bool isNull () const
int left () const
QDeclarativeScaleGrid (QObject *parent=0)
int right () const
void setBottom (int)
void setLeft (int)
void setRight (int)
void setTop (int)
int top () const
~QDeclarativeScaleGrid ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
int _bottom
int _left
int _right
int _top
int bottom
int left
int right
int top
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QDeclarativeScaleGrid class allows you to specify a 3x3 grid to use in scaling an image.
Warning
This function is not part of the public interface.
Definition at line 60 of file qdeclarativescalegrid_p_p.h.
Constructors and Destructors
QDeclarativeScaleGrid()
QDeclarativeScaleGrid::QDeclarativeScaleGrid (QObject * parent = 0)
Definition at line 59 of file qdeclarativescalegrid.cpp.
                                                             : QObject(parent), _left(0), _top(0), _right(0), _bottom(0)
 {
 }
~QDeclarativeScaleGrid()
QDeclarativeScaleGrid::~QDeclarativeScaleGrid ()
Definition at line 63 of file qdeclarativescalegrid.cpp.
 {
 }
Functions
borderChanged
void QDeclarativeScaleGrid::borderChanged () signal
Referenced by setBottom(), setLeft(), setRight(), and setTop().
bottom()
int QDeclarativeScaleGrid::bottom () const inline
Definition at line 85 of file qdeclarativescalegrid_p_p.h.
 { return _bottom; }
isNull()
bool QDeclarativeScaleGrid::isNull () const
Definition at line 67 of file qdeclarativescalegrid.cpp.
 {
     return !_left && !_top && !_right && !_bottom;
 }
left()
int QDeclarativeScaleGrid::left () const inline
Definition at line 76 of file qdeclarativescalegrid_p_p.h.
 { return _left; }
right()
int QDeclarativeScaleGrid::right () const inline
Definition at line 82 of file qdeclarativescalegrid_p_p.h.
 { return _right; }
setBottom()
void QDeclarativeScaleGrid::setBottom (int pos)
Definition at line 96 of file qdeclarativescalegrid.cpp.
Referenced by QDeclarativeBorderImage::setGridScaledImage().
 {
     if (_bottom != pos) {
         _bottom = pos;
         emit borderChanged();
     }
 }
setLeft()
void QDeclarativeScaleGrid::setLeft (int pos)
Definition at line 72 of file qdeclarativescalegrid.cpp.
Referenced by QDeclarativeBorderImage::setGridScaledImage().
 {
     if (_left != pos) {
         _left = pos;
         emit borderChanged();
     }
 }
setRight()
void QDeclarativeScaleGrid::setRight (int pos)
Definition at line 88 of file qdeclarativescalegrid.cpp.
Referenced by QDeclarativeBorderImage::setGridScaledImage().
 {
     if (_right != pos) {
         _right = pos;
         emit borderChanged();
     }
 }
setTop()
void QDeclarativeScaleGrid::setTop (int pos)
Definition at line 80 of file qdeclarativescalegrid.cpp.
Referenced by QDeclarativeBorderImage::setGridScaledImage().
 {
     if (_top != pos) {
         _top = pos;
         emit borderChanged();
     }
 }
top()
int QDeclarativeScaleGrid::top () const inline
Definition at line 79 of file qdeclarativescalegrid_p_p.h.
 { return _top; }
Properties
_bottom
int QDeclarativeScaleGrid::_bottom private
Definition at line 95 of file qdeclarativescalegrid_p_p.h.
Referenced by isNull(), and setBottom().
_left
int QDeclarativeScaleGrid::_left private
Definition at line 92 of file qdeclarativescalegrid_p_p.h.
Referenced by isNull(), and setLeft().
_right
int QDeclarativeScaleGrid::_right private
Definition at line 94 of file qdeclarativescalegrid_p_p.h.
Referenced by isNull(), and setRight().
_top
int QDeclarativeScaleGrid::_top private
Definition at line 93 of file qdeclarativescalegrid_p_p.h.
Referenced by isNull(), and setTop().
bottom
int QDeclarativeScaleGrid::bottom private
Definition at line 68 of file qdeclarativescalegrid_p_p.h.
Referenced by QDeclarativeBorderImage::paint().
left
int QDeclarativeScaleGrid::left private
Definition at line 65 of file qdeclarativescalegrid_p_p.h.
Referenced by QDeclarativeBorderImage::paint().
right
int QDeclarativeScaleGrid::right private
Definition at line 67 of file qdeclarativescalegrid_p_p.h.
Referenced by QDeclarativeBorderImage::paint().
top
int QDeclarativeScaleGrid::top private
Definition at line 66 of file qdeclarativescalegrid_p_p.h.
Referenced by QDeclarativeBorderImage::paint().
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativescalegrid_p_p.h
/src/declarative/graphicsitems/qdeclarativescalegrid.cpp