Qt 4.8: QGLPoint Class Reference
QGLPoint Class Reference
#include <qgl2pexvertexarray_p.h>
Public Functions
operator QPointF ()
operator QPointF () const
QGLPoint (GLfloat new_x, GLfloat new_y)
QGLPoint (const QPointF &p)
QGLPoint (const QPointF *p)
Public Variables
GLfloat x
GLfloat y
Detailed Description
Definition at line 64 of file qgl2pexvertexarray_p.h.
Constructors and Destructors
QGLPoint() [1/3]
QGLPoint::QGLPoint (GLfloat new_x, GLfloat new_y) inline
Definition at line 67 of file qgl2pexvertexarray_p.h.
Referenced by QGL2PEXVertexArray::addQuad(), QGL2PEXVertexArray::addRect(), and QGL2PEXVertexArray::addVertex().
                                            :
         x(new_x), y(new_y) {};
QGLPoint() [2/3]
QGLPoint::QGLPoint (const QPointF & p) inline
Definition at line 70 of file qgl2pexvertexarray_p.h.
                                :
         x(p.x()), y(p.y()) {};
QGLPoint() [3/3]
QGLPoint::QGLPoint (const QPointF * p) inline
Definition at line 73 of file qgl2pexvertexarray_p.h.
                                :
         x(p->x()), y(p->y()) {};
Functions
operator QPointF() [1/2]
QGLPoint::operator QPointF () inline
Definition at line 79 of file qgl2pexvertexarray_p.h.
 {return QPointF(x,y);}
operator QPointF() [2/2]
QGLPoint::operator QPointF () const inline
Definition at line 80 of file qgl2pexvertexarray_p.h.
 {return QPointF(x,y);}
Properties
x
GLfloat QGLPoint::x
Definition at line 74 of file qgl2pexvertexarray_p.h.
Referenced by QGL2PaintEngineExPrivate::drawPixmapFragments(), and QGL2PEXVertexArray::vertexCount().
y
GLfloat QGLPoint::y
Definition at line 77 of file qgl2pexvertexarray_p.h.
Referenced by QGL2PaintEngineExPrivate::drawPixmapFragments(), and QGL2PEXVertexArray::vertexCount().
The documentation for this class was generated from the following file:
/src/opengl/gl2paintengineex/qgl2pexvertexarray_p.h