Qt 4.8: QUrlModel Class Reference
QUrlModel Class Reference
#include <qsidebar_p.h>
Public Types
enum Roles { UrlRole = Qt::UserRole + 1, EnabledRole = Qt::UserRole + 2 }
Public Functions
void addUrls (const QList< QUrl > &urls, int row=-1, bool move=true)
Add urls list into the list at row.
bool canDrop (QDragEnterEvent *event)
Decide based upon the data if it should be accepted or not.
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
Qt::ItemFlags flags (const QModelIndex &index) const
Reimplemented Function
QMimeData * mimeData (const QModelIndexList &indexes) const
Reimplemented Function
QStringList mimeTypes () const
Reimplemented Function
QUrlModel (QObject *parent=0)
QUrlModel lets you have indexes from a QFileSystemModel to a list.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
void setFileSystemModel (QFileSystemModel *model)
QFileSystemModel to get index's from, clears existing rows.
void setUrls (const QList< QUrl > &list)
QList< QUrl > urls () const
Return the complete list of urls in a QList.
Public Functions inherited from QStandardItemModel
void appendColumn (const QList< QStandardItem *> &items)
Appends a column containing items.
void appendRow (const QList< QStandardItem *> &items)
Appends a row containing items.
void appendRow (QStandardItem *item)
void clear ()
Removes all items (including header items) from the model and sets the number of rows and columns to zero.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Reimplemented Function
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
QList< QStandardItem * > findItems (const QString &text, Qt::MatchFlags flags=Qt::MatchExactly, int column=0) const
Returns a list of items that match the given text, using the given flags, in the given column.
Qt::ItemFlags flags (const QModelIndex &index) const
Reimplemented Function
bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Reimplemented Function
QStandardItem * horizontalHeaderItem (int column) const
Returns the horizontal header item for column if one has been set; otherwise returns 0.
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QModelIndex indexFromItem (const QStandardItem *item) const
Returns the QModelIndex associated with the given item.
void insertColumn (int column, const QList< QStandardItem *> &items)
Inserts a column at column containing items.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
void insertRow (int row, const QList< QStandardItem *> &items)
Inserts a row at row containing items.
void insertRow (int row, QStandardItem *item)
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
QStandardItem * invisibleRootItem () const
Returns the model's invisible root item.
QStandardItem * item (int row, int column=0) const
Returns the item for the given row and column if one has been set; otherwise returns 0.
QMap< int, QVariant > itemData (const QModelIndex &index) const
Reimplemented Function
QStandardItem * itemFromIndex (const QModelIndex &index) const
Returns a pointer to the QStandardItem associated with the given index.
const QStandardItem * itemPrototype () const
Returns the item prototype used by the model.
QMimeData * mimeData (const QModelIndexList &indexes) const
Reimplemented Function
QStringList mimeTypes () const
Reimplemented Function
QModelIndex parent (const QModelIndex &child) const
Reimplemented Function
QStandardItemModel (QObject *parent=0)
Constructs a new item model with the given parent.
QStandardItemModel (int rows, int columns, QObject *parent=0)
Constructs a new item model that initially has rows rows and columns columns, and that has the given parent.
bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
int rowCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
void setColumnCount (int columns)
Sets the number of columns in this model to columns.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
void setHorizontalHeaderItem (int column, QStandardItem *item)
Sets the horizontal header item for column to item.
void setHorizontalHeaderLabels (const QStringList &labels)
Sets the horizontal header labels using labels.
void setItem (int row, int column, QStandardItem *item)
Sets the item for the given row and column to item.
void setItem (int row, QStandardItem *item)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Reimplemented Function
void setItemPrototype (const QStandardItem *item)
Sets the item prototype for the model to the specified item.
void setRowCount (int rows)
Sets the number of rows in this model to rows.
void setSortRole (int role)
void setVerticalHeaderItem (int row, QStandardItem *item)
Sets the vertical header item for row to item.
void setVerticalHeaderLabels (const QStringList &labels)
Sets the vertical header labels using labels.
void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Reimplemented Function
int sortRole () const
Qt::DropActions supportedDropActions () const
QStandardItemModel supports both copy and move.
QList< QStandardItem * > takeColumn (int column)
Removes the given column without deleting the column items, and returns a list of pointers to the removed items.
QStandardItem * takeHorizontalHeaderItem (int column)
Removes the horizontal header item at column from the header without deleting it, and returns a pointer to the item.
QStandardItem * takeItem (int row, int column=0)
Removes the item at (row, column) without deleting it.
QList< QStandardItem * > takeRow (int row)
Removes the given row without deleting the row items, and returns a list of pointers to the removed items.
QStandardItem * takeVerticalHeaderItem (int row)
Removes the vertical header item at row from the header without deleting it, and returns a pointer to the item.
QStandardItem * verticalHeaderItem (int row) const
Returns the vertical header item for row row if one has been set; otherwise returns 0.
~QStandardItemModel ()
Destructs the model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
virtual void fetchMore (const QModelIndex &parent)
Fetches any available data for the items with the parent specified by the parent index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
bool showFullPath
Private Slots
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
void layoutChanged ()
Re-get all of our data, anything could have changed!
Private Functions
void addIndexToWatch (const QString &path, const QModelIndex &index)
void changed (const QString &path)
The following path changed data update our copy of that data.
void setUrl (const QModelIndex &index, const QUrl &url, const QModelIndex &dirIndex)
Properties
QFileSystemModel * fileSystemModel
QList< QUrl > invalidUrls
QList< QPair< QModelIndex, QString > > watching
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QStandardItemModel
void itemChanged (QStandardItem *item)
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Functions inherited from QStandardItemModel
QStandardItemModel (QStandardItemModelPrivate &dd, QObject *parent=0)
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 75 of file qsidebar_p.h.
Enumerations
Roles
enum QUrlModel::Roles
Enumerator
UrlRole
EnabledRole
Definition at line 80 of file qsidebar_p.h.
                {
         UrlRole = Qt::UserRole + 1,
         EnabledRole = Qt::UserRole + 2
     };
Constructors and Destructors
QUrlModel()
QUrlModel::QUrlModel (QObject * parent = 0)
QUrlModel lets you have indexes from a QFileSystemModel to a list.
When QFileSystemModel changes them QUrlModel will automatically update.
Example usage: File dialog sidebar and combo box
Definition at line 76 of file qsidebar.cpp.
                                     : QStandardItemModel(parent), showFullPath(false), fileSystemModel(0)
 {
 }
Functions
addIndexToWatch()
void QUrlModel::addIndexToWatch (const QString & path, const QModelIndex & index) private
addUrls()
void QUrlModel::addUrls (const QList< QUrl > & list, int row = -1, bool move = true)
Add urls list into the list at row.
If move then movie existing ones to row.
See also
dropMimeData()
Definition at line 241 of file qsidebar.cpp.
Referenced by dropMimeData(), and setUrls().
 {
     if (row == -1)
         row = rowCount();
     row = qMin(row, rowCount());
     for (int i = list.count() - 1; i >= 0; --i) {
         QUrl url = list.at(i);
         if (!url.isValid() || url.scheme() != QLatin1String("file"))
             continue;
         //this makes sure the url is clean
         const QString cleanUrl = QDir::cleanPath(url.toLocalFile());
         url = QUrl::fromLocalFile(cleanUrl);
         for (int j = 0; move && j < rowCount(); ++j) {
             QString local = index(j, 0).data(UrlRole).toUrl().toLocalFile();
 #if defined(Q_OS_WIN)
             if (index(j, 0).data(UrlRole).toUrl().toLocalFile().toLower() == cleanUrl.toLower()) {
 #else
             if (index(j, 0).data(UrlRole).toUrl().toLocalFile() == cleanUrl) {
 #endif
                 removeRow(j);
                 if (j <= row)
                     row--;
                 break;
             }
         }
         row = qMax(row, 0);
         QModelIndex idx = fileSystemModel->index(cleanUrl);
         if (!fileSystemModel->isDir(idx))
             continue;
         insertRows(row, 1);
         setUrl(index(row, 0), url, idx);
         watching.append(qMakePair(idx, cleanUrl));
     }
 }
canDrop()
bool QUrlModel::canDrop (QDragEnterEvent * event)
Decide based upon the data if it should be accepted or not.
We only accept dirs and not files
Definition at line 128 of file qsidebar.cpp.
Referenced by QSidebar::dragEnterEvent().
 {
     if (!event->mimeData()->formats().contains(mimeTypes().first()))
         return false;
     const QList<QUrl> list = event->mimeData()->urls();
     for (int i = 0; i < list.count(); ++i) {
         QModelIndex idx = fileSystemModel->index(list.at(0).toLocalFile());
         if (!fileSystemModel->isDir(idx))
             return false;
     }
     return true;
 }
changed()
void QUrlModel::changed (const QString & path) private
The following path changed data update our copy of that data.
See also
layoutChanged() dataChanged()
Definition at line 360 of file qsidebar.cpp.
Referenced by dataChanged(), and layoutChanged().
 {
     for (int i = 0; i < rowCount(); ++i) {
         QModelIndex idx = index(i, 0);
         if (idx.data(UrlRole).toUrl().toLocalFile() == path) {
             setData(idx, idx.data(UrlRole).toUrl());
         }
     }
 }
dataChanged
void QUrlModel::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) private slot
Definition at line 319 of file qsidebar.cpp.
Referenced by setFileSystemModel().
 {
     QModelIndex parent = topLeft.parent();
     for (int i = 0; i < watching.count(); ++i) {
         QModelIndex index = watching.at(i).first;
         if (index.model() && topLeft.model()) {
             Q_ASSERT(index.model() == topLeft.model());
         }
         if (   index.row() >= topLeft.row()
             && index.row() <= bottomRight.row()
             && index.column() >= topLeft.column()
             && index.column() <= bottomRight.column()
             && index.parent() == parent) {
                 changed(watching.at(i).second);
         }
     }
 }
dropMimeData()
bool QUrlModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 145 of file qsidebar.cpp.
 {
     if (!data->formats().contains(mimeTypes().first()))
         return false;
     Q_UNUSED(action);
     Q_UNUSED(column);
     Q_UNUSED(parent);
     addUrls(data->urls(), row);
     return true;
 }
flags()
Qt::ItemFlags QUrlModel::flags (const QModelIndex & index) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 91 of file qsidebar.cpp.
 {
     Qt::ItemFlags flags = QStandardItemModel::flags(index);
     if (index.isValid()) {
         flags &= ~Qt::ItemIsEditable;
         // ### some future version could support "moving" urls onto a folder
         flags &= ~Qt::ItemIsDropEnabled;
     }
     if (index.data(Qt::DecorationRole).isNull())
         flags &= ~Qt::ItemIsEnabled;
     return flags;
 }
layoutChanged
void QUrlModel::layoutChanged () private slot
Re-get all of our data, anything could have changed!
Definition at line 340 of file qsidebar.cpp.
Referenced by setFileSystemModel().
 {
     QStringList paths;
     for (int i = 0; i < watching.count(); ++i)
         paths.append(watching.at(i).second);
     watching.clear();
     for (int i = 0; i < paths.count(); ++i) {
         QString path = paths.at(i);
         QModelIndex newIndex = fileSystemModel->index(path);
         watching.append(QPair<QModelIndex, QString>(newIndex, path));
         if (newIndex.isValid())
             changed(path);
      }
 }
mimeData()
QMimeData * QUrlModel::mimeData (const QModelIndexList & indexes) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 109 of file qsidebar.cpp.
 {
     QList<QUrl> list;
     for (int i = 0; i < indexes.count(); ++i) {
         if (indexes.at(i).column() == 0)
            list.append(indexes.at(i).data(UrlRole).toUrl());
     }
     QMimeData *data = new QMimeData();
     data->setUrls(list);
     return data;
 }
mimeTypes()
QStringList QUrlModel::mimeTypes () const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 83 of file qsidebar.cpp.
Referenced by canDrop(), and dropMimeData().
 {
     return QStringList(QLatin1String("text/uri-list"));
 }
setData()
bool QUrlModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Reimplemented Function
If the role is the UrlRole then handle otherwise just pass to QStandardItemModel
Reimplemented from QAbstractItemModel.
Definition at line 164 of file qsidebar.cpp.
Referenced by changed(), and setUrl().
 {
     if (value.type() == QVariant::Url) {
         QUrl url = value.toUrl();
         QModelIndex dirIndex = fileSystemModel->index(url.toLocalFile());
         //On windows the popup display the "C:\", convert to nativeSeparators
         if (showFullPath)
             QStandardItemModel::setData(index, QDir::toNativeSeparators(fileSystemModel->data(dirIndex, QFileSystemModel::FilePathRole).toString()));
         else {
             QStandardItemModel::setData(index, QDir::toNativeSeparators(fileSystemModel->data(dirIndex, QFileSystemModel::FilePathRole).toString()), Qt::ToolTipRole);
             QStandardItemModel::setData(index, fileSystemModel->data(dirIndex).toString());
         }
         QStandardItemModel::setData(index, fileSystemModel->data(dirIndex, Qt::DecorationRole),
                                                Qt::DecorationRole);
         QStandardItemModel::setData(index, url, UrlRole);
         return true;
     }
     return QStandardItemModel::setData(index, value, role);
 }
setFileSystemModel()
void QUrlModel::setFileSystemModel (QFileSystemModel * model)
QFileSystemModel to get index's from, clears existing rows.
Definition at line 291 of file qsidebar.cpp.
Referenced by QSidebar::init().
 {
     if (model == fileSystemModel)
         return;
     if (fileSystemModel != 0) {
         disconnect(model, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
             this, SLOT(dataChanged(QModelIndex,QModelIndex)));
         disconnect(model, SIGNAL(layoutChanged()),
             this, SLOT(layoutChanged()));
         disconnect(model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
             this, SLOT(layoutChanged()));
     }
     fileSystemModel = model;
     if (fileSystemModel != 0) {
         connect(model, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
             this, SLOT(dataChanged(QModelIndex,QModelIndex)));
         connect(model, SIGNAL(layoutChanged()),
             this, SLOT(layoutChanged()));
         connect(model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
             this, SLOT(layoutChanged()));
     }
     clear();
     insertColumns(0, 1);
 }
setUrl()
void QUrlModel::setUrl (const QModelIndex & index, const QUrl & url, const QModelIndex & dirIndex) private
Definition at line 184 of file qsidebar.cpp.
Referenced by addUrls().
 {
     setData(index, url, UrlRole);
     if (url.path().isEmpty()) {
         setData(index, fileSystemModel->myComputer());
         setData(index, fileSystemModel->myComputer(Qt::DecorationRole), Qt::DecorationRole);
     } else {
         QString newName;
         if (showFullPath) {
             //On windows the popup display the "C:\", convert to nativeSeparators
             newName = QDir::toNativeSeparators(dirIndex.data(QFileSystemModel::FilePathRole).toString());
         } else {
             newName = dirIndex.data().toString();
         }
         QIcon newIcon = qvariant_cast<QIcon>(dirIndex.data(Qt::DecorationRole));
         if (!dirIndex.isValid()) {
             newIcon = fileSystemModel->iconProvider()->icon(QFileIconProvider::Folder);
             newName = QFileInfo(url.toLocalFile()).fileName();
             if (!invalidUrls.contains(url))
                 invalidUrls.append(url);
             //The bookmark is invalid then we set to false the EnabledRole
             setData(index, false, EnabledRole);
         } else {
             //The bookmark is valid then we set to true the EnabledRole
             setData(index, true, EnabledRole);
         }
         // Make sure that we have at least 32x32 images
         const QSize size = newIcon.actualSize(QSize(32,32));
         if (size.width() < 32) {
             QPixmap smallPixmap = newIcon.pixmap(QSize(32, 32));
             newIcon.addPixmap(smallPixmap.scaledToWidth(32, Qt::SmoothTransformation));
         }
         if (index.data().toString() != newName)
             setData(index, newName);
         QIcon oldIcon = qvariant_cast<QIcon>(index.data(Qt::DecorationRole));
         if (oldIcon.cacheKey() != newIcon.cacheKey())
             setData(index, newIcon, Qt::DecorationRole);
     }
 }
setUrls()
void QUrlModel::setUrls (const QList< QUrl > & list)
Definition at line 227 of file qsidebar.cpp.
Referenced by QSidebar::init().
 {
     removeRows(0, rowCount());
     invalidUrls.clear();
     watching.clear();
     addUrls(list, 0);
 }
urls()
QList< QUrl > QUrlModel::urls () const
Return the complete list of urls in a QList.
Definition at line 280 of file qsidebar.cpp.
 {
     QList<QUrl> list;
     for (int i = 0; i < rowCount(); ++i)
         list.append(data(index(i, 0), UrlRole).toUrl());
     return list;
 }
Properties
fileSystemModel
QFileSystemModel* QUrlModel::fileSystemModel private
Definition at line 110 of file qsidebar_p.h.
Referenced by addUrls(), canDrop(), layoutChanged(), setData(), setFileSystemModel(), and setUrl().
invalidUrls
QList<QUrl> QUrlModel::invalidUrls private
Definition at line 112 of file qsidebar_p.h.
Referenced by setUrl(), and setUrls().
showFullPath
bool QUrlModel::showFullPath
Definition at line 100 of file qsidebar_p.h.
Referenced by setData(), and setUrl().
watching
QList<QPair<QModelIndex, QString> > QUrlModel::watching private
Definition at line 111 of file qsidebar_p.h.
Referenced by addUrls(), dataChanged(), layoutChanged(), and setUrls().
The documentation for this class was generated from the following files:
/src/gui/dialogs/qsidebar_p.h
/src/gui/dialogs/qsidebar.cpp