Qt 4.8: QPatternist::XsdFacet Class Reference
QPatternist::XsdFacet Class Reference
XML Schema Processing
Represents a XSD facet object.
#include <qxsdfacet_p.h>
Public Types
typedef QHash< XsdFacet::Type, XsdFacet::Ptr > Hash
typedef QHashIterator< XsdFacet::Type, XsdFacet::Ptr > HashIterator
typedef QExplicitlySharedDataPointer< XsdFacet > Ptr
enum Type {
None = 0, Length = 1 << 0, MinimumLength = 1 << 1, MaximumLength = 1 << 2,
Pattern = 1 << 3, WhiteSpace = 1 << 4, MaximumInclusive = 1 << 5, MaximumExclusive = 1 << 6,
MinimumInclusive = 1 << 7, MinimumExclusive = 1 << 8, TotalDigits = 1 << 9, FractionDigits = 1 << 10,
Enumeration = 1 << 11, Assertion = 1 << 12
}
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
XsdAssertion::List assertions () const
bool fixed () const
AtomicValue::List multiValue () const
void setAssertions (const XsdAssertion::List &assertions)
void setFixed (bool fixed)
void setMultiValue (const AtomicValue::List &value)
void setType (Type type)
void setValue (const AtomicValue::Ptr &value)
Type type () const
AtomicValue::Ptr value () const
XsdFacet ()
Public Functions inherited from QPatternist::NamedSchemaComponent
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Static Public Functions
static QString typeName (Type type)
Properties
XsdAssertion::List m_assertions
bool m_fixed
AtomicValue::List m_multiValue
Type m_type
AtomicValue::Ptr m_value
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Represents a XSD facet object.
This class represents one of the following XML schema objects:
length Definition
minLength Definition
maxLength Definition
pattern Definition
whiteSpace Definition
maxInclusive Definition
maxExclusive Definition
minInclusive Definition
minExclusive Definition
totalDigits Definition
fractionDigits Definition
enumeration Definition
assertion Definition
See also
XML Schema API reference
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 93 of file qxsdfacet_p.h.
Typedefs
Hash
typedef QHash<XsdFacet::Type, XsdFacet::Ptr> QPatternist::XsdFacet::Hash
Definition at line 118 of file qxsdfacet_p.h.
HashIterator
typedef QHashIterator<XsdFacet::Type, XsdFacet::Ptr> QPatternist::XsdFacet::HashIterator
Definition at line 119 of file qxsdfacet_p.h.
Ptr
typedef QExplicitlySharedDataPointer<XsdFacet> QPatternist::XsdFacet::Ptr
Definition at line 96 of file qxsdfacet_p.h.
Enumerations
Type
enum QPatternist::XsdFacet::Type
Describes the type of the facet.
Enumerator
None
An invalid facet.
Length
Match the exact length (Length Definition)
MinimumLength
Match the minimum length (Minimum Length Definition)
MaximumLength
Match the maximum length (Maximum Length Definition)
Pattern
Match a regular expression (Pattern Definition)
WhiteSpace
Match a whitespace rule (White Space Definition)
MaximumInclusive
Match a maximum inclusive (Maximum Inclusive Definition)
MaximumExclusive
Match a maximum exclusive (Maximum Exclusive Definition)
MinimumInclusive
Match a minimum inclusive (Minimum Inclusive Definition)
MinimumExclusive
Match a minimum exclusive (Minimum Exclusive Definition)
TotalDigits
Match some integer digits (Total Digits Definition)
FractionDigits
Match some double digits (Fraction Digits Definition)
Enumeration
Match an enumeration (Enumeration Definition)
Assertion
Match an assertion (Assertion Definition)
Definition at line 101 of file qxsdfacet_p.h.
             {
                 None             = 0,
                 Length           = 1 << 0,
                 MinimumLength    = 1 << 1,
                 MaximumLength    = 1 << 2,
                 Pattern          = 1 << 3,
                 WhiteSpace       = 1 << 4,
                 MaximumInclusive = 1 << 5,
                 MaximumExclusive = 1 << 6,
                 MinimumInclusive = 1 << 7,
                 MinimumExclusive = 1 << 8,
                 TotalDigits      = 1 << 9,
                 FractionDigits   = 1 << 10,
                 Enumeration      = 1 << 11,
                 Assertion        = 1 << 12,
             };
Constructors and Destructors
XsdFacet()
XsdFacet::XsdFacet ()
Creates a new facet object of type None.
Definition at line 48 of file qxsdfacet.cpp.
     : m_type(None)
 {
 }
Functions
assertions()
XsdAssertion::List XsdFacet::assertions () const
Returns the assertions of the facet or an empty pointer if facet type is not of type Assertion.
Definition at line 88 of file qxsdfacet.cpp.
Referenced by setAssertions().
 {
     return m_assertions;
 }
fixed()
bool XsdFacet::fixed () const
Returns whether the facet is fixed.
Definition at line 98 of file qxsdfacet.cpp.
Referenced by setFixed().
 {
     return m_fixed;
 }
multiValue()
AtomicValue::List XsdFacet::multiValue () const
Returns the value of the facet or an empty pointer if facet type is not of type Pattern or Enumeration.
Definition at line 78 of file qxsdfacet.cpp.
 {
     return m_multiValue;
 }
setAssertions()
void XsdFacet::setAssertions (const XsdAssertion::List & assertions)
Sets the assertions of the facet.
Note
This method should be used if the type of the facet is Assertion.
Definition at line 83 of file qxsdfacet.cpp.
 {
     m_assertions = assertions;
 }
setFixed()
void XsdFacet::setFixed (bool fixed)
Sets whether the facet is fixed.
All facets except pattern, enumeration and assertion can be fixed.
Definition at line 93 of file qxsdfacet.cpp.
 {
     m_fixed = fixed;
 }
setMultiValue()
void XsdFacet::setMultiValue (const AtomicValue::List & value)
Sets the value of the facet.
Note
This method should be used for if the type of the facet is Pattern or Enumeration.
Definition at line 73 of file qxsdfacet.cpp.
 {
     m_multiValue = value;
 }
setType()
void XsdFacet::setType (Type type)
Sets the type of the facet.
See also
Type
Definition at line 53 of file qxsdfacet.cpp.
 {
     m_type = type;
 }
setValue()
void XsdFacet::setValue (const AtomicValue::Ptr & value)
Sets the value of the facet.
Depending on the type of the facet the value can be a string, interger, double etc.
Note
This method should be used for all types of facets except Pattern, Enumeration and Assertion.
Definition at line 63 of file qxsdfacet.cpp.
 {
     m_value = value;
 }
type()
XsdFacet::Type XsdFacet::type () const
Returns the type of the facet.
Definition at line 58 of file qxsdfacet.cpp.
Referenced by setType().
 {
     return m_type;
 }
typeName()
QString XsdFacet::typeName (Type type) static
Returns the textual description of the facet type.
Definition at line 103 of file qxsdfacet.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkConstrainingFacets(), and QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints().
 {
     switch (type) {
         case Length: return QLatin1String("length"); break;
         case MinimumLength: return QLatin1String("minLength"); break;
         case MaximumLength: return QLatin1String("maxLength"); break;
         case Pattern: return QLatin1String("pattern"); break;
         case WhiteSpace: return QLatin1String("whiteSpace"); break;
         case MaximumInclusive: return QLatin1String("maxInclusive"); break;
         case MaximumExclusive: return QLatin1String("maxExclusive"); break;
         case MinimumInclusive: return QLatin1String("minInclusive"); break;
         case MinimumExclusive: return QLatin1String("minExclusive"); break;
         case TotalDigits: return QLatin1String("totalDigits"); break;
         case FractionDigits: return QLatin1String("fractionDigits"); break;
         case Enumeration: return QLatin1String("enumeration"); break;
         case Assertion: return QLatin1String("assertion"); break;
         case None: // fall through
         default: return QLatin1String("none"); break;
     }
 }
value()
AtomicValue::Ptr XsdFacet::value () const
Returns the value of the facet or an empty pointer if facet type is Pattern, Enumeration or Assertion.
Definition at line 68 of file qxsdfacet.cpp.
Referenced by setMultiValue(), and setValue().
 {
     return m_value;
 }
Properties
m_assertions
XsdAssertion::List QPatternist::XsdFacet::m_assertions private
Definition at line 204 of file qxsdfacet_p.h.
Referenced by assertions(), and setAssertions().
m_fixed
bool QPatternist::XsdFacet::m_fixed private
Definition at line 205 of file qxsdfacet_p.h.
Referenced by fixed(), and setFixed().
m_multiValue
AtomicValue::List QPatternist::XsdFacet::m_multiValue private
Definition at line 203 of file qxsdfacet_p.h.
Referenced by multiValue(), and setMultiValue().
m_type
Type QPatternist::XsdFacet::m_type private
Definition at line 201 of file qxsdfacet_p.h.
Referenced by setType(), and type().
m_value
AtomicValue::Ptr QPatternist::XsdFacet::m_value private
Definition at line 202 of file qxsdfacet_p.h.
Referenced by setValue(), and value().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdfacet_p.h
/src/xmlpatterns/schema/qxsdfacet.cpp