Qt 4.8: QMetaType Class Reference
QMetaType Class Reference
The QMetaType class manages named types in the meta-object system.
#include <qmetatype.h>
Public Types
typedef void *(* Constructor) (const void *)
typedef void(* Destructor) (void *)
typedef void(* LoadOperator) (QDataStream &, void *)
typedef void(* SaveOperator) (QDataStream &, const void *)
enum Type {
Void = 0, Bool = 1, Int = 2, UInt = 3,
LongLong = 4, ULongLong = 5, Double = 6, QChar = 7,
QVariantMap = 8, QVariantList = 9, QString = 10, QStringList = 11,
QByteArray = 12, QBitArray = 13, QDate = 14, QTime = 15,
QDateTime = 16, QUrl = 17, QLocale = 18, QRect = 19,
QRectF = 20, QSize = 21, QSizeF = 22, QLine = 23,
QLineF = 24, QPoint = 25, QPointF = 26, QRegExp = 27,
QVariantHash = 28, QEasingCurve = 29, LastCoreType = QEasingCurve, FirstGuiType = 63,
QFont = 64, QPixmap = 65, QBrush = 66, QColor = 67,
QPalette = 68, QIcon = 69, QImage = 70, QPolygon = 71,
QRegion = 72, QBitmap = 73, QCursor = 74, QSizePolicy = 75,
QKeySequence = 76, QPen = 77, QTextLength = 78, QTextFormat = 79,
QMatrix = 80, QTransform = 81, QMatrix4x4 = 82, QVector2D = 83,
QVector3D = 84, QVector4D = 85, QQuaternion = 86, LastGuiType = QQuaternion,
FirstCoreExtType = 128, VoidStar = 128, Long = 129, Short = 130,
Char = 131, ULong = 132, UShort = 133, UChar = 134,
Float = 135, QObjectStar = 136, QWidgetStar = 137, QVariant = 138,
LastCoreExtType = QVariant, QReal = Double, User = 256
}
These are the built-in types supported by QMetaType:
Static Public Functions
static void * construct (int type, const void *copy=0)
Returns a copy of copy, assuming it is of type type.
static void destroy (int type, void *data)
Destroys the data, assuming it is of the type given.
static bool isRegistered (int type)
Returns true if the datatype with ID type is registered; otherwise returns false.
static bool load (QDataStream &stream, int type, void *data)
Reads the object of the specified type from the given stream into data.
static void registerStreamOperators (const char *typeName, SaveOperator saveOp, LoadOperator loadOp)
static void registerStreamOperators (int type, SaveOperator saveOp, LoadOperator loadOp)
static int registerType (const char *typeName, Destructor destructor, Constructor constructor)
Registers a user type for marshalling, with typeName, a destructor, and a constructor.
static int registerTypedef (const char *typeName, int aliasId)
static bool save (QDataStream &stream, int type, const void *data)
Writes the object pointed to by data with the ID type to the given stream.
static int type (const char *typeName)
Returns a handle to the type called typeName, or 0 if there is no such type.
static const char * typeName (int type)
Returns the type name associated with the given type, or 0 if no matching type was found.
static void unregisterType (const char *typeName)
Unregisters a user type, with typeName.
Related Functions
(Note that these are not member functions.)
int qMetaTypeId ()
Returns the meta type id of type T at compile time.
int qRegisterMetaType (const char *typeName)
int qRegisterMetaType ()
Call this function to register the type T.
int qRegisterMetaTypeStreamOperators (const char *typeName)
Detailed Description
The QMetaType class manages named types in the meta-object system.
Note
This class or function is threadsafe.
The class is used as a helper to marshall types in QVariant and in queued signals and slots connections. It associates a type name to a type so that it can be created and destructed dynamically at run-time. Declare new types with Q_DECLARE_METATYPE() to make them available to QVariant and other template-based functions. Call qRegisterMetaType() to make type available to non-template based functions, such as the queued signal and slot connections.
Any class or struct that has a public default constructor, a public copy constructor, and a public destructor can be registered.
The following code allocates and destructs an instance of MyClass:
int id = QMetaType::type("MyClass");
if (id != 0) {
    void *myClassPtr = QMetaType::construct(id);
    ...
    QMetaType::destroy(id, myClassPtr);
    myClassPtr = 0;
}
If we want the stream operators operator<<() and operator>>() to work on QVariant objects that store custom types, the custom type must provide operator<<() and operator>>() operators.
See also
Q_DECLARE_METATYPE(), QVariant::setValue(), QVariant::value(), QVariant::fromValue()
Definition at line 62 of file qmetatype.h.
Typedefs
Constructor
QMetaType::Constructor
Warning
This function is not part of the public interface.
Definition at line 105 of file qmetatype.h.
Destructor
QMetaType::Destructor
Warning
This function is not part of the public interface.
Definition at line 104 of file qmetatype.h.
LoadOperator
QMetaType::LoadOperator
Warning
This function is not part of the public interface.
Definition at line 109 of file qmetatype.h.
SaveOperator
QMetaType::SaveOperator
Warning
This function is not part of the public interface.
Definition at line 108 of file qmetatype.h.
Enumerations
Type
enum QMetaType::Type
These are the built-in types supported by QMetaType:
Void void
Bool bool
Int int
UInt unsigned int
Double double
QChar QChar
QString QString
QByteArray QByteArray
VoidStar void *
Long long
LongLong LongLong
Short short
Char char
ULong unsigned long
ULongLong ULongLong
UShort unsigned short
UChar unsigned char
Float float
QObjectStar QObject *
QWidgetStar QWidget *
QVariant QVariant
QColorGroup QColorGroup
QCursor QCursor
QDate QDate
QSize QSize
QTime QTime
QVariantList QVariantList
QPolygon QPolygon
QColor QColor
QSizeF QSizeF
QRectF QRectF
QLine QLine
QTextLength QTextLength
QStringList QStringList
QVariantMap QVariantMap
QVariantHash QVariantHash
QIcon QIcon
QPen QPen
QLineF QLineF
QTextFormat QTextFormat
QRect QRect
QPoint QPoint
QUrl QUrl
QRegExp QRegExp
QDateTime QDateTime
QPointF QPointF
QPalette QPalette
QFont QFont
QBrush QBrush
QRegion QRegion
QBitArray QBitArray
QImage QImage
QKeySequence QKeySequence
QSizePolicy QSizePolicy
QPixmap QPixmap
QLocale QLocale
QBitmap QBitmap
QMatrix QMatrix
QTransform QTransform
QMatrix4x4 QMatrix4x4
QVector2D QVector2D
QVector3D QVector3D
QVector4D QVector4D
QQuaternion QQuaternion
QEasingCurve QEasingCurve
User Base value for user types
FirstCoreExtType
FirstGuiType
LastCoreExtType
LastCoreType
LastGuiType
QReal
Additional types can be registered using Q_DECLARE_METATYPE().
See also
type(), typeName()
Enumerator
Void
Bool
Int
UInt
LongLong
ULongLong
Double
QChar
QVariantMap
QVariantList
QString
QStringList
QByteArray
QBitArray
QDate
QTime
QDateTime
QUrl
QLocale
QRect
QRectF
QSize
QSizeF
QLine
QLineF
QPoint
QPointF
QRegExp
QVariantHash
QEasingCurve
LastCoreType
FirstGuiType
QFont
QPixmap
QBrush
QColor
QPalette
QIcon
QImage
QPolygon
QRegion
QBitmap
QCursor
QSizePolicy
QKeySequence
QPen
QTextLength
QTextFormat
QMatrix
QTransform
QMatrix4x4
QVector2D
QVector3D
QVector4D
QQuaternion
LastGuiType
FirstCoreExtType
VoidStar
Long
Short
Char
ULong
UShort
UChar
Float
QObjectStar
QWidgetStar
QVariant
LastCoreExtType
QReal
User
Definition at line 64 of file qmetatype.h.
               {
         // these are merged with QVariant
         Void = 0, Bool = 1, Int = 2, UInt = 3, LongLong = 4, ULongLong = 5,
         Double = 6, QChar = 7, QVariantMap = 8, QVariantList = 9,
         QString = 10, QStringList = 11, QByteArray = 12,
         QBitArray = 13, QDate = 14, QTime = 15, QDateTime = 16, QUrl = 17,
         QLocale = 18, QRect = 19, QRectF = 20, QSize = 21, QSizeF = 22,
         QLine = 23, QLineF = 24, QPoint = 25, QPointF = 26, QRegExp = 27,
         QVariantHash = 28, QEasingCurve = 29, LastCoreType = QEasingCurve,
         FirstGuiType = 63 /* QColorGroup */,
 #ifdef QT3_SUPPORT
         QColorGroup = 63,
 #endif
         QFont = 64, QPixmap = 65, QBrush = 66, QColor = 67, QPalette = 68,
         QIcon = 69, QImage = 70, QPolygon = 71, QRegion = 72, QBitmap = 73,
         QCursor = 74, QSizePolicy = 75, QKeySequence = 76, QPen = 77,
         QTextLength = 78, QTextFormat = 79, QMatrix = 80, QTransform = 81,
         QMatrix4x4 = 82, QVector2D = 83, QVector3D = 84, QVector4D = 85,
         QQuaternion = 86,
         LastGuiType = QQuaternion,
         FirstCoreExtType = 128 /* VoidStar */,
         VoidStar = 128, Long = 129, Short = 130, Char = 131, ULong = 132,
         UShort = 133, UChar = 134, Float = 135, QObjectStar = 136, QWidgetStar = 137,
         QVariant = 138,
         LastCoreExtType = QVariant,
 // This logic must match the one in qglobal.h
 #if defined(QT_COORD_TYPE)
         QReal = 0,
 #elif defined(QT_NO_FPU) || defined(QT_ARCH_ARM) || defined(QT_ARCH_WINDOWSCE) || defined(QT_ARCH_SYMBIAN)
         QReal = Float,
 #else
         QReal = Double,
 #endif
         User = 256
     };
Functions
construct()
void * QMetaType::construct (int type, const void * copy = 0) static
Returns a copy of copy, assuming it is of type type.
If copy is zero, creates a default type.
See also
destroy(), isRegistered(), Type
Definition at line 1042 of file qmetatype.cpp.
Referenced by QTestData::append(), construct(), QMetaMethod::invoke(), qax_createObjectWrapper(), and queued_activate().
 {
     if (copy) {
         switch(type) {
         case QMetaType::VoidStar:
         case QMetaType::QObjectStar:
         case QMetaType::QWidgetStar:
             return new void *(*static_cast<void* const *>(copy));
         case QMetaType::Long:
             return new long(*static_cast<const long*>(copy));
         case QMetaType::Int:
             return new int(*static_cast<const int*>(copy));
         case QMetaType::Short:
             return new short(*static_cast<const short*>(copy));
         case QMetaType::Char:
             return new char(*static_cast<const char*>(copy));
         case QMetaType::ULong:
             return new ulong(*static_cast<const ulong*>(copy));
         case QMetaType::UInt:
             return new uint(*static_cast<const uint*>(copy));
         case QMetaType::LongLong:
             return new qlonglong(*static_cast<const qlonglong*>(copy));
         case QMetaType::ULongLong:
             return new qulonglong(*static_cast<const qulonglong*>(copy));
         case QMetaType::UShort:
             return new ushort(*static_cast<const ushort*>(copy));
         case QMetaType::UChar:
             return new uchar(*static_cast<const uchar*>(copy));
         case QMetaType::Bool:
             return new bool(*static_cast<const bool*>(copy));
         case QMetaType::Float:
             return new float(*static_cast<const float*>(copy));
         case QMetaType::Double:
             return new double(*static_cast<const double*>(copy));
         case QMetaType::QChar:
             return new NS(QChar)(*static_cast<const NS(QChar)*>(copy));
 #ifndef QT_BOOTSTRAPPED
         case QMetaType::QVariantMap:
             return new NS(QVariantMap)(*static_cast<const NS(QVariantMap)*>(copy));
         case QMetaType::QVariantHash:
             return new NS(QVariantHash)(*static_cast<const NS(QVariantHash)*>(copy));
         case QMetaType::QVariantList:
             return new NS(QVariantList)(*static_cast<const NS(QVariantList)*>(copy));
         case QMetaType::QVariant:
             return new NS(QVariant)(*static_cast<const NS(QVariant)*>(copy));
 #endif
         case QMetaType::QByteArray:
             return new NS(QByteArray)(*static_cast<const NS(QByteArray)*>(copy));
         case QMetaType::QString:
             return new NS(QString)(*static_cast<const NS(QString)*>(copy));
         case QMetaType::QStringList:
             return new NS(QStringList)(*static_cast<const NS(QStringList)*>(copy));
 #ifndef QT_BOOTSTRAPPED
         case QMetaType::QBitArray:
             return new NS(QBitArray)(*static_cast<const NS(QBitArray)*>(copy));
 #endif
         case QMetaType::QDate:
             return new NS(QDate)(*static_cast<const NS(QDate)*>(copy));
         case QMetaType::QTime:
             return new NS(QTime)(*static_cast<const NS(QTime)*>(copy));
         case QMetaType::QDateTime:
             return new NS(QDateTime)(*static_cast<const NS(QDateTime)*>(copy));
 #ifndef QT_BOOTSTRAPPED
         case QMetaType::QUrl:
             return new NS(QUrl)(*static_cast<const NS(QUrl)*>(copy));
 #endif
         case QMetaType::QLocale:
             return new NS(QLocale)(*static_cast<const NS(QLocale)*>(copy));
 #ifndef QT_NO_GEOM_VARIANT
         case QMetaType::QRect:
             return new NS(QRect)(*static_cast<const NS(QRect)*>(copy));
         case QMetaType::QRectF:
             return new NS(QRectF)(*static_cast<const NS(QRectF)*>(copy));
         case QMetaType::QSize:
             return new NS(QSize)(*static_cast<const NS(QSize)*>(copy));
         case QMetaType::QSizeF:
             return new NS(QSizeF)(*static_cast<const NS(QSizeF)*>(copy));
         case QMetaType::QLine:
             return new NS(QLine)(*static_cast<const NS(QLine)*>(copy));
         case QMetaType::QLineF:
             return new NS(QLineF)(*static_cast<const NS(QLineF)*>(copy));
         case QMetaType::QPoint:
             return new NS(QPoint)(*static_cast<const NS(QPoint)*>(copy));
         case QMetaType::QPointF:
             return new NS(QPointF)(*static_cast<const NS(QPointF)*>(copy));
 #endif
 #ifndef QT_NO_REGEXP
         case QMetaType::QRegExp:
             return new NS(QRegExp)(*static_cast<const NS(QRegExp)*>(copy));
 #endif
 #ifndef QT_BOOTSTRAPPED
         case QMetaType::QEasingCurve:
             return new NS(QEasingCurve)(*static_cast<const NS(QEasingCurve)*>(copy));
 #endif
         case QMetaType::Void:
             return 0;
         default:
             ;
         }
     } else {
         switch(type) {
         case QMetaType::VoidStar:
         case QMetaType::QObjectStar:
         case QMetaType::QWidgetStar:
             return new void *;
         case QMetaType::Long:
             return new long;
         case QMetaType::Int:
             return new int;
         case QMetaType::Short:
             return new short;
         case QMetaType::Char:
             return new char;
         case QMetaType::ULong:
             return new ulong;
         case QMetaType::UInt:
             return new uint;
         case QMetaType::LongLong:
             return new qlonglong;
         case QMetaType::ULongLong:
             return new qulonglong;
         case QMetaType::UShort:
             return new ushort;
         case QMetaType::UChar:
             return new uchar;
         case QMetaType::Bool:
             return new bool;
         case QMetaType::Float:
             return new float;
         case QMetaType::Double:
             return new double;
         case QMetaType::QChar:
             return new NS(QChar);
 #ifndef QT_BOOTSTRAPPED
         case QMetaType::QVariantMap:
             return new NS(QVariantMap);
         case QMetaType::QVariantHash:
             return new NS(QVariantHash);
         case QMetaType::QVariantList:
             return new NS(QVariantList);
         case QMetaType::QVariant:
             return new NS(QVariant);
 #endif
         case QMetaType::QByteArray:
             return new NS(QByteArray);
         case QMetaType::QString:
             return new NS(QString);
         case QMetaType::QStringList:
             return new NS(QStringList);
 #ifndef QT_BOOTSTRAPPED
         case QMetaType::QBitArray:
             return new NS(QBitArray);
 #endif
         case QMetaType::QDate:
             return new NS(QDate);
         case QMetaType::QTime:
             return new NS(QTime);
         case QMetaType::QDateTime:
             return new NS(QDateTime);
 #ifndef QT_BOOTSTRAPPED
         case QMetaType::QUrl:
             return new NS(QUrl);
 #endif
         case QMetaType::QLocale:
             return new NS(QLocale);
 #ifndef QT_NO_GEOM_VARIANT
         case QMetaType::QRect:
             return new NS(QRect);
         case QMetaType::QRectF:
             return new NS(QRectF);
         case QMetaType::QSize:
             return new NS(QSize);
         case QMetaType::QSizeF:
             return new NS(QSizeF);
         case QMetaType::QLine:
             return new NS(QLine);
         case QMetaType::QLineF:
             return new NS(QLineF);
         case QMetaType::QPoint:
             return new NS(QPoint);
         case QMetaType::QPointF:
             return new NS(QPointF);
 #endif
 #ifndef QT_NO_REGEXP
         case QMetaType::QRegExp:
             return new NS(QRegExp);
 #endif
 #ifndef QT_BOOTSTRAPPED
         case QMetaType::QEasingCurve:
             return new NS(QEasingCurve);
 #endif
         case QMetaType::Void:
             return 0;
         default:
             ;
         }
     }
     Constructor constr = 0;
     if (type >= FirstGuiType && type <= LastGuiType) {
         if (!qMetaTypeGuiHelper)
             return 0;
         constr = qMetaTypeGuiHelper[type - FirstGuiType].constr;
     } else {
         const QVector<QCustomTypeInfo> * const ct = customTypes();
         QReadLocker locker(customTypesLock());
         if (type < User || !ct || ct->count() <= type - User)
             return 0;
         if (ct->at(type - User).typeName.isEmpty())
             return 0;
         constr = ct->at(type - User).constr;
     }
     return constr(copy);
 }
destroy()
void QMetaType::destroy (int type, void * data) static
Destroys the data, assuming it is of the type given.
See also
construct(), isRegistered(), Type
Definition at line 1263 of file qmetatype.cpp.
Referenced by clear(), QMetaMethod::invoke(), QMetaCallEvent::~QMetaCallEvent(), and QTestData::~QTestData().
 {
     if (!data)
         return;
     switch(type) {
     case QMetaType::VoidStar:
     case QMetaType::QObjectStar:
     case QMetaType::QWidgetStar:
         delete static_cast<void**>(data);
         break;
     case QMetaType::Long:
         delete static_cast<long*>(data);
         break;
     case QMetaType::Int:
         delete static_cast<int*>(data);
         break;
     case QMetaType::Short:
         delete static_cast<short*>(data);
         break;
     case QMetaType::Char:
         delete static_cast<char*>(data);
         break;
     case QMetaType::ULong:
         delete static_cast<ulong*>(data);
         break;
     case QMetaType::LongLong:
         delete static_cast<qlonglong*>(data);
         break;
     case QMetaType::ULongLong:
         delete static_cast<qulonglong*>(data);
         break;
     case QMetaType::UInt:
         delete static_cast<uint*>(data);
         break;
     case QMetaType::UShort:
         delete static_cast<ushort*>(data);
         break;
     case QMetaType::UChar:
         delete static_cast<uchar*>(data);
         break;
     case QMetaType::Bool:
         delete static_cast<bool*>(data);
         break;
     case QMetaType::Float:
         delete static_cast<float*>(data);
         break;
     case QMetaType::Double:
         delete static_cast<double*>(data);
         break;
     case QMetaType::QChar:
         delete static_cast< NS(QChar)* >(data);
         break;
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QVariantMap:
         delete static_cast< NS(QVariantMap)* >(data);
         break;
     case QMetaType::QVariantHash:
         delete static_cast< NS(QVariantHash)* >(data);
         break;
     case QMetaType::QVariantList:
         delete static_cast< NS(QVariantList)* >(data);
         break;
     case QMetaType::QVariant:
         delete static_cast< NS(QVariant)* >(data);
         break;
 #endif
     case QMetaType::QByteArray:
         delete static_cast< NS(QByteArray)* >(data);
         break;
     case QMetaType::QString:
         delete static_cast< NS(QString)* >(data);
         break;
     case QMetaType::QStringList:
         delete static_cast< NS(QStringList)* >(data);
         break;
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QBitArray:
         delete static_cast< NS(QBitArray)* >(data);
         break;
 #endif
     case QMetaType::QDate:
         delete static_cast< NS(QDate)* >(data);
         break;
     case QMetaType::QTime:
         delete static_cast< NS(QTime)* >(data);
         break;
     case QMetaType::QDateTime:
         delete static_cast< NS(QDateTime)* >(data);
         break;
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QUrl:
         delete static_cast< NS(QUrl)* >(data);
 #endif
         break;
     case QMetaType::QLocale:
         delete static_cast< NS(QLocale)* >(data);
         break;
 #ifndef QT_NO_GEOM_VARIANT
     case QMetaType::QRect:
         delete static_cast< NS(QRect)* >(data);
         break;
     case QMetaType::QRectF:
         delete static_cast< NS(QRectF)* >(data);
         break;
     case QMetaType::QSize:
         delete static_cast< NS(QSize)* >(data);
         break;
     case QMetaType::QSizeF:
         delete static_cast< NS(QSizeF)* >(data);
         break;
     case QMetaType::QLine:
         delete static_cast< NS(QLine)* >(data);
         break;
     case QMetaType::QLineF:
         delete static_cast< NS(QLineF)* >(data);
         break;
     case QMetaType::QPoint:
         delete static_cast< NS(QPoint)* >(data);
         break;
     case QMetaType::QPointF:
         delete static_cast< NS(QPointF)* >(data);
         break;
 #endif
 #ifndef QT_NO_REGEXP
     case QMetaType::QRegExp:
         delete static_cast< NS(QRegExp)* >(data);
         break;
 #endif
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QEasingCurve:
         delete static_cast< NS(QEasingCurve)* >(data);
         break;
 #endif
     case QMetaType::Void:
         break;
     default: {
         const QVector<QCustomTypeInfo> * const ct = customTypes();
         Destructor destr = 0;
         if (type >= FirstGuiType && type <= LastGuiType) {
             Q_ASSERT(qMetaTypeGuiHelper);
             if (!qMetaTypeGuiHelper)
                 return;
             destr = qMetaTypeGuiHelper[type - FirstGuiType].destr;
         } else {
             QReadLocker locker(customTypesLock());
             if (type < User || !ct || ct->count() <= type - User)
                 break;
             if (ct->at(type - User).typeName.isEmpty())
                 break;
             destr = ct->at(type - User).destr;
         }
         destr(data);
         break; }
     }
 }
isRegistered()
bool QMetaType::isRegistered (int type) static
Returns true if the datatype with ID type is registered; otherwise returns false.
See also
type(), typeName(), Type
Definition at line 590 of file qmetatype.cpp.
Referenced by compare().
 {
     if (type >= 0 && type < User) {
         // predefined type
         return true;
     }
     QReadLocker locker(customTypesLock());
     const QVector<QCustomTypeInfo> * const ct = customTypes();
     return ((type >= User) && (ct && ct->count() > type - User) && !ct->at(type - User).typeName.isEmpty());
 }
load()
bool QMetaType::load (QDataStream & stream, int type, void * data) static
Reads the object of the specified type from the given stream into data.
Returns true if the object is loaded successfully; otherwise returns false.
The type must have been registered with qRegisterMetaType() and qRegisterMetaTypeStreamOperators() beforehand.
Normally, you should not need to call this function directly. Instead, use QVariant's operator>>(), which relies on load() to stream custom types.
See also
save(), qRegisterMetaTypeStreamOperators()
Definition at line 845 of file qmetatype.cpp.
Referenced by QVariant::load().
 {
     if (!data || !isRegistered(type))
         return false;
     switch(type) {
     case QMetaType::Void:
     case QMetaType::VoidStar:
     case QMetaType::QObjectStar:
     case QMetaType::QWidgetStar:
         return false;
     case QMetaType::Long: {
         qlonglong l;
         stream >> l;
         *static_cast<long *>(data) = long(l);
         break; }
     case QMetaType::Int:
         stream >> *static_cast<int *>(data);
         break;
     case QMetaType::Short:
         stream >> *static_cast<short *>(data);
         break;
     case QMetaType::Char:
         // force a char to be signed
         stream >> *static_cast<signed char *>(data);
         break;
     case QMetaType::ULong: {
         qulonglong ul;
         stream >> ul;
         *static_cast<ulong *>(data) = ulong(ul);
         break; }
     case QMetaType::UInt:
         stream >> *static_cast<uint *>(data);
         break;
     case QMetaType::LongLong:
         stream >> *static_cast<qlonglong *>(data);
         break;
     case QMetaType::ULongLong:
         stream >> *static_cast<qulonglong *>(data);
         break;
     case QMetaType::UShort:
         stream >> *static_cast<ushort *>(data);
         break;
     case QMetaType::UChar:
         stream >> *static_cast<uchar *>(data);
         break;
     case QMetaType::Bool: {
         qint8 b;
         stream >> b;
         *static_cast<bool *>(data) = b;
         break; }
     case QMetaType::Float:
         stream >> *static_cast<float *>(data);
         break;
     case QMetaType::Double:
         stream >> *static_cast<double *>(data);
         break;
     case QMetaType::QChar:
         stream >> *static_cast< NS(QChar)*>(data);
         break;
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QVariantMap:
         stream >> *static_cast< NS(QVariantMap)*>(data);
         break;
     case QMetaType::QVariantHash:
         stream >> *static_cast< NS(QVariantHash)*>(data);
         break;
     case QMetaType::QVariantList:
         stream >> *static_cast< NS(QVariantList)*>(data);
         break;
     case QMetaType::QVariant:
         stream >> *static_cast< NS(QVariant)*>(data);
         break;
 #endif
     case QMetaType::QByteArray:
         stream >> *static_cast< NS(QByteArray)*>(data);
         break;
     case QMetaType::QString:
         stream >> *static_cast< NS(QString)*>(data);
         break;
     case QMetaType::QStringList:
         stream >> *static_cast< NS(QStringList)*>(data);
         break;
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QBitArray:
         stream >> *static_cast< NS(QBitArray)*>(data);
         break;
 #endif
     case QMetaType::QDate:
         stream >> *static_cast< NS(QDate)*>(data);
         break;
     case QMetaType::QTime:
         stream >> *static_cast< NS(QTime)*>(data);
         break;
     case QMetaType::QDateTime:
         stream >> *static_cast< NS(QDateTime)*>(data);
         break;
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QUrl:
         stream >> *static_cast< NS(QUrl)*>(data);
         break;
 #endif
     case QMetaType::QLocale:
         stream >> *static_cast< NS(QLocale)*>(data);
         break;
 #ifndef QT_NO_GEOM_VARIANT
     case QMetaType::QRect:
         stream >> *static_cast< NS(QRect)*>(data);
         break;
     case QMetaType::QRectF:
         stream >> *static_cast< NS(QRectF)*>(data);
         break;
     case QMetaType::QSize:
         stream >> *static_cast< NS(QSize)*>(data);
         break;
     case QMetaType::QSizeF:
         stream >> *static_cast< NS(QSizeF)*>(data);
         break;
     case QMetaType::QLine:
         stream >> *static_cast< NS(QLine)*>(data);
         break;
     case QMetaType::QLineF:
         stream >> *static_cast< NS(QLineF)*>(data);
         break;
     case QMetaType::QPoint:
         stream >> *static_cast< NS(QPoint)*>(data);
         break;
     case QMetaType::QPointF:
         stream >> *static_cast< NS(QPointF)*>(data);
         break;
 #endif
 #ifndef QT_NO_REGEXP
     case QMetaType::QRegExp:
         stream >> *static_cast< NS(QRegExp)*>(data);
         break;
 #endif
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QEasingCurve:
         stream >> *static_cast< NS(QEasingCurve)*>(data);
         break;
 #endif
 #ifdef QT3_SUPPORT
     case QMetaType::QColorGroup:
 #endif
     case QMetaType::QFont:
     case QMetaType::QPixmap:
     case QMetaType::QBrush:
     case QMetaType::QColor:
     case QMetaType::QPalette:
     case QMetaType::QIcon:
     case QMetaType::QImage:
     case QMetaType::QPolygon:
     case QMetaType::QRegion:
     case QMetaType::QBitmap:
     case QMetaType::QCursor:
     case QMetaType::QSizePolicy:
     case QMetaType::QKeySequence:
     case QMetaType::QPen:
     case QMetaType::QTextLength:
     case QMetaType::QTextFormat:
     case QMetaType::QMatrix:
     case QMetaType::QTransform:
     case QMetaType::QMatrix4x4:
     case QMetaType::QVector2D:
     case QMetaType::QVector3D:
     case QMetaType::QVector4D:
     case QMetaType::QQuaternion:
         if (!qMetaTypeGuiHelper)
             return false;
         qMetaTypeGuiHelper[type - FirstGuiType].loadOp(stream, data);
         break;
     default: {
         const QVector<QCustomTypeInfo> * const ct = customTypes();
         if (!ct)
             return false;
         LoadOperator loadOp = 0;
         {
             QReadLocker locker(customTypesLock());
             loadOp = ct->at(type - User).loadOp;
         }
         if (!loadOp)
             return false;
         loadOp(stream, data);
         break; }
     }
     return true;
 }
registerStreamOperators() [1/2]
void QMetaType::registerStreamOperators (const char * typeName, SaveOperator saveOp, LoadOperator loadOp) static
Warning
This function is not part of the public interface.
Definition at line 374 of file qmetatype.cpp.
 {
     int idx = type(typeName);
     if (!idx)
         return;
     registerStreamOperators(idx, saveOp, loadOp);
 }
registerStreamOperators() [2/2]
void QMetaType::registerStreamOperators (int idx, SaveOperator saveOp, LoadOperator loadOp) static
Warning
This function is not part of the public interface.
Definition at line 385 of file qmetatype.cpp.
 {
     if (idx < User)
         return; //builtin types should not be registered;
     QVector<QCustomTypeInfo> *ct = customTypes();
     if (!ct)
         return;
     QWriteLocker locker(customTypesLock());
     QCustomTypeInfo &inf = (*ct)[idx - User];
     inf.saveOp = saveOp;
     inf.loadOp = loadOp;
 }
registerType()
int QMetaType::registerType (const char * typeName, Destructor destructor, Constructor constructor) static
Registers a user type for marshalling, with typeName, a destructor, and a constructor.
Warning
This function is not part of the public interface.
Returns the type's handle, or -1 if the type could not be registered.
Definition at line 477 of file qmetatype.cpp.
Referenced by QDeclarativeEnginePrivate::registerCompositeType().
 {
     QVector<QCustomTypeInfo> *ct = customTypes();
     if (!ct || !typeName || !destructor || !constructor)
         return -1;
 #ifdef QT_NO_QOBJECT
     NS(QByteArray) normalizedTypeName = typeName;
 #else
     NS(QByteArray) normalizedTypeName = QMetaObject::normalizedType(typeName);
 #endif
     int idx = qMetaTypeStaticType(normalizedTypeName.constData(),
                                   normalizedTypeName.size());
     if (!idx) {
         QWriteLocker locker(customTypesLock());
         idx = qMetaTypeCustomType_unlocked(normalizedTypeName.constData(),
                                            normalizedTypeName.size());
         if (!idx) {
             QCustomTypeInfo inf;
             inf.typeName = normalizedTypeName;
             inf.constr = constructor;
             inf.destr = destructor;
             inf.alias = -1;
             idx = ct->size() + User;
             ct->append(inf);
         }
     }
     return idx;
 }
registerTypedef()
int QMetaType::registerTypedef (const char * typeName, int aliasId) static
Warning
This function is not part of the public interface.
Since
4.7
Registers a user type for marshalling, as an alias of another type (typedef)
Definition at line 515 of file qmetatype.cpp.
Referenced by qRegisterMetaType().
 {
     QVector<QCustomTypeInfo> *ct = customTypes();
     if (!ct || !typeName)
         return -1;
 #ifdef QT_NO_QOBJECT
     NS(QByteArray) normalizedTypeName = typeName;
 #else
     NS(QByteArray) normalizedTypeName = QMetaObject::normalizedType(typeName);
 #endif
     int idx = qMetaTypeStaticType(normalizedTypeName.constData(),
                                   normalizedTypeName.size());
     if (idx) {
         Q_ASSERT(idx == aliasId);
         return idx;
     }
     QWriteLocker locker(customTypesLock());
     idx = qMetaTypeCustomType_unlocked(normalizedTypeName.constData(),
                                            normalizedTypeName.size());
     if (idx)
         return idx;
     QCustomTypeInfo inf;
     inf.typeName = normalizedTypeName;
     inf.alias = aliasId;
     inf.constr = 0;
     inf.destr = 0;
     ct->append(inf);
     return aliasId;
 }
save()
bool QMetaType::save (QDataStream & stream, int type, const void * data) static
Writes the object pointed to by data with the ID type to the given stream.
Returns true if the object is saved successfully; otherwise returns false.
The type must have been registered with qRegisterMetaType() and qRegisterMetaTypeStreamOperators() beforehand.
Normally, you should not need to call this function directly. Instead, use QVariant's operator<<(), which relies on save() to stream custom types.
See also
load(), qRegisterMetaTypeStreamOperators()
Definition at line 646 of file qmetatype.cpp.
Referenced by QVariant::save().
 {
     if (!data || !isRegistered(type))
         return false;
     switch(type) {
     case QMetaType::Void:
     case QMetaType::VoidStar:
     case QMetaType::QObjectStar:
     case QMetaType::QWidgetStar:
         return false;
     case QMetaType::Long:
         stream << qlonglong(*static_cast<const long *>(data));
         break;
     case QMetaType::Int:
         stream << *static_cast<const int *>(data);
         break;
     case QMetaType::Short:
         stream << *static_cast<const short *>(data);
         break;
     case QMetaType::Char:
         // force a char to be signed
         stream << *static_cast<const signed char *>(data);
         break;
     case QMetaType::ULong:
         stream << qulonglong(*static_cast<const ulong *>(data));
         break;
     case QMetaType::UInt:
         stream << *static_cast<const uint *>(data);
         break;
     case QMetaType::LongLong:
         stream << *static_cast<const qlonglong *>(data);
         break;
     case QMetaType::ULongLong:
         stream << *static_cast<const qulonglong *>(data);
         break;
     case QMetaType::UShort:
         stream << *static_cast<const ushort *>(data);
         break;
     case QMetaType::UChar:
         stream << *static_cast<const uchar *>(data);
         break;
     case QMetaType::Bool:
         stream << qint8(*static_cast<const bool *>(data));
         break;
     case QMetaType::Float:
         stream << *static_cast<const float *>(data);
         break;
     case QMetaType::Double:
         stream << *static_cast<const double *>(data);
         break;
     case QMetaType::QChar:
         stream << *static_cast<const NS(QChar) *>(data);
         break;
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QVariantMap:
         stream << *static_cast<const NS(QVariantMap)*>(data);
         break;
     case QMetaType::QVariantHash:
         stream << *static_cast<const NS(QVariantHash)*>(data);
         break;
     case QMetaType::QVariantList:
         stream << *static_cast<const NS(QVariantList)*>(data);
         break;
     case QMetaType::QVariant:
         stream << *static_cast<const NS(QVariant)*>(data);
         break;
 #endif
     case QMetaType::QByteArray:
         stream << *static_cast<const NS(QByteArray)*>(data);
         break;
     case QMetaType::QString:
         stream << *static_cast<const NS(QString)*>(data);
         break;
     case QMetaType::QStringList:
         stream << *static_cast<const NS(QStringList)*>(data);
         break;
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QBitArray:
         stream << *static_cast<const NS(QBitArray)*>(data);
         break;
 #endif
     case QMetaType::QDate:
         stream << *static_cast<const NS(QDate)*>(data);
         break;
     case QMetaType::QTime:
         stream << *static_cast<const NS(QTime)*>(data);
         break;
     case QMetaType::QDateTime:
         stream << *static_cast<const NS(QDateTime)*>(data);
         break;
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QUrl:
         stream << *static_cast<const NS(QUrl)*>(data);
         break;
 #endif
     case QMetaType::QLocale:
         stream << *static_cast<const NS(QLocale)*>(data);
         break;
 #ifndef QT_NO_GEOM_VARIANT
     case QMetaType::QRect:
         stream << *static_cast<const NS(QRect)*>(data);
         break;
     case QMetaType::QRectF:
         stream << *static_cast<const NS(QRectF)*>(data);
         break;
     case QMetaType::QSize:
         stream << *static_cast<const NS(QSize)*>(data);
         break;
     case QMetaType::QSizeF:
         stream << *static_cast<const NS(QSizeF)*>(data);
         break;
     case QMetaType::QLine:
         stream << *static_cast<const NS(QLine)*>(data);
         break;
     case QMetaType::QLineF:
         stream << *static_cast<const NS(QLineF)*>(data);
         break;
     case QMetaType::QPoint:
         stream << *static_cast<const NS(QPoint)*>(data);
         break;
     case QMetaType::QPointF:
         stream << *static_cast<const NS(QPointF)*>(data);
         break;
 #endif
 #ifndef QT_NO_REGEXP
     case QMetaType::QRegExp:
         stream << *static_cast<const NS(QRegExp)*>(data);
         break;
 #endif
 #ifndef QT_BOOTSTRAPPED
     case QMetaType::QEasingCurve:
         stream << *static_cast<const NS(QEasingCurve)*>(data);
         break;
 #endif
 #ifdef QT3_SUPPORT
     case QMetaType::QColorGroup:
 #endif
     case QMetaType::QFont:
     case QMetaType::QPixmap:
     case QMetaType::QBrush:
     case QMetaType::QColor:
     case QMetaType::QPalette:
     case QMetaType::QIcon:
     case QMetaType::QImage:
     case QMetaType::QPolygon:
     case QMetaType::QRegion:
     case QMetaType::QBitmap:
     case QMetaType::QCursor:
     case QMetaType::QSizePolicy:
     case QMetaType::QKeySequence:
     case QMetaType::QPen:
     case QMetaType::QTextLength:
     case QMetaType::QTextFormat:
     case QMetaType::QMatrix:
     case QMetaType::QTransform:
     case QMetaType::QMatrix4x4:
     case QMetaType::QVector2D:
     case QMetaType::QVector3D:
     case QMetaType::QVector4D:
     case QMetaType::QQuaternion:
         if (!qMetaTypeGuiHelper)
             return false;
         qMetaTypeGuiHelper[type - FirstGuiType].saveOp(stream, data);
         break;
     default: {
         const QVector<QCustomTypeInfo> * const ct = customTypes();
         if (!ct)
             return false;
         SaveOperator saveOp = 0;
         {
             QReadLocker locker(customTypesLock());
             saveOp = ct->at(type - User).saveOp;
         }
         if (!saveOp)
             return false;
         saveOp(stream, data);
         break; }
     }
     return true;
 }
type()
int QMetaType::type (const char * typeName) static
Returns a handle to the type called typeName, or 0 if there is no such type.
See also
isRegistered(), typeName(), Type
Definition at line 607 of file qmetatype.cpp.
Referenced by MetaObjectGenerator::addProperty(), QAxBase::asVariant(), QDeclarativeObjectMethodScriptClass::callOverloaded(), QDeclarativeObjectMethodScriptClass::callPrecise(), QScript::callQtMethod(), QScriptEnginePrivate::convertValue(), QScript::QObjectConnectionManager::execute(), QDBusMetaObjectGenerator::findType(), QStateMachinePrivate::handleTransitionSignal(), QSignalSpy::initArgs(), QAxBase::internalInvoke(), QMetaMethod::invoke(), QAxServerBase::Invoke(), QScriptEnginePrivate::jscValueToVariant(), QDeclarativePropertyCache::Data::load(), QVariant::load(), QVariant::nameToType(), QScriptEnginePrivate::newQObject(), QDeclarativeDomDynamicProperty::propertyType(), qDBusNameToTypeId(), QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters(), QTest::qSignalDumperCallback(), QAxServerBase::qt_metacall(), QAxBase::querySubObject(), queuedConnectionTypes(), qvariant_nameToType(), QVariantToVARIANT(), QMetaProperty::read(), QMetaProperty::type(), QScript::QScriptMetaType::typeId(), QMetaProperty::userType(), QScript::variantFromValue(), VARIANTToQVariant(), QMetaProperty::write(), and QDeclarativePropertyPrivate::writeEnumProperty().
 {
     int length = qstrlen(typeName);
     if (!length)
         return 0;
     int type = qMetaTypeStaticType(typeName, length);
     if (!type) {
         QReadLocker locker(customTypesLock());
         type = qMetaTypeCustomType_unlocked(typeName, length);
 #ifndef QT_NO_QOBJECT
         if (!type) {
             const NS(QByteArray) normalizedTypeName = QMetaObject::normalizedType(typeName);
             type = qMetaTypeStaticType(normalizedTypeName.constData(),
                                        normalizedTypeName.size());
             if (!type) {
                 type = qMetaTypeCustomType_unlocked(normalizedTypeName.constData(),
                                                     normalizedTypeName.size());
             }
         }
 #endif
     }
     return type;
 }
typeName()
const char * QMetaType::typeName (int type) static
Returns the type name associated with the given type, or 0 if no matching type was found.
The returned pointer must not be deleted.
See also
type(), isRegistered(), Type
Definition at line 406 of file qmetatype.cpp.
Referenced by QTestData::append(), compare(), convert(), QScriptEnginePrivate::convertValue(), QScriptEnginePrivate::create(), QDBusConnectionPrivate::deliverCall(), QTest::fetchData(), QScript::QScriptMetaType::name(), QVariant::save(), QDBusPendingCallPrivate::setMetaTypes(), QDeclarativeObjectScriptClass::setProperty(), QVariant::typeToName(), and QDeclarativeBinding::update().
 {
     enum { GuiTypeCount = LastGuiType - FirstGuiType };
     if (type >= 0 && type <= LastCoreType) {
         return types[type].typeName;
     } else if (type >= FirstGuiType && type <= LastGuiType) {
         return types[type - FirstGuiType + LastCoreType + 1].typeName;
     } else if (type >= FirstCoreExtType && type <= LastCoreExtType) {
         return types[type - FirstCoreExtType + GuiTypeCount + LastCoreType + 2].typeName;
     } else if (type >= User) {
         const QVector<QCustomTypeInfo> * const ct = customTypes();
         QReadLocker locker(customTypesLock());
         return ct && ct->count() > type - User && !ct->at(type - User).typeName.isEmpty()
                 ? ct->at(type - User).typeName.constData()
                 : static_cast<const char *>(0);
     }
     return 0;
 }
unregisterType()
void QMetaType::unregisterType (const char * typeName) static
Unregisters a user type, with typeName.
Since
4.4
See also
type(), typeName()
Definition at line 561 of file qmetatype.cpp.
 {
     QVector<QCustomTypeInfo> *ct = customTypes();
     if (!ct || !typeName)
         return;
 #ifdef QT_NO_QOBJECT
     NS(QByteArray) normalizedTypeName = typeName;
 #else
     NS(QByteArray) normalizedTypeName = QMetaObject::normalizedType(typeName);
 #endif
     QWriteLocker locker(customTypesLock());
     for (int v = 0; v < ct->count(); ++v) {
         if (ct->at(v).typeName == typeName) {
             QCustomTypeInfo &inf = (*ct)[v];
             inf.typeName.clear();
             inf.constr = 0;
             inf.destr = 0;
             inf.alias = -1;
         }
     }
 }
Friends and Related Functions
qMetaTypeId()
int qMetaTypeId () related
Returns the meta type id of type T at compile time.
Note
This class or function is threadsafe.
Since
4.1
If the type was not declared with Q_DECLARE_METATYPE(), compilation will fail.
Typical usage:
int id = qMetaTypeId<QString>();    // id is now QMetaType::QString
id = qMetaTypeId<MyStruct>();       // compile error if MyStruct not declared
QMetaType::type() returns the same ID as qMetaTypeId(), but does a lookup at runtime based on the name of the type. QMetaType::type() is a bit slower, but compilation succeeds if a type is not registered.
See also
Q_DECLARE_METATYPE(), QMetaType::type()
Definition at line 224 of file qmetatype.h.
 {
     return QMetaTypeId2<T>::qt_metatype_id();
 }
qRegisterMetaType() [1/2]
int qRegisterMetaType (const char * typeName) related
Note
This class or function is threadsafe.
Registers the type name typeName for the type T. Returns the internal ID used by QMetaType. Any class or struct that has a public default constructor, a public copy constructor and a public destructor can be registered.
After a type has been registered, you can create and destroy objects of that type dynamically at run-time.
This example registers the class MyClass:
qRegisterMetaType<MyClass>("MyClass");
This function is useful to register typedefs so they can be used by QMetaProperty, or in QueuedConnections
typedef QString CustomString;
qRegisterMetaType<CustomString>("CustomString");
See also
qRegisterMetaTypeStreamOperators(), QMetaType::isRegistered(), Q_DECLARE_METATYPE()
Definition at line 185 of file qmetatype.h.
 {
     const int typedefOf = dummy ? -1 : QtPrivate::QMetaTypeIdHelper<T>::qt_metatype_id();
     if (typedefOf != -1)
         return QMetaType::registerTypedef(typeName, typedefOf);
     typedef void*(*ConstructPtr)(const T*);
     ConstructPtr cptr = qMetaTypeConstructHelper<T>;
     typedef void(*DeletePtr)(T*);
     DeletePtr dptr = qMetaTypeDeleteHelper<T>;
     return QMetaType::registerType(typeName, reinterpret_cast<QMetaType::Destructor>(dptr),
                                    reinterpret_cast<QMetaType::Constructor>(cptr));
 }
qRegisterMetaType() [2/2]
int qRegisterMetaType () related
Call this function to register the type T.
Note
This class or function is threadsafe.
Since
4.2
T must be declared with Q_DECLARE_METATYPE(). Returns the meta type Id.
Example:
int id = qRegisterMetaType<MyStruct>();
To use the type T in QVariant, using Q_DECLARE_METATYPE() is sufficient. To use the type T in queued signal and slot connections, qRegisterMetaType<T>() must be called before the first connection is established.
Also, to use type T with the QObject::property() API, qRegisterMetaType<T>() must be called before it is used, typically in the constructor of the class that uses T, or in the main() function.
See also
Q_DECLARE_METATYPE()
Definition at line 234 of file qmetatype.h.
Referenced by convertTypes(), qAxFactory(), qmlRegisterCustomType(), qmlRegisterExtendedType(), qmlRegisterInterface(), qmlRegisterRevision(), qmlRegisterType(), and qmlRegisterUncreatableType().
 {
 #ifdef Q_CC_SUN
     return qMetaTypeId(static_cast<T *>(0));
 #else
     return qMetaTypeId(dummy);
 #endif
 }
qRegisterMetaTypeStreamOperators()
int qRegisterMetaTypeStreamOperators (const char * typeName) related
Note
This class or function is threadsafe.
Registers the stream operators for the type T called typeName.
Afterward, the type can be streamed using QMetaType::load() and QMetaType::save(). These functions are used when streaming a QVariant.
qRegisterMetaTypeStreamOperators<MyClass>("MyClass");
The stream operators should have the following signatures:
QDataStream &operator<<(QDataStream &out, const MyClass &myObj);
QDataStream &operator>>(QDataStream &in, MyClass &myObj);
See also
qRegisterMetaType(), QMetaType::isRegistered(), Q_DECLARE_METATYPE()
Definition at line 206 of file qmetatype.h.
 {
     typedef void(*SavePtr)(QDataStream &, const T *);
     typedef void(*LoadPtr)(QDataStream &, T *);
     SavePtr sptr = qMetaTypeSaveHelper<T>;
     LoadPtr lptr = qMetaTypeLoadHelper<T>;
     qRegisterMetaType<T>(typeName);
     QMetaType::registerStreamOperators(typeName, reinterpret_cast<QMetaType::SaveOperator>(sptr),
                                        reinterpret_cast<QMetaType::LoadOperator>(lptr));
 }
The documentation for this class was generated from the following files:
/src/corelib/kernel/qmetatype.h
/src/corelib/kernel/qmetatype.cpp