Qt 4.8: QSizeF Class Reference
QSizeF Class Reference
The QSizeF class defines the size of a two-dimensional object using floating point precision.
#include <qsize.h>
Public Functions
QSizeF boundedTo (const QSizeF &) const
Returns a size holding the minimum width and height of this size and the given otherSize.
QSizeF expandedTo (const QSizeF &) const
Returns a size holding the maximum width and height of this size and the given otherSize.
qreal height () const
Returns the height.
bool isEmpty () const
Returns true if either of the width and height is less than or equal to 0; otherwise returns false.
bool isNull () const
Returns true if both the width and height are +0.
bool isValid () const
Returns true if both the width and height is equal to or greater than 0; otherwise returns false.
QSizeF & operator*= (qreal c)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Multiplies both the width and height by the given factor and returns a reference to the size.
QSizeF & operator+= (const QSizeF &)
Adds the given size to this size and returns a reference to this size.
QSizeF & operator-= (const QSizeF &)
Subtracts the given size from this size and returns a reference to this size.
QSizeF & operator/= (qreal c)
Divides both the width and height by the given divisor and returns a reference to the size.
QSizeF ()
Constructs an invalid size.
QSizeF (const QSize &sz)
Constructs a size with floating point accuracy from the given size.
QSizeF (qreal w, qreal h)
Constructs a size with the given width and height.
qreal & rheight ()
Returns a reference to the height.
qreal & rwidth ()
Returns a reference to the width.
void scale (qreal w, qreal h, Qt::AspectRatioMode mode)
Scales the size to a rectangle with the given width and height, according to the specified mode.
void scale (const QSizeF &s, Qt::AspectRatioMode mode)
Scales the size to a rectangle with the given size, according to the specified mode.
void setHeight (qreal h)
Sets the height to the given height.
void setWidth (qreal w)
Sets the width to the given width.
QSize toSize () const
Returns an integer based copy of this size.
void transpose ()
Swaps the width and height values.
qreal width () const
Returns the width.
Properties
qreal ht
qreal wd
Friends
bool operator!= (const QSizeF &, const QSizeF &)
Returns true if s1 and s2 are different; otherwise returns false.
const QSizeF operator* (const QSizeF &, qreal)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
const QSizeF operator* (qreal, const QSizeF &)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
const QSizeF operator+ (const QSizeF &, const QSizeF &)
Returns the sum of s1 and s2; each component is added separately.
const QSizeF operator- (const QSizeF &, const QSizeF &)
Returns s2 subtracted from s1; each component is subtracted separately.
const QSizeF operator/ (const QSizeF &, qreal)
Divides the given size by the given divisor and returns the result.
bool operator== (const QSizeF &, const QSizeF &)
Returns true if s1 and s2 are equal; otherwise returns false.
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QSizeF &size)
Writes the given size to the given stream and returns a reference to the stream.
QDataStream & operator>> (QDataStream &stream, QSizeF &size)
Reads a size from the given stream into the given size and returns a reference to the stream.
Detailed Description
The QSizeF class defines the size of a two-dimensional object using floating point precision.
A size is specified by a width() and a height(). It can be set in the constructor and changed using the setWidth(), setHeight(), or scale() functions, or using arithmetic operators. A size can also be manipulated directly by retrieving references to the width and height using the rwidth() and rheight() functions. Finally, the width and height can be swapped using the transpose() function.
The isValid() function determines if a size is valid. A valid size has both width and height greater than or equal to zero. The isEmpty() function returns true if either of the width and height is less than (or equal to) zero, while the isNull() function returns true only if both the width and the height is zero.
Use the expandedTo() function to retrieve a size which holds the maximum height and width of this size and a given size. Similarly, the boundedTo() function returns a size which holds the minimum height and width of this size and a given size.
The QSizeF class also provides the toSize() function returning a QSize copy of this size, constructed by rounding the width and height to the nearest integers.
QSizeF objects can be streamed as well as compared.
See also
QSize, QPointF, QRectF
Definition at line 202 of file qsize.h.
Constructors and Destructors
QSizeF() [1/3]
QSizeF::QSizeF () inline
Constructs an invalid size.
See also
isValid()
Definition at line 264 of file qsize.h.
Referenced by boundedTo(), expandedTo(), operator*(), operator+(), operator-(), operator/(), and scale().
 { wd = ht = -1.; }
QSizeF() [2/3]
QSizeF::QSizeF (const QSize & size) inline
Constructs a size with floating point accuracy from the given size.
See also
toSize()
Definition at line 267 of file qsize.h.
     : wd(sz.width()), ht(sz.height())
 {
 }
QSizeF() [3/3]
QSizeF::QSizeF (qreal w, qreal h) inline
Constructs a size with the given width and height.
Definition at line 272 of file qsize.h.
 { wd = w; ht = h; }
Functions
boundedTo()
QSizeF QSizeF::boundedTo (const QSizeF & otherSize) const inline
Returns a size holding the minimum width and height of this size and the given otherSize.
See also
expandedTo(), scale()
Definition at line 350 of file qsize.h.
Referenced by QGridLayoutItem::geometryWithin(), QGraphicsLayoutItem::setGeometry(), QGraphicsWidget::setGeometry(), and QGraphicsView::sizeHint().
 {
     return QSizeF(qMin(wd,otherSize.wd), qMin(ht,otherSize.ht));
 }
expandedTo()
QSizeF QSizeF::expandedTo (const QSizeF & otherSize) const inline
Returns a size holding the maximum width and height of this size and the given otherSize.
See also
boundedTo(), scale()
Definition at line 345 of file qsize.h.
Referenced by QGraphicsLayoutItem::setGeometry(), and QGraphicsWidget::setGeometry().
 {
     return QSizeF(qMax(wd,otherSize.wd), qMax(ht,otherSize.ht));
 }
height()
qreal QSizeF::height () const inline
Returns the height.
See also
width(), setHeight()
Definition at line 287 of file qsize.h.
Referenced by _q_boundGeometryToSizeConstraints(), QPageSetupWidget::_q_paperSizeChanged(), QGraphicsTextItemPrivate::_q_updateBoundingRect(), QDeclarativeLoaderPrivate::_q_updateSize(), QTextDocument::adjustSize(), QDeclarativePaintedItem::boundingRect(), boundSize(), QGridLayoutItem::box(), QBlitterPaintEnginePrivate::clipAndDrawPixmap(), closestAcceptableSize(), combineSize(), QGraphicsTextItemPrivate::controlOffset(), QDeclarativeRow::doPositioning(), QDeclarativeFlow::doPositioning(), QSvgText::draw(), QTextDocumentLayoutPrivate::drawBorder(), QItemDelegate::drawDisplay(), QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawListItem(), QTextDocumentLayout::dynamicPageCount(), QGridLayoutItem::effectiveMaxSize(), QGraphicsLayoutItemPrivate::effectiveSizeHints(), QGridLayoutEngine::ensureGeometries(), epsilonCompare(), expandSize(), QFixedSize::fromSizeF(), QDeclarativeCompiler::genLiteralAssignment(), QGridLayoutItem::geometryWithin(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutFrame(), QTextDocumentLayoutPrivate::layoutTable(), QGraphicsLayoutItem::maximumHeight(), QGraphicsLayoutItem::minimumHeight(), minimumHeightForWidth(), operator<<(), QPdfBaseEnginePrivate::pageRect(), QtopiaPrintEngine::paperRect(), QPdfBaseEnginePrivate::paperRect(), QPdf::paperSize(), QPrinter::paperSize(), QGraphicsLayoutItem::preferredHeight(), QDeclarativeBasePositioner::prePositioning(), qDrawRoundedCorners(), QRectF::QRectF(), qSizeFTopaperSize(), QSvgIOHandler::read(), QTextDocumentLayout::resizeInlineObject(), QAbstractTextDocumentLayout::resizeInlineObject(), QDeclarativeViewPrivate::rootObjectSize(), QGraphicsWidget::setGeometry(), QGraphicsAnchorLayoutPrivate::setItemsGeometries(), QPrinter::setPaperSize(), QPageSetupWidget::setPrinter(), QWin32PrintEngine::setProperty(), QGraphicsLayoutItemPrivate::setSize(), QDeclarativeItem::setSize(), QRectF::setSize(), QGLShaderProgram::setUniformValue(), QDeclarativeSizeFValueType::setValue(), sizeForOrientation(), QLabelPrivate::sizeForWidth(), QGridLayoutEngine::sizeHint(), QGraphicsTextItemPrivate::textControl(), QItemDelegate::textRectangle(), QTest::toString(), and QPageSetupWidget::unitChanged().
 { return ht; }
isEmpty()
bool QSizeF::isEmpty () const inline
Returns true if either of the width and height is less than or equal to 0; otherwise returns false.
See also
isNull(), isValid()
Definition at line 278 of file qsize.h.
Referenced by QBlitterPaintEngine::fillRect(), and qDrawRoundedCorners().
 { return wd <= 0. || ht <= 0.; }
isNull()
bool QSizeF::isNull () const inline
Returns true if both the width and height are +0.
0; otherwise returns false.
Note
Since this function treats +0.0 and -0.0 differently, sizes with zero width and height where either or both values have a negative sign are not defined to be null sizes.
See also
isValid(), isEmpty()
Definition at line 275 of file qsize.h.
Referenced by QTextEdit::resizeEvent().
 { return qIsNull(wd) && qIsNull(ht); }
isValid()
bool QSizeF::isValid () const inline
Returns true if both the width and height is equal to or greater than 0; otherwise returns false.
See also
isNull(), isEmpty()
Definition at line 281 of file qsize.h.
Referenced by QGraphicsWidget::adjustSize(), QGridLayoutItem::effectiveMaxSize(), QGraphicsLayoutItem::effectiveSizeHint(), and QDeclarativeViewPrivate::updateSize().
 { return wd >= 0. && ht >= 0.; }
operator*=()
QSizeF & QSizeF::operator*= (qreal factor) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Multiplies both the width and height by the given factor and returns a reference to the size.
See also
scale()
Definition at line 311 of file qsize.h.
 { wd *= c; ht *= c; return *this; }
operator+=()
QSizeF & QSizeF::operator+= (const QSizeF & size) inline
Adds the given size to this size and returns a reference to this size.
For example:
QSizeF s(3, 7);
QSizeF r(-1, 4);
s += r;
// s becomes (2,11)
Definition at line 305 of file qsize.h.
 { wd += s.wd; ht += s.ht; return *this; }
operator-=()
QSizeF & QSizeF::operator-= (const QSizeF & size) inline
Subtracts the given size from this size and returns a reference to this size.
For example:
QSizeF s(3, 7);
QSizeF r(-1, 4);
s -= r;
// s becomes (4,3)
Definition at line 308 of file qsize.h.
 { wd -= s.wd; ht -= s.ht; return *this; }
operator/=()
QSizeF & QSizeF::operator/= (qreal divisor) inline
Divides both the width and height by the given divisor and returns a reference to the size.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
scale()
Definition at line 332 of file qsize.h.
 {
     Q_ASSERT(!qFuzzyIsNull(c));
     wd = wd/c; ht = ht/c;
     return *this;
 }
rheight()
qreal & QSizeF::rheight () inline
Returns a reference to the height.
Using a reference makes it possible to manipulate the height directly. For example:
QSizeF size(100, 10.2);
size.rheight() += 5.5;
// size becomes (100,15.7)
See also
rwidth(), setHeight()
Definition at line 302 of file qsize.h.
Referenced by QGraphicsLayoutItemPrivate::effectiveSizeHints(), QPainterPath::operator==(), QtopiaPrintEngine::paperRect(), and QGraphicsLayoutItemPrivate::setSizeComponent().
 { return ht; }
rwidth()
qreal & QSizeF::rwidth () inline
Returns a reference to the width.
Using a reference makes it possible to manipulate the width directly. For example:
QSizeF size(100.3, 10);
size.rwidth() += 20.5;
 // size becomes (120.8,10)
See also
rheight(), setWidth()
Definition at line 299 of file qsize.h.
Referenced by QGraphicsLayoutItemPrivate::effectiveSizeHints(), QPainterPath::operator==(), and QtopiaPrintEngine::paperRect().
 { return wd; }
scale() [1/2]
void QSizeF::scale (qreal width, qreal height, Qt::AspectRatioMode mode) inline
Scales the size to a rectangle with the given width and height, according to the specified mode.
If mode is Qt::IgnoreAspectRatio, the size is set to (width, height).
If mode is Qt::KeepAspectRatio, the current size is scaled to a rectangle as large as possible inside (width, height), preserving the aspect ratio.
If mode is Qt::KeepAspectRatioByExpanding, the current size is scaled to a rectangle as small as possible outside (width, height), preserving the aspect ratio.
Example:
QSizeF t1(10, 12);
t1.scale(60, 60, Qt::IgnoreAspectRatio);
// t1 is (60, 60)
QSizeF t2(10, 12);
t2.scale(60, 60, Qt::KeepAspectRatio);
// t2 is (50, 60)
QSizeF t3(10, 12);
t3.scale(60, 60, Qt::KeepAspectRatioByExpanding);
// t3 is (60, 72)
See also
setWidth(), setHeight()
Definition at line 296 of file qsize.h.
Referenced by QPagePreview::paintEvent().
 { scale(QSizeF(w, h), mode); }
scale() [2/2]
void QSizeF::scale (const QSizeF & size, Qt::AspectRatioMode mode)
Scales the size to a rectangle with the given size, according to the specified mode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 726 of file qsize.cpp.
 {
     if (mode == Qt::IgnoreAspectRatio || qIsNull(wd) || qIsNull(ht)) {
         wd = s.wd;
         ht = s.ht;
     } else {
         bool useHeight;
         qreal rw = s.ht * wd / ht;
         if (mode == Qt::KeepAspectRatio) {
             useHeight = (rw <= s.wd);
         } else { // mode == Qt::KeepAspectRatioByExpanding
             useHeight = (rw >= s.wd);
         }
         if (useHeight) {
             wd = rw;
             ht = s.ht;
         } else {
             ht = s.wd * ht / wd;
             wd = s.wd;
         }
     }
 }
setHeight()
void QSizeF::setHeight (qreal height) inline
Sets the height to the given height.
See also
height(), rheight(), setWidth()
Definition at line 293 of file qsize.h.
Referenced by QPageSetupWidget::_q_paperSizeChanged(), QDeclarativeLoaderPrivate::_q_updateSize(), boundSize(), combineSize(), QDeclarativeColumn::doPositioning(), QDeclarativeRow::doPositioning(), QDeclarativeGrid::doPositioning(), QDeclarativeFlow::doPositioning(), QTextDocumentLayoutPrivate::drawListItem(), QGridLayoutItem::effectiveMaxSize(), QGraphicsLayoutItemPrivate::effectiveSizeHints(), expandSize(), operator>>(), QDeclarativeSizeFValueType::setHeight(), and QTextDocument::setTextWidth().
 { ht = h; }
setWidth()
void QSizeF::setWidth (qreal width) inline
Sets the width to the given width.
See also
width(), rwidth(), setHeight()
Definition at line 290 of file qsize.h.
Referenced by QPageSetupWidget::_q_paperSizeChanged(), QDeclarativeLoaderPrivate::_q_updateSize(), boundSize(), combineSize(), QDeclarativeColumn::doPositioning(), QDeclarativeRow::doPositioning(), QDeclarativeGrid::doPositioning(), QDeclarativeFlow::doPositioning(), QTextDocumentLayoutPrivate::drawListItem(), QGridLayoutItem::effectiveMaxSize(), QGraphicsLayoutItemPrivate::effectiveSizeHints(), QPicture::exec(), expandSize(), operator>>(), QPainterReplayer::process(), QTextDocument::setTextWidth(), and QDeclarativeSizeFValueType::setWidth().
 { wd = w; }
toSize()
QSize QSizeF::toSize () const inline
Returns an integer based copy of this size.
Note that the coordinates in the returned size will be rounded to the nearest integer.
See also
QSizeF()
Definition at line 355 of file qsize.h.
Referenced by documentSize(), QVGPaintEngine::drawImage(), QPagePreview::paintEvent(), QMacPrintEnginePrivate::paperSize(), QWhatsThat::QWhatsThat(), QTextEditPrivate::relayoutDocument(), QGraphicsProxyWidget::resizeEvent(), QMacPrintEnginePrivate::setPaperSize(), QGraphicsView::sizeHint(), and QDeclarativeTextPrivate::textDocumentImage().
 {
     return QSize(qRound(wd), qRound(ht));
 }
transpose()
void QSizeF::transpose ()
Swaps the width and height values.
See also
setWidth(), setHeight()
Definition at line 686 of file qsize.cpp.
 {
     qreal tmp = wd;
     wd = ht;
     ht = tmp;
 }
width()
qreal QSizeF::width () const inline
Returns the width.
See also
height(), setWidth()
Definition at line 284 of file qsize.h.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), _q_boundGeometryToSizeConstraints(), QPageSetupWidget::_q_paperSizeChanged(), QDeclarativeLoaderPrivate::_q_updateSize(), QTextDocument::adjustSize(), QDeclarativePaintedItem::boundingRect(), boundSize(), QGridLayoutItem::box(), QBlitterPaintEnginePrivate::clipAndDrawPixmap(), closestAcceptableSize(), combineSize(), QDeclarativeColumn::doPositioning(), QDeclarativeRow::doPositioning(), QDeclarativeFlow::doPositioning(), QSvgText::draw(), QTextDocumentLayoutPrivate::drawBlock(), QItemDelegate::drawDisplay(), QTextDocumentLayoutPrivate::drawListItem(), QGridLayoutItem::effectiveMaxSize(), QGraphicsLayoutItemPrivate::effectiveSizeHints(), QGridLayoutEngine::ensureGeometries(), epsilonCompare(), expandSize(), QFixedSize::fromSizeF(), QDeclarativeCompiler::genLiteralAssignment(), QGridLayoutItem::geometryWithin(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutFrame(), QGraphicsLayoutItem::maximumWidth(), minimumHeightForWidth(), QGraphicsLayoutItem::minimumWidth(), operator<<(), QPdfBaseEnginePrivate::pageRect(), QPlainTextEdit::paintEvent(), QtopiaPrintEngine::paperRect(), QPdfBaseEnginePrivate::paperRect(), QPdf::paperSize(), QPrinter::paperSize(), QGraphicsLayoutItem::preferredWidth(), QDeclarativeBasePositioner::prePositioning(), qDrawRoundedCorners(), QRectF::QRectF(), qSizeFTopaperSize(), QSvgIOHandler::read(), QTextDocumentLayout::resizeInlineObject(), QAbstractTextDocumentLayout::resizeInlineObject(), QDeclarativeViewPrivate::rootObjectSize(), QGraphicsWidget::setGeometry(), QGraphicsAnchorLayoutPrivate::setItemsGeometries(), QPrinter::setPaperSize(), QPageSetupWidget::setPrinter(), QWin32PrintEngine::setProperty(), QGraphicsLayoutItemPrivate::setSize(), QDeclarativeItem::setSize(), QRectF::setSize(), QTextBrowserPrivate::setSource(), QGLShaderProgram::setUniformValue(), QDeclarativeSizeFValueType::setValue(), sizeForOrientation(), QLabelPrivate::sizeForWidth(), QGridLayoutEngine::sizeHint(), QMacStyle::subControlRect(), QItemDelegate::textRectangle(), QTest::toString(), and QPageSetupWidget::unitChanged().
 { return wd; }
Friends and Related Functions
operator!=
bool operator!= (const QSizeF & s1, const QSizeF & s2) friend
Returns true if s1 and s2 are different; otherwise returns false.
Definition at line 317 of file qsize.h.
 { return !qFuzzyCompare(s1.wd, s2.wd) || !qFuzzyCompare(s1.ht, s2.ht); }
operator* [1/2]
const QSizeF operator* (const QSizeF & size, qreal factor) friend
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Multiplies the given size by the given factor and returns the result.
See also
QSizeF::scale()
Definition at line 326 of file qsize.h.
 { return QSizeF(s.wd*c, s.ht*c); }
operator* [2/2]
const QSizeF operator* (qreal factor, const QSizeF & size) friend
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Multiplies the given size by the given factor and returns the result.
Definition at line 329 of file qsize.h.
 { return QSizeF(s.wd*c, s.ht*c); }
operator+
const QSizeF operator+ (const QSizeF & s1, const QSizeF & s2) friend
Returns the sum of s1 and s2; each component is added separately.
Definition at line 320 of file qsize.h.
 { return QSizeF(s1.wd+s2.wd, s1.ht+s2.ht); }
operator-
const QSizeF operator- (const QSizeF & s1, const QSizeF & s2) friend
Returns s2 subtracted from s1; each component is subtracted separately.
Definition at line 323 of file qsize.h.
 { return QSizeF(s1.wd-s2.wd, s1.ht-s2.ht); }
operator/
const QSizeF operator/ (const QSizeF & size, qreal divisor) friend
Divides the given size by the given divisor and returns the result.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
QSizeF::scale()
Definition at line 339 of file qsize.h.
 {
     Q_ASSERT(!qFuzzyIsNull(c));
     return QSizeF(s.wd/c, s.ht/c);
 }
operator<<()
QDataStream & operator<< (QDataStream & stream, const QSizeF & size) related
Writes the given size to the given stream and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 953 of file qsize.cpp.
Referenced by toSize().
 {
     s << double(sz.width()) << double(sz.height());
     return s;
 }
operator==
bool operator== (const QSizeF & s1, const QSizeF & s2) friend
Returns true if s1 and s2 are equal; otherwise returns false.
Definition at line 314 of file qsize.h.
 { return qFuzzyCompare(s1.wd, s2.wd) && qFuzzyCompare(s1.ht, s2.ht); }
operator>>()
QDataStream & operator>> (QDataStream & stream, QSizeF & size) related
Reads a size from the given stream into the given size and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 972 of file qsize.cpp.
 {
     double w, h;
     s >> w;
     s >> h;
     sz.setWidth(qreal(w));
     sz.setHeight(qreal(h));
     return s;
 }
Properties
ht
qreal QSizeF::ht private
Definition at line 245 of file qsize.h.
Referenced by boundedTo(), expandedTo(), height(), isEmpty(), isNull(), isValid(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), QSizeF(), rheight(), scale(), setHeight(), and toSize().
wd
qreal QSizeF::wd private
Definition at line 244 of file qsize.h.
Referenced by boundedTo(), expandedTo(), isEmpty(), isNull(), isValid(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), QSizeF(), rwidth(), scale(), setWidth(), toSize(), and width().
The documentation for this class was generated from the following files:
/src/corelib/tools/qsize.h
/src/corelib/tools/qsize.cpp