Qt 4.8: QAudioDeviceInfoInternal Class Reference
QAudioDeviceInfoInternal Class Reference
#include <qaudiodeviceinfo_alsa_p.h>
Public Functions
QList< QAudioFormat::Endian > byteOrderList ()
Returns the list of currently available byte orders.
QList< QAudioFormat::Endian > byteOrderList ()
Returns the list of currently available byte orders.
QList< QAudioFormat::Endian > byteOrderList ()
Returns the list of currently available byte orders.
QList< int > channelsList ()
Returns the list of currently available channels.
QList< int > channelsList ()
Returns the list of currently available channels.
QList< int > channelsList ()
Returns the list of currently available channels.
void close ()
QStringList codecList ()
Returns the list of currently available codecs.
QStringList codecList ()
Returns the list of currently available codecs.
QStringList codecList ()
Returns the list of currently available codecs.
QString deviceName () const
Returns the audio device name.
QString deviceName () const
Returns the audio device name.
QString deviceName () const
Returns the audio device name.
QList< int > frequencyList ()
Returns the list of currently available frequencies.
QList< int > frequencyList ()
Returns the list of currently available frequencies.
QList< int > frequencyList ()
Returns the list of currently available frequencies.
bool isFormatSupported (const QAudioFormat &format) const
Returns true if format is available from audio device.
bool isFormatSupported (const QAudioFormat &format) const
Returns true if format is available from audio device.
bool isFormatSupported (const QAudioFormat &format) const
Returns true if format is available from audio device.
QAudioFormat nearestFormat (const QAudioFormat &format) const
Returns the nearest settings format.
QAudioFormat nearestFormat (const QAudioFormat &format) const
Returns the nearest settings format.
QAudioFormat nearestFormat (const QAudioFormat &format) const
Returns the nearest settings format.
bool open ()
QAudioFormat preferredFormat () const
Returns the nearest settings.
QAudioFormat preferredFormat () const
Returns the nearest settings.
QAudioFormat preferredFormat () const
Returns the nearest settings.
QAudioDeviceInfoInternal (QByteArray const &handle, QAudio::Mode mode)
QAudioDeviceInfoInternal (QByteArray dev, QAudio::Mode mode)
QAudioDeviceInfoInternal (QByteArray dev, QAudio::Mode mode)
QList< int > sampleSizeList ()
Returns the list of currently available sample sizes.
QList< int > sampleSizeList ()
Returns the list of currently available sample sizes.
QList< int > sampleSizeList ()
Returns the list of currently available sample sizes.
QList< QAudioFormat::SampleType > sampleTypeList ()
Returns the list of currently available sample types.
QList< QAudioFormat::SampleType > sampleTypeList ()
Returns the list of currently available sample types.
QList< QAudioFormat::SampleType > sampleTypeList ()
Returns the list of currently available sample types.
bool testSettings (const QAudioFormat &format) const
bool testSettings (const QAudioFormat &format) const
void updateLists ()
void updateLists ()
~QAudioDeviceInfoInternal ()
~QAudioDeviceInfoInternal ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QList< QByteArray > availableDevices (QAudio::Mode mode)
static QList< QByteArray > availableDevices (QAudio::Mode)
static QList< QByteArray > availableDevices (QAudio::Mode)
static QByteArray defaultInputDevice ()
static QByteArray defaultInputDevice ()
static QByteArray defaultInputDevice ()
static QByteArray defaultOutputDevice ()
static QByteArray defaultOutputDevice ()
static QByteArray defaultOutputDevice ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables
AudioDeviceID deviceId
QString name
Private Functions
void close ()
bool open ()
Properties
QList< QAudioFormat::Endian > byteOrderz
QList< int > channelz
QStringList codecz
QString device
QList< int > freqz
snd_pcm_t * handle
QAudio::Mode mode
QAudioFormat nearest
snd_pcm_hw_params_t * params
QList< int > sizez
QList< QAudioFormat::SampleType > typez
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 74 of file qaudiodeviceinfo_alsa_p.h.
Constructors and Destructors
QAudioDeviceInfoInternal() [1/3]
QAudioDeviceInfoInternal::QAudioDeviceInfoInternal (QByteArray dev, QAudio::Mode mode)
Definition at line 59 of file qaudiodeviceinfo_alsa_p.cpp.
 {
     handle = 0;
     device = QLatin1String(dev);
     this->mode = mode;
 #if (SND_LIB_MAJOR == 1 && SND_LIB_MINOR == 0 && SND_LIB_SUBMINOR >= 14)
     checkSurround();
 #endif
 }
~QAudioDeviceInfoInternal() [1/2]
QAudioDeviceInfoInternal::~QAudioDeviceInfoInternal ()
Definition at line 71 of file qaudiodeviceinfo_alsa_p.cpp.
 {
     close();
 }
QAudioDeviceInfoInternal() [2/3]
QAudioDeviceInfoInternal::QAudioDeviceInfoInternal (QByteArray const & handle, QAudio::Mode mode)
Definition at line 69 of file qaudiodeviceinfo_mac_p.cpp.
 {
     QDataStream ds(handle);
     quint32 did, tm;
     ds >> did >> tm >> name;
     deviceId = AudioDeviceID(did);
     mode = QAudio::Mode(tm);
 }
QAudioDeviceInfoInternal() [3/3]
QAudioDeviceInfoInternal::QAudioDeviceInfoInternal (QByteArray dev, QAudio::Mode mode)
~QAudioDeviceInfoInternal() [2/2]
QAudioDeviceInfoInternal::~QAudioDeviceInfoInternal ()
Functions
availableDevices() [1/3]
static QList<QByteArray> QAudioDeviceInfoInternal::availableDevices (QAudio::Mode mode) static
availableDevices() [2/3]
QList< QByteArray > QAudioDeviceInfoInternal::availableDevices (QAudio::Mode mode) static
Definition at line 416 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by QAudioDeviceFactory::availableDevices(), defaultInputDevice(), defaultOutputDevice(), get_device_info(), open(), QAudioInputPrivate::open(), QAudioOutputPrivate::open(), and testSettings().
 {
     QList<QByteArray> allDevices;
     QList<QByteArray> devices;
     QByteArray filter;
 #if(SND_LIB_MAJOR == 1 && SND_LIB_MINOR == 0 && SND_LIB_SUBMINOR >= 14)
     // Create a list of all current audio devices that support mode
     void **hints, **n;
     char *name, *descr, *io;
     if(snd_device_name_hint(-1, "pcm", &hints) < 0) {
         qWarning() << "no alsa devices available";
         return devices;
     }
     n = hints;
     if(mode == QAudio::AudioInput) {
         filter = "Input";
     } else {
         filter = "Output";
     }
     while (*n != NULL) {
         name = snd_device_name_get_hint(*n, "NAME");
         if (name != 0 && qstrcmp(name, "null") != 0) {
             descr = snd_device_name_get_hint(*n, "DESC");
             io = snd_device_name_get_hint(*n, "IOID");
             if ((descr != NULL) && ((io == NULL) || (io == filter))) {
                 QString deviceName = QLatin1String(name);
                 QString deviceDescription = QLatin1String(descr);
                 allDevices.append(deviceName.toLocal8Bit().constData());
                 if (deviceDescription.contains(QLatin1String("Default Audio Device")))
                     devices.append(deviceName.toLocal8Bit().constData());
             }
             free(name);
             if (descr != NULL)
                 free(descr);
             if (io != NULL)
                 free(io);
         }
         ++n;
     }
     snd_device_name_free_hint(hints);
     if(devices.size() > 0) {
         devices.append("default");
     }
 #else
     int idx = 0;
     char* name;
     while(snd_card_get_name(idx,&name) == 0) {
         devices.append(name);
         idx++;
     }
     if (idx > 0)
         devices.append("default");
 #endif
     if (devices.size() == 0 && allDevices.size() > 0)
         return allDevices;
     return devices;
 }
availableDevices() [3/3]
static QList<QByteArray> QAudioDeviceInfoInternal::availableDevices (QAudio::Mode) static
byteOrderList() [1/3]
QList<QAudioFormat::Endian> QAudioDeviceInfoInternal::byteOrderList () virtual
Returns the list of currently available byte orders.
Implements QAbstractAudioDeviceInfo.
byteOrderList() [2/3]
QList< QAudioFormat::Endian > QAudioDeviceInfoInternal::byteOrderList () virtual
Returns the list of currently available byte orders.
Implements QAbstractAudioDeviceInfo.
Definition at line 143 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by QAudioDeviceInfoInternal().
 {
     updateLists();
     return byteOrderz;
 }
byteOrderList() [3/3]
QList<QAudioFormat::Endian> QAudioDeviceInfoInternal::byteOrderList () virtual
Returns the list of currently available byte orders.
Implements QAbstractAudioDeviceInfo.
channelsList() [1/3]
QList<int> QAudioDeviceInfoInternal::channelsList () virtual
Returns the list of currently available channels.
Implements QAbstractAudioDeviceInfo.
channelsList() [2/3]
QList< int > QAudioDeviceInfoInternal::channelsList () virtual
Returns the list of currently available channels.
Implements QAbstractAudioDeviceInfo.
Definition at line 131 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by QAudioDeviceInfoInternal().
 {
     updateLists();
     return channelz;
 }
channelsList() [3/3]
QList<int> QAudioDeviceInfoInternal::channelsList () virtual
Returns the list of currently available channels.
Implements QAbstractAudioDeviceInfo.
close() [1/2]
void QAudioDeviceInfoInternal::close ()
close() [2/2]
void QAudioDeviceInfoInternal::close () private
Definition at line 196 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by updateLists(), and ~QAudioDeviceInfoInternal().
 {
     if(handle)
         snd_pcm_close(handle);
     handle = 0;
 }
codecList() [1/3]
QStringList QAudioDeviceInfoInternal::codecList () virtual
Returns the list of currently available codecs.
Implements QAbstractAudioDeviceInfo.
codecList() [2/3]
QStringList QAudioDeviceInfoInternal::codecList () virtual
Returns the list of currently available codecs.
Implements QAbstractAudioDeviceInfo.
Definition at line 119 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by QAudioDeviceInfoInternal().
 {
     updateLists();
     return codecz;
 }
codecList() [3/3]
QStringList QAudioDeviceInfoInternal::codecList () virtual
Returns the list of currently available codecs.
Implements QAbstractAudioDeviceInfo.
defaultInputDevice() [1/3]
static QByteArray QAudioDeviceInfoInternal::defaultInputDevice () static
defaultInputDevice() [2/3]
QByteArray QAudioDeviceInfoInternal::defaultInputDevice () static
Definition at line 483 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by QAudioDeviceFactory::defaultInputDevice(), and get_device_info().
 {
     QList<QByteArray> devices = availableDevices(QAudio::AudioInput);
     if(devices.size() == 0)
         return QByteArray();
     return devices.first();
 }
defaultInputDevice() [3/3]
static QByteArray QAudioDeviceInfoInternal::defaultInputDevice () static
defaultOutputDevice() [1/3]
static QByteArray QAudioDeviceInfoInternal::defaultOutputDevice () static
defaultOutputDevice() [2/3]
QByteArray QAudioDeviceInfoInternal::defaultOutputDevice () static
Definition at line 492 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by QAudioDeviceFactory::defaultOutputDevice(), and get_device_info().
 {
     QList<QByteArray> devices = availableDevices(QAudio::AudioOutput);
     if(devices.size() == 0)
         return QByteArray();
     return devices.first();
 }
defaultOutputDevice() [3/3]
static QByteArray QAudioDeviceInfoInternal::defaultOutputDevice () static
deviceName() [1/3]
QString QAudioDeviceInfoInternal::deviceName () const virtual
Returns the audio device name.
Implements QAbstractAudioDeviceInfo.
deviceName() [2/3]
QString QAudioDeviceInfoInternal::deviceName () const virtual
Returns the audio device name.
Implements QAbstractAudioDeviceInfo.
Definition at line 114 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by availableDevices(), defaultOutputDevice(), and QAudioDeviceInfoInternal().
 {
     return device;
 }
deviceName() [3/3]
QString QAudioDeviceInfoInternal::deviceName () const virtual
Returns the audio device name.
Implements QAbstractAudioDeviceInfo.
frequencyList() [1/3]
QList<int> QAudioDeviceInfoInternal::frequencyList () virtual
Returns the list of currently available frequencies.
Implements QAbstractAudioDeviceInfo.
frequencyList() [2/3]
QList< int > QAudioDeviceInfoInternal::frequencyList () virtual
Returns the list of currently available frequencies.
Implements QAbstractAudioDeviceInfo.
Definition at line 125 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by QAudioDeviceInfoInternal().
 {
     updateLists();
     return freqz;
 }
frequencyList() [3/3]
QList<int> QAudioDeviceInfoInternal::frequencyList () virtual
Returns the list of currently available frequencies.
Implements QAbstractAudioDeviceInfo.
isFormatSupported() [1/3]
bool QAudioDeviceInfoInternal::isFormatSupported (const QAudioFormat & format) const virtual
Returns true if format is available from audio device.
Implements QAbstractAudioDeviceInfo.
isFormatSupported() [2/3]
bool QAudioDeviceInfoInternal::isFormatSupported (const QAudioFormat & format) const virtual
Returns true if format is available from audio device.
Implements QAbstractAudioDeviceInfo.
Definition at line 76 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by QAudioDeviceInfoInternal().
 {
     return testSettings(format);
 }
isFormatSupported() [3/3]
bool QAudioDeviceInfoInternal::isFormatSupported (const QAudioFormat & format) const virtual
Returns true if format is available from audio device.
Implements QAbstractAudioDeviceInfo.
nearestFormat() [1/3]
QAudioFormat QAudioDeviceInfoInternal::nearestFormat (const QAudioFormat & format) const virtual
Returns the nearest settings format.
Implements QAbstractAudioDeviceInfo.
nearestFormat() [2/3]
QAudioFormat QAudioDeviceInfoInternal::nearestFormat (const QAudioFormat & format) const virtual
Returns the nearest settings format.
Implements QAbstractAudioDeviceInfo.
Definition at line 106 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by QAudioDeviceInfoInternal().
 {
     if(testSettings(format))
         return format;
     else
         return preferredFormat();
 }
nearestFormat() [3/3]
QAudioFormat QAudioDeviceInfoInternal::nearestFormat (const QAudioFormat & format) const virtual
Returns the nearest settings format.
Implements QAbstractAudioDeviceInfo.
open() [1/2]
bool QAudioDeviceInfoInternal::open ()
open() [2/2]
bool QAudioDeviceInfoInternal::open () private
Definition at line 155 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by updateLists().
 {
     int err = 0;
     QString dev = device;
     QList<QByteArray> devices = availableDevices(mode);
     if(dev.compare(QLatin1String("default")) == 0) {
 #if(SND_LIB_MAJOR == 1 && SND_LIB_MINOR == 0 && SND_LIB_SUBMINOR >= 14)
         dev = QLatin1String(devices.first().constData());
 #else
         dev = QLatin1String("hw:0,0");
 #endif
     } else {
 #if(SND_LIB_MAJOR == 1 && SND_LIB_MINOR == 0 && SND_LIB_SUBMINOR >= 14)
         dev = device;
 #else
         int idx = 0;
         char *name;
         QString shortName = device.mid(device.indexOf(QLatin1String("="),0)+1);
     while(snd_card_get_name(idx,&name) == 0) {
             if(dev.contains(QLatin1String(name)))
                 break;
             idx++;
     }
         dev = QString(QLatin1String("hw:%1,0")).arg(idx);
 #endif
     }
     if(mode == QAudio::AudioOutput) {
         err=snd_pcm_open( &handle,dev.toLocal8Bit().constData(),SND_PCM_STREAM_PLAYBACK,0);
     } else {
         err=snd_pcm_open( &handle,dev.toLocal8Bit().constData(),SND_PCM_STREAM_CAPTURE,0);
     }
     if(err < 0) {
         handle = 0;
         return false;
     }
     return true;
 }
preferredFormat() [1/3]
QAudioFormat QAudioDeviceInfoInternal::preferredFormat () const virtual
Returns the nearest settings.
Implements QAbstractAudioDeviceInfo.
preferredFormat() [2/3]
QAudioFormat QAudioDeviceInfoInternal::preferredFormat () const virtual
Returns the nearest settings.
Implements QAbstractAudioDeviceInfo.
Definition at line 81 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by nearestFormat(), and QAudioDeviceInfoInternal().
 {
     QAudioFormat nearest;
     if(mode == QAudio::AudioOutput) {
         nearest.setFrequency(44100);
         nearest.setChannels(2);
         nearest.setByteOrder(QAudioFormat::LittleEndian);
         nearest.setSampleType(QAudioFormat::SignedInt);
         nearest.setSampleSize(16);
         nearest.setCodec(QLatin1String("audio/pcm"));
     } else {
         nearest.setFrequency(8000);
         nearest.setChannels(1);
         nearest.setSampleType(QAudioFormat::UnSignedInt);
         nearest.setSampleSize(8);
         nearest.setCodec(QLatin1String("audio/pcm"));
         if(!testSettings(nearest)) {
             nearest.setChannels(2);
             nearest.setSampleSize(16);
             nearest.setSampleType(QAudioFormat::SignedInt);
         }
     }
     return nearest;
 }
preferredFormat() [3/3]
QAudioFormat QAudioDeviceInfoInternal::preferredFormat () const virtual
Returns the nearest settings.
Implements QAbstractAudioDeviceInfo.
sampleSizeList() [1/3]
QList<int> QAudioDeviceInfoInternal::sampleSizeList () virtual
Returns the list of currently available sample sizes.
Implements QAbstractAudioDeviceInfo.
sampleSizeList() [2/3]
QList< int > QAudioDeviceInfoInternal::sampleSizeList () virtual
Returns the list of currently available sample sizes.
Implements QAbstractAudioDeviceInfo.
Definition at line 137 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by QAudioDeviceInfoInternal().
 {
     updateLists();
     return sizez;
 }
sampleSizeList() [3/3]
QList<int> QAudioDeviceInfoInternal::sampleSizeList () virtual
Returns the list of currently available sample sizes.
Implements QAbstractAudioDeviceInfo.
sampleTypeList() [1/3]
QList<QAudioFormat::SampleType> QAudioDeviceInfoInternal::sampleTypeList () virtual
Returns the list of currently available sample types.
Implements QAbstractAudioDeviceInfo.
sampleTypeList() [2/3]
QList< QAudioFormat::SampleType > QAudioDeviceInfoInternal::sampleTypeList () virtual
Returns the list of currently available sample types.
Implements QAbstractAudioDeviceInfo.
Definition at line 149 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by QAudioDeviceInfoInternal().
 {
     updateLists();
     return typez;
 }
sampleTypeList() [3/3]
QList<QAudioFormat::SampleType> QAudioDeviceInfoInternal::sampleTypeList () virtual
Returns the list of currently available sample types.
Implements QAbstractAudioDeviceInfo.
testSettings() [1/2]
bool QAudioDeviceInfoInternal::testSettings (const QAudioFormat & format) const
Definition at line 203 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by isFormatSupported(), nearestFormat(), and preferredFormat().
 {
     // Set nearest to closest settings that do work.
     // See if what is in settings will work (return value).
     int err = 0;
     snd_pcm_t* handle;
     snd_pcm_hw_params_t *params;
     QString dev = device;
     QList<QByteArray> devices = QAudioDeviceInfoInternal::availableDevices(QAudio::AudioOutput);
     if(dev.compare(QLatin1String("default")) == 0) {
 #if(SND_LIB_MAJOR == 1 && SND_LIB_MINOR == 0 && SND_LIB_SUBMINOR >= 14)
         dev = QLatin1String(devices.first().constData());
 #else
         dev = QLatin1String("hw:0,0");
 #endif
     } else {
 #if(SND_LIB_MAJOR == 1 && SND_LIB_MINOR == 0 && SND_LIB_SUBMINOR >= 14)
         dev = device;
 #else
         int idx = 0;
         char *name;
         QString shortName = device.mid(device.indexOf(QLatin1String("="),0)+1);
         while(snd_card_get_name(idx,&name) == 0) {
             if(shortName.compare(QLatin1String(name)) == 0)
                 break;
             idx++;
         }
         dev = QString(QLatin1String("hw:%1,0")).arg(idx);
 #endif
     }
     if(mode == QAudio::AudioOutput) {
         err=snd_pcm_open( &handle,dev.toLocal8Bit().constData(),SND_PCM_STREAM_PLAYBACK,0);
     } else {
         err=snd_pcm_open( &handle,dev.toLocal8Bit().constData(),SND_PCM_STREAM_CAPTURE,0);
     }
     if(err < 0) {
         handle = 0;
         return false;
     }
     bool testChannel = false;
     bool testCodec = false;
     bool testFreq = false;
     bool testType = false;
     bool testSize = false;
     int  dir = 0;
     snd_pcm_nonblock( handle, 0 );
     snd_pcm_hw_params_alloca( &params );
     snd_pcm_hw_params_any( handle, params );
     // set the values!
     snd_pcm_hw_params_set_channels(handle,params,format.channels());
     snd_pcm_hw_params_set_rate(handle,params,format.frequency(),dir);
     err = -1;
     switch(format.sampleSize()) {
         case 8:
             if(format.sampleType() == QAudioFormat::SignedInt)
                 err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_S8);
             else if(format.sampleType() == QAudioFormat::UnSignedInt)
                 err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_U8);
             break;
         case 16:
             if(format.sampleType() == QAudioFormat::SignedInt) {
                 if(format.byteOrder() == QAudioFormat::LittleEndian)
                     err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_S16_LE);
                 else if(format.byteOrder() == QAudioFormat::BigEndian)
                     err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_S16_BE);
             } else if(format.sampleType() == QAudioFormat::UnSignedInt) {
                 if(format.byteOrder() == QAudioFormat::LittleEndian)
                     err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_U16_LE);
                 else if(format.byteOrder() == QAudioFormat::BigEndian)
                     err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_U16_BE);
             }
             break;
         case 32:
             if(format.sampleType() == QAudioFormat::SignedInt) {
                 if(format.byteOrder() == QAudioFormat::LittleEndian)
                     err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_S32_LE);
                 else if(format.byteOrder() == QAudioFormat::BigEndian)
                     err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_S32_BE);
             } else if(format.sampleType() == QAudioFormat::UnSignedInt) {
                 if(format.byteOrder() == QAudioFormat::LittleEndian)
                     err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_U32_LE);
                 else if(format.byteOrder() == QAudioFormat::BigEndian)
                     err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_U32_BE);
             }
     }
     // For now, just accept only audio/pcm codec
     if(!format.codec().startsWith(QLatin1String("audio/pcm"))) {
         err=-1;
     } else
         testCodec = true;
     if(err>=0 && format.channels() != -1) {
         err = snd_pcm_hw_params_test_channels(handle,params,format.channels());
         if(err>=0)
             err = snd_pcm_hw_params_set_channels(handle,params,format.channels());
         if(err>=0)
             testChannel = true;
     }
     if(err>=0 && format.frequency() != -1) {
         err = snd_pcm_hw_params_test_rate(handle,params,format.frequency(),0);
         if(err>=0)
             err = snd_pcm_hw_params_set_rate(handle,params,format.frequency(),dir);
         if(err>=0)
             testFreq = true;
     }
     if((err>=0 && format.sampleSize() != -1) &&
             (format.sampleType() != QAudioFormat::Unknown)) {
         switch(format.sampleSize()) {
             case 8:
                 if(format.sampleType() == QAudioFormat::SignedInt)
                     err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_S8);
                 else if(format.sampleType() == QAudioFormat::UnSignedInt)
                     err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_U8);
                 break;
             case 16:
                 if(format.sampleType() == QAudioFormat::SignedInt) {
                     if(format.byteOrder() == QAudioFormat::LittleEndian)
                         err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_S16_LE);
                     else if(format.byteOrder() == QAudioFormat::BigEndian)
                         err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_S16_BE);
                 } else if(format.sampleType() == QAudioFormat::UnSignedInt) {
                     if(format.byteOrder() == QAudioFormat::LittleEndian)
                         err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_U16_LE);
                     else if(format.byteOrder() == QAudioFormat::BigEndian)
                         err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_U16_BE);
                 }
                 break;
             case 32:
                 if(format.sampleType() == QAudioFormat::SignedInt) {
                     if(format.byteOrder() == QAudioFormat::LittleEndian)
                         err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_S32_LE);
                     else if(format.byteOrder() == QAudioFormat::BigEndian)
                         err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_S32_BE);
                 } else if(format.sampleType() == QAudioFormat::UnSignedInt) {
                     if(format.byteOrder() == QAudioFormat::LittleEndian)
                         err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_U32_LE);
                     else if(format.byteOrder() == QAudioFormat::BigEndian)
                         err = snd_pcm_hw_params_set_format(handle,params,SND_PCM_FORMAT_U32_BE);
                 }
         }
         if(err>=0) {
             testSize = true;
             testType = true;
         }
     }
     if(err>=0)
         err = snd_pcm_hw_params(handle, params);
     if(err == 0) {
         // settings work
         // close()
         if(handle)
             snd_pcm_close(handle);
         return true;
     }
     if(handle)
         snd_pcm_close(handle);
     return false;
 }
testSettings() [2/2]
bool QAudioDeviceInfoInternal::testSettings (const QAudioFormat & format) const
updateLists() [1/2]
void QAudioDeviceInfoInternal::updateLists ()
Definition at line 377 of file qaudiodeviceinfo_alsa_p.cpp.
Referenced by byteOrderList(), channelsList(), codecList(), frequencyList(), sampleSizeList(), and sampleTypeList().
 {
     // redo all lists based on current settings
     freqz.clear();
     channelz.clear();
     sizez.clear();
     byteOrderz.clear();
     typez.clear();
     codecz.clear();
     if(!handle)
         open();
     if(!handle)
         return;
     for(int i=0; i<(int)MAX_SAMPLE_RATES; i++) {
         //if(snd_pcm_hw_params_test_rate(handle, params, SAMPLE_RATES[i], dir) == 0)
         freqz.append(SAMPLE_RATES[i]);
     }
     channelz.append(1);
     channelz.append(2);
 #if (SND_LIB_MAJOR == 1 && SND_LIB_MINOR == 0 && SND_LIB_SUBMINOR >= 14)
     if (surround40) channelz.append(4);
     if (surround51) channelz.append(6);
     if (surround71) channelz.append(8);
 #endif
     sizez.append(8);
     sizez.append(16);
     sizez.append(32);
     byteOrderz.append(QAudioFormat::LittleEndian);
     byteOrderz.append(QAudioFormat::BigEndian);
     typez.append(QAudioFormat::SignedInt);
     typez.append(QAudioFormat::UnSignedInt);
     typez.append(QAudioFormat::Float);
     codecz.append(QLatin1String("audio/pcm"));
     close();
 }
updateLists() [2/2]
void QAudioDeviceInfoInternal::updateLists ()
Properties
byteOrderz
QList< QAudioFormat::Endian > QAudioDeviceInfoInternal::byteOrderz private
Definition at line 114 of file qaudiodeviceinfo_alsa_p.h.
Referenced by byteOrderList(), and updateLists().
channelz
QList< int > QAudioDeviceInfoInternal::channelz private
Definition at line 112 of file qaudiodeviceinfo_alsa_p.h.
Referenced by channelsList(), and updateLists().
codecz
QStringList QAudioDeviceInfoInternal::codecz private
Definition at line 115 of file qaudiodeviceinfo_alsa_p.h.
Referenced by codecList(), and updateLists().
device
QString QAudioDeviceInfoInternal::device private
Definition at line 108 of file qaudiodeviceinfo_alsa_p.h.
Referenced by deviceName(), get_device_info(), open(), QAudioDeviceInfoInternal(), and testSettings().
deviceId
AudioDeviceID QAudioDeviceInfoInternal::deviceId
Definition at line 68 of file qaudiodeviceinfo_mac_p.h.
Referenced by QAudioDeviceInfoInternal().
freqz
QList< int > QAudioDeviceInfoInternal::freqz private
Definition at line 111 of file qaudiodeviceinfo_alsa_p.h.
Referenced by frequencyList(), and updateLists().
handle
snd_pcm_t* QAudioDeviceInfoInternal::handle private
Definition at line 117 of file qaudiodeviceinfo_alsa_p.h.
Referenced by close(), open(), QAudioDeviceInfoInternal(), testSettings(), and updateLists().
mode
QAudio::Mode QAudioDeviceInfoInternal::mode private
Definition at line 109 of file qaudiodeviceinfo_alsa_p.h.
Referenced by defaultOutputDevice(), get_device_info(), open(), preferredFormat(), QAudioDeviceInfoInternal(), and testSettings().
name
QString QAudioDeviceInfoInternal::name
Definition at line 69 of file qaudiodeviceinfo_mac_p.h.
Referenced by availableDevices(), defaultOutputDevice(), get_device_info(), open(), QAudioDeviceInfoInternal(), and testSettings().
nearest
QAudioFormat QAudioDeviceInfoInternal::nearest private
Definition at line 110 of file qaudiodeviceinfo_alsa_p.h.
Referenced by preferredFormat().
params
snd_pcm_hw_params_t* QAudioDeviceInfoInternal::params private
Definition at line 118 of file qaudiodeviceinfo_alsa_p.h.
Referenced by testSettings().
sizez
QList< int > QAudioDeviceInfoInternal::sizez private
Definition at line 113 of file qaudiodeviceinfo_alsa_p.h.
Referenced by sampleSizeList(), and updateLists().
typez
QList< QAudioFormat::SampleType > QAudioDeviceInfoInternal::typez private
Definition at line 116 of file qaudiodeviceinfo_alsa_p.h.
Referenced by sampleTypeList(), and updateLists().
The documentation for this class was generated from the following files:
/src/multimedia/audio/qaudiodeviceinfo_alsa_p.h
/src/multimedia/audio/qaudiodeviceinfo_mac_p.h
/src/multimedia/audio/qaudiodeviceinfo_win32_p.h
/src/multimedia/audio/qaudiodeviceinfo_alsa_p.cpp
/src/multimedia/audio/qaudiodeviceinfo_mac_p.cpp
/src/multimedia/audio/qaudiodeviceinfo_win32_p.cpp