Qt 4.8: QDeclarativeTextEdit Class Reference
QDeclarativeTextEdit Class Reference
#include <qdeclarativetextedit_p.h>
Public Types
enum HAlignment { AlignLeft = Qt::AlignLeft, AlignRight = Qt::AlignRight, AlignHCenter = Qt::AlignHCenter, AlignJustify = Qt::AlignJustify }
enum SelectionMode { SelectCharacters, SelectWords }
enum TextFormat { PlainText = Qt::PlainText, RichText = Qt::RichText, AutoText = Qt::AutoText }
enum VAlignment { AlignTop = Qt::AlignTop, AlignBottom = Qt::AlignBottom, AlignVCenter = Qt::AlignVCenter }
enum WrapMode {
NoWrap = QTextOption::NoWrap, WordWrap = QTextOption::WordWrap, WrapAnywhere = QTextOption::WrapAnywhere, WrapAtWordBoundaryOrAnywhere = QTextOption::WrapAtWordBoundaryOrAnywhere,
Wrap = QTextOption::WrapAtWordBoundaryOrAnywhere
}
Public Types inherited from QDeclarativeItem
enum TransformOrigin {
TopLeft, Top, TopRight, Left,
Center, Right, BottomLeft, Bottom,
BottomRight
}
Controls the point about which simple transforms like scale apply.
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Public Slots
void copy ()
void cut ()
void deselect ()
bool isRightToLeft (int start, int end)
void paste ()
void select (int start, int end)
void selectAll ()
void selectWord ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void activeFocusOnPressChanged (bool activeFocusOnPressed)
void canPasteChanged ()
void colorChanged (const QColor &color)
void cursorDelegateChanged ()
void cursorPositionChanged ()
void cursorRectangleChanged ()
void cursorVisibleChanged (bool isCursorVisible)
void fontChanged (const QFont &font)
void horizontalAlignmentChanged (HAlignment alignment)
void inputMethodComposingChanged ()
void lineCountChanged ()
void linkActivated (const QString &link)
void mouseSelectionModeChanged (SelectionMode mode)
void paintedSizeChanged ()
void persistentSelectionChanged (bool isPersistentSelection)
void readOnlyChanged (bool isReadOnly)
void selectByMouseChanged (bool selectByMouse)
void selectedTextColorChanged (const QColor &color)
void selectionChanged ()
void selectionColorChanged (const QColor &color)
void selectionEndChanged ()
void selectionStartChanged ()
void textChanged (const QString &)
void textFormatChanged (TextFormat textFormat)
void textMarginChanged (qreal textMargin)
void verticalAlignmentChanged (VAlignment alignment)
void wrapModeChanged ()
Signals inherited from QDeclarativeImplicitSizePaintedItem
void implicitHeightChanged ()
void implicitWidthChanged ()
Signals inherited from QDeclarativePaintedItem
void contentsScaleChanged ()
void contentsSizeChanged ()
void fillColorChanged ()
Signals inherited from QDeclarativeItem
void activeFocusChanged (bool)
void baselineOffsetChanged (qreal)
void childrenRectChanged (const QRectF &)
void clipChanged (bool)
void focusChanged (bool)
void implicitHeightChanged ()
void implicitWidthChanged ()
void parentChanged (QDeclarativeItem *)
void smoothChanged (bool)
void stateChanged (const QString &)
void transformOriginChanged (TransformOrigin)
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QRectF boundingRect () const
bool canPaste () const
Q_INVOKABLE void closeSoftwareInputPanel ()
QColor color () const
virtual void componentComplete ()
Ensures any delayed caching or data loading the class needs to performed is complete.
QDeclarativeComponent * cursorDelegate () const
int cursorPosition () const
QRect cursorRectangle () const
HAlignment effectiveHAlign () const
bool focusOnPress () const
QFont font () const
HAlignment hAlign () const
QVariant inputMethodQuery (Qt::InputMethodQuery property) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Returns the value of the given property.
bool isCursorVisible () const
bool isInputMethodComposing () const
bool isReadOnly () const
int lineCount () const
SelectionMode mouseSelectionMode () const
Q_INVOKABLE void moveCursorSelection (int pos)
Q_INVOKABLE void moveCursorSelection (int pos, SelectionMode mode)
Q_INVOKABLE void openSoftwareInputPanel ()
qreal paintedHeight () const
qreal paintedWidth () const
bool persistentSelection () const
Q_INVOKABLE int positionAt (int x, int y) const
Q_INVOKABLE QRectF positionToRectangle (int) const
QDeclarativeTextEdit (QDeclarativeItem *parent=0)
This handler is called when the user clicks on a link embedded in the text.
void resetHAlign ()
bool selectByMouse () const
QString selectedText () const
QColor selectedTextColor () const
QColor selectionColor () const
int selectionEnd () const
int selectionStart () const
void setColor (const QColor &c)
void setCursorDelegate (QDeclarativeComponent *)
void setCursorPosition (int pos)
void setCursorVisible (bool on)
void setFocusOnPress (bool on)
void setFont (const QFont &font)
void setHAlign (HAlignment align)
void setMouseSelectionMode (SelectionMode mode)
void setPersistentSelection (bool on)
void setReadOnly (bool)
void setSelectByMouse (bool)
void setSelectedTextColor (const QColor &c)
void setSelectionColor (const QColor &c)
void setText (const QString &)
void setTextFormat (TextFormat format)
void setTextInteractionFlags (Qt::TextInteractionFlags flags)
Sets how the text edit should interact with user input to the given flags.
void setTextMargin (qreal margin)
void setVAlign (VAlignment align)
void setWrapMode (WrapMode w)
QString text () const
TextFormat textFormat () const
Qt::TextInteractionFlags textInteractionFlags () const
Returns the flags specifying how the text edit should interact with user input.
qreal textMargin () const
VAlignment vAlign () const
WrapMode wrapMode () const
Public Functions inherited from QDeclarativeImplicitSizePaintedItem
QDeclarativeImplicitSizePaintedItem (QDeclarativeItem *parent=0)
Public Functions inherited from QDeclarativePaintedItem
qreal contentsScale () const
QSize contentsSize () const
QColor fillColor () const
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
int pixelCacheSize () const
QDeclarativePaintedItem (QDeclarativeItem *parent=0)
Constructs a new QDeclarativePaintedItem with the given parent.
void setContentsScale (qreal)
void setContentsSize (const QSize &)
Sets the size of the contents to the given size.
void setFillColor (const QColor &)
void setPixelCacheSize (int pixels)
void setSmoothCache (bool on)
bool smoothCache () const
~QDeclarativePaintedItem ()
Destroys the image item.
Public Functions inherited from QDeclarativeItem
qreal baselineOffset () const
Q_INVOKABLE QDeclarativeItem * childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
QRectF childrenRect ()
bool clip () const
Q_INVOKABLE void forceActiveFocus ()
Forces active focus on the item.
bool hasActiveFocus () const
bool hasFocus () const
qreal height () const
qreal implicitHeight () const
qreal implicitWidth () const
bool keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
Q_INVOKABLE QScriptValue mapFromItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
Q_INVOKABLE QScriptValue mapToItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
QDeclarativeItem * parentItem () const
Returns the QDeclarativeItem parent of this item.
QDeclarativeItem (QDeclarativeItem *parent=0)
Constructs a QDeclarativeItem with the given parent.
void resetHeight ()
void resetWidth ()
void setBaselineOffset (qreal)
void setClip (bool)
void setFocus (bool)
void setHeight (qreal)
void setKeepMouseGrab (bool)
The flag indicating whether the mouse should remain with this item is set to keep.
void setParentItem (QDeclarativeItem *parent)
void setSize (const QSizeF &size)
void setSmooth (bool)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
void setTransformOrigin (TransformOrigin)
Set the transform origin.
void setWidth (qreal)
bool smooth () const
QDeclarativeListProperty< QGraphicsTransform > transform ()
TransformOrigin transformOrigin () const
qreal width () const
virtual ~QDeclarativeItem ()
Destroys the QDeclarativeItem.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
void drawContents (QPainter *, const QRect &)
Draws the contents of the text edit using the given painter within the given bounds.
bool event (QEvent *)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given event.
void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
void inputMethodEvent (QInputMethodEvent *e)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given input method event.
void keyPressEvent (QKeyEvent *)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given key event.
void keyReleaseEvent (QKeyEvent *)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given key event.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
void mousePressEvent (QGraphicsSceneMouseEvent *event)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
Protected Functions inherited from QDeclarativeImplicitSizePaintedItem
QDeclarativeImplicitSizePaintedItem (QDeclarativeImplicitSizePaintedItemPrivate &dd, QDeclarativeItem *parent)
Protected Functions inherited from QDeclarativePaintedItem
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
QDeclarativePaintedItem (QDeclarativePaintedItemPrivate &dd, QDeclarativeItem *parent)
Constructs a new QDeclarativePaintedItem with the given parent and initialized private data member dd.
void setCacheFrozen (bool)
Protected Functions inherited from QDeclarativeItem
virtual void classBegin ()
bool heightValid () const
Returns whether the height property has been set explicitly.
void inputMethodPreHandler (QInputMethodEvent *)
bool isComponentComplete () const
Returns true if construction of the QML component is complete; otherwise returns false.
void keyPressPreHandler (QKeyEvent *)
void keyReleasePreHandler (QKeyEvent *)
QDeclarativeItem (QDeclarativeItemPrivate &dd, QDeclarativeItem *parent=0)
virtual bool sceneEvent (QEvent *)
void setImplicitHeight (qreal)
Sets the implied height of the item to h.
void setImplicitWidth (qreal)
Sets the implied width of the item to w.
bool widthValid () const
Returns whether the width property has been set explicitly.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
Filters events for the item watched.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
Private Slots
void loadCursorDelegate ()
void moveCursorDelegate ()
void q_canPasteChanged ()
void q_textChanged ()
void updateImgCache (const QRectF &rect)
void updateSelectionMarkers ()
Private Functions
void updateSize ()
void updateTotalLines ()
Properties
bool activeFocusOnPress
bool canPaste
QColor color
QDeclarativeComponent * cursorDelegate
int cursorPosition
QRect cursorRectangle
bool cursorVisible
QFont font
HAlignment horizontalAlignment
bool inputMethodComposing
Qt::InputMethodHints inputMethodHints
int lineCount
SelectionMode mouseSelectionMode
qreal paintedHeight
qreal paintedWidth
bool persistentSelection
bool readOnly
bool selectByMouse
QString selectedText
QColor selectedTextColor
QColor selectionColor
int selectionEnd
int selectionStart
QString text
TextFormat textFormat
qreal textMargin
VAlignment verticalAlignment
WrapMode wrapMode
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Slots inherited from QDeclarativePaintedItem
void clearCache ()
Marks the entirety of the contents cache as dirty.
void dirtyCache (const QRect &)
Marks areas of the cache that intersect with the given rect as dirty and in need of being refreshed.
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
Definition at line 61 of file qdeclarativetextedit_p.h.
Enumerations
HAlignment
enum QDeclarativeTextEdit::HAlignment
Enumerator
AlignLeft
AlignRight
AlignHCenter
AlignJustify
Definition at line 102 of file qdeclarativetextedit_p.h.
                     {
         AlignLeft = Qt::AlignLeft,
         AlignRight = Qt::AlignRight,
         AlignHCenter = Qt::AlignHCenter,
         AlignJustify = Qt::AlignJustify // ### VERSIONING: Only in QtQuick 1.1
     };
SelectionMode
enum QDeclarativeTextEdit::SelectionMode
Enumerator
SelectCharacters
SelectWords
Definition at line 128 of file qdeclarativetextedit_p.h.
{
         SelectCharacters,
         SelectWords
     };
TextFormat
enum QDeclarativeTextEdit::TextFormat
Enumerator
PlainText
RichText
AutoText
Definition at line 115 of file qdeclarativetextedit_p.h.
                     {
         PlainText = Qt::PlainText,
         RichText = Qt::RichText,
         AutoText = Qt::AutoText
     };
VAlignment
enum QDeclarativeTextEdit::VAlignment
Enumerator
AlignTop
AlignBottom
AlignVCenter
Definition at line 109 of file qdeclarativetextedit_p.h.
                     {
         AlignTop = Qt::AlignTop,
         AlignBottom = Qt::AlignBottom,
         AlignVCenter = Qt::AlignVCenter
     };
WrapMode
enum QDeclarativeTextEdit::WrapMode
Enumerator
NoWrap
WordWrap
WrapAnywhere
WrapAtWordBoundaryOrAnywhere
Wrap
Definition at line 121 of file qdeclarativetextedit_p.h.
                   { NoWrap = QTextOption::NoWrap,
                     WordWrap = QTextOption::WordWrap,
                     WrapAnywhere = QTextOption::WrapAnywhere,
                     WrapAtWordBoundaryOrAnywhere = QTextOption::WrapAtWordBoundaryOrAnywhere, // COMPAT
                     Wrap = QTextOption::WrapAtWordBoundaryOrAnywhere
                   };
Constructors and Destructors
QDeclarativeTextEdit()
QDeclarativeTextEdit::QDeclarativeTextEdit (QDeclarativeItem * parent = 0)
This handler is called when the user clicks on a link embedded in the text.
TextEdit::onLinkActivated(string link)
Since
QtQuick 1.1
The link must be in rich text or HTML format and the link string provides access to the particular link.
Definition at line 122 of file qdeclarativetextedit.cpp.
 : QDeclarativeImplicitSizePaintedItem(*(new QDeclarativeTextEditPrivate), parent)
 {
     Q_D(QDeclarativeTextEdit);
     d->init();
 }
Functions
activeFocusOnPressChanged
void QDeclarativeTextEdit::activeFocusOnPressChanged (bool activeFocusOnPressed) signal
Referenced by setFocusOnPress().
boundingRect()
QRectF QDeclarativeTextEdit::boundingRect () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativePaintedItem.
Definition at line 1777 of file qdeclarativetextedit.cpp.
Referenced by mouseReleaseEvent().
 {
     Q_D(const QDeclarativeTextEdit);
     QRectF r = QDeclarativePaintedItem::boundingRect();
     int cursorWidth = 1;
     if(d->cursor)
         cursorWidth = d->cursor->width();
     if(!d->document->isEmpty())
         cursorWidth += 3;// ### Need a better way of accounting for space between char and cursor
     // Could include font max left/right bearings to either side of rectangle.
     r.setRight(r.right() + cursorWidth);
     return r.translated(0,d->yoff);
 }
canPaste()
bool QDeclarativeTextEdit::canPaste () const
Referenced by QDeclarativeTextEditPrivate::init(), and updateImgCache().
canPasteChanged
void QDeclarativeTextEdit::canPasteChanged () signal
Referenced by q_canPasteChanged().
closeSoftwareInputPanel()
void QDeclarativeTextEdit::closeSoftwareInputPanel ()
Definition at line 2014 of file qdeclarativetextedit.cpp.
 {
     QEvent event(QEvent::CloseSoftwareInputPanel);
     if (qApp) {
         if (QGraphicsView * view = qobject_cast<QGraphicsView*>(qApp->focusWidget())) {
             if (view->scene() && view->scene() == scene()) {
                 QApplication::sendEvent(view, &event);
             }
         }
     }
 }
color()
QColor QDeclarativeTextEdit::color () const
Referenced by QDeclarativeTextEditPrivate::init(), setColor(), setFont(), setSelectedTextColor(), and setSelectionColor().
colorChanged
void QDeclarativeTextEdit::colorChanged (const QColor & color) signal
Referenced by setColor().
componentComplete()
void QDeclarativeTextEdit::componentComplete () virtual
Ensures any delayed caching or data loading the class needs to performed is complete.
Reimplemented from QDeclarativeItem.
Definition at line 1140 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     QDeclarativePaintedItem::componentComplete();
     if (d->dirty) {
         d->determineHorizontalAlignment();
         d->updateDefaultTextOption();
         updateSize();
         d->dirty = false;
     }
 }
copy
void QDeclarativeTextEdit::copy () slot
Definition at line 1463 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     d->control->copy();
 }
cursorDelegate()
QDeclarativeComponent* QDeclarativeTextEdit::cursorDelegate () const
Referenced by setCursorPosition().
cursorDelegateChanged
void QDeclarativeTextEdit::cursorDelegateChanged () signal
Referenced by setCursorDelegate().
cursorPosition()
int QDeclarativeTextEdit::cursorPosition () const
Referenced by setCursorVisible().
cursorPositionChanged
void QDeclarativeTextEdit::cursorPositionChanged () signal
Referenced by QDeclarativeTextEditPrivate::init().
cursorRectangle()
QRect QDeclarativeTextEdit::cursorRectangle () const
Referenced by loadCursorDelegate(), moveCursorDelegate(), setCursorDelegate(), and textInteractionFlags().
cursorRectangleChanged
void QDeclarativeTextEdit::cursorRectangleChanged () signal
Referenced by moveCursorDelegate().
cursorVisibleChanged
void QDeclarativeTextEdit::cursorVisibleChanged (bool isCursorVisible) signal
Referenced by setCursorVisible().
cut
void QDeclarativeTextEdit::cut () slot
Definition at line 1449 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     d->control->cut();
 }
deselect
void QDeclarativeTextEdit::deselect () slot
Definition at line 1350 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     QTextCursor c = d->control->textCursor();
     c.clearSelection();
     d->control->setTextCursor(c);
 }
drawContents()
void QDeclarativeTextEdit::drawContents (QPainter * painter, const QRect & bounds) protected virtual
Draws the contents of the text edit using the given painter within the given bounds.
Reimplemented from QDeclarativeImplicitSizePaintedItem.
Definition at line 1587 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     painter->setRenderHint(QPainter::TextAntialiasing, true);
     painter->translate(0,d->yoff);
     d->control->drawContents(painter, bounds.translated(0,-d->yoff));
     painter->translate(0,-d->yoff);
 }
effectiveHAlign()
QDeclarativeTextEdit::HAlignment QDeclarativeTextEdit::effectiveHAlign () const
Definition at line 570 of file qdeclarativetextedit.cpp.
 {
     Q_D(const QDeclarativeTextEdit);
     QDeclarativeTextEdit::HAlignment effectiveAlignment = d->hAlign;
     if (!d->hAlignImplicit && d->effectiveLayoutMirror) {
         switch (d->hAlign) {
         case QDeclarativeTextEdit::AlignLeft:
             effectiveAlignment = QDeclarativeTextEdit::AlignRight;
             break;
         case QDeclarativeTextEdit::AlignRight:
             effectiveAlignment = QDeclarativeTextEdit::AlignLeft;
             break;
         default:
             break;
         }
     }
     return effectiveAlignment;
 }
event()
bool QDeclarativeTextEdit::event (QEvent * event) protected virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given event.
Reimplemented from QDeclarativeItem.
Definition at line 1296 of file qdeclarativetextedit.cpp.
Referenced by closeSoftwareInputPanel(), and openSoftwareInputPanel().
 {
     Q_D(QDeclarativeTextEdit);
     if (event->type() == QEvent::ShortcutOverride) {
         d->control->processEvent(event, QPointF(0, -d->yoff));
         return event->isAccepted();
     }
     return QDeclarativePaintedItem::event(event);
 }
focusInEvent()
void QDeclarativeTextEdit::focusInEvent (QFocusEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive focus in events for this item.
The default implementation calls ensureVisible().
See also
focusOutEvent(), sceneEvent(), setFocus()
Reimplemented from QGraphicsItem.
Definition at line 2026 of file qdeclarativetextedit.cpp.
 {
     Q_D(const QDeclarativeTextEdit);
     if (d->showInputPanelOnFocus) {
         if (d->focusOnPress && !isReadOnly()) {
             openSoftwareInputPanel();
         }
     }
     QDeclarativePaintedItem::focusInEvent(event);
 }
focusOnPress()
bool QDeclarativeTextEdit::focusOnPress () const
Definition at line 1068 of file qdeclarativetextedit.cpp.
 {
     Q_D(const QDeclarativeTextEdit);
     return d->focusOnPress;
 }
font()
QFont QDeclarativeTextEdit::font () const
Referenced by QDeclarativeTextEditPrivate::init(), setFont(), and setTextFormat().
fontChanged
void QDeclarativeTextEdit::fontChanged (const QFont & font) signal
Referenced by setFont().
geometryChanged()
void QDeclarativeTextEdit::geometryChanged (const QRectF & newGeometry, const QRectF & oldGeometry) protected virtual
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
If the two geometries are the same, it doesn't do anything.
Reimplemented from QDeclarativePaintedItem.
Definition at line 1128 of file qdeclarativetextedit.cpp.
 {
     if (newGeometry.width() != oldGeometry.width())
         updateSize();
     QDeclarativePaintedItem::geometryChanged(newGeometry, oldGeometry);
 }
hAlign()
QDeclarativeTextEdit::HAlignment QDeclarativeTextEdit::hAlign () const
Definition at line 543 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate::mirrorChange(), and QDeclarativeTextEditPrivate::setHAlign().
 {
     Q_D(const QDeclarativeTextEdit);
     return d->hAlign;
 }
horizontalAlignmentChanged
void QDeclarativeTextEdit::horizontalAlignmentChanged (HAlignment alignment) signal
inputMethodComposingChanged
void QDeclarativeTextEdit::inputMethodComposingChanged () signal
Referenced by inputMethodEvent().
inputMethodEvent()
void QDeclarativeTextEdit::inputMethodEvent (QInputMethodEvent * e) protected virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given input method event.
Reimplemented from QDeclarativeItem.
Definition at line 1564 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     const bool wasComposing = isInputMethodComposing();
     d->control->processEvent(event, QPointF(0, -d->yoff));
     if (wasComposing != isInputMethodComposing())
         emit inputMethodComposingChanged();
 }
inputMethodQuery()
QVariant QDeclarativeTextEdit::inputMethodQuery (Qt::InputMethodQuery property) const virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Returns the value of the given property.
Reimplemented from QDeclarativeItem.
Definition at line 1577 of file qdeclarativetextedit.cpp.
 {
     Q_D(const QDeclarativeTextEdit);
     return d->control->inputMethodQuery(property);
 }
isCursorVisible()
bool QDeclarativeTextEdit::isCursorVisible () const
Definition at line 891 of file qdeclarativetextedit.cpp.
 {
     Q_D(const QDeclarativeTextEdit);
     return d->cursorVisible;
 }
isInputMethodComposing()
bool QDeclarativeTextEdit::isInputMethodComposing () const
Definition at line 1668 of file qdeclarativetextedit.cpp.
Referenced by inputMethodEvent().
 {
     Q_D(const QDeclarativeTextEdit);
     if (QTextLayout *layout = d->control->textCursor().block().layout())
         return layout->preeditAreaText().length() > 0;
     return false;
 }
isReadOnly()
bool QDeclarativeTextEdit::isReadOnly () const
Definition at line 1250 of file qdeclarativetextedit.cpp.
Referenced by focusInEvent(), mousePressEvent(), mouseReleaseEvent(), and setReadOnly().
 {
     Q_D(const QDeclarativeTextEdit);
     return !(d->control->textInteractionFlags() & Qt::TextEditable);
 }
isRightToLeft
bool QDeclarativeTextEdit::isRightToLeft (int start, int end) slot
Definition at line 1429 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (start > end) {
         qmlInfo(this) << "isRightToLeft(start, end) called with the end property being smaller than the start.";
         return false;
     } else {
         return d->text.mid(start, end - start).isRightToLeft();
     }
 }
keyPressEvent()
void QDeclarativeTextEdit::keyPressEvent (QKeyEvent * event) protected virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given key event.
Reimplemented from QDeclarativeItem.
Definition at line 1310 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     keyPressPreHandler(event);
     if (!event->isAccepted())
         d->control->processEvent(event, QPointF(0, -d->yoff));
     if (!event->isAccepted())
         QDeclarativePaintedItem::keyPressEvent(event);
 }
keyReleaseEvent()
void QDeclarativeTextEdit::keyReleaseEvent (QKeyEvent * event) protected virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given key event.
Reimplemented from QDeclarativeItem.
Definition at line 1324 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     keyReleasePreHandler(event);
     if (!event->isAccepted())
         d->control->processEvent(event, QPointF(0, -d->yoff));
     if (!event->isAccepted())
         QDeclarativePaintedItem::keyReleaseEvent(event);
 }
lineCount()
int QDeclarativeTextEdit::lineCount () const
Referenced by setWrapMode().
lineCountChanged
void QDeclarativeTextEdit::lineCountChanged () signal
Referenced by updateTotalLines().
linkActivated
void QDeclarativeTextEdit::linkActivated (const QString & link) signal
Referenced by QDeclarativeTextEditPrivate::init().
loadCursorDelegate
void QDeclarativeTextEdit::loadCursorDelegate () private slot
Definition at line 980 of file qdeclarativetextedit.cpp.
Referenced by setCursorDelegate().
 {
     Q_D(QDeclarativeTextEdit);
     if(d->cursorComponent->isLoading())
         return;
     d->cursor = qobject_cast<QDeclarativeItem*>(d->cursorComponent->create(qmlContext(this)));
     if(d->cursor){
         d->control->setCursorWidth(0);
         dirtyCache(cursorRectangle());
         QDeclarative_setParent_noEvent(d->cursor, this);
         d->cursor->setParentItem(this);
         d->cursor->setHeight(QFontMetrics(d->font).height());
         moveCursorDelegate();
     }else{
         qmlInfo(this) << "Error loading cursor delegate.";
     }
 }
mouseDoubleClickEvent()
void QDeclarativeTextEdit::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
Reimplemented from QGraphicsItem.
Definition at line 1538 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     d->control->processEvent(event, QPointF(0, -d->yoff));
     if (!event->isAccepted())
         QDeclarativePaintedItem::mouseDoubleClickEvent(event);
 }
mouseMoveEvent()
void QDeclarativeTextEdit::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
Reimplemented from QGraphicsItem.
Definition at line 1552 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     d->control->processEvent(event, QPointF(0, -d->yoff));
     if (!event->isAccepted())
         QDeclarativePaintedItem::mouseMoveEvent(event);
 }
mousePressEvent()
void QDeclarativeTextEdit::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
Reimplemented from QGraphicsItem.
Definition at line 1488 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (d->focusOnPress){
         bool hadActiveFocus = hasActiveFocus();
         forceActiveFocus();
         if (d->showInputPanelOnFocus) {
             if (hasActiveFocus() && hadActiveFocus && !isReadOnly()) {
                 // re-open input panel on press if already focused
                 openSoftwareInputPanel();
             }
         } else { // show input panel on click
             if (hasActiveFocus() && !hadActiveFocus) {
                 d->clickCausedFocus = true;
             }
         }
     }
     d->control->processEvent(event, QPointF(0, -d->yoff));
     if (!event->isAccepted())
         QDeclarativePaintedItem::mousePressEvent(event);
 }
mouseReleaseEvent()
void QDeclarativeTextEdit::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
Reimplemented from QGraphicsItem.
Definition at line 1515 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     d->control->processEvent(event, QPointF(0, -d->yoff));
     if (!d->showInputPanelOnFocus) { // input panel on click
         if (d->focusOnPress && !isReadOnly() && boundingRect().contains(event->pos())) {
             if (QGraphicsView * view = qobject_cast<QGraphicsView*>(qApp->focusWidget())) {
                 if (view->scene() && view->scene() == scene()) {
                     qt_widget_private(view)->handleSoftwareInputPanel(event->button(), d->clickCausedFocus);
                 }
             }
         }
     }
     d->clickCausedFocus = false;
     if (!event->isAccepted())
         QDeclarativePaintedItem::mouseReleaseEvent(event);
 }
mouseSelectionMode()
SelectionMode QDeclarativeTextEdit::mouseSelectionMode () const
Referenced by setSelectByMouse().
mouseSelectionModeChanged
void QDeclarativeTextEdit::mouseSelectionModeChanged (SelectionMode mode) signal
Referenced by setMouseSelectionMode().
moveCursorDelegate
void QDeclarativeTextEdit::moveCursorDelegate () private slot
Definition at line 1734 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate::init(), loadCursorDelegate(), setFont(), and setVAlign().
 {
     Q_D(QDeclarativeTextEdit);
     d->determineHorizontalAlignment();
     updateMicroFocus();
     emit cursorRectangleChanged();
     if(!d->cursor)
         return;
     QRectF cursorRect = cursorRectangle();
     d->cursor->setX(cursorRect.x());
     d->cursor->setY(cursorRect.y());
 }
moveCursorSelection() [1/2]
void QDeclarativeTextEdit::moveCursorSelection (int pos)
Definition at line 780 of file qdeclarativetextedit.cpp.
 {
     //Note that this is the same as setCursorPosition but with the KeepAnchor flag set
     Q_D(QDeclarativeTextEdit);
     QTextCursor cursor = d->control->textCursor();
     if (cursor.position() == pos)
         return;
     cursor.setPosition(pos, QTextCursor::KeepAnchor);
     d->control->setTextCursor(cursor);
 }
moveCursorSelection() [2/2]
void QDeclarativeTextEdit::moveCursorSelection (int pos, SelectionMode mode)
Definition at line 832 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     QTextCursor cursor = d->control->textCursor();
     if (cursor.position() == pos)
         return;
     if (mode == SelectCharacters) {
         cursor.setPosition(pos, QTextCursor::KeepAnchor);
     } else if (cursor.anchor() < pos || (cursor.anchor() == pos && cursor.position() < pos)) {
         if (cursor.anchor() > cursor.position()) {
             cursor.setPosition(cursor.anchor(), QTextCursor::MoveAnchor);
             cursor.movePosition(QTextCursor::StartOfWord, QTextCursor::KeepAnchor);
             if (cursor.position() == cursor.anchor())
                 cursor.movePosition(QTextCursor::PreviousWord, QTextCursor::MoveAnchor);
             else
                 cursor.setPosition(cursor.position(), QTextCursor::MoveAnchor);
         } else {
             cursor.setPosition(cursor.anchor(), QTextCursor::MoveAnchor);
             cursor.movePosition(QTextCursor::StartOfWord, QTextCursor::MoveAnchor);
         }
         cursor.setPosition(pos, QTextCursor::KeepAnchor);
         cursor.movePosition(QTextCursor::StartOfWord, QTextCursor::KeepAnchor);
         if (cursor.position() != pos)
             cursor.movePosition(QTextCursor::EndOfWord, QTextCursor::KeepAnchor);
     } else if (cursor.anchor() > pos || (cursor.anchor() == pos && cursor.position() > pos)) {
         if (cursor.anchor() < cursor.position()) {
             cursor.setPosition(cursor.anchor(), QTextCursor::MoveAnchor);
             cursor.movePosition(QTextCursor::EndOfWord, QTextCursor::MoveAnchor);
         } else {
             cursor.setPosition(cursor.anchor(), QTextCursor::MoveAnchor);
             cursor.movePosition(QTextCursor::PreviousCharacter, QTextCursor::KeepAnchor);
             cursor.movePosition(QTextCursor::EndOfWord, QTextCursor::KeepAnchor);
             if (cursor.position() != cursor.anchor()) {
                 cursor.setPosition(cursor.anchor(), QTextCursor::MoveAnchor);
                 cursor.movePosition(QTextCursor::EndOfWord, QTextCursor::MoveAnchor);
             }
         }
         cursor.setPosition(pos, QTextCursor::KeepAnchor);
         cursor.movePosition(QTextCursor::EndOfWord, QTextCursor::KeepAnchor);
         if (cursor.position() != pos) {
             cursor.movePosition(QTextCursor::PreviousCharacter, QTextCursor::KeepAnchor);
             cursor.movePosition(QTextCursor::StartOfWord, QTextCursor::KeepAnchor);
         }
     }
     d->control->setTextCursor(cursor);
 }
openSoftwareInputPanel()
void QDeclarativeTextEdit::openSoftwareInputPanel ()
Definition at line 1960 of file qdeclarativetextedit.cpp.
Referenced by focusInEvent(), and mousePressEvent().
 {
     QEvent event(QEvent::RequestSoftwareInputPanel);
     if (qApp) {
         if (QGraphicsView * view = qobject_cast<QGraphicsView*>(qApp->focusWidget())) {
             if (view->scene() && view->scene() == scene()) {
                 QApplication::sendEvent(view, &event);
             }
         }
     }
 }
paintedHeight()
qreal QDeclarativeTextEdit::paintedHeight () const
Referenced by setWrapMode().
paintedSizeChanged
void QDeclarativeTextEdit::paintedSizeChanged () signal
Referenced by updateSize().
paintedWidth()
qreal QDeclarativeTextEdit::paintedWidth () const
Referenced by setWrapMode().
paste
void QDeclarativeTextEdit::paste () slot
Definition at line 1477 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     d->control->paste();
 }
persistentSelection()
bool QDeclarativeTextEdit::persistentSelection () const
Referenced by setFocusOnPress().
persistentSelectionChanged
void QDeclarativeTextEdit::persistentSelectionChanged (bool isPersistentSelection) signal
Referenced by setPersistentSelection().
positionAt()
int QDeclarativeTextEdit::positionAt (int x, int y) const
Definition at line 757 of file qdeclarativetextedit.cpp.
 {
     Q_D(const QDeclarativeTextEdit);
     int r = d->document->documentLayout()->hitTest(QPoint(x,y-d->yoff), Qt::FuzzyHit);
     QTextCursor cursor = d->control->textCursor();
     if (r > cursor.position()) {
         // The cursor position includes positions within the preedit text, but only positions in the
         // same text block are offset so it is possible to get a position that is either part of the
         // preedit or the next text block.
         QTextLayout *layout = cursor.block().layout();
         const int preeditLength = layout
                 ? layout->preeditAreaText().length()
                 : 0;
         if (preeditLength > 0
                 && d->document->documentLayout()->blockBoundingRect(cursor.block()).contains(x,y-d->yoff)) {
             r = r > cursor.position() + preeditLength
                     ? r - preeditLength
                     : cursor.position();
         }
     }
     return r;
 }
positionToRectangle()
QRectF QDeclarativeTextEdit::positionToRectangle (int pos) const
Definition at line 737 of file qdeclarativetextedit.cpp.
 {
     Q_D(const QDeclarativeTextEdit);
     QTextCursor c(d->document);
     c.setPosition(pos);
     return d->control->cursorRect(c);
 }
q_canPasteChanged
void QDeclarativeTextEdit::q_canPasteChanged () private slot
Definition at line 2037 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate::init().
 {
     Q_D(QDeclarativeTextEdit);
     bool old = d->canPaste;
     d->canPaste = d->control->canPaste();
     if(old!=d->canPaste)
         emit canPasteChanged();
 }
q_textChanged
void QDeclarativeTextEdit::q_textChanged () private slot
Definition at line 1722 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate::init(), and setText().
 {
     Q_D(QDeclarativeTextEdit);
     d->text = text();
     d->rightToLeftText = d->document->begin().layout()->engine()->isRightToLeft();
     d->determineHorizontalAlignment();
     d->updateDefaultTextOption();
     updateSize();
     updateTotalLines();
     emit textChanged(d->text);
 }
readOnlyChanged
void QDeclarativeTextEdit::readOnlyChanged (bool isReadOnly) signal
Referenced by QDeclarativeTextEditPrivate::init(), and setReadOnly().
resetHAlign()
void QDeclarativeTextEdit::resetHAlign ()
Definition at line 560 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     d->hAlignImplicit = true;
     if (d->determineHorizontalAlignment() && isComponentComplete()) {
         d->updateDefaultTextOption();
         updateSize();
     }
 }
select
void QDeclarativeTextEdit::select (int start, int end) slot
Definition at line 1404 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (start < 0 || end < 0 || start > d->text.length() || end > d->text.length())
         return;
     QTextCursor cursor = d->control->textCursor();
     cursor.beginEditBlock();
     cursor.setPosition(start, QTextCursor::MoveAnchor);
     cursor.setPosition(end, QTextCursor::KeepAnchor);
     cursor.endEditBlock();
     d->control->setTextCursor(cursor);
     // QTBUG-11100
     updateSelectionMarkers();
 }
selectAll
void QDeclarativeTextEdit::selectAll () slot
Definition at line 1366 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     d->control->selectAll();
 }
selectByMouse()
bool QDeclarativeTextEdit::selectByMouse () const
Referenced by componentComplete().
selectByMouseChanged
void QDeclarativeTextEdit::selectByMouseChanged (bool selectByMouse) signal
Referenced by setSelectByMouse().
selectedText()
QString QDeclarativeTextEdit::selectedText () const
Referenced by loadCursorDelegate().
selectedTextColor()
QColor QDeclarativeTextEdit::selectedTextColor () const
Referenced by setSelectionColor().
selectedTextColorChanged
void QDeclarativeTextEdit::selectedTextColorChanged (const QColor & color) signal
Referenced by setSelectedTextColor().
selectionChanged
void QDeclarativeTextEdit::selectionChanged () signal
Referenced by QDeclarativeTextEditPrivate::init().
selectionColor()
QColor QDeclarativeTextEdit::selectionColor () const
Referenced by setColor().
selectionColorChanged
void QDeclarativeTextEdit::selectionColorChanged (const QColor & color) signal
Referenced by setSelectionColor().
selectionEnd()
int QDeclarativeTextEdit::selectionEnd () const
Referenced by loadCursorDelegate().
selectionEndChanged
void QDeclarativeTextEdit::selectionEndChanged () signal
Referenced by updateSelectionMarkers().
selectionStart()
int QDeclarativeTextEdit::selectionStart () const
Referenced by loadCursorDelegate().
selectionStartChanged
void QDeclarativeTextEdit::selectionStartChanged () signal
Referenced by updateSelectionMarkers().
selectWord
void QDeclarativeTextEdit::selectWord () slot
Definition at line 1380 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     QTextCursor c = d->control->textCursor();
     c.select(QTextCursor::WordUnderCursor);
     d->control->setTextCursor(c);
 }
setColor()
void QDeclarativeTextEdit::setColor (const QColor & c)
Definition at line 438 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (d->color == color)
         return;
     clearCache();
     d->color = color;
     QPalette pal = d->control->palette();
     pal.setColor(QPalette::Text, color);
     d->control->setPalette(pal);
     update();
     emit colorChanged(d->color);
 }
setCursorDelegate()
void QDeclarativeTextEdit::setCursorDelegate (QDeclarativeComponent * c)
Definition at line 957 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if(d->cursorComponent){
         if(d->cursor){
             d->control->setCursorWidth(-1);
             dirtyCache(cursorRectangle());
             delete d->cursor;
             d->cursor = 0;
         }
     }
     d->cursorComponent = c;
     if(c && c->isReady()){
         loadCursorDelegate();
     }else{
         if(c)
             connect(c, SIGNAL(statusChanged()),
                     this, SLOT(loadCursorDelegate()));
     }
     emit cursorDelegateChanged();
 }
setCursorPosition()
void QDeclarativeTextEdit::setCursorPosition (int pos)
Definition at line 923 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (pos < 0 || pos > d->text.length())
         return;
     QTextCursor cursor = d->control->textCursor();
     if (cursor.position() == pos && cursor.anchor() == pos)
         return;
     cursor.setPosition(pos);
     d->control->setTextCursor(cursor);
 }
setCursorVisible()
void QDeclarativeTextEdit::setCursorVisible (bool on)
Definition at line 897 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (d->cursorVisible == on)
         return;
     d->cursorVisible = on;
     QFocusEvent focusEvent(on ? QEvent::FocusIn : QEvent::FocusOut);
     if (!on && !d->persistentSelection)
         d->control->setCursorIsFocusIndicator(true);
     d->control->processEvent(&focusEvent, QPointF(0, -d->yoff));
     emit cursorVisibleChanged(d->cursorVisible);
 }
setFocusOnPress()
void QDeclarativeTextEdit::setFocusOnPress (bool on)
Definition at line 1074 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (d->focusOnPress == on)
         return;
     d->focusOnPress = on;
     emit activeFocusOnPressChanged(d->focusOnPress);
 }
setFont()
void QDeclarativeTextEdit::setFont (const QFont & font)
Definition at line 386 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (d->sourceFont == font)
         return;
     d->sourceFont = font;
     QFont oldFont = d->font;
     d->font = font;
     if (d->font.pointSizeF() != -1) {
         // 0.5pt resolution
         qreal size = qRound(d->font.pointSizeF()*2.0);
         d->font.setPointSizeF(size/2.0);
     }
     if (oldFont != d->font) {
         clearCache();
         d->document->setDefaultFont(d->font);
         if(d->cursor){
             d->cursor->setHeight(QFontMetrics(d->font).height());
             moveCursorDelegate();
         }
         updateSize();
         update();
     }
     emit fontChanged(d->sourceFont);
 }
setHAlign()
void QDeclarativeTextEdit::setHAlign (HAlignment align)
Definition at line 549 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate::determineHorizontalAlignment().
 {
     Q_D(QDeclarativeTextEdit);
     bool forceAlign = d->hAlignImplicit && d->effectiveLayoutMirror;
     d->hAlignImplicit = false;
     if (d->setHAlign(align, forceAlign) && isComponentComplete()) {
         d->updateDefaultTextOption();
         updateSize();
     }
 }
setMouseSelectionMode()
void QDeclarativeTextEdit::setMouseSelectionMode (SelectionMode mode)
Definition at line 1209 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (d->mouseSelectionMode != mode) {
         d->mouseSelectionMode = mode;
         d->control->setWordSelectionEnabled(mode == SelectWords);
         emit mouseSelectionModeChanged(mode);
     }
 }
setPersistentSelection()
void QDeclarativeTextEdit::setPersistentSelection (bool on)
Definition at line 1098 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (d->persistentSelection == on)
         return;
     d->persistentSelection = on;
     emit persistentSelectionChanged(d->persistentSelection);
 }
setReadOnly()
void QDeclarativeTextEdit::setReadOnly (bool r)
Definition at line 1230 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (r == isReadOnly())
         return;
     setFlag(QGraphicsItem::ItemAcceptsInputMethod, !r);
     Qt::TextInteractionFlags flags = Qt::LinksAccessibleByMouse;
     if (d->selectByMouse)
         flags = flags | Qt::TextSelectableByMouse;
     if (!r)
         flags = flags | Qt::TextSelectableByKeyboard | Qt::TextEditable;
     d->control->setTextInteractionFlags(flags);
     if (!r)
         d->control->moveCursor(QTextCursor::End);
     emit readOnlyChanged(r);
 }
setSelectByMouse()
void QDeclarativeTextEdit::setSelectByMouse (bool on)
Definition at line 1171 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (d->selectByMouse != on) {
         d->selectByMouse = on;
         setKeepMouseGrab(on);
         if (on)
             setTextInteractionFlags(d->control->textInteractionFlags() | Qt::TextSelectableByMouse);
         else
             setTextInteractionFlags(d->control->textInteractionFlags() & ~Qt::TextSelectableByMouse);
         emit selectByMouseChanged(on);
     }
 }
setSelectedTextColor()
void QDeclarativeTextEdit::setSelectedTextColor (const QColor & c)
Definition at line 496 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (d->selectedTextColor == color)
         return;
     clearCache();
     d->selectedTextColor = color;
     QPalette pal = d->control->palette();
     pal.setColor(QPalette::HighlightedText, color);
     d->control->setPalette(pal);
     update();
     emit selectedTextColorChanged(d->selectedTextColor);
 }
setSelectionColor()
void QDeclarativeTextEdit::setSelectionColor (const QColor & c)
Definition at line 467 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (d->selectionColor == color)
         return;
     clearCache();
     d->selectionColor = color;
     QPalette pal = d->control->palette();
     pal.setColor(QPalette::Highlight, color);
     d->control->setPalette(pal);
     update();
     emit selectionColorChanged(d->selectionColor);
 }
setText()
void QDeclarativeTextEdit::setText (const QString & text)
Definition at line 290 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (QDeclarativeTextEdit::text() == text)
         return;
     d->richText = d->format == RichText || (d->format == AutoText && Qt::mightBeRichText(text));
     if (d->richText) {
 #ifndef QT_NO_TEXTHTMLPARSER
         d->control->setHtml(text);
 #else
         d->control->setPlainText(text);
 #endif
     } else {
         d->control->setPlainText(text);
     }
     q_textChanged();
 }
setTextFormat()
void QDeclarativeTextEdit::setTextFormat (TextFormat format)
Definition at line 356 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (format == d->format)
         return;
     bool wasRich = d->richText;
     d->richText = format == RichText || (format == AutoText && Qt::mightBeRichText(d->text));
     if (wasRich && !d->richText) {
         d->control->setPlainText(d->text);
         updateSize();
     } else if (!wasRich && d->richText) {
 #ifndef QT_NO_TEXTHTMLPARSER
         d->control->setHtml(d->text);
 #else
         d->control->setPlainText(d->text);
 #endif
         updateSize();
     }
     d->format = format;
     d->control->setAcceptRichText(d->format != PlainText);
     emit textFormatChanged(d->format);
 }
setTextInteractionFlags()
void QDeclarativeTextEdit::setTextInteractionFlags (Qt::TextInteractionFlags flags)
Sets how the text edit should interact with user input to the given flags.
Definition at line 1260 of file qdeclarativetextedit.cpp.
Referenced by setSelectByMouse().
 {
     Q_D(QDeclarativeTextEdit);
     d->control->setTextInteractionFlags(flags);
 }
setTextMargin()
void QDeclarativeTextEdit::setTextMargin (qreal margin)
Definition at line 1118 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (d->textMargin == margin)
         return;
     d->textMargin = margin;
     d->document->setDocumentMargin(d->textMargin);
     emit textMarginChanged(d->textMargin);
 }
setVAlign()
void QDeclarativeTextEdit::setVAlign (QDeclarativeTextEdit::VAlignment alignment)
Definition at line 635 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (alignment == d->vAlign)
         return;
     d->vAlign = alignment;
     d->updateDefaultTextOption();
     updateSize();
     moveCursorDelegate();
     emit verticalAlignmentChanged(d->vAlign);
 }
setWrapMode()
void QDeclarativeTextEdit::setWrapMode (WrapMode w)
Definition at line 671 of file qdeclarativetextedit.cpp.
 {
     Q_D(QDeclarativeTextEdit);
     if (mode == d->wrapMode)
         return;
     d->wrapMode = mode;
     d->updateDefaultTextOption();
     updateSize();
     emit wrapModeChanged();
 }
text()
QString QDeclarativeTextEdit::text () const
Referenced by QDeclarativeTextEditPrivate::determineHorizontalAlignment(), q_textChanged(), QDeclarativeTextEdit(), and setText().
textChanged
void QDeclarativeTextEdit::textChanged (const QString &) signal
Referenced by QDeclarativeTextEditPrivate::init(), and q_textChanged().
textFormat()
TextFormat QDeclarativeTextEdit::textFormat () const
Referenced by setText().
textFormatChanged
void QDeclarativeTextEdit::textFormatChanged (TextFormat textFormat) signal
Referenced by setTextFormat().
textInteractionFlags()
Qt::TextInteractionFlags QDeclarativeTextEdit::textInteractionFlags () const
Returns the flags specifying how the text edit should interact with user input.
Definition at line 1270 of file qdeclarativetextedit.cpp.
 {
     Q_D(const QDeclarativeTextEdit);
     return d->control->textInteractionFlags();
 }
textMargin()
qreal QDeclarativeTextEdit::textMargin () const
Referenced by QDeclarativeTextEditPrivate::init(), and setPersistentSelection().
textMarginChanged
void QDeclarativeTextEdit::textMarginChanged (qreal textMargin) signal
Referenced by setTextMargin().
updateImgCache
void QDeclarativeTextEdit::updateImgCache (const QRectF & rect) private slot
Definition at line 1599 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate::init().
 {
     Q_D(const QDeclarativeTextEdit);
     QRect r;
     if (!rf.isValid()) {
         r = QRect(0,0,INT_MAX,INT_MAX);
     } else {
         r = rf.toRect();
         if (r.height() > INT_MAX/2) {
             // Take care of overflow when translating "everything"
             r.setTop(r.y() + d->yoff);
             r.setBottom(INT_MAX/2);
         } else {
             r = r.translated(0,d->yoff);
         }
     }
     dirtyCache(r);
     emit update();
 }
updateSelectionMarkers
void QDeclarativeTextEdit::updateSelectionMarkers () private slot
Definition at line 1764 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate::init(), and select().
 {
     Q_D(QDeclarativeTextEdit);
     if(d->lastSelectionStart != d->control->textCursor().selectionStart()){
         d->lastSelectionStart = d->control->textCursor().selectionStart();
         emit selectionStartChanged();
     }
     if(d->lastSelectionEnd != d->control->textCursor().selectionEnd()){
         d->lastSelectionEnd = d->control->textCursor().selectionEnd();
         emit selectionEndChanged();
     }
 }
updateSize()
void QDeclarativeTextEdit::updateSize () private
Definition at line 1807 of file qdeclarativetextedit.cpp.
Referenced by componentComplete(), geometryChanged(), QDeclarativeTextEditPrivate::implicitWidth(), q_textChanged(), resetHAlign(), setFont(), setHAlign(), setTextFormat(), setVAlign(), and setWrapMode().
 {
     Q_D(QDeclarativeTextEdit);
     if (isComponentComplete()) {
         qreal naturalWidth = d->mImplicitWidth;
         // ### assumes that if the width is set, the text will fill to edges
         // ### (unless wrap is false, then clipping will occur)
         if (widthValid()) {
             if (!d->requireImplicitWidth) {
                 emit implicitWidthChanged();
                 // if the implicitWidth is used, then updateSize() has already been called (recursively)
                 if (d->requireImplicitWidth)
                     return;
             }
             if (d->requireImplicitWidth) {
                 d->document->setTextWidth(-1);
                 naturalWidth = d->document->idealWidth();
             }
             if (d->document->textWidth() != width())
                 d->document->setTextWidth(width());
         } else {
             d->document->setTextWidth(-1);
         }
         QFontMetrics fm = QFontMetrics(d->font);
         int dy = height();
         dy -= (int)d->document->size().height();
         int nyoff;
         if (heightValid()) {
             if (d->vAlign == AlignBottom)
                 nyoff = dy;
             else if (d->vAlign == AlignVCenter)
                 nyoff = dy/2;
             else
                 nyoff = 0;
         } else {
             nyoff = 0;
         }
         if (nyoff != d->yoff) {
             prepareGeometryChange();
             d->yoff = nyoff;
         }
         setBaselineOffset(fm.ascent() + d->yoff + d->textMargin);
         //### need to comfirm cost of always setting these
         int newWidth = qCeil(d->document->idealWidth());
         if (!widthValid() && d->document->textWidth() != newWidth)
             d->document->setTextWidth(newWidth); // ### Text does not align if width is not set (QTextDoc bug)
         // ### Setting the implicitWidth triggers another updateSize(), and unless there are bindings nothing has changed.
         if (!widthValid())
             setImplicitWidth(newWidth);
         else if (d->requireImplicitWidth)
             setImplicitWidth(naturalWidth);
         qreal newHeight = d->document->size().height();
         if (newHeight == 0)
             newHeight = fm.height();
         setImplicitHeight(newHeight);
         d->paintedSize = QSize(newWidth, newHeight);
         setContentsSize(d->paintedSize);
         emit paintedSizeChanged();
     } else {
         d->dirty = true;
     }
     emit update();
 }
updateTotalLines()
void QDeclarativeTextEdit::updateTotalLines () private
Definition at line 1874 of file qdeclarativetextedit.cpp.
Referenced by q_textChanged().
 {
     Q_D(QDeclarativeTextEdit);
     int subLines = 0;
     for (QTextBlock it = d->document->begin(); it != d->document->end(); it = it.next()) {
         QTextLayout *layout = it.layout();
         if (!layout)
             continue;
         subLines += layout->lineCount()-1;
     }
     int newTotalLines = d->document->lineCount() + subLines;
     if (d->lineCount != newTotalLines) {
         d->lineCount = newTotalLines;
         emit lineCountChanged();
     }
 }
vAlign()
QDeclarativeTextEdit::VAlignment QDeclarativeTextEdit::vAlign () const
Definition at line 629 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate::updateDefaultTextOption().
 {
     Q_D(const QDeclarativeTextEdit);
     return d->vAlign;
 }
verticalAlignmentChanged
void QDeclarativeTextEdit::verticalAlignmentChanged (VAlignment alignment) signal
Referenced by setVAlign().
wrapMode()
WrapMode QDeclarativeTextEdit::wrapMode () const
Referenced by setVAlign(), and QDeclarativeTextEditPrivate::updateDefaultTextOption().
wrapModeChanged
void QDeclarativeTextEdit::wrapModeChanged () signal
Referenced by setWrapMode().
Properties
activeFocusOnPress
bool QDeclarativeTextEdit::activeFocusOnPress private
Definition at line 90 of file qdeclarativetextedit_p.h.
canPaste
bool QDeclarativeTextEdit::canPaste private
Definition at line 96 of file qdeclarativetextedit_p.h.
color
QColor QDeclarativeTextEdit::color private
Definition at line 71 of file qdeclarativetextedit_p.h.
cursorDelegate
QDeclarativeComponent * QDeclarativeTextEdit::cursorDelegate private
Definition at line 86 of file qdeclarativetextedit_p.h.
cursorPosition
int QDeclarativeTextEdit::cursorPosition private
Definition at line 84 of file qdeclarativetextedit_p.h.
cursorRectangle
QRect QDeclarativeTextEdit::cursorRectangle private
Definition at line 85 of file qdeclarativetextedit_p.h.
cursorVisible
bool QDeclarativeTextEdit::cursorVisible private
Definition at line 83 of file qdeclarativetextedit_p.h.
font
QFont QDeclarativeTextEdit::font private
Definition at line 74 of file qdeclarativetextedit_p.h.
horizontalAlignment
HAlignment QDeclarativeTextEdit::horizontalAlignment private
Definition at line 75 of file qdeclarativetextedit_p.h.
Referenced by QDeclarativeTextEditPrivate::updateDefaultTextOption().
inputMethodComposing
bool QDeclarativeTextEdit::inputMethodComposing private
Definition at line 97 of file qdeclarativetextedit_p.h.
inputMethodHints
Qt::InputMethodHints QDeclarativeTextEdit::inputMethodHints private
Definition at line 93 of file qdeclarativetextedit_p.h.
lineCount
int QDeclarativeTextEdit::lineCount private
Definition at line 78 of file qdeclarativetextedit_p.h.
mouseSelectionMode
QDeclarativeTextEdit::SelectionMode QDeclarativeTextEdit::mouseSelectionMode private
Definition at line 95 of file qdeclarativetextedit_p.h.
paintedHeight
qreal QDeclarativeTextEdit::paintedHeight private
Definition at line 80 of file qdeclarativetextedit_p.h.
paintedWidth
qreal QDeclarativeTextEdit::paintedWidth private
Definition at line 79 of file qdeclarativetextedit_p.h.
persistentSelection
bool QDeclarativeTextEdit::persistentSelection private
Definition at line 91 of file qdeclarativetextedit_p.h.
readOnly
bool QDeclarativeTextEdit::readOnly private
Definition at line 82 of file qdeclarativetextedit_p.h.
selectByMouse
bool QDeclarativeTextEdit::selectByMouse private
Definition at line 94 of file qdeclarativetextedit_p.h.
selectedText
QString QDeclarativeTextEdit::selectedText private
Definition at line 89 of file qdeclarativetextedit_p.h.
selectedTextColor
QColor QDeclarativeTextEdit::selectedTextColor private
Definition at line 73 of file qdeclarativetextedit_p.h.
selectionColor
QColor QDeclarativeTextEdit::selectionColor private
Definition at line 72 of file qdeclarativetextedit_p.h.
selectionEnd
int QDeclarativeTextEdit::selectionEnd private
Definition at line 88 of file qdeclarativetextedit_p.h.
selectionStart
int QDeclarativeTextEdit::selectionStart private
Definition at line 87 of file qdeclarativetextedit_p.h.
text
QString QDeclarativeTextEdit::text private
Definition at line 70 of file qdeclarativetextedit_p.h.
textFormat
QDeclarativeTextEdit::TextFormat QDeclarativeTextEdit::textFormat private
Definition at line 81 of file qdeclarativetextedit_p.h.
textMargin
qreal QDeclarativeTextEdit::textMargin private
Definition at line 92 of file qdeclarativetextedit_p.h.
verticalAlignment
VAlignment QDeclarativeTextEdit::verticalAlignment private
Definition at line 76 of file qdeclarativetextedit_p.h.
wrapMode
QDeclarativeTextEdit::WrapMode QDeclarativeTextEdit::wrapMode private
Definition at line 77 of file qdeclarativetextedit_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativetextedit_p.h
/src/declarative/graphicsitems/qdeclarativetextedit.cpp