Qt 4.8: QGLMaskGenerator Class Reference
QGLMaskGenerator Class Reference abstract
Public Functions
virtual void drawMask (const QRect &rect)=0
QTransform matrix () const
QPainterPath path () const
QGLMaskGenerator (const QPainterPath &path, const QTransform &matrix, qreal stroke_width=-1)
virtual QRect screenRect ()=0
qreal strokeWidth () const
virtual ~QGLMaskGenerator ()
Properties
QTransform m
QPainterPath p
qreal w
Detailed Description
Definition at line 2608 of file qpaintengine_opengl.cpp.
Constructors and Destructors
QGLMaskGenerator()
QGLMaskGenerator::QGLMaskGenerator (const QPainterPath & path, const QTransform & matrix, qreal stroke_width = -1) inline
Definition at line 2611 of file qpaintengine_opengl.cpp.
         : p(path),
           m(matrix),
           w(stroke_width)
     {
     }
~QGLMaskGenerator()
virtual QGLMaskGenerator::~QGLMaskGenerator () inline virtual
Definition at line 2625 of file qpaintengine_opengl.cpp.
 {}
Functions
drawMask()
virtual void QGLMaskGenerator::drawMask (const QRect & rect) pure virtual
Implemented in QGLEllipseMaskGenerator, and QGLTrapezoidMaskGenerator.
Referenced by QGLMaskTextureCache::createMask().
matrix()
QTransform QGLMaskGenerator::matrix () const inline
Definition at line 2622 of file qpaintengine_opengl.cpp.
Referenced by QGLPathMaskGenerator::computeScreenRect(), QGLLineMaskGenerator::computeScreenRect(), QGLRectMaskGenerator::computeScreenRect(), QGLEllipseMaskGenerator::drawMask(), QOpenGLPaintEnginePrivate::flushDrawQueue(), QGLRectMaskGenerator::generateTrapezoids(), QGLMaskTextureCache::getMask(), QGLEllipseMaskGenerator::screenRect(), and QOpenGLPaintEnginePrivate::strokePath().
 { return m; }
path()
QPainterPath QGLMaskGenerator::path () const inline
Definition at line 2621 of file qpaintengine_opengl.cpp.
Referenced by QGLPathMaskGenerator::computeScreenRect(), QGLLineMaskGenerator::computeScreenRect(), QGLRectMaskGenerator::computeScreenRect(), QOpenGLPaintEngine::drawEllipse(), QOpenGLPaintEnginePrivate::drawFastRect(), QOpenGLPaintEngine::drawLines(), QOpenGLPaintEngine::drawPolygon(), QOpenGLPaintEngine::drawRects(), ellipseRectToPath(), QGLPathMaskGenerator::generateTrapezoids(), and QGLMaskTextureCache::getMask().
 { return p; }
screenRect()
virtual QRect QGLMaskGenerator::screenRect () pure virtual
Implemented in QGLEllipseMaskGenerator, and QGLTrapezoidMaskGenerator.
Referenced by QGLMaskTextureCache::createMask().
strokeWidth()
qreal QGLMaskGenerator::strokeWidth () const inline
Definition at line 2623 of file qpaintengine_opengl.cpp.
Referenced by QGLLineMaskGenerator::generateTrapezoids(), and QGLMaskTextureCache::getMask().
 { return w; }
Properties
m
QTransform QGLMaskGenerator::m private
Definition at line 2629 of file qpaintengine_opengl.cpp.
Referenced by QGLEllipseMaskGenerator::drawMask().
p
QPainterPath QGLMaskGenerator::p private
Definition at line 2628 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEngine::clip(), QOpenGLPaintEnginePrivate::drawImageAsPath(), QOpenGLPaintEngine::drawLines(), QOpenGLPaintEngine::drawPixmap(), QOpenGLPaintEngine::drawPolygon(), QOpenGLPaintEnginePrivate::drawTiledImageAsPath(), QOpenGLPaintEngine::drawTiledPixmap(), QOpenGLPaintEngine::fill(), and QGLEllipseMaskGenerator::screenRect().
w
qreal QGLMaskGenerator::w private
Definition at line 2630 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEngine::drawRects().
The documentation for this class was generated from the following file:
/src/opengl/qpaintengine_opengl.cpp