Qt 4.8: QAudioRingBuffer Class Reference
QAudioRingBuffer Class Reference
#include <qaudio_mac_p.h>
Public Types
typedef QPair< char *, int > Region
Public Functions
Region acquireReadRegion (int size)
Region acquireWriteRegion (int size)
int free () const
QAudioRingBuffer (int bufferSize)
void releaseReadRegion (Region const &region)
void releaseWriteRegion (Region const &region)
void reset ()
int size () const
int used () const
~QAudioRingBuffer ()
Properties
char * m_buffer
int m_bufferSize
QAtomicInt m_bufferUsed
int m_readPos
int m_writePos
Detailed Description
Definition at line 76 of file qaudio_mac_p.h.
Typedefs
Region
typedef QPair<char*, int> QAudioRingBuffer::Region
Definition at line 79 of file qaudio_mac_p.h.
Constructors and Destructors
QAudioRingBuffer()
QAudioRingBuffer::QAudioRingBuffer (int bufferSize)
Definition at line 109 of file qaudio_mac.cpp.
                                                 :
     m_bufferSize(bufferSize)
 {
     m_buffer = new char[m_bufferSize];
     reset();
 }
~QAudioRingBuffer()
QAudioRingBuffer::~QAudioRingBuffer ()
Definition at line 116 of file qaudio_mac.cpp.
 {
     delete m_buffer;
 }
Functions
acquireReadRegion()
Region QAudioRingBuffer::acquireReadRegion (int size) inline
Definition at line 84 of file qaudio_mac_p.h.
Referenced by QtMultimediaInternal::QAudioOutputBuffer::readFrames().
     {
         const int used = m_bufferUsed.fetchAndAddAcquire(0);
         if (used > 0) {
             const int readSize = qMin(size, qMin(m_bufferSize - m_readPos, used));
             return readSize > 0 ? Region(m_buffer + m_readPos, readSize) : Region(0, 0);
         }
         return Region(0, 0);
     }
acquireWriteRegion()
Region QAudioRingBuffer::acquireWriteRegion (int size) inline
Definition at line 104 of file qaudio_mac_p.h.
Referenced by QtMultimediaInternal::QAudioOutputBuffer::fillBuffer(), and QtMultimediaInternal::QAudioOutputBuffer::writeBytes().
     {
         const int free = m_bufferSize - m_bufferUsed.fetchAndAddAcquire(0);
         if (free > 0) {
             const int writeSize = qMin(size, qMin(m_bufferSize - m_writePos, free));
             return writeSize > 0 ? Region(m_buffer + m_writePos, writeSize) : Region(0, 0);
         }
         return Region(0, 0);
     }
free()
int QAudioRingBuffer::free () const
Definition at line 126 of file qaudio_mac.cpp.
Referenced by acquireWriteRegion(), QtMultimediaInternal::QAudioOutputBuffer::available(), QtMultimediaInternal::QAudioOutputBuffer::fillBuffer(), and releaseWriteRegion().
 {
     return m_bufferSize - m_bufferUsed;
 }
releaseReadRegion()
void QAudioRingBuffer::releaseReadRegion (Region const & region) inline
Definition at line 97 of file qaudio_mac_p.h.
Referenced by QtMultimediaInternal::QAudioOutputBuffer::readFrames().
     {
         m_readPos = (m_readPos + region.second) % m_bufferSize;
         m_bufferUsed.fetchAndAddRelease(-region.second);
     }
releaseWriteRegion()
void QAudioRingBuffer::releaseWriteRegion (Region const & region) inline
Definition at line 117 of file qaudio_mac_p.h.
Referenced by QtMultimediaInternal::QAudioOutputBuffer::fillBuffer(), and QtMultimediaInternal::QAudioOutputBuffer::writeBytes().
     {
         m_writePos = (m_writePos + region.second) % m_bufferSize;
         m_bufferUsed.fetchAndAddRelease(region.second);
     }
reset()
void QAudioRingBuffer::reset ()
Definition at line 136 of file qaudio_mac.cpp.
Referenced by QAudioRingBuffer(), releaseWriteRegion(), and QtMultimediaInternal::QAudioOutputBuffer::reset().
 {
     m_readPos = 0;
     m_writePos = 0;
     m_bufferUsed = 0;
 }
size()
int QAudioRingBuffer::size () const
Definition at line 131 of file qaudio_mac.cpp.
Referenced by releaseWriteRegion(), and QtMultimediaInternal::QAudioOutputBuffer::startFillTimer().
 {
     return m_bufferSize;
 }
used()
int QAudioRingBuffer::used () const
Definition at line 121 of file qaudio_mac.cpp.
Referenced by acquireReadRegion(), and releaseWriteRegion().
 {
     return m_bufferUsed;
 }
Properties
m_buffer
char* QAudioRingBuffer::m_buffer private
Definition at line 134 of file qaudio_mac_p.h.
Referenced by acquireReadRegion(), acquireWriteRegion(), QAudioRingBuffer(), and ~QAudioRingBuffer().
m_bufferSize
int QAudioRingBuffer::m_bufferSize private
Definition at line 131 of file qaudio_mac_p.h.
Referenced by acquireReadRegion(), acquireWriteRegion(), free(), QAudioRingBuffer(), releaseReadRegion(), releaseWriteRegion(), and size().
m_bufferUsed
QAtomicInt QAudioRingBuffer::m_bufferUsed private
Definition at line 135 of file qaudio_mac_p.h.
Referenced by acquireReadRegion(), acquireWriteRegion(), free(), releaseReadRegion(), releaseWriteRegion(), reset(), and used().
m_readPos
int QAudioRingBuffer::m_readPos private
Definition at line 132 of file qaudio_mac_p.h.
Referenced by acquireReadRegion(), releaseReadRegion(), and reset().
m_writePos
int QAudioRingBuffer::m_writePos private
Definition at line 133 of file qaudio_mac_p.h.
Referenced by acquireWriteRegion(), releaseWriteRegion(), and reset().
The documentation for this class was generated from the following files:
/src/multimedia/audio/qaudio_mac_p.h
/src/multimedia/audio/qaudio_mac.cpp