Qt 4.8: QAnimationDriver Class Reference
QAnimationDriver Class Reference
The QAnimationDriver class is used to exchange the mechanism that drives animations.
#include <qabstractanimation.h>
Public Functions
void advance ()
Advances the animation based on the current time.
void install ()
Installs this animation driver.
bool isRunning () const
QAnimationDriver (QObject *parent=0)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QAnimationDriver (QAnimationDriverPrivate &dd, QObject *parent=0)
virtual void started ()
This function is called by the animation framework to notify the driver that it should start running.
virtual void stopped ()
This function is called by the animation framework to notify the driver that it should stop running.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void start ()
void stop ()
Friends
class QUnifiedTimer
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAnimationDriver class is used to exchange the mechanism that drives animations.
The default animation system is driven by a timer that fires at regular intervals. In some scenarios, it is better to drive the animation based on other synchronization mechanisms, such as the vertical refresh rate of the screen.
Warning
This function is not part of the public interface.
Definition at line 137 of file qabstractanimation.h.
Constructors and Destructors
QAnimationDriver() [1/2]
QAnimationDriver::QAnimationDriver (QObject * parent = 0)
Definition at line 439 of file qabstractanimation.cpp.
     : QObject(*(new QAnimationDriverPrivate), parent)
 {
 }
QAnimationDriver() [2/2]
QAnimationDriver::QAnimationDriver (QAnimationDriverPrivate & dd, QObject * parent = 0) protected
Definition at line 444 of file qabstractanimation.cpp.
     : QObject(dd, parent)
 {
 }
Functions
advance()
void QAnimationDriver::advance ()
Advances the animation based on the current time.
This function should be continuously called by the driver while the animation is running.
Warning
This function is not part of the public interface.
Definition at line 456 of file qabstractanimation.cpp.
Referenced by QDefaultAnimationDriver::timerEvent().
 {
     QUnifiedTimer *instance = QUnifiedTimer::instance();
     // update current time on all top level animations
     instance->updateAnimationsTime();
     instance->restartAnimationTimer();
 }
install()
void QAnimationDriver::install ()
Installs this animation driver.
The animation driver is thread local and will only apply for the thread its installed in.
Warning
This function is not part of the public interface.
Definition at line 472 of file qabstractanimation.cpp.
 {
     QUnifiedTimer *timer = QUnifiedTimer::instance(true);
     timer->installAnimationDriver(this);
 }
isRunning()
bool QAnimationDriver::isRunning () const
Definition at line 478 of file qabstractanimation.cpp.
Referenced by QUnifiedTimer::installAnimationDriver(), QUnifiedTimer::restartAnimationTimer(), and QUnifiedTimer::setTimingInterval().
 {
     return d_func()->running;
 }
start()
void QAnimationDriver::start () private
Definition at line 484 of file qabstractanimation.cpp.
Referenced by QUnifiedTimer::restartAnimationTimer(), and QUnifiedTimer::setTimingInterval().
 {
     Q_D(QAnimationDriver);
     if (!d->running) {
         started();
         d->running = true;
     }
 }
started()
QAnimationDriver::started () inline protected virtual
This function is called by the animation framework to notify the driver that it should start running.
Warning
This function is not part of the public interface.
Reimplemented in QDefaultAnimationDriver.
Definition at line 151 of file qabstractanimation.h.
Referenced by start().
 {};
stop()
void QAnimationDriver::stop () private
Definition at line 494 of file qabstractanimation.cpp.
Referenced by QUnifiedTimer::restartAnimationTimer(), and QUnifiedTimer::setTimingInterval().
 {
     Q_D(QAnimationDriver);
     if (d->running) {
         stopped();
         d->running = false;
     }
 }
stopped()
QAnimationDriver::stopped () inline protected virtual
This function is called by the animation framework to notify the driver that it should stop running.
Warning
This function is not part of the public interface.
Reimplemented in QDefaultAnimationDriver.
Definition at line 152 of file qabstractanimation.h.
Referenced by stop().
 {};
Friends and Related Functions
QUnifiedTimer
friend class QUnifiedTimer friend
Definition at line 157 of file qabstractanimation.h.
The documentation for this class was generated from the following files:
/src/corelib/animation/qabstractanimation.h
/src/corelib/animation/qabstractanimation.cpp