Qt 4.8: QWidgetAnimator Class Reference
QWidgetAnimator Class Reference
#include <qwidgetanimator_p.h>
Public Functions
void abort (QWidget *widget)
void animate (QWidget *widget, const QRect &final_geometry, bool animate)
bool animating () const
QWidgetAnimator (QMainWindowLayout *layout)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Types
typedef QMap< QWidget *, QPointer< QPropertyAnimation > > AnimationMap
Private Slots
void animationFinished ()
Properties
AnimationMap m_animation_map
QMainWindowLayout * m_mainWindowLayout
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 67 of file qwidgetanimator_p.h.
Typedefs
AnimationMap
typedef QMap<QWidget*, QPointer<QPropertyAnimation> > QWidgetAnimator::AnimationMap private
Definition at line 83 of file qwidgetanimator_p.h.
Constructors and Destructors
QWidgetAnimator()
QWidgetAnimator::QWidgetAnimator (QMainWindowLayout * layout)
Definition at line 50 of file qwidgetanimator.cpp.
                                                           : m_mainWindowLayout(layout)
 {
 }
Functions
abort()
void QWidgetAnimator::abort (QWidget * widget)
Definition at line 54 of file qwidgetanimator.cpp.
Referenced by animationFinished().
 {
 #ifndef QT_NO_ANIMATION
     AnimationMap::iterator it = m_animation_map.find(w);
     if (it == m_animation_map.end())
         return;
     QPropertyAnimation *anim = *it;
     m_animation_map.erase(it);
     if (anim) {
         anim->stop();
     }
 #ifndef QT_NO_MAINWINDOW
     m_mainWindowLayout->animationFinished(w);
 #endif
 #else
     Q_UNUSED(w); //there is no animation to abort
 #endif //QT_NO_ANIMATION
 }
animate()
void QWidgetAnimator::animate (QWidget * widget, const QRect & final_geometry, bool animate)
Definition at line 81 of file qwidgetanimator.cpp.
Referenced by QMainWindowLayoutState::apply(), QDockAreaLayoutInfo::apply(), QToolBarAreaLayout::apply(), and QDockAreaLayout::apply().
 {
     QRect r = widget->geometry();
     if (r.right() < 0 || r.bottom() < 0)
         r = QRect();
     animate = animate && !r.isNull() && !_final_geometry.isNull();
     // might make the wigdet go away by sending it to negative space
     const QRect final_geometry = _final_geometry.isValid() || widget->isWindow() ? _final_geometry :
         QRect(QPoint(-500 - widget->width(), -500 - widget->height()), widget->size());
 #ifndef QT_NO_ANIMATION
     AnimationMap::const_iterator it = m_animation_map.constFind(widget);
     if (it != m_animation_map.constEnd() && (*it)->endValue().toRect() == final_geometry)
         return;
     QPropertyAnimation *anim = new QPropertyAnimation(widget, "geometry", widget);
     anim->setDuration(animate ? 200 : 0);
     anim->setEasingCurve(QEasingCurve::InOutQuad);
     anim->setEndValue(final_geometry);
     m_animation_map[widget] = anim;
     connect(anim, SIGNAL(finished()), SLOT(animationFinished()));
     anim->start(QPropertyAnimation::DeleteWhenStopped);
 #else
     //we do it in one shot
     widget->setGeometry(final_geometry);
 #ifndef QT_NO_MAINWINDOW
     m_mainWindowLayout->animationFinished(widget);
 #endif //QT_NO_MAINWINDOW
 #endif //QT_NO_ANIMATION
 }
animating()
bool QWidgetAnimator::animating () const
Definition at line 114 of file qwidgetanimator.cpp.
Referenced by QMainWindowLayout::updateGapIndicator().
 {
     return !m_animation_map.isEmpty();
 }
animationFinished
void QWidgetAnimator::animationFinished () private slot
Definition at line 74 of file qwidgetanimator.cpp.
Referenced by animate().
 {
     QPropertyAnimation *anim = qobject_cast<QPropertyAnimation*>(sender());
     abort(static_cast<QWidget*>(anim->targetObject()));
 }
Properties
m_animation_map
AnimationMap QWidgetAnimator::m_animation_map private
Definition at line 84 of file qwidgetanimator_p.h.
Referenced by abort(), animate(), and animating().
m_mainWindowLayout
QMainWindowLayout* QWidgetAnimator::m_mainWindowLayout private
Definition at line 85 of file qwidgetanimator_p.h.
Referenced by abort(), and animate().
The documentation for this class was generated from the following files:
/src/gui/widgets/qwidgetanimator_p.h
/src/gui/widgets/qwidgetanimator.cpp