Qt 4.8: NodeList Class Reference
NodeList Class Reference
Public Functions
bool isNull ()
NodeList ()
NodeList (const NodeList &)
~NodeList ()
Static Public Functions
static QScriptValue create (QScriptEngine *, NodeImpl *)
static QScriptValue length (QScriptContext *context, QScriptEngine *engine)
static QScriptValue prototype (QScriptEngine *)
Public Variables
NodeImpl * d
Private Functions
NodeList & operator= (const NodeList &)
Detailed Description
Definition at line 196 of file qdeclarativexmlhttprequest.cpp.
Constructors and Destructors
NodeList() [1/2]
NodeList::NodeList ()
Definition at line 833 of file qdeclarativexmlhttprequest.cpp.
 : d(0)
 {
 }
NodeList() [2/2]
NodeList::NodeList (const NodeList & o)
Definition at line 838 of file qdeclarativexmlhttprequest.cpp.
 : d(o.d)
 {
     if (d) A(d);
 }
~NodeList()
NodeList::~NodeList ()
Definition at line 844 of file qdeclarativexmlhttprequest.cpp.
 {
     if (d) D(d);
 }
Functions
create()
QScriptValue NodeList::create (QScriptEngine * engine, NodeImpl * data) static
Definition at line 814 of file qdeclarativexmlhttprequest.cpp.
Referenced by Node::childNodes().
 {
     QScriptValue instance = engine->newObject();
     instance.setPrototype(NodeList::prototype(engine));
     NodeList list;
     list.d = data;
     if (data) A(data);
     instance.setData(engine->newVariant(QVariant::fromValue(list)));
     if (!QDeclarativeScriptEngine::get(engine)->nodeListClass)
         QDeclarativeScriptEngine::get(engine)->nodeListClass= new NodeListClass(engine);
     instance.setScriptClass(QDeclarativeScriptEngine::get(engine)->nodeListClass);
     return instance;
 }
isNull()
bool NodeList::isNull ()
Definition at line 849 of file qdeclarativexmlhttprequest.cpp.
Referenced by length(), and NodeListClass::queryProperty().
 {
     return d == 0;
 }
length()
QScriptValue NodeList::length (QScriptContext * context, QScriptEngine * engine) static
Definition at line 797 of file qdeclarativexmlhttprequest.cpp.
 {
     NodeList list = qscriptvalue_cast<NodeList>(context->thisObject().data());
     if (list.isNull()) return engine->undefinedValue();
     return QScriptValue(list.d->children.count());
 }
operator=()
NodeList& NodeList::operator= (const NodeList &) private
prototype()
QScriptValue NodeList::prototype (QScriptEngine * engine) static
Definition at line 805 of file qdeclarativexmlhttprequest.cpp.
Referenced by create().
 {
     QScriptValue proto = engine->newObject();
     proto.setProperty(QLatin1String("length"), engine->newFunction(length), QScriptValue::ReadOnly | QScriptValue::PropertyGetter);
     return proto;
 }
Properties
d
NodeImpl* NodeList::d
Definition at line 211 of file qdeclarativexmlhttprequest.cpp.
Referenced by create(), isNull(), length(), NodeList(), NodeListClass::property(), NodeListClass::queryProperty(), and ~NodeList().
The documentation for this class was generated from the following file:
/src/declarative/qml/qdeclarativexmlhttprequest.cpp