Qt 4.8: QGLContextGroupResourceBase Class Reference
QGLContextGroupResourceBase Class Reference abstract
#include <qgl_p.h>
Public Functions
virtual void freeResource (void *value)=0
QGLContextGroupResourceBase ()
virtual ~QGLContextGroupResourceBase ()
void insert (const QGLContext *context, void *value)
void * value (const QGLContext *context)
void cleanup (const QGLContext *context)
void cleanup (const QGLContext *context, void *value)
virtual void contextDeleted (const QGLContext *ctx)
Protected Variables
QList< QGLContextGroup * > m_groups
Properties
QAtomicInt active
Detailed Description
Definition at line 730 of file qgl_p.h.
Constructors and Destructors
QGLContextGroupResourceBase()
QGLContextGroupResourceBase::QGLContextGroupResourceBase ()
Definition at line 5884 of file qgl.cpp.
     : active(0)
 {
 #ifdef QT_GL_CONTEXT_RESOURCE_DEBUG
     qDebug("Creating context group resource object %p.", this);
 #endif
 }
~QGLContextGroupResourceBase()
QGLContextGroupResourceBase::~QGLContextGroupResourceBase () virtual
Definition at line 5892 of file qgl.cpp.
 {
 #ifdef QT_GL_CONTEXT_RESOURCE_DEBUG
     qDebug("Deleting context group resource %p. Group size: %d.", this, m_groups.size());
 #endif
     for (int i = 0; i < m_groups.size(); ++i) {
         m_groups.at(i)->m_resources.remove(this);
         active.deref();
     }
 #ifndef QT_NO_DEBUG
     if (active != 0) {
         qWarning("QtOpenGL: Resources are still available at program shutdown.\n"
                  "          This is possibly caused by a leaked QGLWidget, \n"
                  "          QGLFramebufferObject or QGLPixelBuffer.");
     }
 #endif
 }
Functions
cleanup() [1/2]
void QGLContextGroupResourceBase::cleanup (const QGLContext * context)
Definition at line 5928 of file qgl.cpp.
Referenced by QGLTextureGlyphCache::clear().
 {
     void *resource = value(ctx);
     if (resource != 0) {
         QGLShareContextScope scope(ctx);
         freeResource(resource);
         QGLContextGroup *group = QGLContextPrivate::contextGroup(ctx);
         group->m_resources.remove(this);
         m_groups.removeOne(group);
         active.deref();
     }
 }
cleanup() [2/2]
void QGLContextGroupResourceBase::cleanup (const QGLContext * context, void * value)
Definition at line 5948 of file qgl.cpp.
 {
 #ifdef QT_GL_CONTEXT_RESOURCE_DEBUG
     qDebug("Cleaning up context group resource %p, for context %p in thread %p.", this, ctx, QThread::currentThread());
 #endif
     QGLShareContextScope scope(ctx);
     freeResource(value);
     active.deref();
     QGLContextGroup *group = QGLContextPrivate::contextGroup(ctx);
     m_groups.removeOne(group);
 }
contextDeleted()
void QGLContextGroupResourceBase::contextDeleted (const QGLContext * ctx) virtual
Reimplemented in QGLTextureGlyphCache.
Definition at line 5943 of file qgl.cpp.
 {
     Q_UNUSED(ctx);
 }
freeResource()
virtual void QGLContextGroupResourceBase::freeResource (void * value) pure virtual
Implemented in QGLContextGroupResource< T >, QGLContextGroupResource< QGLGlyphTexture >, QGLContextGroupResource< QGL2GradientCache >, and QGLTextureGlyphCache.
insert()
void QGLContextGroupResourceBase::insert (const QGLContext * context, void * value)
Definition at line 5910 of file qgl.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs().
 {
 #ifdef QT_GL_CONTEXT_RESOURCE_DEBUG
     qDebug("Inserting context group resource %p for context %p, managed by %p.", value, context, this);
 #endif
     QGLContextGroup *group = QGLContextPrivate::contextGroup(context);
     Q_ASSERT(!group->m_resources.contains(this));
     group->m_resources.insert(this, value);
     m_groups.append(group);
     active.ref();
 }
value()
void * QGLContextGroupResourceBase::value (const QGLContext * context)
Definition at line 5922 of file qgl.cpp.
Referenced by QGLContextGroupResource< QGL2GradientCache >::value(), and QGLContextGroupResource< QGL2GradientCache >::~QGLContextGroupResource().
 {
     QGLContextGroup *group = QGLContextPrivate::contextGroup(context);
     return group->m_resources.value(this, 0);
 }
Properties
active
QAtomicInt QGLContextGroupResourceBase::active private
Definition at line 746 of file qgl_p.h.
m_groups
QList<QGLContextGroup *> QGLContextGroupResourceBase::m_groups protected
Definition at line 743 of file qgl_p.h.
The documentation for this class was generated from the following files:
/src/opengl/qgl_p.h
/src/opengl/qgl.cpp