Qt 4.8: QDomNamedNodeMapPrivate Class Reference
QDomNamedNodeMapPrivate Class Reference
Public Functions
void clearMap ()
QDomNamedNodeMapPrivate * clone (QDomNodePrivate *parent)
bool contains (const QString &name) const
bool containsNS (const QString &nsURI, const QString &localName) const
bool isAppendToParent ()
bool isReadOnly ()
QDomNodePrivate * item (int index) const
uint length () const
QDomNodePrivate * namedItem (const QString &name) const
QDomNodePrivate * namedItemNS (const QString &nsURI, const QString &localName) const
QDomNamedNodeMapPrivate (QDomNodePrivate *)
QDomNodePrivate * removeNamedItem (const QString &name)
void setAppendToParent (bool b)
QDomNodePrivate * setNamedItem (QDomNodePrivate *arg)
QDomNodePrivate * setNamedItemNS (QDomNodePrivate *arg)
void setReadOnly (bool r)
~QDomNamedNodeMapPrivate ()
Public Variables
bool appendToParent
QHash< QString, QDomNodePrivate * > map
QDomNodePrivate * parent
bool readonly
QAtomicInt ref
Detailed Description
Definition at line 235 of file qdom.cpp.
Constructors and Destructors
QDomNamedNodeMapPrivate()
QDomNamedNodeMapPrivate::QDomNamedNodeMapPrivate (QDomNodePrivate * n)
Definition at line 3103 of file qdom.cpp.
 {
     ref = 1;
     readonly = false;
     parent = n;
     appendToParent = false;
 }
~QDomNamedNodeMapPrivate()
QDomNamedNodeMapPrivate::~QDomNamedNodeMapPrivate ()
Definition at line 3111 of file qdom.cpp.
 {
     clearMap();
 }
Functions
clearMap()
void QDomNamedNodeMapPrivate::clearMap ()
Remove all children from the map.
Definition at line 3134 of file qdom.cpp.
 {
     // Dereference all of our children if we took references
     if (!appendToParent) {
         QHash<QString, QDomNodePrivate *>::const_iterator it = map.constBegin();
         for (; it != map.constEnd(); ++it)
             if (!(*it)->ref.deref())
                 delete *it;
     }
     map.clear();
 }
clone()
QDomNamedNodeMapPrivate * QDomNamedNodeMapPrivate::clone (QDomNodePrivate * parent)
Creates a copy of the map. It is a deep copy that means that all children are cloned.
Definition at line 3116 of file qdom.cpp.
Referenced by QDomElementPrivate::QDomElementPrivate().
 {
     QScopedPointer<QDomNamedNodeMapPrivate> m(new QDomNamedNodeMapPrivate(p));
     m->readonly = readonly;
     m->appendToParent = appendToParent;
     QHash<QString, QDomNodePrivate*>::const_iterator it = map.constBegin();
     for (; it != map.constEnd(); ++it) {
         QDomNodePrivate *new_node = (*it)->cloneNode();
         new_node->setParent(p);
         m->setNamedItem(new_node);
     }
     // we are no longer interested in ownership
     m->ref.deref();
     return m.take();
 }
contains()
bool QDomNamedNodeMapPrivate::contains (const QString & name) const
Definition at line 3233 of file qdom.cpp.
Referenced by QDomElementPrivate::hasAttribute().
 {
     return map.value(name) != 0;
 }
containsNS()
bool QDomNamedNodeMapPrivate::containsNS (const QString & nsURI, const QString & localName) const
Definition at line 3238 of file qdom.cpp.
Referenced by QDomElementPrivate::hasAttributeNS().
 {
     return namedItemNS(nsURI, localName) != 0;
 }
isAppendToParent()
bool QDomNamedNodeMapPrivate::isAppendToParent () inline
Definition at line 257 of file qdom.cpp.
 { return appendToParent; }
isReadOnly()
bool QDomNamedNodeMapPrivate::isReadOnly () inline
Definition at line 255 of file qdom.cpp.
 { return readonly; }
item()
QDomNodePrivate * QDomNamedNodeMapPrivate::item (int index) const
Definition at line 3220 of file qdom.cpp.
 {
     if ((uint)index >= length())
         return 0;
     return *(map.constBegin() + index);
 }
length()
uint QDomNamedNodeMapPrivate::length () const
Definition at line 3228 of file qdom.cpp.
Referenced by QDomDocumentTypePrivate::save().
 {
     return map.count();
 }
namedItem()
QDomNodePrivate * QDomNamedNodeMapPrivate::namedItem (const QString & name) const
Definition at line 3146 of file qdom.cpp.
Referenced by QDomElementPrivate::attribute(), QDomElementPrivate::attributeNode(), QDomElementPrivate::setAttribute(), and QDomElementPrivate::setAttributeNode().
 {
     QDomNodePrivate* p = map[name];
     return p;
 }
namedItemNS()
QDomNodePrivate * QDomNamedNodeMapPrivate::namedItemNS (const QString & nsURI, const QString & localName) const
Definition at line 3152 of file qdom.cpp.
Referenced by QDomElementPrivate::attributeNodeNS(), QDomElementPrivate::attributeNS(), QDomElementPrivate::setAttributeNodeNS(), and QDomElementPrivate::setAttributeNS().
 {
     QHash<QString, QDomNodePrivate *>::const_iterator it = map.constBegin();
     QDomNodePrivate *n;
     for (; it != map.constEnd(); ++it) {
         n = *it;
         if (!n->prefix.isNull()) {
             // node has a namespace
             if (n->namespaceURI == nsURI && n->name == localName)
                 return n;
         }
     }
     return 0;
 }
removeNamedItem()
QDomNodePrivate * QDomNamedNodeMapPrivate::removeNamedItem (const QString & name)
Definition at line 3203 of file qdom.cpp.
Referenced by QDomElementPrivate::removeAttribute(), and QDomElementPrivate::removeAttributeNode().
 {
     if (readonly)
         return 0;
     QDomNodePrivate* p = namedItem(name);
     if (p == 0)
         return 0;
     if (appendToParent)
         return parent->removeChild(p);
     map.remove(p->nodeName());
     // We took a reference, so we have to free one here
     p->ref.deref();
     return p;
 }
setAppendToParent()
void QDomNamedNodeMapPrivate::setAppendToParent (bool b) inline
If true, then the node will redirect insert/remove calls to its parent by calling QDomNodePrivate::appendChild or removeChild. In addition the map wont increase or decrease the reference count of the nodes it contains.
By default this value is false and the map will handle reference counting by itself.
Definition at line 267 of file qdom.cpp.
Referenced by QDomDocumentTypePrivate::init().
 { appendToParent = b; }
setNamedItem()
QDomNodePrivate * QDomNamedNodeMapPrivate::setNamedItem (QDomNodePrivate * arg)
Definition at line 3167 of file qdom.cpp.
Referenced by clone(), QDomElementPrivate::setAttribute(), QDomElementPrivate::setAttributeNode(), QDomElementPrivate::setAttributeNodeNS(), and QDomElementPrivate::setAttributeNS().
 {
     if (readonly || !arg)
         return 0;
     if (appendToParent)
         return parent->appendChild(arg);
     QDomNodePrivate *n = map.value(arg->nodeName());
     // We take a reference
     arg->ref.ref();
     map.insertMulti(arg->nodeName(), arg);
     return n;
 }
setNamedItemNS()
QDomNodePrivate * QDomNamedNodeMapPrivate::setNamedItemNS (QDomNodePrivate * arg)
Definition at line 3182 of file qdom.cpp.
 {
     if (readonly || !arg)
         return 0;
     if (appendToParent)
         return parent->appendChild(arg);
     if (!arg->prefix.isNull()) {
         // node has a namespace
         QDomNodePrivate *n = namedItemNS(arg->namespaceURI, arg->name);
         // We take a reference
         arg->ref.ref();
         map.insertMulti(arg->nodeName(), arg);
         return n;
     } else {
         // ### check the following code if it is ok
         return setNamedItem(arg);
     }
 }
setReadOnly()
void QDomNamedNodeMapPrivate::setReadOnly (bool r) inline
Definition at line 256 of file qdom.cpp.
 { readonly = r; }
Properties
appendToParent
bool QDomNamedNodeMapPrivate::appendToParent
Definition at line 280 of file qdom.cpp.
Referenced by clone().
map
QHash<QString, QDomNodePrivate *> QDomNamedNodeMapPrivate::map
Definition at line 277 of file qdom.cpp.
Referenced by QDomDocumentTypePrivate::insertAfter(), QDomDocumentTypePrivate::insertBefore(), QDomDocumentTypePrivate::QDomDocumentTypePrivate(), QDomDocumentTypePrivate::removeChild(), QDomDocumentTypePrivate::replaceChild(), QDomDocumentTypePrivate::save(), and QDomElementPrivate::save().
parent
QDomNodePrivate* QDomNamedNodeMapPrivate::parent
Definition at line 278 of file qdom.cpp.
readonly
bool QDomNamedNodeMapPrivate::readonly
Definition at line 279 of file qdom.cpp.
Referenced by clone().
ref
QAtomicInt QDomNamedNodeMapPrivate::ref
Definition at line 276 of file qdom.cpp.
Referenced by clone(), QDomNamedNodeMap::operator=(), QDomElementPrivate::QDomElementPrivate(), QDomDocumentTypePrivate::~QDomDocumentTypePrivate(), and QDomElementPrivate::~QDomElementPrivate().
The documentation for this class was generated from the following file:
/src/xml/dom/qdom.cpp