Qt 4.8: QMetaPropertyBuilder Class Reference
QMetaPropertyBuilder Class Reference
The QMetaPropertyBuilder class enables modifications to a property definition on a meta object builder.
#include <qmetaobjectbuilder_p.h>
Public Functions
bool hasNotifySignal () const
Returns true if this property has a notify signal; false otherwise.
bool hasStdCppSet () const
Returns true if the property has a C++ setter function that follows Qt's standard "name" / "setName" pattern.
int index () const
Returns the index of this property within its QMetaObjectBuilder.
bool isConstant () const
Returns true if the property is constant; otherwise returns false.
bool isDesignable () const
Returns true if this property is designable; otherwise returns false.
bool isEditable () const
Returns true if the property is editable; otherwise returns false.
bool isEnumOrFlag () const
Returns true if the property is an enumerator or flag type; otherwise returns false.
bool isFinal () const
Returns true if the property is final; otherwise returns false.
bool isReadable () const
Returns true if this property is readable; otherwise returns false.
bool isResettable () const
Returns true if this property can be reset to a default value; otherwise returns false.
bool isScriptable () const
Returns true if the property is scriptable; otherwise returns false.
bool isStored () const
Returns true if the property is stored; otherwise returns false.
bool isUser () const
Returns true if this property is designated as the USER property, i.e., the one that the user can edit or that is significant in some other way.
bool isWritable () const
Returns true if this property is writable; otherwise returns false.
QByteArray name () const
Returns the name associated with this property.
QMetaMethodBuilder notifySignal () const
Returns the notify signal associated with this property.
QMetaPropertyBuilder ()
void removeNotifySignal ()
Removes the notify signal from this property.
void setConstant (bool value)
Sets the CONSTANT flag on this property to value.
void setDesignable (bool value)
Sets this property to designable if value is true.
void setEditable (bool value)
Sets this property to editable if value is true.
void setEnumOrFlag (bool value)
Sets this property to be of an enumerator or flag type if value is true.
void setFinal (bool value)
Sets the FINAL flag on this property to value.
void setNotifySignal (const QMetaMethodBuilder &value)
Sets the notify signal associated with this property to value.
void setReadable (bool value)
Sets this property to readable if value is true.
void setResettable (bool value)
Sets this property to resettable if value is true.
void setScriptable (bool value)
Sets this property to scriptable if value is true.
void setStdCppSet (bool value)
Sets the C++ setter flag on this property to value, which is true if the property has a C++ setter function that follows Qt's standard "name" / "setName" pattern.
void setStored (bool value)
Sets this property to storable if value is true.
void setUser (bool value)
Sets the USER flag on this property to value.
void setWritable (bool value)
Sets this property to writable if value is true.
QByteArray type () const
Returns the type associated with this property.
Private Functions
QMetaPropertyBuilderPrivate * d_func () const
QMetaPropertyBuilder (const QMetaObjectBuilder *mobj, int index)
Properties
int _index
const QMetaObjectBuilder * _mobj
Friends
class QMetaObjectBuilder
Detailed Description
The QMetaPropertyBuilder class enables modifications to a property definition on a meta object builder.
Warning
This function is not part of the public interface.
Definition at line 236 of file qmetaobjectbuilder_p.h.
Constructors and Destructors
QMetaPropertyBuilder() [1/2]
QMetaPropertyBuilder::QMetaPropertyBuilder () inline
Warning
This function is not part of the public interface.
Definition at line 239 of file qmetaobjectbuilder_p.h.
 : _mobj(0), _index(0) {}
QMetaPropertyBuilder() [2/2]
QMetaPropertyBuilder::QMetaPropertyBuilder (const QMetaObjectBuilder * mobj, int index) inline private
Definition at line 283 of file qmetaobjectbuilder_p.h.
         : _mobj(mobj), _index(index) {}
Functions
d_func()
QMetaPropertyBuilderPrivate * QMetaPropertyBuilder::d_func () const private
Definition at line 2035 of file qmetaobjectbuilder.cpp.
Referenced by QMetaMethodBuilder::QMetaMethodBuilder().
 {
     if (_mobj && _index >= 0 && _index < _mobj->d->properties.size())
         return &(_mobj->d->properties[_index]);
     else
         return 0;
 }
hasNotifySignal()
bool QMetaPropertyBuilder::hasNotifySignal () const
Returns true if this property has a notify signal; false otherwise.
See also
notifySignal(), setNotifySignal(), removeNotifySignal()
Definition at line 2090 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(Notify);
     else
         return false;
 }
hasStdCppSet()
bool QMetaPropertyBuilder::hasStdCppSet () const
Returns true if the property has a C++ setter function that follows Qt's standard "name" / "setName" pattern.
Designer and uic query hasStdCppSet() in order to avoid expensive QObject::setProperty() calls. All properties in Qt [should] follow this pattern. The default value is false.
See also
setStdCppSet()
Definition at line 2277 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(StdCppSet);
     else
         return false;
 }
index()
int QMetaPropertyBuilder::index () const inline
Returns the index of this property within its QMetaObjectBuilder.
Definition at line 241 of file qmetaobjectbuilder_p.h.
 { return _index; }
isConstant()
bool QMetaPropertyBuilder::isConstant () const
Returns true if the property is constant; otherwise returns false.
The default value is false.
Definition at line 2305 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(Constant);
     else
         return false;
 }
isDesignable()
bool QMetaPropertyBuilder::isDesignable () const
Returns true if this property is designable; otherwise returns false.
This default value is false.
See also
setDesignable(), isScriptable(), isStored()
Definition at line 2197 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(Designable);
     else
         return false;
 }
isEditable()
bool QMetaPropertyBuilder::isEditable () const
Returns true if the property is editable; otherwise returns false.
This default value is false.
See also
setEditable(), isDesignable(), isScriptable(), isStored()
Definition at line 2242 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(Editable);
     else
         return false;
 }
isEnumOrFlag()
bool QMetaPropertyBuilder::isEnumOrFlag () const
Returns true if the property is an enumerator or flag type; otherwise returns false.
This default value is false.
See also
setEnumOrFlag()
Definition at line 2292 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(EnumOrFlag);
     else
         return false;
 }
isFinal()
bool QMetaPropertyBuilder::isFinal () const
Returns true if the property is final; otherwise returns false.
The default value is false.
Definition at line 2318 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(Final);
     else
         return false;
 }
isReadable()
bool QMetaPropertyBuilder::isReadable () const
Returns true if this property is readable; otherwise returns false.
The default value is true.
See also
setReadable(), isWritable()
Definition at line 2152 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(Readable);
     else
         return false;
 }
isResettable()
bool QMetaPropertyBuilder::isResettable () const
Returns true if this property can be reset to a default value; otherwise returns false.
The default value is false.
See also
setResettable()
Definition at line 2182 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(Resettable);
     else
         return false;
 }
isScriptable()
bool QMetaPropertyBuilder::isScriptable () const
Returns true if the property is scriptable; otherwise returns false.
This default value is true.
See also
setScriptable(), isDesignable(), isStored()
Definition at line 2212 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(Scriptable);
     else
         return false;
 }
isStored()
bool QMetaPropertyBuilder::isStored () const
Returns true if the property is stored; otherwise returns false.
This default value is false.
See also
setStored(), isDesignable(), isScriptable()
Definition at line 2227 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(Stored);
     else
         return false;
 }
isUser()
bool QMetaPropertyBuilder::isUser () const
Returns true if this property is designated as the USER property, i.e., the one that the user can edit or that is significant in some other way.
Otherwise it returns false. This default value is false.
See also
setUser(), isDesignable(), isScriptable()
Definition at line 2259 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(User);
     else
         return false;
 }
isWritable()
bool QMetaPropertyBuilder::isWritable () const
Returns true if this property is writable; otherwise returns false.
The default value is true.
See also
setWritable(), isReadable()
Definition at line 2167 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->flag(Writable);
     else
         return false;
 }
name()
QByteArray QMetaPropertyBuilder::name () const
Returns the name associated with this property.
See also
type()
Definition at line 2062 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeOpenMetaObject::name(), and QDeclarativePropertyMapMetaObject::propertyCreated().
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->name;
     else
         return QByteArray();
 }
notifySignal()
QMetaMethodBuilder QMetaPropertyBuilder::notifySignal () const
Returns the notify signal associated with this property.
See also
hasNotifySignal(), setNotifySignal(), removeNotifySignal()
Definition at line 2104 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d && d->notifySignal >= 0)
         return QMetaMethodBuilder(_mobj, d->notifySignal);
     else
         return QMetaMethodBuilder();
 }
removeNotifySignal()
void QMetaPropertyBuilder::removeNotifySignal ()
Removes the notify signal from this property.
See also
hasNotifySignal(), notifySignal(), setNotifySignal()
Definition at line 2137 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d) {
         d->notifySignal = -1;
         d->setFlag(Notify, false);
     }
 }
setConstant()
void QMetaPropertyBuilder::setConstant (bool value)
Sets the CONSTANT flag on this property to value.
See also
isConstant()
Definition at line 2455 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(Constant, value);
 }
setDesignable()
void QMetaPropertyBuilder::setDesignable (bool value)
Sets this property to designable if value is true.
See also
isDesignable(), setScriptable(), setStored()
Definition at line 2368 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(Designable, value);
 }
setEditable()
void QMetaPropertyBuilder::setEditable (bool value)
Sets this property to editable if value is true.
See also
isEditable(), setDesignable(), setScriptable(), setStored()
Definition at line 2404 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(Editable, value);
 }
setEnumOrFlag()
void QMetaPropertyBuilder::setEnumOrFlag (bool value)
Sets this property to be of an enumerator or flag type if value is true.
See also
isEnumOrFlag()
Definition at line 2443 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(EnumOrFlag, value);
 }
setFinal()
void QMetaPropertyBuilder::setFinal (bool value)
Sets the FINAL flag on this property to value.
See also
isFinal()
Definition at line 2467 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(Final, value);
 }
setNotifySignal()
void QMetaPropertyBuilder::setNotifySignal (const QMetaMethodBuilder & value)
Sets the notify signal associated with this property to value.
See also
hasNotifySignal(), notifySignal(), removeNotifySignal()
Definition at line 2118 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d) {
         if (value._mobj) {
             d->notifySignal = value._index;
             d->setFlag(Notify, true);
         } else {
             d->notifySignal = -1;
             d->setFlag(Notify, false);
         }
     }
 }
setReadable()
void QMetaPropertyBuilder::setReadable (bool value)
Sets this property to readable if value is true.
See also
isReadable(), setWritable()
Definition at line 2332 of file qmetaobjectbuilder.cpp.
Referenced by QMetaObjectBuilder::addProperty().
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(Readable, value);
 }
setResettable()
void QMetaPropertyBuilder::setResettable (bool value)
Sets this property to resettable if value is true.
See also
isResettable()
Definition at line 2356 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(Resettable, value);
 }
setScriptable()
void QMetaPropertyBuilder::setScriptable (bool value)
Sets this property to scriptable if value is true.
See also
isScriptable(), setDesignable(), setStored()
Definition at line 2380 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(Scriptable, value);
 }
setStdCppSet()
void QMetaPropertyBuilder::setStdCppSet (bool value)
Sets the C++ setter flag on this property to value, which is true if the property has a C++ setter function that follows Qt's standard "name" / "setName" pattern.
See also
hasStdCppSet()
Definition at line 2430 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(StdCppSet, value);
 }
setStored()
void QMetaPropertyBuilder::setStored (bool value)
Sets this property to storable if value is true.
See also
isStored(), setDesignable(), setScriptable()
Definition at line 2392 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(Stored, value);
 }
setUser()
void QMetaPropertyBuilder::setUser (bool value)
Sets the USER flag on this property to value.
See also
isUser(), setDesignable(), setScriptable()
Definition at line 2416 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(User, value);
 }
setWritable()
void QMetaPropertyBuilder::setWritable (bool value)
Sets this property to writable if value is true.
See also
isWritable(), setReadable()
Definition at line 2344 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), QDeclarativeCompiler::compileAlias(), VDMDelegateDataType::propertyCreated(), QDeclarativeVisualDataModelPartsMetaObject::propertyCreated(), and QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters().
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         d->setFlag(Writable, value);
 }
type()
QByteArray QMetaPropertyBuilder::type () const
Returns the type associated with this property.
See also
name()
Definition at line 2076 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilderPrivate *d = d_func();
     if (d)
         return d->type;
     else
         return QByteArray();
 }
Friends and Related Functions
QMetaObjectBuilder
friend class QMetaObjectBuilder friend
Definition at line 281 of file qmetaobjectbuilder_p.h.
Properties
_index
int QMetaPropertyBuilder::_index private
Definition at line 279 of file qmetaobjectbuilder_p.h.
_mobj
const QMetaObjectBuilder* QMetaPropertyBuilder::_mobj private
Definition at line 278 of file qmetaobjectbuilder_p.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qmetaobjectbuilder_p.h
/src/declarative/qml/qmetaobjectbuilder.cpp