Qt 4.8: QSqlError Class Reference
QSqlError Class Reference
The QSqlError class provides SQL database error information.
#include <qsqlerror.h>
Public Types
enum ErrorType {
NoError, ConnectionError, StatementError, TransactionError,
UnknownError
}
This enum type describes the context in which the error occurred, e.
Public Functions
QString databaseText () const
Returns the text of the error as reported by the database.
QString driverText () const
Returns the text of the error as reported by the driver.
bool isValid () const
Returns true if an error is set, otherwise false.
int number () const
Returns the database-specific error number, or -1 if it cannot be determined.
QSqlError & operator= (const QSqlError &other)
Assigns the other error's values to this error.
QSqlError (const QString &driverText=QString(), const QString &databaseText=QString(), ErrorType type=NoError, int number=-1)
Constructs an error containing the driver error text driverText, the database-specific error text databaseText, the type type and the optional error number number.
QSqlError (const QSqlError &other)
Creates a copy of other.
void setDatabaseText (const QString &databaseText)
Sets the database error text to the value of databaseText.
void setDriverText (const QString &driverText)
Sets the driver error text to the value of driverText.
void setNumber (int number)
Sets the database-specific error number to number.
void setType (ErrorType type)
Sets the error type to the value of type.
QString text () const
This is a convenience function that returns databaseText() and driverText() concatenated into a single string.
ErrorType type () const
Returns the error type, or -1 if the type cannot be determined.
~QSqlError ()
Destroys the object and frees any allocated resources.
Properties
QString databaseError
QString driverError
int errorNumber
ErrorType errorType
Detailed Description
The QSqlError class provides SQL database error information.
Attention
Module: QtSql
A QSqlError object can provide database-specific error data, including the driverText() and databaseText() messages (or both concatenated together as text()), and the error number() and type(). The functions all have setters so that you can create and return QSqlError objects from your own classes, for example from your own SQL drivers.
See also
QSqlDatabase::lastError(), QSqlQuery::lastError()
Definition at line 53 of file qsqlerror.h.
Enumerations
ErrorType
enum QSqlError::ErrorType
This enum type describes the context in which the error occurred, e.
g., a connection error, a statement error, etc.
\arg \b NoError  No error occurred.
\arg \b ConnectionError  Connection error.
\arg \b StatementError  SQL statement syntax error.
\arg \b TransactionError  Transaction failed error.
\arg \b UnknownError  Unknown error.
\arg \e None
\arg \e Connection
\arg \e Statement
\arg \e Transaction
\arg \e Unknown
Enumerator
NoError
ConnectionError
StatementError
TransactionError
UnknownError
Definition at line 56 of file qsqlerror.h.
                    {
         NoError,
         ConnectionError,
         StatementError,
         TransactionError,
         UnknownError
 #ifdef QT3_SUPPORT
         , None = NoError,
         Connection = ConnectionError,
         Statement = StatementError,
         Transaction = TransactionError,
         Unknown = UnknownError
 #endif
     };
Constructors and Destructors
QSqlError() [1/2]
QSqlError::QSqlError (const QString & driverText = QString(), const QString & databaseText = QString(), ErrorType type = NoError, int number = -1)
Constructs an error containing the driver error text driverText, the database-specific error text databaseText, the type type and the optional error number number.
Definition at line 103 of file qsqlerror.cpp.
     : driverError(driverText), databaseError(databaseText), errorType(type), errorNumber(number)
 {
 }
QSqlError() [2/2]
QSqlError::QSqlError (const QSqlError & other)
Creates a copy of other.
Definition at line 112 of file qsqlerror.cpp.
     : driverError(other.driverError), databaseError(other.databaseError),
       errorType(other.errorType),
       errorNumber(other.errorNumber)
 {
 }
~QSqlError()
QSqlError::~QSqlError ()
Destroys the object and frees any allocated resources.
Definition at line 136 of file qsqlerror.cpp.
 {
 }
Functions
databaseText()
QString QSqlError::databaseText () const
Returns the text of the error as reported by the database.
This may contain database-specific descriptions; it may be empty.
See also
setDatabaseText() driverText() text()
Definition at line 169 of file qsqlerror.cpp.
Referenced by QSQLiteDriver::beginTransaction(), QSQLiteDriver::commitTransaction(), operator<<(), QSQLiteDriver::rollbackTransaction(), and setDatabaseText().
 {
     return databaseError;
 }
driverText()
QString QSqlError::driverText () const
Returns the text of the error as reported by the driver.
This may contain database-specific descriptions. It may also be empty.
See also
setDriverText() databaseText() text()
Definition at line 146 of file qsqlerror.cpp.
Referenced by operator<<(), and setDriverText().
 {
     return driverError;
 }
isValid()
bool QSqlError::isValid () const
Returns true if an error is set, otherwise false.
Example:
QSqlQueryModel model;
model.setQuery("select * from myTable");
if (model.lastError().isValid())
    qDebug() << model.lastError();
See also
type()
Definition at line 254 of file qsqlerror.cpp.
Referenced by QSqlTableModel::select(), and QSqlQueryModel::setQuery().
 {
     return errorType != NoError;
 }
number()
int QSqlError::number () const
Returns the database-specific error number, or -1 if it cannot be determined.
See also
setNumber()
Definition at line 214 of file qsqlerror.cpp.
Referenced by operator<<(), and setNumber().
 {
     return errorNumber;
 }
operator=()
QSqlError & QSqlError::operator= (const QSqlError & other)
Assigns the other error's values to this error.
Definition at line 123 of file qsqlerror.cpp.
 {
     driverError = other.driverError;
     databaseError = other.databaseError;
     errorType = other.errorType;
     errorNumber = other.errorNumber;
     return *this;
 }
setDatabaseText()
void QSqlError::setDatabaseText (const QString & databaseText)
Sets the database error text to the value of databaseText.
See also
databaseText() setDriverText() text()
Definition at line 180 of file qsqlerror.cpp.
 {
     databaseError = databaseText;
 }
setDriverText()
void QSqlError::setDriverText (const QString & driverText)
Sets the driver error text to the value of driverText.
See also
driverText() setDatabaseText() text()
Definition at line 157 of file qsqlerror.cpp.
 {
     driverError = driverText;
 }
setNumber()
void QSqlError::setNumber (int number)
Sets the database-specific error number to number.
See also
number()
Definition at line 225 of file qsqlerror.cpp.
 {
     errorNumber = number;
 }
setType()
void QSqlError::setType (ErrorType type)
Sets the error type to the value of type.
See also
type()
Definition at line 202 of file qsqlerror.cpp.
 {
     errorType = type;
 }
text()
QString QSqlError::text () const
This is a convenience function that returns databaseText() and driverText() concatenated into a single string.
See also
driverText() databaseText()
Definition at line 237 of file qsqlerror.cpp.
Referenced by QSqlDatabasePrivate::database(), and qmlsqldatabase_executeSql().
 {
     QString result = databaseError;
     if (!databaseError.endsWith(QLatin1String("\n")))
         result += QLatin1Char(' ');
     result += driverError;
     return result;
 }
type()
QSqlError::ErrorType QSqlError::type () const
Returns the error type, or -1 if the type cannot be determined.
See also
setType()
Definition at line 191 of file qsqlerror.cpp.
Referenced by setType().
 {
     return errorType;
 }
Properties
databaseError
QString QSqlError::databaseError private
Definition at line 91 of file qsqlerror.h.
Referenced by databaseText(), operator=(), setDatabaseText(), and text().
driverError
QString QSqlError::driverError private
Definition at line 90 of file qsqlerror.h.
Referenced by driverText(), operator=(), setDriverText(), and text().
errorNumber
int QSqlError::errorNumber private
Definition at line 93 of file qsqlerror.h.
Referenced by number(), operator=(), and setNumber().
errorType
ErrorType QSqlError::errorType private
Definition at line 92 of file qsqlerror.h.
Referenced by isValid(), operator=(), setType(), and type().
The documentation for this class was generated from the following files:
/src/sql/kernel/qsqlerror.h
/src/sql/kernel/qsqlerror.cpp