Qt 4.8: QAbstractEventDispatcherPrivate Class Reference
QAbstractEventDispatcherPrivate Class Reference
#include <qabstracteventdispatcher_p.h>
Public Functions
void init ()
QAbstractEventDispatcherPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static int allocateTimerId ()
static void releaseTimerId (int id)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QAbstractEventDispatcher::EventFilter event_filter
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 63 of file qabstracteventdispatcher_p.h.
Constructors and Destructors
QAbstractEventDispatcherPrivate()
QAbstractEventDispatcherPrivate::QAbstractEventDispatcherPrivate () inline
Definition at line 67 of file qabstracteventdispatcher_p.h.
         : event_filter(0)
     { }
Functions
allocateTimerId()
int QAbstractEventDispatcherPrivate::allocateTimerId () static
Definition at line 175 of file qabstracteventdispatcher.cpp.
Referenced by QAbstractEventDispatcher::registerTimer().
 {
     int timerId, newTimerId;
     int at, *b;
     do {
         timerId = nextFreeTimerId; //.loadAcquire(); // ### FIXME Proper memory ordering semantics
         // which bucket are we looking in?
         int which = timerId & TimerIdMask;
         int bucket = bucketOffset(which);
         at = bucketIndex(bucket, which);
         b = timerIds[bucket];
         if (!b) {
             // allocate a new bucket
             b = allocateBucket(bucket);
             if (!timerIds[bucket].testAndSetRelease(0, b)) {
                 // another thread won the race to allocate the bucket
                 delete [] b;
                 b = timerIds[bucket];
             }
         }
         newTimerId = prepareNewValueWithSerialNumber(timerId, b[at]);
     } while (!nextFreeTimerId.testAndSetRelaxed(timerId, newTimerId));
     b[at] = -timerId;
     return timerId;
 }
init()
void QAbstractEventDispatcherPrivate::init ()
Definition at line 151 of file qabstracteventdispatcher.cpp.
 {
     Q_Q(QAbstractEventDispatcher);
     if (threadData->eventDispatcher != 0) {
         qWarning("QAbstractEventDispatcher: An event dispatcher has already been created for this thread");
     } else {
         threadData->eventDispatcher = q;
     }
 }
releaseTimerId()
void QAbstractEventDispatcherPrivate::releaseTimerId (int id) static
Definition at line 217 of file qabstracteventdispatcher.cpp.
Referenced by QTimerInfoList::unregisterTimer(), QEventDispatcherMac::unregisterTimer(), QEventDispatcherWin32Private::unregisterTimer(), QTimerInfoList::unregisterTimers(), and QEventDispatcherMac::unregisterTimers().
 {
     int which = timerId & TimerIdMask;
     int bucket = bucketOffset(which);
     int at = bucketIndex(bucket, which);
     int *b = timerIds[bucket];
     Q_ASSERT_X(timerId == -b[at], "QAbstractEventDispatcher::releaseTimerId",
                "Internal error: timer ID not found");
     int freeId, newTimerId;
     do {
         freeId = nextFreeTimerId;//.loadAcquire(); // ### FIXME Proper memory ordering semantics
         b[at] = freeId & TimerIdMask;
         newTimerId = prepareNewValueWithSerialNumber(freeId, timerId);
     } while (!nextFreeTimerId.testAndSetRelease(freeId, newTimerId));
 }
Properties
event_filter
QAbstractEventDispatcher::EventFilter QAbstractEventDispatcherPrivate::event_filter
Definition at line 71 of file qabstracteventdispatcher_p.h.
The documentation for this class was generated from the following files:
/src/corelib/kernel/qabstracteventdispatcher_p.h
/src/corelib/kernel/qabstracteventdispatcher.cpp