Qt 4.8: QSslError Class Reference
QSslError Class Reference
The QSslError class provides an SSL error.
#include <qsslerror.h>
Public Types
enum SslError {
NoError, UnableToGetIssuerCertificate, UnableToDecryptCertificateSignature, UnableToDecodeIssuerPublicKey,
CertificateSignatureFailed, CertificateNotYetValid, CertificateExpired, InvalidNotBeforeField,
InvalidNotAfterField, SelfSignedCertificate, SelfSignedCertificateInChain, UnableToGetLocalIssuerCertificate,
UnableToVerifyFirstCertificate, CertificateRevoked, InvalidCaCertificate, PathLengthExceeded,
InvalidPurpose, CertificateUntrusted, CertificateRejected, SubjectIssuerMismatch,
AuthorityIssuerSerialNumberMismatch, NoPeerCertificate, HostNameMismatch, NoSslSupport,
CertificateBlacklisted, UnspecifiedError = -1
}
Describes all recognized errors that can occur during an SSL handshake.
Public Functions
QSslCertificate certificate () const
Returns the certificate associated with this error, or a null certificate if the error does not relate to any certificate.
SslError error () const
Returns the type of the error.
QString errorString () const
Returns a short localized human-readable description of the error.
bool operator!= (const QSslError &other) const
Returns true if this error is not equal to other; otherwise returns false.
QSslError & operator= (const QSslError &other)
Assigns the contents of other to this error.
bool operator== (const QSslError &other) const
Returns true if this error is equal to other; otherwise returns false.
QSslError ()
Constructs a QSslError object with no error and default certificate.
QSslError (SslError error)
Constructs a QSslError object.
QSslError (SslError error, const QSslCertificate &certificate)
Constructs a QSslError object.
QSslError (const QSslError &other)
Constructs an identical copy of other.
~QSslError ()
Destroys the QSslError object.
Properties
QScopedPointer< QSslErrorPrivate > d
Detailed Description
The QSslError class provides an SSL error.
Since
4.3
Note
This class or function is reentrant.
Attention
Module: QtNetwork
QSslError provides a simple API for managing errors during QSslSocket's SSL handshake.
See also
QSslSocket, QSslCertificate, QSslCipher
Definition at line 58 of file qsslerror.h.
Enumerations
SslError
enum QSslError::SslError
Describes all recognized errors that can occur during an SSL handshake.
NoError
UnableToGetIssuerCertificate
UnableToDecryptCertificateSignature
UnableToDecodeIssuerPublicKey
CertificateSignatureFailed
CertificateNotYetValid
CertificateExpired
InvalidNotBeforeField
InvalidNotAfterField
SelfSignedCertificate
SelfSignedCertificateInChain
UnableToGetLocalIssuerCertificate
UnableToVerifyFirstCertificate
CertificateRevoked
InvalidCaCertificate
PathLengthExceeded
InvalidPurpose
CertificateUntrusted
CertificateRejected
SubjectIssuerMismatch
AuthorityIssuerSerialNumberMismatch
NoPeerCertificate
HostNameMismatch
UnspecifiedError
NoSslSupport
CertificateBlacklisted
See also
QSslError::errorString()
Enumerator
NoError
UnableToGetIssuerCertificate
UnableToDecryptCertificateSignature
UnableToDecodeIssuerPublicKey
CertificateSignatureFailed
CertificateNotYetValid
CertificateExpired
InvalidNotBeforeField
InvalidNotAfterField
SelfSignedCertificate
SelfSignedCertificateInChain
UnableToGetLocalIssuerCertificate
UnableToVerifyFirstCertificate
CertificateRevoked
InvalidCaCertificate
PathLengthExceeded
InvalidPurpose
CertificateUntrusted
CertificateRejected
SubjectIssuerMismatch
AuthorityIssuerSerialNumberMismatch
NoPeerCertificate
HostNameMismatch
NoSslSupport
CertificateBlacklisted
UnspecifiedError
Definition at line 61 of file qsslerror.h.
                   {
         NoError,
         UnableToGetIssuerCertificate,
         UnableToDecryptCertificateSignature,
         UnableToDecodeIssuerPublicKey,
         CertificateSignatureFailed,
         CertificateNotYetValid,
         CertificateExpired,
         InvalidNotBeforeField,
         InvalidNotAfterField,
         SelfSignedCertificate,
         SelfSignedCertificateInChain,
         UnableToGetLocalIssuerCertificate,
         UnableToVerifyFirstCertificate,
         CertificateRevoked,
         InvalidCaCertificate,
         PathLengthExceeded,
         InvalidPurpose,
         CertificateUntrusted,
         CertificateRejected,
         SubjectIssuerMismatch, // hostname mismatch?
         AuthorityIssuerSerialNumberMismatch,
         NoPeerCertificate,
         HostNameMismatch,
         NoSslSupport,
         CertificateBlacklisted,
         UnspecifiedError = -1
     };
Constructors and Destructors
QSslError() [1/4]
QSslError::QSslError ()
Constructs a QSslError object with no error and default certificate.
Definition at line 122 of file qsslerror.cpp.
Referenced by operator<<().
     : d(new QSslErrorPrivate)
 {
     d->error = QSslError::NoError;
     d->certificate = QSslCertificate();
 }
QSslError() [2/4]
QSslError::QSslError (SslError error)
Constructs a QSslError object.
The argument specifies the error that occurred.
Definition at line 134 of file qsslerror.cpp.
     : d(new QSslErrorPrivate)
 {
     d->error = error;
     d->certificate = QSslCertificate();
 }
QSslError() [3/4]
QSslError::QSslError (SslError error, const QSslCertificate & certificate)
Constructs a QSslError object.
The two arguments specify the error that occurred, and which certificate the error relates to.
See also
QSslCertificate
Definition at line 147 of file qsslerror.cpp.
     : d(new QSslErrorPrivate)
 {
     d->error = error;
     d->certificate = certificate;
 }
QSslError() [4/4]
QSslError::QSslError (const QSslError & other)
Constructs an identical copy of other.
Definition at line 157 of file qsslerror.cpp.
     : d(new QSslErrorPrivate)
 {
     *d.data() = *other.d.data();
 }
~QSslError()
QSslError::~QSslError ()
Destroys the QSslError object.
Definition at line 166 of file qsslerror.cpp.
 {
 }
Functions
certificate()
QSslCertificate QSslError::certificate () const
Returns the certificate associated with this error, or a null certificate if the error does not relate to any certificate.
See also
error(), errorString()
Definition at line 317 of file qsslerror.cpp.
Referenced by QSslError().
 {
     return d->certificate;
 }
error()
QSslError::SslError QSslError::error () const
Returns the type of the error.
See also
errorString(), certificate()
Definition at line 214 of file qsslerror.cpp.
Referenced by QSslError().
 {
     return d->error;
 }
errorString()
QString QSslError::errorString () const
Returns a short localized human-readable description of the error.
See also
error(), certificate()
Definition at line 224 of file qsslerror.cpp.
Referenced by operator<<(), and QSslSocketBackendPrivate::startHandshake().
 {
     QString errStr;
     switch (d->error) {
     case NoError:
         errStr = QSslSocket::tr("No error");
         break;
     case UnableToGetIssuerCertificate:
         errStr = QSslSocket::tr("The issuer certificate could not be found");
         break;
     case UnableToDecryptCertificateSignature:
         errStr = QSslSocket::tr("The certificate signature could not be decrypted");
         break;
     case UnableToDecodeIssuerPublicKey:
         errStr = QSslSocket::tr("The public key in the certificate could not be read");
         break;
     case CertificateSignatureFailed:
         errStr = QSslSocket::tr("The signature of the certificate is invalid");
         break;
     case CertificateNotYetValid:
         errStr = QSslSocket::tr("The certificate is not yet valid");
         break;
     case CertificateExpired:
         errStr = QSslSocket::tr("The certificate has expired");
         break;
     case InvalidNotBeforeField:
         errStr = QSslSocket::tr("The certificate's notBefore field contains an invalid time");
         break;
     case InvalidNotAfterField:
         errStr = QSslSocket::tr("The certificate's notAfter field contains an invalid time");
         break;
     case SelfSignedCertificate:
         errStr = QSslSocket::tr("The certificate is self-signed, and untrusted");
         break;
     case SelfSignedCertificateInChain:
         errStr = QSslSocket::tr("The root certificate of the certificate chain is self-signed, and untrusted");
         break;
     case UnableToGetLocalIssuerCertificate:
         errStr = QSslSocket::tr("The issuer certificate of a locally looked up certificate could not be found");
         break;
     case UnableToVerifyFirstCertificate:
         errStr = QSslSocket::tr("No certificates could be verified");
         break;
     case InvalidCaCertificate:
         errStr = QSslSocket::tr("One of the CA certificates is invalid");
         break;
     case PathLengthExceeded:
         errStr = QSslSocket::tr("The basicConstraints path length parameter has been exceeded");
         break;
     case InvalidPurpose:
         errStr = QSslSocket::tr("The supplied certificate is unsuitable for this purpose");
         break;
     case CertificateUntrusted:
         errStr = QSslSocket::tr("The root CA certificate is not trusted for this purpose");
         break;
     case CertificateRejected:
         errStr = QSslSocket::tr("The root CA certificate is marked to reject the specified purpose");
         break;
     case SubjectIssuerMismatch: // hostname mismatch
         errStr = QSslSocket::tr("The current candidate issuer certificate was rejected because its"
                                 " subject name did not match the issuer name of the current certificate");
         break;
     case AuthorityIssuerSerialNumberMismatch:
         errStr = QSslSocket::tr("The current candidate issuer certificate was rejected because"
                              " its issuer name and serial number was present and did not match the"
                              " authority key identifier of the current certificate");
         break;
     case NoPeerCertificate:
         errStr = QSslSocket::tr("The peer did not present any certificate");
         break;
     case HostNameMismatch:
         errStr = QSslSocket::tr("The host name did not match any of the valid hosts"
                              " for this certificate");
         break;
     case NoSslSupport:
         break;
     case CertificateBlacklisted:
         errStr = QSslSocket::tr("The peer certificate is blacklisted");
         break;
     default:
         errStr = QSslSocket::tr("Unknown error");
         break;
     }
     return errStr;
 }
operator!=()
bool QSslError::operator!= (const QSslError & other) const inline
Returns true if this error is not equal to other; otherwise returns false.
Since
4.4
Definition at line 101 of file qsslerror.h.
     { return !(*this == other); }
operator=()
QSslError & QSslError::operator= (const QSslError & other)
Assigns the contents of other to this error.
Since
4.4
Definition at line 178 of file qsslerror.cpp.
 {
     *d.data() = *other.d.data();
     return *this;
 }
operator==()
bool QSslError::operator== (const QSslError & other) const
Returns true if this error is equal to other; otherwise returns false.
Since
4.4
Definition at line 192 of file qsslerror.cpp.
 {
     return d->error == other.d->error
         && d->certificate == other.d->certificate;
 }
Properties
d
QScopedPointer<QSslErrorPrivate> QSslError::d private
Definition at line 109 of file qsslerror.h.
Referenced by certificate(), error(), errorString(), operator=(), operator==(), and QSslError().
The documentation for this class was generated from the following files:
/src/network/ssl/qsslerror.h
/src/network/ssl/qsslerror.cpp