Qt 4.8: QXmlItem Class Reference
QXmlItem Class Reference
The QXmlItem class contains either an XML node or an atomic value.
#include <qabstractxmlnodemodel.h>
Public Types
typedef QAbstractXmlForwardIterator< QXmlItem > Iterator
A QAbstractXmlForwardIterator over QXmlItem.
Public Functions
bool isAtomicValue () const
Returns true if this item is an atomic value.
bool isNode () const
Returns true if this item is a Node.
bool isNull () const
Returns true if this QXmlItem is neither a node nor an atomic value.
QXmlItem & operator= (const QXmlItem &other)
Assigns other to this.
QXmlItem ()
Constructs a null QXmlItem that is neither a node nor an atomic value.
QXmlItem (const QXmlItem &other)
The copy constructor constructs a copy of other.
QXmlItem (const QXmlNodeModelIndex &node)
Constructs a node QXmlItem that is a copy of node.
QXmlItem (const QVariant &atomicValue)
Constructs an atomic value QXmlItem with atomicValue.
QVariant toAtomicValue () const
If this QXmlItem represents an atomic value, it is converted to an appropriate QVariant and returned.
QXmlNodeModelIndex toNodeModelIndex () const
If this QXmlItem represents a node, it returns the item as a QXmlNodeModelIndex.
~QXmlItem ()
Destructor.
Private Functions
bool internalIsAtomicValue () const
QXmlItem (const QPatternist::Item &i)
Properties
union {
const QPatternist::AtomicValue * m_atomicValue
QPatternist::NodeIndexStorage m_node
QXmlItemPrivate * m_ptr
};
Friends
class QPatternist::Item
class QPatternist::IteratorBridge
class QPatternist::ToItemMapper
class QPatternist::ToQXmlItemMapper
class QPatternist::VariableLoader
Detailed Description
The QXmlItem class contains either an XML node or an atomic value.
Note
This class or function is reentrant.
Since
4.4
In XQuery, all expressions evaluate to a sequence of items, where each item is either an XML node or an atomic value. The query in the following snippet evaluates to sequence of five items.
<aNode/>,
xs:base64Binary("FFFF"),
current-date(),
3e3, (: A floating point value :)
attribute {"name"} {()}
The five items are: An element, an atomic value (binary data encoded in base64), a date, a float, and an attribute.
QXmlItem is the class that represents these XQuery items in the QtXmlPatterns API. A non-null instance of QXmlItem is either a node or an atomic value. Calling isNode() or isAtomicValue() tells you which it is. Atomic values are represented elsewhere in the Qt API as instances of QVariant, and an instance of QXmlItem that represents an atomic value can be converted to a QVariant by calling toAtomicValue(). A QXmlItem that wraps a node is represented elsewhere as an instance of QXmlNodeModelIndex. A node QXmlItem can be converted to a QXmlNodeModelIndex by calling toNodeModelIndex().
A default constructed QXmlItem instance is neither a node nor an atomic value. It is considered null, in which case isNull() returns true.
An instance of QXmlItem will be left dangling if the XML node model it refers to is deleted, if it is a QXmlNodeModelIndex.
Definition at line 380 of file qabstractxmlnodemodel.h.
Typedefs
Iterator
QXmlItem::Iterator
A QAbstractXmlForwardIterator over QXmlItem.
Definition at line 383 of file qabstractxmlnodemodel.h.
Constructors and Destructors
QXmlItem() [1/5]
QXmlItem::QXmlItem ()
Constructs a null QXmlItem that is neither a node nor an atomic value.
isNull() returns true for a default constructed instance.
Definition at line 1207 of file qabstractxmlnodemodel.cpp.
 {
     m_node.reset();
 }
QXmlItem() [2/5]
QXmlItem::QXmlItem (const QXmlItem & other)
The copy constructor constructs a copy of other.
Definition at line 1220 of file qabstractxmlnodemodel.cpp.
                                         : m_node(other.m_node)
 {
     if(internalIsAtomicValue())
         m_atomicValue->ref.ref();
 }
QXmlItem() [3/5]
QXmlItem::QXmlItem (const QXmlNodeModelIndex & node)
Constructs a node QXmlItem that is a copy of node.
See also
isNode()
Definition at line 1263 of file qabstractxmlnodemodel.cpp.
                                                  : m_node(node.m_storage)
 {
 }
QXmlItem() [4/5]
QXmlItem::QXmlItem (const QVariant & atomicValue)
Constructs an atomic value QXmlItem with atomicValue.
See also
isAtomicValue()
Definition at line 1231 of file qabstractxmlnodemodel.cpp.
 {
     m_node.reset();
     if(atomicValue.isNull())
     {
         /* Then we behave just like the default constructor. */
         return;
     }
     /*
       We can't assign directly to m_atomicValue, because the
       temporary will self-destruct before we've ref'd it.
     */
     const QPatternist::Item temp(QPatternist::AtomicValue::toXDM(atomicValue));
     if(temp)
     {
         temp.asAtomicValue()->ref.ref();
         m_node.model = reinterpret_cast<const QAbstractXmlNodeModel *>(~0);
         m_atomicValue = temp.asAtomicValue();
     }
     else
     {
         m_atomicValue = 0;
     }
 }
~QXmlItem()
QXmlItem::~QXmlItem ()
Destructor.
Definition at line 1271 of file qabstractxmlnodemodel.cpp.
 {
     if(internalIsAtomicValue() && !m_atomicValue->ref.deref())
         delete m_atomicValue;
 }
QXmlItem() [5/5]
QXmlItem::QXmlItem (const QPatternist::Item & i) inline private
Definition at line 524 of file qitem_p.h.
                                                       : m_node(i.node)
     {
         if(isAtomicValue())
             m_atomicValue->ref.ref();
     }
Functions
internalIsAtomicValue()
bool QXmlItem::internalIsAtomicValue () const inline private
Definition at line 1212 of file qabstractxmlnodemodel.cpp.
Referenced by isAtomicValue(), operator=(), QXmlItem(), and ~QXmlItem().
 {
     return m_node.model == reinterpret_cast<QAbstractXmlNodeModel *>(~0);
 }
isAtomicValue()
bool QXmlItem::isAtomicValue () const
Returns true if this item is an atomic value.
Returns false if it is a node or null.
See also
isNull(), isNode()
Definition at line 1320 of file qabstractxmlnodemodel.cpp.
Referenced by QPatternist::VariableLoader::isSameType(), QPatternist::AtomicValue::qtToXDMType(), QXmlItem(), and toAtomicValue().
 {
     return internalIsAtomicValue();
 }
isNode()
bool QXmlItem::isNode () const
Returns true if this item is a Node.
Returns false if it is an atomic value or null.
See also
isNull(), isAtomicValue()
Definition at line 1309 of file qabstractxmlnodemodel.cpp.
Referenced by QPatternist::VariableLoader::isSameType(), QPatternist::AtomicValue::qtToXDMType(), and toNodeModelIndex().
 {
     return QPatternist::Item::fromPublic(*this).isNode();
 }
isNull()
bool QXmlItem::isNull () const
Returns true if this QXmlItem is neither a node nor an atomic value.
Default constructed instances of QXmlItem are null.
Definition at line 1363 of file qabstractxmlnodemodel.cpp.
Referenced by QXmlQuery::bindVariable(), QXmlQueryPrivate::dynamicContext(), QPatternist::FieldNode::isEmpty(), qIsForwardIteratorEnd(), QPatternist::AtomicValue::qtToXDMType(), QPatternist::XsdValidatingInstanceReader::selectNodeSets(), and QXmlQueryPrivate::staticContext().
 {
     return !m_node.model;
 }
operator=()
QXmlItem & QXmlItem::operator= (const QXmlItem & other)
Assigns other to this.
Definition at line 1287 of file qabstractxmlnodemodel.cpp.
 {
     if(m_node != other.m_node)
     {
         if(internalIsAtomicValue() && !m_atomicValue->ref.deref())
             delete m_atomicValue;
         m_node = other.m_node;
         if(internalIsAtomicValue())
             m_atomicValue->ref.ref();
     }
     return *this;
 }
toAtomicValue()
QVariant QXmlItem::toAtomicValue () const
If this QXmlItem represents an atomic value, it is converted to an appropriate QVariant and returned.
If this QXmlItem is not an atomic value, the return value is a default constructed QVariant. You can call isAtomicValue() to test whether the item is an atomic value.
See also
isAtomicValue()
Definition at line 1334 of file qabstractxmlnodemodel.cpp.
Referenced by QDeclarativeXmlQueryEngine::doQueryJob(), QPatternist::VariableLoader::isSameType(), and QPatternist::AtomicValue::qtToXDMType().
 {
     if(isAtomicValue())
         return QPatternist::AtomicValue::toQt(m_atomicValue);
     else
         return QVariant();
 }
toNodeModelIndex()
QXmlNodeModelIndex QXmlItem::toNodeModelIndex () const
If this QXmlItem represents a node, it returns the item as a QXmlNodeModelIndex.
If this QXmlItem is not a node, the return value is undefined. You can call isNode() to test whether the item is a node.
See also
isNode()
Definition at line 1350 of file qabstractxmlnodemodel.cpp.
Referenced by QPatternist::XsdInstanceReader::convertToQName(), QPatternist::TargetNode::operator==(), QPatternist::qHash(), QPatternist::XsdValidatingInstanceReader::read(), and QPatternist::XsdValidatingInstanceReader::validateKeyIdentityConstraint().
 {
     if(isNode())
         return reinterpret_cast<const QXmlNodeModelIndex &>(m_node);
     else
         return QXmlNodeModelIndex();
 }
Friends and Related Functions
QPatternist::Item
friend class QPatternist::Item friend
Definition at line 404 of file qabstractxmlnodemodel.h.
QPatternist::IteratorBridge
friend class QPatternist::IteratorBridge friend
Definition at line 400 of file qabstractxmlnodemodel.h.
QPatternist::ToItemMapper
friend class QPatternist::ToItemMapper friend
Definition at line 403 of file qabstractxmlnodemodel.h.
QPatternist::ToQXmlItemMapper
friend class QPatternist::ToQXmlItemMapper friend
Definition at line 402 of file qabstractxmlnodemodel.h.
QPatternist::VariableLoader
friend class QPatternist::VariableLoader friend
Definition at line 401 of file qabstractxmlnodemodel.h.
Properties
@371
union { ... }
m_atomicValue
const QPatternist::AtomicValue* QXmlItem::m_atomicValue
Definition at line 416 of file qabstractxmlnodemodel.h.
Referenced by operator=(), QXmlItem(), toAtomicValue(), and ~QXmlItem().
m_node
QPatternist::NodeIndexStorage QXmlItem::m_node
Definition at line 412 of file qabstractxmlnodemodel.h.
Referenced by QPatternist::Item::fromPublic(), isNull(), operator=(), QXmlItem(), and toNodeModelIndex().
m_ptr
QXmlItemPrivate* QXmlItem::m_ptr
Definition at line 417 of file qabstractxmlnodemodel.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qabstractxmlnodemodel.h
/src/xmlpatterns/api/qabstractxmlnodemodel.cpp
/src/xmlpatterns/data/qitem_p.h