Qt 4.8: QPatternist::XsdSimpleType Class Reference
QPatternist::XsdSimpleType Class Reference
XML Schema Processing
Represents a XSD simpleType object.
#include <qxsdsimpletype_p.h>
Public Types
typedef QExplicitlySharedDataPointer< XsdSimpleType > Ptr
Public Types inherited from QPatternist::XsdUserSchemaType< AnySimpleType >
typedef QExplicitlySharedDataPointer< XsdUserSchemaType > Ptr
Public Types inherited from QPatternist::AnySimpleType
typedef QList< AnySimpleType::Ptr > List
typedef QExplicitlySharedDataPointer< AnySimpleType > Ptr
Public Types inherited from QPatternist::AnyType
typedef QExplicitlySharedDataPointer< AnyType > Ptr
Public Types inherited from QPatternist::SchemaType
enum DerivationConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, ListConstraint = 4, UnionConstraint = 8 }
enum DerivationMethod {
DerivationRestriction = 1, DerivationExtension = 2, DerivationUnion = 4, DerivationList = 8,
NoDerivation = 16
}
typedef QHash< QXmlName, SchemaType::Ptr > Hash
typedef QList< SchemaType::Ptr > List
typedef QExplicitlySharedDataPointer< SchemaType > Ptr
enum TypeCategory {
None = 0, SimpleTypeAtomic, SimpleTypeList, SimpleTypeUnion,
ComplexType
}
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
virtual TypeCategory category () const
NamedSchemaComponent::Ptr context () const
virtual DerivationMethod derivationMethod () const
virtual QString displayName (const NamePool::Ptr &namePool) const
XsdFacet::Hash facets () const
virtual bool isDefinedBySchema () const
AnySimpleType::Ptr itemType () const
AnySimpleType::List memberTypes () const
AnySimpleType::Ptr primitiveType () const
void setCategory (TypeCategory category)
void setContext (const NamedSchemaComponent::Ptr &component)
void setDerivationMethod (DerivationMethod method)
void setFacets (const XsdFacet::Hash &facets)
void setItemType (const AnySimpleType::Ptr &type)
void setMemberTypes (const AnySimpleType::List &types)
void setPrimitiveType (const AnySimpleType::Ptr &type)
void setWxsSuperType (const SchemaType::Ptr &type)
virtual SchemaType::Ptr wxsSuperType () const
Public Functions inherited from QPatternist::XsdUserSchemaType< AnySimpleType >
SchemaType::DerivationConstraints derivationConstraints () const
virtual QXmlName name (const NamePool::Ptr &namePool) const
void setDerivationConstraints (const SchemaType::DerivationConstraints &constraints)
void setName (const QXmlName &name)
Public Functions inherited from QPatternist::AnySimpleType
virtual bool isComplexType () const
virtual bool isSimpleType () const
virtual ~AnySimpleType ()
Public Functions inherited from QPatternist::AnyType
virtual bool isAbstract () const
virtual bool wxsTypeMatches (const SchemaType::Ptr &other) const
virtual ~AnyType ()
Public Functions inherited from QPatternist::SchemaType
SchemaType ()
virtual ~SchemaType ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::NamedSchemaComponent
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Properties
NamedSchemaComponent * m_context
DerivationMethod m_derivationMethod
XsdFacet::Hash m_facets
AnySimpleType::Ptr m_itemType
AnySimpleType::List m_memberTypes
AnySimpleType::Ptr m_primitiveType
SchemaType::Ptr m_superType
TypeCategory m_typeCategory
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::AnySimpleType
AnySimpleType ()
Protected Functions inherited from QPatternist::AnyType
AnyType ()
This constructor is protected, because this class must be sub-classed.
Detailed Description
Represents a XSD simpleType object.
This class represents the simpleType object of a XML schema as described here.
It contains information from either a top-level simple type declaration (as child of a schema object) or a local simple type declaration (as descendant of an element or complexType object).
See also
XML Schema API reference
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 80 of file qxsdsimpletype_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<XsdSimpleType> QPatternist::XsdSimpleType::Ptr
Definition at line 83 of file qxsdsimpletype_p.h.
Functions
category()
XsdSimpleType::TypeCategory XsdSimpleType::category () const virtual
Returns the category (variety) of the simple type.
Reimplemented from QPatternist::AnySimpleType.
Definition at line 128 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkCircularInheritances(), QPatternist::XsdSchemaChecker::checkSimpleDerivationRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), hasCircularUnionInheritance(), QPatternist::XsdTypeChecker::isValidString(), matchesType(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), and setCategory().
 {
     return m_typeCategory;
 }
context()
NamedSchemaComponent::Ptr XsdSimpleType::context () const
Returns the context component of the simple type.
Definition at line 78 of file qxsdsimpletype.cpp.
 {
     return NamedSchemaComponent::Ptr(m_context);
 }
derivationMethod()
XsdSimpleType::DerivationMethod XsdSimpleType::derivationMethod () const virtual
Returns the derivation method of the simple type.
Reimplemented from QPatternist::AnySimpleType.
Definition at line 138 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkConstrainingFacets(), and QPatternist::XsdSchemaResolver::resolveSimpleRestrictions().
 {
     return m_derivationMethod;
 }
displayName()
QString XsdSimpleType::displayName (const NamePool::Ptr & namePool) const virtual
Returns the display name of the simple type.
Parameters
namePool The name pool the type name is stored in.
Reimplemented from QPatternist::XsdUserSchemaType< AnySimpleType >.
Definition at line 58 of file qxsdsimpletype.cpp.
 {
     return np->displayName(name(np));
 }
facets()
XsdFacet::Hash XsdSimpleType::facets () const
Returns the facets of the simple type.
Definition at line 118 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), QPatternist::XsdSchemaContext::facetsForType(), QPatternist::XsdSchemaHelper::isSimpleDerivationOk(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), and setFacets().
 {
     return m_facets;
 }
isDefinedBySchema()
bool XsdSimpleType::isDefinedBySchema () const virtual
Always returns true.
Reimplemented from QPatternist::SchemaType.
Definition at line 143 of file qxsdsimpletype.cpp.
 {
     return true;
 }
itemType()
AnySimpleType::Ptr XsdSimpleType::itemType () const
Returns the list item type of the simple type or an empty pointer if the category is not SimpleTypeList.
Definition at line 98 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkSimpleDerivationRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), comparableType(), QPatternist::XsdTypeChecker::isValidString(), matchesType(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), and QPatternist::XsdTypeChecker::valuesAreEqual().
 {
     return m_itemType;
 }
memberTypes()
AnySimpleType::List XsdSimpleType::memberTypes () const
Returns the list member types of the simple type or an empty list if the category is not SimpleTypeUnion.
Definition at line 108 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkCircularInheritances(), QPatternist::XsdTypeChecker::checkConstrainingFacetsUnion(), QPatternist::XsdSchemaChecker::checkSimpleDerivationRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), comparableType(), hasCircularUnionInheritance(), QPatternist::XsdSchemaHelper::isSimpleDerivationOk(), QPatternist::XsdTypeChecker::isValidString(), matchesType(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), QPatternist::XsdSchemaResolver::resolveSimpleUnionTypes(), and QPatternist::XsdTypeChecker::valuesAreEqual().
 {
     return m_memberTypes;
 }
primitiveType()
AnySimpleType::Ptr XsdSimpleType::primitiveType () const
Returns the primitive type of the simple type or an empty pointer if the category is not SimpleTypeAtomic.
Definition at line 88 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdSchemaChecker::checkElementConstraints(), comparableType(), QPatternist::XsdSchemaDebugger::dumpType(), QPatternist::XsdTypeChecker::isValidString(), and QPatternist::XsdValidatingInstanceReader::selectNodeSets().
 {
     return m_primitiveType;
 }
setCategory()
void XsdSimpleType::setCategory (TypeCategory category)
Sets the category (variety) of the simple type.
See also
Variety Definition
Definition at line 123 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaParser::parseGlobalSimpleType(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalSimpleType(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), and QPatternist::XsdSchemaTypesFactory::XsdSchemaTypesFactory().
 {
     m_typeCategory = category;
 }
setContext()
void XsdSimpleType::setContext (const NamedSchemaComponent::Ptr & component)
Sets the context component of the simple type.
See also
Context Definition
Definition at line 73 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), and QPatternist::XsdSchemaParser::parseUnion().
 {
     m_context = component.data();
 }
setDerivationMethod()
void XsdSimpleType::setDerivationMethod (DerivationMethod method)
Sets the derivation method of the simple type.
See also
DerivationMethod
Definition at line 133 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), and QPatternist::XsdSchemaTypesFactory::XsdSchemaTypesFactory().
 {
     m_derivationMethod = method;
 }
setFacets()
void XsdSimpleType::setFacets (const XsdFacet::Hash & facets)
Sets the facets of the simple type.
See also
Facets Definition
Definition at line 113 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), and QPatternist::XsdSchemaTypesFactory::XsdSchemaTypesFactory().
 {
     m_facets = facets;
 }
setItemType()
void XsdSimpleType::setItemType (const AnySimpleType::Ptr & type)
Sets the list item type of the simple type.
The list item type is only specified if the category is SimpleTypeList.
See also
Item Type Definition
Definition at line 93 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleListType(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), and QPatternist::XsdSchemaTypesFactory::XsdSchemaTypesFactory().
 {
     m_itemType = type;
 }
setMemberTypes()
void XsdSimpleType::setMemberTypes (const AnySimpleType::List & types)
Sets the member types of the simple type.
The member types are only specified if the category is SimpleTypeUnion.
See also
Member Types Definition
Definition at line 103 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), and QPatternist::XsdSchemaResolver::resolveSimpleUnionTypes().
 {
     m_memberTypes = types;
 }
setPrimitiveType()
void XsdSimpleType::setPrimitiveType (const AnySimpleType::Ptr & type)
Sets the primitive type of the simple type.
The primitive type is only specified if the category is SimpleTypeAtomic.
See also
Primitive Type Definition
Definition at line 83 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), and QPatternist::XsdSchemaResolver::resolveSimpleRestrictions().
 {
     m_primitiveType = type;
 }
setWxsSuperType()
void XsdSimpleType::setWxsSuperType (const SchemaType::Ptr & type)
Sets the base type of the simple type.
See also
Base Type Definition
Definition at line 63 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictionBaseTypes(), and QPatternist::XsdSchemaTypesFactory::XsdSchemaTypesFactory().
 {
     m_superType = type;
 }
wxsSuperType()
SchemaType::Ptr XsdSimpleType::wxsSuperType () const virtual
Returns the base type of the simple type or an empty pointer if no base type is set.
Reimplemented from QPatternist::AnySimpleType.
Definition at line 68 of file qxsdsimpletype.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkBasicSimpleTypeConstraints(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), QPatternist::XsdTypeChecker::isValidString(), matchesType(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), and QPatternist::XsdSchemaResolver::resolveSimpleRestrictions().
 {
     return m_superType;
 }
Properties
m_context
NamedSchemaComponent* QPatternist::XsdSimpleType::m_context private
Definition at line 205 of file qxsdsimpletype_p.h.
Referenced by context(), and setContext().
m_derivationMethod
DerivationMethod QPatternist::XsdSimpleType::m_derivationMethod private
Definition at line 211 of file qxsdsimpletype_p.h.
Referenced by derivationMethod(), and setDerivationMethod().
m_facets
XsdFacet::Hash QPatternist::XsdSimpleType::m_facets private
Definition at line 209 of file qxsdsimpletype_p.h.
Referenced by facets(), and setFacets().
m_itemType
AnySimpleType::Ptr QPatternist::XsdSimpleType::m_itemType private
Definition at line 207 of file qxsdsimpletype_p.h.
Referenced by itemType(), and setItemType().
m_memberTypes
AnySimpleType::List QPatternist::XsdSimpleType::m_memberTypes private
Definition at line 208 of file qxsdsimpletype_p.h.
Referenced by memberTypes(), and setMemberTypes().
m_primitiveType
AnySimpleType::Ptr QPatternist::XsdSimpleType::m_primitiveType private
Definition at line 206 of file qxsdsimpletype_p.h.
Referenced by primitiveType(), and setPrimitiveType().
m_superType
SchemaType::Ptr QPatternist::XsdSimpleType::m_superType private
Definition at line 204 of file qxsdsimpletype_p.h.
Referenced by setWxsSuperType(), and wxsSuperType().
m_typeCategory
TypeCategory QPatternist::XsdSimpleType::m_typeCategory private
Definition at line 210 of file qxsdsimpletype_p.h.
Referenced by category(), and setCategory().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdsimpletype_p.h
/src/xmlpatterns/schema/qxsdsimpletype.cpp