Qt 4.8: QmlJSDebugger::LiveRubberBandSelectionManipulator Class Reference
QmlJSDebugger::LiveRubberBandSelectionManipulator Class Reference
#include <liverubberbandselectionmanipulator.h>
Public Types
enum SelectionType { ReplaceSelection, AddToSelection, RemoveFromSelection }
Public Functions
void begin (const QPointF &beginPoint)
QPointF beginPoint () const
void clear ()
void end ()
bool isActive () const
LiveRubberBandSelectionManipulator (QGraphicsObject *layerItem, QDeclarativeViewInspector *editorView)
void select (SelectionType selectionType)
void setItems (const QList< QGraphicsItem *> &itemList)
void update (const QPointF &updatePoint)
Protected Functions
QGraphicsItem * topFormEditorItem (const QList< QGraphicsItem *> &itemList)
Properties
QGraphicsItem * m_beginFormEditorItem
QPointF m_beginPoint
QDeclarativeViewInspector * m_editorView
bool m_isActive
QList< QGraphicsItem * > m_itemList
QList< QGraphicsItem * > m_oldSelectionList
LiveSelectionRectangle m_selectionRectangleElement
Detailed Description
Definition at line 55 of file liverubberbandselectionmanipulator.h.
Enumerations
SelectionType
enum QmlJSDebugger::LiveRubberBandSelectionManipulator::SelectionType
Enumerator
ReplaceSelection
AddToSelection
RemoveFromSelection
Definition at line 58 of file liverubberbandselectionmanipulator.h.
{
         ReplaceSelection,
         AddToSelection,
         RemoveFromSelection
     };
Constructors and Destructors
LiveRubberBandSelectionManipulator()
QmlJSDebugger::LiveRubberBandSelectionManipulator::LiveRubberBandSelectionManipulator (QGraphicsObject * layerItem, QDeclarativeViewInspector * editorView)
Definition at line 52 of file liverubberbandselectionmanipulator.cpp.
     : m_selectionRectangleElement(layerItem),
       m_editorView(editorView),
       m_beginFormEditorItem(0),
       m_isActive(false)
 {
     m_selectionRectangleElement.hide();
 }
Functions
begin()
void QmlJSDebugger::LiveRubberBandSelectionManipulator::begin (const QPointF & beginPoint)
Definition at line 80 of file liverubberbandselectionmanipulator.cpp.
Referenced by QmlJSDebugger::ZoomTool::mouseMoveEvent(), and QmlJSDebugger::LiveSelectionTool::mousePressEvent().
 {
     m_beginPoint = beginPoint;
     m_selectionRectangleElement.setRect(m_beginPoint, m_beginPoint);
     m_selectionRectangleElement.show();
     m_isActive = true;
     QDeclarativeViewInspectorPrivate *inspectorPrivate
             = QDeclarativeViewInspectorPrivate::get(m_editorView);
     m_beginFormEditorItem = topFormEditorItem(inspectorPrivate->selectableItems(beginPoint));
     m_oldSelectionList = m_editorView->selectedItems();
 }
beginPoint()
QPointF QmlJSDebugger::LiveRubberBandSelectionManipulator::beginPoint () const
Definition at line 155 of file liverubberbandselectionmanipulator.cpp.
Referenced by begin(), QmlJSDebugger::LiveSelectionTool::mouseMoveEvent(), QmlJSDebugger::ZoomTool::mouseReleaseEvent(), and QmlJSDebugger::LiveSelectionTool::mouseReleaseEvent().
 {
     return m_beginPoint;
 }
clear()
void QmlJSDebugger::LiveRubberBandSelectionManipulator::clear (void)
Definition at line 62 of file liverubberbandselectionmanipulator.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::clear().
 {
     m_selectionRectangleElement.clear();
     m_isActive = false;
     m_beginPoint = QPointF();
     m_itemList.clear();
     m_oldSelectionList.clear();
 }
end()
void QmlJSDebugger::LiveRubberBandSelectionManipulator::end ()
Definition at line 97 of file liverubberbandselectionmanipulator.cpp.
Referenced by QmlJSDebugger::ZoomTool::mouseReleaseEvent(), and QmlJSDebugger::LiveSelectionTool::mouseReleaseEvent().
 {
     m_oldSelectionList.clear();
     m_selectionRectangleElement.hide();
     m_isActive = false;
 }
isActive()
bool QmlJSDebugger::LiveRubberBandSelectionManipulator::isActive () const
Definition at line 160 of file liverubberbandselectionmanipulator.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::mouseMoveEvent(), and QmlJSDebugger::LiveSelectionTool::mouseReleaseEvent().
 {
     return m_isActive;
 }
select()
void QmlJSDebugger::LiveRubberBandSelectionManipulator::select (SelectionType selectionType)
Definition at line 104 of file liverubberbandselectionmanipulator.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::mouseMoveEvent(), and QmlJSDebugger::LiveSelectionTool::mouseReleaseEvent().
 {
     QDeclarativeViewInspectorPrivate *inspectorPrivate
             = QDeclarativeViewInspectorPrivate::get(m_editorView);
     QList<QGraphicsItem*> itemList
             = inspectorPrivate->selectableItems(m_selectionRectangleElement.rect(),
                                                Qt::IntersectsItemShape);
     QList<QGraphicsItem*> newSelectionList;
     foreach (QGraphicsItem* item, itemList) {
         if (item
                 && item->parentItem()
                 && !newSelectionList.contains(item)
                 //&& m_beginFormEditorItem->childItems().contains(item) // TODO activate this test
                 )
         {
             newSelectionList.append(item);
         }
     }
     if (newSelectionList.isEmpty() && m_beginFormEditorItem)
         newSelectionList.append(m_beginFormEditorItem);
     QList<QGraphicsItem*> resultList;
     switch (selectionType) {
     case AddToSelection: {
         resultList.append(m_oldSelectionList);
         resultList.append(newSelectionList);
     }
         break;
     case ReplaceSelection: {
         resultList.append(newSelectionList);
     }
         break;
     case RemoveFromSelection: {
         QSet<QGraphicsItem*> oldSelectionSet(m_oldSelectionList.toSet());
         QSet<QGraphicsItem*> newSelectionSet(newSelectionList.toSet());
         resultList.append(oldSelectionSet.subtract(newSelectionSet).toList());
     }
     }
     m_editorView->setSelectedItems(resultList);
 }
setItems()
void QmlJSDebugger::LiveRubberBandSelectionManipulator::setItems (const QList< QGraphicsItem *> & itemList)
Definition at line 150 of file liverubberbandselectionmanipulator.cpp.
 {
     m_itemList = itemList;
 }
topFormEditorItem()
QGraphicsItem * QmlJSDebugger::LiveRubberBandSelectionManipulator::topFormEditorItem (const QList< QGraphicsItem *> & itemList) protected
Definition at line 71 of file liverubberbandselectionmanipulator.cpp.
Referenced by begin().
 {
     if (itemList.isEmpty())
         return 0;
     return itemList.first();
 }
update()
void QmlJSDebugger::LiveRubberBandSelectionManipulator::update (const QPointF & updatePoint)
Definition at line 92 of file liverubberbandselectionmanipulator.cpp.
Referenced by QmlJSDebugger::ZoomTool::mouseMoveEvent(), QmlJSDebugger::LiveSelectionTool::mouseMoveEvent(), and QmlJSDebugger::LiveSelectionTool::mouseReleaseEvent().
 {
     m_selectionRectangleElement.setRect(m_beginPoint, updatePoint);
 }
Properties
m_beginFormEditorItem
QGraphicsItem* QmlJSDebugger::LiveRubberBandSelectionManipulator::m_beginFormEditorItem private
Definition at line 90 of file liverubberbandselectionmanipulator.h.
Referenced by begin(), and select().
m_beginPoint
QPointF QmlJSDebugger::LiveRubberBandSelectionManipulator::m_beginPoint private
Definition at line 88 of file liverubberbandselectionmanipulator.h.
Referenced by begin(), beginPoint(), clear(), and update().
m_editorView
QDeclarativeViewInspector* QmlJSDebugger::LiveRubberBandSelectionManipulator::m_editorView private
Definition at line 89 of file liverubberbandselectionmanipulator.h.
Referenced by begin(), and select().
m_isActive
bool QmlJSDebugger::LiveRubberBandSelectionManipulator::m_isActive private
Definition at line 91 of file liverubberbandselectionmanipulator.h.
Referenced by begin(), clear(), end(), and isActive().
m_itemList
QList<QGraphicsItem*> QmlJSDebugger::LiveRubberBandSelectionManipulator::m_itemList private
Definition at line 85 of file liverubberbandselectionmanipulator.h.
Referenced by clear(), and setItems().
m_oldSelectionList
QList<QGraphicsItem*> QmlJSDebugger::LiveRubberBandSelectionManipulator::m_oldSelectionList private
Definition at line 86 of file liverubberbandselectionmanipulator.h.
Referenced by begin(), clear(), end(), and select().
m_selectionRectangleElement
LiveSelectionRectangle QmlJSDebugger::LiveRubberBandSelectionManipulator::m_selectionRectangleElement private
Definition at line 87 of file liverubberbandselectionmanipulator.h.
Referenced by begin(), clear(), end(), LiveRubberBandSelectionManipulator(), select(), and update().
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_inspector/editor/liverubberbandselectionmanipulator.h
/src/plugins/qmltooling/qmldbg_inspector/editor/liverubberbandselectionmanipulator.cpp