Qt 4.8: QNetworkManagerInterface Class Reference
QNetworkManagerInterface Class Reference
#include <qnetworkmanagerservice.h>
Signals
void activationFinished (QDBusPendingCallWatcher *)
void deviceAdded (QDBusObjectPath)
void deviceRemoved (QDBusObjectPath)
void propertiesChanged (const QString &, QMap< QString, QVariant >)
void stateChanged (const QString &, quint32)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void activateConnection (const QString &serviceName, QDBusObjectPath connection, QDBusObjectPath device, QDBusObjectPath specificObject)
QList< QDBusObjectPath > activeConnections () const
QDBusInterface * connectionInterface () const
void deactivateConnection (QDBusObjectPath connectionPath) const
QList< QDBusObjectPath > getDevices () const
bool isValid ()
QDBusObjectPath path () const
QNetworkManagerInterface (QObject *parent=0)
bool setConnections ()
quint32 state ()
bool wirelessEnabled () const
bool wirelessHardwareEnabled () const
~QNetworkManagerInterface ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QNetworkManagerInterfacePrivate * d
QNmDBusHelper * nmDBusHelper
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 139 of file qnetworkmanagerservice.h.
Constructors and Destructors
QNetworkManagerInterface()
QNetworkManagerInterface::QNetworkManagerInterface (QObject * parent = 0)
Definition at line 70 of file qnetworkmanagerservice.cpp.
         : QObject(parent)
 {
     d = new QNetworkManagerInterfacePrivate();
     d->connectionInterface = new QDBusInterface(QLatin1String(NM_DBUS_SERVICE),
                                                 QLatin1String(NM_DBUS_PATH),
                                                 QLatin1String(NM_DBUS_INTERFACE),
                                                 dbusConnection);
     if (!d->connectionInterface->isValid()) {
         d->valid = false;
         return;
     }
     d->valid = true;
     nmDBusHelper = new QNmDBusHelper(this);
     connect(nmDBusHelper, SIGNAL(pathForPropertiesChanged(const QString &,QMap<QString,QVariant>)),
                     this,SIGNAL(propertiesChanged( const QString &, QMap<QString,QVariant>)));
     connect(nmDBusHelper,SIGNAL(pathForStateChanged(const QString &, quint32)),
             this, SIGNAL(stateChanged(const QString&, quint32)));
 }
~QNetworkManagerInterface()
QNetworkManagerInterface::~QNetworkManagerInterface ()
Definition at line 91 of file qnetworkmanagerservice.cpp.
 {
     delete d->connectionInterface;
     delete d;
 }
Functions
activateConnection()
void QNetworkManagerInterface::activateConnection (const QString & serviceName, QDBusObjectPath connection, QDBusObjectPath device, QDBusObjectPath specificObject)
Definition at line 143 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::connectToId().
 {
     QDBusPendingCall pendingCall = d->connectionInterface->asyncCall(QLatin1String("ActivateConnection"),
                                                                     QVariant(serviceName),
                                                                     QVariant::fromValue(connectionPath),
                                                                     QVariant::fromValue(devicePath),
                                                                     QVariant::fromValue(specificObject));
    QDBusPendingCallWatcher *callWatcher = new QDBusPendingCallWatcher(pendingCall, this);
    connect(callWatcher, SIGNAL(finished(QDBusPendingCallWatcher*)),
                     this, SIGNAL(activationFinished(QDBusPendingCallWatcher*)));
 }
activationFinished
void QNetworkManagerInterface::activationFinished (QDBusPendingCallWatcher *) signal
Referenced by activateConnection().
activeConnections()
QList< QDBusObjectPath > QNetworkManagerInterface::activeConnections () const
Definition at line 174 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::disconnectFromId(), QNetworkManagerEngine::getInterfaceFromId(), QNetworkManagerEngine::initialize(), QNetworkManagerEngine::newConnection(), and QNetworkManagerEngine::updateConnection().
 {
     QVariant prop = d->connectionInterface->property("ActiveConnections");
     return prop.value<QList<QDBusObjectPath> >();
 }
connectionInterface()
QDBusInterface * QNetworkManagerInterface::connectionInterface () const
Definition at line 132 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface;
 }
deactivateConnection()
void QNetworkManagerInterface::deactivateConnection (QDBusObjectPath connectionPath) const
Definition at line 159 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::disconnectFromId().
 {
     d->connectionInterface->call(QLatin1String("DeactivateConnection"), QVariant::fromValue(connectionPath));
 }
deviceAdded
void QNetworkManagerInterface::deviceAdded (QDBusObjectPath) signal
Referenced by setConnections().
deviceRemoved
void QNetworkManagerInterface::deviceRemoved (QDBusObjectPath) signal
Referenced by setConnections().
getDevices()
QList< QDBusObjectPath > QNetworkManagerInterface::getDevices () const
Definition at line 137 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::connectToId(), QNetworkManagerEngine::initialize(), and QNetworkManagerEngine::parseConnection().
 {
     QDBusReply<QList<QDBusObjectPath> > reply =  d->connectionInterface->call(QLatin1String("GetDevices"));
     return reply.value();
 }
isValid()
bool QNetworkManagerInterface::isValid ()
Definition at line 97 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::networkManagerAvailable(), QNetworkManagerEngine::QNetworkManagerEngine(), and setConnections().
 {
     return d->valid;
 }
path()
QDBusObjectPath QNetworkManagerInterface::path () const
propertiesChanged
void QNetworkManagerInterface::propertiesChanged (const QString & , QMap< QString, QVariant >) signal
Referenced by QNetworkManagerInterface().
setConnections()
bool QNetworkManagerInterface::setConnections ()
Definition at line 102 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::QNetworkManagerEngine().
 {
     if(!isValid() )
         return false;
     bool allOk = false;
     if (!dbusConnection.connect(QLatin1String(NM_DBUS_SERVICE),
                                   QLatin1String(NM_DBUS_PATH),
                                   QLatin1String(NM_DBUS_INTERFACE),
                                   QLatin1String("PropertiesChanged"),
                                 nmDBusHelper,SLOT(slotPropertiesChanged( QMap<QString,QVariant>)))) {
         allOk = true;
     }
     if (!dbusConnection.connect(QLatin1String(NM_DBUS_SERVICE),
                                   QLatin1String(NM_DBUS_PATH),
                                   QLatin1String(NM_DBUS_INTERFACE),
                                   QLatin1String("DeviceAdded"),
                                 this,SIGNAL(deviceAdded(QDBusObjectPath)))) {
         allOk = true;
     }
     if (!dbusConnection.connect(QLatin1String(NM_DBUS_SERVICE),
                                   QLatin1String(NM_DBUS_PATH),
                                   QLatin1String(NM_DBUS_INTERFACE),
                                   QLatin1String("DeviceRemoved"),
                                   this,SIGNAL(deviceRemoved(QDBusObjectPath)))) {
         allOk = true;
     }
     return allOk;
 }
state()
quint32 QNetworkManagerInterface::state ()
Definition at line 180 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("State").toUInt();
 }
stateChanged
void QNetworkManagerInterface::stateChanged (const QString & , quint32) signal
Referenced by QNetworkManagerInterface().
wirelessEnabled()
bool QNetworkManagerInterface::wirelessEnabled () const
Definition at line 164 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("WirelessEnabled").toBool();
 }
wirelessHardwareEnabled()
bool QNetworkManagerInterface::wirelessHardwareEnabled () const
Definition at line 169 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("WirelessHardwareEnabled").toBool();
 }
Properties
d
QNetworkManagerInterfacePrivate* QNetworkManagerInterface::d private
Definition at line 171 of file qnetworkmanagerservice.h.
Referenced by activateConnection(), activeConnections(), connectionInterface(), deactivateConnection(), getDevices(), isValid(), QNetworkManagerInterface(), state(), wirelessEnabled(), wirelessHardwareEnabled(), and ~QNetworkManagerInterface().
nmDBusHelper
QNmDBusHelper* QNetworkManagerInterface::nmDBusHelper private
Definition at line 172 of file qnetworkmanagerservice.h.
Referenced by QNetworkManagerInterface(), and setConnections().
The documentation for this class was generated from the following files:
/src/plugins/bearer/networkmanager/qnetworkmanagerservice.h
/src/plugins/bearer/networkmanager/qnetworkmanagerservice.cpp