Qt 4.8: QTextBlockGroup Class Reference
QTextBlockGroup Class Reference
The QTextBlockGroup class provides a container for text blocks within a QTextDocument.
#include <qtextobject.h>
Protected Functions
virtual void blockFormatChanged (const QTextBlock &block)
This function is called whenever the specified block of text is changed.
virtual void blockInserted (const QTextBlock &block)
Appends the given block to the end of the group.
QList< QTextBlock > blockList () const
Returns a (possibly empty) list of all the blocks that are part of the block group.
virtual void blockRemoved (const QTextBlock &block)
Removes the given block from the group; the block itself is not deleted, it simply isn't a member of this group anymore.
QTextBlockGroup (QTextDocument *doc)
Creates a new new block group for the given document.
QTextBlockGroup (QTextBlockGroupPrivate &p, QTextDocument *doc)
~QTextBlockGroup ()
Destroys this block group; the blocks are not deleted, they simply don't belong to this block anymore.
Protected Functions inherited from QTextObject
QTextObject (QTextDocument *doc)
Creates a new QTextObject for the given document.
QTextObject (QTextObjectPrivate &p, QTextDocument *doc)
void setFormat (const QTextFormat &format)
Sets the text object's format.
~QTextObject ()
Destroys the text object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Friends
class QTextDocumentPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions inherited from QTextObject
QTextDocumentPrivate * docHandle () const
QTextDocument * document () const
Returns the document this object belongs to.
QTextFormat format () const
Returns the text object's format.
int formatIndex () const
Returns the index of the object's format in the document's internal list of formats.
int objectIndex () const
Returns the object index of this object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QTextBlockGroup class provides a container for text blocks within a QTextDocument.
Note
This class or function is reentrant.
Block groups can be used to organize blocks of text within a document. They maintain an up-to-date list of the text blocks that belong to them, even when text blocks are being edited.
Each group has a parent document which is specified when the group is constructed.
Text blocks can be inserted into a group with blockInserted(), and removed with blockRemoved(). If a block's format is changed, blockFormatChanged() is called.
The list of blocks in the group is returned by blockList(). Note that the blocks in the list are not necessarily adjacent elements in the document; for example, the top-level items in a multi-level list will be separated by the items in lower levels of the list.
See also
QTextBlock QTextDocument
Definition at line 94 of file qtextobject.h.
Constructors and Destructors
QTextBlockGroup() [1/2]
QTextBlockGroup::QTextBlockGroup (QTextDocument * document) explicit protected
Creates a new new block group for the given document.
Warning
This function should only be called from QTextDocument::createObject().
Definition at line 229 of file qtextobject.cpp.
     : QTextObject(*new QTextBlockGroupPrivate(doc), doc)
 {
 }
~QTextBlockGroup()
QTextBlockGroup::~QTextBlockGroup () protected
Destroys this block group; the blocks are not deleted, they simply don't belong to this block anymore.
Definition at line 246 of file qtextobject.cpp.
 {
 }
QTextBlockGroup() [2/2]
QTextBlockGroup::QTextBlockGroup (QTextBlockGroupPrivate & p, QTextDocument * doc) protected
Warning
This function is not part of the public interface.
Definition at line 237 of file qtextobject.cpp.
     : QTextObject(p, doc)
 {
 }
Functions
blockFormatChanged()
void QTextBlockGroup::blockFormatChanged (const QTextBlock & block) protected virtual
This function is called whenever the specified block of text is changed.
The text block is a member of this group.
The base class implementation does nothing.
Definition at line 287 of file qtextobject.cpp.
Referenced by QTextDocumentPrivate::setBlockFormat(), and QTextDocumentPrivate::undoRedo().
 {
 }
blockInserted()
void QTextBlockGroup::blockInserted (const QTextBlock & block) protected virtual
Appends the given block to the end of the group.
Warning
If you reimplement this function you must call the base class implementation.
Definition at line 257 of file qtextobject.cpp.
Referenced by QTextDocumentPrivate::insert_block(), QTextDocumentPrivate::setBlockFormat(), and QTextDocumentPrivate::undoRedo().
 {
     Q_D(QTextBlockGroup);
     QTextBlockGroupPrivate::BlockList::Iterator it = qLowerBound(d->blocks.begin(), d->blocks.end(), block);
     d->blocks.insert(it, block);
     d->markBlocksDirty();
 }
blockList()
QList< QTextBlock > QTextBlockGroup::blockList () const protected
Returns a (possibly empty) list of all the blocks that are part of the block group.
Definition at line 295 of file qtextobject.cpp.
 {
     Q_D(const QTextBlockGroup);
     return d->blocks;
 }
blockRemoved()
void QTextBlockGroup::blockRemoved (const QTextBlock & block) protected virtual
Removes the given block from the group; the block itself is not deleted, it simply isn't a member of this group anymore.
Definition at line 270 of file qtextobject.cpp.
Referenced by QTextDocumentPrivate::remove_block(), QTextDocumentPrivate::setBlockFormat(), and QTextDocumentPrivate::undoRedo().
 {
     Q_D(QTextBlockGroup);
     d->blocks.removeAll(block);
     d->markBlocksDirty();
     if (d->blocks.isEmpty()) {
         document()->docHandle()->deleteObject(this);
         return;
     }
 }
Friends and Related Functions
QTextDocumentPrivate
friend class QTextDocumentPrivate friend
Definition at line 113 of file qtextobject.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextobject.h
/src/gui/text/qtextobject.cpp