Qt 4.8: QSvgNode Class Reference
QSvgNode Class Reference abstract
#include <qsvgnode_p.h>
Public Types
enum DisplayMode {
InlineMode, BlockMode, ListItemMode, RunInMode,
CompactMode, MarkerMode, TableMode, InlineTableMode,
TableRowGroupMode, TableHeaderGroupMode, TableFooterGroupMode, TableRowMode,
TableColumnGroupMode, TableColumnMode, TableCellMode, TableCaptionMode,
NoneMode, InheritMode
}
enum Type {
DOC, G, DEFS, SWITCH,
ANIMATION, ARC, CIRCLE, ELLIPSE,
IMAGE, LINE, PATH, POLYGON,
POLYLINE, RECT, TEXT, TEXTAREA,
TSPAN, USE, VIDEO
}
Public Functions
void appendStyleProperty (QSvgStyleProperty *prop, const QString &id)
void applyStyle (QPainter *p, QSvgExtraStates &states) const
virtual QRectF bounds (QPainter *p, QSvgExtraStates &states) const
DisplayMode displayMode () const
QSvgTinyDocument * document () const
virtual void draw (QPainter *p, QSvgExtraStates &states)=0
bool isVisible () const
QString nodeId () const
QSvgNode * parent () const
QSvgNode (QSvgNode *parent=0)
const QStringList & requiredExtensions () const
const QStringList & requiredFeatures () const
const QStringList & requiredFonts () const
const QStringList & requiredFormats () const
const QStringList & requiredLanguages () const
void revertStyle (QPainter *p, QSvgExtraStates &states) const
void setDisplayMode (DisplayMode display)
void setNodeId (const QString &i)
void setRequiredExtensions (const QStringList &lst)
void setRequiredFeatures (const QStringList &lst)
void setRequiredFonts (const QStringList &lst)
void setRequiredFormats (const QStringList &lst)
void setRequiredLanguages (const QStringList &lst)
void setVisible (bool visible)
void setXmlClass (const QString &str)
QSvgStyleProperty * styleProperty (QSvgStyleProperty::Type type) const
QSvgFillStyleProperty * styleProperty (const QString &id) const
virtual QRectF transformedBounds (QPainter *p, QSvgExtraStates &states) const
QRectF transformedBounds () const
virtual Type type () const =0
QString xmlClass () const
virtual ~QSvgNode ()
Static Protected Functions
static qreal strokeWidth (QPainter *p)
Protected Variables
QSvgStyle m_style
Properties
QRectF m_cachedBounds
QString m_class
DisplayMode m_displayMode
QString m_id
QSvgNode * m_parent
QStringList m_requiredExtensions
QStringList m_requiredFeatures
QStringList m_requiredFonts
QStringList m_requiredFormats
QStringList m_requiredLanguages
bool m_visible
Friends
class QSvgTinyDocument
Detailed Description
Definition at line 68 of file qsvgnode_p.h.
Enumerations
DisplayMode
enum QSvgNode::DisplayMode
Enumerator
InlineMode
BlockMode
ListItemMode
RunInMode
CompactMode
MarkerMode
TableMode
InlineTableMode
TableRowGroupMode
TableHeaderGroupMode
TableFooterGroupMode
TableRowMode
TableColumnGroupMode
TableColumnMode
TableCellMode
TableCaptionMode
NoneMode
InheritMode
Definition at line 93 of file qsvgnode_p.h.
                      {
         InlineMode,
         BlockMode,
         ListItemMode,
         RunInMode,
         CompactMode,
         MarkerMode,
         TableMode,
         InlineTableMode,
         TableRowGroupMode,
         TableHeaderGroupMode,
         TableFooterGroupMode,
         TableRowMode,
         TableColumnGroupMode,
         TableColumnMode,
         TableCellMode,
         TableCaptionMode,
         NoneMode,
         InheritMode
     };
Type
enum QSvgNode::Type
Enumerator
DOC
G
DEFS
SWITCH
ANIMATION
ARC
CIRCLE
ELLIPSE
IMAGE
LINE
PATH
POLYGON
POLYLINE
RECT
TEXT
TEXTAREA
TSPAN
USE
VIDEO
Definition at line 71 of file qsvgnode_p.h.
     {
         DOC,
         G,
         DEFS,
         SWITCH,
         ANIMATION,
         ARC,
         CIRCLE,
         ELLIPSE,
         IMAGE,
         LINE,
         PATH,
         POLYGON,
         POLYLINE,
         RECT,
         TEXT,
         TEXTAREA,
         TSPAN,
         USE,
         VIDEO
     };
Constructors and Destructors
QSvgNode()
QSvgNode::QSvgNode (QSvgNode * parent = 0)
Definition at line 52 of file qsvgnode.cpp.
     : m_parent(parent),
       m_visible(true),
       m_displayMode(BlockMode)
 {
 }
~QSvgNode()
QSvgNode::~QSvgNode () virtual
Definition at line 59 of file qsvgnode.cpp.
 {
 }
Functions
appendStyleProperty()
void QSvgNode::appendStyleProperty (QSvgStyleProperty * prop, const QString & id)
Definition at line 64 of file qsvgnode.cpp.
Referenced by parseAnimateColorNode(), parseAnimateTransformNode(), parseBrush(), parseCompOp(), parseFont(), parseOpacity(), parsePen(), parseTransform(), and QSvgHandler::startElement().
 {
     //qDebug()<<"appending "<<prop->type()<< " ("<< id <<") "<<"to "<<this<<this->type();
     QSvgTinyDocument *doc;
     switch (prop->type()) {
     case QSvgStyleProperty::QUALITY:
         m_style.quality = static_cast<QSvgQualityStyle*>(prop);
         break;
     case QSvgStyleProperty::FILL:
         m_style.fill = static_cast<QSvgFillStyle*>(prop);
         break;
     case QSvgStyleProperty::VIEWPORT_FILL:
         m_style.viewportFill = static_cast<QSvgViewportFillStyle*>(prop);
         break;
     case QSvgStyleProperty::FONT:
         m_style.font = static_cast<QSvgFontStyle*>(prop);
         break;
     case QSvgStyleProperty::STROKE:
         m_style.stroke = static_cast<QSvgStrokeStyle*>(prop);
         break;
     case QSvgStyleProperty::SOLID_COLOR:
         m_style.solidColor = static_cast<QSvgSolidColorStyle*>(prop);
         doc = document();
         if (doc && !id.isEmpty())
             doc->addNamedStyle(id, m_style.solidColor);
         break;
     case QSvgStyleProperty::GRADIENT:
         m_style.gradient = static_cast<QSvgGradientStyle*>(prop);
         doc = document();
         if (doc && !id.isEmpty())
             doc->addNamedStyle(id, m_style.gradient);
         break;
     case QSvgStyleProperty::TRANSFORM:
         m_style.transform = static_cast<QSvgTransformStyle*>(prop);
         break;
     case QSvgStyleProperty::ANIMATE_COLOR:
         m_style.animateColor = static_cast<QSvgAnimateColor*>(prop);
         break;
     case QSvgStyleProperty::ANIMATE_TRANSFORM:
         m_style.animateTransforms.append(
             static_cast<QSvgAnimateTransform*>(prop));
         break;
     case QSvgStyleProperty::OPACITY:
         m_style.opacity = static_cast<QSvgOpacityStyle*>(prop);
         break;
     case QSvgStyleProperty::COMP_OP:
         m_style.compop = static_cast<QSvgCompOpStyle*>(prop);
         break;
     default:
         qDebug("QSvgNode: Trying to append unknown property!");
         break;
     }
 }
applyStyle()
void QSvgNode::applyStyle (QPainter * p, QSvgExtraStates & states) const
Definition at line 118 of file qsvgnode.cpp.
Referenced by QSvgArc::draw(), QSvgG::draw(), QSvgEllipse::draw(), QSvgTinyDocument::draw(), QSvgSwitch::draw(), QSvgImage::draw(), QSvgLine::draw(), QSvgPath::draw(), QSvgPolygon::draw(), QSvgPolyline::draw(), QSvgRect::draw(), QSvgText::draw(), QSvgUse::draw(), QSvgVideo::draw(), and transformedBounds().
 {
     m_style.apply(p, this, states);
 }
bounds()
QRectF QSvgNode::bounds (QPainter * p, QSvgExtraStates & states) const virtual
Reimplemented in QSvgUse, QSvgRect, QSvgPolyline, QSvgPolygon, QSvgPath, QSvgLine, QSvgImage, QSvgEllipse, QSvgArc, and QSvgStructureNode.
Definition at line 199 of file qsvgnode.cpp.
Referenced by QSvgText::draw(), and transformedBounds().
 {
     return QRectF(0, 0, 0, 0);
 }
displayMode()
QSvgNode::DisplayMode QSvgNode::displayMode () const
Definition at line 330 of file qsvgnode.cpp.
Referenced by QSvgG::draw(), QSvgTinyDocument::draw(), and QSvgSwitch::draw().
 {
     return m_displayMode;
 }
document()
QSvgTinyDocument * QSvgNode::document () const
Definition at line 233 of file qsvgnode.cpp.
Referenced by QSvgStructureNode::addChild(), appendStyleProperty(), QSvgAnimateColor::apply(), QSvgStyle::apply(), parseAnimateColorNode(), parseAnimateTransformNode(), parseFont(), QSvgAnimateTransform::resolveMatrix(), QSvgStructureNode::scopeNode(), and styleProperty().
 {
     QSvgTinyDocument *doc = 0;
     QSvgNode *node = const_cast<QSvgNode*>(this);
     while (node && node->type() != QSvgNode::DOC) {
         node = node->parent();
     }
     doc = static_cast<QSvgTinyDocument*>(node);
     return doc;
 }
draw()
virtual void QSvgNode::draw (QPainter * p, QSvgExtraStates & states) pure virtual
Implemented in QSvgVideo, QSvgUse, QSvgTspan, QSvgText, QSvgRect, QSvgPolyline, QSvgPolygon, QSvgPath, QSvgLine, QSvgImage, QSvgSwitch, QSvgDefs, QSvgTinyDocument, QSvgEllipse, QSvgG, QSvgArc, and QSvgAnimation.
Referenced by QSvgG::draw(), QSvgTinyDocument::draw(), QSvgSwitch::draw(), and QSvgUse::draw().
isVisible()
bool QSvgNode::isVisible () const inline
Definition at line 188 of file qsvgnode_p.h.
Referenced by QSvgG::draw(), QSvgTinyDocument::draw(), QSvgSwitch::draw(), parseVisibility(), and setVisible().
 {
     return m_visible;
 }
nodeId()
QString QSvgNode::nodeId () const inline
Definition at line 193 of file qsvgnode_p.h.
Referenced by QSvgStyleSelector::attribute(), QSvgStyleSelector::hasAttributes(), and QSvgStyleSelector::nodeIds().
 {
     return m_id;
 }
parent()
QSvgNode * QSvgNode::parent () const inline
Definition at line 183 of file qsvgnode_p.h.
Referenced by createFontNode(), createLinearGradientNode(), document(), QSvgTinyDocument::draw(), QSvgTinyDocument::matrixForElement(), QSvgStyleSelector::parentNode(), parseVisibility(), QSvgStyleSelector::previousSiblingNode(), styleProperty(), and transformedBounds().
 {
     return m_parent;
 }
requiredExtensions()
const QStringList & QSvgNode::requiredExtensions () const
Definition at line 260 of file qsvgnode.cpp.
Referenced by QSvgSwitch::draw().
 {
     return m_requiredExtensions;
 }
requiredFeatures()
const QStringList & QSvgNode::requiredFeatures () const
Definition at line 250 of file qsvgnode.cpp.
Referenced by QSvgSwitch::draw().
 {
     return m_requiredFeatures;
 }
requiredFonts()
const QStringList & QSvgNode::requiredFonts () const
Definition at line 290 of file qsvgnode.cpp.
Referenced by QSvgSwitch::draw().
 {
     return m_requiredFonts;
 }
requiredFormats()
const QStringList & QSvgNode::requiredFormats () const
Definition at line 280 of file qsvgnode.cpp.
Referenced by QSvgSwitch::draw().
 {
     return m_requiredFormats;
 }
requiredLanguages()
const QStringList & QSvgNode::requiredLanguages () const
Definition at line 270 of file qsvgnode.cpp.
Referenced by QSvgSwitch::draw().
 {
     return m_requiredLanguages;
 }
revertStyle()
void QSvgNode::revertStyle (QPainter * p, QSvgExtraStates & states) const
Definition at line 123 of file qsvgnode.cpp.
Referenced by QSvgArc::draw(), QSvgG::draw(), QSvgEllipse::draw(), QSvgTinyDocument::draw(), QSvgSwitch::draw(), QSvgImage::draw(), QSvgLine::draw(), QSvgPath::draw(), QSvgPolygon::draw(), QSvgPolyline::draw(), QSvgRect::draw(), QSvgText::draw(), QSvgUse::draw(), QSvgVideo::draw(), and transformedBounds().
 {
     m_style.revert(p, states);
 }
setDisplayMode()
void QSvgNode::setDisplayMode (DisplayMode display)
Definition at line 325 of file qsvgnode.cpp.
Referenced by parseOthers().
 {
     m_displayMode = mode;
 }
setNodeId()
void QSvgNode::setNodeId (const QString & i)
Definition at line 315 of file qsvgnode.cpp.
Referenced by parseCoreNode(), and parseStopNode().
 {
     m_id = i;
 }
setRequiredExtensions()
void QSvgNode::setRequiredExtensions (const QStringList & lst)
Definition at line 255 of file qsvgnode.cpp.
Referenced by parseCoreNode().
 {
     m_requiredExtensions = lst;
 }
setRequiredFeatures()
void QSvgNode::setRequiredFeatures (const QStringList & lst)
Definition at line 245 of file qsvgnode.cpp.
Referenced by parseCoreNode().
 {
     m_requiredFeatures = lst;
 }
setRequiredFonts()
void QSvgNode::setRequiredFonts (const QStringList & lst)
Definition at line 285 of file qsvgnode.cpp.
Referenced by parseCoreNode().
 {
     m_requiredFonts = lst;
 }
setRequiredFormats()
void QSvgNode::setRequiredFormats (const QStringList & lst)
Definition at line 275 of file qsvgnode.cpp.
Referenced by parseCoreNode().
 {
     m_requiredFormats = lst;
 }
setRequiredLanguages()
void QSvgNode::setRequiredLanguages (const QStringList & lst)
Definition at line 265 of file qsvgnode.cpp.
Referenced by parseCoreNode().
 {
     m_requiredLanguages = lst;
 }
setVisible()
void QSvgNode::setVisible (bool visible)
Definition at line 295 of file qsvgnode.cpp.
Referenced by parseVisibility(), and setVisible().
 {
     //propagate visibility change of true to the parent
     //not propagating false is just a small performance
     //degradation since we'll iterate over children without
     //drawing any of them
     if (m_parent && visible && !m_parent->isVisible())
         m_parent->setVisible(true);
     m_visible = visible;
 }
setXmlClass()
void QSvgNode::setXmlClass (const QString & str)
Definition at line 320 of file qsvgnode.cpp.
Referenced by parseCoreNode(), and parseStopNode().
 {
     m_class = str;
 }
strokeWidth()
qreal QSvgNode::strokeWidth (QPainter * p) static protected
Definition at line 335 of file qsvgnode.cpp.
Referenced by QSvgArc::bounds(), QSvgEllipse::bounds(), QSvgLine::bounds(), QSvgPath::bounds(), QSvgPolygon::bounds(), QSvgPolyline::bounds(), and QSvgRect::bounds().
 {
     QPen pen = p->pen();
     if (pen.style() == Qt::NoPen || pen.brush().style() == Qt::NoBrush || pen.isCosmetic())
         return 0;
     return pen.widthF();
 }
styleProperty() [1/2]
QSvgStyleProperty * QSvgNode::styleProperty (QSvgStyleProperty::Type type) const
Definition at line 128 of file qsvgnode.cpp.
Referenced by parseBaseGradient(), QSvgHandler::resolveGradients(), and styleFromUrl().
 {
     const QSvgNode *node = this;
     while (node) {
         switch (type) {
         case QSvgStyleProperty::QUALITY:
             if (node->m_style.quality)
                 return node->m_style.quality;
             break;
         case QSvgStyleProperty::FILL:
             if (node->m_style.fill)
                 return node->m_style.fill;
             break;
         case QSvgStyleProperty::VIEWPORT_FILL:
             if (m_style.viewportFill)
                 return node->m_style.viewportFill;
             break;
         case QSvgStyleProperty::FONT:
             if (node->m_style.font)
                 return node->m_style.font;
             break;
         case QSvgStyleProperty::STROKE:
             if (node->m_style.stroke)
                 return node->m_style.stroke;
             break;
         case QSvgStyleProperty::SOLID_COLOR:
             if (node->m_style.solidColor)
                 return node->m_style.solidColor;
             break;
         case QSvgStyleProperty::GRADIENT:
             if (node->m_style.gradient)
                 return node->m_style.gradient;
             break;
         case QSvgStyleProperty::TRANSFORM:
             if (node->m_style.transform)
                 return node->m_style.transform;
             break;
         case QSvgStyleProperty::ANIMATE_COLOR:
             if (node->m_style.animateColor)
                 return node->m_style.animateColor;
             break;
         case QSvgStyleProperty::ANIMATE_TRANSFORM:
             if (!node->m_style.animateTransforms.isEmpty())
                 return node->m_style.animateTransforms.first();
             break;
         case QSvgStyleProperty::OPACITY:
             if (node->m_style.opacity)
                 return node->m_style.opacity;
             break;
         case QSvgStyleProperty::COMP_OP:
             if (node->m_style.compop)
                 return node->m_style.compop;
             break;
         default:
             break;
         }
         node = node->parent();
     }
     return 0;
 }
styleProperty() [2/2]
QSvgFillStyleProperty * QSvgNode::styleProperty (const QString & id) const
Definition at line 190 of file qsvgnode.cpp.
 {
     QString rid = id;
     if (rid.startsWith(QLatin1Char('#')))
         rid.remove(0, 1);
     QSvgTinyDocument *doc = document();
     return doc ? doc->namedStyle(rid) : 0;
 }
transformedBounds() [1/2]
QRectF QSvgNode::transformedBounds (QPainter * p, QSvgExtraStates & states) const virtual
Definition at line 307 of file qsvgnode.cpp.
Referenced by QSvgStructureNode::bounds(), QSvgUse::bounds(), QSvgTinyDocument::boundsOnElement(), and QSvgTinyDocument::draw().
 {
     applyStyle(p, states);
     QRectF rect = bounds(p, states);
     revertStyle(p, states);
     return rect;
 }
transformedBounds() [2/2]
QRectF QSvgNode::transformedBounds () const
Definition at line 204 of file qsvgnode.cpp.
Referenced by QSvgTinyDocument::viewBox().
 {
     if (!m_cachedBounds.isEmpty())
         return m_cachedBounds;
     QImage dummy(1, 1, QImage::Format_RGB32);
     QPainter p(&dummy);
     QSvgExtraStates states;
     QPen pen(Qt::NoBrush, 1, Qt::SolidLine, Qt::FlatCap, Qt::MiterJoin);
     pen.setMiterLimit(4);
     p.setPen(pen);
     QStack<QSvgNode*> parentApplyStack;
     QSvgNode *parent = m_parent;
     while (parent) {
         parentApplyStack.push(parent);
         parent = parent->parent();
     }
     for (int i = parentApplyStack.size() - 1; i >= 0; --i)
         parentApplyStack[i]->applyStyle(&p, states);
     p.setWorldTransform(QTransform());
     m_cachedBounds = transformedBounds(&p, states);
     return m_cachedBounds;
 }
type()
virtual Type QSvgNode::type () const pure virtual
Implemented in QSvgVideo, QSvgUse, QSvgTspan, QSvgText, QSvgRect, QSvgPolyline, QSvgPolygon, QSvgPath, QSvgLine, QSvgImage, QSvgSwitch, QSvgCircle, QSvgDefs, QSvgEllipse, QSvgG, QSvgTinyDocument, QSvgArc, and QSvgAnimation.
Referenced by QSvgHandler::characters(), createFontNode(), createLinearGradientNode(), createUseNode(), document(), QSvgStyleSelector::nodeToName(), QSvgStyleSelector::nodeToStructure(), parseTbreakNode(), QSvgHandler::resolveGradients(), and QSvgHandler::startElement().
xmlClass()
QString QSvgNode::xmlClass () const inline
Definition at line 198 of file qsvgnode_p.h.
Referenced by QSvgStyleSelector::attribute(), and QSvgStyleSelector::hasAttributes().
 {
     return m_class;
 }
Friends and Related Functions
QSvgTinyDocument
friend class QSvgTinyDocument friend
Definition at line 180 of file qsvgnode_p.h.
Properties
m_cachedBounds
QRectF QSvgNode::m_cachedBounds mutable private
Definition at line 178 of file qsvgnode_p.h.
Referenced by transformedBounds().
m_class
QString QSvgNode::m_class private
Definition at line 175 of file qsvgnode_p.h.
Referenced by setXmlClass(), and xmlClass().
m_displayMode
DisplayMode QSvgNode::m_displayMode private
Definition at line 177 of file qsvgnode_p.h.
Referenced by displayMode(), and setDisplayMode().
m_id
QString QSvgNode::m_id private
Definition at line 174 of file qsvgnode_p.h.
Referenced by nodeId(), and setNodeId().
m_parent
QSvgNode* QSvgNode::m_parent private
Definition at line 164 of file qsvgnode_p.h.
Referenced by parent(), setVisible(), and transformedBounds().
m_requiredExtensions
QStringList QSvgNode::m_requiredExtensions private
Definition at line 167 of file qsvgnode_p.h.
Referenced by requiredExtensions(), and setRequiredExtensions().
m_requiredFeatures
QStringList QSvgNode::m_requiredFeatures private
Definition at line 166 of file qsvgnode_p.h.
Referenced by requiredFeatures(), and setRequiredFeatures().
m_requiredFonts
QStringList QSvgNode::m_requiredFonts private
Definition at line 170 of file qsvgnode_p.h.
Referenced by requiredFonts(), and setRequiredFonts().
m_requiredFormats
QStringList QSvgNode::m_requiredFormats private
Definition at line 169 of file qsvgnode_p.h.
Referenced by requiredFormats(), and setRequiredFormats().
m_requiredLanguages
QStringList QSvgNode::m_requiredLanguages private
Definition at line 168 of file qsvgnode_p.h.
Referenced by requiredLanguages(), and setRequiredLanguages().
m_style
QSvgStyle QSvgNode::m_style mutable protected
Definition at line 160 of file qsvgnode_p.h.
Referenced by appendStyleProperty(), applyStyle(), QSvgTinyDocument::matrixForElement(), revertStyle(), and styleProperty().
m_visible
bool QSvgNode::m_visible private
Definition at line 172 of file qsvgnode_p.h.
Referenced by isVisible(), and setVisible().
The documentation for this class was generated from the following files:
/src/svg/qsvgnode_p.h
/src/svg/qsvgnode.cpp