Qt 4.8: QNativeSocketEnginePrivate Class Reference
QNativeSocketEnginePrivate Class Reference
#include <qnativesocketengine_p.h>
Public Types
enum ErrorString {
NonBlockingInitFailedErrorString, BroadcastingInitFailedErrorString, NoIpV6ErrorString, RemoteHostClosedErrorString,
TimeOutErrorString, ResourceErrorString, OperationUnsupportedErrorString, ProtocolUnsupportedErrorString,
InvalidSocketErrorString, HostUnreachableErrorString, NetworkUnreachableErrorString, AccessErrorString,
ConnectionTimeOutErrorString, ConnectionRefusedErrorString, AddressInuseErrorString, AddressNotAvailableErrorString,
AddressProtectedErrorString, DatagramTooLargeErrorString, SendDatagramErrorString, ReceiveDatagramErrorString,
WriteErrorString, ReadErrorString, PortInuseErrorString, NotSocketErrorString,
InvalidProxyTypeString, UnknownSocketErrorString = -1
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
bool checkProxy (const QHostAddress &address)
bool createNewSocket (QAbstractSocket::SocketType type, QAbstractSocket::NetworkLayerProtocol protocol)
Creates and returns a new socket descriptor of type socketType and socketProtocol.
bool fetchConnectionParameters ()
Fetches information about both ends of the connection: whatever is available.
int nativeAccept ()
bool nativeBind (const QHostAddress &address, quint16 port)
qint64 nativeBytesAvailable () const
void nativeClose ()
bool nativeConnect (const QHostAddress &address, quint16 port)
bool nativeHasPendingDatagrams () const
bool nativeJoinMulticastGroup (const QHostAddress &groupAddress, const QNetworkInterface &iface)
bool nativeLeaveMulticastGroup (const QHostAddress &groupAddress, const QNetworkInterface &iface)
bool nativeListen (int backlog)
QNetworkInterface nativeMulticastInterface () const
qint64 nativePendingDatagramSize () const
qint64 nativeRead (char *data, qint64 maxLength)
qint64 nativeReceiveDatagram (char *data, qint64 maxLength, QHostAddress *address, quint16 *port)
int nativeSelect (int timeout, bool selectForRead) const
int nativeSelect (int timeout, bool checkRead, bool checkWrite, bool *selectForRead, bool *selectForWrite) const
qint64 nativeSendDatagram (const char *data, qint64 length, const QHostAddress &host, quint16 port)
bool nativeSetMulticastInterface (const QNetworkInterface &iface)
qint64 nativeWrite (const char *data, qint64 length)
int option (QNativeSocketEngine::SocketOption option) const
Returns the value of the socket option opt.
QNativeSocketEnginePrivate ()
Constructs the private class and initializes all data members.
void setError (QAbstractSocket::SocketError error, ErrorString errorString) const
Sets the error and error string if not set already.
bool setOption (QNativeSocketEngine::SocketOption option, int value)
Sets the socket option opt to v.
~QNativeSocketEnginePrivate ()
Destructs the private class.
Public Functions inherited from QAbstractSocketEnginePrivate
QAbstractSocketEnginePrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QSocketNotifier * exceptNotifier
QSocketNotifier * readNotifier
int socketDescriptor
QWindowsSockInit winSock
QSocketNotifier * writeNotifier
Public Variables inherited from QAbstractSocketEnginePrivate
bool hasSetSocketError
QHostAddress localAddress
quint16 localPort
QHostAddress peerAddress
quint16 peerPort
QAbstractSocketEngineReceiver * receiver
QAbstractSocket::SocketError socketError
QString socketErrorString
QAbstractSocket::NetworkLayerProtocol socketProtocol
QAbstractSocket::SocketState socketState
QAbstractSocket::SocketType socketType
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Detailed Description
Definition at line 190 of file qnativesocketengine_p.h.
Enumerations
ErrorString
enum QNativeSocketEnginePrivate::ErrorString
Enumerator
NonBlockingInitFailedErrorString
BroadcastingInitFailedErrorString
NoIpV6ErrorString
RemoteHostClosedErrorString
TimeOutErrorString
ResourceErrorString
OperationUnsupportedErrorString
ProtocolUnsupportedErrorString
InvalidSocketErrorString
HostUnreachableErrorString
NetworkUnreachableErrorString
AccessErrorString
ConnectionTimeOutErrorString
ConnectionRefusedErrorString
AddressInuseErrorString
AddressNotAvailableErrorString
AddressProtectedErrorString
DatagramTooLargeErrorString
SendDatagramErrorString
ReceiveDatagramErrorString
WriteErrorString
ReadErrorString
PortInuseErrorString
NotSocketErrorString
InvalidProxyTypeString
UnknownSocketErrorString
Definition at line 205 of file qnativesocketengine_p.h.
                      {
         NonBlockingInitFailedErrorString,
         BroadcastingInitFailedErrorString,
         NoIpV6ErrorString,
         RemoteHostClosedErrorString,
         TimeOutErrorString,
         ResourceErrorString,
         OperationUnsupportedErrorString,
         ProtocolUnsupportedErrorString,
         InvalidSocketErrorString,
         HostUnreachableErrorString,
         NetworkUnreachableErrorString,
         AccessErrorString,
         ConnectionTimeOutErrorString,
         ConnectionRefusedErrorString,
         AddressInuseErrorString,
         AddressNotAvailableErrorString,
         AddressProtectedErrorString,
         DatagramTooLargeErrorString,
         SendDatagramErrorString,
         ReceiveDatagramErrorString,
         WriteErrorString,
         ReadErrorString,
         PortInuseErrorString,
         NotSocketErrorString,
         InvalidProxyTypeString,
         UnknownSocketErrorString = -1
     };
Constructors and Destructors
QNativeSocketEnginePrivate()
QNativeSocketEnginePrivate::QNativeSocketEnginePrivate ()
Constructs the private class and initializes all data members.
Warning
This function is not part of the public interface.
On Windows, WSAStartup is called "recursively" for every concurrent QNativeSocketEngine. This is safe, because WSAStartup and WSACleanup are reference counted.
Definition at line 167 of file qnativesocketengine.cpp.
                                                        :
     socketDescriptor(-1),
     readNotifier(0),
     writeNotifier(0),
     exceptNotifier(0)
 {
 }
~QNativeSocketEnginePrivate()
QNativeSocketEnginePrivate::~QNativeSocketEnginePrivate ()
Destructs the private class.
Warning
This function is not part of the public interface.
Definition at line 181 of file qnativesocketengine.cpp.
 {
 }
Functions
checkProxy()
bool QNativeSocketEnginePrivate::checkProxy (const QHostAddress & address)
Definition at line 293 of file qnativesocketengine.cpp.
 {
     if (address == QHostAddress::LocalHost || address == QHostAddress::LocalHostIPv6)
         return true;
 #if !defined(QT_NO_NETWORKPROXY)
     QObject *parent = q_func()->parent();
     QNetworkProxy proxy;
     if (QAbstractSocket *socket = qobject_cast<QAbstractSocket *>(parent)) {
         proxy = socket->proxy();
     } else if (QTcpServer *server = qobject_cast<QTcpServer *>(parent)) {
         proxy = server->proxy();
     } else {
         // no parent -> no proxy
         return true;
     }
     if (proxy.type() == QNetworkProxy::DefaultProxy)
         proxy = QNetworkProxy::applicationProxy();
     if (proxy.type() != QNetworkProxy::DefaultProxy &&
         proxy.type() != QNetworkProxy::NoProxy) {
         // QNativeSocketEngine doesn't do proxies
         setError(QAbstractSocket::UnsupportedSocketOperationError,
                  QNativeSocketEnginePrivate::InvalidProxyTypeString);
         return false;
     }
 #endif
     return true;
 }
createNewSocket()
bool QNativeSocketEnginePrivate::createNewSocket (QAbstractSocket::SocketType socketType, QAbstractSocket::NetworkLayerProtocol socketProtocol)
Creates and returns a new socket descriptor of type socketType and socketProtocol.
Warning
This function is not part of the public interface.
Returns -1 on failure.
Definition at line 148 of file qnativesocketengine_unix.cpp.
 {
 #ifndef QT_NO_IPV6
     int protocol = (socketProtocol == QAbstractSocket::IPv6Protocol) ? AF_INET6 : AF_INET;
 #else
     Q_UNUSED(socketProtocol);
     int protocol = AF_INET;
 #endif
     int type = (socketType == QAbstractSocket::UdpSocket) ? SOCK_DGRAM : SOCK_STREAM;
     int socket = qt_safe_socket(protocol, type, 0);
     if (socket <= 0) {
         switch (errno) {
         case EPROTONOSUPPORT:
         case EAFNOSUPPORT:
         case EINVAL:
             setError(QAbstractSocket::UnsupportedSocketOperationError, ProtocolUnsupportedErrorString);
             break;
         case ENFILE:
         case EMFILE:
         case ENOBUFS:
         case ENOMEM:
             setError(QAbstractSocket::SocketResourceError, ResourceErrorString);
             break;
         case EACCES:
             setError(QAbstractSocket::SocketAccessError, AccessErrorString);
             break;
         default:
             break;
         }
         return false;
     }
     socketDescriptor = socket;
     return true;
 }
fetchConnectionParameters()
bool QNativeSocketEnginePrivate::fetchConnectionParameters ()
Fetches information about both ends of the connection: whatever is available.
Definition at line 910 of file qnativesocketengine_unix.cpp.
 {
     localPort = 0;
     localAddress.clear();
     peerPort = 0;
     peerAddress.clear();
     if (socketDescriptor == -1)
         return false;
     qt_sockaddr sa;
     QT_SOCKLEN_T sockAddrSize = sizeof(sa);
     // Determine local address
     memset(&sa, 0, sizeof(sa));
     if (::getsockname(socketDescriptor, &sa.a, &sockAddrSize) == 0) {
         qt_socket_getPortAndAddress(&sa, &localPort, &localAddress);
         // Determine protocol family
         switch (sa.a.sa_family) {
         case AF_INET:
             socketProtocol = QAbstractSocket::IPv4Protocol;
             break;
 #if !defined (QT_NO_IPV6)
         case AF_INET6:
             socketProtocol = QAbstractSocket::IPv6Protocol;
             break;
 #endif
         default:
             socketProtocol = QAbstractSocket::UnknownNetworkLayerProtocol;
             break;
         }
     } else if (errno == EBADF) {
         setError(QAbstractSocket::UnsupportedSocketOperationError, InvalidSocketErrorString);
         return false;
     }
     // Determine the remote address
     if (!::getpeername(socketDescriptor, &sa.a, &sockAddrSize))
         qt_socket_getPortAndAddress(&sa, &peerPort, &peerAddress);
     // Determine the socket type (UDP/TCP)
     int value = 0;
     QT_SOCKOPTLEN_T valueSize = sizeof(int);
     if (::getsockopt(socketDescriptor, SOL_SOCKET, SO_TYPE, &value, &valueSize) == 0) {
         if (value == SOCK_STREAM)
             socketType = QAbstractSocket::TcpSocket;
         else if (value == SOCK_DGRAM)
             socketType = QAbstractSocket::UdpSocket;
         else
             socketType = QAbstractSocket::UnknownSocketType;
     }
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     QString socketProtocolStr = "UnknownProtocol";
     if (socketProtocol == QAbstractSocket::IPv4Protocol) socketProtocolStr = "IPv4Protocol";
     else if (socketProtocol == QAbstractSocket::IPv6Protocol) socketProtocolStr = "IPv6Protocol";
     QString socketTypeStr = "UnknownSocketType";
     if (socketType == QAbstractSocket::TcpSocket) socketTypeStr = "TcpSocket";
     else if (socketType == QAbstractSocket::UdpSocket) socketTypeStr = "UdpSocket";
     qDebug("QNativeSocketEnginePrivate::fetchConnectionParameters() local == %s:%i,"
            " peer == %s:%i, socket == %s - %s",
            localAddress.toString().toLatin1().constData(), localPort,
            peerAddress.toString().toLatin1().constData(), peerPort,socketTypeStr.toLatin1().constData(),
            socketProtocolStr.toLatin1().constData());
 #endif
     return true;
 }
nativeAccept()
int QNativeSocketEnginePrivate::nativeAccept ()
Definition at line 579 of file qnativesocketengine_unix.cpp.
 {
     int acceptedDescriptor = qt_safe_accept(socketDescriptor, 0, 0);
     return acceptedDescriptor;
 }
nativeBind()
bool QNativeSocketEnginePrivate::nativeBind (const QHostAddress & address, quint16 port)
Definition at line 481 of file qnativesocketengine_unix.cpp.
 {
     struct sockaddr_in sockAddrIPv4;
     struct sockaddr *sockAddrPtr = 0;
     QT_SOCKLEN_T sockAddrSize = 0;
 #if !defined(QT_NO_IPV6)
     struct sockaddr_in6 sockAddrIPv6;
     if (address.protocol() == QAbstractSocket::IPv6Protocol) {
         memset(&sockAddrIPv6, 0, sizeof(sockAddrIPv6));
         sockAddrIPv6.sin6_family = AF_INET6;
         sockAddrIPv6.sin6_port = htons(port);
 #ifndef QT_NO_IPV6IFNAME
         sockAddrIPv6.sin6_scope_id = ::if_nametoindex(address.scopeId().toLatin1().data());
 #else
         sockAddrIPv6.sin6_scope_id = address.scopeId().toInt();
 #endif
         Q_IPV6ADDR tmp = address.toIPv6Address();
         memcpy(&sockAddrIPv6.sin6_addr.s6_addr, &tmp, sizeof(tmp));
         sockAddrSize = sizeof(sockAddrIPv6);
         sockAddrPtr = (struct sockaddr *) &sockAddrIPv6;
     } else
 #endif
         if (address.protocol() == QAbstractSocket::IPv4Protocol) {
             memset(&sockAddrIPv4, 0, sizeof(sockAddrIPv4));
             sockAddrIPv4.sin_family = AF_INET;
             sockAddrIPv4.sin_port = htons(port);
             sockAddrIPv4.sin_addr.s_addr = htonl(address.toIPv4Address());
             sockAddrSize = sizeof(sockAddrIPv4);
             sockAddrPtr = (struct sockaddr *) &sockAddrIPv4;
         } else {
             // unreachable
         }
     int bindResult = QT_SOCKET_BIND(socketDescriptor, sockAddrPtr, sockAddrSize);
     if (bindResult < 0) {
         switch(errno) {
         case EADDRINUSE:
             setError(QAbstractSocket::AddressInUseError, AddressInuseErrorString);
             break;
         case EACCES:
             setError(QAbstractSocket::SocketAccessError, AddressProtectedErrorString);
             break;
         case EINVAL:
             setError(QAbstractSocket::UnsupportedSocketOperationError, OperationUnsupportedErrorString);
             break;
         case EADDRNOTAVAIL:
             setError(QAbstractSocket::SocketAddressNotAvailableError, AddressNotAvailableErrorString);
             break;
         default:
             break;
         }
 #if defined (QNATIVESOCKETENGINE_DEBUG)
         qDebug("QNativeSocketEnginePrivate::nativeBind(%s, %i) == false (%s)",
                address.toString().toLatin1().constData(), port, socketErrorString.toLatin1().constData());
 #endif
         return false;
     }
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     qDebug("QNativeSocketEnginePrivate::nativeBind(%s, %i) == true",
            address.toString().toLatin1().constData(), port);
 #endif
     socketState = QAbstractSocket::BoundState;
     return true;
 }
nativeBytesAvailable()
qint64 QNativeSocketEnginePrivate::nativeBytesAvailable () const
Definition at line 754 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
     int nbytes = 0;
     // gives shorter than true amounts on Unix domain sockets.
     qint64 available = 0;
     if (qt_safe_ioctl(socketDescriptor, FIONREAD, (char *) &nbytes) >= 0)
         available = (qint64) nbytes;
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     qDebug("QNativeSocketEnginePrivate::nativeBytesAvailable() == %lli", available);
 #endif
     return available;
 }
nativeClose()
void QNativeSocketEnginePrivate::nativeClose ()
Definition at line 981 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     qDebug("QNativeSocketEngine::nativeClose()");
 #endif
     qt_safe_close(socketDescriptor);
 }
nativeConnect()
bool QNativeSocketEnginePrivate::nativeConnect (const QHostAddress & address, quint16 port)
Definition at line 366 of file qnativesocketengine_unix.cpp.
 {
 #ifdef QNATIVESOCKETENGINE_DEBUG
     qDebug("QNativeSocketEnginePrivate::nativeConnect() : %d ", socketDescriptor);
 #endif
     struct sockaddr_in sockAddrIPv4;
     struct sockaddr *sockAddrPtr = 0;
     QT_SOCKLEN_T sockAddrSize = 0;
 #if !defined(QT_NO_IPV6)
     struct sockaddr_in6 sockAddrIPv6;
     if (addr.protocol() == QAbstractSocket::IPv6Protocol) {
         memset(&sockAddrIPv6, 0, sizeof(sockAddrIPv6));
         sockAddrIPv6.sin6_family = AF_INET6;
         sockAddrIPv6.sin6_port = htons(port);
         QString scopeid = addr.scopeId();
         bool ok;
         sockAddrIPv6.sin6_scope_id = scopeid.toInt(&ok);
 #ifndef QT_NO_IPV6IFNAME
         if (!ok)
             sockAddrIPv6.sin6_scope_id = ::if_nametoindex(scopeid.toLatin1());
 #endif
         Q_IPV6ADDR ip6 = addr.toIPv6Address();
         memcpy(&sockAddrIPv6.sin6_addr.s6_addr, &ip6, sizeof(ip6));
         sockAddrSize = sizeof(sockAddrIPv6);
         sockAddrPtr = (struct sockaddr *) &sockAddrIPv6;
     } else
 #if 0
     {}
 #endif
 #endif
     if (addr.protocol() == QAbstractSocket::IPv4Protocol) {
         memset(&sockAddrIPv4, 0, sizeof(sockAddrIPv4));
         sockAddrIPv4.sin_family = AF_INET;
         sockAddrIPv4.sin_port = htons(port);
         sockAddrIPv4.sin_addr.s_addr = htonl(addr.toIPv4Address());
         sockAddrSize = sizeof(sockAddrIPv4);
         sockAddrPtr = (struct sockaddr *) &sockAddrIPv4;
     } else {
         // unreachable
     }
     int connectResult = qt_safe_connect(socketDescriptor, sockAddrPtr, sockAddrSize);
     if (connectResult == -1) {
         switch (errno) {
         case EISCONN:
             socketState = QAbstractSocket::ConnectedState;
             break;
         case ECONNREFUSED:
         case EINVAL:
             setError(QAbstractSocket::ConnectionRefusedError, ConnectionRefusedErrorString);
             socketState = QAbstractSocket::UnconnectedState;
             break;
         case ETIMEDOUT:
             setError(QAbstractSocket::NetworkError, ConnectionTimeOutErrorString);
             break;
         case EHOSTUNREACH:
             setError(QAbstractSocket::NetworkError, HostUnreachableErrorString);
             socketState = QAbstractSocket::UnconnectedState;
             break;
         case ENETUNREACH:
             setError(QAbstractSocket::NetworkError, NetworkUnreachableErrorString);
             socketState = QAbstractSocket::UnconnectedState;
             break;
         case EADDRINUSE:
             setError(QAbstractSocket::NetworkError, AddressInuseErrorString);
             break;
         case EINPROGRESS:
         case EALREADY:
             setError(QAbstractSocket::UnfinishedSocketOperationError, InvalidSocketErrorString);
             socketState = QAbstractSocket::ConnectingState;
             break;
         case EAGAIN:
             setError(QAbstractSocket::UnfinishedSocketOperationError, InvalidSocketErrorString);
             setError(QAbstractSocket::SocketResourceError, ResourceErrorString);
             break;
         case EACCES:
         case EPERM:
             setError(QAbstractSocket::SocketAccessError, AccessErrorString);
             socketState = QAbstractSocket::UnconnectedState;
             break;
         case EAFNOSUPPORT:
         case EBADF:
         case EFAULT:
         case ENOTSOCK:
             socketState = QAbstractSocket::UnconnectedState;
         default:
             break;
         }
         if (socketState != QAbstractSocket::ConnectedState) {
 #if defined (QNATIVESOCKETENGINE_DEBUG)
             qDebug("QNativeSocketEnginePrivate::nativeConnect(%s, %i) == false (%s)",
                    addr.toString().toLatin1().constData(), port,
                    socketState == QAbstractSocket::ConnectingState
                    ? "Connection in progress" : socketErrorString.toLatin1().constData());
 #endif
             return false;
         }
     }
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     qDebug("QNativeSocketEnginePrivate::nativeConnect(%s, %i) == true",
            addr.toString().toLatin1().constData(), port);
 #endif
     socketState = QAbstractSocket::ConnectedState;
     return true;
 }
nativeHasPendingDatagrams()
bool QNativeSocketEnginePrivate::nativeHasPendingDatagrams () const
Definition at line 768 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
     // Create a sockaddr struct and reset its port number.
     qt_sockaddr storage;
     QT_SOCKLEN_T storageSize = sizeof(storage);
     memset(&storage, 0, storageSize);
     // Peek 0 bytes into the next message. The size of the message may
     // well be 0, so we can't check recvfrom's return value.
     ssize_t readBytes;
     do {
         char c;
         readBytes = ::recvfrom(socketDescriptor, &c, 1, MSG_PEEK, &storage.a, &storageSize);
     } while (readBytes == -1 && errno == EINTR);
     // If there's no error, or if our buffer was too small, there must be a
     // pending datagram.
     bool result = (readBytes != -1) || errno == EMSGSIZE;
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     qDebug("QNativeSocketEnginePrivate::nativeHasPendingDatagrams() == %s",
            result ? "true" : "false");
 #endif
     return result;
 }
nativeJoinMulticastGroup()
bool QNativeSocketEnginePrivate::nativeJoinMulticastGroup (const QHostAddress & groupAddress, const QNetworkInterface & iface)
Definition at line 663 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
     return multicastMembershipHelper(this,
 #ifndef QT_NO_IPV6
                                      IPV6_JOIN_GROUP,
 #else
                                      0,
 #endif
                                      IP_ADD_MEMBERSHIP,
                                      groupAddress,
                                      interface);
 }
nativeLeaveMulticastGroup()
bool QNativeSocketEnginePrivate::nativeLeaveMulticastGroup (const QHostAddress & groupAddress, const QNetworkInterface & iface)
Definition at line 677 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
     return multicastMembershipHelper(this,
 #ifndef QT_NO_IPV6
                                      IPV6_LEAVE_GROUP,
 #else
                                      0,
 #endif
                                      IP_DROP_MEMBERSHIP,
                                      groupAddress,
                                      interface);
 }
nativeListen()
bool QNativeSocketEnginePrivate::nativeListen (int backlog)
Definition at line 552 of file qnativesocketengine_unix.cpp.
 {
     if (qt_safe_listen(socketDescriptor, backlog) < 0) {
         switch (errno) {
         case EADDRINUSE:
             setError(QAbstractSocket::AddressInUseError,
                      PortInuseErrorString);
             break;
         default:
             break;
         }
 #if defined (QNATIVESOCKETENGINE_DEBUG)
         qDebug("QNativeSocketEnginePrivate::nativeListen(%i) == false (%s)",
                backlog, socketErrorString.toLatin1().constData());
 #endif
         return false;
     }
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     qDebug("QNativeSocketEnginePrivate::nativeListen(%i) == true", backlog);
 #endif
     socketState = QAbstractSocket::ListeningState;
     return true;
 }
nativeMulticastInterface()
QNetworkInterface QNativeSocketEnginePrivate::nativeMulticastInterface () const
Definition at line 691 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
 #ifndef QT_NO_IPV6
     if (socketProtocol == QAbstractSocket::IPv6Protocol) {
         uint v;
         QT_SOCKOPTLEN_T sizeofv = sizeof(v);
         if (::getsockopt(socketDescriptor, IPPROTO_IPV6, IPV6_MULTICAST_IF, &v, &sizeofv) == -1)
             return QNetworkInterface();
         return QNetworkInterface::interfaceFromIndex(v);
     }
 #endif
     struct in_addr v = { 0 };
     QT_SOCKOPTLEN_T sizeofv = sizeof(v);
     if (::getsockopt(socketDescriptor, IPPROTO_IP, IP_MULTICAST_IF, &v, &sizeofv) == -1)
         return QNetworkInterface();
     if (v.s_addr != 0 && sizeofv >= sizeof(v)) {
         QHostAddress ipv4(ntohl(v.s_addr));
         QList<QNetworkInterface> ifaces = QNetworkInterface::allInterfaces();
         for (int i = 0; i < ifaces.count(); ++i) {
             const QNetworkInterface &iface = ifaces.at(i);
             QList<QNetworkAddressEntry> entries = iface.addressEntries();
             for (int j = 0; j < entries.count(); ++j) {
                 const QNetworkAddressEntry &entry = entries.at(j);
                 if (entry.ip() == ipv4)
                     return iface;
             }
         }
     }
     return QNetworkInterface();
 }
nativePendingDatagramSize()
qint64 QNativeSocketEnginePrivate::nativePendingDatagramSize () const
Definition at line 794 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
     QVarLengthArray<char, 8192> udpMessagePeekBuffer(8192);
     ssize_t recvResult = -1;
     for (;;) {
         // the data written to udpMessagePeekBuffer is discarded, so
         // this function is still reentrant although it might not look
         // so.
         recvResult = ::recv(socketDescriptor, udpMessagePeekBuffer.data(),
             udpMessagePeekBuffer.size(), MSG_PEEK);
         if (recvResult == -1 && errno == EINTR)
             continue;
         if (recvResult != (ssize_t) udpMessagePeekBuffer.size())
             break;
         udpMessagePeekBuffer.resize(udpMessagePeekBuffer.size() * 2);
     }
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     qDebug("QNativeSocketEnginePrivate::nativePendingDatagramSize() == %i", recvResult);
 #endif
     return qint64(recvResult);
 }
nativeRead()
qint64 QNativeSocketEnginePrivate::nativeRead (char * data, qint64 maxLength)
Definition at line 1026 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
     Q_Q(QNativeSocketEngine);
     if (!q->isValid()) {
         qWarning("QNativeSocketEngine::nativeRead: Invalid socket");
         return -1;
     }
     ssize_t r = 0;
     r = qt_safe_read(socketDescriptor, data, maxSize);
     if (r < 0) {
         r = -1;
         switch (errno) {
 #if EWOULDBLOCK-0 && EWOULDBLOCK != EAGAIN
         case EWOULDBLOCK:
 #endif
         case EAGAIN:
             // No data was available for reading
             r = -2;
             break;
         case EBADF:
         case EINVAL:
         case EIO:
             //error string is now set in read(), not here in nativeRead()
             break;
         case ECONNRESET:
 #if defined(Q_OS_VXWORKS)
         case ESHUTDOWN:
 #endif
             r = 0;
             break;
         default:
             break;
         }
     }
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     qDebug("QNativeSocketEnginePrivate::nativeRead(%p \"%s\", %llu) == %i",
            data, qt_prettyDebug(data, qMin(r, ssize_t(16)), r).data(),
            maxSize, r);
 #endif
     return qint64(r);
 }
nativeReceiveDatagram()
qint64 QNativeSocketEnginePrivate::nativeReceiveDatagram (char * data, qint64 maxLength, QHostAddress * address, quint16 * port)
Definition at line 821 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
     qt_sockaddr aa;
     memset(&aa, 0, sizeof(aa));
     QT_SOCKLEN_T sz;
     sz = sizeof(aa);
     ssize_t recvFromResult = 0;
     do {
         char c;
         recvFromResult = ::recvfrom(socketDescriptor, maxSize ? data : &c, maxSize ? maxSize : 1,
                                     0, &aa.a, &sz);
     } while (recvFromResult == -1 && errno == EINTR);
     if (recvFromResult == -1) {
         setError(QAbstractSocket::NetworkError, ReceiveDatagramErrorString);
     } else if (port || address) {
         qt_socket_getPortAndAddress(&aa, port, address);
     }
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     qDebug("QNativeSocketEnginePrivate::nativeReceiveDatagram(%p \"%s\", %lli, %s, %i) == %lli",
            data, qt_prettyDebug(data, qMin(recvFromResult, ssize_t(16)), recvFromResult).data(), maxSize,
            address ? address->toString().toLatin1().constData() : "(nil)",
            port ? *port : 0, (qint64) recvFromResult);
 #endif
     return qint64(maxSize ? recvFromResult : recvFromResult == -1 ? -1 : 0);
 }
nativeSelect() [1/2]
int QNativeSocketEnginePrivate::nativeSelect (int timeout, bool selectForRead) const
Definition at line 1072 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
     fd_set fds;
     FD_ZERO(&fds);
     FD_SET(socketDescriptor, &fds);
     struct timeval tv;
     tv.tv_sec = timeout / 1000;
     tv.tv_usec = (timeout % 1000) * 1000;
     int retval;
     if (selectForRead)
         retval = qt_safe_select(socketDescriptor + 1, &fds, 0, 0, timeout < 0 ? 0 : &tv);
     else
         retval = qt_safe_select(socketDescriptor + 1, 0, &fds, 0, timeout < 0 ? 0 : &tv);
     return retval;
 }
nativeSelect() [2/2]
int QNativeSocketEnginePrivate::nativeSelect (int timeout, bool checkRead, bool checkWrite, bool * selectForRead, bool * selectForWrite) const
Definition at line 1091 of file qnativesocketengine_unix.cpp.
 {
     fd_set fdread;
     FD_ZERO(&fdread);
     if (checkRead)
         FD_SET(socketDescriptor, &fdread);
     fd_set fdwrite;
     FD_ZERO(&fdwrite);
     if (checkWrite)
         FD_SET(socketDescriptor, &fdwrite);
     struct timeval tv;
     tv.tv_sec = timeout / 1000;
     tv.tv_usec = (timeout % 1000) * 1000;
     int ret;
     ret = qt_safe_select(socketDescriptor + 1, &fdread, &fdwrite, 0, timeout < 0 ? 0 : &tv);
     if (ret <= 0)
         return ret;
     *selectForRead = FD_ISSET(socketDescriptor, &fdread);
     *selectForWrite = FD_ISSET(socketDescriptor, &fdwrite);
     return ret;
 }
nativeSendDatagram()
qint64 QNativeSocketEnginePrivate::nativeSendDatagram (const char * data, qint64 length, const QHostAddress & host, quint16 port)
Definition at line 852 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
     struct sockaddr_in sockAddrIPv4;
     struct sockaddr *sockAddrPtr = 0;
     QT_SOCKLEN_T sockAddrSize = 0;
 #if !defined(QT_NO_IPV6)
     struct sockaddr_in6 sockAddrIPv6;
     if (host.protocol() == QAbstractSocket::IPv6Protocol) {
         memset(&sockAddrIPv6, 0, sizeof(sockAddrIPv6));
         sockAddrIPv6.sin6_family = AF_INET6;
         sockAddrIPv6.sin6_port = htons(port);
         Q_IPV6ADDR tmp = host.toIPv6Address();
         memcpy(&sockAddrIPv6.sin6_addr.s6_addr, &tmp, sizeof(tmp));
         QString scopeid = host.scopeId();
         bool ok;
         sockAddrIPv6.sin6_scope_id = scopeid.toInt(&ok);
 #ifndef QT_NO_IPV6IFNAME
         if (!ok)
             sockAddrIPv6.sin6_scope_id = ::if_nametoindex(scopeid.toLatin1());
 #endif
         sockAddrSize = sizeof(sockAddrIPv6);
         sockAddrPtr = (struct sockaddr *)&sockAddrIPv6;
     } else
 #endif
     if (host.protocol() == QAbstractSocket::IPv4Protocol) {
         memset(&sockAddrIPv4, 0, sizeof(sockAddrIPv4));
         sockAddrIPv4.sin_family = AF_INET;
         sockAddrIPv4.sin_port = htons(port);
         sockAddrIPv4.sin_addr.s_addr = htonl(host.toIPv4Address());
         sockAddrSize = sizeof(sockAddrIPv4);
         sockAddrPtr = (struct sockaddr *)&sockAddrIPv4;
     }
     ssize_t sentBytes = qt_safe_sendto(socketDescriptor, data, len,
                                        0, sockAddrPtr, sockAddrSize);
     if (sentBytes < 0) {
         switch (errno) {
         case EMSGSIZE:
             setError(QAbstractSocket::DatagramTooLargeError, DatagramTooLargeErrorString);
             break;
         default:
             setError(QAbstractSocket::NetworkError, SendDatagramErrorString);
         }
     }
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     qDebug("QNativeSocketEngine::sendDatagram(%p \"%s\", %lli, \"%s\", %i) == %lli", data,
            qt_prettyDebug(data, qMin<int>(len, 16), len).data(), len, host.toString().toLatin1().constData(),
            port, (qint64) sentBytes);
 #endif
     return qint64(sentBytes);
 }
nativeSetMulticastInterface()
bool QNativeSocketEnginePrivate::nativeSetMulticastInterface (const QNetworkInterface & iface)
Definition at line 723 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
 #ifndef QT_NO_IPV6
     if (socketProtocol == QAbstractSocket::IPv6Protocol) {
         uint v = iface.index();
         return (::setsockopt(socketDescriptor, IPPROTO_IPV6, IPV6_MULTICAST_IF, &v, sizeof(v)) != -1);
     }
 #endif
     struct in_addr v;
     if (iface.isValid()) {
         QList<QNetworkAddressEntry> entries = iface.addressEntries();
         for (int i = 0; i < entries.count(); ++i) {
             const QNetworkAddressEntry &entry = entries.at(i);
             const QHostAddress &ip = entry.ip();
             if (ip.protocol() == QAbstractSocket::IPv4Protocol) {
                 v.s_addr = htonl(ip.toIPv4Address());
                 int r = ::setsockopt(socketDescriptor, IPPROTO_IP, IP_MULTICAST_IF, &v, sizeof(v));
                 if (r != -1)
                     return true;
             }
         }
         return false;
     }
     v.s_addr = INADDR_ANY;
     return (::setsockopt(socketDescriptor, IPPROTO_IP, IP_MULTICAST_IF, &v, sizeof(v)) != -1);
 }
nativeWrite()
qint64 QNativeSocketEnginePrivate::nativeWrite (const char * data, qint64 length)
Definition at line 990 of file qnativesocketengine_unix.cpp.
Referenced by multicastMembershipHelper().
 {
     Q_Q(QNativeSocketEngine);
     ssize_t writtenBytes;
     writtenBytes = qt_safe_write_nosignal(socketDescriptor, data, len);
     if (writtenBytes < 0) {
         switch (errno) {
         case EPIPE:
         case ECONNRESET:
             writtenBytes = -1;
             setError(QAbstractSocket::RemoteHostClosedError, RemoteHostClosedErrorString);
             q->close();
             break;
         case EAGAIN:
             writtenBytes = 0;
             break;
         case EMSGSIZE:
             setError(QAbstractSocket::DatagramTooLargeError, DatagramTooLargeErrorString);
             break;
         default:
             break;
         }
     }
 #if defined (QNATIVESOCKETENGINE_DEBUG)
     qDebug("QNativeSocketEnginePrivate::nativeWrite(%p \"%s\", %llu) == %i",
            data, qt_prettyDebug(data, qMin((int) len, 16),
                                 (int) len).data(), len, (int) writtenBytes);
 #endif
     return qint64(writtenBytes);
 }
option()
int QNativeSocketEnginePrivate::option (QNativeSocketEngine::SocketOption opt) const
Returns the value of the socket option opt.
Warning
This function is not part of the public interface.
Definition at line 191 of file qnativesocketengine_unix.cpp.
 {
     Q_Q(const QNativeSocketEngine);
     if (!q->isValid())
         return -1;
     int n = -1;
     int level = SOL_SOCKET; // default
     switch (opt) {
     case QNativeSocketEngine::ReceiveBufferSocketOption:
         n = SO_RCVBUF;
         break;
     case QNativeSocketEngine::SendBufferSocketOption:
         n = SO_SNDBUF;
         break;
     case QNativeSocketEngine::NonBlockingSocketOption:
         break;
     case QNativeSocketEngine::BroadcastSocketOption:
         break;
     case QNativeSocketEngine::AddressReusable:
         n = SO_REUSEADDR;
         break;
     case QNativeSocketEngine::BindExclusively:
         return true;
     case QNativeSocketEngine::ReceiveOutOfBandData:
         n = SO_OOBINLINE;
         break;
     case QNativeSocketEngine::LowDelayOption:
         level = IPPROTO_TCP;
         n = TCP_NODELAY;
         break;
     case QNativeSocketEngine::KeepAliveOption:
         n = SO_KEEPALIVE;
         break;
     case QNativeSocketEngine::MulticastTtlOption:
 #ifndef QT_NO_IPV6
         if (socketProtocol == QAbstractSocket::IPv6Protocol) {
             level = IPPROTO_IPV6;
             n = IPV6_MULTICAST_HOPS;
         } else
 #endif
         {
             level = IPPROTO_IP;
             n = IP_MULTICAST_TTL;
         }
         break;
     case QNativeSocketEngine::MulticastLoopbackOption:
 #ifndef QT_NO_IPV6
         if (socketProtocol == QAbstractSocket::IPv6Protocol) {
             level = IPPROTO_IPV6;
             n = IPV6_MULTICAST_LOOP;
         } else
 #endif
         {
             level = IPPROTO_IP;
             n = IP_MULTICAST_LOOP;
         }
         break;
     }
     int v = -1;
     QT_SOCKOPTLEN_T len = sizeof(v);
     if (::getsockopt(socketDescriptor, level, n, (char *) &v, &len) != -1)
         return v;
     return -1;
 }
setError()
void QNativeSocketEnginePrivate::setError (QAbstractSocket::SocketError error, ErrorString errorString) const
Sets the error and error string if not set already.
Warning
This function is not part of the public interface.
The only interesting error is the first one that occurred, and not the last one.
Definition at line 194 of file qnativesocketengine.cpp.
Referenced by checkProxy(), createNewSocket(), fetchConnectionParameters(), multicastMembershipHelper(), nativeBind(), nativeConnect(), nativeListen(), nativeReceiveDatagram(), nativeSendDatagram(), and nativeWrite().
 {
     if (hasSetSocketError) {
         // Only set socket errors once for one engine; expect the
         // socket to recreate its engine after an error. Note: There's
         // one exception: SocketError(11) bypasses this as it's purely
         // a temporary internal error condition.
         // Another exception is the way the waitFor*() functions set
         // an error when a timeout occurs. After the call to setError()
         // they reset the hasSetSocketError to false
         return;
     }
     if (error != QAbstractSocket::SocketError(11))
         hasSetSocketError = true;
     socketError = error;
     switch (errorString) {
     case NonBlockingInitFailedErrorString:
         socketErrorString = QNativeSocketEngine::tr("Unable to initialize non-blocking socket");
         break;
     case BroadcastingInitFailedErrorString:
         socketErrorString = QNativeSocketEngine::tr("Unable to initialize broadcast socket");
         break;
     case NoIpV6ErrorString:
         socketErrorString = QNativeSocketEngine::tr("Attempt to use IPv6 socket on a platform with no IPv6 support");
         break;
     case RemoteHostClosedErrorString:
         socketErrorString = QNativeSocketEngine::tr("The remote host closed the connection");
         break;
     case TimeOutErrorString:
         socketErrorString = QNativeSocketEngine::tr("Network operation timed out");
         break;
     case ResourceErrorString:
         socketErrorString = QNativeSocketEngine::tr("Out of resources");
         break;
     case OperationUnsupportedErrorString:
         socketErrorString = QNativeSocketEngine::tr("Unsupported socket operation");
         break;
     case ProtocolUnsupportedErrorString:
         socketErrorString = QNativeSocketEngine::tr("Protocol type not supported");
         break;
     case InvalidSocketErrorString:
         socketErrorString = QNativeSocketEngine::tr("Invalid socket descriptor");
         break;
     case HostUnreachableErrorString:
         socketErrorString = QNativeSocketEngine::tr("Host unreachable");
         break;
     case NetworkUnreachableErrorString:
         socketErrorString = QNativeSocketEngine::tr("Network unreachable");
         break;
     case AccessErrorString:
         socketErrorString = QNativeSocketEngine::tr("Permission denied");
         break;
     case ConnectionTimeOutErrorString:
         socketErrorString = QNativeSocketEngine::tr("Connection timed out");
         break;
     case ConnectionRefusedErrorString:
         socketErrorString = QNativeSocketEngine::tr("Connection refused");
         break;
     case AddressInuseErrorString:
         socketErrorString = QNativeSocketEngine::tr("The bound address is already in use");
         break;
     case AddressNotAvailableErrorString:
         socketErrorString = QNativeSocketEngine::tr("The address is not available");
         break;
     case AddressProtectedErrorString:
         socketErrorString = QNativeSocketEngine::tr("The address is protected");
         break;
     case DatagramTooLargeErrorString:
         socketErrorString = QNativeSocketEngine::tr("Datagram was too large to send");
         break;
     case SendDatagramErrorString:
         socketErrorString = QNativeSocketEngine::tr("Unable to send a message");
         break;
     case ReceiveDatagramErrorString:
         socketErrorString = QNativeSocketEngine::tr("Unable to receive a message");
         break;
     case WriteErrorString:
         socketErrorString = QNativeSocketEngine::tr("Unable to write");
         break;
     case ReadErrorString:
         socketErrorString = QNativeSocketEngine::tr("Network error");
         break;
     case PortInuseErrorString:
         socketErrorString = QNativeSocketEngine::tr("Another socket is already listening on the same port");
         break;
     case NotSocketErrorString:
         socketErrorString = QNativeSocketEngine::tr("Operation on non-socket");
         break;
     case InvalidProxyTypeString:
         socketErrorString = QNativeSocketEngine::tr("The proxy type is invalid for this operation");
         break;
     case UnknownSocketErrorString:
         socketErrorString = QNativeSocketEngine::tr("Unknown error");
         break;
     }
 }
setOption()
bool QNativeSocketEnginePrivate::setOption (QNativeSocketEngine::SocketOption opt, int v)
Sets the socket option opt to v.
Warning
This function is not part of the public interface.
Definition at line 264 of file qnativesocketengine_unix.cpp.
 {
     Q_Q(QNativeSocketEngine);
     if (!q->isValid())
         return false;
     int n = 0;
     int level = SOL_SOCKET; // default
     switch (opt) {
     case QNativeSocketEngine::ReceiveBufferSocketOption:
         n = SO_RCVBUF;
         break;
     case QNativeSocketEngine::SendBufferSocketOption:
         n = SO_SNDBUF;
         break;
     case QNativeSocketEngine::BroadcastSocketOption:
         n = SO_BROADCAST;
         break;
     case QNativeSocketEngine::NonBlockingSocketOption: {
         // Make the socket nonblocking.
 #if !defined(Q_OS_VXWORKS)
         int flags = ::fcntl(socketDescriptor, F_GETFL, 0);
         if (flags == -1) {
 #ifdef QNATIVESOCKETENGINE_DEBUG
             perror("QNativeSocketEnginePrivate::setOption(): fcntl(F_GETFL) failed");
 #endif
             return false;
         }
         if (::fcntl(socketDescriptor, F_SETFL, flags | O_NONBLOCK) == -1) {
 #ifdef QNATIVESOCKETENGINE_DEBUG
             perror("QNativeSocketEnginePrivate::setOption(): fcntl(F_SETFL) failed");
 #endif
             return false;
         }
 #else // Q_OS_VXWORKS
         int onoff = 1;
         if (qt_safe_ioctl(socketDescriptor, FIONBIO, &onoff) < 0) {
 #ifdef QNATIVESOCKETENGINE_DEBUG
             perror("QNativeSocketEnginePrivate::setOption(): ioctl(FIONBIO, 1) failed");
 #endif
             return false;
         }
 #endif // Q_OS_VXWORKS
         return true;
     }
     case QNativeSocketEngine::AddressReusable:
 #if defined(SO_REUSEPORT)
         // on OS X, SO_REUSEADDR isn't sufficient to allow multiple binds to the
         // same port (which is useful for multicast UDP). SO_REUSEPORT is, but
         // we most definitely do not want to use this for TCP. See QTBUG-6305.
         if (socketType == QAbstractSocket::UdpSocket)
             n = SO_REUSEPORT;
         else
             n = SO_REUSEADDR;
 #else
         n = SO_REUSEADDR;
 #endif
         break;
     case QNativeSocketEngine::BindExclusively:
         return true;
     case QNativeSocketEngine::ReceiveOutOfBandData:
         n = SO_OOBINLINE;
         break;
     case QNativeSocketEngine::LowDelayOption:
         level = IPPROTO_TCP;
         n = TCP_NODELAY;
         break;
     case QNativeSocketEngine::KeepAliveOption:
         n = SO_KEEPALIVE;
         break;
     case QNativeSocketEngine::MulticastTtlOption:
 #ifndef QT_NO_IPV6
         if (socketProtocol == QAbstractSocket::IPv6Protocol) {
             level = IPPROTO_IPV6;
             n = IPV6_MULTICAST_HOPS;
         } else
 #endif
         {
             level = IPPROTO_IP;
             n = IP_MULTICAST_TTL;
         }
         break;
     case QNativeSocketEngine::MulticastLoopbackOption:
 #ifndef QT_NO_IPV6
         if (socketProtocol == QAbstractSocket::IPv6Protocol) {
             level = IPPROTO_IPV6;
             n = IPV6_MULTICAST_LOOP;
         } else
 #endif
         {
             level = IPPROTO_IP;
             n = IP_MULTICAST_LOOP;
         }
         break;
     }
     return ::setsockopt(socketDescriptor, level, n, (char *) &v, sizeof(v)) == 0;
 }
Properties
exceptNotifier
QSocketNotifier * QNativeSocketEnginePrivate::exceptNotifier
Definition at line 199 of file qnativesocketengine_p.h.
readNotifier
QSocketNotifier* QNativeSocketEnginePrivate::readNotifier
Definition at line 199 of file qnativesocketengine_p.h.
socketDescriptor
int QNativeSocketEnginePrivate::socketDescriptor
Definition at line 197 of file qnativesocketengine_p.h.
Referenced by createNewSocket(), fetchConnectionParameters(), multicastMembershipHelper(), nativeAccept(), nativeBind(), nativeBytesAvailable(), nativeClose(), nativeConnect(), nativeHasPendingDatagrams(), nativeListen(), nativeMulticastInterface(), nativePendingDatagramSize(), nativeRead(), nativeReceiveDatagram(), nativeSelect(), nativeSendDatagram(), nativeSetMulticastInterface(), nativeWrite(), option(), and setOption().
winSock
QWindowsSockInit QNativeSocketEnginePrivate::winSock
Definition at line 202 of file qnativesocketengine_p.h.
writeNotifier
QSocketNotifier * QNativeSocketEnginePrivate::writeNotifier
Definition at line 199 of file qnativesocketengine_p.h.
The documentation for this class was generated from the following files:
/src/network/socket/qnativesocketengine_p.h
/src/network/socket/qnativesocketengine.cpp
/src/network/socket/qnativesocketengine_unix.cpp
/src/network/socket/qnativesocketengine_win.cpp