Qt 4.8: QAudioDeviceInfo Class Reference
QAudioDeviceInfo Class Reference
The QAudioDeviceInfo class provides an interface to query audio devices and their functionality.
#include <qaudiodeviceinfo.h>
Public Functions
QString deviceName () const
Returns human readable name of audio device.
bool isFormatSupported (const QAudioFormat &format) const
Returns true if settings are supported by the audio device of this QAudioDeviceInfo.
bool isNull () const
Returns whether this QAudioDeviceInfo object holds a device definition.
QAudioFormat nearestFormat (const QAudioFormat &format) const
Returns closest QAudioFormat to settings that system audio supports.
QAudioDeviceInfo & operator= (const QAudioDeviceInfo &other)
Sets the QAudioDeviceInfo object to be equal to other.
QAudioFormat preferredFormat () const
Returns QAudioFormat of default settings.
QAudioDeviceInfo ()
Constructs an empty QAudioDeviceInfo object.
QAudioDeviceInfo (const QAudioDeviceInfo &other)
Constructs a copy of other.
QList< QAudioFormat::Endian > supportedByteOrders () const
Returns a list of supported byte orders.
QList< int > supportedChannelCounts () const
Returns a list of supported channel counts.
QList< int > supportedChannels () const
Use supportedChannelCount() instead.
QStringList supportedCodecs () const
Returns a list of supported codecs.
QList< int > supportedFrequencies () const
Use supportedSampleRates() instead.
QList< int > supportedSampleRates () const
Returns a list of supported sample rates.
QList< int > supportedSampleSizes () const
Returns a list of supported sample sizes.
QList< QAudioFormat::SampleType > supportedSampleTypes () const
Returns a list of supported sample types.
~QAudioDeviceInfo ()
Destroy this audio device info.
Static Public Functions
static QList< QAudioDeviceInfo > availableDevices (QAudio::Mode mode)
Returns a list of audio devices that support mode.
static QAudioDeviceInfo defaultInputDevice ()
Returns the name of the default input audio device.
static QAudioDeviceInfo defaultOutputDevice ()
Returns the name of the default output audio device.
Private Functions
QByteArray handle () const
QAudio::Mode mode () const
QAudioDeviceInfo (const QString &realm, const QByteArray &handle, QAudio::Mode mode)
QString realm () const
Properties
QSharedDataPointer< QAudioDeviceInfoPrivate > d
Friends
class QAudioDeviceFactory
Detailed Description
The QAudioDeviceInfo class provides an interface to query audio devices and their functionality.
Attention
Module: QtMultimedia
Since
4.6
QAudioDeviceInfo lets you query for audio devices–such as sound cards and USB headsets–that are currently available on the system. The audio devices available are dependent on the platform or audio plugins installed.
You can also query each device for the formats it supports. A format in this context is a set consisting of a specific byte order, channel, codec, frequency, sample rate, and sample type. A format is represented by the QAudioFormat class.
The values supported by the the device for each of these parameters can be fetched with supportedByteOrders(), supportedChannelCounts(), supportedCodecs(), supportedSampleRates(), supportedSampleSizes(), and supportedSampleTypes(). The combinations supported are dependent on the platform, audio plugins installed and the audio device capabilities. If you need a specific format, you can check if the device supports it with isFormatSupported(), or fetch a supported format that is as close as possible to the format with nearestFormat(). For instance:
        QAudioFormat format;
        format.setFrequency(44100);
... 8
        format.setSampleType(QAudioFormat::SignedInt);
        QAudioDeviceInfo info(QAudioDeviceInfo::defaultOutputDevice());
        if (!info.isFormatSupported(format))
            format = info.nearestFormat(format);
A QAudioDeviceInfo is used by Qt to construct classes that communicate with the device–such as QAudioInput, and QAudioOutput. The static functions defaultInputDevice(), defaultOutputDevice(), and availableDevices() let you get a list of all available devices. Devices are fetch according to the value of mode this is specified by the QAudio::Mode enum. The QAudioDeviceInfo returned are only valid for the QAudio::Mode.
For instance:
foreach(const QAudioDeviceInfo &deviceInfo, QAudioDeviceInfo::availableDevices(QAudio::AudioOutput))
    qDebug() << "Device name: " << deviceInfo.deviceName();
In this code sample, we loop through all devices that are able to output sound, i.e., play an audio stream in a supported format. For each device we find, we simply print the deviceName().
See also
QAudioOutput, QAudioInput
Definition at line 66 of file qaudiodeviceinfo.h.
Constructors and Destructors
QAudioDeviceInfo() [1/3]
QAudioDeviceInfo::QAudioDeviceInfo ()
Constructs an empty QAudioDeviceInfo object.
Definition at line 151 of file qaudiodeviceinfo.cpp.
                                   :
     d(new QAudioDeviceInfoPrivate)
 {
 }
QAudioDeviceInfo() [2/3]
QAudioDeviceInfo::QAudioDeviceInfo (const QAudioDeviceInfo & other)
Constructs a copy of other.
Definition at line 160 of file qaudiodeviceinfo.cpp.
                                                                :
     d(other.d)
 {
 }
~QAudioDeviceInfo()
QAudioDeviceInfo::~QAudioDeviceInfo ()
Destroy this audio device info.
Definition at line 169 of file qaudiodeviceinfo.cpp.
 {
 }
QAudioDeviceInfo() [3/3]
QAudioDeviceInfo::QAudioDeviceInfo (const QString & realm, const QByteArray & handle, QAudio::Mode mode) private
Warning
This function is not part of the public interface.
Definition at line 435 of file qaudiodeviceinfo.cpp.
                                                                                                  :
     d(new QAudioDeviceInfoPrivate(realm, handle, mode))
 {
 }
Functions
availableDevices()
QList< QAudioDeviceInfo > QAudioDeviceInfo::availableDevices (QAudio::Mode mode) static
Returns a list of audio devices that support mode.
Definition at line 425 of file qaudiodeviceinfo.cpp.
 {
     return QAudioDeviceFactory::availableDevices(mode);
 }
defaultInputDevice()
QAudioDeviceInfo QAudioDeviceInfo::defaultInputDevice () static
Returns the name of the default input audio device.
All platform and audio plugin implementations provide a default audio device to use.
Definition at line 406 of file qaudiodeviceinfo.cpp.
 {
     return QAudioDeviceFactory::defaultInputDevice();
 }
defaultOutputDevice()
QAudioDeviceInfo QAudioDeviceInfo::defaultOutputDevice () static
Returns the name of the default output audio device.
All platform and audio plugin implementations provide a default audio device to use.
Definition at line 416 of file qaudiodeviceinfo.cpp.
 {
     return QAudioDeviceFactory::defaultOutputDevice();
 }
deviceName()
QString QAudioDeviceInfo::deviceName () const
Returns human readable name of audio device.
Device names vary depending on platform/audio plugin being used.
They are a unique string identifiers for the audio device.
eg. default, Intel, U0x46d0x9a4
Definition at line 202 of file qaudiodeviceinfo.cpp.
 {
     return isNull() ? QString() : d->info->deviceName();
 }
handle()
QByteArray QAudioDeviceInfo::handle () const private
Warning
This function is not part of the public interface.
Definition at line 453 of file qaudiodeviceinfo.cpp.
Referenced by QAudioDeviceFactory::createInputDevice(), and QAudioDeviceFactory::createOutputDevice().
 {
     return d->handle;
 }
isFormatSupported()
bool QAudioDeviceInfo::isFormatSupported (const QAudioFormat & format) const
Returns true if settings are supported by the audio device of this QAudioDeviceInfo.
Definition at line 211 of file qaudiodeviceinfo.cpp.
Referenced by nearestFormat().
 {
     return isNull() ? false : d->info->isFormatSupported(settings);
 }
isNull()
bool QAudioDeviceInfo::isNull () const
Returns whether this QAudioDeviceInfo object holds a device definition.
Definition at line 187 of file qaudiodeviceinfo.cpp.
Referenced by QAudioDeviceFactory::createInputDevice(), QAudioDeviceFactory::createOutputDevice(), deviceName(), isFormatSupported(), preferredFormat(), supportedByteOrders(), supportedChannels(), supportedCodecs(), supportedFrequencies(), supportedSampleSizes(), and supportedSampleTypes().
 {
     return d->info == 0;
 }
mode()
QAudio::Mode QAudioDeviceInfo::mode () const private
Warning
This function is not part of the public interface.
Definition at line 463 of file qaudiodeviceinfo.cpp.
 {
     return d->mode;
 }
nearestFormat()
QAudioFormat QAudioDeviceInfo::nearestFormat (const QAudioFormat & settings) const
Returns closest QAudioFormat to settings that system audio supports.
These settings are provided by the platform/audio plugin being used.
They also are dependent on the QAudio::Mode being used.
Definition at line 243 of file qaudiodeviceinfo.cpp.
 {
     if (isFormatSupported(settings))
         return settings;
     QAudioFormat nearest = settings;
     nearest.setCodec(QLatin1String("audio/pcm"));
     if (nearest.sampleType() == QAudioFormat::Unknown) {
         QAudioFormat preferred = preferredFormat();
         nearest.setSampleType(preferred.sampleType());
     }
     QMap<int,int> testFrequencies;
     QList<int> frequenciesAvailable = supportedFrequencies();
     QMap<int,int> testSampleSizes;
     QList<int> sampleSizesAvailable = supportedSampleSizes();
     // Get sorted sampleSizes (equal to and ascending values only)
     if (sampleSizesAvailable.contains(settings.sampleSize()))
         testSampleSizes.insert(0,settings.sampleSize());
     sampleSizesAvailable.removeAll(settings.sampleSize());
     foreach (int size, sampleSizesAvailable) {
         int larger  = (size > settings.sampleSize()) ? size : settings.sampleSize();
         int smaller = (size > settings.sampleSize()) ? settings.sampleSize() : size;
         if (size >= settings.sampleSize()) {
             int diff = larger - smaller;
             testSampleSizes.insert(diff, size);
         }
     }
     // Get sorted frequencies (equal to and ascending values only)
     if (frequenciesAvailable.contains(settings.frequency()))
         testFrequencies.insert(0,settings.frequency());
     frequenciesAvailable.removeAll(settings.frequency());
     foreach (int frequency, frequenciesAvailable) {
         int larger  = (frequency > settings.frequency()) ? frequency : settings.frequency();
         int smaller = (frequency > settings.frequency()) ? settings.frequency() : frequency;
         if (frequency >= settings.frequency()) {
             int diff = larger - smaller;
             testFrequencies.insert(diff, frequency);
         }
     }
     // Try to find nearest
     // Check ascending frequencies, ascending sampleSizes
     QMapIterator<int, int> sz(testSampleSizes);
     while (sz.hasNext()) {
         sz.next();
         nearest.setSampleSize(sz.value());
         QMapIterator<int, int> i(testFrequencies);
         while (i.hasNext()) {
             i.next();
             nearest.setFrequency(i.value());
             if (isFormatSupported(nearest))
                 return nearest;
         }
     }
     //Fallback
     return preferredFormat();
 }
operator=()
QAudioDeviceInfo & QAudioDeviceInfo::operator= (const QAudioDeviceInfo & other)
Sets the QAudioDeviceInfo object to be equal to other.
Definition at line 177 of file qaudiodeviceinfo.cpp.
 {
     d = other.d;
     return *this;
 }
preferredFormat()
QAudioFormat QAudioDeviceInfo::preferredFormat () const
Returns QAudioFormat of default settings.
These settings are provided by the platform/audio plugin being used.
They also are dependent on the QAudio::Mode being used.
A typical audio system would provide something like:
Input settings: 8000Hz mono 8 bit.
Output settings: 44100Hz stereo 16 bit little endian.
Definition at line 230 of file qaudiodeviceinfo.cpp.
Referenced by nearestFormat().
 {
     return isNull() ? QAudioFormat() : d->info->preferredFormat();
 }
realm()
QString QAudioDeviceInfo::realm () const private
Warning
This function is not part of the public interface.
Definition at line 444 of file qaudiodeviceinfo.cpp.
Referenced by QAudioDeviceFactory::createInputDevice(), and QAudioDeviceFactory::createOutputDevice().
 {
     return d->realm;
 }
supportedByteOrders()
QList< QAudioFormat::Endian > QAudioDeviceInfo::supportedByteOrders () const
Returns a list of supported byte orders.
Definition at line 387 of file qaudiodeviceinfo.cpp.
 {
     return isNull() ? QList<QAudioFormat::Endian>() : d->info->byteOrderList();
 }
supportedChannelCounts()
QList< int > QAudioDeviceInfo::supportedChannelCounts () const
Returns a list of supported channel counts.
Since
4.7
Definition at line 355 of file qaudiodeviceinfo.cpp.
 {
     return supportedChannels();
 }
supportedChannels()
QList< int > QAudioDeviceInfo::supportedChannels () const
Use supportedChannelCount() instead.
Definition at line 369 of file qaudiodeviceinfo.cpp.
Referenced by supportedChannelCounts().
 {
     return isNull() ? QList<int>() : d->info->channelsList();
 }
supportedCodecs()
QStringList QAudioDeviceInfo::supportedCodecs () const
Returns a list of supported codecs.
All platform and plugin implementations should provide support for:
"audio/pcm" - Linear PCM
For writing plugins to support additional codecs refer to:
http://www.iana.org/assignments/media-types/audio/
Definition at line 319 of file qaudiodeviceinfo.cpp.
 {
     return isNull() ? QStringList() : d->info->codecList();
 }
supportedFrequencies()
QList< int > QAudioDeviceInfo::supportedFrequencies () const
Use supportedSampleRates() instead.
Definition at line 344 of file qaudiodeviceinfo.cpp.
Referenced by nearestFormat(), and supportedSampleRates().
 {
     return isNull() ? QList<int>() : d->info->frequencyList();
 }
supportedSampleRates()
QList< int > QAudioDeviceInfo::supportedSampleRates () const
Returns a list of supported sample rates.
Since
4.7
Definition at line 330 of file qaudiodeviceinfo.cpp.
 {
     return supportedFrequencies();
 }
supportedSampleSizes()
QList< int > QAudioDeviceInfo::supportedSampleSizes () const
Returns a list of supported sample sizes.
Definition at line 378 of file qaudiodeviceinfo.cpp.
Referenced by nearestFormat().
 {
     return isNull() ? QList<int>() : d->info->sampleSizeList();
 }
supportedSampleTypes()
QList< QAudioFormat::SampleType > QAudioDeviceInfo::supportedSampleTypes () const
Returns a list of supported sample types.
Definition at line 396 of file qaudiodeviceinfo.cpp.
 {
     return isNull() ? QList<QAudioFormat::SampleType>() : d->info->sampleTypeList();
 }
Friends and Related Functions
QAudioDeviceFactory
friend class QAudioDeviceFactory friend
Definition at line 68 of file qaudiodeviceinfo.h.
Properties
d
QSharedDataPointer<QAudioDeviceInfoPrivate> QAudioDeviceInfo::d private
Definition at line 105 of file qaudiodeviceinfo.h.
Referenced by deviceName(), handle(), isFormatSupported(), isNull(), mode(), operator=(), preferredFormat(), realm(), supportedByteOrders(), supportedChannels(), supportedCodecs(), supportedFrequencies(), supportedSampleSizes(), and supportedSampleTypes().
The documentation for this class was generated from the following files:
/src/multimedia/audio/qaudiodeviceinfo.h
/src/multimedia/audio/qaudiodeviceinfo.cpp