Qt 4.8: QWindowsVistaAnimation Class Reference
QWindowsVistaAnimation Class Reference
#include <qwindowsvistastyle_p.h>
Public Functions
virtual void paint (QPainter *painter, const QStyleOption *option)
QWindowsVistaAnimation ()
bool running () const
void setRunning (bool val)
void setStartTime (const QTime &startTime)
void setWidget (QWidget *widget)
const QTime & startTime () const
QWidget * widget () const
virtual ~QWindowsVistaAnimation ()
Protected Functions
void drawBlendedImage (QPainter *painter, QRect rect, float value)
Protected Variables
QImage _primaryImage
bool _running
QImage _secondaryImage
QTime _startTime
QImage _tempImage
QPointer< QWidget > _widget
Detailed Description
Definition at line 140 of file qwindowsvistastyle_p.h.
Constructors and Destructors
QWindowsVistaAnimation()
QWindowsVistaAnimation::QWindowsVistaAnimation () inline
Definition at line 143 of file qwindowsvistastyle_p.h.
 : _running(true) { }
~QWindowsVistaAnimation()
virtual QWindowsVistaAnimation::~QWindowsVistaAnimation () inline virtual
Definition at line 144 of file qwindowsvistastyle_p.h.
 { }
Functions
drawBlendedImage()
void QWindowsVistaAnimation::drawBlendedImage (QPainter * painter, QRect rect, float alpha) protected
Warning
This function is not part of the public interface.
Helperfunction to paint the current transition state between two animation frames.
The result is a blended image consisting of ((alpha)*_primaryImage)
((1-alpha)*_secondaryImage)
Definition at line 216 of file qwindowsvistastyle.cpp.
Referenced by setStartTime().
{
     if (_secondaryImage.isNull() || _primaryImage.isNull())
         return;
     if (_tempImage.isNull())
         _tempImage = _secondaryImage;
     const int a = qRound(alpha*256);
     const int ia = 256 - a;
     const int sw = _primaryImage.width();
     const int sh = _primaryImage.height();
     const int bpl = _primaryImage.bytesPerLine();
     switch(_primaryImage.depth()) {
     case 32:
         {
             uchar *mixed_data = _tempImage.bits();
             const uchar *back_data = _primaryImage.bits();
             const uchar *front_data = _secondaryImage.bits();
             for (int sy = 0; sy < sh; sy++) {
                 quint32* mixed = (quint32*)mixed_data;
                 const quint32* back = (const quint32*)back_data;
                 const quint32* front = (const quint32*)front_data;
                 for (int sx = 0; sx < sw; sx++) {
                     quint32 bp = back[sx];
                     quint32 fp = front[sx];
                     mixed[sx] =  qRgba ((qRed(bp)*ia + qRed(fp)*a)>>8,
                                         (qGreen(bp)*ia + qGreen(fp)*a)>>8,
                                         (qBlue(bp)*ia + qBlue(fp)*a)>>8,
                                         (qAlpha(bp)*ia + qAlpha(fp)*a)>>8);
                 }
                 mixed_data += bpl;
                 back_data += bpl;
                 front_data += bpl;
             }
         }
     default:
         break;
     }
     painter->drawImage(rect, _tempImage);
 }
paint()
void QWindowsVistaAnimation::paint (QPainter * painter, const QStyleOption * option) virtual
Reimplemented in QWindowsVistaPulse, and QWindowsVistaTransition.
Definition at line 201 of file qwindowsvistastyle.cpp.
Referenced by QWindowsVistaStyle::drawControl(), QWindowsVistaStyle::drawPrimitive(), QWindowsVistaPulse::setAlternateImage(), QWindowsVistaTransition::setEndImage(), and setStartTime().
 {
     Q_UNUSED(option);
     Q_UNUSED(painter);
 }
running()
bool QWindowsVistaAnimation::running () const inline
Definition at line 146 of file qwindowsvistastyle_p.h.
 { return _running; }
setRunning()
void QWindowsVistaAnimation::setRunning (bool val) inline
Definition at line 148 of file qwindowsvistastyle_p.h.
 { _running = val; }
setStartTime()
void QWindowsVistaAnimation::setStartTime (const QTime & startTime) inline
Definition at line 150 of file qwindowsvistastyle_p.h.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), and QWindowsVistaStyle::drawPrimitive().
 { _startTime = startTime; }
setWidget()
void QWindowsVistaAnimation::setWidget (QWidget * widget) inline
Definition at line 149 of file qwindowsvistastyle_p.h.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), and QWindowsVistaStyle::drawPrimitive().
 { _widget = widget; }
startTime()
const QTime& QWindowsVistaAnimation::startTime () const inline
Definition at line 147 of file qwindowsvistastyle_p.h.
Referenced by setStartTime().
 { return _startTime; }
widget()
QWidget* QWindowsVistaAnimation::widget () const inline
Definition at line 145 of file qwindowsvistastyle_p.h.
Referenced by setWidget(), QWindowsVistaStylePrivate::startAnimation(), and QWindowsVistaStylePrivate::widgetAnimation().
 { return _widget; }
Properties
_primaryImage
QImage QWindowsVistaAnimation::_primaryImage protected
Definition at line 157 of file qwindowsvistastyle_p.h.
Referenced by QWindowsVistaPulse::setPrimaryImage(), and QWindowsVistaTransition::setStartImage().
_running
bool QWindowsVistaAnimation::_running protected
Definition at line 160 of file qwindowsvistastyle_p.h.
Referenced by running(), and setRunning().
_secondaryImage
QImage QWindowsVistaAnimation::_secondaryImage protected
Definition at line 158 of file qwindowsvistastyle_p.h.
Referenced by QWindowsVistaPulse::setAlternateImage(), and QWindowsVistaTransition::setEndImage().
_startTime
QTime QWindowsVistaAnimation::_startTime protected
Definition at line 155 of file qwindowsvistastyle_p.h.
Referenced by setStartTime(), and startTime().
_tempImage
QImage QWindowsVistaAnimation::_tempImage protected
Definition at line 159 of file qwindowsvistastyle_p.h.
_widget
QPointer<QWidget> QWindowsVistaAnimation::_widget protected
Definition at line 156 of file qwindowsvistastyle_p.h.
Referenced by setWidget(), and widget().
The documentation for this class was generated from the following files:
/src/gui/styles/qwindowsvistastyle_p.h
/src/gui/styles/qwindowsvistastyle.cpp