Qt 4.8: QFileIconProvider Class Reference
QFileIconProvider Class Reference
The QFileIconProvider class provides file icons for the QDirModel and the QFileSystemModel classes.
#include <qfileiconprovider.h>
Public Types
enum IconType {
Computer, Desktop, Trashcan, Network,
Drive, Folder, File
}
Public Functions
virtual QIcon icon (IconType type) const
Returns an icon set for the given type.
virtual QIcon icon (const QFileInfo &info) const
Returns an icon for the file described by info.
QFileIconProvider ()
Constructs a file icon provider.
virtual QString type (const QFileInfo &info) const
Returns the type of the file described by info.
virtual ~QFileIconProvider ()
Destroys the file icon provider.
Properties
QScopedPointer< QFileIconProviderPrivate > d_ptr
Friends
class QFileDialog
Detailed Description
The QFileIconProvider class provides file icons for the QDirModel and the QFileSystemModel classes.
Definition at line 59 of file qfileiconprovider.h.
Enumerations
IconType
enum QFileIconProvider::IconType
Computer
Desktop
Trashcan
Network
Drive
Folder
File
Enumerator
Computer
Desktop
Trashcan
Network
Drive
Folder
File
Definition at line 64 of file qfileiconprovider.h.
 { Computer, Desktop, Trashcan, Network, Drive, Folder, File };
Constructors and Destructors
QFileIconProvider()
QFileIconProvider::QFileIconProvider ()
Constructs a file icon provider.
Definition at line 165 of file qfileiconprovider.cpp.
     : d_ptr(new QFileIconProviderPrivate)
 {
 }
~QFileIconProvider()
QFileIconProvider::~QFileIconProvider () virtual
Destroys the file icon provider.
Definition at line 175 of file qfileiconprovider.cpp.
 {
 }
Functions
icon() [1/2]
QIcon QFileIconProvider::icon (IconType type) const virtual
Returns an icon set for the given type.
Definition at line 183 of file qfileiconprovider.cpp.
Referenced by QFileInfoGatherer::getInfo(), icon(), QUrlModel::setUrl(), and QFileSystemModelPrivate::QFileSystemNode::updateIcon().
 {
     Q_D(const QFileIconProvider);
     switch (type) {
     case Computer:
         return d->getIcon(QStyle::SP_ComputerIcon);
     case Desktop:
         return d->getIcon(QStyle::SP_DesktopIcon);
     case Trashcan:
         return d->getIcon(QStyle::SP_TrashIcon);
     case Network:
         return d->getIcon(QStyle::SP_DriveNetIcon);
     case Drive:
         return d->getIcon(QStyle::SP_DriveHDIcon);
     case Folder:
         return d->getIcon(QStyle::SP_DirIcon);
     case File:
         return d->getIcon(QStyle::SP_FileIcon);
     default:
         break;
     };
     return QIcon();
 }
icon() [2/2]
QIcon QFileIconProvider::icon (const QFileInfo & info) const virtual
Returns an icon for the file described by info.
Definition at line 410 of file qfileiconprovider.cpp.
 {
     Q_D(const QFileIconProvider);
     QIcon platformIcon = qt_guiPlatformPlugin()->fileSystemIcon(info);
     if (!platformIcon.isNull())
         return platformIcon;
 #if defined(Q_WS_X11) && !defined(QT_NO_STYLE_GTK)
     if (X11->desktopEnvironment == DE_GNOME) {
         QIcon gtkIcon = QGtkStylePrivate::getFilesystemIcon(info);
         if (!gtkIcon.isNull())
             return gtkIcon;
     }
 #endif
 #ifdef Q_WS_MAC
     QIcon retIcon = d->getMacIcon(info);
     if (!retIcon.isNull())
         return retIcon;
 #elif defined Q_WS_WIN
     QIcon icon = d->getWinIcon(info);
     if (!icon.isNull())
         return icon;
 #endif
     if (info.isRoot())
 #if defined (Q_WS_WIN) && !defined(Q_WS_WINCE)
     {
         UINT type = GetDriveType((wchar_t *)info.absoluteFilePath().utf16());
         switch (type) {
         case DRIVE_REMOVABLE:
             return d->getIcon(QStyle::SP_DriveFDIcon);
         case DRIVE_FIXED:
             return d->getIcon(QStyle::SP_DriveHDIcon);
         case DRIVE_REMOTE:
             return d->getIcon(QStyle::SP_DriveNetIcon);
         case DRIVE_CDROM:
             return d->getIcon(QStyle::SP_DriveCDIcon);
         case DRIVE_RAMDISK:
         case DRIVE_UNKNOWN:
         case DRIVE_NO_ROOT_DIR:
         default:
             return d->getIcon(QStyle::SP_DriveHDIcon);
         }
     }
 #else
     return d->getIcon(QStyle::SP_DriveHDIcon);
 #endif
     if (info.isFile()) {
         if (info.isSymLink())
             return d->getIcon(QStyle::SP_FileLinkIcon);
         else
             return d->getIcon(QStyle::SP_FileIcon);
     }
   if (info.isDir()) {
     if (info.isSymLink()) {
       return d->getIcon(QStyle::SP_DirLinkIcon);
     } else {
       if (info.absoluteFilePath() == d->homePath) {
         return d->getIcon(QStyle::SP_DirHomeIcon);
       } else {
         return d->getIcon(QStyle::SP_DirIcon);
       }
     }
   }
   return QIcon();
 }
type()
QString QFileIconProvider::type (const QFileInfo & info) const virtual
Returns the type of the file described by info.
Definition at line 483 of file qfileiconprovider.cpp.
Referenced by QFileInfoGatherer::getInfo(), icon(), QFileSystemModelPrivate::QFileSystemNode::retranslateStrings(), and QDirModelPrivate::type().
 {
     if (info.isRoot())
         return QApplication::translate("QFileDialog", "Drive");
     if (info.isFile()) {
         if (!info.suffix().isEmpty())
             return info.suffix() + QLatin1Char(' ') + QApplication::translate("QFileDialog", "File");
         return QApplication::translate("QFileDialog", "File");
     }
     if (info.isDir())
 #ifdef Q_WS_WIN
         return QApplication::translate("QFileDialog", "File Folder", "Match Windows Explorer");
 #else
         return QApplication::translate("QFileDialog", "Folder", "All other platforms");
 #endif
     // Windows   - "File Folder"
     // OS X      - "Folder"
     // Konqueror - "Folder"
     // Nautilus  - "folder"
     if (info.isSymLink())
 #ifdef Q_OS_MAC
         return QApplication::translate("QFileDialog", "Alias", "Mac OS X Finder");
 #else
         return QApplication::translate("QFileDialog", "Shortcut", "All other platforms");
 #endif
     // OS X      - "Alias"
     // Windows   - "Shortcut"
     // Konqueror - "Folder" or "TXT File" i.e. what it is pointing to
     // Nautilus  - "link to folder" or "link to object file", same as Konqueror
     return QApplication::translate("QFileDialog", "Unknown");
 }
Friends and Related Functions
QFileDialog
friend class QFileDialog friend
Definition at line 73 of file qfileiconprovider.h.
Properties
d_ptr
QScopedPointer<QFileIconProviderPrivate> QFileIconProvider::d_ptr private
Definition at line 71 of file qfileiconprovider.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qfileiconprovider.h
/src/gui/itemviews/qfileiconprovider.cpp