Qt 4.8: QItemSelectionRange Class Reference
QItemSelectionRange Class Reference
The QItemSelectionRange class manages information about a range of selected items in a model.
#include <qitemselectionmodel.h>
Public Functions
int bottom () const
Returns the row index corresponding to the lowermost selected row in the selection range.
QModelIndex bottomRight () const
Returns the index for the item located at the bottom-right corner of the selection range.
bool contains (const QModelIndex &index) const
Returns true if the model item specified by the index lies within the range of selected items; otherwise returns false.
bool contains (int row, int column, const QModelIndex &parentIndex) const
Returns true if the model item specified by (row, column) and with parentIndex as the parent item lies within the range of selected items; otherwise returns false.
int height () const
Returns the number of selected rows in the selection range.
QModelIndexList indexes () const
Returns the list of model index items stored in the selection.
QItemSelectionRange intersect (const QItemSelectionRange &other) const
Use intersected(other) instead.
QItemSelectionRange intersected (const QItemSelectionRange &other) const
Returns a new selection range containing only the items that are found in both the selection range and the other selection range.
bool intersects (const QItemSelectionRange &other) const
Returns true if this selection range intersects (overlaps with) the other range given; otherwise returns false.
bool isEmpty () const
Returns true if the selection range contains no selectable item.
bool isValid () const
Returns true if the selection range is valid; otherwise returns false.
int left () const
Returns the column index corresponding to the leftmost selected column in the selection range.
const QAbstractItemModel * model () const
Returns the model that the items in the selection range belong to.
bool operator!= (const QItemSelectionRange &other) const
Returns true if the selection range differs from the other range given; otherwise returns false.
bool operator< (const QItemSelectionRange &other) const
bool operator== (const QItemSelectionRange &other) const
Returns true if the selection range is exactly the same as the other range given; otherwise returns false.
QModelIndex parent () const
Returns the parent model item index of the items in the selection range.
QItemSelectionRange ()
Constructs an empty selection range.
QItemSelectionRange (const QItemSelectionRange &other)
Copy constructor.
QItemSelectionRange (const QModelIndex &topLeft, const QModelIndex &bottomRight)
Constructs a new selection range containing only the index specified by the topLeft and the index bottomRight.
QItemSelectionRange (const QModelIndex &index)
Constructs a new selection range containing only the model item specified by the model index index.
int right () const
Returns the column index corresponding to the rightmost selected column in the selection range.
int top () const
Returns the row index corresponding to the uppermost selected row in the selection range.
QModelIndex topLeft () const
Returns the index for the item located at the top-left corner of the selection range.
int width () const
Returns the number of selected columns in the selection range.
Properties
QPersistentModelIndex br
QPersistentModelIndex tl
Detailed Description
The QItemSelectionRange class manages information about a range of selected items in a model.
A QItemSelectionRange contains information about a range of selected items in a model. A range of items is a contiguous array of model items, extending to cover a number of adjacent rows and columns with a common parent item; this can be visualized as a two-dimensional block of cells in a table. A selection range has a top(), left() a bottom(), right() and a parent().
The QItemSelectionRange class is one of the Model/View Classes and is part of Qt's Model/View Programming{model/view framework}.
The model items contained in the selection range can be obtained using the indexes() function. Use QItemSelectionModel::selectedIndexes() to get a list of all selected items for a view.
You can determine whether a given model item lies within a particular range by using the contains() function. Ranges can also be compared using the overloaded operators for equality and inequality, and the intersects() function allows you to determine whether two ranges overlap.
See also
{Model/View Programming}, QAbstractItemModel, QItemSelection, QItemSelectionModel
Definition at line 58 of file qitemselectionmodel.h.
Constructors and Destructors
QItemSelectionRange() [1/4]
QItemSelectionRange::QItemSelectionRange () inline
Constructs an empty selection range.
Definition at line 62 of file qitemselectionmodel.h.
Referenced by QItemSelectionModelPrivate::_q_layoutChanged(), QItemSelectionModelPrivate::_q_rowsAboutToBeRemoved(), intersect(), mergeIndexes(), QItemSelection::select(), and QItemSelection::split().
 {}
QItemSelectionRange() [2/4]
QItemSelectionRange::QItemSelectionRange (const QItemSelectionRange & other) inline
Copy constructor.
Constructs a new selection range with the same contents as the other range given.
Definition at line 63 of file qitemselectionmodel.h.
         : tl(other.tl), br(other.br) {}
QItemSelectionRange() [3/4]
QItemSelectionRange::QItemSelectionRange (const QModelIndex & topLeft, const QModelIndex & bottomRight) inline
Constructs a new selection range containing only the index specified by the topLeft and the index bottomRight.
Definition at line 144 of file qitemselectionmodel.h.
 { tl = atopLeft; br = abottomRight; }
QItemSelectionRange() [4/4]
QItemSelectionRange::QItemSelectionRange (const QModelIndex & index) inline explicit
Constructs a new selection range containing only the model item specified by the model index index.
Definition at line 66 of file qitemselectionmodel.h.
         { tl = index; br = tl; }
Functions
bottom()
int QItemSelectionRange::bottom () const inline
Returns the row index corresponding to the lowermost selected row in the selection range.
Definition at line 71 of file qitemselectionmodel.h.
Referenced by QItemSelectionModelPrivate::_q_layoutAboutToBeChanged(), QItemSelectionModelPrivate::_q_layoutChanged(), QItemSelectionModelPrivate::_q_rowsAboutToBeInserted(), QItemSelectionModelPrivate::_q_rowsAboutToBeRemoved(), QItemSelectionModel::columnIntersectsSelection(), QItemSelectionModelPrivate::expandSelection(), indexesFromRange(), intersect(), intersects(), isEmpty(), QItemSelectionModel::rowIntersectsSelection(), QItemSelection::select(), QTableWidget::selectedRanges(), QItemSelectionModel::selectedRows(), QItemSelection::split(), QTableViewPrivate::trimHiddenSelections(), QColumnView::visualRegionForSelection(), QTableView::visualRegionForSelection(), and QHeaderView::visualRegionForSelection().
 { return br.row(); }
bottomRight()
QModelIndex QItemSelectionRange::bottomRight () const inline
Returns the index for the item located at the bottom-right corner of the selection range.
See also
bottom(), right(), topLeft()
Definition at line 77 of file qitemselectionmodel.h.
Referenced by intersect(), mergeIndexes(), QTreeView::moveCursor(), operator<<(), QTreeViewPrivate::select(), QListView::visualRegionForSelection(), and QTreeView::visualRegionForSelection().
 { return QModelIndex(br); }
contains() [1/2]
bool QItemSelectionRange::contains (const QModelIndex & index) const inline
Returns true if the model item specified by the index lies within the range of selected items; otherwise returns false.
Definition at line 81 of file qitemselectionmodel.h.
Referenced by QTableView::visualRegionForSelection().
     {
         return (parent() == index.parent()
                 && tl.row() <= index.row() && tl.column() <= index.column()
                 && br.row() >= index.row() && br.column() >= index.column());
     }
contains() [2/2]
bool QItemSelectionRange::contains (int row, int column, const QModelIndex & parentIndex) const inline
Returns true if the model item specified by (row, column) and with parentIndex as the parent item lies within the range of selected items; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 88 of file qitemselectionmodel.h.
     {
         return (parent() == parentIndex
                 && tl.row() <= row && tl.column() <= column
                 && br.row() >= row && br.column() >= column);
     }
height()
int QItemSelectionRange::height () const inline
Returns the number of selected rows in the selection range.
Definition at line 74 of file qitemselectionmodel.h.
Referenced by QTableView::visualRegionForSelection().
 { return br.row() - tl.row() + 1; }
indexes()
QModelIndexList QItemSelectionRange::indexes () const
Returns the list of model index items stored in the selection.
Definition at line 386 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionModelPrivate::_q_layoutAboutToBeChanged().
 {
     QModelIndexList result;
     indexesFromRange(*this, result);
     return result;
 }
intersect()
QItemSelectionRange QItemSelectionRange::intersect (const QItemSelectionRange & other) const
Use intersected(other) instead.
Definition at line 294 of file qitemselectionmodel.cpp.
 {
     if (model() == other.model() && parent() == other.parent()) {
         QModelIndex topLeft = model()->index(qMax(top(), other.top()),
                                              qMax(left(), other.left()),
                                              other.parent());
         QModelIndex bottomRight = model()->index(qMin(bottom(), other.bottom()),
                                                  qMin(right(), other.right()),
                                                  other.parent());
         return QItemSelectionRange(topLeft, bottomRight);
     }
     return QItemSelectionRange();
 }
intersected()
QItemSelectionRange QItemSelectionRange::intersected (const QItemSelectionRange & other) const inline
Returns a new selection range containing only the items that are found in both the selection range and the other selection range.
Since
4.2
Definition at line 97 of file qitemselectionmodel.h.
Referenced by QItemSelectionModel::emitSelectionChanged(), and QItemSelection::merge().
         { return intersect(other); }
intersects()
bool QItemSelectionRange::intersects (const QItemSelectionRange & other) const
Returns true if this selection range intersects (overlaps with) the other range given; otherwise returns false.
Definition at line 262 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionModel::emitSelectionChanged(), and QItemSelection::merge().
 {
     return (isValid() && other.isValid()
             && parent() == other.parent()
             && model() == other.model()
             && ((top() <= other.top() && bottom() >= other.top())
                 || (top() >= other.top() && top() <= other.bottom()))
             && ((left() <= other.left() && right() >= other.left())
                 || (left() >= other.left() && left() <= other.right())));
 }
isEmpty()
bool QItemSelectionRange::isEmpty () const
Returns true if the selection range contains no selectable item.
Since
4.7
Definition at line 366 of file qitemselectionmodel.cpp.
Referenced by QTableView::setSelection().
 {
     if (!isValid() || !model())
         return true;
     for (int column = left(); column <= right(); ++column) {
         for (int row = top(); row <= bottom(); ++row) {
             QModelIndex index = model()->index(row, column, parent());
             Qt::ItemFlags flags = model()->flags(index);
             if ((flags & Qt::ItemIsSelectable) && (flags & Qt::ItemIsEnabled))
                 return false;
         }
     }
     return true;
 }
isValid()
bool QItemSelectionRange::isValid () const inline
Returns true if the selection range is valid; otherwise returns false.
Definition at line 129 of file qitemselectionmodel.h.
Referenced by indexesFromRange(), intersects(), isEmpty(), QTreeViewPrivate::select(), QItemSelectionModel::selection(), QTableViewPrivate::trimHiddenSelections(), QTableView::visualRegionForSelection(), QListView::visualRegionForSelection(), QTreeView::visualRegionForSelection(), and QHeaderView::visualRegionForSelection().
     {
         return (tl.isValid() && br.isValid() && tl.parent() == br.parent()
                 && top() <= bottom() && left() <= right());
     }
left()
int QItemSelectionRange::left () const inline
Returns the column index corresponding to the leftmost selected column in the selection range.
Definition at line 70 of file qitemselectionmodel.h.
Referenced by QItemSelectionModelPrivate::_q_columnsAboutToBeInserted(), QItemSelectionModelPrivate::_q_layoutAboutToBeChanged(), QItemSelectionModel::columnIntersectsSelection(), QItemSelectionModelPrivate::expandSelection(), indexesFromRange(), intersect(), intersects(), isEmpty(), QItemSelectionModel::rowIntersectsSelection(), QTreeViewPrivate::select(), QItemSelection::select(), QItemSelectionModel::selectedColumns(), QTableWidget::selectedRanges(), QItemSelection::split(), QTableViewPrivate::trimHiddenSelections(), QTableView::visualRegionForSelection(), QTreeView::visualRegionForSelection(), and QHeaderView::visualRegionForSelection().
 { return tl.column(); }
model()
const QAbstractItemModel * QItemSelectionRange::model () const inline
Returns the model that the items in the selection range belong to.
Definition at line 79 of file qitemselectionmodel.h.
Referenced by QItemSelectionModelPrivate::_q_columnsAboutToBeInserted(), QItemSelectionModelPrivate::_q_columnsAboutToBeRemoved(), QItemSelectionModelPrivate::_q_layoutAboutToBeChanged(), QItemSelectionModelPrivate::_q_layoutChanged(), QItemSelectionModelPrivate::_q_rowsAboutToBeInserted(), QItemSelectionModelPrivate::_q_rowsAboutToBeRemoved(), QItemSelectionModelPrivate::expandSelection(), indexesFromRange(), QItemSelectionModelPrivate::initModel(), intersect(), intersects(), isEmpty(), and QItemSelection::split().
 { return tl.model(); }
operator!=()
bool QItemSelectionRange::operator!= (const QItemSelectionRange & other) const inline
Returns true if the selection range differs from the other range given; otherwise returns false.
Definition at line 102 of file qitemselectionmodel.h.
         { return !operator==(other); }
operator<()
bool QItemSelectionRange::operator< (const QItemSelectionRange & other) const inline
Definition at line 104 of file qitemselectionmodel.h.
         {
             // Comparing parents will compare the models, but if two equivalent ranges
             // in two different models have invalid parents, they would appear the same
             if (other.tl.model() == tl.model()) {
                 // parent has to be calculated, so we only do so once.
                 const QModelIndex topLeftParent = tl.parent();
                 const QModelIndex otherTopLeftParent = other.tl.parent();
                 if (topLeftParent == otherTopLeftParent) {
                     if (other.tl.row() == tl.row()) {
                         if (other.tl.column() == tl.column()) {
                             if (other.br.row() == br.row()) {
                                 return br.column() < other.br.column();
                             }
                             return br.row() < other.br.row();
                         }
                         return tl.column() < other.tl.column();
                     }
                     return tl.row() < other.tl.row();
                 }
                 return topLeftParent < otherTopLeftParent;
             }
             return tl.model() < other.tl.model();
         }
operator==()
bool QItemSelectionRange::operator== (const QItemSelectionRange & other) const inline
Returns true if the selection range is exactly the same as the other range given; otherwise returns false.
Definition at line 100 of file qitemselectionmodel.h.
         { return (tl == other.tl && br == other.br); }
parent()
QModelIndex QItemSelectionRange::parent () const inline
Returns the parent model item index of the items in the selection range.
Definition at line 78 of file qitemselectionmodel.h.
Referenced by QItemSelectionModelPrivate::_q_columnsAboutToBeRemoved(), QItemSelectionModelPrivate::_q_layoutAboutToBeChanged(), QItemSelectionModelPrivate::_q_rowsAboutToBeRemoved(), QItemSelectionModelPrivate::expandSelection(), indexesFromRange(), intersect(), intersects(), isEmpty(), QTreeViewPrivate::select(), QItemSelectionModel::selectedColumns(), QItemSelectionModel::selectedRows(), QItemSelection::split(), QTableViewPrivate::trimHiddenSelections(), QTableView::visualRegionForSelection(), QTreeView::visualRegionForSelection(), and QHeaderView::visualRegionForSelection().
 { return tl.parent(); }
right()
int QItemSelectionRange::right () const inline
Returns the column index corresponding to the rightmost selected column in the selection range.
Definition at line 72 of file qitemselectionmodel.h.
Referenced by QItemSelectionModelPrivate::_q_columnsAboutToBeInserted(), QItemSelectionModelPrivate::_q_layoutAboutToBeChanged(), QItemSelectionModelPrivate::_q_layoutChanged(), QItemSelectionModel::columnIntersectsSelection(), QItemSelectionModelPrivate::expandSelection(), indexesFromRange(), intersect(), intersects(), isEmpty(), QItemSelectionModel::rowIntersectsSelection(), QItemSelection::select(), QItemSelectionModel::selectedColumns(), QTableWidget::selectedRanges(), QItemSelection::split(), QTableViewPrivate::trimHiddenSelections(), QTableView::visualRegionForSelection(), QTreeView::visualRegionForSelection(), and QHeaderView::visualRegionForSelection().
 { return br.column(); }
top()
int QItemSelectionRange::top () const inline
Returns the row index corresponding to the uppermost selected row in the selection range.
Definition at line 69 of file qitemselectionmodel.h.
Referenced by QItemSelectionModelPrivate::_q_layoutAboutToBeChanged(), QItemSelectionModelPrivate::_q_rowsAboutToBeInserted(), QItemSelectionModelPrivate::_q_rowsAboutToBeRemoved(), QItemSelectionModel::columnIntersectsSelection(), QItemSelectionModelPrivate::expandSelection(), indexesFromRange(), intersect(), intersects(), isEmpty(), QItemSelectionModel::rowIntersectsSelection(), QTreeViewPrivate::select(), QItemSelection::select(), QTableWidget::selectedRanges(), QItemSelectionModel::selectedRows(), QItemSelection::split(), QTableViewPrivate::trimHiddenSelections(), QColumnView::visualRegionForSelection(), QTableView::visualRegionForSelection(), and QHeaderView::visualRegionForSelection().
 { return tl.row(); }
topLeft()
QModelIndex QItemSelectionRange::topLeft () const inline
Returns the index for the item located at the top-left corner of the selection range.
See also
top(), left(), bottomRight()
Definition at line 76 of file qitemselectionmodel.h.
Referenced by intersect(), mergeIndexes(), QTreeView::moveCursor(), operator<<(), QListView::visualRegionForSelection(), and QTreeView::visualRegionForSelection().
 { return QModelIndex(tl); }
width()
int QItemSelectionRange::width () const inline
Returns the number of selected columns in the selection range.
Definition at line 73 of file qitemselectionmodel.h.
Referenced by QTableView::visualRegionForSelection().
 { return br.column() - tl.column() + 1; }
Properties
br
QPersistentModelIndex QItemSelectionRange::br private
Definition at line 140 of file qitemselectionmodel.h.
Referenced by QItemSelectionModelPrivate::_q_columnsAboutToBeRemoved(), QItemSelectionModelPrivate::_q_layoutChanged(), QItemSelectionModelPrivate::expandSelection(), mergeIndexes(), operator<(), operator==(), QItemSelection::select(), and QItemSelection::split().
tl
QPersistentModelIndex QItemSelectionRange::tl private
Definition at line 140 of file qitemselectionmodel.h.
Referenced by QItemSelectionModelPrivate::_q_columnsAboutToBeRemoved(), QItemSelectionModelPrivate::_q_layoutChanged(), QItemSelectionModelPrivate::expandSelection(), mergeIndexes(), operator<(), operator==(), QItemSelection::select(), and QItemSelection::split().
The documentation for this class was generated from the following files:
/src/gui/itemviews/qitemselectionmodel.h
/src/gui/itemviews/qitemselectionmodel.cpp