Qt 4.8: QMultiHash< Key, T > Class Template Reference
QMultiHash< Key, T > Class Template Reference
The QMultiHash class is a convenience QHash subclass that provides multi-valued hashes.
#include <qcontainerfwd.h>
Public Functions
QHash< Key, T >::const_iterator constFind (const Key &key, const T &value) const
Returns an iterator pointing to the item with the key and the value in the hash.
bool contains (const Key &key, const T &value) const
Returns true if the hash contains an item with the key and value; otherwise returns false.
int count (const Key &key, const T &value) const
Returns the number of items with the key and value.
QHash< Key, T >::iterator find (const Key &key, const T &value)
Returns an iterator pointing to the item with the key and value.
QHash< Key, T >::const_iterator find (const Key &key, const T &value) const
QHash< Key, T >::iterator insert (const Key &key, const T &value)
Inserts a new item with the key and a value of value.
QMultiHash operator+ (const QMultiHash &other) const
Returns a hash that contains all the items in this hash in addition to all the items in other.
QMultiHash & operator+= (const QMultiHash &other)
Inserts all the items in the other hash into this hash and returns a reference to this hash.
QMultiHash ()
Constructs an empty hash.
QMultiHash (const QHash< Key, T > &other)
Constructs a copy of other (which can be a QHash or a QMultiHash).
int remove (const Key &key, const T &value)
Removes all the items that have the key and the value value from the hash.
QHash< Key, T >::iterator replace (const Key &key, const T &value)
Inserts a new item with the key and a value of value.
void swap (QMultiHash< Key, T > &other)
Swaps hash other with this hash.
Public Functions inherited from QHash< Key, T >
iterator begin ()
Returns an STL-style iterator pointing to the first item in the hash.
const_iterator begin () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int capacity () const
Returns the number of buckets in the QHash's internal hash table.
void clear ()
Removes all items from the hash.
const_iterator constBegin () const
Returns a const STL-style iterator pointing to the first item in the hash.
const_iterator constEnd () const
Returns a const STL-style iterator pointing to the imaginary item after the last item in the hash.
const_iterator constFind (const Key &key) const
Returns an iterator pointing to the item with the key in the hash.
bool contains (const Key &key) const
Returns true if the hash contains an item with the key; otherwise returns false.
int count (const Key &key) const
Returns the number of items associated with the key.
int count () const
Same as size().
void detach ()
Detaches this hash from any other hashes with which it may share data.
bool empty () const
This function is provided for STL compatibility.
iterator end ()
Returns an STL-style iterator pointing to the imaginary item after the last item in the hash.
const_iterator end () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator erase (iterator it)
Removes the (key, value) pair associated with the iterator pos from the hash, and returns an iterator to the next item in the hash.
iterator find (const Key &key)
Returns an iterator pointing to the item with the key in the hash.
const_iterator find (const Key &key) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator insert (const Key &key, const T &value)
Inserts a new item with the key and a value of value.
iterator insertMulti (const Key &key, const T &value)
Inserts a new item with the key and a value of value.
bool isDetached () const
Returns true if the hash's internal data isn't shared with any other hash object; otherwise returns false.
bool isEmpty () const
Returns true if the hash contains no items; otherwise returns false.
bool isSharedWith (const QHash< Key, T > &other) const
const Key key (const T &value) const
Returns the first key mapped to value.
const Key key (const T &value, const Key &defaultKey) const
Returns the first key mapped to value, or defaultKey if the hash contains no item mapped to value.
QList< Key > keys () const
Returns a list containing all the keys in the hash, in an arbitrary order.
QList< Key > keys (const T &value) const
Returns a list containing all the keys associated with value value, in an arbitrary order.
bool operator!= (const QHash< Key, T > &other) const
Returns true if other is not equal to this hash; otherwise returns false.
QHash< Key, T > & operator= (const QHash< Key, T > &other)
Assigns other to this hash and returns a reference to this hash.
bool operator== (const QHash< Key, T > &other) const
Returns true if other is equal to this hash; otherwise returns false.
T & operator[] (const Key &key)
Returns the value associated with the key as a modifiable reference.
const T operator[] (const Key &key) const
Same as value().
QHash ()
Constructs an empty hash.
QHash (const QHash< Key, T > &other)
Constructs a copy of other.
int remove (const Key &key)
Removes all the items that have the key from the hash.
void reserve (int size)
Ensures that the QHash's internal hash table consists of at least size buckets.
void setSharable (bool sharable)
int size () const
Returns the number of items in the hash.
void squeeze ()
Reduces the size of the QHash's internal hash table to save memory.
void swap (QHash< Key, T > &other)
Swaps hash other with this hash.
T take (const Key &key)
Removes the item with the key from the hash and returns the value associated with it.
QList< Key > uniqueKeys () const
Returns a list containing all the keys in the map.
QHash< Key, T > & unite (const QHash< Key, T > &other)
Inserts all the items in the other hash into this hash.
const T value (const Key &key) const
Returns the value associated with the key.
const T value (const Key &key, const T &defaultValue) const
If the hash contains no item with the given key, the function returns defaultValue.
QList< T > values () const
Returns a list containing all the values in the hash, in an arbitrary order.
QList< T > values (const Key &key) const
Returns a list of all the values associated with the key, from the most recently inserted to the least recently inserted.
~QHash ()
Destroys the hash.
Private Functions
T & operator[] (const Key &key)
const T operator[] (const Key &key) const
Additional Inherited Members
Public Types inherited from QHash< Key, T >
typedef const_iterator ConstIterator
Qt-style synonym for QHash::const_iterator.
typedef qptrdiff difference_type
Typedef for ptrdiff_t.
typedef iterator Iterator
Qt-style synonym for QHash::iterator.
typedef Key key_type
Typedef for Key.
typedef T mapped_type
Typedef for T.
typedef int size_type
Typedef for int.
Related Functions inherited from QHash< Key, T >
QDataStream & operator<< (QDataStream &out, const QHash< Key, T > &hash)
Writes the hash hash to stream out.
QDataStream & operator>> (QDataStream &in, QHash< Key, T > &hash)
Reads a hash from stream in into hash.
uint qHash (const QPair< T1, T2 > &key)
Returns the hash value for the key.
uint qHash (char key)
Returns the hash value for the key.
uint qHash (uchar key)
Returns the hash value for the key.
uint qHash (signed char key)
Returns the hash value for the key.
uint qHash (ushort key)
Returns the hash value for the key.
uint qHash (short key)
Returns the hash value for the key.
uint qHash (uint key)
Returns the hash value for the key.
uint qHash (int key)
Returns the hash value for the key.
uint qHash (ulong key)
Returns the hash value for the key.
uint qHash (long key)
Returns the hash value for the key.
uint qHash (quint64 key)
Returns the hash value for the key.
uint qHash (qint64 key)
Returns the hash value for the key.
uint qHash (QChar key)
Returns the hash value for the key.
uint qHash (const QBitArray &key)
uint qHash (const QString &key)
Returns the hash value for the key.
uint qHash (const T *key)
uint qHash (const QXmlNodeModelIndex &index)
Computes a hash key from the QXmlNodeModelIndex index, and returns it.
Detailed Description
template<class Key, class T>
class QMultiHash< Key, T >
The QMultiHash class is a convenience QHash subclass that provides multi-valued hashes.
Note
This class or function is reentrant.
QMultiHash<Key, T> is one of Qt's generic container classes. It inherits QHash and extends it with a few convenience functions that make it more suitable than QHash for storing multi-valued hashes. A multi-valued hash is a hash that allows multiple values with the same key; QHash normally doesn't allow that, unless you call QHash::insertMulti().
Because QMultiHash inherits QHash, all of QHash's functionality also applies to QMultiHash. For example, you can use isEmpty() to test whether the hash is empty, and you can traverse a QMultiHash using QHash's iterator classes (for example, QHashIterator). But in addition, it provides an insert() function that corresponds to QHash::insertMulti(), and a replace() function that corresponds to QHash::insert(). It also provides convenient operator+() and operator+=().
Example:
QMultiHash<QString, int> hash1, hash2, hash3;
hash1.insert("plenty", 100);
hash1.insert("plenty", 2000);
// hash1.size() == 2
hash2.insert("plenty", 5000);
// hash2.size() == 1
hash3 = hash1 + hash2;
// hash3.size() == 3
Unlike QHash, QMultiHash provides no operator[]. Use value() or replace() if you want to access the most recently inserted item with a certain key.
If you want to retrieve all the values for a single key, you can use values(const Key &key), which returns a QList<T>:
QList<int> values = hash.values("plenty");
for (int i = 0; i < values.size(); ++i)
    cout << values.at(i) << endl;
The items that share the same key are available from most recently to least recently inserted.
A more efficient approach is to call find() to get the STL-style iterator for the first item with a key and iterate from there:
QMultiHash<QString, int>::iterator i = hash.find("plenty");
while (i != hash.end() && i.key() == "plenty") {
    cout << i.value() << endl;
    ++i;
}
QMultiHash's key and value data types must be assignable data types. You cannot, for example, store a QWidget as a value; instead, store a QWidget *. In addition, QMultiHash's key type must provide operator==(), and there must also be a global qHash() function that returns a hash value for an argument of the key's type. See the QHash documentation for details.
See also
QHash, QHashIterator, QMutableHashIterator, QMultiMap
Definition at line 58 of file qcontainerfwd.h.
Constructors and Destructors
QMultiHash() [1/2]
template<class Key, class T> QMultiHash< Key, T >::QMultiHash () inline
Constructs an empty hash.
Definition at line 927 of file qhash.h.
 {}
QMultiHash() [2/2]
template<class Key, class T> QMultiHash< Key, T >::QMultiHash (const QHash< Key, T > & other) inline
Constructs a copy of other (which can be a QHash or a QMultiHash).
See also
operator=()
Definition at line 928 of file qhash.h.
 : QHash<Key, T>(other) {}
Functions
constFind()
template<class Key, class T> typename QHash< Key, T >::const_iterator QMultiHash< Key, T >::constFind (const Key & key, const T & value) const inline
Returns an iterator pointing to the item with the key and the value in the hash.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.3
If the hash contains no such item, the function returns constEnd().
See also
QHash::constFind()
QHash::constFind()
Definition at line 992 of file qhash.h.
Referenced by QDBusConnectionPrivate::socketRead(), and QDBusConnectionPrivate::socketWrite().
         { return find(key, value); }
contains()
template<class Key, class T> Q_INLINE_TEMPLATE bool QMultiHash< Key, T >::contains (const Key & key, const T & value) const
Returns true if the hash contains an item with the key and value; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.3
See also
QHash::contains()
QHash::contains()
Definition at line 1000 of file qhash.h.
 {
     return constFind(key, value) != QHash<Key, T>::constEnd();
 }
count()
template<class Key, class T> Q_INLINE_TEMPLATE int QMultiHash< Key, T >::count (const Key & key, const T & value) const
Returns the number of items with the key and value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.3
See also
QHash::count()
QHash::count()
Definition at line 1023 of file qhash.h.
Referenced by QGraphicsAnchorLayoutPrivate::constraintsFromPaths().
 {
     int n = 0;
     typename QHash<Key, T>::const_iterator i(constFind(key));
     typename QHash<Key, T>::const_iterator end(QHash<Key, T>::constEnd());
     while (i != end && i.key() == key) {
         if (i.value() == value)
             ++n;
         ++i;
     }
     return n;
 }
find() [1/2]
template<class Key, class T> typename QHash< Key, T >::iterator QMultiHash< Key, T >::find (const Key & key, const T & value) inline
Returns an iterator pointing to the item with the key and value.
Since
4.3
If the hash contains no such item, the function returns end().
If the hash contains multiple items with the key and value, the iterator returned points to the most recently inserted item.
See also
QHash::find()
Definition at line 972 of file qhash.h.
Referenced by QMetaObject::changeGuard(), QObjectPrivate::clearGuards(), QDBusConnectionPrivate::connectRelay(), QDBusConnectionPrivate::connectSignal(), QDBusConnectionPrivate::disconnectRelay(), QDBusConnectionPrivate::disconnectSignal(), QDBusConnectionPrivate::handleSignal(), QTextFormatCollection::hasFormatCached(), QTextFormatCollection::indexForFormat(), qDBusRealToggleWatch(), qDBusRemoveWatch(), and QMetaObject::removeGuard().
{
         typename QHash<Key, T>::iterator i(find(key));
         typename QHash<Key, T>::iterator end(this->end());
         while (i != end && i.key() == key) {
             if (i.value() == value)
                 return i;
             ++i;
         }
         return end;
     }
find() [2/2]
template<class Key, class T> typename QHash< Key, T >::const_iterator QMultiHash< Key, T >::find (const Key & key, const T & value) const inline
Since
4.3 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 982 of file qhash.h.
{
         typename QHash<Key, T>::const_iterator i(constFind(key));
         typename QHash<Key, T>::const_iterator end(QHash<Key, T>::constEnd());
         while (i != end && i.key() == key) {
             if (i.value() == value)
                 return i;
             ++i;
         }
         return end;
     }
insert()
template<class Key, class T> QMultiHash::iterator QMultiHash< Key, T >::insert (const Key & key, const T & value) inline
Inserts a new item with the key and a value of value.
If there is already an item with the same key in the hash, this function will simply create a new one. (This behavior is different from replace(), which overwrites the value of an existing item.)
See also
replace()
Definition at line 934 of file qhash.h.
Referenced by QMetaObject::changeGuard(), QIcdEngine::doRequestUpdate(), QGraphicsAnchorLayoutPrivate::findPaths(), and QDBusConnectionPrivate::setConnection().
     { return QHash<Key, T>::insertMulti(key, value); }
operator+()
template<class Key, class T> QMultiHash QMultiHash< Key, T >::operator+ (const QMultiHash< Key, T > & other) const inline
Returns a hash that contains all the items in this hash in addition to all the items in other.
If a key is common to both hashes, the resulting hash will contain the key multiple times.
See also
operator+=()
Definition at line 939 of file qhash.h.
     { QMultiHash result = *this; result += other; return result; }
operator+=()
template<class Key, class T> QMultiHash & QMultiHash< Key, T >::operator+= (const QMultiHash< Key, T > & other) inline
Inserts all the items in the other hash into this hash and returns a reference to this hash.
See also
insert()
Definition at line 937 of file qhash.h.
     { this->unite(other); return *this; }
operator[]() [1/2]
template<class Key, class T> T& QMultiHash< Key, T >::operator[] (const Key & key) private
operator[]() [2/2]
template<class Key, class T> const T QMultiHash< Key, T >::operator[] (const Key & key) const private
remove()
template<class Key, class T> Q_INLINE_TEMPLATE int QMultiHash< Key, T >::remove (const Key & key, const T & value)
Removes all the items that have the key and the value value from the hash.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.3
Returns the number of items removed.
See also
QHash::remove()
QHash::remove()
Definition at line 1006 of file qhash.h.
Referenced by QIcdEngine::doRequestUpdate().
 {
     int n = 0;
     typename QHash<Key, T>::iterator i(find(key));
     typename QHash<Key, T>::iterator end(QHash<Key, T>::end());
     while (i != end && i.key() == key) {
         if (i.value() == value) {
             i = this->erase(i);
             ++n;
         } else {
             ++i;
         }
     }
     return n;
 }
replace()
template<class Key, class T> QMultiHash::iterator QMultiHash< Key, T >::replace (const Key & key, const T & value) inline
Inserts a new item with the key and a value of value.
If there is already an item with the key, that item's value is replaced with value.
If there are multiple items with the key, the most recently inserted item's value is replaced with value.
See also
insert()
Definition at line 931 of file qhash.h.
     { return QHash<Key, T>::insert(key, value); }
swap()
template<class Key, class T> void QMultiHash< Key, T >::swap (QMultiHash< Key, T > & other) inline
Swaps hash other with this hash.
Since
4.8
This operation is very fast and never fails.
Definition at line 929 of file qhash.h.
 { QHash<Key, T>::swap(other); } // prevent QMultiHash<->QHash swaps
The documentation for this class was generated from the following files:
/src/corelib/tools/qcontainerfwd.h
/src/corelib/tools/qhash.h
/src/corelib/tools/qhash.cpp