Qt 4.8: QDeclarativeStatePrivate Class Reference
QDeclarativeStatePrivate Class Reference
#include <qdeclarativestate_p_p.h>
Classes
struct OperationGuard
Public Types
typedef QList< QDeclarativeSimpleAction > SimpleActionList
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
void complete ()
QDeclarativeStateOperation::ActionList generateActionList (QDeclarativeStateGroup *) const
QDeclarativeStatePrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static void operations_append (QDeclarativeListProperty< QDeclarativeStateOperation > *prop, QDeclarativeStateOperation *op)
static QDeclarativeStateOperation * operations_at (QDeclarativeListProperty< QDeclarativeStateOperation > *prop, int index)
static void operations_clear (QDeclarativeListProperty< QDeclarativeStateOperation > *prop)
static int operations_count (QDeclarativeListProperty< QDeclarativeStateOperation > *prop)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QString extends
QDeclarativeStateGroup * group
bool inState
QString name
bool named
QList< OperationGuard > operations
QList< QDeclarativeProperty > reverting
SimpleActionList revertList
QDeclarativeTransitionManager transitionManager
QDeclarativeBinding * when
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Detailed Description
Definition at line 193 of file qdeclarativestate_p_p.h.
Typedefs
SimpleActionList
typedef QList<QDeclarativeSimpleAction> QDeclarativeStatePrivate::SimpleActionList
Definition at line 201 of file qdeclarativestate_p_p.h.
Constructors and Destructors
QDeclarativeStatePrivate()
QDeclarativeStatePrivate::QDeclarativeStatePrivate () inline
Definition at line 198 of file qdeclarativestate_p_p.h.
     : when(0), named(false), inState(false), group(0) {}
Functions
complete()
void QDeclarativeStatePrivate::complete ()
Definition at line 331 of file qdeclarativestate.cpp.
 {
     Q_Q(QDeclarativeState);
     for (int ii = 0; ii < reverting.count(); ++ii) {
         for (int jj = 0; jj < revertList.count(); ++jj) {
             if (revertList.at(jj).property() == reverting.at(ii)) {
                 revertList.removeAt(jj);
                 break;
             }
         }
     }
     reverting.clear();
     emit q->completed();
 }
generateActionList()
QDeclarativeStateOperation::ActionList QDeclarativeStatePrivate::generateActionList (QDeclarativeStateGroup * group) const
Definition at line 351 of file qdeclarativestate.cpp.
 {
     QDeclarativeStateOperation::ActionList applyList;
     if (inState)
         return applyList;
     // Prevent "extends" recursion
     inState = true;
     if (!extends.isEmpty()) {
         QList<QDeclarativeState *> states = group->states();
         for (int ii = 0; ii < states.count(); ++ii)
             if (states.at(ii)->name() == extends) {
                 qmlExecuteDeferred(states.at(ii));
                 applyList = static_cast<QDeclarativeStatePrivate*>(states.at(ii)->d_func())->generateActionList(group);
             }
     }
     foreach(QDeclarativeStateOperation *op, operations)
         applyList << op->actions();
     inState = false;
     return applyList;
 }
operations_append()
static void QDeclarativeStatePrivate::operations_append (QDeclarativeListProperty< QDeclarativeStateOperation > * prop, QDeclarativeStateOperation * op) inline static
Definition at line 220 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeState::setExtends().
{
         QList<OperationGuard> *list = static_cast<QList<OperationGuard> *>(prop->data);
         op->setState(qobject_cast<QDeclarativeState*>(prop->object));
         list->append(OperationGuard(op, list));
     }
operations_at()
static QDeclarativeStateOperation* QDeclarativeStatePrivate::operations_at (QDeclarativeListProperty< QDeclarativeStateOperation > * prop, int index) inline static
Definition at line 236 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeState::setExtends().
{
         QList<OperationGuard> *list = static_cast<QList<OperationGuard> *>(prop->data);
         return list->at(index);
     }
operations_clear()
static void QDeclarativeStatePrivate::operations_clear (QDeclarativeListProperty< QDeclarativeStateOperation > * prop) inline static
Definition at line 225 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeState::setExtends().
{
         QList<OperationGuard> *list = static_cast<QList<OperationGuard> *>(prop->data);
         QMutableListIterator<OperationGuard> listIterator(*list);
         while(listIterator.hasNext())
             listIterator.next()->setState(0);
         list->clear();
     }
operations_count()
static int QDeclarativeStatePrivate::operations_count (QDeclarativeListProperty< QDeclarativeStateOperation > * prop) inline static
Definition at line 232 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeState::setExtends().
{
         QList<OperationGuard> *list = static_cast<QList<OperationGuard> *>(prop->data);
         return list->count();
     }
Properties
extends
QString QDeclarativeStatePrivate::extends
Definition at line 245 of file qdeclarativestate_p_p.h.
group
QDeclarativeStateGroup* QDeclarativeStatePrivate::group
Definition at line 247 of file qdeclarativestate_p_p.h.
inState
bool QDeclarativeStatePrivate::inState mutable
Definition at line 246 of file qdeclarativestate_p_p.h.
name
QString QDeclarativeStatePrivate::name
Definition at line 203 of file qdeclarativestate_p_p.h.
named
bool QDeclarativeStatePrivate::named
Definition at line 205 of file qdeclarativestate_p_p.h.
operations
QList<OperationGuard> QDeclarativeStatePrivate::operations
Definition at line 218 of file qdeclarativestate_p_p.h.
reverting
QList<QDeclarativeProperty> QDeclarativeStatePrivate::reverting
Definition at line 244 of file qdeclarativestate_p_p.h.
revertList
SimpleActionList QDeclarativeStatePrivate::revertList
Definition at line 243 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeState::apply().
transitionManager
QDeclarativeTransitionManager QDeclarativeStatePrivate::transitionManager
Definition at line 241 of file qdeclarativestate_p_p.h.
when
QDeclarativeBinding* QDeclarativeStatePrivate::when
Definition at line 204 of file qdeclarativestate_p_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativestate_p_p.h
/src/declarative/util/qdeclarativestate.cpp