Qt 4.8: QDirectFbBlitter Class Reference
QDirectFbBlitter Class Reference
#include <qdirectfbblitter.h>
Public Functions
void alphaFillRect (const QRectF &rect, const QColor &color, QPainter::CompositionMode cmode)
IDirectFBSurface * dfbSurface () const
virtual void drawPixmap (const QRectF &rect, const QPixmap &pixmap, const QRectF &subrect)
void drawPixmapOpacity (const QRectF &rect, const QPixmap &pixmap, const QRectF &subrect, QPainter::CompositionMode cmode, qreal opacity)
virtual void fillRect (const QRectF &rect, const QColor &color)
QDirectFbBlitter (const QSize &size, IDirectFBSurface *surface)
QDirectFbBlitter (const QSize &size, bool alpha)
virtual ~QDirectFbBlitter ()
Public Functions inherited from QBlittable
Capabilities capabilities () const
bool isLocked () const
QImage * lock ()
Q_DECLARE_FLAGS (Capabilities, Capability)
QBlittable (const QSize &size, Capabilities caps)
QSize size () const
void unlock ()
virtual ~QBlittable ()
Static Public Functions
static DFBSurfacePixelFormat alphaPixmapFormat ()
static DFBSurfacePixelFormat pixmapFormat ()
static DFBSurfacePixelFormat selectPixmapFormat (bool withAlpha)
Protected Functions
virtual QImage * doLock ()
virtual void doUnlock ()
Protected Variables
QImage m_image
QDirectFBPointer< IDirectFBSurface > m_surface
Protected Variables inherited from QBlittable
QBlittablePrivate * d_ptr
Properties
bool m_premult
Friends
class QDirectFbConvenience
Additional Inherited Members
Public Types inherited from QBlittable
enum Capability {
SolidRectCapability = 0x0001, SourcePixmapCapability = 0x0002, SourceOverPixmapCapability = 0x0004, SourceOverScaledPixmapCapability = 0x0008,
AlphaFillRectCapability = 0x0010, OpacityPixmapCapability = 0x0020, OutlineCapability = 0x0001000
}
Detailed Description
Definition at line 53 of file qdirectfbblitter.h.
Constructors and Destructors
QDirectFbBlitter() [1/2]
QDirectFbBlitter::QDirectFbBlitter (const QSize & size, IDirectFBSurface * surface)
Definition at line 64 of file qdirectfbblitter.cpp.
Referenced by QDirectFbBlitterPlatformPixmap::createBlittable().
     : QBlittable(rect, dfb_blitter_capabilities())
         , m_surface(surface)
 {
     m_surface->AddRef(m_surface.data());
     DFBSurfaceCapabilities surfaceCaps;
     m_surface->GetCapabilities(m_surface.data(), &surfaceCaps);
     m_premult = (surfaceCaps & DSCAPS_PREMULTIPLIED);
 }
QDirectFbBlitter() [2/2]
QDirectFbBlitter::QDirectFbBlitter (const QSize & size, bool alpha)
Definition at line 75 of file qdirectfbblitter.cpp.
     : QBlittable(rect, dfb_blitter_capabilities()), m_premult(false)
 {
     DFBSurfaceDescription surfaceDesc;
     memset(&surfaceDesc,0,sizeof(DFBSurfaceDescription));
     surfaceDesc.width = rect.width();
     surfaceDesc.height = rect.height();
     // force alpha format to get AlphaFillRectCapability and ExtendedPixmapCapability support
     alpha = true;
     if (alpha) {
         m_premult = true;
         surfaceDesc.caps = DSCAPS_PREMULTIPLIED;
         surfaceDesc.pixelformat = QDirectFbBlitter::alphaPixmapFormat();
         surfaceDesc.flags = DFBSurfaceDescriptionFlags(DSDESC_WIDTH | DSDESC_HEIGHT | DSDESC_CAPS | DSDESC_PIXELFORMAT);
     } else {
         surfaceDesc.flags = DFBSurfaceDescriptionFlags(DSDESC_WIDTH | DSDESC_HEIGHT | DSDESC_PIXELFORMAT);
         surfaceDesc.pixelformat = QDirectFbBlitter::pixmapFormat();
     }
     IDirectFB *dfb = QDirectFbConvenience::dfbInterface();
     dfb->CreateSurface(dfb , &surfaceDesc, m_surface.outPtr());
     m_surface->Clear(m_surface.data(), 0, 0, 0, 0);
 }
~QDirectFbBlitter()
QDirectFbBlitter::~QDirectFbBlitter () virtual
Definition at line 101 of file qdirectfbblitter.cpp.
 {
     unlock();
 }
Functions
alphaFillRect()
void QDirectFbBlitter::alphaFillRect (const QRectF & rect, const QColor & color, QPainter::CompositionMode cmode) virtual
Reimplemented from QBlittable.
Definition at line 131 of file qdirectfbblitter.cpp.
Referenced by fillRect().
 {
     int x, y, w, h;
     DFBResult result;
     // check paramters
     rect.toRect().getRect(&x, &y ,&w, &h);
     if ((w <= 0) || (h <= 0)) return;
     if ((cmode == QPainter::CompositionMode_Source) || (color.alpha() == 255)) {
         // CompositionMode_Source case or CompositionMode_SourceOver with opaque color
         m_surface->SetDrawingFlags(m_surface.data(),
             DFBSurfaceDrawingFlags(m_premult ? (DSDRAW_NOFX | DSDRAW_SRC_PREMULTIPLY) : DSDRAW_NOFX));
         m_surface->SetPorterDuff(m_surface.data(), DSPD_SRC);
     } else {
         // CompositionMode_SourceOver case
         // check if operation is useless
         if (color.alpha() == 0)
             return;
         m_surface->SetDrawingFlags(m_surface.data(),
             DFBSurfaceDrawingFlags(m_premult ? (DSDRAW_BLEND | DSDRAW_SRC_PREMULTIPLY) : DSDRAW_BLEND));
         m_surface->SetPorterDuff(m_surface.data(), DSPD_SRC_OVER);
     }
     // set color
     m_surface->SetColor(m_surface.data(), color.red(), color.green(), color.blue(), color.alpha());
     // perform fill
     result = m_surface->FillRectangle(m_surface.data(), x, y, w, h);
     if (result != DFB_OK)
         DirectFBError("QDirectFBBlitter::alphaFillRect()", result);
 }
alphaPixmapFormat()
DFBSurfacePixelFormat QDirectFbBlitter::alphaPixmapFormat () static
Definition at line 106 of file qdirectfbblitter.cpp.
Referenced by QDirectFbBlitter(), and selectPixmapFormat().
 {
     return DSPF_ARGB;
 }
dfbSurface()
IDirectFBSurface * QDirectFbBlitter::dfbSurface () const inline
Definition at line 108 of file qdirectfbblitter.h.
 {
     return m_surface.data();
 }
doLock()
QImage * QDirectFbBlitter::doLock () protected virtual
Implements QBlittable.
Definition at line 213 of file qdirectfbblitter.cpp.
 {
     Q_ASSERT(m_surface);
     Q_ASSERT(size().isValid());
     void *mem;
     int bpl;
     const DFBResult result = m_surface->Lock(m_surface.data(), DFBSurfaceLockFlags(DSLF_WRITE|DSLF_READ), static_cast<void**>(&mem), &bpl);
     if (result == DFB_OK) {
         DFBSurfacePixelFormat dfbFormat;
         DFBSurfaceCapabilities dfbCaps;
         m_surface->GetPixelFormat(m_surface.data(), &dfbFormat);
         m_surface->GetCapabilities(m_surface.data(), &dfbCaps);
         QImage::Format format = QDirectFbConvenience::imageFormatFromSurfaceFormat(dfbFormat, dfbCaps);
         int w, h;
         m_surface->GetSize(m_surface.data(), &w, &h);
         m_image = QImage(static_cast<uchar *>(mem),w,h,bpl,format);
     } else {
         DirectFBError("Failed to lock image", result);
     }
     return &m_image;
 }
doUnlock()
void QDirectFbBlitter::doUnlock () protected virtual
Implements QBlittable.
Definition at line 319 of file qdirectfbblitter.cpp.
 {
     m_surface->Unlock(m_surface.data());
 }
drawPixmap()
void QDirectFbBlitter::drawPixmap (const QRectF & rect, const QPixmap & pixmap, const QRectF & subrect) virtual
Implements QBlittable.
Definition at line 126 of file qdirectfbblitter.cpp.
 {
     drawPixmapOpacity(rect, pixmap, srcRect, QPainter::CompositionMode_SourceOver, 1.0);
 }
drawPixmapOpacity()
void QDirectFbBlitter::drawPixmapOpacity (const QRectF & rect, const QPixmap & pixmap, const QRectF & subrect, QPainter::CompositionMode cmode, qreal opacity) virtual
Reimplemented from QBlittable.
Definition at line 168 of file qdirectfbblitter.cpp.
Referenced by drawPixmap().
 {
     QRect sQRect = subrect.toRect();
     QRect dQRect = rect.toRect();
     DFBRectangle sRect = { sQRect.x(), sQRect.y(), sQRect.width(), sQRect.height() };
     DFBRectangle dRect = { dQRect.x(), dQRect.y(), dQRect.width(), dQRect.height() };
     DFBResult result;
     // skip if dst too small
     if ((dRect.w <= 0) || (dRect.h <= 0)) return;
     // correct roundings if needed
     if (sRect.w <= 0) sRect.w = 1;
     if (sRect.h <= 0) sRect.h = 1;
     QBlittablePixmapData *blitPm = static_cast<QBlittablePixmapData*>(pixmap.pixmapData());
     QDirectFbBlitter *dfbBlitter = static_cast<QDirectFbBlitter *>(blitPm->blittable());
     dfbBlitter->unlock();
     IDirectFBSurface *s = dfbBlitter->m_surface.data();
     DFBSurfaceBlittingFlags blittingFlags = DFBSurfaceBlittingFlags(DSBLIT_BLEND_ALPHACHANNEL);
     DFBSurfacePorterDuffRule porterDuff = (cmode == QPainter::CompositionMode_SourceOver) ? DSPD_SRC_OVER : DSPD_SRC;
     if (opacity != 1.0)
     {
         blittingFlags = DFBSurfaceBlittingFlags(blittingFlags | DSBLIT_BLEND_COLORALPHA | (m_premult ? DSBLIT_SRC_PREMULTCOLOR : 0));
         m_surface->SetColor(m_surface.data(), 0xff, 0xff, 0xff, (u8) (opacity * 255.0));
     }
     m_surface->SetBlittingFlags(m_surface.data(), DFBSurfaceBlittingFlags(blittingFlags));
     m_surface->SetPorterDuff(m_surface.data(), porterDuff);
     if (cmode == QPainter::CompositionMode_SourceOver)
         m_surface->SetDstBlendFunction(m_surface.data(), DSBF_INVSRCALPHA);
     if ((sRect.w == dRect.w) && (sRect.h == dRect.h))
         result = m_surface->Blit(m_surface.data(), s, &sRect, dRect.x, dRect.y);
     else
         result = m_surface->StretchBlit(m_surface.data(), s, &sRect, &dRect);
     if (result != DFB_OK)
         DirectFBError("QDirectFBBlitter::drawPixmapExtended()", result);
 }
fillRect()
void QDirectFbBlitter::fillRect (const QRectF & rect, const QColor & color) virtual
Implements QBlittable.
Definition at line 121 of file qdirectfbblitter.cpp.
 {
     alphaFillRect(rect, color, QPainter::CompositionMode_Source);
 }
pixmapFormat()
DFBSurfacePixelFormat QDirectFbBlitter::pixmapFormat () static
Definition at line 111 of file qdirectfbblitter.cpp.
Referenced by QDirectFbBlitter(), and selectPixmapFormat().
 {
     return DSPF_RGB32;
 }
selectPixmapFormat()
DFBSurfacePixelFormat QDirectFbBlitter::selectPixmapFormat (bool withAlpha) static
Definition at line 116 of file qdirectfbblitter.cpp.
 {
     return withAlpha ? alphaPixmapFormat() : pixmapFormat();
 }
Friends and Related Functions
QDirectFbConvenience
friend class QDirectFbConvenience friend
Definition at line 78 of file qdirectfbblitter.h.
Properties
m_image
QImage QDirectFbBlitter::m_image protected
Definition at line 76 of file qdirectfbblitter.h.
Referenced by doLock().
m_premult
bool QDirectFbBlitter::m_premult private
Definition at line 81 of file qdirectfbblitter.h.
Referenced by alphaFillRect(), drawPixmapOpacity(), and QDirectFbBlitter().
m_surface
QDirectFBPointer<IDirectFBSurface> QDirectFbBlitter::m_surface protected
Definition at line 75 of file qdirectfbblitter.h.
Referenced by alphaFillRect(), dfbSurface(), QDirectFbConvenience::dfbSurfaceForPlatformPixmap(), doLock(), doUnlock(), drawPixmapOpacity(), and QDirectFbBlitter().
The documentation for this class was generated from the following files:
/src/plugins/platforms/directfb/qdirectfbblitter.h
/src/plugins/platforms/directfb/qdirectfbblitter.cpp