Qt 4.8: QAccessibleInterface Class Reference
QAccessibleInterface Class Reference abstract
The QAccessibleInterface class defines an interface that exposes information about accessible objects.
#include <qaccessible.h>
Public Functions
QAccessibleActionInterface * actionInterface ()
virtual QString actionText (int action, Text t, int child) const =0
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
QColor backgroundColor ()
virtual int childAt (int x, int y) const =0
Returns the 1-based index of the child that contains the screen coordinates (x, y).
virtual int childCount () const =0
Returns the number of children that belong to this object.
virtual bool doAction (int action, int child, const QVariantList &params=QVariantList())=0
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
virtual int indexOfChild (const QAccessibleInterface *) const =0
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
virtual bool isValid () const =0
Returns true if all the data necessary to use this interface implementation is valid (e.
virtual int navigate (RelationFlag relation, int index, QAccessibleInterface **iface) const =0
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
virtual QObject * object () const =0
Returns a pointer to the QObject this interface implementation provides information for.
virtual QRect rect (int child) const =0
Returns the geometry of the object, or of the object's child if child is not 0.
virtual Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const =0
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
virtual Role role (int child) const =0
Returns the role of the object, or of the object's child if child is not 0.
virtual void setText (Text t, int child, const QString &text)=0
Sets the text property t of the object, or of the object's child if child is not 0, to text.
virtual State state (int child) const =0
Returns the current state of the object, or of the object's child if child is not 0.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
virtual QString text (Text t, int child) const =0
Returns the value of the text property t of the object, or of the object's child if child is not 0.
QAccessibleTextInterface * textInterface ()
virtual int userActionCount (int child) const =0
Returns the number of custom actions of the object, or of the object's child if child is not 0.
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Private Functions
QAccessible2Interface * cast_helper (QAccessible2::InterfaceType)
Additional Inherited Members
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
The QAccessibleInterface class defines an interface that exposes information about accessible objects.
Accessibility tools (also called AT Clients), such as screen readers or braille displays, require high-level information about accessible objects in an application. Accessible objects provide specialized input and output methods, making it possible for users to use accessibility tools with enabled applications (AT Servers).
Every element that the user needs to interact with or react to is an accessible object, and should provide this information. These are mainly visual objects, such as widgets and widget elements, but can also be content, such as sounds.
The AT client uses three basic concepts to acquire information about any accessible object in an application:
Properties The client can read information about accessible objects. In some cases the client can also modify these properties; such as text in a line edit.
Actions The client can invoke actions like pressing a button or .
Relationships and Navigation The client can traverse from one accessible object to another, using the relationships between objects.
The QAccessibleInterface defines the API for these three concepts.
Relationships and Navigation
The functions childCount() and indexOfChild() return the number of children of an accessible object and the index a child object has in its parent. The childAt() function returns the index of a child at a given position.
The relationTo() function provides information about how two different objects relate to each other, and navigate() allows traversing from one object to another object with a given relationship.
Properties
The central property of an accessible objects is what role() it has. Different objects can have the same role, e.g. both the "Add line" element in a scroll bar and the OK button in a dialog have the same role, "button". The role implies what kind of interaction the user can perform with the user interface element.
An object's state() property is a combination of different state flags and can describe both how the object's state differs from a "normal" state, e.g. it might be unavailable, and also how it behaves, e.g. it might be selectable.
The text() property provides textual information about the object. An object usually has a name, but can provide extended information such as a description, help text, or information about any keyboard accelerators it provides. Some objects allow changing the text() property through the setText() function, but this information is in most cases read-only.
The rect() property provides information about the geometry of an accessible object. This information is usually only available for visual objects.
Actions and Selection
To enable the user to interact with an accessible object the object must expose information about the actions that it can perform. userActionCount() returns the number of actions supported by an accessible object, and actionText() returns textual information about those actions. doAction() invokes an action.
Objects that support selections can define actions to change the selection.
Objects and children
A QAccessibleInterface provides information about the accessible object, and can also provide information for the children of that object if those children don't provide a QAccessibleInterface implementation themselves. This is practical if the object has many similar children (e.g. items in a list view), or if the children are an integral part of the object itself, for example, the different sections in a scroll bar.
If an accessible object provides information about its children through one QAccessibleInterface, the children are referenced using indexes. The index is 1-based for the children, i.e. 0 refers to the object itself, 1 to the first child, 2 to the second child, and so on.
All functions in QAccessibleInterface that take a child index relate to the object itself if the index is 0, or to the child specified. If a child provides its own interface implementation (which can be retrieved through navigation) asking the parent for information about that child will usually not succeed.
See also
QAccessible
Definition at line 370 of file qaccessible.h.
Constructors and Destructors
~QAccessibleInterface()
QAccessibleInterface::~QAccessibleInterface () inline virtual
Destroys the object.
Definition at line 373 of file qaccessible.h.
 {}
Functions
actionInterface()
QAccessibleActionInterface * QAccessibleInterface::actionInterface () inline
Warning
This function is not part of the public interface.
Definition at line 426 of file qaccessible.h.
     { return reinterpret_cast<QAccessibleActionInterface *>(cast_helper(QAccessible2::ActionInterface)); }
actionText()
QString QAccessibleInterface::actionText (int action, Text t, int child) const pure virtual
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
See also
text(), userActionCount()
Implemented in QAccessibleTitleBar, QAccessibleTable2CornerButton, QAccessibleComboBox, QAccessibleTable2HeaderCell, QAccessibleTabBar, QAccessibleTable2Cell, QAccessibleSlider, QAccessibleItemRow, QAccessibleApplication, QAccessibleWidgetEx, QAccessibleMenuItem, QAccessibleToolButton, QAccessibleObjectEx, QAccessibleTable2, QAccessibleWidget, QAccessibleObject, and QAccessibleButton.
Referenced by QWindowsAccessible::get_accDefaultAction().
backgroundColor()
QColor QAccessibleInterface::backgroundColor () inline
Warning
This function is not part of the public interface.
Definition at line 411 of file qaccessible.h.
     { return qvariant_cast<QColor>(invokeMethod(BackgroundColor)); }
cast_helper()
QAccessible2Interface * QAccessibleInterface::cast_helper (QAccessible2::InterfaceType t) private
Warning
This function is not part of the public interface.
Definition at line 1240 of file qaccessible.cpp.
 {
     if (state(0) & HasInvokeExtension)
         return static_cast<QAccessibleInterfaceEx *>(this)->interface_cast(t);
     return 0;
 }
childAt()
int QAccessibleInterface::childAt (int x, int y) const pure virtual
Returns the 1-based index of the child that contains the screen coordinates (x, y).
This function returns 0 if the point is positioned on the object itself. If the tested point is outside the boundaries of the object this function returns -1.
This function is only relyable for visible objects (invisible object might not be laid out correctly).
All visual objects provide this information.
See also
rect()
Implemented in QAccessibleMainWindow, QAccessibleTitleBar, QAccessibleDockWidget, QAccessibleCalendarWidget, QAccessibleTable2CornerButton, QAccessibleComboBox, QAccessibleMdiSubWindow, QAccessibleTable2HeaderCell, QAccessibleTable2Cell, QAccessibleStackedWidget, QAccessibleItemView, QAccessibleTree, QAccessibleTextEdit, QAccessibleItemRow, QAccessibleWidgetStack, QAccessibleApplication, QAccessibleMenuItem, QAccessibleWidgetEx, QAccessibleAbstractScrollArea, QAccessibleMenuBar, QAccessibleTable2, QAccessibleWidget, and QAccessibleMenu.
childCount()
int QAccessibleInterface::childCount () const pure virtual
Returns the number of children that belong to this object.
A child can provide accessibility information on its own (e.g. a child widget), or be a sub-element of this accessible object.
All objects provide this information.
See also
indexOfChild()
Implemented in QAccessibleMainWindow, QAccessibleTitleBar, QAccessibleDockWidget, QAccessibleCalendarWidget, QAccessibleTable2CornerButton, QAccessibleComboBox, QAccessibleWorkspace, QAccessibleTable2HeaderCell, QAccessibleMdiSubWindow, QAccessibleTabBar, QAccessibleMdiArea, QAccessibleDial, QAccessibleToolBox, QAccessibleTable2Cell, QAccessibleSlider, QAccessibleStackedWidget, QAccessibleItemView, QAccessibleScrollBar, QAccessibleTree, QAccessibleTextEdit, QAccessibleItemRow, QAccessibleWidgetStack, QAccessiblePlainTextEdit, QAccessibleDoubleSpinBox, QAccessibleApplication, QAccessibleMenuItem, QAccessibleHeader, QAccessibleWidgetEx, QAccessibleToolButton, QAccessibleMenuBar, QAccessibleAbstractScrollArea, QAccessibleTable2, QAccessibleAbstractSpinBox, QAccessibleWidget, and QAccessibleMenu.
Referenced by QAccessibleWidget::navigate(), and QAInterface::QAInterface().
doAction()
bool QAccessibleInterface::doAction (int action, int child, const QVariantList & params = QVariantList()) pure virtual
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
Returns true if the action could be executed; otherwise returns false.
action can be a predefined or a custom action.
See also
userActionCount(), actionText()
Implemented in QAccessibleTitleBar, QAccessibleTable2CornerButton, QAccessibleComboBox, QAccessibleTable2HeaderCell, QAccessibleTabBar, QAccessibleTable2Cell, QAccessibleItemRow, QAccessibleApplication, QAccessibleWidgetEx, QAccessibleMenuItem, QAccessibleToolButton, QAccessibleSpinBox, QAccessibleObjectEx, QAccessibleMenuBar, QAccessibleTable2, QAccessibleAbstractSpinBox, QAccessibleWidget, QAccessibleMenu, QAccessibleObject, and QAccessibleButton.
Referenced by QWindowsAccessible::accDoDefaultAction(), and QWindowsAccessible::accSelect().
editableTextInterface()
QAccessibleEditableTextInterface * QAccessibleInterface::editableTextInterface () inline
Warning
This function is not part of the public interface.
Definition at line 417 of file qaccessible.h.
     { return reinterpret_cast<QAccessibleEditableTextInterface *>(cast_helper(QAccessible2::EditableTextInterface)); }
foregroundColor()
QColor QAccessibleInterface::foregroundColor () inline
Warning
This function is not part of the public interface.
Definition at line 408 of file qaccessible.h.
     { return qvariant_cast<QColor>(invokeMethod(ForegroundColor)); }
imageInterface()
QAccessibleImageInterface * QAccessibleInterface::imageInterface () inline
Warning
This function is not part of the public interface.
Definition at line 429 of file qaccessible.h.
     { return reinterpret_cast<QAccessibleImageInterface *>(cast_helper(QAccessible2::ImageInterface)); }
indexOfChild()
int QAccessibleInterface::indexOfChild (const QAccessibleInterface * child) const pure virtual
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
0 is not a possible return value.
All objects provide this information about their children.
See also
childCount()
Implemented in QAccessibleMainWindow, QAccessibleTitleBar, QAccessibleDockWidget, QAccessibleCalendarWidget, QAccessibleTable2CornerButton, QAccessibleComboBox, QAccessibleWorkspace, QAccessibleTable2HeaderCell, QAccessibleMdiSubWindow, QAccessibleMdiArea, QAccessibleToolBox, QAccessibleTable2Cell, QAccessibleStackedWidget, QAccessibleItemView, QAccessibleTree, QAccessibleItemRow, QAccessibleWidgetStack, QAccessibleApplication, QAccessibleMenuItem, QAccessibleWidgetEx, QAccessibleMenuBar, QAccessibleAbstractScrollArea, QAccessibleTable2, QAccessibleMenu, and QAccessibleWidget.
Referenced by QWindowsAccessible::accNavigate(), QAccessibleWidget::navigate(), QAccessibleMenuItem::navigate(), and QAccessibleWidget::relationTo().
invokeMethod()
QVariant QAccessibleInterface::invokeMethod (Method method, int child = 0, const QVariantList & params = QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
Since
4.2
Note that the type of the returned QVariant depends on the action.
Returns an invalid QVariant if the object doesn't support the action.
Definition at line 1226 of file qaccessible.cpp.
 {
     if (!(state(0) & HasInvokeExtension))
         return QVariant();
     return static_cast<QAccessibleInterfaceEx *>(this)->invokeMethodEx(method, child, params);
 }
isValid()
bool QAccessibleInterface::isValid () const pure virtual
Returns true if all the data necessary to use this interface implementation is valid (e.
g. all pointers are non-null); otherwise returns false.
See also
object()
Implemented in QAccessibleTitleBar, QAccessibleTable2CornerButton, QAccessibleTable2HeaderCell, QAccessibleTable2Cell, QAccessibleItemView, QAccessibleItemRow, QAccessibleMenuItem, QAccessibleObjectEx, QAccessibleAbstractScrollArea, and QAccessibleObject.
navigate()
int QAccessibleInterface::navigate (RelationFlag relation, int index, QAccessibleInterface ** iface) const pure virtual
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
It is the caller's responsibility to delete *target after use.
If an object is found, target is set to point to the object, and the index of the child of target is returned. The return value is 0 if target itself is the requested object. target is set to null if this object is the target object (i.e. the requested object is a handled by this object).
If no object is found target is set to null, and the return value is -1.
The entry parameter has two different meanings:
Hierarchical and Logical relationships – if multiple objects with the requested relationship exist entry specifies which one to return. entry is 1-based, e.g. use 1 to get the first (and possibly only) object with the requested relationship.
The following code demonstrates how to use this function to navigate to the first child of an object:
QAccessibleInterface *child = 0;
int targetChild = object->navigate(Accessible::Child, 1, &child);
if (child) {
    // ...
    delete child;
}
Geometric relationships – the index of the child from which to start navigating in the specified direction. entry can be 0 to navigate to a sibling of this object, or non-null to navigate within contained children that don't provide their own accessible information.
Note that the Descendent value for relation is not supported.
All objects support navigation.
See also
relationTo(), childCount()
Implemented in QAccessibleMainWindow, QAccessibleTitleBar, QAccessibleDockWidget, QAccessibleCalendarWidget, QAccessibleTable2CornerButton, QAccessibleComboBox, QAccessibleWorkspace, QAccessibleTable2HeaderCell, QAccessibleTabBar, QAccessibleMdiSubWindow, QAccessibleMdiArea, QAccessibleToolBox, QAccessibleTable2Cell, QAccessibleStackedWidget, QAccessibleItemView, QAccessibleTree, QAccessibleGroupBox, QAccessibleItemRow, QAccessibleWidgetStack, QAccessibleDisplay, QAccessibleDoubleSpinBox, QAccessibleApplication, QAccessibleMenuItem, QAccessibleWidgetEx, QAccessibleMenuBar, QAccessibleAbstractScrollArea, QAccessibleTable2, QAccessibleAbstractSpinBox, QAccessibleMenu, and QAccessibleWidget.
Referenced by QWindowsAccessible::accHitTest(), QWindowsAccessible::accNavigate(), QWindowsAccessible::get_accChild(), QWindowsAccessible::get_accFocus(), QWindowsAccessible::get_accParent(), QWindowsAccessible::get_accSelection(), QAccessibleWidget::navigate(), QAccessibleMenu::navigate(), QAccessibleMenuItem::navigate(), QAccessibleItemRow::navigate(), QAccessibleItemView::navigate(), QAccessibleTable2Cell::navigate(), and QAccessibleWidget::relationTo().
object()
QObject * QAccessibleInterface::object () const pure virtual
Returns a pointer to the QObject this interface implementation provides information for.
See also
isValid()
Implemented in QAccessibleTitleBar, QAccessibleTable2CornerButton, QAccessibleTable2HeaderCell, QAccessibleTable2Cell, QAccessibleItemView, QAccessibleItemRow, QAccessibleMenuItem, QAccessibleObjectEx, and QAccessibleObject.
Referenced by QAccessibleWidget::indexOfChild(), QAccessibleMenu::indexOfChild(), QAccessibleAbstractScrollArea::indexOfChild(), QAccessibleMenuBar::indexOfChild(), QAccessibleApplication::indexOfChild(), QAccessibleMenuItem::indexOfChild(), QAccessibleWidgetStack::indexOfChild(), QAccessibleStackedWidget::indexOfChild(), QAccessibleToolBox::indexOfChild(), QAccessibleMdiArea::indexOfChild(), QAccessibleMdiSubWindow::indexOfChild(), QAccessibleWorkspace::indexOfChild(), QAccessibleComboBox::indexOfChild(), QAccessibleCalendarWidget::indexOfChild(), QAccessibleMainWindow::indexOfChild(), QAInterface::QAInterface(), QAccessibleWidget::relationTo(), QAccessibleApplication::relationTo(), QAccessibleMenuItem::relationTo(), QAccessibleDisplay::relationTo(), QAccessibleItemRow::relationTo(), and QAccessibleGroupBox::relationTo().
rect()
QRect QAccessibleInterface::rect (int child) const pure virtual
Returns the geometry of the object, or of the object's child if child is not 0.
The geometry is in screen coordinates.
This function is only reliable for visible objects (invisible objects might not be laid out correctly).
All visual objects provide this information.
See also
childAt()
Implemented in QAccessibleTitleBar, QAccessibleDockWidget, QAccessibleCalendarWidget, QAccessibleTable2CornerButton, QAccessibleComboBox, QAccessibleMdiSubWindow, QAccessibleTable2HeaderCell, QAccessibleTabBar, QAccessibleDial, QAccessibleSlider, QAccessibleTable2Cell, QAccessibleItemView, QAccessibleScrollBar, QAccessibleTextEdit, QAccessibleItemRow, QAccessibleDoubleSpinBox, QAccessibleMenuItem, QAccessibleHeader, QAccessibleWidgetEx, QAccessibleToolButton, QAccessibleObjectEx, QAccessibleMenuBar, QAccessibleAbstractScrollArea, QAccessibleAbstractSpinBox, QAccessibleTable2, QAccessibleObject, QAccessibleWidget, and QAccessibleMenu.
Referenced by QWindowsAccessible::accLocation(), QAccessibleWidget::navigate(), QAccessibleItemView::rect(), QAccessibleWidget::relationTo(), and QAccessibleItemRow::state().
relationTo()
QAccessible::Relation QAccessibleInterface::relationTo (int child, const QAccessibleInterface * other, int otherChild) const pure virtual
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
If child is 0 the object's own relation is returned.
The returned value indicates the relation of the called object to the other object, e.g. if this object is a child of other the return value will be Child.
The return value is a combination of the bit flags in the QAccessible::Relation enumeration.
All objects provide this information.
See also
indexOfChild(), navigate()
Implemented in QAccessibleTitleBar, QAccessibleTable2CornerButton, QAccessibleTable2HeaderCell, QAccessibleTable2Cell, QAccessibleTree, QAccessibleGroupBox, QAccessibleItemRow, QAccessibleDisplay, QAccessibleMenuItem, QAccessibleApplication, QAccessibleWidgetEx, QAccessibleTable2, and QAccessibleWidget.
Referenced by QAccessibleWidget::navigate(), and QAccessibleWidget::relationTo().
role()
QAccessible::Role QAccessibleInterface::role (int child) const pure virtual
Returns the role of the object, or of the object's child if child is not 0.
The role of an object is usually static.
All accessible objects have a role.
See also
text(), state()
Implemented in QAccessibleTitleBar, QAccessibleDockWidget, QAccessibleTextBrowser, QAccessibleComboBox, QAccessibleTable2CornerButton, QAccessibleTabBar, QAccessibleTable2HeaderCell, QAccessibleDial, QAccessibleSlider, QAccessibleTable2Cell, QAccessibleScrollBar, QAccessibleItemView, QAccessibleListBox, QAccessibleTextEdit, QAccessibleGroupBox, QAccessibleItemRow, QAccessibleDoubleSpinBox, QAccessibleApplication, QAccessibleMenuItem, QAccessibleDisplay, Q3AccessibleTextEdit, QAccessibleHeader, QAccessibleWidgetEx, QAccessibleIconView, QAccessibleToolButton, QAccessibleMenuBar, QAccessibleAbstractSpinBox, QAccessibleListView, QAccessibleWidget, QAccessibleTable2, and QAccessibleMenu.
Referenced by QWindowsAccessible::get_accRole(), QAccessibleMenu::indexOfChild(), QAccessibleTable2::indexOfChild(), QAccessibleMenuBar::indexOfChild(), QAccessibleMenuItem::indexOfChild(), QAccessibleItemRow::indexOfChild(), QAccessibleTree::indexOfChild(), QAccessibleItemView::indexOfChild(), QAccessibleDockWidget::indexOfChild(), QAccessibleTable2Cell::relationTo(), and QAccessibleWidget::role().
setText()
void QAccessibleInterface::setText (Text t, int child, const QString & text) pure virtual
Sets the text property t of the object, or of the object's child if child is not 0, to text.
Note that the text properties of most objects are read-only.
See also
text()
Implemented in QAccessibleTitleBar, QAccessibleTable2CornerButton, QAccessibleTable2HeaderCell, QAccessibleMdiSubWindow, QAccessibleToolBox, QAccessibleTable2Cell, QAccessibleItemView, QAccessibleLineEdit, QAccessibleTextEdit, QAccessibleItemRow, QAccessibleMenuItem, Q3AccessibleTextEdit, QAccessibleObjectEx, QAccessibleAbstractScrollArea, and QAccessibleObject.
Referenced by QAccessibleSimpleEditableTextInterface::deleteText(), QAccessibleSimpleEditableTextInterface::insertText(), QAccessibleSimpleEditableTextInterface::pasteText(), QAccessibleSimpleEditableTextInterface::replaceText(), and QAccessibleAbstractScrollArea::setText().
state()
QAccessible::State QAccessibleInterface::state (int child) const pure virtual
Returns the current state of the object, or of the object's child if child is not 0.
The returned value is a combination of the flags in the QAccessible::StateFlag enumeration.
All accessible objects have a state.
See also
text(), role()
Implemented in QAccessibleTitleBar, QAccessibleDockWidget, QAccessibleComboBox, QAccessibleTable2CornerButton, QAccessibleWorkspace, QAccessibleTabBar, QAccessibleTable2HeaderCell, QAccessibleMdiSubWindow, QAccessibleDial, QAccessibleMdiArea, QAccessibleToolBox, QAccessibleSlider, QAccessibleTable2Cell, QAccessibleScrollBar, QAccessibleItemView, QAccessibleLineEdit, QAccessibleListBox, QAccessibleGroupBox, QAccessibleItemRow, QAccessibleDoubleSpinBox, QAccessibleApplication, QAccessibleMenuItem, QAccessibleHeader, QAccessibleWidgetEx, QAccessibleSpinBox, QAccessibleIconView, QAccessibleToolButton, QAccessibleMenuBar, QAccessibleAbstractScrollArea, QAccessibleListView, QAccessibleWidget, QAccessibleTable2, QAccessibleMenu, and QAccessibleButton.
Referenced by QWindowsAccessible::get_accSelection(), QWindowsAccessible::get_accState(), QAccessibleWidget::navigate(), QAccessibleWidget::relationTo(), QAccessibleAbstractScrollArea::state(), and QAccessibleMenuItem::state().
supportedMethods()
QSet< Method > QAccessibleInterface::supportedMethods () inline
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
Since
4.3
See also
QAccessible::Method invokeMethod()
Definition at line 405 of file qaccessible.h.
     { return qvariant_cast<QSet<Method> >(invokeMethod(ListSupportedMethods)); }
table2Interface()
QAccessibleTable2Interface * QAccessibleInterface::table2Interface () inline
Warning
This function is not part of the public interface.
Definition at line 432 of file qaccessible.h.
Referenced by QAbstractItemViewPrivate::_q_columnsInserted(), QAbstractItemViewPrivate::_q_columnsRemoved(), QAbstractItemViewPrivate::_q_layoutChanged(), QAbstractItemViewPrivate::_q_rowsInserted(), QAbstractItemViewPrivate::_q_rowsRemoved(), QAbstractItemView::reset(), and QAccessibleTable2Cell::table().
     { return reinterpret_cast<QAccessibleTable2Interface *>(cast_helper(QAccessible2::Table2Interface)); }
tableInterface()
QAccessibleTableInterface * QAccessibleInterface::tableInterface () inline
Warning
This function is not part of the public interface.
Definition at line 423 of file qaccessible.h.
     { return reinterpret_cast<QAccessibleTableInterface *>(cast_helper(QAccessible2::TableInterface)); }
text()
QString QAccessibleInterface::text (Text t, int child) const pure virtual
Returns the value of the text property t of the object, or of the object's child if child is not 0.
The Name is a string used by clients to identify, find, or announce an accessible object for the user. All objects must have a name that is unique within their container. The name can be used differently by clients, so the name should both give a short description of the object and be unique.
An accessible object's Description provides textual information about an object's visual appearance. The description is primarily used to provide greater context for vision-impaired users, but is also used for context searching or other applications. Not all objects have a description. An "OK" button would not need a description, but a tool button that shows a picture of a smiley would.
The Value of an accessible object represents visual information contained by the object, e.g. the text in a line edit. Usually, the value can be modified by the user. Not all objects have a value, e.g. static text labels don't, and some objects have a state that already is the value, e.g. toggle buttons.
The Help text provides information about the function and usage of an accessible object. Not all objects provide this information.
The Accelerator is a keyboard shortcut that activates the object's default action. A keyboard shortcut is the underlined character in the text of a menu, menu item or widget, and is either the character itself, or a combination of this character and a modifier key like Alt, Ctrl or Shift. Command controls like tool buttons also have shortcut keys and usually display them in their tooltip.
All objects provide a string for Name .
See also
role(), state()
Implemented in QAccessibleTitleBar, QAccessibleTable2CornerButton, QAccessibleComboBox, QAccessibleTable2HeaderCell, QAccessibleTabBar, QAccessibleMdiSubWindow, QAccessibleDial, QAccessibleToolBox, QAccessibleTable2Cell, QAccessibleSlider, QAccessibleItemView, QAccessibleScrollBar, QAccessibleLineEdit, QAccessibleListBox, QAccessibleTextEdit, QAccessibleGroupBox, QAccessibleItemRow, QAccessibleMenuItem, QAccessibleDoubleSpinBox, QAccessibleApplication, QAccessibleDisplay, Q3AccessibleTextEdit, QAccessibleHeader, QAccessibleWidgetEx, QAccessibleToolButton, QAccessibleIconView, QAccessibleMenuBar, QAccessibleAbstractSpinBox, QAccessibleAbstractScrollArea, QAccessibleListView, QAccessibleTable2, QAccessibleWidget, QAccessibleMenu, and QAccessibleButton.
Referenced by QAccessibleSimpleEditableTextInterface::deleteText(), QAccessibleTable2::indexOfChild(), QAccessibleTree::indexOfChild(), QAccessibleSimpleEditableTextInterface::insertText(), QAccessibleSimpleEditableTextInterface::pasteText(), QtWndProc(), QAccessibleSimpleEditableTextInterface::replaceText(), QAccessibleAbstractScrollArea::text(), AccessibleElement::text(), and textForRange().
textInterface()
QAccessibleTextInterface * QAccessibleInterface::textInterface () inline
Warning
This function is not part of the public interface.
Definition at line 414 of file qaccessible.h.
     { return reinterpret_cast<QAccessibleTextInterface *>(cast_helper(QAccessible2::TextInterface)); }
userActionCount()
int QAccessibleInterface::userActionCount (int child) const pure virtual
Returns the number of custom actions of the object, or of the object's child if child is not 0.
The Action type enumerates predefined actions: these are not included in the returned value.
See also
actionText(), doAction()
Implemented in QAccessibleTitleBar, QAccessibleTable2CornerButton, QAccessibleTable2HeaderCell, QAccessibleTabBar, QAccessibleTable2Cell, QAccessibleItemRow, QAccessibleApplication, QAccessibleMenuItem, QAccessibleObjectEx, QAccessibleTable2, QAccessibleWidget, and QAccessibleObject.
valueInterface()
QAccessibleValueInterface * QAccessibleInterface::valueInterface () inline
Warning
This function is not part of the public interface.
Definition at line 420 of file qaccessible.h.
     { return reinterpret_cast<QAccessibleValueInterface *>(cast_helper(QAccessible2::ValueInterface)); }
The documentation for this class was generated from the following files:
/src/gui/accessible/qaccessible.h
/src/gui/accessible/qaccessible.cpp