Qt 4.8: QHttp Class Reference
QHttp Class Reference
The QHttp class provides an implementation of the HTTP protocol.
#include <qhttp.h>
Public Types
enum ConnectionMode { ConnectionModeHttp, ConnectionModeHttps }
This enum is used to specify the mode of connection to use:
enum Error {
NoError, UnknownError, HostNotFound, ConnectionRefused,
UnexpectedClose, InvalidResponseHeader, WrongContentLength, Aborted,
AuthenticationRequiredError, ProxyAuthenticationRequiredError
}
This enum identifies the error that occurred.
enum State {
Unconnected, HostLookup, Connecting, Sending,
Reading, Connected, Closing
}
This enum is used to specify the state the client is in:
Public Slots
void abort ()
Aborts the current request and deletes all scheduled requests.
void ignoreSslErrors ()
Tells the QSslSocket used for the Http connection to ignore the errors reported in the sslErrors() signal.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void authenticationRequired (const QString &hostname, quint16 port, QAuthenticator *)
void dataReadProgress (int, int)
This signal is emitted when this object reads data from a HTTP server to indicate the current progress of the download.
void dataSendProgress (int, int)
This signal is emitted when this object sends data to a HTTP server to inform it about the progress of the upload.
void done (bool)
This signal is emitted when the last pending request has finished; (it is emitted after the last request's requestFinished() signal).
void proxyAuthenticationRequired (const QNetworkProxy &proxy, QAuthenticator *)
void readyRead (const QHttpResponseHeader &resp)
This signal is emitted when there is new response data to read.
void requestFinished (int, bool)
This signal is emitted when processing the request identified by id has finished.
void requestStarted (int)
This signal is emitted when processing the request identified by id starts.
void responseHeaderReceived (const QHttpResponseHeader &resp)
This signal is emitted when the HTTP header of a server response is available.
void sslErrors (const QList< QSslError > &errors)
Forwards the sslErrors signal from the QSslSocket used in QHttp.
void stateChanged (int)
This signal is emitted when the state of the QHttp object changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
qint64 bytesAvailable () const
Returns the number of bytes that can be read from the response content at the moment.
void clearPendingRequests ()
Deletes all pending requests from the list of scheduled requests.
int close ()
Closes the connection; this is useful if you have a keep-alive connection and want to close it.
int closeConnection ()
Behaves the same as close().
QIODevice * currentDestinationDevice () const
Returns the QIODevice pointer that is used as to store the data of the HTTP request being executed.
int currentId () const
Returns the identifier of the HTTP request being executed or 0 if there is no request being executed (i.e.
QHttpRequestHeader currentRequest () const
Returns the request header of the HTTP request being executed.
QIODevice * currentSourceDevice () const
Returns the QIODevice pointer that is used as the data source of the HTTP request being executed.
Error error () const
Returns the last error that occurred.
QString errorString () const
Returns a human-readable description of the last error that occurred.
int get (const QString &path, QIODevice *to=0)
Sends a get request for path to the server set by setHost() or as specified in the constructor.
bool hasPendingRequests () const
Returns true if there are any requests scheduled that have not yet been executed; otherwise returns false.
int head (const QString &path)
Sends a header request for path to the server set by setHost() or as specified in the constructor.
QHttpResponseHeader lastResponse () const
Returns the received response header of the most recently finished HTTP request.
int post (const QString &path, QIODevice *data, QIODevice *to=0)
Sends a post request for path to the server set by setHost() or as specified in the constructor.
int post (const QString &path, const QByteArray &data, QIODevice *to=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.data is used as the content data of the HTTP request.
QHttp (QObject *parent=0)
Constructs a QHttp object.
QHttp (const QString &hostname, quint16 port=80, QObject *parent=0)
Constructs a QHttp object.
QHttp (const QString &hostname, ConnectionMode mode, quint16 port=0, QObject *parent=0)
Constructs a QHttp object.
qint64 read (char *data, qint64 maxlen)
Reads maxlen bytes from the response content into data and returns the number of bytes read.
QByteArray readAll ()
Reads all the bytes from the response content and returns them.
int request (const QHttpRequestHeader &header, QIODevice *device=0, QIODevice *to=0)
Sends a request to the server set by setHost() or as specified in the constructor.
int request (const QHttpRequestHeader &header, const QByteArray &data, QIODevice *to=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.data is used as the content data of the HTTP request.
int setHost (const QString &hostname, quint16 port=80)
Sets the HTTP server that is used for requests to hostName on port port.
int setHost (const QString &hostname, ConnectionMode mode, quint16 port=0)
Sets the HTTP server that is used for requests to hostName on port port using the connection mode mode.
int setProxy (const QString &host, int port, const QString &username=QString(), const QString &password=QString())
Enables HTTP proxy support, using the proxy server host on port port.
int setProxy (const QNetworkProxy &proxy)
Enables HTTP proxy support using the proxy settings from proxy.
int setSocket (QTcpSocket *socket)
Replaces the internal QTcpSocket that QHttp uses with socket.
int setUser (const QString &username, const QString &password=QString())
This function sets the user name userName and password password for web pages that require authentication.
State state () const
Returns the current state of the object.
virtual ~QHttp ()
Destroys the QHttp object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Friends
class QHttpCloseRequest
class QHttpNormalRequest
class QHttpPGHRequest
class QHttpSetHostRequest
class QHttpSetProxyRequest
class QHttpSetSocketRequest
class QHttpSetUserRequest
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QHttp class provides an implementation of the HTTP protocol.
Note
This class or function is reentrant.
Attention
Module: QtNetwork
This class provides a direct interface to HTTP that allows you to download and upload data with the HTTP protocol. However, for new applications, it is recommended to use QNetworkAccessManager and QNetworkReply, as those classes possess a simpler, yet more powerful API and a more modern protocol implementation.
The class works asynchronously, so there are no blocking functions. If an operation cannot be executed immediately, the function will still return straight away and the operation will be scheduled for later execution. The results of scheduled operations are reported via signals. This approach depends on the event loop being in operation.
The operations that can be scheduled (they are called "requests" in the rest of the documentation) are the following: setHost(), get(), post(), head() and request().
All of these requests return a unique identifier that allows you to keep track of the request that is currently executed. When the execution of a request starts, the requestStarted() signal with the identifier is emitted and when the request is finished, the requestFinished() signal is emitted with the identifier and a bool that indicates if the request finished with an error.
To make an HTTP request you must set up suitable HTTP headers. The following example demonstrates how to request the main HTML page from the Qt website (i.e., the URL http://qt.nokia.com/index.html):
QHttpRequestHeader header("GET", QUrl::toPercentEncoding("/index.html"));
header.setValue("Host", "qt.nokia.com");
http->setHost("qt.nokia.com");
http->request(header);
For the common HTTP requests GET, POST and HEAD, QHttp provides the convenience functions get(), post() and head(). They already use a reasonable header and if you don't have to set special header fields, they are easier to use. The above example can also be written as:
http->setHost("qt.nokia.com");                // id == 1
http->get(QUrl::toPercentEncoding("/index.html")); // id == 2
For this example the following sequence of signals is emitted (with small variations, depending on network traffic, etc.):
requestStarted(1)
requestFinished(1, false)
requestStarted(2)
stateChanged(Connecting)
stateChanged(Sending)
dataSendProgress(77, 77)
stateChanged(Reading)
responseHeaderReceived(responseheader)
dataReadProgress(5388, 0)
readyRead(responseheader)
dataReadProgress(18300, 0)
readyRead(responseheader)
stateChanged(Connected)
requestFinished(2, false)
done(false)
stateChanged(Closing)
stateChanged(Unconnected)
The dataSendProgress() and dataReadProgress() signals in the above example are useful if you want to show a progress bar to inform the user about the progress of the download. The second argument is the total size of data. In certain cases it is not possible to know the total amount in advance, in which case the second argument is 0. (If you connect to a QProgressBar a total of 0 results in a busy indicator.)
When the response header is read, it is reported with the responseHeaderReceived() signal.
The readyRead() signal tells you that there is data ready to be read. The amount of data can then be queried with the bytesAvailable() function and it can be read with the read() or readAll() functions.
If an error occurs during the execution of one of the commands in a sequence of commands, all the pending commands (i.e. scheduled, but not yet executed commands) are cleared and no signals are emitted for them.
For example, if you have the following sequence of requests
http->setHost("www.foo.bar");       // id == 1
http->get("/index.html");           // id == 2
http->post("register.html", data);  // id == 3
and the get() request fails because the host lookup fails, then the post() request is never executed and the signals would look like this:
requestStarted(1)
requestFinished(1, false)
requestStarted(2)
stateChanged(HostLookup)
requestFinished(2, true)
done(true)
stateChanged(Unconnected)
You can then get details about the error with the error() and errorString() functions. Note that only unexpected behavior, like network failure is considered as an error. If the server response contains an error status, like a 404 response, this is reported as a normal response case. So you should always check the status code of the response header.
The functions currentId() and currentRequest() provide more information about the currently executing request.
The functions hasPendingRequests() and clearPendingRequests() allow you to query and clear the list of pending requests.
See also
QFtp, QNetworkAccessManager, QNetworkRequest, QNetworkReply, {HTTP Example}, {Torrent Example}
Definition at line 173 of file qhttp.h.
Enumerations
ConnectionMode
enum QHttp::ConnectionMode
This enum is used to specify the mode of connection to use:
ConnectionModeHttp The connection is a regular HTTP connection to the server
ConnectionModeHttps The HTTPS protocol is used and the connection is encrypted using SSL.
Since
4.3
When using the HTTPS mode, care should be taken to connect to the sslErrors signal, and handle possible SSL errors.
See also
QSslSocket
Enumerator
ConnectionModeHttp
ConnectionModeHttps
Definition at line 178 of file qhttp.h.
{
         ConnectionModeHttp,
         ConnectionModeHttps
     };
Error
enum QHttp::Error
This enum identifies the error that occurred.
NoError No error occurred.
HostNotFound The host name lookup failed.
ConnectionRefused The server refused the connection.
UnexpectedClose The server closed the connection unexpectedly.
InvalidResponseHeader The server sent an invalid response header.
WrongContentLength The client could not read the content correctly because an error with respect to the content length occurred.
Aborted The request was aborted with abort().
ProxyAuthenticationRequiredError QHttp is using a proxy, and the proxy server requires authentication to establish a connection.
AuthenticationRequiredError The web server requires authentication to complete the request.
UnknownError An error other than those specified above occurred.
See also
error()
Enumerator
NoError
UnknownError
HostNotFound
ConnectionRefused
UnexpectedClose
InvalidResponseHeader
WrongContentLength
Aborted
AuthenticationRequiredError
ProxyAuthenticationRequiredError
Definition at line 197 of file qhttp.h.
                {
         NoError,
         UnknownError,
         HostNotFound,
         ConnectionRefused,
         UnexpectedClose,
         InvalidResponseHeader,
         WrongContentLength,
         Aborted,
         AuthenticationRequiredError,
         ProxyAuthenticationRequiredError
     };
State
enum QHttp::State
This enum is used to specify the state the client is in:
Unconnected There is no connection to the host.
HostLookup A host name lookup is in progress.
Connecting An attempt to connect to the host is in progress.
Sending The client is sending its request to the server.
Reading The client's request has been sent and the client is reading the server's response.
Connected The connection to the host is open, but the client is neither sending a request, nor waiting for a response.
Closing The connection is closing down, but is not yet closed. (The state will be Unconnected when the connection is closed.)
See also
stateChanged() state()
Enumerator
Unconnected
HostLookup
Connecting
Sending
Reading
Connected
Closing
Definition at line 188 of file qhttp.h.
                {
         Unconnected,
         HostLookup,
         Connecting,
         Sending,
         Reading,
         Connected,
         Closing
     };
Constructors and Destructors
QHttp() [1/3]
QHttp::QHttp (QObject * parent = 0) explicit
Constructs a QHttp object.
The parent parameter is passed on to the QObject constructor.
Definition at line 1559 of file qhttp.cpp.
     : QObject(*new QHttpPrivate, parent)
 {
     Q_D(QHttp);
     d->init();
 }
QHttp() [2/3]
QHttp::QHttp (const QString & hostName, quint16 port = 80, QObject * parent = 0)
Constructs a QHttp object.
Subsequent requests are done by connecting to the server hostName on port port.
The parent parameter is passed on to the QObject constructor.
See also
setHost()
Definition at line 1574 of file qhttp.cpp.
     : QObject(*new QHttpPrivate, parent)
 {
     Q_D(QHttp);
     d->init();
     d->hostName = hostName;
     d->port = port;
 }
QHttp() [3/3]
QHttp::QHttp (const QString & hostName, ConnectionMode mode, quint16 port = 0, QObject * parent = 0)
Constructs a QHttp object.
Subsequent requests are done by connecting to the server hostName on port port using the connection mode mode.
If port is 0, it will use the default port for the mode used (80 for Http and 443 for Https).
The parent parameter is passed on to the QObject constructor.
See also
setHost()
Definition at line 1596 of file qhttp.cpp.
     : QObject(*new QHttpPrivate, parent)
 {
     Q_D(QHttp);
     d->init();
     d->hostName = hostName;
     if (port == 0)
         port = (mode == ConnectionModeHttp) ? 80 : 443;
     d->port = port;
     d->mode = mode;
 }
~QHttp()
QHttp::~QHttp () virtual
Destroys the QHttp object.
If there is an open connection, it is closed.
Definition at line 1622 of file qhttp.cpp.
 {
     abort();
 }
Functions
abort
void QHttp::abort () slot
Aborts the current request and deletes all scheduled requests.
For the current request, the requestFinished() signal with the error argument true is emitted. For all other requests that are affected by the abort(), no signals are emitted.
Since this slot also deletes the scheduled requests, there are no requests left and the done() signal is emitted (with the error argument true).
See also
clearPendingRequests()
Definition at line 1894 of file qhttp.cpp.
Referenced by ~QHttp().
 {
     Q_D(QHttp);
     if (d->pending.isEmpty())
         return;
     d->finishedWithError(tr("Request aborted"), Aborted);
     clearPendingRequests();
     if (d->socket)
         d->socket->abort();
     d->closeConn();
 }
authenticationRequired
void QHttp::authenticationRequired (const QString & hostname, quint16 port, QAuthenticator * authenticator) signal
Since
4.3
This signal can be emitted when a web server on a given hostname and port requires authentication. The authenticator object can then be filled in with the required details to allow authentication and continue the connection.
Note
It is not possible to use a QueuedConnection to connect to this signal, as the connection will fail if the authenticator has not been filled in with new information when the signal returns.
See also
QAuthenticator, QNetworkProxy
bytesAvailable()
qint64 QHttp::bytesAvailable () const
Returns the number of bytes that can be read from the response content at the moment.
See also
get() post() request() readyRead() read() readAll()
Definition at line 1913 of file qhttp.cpp.
Referenced by readAll().
 {
     Q_D(const QHttp);
 #if defined(QHTTP_DEBUG)
     qDebug("QHttp::bytesAvailable(): %d bytes", (int)d->rba.size());
 #endif
     return qint64(d->rba.size());
 }
clearPendingRequests()
void QHttp::clearPendingRequests ()
Deletes all pending requests from the list of scheduled requests.
This does not affect the request that is being executed. If you want to stop this as well, use abort().
See also
hasPendingRequests() abort()
Definition at line 2077 of file qhttp.cpp.
Referenced by abort().
 {
     Q_D(QHttp);
     // delete all entires except the first one
     while (d->pending.count() > 1)
         delete d->pending.takeLast();
 }
close()
int QHttp::close ()
Closes the connection; this is useful if you have a keep-alive connection and want to close it.
For the requests issued with get(), post() and head(), QHttp sets the connection to be keep-alive. You can also do this using the header you pass to the request() function. QHttp only closes the connection to the HTTP server if the response header requires it to do so.
The function does not block; instead, it returns immediately. The request is scheduled, and its execution is performed asynchronously. The function returns a unique identifier which is passed by requestStarted() and requestFinished().
When the request is started the requestStarted() signal is emitted. When it is finished the requestFinished() signal is emitted.
If you want to close the connection immediately, you have to use abort() instead.
See also
stateChanged() abort() requestStarted() requestFinished() done()
Definition at line 2420 of file qhttp.cpp.
 {
     Q_D(QHttp);
     return d->addRequest(new QHttpCloseRequest());
 }
closeConnection()
int QHttp::closeConnection ()
Behaves the same as close().
Definition at line 2434 of file qhttp.cpp.
 {
     Q_D(QHttp);
     return d->addRequest(new QHttpCloseRequest());
 }
currentDestinationDevice()
QIODevice * QHttp::currentDestinationDevice () const
Returns the QIODevice pointer that is used as to store the data of the HTTP request being executed.
If there is no current request or if the request does not store the data to an IO device, this function returns 0.
This function can be used to delete the QIODevice in the slot connected to the requestFinished() signal.
See also
currentSourceDevice() get() post() request()
Definition at line 2047 of file qhttp.cpp.
 {
     Q_D(const QHttp);
     if (d->pending.isEmpty())
         return 0;
     return d->pending.first()->destinationDevice();
 }
currentId()
int QHttp::currentId () const
Returns the identifier of the HTTP request being executed or 0 if there is no request being executed (i.e.
they've all finished).
See also
currentRequest()
Definition at line 1979 of file qhttp.cpp.
 {
     Q_D(const QHttp);
     if (d->pending.isEmpty())
         return 0;
     return d->pending.first()->id;
 }
currentRequest()
QHttpRequestHeader QHttp::currentRequest () const
Returns the request header of the HTTP request being executed.
If the request is one issued by setHost() or close(), it returns an invalid request header, i.e. QHttpRequestHeader::isValid() returns false.
See also
currentId()
Definition at line 1995 of file qhttp.cpp.
 {
     Q_D(const QHttp);
     if (!d->pending.isEmpty()) {
         QHttpRequest *r = d->pending.first();
         if (r->hasRequestHeader())
             return r->requestHeader();
     }
     return QHttpRequestHeader();
 }
currentSourceDevice()
QIODevice * QHttp::currentSourceDevice () const
Returns the QIODevice pointer that is used as the data source of the HTTP request being executed.
If there is no current request or if the request does not use an IO device as the data source, this function returns 0.
This function can be used to delete the QIODevice in the slot connected to the requestFinished() signal.
See also
currentDestinationDevice() post() request()
Definition at line 2029 of file qhttp.cpp.
 {
     Q_D(const QHttp);
     if (d->pending.isEmpty())
         return 0;
     return d->pending.first()->sourceDevice();
 }
dataReadProgress
void QHttp::dataReadProgress (int done, int total) signal
This signal is emitted when this object reads data from a HTTP server to indicate the current progress of the download.
done is the amount of data that has already arrived and total is the total amount of data. It is possible that the total amount of data that should be transferred cannot be determined, in which case total is 0.(If you connect to a QProgressBar, the progress bar shows a busy indicator if the total is 0).
Warning
done and total are not necessarily the size in bytes, since for large files these values might need to be "scaled" to avoid overflow.
See also
dataSendProgress() get() post() request() QProgressBar
dataSendProgress
void QHttp::dataSendProgress (int done, int total) signal
This signal is emitted when this object sends data to a HTTP server to inform it about the progress of the upload.
done is the amount of data that has already arrived and total is the total amount of data. It is possible that the total amount of data that should be transferred cannot be determined, in which case total is 0.(If you connect to a QProgressBar, the progress bar shows a busy indicator if the total is 0).
Warning
done and total are not necessarily the size in bytes, since for large files these values might need to be "scaled" to avoid overflow.
See also
dataReadProgress(), post(), request(), QProgressBar
done
void QHttp::done (bool error) signal
This signal is emitted when the last pending request has finished; (it is emitted after the last request's requestFinished() signal).
error is true if an error occurred during the processing; otherwise error is false.
See also
requestFinished() error() errorString()
error()
QHttp::Error QHttp::error () const
Returns the last error that occurred.
This is useful to find out what happened when receiving a requestFinished() or a done() signal with the error argument true.
If you start a new request, the error status is reset to NoError.
Definition at line 3113 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_startNextRequest(), QHttpPrivate::finishedWithError(), and QHttpPrivate::setSock().
 {
     Q_D(const QHttp);
     return d->error;
 }
errorString()
QString QHttp::errorString () const
Returns a human-readable description of the last error that occurred.
This is useful to present a error message to the user when receiving a requestFinished() or a done() signal with the error argument true.
Definition at line 3125 of file qhttp.cpp.
 {
     Q_D(const QHttp);
     return d->errorString;
 }
get()
int QHttp::get (const QString & path, QIODevice * to = 0)
Sends a get request for path to the server set by setHost() or as specified in the constructor.
path must be a absolute path like /index.html or an absolute URI like http://example.com/index.html and must be encoded with either QUrl::toPercentEncoding() or QUrl::encodedPath().
If the IO device to is 0 the readyRead() signal is emitted every time new content data is available to read.
If the IO device to is not 0, the content data of the response is written directly to the device. Make sure that the to pointer is valid for the duration of the operation (it is safe to delete it when the requestFinished() signal is emitted).
Request Processing
The function does not block; instead, it returns immediately. The request is scheduled, and its execution is performed asynchronously. The function returns a unique identifier which is passed by requestStarted() and requestFinished().
When the request is started the requestStarted() signal is emitted. When it is finished the requestFinished() signal is emitted.
See also
setHost(), post(), head(), request(), requestStarted(), requestFinished(), done()
Definition at line 2267 of file qhttp.cpp.
 {
     Q_D(QHttp);
     QHttpRequestHeader header(QLatin1String("GET"), path);
     header.setValue(QLatin1String("Connection"), QLatin1String("Keep-Alive"));
     return d->addRequest(new QHttpPGHRequest(header, (QIODevice *) 0, to));
 }
hasPendingRequests()
bool QHttp::hasPendingRequests () const
Returns true if there are any requests scheduled that have not yet been executed; otherwise returns false.
The request that is being executed is not considered as a scheduled request.
See also
clearPendingRequests() currentId() currentRequest()
Definition at line 2064 of file qhttp.cpp.
 {
     Q_D(const QHttp);
     return d->pending.count() > 1;
 }
head()
int QHttp::head (const QString & path)
Sends a header request for path to the server set by setHost() or as specified in the constructor.
path must be an absolute path like /index.html or an absolute URI like http://example.com/index.html.
The function does not block; instead, it returns immediately. The request is scheduled, and its execution is performed asynchronously. The function returns a unique identifier which is passed by requestStarted() and requestFinished().
When the request is started the requestStarted() signal is emitted. When it is finished the requestFinished() signal is emitted.
See also
setHost() get() post() request() requestStarted() requestFinished() done()
Definition at line 2344 of file qhttp.cpp.
 {
     Q_D(QHttp);
     QHttpRequestHeader header(QLatin1String("HEAD"), path);
     header.setValue(QLatin1String("Connection"), QLatin1String("Keep-Alive"));
     return d->addRequest(new QHttpPGHRequest(header, (QIODevice*)0, 0));
 }
ignoreSslErrors
void QHttp::ignoreSslErrors () slot
Tells the QSslSocket used for the Http connection to ignore the errors reported in the sslErrors() signal.
Note that this function must be called from within a slot connected to the sslErrors() signal to have any effect.
See also
QSslSocket QSslSocket::sslErrors()
Definition at line 3214 of file qhttp.cpp.
 {
     Q_D(QHttp);
     QSslSocket *sslSocket = qobject_cast<QSslSocket *>(d->socket);
     if (sslSocket)
         sslSocket->ignoreSslErrors();
 }
lastResponse()
QHttpResponseHeader QHttp::lastResponse () const
Returns the received response header of the most recently finished HTTP request.
If no response has yet been received QHttpResponseHeader::isValid() will return false.
See also
currentRequest()
Definition at line 2013 of file qhttp.cpp.
 {
     Q_D(const QHttp);
     return d->response;
 }
post() [1/2]
int QHttp::post (const QString & path, QIODevice * data, QIODevice * to = 0)
Sends a post request for path to the server set by setHost() or as specified in the constructor.
path must be an absolute path like /index.html or an absolute URI like http://example.com/index.html and must be encoded with either QUrl::toPercentEncoding() or QUrl::encodedPath().
The incoming data comes via the data IO device.
If the IO device to is 0 the readyRead() signal is emitted every time new content data is available to read.
If the IO device to is not 0, the content data of the response is written directly to the device. Make sure that the to pointer is valid for the duration of the operation (it is safe to delete it when the requestFinished() signal is emitted).
The function does not block; instead, it returns immediately. The request is scheduled, and its execution is performed asynchronously. The function returns a unique identifier which is passed by requestStarted() and requestFinished().
When the request is started the requestStarted() signal is emitted. When it is finished the requestFinished() signal is emitted.
See also
setHost() get() head() request() requestStarted() requestFinished() done()
Definition at line 2305 of file qhttp.cpp.
 {
     Q_D(QHttp);
     QHttpRequestHeader header(QLatin1String("POST"), path);
     header.setValue(QLatin1String("Connection"), QLatin1String("Keep-Alive"));
     return d->addRequest(new QHttpPGHRequest(header, data, to));
 }
post() [2/2]
int QHttp::post (const QString & path, const QByteArray & data, QIODevice * to = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.data is used as the content data of the HTTP request.
Definition at line 2318 of file qhttp.cpp.
 {
     Q_D(QHttp);
     QHttpRequestHeader header(QLatin1String("POST"), path);
     header.setValue(QLatin1String("Connection"), QLatin1String("Keep-Alive"));
     return d->addRequest(new QHttpPGHRequest(header, new QByteArray(data), to));
 }
proxyAuthenticationRequired
void QHttp::proxyAuthenticationRequired (const QNetworkProxy & proxy, QAuthenticator * authenticator) signal
Since
4.3
This signal can be emitted when a proxy that requires authentication is used. The authenticator object can then be filled in with the required details to allow authentication and continue the connection.
Note
It is not possible to use a QueuedConnection to connect to this signal, as the connection will fail if the authenticator has not been filled in with new information when the signal returns.
See also
QAuthenticator, QNetworkProxy
Referenced by QHttpPrivate::setSock().
read()
qint64 QHttp::read (char * data, qint64 maxlen)
Reads maxlen bytes from the response content into data and returns the number of bytes read.
Returns -1 if an error occurred.
See also
get() post() request() readyRead() bytesAvailable() readAll()
Definition at line 1933 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotReadyRead(), and readAll().
 {
     Q_D(QHttp);
     if (data == 0 && maxlen != 0) {
         qWarning("QHttp::read: Null pointer error");
         return -1;
     }
     if (maxlen >= d->rba.size())
         maxlen = d->rba.size();
     int readSoFar = 0;
     while (!d->rba.isEmpty() && readSoFar < maxlen) {
         int nextBlockSize = d->rba.nextDataBlockSize();
         int bytesToRead = qMin<qint64>(maxlen - readSoFar, nextBlockSize);
         memcpy(data + readSoFar, d->rba.readPointer(), bytesToRead);
         d->rba.free(bytesToRead);
         readSoFar += bytesToRead;
     }
     d->bytesDone += maxlen;
 #if defined(QHTTP_DEBUG)
     qDebug("QHttp::read(): read %lld bytes (%lld bytes done)", maxlen, d->bytesDone);
 #endif
     return maxlen;
 }
readAll()
QByteArray QHttp::readAll ()
Reads all the bytes from the response content and returns them.
See also
get() post() request() readyRead() bytesAvailable() read()
Definition at line 1963 of file qhttp.cpp.
 {
     qint64 avail = bytesAvailable();
     QByteArray tmp;
     tmp.resize(int(avail));
     qint64 got = read(tmp.data(), int(avail));
     tmp.resize(got);
     return tmp;
 }
readyRead
void QHttp::readyRead (const QHttpResponseHeader & resp) signal
This signal is emitted when there is new response data to read.
If you specified a device in the request where the data should be written to, then this signal is not emitted; instead the data is written directly to the device.
The response header is passed in resp.
You can read the data with the readAll() or read() functions
This signal is useful if you want to process the data in chunks as soon as it becomes available. If you are only interested in the complete data, just connect to the requestFinished() signal and read the data then instead.
See also
get() post() request() readAll() read() bytesAvailable()
Referenced by QHttpPrivate::setSock().
request() [1/2]
int QHttp::request (const QHttpRequestHeader & header, QIODevice * data = 0, QIODevice * to = 0)
Sends a request to the server set by setHost() or as specified in the constructor.
Uses the header as the HTTP request header. You are responsible for setting up a header that is appropriate for your request.
The incoming data comes via the data IO device.
If the IO device to is 0 the readyRead() signal is emitted every time new content data is available to read.
If the IO device to is not 0, the content data of the response is written directly to the device. Make sure that the to pointer is valid for the duration of the operation (it is safe to delete it when the requestFinished() signal is emitted).
The function does not block; instead, it returns immediately. The request is scheduled, and its execution is performed asynchronously. The function returns a unique identifier which is passed by requestStarted() and requestFinished().
When the request is started the requestStarted() signal is emitted. When it is finished the requestFinished() signal is emitted.
See also
setHost() get() post() head() requestStarted() requestFinished() done()
Definition at line 2379 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest().
 {
     Q_D(QHttp);
     return d->addRequest(new QHttpNormalRequest(header, data, to));
 }
request() [2/2]
int QHttp::request (const QHttpRequestHeader & header, const QByteArray & data, QIODevice * to = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.data is used as the content data of the HTTP request.
Definition at line 2390 of file qhttp.cpp.
 {
     Q_D(QHttp);
     return d->addRequest(new QHttpNormalRequest(header, new QByteArray(data), to));
 }
requestFinished
void QHttp::requestFinished (int id, bool error) signal
This signal is emitted when processing the request identified by id has finished.
error is true if an error occurred during the processing; otherwise error is false.
See also
requestStarted() done() error() errorString()
requestStarted
void QHttp::requestStarted (int id) signal
This signal is emitted when processing the request identified by id starts.
See also
requestFinished() done()
responseHeaderReceived
void QHttp::responseHeaderReceived (const QHttpResponseHeader & resp) signal
This signal is emitted when the HTTP header of a server response is available.
The header is passed in resp.
See also
get() post() head() request() readyRead()
setHost() [1/2]
int QHttp::setHost (const QString & hostName, quint16 port = 80)
Sets the HTTP server that is used for requests to hostName on port port.
The function does not block; instead, it returns immediately. The request is scheduled, and its execution is performed asynchronously. The function returns a unique identifier which is passed by requestStarted() and requestFinished().
When the request is started the requestStarted() signal is emitted. When it is finished the requestFinished() signal is emitted.
See also
get() post() head() request() requestStarted() requestFinished() done()
Definition at line 2100 of file qhttp.cpp.
 {
     Q_D(QHttp);
     return d->addRequest(new QHttpSetHostRequest(hostName, port, ConnectionModeHttp));
 }
setHost() [2/2]
int QHttp::setHost (const QString & hostName, ConnectionMode mode, quint16 port = 0)
Sets the HTTP server that is used for requests to hostName on port port using the connection mode mode.
If port is 0, it will use the default port for the mode used (80 for HTTP and 443 for HTTPS).
The function does not block; instead, it returns immediately. The request is scheduled, and its execution is performed asynchronously. The function returns a unique identifier which is passed by requestStarted() and requestFinished().
When the request is started the requestStarted() signal is emitted. When it is finished the requestFinished() signal is emitted.
See also
get() post() head() request() requestStarted() requestFinished() done()
Definition at line 2124 of file qhttp.cpp.
 {
 #ifdef QT_NO_OPENSSL
     if (mode == ConnectionModeHttps)
         qWarning("QHttp::setHost: HTTPS connection requested but SSL support not compiled in");
 #endif
     Q_D(QHttp);
     if (port == 0)
         port = (mode == ConnectionModeHttp) ? 80 : 443;
     return d->addRequest(new QHttpSetHostRequest(hostName, port, mode));
 }
setProxy() [1/2]
int QHttp::setProxy (const QString & host, int port, const QString & username = QString(), const QString & password = QString())
Enables HTTP proxy support, using the proxy server host on port port.
username and password can be provided if the proxy server requires authentication.
Example:
void Ticker::getTicks()
{
  http = new QHttp(this);
  connect(http, SIGNAL(done(bool)), this, SLOT(showPage()));
  http->setProxy("proxy.example.com", 3128);
  http->setHost("ticker.example.com");
  http->get("/ticks.asp");
}
void Ticker::showPage()
{
  display(http->readAll());
}
QHttp supports non-transparent web proxy servers only, such as the Squid Web proxy cache server (from http://www.squid.org/). For transparent proxying, such as SOCKS5, use QNetworkProxy instead.
Note
setProxy() has to be called before setHost() for it to take effect. If setProxy() is called after setHost(), then it will not apply until after setHost() is called again.
See also
QFtp::setProxy()
Definition at line 2203 of file qhttp.cpp.
 {
     Q_D(QHttp);
     QNetworkProxy proxy(QNetworkProxy::HttpProxy, host, port, username, password);
     return d->addRequest(new QHttpSetProxyRequest(proxy));
 }
setProxy() [2/2]
int QHttp::setProxy (const QNetworkProxy & proxy)
Enables HTTP proxy support using the proxy settings from proxy.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If proxy is a transparent proxy, QHttp will call QAbstractSocket::setProxy() on the underlying socket. If the type is QNetworkProxy::HttpCachingProxy, QHttp will behave like the previous function.
Note
for compatibility with Qt 4.3, if the proxy type is QNetworkProxy::HttpProxy and the request type is unencrypted (that is, ConnectionModeHttp), QHttp will treat the proxy as a caching proxy.
Definition at line 2228 of file qhttp.cpp.
 {
     Q_D(QHttp);
     return d->addRequest(new QHttpSetProxyRequest(proxy));
 }
setSocket()
int QHttp::setSocket (QTcpSocket * socket)
Replaces the internal QTcpSocket that QHttp uses with socket.
This is useful if you want to use your own custom QTcpSocket subclass instead of the plain QTcpSocket that QHttp uses by default. QHttp does not take ownership of the socket, and will not delete socket when destroyed.
The function does not block; instead, it returns immediately. The request is scheduled, and its execution is performed asynchronously. The function returns a unique identifier which is passed by requestStarted() and requestFinished().
When the request is started the requestStarted() signal is emitted. When it is finished the requestFinished() signal is emitted.
Note: If QHttp is used in a non-GUI thread that runs its own event loop, you must move socket to that thread before calling setSocket().
See also
QObject::moveToThread(), {Thread Support in Qt}
Definition at line 2157 of file qhttp.cpp.
 {
     Q_D(QHttp);
     return d->addRequest(new QHttpSetSocketRequest(socket));
 }
setUser()
int QHttp::setUser (const QString & userName, const QString & password = QString())
This function sets the user name userName and password password for web pages that require authentication.
The function does not block; instead, it returns immediately. The request is scheduled, and its execution is performed asynchronously. The function returns a unique identifier which is passed by requestStarted() and requestFinished().
When the request is started the requestStarted() signal is emitted. When it is finished the requestFinished() signal is emitted.
Definition at line 2176 of file qhttp.cpp.
Referenced by QHttpSetUserRequest::start(), and QHttpSetProxyRequest::start().
 {
     Q_D(QHttp);
     return d->addRequest(new QHttpSetUserRequest(userName, password));
 }
sslErrors
void QHttp::sslErrors (const QList< QSslError > & errors) signal
Forwards the sslErrors signal from the QSslSocket used in QHttp.
Since
4.3
errors is the list of errors that occurred during the SSL handshake. Unless you call ignoreSslErrors() from within a slot connected to this signal when an error occurs, QHttp will tear down the connection immediately after emitting the signal.
See also
QSslSocket QSslSocket::ignoreSslErrors()
Referenced by QHttpPrivate::setSock().
state()
QHttp::State QHttp::state () const
Returns the current state of the object.
When the state changes, the stateChanged() signal is emitted.
See also
State stateChanged()
Definition at line 3100 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotClosed(), QHttpPrivate::_q_slotConnected(), QHttpPrivate::_q_slotDoFinished(), QHttpPrivate::_q_slotError(), QHttpPrivate::_q_slotReadyRead(), QHttpPrivate::closeConn(), and QHttpPrivate::setState().
 {
     Q_D(const QHttp);
     return d->state;
 }
stateChanged
void QHttp::stateChanged (int state) signal
This signal is emitted when the state of the QHttp object changes.
The argument state is the new state of the connection; it is one of the State values.
This usually happens when a request is started, but it can also happen when the server closes the connection or when a call to close() succeeded.
See also
get() post() head() request() close() state() State
Friends and Related Functions
QHttpCloseRequest
friend class QHttpCloseRequest friend
Definition at line 305 of file qhttp.h.
Referenced by close(), and closeConnection().
QHttpNormalRequest
friend class QHttpNormalRequest friend
Definition at line 300 of file qhttp.h.
Referenced by request().
QHttpPGHRequest
friend class QHttpPGHRequest friend
Definition at line 306 of file qhttp.h.
Referenced by get(), head(), and post().
QHttpSetHostRequest
friend class QHttpSetHostRequest friend
Definition at line 301 of file qhttp.h.
Referenced by setHost().
QHttpSetProxyRequest
friend class QHttpSetProxyRequest friend
Definition at line 304 of file qhttp.h.
Referenced by setProxy().
QHttpSetSocketRequest
friend class QHttpSetSocketRequest friend
Definition at line 302 of file qhttp.h.
Referenced by setSocket().
QHttpSetUserRequest
friend class QHttpSetUserRequest friend
Definition at line 303 of file qhttp.h.
Referenced by setUser().
The documentation for this class was generated from the following files:
/src/network/access/qhttp.h
/src/network/access/qhttp.cpp