Qt 4.8: QAbstractState Class Reference
QAbstractState Class Reference abstract
The QAbstractState class is the base class of states of a QStateMachine.
#include <qabstractstate.h>
Signals
void entered ()
This signal is emitted when the state has been entered (after onEntry() has been called).
void exited ()
This signal is emitted when the state has been exited (after onExit() has been called).
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QStateMachine * machine () const
Returns the state machine that this state is part of, or 0 if the state is not part of a state machine.
QState * parentState () const
Returns this state's parent state, or 0 if the state has no parent state.
~QAbstractState ()
Destroys this state.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *e)
Reimplemented Function
virtual void onEntry (QEvent *event)=0
This function is called when the state is entered.
virtual void onExit (QEvent *event)=0
This function is called when the state is exited.
QAbstractState (QState *parent=0)
Constructs a new state with the given parent state.
QAbstractState (QAbstractStatePrivate &dd, QState *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAbstractState class is the base class of states of a QStateMachine.
Since
4.6
The QAbstractState class is the abstract base class of states that are part of a QStateMachine. It defines the interface that all state objects have in common. QAbstractState is part of The State Machine Framework.
The entered() signal is emitted when the state has been entered. The exited() signal is emitted when the state has been exited.
The parentState() function returns the state's parent state. The machine() function returns the state machine that the state is part of.
Subclassing
The onEntry() function is called when the state is entered; reimplement this function to perform custom processing when the state is entered.
The onExit() function is called when the state is exited; reimplement this function to perform custom processing when the state is exited.
Definition at line 59 of file qabstractstate.h.
Constructors and Destructors
~QAbstractState()
QAbstractState::~QAbstractState ()
Destroys this state.
Definition at line 153 of file qabstractstate.cpp.
 {
 }
QAbstractState() [1/2]
QAbstractState::QAbstractState (QState * parent = 0) protected
Constructs a new state with the given parent state.
Definition at line 137 of file qabstractstate.cpp.
     : QObject(*new QAbstractStatePrivate(QAbstractStatePrivate::AbstractState), parent)
 {
 }
QAbstractState() [2/2]
QAbstractState::QAbstractState (QAbstractStatePrivate & dd, QState * parent) protected
Warning
This function is not part of the public interface.
Definition at line 145 of file qabstractstate.cpp.
     : QObject(dd, parent)
 {
 }
Functions
entered
QAbstractState::entered () signal
This signal is emitted when the state has been entered (after onEntry() has been called).
event()
bool QAbstractState::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Reimplemented in QStateMachine, QState, QHistoryState, and QFinalState.
Definition at line 217 of file qabstractstate.cpp.
Referenced by QFinalState::event(), QHistoryState::event(), and QState::event().
 {
     return QObject::event(e);
 }
exited
QAbstractState::exited () signal
This signal is emitted when the state has been exited (after onExit() has been called).
machine()
QStateMachine * QAbstractState::machine () const
Returns the state machine that this state is part of, or 0 if the state is not part of a state machine.
Definition at line 172 of file qabstractstate.cpp.
Referenced by QStateMachine::addState(), QStateMachinePrivate::addStatesToEnter(), QState::addTransition(), QAbstractTransitionPrivate::machine(), QSignalEventGenerator::qt_metacall(), QStateMachine::removeState(), QState::setErrorState(), QStateMachinePrivate::stateEntryLessThan(), and QStateMachinePrivate::stateExitLessThan().
 {
     Q_D(const QAbstractState);
     return d->machine();
 }
onEntry()
QAbstractState::onEntry (QEvent * event) protected pure virtual
This function is called when the state is entered.
The given event is what caused the state to be entered. Reimplement this function to perform custom processing when the state is entered.
Implemented in QStateMachine, QState, QHistoryState, and QFinalState.
onExit()
QAbstractState::onExit (QEvent * event) protected pure virtual
This function is called when the state is exited.
The given event is what caused the state to be exited. Reimplement this function to perform custom processing when the state is exited.
Implemented in QStateMachine, QState, QHistoryState, and QFinalState.
parentState()
QState * QAbstractState::parentState () const
Returns this state's parent state, or 0 if the state has no parent state.
Definition at line 160 of file qabstractstate.cpp.
Referenced by QStateMachinePrivate::addStatesToEnter(), QStateMachinePrivate::applyProperties(), QStateMachinePrivate::enterStates(), QStateMachinePrivate::exitStates(), QStateMachinePrivate::findErrorState(), QStateMachinePrivate::findLCA(), QStateMachinePrivate::isDescendantOf(), QStateMachinePrivate::properAncestors(), QHistoryState::setDefaultState(), and QState::setInitialState().
 {
     Q_D(const QAbstractState);
     if (d->parentState != parent())
         d->parentState = qobject_cast<QState*>(parent());
     return d->parentState;
 }
The documentation for this class was generated from the following files:
/src/corelib/statemachine/qabstractstate.h
/src/corelib/statemachine/qabstractstate.cpp