Qt 4.8: QmlJSDebugger::QDeclarativeViewInspector Class Reference
QmlJSDebugger::QDeclarativeViewInspector Class Reference
#include <qdeclarativeviewinspector.h>
Public Functions
QRectF adjustToScreenBoundaries (const QRectF &boundingRectInSceneSpace)
void changeCurrentObjects (const QList< QObject *> &objects)
void changeTool (InspectorProtocol::Tool tool)
QDeclarativeEngine * declarativeEngine () const
QDeclarativeView * declarativeView () const
QDeclarativeViewInspector (QDeclarativeView *view, QObject *parent=0)
void reloadView ()
void reparentQmlObject (QObject *object, QObject *newParent)
QList< QGraphicsItem * > selectedItems () const
void setSelectedItems (QList< QGraphicsItem *> items)
QWidget * viewWidget () const
~QDeclarativeViewInspector ()
Public Functions inherited from QmlJSDebugger::AbstractViewInspector
AbstractViewInspector (QObject *parent=0)
bool animationPaused () const
void clearComponentCache ()
void createQmlObject (const QString &qml, QObject *parent, const QStringList &importList, const QString &filename=QString())
bool designModeBehavior () const
QString idStringForObject (QObject *obj) const
void sendAnimationPaused (bool paused)
void sendAnimationSpeed (qreal slowDownFactor)
void sendCurrentObjects (const QList< QObject *> &)
void sendCurrentTool (Constants::DesignTool toolId)
void sendReloaded ()
void sendShowAppOnTop (bool showAppOnTop)
bool showAppOnTop () const
qreal slowDownFactor () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
AbstractLiveEditTool * currentTool () const
bool eventFilter (QObject *obj, QEvent *event)
Filters events if this object has been installed as an event filter for the watched object.
bool leaveEvent (QEvent *)
bool mouseMoveEvent (QMouseEvent *event)
Protected Functions inherited from QmlJSDebugger::AbstractViewInspector
AbstractTool * currentTool () const
virtual bool keyPressEvent (QKeyEvent *event)
virtual bool keyReleaseEvent (QKeyEvent *keyEvent)
virtual bool mouseDoubleClickEvent (QMouseEvent *event)
virtual bool mousePressEvent (QMouseEvent *event)
virtual bool mouseReleaseEvent (QMouseEvent *event)
void setCurrentTool (AbstractTool *tool)
virtual bool wheelEvent (QWheelEvent *event)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
QDeclarativeViewInspectorPrivate * d_func ()
Properties
QScopedPointer< QDeclarativeViewInspectorPrivate > data
Friends
class AbstractLiveEditTool
class QDeclarativeViewInspectorPrivate
Additional Inherited Members
Public Slots inherited from QmlJSDebugger::AbstractViewInspector
void changeToColorPickerTool ()
void changeToMarqueeSelectTool ()
void changeToSingleSelectTool ()
void changeToZoomTool ()
void sendColorChanged (const QColor &color)
void sendDesignModeBehavior (bool inDesignMode)
void setAnimationPaused (bool paused)
void setAnimationSpeed (qreal factor)
virtual void setDesignModeBehavior (bool value)
void setShowAppOnTop (bool appOnTop)
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QmlJSDebugger::AbstractViewInspector
void animationPausedChanged (bool paused)
void animationSpeedChanged (qreal factor)
void colorPickerActivated ()
void designModeBehaviorChanged (bool inDesignMode)
void marqueeSelectToolActivated ()
void reloadRequested ()
void selectedColorChanged (const QColor &color)
void selectToolActivated ()
void showAppOnTopChanged (bool showAppOnTop)
void zoomToolActivated ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 58 of file qdeclarativeviewinspector.h.
Constructors and Destructors
QDeclarativeViewInspector()
QmlJSDebugger::QDeclarativeViewInspector::QDeclarativeViewInspector (QDeclarativeView * view, QObject * parent = 0) explicit
Definition at line 67 of file qdeclarativeviewinspector.cpp.
                                                                     :
     AbstractViewInspector(parent),
     data(new QDeclarativeViewInspectorPrivate(this))
 {
     data->view = view;
     data->manipulatorLayer = new LiveLayerItem(view->scene());
     data->selectionTool = new LiveSelectionTool(this);
     data->zoomTool = new ZoomTool(this);
     data->colorPickerTool = new ColorPickerTool(this);
     data->boundingRectHighlighter = new BoundingRectHighlighter(this);
     setCurrentTool(data->selectionTool);
     // to capture ChildRemoved event when viewport changes
     data->view->installEventFilter(this);
     data->setViewport(data->view->viewport());
     connect(data->view, SIGNAL(statusChanged(QDeclarativeView::Status)),
             data.data(), SLOT(_q_onStatusChanged(QDeclarativeView::Status)));
     connect(data->colorPickerTool, SIGNAL(selectedColorChanged(QColor)),
             SIGNAL(selectedColorChanged(QColor)));
     connect(data->colorPickerTool, SIGNAL(selectedColorChanged(QColor)),
             this, SLOT(sendColorChanged(QColor)));
     changeTool(InspectorProtocol::SelectTool);
 }
~QDeclarativeViewInspector()
QmlJSDebugger::QDeclarativeViewInspector::~QDeclarativeViewInspector ()
Definition at line 96 of file qdeclarativeviewinspector.cpp.
 {
 }
Functions
adjustToScreenBoundaries()
QRectF QmlJSDebugger::QDeclarativeViewInspector::adjustToScreenBoundaries (const QRectF & boundingRectInSceneSpace)
Definition at line 415 of file qdeclarativeviewinspector.cpp.
Referenced by QmlJSDebugger::BoundingRectHighlighter::highlightAll(), QmlJSDebugger::LiveSelectionIndicator::setItems(), and viewWidget().
 {
     int marginFromEdge = 1;
     QRectF boundingRect(boundingRectInSceneSpace);
     if (qAbs(boundingRect.left()) - 1 < 2)
         boundingRect.setLeft(marginFromEdge);
     QRect rect = data->view->rect();
     if (boundingRect.right() >= rect.right())
         boundingRect.setRight(rect.right() - marginFromEdge);
     if (qAbs(boundingRect.top()) - 1 < 2)
         boundingRect.setTop(marginFromEdge);
     if (boundingRect.bottom() >= rect.bottom())
         boundingRect.setBottom(rect.bottom() - marginFromEdge);
     return boundingRect;
 }
changeCurrentObjects()
void QmlJSDebugger::QDeclarativeViewInspector::changeCurrentObjects (const QList< QObject *> & objects) virtual
Implements QmlJSDebugger::AbstractViewInspector.
Definition at line 100 of file qdeclarativeviewinspector.cpp.
 {
     QList<QGraphicsItem*> items;
     QList<QGraphicsObject*> gfxObjects;
     foreach (QObject *obj, objects) {
         if (QDeclarativeItem *declarativeItem = qobject_cast<QDeclarativeItem*>(obj)) {
             items << declarativeItem;
             gfxObjects << declarativeItem;
         }
     }
     if (designModeBehavior()) {
         data->setSelectedItemsForTools(items);
         data->clearHighlight();
         data->highlight(gfxObjects);
     }
 }
changeTool()
void QmlJSDebugger::QDeclarativeViewInspector::changeTool (InspectorProtocol::Tool tool) virtual
Implements QmlJSDebugger::AbstractViewInspector.
Definition at line 123 of file qdeclarativeviewinspector.cpp.
Referenced by QDeclarativeViewInspector().
 {
     switch (tool) {
     case InspectorProtocol::ColorPickerTool:
         data->changeToColorPickerTool();
         break;
     case InspectorProtocol::SelectMarqueeTool:
         data->changeToMarqueeSelectTool();
         break;
     case InspectorProtocol::SelectTool:
         data->changeToSingleSelectTool();
         break;
     case InspectorProtocol::ZoomTool:
         data->changeToZoomTool();
         break;
     }
 }
currentTool()
AbstractLiveEditTool * QmlJSDebugger::QDeclarativeViewInspector::currentTool () const protected
Definition at line 141 of file qdeclarativeviewinspector.cpp.
Referenced by mouseMoveEvent(), and viewWidget().
 {
     return static_cast<AbstractLiveEditTool*>(AbstractViewInspector::currentTool());
 }
d_func()
QDeclarativeViewInspectorPrivate* QmlJSDebugger::QDeclarativeViewInspector::d_func () inline private
Definition at line 92 of file qdeclarativeviewinspector.h.
 { return data.data(); }
declarativeEngine()
QDeclarativeEngine * QmlJSDebugger::QDeclarativeViewInspector::declarativeEngine () const virtual
Implements QmlJSDebugger::AbstractViewInspector.
Definition at line 146 of file qdeclarativeviewinspector.cpp.
Referenced by viewWidget().
 {
     return data->view->engine();
 }
declarativeView()
QDeclarativeView * QmlJSDebugger::QDeclarativeViewInspector::declarativeView () const
Definition at line 287 of file qdeclarativeviewinspector.cpp.
Referenced by mouseMoveEvent(), QmlJSDebugger::SubcomponentMaskLayerItem::setCurrentItem(), QmlJSDebugger::AbstractLiveEditTool::view(), and viewWidget().
 {
     return data->view;
 }
eventFilter()
bool QmlJSDebugger::QDeclarativeViewInspector::eventFilter (QObject * , QEvent *) protected virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QmlJSDebugger::AbstractViewInspector.
Definition at line 173 of file qdeclarativeviewinspector.cpp.
Referenced by viewWidget().
 {
     if (obj == data->view) {
         // Event from view
         if (event->type() == QEvent::ChildRemoved) {
             // Might mean that viewport has changed
             if (data->view->viewport() != data->viewport.data())
                 data->setViewport(data->view->viewport());
         }
         return QObject::eventFilter(obj, event);
     }
     return AbstractViewInspector::eventFilter(obj, event);
 }
leaveEvent()
bool QmlJSDebugger::QDeclarativeViewInspector::leaveEvent (QEvent * event) protected virtual
Reimplemented from QmlJSDebugger::AbstractViewInspector.
Definition at line 188 of file qdeclarativeviewinspector.cpp.
Referenced by viewWidget().
 {
     data->clearHighlight();
     return AbstractViewInspector::leaveEvent(event);
 }
mouseMoveEvent()
bool QmlJSDebugger::QDeclarativeViewInspector::mouseMoveEvent (QMouseEvent * event) protected virtual
Reimplemented from QmlJSDebugger::AbstractViewInspector.
Definition at line 194 of file qdeclarativeviewinspector.cpp.
Referenced by viewWidget().
 {
     QList<QGraphicsItem*> selItems = data->selectableItems(event->pos());
     if (!selItems.isEmpty()) {
         declarativeView()->setToolTip(currentTool()->titleForItem(selItems.first()));
     } else {
         declarativeView()->setToolTip(QString());
     }
     return AbstractViewInspector::mouseMoveEvent(event);
 }
reloadView()
void QmlJSDebugger::QDeclarativeViewInspector::reloadView () virtual
Implements QmlJSDebugger::AbstractViewInspector.
Definition at line 117 of file qdeclarativeviewinspector.cpp.
 {
     data->clearHighlight();
     emit reloadRequested();
 }
reparentQmlObject()
void QmlJSDebugger::QDeclarativeViewInspector::reparentQmlObject (QObject * object, QObject * newParent) virtual
Implements QmlJSDebugger::AbstractViewInspector.
Definition at line 206 of file qdeclarativeviewinspector.cpp.
 {
     if (!newParent)
         return;
     object->setParent(newParent);
     QDeclarativeItem *newParentItem = qobject_cast<QDeclarativeItem*>(newParent);
     QDeclarativeItem *item    = qobject_cast<QDeclarativeItem*>(object);
     if (newParentItem && item)
         item->setParentItem(newParentItem);
 }
selectedItems()
QList< QGraphicsItem * > QmlJSDebugger::QDeclarativeViewInspector::selectedItems () const
Definition at line 282 of file qdeclarativeviewinspector.cpp.
Referenced by QmlJSDebugger::QDeclarativeViewInspectorPrivate::_q_removeFromSelection(), QmlJSDebugger::LiveRubberBandSelectionManipulator::begin(), QmlJSDebugger::AbstractLiveEditTool::items(), QmlJSDebugger::AbstractLiveEditTool::topSelectedItemIsMovable(), viewWidget(), and QmlJSDebugger::LiveSelectionTool::wheelEvent().
 {
     return data->selectedItems();
 }
setSelectedItems()
void QmlJSDebugger::QDeclarativeViewInspector::setSelectedItems (QList< QGraphicsItem *> items)
Definition at line 277 of file qdeclarativeviewinspector.cpp.
Referenced by QmlJSDebugger::QDeclarativeViewInspectorPrivate::_q_removeFromSelection(), QmlJSDebugger::QDeclarativeViewInspectorPrivate::clearEditorItems(), QmlJSDebugger::LiveSingleSelectionManipulator::select(), QmlJSDebugger::LiveRubberBandSelectionManipulator::select(), and viewWidget().
 {
     data->setSelectedItems(items);
 }
viewWidget()
QWidget* QmlJSDebugger::QDeclarativeViewInspector::viewWidget () const inline virtual
Implements QmlJSDebugger::AbstractViewInspector.
Definition at line 71 of file qdeclarativeviewinspector.h.
 { return declarativeView(); }
Friends and Related Functions
AbstractLiveEditTool
friend class AbstractLiveEditTool friend
Definition at line 95 of file qdeclarativeviewinspector.h.
QDeclarativeViewInspectorPrivate
friend class QDeclarativeViewInspectorPrivate friend
Definition at line 94 of file qdeclarativeviewinspector.h.
Properties
data
QScopedPointer<QDeclarativeViewInspectorPrivate> QmlJSDebugger::QDeclarativeViewInspector::data private
Definition at line 93 of file qdeclarativeviewinspector.h.
Referenced by adjustToScreenBoundaries(), changeCurrentObjects(), changeTool(), d_func(), declarativeEngine(), declarativeView(), eventFilter(), leaveEvent(), mouseMoveEvent(), QDeclarativeViewInspector(), reloadView(), selectedItems(), and setSelectedItems().
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_inspector/qdeclarativeviewinspector.h
/src/plugins/qmltooling/qmldbg_inspector/qdeclarativeviewinspector.cpp