Qt 4.8: QWindowsVistaTransition Class Reference
QWindowsVistaTransition Class Reference
#include <qwindowsvistastyle_p.h>
Public Functions
int duration () const
virtual void paint (QPainter *painter, const QStyleOption *option)
Paints a transition state.
QWindowsVistaTransition ()
void setDuration (int duration)
void setEndImage (const QImage &image)
void setStartImage (const QImage &image)
virtual ~QWindowsVistaTransition ()
Public Functions inherited from QWindowsVistaAnimation
QWindowsVistaAnimation ()
bool running () const
void setRunning (bool val)
void setStartTime (const QTime &startTime)
void setWidget (QWidget *widget)
const QTime & startTime () const
QWidget * widget () const
virtual ~QWindowsVistaAnimation ()
Public Variables
int _duration
Additional Inherited Members
Protected Functions inherited from QWindowsVistaAnimation
void drawBlendedImage (QPainter *painter, QRect rect, float value)
Protected Variables inherited from QWindowsVistaAnimation
QImage _primaryImage
bool _running
QImage _secondaryImage
QTime _startTime
QImage _tempImage
QPointer< QWidget > _widget
Detailed Description
Definition at line 165 of file qwindowsvistastyle_p.h.
Constructors and Destructors
QWindowsVistaTransition()
QWindowsVistaTransition::QWindowsVistaTransition () inline
Definition at line 168 of file qwindowsvistastyle_p.h.
 : QWindowsVistaAnimation() {}
~QWindowsVistaTransition()
virtual QWindowsVistaTransition::~QWindowsVistaTransition () inline virtual
Definition at line 169 of file qwindowsvistastyle_p.h.
 { }
Functions
duration()
int QWindowsVistaTransition::duration () const inline
Definition at line 174 of file qwindowsvistastyle_p.h.
 { return _duration; }
paint()
void QWindowsVistaTransition::paint (QPainter * painter, const QStyleOption * option) virtual
Paints a transition state.
Warning
This function is not part of the public interface. The result will be a mix between the initial and final state of the transition, depending on the time difference between _startTime and current time.
Reimplemented from QWindowsVistaAnimation.
Definition at line 265 of file qwindowsvistastyle.cpp.
 {
     float alpha = 1.0;
     if (_duration > 0) {
         QTime current = QTime::currentTime();
         if (_startTime > current)
             _startTime = current;
         int timeDiff = _startTime.msecsTo(current);
         alpha = timeDiff/(float)_duration;
         if (timeDiff > _duration) {
             _running = false;
             alpha = 1.0;
         }
     }
     else {
         _running = false;
     }
     drawBlendedImage(painter, option->rect, alpha);
 }
setDuration()
void QWindowsVistaTransition::setDuration (int duration) inline
Definition at line 170 of file qwindowsvistastyle_p.h.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), and QWindowsVistaStyle::drawPrimitive().
 { _duration = duration; }
setEndImage()
void QWindowsVistaTransition::setEndImage (const QImage & image) inline
Definition at line 172 of file qwindowsvistastyle_p.h.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), and QWindowsVistaStyle::drawPrimitive().
 { _secondaryImage = image; }
setStartImage()
void QWindowsVistaTransition::setStartImage (const QImage & image) inline
Definition at line 171 of file qwindowsvistastyle_p.h.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), and QWindowsVistaStyle::drawPrimitive().
 { _primaryImage = image; }
Properties
_duration
int QWindowsVistaTransition::_duration
Definition at line 175 of file qwindowsvistastyle_p.h.
The documentation for this class was generated from the following files:
/src/gui/styles/qwindowsvistastyle_p.h
/src/gui/styles/qwindowsvistastyle.cpp