Qt 4.8: QPatternist::GYear Class Reference
QPatternist::GYear Class Reference
Implements the value instance of the xs:gYear type.
#include <qgyear_p.h>
Public Types
typedef AtomicValue::Ptr Ptr
Public Types inherited from QPatternist::AbstractDateTime
enum { DefaultYear = 2000, DefaultMonth = 1, DefaultDay = 1 }
typedef QExplicitlySharedDataPointer< AbstractDateTime > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual QString stringValue () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AbstractDateTime
AbstractDateTime (const QDateTime &dateTime)
QString dateToString () const
virtual Item fromValue (const QDateTime &dt) const
QString timeToString () const
const QDateTime & toDateTime () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static GYear::Ptr fromDateTime (const QDateTime &dt)
static GYear::Ptr fromLexical (const QString &string)
Static Public Functions inherited from QPatternist::AbstractDateTime
static bool isRangeValid (const QDate &date, QString &message)
static QString serializeMSeconds (const MSecondProperty msecs)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
GYear (const QDateTime &dateTime)
Protected Functions inherited from QPatternist::AbstractDateTime
QString zoneOffsetToString () const
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Friends
class CommonValues
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Static Protected Functions inherited from QPatternist::AbstractDateTime
static void copyTimeSpec (const QDateTime &from, QDateTime &to)
Makes the QDateTime::timeSpec() and QDateTime::zoneOffset() of ot * consistent to from.
static QDateTime create (AtomicValue::Ptr &errorMessage, const QString &lexicalSource, const CaptureTable &captTable)
Protected Variables inherited from QPatternist::AbstractDateTime
const QDateTime m_dateTime
Detailed Description
Implements the value instance of the xs:gYear type.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 69 of file qgyear_p.h.
Typedefs
Ptr
typedef AtomicValue::Ptr QPatternist::GYear::Ptr
Definition at line 72 of file qgyear_p.h.
Constructors and Destructors
GYear()
GYear::GYear (const QDateTime & dateTime) protected
Definition at line 50 of file qgyear.cpp.
Referenced by fromDateTime(), and fromLexical().
                                       : AbstractDateTime(dateTime)
 {
 }
Functions
fromDateTime()
GYear::Ptr GYear::fromDateTime (const QDateTime & dt) static
Definition at line 83 of file qgyear.cpp.
Referenced by QPatternist::AbstractDateTimeToGYearCaster::castFrom().
 {
     QDateTime result(QDate(dt.date().year(), DefaultMonth, DefaultDay));
     copyTimeSpec(dt, result);
     return GYear::Ptr(new GYear(result));
 }
fromLexical()
GYear::Ptr GYear::fromLexical (const QString & string) static
Creates an instance from the lexical representation string.
Definition at line 54 of file qgyear.cpp.
Referenced by QPatternist::StringToGYearCaster::castFrom().
 {
     static const CaptureTable captureTable( // STATIC DATA
         /* The extra paranthesis is a build fix for GCC 3.3. */
         (QRegExp(QLatin1String(
                 "^\\s*"                             /* Any preceding whitespace. */
                 "(-?)"                              /* Any preceding minus. */
                 "(-?\\d{4,})"                       /* The year part, "1999". */
                 "(?:(\\+|-)(\\d{2}):(\\d{2})|(Z))?" /* The zone offset, "+08:24". */
                 "\\s*$"                             /* Any terminating whitespace. */))),
         /*zoneOffsetSignP*/         3,
         /*zoneOffsetHourP*/         4,
         /*zoneOffsetMinuteP*/       5,
         /*zoneOffsetUTCSymbolP*/    6,
         /*yearP*/                   2,
         /*monthP*/                  -1,
         /*dayP*/                    -1,
         /*hourP*/                   -1,
         /*minutesP*/                -1,
         /*secondsP*/                -1,
         /*msecondsP*/               -1,
         /*yearSign*/                1);
     AtomicValue::Ptr err;
     const QDateTime retval(create(err, lexical, captureTable));
     return err ? err : GYear::Ptr(new GYear(retval));
 }
stringValue()
QString GYear::stringValue () const virtual
Implements QPatternist::AtomicValue.
Definition at line 91 of file qgyear.cpp.
 {
     return m_dateTime.toString(QLatin1String("yyyy")) + zoneOffsetToString();
 }
type()
ItemType::Ptr GYear::type () const virtual
Implements QPatternist::AtomicValue.
Definition at line 96 of file qgyear.cpp.
 {
     return BuiltinTypes::xsGYear;
 }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 84 of file qgyear_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qgyear_p.h
/src/xmlpatterns/data/qgyear.cpp