Qt 4.8: QGL2GradientCache Class Reference
QGL2GradientCache Class Reference
#include <qglgradientcache_p.h>
Classes
struct CacheInfo
Public Functions
GLuint getBuffer (const QGradient &gradient, qreal opacity)
int paletteSize () const
QGL2GradientCache (const QGLContext *)
~QGL2GradientCache ()
Static Public Functions
static QGL2GradientCache * cacheForContext (const QGLContext *context)
Private Types
typedef QMultiHash< quint64, CacheInfo > QGLGradientColorTableHash
Private Functions
GLuint addCacheElement (quint64 hash_val, const QGradient &gradient, qreal opacity)
void cleanCache ()
void generateGradientColorTable (const QGradient &gradient, uint *colorTable, int size, qreal opacity) const
int maxCacheSize () const
Properties
QGLGradientColorTableHash cache
QMutex m_mutex
Detailed Description
Definition at line 61 of file qglgradientcache_p.h.
Typedefs
QGLGradientColorTableHash
typedef QMultiHash<quint64, CacheInfo> QGL2GradientCache::QGLGradientColorTableHash private
Definition at line 74 of file qglgradientcache_p.h.
Constructors and Destructors
QGL2GradientCache()
QGL2GradientCache::QGL2GradientCache (const QGLContext *) inline
Definition at line 79 of file qglgradientcache_p.h.
 {}
~QGL2GradientCache()
QGL2GradientCache::~QGL2GradientCache () inline
Definition at line 80 of file qglgradientcache_p.h.
 { cleanCache(); }
Functions
addCacheElement()
GLuint QGL2GradientCache::addCacheElement (quint64 hash_val, const QGradient & gradient, qreal opacity) private
Definition at line 109 of file qglgradientcache.cpp.
Referenced by maxCacheSize().
 {
     if (cache.size() == maxCacheSize()) {
         int elem_to_remove = qrand() % maxCacheSize();
         quint64 key = cache.keys()[elem_to_remove];
         // need to call glDeleteTextures on each removed cache entry:
         QGLGradientColorTableHash::const_iterator it = cache.constFind(key);
         do {
             glDeleteTextures(1, &it.value().texId);
         } while (++it != cache.constEnd() && it.key() == key);
         cache.remove(key); // may remove more than 1, but OK
     }
     CacheInfo cache_entry(gradient.stops(), opacity, gradient.interpolationMode());
     uint buffer[1024];
     generateGradientColorTable(gradient, buffer, paletteSize(), opacity);
     glGenTextures(1, &cache_entry.texId);
     glBindTexture(GL_TEXTURE_2D, cache_entry.texId);
     glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, paletteSize(), 1,
                     0, GL_RGBA, GL_UNSIGNED_BYTE, buffer);
     return cache.insert(hash_val, cache_entry).value().texId;
 }
cacheForContext()
QGL2GradientCache * QGL2GradientCache::cacheForContext (const QGLContext * context) static
Definition at line 64 of file qglgradientcache.cpp.
Referenced by cacheForContext(), and QGL2PaintEngineExPrivate::updateBrushTexture().
 {
     return qt_gradient_caches()->cacheForContext(context);
 }
cleanCache()
void QGL2GradientCache::cleanCache () private
Definition at line 69 of file qglgradientcache.cpp.
Referenced by maxCacheSize(), and ~QGL2GradientCache().
 {
     QMutexLocker lock(&m_mutex);
     QGLGradientColorTableHash::const_iterator it = cache.constBegin();
     for (; it != cache.constEnd(); ++it) {
         const CacheInfo &cache_info = it.value();
         glDeleteTextures(1, &cache_info.texId);
     }
     cache.clear();
 }
generateGradientColorTable()
void QGL2GradientCache::generateGradientColorTable (const QGradient & gradient, uint * colorTable, int size, qreal opacity) const inline private
Definition at line 151 of file qglgradientcache.cpp.
Referenced by maxCacheSize().
 {
     int pos = 0;
     QGradientStops s = gradient.stops();
     QVector<uint> colors(s.size());
     for (int i = 0; i < s.size(); ++i)
         colors[i] = s[i].second.rgba(); // Qt LIES! It returns ARGB (on little-endian AND on big-endian)
     bool colorInterpolation = (gradient.interpolationMode() == QGradient::ColorInterpolation);
     uint alpha = qRound(opacity * 256);
     uint current_color = ARGB_COMBINE_ALPHA(colors[0], alpha);
     qreal incr = 1.0 / qreal(size);
     qreal fpos = 1.5 * incr;
     colorTable[pos++] = qtToGlColor(PREMUL(current_color));
     while (fpos <= s.first().first) {
         colorTable[pos] = colorTable[pos - 1];
         pos++;
         fpos += incr;
     }
     if (colorInterpolation)
         current_color = PREMUL(current_color);
     for (int i = 0; i < s.size() - 1; ++i) {
         qreal delta = 1/(s[i+1].first - s[i].first);
         uint next_color = ARGB_COMBINE_ALPHA(colors[i+1], alpha);
         if (colorInterpolation)
             next_color = PREMUL(next_color);
         while (fpos < s[i+1].first && pos < size) {
             int dist = int(256 * ((fpos - s[i].first) * delta));
             int idist = 256 - dist;
             if (colorInterpolation)
                 colorTable[pos] = qtToGlColor(INTERPOLATE_PIXEL_256(current_color, idist, next_color, dist));
             else
                 colorTable[pos] = qtToGlColor(PREMUL(INTERPOLATE_PIXEL_256(current_color, idist, next_color, dist)));
             ++pos;
             fpos += incr;
         }
         current_color = next_color;
     }
     Q_ASSERT(s.size() > 0);
     uint last_color = qtToGlColor(PREMUL(ARGB_COMBINE_ALPHA(colors[s.size() - 1], alpha)));
     for (;pos < size; ++pos)
         colorTable[pos] = last_color;
     // Make sure the last color stop is represented at the end of the table
     colorTable[size-1] = last_color;
 }
getBuffer()
GLuint QGL2GradientCache::getBuffer (const QGradient & gradient, qreal opacity)
Definition at line 80 of file qglgradientcache.cpp.
Referenced by QGL2PaintEngineExPrivate::updateBrushTexture(), and ~QGL2GradientCache().
 {
     QMutexLocker lock(&m_mutex);
     quint64 hash_val = 0;
     QGradientStops stops = gradient.stops();
     for (int i = 0; i < stops.size() && i <= 2; i++)
         hash_val += stops[i].second.rgba();
     QGLGradientColorTableHash::const_iterator it = cache.constFind(hash_val);
     if (it == cache.constEnd())
         return addCacheElement(hash_val, gradient, opacity);
     else {
         do {
             const CacheInfo &cache_info = it.value();
             if (cache_info.stops == stops && cache_info.opacity == opacity
                 && cache_info.interpolationMode == gradient.interpolationMode())
             {
                 return cache_info.texId;
             }
             ++it;
         } while (it != cache.constEnd() && it.key() == hash_val);
         // an exact match for these stops and opacity was not found, create new cache
         return addCacheElement(hash_val, gradient, opacity);
     }
 }
maxCacheSize()
int QGL2GradientCache::maxCacheSize () const inline private
Definition at line 86 of file qglgradientcache_p.h.
 { return 60; }
paletteSize()
int QGL2GradientCache::paletteSize () const inline
Definition at line 83 of file qglgradientcache_p.h.
 { return 1024; }
Properties
cache
QGLGradientColorTableHash QGL2GradientCache::cache private
Definition at line 93 of file qglgradientcache_p.h.
m_mutex
QMutex QGL2GradientCache::m_mutex private
Definition at line 94 of file qglgradientcache_p.h.
The documentation for this class was generated from the following files:
/src/opengl/gl2paintengineex/qglgradientcache_p.h
/src/opengl/gl2paintengineex/qglgradientcache.cpp