Qt 4.8: QDeclarativeScriptParser Class Reference
QDeclarativeScriptParser Class Reference
#include <qdeclarativescriptparser_p.h>
Classes
class Import
class JavaScriptMetaData
class TypeReference
Public Functions
void clear ()
QList< QDeclarativeError > errors () const
TypeReference * findOrCreateType (const QString &name)
QList< Import > imports () const
bool parse (const QByteArray &data, const QUrl &url=QUrl())
QDeclarativeScriptParser ()
QList< TypeReference * > referencedTypes () const
QString scriptFile () const
void setScriptFile (const QString &filename)
void setTree (QDeclarativeParser::Object *tree)
QDeclarativeParser::Object * tree () const
~QDeclarativeScriptParser ()
Static Public Functions
static JavaScriptMetaData extractMetaData (QString &)
static QDeclarativeParser::Object::ScriptBlock::Pragmas extractPragmas (QString &)
Public Variables
QList< QDeclarativeError > _errors
QList< Import > _imports
QList< TypeReference * > _refTypes
QString _scriptFile
QDeclarativeScriptParserJsASTData * data
QDeclarativeParser::Object * root
Detailed Description
Definition at line 70 of file qdeclarativescriptparser_p.h.
Constructors and Destructors
QDeclarativeScriptParser()
QDeclarativeScriptParser::QDeclarativeScriptParser ()
Definition at line 800 of file qdeclarativescriptparser.cpp.
 : root(0), data(0)
 {
 }
~QDeclarativeScriptParser()
QDeclarativeScriptParser::~QDeclarativeScriptParser ()
Definition at line 806 of file qdeclarativescriptparser.cpp.
 {
     clear();
 }
Functions
clear()
void QDeclarativeScriptParser::clear ()
Definition at line 1164 of file qdeclarativescriptparser.cpp.
Referenced by QDeclarativeTypeData::done(), parse(), and ~QDeclarativeScriptParser().
 {
     if (root) {
         root->release();
         root = 0;
     }
     _imports.clear();
     qDeleteAll(_refTypes);
     _refTypes.clear();
     _errors.clear();
     if (data) {
         delete data;
         data = 0;
     }
 }
errors()
QList< QDeclarativeError > QDeclarativeScriptParser::errors () const
Definition at line 886 of file qdeclarativescriptparser.cpp.
Referenced by QDeclarativeTypeData::dataReceived().
 {
     return _errors;
 }
extractMetaData()
QDeclarativeScriptParser::JavaScriptMetaData QDeclarativeScriptParser::extractMetaData (QString & script) static
Definition at line 1007 of file qdeclarativescriptparser.cpp.
 {
     JavaScriptMetaData rv;
     QDeclarativeParser::Object::ScriptBlock::Pragmas &pragmas = rv.pragmas;
     const QString pragma(QLatin1String("pragma"));
     const QString js(QLatin1String(".js"));
     const QString library(QLatin1String("library"));
     QDeclarativeJS::Lexer l(0);
     l.setCode(script, 0);
     int token = l.lex();
     while (true) {
         if (token != QDeclarativeJSGrammar::T_DOT)
             return rv;
         int startOffset = l.tokenOffset();
         int startLine = l.currentLineNo();
         token = l.lex();
         CHECK_LINE;
         if (token == QDeclarativeJSGrammar::T_IMPORT) {
             // .import <URI> <Version> as <Identifier>
             // .import <file.js> as <Identifier>
             token = l.lex();
             CHECK_LINE;
             if (token == QDeclarativeJSGrammar::T_STRING_LITERAL) {
                 QString file(l.characterBuffer(), l.characterCount());
                 if (!file.endsWith(js))
                     return rv;
                 token = l.lex();
                 CHECK_TOKEN(T_AS);
                 CHECK_LINE;
                 token = l.lex();
                 CHECK_TOKEN(T_IDENTIFIER);
                 CHECK_LINE;
                 int endOffset = l.tokenLength() + l.tokenOffset();
                 QString importId = script.mid(l.tokenOffset(), l.tokenLength());
                 if (!importId.at(0).isUpper())
                     return rv;
                 token = l.lex();
                 if (l.currentLineNo() == startLine)
                     return rv;
                 replaceWithSpace(script, startOffset, endOffset - startOffset);
                 Import import;
                 import.type = Import::Script;
                 import.uri = file;
                 import.qualifier = importId;
                 rv.imports << import;
             } else {
                 // URI
                 QString uri;
                 QString version;
                 while (true) {
                     if (!isUriToken(token))
                         return rv;
                     uri.append(QString(l.characterBuffer(), l.characterCount()));
                     token = l.lex();
                     CHECK_LINE;
                     if (token != QDeclarativeJSGrammar::T_DOT)
                         break;
                     uri.append(QLatin1Char('.'));
                     token = l.lex();
                     CHECK_LINE;
                 }
                 CHECK_TOKEN(T_NUMERIC_LITERAL);
                 version = script.mid(l.tokenOffset(), l.tokenLength());
                 token = l.lex();
                 CHECK_TOKEN(T_AS);
                 CHECK_LINE;
                 token = l.lex();
                 CHECK_TOKEN(T_IDENTIFIER);
                 CHECK_LINE;
                 int endOffset = l.tokenLength() + l.tokenOffset();
                 QString importId = script.mid(l.tokenOffset(), l.tokenLength());
                 if (!importId.at(0).isUpper())
                     return rv;
                 token = l.lex();
                 if (l.currentLineNo() == startLine)
                     return rv;
                 replaceWithSpace(script, startOffset, endOffset - startOffset);
                 Import import;
                 import.type = Import::Library;
                 import.uri = uri;
                 import.version = version;
                 import.qualifier = importId;
                 rv.imports << import;
             }
         } else if (token == QDeclarativeJSGrammar::T_IDENTIFIER &&
                    script.mid(l.tokenOffset(), l.tokenLength()) == pragma) {
             token = l.lex();
             CHECK_TOKEN(T_IDENTIFIER);
             CHECK_LINE;
             QString pragmaValue = script.mid(l.tokenOffset(), l.tokenLength());
             int endOffset = l.tokenLength() + l.tokenOffset();
             if (pragmaValue == QLatin1String("library")) {
                 pragmas |= QDeclarativeParser::Object::ScriptBlock::Shared;
                 replaceWithSpace(script, startOffset, endOffset - startOffset);
             } else {
                 return rv;
             }
             token = l.lex();
             if (l.currentLineNo() == startLine)
                 return rv;
         } else {
             return rv;
         }
     }
     return rv;
 }
extractPragmas()
QDeclarativeParser::Object::ScriptBlock::Pragmas QDeclarativeScriptParser::extractPragmas (QString & script) static
Definition at line 904 of file qdeclarativescriptparser.cpp.
Referenced by QDeclarativeScriptData::dataReceived(), QDeclarativeInclude::finished(), QDeclarativeInclude::include(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), and QDeclarativeInclude::worker_include().
 {
     QDeclarativeParser::Object::ScriptBlock::Pragmas rv = QDeclarativeParser::Object::ScriptBlock::None;
     const QString pragma(QLatin1String("pragma"));
     const QString library(QLatin1String("library"));
     QDeclarativeJS::Lexer l(0);
     l.setCode(script, 0);
     int token = l.lex();
     while (true) {
         if (token != QDeclarativeJSGrammar::T_DOT)
             return rv;
         int startOffset = l.tokenOffset();
         int startLine = l.currentLineNo();
         token = l.lex();
         if (token != QDeclarativeJSGrammar::T_IDENTIFIER ||
             l.currentLineNo() != startLine ||
             script.mid(l.tokenOffset(), l.tokenLength()) != pragma)
             return rv;
         token = l.lex();
         if (token != QDeclarativeJSGrammar::T_IDENTIFIER ||
             l.currentLineNo() != startLine)
             return rv;
         QString pragmaValue = script.mid(l.tokenOffset(), l.tokenLength());
         int endOffset = l.tokenLength() + l.tokenOffset();
         token = l.lex();
         if (l.currentLineNo() == startLine)
             return rv;
         if (pragmaValue == library) {
             rv |= QDeclarativeParser::Object::ScriptBlock::Shared;
             replaceWithSpace(script, startOffset, endOffset - startOffset);
         } else {
             return rv;
         }
     }
     return rv;
 }
findOrCreateType()
QDeclarativeScriptParser::TypeReference * QDeclarativeScriptParser::findOrCreateType (const QString & name)
Definition at line 1181 of file qdeclarativescriptparser.cpp.
 {
     TypeReference *type = 0;
     int i = 0;
     for (; i < _refTypes.size(); ++i) {
         if (_refTypes.at(i)->name == name) {
             type = _refTypes.at(i);
             break;
         }
     }
     if (!type) {
         type = new TypeReference(i, name);
         _refTypes.append(type);
     }
     return type;
 }
imports()
QList< QDeclarativeScriptParser::Import > QDeclarativeScriptParser::imports () const
Definition at line 881 of file qdeclarativescriptparser.cpp.
Referenced by QDeclarativeTypeData::dataReceived(), QDeclarativeDomDocument::load(), and QDeclarativeTypeData::resolveTypes().
 {
     return _imports;
 }
parse()
bool QDeclarativeScriptParser::parse (const QByteArray & data, const QUrl & url = QUrl())
Definition at line 821 of file qdeclarativescriptparser.cpp.
Referenced by QDeclarativeTypeData::dataReceived().
 {
     clear();
     const QString fileName = url.toString();
     _scriptFile = fileName;
     QTextStream stream(qmldata, QIODevice::ReadOnly);
 #ifndef QT_NO_TEXTCODEC
     stream.setCodec("UTF-8");
 #endif
     const QString code = stream.readAll();
     data = new QDeclarativeScriptParserJsASTData(fileName);
     Lexer lexer(&data->engine);
     lexer.setCode(code, /*line = */ 1);
     Parser parser(&data->engine);
     if (! parser.parse() || !_errors.isEmpty()) {
         // Extract errors from the parser
         foreach (const DiagnosticMessage &m, parser.diagnosticMessages()) {
             if (m.isWarning())
                 continue;
             QDeclarativeError error;
             error.setUrl(url);
             error.setDescription(m.message);
             error.setLine(m.loc.startLine);
             error.setColumn(m.loc.startColumn);
             _errors << error;
         }
     }
     if (_errors.isEmpty()) {
         ProcessAST process(this);
         process(code, parser.ast());
         // Set the url for process errors
         for(int ii = 0; ii < _errors.count(); ++ii)
             _errors[ii].setUrl(url);
     }
     return _errors.isEmpty();
 }
referencedTypes()
QList< QDeclarativeScriptParser::TypeReference * > QDeclarativeScriptParser::referencedTypes () const
Definition at line 871 of file qdeclarativescriptparser.cpp.
Referenced by QDeclarativeCompiler::compile(), QDeclarativeTypeData::done(), and QDeclarativeTypeData::resolveTypes().
 {
     return _refTypes;
 }
scriptFile()
QString QDeclarativeScriptParser::scriptFile () const inline
Definition at line 132 of file qdeclarativescriptparser_p.h.
 { return _scriptFile; }
setScriptFile()
void QDeclarativeScriptParser::setScriptFile (const QString & filename) inline
Definition at line 131 of file qdeclarativescriptparser_p.h.
 {_scriptFile = filename; }
setTree()
void QDeclarativeScriptParser::setTree (QDeclarativeParser::Object * tree)
Definition at line 1199 of file qdeclarativescriptparser.cpp.
 {
     Q_ASSERT(! root);
     root = tree;
 }
tree()
QDeclarativeParser::Object * QDeclarativeScriptParser::tree () const
Definition at line 876 of file qdeclarativescriptparser.cpp.
Referenced by QDeclarativeCompiler::compile(), QDeclarativeDomDocument::load(), and setTree().
 {
     return root;
 }
Properties
_errors
QList<QDeclarativeError> QDeclarativeScriptParser::_errors
Definition at line 135 of file qdeclarativescriptparser_p.h.
Referenced by clear(), errors(), and parse().
_imports
QList<Import> QDeclarativeScriptParser::_imports
Definition at line 138 of file qdeclarativescriptparser_p.h.
Referenced by clear(), and imports().
_refTypes
QList<TypeReference*> QDeclarativeScriptParser::_refTypes
Definition at line 139 of file qdeclarativescriptparser_p.h.
Referenced by clear(), findOrCreateType(), and referencedTypes().
_scriptFile
QString QDeclarativeScriptParser::_scriptFile
Definition at line 140 of file qdeclarativescriptparser_p.h.
Referenced by parse(), scriptFile(), and setScriptFile().
data
QDeclarativeScriptParserJsASTData* QDeclarativeScriptParser::data
Definition at line 141 of file qdeclarativescriptparser_p.h.
Referenced by clear(), parse(), and replaceWithSpace().
root
QDeclarativeParser::Object* QDeclarativeScriptParser::root
Definition at line 137 of file qdeclarativescriptparser_p.h.
Referenced by clear(), setTree(), and tree().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativescriptparser_p.h
/src/declarative/qml/qdeclarativescriptparser.cpp