Qt 4.8: QCoreApplicationPrivate Class Reference
QCoreApplicationPrivate Class Reference
#include <qcoreapplication_p.h>
Public Functions
void appendApplicationPathToLibraryPaths (void)
virtual QString appName () const
void checkReceiverThread (QObject *receiver)
virtual void createEventDispatcher ()
bool notify_helper (QObject *, QEvent *)
void processCommandLineArguments ()
QCoreApplicationPrivate (int &aargc, char **aargv, uint flags)
bool sendThroughApplicationEventFilters (QObject *, QEvent *)
bool sendThroughObjectEventFilters (QObject *, QEvent *)
~QCoreApplicationPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static bool checkInstance (const char *method)
static bool isTranslatorInstalled (QTranslator *translator)
static QString macMenuBarName ()
static QThread * mainThread ()
static QString qmljsDebugArguments ()
static void removePostedEvent (QEvent *)
Removes event from the queue of posted events, and emits a warning message if appropriate.
static void removePostedTimerEvent (QObject *object, int timerId)
static void sendPostedEvents (QObject *receiver, int event_type, QThreadData *data)
static bool testAttribute (uint flag)
static QSettings * trolltechConf ()
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
bool aboutToQuitEmitted
uint application_type
QString applicationName
int & argc
char ** argv
QString cachedApplicationDirPath
QString cachedApplicationFilePath
QCoreApplication::EventFilter eventFilter
bool in_exec
QTranslatorList translators
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Static Public Variables
static int app_compile_version = 0x040000
static uint attribs
static QAbstractEventDispatcher * eventDispatcher = 0
static bool is_app_closing = false
static bool is_app_running = false
static QThread * theMainThread = 0
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 77 of file qcoreapplication_p.h.
Constructors and Destructors
QCoreApplicationPrivate()
QCoreApplicationPrivate::QCoreApplicationPrivate (int & aargc, char ** aargv, uint flags)
Definition at line 428 of file qcoreapplication.cpp.
     : QObjectPrivate(), argc(aargc), argv(aargv), application_type(0), eventFilter(0),
       in_exec(false), aboutToQuitEmitted(false)
 {
     app_compile_version = flags & 0xffffff;
 #if defined(QT3_SUPPORT)
     useQt3Support = !(flags & 0x01000000);
 #endif
     static const char *const empty = "";
     if (argc == 0 || argv == 0) {
         argc = 0;
         argv = (char **)&empty; // ouch! careful with QCoreApplication::argv()!
     }
     QCoreApplicationPrivate::is_app_closing = false;
 #ifdef Q_OS_SYMBIAN
     qt_init_symbian_apa_arguments(argc, argv);
 #endif
 #ifdef Q_OS_UNIX
     qt_application_thread_id = QThread::currentThreadId();
 #endif
 #ifdef Q_OS_QNX
     // make the kernel attempt to emulate an instruction with a misaligned access
     // if the attempt fails, it faults with a SIGBUS
     int tv = -1;
     ThreadCtl(_NTO_TCTL_ALIGN_FAULT, &tv);
     // without Round Robin drawn intensive apps will hog the cpu
     // and make the system appear frozen
     int sched_policy;
     sched_param param;
     if (pthread_getschedparam(0, &sched_policy, &param) == 0 && sched_policy != SCHED_RR) {
         sched_policy = SCHED_RR;
         pthread_setschedparam(0, sched_policy, &param);
     }
 #endif
     // note: this call to QThread::currentThread() may end up setting theMainThread!
     if (QThread::currentThread() != theMainThread)
         qWarning("WARNING: QApplication was not created in the main() thread.");
 }
~QCoreApplicationPrivate()
QCoreApplicationPrivate::~QCoreApplicationPrivate ()
Definition at line 472 of file qcoreapplication.cpp.
 {
     if (threadData) {
 #ifndef QT_NO_THREAD
         void *data = &threadData->tls;
         QThreadStorageData::finish((void **)data);
 #endif
         // need to clear the state of the mainData, just in case a new QCoreApplication comes along.
         QMutexLocker locker(&threadData->postEventList.mutex);
         for (int i = 0; i < threadData->postEventList.size(); ++i) {
             const QPostEvent &pe = threadData->postEventList.at(i);
             if (pe.event) {
                 --pe.receiver->d_func()->postedEvents;
                 pe.event->posted = false;
                 delete pe.event;
             }
         }
         threadData->postEventList.clear();
         threadData->postEventList.recursion = 0;
         threadData->quitNow = false;
     }
 }
Functions
appendApplicationPathToLibraryPaths()
void QCoreApplicationPrivate::appendApplicationPathToLibraryPaths (void)
Definition at line 550 of file qcoreapplication.cpp.
 {
 #if !defined(QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
     QStringList *app_libpaths = coreappdata()->app_libpaths;
     Q_ASSERT(app_libpaths);
 # if defined(Q_OS_SYMBIAN)
     QString app_location( QCoreApplication::applicationDirPath() );
     // File existence check for application's private dir requires additional '\' or
     // platform security will not allow it.
     if (app_location !=  QLibraryInfo::location(QLibraryInfo::PluginsPath) && QFile::exists(app_location + QLatin1Char('\\')) && !app_libpaths->contains(app_location))
 # else
     QString app_location( QCoreApplication::applicationFilePath() );
     app_location.truncate(app_location.lastIndexOf(QLatin1Char('/')));
     app_location = QDir(app_location).canonicalPath();
     if (QFile::exists(app_location) && !app_libpaths->contains(app_location))
 # endif
         app_libpaths->append(app_location);
 #endif
 }
appName()
QString QCoreApplicationPrivate::appName () const virtual
Reimplemented in QApplicationPrivate.
Definition at line 123 of file qcoreapplication_win.cpp.
Referenced by alert_widget().
 {
     return QFileInfo(qAppFileName()).baseName();
 }
checkInstance()
bool QCoreApplicationPrivate::checkInstance (const char * method) static
Definition at line 222 of file qcoreapplication.cpp.
Referenced by QApplication::alert(), alert_widget(), QCoreApplication::exec(), QCoreApplication::hasPendingEvents(), QCoreApplication::installTranslator(), QApplication::keyboardInputDirection(), QApplication::keyboardInputLocale(), qAppName(), QCoreApplication::removeTranslator(), and QApplication::syncX().
 {
     bool b = (QCoreApplication::self != 0);
     if (!b)
         qWarning("QApplication::%s: Please instantiate the QApplication object first", function);
     return b;
 }
checkReceiverThread()
void QCoreApplicationPrivate::checkReceiverThread (QObject * receiver)
Definition at line 527 of file qcoreapplication.cpp.
 {
     QThread *currentThread = QThread::currentThread();
     QThread *thr = receiver->thread();
     Q_ASSERT_X(currentThread == thr || !thr,
                "QCoreApplication::sendEvent",
                QString::fromLatin1("Cannot send events to objects owned by a different thread. "
                                    "Current thread %1. Receiver '%2' (of type '%3') was created in thread %4")
                .arg(QString::number((quintptr) currentThread, 16))
                .arg(receiver->objectName())
                .arg(QLatin1String(receiver->metaObject()->className()))
                .arg(QString::number((quintptr) thr, 16))
                .toLocal8Bit().data());
     Q_UNUSED(currentThread);
     Q_UNUSED(thr);
 }
createEventDispatcher()
void QCoreApplicationPrivate::createEventDispatcher () virtual
Reimplemented in QApplicationPrivate.
Definition at line 496 of file qcoreapplication.cpp.
 {
     Q_Q(QCoreApplication);
 #if defined(Q_OS_SYMBIAN)
     eventDispatcher = new QEventDispatcherSymbian(q);
 #elif defined(Q_OS_UNIX)
 #  if defined(Q_OS_BLACKBERRY)
     eventDispatcher = new QEventDispatcherBlackberry(q);
 #  else
 #  if !defined(QT_NO_GLIB)
     if (qgetenv("QT_NO_GLIB").isEmpty() && QEventDispatcherGlib::versionSupported())
         eventDispatcher = new QEventDispatcherGlib(q);
     else
 #  endif
         eventDispatcher = new QEventDispatcherUNIX(q);
 #  endif
 #elif defined(Q_OS_WIN)
     eventDispatcher = new QEventDispatcherWin32(q);
 #else
 #  error "QEventDispatcher not yet ported to this platform"
 #endif
 }
isTranslatorInstalled()
bool QCoreApplicationPrivate::isTranslatorInstalled (QTranslator * translator) static
Definition at line 2028 of file qcoreapplication.cpp.
Referenced by QTranslatorPrivate::clear().
 {
     return QCoreApplication::self
            && QCoreApplication::self->d_func()->translators.contains(translator);
 }
macMenuBarName()
static QString QCoreApplicationPrivate::macMenuBarName () static
Referenced by QApplicationPrivate::appName().
mainThread()
QThread * QCoreApplicationPrivate::mainThread () static
Definition at line 520 of file qcoreapplication.cpp.
Referenced by connManager(), QNetworkConfigurationManagerPrivate::initialize(), QFactoryLoader::instance(), QFactoryLoader::QFactoryLoader(), and QHostInfoLookupManager::QHostInfoLookupManager().
 {
     Q_ASSERT(theMainThread != 0);
     return theMainThread;
 }
notify_helper()
bool QCoreApplicationPrivate::notify_helper (QObject * receiver, QEvent * event)
Warning
This function is not part of the public interface.
Helper function called by notify()
Definition at line 1077 of file qcoreapplication.cpp.
 {
     // send to all application event filters
     if (sendThroughApplicationEventFilters(receiver, event))
         return true;
     // send to all receiver event filters
     if (sendThroughObjectEventFilters(receiver, event))
         return true;
     // deliver the event
     return receiver->event(event);
 }
processCommandLineArguments()
void QCoreApplicationPrivate::processCommandLineArguments ()
Definition at line 232 of file qcoreapplication.cpp.
 {
     int j = argc ? 1 : 0;
     for (int i = 1; i < argc; ++i) {
         if (argv[i] && *argv[i] != '-') {
             argv[j++] = argv[i];
             continue;
         }
         QByteArray arg = argv[i];
         if (arg.startsWith("-qmljsdebugger=")) {
             *qmljs_debug_arguments() = QString::fromLocal8Bit(arg.right(arg.length() - 15));
         } else if (arg == "-qmljsdebugger" && i < argc - 1) {
             ++i;
             *qmljs_debug_arguments() = QString::fromLocal8Bit(argv[i]);
         } else {
             argv[j++] = argv[i];
         }
     }
     if (j < argc) {
         argv[j] = 0;
         argc = j;
     }
 }
qmljsDebugArguments()
QString QCoreApplicationPrivate::qmljsDebugArguments () static
Definition at line 570 of file qcoreapplication.cpp.
Referenced by QDeclarativeDebugServer::instance().
 {
     return *qmljs_debug_arguments();
 }
removePostedEvent()
void QCoreApplicationPrivate::removePostedEvent (QEvent * event) static
Removes event from the queue of posted events, and emits a warning message if appropriate.
Warning
This function can be really slow. Avoid using it, if possible.
Note
This class or function is threadsafe.em>Reimplemented Function
Definition at line 1739 of file qcoreapplication.cpp.
Referenced by QEvent::~QEvent().
removePostedTimerEvent()
void QCoreApplicationPrivate::removePostedTimerEvent (QObject * object, int timerId) static
Definition at line 221 of file qcoreapplication_win.cpp.
Referenced by QEventDispatcherWin32Private::unregisterTimer().
 {
     QThreadData *data = object->d_func()->threadData;
     QMutexLocker locker(&data->postEventList.mutex);
     if (data->postEventList.size() == 0)
         return;
     for (int i = 0; i < data->postEventList.size(); ++i) {
         const QPostEvent & pe = data->postEventList.at(i);
         if (pe.receiver == object
             && pe.event
             && (pe.event->type() == QEvent::Timer || pe.event->type() == QEvent::ZeroTimerEvent)
             && static_cast<QTimerEvent *>(pe.event)->timerId() == timerId) {
                 --pe.receiver->d_func()->postedEvents;
                 pe.event->posted = false;
                 delete pe.event;
                 const_cast<QPostEvent &>(pe).event = 0;
                 return;
             }
     }
 }
sendPostedEvents()
void QCoreApplicationPrivate::sendPostedEvents (QObject * receiver, int event_type, QThreadData * data) static
Definition at line 1488 of file qcoreapplication.cpp.
Referenced by QEventDispatcherMac::processEvents(), QEventDispatcherUNIX::processEvents(), processPostedEvents(), qt_internal_proc(), and QCoreApplication::sendPostedEvents().
 {
     if (event_type == -1) {
         // we were called by an obsolete event dispatcher.
         event_type = 0;
     }
     if (receiver && receiver->d_func()->threadData != data) {
         qWarning("QCoreApplication::sendPostedEvents: Cannot send "
                  "posted events for objects in another thread");
         return;
     }
     ++data->postEventList.recursion;
 #ifdef QT3_SUPPORT
     if (event_type == QEvent::ChildInserted) {
         if (receiver) {
             // optimize sendPostedEvents(w, QEvent::ChildInserted) calls away
             receiver->d_func()->sendPendingChildInsertedEvents();
             --data->postEventList.recursion;
             return;
         }
         // ChildInserted events are sent in response to *Request
         event_type = QEvent::ChildInsertedRequest;
     }
 #endif
     QMutexLocker locker(&data->postEventList.mutex);
     // by default, we assume that the event dispatcher can go to sleep after
     // processing all events. if any new events are posted while we send
     // events, canWait will be set to false.
     data->canWait = (data->postEventList.size() == 0);
     if (data->postEventList.size() == 0 || (receiver && !receiver->d_func()->postedEvents)) {
         --data->postEventList.recursion;
         return;
     }
     data->canWait = true;
     // okay. here is the tricky loop. be careful about optimizing
     // this, it looks the way it does for good reasons.
     int startOffset = data->postEventList.startOffset;
     int &i = (!event_type && !receiver) ? data->postEventList.startOffset : startOffset;
     data->postEventList.insertionOffset = data->postEventList.size();
     while (i < data->postEventList.size()) {
         // avoid live-lock
         if (i >= data->postEventList.insertionOffset)
             break;
         const QPostEvent &pe = data->postEventList.at(i);
         ++i;
         if (!pe.event)
             continue;
         if ((receiver && receiver != pe.receiver) || (event_type && event_type != pe.event->type())) {
             data->canWait = false;
             continue;
         }
         if (pe.event->type() == QEvent::DeferredDelete) {
             // DeferredDelete events are only sent when we are explicitly asked to
             // (s.a. QEvent::DeferredDelete), and then only if the event loop that
             // posted the event has returned.
             const bool allowDeferredDelete =
                 (quintptr(pe.event->d) > unsigned(data->loopLevel)
                  || (!quintptr(pe.event->d) && data->loopLevel > 0)
                  || (event_type == QEvent::DeferredDelete
                      && quintptr(pe.event->d) == unsigned(data->loopLevel)));
             if (!allowDeferredDelete) {
                 // cannot send deferred delete
                 if (!event_type && !receiver) {
                     // don't lose the event
                     data->postEventList.addEvent(pe);
                     const_cast<QPostEvent &>(pe).event = 0;
                 }
                 continue;
             }
         }
         // first, we diddle the event so that we can deliver
         // it, and that no one will try to touch it later.
         pe.event->posted = false;
         QEvent * e = pe.event;
         QObject * r = pe.receiver;
         --r->d_func()->postedEvents;
         Q_ASSERT(r->d_func()->postedEvents >= 0);
         // next, update the data structure so that we're ready
         // for the next event.
         const_cast<QPostEvent &>(pe).event = 0;
         locker.unlock();
         // after all that work, it's time to deliver the event.
 #ifdef QT_NO_EXCEPTIONS
         QCoreApplication::sendEvent(r, e);
 #else
         try {
             QCoreApplication::sendEvent(r, e);
         } catch (...) {
             delete e;
             locker.relock();
             // since we were interrupted, we need another pass to make sure we clean everything up
             data->canWait = false;
             // uglehack: copied from below
             --data->postEventList.recursion;
             if (!data->postEventList.recursion && !data->canWait && data->eventDispatcher)
                 data->eventDispatcher->wakeUp();
             throw;              // rethrow
         }
 #endif
         delete e;
         locker.relock();
         // careful when adding anything below this point - the
         // sendEvent() call might invalidate any invariants this
         // function depends on.
     }
     --data->postEventList.recursion;
     if (!data->postEventList.recursion && !data->canWait && data->eventDispatcher)
         data->eventDispatcher->wakeUp();
     // clear the global list, i.e. remove everything that was
     // delivered.
     if (!event_type && !receiver && data->postEventList.startOffset >= 0) {
         const QPostEventList::iterator it = data->postEventList.begin();
         data->postEventList.erase(it, it + data->postEventList.startOffset);
         data->postEventList.insertionOffset -= data->postEventList.startOffset;
         Q_ASSERT(data->postEventList.insertionOffset >= 0);
         data->postEventList.startOffset = 0;
     }
 }
sendThroughApplicationEventFilters()
bool QCoreApplicationPrivate::sendThroughApplicationEventFilters (QObject * receiver, QEvent * event)
Definition at line 1035 of file qcoreapplication.cpp.
 {
     if (receiver->d_func()->threadData == this->threadData) {
         // application event filters are only called for objects in the GUI thread
         for (int i = 0; i < eventFilters.size(); ++i) {
             register QObject *obj = eventFilters.at(i);
             if (!obj)
                 continue;
             if (obj->d_func()->threadData != threadData) {
                 qWarning("QCoreApplication: Application event filter cannot be in a different thread.");
                 continue;
             }
             if (obj->eventFilter(receiver, event))
                 return true;
         }
     }
     return false;
 }
sendThroughObjectEventFilters()
bool QCoreApplicationPrivate::sendThroughObjectEventFilters (QObject * receiver, QEvent * event)
Definition at line 1054 of file qcoreapplication.cpp.
 {
     Q_Q(QCoreApplication);
     if (receiver != q) {
         for (int i = 0; i < receiver->d_func()->eventFilters.size(); ++i) {
             register QObject *obj = receiver->d_func()->eventFilters.at(i);
             if (!obj)
                 continue;
             if (obj->d_func()->threadData != receiver->d_func()->threadData) {
                 qWarning("QCoreApplication: Object event filter cannot be in a different thread.");
                 continue;
             }
             if (obj->eventFilter(receiver, event))
                 return true;
         }
     }
     return false;
 }
testAttribute()
static bool QCoreApplicationPrivate::testAttribute (uint flag) inline static
Definition at line 146 of file qcoreapplication_p.h.
Referenced by QWidget::create(), QWidgetPrivate::init(), qt_cleanup(), QWidget::setParent(), QCoreApplication::testAttribute(), and QETWidget::translateKeyEvent().
 { return attribs & (1 << flag); }
trolltechConf()
static QSettings* QCoreApplicationPrivate::trolltechConf () static
Referenced by QLibraryPrivate::isPlugin().
Properties
aboutToQuitEmitted
bool QCoreApplicationPrivate::aboutToQuitEmitted
Definition at line 125 of file qcoreapplication_p.h.
Referenced by QtWndProc().
app_compile_version
int QCoreApplicationPrivate::app_compile_version = 0x040000 static
Definition at line 147 of file qcoreapplication_p.h.
Referenced by QWidgetPrivate::init(), QApplication::QApplication(), and QWidget::setParent().
application_type
uint QCoreApplicationPrivate::application_type
Definition at line 120 of file qcoreapplication_p.h.
Referenced by QApplicationPrivate::QApplicationPrivate().
applicationName
QString QCoreApplicationPrivate::applicationName mutable
Definition at line 90 of file qcoreapplication_p.h.
argc
int& QCoreApplicationPrivate::argc
Definition at line 110 of file qcoreapplication_p.h.
Referenced by QApplicationPrivate::process_cmdline(), qt_init(), and qWinMain().
argv
char** QCoreApplicationPrivate::argv
Definition at line 111 of file qcoreapplication_p.h.
Referenced by QApplicationPrivate::process_cmdline(), and qt_init().
attribs
uint QCoreApplicationPrivate::attribs static
Definition at line 145 of file qcoreapplication_p.h.
Referenced by qt_set_current_thread_to_main_thread().
cachedApplicationDirPath
QString QCoreApplicationPrivate::cachedApplicationDirPath
Definition at line 126 of file qcoreapplication_p.h.
Referenced by QCoreApplication::applicationDirPath().
cachedApplicationFilePath
QString QCoreApplicationPrivate::cachedApplicationFilePath
Definition at line 127 of file qcoreapplication_p.h.
Referenced by QCoreApplication::applicationFilePath().
eventDispatcher
QAbstractEventDispatcher * QCoreApplicationPrivate::eventDispatcher = 0 static
Definition at line 141 of file qcoreapplication_p.h.
Referenced by QCoreApplication::init(), qt_set_current_thread_to_main_thread(), and QETWidget::raiseOnClick().
eventFilter
QCoreApplication::EventFilter QCoreApplicationPrivate::eventFilter
Definition at line 122 of file qcoreapplication_p.h.
in_exec
bool QCoreApplicationPrivate::in_exec
Definition at line 124 of file qcoreapplication_p.h.
is_app_closing
bool QCoreApplicationPrivate::is_app_closing = false static
Definition at line 143 of file qcoreapplication_p.h.
Referenced by QCoreApplication::closingDown(), QApplication::inputContext(), QApplication::notify(), qt_call_post_routines(), QApplication::setFont(), QApplicationPrivate::setPalette_helper(), QApplication::setStyle(), QApplication::setWindowIcon(), QApplication::~QApplication(), QGraphicsScene::~QGraphicsScene(), and QWidget::~QWidget().
is_app_running
bool QCoreApplicationPrivate::is_app_running = false static
Definition at line 142 of file qcoreapplication_p.h.
Referenced by qt_call_post_routines(), QApplication::setFont(), QApplicationPrivate::setPalette_helper(), QApplication::setStyle(), QApplication::setWindowIcon(), QCoreApplication::startingUp(), and QApplication::~QApplication().
theMainThread
QThread * QCoreApplicationPrivate::theMainThread = 0 static
Definition at line 102 of file qcoreapplication_p.h.
Referenced by createEventDispatcher(), QThreadData::current(), qt_free_tls(), qt_set_current_thread_to_main_thread(), QCoreApplicationData::~QCoreApplicationData(), and QThreadData::~QThreadData().
translators
QTranslatorList QCoreApplicationPrivate::translators
Definition at line 118 of file qcoreapplication_p.h.
Referenced by QCoreApplication::installTranslator(), and QCoreApplication::removeTranslator().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qcoreapplication_p.h
/src/corelib/kernel/qcoreapplication.cpp
/src/corelib/kernel/qcoreapplication_win.cpp