Qt 4.8: QDeclarativePackagePrivate Class Reference
QDeclarativePackagePrivate Class Reference
This attached property holds the name of an item within a Package.
Classes
struct DataGuard
Public Functions
QDeclarativePackagePrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static void data_append (QDeclarativeListProperty< QObject > *prop, QObject *o)
static QObject * data_at (QDeclarativeListProperty< QObject > *prop, int index)
static void data_clear (QDeclarativeListProperty< QObject > *prop)
static int data_count (QDeclarativeListProperty< QObject > *prop)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QList< DataGuard > dataList
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
This attached property holds the name of an item within a Package.
string Package::name
Definition at line 89 of file qdeclarativepackage.cpp.
Constructors and Destructors
QDeclarativePackagePrivate()
QDeclarativePackagePrivate::QDeclarativePackagePrivate () inline
Definition at line 92 of file qdeclarativepackage.cpp.
 {}
Functions
data_append()
static void QDeclarativePackagePrivate::data_append (QDeclarativeListProperty< QObject > * prop, QObject * o) inline static
Definition at line 105 of file qdeclarativepackage.cpp.
Referenced by QDeclarativePackage::~QDeclarativePackage().
{
         QList<DataGuard> *list = static_cast<QList<DataGuard> *>(prop->data);
         list->append(DataGuard(o, list));
     }
data_at()
static QObject* QDeclarativePackagePrivate::data_at (QDeclarativeListProperty< QObject > * prop, int index) inline static
Definition at line 113 of file qdeclarativepackage.cpp.
Referenced by QDeclarativePackage::~QDeclarativePackage().
{
         QList<DataGuard> *list = static_cast<QList<DataGuard> *>(prop->data);
         return list->at(index);
     }
data_clear()
static void QDeclarativePackagePrivate::data_clear (QDeclarativeListProperty< QObject > * prop) inline static
Definition at line 109 of file qdeclarativepackage.cpp.
Referenced by QDeclarativePackage::~QDeclarativePackage().
{
         QList<DataGuard> *list = static_cast<QList<DataGuard> *>(prop->data);
         list->clear();
     }
data_count()
static int QDeclarativePackagePrivate::data_count (QDeclarativeListProperty< QObject > * prop) inline static
Definition at line 117 of file qdeclarativepackage.cpp.
Referenced by QDeclarativePackage::~QDeclarativePackage().
{
         QList<DataGuard> *list = static_cast<QList<DataGuard> *>(prop->data);
         return list->count();
     }
Properties
dataList
QList<DataGuard> QDeclarativePackagePrivate::dataList
Definition at line 104 of file qdeclarativepackage.cpp.
The documentation for this class was generated from the following file:
/src/declarative/util/qdeclarativepackage.cpp