Qt 4.8: QPatternist::PatternPlatform Class Reference
QPatternist::PatternPlatform Class Reference
Contains functionality for functions and expressions that uses regular expressions.
#include <qpatternplatform_p.h>
Public Types
enum Flag {
NoFlags = 0, DotAllMode = 1, MultiLineMode = 2, CaseInsensitive = 4,
SimplifyWhitespace = 8
}
typedef QFlags< Flag > Flags
Public Types inherited from QPatternist::FunctionCall
typedef QExplicitlySharedDataPointer< FunctionCall > Ptr
Public Types inherited from QPatternist::UnlimitedContainer
enum CardinalityComputation { ProductOfCardinality, UnionOfCardinality }
Public Types inherited from QPatternist::Expression
typedef QExplicitlySharedDataPointer< const Expression > ConstPtr
A smart pointer wrapping const Expression instances.
enum ID {
IDBooleanValue = 1, IDCountFN, IDEmptyFN, IDExistsFN,
IDExpressionSequence, IDGeneralComparison, IDIfThenClause, IDIgnorableExpression,
IDIntegerValue, IDPositionFN, IDStringValue, IDValueComparison,
IDRangeVariableReference, IDContextItem, IDUserFunctionCallsite, IDExpressionVariableReference,
IDAttributeConstructor, IDUpperCaseFN, IDLowerCaseFN, IDFirstItemPredicate,
IDEmptySequence, IDReturnOrderBy, IDLetClause, IDForClause,
IDPath, IDNamespaceConstructor, IDArgumentReference, IDGenericPredicate,
IDAxisStep, IDFloat, IDCombineNodes, IDUnresolvedVariableReference,
IDCardinalityVerifier
}
typedef QList< Expression::Ptr > List
typedef QFlags< Property > Properties
enum Property {
UseContextItem = 1, DisableElimination = 1 << 1, IsEvaluated = 1 << 2, DisableTypingDeduction = 1 << 3,
EmptynessFollowsChild = 1 << 4, RewriteToEmptyOnEmpty = 1 << 5, RequiresFocus = 1 << 6, AffectsOrderOnly = 1 << 7,
RequiresContextItem = (1 << 8) | RequiresFocus, CreatesFocusForLast = 1 << 9, LastOperandIsCollation = 1 << 10, DependsOnLocalVariable = (1 << 11) | DisableElimination,
EvaluationCacheRedundant = (1 << 12), IsNodeConstructor = 1 << 13, RequiresCurrentItem = 1 << 14
}
typedef QExplicitlySharedDataPointer< Expression > Ptr
A smart pointer wrapping mutable Expression instances.
typedef ::QAbstractXmlForwardIterator< Expression::Ptr > QAbstractXmlForwardIterator
typedef QVector< Expression::Ptr > Vector
Public Functions
int captureCount () const
virtual Expression::Ptr compress (const StaticContext::Ptr &context)
const QRegExp pattern (const DynamicContext::Ptr &context) const
Public Functions inherited from QPatternist::FunctionCall
virtual ExpressionVisitorResult::Ptr accept (const ExpressionVisitor::Ptr &visitor) const
virtual SequenceType::List expectedOperandTypes () const
virtual ID id () const
virtual Expression::Properties properties () const
virtual void setSignature (const FunctionSignature::Ptr &sign)
virtual FunctionSignature::Ptr signature () const
virtual SequenceType::Ptr staticType () const
virtual Expression::Ptr typeCheck (const StaticContext::Ptr &context, const SequenceType::Ptr &reqType)
Public Functions inherited from QPatternist::UnlimitedContainer
virtual bool compressOperands (const StaticContext::Ptr &)
virtual Expression::List operands () const
virtual void setOperands (const Expression::List &list)
UnlimitedContainer (const Expression::List &operands=Expression::List())
Public Functions inherited from QPatternist::Expression
virtual const SourceLocationReflection * actualReflection () const
Returns this.
virtual void announceFocusType (const ItemType::Ptr &itemType)
Properties deepProperties () const
Computes the union of properties for this Expression and all its descending children.
virtual Properties dependencies () const
virtual QString description () const
virtual bool evaluateEBV (const DynamicContext::Ptr &context) const
virtual Item::Iterator::Ptr evaluateSequence (const DynamicContext::Ptr &context) const
virtual Item evaluateSingleton (const DynamicContext::Ptr &context) const
virtual void evaluateToSequenceReceiver (const DynamicContext::Ptr &context) const
virtual ItemType::Ptr expectedContextItemType () const
Expression ()
bool has (const Property prop) const
bool hasDependency (const Property prop) const
bool is (const ID id) const
bool isEvaluated () const
virtual ItemType::Ptr newFocusType () const
virtual QList< QExplicitlySharedDataPointer< OptimizationPass > > optimizationPasses () const
virtual PatternPriority patternPriority () const
const Expression::Ptr & rewrite (const Expression::Ptr &to, const StaticContext::Ptr &context) const
Rewrites this Expression to to, and return to.
virtual ~Expression ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< Expression >
const TCastTarget * as () const
TCastTarget * as ()
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Static Public Functions
static QRegExp parsePattern (const QString &pattern, const ReportContext::Ptr &context, const SourceLocationReflection *const location)
Parses pattern.
Static Public Functions inherited from QPatternist::Expression
static void rewrite (Expression::Ptr &old, const Expression::Ptr &New, const StaticContext::Ptr &context)
Protected Functions
PatternPlatform (const qint8 flagsPosition)
This constructor is protected, because this class is supposed to be sub-classed.
Protected Functions inherited from QPatternist::UnlimitedContainer
template<CardinalityComputation suppliedCard>
SequenceType::Ptr operandsUnionType () const
Protected Functions inherited from QPatternist::Expression
void typeCheckOperands (const StaticContext::Ptr &context)
Protected Functions inherited from QPatternist::CppCastingHelper< Expression >
CppCastingHelper ()
Private Types
enum PreCompiledPart { NoPart = 0, PatternPrecompiled = 1, FlagsPrecompiled = 2, FlagsAndPattern = PatternPrecompiled | FlagsPrecompiled }
typedef QFlags< PreCompiledPart > PreCompiledParts
Private Functions
Flags parseFlags (const QString &flags, const DynamicContext::Ptr &context) const
QRegExp parsePattern (const QString &pattern, const ReportContext::Ptr &context) const
Calls the public parsePattern() function and passes in this as the location.
Static Private Functions
static void applyFlags (const Flags flags, QRegExp &pattern)
Properties
PreCompiledParts m_compiledParts
Flags m_flags
const qint8 m_flagsPosition
QRegExp m_pattern
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Variables inherited from QPatternist::UnlimitedContainer
Expression::List m_operands
Detailed Description
Contains functionality for functions and expressions that uses regular expressions.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 73 of file qpatternplatform_p.h.
Typedefs
Flags
typedef QFlags<Flag> QPatternist::PatternPlatform::Flags
Definition at line 107 of file qpatternplatform_p.h.
PreCompiledParts
typedef QFlags<PreCompiledPart> QPatternist::PatternPlatform::PreCompiledParts private
Definition at line 155 of file qpatternplatform_p.h.
Enumerations
Flag
enum QPatternist::PatternPlatform::Flag
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 7.6.1.1 Flags
Enumerator
NoFlags
No flags are set. Default behavior is used.
DotAllMode
Flag s
MultiLineMode
Flag m
CaseInsensitive
Flag i
SimplifyWhitespace
Flag x
Definition at line 80 of file qpatternplatform_p.h.
         {
             NoFlags             = 0,
             DotAllMode          = 1,
             MultiLineMode       = 2,
             CaseInsensitive     = 4,
             SimplifyWhitespace  = 8
         };
PreCompiledPart
enum QPatternist::PatternPlatform::PreCompiledPart private
Enum telling whether the flags, pattern, or both have been compiled at compile time.
Enumerator
NoPart
PatternPrecompiled
FlagsPrecompiled
FlagsAndPattern
Definition at line 147 of file qpatternplatform_p.h.
         {
             NoPart          = 0,
             PatternPrecompiled     = 1,
             FlagsPrecompiled       = 2,
             FlagsAndPattern = PatternPrecompiled | FlagsPrecompiled
         };
Constructors and Destructors
PatternPlatform()
PatternPlatform::PatternPlatform (const qint8 flagsPosition) protected
This constructor is protected, because this class is supposed to be sub-classed.
Parameters
flagsPosition an index position specifying the operand containing the pattern flags.
Definition at line 112 of file qpatternplatform.cpp.
                                                           : m_compiledParts(NoPart),
                                                               m_flags(NoFlags),
                                                               m_flagsPosition(flagsPosition)
 {
 }
Functions
applyFlags()
void PatternPlatform::applyFlags (const Flags flags, QRegExp & pattern) static private
Definition at line 158 of file qpatternplatform.cpp.
Referenced by compress(), and pattern().
 {
     Q_ASSERT(patternP.isValid());
     if(flags == NoFlags)
         return;
     if(flags & CaseInsensitive)
     {
         patternP.setCaseSensitivity(Qt::CaseInsensitive);
     }
     // TODO Apply the other flags, like 'x'.
 }
captureCount()
int QPatternist::PatternPlatform::captureCount () const inline
Returns
the number of captures, also called parenthesized sub-expressions, the pattern has.
If the pattern isn't precompiled, -1 is returned.
Definition at line 180 of file qpatternplatform_p.h.
Referenced by QPatternist::ReplaceFN::compress().
     {
         if(m_compiledParts.testFlag(PatternPrecompiled))
             return m_pattern.captureCount();
         else
             return -1;
     }
compress()
Expression::Ptr PatternPlatform::compress (const StaticContext::Ptr & context) virtual
compress() is the last stage performs in compiling an expression, done after the initial AST build and calling typeCheck(). compress() performs crucial simplifications, either by having drastic performance implications or that some expressions depend on it for proper behavior.
The default implementation performs a sparse conditional constant propagation. In short, a recursive process is performed in the AST which examines if the Expression's operands are constant values, and if so, performs a const fold(AST rewrite) into the result of evaluating the expression in question. This default behavior can be disabled by letting properties() return DisableElimination.
This compress() stage can be relative effective due to the design of XPath, in part because intrinsic functions are heavily used. Many Expressions override compress() and do optimizations specific to what they do. Also, many Expressions performs optimizations in their typeCheck().
Parameters
context the static context. Supplies compile time information, and is the channel for communicating error messages.
See also
Wikipedia, the free encyclopedia, Sparse conditional constant propagation
Wikipedia, the free encyclopedia, Intrinsic function
Wikipedia, the free encyclopedia, Compiler optimization
Reimplemented from QPatternist::Expression.
Reimplemented in QPatternist::ReplaceFN.
Definition at line 265 of file qpatternplatform.cpp.
Referenced by QPatternist::ReplaceFN::compress().
 {
     const Expression::Ptr me(FunctionCall::compress(context));
     if(me != this)
         return me;
     if(m_operands.at(1)->is(IDStringValue))
     {
         const DynamicContext::Ptr dynContext(context->dynamicContext());
         m_pattern = parsePattern(m_operands.at(1)->evaluateSingleton(dynContext).stringValue(),
                                  dynContext);
         m_compiledParts |= PatternPrecompiled;
     }
     const Expression::Ptr flagOperand(m_operands.value(m_flagsPosition));
     if(!flagOperand)
     {
         m_flags = NoFlags;
         m_compiledParts |= FlagsPrecompiled;
     }
     else if(flagOperand->is(IDStringValue))
     {
         const DynamicContext::Ptr dynContext(context->dynamicContext());
         m_flags = parseFlags(flagOperand->evaluateSingleton(dynContext).stringValue(),
                              dynContext);
         m_compiledParts |= FlagsPrecompiled;
     }
     if(m_compiledParts == FlagsAndPattern)
         applyFlags(m_flags, m_pattern);
     return me;
 }
parseFlags()
PatternPlatform::Flags PatternPlatform::parseFlags (const QString & flags, const DynamicContext::Ptr & context) const private
Definition at line 213 of file qpatternplatform.cpp.
Referenced by compress(), and pattern().
 {
     if(flags.isEmpty())
         return NoFlags;
     const PatternFlag::Hash flagDescrs(flagDescriptions());
     const int len = flags.length();
     Flags retval = NoFlags;
     for(int i = 0; i < len; ++i)
     {
         const QChar flag(flags.at(i));
         const Flag specified = flagDescrs.value(flag).flag;
         if(specified != NoFlags)
         {
             retval |= specified;
             continue;
         }
         /* Generate a nice error message. */
         QString message(QtXmlPatterns::tr("%1 is an invalid flag for regular expressions. Valid flags are:")
                              .arg(formatKeyword(flag)));
         /* This is formatting, so don't bother translators with it. */
         message.append(QLatin1Char('\n'));
         const PatternFlag::Hash::const_iterator end(flagDescrs.constEnd());
         PatternFlag::Hash::const_iterator it(flagDescrs.constBegin());
         for(; it != end;)
         {
             // TODO handle bidi correctly
             // TODO format this with rich text(list/table)
             message.append(formatKeyword(it.key()));
             message.append(QLatin1String(" - "));
             message.append(it.value().description);
             ++it;
             if(it != end)
                 message.append(QLatin1Char('\n'));
         }
         context->error(message, ReportContext::FORX0001, this);
         return NoFlags;
     }
     return retval;
 }
parsePattern() [1/2]
QRegExp PatternPlatform::parsePattern (const QString & pattern, const ReportContext::Ptr & context, const SourceLocationReflection *const location) static
Parses pattern.
Definition at line 177 of file qpatternplatform.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdTypeChecker::checkConstrainingFacetsBoolean(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDateTime(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDouble(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDuration(), QPatternist::XsdTypeChecker::checkConstrainingFacetsList(), QPatternist::XsdTypeChecker::checkConstrainingFacetsQName(), QPatternist::XsdTypeChecker::checkConstrainingFacetsSignedInteger(), QPatternist::XsdTypeChecker::checkConstrainingFacetsString(), QPatternist::XsdTypeChecker::checkConstrainingFacetsUnion(), QPatternist::XsdTypeChecker::checkConstrainingFacetsUnsignedInteger(), compress(), parsePattern(), and pattern().
 {
     if(patternP == QLatin1String("(.)\\3") ||
        patternP == QLatin1String("\\3")    ||
        patternP == QLatin1String("(.)\\2"))
     {
         context->error(QLatin1String("We don't want to hang infinitely on K2-MatchesFunc-9, "
                                      "10 and 11."),
                        ReportContext::FOER0000, location);
         return QRegExp();
     }
     QString rewrittenPattern(patternP);
     /* We rewrite some well known patterns to QRegExp style here. Note that
      * these character classes only works in the ASCII range, and fail for
      * others. This support needs to be in QRegExp, since it's about checking
      * QChar::category(). */
     rewrittenPattern.replace(QLatin1String("[\\i-[:]]"), QLatin1String("[a-zA-Z_]"));
     rewrittenPattern.replace(QLatin1String("[\\c-[:]]"), QLatin1String("[a-zA-Z0-9_\\-\\.]"));
     QRegExp retval(rewrittenPattern, Qt::CaseSensitive, QRegExp::W3CXmlSchema11);
     if(retval.isValid())
         return retval;
     else
     {
         context->error(QtXmlPatterns::tr("%1 is an invalid regular expression pattern: %2")
                                         .arg(formatExpression(patternP), retval.errorString()),
                                    ReportContext::FORX0002, location);
         return QRegExp();
     }
 }
parsePattern() [2/2]
QRegExp PatternPlatform::parsePattern (const QString & pattern, const ReportContext::Ptr & context) const inline private
Calls the public parsePattern() function and passes in this as the location.
Definition at line 171 of file qpatternplatform.cpp.
 {
     return parsePattern(pattern, context, this);
 }
pattern()
const QRegExp PatternPlatform::pattern (const DynamicContext::Ptr & context) const
Retrieves the pattern supplied in the arguments, taking care of compiling it, settings its flags, and everything else required for getting it ready to use. If an error occurs, an appropriate error is raised via context.
Definition at line 118 of file qpatternplatform.cpp.
Referenced by QPatternist::TokenizeFN::evaluateSequence(), QPatternist::MatchesFN::evaluateSingleton(), and QPatternist::ReplaceFN::evaluateSingleton().
 {
     if(m_compiledParts == FlagsAndPattern) /* This is the most common case. */
     {
         Q_ASSERT(m_pattern.isValid());
         return m_pattern;
     }
     QRegExp retvalPattern;
     Flags flags;
     /* Compile the flags, if necessary. */
     if(m_compiledParts.testFlag(FlagsPrecompiled))
         flags = m_flags;
     else
     {
         const Expression::Ptr flagsOp(m_operands.value(m_flagsPosition));
         if(flagsOp)
             flags = parseFlags(flagsOp->evaluateSingleton(context).stringValue(), context);
         else
             flags = NoFlags;
     }
     /* Compile the pattern, if necessary. */
     if(m_compiledParts.testFlag(PatternPrecompiled))
         retvalPattern = m_pattern;
     else
     {
         retvalPattern = parsePattern(m_operands.at(1)->evaluateSingleton(context).stringValue(),
                                      context);
     }
     applyFlags(flags, retvalPattern);
     Q_ASSERT(m_pattern.isValid());
     return retvalPattern;
 }
Properties
m_compiledParts
PreCompiledParts QPatternist::PatternPlatform::m_compiledParts private
The parts that have been pre-compiled at compile time.
Definition at line 174 of file qpatternplatform_p.h.
Referenced by captureCount(), compress(), and pattern().
m_flags
Flags QPatternist::PatternPlatform::m_flags private
Definition at line 175 of file qpatternplatform_p.h.
Referenced by compress(), and pattern().
m_flagsPosition
const qint8 QPatternist::PatternPlatform::m_flagsPosition private
Definition at line 177 of file qpatternplatform_p.h.
Referenced by compress(), and pattern().
m_pattern
QRegExp QPatternist::PatternPlatform::m_pattern private
Definition at line 176 of file qpatternplatform_p.h.
Referenced by captureCount(), compress(), and pattern().
The documentation for this class was generated from the following files:
/src/xmlpatterns/functions/qpatternplatform_p.h
/src/xmlpatterns/functions/qpatternplatform.cpp