Qt 4.8: Maemo::GConfItemFast Class Reference
Maemo::GConfItemFast Class Reference
Public Functions
GConfItemFast (const QString &k)
QHash< QString, QVariant > getEntries () const
Properties
QString key
Detailed Description
Definition at line 106 of file proxyconf.cpp.
Constructors and Destructors
GConfItemFast()
Maemo::GConfItemFast::GConfItemFast (const QString & k) inline
Definition at line 108 of file proxyconf.cpp.
 : key(k) {}
Functions
getEntries()
QHash< QString, QVariant > Maemo::GConfItemFast::getEntries () const
Definition at line 118 of file proxyconf.cpp.
Referenced by GConfItemFast(), Maemo::getHttpValues(), and Maemo::getValues().
 {
     QHash<QString,QVariant> children;
     withClient(client) {
         QByteArray k = key.toUtf8();
         GSList *entries = gconf_client_all_entries(client, k.data(), NULL);
         for (GSList *e = entries; e; e = e->next) {
         char *key_name = strrchr(((GConfEntry *)e->data)->key, '/');
         if (!key_name)
             key_name = ((GConfEntry *)e->data)->key;
         else
             key_name++;
         QString key(convertKey(key_name));
         QVariant value = convertValue(((GConfEntry *)e->data)->value);
         gconf_entry_unref((GConfEntry *)e->data);
         //qDebug()<<"key="<<key<<"value="<<value;
         children.insert(key, value);
         }
         g_slist_free (entries);
     }
     return children;
 }
Properties
key
QString Maemo::GConfItemFast::key private
Definition at line 112 of file proxyconf.cpp.
Referenced by getEntries().
The documentation for this class was generated from the following file:
/src/plugins/bearer/icd/proxyconf.cpp