Qt 4.8: QGraphicsLayoutItem Class Reference
QGraphicsLayoutItem Class Reference abstract
The QGraphicsLayoutItem class can be inherited to allow your custom items to be managed by layouts.
#include <qgraphicslayoutitem.h>
Public Functions
QRectF contentsRect () const
Returns the contents rect in local coordinates.
QSizeF effectiveSizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Returns the effective size hint for this QGraphicsLayoutItem.
QRectF geometry () const
Returns the item's geometry (e.
virtual void getContentsMargins (qreal *left, qreal *top, qreal *right, qreal *bottom) const
This virtual function provides the left, top, right and bottom contents margins for this QGraphicsLayoutItem.
QGraphicsItem * graphicsItem () const
Returns the QGraphicsItem that this layout item represents.
bool isLayout () const
Returns true if this QGraphicsLayoutItem is a layout (e.g., is inherited by an object that arranges other QGraphicsLayoutItem objects); otherwise returns false.
qreal maximumHeight () const
Returns the maximum height.
QSizeF maximumSize () const
Returns the maximum size.
qreal maximumWidth () const
Returns the maximum width.
qreal minimumHeight () const
Returns the minimum height.
QSizeF minimumSize () const
Returns the minimum size.
qreal minimumWidth () const
Returns the minimum width.
bool ownedByLayout () const
Returns whether a layout should delete this item in its destructor.
QGraphicsLayoutItem * parentLayoutItem () const
Returns the parent of this QGraphicsLayoutItem, or 0 if there is no parent, or if the parent does not inherit from QGraphicsLayoutItem (QGraphicsLayoutItem is often used through multiple inheritance with QObject-derived classes).
qreal preferredHeight () const
Returns the preferred height.
QSizeF preferredSize () const
Returns the preferred size.
qreal preferredWidth () const
Returns the preferred width.
QGraphicsLayoutItem (QGraphicsLayoutItem *parent=0, bool isLayout=false)
Constructs the QGraphicsLayoutItem object.
virtual void setGeometry (const QRectF &rect)
This virtual function sets the geometry of the QGraphicsLayoutItem to rect, which is in parent coordinates (e.
void setMaximumHeight (qreal height)
Sets the maximum height to height.
void setMaximumSize (const QSizeF &size)
Sets the maximum size to size.
void setMaximumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMaximumSize(QSizeF(w, h)).
void setMaximumWidth (qreal width)
Sets the maximum width to width.
void setMinimumHeight (qreal height)
Sets the minimum height to height.
void setMinimumSize (const QSizeF &size)
Sets the minimum size to size.
void setMinimumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMinimumSize(QSizeF(w, h)).
void setMinimumWidth (qreal width)
Sets the minimum width to width.
void setParentLayoutItem (QGraphicsLayoutItem *parent)
Sets the parent of this QGraphicsLayoutItem to parent.
void setPreferredHeight (qreal height)
Sets the preferred height to height.
void setPreferredSize (const QSizeF &size)
Sets the preferred size to size.
void setPreferredSize (qreal w, qreal h)
This convenience function is equivalent to calling setPreferredSize(QSizeF(w, h)).
void setPreferredWidth (qreal width)
Sets the preferred width to width.
void setSizePolicy (const QSizePolicy &policy)
Sets the size policy to policy.
void setSizePolicy (QSizePolicy::Policy hPolicy, QSizePolicy::Policy vPolicy, QSizePolicy::ControlType controlType=QSizePolicy::DefaultType)
This function is equivalent to calling setSizePolicy(QSizePolicy(hPolicy, vPolicy, controlType)).
QSizePolicy sizePolicy () const
Returns the current size policy.
virtual void updateGeometry ()
This virtual function discards any cached size hint information.
virtual ~QGraphicsLayoutItem ()
Destroys the QGraphicsLayoutItem object.
Protected Functions
QGraphicsLayoutItem (QGraphicsLayoutItemPrivate &dd)
void setGraphicsItem (QGraphicsItem *item)
If the QGraphicsLayoutItem represents a QGraphicsItem, and it wants to take advantage of the automatic reparenting capabilities of QGraphicsLayout it should set this value.
void setOwnedByLayout (bool ownedByLayout)
Sets whether a layout should delete this item in its destructor or not.
virtual QSizeF sizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const =0
This pure virtual function returns the size hint for which of the QGraphicsLayoutItem, using the width or height of constraint to constrain the output.
Protected Variables
QScopedPointer< QGraphicsLayoutItemPrivate > d_ptr
Private Functions
QSizeF * effectiveSizeHints (const QSizeF &constraint) const
Friends
class QGraphicsLayout
Detailed Description
The QGraphicsLayoutItem class can be inherited to allow your custom items to be managed by layouts.
Since
4.4
QGraphicsLayoutItem is an abstract class that defines a set of virtual functions describing sizes, size policies, and size hints for any object arranged by QGraphicsLayout. The API contains functions relevant for both the item itself and for the user of the item as most of QGraphicsLayoutItem's functions are also part of the subclass' public API.
In most cases, existing layout-aware classes such as QGraphicsWidget and QGraphicsLayout already provide the functionality you require. However, subclassing these classes will enable you to create both graphical elements that work well with layouts (QGraphicsWidget) or custom layouts (QGraphicsLayout).
Subclassing QGraphicsLayoutItem
If you create a subclass of QGraphicsLayoutItem and reimplement its virtual functions, you will enable the layout to resize and position your item along with other QGraphicsLayoutItems including QGraphicsWidget and QGraphicsLayout.
You can start by reimplementing important functions: the protected sizeHint() function, as well as the public setGeometry() function. If you want your items to be aware of immediate geometry changes, you can also reimplement updateGeometry().
The geometry, size hint, and size policy affect the item's size and position. Calling setGeometry() will always resize and reposition the item immediately. Normally, this function is called by QGraphicsLayout after the layout has been activated, but it can also be called by the item's user at any time.
The sizeHint() function returns the item' minimum, preferred and maximum size hints. You can override these properties by calling setMinimumSize(), setPreferredSize() or setMaximumSize(). You can also use functions such as setMinimumWidth() or setMaximumHeight() to set only the width or height component if desired.
The effectiveSizeHint() function, on the other hand, returns a size hint for any given Qt::SizeHint, and guarantees that the returned size is bound to the minimum and maximum sizes and size hints. You can set the item's vertical and horizontal size policy by calling setSizePolicy(). The sizePolicy property is used by the layout system to describe how this item prefers to grow or shrink.
Nesting QGraphicsLayoutItems
QGraphicsLayoutItems can be nested within other QGraphicsLayoutItems, similar to layouts that can contain sublayouts. This is done either by passing a QGraphicsLayoutItem pointer to QGraphicsLayoutItem's protected constructor, or by calling setParentLayoutItem(). The parentLayoutItem() function returns a pointer to the item's layoutItem parent. If the item's parent is 0 or if the parent does not inherit from QGraphicsItem, the parentLayoutItem() function then returns 0. isLayout() returns true if the QGraphicsLayoutItem subclass is itself a layout, or false otherwise.
Qt uses QGraphicsLayoutItem to provide layout functionality in the Graphics View Framework, but in the future its use may spread throughout Qt itself.
See also
QGraphicsWidget, QGraphicsLayout, QGraphicsLinearLayout, QGraphicsGridLayout
Definition at line 59 of file qgraphicslayoutitem.h.
Constructors and Destructors
QGraphicsLayoutItem() [1/2]
QGraphicsLayoutItem::QGraphicsLayoutItem (QGraphicsLayoutItem * parent = 0, bool isLayout = false)
Constructs the QGraphicsLayoutItem object.
parent becomes the object's parent. If isLayout is true the item is a layout, otherwise isLayout is false.
Definition at line 473 of file qgraphicslayoutitem.cpp.
     : d_ptr(new QGraphicsLayoutItemPrivate(parent, isLayout))
 {
     Q_D(QGraphicsLayoutItem);
     d->init();
     d->sizePolicy = QSizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
     d->q_ptr = this;
 }
~QGraphicsLayoutItem()
QGraphicsLayoutItem::~QGraphicsLayoutItem () virtual
Destroys the QGraphicsLayoutItem object.
Definition at line 496 of file qgraphicslayoutitem.cpp.
 {
     QGraphicsLayoutItem *parentLI = parentLayoutItem();
     if (parentLI && parentLI->isLayout()) {
         QGraphicsLayout *lay = static_cast<QGraphicsLayout*>(parentLI);
         // this is not optimal
         for (int i = lay->count() - 1; i >= 0; --i) {
             if (lay->itemAt(i) == this) {
                 lay->removeAt(i);
                 break;
             }
         }
     }
 }
QGraphicsLayoutItem() [2/2]
QGraphicsLayoutItem::QGraphicsLayoutItem (QGraphicsLayoutItemPrivate & dd) protected
Warning
This function is not part of the public interface.
Definition at line 485 of file qgraphicslayoutitem.cpp.
     : d_ptr(&dd)
 {
     Q_D(QGraphicsLayoutItem);
     d->init();
     d->q_ptr = this;
 }
Functions
contentsRect()
QRectF QGraphicsLayoutItem::contentsRect () const
Returns the contents rect in local coordinates.
The contents rect defines the subrectangle used by an associated layout when arranging subitems. This function is a convenience function that adjusts the item's geometry() by its contents margins. Note that getContentsMargins() is a virtual function that you can reimplement to return the item's contents margins.
See also
getContentsMargins(), geometry()
Definition at line 890 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayout::activate(), and QGraphicsLayout::widgetEvent().
 {
     qreal left, top, right, bottom;
     getContentsMargins(&left, &top, &right, &bottom);
     return QRectF(QPointF(), geometry().size()).adjusted(+left, +top, -right, -bottom);
 }
effectiveSizeHint()
QSizeF QGraphicsLayoutItem::effectiveSizeHint (Qt::SizeHint which, const QSizeF & constraint = QSizeF()) const
Returns the effective size hint for this QGraphicsLayoutItem.
which is the size hint in question. constraint is an optional argument that defines a special constrain when calculating the effective size hint. By default, constraint is QSizeF(-1, -1), which means there is no constraint to the size hint.
If you want to specify the widget's size hint for a given width or height, you can provide the fixed dimension in constraint. This is useful for widgets that can grow only either vertically or horizontally, and need to set either their width or their height to a special value.
For example, a text paragraph item fit into a column width of 200 may grow vertically. You can pass QSizeF(200, -1) as a constraint to get a suitable minimum, preferred and maximum height).
You can adjust the effective size hint by reimplementing sizeHint() in a QGraphicsLayoutItem subclass, or by calling one of the following functions: setMinimumSize(), setPreferredSize, or setMaximumSize() (or a combination of both).
This function caches each of the size hints and guarantees that sizeHint() will be called only once for each value of which - unless constraint is not specified and updateGeometry() has been called.
See also
sizeHint()
Definition at line 925 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsWidget::adjustSize(), QGridLayoutItem::effectiveMaxSize(), maximumSize(), minimumHeightForWidth(), minimumSize(), preferredSize(), setGeometry(), QGraphicsWidget::setGeometry(), QGraphicsAnchorLayoutPrivate::setItemsGeometries(), and QGridLayoutItem::sizeHint().
 {
     Q_D(const QGraphicsLayoutItem);
     if (!d->userSizeHints && constraint.isValid())
         return constraint;
     // ### should respect size policy???
     return d_ptr->effectiveSizeHints(constraint)[which];
 }
effectiveSizeHints()
QSizeF* QGraphicsLayoutItem::effectiveSizeHints (const QSizeF & constraint) const private
geometry()
QRectF QGraphicsLayoutItem::geometry () const
Returns the item's geometry (e.
g., position and size) as a QRectF. This function is equivalent to QRectF(pos(), size()).
See also
setGeometry()
Definition at line 853 of file qgraphicslayoutitem.cpp.
Referenced by contentsRect(), QGraphicsLinearLayout::setGeometry(), QGraphicsGridLayout::setGeometry(), QGraphicsWidget::windowFrameGeometry(), and QGraphicsWidget::~QGraphicsWidget().
 {
     Q_D(const QGraphicsLayoutItem);
     return d->geom;
 }
getContentsMargins()
void QGraphicsLayoutItem::getContentsMargins (qreal * left, qreal * top, qreal * right, qreal * bottom) const virtual
This virtual function provides the left, top, right and bottom contents margins for this QGraphicsLayoutItem.
The default implementation assumes all contents margins are 0. The parameters point to values stored in qreals. If any of the pointers is 0, that value will not be updated.
See also
QGraphicsWidget::setContentsMargins()
Reimplemented in QGraphicsWidget, and QGraphicsLayout.
Definition at line 867 of file qgraphicslayoutitem.cpp.
Referenced by contentsRect(), and QGraphicsWidget::rect().
 {
     if (left)
         *left = 0;
     if (top)
         *top = 0;
     if (right)
         *right = 0;
     if (bottom)
         *bottom = 0;
 }
graphicsItem()
QGraphicsItem * QGraphicsLayoutItem::graphicsItem () const
Returns the QGraphicsItem that this layout item represents.
For QGraphicsWidget it will return itself. For custom items it can return an aggregated value.
See also
setGraphicsItem()
Definition at line 1039 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayoutPrivate::addChildLayoutItem(), QGraphicsLayoutItemPrivate::parentItem(), QGraphicsLayout::QGraphicsLayout(), QGraphicsLayoutPrivate::reparentChildItems(), QGraphicsAnchorLayoutPrivate::styleInfo(), and AnchorVertex::toString().
 {
     return d_func()->graphicsItem;
 }
isLayout()
bool QGraphicsLayoutItem::isLayout () const
Returns true if this QGraphicsLayoutItem is a layout (e.g., is inherited by an object that arranges other QGraphicsLayoutItem objects); otherwise returns false.
See also
QGraphicsLayout
Definition at line 981 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayout::activate(), QGraphicsLayoutPrivate::activateRecursive(), QGraphicsLayoutPrivate::addChildLayoutItem(), QGraphicsLayoutPrivate::getMargin(), QGraphicsLayout::invalidate(), QGraphicsLayoutItemPrivate::parentItem(), QGraphicsLayout::QGraphicsLayout(), removeLayoutItemFromLayout(), QGraphicsLayoutPrivate::reparentChildItems(), QGraphicsAnchorLayoutPrivate::styleInfo(), AnchorVertex::toString(), QGraphicsLayout::updateGeometry(), QGraphicsWidget::updateGeometry(), and ~QGraphicsLayoutItem().
 {
     return d_func()->isLayout;
 }
maximumHeight()
qreal QGraphicsLayoutItem::maximumHeight () const inline
Returns the maximum height.
See also
setMaximumHeight(), setMaximumSize(), maximumSize()
Definition at line 146 of file qgraphicslayoutitem.h.
 { return effectiveSizeHint(Qt::MaximumSize).height(); }
maximumSize()
QSizeF QGraphicsLayoutItem::maximumSize () const
Returns the maximum size.
See also
setMaximumSize(), minimumSize(), preferredSize(), Qt::MaximumSize, sizeHint()
Definition at line 723 of file qgraphicslayoutitem.cpp.
 {
     return effectiveSizeHint(Qt::MaximumSize);
 }
maximumWidth()
qreal QGraphicsLayoutItem::maximumWidth () const inline
Returns the maximum width.
See also
setMaximumWidth(), setMaximumSize(), maximumSize()
Definition at line 144 of file qgraphicslayoutitem.h.
 { return effectiveSizeHint(Qt::MaximumSize).width(); }
minimumHeight()
qreal QGraphicsLayoutItem::minimumHeight () const inline
Returns the minimum height.
See also
setMinimumHeight(), setMinimumSize(), minimumSize()
Definition at line 136 of file qgraphicslayoutitem.h.
 { return effectiveSizeHint(Qt::MinimumSize).height(); }
minimumSize()
QSizeF QGraphicsLayoutItem::minimumSize () const
Returns the minimum size.
See also
setMinimumSize(), preferredSize(), maximumSize(), Qt::MinimumSize, sizeHint()
Definition at line 609 of file qgraphicslayoutitem.cpp.
 {
     return effectiveSizeHint(Qt::MinimumSize);
 }
minimumWidth()
qreal QGraphicsLayoutItem::minimumWidth () const inline
Returns the minimum width.
See also
setMinimumWidth(), setMinimumSize(), minimumSize()
Definition at line 134 of file qgraphicslayoutitem.h.
 { return effectiveSizeHint(Qt::MinimumSize).width(); }
ownedByLayout()
bool QGraphicsLayoutItem::ownedByLayout () const
Returns whether a layout should delete this item in its destructor.
Since
4.6
If its true, then the layout will delete it. If its false, then it is assumed that another object has the ownership of it, and the layout won't delete this item.
If the item inherits both QGraphicsItem and QGraphicsLayoutItem (such as QGraphicsWidget does) the item is really part of two ownership hierarchies. This property informs what the layout should do with its child items when it is destructed. In the case of QGraphicsWidget, it is preferred that when the layout is deleted it won't delete its children (since they are also part of the graphics item hierarchy).
By default this value is initialized to false in QGraphicsLayoutItem, but it is overridden by QGraphicsLayout to return true. This is because QGraphicsLayout is not normally part of the QGraphicsItem hierarchy, so the parent layout should delete it. Subclasses might override this default behaviour by calling setOwnedByLayout(true).
See also
setOwnedByLayout()
Definition at line 1013 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsAnchorLayout::~QGraphicsAnchorLayout(), QGraphicsGridLayout::~QGraphicsGridLayout(), and QGraphicsLinearLayout::~QGraphicsLinearLayout().
 {
     return d_func()->ownedByLayout;
 }
parentLayoutItem()
QGraphicsLayoutItem * QGraphicsLayoutItem::parentLayoutItem () const
Returns the parent of this QGraphicsLayoutItem, or 0 if there is no parent, or if the parent does not inherit from QGraphicsLayoutItem (QGraphicsLayoutItem is often used through multiple inheritance with QObject-derived classes).
See also
setParentLayoutItem()
Definition at line 959 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayout::activate(), QGraphicsLayoutPrivate::addChildLayoutItem(), QGraphicsLayoutPrivate::getMargin(), QGraphicsLayout::invalidate(), QGraphicsLayoutItemPrivate::parentItem(), QGraphicsWidget::setLayout(), QGraphicsAnchorLayoutPrivate::styleInfo(), QGraphicsLayout::updateGeometry(), QGraphicsWidget::updateGeometry(), QGraphicsLayout::widgetEvent(), ~QGraphicsLayoutItem(), and QGraphicsWidget::~QGraphicsWidget().
 {
     return d_func()->parent;
 }
preferredHeight()
qreal QGraphicsLayoutItem::preferredHeight () const inline
Returns the preferred height.
See also
setPreferredHeight(), setPreferredSize(), preferredSize()
Definition at line 141 of file qgraphicslayoutitem.h.
 { return effectiveSizeHint(Qt::PreferredSize).height(); }
preferredSize()
QSizeF QGraphicsLayoutItem::preferredSize () const
Returns the preferred size.
See also
setPreferredSize(), minimumSize(), maximumSize(), Qt::PreferredSize, sizeHint()
Definition at line 666 of file qgraphicslayoutitem.cpp.
 {
     return effectiveSizeHint(Qt::PreferredSize);
 }
preferredWidth()
qreal QGraphicsLayoutItem::preferredWidth () const inline
Returns the preferred width.
See also
setPreferredWidth(), setPreferredSize(), preferredSize()
Definition at line 139 of file qgraphicslayoutitem.h.
 { return effectiveSizeHint(Qt::PreferredSize).width(); }
setGeometry()
void QGraphicsLayoutItem::setGeometry (const QRectF & rect) virtual
This virtual function sets the geometry of the QGraphicsLayoutItem to rect, which is in parent coordinates (e.
g., the top-left corner of rect is equivalent to the item's position in parent coordinates).
You must reimplement this function in a subclass of QGraphicsLayoutItem to receive geometry updates. The layout will call this function when it does a rearrangement.
If rect is outside of the bounds of minimumSize and maximumSize, it will be adjusted to its closest size so that it is within the legal bounds.
See also
geometry()
Reimplemented in QGraphicsGridLayout, QGraphicsWidget, QGraphicsAnchorLayout, QGraphicsLinearLayout, QDeclarativeLayoutItem, and QGraphicsProxyWidget.
Definition at line 834 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayout::activate(), QGraphicsLinearLayout::addStretch(), QGraphicsWidget::resize(), QGraphicsLinearLayout::setGeometry(), QGraphicsAnchorLayout::setGeometry(), QGraphicsWidget::setGeometry(), QGraphicsGridLayout::setGeometry(), QGridLayoutItem::setGeometry(), QGraphicsAnchorLayoutPrivate::setItemsGeometries(), and QGraphicsLayout::widgetEvent().
 {
     Q_D(QGraphicsLayoutItem);
     QSizeF effectiveSize = rect.size().expandedTo(effectiveSizeHint(Qt::MinimumSize))
                                 .boundedTo(effectiveSizeHint(Qt::MaximumSize));
     d->geom = QRectF(rect.topLeft(), effectiveSize);
 }
setGraphicsItem()
void QGraphicsLayoutItem::setGraphicsItem (QGraphicsItem * item) protected
If the QGraphicsLayoutItem represents a QGraphicsItem, and it wants to take advantage of the automatic reparenting capabilities of QGraphicsLayout it should set this value.
Note that if you delete item and not delete the layout item, you are responsible of calling setGraphicsItem(0) in order to avoid having a dangling pointer.
See also
graphicsItem()
Definition at line 1054 of file qgraphicslayoutitem.cpp.
Referenced by QDeclarativeLayoutItem::QDeclarativeLayoutItem().
 {
     d_func()->graphicsItem = item;
 }
setMaximumHeight()
void QGraphicsLayoutItem::setMaximumHeight (qreal height)
Sets the maximum height to height.
See also
maximumHeight(), setMaximumSize(), maximumSize()
Definition at line 743 of file qgraphicslayoutitem.cpp.
 {
     d_ptr->setSizeComponent(Qt::MaximumSize, d_ptr->Height, height);
 }
setMaximumSize() [1/2]
void QGraphicsLayoutItem::setMaximumSize (const QSizeF & size)
Sets the maximum size to size.
This property overrides sizeHint() for Qt::MaximumSize and ensures that effectiveSizeHint() will never return a size larger than size. In order to unset the maximum size, use an invalid size.
See also
maximumSize(), minimumSize(), preferredSize(), Qt::MaximumSize, sizeHint()
Definition at line 700 of file qgraphicslayoutitem.cpp.
 {
     d_ptr->setSize(Qt::MaximumSize, size);
 }
setMaximumSize() [2/2]
void QGraphicsLayoutItem::setMaximumSize (qreal w, qreal h) inline
This convenience function is equivalent to calling setMaximumSize(QSizeF(w, h)).
See also
maximumSize(), setMinimumSize(), setPreferredSize(), sizeHint()
Definition at line 131 of file qgraphicslayoutitem.h.
 { setMaximumSize(QSizeF(aw, ah)); }
setMaximumWidth()
void QGraphicsLayoutItem::setMaximumWidth (qreal width)
Sets the maximum width to width.
See also
maximumWidth(), setMaximumSize(), maximumSize()
Definition at line 733 of file qgraphicslayoutitem.cpp.
 {
     d_ptr->setSizeComponent(Qt::MaximumSize, d_ptr->Width, width);
 }
setMinimumHeight()
void QGraphicsLayoutItem::setMinimumHeight (qreal height)
Sets the minimum height to height.
See also
minimumHeight(), setMinimumSize(), minimumSize()
Definition at line 629 of file qgraphicslayoutitem.cpp.
 {
     d_ptr->setSizeComponent(Qt::MinimumSize, d_ptr->Height, height);
 }
setMinimumSize() [1/2]
void QGraphicsLayoutItem::setMinimumSize (const QSizeF & size)
Sets the minimum size to size.
This property overrides sizeHint() for Qt::MinimumSize and ensures that effectiveSizeHint() will never return a size smaller than size. In order to unset the minimum size, use an invalid size.
See also
minimumSize(), maximumSize(), preferredSize(), Qt::MinimumSize, sizeHint(), setMinimumWidth(), setMinimumHeight()
Definition at line 586 of file qgraphicslayoutitem.cpp.
 {
     d_ptr->setSize(Qt::MinimumSize, size);
 }
setMinimumSize() [2/2]
void QGraphicsLayoutItem::setMinimumSize (qreal w, qreal h) inline
This convenience function is equivalent to calling setMinimumSize(QSizeF(w, h)).
See also
minimumSize(), setMaximumSize(), setPreferredSize(), sizeHint()
Definition at line 127 of file qgraphicslayoutitem.h.
 { setMinimumSize(QSizeF(aw, ah)); }
setMinimumWidth()
void QGraphicsLayoutItem::setMinimumWidth (qreal width)
Sets the minimum width to width.
See also
minimumWidth(), setMinimumSize(), minimumSize()
Definition at line 619 of file qgraphicslayoutitem.cpp.
 {
     d_ptr->setSizeComponent(Qt::MinimumSize, d_ptr->Width, width);
 }
setOwnedByLayout()
void QGraphicsLayoutItem::setOwnedByLayout (bool ownership) protected
Sets whether a layout should delete this item in its destructor or not.
Since
4.6
ownership must be true to in order for the layout to delete it.
See also
ownedByLayout()
Definition at line 1027 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayout::QGraphicsLayout().
 {
     d_func()->ownedByLayout = ownership;
 }
setParentLayoutItem()
void QGraphicsLayoutItem::setParentLayoutItem (QGraphicsLayoutItem * parent)
Sets the parent of this QGraphicsLayoutItem to parent.
See also
parentLayoutItem()
Definition at line 969 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayoutPrivate::addChildLayoutItem(), QGraphicsLayout::QGraphicsLayout(), QGraphicsAnchorLayout::removeAt(), QGraphicsLinearLayout::removeItem(), QGraphicsWidget::setLayout(), QGraphicsGridLayout::~QGraphicsGridLayout(), QGraphicsLinearLayout::~QGraphicsLinearLayout(), and QGraphicsWidget::~QGraphicsWidget().
 {
     d_func()->parent = parent;
 }
setPreferredHeight()
void QGraphicsLayoutItem::setPreferredHeight (qreal height)
Sets the preferred height to height.
See also
preferredWidth(), setPreferredSize(), preferredSize()
Definition at line 676 of file qgraphicslayoutitem.cpp.
 {
     d_ptr->setSizeComponent(Qt::PreferredSize, d_ptr->Height, height);
 }
setPreferredSize() [1/2]
void QGraphicsLayoutItem::setPreferredSize (const QSizeF & size)
Sets the preferred size to size.
This property overrides sizeHint() for Qt::PreferredSize and provides the default value for effectiveSizeHint(). In order to unset the preferred size, use an invalid size.
See also
preferredSize(), minimumSize(), maximumSize(), Qt::PreferredSize, sizeHint()
Definition at line 643 of file qgraphicslayoutitem.cpp.
 {
     d_ptr->setSize(Qt::PreferredSize, size);
 }
setPreferredSize() [2/2]
void QGraphicsLayoutItem::setPreferredSize (qreal w, qreal h) inline
This convenience function is equivalent to calling setPreferredSize(QSizeF(w, h)).
See also
preferredSize(), setMaximumSize(), setMinimumSize(), sizeHint()
Definition at line 129 of file qgraphicslayoutitem.h.
 { setPreferredSize(QSizeF(aw, ah)); }
setPreferredWidth()
void QGraphicsLayoutItem::setPreferredWidth (qreal width)
Sets the preferred width to width.
See also
preferredHeight(), setPreferredSize(), preferredSize()
Definition at line 686 of file qgraphicslayoutitem.cpp.
 {
     d_ptr->setSizeComponent(Qt::PreferredSize, d_ptr->Width, width);
 }
setSizePolicy() [1/2]
void QGraphicsLayoutItem::setSizePolicy (const QSizePolicy & policy)
Sets the size policy to policy.
The size policy describes how the item should grow horizontally and vertically when arranged in a layout.
QGraphicsLayoutItem's default size policy is (QSizePolicy::Fixed, QSizePolicy::Fixed, QSizePolicy::DefaultType), but it is common for subclasses to change the default. For example, QGraphicsWidget defaults to (QSizePolicy::Preferred, QSizePolicy::Preferred, QSizePolicy::DefaultType).
See also
sizePolicy(), QWidget::sizePolicy()
Definition at line 539 of file qgraphicslayoutitem.cpp.
Referenced by setSizePolicy().
 {
     Q_D(QGraphicsLayoutItem);
     if (d->sizePolicy == policy)
         return;
     d->sizePolicy = policy;
     updateGeometry();
 }
setSizePolicy() [2/2]
void QGraphicsLayoutItem::setSizePolicy (QSizePolicy::Policy hPolicy, QSizePolicy::Policy vPolicy, QSizePolicy::ControlType controlType = QSizePolicy::DefaultType)
This function is equivalent to calling setSizePolicy(QSizePolicy(hPolicy, vPolicy, controlType)).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
sizePolicy(), QWidget::sizePolicy()
Definition at line 559 of file qgraphicslayoutitem.cpp.
 {
     setSizePolicy(QSizePolicy(hPolicy, vPolicy, controlType));
 }
sizeHint()
QSizeF QGraphicsLayoutItem::sizeHint (Qt::SizeHint which, const QSizeF & constraint = QSizeF()) const protected pure virtual
This pure virtual function returns the size hint for which of the QGraphicsLayoutItem, using the width or height of constraint to constrain the output.
Reimplement this function in a subclass of QGraphicsLayoutItem to provide the necessary size hints for your items.
See also
effectiveSizeHint()
Implemented in QGraphicsWidget, QGraphicsProxyWidget, QGraphicsGridLayout, QGraphicsAnchorLayout, QGraphicsLinearLayout, and QDeclarativeLayoutItem.
Referenced by QGraphicsLinearLayout::addStretch().
sizePolicy()
QSizePolicy QGraphicsLayoutItem::sizePolicy () const
Returns the current size policy.
See also
setSizePolicy(), QWidget::sizePolicy()
Definition at line 571 of file qgraphicslayoutitem.cpp.
Referenced by QGridLayoutItem::controlTypes(), and QGridLayoutItem::sizePolicy().
 {
     Q_D(const QGraphicsLayoutItem);
     return d->sizePolicy;
 }
updateGeometry()
void QGraphicsLayoutItem::updateGeometry () virtual
This virtual function discards any cached size hint information.
You should always call this function if you change the return value of the sizeHint() function. Subclasses must always call the base implementation when reimplementing this function.
See also
effectiveSizeHint()
Reimplemented in QGraphicsWidget, and QGraphicsLayout.
Definition at line 944 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayout::activate(), setSizePolicy(), QGraphicsLayout::updateGeometry(), and QGraphicsWidget::updateGeometry().
 {
     Q_D(QGraphicsLayoutItem);
     d->sizeHintCacheDirty = true;
     d->sizeHintWithConstraintCacheDirty = true;
 }
Friends and Related Functions
QGraphicsLayout
friend class QGraphicsLayout friend
Definition at line 122 of file qgraphicslayoutitem.h.
Properties
d_ptr
QScopedPointer<QGraphicsLayoutItemPrivate> QGraphicsLayoutItem::d_ptr protected
Definition at line 116 of file qgraphicslayoutitem.h.
Referenced by effectiveSizeHint(), QGraphicsWidget::setGeometry(), setMaximumHeight(), setMaximumSize(), setMaximumWidth(), setMinimumHeight(), setMinimumSize(), setMinimumWidth(), setPreferredHeight(), setPreferredSize(), setPreferredWidth(), and QGraphicsViewPrivate::updateInputMethodSensitivity().
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicslayoutitem.h
/src/gui/graphicsview/qgraphicslayoutitem.cpp