Qt 4.8: QPdfBaseEngine Class Reference
QPdfBaseEngine Class Reference abstract
#include <qpdf_p.h>
Public Functions
bool begin (QPaintDevice *pdev)
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the buffer points.
void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
void drawTextItem (const QPointF &p, const QTextItem &textItem)
This function draws the text item textItem at position p.
bool end ()
Reimplement this function to finish painting on the current paint device.
int metric (QPaintDevice::PaintDeviceMetric metricType) const
Returns the metric for the given id.
bool newPage ()
Instructs the print engine to start a new page.
QVariant property (PrintEnginePropertyKey key) const
Returns the print engine's property specified by key.
QPdfBaseEngine (QPdfBaseEnginePrivate &d, PaintEngineFeatures f)
virtual void setBrush ()=0
void setPen ()
void setProperty (PrintEnginePropertyKey key, const QVariant &value)
Sets the print engine's property specified by key to the given value.
void setupGraphicsState (QPaintEngine::DirtyFlags flags)
void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
~QPdfBaseEngine ()
Public Functions inherited from QAlphaPaintEngine
virtual void drawImage (const QRectF &r, const QImage &image, const QRectF &sr)
virtual void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
virtual void drawTiledPixmap (const QRectF &r, const QPixmap &pixmap, const QPointF &s)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
~QAlphaPaintEngine ()
Public Functions inherited from QPaintEngine
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
virtual void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
virtual void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
virtual void drawImage (const QRectF &r, const QImage &pm, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
virtual void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
virtual void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual Type type () const =0
Reimplement this function to return the paint engine Type.
virtual ~QPaintEngine ()
Destroys the paint engine.
Public Functions inherited from QPrintEngine
virtual bool abort ()=0
Instructs the print engine to abort the printing process.
virtual HDC getPrinterDC () const
virtual QPrinter::PrinterState printerState () const =0
Returns the current state of the printer being used by the print engine.
virtual void releasePrinterDC (HDC) const
virtual ~QPrintEngine ()
Destroys the print engine.
Private Functions
void updateClipPath (const QPainterPath &path, Qt::ClipOperation op)
Additional Inherited Members
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Public Types inherited from QPrintEngine
enum PrintEnginePropertyKey {
PPK_CollateCopies, PPK_ColorMode, PPK_Creator, PPK_DocumentName,
PPK_FullPage, PPK_NumberOfCopies, PPK_Orientation, PPK_OutputFileName,
PPK_PageOrder, PPK_PageRect, PPK_PageSize, PPK_PaperRect,
PPK_PaperSource, PPK_PrinterName, PPK_PrinterProgram, PPK_Resolution,
PPK_SelectionOption, PPK_SupportedResolutions, PPK_WindowsPageSize, PPK_FontEmbedding,
PPK_SuppressSystemPrintStatus, PPK_Duplex, PPK_PaperSources, PPK_CustomPaperSize,
PPK_PageMargins, PPK_CopyCount, PPK_SupportsMultipleCopies, PPK_PaperSize = PPK_PageSize,
PPK_CustomBase = 0xff00
}
This enum is used to communicate properties between the print engine and QPrinter.
Protected Functions inherited from QAlphaPaintEngine
QRegion alphaClipping () const
void cleanUp ()
bool continueCall () const
void flushAndInit (bool init=true)
QAlphaPaintEngine (QAlphaPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 182 of file qpdf_p.h.
Constructors and Destructors
QPdfBaseEngine()
QPdfBaseEngine::QPdfBaseEngine (QPdfBaseEnginePrivate & d, PaintEngineFeatures f)
Definition at line 919 of file qpdf.cpp.
     : QAlphaPaintEngine(dd, f)
 {
     Q_D(QPdfBaseEngine);
 #if !defined(QT_NO_CUPS) && !defined(QT_NO_LIBRARY)
     if (QCUPSSupport::isAvailable()) {
         QCUPSSupport cups;
         const cups_dest_t* printers = cups.availablePrinters();
         int prnCount = cups.availablePrintersCount();
         for (int i = 0; i <  prnCount; ++i) {
             if (printers[i].is_default) {
                 d->printerName = QString::fromLocal8Bit(printers[i].name);
                 break;
             }
         }
     } else
 #endif
     {
         d->printerName = QString::fromLocal8Bit(qgetenv("PRINTER"));
         if (d->printerName.isEmpty())
             d->printerName = QString::fromLocal8Bit(qgetenv("LPDEST"));
         if (d->printerName.isEmpty())
             d->printerName = QString::fromLocal8Bit(qgetenv("NPRINTER"));
         if (d->printerName.isEmpty())
             d->printerName = QString::fromLocal8Bit(qgetenv("NGPRINTER"));
     }
 }
~QPdfBaseEngine()
QPdfBaseEngine::~QPdfBaseEngine () inline
Definition at line 187 of file qpdf_p.h.
 {}
Functions
begin()
bool QPdfBaseEngine::begin (QPaintDevice * pdev) virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Reimplemented from QAlphaPaintEngine.
Reimplemented in QPdfEngine, and QPSPrintEngine.
Definition at line 1617 of file qpdf.cpp.
Referenced by QPSPrintEngine::begin(), and QPdfEngine::begin().
 {
     Q_D(QPdfBaseEngine);
     d->pdev = pdev;
     d->postscript = false;
     d->currentObject = 1;
     d->currentPage = new QPdfPage;
     d->stroker.stream = d->currentPage;
     d->opacity = 1.0;
     return d->openPrintDevice();
 }
drawLines()
void QPdfBaseEngine::drawLines (const QLineF * lines, int lineCount) virtual
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngine.
Definition at line 967 of file qpdf.cpp.
 {
     if (!lines)
         return;
     Q_D(QPdfBaseEngine);
     QPainterPath p;
     for (int i=0; i!=lineCount;++i) {
         p.moveTo(lines[i].p1());
         p.lineTo(lines[i].p2());
     }
     bool hadBrush = d->hasBrush;
     d->hasBrush = false;
     drawPath(p);
     d->hasBrush = hadBrush;
 }
drawPath()
void QPdfBaseEngine::drawPath (const QPainterPath & path) virtual
The default implementation ignores the path and does nothing.
Reimplemented from QAlphaPaintEngine.
Definition at line 1061 of file qpdf.cpp.
Referenced by drawLines(), drawPoints(), drawPolygon(), and drawRects().
 {
     Q_D(QPdfBaseEngine);
     if (d->useAlphaEngine) {
         QAlphaPaintEngine::drawPath(p);
         if (!continueCall())
             return;
     }
     if (d->clipEnabled && d->allClipped)
         return;
     if (!d->hasPen && !d->hasBrush)
         return;
     if (d->simplePen) {
         // draw strokes natively in this case for better output
         *d->currentPage << QPdf::generatePath(p, QTransform(), d->hasBrush ? QPdf::FillAndStrokePath : QPdf::StrokePath);
     } else {
         if (d->hasBrush)
             *d->currentPage << QPdf::generatePath(p, d->stroker.matrix, QPdf::FillPath);
         if (d->hasPen) {
             *d->currentPage << "q\n";
             QBrush b = d->brush;
             d->brush = d->pen.brush();
             setBrush();
             d->stroker.strokePath(p);
             *d->currentPage << "Q\n";
             d->brush = b;
         }
     }
 }
drawPoints()
void QPdfBaseEngine::drawPoints (const QPointF * points, int pointCount) virtual
Draws the first pointCount points in the buffer points.
Reimplemented from QPaintEngine.
Definition at line 949 of file qpdf.cpp.
 {
     if (!points)
         return;
     Q_D(QPdfBaseEngine);
     QPainterPath p;
     for (int i=0; i!=pointCount;++i) {
         p.moveTo(points[i]);
         p.lineTo(points[i] + QPointF(0, 0.001));
     }
     bool hadBrush = d->hasBrush;
     d->hasBrush = false;
     drawPath(p);
     d->hasBrush = hadBrush;
 }
drawPolygon()
void QPdfBaseEngine::drawPolygon (const QPointF * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QAlphaPaintEngine.
Definition at line 1019 of file qpdf.cpp.
 {
     Q_D(QPdfBaseEngine);
     if (d->useAlphaEngine) {
         QAlphaPaintEngine::drawPolygon(points, pointCount, mode);
         if (!continueCall())
             return;
     }
     if (!points || !pointCount)
         return;
     bool hb = d->hasBrush;
     QPainterPath p;
     switch(mode) {
         case OddEvenMode:
             p.setFillRule(Qt::OddEvenFill);
             break;
         case ConvexMode:
         case WindingMode:
             p.setFillRule(Qt::WindingFill);
             break;
         case PolylineMode:
             d->hasBrush = false;
             break;
         default:
             break;
     }
     p.moveTo(points[0]);
     for (int i = 1; i < pointCount; ++i)
         p.lineTo(points[i]);
     if (mode != PolylineMode)
         p.closeSubpath();
     drawPath(p);
     d->hasBrush = hb;
 }
drawRects()
void QPdfBaseEngine::drawRects (const QRectF * rects, int rectCount) virtual
Draws the first rectCount rectangles in the buffer rects.
The default implementation of this function calls drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngine.
Definition at line 984 of file qpdf.cpp.
Referenced by QPdfEngine::drawTiledPixmap().
 {
     if (!rects)
         return;
     Q_D(QPdfBaseEngine);
     if (d->useAlphaEngine) {
         QAlphaPaintEngine::drawRects(rects, rectCount);
         if (!continueCall())
             return;
     }
     if (d->clipEnabled && d->allClipped)
         return;
     if (!d->hasPen && !d->hasBrush)
         return;
     QBrush penBrush = d->pen.brush();
     if (d->simplePen || !d->hasPen) {
         // draw strokes natively in this case for better output
         if(!d->simplePen && !d->stroker.matrix.isIdentity())
             *d->currentPage << "q\n" << QPdf::generateMatrix(d->stroker.matrix);
         for (int i = 0; i < rectCount; ++i)
             *d->currentPage << rects[i].x() << rects[i].y() << rects[i].width() << rects[i].height() << "re\n";
         *d->currentPage << (d->hasPen ? (d->hasBrush ? "B\n" : "S\n") : "f\n");
         if(!d->simplePen && !d->stroker.matrix.isIdentity())
             *d->currentPage << "Q\n";
     } else {
         QPainterPath p;
         for (int i=0; i!=rectCount; ++i)
             p.addRect(rects[i]);
         drawPath(p);
     }
 }
drawTextItem()
void QPdfBaseEngine::drawTextItem (const QPointF & p, const QTextItem & textItem) virtual
This function draws the text item textItem at position p.
The default implementation of this function converts the text to a QPainterPath and paints the resulting path.
Reimplemented from QAlphaPaintEngine.
Definition at line 1094 of file qpdf.cpp.
Referenced by QPdfEnginePrivate::height().
 {
     Q_D(QPdfBaseEngine);
     if (d->useAlphaEngine) {
         QAlphaPaintEngine::drawTextItem(p, textItem);
         if (!continueCall())
             return;
     }
     if (!d->hasPen || (d->clipEnabled && d->allClipped))
         return;
     if (d->stroker.matrix.type() >= QTransform::TxProject) {
         QPaintEngine::drawTextItem(p, textItem);
         return;
     }
     *d->currentPage << "q\n";
     if(!d->simplePen)
         *d->currentPage << QPdf::generateMatrix(d->stroker.matrix);
     bool hp = d->hasPen;
     d->hasPen = false;
     QBrush b = d->brush;
     d->brush = d->pen.brush();
     setBrush();
     const QTextItemInt &ti = static_cast<const QTextItemInt &>(textItem);
     Q_ASSERT(ti.fontEngine->type() != QFontEngine::Multi);
     d->drawTextItem(p, ti);
     d->hasPen = hp;
     d->brush = b;
     *d->currentPage << "Q\n";
 }
end()
bool QPdfBaseEngine::end () virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Reimplemented from QAlphaPaintEngine.
Reimplemented in QPdfEngine, and QPSPrintEngine.
Definition at line 1632 of file qpdf.cpp.
Referenced by QPSPrintEngine::end(), and QPdfEngine::end().
 {
     Q_D(QPdfBaseEngine);
     qDeleteAll(d->fonts);
     d->fonts.clear();
     delete d->currentPage;
     d->currentPage = 0;
     d->closePrintDevice();
     return true;
 }
metric()
int QPdfBaseEngine::metric (QPaintDevice::PaintDeviceMetric id) const virtual
Returns the metric for the given id.
Implements QPrintEngine.
Definition at line 1351 of file qpdf.cpp.
Referenced by QPSPrintEnginePrivate::emitHeader().
 {
     Q_D(const QPdfBaseEngine);
     int val;
     QRect r = d->fullPage ? d->paperRect() : d->pageRect();
     switch (metricType) {
     case QPaintDevice::PdmWidth:
         val = r.width();
         break;
     case QPaintDevice::PdmHeight:
         val = r.height();
         break;
     case QPaintDevice::PdmDpiX:
     case QPaintDevice::PdmDpiY:
         val = d->resolution;
         break;
     case QPaintDevice::PdmPhysicalDpiX:
     case QPaintDevice::PdmPhysicalDpiY:
         val = 1200;
         break;
     case QPaintDevice::PdmWidthMM:
         val = qRound(r.width()*25.4/d->resolution);
         break;
     case QPaintDevice::PdmHeightMM:
         val = qRound(r.height()*25.4/d->resolution);
         break;
     case QPaintDevice::PdmNumColors:
         val = INT_MAX;
         break;
     case QPaintDevice::PdmDepth:
         val = 32;
         break;
     default:
         qWarning("QPrinter::metric: Invalid metric command");
         return 0;
     }
     return val;
 }
newPage()
bool QPdfBaseEngine::newPage () virtual
Instructs the print engine to start a new page.
Returns true if the printer was able to create the new page; otherwise returns false.
Implements QPrintEngine.
Reimplemented in QPdfEngine, and QPSPrintEngine.
Definition at line 1340 of file qpdf.cpp.
Referenced by QPSPrintEngine::newPage(), and QPdfEngine::newPage().
 {
     Q_D(QPdfBaseEngine);
     setupGraphicsState(DirtyBrush|DirtyPen|DirtyClipPath);
     QFile *outfile = qobject_cast<QFile*> (d->outDevice);
     if (outfile && outfile->error() != QFile::NoError)
         return false;
     return true;
 }
property()
QVariant QPdfBaseEngine::property (PrintEnginePropertyKey key) const virtual
Returns the print engine's property specified by key.
See also
setProperty()
Implements QPrintEngine.
Definition at line 1478 of file qpdf.cpp.
 {
     Q_D(const QPdfBaseEngine);
     QVariant ret;
     switch (int(key)) {
     case PPK_CollateCopies:
         ret = d->collate;
         break;
     case PPK_ColorMode:
         ret = d->colorMode;
         break;
     case PPK_Creator:
         ret = d->creator;
         break;
     case PPK_DocumentName:
         ret = d->title;
         break;
     case PPK_FullPage:
         ret = d->fullPage;
         break;
     case PPK_CopyCount:
         ret = d->copies;
         break;
     case PPK_SupportsMultipleCopies:
 #if !defined(QT_NO_CUPS) && !defined(QT_NO_LIBRARY)
         if (QCUPSSupport::isAvailable())
             ret = true;
         else
 #endif
             ret = false;
         break;
     case PPK_NumberOfCopies:
 #if !defined(QT_NO_CUPS) && !defined(QT_NO_LIBRARY)
         if (QCUPSSupport::isAvailable())
             ret = 1;
         else
 #endif
             ret = d->copies;
         break;
     case PPK_Orientation:
         ret = d->orientation;
         break;
     case PPK_OutputFileName:
         ret = d->outputFileName;
         break;
     case PPK_PageOrder:
         ret = d->pageOrder;
         break;
     case PPK_PaperSize:
         ret = d->paperSize;
         break;
     case PPK_PaperSource:
         ret = d->paperSource;
         break;
     case PPK_PrinterName:
         ret = d->printerName;
         break;
     case PPK_PrinterProgram:
         ret = d->printProgram;
         break;
     case PPK_Resolution:
         ret = d->resolution;
         break;
     case PPK_SupportedResolutions:
         ret = QList<QVariant>() << 72;
         break;
     case PPK_PaperRect:
         ret = d->paperRect();
         break;
     case PPK_PageRect:
         ret = d->pageRect();
         break;
     case PPK_SelectionOption:
         ret = d->selectionOption;
         break;
     case PPK_FontEmbedding:
         ret = d->embedFonts;
         break;
     case PPK_Duplex:
         ret = d->duplex;
         break;
     case PPK_CupsPageRect:
         ret = d->cupsPageRect;
         break;
     case PPK_CupsPaperRect:
         ret = d->cupsPaperRect;
         break;
     case PPK_CupsOptions:
         ret = d->cupsOptions;
         break;
     case PPK_CupsStringPageSize:
         ret = d->cupsStringPageSize;
         break;
     case PPK_CustomPaperSize:
         ret = d->customPaperSize;
         break;
     case PPK_PageMargins:
     {
         QList<QVariant> margins;
         if (d->hasCustomPageMargins) {
             margins << d->leftMargin << d->topMargin
                     << d->rightMargin << d->bottomMargin;
         } else {
             const qreal defaultMargin = 10; // ~3.5 mm
             margins << defaultMargin << defaultMargin
                     << defaultMargin << defaultMargin;
         }
         ret = margins;
         break;
     }
     default:
         break;
     }
     return ret;
 }
setBrush()
virtual void QPdfBaseEngine::setBrush () pure virtual
Implemented in QPdfEngine, and QPSPrintEngine.
Referenced by drawPath(), drawTextItem(), and setupGraphicsState().
setPen()
void QPdfBaseEngine::setPen ()
Definition at line 1284 of file qpdf.cpp.
Referenced by setupGraphicsState().
 {
     Q_D(QPdfBaseEngine);
     if (d->pen.style() == Qt::NoPen)
         return;
     QBrush b = d->pen.brush();
     Q_ASSERT(b.style() == Qt::SolidPattern && b.isOpaque());
     QColor rgba = b.color();
     if (d->colorMode == QPrinter::GrayScale) {
         qreal gray = qGray(rgba.rgba())/255.;
         *d->currentPage << gray << gray << gray;
     } else {
         *d->currentPage << rgba.redF()
                         << rgba.greenF()
                         << rgba.blueF();
     }
     *d->currentPage << "SCN\n";
     *d->currentPage << d->pen.widthF() << "w ";
     int pdfCapStyle = 0;
     switch(d->pen.capStyle()) {
     case Qt::FlatCap:
         pdfCapStyle = 0;
         break;
     case Qt::SquareCap:
         pdfCapStyle = 2;
         break;
     case Qt::RoundCap:
         pdfCapStyle = 1;
         break;
     default:
         break;
     }
     *d->currentPage << pdfCapStyle << "J ";
     int pdfJoinStyle = 0;
     switch(d->pen.joinStyle()) {
     case Qt::MiterJoin:
         pdfJoinStyle = 0;
         break;
     case Qt::BevelJoin:
         pdfJoinStyle = 2;
         break;
     case Qt::RoundJoin:
         pdfJoinStyle = 1;
         break;
     default:
         break;
     }
     *d->currentPage << pdfJoinStyle << "j ";
     *d->currentPage << QPdf::generateDashes(d->pen) << " 0 d\n";
 }
setProperty()
void QPdfBaseEngine::setProperty (PrintEnginePropertyKey key, const QVariant & value) virtual
Sets the print engine's property specified by key to the given value.
See also
property()
Implements QPrintEngine.
Definition at line 1390 of file qpdf.cpp.
 {
     Q_D(QPdfBaseEngine);
     switch (int(key)) {
     case PPK_CollateCopies:
         d->collate = value.toBool();
         break;
     case PPK_ColorMode:
         d->colorMode = QPrinter::ColorMode(value.toInt());
         break;
     case PPK_Creator:
         d->creator = value.toString();
         break;
     case PPK_DocumentName:
         d->title = value.toString();
         break;
     case PPK_FullPage:
         d->fullPage = value.toBool();
         break;
     case PPK_CopyCount: // fallthrough
     case PPK_NumberOfCopies:
         d->copies = value.toInt();
         break;
     case PPK_Orientation:
         d->orientation = QPrinter::Orientation(value.toInt());
         break;
     case PPK_OutputFileName:
         d->outputFileName = value.toString();
         break;
     case PPK_PageOrder:
         d->pageOrder = QPrinter::PageOrder(value.toInt());
         break;
     case PPK_PaperSize:
         d->paperSize = QPrinter::PaperSize(value.toInt());
         break;
     case PPK_PaperSource:
         d->paperSource = QPrinter::PaperSource(value.toInt());
         break;
     case PPK_PrinterName:
         d->printerName = value.toString();
         break;
     case PPK_PrinterProgram:
         d->printProgram = value.toString();
         break;
     case PPK_Resolution:
         d->resolution = value.toInt();
         break;
     case PPK_SelectionOption:
         d->selectionOption = value.toString();
         break;
     case PPK_FontEmbedding:
         d->embedFonts = value.toBool();
         break;
     case PPK_Duplex:
         d->duplex = static_cast<QPrinter::DuplexMode> (value.toInt());
         break;
     case PPK_CupsPageRect:
         d->cupsPageRect = value.toRect();
         break;
     case PPK_CupsPaperRect:
         d->cupsPaperRect = value.toRect();
         break;
     case PPK_CupsOptions:
         d->cupsOptions = value.toStringList();
         break;
     case PPK_CupsStringPageSize:
         d->cupsStringPageSize = value.toString();
         break;
     case PPK_CustomPaperSize:
         d->paperSize = QPrinter::Custom;
         d->customPaperSize = value.toSizeF();
         break;
     case PPK_PageMargins:
     {
         QList<QVariant> margins(value.toList());
         Q_ASSERT(margins.size() == 4);
         d->leftMargin = margins.at(0).toReal();
         d->topMargin = margins.at(1).toReal();
         d->rightMargin = margins.at(2).toReal();
         d->bottomMargin = margins.at(3).toReal();
         d->hasCustomPageMargins = true;
         break;
     }
     default:
         break;
     }
 }
setupGraphicsState()
void QPdfBaseEngine::setupGraphicsState (QPaintEngine::DirtyFlags flags)
Definition at line 1193 of file qpdf.cpp.
Referenced by newPage(), and updateState().
 {
     Q_D(QPdfBaseEngine);
     if (flags & DirtyClipPath)
         flags |= DirtyTransform|DirtyPen|DirtyBrush;
     if (flags & DirtyTransform) {
         *d->currentPage << "Q\n";
         flags |= DirtyPen|DirtyBrush;
     }
     if (flags & DirtyClipPath) {
         *d->currentPage << "Q q\n";
         d->allClipped = false;
         if (d->clipEnabled && !d->clips.isEmpty()) {
             for (int i = 0; i < d->clips.size(); ++i) {
                 if (d->clips.at(i).isEmpty()) {
                     d->allClipped = true;
                     break;
                 }
             }
             if (!d->allClipped) {
                 for (int i = 0; i < d->clips.size(); ++i) {
                     *d->currentPage << QPdf::generatePath(d->clips.at(i), QTransform(), QPdf::ClipPath);
                 }
             }
         }
     }
     if (flags & DirtyTransform) {
         *d->currentPage << "q\n";
         if (d->simplePen && !d->stroker.matrix.isIdentity())
             *d->currentPage << QPdf::generateMatrix(d->stroker.matrix);
     }
     if (flags & DirtyBrush)
         setBrush();
     if (d->simplePen && (flags & DirtyPen))
         setPen();
 }
updateClipPath()
void QPdfBaseEngine::updateClipPath (const QPainterPath & path, Qt::ClipOperation op) private
Definition at line 1236 of file qpdf.cpp.
Referenced by updateState().
 {
     Q_D(QPdfBaseEngine);
     QPainterPath path = d->stroker.matrix.map(p);
     //qDebug() << "updateClipPath: " << d->stroker.matrix << p.boundingRect() << path.boundingRect() << op;
     if (op == Qt::NoClip) {
         d->clipEnabled = false;
         d->clips.clear();
     } else if (op == Qt::ReplaceClip) {
         d->clips.clear();
         d->clips.append(path);
     } else if (op == Qt::IntersectClip) {
         d->clips.append(path);
     } else { // UniteClip
         // ask the painter for the current clipping path. that's the easiest solution
         path = painter()->clipPath();
         path = d->stroker.matrix.map(path);
         d->clips.clear();
         d->clips.append(path);
     }
     if (d->useAlphaEngine) {
         // if we have an alpha region, we have to subtract that from the
         // any existing clip region since that region will be filled in
         // later with images
         QPainterPath alphaClip = qt_regionToPath(alphaClipping());
         if (!alphaClip.isEmpty()) {
             if (!d->clipEnabled) {
                 QRect r = d->fullPage ? d->paperRect() : d->pageRect();
                 QPainterPath dev;
                 dev.addRect(QRect(0, 0, r.width(), r.height()));
                 if (path.isEmpty())
                     path = dev;
                 else
                     path = path.intersected(dev);
                 d->clipEnabled = true;
             } else {
                 path = painter()->clipPath();
                 path = d->stroker.matrix.map(path);
             }
             path = path.subtracted(alphaClip);
             d->clips.clear();
             d->clips.append(path);
         }
     }
 }
updateState()
void QPdfBaseEngine::updateState (const QPaintEngineState & state) virtual
Reimplement this function to update the state of a paint engine.
When implemented, this function is responsible for checking the paint engine's current state and update the properties that are changed. Use the QPaintEngineState::state() function to find out which properties that must be updated, then use the corresponding GetFunction{get function} to retrieve the current values for the given properties.
See also
QPaintEngineState
Reimplemented from QAlphaPaintEngine.
Definition at line 1131 of file qpdf.cpp.
 {
     Q_D(QPdfBaseEngine);
     if (d->useAlphaEngine) {
         QAlphaPaintEngine::updateState(state);
         if (!continueCall())
             return;
     }
     QPaintEngine::DirtyFlags flags = state.state();
     if (flags & DirtyTransform)
         d->stroker.matrix = state.transform();
     if (flags & DirtyPen) {
         d->pen = state.pen();
         d->hasPen = d->pen.style() != Qt::NoPen;
         d->stroker.setPen(d->pen);
         QBrush penBrush = d->pen.brush();
         bool oldSimple = d->simplePen;
         d->simplePen = (d->hasPen && (penBrush.style() == Qt::SolidPattern) && penBrush.isOpaque());
         if (oldSimple != d->simplePen)
             flags |= DirtyTransform;
     }
     if (flags & DirtyBrush) {
         d->brush = state.brush();
         if (d->brush.color().alpha() == 0 && d->brush.style() == Qt::SolidPattern)
             d->brush.setStyle(Qt::NoBrush);
         d->hasBrush = d->brush.style() != Qt::NoBrush;
     }
     if (flags & DirtyBrushOrigin) {
         d->brushOrigin = state.brushOrigin();
         flags |= DirtyBrush;
     }
     if (flags & DirtyOpacity)
         d->opacity = state.opacity();
     bool ce = d->clipEnabled;
     if (flags & DirtyClipPath) {
         d->clipEnabled = true;
         updateClipPath(state.clipPath(), state.clipOperation());
     } else if (flags & DirtyClipRegion) {
         d->clipEnabled = true;
         QPainterPath path;
         QVector<QRect> rects = state.clipRegion().rects();
         for (int i = 0; i < rects.size(); ++i)
             path.addRect(rects.at(i));
         updateClipPath(path, state.clipOperation());
         flags |= DirtyClipPath;
     } else if (flags & DirtyClipEnabled) {
         d->clipEnabled = state.isClipEnabled();
     }
     if (ce != d->clipEnabled)
         flags |= DirtyClipPath;
     else if (!d->clipEnabled)
         flags &= ~DirtyClipPath;
     setupGraphicsState(flags);
 }
The documentation for this class was generated from the following files:
/src/gui/painting/qpdf_p.h
/src/gui/painting/qpdf.cpp