Qt 4.8: QPlatformEventLoopIntegration Class Reference
QPlatformEventLoopIntegration Class Reference abstract
#include <qplatformeventloopintegration_qpa.h>
Public Functions
qint64 nextTimerEvent () const
QPlatformEventLoopIntegration ()
virtual void qtNeedsToProcessEvents ()=0
virtual void quitEventLoop ()=0
void setNextTimerEvent (qint64 nextTimerEvent)
virtual void startEventLoop ()=0
virtual ~QPlatformEventLoopIntegration ()
Static Public Functions
static void processEvents ()
Protected Variables
QScopedPointer< QPlatformEventLoopIntegrationPrivate > d_ptr
Private Functions
Q_DECLARE_PRIVATE (QPlatformEventLoopIntegration)
Q_DISABLE_COPY (QPlatformEventLoopIntegration)
Friends
class QEventDispatcherQPA
Detailed Description
Definition at line 56 of file qplatformeventloopintegration_qpa.h.
Constructors and Destructors
QPlatformEventLoopIntegration()
QPlatformEventLoopIntegration::QPlatformEventLoopIntegration ()
Definition at line 60 of file qplatformeventloopintegration_qpa.cpp.
     : d_ptr(new QPlatformEventLoopIntegrationPrivate)
 {
 }
~QPlatformEventLoopIntegration()
QPlatformEventLoopIntegration::~QPlatformEventLoopIntegration () virtual
Definition at line 66 of file qplatformeventloopintegration_qpa.cpp.
 {
 }
Functions
nextTimerEvent()
qint64 QPlatformEventLoopIntegration::nextTimerEvent () const
Definition at line 70 of file qplatformeventloopintegration_qpa.cpp.
Referenced by setNextTimerEvent(), QOpenKODEEventLoopIntegration::startEventLoop(), and timerCallback().
 {
     Q_D(const QPlatformEventLoopIntegration);
     return d->nextTimerEvent;
 }
processEvents()
void QPlatformEventLoopIntegration::processEvents () static
Definition at line 83 of file qplatformeventloopintegration_qpa.cpp.
Referenced by kdprocessevent(), QOpenKODEEventLoopIntegration::startEventLoop(), timerCallback(), and wakeupCallback().
 {
     QCoreApplication::processEvents(QEventLoop::WaitForMoreEvents);
 }
Q_DECLARE_PRIVATE()
QPlatformEventLoopIntegration::Q_DECLARE_PRIVATE (QPlatformEventLoopIntegration) private
Q_DISABLE_COPY()
QPlatformEventLoopIntegration::Q_DISABLE_COPY (QPlatformEventLoopIntegration) private
qtNeedsToProcessEvents()
virtual void QPlatformEventLoopIntegration::qtNeedsToProcessEvents () pure virtual
Implemented in QUIKitEventLoop, QOpenKODEEventLoopIntegration, and QCocoaEventLoopIntegration.
quitEventLoop()
virtual void QPlatformEventLoopIntegration::quitEventLoop () pure virtual
Implemented in QUIKitEventLoop, QOpenKODEEventLoopIntegration, and QCocoaEventLoopIntegration.
setNextTimerEvent()
void QPlatformEventLoopIntegration::setNextTimerEvent (qint64 nextTimerEvent)
Definition at line 77 of file qplatformeventloopintegration_qpa.cpp.
 {
     Q_D(QPlatformEventLoopIntegration);
     d->nextTimerEvent = nextTimerEvent;
 }
startEventLoop()
virtual void QPlatformEventLoopIntegration::startEventLoop () pure virtual
Implemented in QUIKitEventLoop, QOpenKODEEventLoopIntegration, and QCocoaEventLoopIntegration.
Friends and Related Functions
QEventDispatcherQPA
friend class QEventDispatcherQPA friend
Definition at line 75 of file qplatformeventloopintegration_qpa.h.
Properties
d_ptr
QScopedPointer<QPlatformEventLoopIntegrationPrivate> QPlatformEventLoopIntegration::d_ptr protected
Definition at line 72 of file qplatformeventloopintegration_qpa.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qplatformeventloopintegration_qpa.h
/src/gui/kernel/qplatformeventloopintegration_qpa.cpp