Qt 4.8: QMutexPool Class Reference
QMutexPool Class Reference
The QMutexPool class provides a pool of QMutex objects.
#include <qmutexpool_p.h>
Public Functions
QMutex * get (const void *address)
Returns a QMutex from the pool.
QMutexPool (QMutex::RecursionMode recursionMode=QMutex::NonRecursive, int size=131)
Constructs a QMutexPool, reserving space for size QMutexes.
~QMutexPool ()
Destructs a QMutexPool.
Static Public Functions
static QMutex * globalInstanceGet (const void *address)
Returns a QMutex from the global mutex pool.
static QMutexPool * instance ()
Returns the global QMutexPool instance.
Private Functions
QMutex * createMutex (int index)
Properties
QVarLengthArray< QAtomicPointer< QMutex >, 131 > mutexes
QMutex::RecursionMode recursionMode
Detailed Description
The QMutexPool class provides a pool of QMutex objects.
Warning
This function is not part of the public interface.
QMutexPool is a convenience class that provides access to a fixed number of QMutex objects.
Typical use of a QMutexPool is in situations where it is not possible or feasible to use one QMutex for every protected object. The mutex pool will return a mutex based on the address of the object that needs protection.
For example, consider this simple class:
class Number {
public:
    Number(double n) : num (n) { }
    void setNumber(double n) { num = n; }
    double number() const { return num; }
private:
    double num;
};
Adding a QMutex member to the Number class does not make sense, because it is so small. However, in order to ensure that access to each Number is protected, you need to use a mutex. In this case, a QMutexPool would be ideal.
Code to calculate the square of a number would then look something like this:
void calcSquare(Number *num)
{
    QMutexLocker locker(mutexpool.get(num));
    num.setNumber(num.number() * num.number());
}
This function will safely calculate the square of a number, since it uses a mutex from a QMutexPool. The mutex is locked and unlocked automatically by the QMutexLocker class. See the QMutexLocker documentation for more details.
Definition at line 64 of file qmutexpool_p.h.
Constructors and Destructors
QMutexPool()
QMutexPool::QMutexPool (QMutex::RecursionMode recursionMode = QMutex::NonRecursive, int size = 131) explicit
Constructs a QMutexPool, reserving space for size QMutexes.
All mutexes in the pool are created with recursionMode. By default, all mutexes are non-recursive.
The QMutexes are created when needed, and deleted when the QMutexPool is destructed.
Definition at line 101 of file qmutexpool.cpp.
     : mutexes(size), recursionMode(recursionMode)
 {
     for (int index = 0; index < mutexes.count(); ++index) {
         mutexes[index] = 0;
     }
 }
~QMutexPool()
QMutexPool::~QMutexPool ()
Destructs a QMutexPool.
All QMutexes that were created by the pool are deleted.
Definition at line 113 of file qmutexpool.cpp.
 {
     for (int index = 0; index < mutexes.count(); ++index) {
         delete mutexes[index];
         mutexes[index] = 0;
     }
 }
Functions
createMutex()
QMutex * QMutexPool::createMutex (int index) private
Warning
This function is not part of the public interface. create the mutex for the given index
Definition at line 138 of file qmutexpool.cpp.
 {
     // mutex not created, create one
     QMutex *newMutex = new QMutex(recursionMode);
     if (!mutexes[index].testAndSetOrdered(0, newMutex))
         delete newMutex;
     return mutexes[index];
 }
get()
QMutexPool::get (const void * address) inline
Returns a QMutex from the pool.
QMutexPool uses the value address to determine which mutex is returned from the pool.
Definition at line 70 of file qmutexpool_p.h.
Referenced by globalInstanceGet(), and signalSlotLock().
{
         int index = uint(quintptr(address)) % mutexes.count();
         QMutex *m = mutexes[index];
         if (m)
             return m;
         else
             return createMutex(index);
     }
globalInstanceGet()
QMutex * QMutexPool::globalInstanceGet (const void * address) static
Returns a QMutex from the global mutex pool.
Definition at line 150 of file qmutexpool.cpp.
Referenced by QHostInfoAgent::fromName(), QVariantAnimationPrivate::getInterpolator(), ignoreSigPipe(), QSslCertificate::issuerInfo(), q_resolveOpenSslSymbols(), qdbus_loadLibDBus(), resolveUNCLibs(), QSslCertificate::serialNumber(), QSslCertificate::subjectInfo(), QPropertyAnimation::updateState(), and QSslCertificate::version().
 {
     QMutexPool * const globalInstance = globalMutexPool();
     if (globalInstance == 0)
         return 0;
     return globalInstance->get(address);
 }
instance()
QMutexPool * QMutexPool::instance () static
Returns the global QMutexPool instance.
Definition at line 124 of file qmutexpool.cpp.
Referenced by QThread::initialize(), and QEventDispatcherGlibPrivate::QEventDispatcherGlibPrivate().
 {
     return globalMutexPool();
 }
Properties
mutexes
QVarLengthArray<QAtomicPointer<QMutex>, 131> QMutexPool::mutexes private
Definition at line 83 of file qmutexpool_p.h.
Referenced by createMutex(), and ~QMutexPool().
recursionMode
QMutex::RecursionMode QMutexPool::recursionMode private
Definition at line 84 of file qmutexpool_p.h.
Referenced by createMutex().
The documentation for this class was generated from the following files:
/src/corelib/thread/qmutexpool_p.h
/src/corelib/thread/qmutexpool.cpp