Qt 4.8: QFutureCallOutInterface Class Reference
QFutureCallOutInterface Class Reference abstract
#include <qfutureinterface_p.h>
Public Functions
virtual void callOutInterfaceDisconnected ()=0
virtual void postCallOutEvent (const QFutureCallOutEvent &)=0
virtual ~QFutureCallOutInterface ()
Detailed Description
Definition at line 119 of file qfutureinterface_p.h.
Constructors and Destructors
~QFutureCallOutInterface()
virtual QFutureCallOutInterface::~QFutureCallOutInterface () inline virtual
Definition at line 122 of file qfutureinterface_p.h.
 {}
Functions
callOutInterfaceDisconnected()
virtual void QFutureCallOutInterface::callOutInterfaceDisconnected () pure virtual
Implemented in QFutureWatcherBasePrivate.
Referenced by QFutureInterfaceBasePrivate::disconnectOutputInterface().
postCallOutEvent()
virtual void QFutureCallOutInterface::postCallOutEvent (const QFutureCallOutEvent &) pure virtual
Implemented in QFutureWatcherBasePrivate.
Referenced by QFutureInterfaceBasePrivate::connectOutputInterface(), and QFutureInterfaceBasePrivate::sendCallOut().
The documentation for this class was generated from the following file:
/src/corelib/concurrent/qfutureinterface_p.h