Qt 4.8: QDeclarativeDelayedError Class Reference
QDeclarativeDelayedError Class Reference
#include <qdeclarativeexpression_p.h>
Public Functions
bool addError (QDeclarativeEnginePrivate *)
QDeclarativeDelayedError ()
void removeError ()
~QDeclarativeDelayedError ()
Public Variables
QDeclarativeError error
Properties
QDeclarativeDelayedError * nextError
QDeclarativeDelayedError ** prevError
Detailed Description
Definition at line 87 of file qdeclarativeexpression_p.h.
Constructors and Destructors
QDeclarativeDelayedError()
QDeclarativeDelayedError::QDeclarativeDelayedError () inline
Definition at line 90 of file qdeclarativeexpression_p.h.
 : nextError(0), prevError(0) {}
~QDeclarativeDelayedError()
QDeclarativeDelayedError::~QDeclarativeDelayedError () inline
Definition at line 91 of file qdeclarativeexpression_p.h.
 { removeError(); }
Functions
addError()
bool QDeclarativeDelayedError::addError (QDeclarativeEnginePrivate * e)
Definition at line 58 of file qdeclarativeexpression.cpp.
Referenced by throwException().
 {
     if (!e) return false;
     if (e->inProgressCreations == 0) return false; // Not in construction
     if (prevError) return true; // Already in error chain
     prevError = &e->erroredBindings;
     nextError = e->erroredBindings;
     e->erroredBindings = this;
     if (nextError) nextError->prevError = &nextError;
     return true;
 }
removeError()
void QDeclarativeDelayedError::removeError () inline
Definition at line 97 of file qdeclarativeexpression_p.h.
Referenced by QDeclarativeComponentPrivate::complete(), and QDeclarativeCompiledBindingsPrivate::run().
{
         if (!prevError) return;
         if (nextError) nextError->prevError = prevError;
         *prevError = nextError;
         nextError = 0;
         prevError = 0;
     }
Properties
error
QDeclarativeError QDeclarativeDelayedError::error
Definition at line 93 of file qdeclarativeexpression_p.h.
Referenced by QDeclarativeComponentPrivate::complete(), and throwException().
nextError
QDeclarativeDelayedError* QDeclarativeDelayedError::nextError private
Definition at line 106 of file qdeclarativeexpression_p.h.
Referenced by addError().
prevError
QDeclarativeDelayedError** QDeclarativeDelayedError::prevError private
Definition at line 107 of file qdeclarativeexpression_p.h.
Referenced by addError().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeexpression_p.h
/src/declarative/qml/qdeclarativeexpression.cpp