Qt 4.8: QXmlStreamEntityDeclaration Class Reference
QXmlStreamEntityDeclaration Class Reference
The QXmlStreamEntityDeclaration class represents a DTD entity declaration.
#include <qxmlstream.h>
Public Functions
QStringRef name () const
Returns the entity name.
QStringRef notationName () const
Returns the notation name.
bool operator!= (const QXmlStreamEntityDeclaration &other) const
Compares this entity declaration with other and returns true if they are not equal; otherwise returns false.
QXmlStreamEntityDeclaration & operator= (const QXmlStreamEntityDeclaration &)
Assigns other to this entity declaration.
bool operator== (const QXmlStreamEntityDeclaration &other) const
Compares this entity declaration with other and returns true if they are equal; otherwise returns false.
QStringRef publicId () const
Returns the public identifier.
QXmlStreamEntityDeclaration ()
Creates an empty entity declaration.
QXmlStreamEntityDeclaration (const QXmlStreamEntityDeclaration &)
Creates a copy of other.
QStringRef systemId () const
Returns the system identifier.
QStringRef value () const
Returns the entity's value.
~QXmlStreamEntityDeclaration ()
Destructs this entity declaration.
Properties
QXmlStreamStringRef m_name
QXmlStreamStringRef m_notationName
QXmlStreamStringRef m_publicId
QXmlStreamStringRef m_systemId
QXmlStreamStringRef m_value
void * reserved
Friends
class QXmlStreamReaderPrivate
Related Functions
(Note that these are not member functions.)
QXmlStreamEntityDeclarations
Synonym for QVector<QXmlStreamEntityDeclaration>.
Detailed Description
The QXmlStreamEntityDeclaration class represents a DTD entity declaration.
Since
4.3
Note
This class or function is reentrant.
An entity declaration consists of a name(), a notationName(), a systemId(), a publicId(), and a value().
Definition at line 251 of file qxmlstream.h.
Constructors and Destructors
QXmlStreamEntityDeclaration() [1/2]
QXmlStreamEntityDeclaration::QXmlStreamEntityDeclaration ()
Creates an empty entity declaration.
Definition at line 2731 of file qxmlstream.cpp.
 {
 }
~QXmlStreamEntityDeclaration()
QXmlStreamEntityDeclaration::~QXmlStreamEntityDeclaration ()
Destructs this entity declaration.
Definition at line 2759 of file qxmlstream.cpp.
 {
 }
QXmlStreamEntityDeclaration() [2/2]
QXmlStreamEntityDeclaration::QXmlStreamEntityDeclaration (const QXmlStreamEntityDeclaration & other)
Creates a copy of other.
Definition at line 2738 of file qxmlstream.cpp.
 {
     *this = other;
 }
Functions
name()
QStringRef QXmlStreamEntityDeclaration::name () const inline
Returns the entity name.
Definition at line 261 of file qxmlstream.h.
Referenced by operator==().
 { return m_name; }
notationName()
QStringRef QXmlStreamEntityDeclaration::notationName () const inline
Returns the notation name.
Definition at line 262 of file qxmlstream.h.
Referenced by operator==().
 { return m_notationName; }
operator!=()
bool QXmlStreamEntityDeclaration::operator!= (const QXmlStreamEntityDeclaration & other) const inline
Compares this entity declaration with other and returns true if they are not equal; otherwise returns false.
Definition at line 273 of file qxmlstream.h.
         { return !operator==(other); }
operator=()
QXmlStreamEntityDeclaration & QXmlStreamEntityDeclaration::operator= (const QXmlStreamEntityDeclaration & other)
Assigns other to this entity declaration.
Definition at line 2746 of file qxmlstream.cpp.
 {
     m_name = other.m_name;
     m_notationName = other.m_notationName;
     m_systemId = other.m_systemId;
     m_publicId = other.m_publicId;
     m_value = other.m_value;
     return *this;
 }
operator==()
bool QXmlStreamEntityDeclaration::operator== (const QXmlStreamEntityDeclaration & other) const inline
Compares this entity declaration with other and returns true if they are equal; otherwise returns false.
Definition at line 266 of file qxmlstream.h.
{
         return (name() == other.name()
                 && notationName() == other.notationName()
                 && systemId() == other.systemId()
                 && publicId() == other.publicId()
                 && value() == other.value());
     }
publicId()
QStringRef QXmlStreamEntityDeclaration::publicId () const inline
Returns the public identifier.
Definition at line 264 of file qxmlstream.h.
Referenced by operator==().
 { return m_publicId; }
systemId()
QStringRef QXmlStreamEntityDeclaration::systemId () const inline
Returns the system identifier.
Definition at line 263 of file qxmlstream.h.
Referenced by operator==().
 { return m_systemId; }
value()
QStringRef QXmlStreamEntityDeclaration::value () const inline
Returns the entity's value.
Definition at line 265 of file qxmlstream.h.
Referenced by operator==().
 { return m_value; }
Friends and Related Functions
QXmlStreamEntityDeclarations()
QXmlStreamEntityDeclarations related
Synonym for QVector<QXmlStreamEntityDeclaration>.
QXmlStreamReaderPrivate
friend class QXmlStreamReaderPrivate friend
Definition at line 255 of file qxmlstream.h.
Properties
m_name
QXmlStreamStringRef QXmlStreamEntityDeclaration::m_name private
Definition at line 252 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveDtd().
m_notationName
QXmlStreamStringRef QXmlStreamEntityDeclaration::m_notationName private
Definition at line 252 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveDtd().
m_publicId
QXmlStreamStringRef QXmlStreamEntityDeclaration::m_publicId private
Definition at line 252 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveDtd().
m_systemId
QXmlStreamStringRef QXmlStreamEntityDeclaration::m_systemId private
Definition at line 252 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveDtd().
m_value
QXmlStreamStringRef QXmlStreamEntityDeclaration::m_value private
Definition at line 252 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveDtd().
reserved
void* QXmlStreamEntityDeclaration::reserved private
Definition at line 253 of file qxmlstream.h.
The documentation for this class was generated from the following files:
/src/corelib/xml/qxmlstream.h
/src/corelib/xml/qxmlstream.cpp