Qt 4.8: QVector3D Class Reference
QVector3D Class Reference
The QVector3D class represents a vector or vertex in 3D space.
#include <qvector3d.h>
Public Functions
qreal distanceToLine (const QVector3D &point, const QVector3D &direction) const
Returns the distance that this vertex is from a line defined by point and the unit vector direction.
qreal distanceToPlane (const QVector3D &plane, const QVector3D &normal) const
Returns the distance from this vertex to a plane defined by the vertex plane and a normal unit vector.
qreal distanceToPlane (const QVector3D &plane1, const QVector3D &plane2, const QVector3D &plane3) const
Returns the distance from this vertex a plane defined by the vertices plane1, plane2 and plane3.
bool isNull () const
Returns true if the x, y, and z coordinates are set to 0.
qreal length () const
Returns the length of the vector from the origin.
qreal lengthSquared () const
Returns the squared length of the vector from the origin.
void normalize ()
Normalizes the currect vector in place.
QVector3D normalized () const
Returns the normalized unit vector form of this vector.
operator QVariant () const
Returns the 3D vector as a QVariant.
QVector3D & operator*= (qreal factor)
Multiplies this vector's coordinates by the given factor, and returns a reference to this vector.
QVector3D & operator*= (const QVector3D &vector)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Multiplies the components of this vector by the corresponding components in vector.
QVector3D & operator+= (const QVector3D &vector)
Adds the given vector to this vector and returns a reference to this vector.
QVector3D & operator-= (const QVector3D &vector)
Subtracts the given vector from this vector and returns a reference to this vector.
QVector3D & operator/= (qreal divisor)
Divides this vector's coordinates by the given divisor, and returns a reference to this vector.
QVector3D ()
Constructs a null vector, i.
QVector3D (qreal xpos, qreal ypos, qreal zpos)
Constructs a vector with coordinates (xpos, ypos, zpos).
QVector3D (const QPoint &point)
Constructs a vector with x and y coordinates from a 2D point, and a z coordinate of 0.
QVector3D (const QPointF &point)
Constructs a vector with x and y coordinates from a 2D point, and a z coordinate of 0.
QVector3D (const QVector2D &vector)
Constructs a 3D vector from the specified 2D vector.
QVector3D (const QVector2D &vector, qreal zpos)
Constructs a 3D vector from the specified 2D vector.
QVector3D (const QVector4D &vector)
Constructs a 3D vector from the specified 4D vector.
void setX (qreal x)
Sets the x coordinate of this point to the given x coordinate.
void setY (qreal y)
Sets the y coordinate of this point to the given y coordinate.
void setZ (qreal z)
Sets the z coordinate of this point to the given z coordinate.
QPoint toPoint () const
Returns the QPoint form of this 3D vector.
QPointF toPointF () const
Returns the QPointF form of this 3D vector.
QVector2D toVector2D () const
Returns the 2D vector form of this 3D vector, dropping the z coordinate.
QVector4D toVector4D () const
Returns the 4D form of this 3D vector, with the w coordinate set to zero.
qreal x () const
Returns the x coordinate of this point.
qreal y () const
Returns the y coordinate of this point.
qreal z () const
Returns the z coordinate of this point.
Static Public Functions
static QVector3D crossProduct (const QVector3D &v1, const QVector3D &v2)
Returns the cross-product of vectors v1 and v2, which corresponds to the normal vector of a plane defined by v1 and v2.
static qreal dotProduct (const QVector3D &v1, const QVector3D &v2)
Returns the dot product of v1 and v2.
static QVector3D normal (const QVector3D &v1, const QVector3D &v2)
Returns the normal vector of a plane defined by vectors v1 and v2, normalized to be a unit vector.
static QVector3D normal (const QVector3D &v1, const QVector3D &v2, const QVector3D &v3)
Returns the normal vector of a plane defined by vectors v2 - v1 and v3 - v1, normalized to be a unit vector.
Private Functions
QVector3D (float xpos, float ypos, float zpos, int dummy)
Properties
float xp
float yp
float zp
Friends
bool operator!= (const QVector3D &v1, const QVector3D &v2)
Returns true if v1 is not equal to v2; otherwise returns false.
const QVector3D operator* (qreal factor, const QVector3D &vector)
const QVector3D operator* (const QVector3D &vector, qreal factor)
const QVector3D operator* (const QVector3D &v1, const QVector3D &v2)
QVector3D operator* (const QVector3D &vector, const QMatrix4x4 &matrix)
QVector3D operator* (const QMatrix4x4 &matrix, const QVector3D &vector)
const QVector3D operator+ (const QVector3D &v1, const QVector3D &v2)
Returns a QVector3D object that is the sum of the given vectors, v1 and v2; each component is added separately.
const QVector3D operator- (const QVector3D &v1, const QVector3D &v2)
Returns a QVector3D object that is formed by subtracting v2 from v1; each component is subtracted separately.
const QVector3D operator- (const QVector3D &vector)
Returns a QVector3D object that is formed by changing the sign of all three components of the given vector.
const QVector3D operator/ (const QVector3D &vector, qreal divisor)
Returns the QVector3D object formed by dividing all three components of the given vector by the given divisor.
bool operator== (const QVector3D &v1, const QVector3D &v2)
Returns true if v1 is equal to v2; otherwise returns false.
bool qFuzzyCompare (const QVector3D &v1, const QVector3D &v2)
Returns true if v1 and v2 are equal, allowing for a small fuzziness factor for floating-point comparisons; false otherwise.
class QVector2D
class QVector4D
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QVector3D &vector)
Writes the given vector to the given stream and returns a reference to the stream.
QDataStream & operator>> (QDataStream &stream, QVector3D &vector)
Reads a 3D vector from the given stream into the given vector and returns a reference to the stream.
Detailed Description
The QVector3D class represents a vector or vertex in 3D space.
Since
4.6
Vectors are one of the main building blocks of 3D representation and drawing. They consist of three coordinates, traditionally called x, y, and z.
The QVector3D class can also be used to represent vertices in 3D space. We therefore do not need to provide a separate vertex class.
Note: By design values in the QVector3D instance are stored as float. This means that on platforms where the qreal arguments to QVector3D functions are represented by double values, it is possible to lose precision.
See also
QVector2D, QVector4D, QQuaternion
Definition at line 60 of file qvector3d.h.
Constructors and Destructors
QVector3D() [1/8]
QVector3D::QVector3D () inline
Constructs a null vector, i.
e. with coordinates (0, 0, 0).
Definition at line 146 of file qvector3d.h.
Referenced by crossProduct(), normalized(), operator*(), operator+(), operator-(), and operator/().
 : xp(0.0f), yp(0.0f), zp(0.0f) {}
QVector3D() [2/8]
QVector3D::QVector3D (qreal xpos, qreal ypos, qreal zpos) inline
Constructs a vector with coordinates (xpos, ypos, zpos).
Definition at line 148 of file qvector3d.h.
 : xp(xpos), yp(ypos), zp(zpos) {}
QVector3D() [3/8]
QVector3D::QVector3D (const QPoint & point) inline explicit
Constructs a vector with x and y coordinates from a 2D point, and a z coordinate of 0.
Definition at line 152 of file qvector3d.h.
 : xp(point.x()), yp(point.y()), zp(0.0f) {}
QVector3D() [4/8]
QVector3D::QVector3D (const QPointF & point) inline explicit
Constructs a vector with x and y coordinates from a 2D point, and a z coordinate of 0.
Definition at line 154 of file qvector3d.h.
 : xp(point.x()), yp(point.y()), zp(0.0f) {}
QVector3D() [5/8]
QVector3D::QVector3D (const QVector2D & vector)
Constructs a 3D vector from the specified 2D vector.
The z coordinate is set to zero.
See also
toVector2D()
Definition at line 123 of file qvector3d.cpp.
 {
     xp = vector.xp;
     yp = vector.yp;
     zp = 0.0f;
 }
QVector3D() [6/8]
QVector3D::QVector3D (const QVector2D & vector, qreal zpos)
Constructs a 3D vector from the specified 2D vector.
The z coordinate is set to zpos.
See also
toVector2D()
Definition at line 136 of file qvector3d.cpp.
 {
     xp = vector.xp;
     yp = vector.yp;
     zp = zpos;
 }
QVector3D() [7/8]
QVector3D::QVector3D (const QVector4D & vector) explicit
Constructs a 3D vector from the specified 4D vector.
The w coordinate is dropped.
See also
toVector4D()
Definition at line 153 of file qvector3d.cpp.
 {
     xp = vector.xp;
     yp = vector.yp;
     zp = vector.zp;
 }
QVector3D() [8/8]
QVector3D::QVector3D (float xpos, float ypos, float zpos, int dummy) inline private
Definition at line 150 of file qvector3d.h.
 : xp(xpos), yp(ypos), zp(zpos) {}
Functions
crossProduct()
QVector3D QVector3D::crossProduct (const QVector3D & v1, const QVector3D & v2) static
Returns the cross-product of vectors v1 and v2, which corresponds to the normal vector of a plane defined by v1 and v2.
See also
normal()
Definition at line 352 of file qvector3d.cpp.
Referenced by QMatrix4x4::lookAt(), and normal().
 {
     return QVector3D(v1.yp * v2.zp - v1.zp * v2.yp,
                     v1.zp * v2.xp - v1.xp * v2.zp,
                     v1.xp * v2.yp - v1.yp * v2.xp, 1);
 }
distanceToLine()
qreal QVector3D::distanceToLine (const QVector3D & point, const QVector3D & direction) const
Returns the distance that this vertex is from a line defined by point and the unit vector direction.
If direction is a null vector, then it does not define a line. In that case, the distance from point to this vertex is returned.
See also
distanceToPlane()
Definition at line 444 of file qvector3d.cpp.
Referenced by distanceToPlane().
 {
     if (direction.isNull())
         return (*this - point).length();
     QVector3D p = point + dotProduct(*this - point, direction) * direction;
     return (*this - p).length();
 }
distanceToPlane() [1/2]
qreal QVector3D::distanceToPlane (const QVector3D & plane, const QVector3D & normal) const
Returns the distance from this vertex to a plane defined by the vertex plane and a normal unit vector.
The normal parameter is assumed to have been normalized to a unit vector.
The return value will be negative if the vertex is below the plane, or zero if it is on the plane.
See also
normal(), distanceToLine()
Definition at line 405 of file qvector3d.cpp.
Referenced by normal().
 {
     return dotProduct(*this - plane, normal);
 }
distanceToPlane() [2/2]
qreal QVector3D::distanceToPlane (const QVector3D & plane1, const QVector3D & plane2, const QVector3D & plane3) const
Returns the distance from this vertex a plane defined by the vertices plane1, plane2 and plane3.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The return value will be negative if the vertex is below the plane, or zero if it is on the plane.
The two vectors that define the plane are plane2 - plane1 and plane3 - plane1.
See also
normal(), distanceToLine()
Definition at line 428 of file qvector3d.cpp.
 {
     QVector3D n = normal(plane2 - plane1, plane3 - plane1);
     return dotProduct(*this - plane1, n);
 }
dotProduct()
qreal QVector3D::dotProduct (const QVector3D & v1, const QVector3D & v2) static
Returns the dot product of v1 and v2.
Definition at line 341 of file qvector3d.cpp.
Referenced by distanceToLine(), and distanceToPlane().
 {
     return v1.xp * v2.xp + v1.yp * v2.yp + v1.zp * v2.zp;
 }
isNull()
bool QVector3D::isNull () const inline
Returns true if the x, y, and z coordinates are set to 0.
0, otherwise returns false.
Definition at line 156 of file qvector3d.h.
Referenced by distanceToLine().
 {
     return qIsNull(xp) && qIsNull(yp) && qIsNull(zp);
 }
length()
qreal QVector3D::length () const
Returns the length of the vector from the origin.
See also
lengthSquared(), normalized()
Definition at line 632 of file qvector3d.cpp.
 {
     return qSqrt(xp * xp + yp * yp + zp * zp);
 }
lengthSquared()
qreal QVector3D::lengthSquared () const
Returns the squared length of the vector from the origin.
This is equivalent to the dot product of the vector with itself.
See also
length(), dotProduct()
Definition at line 643 of file qvector3d.cpp.
 {
     return xp * xp + yp * yp + zp * zp;
 }
normal() [1/2]
QVector3D QVector3D::normal (const QVector3D & v1, const QVector3D & v2) static
Returns the normal vector of a plane defined by vectors v1 and v2, normalized to be a unit vector.
Use crossProduct() to compute the cross-product of v1 and v2 if you do not need the result to be normalized to a unit vector.
See also
crossProduct(), distanceToPlane()
Definition at line 368 of file qvector3d.cpp.
Referenced by distanceToPlane().
 {
     return crossProduct(v1, v2).normalized();
 }
normal() [2/2]
QVector3D QVector3D::normal (const QVector3D & v1, const QVector3D & v2, const QVector3D & v3) static
Returns the normal vector of a plane defined by vectors v2 - v1 and v3 - v1, normalized to be a unit vector.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Use crossProduct() to compute the cross-product of v2 - v1 and v3 - v1 if you do not need the result to be normalized to a unit vector.
See also
crossProduct(), distanceToPlane()
Definition at line 389 of file qvector3d.cpp.
 {
     return crossProduct((v2 - v1), (v3 - v1)).normalized();
 }
normalize()
void QVector3D::normalize ()
Normalizes the currect vector in place.
Nothing happens if this vector is a null vector or the length of the vector is very close to 1.
See also
length(), normalized()
Definition at line 267 of file qvector3d.cpp.
 {
     // Need some extra precision if the length is very small.
     double len = double(xp) * double(xp) +
                  double(yp) * double(yp) +
                  double(zp) * double(zp);
     if (qFuzzyIsNull(len - 1.0f) || qFuzzyIsNull(len))
         return;
     len = qSqrt(len);
     xp /= len;
     yp /= len;
     zp /= len;
 }
normalized()
QVector3D QVector3D::normalized () const
Returns the normalized unit vector form of this vector.
If this vector is null, then a null vector is returned. If the length of the vector is very close to 1, then the vector will be returned as-is. Otherwise the normalized form of the vector of length 1 will be returned.
See also
length(), normalize()
Definition at line 247 of file qvector3d.cpp.
Referenced by QQuaternion::fromAxisAndAngle(), QMatrix4x4::lookAt(), and normal().
 {
     // Need some extra precision if the length is very small.
     double len = double(xp) * double(xp) +
                  double(yp) * double(yp) +
                  double(zp) * double(zp);
     if (qFuzzyIsNull(len - 1.0f))
         return *this;
     else if (!qFuzzyIsNull(len))
         return *this / qSqrt(len);
     else
         return QVector3D();
 }
operator QVariant()
QVector3D::operator QVariant () const
Returns the 3D vector as a QVariant.
Definition at line 622 of file qvector3d.cpp.
 {
     return QVariant(QVariant::Vector3D, this);
 }
operator*=() [1/2]
QVector3D & QVector3D::operator*= (qreal factor) inline
Multiplies this vector's coordinates by the given factor, and returns a reference to this vector.
See also
operator/=()
Definition at line 185 of file qvector3d.h.
 {
     xp *= factor;
     yp *= factor;
     zp *= factor;
     return *this;
 }
operator*=() [2/2]
QVector3D & QVector3D::operator*= (const QVector3D & vector) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Multiplies the components of this vector by the corresponding components in vector.
Note: this is not the same as the crossProduct() of this vector and vector.
See also
crossProduct()
Definition at line 193 of file qvector3d.h.
 {
     xp *= vector.xp;
     yp *= vector.yp;
     zp *= vector.zp;
     return *this;
 }
operator+=()
QVector3D & QVector3D::operator+= (const QVector3D & vector) inline
Adds the given vector to this vector and returns a reference to this vector.
See also
operator-=()
Definition at line 169 of file qvector3d.h.
 {
     xp += vector.xp;
     yp += vector.yp;
     zp += vector.zp;
     return *this;
 }
operator-=()
QVector3D & QVector3D::operator-= (const QVector3D & vector) inline
Subtracts the given vector from this vector and returns a reference to this vector.
See also
operator+=()
Definition at line 177 of file qvector3d.h.
 {
     xp -= vector.xp;
     yp -= vector.yp;
     zp -= vector.zp;
     return *this;
 }
operator/=()
QVector3D & QVector3D::operator/= (qreal divisor) inline
Divides this vector's coordinates by the given divisor, and returns a reference to this vector.
See also
operator*=()
Definition at line 201 of file qvector3d.h.
 {
     xp /= divisor;
     yp /= divisor;
     zp /= divisor;
     return *this;
 }
setX()
void QVector3D::setX (qreal x) inline
Sets the x coordinate of this point to the given x coordinate.
See also
x(), setY(), setZ()
Definition at line 165 of file qvector3d.h.
Referenced by operator>>(), and QDeclarativeVector3DValueType::setX().
 { xp = aX; }
setY()
void QVector3D::setY (qreal y) inline
Sets the y coordinate of this point to the given y coordinate.
See also
y(), setX(), setZ()
Definition at line 166 of file qvector3d.h.
Referenced by operator>>(), and QDeclarativeVector3DValueType::setY().
 { yp = aY; }
setZ()
void QVector3D::setZ (qreal z) inline
Sets the z coordinate of this point to the given z coordinate.
See also
z(), setX(), setY()
Definition at line 167 of file qvector3d.h.
Referenced by operator>>(), and QDeclarativeVector3DValueType::setZ().
 { zp = aZ; }
toPoint()
QPoint QVector3D::toPoint () const inline
Returns the QPoint form of this 3D vector.
The z coordinate is dropped.
See also
toPointF(), toVector2D()
Definition at line 261 of file qvector3d.h.
 {
     return QPoint(qRound(xp), qRound(yp));
 }
toPointF()
QPointF QVector3D::toPointF () const inline
Returns the QPointF form of this 3D vector.
The z coordinate is dropped.
See also
toPoint(), toVector2D()
Definition at line 266 of file qvector3d.h.
 {
     return QPointF(qreal(xp), qreal(yp));
 }
toVector2D()
QVector2D QVector3D::toVector2D () const
Returns the 2D vector form of this 3D vector, dropping the z coordinate.
See also
toVector4D(), toPoint()
Definition at line 574 of file qvector3d.cpp.
 {
     return QVector2D(xp, yp, 1);
 }
toVector4D()
QVector4D QVector3D::toVector4D () const
Returns the 4D form of this 3D vector, with the w coordinate set to zero.
See also
toVector2D(), toPoint()
Definition at line 588 of file qvector3d.cpp.
 {
     return QVector4D(xp, yp, zp, 0.0f, 1);
 }
x()
qreal QVector3D::x () const inline
Returns the x coordinate of this point.
See also
setX(), y(), z()
Definition at line 161 of file qvector3d.h.
Referenced by QQuaternion::fromAxisAndAngle(), QDeclarativeCompiler::genLiteralAssignment(), QMatrix4x4::lookAt(), QMatrix4x4::mapVector(), QWidgetPrivate::moveRect(), operator*(), operator<<(), operator>>(), QMatrix4x4::rotate(), QMatrix4x4::scale(), QWidgetPrivate::scrollRect(), QDeclarativeVector3DValueType::setValue(), QQuaternion::setVector(), and QMatrix4x4::translate().
 { return qreal(xp); }
y()
qreal QVector3D::y () const inline
Returns the y coordinate of this point.
See also
setY(), x(), z()
Definition at line 162 of file qvector3d.h.
Referenced by QQuaternion::fromAxisAndAngle(), QDeclarativeCompiler::genLiteralAssignment(), QMatrix4x4::lookAt(), QMatrix4x4::mapVector(), operator*(), operator<<(), operator>>(), QMatrix4x4::rotate(), QMatrix4x4::scale(), QDeclarativeVector3DValueType::setValue(), QQuaternion::setVector(), and QMatrix4x4::translate().
 { return qreal(yp); }
z()
qreal QVector3D::z () const inline
Returns the z coordinate of this point.
See also
setZ(), x(), y()
Definition at line 163 of file qvector3d.h.
Referenced by QQuaternion::fromAxisAndAngle(), QDeclarativeCompiler::genLiteralAssignment(), QMatrix4x4::lookAt(), QMatrix4x4::mapVector(), operator*(), operator<<(), operator>>(), QMatrix4x4::rotate(), QMatrix4x4::scale(), QDeclarativeVector3DValueType::setValue(), QQuaternion::setVector(), and QMatrix4x4::translate().
 { return qreal(zp); }
Friends and Related Functions
operator!=
bool operator!= (const QVector3D & v1, const QVector3D & v2) friend
Returns true if v1 is not equal to v2; otherwise returns false.
This operator uses an exact floating-point comparison.
Definition at line 214 of file qvector3d.h.
 {
     return v1.xp != v2.xp || v1.yp != v2.yp || v1.zp != v2.zp;
 }
operator* [1/5]
const QVector3D operator* (qreal factor, const QVector3D & vector) friend
Returns a copy of the given vector, multiplied by the given factor.
See also
QVector3D::operator*=()
Definition at line 229 of file qvector3d.h.
 {
     return QVector3D(vector.xp * factor, vector.yp * factor, vector.zp * factor, 1);
 }
operator* [2/5]
const QVector3D operator* (const QVector3D & vector, qreal factor) friend
Returns a copy of the given vector, multiplied by the given factor.
See also
QVector3D::operator*=()
Definition at line 234 of file qvector3d.h.
 {
     return QVector3D(vector.xp * factor, vector.yp * factor, vector.zp * factor, 1);
 }
operator* [3/5]
const QVector3D operator* (const QVector3D & v1, const QVector3D & v2) friend
Multiplies the components of v1 by the corresponding components in v2.
Note: this is not the same as the crossProduct() of v1 and v2.
See also
QVector3D::crossProduct()
Definition at line 239 of file qvector3d.h.
 {
     return QVector3D(v1.xp * v2.xp, v1.yp * v2.yp, v1.zp * v2.zp, 1);
 }
operator* [4/5]
QVector3D operator* (const QVector3D & vector, const QMatrix4x4 & matrix) friend
Definition at line 606 of file qmatrix4x4.h.
 {
     qreal x, y, z, w;
     x = vector.x() * matrix.m[0][0] +
         vector.y() * matrix.m[0][1] +
         vector.z() * matrix.m[0][2] +
         matrix.m[0][3];
     y = vector.x() * matrix.m[1][0] +
         vector.y() * matrix.m[1][1] +
         vector.z() * matrix.m[1][2] +
         matrix.m[1][3];
     z = vector.x() * matrix.m[2][0] +
         vector.y() * matrix.m[2][1] +
         vector.z() * matrix.m[2][2] +
         matrix.m[2][3];
     w = vector.x() * matrix.m[3][0] +
         vector.y() * matrix.m[3][1] +
         vector.z() * matrix.m[3][2] +
         matrix.m[3][3];
     if (w == 1.0f)
         return QVector3D(x, y, z);
     else
         return QVector3D(x / w, y / w, z / w);
 }
operator* [5/5]
QVector3D operator* (const QMatrix4x4 & matrix, const QVector3D & vector) friend
Definition at line 631 of file qmatrix4x4.h.
 {
     qreal x, y, z, w;
     if (matrix.flagBits == QMatrix4x4::Identity) {
         return vector;
     } else if (matrix.flagBits == QMatrix4x4::Translation) {
         return QVector3D(vector.x() + matrix.m[3][0],
                          vector.y() + matrix.m[3][1],
                          vector.z() + matrix.m[3][2]);
     } else if (matrix.flagBits ==
                     (QMatrix4x4::Translation | QMatrix4x4::Scale)) {
         return QVector3D(vector.x() * matrix.m[0][0] + matrix.m[3][0],
                          vector.y() * matrix.m[1][1] + matrix.m[3][1],
                          vector.z() * matrix.m[2][2] + matrix.m[3][2]);
     } else if (matrix.flagBits == QMatrix4x4::Scale) {
         return QVector3D(vector.x() * matrix.m[0][0],
                          vector.y() * matrix.m[1][1],
                          vector.z() * matrix.m[2][2]);
     } else {
         x = vector.x() * matrix.m[0][0] +
             vector.y() * matrix.m[1][0] +
             vector.z() * matrix.m[2][0] +
             matrix.m[3][0];
         y = vector.x() * matrix.m[0][1] +
             vector.y() * matrix.m[1][1] +
             vector.z() * matrix.m[2][1] +
             matrix.m[3][1];
         z = vector.x() * matrix.m[0][2] +
             vector.y() * matrix.m[1][2] +
             vector.z() * matrix.m[2][2] +
             matrix.m[3][2];
         w = vector.x() * matrix.m[0][3] +
             vector.y() * matrix.m[1][3] +
             vector.z() * matrix.m[2][3] +
             matrix.m[3][3];
         if (w == 1.0f)
             return QVector3D(x, y, z);
         else
             return QVector3D(x / w, y / w, z / w);
     }
 }
operator+
const QVector3D operator+ (const QVector3D & v1, const QVector3D & v2) friend
Returns a QVector3D object that is the sum of the given vectors, v1 and v2; each component is added separately.
See also
QVector3D::operator+=()
Definition at line 219 of file qvector3d.h.
 {
     return QVector3D(v1.xp + v2.xp, v1.yp + v2.yp, v1.zp + v2.zp, 1);
 }
operator- [1/2]
const QVector3D operator- (const QVector3D & v1, const QVector3D & v2) friend
Returns a QVector3D object that is formed by subtracting v2 from v1; each component is subtracted separately.
See also
QVector3D::operator-=()
Definition at line 224 of file qvector3d.h.
 {
     return QVector3D(v1.xp - v2.xp, v1.yp - v2.yp, v1.zp - v2.zp, 1);
 }
operator- [2/2]
const QVector3D operator- (const QVector3D & vector) friend
Returns a QVector3D object that is formed by changing the sign of all three components of the given vector.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Equivalent to {QVector3D(0,0,0) - vector}.
Definition at line 244 of file qvector3d.h.
 {
     return QVector3D(-vector.xp, -vector.yp, -vector.zp, 1);
 }
operator/
const QVector3D operator/ (const QVector3D & vector, qreal divisor) friend
Returns the QVector3D object formed by dividing all three components of the given vector by the given divisor.
See also
QVector3D::operator/=()
Definition at line 249 of file qvector3d.h.
 {
     return QVector3D(vector.xp / divisor, vector.yp / divisor, vector.zp / divisor, 1);
 }
operator<<()
QDataStream & operator<< (QDataStream & stream, const QVector3D & vector) related
Writes the given vector to the given stream and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 674 of file qvector3d.cpp.
Referenced by toPointF().
 {
     stream << double(vector.x()) << double(vector.y())
            << double(vector.z());
     return stream;
 }
operator==
bool operator== (const QVector3D & v1, const QVector3D & v2) friend
Returns true if v1 is equal to v2; otherwise returns false.
This operator uses an exact floating-point comparison.
Definition at line 209 of file qvector3d.h.
 {
     return v1.xp == v2.xp && v1.yp == v2.yp && v1.zp == v2.zp;
 }
operator>>()
QDataStream & operator>> (QDataStream & stream, QVector3D & vector) related
Reads a 3D vector from the given stream into the given vector and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 694 of file qvector3d.cpp.
Referenced by toPointF().
 {
     double x, y, z;
     stream >> x;
     stream >> y;
     stream >> z;
     vector.setX(qreal(x));
     vector.setY(qreal(y));
     vector.setZ(qreal(z));
     return stream;
 }
qFuzzyCompare
bool qFuzzyCompare (const QVector3D & v1, const QVector3D & v2) friend
Returns true if v1 and v2 are equal, allowing for a small fuzziness factor for floating-point comparisons; false otherwise.
Definition at line 254 of file qvector3d.h.
Referenced by qFuzzyCompare().
 {
     return qFuzzyCompare(v1.xp, v2.xp) &&
            qFuzzyCompare(v1.yp, v2.yp) &&
            qFuzzyCompare(v1.zp, v2.zp);
 }
QVector2D
friend class QVector2D friend
Definition at line 136 of file qvector3d.h.
Referenced by toVector2D().
QVector4D
friend class QVector4D friend
Definition at line 137 of file qvector3d.h.
Referenced by toVector4D().
Properties
xp
float QVector3D::xp private
Definition at line 132 of file qvector3d.h.
Referenced by crossProduct(), dotProduct(), isNull(), length(), lengthSquared(), normalize(), normalized(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), qFuzzyCompare(), QVector2D::QVector2D(), QVector3D(), QVector4D::QVector4D(), setX(), toPoint(), toPointF(), toVector2D(), toVector4D(), and x().
yp
float QVector3D::yp private
Definition at line 132 of file qvector3d.h.
Referenced by crossProduct(), dotProduct(), isNull(), length(), lengthSquared(), normalize(), normalized(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), qFuzzyCompare(), QVector2D::QVector2D(), QVector3D(), QVector4D::QVector4D(), setY(), toPoint(), toPointF(), toVector2D(), toVector4D(), and y().
zp
float QVector3D::zp private
Definition at line 132 of file qvector3d.h.
Referenced by crossProduct(), dotProduct(), isNull(), length(), lengthSquared(), normalize(), normalized(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), qFuzzyCompare(), QVector3D(), QVector4D::QVector4D(), setZ(), toVector4D(), and z().
The documentation for this class was generated from the following files:
/src/gui/math3d/qvector3d.h
/src/gui/math3d/qvector3d.cpp