Qt 4.8: QDeclarativeRefCount Class Reference
QDeclarativeRefCount Class Reference
#include <qdeclarativerefcount_p.h>
Public Functions
void addref ()
QDeclarativeRefCount ()
void release ()
virtual ~QDeclarativeRefCount ()
Properties
int refCount
Detailed Description
Definition at line 64 of file qdeclarativerefcount_p.h.
Constructors and Destructors
QDeclarativeRefCount()
QDeclarativeRefCount::QDeclarativeRefCount ()
Definition at line 46 of file qdeclarativerefcount.cpp.
 : refCount(1)
 {
 }
~QDeclarativeRefCount()
QDeclarativeRefCount::~QDeclarativeRefCount () virtual
Definition at line 51 of file qdeclarativerefcount.cpp.
 {
 }
Functions
addref()
void QDeclarativeRefCount::addref ()
Definition at line 55 of file qdeclarativerefcount.cpp.
Referenced by QDeclarativeTypeNameCache::add(), QDeclarativeParser::Object::addAttachedProperty(), QDeclarativeDataBlob::addDependency(), QDeclarativeParser::Object::addGroupedProperty(), DocumentImpl::addref(), QDeclarativeParser::Object::addScriptStringProperty(), QDeclarativeParser::Object::addSignalProperty(), QDeclarativeParser::Object::addValueProperty(), QDeclarativeParser::Object::addValueTypeProperty(), QDeclarativePropertyCache::append(), QDeclarativeComponentPrivate::begin(), QDeclarativeCompiler::buildObject(), QDeclarativeCompiler::compile(), QDeclarativeTypeData::compiledData(), QDeclarativeDomComponent::componentRoot(), QDeclarativeCompiledBindings::configBinding(), QDeclarativeEnginePrivate::createCache(), QDeclarativeCompiledData::TypeReference::createInstance(), QDeclarativeCompiledData::TypeReference::createPropertyCache(), QDeclarativeDomDynamicProperty::defaultValue(), QDeclarativeTypeData::done(), QDeclarativeDomObject::dynamicProperties(), QDeclarativeDomObject::dynamicProperty(), QDeclarativeCompiler::genComponent(), QDeclarativeCompiler::genObject(), QDeclarativeTypeLoader::get(), QDeclarativeTypeLoader::getQmldir(), QDeclarativeTypeLoader::getScript(), QDeclarativeExpressionPrivate::init(), QDeclarativeDomDocument::load(), QDeclarativeDataLoader::load(), QDeclarativeCompiler::mergeDynamicMetaProperties(), QDeclarativeDomValueValueSource::object(), QDeclarativeDomValueValueInterceptor::object(), QDeclarativeProperty::operator=(), QDeclarativeDomObject::properties(), QDeclarativePropertyCache::property(), QDeclarativeObjectScriptClass::propertyNames(), QDeclarativeComponent::QDeclarativeComponent(), QDeclarativeOpenMetaObject::QDeclarativeOpenMetaObject(), QDeclarativeProperty::QDeclarativeProperty(), QDeclarativeVMEMetaObject::QDeclarativeVMEMetaObject(), QDeclarativeEnginePrivate::registerCompositeType(), QDeclarativeDomDocument::rootObject(), QDeclarativeVME::run(), QDeclarativeOpenMetaObject::setCached(), QDeclarativeContextData::setIdPropertyData(), QDeclarativeDomValue::toBinding(), QDeclarativeDomValue::toLiteral(), QDeclarativeDomValue::toObject(), QDeclarativeDomValue::toValueInterceptor(), QDeclarativeDomValue::toValueSource(), TypeNameData::TypeNameData(), QDeclarativeDomProperty::value(), and QDeclarativeDomList::values().
 {
     Q_ASSERT(refCount > 0);
     ++refCount;
 }
release()
void QDeclarativeRefCount::release ()
Definition at line 61 of file qdeclarativerefcount.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), QDeclarativeCompiler::buildObject(), QDeclarativeDataBlob::cancelAllWaitingFor(), QDeclarativeScriptParser::clear(), QDeclarativeComponentPrivate::clear(), QDeclarativePropertyCache::clear(), QDeclarativeTypeData::compile(), QDeclarativeBinding::createBinding(), QDeclarativeEnginePrivate::createCache(), QDeclarativeContextData::destroy(), QDeclarativeTypeData::done(), QDeclarativeComponentPrivate::fromTypeData(), QDeclarativeExpressionPrivate::init(), QDeclarativeDomDocument::load(), QDeclarativeDataLoader::networkReplyFinished(), QDeclarativeDataBlob::notifyComplete(), QDeclarativeProperty::operator=(), QDeclarativeImports::populateCache(), qmlExecuteDeferred(), DocumentImpl::release(), QDeclarativeOpenMetaObject::setCached(), QDeclarativeTypeNameCache::Data::~Data(), QDeclarativeParser::Object::~Object(), QDeclarativeParser::Property::~Property(), QDeclarativeCompiledBindingsPrivate::~QDeclarativeCompiledBindingsPrivate(), QDeclarativeCompiledData::~QDeclarativeCompiledData(), QDeclarativeDomBasicValuePrivate::~QDeclarativeDomBasicValuePrivate(), QDeclarativeDomDocumentPrivate::~QDeclarativeDomDocumentPrivate(), QDeclarativeDomValuePrivate::~QDeclarativeDomValuePrivate(), QDeclarativeOpenMetaObject::~QDeclarativeOpenMetaObject(), QDeclarativeOpenMetaObjectType::~QDeclarativeOpenMetaObjectType(), QDeclarativeProperty::~QDeclarativeProperty(), QDeclarativeQtScriptExpression::~QDeclarativeQtScriptExpression(), QDeclarativeTypeData::~QDeclarativeTypeData(), QDeclarativeVMEMetaObject::~QDeclarativeVMEMetaObject(), and TypeNameData::~TypeNameData().
 {
     Q_ASSERT(refCount > 0);
     --refCount;
     if (refCount == 0)
         delete this;
 }
Properties
refCount
int QDeclarativeRefCount::refCount private
Definition at line 73 of file qdeclarativerefcount_p.h.
Referenced by addref(), and release().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativerefcount_p.h
/src/declarative/qml/qdeclarativerefcount.cpp