Qt 4.8: QVGImagePool Class Reference
QVGImagePool Class Reference
#include <qvgimagepool_p.h>
Public Functions
virtual VGImage createImageForPixmap (VGImageFormat format, VGint width, VGint height, VGbitfield allowedQuality, QVGPixmapData *data)
virtual VGImage createPermanentImage (VGImageFormat format, VGint width, VGint height, VGbitfield allowedQuality)
virtual VGImage createTemporaryImage (VGImageFormat format, VGint width, VGint height, VGbitfield allowedQuality, QVGPixmapData *keepData=0)
virtual void detachImage (QVGPixmapData *data)
virtual void hibernate ()
QVGImagePool ()
virtual bool reclaimSpace (VGImageFormat format, VGint width, VGint height, QVGPixmapData *data)
virtual void releaseImage (QVGPixmapData *data, VGImage image)
virtual void useImage (QVGPixmapData *data)
virtual ~QVGImagePool ()
Static Public Functions
static QVGImagePool * instance ()
static void setImagePool (QVGImagePool *pool)
Protected Functions
void moveToHeadOfLRU (QVGPixmapData *data)
QVGPixmapData * pixmapLRU ()
void removeFromLRU (QVGPixmapData *data)
Properties
QScopedPointer< QVGImagePoolPrivate > d_ptr
Detailed Description
Definition at line 64 of file qvgimagepool_p.h.
Constructors and Destructors
QVGImagePool()
QVGImagePool::QVGImagePool ()
Definition at line 58 of file qvgimagepool.cpp.
Referenced by instance().
     : d_ptr(new QVGImagePoolPrivate())
 {
 }
~QVGImagePool()
QVGImagePool::~QVGImagePool () virtual
Definition at line 63 of file qvgimagepool.cpp.
 {
 }
Functions
createImageForPixmap()
VGImage QVGImagePool::createImageForPixmap (VGImageFormat format, VGint width, VGint height, VGbitfield allowedQuality, QVGPixmapData * data) virtual
Definition at line 97 of file qvgimagepool.cpp.
Referenced by QVGPixmapData::toVGImage().
 {
     VGImage image;
     do {
         image = vgCreateImage(format, width, height, allowedQuality);
         if (image != VG_INVALID_HANDLE) {
             if (data)
                 moveToHeadOfLRU(data);
             return image;
         }
     } while (reclaimSpace(format, width, height, data));
     qWarning("QVGImagePool: cannot reclaim sufficient space for a %dx%d pixmap",
              width, height);
     return VG_INVALID_HANDLE;
 }
createPermanentImage()
VGImage QVGImagePool::createPermanentImage (VGImageFormat format, VGint width, VGint height, VGbitfield allowedQuality) virtual
Definition at line 116 of file qvgimagepool.cpp.
Referenced by drawImageTiled(), toVGImage(), toVGImageSubRect(), toVGImageWithOpacity(), and toVGImageWithOpacitySubRect().
 {
     VGImage image;
     do {
         image = vgCreateImage(format, width, height, allowedQuality);
         if (image != VG_INVALID_HANDLE)
             return image;
     } while (reclaimSpace(format, width, height, 0));
     qWarning("QVGImagePool: cannot reclaim sufficient space for a %dx%d image",
              width, height);
     return VG_INVALID_HANDLE;
 }
createTemporaryImage()
VGImage QVGImagePool::createTemporaryImage (VGImageFormat format, VGint width, VGint height, VGbitfield allowedQuality, QVGPixmapData * keepData = 0) virtual
Definition at line 81 of file qvgimagepool.cpp.
Referenced by QVGPixmapConvolutionFilter::draw(), QVGPixmapColorizeFilter::draw(), QVGPixmapDropShadowFilter::draw(), and QVGPixmapBlurFilter::draw().
 {
     VGImage image;
     do {
         image = vgCreateImage(format, width, height, allowedQuality);
         if (image != VG_INVALID_HANDLE)
             return image;
     } while (reclaimSpace(format, width, height, keepData));
     qWarning("QVGImagePool: cannot reclaim sufficient space for a %dx%d temporary image",
              width, height);
     return VG_INVALID_HANDLE;
 }
detachImage()
void QVGImagePool::detachImage (QVGPixmapData * data) virtual
Definition at line 144 of file qvgimagepool.cpp.
Referenced by QVGPixmapData::detachImageFromPool().
 {
     removeFromLRU(data);
 }
hibernate()
void QVGImagePool::hibernate () virtual
Definition at line 176 of file qvgimagepool.cpp.
Referenced by QVGGraphicsSystem::createWindowSurface(), and qt_vg_hibernate_pixmaps().
 {
     Q_D(QVGImagePool);
     QVGPixmapData *pd = d->lruLast;
     while (pd) {
         QVGPixmapData *prevLRU = pd->prevLRU;
         pd->inImagePool = false;
         pd->inLRU = false;
         pd->nextLRU = 0;
         pd->prevLRU = 0;
         pd->hibernate();
         pd = prevLRU;
     }
     d->lruFirst = 0;
     d->lruLast = 0;
 }
instance()
QVGImagePool * QVGImagePool::instance () static
Definition at line 67 of file qvgimagepool.cpp.
Referenced by QVGGraphicsSystem::createWindowSurface(), QVGPixmapData::destroyImages(), QVGPixmapData::detachImageFromPool(), QVGPixmapConvolutionFilter::draw(), QVGPixmapColorizeFilter::draw(), QVGPixmapDropShadowFilter::draw(), QVGPixmapBlurFilter::draw(), drawImageTiled(), qt_vg_hibernate_pixmaps(), QVGPixmapData::toVGImage(), toVGImage(), toVGImageSubRect(), toVGImageWithOpacity(), and toVGImageWithOpacitySubRect().
 {
     if (!qt_vg_image_pool)
         qt_vg_image_pool = new QVGImagePool();
     return qt_vg_image_pool;
 }
moveToHeadOfLRU()
void QVGImagePool::moveToHeadOfLRU (QVGPixmapData * data) protected
Definition at line 193 of file qvgimagepool.cpp.
Referenced by createImageForPixmap(), reclaimSpace(), and useImage().
 {
     Q_D(QVGImagePool);
     if (data->inLRU) {
         if (!data->prevLRU)
             return;     // Already at the head of the list.
         removeFromLRU(data);
     }
     data->inLRU = true;
     data->nextLRU = d->lruFirst;
     data->prevLRU = 0;
     if (d->lruFirst)
         d->lruFirst->prevLRU = data;
     else
         d->lruLast = data;
     d->lruFirst = data;
 }
pixmapLRU()
QVGPixmapData * QVGImagePool::pixmapLRU () protected
Definition at line 227 of file qvgimagepool.cpp.
Referenced by reclaimSpace().
 {
     Q_D(QVGImagePool);
     return d->lruLast;
 }
reclaimSpace()
bool QVGImagePool::reclaimSpace (VGImageFormat format, VGint width, VGint height, QVGPixmapData * data) virtual
Definition at line 149 of file qvgimagepool.cpp.
Referenced by createImageForPixmap(), createPermanentImage(), and createTemporaryImage().
 {
     Q_UNUSED(format);   // For future use in picking the best image to eject.
     Q_UNUSED(width);
     Q_UNUSED(height);
     bool succeeded = false;
     bool wasInLRU = false;
     if (data) {
         wasInLRU = data->inLRU;
         moveToHeadOfLRU(data);
     }
     QVGPixmapData *lrudata = pixmapLRU();
     if (lrudata && lrudata != data) {
         lrudata->reclaimImages();
         succeeded = true;
     }
     if (data && !wasInLRU)
         removeFromLRU(data);
     return succeeded;
 }
releaseImage()
void QVGImagePool::releaseImage (QVGPixmapData * data, VGImage image) virtual
Definition at line 131 of file qvgimagepool.cpp.
Referenced by QVGPixmapData::destroyImages(), QVGPixmapConvolutionFilter::draw(), QVGPixmapColorizeFilter::draw(), QVGPixmapDropShadowFilter::draw(), and QVGPixmapBlurFilter::draw().
 {
     // Very simple strategy at the moment: just destroy the image.
     if (data)
         removeFromLRU(data);
     vgDestroyImage(image);
 }
removeFromLRU()
void QVGImagePool::removeFromLRU (QVGPixmapData * data) protected
Definition at line 211 of file qvgimagepool.cpp.
Referenced by detachImage(), moveToHeadOfLRU(), reclaimSpace(), and releaseImage().
 {
     Q_D(QVGImagePool);
     if (!data->inLRU)
         return;
     if (data->nextLRU)
         data->nextLRU->prevLRU = data->prevLRU;
     else
         d->lruLast = data->prevLRU;
     if (data->prevLRU)
         data->prevLRU->nextLRU = data->nextLRU;
     else
         d->lruFirst = data->nextLRU;
     data->inLRU = false;
 }
setImagePool()
void QVGImagePool::setImagePool (QVGImagePool * pool) static
Definition at line 74 of file qvgimagepool.cpp.
 {
     if (qt_vg_image_pool != pool)
         delete qt_vg_image_pool;
     qt_vg_image_pool = pool;
 }
useImage()
void QVGImagePool::useImage (QVGPixmapData * data) virtual
Definition at line 139 of file qvgimagepool.cpp.
Referenced by QVGPixmapData::toVGImage().
 {
     moveToHeadOfLRU(data);
 }
Properties
d_ptr
QScopedPointer<QVGImagePoolPrivate> QVGImagePool::d_ptr private
Definition at line 149 of file qvgimagepool_p.h.
The documentation for this class was generated from the following files:
/src/openvg/qvgimagepool_p.h
/src/openvg/qvgimagepool.cpp