Qt 4.8: FxListItem Class Reference
FxListItem Class Reference
Public Functions
bool contains (qreal x, qreal y) const
qreal endPosition () const
FxListItem (QDeclarativeItem *i, QDeclarativeListView *v)
qreal itemPosition () const
qreal itemSize () const
qreal position () const
qreal sectionSize () const
void setPosition (qreal pos)
void setSize (qreal size)
qreal size () const
~FxListItem ()
Public Variables
QDeclarativeListViewAttached * attached
int index
QDeclarativeItem * item
QDeclarativeItem * section
QDeclarativeListView * view
Detailed Description
Definition at line 98 of file qdeclarativelistview.cpp.
Constructors and Destructors
FxListItem()
FxListItem::FxListItem (QDeclarativeItem * i, QDeclarativeListView * v) inline
Definition at line 101 of file qdeclarativelistview.cpp.
                                                              : item(i), section(0), view(v) {
         attached = static_cast<QDeclarativeListViewAttached*>(qmlAttachedPropertiesObject<QDeclarativeListView>(item));
         if (attached)
             attached->setView(view);
     }
~FxListItem()
FxListItem::~FxListItem () inline
Definition at line 106 of file qdeclarativelistview.cpp.
 {}
Functions
contains()
bool FxListItem::contains (qreal x, qreal y) const inline
Definition at line 176 of file qdeclarativelistview.cpp.
Referenced by QDeclarativeListView::indexAt().
{
         return (x >= item->x() && x < item->x() + item->width() &&
                 y >= item->y() && y < item->y() + item->height());
     }
endPosition()
qreal FxListItem::endPosition () const inline
Definition at line 138 of file qdeclarativelistview.cpp.
Referenced by QDeclarativeListViewPrivate::endPositionAt(), QDeclarativeListViewPrivate::firstVisibleItem(), QDeclarativeListViewPrivate::positionViewAtIndex(), QDeclarativeListViewPrivate::refill(), and QDeclarativeListViewPrivate::snapItemAt().
{
         if (view->orientation() == QDeclarativeListView::Vertical) {
             return item->y() + (item->height() >= 1.0 ? item->height() : 1) - 1;
         } else {
             return (view->effectiveLayoutDirection() == Qt::RightToLeft
                     ? -item->width()-item->x() + (item->width() >= 1.0 ? item->width() : 1)
                     : item->x() + (item->width() >= 1.0 ? item->width() : 1)) - 1;
         }
     }
itemPosition()
qreal FxListItem::itemPosition () const inline
Definition at line 118 of file qdeclarativelistview.cpp.
{
         if (view->orientation() == QDeclarativeListView::Vertical)
             return item->y();
         else
             return (view->effectiveLayoutDirection() == Qt::RightToLeft ? -item->width()-item->x() : item->x());
     }
itemSize()
qreal FxListItem::itemSize () const inline
Definition at line 130 of file qdeclarativelistview.cpp.
{
         return (view->orientation() == QDeclarativeListView::Vertical ? item->height() : item->width());
     }
position()
qreal FxListItem::position () const inline
Definition at line 107 of file qdeclarativelistview.cpp.
Referenced by QDeclarativeListViewPrivate::createSection(), QDeclarativeListViewPrivate::fixup(), QDeclarativeListView::itemsInserted(), QDeclarativeListView::itemsMoved(), QDeclarativeListView::itemsRemoved(), QDeclarativeListViewPrivate::positionAt(), QDeclarativeListViewPrivate::positionViewAtIndex(), QDeclarativeListViewPrivate::refill(), and QDeclarativeListViewPrivate::snapItemAt().
{
         if (section) {
             if (view->orientation() == QDeclarativeListView::Vertical)
                 return section->y();
             else
                 return (view->effectiveLayoutDirection() == Qt::RightToLeft ? -section->width()-section->x() : section->x());
         } else {
             return itemPosition();
         }
     }
sectionSize()
qreal FxListItem::sectionSize () const inline
Definition at line 133 of file qdeclarativelistview.cpp.
{
         if (section)
             return (view->orientation() == QDeclarativeListView::Vertical ? section->height() : section->width());
         return 0.0;
     }
setPosition()
void FxListItem::setPosition (qreal pos) inline
Definition at line 147 of file qdeclarativelistview.cpp.
Referenced by QDeclarativeListViewPrivate::createSection(), QDeclarativeListView::itemsInserted(), QDeclarativeListView::itemsMoved(), QDeclarativeListViewPrivate::layout(), and QDeclarativeListViewPrivate::refill().
{
         if (view->orientation() == QDeclarativeListView::Vertical) {
             if (section) {
                 section->setY(pos);
                 pos += section->height();
             }
             item->setY(pos);
         } else {
             if (view->effectiveLayoutDirection() == Qt::RightToLeft) {
                 if (section) {
                     section->setX(-section->width()-pos);
                     pos += section->width();
                 }
                 item->setX(-item->width()-pos);
             } else {
                 if (section) {
                     section->setX(pos);
                     pos += section->width();
                 }
                 item->setX(pos);
             }
         }
     }
setSize()
void FxListItem::setSize (qreal size) inline
Definition at line 170 of file qdeclarativelistview.cpp.
{
         if (view->orientation() == QDeclarativeListView::Vertical)
             item->setHeight(size);
         else
             item->setWidth(size);
     }
size()
qreal FxListItem::size () const inline
Definition at line 124 of file qdeclarativelistview.cpp.
Referenced by QDeclarativeListView::itemsInserted(), QDeclarativeListView::itemsMoved(), QDeclarativeListView::itemsRemoved(), QDeclarativeListViewPrivate::layout(), QDeclarativeListViewPrivate::positionViewAtIndex(), QDeclarativeListViewPrivate::refill(), and QDeclarativeListViewPrivate::snapItemAt().
{
         if (section)
             return (view->orientation() == QDeclarativeListView::Vertical ? item->height()+section->height() : item->width()+section->width());
         else
             return (view->orientation() == QDeclarativeListView::Vertical ? item->height() : item->width());
     }
Properties
attached
QDeclarativeListViewAttached* FxListItem::attached
Definition at line 184 of file qdeclarativelistview.cpp.
Referenced by QDeclarativeListViewPrivate::createItem(), QDeclarativeListViewPrivate::createSection(), QDeclarativeListView::destroyRemoved(), QDeclarativeListView::itemsInserted(), QDeclarativeListView::itemsRemoved(), QDeclarativeListViewPrivate::refill(), QDeclarativeListViewPrivate::sectionAt(), and QDeclarativeListViewPrivate::updateCurrent().
index
int FxListItem::index
Definition at line 185 of file qdeclarativelistview.cpp.
Referenced by QDeclarativeListViewPrivate::checkVisible(), QDeclarativeListViewPrivate::createItem(), QDeclarativeListView::destroyRemoved(), QDeclarativeListViewPrivate::firstVisibleItem(), QDeclarativeListViewPrivate::fixup(), QDeclarativeListView::indexAt(), QDeclarativeListViewPrivate::itemBefore(), QDeclarativeListView::itemsInserted(), QDeclarativeListView::itemsMoved(), QDeclarativeListView::itemsRemoved(), QDeclarativeListViewPrivate::lastVisibleIndex(), QDeclarativeListViewPrivate::mapFromModel(), QDeclarativeListViewPrivate::refill(), QDeclarativeListViewPrivate::snapItemAt(), and QDeclarativeListViewPrivate::visibleItem().
item
QDeclarativeItem* FxListItem::item
Definition at line 181 of file qdeclarativelistview.cpp.
Referenced by QDeclarativeListViewPrivate::createItem(), QDeclarativeListView::itemsInserted(), QDeclarativeListView::itemsMoved(), QDeclarativeListViewPrivate::layout(), QDeclarativeListViewPrivate::releaseItem(), and QDeclarativeListViewPrivate::updateCurrent().
section
QDeclarativeItem* FxListItem::section
Definition at line 182 of file qdeclarativelistview.cpp.
Referenced by QDeclarativeListViewPrivate::createSection(), and QDeclarativeListViewPrivate::releaseItem().
view
QDeclarativeListView* FxListItem::view
Definition at line 183 of file qdeclarativelistview.cpp.
The documentation for this class was generated from the following file:
/src/declarative/graphicsitems/qdeclarativelistview.cpp