Qt 4.8: QMetaMethod Class Reference
QMetaMethod Class Reference
The QMetaMethod class provides meta-data about a member function.
#include <qmetaobject.h>
Public Types
enum Access { Private, Protected, Public }
This enum describes the access level of a method, following the conventions used in C++.
enum Attributes { Compatibility = 0x1, Cloned = 0x2, Scriptable = 0x4 }
enum MethodType { Method, Signal, Slot, Constructor }
Public Functions
Access access () const
Returns the access specification of this method (private, protected, or public).
int attributes () const
const QMetaObject * enclosingMetaObject () const
bool invoke (QObject *object, Qt::ConnectionType connectionType, QGenericReturnArgument returnValue, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument()) const
Invokes this method on the object object.
bool invoke (QObject *object, QGenericReturnArgument returnValue, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument()) const
bool invoke (QObject *object, Qt::ConnectionType connectionType, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument()) const
bool invoke (QObject *object, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument()) const
int methodIndex () const
Returns this method's index.
MethodType methodType () const
Returns the type of this method (signal, slot, or method).
QList< QByteArray > parameterNames () const
Returns a list of parameter names.
QList< QByteArray > parameterTypes () const
Returns a list of parameter types.
QMetaMethod ()
int revision () const
Returns the method revision if one was specified by Q_REVISION, otherwise returns 0.
const char * signature () const
Returns the signature of this method (e.g., setValue(double)).
const char * tag () const
Returns the tag associated with this method.
const char * typeName () const
Returns the return type of this method, or an empty string if the return type is void.
Properties
uint handle
const QMetaObject * mobj
Friends
struct QMetaObject
struct QMetaObjectPrivate
class QObject
Detailed Description
The QMetaMethod class provides meta-data about a member function.
A QMetaMethod has a methodType(), a signature(), a list of parameterTypes() and parameterNames(), a return typeName(), a tag(), and an access() specifier. You can use invoke() to invoke the method on an arbitrary QObject.
A method will only be registered with the meta-object system if it is a slot, a signal, or declared with the Q_INVOKABLE macro. Constructors can also be registered with Q_INVOKABLE.
See also
QMetaObject, QMetaEnum, QMetaProperty, {Qt's Property System}
Definition at line 56 of file qmetaobject.h.
Enumerations
Access
enum QMetaMethod::Access
This enum describes the access level of a method, following the conventions used in C++.
Private
Protected
Public
Enumerator
Private
Protected
Public
Definition at line 66 of file qmetaobject.h.
 { Private, Protected, Public };
Attributes
enum QMetaMethod::Attributes
Warning
This function is not part of the public interface.
Compatibility
Cloned
Scriptable
Enumerator
Compatibility
Cloned
Scriptable
Definition at line 70 of file qmetaobject.h.
 { Compatibility = 0x1, Cloned = 0x2, Scriptable = 0x4 };
MethodType
enum QMetaMethod::MethodType
Method The function is a plain member function.
Signal The function is a signal.
Slot The function is a slot.
Constructor The function is a constructor.
Enumerator
Method
Signal
Slot
Constructor
Definition at line 68 of file qmetaobject.h.
 { Method, Signal, Slot, Constructor };
Constructors and Destructors
QMetaMethod()
QMetaMethod::QMetaMethod () inline
Warning
This function is not part of the public interface.
Definition at line 59 of file qmetaobject.h.
 : mobj(0),handle(0) {}
Functions
access()
QMetaMethod::Access QMetaMethod::access () const
Returns the access specification of this method (private, protected, or public).
Signals are always protected, meaning that you can only emit them from the class or from a subclass.
See also
methodType()
Definition at line 1496 of file qmetaobject.cpp.
Referenced by QAccessibleObjectPrivate::actionList(), QMetaObjectBuilder::addConstructor(), QMetaObjectBuilder::addMetaObject(), QMetaObjectBuilder::addMethod(), QDeclarativePropertyCache::append(), classIDL(), QDeclarativePropertyCache::create(), findSlot(), generateInterfaceXml(), QScript::hasMethodAccess(), and QTest::isValidSlot().
 {
     if (!mobj)
         return Private;
     return (QMetaMethod::Access)(mobj->d.data[handle + 4] & AccessMask);
 }
attributes()
int QMetaMethod::attributes () const
Warning
This function is not part of the public interface.
Definition at line 1443 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addConstructor(), QMetaObjectBuilder::addMethod(), check_and_warn_compat(), classIDL(), QMetaObject::connectSlotsByName(), findSlot(), generateInterfaceXml(), QScript::QtFunction::mostGeneralMethod(), qax_generateDocumentation(), and QStateMachinePrivate::registerSignalTransition().
 {
     if (!mobj)
         return false;
     return ((mobj->d.data[handle + 4])>>4);
 }
enclosingMetaObject()
const QMetaObject * QMetaMethod::enclosingMetaObject () const inline
Warning
This function is not part of the public interface.
Definition at line 75 of file qmetaobject.h.
Referenced by QMetaObject::connectSlotsByName().
 { return mobj; }
invoke() [1/4]
bool QMetaMethod::invoke (QObject * object, Qt::ConnectionType connectionType, QGenericReturnArgument returnValue, QGenericArgument val0 = QGenericArgument(0), QGenericArgument val1 = QGenericArgument(), QGenericArgument val2 = QGenericArgument(), QGenericArgument val3 = QGenericArgument(), QGenericArgument val4 = QGenericArgument(), QGenericArgument val5 = QGenericArgument(), QGenericArgument val6 = QGenericArgument(), QGenericArgument val7 = QGenericArgument(), QGenericArgument val8 = QGenericArgument(), QGenericArgument val9 = QGenericArgument()) const
Invokes this method on the object object.
Returns true if the member could be invoked. Returns false if there is no such member or the parameters did not match.
The invocation can be either synchronous or asynchronous, depending on the connectionType:
If connectionType is Qt::DirectConnection, the member will be invoked immediately.
If connectionType is Qt::QueuedConnection, a QEvent will be posted and the member is invoked as soon as the application enters the main event loop.
If connectionType is Qt::AutoConnection, the member is invoked synchronously if object lives in the same thread as the caller; otherwise it will invoke the member asynchronously.
The return value of this method call is placed in returnValue. If the invocation is asynchronous, the return value cannot be evaluated. You can pass up to ten arguments (val0, val1, val2, val3, val4, val5, val6, val7, val8, and val9) to this method call.
QGenericArgument and QGenericReturnArgument are internal helper classes. Because signals and slots can be dynamically invoked, you must enclose the arguments using the Q_ARG() and Q_RETURN_ARG() macros. Q_ARG() takes a type name and a const reference of that type; Q_RETURN_ARG() takes a type name and a non-const reference.
To asynchronously invoke the animateClick() slot on a QPushButton:
int methodIndex = pushButton->metaObject()->indexOfMethod("animateClick()");
QMetaMethod method = metaObject->method(methodIndex);
method.invoke(pushButton, Qt::QueuedConnection);
With asynchronous method invocations, the parameters must be of types that are known to Qt's meta-object system, because Qt needs to copy the arguments to store them in an event behind the scenes. If you try to use a queued connection and get the error message
QMetaMethod::invoke: Unable to handle unregistered datatype 'MyType'
call qRegisterMetaType() to register the data type before you call QMetaMethod::invoke().
To synchronously invoke the compute(QString, int, double) slot on some arbitrary object obj retrieve its return value:
QString retVal;
QByteArray normalizedSignature = QMetaObject::normalizedSignature("compute(QString, int, double)");
int methodIndex = obj->metaObject()->indexOfMethod(normalizedSignature);
QMetaMethod method = metaObject->method(methodIndex);
method.invoke(obj,
              Qt::DirectConnection,
              Q_RETURN_ARG(QString, retVal),
              Q_ARG(QString, "sqrt"),
              Q_ARG(int, 42),
              Q_ARG(double, 9.7));
QMetaObject::normalizedSignature() is used here to ensure that the format of the signature is what invoke() expects. E.g. extra whitespace is removed.
If the "compute" slot does not take exactly one QString, one int and one double in the specified order, the call will fail.
Warning
this method will not test the validity of the arguments: object must be an instance of the class of the QMetaObject of which this QMetaMethod has been constructed with. The arguments must have the same type as the ones expected by the method, else, the behaviour is undefined.
See also
Q_ARG(), Q_RETURN_ARG(), qRegisterMetaType(), QMetaObject::invokeMethod()
Definition at line 1583 of file qmetaobject.cpp.
Referenced by QGraphicsScene::addItem(), QMetaObject::invokeMethod(), QTest::invokeMethod(), QDeclarativeKeysAttached::keyPressed(), and QGraphicsScenePrivate::markDirty().
 {
     if (!object || !mobj)
         return false;
     Q_ASSERT(mobj->cast(object));
     // check return type
     if (returnValue.data()) {
         const char *retType = typeName();
         if (qstrcmp(returnValue.name(), retType) != 0) {
             // normalize the return value as well
             // the trick here is to make a function signature out of the return type
             // so that we can call normalizedSignature() and avoid duplicating code
             QByteArray unnormalized;
             int len = qstrlen(returnValue.name());
             unnormalized.reserve(len + 3);
             unnormalized = "_(";        // the function is called "_"
             unnormalized.append(returnValue.name());
             unnormalized.append(')');
             QByteArray normalized = QMetaObject::normalizedSignature(unnormalized.constData());
             normalized.truncate(normalized.length() - 1); // drop the ending ')'
             if (qstrcmp(normalized.constData() + 2, retType) != 0)
                 return false;
         }
     }
     // check argument count (we don't allow invoking a method if given too few arguments)
     const char *typeNames[] = {
         returnValue.name(),
         val0.name(),
         val1.name(),
         val2.name(),
         val3.name(),
         val4.name(),
         val5.name(),
         val6.name(),
         val7.name(),
         val8.name(),
         val9.name()
     };
     int paramCount;
     for (paramCount = 1; paramCount < MaximumParamCount; ++paramCount) {
         if (qstrlen(typeNames[paramCount]) <= 0)
             break;
     }
     int metaMethodArgumentCount = 0;
     {
         // based on QMetaObject::parameterNames()
         const char *names = mobj->d.stringdata + mobj->d.data[handle + 1];
         if (*names == 0) {
             // do we have one or zero arguments?
             const char *signature = mobj->d.stringdata + mobj->d.data[handle];
             while (*signature && *signature != '(')
                 ++signature;
             if (*++signature != ')')
                 ++metaMethodArgumentCount;
         } else {
             --names;
             do {
                 ++names;
                 while (*names && *names != ',')
                     ++names;
                 ++metaMethodArgumentCount;
             } while (*names);
         }
     }
     if (paramCount <= metaMethodArgumentCount)
         return false;
     // check connection type
     QThread *currentThread = QThread::currentThread();
     QThread *objectThread = object->thread();
     if (connectionType == Qt::AutoConnection) {
         connectionType = currentThread == objectThread
                          ? Qt::DirectConnection
                          : Qt::QueuedConnection;
     }
 #ifdef QT_NO_THREAD
     if (connectionType == Qt::BlockingQueuedConnection) {
         connectionType = Qt::DirectConnection;
     }
 #endif
     // invoke!
     void *param[] = {
         returnValue.data(),
         val0.data(),
         val1.data(),
         val2.data(),
         val3.data(),
         val4.data(),
         val5.data(),
         val6.data(),
         val7.data(),
         val8.data(),
         val9.data()
     };
     // recompute the methodIndex by reversing the arithmetic in QMetaObject::property()
     int idx_relative = ((handle - priv(mobj->d.data)->methodData) / 5);
     int idx_offset =  mobj->methodOffset();
     QObjectPrivate::StaticMetaCallFunction callFunction =
         (QMetaObjectPrivate::get(mobj)->revision >= 6 && mobj->d.extradata)
         ? reinterpret_cast<const QMetaObjectExtraData *>(mobj->d.extradata)->static_metacall : 0;
     if (connectionType == Qt::DirectConnection) {
         if (callFunction) {
             callFunction(object, QMetaObject::InvokeMetaMethod, idx_relative, param);
             return true;
         } else {
             return QMetaObject::metacall(object, QMetaObject::InvokeMetaMethod, idx_relative + idx_offset, param) < 0;
         }
     } else if (connectionType == Qt::QueuedConnection) {
         if (returnValue.data()) {
             qWarning("QMetaMethod::invoke: Unable to invoke methods with return values in "
                      "queued connections");
             return false;
         }
         int nargs = 1; // include return type
         void **args = (void **) qMalloc(paramCount * sizeof(void *));
         Q_CHECK_PTR(args);
         int *types = (int *) qMalloc(paramCount * sizeof(int));
         Q_CHECK_PTR(types);
         types[0] = 0; // return type
         args[0] = 0;
         for (int i = 1; i < paramCount; ++i) {
             types[i] = QMetaType::type(typeNames[i]);
             if (types[i]) {
                 args[i] = QMetaType::construct(types[i], param[i]);
                 ++nargs;
             } else if (param[i]) {
                 qWarning("QMetaMethod::invoke: Unable to handle unregistered datatype '%s'",
                          typeNames[i]);
                 for (int x = 1; x < i; ++x) {
                     if (types[x] && args[x])
                         QMetaType::destroy(types[x], args[x]);
                 }
                 qFree(types);
                 qFree(args);
                 return false;
             }
         }
         QCoreApplication::postEvent(object, new QMetaCallEvent(idx_offset, idx_relative, callFunction,
                                                         0, -1, nargs, types, args));
     } else { // blocking queued connection
 #ifndef QT_NO_THREAD
         if (currentThread == objectThread) {
             qWarning("QMetaMethod::invoke: Dead lock detected in "
                         "BlockingQueuedConnection: Receiver is %s(%p)",
                         mobj->className(), object);
         }
         QSemaphore semaphore;
         QCoreApplication::postEvent(object, new QMetaCallEvent(idx_offset, idx_relative, callFunction,
                                                         0, -1, 0, 0, param, &semaphore));
         semaphore.acquire();
 #endif // QT_NO_THREAD
     }
     return true;
 }
invoke() [2/4]
bool QMetaMethod::invoke (QObject * object, QGenericReturnArgument returnValue, QGenericArgument val0 = QGenericArgument(0), QGenericArgument val1 = QGenericArgument(), QGenericArgument val2 = QGenericArgument(), QGenericArgument val3 = QGenericArgument(), QGenericArgument val4 = QGenericArgument(), QGenericArgument val5 = QGenericArgument(), QGenericArgument val6 = QGenericArgument(), QGenericArgument val7 = QGenericArgument(), QGenericArgument val8 = QGenericArgument(), QGenericArgument val9 = QGenericArgument()) const inline
Definition at line 90 of file qmetaobject.h.
     {
         return invoke(object, Qt::AutoConnection, returnValue,
                       val0, val1, val2, val3, val4, val5, val6, val7, val8, val9);
     }
invoke() [3/4]
bool QMetaMethod::invoke (QObject * object, Qt::ConnectionType connectionType, QGenericArgument val0 = QGenericArgument(0), QGenericArgument val1 = QGenericArgument(), QGenericArgument val2 = QGenericArgument(), QGenericArgument val3 = QGenericArgument(), QGenericArgument val4 = QGenericArgument(), QGenericArgument val5 = QGenericArgument(), QGenericArgument val6 = QGenericArgument(), QGenericArgument val7 = QGenericArgument(), QGenericArgument val8 = QGenericArgument(), QGenericArgument val9 = QGenericArgument()) const inline
Definition at line 106 of file qmetaobject.h.
     {
         return invoke(object, connectionType, QGenericReturnArgument(),
                       val0, val1, val2, val3, val4, val5, val6, val7, val8, val9);
     }
invoke() [4/4]
bool QMetaMethod::invoke (QObject * object, QGenericArgument val0 = QGenericArgument(0), QGenericArgument val1 = QGenericArgument(), QGenericArgument val2 = QGenericArgument(), QGenericArgument val3 = QGenericArgument(), QGenericArgument val4 = QGenericArgument(), QGenericArgument val5 = QGenericArgument(), QGenericArgument val6 = QGenericArgument(), QGenericArgument val7 = QGenericArgument(), QGenericArgument val8 = QGenericArgument(), QGenericArgument val9 = QGenericArgument()) const inline
Definition at line 122 of file qmetaobject.h.
     {
         return invoke(object, Qt::AutoConnection, QGenericReturnArgument(),
                       val0, val1, val2, val3, val4, val5, val6, val7, val8, val9);
     }
methodIndex()
int QMetaMethod::methodIndex () const
Returns this method's index.
Since
4.6
Definition at line 1458 of file qmetaobject.cpp.
Referenced by QDeclarativeBoundSignal::disconnect(), QDeclarativeBoundSignal::index(), QDeclarativeBoundSignal::init(), and QDeclarativePropertyCache::Data::load().
 {
     if (!mobj)
         return -1;
     return ((handle - priv(mobj->d.data)->methodData) / 5) + mobj->methodOffset();
 }
methodType()
QMetaMethod::MethodType QMetaMethod::methodType () const
Returns the type of this method (signal, slot, or method).
See also
access()
Definition at line 1508 of file qmetaobject.cpp.
Referenced by QAccessibleObjectPrivate::actionList(), QMetaObjectBuilder::addConstructor(), QMetaObjectBuilder::addMetaObject(), QMetaObjectBuilder::addMethod(), QDeclarativePropertyCache::append(), check_and_warn_compat(), classIDL(), QObject::connect(), QMetaObject::connectSlotsByName(), QObject::disconnect(), QAxBase::dynamicCallHelper(), findSlot(), QScript::functionConnect(), QScript::functionDisconnect(), generateInterfaceXml(), QScript::hasMethodAccess(), QAxServerBase::internalConnect(), QAxBase::internalInvoke(), QAxServerBase::Invoke(), QAxEventSink::Invoke(), QTest::isValidSlot(), QDeclarativePropertyCache::Data::load(), QMetaObjectPrivate::memberIndexes(), QDBusInterfacePrivate::metacall(), QDeclarativeProxyMetaObject::metaCall(), qax_generateDocumentation(), QAxServerBase::qt_metacall(), and QDBusAbstractAdaptor::setAutoRelaySignals().
 {
     if (!mobj)
         return QMetaMethod::Method;
     return (QMetaMethod::MethodType)((mobj->d.data[handle + 4] & MethodTypeMask)>>2);
 }
parameterNames()
QList< QByteArray > QMetaMethod::parameterNames () const
Returns a list of parameter names.
See also
parameterTypes(), signature()
Definition at line 1367 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addConstructor(), QMetaObjectBuilder::addMethod(), classIDL(), generateInterfaceXml(), qax_generateDocumentation(), QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters(), QScriptContextInfoPrivate::QScriptContextInfoPrivate(), and QDeclarativeEngineDebugService::setMethodBody().
 {
     QList<QByteArray> list;
     if (!mobj)
         return list;
     const char *names =  mobj->d.stringdata + mobj->d.data[handle + 1];
     if (*names == 0) {
         // do we have one or zero arguments?
         const char *signature = mobj->d.stringdata + mobj->d.data[handle];
         while (*signature && *signature != '(')
             ++signature;
         if (*++signature != ')')
             list += QByteArray();
     } else {
         --names;
         do {
             const char *begin = ++names;
             while (*names && *names != ',')
                 ++names;
             list += QByteArray(begin, names - begin);
         } while (*names);
     }
     return list;
 }
parameterTypes()
QList< QByteArray > QMetaMethod::parameterTypes () const
Returns a list of parameter types.
See also
parameterNames(), signature()
Definition at line 1339 of file qmetaobject.cpp.
Referenced by QDeclarativeObjectMethodScriptClass::callOverloaded(), QDeclarativeObjectMethodScriptClass::callPrecise(), QScript::callQtMethod(), classIDL(), QObject::connect(), QScript::QObjectConnectionManager::execute(), QStateMachinePrivate::handleTransitionSignal(), QSignalSpy::initArgs(), QTest::isValidSlot(), QDeclarativePropertyCache::Data::load(), qax_generateDocumentation(), qDBusParametersForMethod(), QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters(), QTest::qSignalDumperCallback(), QDeclarativeBoundSignal::qt_metacall(), and queued_activate().
 {
     QList<QByteArray> list;
     if (!mobj)
         return list;
     const char *signature = mobj->d.stringdata + mobj->d.data[handle];
     while (*signature && *signature != '(')
         ++signature;
     while (*signature && *signature != ')' && *++signature != ')') {
         const char *begin = signature;
         int level = 0;
         while (*signature && (level > 0 || *signature != ',') && *signature != ')') {
             if (*signature == '<')
                 ++level;
             else if (*signature == '>')
                 --level;
             ++signature;
         }
         list += QByteArray(begin, signature - begin);
     }
     return list;
 }
revision()
int QMetaMethod::revision () const
Returns the method revision if one was specified by Q_REVISION, otherwise returns 0.
Warning
This function is not part of the public interface.
Definition at line 1474 of file qmetaobject.cpp.
Referenced by QDeclarativeTypePrivate::init(), and QDeclarativePropertyCache::Data::load().
 {
     if (!mobj)
         return 0;
     if ((QMetaMethod::Access)(mobj->d.data[handle + 4] & MethodRevisioned)) {
         int offset = priv(mobj->d.data)->methodData
                      + priv(mobj->d.data)->methodCount * 5
                      + (handle - priv(mobj->d.data)->methodData) / 5;
         return mobj->d.data[offset];
     }
     return 0;
 }
signature()
const char * QMetaMethod::signature () const
Returns the signature of this method (e.g., setValue(double)).
See also
parameterTypes(), parameterNames()
Definition at line 1327 of file qmetaobject.cpp.
Referenced by QAccessibleObjectPrivate::actionList(), QMetaObjectBuilder::addConstructor(), QMetaObjectBuilder::addMethod(), QMetaObjectBuilder::addProperty(), QScript::QObjectConnectionManager::addSignalHandler(), QDeclarativePropertyCache::append(), QDeclarativeObjectMethodScriptClass::callOverloaded(), QScript::callQtMethod(), QDBusAbstractInterface::callWithArgumentList(), check_and_warn_compat(), classIDL(), QDeclarativeObjectMethodScriptClass::connect(), QObject::connect(), QDeclarativeProperty::connectNotifySignal(), ShaderEffectItem::connectPropertySignals(), QMetaObject::connectSlotsByName(), QDeclarativePropertyCache::create(), QDeclarativeObjectMethodScriptClass::disconnect(), QObject::disconnect(), QObject::dumpObjectInfo(), QAxBase::dynamicCallHelper(), QScript::QObjectConnectionManager::execute(), QDeclarativePropertyPrivate::findSignalByName(), findSlot(), for(), QScript::functionConnect(), QScript::functionDisconnect(), generateInterfaceXml(), QScript::QObjectDelegate::getOwnPropertyNames(), QStateMachinePrivate::handleTransitionSignal(), QDeclarativePropertyPrivate::initProperty(), QAxBase::internalInvoke(), QAxServerBase::Invoke(), QAxEventSink::Invoke(), QTest::isValidSlot(), QTest::memberName(), QScript::methodNameEquals(), QScript::methodNameLength(), QDeclarativePropertyCache::Data::name(), QScript::QtFunction::overloadedIndexes(), qax_generateDocumentation(), QMetaMethod_name(), QTest::qPrintDataTags(), QTest::qPrintTestSlots(), QTest::qSignalDumperCallback(), QTest::qSignalDumperCallbackSlot(), QDeclarativeBoundSignal::qt_metacall(), QAxServerBase::qt_metacall(), QDBusAdaptorConnector::relay(), QScript::QObjectConnectionManager::removeSignalHandler(), QDBusAbstractAdaptor::setAutoRelaySignals(), setupDBusInterface(), and QObjectPrivate::signalSignature().
 {
     if (!mobj)
         return 0;
     return mobj->d.stringdata + mobj->d.data[handle];
 }
tag()
const char * QMetaMethod::tag () const
Returns the tag associated with this method.
Tags are special macros recognized by moc that make it possible to add extra information about a method.
Tag information can be added in the following way in the function declaration:
#define THISISTESTTAG // tag text
...
private slots:
    THISISTESTTAG void testFunc();
and the information can be accessed by using:
MainWindow win;
win.show();
int functionIndex = win.metaObject()->indexOfSlot("testFunc()");
QMetaMethod mm = metaObject()->method(functionIndex);
qDebug() << mm.tag(); // prints THISISTESTTAG
For the moment, moc doesn't support any special tags.
Definition at line 1434 of file qmetaobject.cpp.
Referenced by QAccessibleObjectPrivate::actionList(), QMetaObjectBuilder::addConstructor(), QMetaObjectBuilder::addMethod(), QDBusAbstractInterface::callWithArgumentList(), findSlot(), and generateInterfaceXml().
 {
     if (!mobj)
         return 0;
     return mobj->d.stringdata + mobj->d.data[handle + 3];
 }
typeName()
const char * QMetaMethod::typeName () const
Returns the return type of this method, or an empty string if the return type is void.
Definition at line 1397 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addConstructor(), QMetaObjectBuilder::addMethod(), QScript::callQtMethod(), classIDL(), QAxBase::dynamicCallHelper(), findSlot(), generateInterfaceXml(), QAxBase::internalInvoke(), QTest::isValidSlot(), QDeclarativePropertyCache::Data::load(), QDBusInterfacePrivate::metacall(), qax_generateDocumentation(), and QAxServerBase::qt_metacall().
 {
     if (!mobj)
         return 0;
     return mobj->d.stringdata + mobj->d.data[handle + 2];
 }
Friends and Related Functions
QMetaObject
friend struct QMetaObject friend
Definition at line 141 of file qmetaobject.h.
QMetaObjectPrivate
friend struct QMetaObjectPrivate friend
Definition at line 142 of file qmetaobject.h.
QObject
friend class QObject friend
Definition at line 143 of file qmetaobject.h.
Properties
handle
uint QMetaMethod::handle private
Definition at line 140 of file qmetaobject.h.
Referenced by QMetaObject::constructor(), QMetaObjectPrivate::memberIndexes(), and QMetaObject::method().
mobj
const QMetaObject* QMetaMethod::mobj private
Definition at line 139 of file qmetaobject.h.
Referenced by QMetaObject::constructor(), QObject::disconnect(), QMetaObjectPrivate::memberIndexes(), and QMetaObject::method().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qmetaobject.h
/src/corelib/kernel/qmetaobject.cpp