Qt 4.8: QDeclarativeAnchorChanges Class Reference
QDeclarativeAnchorChanges Class Reference
#include <qdeclarativestateoperations_p.h>
Public Functions
virtual ActionList actions ()
QList< QDeclarativeAction > additionalActions ()
QDeclarativeAnchorSet * anchors ()
virtual bool changesBindings ()
virtual void clearBindings ()
virtual void copyOriginals (QDeclarativeActionEvent *)
virtual void execute (Reason reason=ActualChange)
virtual bool isReversable ()
virtual bool needsCopy ()
QDeclarativeItem * object () const
virtual bool override (QDeclarativeActionEvent *other)
QDeclarativeAnchorChanges (QObject *parent=0)
virtual void reverse (Reason reason=ActualChange)
virtual void rewind ()
virtual void saveCurrentValues ()
virtual void saveOriginals ()
virtual void saveTargetValues ()
void setObject (QDeclarativeItem *)
virtual QString typeName () const
~QDeclarativeAnchorChanges ()
Public Functions inherited from QDeclarativeStateOperation
QDeclarativeStateOperation (QObject *parent=0)
void setState (QDeclarativeState *state)
QDeclarativeState * state () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeActionEvent
virtual bool isRewindable ()
virtual ~QDeclarativeActionEvent ()
Properties
QDeclarativeAnchorSet * anchors
QDeclarativeItem * target
Additional Inherited Members
Public Types inherited from QDeclarativeStateOperation
typedef QList< QDeclarativeAction > ActionList
Public Types inherited from QDeclarativeActionEvent
enum Reason { ActualChange, FastForward }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QDeclarativeStateOperation
QDeclarativeStateOperation (QObjectPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 262 of file qdeclarativestateoperations_p.h.
Constructors and Destructors
QDeclarativeAnchorChanges()
QDeclarativeAnchorChanges::QDeclarativeAnchorChanges (QObject * parent = 0)
Definition at line 1075 of file qdeclarativestateoperations.cpp.
  : QDeclarativeStateOperation(*(new QDeclarativeAnchorChangesPrivate), parent)
 {
 }
~QDeclarativeAnchorChanges()
QDeclarativeAnchorChanges::~QDeclarativeAnchorChanges ()
Definition at line 1080 of file qdeclarativestateoperations.cpp.
 {
 }
Functions
actions()
QDeclarativeAnchorChanges::ActionList QDeclarativeAnchorChanges::actions () virtual
Reimplemented from QDeclarativeStateOperation.
Definition at line 1084 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorChanges);
     d->leftBinding = d->rightBinding = d->hCenterBinding = d->topBinding
                    = d->bottomBinding = d->vCenterBinding = d->baselineBinding = 0;
     d->leftProp = QDeclarativeProperty(d->target, QLatin1String("anchors.left"));
     d->rightProp = QDeclarativeProperty(d->target, QLatin1String("anchors.right"));
     d->hCenterProp = QDeclarativeProperty(d->target, QLatin1String("anchors.horizontalCenter"));
     d->topProp = QDeclarativeProperty(d->target, QLatin1String("anchors.top"));
     d->bottomProp = QDeclarativeProperty(d->target, QLatin1String("anchors.bottom"));
     d->vCenterProp = QDeclarativeProperty(d->target, QLatin1String("anchors.verticalCenter"));
     d->baselineProp = QDeclarativeProperty(d->target, QLatin1String("anchors.baseline"));
     QDeclarativeContext *ctxt = qmlContext(this);
     if (d->anchorSet->d_func()->usedAnchors & QDeclarativeAnchors::LeftAnchor) {
         d->leftBinding = new QDeclarativeBinding(d->anchorSet->d_func()->leftScript.script(), d->target, ctxt);
         d->leftBinding->setTarget(d->leftProp);
     }
     if (d->anchorSet->d_func()->usedAnchors & QDeclarativeAnchors::RightAnchor) {
         d->rightBinding = new QDeclarativeBinding(d->anchorSet->d_func()->rightScript.script(), d->target, ctxt);
         d->rightBinding->setTarget(d->rightProp);
     }
     if (d->anchorSet->d_func()->usedAnchors & QDeclarativeAnchors::HCenterAnchor) {
         d->hCenterBinding = new QDeclarativeBinding(d->anchorSet->d_func()->hCenterScript.script(), d->target, ctxt);
         d->hCenterBinding->setTarget(d->hCenterProp);
     }
     if (d->anchorSet->d_func()->usedAnchors & QDeclarativeAnchors::TopAnchor) {
         d->topBinding = new QDeclarativeBinding(d->anchorSet->d_func()->topScript.script(), d->target, ctxt);
         d->topBinding->setTarget(d->topProp);
     }
     if (d->anchorSet->d_func()->usedAnchors & QDeclarativeAnchors::BottomAnchor) {
         d->bottomBinding = new QDeclarativeBinding(d->anchorSet->d_func()->bottomScript.script(), d->target, ctxt);
         d->bottomBinding->setTarget(d->bottomProp);
     }
     if (d->anchorSet->d_func()->usedAnchors & QDeclarativeAnchors::VCenterAnchor) {
         d->vCenterBinding = new QDeclarativeBinding(d->anchorSet->d_func()->vCenterScript.script(), d->target, ctxt);
         d->vCenterBinding->setTarget(d->vCenterProp);
     }
     if (d->anchorSet->d_func()->usedAnchors & QDeclarativeAnchors::BaselineAnchor) {
         d->baselineBinding = new QDeclarativeBinding(d->anchorSet->d_func()->baselineScript.script(), d->target, ctxt);
         d->baselineBinding->setTarget(d->baselineProp);
     }
     QDeclarativeAction a;
     a.event = this;
     return ActionList() << a;
 }
additionalActions()
QList< QDeclarativeAction > QDeclarativeAnchorChanges::additionalActions ()
Definition at line 1398 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorChanges);
     QList<QDeclarativeAction> extra;
     QDeclarativeAnchors::Anchors combined = d->anchorSet->d_func()->usedAnchors | d->anchorSet->d_func()->resetAnchors;
     bool hChange = combined & QDeclarativeAnchors::Horizontal_Mask;
     bool vChange = combined & QDeclarativeAnchors::Vertical_Mask;
     if (d->target) {
         QDeclarativeContext *ctxt = qmlContext(this);
         QDeclarativeAction a;
         if (hChange && d->fromX != d->toX) {
             a.property = QDeclarativeProperty(d->target, QLatin1String("x"), ctxt);
             a.toValue = d->toX;
             extra << a;
         }
         if (vChange && d->fromY != d->toY) {
             a.property = QDeclarativeProperty(d->target, QLatin1String("y"), ctxt);
             a.toValue = d->toY;
             extra << a;
         }
         if (hChange && d->fromWidth != d->toWidth) {
             a.property = QDeclarativeProperty(d->target, QLatin1String("width"), ctxt);
             a.toValue = d->toWidth;
             extra << a;
         }
         if (vChange && d->fromHeight != d->toHeight) {
             a.property = QDeclarativeProperty(d->target, QLatin1String("height"), ctxt);
             a.toValue = d->toHeight;
             extra << a;
         }
     }
     return extra;
 }
anchors()
QDeclarativeAnchorSet* QDeclarativeAnchorChanges::anchors ()
Referenced by actions().
changesBindings()
bool QDeclarativeAnchorChanges::changesBindings () virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1435 of file qdeclarativestateoperations.cpp.
 {
     return true;
 }
clearBindings()
void QDeclarativeAnchorChanges::clearBindings () virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1506 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorChanges);
     if (!d->target)
         return;
     //### should this (saving "from" values) be moved to saveCurrentValues()?
     d->fromX = d->target->x();
     d->fromY = d->target->y();
     d->fromWidth = d->target->width();
     d->fromHeight = d->target->height();
     QDeclarativeItemPrivate *targetPrivate = QDeclarativeItemPrivate::get(d->target);
     //reset any anchors with corresponding reverts
     //reset any anchors that have been specified as "undefined"
     //reset any anchors that we'll be setting in the state
     QDeclarativeAnchors::Anchors combined = d->anchorSet->d_func()->resetAnchors |
                                             d->anchorSet->d_func()->usedAnchors;
     if (d->applyOrigLeft || (combined & QDeclarativeAnchors::LeftAnchor)) {
         targetPrivate->anchors()->resetLeft();
         QDeclarativePropertyPrivate::setBinding(d->leftProp, 0);
     }
     if (d->applyOrigRight || (combined & QDeclarativeAnchors::RightAnchor)) {
         targetPrivate->anchors()->resetRight();
         QDeclarativePropertyPrivate::setBinding(d->rightProp, 0);
     }
     if (d->applyOrigHCenter || (combined & QDeclarativeAnchors::HCenterAnchor)) {
         targetPrivate->anchors()->resetHorizontalCenter();
         QDeclarativePropertyPrivate::setBinding(d->hCenterProp, 0);
     }
     if (d->applyOrigTop || (combined & QDeclarativeAnchors::TopAnchor)) {
         targetPrivate->anchors()->resetTop();
         QDeclarativePropertyPrivate::setBinding(d->topProp, 0);
     }
     if (d->applyOrigBottom || (combined & QDeclarativeAnchors::BottomAnchor)) {
         targetPrivate->anchors()->resetBottom();
         QDeclarativePropertyPrivate::setBinding(d->bottomProp, 0);
     }
     if (d->applyOrigVCenter || (combined & QDeclarativeAnchors::VCenterAnchor)) {
         targetPrivate->anchors()->resetVerticalCenter();
         QDeclarativePropertyPrivate::setBinding(d->vCenterProp, 0);
     }
     if (d->applyOrigBaseline || (combined & QDeclarativeAnchors::BaselineAnchor)) {
         targetPrivate->anchors()->resetBaseline();
         QDeclarativePropertyPrivate::setBinding(d->baselineProp, 0);
     }
 }
copyOriginals()
void QDeclarativeAnchorChanges::copyOriginals (QDeclarativeActionEvent * other) virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1468 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorChanges);
     QDeclarativeAnchorChanges *ac = static_cast<QDeclarativeAnchorChanges*>(other);
     QDeclarativeAnchorChangesPrivate *acp = ac->d_func();
     QDeclarativeAnchors::Anchors combined = acp->anchorSet->d_func()->usedAnchors |
                                             acp->anchorSet->d_func()->resetAnchors;
     //probably also need to revert some things
     d->applyOrigLeft = (combined & QDeclarativeAnchors::LeftAnchor);
     d->applyOrigRight = (combined & QDeclarativeAnchors::RightAnchor);
     d->applyOrigHCenter = (combined & QDeclarativeAnchors::HCenterAnchor);
     d->applyOrigTop = (combined & QDeclarativeAnchors::TopAnchor);
     d->applyOrigBottom = (combined & QDeclarativeAnchors::BottomAnchor);
     d->applyOrigVCenter = (combined & QDeclarativeAnchors::VCenterAnchor);
     d->applyOrigBaseline = (combined & QDeclarativeAnchors::BaselineAnchor);
     d->origLeftBinding = acp->origLeftBinding;
     d->origRightBinding = acp->origRightBinding;
     d->origHCenterBinding = acp->origHCenterBinding;
     d->origTopBinding = acp->origTopBinding;
     d->origBottomBinding = acp->origBottomBinding;
     d->origVCenterBinding = acp->origVCenterBinding;
     d->origBaselineBinding = acp->origBaselineBinding;
     d->origWidth = acp->origWidth;
     d->origHeight = acp->origHeight;
     d->origX = acp->origX;
     d->origY = acp->origY;
     d->oldBindings.clear();
     d->oldBindings << acp->leftBinding << acp->rightBinding << acp->hCenterBinding
                 << acp->topBinding << acp->bottomBinding << acp->baselineBinding;
     saveCurrentValues();
 }
execute()
void QDeclarativeAnchorChanges::execute (Reason reason = ActualChange) virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1176 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorChanges);
     if (!d->target)
         return;
     QDeclarativeItemPrivate *targetPrivate = QDeclarativeItemPrivate::get(d->target);
     //incorporate any needed "reverts"
     if (d->applyOrigLeft) {
         if (!d->origLeftBinding)
             targetPrivate->anchors()->resetLeft();
         QDeclarativePropertyPrivate::setBinding(d->leftProp, d->origLeftBinding);
     }
     if (d->applyOrigRight) {
         if (!d->origRightBinding)
             targetPrivate->anchors()->resetRight();
         QDeclarativePropertyPrivate::setBinding(d->rightProp, d->origRightBinding);
     }
     if (d->applyOrigHCenter) {
         if (!d->origHCenterBinding)
             targetPrivate->anchors()->resetHorizontalCenter();
         QDeclarativePropertyPrivate::setBinding(d->hCenterProp, d->origHCenterBinding);
     }
     if (d->applyOrigTop) {
         if (!d->origTopBinding)
             targetPrivate->anchors()->resetTop();
         QDeclarativePropertyPrivate::setBinding(d->topProp, d->origTopBinding);
     }
     if (d->applyOrigBottom) {
         if (!d->origBottomBinding)
             targetPrivate->anchors()->resetBottom();
         QDeclarativePropertyPrivate::setBinding(d->bottomProp, d->origBottomBinding);
     }
     if (d->applyOrigVCenter) {
         if (!d->origVCenterBinding)
             targetPrivate->anchors()->resetVerticalCenter();
         QDeclarativePropertyPrivate::setBinding(d->vCenterProp, d->origVCenterBinding);
     }
     if (d->applyOrigBaseline) {
         if (!d->origBaselineBinding)
             targetPrivate->anchors()->resetBaseline();
         QDeclarativePropertyPrivate::setBinding(d->baselineProp, d->origBaselineBinding);
     }
     //destroy old bindings
     if (reason == ActualChange) {
         for (int i = 0; i < d->oldBindings.size(); ++i) {
             QDeclarativeAbstractBinding *binding = d->oldBindings.at(i);
             if (binding)
                 binding->destroy();
         }
         d->oldBindings.clear();
     }
     //reset any anchors that have been specified as "undefined"
     if (d->anchorSet->d_func()->resetAnchors & QDeclarativeAnchors::LeftAnchor) {
         targetPrivate->anchors()->resetLeft();
         QDeclarativePropertyPrivate::setBinding(d->leftProp, 0);
     }
     if (d->anchorSet->d_func()->resetAnchors & QDeclarativeAnchors::RightAnchor) {
         targetPrivate->anchors()->resetRight();
         QDeclarativePropertyPrivate::setBinding(d->rightProp, 0);
     }
     if (d->anchorSet->d_func()->resetAnchors & QDeclarativeAnchors::HCenterAnchor) {
         targetPrivate->anchors()->resetHorizontalCenter();
         QDeclarativePropertyPrivate::setBinding(d->hCenterProp, 0);
     }
     if (d->anchorSet->d_func()->resetAnchors & QDeclarativeAnchors::TopAnchor) {
         targetPrivate->anchors()->resetTop();
         QDeclarativePropertyPrivate::setBinding(d->topProp, 0);
     }
     if (d->anchorSet->d_func()->resetAnchors & QDeclarativeAnchors::BottomAnchor) {
         targetPrivate->anchors()->resetBottom();
         QDeclarativePropertyPrivate::setBinding(d->bottomProp, 0);
     }
     if (d->anchorSet->d_func()->resetAnchors & QDeclarativeAnchors::VCenterAnchor) {
         targetPrivate->anchors()->resetVerticalCenter();
         QDeclarativePropertyPrivate::setBinding(d->vCenterProp, 0);
     }
     if (d->anchorSet->d_func()->resetAnchors & QDeclarativeAnchors::BaselineAnchor) {
         targetPrivate->anchors()->resetBaseline();
         QDeclarativePropertyPrivate::setBinding(d->baselineProp, 0);
     }
     //set any anchors that have been specified
     if (d->leftBinding)
         QDeclarativePropertyPrivate::setBinding(d->leftBinding->property(), d->leftBinding);
     if (d->rightBinding)
         QDeclarativePropertyPrivate::setBinding(d->rightBinding->property(), d->rightBinding);
     if (d->hCenterBinding)
         QDeclarativePropertyPrivate::setBinding(d->hCenterBinding->property(), d->hCenterBinding);
     if (d->topBinding)
         QDeclarativePropertyPrivate::setBinding(d->topBinding->property(), d->topBinding);
     if (d->bottomBinding)
         QDeclarativePropertyPrivate::setBinding(d->bottomBinding->property(), d->bottomBinding);
     if (d->vCenterBinding)
         QDeclarativePropertyPrivate::setBinding(d->vCenterBinding->property(), d->vCenterBinding);
     if (d->baselineBinding)
         QDeclarativePropertyPrivate::setBinding(d->baselineBinding->property(), d->baselineBinding);
 }
isReversable()
bool QDeclarativeAnchorChanges::isReversable () virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1277 of file qdeclarativestateoperations.cpp.
 {
     return true;
 }
needsCopy()
virtual bool QDeclarativeAnchorChanges::needsCopy () inline virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 288 of file qdeclarativestateoperations_p.h.
 { return true; }
object()
QDeclarativeItem * QDeclarativeAnchorChanges::object () const
Definition at line 1140 of file qdeclarativestateoperations.cpp.
Referenced by override().
 {
     Q_D(const QDeclarativeAnchorChanges);
     return d->target;
 }
override()
bool QDeclarativeAnchorChanges::override (QDeclarativeActionEvent * other) virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1554 of file qdeclarativestateoperations.cpp.
 {
     if (other->typeName() != QLatin1String("AnchorChanges"))
         return false;
     if (static_cast<QDeclarativeActionEvent*>(this) == other)
         return true;
     if (static_cast<QDeclarativeAnchorChanges*>(other)->object() == object())
         return true;
     return false;
 }
reverse()
void QDeclarativeAnchorChanges::reverse (Reason reason = ActualChange) virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1282 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorChanges);
     if (!d->target)
         return;
     QDeclarativeItemPrivate *targetPrivate = QDeclarativeItemPrivate::get(d->target);
     //reset any anchors set by the state
     if (d->leftBinding) {
         targetPrivate->anchors()->resetLeft();
         QDeclarativePropertyPrivate::setBinding(d->leftBinding->property(), 0);
         if (reason == ActualChange) {
             d->leftBinding->destroy(); d->leftBinding = 0;
         }
     }
     if (d->rightBinding) {
         targetPrivate->anchors()->resetRight();
         QDeclarativePropertyPrivate::setBinding(d->rightBinding->property(), 0);
         if (reason == ActualChange) {
             d->rightBinding->destroy(); d->rightBinding = 0;
         }
     }
     if (d->hCenterBinding) {
         targetPrivate->anchors()->resetHorizontalCenter();
         QDeclarativePropertyPrivate::setBinding(d->hCenterBinding->property(), 0);
         if (reason == ActualChange) {
             d->hCenterBinding->destroy(); d->hCenterBinding = 0;
         }
     }
     if (d->topBinding) {
         targetPrivate->anchors()->resetTop();
         QDeclarativePropertyPrivate::setBinding(d->topBinding->property(), 0);
         if (reason == ActualChange) {
             d->topBinding->destroy(); d->topBinding = 0;
         }
     }
     if (d->bottomBinding) {
         targetPrivate->anchors()->resetBottom();
         QDeclarativePropertyPrivate::setBinding(d->bottomBinding->property(), 0);
         if (reason == ActualChange) {
             d->bottomBinding->destroy(); d->bottomBinding = 0;
         }
     }
     if (d->vCenterBinding) {
         targetPrivate->anchors()->resetVerticalCenter();
         QDeclarativePropertyPrivate::setBinding(d->vCenterBinding->property(), 0);
         if (reason == ActualChange) {
             d->vCenterBinding->destroy(); d->vCenterBinding = 0;
         }
     }
     if (d->baselineBinding) {
         targetPrivate->anchors()->resetBaseline();
         QDeclarativePropertyPrivate::setBinding(d->baselineBinding->property(), 0);
         if (reason == ActualChange) {
             d->baselineBinding->destroy(); d->baselineBinding = 0;
         }
     }
     //restore previous anchors
     if (d->origLeftBinding)
         QDeclarativePropertyPrivate::setBinding(d->leftProp, d->origLeftBinding);
     if (d->origRightBinding)
         QDeclarativePropertyPrivate::setBinding(d->rightProp, d->origRightBinding);
     if (d->origHCenterBinding)
         QDeclarativePropertyPrivate::setBinding(d->hCenterProp, d->origHCenterBinding);
     if (d->origTopBinding)
         QDeclarativePropertyPrivate::setBinding(d->topProp, d->origTopBinding);
     if (d->origBottomBinding)
         QDeclarativePropertyPrivate::setBinding(d->bottomProp, d->origBottomBinding);
     if (d->origVCenterBinding)
         QDeclarativePropertyPrivate::setBinding(d->vCenterProp, d->origVCenterBinding);
     if (d->origBaselineBinding)
         QDeclarativePropertyPrivate::setBinding(d->baselineProp, d->origBaselineBinding);
     //restore any absolute geometry changed by the state's anchors
     QDeclarativeAnchors::Anchors stateVAnchors = d->anchorSet->d_func()->usedAnchors & QDeclarativeAnchors::Vertical_Mask;
     QDeclarativeAnchors::Anchors origVAnchors = targetPrivate->anchors()->usedAnchors() & QDeclarativeAnchors::Vertical_Mask;
     QDeclarativeAnchors::Anchors stateHAnchors = d->anchorSet->d_func()->usedAnchors & QDeclarativeAnchors::Horizontal_Mask;
     QDeclarativeAnchors::Anchors origHAnchors = targetPrivate->anchors()->usedAnchors() & QDeclarativeAnchors::Horizontal_Mask;
     bool stateSetWidth = (stateHAnchors &&
                           stateHAnchors != QDeclarativeAnchors::LeftAnchor &&
                           stateHAnchors != QDeclarativeAnchors::RightAnchor &&
                           stateHAnchors != QDeclarativeAnchors::HCenterAnchor);
     bool origSetWidth = (origHAnchors &&
                          origHAnchors != QDeclarativeAnchors::LeftAnchor &&
                          origHAnchors != QDeclarativeAnchors::RightAnchor &&
                          origHAnchors != QDeclarativeAnchors::HCenterAnchor);
     if (d->origWidth.isValid() && stateSetWidth && !origSetWidth)
         d->target->setWidth(d->origWidth.value);
     bool stateSetHeight = (stateVAnchors &&
                            stateVAnchors != QDeclarativeAnchors::TopAnchor &&
                            stateVAnchors != QDeclarativeAnchors::BottomAnchor &&
                            stateVAnchors != QDeclarativeAnchors::VCenterAnchor &&
                            stateVAnchors != QDeclarativeAnchors::BaselineAnchor);
     bool origSetHeight = (origVAnchors &&
                           origVAnchors != QDeclarativeAnchors::TopAnchor &&
                           origVAnchors != QDeclarativeAnchors::BottomAnchor &&
                           origVAnchors != QDeclarativeAnchors::VCenterAnchor &&
                           origVAnchors != QDeclarativeAnchors::BaselineAnchor);
     if (d->origHeight.isValid() && stateSetHeight && !origSetHeight)
         d->target->setHeight(d->origHeight.value);
     if (stateHAnchors && !origHAnchors)
         d->target->setX(d->origX);
     if (stateVAnchors && !origVAnchors)
         d->target->setY(d->origY);
 }
rewind()
void QDeclarativeAnchorChanges::rewind () virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1565 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorChanges);
     if (!d->target)
         return;
     QDeclarativeItemPrivate *targetPrivate = QDeclarativeItemPrivate::get(d->target);
     //restore previous values (but not previous bindings, i.e. anchors)
     d->target->setX(d->rewindX);
     d->target->setY(d->rewindY);
     if (targetPrivate->widthValid) {
         d->target->setWidth(d->rewindWidth);
     }
     if (targetPrivate->heightValid) {
         d->target->setHeight(d->rewindHeight);
     }
 }
saveCurrentValues()
void QDeclarativeAnchorChanges::saveCurrentValues () virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1584 of file qdeclarativestateoperations.cpp.
Referenced by copyOriginals(), and saveOriginals().
 {
     Q_D(QDeclarativeAnchorChanges);
     if (!d->target)
         return;
     QDeclarativeItemPrivate *targetPrivate = QDeclarativeItemPrivate::get(d->target);
     d->rewindLeft = targetPrivate->anchors()->left();
     d->rewindRight = targetPrivate->anchors()->right();
     d->rewindHCenter = targetPrivate->anchors()->horizontalCenter();
     d->rewindTop = targetPrivate->anchors()->top();
     d->rewindBottom = targetPrivate->anchors()->bottom();
     d->rewindVCenter = targetPrivate->anchors()->verticalCenter();
     d->rewindBaseline = targetPrivate->anchors()->baseline();
     d->rewindX = d->target->x();
     d->rewindY = d->target->y();
     d->rewindWidth = d->target->width();
     d->rewindHeight = d->target->height();
 }
saveOriginals()
void QDeclarativeAnchorChanges::saveOriginals () virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1440 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorChanges);
     if (!d->target)
         return;
     d->origLeftBinding = QDeclarativePropertyPrivate::binding(d->leftProp);
     d->origRightBinding = QDeclarativePropertyPrivate::binding(d->rightProp);
     d->origHCenterBinding = QDeclarativePropertyPrivate::binding(d->hCenterProp);
     d->origTopBinding = QDeclarativePropertyPrivate::binding(d->topProp);
     d->origBottomBinding = QDeclarativePropertyPrivate::binding(d->bottomProp);
     d->origVCenterBinding = QDeclarativePropertyPrivate::binding(d->vCenterProp);
     d->origBaselineBinding = QDeclarativePropertyPrivate::binding(d->baselineProp);
     QDeclarativeItemPrivate *targetPrivate = QDeclarativeItemPrivate::get(d->target);
     if (targetPrivate->widthValid)
         d->origWidth = d->target->width();
     if (targetPrivate->heightValid)
         d->origHeight = d->target->height();
     d->origX = d->target->x();
     d->origY = d->target->y();
     d->applyOrigLeft = d->applyOrigRight = d->applyOrigHCenter = d->applyOrigTop
       = d->applyOrigBottom = d->applyOrigVCenter = d->applyOrigBaseline = false;
     saveCurrentValues();
 }
saveTargetValues()
void QDeclarativeAnchorChanges::saveTargetValues () virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1605 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorChanges);
     if (!d->target)
         return;
     d->toX = d->target->x();
     d->toY = d->target->y();
     d->toWidth = d->target->width();
     d->toHeight = d->target->height();
 }
setObject()
void QDeclarativeAnchorChanges::setObject (QDeclarativeItem * target)
Definition at line 1146 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorChanges);
     d->target = target;
 }
typeName()
QString QDeclarativeAnchorChanges::typeName () const virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 1393 of file qdeclarativestateoperations.cpp.
 {
     return QLatin1String("AnchorChanges");
 }
Properties
anchors
QDeclarativeAnchorSet * QDeclarativeAnchorChanges::anchors private
Definition at line 268 of file qdeclarativestateoperations_p.h.
target
QDeclarativeItem* QDeclarativeAnchorChanges::target private
Definition at line 267 of file qdeclarativestateoperations_p.h.
Referenced by setObject().
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativestateoperations_p.h
/src/declarative/util/qdeclarativestateoperations.cpp