Qt 4.8: QDeclarativeValueTypeFactory Class Reference
QDeclarativeValueTypeFactory Class Reference
#include <qdeclarativevaluetype_p.h>
Public Functions
QDeclarativeValueType * operator[] (int idx) const
QDeclarativeValueTypeFactory ()
~QDeclarativeValueTypeFactory ()
Static Public Functions
static bool isValueType (int)
static void registerValueTypes ()
static void registerValueTypesCompat ()
static QDeclarativeValueType * valueType (int)
Properties
QDeclarativeValueType * valueTypes [QVariant::UserType - 1]
Detailed Description
Definition at line 84 of file qdeclarativevaluetype_p.h.
Constructors and Destructors
QDeclarativeValueTypeFactory()
QDeclarativeValueTypeFactory::QDeclarativeValueTypeFactory ()
Definition at line 81 of file qdeclarativevaluetype.cpp.
 {
     // ### Optimize
     for (unsigned int ii = 0; ii < (QVariant::UserType - 1); ++ii)
         valueTypes[ii] = valueType(ii);
 }
~QDeclarativeValueTypeFactory()
QDeclarativeValueTypeFactory::~QDeclarativeValueTypeFactory ()
Definition at line 88 of file qdeclarativevaluetype.cpp.
 {
     for (unsigned int ii = 0; ii < (QVariant::UserType - 1); ++ii)
         delete valueTypes[ii];
 }
Functions
isValueType()
bool QDeclarativeValueTypeFactory::isValueType (int idx) static
Definition at line 94 of file qdeclarativevaluetype.cpp.
Referenced by QDeclarativeCompiler::buildGroupedProperty(), QDeclarativePropertyAnimationPrivate::convertVariant(), QDeclarativePropertyPrivate::initProperty(), QDeclarativeWatchProxy::notifyValueChanged(), QDeclarativeObjectScriptClass::property(), QDeclarativeEngineDebugService::propertyData(), QDeclarativePropertyPrivate::propertyTypeCategory(), and QDeclarativeEngineDebugService::valueContents().
 {
     if ((uint)idx < QVariant::UserType)
         return true;
     return false;
 }
operator[]()
QDeclarativeValueType* QDeclarativeValueTypeFactory::operator[] (int idx) const inline
Definition at line 95 of file qdeclarativevaluetype_p.h.
{
         if (idx < 0 || idx >= (int)QVariant::UserType) return 0;
         else return valueTypes[idx];
     }
registerValueTypes()
void QDeclarativeValueTypeFactory::registerValueTypes () static
Definition at line 101 of file qdeclarativevaluetype.cpp.
Referenced by QDeclarativeEnginePrivate::QDeclarativeEnginePrivate().
 {
     qmlRegisterValueTypeEnums<QDeclarativeEasingValueType>("QtQuick",1,0,"Easing");
     qmlRegisterValueTypeEnums<QDeclarativeFontValueType>("QtQuick",1,0,"Font");
 }
registerValueTypesCompat()
void QDeclarativeValueTypeFactory::registerValueTypesCompat () static
Definition at line 107 of file qdeclarativevaluetype.cpp.
Referenced by QDeclarativeMetaType::isModule().
 {
     if (QApplication::type() == QApplication::Tty)
         return;
     qmlRegisterValueTypeEnums<QDeclarativeEasingValueType>("Qt",4,7,"Easing");
     qmlRegisterValueTypeEnums<QDeclarativeFontValueType>("Qt",4,7,"Font");
 }
valueType()
QDeclarativeValueType * QDeclarativeValueTypeFactory::valueType (int t) static
Definition at line 116 of file qdeclarativevaluetype.cpp.
Referenced by QDeclarativeVMEMetaObject::metaCall(), QDeclarativeProperty::name(), QDeclarativeProperty::propertyTypeName(), QDeclarativeValueTypeFactory(), QDeclarativePropertyPrivate::readValueProperty(), and QDeclarativePropertyPrivate::writeValueProperty().
 {
     QDeclarativeValueType *rv = 0;
     switch (t) {
     case QVariant::Point:
         rv = new QDeclarativePointValueType;
         break;
     case QVariant::PointF:
         rv = new QDeclarativePointFValueType;
         break;
     case QVariant::Size:
         rv = new QDeclarativeSizeValueType;
         break;
     case QVariant::SizeF:
         rv = new QDeclarativeSizeFValueType;
         break;
     case QVariant::Rect:
         rv = new QDeclarativeRectValueType;
         break;
     case QVariant::RectF:
         rv = new QDeclarativeRectFValueType;
         break;
     case QVariant::Vector2D:
         rv = new QDeclarativeVector2DValueType;
         break;
     case QVariant::Vector3D:
         rv = new QDeclarativeVector3DValueType;
         break;
     case QVariant::Vector4D:
         rv = new QDeclarativeVector4DValueType;
         break;
     case QVariant::Quaternion:
         rv = new QDeclarativeQuaternionValueType;
         break;
     case QVariant::Matrix4x4:
         rv = new QDeclarativeMatrix4x4ValueType;
         break;
     case QVariant::EasingCurve:
         rv = new QDeclarativeEasingValueType;
         break;
     case QVariant::Font:
         rv = new QDeclarativeFontValueType;
         break;
     default:
         break;
     }
     Q_ASSERT(!rv || rv->metaObject()->propertyCount() < 32);
     return rv;
 }
Properties
valueTypes
QDeclarativeValueType* QDeclarativeValueTypeFactory::valueTypes[QVariant::UserType - 1] private
Definition at line 101 of file qdeclarativevaluetype_p.h.
Referenced by QDeclarativeValueTypeFactory(), and ~QDeclarativeValueTypeFactory().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativevaluetype_p.h
/src/declarative/qml/qdeclarativevaluetype.cpp