Qt 4.8: QFbScreen Class Reference
QFbScreen Class Reference
#include <fb_base.h>
Public Functions
virtual void addWindow (QFbWindow *surface)
virtual int depth () const
Reimplement in subclass to return current depth of the screen.
virtual QImage::Format format () const
Reimplement in subclass to return the image format which corresponds to the screen format.
virtual QRect geometry () const
Reimplement in subclass to return the pixel geometry of the screen.
QImage * image () const
virtual void lower (QPlatformWindow *surface)
QPaintDevice * paintDevice () const
virtual QSize physicalSize () const
Reimplement this function in subclass to return the physical size of the screen.
QFbScreen ()
virtual void raise (QPlatformWindow *surface)
virtual void removeWindow (QFbWindow *surface)
virtual void setDepth (int depth)
virtual void setDirty (const QRect &rect)
virtual void setFormat (QImage::Format format)
virtual void setGeometry (QRect rect)
virtual void setPhysicalSize (QSize size)
virtual QWidget * topLevelAt (const QPoint &p) const
Return the given top level widget for a given position.
~QFbScreen ()
Public Functions inherited from QPlatformScreen
virtual QRect availableGeometry () const
Reimplement in subclass to return the pixel geometry of the available space This normally is the desktop screen minus the task manager, global menubar etc.
virtual ~QPlatformScreen ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Slots
virtual QRegion doRedraw ()
Protected Variables
QPlatformSoftwareCursor * cursor
int mDepth
QImage::Format mFormat
QRect mGeometry
QSize mPhysicalSize
QImage * mScreenImage
QTimer redrawTimer
QRegion repaintRegion
QList< QFbWindow * > windowStack
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Private Functions
void generateRects ()
void invalidateRectCache ()
Properties
QList< QPair< QRect, int > > cachedRects
QPainter * compositePainter
bool isUpToDate
Friends
class QFbWindow
class QFbWindowSurface
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QPlatformScreen
static QPlatformScreen * platformScreenForWidget (const QWidget *widget)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 155 of file fb_base.h.
Constructors and Destructors
QFbScreen()
QFbScreen::QFbScreen ()
Definition at line 144 of file fb_base.cpp.
                      : cursor(0), mGeometry(), mDepth(16), mFormat(QImage::Format_RGB16), mScreenImage(0), compositePainter(0), isUpToDate(false)
 {
     mScreenImage = new QImage(mGeometry.size(), mFormat);
     redrawTimer.setSingleShot(true);
     redrawTimer.setInterval(0);
     QObject::connect(&redrawTimer, SIGNAL(timeout()), this, SLOT(doRedraw()));
 }
~QFbScreen()
QFbScreen::~QFbScreen ()
Definition at line 181 of file fb_base.cpp.
 {
     delete compositePainter;
     delete mScreenImage;
 }
Functions
addWindow()
void QFbScreen::addWindow (QFbWindow * surface) virtual
Definition at line 305 of file fb_base.cpp.
Referenced by QLinuxFbIntegration::createPlatformWindow(), QVNCIntegration::createPlatformWindow(), and QVNCIntegration::moveToScreen().
 {
     windowStack.prepend(surface);
     surface->mScreens.append(this);
     invalidateRectCache();
     setDirty(surface->geometry());
 }
depth()
virtual int QFbScreen::depth () const inline virtual
Reimplement in subclass to return current depth of the screen.
Implements QPlatformScreen.
Definition at line 163 of file fb_base.h.
Referenced by QVNCServer::convertPixels(), QVNCScreen::initDevice(), QVNCServer::pixelConversionNeeded(), QVNCDirtyMap::QVNCDirtyMap(), QVNCScreenPrivate::QVNCScreenPrivate(), QRfbSingleColorHextile< SRC >::read(), QVNCServer::readClient(), setDepth(), and QVNCServer::setEncodings().
 { return mDepth; }
doRedraw
QRegion QFbScreen::doRedraw () protected virtual slot
Reimplemented in QVNCScreen.
Definition at line 229 of file fb_base.cpp.
Referenced by QLinuxFbScreen::doRedraw(), QVNCScreen::doRedraw(), and QFbScreen().
 {
     QPoint screenOffset = mGeometry.topLeft();
     QRegion touchedRegion;
     if (cursor && cursor->isDirty() && cursor->isOnScreen()) {
         QRect lastCursor = cursor->dirtyRect();
         repaintRegion += lastCursor;
     }
     if (repaintRegion.isEmpty() && (!cursor || !cursor->isDirty())) {
         return touchedRegion;
     }
     QVector<QRect> rects = repaintRegion.rects();
     if (!isUpToDate)
         generateRects();
     if (!compositePainter)
         compositePainter = new QPainter(mScreenImage);
     for (int rectIndex = 0; rectIndex < repaintRegion.numRects(); rectIndex++) {
         QRegion rectRegion = rects[rectIndex];
         for(int i = 0; i < cachedRects.length(); i++) {
             QRect screenSubRect = cachedRects[i].first;
             int layer = cachedRects[i].second;
             QRegion intersect = rectRegion.intersected(screenSubRect);
             if (intersect.isEmpty())
                 continue;
             rectRegion -= intersect;
             // we only expect one rectangle, but defensive coding...
             foreach (QRect rect, intersect.rects()) {
                 bool firstLayer = true;
                 if (layer == -1) {
                     compositePainter->fillRect(rect, Qt::black);
                     firstLayer = false;
                     layer = windowStack.size() - 1;
                 }
                 for (int layerIndex = layer; layerIndex != -1; layerIndex--) {
                     if (!windowStack[layerIndex]->visible())
                         continue;
                     if (windowStack[layerIndex]->widget()->isMinimized())
                         continue;
                     QRect windowRect = windowStack[layerIndex]->geometry().translated(-screenOffset);
                     QRect windowIntersect = rect.translated(-windowRect.left(),
                                                             -windowRect.top());
                     compositePainter->drawImage(rect, windowStack[layerIndex]->surface->image(),
                                                 windowIntersect);
                     if (firstLayer) {
                         firstLayer = false;
                     }
                 }
             }
         }
     }
     QRect cursorRect;
     if (cursor && (cursor->isDirty() || repaintRegion.intersects(cursor->lastPainted()))) {
         cursorRect = cursor->drawCursor(*compositePainter);
         touchedRegion += cursorRect;
     }
     touchedRegion += repaintRegion;
     repaintRegion = QRegion();
 //    qDebug() << "QFbScreen::doRedraw"  << windowStack.size() << mScreenImage->size() << touchedRegion;
     return touchedRegion;
 }
format()
virtual QImage::Format QFbScreen::format () const inline virtual
Reimplement in subclass to return the image format which corresponds to the screen format.
Implements QPlatformScreen.
Definition at line 164 of file fb_base.h.
Referenced by QFbWindowSurface::QFbWindowSurface(), QFbWindowSurface::resize(), QLinuxFbScreen::setFormat(), and setFormat().
 { return mFormat; }
generateRects()
void QFbScreen::generateRects () private
Definition at line 197 of file fb_base.cpp.
Referenced by doRedraw().
 {
     cachedRects.clear();
     QPoint screenOffset = mGeometry.topLeft();
     QRegion remainingScreen(mGeometry.translated(-screenOffset)); // global to local translation
     for (int i = 0; i < windowStack.length(); i++) {
         if (remainingScreen.isEmpty())
             break;
         if (!windowStack[i]->visible())
             continue;
         if (windowStack[i]->widget()->isMinimized())
             continue;
         if (!windowStack[i]->widget()->testAttribute(Qt::WA_TranslucentBackground)) {
             QRect localGeometry = windowStack.at(i)->geometry().translated(-screenOffset); // global to local translation
             remainingScreen -= localGeometry;
             QRegion windowRegion(localGeometry);
             windowRegion -= remainingScreen;
             foreach(QRect rect, windowRegion.rects()) {
                 cachedRects += QPair<QRect, int>(rect, i);
             }
         }
     }
     foreach (QRect rect, remainingScreen.rects())
         cachedRects += QPair<QRect, int>(rect, -1);
     isUpToDate = true;
     return;
 }
geometry()
virtual QRect QFbScreen::geometry () const inline virtual
Reimplement in subclass to return the pixel geometry of the screen.
Implements QPlatformScreen.
Definition at line 162 of file fb_base.h.
Referenced by buttonChange(), QVNCDirtyMap::QVNCDirtyMap(), QVNCScreen::QVNCScreen(), and topLevelAt().
 { return mGeometry; }
image()
QImage* QFbScreen::image () const inline
Definition at line 180 of file fb_base.h.
Referenced by QVNCScreen::base(), QVNCIntegration::grabWindow(), and QVNCScreen::linestep().
 { return mScreenImage; }
invalidateRectCache()
void QFbScreen::invalidateRectCache () inline private
Definition at line 204 of file fb_base.h.
Referenced by addWindow(), lower(), raise(), removeWindow(), and setGeometry().
 { isUpToDate = false; }
lower()
void QFbScreen::lower (QPlatformWindow * surface) virtual
Definition at line 352 of file fb_base.cpp.
 {
     QFbWindow *s = static_cast<QFbWindow *>(surface);
     int index = windowStack.indexOf(s);
     if (index == -1 || index == (windowStack.size() - 1))
         return;
     windowStack.move(index, windowStack.size() - 1);
     invalidateRectCache();
     setDirty(s->geometry());
 }
paintDevice()
QPaintDevice* QFbScreen::paintDevice () const inline
Definition at line 181 of file fb_base.h.
 { return mScreenImage; }
physicalSize()
virtual QSize QFbScreen::physicalSize () const inline virtual
Reimplement this function in subclass to return the physical size of the screen.
This function is used by QFont to convert point sizes to pixel sizes.
The default implementation takes the pixel size of the screen, considers a resolution of 100 dots per inch, and returns the calculated physical size. A device with a screen that has different resolutions will need to be supported by a suitable reimplementation of this function.
Reimplemented from QPlatformScreen.
Definition at line 165 of file fb_base.h.
 { return mPhysicalSize; }
raise()
void QFbScreen::raise (QPlatformWindow * surface) virtual
Definition at line 331 of file fb_base.cpp.
 {
     QFbWindow *s = static_cast<QFbWindow *>(surface);
     int index = windowStack.indexOf(s);
     if (index <= 0)
         return;
     windowStack.move(index, 0);
     invalidateRectCache();
     setDirty(s->geometry());
 }
removeWindow()
void QFbScreen::removeWindow (QFbWindow * surface) virtual
Definition at line 313 of file fb_base.cpp.
Referenced by QVNCIntegration::moveToScreen().
 {
     windowStack.removeOne(surface);
     surface->mScreens.removeOne(this);
     invalidateRectCache();
     setDirty(surface->geometry());
 }
setDepth()
void QFbScreen::setDepth (int depth) virtual
Definition at line 162 of file fb_base.cpp.
Referenced by QVNCScreen::QVNCScreen().
 {
     mDepth = depth;
 }
setDirty()
void QFbScreen::setDirty (const QRect & rect) virtual
Reimplemented from QPlatformScreen.
Reimplemented in QLinuxFbScreen, and QVNCScreen.
Definition at line 187 of file fb_base.cpp.
Referenced by addWindow(), lower(), raise(), and removeWindow().
 {
     QRect intersection = rect.intersected(mGeometry);
     QPoint screenOffset = mGeometry.topLeft();
     repaintRegion += intersection.translated(-screenOffset);    // global to local translation
     if (!redrawTimer.isActive()) {
         redrawTimer.start();
     }
 }
setFormat()
void QFbScreen::setFormat (QImage::Format format) virtual
Reimplemented in QLinuxFbScreen.
Definition at line 172 of file fb_base.cpp.
Referenced by QVNCScreen::QVNCScreen().
 {
     mFormat = format;
     delete mScreenImage;
     mScreenImage = new QImage(mGeometry.size(), mFormat);
     delete compositePainter;
     compositePainter = 0;
 }
setGeometry()
void QFbScreen::setGeometry (QRect rect) virtual
Reimplemented in QLinuxFbScreen.
Definition at line 152 of file fb_base.cpp.
Referenced by QVNCScreen::QVNCScreen().
 {
     delete mScreenImage;
     mGeometry = rect;
     mScreenImage = new QImage(mGeometry.size(), mFormat);
     delete compositePainter;
     compositePainter = 0;
     invalidateRectCache();
 }
setPhysicalSize()
void QFbScreen::setPhysicalSize (QSize size) virtual
Definition at line 167 of file fb_base.cpp.
Referenced by QLinuxFbIntegration::QLinuxFbIntegration(), and QVNCScreen::QVNCScreen().
 {
     mPhysicalSize = size;
 }
topLevelAt()
QWidget * QFbScreen::topLevelAt (const QPoint & pos) const virtual
Return the given top level widget for a given position.
Default implementation retrieves a list of all top level widgets and finds the first widget which contains point pos
Reimplemented from QPlatformScreen.
Definition at line 363 of file fb_base.cpp.
 {
     for(int i = 0; i < windowStack.size(); i++) {
         if (windowStack[i]->geometry().contains(p, false) &&
             windowStack[i]->visible() &&
             !windowStack[i]->widget()->isMinimized()) {
             return windowStack[i]->widget();
         }
     }
     return 0;
 }
Friends and Related Functions
QFbWindow
friend class QFbWindow friend
Definition at line 206 of file fb_base.h.
QFbWindowSurface
friend class QFbWindowSurface friend
Definition at line 205 of file fb_base.h.
Properties
cachedRects
QList<QPair<QRect, int> > QFbScreen::cachedRects private
Definition at line 202 of file fb_base.h.
Referenced by doRedraw(), and generateRects().
compositePainter
QPainter* QFbScreen::compositePainter private
Definition at line 200 of file fb_base.h.
Referenced by doRedraw(), setFormat(), setGeometry(), and ~QFbScreen().
cursor
QPlatformSoftwareCursor* QFbScreen::cursor protected
Definition at line 186 of file fb_base.h.
Referenced by doRedraw(), QLinuxFbScreen::QLinuxFbScreen(), and QVNCScreen::QVNCScreen().
isUpToDate
bool QFbScreen::isUpToDate private
Definition at line 207 of file fb_base.h.
Referenced by doRedraw(), and generateRects().
mDepth
int QFbScreen::mDepth protected
Definition at line 194 of file fb_base.h.
Referenced by QLinuxFbScreen::QLinuxFbScreen(), and setDepth().
mFormat
QImage::Format QFbScreen::mFormat protected
Definition at line 195 of file fb_base.h.
Referenced by QFbScreen(), QLinuxFbScreen::QLinuxFbScreen(), QLinuxFbScreen::setFormat(), setFormat(), QLinuxFbScreen::setGeometry(), and setGeometry().
mGeometry
QRect QFbScreen::mGeometry protected
Definition at line 193 of file fb_base.h.
Referenced by doRedraw(), generateRects(), QFbScreen(), QLinuxFbScreen::QLinuxFbScreen(), setDirty(), QLinuxFbScreen::setFormat(), setFormat(), QLinuxFbScreen::setGeometry(), and setGeometry().
mPhysicalSize
QSize QFbScreen::mPhysicalSize protected
Definition at line 196 of file fb_base.h.
Referenced by setPhysicalSize().
mScreenImage
QImage* QFbScreen::mScreenImage protected
Definition at line 197 of file fb_base.h.
Referenced by QLinuxFbScreen::doRedraw(), doRedraw(), QFbScreen(), QLinuxFbScreen::QLinuxFbScreen(), QLinuxFbScreen::setFormat(), setFormat(), QLinuxFbScreen::setGeometry(), setGeometry(), and ~QFbScreen().
redrawTimer
QTimer QFbScreen::redrawTimer protected
Definition at line 187 of file fb_base.h.
Referenced by QFbScreen(), and setDirty().
repaintRegion
QRegion QFbScreen::repaintRegion protected
Definition at line 185 of file fb_base.h.
Referenced by doRedraw(), and setDirty().
windowStack
QList<QFbWindow *> QFbScreen::windowStack protected
Definition at line 184 of file fb_base.h.
Referenced by addWindow(), doRedraw(), generateRects(), lower(), QVNCIntegration::moveToScreen(), raise(), removeWindow(), and topLevelAt().
The documentation for this class was generated from the following files:
/src/plugins/platforms/fb_base/fb_base.h
/src/plugins/platforms/fb_base/fb_base.cpp