Qt 4.8: QScriptValuePrivate Class Reference
QScriptValuePrivate Class Reference
#include <qscriptvalue_p.h>
Public Types
enum Type { JavaScriptCore, Number, String }
Public Functions
void detachFromEngine ()
void initFrom (JSC::JSValue value)
void initFrom (qsreal value)
void initFrom (const QString &value)
bool isJSC () const
bool isObject () const
qint64 objectId ()
void operator delete (void *)
void * operator new (size_t, QScriptEnginePrivate *)
JSC::JSValue property (const JSC::Identifier &id, const QScriptValue::ResolveFlags &mode=QScriptValue::ResolvePrototype) const
JSC::JSValue property (quint32 index, const QScriptValue::ResolveFlags &mode=QScriptValue::ResolvePrototype) const
JSC::JSValue property (const JSC::UString &, const QScriptValue::ResolveFlags &mode=QScriptValue::ResolvePrototype) const
QScriptValue::PropertyFlags propertyFlags (const JSC::Identifier &id, const QScriptValue::ResolveFlags &mode=QScriptValue::ResolvePrototype) const
QScriptValuePrivate (QScriptEnginePrivate *)
void setProperty (const JSC::UString &name, const JSC::JSValue &value, const QScriptValue::PropertyFlags &flags=QScriptValue::KeepExistingFlags)
void setProperty (const JSC::Identifier &id, const JSC::JSValue &value, const QScriptValue::PropertyFlags &flags=QScriptValue::KeepExistingFlags)
void setProperty (quint32 index, const JSC::JSValue &value, const QScriptValue::PropertyFlags &flags=QScriptValue::KeepExistingFlags)
~QScriptValuePrivate ()
Static Public Functions
static QScriptValuePrivate * get (const QScriptValue &q)
static QScriptEnginePrivate * getEngine (const QScriptValue &q)
static QScriptValue toPublic (QScriptValuePrivate *d)
Public Variables
QScriptEnginePrivate * engine
JSC::JSValue jscValue
QScriptValuePrivate * next
qsreal numberValue
QScriptValuePrivate * prev
QBasicAtomicInt ref
QString stringValue
Type type
Detailed Description
Definition at line 49 of file qscriptvalue_p.h.
Enumerations
Type
enum QScriptValuePrivate::Type
Enumerator
JavaScriptCore
Number
String
Definition at line 56 of file qscriptvalue_p.h.
               {
         JavaScriptCore,
         Number,
         String
     };
Constructors and Destructors
QScriptValuePrivate()
QScriptValuePrivate::QScriptValuePrivate (QScriptEnginePrivate * e) inline
Definition at line 125 of file qscriptvalue_p.h.
     : engine(e), prev(0), next(0)
 {
     ref = 0;
 }
~QScriptValuePrivate()
QScriptValuePrivate::~QScriptValuePrivate () inline
Definition at line 681 of file qscriptengine_p.h.
 {
     if (engine)
         engine->unregisterScriptValue(this);
 }
Functions
detachFromEngine()
void QScriptValuePrivate::detachFromEngine ()
Definition at line 183 of file qscriptvalue.cpp.
Referenced by QScriptEnginePrivate::detachAllRegisteredScriptValues(), and getEngine().
 {
     if (isJSC())
         jscValue = JSC::JSValue();
     engine = 0;
 }
get()
static QScriptValuePrivate* QScriptValuePrivate::get (const QScriptValue & q) inline static
Definition at line 72 of file qscriptvalue_p.h.
Referenced by QScriptEngine::convertV2(), QScriptDeclarativeClass::function(), QScriptDeclarativeClass::functionValue(), QScriptEngine::newQObject(), QScriptDeclarativeClass::object(), QScriptValueIteratorPrivate::object(), QScriptDeclarativeClass::property(), QScriptDeclarativeClass::propertyValue(), QScript::FunctionWrapper::proxyConstruct(), QScriptDeclarativeClass::scriptClass(), QScriptEnginePrivate::scriptValueToJSCValue(), and QScript::ToPrimitive().
     {
         return q.d_ptr.data();
     }
getEngine()
static QScriptEnginePrivate* QScriptValuePrivate::getEngine (const QScriptValue & q) inline static
Definition at line 82 of file qscriptvalue_p.h.
Referenced by QScriptValue::call(), QScriptValue::construct(), QScriptValue::equals(), QScriptValue::instanceOf(), QScriptValue::lessThan(), QScriptValue::setProperty(), QScriptValue::setPrototype(), QScriptValue::setScope(), and QScriptValue::strictlyEquals().
     {
         if (!q.d_ptr)
             return 0;
         return q.d_ptr->engine;
     }
initFrom() [1/3]
void QScriptValuePrivate::initFrom (JSC::JSValue value) inline
Definition at line 687 of file qscriptengine_p.h.
Referenced by QScriptValue::QScriptValue(), QScriptEnginePrivate::scriptValueFromJSCValue(), and QScriptEnginePrivate::scriptValueToJSCValue().
 {
     if (value.isCell()) {
         Q_ASSERT(engine != 0);
         value = engine->toUsableValue(value);
     }
     type = JavaScriptCore;
     jscValue = value;
     if (engine)
         engine->registerScriptValue(this);
 }
initFrom() [2/3]
void QScriptValuePrivate::initFrom (qsreal value) inline
Definition at line 699 of file qscriptengine_p.h.
 {
     type = Number;
     numberValue = value;
     if (engine)
         engine->registerScriptValue(this);
 }
initFrom() [3/3]
void QScriptValuePrivate::initFrom (const QString & value) inline
Definition at line 707 of file qscriptengine_p.h.
 {
     type = String;
     stringValue = value;
     if (engine)
         engine->registerScriptValue(this);
 }
isJSC()
bool QScriptValuePrivate::isJSC () const inline
Definition at line 131 of file qscriptvalue_p.h.
Referenced by detachFromEngine(), QScriptValue::equals(), isObject(), QScriptEnginePrivate::mark(), QScriptDeclarativeClass::object(), and QScriptDeclarativeClass::scriptClass().
 {
     return (type == JavaScriptCore);
 }
isObject()
bool QScriptValuePrivate::isObject () const inline
Definition at line 136 of file qscriptvalue_p.h.
Referenced by QScriptDeclarativeClass::function(), QScriptDeclarativeClass::functionValue(), QScriptDeclarativeClass::property(), and QScriptDeclarativeClass::propertyValue().
 {
     return isJSC() && jscValue && jscValue.isObject();
 }
objectId()
qint64 QScriptValuePrivate::objectId () inline
Definition at line 104 of file qscriptvalue_p.h.
Referenced by QScriptValue::objectId().
     {
         if ( (type == JavaScriptCore) && (engine) && jscValue.isCell() )
             return (qint64)jscValue.asCell();
         else
             return -1;
     }
operator delete()
void QScriptValuePrivate::operator delete (void * ptr) inline
Definition at line 801 of file qscriptengine_p.h.
 {
     QScriptValuePrivate *d = reinterpret_cast<QScriptValuePrivate*>(ptr);
     if (d->engine)
         d->engine->freeScriptValuePrivate(d);
     else
         qFree(d);
 }
operator new()
void * QScriptValuePrivate::operator new (size_t size, QScriptEnginePrivate * engine) inline
Definition at line 794 of file qscriptengine_p.h.
 {
     if (engine)
         return engine->allocateScriptValuePrivate(size);
     return qMalloc(size);
 }
property() [1/3]
JSC::JSValue QScriptValuePrivate::property (const JSC::Identifier & id, const QScriptValue::ResolveFlags & mode = QScriptValue::ResolvePrototype) const inline
Definition at line 753 of file qscriptengine_p.h.
Referenced by getEngine().
 {
     return QScriptEnginePrivate::property(engine->currentFrame, jscValue, id, resolveMode);
 }
property() [2/3]
JSC::JSValue QScriptValuePrivate::property (quint32 index, const QScriptValue::ResolveFlags & mode = QScriptValue::ResolvePrototype) const inline
Definition at line 758 of file qscriptengine_p.h.
 {
     return QScriptEnginePrivate::property(engine->currentFrame, jscValue, index, resolveMode);
 }
property() [3/3]
JSC::JSValue QScriptValuePrivate::property (const JSC::UString & name, const QScriptValue::ResolveFlags & mode = QScriptValue::ResolvePrototype) const inline
Definition at line 763 of file qscriptengine_p.h.
 {
     JSC::ExecState *exec = engine->currentFrame;
     return QScriptEnginePrivate::property(exec, jscValue, JSC::Identifier(exec, name), resolveMode);
 }
propertyFlags()
QScriptValue::PropertyFlags QScriptValuePrivate::propertyFlags (const JSC::Identifier & id, const QScriptValue::ResolveFlags & mode = QScriptValue::ResolvePrototype) const inline
Definition at line 769 of file qscriptengine_p.h.
Referenced by getEngine().
 {
     return QScriptEnginePrivate::propertyFlags(engine->currentFrame, jscValue, id, mode);
 }
setProperty() [1/3]
void QScriptValuePrivate::setProperty (const JSC::UString & name, const JSC::JSValue & value, const QScriptValue::PropertyFlags & flags = QScriptValue::KeepExistingFlags) inline
Definition at line 787 of file qscriptengine_p.h.
Referenced by getEngine().
 {
     JSC::ExecState *exec = engine->currentFrame;
     QScriptEnginePrivate::setProperty(exec, jscValue, JSC::Identifier(exec, name), value, flags);
 }
setProperty() [2/3]
void QScriptValuePrivate::setProperty (const JSC::Identifier & id, const JSC::JSValue & value, const QScriptValue::PropertyFlags & flags = QScriptValue::KeepExistingFlags) inline
Definition at line 775 of file qscriptengine_p.h.
 {
     QScriptEnginePrivate::setProperty(engine->currentFrame, jscValue, id, value, flags);
 }
setProperty() [3/3]
void QScriptValuePrivate::setProperty (quint32 index, const JSC::JSValue & value, const QScriptValue::PropertyFlags & flags = QScriptValue::KeepExistingFlags) inline
Definition at line 781 of file qscriptengine_p.h.
 {
     QScriptEnginePrivate::setProperty(engine->currentFrame, jscValue, index, value, flags);
 }
toPublic()
static QScriptValue QScriptValuePrivate::toPublic (QScriptValuePrivate * d) inline static
Definition at line 77 of file qscriptvalue_p.h.
Referenced by QScriptEnginePrivate::scriptValueFromJSCValue().
     {
         return QScriptValue(d);
     }
Properties
engine
QScriptEnginePrivate* QScriptValuePrivate::engine
Definition at line 112 of file qscriptvalue_p.h.
Referenced by QScriptEngine::convertV2(), detachFromEngine(), QScriptValue::equals(), QScriptDeclarativeClass::function(), QScriptDeclarativeClass::functionValue(), getEngine(), objectId(), operator delete(), QScriptDeclarativeClass::property(), QScriptDeclarativeClass::propertyValue(), QScriptValue::QScriptValue(), QScriptEnginePrivate::scriptValueToJSCValue(), QScriptValue::strictlyEquals(), and QScript::ToPrimitive().
jscValue
JSC::JSValue QScriptValuePrivate::jscValue
Definition at line 114 of file qscriptvalue_p.h.
Referenced by QScriptEngine::convertV2(), detachFromEngine(), QScriptValue::equals(), QScriptDeclarativeClass::function(), QScriptDeclarativeClass::functionValue(), isObject(), QScriptEnginePrivate::mark(), QScriptDeclarativeClass::object(), objectId(), QScriptDeclarativeClass::property(), QScriptDeclarativeClass::propertyValue(), QScript::FunctionWrapper::proxyConstruct(), QScriptDeclarativeClass::scriptClass(), QScriptEnginePrivate::scriptValueToJSCValue(), QScriptValue::strictlyEquals(), and QScript::ToPrimitive().
next
QScriptValuePrivate* QScriptValuePrivate::next
Definition at line 120 of file qscriptvalue_p.h.
Referenced by QScriptEnginePrivate::allocateScriptValuePrivate(), QScriptEnginePrivate::detachAllRegisteredScriptValues(), QScriptEnginePrivate::freeScriptValuePrivate(), QScriptEnginePrivate::mark(), QScriptEnginePrivate::registerScriptValue(), QScriptEnginePrivate::unregisterScriptValue(), and QScriptEnginePrivate::~QScriptEnginePrivate().
numberValue
qsreal QScriptValuePrivate::numberValue
Definition at line 115 of file qscriptvalue_p.h.
Referenced by QScriptEngine::convertV2(), QScriptEnginePrivate::scriptValueToJSCValue(), and QScriptValue::strictlyEquals().
prev
QScriptValuePrivate* QScriptValuePrivate::prev
Definition at line 119 of file qscriptvalue_p.h.
Referenced by QScriptEnginePrivate::detachAllRegisteredScriptValues(), QScriptEnginePrivate::registerScriptValue(), and QScriptEnginePrivate::unregisterScriptValue().
ref
QBasicAtomicInt QScriptValuePrivate::ref
Definition at line 122 of file qscriptvalue_p.h.
Referenced by QScriptValuePrivate().
stringValue
QString QScriptValuePrivate::stringValue
Definition at line 116 of file qscriptvalue_p.h.
Referenced by QScriptEngine::convertV2(), QScriptEnginePrivate::scriptValueToJSCValue(), and QScriptValue::strictlyEquals().
type
Type QScriptValuePrivate::type
Definition at line 113 of file qscriptvalue_p.h.
Referenced by QScriptEngine::convertV2(), isJSC(), objectId(), QScriptEnginePrivate::scriptValueToJSCValue(), and QScriptValue::strictlyEquals().
The documentation for this class was generated from the following files:
/src/script/api/qscriptvalue_p.h
/src/script/api/qscriptengine_p.h
/src/script/api/qscriptvalue.cpp