Qt 4.8: QGLTexturePool Class Reference
QGLTexturePool Class Reference
#include <qgltexturepool_p.h>
Public Functions
bool createPermanentTexture (GLuint texture, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *data)
GLuint createTexture (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, QGLTexture *texture)
void detachTexture (QGLTexture *texture)
void hibernate ()
QGLTexturePool ()
bool reclaimSpace (GLint internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, QGLTexture *data)
void useTexture (QGLTexture *texture)
virtual ~QGLTexturePool ()
Static Public Functions
static QGLTexturePool * instance ()
Protected Functions
void moveToHeadOfLRU (QGLTexture *texture)
void removeFromLRU (QGLTexture *texture)
QGLTexture * textureLRU ()
Properties
QScopedPointer< QGLTexturePoolPrivate > d_ptr
Detailed Description
Definition at line 64 of file qgltexturepool_p.h.
Constructors and Destructors
QGLTexturePool()
QGLTexturePool::QGLTexturePool ()
Definition at line 61 of file qgltexturepool.cpp.
Referenced by instance().
     : d_ptr(new QGLTexturePoolPrivate())
 {
 }
~QGLTexturePool()
QGLTexturePool::~QGLTexturePool () virtual
Definition at line 66 of file qgltexturepool.cpp.
 {
 }
Functions
createPermanentTexture()
bool QGLTexturePool::createPermanentTexture (GLuint texture, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * data)
Definition at line 106 of file qgltexturepool.cpp.
 {
     glBindTexture(target, tex);
     do {
         glTexImage2D(target, level, internalformat, width, height, 0, format, type, data);
         GLenum error = glGetError();
         if (error == GL_NO_ERROR) {
             return true;
         } else if (error != GL_OUT_OF_MEMORY) {
             qWarning("QGLTexturePool: cannot create permanent texture because of invalid params");
             return false;
         }
     } while (reclaimSpace(internalformat, width, height, format, type, 0));
     qWarning("QGLTexturePool: cannot reclaim sufficient space for a %dx%d texture",
              width, height);
     return 0;
 }
createTexture()
GLuint QGLTexturePool::createTexture (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, QGLTexture * texture)
Definition at line 77 of file qgltexturepool.cpp.
 {
     GLuint tex;
     glGenTextures(1, &tex);
     glBindTexture(target, tex);
     do {
         glTexImage2D(target, level, internalformat, width, height, 0, format, type, 0);
         GLenum error = glGetError();
         if (error == GL_NO_ERROR) {
             if (texture)
                 moveToHeadOfLRU(texture);
             return tex;
         } else if (error != GL_OUT_OF_MEMORY) {
             qWarning("QGLTexturePool: cannot create temporary texture because of invalid params");
             return 0;
         }
     } while (reclaimSpace(internalformat, width, height, format, type, texture));
     qWarning("QGLTexturePool: cannot reclaim sufficient space for a %dx%d texture",
              width, height);
     return 0;
 }
detachTexture()
void QGLTexturePool::detachTexture (QGLTexture * texture)
Definition at line 139 of file qgltexturepool.cpp.
 {
     removeFromLRU(texture);
     texture->inTexturePool = false;
 }
hibernate()
void QGLTexturePool::hibernate ()
Definition at line 180 of file qgltexturepool.cpp.
Referenced by QGLGraphicsSystem::createWindowSurface().
 {
     Q_D(QGLTexturePool);
     QGLTexture *texture = d->lruLast;
     while (texture) {
         QGLTexture *prevLRU = texture->prevLRU;
         texture->inTexturePool = false;
         texture->inLRU = false;
         texture->nextLRU = 0;
         texture->prevLRU = 0;
         if (texture->boundPixmap)
             texture->boundPixmap->hibernate();
         else
             QGLTextureCache::instance()->remove(texture->boundKey);
         texture = prevLRU;
     }
     d->lruFirst = 0;
     d->lruLast = 0;
 }
instance()
QGLTexturePool * QGLTexturePool::instance () static
Definition at line 70 of file qgltexturepool.cpp.
Referenced by QGLGraphicsSystem::createWindowSurface().
 {
     if (!qt_gl_texture_pool)
         qt_gl_texture_pool = new QGLTexturePool();
     return qt_gl_texture_pool;
 }
moveToHeadOfLRU()
void QGLTexturePool::moveToHeadOfLRU (QGLTexture * texture) protected
Definition at line 200 of file qgltexturepool.cpp.
Referenced by createTexture(), reclaimSpace(), and useTexture().
 {
     Q_D(QGLTexturePool);
     if (texture->inLRU) {
         if (!texture->prevLRU)
             return;     // Already at the head of the list.
         removeFromLRU(texture);
     }
     texture->inLRU = true;
     texture->nextLRU = d->lruFirst;
     texture->prevLRU = 0;
     if (d->lruFirst)
         d->lruFirst->prevLRU = texture;
     else
         d->lruLast = texture;
     d->lruFirst = texture;
 }
reclaimSpace()
bool QGLTexturePool::reclaimSpace (GLint internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, QGLTexture * data)
Definition at line 145 of file qgltexturepool.cpp.
Referenced by createPermanentTexture(), and createTexture().
 {
     Q_UNUSED(internalformat);   // For future use in picking the best texture to eject.
     Q_UNUSED(width);
     Q_UNUSED(height);
     Q_UNUSED(format);
     Q_UNUSED(type);
     bool succeeded = false;
     bool wasInLRU = false;
     if (texture) {
         wasInLRU = texture->inLRU;
         moveToHeadOfLRU(texture);
     }
     QGLTexture *lrutexture = textureLRU();
     if (lrutexture && lrutexture != texture) {
         if (lrutexture->boundPixmap)
             lrutexture->boundPixmap->reclaimTexture();
         else
             QGLTextureCache::instance()->remove(lrutexture->boundKey);
         succeeded = true;
     }
     if (texture && !wasInLRU)
         removeFromLRU(texture);
     return succeeded;
 }
removeFromLRU()
void QGLTexturePool::removeFromLRU (QGLTexture * texture) protected
Definition at line 218 of file qgltexturepool.cpp.
Referenced by detachTexture(), moveToHeadOfLRU(), and reclaimSpace().
 {
     Q_D(QGLTexturePool);
     if (!texture->inLRU)
         return;
     if (texture->nextLRU)
         texture->nextLRU->prevLRU = texture->prevLRU;
     else
         d->lruLast = texture->prevLRU;
     if (texture->prevLRU)
         texture->prevLRU->nextLRU = texture->nextLRU;
     else
         d->lruFirst = texture->nextLRU;
     texture->inLRU = false;
 }
textureLRU()
QGLTexture * QGLTexturePool::textureLRU () protected
Definition at line 234 of file qgltexturepool.cpp.
Referenced by reclaimSpace().
 {
     Q_D(QGLTexturePool);
     return d->lruLast;
 }
useTexture()
void QGLTexturePool::useTexture (QGLTexture * texture)
Definition at line 133 of file qgltexturepool.cpp.
 {
     moveToHeadOfLRU(texture);
     texture->inTexturePool = true;
 }
Properties
d_ptr
QScopedPointer<QGLTexturePoolPrivate> QGLTexturePool::d_ptr private
Definition at line 136 of file qgltexturepool_p.h.
The documentation for this class was generated from the following files:
/src/opengl/qgltexturepool_p.h
/src/opengl/qgltexturepool.cpp