Qt 4.8: QDBusContext Class Reference
QDBusContext Class Reference
The QDBusContext class allows slots to determine the D-Bus context of the calls.
#include <qdbuscontext.h>
Public Functions
bool calledFromDBus () const
Returns true if we are processing a D-Bus call.
QDBusConnection connection () const
Returns the connection from which this call was received.
bool isDelayedReply () const
Returns true if this call will have a delayed reply.
const QDBusMessage & message () const
Returns the message that generated this call.
QDBusContext ()
Constructs an empty QDBusContext.
void sendErrorReply (const QString &name, const QString &msg=QString()) const
Sends an error name as a reply to the caller.
void sendErrorReply (QDBusError::ErrorType type, const QString &msg=QString()) const
Sends an error type as a reply to the caller.
void setDelayedReply (bool enable) const
Sets whether this call will have a delayed reply or not.
~QDBusContext ()
An empty destructor.
Properties
QDBusContextPrivate * d_ptr
Friends
class QDBusContextPrivate
Detailed Description
The QDBusContext class allows slots to determine the D-Bus context of the calls.
Since
4.3
Attention
Module: QtDBus
When a slot is called in an object due to a signal delivery or due to a remote method call, it is sometimes necessary to know the context in which that happened. In particular, if the slot determines that it wants to send the reply at a later opportunity or if it wants to reply with an error, the context is needed.
The QDBusContext class is an alternative to accessing the context that doesn't involve modifying the code generated by the QtDBus XML Compiler (qdbusxml2cpp).
QDBusContext is used by subclassing it from the objects being exported using QDBusConnection::registerObject(). The following example illustrates the usage:
class MyObject: public QObject,
                protected QDBusContext
{
    Q_OBJECT
    QDBusConnection conn;
    QDBusMessage msg;
...
protected slots:
    void process();
public slots:
    void methodWithError();
    QString methodWithDelayedReply();
};
void MyObject::methodWithError()
{
    sendErrorReply(QDBusError::NotSupported,
                   "The method call 'methodWithError()' is not supported");
}
QString MyObject::methodWithDelayedReply()
{
    conn = connection();
    msg = message();
    setDelayedReply(true);
    QMetaObject::invokeMethod(this, "process", Qt::QueuedConnection);
    return QString();
}
The example illustrates the two typical uses, that of sending error replies and that of delayed replies.
Note: do not subclass QDBusContext and QDBusAbstractAdaptor at the same time. QDBusContext should appear in the real object, not the adaptor. If it's necessary from the adaptor code to determine the context, use a public inheritance and access the functions via QObject::parent().
Definition at line 60 of file qdbuscontext.h.
Constructors and Destructors
QDBusContext()
QDBusContext::QDBusContext ()
Constructs an empty QDBusContext.
Definition at line 110 of file qdbuscontext.cpp.
     : d_ptr(0)
 {
 }
~QDBusContext()
QDBusContext::~QDBusContext ()
An empty destructor.
Definition at line 118 of file qdbuscontext.cpp.
 {
 }
Functions
calledFromDBus()
bool QDBusContext::calledFromDBus () const
Returns true if we are processing a D-Bus call.
If this function returns true, the rest of the functions in this class are available.
Accessing those functions when this function returns false is undefined and may lead to crashes.
Definition at line 130 of file qdbuscontext.cpp.
 {
     return d_ptr;
 }
connection()
QDBusConnection QDBusContext::connection () const
Returns the connection from which this call was received.
Definition at line 138 of file qdbuscontext.cpp.
Referenced by sendErrorReply().
 {
     return d_ptr->connection;
 }
isDelayedReply()
bool QDBusContext::isDelayedReply () const
Returns true if this call will have a delayed reply.
See also
setDelayedReply()
Definition at line 156 of file qdbuscontext.cpp.
 {
     return message().isDelayedReply();
 }
message()
const QDBusMessage & QDBusContext::message () const
Returns the message that generated this call.
Definition at line 146 of file qdbuscontext.cpp.
Referenced by QNmDBusHelper::deviceStateChanged(), isDelayedReply(), QOfonoDBusHelper::propertyChanged(), QConnmanDBusHelper::propertyChanged(), sendErrorReply(), setDelayedReply(), QNmDBusHelper::slotAccessPointAdded(), QNmDBusHelper::slotAccessPointRemoved(), QNmDBusHelper::slotPropertiesChanged(), and QNmDBusHelper::slotSettingsRemoved().
 {
     return d_ptr->message;
 }
sendErrorReply() [1/2]
void QDBusContext::sendErrorReply (const QString & name, const QString & msg = QString()) const
Sends an error name as a reply to the caller.
The optional msg parameter is a human-readable text explaining the failure.
If an error is sent, the return value and any output parameters from the called slot will be ignored by QtDBus.
Definition at line 188 of file qdbuscontext.cpp.
 {
     setDelayedReply(true);
     connection().send(message().createErrorReply(name, msg));
 }
sendErrorReply() [2/2]
void QDBusContext::sendErrorReply (QDBusError::ErrorType type, const QString & msg = QString()) const
Sends an error type as a reply to the caller.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. The optional msg parameter is a human-readable text explaining the failure.
If an error is sent, the return value and any output parameters from the called slot will be ignored by QtDBus.
Definition at line 205 of file qdbuscontext.cpp.
 {
     setDelayedReply(true);
     connection().send(message().createErrorReply(type, msg));
 }
setDelayedReply()
void QDBusContext::setDelayedReply (bool enable) const
Sets whether this call will have a delayed reply or not.
If enable is false, QtDBus will automatically generate a reply back to the caller, if needed, as soon as the called slot returns.
If enable is true, QtDBus will not generate automatic replies. It will also ignore the return value from the slot and any output parameters. Instead, the called object is responsible for storing the incoming message and send a reply or error at a later time.
Failing to send a reply will result in an automatic timeout error being generated by D-Bus.
Definition at line 176 of file qdbuscontext.cpp.
Referenced by sendErrorReply().
 {
     message().setDelayedReply(enable);
 }
Friends and Related Functions
QDBusContextPrivate
friend class QDBusContextPrivate friend
Definition at line 79 of file qdbuscontext.h.
Properties
d_ptr
QDBusContextPrivate* QDBusContext::d_ptr private
Definition at line 78 of file qdbuscontext.h.
Referenced by calledFromDBus(), connection(), message(), and QDBusContextPrivate::set().
The documentation for this class was generated from the following files:
/src/dbus/qdbuscontext.h
/src/dbus/qdbuscontext.cpp