Qt 4.8: QDeclarativeCustomParserProperty Class Reference
QDeclarativeCustomParserProperty Class Reference
#include <qdeclarativecustomparser_p.h>
Public Functions
QList< QVariant > assignedValues () const
bool isList () const
QDeclarativeParser::Location location () const
QByteArray name () const
QDeclarativeCustomParserProperty & operator= (const QDeclarativeCustomParserProperty &)
QDeclarativeCustomParserProperty ()
QDeclarativeCustomParserProperty (const QDeclarativeCustomParserProperty &)
~QDeclarativeCustomParserProperty ()
Properties
QDeclarativeCustomParserPropertyPrivate * d
Friends
class QDeclarativeCustomParserNodePrivate
class QDeclarativeCustomParserPropertyPrivate
Detailed Description
Definition at line 73 of file qdeclarativecustomparser_p.h.
Constructors and Destructors
QDeclarativeCustomParserProperty() [1/2]
QDeclarativeCustomParserProperty::QDeclarativeCustomParserProperty ()
Definition at line 192 of file qdeclarativecustomparser.cpp.
 : d(new QDeclarativeCustomParserPropertyPrivate)
 {
 }
QDeclarativeCustomParserProperty() [2/2]
QDeclarativeCustomParserProperty::QDeclarativeCustomParserProperty (const QDeclarativeCustomParserProperty & other)
Definition at line 197 of file qdeclarativecustomparser.cpp.
 : d(new QDeclarativeCustomParserPropertyPrivate)
 {
     *this = other;
 }
~QDeclarativeCustomParserProperty()
QDeclarativeCustomParserProperty::~QDeclarativeCustomParserProperty ()
Definition at line 212 of file qdeclarativecustomparser.cpp.
 {
     delete d; d = 0;
 }
Functions
assignedValues()
QList< QVariant > QDeclarativeCustomParserProperty::assignedValues () const
Definition at line 232 of file qdeclarativecustomparser.cpp.
Referenced by QDeclarativeGestureAreaParser::compile(), QDeclarativeConnectionsParser::compile(), QDeclarativePropertyChangesParser::compileList(), and QDeclarativeListModelParser::compileProperty().
 {
     return d->values;
 }
isList()
bool QDeclarativeCustomParserProperty::isList () const
Definition at line 222 of file qdeclarativecustomparser.cpp.
 {
     return d->isList;
 }
location()
QDeclarativeParser::Location QDeclarativeCustomParserProperty::location () const
Definition at line 227 of file qdeclarativecustomparser.cpp.
Referenced by QDeclarativeCustomParser::error().
 {
     return d->location;
 }
name()
QByteArray QDeclarativeCustomParserProperty::name () const
Definition at line 217 of file qdeclarativecustomparser.cpp.
Referenced by QDeclarativeGestureAreaParser::compile(), QDeclarativeConnectionsParser::compile(), QDeclarativeListModelParser::compile(), QDeclarativePropertyChangesParser::compileList(), and QDeclarativeListModelParser::compileProperty().
 {
     return d->name;
 }
operator=()
QDeclarativeCustomParserProperty & QDeclarativeCustomParserProperty::operator= (const QDeclarativeCustomParserProperty & other)
Definition at line 203 of file qdeclarativecustomparser.cpp.
 {
     d->name = other.d->name;
     d->isList = other.d->isList;
     d->values = other.d->values;
     d->location = other.d->location;
     return *this;
 }
Friends and Related Functions
QDeclarativeCustomParserNodePrivate
friend class QDeclarativeCustomParserNodePrivate friend
Definition at line 90 of file qdeclarativecustomparser_p.h.
QDeclarativeCustomParserPropertyPrivate
friend class QDeclarativeCustomParserPropertyPrivate friend
Definition at line 91 of file qdeclarativecustomparser_p.h.
Properties
d
QDeclarativeCustomParserPropertyPrivate* QDeclarativeCustomParserProperty::d private
Definition at line 92 of file qdeclarativecustomparser_p.h.
Referenced by assignedValues(), QDeclarativeCustomParserNodePrivate::fromProperty(), isList(), location(), name(), operator=(), and ~QDeclarativeCustomParserProperty().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativecustomparser_p.h
/src/declarative/qml/qdeclarativecustomparser.cpp