Qt 4.8: QMacWindowFader Class Reference
QMacWindowFader Class Reference
#include <qt_mac_p.h>
Public Functions
float fadeDuration () const
void performFade ()
QMacWindowFader ()
void registerWindowToFade (QWidget *window)
void setFadeDuration (float durationInSecs)
Static Public Functions
static QMacWindowFader * currentFader ()
Properties
float m_duration
QWidgetList m_windowsToFade
Detailed Description
Definition at line 127 of file qt_mac_p.h.
Constructors and Destructors
QMacWindowFader()
QMacWindowFader::QMacWindowFader ()
Definition at line 104 of file qt_cocoa_helpers_mac.mm.
     : m_duration(0.250)
 {
 }
Functions
currentFader()
QMacWindowFader * QMacWindowFader::currentFader () static
Definition at line 109 of file qt_cocoa_helpers_mac.mm.
Referenced by QMenuPrivate::hideMenu(), QMenuPrivate::hideUpToMenuBar(), and macWindowFade().
 {
     return macwindowFader();
 }
fadeDuration()
float QMacWindowFader::fadeDuration () const inline
Definition at line 137 of file qt_mac_p.h.
 { return m_duration; }
performFade()
void QMacWindowFader::performFade ()
Definition at line 119 of file qt_cocoa_helpers_mac.mm.
Referenced by QMenuPrivate::hideUpToMenuBar(), and macWindowFade().
 {
     const QWidgetList myWidgetsToFade = m_windowsToFade;
     const int widgetCount = myWidgetsToFade.count();
 #if QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
     [NSAnimationContext beginGrouping];
     [[NSAnimationContext currentContext] setDuration:NSTimeInterval(m_duration)];
 #endif
     for (int i = 0; i < widgetCount; ++i) {
         QWidget *widget = m_windowsToFade.at(i);
         OSWindowRef window = qt_mac_window_for(widget);
 #if QT_MAC_USE_COCOA
         [[window animator] setAlphaValue:0.0];
         QTimer::singleShot(qRound(m_duration * 1000), widget, SLOT(hide()));
 #else
         TransitionWindowOptions options = {0, m_duration, 0, 0};
         TransitionWindowWithOptions(window, kWindowFadeTransitionEffect, kWindowHideTransitionAction,
                                     0, 1, &options);
 #endif
     }
 #if QT_MAC_USE_COCOA
     [NSAnimationContext endGrouping];
 #endif
     m_duration = 0.250;
     m_windowsToFade.clear();
 }
registerWindowToFade()
void QMacWindowFader::registerWindowToFade (QWidget * window)
Definition at line 114 of file qt_cocoa_helpers_mac.mm.
Referenced by QMenuPrivate::hideMenu(), and macWindowFade().
 {
     m_windowsToFade.append(window);
 }
setFadeDuration()
void QMacWindowFader::setFadeDuration (float durationInSecs) inline
Definition at line 136 of file qt_mac_p.h.
Referenced by QMenuPrivate::hideMenu(), and macWindowFade().
 { m_duration = durationInSecs; }
Properties
m_duration
float QMacWindowFader::m_duration private
Definition at line 130 of file qt_mac_p.h.
Referenced by performFade().
m_windowsToFade
QWidgetList QMacWindowFader::m_windowsToFade private
Definition at line 129 of file qt_mac_p.h.
Referenced by performFade(), and registerWindowToFade().
The documentation for this class was generated from the following files:
/src/gui/kernel/qt_mac_p.h
/src/gui/kernel/qt_cocoa_helpers_mac.mm