Qt 4.8: QAlphaPaintEngine Class Reference
QAlphaPaintEngine Class Reference
#include <qpaintengine_alpha_p.h>
Public Functions
virtual bool begin (QPaintDevice *pdev)
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
virtual void drawImage (const QRectF &r, const QImage &image, const QRectF &sr)
virtual void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
virtual void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
virtual void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawTextItem (const QPointF &p, const QTextItem &textItem)
This function draws the text item textItem at position p.
virtual void drawTiledPixmap (const QRectF &r, const QPixmap &pixmap, const QPointF &s)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
virtual bool end ()
Reimplement this function to finish painting on the current paint device.
virtual void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
~QAlphaPaintEngine ()
Public Functions inherited from QPaintEngine
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
virtual void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
virtual void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
virtual void drawImage (const QRectF &r, const QImage &pm, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
virtual void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
virtual void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
virtual void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
virtual void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual Type type () const =0
Reimplement this function to return the paint engine Type.
virtual ~QPaintEngine ()
Destroys the paint engine.
Protected Functions
QRegion alphaClipping () const
void cleanUp ()
bool continueCall () const
void flushAndInit (bool init=true)
QAlphaPaintEngine (QAlphaPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Additional Inherited Members
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 63 of file qpaintengine_alpha_p.h.
Constructors and Destructors
~QAlphaPaintEngine()
QAlphaPaintEngine::~QAlphaPaintEngine ()
Definition at line 60 of file qpaintengine_alpha.cpp.
 {
 }
QAlphaPaintEngine()
QAlphaPaintEngine::QAlphaPaintEngine (QAlphaPaintEnginePrivate & data, PaintEngineFeatures devcaps = 0) protected
Definition at line 54 of file qpaintengine_alpha.cpp.
     : QPaintEngine(data, devcaps)
 {
 }
Functions
alphaClipping()
QRegion QAlphaPaintEngine::alphaClipping () const protected
Definition at line 283 of file qpaintengine_alpha.cpp.
Referenced by QWin32PrintEngine::updateClipPath(), and QPdfBaseEngine::updateClipPath().
 {
     Q_D(const QAlphaPaintEngine);
     return d->m_cliprgn;
 }
begin()
bool QAlphaPaintEngine::begin (QPaintDevice * pdev) virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Implements QPaintEngine.
Reimplemented in QPdfBaseEngine, QPdfEngine, QPSPrintEngine, and QWin32PrintEngine.
Definition at line 65 of file qpaintengine_alpha.cpp.
Referenced by QWin32PrintEngine::begin(), and QPSPrintEngine::begin().
 {
     Q_D(QAlphaPaintEngine);
     d->m_continueCall = true;
     if (d->m_pass != 0) {
         return true;
     }
     d->m_savedcaps = gccaps;
     d->m_pdev = pdev;
     d->m_alphaPen = false;
     d->m_alphaBrush = false;
     d->m_alphaOpacity = false;
     d->m_hasalpha = false;
     d->m_advancedPen = false;
     d->m_advancedBrush = false;
     d->m_complexTransform = false;
     d->m_emulateProjectiveTransforms = false;
     // clear alpha region
     d->m_alphargn = QRegion();
     d->m_cliprgn = QRegion();
     d->m_pen = QPen();
     d->m_transform = QTransform();
     flushAndInit();
     return true;
 }
cleanUp()
void QAlphaPaintEngine::cleanUp () protected
Definition at line 370 of file qpaintengine_alpha.cpp.
Referenced by QWin32PrintEngine::begin(), QWin32PrintEngine::end(), and flushAndInit().
 {
     Q_D(QAlphaPaintEngine);
     delete d->m_picpainter;
     delete d->m_pic;
     d->m_picpainter = 0;
     d->m_pic = 0;
     d->m_picengine = 0;
 }
continueCall()
bool QAlphaPaintEngine::continueCall () const protected
Definition at line 289 of file qpaintengine_alpha.cpp.
Referenced by QWin32PrintEngine::begin(), QPSPrintEngine::begin(), QPSPrintEngine::drawImage(), QWin32PrintEngine::drawPath(), QPdfBaseEngine::drawPath(), QPSPrintEngine::drawPixmap(), QWin32PrintEngine::drawPixmap(), QWin32PrintEngine::drawPolygon(), QPdfBaseEngine::drawPolygon(), QPdfBaseEngine::drawRects(), QWin32PrintEngine::drawTextItem(), QPdfBaseEngine::drawTextItem(), QPSPrintEngine::drawTiledPixmap(), QWin32PrintEngine::drawTiledPixmap(), QWin32PrintEngine::end(), QPSPrintEngine::end(), QWin32PrintEngine::updateState(), and QPdfBaseEngine::updateState().
 {
     Q_D(const QAlphaPaintEngine);
     return d->m_continueCall;
 }
drawImage()
void QAlphaPaintEngine::drawImage (const QRectF & r, const QImage & image, const QRectF & sr) virtual
Definition at line 226 of file qpaintengine_alpha.cpp.
Referenced by QPSPrintEngine::drawImage().
 {
     Q_D(QAlphaPaintEngine);
     QRectF tr = d->m_transform.mapRect(r);
     if (d->m_pass == 0) {
         d->m_continueCall = false;
         if (image.hasAlphaChannel() || d->m_alphaOpacity || d->m_complexTransform) {
             d->addAlphaRect(tr);
         }
         if (d->m_picengine)
             d->m_picengine->drawImage(r, image, sr);
     } else {
         d->m_continueCall = !d->fullyContained(tr);
     }
 }
drawPath()
void QAlphaPaintEngine::drawPath (const QPainterPath & path) virtual
The default implementation ignores the path and does nothing.
Reimplemented from QPaintEngine.
Reimplemented in QPdfBaseEngine, and QWin32PrintEngine.
Definition at line 160 of file qpaintengine_alpha.cpp.
Referenced by QWin32PrintEngine::drawPath(), and QPdfBaseEngine::drawPath().
 {
     Q_D(QAlphaPaintEngine);
     QRectF tr = d->addPenWidth(path);
     if (d->m_pass == 0) {
         d->m_continueCall = false;
         if (d->m_hasalpha || d->m_advancedPen || d->m_advancedBrush
             || d->m_emulateProjectiveTransforms)
         {
             d->addAlphaRect(tr);
         }
         if (d->m_picengine)
             d->m_picengine->drawPath(path);
     } else {
         d->m_continueCall = !d->fullyContained(tr);
     }
 }
drawPixmap()
void QAlphaPaintEngine::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Implements QPaintEngine.
Reimplemented in QPdfEngine, QWin32PrintEngine, and QPSPrintEngine.
Definition at line 207 of file qpaintengine_alpha.cpp.
Referenced by QPSPrintEngine::drawPixmap(), and QWin32PrintEngine::drawPixmap().
 {
     Q_D(QAlphaPaintEngine);
     QRectF tr = d->m_transform.mapRect(r);
     if (d->m_pass == 0) {
         d->m_continueCall = false;
         if (pm.hasAlpha() || d->m_alphaOpacity || d->m_complexTransform || pm.isQBitmap()) {
             d->addAlphaRect(tr);
         }
         if (d->m_picengine)
             d->m_picengine->drawPixmap(r, pm, sr);
     } else {
         d->m_continueCall = !d->fullyContained(tr);
     }
 }
drawPolygon()
void QAlphaPaintEngine::drawPolygon (const QPointF * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QPaintEngine.
Reimplemented in QPdfBaseEngine, and QWin32PrintEngine.
Definition at line 180 of file qpaintengine_alpha.cpp.
Referenced by QWin32PrintEngine::drawPolygon(), and QPdfBaseEngine::drawPolygon().
 {
     Q_D(QAlphaPaintEngine);
     QPolygonF poly;
     for (int i=0; i<pointCount; ++i)
         poly.append(points[i]);
     QPainterPath path;
     path.addPolygon(poly);
     QRectF tr = d->addPenWidth(path);
     if (d->m_pass == 0) {
         d->m_continueCall = false;
         if (d->m_hasalpha || d->m_advancedPen || d->m_advancedBrush
             || d->m_emulateProjectiveTransforms)
         {
             d->addAlphaRect(tr);
         }
         if (d->m_picengine)
             d->m_picengine->drawPolygon(points, pointCount, mode);
     } else {
         d->m_continueCall = !d->fullyContained(tr);
     }
 }
drawTextItem()
void QAlphaPaintEngine::drawTextItem (const QPointF & p, const QTextItem & textItem) virtual
This function draws the text item textItem at position p.
The default implementation of this function converts the text to a QPainterPath and paints the resulting path.
Reimplemented from QPaintEngine.
Reimplemented in QPdfBaseEngine, and QWin32PrintEngine.
Definition at line 245 of file qpaintengine_alpha.cpp.
Referenced by QWin32PrintEngine::drawTextItem(), and QPdfBaseEngine::drawTextItem().
 {
     Q_D(QAlphaPaintEngine);
     QRectF tr(p.x(), p.y() - textItem.ascent(), textItem.width() + 5, textItem.ascent() + textItem.descent() + 5);
     tr = d->m_transform.mapRect(tr);
     if (d->m_pass == 0) {
         d->m_continueCall = false;
         if (d->m_alphaPen || d->m_alphaOpacity || d->m_advancedPen) {
             d->addAlphaRect(tr);
         }
         if (d->m_picengine) {
             d->m_picengine->drawTextItem(p, textItem);
         }
     } else {
         d->m_continueCall = !d->fullyContained(tr);
     }
 }
drawTiledPixmap()
void QAlphaPaintEngine::drawTiledPixmap (const QRectF & rect, const QPixmap & pixmap, const QPointF & p) virtual
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
The pixmap will be drawn repeatedly until the rect is filled.
Reimplemented from QPaintEngine.
Reimplemented in QPdfEngine, QWin32PrintEngine, and QPSPrintEngine.
Definition at line 265 of file qpaintengine_alpha.cpp.
Referenced by QPSPrintEngine::drawTiledPixmap(), and QWin32PrintEngine::drawTiledPixmap().
 {
     Q_D(QAlphaPaintEngine);
     QRectF brect = d->m_transform.mapRect(r);
     if (d->m_pass == 0) {
         d->m_continueCall = false;
         if (pixmap.hasAlpha() || d->m_alphaOpacity || d->m_complexTransform || pixmap.isQBitmap()) {
             d->addAlphaRect(brect);
         }
         if (d->m_picengine)
             d->m_picengine->drawTiledPixmap(r, pixmap, s);
     } else {
         d->m_continueCall = !d->fullyContained(brect);
     }
 }
end()
bool QAlphaPaintEngine::end () virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Implements QPaintEngine.
Reimplemented in QPdfBaseEngine, QPdfEngine, QPSPrintEngine, and QWin32PrintEngine.
Definition at line 97 of file qpaintengine_alpha.cpp.
Referenced by QWin32PrintEngine::end(), and QPSPrintEngine::end().
 {
     Q_D(QAlphaPaintEngine);
     d->m_continueCall = true;
     if (d->m_pass != 0) {
         return true;
     }
     flushAndInit(false);
     return true;
 }
flushAndInit()
void QAlphaPaintEngine::flushAndInit (bool init = true) protected
Definition at line 295 of file qpaintengine_alpha.cpp.
Referenced by begin(), end(), QPSPrintEngine::newPage(), and QWin32PrintEngine::newPage().
 {
     Q_D(QAlphaPaintEngine);
     Q_ASSERT(d->m_pass == 0);
     if (d->m_pic) {
         d->m_picpainter->end();
         // set clip region
         d->m_alphargn = d->m_alphargn.intersected(QRect(0, 0, d->m_pdev->width(), d->m_pdev->height()));
         // just use the bounding rect if it's a complex region..
         QVector<QRect> rects = d->m_alphargn.rects();
         if (rects.size() > 10) {
             QRect br = d->m_alphargn.boundingRect();
             d->m_alphargn = QRegion(br);
             rects.clear();
             rects.append(br);
         }
         d->m_cliprgn = d->m_alphargn;
         // now replay the QPicture
         ++d->m_pass; // we are now doing pass #2
         // reset states
         gccaps = d->m_savedcaps;
         painter()->save();
         d->resetState(painter());
         // make sure the output from QPicture is unscaled
         QTransform mtx;
         mtx.scale(1.0f / (qreal(d->m_pdev->logicalDpiX()) / qreal(qt_defaultDpiX())),
                   1.0f / (qreal(d->m_pdev->logicalDpiY()) / qreal(qt_defaultDpiY())));
         painter()->setTransform(mtx);
         painter()->drawPicture(0, 0, *d->m_pic);
         d->m_cliprgn = QRegion();
         d->resetState(painter());
         // fill in the alpha images
         for (int i=0; i<rects.size(); ++i)
             d->drawAlphaImage(rects.at(i));
         d->m_alphargn = QRegion();
         painter()->restore();
         --d->m_pass; // pass #2 finished
         cleanUp();
     }
     if (init) {
         gccaps = PaintEngineFeatures(AllFeatures & ~QPaintEngine::ObjectBoundingModeGradients);
         d->m_pic = new QPicture();
         d->m_pic->d_ptr->in_memory_only = true;
         d->m_picpainter = new QPainter(d->m_pic);
         d->m_picengine = d->m_picpainter->paintEngine();
         // When newPage() is called and the m_picpainter is recreated
         // we have to copy the current state of the original printer
         // painter back to the m_picpainter
         d->m_picpainter->setPen(painter()->pen());
         d->m_picpainter->setBrush(painter()->brush());
         d->m_picpainter->setBrushOrigin(painter()->brushOrigin());
         d->m_picpainter->setFont(painter()->font());
         d->m_picpainter->setOpacity(painter()->opacity());
         d->m_picpainter->setTransform(painter()->combinedTransform());
         d->m_picengine->syncState();
     }
 }
updateState()
void QAlphaPaintEngine::updateState (const QPaintEngineState & state) virtual
Reimplement this function to update the state of a paint engine.
When implemented, this function is responsible for checking the paint engine's current state and update the properties that are changed. Use the QPaintEngineState::state() function to find out which properties that must be updated, then use the corresponding GetFunction{get function} to retrieve the current values for the given properties.
See also
QPaintEngineState
Implements QPaintEngine.
Reimplemented in QPdfBaseEngine, and QWin32PrintEngine.
Definition at line 110 of file qpaintengine_alpha.cpp.
Referenced by QWin32PrintEngine::updateState(), and QPdfBaseEngine::updateState().
 {
     Q_D(QAlphaPaintEngine);
     DirtyFlags flags = state.state();
     if (flags & QPaintEngine::DirtyTransform) {
         d->m_transform = state.transform();
         d->m_complexTransform = (d->m_transform.type() > QTransform::TxScale);
         d->m_emulateProjectiveTransforms = !(d->m_savedcaps & QPaintEngine::PerspectiveTransform)
                                            && !(d->m_savedcaps & QPaintEngine::AlphaBlend)
                                            && (d->m_transform.type() >= QTransform::TxProject);
     }
     if (flags & QPaintEngine::DirtyPen) {
         d->m_pen = state.pen();
         if (d->m_pen.style() == Qt::NoPen) {
             d->m_advancedPen = false;
             d->m_alphaPen = false;
         } else {
             d->m_advancedPen = (d->m_pen.brush().style() != Qt::SolidPattern);
             d->m_alphaPen = !d->m_pen.brush().isOpaque();
         }
     }
     if (d->m_pass != 0) {
         d->m_continueCall = true;
         return;
     }
     d->m_continueCall = false;
     if (flags & QPaintEngine::DirtyOpacity) {
         d->m_alphaOpacity = (state.opacity() != 1.0f);
     }
     if (flags & QPaintEngine::DirtyBrush) {
         if (state.brush().style() == Qt::NoBrush) {
             d->m_advancedBrush = false;
             d->m_alphaBrush = false;
         } else {
             d->m_advancedBrush = (state.brush().style() != Qt::SolidPattern);
             d->m_alphaBrush = !state.brush().isOpaque();
         }
     }
     d->m_hasalpha = d->m_alphaOpacity || d->m_alphaBrush || d->m_alphaPen;
     if (d->m_picengine)
         d->m_picengine->updateState(state);
 }
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintengine_alpha_p.h
/src/gui/painting/qpaintengine_alpha.cpp