Qt 4.8: QCache< Key, T > Class Template Reference
QCache< Key, T > Class Template Reference
#include <qcache.h>
Classes
struct Node
Public Functions
void clear ()
bool contains (const Key &key) const
int count () const
bool insert (const Key &key, T *object, int cost=1)
bool isEmpty () const
QList< Key > keys () const
int maxCost () const
T * object (const Key &key) const
T * operator[] (const Key &key) const
QCache (int maxCost=100)
bool remove (const Key &key)
void setMaxCost (int m)
int size () const
T * take (const Key &key)
int totalCost () const
~QCache ()
Private Functions
T * relink (const Key &key)
void trim (int m)
void unlink (Node &n)
Properties
Node * f
QHash< Key, Node > hash
Node * l
int mx
int total
void * unused
Detailed Description
template<class Key, class T>
class QCache< Key, T >
Definition at line 54 of file qcache.h.
Constructors and Destructors
QCache()
template<class Key , class T > QCache< Key, T >::QCache (int maxCost = 100) inline explicit
Definition at line 134 of file qcache.h.
Referenced by QCache< QPixmapCache::Key, QPixmapCacheEntry >::relink().
     : f(0), l(0), unused(0), mx(amaxCost), total(0) {}
~QCache()
template<class Key, class T> QCache< Key, T >::~QCache () inline
Definition at line 103 of file qcache.h.
 { clear(); }
Functions
clear()
template<class Key , class T > void QCache< Key, T >::clear () inline
Definition at line 138 of file qcache.h.
Referenced by QPMCache::clear(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::keys(), and QCache< QPixmapCache::Key, QPixmapCacheEntry >::~QCache().
 { while (f) { delete f->t; f = f->n; }
  hash.clear(); l = 0; total = 0; }
contains()
template<class Key, class T> bool QCache< Key, T >::contains (const Key & key) const inline
Definition at line 118 of file qcache.h.
Referenced by QDirectFBPaintEnginePrivate::getSurface().
 { return hash.contains(key); }
count()
template<class Key, class T> int QCache< Key, T >::count () const inline
Definition at line 110 of file qcache.h.
 { return hash.size(); }
insert()
template<class Key, class T> bool QCache< Key, T >::insert (const Key & key, T * object, int cost = 1)
Definition at line 181 of file qcache.h.
Referenced by QDirectFBPaintEnginePrivate::getSurface(), QPMCache::insert(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::keys(), QPMCache::replace(), and QConfFileSettingsPrivate::~QConfFileSettingsPrivate().
 {
     remove(akey);
     if (acost > mx) {
         delete aobject;
         return false;
     }
     trim(mx - acost);
     Node sn(aobject, acost);
     typename QHash<Key, Node>::iterator i = hash.insert(akey, sn);
     total += acost;
     Node *n = &i.value();
     n->keyPtr = &i.key();
     if (f) f->p = n;
     n->n = f;
     f = n;
     if (!l) l = f;
     return true;
 }
isEmpty()
template<class Key, class T> bool QCache< Key, T >::isEmpty () const inline
Definition at line 111 of file qcache.h.
 { return hash.isEmpty(); }
keys()
template<class Key, class T> QList<Key> QCache< Key, T >::keys () const inline
Definition at line 112 of file qcache.h.
Referenced by QPMCache::clear().
 { return hash.keys(); }
maxCost()
template<class Key, class T> int QCache< Key, T >::maxCost () const inline
Definition at line 105 of file qcache.h.
Referenced by QDirectFBPaintEngine::drawImage(), QDirectFBPaintEnginePrivate::getSurface(), and QCache< QPixmapCache::Key, QPixmapCacheEntry >::relink().
 { return mx; }
object()
template<class Key, class T > T * QCache< Key, T >::object (const Key & key) const inline
Definition at line 147 of file qcache.h.
Referenced by QPMCache::allPixmaps(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::contains(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::keys(), QPMCache::object(), and QCache< QPixmapCache::Key, QPixmapCacheEntry >::operator[]().
 { return const_cast<QCache<Key,T>*>(this)->relink(key); }
operator[]()
template<class Key, class T > T * QCache< Key, T >::operator[] (const Key & key) const inline
Definition at line 151 of file qcache.h.
Referenced by QCache< QPixmapCache::Key, QPixmapCacheEntry >::contains().
 { return object(key); }
relink()
template<class Key, class T> T* QCache< Key, T >::relink (const Key & key) inline private
Definition at line 77 of file qcache.h.
Referenced by QCache< QPixmapCache::Key, QPixmapCacheEntry >::object().
{
         typename QHash<Key, Node>::iterator i = hash.find(key);
         if (typename QHash<Key, Node>::const_iterator(i) == hash.constEnd())
             return 0;
         Node &n = *i;
         if (f != &n) {
             if (n.p) n.p->n = n.n;
             if (n.n) n.n->p = n.p;
             if (l == &n) l = n.p;
             n.p = 0;
             n.n = f;
             f->p = &n;
             f = &n;
         }
         return n.t;
     }
remove()
template<class Key, class T > bool QCache< Key, T >::remove (const Key & key) inline
Definition at line 155 of file qcache.h.
Referenced by QPMCache::insert(), QPMCache::remove(), and QPMCache::replace().
 {
     typename QHash<Key, Node>::iterator i = hash.find(key);
     if (typename QHash<Key, Node>::const_iterator(i) == hash.constEnd()) {
         return false;
     } else {
         unlink(*i);
         return true;
     }
 }
setMaxCost()
template<class Key , class T > void QCache< Key, T >::setMaxCost (int m) inline
Definition at line 143 of file qcache.h.
Referenced by QDirectFBPaintEngine::drawBufferSpan(), and QCache< QPixmapCache::Key, QPixmapCacheEntry >::maxCost().
 { mx = m; trim(mx); }
size()
template<class Key, class T> int QCache< Key, T >::size () const inline
Definition at line 109 of file qcache.h.
 { return hash.size(); }
take()
template<class Key, class T > T * QCache< Key, T >::take (const Key & key) inline
Definition at line 167 of file qcache.h.
Referenced by QCache< QPixmapCache::Key, QPixmapCacheEntry >::contains(), QDirectFBPaintEngine::drawBufferSpan(), and QConfFile::fromName().
 {
     typename QHash<Key, Node>::iterator i = hash.find(key);
     if (i == hash.end())
         return 0;
     Node &n = *i;
     T *t = n.t;
     n.t = 0;
     unlink(n);
     return t;
 }
totalCost()
template<class Key, class T> int QCache< Key, T >::totalCost () const inline
Definition at line 107 of file qcache.h.
 { return total; }
trim()
template<class Key , class T > void QCache< Key, T >::trim (int m) private
Definition at line 202 of file qcache.h.
Referenced by QCache< QPixmapCache::Key, QPixmapCacheEntry >::contains(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::insert(), and QCache< QPixmapCache::Key, QPixmapCacheEntry >::setMaxCost().
 {
     Node *n = l;
     while (n && total > m) {
         Node *u = n;
         n = n->p;
         unlink(*u);
     }
 }
unlink()
template<class Key, class T> void QCache< Key, T >::unlink (Node & n) inline private
Definition at line 67 of file qcache.h.
Referenced by QCache< QPixmapCache::Key, QPixmapCacheEntry >::remove(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::take(), and QCache< QPixmapCache::Key, QPixmapCacheEntry >::trim().
{
         if (n.p) n.p->n = n.n;
         if (n.n) n.n->p = n.p;
         if (l == &n) l = n.p;
         if (f == &n) f = n.n;
         total -= n.c;
         T *obj = n.t;
         hash.remove(*n.keyPtr);
         delete obj;
     }
Properties
f
template<class Key, class T> Node* QCache< Key, T >::f private
Definition at line 62 of file qcache.h.
Referenced by QCache< QPixmapCache::Key, QPixmapCacheEntry >::clear(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::insert(), and QCache< QPixmapCache::Key, QPixmapCacheEntry >::relink().
hash
template<class Key, class T> QHash<Key, Node> QCache< Key, T >::hash private
Definition at line 63 of file qcache.h.
Referenced by QCache< QPixmapCache::Key, QPixmapCacheEntry >::clear(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::insert(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::remove(), and QCache< QPixmapCache::Key, QPixmapCacheEntry >::take().
l
template<class Key, class T> Node * QCache< Key, T >::l private
Definition at line 62 of file qcache.h.
Referenced by QCache< QPixmapCache::Key, QPixmapCacheEntry >::clear(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::insert(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::relink(), and QCache< QPixmapCache::Key, QPixmapCacheEntry >::trim().
mx
template<class Key, class T> int QCache< Key, T >::mx private
Definition at line 65 of file qcache.h.
Referenced by QCache< QPixmapCache::Key, QPixmapCacheEntry >::insert(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::maxCost(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::relink(), and QCache< QPixmapCache::Key, QPixmapCacheEntry >::setMaxCost().
total
template<class Key, class T> int QCache< Key, T >::total private
Definition at line 65 of file qcache.h.
Referenced by QCache< QPixmapCache::Key, QPixmapCacheEntry >::clear(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::insert(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::relink(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::totalCost(), and QCache< QPixmapCache::Key, QPixmapCacheEntry >::trim().
unused
template<class Key, class T> void* QCache< Key, T >::unused private
Definition at line 64 of file qcache.h.
The documentation for this class was generated from the following file:
/src/corelib/tools/qcache.h