Qt 4.8: QETWidget Class Reference
QETWidget Class Reference
Public Functions
QWidgetPrivate * d_func ()
QWidgetData * dataPtr ()
void doDeferredMap ()
QWidgetPrivate * dptr ()
void forceUpdate ()
QRect frameStrut () const
void hideChildren (bool spontaneous)
void markFrameStrutDirty ()
QTLWExtra * maybeTopData ()
bool raiseOnClick ()
void repaintDecoration (QRegion r, bool post)
void repolishStyle (QStyle &style)
void setWindowTitle_helper (const QString &title)
void showChildren (bool spontaneous)
void syncBackingStore (const QRegion &rgn)
void syncBackingStore ()
uint testWindowState (uint teststate)
QTLWExtra * topData ()
bool translateCloseEvent (const MSG &msg)
bool translateCloseEvent (const XEvent *)
bool translateConfigEvent (const MSG &msg)
bool translateConfigEvent (const XEvent *)
void translateEmbedEvent (const QWSEmbedEvent *event)
bool translateGestureEvent (const MSG &msg, const GESTUREINFO &gi)
bool translateKeyEvent (const QWSKeyEvent *, bool grab)
bool translateMouseEvent (const QWSMouseEvent *, int oldstate)
bool translateMouseEvent (const MSG &msg)
bool translateMouseEvent (const XEvent *)
bool translatePaintEvent (const MSG &msg)
void translatePaintEvent (const XEvent *)
bool translatePropertyEvent (const XEvent *)
bool translateRegionEvent (const QWSRegionEvent *)
bool translateScrollDoneEvent (const XEvent *)
bool translateTabletEvent (const MSG &msg, PACKET *localPacketBuf, int numPackets)
bool translateWheelEvent (const QWSMouseEvent *me)
bool translateWheelEvent (const MSG &msg)
bool translateWheelEvent (int global_x, int global_y, int delta, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers, Qt::Orientation orient)
bool translateXinputEvent (const XEvent *, QTabletDeviceData *tablet)
void updateRegion ()
bool winEvent (MSG *m, long *r)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
QWExtra * xtra ()
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
virtual QSize minimumSizeHint () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
virtual QSize sizeHint () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static bool sendSpontaneousEvent (QObject *r, QEvent *e)
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool event (QEvent *)
This is the main event handler; it handles event event.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyPressEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key press events for the widget.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
Definition at line 431 of file qapplication_qws.cpp.
Functions
d_func()
QWidgetPrivate* QETWidget::d_func () inline
Definition at line 570 of file qapplication_x11.cpp.
Referenced by QApplication::qwsProcessEvent(), and QApplication::x11ProcessEvent().
 { return QWidget::d_func(); }
dataPtr()
QWidgetData* QETWidget::dataPtr () inline
Definition at line 473 of file qapplication_win.cpp.
Referenced by QtWndProc().
 { return data; }
doDeferredMap()
void QETWidget::doDeferredMap () inline
Definition at line 583 of file qapplication_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
     {
         Q_ASSERT(testAttribute(Qt::WA_WState_Created));
         if (!testAttribute(Qt::WA_Resized)) {
             adjustSize();
             setAttribute(Qt::WA_Resized, false);
         }
         /*
           workaround for WM's that throw away ConfigureRequests from the following:
           window->hide();
           window->move(x, y); // could also be resize(), move()+resize(), or setGeometry()
           window->show();
         */
         QRect r = geometry();
         XMoveResizeWindow(X11->display,
                           internalWinId(),
                           r.x(),
                           r.y(),
                           r.width(),
                           r.height());
         // static gravity!
         XSizeHints sh;
         memset(&sh, 0, sizeof(sh));
         long unused;
         XGetWMNormalHints(X11->display, internalWinId(), &sh, &unused);
         sh.flags |= USPosition | PPosition | USSize | PSize | PWinGravity;
         sh.x = r.x();
         sh.y = r.y();
         sh.width = r.width();
         sh.height = r.height();
         sh.win_gravity = StaticGravity;
         XSetWMNormalHints(X11->display, internalWinId(), &sh);
         setAttribute(Qt::WA_Mapped);
         if (testAttribute(Qt::WA_DontShowOnScreen))
             return;
         d_func()->topData()->waitingForMapNotify = 1;
         XMapWindow(X11->display, internalWinId());
     }
dptr()
QWidgetPrivate* QETWidget::dptr () inline
Definition at line 474 of file qapplication_win.cpp.
Referenced by QtWndProc().
 { return d_func(); }
forceUpdate()
void QETWidget::forceUpdate () inline
Definition at line 492 of file qapplication_win.cpp.
{
         QTLWExtra *tlwExtra = window()->d_func()->maybeTopData();
         if (tlwExtra && tlwExtra->backingStore)
             tlwExtra->backingStore->markDirty(rect(), this, true, true);
     }
frameStrut()
QRect QETWidget::frameStrut () const inline
Definition at line 475 of file qapplication_win.cpp.
Referenced by QtWndProc().
 { return d_func()->frameStrut(); }
hideChildren()
void QETWidget::hideChildren (bool spontaneous) inline
Definition at line 489 of file qapplication_win.cpp.
Referenced by QtWndProc().
 { d_func()->hideChildren(spontaneous); }
markFrameStrutDirty()
void QETWidget::markFrameStrutDirty () inline
Definition at line 477 of file qapplication_win.cpp.
Referenced by QtWndProc().
 { data->fstrut_dirty = 1; }
maybeTopData()
QTLWExtra* QETWidget::maybeTopData () inline
Definition at line 470 of file qapplication_win.cpp.
 { return d_func()->maybeTopData(); }
raiseOnClick()
bool QETWidget::raiseOnClick () inline
Definition at line 444 of file qapplication_qws.cpp.
Referenced by QApplication::qwsProcessEvent().
     {
         // With limited windowmanagement/taskbar/etc., raising big windows
         // (eg. spreadsheet) over the top of everything else (eg. calculator)
         // is just annoying.
         return !isMaximized() && !isFullScreen();
     }
repaintDecoration()
void QETWidget::repaintDecoration (QRegion r, bool post)
Definition at line 3631 of file qapplication_qws.cpp.
Referenced by QApplication::qwsProcessEvent().
 {
     Q_UNUSED(post);
 #ifdef QT_NO_QWS_MANAGER
     Q_UNUSED(r);
 #else
     //please note that qwsManager is a QObject, not a QWidget.
     //therefore, normal ways of painting do not work.
     // However, it does listen to paint events.
     Q_D(QWidget);
     if (isWindow() && d->topData()->qwsManager && isVisible()) {
         QWSManager *manager = d->topData()->qwsManager;
         r &= manager->region();
         if (!r.isEmpty())
             manager->repaintRegion(QDecoration::All, QDecoration::Normal);
     }
 #endif
 }
repolishStyle()
void QETWidget::repolishStyle (QStyle & style)
Definition at line 3039 of file qapplication_win.cpp.
Referenced by QtWndProc().
 {
     QEvent e(QEvent::StyleChange);
     QApplication::sendEvent(this, &e);
 }
sendSpontaneousEvent()
static bool QETWidget::sendSpontaneousEvent (QObject * r, QEvent * e) inline static
Definition at line 587 of file qkeymapper_win.cpp.
Referenced by QKeyMapperPrivate::isADeadKey().
     { return QApplication::sendSpontaneousEvent(r, e); }
setWindowTitle_helper()
void QETWidget::setWindowTitle_helper (const QString & title) inline
Definition at line 491 of file qapplication_win.cpp.
Referenced by QtWndProc().
 { d_func()->setWindowTitle_helper(title); }
showChildren()
void QETWidget::showChildren (bool spontaneous) inline
Definition at line 488 of file qapplication_win.cpp.
Referenced by QtWndProc().
 { d_func()->showChildren(spontaneous); }
syncBackingStore() [1/2]
void QETWidget::syncBackingStore (const QRegion & rgn) inline
Definition at line 471 of file qapplication_win.cpp.
 { d_func()->syncBackingStore(rgn); }
syncBackingStore() [2/2]
void QETWidget::syncBackingStore () inline
Definition at line 472 of file qapplication_win.cpp.
 { d_func()->syncBackingStore(); }
testWindowState()
uint QETWidget::testWindowState (uint teststate) inline
Definition at line 490 of file qapplication_win.cpp.
Referenced by QtWndProc().
 { return dataPtr()->window_state & teststate; }
topData()
QTLWExtra* QETWidget::topData () inline
Definition at line 469 of file qapplication_win.cpp.
Referenced by QtWndProc().
 { return d_func()->topData(); }
translateCloseEvent() [1/2]
bool QETWidget::translateCloseEvent (const MSG & msg)
Definition at line 3963 of file qapplication_win.cpp.
Referenced by QtWndProc(), and QApplication::x11ClientMessage().
 {
     return d_func()->close_helper(QWidgetPrivate::CloseWithSpontaneousEvent);
 }
translateCloseEvent() [2/2]
bool QETWidget::translateCloseEvent (const XEvent *)
Definition at line 5446 of file qapplication_x11.cpp.
 {
     Q_D(QWidget);
     return d->close_helper(QWidgetPrivate::CloseWithSpontaneousEvent);
 }
translateConfigEvent() [1/2]
bool QETWidget::translateConfigEvent (const MSG & msg)
Definition at line 3832 of file qapplication_win.cpp.
Referenced by QtWndProc(), and QApplication::x11ProcessEvent().
 {
     if (!testAttribute(Qt::WA_WState_Created))                // in QWidget::create()
         return true;
     if (testAttribute(Qt::WA_WState_ConfigPending))
         return true;
     if (testAttribute(Qt::WA_DontShowOnScreen))
         return true;
     if (!isWindow())
         return true;
     setAttribute(Qt::WA_WState_ConfigPending);                // set config flag
     QRect cr = geometry();
     if (msg.message == WM_SIZE) {                // resize event
         WORD a = LOWORD(msg.lParam);
         WORD b = HIWORD(msg.lParam);
         QSize oldSize = size();
         QSize newSize(a, b);
 #ifdef Q_WS_WINCE_WM
         if (isFullScreen() && (oldSize.width() == newSize.height()) && (oldSize.height() == newSize.width()))
             qt_wince_hide_taskbar(internalWinId());
 #endif
         cr.setSize(newSize);
         if (msg.wParam != SIZE_MINIMIZED)
             data->crect = cr;
         if (isWindow()) {                        // update title/icon text
             d_func()->createTLExtra();
             // Capture SIZE_MINIMIZED without preceding WM_SYSCOMMAND
             // (like Windows+M)
             if (msg.wParam == SIZE_MINIMIZED && !isMinimized()) {
 #ifndef Q_WS_WINCE
                 const QString title = windowIconText();
                 if (!title.isEmpty())
                     d_func()->setWindowTitle_helper(title);
 #endif
                 data->window_state |= Qt::WindowMinimized;
                 if (isVisible()) {
                     QHideEvent e;
                     QApplication::sendSpontaneousEvent(this, &e);
                     hideChildren(true);
                 }
             } else if (msg.wParam != SIZE_MINIMIZED) {
                 bool window_state_changed = false;
                 Qt::WindowStates oldstate = Qt::WindowStates(dataPtr()->window_state);
                 if (isMinimized()) {
 #ifndef Q_WS_WINCE
                     const QString title = windowTitle();
                     if (!title.isEmpty())
                         d_func()->setWindowTitle_helper(title);
 #endif
                     data->window_state &= ~Qt::WindowMinimized;
                     showChildren(true);
                     QShowEvent e;
                     QApplication::sendSpontaneousEvent(this, &e);
                 // Capture SIZE_MAXIMIZED and SIZE_RESTORED without preceding WM_SYSCOMMAND
                 // (Aero Snap on Win7)
                 } else if (msg.wParam == SIZE_MAXIMIZED && !isMaximized()) {
                     data->window_state |= Qt::WindowMaximized;
                     window_state_changed = true;
                 } else if (msg.wParam == SIZE_RESTORED && isMaximized()) {
                     data->window_state &= ~(Qt::WindowMaximized);
                     window_state_changed = true;
                 }
                 if (window_state_changed) {
                     QWindowStateChangeEvent e(oldstate);
                     QApplication::sendSpontaneousEvent(this, &e);
                 }
             }
         }
         if (msg.wParam != SIZE_MINIMIZED && oldSize != newSize) {
             if (isVisible()) {
                 QTLWExtra *tlwExtra = maybeTopData();
                 static bool slowResize = qgetenv("QT_SLOW_TOPLEVEL_RESIZE").toInt();
                 const bool hasStaticContents = tlwExtra && tlwExtra->backingStore
                                                && tlwExtra->backingStore->hasStaticContents();
                 // If we have a backing store with static contents, we have to disable the top-level
                 // resize optimization in order to get invalidated regions for resized widgets.
                 // The optimization discards all invalidateBuffer() calls since we're going to
                 // repaint everything anyways, but that's not the case with static contents.
                 if (!slowResize && tlwExtra && !hasStaticContents)
                     tlwExtra->inTopLevelResize = true;
                 QResizeEvent e(newSize, oldSize);
                 QApplication::sendSpontaneousEvent(this, &e);
                 if (d_func()->paintOnScreen()) {
                     QRegion updateRegion(rect());
                     if (testAttribute(Qt::WA_StaticContents))
                         updateRegion -= QRect(0, 0, oldSize.width(), oldSize.height());
                     d_func()->syncBackingStore(updateRegion);
                 } else {
                     d_func()->syncBackingStore();
                 }
                 if (!slowResize && tlwExtra)
                     tlwExtra->inTopLevelResize = false;
             } else {
                 QResizeEvent *e = new QResizeEvent(newSize, oldSize);
                 QApplication::postEvent(this, e);
             }
         }
     } else if (msg.message == WM_MOVE) {        // move event
         int a = (int) (short) LOWORD(msg.lParam);
         int b = (int) (short) HIWORD(msg.lParam);
         QPoint oldPos = geometry().topLeft();
         QPoint newCPos(a, b);
         // Ignore silly Windows move event to wild pos after iconify.
 #if !defined(Q_WS_WINCE)
         if (!IsIconic(internalWinId()) && newCPos != oldPos) {
 #endif
             cr.moveTopLeft(newCPos);
             data->crect = cr;
             if (isVisible()) {
                 QMoveEvent e(newCPos, oldPos);  // cpos (client position)
                 QApplication::sendSpontaneousEvent(this, &e);
             } else {
                 QMoveEvent * e = new QMoveEvent(newCPos, oldPos);
                 QApplication::postEvent(this, e);
             }
 #if !defined(Q_WS_WINCE)
         }
 #endif
     }
     setAttribute(Qt::WA_WState_ConfigPending, false);                // clear config flag
     return true;
 }
translateConfigEvent() [2/2]
bool QETWidget::translateConfigEvent (const XEvent * event)
Definition at line 5268 of file qapplication_x11.cpp.
 {
     Q_ASSERT((!isWindow() && !testAttribute(Qt::WA_NativeWindow)) ? internalWinId() : true);
     Q_D(QWidget);
     bool wasResize = testAttribute(Qt::WA_WState_ConfigPending); // set in QWidget::setGeometry_sys()
     setAttribute(Qt::WA_WState_ConfigPending, false);
     if (testAttribute(Qt::WA_OutsideWSRange)) {
         // discard events for windows that have a geometry X can't handle
         XEvent xevent;
         while (XCheckTypedWindowEvent(X11->display,internalWinId(), ConfigureNotify,&xevent) &&
                !qt_x11EventFilter(&xevent)  &&
                !x11Event(&xevent)) // send event through filter
             ;
         return true;
     }
     const QSize oldSize = size();
     if (isWindow()) {
         QPoint newCPos(geometry().topLeft());
         QSize  newSize(event->xconfigure.width, event->xconfigure.height);
         bool trust = isVisible()
                      && (d->topData()->parentWinId == XNone ||
                          d->topData()->parentWinId == QX11Info::appRootWindow());
         bool isCPos = false;
         if (event->xconfigure.send_event || trust) {
             // if a ConfigureNotify comes from a real sendevent request, we can
             // trust its values.
             newCPos.rx() = event->xconfigure.x + event->xconfigure.border_width;
             newCPos.ry() = event->xconfigure.y + event->xconfigure.border_width;
             isCPos = true;
         }
         if (isVisible())
             QApplication::syncX();
         if (d->extra->compress_events) {
             // ConfigureNotify compression for faster opaque resizing
             XEvent otherEvent;
             while (XCheckTypedWindowEvent(X11->display, internalWinId(), ConfigureNotify,
                                           &otherEvent)) {
                 if (qt_x11EventFilter(&otherEvent))
                     continue;
                 if (x11Event(&otherEvent))
                     continue;
                 if (otherEvent.xconfigure.event != otherEvent.xconfigure.window)
                     continue;
                 newSize.setWidth(otherEvent.xconfigure.width);
                 newSize.setHeight(otherEvent.xconfigure.height);
                 if (otherEvent.xconfigure.send_event || trust) {
                     newCPos.rx() = otherEvent.xconfigure.x +
                                    otherEvent.xconfigure.border_width;
                     newCPos.ry() = otherEvent.xconfigure.y +
                                    otherEvent.xconfigure.border_width;
                     isCPos = true;
                 }
             }
 #ifndef QT_NO_XSYNC
             qt_sync_request_event_data sync_event;
             sync_event.window = internalWinId();
             for (XEvent ev;;) {
                 if (!XCheckIfEvent(X11->display, &ev, &qt_sync_request_scanner, (XPointer)&sync_event))
                     break;
             }
 #endif // QT_NO_XSYNC
         }
         if (!isCPos) {
             // we didn't get an updated position of the toplevel.
             // either we haven't moved or there is a bug in the window manager.
             // anyway, let's query the position to be certain.
             int x, y;
             Window child;
             XTranslateCoordinates(X11->display, internalWinId(),
                                   QApplication::desktop()->screen(d->xinfo.screen())->internalWinId(),
                                   0, 0, &x, &y, &child);
             newCPos.rx() = x;
             newCPos.ry() = y;
         }
         QRect cr (geometry());
         if (newCPos != cr.topLeft()) { // compare with cpos (exluding frame)
             QPoint oldPos = geometry().topLeft();
             cr.moveTopLeft(newCPos);
             data->crect = cr;
             if (isVisible()) {
                 QMoveEvent e(newCPos, oldPos); // pos (including frame), not cpos
                 QApplication::sendSpontaneousEvent(this, &e);
             } else {
                 setAttribute(Qt::WA_PendingMoveEvent, true);
             }
         }
         if (newSize != cr.size()) { // size changed
             cr.setSize(newSize);
             data->crect = cr;
             uint old_state = data->window_state;
             if (!X11->isSupportedByWM(ATOM(_NET_WM_STATE_MAXIMIZED_VERT))
                 && !X11->isSupportedByWM(ATOM(_NET_WM_STATE_MAXIMIZED_HORZ)))
                 data->window_state &= ~Qt::WindowMaximized;
             if (!X11->isSupportedByWM(ATOM(_NET_WM_STATE_FULLSCREEN)))
                 data->window_state &= ~Qt::WindowFullScreen;
             if (old_state != data->window_state) {
                 QWindowStateChangeEvent e((Qt::WindowStates) old_state);
                 QApplication::sendEvent(this, &e);
             }
             if (!isVisible())
                 setAttribute(Qt::WA_PendingResizeEvent, true);
             wasResize = true;
         }
     } else {
         XEvent xevent;
         while (XCheckTypedWindowEvent(X11->display,internalWinId(), ConfigureNotify,&xevent) &&
                !qt_x11EventFilter(&xevent)  &&
                !x11Event(&xevent)) // send event through filter
             ;
     }
     if (wasResize) {
         if (isVisible() && data->crect.size() != oldSize) {
             Q_ASSERT(d->extra->topextra);
             QWidgetBackingStore *bs = d->extra->topextra->backingStore.data();
             const bool hasStaticContents = bs && bs->hasStaticContents();
             // If we have a backing store with static contents, we have to disable the top-level
             // resize optimization in order to get invalidated regions for resized widgets.
             // The optimization discards all invalidateBuffer() calls since we're going to
             // repaint everything anyways, but that's not the case with static contents.
             if (!hasStaticContents)
                 d->extra->topextra->inTopLevelResize = true;
             QResizeEvent e(data->crect.size(), oldSize);
             QApplication::sendSpontaneousEvent(this, &e);
         }
         const bool waitingForMapNotify = d->extra->topextra && d->extra->topextra->waitingForMapNotify;
         if (!waitingForMapNotify) {
             if (d->paintOnScreen()) {
                 QRegion updateRegion(rect());
                 if (testAttribute(Qt::WA_StaticContents))
                     updateRegion -= QRect(0, 0, oldSize.width(), oldSize.height());
                 d->syncBackingStore(updateRegion);
             } else {
                 d->syncBackingStore();
             }
         }
         if (d->extra && d->extra->topextra)
             d->extra->topextra->inTopLevelResize = false;
     }
 #ifndef QT_NO_XSYNC
     if (QTLWExtra *tlwExtra = d->maybeTopData()) {
         if (tlwExtra->newCounterValueLo != 0 || tlwExtra->newCounterValueHi != 0) {
             XSyncValue value;
             XSyncIntsToValue(&value,
                              tlwExtra->newCounterValueLo,
                              tlwExtra->newCounterValueHi);
             XSyncSetCounter(X11->display, tlwExtra->syncUpdateCounter, value);
             tlwExtra->newCounterValueHi = 0;
             tlwExtra->newCounterValueLo = 0;
         }
     }
 #endif
     return true;
 }
translateEmbedEvent()
void QETWidget::translateEmbedEvent (const QWSEmbedEvent * event)
Definition at line 3621 of file qapplication_qws.cpp.
Referenced by QApplication::qwsProcessEvent().
 {
     if (event->simpleData.type | QWSEmbedEvent::Region) {
         const QRegion region = event->region;
         setGeometry(region.boundingRect());
         setVisible(!region.isEmpty());
     }
 }
translateGestureEvent()
bool QETWidget::translateGestureEvent (const MSG & msg, const GESTUREINFO & gi)
Definition at line 3969 of file qapplication_win.cpp.
 {
     const QPoint widgetPos = QPoint(gi.ptsLocation.x, gi.ptsLocation.y);
     QWidget *alienWidget = !internalWinId() ? this : childAt(widgetPos);
     if (alienWidget && alienWidget->internalWinId())
         alienWidget = 0;
     QWidget *widget = alienWidget ? alienWidget : this;
     QNativeGestureEvent event;
     event.sequenceId = gi.dwSequenceID;
     event.position = QPoint(gi.ptsLocation.x, gi.ptsLocation.y);
     event.argument = gi.ullArguments;
     switch (gi.dwID) {
     case GID_BEGIN:
         event.gestureType = QNativeGestureEvent::GestureBegin;
         break;
     case GID_END:
         event.gestureType = QNativeGestureEvent::GestureEnd;
         break;
     case GID_ZOOM:
         event.gestureType = QNativeGestureEvent::Zoom;
         break;
     case GID_PAN:
         event.gestureType = QNativeGestureEvent::Pan;
         break;
     case GID_ROTATE:
         event.gestureType = QNativeGestureEvent::Rotate;
         break;
     case GID_TWOFINGERTAP:
     case GID_ROLLOVER:
     default:
         break;
     }
     if (event.gestureType != QNativeGestureEvent::None)
         qt_sendSpontaneousEvent(widget, &event);
     return true;
 }
translateKeyEvent()
bool QETWidget::translateKeyEvent (const QWSKeyEvent * event, bool grab)
Definition at line 3552 of file qapplication_qws.cpp.
Referenced by QApplication::qwsProcessEvent().
 {
     int code = -1;
     //### Qt assumes keyboard state is state *before*, while QWS uses state after the event
     static Qt::KeyboardModifiers oldstate;
     Qt::KeyboardModifiers state = oldstate;
     oldstate = event->simpleData.modifiers;
     if (sm_blockUserInput) // block user interaction during session management
         return true;
     if (!isEnabled())
         return true;
     QEvent::Type type = event->simpleData.is_press ?
                         QEvent::KeyPress : QEvent::KeyRelease;
     bool autor = event->simpleData.is_auto_repeat;
     QString text;
     if (event->simpleData.unicode && event->simpleData.unicode != 0xffff)
         text += QChar(event->simpleData.unicode);
     code = event->simpleData.keycode;
 #if defined QT3_SUPPORT && !defined(QT_NO_SHORTCUT)
     if (type == QEvent::KeyPress && !grab
         && static_cast<QApplicationPrivate*>(qApp->d_ptr.data())->use_compat()) {
         // send accel events if the keyboard is not grabbed
         QKeyEvent a(type, code, state, text, autor, int(text.length()));
         if (static_cast<QApplicationPrivate*>(qApp->d_ptr.data())->qt_tryAccelEvent(this, &a))
             return true;
     }
 #else
     Q_UNUSED(grab);
 #endif
     if (!text.isEmpty() && testAttribute(Qt::WA_KeyCompression)) {
         // the widget wants key compression so it gets it
         // XXX not implemented
     }
     QKeyEvent e(type, code, state, text, autor, int(text.length()));
     return QApplication::sendSpontaneousEvent(this, &e);
 }
translateMouseEvent() [1/3]
bool QETWidget::translateMouseEvent (const QWSMouseEvent * event, int oldstate)
Definition at line 3330 of file qapplication_qws.cpp.
Referenced by QtWndProc(), QApplication::qwsProcessEvent(), and QApplication::x11ProcessEvent().
 {
     static bool manualGrab = false;
     QPoint pos;
     QPoint globalPos;
     int button = 0;
     if (sm_blockUserInput) // block user interaction during session management
         return true;
     const QWSMouseEvent::SimpleData &mouse = event->simpleData;
     pos = mapFromGlobal(QPoint(mouse.x_root, mouse.y_root));
 //     if (qt_last_x) {
 //         *qt_last_x=mouse.x_root;
 //         *qt_last_y=mouse.y_root;
 //     }
     globalPos.rx() = mouse.x_root;
     globalPos.ry() = mouse.y_root;
     QEvent::Type type = QEvent::None;
     Qt::MouseButtons buttonstate = Qt::MouseButtons(mouse.state & Qt::MouseButtonMask);
     Qt::KeyboardModifiers keystate = Qt::KeyboardModifiers(mouse.state & Qt::KeyboardModifierMask);
     if (mouse.state == prevstate) {
         // mouse move
         type = QEvent::MouseMove;
     } else if ((mouse.state&AnyButton) != (prevstate&AnyButton)) {
         Qt::MouseButtons current_buttons = Qt::MouseButtons(prevstate&Qt::MouseButtonMask);
         for (button = Qt::LeftButton; !type && button <= Qt::MidButton; button<<=1) {
             if ((mouse.state&button) != (current_buttons&button)) {
                 // button press or release
                 current_buttons = Qt::MouseButtons(current_buttons ^ button);
 #ifndef QT_NO_QWS_INPUTMETHODS
                 //############ We used to do a QInputContext::reset(oldFocus);
                 // when we changed the focus widget. See change 93389 for where the
                 // focus code went. The IM code was (after testing for ClickToFocus):
                 //if (mouse.state&button && w != QInputContext::microFocusWidget()) //button press
                 //        QInputContext::reset(oldFocus);
 #endif
                 if (mouse.state&button) { //button press
                     qt_button_down = childAt(pos);
                     if (!qt_button_down)
                         qt_button_down = this;
                     if (/*XXX mouseActWindow == this &&*/
                         mouseButtonPressed == button &&
                         long(mouse.time) -long(mouseButtonPressTime)
                             < QApplication::doubleClickInterval() &&
                         qAbs(mouse.x_root - mouseXPos) < mouse_double_click_distance &&
                         qAbs(mouse.y_root - mouseYPos) < mouse_double_click_distance ) {
                         type = QEvent::MouseButtonDblClick;
                         mouseButtonPressTime -= 2000;        // no double-click next time
                     } else {
                         type = QEvent::MouseButtonPress;
                         mouseButtonPressTime = mouse.time;
                     }
                     mouseButtonPressed = button;        // save event params for
                     mouseXPos = globalPos.x();                // future double click tests
                     mouseYPos = globalPos.y();
                 } else {                                // mouse button released
                     if (manualGrab) {                        // release manual grab
                         manualGrab = false;
                         // XXX XUngrabPointer(x11Display(), CurrentTime);
                     }
                     type = QEvent::MouseButtonRelease;
                 }
             }
         }
         button >>= 1;
     }
     //XXX mouseActWindow = winId();                        // save some event params
     if (type == 0) {                                // event consumed
         return false; //EXIT in the normal case
     }
     if (qApp->d_func()->inPopupMode()) {                        // in popup mode
         QWidget *popup = qApp->activePopupWidget();
         // in X11, this would be the window we are over.
         // in QWS this is the top level popup.  to allow mouse
         // events to other widgets, need to go through qApp->QApplicationPrivate::popupWidgets.
         QSize s(qt_screen->width(), qt_screen->height());
         for (int i = 0; i < QApplicationPrivate::popupWidgets->size(); ++i) {
             QWidget *w = QApplicationPrivate::popupWidgets->at(i);
             if ((w->windowType() == Qt::Popup) && w->d_func()->localAllocatedRegion().contains(globalPos - w->geometry().topLeft()))
             {
                 popup = w;
                 break;
             }
         }
         pos = popup->mapFromGlobal(globalPos);
         bool releaseAfter = false;
         QWidget *popupChild  = popup->childAt(pos);
         QWidget *popupTarget = popupChild ? popupChild : popup;
         if (popup != popupOfPopupButtonFocus){
             popupButtonFocus = 0;
             popupOfPopupButtonFocus = 0;
         }
         if (!popupTarget->isEnabled()) {
             return false; //EXIT special case
         }
         switch (type) {
             case QEvent::MouseButtonPress:
             case QEvent::MouseButtonDblClick:
                 popupButtonFocus = popupChild;
                 popupOfPopupButtonFocus = popup;
                 break;
             case QEvent::MouseButtonRelease:
                 releaseAfter = true;
                 break;
             default:
                 break;                                // nothing for mouse move
         }
         int oldOpenPopupCount = openPopupCount;
         if (popupButtonFocus) {
             QMouseEvent e(type, popupButtonFocus->mapFromGlobal(globalPos),
                         globalPos, Qt::MouseButton(button), buttonstate, keystate);
             QApplication::sendSpontaneousEvent(popupButtonFocus, & e);
             if (releaseAfter) {
                 popupButtonFocus = 0;
                 popupOfPopupButtonFocus = 0;
             }
         } else if (popupChild) {
             QMouseEvent e(type, popupChild->mapFromGlobal(globalPos),
                         globalPos, Qt::MouseButton(button), buttonstate, keystate);
             QApplication::sendSpontaneousEvent(popupChild, & e);
         } else {
             QMouseEvent e(type, pos, globalPos, Qt::MouseButton(button), buttonstate, keystate);
             QApplication::sendSpontaneousEvent(popupChild ? popupChild : popup, & e);
         }
 #ifndef QT_NO_CONTEXTMENU
         if (type == QEvent::MouseButtonPress && button == Qt::RightButton && (openPopupCount == oldOpenPopupCount)) {
             QWidget *popupEvent = popup;
             if(popupButtonFocus)
                 popupEvent = popupButtonFocus;
             else if(popupChild)
                 popupEvent = popupChild;
             QContextMenuEvent e(QContextMenuEvent::Mouse, pos, globalPos, keystate);
             QApplication::sendSpontaneousEvent(popupEvent, &e);
         }
 #endif // QT_NO_CONTEXTMENU
         if (releaseAfter)
             qt_button_down = 0;
     } else { //qApp not in popup mode
         QWidget *widget = this;
         QWidget *w = QWidget::mouseGrabber();
         if (!w && qt_button_down)
             w = qt_button_down;
         if (w && w != this) {
             widget = w;
             pos = mapToGlobal(pos);
             pos = w->mapFromGlobal(pos);
         }
         if (popupCloseDownMode) {
             popupCloseDownMode = false;
             if ((windowType() == Qt::Popup))        // ignore replayed event
                 return true; //EXIT
         }
         QPointer<QWidget> leaveAfterRelease = 0;
         if (type == QEvent::MouseButtonRelease &&
             (mouse.state & (~button) & (Qt::LeftButton |
                                     Qt::MidButton |
                                     Qt::RightButton)) == 0) {
             // Button released outside the widget -> leave the widget after the
             // release event has been delivered.
             if (widget == qt_button_down && (pos.x() < 0 || pos.y() < 0))
                 leaveAfterRelease = qt_button_down;
             qt_button_down = 0;
         }
         int oldOpenPopupCount = openPopupCount;
         QMouseEvent e(type, pos, globalPos, Qt::MouseButton(button), buttonstate, keystate);
 #ifndef QT_NO_QWS_MANAGER
         if (widget->isWindow() && widget->d_func()->topData()->qwsManager
             && (widget->d_func()->topData()->qwsManager->region().contains(globalPos)
                 || QWSManager::grabbedMouse() )) {
             if ((*mouseInWidget)) {
                 QApplicationPrivate::dispatchEnterLeave(0, *mouseInWidget);
                 (*mouseInWidget) = 0;
             }
             QApplication::sendSpontaneousEvent(widget->d_func()->topData()->qwsManager, &e);
             qApp->d_func()->last_manager = widget->d_func()->topData()->qwsManager;
         } else
 #endif
         {
             if (widget != (*mouseInWidget)) {
                 QApplicationPrivate::dispatchEnterLeave(widget, *mouseInWidget);
                 (*mouseInWidget) = widget;
                 qt_last_mouse_receiver = widget;
             }
             QApplication::sendSpontaneousEvent(widget, &e);
             if (leaveAfterRelease && !QWidget::mouseGrabber()) {
                 *mouseInWidget = QApplication::widgetAt(globalPos);
                 qt_last_mouse_receiver = *mouseInWidget;
                 QApplicationPrivate::dispatchEnterLeave(*mouseInWidget, leaveAfterRelease);
                 leaveAfterRelease = 0;
             }
         }
 #ifndef QT_NO_CONTEXTMENU
         if (type == QEvent::MouseButtonPress && button == Qt::RightButton && (openPopupCount == oldOpenPopupCount)) {
             QContextMenuEvent e(QContextMenuEvent::Mouse, pos, globalPos, keystate);
             QApplication::sendSpontaneousEvent(widget, &e);
         }
 #endif // QT_NO_CONTEXTMENU
     }
     return true;
 }
translateMouseEvent() [2/3]
bool QETWidget::translateMouseEvent (const MSG & msg)
Definition at line 3045 of file qapplication_win.cpp.
 {
     if (!isWindow() && testAttribute(Qt::WA_NativeWindow))
         Q_ASSERT(internalWinId());
     static QPoint pos;
     static POINT gpos={-1,-1};
     QEvent::Type type;                                // event parameters
     int           button;
     int           state;
     int           i;
     if (sm_blockUserInput) //block user interaction during session management
         return true;
     // Compress mouse move events
     if (msg.message == WM_MOUSEMOVE) {
         MSG mouseMsg;
         while (PeekMessage(&mouseMsg, msg.hwnd, WM_MOUSEFIRST,
                WM_MOUSELAST, PM_NOREMOVE)) {
             if (mouseMsg.message == WM_MOUSEMOVE) {
 #define PEEKMESSAGE_IS_BROKEN 1
 #ifdef PEEKMESSAGE_IS_BROKEN
                 // Since the Windows PeekMessage() function doesn't
                 // correctly return the wParam for WM_MOUSEMOVE events
                 // if there is a key release event in the queue
                 // _before_ the mouse event, we have to also consider
                 // key release events (kls 2003-05-13):
                 MSG keyMsg;
                 bool done = false;
                 while (PeekMessage(&keyMsg, 0, WM_KEYFIRST, WM_KEYLAST,
                        PM_NOREMOVE)) {
                     if (keyMsg.time < mouseMsg.time) {
                         if ((keyMsg.lParam & 0xC0000000) == 0x40000000) {
                             PeekMessage(&keyMsg, 0, keyMsg.message,
                                         keyMsg.message, PM_REMOVE);
                         } else {
                             done = true;
                             break;
                         }
                     } else {
                         break; // no key event before the WM_MOUSEMOVE event
                     }
                 }
                 if (done)
                     break;
 #else
                 // Actually the following 'if' should work instead of
                 // the above key event checking, but apparently
                 // PeekMessage() is broken :-(
                 if (mouseMsg.wParam != msg.wParam)
                     break; // leave the message in the queue because
                            // the key state has changed
 #endif
                 MSG *msgPtr = (MSG *)(&msg);
                 // Update the passed in MSG structure with the
                 // most recent one.
                 msgPtr->lParam = mouseMsg.lParam;
                 msgPtr->wParam = mouseMsg.wParam;
                 // Extract the x,y coordinates from the lParam as we do in the WndProc
                 msgPtr->pt.x = GET_X_LPARAM(mouseMsg.lParam);
                 msgPtr->pt.y = GET_Y_LPARAM(mouseMsg.lParam);
                 ClientToScreen(msg.hwnd, &(msgPtr->pt));
                 // Remove the mouse move message
                 PeekMessage(&mouseMsg, msg.hwnd, WM_MOUSEMOVE,
                             WM_MOUSEMOVE, PM_REMOVE);
             } else {
                 break; // there was no more WM_MOUSEMOVE event
             }
         }
     }
     for (i=0; (UINT)mouseTbl[i] != msg.message && mouseTbl[i]; i += 3)
         ;
     if (!mouseTbl[i])
         return false;
     type   = (QEvent::Type)mouseTbl[++i];        // event type
     button = mouseTbl[++i];                        // which button
     if (button == Qt::XButton1) {
         switch(GET_XBUTTON_WPARAM(msg.wParam)) {
         case XBUTTON1:
             button = Qt::XButton1;
             break;
         case XBUTTON2:
             button = Qt::XButton2;
             break;
         }
     }
 #ifndef Q_OS_WINCE
     static bool trackMouseEventLookup = false;
     typedef BOOL (WINAPI *PtrTrackMouseEvent)(LPTRACKMOUSEEVENT);
     static PtrTrackMouseEvent ptrTrackMouseEvent = 0;
 #endif
     state  = translateButtonState(msg.wParam, type, button); // button state
     const QPoint widgetPos = mapFromGlobal(QPoint(msg.pt.x, msg.pt.y));
     QWidget *alienWidget = !internalWinId() ? this : childAt(widgetPos);
     if (alienWidget && alienWidget->internalWinId())
         alienWidget = 0;
     if (type == QEvent::MouseMove || type == QEvent::NonClientAreaMouseMove
             || type == QEvent::TabletMove) {
         if (!(state & Qt::MouseButtonMask))
             qt_button_down = 0;
 #ifndef QT_NO_CURSOR
         QCursor *c = qt_grab_cursor();
         if (!c)
             c = QApplication::overrideCursor();
         if (c)                                // application cursor defined
             SetCursor(c->handle());
         else if (type != QEvent::NonClientAreaMouseMove && !qt_button_down) {
             // use  widget cursor if widget is enabled
             QWidget *w = alienWidget ? alienWidget : this;
             while (!w->isWindow() && !w->isEnabled())
                 w = w->parentWidget();
             SetCursor(w->cursor().handle());
         }
 #endif // QT_NO_CURSOR
         HWND id = effectiveWinId();
         QWidget *mouseGrabber = QWidget::mouseGrabber();
         QWidget *activePopupWidget = QApplication::activePopupWidget();
         if (mouseGrabber) {
             if (!activePopupWidget || (activePopupWidget == this && !rect().contains(widgetPos)))
                 id = mouseGrabber->effectiveWinId();
         } else if (type == QEvent::NonClientAreaMouseMove) {
             id = 0;
         }
         if (curWin != id) {                // new current window
             if (id == 0) {
                 QWidget *leave = qt_last_mouse_receiver;
                 if (!leave)
                     leave = QWidget::find(curWin);
                 QApplicationPrivate::dispatchEnterLeave(0, leave);
                 qt_last_mouse_receiver = 0;
                 curWin = 0;
             } else {
                 QWidget *leave = 0;
                 if (curWin && qt_last_mouse_receiver)
                     leave = qt_last_mouse_receiver;
                 else
                     leave = QWidget::find(curWin);
                 QWidget *enter = alienWidget ? alienWidget : this;
                 if (mouseGrabber && activePopupWidget) {
                     if (leave != mouseGrabber)
                         enter = mouseGrabber;
                     else
                         enter = activePopupWidget == this ? this : mouseGrabber;
                 }
                 QApplicationPrivate::dispatchEnterLeave(enter, leave);
                 qt_last_mouse_receiver = enter;
                 curWin = enter ? enter->effectiveWinId() : 0;
             }
 #ifndef Q_OS_WINCE
             if (curWin != 0) {
                 if (!trackMouseEventLookup) {
                     ptrTrackMouseEvent = (PtrTrackMouseEvent)QSystemLibrary::resolve(QLatin1String("comctl32"), "_TrackMouseEvent");
                     trackMouseEventLookup = true;
                 }
                 if (ptrTrackMouseEvent && !qApp->d_func()->inPopupMode()) {
                     // We always have to set the tracking, since
                     // Windows detects more leaves than we do..
                     TRACKMOUSEEVENT tme;
                     tme.cbSize = sizeof(TRACKMOUSEEVENT);
                     tme.dwFlags = 0x00000002;    // TME_LEAVE
                     tme.hwndTrack = curWin;      // Track on window receiving msgs
                     tme.dwHoverTime = (DWORD)-1; // HOVER_DEFAULT
                     ptrTrackMouseEvent(&tme);
                 }
             }
 #endif // Q_OS_WINCE
         }
         POINT curPos = msg.pt;
         if (curPos.x == gpos.x && curPos.y == gpos.y)
             return true;                        // same global position
         gpos = curPos;
         Q_ASSERT(testAttribute(Qt::WA_WState_Created));
         ScreenToClient(internalWinId(), &curPos);
         pos.rx() = curPos.x;
         pos.ry() = curPos.y;
         pos = d_func()->mapFromWS(pos);
     } else {
         gpos = msg.pt;
         pos = mapFromGlobal(QPoint(gpos.x, gpos.y));
         // mouse button pressed
         if (!qt_button_down && (type == QEvent::MouseButtonPress || type == QEvent::MouseButtonDblClick)) {
             QWidget *tlw = window();
             if (QWidget *child = tlw->childAt(mapTo(tlw, pos)))
                 qt_button_down = child;
             else
                 qt_button_down = this;
         }
     }
     bool res = false;
     bool nonClientAreaEvent = type >= QEvent::NonClientAreaMouseMove
                                 && type <= QEvent::NonClientAreaMouseButtonDblClick;
     if (qApp->d_func()->inPopupMode()) {                        // in popup mode
         if (nonClientAreaEvent)
             return false;
         replayPopupMouseEvent = false;
         QWidget* activePopupWidget = QApplication::activePopupWidget();
         QWidget *target = activePopupWidget;
         const QPoint globalPos(gpos.x, gpos.y);
         if (target != this) {
             if ((windowType() == Qt::Popup) && rect().contains(pos) && 0)
                 target = this;
             else                                // send to last popup
                 pos = target->mapFromGlobal(globalPos);
         }
         QWidget *popupChild = target->childAt(pos);
         bool releaseAfter = false;
         switch (type) {
             case QEvent::MouseButtonPress:
             case QEvent::MouseButtonDblClick:
                 popupButtonFocus = popupChild;
                 break;
             case QEvent::MouseButtonRelease:
             case QEvent::TabletRelease:
                 releaseAfter = true;
                 break;
             default:
                 break;                                // nothing for mouse move
         }
         if (target->isEnabled()) {
             if (popupButtonFocus) {
                 target = popupButtonFocus;
             } else if (popupChild) {
                 target = popupChild;
             }
             pos = target->mapFromGlobal(globalPos);
                 QMouseEvent e(type, pos, globalPos,
                             Qt::MouseButton(button),
                             Qt::MouseButtons(state & Qt::MouseButtonMask),
                             Qt::KeyboardModifiers(state & Qt::KeyboardModifierMask));
                 res = QApplicationPrivate::sendMouseEvent(target, &e, alienWidget, this, &qt_button_down,
                                                           qt_last_mouse_receiver);
             res = res && e.isAccepted();
         } else {
             // close disabled popups when a mouse button is pressed or released
             switch (type) {
             case QEvent::MouseButtonPress:
             case QEvent::MouseButtonDblClick:
             case QEvent::MouseButtonRelease:
                 target->close();
                 break;
             default:
                 break;
             }
         }
         if (releaseAfter) {
             popupButtonFocus = 0;
             qt_button_down = 0;
         }
 #ifndef Q_OS_WINCE
         if (type == QEvent::MouseButtonPress
             && QApplication::activePopupWidget() != activePopupWidget
             && ptrTrackMouseEvent
             && curWin) {
             // Since curWin is already the window we clicked on,
             // we have to setup the mouse tracking here.
             TRACKMOUSEEVENT tme;
             tme.cbSize = sizeof(TRACKMOUSEEVENT);
             tme.dwFlags = 0x00000002;    // TME_LEAVE
             tme.hwndTrack = curWin;      // Track on window receiving msgs
             tme.dwHoverTime = (DWORD)-1; // HOVER_DEFAULT
             ptrTrackMouseEvent(&tme);
         }
 #endif
         if (type == QEvent::MouseButtonPress
             && QApplication::activePopupWidget() != activePopupWidget
             && replayPopupMouseEvent) {
             // the popup disappeared. Replay the event
             QWidget* w = QApplication::widgetAt(gpos.x, gpos.y);
             if (w && !QApplicationPrivate::isBlockedByModal(w)) {
                 Q_ASSERT(w->testAttribute(Qt::WA_WState_Created));
                 HWND hwndTarget = w->effectiveWinId();
                 if (QWidget::mouseGrabber() == 0)
                     setAutoCapture(hwndTarget);
                 if (!w->isActiveWindow())
                     w->activateWindow();
                 POINT widgetpt = gpos;
                 ScreenToClient(hwndTarget, &widgetpt);
                 LPARAM lParam = MAKELPARAM(widgetpt.x, widgetpt.y);
                 PostMessage(hwndTarget, msg.message, msg.wParam, lParam);
             }
         } else if (type == QEvent::MouseButtonRelease && button == Qt::RightButton
                 && QApplication::activePopupWidget() == activePopupWidget) {
             // popup still alive and received right-button-release
 #if !defined(QT_NO_CONTEXTMENU)
             QContextMenuEvent e2(QContextMenuEvent::Mouse, pos, globalPos,
                               qt_win_getKeyboardModifiers());
             bool res2 = QApplication::sendSpontaneousEvent( target, &e2 );
             if (!res) // RMB not accepted
                 res = res2 && e2.isAccepted();
 #endif
         }
     } else {                                        // not popup mode
         int bs = state & Qt::MouseButtonMask;
         if ((type == QEvent::MouseButtonPress ||
               type == QEvent::MouseButtonDblClick) && bs == button) {
             Q_ASSERT(testAttribute(Qt::WA_WState_Created));
             if (QWidget::mouseGrabber() == 0)
                 setAutoCapture(internalWinId());
         } else if (type == QEvent::MouseButtonRelease && bs == 0) {
             if (QWidget::mouseGrabber() == 0)
                 releaseAutoCapture();
         }
         const QPoint globalPos(gpos.x,gpos.y);
         QWidget *widget = QApplicationPrivate::pickMouseReceiver(this, globalPos, pos, type,
                                                                  Qt::MouseButtons(bs),
                                                                  qt_button_down, alienWidget);
         if (!widget)
             return false; // don't send event
         QMouseEvent e(type, pos, globalPos, Qt::MouseButton(button),
                       Qt::MouseButtons(state & Qt::MouseButtonMask),
                       Qt::KeyboardModifiers(state & Qt::KeyboardModifierMask));
         res = QApplicationPrivate::sendMouseEvent(widget, &e, alienWidget, this, &qt_button_down,
                                                   qt_last_mouse_receiver);
         // non client area events are only informational, you cannot "handle" them
         res = res && e.isAccepted() && !nonClientAreaEvent;
 #if !defined(QT_NO_CONTEXTMENU)
         if (type == QEvent::MouseButtonRelease && button == Qt::RightButton) {
             QContextMenuEvent e2(QContextMenuEvent::Mouse, pos, globalPos,
                               qt_win_getKeyboardModifiers());
             bool res2 = QApplication::sendSpontaneousEvent(widget, &e2);
             if (!res)
                 res = res2 && e2.isAccepted();
         }
 #endif
         if (type != QEvent::MouseMove)
             pos.rx() = pos.ry() = -9999;        // init for move compression
     }
     return res;
 }
translateMouseEvent() [3/3]
bool QETWidget::translateMouseEvent (const XEvent * event)
Definition at line 4214 of file qapplication_x11.cpp.
 {
     if (!isWindow() && testAttribute(Qt::WA_NativeWindow))
         Q_ASSERT(internalWinId());
     Q_D(QWidget);
     QEvent::Type type;                                // event parameters
     QPoint pos;
     QPoint globalPos;
     Qt::MouseButton button = Qt::NoButton;
     Qt::MouseButtons buttons;
     Qt::KeyboardModifiers modifiers;
     XEvent nextEvent;
     if (qt_sm_blockUserInput) // block user interaction during session management
         return true;
     if (event->type == MotionNotify) { // mouse move
         if (event->xmotion.root != RootWindow(X11->display, x11Info().screen()) &&
             ! qt_xdnd_dragging)
             return false;
         XMotionEvent lastMotion = event->xmotion;
         while(XPending(X11->display))  { // compress mouse moves
             XNextEvent(X11->display, &nextEvent);
             if (nextEvent.type == ConfigureNotify
                 || nextEvent.type == PropertyNotify
                 || nextEvent.type == Expose
                 || nextEvent.type == GraphicsExpose
                 || nextEvent.type == NoExpose
                 || nextEvent.type == KeymapNotify
                 || ((nextEvent.type == EnterNotify || nextEvent.type == LeaveNotify)
                     && qt_button_down == this)
                 || (nextEvent.type == ClientMessage
                     && (nextEvent.xclient.message_type == ATOM(_QT_SCROLL_DONE) ||
                     (nextEvent.xclient.message_type == ATOM(WM_PROTOCOLS) &&
                      (Atom)nextEvent.xclient.data.l[0] == ATOM(_NET_WM_SYNC_REQUEST))))) {
                 // Pass the event through the event dispatcher filter so that applications
                 // which install an event filter on the dispatcher get to handle it first.
                 if (!QAbstractEventDispatcher::instance()->filterEvent(&nextEvent))
                     qApp->x11ProcessEvent(&nextEvent);
                 continue;
             } else if (nextEvent.type != MotionNotify ||
                        nextEvent.xmotion.window != event->xmotion.window ||
                        nextEvent.xmotion.state != event->xmotion.state) {
                 XPutBackEvent(X11->display, &nextEvent);
                 break;
             }
             if (!qt_x11EventFilter(&nextEvent)
                 && !x11Event(&nextEvent)) // send event through filter
                 lastMotion = nextEvent.xmotion;
             else
                 break;
         }
         type = QEvent::MouseMove;
         pos.rx() = lastMotion.x;
         pos.ry() = lastMotion.y;
         pos = d->mapFromWS(pos);
         globalPos.rx() = lastMotion.x_root;
         globalPos.ry() = lastMotion.y_root;
         buttons = translateMouseButtons(lastMotion.state);
         modifiers = X11->translateModifiers(lastMotion.state);
         if (qt_button_down && !buttons)
             qt_button_down = 0;
     } else if (event->type == EnterNotify || event->type == LeaveNotify) {
         XEvent *xevent = (XEvent *)event;
         //unsigned int xstate = event->xcrossing.state;
         type = QEvent::MouseMove;
         pos.rx() = xevent->xcrossing.x;
         pos.ry() = xevent->xcrossing.y;
         pos = d->mapFromWS(pos);
         globalPos.rx() = xevent->xcrossing.x_root;
         globalPos.ry() = xevent->xcrossing.y_root;
         buttons = translateMouseButtons(xevent->xcrossing.state);
         modifiers = X11->translateModifiers(xevent->xcrossing.state);
         if (qt_button_down && !buttons)
             qt_button_down = 0;
         if (qt_button_down)
             return true;
     } else {                                        // button press or release
         pos.rx() = event->xbutton.x;
         pos.ry() = event->xbutton.y;
         pos = d->mapFromWS(pos);
         globalPos.rx() = event->xbutton.x_root;
         globalPos.ry() = event->xbutton.y_root;
         buttons = translateMouseButtons(event->xbutton.state);
         modifiers = X11->translateModifiers(event->xbutton.state);
         switch (event->xbutton.button) {
         case Button1: button = Qt::LeftButton; break;
         case Button2: button = Qt::MidButton; break;
         case Button3: button = Qt::RightButton; break;
         case Button4:
         case Button5:
         case 6:
         case 7:
             // the fancy mouse wheel.
             // We are only interested in ButtonPress.
             if (event->type == ButtonPress){
                 // compress wheel events (the X Server will simply
                 // send a button press for each single notch,
                 // regardless whether the application can catch up
                 // or not)
                 int delta = 1;
                 XEvent xevent;
                 while (XCheckTypedWindowEvent(X11->display, effectiveWinId(), ButtonPress, &xevent)){
                     if (xevent.xbutton.button != event->xbutton.button){
                         XPutBackEvent(X11->display, &xevent);
                         break;
                     }
                     delta++;
                 }
                 // the delta is defined as multiples of
                 // WHEEL_DELTA, which is set to 120. Future wheels
                 // may offer a finer-resolution. A positive delta
                 // indicates forward rotation, a negative one
                 // backward rotation respectively.
                 int btn = event->xbutton.button;
                 delta *= 120 * ((btn == Button4 || btn == 6) ? 1 : -1);
                 bool hor = (((btn == Button4 || btn == Button5) && (modifiers & Qt::AltModifier)) ||
                             (btn == 6 || btn == 7));
                 translateWheelEvent(globalPos.x(), globalPos.y(), delta, buttons,
                                     modifiers, (hor) ? Qt::Horizontal: Qt::Vertical);
             }
             return true;
         case 8: button = Qt::XButton1; break;
         case 9: button = Qt::XButton2; break;
         }
         if (event->type == ButtonPress) {        // mouse button pressed
             buttons |= button;
 #if defined(Q_OS_IRIX) && !defined(QT_NO_TABLET)
             QTabletDeviceDataList *tablets = qt_tablet_devices();
             for (int i = 0; i < tablets->size(); ++i) {
                 QTabletDeviceData &tab = tablets->operator[](i);
                 XEvent myEv;
                 if (XCheckTypedEvent(X11->display, tab.xinput_button_press, &myEv)) {
                         if (translateXinputEvent(&myEv, &tab)) {
                             //Spontaneous event sent.  Check if we need to continue.
                             if (qt_tabletChokeMouse) {
                                 qt_tabletChokeMouse = false;
                                 return false;
                             }
                         }
                 }
             }
 #endif
             if (!qt_button_down) {
                 qt_button_down = childAt(pos);        //magic for masked widgets
                 if (!qt_button_down)
                     qt_button_down = this;
             }
             if (mouseActWindow == event->xbutton.window &&
                 mouseButtonPressed == button &&
                 (long)event->xbutton.time -(long)mouseButtonPressTime
                 < QApplication::doubleClickInterval() &&
                 qAbs(event->xbutton.x - mouseXPos) < QT_GUI_DOUBLE_CLICK_RADIUS &&
                 qAbs(event->xbutton.y - mouseYPos) < QT_GUI_DOUBLE_CLICK_RADIUS) {
                 type = QEvent::MouseButtonDblClick;
                 mouseButtonPressTime -= 2000;        // no double-click next time
             } else {
                 type = QEvent::MouseButtonPress;
                 mouseButtonPressTime = event->xbutton.time;
             }
             mouseButtonPressed = button;        // save event params for
             mouseXPos = event->xbutton.x;                // future double click tests
             mouseYPos = event->xbutton.y;
             mouseGlobalXPos = globalPos.x();
             mouseGlobalYPos = globalPos.y();
         } else {                                // mouse button released
             buttons &= ~button;
 #if defined(Q_OS_IRIX) && !defined(QT_NO_TABLET)
             QTabletDeviceDataList *tablets = qt_tablet_devices();
             for (int i = 0; i < tablets->size(); ++i) {
                 QTabletDeviceData &tab = tablets->operator[](i);
                 XEvent myEv;
                 if (XCheckTypedEvent(X11->display, tab.xinput_button_press, &myEv)) {
                         if (translateXinputEvent(&myEv, &tab)) {
                             //Spontaneous event sent.  Check if we need to continue.
                             if (qt_tabletChokeMouse) {
                                 qt_tabletChokeMouse = false;
                                 return false;
                             }
                         }
                 }
             }
 #endif
             type = QEvent::MouseButtonRelease;
         }
     }
     mouseActWindow = effectiveWinId();                        // save some event params
     mouseButtonState = buttons;
     if (type == 0)                                // don't send event
         return false;
     if (qApp->d_func()->inPopupMode()) {                        // in popup mode
         QWidget *activePopupWidget = qApp->activePopupWidget();
         QWidget *popup = qApp->activePopupWidget();
         if (popup != this) {
             if (event->type == LeaveNotify)
                 return false;
             if ((windowType() == Qt::Popup) && rect().contains(pos) && 0)
                 popup = this;
             else                                // send to last popup
                 pos = popup->mapFromGlobal(globalPos);
         }
         bool releaseAfter = false;
         QWidget *popupChild  = popup->childAt(pos);
         if (popup != qt_popup_down){
             qt_button_down = 0;
             qt_popup_down = 0;
         }
         switch (type) {
         case QEvent::MouseButtonPress:
         case QEvent::MouseButtonDblClick:
             qt_button_down = popupChild;
             qt_popup_down = popup;
             break;
         case QEvent::MouseButtonRelease:
             releaseAfter = true;
             break;
         default:
             break;                                // nothing for mouse move
         }
         int oldOpenPopupCount = openPopupCount;
         if (popup->isEnabled()) {
             // deliver event
             replayPopupMouseEvent = false;
             QWidget *receiver = popup;
             QPoint widgetPos = pos;
             if (qt_button_down)
                 receiver = qt_button_down;
             else if (popupChild)
                 receiver = popupChild;
             if (receiver != popup)
                 widgetPos = receiver->mapFromGlobal(globalPos);
             QWidget *alien = childAt(mapFromGlobal(globalPos));
             QMouseEvent e(type, widgetPos, globalPos, button, buttons, modifiers);
             QApplicationPrivate::sendMouseEvent(receiver, &e, alien, this, &qt_button_down, qt_last_mouse_receiver);
         } else {
             // close disabled popups when a mouse button is pressed or released
             switch (type) {
             case QEvent::MouseButtonPress:
             case QEvent::MouseButtonDblClick:
             case QEvent::MouseButtonRelease:
                 popup->close();
                 break;
             default:
                 break;
             }
         }
         if (qApp->activePopupWidget() != activePopupWidget
             && replayPopupMouseEvent) {
             // the active popup was closed, replay the mouse event
             if (!(windowType() == Qt::Popup)) {
 #if 1
                 qt_button_down = 0;
 #else
                 if (buttons == button)
                     qt_button_down = this;
                 QMouseEvent e(type, mapFromGlobal(globalPos), globalPos, button,
                               buttons, modifiers);
                 QApplication::sendSpontaneousEvent(this, &e);
                 if (type == QEvent::MouseButtonPress
                     && button == Qt::RightButton
                     && (openPopupCount == oldOpenPopupCount)) {
                     QContextMenuEvent e(QContextMenuEvent::Mouse, mapFromGlobal(globalPos),
                                         globalPos, modifiers);
                     QApplication::sendSpontaneousEvent(this, &e);
                 }
 #endif
             }
             replayPopupMouseEvent = false;
         } else if (type == QEvent::MouseButtonPress
                    && button == Qt::RightButton
                    && (openPopupCount == oldOpenPopupCount)) {
             QWidget *popupEvent = popup;
             if (qt_button_down)
                 popupEvent = qt_button_down;
             else if(popupChild)
                 popupEvent = popupChild;
             QContextMenuEvent e(QContextMenuEvent::Mouse, pos, globalPos, modifiers);
             QApplication::sendSpontaneousEvent(popupEvent, &e);
         }
         if (releaseAfter) {
             qt_button_down = 0;
             qt_popup_down = 0;
         }
     } else {
         QWidget *alienWidget = childAt(pos);
         QWidget *widget = QApplicationPrivate::pickMouseReceiver(this, globalPos, pos, type, buttons,
                                                                  qt_button_down, alienWidget);
         if (!widget) {
             if (type == QEvent::MouseButtonRelease)
                 QApplicationPrivate::mouse_buttons &= ~button;
             return false; // don't send event
         }
         int oldOpenPopupCount = openPopupCount;
         QMouseEvent e(type, pos, globalPos, button, buttons, modifiers);
         QApplicationPrivate::sendMouseEvent(widget, &e, alienWidget, this, &qt_button_down,
                                             qt_last_mouse_receiver);
         if (type == QEvent::MouseButtonPress
             && button == Qt::RightButton
             && (openPopupCount == oldOpenPopupCount)) {
             QContextMenuEvent e(QContextMenuEvent::Mouse, pos, globalPos, modifiers);
             QApplication::sendSpontaneousEvent(widget, &e);
         }
     }
     return true;
 }
translatePaintEvent() [1/2]
bool QETWidget::translatePaintEvent (const MSG & msg)
Definition at line 3784 of file qapplication_win.cpp.
Referenced by QtWndProc(), and QApplication::x11ProcessEvent().
 {
     if (!isWindow() && testAttribute(Qt::WA_NativeWindow))
         Q_ASSERT(internalWinId());
     Q_ASSERT(testAttribute(Qt::WA_WState_Created));
     if (!GetUpdateRect(internalWinId(), 0, FALSE)) { // The update bounding rect is invalid
         d_func()->hd = 0;
         setAttribute(Qt::WA_PendingUpdate, false);
         return false;
     }
     if (msg.message == WM_ERASEBKGND)
         return true;
     setAttribute(Qt::WA_PendingUpdate, false);
     if (d_func()->isGLWidget) {
         if (d_func()->usesDoubleBufferedGLContext)
             InvalidateRect(internalWinId(), 0, false);
     } else {
         const QRegion dirtyInBackingStore(qt_dirtyRegion(this));
         // Make sure the invalidated region contains the region we're about to repaint.
         // BeginPaint will set the clip to the invalidated region and it is impossible
         // to enlarge it afterwards (only shrink it). Using GetDCEx is not suffient
         // as it may return an invalid context (especially on Windows Vista).
         if (!dirtyInBackingStore.isEmpty())
             InvalidateRgn(internalWinId(), dirtyInBackingStore.handle(), false);
     }
     PAINTSTRUCT ps;
     d_func()->hd = BeginPaint(internalWinId(), &ps);
     const QRect updateRect(QPoint(ps.rcPaint.left, ps.rcPaint.top),
                            QPoint(ps.rcPaint.right, ps.rcPaint.bottom));
     // Mapping region from system to qt (32 bit) coordinate system.
     d_func()->syncBackingStore(updateRect.translated(data->wrect.topLeft()));
     d_func()->hd = 0;
     EndPaint(internalWinId(), &ps);
     return true;
 }
translatePaintEvent() [2/2]
void QETWidget::translatePaintEvent (const XEvent * event)
Definition at line 5206 of file qapplication_x11.cpp.
 {
     if (!isWindow() && testAttribute(Qt::WA_NativeWindow))
         Q_ASSERT(internalWinId());
     Q_D(QWidget);
     QRect  paintRect(event->xexpose.x, event->xexpose.y,
                      event->xexpose.width, event->xexpose.height);
     XEvent xevent;
     PaintEventInfo info;
     info.window = internalWinId();
     translateBySips(this, paintRect);
     paintRect = d->mapFromWS(paintRect);
     QRegion paintRegion = paintRect;
     // WARNING: this is O(number_of_events * number_of_matching_events)
     while (XCheckIfEvent(X11->display,&xevent,isPaintOrScrollDoneEvent,
                          (XPointer)&info) &&
            !qt_x11EventFilter(&xevent)  &&
            !x11Event(&xevent)) // send event through filter
     {
         if (xevent.type == Expose || xevent.type == GraphicsExpose) {
             QRect exposure(xevent.xexpose.x,
                            xevent.xexpose.y,
                            xevent.xexpose.width,
                            xevent.xexpose.height);
             translateBySips(this, exposure);
             exposure = d->mapFromWS(exposure);
             paintRegion |= exposure;
         } else {
             translateScrollDoneEvent(&xevent);
         }
     }
     if (!paintRegion.isEmpty() && !testAttribute(Qt::WA_WState_ConfigPending))
         d->syncBackingStore(paintRegion);
 }
translatePropertyEvent()
bool QETWidget::translatePropertyEvent (const XEvent * event)
Definition at line 4959 of file qapplication_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     Q_D(QWidget);
     if (!isWindow()) return true;
     Atom ret;
     int format, e;
     unsigned char *data = 0;
     unsigned long nitems, after;
     if (event->xproperty.atom == ATOM(_KDE_NET_WM_FRAME_STRUT)) {
         this->data->fstrut_dirty = 1;
         if (event->xproperty.state == PropertyNewValue) {
             e = XGetWindowProperty(X11->display, event->xproperty.window, ATOM(_KDE_NET_WM_FRAME_STRUT),
                                    0, 4, // struts are 4 longs
                                    False, XA_CARDINAL, &ret, &format, &nitems, &after, &data);
             if (e == Success && ret == XA_CARDINAL &&
                 format == 32 && nitems == 4) {
                 long *strut = (long *) data;
                 d->topData()->frameStrut.setCoords(strut[0], strut[2], strut[1], strut[3]);
                 this->data->fstrut_dirty = 0;
             }
         }
     } else if (event->xproperty.atom == ATOM(_NET_WM_STATE)) {
         bool max = false;
         bool full = false;
         Qt::WindowStates oldState = Qt::WindowStates(this->data->window_state);
         if (event->xproperty.state == PropertyNewValue) {
             // using length of 1024 should be safe for all current and
             // possible NET states...
             e = XGetWindowProperty(X11->display, event->xproperty.window, ATOM(_NET_WM_STATE), 0, 1024,
                                    False, XA_ATOM, &ret, &format, &nitems, &after, &data);
             if (e == Success && ret == XA_ATOM && format == 32 && nitems > 0) {
                 Atom *states = (Atom *) data;
                 unsigned long i;
                 uint maximized = 0;
                 for (i = 0; i < nitems; i++) {
                     if (states[i] == ATOM(_NET_WM_STATE_MAXIMIZED_VERT))
                         maximized |= 1;
                     else if (states[i] == ATOM(_NET_WM_STATE_MAXIMIZED_HORZ))
                         maximized |= 2;
                     else if (states[i] == ATOM(_NET_WM_STATE_FULLSCREEN))
                         full = true;
                 }
                 if (maximized == 3) {
                     // only set maximized if both horizontal and vertical properties are set
                     max = true;
                 }
             }
         }
         bool send_event = false;
         if (X11->isSupportedByWM(ATOM(_NET_WM_STATE_MAXIMIZED_VERT))
             && X11->isSupportedByWM(ATOM(_NET_WM_STATE_MAXIMIZED_HORZ))) {
             if (max && !isMaximized()) {
                 this->data->window_state = this->data->window_state | Qt::WindowMaximized;
                 send_event = true;
             } else if (!max && isMaximized()) {
                 this->data->window_state &= ~Qt::WindowMaximized;
                 send_event = true;
             }
         }
         if (X11->isSupportedByWM(ATOM(_NET_WM_STATE_FULLSCREEN))) {
             if (full && !isFullScreen()) {
                 this->data->window_state = this->data->window_state | Qt::WindowFullScreen;
                 send_event = true;
             } else if (!full && isFullScreen()) {
                 this->data->window_state &= ~Qt::WindowFullScreen;
                 send_event = true;
             }
         }
         if (send_event) {
             QWindowStateChangeEvent e(oldState);
             QApplication::sendSpontaneousEvent(this, &e);
         }
     } else if (event->xproperty.atom == ATOM(WM_STATE)) {
         // the widget frame strut should also be invalidated
         this->data->fstrut_dirty = 1;
         if (event->xproperty.state == PropertyDelete) {
             // the window manager has removed the WM State property,
             // so it is now in the withdrawn state (ICCCM 4.1.3.1) and
             // we are free to reuse this window
             d->topData()->parentWinId = 0;
             d->topData()->validWMState = 0;
             // map the window if we were waiting for a transition to
             // withdrawn
             if (X11->deferred_map.removeAll(this)) {
                 doDeferredMap();
             } else if (isVisible()
                        && !testAttribute(Qt::WA_Mapped)
                        && !testAttribute(Qt::WA_OutsideWSRange)) {
                 // so that show() will work again. As stated in the
                 // ICCCM section 4.1.4: "Only the client can effect a
                 // transition into or out of the Withdrawn state.",
                 // but apparently this particular window manager
                 // doesn't seem to care
                 setAttribute(Qt::WA_WState_ExplicitShowHide, false);
                 setAttribute(Qt::WA_WState_Visible, false);
             }
         } else {
             // the window manager has changed the WM State property...
             // we are wanting to see if we are withdrawn so that we
             // can reuse this window...
             e = XGetWindowProperty(X11->display, internalWinId(), ATOM(WM_STATE), 0, 2, False,
                                    ATOM(WM_STATE), &ret, &format, &nitems, &after, &data);
             if (e == Success && ret == ATOM(WM_STATE) && format == 32 && nitems > 0) {
                 long *state = (long *) data;
                 switch (state[0]) {
                 case WithdrawnState:
                     // if we are in the withdrawn state, we are free
                     // to reuse this window provided we remove the
                     // WM_STATE property (ICCCM 4.1.3.1)
                     XDeleteProperty(X11->display, internalWinId(), ATOM(WM_STATE));
                     // set the parent id to zero, so that show() will
                     // work again
                     d->topData()->parentWinId = 0;
                     d->topData()->validWMState = 0;
                     // map the window if we were waiting for a
                     // transition to withdrawn
                     if (X11->deferred_map.removeAll(this)) {
                         doDeferredMap();
                     } else if (isVisible()
                                && !testAttribute(Qt::WA_Mapped)
                                && !testAttribute(Qt::WA_OutsideWSRange)) {
                         // so that show() will work again. As stated
                         // in the ICCCM section 4.1.4: "Only the
                         // client can effect a transition into or out
                         // of the Withdrawn state.", but apparently
                         // this particular window manager doesn't seem
                         // to care
                         setAttribute(Qt::WA_WState_ExplicitShowHide, false);
                         setAttribute(Qt::WA_WState_Visible, false);
                     }
                     break;
                 case IconicState:
                     d->topData()->validWMState = 1;
                     if (!isMinimized()) {
                         // window was minimized
                         this->data->window_state = this->data->window_state | Qt::WindowMinimized;
                         QWindowStateChangeEvent e(Qt::WindowStates(this->data->window_state & ~Qt::WindowMinimized));
                         QApplication::sendSpontaneousEvent(this, &e);
                     }
                     break;
                 default:
                     d->topData()->validWMState = 1;
                     if (isMinimized()) {
                         // window was un-minimized
                         this->data->window_state &= ~Qt::WindowMinimized;
                         QWindowStateChangeEvent e(Qt::WindowStates(this->data->window_state | Qt::WindowMinimized));
                         QApplication::sendSpontaneousEvent(this, &e);
                     }
                     break;
                 }
             }
         }
     } else if (event->xproperty.atom == ATOM(_NET_WM_WINDOW_OPACITY)) {
         // the window opacity was changed
         if (event->xproperty.state == PropertyNewValue) {
             e = XGetWindowProperty(event->xclient.display,
                                    event->xclient.window,
                                    ATOM(_NET_WM_WINDOW_OPACITY),
                                    0, 1, False, XA_CARDINAL,
                                    &ret, &format, &nitems, &after, &data);
             if (e == Success && ret == XA_CARDINAL && format == 32 && nitems == 1
                 && after == 0 && data) {
                 ulong value = *(ulong*)(data);
                 d->topData()->opacity = uint(value >> 24);
             }
         } else
             d->topData()->opacity = 255;
     }
     if (data)
         XFree(data);
     return true;
 }
translateRegionEvent()
bool QETWidget::translateRegionEvent (const QWSRegionEvent * event)
Definition at line 3595 of file qapplication_qws.cpp.
Referenced by QApplication::qwsProcessEvent().
 {
     QWSWindowSurface *surface = static_cast<QWSWindowSurface*>(windowSurface());
     Q_ASSERT(surface);
     QRegion region;
     region.setRects(event->rectangles, event->simpleData.nrectangles);
     switch (event->simpleData.type) {
     case QWSRegionEvent::Allocation:
         region.translate(-mapToGlobal(QPoint()));
         surface->setClipRegion(region);
         break;
 #ifdef QT_QWS_CLIENTBLIT
     case QWSRegionEvent::DirectPaint:
         surface->setDirectRegion(region, event->simpleData.id);
         break;
 #endif
     default:
         break;
     }
     return true;
 }
translateScrollDoneEvent()
bool QETWidget::translateScrollDoneEvent (const XEvent * event)
Definition at line 5249 of file qapplication_x11.cpp.
Referenced by QApplication::x11ClientMessage().
 {
     long id = event->xclient.data.l[0];
     // Remove any scroll-in-progress record for the given id.
     for (int i = 0; i < X11->sip_list.size(); ++i) {
         const QX11Data::ScrollInProgress &sip = X11->sip_list.at(i);
         if (sip.id == id) {
             X11->sip_list.removeAt(i);
             return true;
         }
     }
     return false;
 }
translateTabletEvent()
bool QETWidget::translateTabletEvent (const MSG & msg, PACKET * localPacketBuf, int numPackets)
Definition at line 3593 of file qapplication_win.cpp.
Referenced by QtWndProc().
 {
     Q_UNUSED(msg);
     POINT ptNew;
     static DWORD btnNew, btnOld, btnChange;
     qreal prsNew;
     ORIENTATION ort;
     static bool button_pressed = false;
     int i,
         tiltX,
         tiltY;
     bool sendEvent = false;
     QEvent::Type t;
     int z = 0;
     qreal rotation = 0.0;
     qreal tangentialPressure;
     // The tablet can be used in 2 different modes, depending on it settings:
     // 1) Absolute (pen) mode:
     //    The coordinates are scaled to the virtual desktop (by default). The user
     //    can also choose to scale to the monitor or a region of the screen.
     //    When entering proximity, the tablet driver snaps the mouse pointer to the
     //    tablet position scaled to that area and keeps it in sync.
     // 2) Relative (mouse) mode:
     //    The pen follows the mouse. The constant 'absoluteRange' specifies the
     //    manhattanLength difference for detecting if a tablet input device is in this mode,
     //    in which case we snap the position to the mouse position.
     // It seems there is no way to find out the mode programmatically, the LOGCONTEXT orgX/Y/Ext
     // area is always the virtual desktop.
     enum { absoluteRange = 20 };
     // the most common event that we get...
     t = QEvent::TabletMove;
     for (i = 0; i < numPackets; i++) {
         // get the unique ID of the device...
         btnOld = btnNew;
         btnNew = localPacketBuf[i].pkButtons;
         btnChange = btnOld ^ btnNew;
         if (btnNew & btnChange) {
             button_pressed = true;
             t = QEvent::TabletPress;
         }
         ptNew.x = UINT(localPacketBuf[i].pkX);
         ptNew.y = UINT(localPacketBuf[i].pkY);
 #ifndef QT_NO_TABLETEVENT
         z = (currentTabletPointer.currentDevice == QTabletEvent::FourDMouse) ? UINT(localPacketBuf[i].pkZ) : 0;
 #else
         Q_UNUSED(z);
 #endif // QT_NO_TABLETEVENT
         prsNew = 0.0;
         QRect desktopArea = QApplication::desktop()->geometry();
         // This code is to delay the tablet data one cycle to sync with the mouse location.
         QPointF hiResTabletGlobalPosF = oldHiResTabletGlobalPosF;
         oldHiResTabletGlobalPosF =
             currentTabletPointer.scaleCoord(ptNew.x, ptNew.y, desktopArea.left(),
                                             desktopArea.width(), desktopArea.top(),
                                             desktopArea.height());
         if (btnNew) {
 #ifndef QT_NO_TABLETEVENT
             if (currentTabletPointer.currentPointerType == QTabletEvent::Pen || currentTabletPointer.currentPointerType == QTabletEvent::Eraser)
                 prsNew = localPacketBuf[i].pkNormalPressure
                             / qreal(currentTabletPointer.maxPressure
                                     - currentTabletPointer.minPressure);
             else
 #endif // QT_NO_TABLETEVENT
                 prsNew = 0;
         } else if (button_pressed) {
             // One button press, should only give one button release
             t = QEvent::TabletRelease;
             button_pressed = false;
         }
         QPoint globalPos = hiResTabletGlobalPosF.toPoint();
         // Get Mouse Position and compare to tablet info
         // Positions should be almost the same if we are in absolute
         //  mode. If they are not, use the mouse location.
 #ifndef Q_WS_WINCE
         POINT mouseLocationP;
         if (GetCursorPos(&mouseLocationP)) {
             const QPoint mouseLocation(mouseLocationP.x, mouseLocationP.y);
             if ((mouseLocation - globalPos).manhattanLength() > absoluteRange) {
                 globalPos = mouseLocation;
                 hiResTabletGlobalPosF = globalPos;
             }
         }
 #endif // !Q_WS_WINCE
         if (t == QEvent::TabletPress)
         {
             qt_button_down = QApplication::widgetAt(globalPos);
         }
         // make sure the tablet event get's sent to the proper widget...
         QWidget *w = 0;
         if (qt_button_down)
             w = qt_button_down; // Pass it to the thing that's grabbed it.
         else
             w = QApplication::widgetAt(globalPos);
         if (!w)
             w = this;
         if (t == QEvent::TabletRelease)
         {
             if (qt_win_ignoreNextMouseReleaseEvent) {
                 qt_win_ignoreNextMouseReleaseEvent = false;
                 if (qt_button_down && qt_button_down->internalWinId() == autoCaptureWnd) {
                     releaseAutoCapture();
                     qt_button_down = 0;
                 }
             }
         }
         QPoint localPos = w->mapFromGlobal(globalPos);
 #ifndef QT_NO_TABLETEVENT
         if (currentTabletPointer.currentDevice == QTabletEvent::Airbrush) {
             tangentialPressure = localPacketBuf[i].pkTangentPressure
                                 / qreal(currentTabletPointer.maxTanPressure
                                         - currentTabletPointer.minTanPressure);
         } else {
             tangentialPressure = 0.0;
         }
 #else
         tangentialPressure = 0.0;
 #endif // QT_NO_TABLETEVENT
         if (!qt_tablet_tilt_support) {
             tiltX = tiltY = 0;
             rotation = 0.0;
         } else {
             ort = localPacketBuf[i].pkOrientation;
             // convert from azimuth and altitude to x tilt and y tilt
             // what follows is the optimized version.  Here are the equations
             // I used to get to this point (in case things change :)
             // X = sin(azimuth) * cos(altitude)
             // Y = cos(azimuth) * cos(altitude)
             // Z = sin(altitude)
             // X Tilt = arctan(X / Z)
             // Y Tilt = arctan(Y / Z)
             double radAzim = (ort.orAzimuth / 10) * (Q_PI / 180);
             //double radAlt = abs(ort.orAltitude / 10) * (Q_PI / 180);
             double tanAlt = tan((abs(ort.orAltitude / 10)) * (Q_PI / 180));
             double degX = atan(sin(radAzim) / tanAlt);
             double degY = atan(cos(radAzim) / tanAlt);
             tiltX = int(degX * (180 / Q_PI));
             tiltY = int(-degY * (180 / Q_PI));
             rotation = ort.orTwist;
         }
 #ifndef QT_NO_TABLETEVENT
         QTabletEvent e(t, localPos, globalPos, hiResTabletGlobalPosF, currentTabletPointer.currentDevice,
                        currentTabletPointer.currentPointerType, prsNew, tiltX, tiltY,
                        tangentialPressure, rotation, z, QApplication::keyboardModifiers(), currentTabletPointer.llId);
         sendEvent = QApplication::sendSpontaneousEvent(w, &e);
 #endif // QT_NO_TABLETEVENT
     }
     return sendEvent;
 }
translateWheelEvent() [1/3]
bool QETWidget::translateWheelEvent (const QWSMouseEvent * me)
Definition at line 3288 of file qapplication_qws.cpp.
Referenced by QtWndProc(), and QApplication::qwsProcessEvent().
 {
 #ifdef QT_NO_WHEELEVENT
     Q_UNUSED(me);
     return false;
 #else
     const QWSMouseEvent::SimpleData &mouse = me->simpleData;
     // Figure out wheeling direction:
     //    Horizontal wheel w/o Alt
     // OR Vertical wheel   w/  Alt  ==> Horizontal wheeling
     //    ..all other permutations  ==> Vertical wheeling
     int axis = mouse.delta / 120; // WHEEL_DELTA?
     Qt::Orientation orient = ((axis == 2 || axis == -2) && ((mouse.state & Qt::AltModifier) == 0))
                              ||((axis == 1 || axis == -1) && mouse.state & Qt::AltModifier)
                              ? Qt::Horizontal : Qt::Vertical;
     QPoint mousePoint = QPoint(mouse.x_root, mouse.y_root);
     // send the event to the widget or its ancestors
     QWidget* popup = qApp->activePopupWidget();
     if (popup && window() != popup)
         popup->close();
     QWheelEvent we(mapFromGlobal(mousePoint), mousePoint, mouse.delta,
                    Qt::MouseButtons(mouse.state & Qt::MouseButtonMask),
                    Qt::KeyboardModifiers(mouse.state & Qt::KeyboardModifierMask), orient);
     if (QApplication::sendSpontaneousEvent(this, &we))
         return true;
     // send the event to the widget that has the focus or its ancestors, if different
     QWidget *w = this;
     if (w != qApp->focusWidget() && (w = qApp->focusWidget())) {
         QWidget* popup = qApp->activePopupWidget();
         if (popup && w != popup)
             popup->hide();
         if (QApplication::sendSpontaneousEvent(w, &we))
             return true;
     }
     return false;
 #endif
 }
translateWheelEvent() [2/3]
bool QETWidget::translateWheelEvent (const MSG & msg)
Definition at line 3402 of file qapplication_win.cpp.
 {
     int  state = 0;
     if (sm_blockUserInput) // block user interaction during session management
         return true;
     state = translateButtonState(GET_KEYSTATE_WPARAM(msg.wParam), 0, 0);
     int delta;
     if (msg.message == WM_MOUSEWHEEL || msg.message == WM_MOUSEHWHEEL)
         delta = (short) HIWORD (msg.wParam);
     else
         delta = (int) msg.wParam;
     Qt::Orientation orient = (msg.message == WM_MOUSEHWHEEL || state&Qt::AltModifier
 #if 0
     // disabled for now - Trenton's one-wheel mouse makes trouble...
     // "delta" for usual wheels is +-120. +-240 seems to indicate
     // the second wheel see more recent MSDN for WM_MOUSEWHEEL
     ( // <- parantheses added to make update happy, remove if the
       // #if 0 is removed
         || delta == 240 || delta == -240)?Qt::Horizontal:Vertical;
     if (delta == 240 || delta == -240)
         delta /= 2;
 #endif
        ) ? Qt::Horizontal : Qt::Vertical;
     // according to the MSDN documentation on WM_MOUSEHWHEEL:
     // a positive value indicates that the wheel was rotated to the right;
     // a negative value indicates that the wheel was rotated to the left.
     // Qt defines this value as the exact opposite, so we have to flip the value!
     if (msg.message == WM_MOUSEHWHEEL)
         delta = -delta;
     QPoint globalPos;
     globalPos.rx() = (short)LOWORD (msg.lParam);
     globalPos.ry() = (short)HIWORD (msg.lParam);
     // if there is a widget under the mouse and it is not shadowed
     // by modality, we send the event to it first
     int ret = 0;
     QWidget* w = QApplication::widgetAt(globalPos);
     if (!w || !qt_try_modal(w, (MSG*)&msg, ret)) {
         //synaptics touchpad shows its own widget at this position
         //so widgetAt() will fail with that HWND, try child of this widget
         w = this->childAt(this->mapFromGlobal(globalPos));
         if (!w)
             w = this;
     }
     // send the event to the widget or its ancestors
     {
         QWidget* popup = QApplication::activePopupWidget();
         if (popup && w->window() != popup)
             popup->close();
 #ifndef QT_NO_WHEELEVENT
         QWheelEvent e(w->mapFromGlobal(globalPos), globalPos, delta,
                       Qt::MouseButtons(state & Qt::MouseButtonMask),
                       Qt::KeyboardModifier(state & Qt::KeyboardModifierMask), orient);
         if (QApplication::sendSpontaneousEvent(w, &e))
 #else
         Q_UNUSED(orient);
 #endif //QT_NO_WHEELEVENT
             return true;
     }
     // send the event to the widget that has the focus or its ancestors, if different
     if (w != QApplication::focusWidget() && (w = QApplication::focusWidget())) {
         QWidget* popup = QApplication::activePopupWidget();
         if (popup && w->window() != popup)
             popup->close();
 #ifndef QT_NO_WHEELEVENT
         QWheelEvent e(w->mapFromGlobal(globalPos), globalPos, delta,
                       Qt::MouseButtons(state & Qt::MouseButtonMask),
                       Qt::KeyboardModifier(state & Qt::KeyboardModifierMask), orient);
         if (QApplication::sendSpontaneousEvent(w, &e))
 #endif //QT_NO_WHEELEVENT
             return true;
     }
     return false;
 }
translateWheelEvent() [3/3]
bool QETWidget::translateWheelEvent (int global_x, int global_y, int delta, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers, Qt::Orientation orient)
Definition at line 4537 of file qapplication_x11.cpp.
 {
     const QPoint globalPos = QPoint(global_x, global_y);
     QPoint pos = mapFromGlobal(globalPos);
     QWidget *widget = childAt(pos);
     if (!widget)
         widget = this;
     else if (!widget->internalWinId())
         pos = widget->mapFromGlobal(globalPos);
 #ifdef ALIEN_DEBUG
         qDebug() << "QETWidget::translateWheelEvent: receiver:" << widget << "pos:" << pos;
 #endif
     // send the event to the widget or its ancestors
     {
         QWidget* popup = qApp->activePopupWidget();
         if (popup && window() != popup)
             popup->close();
 #ifndef QT_NO_WHEELEVENT
         QWheelEvent e(pos, globalPos, delta, buttons, modifiers, orient);
         if (QApplication::sendSpontaneousEvent(widget, &e))
 #endif
             return true;
     }
     // send the event to the widget that has the focus or its ancestors, if different
     if (widget != qApp->focusWidget() && (widget = qApp->focusWidget())) {
         if (widget && !widget->internalWinId())
             pos = widget->mapFromGlobal(globalPos);
         QWidget* popup = qApp->activePopupWidget();
         if (popup && widget != popup)
             popup->hide();
 #ifndef QT_NO_WHEELEVENT
         QWheelEvent e(pos, globalPos, delta, buttons, modifiers, orient);
         if (QApplication::sendSpontaneousEvent(widget, &e))
 #endif
             return true;
     }
     return false;
 }
translateXinputEvent()
bool QETWidget::translateXinputEvent (const XEvent * ev, QTabletDeviceData * tablet)
Definition at line 4700 of file qapplication_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
 #if defined (Q_OS_IRIX)
     // Wacom has put defines in their wacom.h file so it would be quite wise
     // to use them, need to think of a decent way of not using
     // it when it doesn't exist...
     XDeviceState *s;
     XInputClass *iClass;
     XValuatorState *vs;
     int j;
 #endif
     Q_ASSERT(tablet != 0);
     QWidget *w = this;
     QPoint global,
         curr;
     QPointF hiRes;
     qreal pressure = 0;
     int xTilt = 0,
         yTilt = 0,
         z = 0;
     qreal tangentialPressure = 0;
     qreal rotation = 0;
     int deviceType = QTabletEvent::NoDevice;
     int pointerType = QTabletEvent::UnknownPointer;
     const XDeviceMotionEvent *motion = 0;
     XDeviceButtonEvent *button = 0;
     const XProximityNotifyEvent *proximity = 0;
     QEvent::Type t;
     Qt::KeyboardModifiers modifiers = 0;
 #if !defined (Q_OS_IRIX)
     XID device_id;
 #endif
     if (ev->type == tablet->xinput_motion) {
         motion = reinterpret_cast<const XDeviceMotionEvent*>(ev);
         t = QEvent::TabletMove;
         global = QPoint(motion->x_root, motion->y_root);
         curr = QPoint(motion->x, motion->y);
 #if !defined (Q_OS_IRIX)
         device_id = motion->deviceid;
 #endif
     } else if (ev->type == tablet->xinput_button_press || ev->type == tablet->xinput_button_release) {
         if (ev->type == tablet->xinput_button_press) {
             t = QEvent::TabletPress;
         } else {
             t = QEvent::TabletRelease;
         }
         button = (XDeviceButtonEvent*)ev;
         global = QPoint(button->x_root, button->y_root);
         curr = QPoint(button->x, button->y);
 #if !defined (Q_OS_IRIX)
         device_id = button->deviceid;
 #endif
     } else { // Proximity
         if (ev->type == tablet->xinput_proximity_in)
             t = QEvent::TabletEnterProximity;
         else
             t = QEvent::TabletLeaveProximity;
         proximity = (const XProximityNotifyEvent*)ev;
 #if !defined (Q_OS_IRIX)
         device_id = proximity->deviceid;
 #endif
     }
     qint64 uid = 0;
 #if defined (Q_OS_IRIX)
     QRect screenArea = qApp->desktop()->screenGeometry(this);
     s = XQueryDeviceState(X11->display, static_cast<XDevice *>(tablet->device));
     if (!s)
         return false;
     iClass = s->data;
     for (j = 0; j < s->num_classes; j++) {
         if (iClass->c_class == ValuatorClass) {
             vs = reinterpret_cast<XValuatorState *>(iClass);
             // figure out what device we have, based on bitmasking...
             if (vs->valuators[WAC_TRANSDUCER_I]
                  & WAC_TRANSDUCER_PROX_MSK) {
                 switch (vs->valuators[WAC_TRANSDUCER_I]
                          & WAC_TRANSDUCER_MSK) {
                 case WAC_PUCK_ID:
                     pointerType = QTabletEvent::Puck;
                     break;
                 case WAC_STYLUS_ID:
                     pointerType = QTabletEvent::Pen;
                     break;
                 case WAC_ERASER_ID:
                     pointerType = QTabletEvent::Eraser;
                     break;
                 }
                 // Get a Unique Id for the device, Wacom gives us this ability
                 uid = vs->valuators[WAC_TRANSDUCER_I] & WAC_TRANSDUCER_ID_MSK;
                 uid = (uid << 24) | vs->valuators[WAC_SERIAL_NUM_I];
                 switch (WAC_TRANSDUCER_I & 0x0F0600) {
                 case 0x080200:
                     deviceType = QTabletEvent::Stylus;
                     break;
                 case 0x090200:
                     deviceType = QTabletEvent::Airbrush;
                     break;
                 case 0x000400:
                     deviceType = QTabletEvent::FourDMouse;
                     break;
                 case 0x000600:
                     deviceType = QTabletEvent::Puck;
                     break;
                 case 0x080400:
                     deviceType = QTabletEvent::RotationStylus;
                     break;
                 }
             } else {
                 pointerType = QTabletEvent::UnknownPointer;
                 deviceType = QTabletEvent::NoDevice;
                 uid = 0;
             }
             if (!proximity) {
                 // apparently Wacom needs a cast for the +/- values to make sense
                 xTilt = short(vs->valuators[WAC_XTILT_I]);
                 yTilt = short(vs->valuators[WAC_YTILT_I]);
                 pressure = vs->valuators[WAC_PRESSURE_I];
                 if (deviceType == QTabletEvent::FourDMouse
                         || deviceType == QTabletEvent::RotationStylus) {
                     rotation = vs->valuators[WAC_ROTATION_I] / 64.0;
                     if (deviceType == QTabletEvent::FourDMouse)
                         z = vs->valuators[WAC_ZCOORD_I];
                 } else if (deviceType == QTabletEvent::Airbrush) {
                     tangentialPressure = vs->valuators[WAC_TAN_PRESSURE_I]
                                             / qreal(tablet->maxTanPressure - tablet->minTanPressure);
                 }
                 hiRes = tablet->scaleCoord(vs->valuators[WAC_XCOORD_I], vs->valuators[WAC_YCOORD_I],
                                            screenArea.x(), screenArea.width(),
                                            screenArea.y(), screenArea.height());
             }
             break;
         }
         iClass = reinterpret_cast<XInputClass*>(reinterpret_cast<char*>(iClass) + iClass->length);
     }
     XFreeDeviceState(s);
 #else
     // We've been passed in data for a tablet device that handles this type
     // of event, but it isn't necessarily the tablet device that originated
     // the event.  Use the device id to find the originating device if we
     // have it.
     QTabletDeviceDataList *tablet_list = qt_tablet_devices();
     for (int i = 0; i < tablet_list->size(); ++i) {
         QTabletDeviceData &tab = tablet_list->operator[](i);
         if (device_id == static_cast<XDevice *>(tab.device)->device_id) {
             // Replace the tablet passed in with this one.
             tablet = &tab;
             deviceType = tab.deviceType;
             if (tab.deviceType == QTabletEvent::XFreeEraser) {
                 deviceType = QTabletEvent::Stylus;
                 pointerType = QTabletEvent::Eraser;
             } else if (tab.deviceType == QTabletEvent::Stylus) {
                 pointerType = QTabletEvent::Pen;
             }
             break;
         }
     }
     fetchWacomToolId(deviceType, uid);
     QRect screenArea = qApp->desktop()->rect();
     if (motion) {
         xTilt = (short) motion->axis_data[3];
         yTilt = (short) motion->axis_data[4];
         rotation = ((short) motion->axis_data[5]) / 64.0;
         pressure = (short) motion->axis_data[2];
         modifiers = X11->translateModifiers(motion->state);
         hiRes = tablet->scaleCoord(motion->axis_data[0], motion->axis_data[1],
                                     screenArea.x(), screenArea.width(),
                                     screenArea.y(), screenArea.height());
     } else if (button) {
         xTilt = (short) button->axis_data[3];
         yTilt = (short) button->axis_data[4];
         rotation = ((short) button->axis_data[5]) / 64.0;
         pressure = (short) button->axis_data[2];
         modifiers = X11->translateModifiers(button->state);
         hiRes = tablet->scaleCoord(button->axis_data[0], button->axis_data[1],
                                     screenArea.x(), screenArea.width(),
                                     screenArea.y(), screenArea.height());
     } else if (proximity) {
         pressure = 0;
         modifiers = 0;
     }
     if (deviceType == QTabletEvent::Airbrush) {
         tangentialPressure = rotation;
         rotation = 0.;
     }
 #endif
     if (tablet->widgetToGetPress) {
         w = tablet->widgetToGetPress;
     } else {
         QWidget *child = w->childAt(curr);
         if (child)
             w = child;
     }
     curr = w->mapFromGlobal(global);
     if (t == QEvent::TabletPress) {
         tablet->widgetToGetPress = w;
     } else if (t == QEvent::TabletRelease && tablet->widgetToGetPress) {
         w = tablet->widgetToGetPress;
         curr = w->mapFromGlobal(global);
         tablet->widgetToGetPress = 0;
     }
     QTabletEvent e(t, curr, global, hiRes,
                    deviceType, pointerType,
                    qreal(pressure / qreal(tablet->maxPressure - tablet->minPressure)),
                    xTilt, yTilt, tangentialPressure, rotation, z, modifiers, uid);
     if (proximity) {
         QApplication::sendSpontaneousEvent(qApp, &e);
     } else {
         QApplication::sendSpontaneousEvent(w, &e);
         const bool accepted = e.isAccepted();
         if (!accepted && ev->type == tablet->xinput_motion) {
             // If the widget does not accept tablet events, we drop the next ones from the event queue
             // for this widget so it is not overloaded with the numerous tablet events.
             qt_tablet_motion_data tabletMotionData;
             tabletMotionData.tabletMotionType = tablet->xinput_motion;
             tabletMotionData.widget = w;
             tabletMotionData.etWidget = this;
             // if nothing is pressed, the events are filtered by position
             tabletMotionData.filterByWidget = (tablet->widgetToGetPress == 0);
             bool reinsertMouseEvent = false;
             XEvent mouseMotionEvent;
             while (true) {
                 // Find first mouse event since we expect them in pairs inside Qt
                 tabletMotionData.error =false;
                 if (XCheckIfEvent(X11->display, &mouseMotionEvent, &qt_mouseMotion_scanner, (XPointer) &tabletMotionData)) {
                     reinsertMouseEvent = true;
                 } else {
                     break;
                 }
                 // Now discard any duplicate tablet events.
                 tabletMotionData.error = false;
                 XEvent dummy;
                 while (XCheckIfEvent(X11->display, &dummy, &qt_tabletMotion_scanner, (XPointer) &tabletMotionData)) {
                     // just discard the event
                 }
             }
             if (reinsertMouseEvent) {
                 XPutBackEvent(X11->display, &mouseMotionEvent);
             }
         }
     }
     return true;
 }
updateRegion()
void QETWidget::updateRegion ()
Definition at line 3651 of file qapplication_qws.cpp.
 {
     Q_D(QWidget);
     QTLWExtra *topextra = d->maybeTopData();
     if (!topextra)
         return;
     QRegion myregion = d->localRequestedRegion();
     myregion.translate(geometry().topLeft());
 #ifndef QT_NO_QWS_MANAGER
     QWSManager *manager = topextra->qwsManager;
     if (manager)
         myregion += manager->region();
 #endif
     QRect br(myregion.boundingRect());
     topextra->frameStrut.setCoords(d->data.crect.x() - br.x(),
                                    d->data.crect.y() - br.y(),
                                    br.right() - d->data.crect.right(),
                                    br.bottom() - d->data.crect.bottom());
 }
winEvent()
bool QETWidget::winEvent (MSG * message, long * result) inline virtual
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
In your reimplementation of this function, if you want to stop the event being handled by Qt, return true and set result to the value that the window procedure should return. If you return false, this native event is passed back to Qt, which translates the event into a Qt event and sends it to the widget.
Warning
This function is not portable.
See also
QApplication::winEventFilter()
Reimplemented from QWidget.
Definition at line 476 of file qapplication_win.cpp.
Referenced by QtWndProc().
 { return QWidget::winEvent(m, r); }
xtra()
QWExtra* QETWidget::xtra () inline
Definition at line 468 of file qapplication_win.cpp.
Referenced by QtWndProc().
 { return d_func()->extraData(); }
The documentation for this class was generated from the following files:
/src/gui/kernel/qapplication_qws.cpp
/src/gui/kernel/qapplication_win.cpp
/src/gui/kernel/qapplication_x11.cpp
/src/gui/kernel/qkeymapper_win.cpp