Qt 4.8: QDeclarativeWorkerScript Class Reference
QDeclarativeWorkerScript Class Reference
#include <qdeclarativeworkerscript_p.h>
Public Slots
void sendMessage (const QScriptValue &)
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void message (const QScriptValue &messageObject)
void sourceChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDeclarativeWorkerScript (QObject *parent=0)
void setSource (const QUrl &)
QUrl source () const
virtual ~QDeclarativeWorkerScript ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
virtual void classBegin ()
Invoked after class creation, but before any properties have been set.
virtual void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
virtual bool event (QEvent *)
This handler is called when a message msg is received from a worker script in another thread through a call to sendMessage().
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
QDeclarativeWorkerScriptEngine * engine ()
Properties
bool m_componentComplete
QDeclarativeWorkerScriptEngine * m_engine
int m_scriptId
QUrl m_source
QUrl source
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 90 of file qdeclarativeworkerscript_p.h.
Constructors and Destructors
QDeclarativeWorkerScript()
QDeclarativeWorkerScript::QDeclarativeWorkerScript (QObject * parent = 0)
Definition at line 629 of file qdeclarativeworkerscript.cpp.
 : QObject(parent), m_engine(0), m_scriptId(-1), m_componentComplete(true)
 {
 }
~QDeclarativeWorkerScript()
QDeclarativeWorkerScript::~QDeclarativeWorkerScript () virtual
Definition at line 634 of file qdeclarativeworkerscript.cpp.
 {
     if (m_scriptId != -1) m_engine->removeWorkerScript(m_scriptId);
 }
Functions
classBegin()
void QDeclarativeWorkerScript::classBegin () protected virtual
Invoked after class creation, but before any properties have been set.
Implements QDeclarativeParserStatus.
Definition at line 696 of file qdeclarativeworkerscript.cpp.
 {
     m_componentComplete = false;
 }
componentComplete()
void QDeclarativeWorkerScript::componentComplete () protected virtual
Invoked after the root component that caused this instantiation has completed construction.
At this point all static values and binding values have been assigned to the class.
Implements QDeclarativeParserStatus.
Definition at line 722 of file qdeclarativeworkerscript.cpp.
 {
     m_componentComplete = true;
     engine(); // Get it started now.
 }
engine()
QDeclarativeWorkerScriptEngine * QDeclarativeWorkerScript::engine () private
Definition at line 701 of file qdeclarativeworkerscript.cpp.
Referenced by componentComplete(), event(), sendMessage(), and setSource().
 {
     if (m_engine) return m_engine;
     if (m_componentComplete) {
         QDeclarativeEngine *engine = qmlEngine(this);
         if (!engine) {
             qWarning("QDeclarativeWorkerScript: engine() called without qmlEngine() set");
             return 0;
         }
         m_engine = QDeclarativeEnginePrivate::get(engine)->getWorkerScriptEngine();
         m_scriptId = m_engine->registerWorkerScript(this);
         if (m_source.isValid())
             m_engine->executeUrl(m_scriptId, m_source);
         return m_engine;
     }
     return 0;
 }
event()
bool QDeclarativeWorkerScript::event (QEvent * event) protected virtual
This handler is called when a message msg is received from a worker script in another thread through a call to sendMessage().
WorkerScript::onMessage(jsobject msg)
Reimplemented from QObject.
Definition at line 738 of file qdeclarativeworkerscript.cpp.
 {
     if (event->type() == (QEvent::Type)WorkerDataEvent::WorkerData) {
         QDeclarativeEngine *engine = qmlEngine(this);
         if (engine) {
             QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
             WorkerDataEvent *workerEvent = static_cast<WorkerDataEvent *>(event);
             QScriptValue value =
                 QDeclarativeWorkerScriptEnginePrivate::variantToScriptValue(workerEvent->data(), scriptEngine);
             emit message(value);
         }
         return true;
     } else if (event->type() == (QEvent::Type)WorkerErrorEvent::WorkerError) {
         WorkerErrorEvent *workerEvent = static_cast<WorkerErrorEvent *>(event);
         QDeclarativeEnginePrivate::warning(qmlEngine(this), workerEvent->error());
         return true;
     } else {
         return QObject::event(event);
     }
 }
message
void QDeclarativeWorkerScript::message (const QScriptValue & messageObject) signal
Referenced by event().
sendMessage
void QDeclarativeWorkerScript::sendMessage (const QScriptValue & message) slot
Definition at line 686 of file qdeclarativeworkerscript.cpp.
 {
     if (!engine()) {
         qWarning("QDeclarativeWorkerScript: Attempt to send message before WorkerScript establishment");
         return;
     }
     m_engine->sendMessage(m_scriptId, QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(message));
 }
setSource()
void QDeclarativeWorkerScript::setSource (const QUrl & source)
Definition at line 653 of file qdeclarativeworkerscript.cpp.
 {
     if (m_source == source)
         return;
     m_source = source;
     if (engine())
         m_engine->executeUrl(m_scriptId, m_source);
     emit sourceChanged();
 }
source()
QUrl QDeclarativeWorkerScript::source () const
Referenced by setSource(), and ~QDeclarativeWorkerScript().
sourceChanged
void QDeclarativeWorkerScript::sourceChanged () signal
Referenced by setSource().
Properties
m_componentComplete
bool QDeclarativeWorkerScript::m_componentComplete private
Definition at line 120 of file qdeclarativeworkerscript_p.h.
Referenced by classBegin(), componentComplete(), and engine().
m_engine
QDeclarativeWorkerScriptEngine* QDeclarativeWorkerScript::m_engine private
Definition at line 117 of file qdeclarativeworkerscript_p.h.
Referenced by engine(), sendMessage(), setSource(), and ~QDeclarativeWorkerScript().
m_scriptId
int QDeclarativeWorkerScript::m_scriptId private
Definition at line 118 of file qdeclarativeworkerscript_p.h.
Referenced by engine(), sendMessage(), setSource(), and ~QDeclarativeWorkerScript().
m_source
QUrl QDeclarativeWorkerScript::m_source private
Definition at line 119 of file qdeclarativeworkerscript_p.h.
Referenced by engine(), setSource(), and ~QDeclarativeWorkerScript().
source
QUrl QDeclarativeWorkerScript::source private
Definition at line 93 of file qdeclarativeworkerscript_p.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeworkerscript_p.h
/src/declarative/qml/qdeclarativeworkerscript.cpp