Qt 4.8: QDeclarativeAnchors Class Reference
QDeclarativeAnchors Class Reference
#include <qdeclarativeanchors_p.h>
Public Types
enum Anchor {
LeftAnchor = 0x01, RightAnchor = 0x02, TopAnchor = 0x04, BottomAnchor = 0x08,
HCenterAnchor = 0x10, VCenterAnchor = 0x20, BaselineAnchor = 0x40, Horizontal_Mask = LeftAnchor | RightAnchor | HCenterAnchor,
Vertical_Mask = TopAnchor | BottomAnchor | VCenterAnchor | BaselineAnchor
}
Signals
void baselineChanged ()
void baselineOffsetChanged ()
void bottomChanged ()
void bottomMarginChanged ()
void centerInChanged ()
void fillChanged ()
void horizontalCenterChanged ()
void horizontalCenterOffsetChanged ()
void leftChanged ()
void leftMarginChanged ()
void marginsChanged ()
void rightChanged ()
void rightMarginChanged ()
void topChanged ()
void topMarginChanged ()
void verticalCenterChanged ()
void verticalCenterOffsetChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDeclarativeAnchorLine baseline () const
qreal baselineOffset () const
QDeclarativeAnchorLine bottom () const
qreal bottomMargin () const
QGraphicsObject * centerIn () const
void classBegin ()
void componentComplete ()
QGraphicsObject * fill () const
QDeclarativeAnchorLine horizontalCenter () const
qreal horizontalCenterOffset () const
QDeclarativeAnchorLine left () const
qreal leftMargin () const
qreal margins () const
bool mirrored ()
QDeclarativeAnchors (QObject *parent=0)
QDeclarativeAnchors (QGraphicsObject *item, QObject *parent=0)
void resetBaseline ()
void resetBottom ()
void resetCenterIn ()
void resetFill ()
void resetHorizontalCenter ()
void resetLeft ()
void resetRight ()
void resetTop ()
void resetVerticalCenter ()
QDeclarativeAnchorLine right () const
qreal rightMargin () const
void setBaseline (const QDeclarativeAnchorLine &edge)
void setBaselineOffset (qreal)
void setBottom (const QDeclarativeAnchorLine &edge)
void setBottomMargin (qreal)
void setCenterIn (QGraphicsObject *)
void setFill (QGraphicsObject *)
void setHorizontalCenter (const QDeclarativeAnchorLine &edge)
void setHorizontalCenterOffset (qreal)
void setLeft (const QDeclarativeAnchorLine &edge)
void setLeftMargin (qreal)
void setMargins (qreal)
void setRight (const QDeclarativeAnchorLine &edge)
void setRightMargin (qreal)
void setTop (const QDeclarativeAnchorLine &edge)
void setTopMargin (qreal)
void setVerticalCenter (const QDeclarativeAnchorLine &edge)
void setVerticalCenterOffset (qreal)
QDeclarativeAnchorLine top () const
qreal topMargin () const
Anchors usedAnchors () const
QDeclarativeAnchorLine verticalCenter () const
qreal verticalCenterOffset () const
virtual ~QDeclarativeAnchors ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QDeclarativeAnchorLine baseline
qreal baselineOffset
QDeclarativeAnchorLine bottom
qreal bottomMargin
QGraphicsObject * centerIn
QGraphicsObject * fill
QDeclarativeAnchorLine horizontalCenter
qreal horizontalCenterOffset
QDeclarativeAnchorLine left
qreal leftMargin
qreal margins
QDeclarativeAnchorLine right
qreal rightMargin
QDeclarativeAnchorLine top
qreal topMargin
QDeclarativeAnchorLine verticalCenter
qreal verticalCenterOffset
Friends
class QDeclarativeGraphicsWidget
class QDeclarativeItem
class QDeclarativeItemPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 61 of file qdeclarativeanchors_p.h.
Enumerations
Anchor
enum QDeclarativeAnchors::Anchor
Enumerator
LeftAnchor
RightAnchor
TopAnchor
BottomAnchor
HCenterAnchor
VCenterAnchor
BaselineAnchor
Horizontal_Mask
Vertical_Mask
Definition at line 88 of file qdeclarativeanchors_p.h.
                 {
         LeftAnchor = 0x01,
         RightAnchor = 0x02,
         TopAnchor = 0x04,
         BottomAnchor = 0x08,
         HCenterAnchor = 0x10,
         VCenterAnchor = 0x20,
         BaselineAnchor = 0x40,
         Horizontal_Mask = LeftAnchor | RightAnchor | HCenterAnchor,
         Vertical_Mask = TopAnchor | BottomAnchor | VCenterAnchor | BaselineAnchor
     };
Constructors and Destructors
QDeclarativeAnchors() [1/2]
QDeclarativeAnchors::QDeclarativeAnchors (QObject * parent = 0)
Definition at line 151 of file qdeclarativeanchors.cpp.
   : QObject(*new QDeclarativeAnchorsPrivate(0), parent)
 {
     qFatal("QDeclarativeAnchors::QDeclarativeAnchors(QObject*) called");
 }
QDeclarativeAnchors() [2/2]
QDeclarativeAnchors::QDeclarativeAnchors (QGraphicsObject * item, QObject * parent = 0)
Definition at line 157 of file qdeclarativeanchors.cpp.
   : QObject(*new QDeclarativeAnchorsPrivate(item), parent)
 {
 }
~QDeclarativeAnchors()
QDeclarativeAnchors::~QDeclarativeAnchors () virtual
Definition at line 162 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorsPrivate::clearItem().
 {
     Q_D(QDeclarativeAnchors);
     d->remDepend(d->fill);
     d->remDepend(d->centerIn);
     d->remDepend(d->left.item);
     d->remDepend(d->right.item);
     d->remDepend(d->top.item);
     d->remDepend(d->bottom.item);
     d->remDepend(d->vCenter.item);
     d->remDepend(d->hCenter.item);
     d->remDepend(d->baseline.item);
 }
Functions
baseline()
QDeclarativeAnchorLine QDeclarativeAnchors::baseline () const
Referenced by QDeclarativeAnchorsPrivate::clearItem(), resetVerticalCenter(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
baselineChanged
void QDeclarativeAnchors::baselineChanged () signal
Referenced by resetBaseline(), and setBaseline().
baselineOffset()
qreal QDeclarativeAnchors::baselineOffset () const
Referenced by setVerticalCenterOffset(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
baselineOffsetChanged
void QDeclarativeAnchors::baselineOffsetChanged () signal
Referenced by setBaselineOffset().
bottom()
QDeclarativeAnchorLine QDeclarativeAnchors::bottom () const
Referenced by QDeclarativeAnchorsPrivate::clearItem(), resetTop(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
bottomChanged
void QDeclarativeAnchors::bottomChanged () signal
Referenced by resetBottom(), and setBottom().
bottomMargin()
qreal QDeclarativeAnchors::bottomMargin () const
Referenced by QDeclarativeAnchorsPrivate::fillChanged(), setTopMargin(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
bottomMarginChanged
void QDeclarativeAnchors::bottomMarginChanged () signal
Referenced by setBottomMargin().
centerIn()
QGraphicsObject* QDeclarativeAnchors::centerIn () const
Referenced by QDeclarativeAnchorsPrivate::centerInChanged(), QDeclarativeAnchorsPrivate::clearItem(), resetFill(), QDeclarativeAnchorsPrivate::updateHorizontalAnchors(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
centerInChanged
void QDeclarativeAnchors::centerInChanged () signal
Referenced by QDeclarativeAnchorsPrivate::_q_widgetGeometryChanged(), QDeclarativeAnchorsPrivate::itemGeometryChanged(), setCenterIn(), QDeclarativeAnchorsPrivate::updateMe(), and QDeclarativeAnchorsPrivate::updateOnComplete().
classBegin()
void QDeclarativeAnchors::classBegin ()
Definition at line 308 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     d->componentComplete = false;
 }
componentComplete()
void QDeclarativeAnchors::componentComplete ()
Definition at line 314 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorsPrivate::isItemComplete().
 {
     Q_D(QDeclarativeAnchors);
     d->componentComplete = true;
 }
fill()
QGraphicsObject* QDeclarativeAnchors::fill () const
Referenced by QDeclarativeAnchorsPrivate::centerInChanged(), QDeclarativeAnchorsPrivate::clearItem(), QDeclarativeAnchorsPrivate::fillChanged(), QDeclarativeAnchorsPrivate::itemGeometryChanged(), QDeclarativeAnchorsPrivate::updateHorizontalAnchors(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
fillChanged
void QDeclarativeAnchors::fillChanged () signal
Referenced by QDeclarativeAnchorsPrivate::_q_widgetGeometryChanged(), QDeclarativeAnchorsPrivate::itemGeometryChanged(), setFill(), QDeclarativeAnchorsPrivate::updateMe(), and QDeclarativeAnchorsPrivate::updateOnComplete().
horizontalCenter()
QDeclarativeAnchorLine QDeclarativeAnchors::horizontalCenter () const
Referenced by resetRight().
horizontalCenterChanged
void QDeclarativeAnchors::horizontalCenterChanged () signal
Referenced by resetHorizontalCenter(), and setHorizontalCenter().
horizontalCenterOffset()
qreal QDeclarativeAnchors::horizontalCenterOffset () const
Referenced by setMargins().
horizontalCenterOffsetChanged
void QDeclarativeAnchors::horizontalCenterOffsetChanged () signal
Referenced by setHorizontalCenterOffset().
left()
QDeclarativeAnchorLine QDeclarativeAnchors::left () const
Referenced by QDeclarativeAnchorsPrivate::clearItem(), resetBaseline(), and QDeclarativeAnchorsPrivate::updateHorizontalAnchors().
leftChanged
void QDeclarativeAnchors::leftChanged () signal
Referenced by resetLeft(), and setLeft().
leftMargin()
qreal QDeclarativeAnchors::leftMargin () const
Referenced by QDeclarativeAnchorsPrivate::fillChanged(), resetHorizontalCenter(), and QDeclarativeAnchorsPrivate::updateHorizontalAnchors().
leftMarginChanged
void QDeclarativeAnchors::leftMarginChanged () signal
Referenced by setLeftMargin().
margins()
qreal QDeclarativeAnchors::margins () const
Referenced by setRightMargin().
marginsChanged
void QDeclarativeAnchors::marginsChanged () signal
Referenced by setMargins().
mirrored()
bool QDeclarativeAnchors::mirrored ()
Definition at line 320 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     QGraphicsItemPrivate * itemPrivate = QGraphicsItemPrivate::get(d->item);
     return itemPrivate->isDeclarativeItem ? static_cast<QDeclarativeItemPrivate *>(itemPrivate)->effectiveLayoutMirror : false;
 }
resetBaseline()
void QDeclarativeAnchors::resetBaseline ()
Definition at line 815 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorChanges::clearBindings(), QDeclarativeAnchorChanges::execute(), and QDeclarativeAnchorChanges::reverse().
 {
     Q_D(QDeclarativeAnchors);
     d->usedAnchors &= ~BaselineAnchor;
     d->remDepend(d->baseline.item);
     d->baseline = QDeclarativeAnchorLine();
     emit baselineChanged();
     d->updateVerticalAnchors();
 }
resetBottom()
void QDeclarativeAnchors::resetBottom ()
Definition at line 743 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorChanges::clearBindings(), QDeclarativeAnchorChanges::execute(), and QDeclarativeAnchorChanges::reverse().
 {
     Q_D(QDeclarativeAnchors);
     d->usedAnchors &= ~BottomAnchor;
     d->remDepend(d->bottom.item);
     d->bottom = QDeclarativeAnchorLine();
     emit bottomChanged();
     d->updateVerticalAnchors();
 }
resetCenterIn()
void QDeclarativeAnchors::resetCenterIn ()
Definition at line 480 of file qdeclarativeanchors.cpp.
 {
     setCenterIn(0);
 }
resetFill()
void QDeclarativeAnchors::resetFill ()
Definition at line 445 of file qdeclarativeanchors.cpp.
 {
     setFill(0);
 }
resetHorizontalCenter()
void QDeclarativeAnchors::resetHorizontalCenter ()
Definition at line 923 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorChanges::clearBindings(), QDeclarativeAnchorChanges::execute(), and QDeclarativeAnchorChanges::reverse().
 {
     Q_D(QDeclarativeAnchors);
     d->usedAnchors &= ~HCenterAnchor;
     d->remDepend(d->hCenter.item);
     d->hCenter = QDeclarativeAnchorLine();
     emit horizontalCenterChanged();
     d->updateHorizontalAnchors();
 }
resetLeft()
void QDeclarativeAnchors::resetLeft ()
Definition at line 851 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorChanges::clearBindings(), QDeclarativeAnchorChanges::execute(), and QDeclarativeAnchorChanges::reverse().
 {
     Q_D(QDeclarativeAnchors);
     d->usedAnchors &= ~LeftAnchor;
     d->remDepend(d->left.item);
     d->left = QDeclarativeAnchorLine();
     emit leftChanged();
     d->updateHorizontalAnchors();
 }
resetRight()
void QDeclarativeAnchors::resetRight ()
Definition at line 887 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorChanges::clearBindings(), QDeclarativeAnchorChanges::execute(), and QDeclarativeAnchorChanges::reverse().
 {
     Q_D(QDeclarativeAnchors);
     d->usedAnchors &= ~RightAnchor;
     d->remDepend(d->right.item);
     d->right = QDeclarativeAnchorLine();
     emit rightChanged();
     d->updateHorizontalAnchors();
 }
resetTop()
void QDeclarativeAnchors::resetTop ()
Definition at line 707 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorChanges::clearBindings(), QDeclarativeAnchorChanges::execute(), and QDeclarativeAnchorChanges::reverse().
 {
     Q_D(QDeclarativeAnchors);
     d->usedAnchors &= ~TopAnchor;
     d->remDepend(d->top.item);
     d->top = QDeclarativeAnchorLine();
     emit topChanged();
     d->updateVerticalAnchors();
 }
resetVerticalCenter()
void QDeclarativeAnchors::resetVerticalCenter ()
Definition at line 779 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorChanges::clearBindings(), QDeclarativeAnchorChanges::execute(), and QDeclarativeAnchorChanges::reverse().
 {
     Q_D(QDeclarativeAnchors);
     d->usedAnchors &= ~VCenterAnchor;
     d->remDepend(d->vCenter.item);
     d->vCenter = QDeclarativeAnchorLine();
     emit verticalCenterChanged();
     d->updateVerticalAnchors();
 }
right()
QDeclarativeAnchorLine QDeclarativeAnchors::right () const
Referenced by QDeclarativeAnchorsPrivate::clearItem(), resetLeft(), and QDeclarativeAnchorsPrivate::updateHorizontalAnchors().
rightChanged
void QDeclarativeAnchors::rightChanged () signal
Referenced by resetRight(), and setRight().
rightMargin()
qreal QDeclarativeAnchors::rightMargin () const
Referenced by QDeclarativeAnchorsPrivate::fillChanged(), setLeftMargin(), and QDeclarativeAnchorsPrivate::updateHorizontalAnchors().
rightMarginChanged
void QDeclarativeAnchors::rightMarginChanged () signal
Referenced by setRightMargin().
setBaseline()
void QDeclarativeAnchors::setBaseline (const QDeclarativeAnchorLine & edge)
Definition at line 795 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     if (!d->checkVAnchorValid(edge) || d->baseline == edge)
         return;
     d->usedAnchors |= BaselineAnchor;
     if (!d->checkVValid()) {
         d->usedAnchors &= ~BaselineAnchor;
         return;
     }
     d->remDepend(d->baseline.item);
     d->baseline = edge;
     d->addDepend(d->baseline.item);
     emit baselineChanged();
     d->updateVerticalAnchors();
 }
setBaselineOffset()
void QDeclarativeAnchors::setBaselineOffset (qreal offset)
Definition at line 1078 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     if (d->baselineOffset == offset)
         return;
     d->baselineOffset = offset;
     d->updateVerticalAnchors();
     emit baselineOffsetChanged();
 }
setBottom()
void QDeclarativeAnchors::setBottom (const QDeclarativeAnchorLine & edge)
Definition at line 723 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     if (!d->checkVAnchorValid(edge) || d->bottom == edge)
         return;
     d->usedAnchors |= BottomAnchor;
     if (!d->checkVValid()) {
         d->usedAnchors &= ~BottomAnchor;
         return;
     }
     d->remDepend(d->bottom.item);
     d->bottom = edge;
     d->addDepend(d->bottom.item);
     emit bottomChanged();
     d->updateVerticalAnchors();
 }
setBottomMargin()
void QDeclarativeAnchors::setBottomMargin (qreal offset)
Definition at line 1040 of file qdeclarativeanchors.cpp.
Referenced by setMargins().
 {
     Q_D(QDeclarativeAnchors);
     if (d->bottomMargin == offset)
         return;
     d->bottomMargin = offset;
     if(d->fill)
         d->fillChanged();
     else
         d->updateVerticalAnchors();
     emit bottomMarginChanged();
 }
setCenterIn()
void QDeclarativeAnchors::setCenterIn (QGraphicsObject * c)
Definition at line 456 of file qdeclarativeanchors.cpp.
Referenced by resetCenterIn().
 {
     Q_D(QDeclarativeAnchors);
     if (d->centerIn == c)
         return;
     if (!c) {
         d->remDepend(d->centerIn);
         d->centerIn = c;
         emit centerInChanged();
         return;
     }
     if (c != d->item->parentItem() && c->parentItem() != d->item->parentItem()){
         qmlInfo(d->item) << tr("Cannot anchor to an item that isn't a parent or sibling.");
         return;
     }
     d->remDepend(d->centerIn);
     d->centerIn = c;
     d->addDepend(d->centerIn);
     emit centerInChanged();
     d->centerInChanged();
 }
setFill()
void QDeclarativeAnchors::setFill (QGraphicsObject * f)
Definition at line 422 of file qdeclarativeanchors.cpp.
Referenced by resetFill().
 {
     Q_D(QDeclarativeAnchors);
     if (d->fill == f)
         return;
     if (!f) {
         d->remDepend(d->fill);
         d->fill = f;
         emit fillChanged();
         return;
     }
     if (f != d->item->parentItem() && f->parentItem() != d->item->parentItem()){
         qmlInfo(d->item) << tr("Cannot anchor to an item that isn't a parent or sibling.");
         return;
     }
     d->remDepend(d->fill);
     d->fill = f;
     d->addDepend(d->fill);
     emit fillChanged();
     d->fillChanged();
 }
setHorizontalCenter()
void QDeclarativeAnchors::setHorizontalCenter (const QDeclarativeAnchorLine & edge)
Definition at line 903 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     if (!d->checkHAnchorValid(edge) || d->hCenter == edge)
         return;
     d->usedAnchors |= HCenterAnchor;
     if (!d->checkHValid()) {
         d->usedAnchors &= ~HCenterAnchor;
         return;
     }
     d->remDepend(d->hCenter.item);
     d->hCenter = edge;
     d->addDepend(d->hCenter.item);
     emit horizontalCenterChanged();
     d->updateHorizontalAnchors();
 }
setHorizontalCenterOffset()
void QDeclarativeAnchors::setHorizontalCenterOffset (qreal offset)
Definition at line 1002 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     if (d->hCenterOffset == offset)
         return;
     d->hCenterOffset = offset;
     if(d->centerIn)
         d->centerInChanged();
     else
         d->updateHorizontalAnchors();
     emit horizontalCenterOffsetChanged();
 }
setLeft()
void QDeclarativeAnchors::setLeft (const QDeclarativeAnchorLine & edge)
Definition at line 831 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     if (!d->checkHAnchorValid(edge) || d->left == edge)
         return;
     d->usedAnchors |= LeftAnchor;
     if (!d->checkHValid()) {
         d->usedAnchors &= ~LeftAnchor;
         return;
     }
     d->remDepend(d->left.item);
     d->left = edge;
     d->addDepend(d->left.item);
     emit leftChanged();
     d->updateHorizontalAnchors();
 }
setLeftMargin()
void QDeclarativeAnchors::setLeftMargin (qreal offset)
Definition at line 939 of file qdeclarativeanchors.cpp.
Referenced by setMargins().
 {
     Q_D(QDeclarativeAnchors);
     if (d->leftMargin == offset)
         return;
     d->leftMargin = offset;
     if(d->fill)
         d->fillChanged();
     else
         d->updateHorizontalAnchors();
     emit leftMarginChanged();
 }
setMargins()
void QDeclarativeAnchors::setMargins (qreal offset)
Definition at line 977 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     if (d->margins == offset)
         return;
     //###Is it significantly faster to set them directly so we can call fillChanged only once?
     if(!d->rightMargin || d->rightMargin == d->margins)
         setRightMargin(offset);
     if(!d->leftMargin || d->leftMargin == d->margins)
         setLeftMargin(offset);
     if(!d->topMargin || d->topMargin == d->margins)
         setTopMargin(offset);
     if(!d->bottomMargin || d->bottomMargin == d->margins)
         setBottomMargin(offset);
     d->margins = offset;
     emit marginsChanged();
 }
setRight()
void QDeclarativeAnchors::setRight (const QDeclarativeAnchorLine & edge)
Definition at line 867 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     if (!d->checkHAnchorValid(edge) || d->right == edge)
         return;
     d->usedAnchors |= RightAnchor;
     if (!d->checkHValid()) {
         d->usedAnchors &= ~RightAnchor;
         return;
     }
     d->remDepend(d->right.item);
     d->right = edge;
     d->addDepend(d->right.item);
     emit rightChanged();
     d->updateHorizontalAnchors();
 }
setRightMargin()
void QDeclarativeAnchors::setRightMargin (qreal offset)
Definition at line 958 of file qdeclarativeanchors.cpp.
Referenced by setMargins().
 {
     Q_D(QDeclarativeAnchors);
     if (d->rightMargin == offset)
         return;
     d->rightMargin = offset;
     if(d->fill)
         d->fillChanged();
     else
         d->updateHorizontalAnchors();
     emit rightMarginChanged();
 }
setTop()
void QDeclarativeAnchors::setTop (const QDeclarativeAnchorLine & edge)
Definition at line 687 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     if (!d->checkVAnchorValid(edge) || d->top == edge)
         return;
     d->usedAnchors |= TopAnchor;
     if (!d->checkVValid()) {
         d->usedAnchors &= ~TopAnchor;
         return;
     }
     d->remDepend(d->top.item);
     d->top = edge;
     d->addDepend(d->top.item);
     emit topChanged();
     d->updateVerticalAnchors();
 }
setTopMargin()
void QDeclarativeAnchors::setTopMargin (qreal offset)
Definition at line 1021 of file qdeclarativeanchors.cpp.
Referenced by setMargins().
 {
     Q_D(QDeclarativeAnchors);
     if (d->topMargin == offset)
         return;
     d->topMargin = offset;
     if(d->fill)
         d->fillChanged();
     else
         d->updateVerticalAnchors();
     emit topMarginChanged();
 }
setVerticalCenter()
void QDeclarativeAnchors::setVerticalCenter (const QDeclarativeAnchorLine & edge)
Definition at line 759 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     if (!d->checkVAnchorValid(edge) || d->vCenter == edge)
         return;
     d->usedAnchors |= VCenterAnchor;
     if (!d->checkVValid()) {
         d->usedAnchors &= ~VCenterAnchor;
         return;
     }
     d->remDepend(d->vCenter.item);
     d->vCenter = edge;
     d->addDepend(d->vCenter.item);
     emit verticalCenterChanged();
     d->updateVerticalAnchors();
 }
setVerticalCenterOffset()
void QDeclarativeAnchors::setVerticalCenterOffset (qreal offset)
Definition at line 1059 of file qdeclarativeanchors.cpp.
 {
     Q_D(QDeclarativeAnchors);
     if (d->vCenterOffset == offset)
         return;
     d->vCenterOffset = offset;
     if(d->centerIn)
         d->centerInChanged();
     else
         d->updateVerticalAnchors();
     emit verticalCenterOffsetChanged();
 }
top()
QDeclarativeAnchorLine QDeclarativeAnchors::top () const
Referenced by QDeclarativeAnchorsPrivate::clearItem(), QDeclarativeAnchorsPrivate::updateHorizontalAnchors(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
topChanged
void QDeclarativeAnchors::topChanged () signal
Referenced by resetTop(), and setTop().
topMargin()
qreal QDeclarativeAnchors::topMargin () const
Referenced by QDeclarativeAnchorsPrivate::fillChanged(), setHorizontalCenterOffset(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
topMarginChanged
void QDeclarativeAnchors::topMarginChanged () signal
Referenced by setTopMargin().
usedAnchors()
QDeclarativeAnchors::Anchors QDeclarativeAnchors::usedAnchors () const
Definition at line 1088 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorsPrivate::checkHValid(), QDeclarativeAnchorsPrivate::checkVValid(), QDeclarativeAnchorsPrivate::clearItem(), QDeclarativeColumn::reportConflictingAnchors(), QDeclarativeRow::reportConflictingAnchors(), QDeclarativeGrid::reportConflictingAnchors(), QDeclarativeFlow::reportConflictingAnchors(), QDeclarativeAnchorChanges::reverse(), QDeclarativeAnchorsPrivate::updateHorizontalAnchors(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
 {
     Q_D(const QDeclarativeAnchors);
     return d->usedAnchors;
 }
verticalCenter()
QDeclarativeAnchorLine QDeclarativeAnchors::verticalCenter () const
Referenced by resetBottom().
verticalCenterChanged
void QDeclarativeAnchors::verticalCenterChanged () signal
Referenced by resetVerticalCenter(), and setVerticalCenter().
verticalCenterOffset()
qreal QDeclarativeAnchors::verticalCenterOffset () const
Referenced by setBottomMargin().
verticalCenterOffsetChanged
void QDeclarativeAnchors::verticalCenterOffsetChanged () signal
Referenced by setVerticalCenterOffset().
Friends and Related Functions
QDeclarativeGraphicsWidget
friend class QDeclarativeGraphicsWidget friend
Definition at line 190 of file qdeclarativeanchors_p.h.
QDeclarativeItem
friend class QDeclarativeItem friend
Definition at line 188 of file qdeclarativeanchors_p.h.
QDeclarativeItemPrivate
friend class QDeclarativeItemPrivate friend
Definition at line 189 of file qdeclarativeanchors_p.h.
Properties
baseline
QDeclarativeAnchorLine QDeclarativeAnchors::baseline private
Definition at line 71 of file qdeclarativeanchors_p.h.
Referenced by QDeclarativeAnchorChanges::saveCurrentValues().
baselineOffset
qreal QDeclarativeAnchors::baselineOffset private
Definition at line 79 of file qdeclarativeanchors_p.h.
bottom
QDeclarativeAnchorLine QDeclarativeAnchors::bottom private
Definition at line 69 of file qdeclarativeanchors_p.h.
Referenced by QDeclarativeAnchorChanges::saveCurrentValues().
bottomMargin
qreal QDeclarativeAnchors::bottomMargin private
Definition at line 77 of file qdeclarativeanchors_p.h.
centerIn
QGraphicsObject * QDeclarativeAnchors::centerIn private
Definition at line 81 of file qdeclarativeanchors_p.h.
Referenced by QDeclarativeColumn::reportConflictingAnchors(), QDeclarativeRow::reportConflictingAnchors(), QDeclarativeGrid::reportConflictingAnchors(), and QDeclarativeFlow::reportConflictingAnchors().
fill
QGraphicsObject * QDeclarativeAnchors::fill private
Definition at line 80 of file qdeclarativeanchors_p.h.
Referenced by QDeclarativeColumn::reportConflictingAnchors(), QDeclarativeRow::reportConflictingAnchors(), QDeclarativeGrid::reportConflictingAnchors(), and QDeclarativeFlow::reportConflictingAnchors().
horizontalCenter
QDeclarativeAnchorLine QDeclarativeAnchors::horizontalCenter private
Definition at line 67 of file qdeclarativeanchors_p.h.
Referenced by QDeclarativeAnchorChanges::saveCurrentValues().
horizontalCenterOffset
qreal QDeclarativeAnchors::horizontalCenterOffset private
Definition at line 75 of file qdeclarativeanchors_p.h.
left
QDeclarativeAnchorLine QDeclarativeAnchors::left private
Definition at line 65 of file qdeclarativeanchors_p.h.
Referenced by QDeclarativeAnchorChanges::saveCurrentValues().
leftMargin
qreal QDeclarativeAnchors::leftMargin private
Definition at line 73 of file qdeclarativeanchors_p.h.
margins
qreal QDeclarativeAnchors::margins private
Definition at line 72 of file qdeclarativeanchors_p.h.
right
QDeclarativeAnchorLine QDeclarativeAnchors::right private
Definition at line 66 of file qdeclarativeanchors_p.h.
Referenced by QDeclarativeAnchorChanges::saveCurrentValues().
rightMargin
qreal QDeclarativeAnchors::rightMargin private
Definition at line 74 of file qdeclarativeanchors_p.h.
top
QDeclarativeAnchorLine QDeclarativeAnchors::top private
Definition at line 68 of file qdeclarativeanchors_p.h.
Referenced by QDeclarativeAnchorChanges::saveCurrentValues().
topMargin
qreal QDeclarativeAnchors::topMargin private
Definition at line 76 of file qdeclarativeanchors_p.h.
verticalCenter
QDeclarativeAnchorLine QDeclarativeAnchors::verticalCenter private
Definition at line 70 of file qdeclarativeanchors_p.h.
Referenced by QDeclarativeAnchorChanges::saveCurrentValues().
verticalCenterOffset
qreal QDeclarativeAnchors::verticalCenterOffset private
Definition at line 78 of file qdeclarativeanchors_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativeanchors_p.h
/src/declarative/graphicsitems/qdeclarativeanchors.cpp