Qt 4.8: QDeclarativePathView Class Reference
QDeclarativePathView Class Reference
#include <qdeclarativepathview_p.h>
Public Types
enum HighlightRangeMode { NoHighlightRange, ApplyRange, StrictlyEnforceRange }
Public Types inherited from QDeclarativeItem
enum TransformOrigin {
TopLeft, Top, TopRight, Left,
Center, Right, BottomLeft, Bottom,
BottomRight
}
Controls the point about which simple transforms like scale apply.
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Public Slots
void decrementCurrentIndex ()
void incrementCurrentIndex ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void countChanged ()
void currentIndexChanged ()
void delegateChanged ()
void dragMarginChanged ()
void flickDecelerationChanged ()
void flickEnded ()
void flickingChanged ()
void flickStarted ()
void highlightChanged ()
void highlightItemChanged ()
void highlightMoveDurationChanged ()
void highlightRangeModeChanged ()
void interactiveChanged ()
void modelChanged ()
void movementEnded ()
void movementStarted ()
void movingChanged ()
void offsetChanged ()
void pathChanged ()
void pathItemCountChanged ()
void preferredHighlightBeginChanged ()
void preferredHighlightEndChanged ()
void snapPositionChanged ()
Signals inherited from QDeclarativeItem
void activeFocusChanged (bool)
void baselineOffsetChanged (qreal)
void childrenRectChanged (const QRectF &)
void clipChanged (bool)
void focusChanged (bool)
void implicitHeightChanged ()
void implicitWidthChanged ()
void parentChanged (QDeclarativeItem *)
void smoothChanged (bool)
void stateChanged (const QString &)
void transformOriginChanged (TransformOrigin)
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int count () const
int currentIndex () const
QDeclarativeComponent * delegate () const
qreal dragMargin () const
qreal flickDeceleration () const
QDeclarativeComponent * highlight () const
QDeclarativeItem * highlightItem ()
int highlightMoveDuration () const
HighlightRangeMode highlightRangeMode () const
bool isFlicking () const
bool isInteractive () const
bool isMoving () const
QVariant model () const
qreal offset () const
QDeclarativePath * path () const
int pathItemCount () const
qreal preferredHighlightBegin () const
qreal preferredHighlightEnd () const
QDeclarativePathView (QDeclarativeItem *parent=0)
void setCurrentIndex (int idx)
void setDelegate (QDeclarativeComponent *)
void setDragMargin (qreal margin)
void setFlickDeceleration (qreal dec)
void setHighlight (QDeclarativeComponent *highlight)
void setHighlightMoveDuration (int)
void setHighlightRangeMode (HighlightRangeMode mode)
void setInteractive (bool)
void setModel (const QVariant &)
void setOffset (qreal offset)
void setPath (QDeclarativePath *)
void setPathItemCount (int)
void setPreferredHighlightBegin (qreal)
void setPreferredHighlightEnd (qreal)
virtual ~QDeclarativePathView ()
Public Functions inherited from QDeclarativeItem
qreal baselineOffset () const
QRectF boundingRect () const
Q_INVOKABLE QDeclarativeItem * childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
QRectF childrenRect ()
bool clip () const
Q_INVOKABLE void forceActiveFocus ()
Forces active focus on the item.
bool hasActiveFocus () const
bool hasFocus () const
qreal height () const
qreal implicitHeight () const
qreal implicitWidth () const
bool keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
Q_INVOKABLE QScriptValue mapFromItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
Q_INVOKABLE QScriptValue mapToItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
virtual void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
QDeclarativeItem * parentItem () const
Returns the QDeclarativeItem parent of this item.
QDeclarativeItem (QDeclarativeItem *parent=0)
Constructs a QDeclarativeItem with the given parent.
void resetHeight ()
void resetWidth ()
void setBaselineOffset (qreal)
void setClip (bool)
void setFocus (bool)
void setHeight (qreal)
void setKeepMouseGrab (bool)
The flag indicating whether the mouse should remain with this item is set to keep.
void setParentItem (QDeclarativeItem *parent)
void setSize (const QSizeF &size)
void setSmooth (bool)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
void setTransformOrigin (TransformOrigin)
Set the transform origin.
void setWidth (qreal)
bool smooth () const
QDeclarativeListProperty< QGraphicsTransform > transform ()
TransformOrigin transformOrigin () const
qreal width () const
virtual ~QDeclarativeItem ()
Destroys the QDeclarativeItem.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Static Public Functions
static QDeclarativePathViewAttached * qmlAttachedProperties (QObject *)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
void componentComplete ()
bool event (QEvent *event)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
void mousePressEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *)
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
bool sceneEventFilter (QGraphicsItem *, QEvent *)
Filters events for the item watched.
bool sendMouseEvent (QGraphicsSceneMouseEvent *event)
Protected Functions inherited from QDeclarativeItem
virtual void classBegin ()
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
bool heightValid () const
Returns whether the height property has been set explicitly.
virtual void inputMethodEvent (QInputMethodEvent *)
void inputMethodPreHandler (QInputMethodEvent *)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
bool isComponentComplete () const
Returns true if construction of the QML component is complete; otherwise returns false.
virtual QVariant itemChange (GraphicsItemChange, const QVariant &)
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
virtual void keyPressEvent (QKeyEvent *event)
void keyPressPreHandler (QKeyEvent *)
virtual void keyReleaseEvent (QKeyEvent *event)
void keyReleasePreHandler (QKeyEvent *)
QDeclarativeItem (QDeclarativeItemPrivate &dd, QDeclarativeItem *parent=0)
virtual bool sceneEvent (QEvent *)
void setImplicitHeight (qreal)
Sets the implied height of the item to h.
void setImplicitWidth (qreal)
Sets the implied width of the item to w.
bool widthValid () const
Returns whether the width property has been set explicitly.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
Private Slots
void createdItem (int index, QDeclarativeItem *item)
void destroyingItem (QDeclarativeItem *item)
void itemsInserted (int index, int count)
void itemsMoved (int, int, int)
void itemsRemoved (int index, int count)
void modelReset ()
void movementEnding ()
void pathUpdated ()
void refill ()
void ticked ()
Properties
int count
int currentIndex
QDeclarativeComponent * delegate
qreal dragMargin
qreal flickDeceleration
bool flicking
QDeclarativeComponent * highlight
QDeclarativeItem * highlightItem
int highlightMoveDuration
HighlightRangeMode highlightRangeMode
bool interactive
QVariant model
bool moving
qreal offset
QDeclarativePath * path
int pathItemCount
qreal preferredHighlightBegin
qreal preferredHighlightEnd
Friends
class QDeclarativePathViewAttached
Additional Inherited Members
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
Definition at line 56 of file qdeclarativepathview_p.h.
Enumerations
HighlightRangeMode
enum QDeclarativePathView::HighlightRangeMode
Enumerator
NoHighlightRange
ApplyRange
StrictlyEnforceRange
Definition at line 106 of file qdeclarativepathview_p.h.
 { NoHighlightRange, ApplyRange, StrictlyEnforceRange };
Constructors and Destructors
QDeclarativePathView()
QDeclarativePathView::QDeclarativePathView (QDeclarativeItem * parent = 0)
Definition at line 417 of file qdeclarativepathview.cpp.
   : QDeclarativeItem(*(new QDeclarativePathViewPrivate), parent)
 {
     Q_D(QDeclarativePathView);
     d->init();
 }
~QDeclarativePathView()
QDeclarativePathView::~QDeclarativePathView () virtual
Definition at line 424 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     d->clear();
     if (d->attType)
         d->attType->release();
     if (d->ownModel)
         delete d->model;
 }
Functions
componentComplete()
void QDeclarativePathView::componentComplete () protected virtual
Warning
This function is not part of the public interface.
componentComplete() is called when all items in the component have been constructed. It is often desirable to delay some processing until the component is complete an all bindings in the component have been resolved.
Reimplemented from QDeclarativeItem.
Definition at line 1405 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     QDeclarativeItem::componentComplete();
     if (d->model) {
         d->modelCount = d->model->count();
         if (d->modelCount && d->currentIndex != 0) // an initial value has been provided for currentIndex
             d->offset = qmlMod(d->modelCount - d->currentIndex, d->modelCount);
     }
     d->createHighlight();
     d->regenerate();
     d->updateHighlight();
     d->updateCurrent();
     if (d->modelCount)
         emit countChanged();
 }
count()
int QDeclarativePathView::count () const
Referenced by QDeclarativePathViewPrivate::handleMouseReleaseEvent(), itemsInserted(), itemsRemoved(), refill(), and setModel().
countChanged
void QDeclarativePathView::countChanged () signal
Referenced by componentComplete(), itemsInserted(), itemsRemoved(), modelReset(), setDelegate(), and setModel().
createdItem
void QDeclarativePathView::createdItem (int index, QDeclarativeItem * item) private slot
Definition at line 1667 of file qdeclarativepathview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativePathView);
     if (d->requestedIndex != index) {
         if (!d->attType) {
             // pre-create one metatype to share with all attached objects
             d->attType = new QDeclarativeOpenMetaObjectType(&QDeclarativePathViewAttached::staticMetaObject, qmlEngine(this));
             foreach(const QString &attr, d->path->attributes())
                 d->attType->createProperty(attr.toUtf8());
         }
         qPathViewAttachedType = d->attType;
         QDeclarativePathViewAttached *att = static_cast<QDeclarativePathViewAttached *>(qmlAttachedPropertiesObject<QDeclarativePathView>(item));
         qPathViewAttachedType = 0;
         if (att) {
             att->m_view = this;
             att->setOnPath(false);
         }
         item->setParentItem(this);
         d->updateItem(item, index < d->firstIndex ? qreal(0.0) : qreal(1.0));
     }
 }
currentIndex()
int QDeclarativePathView::currentIndex () const
Referenced by decrementCurrentIndex(), QDeclarativePathViewPrivate::fixOffset(), incrementCurrentIndex(), itemsInserted(), setPath(), QDeclarativePathViewPrivate::snapToCurrent(), and QDeclarativePathViewPrivate::updateCurrent().
currentIndexChanged
void QDeclarativePathView::currentIndexChanged () signal
Referenced by itemsInserted(), itemsMoved(), itemsRemoved(), setCurrentIndex(), and setModel().
decrementCurrentIndex
void QDeclarativePathView::decrementCurrentIndex () slot
Definition at line 692 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     d->moveDirection = QDeclarativePathViewPrivate::Negative;
     setCurrentIndex(currentIndex()-1);
 }
delegate()
QDeclarativeComponent* QDeclarativePathView::delegate () const
Referenced by isFlicking(), and setDelegate().
delegateChanged
void QDeclarativePathView::delegateChanged () signal
Referenced by setDelegate().
destroyingItem
void QDeclarativePathView::destroyingItem (QDeclarativeItem * item) private slot
Definition at line 1689 of file qdeclarativepathview.cpp.
 {
     Q_UNUSED(item);
 }
dragMargin()
qreal QDeclarativePathView::dragMargin () const
Referenced by QDeclarativePathViewPrivate::handleMousePressEvent(), setDragMargin(), and setHighlightMoveDuration().
dragMarginChanged
void QDeclarativePathView::dragMarginChanged () signal
Referenced by setDragMargin().
event()
bool QDeclarativePathView::event (QEvent * ev) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 1395 of file qdeclarativepathview.cpp.
 {
     if (event->type() == QEvent::User) {
         refill();
         return true;
     }
     return QDeclarativeItem::event(event);
 }
flickDeceleration()
qreal QDeclarativePathView::flickDeceleration () const
Referenced by setDragMargin().
flickDecelerationChanged
void QDeclarativePathView::flickDecelerationChanged () signal
Referenced by setFlickDeceleration().
flickEnded
void QDeclarativePathView::flickEnded () signal
Referenced by movementEnding().
flickingChanged
void QDeclarativePathView::flickingChanged () signal
Referenced by movementEnding().
flickStarted
void QDeclarativePathView::flickStarted () signal
highlight()
QDeclarativeComponent* QDeclarativePathView::highlight () const
Referenced by QDeclarativePathViewPrivate::setAdjustedOffset(), and setHighlight().
highlightChanged
void QDeclarativePathView::highlightChanged () signal
Referenced by setHighlight().
highlightItem()
QDeclarativeItem* QDeclarativePathView::highlightItem ()
Referenced by setHighlight().
highlightItemChanged
void QDeclarativePathView::highlightItemChanged () signal
highlightMoveDuration()
int QDeclarativePathView::highlightMoveDuration () const
Referenced by setHighlightRangeMode(), and QDeclarativePathViewPrivate::snapToCurrent().
highlightMoveDurationChanged
void QDeclarativePathView::highlightMoveDurationChanged () signal
Referenced by setHighlightMoveDuration().
highlightRangeMode()
HighlightRangeMode QDeclarativePathView::highlightRangeMode () const
Referenced by QDeclarativePathViewPrivate::fixOffset(), QDeclarativePathViewPrivate::handleMouseReleaseEvent(), setPreferredHighlightEnd(), and QDeclarativePathViewPrivate::updateCurrent().
highlightRangeModeChanged
void QDeclarativePathView::highlightRangeModeChanged () signal
Referenced by setHighlightRangeMode().
incrementCurrentIndex
void QDeclarativePathView::incrementCurrentIndex () slot
Definition at line 674 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     d->moveDirection = QDeclarativePathViewPrivate::Positive;
     setCurrentIndex(currentIndex()+1);
 }
interactiveChanged
void QDeclarativePathView::interactiveChanged () signal
Referenced by setInteractive().
isFlicking()
bool QDeclarativePathView::isFlicking () const
Definition at line 1017 of file qdeclarativepathview.cpp.
 {
     Q_D(const QDeclarativePathView);
     return d->flicking;
 }
isInteractive()
bool QDeclarativePathView::isInteractive () const
Definition at line 976 of file qdeclarativepathview.cpp.
 {
     Q_D(const QDeclarativePathView);
     return d->interactive;
 }
isMoving()
bool QDeclarativePathView::isMoving () const
Definition at line 1002 of file qdeclarativepathview.cpp.
 {
     Q_D(const QDeclarativePathView);
     return d->moving;
 }
itemsInserted
void QDeclarativePathView::itemsInserted (int index, int count) private slot
Definition at line 1548 of file qdeclarativepathview.cpp.
Referenced by setModel().
 {
     //XXX support animated insertion
     Q_D(QDeclarativePathView);
     if (!d->isValid() || !isComponentComplete())
         return;
     if (d->modelCount) {
         d->itemCache += d->items;
         d->items.clear();
         if (modelIndex <= d->currentIndex) {
             d->currentIndex += count;
             emit currentIndexChanged();
         } else if (d->offset != 0) {
             d->offset += count;
             d->offsetAdj += count;
         }
     }
     d->modelCount += count;
     if (d->flicking || d->moving) {
         d->regenerate();
         d->updateCurrent();
     } else {
         d->firstIndex = -1;
         d->updateMappedRange();
         d->scheduleLayout();
     }
     emit countChanged();
 }
itemsMoved
void QDeclarativePathView::itemsMoved (int , int , int) private slot
Definition at line 1637 of file qdeclarativepathview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativePathView);
     if (!d->isValid() || !isComponentComplete())
         return;
     int oldCurrent = d->currentIndex;
     // Fix current index
     if (d->currentIndex >= 0 && d->currentItem)
         d->currentIndex = d->model->indexOf(d->currentItem, this);
     QList<QDeclarativeItem *> removedItems = d->items;
     d->items.clear();
     d->regenerate();
     while (removedItems.count())
         d->releaseItem(removedItems.takeLast());
     if (oldCurrent != d->currentIndex)
         emit currentIndexChanged();
     d->updateCurrent();
 }
itemsRemoved
void QDeclarativePathView::itemsRemoved (int index, int count) private slot
Definition at line 1578 of file qdeclarativepathview.cpp.
Referenced by setModel().
 {
     //XXX support animated removal
     Q_D(QDeclarativePathView);
     if (!d->model || !d->modelCount || !d->model->isValid() || !d->path || !isComponentComplete())
         return;
     // fix current
     bool currentChanged = false;
     if (d->currentIndex >= modelIndex + count) {
         d->currentIndex -= count;
         currentChanged = true;
     } else if (d->currentIndex >= modelIndex && d->currentIndex < modelIndex + count) {
         // current item has been removed.
         d->currentIndex = qMin(modelIndex, d->modelCount-count-1);
         if (d->currentItem) {
             if (QDeclarativePathViewAttached *att = d->attached(d->currentItem))
                 att->setIsCurrentItem(true);
         }
         currentChanged = true;
     }
     d->itemCache += d->items;
     d->items.clear();
     bool changedOffset = false;
     if (modelIndex > d->currentIndex) {
         if (d->offset >= count) {
             changedOffset = true;
             d->offset -= count;
             d->offsetAdj -= count;
         }
     }
     d->modelCount -= count;
     if (d->currentIndex == -1)
         d->currentIndex = d->calcCurrentIndex();
     if (!d->modelCount) {
         while (d->itemCache.count())
             d->releaseItem(d->itemCache.takeLast());
         d->offset = 0;
         changedOffset = true;
         d->tl.reset(d->moveOffset);
         update();
     } else {
         d->regenerate();
         d->updateCurrent();
         if (!d->flicking && !d->moving && d->haveHighlightRange && d->highlightRangeMode == QDeclarativePathView::StrictlyEnforceRange)
             d->snapToCurrent();
     }
     if (changedOffset)
         emit offsetChanged();
     if (currentChanged)
         emit currentIndexChanged();
     emit countChanged();
 }
model()
QVariant QDeclarativePathView::model () const
Referenced by QDeclarativePathViewPrivate::calcCurrentIndex(), QDeclarativePathViewPrivate::fixOffset(), QDeclarativePathViewPrivate::handleMouseReleaseEvent(), setModel(), QDeclarativePathViewPrivate::snapToCurrent(), QDeclarativePathViewPrivate::updateCurrent(), and ~QDeclarativePathView().
modelChanged
void QDeclarativePathView::modelChanged () signal
Referenced by setModel().
modelReset
void QDeclarativePathView::modelReset () private slot
Definition at line 1659 of file qdeclarativepathview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativePathView);
     d->modelCount = d->model->count();
     d->regenerate();
     emit countChanged();
 }
mouseMoveEvent()
void QDeclarativePathView::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
If you do receive this event, you can be certain that this item also received a mouse press event, and that this item is the current mouse grabber.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mouseMoveEvent() in your reimplementation.
Please note that mousePressEvent() decides which graphics item it is that receives mouse events. See the mousePressEvent() description for details.
See also
mousePressEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 1214 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->interactive) {
         d->handleMouseMoveEvent(event);
         if (d->stealMouse)
             setKeepMouseGrab(true);
         event->accept();
     } else {
         QDeclarativeItem::mouseMoveEvent(event);
     }
 }
mousePressEvent()
void QDeclarativePathView::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
Mouse press events are only delivered to items that accept the mouse button that is pressed. By default, an item accepts all mouse buttons, but you can change this by calling setAcceptedMouseButtons().
The mouse press event decides which item should become the mouse grabber (see QGraphicsScene::mouseGrabberItem()). If you do not reimplement this function, the press event will propagate to any topmost item beneath this item, and no other mouse events will be delivered to this item.
If you do reimplement this function, event will by default be accepted (see QEvent::accept()), and this item is then the mouse grabber. This allows the item to receive future move, release and doubleclick events. If you call QEvent::ignore() on event, this item will lose the mouse grab, and event will propagate to any topmost item beneath. No further mouse events will be delivered to this item unless a new mouse press event is received.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mousePressEvent() in your reimplementation.
The event is for items that are neither QGraphicsItem::ItemIsMovable "movable" nor QGraphicsItem::ItemIsSelectable "selectable". mouseMoveEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 1169 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->interactive) {
         d->handleMousePressEvent(event);
         event->accept();
     } else {
         QDeclarativeItem::mousePressEvent(event);
     }
 }
mouseReleaseEvent()
void QDeclarativePathView::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mouseReleaseEvent() in your reimplementation.
Please note that mousePressEvent() decides which graphics item it is that receives mouse events. See the mousePressEvent() description for details.
See also
mousePressEvent(), mouseMoveEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 1266 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->interactive) {
         d->handleMouseReleaseEvent(event);
         event->accept();
         ungrabMouse();
     } else {
         QDeclarativeItem::mouseReleaseEvent(event);
     }
 }
movementEnded
void QDeclarativePathView::movementEnded () signal
Referenced by movementEnding().
movementEnding
void QDeclarativePathView::movementEnding () private slot
Definition at line 1700 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->flicking) {
         d->flicking = false;
         emit flickingChanged();
         emit flickEnded();
     }
     if (d->moving && !d->stealMouse) {
         d->moving = false;
         emit movingChanged();
         emit movementEnded();
     }
 }
movementStarted
void QDeclarativePathView::movementStarted () signal
movingChanged
void QDeclarativePathView::movingChanged () signal
Referenced by movementEnding().
offset()
qreal QDeclarativePathView::offset () const
Referenced by QDeclarativePathViewPrivate::calcCurrentIndex(), decrementCurrentIndex(), QDeclarativePathViewPrivate::handleMouseMoveEvent(), QDeclarativePathViewPrivate::handleMouseReleaseEvent(), QDeclarativePathViewPrivate::setOffset(), and QDeclarativePathViewPrivate::snapToCurrent().
offsetChanged
void QDeclarativePathView::offsetChanged () signal
Referenced by itemsRemoved(), and setModel().
path()
QDeclarativePath* QDeclarativePathView::path () const
Referenced by QDeclarativePathViewPrivate::pointNear(), setModel(), and setPath().
pathChanged
void QDeclarativePathView::pathChanged () signal
Referenced by setPath().
pathItemCount()
int QDeclarativePathView::pathItemCount () const
Referenced by setDelegate().
pathItemCountChanged
void QDeclarativePathView::pathItemCountChanged () signal
Referenced by setPathItemCount().
pathUpdated
void QDeclarativePathView::pathUpdated () private slot
Definition at line 306 of file qdeclarativepathview.cpp.
Referenced by setPath().
 {
     Q_D(QDeclarativePathView);
     QList<QDeclarativeItem*>::iterator it = d->items.begin();
     while (it != d->items.end()) {
         QDeclarativeItem *item = *it;
         if (QDeclarativePathViewAttached *att = d->attached(item))
             att->m_percent = -1;
         ++it;
     }
     refill();
 }
preferredHighlightBegin()
qreal QDeclarativePathView::preferredHighlightBegin () const
Referenced by setHighlight().
preferredHighlightBeginChanged
void QDeclarativePathView::preferredHighlightBeginChanged () signal
Referenced by setPreferredHighlightBegin().
preferredHighlightEnd()
qreal QDeclarativePathView::preferredHighlightEnd () const
Referenced by setPreferredHighlightBegin().
preferredHighlightEndChanged
void QDeclarativePathView::preferredHighlightEndChanged () signal
Referenced by setPreferredHighlightEnd().
qmlAttachedProperties()
QDeclarativePathViewAttached * QDeclarativePathView::qmlAttachedProperties (QObject * obj) static
Definition at line 1819 of file qdeclarativepathview.cpp.
 {
     return new QDeclarativePathViewAttached(obj);
 }
refill
void QDeclarativePathView::refill () private slot
Definition at line 1425 of file qdeclarativepathview.cpp.
Referenced by event(), setPreferredHighlightBegin(), and setPreferredHighlightEnd().
 {
     Q_D(QDeclarativePathView);
     if (!d->isValid() || !isComponentComplete())
         return;
     d->layoutScheduled = false;
     bool currentVisible = false;
     // first move existing items and remove items off path
     int idx = d->firstIndex;
     QList<QDeclarativeItem*>::iterator it = d->items.begin();
     while (it != d->items.end()) {
         qreal pos = d->positionOfIndex(idx);
         QDeclarativeItem *item = *it;
         if (pos >= 0.0) {
             d->updateItem(item, pos);
             if (idx == d->currentIndex) {
                 currentVisible = true;
                 d->currentItemOffset = pos;
             }
             ++it;
         } else {
 //            qDebug() << "release";
             d->updateItem(item, 1.0);
             d->releaseItem(item);
             if (it == d->items.begin()) {
                 if (++d->firstIndex >= d->modelCount)
                     d->firstIndex = 0;
             }
             it = d->items.erase(it);
         }
         ++idx;
         if (idx >= d->modelCount)
             idx = 0;
     }
     if (!d->items.count())
         d->firstIndex = -1;
     if (d->modelCount) {
         // add items to beginning and end
         int count = d->pathItems == -1 ? d->modelCount : qMin(d->pathItems, d->modelCount);
         if (d->items.count() < count) {
             int idx = qRound(d->modelCount - d->offset) % d->modelCount;
             qreal startPos = 0.0;
             if (d->haveHighlightRange && d->highlightRangeMode != QDeclarativePathView::NoHighlightRange)
                 startPos = d->highlightRangeStart;
             if (d->firstIndex >= 0) {
                 startPos = d->positionOfIndex(d->firstIndex);
                 idx = (d->firstIndex + d->items.count()) % d->modelCount;
             }
             qreal pos = d->positionOfIndex(idx);
             while ((pos > startPos || !d->items.count()) && d->items.count() < count) {
     //            qDebug() << "append" << idx;
                 QDeclarativeItem *item = d->getItem(idx);
                 if (d->model->completePending())
                     item->setZValue(idx+1);
                 if (d->currentIndex == idx) {
                     item->setFocus(true);
                     if (QDeclarativePathViewAttached *att = d->attached(item))
                         att->setIsCurrentItem(true);
                     currentVisible = true;
                     d->currentItemOffset = pos;
                     d->currentItem = item;
                 }
                 if (d->items.count() == 0)
                     d->firstIndex = idx;
                 d->items.append(item);
                 d->updateItem(item, pos);
                 if (d->model->completePending())
                     d->model->completeItem();
                 ++idx;
                 if (idx >= d->modelCount)
                     idx = 0;
                 pos = d->positionOfIndex(idx);
             }
             idx = d->firstIndex - 1;
             if (idx < 0)
                 idx = d->modelCount - 1;
             pos = d->positionOfIndex(idx);
             while (pos >= 0.0 && pos < startPos) {
     //            qDebug() << "prepend" << idx;
                 QDeclarativeItem *item = d->getItem(idx);
                 if (d->model->completePending())
                     item->setZValue(idx+1);
                 if (d->currentIndex == idx) {
                     item->setFocus(true);
                     if (QDeclarativePathViewAttached *att = d->attached(item))
                         att->setIsCurrentItem(true);
                     currentVisible = true;
                     d->currentItemOffset = pos;
                     d->currentItem = item;
                 }
                 d->items.prepend(item);
                 d->updateItem(item, pos);
                 if (d->model->completePending())
                     d->model->completeItem();
                 d->firstIndex = idx;
                 idx = d->firstIndex - 1;
                 if (idx < 0)
                     idx = d->modelCount - 1;
                 pos = d->positionOfIndex(idx);
             }
         }
     }
     if (!currentVisible)
         d->currentItemOffset = 1.0;
     if (d->highlightItem && d->haveHighlightRange && d->highlightRangeMode == QDeclarativePathView::StrictlyEnforceRange) {
         d->updateItem(d->highlightItem, d->highlightRangeStart);
         if (QDeclarativePathViewAttached *att = d->attached(d->highlightItem))
             att->setOnPath(true);
     } else if (d->highlightItem && d->moveReason != QDeclarativePathViewPrivate::SetIndex) {
         d->updateItem(d->highlightItem, d->currentItemOffset);
         if (QDeclarativePathViewAttached *att = d->attached(d->highlightItem))
             att->setOnPath(currentVisible);
     }
     while (d->itemCache.count())
         d->releaseItem(d->itemCache.takeLast());
 }
sceneEventFilter()
bool QDeclarativePathView::sceneEventFilter (QGraphicsItem * watched, QEvent * event) protected virtual
Filters events for the item watched.
event is the filtered event.
Reimplementing this function in a subclass makes it possible for the item to be used as an event filter for other items, intercepting all the events send to those items before they are able to respond.
Reimplementations must return true to prevent further processing of a given event, ensuring that it will not be delivered to the watched item, or return false to indicate that the event should be propagated further by the event system.
See also
installSceneEventFilter()
Reimplemented from QGraphicsItem.
Definition at line 1377 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (!isVisible() || !d->interactive)
         return QDeclarativeItem::sceneEventFilter(i, e);
     switch (e->type()) {
     case QEvent::GraphicsSceneMousePress:
     case QEvent::GraphicsSceneMouseMove:
     case QEvent::GraphicsSceneMouseRelease:
         return sendMouseEvent(static_cast<QGraphicsSceneMouseEvent *>(e));
     default:
         break;
     }
     return QDeclarativeItem::sceneEventFilter(i, e);
 }
sendMouseEvent()
bool QDeclarativePathView::sendMouseEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 1329 of file qdeclarativepathview.cpp.
Referenced by sceneEventFilter().
 {
     Q_D(QDeclarativePathView);
     QGraphicsSceneMouseEvent mouseEvent(event->type());
     QRectF myRect = mapToScene(QRectF(0, 0, width(), height())).boundingRect();
     QGraphicsScene *s = scene();
     QDeclarativeItem *grabber = s ? qobject_cast<QDeclarativeItem*>(s->mouseGrabberItem()) : 0;
     bool stealThisEvent = d->stealMouse;
     if ((stealThisEvent || myRect.contains(event->scenePos().toPoint())) && (!grabber || !grabber->keepMouseGrab())) {
         mouseEvent.setAccepted(false);
         for (int i = 0x1; i <= 0x10; i <<= 1) {
             if (event->buttons() & i) {
                 Qt::MouseButton button = Qt::MouseButton(i);
                 mouseEvent.setButtonDownPos(button, mapFromScene(event->buttonDownPos(button)));
             }
         }
         mouseEvent.setScenePos(event->scenePos());
         mouseEvent.setLastScenePos(event->lastScenePos());
         mouseEvent.setPos(mapFromScene(event->scenePos()));
         mouseEvent.setLastPos(mapFromScene(event->lastScenePos()));
         switch(mouseEvent.type()) {
         case QEvent::GraphicsSceneMouseMove:
             d->handleMouseMoveEvent(&mouseEvent);
             break;
         case QEvent::GraphicsSceneMousePress:
             d->handleMousePressEvent(&mouseEvent);
             stealThisEvent = d->stealMouse;   // Update stealThisEvent in case changed by function call above
             break;
         case QEvent::GraphicsSceneMouseRelease:
             d->handleMouseReleaseEvent(&mouseEvent);
             break;
         default:
             break;
         }
         grabber = qobject_cast<QDeclarativeItem*>(s->mouseGrabberItem());
         if (grabber && stealThisEvent && !grabber->keepMouseGrab() && grabber != this)
             grabMouse();
         return d->stealMouse;
     } else if (d->lastPosTime.isValid()) {
         d->lastPosTime.invalidate();
     }
     if (mouseEvent.type() == QEvent::GraphicsSceneMouseRelease)
         d->stealMouse = false;
     return false;
 }
setCurrentIndex()
void QDeclarativePathView::setCurrentIndex (int idx)
Definition at line 620 of file qdeclarativepathview.cpp.
Referenced by decrementCurrentIndex(), and incrementCurrentIndex().
 {
     Q_D(QDeclarativePathView);
     if (!isComponentComplete()) {
         if (idx != d->currentIndex) {
             d->currentIndex = idx;
             emit currentIndexChanged();
         }
         return;
     }
     idx = d->modelCount
         ? ((idx % d->modelCount) + d->modelCount) % d->modelCount
         : 0;
     if (d->model && idx != d->currentIndex) {
         if (d->modelCount) {
             int itemIndex = (d->currentIndex - d->firstIndex + d->modelCount) % d->modelCount;
             if (itemIndex < d->items.count()) {
                 if (QDeclarativeItem *item = d->items.at(itemIndex)) {
                     if (QDeclarativePathViewAttached *att = d->attached(item))
                         att->setIsCurrentItem(false);
                 }
             }
         }
         d->currentItem = 0;
         d->moveReason = QDeclarativePathViewPrivate::SetIndex;
         d->currentIndex = idx;
         if (d->modelCount) {
             if (d->haveHighlightRange && d->highlightRangeMode == QDeclarativePathView::StrictlyEnforceRange)
                 d->snapToCurrent();
             int itemIndex = (idx - d->firstIndex + d->modelCount) % d->modelCount;
             if (itemIndex < d->items.count()) {
                 d->currentItem = d->items.at(itemIndex);
                 d->currentItem->setFocus(true);
                 if (QDeclarativePathViewAttached *att = d->attached(d->currentItem))
                     att->setIsCurrentItem(true);
             }
             d->currentItemOffset = d->positionOfIndex(d->currentIndex);
             d->updateHighlight();
         }
         emit currentIndexChanged();
     }
 }
setDelegate()
void QDeclarativePathView::setDelegate (QDeclarativeComponent * delegate)
Definition at line 1098 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (delegate == this->delegate())
         return;
     if (!d->ownModel) {
         d->model = new QDeclarativeVisualDataModel(qmlContext(this));
         d->ownModel = true;
     }
     if (QDeclarativeVisualDataModel *dataModel = qobject_cast<QDeclarativeVisualDataModel*>(d->model)) {
         int oldCount = dataModel->count();
         dataModel->setDelegate(delegate);
         d->modelCount = dataModel->count();
         d->regenerate();
         if (oldCount != dataModel->count())
             emit countChanged();
         emit delegateChanged();
     }
 }
setDragMargin()
void QDeclarativePathView::setDragMargin (qreal margin)
Definition at line 932 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->dragMargin == dragMargin)
         return;
     d->dragMargin = dragMargin;
     emit dragMarginChanged();
 }
setFlickDeceleration()
void QDeclarativePathView::setFlickDeceleration (qreal dec)
Definition at line 956 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->deceleration == dec)
         return;
     d->deceleration = dec;
     emit flickDecelerationChanged();
 }
setHighlight()
void QDeclarativePathView::setHighlight (QDeclarativeComponent * highlight)
Definition at line 775 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (highlight != d->highlightComponent) {
         d->highlightComponent = highlight;
         d->createHighlight();
         d->updateHighlight();
         emit highlightChanged();
     }
 }
setHighlightMoveDuration()
void QDeclarativePathView::setHighlightMoveDuration (int duration)
Definition at line 906 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->highlightMoveDuration == duration)
         return;
     d->highlightMoveDuration = duration;
     emit highlightMoveDurationChanged();
 }
setHighlightRangeMode()
void QDeclarativePathView::setHighlightRangeMode (HighlightRangeMode mode)
Definition at line 877 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->highlightRangeMode == mode)
         return;
     d->highlightRangeMode = mode;
     d->haveHighlightRange = d->highlightRangeMode != NoHighlightRange && d->highlightRangeStart <= d->highlightRangeEnd;
     emit highlightRangeModeChanged();
 }
setInteractive()
void QDeclarativePathView::setInteractive (bool interactive)
Definition at line 982 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (interactive != d->interactive) {
         d->interactive = interactive;
         if (!interactive)
             d->tl.clear();
         emit interactiveChanged();
     }
 }
setModel()
void QDeclarativePathView::setModel (const QVariant & model)
Definition at line 502 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->modelVariant == model)
         return;
     if (d->model) {
         disconnect(d->model, SIGNAL(itemsInserted(int,int)), this, SLOT(itemsInserted(int,int)));
         disconnect(d->model, SIGNAL(itemsRemoved(int,int)), this, SLOT(itemsRemoved(int,int)));
         disconnect(d->model, SIGNAL(itemsMoved(int,int,int)), this, SLOT(itemsMoved(int,int,int)));
         disconnect(d->model, SIGNAL(modelReset()), this, SLOT(modelReset()));
         disconnect(d->model, SIGNAL(createdItem(int,QDeclarativeItem*)), this, SLOT(createdItem(int,QDeclarativeItem*)));
         d->clear();
     }
     d->modelVariant = model;
     QObject *object = qvariant_cast<QObject*>(model);
     QDeclarativeVisualModel *vim = 0;
     if (object && (vim = qobject_cast<QDeclarativeVisualModel *>(object))) {
         if (d->ownModel) {
             delete d->model;
             d->ownModel = false;
         }
         d->model = vim;
     } else {
         if (!d->ownModel) {
             d->model = new QDeclarativeVisualDataModel(qmlContext(this), this);
             d->ownModel = true;
         }
         if (QDeclarativeVisualDataModel *dataModel = qobject_cast<QDeclarativeVisualDataModel*>(d->model))
             dataModel->setModel(model);
     }
     int oldModelCount = d->modelCount;
     d->modelCount = 0;
     if (d->model) {
         connect(d->model, SIGNAL(itemsInserted(int,int)), this, SLOT(itemsInserted(int,int)));
         connect(d->model, SIGNAL(itemsRemoved(int,int)), this, SLOT(itemsRemoved(int,int)));
         connect(d->model, SIGNAL(itemsMoved(int,int,int)), this, SLOT(itemsMoved(int,int,int)));
         connect(d->model, SIGNAL(modelReset()), this, SLOT(modelReset()));
         connect(d->model, SIGNAL(createdItem(int,QDeclarativeItem*)), this, SLOT(createdItem(int,QDeclarativeItem*)));
         d->modelCount = d->model->count();
     }
     if (isComponentComplete()) {
         if (d->currentIndex != 0) {
             d->currentIndex = 0;
             emit currentIndexChanged();
         }
         if (d->offset != 0.0) {
             d->offset = 0;
             emit offsetChanged();
         }
     }
     d->regenerate();
     if (d->modelCount != oldModelCount)
         emit countChanged();
     emit modelChanged();
 }
setOffset()
void QDeclarativePathView::setOffset (qreal offset)
Definition at line 714 of file qdeclarativepathview.cpp.
Referenced by QDeclarativePathViewPrivate::setAdjustedOffset().
 {
     Q_D(QDeclarativePathView);
     d->setOffset(offset);
     d->updateCurrent();
 }
setPath()
void QDeclarativePathView::setPath (QDeclarativePath * path)
Definition at line 587 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->path == path)
         return;
     if (d->path)
         disconnect(d->path, SIGNAL(changed()), this, SLOT(pathUpdated()));
     d->path = path;
     connect(d->path, SIGNAL(changed()), this, SLOT(pathUpdated()));
     if (d->isValid() && isComponentComplete()) {
         d->clear();
         if (d->attType) {
             d->attType->release();
             d->attType = 0;
         }
         d->regenerate();
     }
     emit pathChanged();
 }
setPathItemCount()
void QDeclarativePathView::setPathItemCount (int i)
Definition at line 1131 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (i == d->pathItems)
         return;
     if (i < 1)
         i = 1;
     d->pathItems = i;
     d->updateMappedRange();
     if (d->isValid() && isComponentComplete()) {
         d->regenerate();
     }
     emit pathItemCountChanged();
 }
setPreferredHighlightBegin()
void QDeclarativePathView::setPreferredHighlightBegin (qreal start)
Definition at line 843 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->highlightRangeStart == start || start < 0 || start > 1.0)
         return;
     d->highlightRangeStart = start;
     d->haveHighlightRange = d->highlightRangeMode != NoHighlightRange && d->highlightRangeStart <= d->highlightRangeEnd;
     refill();
     emit preferredHighlightBeginChanged();
 }
setPreferredHighlightEnd()
void QDeclarativePathView::setPreferredHighlightEnd (qreal end)
Definition at line 860 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     if (d->highlightRangeEnd == end || end < 0 || end > 1.0)
         return;
     d->highlightRangeEnd = end;
     d->haveHighlightRange = d->highlightRangeMode != NoHighlightRange && d->highlightRangeStart <= d->highlightRangeEnd;
     refill();
     emit preferredHighlightEndChanged();
 }
snapPositionChanged
void QDeclarativePathView::snapPositionChanged () signal
ticked
void QDeclarativePathView::ticked () private slot
Definition at line 1694 of file qdeclarativepathview.cpp.
 {
     Q_D(QDeclarativePathView);
     d->updateCurrent();
 }
Friends and Related Functions
QDeclarativePathViewAttached
friend class QDeclarativePathViewAttached friend
Definition at line 192 of file qdeclarativepathview_p.h.
Referenced by qmlAttachedProperties().
Properties
count
int QDeclarativePathView::count private
Definition at line 80 of file qdeclarativepathview_p.h.
currentIndex
int QDeclarativePathView::currentIndex private
Definition at line 62 of file qdeclarativepathview_p.h.
delegate
QDeclarativeComponent * QDeclarativePathView::delegate private
Definition at line 81 of file qdeclarativepathview_p.h.
dragMargin
qreal QDeclarativePathView::dragMargin private
Definition at line 73 of file qdeclarativepathview_p.h.
flickDeceleration
qreal QDeclarativePathView::flickDeceleration private
Definition at line 74 of file qdeclarativepathview_p.h.
flicking
bool QDeclarativePathView::flicking private
Definition at line 78 of file qdeclarativepathview_p.h.
Referenced by QDeclarativePathViewPrivate::handleMousePressEvent(), and QDeclarativePathViewPrivate::handleMouseReleaseEvent().
highlight
QDeclarativeComponent * QDeclarativePathView::highlight private
Definition at line 65 of file qdeclarativepathview_p.h.
highlightItem
QDeclarativeItem * QDeclarativePathView::highlightItem private
Definition at line 66 of file qdeclarativepathview_p.h.
highlightMoveDuration
int QDeclarativePathView::highlightMoveDuration private
Definition at line 71 of file qdeclarativepathview_p.h.
highlightRangeMode
QDeclarativePathView::HighlightRangeMode QDeclarativePathView::highlightRangeMode private
Definition at line 70 of file qdeclarativepathview_p.h.
interactive
bool QDeclarativePathView::interactive private
Definition at line 75 of file qdeclarativepathview_p.h.
Referenced by QDeclarativePathViewPrivate::handleMouseMoveEvent(), QDeclarativePathViewPrivate::handleMousePressEvent(), QDeclarativePathViewPrivate::handleMouseReleaseEvent(), and setInteractive().
model
QVariant QDeclarativePathView::model private
Definition at line 60 of file qdeclarativepathview_p.h.
moving
bool QDeclarativePathView::moving private
Definition at line 77 of file qdeclarativepathview_p.h.
Referenced by QDeclarativePathViewPrivate::handleMouseMoveEvent().
offset
qreal QDeclarativePathView::offset private
Definition at line 63 of file qdeclarativepathview_p.h.
path
QDeclarativePath * QDeclarativePathView::path private
Definition at line 61 of file qdeclarativepathview_p.h.
pathItemCount
int QDeclarativePathView::pathItemCount private
Definition at line 82 of file qdeclarativepathview_p.h.
preferredHighlightBegin
qreal QDeclarativePathView::preferredHighlightBegin private
Definition at line 68 of file qdeclarativepathview_p.h.
preferredHighlightEnd
qreal QDeclarativePathView::preferredHighlightEnd private
Definition at line 69 of file qdeclarativepathview_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativepathview_p.h
/src/declarative/graphicsitems/qdeclarativepathview.cpp