Qt 4.8: QGLFramebufferObjectPool Class Reference
QGLFramebufferObjectPool Class Reference
The QGLFramebufferObject class provides a pool of framebuffer objects for offscreen rendering purposes.
#include <qpixmapdata_gl_p.h>
Public Functions
QGLFramebufferObject * acquire (const QSize &size, const QGLFramebufferObjectFormat &format, bool strictSize=false)
void release (QGLFramebufferObject *fbo)
Properties
QList< QGLFramebufferObject * > m_fbos
Detailed Description
The QGLFramebufferObject class provides a pool of framebuffer objects for offscreen rendering purposes.
Since
4.6
When requesting an FBO of a given size and format, an FBO of the same format and a size at least as big as the requested size will be returned.
Warning
This function is not part of the public interface.
Definition at line 79 of file qpixmapdata_gl_p.h.
Functions
acquire()
QGLFramebufferObject * QGLFramebufferObjectPool::acquire (const QSize & size, const QGLFramebufferObjectFormat & format, bool strictSize = false)
Definition at line 99 of file qpixmapdata_gl.cpp.
Referenced by QGLWindowSurface::flush(), and QGLPixmapData::paintEngine().
 {
     QGLFramebufferObject *chosen = 0;
     QGLFramebufferObject *candidate = 0;
     for (int i = 0; !chosen && i < m_fbos.size(); ++i) {
         QGLFramebufferObject *fbo = m_fbos.at(i);
         if (strictSize) {
             if (fbo->size() == requestSize && fbo->format() == requestFormat) {
                 chosen = fbo;
                 break;
             } else {
                 continue;
             }
         }
         if (fbo->format() == requestFormat) {
             // choose the fbo with a matching format and the closest size
             if (!candidate || areaDiff(requestSize, candidate) > areaDiff(requestSize, fbo))
                 candidate = fbo;
         }
         if (candidate) {
             m_fbos.removeOne(candidate);
             const QSize fboSize = candidate->size();
             QSize sz = fboSize;
             if (sz.width() < requestSize.width())
                 sz.setWidth(qMax(requestSize.width(), qRound(sz.width() * 1.5)));
             if (sz.height() < requestSize.height())
                 sz.setHeight(qMax(requestSize.height(), qRound(sz.height() * 1.5)));
             // wasting too much space?
             if (sz.width() * sz.height() > requestSize.width() * requestSize.height() * 4)
                 sz = requestSize;
             if (sz != fboSize) {
                 delete candidate;
                 candidate = new QGLFramebufferObject(maybeRoundToNextPowerOfTwo(sz), requestFormat);
             }
             chosen = candidate;
         }
     }
     if (!chosen) {
         if (strictSize)
             chosen = new QGLFramebufferObject(requestSize, requestFormat);
         else
             chosen = new QGLFramebufferObject(maybeRoundToNextPowerOfTwo(requestSize), requestFormat);
     }
     if (!chosen->isValid()) {
         delete chosen;
         chosen = 0;
     }
     return chosen;
 }
release()
void QGLFramebufferObjectPool::release (QGLFramebufferObject * fbo)
Definition at line 160 of file qpixmapdata_gl.cpp.
Referenced by QGLPixmapGLPaintDevice::endPaint(), and QGLWindowSurface::flush().
 {
     if (fbo)
         m_fbos << fbo;
 }
Properties
m_fbos
QList<QGLFramebufferObject *> QGLFramebufferObjectPool::m_fbos private
Definition at line 86 of file qpixmapdata_gl_p.h.
Referenced by acquire(), and release().
The documentation for this class was generated from the following files:
/src/opengl/qpixmapdata_gl_p.h
/src/opengl/qpixmapdata_gl.cpp