Qt 4.8: QGraphicsSceneMoveEvent Class Reference
QGraphicsSceneMoveEvent Class Reference
The QGraphicsSceneMoveEvent class provides events for widget moving in the graphics view framework.
#include <qgraphicssceneevent.h>
Public Functions
QPointF newPos () const
Returns the new position (i.e., the current position).
QPointF oldPos () const
Returns the old position (i.e., the position immediately before the widget was moved).
QGraphicsSceneMoveEvent ()
Constructs a QGraphicsSceneMoveEvent.
void setNewPos (const QPointF &pos)
void setOldPos (const QPointF &pos)
~QGraphicsSceneMoveEvent ()
Destroys the QGraphicsSceneMoveEvent.
Public Functions inherited from QGraphicsSceneEvent
QGraphicsSceneEvent (Type type)
Constructs a generic graphics scene event of the specified type.
void setWidget (QWidget *widget)
Sets the widget related to this event.
QWidget * widget () const
Returns the widget where the event originated, or 0 if the event originates from another application.
~QGraphicsSceneEvent ()
Destroys the event.
Public Functions inherited from QEvent
void accept ()
Sets the accept flag of the event object, the equivalent of calling setAccepted(true).
void ignore ()
Clears the accept flag parameter of the event object, the equivalent of calling setAccepted(false).
bool isAccepted () const
QEvent (Type type)
Contructs an event object of type type.
void setAccepted (bool accepted)
bool spontaneous () const
Returns true if the event originated outside the application (a system event); otherwise returns false.
Type type () const
Returns the event type.
virtual ~QEvent ()
Destroys the event.
Additional Inherited Members
Public Types inherited from QEvent
enum Type {
None = 0, Timer = 1, MouseButtonPress = 2, MouseButtonRelease = 3,
MouseButtonDblClick = 4, MouseMove = 5, KeyPress = 6, KeyRelease = 7,
FocusIn = 8, FocusOut = 9, Enter = 10, Leave = 11,
Paint = 12, Move = 13, Resize = 14, Create = 15,
Destroy = 16, Show = 17, Hide = 18, Close = 19,
Quit = 20, ParentChange = 21, ParentAboutToChange = 131, ThreadChange = 22,
WindowActivate = 24, WindowDeactivate = 25, ShowToParent = 26, HideToParent = 27,
Wheel = 31, WindowTitleChange = 33, WindowIconChange = 34, ApplicationWindowIconChange = 35,
ApplicationFontChange = 36, ApplicationLayoutDirectionChange = 37, ApplicationPaletteChange = 38, PaletteChange = 39,
Clipboard = 40, Speech = 42, MetaCall = 43, SockAct = 50,
WinEventAct = 132, DeferredDelete = 52, DragEnter = 60, DragMove = 61,
DragLeave = 62, Drop = 63, DragResponse = 64, ChildAdded = 68,
ChildPolished = 69, ChildRemoved = 71, ShowWindowRequest = 73, PolishRequest = 74,
Polish = 75, LayoutRequest = 76, UpdateRequest = 77, UpdateLater = 78,
EmbeddingControl = 79, ActivateControl = 80, DeactivateControl = 81, ContextMenu = 82,
InputMethod = 83, AccessibilityPrepare = 86, TabletMove = 87, LocaleChange = 88,
LanguageChange = 89, LayoutDirectionChange = 90, Style = 91, TabletPress = 92,
TabletRelease = 93, OkRequest = 94, HelpRequest = 95, IconDrag = 96,
FontChange = 97, EnabledChange = 98, ActivationChange = 99, StyleChange = 100,
IconTextChange = 101, ModifiedChange = 102, MouseTrackingChange = 109, WindowBlocked = 103,
WindowUnblocked = 104, WindowStateChange = 105, ToolTip = 110, WhatsThis = 111,
StatusTip = 112, ActionChanged = 113, ActionAdded = 114, ActionRemoved = 115,
FileOpen = 116, Shortcut = 117, ShortcutOverride = 51, WhatsThisClicked = 118,
ToolBarChange = 120, ApplicationActivate = 121, ApplicationActivated = ApplicationActivate, ApplicationDeactivate = 122,
ApplicationDeactivated = ApplicationDeactivate, QueryWhatsThis = 123, EnterWhatsThisMode = 124, LeaveWhatsThisMode = 125,
ZOrderChange = 126, HoverEnter = 127, HoverLeave = 128, HoverMove = 129,
AccessibilityHelp = 119, AccessibilityDescription = 130, AcceptDropsChange = 152, MenubarUpdated = 153,
ZeroTimerEvent = 154, GraphicsSceneMouseMove = 155, GraphicsSceneMousePress = 156, GraphicsSceneMouseRelease = 157,
GraphicsSceneMouseDoubleClick = 158, GraphicsSceneContextMenu = 159, GraphicsSceneHoverEnter = 160, GraphicsSceneHoverMove = 161,
GraphicsSceneHoverLeave = 162, GraphicsSceneHelp = 163, GraphicsSceneDragEnter = 164, GraphicsSceneDragMove = 165,
GraphicsSceneDragLeave = 166, GraphicsSceneDrop = 167, GraphicsSceneWheel = 168, KeyboardLayoutChange = 169,
DynamicPropertyChange = 170, TabletEnterProximity = 171, TabletLeaveProximity = 172, NonClientAreaMouseMove = 173,
NonClientAreaMouseButtonPress = 174, NonClientAreaMouseButtonRelease = 175, NonClientAreaMouseButtonDblClick = 176, MacSizeChange = 177,
ContentsRectChange = 178, MacGLWindowChange = 179, FutureCallOut = 180, GraphicsSceneResize = 181,
GraphicsSceneMove = 182, CursorChange = 183, ToolTipChange = 184, NetworkReplyUpdated = 185,
GrabMouse = 186, UngrabMouse = 187, GrabKeyboard = 188, UngrabKeyboard = 189,
MacGLClearDrawable = 191, StateMachineSignal = 192, StateMachineWrapped = 193, TouchBegin = 194,
TouchUpdate = 195, TouchEnd = 196, NativeGesture = 197, RequestSoftwareInputPanel = 199,
CloseSoftwareInputPanel = 200, UpdateSoftKeys = 201, WinIdChange = 203, Gesture = 198,
GestureOverride = 202, PlatformPanel = 212, User = 1000, MaxUser = 65535
}
This enum type defines the valid event types in Qt.
Static Public Functions inherited from QEvent
static int registerEventType (int hint=-1)
Registers and returns a custom event type.
Protected Functions inherited from QGraphicsSceneEvent
QGraphicsSceneEvent (QGraphicsSceneEventPrivate &dd, Type type=None)
Constructs a generic graphics scene event.
Protected Variables inherited from QGraphicsSceneEvent
QScopedPointer< QGraphicsSceneEventPrivate > d_ptr
Protected Variables inherited from QEvent
QEventPrivate * d
ushort t
Detailed Description
The QGraphicsSceneMoveEvent class provides events for widget moving in the graphics view framework.
Since
4.4
A QGraphicsWidget sends itself a QGraphicsSceneMoveEvent immediately when its local position changes. The delivery is implemented as part of QGraphicsItem::itemChange().
It's similar to QMoveEvent, but its positions, oldPos() and newPos(), use QPointF instead of QPoint.
See also
QGraphicsItem::setPos(), QGraphicsItem::ItemPositionChange, QGraphicsItem::ItemPositionHasChanged
Definition at line 305 of file qgraphicssceneevent.h.
Constructors and Destructors
QGraphicsSceneMoveEvent()
QGraphicsSceneMoveEvent::QGraphicsSceneMoveEvent ()
Constructs a QGraphicsSceneMoveEvent.
Definition at line 1747 of file qgraphicssceneevent.cpp.
     : QGraphicsSceneEvent(*new QGraphicsSceneMoveEventPrivate, QEvent::GraphicsSceneMove)
 {
 }
~QGraphicsSceneMoveEvent()
QGraphicsSceneMoveEvent::~QGraphicsSceneMoveEvent ()
Destroys the QGraphicsSceneMoveEvent.
Definition at line 1755 of file qgraphicssceneevent.cpp.
 {
 }
Functions
newPos()
QPointF QGraphicsSceneMoveEvent::newPos () const
Returns the new position (i.e., the current position).
See also
oldPos(), QGraphicsItem::setPos()
Definition at line 1785 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent().
 {
     Q_D(const QGraphicsSceneMoveEvent);
     return d->newPos;
 }
oldPos()
QPointF QGraphicsSceneMoveEvent::oldPos () const
Returns the old position (i.e., the position immediately before the widget was moved).
See also
newPos(), QGraphicsItem::setPos()
Definition at line 1765 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent().
 {
     Q_D(const QGraphicsSceneMoveEvent);
     return d->oldPos;
 }
setNewPos()
void QGraphicsSceneMoveEvent::setNewPos (const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 1794 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent().
 {
     Q_D(QGraphicsSceneMoveEvent);
     d->newPos = pos;
 }
setOldPos()
void QGraphicsSceneMoveEvent::setOldPos (const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 1774 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent().
 {
     Q_D(QGraphicsSceneMoveEvent);
     d->oldPos = pos;
 }
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicssceneevent.h
/src/gui/graphicsview/qgraphicssceneevent.cpp