Qt 4.8: ShaderEffectSource Class Reference
ShaderEffectSource Class Reference
The ShaderEffectSource object encapsulates the source content for the ShaderEffectItem.
#include <shadereffectsource.h>
Public Types
enum Format { Alpha = GL_ALPHA, RGB = GL_RGB, RGBA = GL_RGBA }
enum WrapMode { ClampToEdge, RepeatHorizontally, RepeatVertically, Repeat }
Public Types inherited from QDeclarativeItem
enum TransformOrigin {
TopLeft, Top, TopRight, Left,
Center, Right, BottomLeft, Bottom,
BottomRight
}
Controls the point about which simple transforms like scale apply.
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Public Slots
void markSceneGraphDirty ()
void markSourceItemDirty ()
void markSourceSizeDirty ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void activeChanged ()
void formatChanged ()
void hideSourceChanged ()
void liveChanged ()
void repaintRequired ()
void sourceItemChanged ()
void sourceRectChanged ()
void textureSizeChanged ()
void wrapModeChanged ()
Signals inherited from QDeclarativeItem
void activeFocusChanged (bool)
void baselineOffsetChanged (qreal)
void childrenRectChanged (const QRectF &)
void clipChanged (bool)
void focusChanged (bool)
void implicitHeightChanged ()
void implicitWidthChanged ()
void parentChanged (QDeclarativeItem *)
void smoothChanged (bool)
void stateChanged (const QString &)
void transformOriginChanged (TransformOrigin)
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void bind ()
void derefFromEffectItem ()
ShaderEffectBuffer * fbo ()
Q_INVOKABLE void grab ()
Repaints the source item content into the texture.
bool hideSource () const
bool isActive () const
bool isDirtyTexture ()
bool isLive () const
bool isMirrored ()
void refFromEffectItem ()
void setHideSource (bool hide)
void setLive (bool s)
void setSourceItem (QDeclarativeItem *item)
void setSourceRect (const QRectF &rect)
void setTextureSize (const QSize &size)
void setWrapMode (WrapMode mode)
ShaderEffectSource (QDeclarativeItem *parent=0)
QDeclarativeItem * sourceItem () const
QRectF sourceRect () const
QSize textureSize () const
void updateBackbuffer ()
WrapMode wrapMode () const
virtual ~ShaderEffectSource ()
Public Functions inherited from QDeclarativeItem
qreal baselineOffset () const
QRectF boundingRect () const
Q_INVOKABLE QDeclarativeItem * childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
QRectF childrenRect ()
bool clip () const
Q_INVOKABLE void forceActiveFocus ()
Forces active focus on the item.
bool hasActiveFocus () const
bool hasFocus () const
qreal height () const
qreal implicitHeight () const
qreal implicitWidth () const
bool keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
Q_INVOKABLE QScriptValue mapFromItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
Q_INVOKABLE QScriptValue mapToItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
virtual void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
QDeclarativeItem * parentItem () const
Returns the QDeclarativeItem parent of this item.
QDeclarativeItem (QDeclarativeItem *parent=0)
Constructs a QDeclarativeItem with the given parent.
void resetHeight ()
void resetWidth ()
void setBaselineOffset (qreal)
void setClip (bool)
void setFocus (bool)
void setHeight (qreal)
void setKeepMouseGrab (bool)
The flag indicating whether the mouse should remain with this item is set to keep.
void setParentItem (QDeclarativeItem *parent)
void setSize (const QSizeF &size)
void setSmooth (bool)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
void setTransformOrigin (TransformOrigin)
Set the transform origin.
void setWidth (qreal)
bool smooth () const
QDeclarativeListProperty< QGraphicsTransform > transform ()
TransformOrigin transformOrigin () const
qreal width () const
virtual ~QDeclarativeItem ()
Destroys the QDeclarativeItem.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Private Functions
void attachSourceItem ()
void detachSourceItem ()
void updateSizeAndTexture ()
Properties
bool hideSource
This property holds the flag to define whether the original source item is hidden when the effect item is drawn.
bool live
This property holds the optimization flag to define whether the source item content is changing or static.
bool m_checkedForMultisamplingSupport: 1
bool m_dirtySceneGraph: 1
bool m_dirtyTexture: 1
ShaderEffectBuffer * m_fbo
Format m_format
bool m_hideSource: 1
bool m_live: 1
bool m_mirrored: 1
ShaderEffectBuffer * m_multisampledFbo
bool m_multisamplingSupported: 1
int m_refs
QSize m_size
QPointer< QDeclarativeItem > m_sourceItem
QRectF m_sourceRect
QSize m_textureSize
WrapMode m_wrapMode
QDeclarativeItem * sourceItem
This property holds the Item which is used as the source for the shader effect.
QRectF sourceRect
This property can be used to specify margins for the source content.
QSize textureSize
This property holds the size for the texture containing the source content.
WrapMode wrapMode
This property defines the wrap parameter for the source after it has been mapped as a texture.
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Functions inherited from QDeclarativeItem
virtual void classBegin ()
virtual void componentComplete ()
virtual bool event (QEvent *)
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
bool heightValid () const
Returns whether the height property has been set explicitly.
virtual void inputMethodEvent (QInputMethodEvent *)
void inputMethodPreHandler (QInputMethodEvent *)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
bool isComponentComplete () const
Returns true if construction of the QML component is complete; otherwise returns false.
virtual QVariant itemChange (GraphicsItemChange, const QVariant &)
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
virtual void keyPressEvent (QKeyEvent *event)
void keyPressPreHandler (QKeyEvent *)
virtual void keyReleaseEvent (QKeyEvent *event)
void keyReleasePreHandler (QKeyEvent *)
QDeclarativeItem (QDeclarativeItemPrivate &dd, QDeclarativeItem *parent=0)
virtual bool sceneEvent (QEvent *)
void setImplicitHeight (qreal)
Sets the implied height of the item to h.
void setImplicitWidth (qreal)
Sets the implied width of the item to w.
bool widthValid () const
Returns whether the width property has been set explicitly.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
Filters events for the item watched.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
The ShaderEffectSource object encapsulates the source content for the ShaderEffectItem.
ShaderEffectSource is available in the Qt.labs.shaders 1.0 module. {Elements in the Qt.labs module are not guaranteed to remain compatible in future versions.}
This element provides preliminary support for OpenGL shaders in QML, and may be heavily changed or removed in later versions.
Requirement for the ability to use of shaders is that the application is either using opengl graphicssystem or has set QGLWidget as the viewport to QDeclarativeView (recommended way).
ShaderEffectSource object encapsulates the source content so that it can be utilized in ShaderEffectItem. Source content can be a live QML object tree, or a snapshot of QML object tree.
Definition at line 54 of file shadereffectsource.h.
Enumerations
Format
enum ShaderEffectSource::Format
Enumerator
Alpha
RGB
RGBA
Definition at line 74 of file shadereffectsource.h.
                 {
         Alpha = GL_ALPHA,
         RGB = GL_RGB,
         RGBA = GL_RGBA
     };
WrapMode
enum ShaderEffectSource::WrapMode
Enumerator
ClampToEdge
RepeatHorizontally
RepeatVertically
Repeat
Definition at line 67 of file shadereffectsource.h.
                   {
             ClampToEdge,
             RepeatHorizontally,
             RepeatVertically,
             Repeat
         };
Constructors and Destructors
ShaderEffectSource()
ShaderEffectSource::ShaderEffectSource (QDeclarativeItem * parent = 0)
Definition at line 72 of file shadereffectsource.cpp.
     : QDeclarativeItem(parent)
     , m_sourceItem(0)
     , m_wrapMode(ClampToEdge)
     , m_sourceRect(0, 0, 0, 0)
     , m_textureSize(0, 0)
     , m_format(RGBA)
     , m_size(0, 0)
     , m_fbo(0)
     , m_multisampledFbo(0)
     , m_refs(0)
     , m_dirtyTexture(true)
     , m_dirtySceneGraph(true)
     , m_multisamplingSupported(false)
     , m_checkedForMultisamplingSupport(false)
     , m_live(true)
     , m_hideSource(false)
     , m_mirrored(false)
 {
 }
~ShaderEffectSource()
ShaderEffectSource::~ShaderEffectSource () virtual
Definition at line 93 of file shadereffectsource.cpp.
 {
     if (m_refs && m_sourceItem)
         detachSourceItem();
     delete m_fbo;
     delete m_multisampledFbo;
 }
Functions
activeChanged
void ShaderEffectSource::activeChanged () signal
Referenced by derefFromEffectItem(), isMirrored(), and refFromEffectItem().
attachSourceItem()
void ShaderEffectSource::attachSourceItem () private
Definition at line 437 of file shadereffectsource.cpp.
Referenced by isMirrored(), refFromEffectItem(), and setSourceItem().
 {
     if (!m_sourceItem)
         return;
     ShaderEffect *effect = qobject_cast<ShaderEffect*> (m_sourceItem->graphicsEffect());
     if (!effect) {
         effect = new ShaderEffect();
         m_sourceItem->setGraphicsEffect(effect);
     }
     if (effect)
         effect->addRenderTarget(this);
     m_sourceItem->update();
 }
bind()
void ShaderEffectSource::bind ()
Definition at line 303 of file shadereffectsource.cpp.
Referenced by isActive(), and ShaderEffectItem::updateEffectState().
 {
     GLint filtering = smooth() ? GL_LINEAR : GL_NEAREST;
     GLuint hwrap = (m_wrapMode == Repeat || m_wrapMode == RepeatHorizontally) ? GL_REPEAT : GL_CLAMP_TO_EDGE;
     GLuint vwrap = (m_wrapMode == Repeat || m_wrapMode == RepeatVertically) ? GL_REPEAT : GL_CLAMP_TO_EDGE;
 #if !defined(QT_OPENGL_ES_2)
     glEnable(GL_TEXTURE_2D);
 #endif
     if (m_fbo && m_fbo->isValid()) {
         glBindTexture(GL_TEXTURE_2D, m_fbo->texture());
     } else {
         m_dirtyTexture = true;
         emit repaintRequired();
         markSourceItemDirty();
         glBindTexture(GL_TEXTURE_2D, 0);
     }
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, filtering);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, smooth() ? GL_LINEAR : GL_NEAREST);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, hwrap);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, vwrap);
 }
derefFromEffectItem()
void ShaderEffectSource::derefFromEffectItem ()
Definition at line 336 of file shadereffectsource.cpp.
Referenced by isActive(), ShaderEffectItem::reset(), and ShaderEffectItem::setActive().
 {
     if (--m_refs == 0) {
         detachSourceItem();
         emit activeChanged();
     }
     Q_ASSERT(m_refs >= 0);
 }
detachSourceItem()
void ShaderEffectSource::detachSourceItem () private
Definition at line 455 of file shadereffectsource.cpp.
Referenced by derefFromEffectItem(), isMirrored(), setSourceItem(), and ~ShaderEffectSource().
 {
     if (!m_sourceItem)
         return;
     ShaderEffect* effect = qobject_cast<ShaderEffect*> (m_sourceItem->graphicsEffect());
     if (effect)
         effect->removeRenderTarget(this);
     delete m_fbo;
     m_fbo = 0;
     delete m_multisampledFbo;
     m_multisampledFbo = 0;
     m_dirtyTexture = true;
 }
fbo()
ShaderEffectBuffer* ShaderEffectSource::fbo () inline
Definition at line 107 of file shadereffectsource.h.
 { return m_fbo; }
formatChanged
void ShaderEffectSource::formatChanged () signal
Referenced by isMirrored().
grab()
void ShaderEffectSource::grab ()
Repaints the source item content into the texture.
This method is useful when ShaderEffectSource::live has been set to false and the changes in the source item content is desired to be made visible for the shaders.
Definition at line 297 of file shadereffectsource.cpp.
Referenced by isMirrored().
 {
     m_dirtyTexture = true;
     emit repaintRequired();
 }
hideSource()
bool ShaderEffectSource::hideSource () const inline
Definition at line 95 of file shadereffectsource.h.
 { return m_hideSource; }
hideSourceChanged
void ShaderEffectSource::hideSourceChanged () signal
Referenced by isMirrored(), and setHideSource().
isActive()
bool ShaderEffectSource::isActive () const inline
Definition at line 101 of file shadereffectsource.h.
 { return m_refs; }
isDirtyTexture()
bool ShaderEffectSource::isDirtyTexture () inline
Definition at line 108 of file shadereffectsource.h.
 { return m_dirtyTexture; }
isLive()
bool ShaderEffectSource::isLive () const inline
Definition at line 92 of file shadereffectsource.h.
 { return m_live; }
isMirrored()
bool ShaderEffectSource::isMirrored () inline
Definition at line 109 of file shadereffectsource.h.
 { return m_mirrored; }
liveChanged
void ShaderEffectSource::liveChanged () signal
Referenced by isMirrored(), and setLive().
markSceneGraphDirty
void ShaderEffectSource::markSceneGraphDirty () slot
Definition at line 375 of file shadereffectsource.cpp.
Referenced by isMirrored().
 {
     m_dirtySceneGraph = true;
     emit repaintRequired();
 }
markSourceItemDirty
void ShaderEffectSource::markSourceItemDirty () slot
Definition at line 390 of file shadereffectsource.cpp.
Referenced by bind(), isMirrored(), setSourceRect(), setTextureSize(), and setWrapMode().
 {
     m_dirtyTexture = true;
     if (m_sourceItem) {
         ShaderEffect* effect = qobject_cast<ShaderEffect*> (m_sourceItem->graphicsEffect());
         if (effect)
             effect->m_changed = true;
     }
 }
markSourceSizeDirty
void ShaderEffectSource::markSourceSizeDirty () slot
Definition at line 381 of file shadereffectsource.cpp.
Referenced by isMirrored(), and setSourceItem().
 {
     Q_ASSERT(m_sourceItem);
     if (m_textureSize.isEmpty())
         updateSizeAndTexture();
     if (m_refs)
         emit repaintRequired();
 }
refFromEffectItem()
void ShaderEffectSource::refFromEffectItem ()
Definition at line 328 of file shadereffectsource.cpp.
Referenced by isActive(), and ShaderEffectItem::setActive().
 {
     if (m_refs++ == 0) {
         attachSourceItem();
         emit activeChanged();
     }
 }
repaintRequired
void ShaderEffectSource::repaintRequired () signal
Referenced by bind(), grab(), isMirrored(), markSceneGraphDirty(), markSourceSizeDirty(), setHideSource(), setLive(), setSourceItem(), setSourceRect(), and setTextureSize().
setHideSource()
void ShaderEffectSource::setHideSource (bool hide)
Definition at line 245 of file shadereffectsource.cpp.
Referenced by hideSource().
 {
     if (hide == m_hideSource)
         return;
     m_hideSource = hide;
     emit hideSourceChanged();
     emit repaintRequired();
 }
setLive()
void ShaderEffectSource::setLive (bool s)
Definition at line 223 of file shadereffectsource.cpp.
Referenced by isLive().
 {
     if (s == m_live)
         return;
     m_live = s;
     emit liveChanged();
     emit repaintRequired();
 }
setSourceItem()
void ShaderEffectSource::setSourceItem (QDeclarativeItem * item)
Definition at line 114 of file shadereffectsource.cpp.
Referenced by sourceItem().
 {
     if (item == m_sourceItem)
         return;
     if (m_sourceItem) {
         disconnect(m_sourceItem, SIGNAL(widthChanged()), this, SLOT(markSourceSizeDirty()));
         disconnect(m_sourceItem, SIGNAL(heightChanged()), this, SLOT(markSourceSizeDirty()));
         if (m_refs)
             detachSourceItem();
     }
     m_sourceItem = item;
     if (m_sourceItem) {
         // Must have some item as parent
         if (m_sourceItem->parentItem() == 0)
             m_sourceItem->setParentItem(this);
         if (m_refs)
             attachSourceItem();
         connect(m_sourceItem, SIGNAL(widthChanged()), this, SLOT(markSourceSizeDirty()));
         connect(m_sourceItem, SIGNAL(heightChanged()), this, SLOT(markSourceSizeDirty()));
     }
     updateSizeAndTexture();
     emit sourceItemChanged();
     emit repaintRequired();
 }
setSourceRect()
void ShaderEffectSource::setSourceRect (const QRectF & rect)
Definition at line 166 of file shadereffectsource.cpp.
Referenced by sourceRect().
 {
     if (rect == m_sourceRect)
         return;
     m_sourceRect = rect;
     updateSizeAndTexture();
     emit sourceRectChanged();
     emit repaintRequired();
     m_dirtyTexture = true;
     markSourceItemDirty();
 }
setTextureSize()
void ShaderEffectSource::setTextureSize (const QSize & size)
Definition at line 193 of file shadereffectsource.cpp.
Referenced by textureSize().
 {
     if (size == m_textureSize)
         return;
     m_textureSize = size;
     updateSizeAndTexture();
     emit textureSizeChanged();
     emit repaintRequired();
     m_dirtyTexture = true;
     markSourceItemDirty();
 }
setWrapMode()
void ShaderEffectSource::setWrapMode (WrapMode mode)
Definition at line 272 of file shadereffectsource.cpp.
Referenced by wrapMode().
 {
     if (mode == m_wrapMode)
         return;
     m_wrapMode = mode;
     emit wrapModeChanged();
     m_dirtyTexture = true;
     markSourceItemDirty();
 }
sourceItem()
QDeclarativeItem* ShaderEffectSource::sourceItem () const inline
Definition at line 83 of file shadereffectsource.h.
 { return m_sourceItem.data(); }
sourceItemChanged
void ShaderEffectSource::sourceItemChanged () signal
Referenced by isMirrored(), and setSourceItem().
sourceRect()
QRectF ShaderEffectSource::sourceRect () const inline
Definition at line 86 of file shadereffectsource.h.
 { return m_sourceRect; };
sourceRectChanged
void ShaderEffectSource::sourceRectChanged () signal
Referenced by isMirrored(), and setSourceRect().
textureSize()
QSize ShaderEffectSource::textureSize () const inline
Definition at line 89 of file shadereffectsource.h.
 { return m_textureSize; }
textureSizeChanged
void ShaderEffectSource::textureSizeChanged () signal
Referenced by isMirrored(), and setTextureSize().
updateBackbuffer()
void ShaderEffectSource::updateBackbuffer ()
Definition at line 345 of file shadereffectsource.cpp.
Referenced by isActive(), and ShaderEffectItem::preprocess().
 {
     if (!m_sourceItem || !QGLContext::currentContext())
         return;
     // Multisampling is not (for now) supported.
     QSize size = QSize(m_sourceItem->width(), m_sourceItem->height());
     if (!m_textureSize.isEmpty())
         size = m_textureSize;
     if (size.height() > 0 && size.width() > 0) {
         QGLFramebufferObjectFormat format;
         format.setAttachment(QGLFramebufferObject::CombinedDepthStencil);
         format.setInternalTextureFormat(m_format);
         if (!m_fbo) {
             m_fbo =  new ShaderEffectBuffer(size, format);
         } else {
             if (!m_fbo->isValid() || m_fbo->size() != size || m_fbo->format().internalTextureFormat() != GLenum(m_format)) {
                 delete m_fbo;
                 m_fbo = 0;
                 m_fbo =  new ShaderEffectBuffer(size, format);
             }
         }
     }
     // Note that real update for the source content happens in shadereffect.cpp
     m_dirtyTexture = false;
 }
updateSizeAndTexture()
void ShaderEffectSource::updateSizeAndTexture () private
Definition at line 400 of file shadereffectsource.cpp.
Referenced by isMirrored(), markSourceSizeDirty(), setSourceItem(), setSourceRect(), and setTextureSize().
 {
     if (m_sourceItem) {
         QSize size = m_textureSize;
         if (size.isEmpty())
             size = QSize(m_sourceItem->width(), m_sourceItem->height());
         if (size.width() < 1)
             size.setWidth(1);
         if (size.height() < 1)
             size.setHeight(1);
         if (m_fbo && (m_fbo->size() != size || !m_fbo->isValid())) {
             delete m_fbo;
             m_fbo = 0;
             delete m_multisampledFbo;
             m_fbo = m_multisampledFbo = 0;
         }
         if (m_size.width() != size.width()) {
             m_size.setWidth(size.width());
             emit widthChanged();
         }
         if (m_size.height() != size.height()) {
             m_size.setHeight(size.height());
             emit heightChanged();
         }
         m_dirtyTexture = true;
     } else {
         if (m_size.width() != 0) {
             m_size.setWidth(0);
             emit widthChanged();
         }
         if (m_size.height() != 0) {
             m_size.setHeight(0);
             emit heightChanged();
         }
     }
 }
wrapMode()
WrapMode ShaderEffectSource::wrapMode () const inline
Definition at line 98 of file shadereffectsource.h.
 { return m_wrapMode; };
wrapModeChanged
void ShaderEffectSource::wrapModeChanged () signal
Referenced by isMirrored(), and setWrapMode().
Properties
hideSource
bool ShaderEffectSource::hideSource private
This property holds the flag to define whether the original source item is hidden when the effect item is drawn.
The default value is false.
Definition at line 61 of file shadereffectsource.h.
live
bool ShaderEffectSource::live private
This property holds the optimization flag to define whether the source item content is changing or static.
If value true is assigned to this property, source item content is re-rendered into a texture for every frame. Setting the value to false improves the performance as it skips rendering the source item (and its chidleren) and instead immediately passes the previously rendered and cached texture to the shaders.
The default value is true.
Definition at line 60 of file shadereffectsource.h.
m_checkedForMultisamplingSupport
bool ShaderEffectSource::m_checkedForMultisamplingSupport private
Definition at line 148 of file shadereffectsource.h.
m_dirtySceneGraph
bool ShaderEffectSource::m_dirtySceneGraph private
Definition at line 146 of file shadereffectsource.h.
Referenced by markSceneGraphDirty().
m_dirtyTexture
bool ShaderEffectSource::m_dirtyTexture private
Definition at line 145 of file shadereffectsource.h.
Referenced by bind(), detachSourceItem(), grab(), isDirtyTexture(), markSourceItemDirty(), setSourceRect(), setTextureSize(), setWrapMode(), updateBackbuffer(), and updateSizeAndTexture().
m_fbo
ShaderEffectBuffer* ShaderEffectSource::m_fbo private
Definition at line 142 of file shadereffectsource.h.
Referenced by bind(), detachSourceItem(), fbo(), updateBackbuffer(), updateSizeAndTexture(), and ~ShaderEffectSource().
m_format
Format ShaderEffectSource::m_format private
Definition at line 139 of file shadereffectsource.h.
Referenced by updateBackbuffer().
m_hideSource
bool ShaderEffectSource::m_hideSource private
Definition at line 150 of file shadereffectsource.h.
Referenced by hideSource(), and setHideSource().
m_live
bool ShaderEffectSource::m_live private
Definition at line 149 of file shadereffectsource.h.
Referenced by isLive(), and setLive().
m_mirrored
bool ShaderEffectSource::m_mirrored private
Definition at line 151 of file shadereffectsource.h.
Referenced by isMirrored().
m_multisampledFbo
ShaderEffectBuffer* ShaderEffectSource::m_multisampledFbo private
Definition at line 143 of file shadereffectsource.h.
Referenced by detachSourceItem(), updateSizeAndTexture(), and ~ShaderEffectSource().
m_multisamplingSupported
bool ShaderEffectSource::m_multisamplingSupported private
Definition at line 147 of file shadereffectsource.h.
m_refs
int ShaderEffectSource::m_refs private
Definition at line 144 of file shadereffectsource.h.
Referenced by derefFromEffectItem(), isActive(), markSourceSizeDirty(), refFromEffectItem(), setSourceItem(), and ~ShaderEffectSource().
m_size
QSize ShaderEffectSource::m_size private
Definition at line 140 of file shadereffectsource.h.
Referenced by updateSizeAndTexture().
m_sourceItem
QPointer<QDeclarativeItem> ShaderEffectSource::m_sourceItem private
Definition at line 135 of file shadereffectsource.h.
Referenced by attachSourceItem(), detachSourceItem(), markSourceItemDirty(), markSourceSizeDirty(), setSourceItem(), sourceItem(), updateBackbuffer(), updateSizeAndTexture(), and ~ShaderEffectSource().
m_sourceRect
QRectF ShaderEffectSource::m_sourceRect private
Definition at line 137 of file shadereffectsource.h.
Referenced by setSourceRect(), and sourceRect().
m_textureSize
QSize ShaderEffectSource::m_textureSize private
Definition at line 138 of file shadereffectsource.h.
Referenced by markSourceSizeDirty(), setTextureSize(), textureSize(), updateBackbuffer(), and updateSizeAndTexture().
m_wrapMode
WrapMode ShaderEffectSource::m_wrapMode private
Definition at line 136 of file shadereffectsource.h.
Referenced by bind(), setWrapMode(), and wrapMode().
sourceItem
Item ShaderEffectSource::sourceItem private
This property holds the Item which is used as the source for the shader effect.
If the item has children, those are included as well.
Note
When source item content is passed to the ShaderEffectItem(s), it is always clipped to the boundingrect of the sourceItem regardless of its clipping property.
Definition at line 57 of file shadereffectsource.h.
sourceRect
QRectF ShaderEffectSource::sourceRect private
This property can be used to specify margins for the source content.
If other value than Qt.rect(0,0,0,0) is assigned to this property, it is interpreted as specifying a relative source rectangle for the source content.
For example, setting Qt.rect(-10.0, -10.0, 120.0, 120.0) for a source that has width and height of 100 pixels would produce 10 pixels margins to each side of the source.
Margins are useful when the original content is wanted to be spread outside the original source area, like when creating a dropshadow with the shader or in other similar effects.
The default value is Qt.rect(0,0,0,0).
Definition at line 58 of file shadereffectsource.h.
textureSize
QSize ShaderEffectSource::textureSize private
This property holds the size for the texture containing the source content.
If value QSize(0,0) is assigned to this property, texture is resized according to the source size. Otherwise source content is scaled to the given size.
The default value is QSize(0,0).
Definition at line 59 of file shadereffectsource.h.
wrapMode
enumeration ShaderEffectSource::wrapMode private
This property defines the wrap parameter for the source after it has been mapped as a texture.
ShaderEffectSource.ClampToEdge - Causes texturecoordinates to be clamped to the range [ 1/2*N , 1 - 1/2*N ], where N is the texture width.
ShaderEffectSource.RepeatHorizontally - Causes the integer part of the horizontal texturecoordinate to be ignored; the GL uses only the fractional part, thereby creating a horizontal repeating pattern.
ShaderEffectSource.RepeatVertically - Causes the integer part of the vertical texturecoordinate to be ignored; the GL uses only the fractional part, thereby creating a vertical repeating pattern.
ShaderEffectSource.Repeat - Causes the integer part of both the horizontal and vertical texturecoordinates to be ignored; the GL uses only the fractional part, thereby creating a repeating pattern.
The default value is ClampToEdge.
Definition at line 62 of file shadereffectsource.h.
The documentation for this class was generated from the following files:
/src/imports/shaders/shadereffectsource.h
/src/imports/shaders/shadereffectsource.cpp