Qt 4.8: QTextFormat Class Reference
QTextFormat Class Reference
The QTextFormat class provides formatting information for a QTextDocument.
#include <qtextformat.h>
Public Types
enum FormatType {
InvalidFormat = -1, BlockFormat = 1, CharFormat = 2, ListFormat = 3,
TableFormat = 4, FrameFormat = 5, UserFormat = 100
}
This enum describes the text item a QTextFormat object is formatting.
enum ObjectTypes {
NoObject, ImageObject, TableObject, TableCellObject,
UserObject = 0x1000
}
This enum describes what kind of QTextObject this format is associated with.
enum PageBreakFlag { PageBreak_Auto = 0, PageBreak_AlwaysBefore = 0x001, PageBreak_AlwaysAfter = 0x010 }
This enum describes how page breaking is performed when printing.
enum Property {
ObjectIndex = 0x0, CssFloat = 0x0800, LayoutDirection = 0x0801, OutlinePen = 0x810,
BackgroundBrush = 0x820, ForegroundBrush = 0x821, BackgroundImageUrl = 0x823, BlockAlignment = 0x1010,
BlockTopMargin = 0x1030, BlockBottomMargin = 0x1031, BlockLeftMargin = 0x1032, BlockRightMargin = 0x1033,
TextIndent = 0x1034, TabPositions = 0x1035, BlockIndent = 0x1040, LineHeight = 0x1048,
LineHeightType = 0x1049, BlockNonBreakableLines = 0x1050, BlockTrailingHorizontalRulerWidth = 0x1060, FirstFontProperty = 0x1FE0,
FontCapitalization = FirstFontProperty, FontLetterSpacing = 0x1FE1, FontWordSpacing = 0x1FE2, FontStyleHint = 0x1FE3,
FontStyleStrategy = 0x1FE4, FontKerning = 0x1FE5, FontHintingPreference = 0x1FE6, FontFamily = 0x2000,
FontPointSize = 0x2001, FontSizeAdjustment = 0x2002, FontSizeIncrement = FontSizeAdjustment, FontWeight = 0x2003,
FontItalic = 0x2004, FontUnderline = 0x2005, FontOverline = 0x2006, FontStrikeOut = 0x2007,
FontFixedPitch = 0x2008, FontPixelSize = 0x2009, LastFontProperty = FontPixelSize, TextUnderlineColor = 0x2010,
TextVerticalAlignment = 0x2021, TextOutline = 0x2022, TextUnderlineStyle = 0x2023, TextToolTip = 0x2024,
IsAnchor = 0x2030, AnchorHref = 0x2031, AnchorName = 0x2032, ObjectType = 0x2f00,
ListStyle = 0x3000, ListIndent = 0x3001, ListNumberPrefix = 0x3002, ListNumberSuffix = 0x3003,
FrameBorder = 0x4000, FrameMargin = 0x4001, FramePadding = 0x4002, FrameWidth = 0x4003,
FrameHeight = 0x4004, FrameTopMargin = 0x4005, FrameBottomMargin = 0x4006, FrameLeftMargin = 0x4007,
FrameRightMargin = 0x4008, FrameBorderBrush = 0x4009, FrameBorderStyle = 0x4010, TableColumns = 0x4100,
TableColumnWidthConstraints = 0x4101, TableCellSpacing = 0x4102, TableCellPadding = 0x4103, TableHeaderRowCount = 0x4104,
TableCellRowSpan = 0x4810, TableCellColumnSpan = 0x4811, TableCellTopPadding = 0x4812, TableCellBottomPadding = 0x4813,
TableCellLeftPadding = 0x4814, TableCellRightPadding = 0x4815, ImageName = 0x5000, ImageWidth = 0x5010,
ImageHeight = 0x5011, FullWidthSelection = 0x06000, PageBreakPolicy = 0x7000, UserProperty = 0x100000
}
This enum describes the different properties a format can have.
Public Functions
QBrush background () const
Returns the brush used to paint the document's background.
bool boolProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush brushProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Brush type, Qt::NoBrush is returned instead.
void clearBackground ()
Clears the brush used to paint the document's background.
void clearForeground ()
Clears the brush used to paint the document's foreground.
void clearProperty (int propertyId)
Clears the value of the property given by propertyId.
QColor colorProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Color type, an invalid color is returned instead.
qreal doubleProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush foreground () const
Returns the brush used to render foreground details, such as text, frame outlines, and table borders.
bool hasProperty (int propertyId) const
Returns true if the text format has a property with the given propertyId; otherwise returns false.
int intProperty (int propertyId) const
Returns the value of the property specified by propertyId.
bool isBlockFormat () const
Returns true if this text format is a BlockFormat; otherwise returns false.
bool isCharFormat () const
Returns true if this text format is a CharFormat; otherwise returns false.
bool isFrameFormat () const
Returns true if this text format is a FrameFormat; otherwise returns false.
bool isImageFormat () const
Returns true if this text format is an image format; otherwise returns false.
bool isListFormat () const
Returns true if this text format is a ListFormat; otherwise returns false.
bool isTableCellFormat () const
Returns true if this text format is a TableCellFormat; otherwise returns false.
bool isTableFormat () const
Returns true if this text format is a TableFormat; otherwise returns false.
bool isValid () const
Returns true if the format is valid (i.
Qt::LayoutDirection layoutDirection () const
Returns the document's layout direction.
QTextLength lengthProperty (int propertyId) const
Returns the value of the property given by propertyId.
QVector< QTextLength > lengthVectorProperty (int propertyId) const
Returns the value of the property given by propertyId.
void merge (const QTextFormat &other)
Merges the other format with this format; where there are conflicts the other format takes precedence.
int objectIndex () const
Returns the index of the format object, or -1 if the format object is invalid.
int objectType () const
Returns the text format's object type.
operator QVariant () const
Returns the text format as a QVariant.
bool operator!= (const QTextFormat &rhs) const
Returns true if this text format is different from the other text format.
QTextFormat & operator= (const QTextFormat &rhs)
Assigns the other text format to this text format, and returns a reference to this text format.
bool operator== (const QTextFormat &rhs) const
Returns true if this text format is the same as the other text format.
QPen penProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Pen type, Qt::NoPen is returned instead.
QMap< int, QVariant > properties () const
Returns a map with all properties of this text format.
QVariant property (int propertyId) const
Returns the property specified by the given propertyId.
int propertyCount () const
Returns the number of properties stored in the format.
QTextFormat ()
Creates a new text format with an InvalidFormat.
QTextFormat (int type)
Creates a new text format of the given type.
QTextFormat (const QTextFormat &rhs)
Creates a new text format with the same attributes as the other text format.
void setBackground (const QBrush &brush)
Sets the brush use to paint the document's background to the brush specified.
void setForeground (const QBrush &brush)
Sets the foreground brush to the specified brush.
void setLayoutDirection (Qt::LayoutDirection direction)
Sets the document's layout direction to the specified direction.
void setObjectIndex (int object)
Sets the format object's object index.
void setObjectType (int type)
Sets the text format's object type to type.
void setProperty (int propertyId, const QVariant &value)
Sets the property specified by the propertyId to the given value.
void setProperty (int propertyId, const QVector< QTextLength > &lengths)
Sets the value of the property given by propertyId to value.
QString stringProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::String type, an empty string is returned instead.
QTextBlockFormat toBlockFormat () const
Returns this format as a block format.
QTextCharFormat toCharFormat () const
Returns this format as a character format.
QTextFrameFormat toFrameFormat () const
Returns this format as a frame format.
QTextImageFormat toImageFormat () const
Returns this format as an image format.
QTextListFormat toListFormat () const
Returns this format as a list format.
QTextTableCellFormat toTableCellFormat () const
Returns this format as a table cell format.
QTextTableFormat toTableFormat () const
Returns this format as a table format.
int type () const
Returns the type of this format.
~QTextFormat ()
Destroys this text format.
Properties
QSharedDataPointer< QTextFormatPrivate > d
qint32 format_type
Friends
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QTextFormat &)
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QTextFormat &)
class QTextCharFormat
class QTextFormatCollection
Detailed Description
The QTextFormat class provides formatting information for a QTextDocument.
Note
This class or function is reentrant.
A QTextFormat is a generic class used for describing the format of parts of a QTextDocument. The derived classes QTextCharFormat, QTextBlockFormat, QTextListFormat, and QTextTableFormat are usually more useful, and describe the formatting that is applied to specific parts of the document.
A format has a FormatType which specifies the kinds of text item it can format; e.g. a block of text, a list, a table, etc. A format also has various properties (some specific to particular format types), as described by the Property enum. Every property has a corresponding Property.
The format type is given by type(), and the format can be tested with isCharFormat(), isBlockFormat(), isListFormat(), isTableFormat(), isFrameFormat(), and isImageFormat(). If the type is determined, it can be retrieved with toCharFormat(), toBlockFormat(), toListFormat(), toTableFormat(), toFrameFormat(), and toImageFormat().
A format's properties can be set with the setProperty() functions, and retrieved with boolProperty(), intProperty(), doubleProperty(), and stringProperty() as appropriate. All the property IDs used in the format can be retrieved with allPropertyIds(). One format can be merged into another using merge().
A format's object index can be set with setObjectIndex(), and retrieved with objectIndex(). These methods can be used to associate the format with a QTextObject. It is used to represent lists, frames, and tables inside the document.
See also
{Rich Text Processing}
Definition at line 129 of file qtextformat.h.
Enumerations
FormatType
enum QTextFormat::FormatType
This enum describes the text item a QTextFormat object is formatting.
InvalidFormat An invalid format as created by the default constructor
BlockFormat The object formats a text block
CharFormat The object formats a single character
ListFormat The object formats a list
TableFormat The object formats a table
FrameFormat The object formats a frame
UserFormat
See also
QTextCharFormat, QTextBlockFormat, QTextListFormat, QTextTableFormat, type()
Enumerator
InvalidFormat
BlockFormat
CharFormat
ListFormat
TableFormat
FrameFormat
UserFormat
Definition at line 134 of file qtextformat.h.
                     {
         InvalidFormat = -1,
         BlockFormat = 1,
         CharFormat = 2,
         ListFormat = 3,
         TableFormat = 4,
         FrameFormat = 5,
         UserFormat = 100
     };
ObjectTypes
enum QTextFormat::ObjectTypes
This enum describes what kind of QTextObject this format is associated with.
NoObject
ImageObject
TableObject
TableCellObject
UserObject The first object that can be used for application-specific purposes.
See also
QTextObject, QTextTable, QTextObject::format()
Enumerator
NoObject
ImageObject
TableObject
TableCellObject
UserObject
Definition at line 260 of file qtextformat.h.
                      {
         NoObject,
         ImageObject,
         TableObject,
         TableCellObject,
         UserObject = 0x1000
     };
PageBreakFlag
enum QTextFormat::PageBreakFlag
This enum describes how page breaking is performed when printing.
Since
4.2
It maps to the corresponding css properties.
PageBreak_Auto The page break is determined automatically depending on the available space on the current page
PageBreak_AlwaysBefore The page is always broken before the paragraph/table
PageBreak_AlwaysAfter A new page is always started after the paragraph/table
See also
QTextBlockFormat::pageBreakPolicy(), QTextFrameFormat::pageBreakPolicy(), PageBreakPolicy
Enumerator
PageBreak_Auto
PageBreak_AlwaysBefore
PageBreak_AlwaysAfter
Definition at line 269 of file qtextformat.h.
{
         PageBreak_Auto = 0,
         PageBreak_AlwaysBefore = 0x001,
         PageBreak_AlwaysAfter  = 0x010
         // PageBreak_AlwaysInside = 0x100
     };
Property
enum QTextFormat::Property
This enum describes the different properties a format can have.
ObjectIndex The index of the formatted object. See objectIndex().
Paragraph and character properties
CssFloat How a frame is located relative to the surrounding text
LayoutDirection The layout direction of the text in the document (Qt::LayoutDirection).
OutlinePen
ForegroundBrush
BackgroundBrush
BackgroundImageUrl
Paragraph properties
BlockAlignment
BlockTopMargin
BlockBottomMargin
BlockLeftMargin
BlockRightMargin
TextIndent
TabPositions Specifies the tab positions. The tab positions are structs of QTextOption::Tab which are stored in a QList (internally, in a QList<QVariant>).
BlockIndent
LineHeight
LineHeightType
BlockNonBreakableLines
BlockTrailingHorizontalRulerWidth The width of a horizontal ruler element.
Character properties
FontFamily
FontPointSize
FontPixelSize
FontSizeAdjustment Specifies the change in size given to the fontsize already set using FontPointSize or FontPixelSize.
FontFixedPitch
FontSizeIncrement
FontWeight
FontItalic
FontUnderline This property has been deprecated. Use QTextFormat::TextUnderlineStyle instead.
FontOverline
FontStrikeOut
FontCapitalization Specifies the capitalization type that is to be applied to the text.
FontLetterSpacing Changes the default spacing between individual letters in the font. The value is specified in percentage, with 100 as the default value.
FontWordSpacing Changes the default spacing between individual words. A positive value increases the word spacing by the corresponding pixels; a negative value decreases the spacing.
FontStyleHint Corresponds to the QFont::StyleHint property
FontStyleStrategy Corresponds to the QFont::StyleStrategy property
FontKerning Specifies whether the font has kerning turned on.
FontHintingPreference Controls the use of hinting according to values of the QFont::HintingPreference enum.
FirstFontProperty
LastFontProperty
TextUnderlineColor
TextVerticalAlignment
TextOutline
TextUnderlineStyle
TextToolTip Specifies the (optional) tool tip to be displayed for a fragment of text.
IsAnchor
AnchorHref
AnchorName
ObjectType
List properties
ListStyle Specifies the style used for the items in a list, described by values of the QTextListFormat::Style enum.
ListIndent Specifies the amount of indentation used for a list.
ListNumberPrefix Defines the text which is prepended to item numbers in numeric lists.
ListNumberSuffix Defines the text which is appended to item numbers in numeric lists.
Table and frame properties
FrameBorder
FrameBorderBrush
FrameBorderStyle See the BorderStyle enum.
FrameBottomMargin
FrameHeight
FrameLeftMargin
FrameMargin
FramePadding
FrameRightMargin
FrameTopMargin
FrameWidth
TableCellSpacing
TableCellPadding
TableColumns
TableColumnWidthConstraints
TableHeaderRowCount
Table cell properties
TableCellRowSpan
TableCellColumnSpan
TableCellLeftPadding
TableCellRightPadding
TableCellTopPadding
TableCellBottomPadding
Image properties
ImageName
ImageWidth
ImageHeight
Selection properties
FullWidthSelection When set on the characterFormat of a selection, the whole width of the text will be shown selected.
Page break properties
PageBreakPolicy Specifies how pages are broken. See the PageBreakFlag enum.
UserProperty
See also
property(), setProperty()
Enumerator
ObjectIndex
CssFloat
LayoutDirection
OutlinePen
BackgroundBrush
ForegroundBrush
BackgroundImageUrl
BlockAlignment
BlockTopMargin
BlockBottomMargin
BlockLeftMargin
BlockRightMargin
TextIndent
TabPositions
BlockIndent
LineHeight
LineHeightType
BlockNonBreakableLines
BlockTrailingHorizontalRulerWidth
FirstFontProperty
FontCapitalization
FontLetterSpacing
FontWordSpacing
FontStyleHint
FontStyleStrategy
FontKerning
FontHintingPreference
FontFamily
FontPointSize
FontSizeAdjustment
FontSizeIncrement
FontWeight
FontItalic
FontUnderline
FontOverline
FontStrikeOut
FontFixedPitch
FontPixelSize
LastFontProperty
TextUnderlineColor
TextVerticalAlignment
TextOutline
TextUnderlineStyle
TextToolTip
IsAnchor
AnchorHref
AnchorName
ObjectType
ListStyle
ListIndent
ListNumberPrefix
ListNumberSuffix
FrameBorder
FrameMargin
FramePadding
FrameWidth
FrameHeight
FrameTopMargin
FrameBottomMargin
FrameLeftMargin
FrameRightMargin
FrameBorderBrush
FrameBorderStyle
TableColumns
TableColumnWidthConstraints
TableCellSpacing
TableCellPadding
TableHeaderRowCount
TableCellRowSpan
TableCellColumnSpan
TableCellTopPadding
TableCellBottomPadding
TableCellLeftPadding
TableCellRightPadding
ImageName
ImageWidth
ImageHeight
FullWidthSelection
PageBreakPolicy
UserProperty
Definition at line 145 of file qtextformat.h.
                   {
         ObjectIndex = 0x0,
         // paragraph and char
         CssFloat = 0x0800,
         LayoutDirection = 0x0801,
         OutlinePen = 0x810,
         BackgroundBrush = 0x820,
         ForegroundBrush = 0x821,
         // Internal to qtextlayout.cpp: ObjectSelectionBrush = 0x822
         BackgroundImageUrl = 0x823,
         // paragraph
         BlockAlignment = 0x1010,
         BlockTopMargin = 0x1030,
         BlockBottomMargin = 0x1031,
         BlockLeftMargin = 0x1032,
         BlockRightMargin = 0x1033,
         TextIndent = 0x1034,
         TabPositions = 0x1035,
         BlockIndent = 0x1040,
         LineHeight = 0x1048,
         LineHeightType = 0x1049,
         BlockNonBreakableLines = 0x1050,
         BlockTrailingHorizontalRulerWidth = 0x1060,
         // character properties
         FirstFontProperty = 0x1FE0,
         FontCapitalization = FirstFontProperty,
         FontLetterSpacing = 0x1FE1,
         FontWordSpacing = 0x1FE2,
         FontStyleHint = 0x1FE3,
         FontStyleStrategy = 0x1FE4,
         FontKerning = 0x1FE5,
         FontHintingPreference = 0x1FE6,
         FontFamily = 0x2000,
         FontPointSize = 0x2001,
         FontSizeAdjustment = 0x2002,
         FontSizeIncrement = FontSizeAdjustment, // old name, compat
         FontWeight = 0x2003,
         FontItalic = 0x2004,
         FontUnderline = 0x2005, // deprecated, use TextUnderlineStyle instead
         FontOverline = 0x2006,
         FontStrikeOut = 0x2007,
         FontFixedPitch = 0x2008,
         FontPixelSize = 0x2009,
         LastFontProperty = FontPixelSize,
         TextUnderlineColor = 0x2010,
         TextVerticalAlignment = 0x2021,
         TextOutline = 0x2022,
         TextUnderlineStyle = 0x2023,
         TextToolTip = 0x2024,
         IsAnchor = 0x2030,
         AnchorHref = 0x2031,
         AnchorName = 0x2032,
         ObjectType = 0x2f00,
         // list properties
         ListStyle = 0x3000,
         ListIndent = 0x3001,
         ListNumberPrefix = 0x3002,
         ListNumberSuffix = 0x3003,
         // table and frame properties
         FrameBorder = 0x4000,
         FrameMargin = 0x4001,
         FramePadding = 0x4002,
         FrameWidth = 0x4003,
         FrameHeight = 0x4004,
         FrameTopMargin    = 0x4005,
         FrameBottomMargin = 0x4006,
         FrameLeftMargin   = 0x4007,
         FrameRightMargin  = 0x4008,
         FrameBorderBrush = 0x4009,
         FrameBorderStyle = 0x4010,
         TableColumns = 0x4100,
         TableColumnWidthConstraints = 0x4101,
         TableCellSpacing = 0x4102,
         TableCellPadding = 0x4103,
         TableHeaderRowCount = 0x4104,
         // table cell properties
         TableCellRowSpan = 0x4810,
         TableCellColumnSpan = 0x4811,
         TableCellTopPadding = 0x4812,
         TableCellBottomPadding = 0x4813,
         TableCellLeftPadding = 0x4814,
         TableCellRightPadding = 0x4815,
         // image properties
         ImageName = 0x5000,
         ImageWidth = 0x5010,
         ImageHeight = 0x5011,
         // internal
         /*
            SuppressText = 0x5012,
            SuppressBackground = 0x513
         */
         // selection properties
         FullWidthSelection = 0x06000,
         // page break properties
         PageBreakPolicy = 0x7000,
         // --
         UserProperty = 0x100000
     };
Constructors and Destructors
QTextFormat() [1/3]
QTextFormat::QTextFormat ()
Creates a new text format with an InvalidFormat.
See also
FormatType
Definition at line 814 of file qtextformat.cpp.
Referenced by QTextFormatCollection::format(), and QTextFormatCollection::objectFormat().
     : format_type(InvalidFormat)
 {
 }
QTextFormat() [2/3]
QTextFormat::QTextFormat (int type) explicit
Creates a new text format of the given type.
See also
FormatType
Definition at line 824 of file qtextformat.cpp.
     : format_type(type)
 {
 }
QTextFormat() [3/3]
QTextFormat::QTextFormat (const QTextFormat & rhs)
Creates a new text format with the same attributes as the other text format.
Definition at line 839 of file qtextformat.cpp.
     : d(rhs.d), format_type(rhs.format_type)
 {
 }
~QTextFormat()
QTextFormat::~QTextFormat ()
Destroys this text format.
Definition at line 863 of file qtextformat.cpp.
 {
 }
Functions
background()
QColor QTextFormat::background () const inline
Returns the brush used to paint the document's background.
See also
setBackground() clearBackground() foreground()
Definition at line 345 of file qtextformat.h.
Referenced by QAccessibleTextWidget::attributes(), QCalendarModel::data(), QTextLayout::draw(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QTextDocumentLayoutPrivate::drawListItem(), QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitBackgroundAttribute(), QTextHtmlExporter::emitBlockAttributes(), QTextHtmlExporter::emitCharFormatStyle(), QTextControlPrivate::inputMethodEvent(), QPlainTextEdit::paintEvent(), QTextHtmlImporter::processBlockNode(), QLineControl::processInputMethodEvent(), QTextHtmlImporter::processSpecialNodes(), QTextHtmlImporter::scanTable(), setPenAndDrawBackground(), QTextOdfWriter::writeBlockFormat(), and QTextOdfWriter::writeCharacterFormat().
     { return brushProperty(BackgroundBrush); }
boolProperty()
bool QTextFormat::boolProperty (int propertyId) const
Returns the value of the property specified by propertyId.
If the property isn't of QTextFormat::Bool type, false is returned instead.
See also
setProperty() intProperty() doubleProperty() stringProperty() colorProperty() lengthProperty() lengthVectorProperty() Property
Definition at line 980 of file qtextformat.cpp.
Referenced by QTextLayout::draw(), QTextCharFormat::fontFixedPitch(), QTextCharFormat::fontItalic(), QTextCharFormat::fontKerning(), QTextCharFormat::fontOverline(), QTextCharFormat::fontStrikeOut(), QTextCharFormat::fontUnderline(), QTextItemInt::initWithScriptItem(), QTextCharFormat::isAnchor(), and QTextControl::setExtraSelections().
 {
     if (!d)
         return false;
     const QVariant prop = d->property(propertyId);
     if (prop.userType() != QVariant::Bool)
         return false;
     return prop.toBool();
 }
brushProperty()
QBrush QTextFormat::brushProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Brush type, Qt::NoBrush is returned instead.
See also
setProperty() boolProperty() intProperty() doubleProperty() stringProperty() lengthProperty() lengthVectorProperty() Property
Definition at line 1085 of file qtextformat.cpp.
Referenced by QTextLayout::draw(), and QTextLine::draw().
 {
     if (!d)
         return QBrush(Qt::NoBrush);
     const QVariant prop = d->property(propertyId);
     if (prop.userType() != QVariant::Brush)
         return QBrush(Qt::NoBrush);
     return qvariant_cast<QBrush>(prop);
 }
clearBackground()
void QTextFormat::clearBackground () inline
Clears the brush used to paint the document's background.
The default brush will be used.
See also
background() setBackground() clearForeground()
Definition at line 347 of file qtextformat.h.
Referenced by QTextLine::draw().
     { clearProperty(BackgroundBrush); }
clearForeground()
void QTextFormat::clearForeground () inline
Clears the brush used to paint the document's foreground.
The default brush will be used.
See also
foreground() setForeground() clearBackground()
Definition at line 354 of file qtextformat.h.
Referenced by QTextLine::draw().
     { clearProperty(ForegroundBrush); }
clearProperty()
void QTextFormat::clearProperty (int propertyId)
Clears the value of the property given by propertyId.
See also
Property
Definition at line 1178 of file qtextformat.cpp.
Referenced by QTextHtmlImporter::appendNodeText(), QTextCursor::charFormat(), QTextLayout::draw(), QTextLine::draw(), QTextHtmlExporter::emitBlockAttributes(), formatDifference(), QTextHtmlParserNode::initializeProperties(), QTextCursor::insertBlock(), QTextCursor::insertText(), QTextHtmlExporter::QTextHtmlExporter(), QTextCursorPrivate::setBlockCharFormat(), QTextCursorPrivate::setCharFormat(), QTextDocumentPrivate::setCharFormat(), QTextTableCell::setFormat(), setProperty(), QTextCharFormat::setTableCellColumnSpan(), QTextCharFormat::setTableCellRowSpan(), and QTextHtmlExporter::toHtml().
 {
     if (!d)
         return;
     d->clearProperty(propertyId);
 }
colorProperty()
QColor QTextFormat::colorProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Color type, an invalid color is returned instead.
See also
setProperty(), boolProperty(), intProperty(), doubleProperty(), stringProperty(), lengthProperty(), lengthVectorProperty(), Property
Definition at line 1051 of file qtextformat.cpp.
Referenced by QTextCharFormat::underlineColor().
 {
     if (!d)
         return QColor();
     const QVariant prop = d->property(propertyId);
     if (prop.userType() != QVariant::Color)
         return QColor();
     return qvariant_cast<QColor>(prop);
 }
doubleProperty()
qreal QTextFormat::doubleProperty (int propertyId) const
Returns the value of the property specified by propertyId.
If the property isn't of QVariant::Double or QMetaType::Float type, 0 is returned instead.
See also
setProperty() boolProperty() intProperty() stringProperty() colorProperty() lengthProperty() lengthVectorProperty() Property
Definition at line 1016 of file qtextformat.cpp.
Referenced by QTextFrameFormat::bottomMargin(), QTextTableCellFormat::bottomPadding(), QTextCharFormat::fontLetterSpacing(), QTextCharFormat::fontPointSize(), QTextCharFormat::fontWordSpacing(), QTextFrameFormat::leftMargin(), QTextTableCellFormat::leftPadding(), QTextBlockFormat::lineHeight(), QTextFrameFormat::rightMargin(), QTextTableCellFormat::rightPadding(), QTextFrameFormat::topMargin(), and QTextTableCellFormat::topPadding().
 {
     if (!d)
         return 0.;
     const QVariant prop = d->property(propertyId);
     if (prop.userType() != QVariant::Double && prop.userType() != QMetaType::Float)
         return 0.;
     return qvariant_cast<qreal>(prop);
 }
foreground()
QBrush QTextFormat::foreground () const inline
Returns the brush used to render foreground details, such as text, frame outlines, and table borders.
See also
setForeground() clearForeground() background()
Definition at line 352 of file qtextformat.h.
Referenced by QTextEditPrivate::_q_currentCharFormatChanged(), QAccessibleTextWidget::attributes(), QCalendarModel::data(), QTextLayout::draw(), QTextLine::draw(), QTextDocumentLayoutPrivate::drawListItem(), QTextHtmlExporter::emitCharFormatStyle(), setPenAndDrawBackground(), and QTextOdfWriter::writeCharacterFormat().
     { return brushProperty(ForegroundBrush); }
hasProperty()
bool QTextFormat::hasProperty (int propertyId) const
Returns true if the text format has a property with the given propertyId; otherwise returns false.
See also
properties() Property
Definition at line 1254 of file qtextformat.cpp.
Referenced by QTextControlPrivate::anchorForCursor(), QTextHtmlImporter::appendNodeText(), QTextFrameFormat::bottomMargin(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawListItem(), QTextHtmlExporter::emitBackgroundAttribute(), QTextHtmlExporter::emitBlock(), QTextHtmlExporter::emitBlockAttributes(), QTextHtmlExporter::emitCharFormatStyle(), QTextHtmlExporter::emitFragment(), QTextHtmlExporter::emitFrameStyle(), QTextHtmlExporter::emitTable(), QTextHtmlExporter::emitTextFrame(), QTextControl::findNextPrevAnchor(), QTextCharFormat::fontUnderline(), getImageSize(), getPixmapSize(), QTextHtmlImporter::import(), QTextHtmlParserNode::initializeProperties(), QTextItemInt::initWithScriptItem(), isEmptyBlockBeforeTable(), QTextDocumentLayoutPrivate::layoutBlock(), QTextFrameFormat::leftMargin(), QPlainTextEdit::paintEvent(), QTextFrameFormat::rightMargin(), QTextHtmlImporter::scanTable(), QTextHtmlExporter::toHtml(), QTextFrameFormat::topMargin(), QTextOdfWriter::writeBlockFormat(), QTextOdfWriter::writeCharacterFormat(), QTextOdfWriter::writeFrameFormat(), QTextOdfWriter::writeInlineCharacter(), QTextOdfWriter::writeListFormat(), and QTextOdfWriter::writeTableCellFormat().
 {
     return d ? d->hasProperty(propertyId) : false;
 }
intProperty()
int QTextFormat::intProperty (int propertyId) const
Returns the value of the property specified by propertyId.
If the property is not of QTextFormat::Integer type, 0 is returned instead.
See also
setProperty() boolProperty() doubleProperty() stringProperty() colorProperty() lengthProperty() lengthVectorProperty() Property
Definition at line 996 of file qtextformat.cpp.
Referenced by QTextDocumentLayoutPrivate::drawListItem(), QTextHtmlExporter::emitCharFormatStyle(), QTextCharFormat::fontCapitalization(), QTextCharFormat::fontHintingPreference(), QTextCharFormat::fontStyleHint(), QTextCharFormat::fontStyleStrategy(), QTextCharFormat::fontWeight(), QTextBlockFormat::lineHeight(), QTextCharFormat::tableCellColumnSpan(), QTextCharFormat::tableCellRowSpan(), QTextHtmlExporter::toHtml(), QTextCharFormat::underlineStyle(), and QTextCharFormat::verticalAlignment().
 {
     // required, since the default layout direction has to be LayoutDirectionAuto, which is not integer 0
     int def = (propertyId == QTextFormat::LayoutDirection) ? int(Qt::LayoutDirectionAuto) : 0;
     if (!d)
         return def;
     const QVariant prop = d->property(propertyId);
     if (prop.userType() != QVariant::Int)
         return def;
     return prop.toInt();
 }
isBlockFormat()
bool QTextFormat::isBlockFormat () const inline
Returns true if this text format is a BlockFormat; otherwise returns false.
Definition at line 319 of file qtextformat.h.
Referenced by QTextCursorPrivate::insertBlock(), and QTextDocumentPrivate::insertBlock().
 { return type() == BlockFormat; }
isCharFormat()
bool QTextFormat::isCharFormat () const inline
Returns true if this text format is a CharFormat; otherwise returns false.
Definition at line 318 of file qtextformat.h.
Referenced by QTextDocumentPrivate::insert(), QTextDocumentPrivate::insertBlock(), QTextCursor::insertText(), and QTextCharFormat::isValid().
 { return type() == CharFormat; }
isFrameFormat()
bool QTextFormat::isFrameFormat () const inline
Returns true if this text format is a FrameFormat; otherwise returns false.
Definition at line 321 of file qtextformat.h.
Referenced by QTextDocument::createObject().
 { return type() == FrameFormat; }
isImageFormat()
bool QTextFormat::isImageFormat () const inline
Returns true if this text format is an image format; otherwise returns false.
Definition at line 322 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitFragment(), and QTextOdfWriter::writeInlineCharacter().
 { return type() == CharFormat && objectType() == ImageObject; }
isListFormat()
bool QTextFormat::isListFormat () const inline
Returns true if this text format is a ListFormat; otherwise returns false.
Definition at line 320 of file qtextformat.h.
Referenced by QTextDocument::createObject().
 { return type() == ListFormat; }
isTableCellFormat()
bool QTextFormat::isTableCellFormat () const inline
Returns true if this text format is a TableCellFormat; otherwise returns false.
Since
4.4
Definition at line 324 of file qtextformat.h.
Referenced by QTextOdfWriter::writeFormats(), and QTextOdfWriter::writeFrame().
 { return type() == CharFormat && objectType() == TableCellObject; }
isTableFormat()
bool QTextFormat::isTableFormat () const inline
Returns true if this text format is a TableFormat; otherwise returns false.
Definition at line 323 of file qtextformat.h.
Referenced by QTextDocument::createObject().
 { return type() == FrameFormat && objectType() == TableObject; }
isValid()
bool QTextFormat::isValid () const inline
Returns true if the format is valid (i.
e. is not InvalidFormat); otherwise returns false.
Definition at line 287 of file qtextformat.h.
 { return type() != InvalidFormat; }
layoutDirection()
Qt::LayoutDirection QTextFormat::layoutDirection () const inline
Returns the document's layout direction.
See also
setLayoutDirection()
Definition at line 340 of file qtextformat.h.
Referenced by QAccessibleTextWidget::characterRect(), QTextHtmlParserNode::initializeProperties(), and QTextHtmlImporter::scanTable().
         { return Qt::LayoutDirection(intProperty(QTextFormat::LayoutDirection)); }
lengthProperty()
QTextLength QTextFormat::lengthProperty (int propertyId) const
Returns the value of the property given by propertyId.
See also
setProperty() boolProperty() intProperty() doubleProperty() stringProperty() colorProperty() lengthVectorProperty() Property
Definition at line 1100 of file qtextformat.cpp.
Referenced by QTextDocumentLayoutPrivate::drawBlock(), and QTextHtmlExporter::emitBlock().
 {
     if (!d)
         return QTextLength();
     return qvariant_cast<QTextLength>(d->property(propertyId));
 }
lengthVectorProperty()
QVector< QTextLength > QTextFormat::lengthVectorProperty (int propertyId) const
Returns the value of the property given by propertyId.
If the property isn't of QTextFormat::LengthVector type, an empty length vector is returned instead.
See also
setProperty() boolProperty() intProperty() doubleProperty() stringProperty() colorProperty() lengthProperty() Property
Definition at line 1114 of file qtextformat.cpp.
 {
     QVector<QTextLength> vector;
     if (!d)
         return vector;
     const QVariant prop = d->property(propertyId);
     if (prop.userType() != QVariant::List)
         return vector;
     QList<QVariant> propertyList = prop.toList();
     for (int i=0; i<propertyList.size(); ++i) {
         QVariant var = propertyList.at(i);
         if (var.userType() == QVariant::TextLength)
             vector.append(qvariant_cast<QTextLength>(var));
     }
     return vector;
 }
merge()
void QTextFormat::merge (const QTextFormat & other)
Merges the other format with this format; where there are conflicts the other format takes precedence.
Definition at line 880 of file qtextformat.cpp.
Referenced by QTextLine::draw(), QTextHtmlExporter::emitBlock(), QTextHtmlExporter::emitTable(), QTextEngine::format(), QCalendarModel::formatForCell(), QTextCursor::mergeCharFormat(), QTextHtmlImporter::processBlockNode(), QTextHtmlImporter::processSpecialNodes(), QTextDocumentPrivate::setBlockFormat(), and QTextDocumentPrivate::setCharFormat().
 {
     if (format_type != other.format_type)
         return;
     if (!d) {
         d = other.d;
         return;
     }
     if (!other.d)
         return;
     QTextFormatPrivate *d = this->d;
     const QVector<QTextFormatPrivate::Property> &otherProps = other.d->props;
     d->props.reserve(d->props.size() + otherProps.size());
     for (int i = 0; i < otherProps.count(); ++i) {
         const QTextFormatPrivate::Property &p = otherProps.at(i);
         d->insertProperty(p.key, p.value);
     }
 }
objectIndex()
int QTextFormat::objectIndex () const
Returns the index of the format object, or -1 if the format object is invalid.
See also
setObjectIndex()
Definition at line 1215 of file qtextformat.cpp.
Referenced by QTextCopyHelper::appendFragment(), QTextCursorPrivate::canDelete(), QTextCopyHelper::convertFormatIndex(), QTextFormatCollection::createObjectIndex(), QTextDocumentPrivate::insertBlock(), QTextDocumentPrivate::objectForFormat(), QTextDocumentPrivate::setCharFormat(), QTextFormatCollection::setObjectFormat(), and QTextFormatCollection::setObjectFormatIndex().
 {
     if (!d)
         return -1;
     const QVariant prop = d->property(ObjectIndex);
     if (prop.userType() != QVariant::Int) // ####
         return -1;
     return prop.toInt();
 }
objectType()
int QTextFormat::objectType () const inline
Returns the text format's object type.
See also
ObjectTypes, setObjectType()
Definition at line 315 of file qtextformat.h.
Referenced by QTextCursorPrivate::canDelete(), QTextDocumentLayoutPrivate::drawFlow(), QAbstractTextDocumentLayout::drawInlineObject(), QTextDocumentLayout::positionInlineObject(), QTextDocumentLayout::resizeInlineObject(), and QAbstractTextDocumentLayout::resizeInlineObject().
     { return intProperty(ObjectType); }
operator QVariant()
QTextFormat::operator QVariant () const
Returns the text format as a QVariant.
Definition at line 871 of file qtextformat.cpp.
 {
     return QVariant(QVariant::TextFormat, this);
 }
operator!=()
bool QTextFormat::operator!= (const QTextFormat & rhs) const inline
Returns true if this text format is different from the other text format.
Definition at line 335 of file qtextformat.h.
 { return !operator==(rhs); }
operator=()
QTextFormat & QTextFormat::operator= (const QTextFormat & rhs)
Assigns the other text format to this text format, and returns a reference to this text format.
Definition at line 853 of file qtextformat.cpp.
 {
     d = rhs.d;
     format_type = rhs.format_type;
     return *this;
 }
operator==()
bool QTextFormat::operator== (const QTextFormat & rhs) const
Returns true if this text format is the same as the other text format.
Definition at line 1310 of file qtextformat.cpp.
 {
     if (format_type != rhs.format_type)
         return false;
     if (d == rhs.d)
         return true;
     if (d && d->props.isEmpty() && !rhs.d)
         return true;
     if (!d && rhs.d && rhs.d->props.isEmpty())
         return true;
     if (!d || !rhs.d)
         return false;
     return *d == *rhs.d;
 }
penProperty()
QPen QTextFormat::penProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Pen type, Qt::NoPen is returned instead.
See also
setProperty() boolProperty() intProperty() doubleProperty() stringProperty() lengthProperty() lengthVectorProperty() Property
Definition at line 1068 of file qtextformat.cpp.
Referenced by QTextLayout::draw(), QTextLine::draw(), and QTextCharFormat::textOutline().
 {
     if (!d)
         return QPen(Qt::NoPen);
     const QVariant prop = d->property(propertyId);
     if (prop.userType() != QVariant::Pen)
         return QPen(Qt::NoPen);
     return qvariant_cast<QPen>(prop);
 }
properties()
QMap< int, QVariant > QTextFormat::properties () const
Returns a map with all properties of this text format.
Definition at line 1268 of file qtextformat.cpp.
Referenced by QTextHtmlExporter::emitBlock(), formatDifference(), and operator<<().
 {
     QMap<int, QVariant> map;
     if (d) {
         for (int i = 0; i < d->props.count(); ++i)
             map.insert(d->props.at(i).key, d->props.at(i).value);
     }
     return map;
 }
property()
QVariant QTextFormat::property (int propertyId) const
Returns the property specified by the given propertyId.
See also
Property
Definition at line 1138 of file qtextformat.cpp.
Referenced by QTextCharFormat::anchorName(), QTextCharFormat::anchorNames(), QTextLayout::draw(), QTextLine::draw(), QTextHtmlExporter::emitBackgroundAttribute(), QTextHtmlExporter::emitBlockAttributes(), formatDifference(), QTextTableData::paddingProperty(), setPenAndDrawBackground(), and QTextBlockFormat::tabPositions().
 {
     return d ? d->property(propertyId) : QVariant();
 }
propertyCount()
int QTextFormat::propertyCount () const
Returns the number of properties stored in the format.
Since
4.3
Definition at line 1285 of file qtextformat.cpp.
Referenced by QTextHtmlImporter::processBlockNode().
 {
     return d ? d->props.count() : 0;
 }
setBackground()
void QTextFormat::setBackground (const QBrush & brush) inline
Sets the brush use to paint the document's background to the brush specified.
See also
background() clearBackground() setForeground()
Definition at line 343 of file qtextformat.h.
Referenced by QTextHtmlParser::applyAttributes(), QTextHtmlParserNode::applyBackgroundImage(), QTextHtmlParserNode::applyCssDeclarations(), QLineControl::draw(), QCalendarModel::formatForCell(), QTextControl::getPaintContext(), QTextControlPrivate::inputMethodEvent(), QPlainTextEdit::paintEvent(), QTextHtmlImporter::processBlockNode(), QLineControl::processInputMethodEvent(), QTextHtmlImporter::processSpecialNodes(), QTextHtmlImporter::scanTable(), QTextEdit::setTextBackgroundColor(), QInputContext::standardFormat(), and QScriptEdit::updateExtraSelections().
     { setProperty(BackgroundBrush, brush); }
setForeground()
void QTextFormat::setForeground (const QBrush & brush) inline
Sets the foreground brush to the specified brush.
The foreground brush is mostly used to render text.
See also
foreground() clearForeground() setBackground()
Definition at line 350 of file qtextformat.h.
Referenced by QTextHtmlParser::applyAttributes(), QTextHtmlParserNode::applyCssDeclarations(), QSvgText::draw(), QLineControl::draw(), QCalendarModel::formatForCell(), QTextControl::getPaintContext(), QTextHtmlParserNode::initializeProperties(), QTextControlPrivate::inputMethodEvent(), QScriptDebuggerConsoleWidget::message(), QScriptDebugOutputWidget::message(), QPlainTextEdit::paintEvent(), QDeclarativeStyledTextPrivate::parseFontAttributes(), QLineControl::processInputMethodEvent(), QCalendarWidget::QCalendarWidget(), QScriptSyntaxHighlighter::QScriptSyntaxHighlighter(), QSyntaxHighlighter::setFormat(), QTextEdit::setTextColor(), and QInputContext::standardFormat().
     { setProperty(ForegroundBrush, brush); }
setLayoutDirection()
void QTextFormat::setLayoutDirection (Qt::LayoutDirection direction) inline
Sets the document's layout direction to the specified direction.
See also
layoutDirection()
Definition at line 338 of file qtextformat.h.
Referenced by QTextHtmlParser::applyAttributes(), QTextHtmlParserNode::initializeProperties(), QTextControlPrivate::keyPressEvent(), and QTextHtmlImporter::scanTable().
         { setProperty(QTextFormat::LayoutDirection, direction); }
setObjectIndex()
void QTextFormat::setObjectIndex (int index)
Sets the format object's object index.
See also
objectIndex()
Definition at line 1235 of file qtextformat.cpp.
Referenced by QTextList::add(), QTextCopyHelper::convertFormatIndex(), QTextCursor::createList(), QTextTablePrivate::createTable(), QTextDocumentPrivate::insertFrame(), QTextCursor::insertImage(), QTextList::remove(), and QTextDocumentPrivate::setCharFormat().
 {
     if (o == -1) {
         if (d)
             d->clearProperty(ObjectIndex);
     } else {
         if (!d)
             d = new QTextFormatPrivate;
         // ### type
         d->insertProperty(ObjectIndex, o);
     }
 }
setObjectType()
void QTextFormat::setObjectType (int type) inline
Sets the text format's object type to type.
See also
ObjectTypes, objectType()
Definition at line 367 of file qtextformat.h.
Referenced by QTextTablePrivate::createTable(), QTextTableCell::format(), QTextImageFormat::QTextImageFormat(), QTextTableCellFormat::QTextTableCellFormat(), QTextTableFormat::QTextTableFormat(), and QTextTableCell::setFormat().
 { setProperty(ObjectType, atype); }
setProperty() [1/2]
void QTextFormat::setProperty (int propertyId, const QVariant & value)
Sets the property specified by the propertyId to the given value.
See also
Property
Definition at line 1148 of file qtextformat.cpp.
Referenced by QTextHtmlParser::applyAttributes(), QTextHtmlParserNode::applyBackgroundImage(), QTextHtmlParserNode::applyCssDeclarations(), QTextLayout::draw(), QTextControl::getPaintContext(), QTextHtmlParserNode::initializeProperties(), QTextHtmlImporter::processSpecialNodes(), QTextHtmlImporter::scanTable(), QTextBlockFormat::setAlignment(), QTextTableFormat::setAlignment(), QTextCharFormat::setAnchor(), QTextCharFormat::setAnchorHref(), QTextCharFormat::setAnchorNames(), QTextFrameFormat::setBorder(), QTextFrameFormat::setBottomMargin(), QTextTableCellFormat::setBottomPadding(), QTextTableFormat::setCellPadding(), QTextTableFormat::setColumns(), QTextCharFormat::setFont(), QTextCharFormat::setFontCapitalization(), QTextCharFormat::setFontFamily(), QTextCharFormat::setFontFixedPitch(), QTextCharFormat::setFontHintingPreference(), QTextCharFormat::setFontItalic(), QTextCharFormat::setFontKerning(), QTextCharFormat::setFontLetterSpacing(), QTextCharFormat::setFontOverline(), QTextCharFormat::setFontPointSize(), QTextCharFormat::setFontStrikeOut(), QTextCharFormat::setFontStyleHint(), QTextCharFormat::setFontStyleStrategy(), QTextCharFormat::setFontUnderline(), QTextCharFormat::setFontWeight(), QTextCharFormat::setFontWordSpacing(), QTextImageFormat::setHeight(), QTextFrameFormat::setHeight(), QTextBlockFormat::setIndent(), QTextListFormat::setIndent(), QTextFrameFormat::setLeftMargin(), QTextTableCellFormat::setLeftPadding(), QTextHtmlParserNode::setListStyle(), QTextFrameFormat::setMargin(), QTextImageFormat::setName(), QTextListFormat::setNumberPrefix(), QTextListFormat::setNumberSuffix(), setObjectType(), QTextFrameFormat::setPadding(), QTextFrameFormat::setRightMargin(), QTextTableCellFormat::setRightPadding(), QTextListFormat::setStyle(), QTextCharFormat::setTableCellColumnSpan(), QTextCharFormat::setTableCellRowSpan(), QTextBlockFormat::setTabPositions(), QTextCharFormat::setTextOutline(), QTextCharFormat::setToolTip(), QTextFrameFormat::setTopMargin(), QTextTableCellFormat::setTopPadding(), QTextCharFormat::setUnderlineColor(), QTextCharFormat::setUnderlineStyle(), QTextCharFormat::setVerticalAlignment(), QTextImageFormat::setWidth(), QTextFrameFormat::setWidth(), QCommonStyle::styleHint(), and QScriptEdit::updateExtraSelections().
 {
     if (!d)
         d = new QTextFormatPrivate;
     if (!value.isValid())
         clearProperty(propertyId);
     else
         d->insertProperty(propertyId, value);
 }
setProperty() [2/2]
void QTextFormat::setProperty (int propertyId, const QVector< QTextLength > & value)
Sets the value of the property given by propertyId to value.
See also
lengthVectorProperty() Property
Definition at line 1163 of file qtextformat.cpp.
 {
     if (!d)
         d = new QTextFormatPrivate;
     QVariantList list;
     for (int i=0; i<value.size(); ++i)
         list << value.at(i);
     d->insertProperty(propertyId, list);
 }
stringProperty()
QString QTextFormat::stringProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::String type, an empty string is returned instead.
See also
setProperty() boolProperty() intProperty() doubleProperty() colorProperty() lengthProperty() lengthVectorProperty() Property
Definition at line 1033 of file qtextformat.cpp.
Referenced by QTextControlPrivate::anchorForCursor(), QTextCharFormat::anchorHref(), QTextCharFormat::fontFamily(), and QTextCharFormat::toolTip().
 {
     if (!d)
         return QString();
     const QVariant prop = d->property(propertyId);
     if (prop.userType() != QVariant::String)
         return QString();
     return prop.toString();
 }
toBlockFormat()
QTextBlockFormat QTextFormat::toBlockFormat () const
Returns this format as a block format.
Definition at line 916 of file qtextformat.cpp.
Referenced by QTextBlock::blockFormat(), and QTextOdfWriter::writeFormats().
 {
     return QTextBlockFormat(*this);
 }
toCharFormat()
QTextCharFormat QTextFormat::toCharFormat () const
Returns this format as a character format.
Definition at line 924 of file qtextformat.cpp.
Referenced by QTextBlock::charFormat(), QTextDocumentLayout::drawInlineObject(), QAbstractTextDocumentLayout::drawInlineObject(), QTextHtmlExporter::emitBlockAttributes(), QTextDocumentLayout::positionInlineObject(), QTextDocumentLayout::resizeInlineObject(), QAbstractTextDocumentLayout::resizeInlineObject(), and QTextOdfWriter::writeFormats().
 {
     return QTextCharFormat(*this);
 }
toFrameFormat()
QTextFrameFormat QTextFormat::toFrameFormat () const
Returns this format as a frame format.
Definition at line 948 of file qtextformat.cpp.
Referenced by QTextFrame::frameFormat(), and QTextOdfWriter::writeFormats().
 {
     return QTextFrameFormat(*this);
 }
toImageFormat()
QTextImageFormat QTextFormat::toImageFormat () const
Returns this format as an image format.
Definition at line 956 of file qtextformat.cpp.
Referenced by QTextImageHandler::drawObject(), QTextHtmlExporter::emitFragment(), QTextImageHandler::intrinsicSize(), and QTextOdfWriter::writeInlineCharacter().
 {
     return QTextImageFormat(*this);
 }
toListFormat()
QTextListFormat QTextFormat::toListFormat () const
Returns this format as a list format.
Definition at line 932 of file qtextformat.cpp.
Referenced by QTextDocumentLayoutPrivate::blockIndent(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawListItem(), QTextList::format(), and QTextOdfWriter::writeFormats().
 {
     return QTextListFormat(*this);
 }
toTableCellFormat()
QTextTableCellFormat QTextFormat::toTableCellFormat () const
Returns this format as a table cell format.
Since
4.4
Definition at line 969 of file qtextformat.cpp.
Referenced by QTextHtmlExporter::emitTable(), QTextHtmlImporter::processBlockNode(), and QTextOdfWriter::writeFormats().
 {
     return QTextTableCellFormat(*this);
 }
toTableFormat()
QTextTableFormat QTextFormat::toTableFormat () const
Returns this format as a table format.
Definition at line 940 of file qtextformat.cpp.
Referenced by QTextTable::format(), and QTextHtmlImporter::scanTable().
 {
     return QTextTableFormat(*this);
 }
type()
int QTextFormat::type () const
Returns the type of this format.
See also
FormatType
Definition at line 908 of file qtextformat.cpp.
Referenced by QTextCopyHelper::convertFormatIndex(), QTextDocumentPrivate::setCharFormat(), and QTextOdfWriter::writeFormats().
 {
     return format_type;
 }
Friends and Related Functions
operator<<
Q_GUI_EXPORT QDataStream& operator<< (QDataStream & , const QTextFormat &) friend
Definition at line 459 of file qtextformat.cpp.
 {
     stream << fmt.format_type << fmt.properties();
     return stream;
 }
operator>>
Q_GUI_EXPORT QDataStream& operator>> (QDataStream & , QTextFormat &) friend
Definition at line 465 of file qtextformat.cpp.
 {
     QMap<qint32, QVariant> properties;
     stream >> fmt.format_type >> properties;
     // QTextFormat's default constructor doesn't allocate the private structure, so
     // we have to do this, in case fmt is a default constructed value.
     if(!fmt.d)
         fmt.d = new QTextFormatPrivate();
     for (QMap<qint32, QVariant>::ConstIterator it = properties.constBegin();
          it != properties.constEnd(); ++it)
         fmt.d->insertProperty(it.key(), it.value());
     return stream;
 }
QTextCharFormat
friend class QTextCharFormat friend
Definition at line 362 of file qtextformat.h.
Referenced by toCharFormat().
QTextFormatCollection
friend class QTextFormatCollection friend
Definition at line 361 of file qtextformat.h.
Properties
d
QSharedDataPointer<QTextFormatPrivate> QTextFormat::d private
Definition at line 358 of file qtextformat.h.
Referenced by boolProperty(), brushProperty(), clearProperty(), colorProperty(), doubleProperty(), QTextCharFormat::font(), QTextFormatCollection::hasFormatCached(), hasProperty(), QTextFormatCollection::indexForFormat(), intProperty(), lengthProperty(), lengthVectorProperty(), merge(), objectIndex(), operator=(), operator==(), operator>>(), penProperty(), properties(), property(), propertyCount(), QTextFormatCollection::setDefaultFont(), setObjectIndex(), setProperty(), and stringProperty().
format_type
qint32 QTextFormat::format_type private
Definition at line 359 of file qtextformat.h.
Referenced by QTextFormatCollection::hasFormatCached(), QTextFormatCollection::indexForFormat(), merge(), operator<<(), operator=(), operator==(), operator>>(), and type().
The documentation for this class was generated from the following files:
/src/gui/text/qtextformat.h
/src/gui/text/qtextformat.cpp