Qt 4.8: QGLBlurTextureCache Class Reference
QGLBlurTextureCache Class Reference
Public Functions
void clearBlurTextureInfo (quint64 cacheKey)
bool hasBlurTextureInfo (quint64 cacheKey) const
void insertBlurTextureInfo (const QPixmap &pixmap, QGLBlurTextureInfo *info)
QGLBlurTextureCache (const QGLContext *)
QGLBlurTextureInfo * takeBlurTextureInfo (const QPixmap &pixmap)
void timerEvent (QTimerEvent *event)
This event handler can be reimplemented in a subclass to receive timer events for the object.
~QGLBlurTextureCache ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QGLBlurTextureCache * cacheForContext (const QGLContext *context)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Private Functions
static void pixmapDestroyed (QPixmapData *pixmap)
Properties
QCache< quint64, QGLBlurTextureInfo > cache
int timerId
Static Private Attributes
static QList< QGLBlurTextureCache * > blurTextureCaches
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 313 of file qglpixmapfilter.cpp.
Constructors and Destructors
QGLBlurTextureCache()
QGLBlurTextureCache::QGLBlurTextureCache (const QGLContext *)
Definition at line 341 of file qglpixmapfilter.cpp.
     : timerId(0)
 {
     cache.setMaxCost(4 * 1024 * 1024);
     blurTextureCaches.append(this);
 }
~QGLBlurTextureCache()
QGLBlurTextureCache::~QGLBlurTextureCache ()
Definition at line 348 of file qglpixmapfilter.cpp.
 {
     blurTextureCaches.removeAt(blurTextureCaches.indexOf(this));
 }
Functions
cacheForContext()
QGLBlurTextureCache * QGLBlurTextureCache::cacheForContext (const QGLContext * context) static
Definition at line 361 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL(), and QGLPixmapDropShadowFilter::processGL().
 {
     return qt_blur_texture_caches()->value(context);
 }
clearBlurTextureInfo()
void QGLBlurTextureCache::clearBlurTextureInfo (quint64 cacheKey)
Definition at line 371 of file qglpixmapfilter.cpp.
Referenced by pixmapDestroyed().
 {
     cache.remove(cacheKey);
 }
hasBlurTextureInfo()
bool QGLBlurTextureCache::hasBlurTextureInfo (quint64 cacheKey) const
Definition at line 376 of file qglpixmapfilter.cpp.
Referenced by pixmapDestroyed().
 {
     return cache.contains(cacheKey);
 }
insertBlurTextureInfo()
void QGLBlurTextureCache::insertBlurTextureInfo (const QPixmap & pixmap, QGLBlurTextureInfo * info)
Definition at line 381 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL(), and QGLPixmapDropShadowFilter::processGL().
 {
     static bool hookAdded = false;
     if (!hookAdded) {
         QImagePixmapCleanupHooks::instance()->addPixmapDataDestructionHook(pixmapDestroyed);
         QImagePixmapCleanupHooks::instance()->addPixmapDataModificationHook(pixmapDestroyed);
         hookAdded = true;
     }
     QImagePixmapCleanupHooks::enableCleanupHooks(pixmap);
     cache.insert(pixmap.cacheKey(), info, pixmap.width() * pixmap.height());
     if (timerId)
         killTimer(timerId);
     timerId = startTimer(8000);
 }
pixmapDestroyed()
void QGLBlurTextureCache::pixmapDestroyed (QPixmapData * pixmap) static private
Definition at line 399 of file qglpixmapfilter.cpp.
 {
     foreach (QGLBlurTextureCache *cache, blurTextureCaches) {
         if (cache->hasBlurTextureInfo(pmd->cacheKey()))
             cache->clearBlurTextureInfo(pmd->cacheKey());
     }
 }
takeBlurTextureInfo()
QGLBlurTextureInfo * QGLBlurTextureCache::takeBlurTextureInfo (const QPixmap & pixmap)
Definition at line 366 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL(), and QGLPixmapDropShadowFilter::processGL().
 {
     return cache.take(pixmap.cacheKey());
 }
timerEvent()
void QGLBlurTextureCache::timerEvent (QTimerEvent * event) virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 353 of file qglpixmapfilter.cpp.
 {
     killTimer(timerId);
     timerId = 0;
     cache.clear();
 }
Properties
blurTextureCaches
QList< QGLBlurTextureCache * > QGLBlurTextureCache::blurTextureCaches static private
Definition at line 333 of file qglpixmapfilter.cpp.
cache
QCache<quint64, QGLBlurTextureInfo > QGLBlurTextureCache::cache private
Definition at line 331 of file qglpixmapfilter.cpp.
timerId
int QGLBlurTextureCache::timerId private
Definition at line 335 of file qglpixmapfilter.cpp.
The documentation for this class was generated from the following file:
/src/opengl/qglpixmapfilter.cpp