Qt 4.8: QNetworkManagerConnectionActive Class Reference
QNetworkManagerConnectionActive Class Reference
#include <qnetworkmanagerservice.h>
Public Types
enum ActiveConnectionState { Unknown = 0, Activating = 1, Activated = 2 }
Signals
void propertiesChanged (QList< QDBusObjectPath >)
void propertiesChanged (const QString &, QMap< QString, QVariant >)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDBusObjectPath connection () const
QDBusInterface * connectionInterface () const
bool defaultRoute () const
QList< QDBusObjectPath > devices () const
bool isValid ()
QNetworkManagerConnectionActive (const QString &dbusPathName, QObject *parent=0)
QString serviceName () const
bool setConnections ()
QDBusObjectPath specificObject () const
quint32 state () const
~ QNetworkManagerConnectionActive ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QNetworkManagerConnectionActivePrivate * d
QNmDBusHelper * nmDBusHelper
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 395 of file qnetworkmanagerservice.h.
Enumerations
ActiveConnectionState
enum QNetworkManagerConnectionActive::ActiveConnectionState
Enumerator
Unknown
Activating
Activated
Definition at line 401 of file qnetworkmanagerservice.h.
{
         Unknown = 0,
         Activating = 1,
         Activated = 2
        };
Constructors and Destructors
QNetworkManagerConnectionActive()
QNetworkManagerConnectionActive::QNetworkManagerConnectionActive (const QString & dbusPathName, QObject * parent = 0) explicit
Definition at line 803 of file qnetworkmanagerservice.cpp.
     : QObject(parent), nmDBusHelper(0)
 {
     d = new QNetworkManagerConnectionActivePrivate();
     d->path = activeConnectionObjectPath;
     d->connectionInterface = new QDBusInterface(QLatin1String(NM_DBUS_SERVICE),
                                                 d->path,
                                                 QLatin1String(NM_DBUS_INTERFACE_ACTIVE_CONNECTION),
                                                 dbusConnection, parent);
     if (!d->connectionInterface->isValid()) {
         d->valid = false;
         return;
     }
     d->valid = true;
 }
~ QNetworkManagerConnectionActive()
QNetworkManagerConnectionActive::~ QNetworkManagerConnectionActive ()
Functions
connection()
QDBusObjectPath QNetworkManagerConnectionActive::connection () const
Definition at line 861 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::activeConnectionPropertiesChanged(), QNetworkManagerEngine::interfacePropertiesChanged(), and QNetworkManagerEngine::sessionStateForId().
 {
     QVariant prop = d->connectionInterface->property("Connection");
     return prop.value<QDBusObjectPath>();
 }
connectionInterface()
QDBusInterface * QNetworkManagerConnectionActive::connectionInterface () const
Definition at line 851 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface;
 }
defaultRoute()
bool QNetworkManagerConnectionActive::defaultRoute () const
Definition at line 884 of file qnetworkmanagerservice.cpp.
 {
     return d->connectionInterface->property("Default").toBool();
 }
devices()
QList< QDBusObjectPath > QNetworkManagerConnectionActive::devices () const
Definition at line 873 of file qnetworkmanagerservice.cpp.
 {
     QVariant prop = d->connectionInterface->property("Devices");
     return prop.value<QList<QDBusObjectPath> >();
 }
isValid()
bool QNetworkManagerConnectionActive::isValid ()
Definition at line 825 of file qnetworkmanagerservice.cpp.
Referenced by setConnections().
 {
     return d->valid;
 }
propertiesChanged [1/2]
void QNetworkManagerConnectionActive::propertiesChanged (QList< QDBusObjectPath >) signal
Referenced by setConnections().
propertiesChanged [2/2]
void QNetworkManagerConnectionActive::propertiesChanged (const QString & , QMap< QString, QVariant >) signal
serviceName()
QString QNetworkManagerConnectionActive::serviceName () const
Definition at line 856 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::activeConnectionPropertiesChanged(), QNetworkManagerEngine::interfacePropertiesChanged(), and QNetworkManagerEngine::sessionStateForId().
 {
     return d->connectionInterface->property("ServiceName").toString();
 }
setConnections()
bool QNetworkManagerConnectionActive::setConnections ()
Definition at line 830 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::initialize(), and QNetworkManagerEngine::interfacePropertiesChanged().
 {
     if(!isValid() )
         return false;
     bool allOk = false;
     delete nmDBusHelper;
     nmDBusHelper = new QNmDBusHelper(this);
     connect(nmDBusHelper, SIGNAL(pathForPropertiesChanged(const QString &,QMap<QString,QVariant>)),
             this,SIGNAL(propertiesChanged( const QString &, QMap<QString,QVariant>)));
     if(dbusConnection.connect(QLatin1String(NM_DBUS_SERVICE),
                               d->path,
                               QLatin1String(NM_DBUS_INTERFACE_ACTIVE_CONNECTION),
                               QLatin1String("PropertiesChanged"),
                               nmDBusHelper,SLOT(slotPropertiesChanged( QMap<QString,QVariant>))) )  {
         allOk = true;
     }
     return allOk;
 }
specificObject()
QDBusObjectPath QNetworkManagerConnectionActive::specificObject () const
Definition at line 867 of file qnetworkmanagerservice.cpp.
 {
     QVariant prop = d->connectionInterface->property("SpecificObject");
     return prop.value<QDBusObjectPath>();
 }
state()
quint32 QNetworkManagerConnectionActive::state () const
Definition at line 879 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::activeConnectionPropertiesChanged(), QNetworkManagerEngine::interfacePropertiesChanged(), and QNetworkManagerEngine::sessionStateForId().
 {
     return d->connectionInterface->property("State").toUInt();
 }
Properties
d
QNetworkManagerConnectionActivePrivate* QNetworkManagerConnectionActive::d private
Definition at line 425 of file qnetworkmanagerservice.h.
Referenced by connection(), connectionInterface(), defaultRoute(), devices(), isValid(), QNetworkManagerConnectionActive(), serviceName(), setConnections(), specificObject(), and state().
nmDBusHelper
QNmDBusHelper* QNetworkManagerConnectionActive::nmDBusHelper private
Definition at line 426 of file qnetworkmanagerservice.h.
Referenced by setConnections().
The documentation for this class was generated from the following files:
/src/plugins/bearer/networkmanager/qnetworkmanagerservice.h
/src/plugins/bearer/networkmanager/qnetworkmanagerservice.cpp