Qt 4.8: QPdfEngine Class Reference
QPdfEngine Class Reference
#include <qprintengine_pdf_p.h>
Public Functions
bool abort ()
Instructs the print engine to abort the printing process.
QString author () const
bool begin (QPaintDevice *pdev)
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
void drawImage (const QRectF &r, const QImage &pm, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
void drawPixmap (const QRectF &rectangle, const QPixmap &pixmap, const QRectF &sr)
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
void drawTiledPixmap (const QRectF &rectangle, const QPixmap &pixmap, const QPointF &point)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
bool end ()
Reimplement this function to finish painting on the current paint device.
bool newPage ()
Instructs the print engine to start a new page.
QPrinter::PrinterState printerState () const
Returns the current state of the printer being used by the print engine.
QPdfEngine (QPrinter::PrinterMode m)
void setAuthor (const QString &author)
void setBrush ()
void setDevice (QIODevice *dev)
Type type () const
Reimplement this function to return the paint engine Type.
virtual ~QPdfEngine ()
Public Functions inherited from QPdfBaseEngine
void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the buffer points.
void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
void drawTextItem (const QPointF &p, const QTextItem &textItem)
This function draws the text item textItem at position p.
int metric (QPaintDevice::PaintDeviceMetric metricType) const
Returns the metric for the given id.
QVariant property (PrintEnginePropertyKey key) const
Returns the print engine's property specified by key.
QPdfBaseEngine (QPdfBaseEnginePrivate &d, PaintEngineFeatures f)
void setPen ()
void setProperty (PrintEnginePropertyKey key, const QVariant &value)
Sets the print engine's property specified by key to the given value.
void setupGraphicsState (QPaintEngine::DirtyFlags flags)
void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
~QPdfBaseEngine ()
Public Functions inherited from QAlphaPaintEngine
virtual void drawImage (const QRectF &r, const QImage &image, const QRectF &sr)
~QAlphaPaintEngine ()
Public Functions inherited from QPaintEngine
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
virtual void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
virtual void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
virtual void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
virtual void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual ~QPaintEngine ()
Destroys the paint engine.
Public Functions inherited from QPrintEngine
virtual HDC getPrinterDC () const
virtual void releasePrinterDC (HDC) const
virtual ~QPrintEngine ()
Destroys the print engine.
Properties
QPrinter::PrinterState state
Additional Inherited Members
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Public Types inherited from QPrintEngine
enum PrintEnginePropertyKey {
PPK_CollateCopies, PPK_ColorMode, PPK_Creator, PPK_DocumentName,
PPK_FullPage, PPK_NumberOfCopies, PPK_Orientation, PPK_OutputFileName,
PPK_PageOrder, PPK_PageRect, PPK_PageSize, PPK_PaperRect,
PPK_PaperSource, PPK_PrinterName, PPK_PrinterProgram, PPK_Resolution,
PPK_SelectionOption, PPK_SupportedResolutions, PPK_WindowsPageSize, PPK_FontEmbedding,
PPK_SuppressSystemPrintStatus, PPK_Duplex, PPK_PaperSources, PPK_CustomPaperSize,
PPK_PageMargins, PPK_CopyCount, PPK_SupportsMultipleCopies, PPK_PaperSize = PPK_PageSize,
PPK_CustomBase = 0xff00
}
This enum is used to communicate properties between the print engine and QPrinter.
Protected Functions inherited from QAlphaPaintEngine
QRegion alphaClipping () const
void cleanUp ()
bool continueCall () const
void flushAndInit (bool init=true)
QAlphaPaintEngine (QAlphaPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 85 of file qprintengine_pdf_p.h.
Constructors and Destructors
QPdfEngine()
QPdfEngine::QPdfEngine (QPrinter::PrinterMode m)
Definition at line 112 of file qprintengine_pdf.cpp.
     : QPdfBaseEngine(*new QPdfEnginePrivate(m), qt_pdf_decide_features())
 {
     state = QPrinter::Idle;
 }
~QPdfEngine()
QPdfEngine::~QPdfEngine () virtual
Definition at line 118 of file qprintengine_pdf.cpp.
 {
 }
Functions
abort()
bool QPdfEngine::abort () inline virtual
Instructs the print engine to abort the printing process.
Returns true if successful; otherwise returns false.
Implements QPrintEngine.
Definition at line 104 of file qprintengine_pdf_p.h.
 {return false;}
author()
QString QPdfEngine::author () const
Referenced by printerState().
begin()
bool QPdfEngine::begin (QPaintDevice * pdev) virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Reimplemented from QPdfBaseEngine.
Definition at line 122 of file qprintengine_pdf.cpp.
 {
     Q_D(QPdfEngine);
     if(!QPdfBaseEngine::begin(pdev)) {
         state = QPrinter::Error;
         return false;
     }
     d->stream->setDevice(d->outDevice);
     d->streampos = 0;
     d->hasPen = true;
     d->hasBrush = false;
     d->clipEnabled = false;
     d->allClipped = false;
     d->xrefPositions.clear();
     d->pageRoot = 0;
     d->catalog = 0;
     d->info = 0;
     d->graphicsState = 0;
     d->patternColorSpace = 0;
     d->pages.clear();
     d->imageCache.clear();
     d->alphaCache.clear();
     setActive(true);
     state = QPrinter::Active;
     d->writeHeader();
     newPage();
     return true;
 }
drawImage()
void QPdfEngine::drawImage (const QRectF & r, const QImage & pm, const QRectF & sr, Qt::ImageConversionFlags flags = Qt::AutoColor) virtual
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
Reimplemented from QPaintEngine.
Definition at line 200 of file qprintengine_pdf.cpp.
 {
     if (sr.isEmpty() || rectangle.isEmpty() || image.isNull())
         return;
     Q_D(QPdfEngine);
     QRect sourceRect = sr.toRect();
     QImage im = sourceRect != image.rect() ? image.copy(sourceRect) : image;
     bool bitmap = true;
     const int object = d->addImage(im, &bitmap, im.cacheKey());
     if (object < 0)
         return;
     *d->currentPage << "q\n/GSa gs\n";
     *d->currentPage
         << QPdf::generateMatrix(QTransform(rectangle.width() / sr.width(), 0, 0, rectangle.height() / sr.height(),
                                            rectangle.x(), rectangle.y()) * (d->simplePen ? QTransform() : d->stroker.matrix));
     setBrush();
     d->currentPage->streamImage(im.width(), im.height(), object);
     *d->currentPage << "Q\n";
 }
drawPixmap()
void QPdfEngine::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Reimplemented from QAlphaPaintEngine.
Definition at line 169 of file qprintengine_pdf.cpp.
 {
     if (sr.isEmpty() || rectangle.isEmpty() || pixmap.isNull())
         return;
     Q_D(QPdfEngine);
     QBrush b = d->brush;
     QRect sourceRect = sr.toRect();
     QPixmap pm = sourceRect != pixmap.rect() ? pixmap.copy(sourceRect) : pixmap;
     QImage image = pm.toImage();
     bool bitmap = true;
     const int object = d->addImage(image, &bitmap, pm.cacheKey());
     if (object < 0)
         return;
     *d->currentPage << "q\n/GSa gs\n";
     *d->currentPage
         << QPdf::generateMatrix(QTransform(rectangle.width() / sr.width(), 0, 0, rectangle.height() / sr.height(),
                                            rectangle.x(), rectangle.y()) * (d->simplePen ? QTransform() : d->stroker.matrix));
     if (bitmap) {
         // set current pen as d->brush
         d->brush = d->pen.brush();
     }
     setBrush();
     d->currentPage->streamImage(image.width(), image.height(), object);
     *d->currentPage << "Q\n";
     d->brush = b;
 }
drawTiledPixmap()
void QPdfEngine::drawTiledPixmap (const QRectF & rect, const QPixmap & pixmap, const QPointF & p) virtual
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
The pixmap will be drawn repeatedly until the rect is filled.
Reimplemented from QAlphaPaintEngine.
Definition at line 222 of file qprintengine_pdf.cpp.
 {
     Q_D(QPdfEngine);
     bool bitmap = (pixmap.depth() == 1);
     QBrush b = d->brush;
     QPointF bo = d->brushOrigin;
     bool hp = d->hasPen;
     d->hasPen = false;
     bool hb = d->hasBrush;
     d->hasBrush = true;
     d->brush = QBrush(pixmap);
     if (bitmap)
         // #### fix bitmap case where we have a brush pen
         d->brush.setColor(d->pen.color());
     d->brushOrigin = -point;
     *d->currentPage << "q\n";
     setBrush();
     drawRects(&rectangle, 1);
     *d->currentPage << "Q\n";
     d->hasPen = hp;
     d->hasBrush = hb;
     d->brush = b;
     d->brushOrigin = bo;
 }
end()
bool QPdfEngine::end () virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Reimplemented from QPdfBaseEngine.
Definition at line 156 of file qprintengine_pdf.cpp.
 {
     Q_D(QPdfEngine);
     d->writeTail();
     d->stream->unsetDevice();
     QPdfBaseEngine::end();
     setActive(false);
     state = QPrinter::Idle;
     return true;
 }
newPage()
bool QPdfEngine::newPage () virtual
Instructs the print engine to start a new page.
Returns true if the printer was able to create the new page; otherwise returns false.
Reimplemented from QPdfBaseEngine.
Definition at line 291 of file qprintengine_pdf.cpp.
Referenced by abort(), and begin().
 {
     Q_D(QPdfEngine);
     if (!isActive())
         return false;
     d->newPage();
     return QPdfBaseEngine::newPage();
 }
printerState()
QPrinter::PrinterState QPdfEngine::printerState () const inline virtual
Returns the current state of the printer being used by the print engine.
Implements QPrintEngine.
Definition at line 106 of file qprintengine_pdf_p.h.
 {return state;}
setAuthor()
void QPdfEngine::setAuthor (const QString & author)
Referenced by printerState().
setBrush()
void QPdfEngine::setBrush () virtual
Implements QPdfBaseEngine.
Definition at line 253 of file qprintengine_pdf.cpp.
Referenced by drawImage(), drawPixmap(), drawTiledPixmap(), and printerState().
 {
     Q_D(QPdfEngine);
     Qt::BrushStyle style = d->brush.style();
     if (style == Qt::NoBrush)
         return;
     bool specifyColor;
     int gStateObject = 0;
     int patternObject = d->addBrushPattern(d->stroker.matrix, &specifyColor, &gStateObject);
     *d->currentPage << (patternObject ? "/PCSp cs " : "/CSp cs ");
     if (specifyColor) {
         QColor rgba = d->brush.color();
         if (d->colorMode == QPrinter::GrayScale) {
             qreal gray = qGray(rgba.rgba())/255.;
             *d->currentPage << gray << gray << gray;
         } else {
             *d->currentPage << rgba.redF()
                             << rgba.greenF()
                             << rgba.blueF();
         }
     }
     if (patternObject)
         *d->currentPage << "/Pat" << patternObject;
     *d->currentPage << "scn\n";
     if (gStateObject)
         *d->currentPage << "/GState" << gStateObject << "gs\n";
     else
         *d->currentPage << "/GSa gs\n";
 }
setDevice()
void QPdfEngine::setDevice (QIODevice * dev)
Referenced by printerState().
type()
QPaintEngine::Type QPdfEngine::type () const virtual
Reimplement this function to return the paint engine Type.
Implements QPaintEngine.
Definition at line 286 of file qprintengine_pdf.cpp.
 {
     return QPaintEngine::Pdf;
 }
Properties
state
QPrinter::PrinterState QPdfEngine::state private
Definition at line 120 of file qprintengine_pdf_p.h.
Referenced by begin(), end(), printerState(), and QPdfEngine().
The documentation for this class was generated from the following files:
/src/gui/painting/qprintengine_pdf_p.h
/src/gui/painting/qprintengine_pdf.cpp