Qt 4.8: QIncrementalSleepTimer Class Reference
QIncrementalSleepTimer Class Reference
#include <qwindowspipewriter_p.h>
Public Functions
bool hasTimedOut () const
int nextSleepTime ()
QIncrementalSleepTimer (int msecs)
void resetIncrements ()
int timeLeft () const
Properties
int nextSleep
QTime timer
int totalTimeOut
Detailed Description
Definition at line 73 of file qwindowspipewriter_p.h.
Constructors and Destructors
QIncrementalSleepTimer()
QIncrementalSleepTimer::QIncrementalSleepTimer (int msecs) inline
Definition at line 77 of file qwindowspipewriter_p.h.
         : totalTimeOut(msecs)
         , nextSleep(qMin(SLEEPMIN, totalTimeOut))
     {
         if (totalTimeOut == -1)
             nextSleep = SLEEPMIN;
         timer.start();
     }
Functions
hasTimedOut()
bool QIncrementalSleepTimer::hasTimedOut () const inline
Definition at line 100 of file qwindowspipewriter_p.h.
Referenced by QLocalSocketPrivate::_q_emitReadyRead(), and qt_terminateApp().
     {
         if (totalTimeOut == -1)
             return false;
         return timer.elapsed() >= totalTimeOut;
     }
nextSleepTime()
int QIncrementalSleepTimer::nextSleepTime () inline
Definition at line 86 of file qwindowspipewriter_p.h.
Referenced by QLocalSocketPrivate::_q_emitReadyRead(), and qt_terminateApp().
     {
         int tmp = nextSleep;
         nextSleep = qMin(nextSleep * 2, qMin(SLEEPMAX, timeLeft()));
         return tmp;
     }
resetIncrements()
void QIncrementalSleepTimer::resetIncrements () inline
Definition at line 107 of file qwindowspipewriter_p.h.
Referenced by qt_terminateApp().
     {
         nextSleep = qMin(SLEEPMIN, timeLeft());
     }
timeLeft()
int QIncrementalSleepTimer::timeLeft () const inline
Definition at line 93 of file qwindowspipewriter_p.h.
Referenced by nextSleepTime(), and resetIncrements().
     {
         if (totalTimeOut == -1)
             return SLEEPMAX;
         return qMax(totalTimeOut - timer.elapsed(), 0);
     }
Properties
nextSleep
int QIncrementalSleepTimer::nextSleep private
Definition at line 115 of file qwindowspipewriter_p.h.
Referenced by nextSleepTime(), QIncrementalSleepTimer(), and resetIncrements().
timer
QTime QIncrementalSleepTimer::timer private
Definition at line 113 of file qwindowspipewriter_p.h.
Referenced by hasTimedOut(), QIncrementalSleepTimer(), and timeLeft().
totalTimeOut
int QIncrementalSleepTimer::totalTimeOut private
Definition at line 114 of file qwindowspipewriter_p.h.
Referenced by hasTimedOut(), QIncrementalSleepTimer(), and timeLeft().
The documentation for this class was generated from the following file:
/src/corelib/io/qwindowspipewriter_p.h