Qt 4.8: QDirectFBPointer< T > Class Template Reference
QDirectFBPointer< T > Class Template Reference
#include <qdirectfbconvenience.h>
Public Functions
T ** outPtr ()
QDirectFBPointer (T *t=0)
QDirectFBPointer (T *t=0)
Public Functions inherited from QScopedPointer< T, QDirectFBInterfaceCleanupHandler< T > >
T * data () const
Returns the value of the pointer referenced by this object.
bool isNull () const
Returns true if this object is holding a pointer that is null.
operator bool () const
Returns true if this object is not null.
bool operator! () const
Returns true if the pointer referenced by this object is null, otherwise returns false.
T & operator* () const
Provides access to the scoped pointer's object.
T * operator-> () const
Provides access to the scoped pointer's object.
QScopedPointer (T *p=0)
Constructs this QScopedPointer instance and sets its pointer to p.
void reset (T *other=0)
Deletes the existing object it is pointing to if any, and sets its pointer to other.
void swap (QScopedPointer< T, QDirectFBInterfaceCleanupHandler< T > > &other)
Swap this pointer with other.
T * take ()
Returns the value of the pointer referenced by this object.
~QScopedPointer ()
Destroys this QScopedPointer object.
Additional Inherited Members
Public Types inherited from QScopedPointer< T, QDirectFBInterfaceCleanupHandler< T > >
typedef T * pointer
Protected Variables inherited from QScopedPointer< T, QDirectFBInterfaceCleanupHandler< T > >
T * d
Detailed Description
template<typename T>
class QDirectFBPointer< T >
Definition at line 227 of file qdirectfbpixmap.cpp.
Constructors and Destructors
QDirectFBPointer() [1/2]
template<typename T> QDirectFBPointer< T >::QDirectFBPointer (T * t = 0) inline
Definition at line 230 of file qdirectfbpixmap.cpp.
         : QScopedPointer<T, QDirectFBInterfaceCleanupHandler<T> >(t)
     {}
QDirectFBPointer() [2/2]
template<typename T> QDirectFBPointer< T >::QDirectFBPointer (T * t = 0) inline
Definition at line 103 of file qdirectfbconvenience.h.
         : QScopedPointer<T, QDirectFBInterfaceCleanupHandler<T> >(t)
     {}
Functions
outPtr()
template<typename T> T** QDirectFBPointer< T >::outPtr () inline
Definition at line 107 of file qdirectfbconvenience.h.
Referenced by QDirectFbWindow::dfbSurface(), QDirectFbBlitterPlatformPixmap::fromDataBufferDescription(), QDirectFbInput::globalPoint(), QDirectFbInput::handleMouseEvents(), QDirectFbBlitter::QDirectFbBlitter(), QDirectFbInput::QDirectFbInput(), QDirectFbWindow::QDirectFbWindow(), QDirectFbWindowSurface::QDirectFbWindowSurface(), and QDirectFbWindow::setVisible().
     {
         this->reset(0);
         return &this->d;
     }
The documentation for this class was generated from the following files:
/src/plugins/gfxdrivers/directfb/qdirectfbpixmap.cpp
/src/plugins/platforms/directfb/qdirectfbconvenience.h