Qt 4.8: QPaintBufferPrivate Class Reference
QPaintBufferPrivate Class Reference
#include <qpaintbuffer_p.h>
Public Types
enum Command {
Cmd_Save, Cmd_Restore, Cmd_SetBrush, Cmd_SetBrushOrigin,
Cmd_SetClipEnabled, Cmd_SetCompositionMode, Cmd_SetOpacity, Cmd_SetPen,
Cmd_SetRenderHints, Cmd_SetTransform, Cmd_SetBackgroundMode, Cmd_ClipPath,
Cmd_ClipRect, Cmd_ClipRegion, Cmd_ClipVectorPath, Cmd_DrawVectorPath,
Cmd_FillVectorPath, Cmd_StrokeVectorPath, Cmd_DrawConvexPolygonF, Cmd_DrawConvexPolygonI,
Cmd_DrawEllipseF, Cmd_DrawEllipseI, Cmd_DrawLineF, Cmd_DrawLineI,
Cmd_DrawPath, Cmd_DrawPointsF, Cmd_DrawPointsI, Cmd_DrawPolygonF,
Cmd_DrawPolygonI, Cmd_DrawPolylineF, Cmd_DrawPolylineI, Cmd_DrawRectF,
Cmd_DrawRectI, Cmd_FillRectBrush, Cmd_FillRectColor, Cmd_DrawText,
Cmd_DrawTextItem, Cmd_DrawImagePos, Cmd_DrawImageRect, Cmd_DrawPixmapPos,
Cmd_DrawPixmapRect, Cmd_DrawTiledPixmap, Cmd_SystemStateChanged, Cmd_Translate,
Cmd_DrawStaticText, Cmd_LastCommand
}
Public Functions
QPaintBufferCommand * addCommand (Command command)
QPaintBufferCommand * addCommand (Command command, const QVariant &var)
QPaintBufferCommand * addCommand (Command command, const QVectorPath &path)
QPaintBufferCommand * addCommand (Command command, const qreal *pts, int arrayLength, int elementCount)
QPaintBufferCommand * addCommand (Command command, const int *pts, int arrayLength, int elementCount)
int addData (const int *data, int count)
int addData (const qreal *data, int count)
int addData (const QVariant &var)
QPaintBufferPrivate ()
void updateBoundingRect (const QRectF &rect)
~QPaintBufferPrivate ()
Public Variables
QRectF boundingRect
void * cache
uint calculateBoundingRect: 1
QVector< QPaintBufferCommand > commands
QPaintBufferEngine * engine
QVector< qreal > floats
QList< int > frames
QVector< int > ints
qreal penWidthAdjustment
QAtomicInt ref
QVector< QVariant > variants
Detailed Description
Definition at line 139 of file qpaintbuffer_p.h.
Enumerations
Command
enum QPaintBufferPrivate::Command
Enumerator
Cmd_Save
Cmd_Restore
Cmd_SetBrush
Cmd_SetBrushOrigin
Cmd_SetClipEnabled
Cmd_SetCompositionMode
Cmd_SetOpacity
Cmd_SetPen
Cmd_SetRenderHints
Cmd_SetTransform
Cmd_SetBackgroundMode
Cmd_ClipPath
Cmd_ClipRect
Cmd_ClipRegion
Cmd_ClipVectorPath
Cmd_DrawVectorPath
Cmd_FillVectorPath
Cmd_StrokeVectorPath
Cmd_DrawConvexPolygonF
Cmd_DrawConvexPolygonI
Cmd_DrawEllipseF
Cmd_DrawEllipseI
Cmd_DrawLineF
Cmd_DrawLineI
Cmd_DrawPath
Cmd_DrawPointsF
Cmd_DrawPointsI
Cmd_DrawPolygonF
Cmd_DrawPolygonI
Cmd_DrawPolylineF
Cmd_DrawPolylineI
Cmd_DrawRectF
Cmd_DrawRectI
Cmd_FillRectBrush
Cmd_FillRectColor
Cmd_DrawText
Cmd_DrawTextItem
Cmd_DrawImagePos
Cmd_DrawImageRect
Cmd_DrawPixmapPos
Cmd_DrawPixmapRect
Cmd_DrawTiledPixmap
Cmd_SystemStateChanged
Cmd_Translate
Cmd_DrawStaticText
Cmd_LastCommand
Definition at line 142 of file qpaintbuffer_p.h.
                  {
         Cmd_Save,
         Cmd_Restore,
         Cmd_SetBrush,
         Cmd_SetBrushOrigin,
         Cmd_SetClipEnabled,
         Cmd_SetCompositionMode,
         Cmd_SetOpacity,
         Cmd_SetPen,
         Cmd_SetRenderHints,
         Cmd_SetTransform,
         Cmd_SetBackgroundMode,
         Cmd_ClipPath,
         Cmd_ClipRect,
         Cmd_ClipRegion,
         Cmd_ClipVectorPath,
         Cmd_DrawVectorPath,
         Cmd_FillVectorPath,
         Cmd_StrokeVectorPath,
         Cmd_DrawConvexPolygonF,
         Cmd_DrawConvexPolygonI,
         Cmd_DrawEllipseF,
         Cmd_DrawEllipseI,
         Cmd_DrawLineF,
         Cmd_DrawLineI,
         Cmd_DrawPath,
         Cmd_DrawPointsF,
         Cmd_DrawPointsI,
         Cmd_DrawPolygonF,
         Cmd_DrawPolygonI,
         Cmd_DrawPolylineF,
         Cmd_DrawPolylineI,
         Cmd_DrawRectF,
         Cmd_DrawRectI,
         Cmd_FillRectBrush,
         Cmd_FillRectColor,
         Cmd_DrawText,
         Cmd_DrawTextItem,
         Cmd_DrawImagePos,
         Cmd_DrawImageRect,
         Cmd_DrawPixmapPos,
         Cmd_DrawPixmapRect,
         Cmd_DrawTiledPixmap,
         Cmd_SystemStateChanged,
         Cmd_Translate,
         Cmd_DrawStaticText,
         // new commands must be added above this line
         Cmd_LastCommand
     };
Constructors and Destructors
QPaintBufferPrivate()
QPaintBufferPrivate::QPaintBufferPrivate ()
Definition at line 118 of file qpaintbuffer.cpp.
     : ref(1), engine(0), penWidthAdjustment(0)
     , calculateBoundingRect(true)
     , cache(0)
 {
 }
~QPaintBufferPrivate()
QPaintBufferPrivate::~QPaintBufferPrivate ()
Definition at line 125 of file qpaintbuffer.cpp.
 {
     QPaintBufferSignalProxy::instance()->emitAboutToDestroy(this);
     for (int i = 0; i < commands.size(); ++i) {
         const QPaintBufferCommand &cmd = commands.at(i);
         if (cmd.id == QPaintBufferPrivate::Cmd_DrawTextItem)
             delete reinterpret_cast<QTextItemIntCopy *>(qvariant_cast<void *>(variants.at(cmd.offset)));
     }
 }
Functions
addCommand() [1/5]
QPaintBufferCommand* QPaintBufferPrivate::addCommand (Command command) inline
Definition at line 228 of file qpaintbuffer_p.h.
Referenced by QPaintBufferEngine::backgroundModeChanged(), QPaintBufferEngine::brushChanged(), QPaintBufferEngine::brushOriginChanged(), QPaintBufferEngine::clip(), QPaintBufferEngine::clipEnabledChanged(), QPaintBufferEngine::compositionModeChanged(), QPaintBufferEngine::draw(), QPaintBufferEngine::drawEllipse(), QPaintBufferEngine::drawImage(), QPaintBufferEngine::drawLines(), QPaintBufferEngine::drawPixmap(), QPaintBufferEngine::drawPoints(), QPaintBufferEngine::drawPolygon(), QPaintBufferEngine::drawRects(), QPaintBufferEngine::drawStaticTextItem(), QPaintBufferEngine::drawTextItem(), QPaintBufferEngine::drawTiledPixmap(), QPaintBufferEngine::fill(), QPaintBufferEngine::fillRect(), QPaintBufferEngine::opacityChanged(), QPaintBufferEngine::penChanged(), QPaintBufferEngine::renderHintsChanged(), QPaintBufferEngine::setState(), QPaintBufferEngine::stroke(), and QPaintBufferEngine::transformChanged().
{
         QPaintBufferCommand cmd;
         cmd.id = command;
         cmd.size = cmd.offset = cmd.offset2 = cmd.extra = 0;
         commands << cmd;
         return &commands.last();
     }
addCommand() [2/5]
QPaintBufferCommand* QPaintBufferPrivate::addCommand (Command command, const QVariant & var) inline
Definition at line 236 of file qpaintbuffer_p.h.
{
         QPaintBufferCommand cmd;
         cmd.id = command;
         cmd.offset = addData(var);
         cmd.size = cmd.offset2 = cmd.extra = 0;
         commands << cmd;
         return &commands.last();
     }
addCommand() [3/5]
QPaintBufferCommand* QPaintBufferPrivate::addCommand (Command command, const QVectorPath & path) inline
Definition at line 245 of file qpaintbuffer_p.h.
{
         QPaintBufferCommand cmd;
         cmd.id = command;
         cmd.offset = addData(path.points(), path.elementCount() * 2);
         cmd.offset2 = ints.size();
         ints << path.hints();
         // The absence of path elements is indicated by setting the highest bit in 'cmd.offset2'.
         if (path.elements())
             addData((const int *) path.elements(), path.elementCount());
         else
             cmd.offset2 |= 0x80000000;
         cmd.size = path.elementCount();
         cmd.extra = 0;
         commands << cmd;
         return &commands.last();
     }
addCommand() [4/5]
QPaintBufferCommand* QPaintBufferPrivate::addCommand (Command command, const qreal * pts, int arrayLength, int elementCount) inline
Definition at line 262 of file qpaintbuffer_p.h.
{
         QPaintBufferCommand cmd;
         cmd.id = command;
         cmd.offset = addData(pts, arrayLength);
         cmd.size = elementCount;
         cmd.offset2 = cmd.extra = 0;
         commands << cmd;
         return &commands.last();
     }
addCommand() [5/5]
QPaintBufferCommand* QPaintBufferPrivate::addCommand (Command command, const int * pts, int arrayLength, int elementCount) inline
Definition at line 272 of file qpaintbuffer_p.h.
{
         QPaintBufferCommand cmd;
         cmd.id = command;
         cmd.offset = addData(pts, arrayLength);
         cmd.size = elementCount;
         cmd.offset2 = cmd.extra = 0;
         commands << cmd;
         return &commands.last();
     }
addData() [1/3]
int QPaintBufferPrivate::addData (const int * data, int count) inline
Definition at line 205 of file qpaintbuffer_p.h.
Referenced by QPaintBufferEngine::drawImage(), QPaintBufferEngine::drawPixmap(), QPaintBufferEngine::drawTextItem(), QPaintBufferEngine::drawTiledPixmap(), QPaintBufferEngine::fill(), QPaintBufferEngine::fillRect(), QPaintBufferEngine::stroke(), and QPaintBufferEngine::transformChanged().
{
         if (count <= 0)
             return 0;
         int pos = ints.size();
         ints.resize(pos + count);
         memcpy(ints.data() + pos, data, count * sizeof(int));
         return pos;
     }
addData() [2/3]
int QPaintBufferPrivate::addData (const qreal * data, int count) inline
Definition at line 214 of file qpaintbuffer_p.h.
{
         if (count <= 0)
             return 0;
         int pos = floats.size();
         floats.resize(pos + count);
         memcpy(floats.data() + pos, data, count * sizeof(qreal));
         return pos;
     }
addData() [3/3]
int QPaintBufferPrivate::addData (const QVariant & var) inline
Definition at line 223 of file qpaintbuffer_p.h.
{
         variants << var;
         return variants.size() - 1;
     }
updateBoundingRect()
void QPaintBufferPrivate::updateBoundingRect (const QRectF & rect) inline
Definition at line 137 of file qpaintbuffer.cpp.
Referenced by QPaintBufferEngine::drawEllipse(), QPaintBufferEngine::drawImage(), QPaintBufferEngine::drawLines(), QPaintBufferEngine::drawPixmap(), QPaintBufferEngine::drawPoints(), QPaintBufferEngine::drawPolygon(), QPaintBufferEngine::drawRects(), QPaintBufferEngine::drawTextItem(), QPaintBufferEngine::drawTiledPixmap(), and QPaintBufferEngine::fillRect().
 {
     // transform to device coords and adjust for pen width
     Q_ASSERT(engine && engine->painter());
     QPainter *painter = engine->painter();
     const QTransform transform = painter->transform();
     QRectF devRect = transform.mapRect(br);
     if (penWidthAdjustment > 0) {
         devRect = devRect.adjusted(-penWidthAdjustment, -penWidthAdjustment,
                                    penWidthAdjustment, penWidthAdjustment);
     }
     if (boundingRect.isEmpty()) {
         boundingRect = devRect;
     } else {
         qreal min_x = qMin(devRect.left(), boundingRect.left());
         qreal min_y = qMin(devRect.top(), boundingRect.top());
         qreal max_x = qMax(devRect.right(), boundingRect.right());
         qreal max_y = qMax(devRect.bottom(), boundingRect.bottom());
         boundingRect = QRectF(min_x, min_y, max_x - min_x, max_y - min_y);
     }
     if (painter->hasClipping())
         boundingRect &= transform.mapRect(painter->clipRegion().boundingRect());
 }
Properties
boundingRect
QRectF QPaintBufferPrivate::boundingRect
Definition at line 294 of file qpaintbuffer_p.h.
Referenced by QPaintBuffer::boundingRect(), QPaintBuffer::metric(), operator>>(), QPaintBuffer::setBoundingRect(), and updateBoundingRect().
cache
void* QPaintBufferPrivate::cache
Definition at line 298 of file qpaintbuffer_p.h.
calculateBoundingRect
uint QPaintBufferPrivate::calculateBoundingRect
Definition at line 296 of file qpaintbuffer_p.h.
Referenced by QPaintBufferEngine::drawEllipse(), QPaintBufferEngine::drawImage(), QPaintBufferEngine::drawLines(), QPaintBufferEngine::drawPixmap(), QPaintBufferEngine::drawPoints(), QPaintBufferEngine::drawPolygon(), QPaintBufferEngine::drawRects(), QPaintBufferEngine::drawTextItem(), QPaintBufferEngine::drawTiledPixmap(), QPaintBufferEngine::fillRect(), QPaintBufferEngine::penChanged(), and QPaintBuffer::setBoundingRect().
commands
QVector<QPaintBufferCommand> QPaintBufferPrivate::commands
Definition at line 290 of file qpaintbuffer_p.h.
Referenced by QPaintBufferEngine::brushChanged(), QPaintBuffer::commandDescription(), QPaintBuffer::frameEndIndex(), QPaintBuffer::isEmpty(), operator>>(), QPaintBufferEngine::penChanged(), QPaintBuffer::processCommands(), QPaintBufferEngine::transformChanged(), and ~QPaintBufferPrivate().
engine
QPaintBufferEngine* QPaintBufferPrivate::engine
Definition at line 293 of file qpaintbuffer_p.h.
Referenced by QPaintBuffer::paintEngine(), and updateBoundingRect().
floats
QVector<qreal> QPaintBufferPrivate::floats
Definition at line 287 of file qpaintbuffer_p.h.
Referenced by QPaintBuffer::commandDescription(), and operator>>().
frames
QList<int> QPaintBufferPrivate::frames
Definition at line 291 of file qpaintbuffer_p.h.
Referenced by QPaintBuffer::frameEndIndex(), QPaintBuffer::frameStartIndex(), and operator>>().
ints
QVector<int> QPaintBufferPrivate::ints
Definition at line 286 of file qpaintbuffer_p.h.
Referenced by QPaintBuffer::commandDescription(), and operator>>().
penWidthAdjustment
qreal QPaintBufferPrivate::penWidthAdjustment
Definition at line 295 of file qpaintbuffer_p.h.
Referenced by QPaintBufferEngine::penChanged(), and updateBoundingRect().
ref
QAtomicInt QPaintBufferPrivate::ref
Definition at line 284 of file qpaintbuffer_p.h.
Referenced by QPaintBuffer::operator=(), QPaintBuffer::QPaintBuffer(), and QPaintBuffer::~QPaintBuffer().
variants
QVector<QVariant> QPaintBufferPrivate::variants
Definition at line 288 of file qpaintbuffer_p.h.
Referenced by QPaintBufferEngine::brushChanged(), QPaintBuffer::commandDescription(), operator>>(), QPaintBufferEngine::penChanged(), QPaintBufferEngine::transformChanged(), and ~QPaintBufferPrivate().
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintbuffer_p.h
/src/gui/painting/qpaintbuffer.cpp