Qt 4.8: QPropertyAnimation Class Reference
QPropertyAnimation Class Reference
The QPropertyAnimation class animates Qt properties.
#include <qpropertyanimation.h>
Public Functions
QByteArray propertyName () const
QPropertyAnimation (QObject *parent=0)
Construct a QPropertyAnimation object.
QPropertyAnimation (QObject *target, const QByteArray &propertyName, QObject *parent=0)
Construct a QPropertyAnimation object.
void setPropertyName (const QByteArray &propertyName)
void setTargetObject (QObject *target)
QObject * targetObject () const
~QPropertyAnimation ()
Destroys the QPropertyAnimation instance.
Public Functions inherited from QVariantAnimation
QVariant currentValue () const
int duration () const
QEasingCurve easingCurve () const
QVariant endValue () const
QVariant keyValueAt (qreal step) const
Returns the key frame value for the given step.
KeyValues keyValues () const
Returns the key frames of this animation.
QVariantAnimation (QObject *parent=0)
Construct a QVariantAnimation object.
void setDuration (int msecs)
void setEasingCurve (const QEasingCurve &easing)
void setEndValue (const QVariant &value)
void setKeyValueAt (qreal step, const QVariant &value)
Creates a key frame at the given step with the given value.
void setKeyValues (const KeyValues &values)
Replaces the current set of key frames with the given keyValues.
void setStartValue (const QVariant &value)
QVariant startValue () const
~QVariantAnimation ()
Destroys the animation.
Public Functions inherited from QAbstractAnimation
int currentLoop () const
int currentLoopTime () const
Returns the current time inside the current loop.
int currentTime () const
Direction direction () const
QAnimationGroup * group () const
If this animation is part of a QAnimationGroup, this function returns a pointer to the group; otherwise, it returns 0.
int loopCount () const
QAbstractAnimation (QObject *parent=0)
Constructs the QAbstractAnimation base class, and passes parent to QObject's constructor.
void setDirection (Direction direction)
void setLoopCount (int loopCount)
State state () const
int totalDuration () const
Returns the total and effective duration of the animation, including the loop count.
virtual ~QAbstractAnimation ()
Stops the animation if it's running, then destroys the QAbstractAnimation.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *event)
Reimplemented Function
void updateCurrentValue (const QVariant &value)
This virtual function is called by QVariantAnimation whenever the current value changes.
void updateState (QAbstractAnimation::State newState, QAbstractAnimation::State oldState)
If the startValue is not defined when the state of the animation changes from Stopped to Running, the current property value is used as the initial value for the animation.
Protected Functions inherited from QVariantAnimation
bool event (QEvent *event)
Reimplemented Function
virtual QVariant interpolated (const QVariant &from, const QVariant &to, qreal progress) const
This virtual function returns the linear interpolation between variants from and to, at progress, usually a value between 0 and 1.
QVariantAnimation (QVariantAnimationPrivate &dd, QObject *parent=0)
void updateCurrentTime (int)
Reimplemented Function
void updateState (QAbstractAnimation::State newState, QAbstractAnimation::State oldState)
Reimplemented Function
Protected Functions inherited from QAbstractAnimation
QAbstractAnimation (QAbstractAnimationPrivate &dd, QObject *parent=0)
virtual void updateDirection (QAbstractAnimation::Direction direction)
This virtual function is called by QAbstractAnimation when the direction of the animation is changed.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
QByteArray propertyName
the target property name for this animation
QObject * targetObject
the target QObject for this animation.
Additional Inherited Members
Public Types inherited from QVariantAnimation
typedef QVariant(* Interpolator) (const void *from, const void *to, qreal progress)
typedef QPair< qreal, QVariant > KeyValue
This is a typedef for QPair<qreal, QVariant>.
typedef QVector< KeyValue > KeyValues
This is a typedef for QVector<KeyValue>
Public Types inherited from QAbstractAnimation
enum DeletionPolicy { KeepWhenStopped = 0, DeleteWhenStopped }
enum Direction { Forward, Backward }
This enum describes the direction of the animation when in Running state.
enum State { Stopped, Paused, Running }
This enum describes the state of the animation.
Public Slots inherited from QAbstractAnimation
void pause ()
Pauses the animation.
void resume ()
Resumes the animation after it was paused.
void setCurrentTime (int msecs)
void setPaused (bool)
If paused is true, the animation is paused.
void start (QAbstractAnimation::DeletionPolicy policy=KeepWhenStopped)
Starts the animation.
void stop ()
Stops the animation.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QVariantAnimation
void valueChanged (const QVariant &value)
QVariantAnimation emits this signal whenever the current value changes.
Signals inherited from QAbstractAnimation
void currentLoopChanged (int currentLoop)
QAbstractAnimation emits this signal whenever the current loop changes.
void directionChanged (QAbstractAnimation::Direction)
QAbstractAnimation emits this signal whenever the direction has been changed.
void finished ()
QAbstractAnimation emits this signal after the animation has stopped and has reached the end.
void stateChanged (QAbstractAnimation::State newState, QAbstractAnimation::State oldState)
QAbstractAnimation emits this signal whenever the state of the animation has changed from oldState to newState.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QVariantAnimation
void qRegisterAnimationInterpolator (QVariant(*func)(const T &from, const T &to, qreal progress))
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QPropertyAnimation class animates Qt properties.
Since
4.6
QPropertyAnimation interpolates over Qt's Property System{Qt properties}. As property values are stored in QVariant, the class inherits QVariantAnimation, and supports animation of the same variant types as its super class.
A class declaring properties must be a QObject. To make it possible to animate a property, it must provide a setter (so that QPropertyAnimation can set the property's value). Note that this makes it possible to animate many of Qt's widgets. Let's look at an example:
QPropertyAnimation *animation = new QPropertyAnimation(myWidget, "geometry");
animation->setDuration(10000);
animation->setStartValue(QRect(0, 0, 100, 30));
animation->setEndValue(QRect(250, 250, 100, 30));
animation->start();
The property name and the QObject instance of which property should be animated are passed to the constructor. You can then specify the start and end value of the property. The procedure is equal for properties in classes you have implemented yourself–just check with QVariantAnimation that your QVariant type is supported.
The QVariantAnimation class description explains how to set up the animation in detail. Note, however, that if a start value is not set, the property will start at the value it had when the QPropertyAnimation instance was created.
QPropertyAnimation works like a charm on its own. For complex animations that, for instance, contain several objects, QAnimationGroup is provided. An animation group is an animation that can contain other animations, and that can manage when its animations are played. Look at QParallelAnimationGroup for an example.
See also
QVariantAnimation, QAnimationGroup, {The Animation Framework}
Definition at line 56 of file qpropertyanimation.h.
Constructors and Destructors
QPropertyAnimation() [1/2]
QPropertyAnimation::QPropertyAnimation (QObject * parent = 0)
Construct a QPropertyAnimation object.
parent is passed to QObject's constructor.
Definition at line 151 of file qpropertyanimation.cpp.
     : QVariantAnimation(*new QPropertyAnimationPrivate, parent)
 {
 }
QPropertyAnimation() [2/2]
QPropertyAnimation::QPropertyAnimation (QObject * target, const QByteArray & propertyName, QObject * parent = 0)
Construct a QPropertyAnimation object.
parent is passed to QObject's constructor. The animation changes the property propertyName on target. The default duration is 250ms.
See also
targetObject, propertyName
Definition at line 163 of file qpropertyanimation.cpp.
     : QVariantAnimation(*new QPropertyAnimationPrivate, parent)
 {
     setTargetObject(target);
     setPropertyName(propertyName);
 }
~QPropertyAnimation()
QPropertyAnimation::~QPropertyAnimation ()
Destroys the QPropertyAnimation instance.
Definition at line 173 of file qpropertyanimation.cpp.
 {
     stop();
 }
Functions
event()
bool QPropertyAnimation::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractAnimation.
Definition at line 239 of file qpropertyanimation.cpp.
 {
     return QVariantAnimation::event(event);
 }
propertyName()
QByteArray QPropertyAnimation::propertyName () const
Referenced by setPropertyName(), and setTargetObject().
setPropertyName()
void QPropertyAnimation::setPropertyName (const QByteArray & propertyName)
Definition at line 223 of file qpropertyanimation.cpp.
Referenced by QPropertyAnimation().
 {
     Q_D(QPropertyAnimation);
     if (d->state != QAbstractAnimation::Stopped) {
         qWarning("QPropertyAnimation::setPropertyName: you can't change the property name of a running animation");
         return;
     }
     d->propertyName = propertyName;
     d->updateMetaProperty();
 }
setTargetObject()
void QPropertyAnimation::setTargetObject (QObject * target)
Definition at line 192 of file qpropertyanimation.cpp.
Referenced by QPropertyAnimation().
 {
     Q_D(QPropertyAnimation);
     if (d->targetValue == target)
         return;
     if (d->state != QAbstractAnimation::Stopped) {
         qWarning("QPropertyAnimation::setTargetObject: you can't change the target of a running animation");
         return;
     }
     d->target = d->targetValue = target;
     d->updateMetaProperty();
 }
targetObject()
QObject* QPropertyAnimation::targetObject () const
Referenced by ~QPropertyAnimation().
updateCurrentValue()
void QPropertyAnimation::updateCurrentValue (const QVariant & value) protected virtual
This virtual function is called by QVariantAnimation whenever the current value changes.
value is the new, updated value. It updates the current value of the property on the target object.
See also
currentValue, currentTime
Implements QVariantAnimation.
Definition at line 251 of file qpropertyanimation.cpp.
 {
     Q_D(QPropertyAnimation);
     d->updateProperty(value);
 }
updateState()
void QPropertyAnimation::updateState (QAbstractAnimation::State newState, QAbstractAnimation::State oldState) protected virtual
If the startValue is not defined when the state of the animation changes from Stopped to Running, the current property value is used as the initial value for the animation.
Reimplemented Function
Reimplemented from QAbstractAnimation.
Definition at line 266 of file qpropertyanimation.cpp.
 {
     Q_D(QPropertyAnimation);
     if (!d->target && oldState == Stopped) {
         qWarning("QPropertyAnimation::updateState (%s): Changing state of an animation without target",
                  d->propertyName.constData());
         return;
     }
     QVariantAnimation::updateState(newState, oldState);
     QPropertyAnimation *animToStop = 0;
     {
 #ifndef QT_NO_THREAD
         QMutexLocker locker(QMutexPool::globalInstanceGet(&staticMetaObject));
 #endif
         typedef QPair<QObject *, QByteArray> QPropertyAnimationPair;
         typedef QHash<QPropertyAnimationPair, QPropertyAnimation*> QPropertyAnimationHash;
         static QPropertyAnimationHash hash;
         //here we need to use value because we need to know to which pointer
         //the animation was referring in case stopped because the target was destroyed
         QPropertyAnimationPair key(d->targetValue, d->propertyName);
         if (newState == Running) {
             d->updateMetaProperty();
             animToStop = hash.value(key, 0);
             hash.insert(key, this);
             // update the default start value
             if (oldState == Stopped) {
                 d->setDefaultStartEndValue(d->targetValue->property(d->propertyName.constData()));
                 //let's check if we have a start value and an end value
                 if (!startValue().isValid() && (d->direction == Backward || !d->defaultStartEndValue.isValid())) {
                     qWarning("QPropertyAnimation::updateState (%s, %s, %s): starting an animation without start value",
                              d->propertyName.constData(), d->target.data()->metaObject()->className(),
                              qPrintable(d->target.data()->objectName()));
                 }
                 if (!endValue().isValid() && (d->direction == Forward || !d->defaultStartEndValue.isValid())) {
                     qWarning("QPropertyAnimation::updateState (%s, %s, %s): starting an animation without end value",
                              d->propertyName.constData(), d->target.data()->metaObject()->className(),
                              qPrintable(d->target.data()->objectName()));
                 }
             }
         } else if (hash.value(key) == this) {
             hash.remove(key);
         }
     }
     //we need to do that after the mutex was unlocked
     if (animToStop) {
         // try to stop the top level group
         QAbstractAnimation *current = animToStop;
         while (current->group() && current->state() != Stopped)
             current = current->group();
         current->stop();
     }
 }
Properties
propertyName
QByteArray QPropertyAnimation::propertyName private
the target property name for this animation
This property defines the target property name for this animation. The property name is required for the animation to operate.
Definition at line 59 of file qpropertyanimation.h.
Referenced by QStateMachinePrivate::initializeAnimation().
targetObject
QObject * QPropertyAnimation::targetObject private
the target QObject for this animation.
This property defines the target QObject for this animation.
Definition at line 60 of file qpropertyanimation.h.
Referenced by QWidgetAnimator::animationFinished(), and QStateMachinePrivate::initializeAnimation().
The documentation for this class was generated from the following files:
/src/corelib/animation/qpropertyanimation.h
/src/corelib/animation/qpropertyanimation.cpp