Qt 4.8: QAbstractFileEngine Class Reference
QAbstractFileEngine Class Reference
The QAbstractFileEngine class provides an abstraction for accessing the filesystem.
#include <qabstractfileengine.h>
Classes
class ExtensionOption
provides an extended input argument to QAbstractFileEngine's extension support.
class ExtensionReturn
provides an extended output argument to QAbstractFileEngine's extension support.
class MapExtensionOption
class MapExtensionReturn
class UnMapExtensionOption
Public Types
enum Extension { AtEndExtension, FastReadLineExtension, MapExtension, UnMapExtension }
This enum describes the types of extensions that the file engine can support.
enum FileFlag {
ReadOwnerPerm = 0x4000, WriteOwnerPerm = 0x2000, ExeOwnerPerm = 0x1000, ReadUserPerm = 0x0400,
WriteUserPerm = 0x0200, ExeUserPerm = 0x0100, ReadGroupPerm = 0x0040, WriteGroupPerm = 0x0020,
ExeGroupPerm = 0x0010, ReadOtherPerm = 0x0004, WriteOtherPerm = 0x0002, ExeOtherPerm = 0x0001,
LinkType = 0x10000, FileType = 0x20000, DirectoryType = 0x40000, BundleType = 0x80000,
HiddenFlag = 0x0100000, LocalDiskFlag = 0x0200000, ExistsFlag = 0x0400000, RootFlag = 0x0800000,
Refresh = 0x1000000, PermsMask = 0x0000FFFF, TypesMask = 0x000F0000, FlagsMask = 0x0FF00000,
FileInfoAll = FlagsMask | PermsMask | TypesMask
}
The permissions and types of a file, suitable for OR'ing together.
enum FileName {
DefaultName, BaseName, PathName, AbsoluteName,
AbsolutePathName, LinkName, CanonicalName, CanonicalPathName,
BundleName, NFileNames = 9
}
These values are used to request a file name in a particular format.
enum FileOwner { OwnerUser, OwnerGroup }
enum FileTime { CreationTime, ModificationTime, AccessTime }
These are used by the fileTime() function.
typedef QAbstractFileEngineIterator Iterator
Public Functions
bool atEnd () const
Returns true if the current position is at the end of the file; otherwise, returns false.
virtual Iterator * beginEntryList (QDir::Filters filters, const QStringList &filterNames)
Returns an instance of a QAbstractFileEngineIterator using filters for entry filtering and filterNames for name filtering.
virtual bool caseSensitive () const
Should return true if the underlying file system is case-sensitive; otherwise return false.
virtual bool close ()
Closes the file, returning true if successful; otherwise returns false.
virtual bool copy (const QString &newName)
Copies the contents of this file to a file with the name newName.
virtual Iterator * endEntryList ()
virtual QStringList entryList (QDir::Filters filters, const QStringList &filterNames) const
Requests that a list of all the files matching the filters list based on the filterNames in the file engine's directory are returned.
QFile::FileError error () const
Returns the QFile::FileError that resulted from the last failed operation.
QString errorString () const
Returns the human-readable message appropriate to the current error reported by error().
virtual bool extension (Extension extension, const ExtensionOption *option=0, ExtensionReturn *output=0)
This virtual function can be reimplemented in a QAbstractFileEngine subclass to provide support for extensions.
virtual FileFlags fileFlags (FileFlags type=FileInfoAll) const
This function should return the set of OR'd flags that are true for the file engine's file, and that are in the type's OR'd members.
virtual QString fileName (FileName file=DefaultName) const
Return the file engine's current file name in the format specified by file.
virtual QDateTime fileTime (FileTime time) const
If time is CreationTime, return when the file was created.
virtual bool flush ()
Flushes the open file, returning true if successful; otherwise returns false.
virtual int handle () const
Returns the native file handle for this file engine.
virtual bool isRelativePath () const
Return true if the file referred to by this file engine has a relative path; otherwise return false.
virtual bool isSequential () const
Returns true if the file is a sequential access device; returns false if the file is a direct access device.
virtual bool link (const QString &newName)
Creates a link from the file currently specified by fileName() to newName.
uchar * map (qint64 offset, qint64 size, QFile::MemoryMapFlags flags)
Maps size bytes of the file into memory starting at offset.
virtual bool mkdir (const QString &dirName, bool createParentDirectories) const
Requests that the directory dirName be created.
virtual bool open (QIODevice::OpenMode openMode)
Opens the file in the specified mode.
virtual QString owner (FileOwner) const
If owner is OwnerUser return the name of the user who owns the file.
virtual uint ownerId (FileOwner) const
If owner is OwnerUser return the ID of the user who owns the file.
virtual qint64 pos () const
Returns the current file position.
virtual qint64 read (char *data, qint64 maxlen)
Reads a number of characters from the file into data.
virtual qint64 readLine (char *data, qint64 maxlen)
This function reads one line, terminated by a '
' character, from the file info data.
virtual bool remove ()
Requests that the file is deleted from the file system.
virtual bool rename (const QString &newName)
Requests that the file be renamed to newName in the file system.
virtual bool rmdir (const QString &dirName, bool recurseParentDirectories) const
Requests that the directory dirName is deleted from the file system.
virtual bool seek (qint64 pos)
Sets the file position to the given offset.
virtual void setFileName (const QString &file)
Sets the file engine's file name to file.
virtual bool setPermissions (uint perms)
Requests that the file's permissions be set to perms.
virtual bool setSize (qint64 size)
Requests that the file be set to size size.
virtual qint64 size () const
Returns the size of the file.
virtual bool supportsExtension (Extension extension) const
This virtual function returns true if the file engine supports extension; otherwise, false is returned.
bool unmap (uchar *ptr)
Unmaps the memory address.
virtual qint64 write (const char *data, qint64 len)
Writes len bytes from data to the file.
virtual ~QAbstractFileEngine ()
Destroys the QAbstractFileEngine.
Static Public Functions
static QAbstractFileEngine * create (const QString &fileName)
Creates and returns a QAbstractFileEngine suitable for processing fileName.
Protected Functions
QAbstractFileEngine ()
Constructs a new QAbstractFileEngine that does not refer to any file or directory.
QAbstractFileEngine (QAbstractFileEnginePrivate &)
Constructs a QAbstractFileEngine.
void setError (QFile::FileError error, const QString &str)
Sets the error type to error, and the error string to errorString.
Protected Variables
QScopedPointer< QAbstractFileEnginePrivate > d_ptr
Related Functions
(Note that these are not member functions.)
Iterator
Synonym for QAbstractFileEngineIterator.
Detailed Description
The QAbstractFileEngine class provides an abstraction for accessing the filesystem.
Note
This class or function is reentrant.
Since
4.1
The QDir, QFile, and QFileInfo classes all make use of a QAbstractFileEngine internally. If you create your own QAbstractFileEngine subclass (and register it with Qt by creating a QAbstractFileEngineHandler subclass), your file engine will be used when the path is one that your file engine handles.
A QAbstractFileEngine refers to one file or one directory. If the referent is a file, the setFileName(), rename(), and remove() functions are applicable. If the referent is a directory the mkdir(), rmdir(), and entryList() functions are applicable. In all cases the caseSensitive(), isRelativePath(), fileFlags(), ownerId(), owner(), and fileTime() functions are applicable.
A QAbstractFileEngine subclass can be created to do synchronous network I/O based file system operations, local file system operations, or to operate as a resource system to access file based resources.
See also
QAbstractFileEngineHandler
Definition at line 63 of file qabstractfileengine.h.
Typedefs
Iterator
typedef QAbstractFileEngineIterator QAbstractFileEngine::Iterator
Definition at line 147 of file qabstractfileengine.h.
Enumerations
Extension
enum QAbstractFileEngine::Extension
This enum describes the types of extensions that the file engine can support.
Since
4.3
Before using these extensions, you must verify that the extension is supported (i.e., call supportsExtension()).
AtEndExtension Whether the current file position is at the end of the file or not. This extension allows file engines that implement local buffering to report end-of-file status without having to check the size of the file. It is also useful for sequential files, where the size of the file cannot be used to determine whether or not you have reached the end. This extension returns true if the file is at the end; otherwise it returns false. The input and output arguments to extension() are ignored.
FastReadLineExtension Whether the file engine provides a fast implementation for readLine() or not. If readLine() remains unimplemented in the file engine, QAbstractFileEngine will provide an implementation based on calling read() repeatedly. If supportsExtension() returns false for this extension, however, QIODevice can provide a faster implementation by making use of its internal buffer. For engines that already provide a fast readLine() implementation, returning false for this extension can avoid unnnecessary double-buffering in QIODevice.
MapExtension Whether the file engine provides the ability to map a file to memory.
UnMapExtension Whether the file engine provides the ability to unmap memory that was previously mapped.
Enumerator
AtEndExtension
FastReadLineExtension
MapExtension
UnMapExtension
Definition at line 158 of file qabstractfileengine.h.
                    {
         AtEndExtension,
         FastReadLineExtension,
         MapExtension,
         UnMapExtension
     };
FileFlag
enum QAbstractFileEngine::FileFlag
The permissions and types of a file, suitable for OR'ing together.
ReadOwnerPerm The owner of the file has permission to read it.
WriteOwnerPerm The owner of the file has permission to write to it.
ExeOwnerPerm The owner of the file has permission to execute it.
ReadUserPerm The current user has permission to read the file.
WriteUserPerm The current user has permission to write to the file.
ExeUserPerm The current user has permission to execute the file.
ReadGroupPerm Members of the current user's group have permission to read the file.
WriteGroupPerm Members of the current user's group have permission to write to the file.
ExeGroupPerm Members of the current user's group have permission to execute the file.
ReadOtherPerm All users have permission to read the file.
WriteOtherPerm All users have permission to write to the file.
ExeOtherPerm All users have permission to execute the file.
LinkType The file is a link to another file (or link) in the file system (i.e. not a file or directory).
FileType The file is a regular file to the file system (i.e. not a link or directory)
BundleType The file is a Mac OS X bundle implies DirectoryType
DirectoryType The file is a directory in the file system (i.e. not a link or file).
HiddenFlag The file is hidden.
ExistsFlag The file actually exists in the file system.
RootFlag The file or the file pointed to is the root of the filesystem.
LocalDiskFlag The file resides on the local disk and can be passed to standard file functions.
Refresh Passing this flag will force the file engine to refresh all flags.
PermsMask
TypesMask
FlagsMask
FileInfoAll
See also
fileFlags(), setFileName()
Enumerator
ReadOwnerPerm
WriteOwnerPerm
ExeOwnerPerm
ReadUserPerm
WriteUserPerm
ExeUserPerm
ReadGroupPerm
WriteGroupPerm
ExeGroupPerm
ReadOtherPerm
WriteOtherPerm
ExeOtherPerm
LinkType
FileType
DirectoryType
BundleType
HiddenFlag
LocalDiskFlag
ExistsFlag
RootFlag
Refresh
PermsMask
TypesMask
FlagsMask
FileInfoAll
Definition at line 66 of file qabstractfileengine.h.
                   {
         //perms (overlaps the QFile::Permission)
         ReadOwnerPerm = 0x4000, WriteOwnerPerm = 0x2000, ExeOwnerPerm = 0x1000,
         ReadUserPerm  = 0x0400, WriteUserPerm  = 0x0200, ExeUserPerm  = 0x0100,
         ReadGroupPerm = 0x0040, WriteGroupPerm = 0x0020, ExeGroupPerm = 0x0010,
         ReadOtherPerm = 0x0004, WriteOtherPerm = 0x0002, ExeOtherPerm = 0x0001,
         //types
         LinkType      = 0x10000,
         FileType      = 0x20000,
         DirectoryType = 0x40000,
         BundleType    = 0x80000,
         //flags
         HiddenFlag     = 0x0100000,
         LocalDiskFlag  = 0x0200000,
         ExistsFlag     = 0x0400000,
         RootFlag       = 0x0800000,
         Refresh        = 0x1000000,
         //masks
         PermsMask  = 0x0000FFFF,
         TypesMask  = 0x000F0000,
         FlagsMask  = 0x0FF00000,
         FileInfoAll = FlagsMask | PermsMask | TypesMask
     };
FileName
enum QAbstractFileEngine::FileName
These values are used to request a file name in a particular format.
DefaultName The same filename that was passed to the QAbstractFileEngine.
BaseName The name of the file excluding the path.
PathName The path to the file excluding the base name.
AbsoluteName The absolute path to the file (including the base name).
AbsolutePathName The absolute path to the file (excluding the base name).
LinkName The full file name of the file that this file is a link to. (This will be empty if this file is not a link.)
CanonicalName Often very similar to LinkName. Will return the true path to the file.
CanonicalPathName Same as CanonicalName, excluding the base name.
BundleName Returns the name of the bundle implies BundleType is set.
NFileNames
See also
fileName(), setFileName()
Enumerator
DefaultName
BaseName
PathName
AbsoluteName
AbsolutePathName
LinkName
CanonicalName
CanonicalPathName
BundleName
NFileNames
Definition at line 94 of file qabstractfileengine.h.
                   {
         DefaultName,
         BaseName,
         PathName,
         AbsoluteName,
         AbsolutePathName,
         LinkName,
         CanonicalName,
         CanonicalPathName,
         BundleName,
         NFileNames = 9
     };
FileOwner
enum QAbstractFileEngine::FileOwner
OwnerUser The user who owns the file.
OwnerGroup The group who owns the file.
See also
owner(), ownerId(), setFileName()
Enumerator
OwnerUser
OwnerGroup
Definition at line 106 of file qabstractfileengine.h.
                    {
         OwnerUser,
         OwnerGroup
     };
FileTime
enum QAbstractFileEngine::FileTime
These are used by the fileTime() function.
CreationTime When the file was created.
ModificationTime When the file was most recently modified.
AccessTime When the file was most recently accessed (e.g. read or written to).
See also
setFileName()
Enumerator
CreationTime
ModificationTime
AccessTime
Definition at line 110 of file qabstractfileengine.h.
                   {
         CreationTime,
         ModificationTime,
         AccessTime
     };
Constructors and Destructors
~QAbstractFileEngine()
QAbstractFileEngine::~QAbstractFileEngine () virtual
Destroys the QAbstractFileEngine.
Definition at line 388 of file qabstractfileengine.cpp.
 {
 }
QAbstractFileEngine() [1/2]
QAbstractFileEngine::QAbstractFileEngine () protected
Constructs a new QAbstractFileEngine that does not refer to any file or directory.
See also
setFileName()
Definition at line 367 of file qabstractfileengine.cpp.
                                          : d_ptr(new QAbstractFileEnginePrivate)
 {
     d_ptr->q_ptr = this;
 }
QAbstractFileEngine() [2/2]
QAbstractFileEngine::QAbstractFileEngine (QAbstractFileEnginePrivate & dd) protected
Constructs a QAbstractFileEngine.
Warning
This function is not part of the public interface.
Definition at line 380 of file qabstractfileengine.cpp.
                                                                        : d_ptr(&dd)
 {
     d_ptr->q_ptr = this;
 }
Functions
atEnd()
bool QAbstractFileEngine::atEnd () const
Returns true if the current position is at the end of the file; otherwise, returns false.
Since
4.3
This function bases its behavior on calling extension() with AtEndExtension. If the engine does not support this extension, false is returned.
See also
extension(), supportsExtension(), QFile::atEnd()
Definition at line 777 of file qabstractfileengine.cpp.
 {
     return const_cast<QAbstractFileEngine *>(this)->extension(AtEndExtension);
 }
beginEntryList()
QAbstractFileEngine::Iterator * QAbstractFileEngine::beginEntryList (QDir::Filters filters, const QStringList & filterNames) virtual
Returns an instance of a QAbstractFileEngineIterator using filters for entry filtering and filterNames for name filtering.
This function is called by QDirIterator to initiate directory iteration.
QDirIterator takes ownership of the returned instance, and deletes it when it's done.
See also
QDirIterator
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 1097 of file qabstractfileengine.cpp.
Referenced by QDirIteratorPrivate::pushDirectory().
 {
     Q_UNUSED(filters);
     Q_UNUSED(filterNames);
     return 0;
 }
caseSensitive()
bool QAbstractFileEngine::caseSensitive () const virtual
Should return true if the underlying file system is case-sensitive; otherwise return false.
This virtual function must be reimplemented by all subclasses.
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 592 of file qabstractfileengine.cpp.
Referenced by QFileInfo::operator==(), and QDir::operator==().
 {
     return false;
 }
close()
bool QAbstractFileEngine::close () virtual
Closes the file, returning true if successful; otherwise returns false.
The default implementation always returns false.
Reimplemented in QTemporaryFileEngine, QResourceFileEngine, and QFSFileEngine.
Definition at line 415 of file qabstractfileengine.cpp.
 {
     return false;
 }
copy()
bool QAbstractFileEngine::copy (const QString & newName) virtual
Copies the contents of this file to a file with the name newName.
Returns true on success; otherwise, false is returned.
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 498 of file qabstractfileengine.cpp.
 {
     Q_UNUSED(newName);
     return false;
 }
create()
QAbstractFileEngine * QAbstractFileEngine::create (const QString & fileName) static
Creates and returns a QAbstractFileEngine suitable for processing fileName.
You should not need to call this function; use QFile, QFileInfo or QDir directly instead.
If you reimplemnt this function, it should only return file engines that knows how to handle fileName; otherwise, it should return 0.
See also
QAbstractFileEngineHandler
Definition at line 208 of file qabstractfileengine.cpp.
Referenced by QFile::fileEngine().
 {
     QFileSystemEntry entry(fileName);
     QFileSystemMetaData metaData;
     QAbstractFileEngine *engine = QFileSystemEngine::resolveEntryAndCreateLegacyEngine(entry, metaData);
 #ifndef QT_NO_FSFILEENGINE
     if (!engine)
         // fall back to regular file engine
         return new QFSFileEngine(entry.filePath());
 #endif
     return engine;
 }
endEntryList()
QAbstractFileEngine::Iterator * QAbstractFileEngine::endEntryList () virtual
Warning
This function is not part of the public interface.
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 1107 of file qabstractfileengine.cpp.
 {
     return 0;
 }
entryList()
QStringList QAbstractFileEngine::entryList (QDir::Filters filters, const QStringList & filterNames) const virtual
Requests that a list of all the files matching the filters list based on the filterNames in the file engine's directory are returned.
Should return an empty list if the file engine refers to a file rather than a directory, or if the directory is unreadable or does not exist or if nothing matches the specifications.
This virtual function must be reimplemented by all subclasses.
See also
setFileName()
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 623 of file qabstractfileengine.cpp.
Referenced by QFSFileEngine::entryList(), and QResourceFileEngine::entryList().
 {
     QStringList ret;
     QDirIterator it(fileName(), filterNames, filters);
     while (it.hasNext()) {
         it.next();
         ret << it.fileName();
     }
     return ret;
 }
error()
QFile::FileError QAbstractFileEngine::error () const
Returns the QFile::FileError that resulted from the last failed operation.
If QFile::UnspecifiedError is returned, QFile will use its own idea of the error status.
See also
QFile::FileError, errorString()
Definition at line 1272 of file qabstractfileengine.cpp.
Referenced by QTemporaryFileEngine::open().
 {
     Q_D(const QAbstractFileEngine);
     return d->fileError;
 }
errorString()
QString QAbstractFileEngine::errorString () const
Returns the human-readable message appropriate to the current error reported by error().
If no suitable string is available, an empty string is returned.
See also
error()
Definition at line 1285 of file qabstractfileengine.cpp.
 {
     Q_D(const QAbstractFileEngine);
     return d->errorString;
 }
extension()
bool QAbstractFileEngine::extension (Extension extension, const ExtensionOption * option = 0, ExtensionReturn * output = 0) virtual
This virtual function can be reimplemented in a QAbstractFileEngine subclass to provide support for extensions.
Since
4.3
The option argument is provided as input to the extension, and this function can store output results in output.
The behavior of this function is determined by extension; see the Extension documentation for details.
You can call supportsExtension() to check if an extension is supported by the file engine.
By default, no extensions are supported, and this function returns false.
See also
supportsExtension(), Extension
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 1239 of file qabstractfileengine.cpp.
Referenced by atEnd(), map(), and unmap().
 {
     Q_UNUSED(extension);
     Q_UNUSED(option);
     Q_UNUSED(output);
     return false;
 }
fileFlags()
QAbstractFileEngine::FileFlags QAbstractFileEngine::fileFlags (FileFlags type = FileInfoAll) const virtual
This function should return the set of OR'd flags that are true for the file engine's file, and that are in the type's OR'd members.
In your reimplementation you can use the type argument as an optimization hint and only return the OR'd set of members that are true and that match those in type; in other words you can ignore any members not mentioned in type, thus avoiding some potentially expensive lookups or system calls.
This virtual function must be reimplemented by all subclasses.
See also
setFileName()
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 649 of file qabstractfileengine.cpp.
Referenced by _q_checkEntry(), QFontDatabase::addApplicationFont(), QDirPrivate::exists(), QFreetypeFace::getFace(), QFileInfoPrivate::getFileFlags(), QDir::isReadable(), QDir::isRoot(), and QFile::permissions().
 {
     Q_UNUSED(type);
     return 0;
 }
fileName()
QString QAbstractFileEngine::fileName (FileName file = DefaultName) const virtual
Return the file engine's current file name in the format specified by file.
If you don't handle some FileName possibilities, return the file name set in setFileName() when an unhandled format is requested.
This virtual function must be reimplemented by all subclasses.
See also
setFileName(), FileName
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 684 of file qabstractfileengine.cpp.
Referenced by QDir::canonicalPath(), entryList(), QTemporaryFile::fileName(), QFile::fileName(), QFileInfoPrivate::getFileName(), QDir::makeAbsolute(), QFile::readLink(), and QDirPrivate::resolveAbsoluteEntry().
 {
     Q_UNUSED(file);
     return QString();
 }
fileTime()
QDateTime QAbstractFileEngine::fileTime (FileTime time) const virtual
If time is CreationTime, return when the file was created.
If time is ModificationTime, return when the file was most recently modified. If time is AccessTime, return when the file was most recently accessed (e.g. read or written). If the time cannot be determined return QDateTime() (an invalid date time).
This virtual function must be reimplemented by all subclasses.
See also
setFileName(), QDateTime, QDateTime::isValid(), FileTime
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 733 of file qabstractfileengine.cpp.
Referenced by QFileInfoPrivate::getFileTime().
 {
     Q_UNUSED(time);
     return QDateTime();
 }
flush()
bool QAbstractFileEngine::flush () virtual
Flushes the open file, returning true if successful; otherwise returns false.
The default implementation always returns false.
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 426 of file qabstractfileengine.cpp.
 {
     return false;
 }
handle()
int QAbstractFileEngine::handle () const virtual
Returns the native file handle for this file engine.
This handle must be used with care; its value and type are platform specific, and using it will most likely lead to non-portable code.
Reimplemented in QFSFileEngine.
Definition at line 757 of file qabstractfileengine.cpp.
 {
     return -1;
 }
isRelativePath()
bool QAbstractFileEngine::isRelativePath () const virtual
Return true if the file referred to by this file engine has a relative path; otherwise return false.
This virtual function must be reimplemented by all subclasses.
See also
setFileName()
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 605 of file qabstractfileengine.cpp.
Referenced by QDir::isRelative().
 {
     return false;
 }
isSequential()
bool QAbstractFileEngine::isSequential () const virtual
Returns true if the file is a sequential access device; returns false if the file is a direct access device.
Operations involving size() and seek(int) are not valid on sequential devices.
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 476 of file qabstractfileengine.cpp.
 {
     return false;
 }
link()
bool QAbstractFileEngine::link (const QString & newName) virtual
Creates a link from the file currently specified by fileName() to newName.
What a link is depends on the underlying filesystem (be it a shortcut on Windows or a symbolic link on Unix). Returns true if successful; otherwise returns false.
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 525 of file qabstractfileengine.cpp.
 {
     Q_UNUSED(newName);
     return false;
 }
map()
uchar * QAbstractFileEngine::map (qint64 offset, qint64 size, QFile::MemoryMapFlags flags)
Maps size bytes of the file into memory starting at offset.
Since
4.4
Returns a pointer to the memory if successful; otherwise returns false if, for example, an error occurs.
This function bases its behavior on calling extension() with MapExtensionOption. If the engine does not support this extension, 0 is returned.
flags is currently not used, but could be used in the future.
See also
unmap(), supportsExtension()
Definition at line 801 of file qabstractfileengine.cpp.
 {
     MapExtensionOption option;
     option.offset = offset;
     option.size = size;
     option.flags = flags;
     MapExtensionReturn r;
     if (!extension(MapExtension, &option, &r))
         return 0;
     return r.address;
 }
mkdir()
bool QAbstractFileEngine::mkdir (const QString & dirName, bool createParentDirectories) const virtual
Requests that the directory dirName be created.
If createParentDirectories is true, then any sub-directories in dirName that don't exist must be created. If createParentDirectories is false then any sub-directories in dirName must already exist for the function to succeed. If the operation succeeds return true; otherwise return false.
This virtual function must be reimplemented by all subclasses.
See also
setFileName() rmdir() isRelativePath()
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 543 of file qabstractfileengine.cpp.
Referenced by QDir::mkdir(), and QDir::mkpath().
 {
     Q_UNUSED(dirName);
     Q_UNUSED(createParentDirectories);
     return false;
 }
open()
bool QAbstractFileEngine::open (QIODevice::OpenMode mode) virtual
Opens the file in the specified mode.
Returns true if the file was successfully opened; otherwise returns false.
The mode is an OR combination of QIODevice::OpenMode and QIODevice::HandlingMode values.
Reimplemented in QTemporaryFileEngine, QResourceFileEngine, and QFSFileEngine.
Definition at line 404 of file qabstractfileengine.cpp.
 {
     Q_UNUSED(openMode);
     return false;
 }
owner()
QString QAbstractFileEngine::owner (FileOwner owner) const virtual
If owner is OwnerUser return the name of the user who owns the file.
If owner is OwnerGroup return the name of the group that own the file. If you can't determine the owner return QString().
This virtual function must be reimplemented by all subclasses.
See also
ownerId() setFileName(), FileOwner
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 715 of file qabstractfileengine.cpp.
Referenced by QFileInfoPrivate::getFileOwner().
 {
     Q_UNUSED(owner);
     return QString();
 }
ownerId()
uint QAbstractFileEngine::ownerId (FileOwner owner) const virtual
If owner is OwnerUser return the ID of the user who owns the file.
If owner is OwnerGroup return the ID of the group that own the file. If you can't determine the owner return -2.
This virtual function must be reimplemented by all subclasses.
See also
owner() setFileName(), FileOwner
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 699 of file qabstractfileengine.cpp.
 {
     Q_UNUSED(owner);
     return 0;
 }
pos()
qint64 QAbstractFileEngine::pos () const virtual
Returns the current file position.
This is the position of the data read/write head of the file.
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 444 of file qabstractfileengine.cpp.
 {
     return 0;
 }
read()
qint64 QAbstractFileEngine::read (char * data, qint64 maxlen) virtual
Reads a number of characters from the file into data.
At most maxlen characters will be read.
Returns -1 if a fatal error occurs, or 0 if there are no bytes to read.
Reimplemented in QFSFileEngine, and QResourceFileEngine.
Definition at line 1119 of file qabstractfileengine.cpp.
 {
     Q_UNUSED(data);
     Q_UNUSED(maxlen);
     return -1;
 }
readLine()
qint64 QAbstractFileEngine::readLine (char * data, qint64 maxlen) virtual
This function reads one line, terminated by a '
' character, from the file info data.
At most maxlen characters will be read. The end-of-line character is included.
Reimplemented in QFSFileEngine.
Definition at line 1142 of file qabstractfileengine.cpp.
 {
     qint64 readSoFar = 0;
     while (readSoFar < maxlen) {
         char c;
         qint64 readResult = read(&c, 1);
         if (readResult <= 0)
             return (readSoFar > 0) ? readSoFar : -1;
         ++readSoFar;
         *data++ = c;
         if (c == '\n')
             return readSoFar;
     }
     return readSoFar;
 }
remove()
bool QAbstractFileEngine::remove () virtual
Requests that the file is deleted from the file system.
If the operation succeeds return true; otherwise return false.
This virtual function must be reimplemented by all subclasses.
See also
setFileName() rmdir()
Reimplemented in QTemporaryFileEngine, QResourceFileEngine, and QFSFileEngine.
Definition at line 489 of file qabstractfileengine.cpp.
 {
     return false;
 }
rename()
bool QAbstractFileEngine::rename (const QString & newName) virtual
Requests that the file be renamed to newName in the file system.
If the operation succeeds return true; otherwise return false.
This virtual function must be reimplemented by all subclasses.
See also
setFileName()
Reimplemented in QTemporaryFileEngine, QResourceFileEngine, and QFSFileEngine.
Definition at line 513 of file qabstractfileengine.cpp.
 {
     Q_UNUSED(newName);
     return false;
 }
rmdir()
bool QAbstractFileEngine::rmdir (const QString & dirName, bool recurseParentDirectories) const virtual
Requests that the directory dirName is deleted from the file system.
When recurseParentDirectories is true, then any empty parent-directories in dirName must also be deleted. If recurseParentDirectories is false, only the dirName leaf-node should be deleted. In most file systems a directory cannot be deleted using this function if it is non-empty. If the operation succeeds return true; otherwise return false.
This virtual function must be reimplemented by all subclasses.
See also
setFileName() remove() mkdir() isRelativePath()
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 563 of file qabstractfileengine.cpp.
Referenced by QDir::rmdir(), and QDir::rmpath().
 {
     Q_UNUSED(dirName);
     Q_UNUSED(recurseParentDirectories);
     return false;
 }
seek()
bool QAbstractFileEngine::seek (qint64 offset) virtual
Sets the file position to the given offset.
Returns true if the position was successfully set; otherwise returns false.
The offset is from the beginning of the file, unless the file is sequential.
See also
isSequential()
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 463 of file qabstractfileengine.cpp.
Referenced by QFile::open().
 {
     Q_UNUSED(pos);
     return false;
 }
setError()
void QAbstractFileEngine::setError (QFile::FileError error, const QString & errorString) protected
Sets the error type to error, and the error string to errorString.
Call this function to set the error values returned by the higher-level classes.
See also
QFile::error(), QIODevice::errorString(), QIODevice::setErrorString()
Definition at line 1298 of file qabstractfileengine.cpp.
Referenced by QTemporaryFileEngine::close(), QFSFileEnginePrivate::longFileName(), QFSFileEngine::open(), and QTemporaryFileEngine::open().
 {
     Q_D(QAbstractFileEngine);
     d->fileError = error;
     d->errorString = errorString;
 }
setFileName()
void QAbstractFileEngine::setFileName (const QString & file) virtual
Sets the file engine's file name to file.
This file name is the file that the rest of the virtual functions will operate on.
This virtual function must be reimplemented by all subclasses.
See also
rename()
Reimplemented in QTemporaryFileEngine, QFSFileEngine, and QResourceFileEngine.
Definition at line 747 of file qabstractfileengine.cpp.
Referenced by QDirIteratorPrivate::pushDirectory().
 {
     Q_UNUSED(file);
 }
setPermissions()
bool QAbstractFileEngine::setPermissions (uint perms) virtual
Requests that the file's permissions be set to perms.
The argument perms will be set to the OR-ed together combination of QAbstractFileEngine::FileInfo, with only the QAbstractFileEngine::PermsMask being honored. If the operations succceeds return true; otherwise return false;
This virtual function must be reimplemented by all subclasses.
See also
size()
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 666 of file qabstractfileengine.cpp.
 {
     Q_UNUSED(perms);
     return false;
 }
setSize()
bool QAbstractFileEngine::setSize (qint64 size) virtual
Requests that the file be set to size size.
If size is larger than the current file then it is filled with 0's, if smaller it is simply truncated. If the operations succceeds return true; otherwise return false;
This virtual function must be reimplemented by all subclasses.
See also
size()
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 580 of file qabstractfileengine.cpp.
 {
     Q_UNUSED(size);
     return false;
 }
size()
qint64 QAbstractFileEngine::size () const virtual
Returns the size of the file.
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 434 of file qabstractfileengine.cpp.
Referenced by map(), and QFile::size().
 {
     return 0;
 }
supportsExtension()
bool QAbstractFileEngine::supportsExtension (Extension extension) const virtual
This virtual function returns true if the file engine supports extension; otherwise, false is returned.
Since
4.3
By default, no extensions are supported.
See also
extension()
Reimplemented in QResourceFileEngine, and QFSFileEngine.
Definition at line 1259 of file qabstractfileengine.cpp.
 {
     Q_UNUSED(extension);
     return false;
 }
unmap()
bool QAbstractFileEngine::unmap (uchar * address)
Unmaps the memory address.
Since
4.4
Returns true if the unmap succeeds; otherwise returns false.
This function bases its behavior on calling extension() with UnMapExtensionOption. If the engine does not support this extension, false is returned.
See also
map(), supportsExtension()
Definition at line 828 of file qabstractfileengine.cpp.
Referenced by QFSFileEngine::~QFSFileEngine().
 {
     UnMapExtensionOption options;
     options.address = address;
     return extension(UnMapExtension, &options);
 }
write()
qint64 QAbstractFileEngine::write (const char * data, qint64 len) virtual
Writes len bytes from data to the file.
Returns the number of characters written on success; otherwise returns -1.
Reimplemented in QFSFileEngine, and QResourceFileEngine.
Definition at line 1130 of file qabstractfileengine.cpp.
Referenced by _qfile_writeData().
 {
     Q_UNUSED(data);
     Q_UNUSED(len);
     return -1;
 }
Friends and Related Functions
Iterator()
Iterator related
Synonym for QAbstractFileEngineIterator.
Since
4.3
Properties
d_ptr
QScopedPointer<QAbstractFileEnginePrivate> QAbstractFileEngine::d_ptr protected
Definition at line 197 of file qabstractfileengine.h.
Referenced by QAbstractFileEngine().
The documentation for this class was generated from the following files:
/src/corelib/io/qabstractfileengine.h
/src/corelib/io/qabstractfileengine.cpp