Qt 4.8: QWaylandWindowManagerIntegration Class Reference
QWaylandWindowManagerIntegration Class Reference
#include <qwaylandwindowmanagerintegration.h>
Public Functions
void authenticateWithToken (const QByteArray &token=QByteArray())
void mapClientToProcess (long long processId)
void mapSurfaceToProcess (struct wl_surface *surface, long long processId)
QWaylandWindowManagerIntegration (QWaylandDisplay *waylandDisplay)
struct wl_windowmanager * windowManager () const
virtual ~QWaylandWindowManagerIntegration ()
Static Public Functions
static QWaylandWindowManagerIntegration * createIntegration (QWaylandDisplay *waylandDisplay)
Static Private Functions
static void wlHandleListenerGlobal (wl_display *display, uint32_t id, const char *interface, uint32_t version, void *data)
Properties
QWaylandDisplay * mWaylandDisplay
struct wl_windowmanager * mWaylandWindowManager
Detailed Description
Definition at line 49 of file qwaylandwindowmanagerintegration.h.
Constructors and Destructors
QWaylandWindowManagerIntegration()
QWaylandWindowManagerIntegration::QWaylandWindowManagerIntegration (QWaylandDisplay * waylandDisplay) explicit
Definition at line 52 of file qwaylandwindowmanagerintegration.cpp.
Referenced by createIntegration().
     : mWaylandDisplay(waylandDisplay)
     , mWaylandWindowManager(0)
 {
     wl_display_add_global_listener(mWaylandDisplay->wl_display(),
                                    QWaylandWindowManagerIntegration::wlHandleListenerGlobal,
                                    this);
 }
~QWaylandWindowManagerIntegration()
QWaylandWindowManagerIntegration::~QWaylandWindowManagerIntegration () virtual
Definition at line 61 of file qwaylandwindowmanagerintegration.cpp.
 {
 }
Functions
authenticateWithToken()
void QWaylandWindowManagerIntegration::authenticateWithToken (const QByteArray & token = QByteArray())
Definition at line 85 of file qwaylandwindowmanagerintegration.cpp.
 {
     QByteArray authToken = token;
     if (authToken.isEmpty())
         authToken = qgetenv("WL_AUTHENTICATION_TOKEN");
     if (mWaylandWindowManager)
         wl_windowmanager_authenticate_with_token(mWaylandWindowManager, authToken.constData());
 }
createIntegration()
QWaylandWindowManagerIntegration * QWaylandWindowManagerIntegration::createIntegration (QWaylandDisplay * waylandDisplay) static
Definition at line 47 of file qwaylandwindowmanagerintegration.cpp.
Referenced by QWaylandDisplay::QWaylandDisplay().
 {
     return new QWaylandWindowManagerIntegration(waylandDisplay);
 }
mapClientToProcess()
void QWaylandWindowManagerIntegration::mapClientToProcess (long long processId)
Definition at line 79 of file qwaylandwindowmanagerintegration.cpp.
 {
     if (mWaylandWindowManager)
         wl_windowmanager_map_client_to_process(mWaylandWindowManager, (uint32_t) processId);
 }
mapSurfaceToProcess()
void QWaylandWindowManagerIntegration::mapSurfaceToProcess (struct wl_surface * surface, long long processId)
windowManager()
struct wl_windowmanager * QWaylandWindowManagerIntegration::windowManager () const
Definition at line 66 of file qwaylandwindowmanagerintegration.cpp.
 {
     return mWaylandWindowManager;
 }
wlHandleListenerGlobal()
void QWaylandWindowManagerIntegration::wlHandleListenerGlobal (wl_display * display, uint32_t id, const char * interface, uint32_t version, void * data) static private
Definition at line 71 of file qwaylandwindowmanagerintegration.cpp.
Referenced by QWaylandWindowManagerIntegration().
 {
     if (strcmp(interface, "wl_windowmanager") == 0) {
         QWaylandWindowManagerIntegration *integration = static_cast<QWaylandWindowManagerIntegration *>(data);
         integration->mWaylandWindowManager = wl_windowmanager_create(display, id);
     }
 }
Properties
mWaylandDisplay
QWaylandDisplay* QWaylandWindowManagerIntegration::mWaylandDisplay private
Definition at line 66 of file qwaylandwindowmanagerintegration.h.
Referenced by QWaylandWindowManagerIntegration().
mWaylandWindowManager
struct wl_windowmanager* QWaylandWindowManagerIntegration::mWaylandWindowManager private
Definition at line 67 of file qwaylandwindowmanagerintegration.h.
Referenced by authenticateWithToken(), mapClientToProcess(), windowManager(), and wlHandleListenerGlobal().
The documentation for this class was generated from the following files:
/src/plugins/platforms/wayland/windowmanager_integration/qwaylandwindowmanagerintegration.h
/src/plugins/platforms/wayland/windowmanager_integration/qwaylandwindowmanagerintegration.cpp