Qt 4.8: QWaylandReadbackEglIntegration Class Reference
QWaylandReadbackEglIntegration Class Reference
#include <qwaylandreadbackeglintegration.h>
Public Functions
QWaylandWindow * createEglWindow (QWidget *widget)
int depth () const
EGLDisplay eglDisplay ()
void initialize ()
QWaylandReadbackEglIntegration (QWaylandDisplay *display)
Window rootWindow () const
QWaylandDisplay * waylandDisplay () const
Display * xDisplay () const
~QWaylandReadbackEglIntegration ()
Public Functions inherited from QWaylandGLIntegration
QWaylandGLIntegration ()
virtual ~QWaylandGLIntegration ()
Properties
Display * mDisplay
EGLDisplay mEglDisplay
Window mRootWindow
int mScreen
QWaylandDisplay * mWaylandDisplay
Additional Inherited Members
Static Public Functions inherited from QWaylandGLIntegration
static QWaylandGLIntegration * createGLIntegration (QWaylandDisplay *waylandDisplay)
Detailed Description
Definition at line 57 of file qwaylandreadbackeglintegration.h.
Constructors and Destructors
QWaylandReadbackEglIntegration()
QWaylandReadbackEglIntegration::QWaylandReadbackEglIntegration (QWaylandDisplay * display)
Definition at line 48 of file qwaylandreadbackeglintegration.cpp.
Referenced by QWaylandGLIntegration::createGLIntegration().
     : QWaylandGLIntegration()
     , mWaylandDisplay(display)
 {
     qDebug() << "Using Readback-EGL";
     char *display_name = getenv("DISPLAY");
     mDisplay = XOpenDisplay(display_name);
     mScreen = XDefaultScreen(mDisplay);
     mRootWindow = XDefaultRootWindow(mDisplay);
     XSync(mDisplay, False);
 }
~QWaylandReadbackEglIntegration()
QWaylandReadbackEglIntegration::~QWaylandReadbackEglIntegration ()
Definition at line 60 of file qwaylandreadbackeglintegration.cpp.
 {
     XCloseDisplay(mDisplay);
 }
Functions
createEglWindow()
QWaylandWindow * QWaylandReadbackEglIntegration::createEglWindow (QWidget * widget) virtual
Implements QWaylandGLIntegration.
Definition at line 84 of file qwaylandreadbackeglintegration.cpp.
 {
     return new QWaylandReadbackEglWindow(widget,this);
 }
depth()
int QWaylandReadbackEglIntegration::depth () const
Definition at line 99 of file qwaylandreadbackeglintegration.cpp.
Referenced by QWaylandReadbackEglContext::geometryChanged().
 {
     return XDefaultDepth(mDisplay,mScreen);
 }
eglDisplay()
EGLDisplay QWaylandReadbackEglIntegration::eglDisplay ()
Definition at line 89 of file qwaylandreadbackeglintegration.cpp.
Referenced by QWaylandReadbackEglContext::doneCurrent(), QWaylandReadbackEglContext::geometryChanged(), QWaylandReadbackEglContext::makeCurrent(), QWaylandReadbackEglContext::platformWindowFormat(), QWaylandReadbackEglContext::QWaylandReadbackEglContext(), QWaylandReadbackEglContext::swapBuffers(), and QWaylandReadbackEglContext::~QWaylandReadbackEglContext().
 {
     return mEglDisplay;
 }
initialize()
void QWaylandReadbackEglIntegration::initialize () virtual
Implements QWaylandGLIntegration.
Definition at line 71 of file qwaylandreadbackeglintegration.cpp.
 {
     eglBindAPI(EGL_OPENGL_ES_API);
     mEglDisplay = eglGetDisplay(mDisplay);
     EGLint major, minor;
     EGLBoolean initialized = eglInitialize(mEglDisplay,&major,&minor);
     if (initialized) {
         qDebug() << "EGL initialized successfully" << major << "," << minor;
     } else {
         qDebug() << "EGL could not initialized. All EGL and GL operations will fail";
     }
 }
rootWindow()
Window QWaylandReadbackEglIntegration::rootWindow () const
Definition at line 94 of file qwaylandreadbackeglintegration.cpp.
Referenced by QWaylandReadbackEglContext::geometryChanged().
 {
     return mRootWindow;
 }
waylandDisplay()
QWaylandDisplay * QWaylandReadbackEglIntegration::waylandDisplay () const
Definition at line 109 of file qwaylandreadbackeglintegration.cpp.
Referenced by QWaylandReadbackEglContext::geometryChanged().
 {
     return mWaylandDisplay;
 }
xDisplay()
Display * QWaylandReadbackEglIntegration::xDisplay () const
Definition at line 104 of file qwaylandreadbackeglintegration.cpp.
Referenced by QWaylandReadbackEglContext::geometryChanged().
 {
     return mDisplay;
 }
Properties
mDisplay
Display* QWaylandReadbackEglIntegration::mDisplay private
Definition at line 75 of file qwaylandreadbackeglintegration.h.
Referenced by depth(), initialize(), QWaylandReadbackEglIntegration(), xDisplay(), and ~QWaylandReadbackEglIntegration().
mEglDisplay
EGLDisplay QWaylandReadbackEglIntegration::mEglDisplay private
Definition at line 78 of file qwaylandreadbackeglintegration.h.
Referenced by eglDisplay(), and initialize().
mRootWindow
Window QWaylandReadbackEglIntegration::mRootWindow private
Definition at line 77 of file qwaylandreadbackeglintegration.h.
Referenced by QWaylandReadbackEglIntegration(), and rootWindow().
mScreen
int QWaylandReadbackEglIntegration::mScreen private
Definition at line 76 of file qwaylandreadbackeglintegration.h.
Referenced by depth(), and QWaylandReadbackEglIntegration().
mWaylandDisplay
QWaylandDisplay* QWaylandReadbackEglIntegration::mWaylandDisplay private
Definition at line 74 of file qwaylandreadbackeglintegration.h.
Referenced by waylandDisplay().
The documentation for this class was generated from the following files:
/src/plugins/platforms/wayland/gl_integration/readback_egl/qwaylandreadbackeglintegration.h
/src/plugins/platforms/wayland/gl_integration/readback_egl/qwaylandreadbackeglintegration.cpp