Qt 4.8: QDeclarativeBasePositionerPrivate Class Reference
QDeclarativeBasePositionerPrivate Class Reference
#include <qdeclarativepositioners_p_p.h>
Public Functions
void init (QDeclarativeBasePositioner::PositionerType at)
bool isLeftToRight () const
void itemDestroyed (QDeclarativeItem *item)
void itemGeometryChanged (QDeclarativeItem *, const QRectF &newGeometry, const QRectF &oldGeometry)
virtual void itemOpacityChanged (QDeclarativeItem *)
virtual void itemSiblingOrderChanged (QDeclarativeItem *other)
virtual void itemVisibilityChanged (QDeclarativeItem *)
void mirrorChange ()
QDeclarativeBasePositionerPrivate ()
void schedulePositioning ()
void unwatchChanges (QGraphicsObject *other)
void watchChanges (QGraphicsObject *other)
Public Functions inherited from QDeclarativeImplicitSizeItemPrivate
virtual void implicitHeightChanged ()
virtual void implicitWidthChanged ()
QDeclarativeImplicitSizeItemPrivate ()
Public Functions inherited from QDeclarativeItemPrivate
QDeclarativeStateGroup * _states ()
void addItemChangeListener (QDeclarativeItemChangeListener *listener, ChangeTypes types)
AnchorLines * anchorLines () const
QDeclarativeAnchors * anchors ()
QDeclarativeAnchorLine baseline () const
QDeclarativeAnchorLine bottom () const
QPointF computeTransformOrigin () const
QDeclarativeListProperty< QObject > data ()
virtual void focusChanged (bool)
virtual void focusScopeItemChange (bool isSubFocusItem)
Subclasses can reimplement this function to be notified when an item becomes a focusScopeItem (or is no longer a focusScopeItem).
qreal height () const
QDeclarativeAnchorLine horizontalCenter () const
virtual qreal implicitHeight () const
virtual qreal implicitWidth () const
void init (QDeclarativeItem *parent)
bool isMirrored () const
QDeclarativeAnchorLine left () const
QDeclarativeItemPrivate ()
void removeItemChangeListener (QDeclarativeItemChangeListener *, ChangeTypes types)
void resetHeight ()
void resetWidth ()
void resolveLayoutMirror ()
QDeclarativeListProperty< QObject > resources ()
QDeclarativeAnchorLine right () const
void setHeight (qreal)
void setImplicitLayoutMirror (bool mirror, bool inherit)
void setLayoutMirror (bool mirror)
virtual void setPosHelper (const QPointF &pos)
Sets the position pos.
void setState (const QString &)
void setWidth (qreal)
virtual void siblingOrderChange ()
Subclasses can reimplement this function to be notified when its siblingIndex order is changed.
QString state () const
QDeclarativeListProperty< QDeclarativeState > states ()
QDeclarativeAnchorLine top () const
virtual void transformChanged ()
QDeclarativeListProperty< QDeclarativeTransition > transitions ()
QDeclarativeAnchorLine verticalCenter () const
qreal width () const
Public Functions inherited from QGraphicsItemPrivate
void addChild (QGraphicsItem *child)
QGraphicsScenePrivate::registerTopLevelItem().
void appendGraphicsTransform (QGraphicsTransform *t)
qreal calcEffectiveOpacity () const
void childrenBoundingRectHelper (QTransform *x, QRectF *rect, QGraphicsItem *topMostEffectItem)
Returns the bounding rect of this item's children (excluding itself).
bool childrenClippedToShape () const
bool childrenCombineOpacity () const
QDeclarativeListProperty< QGraphicsObject > childrenList ()
Returns a list of this item's children.
void clearFocusHelper (bool giveFocusToParent)
void clearSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
qreal combineOpacityFromParent (qreal parentOpacity) const
void combineTransformFromParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
void combineTransformToParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
int depth () const
bool discardUpdateRequest (bool ignoreVisibleBit=false, bool ignoreDirtyBit=false, bool ignoreOpacity=false) const
Returns true if we can discard an update request; otherwise false.
QRectF effectiveBoundingRect (QGraphicsItem *topMostEffectItem=0) const
Returns the effective bounding rect of the item.
QRectF effectiveBoundingRect (const QRectF &rect) const
Returns the effective bounding rect of the given item space rect.
qreal effectiveOpacity () const
void ensureSceneTransform ()
void ensureSceneTransformRecursive (QGraphicsItem **topMostDirtyItem)
void ensureSequentialSiblingIndex ()
Ensures that the list of children is sorted by insertion order, and that the siblingIndexes are packed (no gaps), and start at 0.
void ensureSortedChildren ()
QVariant extra (Extra type) const
QGraphicsItemCache * extraItemCache () const
QPointF genericMapFromScene (const QPointF &pos, const QWidget *viewport) const
Maps the point pos from scene to item coordinates.
bool hasTranslateOnlySceneTransform ()
void initStyleOption (QStyleOptionGraphicsItem *option, const QTransform &worldTransform, const QRegion &exposedRegion, bool allItems=false) const
virtual QVariant inputMethodQueryHelper (Qt::InputMethodQuery query) const
This helper function helped us add input method query support in Qt 4.
void invalidateChildGraphicsEffectsRecursively (InvalidateReason reason)
void invalidateChildrenSceneTransform ()
void invalidateDepthRecursively ()
void invalidateParentGraphicsEffectsRecursively ()
bool isFullyTransparent () const
bool isInvisible () const
bool isOpacityNull () const
virtual bool isProxyWidget () const
bool itemIsUntransformable () const
void markParentDirty (bool updateBoundingRect=false)
QGraphicsItemCache * maybeExtraItemCache () const
void prependGraphicsTransform (QGraphicsTransform *t)
QGraphicsItemPrivate ()
void remapItemPos (QEvent *event, QGraphicsItem *item)
Maps any item pos properties of event to item's coordinate system.
void removeChild (QGraphicsItem *child)
QGraphicsScenePrivate::unregisterTopLevelItem().
void removeExtraItemCache ()
void resetFocusProxy ()
Sets the focusProxy pointer to 0 for all items that have this item as their focusProxy.
void resolveDepth ()
Resolves the stacking depth of this object and all its ancestors.
virtual void resolveFont (uint inheritedMask)
virtual void resolvePalette (uint inheritedMask)
QRectF sceneEffectiveBoundingRect () const
Returns the effective bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect(), taking into account the effect that the item might have.
void sendScenePosChange ()
void setEnabledHelper (bool newEnabled, bool explicitly, bool update=true)
Sets this item's visibility to newEnabled.
void setExtra (Extra type, const QVariant &value)
void setFocusHelper (Qt::FocusReason focusReason, bool climb, bool focusFromHide)
void setIsMemberOfGroup (bool enabled)
Propagates item group membership.
void setParentItemHelper (QGraphicsItem *parent, const QVariant *newParentVariant, const QVariant *thisPointerVariant)
Make sure not to trigger any pure virtual function calls (e.
void setSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
void setTransformHelper (const QTransform &transform)
Sets the transform transform.
void setVisibleHelper (bool newVisible, bool explicitly, bool update=true)
Sets this item's visibility to newVisible.
virtual void subFocusItemChange ()
Subclasses can reimplement this function to be notified when subFocusItem changes.
QTransform transformToParent () const
void unsetExtra (Extra type)
void updateAncestorFlag (QGraphicsItem::GraphicsItemFlag childFlag, AncestorFlag flag=NoFlag, bool enabled=false, bool root=true)
Propagates the ancestor flag flag with value enabled to all this item's children.
void updateAncestorFlags ()
void updateChildWithGraphicsEffectFlagRecursively ()
void updatePaintedViewBoundingRects (bool updateChildren)
virtual void updateSceneTransformFromParent ()
virtual ~QGraphicsItemPrivate ()
Public Functions inherited from QDeclarativeItemChangeListener
virtual QDeclarativeAnchorsPrivate * anchorPrivate ()
Static Public Functions
static Qt::LayoutDirection getEffectiveLayoutDirection (const QDeclarativeBasePositioner *positioner)
static Qt::LayoutDirection getLayoutDirection (const QDeclarativeBasePositioner *positioner)
Static Public Functions inherited from QDeclarativeItemPrivate
static void data_append (QDeclarativeListProperty< QObject > *, QObject *)
static QObject * data_at (QDeclarativeListProperty< QObject > *, int)
static void data_clear (QDeclarativeListProperty< QObject > *)
static int data_count (QDeclarativeListProperty< QObject > *)
static qint64 elapsed (QElapsedTimer &)
static QDeclarativeItemPrivate * get (QDeclarativeItem *item)
static void parentProperty (QObject *o, void *rv, QDeclarativeNotifierEndpoint *e)
static void resources_append (QDeclarativeListProperty< QObject > *, QObject *)
static QObject * resources_at (QDeclarativeListProperty< QObject > *, int)
static void resources_clear (QDeclarativeListProperty< QObject > *)
static int resources_count (QDeclarativeListProperty< QObject > *)
static qint64 restart (QElapsedTimer &)
static void setConsistentTime (qint64 t)
static void start (QElapsedTimer &)
static void transform_append (QDeclarativeListProperty< QGraphicsTransform > *list, QGraphicsTransform *)
static QGraphicsTransform * transform_at (QDeclarativeListProperty< QGraphicsTransform > *list, int)
static void transform_clear (QDeclarativeListProperty< QGraphicsTransform > *list)
static int transform_count (QDeclarativeListProperty< QGraphicsTransform > *list)
Static Public Functions inherited from QGraphicsItemPrivate
static void children_append (QDeclarativeListProperty< QGraphicsObject > *list, QGraphicsObject *item)
static QGraphicsObject * children_at (QDeclarativeListProperty< QGraphicsObject > *list, int)
static void children_clear (QDeclarativeListProperty< QGraphicsObject > *list)
static int children_count (QDeclarativeListProperty< QGraphicsObject > *list)
static const QGraphicsItemPrivate * get (const QGraphicsItem *item)
static QGraphicsItemPrivate * get (QGraphicsItem *item)
static bool insertionOrder (QGraphicsItem *a, QGraphicsItem *b)
static bool isOpacityNull (qreal opacity)
static bool movableAncestorIsSelected (const QGraphicsItem *item)
Public Variables
QDeclarativeStateOperation::ActionList addActions
QDeclarativeTransition * addTransition
QDeclarativeTransitionManager addTransitionManager
bool anchorConflict: 1
bool doingPositioning: 1
Qt::LayoutDirection layoutDirection
QDeclarativeStateOperation::ActionList moveActions
QDeclarativeTransition * moveTransition
QDeclarativeTransitionManager moveTransitionManager
bool queuedPositioning: 1
int spacing
QDeclarativeBasePositioner::PositionerType type
Public Variables inherited from QDeclarativeItemPrivate
AnchorLines * _anchorLines
QDeclarativeAnchors * _anchors
QDeclarativeContents * _contents
QDeclarativeStateGroup * _stateGroup
QDeclarativeLayoutMirroringAttached * attachedLayoutDirection
QDeclarativeNullableValue< qreal > baselineOffset
QPODVector< ChangeListener, 4 > changeListeners
bool componentComplete:1
bool doneEventPreHandler: 1
bool effectiveLayoutMirror:1
bool hadActiveFocus:1
bool hadFocus:1
bool heightValid:1
bool inheritedLayoutMirror:1
bool inheritMirrorFromItem:1
bool inheritMirrorFromParent:1
bool isMirrorImplicit:1
bool keepMouse:1
QDeclarativeItemKeyFilter * keyHandler
qreal mHeight
qreal mImplicitHeight
qreal mImplicitWidth
qreal mWidth
QDeclarativeItem::TransformOrigin origin:5
QDeclarativeNotifier parentNotifier
bool smooth:1
bool transformOriginDirty: 1
bool widthValid:1
Public Variables inherited from QGraphicsItemPrivate
quint32 acceptDrops: 1
quint32 acceptedMouseButtons: 5
quint32 acceptedTouchBeginEvent: 1
quint32 acceptsHover: 1
quint32 acceptTouchEvents: 1
quint32 allChildrenDirty: 1
quint32 ancestorFlags: 4
quint32 cacheMode: 2
QList< QGraphicsItem * > children
QRectF childrenBoundingRect
quint32 dirty: 1
quint32 dirtyChildren: 1
quint32 dirtyChildrenBoundingRect: 1
quint32 dirtySceneTransform: 1
quint32 enabled: 1
quint32 explicitActivate: 1
quint32 explicitlyDisabled: 1
quint32 explicitlyHidden: 1
QList< ExtraStruct > extras
quint32 filtersDescendantEvents: 1
quint32 flags: 19
QGraphicsItem * focusProxy
QList< QGraphicsItem ** > focusProxyRefs
QGraphicsItem * focusScopeItem
quint32 fullUpdatePending: 1
quint32 geometryChanged: 1
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
int globalStackingOrder
QGraphicsEffect * graphicsEffect
quint32 handlesChildEvents: 1
quint32 hasBoundingRegionGranularity: 1
quint32 hasCursor: 1
quint32 holesInSiblingIndex: 1
quint32 ignoreOpacity: 1
quint32 ignoreVisible: 1
Qt::InputMethodHints imHints
quint32 inDestructor: 1
int index
quint32 inSetPosHelper: 1
quint32 isDeclarativeItem: 1
quint32 isMemberOfGroup: 1
quint32 isObject: 1
quint32 isWidget: 1
int itemDepth
quint32 itemDiscovered: 1
quint32 localCollisionHack: 1
quint32 mayHaveChildWithGraphicsEffect: 1
quint32 mouseSetsFocus: 1
quint32 needSortChildren: 1
QRectF needsRepaint
quint32 notifyBoundingRectChanged: 1
quint32 notifyInvalidated: 1
qreal opacity
quint32 padding: 21
QMap< QWidget *, QRect > paintedViewBoundingRects
quint32 paintedViewBoundingRectsNeedRepaint: 1
QGraphicsItem::PanelModality panelModality
QGraphicsItem * parent
quint32 pendingPolish: 1
QPointF pos
QGraphicsItem * q_ptr
QGraphicsScene * scene
quint32 scenePosDescendants: 1
QTransform sceneTransform
quint32 sceneTransformTranslateOnly: 1
quint32 selected: 1
quint32 sendParentChangeNotification: 1
quint32 sequentialOrdering: 1
int siblingIndex
QGraphicsItem * subFocusItem
TransformData * transformData
quint32 updateDueToGraphicsEffect: 1
quint32 visible: 1
quint32 wantsActive: 1
qreal z
Additional Inherited Members
Public Types inherited from QDeclarativeItemPrivate
enum ChangeType {
Geometry = 0x01, SiblingOrder = 0x02, Visibility = 0x04, Opacity = 0x08,
Destroyed = 0x10
}
Public Types inherited from QGraphicsItemPrivate
enum AncestorFlag {
NoFlag = 0, AncestorHandlesChildEvents = 0x1, AncestorClipsChildren = 0x2, AncestorIgnoresTransformations = 0x4,
AncestorFiltersChildEvents = 0x8
}
enum Extra {
ExtraToolTip, ExtraCursor, ExtraCacheData, ExtraMaxDeviceCoordCacheSize,
ExtraBoundingRegionGranularity
}
enum InvalidateReason { OpacityChanged }
Static Public Variables inherited from QDeclarativeItemPrivate
static qint64 consistentTime = -1
Detailed Description
Definition at line 70 of file qdeclarativepositioners_p_p.h.
Constructors and Destructors
QDeclarativeBasePositionerPrivate()
QDeclarativeBasePositionerPrivate::QDeclarativeBasePositionerPrivate () inline
Definition at line 75 of file qdeclarativepositioners_p_p.h.
         : spacing(0), type(QDeclarativeBasePositioner::None)
         , moveTransition(0), addTransition(0), queuedPositioning(false)
         , doingPositioning(false), anchorConflict(false), layoutDirection(Qt::LeftToRight)
     {
     }
Functions
getEffectiveLayoutDirection()
static Qt::LayoutDirection QDeclarativeBasePositionerPrivate::getEffectiveLayoutDirection (const QDeclarativeBasePositioner * positioner) inline static
Definition at line 163 of file qdeclarativepositioners_p_p.h.
Referenced by QDeclarativeRow::effectiveLayoutDirection(), QDeclarativeGrid::effectiveLayoutDirection(), and QDeclarativeFlow::effectiveLayoutDirection().
     {
         if (positioner->d_func()->effectiveLayoutMirror)
             return positioner->d_func()->layoutDirection == Qt::RightToLeft ? Qt::LeftToRight : Qt::RightToLeft;
         else
             return positioner->d_func()->layoutDirection;
     }
getLayoutDirection()
static Qt::LayoutDirection QDeclarativeBasePositionerPrivate::getLayoutDirection (const QDeclarativeBasePositioner * positioner) inline static
Definition at line 158 of file qdeclarativepositioners_p_p.h.
Referenced by QDeclarativeRow::QDeclarativeRow(), and QDeclarativeGrid::setFlow().
     {
         return positioner->d_func()->layoutDirection;
     }
init()
void QDeclarativeBasePositionerPrivate::init (QDeclarativeBasePositioner::PositionerType at) inline
Definition at line 82 of file qdeclarativepositioners_p_p.h.
     {
         type = at;
     }
isLeftToRight()
bool QDeclarativeBasePositionerPrivate::isLeftToRight () const inline
Definition at line 120 of file qdeclarativepositioners_p_p.h.
Referenced by QDeclarativeRow::doPositioning(), and QDeclarativeGrid::doPositioning().
{
         if (type == QDeclarativeBasePositioner::Vertical)
             return true;
         else
             return effectiveLayoutMirror ? layoutDirection == Qt::RightToLeft : layoutDirection == Qt::LeftToRight;
     }
itemDestroyed()
void QDeclarativeBasePositionerPrivate::itemDestroyed (QDeclarativeItem * item) inline virtual
Reimplemented from QDeclarativeItemChangeListener.
Definition at line 152 of file qdeclarativepositioners_p_p.h.
     {
         Q_Q(QDeclarativeBasePositioner);
         q->positionedItems.removeOne(QDeclarativeBasePositioner::PositionedItem(item));
     }
itemGeometryChanged()
void QDeclarativeBasePositionerPrivate::itemGeometryChanged (QDeclarativeItem * , const QRectF & newGeometry, const QRectF & oldGeometry) inline virtual
Reimplemented from QDeclarativeItemChangeListener.
Definition at line 135 of file qdeclarativepositioners_p_p.h.
     {
         Q_Q(QDeclarativeBasePositioner);
         if (newGeometry.size() != oldGeometry.size())
             q->prePositioning();
     }
itemOpacityChanged()
virtual void QDeclarativeBasePositionerPrivate::itemOpacityChanged (QDeclarativeItem *) inline virtual
Reimplemented from QDeclarativeItemChangeListener.
Definition at line 146 of file qdeclarativepositioners_p_p.h.
     {
         Q_Q(QDeclarativeBasePositioner);
         q->prePositioning();
     }
itemSiblingOrderChanged()
virtual void QDeclarativeBasePositionerPrivate::itemSiblingOrderChanged (QDeclarativeItem * other) inline virtual
Reimplemented from QDeclarativeItemChangeListener.
Definition at line 127 of file qdeclarativepositioners_p_p.h.
     {
         Q_UNUSED(other);
         //Delay is due to many children often being reordered at once
         //And we only want to reposition them all once
         schedulePositioning();
     }
itemVisibilityChanged()
virtual void QDeclarativeBasePositionerPrivate::itemVisibilityChanged (QDeclarativeItem *) inline virtual
Reimplemented from QDeclarativeItemChangeListener.
Definition at line 142 of file qdeclarativepositioners_p_p.h.
     {
         schedulePositioning();
     }
mirrorChange()
void QDeclarativeBasePositionerPrivate::mirrorChange () inline virtual
Reimplemented from QDeclarativeItemPrivate.
Definition at line 115 of file qdeclarativepositioners_p_p.h.
{
         Q_Q(QDeclarativeBasePositioner);
         if (type != QDeclarativeBasePositioner::Vertical)
             q->prePositioning();
     }
schedulePositioning()
void QDeclarativeBasePositionerPrivate::schedulePositioning () inline
Definition at line 106 of file qdeclarativepositioners_p_p.h.
Referenced by itemSiblingOrderChanged(), and itemVisibilityChanged().
     {
         Q_Q(QDeclarativeBasePositioner);
         if(!queuedPositioning){
             QTimer::singleShot(0,q,SLOT(prePositioning()));
             queuedPositioning = true;
         }
     }
unwatchChanges()
void QDeclarativeBasePositionerPrivate::unwatchChanges (QGraphicsObject * other)
Definition at line 78 of file qdeclarativepositioners.cpp.
 {
     if (QGraphicsItemPrivate::get(other)->isDeclarativeItem) {
         QDeclarativeItemPrivate *otherPrivate = static_cast<QDeclarativeItemPrivate*>(QGraphicsItemPrivate::get(other));
         otherPrivate->removeItemChangeListener(this, watchedChanges);
     } else {
         Q_Q(QDeclarativeBasePositioner);
         QObject::disconnect(other, SIGNAL(widthChanged()), q, SLOT(graphicsWidgetGeometryChanged()));
         QObject::disconnect(other, SIGNAL(heightChanged()), q, SLOT(graphicsWidgetGeometryChanged()));
         QObject::disconnect(other, SIGNAL(opacityChanged()), q, SLOT(graphicsWidgetGeometryChanged()));
         QObject::disconnect(other, SIGNAL(visibleChanged()), q, SLOT(graphicsWidgetGeometryChanged()));
     }
 }
watchChanges()
void QDeclarativeBasePositionerPrivate::watchChanges (QGraphicsObject * other)
Definition at line 64 of file qdeclarativepositioners.cpp.
 {
     if (QGraphicsItemPrivate::get(other)->isDeclarativeItem) {
         QDeclarativeItemPrivate *otherPrivate = static_cast<QDeclarativeItemPrivate*>(QGraphicsItemPrivate::get(other));
         otherPrivate->addItemChangeListener(this, watchedChanges);
     } else {
         Q_Q(QDeclarativeBasePositioner);
         QObject::connect(other, SIGNAL(widthChanged()), q, SLOT(graphicsWidgetGeometryChanged()));
         QObject::connect(other, SIGNAL(heightChanged()), q, SLOT(graphicsWidgetGeometryChanged()));
         QObject::connect(other, SIGNAL(opacityChanged()), q, SLOT(graphicsWidgetGeometryChanged()));
         QObject::connect(other, SIGNAL(visibleChanged()), q, SLOT(graphicsWidgetGeometryChanged()));
     }
 }
Properties
addActions
QDeclarativeStateOperation::ActionList QDeclarativeBasePositionerPrivate::addActions
Definition at line 92 of file qdeclarativepositioners_p_p.h.
addTransition
QDeclarativeTransition* QDeclarativeBasePositionerPrivate::addTransition
Definition at line 91 of file qdeclarativepositioners_p_p.h.
addTransitionManager
QDeclarativeTransitionManager QDeclarativeBasePositionerPrivate::addTransitionManager
Definition at line 94 of file qdeclarativepositioners_p_p.h.
anchorConflict
bool QDeclarativeBasePositionerPrivate::anchorConflict
Definition at line 101 of file qdeclarativepositioners_p_p.h.
Referenced by QDeclarativeColumn::reportConflictingAnchors(), QDeclarativeRow::reportConflictingAnchors(), and QDeclarativeGrid::reportConflictingAnchors().
doingPositioning
bool QDeclarativeBasePositionerPrivate::doingPositioning
Definition at line 100 of file qdeclarativepositioners_p_p.h.
layoutDirection
Qt::LayoutDirection QDeclarativeBasePositionerPrivate::layoutDirection
Definition at line 103 of file qdeclarativepositioners_p_p.h.
Referenced by QDeclarativeRow::setLayoutDirection(), and QDeclarativeGrid::setLayoutDirection().
moveActions
QDeclarativeStateOperation::ActionList QDeclarativeBasePositionerPrivate::moveActions
Definition at line 93 of file qdeclarativepositioners_p_p.h.
moveTransition
QDeclarativeTransition* QDeclarativeBasePositionerPrivate::moveTransition
Definition at line 90 of file qdeclarativepositioners_p_p.h.
moveTransitionManager
QDeclarativeTransitionManager QDeclarativeBasePositionerPrivate::moveTransitionManager
Definition at line 95 of file qdeclarativepositioners_p_p.h.
queuedPositioning
bool QDeclarativeBasePositionerPrivate::queuedPositioning
Definition at line 99 of file qdeclarativepositioners_p_p.h.
Referenced by schedulePositioning().
spacing
int QDeclarativeBasePositionerPrivate::spacing
Definition at line 87 of file qdeclarativepositioners_p_p.h.
type
QDeclarativeBasePositioner::PositionerType QDeclarativeBasePositionerPrivate::type
Definition at line 89 of file qdeclarativepositioners_p_p.h.
Referenced by init().
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativepositioners_p_p.h
/src/declarative/graphicsitems/qdeclarativepositioners.cpp