Qt 4.8: QDataWidgetMapperPrivate Class Reference
QDataWidgetMapperPrivate Class Reference
Classes
struct WidgetMapper
Public Functions
void _q_closeEditor (QWidget *, QAbstractItemDelegate::EndEditHint)
void _q_commitData (QWidget *)
void _q_dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
void _q_modelDestroyed ()
bool commit (const WidgetMapper &m)
int currentIdx () const
int findWidget (QWidget *w) const
void flipEventFilters (QAbstractItemDelegate *oldDelegate, QAbstractItemDelegate *newDelegate)
QModelIndex indexAt (int itemPos)
int itemCount ()
void populate ()
void populate (WidgetMapper &m)
QDataWidgetMapperPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QPersistentModelIndex currentTopLeft
QAbstractItemDelegate * delegate
QAbstractItemModel * model
Qt::Orientation orientation
QPersistentModelIndex rootIndex
QDataWidgetMapper::SubmitPolicy submitPolicy
QList< WidgetMapper > widgetMap
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Detailed Description
Definition at line 55 of file qdatawidgetmapper.cpp.
Constructors and Destructors
QDataWidgetMapperPrivate()
QDataWidgetMapperPrivate::QDataWidgetMapperPrivate () inline
Definition at line 60 of file qdatawidgetmapper.cpp.
         : model(QAbstractItemModelPrivate::staticEmptyModel()), delegate(0),
           orientation(Qt::Horizontal), submitPolicy(QDataWidgetMapper::AutoSubmit)
     {
     }
Functions
_q_closeEditor()
void QDataWidgetMapperPrivate::_q_closeEditor (QWidget * w, QAbstractItemDelegate::EndEditHint hint)
Definition at line 223 of file qdatawidgetmapper.cpp.
Referenced by flipEventFilters().
 {
     int idx = findWidget(w);
     if (idx == -1)
         return; // not our widget
     switch (hint) {
     case QAbstractItemDelegate::RevertModelCache: {
         populate(widgetMap[idx]);
         break; }
     case QAbstractItemDelegate::EditNextItem:
         QFocusHelper::focusNextPrevChild(w, true);
         break;
     case QAbstractItemDelegate::EditPreviousItem:
         QFocusHelper::focusNextPrevChild(w, false);
         break;
     case QAbstractItemDelegate::SubmitModelCache:
     case QAbstractItemDelegate::NoHint:
         // nothing
         break;
     }
 }
_q_commitData()
void QDataWidgetMapperPrivate::_q_commitData (QWidget * w)
Definition at line 197 of file qdatawidgetmapper.cpp.
Referenced by flipEventFilters().
 {
     if (submitPolicy == QDataWidgetMapper::ManualSubmit)
         return;
     int idx = findWidget(w);
     if (idx == -1)
         return; // not our widget
     commit(widgetMap.at(idx));
 }
_q_dataChanged()
void QDataWidgetMapperPrivate::_q_dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight)
Definition at line 185 of file qdatawidgetmapper.cpp.
Referenced by flipEventFilters().
 {
     if (topLeft.parent() != rootIndex)
         return; // not in our hierarchy
     for (int i = 0; i < widgetMap.count(); ++i) {
         WidgetMapper &m = widgetMap[i];
         if (qContainsIndex(m.currentIndex, topLeft, bottomRight))
             populate(m);
     }
 }
_q_modelDestroyed()
void QDataWidgetMapperPrivate::_q_modelDestroyed ()
Definition at line 246 of file qdatawidgetmapper.cpp.
Referenced by flipEventFilters().
 {
     Q_Q(QDataWidgetMapper);
     model = 0;
     q->setModel(QAbstractItemModelPrivate::staticEmptyModel());
 }
commit()
bool QDataWidgetMapperPrivate::commit (const WidgetMapper & m)
Definition at line 142 of file qdatawidgetmapper.cpp.
Referenced by _q_commitData().
 {
     if (m.widget.isNull())
         return true; // just ignore
     if (!m.currentIndex.isValid())
         return false;
     // Create copy to avoid passing the widget mappers data
     QModelIndex idx = m.currentIndex;
     if (m.property.isEmpty())
         delegate->setModelData(m.widget, model, idx);
     else
         model->setData(idx, m.widget->property(m.property), Qt::EditRole);
     return true;
 }
currentIdx()
int QDataWidgetMapperPrivate::currentIdx () const inline
Definition at line 80 of file qdatawidgetmapper.cpp.
Referenced by indexAt().
     {
         return orientation == Qt::Horizontal ? currentTopLeft.row() : currentTopLeft.column();
     }
findWidget()
int QDataWidgetMapperPrivate::findWidget (QWidget * w) const
Definition at line 133 of file qdatawidgetmapper.cpp.
Referenced by _q_closeEditor(), and _q_commitData().
 {
     for (int i = 0; i < widgetMap.count(); ++i) {
         if (widgetMap.at(i).widget == w)
             return i;
     }
     return -1;
 }
flipEventFilters()
void QDataWidgetMapperPrivate::flipEventFilters (QAbstractItemDelegate * oldDelegate, QAbstractItemDelegate * newDelegate) inline
Definition at line 92 of file qdatawidgetmapper.cpp.
     {
         for (int i = 0; i < widgetMap.count(); ++i) {
             QWidget *w = widgetMap.at(i).widget;
             if (!w)
                 continue;
             w->removeEventFilter(oldDelegate);
             w->installEventFilter(newDelegate);
         }
     }
indexAt()
QModelIndex QDataWidgetMapperPrivate::indexAt (int itemPos) inline
Definition at line 85 of file qdatawidgetmapper.cpp.
Referenced by populate().
     {
         return orientation == Qt::Horizontal
             ? model->index(currentIdx(), itemPos, rootIndex)
             : model->index(itemPos, currentIdx(), rootIndex);
     }
itemCount()
int QDataWidgetMapperPrivate::itemCount () inline
Definition at line 73 of file qdatawidgetmapper.cpp.
     {
         return orientation == Qt::Horizontal
             ? model->rowCount(rootIndex)
             : model->columnCount(rootIndex);
     }
populate() [1/2]
void QDataWidgetMapperPrivate::populate ()
Definition at line 172 of file qdatawidgetmapper.cpp.
Referenced by _q_closeEditor(), _q_dataChanged(), and flipEventFilters().
 {
     for (int i = 0; i < widgetMap.count(); ++i)
         populate(widgetMap[i]);
 }
populate() [2/2]
void QDataWidgetMapperPrivate::populate (WidgetMapper & m)
Definition at line 160 of file qdatawidgetmapper.cpp.
 {
     if (m.widget.isNull())
         return;
     m.currentIndex = indexAt(m.section);
     if (m.property.isEmpty())
         delegate->setEditorData(m.widget, m.currentIndex);
     else
         m.widget->setProperty(m.property, m.currentIndex.data(Qt::EditRole));
 }
Properties
currentTopLeft
QPersistentModelIndex QDataWidgetMapperPrivate::currentTopLeft
Definition at line 71 of file qdatawidgetmapper.cpp.
delegate
QAbstractItemDelegate* QDataWidgetMapperPrivate::delegate
Definition at line 67 of file qdatawidgetmapper.cpp.
model
QAbstractItemModel* QDataWidgetMapperPrivate::model
Definition at line 66 of file qdatawidgetmapper.cpp.
orientation
Qt::Orientation QDataWidgetMapperPrivate::orientation
Definition at line 68 of file qdatawidgetmapper.cpp.
Referenced by currentIdx(), indexAt(), and itemCount().
rootIndex
QPersistentModelIndex QDataWidgetMapperPrivate::rootIndex
Definition at line 70 of file qdatawidgetmapper.cpp.
Referenced by _q_dataChanged().
submitPolicy
QDataWidgetMapper::SubmitPolicy QDataWidgetMapperPrivate::submitPolicy
Definition at line 69 of file qdatawidgetmapper.cpp.
Referenced by _q_commitData().
widgetMap
QList<WidgetMapper> QDataWidgetMapperPrivate::widgetMap
Definition at line 130 of file qdatawidgetmapper.cpp.
Referenced by _q_closeEditor(), _q_commitData(), _q_dataChanged(), findWidget(), flipEventFilters(), and populate().
The documentation for this class was generated from the following file:
/src/gui/itemviews/qdatawidgetmapper.cpp