Qt 4.8: QCoreGraphicsPaintEngine Class Reference
QCoreGraphicsPaintEngine Class Reference
#include <qpaintengine_mac_p.h>
Public Functions
bool begin (QPaintDevice *pdev)
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
void drawImage (const QRectF &r, const QImage &pm, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
void drawPoints (const QPointF *p, int pointCount)
Draws the first pointCount points in the buffer points.
void drawPoints (const QPoint *p, int pointCount)
Draws the first pointCount points in the buffer points.
void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
void drawTextItem (const QPointF &pos, const QTextItem &item)
This function draws the text item textItem at position p.
void drawTiledPixmap (const QRectF &r, const QPixmap &pixmap, const QPointF &s)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
bool end ()
Reimplement this function to finish painting on the current paint device.
CGContextRef handle () const
QCoreGraphicsPaintEngine ()
QPainter::RenderHints supportedRenderHints () const
bool supportsTransformations (qreal, const QTransform &) const
Type type () const
Reimplement this function to return the paint engine Type.
void updateBrush (const QBrush &brush, const QPointF &pt)
void updateClipPath (const QPainterPath &path, Qt::ClipOperation op)
void updateClipRegion (const QRegion &region, Qt::ClipOperation op)
void updateCompositionMode (QPainter::CompositionMode mode)
void updateFont (const QFont &font)
void updateMatrix (const QTransform &matrix)
void updateOpacity (qreal opacity)
void updatePen (const QPen &pen)
void updateRenderHints (QPainter::RenderHints hints)
void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
void updateTransform (const QTransform &matrix)
~QCoreGraphicsPaintEngine ()
Public Functions inherited from QPaintEngine
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual ~QPaintEngine ()
Destroys the paint engine.
Static Public Functions
static void cleanup ()
static void clearColorSpace (QWidget *w)
static void initialize ()
static CGColorSpaceRef macDisplayColorSpace (const QWidget *widget=0)
static CGColorSpaceRef macGenericColorSpace ()
Protected Functions
QCoreGraphicsPaintEngine (QPaintEnginePrivate &dptr)
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Static Private Functions
static void cleanUpMacColorSpaces ()
Static Private Attributes
static QHash< QWidget *, CGColorSpaceRef > m_displayColorSpaceHash
static CGColorSpaceRef m_genericColorSpace = 0
static bool m_postRoutineRegistered = false
Friends
class QMacPrintEngine
class QMacPrintEnginePrivate
void qt_color_profile_changed (CFNotificationCenterRef center, void *, CFStringRef, const void *, CFDictionaryRef)
void qt_mac_display_change_callbk (CGDirectDisplayID, CGDisplayChangeSummaryFlags, void *)
Additional Inherited Members
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 67 of file qpaintengine_mac_p.h.
Constructors and Destructors
QCoreGraphicsPaintEngine() [1/2]
QCoreGraphicsPaintEngine::QCoreGraphicsPaintEngine ()
Definition at line 544 of file qpaintengine_mac.cpp.
 : QPaintEngine(*(new QCoreGraphicsPaintEnginePrivate), qt_mac_cg_features())
 {
 }
~QCoreGraphicsPaintEngine()
QCoreGraphicsPaintEngine::~QCoreGraphicsPaintEngine ()
Definition at line 554 of file qpaintengine_mac.cpp.
 {
 }
QCoreGraphicsPaintEngine() [2/2]
QCoreGraphicsPaintEngine::QCoreGraphicsPaintEngine (QPaintEnginePrivate & dptr) protected
Definition at line 549 of file qpaintengine_mac.cpp.
 : QPaintEngine(dptr, qt_mac_cg_features())
 {
 }
Functions
begin()
bool QCoreGraphicsPaintEngine::begin (QPaintDevice * pdev) virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Implements QPaintEngine.
Definition at line 559 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     if(isActive()) {                         // already active painting
         qWarning("QCoreGraphicsPaintEngine::begin: Painter already active");
         return false;
     }
     //initialization
     d->pdev = pdev;
     d->complexXForm = false;
     d->cosmeticPen = QCoreGraphicsPaintEnginePrivate::CosmeticSetPenWidth;
     d->cosmeticPenSize = 1;
     d->current.clipEnabled = false;
     d->pixelSize = QPoint(1,1);
     d->hd = qt_mac_cg_context(pdev);
     if(d->hd) {
         d->saveGraphicsState();
         d->orig_xform = CGContextGetCTM(d->hd);
         if (d->shading) {
             CGShadingRelease(d->shading);
             d->shading = 0;
         }
         d->setClip(0);  //clear the context's clipping
     }
     setActive(true);
     if(d->pdev->devType() == QInternal::Widget) {                    // device is a widget
         QWidget *w = (QWidget*)d->pdev;
         bool unclipped = w->testAttribute(Qt::WA_PaintUnclipped);
         if((w->windowType() == Qt::Desktop)) {
             if(!unclipped)
                 qWarning("QCoreGraphicsPaintEngine::begin: Does not support clipped desktop on Mac OS X");
             // ## need to do [qt_mac_window_for(w) makeKeyAndOrderFront]; (need to rename the file)
         } else if(unclipped) {
             qWarning("QCoreGraphicsPaintEngine::begin: Does not support unclipped painting");
         }
     } else if(d->pdev->devType() == QInternal::Pixmap) {             // device is a pixmap
         QPixmap *pm = (QPixmap*)d->pdev;
         if(pm->isNull()) {
             qWarning("QCoreGraphicsPaintEngine::begin: Cannot paint null pixmap");
             end();
             return false;
         }
     }
     setDirty(QPaintEngine::DirtyPen);
     setDirty(QPaintEngine::DirtyBrush);
     setDirty(QPaintEngine::DirtyBackground);
     setDirty(QPaintEngine::DirtyHints);
     return true;
 }
cleanup()
void QCoreGraphicsPaintEngine::cleanup () static
Definition at line 1066 of file qpaintengine_mac.cpp.
Referenced by type().
 {
 }
cleanUpMacColorSpaces()
void QCoreGraphicsPaintEngine::cleanUpMacColorSpaces () static private
Definition at line 366 of file qpaintengine_mac.cpp.
Referenced by macDisplayColorSpace(), macGenericColorSpace(), qt_color_profile_changed(), and qt_mac_display_change_callbk().
 {
     if (m_genericColorSpace) {
         CFRelease(m_genericColorSpace);
         m_genericColorSpace = 0;
     }
     QHash<QWidget*, CGColorSpaceRef>::const_iterator it = m_displayColorSpaceHash.constBegin();
     while (it != m_displayColorSpaceHash.constEnd()) {
         if (it.value())
             CFRelease(it.value());
         ++it;
     }
     m_displayColorSpaceHash.clear();
 }
clearColorSpace()
void QCoreGraphicsPaintEngine::clearColorSpace (QWidget * w) static
Definition at line 1070 of file qpaintengine_mac.cpp.
Referenced by QWidget::destroy(), and type().
 {
     m_displayColorSpaceHash.remove(w);
 }
drawEllipse() [1/2]
void QCoreGraphicsPaintEngine::drawEllipse (const QRectF & rect) virtual
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
The default implementation calls drawPolygon().
Reimplemented from QPaintEngine.
Definition at line 909 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     if (state->compositionMode() == QPainter::CompositionMode_Destination)
         return;
     CGMutablePathRef path = CGPathCreateMutable();
     CGAffineTransform transform = CGAffineTransformMakeScale(r.width() / r.height(), 1);
     CGPathAddArc(path, &transform,(r.x() + (r.width() / 2)) / (r.width() / r.height()),
             r.y() + (r.height() / 2), r.height() / 2, 0, (2 * M_PI), false);
     d->drawPath(QCoreGraphicsPaintEnginePrivate::CGFill | QCoreGraphicsPaintEnginePrivate::CGStroke,
             path);
     CGPathRelease(path);
 }
drawEllipse() [2/2]
void QCoreGraphicsPaintEngine::drawEllipse (const QRect & r) inline virtual
The default implementation of this function calls the floating point version of this function.
Reimplemented from QPaintEngine.
Definition at line 121 of file qpaintengine_mac_p.h.
 { QPaintEngine::drawEllipse(r); }
drawImage()
void QCoreGraphicsPaintEngine::drawImage (const QRectF & r, const QImage & pm, const QRectF & sr, Qt::ImageConversionFlags flags = Qt::AutoColor) virtual
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
Reimplemented from QPaintEngine.
Definition at line 1043 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_UNUSED(flags);
     Q_ASSERT(isActive());
     if (img.isNull() || state->compositionMode() == QPainter::CompositionMode_Destination)
         return;
     const QImage *image;
     QCFType<CGImageRef> cgimage = qt_mac_createCGImageFromQImage(img, &image);
     CGRect rect = CGRectMake(r.x(), r.y(), r.width(), r.height());
     if (QRectF(0, 0, img.width(), img.height()) != sr)
         cgimage = CGImageCreateWithImageInRect(cgimage, CGRectMake(sr.x(), sr.y(),
                                                sr.width(), sr.height()));
     qt_mac_drawCGImage(d->hd, &rect, cgimage);
 }
drawLines() [1/2]
void QCoreGraphicsPaintEngine::drawLines (const QLineF * lines, int lineCount) virtual
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngine.
Definition at line 950 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     if (state->compositionMode() == QPainter::CompositionMode_Destination)
         return;
     CGMutablePathRef path = CGPathCreateMutable();
     for(int i = 0; i < lineCount; i++) {
         const QPointF start = lines[i].p1(), end = lines[i].p2();
         CGPathMoveToPoint(path, 0, start.x(), start.y());
         CGPathAddLineToPoint(path, 0, end.x(), end.y());
     }
     d->drawPath(QCoreGraphicsPaintEnginePrivate::CGStroke, path);
     CGPathRelease(path);
 }
drawLines() [2/2]
void QCoreGraphicsPaintEngine::drawLines (const QLine * lines, int lineCount) inline virtual
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Reimplemented from QPaintEngine.
Definition at line 118 of file qpaintengine_mac_p.h.
 { QPaintEngine::drawLines(lines, lineCount); }
drawPath()
void QCoreGraphicsPaintEngine::drawPath (const QPainterPath & path) virtual
The default implementation ignores the path and does nothing.
Reimplemented from QPaintEngine.
Definition at line 835 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     if (state->compositionMode() == QPainter::CompositionMode_Destination)
         return;
     CGMutablePathRef path = qt_mac_compose_path(p);
     uchar ops = QCoreGraphicsPaintEnginePrivate::CGStroke;
     if(p.fillRule() == Qt::WindingFill)
         ops |= QCoreGraphicsPaintEnginePrivate::CGFill;
     else
         ops |= QCoreGraphicsPaintEnginePrivate::CGEOFill;
     CGContextBeginPath(d->hd);
     d->drawPath(ops, path);
     CGPathRelease(path);
 }
drawPixmap()
void QCoreGraphicsPaintEngine::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Implements QPaintEngine.
Definition at line 968 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     if (state->compositionMode() == QPainter::CompositionMode_Destination)
         return;
     if(pm.isNull())
         return;
     bool differentSize = (QRectF(0, 0, pm.width(), pm.height()) != sr), doRestore = false;
     CGRect rect = CGRectMake(r.x(), r.y(), r.width(), r.height());
     QCFType<CGImageRef> image;
     bool isBitmap = (pm.depth() == 1);
     if (isBitmap) {
         doRestore = true;
         d->saveGraphicsState();
         const QColor &col = d->current.pen.color();
         CGContextSetFillColorWithColor(d->hd, cgColorForQColor(col, d->pdev));
         image = qt_mac_create_imagemask(pm, sr);
     } else if (differentSize) {
         QCFType<CGImageRef> img = pm.toMacCGImageRef();
         image = CGImageCreateWithImageInRect(img, CGRectMake(qRound(sr.x()), qRound(sr.y()), qRound(sr.width()), qRound(sr.height())));
     } else {
         image = (CGImageRef)pm.macCGHandle();
     }
     qt_mac_drawCGImage(d->hd, &rect, image);
     if (doRestore)
         d->restoreGraphicsState();
 }
drawPoints() [1/2]
void QCoreGraphicsPaintEngine::drawPoints (const QPointF * points, int pointCount) virtual
Draws the first pointCount points in the buffer points.
Reimplemented from QPaintEngine.
Definition at line 875 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     if (state->compositionMode() == QPainter::CompositionMode_Destination)
         return;
     if (d->current.pen.capStyle() == Qt::FlatCap)
         CGContextSetLineCap(d->hd, kCGLineCapSquare);
     CGMutablePathRef path = CGPathCreateMutable();
     for(int i=0; i < pointCount; i++) {
         float x = points[i].x(), y = points[i].y();
         CGPathMoveToPoint(path, 0, x, y);
         CGPathAddLineToPoint(path, 0, x+0.001, y);
     }
     bool doRestore = false;
     if(d->cosmeticPen == QCoreGraphicsPaintEnginePrivate::CosmeticNone && !(state->renderHints() & QPainter::Antialiasing)) {
         //we don't want adjusted pens for point rendering
         doRestore = true;
         d->saveGraphicsState();
         CGContextSetLineWidth(d->hd, d->current.pen.widthF());
     }
     d->drawPath(QCoreGraphicsPaintEnginePrivate::CGStroke, path);
     if (doRestore)
         d->restoreGraphicsState();
     CGPathRelease(path);
     if (d->current.pen.capStyle() == Qt::FlatCap)
         CGContextSetLineCap(d->hd, kCGLineCapButt);
 }
drawPoints() [2/2]
void QCoreGraphicsPaintEngine::drawPoints (const QPoint * points, int pointCount) inline virtual
Draws the first pointCount points in the buffer points.
The default implementation converts the first pointCount QPoints in points to QPointFs and calls the floating point version of drawPoints.
Reimplemented from QPaintEngine.
Definition at line 120 of file qpaintengine_mac_p.h.
 { QPaintEngine::drawPoints(p, pointCount); }
drawPolygon() [1/2]
void QCoreGraphicsPaintEngine::drawPolygon (const QPointF * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QPaintEngine.
Definition at line 927 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     if (state->compositionMode() == QPainter::CompositionMode_Destination)
         return;
     CGMutablePathRef path = CGPathCreateMutable();
     CGPathMoveToPoint(path, 0, points[0].x(), points[0].y());
     for(int x = 1; x < pointCount; ++x)
         CGPathAddLineToPoint(path, 0, points[x].x(), points[x].y());
     if(mode != PolylineMode && points[0] != points[pointCount-1])
         CGPathAddLineToPoint(path, 0, points[0].x(), points[0].y());
     uint op = QCoreGraphicsPaintEnginePrivate::CGStroke;
     if (mode != PolylineMode)
         op |= mode == OddEvenMode ? QCoreGraphicsPaintEnginePrivate::CGEOFill
             : QCoreGraphicsPaintEnginePrivate::CGFill;
     d->drawPath(op, path);
     CGPathRelease(path);
 }
drawPolygon() [2/2]
void QCoreGraphicsPaintEngine::drawPolygon (const QPoint * points, int pointCount, PolygonDrawMode mode) inline virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QPaintEngine.
Definition at line 122 of file qpaintengine_mac_p.h.
     { QPaintEngine::drawPolygon(points, pointCount, mode); }
drawRects() [1/2]
void QCoreGraphicsPaintEngine::drawRects (const QRectF * rects, int rectCount) virtual
Draws the first rectCount rectangles in the buffer rects.
The default implementation of this function calls drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngine.
Definition at line 855 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     if (state->compositionMode() == QPainter::CompositionMode_Destination)
         return;
     for (int i=0; i<rectCount; ++i) {
         QRectF r = rects[i];
         CGMutablePathRef path = CGPathCreateMutable();
         CGPathAddRect(path, 0, qt_mac_compose_rect(r));
         d->drawPath(QCoreGraphicsPaintEnginePrivate::CGFill|QCoreGraphicsPaintEnginePrivate::CGStroke,
                 path);
         CGPathRelease(path);
     }
 }
drawRects() [2/2]
void QCoreGraphicsPaintEngine::drawRects (const QRect * rects, int rectCount) inline virtual
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Reimplemented from QPaintEngine.
Definition at line 119 of file qpaintengine_mac_p.h.
 { QPaintEngine::drawRects(rects, rectCount); }
drawTextItem()
void QCoreGraphicsPaintEngine::drawTextItem (const QPointF & p, const QTextItem & textItem) virtual
This function draws the text item textItem at position p.
The default implementation of this function converts the text to a QPainterPath and paints the resulting path.
Reimplemented from QPaintEngine.
Definition at line 1126 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     if (d->current.transform.type() == QTransform::TxProject
 #ifndef QMAC_NATIVE_GRADIENTS
         || painter()->pen().brush().gradient()  //Just let the base engine "emulate" the gradient
 #endif
         ) {
         QPaintEngine::drawTextItem(pos, item);
         return;
     }
     if (state->compositionMode() == QPainter::CompositionMode_Destination)
         return;
     const QTextItemInt &ti = static_cast<const QTextItemInt &>(item);
     QPen oldPen = painter()->pen();
     QBrush oldBrush = painter()->brush();
     QPointF oldBrushOrigin = painter()->brushOrigin();
     updatePen(Qt::NoPen);
     updateBrush(oldPen.brush(), QPointF(0, 0));
     Q_ASSERT(type() == QPaintEngine::CoreGraphics);
     QFontEngine *fe = ti.fontEngine;
     const bool textAA = state->renderHints() & QPainter::TextAntialiasing && fe->fontDef.pointSize > qt_antialiasing_threshold && !(fe->fontDef.styleStrategy & QFont::NoAntialias);
     const bool lineAA = state->renderHints() & QPainter::Antialiasing;
     if(textAA != lineAA)
         CGContextSetShouldAntialias(d->hd, textAA);
     if (ti.glyphs.numGlyphs) {
         switch (fe->type()) {
         case QFontEngine::Mac:
 #ifdef QT_MAC_USE_COCOA
             static_cast<QCoreTextFontEngine *>(fe)->draw(d->hd, pos.x(), pos.y(), ti, paintDevice()->height());
 #else
             static_cast<QFontEngineMac *>(fe)->draw(d->hd, pos.x(), pos.y(), ti, paintDevice()->height());
 #endif
             break;
         case QFontEngine::Box:
             d->drawBoxTextItem(pos, ti);
             break;
         default:
             break;
         }
     }
     if(textAA != lineAA)
         CGContextSetShouldAntialias(d->hd, !textAA);
     updatePen(oldPen);
     updateBrush(oldBrush, oldBrushOrigin);
 }
drawTiledPixmap()
void QCoreGraphicsPaintEngine::drawTiledPixmap (const QRectF & rect, const QPixmap & pixmap, const QPointF & p) virtual
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
The pixmap will be drawn repeatedly until the rect is filled.
Reimplemented from QPaintEngine.
Definition at line 1082 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     if (state->compositionMode() == QPainter::CompositionMode_Destination)
         return;
     //save the old state
     d->saveGraphicsState();
     //setup the pattern
     QMacPattern *qpattern = new QMacPattern;
     qpattern->data.pixmap = pixmap;
     qpattern->foreground = d->current.pen.color();
     qpattern->pdev = d->pdev;
     CGPatternCallbacks callbks;
     callbks.version = 0;
     callbks.drawPattern = qt_mac_draw_pattern;
     callbks.releaseInfo = qt_mac_dispose_pattern;
     const int width = qpattern->width(), height = qpattern->height();
     CGAffineTransform trans = CGContextGetCTM(d->hd);
     CGPatternRef pat = CGPatternCreate(qpattern, CGRectMake(0, 0, width, height),
             trans, width, height,
             kCGPatternTilingNoDistortion, true, &callbks);
     CGColorSpaceRef cs = CGColorSpaceCreatePattern(0);
     CGContextSetFillColorSpace(d->hd, cs);
     CGFloat component = 1.0; //just one
     CGContextSetFillPattern(d->hd, pat, &component);
     CGSize phase = CGSizeApplyAffineTransform(CGSizeMake(-(p.x()-r.x()), -(p.y()-r.y())), trans);
     CGContextSetPatternPhase(d->hd, phase);
     //fill the rectangle
     CGRect mac_rect = CGRectMake(r.x(), r.y(), r.width(), r.height());
     CGContextFillRect(d->hd, mac_rect);
     //restore the state
     d->restoreGraphicsState();
     //cleanup
     CGColorSpaceRelease(cs);
     CGPatternRelease(pat);
 }
end()
bool QCoreGraphicsPaintEngine::end () virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Implements QPaintEngine.
Definition at line 615 of file qpaintengine_mac.cpp.
Referenced by begin(), and drawLines().
 {
     Q_D(QCoreGraphicsPaintEngine);
     setActive(false);
     if(d->pdev->devType() == QInternal::Widget && static_cast<QWidget*>(d->pdev)->windowType() == Qt::Desktop) {
 #ifndef QT_MAC_USE_COCOA
         HideWindow(qt_mac_window_for(static_cast<QWidget*>(d->pdev)));
 #else
 //        // ### need to do [qt_mac_window_for(static_cast<QWidget *>(d->pdev)) orderOut]; (need to rename)
 #endif
     }
     if(d->shading) {
         CGShadingRelease(d->shading);
         d->shading = 0;
     }
     d->pdev = 0;
     if(d->hd) {
         d->restoreGraphicsState();
         CGContextSynchronize(d->hd);
         CGContextRelease(d->hd);
         d->hd = 0;
     }
     return true;
 }
handle()
CGContextRef QCoreGraphicsPaintEngine::handle () const
Definition at line 1076 of file qpaintengine_mac.cpp.
Referenced by type().
 {
     return d_func()->hd;
 }
initialize()
void QCoreGraphicsPaintEngine::initialize () static
Definition at line 1062 of file qpaintengine_mac.cpp.
Referenced by qt_init(), and type().
 {
 }
macDisplayColorSpace()
CGColorSpaceRef QCoreGraphicsPaintEngine::macDisplayColorSpace (const QWidget * widget = 0) static
Definition at line 319 of file qpaintengine_mac.cpp.
Referenced by QMacPixmapData::macCreateCGImageRef(), qt_mac_colorSpaceForDeviceType(), and QNativeImage::systemFormat().
 {
     // The color space depends on which screen the widget's window is on.
     // widget == 0 is a spacial case where we use the main display.
     QWidget *window = widget ? widget->window() : 0;
     // Check for cached color space and return if found.
     if (m_displayColorSpaceHash.contains(window))
         return m_displayColorSpaceHash.value(window);
     // Find which display the window is on.
     CGDirectDisplayID displayID;
     if (window == 0) {
         displayID = CGMainDisplayID();
     } else {
         const QRect &qrect = window->geometry();
         CGRect rect = CGRectMake(qrect.x(), qrect.y(), qrect.width(), qrect.height());
         CGDisplayCount throwAway;
         CGDisplayErr dErr = CGGetDisplaysWithRect(rect, 1, &displayID, &throwAway);
         if (dErr != kCGErrorSuccess)
             displayID = CGMainDisplayID();
     }
     // Get the color space from the display profile.
     CGColorSpaceRef colorSpace = 0;
     CMProfileRef displayProfile = 0;
     CMError err = CMGetProfileByAVID((CMDisplayIDType)displayID, &displayProfile);
     if (err == noErr) {
         colorSpace = CGColorSpaceCreateWithPlatformColorSpace(displayProfile);
         CMCloseProfile(displayProfile);
     }
     // Fallback: use generic DeviceRGB
     if (colorSpace == 0)
         colorSpace = CGColorSpaceCreateDeviceRGB();
     // Install cleanup routines
     if (!m_postRoutineRegistered) {
         m_postRoutineRegistered = true;
         qAddPostRoutine(QCoreGraphicsPaintEngine::cleanUpMacColorSpaces);
     }
     // Cache and return.
     m_displayColorSpaceHash.insert(window, colorSpace);
     return colorSpace;
 }
macGenericColorSpace()
CGColorSpaceRef QCoreGraphicsPaintEngine::macGenericColorSpace () static
Definition at line 295 of file qpaintengine_mac.cpp.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QFontEngineMac::imageForGlyph(), qt_mac_createCGImageFromQImage(), qt_mac_grabScreenRect(), qt_mac_image_to_cgimage(), and QCoreGraphicsPaintEnginePrivate::setFillBrush().
 {
 #if 0
     if (!m_genericColorSpace) {
 #if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_4
         if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_4) {
             m_genericColorSpace = CGColorSpaceCreateWithName(kCGColorSpaceGenericRGB);
         } else
 #endif
         {
             m_genericColorSpace = CGColorSpaceCreateDeviceRGB();
         }
         if (!m_postRoutineRegistered) {
             m_postRoutineRegistered = true;
             qAddPostRoutine(QCoreGraphicsPaintEngine::cleanUpMacColorSpaces);
         }
     }
     return m_genericColorSpace;
 #else
     // Just return the main display colorspace for the moment.
     return macDisplayColorSpace();
 #endif
 }
supportedRenderHints()
QPainter::RenderHints QCoreGraphicsPaintEngine::supportedRenderHints () const
Definition at line 1183 of file qpaintengine_mac.cpp.
Referenced by type().
 {
     return QPainter::RenderHints(QPainter::Antialiasing | QPainter::TextAntialiasing | QPainter::SmoothPixmapTransform);
 }
supportsTransformations()
bool QCoreGraphicsPaintEngine::supportsTransformations (qreal , const QTransform &) const inline
Definition at line 125 of file qpaintengine_mac_p.h.
 { return true; };
type()
Type QCoreGraphicsPaintEngine::type () const inline virtual
Reimplement this function to return the paint engine Type.
Implements QPaintEngine.
Definition at line 107 of file qpaintengine_mac_p.h.
Referenced by drawTextItem().
 { return QPaintEngine::CoreGraphics; }
updateBrush()
void QCoreGraphicsPaintEngine::updateBrush (const QBrush & brush, const QPointF & pt)
Definition at line 712 of file qpaintengine_mac.cpp.
Referenced by drawTextItem(), and updateState().
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     d->current.brush = brush;
 #ifdef QT_MAC_USE_NATIVE_GRADIENTS
     // Quartz supports only pad spread
     if (const QGradient *gradient = brush.gradient()) {
         if (drawGradientNatively(gradient)) {
             gccaps |= QPaintEngine::LinearGradientFill | QPaintEngine::RadialGradientFill;
         } else {
             gccaps &= ~(QPaintEngine::LinearGradientFill | QPaintEngine::RadialGradientFill);
         }
     }
 #endif
     if (d->shading) {
         CGShadingRelease(d->shading);
         d->shading = 0;
     }
     d->setFillBrush(brushOrigin);
 }
updateClipPath()
void QCoreGraphicsPaintEngine::updateClipPath (const QPainterPath & path, Qt::ClipOperation op)
Definition at line 770 of file qpaintengine_mac.cpp.
Referenced by updateState().
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     if(op == Qt::NoClip) {
         if(d->current.clipEnabled) {
             d->current.clipEnabled = false;
             d->current.clip = QRegion();
             d->setClip(0);
         }
     } else {
         if(!d->current.clipEnabled)
             op = Qt::ReplaceClip;
         d->current.clipEnabled = true;
         QRegion clipRegion(p.toFillPolygon().toPolygon(), p.fillRule());
         if(op == Qt::ReplaceClip) {
             d->current.clip = clipRegion;
             d->setClip(0);
             if(p.isEmpty()) {
                 CGRect rect = CGRectMake(0, 0, 0, 0);
                 CGContextClipToRect(d->hd, rect);
             } else {
                 CGMutablePathRef path = qt_mac_compose_path(p);
                 CGContextBeginPath(d->hd);
                 CGContextAddPath(d->hd, path);
                 if(p.fillRule() == Qt::WindingFill)
                     CGContextClip(d->hd);
                 else
                     CGContextEOClip(d->hd);
                 CGPathRelease(path);
             }
         } else if(op == Qt::IntersectClip) {
             d->current.clip = d->current.clip.intersected(clipRegion);
             d->setClip(&d->current.clip);
         } else if(op == Qt::UniteClip) {
             d->current.clip = d->current.clip.united(clipRegion);
             d->setClip(&d->current.clip);
         }
     }
 }
updateClipRegion()
void QCoreGraphicsPaintEngine::updateClipRegion (const QRegion & region, Qt::ClipOperation op)
Definition at line 812 of file qpaintengine_mac.cpp.
Referenced by updateState().
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     if(op == Qt::NoClip) {
         d->current.clipEnabled = false;
         d->current.clip = QRegion();
         d->setClip(0);
     } else {
         if(!d->current.clipEnabled)
             op = Qt::ReplaceClip;
         d->current.clipEnabled = true;
         if(op == Qt::IntersectClip)
             d->current.clip = d->current.clip.intersected(clipRegion);
         else if(op == Qt::ReplaceClip)
             d->current.clip = clipRegion;
         else if(op == Qt::UniteClip)
             d->current.clip = d->current.clip.united(clipRegion);
         d->setClip(&d->current.clip);
     }
 }
updateCompositionMode()
void QCoreGraphicsPaintEngine::updateCompositionMode (QPainter::CompositionMode mode)
Definition at line 1206 of file qpaintengine_mac.cpp.
Referenced by updateState().
 {
 #if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
     if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_5) {
         int cg_mode = kCGBlendModeNormal;
         switch(mode) {
         case QPainter::CompositionMode_Multiply:
             cg_mode = kCGBlendModeMultiply;
             break;
         case QPainter::CompositionMode_Screen:
             cg_mode = kCGBlendModeScreen;
             break;
         case QPainter::CompositionMode_Overlay:
             cg_mode = kCGBlendModeOverlay;
             break;
         case QPainter::CompositionMode_Darken:
             cg_mode = kCGBlendModeDarken;
             break;
         case QPainter::CompositionMode_Lighten:
             cg_mode = kCGBlendModeLighten;
             break;
         case QPainter::CompositionMode_ColorDodge:
             cg_mode = kCGBlendModeColorDodge;
             break;
         case QPainter::CompositionMode_ColorBurn:
             cg_mode = kCGBlendModeColorBurn;
             break;
         case QPainter::CompositionMode_HardLight:
             cg_mode = kCGBlendModeHardLight;
             break;
         case QPainter::CompositionMode_SoftLight:
             cg_mode = kCGBlendModeSoftLight;
             break;
         case QPainter::CompositionMode_Difference:
             cg_mode = kCGBlendModeDifference;
             break;
         case QPainter::CompositionMode_Exclusion:
             cg_mode = kCGBlendModeExclusion;
             break;
         case QPainter::CompositionMode_Plus:
             cg_mode = kCGBlendModePlusLighter;
             break;
         case QPainter::CompositionMode_SourceOver:
             cg_mode = kCGBlendModeNormal;
             break;
         case QPainter::CompositionMode_DestinationOver:
             cg_mode = kCGBlendModeDestinationOver;
             break;
         case QPainter::CompositionMode_Clear:
             cg_mode = kCGBlendModeClear;
             break;
         case QPainter::CompositionMode_Source:
             cg_mode = kCGBlendModeCopy;
             break;
         case QPainter::CompositionMode_Destination:
             cg_mode = -1;
             break;
         case QPainter::CompositionMode_SourceIn:
             cg_mode = kCGBlendModeSourceIn;
             break;
         case QPainter::CompositionMode_DestinationIn:
             cg_mode = kCGCompositeModeDestinationIn;
             break;
         case QPainter::CompositionMode_SourceOut:
             cg_mode = kCGBlendModeSourceOut;
             break;
         case QPainter::CompositionMode_DestinationOut:
             cg_mode = kCGBlendModeDestinationOver;
             break;
         case QPainter::CompositionMode_SourceAtop:
             cg_mode = kCGBlendModeSourceAtop;
             break;
         case QPainter::CompositionMode_DestinationAtop:
             cg_mode = kCGBlendModeDestinationAtop;
             break;
         case QPainter::CompositionMode_Xor:
             cg_mode = kCGBlendModeXOR;
             break;
         default:
             break;
         }
         if (cg_mode > -1) {
             CGContextSetBlendMode(d_func()->hd, CGBlendMode(cg_mode));
         }
     } else
 #endif
     // The standard porter duff ops.
     if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_3
             && mode <= QPainter::CompositionMode_Xor) {
         int cg_mode = kCGCompositeModeCopy;
         switch (mode) {
         case QPainter::CompositionMode_SourceOver:
             cg_mode = kCGCompositeModeSourceOver;
             break;
         case QPainter::CompositionMode_DestinationOver:
             cg_mode = kCGCompositeModeDestinationOver;
             break;
         case QPainter::CompositionMode_Clear:
             cg_mode = kCGCompositeModeClear;
             break;
         default:
             qWarning("QCoreGraphicsPaintEngine: Unhandled composition mode %d", (int)mode);
             break;
         case QPainter::CompositionMode_Source:
             cg_mode = kCGCompositeModeCopy;
             break;
         case QPainter::CompositionMode_Destination:
             cg_mode = CGCompositeMode(-1);
             break;
         case QPainter::CompositionMode_SourceIn:
             cg_mode = kCGCompositeModeSourceIn;
             break;
         case QPainter::CompositionMode_DestinationIn:
             cg_mode = kCGCompositeModeDestinationIn;
             break;
         case QPainter::CompositionMode_SourceOut:
             cg_mode = kCGCompositeModeSourceOut;
             break;
         case QPainter::CompositionMode_DestinationOut:
             cg_mode = kCGCompositeModeDestinationOut;
             break;
         case QPainter::CompositionMode_SourceAtop:
             cg_mode = kCGCompositeModeSourceAtop;
             break;
         case QPainter::CompositionMode_DestinationAtop:
             cg_mode = kCGCompositeModeDestinationAtop;
             break;
         case QPainter::CompositionMode_Xor:
             cg_mode = kCGCompositeModeXOR;
             break;
         }
         if (cg_mode > -1)
             CGContextSetCompositeOperation(d_func()->hd, CGCompositeMode(cg_mode));
     } else {
 #if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_4)
         bool needPrivateAPI = false;
         if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_4) {
             int cg_mode = kCGBlendModeNormal;
             switch (mode) {
             case QPainter::CompositionMode_Multiply:
                 cg_mode = kCGBlendModeMultiply;
                 break;
             case QPainter::CompositionMode_Screen:
                 cg_mode = kCGBlendModeScreen;
                 break;
             case QPainter::CompositionMode_Overlay:
                 cg_mode = kCGBlendModeOverlay;
                 break;
             case QPainter::CompositionMode_Darken:
                 cg_mode = kCGBlendModeDarken;
                 break;
             case QPainter::CompositionMode_Lighten:
                 cg_mode = kCGBlendModeLighten;
                 break;
             case QPainter::CompositionMode_ColorDodge:
                 cg_mode = kCGBlendModeColorDodge;
                 break;
             case QPainter::CompositionMode_ColorBurn:
                 cg_mode = kCGBlendModeColorBurn;
                 break;
             case QPainter::CompositionMode_HardLight:
                 cg_mode = kCGBlendModeHardLight;
                 break;
             case QPainter::CompositionMode_SoftLight:
                 cg_mode = kCGBlendModeSoftLight;
                 break;
             case QPainter::CompositionMode_Difference:
                 cg_mode = kCGBlendModeDifference;
                 break;
             case QPainter::CompositionMode_Exclusion:
                 cg_mode = kCGBlendModeExclusion;
                 break;
             case QPainter::CompositionMode_Plus:
                 needPrivateAPI = true;
                 cg_mode = kCGCompositeModePlusLighter;
                 break;
             default:
                 break;
             }
             if (!needPrivateAPI)
                 CGContextSetBlendMode(d_func()->hd, CGBlendMode(cg_mode));
             else
                 CGContextSetCompositeOperation(d_func()->hd, CGCompositeMode(cg_mode));
         }
 #endif
     }
 }
updateFont()
void QCoreGraphicsPaintEngine::updateFont (const QFont & font)
Definition at line 744 of file qpaintengine_mac.cpp.
Referenced by updateState().
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     updatePen(d->current.pen);
 }
updateMatrix()
void QCoreGraphicsPaintEngine::updateMatrix (const QTransform & matrix)
Definition at line 752 of file qpaintengine_mac.cpp.
Referenced by updateState().
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     if (qt_is_nan(transform.m11()) || qt_is_nan(transform.m12()) || qt_is_nan(transform.m13())
     || qt_is_nan(transform.m21()) || qt_is_nan(transform.m22()) || qt_is_nan(transform.m23())
     || qt_is_nan(transform.m31()) || qt_is_nan(transform.m32()) || qt_is_nan(transform.m33()))
     return;
     d->current.transform = transform;
     d->setTransform(transform.isIdentity() ? 0 : &transform);
     d->complexXForm = (transform.m11() != 1 || transform.m22() != 1
             || transform.m12() != 0 || transform.m21() != 0);
     d->pixelSize = d->devicePixelSize(d->hd);
 }
updateOpacity()
void QCoreGraphicsPaintEngine::updateOpacity (qreal opacity)
Definition at line 737 of file qpaintengine_mac.cpp.
Referenced by updateState().
 {
     Q_D(QCoreGraphicsPaintEngine);
     CGContextSetAlpha(d->hd, opacity);
 }
updatePen()
void QCoreGraphicsPaintEngine::updatePen (const QPen & pen)
Definition at line 703 of file qpaintengine_mac.cpp.
Referenced by drawTextItem(), updateFont(), and updateState().
 {
     Q_D(QCoreGraphicsPaintEngine);
     Q_ASSERT(isActive());
     d->current.pen = pen;
     d->setStrokePen(pen);
 }
updateRenderHints()
void QCoreGraphicsPaintEngine::updateRenderHints (QPainter::RenderHints hints)
Definition at line 1395 of file qpaintengine_mac.cpp.
Referenced by updateState().
 {
     Q_D(QCoreGraphicsPaintEngine);
     CGContextSetShouldAntialias(d->hd, hints & QPainter::Antialiasing);
     static const CGFloat ScaleFactor = qt_mac_get_scalefactor();
     if (ScaleFactor > 1.) {
         CGContextSetInterpolationQuality(d->hd, kCGInterpolationHigh);
     } else {
         CGContextSetInterpolationQuality(d->hd, (hints & QPainter::SmoothPixmapTransform) ?
                                          kCGInterpolationHigh : kCGInterpolationNone);
     }
     bool textAntialiasing = (hints & QPainter::TextAntialiasing) == QPainter::TextAntialiasing;
     if (!textAntialiasing || d->disabledSmoothFonts) {
         d->disabledSmoothFonts = !textAntialiasing;
         CGContextSetShouldSmoothFonts(d->hd, textAntialiasing);
     }
 }
updateState()
void QCoreGraphicsPaintEngine::updateState (const QPaintEngineState & state) virtual
Reimplement this function to update the state of a paint engine.
When implemented, this function is responsible for checking the paint engine's current state and update the properties that are changed. Use the QPaintEngineState::state() function to find out which properties that must be updated, then use the corresponding GetFunction{get function} to retrieve the current values for the given properties.
See also
QPaintEngineState
Implements QPaintEngine.
Definition at line 642 of file qpaintengine_mac.cpp.
 {
     Q_D(QCoreGraphicsPaintEngine);
     QPaintEngine::DirtyFlags flags = state.state();
     if (flags & DirtyTransform)
         updateMatrix(state.transform());
     if (flags & DirtyClipEnabled) {
         if (state.isClipEnabled())
             updateClipPath(painter()->clipPath(), Qt::ReplaceClip);
         else
             updateClipPath(QPainterPath(), Qt::NoClip);
     }
     if (flags & DirtyClipPath) {
         updateClipPath(state.clipPath(), state.clipOperation());
     } else if (flags & DirtyClipRegion) {
         updateClipRegion(state.clipRegion(), state.clipOperation());
     }
     // If the clip has changed we need to update all other states
     // too, since they are included in the system context on OSX,
     // and changing the clip resets that context back to scratch.
     if (flags & (DirtyClipPath | DirtyClipRegion | DirtyClipEnabled))
         flags |= AllDirty;
     if (flags & DirtyPen)
         updatePen(state.pen());
     if (flags & (DirtyBrush|DirtyBrushOrigin))
         updateBrush(state.brush(), state.brushOrigin());
     if (flags & DirtyFont)
         updateFont(state.font());
     if (flags & DirtyOpacity)
         updateOpacity(state.opacity());
     if (flags & DirtyHints)
         updateRenderHints(state.renderHints());
     if (flags & DirtyCompositionMode)
         updateCompositionMode(state.compositionMode());
     if (flags & (DirtyPen | DirtyTransform)) {
         if (!d->current.pen.isCosmetic()) {
             d->cosmeticPen = QCoreGraphicsPaintEnginePrivate::CosmeticNone;
         } else if (d->current.transform.m11() < d->current.transform.m22()-1.0 ||
                   d->current.transform.m11() > d->current.transform.m22()+1.0) {
             d->cosmeticPen = QCoreGraphicsPaintEnginePrivate::CosmeticTransformPath;
             d->cosmeticPenSize = d->adjustPenWidth(d->current.pen.widthF());
             if (!d->cosmeticPenSize)
                 d->cosmeticPenSize = 1.0;
         } else {
             d->cosmeticPen = QCoreGraphicsPaintEnginePrivate::CosmeticSetPenWidth;
             static const float sqrt2 = sqrt(2);
             qreal width = d->current.pen.widthF();
             if (!width)
                 width = 1;
             d->cosmeticPenSize = sqrt(pow(d->pixelSize.y(), 2) + pow(d->pixelSize.x(), 2)) / sqrt2 * width;
         }
     }
 }
updateTransform()
void QCoreGraphicsPaintEngine::updateTransform (const QTransform & matrix)
Friends and Related Functions
QMacPrintEngine
friend class QMacPrintEngine friend
Definition at line 125 of file qpaintengine_mac_p.h.
QMacPrintEnginePrivate
friend class QMacPrintEnginePrivate friend
Definition at line 129 of file qpaintengine_mac_p.h.
qt_color_profile_changed
void qt_color_profile_changed (CFNotificationCenterRef center, void * , CFStringRef , const void * , CFDictionaryRef) friend
Definition at line 1122 of file qapplication_mac.mm.
 {
     QCoreGraphicsPaintEngine::cleanUpMacColorSpaces();
 }
qt_mac_display_change_callbk
void qt_mac_display_change_callbk (CGDirectDisplayID , CGDisplayChangeSummaryFlags flags, void *) friend
Definition at line 352 of file qapplication_mac.mm.
 {
 #if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
     const bool resized = flags & kCGDisplayDesktopShapeChangedFlag;
 #else
     Q_UNUSED(flags);
     const bool resized = true;
 #endif
     if (resized && qApp) {
         if (QDesktopWidget *dw = qApp->desktop()) {
             QResizeEvent *re = new QResizeEvent(dw->size(), dw->size());
             QApplication::postEvent(dw, re);
             QCoreGraphicsPaintEngine::cleanUpMacColorSpaces();
         }
     }
 }
Properties
m_displayColorSpaceHash
QHash< QWidget *, CGColorSpaceRef > QCoreGraphicsPaintEngine::m_displayColorSpaceHash static private
Definition at line 138 of file qpaintengine_mac_p.h.
Referenced by clearColorSpace(), and qt_mac_compose_path().
m_genericColorSpace
CGColorSpaceRef QCoreGraphicsPaintEngine::m_genericColorSpace = 0 static private
Definition at line 137 of file qpaintengine_mac_p.h.
Referenced by qt_mac_compose_path().
m_postRoutineRegistered
bool QCoreGraphicsPaintEngine::m_postRoutineRegistered = false static private
Definition at line 136 of file qpaintengine_mac_p.h.
Referenced by qt_mac_compose_path().
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintengine_mac_p.h
/src/gui/painting/qpaintengine_mac.cpp