Qt 4.8: QWindowsPipeWriter Class Reference
QWindowsPipeWriter Class Reference
#include <qwindowspipewriter_p.h>
Signals
void bytesWritten (qint64 bytes)
void canWrite ()
Signals inherited from QThread
void finished ()
This signal is emitted when the thread has finished executing.
void started ()
This signal is emitted when the thread starts executing.
void terminated ()
This signal is emitted when the thread is terminated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
qint64 bytesToWrite () const
bool hadWritten () const
QWindowsPipeWriter (HANDLE writePipe, QObject *parent=0)
bool waitForWrite (int msecs)
qint64 write (const char *data, qint64 maxlen)
~QWindowsPipeWriter ()
Public Functions inherited from QThread
void exit (int retcode=0)
Tells the thread's event loop to exit with a return code.
bool isFinished () const
Returns true if the thread is finished; otherwise returns false.
bool isRunning () const
Returns true if the thread is running; otherwise returns false.
Priority priority () const
Returns the priority for a running thread.
QThread (QObject *parent=0)
Constructs a new QThread to manage a new thread.
void setPriority (Priority priority)
This function sets the priority for a running thread.
void setStackSize (uint stackSize)
Sets the maximum stack size for the thread to stackSize.
uint stackSize () const
Returns the maximum stack size for the thread (if set with setStackSize()); otherwise returns zero.
bool wait (unsigned long time=ULONG_MAX)
Blocks the thread until either of these conditions is met:
~QThread ()
Destroys the QThread.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void run ()
The starting point for the thread.
Protected Functions inherited from QThread
int exec ()
Enters the event loop and waits until exit() is called, returning the value that was passed to exit().
QThread (QThreadPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
QByteArray data
bool hasWritten
QMutex lock
volatile bool quitNow
QWaitCondition waitCondition
HANDLE writePipe
Additional Inherited Members
Public Types inherited from QThread
enum Priority {
IdlePriority, LowestPriority, LowPriority, NormalPriority,
HighPriority, HighestPriority, TimeCriticalPriority, InheritPriority
}
This enum type indicates how the operating system should schedule newly created threads.
Public Slots inherited from QThread
void quit ()
Tells the thread's event loop to exit with return code 0 (success).
void start (Priority=InheritPriority)
Begins execution of the thread by calling run().
void terminate ()
Terminates the execution of the thread.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QThread
static QThread * currentThread ()
Returns a pointer to a QThread which manages the currently executing thread.
static Qt::HANDLE currentThreadId ()
Returns the thread handle of the currently executing thread.
static int idealThreadCount ()
Returns the ideal number of threads that can be run on the system.
static void yieldCurrentThread ()
Yields execution of the current thread to another runnable thread, if any.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Static Protected Functions inherited from QThread
static void msleep (unsigned long)
Forces the current thread to sleep for msecs milliseconds.
static void setTerminationEnabled (bool enabled=true)
Enables or disables termination of the current thread based on the enabled parameter.
static void sleep (unsigned long)
Forces the current thread to sleep for secs seconds.
static void usleep (unsigned long)
Forces the current thread to sleep for usecs microseconds.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 118 of file qwindowspipewriter_p.h.
Constructors and Destructors
QWindowsPipeWriter()
QWindowsPipeWriter::QWindowsPipeWriter (HANDLE writePipe, QObject * parent = 0)
Definition at line 49 of file qwindowspipewriter.cpp.
     : QThread(parent),
       writePipe(INVALID_HANDLE_VALUE),
       quitNow(false),
       hasWritten(false)
 {
 #if !defined(Q_OS_WINCE) || (_WIN32_WCE >= 0x600)
     DuplicateHandle(GetCurrentProcess(), pipe, GetCurrentProcess(),
                          &writePipe, 0, FALSE, DUPLICATE_SAME_ACCESS);
 #else
     Q_UNUSED(pipe);
     writePipe = GetCurrentProcess();
 #endif
 }
~QWindowsPipeWriter()
QWindowsPipeWriter::~QWindowsPipeWriter ()
Definition at line 64 of file qwindowspipewriter.cpp.
 {
     lock.lock();
     quitNow = true;
     waitCondition.wakeOne();
     lock.unlock();
     if (!wait(30000))
         terminate();
 #if !defined(Q_OS_WINCE) || (_WIN32_WCE >= 0x600)
     CloseHandle(writePipe);
 #endif
 }
Functions
bytesToWrite()
qint64 QWindowsPipeWriter::bytesToWrite () const inline
Definition at line 133 of file qwindowspipewriter_p.h.
Referenced by QProcessPrivate::flushPipeWriter(), QProcessPrivate::pipeWriterBytesToWrite(), and qt_terminateApp().
     {
         QMutexLocker locker(&lock);
         return data.size();
     }
bytesWritten
void QWindowsPipeWriter::bytesWritten (qint64 bytes) signal
Referenced by run().
canWrite
void QWindowsPipeWriter::canWrite () signal
Referenced by run().
hadWritten()
bool QWindowsPipeWriter::hadWritten () const inline
Definition at line 139 of file qwindowspipewriter_p.h.
Referenced by qt_terminateApp(), and waitForWrite().
     {
         return hasWritten;
     }
run()
void QWindowsPipeWriter::run (void) protected virtual
The starting point for the thread.
After calling start(), the newly created thread calls this function. The default implementation simply calls exec().
You can reimplement this function to facilitate advanced thread management. Returning from this method will end the execution of the thread.
See also
start() wait()
Reimplemented from QThread.
Definition at line 102 of file qwindowspipewriter.cpp.
 {
     OVERLAPPED overl;
     memset(&overl, 0, sizeof overl);
     overl.hEvent = CreateEvent(NULL, TRUE, FALSE, NULL);
     forever {
         lock.lock();
         while(data.isEmpty() && (!quitNow)) {
             waitCondition.wakeOne();
             waitCondition.wait(&lock);
         }
         if (quitNow) {
             lock.unlock();
             quitNow = false;
         break;
         }
         QByteArray copy = data;
         lock.unlock();
         const char *ptrData = copy.data();
         qint64 maxlen = copy.size();
         qint64 totalWritten = 0;
         overl.Offset = 0;
         overl.OffsetHigh = 0;
         while ((!quitNow) && totalWritten < maxlen) {
             DWORD written = 0;
             if (!WriteFile(writePipe, ptrData + totalWritten,
                            maxlen - totalWritten, &written, &overl)) {
                 if (GetLastError() == 0xE8/*NT_STATUS_INVALID_USER_BUFFER*/) {
                     // give the os a rest
                     msleep(100);
                     continue;
                 }
 #ifndef Q_OS_WINCE
                 if (GetLastError() == ERROR_IO_PENDING) {
                   if (!GetOverlappedResult(writePipe, &overl, &written, TRUE)) {
                       CloseHandle(overl.hEvent);
                       return;
                   }
                 } else {
                     CloseHandle(overl.hEvent);
                     return;
                 }
 #else
                 return;
 #endif
             }
             totalWritten += written;
 #if defined QPIPEWRITER_DEBUG
             qDebug("QWindowsPipeWriter::run() wrote %d %d/%d bytes",
                 written, int(totalWritten), int(maxlen));
 #endif
             lock.lock();
             data.remove(0, written);
             hasWritten = true;
             lock.unlock();
         }
         emit bytesWritten(totalWritten);
         emit canWrite();
     }
     CloseHandle(overl.hEvent);
 }
waitForWrite()
bool QWindowsPipeWriter::waitForWrite (int msecs)
Definition at line 77 of file qwindowspipewriter.cpp.
Referenced by QProcessPrivate::flushPipeWriter(), QProcessPrivate::pipeWriterBytesToWrite(), and qt_terminateApp().
 {
     QMutexLocker locker(&lock);
     bool hadWritten = hasWritten;
     hasWritten = false;
     if (hadWritten)
         return true;
     if (!waitCondition.wait(&lock, msecs))
         return false;
     hadWritten = hasWritten;
     hasWritten = false;
     return hadWritten;
 }
write()
qint64 QWindowsPipeWriter::write (const char * data, qint64 maxlen)
Definition at line 91 of file qwindowspipewriter.cpp.
Referenced by QProcessPrivate::pipeWriterBytesToWrite().
 {
     if (!isRunning())
         return -1;
     QMutexLocker locker(&lock);
     data.append(QByteArray(ptr, maxlen));
     waitCondition.wakeOne();
     return maxlen;
 }
Properties
data
QByteArray QWindowsPipeWriter::data private
Definition at line 148 of file qwindowspipewriter_p.h.
Referenced by run(), and write().
hasWritten
bool QWindowsPipeWriter::hasWritten private
Definition at line 153 of file qwindowspipewriter_p.h.
Referenced by run(), and waitForWrite().
lock
QMutex QWindowsPipeWriter::lock mutable private
Definition at line 150 of file qwindowspipewriter_p.h.
Referenced by run(), waitForWrite(), write(), and ~QWindowsPipeWriter().
quitNow
volatile bool QWindowsPipeWriter::quitNow private
Definition at line 152 of file qwindowspipewriter_p.h.
Referenced by run(), and ~QWindowsPipeWriter().
waitCondition
QWaitCondition QWindowsPipeWriter::waitCondition private
Definition at line 149 of file qwindowspipewriter_p.h.
Referenced by run(), waitForWrite(), write(), and ~QWindowsPipeWriter().
writePipe
HANDLE QWindowsPipeWriter::writePipe private
Definition at line 151 of file qwindowspipewriter_p.h.
Referenced by QWindowsPipeWriter(), run(), and ~QWindowsPipeWriter().
The documentation for this class was generated from the following files:
/src/corelib/io/qwindowspipewriter_p.h
/src/corelib/io/qwindowspipewriter.cpp