Qt 4.8: QRfbDualColorHextile< SRC > Class Template Reference
QRfbDualColorHextile< SRC > Class Template Reference
#include <qscreenvnc_p.h>
Classes
struct Rect
Public Functions
QRfbDualColorHextile (QRfbHextileEncoder< SRC > *e)
QRfbDualColorHextile (QRfbHextileEncoder< SRC > *e)
bool read (const uchar *data, int width, int height, int stride)
bool read (const uchar *data, int width, int height, int stride)
void write (QTcpSocket *socket) const
void write (QTcpSocket *socket) const
Private Functions
int height (int r) const
int height (int r) const
int lastx () const
int lastx () const
int lasty () const
int lasty () const
void next ()
void next ()
int rectx (int r) const
int rectx (int r) const
int recty (int r) const
int recty (int r) const
void setHeight (int r, int height)
void setHeight (int height)
void setHeight (int r, int height)
void setHeight (int height)
void setWidth (int r, int width)
void setWidth (int r, int width)
void setWidth (int width)
void setWidth (int width)
void setX (int r, int x)
void setX (int r, int x)
void setX (int x)
void setX (int x)
void setY (int r, int y)
void setY (int r, int y)
void setY (int y)
void setY (int y)
int width (int r) const
int width (int r) const
Properties
QRfbHextileEncoder< SRC > * encoder
quint8 numRects
struct QRfbDualColorHextile::Rect rects [8 *16]
Detailed Description
template<class SRC>
class QRfbDualColorHextile< SRC >
Definition at line 304 of file qscreenvnc_p.h.
Constructors and Destructors
QRfbDualColorHextile() [1/2]
template<class SRC> QRfbDualColorHextile< SRC >::QRfbDualColorHextile (QRfbHextileEncoder< SRC > * e) inline
Definition at line 307 of file qscreenvnc_p.h.
 : encoder(e) {}
QRfbDualColorHextile() [2/2]
template<class SRC> QRfbDualColorHextile< SRC >::QRfbDualColorHextile (QRfbHextileEncoder< SRC > * e) inline
Definition at line 313 of file qvncserver.h.
 : encoder(e) {}
Functions
height() [1/2]
template<class SRC> int QRfbDualColorHextile< SRC >::height (int r) const inline private
Definition at line 326 of file qscreenvnc_p.h.
 { return (rects[r].wh & 0x0f) + 1; }
height() [2/2]
template<class SRC> int QRfbDualColorHextile< SRC >::height (int r) const inline private
Definition at line 332 of file qvncserver.h.
 { return (rects[r].wh & 0x0f) + 1; }
lastx() [1/2]
template<class SRC> int QRfbDualColorHextile< SRC >::lastx () const inline private
Definition at line 321 of file qscreenvnc_p.h.
 { return rectx(numRects); }
lastx() [2/2]
template<class SRC> int QRfbDualColorHextile< SRC >::lastx () const inline private
Definition at line 327 of file qvncserver.h.
 { return rectx(numRects); }
lasty() [1/2]
template<class SRC> int QRfbDualColorHextile< SRC >::lasty () const inline private
Definition at line 322 of file qscreenvnc_p.h.
 { return recty(numRects); }
lasty() [2/2]
template<class SRC> int QRfbDualColorHextile< SRC >::lasty () const inline private
Definition at line 328 of file qvncserver.h.
 { return recty(numRects); }
next() [1/2]
template<class SRC > void QRfbDualColorHextile< SRC >::next () private
Definition at line 1277 of file qscreenvnc_qws.cpp.
Referenced by buttonChange().
 {
     for (int r = numRects - 1; r >= 0; --r) {
         if (recty(r) == lasty())
             continue;
         if (recty(r) < lasty() - 1) // only search previous scanline
             break;
         if (rectx(r) == lastx() && width(r) == width(numRects)) {
             ++rects[r].wh;
             return;
         }
     }
     ++numRects;
 }
next() [2/2]
template<class SRC> void QRfbDualColorHextile< SRC >::next () private
read() [1/2]
template<class SRC > bool QRfbDualColorHextile< SRC >::read (const uchar * data, int width, int height, int stride)
Definition at line 1150 of file qscreenvnc_qws.cpp.
Referenced by buttonChange().
 {
     const SRC *ptr = reinterpret_cast<const SRC*>(data);
     const int linestep = (stride / sizeof(SRC)) - width;
     SRC c1;
     SRC c2 = 0;
     int n1 = 0;
     int n2 = 0;
     int x = 0;
     int y = 0;
     c1 = *ptr;
     // find second color
     while (y < height) {
         while (x < width) {
             if (*ptr == c1) {
                 ++n1;
             } else {
                 c2 = *ptr;
                 goto found_second_color;
             }
             ++ptr;
             ++x;
         }
         x = 0;
         ptr += linestep;
         ++y;
     }
 found_second_color:
     // finish counting
     while (y < height) {
         while (x < width) {
             if (*ptr == c1) {
                 ++n1;
             } else if (*ptr == c2) {
                 ++n2;
             } else {
                 return false;
             }
             ++ptr;
             ++x;
         }
         x = 0;
         ptr += linestep;
         ++y;
     }
     if (n2 > n1) {
         const quint32 tmpC = c1;
         c1 = c2;
         c2 = tmpC;
     }
     encoder->newBg |= (c1 != encoder->bg);
     encoder->newFg |= (c2 != encoder->fg);
     encoder->bg = c1;
     encoder->fg = c2;
     // create map
     bool inRect = false;
     numRects = 0;
     ptr = reinterpret_cast<const SRC*>(data);
     for (y = 0; y < height; ++y) {
         for (x = 0; x < width; ++x) {
             if (inRect && *ptr == encoder->bg) {
                 // rect finished
                 setWidth(x - lastx());
                 next();
                 inRect = false;
             } else if (!inRect && *ptr == encoder->fg) {
                 // rect start
                 setX(x);
                 setY(y);
                 setHeight(1);
                 inRect = true;
             }
             ++ptr;
         }
         if (inRect) {
             // finish rect
             setWidth(width - lastx());
             next();
             inRect = false;
         }
         ptr += linestep;
     }
     return true;
 }
read() [2/2]
template<class SRC> bool QRfbDualColorHextile< SRC >::read (const uchar * data, int width, int height, int stride)
rectx() [1/2]
template<class SRC> int QRfbDualColorHextile< SRC >::rectx (int r) const inline private
Definition at line 323 of file qscreenvnc_p.h.
 { return rects[r].xy >> 4; }
rectx() [2/2]
template<class SRC> int QRfbDualColorHextile< SRC >::rectx (int r) const inline private
Definition at line 329 of file qvncserver.h.
 { return rects[r].xy >> 4; }
recty() [1/2]
template<class SRC> int QRfbDualColorHextile< SRC >::recty (int r) const inline private
Definition at line 324 of file qscreenvnc_p.h.
 { return rects[r].xy & 0x0f; }
recty() [2/2]
template<class SRC> int QRfbDualColorHextile< SRC >::recty (int r) const inline private
Definition at line 330 of file qvncserver.h.
 { return rects[r].xy & 0x0f; }
setHeight() [1/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setHeight (int r, int height) inline private
Definition at line 337 of file qscreenvnc_p.h.
{
         rects[r].wh = (rects[r].wh & 0xf0) | (height - 1);
     }
setHeight() [2/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setHeight (int height) inline private
Definition at line 342 of file qscreenvnc_p.h.
Referenced by QRfbDualColorHextile< SRC >::setHeight().
 { setHeight(numRects, height); }
setHeight() [3/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setHeight (int r, int height) inline private
Definition at line 343 of file qvncserver.h.
{
         rects[r].wh = (rects[r].wh & 0xf0) | (height - 1);
     }
setHeight() [4/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setHeight (int height) inline private
Definition at line 348 of file qvncserver.h.
Referenced by QRfbDualColorHextile< SRC >::setHeight().
 { setHeight(numRects, height); }
setWidth() [1/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setWidth (int r, int width) inline private
Definition at line 334 of file qscreenvnc_p.h.
{
         rects[r].wh = ((width - 1) << 4) | (rects[r].wh & 0x0f);
     }
setWidth() [2/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setWidth (int r, int width) inline private
Definition at line 340 of file qvncserver.h.
{
         rects[r].wh = ((width - 1) << 4) | (rects[r].wh & 0x0f);
     }
setWidth() [3/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setWidth (int width) inline private
Definition at line 341 of file qscreenvnc_p.h.
Referenced by QRfbDualColorHextile< SRC >::setWidth().
 { setWidth(numRects, width); }
setWidth() [4/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setWidth (int width) inline private
Definition at line 347 of file qvncserver.h.
Referenced by QRfbDualColorHextile< SRC >::setWidth().
 { setWidth(numRects, width); }
setX() [1/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setX (int r, int x) inline private
Definition at line 328 of file qscreenvnc_p.h.
{
         rects[r].xy = (x << 4) | (rects[r].xy & 0x0f);
     }
setX() [2/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setX (int r, int x) inline private
Definition at line 334 of file qvncserver.h.
{
         rects[r].xy = (x << 4) | (rects[r].xy & 0x0f);
     }
setX() [3/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setX (int x) inline private
Definition at line 343 of file qscreenvnc_p.h.
Referenced by QRfbDualColorHextile< SRC >::setX().
 { setX(numRects, x); }
setX() [4/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setX (int x) inline private
Definition at line 349 of file qvncserver.h.
Referenced by QRfbDualColorHextile< SRC >::setX().
 { setX(numRects, x); }
setY() [1/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setY (int r, int y) inline private
Definition at line 331 of file qscreenvnc_p.h.
{
         rects[r].xy = (rects[r].xy & 0xf0) | y;
     }
setY() [2/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setY (int r, int y) inline private
Definition at line 337 of file qvncserver.h.
{
         rects[r].xy = (rects[r].xy & 0xf0) | y;
     }
setY() [3/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setY (int y) inline private
Definition at line 344 of file qscreenvnc_p.h.
Referenced by QRfbDualColorHextile< SRC >::setY().
 { setY(numRects, y); }
setY() [4/4]
template<class SRC> void QRfbDualColorHextile< SRC >::setY (int y) inline private
Definition at line 350 of file qvncserver.h.
Referenced by QRfbDualColorHextile< SRC >::setY().
 { setY(numRects, y); }
width() [1/2]
template<class SRC> int QRfbDualColorHextile< SRC >::width (int r) const inline private
Definition at line 325 of file qscreenvnc_p.h.
 { return (rects[r].wh >> 4) + 1; }
width() [2/2]
template<class SRC> int QRfbDualColorHextile< SRC >::width (int r) const inline private
Definition at line 331 of file qvncserver.h.
 { return (rects[r].wh >> 4) + 1; }
write() [1/2]
template<class SRC > void QRfbDualColorHextile< SRC >::write (QTcpSocket * socket) const
Definition at line 1246 of file qscreenvnc_qws.cpp.
Referenced by buttonChange().
 {
     const int bpp = encoder->server->clientBytesPerPixel();
     const int padding = 3;
     QVarLengthArray<char> buffer(padding + 2 * bpp + sizeof(char) + sizeof(numRects));
     char &subenc = buffer[padding];
     int n = padding + sizeof(subenc);
     subenc = 0x8; // AnySubrects
     if (encoder->newBg) {
         subenc |= 0x2; // Background
         encoder->server->convertPixels(buffer.data() + n, (char*)&encoder->bg, 1);
         n += bpp;
 //        encoder->newBg = false;
     }
     if (encoder->newFg) {
         subenc |= 0x4; // Foreground
         encoder->server->convertPixels(buffer.data() + n, (char*)&encoder->fg, 1);
         n += bpp;
 //        encoder->newFg = false;
     }
     buffer[n] = numRects;
     n += sizeof(numRects);
     socket->write(buffer.data() + padding, n - padding);
     socket->write((char*)rects, numRects * sizeof(Rect));
 }
write() [2/2]
template<class SRC> void QRfbDualColorHextile< SRC >::write (QTcpSocket * socket) const
Properties
encoder
template<class SRC> QRfbHextileEncoder< SRC > * QRfbDualColorHextile< SRC >::encoder private
Definition at line 318 of file qscreenvnc_p.h.
numRects
template<class SRC> quint8 QRfbDualColorHextile< SRC >::numRects private
Definition at line 317 of file qscreenvnc_p.h.
rects
template<class SRC> struct QRfbDualColorHextile::Rect QRfbDualColorHextile< SRC >::rects private
The documentation for this class was generated from the following files:
/src/plugins/gfxdrivers/vnc/qscreenvnc_p.h
/src/plugins/platforms/vnc/qvncserver.h
/src/plugins/gfxdrivers/vnc/qscreenvnc_qws.cpp
/src/plugins/platforms/vnc/qvncserver.cpp