Qt 4.8: qargb8565 Class Reference
qargb8565 Class Reference
#include <qdrawhelper_p.h>
Public Functions
quint8 alpha () const
Q_STATIC_INLINE_FUNCTION quint8 alpha (quint8 a)
qargb8565 byte_mul (quint8 a) const
Q_STATIC_INLINE_FUNCTION bool hasAlpha ()
Q_STATIC_INLINE_FUNCTION quint8 ialpha (quint8 a)
operator quint16 () const
operator quint32 () const
qargb8565 operator+ (qargb8565 v) const
bool operator== (const qargb8565 &v) const
qargb8565 ()
qargb8565 (quint32 v)
qargb8565 (quint32p v)
qargb8565 (const qargb8565 &v)
qargb8565 (const qrgb565 &v)
quint32 rawValue () const
quint16 rawValue16 () const
qargb8565 truncedAlpha ()
Properties
quint8 data [3]
Friends
class qrgb565
Detailed Description
Definition at line 749 of file qdrawhelper_p.h.
Constructors and Destructors
qargb8565() [1/5]
qargb8565::qargb8565 () inline
Definition at line 754 of file qdrawhelper_p.h.
Referenced by qargb8565().
 {}
qargb8565() [2/5]
qargb8565::qargb8565 (quint32 v) inline
Definition at line 817 of file qdrawhelper_p.h.
 {
     *this = qargb8565(quint32p(v));
 }
qargb8565() [3/5]
qargb8565::qargb8565 (quint32p v) inline explicit
Definition at line 822 of file qdrawhelper_p.h.
 {
     data[0] = qAlpha(v);
     const int r = qRed(v);
     const int g = qGreen(v);
     const int b = qBlue(v);
     data[1] = ((g << 3) & 0xe0) | (b >> 3);
     data[2] = (r & 0xf8) | (g >> 5);
 }
qargb8565() [4/5]
qargb8565::qargb8565 (const qargb8565 & v) inline
Definition at line 832 of file qdrawhelper_p.h.
 {
     data[0] = v.data[0];
     data[1] = v.data[1];
     data[2] = v.data[2];
 }
qargb8565() [5/5]
qargb8565::qargb8565 (const qrgb565 & v) inline
Definition at line 839 of file qdrawhelper_p.h.
 {
     data[0] = 0xff;
     data[1] = v.data & 0xff;
     data[2] = v.data >> 8;
 }
Functions
alpha() [1/2]
quint8 qargb8565::alpha () const inline
Definition at line 763 of file qdrawhelper_p.h.
Referenced by Blend_ARGB24_on_RGB16_SourceAlpha::write(), and Blend_ARGB24_on_RGB16_SourceAndConstAlpha::write().
 { return data[0]; }
alpha() [2/2]
Q_STATIC_INLINE_FUNCTION quint8 qargb8565::alpha (quint8 a) inline
Definition at line 769 of file qdrawhelper_p.h.
 { return (a + 1) >> 3; }
byte_mul()
qargb8565 qargb8565::byte_mul (quint8 a) const inline
Definition at line 875 of file qdrawhelper_p.h.
Referenced by Blend_ARGB24_on_RGB16_SourceAndConstAlpha::write().
 {
     qargb8565 result;
     result.data[0] = (data[0] * a) >> 5;
     const quint16 x = (data[2] << 8) | data[1];
     const quint16 t = ((((x & 0x07e0) >> 5) * a) & 0x07e0) |
                       ((((x & 0xf81f) * a) >> 5) & 0xf81f);
     result.data[1] = t & 0xff;
     result.data[2] = t >> 8;
     return result;
 }
hasAlpha()
Q_STATIC_INLINE_FUNCTION bool qargb8565::hasAlpha () inline
Definition at line 752 of file qdrawhelper_p.h.
 { return true; }
ialpha()
Q_STATIC_INLINE_FUNCTION quint8 qargb8565::ialpha (quint8 a) inline
Definition at line 770 of file qdrawhelper_p.h.
 { return 0x20 - alpha(a); }
operator quint16()
qargb8565::operator quint16 () const inline
Definition at line 859 of file qdrawhelper_p.h.
 {
     return (data[2] << 8) | data[1];
 }
operator quint32()
qargb8565::operator quint32 () const inline
Definition at line 846 of file qdrawhelper_p.h.
 {
     const quint16 rgb = (data[2] << 8) | data[1];
     const int a = data[0];
     const int r = (rgb & 0xf800);
     const int g = (rgb & 0x07e0);
     const int b = (rgb & 0x001f);
     const int tr = qMin(a, (r >> 8) | (r >> 13));
     const int tg = qMin(a, (g >> 3) | (g >> 9));
     const int tb = qMin(a, (b << 3) | (b >> 2));
     return qRgba(tr, tg, tb, data[0]);
 }
operator+()
qargb8565 qargb8565::operator+ (qargb8565 v) const inline
Definition at line 864 of file qdrawhelper_p.h.
 {
     qargb8565 t;
     t.data[0] = data[0] + v.data[0];
     const quint16 rgb =  ((data[2] + v.data[2]) << 8)
                          + (data[1] + v.data[1]);
     t.data[1] = rgb & 0xff;
     t.data[2] = rgb >> 8;
     return t;
 }
operator==()
bool qargb8565::operator== (const qargb8565 & v) const inline
Definition at line 888 of file qdrawhelper_p.h.
 {
     return data[0] == v.data[0]
         && data[1] == v.data[1]
         && data[2] == v.data[2];
 }
rawValue()
quint32 qargb8565::rawValue () const inline
Definition at line 895 of file qdrawhelper_p.h.
 {
     return (data[2] << 16) | (data[1] << 8) | data[0];
 }
rawValue16()
quint16 qargb8565::rawValue16 () const inline
Definition at line 900 of file qdrawhelper_p.h.
Referenced by Blend_ARGB24_on_RGB16_SourceAlpha::write(), and Blend_ARGB24_on_RGB16_SourceAndConstAlpha::write().
 {
     return (data[2] << 8) | data[1];
 }
truncedAlpha()
qargb8565 qargb8565::truncedAlpha () inline
Definition at line 764 of file qdrawhelper_p.h.
{
         data[0] &= 0xf8;
         data[1] &= 0xdf;
         return *this;
     }
Friends and Related Functions
qrgb565
friend class qrgb565 friend
Definition at line 780 of file qdrawhelper_p.h.
Referenced by qrgb565::qrgb565().
Properties
data
quint8 qargb8565::data[3] private
Definition at line 782 of file qdrawhelper_p.h.
Referenced by byte_mul(), operator+(), operator==(), qargb8565(), and qrgb565::qrgb565().
The documentation for this class was generated from the following file:
/src/gui/painting/qdrawhelper_p.h