Qt 4.8: QFontMetrics Class Reference
QFontMetrics Class Reference
The QFontMetrics class provides font metrics information.
#include <qfontmetrics.h>
Public Functions
int ascent () const
Returns the ascent of the font.
int averageCharWidth () const
Returns the average width of glyphs in the font.
QRect boundingRect (QChar) const
Returns the rectangle that is covered by ink if character ch were to be drawn at the origin of the coordinate system.
QRect boundingRect (const QString &text) const
Returns the bounding rectangle of the characters in the string specified by text.
QRect boundingRect (const QRect &r, int flags, const QString &text, int tabstops=0, int *tabarray=0) const
Returns the bounding rectangle of the characters in the string specified by text, which is the set of pixels the text would cover if drawn at (0, 0).
QRect boundingRect (int x, int y, int w, int h, int flags, const QString &text, int tabstops=0, int *tabarray=0) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the bounding rectangle for the given text within the rectangle specified by the x and y coordinates, width, and height.
int charWidth (const QString &str, int pos) const
Returns the width of the character at position pos in the string text.
int descent () const
Returns the descent of the font.
QString elidedText (const QString &text, Qt::TextElideMode mode, int width, int flags=0) const
If the string text is wider than width, returns an elided version of the string (i.
int height () const
Returns the height of the font.
bool inFont (QChar) const
Returns true if character ch is a valid character in the font; otherwise returns false.
bool inFontUcs4 (uint ucs4) const
Returns true if the given character encoded in UCS-4/UTF-32 is a valid character in the font; otherwise returns false.
int leading () const
Returns the leading of the font.
int leftBearing (QChar) const
Returns the left bearing of character ch in the font.
int lineSpacing () const
Returns the distance from one base line to the next.
int lineWidth () const
Returns the width of the underline and strikeout lines, adjusted for the point size of the font.
int maxWidth () const
Returns the width of the widest character in the font.
int minLeftBearing () const
Returns the minimum left bearing of the font.
int minRightBearing () const
Returns the minimum right bearing of the font.
bool operator!= (const QFontMetrics &other)
Returns true if other is not equal to this object; otherwise returns false.
bool operator!= (const QFontMetrics &other) const
Returns true if other is not equal to this object; otherwise returns false.
QFontMetrics & operator= (const QFontMetrics &)
Assigns the font metrics fm.
bool operator== (const QFontMetrics &other)
Returns true if other is equal to this object; otherwise returns false.
bool operator== (const QFontMetrics &other) const
Returns true if other is equal to this object; otherwise returns false.
int overlinePos () const
Returns the distance from the base line to where an overline should be drawn.
QFontMetrics (const QFont &)
Constructs a font metrics object for font.
QFontMetrics (const QFont &, QPaintDevice *pd)
Constructs a font metrics object for font and paintdevice.
QFontMetrics (const QFontMetrics &)
Constructs a copy of fm.
int rightBearing (QChar) const
Returns the right bearing of character ch in the font.
QSize size (int flags, const QString &str, int tabstops=0, int *tabarray=0) const
Returns the size in pixels of text.
int strikeOutPos () const
Returns the distance from the base line to where the strikeout line should be drawn.
QRect tightBoundingRect (const QString &text) const
Returns a tight bounding rectangle around the characters in the string specified by text.
int underlinePos () const
Returns the distance from the base line to where an underscore should be drawn.
int width (const QString &, int len=-1) const
Returns the width in pixels of the first len characters of text.
int width (const QString &, int len, int flags) const
int width (QChar) const
Returns the logical width of character ch in pixels.
int xHeight () const
Returns the 'x' height of the font.
~QFontMetrics ()
Destroys the font metrics object and frees all allocated resources.
Properties
QExplicitlySharedDataPointer< QFontPrivate > d
Friends
class QFontMetricsF
class QFontPrivate
class QStackTextEngine
Detailed Description
The QFontMetrics class provides font metrics information.
Note
This class or function is reentrant.
QFontMetrics functions calculate the size of characters and strings for a given font. There are three ways you can create a QFontMetrics object:
Calling the QFontMetrics constructor with a QFont creates a font metrics object for a screen-compatible font, i.e. the font cannot be a printer font. If the font is changed later, the font metrics object is not updated.
(Note: If you use a printer font the values returned may be inaccurate. Printer fonts are not always accessible so the nearest screen font is used if a printer font is supplied.)
QWidget::fontMetrics() returns the font metrics for a widget's font. This is equivalent to QFontMetrics(widget->font()). If the widget's font is changed later, the font metrics object is not updated.
QPainter::fontMetrics() returns the font metrics for a painter's current font. If the painter's font is changed later, the font metrics object is not updated.
Once created, the object provides functions to access the individual metrics of the font, its characters, and for strings rendered in the font.
There are several functions that operate on the font: ascent(), descent(), height(), leading() and lineSpacing() return the basic size properties of the font. The underlinePos(), overlinePos(), strikeOutPos() and lineWidth() functions, return the properties of the line that underlines, overlines or strikes out the characters. These functions are all fast.
There are also some functions that operate on the set of glyphs in the font: minLeftBearing(), minRightBearing() and maxWidth(). These are by necessity slow, and we recommend avoiding them if possible.
For each character, you can get its width(), leftBearing() and rightBearing() and find out whether it is in the font using inFont(). You can also treat the character as a string, and use the string functions on it.
The string functions include width(), to return the width of a string in pixels (or points, for a printer), boundingRect(), to return a rectangle large enough to contain the rendered string, and size(), to return the size of that rectangle.
Example:
QFont font("times", 24);
QFontMetrics fm(font);
int pixelsWide = fm.width("What's the width of this text?");
int pixelsHigh = fm.height();
See also
QFont, QFontInfo, QFontDatabase, QFontComboBox, {Character Map Example}
Definition at line 65 of file qfontmetrics.h.
Constructors and Destructors
QFontMetrics() [1/3]
QFontMetrics::QFontMetrics (const QFont & font)
Constructs a font metrics object for font.
The font metrics will be compatible with the paintdevice used to create font.
The font metrics object holds the information for the font that is passed in the constructor at the time it is created, and is not updated if the font's attributes are changed later.
Use QFontMetrics(const QFont &, QPaintDevice *) to get the font metrics that are compatible with a certain paint device.
Definition at line 167 of file qfontmetrics.cpp.
     : d(font.d.data())
 {
 }
QFontMetrics() [2/3]
QFontMetrics::QFontMetrics (const QFont & font, QPaintDevice * paintdevice)
Constructs a font metrics object for font and paintdevice.
The font metrics will be compatible with the paintdevice passed. If the paintdevice is 0, the metrics will be screen-compatible, ie. the metrics you get if you use the font for drawing text on a widgets or pixmaps, not on a QPicture or QPrinter.
The font metrics object holds the information for the font that is passed in the constructor at the time it is created, and is not updated if the font's attributes are changed later.
Definition at line 185 of file qfontmetrics.cpp.
 {
     int dpi = paintdevice ? paintdevice->logicalDpiY() : qt_defaultDpi();
 #ifdef Q_WS_X11
     const QX11Info *info = qt_x11Info(paintdevice);
     int screen = info ? info->screen() : 0;
 #else
     const int screen = 0;
 #endif
     if (font.d->dpi != dpi || font.d->screen != screen ) {
         d = new QFontPrivate(*font.d);
         d->dpi = dpi;
         d->screen = screen;
     } else {
         d = font.d.data();
     }
 }
QFontMetrics() [3/3]
QFontMetrics::QFontMetrics (const QFontMetrics & fm)
Constructs a copy of fm.
Definition at line 207 of file qfontmetrics.cpp.
     : d(fm.d.data())
 {
 }
~QFontMetrics()
QFontMetrics::~QFontMetrics ()
Destroys the font metrics object and frees all allocated resources.
Definition at line 216 of file qfontmetrics.cpp.
 {
 }
Functions
ascent()
int QFontMetrics::ascent () const
Returns the ascent of the font.
The ascent of a font is the distance from the baseline to the highest position characters extend to. In practice, some font designers break this rule, e.g. when they put more than one accent on top of a character, or to accommodate an unusual character in an exotic language, so it is possible (though rare) that this value will be too small.
See also
descent()
Definition at line 305 of file qfontmetrics.cpp.
Referenced by QDragManager::drag(), QDeclarativeTextInput::drawContents(), QGtkStyle::drawControl(), QMacStyle::drawControl(), QPicture::exec(), overlinePos(), QLineEdit::paintEvent(), QPainterReplayer::process(), QTipLabel::reuseTip(), strikeOutPos(), QDeclarativeTextPrivate::updateSize(), and QDeclarativeTextEdit::updateSize().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->ascent());
 }
averageCharWidth()
int QFontMetrics::averageCharWidth () const
Returns the average width of glyphs in the font.
Since
4.2
Definition at line 438 of file qfontmetrics.cpp.
Referenced by QAccessibleTextWidget::characterRect(), and QLabelPrivate::sizeForWidth().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->averageCharWidth());
 }
boundingRect() [1/4]
QRect QFontMetrics::boundingRect (QChar ch) const
Returns the rectangle that is covered by ink if character ch were to be drawn at the origin of the coordinate system.
Note that the bounding rectangle may extend to the left of (0, 0) (e.g., for italicized fonts), and that the text output may cover all pixels in the bounding rectangle. For a space character the rectangle will usually be empty.
Note that the rectangle usually extends both above and below the base line.
Warning
The width of the returned rectangle is not the advance width of the character. Use boundingRect(const QString &) or width() instead.
See also
width()
Definition at line 753 of file qfontmetrics.cpp.
Referenced by QVistaHelper::drawTitleBar(), QStyle::itemTextRect(), QCalendarWidget::minimumSizeHint(), QMacStylePrivate::pushButtonSizeFromContents(), QWhatsThat::QWhatsThat(), QComboBoxPrivate::recomputeSizeHint(), size(), QLabelPrivate::sizeForWidth(), QCleanlooksStyle::subControlRect(), QGtkStyle::subControlRect(), and QMenuPrivate::updateActionRects().
 {
     const int script = QUnicodeTables::script(ch);
     QFontEngine *engine;
     if (d->capital == QFont::SmallCaps && ch.isLower())
         engine = d->smallCapsFontPrivate()->engineForScript(script);
     else
         engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     d->alterCharForCapitalization(ch);
     QGlyphLayoutArray<10> glyphs;
     int nglyphs = 9;
     engine->stringToCMap(&ch, 1, &glyphs, &nglyphs, 0);
     glyph_metrics_t gm = engine->boundingBox(glyphs.glyphs[0]);
     return QRect(qRound(gm.x), qRound(gm.y), qRound(gm.width), qRound(gm.height));
 }
boundingRect() [2/4]
QRect QFontMetrics::boundingRect (const QString & text) const
Returns the bounding rectangle of the characters in the string specified by text.
The bounding rectangle always covers at least the set of pixels the text would cover if drawn at (0, 0).
Note that the bounding rectangle may extend to the left of (0, 0), e.g. for italicized fonts, and that the width of the returned rectangle might be different than what the width() method returns.
If you want to know the advance width of the string (to layout a set of strings next to each other), use width() instead.
Newline characters are processed as normal characters, not as linebreaks.
The height of the bounding rectangle is at least as large as the value returned by height().
See also
width(), height(), QPainter::boundingRect(), tightBoundingRect()
Definition at line 724 of file qfontmetrics.cpp.
 {
     if (text.length() == 0)
         return QRect();
     QStackTextEngine layout(text, d.data());
     layout.ignoreBidi = true;
     layout.itemize();
     glyph_metrics_t gm = layout.boundingBox(0, text.length());
     return QRect(qRound(gm.x), qRound(gm.y), qRound(gm.width), qRound(gm.height));
 }
boundingRect() [3/4]
QRect QFontMetrics::boundingRect (const QRect & rect, int flags, const QString & text, int tabStops = 0, int * tabArray = 0) const
Returns the bounding rectangle of the characters in the string specified by text, which is the set of pixels the text would cover if drawn at (0, 0).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The drawing, and hence the bounding rectangle, is constrained to the rectangle rect.
The flags argument is the bitwise OR of the following flags:
Qt::AlignLeft aligns to the left border, except for Arabic and Hebrew where it aligns to the right.
Qt::AlignRight aligns to the right border, except for Arabic and Hebrew where it aligns to the left.
Qt::AlignJustify produces justified text.
Qt::AlignHCenter aligns horizontally centered.
Qt::AlignTop aligns to the top border.
Qt::AlignBottom aligns to the bottom border.
Qt::AlignVCenter aligns vertically centered
Qt::AlignCenter (== Qt::AlignHCenter | Qt::AlignVCenter)
Qt::TextSingleLine ignores newline characters in the text.
Qt::TextExpandTabs expands tabs (see below)
Qt::TextShowMnemonic interprets "&x" as x; i.e., underlined.
Qt::TextWordWrap breaks the text to fit the rectangle.
Qt::Horizontal alignment defaults to Qt::AlignLeft and vertical alignment defaults to Qt::AlignTop.
If several of the horizontal or several of the vertical alignment flags are set, the resulting alignment is undefined.
If Qt::TextExpandTabs is set in flags, then: if tabArray is non-null, it specifies a 0-terminated sequence of pixel-positions for tabs; otherwise if tabStops is non-zero, it is used as the tab spacing (in pixels).
Note that the bounding rectangle may extend to the left of (0, 0), e.g. for italicized fonts, and that the text output may cover all pixels in the bounding rectangle.
Newline characters are processed as linebreaks.
Despite the different actual character heights, the heights of the bounding rectangles of "Yes" and "yes" are the same.
The bounding rectangle returned by this function is somewhat larger than that calculated by the simpler boundingRect() function. This function uses the maximum left and right font bearings as is necessary for multi-line text to align correctly. Also, fontHeight() and lineSpacing() are used to calculate the height, rather than individual character heights.
See also
width(), QPainter::boundingRect(), Qt::Alignment
Definition at line 831 of file qfontmetrics.cpp.
 {
     int tabArrayLen = 0;
     if (tabArray)
         while (tabArray[tabArrayLen])
             tabArrayLen++;
     QRectF rb;
     QRectF rr(rect);
     qt_format_text(QFont(d.data()), rr, flags | Qt::TextDontPrint, text, &rb, tabStops, tabArray,
                    tabArrayLen, 0);
     return rb.toAlignedRect();
 }
boundingRect() [4/4]
QRect QFontMetrics::boundingRect (int x, int y, int width, int height, int flags, const QString & text, int tabStops = 0, int * tabArray = 0) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the bounding rectangle for the given text within the rectangle specified by the x and y coordinates, width, and height.
If Qt::TextExpandTabs is set in flags and tabArray is non-null, it specifies a 0-terminated sequence of pixel-positions for tabs; otherwise, if tabStops is non-zero, it is used as the tab spacing (in pixels).
Definition at line 106 of file qfontmetrics.h.
         { return boundingRect(QRect(x, y, w, h), flags, text, tabstops, tabarray); }
charWidth()
int QFontMetrics::charWidth (const QString & text, int pos) const
Returns the width of the character at position pos in the string text.
The whole string is needed, as the glyph drawn may change depending on the context (the letter before and after the current one) for some languages (e.g. Arabic).
This function also takes non spacing marks and ligatures into account.
Definition at line 666 of file qfontmetrics.cpp.
 {
     if (pos < 0 || pos > (int)text.length())
         return 0;
     QChar ch = text.unicode()[pos];
     const int script = QUnicodeTables::script(ch);
     int width;
     if (script != QUnicodeTables::Common) {
         // complex script shaping. Have to do some hard work
         int from = qMax(0, pos - 8);
         int to = qMin(text.length(), pos + 8);
         QString cstr = QString::fromRawData(text.unicode() + from, to - from);
         QStackTextEngine layout(cstr, d.data());
         layout.ignoreBidi = true;
         layout.itemize();
         width = qRound(layout.width(pos-from, 1));
     } else if (QChar::category(ch.unicode()) == QChar::Mark_NonSpacing) {
         width = 0;
     } else {
         QFontEngine *engine;
         if (d->capital == QFont::SmallCaps && ch.isLower())
             engine = d->smallCapsFontPrivate()->engineForScript(script);
         else
             engine = d->engineForScript(script);
         Q_ASSERT(engine != 0);
         d->alterCharForCapitalization(ch);
         QGlyphLayoutArray<8> glyphs;
         int nglyphs = 7;
         engine->stringToCMap(&ch, 1, &glyphs, &nglyphs, 0);
         width = qRound(glyphs.advances_x[0]);
     }
     return width;
 }
descent()
int QFontMetrics::descent () const
Returns the descent of the font.
The descent is the distance from the base line to the lowest point characters extend to. In practice, some font designers break this rule, e.g. to accommodate an unusual character in an exotic language, so it is possible (though rare) that this value will be too small.
See also
ascent()
Definition at line 323 of file qfontmetrics.cpp.
Referenced by QCommonStyle::drawControl(), QWindowsVistaStyle::drawControl(), QGtkStyle::drawControl(), and QTipLabel::reuseTip().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->descent());
 }
elidedText()
QString QFontMetrics::elidedText (const QString & text, Qt::TextElideMode mode, int width, int flags = 0) const
If the string text is wider than width, returns an elided version of the string (i.
Since
4.2
e., a string with "..." in it). Otherwise, returns the original string.
The mode parameter specifies whether the text is elided on the left (e.g., "...tech"), in the middle (e.g., "Tr...ch"), or on the right (e.g., "Trol...").
The width is specified in pixels, not characters.
The flags argument is optional and currently only supports Qt::TextShowMnemonic as value.
The elide mark will follow the layout direction; it will be on the right side of the text for right-to-left layouts, and on the left side for right-to-left layouts. Note that this behavior is independent of the text language.
Definition at line 937 of file qfontmetrics.cpp.
Referenced by QCleanlooksStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QGtkStyle::drawControl(), QMacStyle::drawControl(), QItemDelegate::drawDisplay(), QAbstractItemDelegate::elidedText(), QGraphicsWidgetPrivate::initStyleOptionTitleBar(), QLineEdit::paintEvent(), QWorkspaceTitleBar::paintEvent(), QFileDialogComboBox::paintEvent(), QHeaderView::paintSection(), QMdiSubWindowPrivate::titleBarOptions(), and QDeclarativeTextPrivate::updateLayout().
 {
     QString _text = text;
     if (!(flags & Qt::TextLongestVariant)) {
         int posA = 0;
         int posB = _text.indexOf(QLatin1Char('\x9c'));
         while (posB >= 0) {
             QString portion = _text.mid(posA, posB - posA);
             if (size(flags, portion).width() <= width)
                 return portion;
             posA = posB + 1;
             posB = _text.indexOf(QLatin1Char('\x9c'), posA);
         }
         _text = _text.mid(posA);
     }
     QStackTextEngine engine(_text, QFont(d.data()));
     return engine.elidedText(mode, width, flags);
 }
height()
int QFontMetrics::height () const
Returns the height of the font.
This is always equal to ascent()+descent()+1 (the 1 is for the base line).
See also
leading(), lineSpacing()
Definition at line 338 of file qfontmetrics.cpp.
Referenced by QAccessibleLineEdit::characterRect(), QCommandLinkButtonPrivate::descriptionOffset(), QItemDelegate::doLayout(), QDragManager::drag(), QWindowsStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QTextDocumentLayoutPrivate::drawListItem(), QStatusBar::event(), QPlainTextEdit::event(), QScriptEdit::extraAreaPaintEvent(), QDeclarativeTextEdit::loadCursorDelegate(), QGroupBox::minimumSizeHint(), QLineEdit::minimumSizeHint(), QLineEdit::paintEvent(), QCommonStyle::pixelMetric(), QPlastiqueStyle::pixelMetric(), QStyleSheetStyle::pixelMetric(), qt_aqua_get_known_size(), QMdi::SimpleCascader::rearrange(), QStatusBar::reformat(), QDecorationWindows::region(), QHeaderView::setDefaultSectionSize(), QDeclarativeTextInput::setFont(), QDeclarativeTextEdit::setFont(), QScrollArea::sizeHint(), QProgressBar::sizeHint(), QFontFamilyDelegate::sizeHint(), QLineEdit::sizeHint(), QCommonStyle::subControlRect(), QWindowsMobileStyle::subControlRect(), QWindowsCEStyle::subControlRect(), QCleanlooksStyle::subControlRect(), QStyleSheetStyle::subControlRect(), QTabBar::tabSizeHint(), QStyleSheetStyle::titleBarLayout(), QDockWidgetLayout::titleHeight(), QCommandLinkButtonPrivate::titleRect(), QMenuPrivate::updateActionRects(), QDeclarativeTextPrivate::updateSize(), QDeclarativeTextEdit::updateSize(), and QCommonStylePrivate::viewItemLayout().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->ascent()) + qRound(engine->descent()) + 1;
 }
inFont()
bool QFontMetrics::inFont (QChar ch) const
Returns true if character ch is a valid character in the font; otherwise returns false.
Definition at line 449 of file qfontmetrics.cpp.
Referenced by QCommonStyle::styleHint(), and QWindowsStyle::styleHint().
 {
     const int script = QUnicodeTables::script(ch);
     QFontEngine *engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     if (engine->type() == QFontEngine::Box)
         return false;
     return engine->canRender(&ch, 1);
 }
inFontUcs4()
bool QFontMetrics::inFontUcs4 (uint character) const
Returns true if the given character encoded in UCS-4/UTF-32 is a valid character in the font; otherwise returns false.
Since
4.8
Definition at line 469 of file qfontmetrics.cpp.
 {
     const int script = QUnicodeTables::script(ucs4);
     QFontEngine *engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     if (engine->type() == QFontEngine::Box)
         return false;
     QString utf16 = QString::fromUcs4(&ucs4, 1);
     return engine->canRender(utf16.data(), utf16.length());
 }
leading()
int QFontMetrics::leading () const
Returns the leading of the font.
This is the natural inter-line spacing.
See also
height(), lineSpacing()
Definition at line 352 of file qfontmetrics.cpp.
Referenced by QLineEdit::minimumSizeHint().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->leading());
 }
leftBearing()
int QFontMetrics::leftBearing (QChar ch) const
Returns the left bearing of character ch in the font.
The left bearing is the right-ward distance of the left-most pixel of the character from the logical origin of the character. This value is negative if the pixels of the character extend to the left of the logical origin.
See width(QChar) for a graphical description of this metric.
See also
rightBearing(), minLeftBearing(), width()
Definition at line 492 of file qfontmetrics.cpp.
 {
     const int script = QUnicodeTables::script(ch);
     QFontEngine *engine;
     if (d->capital == QFont::SmallCaps && ch.isLower())
         engine = d->smallCapsFontPrivate()->engineForScript(script);
     else
         engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     if (engine->type() == QFontEngine::Box)
         return 0;
     d->alterCharForCapitalization(ch);
     QGlyphLayoutArray<10> glyphs;
     int nglyphs = 9;
     engine->stringToCMap(&ch, 1, &glyphs, &nglyphs, 0);
     // ### can nglyphs != 1 happen at all? Not currently I think
     qreal lb;
     engine->getGlyphBearings(glyphs.glyphs[0], &lb);
     return qRound(lb);
 }
lineSpacing()
int QFontMetrics::lineSpacing () const
Returns the distance from one base line to the next.
This value is always equal to leading()+height().
See also
height(), leading()
Definition at line 366 of file qfontmetrics.cpp.
Referenced by QTextDocumentLayoutPrivate::drawListItem(), QScriptEdit::extraAreaMouseEvent(), QScriptEdit::extraAreaPaintEvent(), QScriptEdit::extraAreaWidth(), and QLabelPrivate::sizeForWidth().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->leading()) + qRound(engine->ascent()) + qRound(engine->descent()) + 1;
 }
lineWidth()
int QFontMetrics::lineWidth () const
Returns the width of the underline and strikeout lines, adjusted for the point size of the font.
See also
underlinePos(), overlinePos(), strikeOutPos()
Definition at line 998 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->lineThickness());
 }
maxWidth()
int QFontMetrics::maxWidth () const
Returns the width of the widest character in the font.
Definition at line 410 of file qfontmetrics.cpp.
Referenced by QLineEdit::minimumSizeHint(), and QHeaderView::setDefaultSectionSize().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->maxCharWidth());
 }
minLeftBearing()
int QFontMetrics::minLeftBearing () const
Returns the minimum left bearing of the font.
This is the smallest leftBearing(char) of all characters in the font.
Note that this function can be very slow if the font is large.
See also
minRightBearing(), leftBearing()
Definition at line 383 of file qfontmetrics.cpp.
Referenced by QLineEdit::paintEvent().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->minLeftBearing());
 }
minRightBearing()
int QFontMetrics::minRightBearing () const
Returns the minimum right bearing of the font.
This is the smallest rightBearing(char) of all characters in the font.
Note that this function can be very slow if the font is large.
See also
minLeftBearing(), rightBearing()
Definition at line 400 of file qfontmetrics.cpp.
Referenced by QLineEdit::paintEvent().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->minRightBearing());
 }
operator!=() [1/2]
bool QFontMetrics::operator!= (const QFontMetrics & other) inline
Returns true if other is not equal to this object; otherwise returns false.
Two font metrics are considered equal if they were constructed from the same QFont and the paint devices they were constructed for are considered compatible.
See also
operator==()
Definition at line 122 of file qfontmetrics.h.
 { return !operator==(other); } // 5.0 - remove me
operator!=() [2/2]
bool QFontMetrics::operator!= (const QFontMetrics & other) const inline
Returns true if other is not equal to this object; otherwise returns false.
Two font metrics are considered equal if they were constructed from the same QFont and the paint devices they were constructed for are considered compatible.
See also
operator==()
Definition at line 123 of file qfontmetrics.h.
 { return !operator==(other); }
operator=()
QFontMetrics & QFontMetrics::operator= (const QFontMetrics & fm)
Assigns the font metrics fm.
Definition at line 223 of file qfontmetrics.cpp.
 {
     d = fm.d.data();
     return *this;
 }
operator==() [1/2]
bool QFontMetrics::operator== (const QFontMetrics & other)
Returns true if other is equal to this object; otherwise returns false.
Two font metrics are considered equal if they were constructed from the same QFont and the paint devices they were constructed for are considered compatible.
See also
operator!=()
Definition at line 258 of file qfontmetrics.cpp.
 {
     return d == other.d;
 }
operator==() [2/2]
bool QFontMetrics::operator== (const QFontMetrics & other) const
Returns true if other is equal to this object; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Two font metrics are considered equal if they were constructed from the same QFont and the paint devices they were constructed for are considered compatible.
See also
operator!=()
Definition at line 243 of file qfontmetrics.cpp.
 {
     return d == other.d;
 }
overlinePos()
int QFontMetrics::overlinePos () const
Returns the distance from the base line to where an overline should be drawn.
See also
underlinePos(), strikeOutPos(), lineWidth()
Definition at line 975 of file qfontmetrics.cpp.
 {
     return ascent() + 1;
 }
rightBearing()
int QFontMetrics::rightBearing (QChar ch) const
Returns the right bearing of character ch in the font.
The right bearing is the left-ward distance of the right-most pixel of the character from the logical origin of a subsequent character. This value is negative if the pixels of the character extend to the right of the width() of the character.
See width() for a graphical description of this metric.
See also
leftBearing(), minRightBearing(), width()
Definition at line 527 of file qfontmetrics.cpp.
 {
     const int script = QUnicodeTables::script(ch);
     QFontEngine *engine;
     if (d->capital == QFont::SmallCaps && ch.isLower())
         engine = d->smallCapsFontPrivate()->engineForScript(script);
     else
         engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     if (engine->type() == QFontEngine::Box)
         return 0;
     d->alterCharForCapitalization(ch);
     QGlyphLayoutArray<10> glyphs;
     int nglyphs = 9;
     engine->stringToCMap(&ch, 1, &glyphs, &nglyphs, 0);
     // ### can nglyphs != 1 happen at all? Not currently I think
     qreal rb;
     engine->getGlyphBearings(glyphs.glyphs[0], 0, &rb);
     return qRound(rb);
 }
size()
QSize QFontMetrics::size (int flags, const QString & text, int tabStops = 0, int * tabArray = 0) const
Returns the size in pixels of text.
Use the size() function in combination with QString::left() instead.
The flags argument is the bitwise OR of the following flags:
Qt::TextSingleLine ignores newline characters.
Qt::TextExpandTabs expands tabs (see below)
Qt::TextShowMnemonic interprets "&x" as x; i.e., underlined.
Qt::TextWordBreak breaks the text to fit the rectangle.
If Qt::TextExpandTabs is set in flags, then: if tabArray is non-null, it specifies a 0-terminated sequence of pixel-positions for tabs; otherwise if tabStops is non-zero, it is used as the tab spacing (in pixels).
Newline characters are processed as linebreaks.
Despite the different actual character heights, the heights of the bounding rectangles of "Yes" and "yes" are the same.
See also
boundingRect()
QSize size = size(flags, str, len, tabstops, tabarray); QSize size = size(flags, str.left(len), tabstops, tabarray);
Definition at line 870 of file qfontmetrics.cpp.
Referenced by QMenuBarPrivate::calcActionRects(), elidedText(), QMacStyle::sizeFromContents(), QPushButton::sizeHint(), QToolBoxButton::sizeHint(), QToolButton::sizeHint(), DetailButton::sizeHint(), QCommonStyle::subControlRect(), QWindowsMobileStyle::subControlRect(), QWindowsCEStyle::subControlRect(), and QTabBar::tabSizeHint().
 {
     return boundingRect(QRect(0,0,0,0), flags | Qt::TextLongestVariant, text, tabStops, tabArray).size();
 }
strikeOutPos()
int QFontMetrics::strikeOutPos () const
Returns the distance from the base line to where the strikeout line should be drawn.
See also
underlinePos(), overlinePos(), lineWidth()
Definition at line 986 of file qfontmetrics.cpp.
 {
     int pos = ascent() / 3;
     return pos > 0 ? pos : 1;
 }
tightBoundingRect()
QRect QFontMetrics::tightBoundingRect (const QString & text) const
Returns a tight bounding rectangle around the characters in the string specified by text.
Since
4.3
The bounding rectangle always covers at least the set of pixels the text would cover if drawn at (0, 0).
Note that the bounding rectangle may extend to the left of (0, 0), e.g. for italicized fonts, and that the width of the returned rectangle might be different than what the width() method returns.
If you want to know the advance width of the string (to layout a set of strings next to each other), use width() instead.
Newline characters are processed as normal characters, not as linebreaks.
Warning
Calling this method is very slow on Windows.
See also
width(), height(), boundingRect()
Definition at line 900 of file qfontmetrics.cpp.
 {
     if (text.length() == 0)
         return QRect();
     QStackTextEngine layout(text, d.data());
     layout.ignoreBidi = true;
     layout.itemize();
     glyph_metrics_t gm = layout.tightBoundingBox(0, text.length());
     return QRect(qRound(gm.x), qRound(gm.y), qRound(gm.width), qRound(gm.height));
 }
underlinePos()
int QFontMetrics::underlinePos () const
Returns the distance from the base line to where an underscore should be drawn.
See also
overlinePos(), strikeOutPos(), lineWidth()
Definition at line 962 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->underlinePosition());
 }
width() [1/3]
int QFontMetrics::width (const QString & text, int len = -1) const
Returns the width in pixels of the first len characters of text.
If len is negative (the default), the entire string is used.
Note that this value is not equal to boundingRect().width(); boundingRect() returns a rectangle describing the pixels this string will cover whereas width() returns the distance to where the next string should be drawn.
See also
boundingRect()
Definition at line 562 of file qfontmetrics.cpp.
Referenced by QTextDocument::adjustSize(), QAccessibleLineEdit::characterRect(), charWidth(), QComboBoxPrivate::computeWidthHint(), QDragManager::drag(), QTextLine::draw(), QPlastiqueStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QTextDocumentLayoutPrivate::drawListItem(), elidedText(), elliditide(), QScriptEdit::extraAreaWidth(), QPlainTextDocumentLayout::layoutBlock(), QGroupBox::minimumSizeHint(), QAbstractSpinBox::minimumSizeHint(), QFontFamilyDelegate::paint(), printPage(), qt_aqua_get_known_size(), qt_mac_get_fixed_pitch(), QComboBoxPrivate::recomputeSizeHint(), QExpandingLineEdit::resizeToContents(), QLabelPrivate::sizeForWidth(), QCleanlooksStyle::sizeFromContents(), QWindowsStyle::sizeFromContents(), QToolButton::sizeHint(), QFontComboBox::sizeHint(), QProgressBar::sizeHint(), QFontFamilyDelegate::sizeHint(), QAbstractSpinBox::sizeHint(), QLineEdit::sizeHint(), QDateTimeEdit::sizeHint(), QStyleSheetStyle::subControlRect(), QStyleSheetStyle::titleBarLayout(), QMessageBoxPrivate::updateSize(), and width().
 {
     return width(text, len, 0);
 }
width() [2/3]
int QFontMetrics::width (const QString & text, int len, int flags) const
Warning
This function is not part of the public interface.
Definition at line 570 of file qfontmetrics.cpp.
 {
     int pos = text.indexOf(QLatin1Char('\x9c'));
     if (pos != -1) {
         len = (len < 0) ? pos : qMin(pos, len);
     } else if (len < 0) {
         len = text.length();
     }
     if (len == 0)
         return 0;
     if (flags & Qt::TextBypassShaping) {
         // Skip harfbuzz complex shaping, only use advances
         int numGlyphs = len;
         QVarLengthGlyphLayoutArray glyphs(numGlyphs);
         QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
         if (!engine->stringToCMap(text.data(), len, &glyphs, &numGlyphs, 0)) {
             glyphs.resize(numGlyphs);
             if (!engine->stringToCMap(text.data(), len, &glyphs, &numGlyphs, 0))
                 Q_ASSERT_X(false, Q_FUNC_INFO, "stringToCMap shouldn't fail twice");
         }
         QFixed width;
         for (int i = 0; i < numGlyphs; ++i)
             width += glyphs.advances_x[i];
         return qRound(width);
     }
     QStackTextEngine layout(text, d.data());
     layout.ignoreBidi = true;
     return qRound(layout.width(0, len));
 }
width() [3/3]
int QFontMetrics::width (QChar ch) const
Returns the logical width of character ch in pixels.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Bearings
This is a distance appropriate for drawing a subsequent character after ch.
Some of the metrics are described in the image to the right. The central dark rectangles cover the logical width() of each character. The outer pale rectangles cover the leftBearing() and rightBearing() of each character. Notice that the bearings of "f" in this particular font are both negative, while the bearings of "o" are both positive.
Warning
This function will produce incorrect results for Arabic characters or non-spacing marks in the middle of a string, as the glyph shaping and positioning of marks that happens when processing strings cannot be taken into account. When implementing an interactive text control, use QTextLayout instead.
See also
boundingRect()
Definition at line 630 of file qfontmetrics.cpp.
 {
     if (QChar::category(ch.unicode()) == QChar::Mark_NonSpacing)
         return 0;
     const int script = QUnicodeTables::script(ch);
     QFontEngine *engine;
     if (d->capital == QFont::SmallCaps && ch.isLower())
         engine = d->smallCapsFontPrivate()->engineForScript(script);
     else
         engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     d->alterCharForCapitalization(ch);
     QGlyphLayoutArray<8> glyphs;
     int nglyphs = 7;
     engine->stringToCMap(&ch, 1, &glyphs, &nglyphs, 0);
     return qRound(glyphs.advances_x[0]);
 }
xHeight()
int QFontMetrics::xHeight () const
Returns the 'x' height of the font.
This is often but not always the same as the height of the character 'x'.
Definition at line 421 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     if (d->capital == QFont::SmallCaps)
         return qRound(d->smallCapsFontPrivate()->engineForScript(QUnicodeTables::Common)->ascent());
     return qRound(engine->xHeight());
 }
Friends and Related Functions
QFontMetricsF
friend class QFontMetricsF friend
Definition at line 138 of file qfontmetrics.h.
QFontPrivate
friend class QFontPrivate friend
Definition at line 136 of file qfontmetrics.h.
Referenced by QFontMetrics().
QStackTextEngine
friend class QStackTextEngine friend
Definition at line 139 of file qfontmetrics.h.
Properties
d
QExplicitlySharedDataPointer<QFontPrivate> QFontMetrics::d private
Definition at line 141 of file qfontmetrics.h.
Referenced by ascent(), averageCharWidth(), boundingRect(), charWidth(), descent(), elidedText(), height(), inFont(), inFontUcs4(), leading(), leftBearing(), lineSpacing(), lineWidth(), maxWidth(), minLeftBearing(), minRightBearing(), operator=(), QFontMetricsF::operator=(), operator==(), QFontMetrics(), rightBearing(), tightBoundingRect(), underlinePos(), width(), and xHeight().
The documentation for this class was generated from the following files:
/src/gui/text/qfontmetrics.h
/src/gui/text/qfontmetrics.cpp