Qt 4.8: QPatternist::StaticContext Class Reference
QPatternist::StaticContext Class Reference abstract
Carries information and facilities used at compilation time.
#include <qstaticcontext_p.h>
Public Types
enum BoundarySpacePolicy { BSPPreserve, BSPStrip }
enum ConstructionMode { CMPreserve, CMStrip }
enum InheritMode { Inherit, NoInherit }
enum OrderingEmptySequence { Greatest, Least }
enum OrderingMode { Ordered, Unordered }
enum PreserveMode { Preserve, NoPreserve }
typedef QExplicitlySharedDataPointer< StaticContext > Ptr
Public Types inherited from QPatternist::ReportContext
enum ErrorCode {
XSDError, XPST0001, XPDY0002, XPST0003,
XPTY0004, XPST0005, XPTY0006, XPTY0007,
XPST0008, XQST0009, XPST0010, XQST0012,
XQST0013, XQST0014, XQST0015, XQST0016,
XPST0017, XPTY0018, XPTY0019, XPTY0020,
XPDY0021, XQST0022, XQTY0023, XQTY0024,
XQDY0025, XQDY0026, XQDY0027, XQTY0028,
XQDY0029, XQTY0030, XQST0031, XQST0032,
XQST0033, XQST0034, XQST0035, XQST0036,
XQST0037, XQST0038, XQST0039, XQST0040,
XQDY0041, XQST0042, XQST0043, XQDY0044,
XQST0045, XQST0046, XQST0047, XQST0048,
XQST0049, XPDY0050, XPST0051, XQDY0052,
XQST0053, XQST0054, XQST0055, XQST0056,
XQST0057, XQST0058, XQST0059, XQST0060,
XQDY0061, XQDY0062, XQST0063, XQDY0064,
XQST0065, XQST0066, XQST0067, XQST0068,
XQST0069, XQST0070, XQST0071, XQDY0072,
XQST0073, XQDY0074, XQST0075, XQST0076,
XQST0077, XQST0078, XQST0079, XPST0080,
XPST0081, XQST0082, XPST0083, XQDY0084,
XQST0085, XQTY0086, XQST0087, XQST0088,
XQST0089, XQST0090, XQDY0091, XQDY0092,
XQST0093, FOER0000, FOAR0001, FOAR0002,
FOCA0001, FOCA0002, FOCA0003, FOCA0005,
FOCA0006, FOCH0001, FOCH0002, FOCH0003,
FOCH0004, FODC0001, FODC0002, FODC0003,
FODC0004, FODC0005, FODT0001, FODT0002,
FODT0003, FONS0004, FONS0005, FORG0001,
FORG0002, FORG0003, FORG0004, FORG0005,
FORG0006, FORG0008, FORG0009, FORX0001,
FORX0002, FORX0003, FORX0004, FOTY0012,
SENR0001, SERE0003, SEPM0004, SERE0005,
SERE0006, SESU0007, SERE0008, SEPM0009,
SEPM0010, SESU0011, SERE0012, SESU0013,
SERE0014, SERE0015, SEPM0016, XTSE0010,
XTSE0020, XTSE0080, XTSE0090, XTSE0110,
XTSE0120, XTSE0125, XTSE0130, XTSE0150,
XTSE0165, XTSE0170, XTSE0180, XTSE0190,
XTSE0200, XTSE0210, XTSE0215, XTSE0220,
XTSE0260, XTSE0265, XTSE0280, XTSE0340,
XTSE0350, XTSE0370, XTSE0500, XTSE0530,
XTSE0550, XTSE0580, XTSE0620, XTSE0630,
XTSE0650, XTSE0660, XTSE0670, XTSE0680,
XTSE0690, XTSE0710, XTSE0720, XTSE0740,
XTSE0760, XTSE0770, XTSE0805, XTSE0808,
XTSE0809, XTSE0810, XTSE0812, XTSE0840,
XTSE0870, XTSE0880, XTSE0910, XTSE0940,
XTTE0950, XTSE0975, XTSE1015, XTSE1017,
XTSE1040, XTSE1060, XTSE1070, XTSE1080,
XTSE1090, XTSE1130, XTSE1205, XTSE1210,
XTSE1220, XTSE1290, XTSE1295, XTSE1300,
XTSE1430, XTSE1505, XTSE1520, XTSE1530,
XTSE1560, XTSE1570, XTSE1580, XTSE1590,
XTSE1600, XTSE1650, XTSE1660, XTTE0505,
XTTE0510, XTTE0520, XTTE0570, XTTE0590,
XTTE0600, XTTE0780, XTTE0790, XTTE0990,
XTTE1000, XTTE1020, XTTE1100, XTTE1120,
XTTE1510, XTTE1512, XTTE1515, XTTE1540,
XTTE1545, XTTE1550, XTTE1555, XTDE0030,
XTDE0040, XTDE0045, XTDE0047, XTDE0050,
XTDE0060, XTDE0160, XTRE0270, XTDE0290,
XTDE0410, XTDE0420, XTDE0430, XTDE0440,
XTDE0485, XTRE0540, XTDE0560, XTDE0610,
XTDE0640, XTDE0700, XTRE0795, XTDE0820,
XTDE0830, XTDE0835, XTDE0850, XTDE0855,
XTDE0860, XTDE0865, XTDE0890, XTDE0905,
XTDE0920, XTDE0925, XTDE0930, XTDE0980,
XTDE1030, XTDE1035, XTDE1110, XTDE1140,
XTDE1145, XTDE1150, XTRE1160, XTDE1170,
XTDE1190, XTDE1200, XTDE1260, XTDE1270,
XTDE1280, XTDE1310, XTDE1340, XTDE1350,
XTDE1360, XTDE1370, XTDE1380, XTDE1390,
XTMM9000, XTDE1400, XTDE1420, XTDE1425,
XTDE1428, XTDE1440, XTDE1450, XTDE1460,
XTDE1480, XTDE1490, XTRE1495, XTRE1500,
XTRE1620, XTRE1630, XTDE1665
}
typedef QHash< const SourceLocationReflection *, QSourceLocation > LocationHash
typedef QExplicitlySharedDataPointer< ReportContext > Ptr
Public Functions
virtual void addLocation (const SourceLocationReflection *const reflection, const QSourceLocation &location)=0
Adds location for reflection.
virtual VariableSlotID allocateRangeSlot ()=0
virtual QUrl baseURI () const =0
virtual BoundarySpacePolicy boundarySpacePolicy () const =0
virtual bool compatModeEnabled () const =0
virtual ConstructionMode constructionMode () const =0
virtual ItemType::Ptr contextItemType () const =0
The static type of the context item.
virtual StaticContext::Ptr copy () const =0
virtual ItemType::Ptr currentItemType () const =0
The static type of the current item, as returned by fn:current().
virtual VariableSlotID currentRangeSlot () const =0
virtual QUrl defaultCollation () const =0
virtual QString defaultElementNamespace () const =0
virtual QString defaultFunctionNamespace () const =0
virtual QExplicitlySharedDataPointer< DynamicContext > dynamicContext () const =0
virtual ExternalVariableLoader::Ptr externalVariableLoader () const =0
virtual QExplicitlySharedDataPointer< FunctionFactory > functionSignatures () const =0
virtual InheritMode inheritMode () const =0
virtual NamePool::Ptr namePool () const =0
virtual NamespaceResolver::Ptr namespaceBindings () const =0
virtual OrderingEmptySequence orderingEmptySequence () const =0
virtual OrderingMode orderingMode () const =0
virtual PreserveMode preserveMode () const =0
virtual ResourceLoader::Ptr resourceLoader () const =0
virtual QExplicitlySharedDataPointer< SchemaTypeFactory > schemaDefinitions () const =0
virtual void setBaseURI (const QUrl &uri)=0
virtual void setBoundarySpacePolicy (const BoundarySpacePolicy policy)=0
virtual void setCompatModeEnabled (const bool newVal)=0
virtual void setConstructionMode (const ConstructionMode mode)=0
virtual void setDefaultCollation (const QUrl &uri)=0
virtual void setDefaultElementNamespace (const QString &ns)=0
virtual void setDefaultFunctionNamespace (const QString &ns)=0
virtual void setInheritMode (const InheritMode mode)=0
virtual void setNamespaceBindings (const NamespaceResolver::Ptr &)=0
virtual void setOrderingEmptySequence (const OrderingEmptySequence ordering)=0
virtual void setOrderingMode (const OrderingMode mode)=0
virtual void setPreserveMode (const PreserveMode mode)=0
virtual LocationHash sourceLocations () const =0
Returns a hash of the contained locations.
StaticContext ()
void wrapExpressionWith (const SourceLocationReflection *const existingNode, const QExplicitlySharedDataPointer< Expression > &newNode)
Ensures source locations are handled in such a manner that existingNode wraps newNode.
virtual ~StaticContext ()
Public Functions inherited from QPatternist::ReportContext
void error (const QString &message, const ReportContext::ErrorCode errorCode, const QSourceLocation &sourceLocation)
void error (const QString &message, const ReportContext::ErrorCode errorCode, const SourceLocationReflection *const reflection)
void error (const QString &message, const QXmlName qName, const SourceLocationReflection *const r)
virtual QSourceLocation locationFor (const SourceLocationReflection *const reflection) const =0
Returns the source location applying for reflection.
virtual QAbstractMessageHandler * messageHandler () const =0
ReportContext ()
Default constructors.
QUrl resolveURI (const QUrl &relative, const QUrl &baseURI) const
virtual const QAbstractUriResolver * uriResolver () const =0
The URI resolver in use.
void warning (const QString &message, const QSourceLocation &sourceLocation=QSourceLocation())
virtual ~ReportContext ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Additional Inherited Members
Static Public Functions inherited from QPatternist::ReportContext
static QString codeFromURI (const QString &typeURI, QString &uri)
static QString codeToString (const ReportContext::ErrorCode errorCode)
Public Variables inherited from QSharedData
QAtomicInt ref
Related Functions inherited from QPatternist::ReportContext
typedef bool Exception
This is the class type that is being thrown when a query error occur.
Detailed Description
Carries information and facilities used at compilation time.
A representation of the Static Context in XPath 2.0. The Static Context contains information which doesn't change and is the "outer scope" of the expression. It provides for example a base URI the expression can relate to and what functions and variables that are available for the expression.
See also
XML Path Language (XPath) 2.0, 2.1.1 Static Context
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 88 of file qstaticcontext_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<StaticContext> QPatternist::StaticContext::Ptr
A smart pointer wrapping StaticContext instances.
Definition at line 94 of file qstaticcontext_p.h.
Enumerations
BoundarySpacePolicy
enum QPatternist::StaticContext::BoundarySpacePolicy
See also
XQuery 1.0: An XML Query Language, 4.3 Boundary-space Declaration
XQuery 1.0: An XML Query Language, Definition: Boundary-space policy
Enumerator
BSPPreserve
BSPStrip
Definition at line 102 of file qstaticcontext_p.h.
         {
             BSPPreserve,
             BSPStrip
         };
ConstructionMode
enum QPatternist::StaticContext::ConstructionMode
See also
XQuery 1.0: An XML Query Language, 4.6 Construction Declaration
XQuery 1.0: An XML Query Language, Definition: Construction mode
Enumerator
CMPreserve
CMStrip
Definition at line 114 of file qstaticcontext_p.h.
         {
             CMPreserve,
             CMStrip
         };
InheritMode
enum QPatternist::StaticContext::InheritMode
Enumerator
Inherit
NoInherit
Definition at line 144 of file qstaticcontext_p.h.
         {
             Inherit,
             NoInherit
         };
OrderingEmptySequence
enum QPatternist::StaticContext::OrderingEmptySequence
See also
XQuery 1.0: An XML Query Language, 4.8 Empty Order Declaration
XQuery 1.0: An XML Query Language, Definition: Default order for empty sequences
Enumerator
Greatest
Least
Definition at line 138 of file qstaticcontext_p.h.
         {
             Greatest,
             Least
         };
OrderingMode
enum QPatternist::StaticContext::OrderingMode
See also
XQuery 1.0: An XML Query Language, 4.7 Ordering Mode Declaration
XQuery 1.0: An XML Query Language, Definition: Ordering mode
Enumerator
Ordered
Unordered
Definition at line 126 of file qstaticcontext_p.h.
         {
             Ordered,
             Unordered
         };
PreserveMode
enum QPatternist::StaticContext::PreserveMode
Enumerator
Preserve
NoPreserve
Definition at line 150 of file qstaticcontext_p.h.
         {
             Preserve,
             NoPreserve
         };
Constructors and Destructors
StaticContext()
QPatternist::StaticContext::StaticContext () inline
Definition at line 156 of file qstaticcontext_p.h.
         {
         }
~StaticContext()
StaticContext::~StaticContext () virtual
Definition at line 51 of file qstaticcontext.cpp.
Referenced by StaticContext().
 {
 }
Functions
addLocation()
virtual void QPatternist::StaticContext::addLocation (const SourceLocationReflection *const reflection, const QSourceLocation & location) pure virtual
Adds location for reflection.
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::addLocation(), StaticContext(), QPatternist::DocumentFN::typeCheck(), and wrapExpressionWith().
allocateRangeSlot()
virtual VariableSlotID QPatternist::StaticContext::allocateRangeSlot () pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::allocateRangeSlot(), StaticContext(), and QPatternist::DocumentFN::typeCheck().
baseURI()
virtual QUrl QPatternist::StaticContext::baseURI () const pure virtual
The base URI of the context. Typically, this is the base URI if of the element that contained the expression.
The base URI is in this implementation is never undefined, but is always valid.
Implemented in QPatternist::GenericStaticContext, QPatternist::DelegatingStaticContext, and QPatternist::StaticBaseURIContext.
Referenced by QPatternist::DelegatingStaticContext::baseURI(), StaticContext(), QPatternist::ResolveURIFN::typeCheck(), QPatternist::StaticBaseURIStore::typeCheck(), QPatternist::DocumentConstructor::typeCheck(), QPatternist::ElementConstructor::typeCheck(), and QPatternist::StaticBaseURIFN::typeCheck().
boundarySpacePolicy()
virtual BoundarySpacePolicy QPatternist::StaticContext::boundarySpacePolicy () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::boundarySpacePolicy(), and StaticContext().
compatModeEnabled()
virtual bool QPatternist::StaticContext::compatModeEnabled () const pure virtual
Determine whether Backwards Compatible Mode is used.
See also
XML Path Language (XPath) 2.0, I Backwards Compatibility with XPath 1.0 (Non-Normative)
XML Path Language (XPath) 2.0, Definition: XPath 1.0 compatibility mode
Implemented in QPatternist::GenericStaticContext, QPatternist::DelegatingStaticContext, and QPatternist::StaticCompatibilityContext.
Referenced by QPatternist::DelegatingStaticContext::compatModeEnabled(), StaticContext(), QPatternist::ArithmeticExpression::typeCheck(), QPatternist::CardinalityVerifier::verifyCardinality(), and QPatternist::TypeChecker::verifyType().
constructionMode()
virtual ConstructionMode QPatternist::StaticContext::constructionMode () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::constructionMode(), and StaticContext().
contextItemType()
virtual ItemType::Ptr QPatternist::StaticContext::contextItemType () const pure virtual
The static type of the context item.
Different StaticContext instances are used for different nodes in the AST to properly reflect the type of the focus. If the focus is undefined, this function must return null.
See also
XQuery 1.0: An XML Query Language, Definition: Context item static type
Implemented in QPatternist::GenericStaticContext, QPatternist::DelegatingStaticContext, and QPatternist::StaticFocusContext.
Referenced by QPatternist::ContextItem::compress(), QPatternist::DelegatingStaticContext::contextItemType(), QPatternist::CurrentItemStore::newStaticContext(), StaticContext(), QPatternist::ContextItem::typeCheck(), and QPatternist::TypeChecker::verifyType().
copy()
virtual StaticContext::Ptr QPatternist::StaticContext::copy () const pure virtual
Copies this StaticContext and returns the copy.
The copy and original must not be independent. Since the StaticContext is modified during the compilation process, the copy must be independent from the original to the degree that is required for the subclass in question.
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::copy(), and StaticContext().
currentItemType()
virtual ItemType::Ptr QPatternist::StaticContext::currentItemType () const pure virtual
The static type of the current item, as returned by fn:current().
Implemented in QPatternist::GenericStaticContext, QPatternist::DelegatingStaticContext, and QPatternist::StaticCurrentContext.
Referenced by QPatternist::CurrentFN::compress(), QPatternist::DelegatingStaticContext::currentItemType(), StaticContext(), and QPatternist::CurrentFN::typeCheck().
currentRangeSlot()
virtual VariableSlotID QPatternist::StaticContext::currentRangeSlot () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::currentRangeSlot(), and StaticContext().
defaultCollation()
virtual QUrl QPatternist::StaticContext::defaultCollation () const pure virtual
Returns
the URI identifying the default collation. The function is responsible for ensuring a collation is always returned. If a collation is not provided by the user or the host language in the context, the Unicode codepoint URI should be returned.
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::defaultCollation(), StaticContext(), and QPatternist::DefaultCollationFN::typeCheck().
defaultElementNamespace()
virtual QString QPatternist::StaticContext::defaultElementNamespace () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::defaultElementNamespace(), and StaticContext().
defaultFunctionNamespace()
virtual QString QPatternist::StaticContext::defaultFunctionNamespace () const pure virtual
Returns
always the standard function namespace defined in XQuery 1.0 and XPath 2.0 Functions and Operators
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::defaultFunctionNamespace(), StaticContext(), and QPatternist::FunctionAvailableFN::typeCheck().
dynamicContext()
virtual QExplicitlySharedDataPointer<DynamicContext> QPatternist::StaticContext::dynamicContext () const pure virtual
This is the DynamicContext that is used for pre-evaluation at compilation time, const-folding at the static stage.
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::OrExpression::compress(), QPatternist::IfThenClause::compress(), QPatternist::AndExpression::compress(), QPatternist::ReplaceFN::compress(), QPatternist::PatternPlatform::compress(), QPatternist::NormalizeUnicodeFN::compress(), QPatternist::Expression::constantPropagate(), QPatternist::DelegatingStaticContext::dynamicContext(), StaticContext(), and QPatternist::DocFN::typeCheck().
externalVariableLoader()
virtual ExternalVariableLoader::Ptr QPatternist::StaticContext::externalVariableLoader () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::externalVariableLoader(), and StaticContext().
functionSignatures()
virtual QExplicitlySharedDataPointer<FunctionFactory> QPatternist::StaticContext::functionSignatures () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::ByIDCreator::create(), QPatternist::DelegatingStaticContext::functionSignatures(), StaticContext(), QPatternist::FunctionAvailableFN::typeCheck(), QPatternist::DocumentFN::typeCheck(), and QPatternist::TypeChecker::verifyType().
inheritMode()
virtual InheritMode QPatternist::StaticContext::inheritMode () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::inheritMode(), and StaticContext().
namePool()
virtual NamePool::Ptr QPatternist::StaticContext::namePool () const pure virtual
Implements QPatternist::ReportContext.
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::CastAs::castToQName(), QPatternist::GenericPredicate::create(), QPatternist::AbstractFunctionFactory::createFunctionCall(), QPatternist::ParserContext::finalizePushedVariable(), QPatternist::DelegatingStaticContext::namePool(), QPatternist::QNameConstructor::namespaceForPrefix(), QPatternist::TypeChecker::promotionPossible(), StaticContext(), QPatternist::FunctionAvailableFN::typeCheck(), QPatternist::AddingAggregate::typeCheck(), QPatternist::CastAs::typeCheck(), QPatternist::AvgFN::typeCheck(), QPatternist::SumFN::typeCheck(), QPatternist::AbstractFunctionFactory::verifyArity(), and QPatternist::TypeChecker::verifyType().
namespaceBindings()
virtual NamespaceResolver::Ptr QPatternist::StaticContext::namespaceBindings () const pure virtual
Implemented in QPatternist::GenericStaticContext, QPatternist::StaticNamespaceContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::CastAs::castToQName(), QPatternist::DelegatingStaticContext::namespaceBindings(), QPatternist::QNameConstructor::namespaceForPrefix(), QPatternist::ParserContext::ParserContext(), StaticContext(), QPatternist::StaticNamespacesContainer::typeCheck(), and QPatternist::ElementConstructor::typeCheck().
orderingEmptySequence()
virtual OrderingEmptySequence QPatternist::StaticContext::orderingEmptySequence () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::orderingEmptySequence(), and StaticContext().
orderingMode()
virtual OrderingMode QPatternist::StaticContext::orderingMode () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::orderingMode(), and StaticContext().
preserveMode()
virtual PreserveMode QPatternist::StaticContext::preserveMode () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::preserveMode(), and StaticContext().
resourceLoader()
virtual ResourceLoader::Ptr QPatternist::StaticContext::resourceLoader () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::resourceLoader(), StaticContext(), and QPatternist::DocFN::typeCheck().
schemaDefinitions()
virtual QExplicitlySharedDataPointer<SchemaTypeFactory> QPatternist::StaticContext::schemaDefinitions () const pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::schemaDefinitions(), StaticContext(), and QPatternist::TypeAvailableFN::typeCheck().
setBaseURI()
virtual void QPatternist::StaticContext::setBaseURI (const QUrl & uri) pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::setBaseURI(), and StaticContext().
setBoundarySpacePolicy()
virtual void QPatternist::StaticContext::setBoundarySpacePolicy (const BoundarySpacePolicy policy) pure virtual
Implemented in QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::setBoundarySpacePolicy(), and StaticContext().
setCompatModeEnabled()
virtual void QPatternist::StaticContext::setCompatModeEnabled (const bool newVal) pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::XSLTTokenizer::handleXSLTVersion(), QPatternist::DelegatingStaticContext::setCompatModeEnabled(), and StaticContext().
setConstructionMode()
virtual void QPatternist::StaticContext::setConstructionMode (const ConstructionMode mode) pure virtual
Implemented in QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::setConstructionMode(), and StaticContext().
setDefaultCollation()
virtual void QPatternist::StaticContext::setDefaultCollation (const QUrl & uri) pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::setDefaultCollation(), and StaticContext().
setDefaultElementNamespace()
virtual void QPatternist::StaticContext::setDefaultElementNamespace (const QString & ns) pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::setDefaultElementNamespace(), and StaticContext().
setDefaultFunctionNamespace()
virtual void QPatternist::StaticContext::setDefaultFunctionNamespace (const QString & ns) pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::setDefaultFunctionNamespace(), and StaticContext().
setInheritMode()
virtual void QPatternist::StaticContext::setInheritMode (const InheritMode mode) pure virtual
Implemented in QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::setInheritMode(), and StaticContext().
setNamespaceBindings()
virtual void QPatternist::StaticContext::setNamespaceBindings (const NamespaceResolver::Ptr &) pure virtual
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::setNamespaceBindings(), and StaticContext().
setOrderingEmptySequence()
virtual void QPatternist::StaticContext::setOrderingEmptySequence (const OrderingEmptySequence ordering) pure virtual
Implemented in QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::setOrderingEmptySequence(), and StaticContext().
setOrderingMode()
virtual void QPatternist::StaticContext::setOrderingMode (const OrderingMode mode) pure virtual
Implemented in QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::setOrderingMode(), and StaticContext().
setPreserveMode()
virtual void QPatternist::StaticContext::setPreserveMode (const PreserveMode mode) pure virtual
Implemented in QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::setPreserveMode(), and StaticContext().
sourceLocations()
virtual LocationHash QPatternist::StaticContext::sourceLocations () const pure virtual
Returns a hash of the contained locations.
The key is the address for the expression, and the value is its location. Note that the key cannot be dereferenced, there's no guarantee the Expression is in scope. The key is merely an identifier.
Implemented in QPatternist::GenericStaticContext, and QPatternist::DelegatingStaticContext.
Referenced by QPatternist::DelegatingStaticContext::sourceLocations(), and StaticContext().
wrapExpressionWith()
void StaticContext::wrapExpressionWith (const SourceLocationReflection *const existingNode, const QExplicitlySharedDataPointer< Expression > & newNode)
Ensures source locations are handled in such a manner that existingNode wraps newNode.
Ensures that the source locations for existingNode, applies to newNode.
Definition at line 55 of file qstaticcontext.cpp.
Referenced by QPatternist::EmptySequence::create(), QPatternist::ByIDCreator::create(), StaticContext(), QPatternist::FunctionCall::typeCheck(), QPatternist::IdFN::typeCheck(), QPatternist::TypeChecker::verifyType(), and QPatternist::NodeSortExpression::wrapAround().
 {
     addLocation(newNode.data(), locationFor(existingNode));
 }
The documentation for this class was generated from the following files:
/src/xmlpatterns/environment/qstaticcontext_p.h
/src/xmlpatterns/environment/qstaticcontext.cpp