Qt 4.8: QVolatileImage Class Reference
QVolatileImage Class Reference
#include <qvolatileimage_p.h>
Public Functions
void beginDataAccess () const
uchar * bits ()
Access to pixel data via bits() or constBits() should be guarded by begin/endDataAccess().
int byteCount () const
int bytesPerLine () const
const uchar * constBits () const
const QImage & constImageRef () const
Non-detaching version, for read-only access only.
void copyFrom (QVolatileImage *source, const QRect &rect)
int depth () const
void * duplicateNativeImage () const
void endDataAccess (bool readOnly=false) const
bool ensureFormat (QImage::Format format)
void fill (uint pixelValue)
QImage::Format format () const
bool hasAlphaChannel () const
int height () const
QImage & imageRef ()
Returns a reference to the image that is potentially using some native buffer internally.
bool isNull () const
QVolatileImage & operator= (const QVolatileImage &rhs)
QPaintEngine * paintEngine ()
To be called from the PixmapData's paintEngine().
bool paintingActive () const
QVolatileImage ()
QVolatileImage (int w, int h, QImage::Format format)
QVolatileImage (const QImage &sourceImage)
QVolatileImage (void *nativeImage, void *nativeMask=0)
QVolatileImage (const QVolatileImage &other)
void setAlphaChannel (const QPixmap &alphaChannel)
QImage toImage () const
This will always perform a copy of the pixel data.
int width () const
~QVolatileImage ()
Properties
QSharedDataPointer< QVolatileImageData > d
Detailed Description
Definition at line 63 of file qvolatileimage_p.h.
Constructors and Destructors
QVolatileImage() [1/5]
QVolatileImage::QVolatileImage ()
Definition at line 68 of file qvolatileimage.cpp.
     : d(new QVolatileImageData)
 {
 }
QVolatileImage() [2/5]
QVolatileImage::QVolatileImage (int w, int h, QImage::Format format)
Definition at line 73 of file qvolatileimage.cpp.
     : d(new QVolatileImageData(w, h, format))
 {
 }
QVolatileImage() [3/5]
QVolatileImage::QVolatileImage (const QImage & sourceImage) explicit
Definition at line 78 of file qvolatileimage.cpp.
     : d(new QVolatileImageData(sourceImage))
 {
 }
QVolatileImage() [4/5]
QVolatileImage::QVolatileImage (void * nativeImage, void * nativeMask = 0) explicit
Definition at line 83 of file qvolatileimage.cpp.
     : d(new QVolatileImageData(nativeImage, nativeMask))
 {
 }
QVolatileImage() [5/5]
QVolatileImage::QVolatileImage (const QVolatileImage & other)
Definition at line 91 of file qvolatileimage.cpp.
     : d(other.d)
 {
 }
~QVolatileImage()
QVolatileImage::~QVolatileImage ()
Definition at line 96 of file qvolatileimage.cpp.
 {
 }
Functions
beginDataAccess()
void QVolatileImage::beginDataAccess () const
Definition at line 151 of file qvolatileimage.cpp.
Referenced by copyFrom(), QVolatileImagePaintEngine::drawPixmap(), QVGPaintEngine::drawPixmap(), QVGPixmapData::ensureReadback(), fill(), setAlphaChannel(), and QVGPixmapData::toVGImage().
 {
     d->beginDataAccess();
 }
bits()
uchar * QVolatileImage::bits ()
Access to pixel data via bits() or constBits() should be guarded by begin/endDataAccess().
Definition at line 165 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::ensureReadback().
 {
     return d->image.bits();
 }
byteCount()
int QVolatileImage::byteCount () const
Definition at line 136 of file qvolatileimage.cpp.
 {
     return d->image.byteCount();
 }
bytesPerLine()
int QVolatileImage::bytesPerLine () const
Definition at line 131 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::ensureReadback(), and QVGPixmapData::toVGImage().
 {
     return d->image.bytesPerLine();
 }
constBits()
const uchar * QVolatileImage::constBits () const
Definition at line 170 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::toVGImage().
 {
     return d->image.constBits();
 }
constImageRef()
const QImage & QVolatileImage::constImageRef () const
Non-detaching version, for read-only access only.
Must be guarded by begin/endDataAccess().
Definition at line 207 of file qvolatileimage.cpp.
Referenced by QVolatileImagePaintEngine::drawPixmap().
 {
     const_cast<QVolatileImageData *>(d.data())->ensureImage();
     return d->image;
 }
copyFrom()
void QVolatileImage::copyFrom (QVolatileImage * source, const QRect & rect)
Definition at line 235 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::copy().
 {
     if (source->isNull()) {
         return;
     }
     QRect r = rect;
     if (rect.isNull()) {
         r = QRect(0, 0, source->width(), source->height());
     }
     source->beginDataAccess();
     QImage &srcImgRef(source->imageRef());
     int srcbpl = srcImgRef.bytesPerLine();
     int srcbpp = srcImgRef.depth() / 8;
     const uchar *sptr = srcImgRef.constBits() + r.y() * srcbpl;
     beginDataAccess();
     QImage &dstImgRef(imageRef());
     if (!dstImgRef.isNull()) {
         int dstbpl = dstImgRef.bytesPerLine();
         uchar *dptr = dstImgRef.bits();
         for (int y = 0; y < r.height(); ++y) {
             qMemCopy(dptr, sptr + r.x() * srcbpp, r.width() * srcbpp);
             sptr += srcbpl;
             dptr += dstbpl;
         }
     }
     endDataAccess();
     source->endDataAccess(true);
 }
depth()
int QVolatileImage::depth () const
Definition at line 141 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::fill().
 {
     return d->image.depth();
 }
duplicateNativeImage()
void * QVolatileImage::duplicateNativeImage () const
Definition at line 213 of file qvolatileimage.cpp.
 {
     return d->duplicateNativeImage();
 }
endDataAccess()
void QVolatileImage::endDataAccess (bool readOnly = false) const
Definition at line 156 of file qvolatileimage.cpp.
Referenced by copyFrom(), QVolatileImagePaintEngine::drawPixmap(), QVGPaintEngine::drawPixmap(), QVGPixmapData::ensureReadback(), fill(), setAlphaChannel(), and QVGPixmapData::toVGImage().
 {
     d->endDataAccess(readOnly);
 }
ensureFormat()
bool QVolatileImage::ensureFormat (QImage::Format format)
Definition at line 175 of file qvolatileimage.cpp.
Referenced by setAlphaChannel().
 {
     return d->ensureFormat(format);
 }
fill()
void QVolatileImage::fill (uint pixelValue)
Definition at line 227 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::fill().
 {
     beginDataAccess();
     imageRef().fill(pixelValue);
     endDataAccess();
     d->ensureImage();
 }
format()
QImage::Format QVolatileImage::format () const
Definition at line 116 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::copy(), QVGPixmapData::ensureReadback(), and QVGPixmapData::toVGImage().
 {
     return d->image.format();
 }
hasAlphaChannel()
bool QVolatileImage::hasAlphaChannel () const
Definition at line 146 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::hasAlphaChannel().
 {
     return d->image.hasAlphaChannel();
 }
height()
int QVolatileImage::height () const
Definition at line 126 of file qvolatileimage.cpp.
Referenced by copyFrom().
 {
     return d->image.height();
 }
imageRef()
QImage & QVolatileImage::imageRef ()
Returns a reference to the image that is potentially using some native buffer internally.
Access to the image's pixel data should be guarded by begin/endDataAccess(). Use it when there is a need for QImage APIs not provided by this class. The returned QImage must never be shared or assigned to.
Definition at line 197 of file qvolatileimage.cpp.
Referenced by copyFrom(), QVGPaintEngine::drawPixmap(), fill(), QVGPixmapData::fill(), paintEngine(), and setAlphaChannel().
 {
     d->ensureImage();
     return d->image;
 }
isNull()
bool QVolatileImage::isNull () const
Definition at line 111 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::copy(), copyFrom(), QVolatileImagePaintEngine::drawPixmap(), QVGPixmapData::ensureReadback(), QVGPixmapData::forceToImage(), QVGPixmapData::hasAlphaChannel(), QVGPixmapData::hibernate(), QVGPixmapData::toImage(), and QVGPixmapData::toVGImage().
 {
     return d->image.isNull();
 }
operator=()
QVolatileImage & QVolatileImage::operator= (const QVolatileImage & rhs)
Definition at line 100 of file qvolatileimage.cpp.
 {
     d = rhs.d;
     return *this;
 }
paintEngine()
QPaintEngine * QVolatileImage::paintEngine ()
To be called from the PixmapData's paintEngine().
Definition at line 267 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::paintEngine().
 {
     if (!d->pengine) {
         d->pengine = new QVolatileImagePaintEngine(&imageRef(), this);
     }
     return d->pengine;
 }
paintingActive()
bool QVolatileImage::paintingActive () const
Definition at line 106 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::toVGImage().
 {
     return d->pengine && d->pengine->isActive();
 }
setAlphaChannel()
void QVolatileImage::setAlphaChannel (const QPixmap & alphaChannel)
Definition at line 218 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::setAlphaChannel().
 {
     ensureFormat(QImage::Format_ARGB32_Premultiplied);
     beginDataAccess();
     imageRef().setAlphaChannel(alphaChannel.toImage());
     endDataAccess();
     d->ensureImage();
 }
toImage()
QImage QVolatileImage::toImage () const
This will always perform a copy of the pixel data.
Definition at line 183 of file qvolatileimage.cpp.
Referenced by QVGPixmapData::toImage().
 {
     d->beginDataAccess();
     QImage newImage = d->image.copy(); // no sharing allowed
     d->endDataAccess(true);
     return newImage;
 }
width()
int QVolatileImage::width () const
Definition at line 121 of file qvolatileimage.cpp.
Referenced by copyFrom().
 {
     return d->image.width();
 }
Properties
d
QSharedDataPointer<QVolatileImageData> QVolatileImage::d private
Definition at line 98 of file qvolatileimage_p.h.
Referenced by beginDataAccess(), bits(), byteCount(), bytesPerLine(), constBits(), constImageRef(), depth(), duplicateNativeImage(), endDataAccess(), ensureFormat(), fill(), format(), hasAlphaChannel(), height(), imageRef(), isNull(), operator=(), paintEngine(), paintingActive(), setAlphaChannel(), toImage(), and width().
The documentation for this class was generated from the following files:
/src/gui/image/qvolatileimage_p.h
/src/gui/image/qvolatileimage.cpp