Qt 4.8: QBBVirtualKeyboardPps Class Reference
QBBVirtualKeyboardPps Class Reference
#include <qbbvirtualkeyboardpps.h>
Public Slots
void start ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
bool hideKeyboard ()
QBBVirtualKeyboardPps ()
bool showKeyboard ()
~QBBVirtualKeyboardPps ()
Public Functions inherited from QBBAbstractVirtualKeyboard
QString countryId () const
int getHeight () const
bool isVisible () const
KeyboardMode keyboardMode () const
QString languageId () const
QBBAbstractVirtualKeyboard (QObject *parent=0)
void setInputHintsFromWidget (QWidget *focusWidget)
void setKeyboardMode (KeyboardMode mode)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void applyKeyboardMode (KeyboardMode mode)
Protected Functions inherited from QBBAbstractVirtualKeyboard
void setCountry (const QString &country)
void setHeight (int height)
void setLanguage (const QString &language)
void setVisible (bool visible)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void ppsDataReady ()
Private Functions
void addDefaultModeOptions ()
void addEmailModeOptions ()
void addNumPuncModeOptions ()
void addPhoneModeOptions ()
void addPinModeOptions ()
void addSymbolModeOptions ()
void addUrlModeOptions ()
void addWebModeOptions ()
void applyKeyboardModeOptions (KeyboardMode mode)
void close ()
bool connect ()
void handleKeyboardInfoMessage ()
bool queryPPSInfo ()
Properties
char * mBuffer
pps_decoder_t * mDecoder
pps_encoder_t * mEncoder
int mFd
QSocketNotifier * mReadNotifier
Static Private Attributes
static const size_t sBufferSize = 2048
static const char * sPPSPath = "/pps/services/input/control"
Additional Inherited Members
Public Types inherited from QBBAbstractVirtualKeyboard
enum KeyboardMode {
Default, Url, Email, Web,
NumPunc, Symbol, Phone, Pin
}
Signals inherited from QBBAbstractVirtualKeyboard
void heightChanged (int height)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 54 of file qbbvirtualkeyboardpps.h.
Constructors and Destructors
QBBVirtualKeyboardPps()
QBBVirtualKeyboardPps::QBBVirtualKeyboardPps ()
Definition at line 72 of file qbbvirtualkeyboardpps.cpp.
     : mEncoder(0),
       mDecoder(0),
       mBuffer(0),
       mFd(-1),
       mReadNotifier(0)
 {
 }
~QBBVirtualKeyboardPps()
QBBVirtualKeyboardPps::~QBBVirtualKeyboardPps ()
Definition at line 81 of file qbbvirtualkeyboardpps.cpp.
 {
     close();
 }
Functions
addDefaultModeOptions()
void QBBVirtualKeyboardPps::addDefaultModeOptions () private
Definition at line 382 of file qbbvirtualkeyboardpps.cpp.
Referenced by applyKeyboardModeOptions().
 {
     pps_encoder_add_string(mEncoder, "enter", "enter.default");
     pps_encoder_add_string(mEncoder, "type", "default");
 }
addEmailModeOptions()
void QBBVirtualKeyboardPps::addEmailModeOptions () private
Definition at line 394 of file qbbvirtualkeyboardpps.cpp.
Referenced by applyKeyboardModeOptions().
 {
     pps_encoder_add_string(mEncoder, "enter", "enter.default");
     pps_encoder_add_string(mEncoder, "type", "email");
 }
addNumPuncModeOptions()
void QBBVirtualKeyboardPps::addNumPuncModeOptions () private
Definition at line 406 of file qbbvirtualkeyboardpps.cpp.
Referenced by applyKeyboardModeOptions().
 {
     pps_encoder_add_string(mEncoder, "enter", "enter.default");
     pps_encoder_add_string(mEncoder, "type", "numPunc");
 }
addPhoneModeOptions()
void QBBVirtualKeyboardPps::addPhoneModeOptions () private
Definition at line 412 of file qbbvirtualkeyboardpps.cpp.
Referenced by applyKeyboardModeOptions().
 {
     pps_encoder_add_string(mEncoder, "enter", "enter.default");
     pps_encoder_add_string(mEncoder, "type", "phone");
 }
addPinModeOptions()
void QBBVirtualKeyboardPps::addPinModeOptions () private
Definition at line 418 of file qbbvirtualkeyboardpps.cpp.
Referenced by applyKeyboardModeOptions().
 {
     pps_encoder_add_string(mEncoder, "enter", "enter.default");
     pps_encoder_add_string(mEncoder, "type", "pin");
 }
addSymbolModeOptions()
void QBBVirtualKeyboardPps::addSymbolModeOptions () private
Definition at line 424 of file qbbvirtualkeyboardpps.cpp.
Referenced by applyKeyboardModeOptions().
 {
     pps_encoder_add_string(mEncoder, "enter", "enter.default");
     pps_encoder_add_string(mEncoder, "type", "symbol");
 }
addUrlModeOptions()
void QBBVirtualKeyboardPps::addUrlModeOptions () private
Definition at line 388 of file qbbvirtualkeyboardpps.cpp.
Referenced by applyKeyboardModeOptions().
 {
     pps_encoder_add_string(mEncoder, "enter", "enter.default");
     pps_encoder_add_string(mEncoder, "type", "url");
 }
addWebModeOptions()
void QBBVirtualKeyboardPps::addWebModeOptions () private
Definition at line 400 of file qbbvirtualkeyboardpps.cpp.
Referenced by applyKeyboardModeOptions().
 {
     pps_encoder_add_string(mEncoder, "enter", "enter.default");
     pps_encoder_add_string(mEncoder, "type", "web");
 }
applyKeyboardMode()
void QBBVirtualKeyboardPps::applyKeyboardMode (KeyboardMode mode) protected virtual
Implements QBBAbstractVirtualKeyboard.
Definition at line 96 of file qbbvirtualkeyboardpps.cpp.
 {
     applyKeyboardModeOptions(mode);
 }
applyKeyboardModeOptions()
void QBBVirtualKeyboardPps::applyKeyboardModeOptions (KeyboardMode mode) private
Definition at line 336 of file qbbvirtualkeyboardpps.cpp.
Referenced by applyKeyboardMode(), and showKeyboard().
 {
     // Try to connect.
     if (mFd == -1 && !connect())
         return;
     // Send the options message.
     pps_encoder_add_string(mEncoder, "msg", "options");
     pps_encoder_start_object(mEncoder, "dat");
     switch (mode) {
     case Url:
         addUrlModeOptions();
         break;
     case Email:
         addEmailModeOptions();
         break;
     case Web:
         addWebModeOptions();
         break;
     case NumPunc:
         addNumPuncModeOptions();
         break;
     case Symbol:
         addSymbolModeOptions();
         break;
     case Phone:
         addPhoneModeOptions();
         break;
     case Pin:
         addPinModeOptions();
         break;
     case Default: // fall through
     default:
         addDefaultModeOptions();
         break;
     }
     pps_encoder_end_object(mEncoder);
     if (::write(mFd, pps_encoder_buffer(mEncoder), pps_encoder_length(mEncoder)) == -1)
         close();
     pps_encoder_reset(mEncoder);
 }
close()
void QBBVirtualKeyboardPps::close () private
Definition at line 101 of file qbbvirtualkeyboardpps.cpp.
Referenced by applyKeyboardModeOptions(), connect(), hideKeyboard(), queryPPSInfo(), showKeyboard(), and ~QBBVirtualKeyboardPps().
 {
     delete mReadNotifier;
     mReadNotifier = 0;
     if (mFd != -1) {
         // any reads will fail after we close the fd, which is basically what we want.
         ::close(mFd);
         mFd = -1;
     }
     if (mDecoder) {
         pps_decoder_cleanup(mDecoder);
         delete mDecoder;
         mDecoder = 0;
     }
     if (mEncoder) {
         pps_encoder_cleanup(mEncoder);
         delete mEncoder;
         mEncoder = 0;
     }
     delete [] mBuffer;
     mBuffer = 0;
 }
connect()
bool QBBVirtualKeyboardPps::connect () private
Definition at line 128 of file qbbvirtualkeyboardpps.cpp.
Referenced by applyKeyboardModeOptions(), hideKeyboard(), ppsDataReady(), showKeyboard(), and start().
 {
     close();
     mEncoder = new pps_encoder_t;
     mDecoder = new pps_decoder_t;
     pps_encoder_initialize(mEncoder, false);
     pps_decoder_initialize(mDecoder, NULL);
     errno = 0;
     mFd = ::open(sPPSPath, O_RDWR);
     if (mFd == -1) {
         qCritical("QBBVirtualKeyboard: Unable to open \"%s\" for keyboard: %s (%d).",
                 sPPSPath, strerror(errno), errno);
         close();
         return false;
     }
     mBuffer = new char[sBufferSize];
     if (!mBuffer) {
         qCritical("QBBVirtualKeyboard: Unable to allocate buffer of %d bytes. Size is unavailable.",  sBufferSize);
         return false;
     }
     if (!queryPPSInfo())
         return false;
     mReadNotifier = new QSocketNotifier(mFd, QSocketNotifier::Read);
     QObject::connect(mReadNotifier, SIGNAL(activated(int)), this, SLOT(ppsDataReady()));
     return true;
 }
handleKeyboardInfoMessage()
void QBBVirtualKeyboardPps::handleKeyboardInfoMessage () private
Definition at line 235 of file qbbvirtualkeyboardpps.cpp.
Referenced by ppsDataReady().
 {
     int newHeight = 0;
     const char* value;
     if (pps_decoder_push(mDecoder, "dat") != PPS_DECODER_OK) {
         qCritical("QBBVirtualKeyboard: Keyboard PPS dat object not found");
         return;
     }
     if (pps_decoder_get_int(mDecoder, "size", &newHeight) != PPS_DECODER_OK) {
         qCritical("QBBVirtualKeyboard: Keyboard PPS size field not found");
         return;
     }
     if (pps_decoder_push(mDecoder, "locale") != PPS_DECODER_OK) {
         qCritical("QBBVirtualKeyboard: Keyboard PPS locale object not found");
         return;
     }
     if (pps_decoder_get_string(mDecoder, "languageId", &value) != PPS_DECODER_OK) {
         qCritical("QBBVirtualKeyboard: Keyboard PPS languageId field not found");
         return;
     }
     setLanguage(QString::fromLatin1(value));
     if (pps_decoder_get_string(mDecoder, "countryId", &value) != PPS_DECODER_OK) {
         qCritical("QBBVirtualKeyboard: Keyboard PPS size countryId not found");
         return;
     }
     setCountry(QString::fromLatin1(value));
     // HUGE hack, should be removed ASAP.
     newHeight -= KEYBOARD_SHADOW_HEIGHT; // We want to ignore the 8 pixel shadow above the keyboard. (PR 88400)
     setHeight(newHeight);
 #ifdef QBBVIRTUALKEYBOARD_DEBUG
     qDebug() << "QBB: handleKeyboardInfoMessage size=" << getHeight() << "languageId=" << languageId() << " countryId=" << countryId();
 #endif
 }
hideKeyboard()
bool QBBVirtualKeyboardPps::hideKeyboard () virtual
Implements QBBAbstractVirtualKeyboard.
Definition at line 304 of file qbbvirtualkeyboardpps.cpp.
 {
 #ifdef QBBVIRTUALKEYBOARD_DEBUG
     qDebug() << "QBB: hideKeyboard()";
 #endif
     if (mFd == -1 && !connect())
         return false;
     pps_encoder_add_string(mEncoder, "msg", "hide");
     if (::write(mFd, pps_encoder_buffer(mEncoder), pps_encoder_length(mEncoder)) == -1) {
         close();
         //Try again.
         if (connect()) {
             if (::write(mFd, pps_encoder_buffer(mEncoder), pps_encoder_length(mEncoder)) == -1) {
                 close();
                 return false;
             }
         } else {
             return false;
         }
     }
     pps_encoder_reset(mEncoder);
     // Return true if no error occurs.  Sizing response will be triggered when confirmation of
     // the change arrives.
     return true;
 }
ppsDataReady
void QBBVirtualKeyboardPps::ppsDataReady () private slot
Definition at line 178 of file qbbvirtualkeyboardpps.cpp.
Referenced by connect().
 {
     ssize_t nread = qt_safe_read(mFd, mBuffer, sBufferSize - 1);
 #ifdef QBBVIRTUALKEYBOARD_DEBUG
     qDebug() << "QBB: keyboardMessage size: " << nread;
 #endif
     if (nread < 0) {
         connect(); // reconnect
         return;
     }
     // We sometimes get spurious read notifications when no data is available.
     // Bail out early in this case
     if (nread == 0)
         return;
     // nread is the real space necessary, not the amount read.
     if (static_cast<size_t>(nread) > sBufferSize - 1) {
         qCritical("QBBVirtualKeyboard: Keyboard buffer size too short; need %u.", nread + 1);
         connect(); // reconnect
         return;
     }
     mBuffer[nread] = 0;
     pps_decoder_parse_pps_str(mDecoder, mBuffer);
     pps_decoder_push(mDecoder, NULL);
 #ifdef QBBVIRTUALKEYBOARD_DEBUG
     pps_decoder_dump_tree(mDecoder, stderr);
 #endif
     const char* value;
     if (pps_decoder_get_string(mDecoder, "error", &value) == PPS_DECODER_OK) {
         qCritical("QBBVirtualKeyboard: Keyboard PPS decoder error: %s", value ? value : "[null]");
         return;
     }
     if (pps_decoder_get_string(mDecoder, "msg", &value) == PPS_DECODER_OK) {
         if (strcmp(value, "show") == 0)
             setVisible(true);
         else if (strcmp(value, "hide") == 0)
             setVisible(false);
         else if (strcmp(value, "info") == 0)
             handleKeyboardInfoMessage();
         else if (strcmp(value, "connect") == 0) { }
         else
             qCritical("QBBVirtualKeyboard: Unexpected keyboard PPS msg value: %s", value ? value : "[null]");
     } else if (pps_decoder_get_string(mDecoder, "res", &value) == PPS_DECODER_OK) {
         if (strcmp(value, "info") == 0)
             handleKeyboardInfoMessage();
         else
             qCritical("QBBVirtualKeyboard: Unexpected keyboard PPS res value: %s", value ? value : "[null]");
     } else {
         qCritical("QBBVirtualKeyboard: Unexpected keyboard PPS message type");
     }
 }
queryPPSInfo()
bool QBBVirtualKeyboardPps::queryPPSInfo () private
Definition at line 162 of file qbbvirtualkeyboardpps.cpp.
Referenced by connect().
 {
     // Request info, requires id to regenerate res message.
     pps_encoder_add_string(mEncoder, "msg", "info");
     pps_encoder_add_string(mEncoder, "id", "libWebView");
     if (::write(mFd, pps_encoder_buffer(mEncoder), pps_encoder_length(mEncoder)) == -1) {
         close();
         return false;
     }
     pps_encoder_reset(mEncoder);
     return true;
 }
showKeyboard()
bool QBBVirtualKeyboardPps::showKeyboard () virtual
Implements QBBAbstractVirtualKeyboard.
Definition at line 273 of file qbbvirtualkeyboardpps.cpp.
 {
 #ifdef QBBVIRTUALKEYBOARD_DEBUG
     qDebug() << "QBB: showKeyboard()";
 #endif
     // Try to connect.
     if (mFd == -1 && !connect())
         return false;
     // NOTE:  This must be done everytime the keyboard is shown even if there is no change because
     // hiding the keyboard wipes the setting.
     applyKeyboardModeOptions(keyboardMode());
     pps_encoder_reset(mEncoder);
     // Send the show message.
     pps_encoder_add_string(mEncoder, "msg", "show");
     if (::write(mFd, pps_encoder_buffer(mEncoder), pps_encoder_length(mEncoder)) == -1) {
         close();
         return false;
     }
     pps_encoder_reset(mEncoder);
     // Return true if no error occurs.  Sizing response will be triggered when confirmation of
     // the change arrives.
     return true;
 }
start
void QBBVirtualKeyboardPps::start () slot
Definition at line 86 of file qbbvirtualkeyboardpps.cpp.
 {
 #ifdef QBBVIRTUALKEYBOARD_DEBUG
     qDebug() << "QBB: starting keyboard event processing";
 #endif
     if (!connect())
         return;
 }
Properties
mBuffer
char* QBBVirtualKeyboardPps::mBuffer private
Definition at line 76 of file qbbvirtualkeyboardpps.h.
Referenced by close(), connect(), and ppsDataReady().
mDecoder
pps_decoder_t* QBBVirtualKeyboardPps::mDecoder private
Definition at line 75 of file qbbvirtualkeyboardpps.h.
Referenced by close(), connect(), handleKeyboardInfoMessage(), and ppsDataReady().
mEncoder
pps_encoder_t* QBBVirtualKeyboardPps::mEncoder private
Definition at line 74 of file qbbvirtualkeyboardpps.h.
Referenced by addDefaultModeOptions(), addEmailModeOptions(), addNumPuncModeOptions(), addPhoneModeOptions(), addPinModeOptions(), addSymbolModeOptions(), addUrlModeOptions(), addWebModeOptions(), applyKeyboardModeOptions(), close(), connect(), hideKeyboard(), queryPPSInfo(), and showKeyboard().
mFd
int QBBVirtualKeyboardPps::mFd private
Definition at line 77 of file qbbvirtualkeyboardpps.h.
Referenced by applyKeyboardModeOptions(), close(), connect(), hideKeyboard(), ppsDataReady(), queryPPSInfo(), and showKeyboard().
mReadNotifier
QSocketNotifier* QBBVirtualKeyboardPps::mReadNotifier private
Definition at line 78 of file qbbvirtualkeyboardpps.h.
Referenced by close(), and connect().
sBufferSize
const size_t QBBVirtualKeyboardPps::sBufferSize = 2048 static private
Definition at line 82 of file qbbvirtualkeyboardpps.h.
Referenced by connect(), and ppsDataReady().
sPPSPath
const char * QBBVirtualKeyboardPps::sPPSPath = "/pps/services/input/control" static private
Definition at line 81 of file qbbvirtualkeyboardpps.h.
Referenced by connect().
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbvirtualkeyboardpps.h
/src/plugins/platforms/blackberry/qbbvirtualkeyboardpps.cpp