Qt 4.8: QAbstractSocket Class Reference
QAbstractSocket Class Reference
The QAbstractSocket class provides the base functionality common to all socket types.
#include <qabstractsocket.h>
Public Types
enum NetworkLayerProtocol { IPv4Protocol, IPv6Protocol, UnknownNetworkLayerProtocol = -1 }
This enum describes the network layer protocol values used in Qt.
enum SocketError {
ConnectionRefusedError, RemoteHostClosedError, HostNotFoundError, SocketAccessError,
SocketResourceError, SocketTimeoutError, DatagramTooLargeError, NetworkError,
AddressInUseError, SocketAddressNotAvailableError, UnsupportedSocketOperationError, UnfinishedSocketOperationError,
ProxyAuthenticationRequiredError, SslHandshakeFailedError, ProxyConnectionRefusedError, ProxyConnectionClosedError,
ProxyConnectionTimeoutError, ProxyNotFoundError, ProxyProtocolError, UnknownSocketError = -1
}
This enum describes the socket errors that can occur.
enum SocketOption { LowDelayOption, KeepAliveOption, MulticastTtlOption, MulticastLoopbackOption }
This enum represents the options that can be set on a socket.
enum SocketState {
UnconnectedState, HostLookupState, ConnectingState, ConnectedState,
BoundState, ListeningState, ClosingState
}
This enum describes the different states in which a socket can be.
enum SocketType { TcpSocket, UdpSocket, UnknownSocketType = -1 }
This enum describes the transport layer protocol.
Public Types inherited from QIODevice
enum OpenModeFlag {
NotOpen = 0x0000, ReadOnly = 0x0001, WriteOnly = 0x0002, ReadWrite = ReadOnly | WriteOnly,
Append = 0x0004, Truncate = 0x0008, Text = 0x0010, Unbuffered = 0x0020
}
This enum is used with open() to describe the mode in which a device is opened.
Signals
void connected ()
This signal is emitted after connectToHost() has been called and a connection has been successfully established.
void disconnected ()
This signal is emitted when the socket has been disconnected.
void error (QAbstractSocket::SocketError)
This signal is emitted after an error occurred.
void hostFound ()
This signal is emitted after connectToHost() has been called and the host lookup has succeeded.
void proxyAuthenticationRequired (const QNetworkProxy &proxy, QAuthenticator *authenticator)
void stateChanged (QAbstractSocket::SocketState)
This signal is emitted whenever QAbstractSocket's state changes.
Signals inherited from QIODevice
void aboutToClose ()
This signal is emitted when the device is about to close.
void bytesWritten (qint64 bytes)
This signal is emitted every time a payload of data has been written to the device.
void readChannelFinished ()
This signal is emitted when the input (reading) stream is closed in this device.
void readyRead ()
This signal is emitted once every time new data is available for reading from the device.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void abort ()
Aborts the current connection and resets the socket.
bool atEnd () const
Returns true if no more data is currently available for reading; otherwise returns false.
qint64 bytesAvailable () const
Returns the number of incoming bytes that are waiting to be read.
qint64 bytesToWrite () const
Returns the number of bytes that are waiting to be written.
bool canReadLine () const
Returns true if a line of data can be read from the socket; otherwise returns false.
void close ()
Closes the I/O device for the socket, disconnects the socket's connection with the host, closes the socket, and resets the name, address, port number and underlying socket descriptor.
void connectToHost (const QString &hostName, quint16 port, OpenMode mode=ReadWrite)
Attempts to make a connection to hostName on the given port.
void connectToHost (const QHostAddress &address, quint16 port, OpenMode mode=ReadWrite)
Attempts to make a connection to address on port port.
void disconnectFromHost ()
Attempts to close the socket.
SocketError error () const
Returns the type of error that last occurred.
bool flush ()
This function writes as much as possible from the internal write buffer to the underlying network socket, without blocking.
bool isSequential () const
Reimplemented Function
bool isValid () const
Returns true if the socket is valid and ready for use; otherwise returns false.
QHostAddress localAddress () const
Returns the host address of the local socket if available; otherwise returns QHostAddress::Null.
quint16 localPort () const
Returns the host port number (in native byte order) of the local socket if available; otherwise returns 0.
QHostAddress peerAddress () const
Returns the address of the connected peer if the socket is in ConnectedState; otherwise returns QHostAddress::Null.
QString peerName () const
Returns the name of the peer as specified by connectToHost(), or an empty QString if connectToHost() has not been called.
quint16 peerPort () const
Returns the port of the connected peer if the socket is in ConnectedState; otherwise returns 0.
QNetworkProxy proxy () const
Returns the network proxy for this socket.
QAbstractSocket (SocketType socketType, QObject *parent)
Creates a new abstract socket of type socketType.
qint64 readBufferSize () const
Returns the size of the internal read buffer.
void setProxy (const QNetworkProxy &networkProxy)
Sets the explicit network proxy for this socket to networkProxy.
void setReadBufferSize (qint64 size)
Sets the size of QAbstractSocket's internal read buffer to be size bytes.
bool setSocketDescriptor (int socketDescriptor, SocketState state=ConnectedState, OpenMode openMode=ReadWrite)
Initializes QAbstractSocket with the native socket descriptor socketDescriptor.
void setSocketOption (QAbstractSocket::SocketOption option, const QVariant &value)
Sets the given option to the value described by value.
int socketDescriptor () const
Returns the native socket descriptor of the QAbstractSocket object if this is available; otherwise returns -1.
QVariant socketOption (QAbstractSocket::SocketOption option)
Returns the value of the option option.
SocketType socketType () const
Returns the socket type (TCP, UDP, or other).
SocketState state () const
Returns the state of the socket.
bool waitForBytesWritten (int msecs=30000)
Reimplemented Function
bool waitForConnected (int msecs=30000)
Waits until the socket is connected, up to msecs milliseconds.
bool waitForDisconnected (int msecs=30000)
Waits until the socket has disconnected, up to msecs milliseconds.
bool waitForReadyRead (int msecs=30000)
This function blocks until new data is available for reading and the QIODevice::readyRead() signal has been emitted.
virtual ~QAbstractSocket ()
Destroys the socket.
Public Functions inherited from QIODevice
QString errorString () const
Returns a human-readable description of the last device error that occurred.
bool getChar (char *c)
Reads one character from the device and stores it in c.
bool isOpen () const
Returns true if the device is open; otherwise returns false.
bool isReadable () const
Returns true if data can be read from the device; otherwise returns false.
bool isTextModeEnabled () const
Returns true if the Text flag is enabled; otherwise returns false.
bool isWritable () const
Returns true if data can be written to the device; otherwise returns false.
virtual bool open (OpenMode mode)
Opens the device and sets its OpenMode to mode.
OpenMode openMode () const
Returns the mode in which the device has been opened; i.e.
qint64 peek (char *data, qint64 maxlen)
Reads at most maxSize bytes from the device into data, without side effects (i.
QByteArray peek (qint64 maxlen)
Peeks at most maxSize bytes from the device, returning the data peeked as a QByteArray.
virtual qint64 pos () const
For random-access devices, this function returns the position that data is written to or read from.
bool putChar (char c)
Writes the character c to the device.
QIODevice ()
Constructs a QIODevice object.
QIODevice (QObject *parent)
Constructs a QIODevice object with the given parent.
qint64 read (char *data, qint64 maxlen)
Reads at most maxSize bytes from the device into data, and returns the number of bytes read.
QByteArray read (qint64 maxlen)
Reads at most maxSize bytes from the device, and returns the data read as a QByteArray.
QByteArray readAll ()
Reads all available data from the device, and returns it as a QByteArray.
qint64 readLine (char *data, qint64 maxlen)
This function reads a line of ASCII characters from the device, up to a maximum of maxSize - 1 bytes, stores the characters in data, and returns the number of bytes read.
QByteArray readLine (qint64 maxlen=0)
Reads a line from the device, but no more than maxSize characters, and returns the result as a QByteArray.
virtual bool reset ()
Seeks to the start of input for random-access devices.
virtual bool seek (qint64 pos)
For random-access devices, this function sets the current position to pos, returning true on success, or false if an error occurred.
void setTextModeEnabled (bool enabled)
If enabled is true, this function sets the Text flag on the device; otherwise the Text flag is removed.
virtual qint64 size () const
For open random-access devices, this function returns the size of the device.
void ungetChar (char c)
Puts the character c back into the device, and decrements the current position unless the position is 0.
qint64 write (const char *data, qint64 len)
Writes at most maxSize bytes of data from data to the device.
qint64 write (const char *data)
Writes data from a zero-terminated string of 8-bit characters to the device.
qint64 write (const QByteArray &data)
Writes the content of byteArray to the device.
virtual ~QIODevice ()
The destructor is virtual, and QIODevice is an abstract base class.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Slots
void connectToHostImplementation (const QString &hostName, quint16 port, OpenMode mode=ReadWrite)
Contains the implementation of connectToHost().
void disconnectFromHostImplementation ()
Contains the implementation of disconnectFromHost().
Protected Functions
QAbstractSocket (SocketType socketType, QAbstractSocketPrivate &dd, QObject *parent=0)
Constructs a new abstract socket of type socketType.
qint64 readData (char *data, qint64 maxlen)
Reimplemented Function
qint64 readLineData (char *data, qint64 maxlen)
Reimplemented Function
void setLocalAddress (const QHostAddress &address)
Sets the address on the local side of a connection to address.
void setLocalPort (quint16 port)
Sets the port on the local side of a connection to port.
void setPeerAddress (const QHostAddress &address)
Sets the address of the remote side of the connection to address.
void setPeerName (const QString &name)
Sets the host name of the remote peer to name.
void setPeerPort (quint16 port)
Sets the port of the remote side of the connection to port.
void setSocketError (SocketError socketError)
Sets the type of error that last occurred to socketError.
void setSocketState (SocketState state)
Sets the state of the socket to state.
qint64 writeData (const char *data, qint64 len)
Reimplemented Function
Protected Functions inherited from QIODevice
QIODevice (QIODevicePrivate &dd, QObject *parent=0)
void setErrorString (const QString &errorString)
Sets the human readable description of the last device error that occurred to str.
void setOpenMode (OpenMode openMode)
Sets the OpenMode of the device to openMode.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAbstractSocket class provides the base functionality common to all socket types.
Note
This class or function is reentrant.
Attention
Module: QtNetwork
QAbstractSocket is the base class for QTcpSocket and QUdpSocket and contains all common functionality of these two classes. If you need a socket, you have two options:
Instantiate QTcpSocket or QUdpSocket.
Create a native socket descriptor, instantiate QAbstractSocket, and call setSocketDescriptor() to wrap the native socket.
TCP (Transmission Control Protocol) is a reliable, stream-oriented, connection-oriented transport protocol. UDP (User Datagram Protocol) is an unreliable, datagram-oriented, connectionless protocol. In practice, this means that TCP is better suited for continuous transmission of data, whereas the more lightweight UDP can be used when reliability isn't important.
QAbstractSocket's API unifies most of the differences between the two protocols. For example, although UDP is connectionless, connectToHost() establishes a virtual connection for UDP sockets, enabling you to use QAbstractSocket in more or less the same way regardless of the underlying protocol. Internally, QAbstractSocket remembers the address and port passed to connectToHost(), and functions like read() and write() use these values.
At any time, QAbstractSocket has a state (returned by state()). The initial state is UnconnectedState. After calling connectToHost(), the socket first enters HostLookupState. If the host is found, QAbstractSocket enters ConnectingState and emits the hostFound() signal. When the connection has been established, it enters ConnectedState and emits connected(). If an error occurs at any stage, error() is emitted. Whenever the state changes, stateChanged() is emitted. For convenience, isValid() returns true if the socket is ready for reading and writing, but note that the socket's state must be ConnectedState before reading and writing can occur.
Read or write data by calling read() or write(), or use the convenience functions readLine() and readAll(). QAbstractSocket also inherits getChar(), putChar(), and ungetChar() from QIODevice, which work on single bytes. The bytesWritten() signal is emitted when data has been written to the socket (i.e., when the client has read the data). Note that Qt does not limit the write buffer size. You can monitor its size by listening to this signal.
The readyRead() signal is emitted every time a new chunk of data has arrived. bytesAvailable() then returns the number of bytes that are available for reading. Typically, you would connect the readyRead() signal to a slot and read all available data there. If you don't read all the data at once, the remaining data will still be available later, and any new incoming data will be appended to QAbstractSocket's internal read buffer. To limit the size of the read buffer, call setReadBufferSize().
To close the socket, call disconnectFromHost(). QAbstractSocket enters QAbstractSocket::ClosingState. After all pending data has been written to the socket, QAbstractSocket actually closes the socket, enters QAbstractSocket::ClosedState, and emits disconnected(). If you want to abort a connection immediately, discarding all pending data, call abort() instead. If the remote host closes the connection, QAbstractSocket will emit error(QAbstractSocket::RemoteHostClosedError), during which the socket state will still be ConnectedState, and then the disconnected() signal will be emitted.
The port and address of the connected peer is fetched by calling peerPort() and peerAddress(). peerName() returns the host name of the peer, as passed to connectToHost(). localPort() and localAddress() return the port and address of the local socket.
QAbstractSocket provides a set of functions that suspend the calling thread until certain signals are emitted. These functions can be used to implement blocking sockets:
waitForConnected() blocks until a connection has been established.
waitForReadyRead() blocks until new data is available for reading.
waitForBytesWritten() blocks until one payload of data has been written to the socket.
waitForDisconnected() blocks until the connection has closed.
We show an example:
    int numRead = 0, numReadTotal = 0;
    char buffer[50];
    forever {
    numRead  = socket.read(buffer, 50);
    // do whatever with array
    numReadTotal += numRead;
    if (numRead == 0 && !socket.waitForReadyRead())
        break;
    }
If QIODevice::waitForReadyRead() returns false, the connection has been closed or an error has occurred.
Programming with a blocking socket is radically different from programming with a non-blocking socket. A blocking socket doesn't require an event loop and typically leads to simpler code. However, in a GUI application, blocking sockets should only be used in non-GUI threads, to avoid freezing the user interface. See the network/fortuneclient and network/blockingfortuneclient examples for an overview of both approaches.
Note
We discourage the use of the blocking functions together with signals. One of the two possibilities should be used.
QAbstractSocket can be used with QTextStream and QDataStream's stream operators (operator<<() and operator>>()). There is one issue to be aware of, though: You must make sure that enough data is available before attempting to read it using operator>>().
See also
QFtp, QNetworkAccessManager, QTcpServer
Definition at line 64 of file qabstractsocket.h.
Enumerations
NetworkLayerProtocol
enum QAbstractSocket::NetworkLayerProtocol
This enum describes the network layer protocol values used in Qt.
IPv4Protocol IPv4
IPv6Protocol IPv6
UnknownNetworkLayerProtocol Other than IPv4 and IPv6
See also
QHostAddress::protocol()
Enumerator
IPv4Protocol
IPv6Protocol
UnknownNetworkLayerProtocol
Definition at line 74 of file qabstractsocket.h.
{
         IPv4Protocol,
         IPv6Protocol,
         UnknownNetworkLayerProtocol = -1
     };
SocketError
enum QAbstractSocket::SocketError
This enum describes the socket errors that can occur.
ConnectionRefusedError The connection was refused by the peer (or timed out).
RemoteHostClosedError The remote host closed the connection. Note that the client socket (i.e., this socket) will be closed after the remote close notification has been sent.
HostNotFoundError The host address was not found.
SocketAccessError The socket operation failed because the application lacked the required privileges.
SocketResourceError The local system ran out of resources (e.g., too many sockets).
SocketTimeoutError The socket operation timed out.
DatagramTooLargeError The datagram was larger than the operating system's limit (which can be as low as 8192 bytes).
NetworkError An error occurred with the network (e.g., the network cable was accidentally plugged out).
AddressInUseError The address specified to QUdpSocket::bind() is already in use and was set to be exclusive.
SocketAddressNotAvailableError The address specified to QUdpSocket::bind() does not belong to the host.
UnsupportedSocketOperationError The requested socket operation is not supported by the local operating system (e.g., lack of IPv6 support).
ProxyAuthenticationRequiredError The socket is using a proxy, and the proxy requires authentication.
SslHandshakeFailedError The SSL/TLS handshake failed, so the connection was closed (only used in QSslSocket) (This value was introduced in 4.4.)
UnfinishedSocketOperationError Used by QAbstractSocketEngine only, The last operation attempted has not finished yet (still in progress in the background). (This value was introduced in 4.4.)
ProxyConnectionRefusedError Could not contact the proxy server because the connection to that server was denied (This value was introduced in 4.5.)
ProxyConnectionClosedError The connection to the proxy server was closed unexpectedly (before the connection to the final peer was established) (This value was introduced in 4.5.)
ProxyConnectionTimeoutError The connection to the proxy server timed out or the proxy server stopped responding in the authentication phase. (This value was introduced in 4.5.)
ProxyNotFoundError The proxy address set with setProxy() (or the application proxy) was not found. (This value was introduced in 4.5.)
ProxyProtocolError The connection negotiation with the proxy server because the response from the proxy server could not be understood. (This value was introduced in 4.5.)
UnknownSocketError An unidentified error occurred.
See also
QAbstractSocket::error()
Enumerator
ConnectionRefusedError
RemoteHostClosedError
HostNotFoundError
SocketAccessError
SocketResourceError
SocketTimeoutError
DatagramTooLargeError
NetworkError
AddressInUseError
SocketAddressNotAvailableError
UnsupportedSocketOperationError
UnfinishedSocketOperationError
ProxyAuthenticationRequiredError
SslHandshakeFailedError
ProxyConnectionRefusedError
ProxyConnectionClosedError
ProxyConnectionTimeoutError
ProxyNotFoundError
ProxyProtocolError
UnknownSocketError
Definition at line 79 of file qabstractsocket.h.
                      {
         ConnectionRefusedError,
         RemoteHostClosedError,
         HostNotFoundError,
         SocketAccessError,
         SocketResourceError,
         SocketTimeoutError,                     /* 5 */
         DatagramTooLargeError,
         NetworkError,
         AddressInUseError,
         SocketAddressNotAvailableError,
         UnsupportedSocketOperationError,        /* 10 */
         UnfinishedSocketOperationError,
         ProxyAuthenticationRequiredError,
         SslHandshakeFailedError,
         ProxyConnectionRefusedError,
         ProxyConnectionClosedError,             /* 15 */
         ProxyConnectionTimeoutError,
         ProxyNotFoundError,
         ProxyProtocolError,
         UnknownSocketError = -1
     };
SocketOption
enum QAbstractSocket::SocketOption
This enum represents the options that can be set on a socket.
Since
4.6
If desired, they can be set after having received the connected() signal from the socket or after having received a new socket from a QTcpServer.
LowDelayOption Try to optimize the socket for low latency. For a QTcpSocket this would set the TCP_NODELAY option and disable Nagle's algorithm. Set this to 1 to enable.
KeepAliveOption Set this to 1 to enable the SO_KEEPALIVE socket option
MulticastTtlOption Set this to an integer value to set IP_MULTICAST_TTL (TTL for multicast datagrams) socket option.
MulticastLoopbackOption Set this to 1 to enable the IP_MULTICAST_LOOP (multicast loopback) socket option.
See also
QAbstractSocket::setSocketOption(), QAbstractSocket::socketOption()
Enumerator
LowDelayOption
KeepAliveOption
MulticastTtlOption
MulticastLoopbackOption
Definition at line 120 of file qabstractsocket.h.
                       {
         LowDelayOption, // TCP_NODELAY
         KeepAliveOption, // SO_KEEPALIVE
         MulticastTtlOption, // IP_MULTICAST_TTL
         MulticastLoopbackOption // IP_MULTICAST_LOOPBACK
     };
SocketState
enum QAbstractSocket::SocketState
This enum describes the different states in which a socket can be.
UnconnectedState The socket is not connected.
HostLookupState The socket is performing a host name lookup.
ConnectingState The socket has started establishing a connection.
ConnectedState A connection is established.
BoundState The socket is bound to an address and port (for servers).
ClosingState The socket is about to close (data may still be waiting to be written).
ListeningState For internal use only.
Idle
HostLookup
Connecting
Connected
Closing
Connection
See also
QAbstractSocket::state()
Enumerator
UnconnectedState
HostLookupState
ConnectingState
ConnectedState
BoundState
ListeningState
ClosingState
Definition at line 102 of file qabstractsocket.h.
                      {
         UnconnectedState,
         HostLookupState,
         ConnectingState,
         ConnectedState,
         BoundState,
         ListeningState,
         ClosingState
 #ifdef QT3_SUPPORT
         ,
         Idle = UnconnectedState,
         HostLookup = HostLookupState,
         Connecting = ConnectingState,
         Connected = ConnectedState,
         Closing = ClosingState,
         Connection = ConnectedState
 #endif
     };
SocketType
enum QAbstractSocket::SocketType
This enum describes the transport layer protocol.
TcpSocket TCP
UdpSocket UDP
UnknownSocketType Other than TCP and UDP
See also
QAbstractSocket::socketType()
Enumerator
TcpSocket
UdpSocket
UnknownSocketType
Definition at line 69 of file qabstractsocket.h.
                     {
         TcpSocket,
         UdpSocket,
         UnknownSocketType = -1
     };
Constructors and Destructors
QAbstractSocket() [1/2]
QAbstractSocket::QAbstractSocket (SocketType socketType, QObject * parent)
Creates a new abstract socket of type socketType.
The parent argument is passed to QObject's constructor.
See also
socketType(), QTcpSocket, QUdpSocket
Definition at line 1351 of file qabstractsocket.cpp.
     : QIODevice(*new QAbstractSocketPrivate, parent)
 {
     Q_D(QAbstractSocket);
 #if defined(QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::QAbstractSocket(%p)", parent);
 #endif
     d->socketType = socketType;
 }
~QAbstractSocket()
QAbstractSocket::~QAbstractSocket () virtual
Destroys the socket.
Definition at line 1364 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
 #if defined(QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::~QAbstractSocket()");
 #endif
     if (d->state != UnconnectedState)
         abort();
 }
QAbstractSocket() [2/2]
QAbstractSocket::QAbstractSocket (SocketType socketType, QAbstractSocketPrivate & dd, QObject * parent = 0) protected
Constructs a new abstract socket of type socketType.
Warning
This function is not part of the public interface.
The parent argument is passed to QObject's constructor.
Definition at line 1332 of file qabstractsocket.cpp.
     : QIODevice(dd, parent)
 {
     Q_D(QAbstractSocket);
 #if defined(QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::QAbstractSocket(%sSocket, QAbstractSocketPrivate == %p, parent == %p)",
            socketType == TcpSocket ? "Tcp" : socketType == UdpSocket
            ? "Udp" : "Unknown", &dd, parent);
 #endif
     d->socketType = socketType;
 }
Functions
abort()
void QAbstractSocket::abort ()
Aborts the current connection and resets the socket.
Unlike disconnectFromHost(), this function immediately closes the socket, discarding any pending data in the write buffer.
See also
disconnectFromHost(), close()
Definition at line 2151 of file qabstractsocket.cpp.
Referenced by QHttpPrivate::_q_slotError(), QHttpPrivate::_q_slotSendRequest(), QFtpDTP::abortConnection(), QSocks5SocketEnginePrivate::reauthenticate(), and ~QAbstractSocket().
 {
     Q_D(QAbstractSocket);
 #if defined (QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::abort()");
 #endif
     if (d->state == UnconnectedState)
         return;
 #ifndef QT_NO_OPENSSL
     if (QSslSocket *socket = qobject_cast<QSslSocket *>(this)) {
         socket->abort();
         return;
     }
 #endif
     if (d->connectTimer) {
         d->connectTimer->stop();
         delete d->connectTimer;
         d->connectTimer = 0;
     }
     d->writeBuffer.clear();
     d->abortCalled = true;
     close();
 }
atEnd()
bool QAbstractSocket::atEnd () const virtual
Returns true if no more data is currently available for reading; otherwise returns false.
Reimplemented Function
This function is most commonly used when reading data from the socket in a loop. For example:
 // This slot is connected to QAbstractSocket::readyRead()
 void SocketClass::readyReadSlot()
 {
     while (!socket.atEnd()) {
         QByteArray data = socket.read(100);
         ....
     }
 }
See also
bytesAvailable(), readyRead()
Reimplemented from QIODevice.
Reimplemented in QSslSocket.
Definition at line 2198 of file qabstractsocket.cpp.
 {
     return QIODevice::atEnd() && (!isOpen() || d_func()->readBuffer.isEmpty());
 }
bytesAvailable()
qint64 QAbstractSocket::bytesAvailable () const virtual
Returns the number of incoming bytes that are waiting to be read.
See also
bytesToWrite(), read()
Reimplemented from QIODevice.
Reimplemented in QSslSocket.
Definition at line 1558 of file qabstractsocket.cpp.
Referenced by QHttpNetworkConnectionChannel::_q_error(), QHttpNetworkConnectionChannel::_q_readyRead(), QSslSocketPrivate::_q_readyReadSlot(), QHttpNetworkConnectionChannel::_q_receiveReply(), QHttpPrivate::_q_slotReadyRead(), QFtpDTP::abortConnection(), QHttpNetworkConnectionChannel::allDone(), QFtpDTP::bytesAvailable(), QVNCServer::clientCutText(), QSocks5PasswordAuthenticator::continueAuthenticate(), QSslSocketBackendPrivate::disconnected(), QHttpNetworkReplyPrivate::getChunkSize(), QSocks5SocketEnginePrivate::parseAuthenticationMethodReply(), QRfbSetEncodings::read(), QRfbFrameBufferUpdateRequest::read(), QRfbKeyEvent::read(), QRfbPointerEvent::read(), QRfbClientCutText::read(), QHttpNetworkReplyPrivate::readBody(), QHttpNetworkReplyPrivate::readBodyFast(), QVNCServer::readClient(), QHttpNetworkReplyPrivate::readReplyBodyChunked(), QHttpNetworkReplyPrivate::readReplyBodyRaw(), QHttpNetworkConnectionChannel::sendRequest(), QVNCServer::setEncodings(), QVNCServer::setPixelFormat(), QFtpDTP::socketReadyRead(), and QSslSocketBackendPrivate::transmit().
 {
     Q_D(const QAbstractSocket);
     qint64 available = QIODevice::bytesAvailable();
     available += (qint64) d->readBuffer.size();
     if (!d->isBuffered && d->socketEngine && d->socketEngine->isValid())
         available += d->socketEngine->bytesAvailable();
 #if defined(QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::bytesAvailable() == %llu", available);
 #endif
     return available;
 }
bytesToWrite()
qint64 QAbstractSocket::bytesToWrite () const virtual
Returns the number of bytes that are waiting to be written.
The bytes are written when control goes back to the event loop or when flush() is called.
See also
bytesAvailable(), flush()
Reimplemented from QIODevice.
Reimplemented in QSslSocket.
Definition at line 1544 of file qabstractsocket.cpp.
Referenced by QHttpPrivate::postMoreData(), QHttpNetworkConnectionChannel::sendRequest(), and QFtpDTP::writeData().
 {
     Q_D(const QAbstractSocket);
 #if defined(QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::bytesToWrite() == %i", d->writeBuffer.size());
 #endif
     return (qint64)d->writeBuffer.size();
 }
canReadLine()
bool QAbstractSocket::canReadLine () const virtual
Returns true if a line of data can be read from the socket; otherwise returns false.
See also
readLine()
Reimplemented from QIODevice.
Reimplemented in QSslSocket.
Definition at line 1644 of file qabstractsocket.cpp.
Referenced by QHttpPrivate::_q_slotReadyRead(), QFtpPI::readyRead(), and QFtpDTP::socketReadyRead().
 {
     bool hasLine = d_func()->readBuffer.canReadLine();
 #if defined (QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::canReadLine() == %s, buffer size = %d, size = %d", hasLine ? "true" : "false",
            d_func()->readBuffer.size(), d_func()->buffer.size());
 #endif
     return hasLine || QIODevice::canReadLine();
 }
close()
void QAbstractSocket::close () virtual
Closes the I/O device for the socket, disconnects the socket's connection with the host, closes the socket, and resets the name, address, port number and underlying socket descriptor.
See QIODevice::close() for a description of the actions that occur when an I/O device is closed.
See also
abort()
Reimplemented from QIODevice.
Reimplemented in QSslSocket.
Definition at line 2550 of file qabstractsocket.cpp.
Referenced by QHttpPrivate::_q_slotReadyRead(), abort(), QSslSocket::close(), QHttpNetworkConnectionChannel::close(), QHttpPrivate::closeConn(), QFtpPI::connectionClosed(), QSocks5PasswordAuthenticator::continueAuthenticate(), QSocks5SocketEnginePrivate::parseAuthenticationMethodReply(), QSocks5SocketEnginePrivate::parseRequestMethodReply(), QSocks5SocketEnginePrivate::reauthenticate(), QFtpDTP::socketReadyRead(), waitForBytesWritten(), waitForDisconnected(), waitForReadyRead(), QFtpDTP::writeData(), and QHttpNetworkConnectionPrivate::~QHttpNetworkConnectionPrivate().
 {
     Q_D(QAbstractSocket);
 #if defined(QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::close()");
 #endif
     QIODevice::close();
     if (d->state != UnconnectedState) {
         d->closeCalled = true;
         disconnectFromHost();
     }
     d->localPort = 0;
     d->peerPort = 0;
     d->localAddress.clear();
     d->peerAddress.clear();
     d->peerName.clear();
     d->cachedSocketDescriptor = -1;
 }
connected
void QAbstractSocket::connected () signal
This signal is emitted after connectToHost() has been called and a connection has been successfully established.
Note
On some operating systems the connected() signal may be directly emitted from the connectToHost() call for connections to the localhost.
See also
connectToHost(), disconnected()
connectToHost() [1/2]
void QAbstractSocket::connectToHost (const QString & hostName, quint16 port, OpenMode openMode = ReadWrite)
Attempts to make a connection to hostName on the given port.
The socket is opened in the given openMode and first enters HostLookupState, then performs a host name lookup of hostName. If the lookup succeeds, hostFound() is emitted and QAbstractSocket enters ConnectingState. It then attempts to connect to the address or addresses returned by the lookup. Finally, if a connection is established, QAbstractSocket enters ConnectedState and emits connected().
At any point, the socket can emit error() to signal that an error occurred.
hostName may be an IP address in string form (e.g., "43.195.83.32"), or it may be a host name (e.g., "example.com"). QAbstractSocket will do a lookup only if required. port is in native byte order.
See also
state(), peerName(), peerAddress(), peerPort(), waitForConnected()
Definition at line 1409 of file qabstractsocket.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), QFtpDTP::connectToHost(), connectToHost(), QFtpPI::connectToHost(), QHttpNetworkConnectionChannel::ensureConnection(), and QSocks5SocketEnginePrivate::reauthenticate().
 {
     QMetaObject::invokeMethod(this, "connectToHostImplementation",
                               Qt::DirectConnection,
                               Q_ARG(QString, hostName),
                               Q_ARG(quint16, port),
                               Q_ARG(OpenMode, openMode));
 }
connectToHost() [2/2]
void QAbstractSocket::connectToHost (const QHostAddress & address, quint16 port, OpenMode openMode = ReadWrite)
Attempts to make a connection to address on port port.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1527 of file qabstractsocket.cpp.
 {
 #if defined(QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::connectToHost([%s], %i, %i)...",
            address.toString().toLatin1().constData(), port, (int) openMode);
 #endif
     connectToHost(address.toString(), port, openMode);
 }
connectToHostImplementation
void QAbstractSocket::connectToHostImplementation (const QString & hostName, quint16 port, OpenMode openMode = ReadWrite) protected slot
Contains the implementation of connectToHost().
Since
4.1
Attempts to make a connection to hostName on the given port. The socket is opened in the given openMode.
Definition at line 1430 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
 #if defined(QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::connectToHost(\"%s\", %i, %i)...", qPrintable(hostName), port,
            (int) openMode);
 #endif
     if (d->state == ConnectedState || d->state == ConnectingState
         || d->state == ClosingState || d->state == HostLookupState) {
         qWarning("QAbstractSocket::connectToHost() called when already looking up or connecting/connected to \"%s\"", qPrintable(hostName));
         return;
     }
     d->hostName = hostName;
     d->port = port;
     d->state = UnconnectedState;
     d->readBuffer.clear();
     d->writeBuffer.clear();
     d->abortCalled = false;
     d->closeCalled = false;
     d->pendingClose = false;
     d->localPort = 0;
     d->peerPort = 0;
     d->localAddress.clear();
     d->peerAddress.clear();
     d->peerName = hostName;
     if (d->hostLookupId != -1) {
         QHostInfo::abortHostLookup(d->hostLookupId);
         d->hostLookupId = -1;
     }
 #ifndef QT_NO_NETWORKPROXY
     // Get the proxy information
     d->resolveProxy(hostName, port);
     if (d->proxyInUse.type() == QNetworkProxy::DefaultProxy) {
         // failed to setup the proxy
         d->socketError = QAbstractSocket::UnsupportedSocketOperationError;
         setErrorString(QAbstractSocket::tr("Operation on socket is not supported"));
         emit error(d->socketError);
         return;
     }
 #endif
     if (openMode & QIODevice::Unbuffered)
         d->isBuffered = false; // Unbuffered QTcpSocket
     else if (!d_func()->isBuffered)
         openMode |= QAbstractSocket::Unbuffered; // QUdpSocket
     QIODevice::open(openMode);
     d->state = HostLookupState;
     emit stateChanged(d->state);
     QHostAddress temp;
     if (temp.setAddress(hostName)) {
         QHostInfo info;
         info.setAddresses(QList<QHostAddress>() << temp);
         d->_q_startConnecting(info);
 #ifndef QT_NO_NETWORKPROXY
     } else if (d->proxyInUse.capabilities() & QNetworkProxy::HostNameLookupCapability) {
         // the proxy supports connection by name, so use it
         d->startConnectingByName(hostName);
         return;
 #endif
     } else {
         if (d->threadData->eventDispatcher) {
             // this internal API for QHostInfo either immediately gives us the desired
             // QHostInfo from cache or later calls the _q_startConnecting slot.
             bool immediateResultValid = false;
             QHostInfo hostInfo = qt_qhostinfo_lookup(hostName,
                                                      this,
                                                      SLOT(_q_startConnecting(QHostInfo)),
                                                      &immediateResultValid,
                                                      &d->hostLookupId);
             if (immediateResultValid) {
                 d->hostLookupId = -1;
                 d->_q_startConnecting(hostInfo);
             }
         }
     }
 #if defined(QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::connectToHost(\"%s\", %i) == %s%s", hostName.toLatin1().constData(), port,
            (d->state == ConnectedState) ? "true" : "false",
            (d->state == ConnectingState || d->state == HostLookupState)
            ? " (connection in progress)" : "");
 #endif
 }
disconnected
void QAbstractSocket::disconnected () signal
This signal is emitted when the socket has been disconnected.
Warning
If you need to delete the sender() of this signal in a slot connected to it, use the deleteLater() function.
See also
connectToHost(), disconnectFromHost(), abort()
Referenced by disconnectFromHostImplementation().
disconnectFromHost()
void QAbstractSocket::disconnectFromHost ()
Attempts to close the socket.
If there is pending data waiting to be written, QAbstractSocket will enter ClosingState and wait until all data has been written. Eventually, it will enter UnconnectedState and emit the disconnected() signal.
See also
connectToHost()
Definition at line 2578 of file qabstractsocket.cpp.
Referenced by close(), QSslSocketBackendPrivate::disconnectFromHost(), QSslSocketBackendPrivate::startHandshake(), and waitForConnected().
 {
     QMetaObject::invokeMethod(this, "disconnectFromHostImplementation",
                               Qt::DirectConnection);
 }
disconnectFromHostImplementation
void QAbstractSocket::disconnectFromHostImplementation () protected slot
Contains the implementation of disconnectFromHost().
Since
4.1
Definition at line 2592 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
 #if defined(QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::disconnectFromHost()");
 #endif
     if (d->state == UnconnectedState) {
 #if defined(QABSTRACTSOCKET_DEBUG)
         qDebug("QAbstractSocket::disconnectFromHost() was called on an unconnected socket");
 #endif
         return;
     }
     if (!d->abortCalled && (d->state == ConnectingState || d->state == HostLookupState)) {
 #if defined(QABSTRACTSOCKET_DEBUG)
         qDebug("QAbstractSocket::disconnectFromHost() but we're still connecting");
 #endif
         d->pendingClose = true;
         return;
     }
 #ifdef QT3_SUPPORT
     emit connectionClosed(); // compat signal
 #endif
     // Disable and delete read notification
     if (d->socketEngine)
         d->socketEngine->setReadNotificationEnabled(false);
     if (d->abortCalled) {
 #if defined(QABSTRACTSOCKET_DEBUG)
         qDebug("QAbstractSocket::disconnectFromHost() aborting immediately");
 #endif
         if (d->state == HostLookupState) {
             QHostInfo::abortHostLookup(d->hostLookupId);
             d->hostLookupId = -1;
         }
     } else {
         // Perhaps emit closing()
         if (d->state != ClosingState) {
             d->state = ClosingState;
 #if defined(QABSTRACTSOCKET_DEBUG)
             qDebug("QAbstractSocket::disconnectFromHost() emits stateChanged()(ClosingState)");
 #endif
             emit stateChanged(d->state);
         } else {
 #if defined(QABSTRACTSOCKET_DEBUG)
             qDebug("QAbstractSocket::disconnectFromHost() return from delayed close");
 #endif
         }
         // Wait for pending data to be written.
         if (d->socketEngine && d->socketEngine->isValid() && (d->writeBuffer.size() > 0
             || d->socketEngine->bytesToWrite() > 0)) {
             // hack: when we are waiting for the socket engine to write bytes (only
             // possible when using Socks5 or HTTP socket engine), then close
             // anyway after 2 seconds. This is to prevent a timeout on Mac, where we
             // sometimes just did not get the write notifier from the underlying
             // CFSocket and no progress was made.
             if (d->writeBuffer.size() == 0 && d->socketEngine->bytesToWrite() > 0) {
                 if (!d->disconnectTimer) {
                     d->disconnectTimer = new QTimer(this);
                     connect(d->disconnectTimer, SIGNAL(timeout()), this,
                             SLOT(_q_forceDisconnect()), Qt::DirectConnection);
                 }
                 if (!d->disconnectTimer->isActive())
                     d->disconnectTimer->start(2000);
             }
             d->socketEngine->setWriteNotificationEnabled(true);
 #if defined(QABSTRACTSOCKET_DEBUG)
             qDebug("QAbstractSocket::disconnectFromHost() delaying disconnect");
 #endif
             return;
         } else {
 #if defined(QABSTRACTSOCKET_DEBUG)
             qDebug("QAbstractSocket::disconnectFromHost() disconnecting immediately");
 #endif
         }
     }
     SocketState previousState = d->state;
     d->resetSocketLayer();
     d->state = UnconnectedState;
     emit stateChanged(d->state);
     emit readChannelFinished();       // we got an EOF
 #ifdef QT3_SUPPORT
     emit delayedCloseFinished(); // compat signal
 #endif
     // only emit disconnected if we were connected before
     if (previousState == ConnectedState || previousState == ClosingState)
         emit disconnected();
     d->localPort = 0;
     d->peerPort = 0;
     d->localAddress.clear();
     d->peerAddress.clear();
 #if defined(QABSTRACTSOCKET_DEBUG)
         qDebug("QAbstractSocket::disconnectFromHost() disconnected!");
 #endif
     if (d->closeCalled) {
 #if defined(QABSTRACTSOCKET_DEBUG)
         qDebug("QAbstractSocket::disconnectFromHost() closed!");
 #endif
         d->readBuffer.clear();
         d->writeBuffer.clear();
         QIODevice::close();
     }
 }
error() [1/2]
QAbstractSocket::SocketError QAbstractSocket::error () const
Returns the type of error that last occurred.
See also
state(), errorString()
Definition at line 2803 of file qabstractsocket.cpp.
Referenced by QSocks5SocketEnginePrivate::_q_emitPendingReadNotification(), QSslSocketPrivate::_q_errorSlot(), QHttpNetworkConnectionChannel::_q_readyRead(), QUdpSocket::bind(), QSocks5SocketEngine::bind(), connectToHostImplementation(), QUdpSocket::readDatagram(), QSocks5SocketEnginePrivate::setErrorState(), QSslSocketBackendPrivate::transmit(), waitForBytesWritten(), waitForDisconnected(), waitForReadyRead(), and QUdpSocket::writeDatagram().
 {
     return d_func()->socketError;
 }
error [2/2]
void QAbstractSocket::error (QAbstractSocket::SocketError socketError) signal
This signal is emitted after an error occurred.
The socketError parameter describes the type of error that occurred.
QAbstractSocket::SocketError is not a registered metatype, so for queued connections, you will have to register it with Q_DECLARE_METATYPE() and qRegisterMetaType().
See also
error(), errorString(), {Creating Custom Qt Types}
flush()
bool QAbstractSocket::flush ()
This function writes as much as possible from the internal write buffer to the underlying network socket, without blocking.
If any data was written, this function returns true; otherwise false is returned.
Call this function if you need QAbstractSocket to start sending buffered data immediately. The number of bytes successfully written depends on the operating system. In most cases, you do not need to call this function, because QAbstractSocket will start sending data automatically once control goes back to the event loop. In the absence of an event loop, call waitForBytesWritten() instead.
See also
write(), waitForBytesWritten()
Definition at line 2218 of file qabstractsocket.cpp.
Referenced by QDeclarativeDebugConnectionPrivate::advertisePlugins(), QDeclarativeDebugConnectionPrivate::connected(), QVNCDirtyMap::QVNCDirtyMap(), QSocks5SocketEnginePrivate::sendRequestMethod(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 {
     Q_D(QAbstractSocket);
 #ifndef QT_NO_OPENSSL
     // Manual polymorphism; flush() isn't virtual, but QSslSocket overloads
     // it.
     if (QSslSocket *socket = qobject_cast<QSslSocket *>(this))
         return socket->flush();
 #endif
     Q_CHECK_SOCKETENGINE(false);
     return d->flush();
 }
hostFound
void QAbstractSocket::hostFound () signal
This signal is emitted after connectToHost() has been called and the host lookup has succeeded.
Note
Since Qt 4.6.3 QAbstractSocket may emit hostFound() directly from the connectToHost() call since a DNS result could have been cached.
See also
connected()
isSequential()
bool QAbstractSocket::isSequential () const virtual
Reimplemented Function
Reimplemented from QIODevice.
Definition at line 2178 of file qabstractsocket.cpp.
 {
     return true;
 }
isValid()
bool QAbstractSocket::isValid () const
Returns true if the socket is valid and ready for use; otherwise returns false.
Note: The socket's state must be ConnectedState before reading and writing can occur.
See also
state()
Definition at line 1383 of file qabstractsocket.cpp.
Referenced by QUdpSocket::setMulticastInterface(), and QSslSocketBackendPrivate::transmit().
 {
     return d_func()->socketEngine ? d_func()->socketEngine->isValid() : isOpen();
 }
localAddress()
QHostAddress QAbstractSocket::localAddress () const
Returns the host address of the local socket if available; otherwise returns QHostAddress::Null.
This is normally the main IP address of the host, but can be QHostAddress::LocalHost (127.0.0.1) for connections to the local host.
See also
localPort(), peerAddress(), setLocalAddress()
Definition at line 1596 of file qabstractsocket.cpp.
Referenced by QSslSocketPrivate::_q_connectedSlot(), and QFtpPI::startNextCmd().
 {
     Q_D(const QAbstractSocket);
     return d->localAddress;
 }
localPort()
quint16 QAbstractSocket::localPort () const
Returns the host port number (in native byte order) of the local socket if available; otherwise returns 0.
See also
localAddress(), peerPort(), setLocalPort()
Definition at line 1580 of file qabstractsocket.cpp.
Referenced by QSslSocketPrivate::_q_connectedSlot(), and QSocks5SocketEngine::bind().
 {
     Q_D(const QAbstractSocket);
     return d->localPort;
 }
peerAddress()
QHostAddress QAbstractSocket::peerAddress () const
Returns the address of the connected peer if the socket is in ConnectedState; otherwise returns QHostAddress::Null.
See also
peerName(), peerPort(), localAddress(), setPeerAddress()
Definition at line 1620 of file qabstractsocket.cpp.
Referenced by QSslSocketPrivate::_q_connectedSlot(), and QFtpPI::processReply().
 {
     Q_D(const QAbstractSocket);
     return d->peerAddress;
 }
peerName()
QString QAbstractSocket::peerName () const
Returns the name of the peer as specified by connectToHost(), or an empty QString if connectToHost() has not been called.
See also
peerAddress(), peerPort(), setPeerName()
Definition at line 1632 of file qabstractsocket.cpp.
Referenced by QSslSocketPrivate::_q_connectedSlot(), QHttpPrivate::_q_slotError(), QHttpPrivate::_q_slotSendRequest(), QFtpPI::error(), QHttpNetworkConnectionPrivate::errorDetail(), and QFtpPI::processReply().
 {
     Q_D(const QAbstractSocket);
     return d->peerName.isEmpty() ? d->hostName : d->peerName;
 }
peerPort()
quint16 QAbstractSocket::peerPort () const
Returns the port of the connected peer if the socket is in ConnectedState; otherwise returns 0.
See also
peerAddress(), localPort(), setPeerPort()
Definition at line 1608 of file qabstractsocket.cpp.
Referenced by QSslSocketPrivate::_q_connectedSlot(), and QHttpPrivate::_q_slotSendRequest().
 {
     Q_D(const QAbstractSocket);
     return d->peerPort;
 }
proxy()
QNetworkProxy QAbstractSocket::proxy () const
Returns the network proxy for this socket.
Since
4.1
By default QNetworkProxy::DefaultProxy is used, which means this socket will query the default proxy settings for the application.
See also
setProxy(), QNetworkProxy, QNetworkProxyFactory
Definition at line 2859 of file qabstractsocket.cpp.
Referenced by QHttpNetworkConnectionChannel::ensureConnection().
 {
     Q_D(const QAbstractSocket);
     return d->proxy;
 }
proxyAuthenticationRequired
void QAbstractSocket::proxyAuthenticationRequired (const QNetworkProxy & proxy, QAuthenticator * authenticator) signal
Since
4.3
This signal can be emitted when a proxy that requires authentication is used. The authenticator object can then be filled in with the required details to allow authentication and continue the connection.
Note
It is not possible to use a QueuedConnection to connect to this signal, as the connection will fail if the authenticator has not been filled in with new information when the signal returns.
See also
QAuthenticator, QNetworkProxy
readBufferSize()
qint64 QAbstractSocket::readBufferSize () const
Returns the size of the internal read buffer.
This limits the amount of data that the client can receive before you call read() or readAll().
A read buffer size of 0 (the default) means that the buffer has no size limit, ensuring that no data is lost.
See also
setReadBufferSize(), read()
Definition at line 2716 of file qabstractsocket.cpp.
 {
     return d_func()->readBufferMaxSize;
 }
readData()
qint64 QAbstractSocket::readData (char * data, qint64 maxlen) protected virtual
Reimplemented Function
Implements QIODevice.
Reimplemented in QSslSocket.
Definition at line 2233 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
     // This is for a buffered QTcpSocket
     if (d->isBuffered && d->readBuffer.isEmpty())
         // if we're still connected, return 0 indicating there may be more data in the future
         // if we're not connected, return -1 indicating EOF
         return d->state == QAbstractSocket::ConnectedState ? qint64(0) : qint64(-1);
     // short cut for a char read if we have something in the buffer
     if (maxSize == 1 && !d->readBuffer.isEmpty()) {
         *data = d->readBuffer.getChar();
 #if defined (QABSTRACTSOCKET_DEBUG)
         qDebug("QAbstractSocket::readData(%p '%c (0x%.2x)', 1) == 1 [char buffer]",
                data, isprint(int(uchar(*data))) ? *data : '?', *data);
 #endif
         if (d->readBuffer.isEmpty() && d->socketEngine && d->socketEngine->isValid())
             d->socketEngine->setReadNotificationEnabled(true);
         return 1;
     }
     // Special case for an Unbuffered QTcpSocket
     // Re-filling the buffer.
     if (d->socketType == TcpSocket
             && !d->isBuffered
             && d->readBuffer.size() < maxSize
             && d->readBufferMaxSize > 0
             && maxSize < d->readBufferMaxSize
             && d->socketEngine
             && d->socketEngine->isValid()) {
         // Our buffer is empty and a read() was requested for a byte amount that is smaller
         // than the readBufferMaxSize. This means that we should fill our buffer since we want
         // such small reads come from the buffer and not always go to the costly socket engine read()
         qint64 bytesToRead = d->socketEngine->bytesAvailable();
         if (bytesToRead > 0) {
             char *ptr = d->readBuffer.reserve(bytesToRead);
             qint64 readBytes = d->socketEngine->read(ptr, bytesToRead);
             if (readBytes == -2) {
                 // No bytes currently available for reading.
                 d->readBuffer.chop(bytesToRead);
             } else {
                 d->readBuffer.chop(int(bytesToRead - (readBytes < 0 ? qint64(0) : readBytes)));
             }
         }
    }
     // First try to satisfy the read from the buffer
     qint64 bytesToRead = qMin(qint64(d->readBuffer.size()), maxSize);
     qint64 readSoFar = 0;
     while (readSoFar < bytesToRead) {
         const char *ptr = d->readBuffer.readPointer();
         int bytesToReadFromThisBlock = qMin(int(bytesToRead - readSoFar),
                                             d->readBuffer.nextDataBlockSize());
         memcpy(data + readSoFar, ptr, bytesToReadFromThisBlock);
         readSoFar += bytesToReadFromThisBlock;
         d->readBuffer.free(bytesToReadFromThisBlock);
     }
     if (d->socketEngine && !d->socketEngine->isReadNotificationEnabled() && d->socketEngine->isValid())
         d->socketEngine->setReadNotificationEnabled(true);
     if (readSoFar > 0) {
         // we read some data from buffer.
         // Just return, readyRead will be emitted again
 #if defined (QABSTRACTSOCKET_DEBUG)
         qDebug("QAbstractSocket::readData(%p '%c (0x%.2x)', %lli) == %lli [buffer]",
                data, isprint(int(uchar(*data))) ? *data : '?', *data, maxSize, readSoFar);
 #endif
         if (d->readBuffer.isEmpty() && d->socketEngine)
             d->socketEngine->setReadNotificationEnabled(true);
         return readSoFar;
     }
     // This code path is for Unbuffered QTcpSocket or for connected UDP
     if (!d->isBuffered) {
         if (!d->socketEngine)
             return -1;          // no socket engine is probably EOF
         if (!d->socketEngine->isValid())
             return -1; // This is for unbuffered TCP when we already had been disconnected
         if (d->state != QAbstractSocket::ConnectedState)
             return -1; // This is for unbuffered TCP if we're not connected yet
         qint64 readBytes = d->socketEngine->read(data, maxSize);
         if (readBytes == -2) {
             // -2 from the engine means no bytes available (EAGAIN) so read more later
             return 0;
         } else if (readBytes < 0) {
             d->socketError = d->socketEngine->error();
             setErrorString(d->socketEngine->errorString());
             d->resetSocketLayer();
             d->state = QAbstractSocket::UnconnectedState;
         } else if (!d->socketEngine->isReadNotificationEnabled()) {
             // Only do this when there was no error
             d->socketEngine->setReadNotificationEnabled(true);
         }
 #if defined (QABSTRACTSOCKET_DEBUG)
         qDebug("QAbstractSocket::readData(%p \"%s\", %lli) == %lld [engine]",
                data, qt_prettyDebug(data, 32, readBytes).data(), maxSize,
                readBytes);
 #endif
         return readBytes;
     }
 #if defined (QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::readData(%p \"%s\", %lli) == %lld [unreachable]",
            data, qt_prettyDebug(data, qMin<qint64>(32, readSoFar), readSoFar).data(),
            maxSize, readSoFar);
 #endif
     return readSoFar;
 }
readLineData()
qint64 QAbstractSocket::readLineData (char * data, qint64 maxlen) protected virtual
Reimplemented Function
Reimplemented from QIODevice.
Definition at line 2350 of file qabstractsocket.cpp.
 {
     return QIODevice::readLineData(data, maxlen);
 }
setLocalAddress()
void QAbstractSocket::setLocalAddress (const QHostAddress & address) protected
Sets the address on the local side of a connection to address.
Since
4.1
You can call this function in a subclass of QAbstractSocket to change the return value of the localAddress() function after a connection has been established. This feature is commonly used by proxy connections for virtual connection settings.
Note that this function does not bind the local address of the socket prior to a connection (e.g., QUdpSocket::bind()).
See also
localAddress(), setLocalPort(), setPeerAddress()
Definition at line 2469 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
     d->localAddress = address;
 }
setLocalPort()
void QAbstractSocket::setLocalPort (quint16 port) protected
Sets the port on the local side of a connection to port.
Since
4.1
You can call this function in a subclass of QAbstractSocket to change the return value of the localPort() function after a connection has been established. This feature is commonly used by proxy connections for virtual connection settings.
Note that this function does not bind the local port of the socket prior to a connection (e.g., QUdpSocket::bind()).
See also
localAddress(), setLocalAddress(), setPeerPort()
Definition at line 2444 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
     d->localPort = port;
 }
setPeerAddress()
void QAbstractSocket::setPeerAddress (const QHostAddress & address) protected
Sets the address of the remote side of the connection to address.
Since
4.1
You can call this function in a subclass of QAbstractSocket to change the return value of the peerAddress() function after a connection has been established. This feature is commonly used by proxy connections for virtual connection settings.
See also
peerAddress(), setPeerPort(), setLocalAddress()
Definition at line 2513 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
     d->peerAddress = address;
 }
setPeerName()
void QAbstractSocket::setPeerName (const QString & name) protected
Sets the host name of the remote peer to name.
Since
4.1
You can call this function in a subclass of QAbstractSocket to change the return value of the peerName() function after a connection has been established. This feature is commonly used by proxy connections for virtual connection settings.
See also
peerName()
Definition at line 2534 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
     d->peerName = name;
 }
setPeerPort()
void QAbstractSocket::setPeerPort (quint16 port) protected
Sets the port of the remote side of the connection to port.
Since
4.1
You can call this function in a subclass of QAbstractSocket to change the return value of the peerPort() function after a connection has been established. This feature is commonly used by proxy connections for virtual connection settings.
See also
peerPort(), setPeerAddress(), setLocalPort()
Definition at line 2491 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
     d->peerPort = port;
 }
setProxy()
void QAbstractSocket::setProxy (const QNetworkProxy & networkProxy)
Sets the explicit network proxy for this socket to networkProxy.
Since
4.1
To disable the use of a proxy for this socket, use the QNetworkProxy::NoProxy proxy type:
socket->setProxy(QNetworkProxy::NoProxy);
The default value for the proxy is QNetworkProxy::DefaultProxy, which means the socket will use the application settings: if a proxy is set with QNetworkProxy::setApplicationProxy, it will use that; otherwise, if a factory is set with QNetworkProxyFactory::setApplicationProxyFactory, it will query that factory with type QNetworkProxyQuery::TcpSocket.
See also
proxy(), QNetworkProxy, QNetworkProxyFactory::queryProxy()
Definition at line 2841 of file qabstractsocket.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), QSocks5SocketEngine::bind(), QHttpNetworkConnectionChannel::init(), and QSocks5SocketEnginePrivate::initialize().
 {
     Q_D(QAbstractSocket);
     d->proxy = networkProxy;
 }
setReadBufferSize()
void QAbstractSocket::setReadBufferSize (qint64 size)
Sets the size of QAbstractSocket's internal read buffer to be size bytes.
If the buffer size is limited to a certain size, QAbstractSocket won't buffer more than this size of data. Exceptionally, a buffer size of 0 means that the read buffer is unlimited and all incoming data is buffered. This is the default.
This option is useful if you only read the data at certain points in time (e.g., in a real-time streaming application) or if you want to protect your socket against receiving too much data, which may eventually cause your application to run out of memory.
Only QTcpSocket uses QAbstractSocket's internal buffer; QUdpSocket does not use any buffering at all, but rather relies on the implicit buffering provided by the operating system. Because of this, calling this function on QUdpSocket has no effect.
See also
readBufferSize(), read()
Definition at line 2743 of file qabstractsocket.cpp.
Referenced by QHttpNetworkConnectionChannel::ensureConnection(), and QSslSocketBackendPrivate::startHandshake().
 {
     Q_D(QAbstractSocket);
 #ifndef QT_NO_OPENSSL
     // Manual polymorphism; setReadBufferSize() isn't virtual, but QSslSocket overloads
     // it.
     if (QSslSocket *socket = qobject_cast<QSslSocket *>(this)) {
         socket->setReadBufferSize(size);
         return;
     }
 #endif
     if (d->readBufferMaxSize == size)
         return;
     d->readBufferMaxSize = size;
     if (!d->readSocketNotifierCalled && d->socketEngine) {
         // ensure that the read notification is enabled if we've now got
         // room in the read buffer
         // but only if we're not inside canReadNotification -- that will take care on its own
         if ((size == 0 || d->readBuffer.size() < size) && d->state == QAbstractSocket::ConnectedState) // Do not change the notifier unless we are connected.
             d->socketEngine->setReadNotificationEnabled(true);
     }
 }
setSocketDescriptor()
bool QAbstractSocket::setSocketDescriptor (int socketDescriptor, SocketState socketState = ConnectedState, OpenMode openMode = ReadWrite)
Initializes QAbstractSocket with the native socket descriptor socketDescriptor.
Returns true if socketDescriptor is accepted as a valid socket descriptor; otherwise returns false. The socket is opened in the mode specified by openMode, and enters the socket state specified by socketState.
Note: It is not possible to initialize two abstract sockets with the same native socket descriptor.
See also
socketDescriptor()
Definition at line 1684 of file qabstractsocket.cpp.
Referenced by QTcpServer::incomingConnection().
 {
     Q_D(QAbstractSocket);
 #ifndef QT_NO_OPENSSL
     if (QSslSocket *socket = qobject_cast<QSslSocket *>(this))
         return socket->setSocketDescriptor(socketDescriptor, socketState, openMode);
 #endif
     d->resetSocketLayer();
     d->socketEngine = QAbstractSocketEngine::createSocketEngine(socketDescriptor, this);
     if (!d->socketEngine) {
         d->socketError = UnsupportedSocketOperationError;
         setErrorString(tr("Operation on socket is not supported"));
         return false;
     }
 #ifndef QT_NO_BEARERMANAGEMENT
     //copy network session down to the socket engine (if it has been set)
     d->socketEngine->setProperty("_q_networksession", property("_q_networksession"));
 #endif
     bool result = d->socketEngine->initialize(socketDescriptor, socketState);
     if (!result) {
         d->socketError = d->socketEngine->error();
         setErrorString(d->socketEngine->errorString());
         return false;
     }
     if (d->threadData->eventDispatcher)
         d->socketEngine->setReceiver(d);
     QIODevice::open(openMode);
     if (d->state != socketState) {
         d->state = socketState;
         emit stateChanged(d->state);
     }
     d->pendingClose = false;
     d->socketEngine->setReadNotificationEnabled(true);
     d->localPort = d->socketEngine->localPort();
     d->peerPort = d->socketEngine->peerPort();
     d->localAddress = d->socketEngine->localAddress();
     d->peerAddress = d->socketEngine->peerAddress();
     d->cachedSocketDescriptor = socketDescriptor;
     return true;
 }
setSocketError()
void QAbstractSocket::setSocketError (SocketError socketError) protected
Sets the type of error that last occurred to socketError.
See also
setSocketState(), setErrorString()
Definition at line 2813 of file qabstractsocket.cpp.
 {
     d_func()->socketError = socketError;
 }
setSocketOption()
void QAbstractSocket::setSocketOption (QAbstractSocket::SocketOption option, const QVariant & value)
Sets the given option to the value described by value.
Since
4.6
See also
socketOption()
Definition at line 1741 of file qabstractsocket.cpp.
Referenced by QHttpNetworkConnectionChannel::_q_connected(), and QFtpPI::connected().
 {
 #ifndef QT_NO_OPENSSL
     if (QSslSocket *sslSocket = qobject_cast<QSslSocket*>(this)) {
         sslSocket->setSocketOption(option, value);
         return;
     }
 #endif
     if (!d_func()->socketEngine)
         return;
     switch (option) {
         case LowDelayOption:
             d_func()->socketEngine->setOption(QAbstractSocketEngine::LowDelayOption, value.toInt());
             break;
         case KeepAliveOption:
             d_func()->socketEngine->setOption(QAbstractSocketEngine::KeepAliveOption, value.toInt());
             break;
         case MulticastTtlOption:
                 d_func()->socketEngine->setOption(QAbstractSocketEngine::MulticastTtlOption, value.toInt());
                 break;
         case MulticastLoopbackOption:
                 d_func()->socketEngine->setOption(QAbstractSocketEngine::MulticastLoopbackOption, value.toInt());
                 break;
     }
 }
setSocketState()
void QAbstractSocket::setSocketState (SocketState state) protected
Sets the state of the socket to state.
See also
state()
Definition at line 2783 of file qabstractsocket.cpp.
 {
     d_func()->state = state;
 }
socketDescriptor()
int QAbstractSocket::socketDescriptor () const
Returns the native socket descriptor of the QAbstractSocket object if this is available; otherwise returns -1.
If the socket is using QNetworkProxy, the returned descriptor may not be usable with native socket functions.
The socket descriptor is not available when QAbstractSocket is in UnconnectedState.
See also
setSocketDescriptor()
Definition at line 1666 of file qabstractsocket.cpp.
Referenced by QSslSocketPrivate::_q_connectedSlot(), QLocalServerPrivate::_q_onNewConnection(), QLocalSocket::setSocketDescriptor(), and setSocketDescriptor().
 {
     Q_D(const QAbstractSocket);
     return d->cachedSocketDescriptor;
 }
socketOption()
QVariant QAbstractSocket::socketOption (QAbstractSocket::SocketOption option)
Returns the value of the option option.
Since
4.6
See also
setSocketOption()
Definition at line 1781 of file qabstractsocket.cpp.
 {
 #ifndef QT_NO_OPENSSL
     if (QSslSocket *sslSocket = qobject_cast<QSslSocket*>(this)) {
         return sslSocket->socketOption(option);
     }
 #endif
     if (!d_func()->socketEngine)
         return QVariant();
     int ret = -1;
     switch (option) {
         case LowDelayOption:
             ret = d_func()->socketEngine->option(QAbstractSocketEngine::LowDelayOption);
             break;
         case KeepAliveOption:
             ret = d_func()->socketEngine->option(QAbstractSocketEngine::KeepAliveOption);
             break;
         case MulticastTtlOption:
                 ret = d_func()->socketEngine->option(QAbstractSocketEngine::MulticastTtlOption);
                 break;
         case MulticastLoopbackOption:
                 ret = d_func()->socketEngine->option(QAbstractSocketEngine::MulticastLoopbackOption);
                 break;
     }
     if (ret == -1)
         return QVariant();
     else
         return QVariant(ret);
 }
socketType()
QAbstractSocket::SocketType QAbstractSocket::socketType () const
Returns the socket type (TCP, UDP, or other).
See also
QTcpSocket, QUdpSocket
Definition at line 2793 of file qabstractsocket.cpp.
Referenced by QAbstractSocket().
 {
     return d_func()->socketType;
 }
state()
QAbstractSocket::SocketState QAbstractSocket::state () const
Returns the state of the socket.
See also
error()
Definition at line 2773 of file qabstractsocket.cpp.
Referenced by QSocks5SocketEnginePrivate::_q_emitPendingReadNotification(), QHttpNetworkConnectionChannel::_q_readyRead(), QHttpNetworkConnectionChannel::_q_receiveReply(), QHttpPrivate::_q_slotSendRequest(), QHttpNetworkConnectionPrivate::_q_startNextRequest(), QHttpNetworkConnectionChannel::allDone(), QUdpSocket::bind(), QFtpDTP::bytesAvailable(), QHttpNetworkConnectionChannel::close(), QHttpNetworkConnectionChannel::detectPipeliningSupport(), QHttpNetworkConnectionChannel::ensureConnection(), QHttpNetworkConnectionPrivate::fillPipeline(), QDeclarativeDebugConnection::isConnected(), QVNCDirtyMap::QVNCDirtyMap(), QFtpDTP::read(), QFtpDTP::readAll(), QFtpPI::sendCommands(), setSocketState(), QFtpDTP::state(), QSslSocketBackendPrivate::transmit(), waitForBytesWritten(), waitForConnected(), waitForDisconnected(), waitForReadyRead(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 {
     return d_func()->state;
 }
stateChanged
void QAbstractSocket::stateChanged (QAbstractSocket::SocketState socketState) signal
This signal is emitted whenever QAbstractSocket's state changes.
The socketState parameter is the new state.
QAbstractSocket::SocketState is not a registered metatype, so for queued connections, you will have to register it with Q_REGISTER_METATYPE() and qRegisterMetaType().
See also
state(), {Creating Custom Qt Types}
Referenced by QUdpSocket::bind(), connectToHostImplementation(), disconnectFromHostImplementation(), setSocketDescriptor(), and waitForConnected().
waitForBytesWritten()
bool QAbstractSocket::waitForBytesWritten (int msecs = 30000) virtual
Reimplemented Function
Reimplemented from QIODevice.
Reimplemented in QSslSocket.
Definition at line 2006 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
 #if defined (QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::waitForBytesWritten(%i)", msecs);
 #endif
     // require calling connectToHost() before waitForBytesWritten()
     if (state() == UnconnectedState) {
         qWarning("QAbstractSocket::waitForBytesWritten() is not allowed in UnconnectedState");
         return false;
     }
     if (d->writeBuffer.isEmpty())
         return false;
     QElapsedTimer stopWatch;
     stopWatch.start();
     // handle a socket in connecting state
     if (state() == HostLookupState || state() == ConnectingState) {
         if (!waitForConnected(msecs))
             return false;
     }
     forever {
         bool readyToRead = false;
         bool readyToWrite = false;
         if (!d->socketEngine->waitForReadOrWrite(&readyToRead, &readyToWrite, true, !d->writeBuffer.isEmpty(),
                                                qt_timeout_value(msecs, stopWatch.elapsed()))) {
             d->socketError = d->socketEngine->error();
             setErrorString(d->socketEngine->errorString());
 #if defined (QABSTRACTSOCKET_DEBUG)
             qDebug("QAbstractSocket::waitForBytesWritten(%i) failed (%i, %s)",
                    msecs, d->socketError, errorString().toLatin1().constData());
 #endif
             emit error(d->socketError);
             if (d->socketError != SocketTimeoutError)
                 close();
             return false;
         }
         if (readyToRead) {
 #if defined (QABSTRACTSOCKET_DEBUG)
             qDebug("QAbstractSocket::waitForBytesWritten calls canReadNotification");
 #endif
             if(!d->canReadNotification())
                 return false;
         }
         if (readyToWrite) {
             if (d->canWriteNotification()) {
 #if defined (QABSTRACTSOCKET_DEBUG)
                 qDebug("QAbstractSocket::waitForBytesWritten returns true");
 #endif
                 return true;
             }
         }
         if (state() != ConnectedState)
             return false;
     }
     return false;
 }
waitForConnected()
bool QAbstractSocket::waitForConnected (int msecs = 30000)
Waits until the socket is connected, up to msecs milliseconds.
If the connection has been established, this function returns true; otherwise it returns false. In the case where it returns false, you can call error() to determine the cause of the error.
The following example waits up to one second for a connection to be established:
socket->connectToHost("imap", 143);
if (socket->waitForConnected(1000))
    qDebug("Connected!");
If msecs is -1, this function will not time out.
Note
This function may wait slightly longer than msecs, depending on the time it takes to complete the host lookup.
Multiple calls to this functions do not accumulate the time. If the function times out, the connecting process will be aborted.
See also
connectToHost(), connected()
Definition at line 1851 of file qabstractsocket.cpp.
Referenced by waitForBytesWritten(), waitForDisconnected(), and waitForReadyRead().
 {
     Q_D(QAbstractSocket);
 #if defined (QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::waitForConnected(%i)", msecs);
 #endif
     if (state() == ConnectedState) {
 #if defined (QABSTRACTSOCKET_DEBUG)
         qDebug("QAbstractSocket::waitForConnected(%i) already connected", msecs);
 #endif
         return true;
     }
 #ifndef QT_NO_OPENSSL
     // Manual polymorphism; this function is not virtual, but has an overload
     // in QSslSocket.
     if (QSslSocket *socket = qobject_cast<QSslSocket *>(this))
         return socket->waitForConnected(msecs);
 #endif
     bool wasPendingClose = d->pendingClose;
     d->pendingClose = false;
     QElapsedTimer stopWatch;
     stopWatch.start();
     if (d->state == HostLookupState) {
 #if defined (QABSTRACTSOCKET_DEBUG)
         qDebug("QAbstractSocket::waitForConnected(%i) doing host name lookup", msecs);
 #endif
         QHostInfo::abortHostLookup(d->hostLookupId);
         d->hostLookupId = -1;
 #ifndef QT_NO_BEARERMANAGEMENT
         QSharedPointer<QNetworkSession> networkSession;
         QVariant v(property("_q_networksession"));
         if (v.isValid()) {
             networkSession = qvariant_cast< QSharedPointer<QNetworkSession> >(v);
             d->_q_startConnecting(QHostInfoPrivate::fromName(d->hostName, networkSession));
         } else
 #endif
         d->_q_startConnecting(QHostInfo::fromName(d->hostName));
     }
     if (state() == UnconnectedState)
         return false; // connect not im progress anymore!
     bool timedOut = true;
 #if defined (QABSTRACTSOCKET_DEBUG)
     int attempt = 1;
 #endif
     while (state() == ConnectingState && (msecs == -1 || stopWatch.elapsed() < msecs)) {
         int timeout = qt_timeout_value(msecs, stopWatch.elapsed());
         if (msecs != -1 && timeout > QT_CONNECT_TIMEOUT)
             timeout = QT_CONNECT_TIMEOUT;
 #if defined (QABSTRACTSOCKET_DEBUG)
         qDebug("QAbstractSocket::waitForConnected(%i) waiting %.2f secs for connection attempt #%i",
                msecs, timeout / 1000.0, attempt++);
 #endif
         timedOut = false;
         if (d->socketEngine && d->socketEngine->waitForWrite(timeout, &timedOut) && !timedOut) {
             d->_q_testConnection();
         } else {
             d->_q_connectToNextAddress();
         }
     }
     if ((timedOut && state() != ConnectedState) || state() == ConnectingState) {
         d->socketError = SocketTimeoutError;
         d->state = UnconnectedState;
         emit stateChanged(d->state);
         d->resetSocketLayer();
         setErrorString(tr("Socket operation timed out"));
     }
 #if defined (QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::waitForConnected(%i) == %s", msecs,
            state() == ConnectedState ? "true" : "false");
 #endif
     if (state() != ConnectedState)
         return false;
     if (wasPendingClose)
         disconnectFromHost();
     return true;
 }
waitForDisconnected()
bool QAbstractSocket::waitForDisconnected (int msecs = 30000)
Waits until the socket has disconnected, up to msecs milliseconds.
If the connection has been disconnected, this function returns true; otherwise it returns false. In the case where it returns false, you can call error() to determine the cause of the error.
The following example waits up to one second for a connection to be closed:
socket->disconnectFromHost();
    if (socket->state() == QAbstractSocket::UnconnectedState ||
        socket->waitForDisconnected(1000))
        qDebug("Disconnected!");
If msecs is -1, this function will not time out.
See also
disconnectFromHost(), close()
Definition at line 2088 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
 #ifndef QT_NO_OPENSSL
     // Manual polymorphism; this function is not virtual, but has an overload
     // in QSslSocket.
     if (QSslSocket *socket = qobject_cast<QSslSocket *>(this))
         return socket->waitForDisconnected(msecs);
 #endif
     // require calling connectToHost() before waitForDisconnected()
     if (state() == UnconnectedState) {
         qWarning("QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState");
         return false;
     }
     QElapsedTimer stopWatch;
     stopWatch.start();
     // handle a socket in connecting state
     if (state() == HostLookupState || state() == ConnectingState) {
         if (!waitForConnected(msecs))
             return false;
         if (state() == UnconnectedState)
             return true;
     }
     forever {
         bool readyToRead = false;
         bool readyToWrite = false;
         if (!d->socketEngine->waitForReadOrWrite(&readyToRead, &readyToWrite, state() == ConnectedState,
                                                !d->writeBuffer.isEmpty(),
                                                qt_timeout_value(msecs, stopWatch.elapsed()))) {
             d->socketError = d->socketEngine->error();
             setErrorString(d->socketEngine->errorString());
 #if defined (QABSTRACTSOCKET_DEBUG)
             qDebug("QAbstractSocket::waitForReadyRead(%i) failed (%i, %s)",
                    msecs, d->socketError, errorString().toLatin1().constData());
 #endif
             emit error(d->socketError);
             if (d->socketError != SocketTimeoutError)
                 close();
             return false;
         }
         if (readyToRead)
             d->canReadNotification();
         if (readyToWrite)
             d->canWriteNotification();
         if (state() == UnconnectedState)
             return true;
     }
     return false;
 }
waitForReadyRead()
bool QAbstractSocket::waitForReadyRead (int msecs = 30000) virtual
This function blocks until new data is available for reading and the QIODevice::readyRead() signal has been emitted.
The function will timeout after msecs milliseconds; the default timeout is 30000 milliseconds.
The function returns true if the readyRead() signal is emitted and there is new data available for reading; otherwise it returns false (if an error occurred or the operation timed out).
See also
waitForBytesWritten()
Reimplemented from QIODevice.
Reimplemented in QSslSocket.
Definition at line 1948 of file qabstractsocket.cpp.
Referenced by QSocks5SocketEngine::bind().
 {
     Q_D(QAbstractSocket);
 #if defined (QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::waitForReadyRead(%i)", msecs);
 #endif
     // require calling connectToHost() before waitForReadyRead()
     if (state() == UnconnectedState) {
         /* If all you have is a QIODevice pointer to an abstractsocket, you cannot check
            this, so you cannot avoid this warning. */
 //        qWarning("QAbstractSocket::waitForReadyRead() is not allowed in UnconnectedState");
         return false;
     }
     QElapsedTimer stopWatch;
     stopWatch.start();
     // handle a socket in connecting state
     if (state() == HostLookupState || state() == ConnectingState) {
         if (!waitForConnected(msecs))
             return false;
     }
     Q_ASSERT(d->socketEngine);
     do {
         bool readyToRead = false;
         bool readyToWrite = false;
         if (!d->socketEngine->waitForReadOrWrite(&readyToRead, &readyToWrite, true, !d->writeBuffer.isEmpty(),
                                                qt_timeout_value(msecs, stopWatch.elapsed()))) {
             d->socketError = d->socketEngine->error();
             setErrorString(d->socketEngine->errorString());
 #if defined (QABSTRACTSOCKET_DEBUG)
             qDebug("QAbstractSocket::waitForReadyRead(%i) failed (%i, %s)",
                    msecs, d->socketError, errorString().toLatin1().constData());
 #endif
             emit error(d->socketError);
             if (d->socketError != SocketTimeoutError)
                 close();
             return false;
         }
         if (readyToRead) {
             if (d->canReadNotification())
                 return true;
         }
         if (readyToWrite)
             d->canWriteNotification();
         if (state() != ConnectedState)
             return false;
     } while (msecs == -1 || qt_timeout_value(msecs, stopWatch.elapsed()) > 0);
     return false;
 }
writeData()
qint64 QAbstractSocket::writeData (const char * data, qint64 len) protected virtual
Reimplemented Function
Implements QIODevice.
Reimplemented in QSslSocket.
Definition at line 2357 of file qabstractsocket.cpp.
 {
     Q_D(QAbstractSocket);
     if (d->state == QAbstractSocket::UnconnectedState) {
         d->socketError = QAbstractSocket::UnknownSocketError;
         setErrorString(tr("Socket is not connected"));
         return -1;
     }
     if (!d->isBuffered && d->socketType == TcpSocket && d->writeBuffer.isEmpty()) {
         // This code is for the new Unbuffered QTcpSocket use case
         qint64 written = d->socketEngine->write(data, size);
         if (written < 0) {
             d->socketError = d->socketEngine->error();
             setErrorString(d->socketEngine->errorString());
             return written;
         } else if (written < size) {
             // Buffer what was not written yet
             char *ptr = d->writeBuffer.reserve(size - written);
             memcpy(ptr, data + written, size - written);
             if (d->socketEngine)
                 d->socketEngine->setWriteNotificationEnabled(true);
         }
         return size; // size=actually written + what has been buffered
     } else if (!d->isBuffered && d->socketType != TcpSocket) {
         // This is for a QUdpSocket that was connect()ed
         qint64 written = d->socketEngine->write(data, size);
         if (written < 0) {
             d->socketError = d->socketEngine->error();
             setErrorString(d->socketEngine->errorString());
         } else if (!d->writeBuffer.isEmpty()) {
             d->socketEngine->setWriteNotificationEnabled(true);
         }
 #if defined (QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::writeData(%p \"%s\", %lli) == %lli", data,
            qt_prettyDebug(data, qMin((int)size, 32), size).data(),
            size, written);
 #endif
         if (written >= 0)
             emit bytesWritten(written);
         return written;
     }
     // This is the code path for normal buffered QTcpSocket or
     // unbuffered QTcpSocket when there was already something in the
     // write buffer and therefore we could not do a direct engine write.
     // We just write to our write buffer and enable the write notifier
     // The write notifier then flush()es the buffer.
     char *ptr = d->writeBuffer.reserve(size);
     if (size == 1)
         *ptr = *data;
     else
         memcpy(ptr, data, size);
     qint64 written = size;
     if (d->socketEngine && !d->writeBuffer.isEmpty())
         d->socketEngine->setWriteNotificationEnabled(true);
 #if defined (QABSTRACTSOCKET_DEBUG)
     qDebug("QAbstractSocket::writeData(%p \"%s\", %lli) == %lli", data,
            qt_prettyDebug(data, qMin((int)size, 32), size).data(),
            size, written);
 #endif
     return written;
 }
The documentation for this class was generated from the following files:
/src/network/socket/qabstractsocket.h
/src/network/socket/qabstractsocket.cpp