Qt 4.8: QCriticalSection Class Reference
QCriticalSection Class Reference
Public Functions
void lock ()
QCriticalSection ()
void unlock ()
~QCriticalSection ()
Properties
CRITICAL_SECTION section
Detailed Description
Definition at line 48 of file qatomic_generic_windows.cpp.
Constructors and Destructors
QCriticalSection()
QCriticalSection::QCriticalSection () inline
Definition at line 51 of file qatomic_generic_windows.cpp.
 { InitializeCriticalSection(&section); }
~QCriticalSection()
QCriticalSection::~QCriticalSection () inline
Definition at line 52 of file qatomic_generic_windows.cpp.
 { DeleteCriticalSection(&section); }
Functions
lock()
void QCriticalSection::lock () inline
Definition at line 53 of file qatomic_generic_windows.cpp.
Referenced by QBasicAtomicInt_fetchAndAddOrdered(), QBasicAtomicInt_fetchAndStoreOrdered(), QBasicAtomicInt_testAndSetOrdered(), QBasicAtomicPointer_fetchAndAddOrdered(), QBasicAtomicPointer_fetchAndStoreOrdered(), and QBasicAtomicPointer_testAndSetOrdered().
 { EnterCriticalSection(&section); }
unlock()
void QCriticalSection::unlock () inline
Definition at line 54 of file qatomic_generic_windows.cpp.
Referenced by QBasicAtomicInt_fetchAndAddOrdered(), QBasicAtomicInt_fetchAndStoreOrdered(), QBasicAtomicInt_testAndSetOrdered(), QBasicAtomicPointer_fetchAndAddOrdered(), QBasicAtomicPointer_fetchAndStoreOrdered(), and QBasicAtomicPointer_testAndSetOrdered().
 { LeaveCriticalSection(&section); }
Properties
section
CRITICAL_SECTION QCriticalSection::section private
Definition at line 57 of file qatomic_generic_windows.cpp.
Referenced by lock(), QCriticalSection(), unlock(), and ~QCriticalSection().
The documentation for this class was generated from the following file:
/src/corelib/arch/generic/qatomic_generic_windows.cpp