Qt 4.8: QDeclarativeSimpleAction Class Reference
QDeclarativeSimpleAction Class Reference
#include <qdeclarativestate_p_p.h>
Public Types
enum State { StartState, EndState }
Public Functions
QDeclarativeAbstractBinding * binding () const
QDeclarativeActionEvent * event () const
QDeclarativeSimpleAction & operator= (const QDeclarativeSimpleAction &other)
const QDeclarativeProperty & property () const
QDeclarativeSimpleAction (const QDeclarativeAction &a, State state=StartState)
QDeclarativeSimpleAction (const QDeclarativeSimpleAction &other)
bool reverseEvent () const
void setBinding (QDeclarativeAbstractBinding *binding)
void setProperty (const QDeclarativeProperty &property)
void setValue (const QVariant &value)
QObject * specifiedObject () const
const QString & specifiedProperty () const
const QVariant & value () const
~QDeclarativeSimpleAction ()
Properties
QDeclarativeAbstractBinding::Pointer m_binding
QDeclarativeActionEvent * m_event
QDeclarativeProperty m_property
bool m_reverseEvent
QObject * m_specifiedObject
QString m_specifiedProperty
QVariant m_value
Detailed Description
Definition at line 70 of file qdeclarativestate_p_p.h.
Enumerations
State
enum QDeclarativeSimpleAction::State
Enumerator
StartState
EndState
Definition at line 73 of file qdeclarativestate_p_p.h.
 { StartState, EndState };
Constructors and Destructors
QDeclarativeSimpleAction() [1/2]
QDeclarativeSimpleAction::QDeclarativeSimpleAction (const QDeclarativeAction & a, State state = StartState) inline
Definition at line 74 of file qdeclarativestate_p_p.h.
     {
         m_property = a.property;
         m_specifiedObject = a.specifiedObject;
         m_specifiedProperty = a.specifiedProperty;
         m_event = a.event;
         if (state == StartState) {
             m_value = a.fromValue;
             if (QDeclarativePropertyPrivate::binding(m_property)) {
                 m_binding = QDeclarativeAbstractBinding::getPointer(QDeclarativePropertyPrivate::binding(m_property));
             }
             m_reverseEvent = true;
         } else {
             m_value = a.toValue;
             m_binding = a.toBinding;
             m_reverseEvent = false;
         }
     }
~QDeclarativeSimpleAction()
QDeclarativeSimpleAction::~QDeclarativeSimpleAction () inline
Definition at line 93 of file qdeclarativestate_p_p.h.
     {
     }
QDeclarativeSimpleAction() [2/2]
QDeclarativeSimpleAction::QDeclarativeSimpleAction (const QDeclarativeSimpleAction & other) inline
Definition at line 97 of file qdeclarativestate_p_p.h.
         :  m_property(other.m_property),
         m_value(other.m_value),
         m_binding(QDeclarativeAbstractBinding::getPointer(other.binding())),
         m_specifiedObject(other.m_specifiedObject),
         m_specifiedProperty(other.m_specifiedProperty),
         m_event(other.m_event),
         m_reverseEvent(other.m_reverseEvent)
     {
     }
Functions
binding()
QDeclarativeAbstractBinding* QDeclarativeSimpleAction::binding () const inline
Definition at line 146 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeState::bindingInRevertList(), QDeclarativeState::changeBindingInRevertList(), operator=(), QDeclarativeState::removeAllEntriesFromRevertList(), and QDeclarativeState::removeEntryFromRevertList().
     {
         return m_binding.data();
     }
event()
QDeclarativeActionEvent* QDeclarativeSimpleAction::event () const inline
Definition at line 161 of file qdeclarativestate_p_p.h.
     {
         return m_event;
     }
operator=()
QDeclarativeSimpleAction& QDeclarativeSimpleAction::operator= (const QDeclarativeSimpleAction & other) inline
Definition at line 108 of file qdeclarativestate_p_p.h.
     {
         m_property = other.m_property;
         m_value = other.m_value;
         m_binding = QDeclarativeAbstractBinding::getPointer(other.binding());
         m_specifiedObject = other.m_specifiedObject;
         m_specifiedProperty = other.m_specifiedProperty;
         m_event = other.m_event;
         m_reverseEvent = other.m_reverseEvent;
         return *this;
     }
property()
const QDeclarativeProperty& QDeclarativeSimpleAction::property () const inline
Definition at line 126 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeState::addEntriesToRevertList(), QDeclarativeTransitionManager::complete(), QDeclarativeState::removeAllEntriesFromRevertList(), QDeclarativeState::removeEntryFromRevertList(), and setProperty().
     {
         return m_property;
     }
reverseEvent()
bool QDeclarativeSimpleAction::reverseEvent () const inline
Definition at line 166 of file qdeclarativestate_p_p.h.
     {
         return m_reverseEvent;
     }
setBinding()
void QDeclarativeSimpleAction::setBinding (QDeclarativeAbstractBinding * binding) inline
Definition at line 141 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeState::changeBindingInRevertList().
     {
         m_binding = QDeclarativeAbstractBinding::getPointer(binding);
     }
setProperty()
void QDeclarativeSimpleAction::setProperty (const QDeclarativeProperty & property) inline
Definition at line 121 of file qdeclarativestate_p_p.h.
     {
         m_property = property;
     }
setValue()
void QDeclarativeSimpleAction::setValue (const QVariant & value) inline
Definition at line 131 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeState::changeValueInRevertList().
     {
         m_value = value;
     }
specifiedObject()
QObject* QDeclarativeSimpleAction::specifiedObject () const inline
Definition at line 151 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeState::bindingInRevertList(), QDeclarativeState::changeBindingInRevertList(), QDeclarativeState::changeValueInRevertList(), QDeclarativeState::containsPropertyInRevertList(), and QDeclarativeState::valueInRevertList().
     {
         return m_specifiedObject;
     }
specifiedProperty()
const QString& QDeclarativeSimpleAction::specifiedProperty () const inline
Definition at line 156 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeState::bindingInRevertList(), QDeclarativeState::changeBindingInRevertList(), QDeclarativeState::changeValueInRevertList(), QDeclarativeState::containsPropertyInRevertList(), and QDeclarativeState::valueInRevertList().
     {
         return m_specifiedProperty;
     }
value()
const QVariant& QDeclarativeSimpleAction::value () const inline
Definition at line 136 of file qdeclarativestate_p_p.h.
Referenced by QDeclarativeTransitionManager::complete(), QDeclarativeState::removeAllEntriesFromRevertList(), QDeclarativeState::removeEntryFromRevertList(), setValue(), and QDeclarativeState::valueInRevertList().
     {
         return m_value;
     }
Properties
m_binding
QDeclarativeAbstractBinding::Pointer QDeclarativeSimpleAction::m_binding private
Definition at line 174 of file qdeclarativestate_p_p.h.
Referenced by binding(), operator=(), QDeclarativeSimpleAction(), and setBinding().
m_event
QDeclarativeActionEvent* QDeclarativeSimpleAction::m_event private
Definition at line 177 of file qdeclarativestate_p_p.h.
Referenced by event(), operator=(), and QDeclarativeSimpleAction().
m_property
QDeclarativeProperty QDeclarativeSimpleAction::m_property private
Definition at line 172 of file qdeclarativestate_p_p.h.
Referenced by operator=(), property(), QDeclarativeSimpleAction(), and setProperty().
m_reverseEvent
bool QDeclarativeSimpleAction::m_reverseEvent private
Definition at line 178 of file qdeclarativestate_p_p.h.
Referenced by operator=(), QDeclarativeSimpleAction(), and reverseEvent().
m_specifiedObject
QObject* QDeclarativeSimpleAction::m_specifiedObject private
Definition at line 175 of file qdeclarativestate_p_p.h.
Referenced by operator=(), QDeclarativeSimpleAction(), and specifiedObject().
m_specifiedProperty
QString QDeclarativeSimpleAction::m_specifiedProperty private
Definition at line 176 of file qdeclarativestate_p_p.h.
Referenced by operator=(), QDeclarativeSimpleAction(), and specifiedProperty().
m_value
QVariant QDeclarativeSimpleAction::m_value private
Definition at line 173 of file qdeclarativestate_p_p.h.
Referenced by operator=(), QDeclarativeSimpleAction(), setValue(), and value().
The documentation for this class was generated from the following file:
/src/declarative/util/qdeclarativestate_p_p.h