Qt 4.8: QSqlIndex Class Reference
QSqlIndex Class Reference
The QSqlIndex class provides functions to manipulate and describe database indexes.
#include <qsqlindex.h>
Public Functions
void append (const QSqlField &field)
Appends the field field to the list of indexed fields.
void append (const QSqlField &field, bool desc)
Appends the field field to the list of indexed fields.
QString cursorName () const
Returns the name of the cursor which the index is associated with.
bool isDescending (int i) const
Returns true if field i in the index is sorted in descending order; otherwise returns false.
QString name () const
Returns the name of the index.
QSqlIndex & operator= (const QSqlIndex &other)
Sets the index equal to other.
QSqlIndex (const QString &cursorName=QString(), const QString &name=QString())
Constructs an empty index using the cursor name cursorname and index name name.
QSqlIndex (const QSqlIndex &other)
Constructs a copy of other.
void setCursorName (const QString &cursorName)
Sets the name of the cursor that the index is associated with to cursorName.
void setDescending (int i, bool desc)
If desc is true, field i is sorted in descending order.
void setName (const QString &name)
Sets the name of the index to name.
~QSqlIndex ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QSqlRecord
void append (const QSqlField &field)
Append a copy of field field to the end of the record.
void clear ()
Removes all the record's fields.
void clearValues ()
Clears the value of all fields in the record and sets each field to null.
bool contains (const QString &name) const
Returns true if there is a field in the record called name; otherwise returns false.
int count () const
Returns the number of fields in the record.
QSqlField field (int i) const
Returns the field at position index.
QSqlField field (const QString &name) const
Returns the field called name.
QString fieldName (int i) const
Returns the name of the field at position index.
int indexOf (const QString &name) const
Returns the position of the field called name within the record, or -1 if it cannot be found.
void insert (int pos, const QSqlField &field)
Inserts the field field at position pos in the record.
bool isEmpty () const
Returns true if there are no fields in the record; otherwise returns false.
bool isGenerated (int i) const
Returns true if the record has a field at position index and this field is to be generated (the default); otherwise returns false.
bool isGenerated (const QString &name) const
Returns true if the record has a field called name and this field is to be generated (the default); otherwise returns false.
bool isNull (int i) const
Returns true if the field index is null or if there is no field at position index; otherwise returns false.
bool isNull (const QString &name) const
Returns true if the field called name is null or if there is no field called name; otherwise returns false.
bool operator!= (const QSqlRecord &other) const
Returns true if this object is not identical to other; otherwise returns false.
QSqlRecord & operator= (const QSqlRecord &other)
Sets the record equal to other.
bool operator== (const QSqlRecord &other) const
Returns true if this object is identical to other (i.e., has the same fields in the same order); otherwise returns false.
QSqlRecord ()
Constructs an empty record.
QSqlRecord (const QSqlRecord &other)
Constructs a copy of other.
void remove (int pos)
Removes the field at position pos.
void replace (int pos, const QSqlField &field)
Replaces the field at position pos with the given field.
void setGenerated (const QString &name, bool generated)
Sets the generated flag for the field called name to generated.
void setGenerated (int i, bool generated)
Sets the generated flag for the field index to generated.
void setNull (int i)
Sets the value of field index to null.
void setNull (const QString &name)
Sets the value of the field called name to null.
void setValue (int i, const QVariant &val)
Sets the value of the field at position index to val.
void setValue (const QString &name, const QVariant &val)
Sets the value of the field called name to val.
QVariant value (int i) const
Returns the value of the field located at position index in the record.
QVariant value (const QString &name) const
Returns the value of the field called name in the record.
~QSqlRecord ()
Destroys the object and frees any allocated resources.
Private Functions
QString createField (int i, const QString &prefix, bool verbose) const
Creates a string representing the field number i using prefix prefix.
Properties
QString cursor
QString nm
QList< bool > sorts
Detailed Description
The QSqlIndex class provides functions to manipulate and describe database indexes.
Attention
Module: QtSql
An index refers to a single table or view in a database. Information about the fields that comprise the index can be used to generate SQL statements.
Definition at line 55 of file qsqlindex.h.
Constructors and Destructors
QSqlIndex() [1/2]
QSqlIndex::QSqlIndex (const QString & cursorName = QString(), const QString & name = QString())
Constructs an empty index using the cursor name cursorname and index name name.
Definition at line 70 of file qsqlindex.cpp.
     : cursor(cursorname), nm(name)
 {
 }
QSqlIndex() [2/2]
QSqlIndex::QSqlIndex (const QSqlIndex & other)
Constructs a copy of other.
Definition at line 79 of file qsqlindex.cpp.
     : QSqlRecord(other), cursor(other.cursor), nm(other.nm), sorts(other.sorts)
 {
 }
~QSqlIndex()
QSqlIndex::~QSqlIndex ()
Destroys the object and frees any allocated resources.
Definition at line 101 of file qsqlindex.cpp.
 {
 }
Functions
append() [1/2]
void QSqlIndex::append (const QSqlField & field)
Appends the field field to the list of indexed fields.
The field is appended with an ascending sort order.
Definition at line 129 of file qsqlindex.cpp.
Referenced by QDB2Driver::primaryIndex(), QIBaseDriver::primaryIndex(), QOCIDriver::primaryIndex(), QSQLite2Driver::primaryIndex(), QTDSDriver::primaryIndex(), QMYSQLDriver::primaryIndex(), QODBCDriver::primaryIndex(), QPSQLDriver::primaryIndex(), qExtractSecurityPolicyFromString(), and qGetTableInfo().
 {
     append(field, false);
 }
append() [2/2]
void QSqlIndex::append (const QSqlField & field, bool desc)
Appends the field field to the list of indexed fields.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The field is appended with an ascending sort order, unless desc is true.
Definition at line 145 of file qsqlindex.cpp.
 {
     sorts.append(desc);
     QSqlRecord::append(field);
 }
createField()
QString QSqlIndex::createField (int i, const QString & prefix, bool verbose) const private
Creates a string representing the field number i using prefix prefix.
Warning
This function is not part of the public interface.
If verbose is true, ASC or DESC is included in the field description if the field is sorted in ASCending or DESCending order.
Definition at line 240 of file qsqlindex.cpp.
Referenced by setDescending().
 {
     QString f;
     if (!prefix.isEmpty())
         f += prefix + QLatin1Char('.');
     f += field(i).name();
     if (verbose)
         f += QLatin1Char(' ') + QString((isDescending(i)
                     ? QLatin1String("DESC") : QLatin1String("ASC")));
     return f;
 }
cursorName()
QString QSqlIndex::cursorName () const inline
Returns the name of the cursor which the index is associated with.
Definition at line 63 of file qsqlindex.h.
Referenced by setCursorName().
 { return cursor; }
isDescending()
bool QSqlIndex::isDescending (int i) const
Returns true if field i in the index is sorted in descending order; otherwise returns false.
Definition at line 157 of file qsqlindex.cpp.
Referenced by createField().
 {
     if (i >= 0 && i < sorts.size())
         return sorts[i];
     return false;
 }
name()
QString QSqlIndex::name () const inline
Returns the name of the index.
Definition at line 65 of file qsqlindex.h.
Referenced by setName().
 { return nm; }
operator=()
QSqlIndex & QSqlIndex::operator= (const QSqlIndex & other)
Sets the index equal to other.
Definition at line 88 of file qsqlindex.cpp.
 {
     cursor = other.cursor;
     nm = other.nm;
     sorts = other.sorts;
     QSqlRecord::operator=(other);
     return *this;
 }
setCursorName()
void QSqlIndex::setCursorName (const QString & cursorName)
Sets the name of the cursor that the index is associated with to cursorName.
Definition at line 266 of file qsqlindex.cpp.
Referenced by QMYSQLDriver::primaryIndex().
 {
     cursor = cursorName;
 }
setDescending()
void QSqlIndex::setDescending (int i, bool desc)
If desc is true, field i is sorted in descending order.
Otherwise, field i is sorted in ascending order (the default). If the field does not exist, nothing happens.
Definition at line 170 of file qsqlindex.cpp.
 {
     if (i >= 0 && i < sorts.size())
         sorts[i] = desc;
 }
setName()
void QSqlIndex::setName (const QString & name)
Sets the name of the index to name.
Definition at line 110 of file qsqlindex.cpp.
Referenced by QDB2Driver::primaryIndex(), QIBaseDriver::primaryIndex(), QOCIDriver::primaryIndex(), QTDSDriver::primaryIndex(), QMYSQLDriver::primaryIndex(), QODBCDriver::primaryIndex(), and QPSQLDriver::primaryIndex().
 {
     nm = name;
 }
Properties
cursor
QString QSqlIndex::cursor private
Definition at line 83 of file qsqlindex.h.
Referenced by operator=(), and setCursorName().
nm
QString QSqlIndex::nm private
Definition at line 84 of file qsqlindex.h.
Referenced by operator=(), and setName().
sorts
QList<bool> QSqlIndex::sorts private
Definition at line 85 of file qsqlindex.h.
Referenced by append(), isDescending(), operator=(), and setDescending().
The documentation for this class was generated from the following files:
/src/sql/kernel/qsqlindex.h
/src/sql/kernel/qsqlindex.cpp