Qt 4.8: QLayoutStyleInfo Class Reference
QLayoutStyleInfo Class Reference
#include <qgraphicslayout_p.h>
Public Functions
qreal defaultSpacing (Qt::Orientation o) const
void invalidate ()
bool operator!= (const QLayoutStyleInfo &other)
bool operator== (const QLayoutStyleInfo &other)
qreal perItemSpacing (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation) const
QLayoutStyleInfo ()
QLayoutStyleInfo (QStyle *style, QWidget *widget)
void setDefaultSpacing (Qt::Orientation o, qreal spacing)
QStyle * style () const
QWidget * widget () const
Properties
qreal m_defaultSpacing [2]
QStyle * m_style
QStyleOption m_styleOption
bool m_valid
QWidget * m_widget
Detailed Description
Definition at line 82 of file qgraphicslayout_p.h.
Constructors and Destructors
QLayoutStyleInfo() [1/2]
QLayoutStyleInfo::QLayoutStyleInfo () inline
Definition at line 85 of file qgraphicslayout_p.h.
 { invalidate(); }
QLayoutStyleInfo() [2/2]
QLayoutStyleInfo::QLayoutStyleInfo (QStyle * style, QWidget * widget) inline
Definition at line 86 of file qgraphicslayout_p.h.
         : m_valid(true), m_style(style), m_widget(widget)
     {
         Q_ASSERT(style);
         if (widget) //###
             m_styleOption.initFrom(widget);
         m_defaultSpacing[0] = style->pixelMetric(QStyle::PM_LayoutHorizontalSpacing);
         m_defaultSpacing[1] = style->pixelMetric(QStyle::PM_LayoutVerticalSpacing);
     }
Functions
defaultSpacing()
qreal QLayoutStyleInfo::defaultSpacing (Qt::Orientation o) const inline
Definition at line 111 of file qgraphicslayout_p.h.
Referenced by AnchorData::refreshSizeHints().
{
         return m_defaultSpacing[o - 1];
     }
invalidate()
void QLayoutStyleInfo::invalidate () inline
Definition at line 96 of file qgraphicslayout_p.h.
Referenced by QLayoutStyleInfo().
 { m_valid = false; m_style = 0; m_widget = 0; }
operator!=()
bool QLayoutStyleInfo::operator!= (const QLayoutStyleInfo & other) inline
Definition at line 103 of file qgraphicslayout_p.h.
         { return !(*this == other); }
operator==()
bool QLayoutStyleInfo::operator== (const QLayoutStyleInfo & other) inline
Definition at line 101 of file qgraphicslayout_p.h.
         { return m_style == other.m_style && m_widget == other.m_widget; }
perItemSpacing()
qreal QLayoutStyleInfo::perItemSpacing (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation) const inline
Definition at line 115 of file qgraphicslayout_p.h.
Referenced by AnchorData::refreshSizeHints().
     {
         Q_ASSERT(style());
         return style()->layoutSpacing(control1, control2, orientation, &m_styleOption, widget());
     }
setDefaultSpacing()
void QLayoutStyleInfo::setDefaultSpacing (Qt::Orientation o, qreal spacing) inline
Definition at line 106 of file qgraphicslayout_p.h.
Referenced by QGraphicsAnchorLayoutPrivate::styleInfo().
{
         if (spacing >= 0)
             m_defaultSpacing[o - 1] = spacing;
     }
style()
QStyle* QLayoutStyleInfo::style () const inline
Definition at line 98 of file qgraphicslayout_p.h.
Referenced by QGridLayoutEngine::fillRowData(), perItemSpacing(), and QGridLayoutEngine::spacing().
 { return m_style; }
widget()
QWidget* QLayoutStyleInfo::widget () const inline
Definition at line 99 of file qgraphicslayout_p.h.
Referenced by QGridLayoutEngine::fillRowData(), perItemSpacing(), and QGridLayoutEngine::spacing().
 { return m_widget; }
Properties
m_defaultSpacing
qreal QLayoutStyleInfo::m_defaultSpacing[2] private
Definition at line 127 of file qgraphicslayout_p.h.
Referenced by defaultSpacing(), QLayoutStyleInfo(), and setDefaultSpacing().
m_style
QStyle* QLayoutStyleInfo::m_style private
Definition at line 124 of file qgraphicslayout_p.h.
Referenced by invalidate(), operator==(), and style().
m_styleOption
QStyleOption QLayoutStyleInfo::m_styleOption private
Definition at line 126 of file qgraphicslayout_p.h.
Referenced by perItemSpacing(), and QLayoutStyleInfo().
m_valid
bool QLayoutStyleInfo::m_valid private
Definition at line 123 of file qgraphicslayout_p.h.
Referenced by invalidate().
m_widget
QWidget* QLayoutStyleInfo::m_widget private
Definition at line 125 of file qgraphicslayout_p.h.
Referenced by invalidate(), operator==(), and widget().
The documentation for this class was generated from the following file:
/src/gui/graphicsview/qgraphicslayout_p.h