Qt 4.8: QMacInputContext Class Reference
QMacInputContext Class Reference
#include <qmacinputcontext_p.h>
Public Functions
virtual QString identifierName ()
This function must be implemented in any subclasses to return the identifier name of the input method.
virtual bool isComposing () const
This function indicates whether InputMethodStart event had been sent to the current focus widget.
virtual QString language ()
This function must be implemented in any subclasses to return a language code (e.
QWidget * lastFocusWidget () const
EventRef lastKeydownEvent ()
QMacInputContext (QObject *parent=0)
virtual void reset ()
This function can be reimplemented in a subclass to reset the state of the input method.
virtual void setFocusWidget (QWidget *w)
Sets the widget that has an input focus for this input context.
void setLastKeydownEvent (EventRef)
virtual ~QMacInputContext ()
Public Functions inherited from QInputContext
virtual QList< QAction * > actions ()
This is a preliminary interface for Qt 4.
virtual bool filterEvent (const QEvent *event)
This function can be reimplemented in a subclass to filter input events.
QWidget * focusWidget () const
Returns the widget that has an input focus for this input context.
virtual QFont font () const
Returns the font of the current input widget.
QInputContext (QObject *parent=0)
Constructs an input context with the given parent.
void sendEvent (const QInputMethodEvent &event)
Sends an input method event specified by event to the current focus widget.
QTextFormat standardFormat (StandardFormat s) const
Returns a QTextFormat object that specifies the format for component s.
virtual void update ()
This virtual function is called when a state in the focus widget has changed.
virtual void widgetDestroyed (QWidget *w)
This virtual function is called when the specified widget is destroyed.
virtual bool x11FilterEvent (QWidget *keywidget, XEvent *event)
This function may be overridden only if input method is depending on X11 and you need raw XEvent.
virtual ~QInputContext ()
Destroys the input context.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static void cleanup ()
static OSStatus globalEventProcessor (EventHandlerCallRef, EventRef, void *)
static void initialize ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
void mouseHandler (int pos, QMouseEvent *)
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void createTextDocument ()
Properties
bool composing
QString currentText
EventRef keydownEvent
QWidget * lastFocusWid
bool recursionGuard
TSMDocumentID textDocument
Additional Inherited Members
Public Types inherited from QInputContext
enum StandardFormat { PreeditFormat, SelectionFormat }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 62 of file qmacinputcontext_p.h.
Constructors and Destructors
QMacInputContext()
QMacInputContext::QMacInputContext (QObject * parent = 0) explicit
Definition at line 61 of file qmacinputcontext_mac.cpp.
     : QInputContext(parent), composing(false), recursionGuard(false), textDocument(0),
       keydownEvent(0), lastFocusWid(0)
 {
 //    createTextDocument();
 }
~QMacInputContext()
QMacInputContext::~QMacInputContext () virtual
Definition at line 68 of file qmacinputcontext_mac.cpp.
 {
 #ifndef QT_MAC_USE_COCOA
     if(textDocument)
         DeleteTSMDocument(textDocument);
 #endif
 }
Functions
cleanup()
void QMacInputContext::cleanup () static
Definition at line 183 of file qmacinputcontext_mac.cpp.
Referenced by qt_cleanup().
 {
 #ifndef QT_MAC_USE_COCOA
     if(input_proc_handler) {
         RemoveEventHandler(input_proc_handler);
         input_proc_handler = 0;
     }
     if(input_proc_handlerUPP) {
         DisposeEventHandlerUPP(input_proc_handlerUPP);
         input_proc_handlerUPP = 0;
     }
 #endif
 }
createTextDocument()
void QMacInputContext::createTextDocument () private
Definition at line 77 of file qmacinputcontext_mac.cpp.
Referenced by reset(), and setFocusWidget().
 {
 #ifndef QT_MAC_USE_COCOA
     if(!textDocument) {
         InterfaceTypeList itl = { kUnicodeDocument };
         NewTSMDocument(1, itl, &textDocument, SRefCon(this));
     }
 #endif
 }
globalEventProcessor()
OSStatus QMacInputContext::globalEventProcessor (EventHandlerCallRef , EventRef event, void *) static
Definition at line 208 of file qmacinputcontext_mac.cpp.
Referenced by initialize().
 {
 #ifndef QT_MAC_USE_COCOA
     QScopedLoopLevelCounter loopLevelCounter(QApplicationPrivate::instance()->threadData);
     SRefCon refcon = 0;
     GetEventParameter(event, kEventParamTextInputSendRefCon, typeRefCon, 0,
                       sizeof(refcon), 0, &refcon);
     QMacInputContext *context = reinterpret_cast<QMacInputContext*>(refcon);
     bool handled_event=true;
     UInt32 ekind = GetEventKind(event), eclass = GetEventClass(event);
     switch(eclass) {
     case kEventClassTextInput: {
         handled_event = false;
         QWidget *widget = QApplicationPrivate::focus_widget;
         bool canCompose = widget && (!context || widget->inputContext() == context)
                 && !(widget->inputMethodHints() & Qt::ImhDigitsOnly
                 || widget->inputMethodHints() & Qt::ImhFormattedNumbersOnly
                 || widget->inputMethodHints() & Qt::ImhHiddenText);
         if(!canCompose) {
             handled_event = false;
         } else if(ekind == kEventTextInputOffsetToPos) {
             if(!widget->testAttribute(Qt::WA_InputMethodEnabled)) {
                 handled_event = false;
                 break;
             }
             QRect mr(widget->inputMethodQuery(Qt::ImMicroFocus).toRect());
             QPoint mp(widget->mapToGlobal(QPoint(mr.topLeft())));
             Point pt;
             pt.h = mp.x();
             pt.v = mp.y() + mr.height();
             SetEventParameter(event, kEventParamTextInputReplyPoint, typeQDPoint,
                               sizeof(pt), &pt);
             handled_event = true;
         } else if(ekind == kEventTextInputUpdateActiveInputArea) {
             if(!widget->testAttribute(Qt::WA_InputMethodEnabled)) {
                 handled_event = false;
                 break;
             }
             if (context->recursionGuard)
                 break;
             ByteCount unilen = 0;
             GetEventParameter(event, kEventParamTextInputSendText, typeUnicodeText,
                               0, 0, &unilen, 0);
             UniChar *unicode = (UniChar*)NewPtr(unilen);
             GetEventParameter(event, kEventParamTextInputSendText, typeUnicodeText,
                               0, unilen, 0, unicode);
             QString text((QChar*)unicode, unilen / sizeof(UniChar));
             DisposePtr((char*)unicode);
             ByteCount fixed_length = 0;
             GetEventParameter(event, kEventParamTextInputSendFixLen, typeByteCount, 0,
                               sizeof(fixed_length), 0, &fixed_length);
             if(fixed_length == ULONG_MAX || fixed_length == unilen) {
                 QInputMethodEvent e;
                 e.setCommitString(text);
                 context->currentText = QString();
                 qt_sendSpontaneousEvent(context->focusWidget(), &e);
                 handled_event = true;
                 context->reset();
             } else {
                 ByteCount rngSize = 0;
                 OSStatus err = GetEventParameter(event, kEventParamTextInputSendHiliteRng, typeTextRangeArray, 0,
                                                  0, &rngSize, 0);
                 QVarLengthArray<TextRangeArray> highlight(rngSize);
                 if (noErr == err) {
                     err = GetEventParameter(event, kEventParamTextInputSendHiliteRng, typeTextRangeArray, 0,
                                             rngSize, &rngSize, highlight.data());
                 }
                 context->composing = true;
                 if(fixed_length > 0) {
                     const int qFixedLength = fixed_length / sizeof(UniChar);
                     QList<QInputMethodEvent::Attribute> attrs;
                     attrs << QInputMethodEvent::Attribute(QInputMethodEvent::TextFormat,
                                                           qFixedLength, text.length()-qFixedLength,
                                                           qt_mac_compose_format());
                     QInputMethodEvent e(text, attrs);
                     context->currentText = text;
                     e.setCommitString(text.left(qFixedLength), 0, qFixedLength);
                     qt_sendSpontaneousEvent(widget, &e);
                     handled_event = true;
                 } else {
                     /* Apple's enums that they have removed from Tiger :(
                     enum {
                         kCaretPosition = 1,
                         kRawText = 2,
                         kSelectedRawText = 3,
                         kConvertedText = 4,
                         kSelectedConvertedText = 5,
                         kBlockFillText = 6,
                         kOutlineText = 7,
                         kSelectedText = 8
                     };
                     */
 #ifndef kConvertedText
 #define kConvertedText 4
 #endif
 #ifndef kCaretPosition
 #define kCaretPosition 1
 #endif
                     QList<QInputMethodEvent::Attribute> attrs;
                     if (!highlight.isEmpty()) {
                         TextRangeArray *data = highlight.data();
                         for (int i = 0; i < data->fNumOfRanges; ++i) {
                             int start = data->fRange[i].fStart / sizeof(UniChar);
                             int len = (data->fRange[i].fEnd - data->fRange[i].fStart) / sizeof(UniChar);
                             if (data->fRange[i].fHiliteStyle == kCaretPosition) {
                                 attrs << QInputMethodEvent::Attribute(QInputMethodEvent::Cursor, start, 0, QVariant());
                                 continue;
                             }
                             QTextCharFormat format;
                             format.setFontUnderline(true);
                             if (data->fRange[i].fHiliteStyle == kConvertedText)
                                 format.setUnderlineColor(Qt::gray);
                             else
                                 format.setUnderlineColor(Qt::black);
                             attrs << QInputMethodEvent::Attribute(QInputMethodEvent::TextFormat, start, len, format);
                         }
                     } else {
                         attrs << QInputMethodEvent::Attribute(QInputMethodEvent::TextFormat,
                                 0, text.length(), qt_mac_compose_format());
                     }
                     context->currentText = text;
                     QInputMethodEvent e(text, attrs);
                     qt_sendSpontaneousEvent(widget, &e);
                     handled_event = true;
                 }
             }
 #if 0
             if(!context->composing)
                 handled_event = false;
 #endif
             extern bool qt_mac_eat_unicode_key; //qapplication_mac.cpp
             qt_mac_eat_unicode_key = handled_event;
         } else if(ekind == kEventTextInputUnicodeForKeyEvent) {
             EventRef key_ev = 0;
             GetEventParameter(event, kEventParamTextInputSendKeyboardEvent, typeEventRef, 0,
                               sizeof(key_ev), 0, &key_ev);
             QString text;
             ByteCount unilen = 0;
             if(GetEventParameter(key_ev, kEventParamKeyUnicodes, typeUnicodeText, 0, 0, &unilen, 0) == noErr) {
                 UniChar *unicode = (UniChar*)NewPtr(unilen);
                 GetEventParameter(key_ev, kEventParamKeyUnicodes, typeUnicodeText, 0, unilen, 0, unicode);
                 text = QString((QChar*)unicode, unilen / sizeof(UniChar));
                 DisposePtr((char*)unicode);
             }
             unsigned char chr = 0;
             GetEventParameter(key_ev, kEventParamKeyMacCharCodes, typeChar, 0, sizeof(chr), 0, &chr);
             if(!chr || chr >= 128 || (text.length() > 0 && (text.length() > 1 || text.at(0) != QLatin1Char(chr))))
                 handled_event = !widget->testAttribute(Qt::WA_InputMethodEnabled);
             QMacInputContext *context = qobject_cast<QMacInputContext*>(qApp->inputContext());
             if (context && context->lastKeydownEvent()) {
                 qt_keymapper_private()->translateKeyEvent(widget, 0, context->lastKeydownEvent(),
                                                           0, false);
                 context->setLastKeydownEvent(0);
             }
         }
         break; }
     default:
         break;
     }
     if(!handled_event) //let the event go through
         return eventNotHandledErr;
 #else
     Q_UNUSED(event);
 #endif
     return noErr; //we eat the event
 }
identifierName()
virtual QString QMacInputContext::identifierName () inline virtual
This function must be implemented in any subclasses to return the identifier name of the input method.
Return value is the name to identify and specify input methods for the input method switching mechanism and so on. The name has to be consistent with QInputContextPlugin::keys(). The name has to consist of ASCII characters only.
There are two different names with different responsibility in the input method domain. This function returns one of them. Another name is called 'display name' that stands for the name for endusers appeared in a menu and so on.
See also
QInputContextPlugin::keys(), QInputContextPlugin::displayName()
Implements QInputContext.
Definition at line 72 of file qmacinputcontext_p.h.
 { return QLatin1String("mac"); }
initialize()
void QMacInputContext::initialize () static
Definition at line 170 of file qmacinputcontext_mac.cpp.
Referenced by qt_init().
 {
 #ifndef QT_MAC_USE_COCOA
     if(!input_proc_handler) {
         input_proc_handlerUPP = NewEventHandlerUPP(QMacInputContext::globalEventProcessor);
         InstallEventHandler(GetApplicationEventTarget(), input_proc_handlerUPP,
                             GetEventTypeCount(input_events), input_events,
                             0, &input_proc_handler);
     }
 #endif
 }
isComposing()
bool QMacInputContext::isComposing () const virtual
This function indicates whether InputMethodStart event had been sent to the current focus widget.
It is ensured that an input context can send InputMethodCompose or InputMethodEnd event safely if this function returned true.
The state is automatically being tracked through sendEvent().
See also
sendEvent()
Implements QInputContext.
Definition at line 138 of file qmacinputcontext_mac.cpp.
 {
     return composing;
 }
language()
QString QMacInputContext::language () virtual
This function must be implemented in any subclasses to return a language code (e.
g. "zh_CN", "zh_TW", "zh_HK", "ja", "ko", ...) of the input context. If the input context can handle multiple languages, return the currently used one. The name has to be consistent with QInputContextPlugin::language().
This information will be used by language tagging feature in QInputMethodEvent. It is required to distinguish unified han characters correctly. It enables proper font and character code handling. Suppose CJK-awared multilingual web browser (that automatically modifies fonts in CJK-mixed text) and XML editor (that automatically inserts lang attr).
Implements QInputContext.
Definition at line 88 of file qmacinputcontext_mac.cpp.
 {
     return QString();
 }
lastFocusWidget()
QWidget* QMacInputContext::lastFocusWidget () const inline
Definition at line 85 of file qmacinputcontext_p.h.
 { return lastFocusWid; }
lastKeydownEvent()
EventRef QMacInputContext::lastKeydownEvent () inline
Definition at line 83 of file qmacinputcontext_p.h.
Referenced by globalEventProcessor().
 { return keydownEvent; }
mouseHandler()
void QMacInputContext::mouseHandler (int x, QMouseEvent * event) protected virtual
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
You can use the function to implement mouse-oriented user interface such as text selection or popup menu for candidate selection.
The x parameter is the offset within the string that was sent with the InputMethodCompose event. The alteration boundary of x is ensured as character boundary of preedit string accurately.
The event parameter is the event that was sent to the editor widget. The event type is QEvent::MouseButtonPress, QEvent::MouseButtonRelease, QEvent::MouseButtonDblClick or QEvent::MouseMove. The event's button and state indicate the kind of operation that was performed.
Reimplemented from QInputContext.
Definition at line 94 of file qmacinputcontext_mac.cpp.
 {
 #ifndef QT_MAC_USE_COCOA
     if(e->type() != QEvent::MouseButtonPress)
         return;
     if (!composing)
         return;
     if (pos < 0 || pos > currentText.length())
         reset();
     // ##### handle mouse position
 #else
     Q_UNUSED(pos);
     Q_UNUSED(e);
 #endif
 }
reset()
void QMacInputContext::reset () virtual
This function can be reimplemented in a subclass to reset the state of the input method.
This function is called by several widgets to reset input state. For example, a text widget call this function before inserting a text to make widget ready to accept a text.
Default implementation is sufficient for simple input method. You can override this function to reset external input method engines in complex input method. In the case, call QInputContext::reset() to ensure proper termination of inputting.
In a reimplementation of reset(), you must not send any QInputMethodEvent containing preedit text. You can only commit string and attributes; otherwise, you risk breaking input state consistency.
Implements QInputContext.
Definition at line 120 of file qmacinputcontext_mac.cpp.
Referenced by globalEventProcessor(), and mouseHandler().
 {
     if (recursionGuard)
         return;
     if (!currentText.isEmpty()){
         QInputMethodEvent e;
         e.setCommitString(currentText);
         qt_sendSpontaneousEvent(focusWidget(), &e);
         currentText = QString();
     }
     recursionGuard = true;
     createTextDocument();
     composing = false;
     ActivateTSMDocument(textDocument);
     FixTSMDocument(textDocument);
     recursionGuard = false;
 }
setFocusWidget()
void QMacInputContext::setFocusWidget (QWidget * widget) virtual
Sets the widget that has an input focus for this input context.
Warning
Ordinary input methods must not call this function directly.
See also
focusWidget()
Reimplemented from QInputContext.
Definition at line 144 of file qmacinputcontext_mac.cpp.
 {
     if (!w)
         lastFocusWid = focusWidget();
     createTextDocument();
 #ifndef QT_MAC_USE_COCOA
     if(w)
         ActivateTSMDocument(textDocument);
     else
         DeactivateTSMDocument(textDocument);
 #endif
     QInputContext::setFocusWidget(w);
 }
setLastKeydownEvent()
void QMacInputContext::setLastKeydownEvent (EventRef event)
Definition at line 197 of file qmacinputcontext_mac.cpp.
Referenced by globalEventProcessor(), and QKeyMapperPrivate::translateKeyEvent().
 {
     EventRef tmpEvent = keydownEvent;
     keydownEvent = event;
     if (keydownEvent)
         RetainEvent(keydownEvent);
     if (tmpEvent)
         ReleaseEvent(tmpEvent);
 }
Properties
composing
bool QMacInputContext::composing private
Definition at line 89 of file qmacinputcontext_p.h.
Referenced by globalEventProcessor(), isComposing(), mouseHandler(), and reset().
currentText
QString QMacInputContext::currentText private
Definition at line 92 of file qmacinputcontext_p.h.
Referenced by globalEventProcessor(), mouseHandler(), and reset().
keydownEvent
EventRef QMacInputContext::keydownEvent private
Definition at line 93 of file qmacinputcontext_p.h.
Referenced by setLastKeydownEvent().
lastFocusWid
QWidget* QMacInputContext::lastFocusWid private
Definition at line 94 of file qmacinputcontext_p.h.
Referenced by setFocusWidget().
recursionGuard
bool QMacInputContext::recursionGuard private
Definition at line 90 of file qmacinputcontext_p.h.
Referenced by globalEventProcessor(), and reset().
textDocument
TSMDocumentID QMacInputContext::textDocument private
Definition at line 91 of file qmacinputcontext_p.h.
Referenced by createTextDocument(), reset(), setFocusWidget(), and ~QMacInputContext().
The documentation for this class was generated from the following files:
/src/gui/inputmethod/qmacinputcontext_p.h
/src/gui/inputmethod/qmacinputcontext_mac.cpp