Qt 4.8: QDecoration Class Reference
QDecoration Class Reference abstract
The QDecoration class is a base class for window decorations in Qt for Embedded Linux.
#include <qdecoration_qws.h>
Public Types
enum DecorationRegion {
None = 0x0000000000, All = 0x7fffffff, TopLeft = 0x0000000001, Top = 0x0000000002,
TopRight = 0x0000000004, Left = 0x0000000008, Right = 0x0000000010, BottomLeft = 0x0000000020,
Bottom = 0x0000000040, BottomRight = 0x0000000080, Borders = 0x00000000ff, Menu = 0x0000000100,
Title = 0x0000000200, Help = 0x0000000400, Minimize = 0x0000000800, Maximize = 0x0000001000,
Normalize = 0x0000002000, Close = 0x0000004000, Move = 0x0000008000, Resize = 0x0000010000
}
This enum describes the various regions of the window decoration.
enum DecorationState { Normal = 0x04, Disabled = 0x08, Hover = 0x01, Pressed = 0x02 }
This enum describes the various states of a decoration region.
Public Functions
virtual void buildSysMenu (QWidget *widget, QMenu *menu)
Builds the system menu for the given top level widget, adding Restore, Move, Size, Minimize, Maximize and Close actions to the given menu.
void menuTriggered (QWidget *widget, QAction *action)
This function is called whenever an action in a top level widget's menu is triggered, and simply calls the regionClicked() function passing the widget and action parameters as arguments.
virtual bool paint (QPainter *p, const QWidget *w, int decorationRegion=All, DecorationState state=Normal)=0
Implement this function to paint the border and title decoration for the specified top level widget using the given painter and decoration state.
QDecoration ()
Constructs a decoration object.
virtual QRegion region (const QWidget *w, const QRect &rect, int decorationRegion=All)=0
Implement this function to return the region specified by decorationRegion for the given top level widget.
QRegion region (const QWidget *w, int decorationRegion=All)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
virtual int regionAt (const QWidget *w, const QPoint &point)
Returns the type of the first region of the specified top level widget containing the given point.
virtual void regionClicked (QWidget *widget, int region)
Handles the event that the specified region in the given top level widget is activated by a single click (the region parameter is described using the DecorationRegion enum).
virtual void regionDoubleClicked (QWidget *widget, int region)
Handles the event that the specified region in the given top level widget is activated by a double click (the region parameter is described using the DecorationRegion enum).
virtual ~QDecoration ()
Destroys this decoration object.
Static Public Functions
static void startMove (QWidget *widget)
Starts to move the given top level widget by making its Title region active and grabbing the mouse input.
static void startResize (QWidget *widget)
Starts to resize the given top level widget by making its BottomRight region active and grabbing the mouse input.
Detailed Description
The QDecoration class is a base class for window decorations in Qt for Embedded Linux.
Note that this class is non-portable and only available in Qt for Embedded Linux.
Qt for Embedded Linux provides window management of top level windows and several ready made decorations (i.e., Default, Styled and Windows). Custom decorations can be implemented by subclassing the QDecoration class and creating a decoration plugin (derived from QDecorationPlugin). The default implementation of the QDecorationFactory class will automatically detect the plugin, and load the decoration into the application at run-time using Qt's How to Create Qt Plugins. To actually apply a decoration, use the QApplication::qwsSetDecoration() function.
When creating a custom decoration, implement the paint() function to paint the border and title decoration, and the region() function to return the regions the decoration occupies. Reimplement the regionClicked() and regionDoubleClicked() functions to respond to mouse clicks (the default implementations responds to (single) clicks on items in a widget's system menu and double clicks on a widget's title).
QDecoration provides the DecorationRegion enum that describes the various regions of the window decoration, and the regionAt() function to determine the region containing a given point. The QDecoration class also provides the DecorationState enum describing the state of a given region, e.g. whether it is active or not.
In addition, it is possible to build the system menu for a given top level widget using the buildSysMenu() function; whenever an action in this menu is triggered, the menuTriggered() function is called automatically.
Finally, the QDecoration class provides a couple of static functions, startMove() and startResize(), which start a move or resize action by making the appropriate decoration region active and grabbing the mouse input.
See also
QDecorationFactory, QDecorationPlugin, {Qt for Embedded Linux Architecture}
Definition at line 71 of file qdecoration_qws.h.
Enumerations
DecorationRegion
enum QDecoration::DecorationRegion
This enum describes the various regions of the window decoration.
All The entire region used by the window decoration.
Top The top border used to vertically resize the window.
Bottom The bottom border used to vertically resize the window.
Left The left border used to horizontally resize the window.
Right The right border used to horizontally resize the window.
TopLeft The top-left corner of the window used to resize the window both horizontally and vertically.
TopRight The top-right corner of the window used to resize the window both horizontally and vertically.
BottomLeft The bottom-left corner of the window used to resize the window both horizontally and vertically.
BottomRight The bottom-right corner of the window used to resize the window both horizontally and vertically.
Borders All the regions used to describe the window's borders.
Title The region containing the window title, used to move the window by dragging with the mouse cursor.
Close The region occupied by the close button. Clicking in this region closes the window.
Minimize The region occupied by the minimize button. Clicking in this region minimizes the window.
Maximize The region occupied by the maximize button. Clicking in this region maximizes the window.
Normalize The region occupied by a button used to restore a window's normal size. Clicking in this region restores a maximized window to its previous size. The region used for this button is often also the Maximize region.
Menu The region occupied by the window's menu button. Clicking in this region opens the window operations (system) menu.
Help The region occupied by the window's help button. Clicking in this region causes the context-sensitive help function to be enabled.
Resize The region used to resize the window.
Move The region used to move the window.
None No region.
See also
region(), regionAt(), DecorationState
Enumerator
None
All
TopLeft
Top
TopRight
Left
Right
BottomLeft
Bottom
BottomRight
Borders
Menu
Title
Minimize
Maximize
Normalize
Close
Move
Resize
Definition at line 87 of file qdecoration_qws.h.
{
         None        = 0x0000000000, All      = 0x7fffffff,
         TopLeft     = 0x0000000001, Top      = 0x0000000002, TopRight    = 0x0000000004,
         Left        = 0x0000000008,                          Right       = 0x0000000010,
         BottomLeft  = 0x0000000020, Bottom   = 0x0000000040, BottomRight = 0x0000000080,
         Borders     = 0x00000000ff,
         Menu        = 0x0000000100, Title    = 0x0000000200, Help        = 0x0000000400,
         Minimize    = 0x0000000800, Maximize = 0x0000001000, Normalize   = 0x0000002000,
         Close       = 0x0000004000, Move     = 0x0000008000, Resize      = 0x0000010000
     };
DecorationState
enum QDecoration::DecorationState
This enum describes the various states of a decoration region.
Normal The region is active
Disabled The region is inactive.
Hover The cursor is hovering over the region.
Pressed The region is pressed.
See also
paint(), DecorationRegion
Enumerator
Normal
Disabled
Hover
Pressed
Definition at line 98 of file qdecoration_qws.h.
 { Normal = 0x04, Disabled = 0x08, Hover = 0x01, Pressed = 0x02 };
Constructors and Destructors
QDecoration()
QDecoration::QDecoration () inline
Constructs a decoration object.
Definition at line 74 of file qdecoration_qws.h.
 {}
~QDecoration()
QDecoration::~QDecoration () inline virtual
Destroys this decoration object.
Definition at line 75 of file qdecoration_qws.h.
 {}
Functions
buildSysMenu()
void QDecoration::buildSysMenu (QWidget * widget, QMenu * menu) virtual
Builds the system menu for the given top level widget, adding Restore, Move, Size, Minimize, Maximize and Close actions to the given menu.
See also
menuTriggered()
Definition at line 276 of file qdecoration_qws.cpp.
 {
     QDecorationAction *act = new QDecorationAction(QLatin1String("Restore"),
                                                    menu, Maximize);
     act->setEnabled(widget->windowState() & Qt::WindowMaximized);
     menu->addAction(act);
     act = new QDecorationAction(QLatin1String("Move"), menu, Move);
     act->setEnabled(!(widget->windowState() & Qt::WindowMaximized));
     menu->addAction(act);
     menu->addAction(new QDecorationAction(QLatin1String("Size"), menu, Resize));
     act = new QDecorationAction(QLatin1String("Minimize"), menu, Minimize);
     menu->addAction(act);
     act = new QDecorationAction(QLatin1String("Maximize"), menu, Maximize);
     act->setDisabled(widget->windowState() & Qt::WindowMaximized);
     menu->addAction(act);
     menu->addSeparator();
     menu->addAction(new QDecorationAction(QLatin1String("Close"), menu, Close));
 }
menuTriggered()
void QDecoration::menuTriggered (QWidget * widget, QAction * action)
This function is called whenever an action in a top level widget's menu is triggered, and simply calls the regionClicked() function passing the widget and action parameters as arguments.
See also
buildSysMenu()
Definition at line 302 of file qdecoration_qws.cpp.
 {
     QDecorationAction *decAction = static_cast<QDecorationAction *>(action);
     regionClicked(widget, decAction->reg);
 }
paint()
bool QDecoration::paint (QPainter * painter, const QWidget * widget, int decorationRegion = All, DecorationState state = Normal) pure virtual
Implement this function to paint the border and title decoration for the specified top level widget using the given painter and decoration state.
The specified decorationRegion is a bitmask of the values described by the DecorationRegion enum.
Note that Qt for Embedded Linux expects this function to return true if any of the widget's decorations are repainted; otherwise it should return false.
See also
region()
Implemented in QDecorationDefault, QDecorationStyled, and QDecorationWindows.
Referenced by QWidgetBackingStore::removeDirtyWidget().
region() [1/2]
QRegion QDecoration::region (const QWidget * widget, const QRect & rectangle, int decorationRegion = All) pure virtual
Implement this function to return the region specified by decorationRegion for the given top level widget.
The rectangle parameter specifies the rectangle the decoration is wrapped around. The decorationRegion is a bitmask of the values described by the DecorationRegion enum.
See also
regionAt(), paint()
Implemented in QDecorationDefault, QDecorationStyled, and QDecorationWindows.
Referenced by QDecorationStyled::paint(), QDecorationWindows::paint(), QDecorationDefault::paint(), QDecorationWindows::paintButton(), QDecorationDefault::paintButton(), regionAt(), and QWidgetBackingStore::removeDirtyWidget().
region() [2/2]
QRegion QDecoration::region (const QWidget * w, int decorationRegion = All) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 101 of file qdecoration_qws.h.
     { return region(w, w->rect(), decorationRegion); }
regionAt()
int QDecoration::regionAt (const QWidget * widget, const QPoint & point) virtual
Returns the type of the first region of the specified top level widget containing the given point.
The return value is one of the DecorationRegion enum's values. Use the region() function to retrieve the actual region. If none of the widget's regions contain the point, this function returns None .
See also
region()
Definition at line 236 of file qdecoration_qws.cpp.
 {
     int regions[] = {
         TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight, // Borders first
         Menu, Title, Help, Minimize, Normalize, Maximize, Close,                         // then buttons
         None
     };
 //     char *regions_str[] = {
 //         "TopLeft", "Top", "TopRight", "Left", "Right", "BottomLeft", "Bottom", "BottomRight",
 //         "Menu", "Title", "Help", "Minimize", "Normalize", "Maximize", "Close",
 //         "None"
 //     };
     // First check to see if within all regions at all
     QRegion reg = region(w, w->geometry(), All);
     if (!reg.contains(point)) {
         return None;
     }
     int i = 0;
     while (regions[i]) {
         reg = region(w, w->geometry(), regions[i]);
         if (reg.contains(point)) {
 //            qDebug("In region %s", regions_str[i]);
             return regions[i];
         }
         ++i;
     }
     return None;
 }
regionClicked()
void QDecoration::regionClicked (QWidget * widget, int region) virtual
Handles the event that the specified region in the given top level widget is activated by a single click (the region parameter is described using the DecorationRegion enum).
This function is called whenever a region in a top level widget is clicked; the default implementation responds to clicks on items in the system menu, performing the requested actions.
See also
regionDoubleClicked(), region()
Definition at line 322 of file qdecoration_qws.cpp.
Referenced by menuTriggered().
 {
     switch(reg) {
     case Move:
         startMove(widget);
         break;
     case Resize:
         startResize(widget);
         break;
     case Help:
 #ifndef QT_NO_WHATSTHIS
         if (QWhatsThis::inWhatsThisMode())
             QWhatsThis::leaveWhatsThisMode();
         else
             QWhatsThis::enterWhatsThisMode();
 #endif
         break;
     case Close:
         widget->close();
         break;
     case Normalize:
         widget->showNormal();
         break;
     case Maximize:
         if (widget->windowState() & Qt::WindowMaximized)
             widget->showNormal();
         else
             widget->showMaximized();
         break;
     }
 }
regionDoubleClicked()
void QDecoration::regionDoubleClicked (QWidget * widget, int region) virtual
Handles the event that the specified region in the given top level widget is activated by a double click (the region parameter is described using the DecorationRegion enum).
This function is called whenever a region in a top level widget is double clicked; the default implementation responds to a double click on the widget's title, toggling its size between the maximum and its normal size.
See also
regionClicked(), region()
Definition at line 368 of file qdecoration_qws.cpp.
 {
     switch(reg)
     {
         case Title: {
             if (widget->windowState() & Qt::WindowMaximized)
                 widget->showNormal();
             else
                 widget->showMaximized();
             break;
         }
     }
 }
startMove()
void QDecoration::startMove (QWidget * widget) static
Starts to move the given top level widget by making its Title region active and grabbing the mouse input.
See also
startResize()
Definition at line 387 of file qdecoration_qws.cpp.
Referenced by regionClicked().
 {
 #ifdef QT_NO_QWS_MANAGER
     Q_UNUSED(widget);
 #else
     QWSManager *manager = widget->d_func()->topData()->qwsManager;
     if (manager)
         manager->startMove();
 #endif
 }
startResize()
void QDecoration::startResize (QWidget * widget) static
Starts to resize the given top level widget by making its BottomRight region active and grabbing the mouse input.
See also
startMove()
Definition at line 403 of file qdecoration_qws.cpp.
Referenced by regionClicked().
 {
 #ifdef QT_NO_QWS_MANAGER
     Q_UNUSED(widget);
 #else
     QWSManager *manager = widget->d_func()->topData()->qwsManager;
     if (manager)
         manager->startResize();
 #endif
 }
The documentation for this class was generated from the following files:
/src/gui/embedded/qdecoration_qws.h
/src/gui/embedded/qdecoration_qws.cpp