Qt 4.8: QDateTime Class Reference
QDateTime Class Reference
The QDateTime class provides date and time functions.
#include <qdatetime.h>
Public Functions
QDateTime addDays (int days) const
Returns a QDateTime object containing a datetime ndays days later than the datetime of this object (or earlier if ndays is negative).
QDateTime addMonths (int months) const
Returns a QDateTime object containing a datetime nmonths months later than the datetime of this object (or earlier if nmonths is negative).
QDateTime addMSecs (qint64 msecs) const
Returns a QDateTime object containing a datetime msecs miliseconds later than the datetime of this object (or earlier if msecs is negative).
QDateTime addSecs (int secs) const
Returns a QDateTime object containing a datetime s seconds later than the datetime of this object (or earlier if s is negative).
QDateTime addYears (int years) const
Returns a QDateTime object containing a datetime nyears years later than the datetime of this object (or earlier if nyears is negative).
QDate date () const
Returns the date part of the datetime.
int daysTo (const QDateTime &) const
Returns the number of days from this datetime to the other datetime.
bool isNull () const
Returns true if both the date and the time are null; otherwise returns false.
bool isValid () const
Returns true if both the date and the time are valid; otherwise returns false.
qint64 msecsTo (const QDateTime &) const
Returns the number of milliseconds from this datetime to the other datetime.
bool operator!= (const QDateTime &other) const
Returns true if this datetime is different from the other datetime; otherwise returns false.
bool operator< (const QDateTime &other) const
Returns true if this datetime is earlier than the other datetime; otherwise returns false.
bool operator<= (const QDateTime &other) const
Returns true if this datetime is earlier than or equal to the other datetime; otherwise returns false.
QDateTime & operator= (const QDateTime &other)
Makes a copy of the other datetime and returns a reference to the copy.
bool operator== (const QDateTime &other) const
Returns true if this datetime is equal to the other datetime; otherwise returns false.
bool operator> (const QDateTime &other) const
Returns true if this datetime is later than the other datetime; otherwise returns false.
bool operator>= (const QDateTime &other) const
Returns true if this datetime is later than or equal to the other datetime; otherwise returns false.
QDateTime ()
Constructs a null datetime (i.e.
QDateTime (const QDate &)
Constructs a datetime with the given date, a valid time(00:00:00.000), and sets the timeSpec() to Qt::LocalTime.
QDateTime (const QDate &, const QTime &, Qt::TimeSpec spec=Qt::LocalTime)
Constructs a datetime with the given date and time, using the time specification defined by spec.
QDateTime (const QDateTime &other)
Constructs a copy of the other datetime.
int secsTo (const QDateTime &) const
Returns the number of seconds from this datetime to the other datetime.
void setDate (const QDate &date)
Sets the date part of this datetime to date.
void setMSecsSinceEpoch (qint64 msecs)
Sets the date and time given the number of milliseconds,msecs, that have passed since 1970-01-01T00:00:00.
void setTime (const QTime &time)
Sets the time part of this datetime to time.
void setTime_t (uint secsSince1Jan1970UTC)
Sets the date and time given the number of seconds that have passed since 1970-01-01T00:00:00, Coordinated Universal Time (Qt::UTC).
void setTimeSpec (Qt::TimeSpec spec)
Sets the time specification used in this datetime to spec.
void setUtcOffset (int seconds)
QTime time () const
Returns the time part of the datetime.
Qt::TimeSpec timeSpec () const
Returns the time specification of the datetime.
QDateTime toLocalTime () const
Returns a datetime containing the date and time information in this datetime, but specified using the Qt::LocalTime definition.
qint64 toMSecsSinceEpoch () const
Returns the datetime as the number of milliseconds that have passed since 1970-01-01T00:00:00.
QString toString (Qt::DateFormat f=Qt::TextDate) const
Returns the datetime as a string in the format given.
QString toString (const QString &format) const
Returns the datetime as a string.
uint toTime_t () const
Returns the datetime as the number of seconds that have passed since 1970-01-01T00:00:00, Coordinated Universal Time (Qt::UTC).
QDateTime toTimeSpec (Qt::TimeSpec spec) const
Returns a copy of this datetime configured to use the given time specification.
QDateTime toUTC () const
Returns a datetime containing the date and time information in this datetime, but specified using the Qt::UTC definition.
int utcOffset () const
~QDateTime ()
Destroys the datetime.
Static Public Functions
static QDateTime currentDateTime ()
Returns the current datetime, as reported by the system clock, in the local time zone.
static QDateTime currentDateTimeUtc ()
Returns the current datetime, as reported by the system clock, in UTC.
static qint64 currentMSecsSinceEpoch ()
Returns the number of milliseconds since 1970-01-01T00:00:00 Universal Coordinated Time.
static QDateTime fromMSecsSinceEpoch (qint64 msecs)
Returns a datetime whose date and time are the number of milliseconds, msecs, that have passed since 1970-01-01T00:00:00.
static QDateTime fromString (const QString &s, Qt::DateFormat f=Qt::TextDate)
Returns the QDateTime represented by the string, using the format given, or an invalid datetime if this is not possible.
static QDateTime fromString (const QString &s, const QString &format)
Returns the QDateTime represented by the string, using the format given, or an invalid datetime if the string cannot be parsed.
static QDateTime fromTime_t (uint secsSince1Jan1970UTC)
Returns a datetime whose date and time are the number of seconds that have passed since 1970-01-01T00:00:00, Coordinated Universal Time (Qt::UTC).
Private Functions
void detach ()
Properties
QExplicitlySharedDataPointer< QDateTimePrivate > d
Friends
Q_CORE_EXPORT QDataStream & operator<< (QDataStream &, const QDateTime &)
Writes dateTime to the out stream.
Q_CORE_EXPORT QDataStream & operator>> (QDataStream &, QDateTime &)
Reads a datetime from the stream in into dateTime.
class QDateTimePrivate
Detailed Description
The QDateTime class provides date and time functions.
Note
This class or function is reentrant.
A QDateTime object contains a calendar date and a clock time (a "datetime"). It is a combination of the QDate and QTime classes. It can read the current datetime from the system clock. It provides functions for comparing datetimes and for manipulating a datetime by adding a number of seconds, days, months, or years.
A QDateTime object is typically created either by giving a date and time explicitly in the constructor, or by using the static function currentDateTime() that returns a QDateTime object set to the system clock's time. The date and time can be changed with setDate() and setTime(). A datetime can also be set using the setTime_t() function that takes a POSIX-standard "number of seconds since 00:00:00 on January 1, 1970" value. The fromString() function returns a QDateTime, given a string and a date format used to interpret the date within the string.
The date() and time() functions provide access to the date and time parts of the datetime. The same information is provided in textual format by the toString() function.
QDateTime provides a full set of operators to compare two QDateTime objects where smaller means earlier and larger means later.
You can increment (or decrement) a datetime by a given number of milliseconds using addMSecs(), seconds using addSecs(), or days using addDays(). Similarly you can use addMonths() and addYears(). The daysTo() function returns the number of days between two datetimes, secsTo() returns the number of seconds between two datetimes, and msecsTo() returns the number of milliseconds between two datetimes.
QDateTime can store datetimes as local time or as UTC. QDateTime::currentDateTime() returns a QDateTime expressed as local time; use toUTC() to convert it to UTC. You can also use timeSpec() to find out if a QDateTime object stores a UTC time or a local time. Operations such as addSecs() and secsTo() are aware of daylight saving time (DST).
Note
QDateTime does not account for leap seconds.
Definition at line 216 of file qdatetime.h.
Constructors and Destructors
QDateTime() [1/4]
QDateTime::QDateTime ()
Constructs a null datetime (i.e.
null date and null time). A null datetime is invalid, since the date is invalid.
See also
isValid()
Definition at line 2267 of file qdatetime.cpp.
Referenced by addDays(), addMonths(), QDateTimePrivate::addMSecs(), addYears(), currentDateTime(), currentDateTimeUtc(), currentMSecsSinceEpoch(), fromString(), QDateTimeParser::getMaximum(), QDateTimeParser::getMinimum(), localToUtc(), QDateTimeParser::parse(), and QDateTimeParser::setDigit().
     : d(new QDateTimePrivate)
 {
 }
QDateTime() [2/4]
QDateTime::QDateTime (const QDate & date) explicit
Constructs a datetime with the given date, a valid time(00:00:00.000), and sets the timeSpec() to Qt::LocalTime.
Definition at line 2278 of file qdatetime.cpp.
     : d(new QDateTimePrivate)
 {
     d->date = date;
     d->time = QTime(0, 0, 0);
 }
QDateTime() [3/4]
QDateTime::QDateTime (const QDate & date, const QTime & time, Qt::TimeSpec spec = Qt::LocalTime)
Constructs a datetime with the given date and time, using the time specification defined by spec.
If date is valid and time is not, the time will be set to midnight.
Definition at line 2292 of file qdatetime.cpp.
     : d(new QDateTimePrivate)
 {
     d->date = date;
     d->time = date.isValid() && !time.isValid() ? QTime(0, 0, 0) : time;
     d->spec = (spec == Qt::UTC) ? QDateTimePrivate::UTC : QDateTimePrivate::LocalUnknown;
 }
QDateTime() [4/4]
QDateTime::QDateTime (const QDateTime & other)
Constructs a copy of the other datetime.
Definition at line 2304 of file qdatetime.cpp.
     : d(other.d)
 {
 }
~QDateTime()
QDateTime::~QDateTime ()
Destroys the datetime.
Definition at line 2312 of file qdatetime.cpp.
 {
 }
Functions
addDays()
QDateTime QDateTime::addDays (int ndays) const
Returns a QDateTime object containing a datetime ndays days later than the datetime of this object (or earlier if ndays is negative).
See also
daysTo(), addMonths(), addYears(), addSecs()
Definition at line 2783 of file qdatetime.cpp.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), operator+(), operator-(), and QDateTimeEditPrivate::stepBy().
 {
     return QDateTime(d->date.addDays(ndays), d->time, timeSpec());
 }
addMonths()
QDateTime QDateTime::addMonths (int nmonths) const
Returns a QDateTime object containing a datetime nmonths months later than the datetime of this object (or earlier if nmonths is negative).
See also
daysTo(), addDays(), addYears(), addSecs()
Definition at line 2796 of file qdatetime.cpp.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), and QDateTimeParser::parse().
 {
     return QDateTime(d->date.addMonths(nmonths), d->time, timeSpec());
 }
addMSecs()
QDateTime QDateTime::addMSecs (qint64 msecs) const
Returns a QDateTime object containing a datetime msecs miliseconds later than the datetime of this object (or earlier if msecs is negative).
See also
addSecs(), msecsTo(), addDays(), addMonths(), addYears()
Definition at line 2881 of file qdatetime.cpp.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), QDateTimePrivate::addMSecs(), QDateTimePrivate::getUTC(), and localToUtc().
 {
     return d->addMSecs(*this, msecs);
 }
addSecs()
QDateTime QDateTime::addSecs (int s) const
Returns a QDateTime object containing a datetime s seconds later than the datetime of this object (or earlier if s is negative).
See also
addMSecs(), secsTo(), addDays(), addMonths(), addYears()
Definition at line 2869 of file qdatetime.cpp.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), QNetworkAccessHttpBackend::fetchCacheMetaData(), QNetworkAccessCache::linkEntry(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), operator-(), QDateTimeParser::parse(), parseDateString(), QNetworkCookiePrivate::parseSetCookieHeaderLine(), q_getTimeFromASN1(), and qtValue().
 {
     return d->addMSecs(*this, qint64(s) * 1000);
 }
addYears()
QDateTime QDateTime::addYears (int nyears) const
Returns a QDateTime object containing a datetime nyears years later than the datetime of this object (or earlier if nyears is negative).
See also
daysTo(), addDays(), addMonths(), addSecs()
Definition at line 2809 of file qdatetime.cpp.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime().
 {
     return QDateTime(d->date.addYears(nyears), d->time, timeSpec());
 }
currentDateTime()
QDateTime QDateTime::currentDateTime () static
Returns the current datetime, as reported by the system clock, in the local time zone.
Use the currentDateTime() overload that takes no parameters instead.
See also
currentDateTimeUtc(), QDate::currentDate(), QTime::currentTime(), toTimeSpec()
Definition at line 3138 of file qdatetime.cpp.
Referenced by _q_fixupDateTime(), QZipWriterPrivate::addEntry(), QTransportAuth::authFromMessage(), QNetworkCookieJar::cookiesForUrl(), QUuid::createUuid(), currentMSecsSinceEpoch(), DumpIDL(), QPSPrintEnginePrivate::emitHeader(), QNetworkAccessHttpBackend::fetchCacheMetaData(), QNetworkSessionManagerPrivate::forceSessionClose(), QScriptDebuggerLocalsModelPrivate::get(), QSslCertificate::isValid(), QNetworkAccessCache::linkEntry(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QScriptErrorLogWidget::message(), QNetworkCookiePrivate::parseSetCookieHeaderLine(), QScriptScriptData::QScriptScriptData(), qt_CoCreateGuid(), qt_x11_apply_settings_in_all_apps(), QNetworkCookieJar::setCookiesFromUrl(), QConnmanEngine::startTime(), QNetworkSessionPrivateImpl::stateChange(), QNetworkAccessCache::timerEvent(), QNetworkAccessCache::updateTimer(), and QPdfEnginePrivate::writeInfo().
 {
     QDate d;
     QTime t;
     SYSTEMTIME st;
     memset(&st, 0, sizeof(SYSTEMTIME));
     GetLocalTime(&st);
     d.jd = julianDayFromDate(st.wYear, st.wMonth, st.wDay);
     t.mds = msecsFromDecomposed(st.wHour, st.wMinute, st.wSecond, st.wMilliseconds);
     return QDateTime(d, t);
 }
currentDateTimeUtc()
QDateTime QDateTime::currentDateTimeUtc () static
Returns the current datetime, as reported by the system clock, in UTC.
Since
4.7
See also
currentDateTime(), QDate::currentDate(), QTime::currentTime(), toTimeSpec()
Definition at line 3150 of file qdatetime.cpp.
Referenced by currentMSecsSinceEpoch().
 {
     QDate d;
     QTime t;
     SYSTEMTIME st;
     memset(&st, 0, sizeof(SYSTEMTIME));
     GetSystemTime(&st);
     d.jd = julianDayFromDate(st.wYear, st.wMonth, st.wDay);
     t.mds = msecsFromDecomposed(st.wHour, st.wMinute, st.wSecond, st.wMilliseconds);
     return QDateTime(d, t, Qt::UTC);
 }
currentMSecsSinceEpoch()
qint64 QDateTime::currentMSecsSinceEpoch () static
Returns the number of milliseconds since 1970-01-01T00:00:00 Universal Coordinated Time.
Since
4.7
This number is like the POSIX time_t variable, but expressed in milliseconds instead.
See also
currentDateTime(), currentDateTimeUtc(), toTime_t(), toTimeSpec()
Definition at line 3162 of file qdatetime.cpp.
Referenced by QElapsedTimer::elapsed(), and QElapsedTimer::restart().
 {
     QDate d;
     QTime t;
     SYSTEMTIME st;
     memset(&st, 0, sizeof(SYSTEMTIME));
     GetSystemTime(&st);
     return msecsFromDecomposed(st.wHour, st.wMinute, st.wSecond, st.wMilliseconds) +
             qint64(julianDayFromGregorianDate(st.wYear, st.wMonth, st.wDay)
                    - julianDayFromGregorianDate(1970, 1, 1)) * Q_INT64_C(86400000);
 }
date()
QDate QDateTime::date () const
Returns the date part of the datetime.
See also
setDate(), time(), timeSpec()
Definition at line 2357 of file qdatetime.cpp.
Referenced by _q_fixupDateTime(), _q_parseDosDir(), _q_parseUnixDir(), QDateTimeParser::absoluteMax(), adjustDate(), QScript::DateTimeToMs(), QStyledItemDelegate::displayText(), QDB2Result::exec(), QODBCResult::exec(), QPatternist::YearFromAbstractDateTimeFN::extract(), QPatternist::DayFromAbstractDateTimeFN::extract(), QPatternist::MonthFromAbstractDateTimeFN::extract(), QDeclarativeEnginePrivate::formatDate(), QDB2Driver::formatValue(), QIBaseDriver::formatValue(), QOCIDriver::formatValue(), QODBCDriver::formatValue(), QPSQLDriver::formatValue(), QPatternist::GMonthDay::fromDateTime(), QPatternist::Date::fromDateTime(), QPatternist::GDay::fromDateTime(), QPatternist::GMonth::fromDateTime(), QPatternist::GYear::fromDateTime(), QPatternist::GYearMonth::fromDateTime(), QDateTimeParser::fromString(), fromString(), QDeclarativeCompiler::genLiteralAssignment(), QDateTimeParser::getDigit(), QDateTimePrivate::getLocal(), QDateTimePrivate::getUTC(), localToUtc(), operator*(), operator<<(), QDateTimeParser::parse(), QDateTimeParser::parseSection(), QDateTimeParser::potentialValue(), QDateTime(), QDateTimeToDATE(), qMakeOraDate(), setDate(), QDateTimeEdit::setDateTime(), QDateTimeParser::setDigit(), QDateTimeEdit::setMaximumDateTime(), QDateTimeEdit::setMinimumDateTime(), QDateTimeEditPrivate::stepBy(), QPatternist::AtomicValue::toQt(), QSystemLocalePrivate::toString(), QLocale::toString(), toTimeStamp(), QItemDelegatePrivate::valueToText(), QPdfEnginePrivate::writeInfo(), and writeMSDosDate().
 {
     return d->date;
 }
daysTo()
int QDateTime::daysTo (const QDateTime & other) const
Returns the number of days from this datetime to the other datetime.
If the other datetime is earlier than this datetime, the value returned is negative.
See also
addDays(), secsTo(), msecsTo()
Definition at line 2894 of file qdatetime.cpp.
Referenced by QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), operator-(), and QDateTimeParser::parse().
 {
     return d->date.daysTo(other.d->date);
 }
detach()
void QDateTime::detach () private
Warning
This function is not part of the public interface.
Definition at line 3791 of file qdatetime.cpp.
Referenced by setDate(), setMSecsSinceEpoch(), setTime(), setTime_t(), setTimeSpec(), and setUtcOffset().
 {
     d.detach();
 }
fromMSecsSinceEpoch()
QDateTime QDateTime::fromMSecsSinceEpoch (qint64 msecs) static
Returns a datetime whose date and time are the number of milliseconds, msecs, that have passed since 1970-01-01T00:00:00.
Since
4.7
000, Coordinated Universal Time (Qt::UTC). On systems that do not support time zones, the time will be set as if local time were Qt::UTC.
Note that there are possible values for msecs that lie outside the valid range of QDateTime, both negative and positive. The behavior of this function is undefined for those values.
See also
toTime_t(), setTime_t()
Definition at line 3393 of file qdatetime.cpp.
Referenced by operator==().
 {
     QDateTime d;
     d.setMSecsSinceEpoch(msecs);
     return d;
 }
fromString() [1/2]
QDateTime QDateTime::fromString (const QString & string, Qt::DateFormat format = Qt::TextDate) static
Returns the QDateTime represented by the string, using the format given, or an invalid datetime if this is not possible.
Note for Qt::TextDate: It is recommended that you use the English short month names (e.g. "Jan"). Although localized month names can also be used, they depend on the user's locale settings.
Definition at line 3487 of file qdatetime.cpp.
Referenced by convert(), QPSQLResult::data(), QDeclarativeStringConverters::dateTimeFromString(), QNetworkHeadersPrivate::fromHttpDate(), QNetworkAccessFtpBackend::ftpRawCommandReply(), and qDateTimeFromString().
 {
     if (s.isEmpty()) {
         return QDateTime();
     }
     switch (f) {
     case Qt::ISODate: {
         QString tmp = s;
         Qt::TimeSpec ts = Qt::LocalTime;
         const QDate date = QDate::fromString(tmp.left(10), Qt::ISODate);
         if (tmp.size() == 10)
             return QDateTime(date);
         tmp = tmp.mid(11);
         // Recognize UTC specifications
         if (tmp.endsWith(QLatin1Char('Z'))) {
             ts = Qt::UTC;
             tmp.chop(1);
         }
         // Recognize timezone specifications
         QRegExp rx(QLatin1String("[+-]"));
         if (tmp.contains(rx)) {
             int idx = tmp.indexOf(rx);
             QString tmp2 = tmp.mid(idx);
             tmp = tmp.left(idx);
             bool ok = true;
             int ntzhour = 1;
             int ntzminute = 3;
             if ( tmp2.indexOf(QLatin1Char(':')) == 3 )
                ntzminute = 4;
             const int tzhour(tmp2.mid(ntzhour, 2).toInt(&ok));
             const int tzminute(tmp2.mid(ntzminute, 2).toInt(&ok));
             QTime tzt(tzhour, tzminute);
             int utcOffset = (tzt.hour() * 60 + tzt.minute()) * 60;
             if ( utcOffset != 0 ) {
                 ts = Qt::OffsetFromUTC;
                 QDateTime dt(date, QTime::fromString(tmp, Qt::ISODate), ts);
                 dt.setUtcOffset( utcOffset * (tmp2.startsWith(QLatin1Char('-')) ? -1 : 1) );
                 return dt;
             }
         }
         return QDateTime(date, QTime::fromString(tmp, Qt::ISODate), ts);
     }
     case Qt::SystemLocaleDate:
     case Qt::SystemLocaleShortDate:
     case Qt::SystemLocaleLongDate:
         return fromString(s, QLocale::system().dateTimeFormat(f == Qt::SystemLocaleLongDate ? QLocale::LongFormat
                                                                                             : QLocale::ShortFormat));
     case Qt::LocaleDate:
     case Qt::DefaultLocaleShortDate:
     case Qt::DefaultLocaleLongDate:
         return fromString(s, QLocale().dateTimeFormat(f == Qt::DefaultLocaleLongDate ? QLocale::LongFormat
                                                                                      : QLocale::ShortFormat));
 #if !defined(QT_NO_TEXTDATE)
     case Qt::TextDate: {
         QStringList parts = s.split(QLatin1Char(' '), QString::SkipEmptyParts);
         if ((parts.count() < 5) || (parts.count() > 6)) {
             return QDateTime();
         }
         // Accept "Sun Dec 1 13:02:00 1974" and "Sun 1. Dec 13:02:00 1974"
         int month = -1, day = -1;
         bool ok;
         month = fromShortMonthName(parts.at(1));
         if (month != -1) {
             day = parts.at(2).toInt(&ok);
             if (!ok)
                 day = -1;
         }
         if (month == -1 || day == -1) {
             // first variant failed, lets try the other
             month = fromShortMonthName(parts.at(2));
             if (month != -1) {
                 QString dayStr = parts.at(1);
                 if (dayStr.endsWith(QLatin1Char('.'))) {
                     dayStr.chop(1);
                     day = dayStr.toInt(&ok);
                     if (!ok)
                         day = -1;
                 } else {
                     day = -1;
                 }
             }
         }
         if (month == -1 || day == -1) {
             // both variants failed, give up
             return QDateTime();
         }
         int year;
         QStringList timeParts = parts.at(3).split(QLatin1Char(':'));
         if ((timeParts.count() == 3) || (timeParts.count() == 2)) {
             year = parts.at(4).toInt(&ok);
             if (!ok)
                 return QDateTime();
         } else {
             timeParts = parts.at(4).split(QLatin1Char(':'));
             if ((timeParts.count() != 3) && (timeParts.count() != 2))
                 return QDateTime();
             year = parts.at(3).toInt(&ok);
             if (!ok)
                 return QDateTime();
         }
         int hour = timeParts.at(0).toInt(&ok);
         if (!ok) {
             return QDateTime();
         }
         int minute = timeParts.at(1).toInt(&ok);
         if (!ok) {
             return QDateTime();
         }
         int second = (timeParts.count() > 2) ? timeParts.at(2).toInt(&ok) : 0;
         if (!ok) {
             return QDateTime();
         }
         QDate date(year, month, day);
         QTime time(hour, minute, second);
         if (parts.count() == 5)
             return QDateTime(date, time, Qt::LocalTime);
         QString tz = parts.at(5);
         if (!tz.startsWith(QLatin1String("GMT"), Qt::CaseInsensitive))
             return QDateTime();
         QDateTime dt(date, time, Qt::UTC);
         if (tz.length() > 3) {
             int tzoffset = 0;
             QChar sign = tz.at(3);
             if ((sign != QLatin1Char('+'))
                 && (sign != QLatin1Char('-'))) {
                 return QDateTime();
             }
             int tzhour = tz.mid(4, 2).toInt(&ok);
             if (!ok)
                 return QDateTime();
             int tzminute = tz.mid(6).toInt(&ok);
             if (!ok)
                 return QDateTime();
             tzoffset = (tzhour*60 + tzminute) * 60;
             if (sign == QLatin1Char('-'))
                 tzoffset = -tzoffset;
             dt.setUtcOffset(tzoffset);
         }
         return dt.toLocalTime();
     }
 #endif //QT_NO_TEXTDATE
     }
     return QDateTime();
 }
fromString() [2/2]
QDateTime QDateTime::fromString (const QString & string, const QString & format) static
Returns the QDateTime represented by the string, using the format given, or an invalid datetime if the string cannot be parsed.
These expressions may be used for the date part of the format string:
Expression Output
d the day as number without a leading zero (1 to 31)
dd the day as number with a leading zero (01 to 31)
ddd the abbreviated localized day name (e.g. 'Mon' to 'Sun'). Uses QDate::shortDayName().
dddd the long localized day name (e.g. 'Monday' to 'Sunday'). Uses QDate::longDayName().
M the month as number without a leading zero (1-12)
MM the month as number with a leading zero (01-12)
MMM the abbreviated localized month name (e.g. 'Jan' to 'Dec'). Uses QDate::shortMonthName().
MMMM the long localized month name (e.g. 'January' to 'December'). Uses QDate::longMonthName().
yy the year as two digit number (00-99)
yyyy the year as four digit number
Note
Unlike the other version of this function, day and month names must be given in the user's local language. It is only possible to use the English names if the user's language is English.
These expressions may be used for the time part of the format string:
Expression Output
h the hour without a leading zero (0 to 23 or 1 to 12 if AM/PM display)
hh the hour with a leading zero (00 to 23 or 01 to 12 if AM/PM display)
H the hour without a leading zero (0 to 23, even with AM/PM display)
HH the hour with a leading zero (00 to 23, even with AM/PM display)
m the minute without a leading zero (0 to 59)
mm the minute with a leading zero (00 to 59)
s the second without a leading zero (0 to 59)
ss the second with a leading zero (00 to 59)
z the milliseconds without leading zeroes (0 to 999)
zzz the milliseconds with leading zeroes (000 to 999)
AP or A interpret as an AM/PM time. AP must be either "AM" or "PM".
ap or a Interpret as an AM/PM time. ap must be either "am" or "pm".
All other input characters will be treated as text. Any sequence of characters that are enclosed in singlequotes will also be treated as text and not be used as an expression.
QTime time1 = QTime::fromString("131", "HHh");
// time1 is 13:00:00
QTime time1 = QTime::fromString("1apA", "1amAM");
// time1 is 01:00:00
QDateTime dateTime2 = QDateTime::fromString("M1d1y9800:01:02",
                                            "'M'M'd'd'y'yyhh:mm:ss");
// dateTime is 1 January 1998 00:01:02
If the format is not satisfied an invalid QDateTime is returned. The expressions that don't have leading zeroes (d, M, h, m, s, z) will be greedy. This means that they will use two digits even if this will put them outside the range and/or leave too few digits for other sections.
QDateTime dateTime = QDateTime::fromString("130", "Mm"); // invalid
This could have meant 1 January 00:30.00 but the M will grab two digits.
For any field that is not represented in the format the following defaults are used:
Field Default value
Year 1900
Month 1 (January)
Day 1
Hour 0
Minute 0
Second 0
For example:
QDateTime dateTime = QDateTime::fromString("1.30.1", "M.d.s");
// dateTime is January 30 in 1900 at 00:00:01.
See also
QDate::fromString() QTime::fromString() QDate::toString() QDateTime::toString() QTime::toString()
Definition at line 3748 of file qdatetime.cpp.
 {
 #ifndef QT_BOOTSTRAPPED
     QTime time;
     QDate date;
     QDateTimeParser dt(QVariant::DateTime, QDateTimeParser::FromString);
     if (dt.parseFormat(format) && dt.fromString(string, &date, &time))
         return QDateTime(date, time);
 #else
     Q_UNUSED(string);
     Q_UNUSED(format);
 #endif
     return QDateTime(QDate(), QTime(-1, -1, -1));
 }
fromTime_t()
QDateTime QDateTime::fromTime_t (uint seconds) static
Returns a datetime whose date and time are the number of seconds that have passed since 1970-01-01T00:00:00, Coordinated Universal Time (Qt::UTC).
Since
4.2
On systems that do not support time zones, the time will be set as if local time were Qt::UTC.
See also
toTime_t(), setTime_t()
Definition at line 3369 of file qdatetime.cpp.
Referenced by QFileSystemMetaData::fileTime().
 {
     QDateTime d;
     d.setTime_t(seconds);
     return d;
 }
isNull()
bool QDateTime::isNull () const
Returns true if both the date and the time are null; otherwise returns false.
A null datetime is invalid.
See also
QDate::isNull(), QTime::isNull(), isValid()
Definition at line 2334 of file qdatetime.cpp.
Referenced by QDateTimeToDATE(), QConnmanEngine::startTime(), and QDateTimeEditPrivate::validateAndInterpret().
 {
     return d->date.isNull() && d->time.isNull();
 }
isValid()
bool QDateTime::isValid () const
Returns true if both the date and the time are valid; otherwise returns false.
See also
QDate::isValid(), QTime::isValid()
Definition at line 2346 of file qdatetime.cpp.
Referenced by _q_parseUnixDir(), QDateTimeParser::absoluteMax(), QPatternist::AbstractDateTime::AbstractDateTime(), convert(), QPatternist::AdjustDateTimeToTimezoneFN::createValue(), QPatternist::AdjustDateToTimezoneFN::createValue(), QPatternist::AdjustTimeToTimezoneFN::createValue(), QDeclarativeStringConverters::dateTimeFromString(), QScript::DateTimeToMs(), QDB2Driver::formatValue(), QSqlDriver::formatValue(), QIBaseDriver::formatValue(), QOCIDriver::formatValue(), QTDSDriver::formatValue(), QODBCDriver::formatValue(), QPSQLDriver::formatValue(), QPatternist::Date::fromDateTime(), QPatternist::SchemaTime::fromDateTime(), QPatternist::DateTime::fromDateTime(), QNetworkHeadersPrivate::fromHttpDate(), QPatternist::Date::fromValue(), QPatternist::SchemaTime::fromValue(), QPatternist::DateTime::fromValue(), QNetworkCookie::isSessionCookie(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QDateTimeParser::parse(), parseDateString(), parseHttpDate(), QNetworkCookiePrivate::parseSetCookieHeaderLine(), QDateTimeEdit::QDateTimeEdit(), QDateTimeToDATE(), QScriptScriptData::QScriptScriptData(), QDateTimeEdit::setDateTime(), QDateTimeEdit::setMaximumDateTime(), QDateTimeEdit::setMinimumDateTime(), QTest::toString(), toString(), QLocale::toString(), utcOffset(), and writeMSDosDate().
 {
     return d->date.isValid() && d->time.isValid();
 }
msecsTo()
qint64 QDateTime::msecsTo (const QDateTime & other) const
Returns the number of milliseconds from this datetime to the other datetime.
Since
4.7
If the other datetime is earlier than this datetime, the value returned is negative.
Before performing the comparison, the two datetimes are converted to Qt::UTC to ensure that the result is correct if one of the two datetimes has daylight saving time (DST) and the other doesn't.
See also
addMSecs(), daysTo(), QTime::msecsTo()
Definition at line 2942 of file qdatetime.cpp.
 {
     QDate selfDate;
     QDate otherDate;
     QTime selfTime;
     QTime otherTime;
     d->getUTC(selfDate, selfTime);
     other.d->getUTC(otherDate, otherTime);
     return (static_cast<qint64>(selfDate.daysTo(otherDate)) * static_cast<qint64>(MSECS_PER_DAY))
            + static_cast<qint64>(selfTime.msecsTo(otherTime));
 }
operator!=()
bool QDateTime::operator!= (const QDateTime & other) const inline
Returns true if this datetime is different from the other datetime; otherwise returns false.
Two datetimes are different if either the date, the time, or the time zone components are different.
See also
operator==()
Definition at line 257 of file qdatetime.h.
 { return !(*this == other); }
operator<()
bool QDateTime::operator< (const QDateTime & other) const
Returns true if this datetime is earlier than the other datetime; otherwise returns false.
Definition at line 3025 of file qdatetime.cpp.
 {
     if (d->spec == other.d->spec && d->spec != QDateTimePrivate::OffsetFromUTC) {
         if (d->date != other.d->date)
             return d->date < other.d->date;
         return d->time < other.d->time;
     } else {
         QDate date1, date2;
         QTime time1, time2;
         d->getUTC(date1, time1);
         other.d->getUTC(date2, time2);
         if (date1 != date2)
             return date1 < date2;
         return time1 < time2;
     }
 }
operator<=()
bool QDateTime::operator<= (const QDateTime & other) const inline
Returns true if this datetime is earlier than or equal to the other datetime; otherwise returns false.
Definition at line 259 of file qdatetime.h.
 { return !(other < *this); }
operator=()
QDateTime & QDateTime::operator= (const QDateTime & other)
Makes a copy of the other datetime and returns a reference to the copy.
Definition at line 2321 of file qdatetime.cpp.
 {
     d = other.d;
     return *this;
 }
operator==()
bool QDateTime::operator== (const QDateTime & other) const
Returns true if this datetime is equal to the other datetime; otherwise returns false.
See also
operator!=()
Definition at line 2991 of file qdatetime.cpp.
 {
     if (d->spec == other.d->spec && d->utcOffset == other.d->utcOffset)
         return d->time == other.d->time && d->date == other.d->date;
     else {
         QDate date1, date2;
         QTime time1, time2;
         d->getUTC(date1, time1);
         other.d->getUTC(date2, time2);
         return time1 == time2 && date1 == date2;
     }
 }
operator>()
bool QDateTime::operator> (const QDateTime & other) const inline
Returns true if this datetime is later than the other datetime; otherwise returns false.
Definition at line 260 of file qdatetime.h.
 { return other < *this; }
operator>=()
bool QDateTime::operator>= (const QDateTime & other) const inline
Returns true if this datetime is later than or equal to the other datetime; otherwise returns false.
Definition at line 261 of file qdatetime.h.
 { return !(*this < other); }
secsTo()
int QDateTime::secsTo (const QDateTime & other) const
Returns the number of seconds from this datetime to the other datetime.
If the other datetime is earlier than this datetime, the value returned is negative.
Before performing the comparison, the two datetimes are converted to Qt::UTC to ensure that the result is correct if one of the two datetimes has daylight saving time (DST) and the other doesn't.
Example:
QDateTime now = QDateTime::currentDateTime();
QDateTime xmas(QDate(now.date().year(), 12, 25), QTime(0, 0));
qDebug("There are %d seconds to Christmas", now.secsTo(xmas));
See also
addSecs(), daysTo(), QTime::secsTo()
Definition at line 2914 of file qdatetime.cpp.
Referenced by _q_fixupDateTime(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), FAREnforcer::logAuthAttempt(), macValue(), QDirSortItemComparator::operator()(), operator-(), QConnmanEngine::startTime(), and QNetworkAccessCache::updateTimer().
 {
     QDate date1, date2;
     QTime time1, time2;
     d->getUTC(date1, time1);
     other.d->getUTC(date2, time2);
     return (date1.daysTo(date2) * SECS_PER_DAY) + time1.secsTo(time2);
 }
setDate()
void QDateTime::setDate (const QDate & date)
Sets the date part of this datetime to date.
If no time is set, it is set to midnight.
See also
date(), setTime(), setTimeSpec()
Definition at line 2399 of file qdatetime.cpp.
Referenced by _q_fixupDateTime(), _q_parseDosDir(), _q_parseUnixDir(), fileTimeToQDateTime(), QPatternist::Date::fromDateTime(), and QPatternist::SchemaTime::fromDateTime().
 {
     detach();
     d->date = date;
     if (d->spec == QDateTimePrivate::LocalStandard
         || d->spec == QDateTimePrivate::LocalDST)
         d->spec = QDateTimePrivate::LocalUnknown;
     if (date.isValid() && !d->time.isValid())
         d->time = QTime(0, 0, 0);
 }
setMSecsSinceEpoch()
void QDateTime::setMSecsSinceEpoch (qint64 msecs)
Sets the date and time given the number of milliseconds,msecs, that have passed since 1970-01-01T00:00:00.
Since
4.7
000, Coordinated Universal Time (Qt::UTC). On systems that do not support time zones this function will behave as if local time were Qt::UTC.
Note that there are possible values for msecs that lie outside the valid range of QDateTime, both negative and positive. The behavior of this function is undefined for those values.
See also
toMSecsSinceEpoch(), setTime_t()
Definition at line 2530 of file qdatetime.cpp.
Referenced by fromMSecsSinceEpoch().
 {
     detach();
     QDateTimePrivate::Spec oldSpec = d->spec;
     int ddays = msecs / MSECS_PER_DAY;
     msecs %= MSECS_PER_DAY;
     if (msecs < 0) {
         // negative
         --ddays;
         msecs += MSECS_PER_DAY;
     }
     d->date = QDate(1970, 1, 1).addDays(ddays);
     d->time = QTime().addMSecs(msecs);
     d->spec = QDateTimePrivate::UTC;
     if (oldSpec != QDateTimePrivate::UTC)
         d->spec = d->getLocal(d->date, d->time);
 }
setTime()
void QDateTime::setTime (const QTime & time)
Sets the time part of this datetime to time.
See also
time(), setDate(), setTimeSpec()
Definition at line 2416 of file qdatetime.cpp.
Referenced by fileTimeToQDateTime(), QPatternist::SchemaTime::fromDateTime(), operator+(), and operator-().
 {
     detach();
     if (d->spec == QDateTimePrivate::LocalStandard
         || d->spec == QDateTimePrivate::LocalDST)
         d->spec = QDateTimePrivate::LocalUnknown;
     d->time = time;
 }
setTime_t()
void QDateTime::setTime_t (uint seconds)
Sets the date and time given the number of seconds that have passed since 1970-01-01T00:00:00, Coordinated Universal Time (Qt::UTC).
Use the single-argument overload of setTime_t() instead.
On systems that do not support time zones this function will behave as if local time were Qt::UTC.
See also
toTime_t()
Definition at line 2566 of file qdatetime.cpp.
Referenced by fileTimeToQDateTime(), fromTime_t(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), macValue(), and qtValue().
 {
     detach();
     QDateTimePrivate::Spec oldSpec = d->spec;
     d->date = QDate(1970, 1, 1).addDays(secsSince1Jan1970UTC / SECS_PER_DAY);
     d->time = QTime().addSecs(secsSince1Jan1970UTC % SECS_PER_DAY);
     d->spec = QDateTimePrivate::UTC;
     if (oldSpec != QDateTimePrivate::UTC)
         d->spec = d->getLocal(d->date, d->time);
 }
setTimeSpec()
void QDateTime::setTimeSpec (Qt::TimeSpec spec)
Sets the time specification used in this datetime to spec.
See also
timeSpec(), setDate(), setTime(), Qt::TimeSpec
Definition at line 2431 of file qdatetime.cpp.
Referenced by QPatternist::AbstractDateTime::copyTimeSpec(), QNetworkHeadersPrivate::fromHttpDate(), and QPatternist::AbstractDateTime::setUtcOffset().
 {
     detach();
     switch(spec)
     {
         case Qt::UTC:
             d->spec = QDateTimePrivate::UTC;
             break;
         case Qt::OffsetFromUTC:
             d->spec = QDateTimePrivate::OffsetFromUTC;
             break;
         default:
             d->spec = QDateTimePrivate::LocalUnknown;
             break;
     }
 }
setUtcOffset()
void QDateTime::setUtcOffset (int seconds)
Since
4.4
Warning
This function is not part of the public interface.
Sets the offset from UTC to seconds, and also sets timeSpec() to Qt::OffsetFromUTC.
The maximum and minimum offset is 14 positive or negative hours. If seconds is larger or smaller than that, the result is undefined.
0 as offset is identical to UTC. Therefore, if seconds is 0, the timeSpec() will be set to Qt::UTC. Hence the UTC offset always relates to UTC, and can never relate to local time.
See also
isValid(), utcOffset()
Definition at line 3416 of file qdatetime.cpp.
Referenced by QPatternist::AbstractDateTime::copyTimeSpec(), fromString(), and QPatternist::AbstractDateTime::setUtcOffset().
 {
     detach();
     /* The motivation to also setting d->spec is to ensure that the QDateTime
      * instance stay in well-defined states all the time, instead of that
      * we instruct the user to ensure it. */
     if(seconds == 0)
         d->spec = QDateTimePrivate::UTC;
     else
         d->spec = QDateTimePrivate::OffsetFromUTC;
     /* Even if seconds is 0 we assign it to utcOffset. */
     d->utcOffset = seconds;
 }
time()
QTime QDateTime::time () const
Returns the time part of the datetime.
See also
setTime(), date(), timeSpec()
Definition at line 2368 of file qdatetime.cpp.
Referenced by currentMSecsSinceEpoch(), QScript::DateTimeToMs(), QStyledItemDelegate::displayText(), QDB2Result::exec(), QODBCResult::exec(), QPatternist::HoursFromAbstractDateTimeFN::extract(), QPatternist::MinutesFromAbstractDateTimeFN::extract(), QPatternist::SecondsFromAbstractDateTimeFN::extract(), QDeclarativeEnginePrivate::formatTime(), QDB2Driver::formatValue(), QIBaseDriver::formatValue(), QOCIDriver::formatValue(), QODBCDriver::formatValue(), QPSQLDriver::formatValue(), QPatternist::SchemaTime::fromDateTime(), QDateTimeParser::fromString(), fromString(), QDeclarativeCompiler::genLiteralAssignment(), QDateTimeParser::getDigit(), QDateTimePrivate::getLocal(), QDateTimePrivate::getUTC(), localToUtc(), operator*(), operator+(), operator-(), operator/(), operator<<(), operator==(), QDateTimeParser::parse(), QDateTime(), QDateTimeToDATE(), qMakeOraDate(), QDateTimeEdit::setDateTime(), QDateTimeParser::setDigit(), setTime(), QPatternist::AbstractDateTime::timeToString(), QSystemLocalePrivate::toString(), QLocale::toString(), toTimeStamp(), QItemDelegatePrivate::valueToText(), QPdfEnginePrivate::writeInfo(), and writeMSDosDate().
 {
     return d->time;
 }
timeSpec()
Qt::TimeSpec QDateTime::timeSpec () const
Returns the time specification of the datetime.
See also
setTimeSpec(), date(), time(), Qt::TimeSpec
Definition at line 2379 of file qdatetime.cpp.
Referenced by addDays(), addMonths(), QDateTimePrivate::addMSecs(), addYears(), QPatternist::AbstractDateTime::copyTimeSpec(), QPatternist::AbstractDateTimeComparator::equals(), QPatternist::TimezoneFromAbstractDateTimeFN::extract(), macValue(), operator<<(), QTest::toString(), and QPatternist::AbstractDateTime::zoneOffsetToString().
 {
     switch(d->spec)
     {
         case QDateTimePrivate::UTC:
             return Qt::UTC;
         case QDateTimePrivate::OffsetFromUTC:
             return Qt::OffsetFromUTC;
         default:
             return Qt::LocalTime;
     }
 }
toLocalTime()
QDateTime QDateTime::toLocalTime () const inline
Returns a datetime containing the date and time information in this datetime, but specified using the Qt::LocalTime definition.
See also
toTimeSpec()
Definition at line 250 of file qdatetime.h.
Referenced by fromString(), and QScript::MsToDateTime().
 { return toTimeSpec(Qt::LocalTime); }
toMSecsSinceEpoch()
qint64 QDateTime::toMSecsSinceEpoch () const
Returns the datetime as the number of milliseconds that have passed since 1970-01-01T00:00:00.
Since
4.7
000, Coordinated Universal Time (Qt::UTC).
On systems that do not support time zones, this function will
behave as if local time were Qt::UTC.
The behavior for this function is undefined if the datetime stored in
this object is not valid. However, for all valid dates, this function
returns a unique value.
\sa toTime_t(), setMSecsSinceEpoch()
Definition at line 2474 of file qdatetime.cpp.
Referenced by operator==(), and toTime_t().
 {
     QDate utcDate;
     QTime utcTime;
     d->getUTC(utcDate, utcTime);
     return toMSecsSinceEpoch_helper(utcDate.jd, utcTime.ds());
 }
toString() [1/2]
QString QDateTime::toString (Qt::DateFormat format = Qt::TextDate) const
Returns the datetime as a string in the format given.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the format is Qt::TextDate, the string is formatted in the default way. QDate::shortDayName(), QDate::shortMonthName(), and QTime::toString() are used to generate the string, so the day and month names will be localized names. An example of this formatting is "Wed May 20 03:40:13 1998".
If the format is Qt::ISODate, the string format corresponds to the ISO 8601 extended specification for representations of dates and times, taking the form YYYY-MM-DDTHH:mm:ss[Z|[+|-]HH:mm], depending on the timeSpec() of the QDateTime. If the timeSpec() is Qt::UTC, Z will be appended to the string; if the timeSpec() is Qt::OffsetFromUTC the offset in hours and minutes from UTC will be appended to the string.
If the format is Qt::SystemLocaleShortDate or Qt::SystemLocaleLongDate, the string format depends on the locale settings of the system. Identical to calling QLocale::system().toString(datetime, QLocale::ShortFormat) or QLocale::system().toString(datetime, QLocale::LongFormat).
If the format is Qt::DefaultLocaleShortDate or Qt::DefaultLocaleLongDate, the string format depends on the default application locale. This is the locale set with QLocale::setDefault(), or the system locale if no default locale has been set. Identical to calling QLocale().toString(datetime, QLocale::ShortFormat) or QLocale().toString(datetime, QLocale::LongFormat).
If the datetime is invalid, an empty string will be returned.
Warning
The Qt::ISODate format is only valid for years in the range 0 to 9999. This restriction may apply to locale-aware formats as well, depending on the locale settings.
See also
QDate::toString() QTime::toString() Qt::DateFormat
Definition at line 2628 of file qdatetime.cpp.
Referenced by QPatternist::AbstractDateTime::dateToString(), DumpIDL(), QPSPrintEnginePrivate::emitHeader(), QDeclarativeEnginePrivate::formatDateTime(), QSqlDriver::formatValue(), QTDSDriver::formatValue(), fromScriptValue(), QScriptDebuggerLocalsModelPrivate::get(), QDateTimeParser::getDigit(), QLibraryPrivate::isPlugin(), operator<<(), QDateTimeParser::parse(), QDateTimeParser::setDigit(), QPatternist::GYear::stringValue(), QPatternist::GYearMonth::stringValue(), QPatternist::GMonth::stringValue(), QPatternist::GDay::stringValue(), QPatternist::GMonthDay::stringValue(), QPatternist::AbstractDateTime::timeToString(), and QTest::toString().
 {
     QString buf;
     if (!isValid())
         return buf;
     if (f == Qt::ISODate) {
         buf = d->date.toString(Qt::ISODate);
         if (buf.isEmpty())
             return QString();   // failed to convert
         buf += QLatin1Char('T');
         buf += d->time.toString(Qt::ISODate);
         switch (d->spec) {
         case QDateTimePrivate::UTC:
             buf += QLatin1Char('Z');
             break;
         case QDateTimePrivate::OffsetFromUTC: {
             int sign = d->utcOffset >= 0 ? 1: -1;
             buf += QString::fromLatin1("%1%2:%3").
                 arg(sign == 1 ? QLatin1Char('+') : QLatin1Char('-')).
                 arg(d->utcOffset * sign / SECS_PER_HOUR, 2, 10, QLatin1Char('0')).
                 arg((d->utcOffset / 60) % 60, 2, 10, QLatin1Char('0'));
             break;
         }
         default:
             break;
         }
     }
 #ifndef QT_NO_TEXTDATE
     else if (f == Qt::TextDate) {
 #ifndef Q_WS_WIN
         buf = d->date.shortDayName(d->date.dayOfWeek());
         buf += QLatin1Char(' ');
         buf += d->date.shortMonthName(d->date.month());
         buf += QLatin1Char(' ');
         buf += QString::number(d->date.day());
 #else
         wchar_t out[255];
         GetLocaleInfo(LOCALE_USER_DEFAULT, LOCALE_ILDATE, out, 255);
         QString winstr = QString::fromWCharArray(out);
         switch (winstr.toInt()) {
         case 1:
             buf = d->date.shortDayName(d->date.dayOfWeek());
             buf += QLatin1Char(' ');
             buf += QString::number(d->date.day());
             buf += QLatin1String(". ");
             buf += d->date.shortMonthName(d->date.month());
             break;
         default:
             buf = d->date.shortDayName(d->date.dayOfWeek());
             buf += QLatin1Char(' ');
             buf += d->date.shortMonthName(d->date.month());
             buf += QLatin1Char(' ');
             buf += QString::number(d->date.day());
         }
 #endif
         buf += QLatin1Char(' ');
         buf += d->time.toString();
         buf += QLatin1Char(' ');
         buf += QString::number(d->date.year());
     }
 #endif
     else {
         buf = d->date.toString(f);
         if (buf.isEmpty())
             return QString();   // failed to convert
         buf += QLatin1Char(' ');
         buf += d->time.toString(f);
     }
     return buf;
 }
toString() [2/2]
QString QDateTime::toString (const QString & format) const
Returns the datetime as a string.
The format parameter determines the format of the result string.
These expressions may be used for the date:
Expression Output
d the day as number without a leading zero (1 to 31)
dd the day as number with a leading zero (01 to 31)
ddd the abbreviated localized day name (e.g. 'Mon' to 'Sun'). Uses QDate::shortDayName().
dddd the long localized day name (e.g. 'Monday' to 'Qt::Sunday'). Uses QDate::longDayName().
M the month as number without a leading zero (1-12)
MM the month as number with a leading zero (01-12)
MMM the abbreviated localized month name (e.g. 'Jan' to 'Dec'). Uses QDate::shortMonthName().
MMMM the long localized month name (e.g. 'January' to 'December'). Uses QDate::longMonthName().
yy the year as two digit number (00-99)
yyyy the year as four digit number
These expressions may be used for the time:
Expression Output
h the hour without a leading zero (0 to 23 or 1 to 12 if AM/PM display)
hh the hour with a leading zero (00 to 23 or 01 to 12 if AM/PM display)
m the minute without a leading zero (0 to 59)
mm the minute with a leading zero (00 to 59)
s the second without a leading zero (0 to 59)
ss the second with a leading zero (00 to 59)
z the milliseconds without leading zeroes (0 to 999)
zzz the milliseconds with leading zeroes (000 to 999)
AP use AM/PM display. AP will be replaced by either "AM" or "PM".
ap use am/pm display. ap will be replaced by either "am" or "pm".
All other input characters will be ignored. Any sequence of characters that are enclosed in singlequotes will be treated as text and not be used as an expression. Two consecutive singlequotes ("''") are replaced by a singlequote in the output.
Example format strings (assumed that the QDateTime is 21 May 2001 14:13:09):
Format Result
dd.MM.yyyy 21.05.2001
ddd MMMM d yy Tue May 21 01
hh:mm:ss.zzz 14:13:09.042
h:m:s ap 2:13:9 pm
If the datetime is invalid, an empty string will be returned.
See also
QDate::toString() QTime::toString()
Definition at line 2769 of file qdatetime.cpp.
 {
     return fmtDateTime(format, &d->time, &d->date);
 }
toTime_t()
uint QDateTime::toTime_t () const
Returns the datetime as the number of seconds that have passed since 1970-01-01T00:00:00, Coordinated Universal Time (Qt::UTC).
On systems that do not support time zones, this function will behave as if local time were Qt::UTC.
Note
This function returns a 32-bit unsigned integer, so it does not support dates before 1970, but it does support dates after 2038-01-19T03:14:06, which may not be valid time_t values. Be careful when passing those time_t values to system functions, which could interpret them as negative dates.
If the date is outside the range 1970-01-01T00:00:00 to 2106-02-07T06:28:14, this function returns -1 cast to an unsigned integer (i.e., 0xFFFFFFFF).
To get an extended range, use toMSecsSinceEpoch().
See also
toMSecsSinceEpoch(), setTime_t()
Definition at line 2505 of file qdatetime.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), QPixmap::load(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), qEncodeNtlmv2Response(), and qt_CoCreateGuid().
 {
     qint64 retval = toMSecsSinceEpoch() / 1000;
     if (quint64(retval) >= Q_UINT64_C(0xFFFFFFFF))
         return uint(-1);
     return uint(retval);
 }
toTimeSpec()
QDateTime QDateTime::toTimeSpec (Qt::TimeSpec specification) const
Returns a copy of this datetime configured to use the given time specification.
See also
timeSpec(), toUTC(), toLocalTime()
Definition at line 2969 of file qdatetime.cpp.
Referenced by QDateTimeParser::parse(), QDateTimeEdit::setDateTimeRange(), QDateTimeEdit::setMaximumDateTime(), QDateTimeEdit::setMinimumDateTime(), QDateTimeEditPrivate::stepBy(), and QDateTimeEditPrivate::updateTimeSpec().
 {
     if ((d->spec == QDateTimePrivate::UTC) == (spec == Qt::UTC))
         return *this;
     QDateTime ret;
     if (spec == Qt::UTC) {
         d->getUTC(ret.d->date, ret.d->time);
         ret.d->spec = QDateTimePrivate::UTC;
     } else {
         ret.d->spec = d->getLocal(ret.d->date, ret.d->time);
     }
     return ret;
 }
toUTC()
QDateTime QDateTime::toUTC () const inline
Returns a datetime containing the date and time information in this datetime, but specified using the Qt::UTC definition.
See also
toTimeSpec()
Definition at line 251 of file qdatetime.h.
Referenced by QScript::DateTimeToMs(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QNetworkCookie::operator==(), operator>=(), QNetworkCookiePrivate::parseSetCookieHeaderLine(), QPatternist::AtomicValue::toQt(), QNetworkCookie::toRawForm(), and QPdfEnginePrivate::writeInfo().
 { return toTimeSpec(Qt::UTC); }
utcOffset()
int QDateTime::utcOffset () const
Since
4.4
Warning
This function is not part of the public interface.
Returns the UTC offset in seconds. If the timeSpec() isn't Qt::OffsetFromUTC, 0 is returned. However, since 0 is a valid UTC offset the return value of this function cannot be used to determine whether a utcOffset() is used or is valid, timeSpec() must be checked.
Likewise, if this QDateTime() is invalid or if timeSpec() isn't Qt::OffsetFromUTC, 0 is returned.
The UTC offset only applies if the timeSpec() is Qt::OffsetFromUTC.
See also
isValid(), setUtcOffset()
Definition at line 3449 of file qdatetime.cpp.
Referenced by QPatternist::AbstractDateTime::copyTimeSpec(), QPatternist::TimezoneFromAbstractDateTimeFN::extract(), fromString(), QDateTimePrivate::getUTC(), and QPatternist::AbstractDateTime::zoneOffsetToString().
 {
     if(isValid() && d->spec == QDateTimePrivate::OffsetFromUTC)
         return d->utcOffset;
     else
         return 0;
 }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & out, const QDateTime & dateTime) friend
Writes dateTime to the out stream.
See also
{Serializing Qt Data Types}
Definition at line 3881 of file qdatetime.cpp.
 {
     out << dateTime.d->date << dateTime.d->time;
     if (out.version() >= 7)
         out << (qint8)dateTime.d->spec;
     return out;
 }
operator>>
QDataStream & operator>> (QDataStream & in, QDateTime & dateTime) friend
Reads a datetime from the stream in into dateTime.
See also
{Serializing Qt Data Types}
Definition at line 3900 of file qdatetime.cpp.
 {
     dateTime.detach();
     qint8 ts = (qint8)QDateTimePrivate::LocalUnknown;
     in >> dateTime.d->date >> dateTime.d->time;
     if (in.version() >= 7)
         in >> ts;
     dateTime.d->spec = (QDateTimePrivate::Spec)ts;
     return in;
 }
QDateTimePrivate
friend class QDateTimePrivate friend
Definition at line 292 of file qdatetime.h.
Properties
d
QExplicitlySharedDataPointer<QDateTimePrivate> QDateTime::d private
Definition at line 294 of file qdatetime.h.
Referenced by addDays(), addMonths(), QDateTimePrivate::addMSecs(), addMSecs(), addSecs(), addYears(), QDate::currentDate(), currentDateTime(), currentDateTimeUtc(), currentMSecsSinceEpoch(), date(), daysTo(), detach(), fromMSecsSinceEpoch(), QDateTimeParser::fromString(), fromTime_t(), isNull(), isValid(), msecsTo(), operator<(), operator=(), operator==(), QDateTime(), secsTo(), setDate(), setMSecsSinceEpoch(), setTime(), setTime_t(), setTimeSpec(), setUtcOffset(), time(), timeSpec(), toMSecsSinceEpoch(), toString(), toTimeSpec(), and utcOffset().
The documentation for this class was generated from the following files:
/src/corelib/tools/qdatetime.h
/src/corelib/tools/qdatetime.cpp