Qt 4.8: QScriptDebuggerConsoleGlobalObject Class Reference
QScriptDebuggerConsoleGlobalObject Class Reference
#include <qscriptdebuggerconsoleglobalobject_p.h>
Public Slots
bool checkSyntax (const QString &program)
void error (const QString &text, const QString &fileName=QString(), int lineNumber=-1, int columnNumber=-1)
QScriptDebuggerConsoleCommand * findCommand (const QString &command) const
QStringList getCommandCompletions (const QString &prefix) const
QScriptDebuggerConsoleCommandGroupMap getCommandGroups () const
QScriptDebuggerConsoleCommandList getCommandsInGroup (const QString &name) const
int getCurrentFrameIndex () const
int getCurrentLineNumber () const
qint64 getCurrentScriptId () const
qint64 getSessionId () const
void message (const QString &text, const QString &fileName=QString(), int lineNumber=-1, int columnNumber=-1)
int scheduleClearExceptions ()
int scheduleCommand (const QScriptDebuggerCommand &command)
int scheduleContinue ()
int scheduleDeleteAllBreakpoints ()
int scheduleDeleteBreakpoint (int id)
int scheduleDeleteScriptValueIterator (int id)
int scheduleEvaluate (int contextIndex, const QString &program, const QString &fileName=QString(), int lineNumber=1)
int scheduleForceReturn (int contextIndex, const QScriptDebuggerValue &value)
int scheduleGetActivationObject (int contextIndex)
int scheduleGetBacktrace ()
int scheduleGetBreakpointData (int id)
int scheduleGetBreakpoints ()
int scheduleGetContextCount ()
int scheduleGetContextInfo (int contextIndex)
int scheduleGetPropertiesByIterator (int id, int count)
int scheduleGetScriptData (qint64 id)
int scheduleGetScripts ()
int scheduleGetScriptsDelta ()
int scheduleGetThisObject (int contextIndex)
int scheduleInterrupt ()
int scheduleNewScriptValueIterator (const QScriptDebuggerValue &object)
int scheduleResolveScript (const QString &fileName)
int scheduleRunToLocation (const QString &fileName, int lineNumber)
int scheduleRunToLocation (qint64 scriptId, int lineNumber)
int scheduleScriptsCheckpoint ()
int scheduleScriptValueToString (const QScriptDebuggerValue &value)
int scheduleSetBreakpoint (const QScriptBreakpointData &data)
int scheduleSetBreakpointData (int id, const QScriptBreakpointData &data)
int scheduleStepInto (int count=1)
int scheduleStepOut ()
int scheduleStepOver (int count=1)
void setCurrentFrameIndex (int index)
void setCurrentLineNumber (int lineNumber)
void setCurrentScriptId (qint64 id)
void setEvaluateAction (int action)
void warning (const QString &text, const QString &fileName=QString(), int lineNumber=-1, int columnNumber=-1)
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
QScriptDebuggerConsole * console () const
QScriptMessageHandlerInterface * messageHandler () const
QScriptDebuggerConsoleGlobalObject (QObject *parent=0)
QScriptDebuggerResponseHandlerInterface * responseHandler () const
QScriptDebuggerCommandSchedulerInterface * scheduler () const
void setConsole (QScriptDebuggerConsole *console)
void setMessageHandler (QScriptMessageHandlerInterface *messageHandler)
void setResponseHandler (QScriptDebuggerResponseHandlerInterface *responseHandler)
void setScheduler (QScriptDebuggerCommandSchedulerInterface *scheduler)
~QScriptDebuggerConsoleGlobalObject ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 74 of file qscriptdebuggerconsoleglobalobject_p.h.
Constructors and Destructors
QScriptDebuggerConsoleGlobalObject()
QScriptDebuggerConsoleGlobalObject::QScriptDebuggerConsoleGlobalObject (QObject * parent = 0)
Definition at line 80 of file qscriptdebuggerconsoleglobalobject.cpp.
     : QObject(*new QScriptDebuggerConsoleGlobalObjectPrivate, parent)
 {
 }
~QScriptDebuggerConsoleGlobalObject()
QScriptDebuggerConsoleGlobalObject::~QScriptDebuggerConsoleGlobalObject ()
Definition at line 85 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
 }
Functions
checkSyntax
bool QScriptDebuggerConsoleGlobalObject::checkSyntax (const QString & program) slot
Definition at line 452 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     return (QScriptEngine::checkSyntax(program).state() == QScriptSyntaxCheckResult::Valid);
 }
console()
QScriptDebuggerConsole * QScriptDebuggerConsoleGlobalObject::console () const
Definition at line 126 of file qscriptdebuggerconsoleglobalobject.cpp.
Referenced by setConsole().
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->console;
 }
error
void QScriptDebuggerConsoleGlobalObject::error (const QString & text, const QString & fileName = QString(), int lineNumber = -1, int columnNumber = -1) slot
Definition at line 377 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     Q_ASSERT(d->messageHandler != 0);
     d->messageHandler->message(QtCriticalMsg, text, fileName, lineNumber, columnNumber);
 }
findCommand
QScriptDebuggerConsoleCommand * QScriptDebuggerConsoleGlobalObject::findCommand (const QString & command) const slot
Definition at line 434 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->console->commandManager()->findCommand(name);
 }
getCommandCompletions
QStringList QScriptDebuggerConsoleGlobalObject::getCommandCompletions (const QString & prefix) const slot
Definition at line 446 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->console->commandManager()->completions(prefix);
 }
getCommandGroups
QScriptDebuggerConsoleCommandGroupMap QScriptDebuggerConsoleGlobalObject::getCommandGroups () const slot
Definition at line 428 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->console->commandManager()->commandGroups();
 }
getCommandsInGroup
QScriptDebuggerConsoleCommandList QScriptDebuggerConsoleGlobalObject::getCommandsInGroup (const QString & name) const slot
Definition at line 440 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->console->commandManager()->commandsInGroup(name);
 }
getCurrentFrameIndex
int QScriptDebuggerConsoleGlobalObject::getCurrentFrameIndex () const slot
Definition at line 386 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->console->currentFrameIndex();
 }
getCurrentLineNumber
int QScriptDebuggerConsoleGlobalObject::getCurrentLineNumber () const slot
Definition at line 398 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->console->currentLineNumber();
 }
getCurrentScriptId
qint64 QScriptDebuggerConsoleGlobalObject::getCurrentScriptId () const slot
Definition at line 410 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->console->currentScriptId();
 }
getSessionId
qint64 QScriptDebuggerConsoleGlobalObject::getSessionId () const slot
Definition at line 422 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->console->sessionId();
 }
message
void QScriptDebuggerConsoleGlobalObject::message (const QString & text, const QString & fileName = QString(), int lineNumber = -1, int columnNumber = -1) slot
Definition at line 368 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     Q_ASSERT(d->messageHandler != 0);
     d->messageHandler->message(QtDebugMsg, text, fileName, lineNumber, columnNumber);
 }
messageHandler()
QScriptMessageHandlerInterface * QScriptDebuggerConsoleGlobalObject::messageHandler () const
Definition at line 114 of file qscriptdebuggerconsoleglobalobject.cpp.
Referenced by setMessageHandler().
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->messageHandler;
 }
responseHandler()
QScriptDebuggerResponseHandlerInterface * QScriptDebuggerConsoleGlobalObject::responseHandler () const
Definition at line 101 of file qscriptdebuggerconsoleglobalobject.cpp.
Referenced by setResponseHandler().
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->responseHandler;
 }
scheduleClearExceptions
int QScriptDebuggerConsoleGlobalObject::scheduleClearExceptions () slot
Definition at line 346 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleClearExceptions();
 }
scheduleCommand
int QScriptDebuggerConsoleGlobalObject::scheduleCommand (const QScriptDebuggerCommand & command) slot
Definition at line 353 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     return d->scheduler->scheduleCommand(command, d->responseHandler);
 }
scheduleContinue
int QScriptDebuggerConsoleGlobalObject::scheduleContinue () slot
Definition at line 148 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleContinue();
 }
scheduleDeleteAllBreakpoints
int QScriptDebuggerConsoleGlobalObject::scheduleDeleteAllBreakpoints () slot
Definition at line 211 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleDeleteAllBreakpoints();
 }
scheduleDeleteBreakpoint
int QScriptDebuggerConsoleGlobalObject::scheduleDeleteBreakpoint (int id) slot
Definition at line 204 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleDeleteBreakpoint(id);
 }
scheduleDeleteScriptValueIterator
int QScriptDebuggerConsoleGlobalObject::scheduleDeleteScriptValueIterator (int id) slot
Definition at line 323 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleDeleteScriptValueIterator(id);
 }
scheduleEvaluate
int QScriptDebuggerConsoleGlobalObject::scheduleEvaluate (int contextIndex, const QString & program, const QString & fileName = QString(), int lineNumber = 1) slot
Definition at line 330 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleEvaluate(contextIndex, program, fileName, lineNumber);
 }
scheduleForceReturn
int QScriptDebuggerConsoleGlobalObject::scheduleForceReturn (int contextIndex, const QScriptDebuggerValue & value) slot
Definition at line 190 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleForceReturn(contextIndex, value);
 }
scheduleGetActivationObject
int QScriptDebuggerConsoleGlobalObject::scheduleGetActivationObject (int contextIndex) slot
Definition at line 288 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleGetActivationObject(contextIndex);
 }
scheduleGetBacktrace
int QScriptDebuggerConsoleGlobalObject::scheduleGetBacktrace () slot
Definition at line 274 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleGetBacktrace();
 }
scheduleGetBreakpointData
int QScriptDebuggerConsoleGlobalObject::scheduleGetBreakpointData (int id) slot
Definition at line 225 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleGetBreakpointData(id);
 }
scheduleGetBreakpoints
int QScriptDebuggerConsoleGlobalObject::scheduleGetBreakpoints () slot
Definition at line 218 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleGetBreakpoints();
 }
scheduleGetContextCount
int QScriptDebuggerConsoleGlobalObject::scheduleGetContextCount () slot
Definition at line 295 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleGetContextCount();
 }
scheduleGetContextInfo
int QScriptDebuggerConsoleGlobalObject::scheduleGetContextInfo (int contextIndex) slot
Definition at line 302 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleGetContextInfo(contextIndex);
 }
scheduleGetPropertiesByIterator
int QScriptDebuggerConsoleGlobalObject::scheduleGetPropertiesByIterator (int id, int count) slot
Definition at line 316 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleGetPropertiesByIterator(id, count);
 }
scheduleGetScriptData
int QScriptDebuggerConsoleGlobalObject::scheduleGetScriptData (qint64 id) slot
Definition at line 246 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleGetScriptData(id);
 }
scheduleGetScripts
int QScriptDebuggerConsoleGlobalObject::scheduleGetScripts () slot
Definition at line 239 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleGetScripts();
 }
scheduleGetScriptsDelta
int QScriptDebuggerConsoleGlobalObject::scheduleGetScriptsDelta () slot
Definition at line 260 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleGetScriptsDelta();
 }
scheduleGetThisObject
int QScriptDebuggerConsoleGlobalObject::scheduleGetThisObject (int contextIndex) slot
Definition at line 281 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleGetThisObject(contextIndex);
 }
scheduleInterrupt
int QScriptDebuggerConsoleGlobalObject::scheduleInterrupt () slot
Definition at line 141 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleInterrupt();
 }
scheduleNewScriptValueIterator
int QScriptDebuggerConsoleGlobalObject::scheduleNewScriptValueIterator (const QScriptDebuggerValue & object) slot
Definition at line 309 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleNewScriptValueIterator(object);
 }
scheduler()
QScriptDebuggerCommandSchedulerInterface * QScriptDebuggerConsoleGlobalObject::scheduler () const
Definition at line 89 of file qscriptdebuggerconsoleglobalobject.cpp.
Referenced by setScheduler().
 {
     Q_D(const QScriptDebuggerConsoleGlobalObject);
     return d->scheduler;
 }
scheduleResolveScript
int QScriptDebuggerConsoleGlobalObject::scheduleResolveScript (const QString & fileName) slot
Definition at line 267 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleResolveScript(fileName);
 }
scheduleRunToLocation [1/2]
int QScriptDebuggerConsoleGlobalObject::scheduleRunToLocation (const QString & fileName, int lineNumber) slot
Definition at line 176 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleRunToLocation(fileName, lineNumber);
 }
scheduleRunToLocation [2/2]
int QScriptDebuggerConsoleGlobalObject::scheduleRunToLocation (qint64 scriptId, int lineNumber) slot
Definition at line 183 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleRunToLocation(scriptId, lineNumber);
 }
scheduleScriptsCheckpoint
int QScriptDebuggerConsoleGlobalObject::scheduleScriptsCheckpoint () slot
Definition at line 253 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleScriptsCheckpoint();
 }
scheduleScriptValueToString
int QScriptDebuggerConsoleGlobalObject::scheduleScriptValueToString (const QScriptDebuggerValue & value) slot
Definition at line 339 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleScriptValueToString(value);
 }
scheduleSetBreakpoint
int QScriptDebuggerConsoleGlobalObject::scheduleSetBreakpoint (const QScriptBreakpointData & data) slot
Definition at line 197 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleSetBreakpoint(data);
 }
scheduleSetBreakpointData
int QScriptDebuggerConsoleGlobalObject::scheduleSetBreakpointData (int id, const QScriptBreakpointData & data) slot
Definition at line 232 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleSetBreakpointData(id, data);
 }
scheduleStepInto
int QScriptDebuggerConsoleGlobalObject::scheduleStepInto (int count = 1) slot
Definition at line 155 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleStepInto(count);
 }
scheduleStepOut
int QScriptDebuggerConsoleGlobalObject::scheduleStepOut () slot
Definition at line 169 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleStepOut();
 }
scheduleStepOver
int QScriptDebuggerConsoleGlobalObject::scheduleStepOver (int count = 1) slot
Definition at line 162 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     QScriptDebuggerCommandSchedulerFrontend frontend(d->scheduler, d->responseHandler);
     return frontend.scheduleStepOver(count);
 }
setConsole()
void QScriptDebuggerConsoleGlobalObject::setConsole (QScriptDebuggerConsole * console)
Definition at line 132 of file qscriptdebuggerconsoleglobalobject.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommandJob::handleResponse(), and QScriptDebuggerScriptedConsoleCommandJob::start().
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     d->console = console;
 }
setCurrentFrameIndex
void QScriptDebuggerConsoleGlobalObject::setCurrentFrameIndex (int index) slot
Definition at line 392 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     d->console->setCurrentFrameIndex(index);
 }
setCurrentLineNumber
void QScriptDebuggerConsoleGlobalObject::setCurrentLineNumber (int lineNumber) slot
Definition at line 404 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     d->console->setCurrentLineNumber(lineNumber);
 }
setCurrentScriptId
void QScriptDebuggerConsoleGlobalObject::setCurrentScriptId (qint64 id) slot
Definition at line 416 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     d->console->setCurrentScriptId(id);
 }
setEvaluateAction
void QScriptDebuggerConsoleGlobalObject::setEvaluateAction (int action) slot
Definition at line 457 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     d->console->setEvaluateAction(action);
 }
setMessageHandler()
void QScriptDebuggerConsoleGlobalObject::setMessageHandler (QScriptMessageHandlerInterface * messageHandler)
Definition at line 120 of file qscriptdebuggerconsoleglobalobject.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommandJob::handleResponse(), QScriptDebuggerScriptedConsoleCommand::parse(), and QScriptDebuggerScriptedConsoleCommandJob::start().
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     d->messageHandler = messageHandler;
 }
setResponseHandler()
void QScriptDebuggerConsoleGlobalObject::setResponseHandler (QScriptDebuggerResponseHandlerInterface * responseHandler)
Definition at line 107 of file qscriptdebuggerconsoleglobalobject.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommandJob::handleResponse(), and QScriptDebuggerScriptedConsoleCommandJob::start().
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     d->responseHandler = responseHandler;
 }
setScheduler()
void QScriptDebuggerConsoleGlobalObject::setScheduler (QScriptDebuggerCommandSchedulerInterface * scheduler)
Definition at line 95 of file qscriptdebuggerconsoleglobalobject.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommandJob::handleResponse(), and QScriptDebuggerScriptedConsoleCommandJob::start().
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     d->scheduler = scheduler;
 }
warning
void QScriptDebuggerConsoleGlobalObject::warning (const QString & text, const QString & fileName = QString(), int lineNumber = -1, int columnNumber = -1) slot
Definition at line 359 of file qscriptdebuggerconsoleglobalobject.cpp.
 {
     Q_D(QScriptDebuggerConsoleGlobalObject);
     Q_ASSERT(d->messageHandler != 0);
     d->messageHandler->message(QtWarningMsg, text, fileName, lineNumber, columnNumber);
 }
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerconsoleglobalobject_p.h
/src/scripttools/debugging/qscriptdebuggerconsoleglobalobject.cpp