Qt 4.8: quint32p Class Reference
quint32p Class Reference
#include <qdrawhelper_p.h>
Public Functions
Q_STATIC_INLINE_FUNCTION quint32p fromRawData (quint32 v)
operator quint16 () const
operator quint32 () const
quint32p (quint32 v)
Private Functions
quint32p ()
Properties
quint32 data
Detailed Description
Definition at line 709 of file qdrawhelper_p.h.
Constructors and Destructors
quint32p() [1/2]
quint32p::quint32p (quint32 v) inline
Definition at line 712 of file qdrawhelper_p.h.
 : data(PREMUL(v)) {}
quint32p() [2/2]
quint32p::quint32p () inline private
Definition at line 729 of file qdrawhelper_p.h.
 {}
Functions
fromRawData()
Q_STATIC_INLINE_FUNCTION quint32p quint32p::fromRawData (quint32 v) inline
Definition at line 721 of file qdrawhelper_p.h.
Referenced by blendColor(), qt_rectfill_template(), and QImage::setPixel().
     {
         quint32p p;
         p.data = v;
         return p;
     }
operator quint16()
quint32p::operator quint16 () const inline
Definition at line 716 of file qdrawhelper_p.h.
     {
         return qt_colorConvert<quint16, quint32>(data, 0);
     }
operator quint32()
quint32p::operator quint32 () const inline
Definition at line 714 of file qdrawhelper_p.h.
 { return data; }
Properties
data
quint32 quint32p::data private
Definition at line 730 of file qdrawhelper_p.h.
Referenced by fromRawData().
The documentation for this class was generated from the following file:
/src/gui/painting/qdrawhelper_p.h