Qt 4.8: QMutexPrivate Class Reference
QMutexPrivate Class Reference
#include <qmutex_p.h>
Public Types
enum { MaximumSpinTimeThreshold = 1000000 }
Public Functions
QMutexPrivate (QMutex::RecursionMode mode)
bool wait (int timeout=-1)
void wakeUp ()
~QMutexPrivate ()
Public Variables
volatile qint64 averageWaitTime
uint count
HANDLE event
volatile qint64 maximumSpinTime
Qt::HANDLE owner
Public Variables inherited from QMutexData
QAtomicInt contenders
const uint recursive: 1
uint reserved: 31
Additional Inherited Members
Protected Functions inherited from QMutexData
QMutexData (QMutex::RecursionMode mode)
~QMutexData ()
Detailed Description
Definition at line 67 of file qmutex_p.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
MaximumSpinTimeThreshold
Definition at line 76 of file qmutex_p.h.
 { MaximumSpinTimeThreshold = 1000000 };
Constructors and Destructors
QMutexPrivate()
QMutexPrivate::QMutexPrivate (QMutex::RecursionMode mode)
Definition at line 77 of file qmutex_unix.cpp.
     : QMutexData(mode), maximumSpinTime(MaximumSpinTimeThreshold), averageWaitTime(0), owner(0), count(0)
 {
 #if !defined(Q_OS_LINUX) || defined(QT_LINUXBASE)
     wakeup = false;
     report_error(pthread_mutex_init(&mutex, NULL), "QMutex", "mutex init");
     report_error(pthread_cond_init(&cond, NULL), "QMutex", "cv init");
 #endif
 }
~QMutexPrivate()
QMutexPrivate::~QMutexPrivate ()
Definition at line 87 of file qmutex_unix.cpp.
 {
 #if !defined(Q_OS_LINUX) || defined(QT_LINUXBASE)
     report_error(pthread_cond_destroy(&cond), "QMutex", "cv destroy");
     report_error(pthread_mutex_destroy(&mutex), "QMutex", "mutex destroy");
 #endif
 }
Functions
wait()
bool QMutexPrivate::wait (int timeout = -1)
Definition at line 102 of file qmutex_unix.cpp.
Referenced by QMutex::lock(), QMutex::lockInternal(), and QMutex::tryLock().
 {
     struct timespec ts, *pts = 0;
     QElapsedTimer timer;
     if (timeout >= 0) {
         ts.tv_nsec = ((timeout % 1000) * 1000) * 1000;
         ts.tv_sec = (timeout / 1000);
         pts = &ts;
         timer.start();
     }
     while (contenders.fetchAndStoreAcquire(2) > 0) {
         int r = _q_futex(&contenders._q_value, FUTEX_WAIT, 2, pts, 0, 0);
         if (r != 0 && errno == ETIMEDOUT)
             return false;
         if (pts) {
             // recalculate the timeout
             qint64 xtimeout = timeout * 1000 * 1000;
             xtimeout -= timer.nsecsElapsed();
             if (xtimeout < 0) {
                 // timer expired after we returned
                 return false;
             }
             ts.tv_sec = xtimeout / Q_INT64_C(1000) / 1000 / 1000;
             ts.tv_nsec = xtimeout % (Q_INT64_C(1000) * 1000 * 1000);
         }
     }
     return true;
 }
wakeUp()
void QMutexPrivate::wakeUp ()
Definition at line 133 of file qmutex_unix.cpp.
Referenced by QMutex::unlock().
 {
     (void) contenders.fetchAndStoreRelease(0);
     (void) _q_futex(&contenders._q_value, FUTEX_WAKE, 1, 0, 0, 0);
 }
Properties
averageWaitTime
volatile qint64 QMutexPrivate::averageWaitTime
Definition at line 78 of file qmutex_p.h.
Referenced by QMutex::lockInternal().
count
uint QMutexPrivate::count
Definition at line 80 of file qmutex_p.h.
Referenced by QMutex::lock(), QMutex::tryLock(), and QMutex::unlock().
event
HANDLE QMutexPrivate::event
Definition at line 87 of file qmutex_p.h.
maximumSpinTime
volatile qint64 QMutexPrivate::maximumSpinTime
Definition at line 77 of file qmutex_p.h.
Referenced by QMutex::lockInternal().
owner
Qt::HANDLE QMutexPrivate::owner
Definition at line 79 of file qmutex_p.h.
Referenced by QMutex::lock(), QMutex::tryLock(), and QMutex::unlock().
The documentation for this class was generated from the following files:
/src/corelib/thread/qmutex_p.h
/src/corelib/thread/qmutex_unix.cpp
/src/corelib/thread/qmutex_win.cpp