Qt 4.8: QDeclarativeDomDynamicProperty Class Reference
QDeclarativeDomDynamicProperty Class Reference
#include <qdeclarativedom_p.h>
Public Functions
QDeclarativeDomProperty defaultValue () const
Returns the default value as a QDeclarativeDomProperty.
bool isAlias () const
Returns true if this dynamic property is an alias for another property, false otherwise.
bool isDefaultProperty () const
Return true if this property is used as a default property in the QML document.
bool isValid () const
int length () const
Returns the length in the input data from where the property ID started upto the end of it, or 0 if the property is invalid.
QDeclarativeDomDynamicProperty & operator= (const QDeclarativeDomDynamicProperty &)
Assign other to this QDeclarativeDomDynamicProperty.
int position () const
Returns the position in the input data where the property ID startd, or 0 if the property is invalid.
QByteArray propertyName () const
Return the name of this dynamic property.
int propertyType () const
Returns the type of the dynamic property.
QByteArray propertyTypeName () const
QDeclarativeDomDynamicProperty ()
Construct an invalid QDeclarativeDomDynamicProperty.
QDeclarativeDomDynamicProperty (const QDeclarativeDomDynamicProperty &)
Create a copy of other QDeclarativeDomDynamicProperty.
~QDeclarativeDomDynamicProperty ()
Destroy the QDeclarativeDomDynamicProperty.
Properties
QSharedDataPointer< QDeclarativeDomDynamicPropertyPrivate > d
Friends
class QDeclarativeDomObject
Detailed Description
Definition at line 128 of file qdeclarativedom_p.h.
Constructors and Destructors
QDeclarativeDomDynamicProperty() [1/2]
QDeclarativeDomDynamicProperty::QDeclarativeDomDynamicProperty ()
Construct an invalid QDeclarativeDomDynamicProperty.
Definition at line 405 of file qdeclarativedom.cpp.
                                                               :
         d(new QDeclarativeDomDynamicPropertyPrivate)
 {
 }
QDeclarativeDomDynamicProperty() [2/2]
QDeclarativeDomDynamicProperty::QDeclarativeDomDynamicProperty (const QDeclarativeDomDynamicProperty & other)
Create a copy of other QDeclarativeDomDynamicProperty.
Definition at line 413 of file qdeclarativedom.cpp.
                                                                                                          :
         d(other.d)
 {
 }
~QDeclarativeDomDynamicProperty()
QDeclarativeDomDynamicProperty::~QDeclarativeDomDynamicProperty ()
Destroy the QDeclarativeDomDynamicProperty.
Definition at line 421 of file qdeclarativedom.cpp.
 {
 }
Functions
defaultValue()
QDeclarativeDomProperty QDeclarativeDomDynamicProperty::defaultValue () const
Returns the default value as a QDeclarativeDomProperty.
Definition at line 540 of file qdeclarativedom.cpp.
 {
     QDeclarativeDomProperty rp;
     if (isValid() && d->property.defaultValue) {
         rp.d->property = d->property.defaultValue;
         rp.d->propertyName = propertyName();
         rp.d->property->addref();
     }
     return rp;
 }
isAlias()
bool QDeclarativeDomDynamicProperty::isAlias () const
Returns true if this dynamic property is an alias for another property, false otherwise.
Definition at line 557 of file qdeclarativedom.cpp.
 {
     if (isValid())
         return d->property.type == QDeclarativeParser::Object::DynamicProperty::Alias;
     else
         return false;
 }
isDefaultProperty()
bool QDeclarativeDomDynamicProperty::isDefaultProperty () const
Return true if this property is used as a default property in the QML document.
<Text text="hello"/>
<Text>hello</Text>
The above two examples return the same DOM tree, except that the second has the default property flag set on the text property. Observe that whether or not a property has isDefaultProperty set is determined by how the property is used, and not only by whether the property is the types default property.
Definition at line 529 of file qdeclarativedom.cpp.
 {
     if (isValid())
         return d->property.isDefaultProperty;
     else
         return false;
 }
isValid()
bool QDeclarativeDomDynamicProperty::isValid () const
Definition at line 434 of file qdeclarativedom.cpp.
Referenced by defaultValue(), isAlias(), isDefaultProperty(), length(), position(), propertyName(), propertyType(), and propertyTypeName().
 {
     return d && d->valid;
 }
length()
int QDeclarativeDomDynamicProperty::length () const
Returns the length in the input data from where the property ID started upto the end of it, or 0 if the property is invalid.
Definition at line 581 of file qdeclarativedom.cpp.
 {
     if (isValid())
         return d->property.location.range.length;
     else
         return -1;
 }
operator=()
QDeclarativeDomDynamicProperty & QDeclarativeDomDynamicProperty::operator= (const QDeclarativeDomDynamicProperty & other)
Assign other to this QDeclarativeDomDynamicProperty.
Definition at line 428 of file qdeclarativedom.cpp.
 {
     d = other.d;
     return *this;
 }
position()
int QDeclarativeDomDynamicProperty::position () const
Returns the position in the input data where the property ID startd, or 0 if the property is invalid.
Definition at line 569 of file qdeclarativedom.cpp.
 {
     if (isValid()) {
         return d->property.location.range.offset;
     } else
         return -1;
 }
propertyName()
QByteArray QDeclarativeDomDynamicProperty::propertyName () const
Return the name of this dynamic property.
Item {
    property int count: 10;
}
As illustrated above, a dynamic property name can have a name and a default value ("10").
Definition at line 451 of file qdeclarativedom.cpp.
Referenced by defaultValue().
 {
     if (isValid())
         return d->property.name;
     else
         return QByteArray();
 }
propertyType()
int QDeclarativeDomDynamicProperty::propertyType () const
Returns the type of the dynamic property.
Note that when the property is an alias property, this will return -1. Use QDeclarativeDomProperty::isAlias() to check if the property is an alias.
Definition at line 464 of file qdeclarativedom.cpp.
 {
     if (isValid()) {
         switch (d->property.type) {
             case QDeclarativeParser::Object::DynamicProperty::Bool:
                 return QMetaType::type("bool");
             case QDeclarativeParser::Object::DynamicProperty::Color:
                 return QMetaType::type("QColor");
             case QDeclarativeParser::Object::DynamicProperty::Time:
                 return QMetaType::type("QTime");
             case QDeclarativeParser::Object::DynamicProperty::Date:
                 return QMetaType::type("QDate");
             case QDeclarativeParser::Object::DynamicProperty::DateTime:
                 return QMetaType::type("QDateTime");
             case QDeclarativeParser::Object::DynamicProperty::Int:
                 return QMetaType::type("int");
             case QDeclarativeParser::Object::DynamicProperty::Real:
                 return sizeof(qreal) == sizeof(double) ? QMetaType::type("double") : QMetaType::type("float");
             case QDeclarativeParser::Object::DynamicProperty::String:
                 return QMetaType::type("QString");
             case QDeclarativeParser::Object::DynamicProperty::Url:
                 return QMetaType::type("QUrl");
             case QDeclarativeParser::Object::DynamicProperty::Variant:
                 return QMetaType::type("QVariant");
             default:
                 break;
         }
     }
     return -1;
 }
propertyTypeName()
QByteArray QDeclarativeDomDynamicProperty::propertyTypeName () const
Definition at line 506 of file qdeclarativedom.cpp.
 {
     if (isValid())
         return d->property.customType;
     return QByteArray();
 }
Friends and Related Functions
QDeclarativeDomObject
friend class QDeclarativeDomObject friend
Definition at line 151 of file qdeclarativedom_p.h.
Properties
d
QSharedDataPointer<QDeclarativeDomDynamicPropertyPrivate> QDeclarativeDomDynamicProperty::d private
Definition at line 152 of file qdeclarativedom_p.h.
Referenced by defaultValue(), QDeclarativeDomObject::dynamicProperties(), QDeclarativeDomObject::dynamicProperty(), isAlias(), isDefaultProperty(), isValid(), length(), operator=(), position(), propertyName(), propertyType(), and propertyTypeName().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativedom_p.h
/src/declarative/qml/qdeclarativedom.cpp