Qt 4.8: QSignalTransition Class Reference
QSignalTransition Class Reference
The QSignalTransition class provides a transition based on a Qt signal.
#include <qsignaltransition.h>
Public Functions
QSignalTransition (QState *sourceState=0)
Constructs a new signal transition with the given sourceState.
QSignalTransition (QObject *sender, const char *signal, QState *sourceState=0)
Constructs a new signal transition associated with the given signal of the given sender, and with the given sourceState.
QObject * senderObject () const
void setSenderObject (QObject *sender)
Sets the sender object associated with this signal transition.
void setSignal (const QByteArray &signal)
Sets the signal associated with this signal transition.
QByteArray signal () const
~QSignalTransition ()
Destroys this signal transition.
Public Functions inherited from QAbstractTransition
void addAnimation (QAbstractAnimation *animation)
Adds the given animation to this transition.
QList< QAbstractAnimation * > animations () const
Returns the list of animations associated with this transition, or an empty list if it has no animations.
QStateMachine * machine () const
Returns the state machine that this transition is part of, or 0 if the transition is not part of a state machine.
QAbstractTransition (QState *sourceState=0)
Constructs a new QAbstractTransition object with the given sourceState.
void removeAnimation (QAbstractAnimation *animation)
Removes the given animation from this transition.
void setTargetState (QAbstractState *target)
Sets the target state of this transition.
void setTargetStates (const QList< QAbstractState *> &targets)
Sets the target states of this transition to be the given targets.
QState * sourceState () const
QAbstractState * targetState () const
QList< QAbstractState * > targetStates () const
virtual ~QAbstractTransition ()
Destroys this transition.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *e)
Reimplemented Function
bool eventTest (QEvent *event)
The default implementation returns true if the event is a QStateMachine::SignalEvent object and the event's sender and signal index match this transition, and returns false otherwise.
void onTransition (QEvent *event)
Reimplemented Function
Protected Functions inherited from QAbstractTransition
QAbstractTransition (QAbstractTransitionPrivate &dd, QState *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
QObject * senderObject
the sender object that this signal transition is associated with
QByteArray signal
the signal that this signal transition is associated with
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractTransition
void triggered ()
This signal is emitted when the transition has been triggered (after onTransition() has been called).
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSignalTransition class provides a transition based on a Qt signal.
Since
4.6
Typically you would use the overload of QState::addTransition() that takes a sender and signal as arguments, rather than creating QSignalTransition objects directly. QSignalTransition is part of The State Machine Framework.
You can subclass QSignalTransition and reimplement eventTest() to make a signal transition conditional; the event object passed to eventTest() will be a QStateMachine::SignalEvent object. Example:
class CheckedTransition : public QSignalTransition
{
public:
    CheckedTransition(QCheckBox *check)
        : QSignalTransition(check, SIGNAL(stateChanged(int))) {}
protected:
    bool eventTest(QEvent *e) {
        if (!QSignalTransition::eventTest(e))
            return false;
        QStateMachine::SignalEvent *se = static_cast<QStateMachine::SignalEvent*>(e);
        return (se->arguments().at(0).toInt() == Qt::Checked);
    }
};
...
QCheckBox *check = new QCheckBox();
check->setTristate(true);
QState *s1 = new QState();
QState *s2 = new QState();
CheckedTransition *t1 = new CheckedTransition(check);
t1->setTargetState(s2);
s1->addTransition(t1);
Definition at line 56 of file qsignaltransition.h.
Constructors and Destructors
QSignalTransition() [1/2]
QSignalTransition::QSignalTransition (QState * sourceState = 0)
Constructs a new signal transition with the given sourceState.
Definition at line 151 of file qsignaltransition.cpp.
     : QAbstractTransition(*new QSignalTransitionPrivate, sourceState)
 {
 }
QSignalTransition() [2/2]
QSignalTransition::QSignalTransition (QObject * sender, const char * signal, QState * sourceState = 0)
Constructs a new signal transition associated with the given signal of the given sender, and with the given sourceState.
Definition at line 160 of file qsignaltransition.cpp.
     : QAbstractTransition(*new QSignalTransitionPrivate, sourceState)
 {
     Q_D(QSignalTransition);
     d->sender = sender;
     d->signal = signal;
 }
~QSignalTransition()
QSignalTransition::~QSignalTransition ()
Destroys this signal transition.
Definition at line 172 of file qsignaltransition.cpp.
 {
 }
Functions
event()
bool QSignalTransition::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractTransition.
Definition at line 254 of file qsignaltransition.cpp.
Referenced by eventTest().
 {
     return QAbstractTransition::event(e);
 }
eventTest()
bool QSignalTransition::eventTest (QEvent * event) protected virtual
The default implementation returns true if the event is a QStateMachine::SignalEvent object and the event's sender and signal index match this transition, and returns false otherwise.
Reimplemented Function
Implements QAbstractTransition.
Definition at line 230 of file qsignaltransition.cpp.
 {
     Q_D(const QSignalTransition);
     if (event->type() == QEvent::StateMachineSignal) {
         if (d->signalIndex == -1)
             return false;
         QStateMachine::SignalEvent *se = static_cast<QStateMachine::SignalEvent*>(event);
         return (se->sender() == d->sender)
             && (se->signalIndex() == d->signalIndex);
     }
     return false;
 }
onTransition()
void QSignalTransition::onTransition (QEvent * event) protected virtual
Reimplemented Function
Implements QAbstractTransition.
Definition at line 246 of file qsignaltransition.cpp.
 {
     Q_UNUSED(event);
 }
senderObject()
QObject* QSignalTransition::senderObject () const
Referenced by ~QSignalTransition().
setSenderObject()
void QSignalTransition::setSenderObject (QObject * sender)
Sets the sender object associated with this signal transition.
Definition at line 188 of file qsignaltransition.cpp.
 {
     Q_D(QSignalTransition);
     if (sender == d->sender)
         return;
     d->unregister();
     d->sender = sender;
     d->maybeRegister();
 }
setSignal()
void QSignalTransition::setSignal (const QByteArray & signal)
Sets the signal associated with this signal transition.
Definition at line 210 of file qsignaltransition.cpp.
 {
     Q_D(QSignalTransition);
     if (signal == d->signal)
         return;
     d->unregister();
     d->signal = signal;
     d->maybeRegister();
 }
signal()
QByteArray QSignalTransition::signal () const
Referenced by QSignalTransition(), setSenderObject(), and setSignal().
Properties
senderObject
QObject * QSignalTransition::senderObject private
the sender object that this signal transition is associated with
Returns the sender object associated with this signal transition.
Definition at line 59 of file qsignaltransition.h.
signal
QByteArray QSignalTransition::signal private
the signal that this signal transition is associated with
Returns the signal associated with this signal transition.
Definition at line 60 of file qsignaltransition.h.
The documentation for this class was generated from the following files:
/src/corelib/statemachine/qsignaltransition.h
/src/corelib/statemachine/qsignaltransition.cpp