Qt 4.8: QStatePrivate Class Reference
QStatePrivate Class Reference
#include <qstate_p.h>
Public Functions
QList< QAbstractState * > childStates () const
void emitFinished ()
void emitPropertiesAssigned ()
QList< QHistoryState * > historyStates () const
QStatePrivate ()
QList< QAbstractTransition * > transitions () const
~QStatePrivate ()
Public Functions inherited from QAbstractStatePrivate
void callOnEntry (QEvent *e)
void callOnExit (QEvent *e)
void emitEntered ()
void emitExited ()
QStateMachine * machine () const
QAbstractStatePrivate (StateType type)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QStatePrivate * get (QState *q)
static const QStatePrivate * get (const QState *q)
Static Public Functions inherited from QAbstractStatePrivate
static QAbstractStatePrivate * get (QAbstractState *q)
static const QAbstractStatePrivate * get (const QAbstractState *q)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QState::ChildMode childMode
QList< QAbstractState * > childStatesList
bool childStatesListNeedsRefresh
QAbstractState * errorState
QAbstractState * initialState
QList< QPropertyAssignment > propertyAssignments
QList< QAbstractTransition * > transitionsList
bool transitionsListNeedsRefresh
Public Variables inherited from QAbstractStatePrivate
uint isMachine:1
QState * parentState
uint stateType:31
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QAbstractStatePrivate
enum StateType { AbstractState, StandardState, FinalState, HistoryState }
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 82 of file qstate_p.h.
Constructors and Destructors
QStatePrivate()
QStatePrivate::QStatePrivate ()
Definition at line 142 of file qstate.cpp.
     : QAbstractStatePrivate(StandardState),
       errorState(0), initialState(0), childMode(QState::ExclusiveStates),
       childStatesListNeedsRefresh(true), transitionsListNeedsRefresh(true)
 {
 }
~QStatePrivate()
QStatePrivate::~QStatePrivate ()
Definition at line 149 of file qstate.cpp.
 {
 }
Functions
childStates()
QList< QAbstractState * > QStatePrivate::childStates () const
Definition at line 199 of file qstate.cpp.
Referenced by QStateMachinePrivate::addStatesToEnter(), QStateMachinePrivate::enterStates(), indexOfDescendant(), QStateMachinePrivate::isAtomic(), QStateMachinePrivate::isCompound(), and QStateMachinePrivate::isInFinalState().
 {
     if (childStatesListNeedsRefresh) {
         childStatesList.clear();
         QList<QObject*>::const_iterator it;
         for (it = children.constBegin(); it != children.constEnd(); ++it) {
             QAbstractState *s = qobject_cast<QAbstractState*>(*it);
             if (!s || qobject_cast<QHistoryState*>(s))
                 continue;
             childStatesList.append(s);
         }
         childStatesListNeedsRefresh = false;
     }
     return childStatesList;
 }
emitFinished()
void QStatePrivate::emitFinished ()
Definition at line 153 of file qstate.cpp.
Referenced by QStateMachinePrivate::enterStates().
 {
     Q_Q(QState);
     emit q->finished();
 }
emitPropertiesAssigned()
void QStatePrivate::emitPropertiesAssigned ()
Definition at line 159 of file qstate.cpp.
Referenced by QStateMachinePrivate::_q_animationFinished(), and QStateMachinePrivate::applyProperties().
 {
     Q_Q(QState);
     emit q->propertiesAssigned();
 }
get() [1/2]
static QStatePrivate* QStatePrivate::get (QState * q) inline static
Definition at line 89 of file qstate_p.h.
Referenced by QStateMachinePrivate::_q_animationFinished(), QStateMachinePrivate::_q_start(), QStateMachinePrivate::addStatesToEnter(), QStateMachinePrivate::applyProperties(), QStateMachinePrivate::enterStates(), QStateMachinePrivate::exitStates(), indexOfDescendant(), QStateMachinePrivate::isAtomic(), QStateMachinePrivate::isCompound(), QStateMachinePrivate::isInFinalState(), QStateMachinePrivate::isParallel(), QStateMachinePrivate::registerTransitions(), and QStateMachinePrivate::selectTransitions().
 { return q ? q->d_func() : 0; }
get() [2/2]
static const QStatePrivate* QStatePrivate::get (const QState * q) inline static
Definition at line 90 of file qstate_p.h.
 { return q? q->d_func() : 0; }
historyStates()
QList< QHistoryState * > QStatePrivate::historyStates () const
Definition at line 215 of file qstate.cpp.
Referenced by QStateMachinePrivate::clearHistory(), and QStateMachinePrivate::exitStates().
 {
     QList<QHistoryState*> result;
     QList<QObject*>::const_iterator it;
     for (it = children.constBegin(); it != children.constEnd(); ++it) {
         QHistoryState *h = qobject_cast<QHistoryState*>(*it);
         if (h)
             result.append(h);
     }
     return result;
 }
transitions()
QList< QAbstractTransition * > QStatePrivate::transitions () const
Definition at line 227 of file qstate.cpp.
Referenced by QStateMachinePrivate::_q_start(), QStateMachinePrivate::registerTransitions(), QStateMachinePrivate::selectTransitions(), and QStateMachinePrivate::unregisterAllTransitions().
 {
     if (transitionsListNeedsRefresh) {
         transitionsList.clear();
         QList<QObject*>::const_iterator it;
         for (it = children.constBegin(); it != children.constEnd(); ++it) {
             QAbstractTransition *t = qobject_cast<QAbstractTransition*>(*it);
             if (t)
                 transitionsList.append(t);
         }
         transitionsListNeedsRefresh = false;
     }
     return transitionsList;
 }
Properties
childMode
QState::ChildMode QStatePrivate::childMode
Definition at line 101 of file qstate_p.h.
Referenced by QStateMachinePrivate::isParallel().
childStatesList
QList<QAbstractState*> QStatePrivate::childStatesList mutable
Definition at line 103 of file qstate_p.h.
childStatesListNeedsRefresh
bool QStatePrivate::childStatesListNeedsRefresh mutable
Definition at line 102 of file qstate_p.h.
errorState
QAbstractState* QStatePrivate::errorState
Definition at line 99 of file qstate_p.h.
Referenced by QStateMachinePrivate::findErrorState().
initialState
QAbstractState* QStatePrivate::initialState
Definition at line 100 of file qstate_p.h.
propertyAssignments
QList<QPropertyAssignment> QStatePrivate::propertyAssignments
Definition at line 107 of file qstate_p.h.
Referenced by QStateMachinePrivate::applyProperties().
transitionsList
QList<QAbstractTransition*> QStatePrivate::transitionsList mutable
Definition at line 105 of file qstate_p.h.
transitionsListNeedsRefresh
bool QStatePrivate::transitionsListNeedsRefresh mutable
Definition at line 104 of file qstate_p.h.
The documentation for this class was generated from the following files:
/src/corelib/statemachine/qstate_p.h
/src/corelib/statemachine/qstate.cpp