Qt 4.8: QToolTip Class Reference
QToolTip Class Reference
The QToolTip class provides tool tips (balloon help) for any widget.
#include <qtooltip.h>
Static Public Functions
static QFont font ()
Returns the font used to render tooltips.
static void hideText ()
Hides the tool tip.
static bool isVisible ()
Returns true if this tooltip is currently shown.
static QPalette palette ()
Returns the palette used to render tooltips.
static void setFont (const QFont &)
Sets the font used to render tooltips.
static void setPalette (const QPalette &)
Sets the palette used to render tooltips.
static void showText (const QPoint &pos, const QString &text, QWidget *w=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This is analogous to calling QToolTip::showText(pos, text, w, QRect())
static void showText (const QPoint &pos, const QString &text, QWidget *w, const QRect &rect)
Shows text as a tool tip, with the global position pos as the point of interest.
static QString text ()
Returns the tooltip text, if a tooltip is visible, or an empty string if a tooltip is not visible.
Private Functions
QToolTip ()
Detailed Description
The QToolTip class provides tool tips (balloon help) for any widget.
The tip is a short piece of text reminding the user of the widget's function. It is drawn immediately below the given position in a distinctive black-on-yellow color combination. The tip can be any rich text formatted string.
Rich text displayed in a tool tip is implicitly word-wrapped unless specified differently with
.
The simplest and most common way to set a widget's tool tip is by calling its QWidget::setToolTip() function.
It is also possible to show different tool tips for different regions of a widget, by using a QHelpEvent of type QEvent::ToolTip. Intercept the help event in your widget's QWidget::event() function and call QToolTip::showText() with the text you want to display. The Tooltips example illustrates this technique.
If you are calling QToolTip::hideText(), or QToolTip::showText() with an empty string, as a result of a QEvent::ToolTip-event you should also call QEvent::ignore() on the event, to signal that you don't want to start any tooltip specific modes.
Note that, if you want to show tooltips in an item view, the model/view architecture provides functionality to set an item's tool tip; e.g., the QTableWidgetItem::setToolTip() function. However, if you want to provide custom tool tips in an item view, you must intercept the help event in the QAbstractItemView::viewportEvent() function and handle it yourself.
The default tool tip color and font can be customized with setPalette() and setFont(). When a tooltip is currently on display, isVisible() returns true and text() the currently visible text.
Note
Tool tips use the inactive color group of QPalette, because tool tips are not active windows.
See also
QWidget::toolTip, QAction::toolTip, {Tool Tips Example}
Definition at line 55 of file qtooltip.h.
Constructors and Destructors
QToolTip()
QToolTip::QToolTip () private
Functions
font()
QFont QToolTip::font () static
Returns the font used to render tooltips.
Since
4.2
Definition at line 570 of file qtooltip.cpp.
 {
     return QApplication::font("QTipLabel");
 }
hideText()
void QToolTip::hideText () inline static
Hides the tool tip.
Since
4.2
This is the same as calling showText() with an empty string.
See also
showText()
Definition at line 61 of file qtooltip.h.
Referenced by QMDIControl::event(), and QGraphicsScenePrivate::leaveScene().
 { showText(QPoint(), QString()); }
isVisible()
bool QToolTip::isVisible () static
Returns true if this tooltip is currently shown.
Since
4.4
See also
showText()
Definition at line 527 of file qtooltip.cpp.
 {
     return (QTipLabel::instance != 0 && QTipLabel::instance->isVisible());
 }
palette()
QPalette QToolTip::palette () static
Returns the palette used to render tooltips.
Note
Tool tips use the inactive color group of QPalette, because tool tips are not active windows.
Definition at line 557 of file qtooltip.cpp.
Referenced by QRenderRule::QRenderRule(), and QTipLabel::QTipLabel().
 {
     return *tooltip_palette();
 }
setFont()
void QToolTip::setFont (const QFont & font) static
Sets the font used to render tooltips.
Since
4.2
Definition at line 601 of file qtooltip.cpp.
 {
     QApplication::setFont(font, "QTipLabel");
 }
setPalette()
void QToolTip::setPalette (const QPalette & palette) static
Sets the palette used to render tooltips.
Since
4.2
Note
Tool tips use the inactive color group of QPalette, because tool tips are not active windows.
Definition at line 586 of file qtooltip.cpp.
Referenced by qt_set_windows_color_resources().
 {
     *tooltip_palette() = palette;
     if (QTipLabel::instance)
         QTipLabel::instance->setPalette(palette);
 }
showText() [1/2]
void QToolTip::showText (const QPoint & pos, const QString & text, QWidget * w = 0) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This is analogous to calling QToolTip::showText(pos, text, w, QRect())
Definition at line 497 of file qtooltip.cpp.
Referenced by QMDIControl::event(), QTabBar::event(), QWidget::event(), QScriptToolTipJob::handleResponse(), QAbstractItemDelegate::helpEvent(), QGraphicsScene::helpEvent(), QTextControlPrivate::showToolTip(), showToolTip(), and QHeaderView::viewportEvent().
 {
     QToolTip::showText(pos, text, w, QRect());
 }
showText() [2/2]
void QToolTip::showText (const QPoint & pos, const QString & text, QWidget * w, const QRect & rect) static
Shows text as a tool tip, with the global position pos as the point of interest.
The tool tip will be shown with a platform specific offset from this point of interest.
If you specify a non-empty rect the tip will be hidden as soon as you move your cursor out of this area.
The rect is in the coordinates of the widget you specify with w. If the rect is not empty you must specify a widget. Otherwise this argument can be 0 but it is used to determine the appropriate screen on multi-head systems.
If text is empty the tool tip is hidden. If the text is the same as the currently shown tooltip, the tip will not move. You can force moving by first hiding the tip with an empty text, and then showing the new tip at the new position.
Definition at line 443 of file qtooltip.cpp.
 {
     if (QTipLabel::instance && QTipLabel::instance->isVisible()){ // a tip does already exist
         if (text.isEmpty()){ // empty text means hide current tip
             QTipLabel::instance->hideTip();
             return;
         }
         else if (!QTipLabel::instance->fadingOut){
             // If the tip has changed, reuse the one
             // that is showing (removes flickering)
             QPoint localPos = pos;
             if (w)
                 localPos = w->mapFromGlobal(pos);
             if (QTipLabel::instance->tipChanged(localPos, text, w)){
                 QTipLabel::instance->reuseTip(text);
                 QTipLabel::instance->setTipRect(w, rect);
                 QTipLabel::instance->placeTip(pos, w);
             }
             return;
         }
     }
     if (!text.isEmpty()){ // no tip can be reused, create new tip:
 #ifndef Q_WS_WIN
         new QTipLabel(text, w); // sets QTipLabel::instance to itself
 #else
         // On windows, we can't use the widget as parent otherwise the window will be
         // raised when the tooltip will be shown
         new QTipLabel(text, QApplication::desktop()->screen(QTipLabel::getTipScreen(pos, w)));
 #endif
         QTipLabel::instance->setTipRect(w, rect);
         QTipLabel::instance->placeTip(pos, w);
         QTipLabel::instance->setObjectName(QLatin1String("qtooltip_label"));
 #if !defined(QT_NO_EFFECTS) && !defined(Q_WS_MAC)
         if (QApplication::isEffectEnabled(Qt::UI_FadeTooltip))
             qFadeEffect(QTipLabel::instance);
         else if (QApplication::isEffectEnabled(Qt::UI_AnimateTooltip))
             qScrollEffect(QTipLabel::instance);
         else
             QTipLabel::instance->show();
 #else
         QTipLabel::instance->show();
 #endif
     }
 }
text()
QString QToolTip::text () static
Returns the tooltip text, if a tooltip is visible, or an empty string if a tooltip is not visible.
Since
4.4
Definition at line 541 of file qtooltip.cpp.
 {
     if (QTipLabel::instance)
         return QTipLabel::instance->text();
     return QString();
 }
The documentation for this class was generated from the following files:
/src/gui/kernel/qtooltip.h
/src/gui/kernel/qtooltip.cpp