Qt 4.8: QIcon Class Reference
QIcon Class Reference
The QIcon class provides scalable icons in different modes and states.
#include <qicon.h>
Public Types
typedef QIconPrivate * DataPtr
enum Mode { Normal, Disabled, Active, Selected }
This enum type describes the mode for which a pixmap is intended to be used.
enum State { On, Off }
This enum describes the state for which a pixmap is intended to be used.
Public Functions
QSize actualSize (const QSize &size, Mode mode=Normal, State state=Off) const
Returns the actual size of the icon for the requested size, mode, and state.
void addFile (const QString &fileName, const QSize &size=QSize(), Mode mode=Normal, State state=Off)
Adds an image from the file with the given fileName to the icon, as a specialization for size, mode and state.
void addPixmap (const QPixmap &pixmap, Mode mode=Normal, State state=Off)
Adds pixmap to the icon, as a specialization for mode and state.
QList< QSize > availableSizes (Mode mode=Normal, State state=Off) const
Returns a list of available icon sizes for the specified mode and state.
qint64 cacheKey () const
Returns a number that identifies the contents of this QIcon object.
DataPtr & data_ptr ()
void detach ()
bool isDetached () const
bool isNull () const
Returns true if the icon is empty; otherwise returns false.
QString name () const
Returns the name used to create the icon, if available.
operator QVariant () const
Returns the icon as a QVariant.
QIcon & operator= (const QIcon &other)
Assigns the other icon to this icon and returns a reference to this icon.
void paint (QPainter *painter, const QRect &rect, Qt::Alignment alignment=Qt::AlignCenter, Mode mode=Normal, State state=Off) const
Uses the painter to paint the icon with specified alignment, required mode, and state into the rectangle rect.
void paint (QPainter *painter, int x, int y, int w, int h, Qt::Alignment alignment=Qt::AlignCenter, Mode mode=Normal, State state=Off) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Paints the icon into the rectangle QRect(x, y, w, h).
QPixmap pixmap (const QSize &size, Mode mode=Normal, State state=Off) const
Returns a pixmap with the requested size, mode, and state, generating one if necessary.
QPixmap pixmap (int w, int h, Mode mode=Normal, State state=Off) const
Returns a pixmap of size QSize(w, h).
QPixmap pixmap (int extent, Mode mode=Normal, State state=Off) const
Returns a pixmap of size QSize(extent, extent).
QIcon ()
Constructs a null icon.
QIcon (const QPixmap &pixmap)
Constructs an icon from a pixmap.
QIcon (const QIcon &other)
Constructs a copy of other.
QIcon (const QString &fileName)
Constructs an icon from the file with the given fileName.
QIcon (QIconEngine *engine)
Creates an icon with a specific icon engine.
QIcon (QIconEngineV2 *engine)
Creates an icon with a specific icon engine.
int serialNumber () const
Returns a number that identifies the contents of this QIcon object.
void swap (QIcon &other)
Swaps icon other with this icon.
~QIcon ()
Destroys the icon.
Static Public Functions
static QIcon fromTheme (const QString &name, const QIcon &fallback=QIcon())
Returns the QIcon corresponding to name in the current icon theme.
static bool hasThemeIcon (const QString &name)
Returns true if there is an icon available for name in the current icon theme, otherwise returns false.
static void setThemeName (const QString &path)
Sets the current icon theme to name.
static void setThemeSearchPaths (const QStringList &searchpath)
Sets the search paths for icon themes to paths.
static QString themeName ()
Returns the name of the current icon theme.
static QStringList themeSearchPaths ()
Returns the search paths for icon themes.
Properties
QIconPrivate * d
Friends
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QIcon &)
Writes the given icon to the given stream as a PNG image.
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QIcon &)
Reads an image, or a set of images, from the given stream into the given icon.
Detailed Description
The QIcon class provides scalable icons in different modes and states.
A QIcon can generate smaller, larger, active, and disabled pixmaps from the set of pixmaps it is given. Such pixmaps are used by Qt widgets to show an icon representing a particular action.
The simplest use of QIcon is to create one from a QPixmap file or resource, and then use it, allowing Qt to work out all the required icon styles and sizes. For example:
QToolButton *button = new QToolButton;
button->setIcon(QIcon("open.xpm"));
To undo a QIcon, simply set a null icon in its place:
button->setIcon(QIcon());
Use the QImageReader::supportedImageFormats() and QImageWriter::supportedImageFormats() functions to retrieve a complete list of the supported file formats.
When you retrieve a pixmap using pixmap(QSize, Mode, State), and no pixmap for this given size, mode and state has been added with addFile() or addPixmap(), then QIcon will generate one on the fly. This pixmap generation happens in a QIconEngineV2. The default engine scales pixmaps down if required, but never up, and it uses the current style to calculate a disabled appearance. By using custom icon engines, you can customize every aspect of generated icons. With QIconEnginePluginV2 it is possible to register different icon engines for different file suffixes, making it possible for third parties to provide additional icon engines to those included with Qt.
Note
Since Qt 4.2, an icon engine that supports SVG is included.
Making Classes that Use QIcon
If you write your own widgets that have an option to set a small pixmap, consider allowing a QIcon to be set for that pixmap. The Qt class QToolButton is an example of such a widget.
Provide a method to set a QIcon, and when you draw the icon, choose whichever pixmap is appropriate for the current state of your widget. For example:
void MyWidget::drawIcon(QPainter *painter, QPoint pos)
{
    QPixmap pixmap = icon.pixmap(QSize(22, 22),
                                   isEnabled() ? QIcon::Normal
                                               : QIcon::Disabled,
                                   isChecked() ? QIcon::On
                                               : QIcon::Off);
    painter->drawPixmap(pos, pixmap);
}
You might also make use of the Active mode, perhaps making your widget Active when the mouse is over the widget (see QWidget::enterEvent()) , while the mouse is pressed pending the release that will activate the function, or when it is the currently selected item. If the widget can be toggled, the "On" mode might be used to draw a different icon.
QIcon
See also
{fowler}{GUI Design Handbook: Iconic Label}, {Icons Example}
Definition at line 60 of file qicon.h.
Typedefs
DataPtr
QIcon::DataPtr
Warning
This function is not part of the public interface.
Definition at line 142 of file qicon.h.
Enumerations
Mode
enum QIcon::Mode
This enum type describes the mode for which a pixmap is intended to be used.
The currently defined modes are:
Normal Display the pixmap when the user is not interacting with the icon, but the functionality represented by the icon is available.
Disabled Display the pixmap when the functionality represented by the icon is not available.
Active Display the pixmap when the functionality represented by the icon is available and the user is interacting with the icon, for example, moving the mouse over it or clicking it.
Selected Display the pixmap when the item represented by the icon is selected.
Enumerator
Normal
Disabled
Active
Selected
Definition at line 63 of file qicon.h.
 { Normal, Disabled, Active, Selected };
State
enum QIcon::State
This enum describes the state for which a pixmap is intended to be used.
The state can be:
Off Display the pixmap when the widget is in an "off" state
On Display the pixmap when the widget is in an "on" state
Enumerator
On
Off
Definition at line 64 of file qicon.h.
 { On, Off };
Constructors and Destructors
QIcon() [1/6]
QIcon::QIcon ()
Constructs a null icon.
Definition at line 528 of file qicon.cpp.
Referenced by fromTheme(), and operator>>().
     : d(0)
 {
 }
QIcon() [2/6]
QIcon::QIcon (const QPixmap & pixmap)
Constructs an icon from a pixmap.
Definition at line 536 of file qicon.cpp.
     :d(0)
 {
     addPixmap(pixmap);
 }
QIcon() [3/6]
QIcon::QIcon (const QIcon & other)
Constructs a copy of other.
This is very fast.
Definition at line 545 of file qicon.cpp.
     :d(other.d)
 {
     if (d)
         d->ref.ref();
 }
QIcon() [4/6]
QIcon::QIcon (const QString & fileName) explicit
Constructs an icon from the file with the given fileName.
The file will be loaded on demand.
If fileName contains a relative path (e.g. the filename only) the relevant file must be found relative to the runtime working directory.
The file name can be either refer to an actual file on disk or to one of the application's embedded resources. See the Resource System overview for details on how to embed images and other resource files in the application's executable.
Use the QImageReader::supportedImageFormats() and QImageWriter::supportedImageFormats() functions to retrieve a complete list of the supported file formats.
Definition at line 569 of file qicon.cpp.
     : d(0)
 {
     addFile(fileName);
 }
QIcon() [5/6]
QIcon::QIcon (QIconEngine * engine) explicit
Creates an icon with a specific icon engine.
The icon takes ownership of the engine.
Definition at line 580 of file qicon.cpp.
     :d(new QIconPrivate)
 {
     d->engine_version = 1;
     d->engine = engine;
     d->v1RefCount = new QAtomicInt(1);
 }
QIcon() [6/6]
QIcon::QIcon (QIconEngineV2 * engine) explicit
Creates an icon with a specific icon engine.
The icon takes ownership of the engine.
Definition at line 592 of file qicon.cpp.
     :d(new QIconPrivate)
 {
     d->engine_version = 2;
     d->engine = engine;
 }
~QIcon()
QIcon::~QIcon ()
Destroys the icon.
Definition at line 602 of file qicon.cpp.
 {
     if (d && !d->ref.deref())
         delete d;
 }
Functions
actualSize()
QSize QIcon::actualSize (const QSize & size, Mode mode = Normal, State state = Off) const
Returns the actual size of the icon for the requested size, mode, and state.
The result might be smaller than requested, but never larger.
See also
pixmap(), paint()
Definition at line 730 of file qicon.cpp.
Referenced by QMessageBox::about(), QSystemTrayIconSys::createIcon(), QWindowsVistaStyle::drawControl(), QWindowsXPStyle::drawControl(), QCommandLinkButton::heightForWidth(), QWorkspaceTitleBar::initStyleOption(), QCommandLinkButton::minimumSizeHint(), QFontFamilyDelegate::paint(), QCommandLinkButton::paintEvent(), qt_aqua_get_known_size(), qt_createIcon(), QItemDelegate::rect(), QUrlModel::setUrl(), QApplication::setWindowIcon(), QDockWidgetTitleButton::sizeHint(), QCommonStyle::subElementRect(), QMacStyle::subElementRect(), and QCommonStylePrivate::tabLayout().
 {
     if (!d)
         return QSize();
     return d->engine->actualSize(size, mode, state);
 }
addFile()
void QIcon::addFile (const QString & fileName, const QSize & size = QSize(), Mode mode = Normal, State state = Off)
Adds an image from the file with the given fileName to the icon, as a specialization for size, mode and state.
The file will be loaded on demand. Note: custom icon engines are free to ignore additionally added pixmaps.
If fileName contains a relative path (e.g. the filename only) the relevant file must be found relative to the runtime working directory.
The file name can be either refer to an actual file on disk or to one of the application's embedded resources. See the Resource System overview for details on how to embed images and other resource files in the application's executable.
Use the QImageReader::supportedImageFormats() and QImageWriter::supportedImageFormats() functions to retrieve a complete list of the supported file formats.
Note: When you add a non-empty filename to a QIcon, the icon becomes non-null, even if the file doesn't exist or points to a corrupt file.
See also
addPixmap()
Definition at line 851 of file qicon.cpp.
Referenced by operator>>(), QIcon(), qt_setupActionIcon(), and QCommonStyle::standardIconImplementation().
 {
     if (fileName.isEmpty())
         return;
     if (!d) {
 #if !defined (QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
         QFileInfo info(fileName);
         QString suffix = info.suffix();
         if (!suffix.isEmpty()) {
             // first try version 2 engines..
             if (QIconEngineFactoryInterfaceV2 *factory = qobject_cast<QIconEngineFactoryInterfaceV2*>(loaderV2()->instance(suffix))) {
                 if (QIconEngine *engine = factory->create(fileName)) {
                     d = new QIconPrivate;
                     d->engine = engine;
                 }
             }
             // ..then fall back and try to load version 1 engines
             if (!d) {
                 if (QIconEngineFactoryInterface *factory = qobject_cast<QIconEngineFactoryInterface*>(loader()->instance(suffix))) {
                     if (QIconEngine *engine = factory->create(fileName)) {
                         d = new QIconPrivate;
                         d->engine = engine;
                         d->engine_version = 1;
                         d->v1RefCount = new QAtomicInt(1);
                     }
                 }
             }
         }
 #endif
         // ...then fall back to the default engine
         if (!d) {
             d = new QIconPrivate;
             d->engine = new QPixmapIconEngine;
         }
     } else {
         detach();
     }
     d->engine->addFile(fileName, size, mode, state);
 }
addPixmap()
void QIcon::addPixmap (const QPixmap & pixmap, Mode mode = Normal, State state = Off)
Adds pixmap to the icon, as a specialization for mode and state.
Custom icon engines are free to ignore additionally added pixmaps.
See also
addFile()
Definition at line 814 of file qicon.cpp.
Referenced by QScriptDebugger::continueAction(), QScriptDebugger::findInScriptAction(), QFileIconProviderPrivate::getWinIcon(), QCss::Declaration::iconValue(), QScriptDebugger::interruptAction(), operator>>(), QIcon(), QScriptBreakpointsWidget::QScriptBreakpointsWidget(), qt_mac_constructQIconFromIconRef(), QScriptDebugger::runToCursorAction(), QScriptDebugger::runToNewScriptAction(), QUrlModel::setUrl(), QWindowsXPStyle::standardIconImplementation(), QWindowsStyle::standardIconImplementation(), QCommonStyle::standardIconImplementation(), QScriptDebugger::stepIntoAction(), QScriptDebugger::stepOutAction(), and QScriptDebugger::stepOverAction().
 {
     if (pixmap.isNull())
         return;
     if (!d) {
         d = new QIconPrivate;
         d->engine = new QPixmapIconEngine;
     } else {
         detach();
     }
     d->engine->addPixmap(pixmap, mode, state);
 }
availableSizes()
QList< QSize > QIcon::availableSizes (Mode mode = Normal, State state = Off) const
Returns a list of available icon sizes for the specified mode and state.
Since
4.5
Definition at line 900 of file qicon.cpp.
Referenced by fromTheme(), qstring_to_xtp(), and QCommonStyle::standardIconImplementation().
 {
     if (!d || !d->engine || d->engine_version < 2)
         return QList<QSize>();
     QIconEngineV2 *engine = static_cast<QIconEngineV2*>(d->engine);
     return engine->availableSizes(mode, state);
 }
cacheKey()
qint64 QIcon::cacheKey () const
Returns a number that identifies the contents of this QIcon object.
Distinct QIcon objects can have the same key if they refer to the same contents.
Since
4.3
The cacheKey() will change when the icon is altered via addPixmap() or addFile().
Cache keys are mostly useful in conjunction with caching.
See also
QPixmap::cacheKey()
Definition at line 679 of file qicon.cpp.
Referenced by QWindowsVistaStyle::drawControl(), QWindowsXPStyle::drawControl(), QUrlModel::setUrl(), QCommonStyle::subElementRect(), and QMacStyle::subElementRect().
 {
     if (!d)
         return 0;
     return (((qint64) d->serialNum) << 32) | ((qint64) (d->detach_no));
 }
data_ptr()
DataPtr & QIcon::data_ptr () inline
Warning
This function is not part of the public interface.
Definition at line 143 of file qicon.h.
 { return d; }
detach()
void QIcon::detach ()
Warning
This function is not part of the public interface.
Definition at line 783 of file qicon.cpp.
Referenced by addFile(), and addPixmap().
 {
     if (d) {
         if (d->ref != 1) {
             QIconPrivate *x = new QIconPrivate;
             if (d->engine_version > 1) {
                 QIconEngineV2 *engine = static_cast<QIconEngineV2 *>(d->engine);
                 x->engine = engine->clone();
             } else {
                 x->engine = d->engine;
                 x->v1RefCount = d->v1RefCount;
                 x->v1RefCount->ref();
             }
             x->engine_version = d->engine_version;
             if (!d->ref.deref())
                 delete d;
             d = x;
         }
         ++d->detach_no;
     }
 }
fromTheme()
QIcon QIcon::fromTheme (const QString & name, const QIcon & fallback = QIcon()) static
Returns the QIcon corresponding to name in the current icon theme.
Since
4.6
If no such icon is found in the current theme fallback is returned instead.
The latest version of the freedesktop icon specification and naming specification can be obtained here:
http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
To fetch an icon from the current icon theme:
    QIcon undoicon = QIcon::fromTheme("edit-undo");
Or if you want to provide a guaranteed fallback for platforms that do not support theme icons, you can use the second argument:
    QIcon undoicon = QIcon::fromTheme("edit-undo", QIcon(":/undo.png"));
Note
By default, only X11 will support themed icons. In order to use themed icons on Mac and Windows, you will have to bundle a compliant theme in one of your themeSearchPaths() and set the appropriate themeName().
See also
themeName(), setThemeName(), themeSearchPaths()
Definition at line 1039 of file qicon.cpp.
Referenced by QGtkStylePrivate::getFilesystemIcon(), hasThemeIcon(), QCommonStyle::standardIconImplementation(), and QCommonStyle::standardPixmap().
 {
     QIcon icon;
     if (qtIconCache()->contains(name)) {
         icon = *qtIconCache()->object(name);
     } else {
         QIcon *cachedIcon  = new QIcon(new QIconLoaderEngine(name));
         qtIconCache()->insert(name, cachedIcon);
         icon = *cachedIcon;
     }
     // Note the qapp check is to allow lazy loading of static icons
     // Supporting fallbacks will not work for this case.
     if (qApp && icon.availableSizes().isEmpty())
         return fallback;
     return icon;
 }
hasThemeIcon()
bool QIcon::hasThemeIcon (const QString & name) static
Returns true if there is an icon available for name in the current icon theme, otherwise returns false.
Since
4.6
See also
themeSearchPaths(), fromTheme(), setThemeName()
Definition at line 1070 of file qicon.cpp.
 {
     QIcon icon = fromTheme(name);
     return !icon.isNull();
 }
isDetached()
bool QIcon::isDetached () const
Warning
This function is not part of the public interface.
Definition at line 776 of file qicon.cpp.
 {
     return !d || d->ref == 1;
 }
isNull()
bool QIcon::isNull () const
Returns true if the icon is empty; otherwise returns false.
An icon is empty if it has neither a pixmap nor a filename.
Note: Even a non-null icon might not be able to create valid pixmaps, eg. if the file does not exist or cannot be read.
Definition at line 769 of file qicon.cpp.
Referenced by QMenuBarPrivate::calcActionRects(), QSystemTrayIconSys::createIcon(), QUndoModel::data(), QFileSystemModel::data(), QCommonStyle::drawControl(), QStyleSheetStyle::drawControl(), QWindowsVistaStyle::drawPrimitive(), QVistaHelper::drawTitleBar(), QDirModel::fileIcon(), QSystemTrayIconSys::findTrayGeometry(), QFileIconProviderPrivate::getIcon(), hasThemeIcon(), QFileIconProvider::icon(), QCss::Declaration::iconValue(), QComboBox::insertItem(), QCommonStylePrivate::isViewItemCached(), operator<<(), QHeaderView::paintSection(), QDecorationDefault::pixmapFor(), QMacStylePrivate::pushButtonSizeFromContents(), QBalloonTip::QBalloonTip(), qstring_to_xtp(), qt_aqua_get_known_size(), qt_createIcon(), QWorkspaceChild::QWorkspaceChild(), QHeaderView::sectionSizeFromContents(), QTabBar::setTabIcon(), QWidget::setWindowIcon(), QWidgetPrivate::setWindowIcon_sys(), QRadioButton::sizeHint(), QCheckBox::sizeHint(), QMessageBoxPrivate::standardIcon(), QWindowsStyle::standardIconImplementation(), QWindowsXPStyle::standardIconImplementation(), QCommonStyle::standardIconImplementation(), QCommonStyle::subElementRect(), QMacStyle::subElementRect(), QMenuPrivate::QMacMenuPrivate::syncAction(), QCommonStylePrivate::tabLayout(), QTabBar::tabSizeHint(), QVistaHelper::titleOffset(), QMenuPrivate::updateActionRects(), and QMdi::ControlLabel::updateWindowIcon().
 {
     return !d;
 }
name()
QString QIcon::name () const
Returns the name used to create the icon, if available.
Since
4.7
Depending on the way the icon was created, it may have an associated name. This is the case for icons created with fromTheme() or icons using a QIconEngine which supports the QIconEngineV2::IconNameHook.
See also
fromTheme(), QIconEngine
Definition at line 922 of file qicon.cpp.
 {
     if (!d || !d->engine || d->engine_version < 2)
         return QString();
     QIconEngineV2 *engine = static_cast<QIconEngineV2*>(d->engine);
     return engine->iconName();
 }
operator QVariant()
QIcon::operator QVariant () const
Returns the icon as a QVariant.
Definition at line 636 of file qicon.cpp.
 {
     return QVariant(QVariant::Icon, this);
 }
operator=()
QIcon & QIcon::operator= (const QIcon & other)
Assigns the other icon to this icon and returns a reference to this icon.
Definition at line 612 of file qicon.cpp.
 {
     if (other.d)
         other.d->ref.ref();
     if (d && !d->ref.deref())
         delete d;
     d = other.d;
     return *this;
 }
paint() [1/2]
void QIcon::paint (QPainter * painter, const QRect & rect, Qt::Alignment alignment = Qt::AlignCenter, Mode mode = Normal, State state = Off) const
Uses the painter to paint the icon with specified alignment, required mode, and state into the rectangle rect.
See also
actualSize(), pixmap()
Definition at line 744 of file qicon.cpp.
Referenced by QStyleSheetStyle::drawComplexControl(), QRenderRule::drawImage(), QScriptEdit::extraAreaPaintEvent(), QFontFamilyDelegate::paint(), and QSystemTrayIconSys::paintEvent().
 {
     if (!d || !painter)
         return;
     QRect alignedRect = QStyle::alignedRect(painter->layoutDirection(), alignment, d->engine->actualSize(rect.size(), mode, state), rect);
     d->engine->paint(painter, alignedRect, mode, state);
 }
paint() [2/2]
void QIcon::paint (QPainter * painter, int x, int y, int w, int h, Qt::Alignment alignment = Qt::AlignCenter, Mode mode = Normal, State state = Off) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Paints the icon into the rectangle QRect(x, y, w, h).
Definition at line 93 of file qicon.h.
         { paint(painter, QRect(x, y, w, h), alignment, mode, state); }
pixmap() [1/3]
QPixmap QIcon::pixmap (const QSize & size, Mode mode = Normal, State state = Off) const
Returns a pixmap with the requested size, mode, and state, generating one if necessary.
The pixmap might be smaller than requested, but never larger.
See also
actualSize(), paint()
Definition at line 693 of file qicon.cpp.
Referenced by QMessageBox::about(), QSystemTrayIconSys::createIcon(), QCommonStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QStyleSheetStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsXPStyle::drawControl(), QStyleSheetStyle::drawControl(), QVistaHelper::drawTitleBar(), QWorkspaceChild::eventFilter(), QSystemTrayIconSys::findTrayGeometry(), QFileIconProviderPrivate::getWinIcon(), QWorkspaceTitleBar::initStyleOption(), operator<<(), operator>>(), QCommandLinkButton::paintEvent(), ScalableEntry::pixmap(), QDecorationDefault::pixmapFor(), QBalloonTip::QBalloonTip(), qstring_to_xtp(), qt_createIcon(), QUrlModel::setUrl(), QWidgetPrivate::setWindowIcon_sys(), QWorkspacePrivate::showMaximizeControls(), QMessageBoxPrivate::standardIcon(), QCommonStyle::standardIconImplementation(), QCommonStyle::standardPixmap(), QWindowsXPStyle::standardPixmap(), QStyleSheetStyle::standardPixmap(), QMacStyle::standardPixmap(), QMenuPrivate::QMacMenuPrivate::syncAction(), and QMdi::ControlLabel::updateWindowIcon().
 {
     if (!d)
         return QPixmap();
     return d->engine->pixmap(size, mode, state);
 }
pixmap() [2/3]
QPixmap QIcon::pixmap (int w, int h, Mode mode = Normal, State state = Off) const inline
Returns a pixmap of size QSize(w, h).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The pixmap might be smaller than requested, but never larger.
Definition at line 83 of file qicon.h.
         { return pixmap(QSize(w, h), mode, state); }
pixmap() [3/3]
QPixmap QIcon::pixmap (int extent, Mode mode = Normal, State state = Off) const inline
Returns a pixmap of size QSize(extent, extent).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The pixmap might be smaller than requested, but never larger.
Definition at line 85 of file qicon.h.
         { return pixmap(QSize(extent, extent), mode, state); }
serialNumber()
int QIcon::serialNumber () const
Returns a number that identifies the contents of this QIcon object.
Distinct QIcon objects can have the same serial number if they refer to the same contents (but they don't have to). Also, the serial number of a QIcon object may change during its lifetime.
Use cacheKey() instead.
A null icon always has a serial number of 0.
Serial numbers are mostly useful in conjunction with caching.
See also
QPixmap::serialNumber()
Definition at line 661 of file qicon.cpp.
 {
     return d ? d->serialNum : 0;
 }
setThemeName()
void QIcon::setThemeName (const QString & name) static
Sets the current icon theme to name.
Since
4.6
The name should correspond to a directory name in the themeSearchPath() containing an index.theme file describing it's contents.
See also
themeSearchPaths(), themeName()
Definition at line 982 of file qicon.cpp.
 {
     QIconLoader::instance()->setThemeName(name);
 }
setThemeSearchPaths()
void QIcon::setThemeSearchPaths (const QStringList & paths) static
Sets the search paths for icon themes to paths.
Since
4.6
See also
themeSearchPaths(), fromTheme(), setThemeName()
Definition at line 939 of file qicon.cpp.
 {
     QIconLoader::instance()->setThemeSearchPath(paths);
 }
swap()
void QIcon::swap (QIcon & other) inline
Swaps icon other with this icon.
Since
4.8
This operation is very fast and never fails.
Definition at line 78 of file qicon.h.
 { qSwap(d, other.d); }
themeName()
QString QIcon::themeName () static
Returns the name of the current icon theme.
Since
4.6
On X11, the current icon theme depends on your desktop settings. On other platforms it is not set by default.
See also
setThemeName(), themeSearchPaths(), fromTheme(), hasThemeIcon()
Definition at line 1001 of file qicon.cpp.
Referenced by QCommonStyle::standardIconImplementation(), and QCommonStyle::standardPixmap().
 {
     return QIconLoader::instance()->themeName();
 }
themeSearchPaths()
QStringList QIcon::themeSearchPaths () static
Returns the search paths for icon themes.
Since
4.6
The default value will depend on the platform:
On X11, the search path will use the XDG_DATA_DIRS environment variable if available.
By default all platforms will have the resource directory : as a fallback. You can use "rcc -project" to generate a resource file from your icon theme.
See also
setThemeSearchPaths(), fromTheme(), setThemeName()
Definition at line 963 of file qicon.cpp.
Referenced by QIconTheme::QIconTheme().
 {
     return QIconLoader::instance()->themeSearchPaths();
 }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & stream, const QIcon & icon) friend
Writes the given icon to the given stream as a PNG image.
Since
4.2
If the icon contains more than one image, all images will be written to the stream. Note that writing the stream to a file will not produce a valid image file.
Definition at line 1096 of file qicon.cpp.
 {
     if (s.version() >= QDataStream::Qt_4_3) {
         if (icon.isNull()) {
             s << QString();
         } else {
             if (icon.d->engine_version > 1) {
                 QIconEngineV2 *engine = static_cast<QIconEngineV2 *>(icon.d->engine);
                 s << engine->key();
                 engine->write(s);
             } else {
                 // not really supported
                 qWarning("QIcon: Cannot stream QIconEngine. Use QIconEngineV2 instead.");
             }
         }
     } else if (s.version() == QDataStream::Qt_4_2) {
         if (icon.isNull()) {
             s << 0;
         } else {
             QPixmapIconEngine *engine = static_cast<QPixmapIconEngine *>(icon.d->engine);
             int num_entries = engine->pixmaps.size();
             s << num_entries;
             for (int i=0; i < num_entries; ++i) {
                 s << engine->pixmaps.at(i).pixmap;
                 s << engine->pixmaps.at(i).fileName;
                 s << engine->pixmaps.at(i).size;
                 s << (uint) engine->pixmaps.at(i).mode;
                 s << (uint) engine->pixmaps.at(i).state;
             }
         }
     } else {
         s << QPixmap(icon.pixmap(22,22));
     }
     return s;
 }
operator>>
QDataStream & operator>> (QDataStream & stream, QIcon & icon) friend
Reads an image, or a set of images, from the given stream into the given icon.
Since
4.2
Definition at line 1144 of file qicon.cpp.
 {
     if (s.version() >= QDataStream::Qt_4_3) {
         icon = QIcon();
         QString key;
         s >> key;
         if (key == QLatin1String("QPixmapIconEngine")) {
             icon.d = new QIconPrivate;
             QIconEngineV2 *engine = new QPixmapIconEngine;
             icon.d->engine = engine;
             engine->read(s);
         } else if (key == QLatin1String("QIconLoaderEngine")) {
             icon.d = new QIconPrivate;
             QIconEngineV2 *engine = new QIconLoaderEngine();
             icon.d->engine = engine;
             engine->read(s);
 #if !defined (QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
         } else if (QIconEngineFactoryInterfaceV2 *factory = qobject_cast<QIconEngineFactoryInterfaceV2*>(loaderV2()->instance(key))) {
             if (QIconEngineV2 *engine= factory->create()) {
                 icon.d = new QIconPrivate;
                 icon.d->engine = engine;
                 engine->read(s);
             }
 #endif
         }
     } else if (s.version() == QDataStream::Qt_4_2) {
         icon = QIcon();
         int num_entries;
         QPixmap pm;
         QString fileName;
         QSize sz;
         uint mode;
         uint state;
         s >> num_entries;
         for (int i=0; i < num_entries; ++i) {
             s >> pm;
             s >> fileName;
             s >> sz;
             s >> mode;
             s >> state;
             if (pm.isNull())
                 icon.addFile(fileName, sz, QIcon::Mode(mode), QIcon::State(state));
             else
                 icon.addPixmap(pm, QIcon::Mode(mode), QIcon::State(state));
         }
     } else {
         QPixmap pm;
         s >> pm;
         icon.addPixmap(pm);
     }
     return s;
 }
Properties
d
QIconPrivate* QIcon::d private
Definition at line 135 of file qicon.h.
Referenced by actualSize(), addFile(), addPixmap(), availableSizes(), cacheKey(), detach(), isDetached(), isNull(), name(), operator<<(), operator=(), operator>>(), paint(), pixmap(), QIcon(), serialNumber(), swap(), and ~QIcon().
The documentation for this class was generated from the following files:
/src/gui/image/qicon.h
/src/gui/image/qicon.cpp