Qt 4.8: QDomElement Class Reference
QDomElement Class Reference
The QDomElement class represents one element in the DOM tree.
#include <qdom.h>
Public Functions
QString attribute (const QString &name, const QString &defValue=QString()) const
Returns the attribute called name.
QDomAttr attributeNode (const QString &name)
Returns the QDomAttr object that corresponds to the attribute called name.
QDomAttr attributeNodeNS (const QString &nsURI, const QString &localName)
Returns the QDomAttr object that corresponds to the attribute with the local name localName and the namespace URI nsURI.
QString attributeNS (const QString nsURI, const QString &localName, const QString &defValue=QString()) const
Returns the attribute with the local name localName and the namespace URI nsURI.
QDomNamedNodeMap attributes () const
Returns a QDomNamedNodeMap containing all this element's attributes.
QDomNodeList elementsByTagName (const QString &tagname) const
Returns a QDomNodeList containing all descendants of this element named tagname encountered during a preorder traversal of the element subtree with this element as its root.
QDomNodeList elementsByTagNameNS (const QString &nsURI, const QString &localName) const
Returns a QDomNodeList containing all descendants of this element with local name localName and namespace URI nsURI encountered during a preorder traversal of the element subtree with this element as its root.
bool hasAttribute (const QString &name) const
Returns true if this element has an attribute called name; otherwise returns false.
bool hasAttributeNS (const QString &nsURI, const QString &localName) const
Returns true if this element has an attribute with the local name localName and the namespace URI nsURI; otherwise returns false.
QDomNode::NodeType nodeType () const
Returns ElementNode.
QDomElement & operator= (const QDomElement &)
Assigns x to this DOM element.
QDomElement ()
Constructs an empty element.
QDomElement (const QDomElement &x)
Constructs a copy of x.
void removeAttribute (const QString &name)
Removes the attribute called name name from this element.
QDomAttr removeAttributeNode (const QDomAttr &oldAttr)
Removes the attribute oldAttr from the element and returns it.
void removeAttributeNS (const QString &nsURI, const QString &localName)
Removes the attribute with the local name localName and the namespace URI nsURI from this element.
void setAttribute (const QString &name, const QString &value)
Adds an attribute called name with value value.
void setAttribute (const QString &name, qlonglong value)
The number is formatted according to the current locale.
void setAttribute (const QString &name, qulonglong value)
The number is formatted according to the current locale.
void setAttribute (const QString &name, int value)
The number is formatted according to the current locale.
void setAttribute (const QString &name, uint value)
The number is formatted according to the current locale.
void setAttribute (const QString &name, float value)
The number is formatted according to the current locale.
void setAttribute (const QString &name, double value)
The number is formatted according to the current locale.
QDomAttr setAttributeNode (const QDomAttr &newAttr)
Adds the attribute newAttr to this element.
QDomAttr setAttributeNodeNS (const QDomAttr &newAttr)
Adds the attribute newAttr to this element.
void setAttributeNS (const QString nsURI, const QString &qName, const QString &value)
Adds an attribute with the qualified name qName and the namespace URI nsURI with the value value.
void setAttributeNS (const QString nsURI, const QString &qName, int value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void setAttributeNS (const QString nsURI, const QString &qName, uint value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void setAttributeNS (const QString nsURI, const QString &qName, qlonglong value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void setAttributeNS (const QString nsURI, const QString &qName, qulonglong value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void setAttributeNS (const QString nsURI, const QString &qName, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void setTagName (const QString &name)
Sets this element's tag name to name.
QString tagName () const
Returns the tag name of this element.
QString text () const
Returns the element's text or an empty string.
Public Functions inherited from QDomNode
QDomNode appendChild (const QDomNode &newChild)
Appends newChild as the node's last child.
QDomNamedNodeMap attributes () const
Returns a named node map of all attributes.
QDomNodeList childNodes () const
Returns a list of all direct child nodes.
void clear ()
Converts the node into a null node; if it was not a null node before, its type and contents are deleted.
QDomNode cloneNode (bool deep=true) const
Creates a deep (not shallow) copy of the QDomNode.
int columnNumber () const
For nodes created by QDomDocument::setContent(), this function returns the column number in the XML document where the node was parsed.
QDomNode firstChild () const
Returns the first child of the node.
QDomElement firstChildElement (const QString &tagName=QString()) const
Returns the first child element with tag name tagName if tagName is non-empty; otherwise returns the first child element.
bool hasAttributes () const
Returns true if the node has attributes; otherwise returns false.
bool hasChildNodes () const
Returns true if the node has one or more children; otherwise returns false.
QDomNode insertAfter (const QDomNode &newChild, const QDomNode &refChild)
Inserts the node newChild after the child node refChild.
QDomNode insertBefore (const QDomNode &newChild, const QDomNode &refChild)
Inserts the node newChild before the child node refChild.
bool isAttr () const
Returns true if the node is an attribute; otherwise returns false.
bool isCDATASection () const
Returns true if the node is a CDATA section; otherwise returns false.
bool isCharacterData () const
Returns true if the node is a character data node; otherwise returns false.
bool isComment () const
Returns true if the node is a comment; otherwise returns false.
bool isDocument () const
Returns true if the node is a document; otherwise returns false.
bool isDocumentFragment () const
Returns true if the node is a document fragment; otherwise returns false.
bool isDocumentType () const
Returns true if the node is a document type; otherwise returns false.
bool isElement () const
Returns true if the node is an element; otherwise returns false.
bool isEntity () const
Returns true if the node is an entity; otherwise returns false.
bool isEntityReference () const
Returns true if the node is an entity reference; otherwise returns false.
bool isNotation () const
Returns true if the node is a notation; otherwise returns false.
bool isNull () const
Returns true if this node is null (i.e.
bool isProcessingInstruction () const
Returns true if the node is a processing instruction; otherwise returns false.
bool isSupported (const QString &feature, const QString &version) const
Returns true if the DOM implementation implements the feature feature and this feature is supported by this node in the version version; otherwise returns false.
bool isText () const
Returns true if the node is a text node; otherwise returns false.
QDomNode lastChild () const
Returns the last child of the node.
QDomElement lastChildElement (const QString &tagName=QString()) const
Returns the last child element with tag name tagName if tagName is non-empty; otherwise returns the last child element.
int lineNumber () const
For nodes created by QDomDocument::setContent(), this function returns the line number in the XML document where the node was parsed.
QString localName () const
If the node uses namespaces, this function returns the local name of the node; otherwise it returns an empty string.
QDomNode namedItem (const QString &name) const
Returns the first direct child node for which nodeName() equals name.
QString namespaceURI () const
Returns the namespace URI of this node or an empty string if the node has no namespace URI.
QDomNode nextSibling () const
Returns the next sibling in the document tree.
QDomElement nextSiblingElement (const QString &taName=QString()) const
Returns the next sibling element with tag name tagName if tagName is non-empty; otherwise returns any next sibling element.
QString nodeName () const
Returns the name of the node.
NodeType nodeType () const
Returns the type of the node.
QString nodeValue () const
Returns the value of the node.
void normalize ()
Calling normalize() on an element converts all its children into a standard form.
bool operator!= (const QDomNode &) const
Returns true if n and this DOM node are not equal; otherwise returns false.
QDomNode & operator= (const QDomNode &)
Assigns a copy of n to this DOM node.
bool operator== (const QDomNode &) const
Returns true if n and this DOM node are equal; otherwise returns false.
QDomDocument ownerDocument () const
Returns the document to which this node belongs.
QDomNode parentNode () const
Returns the parent node.
QString prefix () const
Returns the namespace prefix of the node or an empty string if the node has no namespace prefix.
QDomNode previousSibling () const
Returns the previous sibling in the document tree.
QDomElement previousSiblingElement (const QString &tagName=QString()) const
Returns the previous sibilng element with tag name tagName if tagName is non-empty; otherwise returns any previous sibling element.
QDomNode ()
Constructs a null node.
QDomNode (const QDomNode &)
Constructs a copy of n.
QDomNode removeChild (const QDomNode &oldChild)
Removes oldChild from the list of children.
QDomNode replaceChild (const QDomNode &newChild, const QDomNode &oldChild)
Replaces oldChild with newChild.
void save (QTextStream &, int) const
Writes the XML representation of the node and all its children to the stream str.
void save (QTextStream &, int, EncodingPolicy) const
If encodingPolicy is QDomNode::EncodingFromDocument, this function behaves as save(QTextStream &str, int indent).
void setNodeValue (const QString &)
Sets the node's value to v.
void setPrefix (const QString &pre)
If the node has a namespace prefix, this function changes the namespace prefix of the node to pre.
QDomAttr toAttr () const
Converts a QDomNode into a QDomAttr.
QDomCDATASection toCDATASection () const
Converts a QDomNode into a QDomCDATASection.
QDomCharacterData toCharacterData () const
Converts a QDomNode into a QDomCharacterData.
QDomComment toComment () const
Converts a QDomNode into a QDomComment.
QDomDocument toDocument () const
Converts a QDomNode into a QDomDocument.
QDomDocumentFragment toDocumentFragment () const
Converts a QDomNode into a QDomDocumentFragment.
QDomDocumentType toDocumentType () const
Converts a QDomNode into a QDomDocumentType.
QDomElement toElement () const
Converts a QDomNode into a QDomElement.
QDomEntity toEntity () const
Converts a QDomNode into a QDomEntity.
QDomEntityReference toEntityReference () const
Converts a QDomNode into a QDomEntityReference.
QDomNotation toNotation () const
Converts a QDomNode into a QDomNotation.
QDomProcessingInstruction toProcessingInstruction () const
Converts a QDomNode into a QDomProcessingInstruction.
QDomText toText () const
Converts a QDomNode into a QDomText.
~QDomNode ()
Destroys the object and frees its resources.
Private Functions
QDomElement (QDomElementPrivate *)
Friends
class QDomAttr
class QDomDocument
class QDomNode
Additional Inherited Members
Public Types inherited from QDomNode
enum EncodingPolicy { EncodingFromDocument = 1, EncodingFromTextStream = 2 }
This enum specifies how QDomNode::save() determines what encoding to use when serializing.
enum NodeType {
ElementNode = 1, AttributeNode = 2, TextNode = 3, CDATASectionNode = 4,
EntityReferenceNode = 5, EntityNode = 6, ProcessingInstructionNode = 7, CommentNode = 8,
DocumentNode = 9, DocumentTypeNode = 10, DocumentFragmentNode = 11, NotationNode = 12,
BaseNode = 21, CharacterDataNode = 22
}
This enum defines the type of the node:
Protected Functions inherited from QDomNode
QDomNode (QDomNodePrivate *)
Constructs a new node for the data n.
Protected Variables inherited from QDomNode
QDomNodePrivate * impl
Related Functions inherited from QDomNode
QTextStream & operator<< (QTextStream &str, const QDomNode &node)
Writes the XML representation of the node node and all its children to the stream str.
Detailed Description
The QDomElement class represents one element in the DOM tree.
Note
This class or function is reentrant.
Attention
Module: QtXml
Elements have a tagName() and zero or more attributes associated with them. The tag name can be changed with setTagName().
Element attributes are represented by QDomAttr objects that can be queried using the attribute() and attributeNode() functions. You can set attributes with the setAttribute() and setAttributeNode() functions. Attributes can be removed with removeAttribute(). There are namespace-aware equivalents to these functions, i.e. setAttributeNS(), setAttributeNodeNS() and removeAttributeNS().
If you want to access the text of a node use text(), e.g.
QDomElement e = //...
//...
QString s = e.text()
The text() function operates recursively to find the text (since not all elements contain text). If you want to find all the text in all of a node's children, iterate over the children looking for QDomText nodes, e.g.
QString text;
QDomElement element = doc.documentElement();
for(QDomNode n = element.firstChild(); !n.isNull(); n = n.nextSibling())
{
    QDomText t = n.toText();
    if (!t.isNull())
        text += t.data();
}
Note that we attempt to convert each node to a text node and use text() rather than using firstChild().toText().data() or n.toText().data() directly on the node, because the node may not be a text element.
You can get a list of all the decendents of an element which have a specified tag name with elementsByTagName() or elementsByTagNameNS().
To browse the elements of a dom document use firstChildElement(), lastChildElement(), nextSiblingElement() and previousSiblingElement(). For example, to iterate over all child elements called "entry" in a root element called "database", you can use:
QDomDocument doc = // ...
QDomElement root = doc.firstChildElement("database");
QDomElement elt = root.firstChildElement("entry");
for (; !elt.isNull(); elt = elt.nextSiblingElement("entry")) {
    // ...
}
For further information about the Document Object Model see Level 1 and Level 2 Core. For a more general introduction of the DOM implementation see the QDomDocument documentation.
Definition at line 476 of file qdom.h.
Constructors and Destructors
QDomElement() [1/3]
QDomElement::QDomElement ()
Constructs an empty element.
Use the QDomDocument::createElement() function to construct elements with content.
Definition at line 4808 of file qdom.cpp.
     : QDomNode()
 {
 }
QDomElement() [2/3]
QDomElement::QDomElement (const QDomElement & x)
Constructs a copy of x.
The data of the copy is shared (shallow copy): modifying one node will also change the other. If you want to make a deep copy, use cloneNode().
Definition at line 4820 of file qdom.cpp.
     : QDomNode(x)
 {
 }
QDomElement() [3/3]
QDomElement::QDomElement (QDomElementPrivate * n) private
Definition at line 4825 of file qdom.cpp.
     : QDomNode(n)
 {
 }
Functions
attribute()
QString QDomElement::attribute (const QString & name, const QString & defValue = QString()) const
Returns the attribute called name.
If the attribute does not exist defValue is returned.
See also
setAttribute() attributeNode() setAttributeNode() attributeNS()
Definition at line 4897 of file qdom.cpp.
Referenced by QDBusXmlParser::interfaces(), QDBusXmlParser::object(), QDBusXmlParser::objectTree(), parseAnnotations(), and parseArgs().
 {
     if (!impl)
         return defValue;
     return IMPL->attribute(name, defValue);
 }
attributeNode()
QDomAttr QDomElement::attributeNode (const QString & name)
Returns the QDomAttr object that corresponds to the attribute called name.
If no such attribute exists a null attribute is returned.
See also
setAttributeNode() attribute() setAttribute() attributeNodeNS()
Definition at line 5030 of file qdom.cpp.
 {
     if (!impl)
         return QDomAttr();
     return QDomAttr(IMPL->attributeNode(name));
 }
attributeNodeNS()
QDomAttr QDomElement::attributeNodeNS (const QString & nsURI, const QString & localName)
Returns the QDomAttr object that corresponds to the attribute with the local name localName and the namespace URI nsURI.
If no such attribute exists a null attribute is returned.
See also
setAttributeNode() attribute() setAttribute()
Definition at line 5203 of file qdom.cpp.
 {
     if (!impl)
         return QDomAttr();
     return QDomAttr(IMPL->attributeNodeNS(nsURI, localName));
 }
attributeNS()
QString QDomElement::attributeNS (const QString nsURI, const QString & localName, const QString & defValue = QString()) const
Returns the attribute with the local name localName and the namespace URI nsURI.
If the attribute does not exist defValue is returned.
See also
setAttributeNS() attributeNodeNS() setAttributeNodeNS() attribute()
Definition at line 5106 of file qdom.cpp.
 {
     if (!impl)
         return defValue;
     return IMPL->attributeNS(nsURI, localName, defValue);
 }
attributes()
QDomNamedNodeMap QDomElement::attributes () const
Returns a QDomNamedNodeMap containing all this element's attributes.
See also
attribute() setAttribute() attributeNode() setAttributeNode()
Definition at line 4884 of file qdom.cpp.
 {
     if (!impl)
         return QDomNamedNodeMap();
     return QDomNamedNodeMap(IMPL->attributes());
 }
elementsByTagName()
QDomNodeList QDomElement::elementsByTagName (const QString & tagname) const
Returns a QDomNodeList containing all descendants of this element named tagname encountered during a preorder traversal of the element subtree with this element as its root.
The order of the elements in the returned list is the order they are encountered during the preorder traversal.
See also
elementsByTagNameNS() QDomDocument::elementsByTagName()
Definition at line 5075 of file qdom.cpp.
Referenced by QDBusXmlParser::interfaces(), QDBusXmlParser::object(), QDBusXmlParser::objectTree(), parseAnnotations(), and parseArgs().
 {
     return QDomNodeList(new QDomNodeListPrivate(impl, tagname));
 }
elementsByTagNameNS()
QDomNodeList QDomElement::elementsByTagNameNS (const QString & nsURI, const QString & localName) const
Returns a QDomNodeList containing all descendants of this element with local name localName and namespace URI nsURI encountered during a preorder traversal of the element subtree with this element as its root.
The order of the elements in the returned list is the order they are encountered during the preorder traversal.
See also
elementsByTagName() QDomDocument::elementsByTagNameNS()
Definition at line 5236 of file qdom.cpp.
 {
     return QDomNodeList(new QDomNodeListPrivate(impl, nsURI, localName));
 }
hasAttribute()
bool QDomElement::hasAttribute (const QString & name) const
Returns true if this element has an attribute called name; otherwise returns false.
Note: This function does not take the presence of namespaces into account. As a result, the specified name will be tested against fully-qualified attribute names that include any namespace prefixes that may be present.
Use hasAttributeNS() to explicitly test for attributes with specific namespaces and names.
Definition at line 5092 of file qdom.cpp.
Referenced by parseArgs().
 {
     if (!impl)
         return false;
     return IMPL->hasAttribute(name);
 }
hasAttributeNS()
bool QDomElement::hasAttributeNS (const QString & nsURI, const QString & localName) const
Returns true if this element has an attribute with the local name localName and the namespace URI nsURI; otherwise returns false.
Definition at line 5246 of file qdom.cpp.
 {
     if (!impl)
         return false;
     return IMPL->hasAttributeNS(nsURI, localName);
 }
nodeType()
QDomNode::NodeType QDomElement::nodeType () const inline
Returns ElementNode.
Definition at line 522 of file qdom.h.
 { return ElementNode; }
operator=()
QDomElement & QDomElement::operator= (const QDomElement & x)
Assigns x to this DOM element.
The data of the copy is shared (shallow copy): modifying one node will also change the other. If you want to make a deep copy, use cloneNode().
Definition at line 4837 of file qdom.cpp.
 {
     return (QDomElement&) QDomNode::operator=(x);
 }
removeAttribute()
void QDomElement::removeAttribute (const QString & name)
Removes the attribute called name name from this element.
See also
setAttribute() attribute() removeAttributeNS()
Definition at line 5016 of file qdom.cpp.
 {
     if (!impl)
         return;
     IMPL->removeAttribute(name);
 }
removeAttributeNode()
QDomAttr QDomElement::removeAttributeNode (const QDomAttr & oldAttr)
Removes the attribute oldAttr from the element and returns it.
See also
attributeNode() setAttributeNode()
Definition at line 5059 of file qdom.cpp.
 {
     if (!impl)
         return QDomAttr(); // ### should this return oldAttr?
     return QDomAttr(IMPL->removeAttributeNode(((QDomAttrPrivate*)oldAttr.impl)));
 }
removeAttributeNS()
void QDomElement::removeAttributeNS (const QString & nsURI, const QString & localName)
Removes the attribute with the local name localName and the namespace URI nsURI from this element.
See also
setAttributeNS() attributeNS() removeAttribute()
Definition at line 5186 of file qdom.cpp.
 {
     if (!impl)
         return;
     QDomNodePrivate *n = IMPL->attributeNodeNS(nsURI, localName);
     if (!n)
         return;
     IMPL->removeAttribute(n->nodeName());
 }
setAttribute() [1/7]
void QDomElement::setAttribute (const QString & name, const QString & value)
Adds an attribute called name with value value.
If an attribute with the same name exists, its value is replaced by value.
See also
attribute() setAttributeNode() setAttributeNS()
Definition at line 4911 of file qdom.cpp.
 {
     if (!impl)
         return;
     IMPL->setAttribute(name, value);
 }
setAttribute() [2/7]
void QDomElement::setAttribute (const QString & name, qlonglong value)
The number is formatted according to the current locale.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4946 of file qdom.cpp.
 {
     if (!impl)
         return;
     QString x;
     x.setNum(value);
     IMPL->setAttribute(name, x);
 }
setAttribute() [3/7]
void QDomElement::setAttribute (const QString & name, qulonglong value)
The number is formatted according to the current locale.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4963 of file qdom.cpp.
 {
     if (!impl)
         return;
     QString x;
     x.setNum(value);
     IMPL->setAttribute(name, x);
 }
setAttribute() [4/7]
void QDomElement::setAttribute (const QString & name, int value) inline
The number is formatted according to the current locale.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 488 of file qdom.h.
         { setAttribute(name, qlonglong(value)); }
setAttribute() [5/7]
void QDomElement::setAttribute (const QString & name, uint value) inline
The number is formatted according to the current locale.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 490 of file qdom.h.
         { setAttribute(name, qulonglong(value)); }
setAttribute() [6/7]
void QDomElement::setAttribute (const QString & name, float value)
The number is formatted according to the current locale.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4980 of file qdom.cpp.
 {
     if (!impl)
         return;
     QString x;
     x.setNum(value);
     IMPL->setAttribute(name, x);
 }
setAttribute() [7/7]
void QDomElement::setAttribute (const QString & name, double value)
The number is formatted according to the current locale.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4997 of file qdom.cpp.
 {
     if (!impl)
         return;
     QString x;
     char buf[256];
     int count = qsnprintf(buf, sizeof(buf), "%.16g", value);
     if (count > 0)
         x = QString::fromLatin1(buf, count);
     else
         x.setNum(value); // Fallback
     IMPL->setAttribute(name, x);
 }
setAttributeNode()
QDomAttr QDomElement::setAttributeNode (const QDomAttr & newAttr)
Adds the attribute newAttr to this element.
If the element has another attribute that has the same name as newAttr, this function replaces that attribute and returns it; otherwise the function returns a null attribute.
See also
attributeNode() setAttribute() setAttributeNodeNS()
Definition at line 5047 of file qdom.cpp.
 {
     if (!impl)
         return QDomAttr();
     return QDomAttr(IMPL->setAttributeNode(((QDomAttrPrivate*)newAttr.impl)));
 }
setAttributeNodeNS()
QDomAttr QDomElement::setAttributeNodeNS (const QDomAttr & newAttr)
Adds the attribute newAttr to this element.
If the element has another attribute that has the same local name and namespace URI as newAttr, this function replaces that attribute and returns it; otherwise the function returns a null attribute.
See also
attributeNodeNS() setAttributeNS() setAttributeNode()
Definition at line 5220 of file qdom.cpp.
 {
     if (!impl)
         return QDomAttr();
     return QDomAttr(IMPL->setAttributeNodeNS(((QDomAttrPrivate*)newAttr.impl)));
 }
setAttributeNS() [1/6]
void QDomElement::setAttributeNS (const QString nsURI, const QString & qName, const QString & value)
Adds an attribute with the qualified name qName and the namespace URI nsURI with the value value.
If an attribute with the same local name and namespace URI exists, its prefix is replaced by the prefix of qName and its value is repaced by value.
Although qName is the qualified name, the local name is used to decide if an existing attribute's value should be replaced.
See also
attributeNS() setAttributeNodeNS() setAttribute()
Definition at line 5125 of file qdom.cpp.
 {
     if (!impl)
         return;
     IMPL->setAttributeNS(nsURI, qName, value);
 }
setAttributeNS() [2/6]
void QDomElement::setAttributeNS (const QString nsURI, const QString & qName, int value) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 503 of file qdom.h.
         { setAttributeNS(nsURI, qName, qlonglong(value)); }
setAttributeNS() [3/6]
void QDomElement::setAttributeNS (const QString nsURI, const QString & qName, uint value) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 505 of file qdom.h.
         { setAttributeNS(nsURI, qName, qulonglong(value)); }
setAttributeNS() [4/6]
void QDomElement::setAttributeNS (const QString nsURI, const QString & qName, qlonglong value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 5147 of file qdom.cpp.
 {
     if (!impl)
         return;
     QString x;
     x.setNum(value);
     IMPL->setAttributeNS(nsURI, qName, x);
 }
setAttributeNS() [5/6]
void QDomElement::setAttributeNS (const QString nsURI, const QString & qName, qulonglong value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 5159 of file qdom.cpp.
 {
     if (!impl)
         return;
     QString x;
     x.setNum(value);
     IMPL->setAttributeNS(nsURI, qName, x);
 }
setAttributeNS() [6/6]
void QDomElement::setAttributeNS (const QString nsURI, const QString & qName, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 5171 of file qdom.cpp.
 {
     if (!impl)
         return;
     QString x;
     x.setNum(value);
     IMPL->setAttributeNS(nsURI, qName, x);
 }
setTagName()
void QDomElement::setTagName (const QString & name)
Sets this element's tag name to name.
See also
tagName()
Definition at line 4856 of file qdom.cpp.
 {
     if (impl)
         impl->name = name;
 }
tagName()
QString QDomElement::tagName () const
Returns the tag name of this element.
For an XML element like this:
<img src="myimg.png">
the tagname would return "img".
See also
setTagName()
Definition at line 4871 of file qdom.cpp.
Referenced by QDomNode::firstChildElement(), QDomNode::lastChildElement(), QDomNode::nextSiblingElement(), and QDomNode::previousSiblingElement().
 {
     if (!impl)
         return QString();
     return impl->nodeName();
 }
text()
QString QDomElement::text () const
Returns the element's text or an empty string.
Example:
<h1>Hello <b>Qt</b> <![CDATA[<xml is cool>]]></h1>
The function text() of the QDomElement for the
tag, will return the following text: doc/src/snippets/code/src_xml_dom_qdom.cpp 14 Comments are ignored by this function. It only evaluates QDomText and QDomCDATASection objects.
Definition at line 5267 of file qdom.cpp.
 {
     if (!impl)
         return QString();
     return IMPL->text();
 }
Friends and Related Functions
QDomAttr
friend class QDomAttr friend
Definition at line 531 of file qdom.h.
QDomDocument
friend class QDomDocument friend
Definition at line 529 of file qdom.h.
QDomNode
friend class QDomNode friend
Definition at line 530 of file qdom.h.
The documentation for this class was generated from the following files:
/src/xml/dom/qdom.h
/src/xml/dom/qdom.cpp