Qt 4.8: QSpacerItem Class Reference
QSpacerItem Class Reference
The QSpacerItem class provides blank space in a layout.
#include <qlayoutitem.h>
Public Functions
void changeSize (int w, int h, QSizePolicy::Policy hData=QSizePolicy::Minimum, QSizePolicy::Policy vData=QSizePolicy::Minimum)
Changes this spacer item to have preferred width w, preferred height h, horizontal size policy hPolicy and vertical size policy vPolicy.
Qt::Orientations expandingDirections () const
Reimplemented Function
QRect geometry () const
Reimplemented Function
bool isEmpty () const
Returns true.
QSize maximumSize () const
Reimplemented Function
QSize minimumSize () const
Reimplemented Function
QSpacerItem (int w, int h, QSizePolicy::Policy hData=QSizePolicy::Minimum, QSizePolicy::Policy vData=QSizePolicy::Minimum)
Constructs a spacer item with preferred width w, preferred height h, horizontal size policy hPolicy and vertical size policy vPolicy.
void setGeometry (const QRect &)
Reimplemented Function
QSize sizeHint () const
Reimplemented Function
QSpacerItem * spacerItem ()
Returns a pointer to this object.
Public Functions inherited from QLayoutItem
Qt::Alignment alignment () const
Returns the alignment of this item.
QSizePolicy::ControlTypes controlTypes () const
Returns the control type(s) for the layout item.
virtual bool hasHeightForWidth () const
Returns true if this layout's preferred height depends on its width; otherwise returns false.
virtual int heightForWidth (int) const
Returns the preferred height for this layout item, given the width w.
virtual void invalidate ()
Invalidates any cached information in this layout item.
virtual QLayout * layout ()
If this item is a QLayout, it is returned as a QLayout; otherwise 0 is returned.
virtual int minimumHeightForWidth (int) const
Returns the minimum height this widget needs for the given width, w.
QLayoutItem (Qt::Alignment alignment=0)
Constructs a layout item with an alignment.
void setAlignment (Qt::Alignment a)
Sets the alignment of this item to alignment.
virtual QWidget * widget ()
If this item is a QWidget, it is returned as a QWidget; otherwise 0 is returned.
virtual ~QLayoutItem ()
Destroys the QLayoutItem.
Properties
int height
QRect rect
QSizePolicy sizeP
int width
Additional Inherited Members
Protected Variables inherited from QLayoutItem
Qt::Alignment align
Detailed Description
The QSpacerItem class provides blank space in a layout.
Normally, you don't need to use this class directly. Qt's built-in layout managers provide the following functions for manipulating empty space in layouts:
Class Functions
QHBoxLayout addSpacing(), addStretch(), insertSpacing(), insertStretch()
QGridLayout setRowMinimumHeight(), setRowStretch(), setColumnMinimumWidth(), setColumnStretch()
See also
QLayout, QWidgetItem, QLayoutItem::spacerItem()
Definition at line 96 of file qlayoutitem.h.
Constructors and Destructors
QSpacerItem()
QSpacerItem::QSpacerItem (int w, int h, QSizePolicy::Policy hPolicy = QSizePolicy::Minimum, QSizePolicy::Policy vPolicy = QSizePolicy::Minimum) inline
Constructs a spacer item with preferred width w, preferred height h, horizontal size policy hPolicy and vertical size policy vPolicy.
The default values provide a gap that is able to stretch if nothing else wants the space.
Definition at line 99 of file qlayoutitem.h.
         : width(w), height(h), sizeP(hData, vData) { }
Functions
changeSize()
void QSpacerItem::changeSize (int w, int h, QSizePolicy::Policy hPolicy = QSizePolicy::Minimum, QSizePolicy::Policy vPolicy = QSizePolicy::Minimum)
Changes this spacer item to have preferred width w, preferred height h, horizontal size policy hPolicy and vertical size policy vPolicy.
The default values provide a gap that is able to stretch if nothing else wants the space.
Note that if changeSize() is called after the spacer item has been added to a layout, it is necessary to invalidate the layout in order for the spacer item's new size to take effect.
See also
QSpacerItem::invalidate()
Definition at line 311 of file qlayoutitem.cpp.
Referenced by QCalendarWidgetPrivate::_q_yearClicked(), QCalendarWidgetPrivate::_q_yearEditingFinished(), changeSpacerSize(), QBoxLayout::setDirection(), QWizardPrivate::updateLayout(), and QComboBoxPrivateContainer::updateTopBottomMargin().
 {
     width = w;
     height = h;
     sizeP = QSizePolicy(hPolicy, vPolicy);
 }
expandingDirections()
Qt::Orientations QSpacerItem::expandingDirections () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 595 of file qlayoutitem.cpp.
Referenced by QBoxLayout::setDirection().
 {
     return sizeP.expandingDirections();
 }
geometry()
QRect QSpacerItem::geometry () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 534 of file qlayoutitem.cpp.
 {
     return rect;
 }
isEmpty()
bool QSpacerItem::isEmpty () const virtual
Returns true.
Implements QLayoutItem.
Definition at line 708 of file qlayoutitem.cpp.
 {
     return true;
 }
maximumSize()
QSize QSpacerItem::maximumSize () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 655 of file qlayoutitem.cpp.
 {
     return QSize(sizeP.horizontalPolicy() & QSizePolicy::GrowFlag ? QLAYOUTSIZE_MAX : width,
                  sizeP.verticalPolicy() & QSizePolicy::GrowFlag ? QLAYOUTSIZE_MAX : height);
 }
minimumSize()
QSize QSpacerItem::minimumSize () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 634 of file qlayoutitem.cpp.
 {
     return QSize(sizeP.horizontalPolicy() & QSizePolicy::ShrinkFlag ? 0 : width,
                  sizeP.verticalPolicy() & QSizePolicy::ShrinkFlag ? 0 : height);
 }
setGeometry()
void QSpacerItem::setGeometry (const QRect & r) virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 466 of file qlayoutitem.cpp.
 {
     rect = r;
 }
sizeHint()
QSize QSpacerItem::sizeHint () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 678 of file qlayoutitem.cpp.
Referenced by QBoxLayout::setDirection().
 {
     return QSize(width, height);
 }
spacerItem()
QSpacerItem * QSpacerItem::spacerItem () virtual
Returns a pointer to this object.
Reimplemented from QLayoutItem.
Definition at line 368 of file qlayoutitem.cpp.
 {
     return this;
 }
Properties
height
int QSpacerItem::height private
Definition at line 117 of file qlayoutitem.h.
rect
QRect QSpacerItem::rect private
Definition at line 119 of file qlayoutitem.h.
sizeP
QSizePolicy QSpacerItem::sizeP private
Definition at line 118 of file qlayoutitem.h.
width
int QSpacerItem::width private
Definition at line 116 of file qlayoutitem.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qlayoutitem.h
/src/gui/kernel/qlayoutitem.cpp