Qt 4.8: QPatternist::AbstractFloat< isDouble > Class Template Reference
QPatternist::AbstractFloat< isDouble > Class Template Reference
Base template class for Float and Double classes.
#include <qabstractfloat_p.h>
Public Functions
virtual Numeric::Ptr abs () const
virtual Numeric::Ptr ceiling () const
bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const
virtual Numeric::Ptr floor () const
virtual bool isInf () const
virtual bool isNaN () const
virtual bool isSigned () const
Returns true if this value is signed. If false is returned, the value is unsigned.
virtual Numeric::Ptr round () const
virtual Numeric::Ptr roundHalfToEven (const xsInteger scale) const
virtual QString stringValue () const
virtual xsDecimal toDecimal () const
virtual xsDouble toDouble () const
virtual xsFloat toFloat () const
virtual xsInteger toInteger () const
virtual Item toNegated () const
virtual qulonglong toUnsignedInteger () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static AtomicValue::Ptr fromLexical (const QString &strNumeric)
static Numeric::Ptr fromValue (const xsDouble num)
static bool isEqual (const xsDouble a, const xsDouble b)
Static Public Functions inherited from QPatternist::Numeric
static AtomicValue::Ptr fromLexical (const QString &number)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
AbstractFloat (const xsDouble num)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Private Functions
bool isZero () const
Static Private Functions
static int internalSignbit (const xsDouble v)
Properties
const xsDouble m_value
Additional Inherited Members
Public Types inherited from QPatternist::Numeric
typedef QExplicitlySharedDataPointer< Numeric > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Variables inherited from QSharedData
QAtomicInt ref
Static Protected Functions inherited from QPatternist::Numeric
static xsDouble roundFloat (const xsDouble val)
Implements fn:round() for types implemented with floating point.
Detailed Description
template<const bool isDouble>
class QPatternist::AbstractFloat< isDouble >
Base template class for Float and Double classes.
Author
Vincent Ricard magic.nosp@m.@mag.nosp@m.icnin.nosp@m.ja.o.nosp@m.rg
Definition at line 78 of file qabstractfloat_p.h.
Constructors and Destructors
AbstractFloat()
template<const bool isDouble> QPatternist::AbstractFloat< isDouble >::AbstractFloat (const xsDouble num) protected
Definition at line 49 of file qabstractfloat.cpp.
                                                          : m_value(num)
 {
 }
Functions
abs()
template<const bool isDouble> Numeric::Ptr QPatternist::AbstractFloat< isDouble >::abs () const virtual
Performs the algorithm specified for the function fn:abs on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.1 fn:abs
Implements QPatternist::Numeric.
Definition at line 275 of file qabstractfloat.cpp.
 {
     /* We must use fabs() instead of qAbs() because qAbs()
      * doesn't return 0 for -0.0. */
     return AbstractFloat<isDouble>::fromValue(static_cast<xsDouble>(fabs(m_value)));
 }
ceiling()
template<const bool isDouble> Numeric::Ptr QPatternist::AbstractFloat< isDouble >::ceiling () const virtual
Performs the algorithm specified for the function fn:ceiling on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.2 fn:ceiling
Implements QPatternist::Numeric.
Definition at line 269 of file qabstractfloat.cpp.
 {
     return AbstractFloat<isDouble>::fromValue(static_cast<xsDouble>(ceil(m_value)));
 }
evaluateEBV()
template<const bool isDouble> bool QPatternist::AbstractFloat< isDouble >::evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const virtual
Determines the Effective Boolean Value of this number.
Returns
false if the number is 0 or NaN, otherwise true.
Reimplemented from QPatternist::AtomicValue.
Definition at line 136 of file qabstractfloat.cpp.
 {
     if(isZero() || qIsNaN(m_value))
         return false;
     else
         return true;
 }
floor()
template<const bool isDouble> Numeric::Ptr QPatternist::AbstractFloat< isDouble >::floor () const virtual
Performs the algorithm specified for the function fn:floor on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.3 fn:floor
Implements QPatternist::Numeric.
Definition at line 263 of file qabstractfloat.cpp.
Referenced by QPatternist::AbstractFloat< isDouble >::roundHalfToEven().
 {
     return AbstractFloat<isDouble>::fromValue(static_cast<xsDouble>(::floor(m_value)));
 }
fromLexical()
template<const bool isDouble> AtomicValue::Ptr QPatternist::AbstractFloat< isDouble >::fromLexical (const QString & strNumeric) static
Definition at line 60 of file qabstractfloat.cpp.
 {
     /* QString::toDouble() handles the whitespace facet. */
     if(strNumeric == QLatin1String("NaN"))
         return isDouble ? CommonValues::DoubleNaN : CommonValues::FloatNaN;
     else if(strNumeric == QLatin1String("-INF"))
         return isDouble ? CommonValues::NegativeInfDouble : CommonValues::NegativeInfFloat;
     else if(strNumeric == QLatin1String("INF"))
         return isDouble ? CommonValues::InfDouble : CommonValues::InfFloat;
     /* QString::toDouble() supports any case as well as +INF, but we don't. */
     const QString toUpper(strNumeric.toUpper());
     if(toUpper == QLatin1String("-INF") ||
        toUpper == QLatin1String("INF")  ||
        toUpper == QLatin1String("+INF") ||
        toUpper == QLatin1String("NAN"))
     {
         return ValidationError::createError();
     }
     bool conversionOk = false;
     const xsDouble num = strNumeric.toDouble(&conversionOk);
     if(conversionOk)
         return AtomicValue::Ptr(new AbstractFloat<isDouble>(num));
     else
         return ValidationError::createError();
 }
fromValue()
template<const bool isDouble> Numeric::Ptr QPatternist::AbstractFloat< isDouble >::fromValue (const xsDouble num) static
Definition at line 54 of file qabstractfloat.cpp.
Referenced by QPatternist::AbstractFloat< isDouble >::abs(), QPatternist::AbstractFloat< isDouble >::ceiling(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDouble(), QPatternist::SubstringFN::evaluateSingleton(), QPatternist::AbstractFloat< isDouble >::floor(), QPatternist::AbstractFloat< isDouble >::round(), QPatternist::AbstractFloat< isDouble >::roundHalfToEven(), QPatternist::AbstractFloat< isDouble >::toNegated(), and QPatternist::AtomicValue::toXDM().
 {
     return Numeric::Ptr(new AbstractFloat<isDouble>(num));
 }
internalSignbit()
template<const bool isDouble> int QPatternist::AbstractFloat< isDouble >::internalSignbit (const xsDouble v) inline static private
From the Open Group's man page: "The signbit() macro shall return a non-zero value if and only if the sign of its argument value is negative."
MS Windows doesn't have std::signbit() so here's a reinvention of that function.
Definition at line 91 of file qabstractfloat.cpp.
Referenced by QPatternist::AbstractFloat< isDouble >::isEqual(), and QPatternist::AbstractFloat< isDouble >::stringValue().
 {
     Q_ASSERT_X(sizeof(xsDouble) == 8 || sizeof(xsDouble) == 4, Q_FUNC_INFO,
                "This implementation of signbit assumes xsDouble, that is qreal, is 64 bits large.");
     union
     {
         xsDouble asDouble;
         qint64 asInt;
     } value;
     value.asDouble = num;
     /* The highest bit, the 64'th for those who have 64bit floats, is the sign bit. So we pull it down until that bit is the
      * only one left. */
     if(sizeof(xsDouble) == 8)
         return value.asInt >> 63;
     else
         return value.asInt >> 31;
 }
isEqual()
template<const bool isDouble> bool QPatternist::AbstractFloat< isDouble >::isEqual (const xsDouble a, const xsDouble b) static
Performs floating point comparison.
Returns
true if a and are equal, otherwise false.
Definition at line 113 of file qabstractfloat.cpp.
Referenced by QPatternist::DurationNumericMathematician::calculate(), QPatternist::NumericToBooleanCaster::castFrom(), QPatternist::AbstractFloatComparator::compare(), QPatternist::AbstractFloatSortComparator< t_op >::compare(), QPatternist::DecimalComparator::compare(), QPatternist::AbstractFloatComparator::equals(), QPatternist::DecimalComparator::equals(), QPatternist::Decimal::evaluateEBV(), QPatternist::AbstractFloat< isDouble >::isZero(), QPatternist::GenericPredicate::mapToItem(), and QPatternist::Decimal::toString().
 {
     if(qIsInf(a))
         return qIsInf(b) && internalSignbit(a) == internalSignbit(b);
     else if(qIsInf(b))
         return qIsInf(a) && internalSignbit(a) == internalSignbit(b);
     else
     {
         /* Preferably, we would use std::numeric_limits<xsDouble>::espilon(), but
          * we cannot since we cannot depend on the STL. The small xs:double value below,
          * was extracted by printing the std::numeric_limits<xsDouble>::epsilon() using
          * gdb. */
         return qAbs(a - b) <= 2.2204460492503131e-16 * qAbs(a);
     }
 }
isInf()
template<const bool isDouble> bool QPatternist::AbstractFloat< isDouble >::isInf () const virtual
Determines whether this Numeric is an infinite number. Signedness is irrelevant, -INF as well as INF is considered infinity.
For numeric types that cannot represent infinity, such as xs:integer , this function should return false.
Returns
true if this Numeric is an infinite number
Implements QPatternist::Numeric.
Definition at line 289 of file qabstractfloat.cpp.
Referenced by QPatternist::AbstractFloat< isDouble >::roundHalfToEven().
 {
     return qIsInf(m_value);
 }
isNaN()
template<const bool isDouble> bool QPatternist::AbstractFloat< isDouble >::isNaN () const virtual
Determines whether this Numeric is not-a-number, NaN. For numeric types that cannot represent NaN, this function should return false.
Returns
true if this Numeric is NaN
Implements QPatternist::Numeric.
Definition at line 283 of file qabstractfloat.cpp.
Referenced by QPatternist::AbstractFloat< isDouble >::roundHalfToEven().
 {
     return qIsNaN(m_value);
 }
isSigned()
template<const bool isDouble> bool QPatternist::AbstractFloat< isDouble >::isSigned () const virtual
Returns true if this value is signed. If false is returned, the value is unsigned.
For float and decimal values, xs:double, xs:float and xs:decimal, the code asserts and behavior is undefined.
Implements QPatternist::Numeric.
Definition at line 307 of file qabstractfloat.cpp.
 {
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "It makes no sense to call this function, see Numeric::isSigned().");
     return false;
 }
isZero()
template<const bool isDouble> bool QPatternist::AbstractFloat< isDouble >::isZero () const inline private
Definition at line 130 of file qabstractfloat.cpp.
Referenced by QPatternist::AbstractFloat< isDouble >::evaluateEBV(), QPatternist::AbstractFloat< isDouble >::roundHalfToEven(), and QPatternist::AbstractFloat< isDouble >::stringValue().
 {
     return AbstractFloat<isDouble>::isEqual(m_value, 0.0);
 }
round()
template<const bool isDouble> Numeric::Ptr QPatternist::AbstractFloat< isDouble >::round () const virtual
Performs the algorithm specified for the function fn:round on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.4 fn:round
Implements QPatternist::Numeric.
Definition at line 230 of file qabstractfloat.cpp.
 {
     return AbstractFloat<isDouble>::fromValue(static_cast<xsDouble>(roundFloat(m_value)));
 }
roundHalfToEven()
template<const bool isDouble> Numeric::Ptr QPatternist::AbstractFloat< isDouble >::roundHalfToEven (const xsInteger scale) const virtual
Performs rounding as defined for the fn:round-half-to-even on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.5 fn:round-half-to-even
Implements QPatternist::Numeric.
Definition at line 236 of file qabstractfloat.cpp.
 {
     if(isNaN() || isInf() || isZero())
         return Numeric::Ptr(const_cast<AbstractFloat<isDouble> *>(this));
     else
     {
         /* The cast to double helps finding the correct pow() version on irix-cc. */
         const xsDouble powered = pow(double(10), double(precision));
         xsDouble val = powered * m_value;
         bool isHalf = false;
         if(val - 0.5 == ::floor(val))
             isHalf = true;
         val = m_value * powered + 0.5;
         val = ::floor(val);
         if(isHalf /*&& isOdd(val) or? TODO */)
             val -= 1;
         val /= powered;
         return fromValue(val);
     }
 }
stringValue()
template<const bool isDouble> QString QPatternist::AbstractFloat< isDouble >::stringValue () const virtual
Returns this AbstractFloat represented as an xs:string.
Note
In the XPath/XQuery languages, converting xs:double and xs:float to xs:string is not specified in XML Schema 1.0 Part 2: Datatypes Second Edition, but in XQuery 1.0 and XPath 2.0 Functions and Operators. This will change with W3C XML Schema 1.1
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 17.1.2 Casting to xs:string and xdt:untypedAtomic
Implements QPatternist::AtomicValue.
Definition at line 145 of file qabstractfloat.cpp.
 {
     if(qIsNaN(m_value))
         return QLatin1String("NaN");
     else if(qIsInf(m_value))
         return internalSignbit(m_value) == 0 ? QLatin1String("INF") : QLatin1String("-INF");
     /*
      * If SV has an absolute value that is greater than or equal to 0.000001
      * (one millionth) and less than 1000000 (one million),
      * then the value is converted to an xs:decimal and the resulting xs:decimal
      * is converted to an xs:string according to the rules above.
      */
     else if(0.000001 <= qAbs(m_value) && qAbs(m_value) < 1000000.0)
         return Decimal::toString(toDecimal());
     /*
      * If SV has the value positive or negative zero, TV is "0" or "-0" respectively.
      */
     else if(isZero())
         return internalSignbit(m_value) == 0 ? QLatin1String("0") : QLatin1String("-0");
     else
     {
         /*
          * Besides these special values, the general form of the canonical form for
          * xs:float and xs:double is a mantissa, which is a xs:decimal, followed by
          * the letter "E", followed by an exponent which is an xs:integer.
          */
         int sign;
         int decimalPoint;
         char *result = 0;
         static_cast<void>(qdtoa(m_value, -1, 0, &decimalPoint, &sign, 0, &result));
         /* If the copy constructor is used instead of QString::operator=(),
          * it doesn't compile. I have no idea why. */
         const QString qret(QString::fromLatin1(result));
         /* We use free() instead of delete here, because qlocale.cpp use malloc(). Spotted
          * by valgrind. */
         free(result);
         QString valueAsString;
         if(sign)
             valueAsString += QLatin1Char('-');
         valueAsString += qret.at(0);
         valueAsString += QLatin1Char('.');
         if(1 == qret.size())
             valueAsString += QLatin1Char('0');
         else
             valueAsString += qret.mid(1);
         valueAsString += QLatin1Char('E');
         decimalPoint--;
         valueAsString += QString::number(decimalPoint);
         return valueAsString;
     }
 }
toDecimal()
template<const bool isDouble> xsDecimal QPatternist::AbstractFloat< isDouble >::toDecimal () const virtual
Returns
the particular number's value as a native representation of the type xs:decimal. This can be considered that the value is cast to xs:decimal.
Implements QPatternist::Numeric.
Definition at line 224 of file qabstractfloat.cpp.
Referenced by QPatternist::AbstractFloat< isDouble >::stringValue().
 {
     return static_cast<xsDecimal>(m_value);
 }
toDouble()
template<const bool isDouble> xsDouble QPatternist::AbstractFloat< isDouble >::toDouble () const virtual
Returns
the particular number's value as a native representation of the type xs:double. This can be considered that the value is cast to xs:double.
Implements QPatternist::Numeric.
Definition at line 205 of file qabstractfloat.cpp.
 {
     return m_value;
 }
toFloat()
template<const bool isDouble> xsFloat QPatternist::AbstractFloat< isDouble >::toFloat () const virtual
Returns
the particular number's value as a native representation of the type xs:float. This can be considered that the value is cast to xs:float.
Implements QPatternist::Numeric.
Definition at line 217 of file qabstractfloat.cpp.
 {
     /* No cast, since xsFloat and xsDouble are typedef'ed with the same type. */
     return m_value;
 }
toInteger()
template<const bool isDouble> xsInteger QPatternist::AbstractFloat< isDouble >::toInteger () const virtual
Returns
the particular number's value as a native representation of the type xs:integer. This can be considered that the value is cast to xs:integer.
Implements QPatternist::Numeric.
Definition at line 211 of file qabstractfloat.cpp.
 {
     return static_cast<xsInteger>(m_value);
 }
toNegated()
template<const bool isDouble> Item QPatternist::AbstractFloat< isDouble >::toNegated () const virtual
Unary minus.
Implements QPatternist::Numeric.
Definition at line 301 of file qabstractfloat.cpp.
 {
     return fromValue(-m_value).data();
 }
toUnsignedInteger()
template<const bool isDouble> qulonglong QPatternist::AbstractFloat< isDouble >::toUnsignedInteger () const virtual
Returns
the number as an unsigned integer. If the value is not unsigned, the code asserts and behavior is undefined.
Implements QPatternist::Numeric.
Definition at line 315 of file qabstractfloat.cpp.
 {
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "It makes no sense to call this function, see Numeric::toUnsignedInteger().");
     return 0;
 }
type()
template<const bool isDouble> ItemType::Ptr QPatternist::AbstractFloat< isDouble >::type () const virtual
Implements QPatternist::AtomicValue.
Definition at line 295 of file qabstractfloat.cpp.
 {
     return isDouble ? BuiltinTypes::xsDouble : BuiltinTypes::xsFloat;
 }
Properties
m_value
template<const bool isDouble> const xsDouble QPatternist::AbstractFloat< isDouble >::m_value private
Definition at line 147 of file qabstractfloat_p.h.
Referenced by QPatternist::AbstractFloat< isDouble >::abs(), QPatternist::AbstractFloat< isDouble >::ceiling(), QPatternist::AbstractFloat< isDouble >::evaluateEBV(), QPatternist::AbstractFloat< isDouble >::floor(), QPatternist::AbstractFloat< isDouble >::isInf(), QPatternist::AbstractFloat< isDouble >::isNaN(), QPatternist::AbstractFloat< isDouble >::isZero(), QPatternist::AbstractFloat< isDouble >::round(), QPatternist::AbstractFloat< isDouble >::roundHalfToEven(), QPatternist::AbstractFloat< isDouble >::stringValue(), QPatternist::AbstractFloat< isDouble >::toDecimal(), QPatternist::AbstractFloat< isDouble >::toDouble(), QPatternist::AbstractFloat< isDouble >::toFloat(), QPatternist::AbstractFloat< isDouble >::toInteger(), and QPatternist::AbstractFloat< isDouble >::toNegated().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qabstractfloat_p.h
/src/xmlpatterns/data/qabstractfloat.cpp