Qt 4.8: QConnmanEngine Class Reference
QConnmanEngine Class Reference
#include <qconnmanengine.h>
Public Functions
virtual quint64 bytesReceived (const QString &id)
virtual quint64 bytesWritten (const QString &id)
virtual QNetworkConfigurationManager::Capabilities capabilities () const
void configurationChange (const QString &id)
virtual void connectToId (const QString &id)
bool connmanAvailable () const
QNetworkSessionPrivate * createSessionBackend ()
virtual QNetworkConfigurationPrivatePointer defaultConfiguration ()
virtual void disconnectFromId (const QString &id)
QList< QNetworkConfigurationPrivate * > getConfigurations ()
virtual QString getInterfaceFromId (const QString &id)
bool hasIdentifier (const QString &id)
Q_INVOKABLE void initialize ()
QConnmanEngine (QObject *parent=0)
Q_INVOKABLE void requestUpdate ()
QNetworkSession::State sessionStateForId (const QString &id)
virtual quint64 startTime (const QString &id)
~QConnmanEngine ()
Public Functions inherited from QBearerEngineImpl
QBearerEngineImpl (QObject *parent=0)
~QBearerEngineImpl ()
Public Functions inherited from QBearerEngine
bool configurationsInUse () const
QBearerEngine (QObject *parent=0)
virtual ~QBearerEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool requiresPolling () const
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void doRequestUpdate ()
void propertyChangedContext (const QString &, const QString &, const QDBusVariant &)
void servicePropertyChangedContext (const QString &, const QString &, const QDBusVariant &)
void technologyPropertyChangedContext (const QString &, const QString &, const QDBusVariant &)
Private Functions
void addServiceConfiguration (const QString &servicePath)
QNetworkConfiguration::StateFlags getStateForService (const QString &service)
bool isRoamingAllowed (const QString &context)
QString networkFromId (const QString &id)
QNetworkConfiguration::BearerType ofonoTechToBearerType (const QString &type)
void removeConfiguration (const QString &servicePath)
QString serviceFromId (const QString &id)
QNetworkConfiguration::BearerType typeToBearer (const QString &type)
Properties
QDateTime activeTime
QMap< QString, QString > configInterfaces
QConnmanManagerInterface * connmanManager
QList< QNetworkConfigurationPrivate * > foundConfigurations
QList< QString > serviceNetworks
QMap< QString, QConnmanTechnologyInterface * > technologies
Additional Inherited Members
Public Types inherited from QBearerEngineImpl
enum ConnectionError { InterfaceLookupError = 0, ConnectError, OperationNotSupported, DisconnectionError }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QBearerEngineImpl
void connectionError (const QString &id, QBearerEngineImpl::ConnectionError error)
Signals inherited from QBearerEngine
void configurationAdded (QNetworkConfigurationPrivatePointer config)
void configurationChanged (QNetworkConfigurationPrivatePointer config)
void configurationRemoved (QNetworkConfigurationPrivatePointer config)
void updateCompleted ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QBearerEngine
QHash< QString, QNetworkConfigurationPrivatePointer > accessPointConfigurations
QMutex mutex
QHash< QString, QNetworkConfigurationPrivatePointer > snapConfigurations
QHash< QString, QNetworkConfigurationPrivatePointer > userChoiceConfigurations
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 68 of file qconnmanengine.h.
Constructors and Destructors
QConnmanEngine()
QConnmanEngine::QConnmanEngine (QObject * parent = 0)
Definition at line 64 of file qconnmanengine.cpp.
 :   QBearerEngineImpl(parent),
     connmanManager(new QConnmanManagerInterface(this))
 {
 }
~QConnmanEngine()
QConnmanEngine::~QConnmanEngine ()
Definition at line 70 of file qconnmanengine.cpp.
 {
 }
Functions
addServiceConfiguration()
void QConnmanEngine::addServiceConfiguration (const QString & servicePath) private
Definition at line 524 of file qconnmanengine.cpp.
Referenced by initialize(), and propertyChangedContext().
 {
     QMutexLocker locker(&mutex);
     QConnmanServiceInterface *serv;
     serv = new QConnmanServiceInterface(servicePath);
     const QString id = QString::number(qHash(servicePath));
     if (!accessPointConfigurations.contains(id)) {
         serviceNetworks.append(servicePath);
         connect(serv,SIGNAL(propertyChangedContext(QString,QString,QDBusVariant)),
                 this,SLOT(servicePropertyChangedContext(QString,QString, QDBusVariant)));
         QNetworkConfigurationPrivate* cpPriv = new QNetworkConfigurationPrivate();
         QString networkName = serv->getName();
         const QString connectionType = serv->getType();
         if (connectionType == "ethernet") {
             cpPriv->bearerType = QNetworkConfiguration::BearerEthernet;
         } else if (connectionType == "wifi") {
             cpPriv->bearerType = QNetworkConfiguration::BearerWLAN;
         } else if (connectionType == "cellular") {
             cpPriv->bearerType = ofonoTechToBearerType("cellular");
             if(servicePath.isEmpty()) {
                 networkName = serv->getAPN();
                 if(networkName.isEmpty()) {
                     networkName = serv->getName();
                 }
             }
             cpPriv->roamingSupported = isRoamingAllowed(servicePath);
         } else if (connectionType == "wimax") {
             cpPriv->bearerType = QNetworkConfiguration::BearerWiMAX;
         } else {
             cpPriv->bearerType = QNetworkConfiguration::BearerUnknown;
         }
         cpPriv->name = networkName;
         cpPriv->isValid = true;
         cpPriv->id = id;
         cpPriv->type = QNetworkConfiguration::InternetAccessPoint;
         if(serv->getSecurity() == "none") {
             cpPriv->purpose = QNetworkConfiguration::PublicPurpose;
         } else {
             cpPriv->purpose = QNetworkConfiguration::PrivatePurpose;
         }
         cpPriv->state = getStateForService(servicePath);
         QNetworkConfigurationPrivatePointer ptr(cpPriv);
         accessPointConfigurations.insert(ptr->id, ptr);
         foundConfigurations.append(cpPriv);
         configInterfaces[cpPriv->id] = serv->getInterface();
         locker.unlock();
         emit configurationAdded(ptr);
         locker.relock();
         emit updateCompleted();
     }
 }
bytesReceived()
quint64 QConnmanEngine::bytesReceived (const QString & id) virtual
Reimplemented from QBearerEngineImpl.
Definition at line 267 of file qconnmanengine.cpp.
 {//TODO use connman counter API
     QMutexLocker locker(&mutex);
     quint64 result = 0;
     QString devFile = getInterfaceFromId(id);
     QFile rx("/sys/class/net/"+devFile+"/statistics/rx_bytes");
     if(rx.exists() && rx.open(QIODevice::ReadOnly | QIODevice::Text)) {
         QTextStream in(&rx);
         in >> result;
         rx.close();
     }
     return result;
 }
bytesWritten()
quint64 QConnmanEngine::bytesWritten (const QString & id) virtual
Reimplemented from QBearerEngineImpl.
Definition at line 252 of file qconnmanengine.cpp.
 {//TODO use connman counter API
     QMutexLocker locker(&mutex);
     quint64 result = 0;
     QString devFile = getInterfaceFromId(id);
     QFile tx("/sys/class/net/"+devFile+"/statistics/tx_bytes");
     if(tx.exists() && tx.open(QIODevice::ReadOnly | QIODevice::Text)) {
         QTextStream in(&tx);
         in >> result;
         tx.close();
     }
     return result;
 }
capabilities()
QNetworkConfigurationManager::Capabilities QConnmanEngine::capabilities () const virtual
Implements QBearerEngine.
Definition at line 291 of file qconnmanengine.cpp.
 {
     return QNetworkConfigurationManager::ForcedRoaming |
             QNetworkConfigurationManager::DataStatistics |
            QNetworkConfigurationManager::CanStartAndStopInterfaces;
 }
configurationChange()
void QConnmanEngine::configurationChange (const QString & id)
Definition at line 372 of file qconnmanengine.cpp.
Referenced by servicePropertyChangedContext().
 {
     QMutexLocker locker(&mutex);
     if (accessPointConfigurations.contains(id)) {
         QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
         QString servicePath = serviceFromId(id);
         QConnmanServiceInterface *serv;
         serv = new QConnmanServiceInterface(servicePath);
         QString networkName = serv->getName();
         QNetworkConfiguration::StateFlags curState = getStateForService(servicePath);
         ptr->mutex.lock();
         if (!ptr->isValid) {
             ptr->isValid = true;
         }
         if (ptr->name != networkName) {
             ptr->name = networkName;
         }
         if (ptr->state != curState) {
             ptr->state = curState;
         }
         ptr->mutex.unlock();
         locker.unlock();
         emit configurationChanged(ptr);
         locker.relock();
     }
      locker.unlock();
      emit updateCompleted();
 }
connectToId()
void QConnmanEngine::connectToId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 145 of file qconnmanengine.cpp.
 {
     QMutexLocker locker(&mutex);
     QString servicePath = serviceFromId(id);
     QConnmanServiceInterface serv(servicePath);
     if(!serv.isValid()) {
         emit connectionError(id, QBearerEngineImpl::InterfaceLookupError);
     } else {
         if(serv.getType() != "cellular") {
             serv.connect();
         } else {
             QOfonoManagerInterface ofonoManager(0);
             QString modemPath = ofonoManager.currentModem().path();
             QOfonoDataConnectionManagerInterface dc(modemPath,0);
             foreach(const QDBusObjectPath dcPath,dc.getPrimaryContexts()) {
                 if(dcPath.path().contains(servicePath.section("_",-1))) {
                     QOfonoPrimaryDataContextInterface primaryContext(dcPath.path(),0);
                     primaryContext.setActive(true);
                 }
             }
         }
     }
 }
connmanAvailable()
bool QConnmanEngine::connmanAvailable () const
Definition at line 74 of file qconnmanengine.cpp.
Referenced by QConnmanEnginePlugin::create().
 {
     QMutexLocker locker(&mutex);
     return connmanManager->isValid();
 }
createSessionBackend()
QNetworkSessionPrivate * QConnmanEngine::createSessionBackend () virtual
Implements QBearerEngine.
Definition at line 298 of file qconnmanengine.cpp.
 {
      return new QNetworkSessionPrivateImpl;
 }
defaultConfiguration()
QNetworkConfigurationPrivatePointer QConnmanEngine::defaultConfiguration () virtual
Implements QBearerEngine.
Definition at line 303 of file qconnmanengine.cpp.
 {
     return QNetworkConfigurationPrivatePointer();
 }
disconnectFromId()
void QConnmanEngine::disconnectFromId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 170 of file qconnmanengine.cpp.
 {
     QMutexLocker locker(&mutex);
     QString servicePath = serviceFromId(id);
     QConnmanServiceInterface serv(servicePath);
     if(!serv.isValid()) {
         emit connectionError(id, DisconnectionError);
     } else {
         if(serv.getType() != "cellular") {
             serv.disconnect();
         } else {
             QOfonoManagerInterface ofonoManager(0);
             QString modemPath = ofonoManager.currentModem().path();
             QOfonoDataConnectionManagerInterface dc(modemPath,0);
             foreach(const QDBusObjectPath dcPath,dc.getPrimaryContexts()) {
                 if(dcPath.path().contains(servicePath.section("_",-1))) {
                     QOfonoPrimaryDataContextInterface primaryContext(dcPath.path(),0);
                     primaryContext.setActive(false);
                 }
             }
         }
     }
 }
doRequestUpdate
void QConnmanEngine::doRequestUpdate () private slot
Definition at line 126 of file qconnmanengine.cpp.
Referenced by requestUpdate().
 {
     connmanManager->requestScan("");
     getConfigurations();
     emit updateCompleted();
 }
getConfigurations()
QList< QNetworkConfigurationPrivate * > QConnmanEngine::getConfigurations ()
Definition at line 101 of file qconnmanengine.cpp.
Referenced by doRequestUpdate(), and initialize().
 {
     QMutexLocker locker(&mutex);
     QList<QNetworkConfigurationPrivate *> fetchedConfigurations;
     QNetworkConfigurationPrivate* cpPriv = 0;
     for (int i = 0; i < foundConfigurations.count(); ++i) {
         QNetworkConfigurationPrivate *config = new QNetworkConfigurationPrivate;
         cpPriv = foundConfigurations.at(i);
         config->name = cpPriv->name;
         config->isValid = cpPriv->isValid;
         config->id = cpPriv->id;
         config->state = cpPriv->state;
         config->type = cpPriv->type;
         config->roamingSupported = cpPriv->roamingSupported;
         config->purpose = cpPriv->purpose;
         config->bearerType = cpPriv->bearerType;
         fetchedConfigurations.append(config);
         delete config;
     }
     return fetchedConfigurations;
 }
getInterfaceFromId()
QString QConnmanEngine::getInterfaceFromId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 133 of file qconnmanengine.cpp.
Referenced by bytesReceived(), and bytesWritten().
 {
     QMutexLocker locker(&mutex);
     return configInterfaces.value(id);
 }
getStateForService()
QNetworkConfiguration::StateFlags QConnmanEngine::getStateForService (const QString & service) private
Definition at line 412 of file qconnmanengine.cpp.
Referenced by addServiceConfiguration(), and configurationChange().
 {
     QMutexLocker locker(&mutex);
     QConnmanServiceInterface serv(service);
     QNetworkConfiguration::StateFlags flag = QNetworkConfiguration::Defined;
     if( serv.getType() == "cellular") {
         if(serv.isSetupRequired()) {
             flag = ( flag | QNetworkConfiguration::Defined);
         } else {
             flag = ( flag | QNetworkConfiguration::Discovered);
         }
     } else {
         if(serv.isFavorite()) {
             flag = ( flag | QNetworkConfiguration::Discovered);
         } else {
             flag = QNetworkConfiguration::Undefined;
         }
     }
     if(serv.getState() == "ready" || serv.getState() == "online") {
         flag = ( flag | QNetworkConfiguration::Active);
     }
     return flag;
 }
hasIdentifier()
bool QConnmanEngine::hasIdentifier (const QString & id) virtual
Implements QBearerEngine.
Definition at line 139 of file qconnmanengine.cpp.
 {
     QMutexLocker locker(&mutex);
     return accessPointConfigurations.contains(id);
 }
initialize()
void QConnmanEngine::initialize ()
Definition at line 80 of file qconnmanengine.cpp.
 {
     connect(connmanManager,SIGNAL(propertyChangedContext(QString,QString,QDBusVariant)),
             this,SLOT(propertyChangedContext(QString,QString,QDBusVariant)));
     foreach(const QString techPath, connmanManager->getTechnologies()) {
         QConnmanTechnologyInterface *tech;
         tech = new QConnmanTechnologyInterface(techPath, this);
         connect(tech,SIGNAL(propertyChangedContext(QString,QString,QDBusVariant)),
                 this,SLOT(technologyPropertyChangedContext(QString,QString,QDBusVariant)));
     }
     foreach(const QString servPath, connmanManager->getServices()) {
         addServiceConfiguration(servPath);
     }
     // Get current list of access points.
     getConfigurations();
 }
isRoamingAllowed()
bool QConnmanEngine::isRoamingAllowed (const QString & context) private
Definition at line 490 of file qconnmanengine.cpp.
Referenced by addServiceConfiguration().
 {
     QOfonoManagerInterface ofonoManager(this);
     QString modemPath = ofonoManager.currentModem().path();
     QOfonoDataConnectionManagerInterface dc(modemPath,this);
     foreach(const QDBusObjectPath dcPath,dc.getPrimaryContexts()) {
         if(dcPath.path().contains(context.section("_",-1))) {
             return dc.isRoamingAllowed();
         }
     }
     return false;
 }
networkFromId()
QString QConnmanEngine::networkFromId (const QString & id) private
ofonoTechToBearerType()
QNetworkConfiguration::BearerType QConnmanEngine::ofonoTechToBearerType (const QString & type) private
Definition at line 458 of file qconnmanengine.cpp.
Referenced by addServiceConfiguration(), and typeToBearer().
 {
     QOfonoManagerInterface ofonoManager(this);
     QOfonoNetworkRegistrationInterface ofonoNetwork(ofonoManager.currentModem().path(),this);
     if(ofonoNetwork.isValid()) {
         foreach(const QDBusObjectPath op,ofonoNetwork.getOperators() ) {
             QOfonoNetworkOperatorInterface opIface(op.path(),this);
             foreach(const QString opTech, opIface.getTechnologies()) {
                 if(opTech == "gsm") {
                     return QNetworkConfiguration::Bearer2G;
                 }
                 if(opTech == "edge"){
                     return QNetworkConfiguration::BearerCDMA2000; //wrong, I know
                 }
                 if(opTech == "umts"){
                     return QNetworkConfiguration::BearerWCDMA;
                 }
                 if(opTech == "hspa"){
                     return QNetworkConfiguration::BearerHSPA;
                 }
                 if(opTech == "lte"){
                     return QNetworkConfiguration::BearerWiMAX; //not exact
                 }
             }
         }
     }
     return QNetworkConfiguration::BearerUnknown;
 }
propertyChangedContext
void QConnmanEngine::propertyChangedContext (const QString & path, const QString & item, const QDBusVariant & value) private slot
Definition at line 308 of file qconnmanengine.cpp.
Referenced by addServiceConfiguration(), initialize(), removeConfiguration(), and technologyPropertyChangedContext().
 {
     Q_UNUSED(path);
     QMutexLocker locker(&mutex);
     if(item == "Services") {
         QDBusArgument arg = qvariant_cast<QDBusArgument>(value.variant());
         QStringList list = qdbus_cast<QStringList>(arg);
         if(list.count() > accessPointConfigurations.count()) {
             foreach(const QString service, list) {
                 addServiceConfiguration(service);
             }
         }
     }
     if(item == "Technologies") {
         QDBusArgument arg = qvariant_cast<QDBusArgument>(value.variant());
         QStringList newlist = qdbus_cast<QStringList>(arg);
         if(newlist.count() > 0) {
             QMap<QString,QConnmanTechnologyInterface *> oldtech = technologies;
             foreach(const QString listPath, newlist) {
                 if(!oldtech.contains(listPath)) {
                     QConnmanTechnologyInterface *tech;
                     tech = new QConnmanTechnologyInterface(listPath,this);
                     connect(tech,SIGNAL(propertyChangedContext(QString,QString,QDBusVariant)),
                             this,SLOT(technologyPropertyChangedContext(QString,QString,QDBusVariant)));
                     technologies.insert(listPath, tech);
                 }
             }
         }
     }
     if(item == "State") {
 // qDebug() << value.variant();
     }
 }
removeConfiguration()
void QConnmanEngine::removeConfiguration (const QString & servicePath) private
Definition at line 503 of file qconnmanengine.cpp.
 {
     QMutexLocker locker(&mutex);
     if (accessPointConfigurations.contains(id)) {
         QString service = serviceFromId(id);
         QConnmanServiceInterface serv(service);
         disconnect(&serv,SIGNAL(propertyChangedContext(QString,QString,QDBusVariant)),
                    this,SLOT(servicePropertyChangedContext(QString,QString, QDBusVariant)));
         serviceNetworks.removeOne(service);
         QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.take(id);
         locker.unlock();
         emit configurationRemoved(ptr);
         locker.relock();
     }
 }
requestUpdate()
void QConnmanEngine::requestUpdate ()
Definition at line 194 of file qconnmanengine.cpp.
 {
     QMutexLocker locker(&mutex);
     QTimer::singleShot(0, this, SLOT(doRequestUpdate()));
 }
requiresPolling()
bool QConnmanEngine::requiresPolling () const protected virtual
Reimplemented from QBearerEngine.
Definition at line 586 of file qconnmanengine.cpp.
 {
     return false;
 }
serviceFromId()
QString QConnmanEngine::serviceFromId (const QString & id) private
Definition at line 200 of file qconnmanengine.cpp.
Referenced by configurationChange(), connectToId(), disconnectFromId(), removeConfiguration(), and sessionStateForId().
 {
     QMutexLocker locker(&mutex);
     foreach(const QString service, serviceNetworks) {
         if (id == QString::number(qHash(service)))
             return service;
     }
     return QString();
 }
servicePropertyChangedContext
void QConnmanEngine::servicePropertyChangedContext (const QString & path, const QString & item, const QDBusVariant & value) private slot
Definition at line 346 of file qconnmanengine.cpp.
Referenced by addServiceConfiguration(), and removeConfiguration().
 {
     QMutexLocker locker(&mutex);
     if(item == "State") {
         configurationChange(QString::number(qHash(path)));
         if(value.variant().toString() == "failure") {
             QConnmanServiceInterface serv(path);
             emit connectionError(QString::number(qHash(path)), ConnectError);
         }
     }
 }
sessionStateForId()
QNetworkSession::State QConnmanEngine::sessionStateForId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 211 of file qconnmanengine.cpp.
 {
     QMutexLocker locker(&mutex);
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
     if (!ptr)
         return QNetworkSession::Invalid;
     if (!ptr->isValid) {
         return QNetworkSession::Invalid;
     }
     QString service = serviceFromId(id);
     QConnmanServiceInterface serv(service);
     QString servState = serv.getState();
     if(serv.isFavorite() && (servState == "idle" || servState == "failure")) {
         return QNetworkSession::Disconnected;
     }
     if(servState == "association" || servState == "configuration" || servState == "login") {
         return QNetworkSession::Connecting;
     }
     if(servState == "ready" || servState == "online") {
         return QNetworkSession::Connected;
     }
     if ((ptr->state & QNetworkConfiguration::Discovered) ==
                 QNetworkConfiguration::Discovered) {
         return QNetworkSession::Disconnected;
     } else if ((ptr->state & QNetworkConfiguration::Defined) == QNetworkConfiguration::Defined) {
         return QNetworkSession::NotAvailable;
     } else if ((ptr->state & QNetworkConfiguration::Undefined) ==
                 QNetworkConfiguration::Undefined) {
         return QNetworkSession::NotAvailable;
     }
     return QNetworkSession::Invalid;
 }
startTime()
quint64 QConnmanEngine::startTime (const QString & id) virtual
Reimplemented from QBearerEngineImpl.
Definition at line 281 of file qconnmanengine.cpp.
 {
     // TODO
     QMutexLocker locker(&mutex);
     if (activeTime.isNull()) {
         return 0;
     }
     return activeTime.secsTo(QDateTime::currentDateTime());
 }
technologyPropertyChangedContext
void QConnmanEngine::technologyPropertyChangedContext (const QString & path, const QString & item, const QDBusVariant & value) private slot
Definition at line 359 of file qconnmanengine.cpp.
Referenced by initialize(), and propertyChangedContext().
 {
     if(item == "State") {
         if(value.variant().toString() == "offline") {
             QConnmanTechnologyInterface tech(path);
             disconnect(&tech,SIGNAL(propertyChangedContext(QString,QString,QDBusVariant)),
                        this,SLOT(technologyPropertyChangedContext(QString,QString,QDBusVariant)));
             technologies.remove(path);
         }
     }
 }
typeToBearer()
QNetworkConfiguration::BearerType QConnmanEngine::typeToBearer (const QString & type) private
Definition at line 438 of file qconnmanengine.cpp.
 {
     if (type == "wifi")
         return QNetworkConfiguration::BearerWLAN;
     if (type == "ethernet")
         return QNetworkConfiguration::BearerEthernet;
     if (type == "bluetooth")
         return QNetworkConfiguration::BearerBluetooth;
     if (type == "cellular") {
         return ofonoTechToBearerType(type);
     }
     if (type == "wimax")
         return QNetworkConfiguration::BearerWiMAX;
 //    if(type == "gps")
 //    if(type == "vpn")
     return QNetworkConfiguration::BearerUnknown;
 }
Properties
activeTime
QDateTime QConnmanEngine::activeTime private
Definition at line 122 of file qconnmanengine.h.
Referenced by startTime().
configInterfaces
QMap<QString,QString> QConnmanEngine::configInterfaces private
Definition at line 126 of file qconnmanengine.h.
Referenced by addServiceConfiguration(), and getInterfaceFromId().
connmanManager
QConnmanManagerInterface* QConnmanEngine::connmanManager private
Definition at line 110 of file qconnmanengine.h.
Referenced by connmanAvailable(), doRequestUpdate(), and initialize().
foundConfigurations
QList<QNetworkConfigurationPrivate *> QConnmanEngine::foundConfigurations private
Definition at line 112 of file qconnmanengine.h.
Referenced by addServiceConfiguration(), and getConfigurations().
serviceNetworks
QList<QString> QConnmanEngine::serviceNetworks private
Definition at line 127 of file qconnmanengine.h.
Referenced by addServiceConfiguration(), removeConfiguration(), and serviceFromId().
technologies
QMap<QString,QConnmanTechnologyInterface *> QConnmanEngine::technologies private
Definition at line 125 of file qconnmanengine.h.
Referenced by propertyChangedContext(), and technologyPropertyChangedContext().
The documentation for this class was generated from the following files:
/src/plugins/bearer/connman/qconnmanengine.h
/src/plugins/bearer/connman/qconnmanengine.cpp