Qt 4.8: QScriptDebuggerValueProperty Class Reference
QScriptDebuggerValueProperty Class Reference
#include <qscriptdebuggervalueproperty_p.h>
Public Functions
QScriptValue::PropertyFlags flags () const
Returns the flags of this QScriptDebuggerValueProperty.
bool isValid () const
Returns true if this QScriptDebuggerValueProperty is valid, otherwise returns false.
QString name () const
Returns the name of this QScriptDebuggerValueProperty.
QScriptDebuggerValueProperty & operator= (const QScriptDebuggerValueProperty &other)
Assigns the other property to this QScriptDebuggerValueProperty.
QScriptDebuggerValueProperty ()
Constructs an invalid QScriptDebuggerValueProperty.
QScriptDebuggerValueProperty (const QString &name, const QScriptDebuggerValue &value, const QString &valueAsString, QScriptValue::PropertyFlags flags)
Constructs a QScriptDebuggerValueProperty with the given name, value and flags.
QScriptDebuggerValueProperty (const QScriptDebuggerValueProperty &other)
Constructs a QScriptDebuggerValueProperty that is a copy of the other property.
QScriptDebuggerValue value () const
Returns the value of this QScriptDebuggerValueProperty.
QString valueAsString () const
~QScriptDebuggerValueProperty ()
Destroys this QScriptDebuggerValueProperty.
Properties
QScopedSharedPointer< QScriptDebuggerValuePropertyPrivate > d_ptr
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QScriptDebuggerValueProperty &property)
Writes the given property to the specified stream.
QDataStream & operator>> (QDataStream &stream, QScriptDebuggerValueProperty &property)
Reads a QScriptDebuggerValueProperty from the specified stream into the given property.
Detailed Description
Warning
This function is not part of the public interface.
Definition at line 68 of file qscriptdebuggervalueproperty_p.h.
Constructors and Destructors
QScriptDebuggerValueProperty() [1/3]
QScriptDebuggerValueProperty::QScriptDebuggerValueProperty ()
Constructs an invalid QScriptDebuggerValueProperty.
Definition at line 83 of file qscriptdebuggervalueproperty.cpp.
Referenced by operator>>().
     : d_ptr(0)
 {
 }
QScriptDebuggerValueProperty() [2/3]
QScriptDebuggerValueProperty::QScriptDebuggerValueProperty (const QString & name, const QScriptDebuggerValue & value, const QString & valueAsString, QScriptValue::PropertyFlags flags)
Constructs a QScriptDebuggerValueProperty with the given name, value and flags.
Definition at line 92 of file qscriptdebuggervalueproperty.cpp.
     : d_ptr(new QScriptDebuggerValuePropertyPrivate)
 {
     d_ptr->name = name;
     d_ptr->value = value;
     d_ptr->valueAsString = valueAsString;
     d_ptr->flags = flags;
     d_ptr->ref.ref();
 }
QScriptDebuggerValueProperty() [3/3]
QScriptDebuggerValueProperty::QScriptDebuggerValueProperty (const QScriptDebuggerValueProperty & other)
Constructs a QScriptDebuggerValueProperty that is a copy of the other property.
Definition at line 108 of file qscriptdebuggervalueproperty.cpp.
     : d_ptr(other.d_ptr.data())
 {
     if (d_ptr)
         d_ptr->ref.ref();
 }
~QScriptDebuggerValueProperty()
QScriptDebuggerValueProperty::~QScriptDebuggerValueProperty ()
Destroys this QScriptDebuggerValueProperty.
Definition at line 118 of file qscriptdebuggervalueproperty.cpp.
 {
 }
Functions
flags()
QScriptValue::PropertyFlags QScriptDebuggerValueProperty::flags () const
Returns the flags of this QScriptDebuggerValueProperty.
Definition at line 164 of file qscriptdebuggervalueproperty.cpp.
Referenced by debuggerScriptValuePropertyToScriptValue(), QScriptDebuggerLocalsModel::flags(), operator<<(), operator>>(), and QScriptDebuggerValueProperty().
 {
     Q_D(const QScriptDebuggerValueProperty);
     if (!d)
         return 0;
     return d->flags;
 }
isValid()
bool QScriptDebuggerValueProperty::isValid () const
Returns true if this QScriptDebuggerValueProperty is valid, otherwise returns false.
Definition at line 176 of file qscriptdebuggervalueproperty.cpp.
 {
     Q_D(const QScriptDebuggerValueProperty);
     return (d != 0);
 }
name()
QString QScriptDebuggerValueProperty::name () const
Returns the name of this QScriptDebuggerValueProperty.
Definition at line 134 of file qscriptdebuggervalueproperty.cpp.
Referenced by QScriptDebuggerLocalsModel::data(), debuggerScriptValuePropertyToScriptValue(), QScriptDebuggerLocalsModelNode::findChild(), QScriptDebuggerLocalsModelPrivate::get(), operator>>(), QScriptDebuggerValueProperty(), and QScriptDebuggerLocalsModelPrivate::reallySyncIndex().
 {
     Q_D(const QScriptDebuggerValueProperty);
     if (!d)
         return QString();
     return d->name;
 }
operator=()
QScriptDebuggerValueProperty & QScriptDebuggerValueProperty::operator= (const QScriptDebuggerValueProperty & other)
Assigns the other property to this QScriptDebuggerValueProperty.
Definition at line 125 of file qscriptdebuggervalueproperty.cpp.
 {
     d_ptr.assign(other.d_ptr.data());
     return *this;
 }
value()
QScriptDebuggerValue QScriptDebuggerValueProperty::value () const
Returns the value of this QScriptDebuggerValueProperty.
Definition at line 145 of file qscriptdebuggervalueproperty.cpp.
Referenced by QScriptDebuggerLocalsModel::canFetchMore(), QScriptDebuggerLocalsModel::data(), debuggerScriptValuePropertyToScriptValue(), QScriptDebuggerLocalsModelPrivate::get(), QScriptDebuggerLocalsModel::hasChildren(), QScriptDebuggerLocalsModel::init(), QScriptDebuggerLocalsModelPrivate::isTopLevelNode(), operator>>(), QScriptDebuggerLocalsModelPrivate::populateIndex(), QScriptDebuggerValueProperty(), QScriptDebuggerLocalsModelPrivate::repopulate(), and QScriptDebuggerLocalsModel::sync().
 {
     Q_D(const QScriptDebuggerValueProperty);
     if (!d)
         return QScriptDebuggerValue();
     return d->value;
 }
valueAsString()
QString QScriptDebuggerValueProperty::valueAsString () const
Definition at line 153 of file qscriptdebuggervalueproperty.cpp.
Referenced by QScriptDebuggerLocalsModel::data(), debuggerScriptValuePropertyToScriptValue(), operator>>(), and QScriptDebuggerValueProperty().
 {
     Q_D(const QScriptDebuggerValueProperty);
     if (!d)
         return QString();
     return d->valueAsString;
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & stream, const QScriptDebuggerValueProperty & property) related
Writes the given property to the specified stream.
Definition at line 191 of file qscriptdebuggervalueproperty.cpp.
 {
     out << property.name();
     out << property.value();
     out << property.valueAsString();
     out << (quint32)property.flags();
     return out;
 }
operator>>()
QDataStream & operator>> (QDataStream & stream, QScriptDebuggerValueProperty & property) related
Reads a QScriptDebuggerValueProperty from the specified stream into the given property.
Definition at line 210 of file qscriptdebuggervalueproperty.cpp.
 {
     QString name;
     QScriptDebuggerValue value;
     QString valueAsString;
     quint32 flags;
     in >> name;
     in >> value;
     in >> valueAsString;
     in >> flags;
     property = QScriptDebuggerValueProperty(
         name, value, valueAsString, QScriptValue::PropertyFlags(flags));
     return in;
 }
Properties
d_ptr
QScopedSharedPointer<QScriptDebuggerValuePropertyPrivate> QScriptDebuggerValueProperty::d_ptr private
Definition at line 89 of file qscriptdebuggervalueproperty_p.h.
Referenced by operator=(), and QScriptDebuggerValueProperty().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggervalueproperty_p.h
/src/scripttools/debugging/qscriptdebuggervalueproperty.cpp