Qt 4.8: QMdiArea Class Reference
QMdiArea Class Reference
The QMdiArea widget provides an area in which MDI windows are displayed.
#include <qmdiarea.h>
Public Types
enum AreaOption { DontMaximizeSubWindowOnActivation = 0x1 }
This enum describes options that customize the behavior of the QMdiArea.
enum ViewMode { SubWindowView, TabbedView }
This enum describes the view mode of the area; i.
enum WindowOrder { CreationOrder, StackingOrder, ActivationHistoryOrder }
Specifies the criteria to use for ordering the list of child windows returned by subWindowList().
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void activateNextSubWindow ()
Gives the keyboard focus to another window in the list of child windows.
void activatePreviousSubWindow ()
Gives the keyboard focus to another window in the list of child windows.
void cascadeSubWindows ()
Arranges all the child windows in a cascade pattern.
void closeActiveSubWindow ()
Closes the active subwindow.
void closeAllSubWindows ()
Closes all subwindows by sending a QCloseEvent to each window.
void setActiveSubWindow (QMdiSubWindow *window)
Activates the subwindow window.
void tileSubWindows ()
Arranges all child windows in a tile pattern.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void subWindowActivated (QMdiSubWindow *)
QMdiArea emits this signal after window has been activated.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
WindowOrder activationOrder () const
QMdiSubWindow * activeSubWindow () const
Returns a pointer to the current active subwindow.
QMdiSubWindow * addSubWindow (QWidget *widget, Qt::WindowFlags flags=0)
Adds widget as a new subwindow to the MDI area.
QBrush background () const
QMdiSubWindow * currentSubWindow () const
Returns a pointer to the current subwindow, or 0 if there is no current subwindow.
bool documentMode () const
QSize minimumSizeHint () const
Reimplemented Function
QMdiArea (QWidget *parent=0)
Constructs an empty mdi area.
void removeSubWindow (QWidget *widget)
Removes widget from the MDI area.
void setActivationOrder (WindowOrder order)
void setBackground (const QBrush &background)
void setDocumentMode (bool enabled)
void setOption (AreaOption option, bool on=true)
If on is true, option is enabled on the MDI area; otherwise it is disabled.
void setTabPosition (QTabWidget::TabPosition position)
void setTabsClosable (bool closable)
void setTabShape (QTabWidget::TabShape shape)
void setTabsMovable (bool movable)
void setViewMode (ViewMode mode)
QSize sizeHint () const
Reimplemented Function
QList< QMdiSubWindow * > subWindowList (WindowOrder order=CreationOrder) const
Returns a list of all subwindows in the MDI area.
QTabWidget::TabPosition tabPosition () const
bool tabsClosable () const
QTabWidget::TabShape tabShape () const
bool tabsMovable () const
bool testOption (AreaOption opton) const
Returns true if option is enabled; otherwise returns false.
ViewMode viewMode () const
~QMdiArea ()
Destroys the MDI area.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Slots
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport() has been called.
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Functions
void childEvent (QChildEvent *childEvent)
Reimplemented Function
bool event (QEvent *event)
Reimplemented Function
bool eventFilter (QObject *object, QEvent *event)
Reimplemented Function
void paintEvent (QPaintEvent *paintEvent)
Reimplemented Function
void resizeEvent (QResizeEvent *resizeEvent)
Reimplemented Function
void scrollContentsBy (int dx, int dy)
Reimplemented Function
void showEvent (QShowEvent *showEvent)
Reimplemented Function
void timerEvent (QTimerEvent *timerEvent)
Reimplemented Function
bool viewportEvent (QEvent *event)
Reimplemented Function
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
WindowOrder activationOrder
the ordering criteria for subwindow lists
QBrush background
the background brush for the workspace
bool documentMode
whether the tab bar is set to document mode in tabbed view mode.
QTabWidget::TabPosition tabPosition
the position of the tabs in tabbed view mode.
bool tabsClosable
whether the tab bar should place close buttons on each tab in tabbed view mode.
QTabWidget::TabShape tabShape
the shape of the tabs in tabbed view mode.
bool tabsMovable
whether the user can move the tabs within the tabbar area in tabbed view mode.
ViewMode viewMode
the way sub-windows are displayed in the QMdiArea.
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QMdiArea widget provides an area in which MDI windows are displayed.
Since
4.3
QMdiArea functions, essentially, like a window manager for MDI windows. For instance, it draws the windows it manages on itself and arranges them in a cascading or tile pattern. QMdiArea is commonly used as the center widget in a QMainWindow to create MDI applications, but can also be placed in any layout. The following code adds an area to a main window:
    QMainWindow *mainWindow = new QMainWindow;
    mainWindow->setCentralWidget(mdiArea);
Unlike the window managers for top-level windows, all window flags (Qt::WindowFlags) are supported by QMdiArea as long as the flags are supported by the current widget style. If a specific flag is not supported by the style (e.g., the Qt::WindowShadeButtonHint), you can still shade the window with showShaded().
Subwindows in QMdiArea are instances of QMdiSubWindow. They are added to an MDI area with addSubWindow(). It is common to pass a QWidget, which is set as the internal widget, to this function, but it is also possible to pass a QMdiSubWindow directly.The class inherits QWidget, and you can use the same API as with a normal top-level window when programming. QMdiSubWindow also has behavior that is specific to MDI windows. See the QMdiSubWindow class description for more details.
A subwindow becomes active when it gets the keyboard focus, or when setFocus() is called. The user activates a window by moving focus in the usual ways. The MDI area emits the subWindowActivated() signal when the active window changes, and the activeSubWindow() function returns the active subwindow.
The convenience function subWindowList() returns a list of all subwindows. This information could be used in a popup menu containing a list of windows, for example.
The subwindows are sorted by the current QMdiArea::WindowOrder. This is used for the subWindowList() and for activateNextSubWindow() and acivatePreviousSubWindow(). Also, it is used when cascading or tiling the windows with cascadeSubWindows() and tileSubWindows().
QMdiArea provides two built-in layout strategies for subwindows: cascadeSubWindows() and tileSubWindows(). Both are slots and are easily connected to menu entries.
Note
The default scroll bar property for QMdiArea is Qt::ScrollBarAlwaysOff.
See also
QMdiSubWindow
Definition at line 59 of file qmdiarea.h.
Enumerations
AreaOption
enum QMdiArea::AreaOption
This enum describes options that customize the behavior of the QMdiArea.
DontMaximizeSubWindowOnActivation When the active subwindow is maximized, the default behavior is to maximize the next subwindow that is activated. Set this option if you do not want this behavior.
Enumerator
DontMaximizeSubWindowOnActivation
Definition at line 77 of file qmdiarea.h.
                     {
         DontMaximizeSubWindowOnActivation = 0x1
     };
ViewMode
enum QMdiArea::ViewMode
This enum describes the view mode of the area; i.
Since
4.4
e. how sub-windows will be displayed.
SubWindowView Display sub-windows with window frames (default).
TabbedView Display sub-windows with tabs in a tab bar.
See also
setViewMode()
Enumerator
SubWindowView
TabbedView
Definition at line 88 of file qmdiarea.h.
                   {
         SubWindowView,
         TabbedView
     };
WindowOrder
enum QMdiArea::WindowOrder
Specifies the criteria to use for ordering the list of child windows returned by subWindowList().
The functions cascadeSubWindows() and tileSubWindows() follow this order when arranging the windows.
CreationOrder The windows are returned in the order of their creation.
StackingOrder The windows are returned in the order in which they are stacked, with the top-most window being last in the list.
ActivationHistoryOrder The windows are returned in the order in which they were activated.
See also
subWindowList()
Enumerator
CreationOrder
StackingOrder
ActivationHistoryOrder
Definition at line 82 of file qmdiarea.h.
                      {
         CreationOrder,
         StackingOrder,
         ActivationHistoryOrder
     };
Constructors and Destructors
QMdiArea()
QMdiArea::QMdiArea (QWidget * parent = 0)
Constructs an empty mdi area.
parent is passed to QWidget's constructor.
Definition at line 1715 of file qmdiarea.cpp.
     : QAbstractScrollArea(*new QMdiAreaPrivate, parent)
 {
     setBackground(palette().brush(QPalette::Dark));
     setFrameStyle(QFrame::NoFrame);
     setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
     setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
     setViewport(0);
     setFocusPolicy(Qt::NoFocus);
     QApplication::instance()->installEventFilter(this);
 }
~QMdiArea()
QMdiArea::~QMdiArea ()
Destroys the MDI area.
Definition at line 1730 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     delete d->cascader;
     d->cascader = 0;
     delete d->regularTiler;
     d->regularTiler = 0;
     delete d->iconTiler;
     d->iconTiler = 0;
     delete d->placer;
     d->placer = 0;
 }
Functions
activateNextSubWindow
void QMdiArea::activateNextSubWindow () slot
Gives the keyboard focus to another window in the list of child windows.
The window activated will be the next one determined by the current activation order.
See also
activatePreviousSubWindow(), QMdiArea::WindowOrder
Definition at line 1927 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (d->childWindows.isEmpty())
         return;
     QMdiSubWindow *next = d->nextVisibleSubWindow(1, d->activationOrder);
     if (next)
         d->activateWindow(next);
 }
activatePreviousSubWindow
void QMdiArea::activatePreviousSubWindow () slot
Gives the keyboard focus to another window in the list of child windows.
The window activated will be the previous one determined by the current activation order.
See also
activateNextSubWindow(), QMdiArea::WindowOrder
Definition at line 1945 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (d->childWindows.isEmpty())
         return;
     QMdiSubWindow *previous = d->nextVisibleSubWindow(-1, d->activationOrder);
     if (previous)
         d->activateWindow(previous);
 }
activationOrder()
WindowOrder QMdiArea::activationOrder () const
Referenced by setBackground().
activeSubWindow()
QMdiSubWindow * QMdiArea::activeSubWindow () const
Returns a pointer to the current active subwindow.
If no window is currently active, 0 is returned.
Subwindows are treated as top-level windows with respect to window state, i.e., if a widget outside the MDI area is the active window, no subwindow will be active. Note that if a widget in the window in which the MDI area lives gains focus, the window will be activated.
See also
setActiveSubWindow(), Qt::WindowState
Definition at line 1832 of file qmdiarea.cpp.
Referenced by QAccessibleMdiArea::state().
 {
     Q_D(const QMdiArea);
     return d->active;
 }
addSubWindow()
QMdiSubWindow * QMdiArea::addSubWindow (QWidget * widget, Qt::WindowFlags windowFlags = 0)
Adds widget as a new subwindow to the MDI area.
If windowFlags are non-zero, they will override the flags set on the widget.
The widget can be either a QMdiSubWindow or another QWidget (in which case the MDI area will create a subwindow and set the widget as the internal widget).
Note
Once the subwindow has been added, its parent will be the viewport widget of the QMdiArea.
    QMdiArea mdiArea;
    QMdiSubWindow *subWindow1 = new QMdiSubWindow;
    subWindow1->setWidget(internalWidget1);
    subWindow1->setAttribute(Qt::WA_DeleteOnClose);
    mdiArea.addSubWindow(subWindow1);
    QMdiSubWindow *subWindow2 =
    mdiArea.addSubWindow(internalWidget2);
When you create your own subwindow, you must set the Qt::WA_DeleteOnClose widget attribute if you want the window to be deleted when closed in the MDI area. If not, the window will be hidden and the MDI area will not activate the next subwindow.
Returns the QMdiSubWindow that is added to the MDI area.
See also
removeSubWindow()
Definition at line 1979 of file qmdiarea.cpp.
 {
     if (!widget) {
         qWarning("QMdiArea::addSubWindow: null pointer to widget");
         return 0;
     }
     Q_D(QMdiArea);
     // QWidget::setParent clears focusWidget so store it
     QWidget *childFocus = widget->focusWidget();
     QMdiSubWindow *child = qobject_cast<QMdiSubWindow *>(widget);
     // Widget is already a QMdiSubWindow
     if (child) {
         if (d->childWindows.indexOf(child) != -1) {
             qWarning("QMdiArea::addSubWindow: window is already added");
             return child;
         }
         child->setParent(viewport(), windowFlags ? windowFlags : child->windowFlags());
     // Create a QMdiSubWindow
     } else {
         child = new QMdiSubWindow(viewport(), windowFlags);
         child->setAttribute(Qt::WA_DeleteOnClose);
         child->setWidget(widget);
         Q_ASSERT(child->testAttribute(Qt::WA_DeleteOnClose));
     }
     if (childFocus)
         childFocus->setFocus();
     d->appendChild(child);
     return child;
 }
background()
QBrush QMdiArea::background () const
Referenced by removeSubWindow().
cascadeSubWindows
void QMdiArea::cascadeSubWindows () slot
Arranges all the child windows in a cascade pattern.
See also
tileSubWindows()
Definition at line 2521 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (!d->cascader)
         d->cascader = new SimpleCascader;
     d->rearrange(d->cascader);
 }
childEvent()
void QMdiArea::childEvent (QChildEvent * childEvent) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 2315 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (childEvent->type() == QEvent::ChildPolished) {
         if (QMdiSubWindow *mdiChild = qobject_cast<QMdiSubWindow *>(childEvent->child())) {
             if (d->childWindows.indexOf(mdiChild) == -1)
                 d->appendChild(mdiChild);
         }
     }
 }
closeActiveSubWindow
void QMdiArea::closeActiveSubWindow () slot
Closes the active subwindow.
See also
closeAllSubWindows()
Definition at line 1870 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (d->active)
         d->active->close();
 }
closeAllSubWindows
void QMdiArea::closeAllSubWindows () slot
Closes all subwindows by sending a QCloseEvent to each window.
You may receive subWindowActivated() signals from subwindows before they are closed (if the MDI area activates the subwindow when another is closing).
Subwindows that ignore the close event will remain open.
See also
closeActiveSubWindow()
Definition at line 1904 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (d->childWindows.isEmpty())
         return;
     d->isSubWindowsTiled = false;
     foreach (QMdiSubWindow *child, d->childWindows) {
         if (!sanityCheck(child, "QMdiArea::closeAllSubWindows"))
             continue;
         child->close();
     }
     d->updateScrollBars();
 }
currentSubWindow()
QMdiSubWindow * QMdiArea::currentSubWindow () const
Returns a pointer to the current subwindow, or 0 if there is no current subwindow.
This function will return the same as activeSubWindow() if the QApplication containing QMdiArea is active.
See also
activeSubWindow(), QApplication::activeWindow()
Definition at line 1800 of file qmdiarea.cpp.
 {
     Q_D(const QMdiArea);
     if (d->childWindows.isEmpty())
         return 0;
     if (d->active)
         return d->active;
     if (d->isActivated && !window()->isMinimized())
         return 0;
     Q_ASSERT(d->indicesToActivatedChildren.count() > 0);
     int index = d->indicesToActivatedChildren.at(0);
     Q_ASSERT(index >= 0 && index < d->childWindows.size());
     QMdiSubWindow *current = d->childWindows.at(index);
     Q_ASSERT(current);
     return current;
 }
documentMode()
bool QMdiArea::documentMode () const
Referenced by setViewMode().
event()
bool QMdiArea::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2532 of file qmdiarea.cpp.
Referenced by eventFilter(), and viewportEvent().
 {
     Q_D(QMdiArea);
     switch (event->type()) {
 #ifdef Q_WS_WIN
     // QWidgetPrivate::hide_helper activates another sub-window when closing a
     // modal dialog on Windows (see activateWindow() inside the the ifdef).
     case QEvent::WindowUnblocked:
         d->activateCurrentWindow();
         break;
 #endif
     case QEvent::WindowActivate: {
         d->isActivated = true;
         if (d->childWindows.isEmpty())
             break;
         if (!d->active)
             d->activateCurrentWindow();
         d->setChildActivationEnabled(false, true);
         break;
     }
     case QEvent::WindowDeactivate:
         d->isActivated = false;
         d->setChildActivationEnabled(false, true);
         break;
     case QEvent::StyleChange:
         // Re-tile the views if we're in tiled mode. Re-tile means we will change
         // the geometry of the children, which in turn means 'isSubWindowsTiled'
         // is set to false, so we have to update the state at the end.
         if (d->isSubWindowsTiled) {
             tileSubWindows();
             d->isSubWindowsTiled = true;
         }
         break;
     case QEvent::WindowIconChange:
         foreach (QMdiSubWindow *window, d->childWindows) {
             if (sanityCheck(window, "QMdiArea::WindowIconChange"))
                 QApplication::sendEvent(window, event);
         }
         break;
     case QEvent::Hide:
         d->setActive(d->active, false, false);
         d->setChildActivationEnabled(false);
         break;
 #ifndef QT_NO_TABBAR
     case QEvent::LayoutDirectionChange:
         d->updateTabBarGeometry();
         break;
 #endif
     default:
         break;
     }
     return QAbstractScrollArea::event(event);
 }
eventFilter()
bool QMdiArea::eventFilter (QObject * object, QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 2589 of file qmdiarea.cpp.
 {
     if (!object)
         return QAbstractScrollArea::eventFilter(object, event);
     Q_D(QMdiArea);
     // Global key events with Ctrl modifier.
     if (event->type() == QEvent::KeyPress || event->type() == QEvent::KeyRelease) {
         QKeyEvent *keyEvent = static_cast<QKeyEvent *>(event);
         // Ingore key events without a Ctrl modifier (except for press/release on the modifier itself).
 #ifdef Q_WS_MAC
         if (!(keyEvent->modifiers() & Qt::MetaModifier) && keyEvent->key() != Qt::Key_Meta)
 #else
         if (!(keyEvent->modifiers() & Qt::ControlModifier) && keyEvent->key() != Qt::Key_Control)
 #endif
             return QAbstractScrollArea::eventFilter(object, event);
         // Find closest mdi area (in case we have a nested workspace).
         QMdiArea *area = mdiAreaParent(static_cast<QWidget *>(object));
         if (!area)
             return QAbstractScrollArea::eventFilter(object, event);
         const bool keyPress = (event->type() == QEvent::KeyPress) ? true : false;
         // 1) Ctrl-Tab once -> activate the previously active window.
         // 2) Ctrl-Tab (Tab, Tab, ...) -> iterate through all windows (activateNextSubWindow()).
         // 3) Ctrl-Shift-Tab (Tab, Tab, ...) -> iterate through all windows in the opposite
         //    direction (activatePreviousSubWindow())
         switch (keyEvent->key()) {
 #ifdef Q_WS_MAC
         case Qt::Key_Meta:
 #else
         case Qt::Key_Control:
 #endif
             if (keyPress)
                 area->d_func()->startTabToPreviousTimer();
             else
                 area->d_func()->activateHighlightedWindow();
             break;
         case Qt::Key_Tab:
         case Qt::Key_Backtab:
             if (keyPress)
                 area->d_func()->highlightNextSubWindow(keyEvent->key() == Qt::Key_Tab ? 1 : -1);
             return true;
 #ifndef QT_NO_RUBBERBAND
         case Qt::Key_Escape:
             area->d_func()->hideRubberBand();
             break;
 #endif
         default:
             break;
         }
         return QAbstractScrollArea::eventFilter(object, event);
     }
     QMdiSubWindow *subWindow = qobject_cast<QMdiSubWindow *>(object);
     if (!subWindow) {
         // QApplication events:
         if (event->type() == QEvent::ApplicationActivate && !d->active
             && isVisible() && !window()->isMinimized()) {
             d->activateCurrentWindow();
         } else if (event->type() == QEvent::ApplicationDeactivate && d->active) {
             d->setActive(d->active, false, false);
         }
         return QAbstractScrollArea::eventFilter(object, event);
     }
     // QMdiSubWindow events:
     switch (event->type()) {
     case QEvent::Move:
     case QEvent::Resize:
         if (d->tileCalledFromResizeEvent)
             break;
         d->updateScrollBars();
         if (!subWindow->isMinimized())
             d->isSubWindowsTiled = false;
         break;
     case QEvent::Show:
 #ifndef QT_NO_TABBAR
         if (d->tabBar) {
             const int tabIndex = d->childWindows.indexOf(subWindow);
             if (!d->tabBar->isTabEnabled(tabIndex))
                 d->tabBar->setTabEnabled(tabIndex, true);
         }
 #endif // QT_NO_TABBAR
         // fall through
     case QEvent::Hide:
         d->isSubWindowsTiled = false;
         break;
 #ifndef QT_NO_RUBBERBAND
     case QEvent::Close:
         if (d->childWindows.indexOf(subWindow) == d->indexToHighlighted)
             d->hideRubberBand();
         break;
 #endif
 #ifndef QT_NO_TABBAR
     case QEvent::WindowTitleChange:
     case QEvent::ModifiedChange:
         if (d->tabBar)
             d->tabBar->setTabText(d->childWindows.indexOf(subWindow), tabTextFor(subWindow));
         break;
     case QEvent::WindowIconChange:
         if (d->tabBar)
             d->tabBar->setTabIcon(d->childWindows.indexOf(subWindow), subWindow->windowIcon());
         break;
 #endif // QT_NO_TABBAR
     default:
         break;
     }
     return QAbstractScrollArea::eventFilter(object, event);
 }
minimumSizeHint()
QSize QMdiArea::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1775 of file qmdiarea.cpp.
 {
     Q_D(const QMdiArea);
     QSize size(style()->pixelMetric(QStyle::PM_MdiSubWindowMinimizedWidth, 0, this),
                style()->pixelMetric(QStyle::PM_TitleBarHeight, 0, this));
     size = size.expandedTo(QAbstractScrollArea::minimumSizeHint());
     if (!d->scrollBarsEnabled()) {
         foreach (QMdiSubWindow *child, d->childWindows) {
             if (!sanityCheck(child, "QMdiArea::sizeHint"))
                 continue;
             size = size.expandedTo(child->minimumSizeHint());
         }
     }
     return size.expandedTo(QApplication::globalStrut());
 }
paintEvent()
void QMdiArea::paintEvent (QPaintEvent * paintEvent) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2706 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     QPainter painter(d->viewport);
     const QVector<QRect> &exposedRects = paintEvent->region().rects();
     for (int i = 0; i < exposedRects.size(); ++i)
         painter.fillRect(exposedRects.at(i), d->background);
 }
removeSubWindow()
void QMdiArea::removeSubWindow (QWidget * widget)
Removes widget from the MDI area.
The widget must be either a QMdiSubWindow or a widget that is the internal widget of a subwindow. Note widget is never actually deleted by QMdiArea. If a QMdiSubWindow is passed in its parent is set to 0 and it is removed, but if an internal widget is passed in the child widget is set to 0 but the QMdiSubWindow is not removed.
See also
addSubWindow()
Definition at line 2022 of file qmdiarea.cpp.
 {
     if (!widget) {
         qWarning("QMdiArea::removeSubWindow: null pointer to widget");
         return;
     }
     Q_D(QMdiArea);
     if (d->childWindows.isEmpty())
         return;
     if (QMdiSubWindow *child = qobject_cast<QMdiSubWindow *>(widget)) {
         int index = d->childWindows.indexOf(child);
         if (index == -1) {
             qWarning("QMdiArea::removeSubWindow: window is not inside workspace");
             return;
         }
         d->disconnectSubWindow(child);
         d->childWindows.removeAll(child);
         d->indicesToActivatedChildren.removeAll(index);
         d->updateActiveWindow(index, d->active == child);
         child->setParent(0);
         return;
     }
     bool found = false;
     foreach (QMdiSubWindow *child, d->childWindows) {
         if (!sanityCheck(child, "QMdiArea::removeSubWindow"))
             continue;
         if (child->widget() == widget) {
             child->setWidget(0);
             Q_ASSERT(!child->widget());
             found = true;
             break;
         }
     }
     if (!found)
         qWarning("QMdiArea::removeSubWindow: widget is not child of any window inside QMdiArea");
 }
resizeEvent()
void QMdiArea::resizeEvent (QResizeEvent * resizeEvent) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2329 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (d->childWindows.isEmpty()) {
         resizeEvent->ignore();
         return;
     }
 #ifndef QT_NO_TABBAR
     d->updateTabBarGeometry();
 #endif
     // Re-tile the views if we're in tiled mode. Re-tile means we will change
     // the geometry of the children, which in turn means 'isSubWindowsTiled'
     // is set to false, so we have to update the state at the end.
     if (d->isSubWindowsTiled) {
         d->tileCalledFromResizeEvent = true;
         tileSubWindows();
         d->tileCalledFromResizeEvent = false;
         d->isSubWindowsTiled = true;
         d->startResizeTimer();
         // We don't have scroll bars or any maximized views.
         return;
     }
     // Resize maximized views.
     bool hasMaximizedSubWindow = false;
     foreach (QMdiSubWindow *child, d->childWindows) {
         if (sanityCheck(child, "QMdiArea::resizeEvent") && child->isMaximized()
                 && child->size() != resizeEvent->size()) {
             child->resize(resizeEvent->size());
             if (!hasMaximizedSubWindow)
                 hasMaximizedSubWindow = true;
         }
     }
     d->updateScrollBars();
     // Minimized views are stacked under maximized views so there's
     // no need to re-arrange minimized views on-demand. Start a timer
     // just to make things faster with subsequent resize events.
     if (hasMaximizedSubWindow)
         d->startResizeTimer();
     else
         d->arrangeMinimizedSubWindows();
 }
scrollContentsBy()
void QMdiArea::scrollContentsBy (int dx, int dy) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2491 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     const bool wasSubWindowsTiled = d->isSubWindowsTiled;
     d->ignoreGeometryChange = true;
     viewport()->scroll(isLeftToRight() ? dx : -dx, dy);
     d->arrangeMinimizedSubWindows();
     d->ignoreGeometryChange = false;
     if (wasSubWindowsTiled)
         d->isSubWindowsTiled = true;
 }
setActivationOrder()
void QMdiArea::setActivationOrder (WindowOrder order)
Definition at line 2110 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (order != d->activationOrder)
         d->activationOrder = order;
 }
setActiveSubWindow
void QMdiArea::setActiveSubWindow (QMdiSubWindow * window) slot
Activates the subwindow window.
If window is 0, any current active window is deactivated.
See also
activeSubWindow()
Definition at line 1844 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (!window) {
         d->activateWindow(0);
         return;
     }
     if (d->childWindows.isEmpty()) {
         qWarning("QMdiArea::setActiveSubWindow: workspace is empty");
         return;
     }
     if (d->childWindows.indexOf(window) == -1) {
         qWarning("QMdiArea::setActiveSubWindow: window is not inside workspace");
         return;
     }
     d->activateWindow(window);
 }
setBackground()
void QMdiArea::setBackground (const QBrush & background)
Definition at line 2079 of file qmdiarea.cpp.
Referenced by QMdiArea().
 {
     Q_D(QMdiArea);
     if (d->background != brush) {
         d->background = brush;
         d->viewport->setAttribute(Qt::WA_OpaquePaintEvent, brush.isOpaque());
         update();
     }
 }
setDocumentMode()
void QMdiArea::setDocumentMode (bool enabled)
Definition at line 2185 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (d->documentMode == enabled)
         return;
     d->documentMode = enabled;
     d->refreshTabBar();
 }
setOption()
void QMdiArea::setOption (AreaOption option, bool on = true)
If on is true, option is enabled on the MDI area; otherwise it is disabled.
See AreaOption for the effect of each option.
See also
AreaOption, testOption()
Definition at line 2123 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (on && !(d->options & option))
         d->options |= option;
     else if (!on && (d->options & option))
         d->options &= ~option;
 }
setTabPosition()
void QMdiArea::setTabPosition (QTabWidget::TabPosition position)
Definition at line 2301 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (d->tabPosition == position)
         return;
     d->tabPosition = position;
     d->refreshTabBar();
 }
setTabsClosable()
void QMdiArea::setTabsClosable (bool closable)
Definition at line 2213 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (d->tabsClosable == closable)
         return;
     d->tabsClosable = closable;
     d->refreshTabBar();
 }
setTabShape()
void QMdiArea::setTabShape (QTabWidget::TabShape shape)
Definition at line 2272 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (d->tabShape == shape)
         return;
     d->tabShape = shape;
     d->refreshTabBar();
 }
setTabsMovable()
void QMdiArea::setTabsMovable (bool movable)
Definition at line 2241 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (d->tabsMovable == movable)
         return;
     d->tabsMovable = movable;
     d->refreshTabBar();
 }
setupViewport
void QMdiArea::setupViewport (QWidget * viewport) protected slot
This slot is called by QAbstractScrollArea after setViewport() has been called.
Reimplement this function in a subclass of QMdiArea to initialize the new viewport before it is used.
See also
setViewport()
Definition at line 2722 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (viewport)
         viewport->setAttribute(Qt::WA_OpaquePaintEvent, d->background.isOpaque());
     foreach (QMdiSubWindow *child, d->childWindows) {
         if (!sanityCheck(child, "QMdiArea::setupViewport"))
             continue;
         child->setParent(viewport, child->windowFlags());
     }
 }
setViewMode()
void QMdiArea::setViewMode (ViewMode mode)
Definition at line 2160 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     d->setViewMode(mode);
 }
showEvent()
void QMdiArea::showEvent (QShowEvent * showEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2403 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (!d->pendingRearrangements.isEmpty()) {
         bool skipPlacement = false;
         foreach (Rearranger *rearranger, d->pendingRearrangements) {
             // If this is the case, we don't have to lay out pending child windows
             // since the rearranger will find a placement for them.
             if (rearranger->type() != Rearranger::IconTiler && !skipPlacement)
                 skipPlacement = true;
             d->rearrange(rearranger);
         }
         d->pendingRearrangements.clear();
         if (skipPlacement && !d->pendingPlacements.isEmpty())
             d->pendingPlacements.clear();
     }
     if (!d->pendingPlacements.isEmpty()) {
         foreach (QMdiSubWindow *window, d->pendingPlacements) {
             if (!window)
                 continue;
             if (!window->testAttribute(Qt::WA_Resized)) {
                 QSize newSize(window->sizeHint().boundedTo(viewport()->size()));
                 window->resize(newSize.expandedTo(qSmartMinSize(window)));
             }
             if (!window->testAttribute(Qt::WA_Moved) && !window->isMinimized()
                     && !window->isMaximized()) {
                 d->place(d->placer, window);
             }
         }
         d->pendingPlacements.clear();
     }
     d->setChildActivationEnabled(true);
     d->activateCurrentWindow();
     QAbstractScrollArea::showEvent(showEvent);
 }
sizeHint()
QSize QMdiArea::sizeHint () const virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1749 of file qmdiarea.cpp.
 {
     // Calculate a proper scale factor for QDesktopWidget::size().
     // This also takes into account that we can have nested workspaces.
     int nestedCount = 0;
     QWidget *widget = this->parentWidget();
     while (widget) {
         if (qobject_cast<QMdiArea *>(widget))
             ++nestedCount;
         widget = widget->parentWidget();
     }
     const int scaleFactor = 3 * (nestedCount + 1);
     QSize desktopSize = QApplication::desktop()->size();
     QSize size(desktopSize.width() * 2 / scaleFactor, desktopSize.height() * 2 / scaleFactor);
     foreach (QMdiSubWindow *child, d_func()->childWindows) {
         if (!sanityCheck(child, "QMdiArea::sizeHint"))
             continue;
         size = size.expandedTo(child->sizeHint());
     }
     return size.expandedTo(QApplication::globalStrut());
 }
subWindowActivated
QMdiArea::subWindowActivated (QMdiSubWindow * window) signal
QMdiArea emits this signal after window has been activated.
When window is 0, QMdiArea has just deactivated its last active window, and there are no active windows on the workspace.
See also
QMdiArea::activeSubWindow()
subWindowList()
QList< QMdiSubWindow * > QMdiArea::subWindowList (WindowOrder order = CreationOrder) const
Returns a list of all subwindows in the MDI area.
If order is CreationOrder (the default), the windows are sorted in the order in which they were inserted into the workspace. If order is StackingOrder, the windows are listed in their stacking order, with the topmost window as the last item in the list. If order is ActivationHistoryOrder, the windows are listed according to their recent activation history.
See also
WindowOrder
Definition at line 1888 of file qmdiarea.cpp.
Referenced by QAccessibleMdiArea::childCount(), QAccessibleMdiArea::indexOfChild(), mdiAreaNavigate(), QAccessibleMdiArea::navigate(), QAccessibleMdiSubWindow::navigate(), QAccessibleMdiArea::state(), and QMdiAreaTabBar::subWindowFromIndex().
 {
     Q_D(const QMdiArea);
     return d->subWindowList(order, false);
 }
tabPosition()
QTabWidget::TabPosition QMdiArea::tabPosition () const
Referenced by setTabShape().
tabsClosable()
bool QMdiArea::tabsClosable () const
Referenced by setDocumentMode().
tabShape()
QTabWidget::TabShape QMdiArea::tabShape () const
Referenced by setTabsMovable().
tabsMovable()
bool QMdiArea::tabsMovable () const
Referenced by setTabsClosable().
testOption()
bool QMdiArea::testOption (AreaOption option) const
Returns true if option is enabled; otherwise returns false.
See also
AreaOption, setOption()
Definition at line 2137 of file qmdiarea.cpp.
Referenced by viewportEvent().
 {
     return d_func()->options & option;
 }
tileSubWindows
void QMdiArea::tileSubWindows () slot
Arranges all child windows in a tile pattern.
See also
cascadeSubWindows()
Definition at line 2508 of file qmdiarea.cpp.
Referenced by event(), and resizeEvent().
 {
     Q_D(QMdiArea);
     if (!d->regularTiler)
         d->regularTiler = new RegularTiler;
     d->rearrange(d->regularTiler);
 }
timerEvent()
void QMdiArea::timerEvent (QTimerEvent * timerEvent) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 2379 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     if (timerEvent->timerId() == d->resizeTimerId) {
         killTimer(d->resizeTimerId);
         d->resizeTimerId = -1;
         d->arrangeMinimizedSubWindows();
     } else if (timerEvent->timerId() == d->tabToPreviousTimerId) {
         killTimer(d->tabToPreviousTimerId);
         d->tabToPreviousTimerId = -1;
         if (d->indexToHighlighted < 0)
             return;
 #ifndef QT_NO_RUBBERBAND
         // We're not doing a "quick switch" ... show rubber band.
         Q_ASSERT(d->indexToHighlighted < d->childWindows.size());
         Q_ASSERT(d->rubberBand);
         d->showRubberBandFor(d->childWindows.at(d->indexToHighlighted));
 #endif
     }
 }
viewMode()
ViewMode QMdiArea::viewMode () const
Referenced by testOption().
viewportEvent()
bool QMdiArea::viewportEvent (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2446 of file qmdiarea.cpp.
 {
     Q_D(QMdiArea);
     switch (event->type()) {
     case QEvent::ChildRemoved: {
         d->isSubWindowsTiled = false;
         QObject *removedChild = static_cast<QChildEvent *>(event)->child();
         for (int i = 0; i < d->childWindows.size(); ++i) {
             QObject *child = d->childWindows.at(i);
             if (!child || child == removedChild || !child->parent()
                     || child->parent() != viewport()) {
                 if (!testOption(DontMaximizeSubWindowOnActivation)) {
                     // In this case we can only rely on the child being a QObject
                     // (or 0), but let's try and see if we can get more information.
                     QWidget *mdiChild = qobject_cast<QWidget *>(removedChild);
                     if (mdiChild && mdiChild->isMaximized())
                         d->showActiveWindowMaximized = true;
                 }
                 d->disconnectSubWindow(child);
                 const bool activeRemoved = i == d->indicesToActivatedChildren.at(0);
                 d->childWindows.removeAt(i);
                 d->indicesToActivatedChildren.removeAll(i);
                 d->updateActiveWindow(i, activeRemoved);
                 d->arrangeMinimizedSubWindows();
                 break;
             }
         }
         d->updateScrollBars();
         break;
     }
     case QEvent::Destroy:
         d->isSubWindowsTiled = false;
         d->resetActiveWindow();
         d->childWindows.clear();
         qWarning("QMdiArea: Deleting the view port is undefined, use setViewport instead.");
         break;
     default:
         break;
     }
     return QAbstractScrollArea::viewportEvent(event);
 }
Properties
activationOrder
QMdiArea::WindowOrder QMdiArea::activationOrder private
the ordering criteria for subwindow lists
Since
4.4
This property specifies the ordering criteria for the list of subwindows returned by subWindowList(). By default, it is the window creation order.
See also
subWindowList()
Definition at line 64 of file qmdiarea.h.
background
QBrush QMdiArea::background private
the background brush for the workspace
This property sets the background brush for the workspace area itself. By default, it is a gray color, but can be any brush (e.g., colors, gradients or pixmaps).
Definition at line 63 of file qmdiarea.h.
documentMode
bool QMdiArea::documentMode private
whether the tab bar is set to document mode in tabbed view mode.
Since
4.5
Document mode is disabled by default.
See also
QTabBar::documentMode, setViewMode()
Definition at line 67 of file qmdiarea.h.
tabPosition
QTabWidget::TabPosition QMdiArea::tabPosition private
the position of the tabs in tabbed view mode.
Since
4.4
Possible values for this property are described by the QTabWidget::TabPosition enum.
See also
QTabWidget::TabPosition, setViewMode()
Definition at line 73 of file qmdiarea.h.
tabsClosable
bool QMdiArea::tabsClosable private
whether the tab bar should place close buttons on each tab in tabbed view mode.
Since
4.8
Tabs are not closable by default.
See also
QTabBar::tabsClosable, setViewMode()
Definition at line 68 of file qmdiarea.h.
tabShape
QTabWidget::TabShape QMdiArea::tabShape private
the shape of the tabs in tabbed view mode.
Since
4.4
Possible values for this property are QTabWidget::Rounded (default) or QTabWidget::Triangular.
See also
QTabWidget::TabShape, setViewMode()
Definition at line 72 of file qmdiarea.h.
tabsMovable
bool QMdiArea::tabsMovable private
whether the user can move the tabs within the tabbar area in tabbed view mode.
Since
4.8
Tabs are not movable by default.
See also
QTabBar::movable, setViewMode()
Definition at line 69 of file qmdiarea.h.
viewMode
QMdiArea::ViewMode QMdiArea::viewMode private
the way sub-windows are displayed in the QMdiArea.
Since
4.4
By default, the SubWindowView is used to display sub-windows.
See also
ViewMode, setTabShape(), setTabPosition()
Definition at line 65 of file qmdiarea.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qmdiarea.h
/src/gui/widgets/qmdiarea.cpp