Qt 4.8: QSvgStructureNode Class Reference
QSvgStructureNode Class Reference
#include <qsvgstructure_p.h>
Public Functions
void addChild (QSvgNode *child, const QString &id)
virtual QRectF bounds (QPainter *p, QSvgExtraStates &states) const
QSvgNode * previousSiblingNode (QSvgNode *n) const
QSvgStructureNode (QSvgNode *parent)
QList< QSvgNode * > renderers () const
QSvgNode * scopeNode (const QString &id) const
~QSvgStructureNode ()
Public Functions inherited from QSvgNode
void appendStyleProperty (QSvgStyleProperty *prop, const QString &id)
void applyStyle (QPainter *p, QSvgExtraStates &states) const
DisplayMode displayMode () const
QSvgTinyDocument * document () const
virtual void draw (QPainter *p, QSvgExtraStates &states)=0
bool isVisible () const
QString nodeId () const
QSvgNode * parent () const
QSvgNode (QSvgNode *parent=0)
const QStringList & requiredExtensions () const
const QStringList & requiredFeatures () const
const QStringList & requiredFonts () const
const QStringList & requiredFormats () const
const QStringList & requiredLanguages () const
void revertStyle (QPainter *p, QSvgExtraStates &states) const
void setDisplayMode (DisplayMode display)
void setNodeId (const QString &i)
void setRequiredExtensions (const QStringList &lst)
void setRequiredFeatures (const QStringList &lst)
void setRequiredFonts (const QStringList &lst)
void setRequiredFormats (const QStringList &lst)
void setRequiredLanguages (const QStringList &lst)
void setVisible (bool visible)
void setXmlClass (const QString &str)
QSvgStyleProperty * styleProperty (QSvgStyleProperty::Type type) const
QSvgFillStyleProperty * styleProperty (const QString &id) const
virtual QRectF transformedBounds (QPainter *p, QSvgExtraStates &states) const
QRectF transformedBounds () const
virtual Type type () const =0
QString xmlClass () const
virtual ~QSvgNode ()
Protected Variables
QList< QSvgStructureNode * > m_linkedScopes
QList< QSvgNode * > m_renderers
QHash< QString, QSvgNode * > m_scope
Protected Variables inherited from QSvgNode
QSvgStyle m_style
Additional Inherited Members
Public Types inherited from QSvgNode
enum DisplayMode {
InlineMode, BlockMode, ListItemMode, RunInMode,
CompactMode, MarkerMode, TableMode, InlineTableMode,
TableRowGroupMode, TableHeaderGroupMode, TableFooterGroupMode, TableRowMode,
TableColumnGroupMode, TableColumnMode, TableCellMode, TableCaptionMode,
NoneMode, InheritMode
}
enum Type {
DOC, G, DEFS, SWITCH,
ANIMATION, ARC, CIRCLE, ELLIPSE,
IMAGE, LINE, PATH, POLYGON,
POLYLINE, RECT, TEXT, TEXTAREA,
TSPAN, USE, VIDEO
}
Static Protected Functions inherited from QSvgNode
static qreal strokeWidth (QPainter *p)
Detailed Description
Definition at line 70 of file qsvgstructure_p.h.
Constructors and Destructors
QSvgStructureNode()
QSvgStructureNode::QSvgStructureNode (QSvgNode * parent)
Definition at line 86 of file qsvgstructure.cpp.
     :QSvgNode(parent)
 {
 }
~QSvgStructureNode()
QSvgStructureNode::~QSvgStructureNode ()
Definition at line 62 of file qsvgstructure.cpp.
 {
     qDeleteAll(m_renderers);
 }
Functions
addChild()
void QSvgStructureNode::addChild (QSvgNode * child, const QString & id)
Definition at line 98 of file qsvgstructure.cpp.
Referenced by QSvgHandler::startElement().
 {
     m_renderers.append(child);
     if (id.isEmpty())
         return; //we can't add it to scope without id
     QSvgTinyDocument *doc = document();
     if (doc)
         doc->addNamedNode(id, child);
 }
bounds()
QRectF QSvgStructureNode::bounds (QPainter * p, QSvgExtraStates & states) const virtual
Reimplemented from QSvgNode.
Definition at line 360 of file qsvgstructure.cpp.
 {
     QRectF bounds;
     foreach(QSvgNode *node, m_renderers)
         bounds |= node->transformedBounds(p, states);
     return bounds;
 }
previousSiblingNode()
QSvgNode * QSvgStructureNode::previousSiblingNode (QSvgNode * n) const
Definition at line 368 of file qsvgstructure.cpp.
Referenced by QSvgStyleSelector::previousSiblingNode().
 {
     QSvgNode *prev = 0;
     QList<QSvgNode*>::const_iterator itr = m_renderers.constBegin();
     for (; itr != m_renderers.constEnd(); ++itr) {
         QSvgNode *node = *itr;
         if (node == n)
             return prev;
         prev = node;
     }
     return prev;
 }
renderers()
QList<QSvgNode*> QSvgStructureNode::renderers () const inline
Definition at line 79 of file qsvgstructure_p.h.
Referenced by QSvgHandler::resolveGradients().
 { return m_renderers; }
scopeNode()
QSvgNode * QSvgStructureNode::scopeNode (const QString & id) const
Definition at line 92 of file qsvgstructure.cpp.
Referenced by QSvgTinyDocument::boundsOnElement(), createUseNode(), QSvgTinyDocument::draw(), QSvgTinyDocument::elementExists(), and QSvgTinyDocument::matrixForElement().
 {
     QSvgTinyDocument *doc = document();
     return doc ? doc->namedNode(id) : 0;
 }
Properties
m_linkedScopes
QList<QSvgStructureNode*> QSvgStructureNode::m_linkedScopes protected
Definition at line 83 of file qsvgstructure_p.h.
m_renderers
QList<QSvgNode*> QSvgStructureNode::m_renderers protected
Definition at line 81 of file qsvgstructure_p.h.
Referenced by addChild(), bounds(), QSvgG::draw(), QSvgTinyDocument::draw(), QSvgSwitch::draw(), previousSiblingNode(), renderers(), and ~QSvgStructureNode().
m_scope
QHash<QString, QSvgNode*> QSvgStructureNode::m_scope protected
Definition at line 82 of file qsvgstructure_p.h.
The documentation for this class was generated from the following files:
/src/svg/qsvgstructure_p.h
/src/svg/qsvgstructure.cpp