Qt 4.8: QFileSystemWatcherPrivate Class Reference
QFileSystemWatcherPrivate Class Reference
#include <qfilesystemwatcher_p.h>
Signals
static QFileSystemWatcherEngine * createNativeEngine ()
Public Functions
void _q_directoryChanged (const QString &path, bool removed)
void _q_fileChanged (const QString &path, bool removed)
void init ()
void initForcedEngine (const QString &)
void initPollerEngine ()
QFileSystemWatcherPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QStringList directories
QStringList files
QFileSystemWatcherEngine * forced
QFileSystemWatcherEngine * native
QFileSystemWatcherEngine * poller
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Detailed Description
Definition at line 98 of file qfilesystemwatcher_p.h.
Constructors and Destructors
QFileSystemWatcherPrivate()
QFileSystemWatcherPrivate::QFileSystemWatcherPrivate ()
Definition at line 274 of file qfilesystemwatcher.cpp.
     : native(0), poller(0), forced(0)
 {
 }
Functions
_q_directoryChanged()
void QFileSystemWatcherPrivate::_q_directoryChanged (const QString & path, bool removed)
Definition at line 353 of file qfilesystemwatcher.cpp.
Referenced by init(), initForcedEngine(), and initPollerEngine().
 {
     Q_Q(QFileSystemWatcher);
     if (!directories.contains(path)) {
         // perhaps the path was removed after a change was detected, but before we delivered the signal
         return;
     }
     if (removed)
         directories.removeAll(path);
     emit q->directoryChanged(path);
 }
_q_fileChanged()
void QFileSystemWatcherPrivate::_q_fileChanged (const QString & path, bool removed)
Definition at line 341 of file qfilesystemwatcher.cpp.
Referenced by init(), initForcedEngine(), and initPollerEngine().
 {
     Q_Q(QFileSystemWatcher);
     if (!files.contains(path)) {
         // the path was removed after a change was detected, but before we delivered the signal
         return;
     }
     if (removed)
         files.removeAll(path);
     emit q->fileChanged(path);
 }
createNativeEngine
QFileSystemWatcherEngine * QFileSystemWatcherPrivate::createNativeEngine () static private signal
Definition at line 249 of file qfilesystemwatcher.cpp.
Referenced by init().
 {
 #if defined(Q_OS_WIN)
     return new QWindowsFileSystemWatcherEngine;
 #elif defined(Q_OS_QNX) && !defined(QT_NO_INOTIFY)
     return QInotifyFileSystemWatcherEngine::create();
 #elif defined(Q_OS_LINUX)
     QFileSystemWatcherEngine *eng = QInotifyFileSystemWatcherEngine::create();
     if(!eng)
         eng = QDnotifyFileSystemWatcherEngine::create();
     return eng;
 #elif defined(Q_OS_FREEBSD) || defined(Q_OS_MAC)
 #  if 0 && defined(Q_OS_MAC) && (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
     if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_5)
         return QFSEventsFileSystemWatcherEngine::create();
     else
 #  endif
         return QKqueueFileSystemWatcherEngine::create();
 #elif defined(Q_OS_SYMBIAN)
     return new QSymbianFileSystemWatcherEngine;
 #else
     return 0;
 #endif
 }
init()
void QFileSystemWatcherPrivate::init ()
Definition at line 279 of file qfilesystemwatcher.cpp.
 {
     Q_Q(QFileSystemWatcher);
     native = createNativeEngine();
     if (native) {
         QObject::connect(native,
                          SIGNAL(fileChanged(QString,bool)),
                          q,
                          SLOT(_q_fileChanged(QString,bool)));
         QObject::connect(native,
                          SIGNAL(directoryChanged(QString,bool)),
                          q,
                          SLOT(_q_directoryChanged(QString,bool)));
     }
 }
initForcedEngine()
void QFileSystemWatcherPrivate::initForcedEngine (const QString & forceName)
Definition at line 295 of file qfilesystemwatcher.cpp.
 {
     if(forced)
         return;
     Q_Q(QFileSystemWatcher);
 #if defined(Q_OS_LINUX)
     if(forceName == QLatin1String("inotify")) {
         forced = QInotifyFileSystemWatcherEngine::create();
     } else if(forceName == QLatin1String("dnotify")) {
         forced = QDnotifyFileSystemWatcherEngine::create();
     }
 #else
     Q_UNUSED(forceName);
 #endif
     if(forced) {
         QObject::connect(forced,
                          SIGNAL(fileChanged(QString,bool)),
                          q,
                          SLOT(_q_fileChanged(QString,bool)));
         QObject::connect(forced,
                          SIGNAL(directoryChanged(QString,bool)),
                          q,
                          SLOT(_q_directoryChanged(QString,bool)));
     }
 }
initPollerEngine()
void QFileSystemWatcherPrivate::initPollerEngine ()
Definition at line 324 of file qfilesystemwatcher.cpp.
 {
     if(poller)
         return;
     Q_Q(QFileSystemWatcher);
     poller = new QPollingFileSystemWatcherEngine; // that was a mouthful
     QObject::connect(poller,
                      SIGNAL(fileChanged(QString,bool)),
                      q,
                      SLOT(_q_fileChanged(QString,bool)));
     QObject::connect(poller,
                      SIGNAL(directoryChanged(QString,bool)),
                      q,
                      SLOT(_q_directoryChanged(QString,bool)));
 }
Properties
directories
QStringList QFileSystemWatcherPrivate::directories
Definition at line 111 of file qfilesystemwatcher_p.h.
Referenced by _q_directoryChanged().
files
QStringList QFileSystemWatcherPrivate::files
Definition at line 111 of file qfilesystemwatcher_p.h.
Referenced by _q_fileChanged().
forced
QFileSystemWatcherEngine * QFileSystemWatcherPrivate::forced
Definition at line 110 of file qfilesystemwatcher_p.h.
Referenced by initForcedEngine().
native
QFileSystemWatcherEngine* QFileSystemWatcherPrivate::native
Definition at line 110 of file qfilesystemwatcher_p.h.
Referenced by init().
poller
QFileSystemWatcherEngine * QFileSystemWatcherPrivate::poller
Definition at line 110 of file qfilesystemwatcher_p.h.
Referenced by initPollerEngine().
The documentation for this class was generated from the following files:
/src/corelib/io/qfilesystemwatcher_p.h
/src/corelib/io/qfilesystemwatcher.cpp