Qt 4.8: QInterfaceFactory Class Reference
QInterfaceFactory Class Reference abstract
#include <qaccessible_mac_p.h>
Public Functions
virtual QAElement element (int id)=0
virtual QAElement element (const QAInterface &interface)
virtual QAInterface interface (UInt64 identifier)=0
virtual void registerChildren ()=0
virtual ~QInterfaceFactory ()
Detailed Description
Definition at line 419 of file qaccessible_mac_p.h.
Constructors and Destructors
~QInterfaceFactory()
virtual QInterfaceFactory::~QInterfaceFactory () inline virtual
Definition at line 429 of file qaccessible_mac_p.h.
 {}
Functions
element() [1/2]
virtual QAElement QInterfaceFactory::element (int id) pure virtual
Implemented in QItemViewInterfaceFactory, QMultipleHIObjectFactory, and QStandardInterfaceFactory.
Referenced by QAccessibleHierarchyManager::lookup().
element() [2/2]
virtual QAElement QInterfaceFactory::element (const QAInterface & interface) inline virtual
Reimplemented in QItemViewInterfaceFactory, and QStandardInterfaceFactory.
Definition at line 424 of file qaccessible_mac_p.h.
     {
         return element(interface.id());
     }
interface()
virtual QAInterface QInterfaceFactory::interface (UInt64 identifier) pure virtual
Implemented in QItemViewInterfaceFactory, QMultipleHIObjectFactory, and QStandardInterfaceFactory.
Referenced by QAccessibleHierarchyManager::lookup().
registerChildren()
virtual void QInterfaceFactory::registerChildren () pure virtual
Implemented in QItemViewInterfaceFactory, QMultipleHIObjectFactory, and QStandardInterfaceFactory.
Referenced by QAccessibleHierarchyManager::registerChildren().
The documentation for this class was generated from the following file:
/src/gui/accessible/qaccessible_mac_p.h