Qt 4.8: QDBusDemarshaller Class Reference
QDBusDemarshaller Class Reference
#include <qdbusargument_p.h>
Public Functions
bool atEnd ()
QDBusDemarshaller * beginArray ()
QDBusDemarshaller * beginCommon ()
QDBusDemarshaller * beginMap ()
QDBusDemarshaller * beginMapEntry ()
QDBusDemarshaller * beginStructure ()
void close ()
QString currentSignature ()
QDBusArgument::ElementType currentType ()
QDBusArgument duplicate ()
QDBusDemarshaller * endArray ()
QDBusDemarshaller * endCommon ()
QDBusDemarshaller * endMap ()
QDBusDemarshaller * endMapEntry ()
QDBusDemarshaller * endStructure ()
bool isCurrentTypeStringLike ()
QDBusDemarshaller (int flags)
bool toBool ()
uchar toByte ()
QByteArray toByteArray ()
double toDouble ()
int toInt ()
qlonglong toLongLong ()
QDBusObjectPath toObjectPath ()
short toShort ()
QDBusSignature toSignature ()
QString toString ()
QStringList toStringList ()
uint toUInt ()
qulonglong toULongLong ()
QDBusUnixFileDescriptor toUnixFileDescriptor ()
ushort toUShort ()
QDBusVariant toVariant ()
QVariant toVariantInternal ()
~QDBusDemarshaller ()
Public Functions inherited from QDBusArgumentPrivate
QDBusDemarshaller * demarshaller ()
QDBusMarshaller * marshaller ()
QDBusArgumentPrivate (int flags=0)
~QDBusArgumentPrivate ()
Public Variables
DBusMessageIter iterator
QDBusDemarshaller * parent
Public Variables inherited from QDBusArgumentPrivate
int capabilities
enum QDBusArgumentPrivate::Direction direction
DBusMessage * message
QAtomicInt ref
Private Functions
QByteArray toByteArrayUnchecked ()
QDBusObjectPath toObjectPathUnchecked ()
QDBusSignature toSignatureUnchecked ()
QStringList toStringListUnchecked ()
QString toStringUnchecked ()
Additional Inherited Members
Public Types inherited from QDBusArgumentPrivate
enum Direction { Marshalling, Demarshalling }
Static Public Functions inherited from QDBusArgumentPrivate
static bool checkRead (QDBusArgumentPrivate *d)
static bool checkReadAndDetach (QDBusArgumentPrivate *&d)
static bool checkWrite (QDBusArgumentPrivate *&d)
static QDBusArgument create (QDBusArgumentPrivate *d)
static QByteArray createSignature (int id)
static QDBusArgumentPrivate * d (QDBusArgument &q)
Detailed Description
Definition at line 161 of file qdbusargument_p.h.
Constructors and Destructors
QDBusDemarshaller()
QDBusDemarshaller::QDBusDemarshaller (int flags) inline
Definition at line 164 of file qdbusargument_p.h.
Referenced by beginCommon(), and duplicate().
                                         : QDBusArgumentPrivate(flags), parent(0)
     { direction = Demarshalling; }
~QDBusDemarshaller()
QDBusDemarshaller::~QDBusDemarshaller ()
Definition at line 75 of file qdbusdemarshaller.cpp.
 {
 }
Functions
atEnd()
bool QDBusDemarshaller::atEnd ()
Definition at line 362 of file qdbusdemarshaller.cpp.
Referenced by QDBusMarshaller::appendCrossMarshalling(), QDBusArgument::atEnd(), QDBusMessagePrivate::fromDBusMessage(), and toStringListUnchecked().
 {
     // dbus_message_iter_has_next is broken if the list has one single element
     return q_dbus_message_iter_get_arg_type(&iterator) == DBUS_TYPE_INVALID;
 }
beginArray()
QDBusDemarshaller * QDBusDemarshaller::beginArray () inline
Definition at line 373 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::beginArray().
 {
     return beginCommon();
 }
beginCommon()
QDBusDemarshaller * QDBusDemarshaller::beginCommon ()
Definition at line 388 of file qdbusdemarshaller.cpp.
Referenced by QDBusMarshaller::appendCrossMarshalling(), beginArray(), beginMap(), beginMapEntry(), and beginStructure().
 {
     QDBusDemarshaller *d = new QDBusDemarshaller(capabilities);
     d->parent = this;
     d->message = q_dbus_message_ref(message);
     // recurse
     q_dbus_message_iter_recurse(&iterator, &d->iterator);
     q_dbus_message_iter_next(&iterator);
     return d;
 }
beginMap()
QDBusDemarshaller * QDBusDemarshaller::beginMap () inline
Definition at line 378 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::beginMap().
 {
     return beginCommon();
 }
beginMapEntry()
QDBusDemarshaller * QDBusDemarshaller::beginMapEntry () inline
Definition at line 383 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::beginMapEntry().
 {
     return beginCommon();
 }
beginStructure()
QDBusDemarshaller * QDBusDemarshaller::beginStructure () inline
Definition at line 368 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::beginStructure().
 {
     return beginCommon();
 }
close()
void QDBusDemarshaller::close () inline
Definition at line 198 of file qdbusargument_p.h.
 { }
currentSignature()
QString QDBusDemarshaller::currentSignature () inline
Definition at line 79 of file qdbusdemarshaller.cpp.
Referenced by QDBusMarshaller::appendCrossMarshalling(), and QDBusArgument::currentSignature().
 {
     char *sig = q_dbus_message_iter_get_signature(&iterator);
     QString retval = QString::fromUtf8(sig);
     q_dbus_free(sig);
     return retval;
 }
currentType()
QDBusArgument::ElementType QDBusDemarshaller::currentType ()
Definition at line 189 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::currentType().
 {
     switch (q_dbus_message_iter_get_arg_type(&iterator)) {
     case DBUS_TYPE_BYTE:
     case DBUS_TYPE_INT16:
     case DBUS_TYPE_UINT16:
     case DBUS_TYPE_INT32:
     case DBUS_TYPE_UINT32:
     case DBUS_TYPE_INT64:
     case DBUS_TYPE_UINT64:
     case DBUS_TYPE_BOOLEAN:
     case DBUS_TYPE_DOUBLE:
     case DBUS_TYPE_STRING:
     case DBUS_TYPE_OBJECT_PATH:
     case DBUS_TYPE_SIGNATURE:
         return QDBusArgument::BasicType;
     case DBUS_TYPE_VARIANT:
         return QDBusArgument::VariantType;
     case DBUS_TYPE_ARRAY:
         switch (q_dbus_message_iter_get_element_type(&iterator)) {
         case DBUS_TYPE_BYTE:
         case DBUS_TYPE_STRING:
             // QByteArray and QStringList
             return QDBusArgument::BasicType;
         case DBUS_TYPE_DICT_ENTRY:
             return QDBusArgument::MapType;
         default:
             return QDBusArgument::ArrayType;
         }
     case DBUS_TYPE_STRUCT:
         return QDBusArgument::StructureType;
     case DBUS_TYPE_DICT_ENTRY:
         return QDBusArgument::MapEntryType;
     case DBUS_TYPE_UNIX_FD:
         return capabilities & QDBusConnection::UnixFileDescriptorPassing ?
                     QDBusArgument::BasicType : QDBusArgument::UnknownType;
     case DBUS_TYPE_INVALID:
         return QDBusArgument::UnknownType;
 //    default:
 //        qWarning("QDBusDemarshaller: Found unknown D-Bus type %d '%c'",
 //                 q_dbus_message_iter_get_arg_type(&iterator),
 //                 q_dbus_message_iter_get_arg_type(&iterator));
     }
     return QDBusArgument::UnknownType;
 }
duplicate()
QDBusArgument QDBusDemarshaller::duplicate ()
Definition at line 427 of file qdbusdemarshaller.cpp.
Referenced by toVariantInternal().
 {
     QDBusDemarshaller *d = new QDBusDemarshaller(capabilities);
     d->iterator = iterator;
     d->message = q_dbus_message_ref(message);
     q_dbus_message_iter_next(&iterator);
     return QDBusArgumentPrivate::create(d);
 }
endArray()
QDBusDemarshaller * QDBusDemarshaller::endArray () inline
Definition at line 405 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::endArray().
 {
     return endCommon();
 }
endCommon()
QDBusDemarshaller * QDBusDemarshaller::endCommon ()
Definition at line 420 of file qdbusdemarshaller.cpp.
Referenced by endArray(), endMap(), endMapEntry(), and endStructure().
 {
     QDBusDemarshaller *retval = parent;
     delete this;
     return retval;
 }
endMap()
QDBusDemarshaller * QDBusDemarshaller::endMap () inline
Definition at line 410 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::endMap().
 {
     return endCommon();
 }
endMapEntry()
QDBusDemarshaller * QDBusDemarshaller::endMapEntry () inline
Definition at line 415 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::endMapEntry().
 {
     return endCommon();
 }
endStructure()
QDBusDemarshaller * QDBusDemarshaller::endStructure () inline
Definition at line 400 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::endStructure().
 {
     return endCommon();
 }
isCurrentTypeStringLike()
bool QDBusDemarshaller::isCurrentTypeStringLike ()
Definition at line 307 of file qdbusdemarshaller.cpp.
Referenced by toObjectPath(), toSignature(), and toString().
 {
     const int type = q_dbus_message_iter_get_arg_type(&iterator);
     switch (type) {
     case DBUS_TYPE_STRING:  //FALLTHROUGH
     case DBUS_TYPE_OBJECT_PATH:  //FALLTHROUGH
     case DBUS_TYPE_SIGNATURE:
         return true;
     default:
         return false;
     }
 }
toBool()
bool QDBusDemarshaller::toBool () inline
Definition at line 93 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>(), and toVariantInternal().
 {
     return bool(qIterGet<dbus_bool_t>(&iterator));
 }
toByte()
uchar QDBusDemarshaller::toByte () inline
Definition at line 88 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>(), and toVariantInternal().
 {
     return qIterGet<uchar>(&iterator);
 }
toByteArray()
QByteArray QDBusDemarshaller::toByteArray ()
Definition at line 353 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>().
 {
     if (q_dbus_message_iter_get_arg_type(&iterator) == DBUS_TYPE_ARRAY
             && q_dbus_message_iter_get_element_type(&iterator) == DBUS_TYPE_BYTE) {
         return toByteArrayUnchecked();
     }
     return QByteArray();
 }
toByteArrayUnchecked()
QByteArray QDBusDemarshaller::toByteArrayUnchecked () private
Definition at line 342 of file qdbusdemarshaller.cpp.
Referenced by toByteArray(), and toVariantInternal().
 {
     DBusMessageIter sub;
     q_dbus_message_iter_recurse(&iterator, &sub);
     q_dbus_message_iter_next(&iterator);
     int len;
     char* data;
     q_dbus_message_iter_get_fixed_array(&sub,&data,&len);
     return QByteArray(data,len);
 }
toDouble()
double QDBusDemarshaller::toDouble () inline
Definition at line 128 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>(), and toVariantInternal().
 {
     return qIterGet<double>(&iterator);
 }
toInt()
int QDBusDemarshaller::toInt () inline
Definition at line 108 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>(), and toVariantInternal().
 {
     return qIterGet<dbus_int32_t>(&iterator);
 }
toLongLong()
qlonglong QDBusDemarshaller::toLongLong () inline
Definition at line 118 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>(), and toVariantInternal().
 {
     return qIterGet<qlonglong>(&iterator);
 }
toObjectPath()
QDBusObjectPath QDBusDemarshaller::toObjectPath () inline
Definition at line 151 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>().
 {
     if (isCurrentTypeStringLike())
         return toObjectPathUnchecked();
     else
         return QDBusObjectPath();
 }
toObjectPathUnchecked()
QDBusObjectPath QDBusDemarshaller::toObjectPathUnchecked () inline private
Definition at line 146 of file qdbusdemarshaller.cpp.
Referenced by toObjectPath(), and toVariantInternal().
  {
      return QDBusObjectPath(QString::fromUtf8(qIterGet<char *>(&iterator)));
  }
toShort()
short QDBusDemarshaller::toShort () inline
Definition at line 103 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>(), and toVariantInternal().
 {
     return qIterGet<dbus_int16_t>(&iterator);
 }
toSignature()
QDBusSignature QDBusDemarshaller::toSignature () inline
Definition at line 164 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>().
 {
     if (isCurrentTypeStringLike())
         return toSignatureUnchecked();
     else
         return QDBusSignature();
 }
toSignatureUnchecked()
QDBusSignature QDBusDemarshaller::toSignatureUnchecked () inline private
Definition at line 159 of file qdbusdemarshaller.cpp.
Referenced by toSignature(), and toVariantInternal().
  {
      return QDBusSignature(QString::fromUtf8(qIterGet<char *>(&iterator)));
  }
toString()
QString QDBusDemarshaller::toString () inline
Definition at line 138 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>().
 {
     if (isCurrentTypeStringLike())
         return toStringUnchecked();
     else
         return QString();
 }
toStringList()
QStringList QDBusDemarshaller::toStringList ()
Definition at line 333 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>().
 {
     if (q_dbus_message_iter_get_arg_type(&iterator) == DBUS_TYPE_ARRAY
             && q_dbus_message_iter_get_element_type(&iterator) == DBUS_TYPE_STRING)
         return toStringListUnchecked();
     else
         return QStringList();
 }
toStringListUnchecked()
QStringList QDBusDemarshaller::toStringListUnchecked () private
Definition at line 320 of file qdbusdemarshaller.cpp.
Referenced by toStringList(), and toVariantInternal().
 {
     QStringList list;
     QDBusDemarshaller sub(capabilities);
     q_dbus_message_iter_recurse(&iterator, &sub.iterator);
     q_dbus_message_iter_next(&iterator);
     while (!sub.atEnd())
         list.append(sub.toStringUnchecked());
     return list;
 }
toStringUnchecked()
QString QDBusDemarshaller::toStringUnchecked () inline private
Definition at line 133 of file qdbusdemarshaller.cpp.
Referenced by toString(), toStringListUnchecked(), and toVariantInternal().
 {
     return QString::fromUtf8(qIterGet<char *>(&iterator));
 }
toUInt()
uint QDBusDemarshaller::toUInt () inline
Definition at line 113 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>(), and toVariantInternal().
 {
     return qIterGet<dbus_uint32_t>(&iterator);
 }
toULongLong()
qulonglong QDBusDemarshaller::toULongLong () inline
Definition at line 123 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>(), and toVariantInternal().
 {
     return qIterGet<qulonglong>(&iterator);
 }
toUnixFileDescriptor()
QDBusUnixFileDescriptor QDBusDemarshaller::toUnixFileDescriptor () inline
Definition at line 172 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>(), and toVariantInternal().
 {
     QDBusUnixFileDescriptor fd;
     fd.giveFileDescriptor(qIterGet<dbus_int32_t>(&iterator));
     return fd;
 }
toUShort()
ushort QDBusDemarshaller::toUShort () inline
Definition at line 98 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>(), and toVariantInternal().
 {
     return qIterGet<dbus_uint16_t>(&iterator);
 }
toVariant()
QDBusVariant QDBusDemarshaller::toVariant () inline
Definition at line 179 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::operator>>(), and toVariantInternal().
 {
     QDBusDemarshaller sub(capabilities);
     sub.message = q_dbus_message_ref(message);
     q_dbus_message_iter_recurse(&iterator, &sub.iterator);
     q_dbus_message_iter_next(&iterator);
     return QDBusVariant( sub.toVariantInternal() );
 }
toVariantInternal()
QVariant QDBusDemarshaller::toVariantInternal ()
Definition at line 241 of file qdbusdemarshaller.cpp.
Referenced by QDBusArgument::asVariant(), QDBusMessagePrivate::fromDBusMessage(), and toVariant().
 {
     switch (q_dbus_message_iter_get_arg_type(&iterator)) {
     case DBUS_TYPE_BYTE:
         return QVariant::fromValue(toByte());
     case DBUS_TYPE_INT16:
     return QVariant::fromValue(toShort());
     case DBUS_TYPE_UINT16:
     return QVariant::fromValue(toUShort());
     case DBUS_TYPE_INT32:
         return toInt();
     case DBUS_TYPE_UINT32:
         return toUInt();
     case DBUS_TYPE_DOUBLE:
         return toDouble();
     case DBUS_TYPE_BOOLEAN:
         return toBool();
     case DBUS_TYPE_INT64:
         return toLongLong();
     case DBUS_TYPE_UINT64:
         return toULongLong();
     case DBUS_TYPE_STRING:
         return toStringUnchecked();
     case DBUS_TYPE_OBJECT_PATH:
         return QVariant::fromValue(toObjectPathUnchecked());
     case DBUS_TYPE_SIGNATURE:
         return QVariant::fromValue(toSignatureUnchecked());
     case DBUS_TYPE_VARIANT:
         return QVariant::fromValue(toVariant());
     case DBUS_TYPE_ARRAY:
         switch (q_dbus_message_iter_get_element_type(&iterator)) {
         case DBUS_TYPE_BYTE:
             // QByteArray
             return toByteArrayUnchecked();
         case DBUS_TYPE_STRING:
             return toStringListUnchecked();
         case DBUS_TYPE_DICT_ENTRY:
             return QVariant::fromValue(duplicate());
         default:
             return QVariant::fromValue(duplicate());
         }
     case DBUS_TYPE_STRUCT:
         return QVariant::fromValue(duplicate());
     case DBUS_TYPE_UNIX_FD:
         if (capabilities & QDBusConnection::UnixFileDescriptorPassing)
             return qVariantFromValue(toUnixFileDescriptor());
         // fall through
     default:
 //        qWarning("QDBusDemarshaller: Found unknown D-Bus type %d '%c'",
 //                 q_dbus_message_iter_get_arg_type(&iterator),
 //                 q_dbus_message_iter_get_arg_type(&iterator));
         char *ptr = 0;
         ptr += q_dbus_message_iter_get_arg_type(&iterator);
         q_dbus_message_iter_next(&iterator);
         // I hope you never dereference this pointer!
         return QVariant::fromValue<void *>(ptr);
         break;
     };
 }
Properties
iterator
DBusMessageIter QDBusDemarshaller::iterator
Definition at line 207 of file qdbusargument_p.h.
Referenced by QDBusMarshaller::appendCrossMarshalling(), QDBusMarshaller::appendVariantInternal(), atEnd(), beginCommon(), QDBusArgumentPrivate::checkReadAndDetach(), currentSignature(), currentType(), duplicate(), QDBusMessagePrivate::fromDBusMessage(), isCurrentTypeStringLike(), toBool(), toByte(), toByteArray(), toByteArrayUnchecked(), toDouble(), toInt(), toLongLong(), toObjectPathUnchecked(), toShort(), toSignatureUnchecked(), toStringList(), toStringListUnchecked(), toStringUnchecked(), toUInt(), toULongLong(), toUnixFileDescriptor(), toUShort(), toVariant(), and toVariantInternal().
parent
QDBusDemarshaller* QDBusDemarshaller::parent
Definition at line 208 of file qdbusargument_p.h.
Referenced by beginCommon(), and endCommon().
The documentation for this class was generated from the following files:
/src/dbus/qdbusargument_p.h
/src/dbus/qdbusdemarshaller.cpp