Qt 4.8: QDBusConnectionInterface Class Reference
QDBusConnectionInterface Class Reference
The QDBusConnectionInterface class provides access to the D-Bus bus daemon service.
#include <qdbusconnectioninterface.h>
Public Types
enum RegisterServiceReply { ServiceNotRegistered = 0, ServiceRegistered, ServiceQueued }
The possible return values from registerService():
enum ServiceQueueOptions { DontQueueService, QueueService, ReplaceExistingService }
Flags for determining how a service registration should behave, in case the service name is already registered.
enum ServiceReplacementOptions { DontAllowReplacement, AllowReplacement }
Flags for determining if the D-Bus server should allow another application to replace a name that this application has registered with the ReplaceExistingService option.
Public Slots
QDBusReply< bool > isServiceRegistered (const QString &serviceName) const
Returns true if the service name serviceName has is currently registered.
QDBusReply< QStringList > registeredServiceNames () const
QDBusReply< QDBusConnectionInterface::RegisterServiceReply > registerService (const QString &serviceName, ServiceQueueOptions qoption=DontQueueService, ServiceReplacementOptions roption=DontAllowReplacement)
Requests to register the service name serviceName on the bus.
QDBusReply< QString > serviceOwner (const QString &name) const
Returns the unique connection name of the primary owner of the name name.
QDBusReply< uint > servicePid (const QString &serviceName) const
Returns the Unix Process ID (PID) for the process currently holding the bus service serviceName.
QDBusReply< uint > serviceUid (const QString &serviceName) const
Returns the Unix User ID (UID) for the process currently holding the bus service serviceName.
QDBusReply< void > startService (const QString &name)
Requests that the bus start the service given by the name name.
QDBusReply< bool > unregisterService (const QString &serviceName)
Releases the claim on the bus service name serviceName, that had been previously registered with registerService().
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void callWithCallbackFailed (const QDBusError &error, const QDBusMessage &call)
This signal is emitted when there is an error during a QDBusConnection::callWithCallback().
void serviceOwnerChanged (const QString &name, const QString &oldOwner, const QString &newOwner)
This signal is emitted by the D-Bus server whenever a service ownership change happens in the bus, including apparition and disparition of names.
void serviceRegistered (const QString &service)
This signal is emitted by the D-Bus server when the bus service name (unique connection name or well-known service name) given by serviceName is acquired by this application.
void serviceUnregistered (const QString &service)
This signal is emitted by the D-Bus server when this application loses ownership of the bus service name given by serviceName.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Private Functions
QDBusConnectionInterface (const QDBusConnection &connection, QObject *parent)
~QDBusConnectionInterface ()
Static Private Functions
static const char * staticInterfaceName ()
Properties
QDBusReply< QStringList > registeredServiceNames
holds the registered service names
Friends
class QDBusConnectionPrivate
Additional Inherited Members
Public Functions inherited from QDBusAbstractInterface
QDBusPendingCall asyncCall (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusPendingCall asyncCallWithArgumentList (const QString &method, const QList< QVariant > &args)
Places a call to the remote method specified by method on this interface, using args as arguments.
QDBusMessage call (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusMessage call (QDBus::CallMode mode, const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusMessage callWithArgumentList (QDBus::CallMode mode, const QString &method, const QList< QVariant > &args)
Places a call to the remote method specified by method on this interface, using args as arguments.
bool callWithCallback (const QString &method, const QList< QVariant > &args, QObject *receiver, const char *member, const char *errorSlot)
Places a call to the remote method specified by method on this interface, using args as arguments.
bool callWithCallback (const QString &method, const QList< QVariant > &args, QObject *receiver, const char *member)
This function is deprecated.
QDBusConnection connection () const
Returns the connection this interface is assocated with.
QString interface () const
Returns the name of this interface.
bool isValid () const
Returns true if this is a valid reference to a remote object.
QDBusError lastError () const
Returns the error the last operation produced, or an invalid error if the last operation did not produce an error.
QString path () const
Returns the object path that this interface is associated with.
QString service () const
Returns the name of the service this interface is associated with.
void setTimeout (int timeout)
Sets the timeout in milliseconds for all future DBus calls to timeout.
int timeout () const
Returns the current value of the timeout in milliseconds.
virtual ~QDBusAbstractInterface ()
Releases this object's resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QDBusAbstractInterface
void connectNotify (const char *signal)
Catch signal connections.
void disconnectNotify (const char *signal)
Catch signal disconnections.
QDBusMessage internalConstCall (QDBus::CallMode mode, const QString &method, const QList< QVariant > &args=QList< QVariant >()) const
QVariant internalPropGet (const char *propname) const
Get the value of the property propname.
void internalPropSet (const char *propname, const QVariant &value)
Set the value of the property propname to value.
QDBusAbstractInterface (const QString &service, const QString &path, const char *interface, const QDBusConnection &connection, QObject *parent)
This is the constructor called from static classes derived from QDBusAbstractInterface (i.
QDBusAbstractInterface (QDBusAbstractInterfacePrivate &, QObject *parent)
This is the constructor called from QDBusInterface::QDBusInterface.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QDBusConnectionInterface class provides access to the D-Bus bus daemon service.
Attention
Module: QtDBus
Since
4.2
The D-Bus bus server daemon provides one special interface org.freedesktop.DBus that allows clients to access certain properties of the bus, such as the current list of clients connected. The QDBusConnectionInterface class provides access to that interface.
The most common uses of this class are to register and unregister service names on the bus using the registerService() and unregisterService() functions, query about existing names using the isServiceRegistered(), registeredServiceNames() and serviceOwner() functions, and to receive notification that a client has registered or de-registered through the serviceRegistered(), serviceUnregistered() and serviceOwnerChanged() signals.
Definition at line 65 of file qdbusconnectioninterface.h.
Enumerations
RegisterServiceReply
enum QDBusConnectionInterface::RegisterServiceReply
The possible return values from registerService():
ServiceNotRegistered The call failed and the service name was not registered.
ServiceRegistered The caller is now the owner of the service name.
ServiceQueued The caller specified the QueueService flag and the service was already registered, so we are in queue.
The serviceRegistered() signal will be emitted when the service is acquired by this application.
Enumerator
ServiceNotRegistered
ServiceRegistered
ServiceQueued
Definition at line 87 of file qdbusconnectioninterface.h.
{
         ServiceNotRegistered = 0,
         ServiceRegistered,
         ServiceQueued
     };
ServiceQueueOptions
enum QDBusConnectionInterface::ServiceQueueOptions
Flags for determining how a service registration should behave, in case the service name is already registered.
DontQueueService If an application requests a name that is already owned, no queueing will be performed. The registeredService() call will simply fail. This is the default.
QueueService Attempts to register the requested service, but do not try to replace it if another application already has it registered. Instead, simply put this application in queue, until it is given up. The serviceRegistered() signal will be emitted when that happens.
ReplaceExistingService If another application already has the service name registered, attempt to replace it.
See also
ServiceReplacementOptions
Enumerator
DontQueueService
QueueService
ReplaceExistingService
Definition at line 78 of file qdbusconnectioninterface.h.
{
         DontQueueService,
         QueueService,
         ReplaceExistingService
     };
ServiceReplacementOptions
enum QDBusConnectionInterface::ServiceReplacementOptions
Flags for determining if the D-Bus server should allow another application to replace a name that this application has registered with the ReplaceExistingService option.
The possible values are:
DontAllowReplacement Do not allow another application to replace us. The service must be explicitly unregistered with unregisterService() for another application to acquire it. This is the default.
AllowReplacement Allow other applications to replace us with the ReplaceExistingService option to registerService() without intervention. If that happens, the serviceUnregistered() signal will be emitted.
See also
ServiceQueueOptions
Enumerator
DontAllowReplacement
AllowReplacement
Definition at line 83 of file qdbusconnectioninterface.h.
{
         DontAllowReplacement,
         AllowReplacement
     };
Constructors and Destructors
QDBusConnectionInterface()
QDBusConnectionInterface::QDBusConnectionInterface (const QDBusConnection & connection, QObject * parent) explicit private
Warning
This function is not part of the public interface.
Definition at line 174 of file qdbusconnectioninterface.cpp.
     : QDBusAbstractInterface(QLatin1String(DBUS_SERVICE_DBUS),
                              QLatin1String(DBUS_PATH_DBUS),
                              DBUS_INTERFACE_DBUS, connection, parent)
 {
     connect(this, SIGNAL(NameAcquired(QString)), this, SIGNAL(serviceRegistered(QString)));
     connect(this, SIGNAL(NameLost(QString)), this, SIGNAL(serviceUnregistered(QString)));
     connect(this, SIGNAL(NameOwnerChanged(QString,QString,QString)),
             this, SIGNAL(serviceOwnerChanged(QString,QString,QString)));
 }
~QDBusConnectionInterface()
QDBusConnectionInterface::~QDBusConnectionInterface () private
Warning
This function is not part of the public interface.
Definition at line 189 of file qdbusconnectioninterface.cpp.
 {
 }
Functions
callWithCallbackFailed
void QDBusConnectionInterface::callWithCallbackFailed (const QDBusError & error, const QDBusMessage & call) signal
This signal is emitted when there is an error during a QDBusConnection::callWithCallback().
error specifies the error. call is the message that couldn't be delivered.
See also
QDBusConnection::callWithCallback()
isServiceRegistered
QDBusReply< bool > QDBusConnectionInterface::isServiceRegistered (const QString & serviceName) const slot
Returns true if the service name serviceName has is currently registered.
Definition at line 221 of file qdbusconnectioninterface.cpp.
 {
     return internalConstCall(QDBus::AutoDetect, QLatin1String("NameHasOwner"),
                              QList<QVariant>() << serviceName);
 }
registeredServiceNames
QDBusReply<QStringList> QDBusConnectionInterface::registeredServiceNames () const slot
Referenced by serviceOwner().
registerService
QDBusReply< QDBusConnectionInterface::RegisterServiceReply > QDBusConnectionInterface::registerService (const QString & serviceName, ServiceQueueOptions qoption = DontQueueService, ServiceReplacementOptions roption = DontAllowReplacement) slot
Requests to register the service name serviceName on the bus.
The qoption flag specifies how the D-Bus server should behave if serviceName is already registered. The roption flag specifies if the server should allow another application to replace our registered name.
If the service registration succeeds, the serviceRegistered() signal will be emitted. If we are placed in queue, the signal will be emitted when we obtain the name. If roption is AllowReplacement, the serviceUnregistered() signal will be emitted if another application replaces this one.
See also
unregisterService()
Definition at line 271 of file qdbusconnectioninterface.cpp.
 {
     // reconstruct the low-level flags
     uint flags = 0;
     switch (qoption) {
     case DontQueueService:
         flags = DBUS_NAME_FLAG_DO_NOT_QUEUE;
         break;
     case QueueService:
         flags = 0;
         break;
     case ReplaceExistingService:
         flags = DBUS_NAME_FLAG_DO_NOT_QUEUE | DBUS_NAME_FLAG_REPLACE_EXISTING;
         break;
     }
     switch (roption) {
     case DontAllowReplacement:
         break;
     case AllowReplacement:
         flags |= DBUS_NAME_FLAG_ALLOW_REPLACEMENT;
         break;
     }
     QDBusMessage reply = call(QLatin1String("RequestName"), serviceName, flags);
 //    qDebug() << "QDBusConnectionInterface::registerService" << serviceName << "Reply:" << reply;
     // convert the low-level flags to something that we can use
     if (reply.type() == QDBusMessage::ReplyMessage) {
         uint code = 0;
         switch (reply.arguments().at(0).toUInt()) {
         case DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER:
         case DBUS_REQUEST_NAME_REPLY_ALREADY_OWNER:
             code = uint(ServiceRegistered);
             break;
         case DBUS_REQUEST_NAME_REPLY_EXISTS:
             code = uint(ServiceNotRegistered);
             break;
         case DBUS_REQUEST_NAME_REPLY_IN_QUEUE:
             code = uint(ServiceQueued);
             break;
         }
         reply.setArguments(QVariantList() << code);
     }
     return reply;
 }
serviceOwner
QDBusReply< QString > QDBusConnectionInterface::serviceOwner (const QString & name) const slot
Returns the unique connection name of the primary owner of the name name.
If the requested name doesn't have an owner, returns a org.freedesktop.DBus.Error.NameHasNoOwner error.
Definition at line 198 of file qdbusconnectioninterface.cpp.
 {
     return internalConstCall(QDBus::AutoDetect, QLatin1String("GetNameOwner"), QList<QVariant>() << name);
 }
serviceOwnerChanged
QDBusConnectionInterface::serviceOwnerChanged (const QString & name, const QString & oldOwner, const QString & newOwner) signal
This signal is emitted by the D-Bus server whenever a service ownership change happens in the bus, including apparition and disparition of names.
This signal means the application oldOwner lost ownership of bus name name to application newOwner. If oldOwner is an empty string, it means the name name has just been created; if newOwner is empty, the name name has no current owner and is no longer available.
Note
connecting to this signal will make the application listen for and receive every single service ownership change on the bus. Depending on how many services are running, this make the application be activated to receive more signals than it needs. To avoid this problem, use the QDBusServiceWatcher class, which can listen for specific changes.
Referenced by QDBusConnectionInterface(), and unregisterService().
servicePid
QDBusReply< uint > QDBusConnectionInterface::servicePid (const QString & serviceName) const slot
Returns the Unix Process ID (PID) for the process currently holding the bus service serviceName.
Definition at line 231 of file qdbusconnectioninterface.cpp.
 {
     return internalConstCall(QDBus::AutoDetect, QLatin1String("GetConnectionUnixProcessID"),
                              QList<QVariant>() << serviceName);
 }
serviceRegistered
QDBusConnectionInterface::serviceRegistered (const QString & serviceName) signal
This signal is emitted by the D-Bus server when the bus service name (unique connection name or well-known service name) given by serviceName is acquired by this application.
Acquisition happens after this application has requested a name using registerService().
Referenced by QDBusConnectionInterface(), and unregisterService().
serviceUid
QDBusReply< uint > QDBusConnectionInterface::serviceUid (const QString & serviceName) const slot
Returns the Unix User ID (UID) for the process currently holding the bus service serviceName.
Definition at line 241 of file qdbusconnectioninterface.cpp.
 {
     return internalConstCall(QDBus::AutoDetect, QLatin1String("GetConnectionUnixUser"),
                              QList<QVariant>() << serviceName);
 }
serviceUnregistered
QDBusConnectionInterface::serviceUnregistered (const QString & service) signal
This signal is emitted by the D-Bus server when this application loses ownership of the bus service name given by serviceName.
Referenced by QDBusConnectionInterface(), and unregisterService().
startService
QDBusReply< void > QDBusConnectionInterface::startService (const QString & name) slot
Requests that the bus start the service given by the name name.
Definition at line 250 of file qdbusconnectioninterface.cpp.
 {
     return call(QLatin1String("StartServiceByName"), name, uint(0));
 }
staticInterfaceName()
const char * QDBusConnectionInterface::staticInterfaceName () inline static private
Warning
This function is not part of the public interface.
Definition at line 168 of file qdbusconnectioninterface.cpp.
 { return "org.freedesktop.DBus"; }
unregisterService
QDBusReply< bool > QDBusConnectionInterface::unregisterService (const QString & serviceName) slot
Releases the claim on the bus service name serviceName, that had been previously registered with registerService().
If this application had ownership of the name, it will be released for other applications to claim. If it only had the name queued, it gives up its position in the queue.
Definition at line 333 of file qdbusconnectioninterface.cpp.
 {
     QDBusMessage reply = call(QLatin1String("ReleaseName"), serviceName);
     if (reply.type() == QDBusMessage::ReplyMessage) {
         bool success = reply.arguments().at(0).toUInt() == DBUS_RELEASE_NAME_REPLY_RELEASED;
         reply.setArguments(QVariantList() << success);
     }
     return reply;
 }
Friends and Related Functions
QDBusConnectionPrivate
friend class QDBusConnectionPrivate friend
Definition at line 69 of file qdbusconnectioninterface.h.
Properties
registeredServiceNames
QDBusReply< QStringList > QDBusConnectionInterface::registeredServiceNames private
holds the registered service names
Lists all names currently registered on the bus.
Definition at line 75 of file qdbusconnectioninterface.h.
The documentation for this class was generated from the following files:
/src/dbus/qdbusconnectioninterface.h
/src/dbus/qdbusconnectioninterface.cpp