Qt 4.8: CapabilitiesToStateMask Class Reference
CapabilitiesToStateMask Class Reference
Public Functions
bool canBlitterAlphaFillRect () const
bool canBlitterDrawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr) const
bool canBlitterDrawPixmapOpacity (const QPixmap &pm) const
bool canBlitterDrawRectMask () const
bool canBlitterFillRect () const
CapabilitiesToStateMask (QBlittable::Capabilities capabilities)
void updateState (uint mask, bool on)
Private Functions
void setAlphaFillRectMask ()
void setFillRectMask ()
void setOpacityPixmapMask ()
void setSourceOverPixmapMask ()
void setSourceOverScaledPixmapMask ()
void setSourcePixmapMask ()
Static Private Functions
static bool checkStateAgainstMask (uint state, uint mask)
static void updateStateBits (uint *state, uint mask, bool on)
Properties
uint alphaFillRectMask
uint capabillitiesState
uint drawPixmapMask
uint drawRectMask
uint fillRectMask
QBlittable::Capabilities m_capabilities
uint opacityPixmapMask
Detailed Description
Definition at line 69 of file qpaintengine_blitter.cpp.
Constructors and Destructors
CapabilitiesToStateMask()
CapabilitiesToStateMask::CapabilitiesToStateMask (QBlittable::Capabilities capabilities) inline
Definition at line 72 of file qpaintengine_blitter.cpp.
         : m_capabilities(capabilities)
         , fillRectMask(0)
         , drawRectMask(0)
         , drawPixmapMask(0)
         , alphaFillRectMask(0)
         , opacityPixmapMask(0)
         , capabillitiesState(0)
     {
         if (capabilities & QBlittable::SolidRectCapability)
             setFillRectMask();
         if (capabilities & QBlittable::SourcePixmapCapability)
            setSourcePixmapMask();
         if (capabilities & QBlittable::SourceOverPixmapCapability)
            setSourceOverPixmapMask();
         if (capabilities & QBlittable::SourceOverScaledPixmapCapability)
             setSourceOverScaledPixmapMask();
         if (capabilities & QBlittable::AlphaFillRectCapability)
             setAlphaFillRectMask();
         if (capabilities & QBlittable::OpacityPixmapCapability)
             setOpacityPixmapMask();
     }
Functions
canBlitterAlphaFillRect()
bool CapabilitiesToStateMask::canBlitterAlphaFillRect () const inline
Definition at line 100 of file qpaintengine_blitter.cpp.
     {
         return checkStateAgainstMask(capabillitiesState, alphaFillRectMask);
     }
canBlitterDrawPixmap()
bool CapabilitiesToStateMask::canBlitterDrawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) const inline
Definition at line 110 of file qpaintengine_blitter.cpp.
     {
         if (pm.pixmapData()->classId() != QPixmapData::BlitterClass)
             return false;
         if (checkStateAgainstMask(capabillitiesState, drawPixmapMask)) {
             if (m_capabilities & (QBlittable::SourceOverPixmapCapability
                                   | QBlittable::SourceOverScaledPixmapCapability)) {
                 if (r.size() != sr.size())
                     return m_capabilities & QBlittable::SourceOverScaledPixmapCapability;
                 else
                     return m_capabilities & QBlittable::SourceOverPixmapCapability;
             }
             if ((m_capabilities & QBlittable::SourcePixmapCapability) && r.size() == sr.size() && !pm.hasAlphaChannel())
                 return m_capabilities & QBlittable::SourcePixmapCapability;
         }
         return false;
     }
canBlitterDrawPixmapOpacity()
bool CapabilitiesToStateMask::canBlitterDrawPixmapOpacity (const QPixmap & pm) const inline
Definition at line 128 of file qpaintengine_blitter.cpp.
     {
         if (pm.pixmapData()->classId() != QPixmapData::BlitterClass)
             return false;
         return checkStateAgainstMask(capabillitiesState, opacityPixmapMask);
     }
canBlitterDrawRectMask()
bool CapabilitiesToStateMask::canBlitterDrawRectMask () const inline
Definition at line 105 of file qpaintengine_blitter.cpp.
     {
         return checkStateAgainstMask(capabillitiesState, drawRectMask);
     }
canBlitterFillRect()
bool CapabilitiesToStateMask::canBlitterFillRect () const inline
Definition at line 95 of file qpaintengine_blitter.cpp.
     {
         return checkStateAgainstMask(capabillitiesState, fillRectMask);
     }
checkStateAgainstMask()
static bool CapabilitiesToStateMask::checkStateAgainstMask (uint state, uint mask) inline static private
Definition at line 147 of file qpaintengine_blitter.cpp.
Referenced by canBlitterAlphaFillRect(), canBlitterDrawPixmap(), canBlitterDrawPixmapOpacity(), canBlitterDrawRectMask(), and canBlitterFillRect().
     {
         return !state || (state & mask && !(state & ~mask));
     }
setAlphaFillRectMask()
void CapabilitiesToStateMask::setAlphaFillRectMask () inline private
Definition at line 170 of file qpaintengine_blitter.cpp.
Referenced by CapabilitiesToStateMask().
{
         updateStateBits(&alphaFillRectMask, STATE_XFORM_SCALE, false);
         updateStateBits(&alphaFillRectMask, STATE_XFORM_COMPLEX, false);
         updateStateBits(&alphaFillRectMask, STATE_BRUSH_PATTERN, false);
         updateStateBits(&alphaFillRectMask, STATE_BRUSH_ALPHA, true);
         updateStateBits(&alphaFillRectMask, STATE_PEN_ENABLED, true);
         //Sub-pixel aliasing should not be sent to the blitter
         updateStateBits(&alphaFillRectMask, STATE_ANTIALIASING, true);
         updateStateBits(&alphaFillRectMask, STATE_ALPHA, false);
         updateStateBits(&alphaFillRectMask, STATE_BLENDING_COMPLEX, false);
         updateStateBits(&alphaFillRectMask, STATE_CLIPSYS_COMPLEX, false);
         updateStateBits(&alphaFillRectMask, STATE_CLIP_COMPLEX, false);
     }
setFillRectMask()
void CapabilitiesToStateMask::setFillRectMask () inline private
Definition at line 152 of file qpaintengine_blitter.cpp.
Referenced by CapabilitiesToStateMask().
{
         updateStateBits(&fillRectMask, STATE_XFORM_SCALE, false);
         updateStateBits(&fillRectMask, STATE_XFORM_COMPLEX, false);
         updateStateBits(&fillRectMask, STATE_BRUSH_PATTERN, false);
         updateStateBits(&fillRectMask, STATE_BRUSH_ALPHA, false);
         updateStateBits(&fillRectMask, STATE_PEN_ENABLED, true);
         //Sub-pixel aliasing should not be sent to the blitter
         updateStateBits(&fillRectMask, STATE_ANTIALIASING, true);
         updateStateBits(&fillRectMask, STATE_ALPHA, false);
         updateStateBits(&fillRectMask, STATE_BLENDING_COMPLEX, false);
         updateStateBits(&fillRectMask, STATE_CLIPSYS_COMPLEX, false);
         updateStateBits(&fillRectMask, STATE_CLIP_COMPLEX, false);
     }
setOpacityPixmapMask()
void CapabilitiesToStateMask::setOpacityPixmapMask () inline private
Definition at line 214 of file qpaintengine_blitter.cpp.
Referenced by CapabilitiesToStateMask().
{
         updateStateBits(&opacityPixmapMask, STATE_XFORM_SCALE, true);
         updateStateBits(&opacityPixmapMask, STATE_XFORM_COMPLEX, false);
         updateStateBits(&opacityPixmapMask, STATE_BRUSH_PATTERN, true);
         updateStateBits(&opacityPixmapMask, STATE_BRUSH_ALPHA, true);
         updateStateBits(&opacityPixmapMask, STATE_PEN_ENABLED, true);
         updateStateBits(&opacityPixmapMask, STATE_ANTIALIASING, true);
         updateStateBits(&opacityPixmapMask, STATE_ALPHA, true);
         updateStateBits(&opacityPixmapMask, STATE_BLENDING_COMPLEX, false);
         updateStateBits(&opacityPixmapMask, STATE_CLIPSYS_COMPLEX, false);
         updateStateBits(&opacityPixmapMask, STATE_CLIP_COMPLEX, false);
     }
setSourceOverPixmapMask()
void CapabilitiesToStateMask::setSourceOverPixmapMask () inline private
Definition at line 205 of file qpaintengine_blitter.cpp.
Referenced by CapabilitiesToStateMask(), and setSourceOverScaledPixmapMask().
{
         setSourcePixmapMask();
     }
setSourceOverScaledPixmapMask()
void CapabilitiesToStateMask::setSourceOverScaledPixmapMask () inline private
Definition at line 209 of file qpaintengine_blitter.cpp.
Referenced by CapabilitiesToStateMask().
{
         setSourceOverPixmapMask();
         updateStateBits(&drawRectMask, STATE_XFORM_SCALE, true);
     }
setSourcePixmapMask()
void CapabilitiesToStateMask::setSourcePixmapMask () inline private
Definition at line 188 of file qpaintengine_blitter.cpp.
Referenced by CapabilitiesToStateMask(), and setSourceOverPixmapMask().
{
         updateStateBits(&drawPixmapMask, STATE_XFORM_SCALE, true);
         updateStateBits(&drawPixmapMask, STATE_XFORM_COMPLEX, false);
         updateStateBits(&drawPixmapMask, STATE_BRUSH_PATTERN, true);
         updateStateBits(&drawPixmapMask, STATE_BRUSH_ALPHA, false);
         updateStateBits(&drawPixmapMask, STATE_PEN_ENABLED, true);
         updateStateBits(&drawPixmapMask, STATE_ANTIALIASING, true);
         updateStateBits(&drawPixmapMask, STATE_ALPHA, false);
         updateStateBits(&drawPixmapMask, STATE_BLENDING_COMPLEX, false);
         updateStateBits(&drawPixmapMask, STATE_CLIPSYS_COMPLEX, false);
         updateStateBits(&drawPixmapMask, STATE_CLIP_COMPLEX, false);
     }
updateState()
void CapabilitiesToStateMask::updateState (uint mask, bool on) inline
Definition at line 136 of file qpaintengine_blitter.cpp.
{
         updateStateBits(&capabillitiesState, mask, on);
     }
updateStateBits()
static void CapabilitiesToStateMask::updateStateBits (uint * state, uint mask, bool on) inline static private
Definition at line 142 of file qpaintengine_blitter.cpp.
Referenced by setAlphaFillRectMask(), setFillRectMask(), setOpacityPixmapMask(), setSourceOverScaledPixmapMask(), setSourcePixmapMask(), and updateState().
     {
         *state = on ? (*state | mask) : (*state & ~mask);
     }
Properties
alphaFillRectMask
uint CapabilitiesToStateMask::alphaFillRectMask private
Definition at line 235 of file qpaintengine_blitter.cpp.
Referenced by canBlitterAlphaFillRect(), and setAlphaFillRectMask().
capabillitiesState
uint CapabilitiesToStateMask::capabillitiesState private
Definition at line 237 of file qpaintengine_blitter.cpp.
Referenced by canBlitterAlphaFillRect(), canBlitterDrawPixmap(), canBlitterDrawPixmapOpacity(), canBlitterDrawRectMask(), canBlitterFillRect(), and updateState().
drawPixmapMask
uint CapabilitiesToStateMask::drawPixmapMask private
Definition at line 234 of file qpaintengine_blitter.cpp.
Referenced by canBlitterDrawPixmap(), and setSourcePixmapMask().
drawRectMask
uint CapabilitiesToStateMask::drawRectMask private
Definition at line 233 of file qpaintengine_blitter.cpp.
Referenced by canBlitterDrawRectMask(), and setSourceOverScaledPixmapMask().
fillRectMask
uint CapabilitiesToStateMask::fillRectMask private
Definition at line 232 of file qpaintengine_blitter.cpp.
Referenced by canBlitterFillRect(), and setFillRectMask().
m_capabilities
QBlittable::Capabilities CapabilitiesToStateMask::m_capabilities private
Definition at line 231 of file qpaintengine_blitter.cpp.
Referenced by canBlitterDrawPixmap().
opacityPixmapMask
uint CapabilitiesToStateMask::opacityPixmapMask private
Definition at line 236 of file qpaintengine_blitter.cpp.
Referenced by canBlitterDrawPixmapOpacity(), and setOpacityPixmapMask().
The documentation for this class was generated from the following file:
/src/gui/painting/qpaintengine_blitter.cpp