Qt 4.8: QSvgHandler Class Reference
QSvgHandler Class Reference
#include <qsvghandler_p.h>
Public Types
enum LengthType {
LT_PERCENT, LT_PX, LT_PC, LT_PT,
LT_MM, LT_CM, LT_IN, LT_OTHER
}
Public Functions
int animationDuration () const
bool characters (const QStringRef &str)
QColor currentColor () const
LengthType defaultCoordinateSystem () const
QPen defaultPen () const
QSvgTinyDocument * document () const
bool endElement (const QStringRef &localName)
QString errorString () const
bool inStyle () const
int lineNumber () const
bool ok () const
void parseCSStoXMLAttrs (QString css, QVector< QSvgCssAttribute > *attributes)
void popColor ()
bool processingInstruction (const QString &target, const QString &data)
void pushColor (const QColor &color)
void pushColorCopy ()
QSvgHandler (QIODevice *device)
QSvgHandler (const QByteArray &data)
QSvgHandler (QXmlStreamReader *const data)
QSvgStyleSelector * selector () const
void setAnimPeriod (int start, int end)
void setDefaultCoordinateSystem (LengthType type)
void setInStyle (bool b)
bool startElement (const QString &localName, const QXmlStreamAttributes &attributes)
~QSvgHandler ()
Private Types
enum CurrentNode { Unknown, Graphics, Style }
Private Functions
void init ()
void parse ()
void resolveGradients (QSvgNode *node)
Properties
int m_animEnd
QStack< QColor > m_colorStack
QStack< int > m_colorTagCount
QCss::Parser m_cssParser
LengthType m_defaultCoords
QPen m_defaultPen
QSvgTinyDocument * m_doc
bool m_inStyle
QStack< QSvgNode * > m_nodes
const bool m_ownsReader
QList< QSvgNode * > m_resolveNodes
QSvgStyleSelector * m_selector
QStack< CurrentNode > m_skipNodes
QSvgRefCounter< QSvgStyleProperty > m_style
QStack< QSvgText::WhitespaceMode > m_whitespaceMode
Follows the depths of elements.
QXmlStreamReader *const xml
Detailed Description
Definition at line 81 of file qsvghandler_p.h.
Enumerations
CurrentNode
enum QSvgHandler::CurrentNode private
Enumerator
Unknown
Graphics
Style
Definition at line 145 of file qsvghandler_p.h.
     {
         Unknown,
         Graphics,
         Style
     };
LengthType
enum QSvgHandler::LengthType
Enumerator
LT_PERCENT
LT_PX
LT_PC
LT_PT
LT_MM
LT_CM
LT_IN
LT_OTHER
Definition at line 84 of file qsvghandler_p.h.
                     {
         LT_PERCENT,
         LT_PX,
         LT_PC,
         LT_PT,
         LT_MM,
         LT_CM,
         LT_IN,
         LT_OTHER
     };
Constructors and Destructors
QSvgHandler() [1/3]
QSvgHandler::QSvgHandler (QIODevice * device)
Definition at line 3513 of file qsvghandler.cpp.
                                           : xml(new QXmlStreamReader(device))
                                              , m_ownsReader(true)
 {
     init();
 }
QSvgHandler() [2/3]
QSvgHandler::QSvgHandler (const QByteArray & data)
Definition at line 3519 of file qsvghandler.cpp.
                                                : xml(new QXmlStreamReader(data))
                                                  , m_ownsReader(true)
 {
     init();
 }
QSvgHandler() [3/3]
QSvgHandler::QSvgHandler (QXmlStreamReader *const data)
Definition at line 3525 of file qsvghandler.cpp.
                                                        : xml(reader)
                                                          , m_ownsReader(false)
 {
     init();
 }
~QSvgHandler()
QSvgHandler::~QSvgHandler ()
Definition at line 3912 of file qsvghandler.cpp.
 {
     delete m_selector;
     m_selector = 0;
     if(m_ownsReader)
         delete xml;
 }
Functions
animationDuration()
int QSvgHandler::animationDuration () const
Definition at line 3907 of file qsvghandler.cpp.
Referenced by QSvgTinyDocument::load().
 {
     return m_animEnd;
 }
characters()
bool QSvgHandler::characters (const QStringRef & str)
Definition at line 3777 of file qsvghandler.cpp.
Referenced by parse().
 {
     if (m_inStyle) {
         QString css = str.toString();
         QCss::StyleSheet sheet;
         QCss::Parser(css).parse(&sheet);
         m_selector->styleSheets.append(sheet);
         return true;
     } else if (m_skipNodes.isEmpty() || m_skipNodes.top() == Unknown || m_nodes.isEmpty())
         return true;
     if (m_nodes.top()->type() == QSvgNode::TEXT || m_nodes.top()->type() == QSvgNode::TEXTAREA) {
         static_cast<QSvgText*>(m_nodes.top())->addText(str.toString());
     } else if (m_nodes.top()->type() == QSvgNode::TSPAN) {
         static_cast<QSvgTspan*>(m_nodes.top())->addText(str.toString());
     }
     return true;
 }
currentColor()
QColor QSvgHandler::currentColor () const
Definition at line 3836 of file qsvghandler.cpp.
Referenced by resolveColor().
 {
     if (!m_colorStack.isEmpty())
         return m_colorStack.top();
     else
         return QColor(0, 0, 0);
 }
defaultCoordinateSystem()
QSvgHandler::LengthType QSvgHandler::defaultCoordinateSystem () const
Definition at line 3802 of file qsvghandler.cpp.
Referenced by parseLength().
 {
     return m_defaultCoords;
 }
defaultPen()
QPen QSvgHandler::defaultPen () const inline
Definition at line 128 of file qsvghandler_p.h.
     { return m_defaultPen; }
document()
QSvgTinyDocument * QSvgHandler::document () const
Definition at line 3797 of file qsvghandler.cpp.
Referenced by QSvgTinyDocument::load(), and parseBaseGradient().
 {
     return m_doc;
 }
endElement()
bool QSvgHandler::endElement (const QStringRef & localName)
Definition at line 3716 of file qsvghandler.cpp.
Referenced by parse().
 {
     CurrentNode node = m_skipNodes.top();
     m_skipNodes.pop();
     m_whitespaceMode.pop();
     popColor();
     if (node == Unknown) {
         return true;
     }
     if (m_inStyle && localName == QLatin1String("style"))
         m_inStyle = false;
     if (node == Graphics)
         m_nodes.pop();
     else if (m_style && !m_skipNodes.isEmpty() && m_skipNodes.top() != Style)
         m_style = 0;
     return true;
 }
errorString()
QString QSvgHandler::errorString () const inline
Definition at line 107 of file qsvghandler_p.h.
Referenced by QSvgTinyDocument::load().
 { return xml->errorString(); }
init()
void QSvgHandler::init () private
Definition at line 3531 of file qsvghandler.cpp.
Referenced by QSvgHandler().
 {
     m_doc = 0;
     m_style = 0;
     m_animEnd = 0;
     m_defaultCoords = LT_PX;
     m_defaultPen = QPen(Qt::black, 1, Qt::SolidLine, Qt::FlatCap, Qt::SvgMiterJoin);
     m_defaultPen.setMiterLimit(4);
     parse();
 }
inStyle()
bool QSvgHandler::inStyle () const
Definition at line 3849 of file qsvghandler.cpp.
 {
     return m_inStyle;
 }
lineNumber()
int QSvgHandler::lineNumber () const inline
Definition at line 108 of file qsvghandler_p.h.
Referenced by QSvgTinyDocument::load().
 { return xml->lineNumber(); }
ok()
bool QSvgHandler::ok () const inline
Definition at line 103 of file qsvghandler_p.h.
Referenced by QSvgTinyDocument::load().
{
         return document() != 0 && !xml->hasError();
     }
parse()
void QSvgHandler::parse () private
Definition at line 3542 of file qsvghandler.cpp.
Referenced by init().
 {
     xml->setNamespaceProcessing(false);
     m_selector = new QSvgStyleSelector;
     m_inStyle = false;
     bool done = false;
     while (!xml->atEnd() && !done) {
         switch (xml->readNext()) {
         case QXmlStreamReader::StartElement:
             // he we could/should verify the namespaces, and simply
             // call m_skipNodes(Unknown) if we don't know the
             // namespace.  We do support http://www.w3.org/2000/svg
             // but also http://www.w3.org/2000/svg-20000303-stylable
             // And if the document uses an external dtd, the reported
             // namespaceUri is empty. The only possible strategy at
             // this point is to do what everyone else seems to do and
             // ignore the reported namespaceUri completely.
             if (!startElement(xml->name().toString(), xml->attributes())) {
                 delete m_doc;
                 m_doc = 0;
                 return;
             }
             break;
         case QXmlStreamReader::EndElement:
             endElement(xml->name());
             // if we are using somebody else's qxmlstreamreader
             // we should not read until the end of the stream
             done = !m_ownsReader && (xml->name() == QLatin1String("svg"));
             break;
         case QXmlStreamReader::Characters:
             characters(xml->text());
             break;
         case QXmlStreamReader::ProcessingInstruction:
             processingInstruction(xml->processingInstructionTarget().toString(), xml->processingInstructionData().toString());
             break;
         default:
             break;
         }
     }
     resolveGradients(m_doc);
 }
parseCSStoXMLAttrs()
void QSvgHandler::parseCSStoXMLAttrs (QString css, QVector< QSvgCssAttribute > * attributes)
Definition at line 1923 of file qsvghandler.cpp.
Referenced by QSvgAttributes::QSvgAttributes().
 {
     // preprocess (for unicode escapes), tokenize and remove comments
     m_cssParser.init(css);
     QString key;
     attributes->reserve(10);
     while (m_cssParser.hasNext()) {
         m_cssParser.skipSpace();
         if (!m_cssParser.hasNext())
             break;
         m_cssParser.next();
         QStringRef name;
         if (m_cssParser.hasEscapeSequences) {
             key = m_cssParser.lexem();
             name = QStringRef(&key, 0, key.length());
         } else {
             const QCss::Symbol &sym = m_cssParser.symbol();
             name = QStringRef(&sym.text, sym.start, sym.len);
         }
         m_cssParser.skipSpace();
         if (!m_cssParser.test(QCss::COLON))
             break;
         m_cssParser.skipSpace();
         if (!m_cssParser.hasNext())
             break;
         QSvgCssAttribute attribute;
         attribute.name = QXmlStreamStringRef(name);
         const int firstSymbol = m_cssParser.index;
         int symbolCount = 0;
         do {
             m_cssParser.next();
             ++symbolCount;
         } while (m_cssParser.hasNext() && !m_cssParser.test(QCss::SEMICOLON));
         bool canExtractValueByRef = !m_cssParser.hasEscapeSequences;
         if (canExtractValueByRef) {
             int len = m_cssParser.symbols.at(firstSymbol).len;
             for (int i = firstSymbol + 1; i < firstSymbol + symbolCount; ++i) {
                 len += m_cssParser.symbols.at(i).len;
                 if (m_cssParser.symbols.at(i - 1).start + m_cssParser.symbols.at(i - 1).len
                         != m_cssParser.symbols.at(i).start) {
                     canExtractValueByRef = false;
                     break;
                 }
             }
             if (canExtractValueByRef) {
                 const QCss::Symbol &sym = m_cssParser.symbols.at(firstSymbol);
                 attribute.value = QXmlStreamStringRef(QStringRef(&sym.text, sym.start, len));
             }
         }
         if (!canExtractValueByRef) {
             QString value;
             for (int i = firstSymbol; i < m_cssParser.index - 1; ++i)
                 value += m_cssParser.symbols.at(i).lexem();
             attribute.value = QXmlStreamStringRef(QStringRef(&value, 0, value.length()));
         }
         attributes->append(attribute);
         m_cssParser.skipSpace();
     }
 }
popColor()
void QSvgHandler::popColor ()
Definition at line 3826 of file qsvghandler.cpp.
Referenced by endElement(), parseBaseGradient(), and parseColor().
 {
     if (m_colorTagCount.count()) {
         if (!--m_colorTagCount.top()) {
             m_colorStack.pop();
             m_colorTagCount.pop();
         }
     }
 }
processingInstruction()
bool QSvgHandler::processingInstruction (const QString & target, const QString & data)
Definition at line 3859 of file qsvghandler.cpp.
Referenced by parse().
 {
     if (target == QLatin1String("xml-stylesheet")) {
         QRegExp rx(QLatin1String("type=\\\"(.+)\\\""));
         rx.setMinimal(true);
         bool isCss = false;
         int pos = 0;
         while ((pos = rx.indexIn(data, pos)) != -1) {
             QString type =  rx.cap(1);
             if (type.toLower() == QLatin1String("text/css")) {
                 isCss = true;
             }
             pos += rx.matchedLength();
         }
         if (isCss) {
             QRegExp rx(QLatin1String("href=\\\"(.+)\\\""));
             rx.setMinimal(true);
             pos = 0;
             pos = rx.indexIn(data, pos);
             QString addr = rx.cap(1);
             QFileInfo fi(addr);
             //qDebug()<<"External CSS file "<<fi.absoluteFilePath()<<fi.exists();
             if (fi.exists()) {
                 QFile file(fi.absoluteFilePath());
                 if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
                     return true;
                 }
                 QByteArray cssData = file.readAll();
                 QString css = QString::fromUtf8(cssData);
                 QCss::StyleSheet sheet;
                 QCss::Parser(css).parse(&sheet);
                 m_selector->styleSheets.append(sheet);
             }
         }
     }
     return true;
 }
pushColor()
void QSvgHandler::pushColor (const QColor & color)
Definition at line 3812 of file qsvghandler.cpp.
Referenced by parseBaseGradient(), parseColor(), and pushColorCopy().
 {
     m_colorStack.push(color);
     m_colorTagCount.push(1);
 }
pushColorCopy()
void QSvgHandler::pushColorCopy ()
Definition at line 3818 of file qsvghandler.cpp.
Referenced by startElement().
 {
     if (m_colorTagCount.count())
         ++m_colorTagCount.top();
     else
         pushColor(Qt::black);
 }
resolveGradients()
void QSvgHandler::resolveGradients (QSvgNode * node) private
Definition at line 3739 of file qsvghandler.cpp.
Referenced by parse().
 {
     if (!node || (node->type() != QSvgNode::DOC && node->type() != QSvgNode::G
         && node->type() != QSvgNode::DEFS && node->type() != QSvgNode::SWITCH)) {
         return;
     }
     QSvgStructureNode *structureNode = static_cast<QSvgStructureNode *>(node);
     QList<QSvgNode *> ren = structureNode->renderers();
     for (QList<QSvgNode *>::iterator it = ren.begin(); it != ren.end(); ++it) {
         QSvgFillStyle *fill = static_cast<QSvgFillStyle *>((*it)->styleProperty(QSvgStyleProperty::FILL));
         if (fill && !fill->isGradientResolved()) {
             QString id = fill->gradientId();
             QSvgFillStyleProperty *style = structureNode->styleProperty(id);
             if (style) {
                 fill->setFillStyle(style);
             } else {
                 qWarning("Could not resolve property : %s", qPrintable(id));
                 fill->setBrush(Qt::NoBrush);
             }
         }
         QSvgStrokeStyle *stroke = static_cast<QSvgStrokeStyle *>((*it)->styleProperty(QSvgStyleProperty::STROKE));
         if (stroke && !stroke->isGradientResolved()) {
             QString id = stroke->gradientId();
             QSvgFillStyleProperty *style = structureNode->styleProperty(id);
             if (style) {
                 stroke->setStyle(style);
             } else {
                 qWarning("Could not resolve property : %s", qPrintable(id));
                 stroke->setStroke(Qt::NoBrush);
             }
         }
         resolveGradients(*it);
     }
 }
selector()
QSvgStyleSelector * QSvgHandler::selector () const
Definition at line 3854 of file qsvghandler.cpp.
Referenced by parseStopNode().
 {
     return m_selector;
 }
setAnimPeriod()
void QSvgHandler::setAnimPeriod (int start, int end)
Definition at line 3901 of file qsvghandler.cpp.
Referenced by parseAnimateColorNode(), and parseAnimateTransformNode().
 {
     Q_UNUSED(start);
     m_animEnd   = qMax(end, m_animEnd);
 }
setDefaultCoordinateSystem()
void QSvgHandler::setDefaultCoordinateSystem (LengthType type)
Definition at line 3807 of file qsvghandler.cpp.
Referenced by createSvgNode().
 {
     m_defaultCoords = type;
 }
setInStyle()
void QSvgHandler::setInStyle (bool b)
Definition at line 3844 of file qsvghandler.cpp.
Referenced by parseStyleNode().
 {
     m_inStyle = b;
 }
startElement()
bool QSvgHandler::startElement (const QString & localName, const QXmlStreamAttributes & attributes)
Definition at line 3584 of file qsvghandler.cpp.
Referenced by parse().
 {
     QSvgNode *node = 0;
     pushColorCopy();
     /* The xml:space attribute may appear on any element. We do
      * a lookup by the qualified name here, but this is namespace aware, since
      * the XML namespace can only be bound to prefix "xml." */
     const QStringRef xmlSpace(attributes.value(QLatin1String("xml:space")));
     if (xmlSpace.isNull()) {
         // This element has no xml:space attribute.
         m_whitespaceMode.push(m_whitespaceMode.isEmpty() ? QSvgText::Default : m_whitespaceMode.top());
     } else if (xmlSpace == QLatin1String("preserve")) {
         m_whitespaceMode.push(QSvgText::Preserve);
     } else if (xmlSpace == QLatin1String("default")) {
         m_whitespaceMode.push(QSvgText::Default);
     } else {
         qWarning() << QString::fromLatin1("\"%1\" is an invalid value for attribute xml:space. "
                                           "Valid values are \"preserve\" and \"default\".").arg(xmlSpace.toString());
         m_whitespaceMode.push(QSvgText::Default);
     }
     if (!m_doc && localName != QLatin1String("svg"))
         return false;
     if (FactoryMethod method = findGroupFactory(localName)) {
         //group
         node = method(m_doc ? m_nodes.top() : 0, attributes, this);
         Q_ASSERT(node);
         if (!m_doc) {
             Q_ASSERT(node->type() == QSvgNode::DOC);
             m_doc = static_cast<QSvgTinyDocument*>(node);
         } else {
             switch (m_nodes.top()->type()) {
             case QSvgNode::DOC:
             case QSvgNode::G:
             case QSvgNode::DEFS:
             case QSvgNode::SWITCH:
             {
                 QSvgStructureNode *group =
                     static_cast<QSvgStructureNode*>(m_nodes.top());
                 group->addChild(node, someId(attributes));
             }
                 break;
             default:
                 break;
             }
         }
         parseCoreNode(node, attributes);
         cssStyleLookup(node, this, m_selector);
         parseStyle(node, attributes, this);
     } else if (FactoryMethod method = findGraphicsFactory(localName)) {
         //rendering element
         Q_ASSERT(!m_nodes.isEmpty());
         node = method(m_nodes.top(), attributes, this);
         if (node) {
             switch (m_nodes.top()->type()) {
             case QSvgNode::DOC:
             case QSvgNode::G:
             case QSvgNode::DEFS:
             case QSvgNode::SWITCH:
             {
                 QSvgStructureNode *group =
                     static_cast<QSvgStructureNode*>(m_nodes.top());
                 group->addChild(node, someId(attributes));
             }
                 break;
             case QSvgNode::TEXT:
             case QSvgNode::TEXTAREA:
                 if (node->type() == QSvgNode::TSPAN) {
                     static_cast<QSvgText *>(m_nodes.top())->addTspan(static_cast<QSvgTspan *>(node));
                 } else {
                     qWarning("\'text\' or \'textArea\' element contains invalid element type.");
                     delete node;
                     node = 0;
                 }
                 break;
             default:
                 qWarning("Could not add child element to parent element because the types are incorrect.");
                 delete node;
                 node = 0;
                 break;
             }
             if (node) {
                 parseCoreNode(node, attributes);
                 cssStyleLookup(node, this, m_selector);
                 parseStyle(node, attributes, this);
                 if (node->type() == QSvgNode::TEXT || node->type() == QSvgNode::TEXTAREA) {
                     static_cast<QSvgText *>(node)->setWhitespaceMode(m_whitespaceMode.top());
                 } else if (node->type() == QSvgNode::TSPAN) {
                     static_cast<QSvgTspan *>(node)->setWhitespaceMode(m_whitespaceMode.top());
                 }
             }
         }
     } else if (ParseMethod method = findUtilFactory(localName)) {
         Q_ASSERT(!m_nodes.isEmpty());
         if (!method(m_nodes.top(), attributes, this)) {
             qWarning("Problem parsing %s", qPrintable(localName));
         }
     } else if (StyleFactoryMethod method = findStyleFactoryMethod(localName)) {
         QSvgStyleProperty *prop = method(m_nodes.top(), attributes, this);
         if (prop) {
             m_style = prop;
             m_nodes.top()->appendStyleProperty(prop, someId(attributes));
         } else {
             qWarning("Could not parse node: %s", qPrintable(localName));
         }
     } else if (StyleParseMethod method = findStyleUtilFactoryMethod(localName)) {
         if (m_style) {
             if (!method(m_style, attributes, this)) {
                 qWarning("Problem parsing %s", qPrintable(localName));
             }
         }
     } else {
         //qWarning()<<"Skipping unknown element!"<<namespaceURI<<"::"<<localName;
         m_skipNodes.push(Unknown);
         return true;
     }
     if (node) {
         m_nodes.push(node);
         m_skipNodes.push(Graphics);
     } else {
         //qDebug()<<"Skipping "<<localName;
         m_skipNodes.push(Style);
     }
     return true;
 }
Properties
m_animEnd
int QSvgHandler::m_animEnd private
Definition at line 170 of file qsvghandler_p.h.
Referenced by animationDuration(), init(), and setAnimPeriod().
m_colorStack
QStack<QColor> QSvgHandler::m_colorStack private
Definition at line 163 of file qsvghandler_p.h.
Referenced by currentColor(), popColor(), and pushColor().
m_colorTagCount
QStack<int> QSvgHandler::m_colorTagCount private
Definition at line 164 of file qsvghandler_p.h.
Referenced by popColor(), pushColor(), and pushColorCopy().
m_cssParser
QCss::Parser QSvgHandler::m_cssParser private
Definition at line 173 of file qsvghandler_p.h.
m_defaultCoords
LengthType QSvgHandler::m_defaultCoords private
Definition at line 161 of file qsvghandler_p.h.
Referenced by defaultCoordinateSystem(), init(), and setDefaultCoordinateSystem().
m_defaultPen
QPen QSvgHandler::m_defaultPen private
Definition at line 177 of file qsvghandler_p.h.
Referenced by init().
m_doc
QSvgTinyDocument* QSvgHandler::m_doc private
Definition at line 140 of file qsvghandler_p.h.
Referenced by document(), init(), parse(), and startElement().
m_inStyle
bool QSvgHandler::m_inStyle private
Definition at line 166 of file qsvghandler_p.h.
Referenced by characters(), endElement(), inStyle(), parse(), and setInStyle().
m_nodes
QStack<QSvgNode*> QSvgHandler::m_nodes private
Definition at line 141 of file qsvghandler_p.h.
Referenced by characters(), endElement(), and startElement().
m_ownsReader
const bool QSvgHandler::m_ownsReader private
Whether we own the variable xml, and hence whether we need to delete it.
Definition at line 182 of file qsvghandler_p.h.
Referenced by parse(), and ~QSvgHandler().
m_resolveNodes
QList<QSvgNode*> QSvgHandler::m_resolveNodes private
Definition at line 143 of file qsvghandler_p.h.
m_selector
QSvgStyleSelector* QSvgHandler::m_selector private
Definition at line 168 of file qsvghandler_p.h.
Referenced by characters(), parse(), processingInstruction(), selector(), startElement(), and ~QSvgHandler().
m_skipNodes
QStack<CurrentNode> QSvgHandler::m_skipNodes private
Definition at line 151 of file qsvghandler_p.h.
Referenced by characters(), endElement(), and startElement().
m_style
QSvgRefCounter<QSvgStyleProperty> QSvgHandler::m_style private
Definition at line 159 of file qsvghandler_p.h.
Referenced by endElement(), init(), and startElement().
m_whitespaceMode
QStack<QSvgText::WhitespaceMode> QSvgHandler::m_whitespaceMode private
Follows the depths of elements.
The top is current xml:space value that applies for a given element.
Definition at line 157 of file qsvghandler_p.h.
Referenced by endElement(), and startElement().
xml
QXmlStreamReader* const QSvgHandler::xml private
Definition at line 172 of file qsvghandler_p.h.
Referenced by parse(), and ~QSvgHandler().
The documentation for this class was generated from the following files:
/src/svg/qsvghandler_p.h
/src/svg/qsvghandler.cpp