Qt 4.8: QLocalServer Class Reference
QLocalServer Class Reference
The QLocalServer class provides a local socket based server.
#include <qlocalserver.h>
Signals
void newConnection ()
This signal is emitted every time a new connection is available.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void close ()
Stop listening for incoming connections.
QString errorString () const
Returns the human-readable message appropriate to the current error reported by serverError().
QString fullServerName () const
Returns the full path that the server is listening on.
virtual bool hasPendingConnections () const
Returns true if the server has a pending connection; otherwise returns false.
bool isListening () const
Returns true if the server is listening for incoming connections otherwise false.
bool listen (const QString &name)
Tells the server to listen for incoming connections on name.
int maxPendingConnections () const
Returns the maximum number of pending accepted connections.
virtual QLocalSocket * nextPendingConnection ()
Returns the next pending connection as a connected QLocalSocket object.
QLocalServer (QObject *parent=0)
Create a new local socket server with the given parent.
QAbstractSocket::SocketError serverError () const
Returns the type of error that occurred last or NoError.
QString serverName () const
Returns the server name if the server is listening for connections; otherwise returns QString()
void setMaxPendingConnections (int numConnections)
Sets the maximum number of pending accepted connections to numConnections.
bool waitForNewConnection (int msec=0, bool *timedOut=0)
Waits for at most msec milliseconds or until an incoming connection is available.
~QLocalServer ()
Destroys the QLocalServer object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool removeServer (const QString &name)
Removes any server instance that might cause a call to listen() to fail and returns true if successful; otherwise returns false.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
virtual void incomingConnection (quintptr socketDescriptor)
This virtual function is called by QLocalServer when a new connection is available.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QLocalServer class provides a local socket based server.
Since
4.4
This class makes it possible to accept incoming local socket connections.
Call listen() to have the server start listening for incoming connections on a specified key. The newConnection() signal is then emitted each time a client connects to the server.
Call nextPendingConnection() to accept the pending connection as a connected QLocalSocket. The function returns a pointer to a QLocalSocket that can be used for communicating with the client.
If an error occurs, serverError() returns the type of error, and errorString() can be called to get a human readable description of what happened.
When listening for connections, the name which the server is listening on is available through serverName().
Calling close() makes QLocalServer stop listening for incoming connections.
Although QLocalServer is designed for use with an event loop, it's possible to use it without one. In that case, you must use waitForNewConnection(), which blocks until either a connection is available or a timeout expires.
See also
QLocalSocket, QTcpServer
Definition at line 58 of file qlocalserver.h.
Constructors and Destructors
QLocalServer()
QLocalServer::QLocalServer (QObject * parent = 0)
Create a new local socket server with the given parent.
See also
listen()
Definition at line 92 of file qlocalserver.cpp.
         : QObject(*new QLocalServerPrivate, parent)
 {
     Q_D(QLocalServer);
     d->init();
 }
~QLocalServer()
QLocalServer::~QLocalServer ()
Destroys the QLocalServer object.
If the server is listening for connections, it is automatically closed.
Any client QLocalSockets that are still connected must either disconnect or be reparented before the server is deleted.
See also
close()
Definition at line 108 of file qlocalserver.cpp.
 {
     if (isListening())
     close();
 }
Functions
close()
void QLocalServer::close ()
Stop listening for incoming connections.
Existing connections are not effected, but any new connections will be refused.
See also
isListening(), listen()
Definition at line 120 of file qlocalserver.cpp.
Referenced by ~QLocalServer().
 {
     Q_D(QLocalServer);
     if (!isListening())
         return;
     qDeleteAll(d->pendingConnections);
     d->pendingConnections.clear();
     d->closeServer();
     d->serverName.clear();
     d->fullServerName.clear();
     d->errorString.clear();
     d->error = QAbstractSocket::UnknownSocketError;
 }
errorString()
QString QLocalServer::errorString () const
Returns the human-readable message appropriate to the current error reported by serverError().
If no suitable string is available, an empty string is returned.
See also
serverError()
Definition at line 141 of file qlocalserver.cpp.
 {
     Q_D(const QLocalServer);
     return d->errorString;
 }
fullServerName()
QString QLocalServer::fullServerName () const
Returns the full path that the server is listening on.
Note: This is platform specific
See also
listen(), serverName()
Definition at line 338 of file qlocalserver.cpp.
 {
     Q_D(const QLocalServer);
     return d->fullServerName;
 }
hasPendingConnections()
bool QLocalServer::hasPendingConnections () const virtual
Returns true if the server has a pending connection; otherwise returns false.
See also
nextPendingConnection(), setMaxPendingConnections()
Definition at line 153 of file qlocalserver.cpp.
 {
     Q_D(const QLocalServer);
     return !(d->pendingConnections.isEmpty());
 }
incomingConnection()
void QLocalServer::incomingConnection (quintptr socketDescriptor) protected virtual
This virtual function is called by QLocalServer when a new connection is available.
socketDescriptor is the native socket descriptor for the accepted connection.
The base implementation creates a QLocalSocket, sets the socket descriptor and then stores the QLocalSocket in an internal list of pending connections. Finally newConnection() is emitted.
Reimplement this function to alter the server's behavior when a connection is available.
See also
newConnection(), nextPendingConnection(), QLocalSocket::setSocketDescriptor()
Definition at line 174 of file qlocalserver.cpp.
 {
     Q_D(QLocalServer);
     QLocalSocket *socket = new QLocalSocket(this);
     socket->setSocketDescriptor(socketDescriptor);
     d->pendingConnections.enqueue(socket);
     emit newConnection();
 }
isListening()
bool QLocalServer::isListening () const
Returns true if the server is listening for incoming connections otherwise false.
See also
listen(), close()
Definition at line 189 of file qlocalserver.cpp.
Referenced by close(), listen(), waitForNewConnection(), and ~QLocalServer().
 {
     Q_D(const QLocalServer);
     return !(d->serverName.isEmpty());
 }
listen()
bool QLocalServer::listen (const QString & name)
Tells the server to listen for incoming connections on name.
If the server is currently listening then it will return false. Return true on success otherwise false.
name can be a single name and QLocalServer will determine the correct platform specific path. serverName() will return the name that is passed into listen.
Usually you would just pass in a name like "foo", but on Unix this could also be a path such as "/tmp/foo" and on Windows this could be a pipe path such as "\\\\.\\pipe\\foo"
Note: On Unix if the server crashes without closing listen will fail with AddressInUseError. To create a new server the file should be removed. On Windows two local servers can listen to the same pipe at the same time, but any connections will go to one of the server.
See also
serverName(), isListening(), close()
Definition at line 216 of file qlocalserver.cpp.
 {
     Q_D(QLocalServer);
     if (isListening()) {
         qWarning("QLocalServer::listen() called when already listening");
         return false;
     }
     if (name.isEmpty()) {
         d->error = QAbstractSocket::HostNotFoundError;
         QString function = QLatin1String("QLocalServer::listen");
         d->errorString = tr("%1: Name error").arg(function);
         return false;
     }
     if (!d->listen(name)) {
         d->serverName.clear();
         d->fullServerName.clear();
         return false;
     }
     d->serverName = name;
     return true;
 }
maxPendingConnections()
int QLocalServer::maxPendingConnections () const
Returns the maximum number of pending accepted connections.
The default is 30.
See also
setMaxPendingConnections(), hasPendingConnections()
Definition at line 247 of file qlocalserver.cpp.
 {
     Q_D(const QLocalServer);
     return d->maxPendingConnections;
 }
newConnection
void QLocalServer::newConnection () signal
This signal is emitted every time a new connection is available.
See also
hasPendingConnections(), nextPendingConnection()
Referenced by incomingConnection().
nextPendingConnection()
QLocalSocket * QLocalServer::nextPendingConnection () virtual
Returns the next pending connection as a connected QLocalSocket object.
The socket is created as a child of the server, which means that it is automatically deleted when the QLocalServer object is destroyed. It is still a good idea to delete the object explicitly when you are done with it, to avoid wasting memory.
0 is returned if this function is called when there are no pending connections.
See also
hasPendingConnections(), newConnection(), incomingConnection()
Definition at line 277 of file qlocalserver.cpp.
 {
     Q_D(QLocalServer);
     if (d->pendingConnections.isEmpty())
         return 0;
     QLocalSocket *nextSocket = d->pendingConnections.dequeue();
 #ifndef QT_LOCALSOCKET_TCP
 #ifdef Q_OS_SYMBIAN
     if(!d->socketNotifier)
         return nextSocket;
 #endif
     if (d->pendingConnections.size() <= d->maxPendingConnections)
 #ifndef Q_OS_WIN
         d->socketNotifier->setEnabled(true);
 #else
         d->connectionEventNotifier->setEnabled(true);
 #endif
 #endif
     return nextSocket;
 }
removeServer()
bool QLocalServer::removeServer (const QString & name) static
Removes any server instance that might cause a call to listen() to fail and returns true if successful; otherwise returns false.
Since
4.5
This function is meant to recover from a crash, when the previous server instance has not been cleaned up.
On Windows, this function does nothing; on Unix, it removes the socket file given by name.
Warning
Be careful to avoid removing sockets of running instances.
Definition at line 314 of file qlocalserver.cpp.
 {
     return QLocalServerPrivate::removeServer(name);
 }
serverError()
QAbstractSocket::SocketError QLocalServer::serverError () const
Returns the type of error that occurred last or NoError.
See also
errorString()
Definition at line 349 of file qlocalserver.cpp.
 {
     Q_D(const QLocalServer);
     return d->error;
 }
serverName()
QString QLocalServer::serverName () const
Returns the server name if the server is listening for connections; otherwise returns QString()
See also
listen(), fullServerName()
Definition at line 325 of file qlocalserver.cpp.
 {
     Q_D(const QLocalServer);
     return d->serverName;
 }
setMaxPendingConnections()
void QLocalServer::setMaxPendingConnections (int numConnections)
Sets the maximum number of pending accepted connections to numConnections.
QLocalServer will accept no more than numConnections incoming connections before nextPendingConnection() is called.
Note: Even though QLocalServer will stop accepting new connections after it has reached its maximum number of pending connections, the operating system may still keep them in queue which will result in clients signaling that it is connected.
See also
maxPendingConnections(), hasPendingConnections()
Definition at line 368 of file qlocalserver.cpp.
 {
     Q_D(QLocalServer);
     d->maxPendingConnections = numConnections;
 }
waitForNewConnection()
bool QLocalServer::waitForNewConnection (int msec = 0, bool * timedOut = 0)
Waits for at most msec milliseconds or until an incoming connection is available.
Returns true if a connection is available; otherwise returns false. If the operation timed out and timedOut is not 0, timedOut will be set to true.
This is a blocking function call. Its use is ill-advised in a single-threaded GUI application, since the whole application will stop responding until the function returns. waitForNewConnection() is mostly useful when there is no event loop available.
The non-blocking alternative is to connect to the newConnection() signal.
If msec is -1, this function will not time out.
See also
hasPendingConnections(), nextPendingConnection()
Definition at line 391 of file qlocalserver.cpp.
 {
     Q_D(QLocalServer);
     if (timedOut)
         *timedOut = false;
     if (!isListening())
         return false;
     d->waitForNewConnection(msec, timedOut);
     return !d->pendingConnections.isEmpty();
 }
The documentation for this class was generated from the following files:
/src/network/socket/qlocalserver.h
/src/network/socket/qlocalserver.cpp