Qt 4.8: QInternalMimeData Class Reference
QInternalMimeData Class Reference abstract
#include <qdnd_p.h>
Public Functions
QStringList formats () const
Returns a list of formats supported by the object.
bool hasFormat (const QString &mimeType) const
Returns true if the object can return data for the MIME type specified by mimeType; otherwise returns false.
QInternalMimeData ()
~QInternalMimeData ()
Public Functions inherited from QMimeData
void clear ()
Removes all the MIME type and data entries in the object.
QVariant colorData () const
Returns a color if the data stored in the object represents a color (MIME type application/x-color); otherwise returns a null variant.
QByteArray data (const QString &mimetype) const
Returns the data stored in the object in the format described by the MIME type specified by mimeType.
bool hasColor () const
Returns true if the object can return a color (MIME type application/x-color); otherwise returns false.
bool hasHtml () const
Returns true if the object can return HTML (MIME type text/html); otherwise returns false.
bool hasImage () const
Returns true if the object can return an image; otherwise returns false.
bool hasText () const
Returns true if the object can return plain text (MIME type text/plain); otherwise returns false.
bool hasUrls () const
Returns true if the object can return a list of urls; otherwise returns false.
QString html () const
Returns a string if the data stored in the object is HTML (MIME type text/html); otherwise returns an empty string.
QVariant imageData () const
Returns a QVariant storing a QImage if the object can return an image; otherwise returns a null variant.
QMimeData ()
Constructs a new MIME data object with no data in it.
void removeFormat (const QString &mimetype)
Removes the data entry for mimeType in the object.
void setColorData (const QVariant &color)
Sets the color data in the object to the given color.
void setData (const QString &mimetype, const QByteArray &data)
Sets the data associated with the MIME type given by mimeType to the specified data.
void setHtml (const QString &html)
Sets html as the HTML (MIME type text/html) used to represent the data.
void setImageData (const QVariant &image)
Sets the data in the object to the given image.
void setText (const QString &text)
Sets text as the plain text (MIME type text/plain) used to represent the data.
void setUrls (const QList< QUrl > &urls)
Sets the URLs stored in the MIME data object to those specified by urls.
QString text () const
Returns a plain text (MIME type text/plain) representation of the data.
QList< QUrl > urls () const
Returns a list of URLs contained within the MIME data object.
~QMimeData ()
Destroys the MIME data object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool canReadData (const QString &mimeType)
static QStringList formatsHelper (const QMimeData *data)
static bool hasFormatHelper (const QString &mimeType, const QMimeData *data)
static QByteArray renderDataHelper (const QString &mimeType, const QMimeData *data)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
virtual QStringList formats_sys () const =0
virtual bool hasFormat_sys (const QString &mimeType) const =0
QVariant retrieveData (const QString &mimeType, QVariant::Type type) const
Returns a variant with the given type containing data for the MIME type specified by mimeType.
virtual QVariant retrieveData_sys (const QString &mimeType, QVariant::Type type) const =0
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 79 of file qdnd_p.h.
Constructors and Destructors
QInternalMimeData()
QInternalMimeData::QInternalMimeData ()
Definition at line 329 of file qdnd.cpp.
     : QMimeData()
 {
 }
~QInternalMimeData()
QInternalMimeData::~QInternalMimeData ()
Definition at line 334 of file qdnd.cpp.
 {
 }
Functions
canReadData()
bool QInternalMimeData::canReadData (const QString & mimeType) static
Definition at line 408 of file qdnd.cpp.
Referenced by QLastResortMimes::mimeForFormat().
 {
     return imageReadMimeFormats().contains(mimeType);
 }
formats()
QStringList QInternalMimeData::formats () const virtual
Returns a list of formats supported by the object.
This is a list of MIME types for which the object can return suitable data. The formats in the list are in a priority order.
For the most common types of data, you can call the higher-level functions hasText(), hasHtml(), hasUrls(), hasImage(), and hasColor() instead.
See also
hasFormat(), setData(), data()
Reimplemented from QMimeData.
Definition at line 351 of file qdnd.cpp.
Referenced by QClipboardWatcher::empty(), QCocoaDropData::formats_sys(), QWaylandMimeData::hasFormat_sys(), QXlibClipboardMime::hasFormat_sys(), imageReadMimeFormats(), imageWriteMimeFormats(), and QXlibMime::mimeFormatsForAtom().
 {
     QStringList realFormats = formats_sys();
     if (!realFormats.contains(QLatin1String("application/x-qt-image"))) {
         QStringList imageFormats = imageReadMimeFormats();
         for (int i = 0; i < imageFormats.size(); ++i) {
             if (realFormats.contains(imageFormats.at(i))) {
                 realFormats += QLatin1String("application/x-qt-image");
                 break;
             }
         }
     }
     return realFormats;
 }
formats_sys()
virtual QStringList QInternalMimeData::formats_sys () const protected pure virtual
Implemented in QCocoaDropData, QDropData, QClipboardWatcher, QClipboardWatcher, QXlibClipboardMime, and QWaylandMimeData.
Referenced by formats().
formatsHelper()
QStringList QInternalMimeData::formatsHelper (const QMimeData * data) static
Definition at line 414 of file qdnd.cpp.
Referenced by QWindowsMime::allFormatsForMime(), findRealWindow(), send_targets_selection(), and QXlibClipboard::sendTargetsSelection().
 {
     QStringList realFormats = data->formats();
     if (realFormats.contains(QLatin1String("application/x-qt-image"))) {
         // add all supported image formats
         QStringList imageFormats = imageWriteMimeFormats();
         for (int i = 0; i < imageFormats.size(); ++i) {
             if (!realFormats.contains(imageFormats.at(i)))
                 realFormats.append(imageFormats.at(i));
         }
     }
     return realFormats;
 }
hasFormat()
bool QInternalMimeData::hasFormat (const QString & mimeType) const virtual
Returns true if the object can return data for the MIME type specified by mimeType; otherwise returns false.
For the most common types of data, you can call the higher-level functions hasText(), hasHtml(), hasUrls(), hasImage(), and hasColor() instead.
See also
formats(), setData(), data()
Reimplemented from QMimeData.
Definition at line 338 of file qdnd.cpp.
 {
     bool foundFormat = hasFormat_sys(mimeType);
     if (!foundFormat && mimeType == QLatin1String("application/x-qt-image")) {
         QStringList imageFormats = imageReadMimeFormats();
         for (int i = 0; i < imageFormats.size(); ++i) {
             if ((foundFormat = hasFormat_sys(imageFormats.at(i))))
                 break;
         }
     }
     return foundFormat;
 }
hasFormat_sys()
virtual bool QInternalMimeData::hasFormat_sys (const QString & mimeType) const protected pure virtual
Implemented in QCocoaDropData, QDropData, QClipboardWatcher, QXlibClipboardMime, QClipboardWatcher, and QWaylandMimeData.
Referenced by hasFormat().
hasFormatHelper()
bool QInternalMimeData::hasFormatHelper (const QString & mimeType, const QMimeData * data) static
Definition at line 428 of file qdnd.cpp.
Referenced by QLastResortMimes::canConvertFromMime(), QXlibMime::mimeDataForAtom(), and QX11Data::xdndMimeDataForAtom().
 {
     bool foundFormat = data->hasFormat(mimeType);
     if (!foundFormat) {
         if (mimeType == QLatin1String("application/x-qt-image")) {
             // check all supported image formats
             QStringList imageFormats = imageWriteMimeFormats();
             for (int i = 0; i < imageFormats.size(); ++i) {
                 if ((foundFormat = data->hasFormat(imageFormats.at(i))))
                     break;
             }
         } else if (mimeType.startsWith(QLatin1String("image/"))) {
             return data->hasImage() && imageWriteMimeFormats().contains(mimeType);
         }
     }
     return foundFormat;
 }
renderDataHelper()
QByteArray QInternalMimeData::renderDataHelper (const QString & mimeType, const QMimeData * data) static
Definition at line 447 of file qdnd.cpp.
Referenced by QBuiltInMimes::convertFromMime(), QLastResortMimes::convertFromMime(), QXlibMime::mimeDataForAtom(), and QX11Data::xdndMimeDataForAtom().
 {
     QByteArray ba;
     if (mimeType == QLatin1String("application/x-color")) {
         /* QMimeData can only provide colors as QColor or the name
            of a color as a QByteArray or a QString. So we need to do
            the conversion to application/x-color here.
            The application/x-color format is :
            type: application/x-color
            format: 16
            data[0]: red
            data[1]: green
            data[2]: blue
            data[3]: opacity
         */
         ba.resize(8);
         ushort * colBuf = (ushort *)ba.data();
         QColor c = qvariant_cast<QColor>(data->colorData());
         colBuf[0] = ushort(c.redF() * 0xFFFF);
         colBuf[1] = ushort(c.greenF() * 0xFFFF);
         colBuf[2] = ushort(c.blueF() * 0xFFFF);
         colBuf[3] = ushort(c.alphaF() * 0xFFFF);
     } else {
         ba = data->data(mimeType);
         if (ba.isEmpty()) {
             if (mimeType == QLatin1String("application/x-qt-image") && data->hasImage()) {
                 QImage image = qvariant_cast<QImage>(data->imageData());
                 QBuffer buf(&ba);
                 buf.open(QBuffer::WriteOnly);
                 // would there not be PNG ??
                 image.save(&buf, "PNG");
             } else if (mimeType.startsWith(QLatin1String("image/")) && data->hasImage()) {
                 QImage image = qvariant_cast<QImage>(data->imageData());
                 QBuffer buf(&ba);
                 buf.open(QBuffer::WriteOnly);
                 image.save(&buf, mimeType.mid(mimeType.indexOf(QLatin1Char('/')) + 1).toLatin1().toUpper());
             }
         }
     }
     return ba;
 }
retrieveData()
QVariant QInternalMimeData::retrieveData (const QString & mimeType, QVariant::Type type) const protected virtual
Returns a variant with the given type containing data for the MIME type specified by mimeType.
If the object does not support the MIME type or variant type given, a null variant is returned instead.
This function is called by the general data() getter and by the convenience getters (text(), html(), urls(), imageData(), and colorData()). You can reimplement it if you want to store your data using a custom data structure (instead of a QByteArray, which is what setData() provides). You would then also need to reimplement hasFormat() and formats().
See also
data()
Reimplemented from QMimeData.
Definition at line 366 of file qdnd.cpp.
 {
     QVariant data = retrieveData_sys(mimeType, type);
     if (mimeType == QLatin1String("application/x-qt-image")) {
         if (data.isNull() || (data.type() == QVariant::ByteArray && data.toByteArray().isEmpty())) {
             // try to find an image
             QStringList imageFormats = imageReadMimeFormats();
             for (int i = 0; i < imageFormats.size(); ++i) {
                 data = retrieveData_sys(imageFormats.at(i), type);
                 if (data.isNull() || (data.type() == QVariant::ByteArray && data.toByteArray().isEmpty()))
                     continue;
                 break;
             }
         }
         // we wanted some image type, but all we got was a byte array. Convert it to an image.
         if (data.type() == QVariant::ByteArray
             && (type == QVariant::Image || type == QVariant::Pixmap || type == QVariant::Bitmap))
             data = QImage::fromData(data.toByteArray());
     } else if (mimeType == QLatin1String("application/x-color") && data.type() == QVariant::ByteArray) {
         QColor c;
         QByteArray ba = data.toByteArray();
         if (ba.size() == 8) {
             ushort * colBuf = (ushort *)ba.data();
             c.setRgbF(qreal(colBuf[0]) / qreal(0xFFFF),
                       qreal(colBuf[1]) / qreal(0xFFFF),
                       qreal(colBuf[2]) / qreal(0xFFFF),
                       qreal(colBuf[3]) / qreal(0xFFFF));
             data = c;
         } else {
             qWarning("Qt: Invalid color format");
         }
     } else if (data.type() != type && data.type() == QVariant::ByteArray) {
         // try to use mime data's internal conversion stuf.
         QInternalMimeData *that = const_cast<QInternalMimeData *>(this);
         that->setData(mimeType, data.toByteArray());
         data = QMimeData::retrieveData(mimeType, type);
         that->clear();
     }
     return data;
 }
retrieveData_sys()
virtual QVariant QInternalMimeData::retrieveData_sys (const QString & mimeType, QVariant::Type type) const protected pure virtual
Implemented in QCocoaDropData, QDropData, QClipboardWatcher, QXlibClipboardMime, QClipboardWatcher, and QWaylandMimeData.
Referenced by retrieveData().
The documentation for this class was generated from the following files:
/src/gui/kernel/qdnd_p.h
/src/gui/kernel/qdnd.cpp