Qt 4.8: QNetmaskAddress Class Reference
QNetmaskAddress Class Reference
#include <qhostaddress_p.h>
Public Functions
int prefixLength () const
QNetmaskAddress ()
bool setAddress (const QString &address)
bool setAddress (const QHostAddress &address)
void setPrefixLength (QAbstractSocket::NetworkLayerProtocol proto, int len)
Public Functions inherited from QHostAddress
void clear ()
Sets the host address to 0.0.0.0.
bool isInSubnet (const QHostAddress &subnet, int netmask) const
Returns true if this IP is in the subnet described by the network prefix subnet and netmask netmask.
bool isInSubnet (const QPair< QHostAddress, int > &subnet) const
Returns true if this IP is in the subnet described by subnet.
bool isNull () const
Returns true if this host address is null (INADDR_ANY or in6addr_any).
bool operator!= (const QHostAddress &address) const
Returns true if this host address is not the same as the other address given; otherwise returns false.
bool operator!= (SpecialAddress address) const
Returns true if this host address is not the same as the other address given; otherwise returns false.
QHostAddress & operator= (const QHostAddress &other)
Assigns another host address to this object, and returns a reference to this object.
QHostAddress & operator= (const QString &address)
Assigns the host address address to this object, and returns a reference to this object.
bool operator== (const QHostAddress &address) const
Returns true if this host address is the same as the other address given; otherwise returns false.
bool operator== (SpecialAddress address) const
Returns true if this host address is the same as the other address given; otherwise returns false.
QAbstractSocket::NetworkLayerProtocol protocol () const
Returns the network layer protocol of the host address.
QHostAddress ()
Constructs a host address object with the IP address 0.0.0.0.
QHostAddress (quint32 ip4Addr)
Constructs a host address object with the IPv4 address ip4Addr.
QHostAddress (quint8 *ip6Addr)
Constructs a host address object with the IPv6 address ip6Addr.
QHostAddress (const Q_IPV6ADDR &ip6Addr)
Constructs a host address object with the IPv6 address ip6Addr.
QHostAddress (const sockaddr *sockaddr)
Constructs an IPv4 or IPv6 address using the address specified by the native structure sockaddr.
QHostAddress (const QString &address)
Constructs an IPv4 or IPv6 address based on the string address (e.g., "127.0.0.1").
QHostAddress (const QHostAddress &copy)
Constructs a copy of the given address.
QHostAddress (SpecialAddress address)
Constructs a QHostAddress object for address.
QString scopeId () const
Returns the scope ID of an IPv6 address.
void setAddress (quint32 ip4Addr)
Set the IPv4 address specified by ip4Addr.
void setAddress (quint8 *ip6Addr)
Set the IPv6 address specified by ip6Addr.
void setAddress (const Q_IPV6ADDR &ip6Addr)
Set the IPv6 address specified by ip6Addr.
void setAddress (const sockaddr *sockaddr)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Sets the IPv4 or IPv6 address specified by the native structure sockaddr.
bool setAddress (const QString &address)
Sets the IPv4 or IPv6 address specified by the string representation specified by address (e.
void setScopeId (const QString &id)
Sets the IPv6 scope ID of the address to id.
quint32 toIPv4Address () const
Returns the IPv4 address as a number.
Q_IPV6ADDR toIPv6Address () const
Returns the IPv6 address as a Q_IPV6ADDR structure.
QString toString () const
Returns the address as a string.
~QHostAddress ()
Destroys the host address object.
Properties
int length
Additional Inherited Members
Public Types inherited from QHostAddress
enum SpecialAddress {
Null, Broadcast, LocalHost, LocalHostIPv6,
Any, AnyIPv6
}
Static Public Functions inherited from QHostAddress
static QPair< QHostAddress, int > parseSubnet (const QString &subnet)
Parses the IP and subnet information contained in subnet and returns the network prefix for that network and its prefix length.
Protected Variables inherited from QHostAddress
QScopedPointer< QHostAddressPrivate > d
Related Functions inherited from QHostAddress
QDataStream & operator<< (QDataStream &out, const QHostAddress &address)
Writes host address address to the stream out and returns a reference to the stream.
QDataStream & operator>> (QDataStream &in, QHostAddress &address)
Reads a host address into address from the stream in and returns a reference to the stream.
Detailed Description
Definition at line 61 of file qhostaddress_p.h.
Constructors and Destructors
QNetmaskAddress()
QNetmaskAddress::QNetmaskAddress () inline
Definition at line 65 of file qhostaddress_p.h.
 : QHostAddress(), length(-1) { }
Functions
prefixLength()
int QNetmaskAddress::prefixLength () const
Definition at line 388 of file qhostaddress.cpp.
Referenced by QHostAddress::parseSubnet(), QNetworkAddressEntry::prefixLength(), and QNetmaskAddress().
 {
     return length;
 }
setAddress() [1/2]
bool QNetmaskAddress::setAddress (const QString & address)
Definition at line 299 of file qhostaddress.cpp.
Referenced by QHostAddress::parseSubnet(), QNetmaskAddress(), and QNetworkAddressEntry::setNetmask().
 {
     length = -1;
     QHostAddress other;
     return other.setAddress(address) && setAddress(other);
 }
setAddress() [2/2]
bool QNetmaskAddress::setAddress (const QHostAddress & address)
Definition at line 306 of file qhostaddress.cpp.
 {
     static const quint8 zeroes[16] = { 0 };
     union {
         quint32 v4;
         quint8 v6[16];
     } ip;
     int netmask = 0;
     quint8 *ptr = ip.v6;
     quint8 *end;
     length = -1;
     QHostAddress::operator=(address);
     if (d->protocol == QAbstractSocket::IPv4Protocol) {
         ip.v4 = qToBigEndian(d->a);
         end = ptr + 4;
     } else if (d->protocol == QAbstractSocket::IPv6Protocol) {
         memcpy(ip.v6, d->a6.c, 16);
         end = ptr + 16;
     } else {
         d->clear();
         return false;
     }
     while (ptr < end) {
         switch (*ptr) {
         case 255:
             netmask += 8;
             ++ptr;
             continue;
         default:
             d->clear();
             return false;       // invalid IP-style netmask
             // the rest always falls through
         case 254:
             ++netmask;
         case 252:
             ++netmask;
         case 248:
             ++netmask;
         case 240:
             ++netmask;
         case 224:
             ++netmask;
         case 192:
             ++netmask;
         case 128:
             ++netmask;
         case 0:
             break;
         }
         break;
     }
     // confirm that the rest is only zeroes
     if (ptr < end && memcmp(ptr + 1, zeroes, end - ptr - 1) != 0) {
         d->clear();
         return false;
     }
     length = netmask;
     return true;
 }
setPrefixLength()
void QNetmaskAddress::setPrefixLength (QAbstractSocket::NetworkLayerProtocol proto, int len)
Definition at line 393 of file qhostaddress.cpp.
Referenced by QNetmaskAddress(), and QNetworkAddressEntry::setPrefixLength().
 {
     length = newLength;
     if (length < 0 || length > (proto == QAbstractSocket::IPv4Protocol ? 32 :
                                 proto == QAbstractSocket::IPv6Protocol ? 128 : -1)) {
         // invalid information, reject
         d->protocol = QAbstractSocket::UnknownNetworkLayerProtocol;
         length = -1;
         return;
     }
     d->protocol = proto;
     if (d->protocol == QAbstractSocket::IPv4Protocol) {
         if (length == 0) {
             d->a = 0;
         } else if (length == 32) {
             d->a = quint32(0xffffffff);
         } else {
             d->a = quint32(0xffffffff) >> (32 - length) << (32 - length);
         }
     } else {
         memset(d->a6.c, 0xFF, sizeof(d->a6));
         clearBits(d->a6.c, length, 128);
     }
 }
Properties
length
int QNetmaskAddress::length private
Definition at line 63 of file qhostaddress_p.h.
The documentation for this class was generated from the following files:
/src/network/kernel/qhostaddress_p.h
/src/network/kernel/qhostaddress.cpp