Qt 4.8: QLabel Class Reference
QLabel Class Reference
The QLabel widget provides a text or image display.
#include <qlabel.h>
Public Slots
void clear ()
Clears any label contents.
void setMovie (QMovie *movie)
Sets the label contents to movie.
void setNum (int)
Sets the label contents to plain text containing the textual representation of integer num.
void setNum (double)
Sets the label contents to plain text containing the textual representation of double num.
void setPicture (const QPicture &)
Sets the label contents to picture.
void setPixmap (const QPixmap &)
void setText (const QString &)
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void linkActivated (const QString &link)
This signal is emitted when the user clicks a link.
void linkHovered (const QString &link)
This signal is emitted when the user hovers over a link.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
Qt::Alignment alignment () const
QWidget * buddy () const
Returns this label's buddy, or 0 if no buddy is currently set.
bool hasScaledContents () const
bool hasSelectedText () const
int heightForWidth (int) const
Reimplemented Function
int indent () const
int margin () const
QSize minimumSizeHint () const
Reimplemented Function
QMovie * movie () const
Returns a pointer to the label's movie, or 0 if no movie has been set.
bool openExternalLinks () const
const QPicture * picture () const
Returns the label's picture or 0 if the label doesn't have a picture.
const QPixmap * pixmap () const
QLabel (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs an empty label.
QLabel (const QString &text, QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a label that displays the text, text.
QString selectedText () const
int selectionStart () const
selectionStart() returns the index of the first selected character in the label or -1 if no text is selected.
void setAlignment (Qt::Alignment)
Without this function, a call to e.
void setBuddy (QWidget *)
Sets this label's buddy to buddy.
void setIndent (int)
void setMargin (int)
void setOpenExternalLinks (bool open)
void setScaledContents (bool)
void setSelection (int, int)
Selects text from position start and for length characters.
void setTextFormat (Qt::TextFormat)
void setTextInteractionFlags (Qt::TextInteractionFlags flags)
void setWordWrap (bool on)
QSize sizeHint () const
em>Reimplemented Function
QString text () const
Qt::TextFormat textFormat () const
Qt::TextInteractionFlags textInteractionFlags () const
bool wordWrap () const
~QLabel ()
Destroys the label.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *)
Reimplemented Function
void contextMenuEvent (QContextMenuEvent *ev)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
bool event (QEvent *e)
em>Reimplemented Function
void focusInEvent (QFocusEvent *ev)
Reimplemented Function
bool focusNextPrevChild (bool next)
em>Reimplemented Function
void focusOutEvent (QFocusEvent *ev)
Reimplemented Function
void keyPressEvent (QKeyEvent *ev)
em>Reimplemented Function
void mouseMoveEvent (QMouseEvent *ev)
em>Reimplemented Function
void mousePressEvent (QMouseEvent *ev)
em>Reimplemented Function
void mouseReleaseEvent (QMouseEvent *ev)
em>Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
Protected Functions inherited from QFrame
void drawFrame (QPainter *)
em>Reimplemented Function
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
Qt::Alignment alignment
the alignment of the label's contents
bool hasSelectedText
whether there is any text selected
int indent
the label's text indent in pixels
int margin
the width of the margin
bool openExternalLinks
Specifies whether QLabel should automatically open links using QDesktopServices::openUrl() instead of emitting the linkActivated() signal.
QPixmap pixmap
the label's pixmap
bool scaledContents
whether the label will scale its contents to fill all available space.
QString selectedText
the selected text
QString text
the label's text
Qt::TextFormat textFormat
the label's text format
Qt::TextInteractionFlags textInteractionFlags
Specifies how the label should interact with user input if it displays text.
bool wordWrap
the label's word-wrapping policy
Friends
class QBalloonTip
class QMessageBoxPrivate
class QTipLabel
Additional Inherited Members
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QLabel widget provides a text or image display.
QLabel is used for displaying text or an image. No user interaction functionality is provided. The visual appearance of the label can be configured in various ways, and it can be used for specifying a focus mnemonic key for another widget.
A QLabel can contain any of the following content types:
Content Setting
Plain text Pass a QString to setText().
Rich text Pass a QString that contains rich text to setText().
A pixmap Pass a QPixmap to setPixmap().
A movie Pass a QMovie to setMovie().
A number Pass an int or a double to setNum(), which converts the number to plain text.
Nothing The same as an empty plain text. This is the default. Set by clear().
Warning
When passing a QString to the constructor or calling setText(), make sure to sanitize your input, as QLabel tries to guess whether it displays the text as plain text or as rich text. You may want to call setTextFormat() explicitly, e.g. in case you expect the text to be in plain format but cannot control the text source (for instance when displaying data loaded from the Web).
When the content is changed using any of these functions, any previous content is cleared.
By default, labels display left-aligned, vertically-centered text and images, where any tabs in the text to be displayed are automatically expanded. However, the look of a QLabel can be adjusted and fine-tuned in several ways.
The positioning of the content within the QLabel widget area can be tuned with setAlignment() and setIndent(). Text content can also wrap lines along word boundaries with setWordWrap(). For example, this code sets up a sunken panel with a two-line text in the bottom right corner (both lines being flush with the right side of the label):
QLabel *label = new QLabel(this);
label->setFrameStyle(QFrame::Panel | QFrame::Sunken);
label->setText("first line\nsecond line");
label->setAlignment(Qt::AlignBottom | Qt::AlignRight);
The properties and functions QLabel inherits from QFrame can also be used to specify the widget frame to be used for any given label.
A QLabel is often used as a label for an interactive widget. For this use QLabel provides a useful mechanism for adding an mnemonic (see QKeySequence) that will set the keyboard focus to the other widget (called the QLabel's "buddy"). For example:
QLineEdit* phoneEdit = new QLineEdit(this);
QLabel* phoneLabel = new QLabel("&Phone:", this);
phoneLabel->setBuddy(phoneEdit);
In this example, keyboard focus is transferred to the label's buddy (the QLineEdit) when the user presses Alt+P. If the buddy was a button (inheriting from QAbstractButton), triggering the mnemonic would emulate a button click.
Screenshot of a Macintosh style label
A label shown in the Macintosh Style Widget Gallery{Macintosh widget style}.
Screenshot of a Plastique style label
A label shown in the Plastique Style Widget Gallery{Plastique widget style}.
Screenshot of a Windows XP style label
A label shown in the Windows XP Style Widget Gallery{Windows XP widget style}.
See also
QLineEdit, QTextEdit, QPixmap, QMovie, {fowler}{GUI Design Handbook: Label}
Definition at line 55 of file qlabel.h.
Constructors and Destructors
QLabel() [1/2]
QLabel::QLabel (QWidget * parent = 0, Qt::WindowFlags f = 0) explicit
Constructs an empty label.
The parent and widget flag f, arguments are passed to the QFrame constructor.
See also
setAlignment(), setFrameStyle(), setIndent()
Definition at line 179 of file qlabel.cpp.
Referenced by QLabel().
     : QFrame(*new QLabelPrivate(), parent, f)
 {
     Q_D(QLabel);
     d->init();
 }
QLabel() [2/2]
QLabel::QLabel (const QString & text, QWidget * parent = 0, Qt::WindowFlags f = 0) explicit
Constructs a label that displays the text, text.
The parent and widget flag f, arguments are passed to the QFrame constructor.
See also
setText(), setAlignment(), setFrameStyle(), setIndent()
Definition at line 194 of file qlabel.cpp.
         : QFrame(*new QLabelPrivate(), parent, f)
 {
     Q_D(QLabel);
     d->init();
     setText(text);
 }
~QLabel()
QLabel::~QLabel ()
Destroys the label.
Definition at line 286 of file qlabel.cpp.
 {
     Q_D(QLabel);
     d->clearContents();
 }
Functions
alignment()
Qt::Alignment QLabel::alignment () const
Referenced by setAlignment().
buddy()
QWidget * QLabel::buddy () const
Returns this label's buddy, or 0 if no buddy is currently set.
See also
setBuddy()
Definition at line 1319 of file qlabel.cpp.
Referenced by buddyString(), QAccessibleDisplay::navigate(), QLabel(), QAccessibleDisplay::relationTo(), and setBuddy().
 {
     Q_D(const QLabel);
     return d->buddy;
 }
changeEvent()
void QLabel::changeEvent (QEvent * ev) protected virtual
Reimplemented Function
Reimplemented from QFrame.
Definition at line 1513 of file qlabel.cpp.
 {
     Q_D(QLabel);
     if(ev->type() == QEvent::FontChange || ev->type() == QEvent::ApplicationFontChange) {
         if (d->isTextLabel) {
             if (d->control)
                 d->control->document()->setDefaultFont(font());
             d->updateLabel();
         }
     } else if (ev->type() == QEvent::PaletteChange && d->control) {
         d->control->setPalette(palette());
     } else if (ev->type() == QEvent::ContentsRectChange) {
         d->updateLabel();
     }
     QFrame::changeEvent(ev);
 }
clear
void QLabel::clear () slot
Clears any label contents.
Definition at line 420 of file qlabel.cpp.
 {
     Q_D(QLabel);
     d->clearContents();
     d->updateLabel();
 }
contextMenuEvent()
void QLabel::contextMenuEvent (QContextMenuEvent * event) protected virtual
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
The handler is called when the widget's contextMenuPolicy is Qt::DefaultContextMenu.
The default implementation ignores the context event. See the QContextMenuEvent documentation for more details.
See also
event(), QContextMenuEvent customContextMenuRequested()
Reimplemented from QWidget.
Reimplemented in QmlJSDebugger::ToolBarColorBox.
Definition at line 1010 of file qlabel.cpp.
 {
 #ifdef QT_NO_CONTEXTMENU
     Q_UNUSED(ev);
 #else
     Q_D(QLabel);
     if (!d->isTextLabel) {
         ev->ignore();
         return;
     }
     QMenu *menu = d->createStandardContextMenu(ev->pos());
     if (!menu) {
         ev->ignore();
         return;
     }
     ev->accept();
     menu->setAttribute(Qt::WA_DeleteOnClose);
     menu->popup(ev->globalPos());
 #endif
 }
event()
bool QLabel::event (QEvent * e) protected virtual
em>Reimplemented Function
Reimplemented from QFrame.
Definition at line 1085 of file qlabel.cpp.
focusInEvent()
void QLabel::focusInEvent (QFocusEvent * ev) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1034 of file qlabel.cpp.
 {
     Q_D(QLabel);
     if (d->isTextLabel) {
         d->ensureTextControl();
         d->sendControlEvent(ev);
     }
     QFrame::focusInEvent(ev);
 }
focusNextPrevChild()
bool QLabel::focusNextPrevChild (bool next) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1067 of file qlabel.cpp.
focusOutEvent()
void QLabel::focusOutEvent (QFocusEvent * ev) protected virtual
Reimplemented Function
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1047 of file qlabel.cpp.
hasScaledContents()
bool QLabel::hasScaledContents () const
Definition at line 1543 of file qlabel.cpp.
 {
     Q_D(const QLabel);
     return d->scaledcontents;
 }
hasSelectedText()
bool QLabel::hasSelectedText () const
Referenced by setSelection().
heightForWidth()
int QLabel::heightForWidth (int w) const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 765 of file qlabel.cpp.
Referenced by QBalloonTip::QBalloonTip(), and QWizardHeader::setup().
 {
     Q_D(const QLabel);
     if (d->isTextLabel)
         return d->sizeForWidth(w).height();
     return QWidget::heightForWidth(w);
 }
indent()
int QLabel::indent () const
Referenced by QLabelPrivate::documentRect(), QLabelPrivate::init(), setIndent(), and QLabelPrivate::sizeForWidth().
keyPressEvent()
void QLabel::keyPressEvent (QKeyEvent * ev) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1077 of file qlabel.cpp.
linkActivated
void QLabel::linkActivated (const QString & link) signal
This signal is emitted when the user clicks a link.
Since
4.2
The URL referred to by the anchor is passed in link.
See also
linkHovered()
Referenced by QLabelPrivate::ensureTextControl().
linkHovered
void QLabel::linkHovered (const QString & link) signal
This signal is emitted when the user hovers over a link.
Since
4.2
The URL referred to by the anchor is passed in link.
See also
linkActivated()
Referenced by QLabelPrivate::ensureTextControl().
margin()
int QLabel::margin () const
Referenced by QLabelPrivate::documentRect(), QLabelPrivate::init(), setIndent(), setMargin(), and QLabelPrivate::sizeForWidth().
minimumSizeHint()
QSize QLabel::minimumSizeHint () const virtual
Reimplemented Function
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 958 of file qlabel.cpp.
mouseMoveEvent()
void QLabel::mouseMoveEvent (QMouseEvent * ev) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QmlJSDebugger::ToolBarColorBox.
Definition at line 994 of file qlabel.cpp.
Referenced by QTipLabel::mouseMoveEvent().
mousePressEvent()
void QLabel::mousePressEvent (QMouseEvent * ev) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QmlJSDebugger::ToolBarColorBox.
Definition at line 986 of file qlabel.cpp.
mouseReleaseEvent()
void QLabel::mouseReleaseEvent (QMouseEvent * ev) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1002 of file qlabel.cpp.
movie()
QMovie * QLabel::movie () const
Returns a pointer to the label's movie, or 0 if no movie has been set.
See also
setMovie()
Definition at line 1468 of file qlabel.cpp.
Referenced by QLabelPrivate::_q_movieUpdated(), QLabelPrivate::clearContents(), QLabelPrivate::init(), QAccessibleDisplay::role(), setMovie(), and QLabelPrivate::sizeForWidth().
 {
     Q_D(const QLabel);
     return d->movie;
 }
openExternalLinks()
bool QLabel::openExternalLinks () const
Referenced by QLabelPrivate::ensureTextControl(), heightForWidth(), and QLabelPrivate::init().
paintEvent()
void QLabel::paintEvent (QPaintEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive paint events passed in event.
A paint event is a request to repaint all or part of a widget. It can happen for one of the following reasons:
repaint() or update() was invoked,
the widget was obscured and has now been uncovered, or
many other reasons.
Many widgets can simply repaint their entire surface when asked to, but some slow widgets need to optimize by painting only the requested region: QPaintEvent::region(). This speed optimization does not change the result, as painting is clipped to that region during event processing. QListView and QTableView do this, for example.
Qt also tries to speed up painting by merging multiple paint events into one. When update() is called several times or the window system sends several paint events, Qt merges these events into one event with a larger region (see QRegion::united()). The repaint() function does not permit this optimization, so we suggest using update() whenever possible.
When the paint event occurs, the update region has normally been erased, so you are painting on the widget's background.
The background can be set using setBackgroundRole() and setPalette().
Since Qt 4.0, QWidget automatically double-buffers its painting, so there is no need to write double-buffering code in paintEvent() to avoid flicker.
Note for the X11 platform: It is possible to toggle global double buffering by calling qt_x11_set_global_double_buffer(). For example,
...
extern void qt_x11_set_global_double_buffer(bool);
qt_x11_set_global_double_buffer(false);
...
Note
Generally, you should refrain from calling update() or repaint() inside a paintEvent(). For example, calling update() or repaint() on children inside a paintevent() results in undefined behavior; the child may or may not get a paint event.
Warning
If you are using a custom paint engine without Qt's backingstore, Qt::WA_PaintOnScreen must be set. Otherwise, QWidget::paintEngine() will never be called; the backingstore will be used instead.
See also
event(), repaint(), update(), QPainter, QPixmap, QPaintEvent, {Analog Clock Example}
Reimplemented from QFrame.
Definition at line 1123 of file qlabel.cpp.
Referenced by QTipLabel::paintEvent().
 {
     Q_D(QLabel);
     QStyle *style = QWidget::style();
     QPainter painter(this);
     drawFrame(&painter);
     QRect cr = contentsRect();
     cr.adjust(d->margin, d->margin, -d->margin, -d->margin);
     int align = QStyle::visualAlignment(d->isTextLabel ? d->textDirection()
                                                        : layoutDirection(), QFlag(d->align));
 #ifndef QT_NO_MOVIE
     if (d->movie) {
         if (d->scaledcontents)
             style->drawItemPixmap(&painter, cr, align, d->movie->currentPixmap().scaled(cr.size()));
         else
             style->drawItemPixmap(&painter, cr, align, d->movie->currentPixmap());
     }
     else
 #endif
     if (d->isTextLabel) {
         QRectF lr = d->layoutRect().toAlignedRect();
         QStyleOption opt;
         opt.initFrom(this);
 #ifndef QT_NO_STYLE_STYLESHEET
         if (QStyleSheetStyle* cssStyle = qobject_cast<QStyleSheetStyle*>(style)) {
             cssStyle->styleSheetPalette(this, &opt, &opt.palette);
         }
 #endif
         if (d->control) {
 #ifndef QT_NO_SHORTCUT
             const bool underline = (bool)style->styleHint(QStyle::SH_UnderlineShortcut, 0, this, 0);
             if (d->shortcutId != 0
                 && underline != d->shortcutCursor.charFormat().fontUnderline()) {
                 QTextCharFormat fmt;
                 fmt.setFontUnderline(underline);
                 d->shortcutCursor.mergeCharFormat(fmt);
             }
 #endif
             d->ensureTextLayouted();
             QAbstractTextDocumentLayout::PaintContext context;
             if (!isEnabled() && !d->control &&
                 // We cannot support etched for rich text controls because custom
                 // colors and links will override the light palette
                 style->styleHint(QStyle::SH_EtchDisabledText, &opt, this)) {
                 context.palette = opt.palette;
                 context.palette.setColor(QPalette::Text, context.palette.light().color());
                 painter.save();
                 painter.translate(lr.x() + 1, lr.y() + 1);
                 painter.setClipRect(lr.translated(-lr.x() - 1, -lr.y() - 1));
                 QAbstractTextDocumentLayout *layout = d->control->document()->documentLayout();
                 layout->draw(&painter, context);
                 painter.restore();
             }
             // Adjust the palette
             context.palette = opt.palette;
             if (foregroundRole() != QPalette::Text && isEnabled())
                 context.palette.setColor(QPalette::Text, context.palette.color(foregroundRole()));
             painter.save();
             painter.translate(lr.topLeft());
             painter.setClipRect(lr.translated(-lr.x(), -lr.y()));
             d->control->setPalette(context.palette);
             d->control->drawContents(&painter, QRectF(), this);
             painter.restore();
         } else {
             int flags = align | (d->textDirection() == Qt::LeftToRight ? Qt::TextForceLeftToRight
                                                                        : Qt::TextForceRightToLeft);
             if (d->hasShortcut) {
                 flags |= Qt::TextShowMnemonic;
                 if (!style->styleHint(QStyle::SH_UnderlineShortcut, &opt, this))
                     flags |= Qt::TextHideMnemonic;
             }
             style->drawItemText(&painter, lr.toRect(), flags, opt.palette, isEnabled(), d->text, foregroundRole());
         }
     } else
 #ifndef QT_NO_PICTURE
     if (d->picture) {
         QRect br = d->picture->boundingRect();
         int rw = br.width();
         int rh = br.height();
         if (d->scaledcontents) {
             painter.save();
             painter.translate(cr.x(), cr.y());
             painter.scale((double)cr.width()/rw, (double)cr.height()/rh);
             painter.drawPicture(-br.x(), -br.y(), *d->picture);
             painter.restore();
         } else {
             int xo = 0;
             int yo = 0;
             if (align & Qt::AlignVCenter)
                 yo = (cr.height()-rh)/2;
             else if (align & Qt::AlignBottom)
                 yo = cr.height()-rh;
             if (align & Qt::AlignRight)
                 xo = cr.width()-rw;
             else if (align & Qt::AlignHCenter)
                 xo = (cr.width()-rw)/2;
             painter.drawPicture(cr.x()+xo-br.x(), cr.y()+yo-br.y(), *d->picture);
         }
     } else
 #endif
     if (d->pixmap && !d->pixmap->isNull()) {
         QPixmap pix;
         if (d->scaledcontents) {
             if (!d->scaledpixmap || d->scaledpixmap->size() != cr.size()) {
                 if (!d->cachedimage)
                     d->cachedimage = new QImage(d->pixmap->toImage());
                 delete d->scaledpixmap;
                 d->scaledpixmap = new QPixmap(QPixmap::fromImage(d->cachedimage->scaled(cr.size(),Qt::IgnoreAspectRatio,Qt::SmoothTransformation)));
             }
             pix = *d->scaledpixmap;
         } else
             pix = *d->pixmap;
         QStyleOption opt;
         opt.initFrom(this);
         if (!isEnabled())
             pix = style->generatedIconPixmap(QIcon::Disabled, pix, &opt);
         style->drawItemPixmap(&painter, cr, align, pix);
     }
 }
picture()
const QPicture * QLabel::picture () const
Returns the label's picture or 0 if the label doesn't have a picture.
Definition at line 163 of file qlabel.cpp.
Referenced by QLabelPrivate::clearContents(), QLabelPrivate::init(), QAccessibleDisplay::role(), and QLabelPrivate::sizeForWidth().
 {
     Q_D(const QLabel);
     return d->picture;
 }
pixmap()
const QPixmap* QLabel::pixmap () const
Referenced by QLabelPrivate::clearContents(), QLabelPrivate::init(), setPixmap(), and QLabelPrivate::sizeForWidth().
selectedText()
QString QLabel::selectedText () const
Referenced by setSelection().
selectionStart()
int QLabel::selectionStart () const
selectionStart() returns the index of the first selected character in the label or -1 if no text is selected.
See also
selectedText()
Note: The textInteractionFlags set on the label need to include either TextSelectableByMouse or TextSelectableByKeyboard.
Since
4.7em>Reimplemented Function
Definition at line 937 of file qlabel.cpp.
setAlignment()
void QLabel::setAlignment (Qt::Alignment alignment)
Without this function, a call to e.
Warning
This function is not part of the public interface.
g. setAlignment(Qt::AlignTop) results in the QT3_SUPPORT function setAlignment(int) being called, rather than setAlignment(Qt::Alignment).
Definition at line 532 of file qlabel.cpp.
Referenced by QProgressDialogPrivate::init(), QBalloonTip::QBalloonTip(), QColorShower::QColorShower(), QTipLabel::QTipLabel(), QWizardHeader::QWizardHeader(), QMessageBox::setInformativeText(), and QCoreFuriCuri::timerEvent().
 {
     Q_D(QLabel);
     if (alignment == (d->align & (Qt::AlignVertical_Mask|Qt::AlignHorizontal_Mask)))
         return;
     d->align = (d->align & ~(Qt::AlignVertical_Mask|Qt::AlignHorizontal_Mask))
                | (alignment & (Qt::AlignVertical_Mask|Qt::AlignHorizontal_Mask));
     d->updateLabel();
 }
setBuddy()
void QLabel::setBuddy (QWidget * buddy)
Sets this label's buddy to buddy.
When the user presses the shortcut key indicated by this label, the keyboard focus is transferred to the label's buddy widget.
The buddy mechanism is only available for QLabels that contain text in which one character is prefixed with an ampersand, '&'. This character is set as the shortcut key. See the QKeySequence::mnemonic() documentation for details (to display an actual ampersand, use '&&').
In a dialog, you might create two data entry widgets and a label for each, and set up the geometry layout so each label is just to the left of its data entry widget (its "buddy"), for example:
QLineEdit *nameEd  = new QLineEdit(this);
QLabel    *nameLb  = new QLabel("&Name:", this);
nameLb->setBuddy(nameEd);
QLineEdit *phoneEd = new QLineEdit(this);
QLabel    *phoneLb = new QLabel("&Phone:", this);
phoneLb->setBuddy(phoneEd);
// (layout setup not shown)
With the code above, the focus jumps to the Name field when the user presses Alt+N, and to the Phone field when the user presses Alt+P.
To unset a previously set buddy, call this function with buddy set to 0.
See also
buddy(), setText(), QShortcut, setAlignment()
Definition at line 1297 of file qlabel.cpp.
Referenced by QInputDialogPrivate::ensureLayout(), QFormLayout::insertRow(), QColorShower::QColorShower(), and QLabel().
 {
     Q_D(QLabel);
     d->buddy = buddy;
     if (d->isTextLabel) {
         if (d->shortcutId)
             releaseShortcut(d->shortcutId);
         d->shortcutId = 0;
         d->textDirty = true;
         if (buddy)
             d->updateShortcut(); // grab new shortcut
         d->updateLabel();
     }
 }
setIndent()
void QLabel::setIndent (int indent)
Definition at line 620 of file qlabel.cpp.
Referenced by QTipLabel::QTipLabel(), QWizardPrivate::recreateLayout(), and QMessageBox::setInformativeText().
 {
     Q_D(QLabel);
     d->indent = indent;
     d->updateLabel();
 }
setMargin()
void QLabel::setMargin (int margin)
Definition at line 654 of file qlabel.cpp.
Referenced by QBalloonTip::QBalloonTip(), and QTipLabel::QTipLabel().
 {
     Q_D(QLabel);
     if (d->margin == margin)
         return;
     d->margin = margin;
     d->updateLabel();
 }
setMovie
void QLabel::setMovie (QMovie * movie) slot
Sets the label contents to movie.
Any previous content is cleared. The label does NOT take ownership of the movie.
The buddy shortcut, if any, is disabled.
See also
movie(), setBuddy()
Definition at line 1385 of file qlabel.cpp.
 {
     Q_D(QLabel);
     d->clearContents();
     if (!movie)
         return;
     d->movie = movie;
     connect(movie, SIGNAL(resized(QSize)), this, SLOT(_q_movieResized(QSize)));
     connect(movie, SIGNAL(updated(QRect)), this, SLOT(_q_movieUpdated(QRect)));
     // Assume that if the movie is running,
     // resize/update signals will come soon enough
     if (movie->state() != QMovie::Running)
         d->updateLabel();
 }
setNum [1/2]
void QLabel::setNum (int num) slot
Sets the label contents to plain text containing the textual representation of integer num.
Any previous content is cleared. Does nothing if the integer's string representation is the same as the current contents of the label.
The buddy shortcut, if any, is disabled.
See also
setText(), QString::setNum(), setBuddy()
Definition at line 490 of file qlabel.cpp.
 {
     QString str;
     str.setNum(num);
     setText(str);
 }
setNum [2/2]
void QLabel::setNum (double num) slot
Sets the label contents to plain text containing the textual representation of double num.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Any previous content is cleared. Does nothing if the double's string representation is the same as the current contents of the label.
The buddy shortcut, if any, is disabled.
See also
setText(), QString::setNum(), setBuddy()
Definition at line 513 of file qlabel.cpp.
 {
     QString str;
     str.setNum(num);
     setText(str);
 }
setOpenExternalLinks()
void QLabel::setOpenExternalLinks (bool open)
Definition at line 797 of file qlabel.cpp.
Referenced by QMessageBox::setInformativeText().
 {
     Q_D(QLabel);
     d->openExternalLinks = open;
     if (d->control)
         d->control->setOpenExternalLinks(open);
 }
setPicture
void QLabel::setPicture (const QPicture & picture) slot
Sets the label contents to picture.
Any previous content is cleared.
The buddy shortcut, if any, is disabled.
See also
picture(), setBuddy()
Definition at line 469 of file qlabel.cpp.
 {
     Q_D(QLabel);
     d->clearContents();
     d->picture = new QPicture(picture);
     d->updateLabel();
 }
setPixmap
void QLabel::setPixmap (const QPixmap & pixmap) slot
Definition at line 439 of file qlabel.cpp.
Referenced by QBalloonTip::QBalloonTip(), QmlJSDebugger::ToolBarColorBox::setColor(), QWizardHeader::setup(), and QCoreFuriCuri::timerEvent().
 {
     Q_D(QLabel);
     if (!d->pixmap || d->pixmap->cacheKey() != pixmap.cacheKey()) {
         d->clearContents();
         d->pixmap = new QPixmap(pixmap);
     }
     if (d->pixmap->depth() == 1 && !d->pixmap->mask())
         d->pixmap->setMask(*((QBitmap *)d->pixmap));
     d->updateLabel();
 }
setScaledContents()
void QLabel::setScaledContents (bool enable)
Definition at line 1549 of file qlabel.cpp.
Referenced by QmlJSDebugger::ToolBarColorBox::ToolBarColorBox().
 {
     Q_D(QLabel);
     if ((bool)d->scaledcontents == enable)
         return;
     d->scaledcontents = enable;
     if (!enable) {
         delete d->scaledpixmap;
         d->scaledpixmap = 0;
         delete d->cachedimage;
         d->cachedimage = 0;
     }
     update(contentsRect());
 }
setSelection()
void QLabel::setSelection (int start, int length)
Selects text from position start and for length characters.
See also
selectedText()
Note: The textInteractionFlags set on the label need to include either TextSelectableByMouse or TextSelectableByKeyboard.
Since
4.7
Definition at line 860 of file qlabel.cpp.
 {
     Q_D(QLabel);
     if (d->control) {
         d->ensureTextPopulated();
         QTextCursor cursor = d->control->textCursor();
         cursor.setPosition(start);
         cursor.setPosition(start + length, QTextCursor::KeepAnchor);
         d->control->setTextCursor(cursor);
     }
 }
setText
void QLabel::setText (const QString & text) slot
Definition at line 366 of file qlabel.cpp.
Referenced by QBalloonTip::QBalloonTip(), QLabel(), QColorShower::retranslateStrings(), QTipLabel::reuseTip(), setNum(), setTextFormat(), QWizardHeader::setup(), and QWizardPrivate::updateLayout().
 {
     Q_D(QLabel);
     if (d->text == text)
         return;
     QTextControl *oldControl = d->control;
     d->control = 0;
     d->clearContents();
     d->text = text;
     d->isTextLabel = true;
     d->textDirty = true;
     d->isRichText = d->textformat == Qt::RichText
                     || (d->textformat == Qt::AutoText && Qt::mightBeRichText(d->text));
     d->control = oldControl;
     if (d->needTextControl()) {
         d->ensureTextControl();
     } else {
         delete d->control;
         d->control = 0;
     }
     if (d->isRichText) {
         setMouseTracking(true);
     } else {
         // Note: mouse tracking not disabled intentionally
     }
 #ifndef QT_NO_SHORTCUT
     if (d->buddy)
         d->updateShortcut();
 #endif
     d->updateLabel();
 #ifndef QT_NO_ACCESSIBILITY
     if (accessibleName().isEmpty())
         QAccessible::updateAccessibility(this, 0, QAccessible::NameChanged);
 #endif
 }
setTextFormat()
void QLabel::setTextFormat (Qt::TextFormat format)
Definition at line 1497 of file qlabel.cpp.
Referenced by QBalloonTip::QBalloonTip(), QWizardHeader::setup(), and QWizardPrivate::updateLayout().
 {
     Q_D(QLabel);
     if (format != d->textformat) {
         d->textformat = format;
         QString t = d->text;
         if (!t.isNull()) {
             d->text.clear();
             setText(t);
         }
     }
 }
setTextInteractionFlags()
void QLabel::setTextInteractionFlags (Qt::TextInteractionFlags flags)
Definition at line 820 of file qlabel.cpp.
Referenced by QMessageBox::setInformativeText().
 {
     Q_D(QLabel);
     if (d->textInteractionFlags == flags)
         return;
     d->textInteractionFlags = flags;
     if (flags & Qt::LinksAccessibleByKeyboard)
         setFocusPolicy(Qt::StrongFocus);
     else if (flags & (Qt::TextSelectableByKeyboard | Qt::TextSelectableByMouse))
         setFocusPolicy(Qt::ClickFocus);
     else
         setFocusPolicy(Qt::NoFocus);
     if (d->needTextControl()) {
         d->ensureTextControl();
     } else {
         delete d->control;
         d->control = 0;
     }
     if (d->control)
         d->control->setTextInteractionFlags(d->textInteractionFlags);
 }
setWordWrap()
void QLabel::setWordWrap (bool on)
Definition at line 579 of file qlabel.cpp.
Referenced by QBalloonTip::QBalloonTip(), QWizardHeader::QWizardHeader(), QWizardPrivate::recreateLayout(), QTipLabel::reuseTip(), and QMessageBox::setInformativeText().
 {
     Q_D(QLabel);
     if (on)
         d->align |= Qt::TextWordWrap;
     else
         d->align &= ~Qt::TextWordWrap;
     d->updateLabel();
 }
sizeHint()
QSize QLabel::sizeHint () const virtual
em>Reimplemented Function
Reimplemented from QFrame.
Definition at line 947 of file qlabel.cpp.
Referenced by QBalloonTip::QBalloonTip(), QTipLabel::reuseTip(), and QWizardHeader::setup().
 {
     Q_D(const QLabel);
     if (!d->valid_hints)
         (void) QLabel::minimumSizeHint();
     return d->sh;
 }
text()
QString QLabel::text () const
Referenced by QLabel(), QTipLabel::restartExpireTimer(), setText(), QToolTip::text(), and QTipLabel::tipChanged().
textFormat()
Qt::TextFormat QLabel::textFormat () const
Referenced by movie().
textInteractionFlags()
Qt::TextInteractionFlags QLabel::textInteractionFlags () const
Referenced by QLabelPrivate::ensureTextControl(), QLabelPrivate::init(), QLabelPrivate::sendControlEvent(), and setTextInteractionFlags().
wordWrap()
bool QLabel::wordWrap () const
Referenced by setWordWrap().
Friends and Related Functions
QBalloonTip
friend class QBalloonTip friend
Definition at line 175 of file qlabel.h.
QMessageBoxPrivate
friend class QMessageBoxPrivate friend
Definition at line 174 of file qlabel.h.
QTipLabel
friend class QTipLabel friend
Definition at line 173 of file qlabel.h.
Properties
alignment
Qt::Alignment QLabel::alignment private
the alignment of the label's contents
By default, the contents of the label are left-aligned and vertically-centered.
See also
text
Definition at line 62 of file qlabel.h.
hasSelectedText
bool QLabel::hasSelectedText private
whether there is any text selected
hasSelectedText() returns true if some or all of the text has been selected by the user; otherwise returns false.
By default, this property is false.
See also
selectedText()
Note: The textInteractionFlags set on the label need to include either TextSelectableByMouse or TextSelectableByKeyboard.
Since
4.7
Definition at line 68 of file qlabel.h.
indent
int QLabel::indent private
the label's text indent in pixels
If a label displays text, the indent applies to the left edge if alignment() is Qt::AlignLeft, to the right edge if alignment() is Qt::AlignRight, to the top edge if alignment() is Qt::AlignTop, and to to the bottom edge if alignment() is Qt::AlignBottom.
If indent is negative, or if no indent has been set, the label computes the effective indent as follows: If frameWidth() is 0, the effective indent becomes 0. If frameWidth() is greater than 0, the effective indent becomes half the width of the "x" character of the widget's current font().
By default, the indent is -1, meaning that an effective indent is calculating in the manner described above.
See also
alignment, margin, frameWidth(), font()
Definition at line 65 of file qlabel.h.
margin
int QLabel::margin private
the width of the margin
The margin is the distance between the innermost pixel of the frame and the outermost pixel of contents.
The default margin is 0.
See also
indent
Definition at line 64 of file qlabel.h.
openExternalLinks
bool QLabel::openExternalLinks private
Specifies whether QLabel should automatically open links using QDesktopServices::openUrl() instead of emitting the linkActivated() signal.
Since
4.2
Note: The textInteractionFlags set on the label need to include either LinksAccessibleByMouse or LinksAccessibleByKeyboard.
The default value is false.
See also
textInteractionFlags()
Definition at line 66 of file qlabel.h.
pixmap
const QPixmap * QLabel::pixmap private
the label's pixmap
If no pixmap has been set this will return 0.
Setting the pixmap clears any previous content. The buddy shortcut, if any, is disabled.
Definition at line 60 of file qlabel.h.
Referenced by QAccessibleDisplay::imagePosition(), QAccessibleDisplay::imageSize(), and QAccessibleDisplay::role().
scaledContents
QLabel::scaledContents private
whether the label will scale its contents to fill all available space.
When enabled and the label shows a pixmap, it will scale the pixmap to fill the available space.
This property's default is false.
Definition at line 61 of file qlabel.h.
selectedText
QString QLabel::selectedText private
the selected text
If there is no selected text this property's value is an empty string.
By default, this property contains an empty string.
See also
hasSelectedText()
Note: The textInteractionFlags set on the label need to include either TextSelectableByMouse or TextSelectableByKeyboard.
Since
4.7
Definition at line 69 of file qlabel.h.
text
QString QLabel::text private
the label's text
If no text has been set this will return an empty string. Setting the text clears any previous content.
The text will be interpreted either as plain text or as rich text, depending on the text format setting; see setTextFormat(). The default setting is Qt::AutoText; i.e. QLabel will try to auto-detect the format of the text set.
If a buddy has been set, the buddy mnemonic key is updated from the new text.
Note that QLabel is well-suited to display small rich text documents, such as small documents that get their document specific settings (font, text color, link color) from the label's palette and font properties. For large documents, use QTextEdit in read-only mode instead. QTextEdit can also provide a scroll bar when necessary.
Note
This function enables mouse tracking if text contains rich text.
See also
setTextFormat(), setBuddy(), alignment
Definition at line 58 of file qlabel.h.
Referenced by buddyString(), and QAccessibleDisplay::text().
textFormat
Qt::TextFormat QLabel::textFormat private
the label's text format
See the Qt::TextFormat enum for an explanation of the possible options.
The default format is Qt::AutoText.
See also
text()
Definition at line 59 of file qlabel.h.
Referenced by QAccessibleDisplay::text().
textInteractionFlags
Qt::TextInteractionFlags QLabel::textInteractionFlags private
Specifies how the label should interact with user input if it displays text.
Since
4.2
If the flags contain Qt::LinksAccessibleByKeyboard the focus policy is also automatically set to Qt::StrongFocus. If Qt::TextSelectableByKeyboard is set then the focus policy is set to Qt::ClickFocus.
The default value is Qt::LinksAccessibleByMouse.
Definition at line 67 of file qlabel.h.
wordWrap
bool QLabel::wordWrap private
the label's word-wrapping policy
If this property is true then label text is wrapped where necessary at word-breaks; otherwise it is not wrapped at all.
By default, word wrap is disabled.
See also
text
Definition at line 63 of file qlabel.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qlabel.h
/src/gui/widgets/qlabel.cpp