Qt 4.8: QPatternist::AutoPtr< T > Class Template Reference
QPatternist::AutoPtr< T > Class Template Reference
A smart pointer very similar to std::auto_ptr.
#include <qautoptr_p.h>
Public Functions
AutoPtr (T *pointer=0)
AutoPtr (AutoPtr< T > &other)
AutoPtr (AutoPtrRef< T > ref)
template<typename L >
AutoPtr (AutoPtr< L > &other)
T * data () const
template<typename L >
operator AutoPtr< L > ()
template<typename L >
operator AutoPtrRef< L > ()
operator bool () const
bool operator! () const
T & operator* () const
T * operator-> () const
AutoPtr & operator= (AutoPtrRef< T > ref)
AutoPtr & operator= (AutoPtr &other)
T * release ()
void reset (T *other=0)
~AutoPtr ()
Properties
T * m_ptr
Detailed Description
template<typename T>
class QPatternist::AutoPtr< T >
A smart pointer very similar to std::auto_ptr.
Warning
This function is not part of the public interface.
Since
4.4
Definition at line 73 of file qautoptr_p.h.
Constructors and Destructors
AutoPtr() [1/4]
template<typename T> QPatternist::AutoPtr< T >::AutoPtr (T * pointer = 0) inline explicit
Definition at line 76 of file qautoptr_p.h.
                                                 : m_ptr(pointer)
         {
         }
AutoPtr() [2/4]
template<typename T> QPatternist::AutoPtr< T >::AutoPtr (AutoPtr< T > & other) inline
Definition at line 80 of file qautoptr_p.h.
                                           : m_ptr(other.release())
         {
         }
~AutoPtr()
template<typename T> QPatternist::AutoPtr< T >::~AutoPtr () inline
Definition at line 84 of file qautoptr_p.h.
         {
             delete m_ptr;
         }
AutoPtr() [3/4]
template<typename T> QPatternist::AutoPtr< T >::AutoPtr (AutoPtrRef< T > ref) inline
Definition at line 111 of file qautoptr_p.h.
                                    : m_ptr(ref.m_ptr)
         {
         }
AutoPtr() [4/4]
template<typename T> template<typename L > QPatternist::AutoPtr< T >::AutoPtr (AutoPtr< L > & other) inline
Definition at line 138 of file qautoptr_p.h.
                                           : m_ptr(other.release())
         {
         }
Functions
data()
template<typename T> T* QPatternist::AutoPtr< T >::data () const inline
Definition at line 149 of file qautoptr_p.h.
Referenced by QXmlSchemaPrivate::load(), QPatternist::XsdValidatingInstanceReader::loadSchema(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), and QXmlSchemaValidator::validate().
         {
             return m_ptr;
         }
operator AutoPtr< L >()
template<typename T> template<typename L > QPatternist::AutoPtr< T >::operator AutoPtr< L > () inline
Definition at line 132 of file qautoptr_p.h.
         {
             return AutoPtr<L>(this->release());
         }
operator AutoPtrRef< L >()
template<typename T> template<typename L > QPatternist::AutoPtr< T >::operator AutoPtrRef< L > () inline
Definition at line 126 of file qautoptr_p.h.
         {
             return AutoPtrRef<L>(this->release());
         }
operator bool()
template<typename T> QPatternist::AutoPtr< T >::operator bool () const inline
Definition at line 106 of file qautoptr_p.h.
         {
             return m_ptr != 0;
         }
operator!()
template<typename T> bool QPatternist::AutoPtr< T >::operator! () const inline
Definition at line 101 of file qautoptr_p.h.
         {
             return !m_ptr;
         }
operator*()
template<typename T> T& QPatternist::AutoPtr< T >::operator* () const inline
Definition at line 89 of file qautoptr_p.h.
         {
             Q_ASSERT_X(m_ptr, Q_FUNC_INFO, "");
             return *m_ptr;
         }
operator->()
template<typename T> T* QPatternist::AutoPtr< T >::operator-> () const inline
Definition at line 95 of file qautoptr_p.h.
         {
             Q_ASSERT_X(m_ptr, Q_FUNC_INFO, "");
             return m_ptr;
         }
operator=() [1/2]
template<typename T> AutoPtr& QPatternist::AutoPtr< T >::operator= (AutoPtrRef< T > ref) inline
Definition at line 115 of file qautoptr_p.h.
         {
             if(ref.m_ptr != m_ptr)
             {
                 delete m_ptr;
                 m_ptr = ref.m_ptr;
             }
             return *this;
         }
operator=() [2/2]
template<typename T> AutoPtr& QPatternist::AutoPtr< T >::operator= (AutoPtr< T > & other) inline
Definition at line 163 of file qautoptr_p.h.
         {
             reset(other.release());
             return *this;
         }
release()
template<typename T> T* QPatternist::AutoPtr< T >::release () inline
Definition at line 142 of file qautoptr_p.h.
Referenced by QPatternist::AutoPtr< NodeBuilder >::operator=().
         {
             T *const retval = m_ptr;
             m_ptr = 0;
             return retval;
         }
reset()
template<typename T> void QPatternist::AutoPtr< T >::reset (T * other = 0) inline
Definition at line 154 of file qautoptr_p.h.
Referenced by QXmlQuery::setQuery().
         {
             if(other != m_ptr)
             {
                 delete m_ptr;
                 m_ptr = other;
             }
         }
Properties
m_ptr
template<typename T> T* QPatternist::AutoPtr< T >::m_ptr private
Definition at line 170 of file qautoptr_p.h.
The documentation for this class was generated from the following file:
/src/xmlpatterns/utils/qautoptr_p.h