Qt 4.8: QDirectFbInput Class Reference
QDirectFbInput Class Reference
#include <qdirectfbinput.h>
Public Functions
void addWindow (IDirectFBWindow *window, QWidget *platformWindow)
QDirectFbInput (IDirectFB *dfb, IDirectFBDisplayLayer *dfbLayer)
void removeWindow (IDirectFBWindow *window)
void stopInputEventLoop ()
Public Functions inherited from QThread
void exit (int retcode=0)
Tells the thread's event loop to exit with a return code.
bool isFinished () const
Returns true if the thread is finished; otherwise returns false.
bool isRunning () const
Returns true if the thread is running; otherwise returns false.
Priority priority () const
Returns the priority for a running thread.
QThread (QObject *parent=0)
Constructs a new QThread to manage a new thread.
void setPriority (Priority priority)
This function sets the priority for a running thread.
void setStackSize (uint stackSize)
Sets the maximum stack size for the thread to stackSize.
uint stackSize () const
Returns the maximum stack size for the thread (if set with setStackSize()); otherwise returns zero.
bool wait (unsigned long time=ULONG_MAX)
Blocks the thread until either of these conditions is met:
~QThread ()
Destroys the QThread.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void run ()
The starting point for the thread.
Protected Functions inherited from QThread
int exec ()
Enters the event loop and waits until exit() is called, returning the value that was passed to exit().
QThread (QThreadPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
QPoint globalPoint (const DFBEvent &event) const
void handleEnterLeaveEvents (const DFBEvent &event)
void handleEvents ()
void handleKeyEvents (const DFBEvent &event)
void handleMouseEvents (const DFBEvent &event)
void handleWheelEvent (const DFBEvent &event)
Properties
IDirectFBDisplayLayer * m_dfbDisplayLayer
IDirectFB * m_dfbInterface
QDirectFBPointer< IDirectFBEventBuffer > m_eventBuffer
bool m_shouldStop
QHash< DFBWindowID, QWidget * > m_tlwMap
Additional Inherited Members
Public Types inherited from QThread
enum Priority {
IdlePriority, LowestPriority, LowPriority, NormalPriority,
HighPriority, HighestPriority, TimeCriticalPriority, InheritPriority
}
This enum type indicates how the operating system should schedule newly created threads.
Public Slots inherited from QThread
void quit ()
Tells the thread's event loop to exit with return code 0 (success).
void start (Priority=InheritPriority)
Begins execution of the thread by calling run().
void terminate ()
Terminates the execution of the thread.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QThread
void finished ()
This signal is emitted when the thread has finished executing.
void started ()
This signal is emitted when the thread starts executing.
void terminated ()
This signal is emitted when the thread is terminated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QThread
static QThread * currentThread ()
Returns a pointer to a QThread which manages the currently executing thread.
static Qt::HANDLE currentThreadId ()
Returns the thread handle of the currently executing thread.
static int idealThreadCount ()
Returns the ideal number of threads that can be run on the system.
static void yieldCurrentThread ()
Yields execution of the current thread to another runnable thread, if any.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Static Protected Functions inherited from QThread
static void msleep (unsigned long)
Forces the current thread to sleep for msecs milliseconds.
static void setTerminationEnabled (bool enabled=true)
Enables or disables termination of the current thread based on the enabled parameter.
static void sleep (unsigned long)
Forces the current thread to sleep for secs seconds.
static void usleep (unsigned long)
Forces the current thread to sleep for usecs microseconds.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 54 of file qdirectfbinput.h.
Constructors and Destructors
QDirectFbInput()
QDirectFbInput::QDirectFbInput (IDirectFB * dfb, IDirectFBDisplayLayer * dfbLayer)
Definition at line 55 of file qdirectfbinput.cpp.
     : m_dfbInterface(dfb)
     , m_dfbDisplayLayer(dfbLayer)
     , m_shouldStop(false)
 {
     DFBResult ok = m_dfbInterface->CreateEventBuffer(m_dfbInterface, m_eventBuffer.outPtr());
     if (ok != DFB_OK)
         DirectFBError("Failed to initialise eventbuffer", ok);
 }
Functions
addWindow()
void QDirectFbInput::addWindow (IDirectFBWindow * window, QWidget * platformWindow)
Definition at line 79 of file qdirectfbinput.cpp.
Referenced by QDirectFbWindow::QDirectFbWindow().
 {
     DFBResult res;
     DFBWindowID id;
     res = window->GetID(window, &id);
     if (res != DFB_OK) {
         DirectFBError("QDirectFbInput::addWindow", res);
         return;
     }
     m_tlwMap.insert(id, platformWindow);
     window->AttachEventBuffer(window, m_eventBuffer.data());
 }
globalPoint()
QPoint QDirectFbInput::globalPoint (const DFBEvent & event) const inline private
Definition at line 201 of file qdirectfbinput.cpp.
Referenced by handleMouseEvents(), and handleWheelEvent().
 {
     QDirectFBPointer<IDirectFBWindow> window;
     m_dfbDisplayLayer->GetWindow(m_dfbDisplayLayer, event.window.window_id, window.outPtr());
     int x,y;
     window->GetPosition(window.data(), &x, &y);
     return QPoint(event.window.cx +x, event.window.cy + y);
 }
handleEnterLeaveEvents()
void QDirectFbInput::handleEnterLeaveEvents (const DFBEvent & event) private
Definition at line 186 of file qdirectfbinput.cpp.
Referenced by handleEvents().
 {
     QWidget *tlw = m_tlwMap.value(event.window.window_id);
     switch (event.window.type) {
     case DWET_ENTER:
         QWindowSystemInterface::handleEnterEvent(tlw);
         break;
     case DWET_LEAVE:
         QWindowSystemInterface::handleLeaveEvent(tlw);
         break;
     default:
         break;
     }
 }
handleEvents()
void QDirectFbInput::handleEvents () private
Definition at line 109 of file qdirectfbinput.cpp.
Referenced by run().
 {
     DFBResult hasEvent = m_eventBuffer->HasEvent(m_eventBuffer.data());
     while(hasEvent == DFB_OK){
         DFBEvent event;
         DFBResult ok = m_eventBuffer->GetEvent(m_eventBuffer.data(), &event);
         if (ok != DFB_OK)
             DirectFBError("Failed to get event",ok);
         if (event.clazz == DFEC_WINDOW) {
             switch (event.window.type) {
             case DWET_BUTTONDOWN:
             case DWET_BUTTONUP:
             case DWET_MOTION:
                 handleMouseEvents(event);
                 break;
             case DWET_WHEEL:
                 handleWheelEvent(event);
                 break;
             case DWET_KEYDOWN:
             case DWET_KEYUP:
                 handleKeyEvents(event);
                 break;
             case DWET_ENTER:
             case DWET_LEAVE:
                 handleEnterLeaveEvents(event);
             default:
                 break;
             }
         }
         hasEvent = m_eventBuffer->HasEvent(m_eventBuffer.data());
     }
 }
handleKeyEvents()
void QDirectFbInput::handleKeyEvents (const DFBEvent & event) private
Definition at line 171 of file qdirectfbinput.cpp.
Referenced by handleEvents().
 {
     QEvent::Type type = QDirectFbConvenience::eventType(event.window.type);
     Qt::Key key = QDirectFbConvenience::keyMap()->value(event.window.key_symbol);
     Qt::KeyboardModifiers modifiers = QDirectFbConvenience::keyboardModifiers(event.window.modifiers);
     long timestamp = (event.window.timestamp.tv_sec*1000) + (event.window.timestamp.tv_usec/1000);
     QChar character;
     if (DFB_KEY_TYPE(event.window.key_symbol) == DIKT_UNICODE)
         character = QChar(event.window.key_symbol);
     QWidget *tlw = m_tlwMap.value(event.window.window_id);
     QWindowSystemInterface::handleKeyEvent(tlw, timestamp, type, key, modifiers, character);
 }
handleMouseEvents()
void QDirectFbInput::handleMouseEvents (const DFBEvent & event) private
Definition at line 144 of file qdirectfbinput.cpp.
Referenced by handleEvents().
 {
     QPoint p(event.window.x, event.window.y);
     QPoint globalPos = globalPoint(event);
     Qt::MouseButtons buttons = QDirectFbConvenience::mouseButtons(event.window.buttons);
     QDirectFBPointer<IDirectFBDisplayLayer> layer(QDirectFbConvenience::dfbDisplayLayer());
     QDirectFBPointer<IDirectFBWindow> window;
     layer->GetWindow(layer.data(), event.window.window_id, window.outPtr());
     long timestamp = (event.window.timestamp.tv_sec*1000) + (event.window.timestamp.tv_usec/1000);
     QWidget *tlw = m_tlwMap.value(event.window.window_id);
     QWindowSystemInterface::handleMouseEvent(tlw, timestamp, p, globalPos, buttons);
 }
handleWheelEvent()
void QDirectFbInput::handleWheelEvent (const DFBEvent & event) private
Definition at line 160 of file qdirectfbinput.cpp.
Referenced by handleEvents().
 {
     QPoint p(event.window.cx, event.window.cy);
     QPoint globalPos = globalPoint(event);
     long timestamp = (event.window.timestamp.tv_sec*1000) + (event.window.timestamp.tv_usec/1000);
     QWidget *tlw = m_tlwMap.value(event.window.window_id);
     QWindowSystemInterface::handleWheelEvent(tlw, timestamp, p, globalPos,
                                           event.window.step*120,
                                           Qt::Vertical);
 }
removeWindow()
void QDirectFbInput::removeWindow (IDirectFBWindow * window)
Definition at line 94 of file qdirectfbinput.cpp.
Referenced by QDirectFbWindow::~QDirectFbWindow().
 {
     DFBResult res;
     DFBWindowID id;
     res = window->GetID(window, &id);
     if (res != DFB_OK) {
         DirectFBError("QDirectFbInput::removeWindow", res);
         return;
     }
     window->DetachEventBuffer(window, m_eventBuffer.data());
     m_tlwMap.remove(id);
 }
run()
void QDirectFbInput::run (void) protected virtual
The starting point for the thread.
After calling start(), the newly created thread calls this function. The default implementation simply calls exec().
You can reimplement this function to facilitate advanced thread management. Returning from this method will end the execution of the thread.
See also
start() wait()
Reimplemented from QThread.
Definition at line 65 of file qdirectfbinput.cpp.
 {
     while (!m_shouldStop) {
         if (m_eventBuffer->WaitForEvent(m_eventBuffer.data()) == DFB_OK)
             handleEvents();
     }
 }
stopInputEventLoop()
void QDirectFbInput::stopInputEventLoop ()
Definition at line 73 of file qdirectfbinput.cpp.
Referenced by QDirectFbIntegration::~QDirectFbIntegration().
 {
     m_shouldStop = true;
     m_eventBuffer->WakeUp(m_eventBuffer.data());
 }
Properties
m_dfbDisplayLayer
IDirectFBDisplayLayer* QDirectFbInput::m_dfbDisplayLayer private
Definition at line 77 of file qdirectfbinput.h.
Referenced by globalPoint().
m_dfbInterface
IDirectFB* QDirectFbInput::m_dfbInterface private
Definition at line 76 of file qdirectfbinput.h.
Referenced by QDirectFbInput().
m_eventBuffer
QDirectFBPointer<IDirectFBEventBuffer> QDirectFbInput::m_eventBuffer private
Definition at line 78 of file qdirectfbinput.h.
Referenced by addWindow(), handleEvents(), QDirectFbInput(), removeWindow(), run(), and stopInputEventLoop().
m_shouldStop
bool QDirectFbInput::m_shouldStop private
Definition at line 80 of file qdirectfbinput.h.
Referenced by run(), and stopInputEventLoop().
m_tlwMap
QHash<DFBWindowID,QWidget *> QDirectFbInput::m_tlwMap private
Definition at line 81 of file qdirectfbinput.h.
Referenced by addWindow(), handleEnterLeaveEvents(), handleKeyEvents(), handleMouseEvents(), handleWheelEvent(), and removeWindow().
The documentation for this class was generated from the following files:
/src/plugins/platforms/directfb/qdirectfbinput.h
/src/plugins/platforms/directfb/qdirectfbinput.cpp