Qt 4.8: QPatternist::VariableLoader Class Reference
QPatternist::VariableLoader Class Reference
#include <qvariableloader_p.h>
Public Types
typedef QHash< QXmlName, QVariant > BindingHash
typedef QExplicitlySharedDataPointer< VariableLoader > Ptr
Public Types inherited from QPatternist::ExternalVariableLoader
typedef QExplicitlySharedDataPointer< ExternalVariableLoader > Ptr
Public Functions
void addBinding (const QXmlName &name, const QVariant &value)
virtual QPatternist::SequenceType::Ptr announceExternalVariable (const QXmlName name, const QPatternist::SequenceType::Ptr &declaredType)
virtual QPatternist::Item::Iterator::Ptr evaluateSequence (const QXmlName name, const QPatternist::DynamicContext::Ptr &)
virtual QPatternist::Item evaluateSingleton (const QXmlName name, const QPatternist::DynamicContext::Ptr &)
bool hasBinding (const QXmlName &name) const
bool invalidationRequired (const QXmlName &name, const QVariant &variant) const
bool isSameType (const QVariant &v1, const QVariant &v2) const
void removeBinding (const QXmlName &name)
QVariant valueFor (const QXmlName &name) const
VariableLoader (const NamePool::Ptr &np, const VariableLoader::Ptr &previousLoader=VariableLoader::Ptr())
Public Functions inherited from QPatternist::ExternalVariableLoader
virtual bool evaluateEBV (const QXmlName name, const QExplicitlySharedDataPointer< DynamicContext > &context)
virtual Item::Iterator::Ptr evaluateSequence (const QXmlName name, const QExplicitlySharedDataPointer< DynamicContext > &context)
virtual Item evaluateSingleton (const QXmlName name, const QExplicitlySharedDataPointer< DynamicContext > &context)
ExternalVariableLoader ()
virtual ~ExternalVariableLoader ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Private Functions
QPatternist::Item itemForName (const QXmlName &name) const
Properties
BindingHash m_bindingHash
const NamePool::Ptr m_namePool
VariableLoader::Ptr m_previousLoader
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Definition at line 68 of file qvariableloader_p.h.
Typedefs
BindingHash
typedef QHash<QXmlName, QVariant> QPatternist::VariableLoader::BindingHash
Definition at line 71 of file qvariableloader_p.h.
Ptr
typedef QExplicitlySharedDataPointer<VariableLoader> QPatternist::VariableLoader::Ptr
Definition at line 72 of file qvariableloader_p.h.
Constructors and Destructors
VariableLoader()
QPatternist::VariableLoader::VariableLoader (const NamePool::Ptr & np, const VariableLoader::Ptr & previousLoader = VariableLoader::Ptr()) inline
Definition at line 74 of file qvariableloader_p.h.
                                                                                              : m_namePool(np)
                                                                                                  , m_previousLoader(previousLoader)
         {
         }
Functions
addBinding()
void VariableLoader::addBinding (const QXmlName & name, const QVariant & value)
Definition at line 251 of file qvariableloader.cpp.
Referenced by VariableLoader().
 {
     m_bindingHash.insert(name, value);
 }
announceExternalVariable()
SequenceType::Ptr VariableLoader::announceExternalVariable (const QXmlName name, const QPatternist::SequenceType::Ptr & declaredType) virtual
Called when Patternist encounters an external variable in the query. It is guaranteed to be called once for each external variable appearing in a query module.
Parameters
name the name of the variable. Quaranteed to never be null.
declaredType the type that the user declared the variable to be of. Whether this type matches the actual value of the variable or not is irrelevant. Patternist will do the necessary error handling based on the sequence type that is returned from this function. If the user didn't declare a type, the type is item()*(zero or more items). Quaranteed to never be null.
Returns
the sequence type of the value this ExternalVariableLoader actually supplies. However, if the ExternalVariableLoader knows it cannot supply a variable by this name, null should be returned.
Reimplemented from QPatternist::ExternalVariableLoader.
Definition at line 121 of file qvariableloader.cpp.
Referenced by VariableLoader().
 {
     Q_UNUSED(declaredType);
     const QVariant &variant = m_bindingHash.value(name);
     if(variant.isNull())
         return SequenceType::Ptr();
     else if(variant.userType() == qMetaTypeId<QIODevice *>())
         return CommonSequenceTypes::ExactlyOneAnyURI;
     else if(variant.userType() == qMetaTypeId<QXmlQuery>())
     {
         const QXmlQuery variableQuery(qvariant_cast<QXmlQuery>(variant));
         return variableQuery.d->expression()->staticType();
     }
     else
     {
         return makeGenericSequenceType(AtomicValue::qtToXDMType(qvariant_cast<QXmlItem>(variant)),
                                        Cardinality::exactlyOne());
     }
 }
evaluateSequence()
Item::Iterator::Ptr VariableLoader::evaluateSequence (const QXmlName name, const QPatternist::DynamicContext::Ptr & context) virtual
Definition at line 144 of file qvariableloader.cpp.
Referenced by VariableLoader().
 {
     const QVariant &variant = m_bindingHash.value(name);
     Q_ASSERT_X(!variant.isNull(), Q_FUNC_INFO,
                "We assume that we have a binding.");
     /* Same code as in the default clause below. */
     if(variant.userType() == qMetaTypeId<QIODevice *>())
         return makeSingletonIterator(itemForName(name));
     else if(variant.userType() == qMetaTypeId<QXmlQuery>())
     {
         const QXmlQuery variableQuery(qvariant_cast<QXmlQuery>(variant));
         return variableQuery.d->expression()->evaluateSequence(DynamicContext::Ptr(new TemporaryTreesRedirectingContext(variableQuery.d->dynamicContext(), context)));
     }
     const QVariant v(qvariant_cast<QXmlItem>(variant).toAtomicValue());
     switch(v.type())
     {
         case QVariant::StringList:
             return Item::Iterator::Ptr(new StringListIterator(v.toStringList()));
         case QVariant::List:
             return Item::Iterator::Ptr(new VariantListIterator(v.toList()));
         default:
             return makeSingletonIterator(itemForName(name));
     }
 }
evaluateSingleton()
Item VariableLoader::evaluateSingleton (const QXmlName name, const QPatternist::DynamicContext::Ptr &) virtual
Definition at line 199 of file qvariableloader.cpp.
Referenced by VariableLoader().
 {
     return itemForName(name);
 }
hasBinding()
bool VariableLoader::hasBinding (const QXmlName & name) const
Definition at line 235 of file qvariableloader.cpp.
Referenced by VariableLoader().
 {
     return m_bindingHash.contains(name)
         || (m_previousLoader && m_previousLoader->hasBinding(name));
 }
invalidationRequired()
bool VariableLoader::invalidationRequired (const QXmlName & name, const QVariant & variant) const
Definition at line 257 of file qvariableloader.cpp.
Referenced by VariableLoader().
 {
     return hasBinding(name) && !isSameType(valueFor(name), variant);
 }
isSameType()
bool VariableLoader::isSameType (const QVariant & v1, const QVariant & v2) const
Definition at line 205 of file qvariableloader.cpp.
Referenced by VariableLoader().
 {
     /* Are both of type QIODevice *? */
     if(v1.userType() == qMetaTypeId<QIODevice *>() && v1.userType() == v2.userType())
         return true;
     /* Ok, we have two QXmlItems. */
     const QXmlItem i1(qvariant_cast<QXmlItem>(v1));
     const QXmlItem i2(qvariant_cast<QXmlItem>(v2));
     if(i1.isNode())
     {
         Q_ASSERT(false);
         return false;
     }
     else if(i2.isAtomicValue())
         return i1.toAtomicValue().type() == i2.toAtomicValue().type();
     else
     {
         /* One is an atomic, the other is a node or they are null. */
         return false;
     }
 }
itemForName()
Item VariableLoader::itemForName (const QXmlName & name) const inline private
Definition at line 175 of file qvariableloader.cpp.
Referenced by VariableLoader().
 {
     const QVariant &variant = m_bindingHash.value(name);
     if(variant.userType() == qMetaTypeId<QIODevice *>())
         return Item(AnyURI::fromValue(QLatin1String("tag:trolltech.com,2007:QtXmlPatterns:QIODeviceVariable:") + m_namePool->stringForLocalName(name.localName())));
     const QXmlItem item(qvariant_cast<QXmlItem>(variant));
     if(item.isNode())
         return Item::fromPublic(item);
     else
     {
         const QVariant atomicValue(item.toAtomicValue());
         /* If the atomicValue is null it means it doesn't exist in m_bindingHash, and therefore it must
          * be a QIODevice, since Patternist guarantees to only ask for variables that announceExternalVariable()
          * has accepted. */
         if(atomicValue.isNull())
             return Item(AnyURI::fromValue(QLatin1String("tag:trolltech.com,2007:QtXmlPatterns:QIODeviceVariable:") + m_namePool->stringForLocalName(name.localName())));
         else
             return AtomicValue::toXDM(atomicValue);
     }
 }
removeBinding()
void VariableLoader::removeBinding (const QXmlName & name)
Definition at line 230 of file qvariableloader.cpp.
Referenced by VariableLoader().
 {
     m_bindingHash.remove(name);
 }
valueFor()
QVariant VariableLoader::valueFor (const QXmlName & name) const
Definition at line 241 of file qvariableloader.cpp.
Referenced by QPatternist::URILoader::createRequest(), and VariableLoader().
 {
     if(m_bindingHash.contains(name))
         return m_bindingHash.value(name);
     else if(m_previousLoader)
         return m_previousLoader->valueFor(name);
     else
         return QVariant();
 }
Properties
m_bindingHash
BindingHash QPatternist::VariableLoader::m_bindingHash private
Definition at line 107 of file qvariableloader_p.h.
m_namePool
const NamePool::Ptr QPatternist::VariableLoader::m_namePool private
Definition at line 105 of file qvariableloader_p.h.
m_previousLoader
VariableLoader::Ptr QPatternist::VariableLoader::m_previousLoader private
Definition at line 106 of file qvariableloader_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qvariableloader_p.h
/src/xmlpatterns/api/qvariableloader.cpp