Qt 4.8: QNetworkAccessCache Class Reference
QNetworkAccessCache Class Reference
#include <qnetworkaccesscache_p.h>
Classes
class CacheableObject
struct Node
Public Types
typedef QHash< QByteArray, Node > NodeHash
Signals
void entryReady (QNetworkAccessCache::CacheableObject *)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addEntry (const QByteArray &key, CacheableObject *entry)
void clear ()
bool hasEntry (const QByteArray &key) const
QNetworkAccessCache ()
void releaseEntry (const QByteArray &key)
void removeEntry (const QByteArray &key)
bool requestEntry (const QByteArray &key, QObject *target, const char *member)
CacheableObject * requestEntryNow (const QByteArray &key)
~QNetworkAccessCache ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Private Functions
bool emitEntryReady (Node *node, QObject *target, const char *member)
void linkEntry (const QByteArray &key)
Appens the entry given by key to the end of the linked list.
bool unlinkEntry (const QByteArray &key)
Removes the entry pointed by key from the linked list.
void updateTimer ()
Properties
NodeHash hash
Node * newest
Node * oldest
QBasicTimer timer
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 70 of file qnetworkaccesscache_p.h.
Typedefs
NodeHash
typedef QHash<QByteArray, Node> QNetworkAccessCache::NodeHash
Definition at line 74 of file qnetworkaccesscache_p.h.
Constructors and Destructors
QNetworkAccessCache()
QNetworkAccessCache::QNetworkAccessCache ()
Definition at line 106 of file qnetworkaccesscache.cpp.
     : oldest(0), newest(0)
 {
 }
~QNetworkAccessCache()
QNetworkAccessCache::~QNetworkAccessCache ()
Definition at line 111 of file qnetworkaccesscache.cpp.
Referenced by QNetworkAccessCache::CacheableObject::cacheKey().
 {
     clear();
 }
Functions
addEntry()
void QNetworkAccessCache::addEntry (const QByteArray & key, CacheableObject * entry)
Definition at line 246 of file qnetworkaccesscache.cpp.
Referenced by QNetworkAccessCache::CacheableObject::cacheKey(), QNetworkAccessFtpBackend::open(), and QHttpThreadDelegate::startRequest().
 {
     Q_ASSERT(!key.isEmpty());
     if (unlinkEntry(key))
         updateTimer();
     Node &node = hash[key];     // create the entry in the hash if it didn't exist
     if (node.useCount)
         qWarning("QNetworkAccessCache::addEntry: overriding active cache entry '%s'",
                  key.constData());
     if (node.object)
         node.object->dispose();
     node.object = entry;
     node.object->key = key;
     node.key = key;
     node.useCount = 1;
 }
clear()
void QNetworkAccessCache::clear ()
Definition at line 116 of file qnetworkaccesscache.cpp.
Referenced by QNetworkAccessCache::CacheableObject::cacheKey(), and ~QNetworkAccessCache().
 {
     NodeHash hashCopy = hash;
     hash.clear();
     // remove all entries
     NodeHash::Iterator it = hashCopy.begin();
     NodeHash::Iterator end = hashCopy.end();
     for ( ; it != end; ++it) {
         it->object->key.clear();
         it->object->dispose();
     }
     // now delete:
     hashCopy.clear();
     timer.stop();
     oldest = newest = 0;
 }
emitEntryReady()
bool QNetworkAccessCache::emitEntryReady (Node * node, QObject * target, const char * member) private
Definition at line 212 of file qnetworkaccesscache.cpp.
Referenced by releaseEntry(), and requestEntry().
 {
     if (!connect(this, SIGNAL(entryReady(QNetworkAccessCache::CacheableObject*)),
                  target, member, Qt::QueuedConnection))
         return false;
     emit entryReady(node->object);
     disconnect(SIGNAL(entryReady(QNetworkAccessCache::CacheableObject*)));
     return true;
 }
entryReady
void QNetworkAccessCache::entryReady (QNetworkAccessCache::CacheableObject *) signal
Referenced by QNetworkAccessCache::CacheableObject::cacheKey(), and emitEntryReady().
hasEntry()
bool QNetworkAccessCache::hasEntry (const QByteArray & key) const
Definition at line 265 of file qnetworkaccesscache.cpp.
Referenced by QNetworkAccessCache::CacheableObject::cacheKey().
 {
     return hash.contains(key);
 }
linkEntry()
void QNetworkAccessCache::linkEntry (const QByteArray & key) private
Appens the entry given by key to the end of the linked list.
(i.e., makes it the newest entry)
Definition at line 141 of file qnetworkaccesscache.cpp.
Referenced by releaseEntry().
 {
     NodeHash::Iterator it = hash.find(key);
     if (it == hash.end())
         return;
     Node *const node = &it.value();
     Q_ASSERT(node != oldest && node != newest);
     Q_ASSERT(node->older == 0 && node->newer == 0);
     Q_ASSERT(node->useCount == 0);
     if (newest) {
         Q_ASSERT(newest->newer == 0);
         newest->newer = node;
         node->older = newest;
     }
     if (!oldest) {
         // there are no entries, so this is the oldest one too
         oldest = node;
     }
     node->timestamp = QDateTime::currentDateTime().addSecs(ExpiryTime);
     newest = node;
 }
releaseEntry()
void QNetworkAccessCache::releaseEntry (const QByteArray & key)
Definition at line 323 of file qnetworkaccesscache.cpp.
Referenced by QNetworkAccessCache::CacheableObject::cacheKey(), QNetworkAccessFtpBackend::disconnectFromFtp(), and QHttpThreadDelegate::startRequestSynchronously().
 {
     NodeHash::Iterator it = hash.find(key);
     if (it == hash.end()) {
         qWarning("QNetworkAccessCache::releaseEntry: trying to release key '%s' that is not in cache",
                  key.constData());
         return;
     }
     Node *node = &it.value();
     Q_ASSERT(node->useCount > 0);
     // are there other objects waiting?
     if (!node->receiverQueue.isEmpty()) {
         // queue another activation
         Receiver receiver;
         do {
             receiver = node->receiverQueue.dequeue();
         } while (receiver.object.isNull() && !node->receiverQueue.isEmpty());
         if (!receiver.object.isNull()) {
             emitEntryReady(node, receiver.object, receiver.member);
             return;
         }
     }
     if (!--node->useCount) {
         // no objects waiting; add it back to the expiry list
         if (node->object->expires)
             linkEntry(key);
         if (oldest == node)
             updateTimer();
     }
 }
removeEntry()
void QNetworkAccessCache::removeEntry (const QByteArray & key)
Definition at line 359 of file qnetworkaccesscache.cpp.
Referenced by QNetworkAccessCache::CacheableObject::cacheKey(), and QNetworkAccessFtpBackend::ftpDone().
 {
     NodeHash::Iterator it = hash.find(key);
     if (it == hash.end()) {
         qWarning("QNetworkAccessCache::removeEntry: trying to remove key '%s' that is not in cache",
                  key.constData());
         return;
     }
     Node *node = &it.value();
     if (unlinkEntry(key))
         updateTimer();
     if (node->useCount > 1)
         qWarning("QNetworkAccessCache::removeEntry: removing active cache entry '%s'",
                  key.constData());
     node->object->key.clear();
     hash.remove(node->key);
 }
requestEntry()
bool QNetworkAccessCache::requestEntry (const QByteArray & key, QObject * target, const char * member)
Definition at line 270 of file qnetworkaccesscache.cpp.
Referenced by QNetworkAccessCache::CacheableObject::cacheKey(), and QNetworkAccessFtpBackend::open().
 {
     NodeHash::Iterator it = hash.find(key);
     if (it == hash.end())
         return false;           // no such entry
     Node *node = &it.value();
     if (node->useCount > 0 && !node->object->shareable) {
         // object is not shareable and is in use
         // queue for later use
         Q_ASSERT(node->older == 0 && node->newer == 0);
         Receiver receiver;
         receiver.object = target;
         receiver.member = member;
         node->receiverQueue.enqueue(receiver);
         // request queued
         return true;
     } else {
         // node not in use or is shareable
         if (unlinkEntry(key))
             updateTimer();
         ++node->useCount;
         return emitEntryReady(node, target, member);
     }
 }
requestEntryNow()
QNetworkAccessCache::CacheableObject * QNetworkAccessCache::requestEntryNow (const QByteArray & key)
Definition at line 299 of file qnetworkaccesscache.cpp.
Referenced by QNetworkAccessCache::CacheableObject::cacheKey(), and QHttpThreadDelegate::startRequest().
 {
     NodeHash::Iterator it = hash.find(key);
     if (it == hash.end())
         return 0;
     if (it->useCount > 0) {
         if (it->object->shareable) {
             ++it->useCount;
             return it->object;
         }
         // object in use and not shareable
         return 0;
     }
     // entry not in use, let the caller have it
     bool wasOldest = unlinkEntry(key);
     ++it->useCount;
     if (wasOldest)
         updateTimer();
     return it->object;
 }
timerEvent()
void QNetworkAccessCache::timerEvent (QTimerEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 224 of file qnetworkaccesscache.cpp.
Referenced by QNetworkAccessCache::CacheableObject::cacheKey().
 {
     // expire old items
     QDateTime now = QDateTime::currentDateTime();
     while (oldest && oldest->timestamp < now) {
         Node *next = oldest->newer;
         oldest->object->dispose();
         hash.remove(oldest->key); // oldest gets deleted
         oldest = next;
     }
     // fixup the list
     if (oldest)
         oldest->older = 0;
     else
         newest = 0;
     updateTimer();
 }
unlinkEntry()
bool QNetworkAccessCache::unlinkEntry (const QByteArray & key) private
Removes the entry pointed by key from the linked list.
Returns true if the entry removed was the oldest one.
Definition at line 170 of file qnetworkaccesscache.cpp.
Referenced by addEntry(), removeEntry(), requestEntry(), and requestEntryNow().
 {
     NodeHash::Iterator it = hash.find(key);
     if (it == hash.end())
         return false;
     Node *const node = &it.value();
     bool wasOldest = false;
     if (node == oldest) {
         oldest = node->newer;
         wasOldest = true;
     }
     if (node == newest)
         newest = node->older;
     if (node->older)
         node->older->newer = node->newer;
     if (node->newer)
         node->newer->older = node->older;
     node->newer = node->older = 0;
     return wasOldest;
 }
updateTimer()
void QNetworkAccessCache::updateTimer () private
Definition at line 194 of file qnetworkaccesscache.cpp.
Referenced by addEntry(), releaseEntry(), removeEntry(), requestEntry(), requestEntryNow(), and timerEvent().
 {
     timer.stop();
     if (!oldest)
         return;
     int interval = QDateTime::currentDateTime().secsTo(oldest->timestamp);
     if (interval <= 0) {
         interval = 0;
     } else {
         // round up the interval
         interval = (interval + 15) & ~16;
     }
     timer.start(interval * 1000, this);
 }
Properties
hash
NodeHash QNetworkAccessCache::hash private
Definition at line 114 of file qnetworkaccesscache_p.h.
Referenced by addEntry(), clear(), hasEntry(), linkEntry(), releaseEntry(), removeEntry(), requestEntry(), requestEntryNow(), timerEvent(), and unlinkEntry().
newest
Node* QNetworkAccessCache::newest private
Definition at line 116 of file qnetworkaccesscache_p.h.
Referenced by clear(), linkEntry(), timerEvent(), and unlinkEntry().
oldest
Node* QNetworkAccessCache::oldest private
Definition at line 115 of file qnetworkaccesscache_p.h.
Referenced by clear(), linkEntry(), releaseEntry(), timerEvent(), unlinkEntry(), and updateTimer().
timer
QBasicTimer QNetworkAccessCache::timer private
Definition at line 118 of file qnetworkaccesscache_p.h.
Referenced by clear(), and updateTimer().
The documentation for this class was generated from the following files:
/src/network/access/qnetworkaccesscache_p.h
/src/network/access/qnetworkaccesscache.cpp