Qt 4.8: QMdi::Rearranger Class Reference
QMdi::Rearranger Class Reference abstract
#include <qmdiarea_p.h>
Public Types
enum Type { RegularTiler, SimpleCascader, IconTiler }
Public Functions
virtual void rearrange (QList< QWidget *> &widgets, const QRect &domain) const =0
virtual Type type () const =0
virtual ~Rearranger ()
Detailed Description
Definition at line 71 of file qmdiarea_p.h.
Enumerations
Type
enum QMdi::Rearranger::Type
Enumerator
RegularTiler
SimpleCascader
IconTiler
Definition at line 74 of file qmdiarea_p.h.
               {
         RegularTiler,
         SimpleCascader,
         IconTiler
     };
Constructors and Destructors
~Rearranger()
virtual QMdi::Rearranger::~Rearranger () inline virtual
Definition at line 83 of file qmdiarea_p.h.
 {}
Functions
rearrange()
virtual void QMdi::Rearranger::rearrange (QList< QWidget *> & widgets, const QRect & domain) const pure virtual
Implemented in QMdi::IconTiler, QMdi::SimpleCascader, and QMdi::RegularTiler.
Referenced by QMdiAreaPrivate::rearrange().
type()
virtual Type QMdi::Rearranger::type () const pure virtual
Implemented in QMdi::IconTiler, QMdi::SimpleCascader, and QMdi::RegularTiler.
Referenced by QMdiAreaPrivate::rearrange(), and QMdiArea::showEvent().
The documentation for this class was generated from the following file:
/src/gui/widgets/qmdiarea_p.h