Qt 4.8: QAbstractItemModelPrivate Class Reference
QAbstractItemModelPrivate Class Reference
#include <qabstractitemmodel_p.h>
Classes
struct Change
struct Persistent
Public Functions
bool allowMove (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation orientation)
Returns whether a move operation is valid.
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
QModelIndex createIndex (int row, int column, void *data=0) const
QModelIndex createIndex (int row, int column, int id) const
bool indexValid (const QModelIndex &index) const
void invalidatePersistentIndex (const QModelIndex &index)
void invalidatePersistentIndexes ()
void itemsAboutToBeMoved (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation)
void itemsMoved (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation orientation)
void movePersistentIndexes (QVector< QPersistentModelIndexData *> indexes, int change, const QModelIndex &parent, Qt::Orientation orientation)
Moves persistent indexes indexes by amount change.
QAbstractItemModelPrivate ()
void removePersistentIndexData (QPersistentModelIndexData *data)
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static const QHash< int, QByteArray > & defaultRoleNames ()
static QAbstractItemModel * staticEmptyModel ()
static bool variantLessThan (const QVariant &v1, const QVariant &v2)
This function is used by our Q{Tree,Widget,Table}WidgetModel classes to sort.
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QStack< Change > changes
struct QAbstractItemModelPrivate::Persistent persistent
QHash< int, QByteArray > roleNames
Qt::DropActions supportedDragActions
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 76 of file qabstractitemmodel_p.h.
Constructors and Destructors
QAbstractItemModelPrivate()
QAbstractItemModelPrivate::QAbstractItemModelPrivate () inline
Definition at line 81 of file qabstractitemmodel_p.h.
 : QObjectPrivate(), supportedDragActions(-1), roleNames(defaultRoleNames()) {}
Functions
allowMove()
bool QAbstractItemModelPrivate::allowMove (const QModelIndex & srcParent, int start, int end, const QModelIndex & destinationParent, int destinationStart, Qt::Orientation orientation)
Returns whether a move operation is valid.
A move operation is not allowed if it moves a continuous range of rows to a destination within itself, or if it attempts to move a row to one of its own descendants.
Warning
This function is not part of the public interface.
Definition at line 2683 of file qabstractitemmodel.cpp.
 {
     // Don't move the range within itself.
     if (destinationParent == srcParent)
         return !(destinationStart >= start && destinationStart <= end + 1);
     QModelIndex destinationAncestor = destinationParent;
     int pos = (Qt::Vertical == orientation) ? destinationAncestor.row() : destinationAncestor.column();
     forever {
         if (destinationAncestor == srcParent) {
             if (pos >= start && pos <= end)
                 return false;
             break;
         }
         if (!destinationAncestor.isValid())
           break;
         pos = (Qt::Vertical == orientation) ? destinationAncestor.row() : destinationAncestor.column();
         destinationAncestor = destinationAncestor.parent();
     }
     return true;
 }
columnsAboutToBeInserted()
void QAbstractItemModelPrivate::columnsAboutToBeInserted (const QModelIndex & parent, int first, int last)
Definition at line 809 of file qabstractitemmodel.cpp.
 {
     Q_Q(QAbstractItemModel);
     Q_UNUSED(last);
     QVector<QPersistentModelIndexData *> persistent_moved;
     if (first < q->columnCount(parent)) {
         for (QHash<QModelIndex, QPersistentModelIndexData *>::const_iterator it = persistent.indexes.constBegin();
              it != persistent.indexes.constEnd(); ++it) {
             QPersistentModelIndexData *data = *it;
             const QModelIndex &index = data->index;
             if (index.column() >= first && index.isValid() && index.parent() == parent)
                 persistent_moved.append(data);
         }
     }
     persistent.moved.push(persistent_moved);
 }
columnsAboutToBeRemoved()
void QAbstractItemModelPrivate::columnsAboutToBeRemoved (const QModelIndex & parent, int first, int last)
Definition at line 846 of file qabstractitemmodel.cpp.
 {
     QVector<QPersistentModelIndexData *> persistent_moved;
     QVector<QPersistentModelIndexData *> persistent_invalidated;
     // find the persistent indexes that are affected by the change, either by being in the removed subtree
     // or by being on the same level and to the right of the removed columns
     for (QHash<QModelIndex, QPersistentModelIndexData *>::const_iterator it = persistent.indexes.constBegin();
          it != persistent.indexes.constEnd(); ++it) {
         QPersistentModelIndexData *data = *it;
         bool level_changed = false;
         QModelIndex current = data->index;
         while (current.isValid()) {
             QModelIndex current_parent = current.parent();
             if (current_parent == parent) { // on the same level as the change
                 if (!level_changed && current.column() > last) // right of the removed columns
                     persistent_moved.append(data);
                 else if (current.column() <= last && current.column() >= first) // in the removed subtree
                     persistent_invalidated.append(data);
                 break;
             }
             current = current_parent;
             level_changed = true;
         }
     }
     persistent.moved.push(persistent_moved);
     persistent.invalidated.push(persistent_invalidated);
 }
columnsInserted()
void QAbstractItemModelPrivate::columnsInserted (const QModelIndex & parent, int first, int last)
Definition at line 827 of file qabstractitemmodel.cpp.
 {
     QVector<QPersistentModelIndexData *> persistent_moved = persistent.moved.pop();
     int count = (last - first) + 1; // it is important to only use the delta, because the change could be nested
     for (QVector<QPersistentModelIndexData *>::const_iterator it = persistent_moved.constBegin();
          it != persistent_moved.constEnd(); ++it) {
         QPersistentModelIndexData *data = *it;
         QModelIndex old = data->index;
         persistent.indexes.erase(persistent.indexes.find(old));
         data->index = q_func()->index(old.row(), old.column() + count, parent);
         if (data->index.isValid()) {
             persistent.insertMultiAtEnd(data->index, data);
         } else {
             qWarning() << "QAbstractItemModel::endInsertColumns:  Invalid index (" << old.row() << ',' << old.column() + count << ") in model" << q_func();
         }
      }
 }
columnsRemoved()
void QAbstractItemModelPrivate::columnsRemoved (const QModelIndex & parent, int first, int last)
Definition at line 877 of file qabstractitemmodel.cpp.
 {
     QVector<QPersistentModelIndexData *> persistent_moved = persistent.moved.pop();
     int count = (last - first) + 1; // it is important to only use the delta, because the change could be nested
     for (QVector<QPersistentModelIndexData *>::const_iterator it = persistent_moved.constBegin();
          it != persistent_moved.constEnd(); ++it) {
         QPersistentModelIndexData *data = *it;
         QModelIndex old = data->index;
         persistent.indexes.erase(persistent.indexes.find(old));
         data->index = q_func()->index(old.row(), old.column() - count, parent);
         if (data->index.isValid()) {
             persistent.insertMultiAtEnd(data->index, data);
         } else {
             qWarning() << "QAbstractItemModel::endRemoveColumns:  Invalid index (" << old.row() << ',' << old.column() - count << ") in model" << q_func();
         }
     }
     QVector<QPersistentModelIndexData *> persistent_invalidated = persistent.invalidated.pop();
     for (QVector<QPersistentModelIndexData *>::const_iterator it = persistent_invalidated.constBegin();
          it != persistent_invalidated.constEnd(); ++it) {
         QPersistentModelIndexData *data = *it;
         persistent.indexes.erase(persistent.indexes.find(data->index));
         data->index = QModelIndex();
         data->model = 0;
     }
 }
createIndex() [1/2]
QModelIndex QAbstractItemModelPrivate::createIndex (int row, int column, void * data = 0) const inline
Definition at line 99 of file qabstractitemmodel_p.h.
{
         return q_func()->createIndex(row, column, data);
     }
createIndex() [2/2]
QModelIndex QAbstractItemModelPrivate::createIndex (int row, int column, int id) const inline
Definition at line 103 of file qabstractitemmodel_p.h.
{
         return q_func()->createIndex(row, column, id);
     }
defaultRoleNames()
const QHash< int, QByteArray > & QAbstractItemModelPrivate::defaultRoleNames () static
Definition at line 523 of file qabstractitemmodel.cpp.
 {
     return *qDefaultRoleNames();
 }
indexValid()
bool QAbstractItemModelPrivate::indexValid (const QModelIndex & index) const inline
Definition at line 107 of file qabstractitemmodel_p.h.
{
          return (index.row() >= 0) && (index.column() >= 0) && (index.model() == q_func());
     }
invalidatePersistentIndex()
void QAbstractItemModelPrivate::invalidatePersistentIndex (const QModelIndex & index) inline
Warning
This function is not part of the public interface. clean the QPersistentModelIndex relative to the index if there is one. To be used before an index is invalided
Definition at line 124 of file qabstractitemmodel_p.h.
{
         QHash<QModelIndex, QPersistentModelIndexData *>::iterator it = persistent.indexes.find(index);
         if(it != persistent.indexes.end()) {
             QPersistentModelIndexData *data = *it;
             persistent.indexes.erase(it);
             data->index = QModelIndex();
             data->model = 0;
         }
     }
invalidatePersistentIndexes()
void QAbstractItemModelPrivate::invalidatePersistentIndexes () inline
Definition at line 111 of file qabstractitemmodel_p.h.
{
         foreach (QPersistentModelIndexData *data, persistent.indexes) {
             data->index = QModelIndex();
             data->model = 0;
         }
         persistent.indexes.clear();
     }
itemsAboutToBeMoved()
void QAbstractItemModelPrivate::itemsAboutToBeMoved (const QModelIndex & srcParent, int srcFirst, int srcLast, const QModelIndex & destinationParent, int destinationChild, Qt::Orientation orientation)
Definition at line 638 of file qabstractitemmodel.cpp.
 {
     QVector<QPersistentModelIndexData *> persistent_moved_explicitly;
     QVector<QPersistentModelIndexData *> persistent_moved_in_source;
     QVector<QPersistentModelIndexData *> persistent_moved_in_destination;
     QHash<QModelIndex, QPersistentModelIndexData *>::const_iterator it;
     const QHash<QModelIndex, QPersistentModelIndexData *>::const_iterator begin = persistent.indexes.constBegin();
     const QHash<QModelIndex, QPersistentModelIndexData *>::const_iterator end = persistent.indexes.constEnd();
     const bool sameParent = (srcParent == destinationParent);
     const bool movingUp = (srcFirst > destinationChild);
     for ( it = begin; it != end; ++it) {
         QPersistentModelIndexData *data = *it;
         const QModelIndex &index = data->index;
         const QModelIndex &parent = index.parent();
         const bool isSourceIndex = (parent == srcParent);
         const bool isDestinationIndex = (parent == destinationParent);
         int childPosition;
         if (orientation == Qt::Vertical)
             childPosition = index.row();
         else
             childPosition = index.column();
         if (!index.isValid() || !(isSourceIndex || isDestinationIndex ) )
             continue;
         if (!sameParent && isDestinationIndex) {
             if (childPosition >= destinationChild)
                 persistent_moved_in_destination.append(data);
             continue;
         }
         if (sameParent && movingUp && childPosition < destinationChild)
             continue;
         if (sameParent && !movingUp && childPosition < srcFirst )
             continue;
         if (!sameParent && childPosition < srcFirst)
             continue;
         if (sameParent && (childPosition > srcLast) && (childPosition >= destinationChild ))
             continue;
         if ((childPosition <= srcLast) && (childPosition >= srcFirst)) {
             persistent_moved_explicitly.append(data);
         } else {
             persistent_moved_in_source.append(data);
         }
     }
     persistent.moved.push(persistent_moved_explicitly);
     persistent.moved.push(persistent_moved_in_source);
     persistent.moved.push(persistent_moved_in_destination);
 }
itemsMoved()
void QAbstractItemModelPrivate::itemsMoved (const QModelIndex & srcParent, int srcFirst, int srcLast, const QModelIndex & destinationParent, int destinationChild, Qt::Orientation orientation)
Definition at line 734 of file qabstractitemmodel.cpp.
 {
     QVector<QPersistentModelIndexData *> moved_in_destination = persistent.moved.pop();
     QVector<QPersistentModelIndexData *> moved_in_source = persistent.moved.pop();
     QVector<QPersistentModelIndexData *> moved_explicitly = persistent.moved.pop();
     const bool sameParent = (sourceParent == destinationParent);
     const bool movingUp = (sourceFirst > destinationChild);
     const int explicit_change = (!sameParent || movingUp) ? destinationChild - sourceFirst : destinationChild - sourceLast - 1 ;
     const int source_change = (!sameParent || !movingUp) ? -1*(sourceLast - sourceFirst + 1) : sourceLast - sourceFirst + 1 ;
     const int destination_change = sourceLast - sourceFirst + 1;
     movePersistentIndexes(moved_explicitly, explicit_change, destinationParent, orientation);
     movePersistentIndexes(moved_in_source, source_change, sourceParent, orientation);
     movePersistentIndexes(moved_in_destination, destination_change, destinationParent, orientation);
 }
movePersistentIndexes()
void QAbstractItemModelPrivate::movePersistentIndexes (QVector< QPersistentModelIndexData *> indexes, int change, const QModelIndex & parent, Qt::Orientation orientation)
Moves persistent indexes indexes by amount change.
Warning
This function is not part of the public interface.
The change will be either a change in row value or a change in column value depending on the value of orientation. The indexes may also be moved to a different parent if parent differs from the existing parent for the index.
Definition at line 706 of file qabstractitemmodel.cpp.
 {
     QVector<QPersistentModelIndexData *>::const_iterator it;
     const QVector<QPersistentModelIndexData *>::const_iterator begin = indexes.constBegin();
     const QVector<QPersistentModelIndexData *>::const_iterator end = indexes.constEnd();
     for (it = begin; it != end; ++it)
     {
         QPersistentModelIndexData *data = *it;
         int row = data->index.row();
         int column = data->index.column();
         if (Qt::Vertical == orientation)
             row += change;
         else
             column += change;
         persistent.indexes.erase(persistent.indexes.find(data->index));
         data->index = q_func()->index(row, column, parent);
         if (data->index.isValid()) {
             persistent.insertMultiAtEnd(data->index, data);
         } else {
             qWarning() << "QAbstractItemModel::endMoveRows:  Invalid index (" << row << "," << column << ") in model" << q_func();
         }
     }
 }
removePersistentIndexData()
void QAbstractItemModelPrivate::removePersistentIndexData (QPersistentModelIndexData * data)
Definition at line 575 of file qabstractitemmodel.cpp.
Referenced by QPersistentModelIndexData::destroy().
 {
     if (data->index.isValid()) {
         int removed = persistent.indexes.remove(data->index);
         Q_ASSERT_X(removed == 1, "QPersistentModelIndex::~QPersistentModelIndex",
                    "persistent model indexes corrupted"); //maybe the index was somewhat invalid?
         // This assert may happen if the model use changePersistentIndex in a way that could result on two
         // QPersistentModelIndex pointing to the same index.
         Q_UNUSED(removed);
     }
     // make sure our optimization still works
     for (int i = persistent.moved.count() - 1; i >= 0; --i) {
         int idx = persistent.moved[i].indexOf(data);
         if (idx >= 0)
             persistent.moved[i].remove(idx);
     }
     // update the references to invalidated persistent indexes
     for (int i = persistent.invalidated.count() - 1; i >= 0; --i) {
         int idx = persistent.invalidated[i].indexOf(data);
         if (idx >= 0)
             persistent.invalidated[i].remove(idx);
     }
 }
rowsAboutToBeInserted()
void QAbstractItemModelPrivate::rowsAboutToBeInserted (const QModelIndex & parent, int first, int last)
Definition at line 600 of file qabstractitemmodel.cpp.
 {
     Q_Q(QAbstractItemModel);
     Q_UNUSED(last);
     QVector<QPersistentModelIndexData *> persistent_moved;
     if (first < q->rowCount(parent)) {
         for (QHash<QModelIndex, QPersistentModelIndexData *>::const_iterator it = persistent.indexes.constBegin();
              it != persistent.indexes.constEnd(); ++it) {
             QPersistentModelIndexData *data = *it;
             const QModelIndex &index = data->index;
             if (index.row() >= first && index.isValid() && index.parent() == parent) {
                 persistent_moved.append(data);
             }
         }
     }
     persistent.moved.push(persistent_moved);
 }
rowsAboutToBeRemoved()
void QAbstractItemModelPrivate::rowsAboutToBeRemoved (const QModelIndex & parent, int first, int last)
Definition at line 752 of file qabstractitemmodel.cpp.
 {
     QVector<QPersistentModelIndexData *>  persistent_moved;
     QVector<QPersistentModelIndexData *>  persistent_invalidated;
     // find the persistent indexes that are affected by the change, either by being in the removed subtree
     // or by being on the same level and below the removed rows
     for (QHash<QModelIndex, QPersistentModelIndexData *>::const_iterator it = persistent.indexes.constBegin();
          it != persistent.indexes.constEnd(); ++it) {
         QPersistentModelIndexData *data = *it;
         bool level_changed = false;
         QModelIndex current = data->index;
         while (current.isValid()) {
             QModelIndex current_parent = current.parent();
             if (current_parent == parent) { // on the same level as the change
                 if (!level_changed && current.row() > last) // below the removed rows
                     persistent_moved.append(data);
                 else if (current.row() <= last && current.row() >= first) // in the removed subtree
                     persistent_invalidated.append(data);
                 break;
             }
             current = current_parent;
             level_changed = true;
         }
     }
     persistent.moved.push(persistent_moved);
     persistent.invalidated.push(persistent_invalidated);
 }
rowsInserted()
void QAbstractItemModelPrivate::rowsInserted (const QModelIndex & parent, int first, int last)
Definition at line 619 of file qabstractitemmodel.cpp.
 {
     QVector<QPersistentModelIndexData *> persistent_moved = persistent.moved.pop();
     int count = (last - first) + 1; // it is important to only use the delta, because the change could be nested
     for (QVector<QPersistentModelIndexData *>::const_iterator it = persistent_moved.constBegin();
          it != persistent_moved.constEnd(); ++it) {
         QPersistentModelIndexData *data = *it;
         QModelIndex old = data->index;
         persistent.indexes.erase(persistent.indexes.find(old));
         data->index = q_func()->index(old.row() + count, old.column(), parent);
         if (data->index.isValid()) {
             persistent.insertMultiAtEnd(data->index, data);
         } else {
             qWarning() << "QAbstractItemModel::endInsertRows:  Invalid index (" << old.row() + count << ',' << old.column() << ") in model" << q_func();
         }
     }
 }
rowsRemoved()
void QAbstractItemModelPrivate::rowsRemoved (const QModelIndex & parent, int first, int last)
Definition at line 782 of file qabstractitemmodel.cpp.
 {
     QVector<QPersistentModelIndexData *> persistent_moved = persistent.moved.pop();
     int count = (last - first) + 1; // it is important to only use the delta, because the change could be nested
     for (QVector<QPersistentModelIndexData *>::const_iterator it = persistent_moved.constBegin();
          it != persistent_moved.constEnd(); ++it) {
         QPersistentModelIndexData *data = *it;
         QModelIndex old = data->index;
         persistent.indexes.erase(persistent.indexes.find(old));
         data->index = q_func()->index(old.row() - count, old.column(), parent);
         if (data->index.isValid()) {
             persistent.insertMultiAtEnd(data->index, data);
         } else {
             qWarning() << "QAbstractItemModel::endRemoveRows:  Invalid index (" << old.row() - count << ',' << old.column() << ") in model" << q_func();
         }
     }
     QVector<QPersistentModelIndexData *> persistent_invalidated = persistent.invalidated.pop();
     for (QVector<QPersistentModelIndexData *>::const_iterator it = persistent_invalidated.constBegin();
          it != persistent_invalidated.constEnd(); ++it) {
         QPersistentModelIndexData *data = *it;
         persistent.indexes.erase(persistent.indexes.find(data->index));
         data->index = QModelIndex();
         data->model = 0;
     }
 }
staticEmptyModel()
QAbstractItemModel * QAbstractItemModelPrivate::staticEmptyModel () static
Definition at line 502 of file qabstractitemmodel.cpp.
Referenced by QDataWidgetMapperPrivate::_q_modelDestroyed(), QAbstractItemViewPrivate::_q_modelDestroyed(), QComboBoxPrivate::_q_modelDestroyed(), QAbstractProxyModelPrivate::_q_sourceModelDestroyed(), QDataWidgetMapper::model(), QAbstractItemView::model(), QComboBox::model(), QAbstractProxyModel::QAbstractProxyModel(), QTableView::setModel(), QTreeView::setModel(), QHeaderView::setModel(), QAbstractItemView::setModel(), QAbstractProxyModel::setSourceModel(), and QAbstractProxyModel::sourceModel().
 {
     return qEmptyModel();
 }
variantLessThan()
bool QAbstractItemModelPrivate::variantLessThan (const QVariant & v1, const QVariant & v2) static
This function is used by our Q{Tree,Widget,Table}WidgetModel classes to sort.
Warning
This function is not part of the public interface. return true if value contains a numerical type
Definition at line 562 of file qabstractitemmodel.cpp.
Referenced by QListWidgetItem::operator<(), QTableWidgetItem::operator<(), and QTreeWidgetItem::operator<().
 {
     switch(qMax(typeOfVariant(v1), typeOfVariant(v2)))
     {
     case 0: //integer type
         return v1.toLongLong() < v2.toLongLong();
     case 1: //floating point
         return v1.toReal() < v2.toReal();
     default:
         return v1.toString().localeAwareCompare(v2.toString()) < 0;
     }
 }
Properties
changes
QStack<Change> QAbstractItemModelPrivate::changes
Definition at line 158 of file qabstractitemmodel_p.h.
persistent
struct QAbstractItemModelPrivate::Persistent QAbstractItemModelPrivate::persistent
roleNames
QHash<int,QByteArray> QAbstractItemModelPrivate::roleNames
Definition at line 170 of file qabstractitemmodel_p.h.
supportedDragActions
Qt::DropActions QAbstractItemModelPrivate::supportedDragActions
Definition at line 168 of file qabstractitemmodel_p.h.
The documentation for this class was generated from the following files:
/src/corelib/kernel/qabstractitemmodel_p.h
/src/corelib/kernel/qabstractitemmodel.cpp