Qt 4.8: QHttpNormalRequest Class Reference
QHttpNormalRequest Class Reference
Public Functions
QIODevice * destinationDevice ()
bool hasRequestHeader ()
QHttpNormalRequest (const QHttpRequestHeader &h, QIODevice *d, QIODevice *t)
QHttpNormalRequest (const QHttpRequestHeader &h, QByteArray *d, QIODevice *t)
QHttpRequestHeader requestHeader ()
void setRequestHeader (const QHttpRequestHeader &h)
QIODevice * sourceDevice ()
void start (QHttp *)
~QHttpNormalRequest ()
Public Functions inherited from QHttpRequest
QHttpRequest ()
virtual ~QHttpRequest ()
Protected Variables
QHttpRequestHeader header
Properties
union {
QByteArray * ba
QIODevice * dev
} data
bool is_ba
QIODevice * to
Additional Inherited Members
Public Variables inherited from QHttpRequest
bool finished
int id
Detailed Description
Definition at line 201 of file qhttp.cpp.
Constructors and Destructors
QHttpNormalRequest() [1/2]
QHttpNormalRequest::QHttpNormalRequest (const QHttpRequestHeader & h, QIODevice * d, QIODevice * t) inline
Definition at line 204 of file qhttp.cpp.
                                                                                 :
         header(h), to(t)
     {
         is_ba = false;
         data.dev = d;
     }
QHttpNormalRequest() [2/2]
QHttpNormalRequest::QHttpNormalRequest (const QHttpRequestHeader & h, QByteArray * d, QIODevice * t) inline
Definition at line 211 of file qhttp.cpp.
                                                                                  :
         header(h), to(t)
     {
         is_ba = true;
         data.ba = d;
     }
~QHttpNormalRequest()
QHttpNormalRequest::~QHttpNormalRequest () inline
Definition at line 218 of file qhttp.cpp.
     {
         if (is_ba)
             delete data.ba;
     }
Functions
destinationDevice()
QIODevice * QHttpNormalRequest::destinationDevice () virtual
Implements QHttpRequest.
Definition at line 294 of file qhttp.cpp.
 {
     return to;
 }
hasRequestHeader()
bool QHttpNormalRequest::hasRequestHeader () virtual
Reimplemented from QHttpRequest.
Definition at line 277 of file qhttp.cpp.
 {
     return true;
 }
requestHeader()
QHttpRequestHeader QHttpNormalRequest::requestHeader () virtual
Reimplemented from QHttpRequest.
Definition at line 282 of file qhttp.cpp.
Referenced by QHttpPrivate::addRequest().
 {
     return header;
 }
setRequestHeader()
void QHttpNormalRequest::setRequestHeader (const QHttpRequestHeader & h) inline
Definition at line 227 of file qhttp.cpp.
Referenced by QHttpPrivate::addRequest().
 { header = h; }
sourceDevice()
QIODevice * QHttpNormalRequest::sourceDevice () virtual
Implements QHttpRequest.
Definition at line 287 of file qhttp.cpp.
 {
     if (is_ba)
         return 0;
     return data.dev;
 }
start()
void QHttpNormalRequest::start (QHttp * http) virtual
Implements QHttpRequest.
Reimplemented in QHttpPGHRequest.
Definition at line 244 of file qhttp.cpp.
Referenced by QHttpPGHRequest::start().
 {
     if (!http->d_func()->socket)
         http->d_func()->setSock(0);
     http->d_func()->header = header;
     if (is_ba) {
         http->d_func()->buffer = *data.ba;
         if (http->d_func()->buffer.size() >= 0)
             http->d_func()->header.setContentLength(http->d_func()->buffer.size());
         http->d_func()->postDevice = 0;
     } else {
         http->d_func()->buffer = QByteArray();
         if (data.dev && (data.dev->isOpen() || data.dev->open(QIODevice::ReadOnly))) {
             http->d_func()->postDevice = data.dev;
             if (http->d_func()->postDevice->size() >= 0)
                 http->d_func()->header.setContentLength(http->d_func()->postDevice->size());
         } else {
             http->d_func()->postDevice = 0;
         }
     }
     if (to && (to->isOpen() || to->open(QIODevice::WriteOnly)))
         http->d_func()->toDevice = to;
     else
         http->d_func()->toDevice = 0;
     http->d_func()->reconnectAttempts = 2;
     http->d_func()->_q_slotSendRequest();
 }
Properties
ba
QByteArray* QHttpNormalRequest::ba
Definition at line 237 of file qhttp.cpp.
data
union { ... } QHttpNormalRequest::data
dev
QIODevice* QHttpNormalRequest::dev
Definition at line 238 of file qhttp.cpp.
header
QHttpRequestHeader QHttpNormalRequest::header protected
Definition at line 233 of file qhttp.cpp.
is_ba
bool QHttpNormalRequest::is_ba private
Definition at line 240 of file qhttp.cpp.
to
QIODevice* QHttpNormalRequest::to private
Definition at line 241 of file qhttp.cpp.
The documentation for this class was generated from the following file:
/src/network/access/qhttp.cpp