Qt 4.8: QTextObject Class Reference
QTextObject Class Reference
The QTextObject class is a base class for different kinds of objects that can group parts of a QTextDocument together.
#include <qtextobject.h>
Public Functions
QTextDocumentPrivate * docHandle () const
QTextDocument * document () const
Returns the document this object belongs to.
QTextFormat format () const
Returns the text object's format.
int formatIndex () const
Returns the index of the object's format in the document's internal list of formats.
int objectIndex () const
Returns the object index of this object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QTextObject (QTextDocument *doc)
Creates a new QTextObject for the given document.
QTextObject (QTextObjectPrivate &p, QTextDocument *doc)
void setFormat (const QTextFormat &format)
Sets the text object's format.
~QTextObject ()
Destroys the text object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Friends
class QTextDocumentPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QTextObject class is a base class for different kinds of objects that can group parts of a QTextDocument together.
Note
This class or function is reentrant.
The common grouping text objects are lists (QTextList), frames (QTextFrame), and tables (QTextTable). A text object has an associated format() and document().
There are essentially two kinds of text objects: those that are used with blocks (block formats), and those that are used with characters (character formats). The first kind are derived from QTextBlockGroup, and the second kind from QTextFrame.
You rarely need to use this class directly. When creating custom text objects, you will also need to reimplement QTextDocument::createObject() which acts as a factory method for creating text objects.
See also
QTextDocument, {Text Object Example}
Definition at line 64 of file qtextobject.h.
Constructors and Destructors
QTextObject() [1/2]
QTextObject::QTextObject (QTextDocument * document) explicit protected
Creates a new QTextObject for the given document.
Warning
This function should never be called directly, but only from QTextDocument::createObject().
Definition at line 93 of file qtextobject.cpp.
     : QObject(*new QTextObjectPrivate(doc), doc)
 {
 }
~QTextObject()
QTextObject::~QTextObject () protected
Destroys the text object.
Warning
Text objects are owned by the document, so you should never destroy them yourself.
Definition at line 114 of file qtextobject.cpp.
 {
 }
QTextObject() [2/2]
QTextObject::QTextObject (QTextObjectPrivate & p, QTextDocument * document) protected
Warning
This function is not part of the public interface.
Definition at line 103 of file qtextobject.cpp.
     : QObject(p, doc)
 {
 }
Functions
docHandle()
QTextDocumentPrivate * QTextObject::docHandle () const
Warning
This function is not part of the public interface.
Definition at line 177 of file qtextobject.cpp.
Referenced by QTextTableCell::begin(), QTextFrame::begin(), QTextTableCell::end(), QTextFrame::end(), QTextTableCell::firstPosition(), QTextTableCell::format(), QTextTableCell::lastPosition(), QTextTableCell::setFormat(), and QTextTableCell::tableCellFormatIndex().
 {
     return static_cast<const QTextDocument *>(parent())->docHandle();
 }
document()
QTextDocument * QTextObject::document () const
Returns the document this object belongs to.
See also
format()
Definition at line 169 of file qtextobject.cpp.
Referenced by QTextBlockGroup::blockRemoved(), boundingRectOfFloatsInSelection(), QTextBlock::textList(), and QTextOdfWriter::writeFrame().
 {
     return static_cast<QTextDocument *>(parent());
 }
format()
QTextFormat QTextObject::format () const
Returns the text object's format.
See also
setFormat() document()
Definition at line 123 of file qtextobject.cpp.
Referenced by QTextDocumentLayoutPrivate::blockIndent(), QTextDocumentLayoutPrivate::drawBlock(), QTextList::format(), QTextTable::format(), and QTextFrame::frameFormat().
 {
     Q_D(const QTextObject);
     return d->pieceTable->formatCollection()->objectFormat(d->objectIndex);
 }
formatIndex()
int QTextObject::formatIndex () const
Returns the index of the object's format in the document's internal list of formats.
See also
QTextDocument::allFormats()
Definition at line 135 of file qtextobject.cpp.
Referenced by QTextBlock::iterator::fragment(), QTextBlock::iterator::operator++(), QTextBlock::iterator::operator--(), and QTextOdfWriter::writeBlock().
 {
     Q_D(const QTextObject);
     return d->pieceTable->formatCollection()->objectFormatIndex(d->objectIndex);
 }
objectIndex()
int QTextObject::objectIndex () const
Returns the object index of this object.
This can be used together with QTextFormat::setObjectIndex().
Definition at line 158 of file qtextobject.cpp.
Referenced by QTextList::add(), QTextDocumentPrivate::changeObjectFormat(), QTextCursor::createList(), QTextDocumentPrivate::createObject(), QTextTablePrivate::createTable(), QTextTable::insertColumns(), QTextDocumentPrivate::insertFrame(), QTextCursor::insertImage(), and QTextTable::insertRows().
 {
     Q_D(const QTextObject);
     return d->objectIndex;
 }
setFormat()
void QTextObject::setFormat (const QTextFormat & format) protected
Sets the text object's format.
See also
format()
Definition at line 147 of file qtextobject.cpp.
Referenced by QTextTable::insertColumns(), QTextList::isEmpty(), QTextTable::removeColumns(), QTextList::setFormat(), QTextTable::setFormat(), and QTextFrame::setFrameFormat().
 {
     Q_D(QTextObject);
     int idx = d->pieceTable->formatCollection()->indexForFormat(format);
     d->pieceTable->changeObjectFormat(this, idx);
 }
Friends and Related Functions
QTextDocumentPrivate
friend class QTextDocumentPrivate friend
Definition at line 90 of file qtextobject.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextobject.h
/src/gui/text/qtextobject.cpp