Qt 4.8: QDeclarativeItemPrivate Class Reference
QDeclarativeItemPrivate Class Reference
#include <qdeclarativeitem_p.h>
Classes
struct AnchorLines
struct ChangeListener
Public Types
enum ChangeType {
Geometry = 0x01, SiblingOrder = 0x02, Visibility = 0x04, Opacity = 0x08,
Destroyed = 0x10
}
Public Types inherited from QGraphicsItemPrivate
enum AncestorFlag {
NoFlag = 0, AncestorHandlesChildEvents = 0x1, AncestorClipsChildren = 0x2, AncestorIgnoresTransformations = 0x4,
AncestorFiltersChildEvents = 0x8
}
enum Extra {
ExtraToolTip, ExtraCursor, ExtraCacheData, ExtraMaxDeviceCoordCacheSize,
ExtraBoundingRegionGranularity
}
enum InvalidateReason { OpacityChanged }
Public Functions
QDeclarativeStateGroup * _states ()
void addItemChangeListener (QDeclarativeItemChangeListener *listener, ChangeTypes types)
AnchorLines * anchorLines () const
QDeclarativeAnchors * anchors ()
QDeclarativeAnchorLine baseline () const
QDeclarativeAnchorLine bottom () const
QPointF computeTransformOrigin () const
QDeclarativeListProperty< QObject > data ()
virtual void focusChanged (bool)
virtual void focusScopeItemChange (bool isSubFocusItem)
Subclasses can reimplement this function to be notified when an item becomes a focusScopeItem (or is no longer a focusScopeItem).
qreal height () const
QDeclarativeAnchorLine horizontalCenter () const
virtual qreal implicitHeight () const
virtual void implicitHeightChanged ()
virtual qreal implicitWidth () const
virtual void implicitWidthChanged ()
void init (QDeclarativeItem *parent)
bool isMirrored () const
QDeclarativeAnchorLine left () const
virtual void mirrorChange ()
QDeclarativeItemPrivate ()
void removeItemChangeListener (QDeclarativeItemChangeListener *, ChangeTypes types)
void resetHeight ()
void resetWidth ()
void resolveLayoutMirror ()
QDeclarativeListProperty< QObject > resources ()
QDeclarativeAnchorLine right () const
void setHeight (qreal)
void setImplicitLayoutMirror (bool mirror, bool inherit)
void setLayoutMirror (bool mirror)
virtual void setPosHelper (const QPointF &pos)
Sets the position pos.
void setState (const QString &)
void setWidth (qreal)
virtual void siblingOrderChange ()
Subclasses can reimplement this function to be notified when its siblingIndex order is changed.
QString state () const
QDeclarativeListProperty< QDeclarativeState > states ()
QDeclarativeAnchorLine top () const
virtual void transformChanged ()
QDeclarativeListProperty< QDeclarativeTransition > transitions ()
QDeclarativeAnchorLine verticalCenter () const
qreal width () const
Public Functions inherited from QGraphicsItemPrivate
void addChild (QGraphicsItem *child)
QGraphicsScenePrivate::registerTopLevelItem().
void appendGraphicsTransform (QGraphicsTransform *t)
qreal calcEffectiveOpacity () const
void childrenBoundingRectHelper (QTransform *x, QRectF *rect, QGraphicsItem *topMostEffectItem)
Returns the bounding rect of this item's children (excluding itself).
bool childrenClippedToShape () const
bool childrenCombineOpacity () const
QDeclarativeListProperty< QGraphicsObject > childrenList ()
Returns a list of this item's children.
void clearFocusHelper (bool giveFocusToParent)
void clearSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
qreal combineOpacityFromParent (qreal parentOpacity) const
void combineTransformFromParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
void combineTransformToParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
int depth () const
bool discardUpdateRequest (bool ignoreVisibleBit=false, bool ignoreDirtyBit=false, bool ignoreOpacity=false) const
Returns true if we can discard an update request; otherwise false.
QRectF effectiveBoundingRect (QGraphicsItem *topMostEffectItem=0) const
Returns the effective bounding rect of the item.
QRectF effectiveBoundingRect (const QRectF &rect) const
Returns the effective bounding rect of the given item space rect.
qreal effectiveOpacity () const
void ensureSceneTransform ()
void ensureSceneTransformRecursive (QGraphicsItem **topMostDirtyItem)
void ensureSequentialSiblingIndex ()
Ensures that the list of children is sorted by insertion order, and that the siblingIndexes are packed (no gaps), and start at 0.
void ensureSortedChildren ()
QVariant extra (Extra type) const
QGraphicsItemCache * extraItemCache () const
QPointF genericMapFromScene (const QPointF &pos, const QWidget *viewport) const
Maps the point pos from scene to item coordinates.
bool hasTranslateOnlySceneTransform ()
void initStyleOption (QStyleOptionGraphicsItem *option, const QTransform &worldTransform, const QRegion &exposedRegion, bool allItems=false) const
virtual QVariant inputMethodQueryHelper (Qt::InputMethodQuery query) const
This helper function helped us add input method query support in Qt 4.
void invalidateChildGraphicsEffectsRecursively (InvalidateReason reason)
void invalidateChildrenSceneTransform ()
void invalidateDepthRecursively ()
void invalidateParentGraphicsEffectsRecursively ()
bool isFullyTransparent () const
bool isInvisible () const
bool isOpacityNull () const
virtual bool isProxyWidget () const
bool itemIsUntransformable () const
void markParentDirty (bool updateBoundingRect=false)
QGraphicsItemCache * maybeExtraItemCache () const
void prependGraphicsTransform (QGraphicsTransform *t)
QGraphicsItemPrivate ()
void remapItemPos (QEvent *event, QGraphicsItem *item)
Maps any item pos properties of event to item's coordinate system.
void removeChild (QGraphicsItem *child)
QGraphicsScenePrivate::unregisterTopLevelItem().
void removeExtraItemCache ()
void resetFocusProxy ()
Sets the focusProxy pointer to 0 for all items that have this item as their focusProxy.
void resolveDepth ()
Resolves the stacking depth of this object and all its ancestors.
virtual void resolveFont (uint inheritedMask)
virtual void resolvePalette (uint inheritedMask)
QRectF sceneEffectiveBoundingRect () const
Returns the effective bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect(), taking into account the effect that the item might have.
void sendScenePosChange ()
void setEnabledHelper (bool newEnabled, bool explicitly, bool update=true)
Sets this item's visibility to newEnabled.
void setExtra (Extra type, const QVariant &value)
void setFocusHelper (Qt::FocusReason focusReason, bool climb, bool focusFromHide)
void setIsMemberOfGroup (bool enabled)
Propagates item group membership.
void setParentItemHelper (QGraphicsItem *parent, const QVariant *newParentVariant, const QVariant *thisPointerVariant)
Make sure not to trigger any pure virtual function calls (e.
void setSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
void setTransformHelper (const QTransform &transform)
Sets the transform transform.
void setVisibleHelper (bool newVisible, bool explicitly, bool update=true)
Sets this item's visibility to newVisible.
virtual void subFocusItemChange ()
Subclasses can reimplement this function to be notified when subFocusItem changes.
QTransform transformToParent () const
void unsetExtra (Extra type)
void updateAncestorFlag (QGraphicsItem::GraphicsItemFlag childFlag, AncestorFlag flag=NoFlag, bool enabled=false, bool root=true)
Propagates the ancestor flag flag with value enabled to all this item's children.
void updateAncestorFlags ()
void updateChildWithGraphicsEffectFlagRecursively ()
void updatePaintedViewBoundingRects (bool updateChildren)
virtual void updateSceneTransformFromParent ()
virtual ~QGraphicsItemPrivate ()
Static Public Functions
static void data_append (QDeclarativeListProperty< QObject > *, QObject *)
static QObject * data_at (QDeclarativeListProperty< QObject > *, int)
static void data_clear (QDeclarativeListProperty< QObject > *)
static int data_count (QDeclarativeListProperty< QObject > *)
static qint64 elapsed (QElapsedTimer &)
static QDeclarativeItemPrivate * get (QDeclarativeItem *item)
static void parentProperty (QObject *o, void *rv, QDeclarativeNotifierEndpoint *e)
static void resources_append (QDeclarativeListProperty< QObject > *, QObject *)
static QObject * resources_at (QDeclarativeListProperty< QObject > *, int)
static void resources_clear (QDeclarativeListProperty< QObject > *)
static int resources_count (QDeclarativeListProperty< QObject > *)
static qint64 restart (QElapsedTimer &)
static void setConsistentTime (qint64 t)
static void start (QElapsedTimer &)
static void transform_append (QDeclarativeListProperty< QGraphicsTransform > *list, QGraphicsTransform *)
static QGraphicsTransform * transform_at (QDeclarativeListProperty< QGraphicsTransform > *list, int)
static void transform_clear (QDeclarativeListProperty< QGraphicsTransform > *list)
static int transform_count (QDeclarativeListProperty< QGraphicsTransform > *list)
Static Public Functions inherited from QGraphicsItemPrivate
static void children_append (QDeclarativeListProperty< QGraphicsObject > *list, QGraphicsObject *item)
static QGraphicsObject * children_at (QDeclarativeListProperty< QGraphicsObject > *list, int)
static void children_clear (QDeclarativeListProperty< QGraphicsObject > *list)
static int children_count (QDeclarativeListProperty< QGraphicsObject > *list)
static const QGraphicsItemPrivate * get (const QGraphicsItem *item)
static QGraphicsItemPrivate * get (QGraphicsItem *item)
static bool insertionOrder (QGraphicsItem *a, QGraphicsItem *b)
static bool isOpacityNull (qreal opacity)
static bool movableAncestorIsSelected (const QGraphicsItem *item)
Public Variables
AnchorLines * _anchorLines
QDeclarativeAnchors * _anchors
QDeclarativeContents * _contents
QDeclarativeStateGroup * _stateGroup
QDeclarativeLayoutMirroringAttached * attachedLayoutDirection
QDeclarativeNullableValue< qreal > baselineOffset
QPODVector< ChangeListener, 4 > changeListeners
bool componentComplete:1
bool doneEventPreHandler: 1
bool effectiveLayoutMirror:1
bool hadActiveFocus:1
bool hadFocus:1
bool heightValid:1
bool inheritedLayoutMirror:1
bool inheritMirrorFromItem:1
bool inheritMirrorFromParent:1
bool isMirrorImplicit:1
bool keepMouse:1
QDeclarativeItemKeyFilter * keyHandler
qreal mHeight
qreal mImplicitHeight
qreal mImplicitWidth
qreal mWidth
QDeclarativeItem::TransformOrigin origin:5
QDeclarativeNotifier parentNotifier
bool smooth:1
bool transformOriginDirty: 1
bool widthValid:1
Public Variables inherited from QGraphicsItemPrivate
quint32 acceptDrops: 1
quint32 acceptedMouseButtons: 5
quint32 acceptedTouchBeginEvent: 1
quint32 acceptsHover: 1
quint32 acceptTouchEvents: 1
quint32 allChildrenDirty: 1
quint32 ancestorFlags: 4
quint32 cacheMode: 2
QList< QGraphicsItem * > children
QRectF childrenBoundingRect
quint32 dirty: 1
quint32 dirtyChildren: 1
quint32 dirtyChildrenBoundingRect: 1
quint32 dirtySceneTransform: 1
quint32 enabled: 1
quint32 explicitActivate: 1
quint32 explicitlyDisabled: 1
quint32 explicitlyHidden: 1
QList< ExtraStruct > extras
quint32 filtersDescendantEvents: 1
quint32 flags: 19
QGraphicsItem * focusProxy
QList< QGraphicsItem ** > focusProxyRefs
QGraphicsItem * focusScopeItem
quint32 fullUpdatePending: 1
quint32 geometryChanged: 1
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
int globalStackingOrder
QGraphicsEffect * graphicsEffect
quint32 handlesChildEvents: 1
quint32 hasBoundingRegionGranularity: 1
quint32 hasCursor: 1
quint32 holesInSiblingIndex: 1
quint32 ignoreOpacity: 1
quint32 ignoreVisible: 1
Qt::InputMethodHints imHints
quint32 inDestructor: 1
int index
quint32 inSetPosHelper: 1
quint32 isDeclarativeItem: 1
quint32 isMemberOfGroup: 1
quint32 isObject: 1
quint32 isWidget: 1
int itemDepth
quint32 itemDiscovered: 1
quint32 localCollisionHack: 1
quint32 mayHaveChildWithGraphicsEffect: 1
quint32 mouseSetsFocus: 1
quint32 needSortChildren: 1
QRectF needsRepaint
quint32 notifyBoundingRectChanged: 1
quint32 notifyInvalidated: 1
qreal opacity
quint32 padding: 21
QMap< QWidget *, QRect > paintedViewBoundingRects
quint32 paintedViewBoundingRectsNeedRepaint: 1
QGraphicsItem::PanelModality panelModality
QGraphicsItem * parent
quint32 pendingPolish: 1
QPointF pos
QGraphicsItem * q_ptr
QGraphicsScene * scene
quint32 scenePosDescendants: 1
QTransform sceneTransform
quint32 sceneTransformTranslateOnly: 1
quint32 selected: 1
quint32 sendParentChangeNotification: 1
quint32 sequentialOrdering: 1
int siblingIndex
QGraphicsItem * subFocusItem
TransformData * transformData
quint32 updateDueToGraphicsEffect: 1
quint32 visible: 1
quint32 wantsActive: 1
qreal z
Static Public Variables
static qint64 consistentTime = -1
Detailed Description
Definition at line 117 of file qdeclarativeitem_p.h.
Enumerations
ChangeType
enum QDeclarativeItemPrivate::ChangeType
Enumerator
Geometry
SiblingOrder
Visibility
Opacity
Destroyed
Definition at line 253 of file qdeclarativeitem_p.h.
                     {
         Geometry = 0x01,
         SiblingOrder = 0x02,
         Visibility = 0x04,
         Opacity = 0x08,
         Destroyed = 0x10
     };
Constructors and Destructors
QDeclarativeItemPrivate()
QDeclarativeItemPrivate::QDeclarativeItemPrivate () inline
Definition at line 122 of file qdeclarativeitem_p.h.
     : _anchors(0), _contents(0),
       baselineOffset(0),
       _anchorLines(0),
       _stateGroup(0), origin(QDeclarativeItem::Center),
       widthValid(false), heightValid(false),
       componentComplete(true), keepMouse(false),
       smooth(false), transformOriginDirty(true), doneEventPreHandler(false),
       inheritedLayoutMirror(false), effectiveLayoutMirror(false), isMirrorImplicit(true),
       inheritMirrorFromParent(false), inheritMirrorFromItem(false), hadFocus(false), hadActiveFocus(false), keyHandler(0),
       mWidth(0), mHeight(0), mImplicitWidth(0), mImplicitHeight(0), attachedLayoutDirection(0)
     {
         QGraphicsItemPrivate::acceptedMouseButtons = 0;
         isDeclarativeItem = 1;
         QGraphicsItemPrivate::flags = QGraphicsItem::GraphicsItemFlags(
                                       QGraphicsItem::ItemHasNoContents
                                       | QGraphicsItem::ItemIsFocusable
                                       | QGraphicsItem::ItemNegativeZStacksBehindParent);
     }
Functions
_states()
QDeclarativeStateGroup * QDeclarativeItemPrivate::_states ()
Definition at line 3228 of file qdeclarativeitem.cpp.
 {
     Q_Q(QDeclarativeItem);
     if (!_stateGroup) {
         _stateGroup = new QDeclarativeStateGroup;
         if (!componentComplete)
             _stateGroup->classBegin();
         QObject::connect(_stateGroup, SIGNAL(stateChanged(QString)),
                          q, SIGNAL(stateChanged(QString)));
     }
     return _stateGroup;
 }
addItemChangeListener()
void QDeclarativeItemPrivate::addItemChangeListener (QDeclarativeItemChangeListener * listener, ChangeTypes types) inline
Definition at line 270 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeAnchorsPrivate::addDepend(), QDeclarativeContents::childAdded(), QDeclarativeContents::complete(), QDeclarativeListViewPrivate::createHighlight(), QDeclarativeListViewPrivate::createItem(), QDeclarativePathViewPrivate::getItem(), QDeclarativeFlickablePrivate::init(), QDeclarativeLoaderPrivate::initResize(), QDeclarativeViewPrivate::initResize(), QDeclarativeRow::setLayoutDirection(), QDeclarativeGrid::setLayoutDirection(), QDeclarativeGridViewPrivate::updateFooter(), QDeclarativeListViewPrivate::updateFooter(), QDeclarativeGridViewPrivate::updateHeader(), QDeclarativeListViewPrivate::updateHeader(), and QDeclarativeBasePositionerPrivate::watchChanges().
{
         changeListeners.append(ChangeListener(listener, types));
     }
anchorLines()
AnchorLines* QDeclarativeItemPrivate::anchorLines () const inline
Definition at line 246 of file qdeclarativeitem_p.h.
{
         Q_Q(const QDeclarativeItem);
         if (!_anchorLines) _anchorLines =
             new AnchorLines(const_cast<QDeclarativeItem *>(q));
         return _anchorLines;
     }
anchors()
QDeclarativeAnchors* QDeclarativeItemPrivate::anchors () inline
Definition at line 221 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeAnchorChanges::clearBindings(), QDeclarativeAnchorChanges::execute(), QDeclarativeAnchorChanges::reverse(), and QDeclarativeAnchorChanges::saveCurrentValues().
{
         if (!_anchors) {
             Q_Q(QDeclarativeItem);
             _anchors = new QDeclarativeAnchors(q);
             if (!componentComplete)
                 _anchors->classBegin();
         }
         return _anchors;
     }
baseline()
QDeclarativeAnchorLine QDeclarativeItemPrivate::baseline () const
Warning
This function is not part of the public interface.
Definition at line 2531 of file qdeclarativeitem.cpp.
 {
     return anchorLines()->baseline;
 }
bottom()
QDeclarativeAnchorLine QDeclarativeItemPrivate::bottom () const
Warning
This function is not part of the public interface.
Definition at line 2514 of file qdeclarativeitem.cpp.
 {
     return anchorLines()->bottom;
 }
computeTransformOrigin()
QPointF QDeclarativeItemPrivate::computeTransformOrigin () const
Definition at line 3260 of file qdeclarativeitem.cpp.
 {
     Q_Q(const QDeclarativeItem);
     QRectF br = q->boundingRect();
     switch(origin) {
     default:
     case QDeclarativeItem::TopLeft:
         return QPointF(0, 0);
     case QDeclarativeItem::Top:
         return QPointF(br.width() / 2., 0);
     case QDeclarativeItem::TopRight:
         return QPointF(br.width(), 0);
     case QDeclarativeItem::Left:
         return QPointF(0, br.height() / 2.);
     case QDeclarativeItem::Center:
         return QPointF(br.width() / 2., br.height() / 2.);
     case QDeclarativeItem::Right:
         return QPointF(br.width(), br.height() / 2.);
     case QDeclarativeItem::BottomLeft:
         return QPointF(0, br.height());
     case QDeclarativeItem::Bottom:
         return QPointF(br.width() / 2., br.height());
     case QDeclarativeItem::BottomRight:
         return QPointF(br.width(), br.height());
     }
 }
data()
QDeclarativeListProperty< QObject > QDeclarativeItemPrivate::data ()
Definition at line 2177 of file qdeclarativeitem.cpp.
 {
     return QDeclarativeListProperty<QObject>(q_func(), 0, QDeclarativeItemPrivate::data_append,
                                              QDeclarativeItemPrivate::data_count,
                                              QDeclarativeItemPrivate::data_at,
                                              QDeclarativeItemPrivate::data_clear
                                              );
 }
data_append()
void QDeclarativeItemPrivate::data_append (QDeclarativeListProperty< QObject > * prop, QObject * o) static
Definition at line 1990 of file qdeclarativeitem.cpp.
Referenced by data().
 {
     if (!o)
         return;
     QDeclarativeItem *that = static_cast<QDeclarativeItem *>(prop->object);
     // This test is measurably (albeit only slightly) faster than qobject_cast<>()
     const QMetaObject *mo = o->metaObject();
     while (mo && mo != &QGraphicsObject::staticMetaObject) mo = mo->d.superdata;
     if (mo) {
         QGraphicsObject *graphicsObject = static_cast<QGraphicsObject *>(o);
         QDeclarativeItemPrivate *contentItemPrivate = static_cast<QDeclarativeItemPrivate *>(QGraphicsItemPrivate::get(graphicsObject));
         if (contentItemPrivate->componentComplete) {
             graphicsObject->setParentItem(that);
         } else {
             contentItemPrivate->setParentItemHelper(that, /*newParentVariant=*/0, /*thisPointerVariant=*/0);
         }
     } else {
         o->setParent(that);
     }
 }
data_at()
QObject * QDeclarativeItemPrivate::data_at (QDeclarativeListProperty< QObject > * prop, int i) static
Definition at line 2047 of file qdeclarativeitem.cpp.
Referenced by data().
 {
     int resourcesCount = resources_count(prop);
     if (i < resourcesCount)
         return resources_at(prop, i);
     const int j = i - resourcesCount;
     if (j < children_count_helper(prop))
         return children_at_helper(prop, j);
     return 0;
 }
data_clear()
void QDeclarativeItemPrivate::data_clear (QDeclarativeListProperty< QObject > * prop) static
Definition at line 2058 of file qdeclarativeitem.cpp.
Referenced by data().
 {
     resources_clear(prop);
     children_clear_helper(prop);
 }
data_count()
int QDeclarativeItemPrivate::data_count (QDeclarativeListProperty< QObject > * prop) static
Definition at line 2042 of file qdeclarativeitem.cpp.
Referenced by data().
 {
     return resources_count(prop) + children_count_helper(prop);
 }
elapsed()
qint64 QDeclarativeItemPrivate::elapsed (QElapsedTimer & t) static
Definition at line 4055 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeFlickablePrivate::handleMouseMoveEvent(), QDeclarativePathViewPrivate::handleMouseReleaseEvent(), and QDeclarativeFlickablePrivate::handleMouseReleaseEvent().
 {
     if (QDeclarativeItemPrivate::consistentTime == -1)
         return t.elapsed();
     else
         return ((QElapsedTimerConsistentTimeHack*)&t)->elapsed();
 }
focusChanged()
void QDeclarativeItemPrivate::focusChanged (bool flag) virtual
Reimplemented in QDeclarativeTextInputPrivate, and QDeclarativeTextEditPrivate.
Definition at line 2981 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeTextEditPrivate::focusChanged(), QDeclarativeTextInputPrivate::focusChanged(), and QDeclarativeTextInputPrivate::xToPos().
 {
     Q_Q(QDeclarativeItem);
     if (hadActiveFocus != flag) {
         hadActiveFocus = flag;
         emit q->activeFocusChanged(flag);
     }
     QDeclarativeItem *focusItem = q;
     for (QDeclarativeItem *p = q->parentItem(); p; p = p->parentItem()) {
         if (p->flags() & QGraphicsItem::ItemIsFocusScope) {
             if (!flag && QGraphicsItemPrivate::get(p)->focusScopeItem != focusItem)
                 break;
             if (p->d_func()->hadActiveFocus != flag) {
                 p->d_func()->hadActiveFocus = flag;
                 emit p->activeFocusChanged(flag);
             }
             focusItem = p;
         }
     }
     // For all but the top most focus scope/item this will be called for us by QGraphicsItem.
     focusItem->d_func()->focusScopeItemChange(flag);
 }
focusScopeItemChange()
virtual void QDeclarativeItemPrivate::focusScopeItemChange (bool isSubFocusItem) inline virtual
Subclasses can reimplement this function to be notified when an item becomes a focusScopeItem (or is no longer a focusScopeItem).
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItemPrivate.
Definition at line 316 of file qdeclarativeitem_p.h.
     {
         if (hadFocus != isSubFocusItem) {
             hadFocus = isSubFocusItem;
             emit q_func()->focusChanged(isSubFocusItem);
         }
     }
get()
static QDeclarativeItemPrivate* QDeclarativeItemPrivate::get (QDeclarativeItem * item) inline static
Definition at line 212 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeContents::childAdded(), QDeclarativeContents::childRemoved(), QDeclarativeAnchorChanges::clearBindings(), QDeclarativeContents::complete(), QDeclarativeRow::doPositioning(), QDeclarativeGrid::doPositioning(), QDeclarativeAnchorChanges::execute(), init(), QDeclarativeContents::itemDestroyed(), QDeclarativeKeyNavigationAttached::keyPressed(), QDeclarativeKeyNavigationAttached::keyReleased(), QDeclarativeLayoutMirroringAttached::QDeclarativeLayoutMirroringAttached(), QDeclarativeColumn::reportConflictingAnchors(), QDeclarativeRow::reportConflictingAnchors(), QDeclarativeGrid::reportConflictingAnchors(), QDeclarativeFlow::reportConflictingAnchors(), resolveLayoutMirror(), QDeclarativeAnchorChanges::reverse(), QDeclarativeAnchorChanges::rewind(), QDeclarativeAnchorChanges::saveCurrentValues(), QDeclarativeAnchorChanges::saveOriginals(), setImplicitLayoutMirror(), QDeclarativeRow::setLayoutDirection(), QDeclarativeGrid::setLayoutDirection(), and QDeclarativeContents::~QDeclarativeContents().
     {
         return item->d_func();
     }
height()
qreal QDeclarativeItemPrivate::height () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItemPrivate.
Definition at line 3725 of file qdeclarativeitem.cpp.
 {
     return mHeight;
 }
horizontalCenter()
QDeclarativeAnchorLine QDeclarativeItemPrivate::horizontalCenter () const
Warning
This function is not part of the public interface.
Definition at line 2498 of file qdeclarativeitem.cpp.
 {
     return anchorLines()->hCenter;
 }
implicitHeight()
qreal QDeclarativeItemPrivate::implicitHeight () const virtual
Definition at line 3768 of file qdeclarativeitem.cpp.
 {
     return mImplicitHeight;
 }
implicitHeightChanged()
void QDeclarativeItemPrivate::implicitHeightChanged () virtual
Reimplemented in QDeclarativeImplicitSizePaintedItemPrivate, and QDeclarativeImplicitSizeItemPrivate.
Definition at line 3762 of file qdeclarativeitem.cpp.
 {
     Q_Q(QDeclarativeItem);
     emit q->implicitHeightChanged();
 }
implicitWidth()
qreal QDeclarativeItemPrivate::implicitWidth () const virtual
Reimplemented in QDeclarativeTextPrivate, and QDeclarativeTextEditPrivate.
Definition at line 3642 of file qdeclarativeitem.cpp.
 {
     return mImplicitWidth;
 }
implicitWidthChanged()
void QDeclarativeItemPrivate::implicitWidthChanged () virtual
Reimplemented in QDeclarativeImplicitSizePaintedItemPrivate, and QDeclarativeImplicitSizeItemPrivate.
Definition at line 3636 of file qdeclarativeitem.cpp.
 {
     Q_Q(QDeclarativeItem);
     emit q->implicitWidthChanged();
 }
init()
void QDeclarativeItemPrivate::init (QDeclarativeItem * parent) inline
Definition at line 142 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeTextInputPrivate::xToPos().
     {
         Q_Q(QDeclarativeItem);
         if (parent) {
             QDeclarative_setParent_noEvent(q, parent);
             q->setParentItem(parent);
             QDeclarativeItemPrivate *parentPrivate = QDeclarativeItemPrivate::get(parent);
             setImplicitLayoutMirror(parentPrivate->inheritedLayoutMirror, parentPrivate->inheritMirrorFromParent);
         }
         baselineOffset.invalidate();
         mouseSetsFocus = false;
     }
isMirrored()
bool QDeclarativeItemPrivate::isMirrored () const inline
Definition at line 155 of file qdeclarativeitem_p.h.
{
         return effectiveLayoutMirror;
     }
left()
QDeclarativeAnchorLine QDeclarativeItemPrivate::left () const
Warning
This function is not part of the public interface.
Definition at line 2482 of file qdeclarativeitem.cpp.
 {
     return anchorLines()->left;
 }
mirrorChange()
virtual void QDeclarativeItemPrivate::mirrorChange () inline virtual
Reimplemented in QDeclarativeListViewPrivate, QDeclarativeGridViewPrivate, QDeclarativeBasePositionerPrivate, QDeclarativeTextInputPrivate, QDeclarativeTextEditPrivate, and QDeclarativeTextPrivate.
Definition at line 341 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeTextInputPrivate::xToPos().
 {};
parentProperty()
void QDeclarativeItemPrivate::parentProperty (QObject * o, void * rv, QDeclarativeNotifierEndpoint * e) static
Definition at line 2132 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeFastProperties::QDeclarativeFastProperties().
 {
     QDeclarativeItem *item = static_cast<QDeclarativeItem*>(o);
     if (e)
         e->connect(&item->d_func()->parentNotifier);
     *((QDeclarativeItem **)rv) = item->parentItem();
 }
removeItemChangeListener()
void QDeclarativeItemPrivate::removeItemChangeListener (QDeclarativeItemChangeListener * listener, ChangeTypes types)
Definition at line 2381 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeContents::childRemoved(), QDeclarativeLoaderPrivate::clear(), QDeclarativeContents::itemDestroyed(), QDeclarativePathViewPrivate::releaseItem(), QDeclarativeListViewPrivate::releaseItem(), QDeclarativeAnchorsPrivate::remDepend(), QDeclarativeRow::setLayoutDirection(), QDeclarativeGrid::setLayoutDirection(), QDeclarativeView::setResizeMode(), QDeclarativeBasePositionerPrivate::unwatchChanges(), QDeclarativeContents::~QDeclarativeContents(), and QDeclarativeLoader::~QDeclarativeLoader().
 {
     ChangeListener change(listener, types);
     changeListeners.removeOne(change);
 }
resetHeight()
void QDeclarativeItemPrivate::resetHeight () virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItemPrivate.
Definition at line 3755 of file qdeclarativeitem.cpp.
 {
     Q_Q(QDeclarativeItem);
     heightValid = false;
     q->setImplicitHeight(q->implicitHeight());
 }
resetWidth()
void QDeclarativeItemPrivate::resetWidth () virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItemPrivate.
Definition at line 3629 of file qdeclarativeitem.cpp.
 {
     Q_Q(QDeclarativeItem);
     widthValid = false;
     q->setImplicitWidth(q->implicitWidth());
 }
resolveLayoutMirror()
void QDeclarativeItemPrivate::resolveLayoutMirror ()
Definition at line 918 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeLayoutMirroringAttached::resetEnabled(), QDeclarativeLayoutMirroringAttached::setChildrenInherit(), and QDeclarativeLayoutMirroringAttached::setEnabled().
 {
     Q_Q(QDeclarativeItem);
     if (QDeclarativeItem *parentItem = q->parentItem()) {
         QDeclarativeItemPrivate *parentPrivate = QDeclarativeItemPrivate::get(parentItem);
         setImplicitLayoutMirror(parentPrivate->inheritedLayoutMirror, parentPrivate->inheritMirrorFromParent);
     } else {
         setImplicitLayoutMirror(isMirrorImplicit ? false : effectiveLayoutMirror, inheritMirrorFromItem);
     }
 }
resources()
QDeclarativeListProperty< QObject > QDeclarativeItemPrivate::resources ()
Definition at line 3007 of file qdeclarativeitem.cpp.
 {
     return QDeclarativeListProperty<QObject>(q_func(), 0, QDeclarativeItemPrivate::resources_append,
                                              QDeclarativeItemPrivate::resources_count,
                                              QDeclarativeItemPrivate::resources_at,
                                              QDeclarativeItemPrivate::resources_clear
                                              );
 }
resources_append()
void QDeclarativeItemPrivate::resources_append (QDeclarativeListProperty< QObject > * prop, QObject * o) static
Definition at line 2073 of file qdeclarativeitem.cpp.
Referenced by resources().
 {
     o->setParent(prop->object);
 }
resources_at()
QObject * QDeclarativeItemPrivate::resources_at (QDeclarativeListProperty< QObject > * prop, int index) static
Definition at line 2064 of file qdeclarativeitem.cpp.
Referenced by resources().
 {
     const QObjectList children = prop->object->children();
     if (index < children.count())
         return children.at(index);
     else
         return 0;
 }
resources_clear()
void QDeclarativeItemPrivate::resources_clear (QDeclarativeListProperty< QObject > * prop) static
Definition at line 2083 of file qdeclarativeitem.cpp.
Referenced by resources().
 {
     const QObjectList children = prop->object->children();
     for (int index = 0; index < children.count(); index++)
         children.at(index)->setParent(0);
 }
resources_count()
int QDeclarativeItemPrivate::resources_count (QDeclarativeListProperty< QObject > * prop) static
Definition at line 2078 of file qdeclarativeitem.cpp.
Referenced by resources().
 {
     return prop->object->children().count();
 }
restart()
qint64 QDeclarativeItemPrivate::restart (QElapsedTimer & t) static
Definition at line 4063 of file qdeclarativeitem.cpp.
Referenced by QDeclarativePathViewPrivate::handleMouseMoveEvent(), QDeclarativeFlickablePrivate::handleMouseMoveEvent(), and QDeclarativeFlickable::viewportMoved().
 {
     if (QDeclarativeItemPrivate::consistentTime == -1)
         return t.restart();
     else
         return ((QElapsedTimerConsistentTimeHack*)&t)->restart();
 }
right()
QDeclarativeAnchorLine QDeclarativeItemPrivate::right () const
Warning
This function is not part of the public interface.
Definition at line 2490 of file qdeclarativeitem.cpp.
 {
     return anchorLines()->right;
 }
setConsistentTime()
void QDeclarativeItemPrivate::setConsistentTime (qint64 t) static
Definition at line 4020 of file qdeclarativeitem.cpp.
 {
     consistentTime = t;
 }
setHeight()
void QDeclarativeItemPrivate::setHeight (qreal h) virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItemPrivate.
Definition at line 3733 of file qdeclarativeitem.cpp.
 {
     Q_Q(QDeclarativeItem);
     if (qIsNaN(h))
         return;
     heightValid = true;
     if (mHeight == h)
         return;
     qreal oldHeight = mHeight;
     q->prepareGeometryChange();
     mHeight = h;
     q->geometryChanged(QRectF(q->x(), q->y(), width(), height()),
                     QRectF(q->x(), q->y(), width(), oldHeight));
 }
setImplicitLayoutMirror()
void QDeclarativeItemPrivate::setImplicitLayoutMirror (bool mirror, bool inherit)
Definition at line 929 of file qdeclarativeitem.cpp.
Referenced by setImplicitLayoutMirror().
 {
     inherit = inherit || inheritMirrorFromItem;
     if (!isMirrorImplicit && inheritMirrorFromItem)
         mirror = effectiveLayoutMirror;
     if (mirror == inheritedLayoutMirror && inherit == inheritMirrorFromParent)
         return;
     inheritMirrorFromParent = inherit;
     inheritedLayoutMirror = inheritMirrorFromParent ? mirror : false;
     if (isMirrorImplicit)
         setLayoutMirror(inherit ? inheritedLayoutMirror : false);
     for (int i = 0; i < children.count(); ++i) {
         if (QDeclarativeItem *child = qobject_cast<QDeclarativeItem *>(children.at(i))) {
             QDeclarativeItemPrivate *childPrivate = QDeclarativeItemPrivate::get(child);
             childPrivate->setImplicitLayoutMirror(inheritedLayoutMirror, inheritMirrorFromParent);
         }
     }
 }
setLayoutMirror()
void QDeclarativeItemPrivate::setLayoutMirror (bool mirror)
Definition at line 950 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeLayoutMirroringAttached::setEnabled().
 {
     if (mirror != effectiveLayoutMirror) {
         effectiveLayoutMirror = mirror;
         if (_anchors) {
             _anchors->d_func()->fillChanged();
             _anchors->d_func()->centerInChanged();
             _anchors->d_func()->updateHorizontalAnchors();
         }
         mirrorChange();
         if (attachedLayoutDirection) {
             emit attachedLayoutDirection->enabledChanged();
         }
     }
 }
setPosHelper()
virtual void QDeclarativeItemPrivate::setPosHelper (const QPointF & pos) inline virtual
Sets the position pos.
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItemPrivate.
Definition at line 307 of file qdeclarativeitem_p.h.
     {
         Q_Q(QDeclarativeItem);
         QRectF oldGeometry(this->pos.x(), this->pos.y(), mWidth, mHeight);
         QGraphicsItemPrivate::setPosHelper(pos);
         q->geometryChanged(QRectF(this->pos.x(), this->pos.y(), mWidth, mHeight), oldGeometry);
     }
setState()
void QDeclarativeItemPrivate::setState (const QString & state)
Definition at line 3163 of file qdeclarativeitem.cpp.
 {
     _states()->setState(state);
 }
setWidth()
void QDeclarativeItemPrivate::setWidth (qreal w) virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItemPrivate.
Definition at line 3607 of file qdeclarativeitem.cpp.
 {
     Q_Q(QDeclarativeItem);
     if (qIsNaN(w))
         return;
     widthValid = true;
     if (mWidth == w)
         return;
     qreal oldWidth = mWidth;
     q->prepareGeometryChange();
     mWidth = w;
     q->geometryChanged(QRectF(q->x(), q->y(), width(), height()),
                     QRectF(q->x(), q->y(), oldWidth, height()));
 }
siblingOrderChange()
virtual void QDeclarativeItemPrivate::siblingOrderChange () inline virtual
Subclasses can reimplement this function to be notified when its siblingIndex order is changed.
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItemPrivate.
Definition at line 325 of file qdeclarativeitem_p.h.
     {
         Q_Q(QDeclarativeItem);
         for(int ii = 0; ii < changeListeners.count(); ++ii) {
             const QDeclarativeItemPrivate::ChangeListener &change = changeListeners.at(ii);
             if (change.types & QDeclarativeItemPrivate::SiblingOrder) {
                 change.listener->itemSiblingOrderChanged(q);
             }
         }
     }
start()
void QDeclarativeItemPrivate::start (QElapsedTimer & t) static
Definition at line 4047 of file qdeclarativeitem.cpp.
Referenced by QDeclarativePathViewPrivate::handleMousePressEvent(), and QDeclarativeFlickablePrivate::handleMousePressEvent().
 {
     if (QDeclarativeItemPrivate::consistentTime == -1)
         t.start();
     else
         ((QElapsedTimerConsistentTimeHack*)&t)->start();
 }
state()
QString QDeclarativeItemPrivate::state () const
Definition at line 3155 of file qdeclarativeitem.cpp.
 {
     if (!_stateGroup)
         return QString();
     else
         return _stateGroup->state();
 }
states()
QDeclarativeListProperty< QDeclarativeState > QDeclarativeItemPrivate::states ()
Definition at line 3040 of file qdeclarativeitem.cpp.
 {
     return _states()->statesProperty();
 }
top()
QDeclarativeAnchorLine QDeclarativeItemPrivate::top () const
Warning
This function is not part of the public interface.
Definition at line 2506 of file qdeclarativeitem.cpp.
 {
     return anchorLines()->top;
 }
transform_append()
void QDeclarativeItemPrivate::transform_append (QDeclarativeListProperty< QGraphicsTransform > * list, QGraphicsTransform * item) static
Definition at line 2101 of file qdeclarativeitem.cpp.
 {
     QGraphicsObject *object = qobject_cast<QGraphicsObject *>(list->object);
     if (object && item) // QGraphicsItem applies the list in the wrong order, so we prepend.
         QGraphicsItemPrivate::get(object)->prependGraphicsTransform(item);
 }
transform_at()
QGraphicsTransform * QDeclarativeItemPrivate::transform_at (QDeclarativeListProperty< QGraphicsTransform > * list, int idx) static
Definition at line 2108 of file qdeclarativeitem.cpp.
 {
     QGraphicsObject *object = qobject_cast<QGraphicsObject *>(list->object);
     if (object) {
         QGraphicsItemPrivate *d = QGraphicsItemPrivate::get(object);
         if (!d->transformData)
             return 0;
         return d->transformData->graphicsTransforms.at(idx);
     } else {
         return 0;
     }
 }
transform_clear()
void QDeclarativeItemPrivate::transform_clear (QDeclarativeListProperty< QGraphicsTransform > * list) static
Definition at line 2121 of file qdeclarativeitem.cpp.
 {
     QGraphicsObject *object = qobject_cast<QGraphicsObject *>(list->object);
     if (object) {
         QGraphicsItemPrivate *d = QGraphicsItemPrivate::get(object);
         if (!d->transformData)
             return;
         object->setTransformations(QList<QGraphicsTransform *>());
     }
 }
transform_count()
int QDeclarativeItemPrivate::transform_count (QDeclarativeListProperty< QGraphicsTransform > * list) static
Definition at line 2090 of file qdeclarativeitem.cpp.
 {
     QGraphicsObject *object = qobject_cast<QGraphicsObject *>(list->object);
     if (object) {
         QGraphicsItemPrivate *d = QGraphicsItemPrivate::get(object);
         return d->transformData ? d->transformData->graphicsTransforms.size() : 0;
     } else {
         return 0;
     }
 }
transformChanged()
void QDeclarativeItemPrivate::transformChanged () virtual
Reimplemented from QGraphicsItemPrivate.
Definition at line 3422 of file qdeclarativeitem.cpp.
 {
     Q_Q(QDeclarativeItem);
     if (transformOriginDirty) {
         q->QGraphicsItem::setTransformOriginPoint(computeTransformOrigin());
         transformOriginDirty = false;
     }
 }
transitions()
QDeclarativeListProperty< QDeclarativeTransition > QDeclarativeItemPrivate::transitions ()
Definition at line 3070 of file qdeclarativeitem.cpp.
 {
     return _states()->transitionsProperty();
 }
verticalCenter()
QDeclarativeAnchorLine QDeclarativeItemPrivate::verticalCenter () const
Warning
This function is not part of the public interface.
Definition at line 2522 of file qdeclarativeitem.cpp.
 {
     return anchorLines()->vCenter;
 }
width()
qreal QDeclarativeItemPrivate::width () const virtual
Warning
This function is not part of the public interface. Return the width of the item
Reimplemented from QGraphicsItemPrivate.
Definition at line 3599 of file qdeclarativeitem.cpp.
 {
     return mWidth;
 }
Properties
_anchorLines
AnchorLines* QDeclarativeItemPrivate::_anchorLines mutable
Definition at line 245 of file qdeclarativeitem_p.h.
_anchors
QDeclarativeAnchors* QDeclarativeItemPrivate::_anchors
Definition at line 230 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeColumn::reportConflictingAnchors(), QDeclarativeRow::reportConflictingAnchors(), QDeclarativeGrid::reportConflictingAnchors(), and QDeclarativeFlow::reportConflictingAnchors().
_contents
QDeclarativeContents* QDeclarativeItemPrivate::_contents
Definition at line 231 of file qdeclarativeitem_p.h.
_stateGroup
QDeclarativeStateGroup* QDeclarativeItemPrivate::_stateGroup
Definition at line 277 of file qdeclarativeitem_p.h.
attachedLayoutDirection
QDeclarativeLayoutMirroringAttached* QDeclarativeItemPrivate::attachedLayoutDirection
Definition at line 302 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeLayoutMirroringAttached::QDeclarativeLayoutMirroringAttached().
baselineOffset
QDeclarativeNullableValue<qreal> QDeclarativeItemPrivate::baselineOffset
Definition at line 233 of file qdeclarativeitem_p.h.
changeListeners
QPODVector<ChangeListener,4> QDeclarativeItemPrivate::changeListeners
Definition at line 274 of file qdeclarativeitem_p.h.
componentComplete
bool QDeclarativeItemPrivate::componentComplete
Definition at line 282 of file qdeclarativeitem_p.h.
Referenced by children_clear_helper(), and data_append().
consistentTime
qint64 QDeclarativeItemPrivate::consistentTime = -1 static
Definition at line 341 of file qdeclarativeitem_p.h.
Referenced by elapsed(), QElapsedTimerConsistentTimeHack::elapsed(), operator<<(), restart(), QElapsedTimerConsistentTimeHack::restart(), start(), and QElapsedTimerConsistentTimeHack::start().
doneEventPreHandler
bool QDeclarativeItemPrivate::doneEventPreHandler
Definition at line 286 of file qdeclarativeitem_p.h.
effectiveLayoutMirror
bool QDeclarativeItemPrivate::effectiveLayoutMirror
Definition at line 288 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeBasePositionerPrivate::isLeftToRight(), QDeclarativeKeyNavigationAttached::keyPressed(), QDeclarativeKeyNavigationAttached::keyReleased(), QDeclarativeLayoutMirroringAttached::qmlAttachedProperties(), and QDeclarativeLayoutMirroringAttached::setEnabled().
hadActiveFocus
bool QDeclarativeItemPrivate::hadActiveFocus
Definition at line 293 of file qdeclarativeitem_p.h.
hadFocus
bool QDeclarativeItemPrivate::hadFocus
Definition at line 292 of file qdeclarativeitem_p.h.
heightValid
bool QDeclarativeItemPrivate::heightValid
Definition at line 281 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeLoaderPrivate::initResize(), QDeclarativeAnchorChanges::rewind(), and QDeclarativeAnchorChanges::saveOriginals().
inheritedLayoutMirror
bool QDeclarativeItemPrivate::inheritedLayoutMirror
Definition at line 287 of file qdeclarativeitem_p.h.
Referenced by init(), and resolveLayoutMirror().
inheritMirrorFromItem
bool QDeclarativeItemPrivate::inheritMirrorFromItem
Definition at line 291 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeLayoutMirroringAttached::resetEnabled(), QDeclarativeLayoutMirroringAttached::setChildrenInherit(), and QDeclarativeLayoutMirroringAttached::setEnabled().
inheritMirrorFromParent
bool QDeclarativeItemPrivate::inheritMirrorFromParent
Definition at line 290 of file qdeclarativeitem_p.h.
Referenced by init(), and resolveLayoutMirror().
isMirrorImplicit
bool QDeclarativeItemPrivate::isMirrorImplicit
Definition at line 289 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeLayoutMirroringAttached::resetEnabled(), and QDeclarativeLayoutMirroringAttached::setEnabled().
keepMouse
bool QDeclarativeItemPrivate::keepMouse
Definition at line 283 of file qdeclarativeitem_p.h.
keyHandler
QDeclarativeItemKeyFilter* QDeclarativeItemPrivate::keyHandler
Definition at line 295 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeItemKeyFilter::QDeclarativeItemKeyFilter().
mHeight
qreal QDeclarativeItemPrivate::mHeight
Definition at line 298 of file qdeclarativeitem_p.h.
mImplicitHeight
qreal QDeclarativeItemPrivate::mImplicitHeight
Definition at line 300 of file qdeclarativeitem_p.h.
mImplicitWidth
qreal QDeclarativeItemPrivate::mImplicitWidth
Definition at line 299 of file qdeclarativeitem_p.h.
mWidth
qreal QDeclarativeItemPrivate::mWidth
Definition at line 297 of file qdeclarativeitem_p.h.
origin
QDeclarativeItem::TransformOrigin QDeclarativeItemPrivate::origin
Definition at line 279 of file qdeclarativeitem_p.h.
parentNotifier
QDeclarativeNotifier QDeclarativeItemPrivate::parentNotifier
Definition at line 218 of file qdeclarativeitem_p.h.
smooth
bool QDeclarativeItemPrivate::smooth
Definition at line 284 of file qdeclarativeitem_p.h.
transformOriginDirty
bool QDeclarativeItemPrivate::transformOriginDirty
Definition at line 285 of file qdeclarativeitem_p.h.
widthValid
bool QDeclarativeItemPrivate::widthValid
Definition at line 280 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeLoaderPrivate::initResize(), QDeclarativeAnchorChanges::rewind(), and QDeclarativeAnchorChanges::saveOriginals().
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativeitem_p.h
/src/declarative/graphicsitems/qdeclarativeitem.cpp