Qt 4.8: QGridLayout Class Reference
QGridLayout Class Reference
The QGridLayout class lays out widgets in a grid.
#include <qgridlayout.h>
Public Functions
void addItem (QLayoutItem *item, int row, int column, int rowSpan=1, int columnSpan=1, Qt::Alignment=0)
Adds item at position row, column, spanning rowSpan rows and columnSpan columns, and aligns it according to alignment.
void addLayout (QLayout *, int row, int column, Qt::Alignment=0)
Places the layout at position (row, column) in the grid.
void addLayout (QLayout *, int row, int column, int rowSpan, int columnSpan, Qt::Alignment=0)
This version adds the layout layout to the cell grid, spanning multiple rows/columns.
void addWidget (QWidget *w)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void addWidget (QWidget *, int row, int column, Qt::Alignment=0)
Adds the given widget to the cell grid at row, column.
void addWidget (QWidget *, int row, int column, int rowSpan, int columnSpan, Qt::Alignment=0)
This version adds the given widget to the cell grid, spanning multiple rows/columns.
QRect cellRect (int row, int column) const
Returns the geometry of the cell with row row and column column in the grid.
int columnCount () const
Returns the number of columns in this grid.
int columnMinimumWidth (int column) const
Returns the column spacing for column column.
int columnStretch (int column) const
Returns the stretch factor for column column.
int count () const
Reimplemented Function
Qt::Orientations expandingDirections () const
Reimplemented Function
void getItemPosition (int idx, int *row, int *column, int *rowSpan, int *columnSpan)
Returns the position information of the item with the given index.
bool hasHeightForWidth () const
Reimplemented Function
int heightForWidth (int) const
Reimplemented Function
int horizontalSpacing () const
the spacing between widgets that are laid out side by side
void invalidate ()
Reimplemented Function
QLayoutItem * itemAt (int index) const
Reimplemented Function
QLayoutItem * itemAtPosition (int row, int column) const
Returns the layout item that occupies cell (row, column), or 0 if the cell is empty.
QSize maximumSize () const
Reimplemented Function
int minimumHeightForWidth (int) const
Reimplemented Function
QSize minimumSize () const
Reimplemented Function
Qt::Corner originCorner () const
Returns the corner that's used for the grid's origin, i.e.
QGridLayout (QWidget *parent)
Constructs a new QGridLayout with parent widget, parent.
QGridLayout ()
Constructs a new grid layout.
int rowCount () const
Returns the number of rows in this grid.
int rowMinimumHeight (int row) const
Returns the minimum width set for row row.
int rowStretch (int row) const
Returns the stretch factor for row row.
void setColumnMinimumWidth (int column, int minSize)
Sets the minimum width of column column to minSize pixels.
void setColumnStretch (int column, int stretch)
Sets the stretch factor of column column to stretch.
void setDefaultPositioning (int n, Qt::Orientation orient)
void setGeometry (const QRect &)
Reimplemented Function
void setHorizontalSpacing (int spacing)
void setOriginCorner (Qt::Corner)
Sets the grid's origin corner, i.e.
void setRowMinimumHeight (int row, int minSize)
Sets the minimum height of row row to minSize pixels.
void setRowStretch (int row, int stretch)
Sets the stretch factor of row row to stretch.
void setSpacing (int spacing)
This function sets both the vertical and horizontal spacing to spacing.
void setVerticalSpacing (int spacing)
QSize sizeHint () const
Reimplemented Function
int spacing () const
If the vertical spacing is equal to the horizontal spacing, this function returns that value; otherwise it return -1.
QLayoutItem * takeAt (int index)
Reimplemented Function
int verticalSpacing () const
the spacing between widgets that are laid out on top of each other
~QGridLayout ()
Destroys the grid layout.
Public Functions inherited from QLayout
bool activate ()
Redoes the layout for parentWidget() if necessary.
void addWidget (QWidget *w)
Adds widget w to this layout in a manner specific to the layout.
QMargins contentsMargins () const
Returns the margins used around the layout.
QRect contentsRect () const
Returns the layout's geometry() rectangle, but taking into account the contents margins.
Qt::Orientations expandingDirections () const
Returns whether this layout can make use of more space than sizeHint().
QRect geometry () const
Reimplemented Function
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
virtual int indexOf (QWidget *) const
Searches for widget widget in this layout (not including child layouts).
void invalidate ()
Reimplemented Function
bool isEmpty () const
Reimplemented Function
bool isEnabled () const
Returns true if the layout is enabled; otherwise returns false.
QLayout * layout ()
Reimplemented Function
int margin () const
QSize maximumSize () const
Returns the maximum size of this layout.
QWidget * menuBar () const
Returns the menu bar set for this layout, or 0 if no menu bar is set.
QSize minimumSize () const
Returns the minimum size of this layout.
QWidget * parentWidget () const
Returns the parent widget of this layout, or 0 if this layout is not installed on any widget.
QLayout (QWidget *parent)
Constructs a new top-level QLayout, with parent parent.
QLayout ()
Constructs a new child QLayout.
void removeItem (QLayoutItem *)
Removes the layout item item from the layout.
void removeWidget (QWidget *w)
Removes the widget widget from the layout.
bool setAlignment (QWidget *w, Qt::Alignment alignment)
Sets the alignment for widget w to alignment and returns true if w is found in this layout (not including child layouts); otherwise returns false.
bool setAlignment (QLayout *l, Qt::Alignment alignment)
Sets the alignment for the layout l to alignment and returns true if l is found in this layout (not including child layouts); otherwise returns false.
void setContentsMargins (int left, int top, int right, int bottom)
Sets the left, top, right, and bottom margins to use around the layout.
void setContentsMargins (const QMargins &margins)
Sets the margins to use around the layout.
void setEnabled (bool)
Enables this layout if enable is true, otherwise disables it.
void setMargin (int)
void setMenuBar (QWidget *w)
Tells the geometry manager to place the menu bar widget at the top of parentWidget(), outside QWidget::contentsMargins().
void setSizeConstraint (SizeConstraint)
void setSpacing (int)
SizeConstraint sizeConstraint () const
int spacing () const
int totalHeightForWidth (int w) const
Also takes contentsMargins and menu bar into account.
QSize totalMaximumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalMinimumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalSizeHint () const
Also takes contentsMargins and menu bar into account.
void update ()
Updates the layout for parentWidget().
~QLayout ()
Destroys the layout, deleting all child layouts.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QLayoutItem
Qt::Alignment alignment () const
Returns the alignment of this item.
QSizePolicy::ControlTypes controlTypes () const
Returns the control type(s) for the layout item.
QLayoutItem (Qt::Alignment alignment=0)
Constructs a layout item with an alignment.
void setAlignment (Qt::Alignment a)
Sets the alignment of this item to alignment.
virtual QSpacerItem * spacerItem ()
If this item is a QSpacerItem, it is returned as a QSpacerItem; otherwise 0 is returned.
virtual QWidget * widget ()
If this item is a QWidget, it is returned as a QWidget; otherwise 0 is returned.
virtual ~QLayoutItem ()
Destroys the QLayoutItem.
Protected Functions
void addItem (QLayoutItem *)
Reimplemented Function
Protected Functions inherited from QLayout
void addChildLayout (QLayout *l)
This function is called from addLayout() or insertLayout() functions in subclasses to add layout l as a sub-layout.
void addChildWidget (QWidget *w)
This function is called from addWidget() functions in subclasses to add w as a managed widget of a layout.
bool adoptLayout (QLayout *layout)
QRect alignmentRect (const QRect &) const
Returns the rectangle that should be covered when the geometry of this layout is set to r, provided that this layout supports setAlignment().
void childEvent (QChildEvent *e)
Reimplemented Function
QLayout (QLayoutPrivate &d, QLayout *, QWidget *)
void widgetEvent (QEvent *)
Performs child widget layout when the parent widget is resized.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Types inherited from QLayout
enum SizeConstraint {
SetDefaultConstraint, SetNoConstraint, SetMinimumSize, SetFixedSize,
SetMaximumSize, SetMinAndMaxSize
}
The possible values are:
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QLayout
static QSize closestAcceptableSize (const QWidget *w, const QSize &s)
Returns a size that satisfies all size constraints on widget, including heightForWidth() and that is as close as possible to size.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QLayoutItem
Qt::Alignment align
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGridLayout class lays out widgets in a grid.
QGridLayout takes the space made available to it (by its parent layout or by the parentWidget()), divides it up into rows and columns, and puts each widget it manages into the correct cell.
Columns and rows behave identically; we will discuss columns, but there are equivalent functions for rows.
Each column has a minimum width and a stretch factor. The minimum width is the greatest of that set using setColumnMinimumWidth() and the minimum width of each widget in that column. The stretch factor is set using setColumnStretch() and determines how much of the available space the column will get over and above its necessary minimum.
Normally, each managed widget or layout is put into a cell of its own using addWidget(). It is also possible for a widget to occupy multiple cells using the row and column spanning overloads of addItem() and addWidget(). If you do this, QGridLayout will guess how to distribute the size over the columns/rows (based on the stretch factors).
To remove a widget from a layout, call removeWidget(). Calling QWidget::hide() on a widget also effectively removes the widget from the layout until QWidget::show() is called.
This illustration shows a fragment of a dialog with a five-column, three-row grid (the grid is shown overlaid in magenta):
A grid layout
Columns 0, 2 and 4 in this dialog fragment are made up of a QLabel, a QLineEdit, and a QListBox. Columns 1 and 3 are placeholders made with setColumnMinimumWidth(). Row 0 consists of three QLabel objects, row 1 of three QLineEdit objects and row 2 of three QListBox objects. We used placeholder columns (1 and 3) to get the right amount of space between the columns.
Note that the columns and rows are not equally wide or tall. If you want two columns to have the same width, you must set their minimum widths and stretch factors to be the same yourself. You do this using setColumnMinimumWidth() and setColumnStretch().
If the QGridLayout is not the top-level layout (i.e. does not manage all of the widget's area and children), you must add it to its parent layout when you create it, but before you do anything with it. The normal way to add a layout is by calling addLayout() on the parent layout.
Once you have added your layout you can start putting widgets and other layouts into the cells of your grid layout using addWidget(), addItem(), and addLayout().
QGridLayout also includes two margin widths: the contents margin and the spacing(). The contents margin is the width of the reserved space along each of the QGridLayout's four sides. The spacing() is the width of the automatically allocated spacing between neighboring boxes.
The default contents margin values are provided by the style. The default value Qt styles specify is 9 for child widgets and 11 for windows. The spacing defaults to the same as the margin width for a top-level layout, or to the same as the parent layout.
See also
QBoxLayout, QStackedLayout, {Layout Management}, {Basic Layouts Example}
Definition at line 60 of file qgridlayout.h.
Constructors and Destructors
QGridLayout() [1/2]
QGridLayout::QGridLayout (QWidget * parent) explicit
Constructs a new QGridLayout with parent widget, parent.
The layout has one row and one column initially, and will expand when new items are inserted.
Definition at line 1065 of file qgridlayout.cpp.
     : QLayout(*new QGridLayoutPrivate, 0, parent)
 {
     Q_D(QGridLayout);
     d->expand(1, 1);
 }
QGridLayout() [2/2]
QGridLayout::QGridLayout ()
Constructs a new grid layout.
You must insert this grid into another layout. You can insert widgets and layouts into this layout at any time, but laying out will not be performed before this is inserted into another layout.
Definition at line 1079 of file qgridlayout.cpp.
     : QLayout(*new QGridLayoutPrivate, 0, 0)
 {
     Q_D(QGridLayout);
     d->expand(1, 1);
 }
~QGridLayout()
QGridLayout::~QGridLayout ()
Destroys the grid layout.
Geometry management is terminated if this is a top-level grid.
The layout's widgets aren't destroyed.
Definition at line 1191 of file qgridlayout.cpp.
 {
     Q_D(QGridLayout);
     d->deleteAll();
 }
Functions
addItem() [1/2]
void QGridLayout::addItem (QLayoutItem * item, int row, int column, int rowSpan = 1, int columnSpan = 1, Qt::Alignment alignment = 0)
Adds item at position row, column, spanning rowSpan rows and columnSpan columns, and aligns it according to alignment.
If rowSpan and/or columnSpan is -1, then the item will extend to the bottom and/or right edge, respectively. The layout takes ownership of the item.
Warning
Do not use this function to add child layouts or child widget items. Use addLayout() or addWidget() instead.
Definition at line 1539 of file qgridlayout.cpp.
Referenced by addItem(), addWidget(), and QMainWindowPrivate::init().
 {
     Q_D(QGridLayout);
     QGridBox *b = new QGridBox(item);
     b->setAlignment(alignment);
     d->add(b, row, (rowSpan < 0) ? -1 : row + rowSpan - 1, column, (columnSpan < 0) ? -1 : column + columnSpan - 1);
     invalidate();
 }
addItem() [2/2]
void QGridLayout::addItem (QLayoutItem * item) protected virtual
Reimplemented Function
Implements QLayout.
Definition at line 1521 of file qgridlayout.cpp.
 {
     Q_D(QGridLayout);
     int r, c;
     d->getNextPos(r, c);
     addItem(item, r, c);
 }
addLayout() [1/2]
void QGridLayout::addLayout (QLayout * layout, int row, int column, Qt::Alignment alignment = 0)
Places the layout at position (row, column) in the grid.
The top-left position is (0, 0).
The alignment is specified by alignment. The default alignment is 0, which means that the widget fills the entire cell.
A non-zero alignment indicates that the layout should not grow to fill the available space but should be sized according to sizeHint().
layout becomes a child of the grid layout.
Definition at line 1636 of file qgridlayout.cpp.
 {
     Q_D(QGridLayout);
     if (!adoptLayout(layout))
         return;
     QGridBox *b = new QGridBox(layout);
     b->setAlignment(alignment);
     d->add(b, row, column);
 }
addLayout() [2/2]
void QGridLayout::addLayout (QLayout * layout, int row, int column, int rowSpan, int columnSpan, Qt::Alignment alignment = 0)
This version adds the layout layout to the cell grid, spanning multiple rows/columns.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. The cell will start at row, column spanning rowSpan rows and columnSpan columns.
If rowSpan and/or columnSpan is -1, then the layout will extend to the bottom and/or right edge, respectively.
Definition at line 1658 of file qgridlayout.cpp.
 {
     Q_D(QGridLayout);
     if (!adoptLayout(layout))
         return;
     QGridBox *b = new QGridBox(layout);
     b->setAlignment(alignment);
     d->add(b, row, (rowSpan < 0) ? -1 : row + rowSpan - 1, column, (columnSpan < 0) ? -1 : column + columnSpan - 1);
 }
addWidget() [1/3]
void QGridLayout::addWidget (QWidget * widget) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Warning
This function is not part of the public interface.
Definition at line 116 of file qgridlayout.h.
Referenced by QFontDialogPrivate::init(), QMessageBoxPrivate::init(), QBalloonTip::QBalloonTip(), QColorShower::QColorShower(), QErrorMessage::QErrorMessage(), qt_mainwindow_layout(), QMessageBox::setDetailedText(), and QMessageBox::setInformativeText().
 { QLayout::addWidget(w); }
addWidget() [2/3]
void QGridLayout::addWidget (QWidget * widget, int row, int column, Qt::Alignment alignment = 0)
Adds the given widget to the cell grid at row, column.
The top-left position is (0, 0) by default.
The alignment is specified by alignment. The default alignment is 0, which means that the widget fills the entire cell.
Definition at line 1570 of file qgridlayout.cpp.
 {
     if (!checkWidget(this, widget))
         return;
     if (row < 0 || column < 0) {
         qWarning("QGridLayout: Cannot add %s/%s to %s/%s at row %d column %d",
                  widget->metaObject()->className(), widget->objectName().toLocal8Bit().data(),
                  metaObject()->className(), objectName().toLocal8Bit().data(), row, column);
         return;
     }
     addChildWidget(widget);
     QWidgetItem *b = QLayoutPrivate::createWidgetItem(this, widget);
     addItem(b, row, column, 1, 1, alignment);
 }
addWidget() [3/3]
void QGridLayout::addWidget (QWidget * widget, int fromRow, int fromColumn, int rowSpan, int columnSpan, Qt::Alignment alignment = 0)
This version adds the given widget to the cell grid, spanning multiple rows/columns.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The cell will start at fromRow, fromColumn spanning rowSpan rows and columnSpan columns. The widget will have the given alignment.
If rowSpan and/or columnSpan is -1, then the widget will extend to the bottom and/or right edge, respectively.
Definition at line 1600 of file qgridlayout.cpp.
 {
     Q_D(QGridLayout);
     if (!checkWidget(this, widget))
         return;
     int toRow = (rowSpan < 0) ? -1 : fromRow + rowSpan - 1;
     int toColumn = (columnSpan < 0) ? -1 : fromColumn + columnSpan - 1;
     addChildWidget(widget);
     QGridBox *b = new QGridBox(this, widget);
     b->setAlignment(alignment);
     d->add(b, fromRow, toRow, fromColumn, toColumn);
     invalidate();
 }
cellRect()
QRect QGridLayout::cellRect (int row, int column) const
Returns the geometry of the cell with row row and column column in the grid.
Returns an invalid rectangle if row or column is outside the grid.
Warning
in the current version of Qt this function does not return valid results until setGeometry() has been called, i.e. after the parentWidget() is visible.
Definition at line 1495 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     return d->cellRect(row, column);
 }
columnCount()
int QGridLayout::columnCount () const
Returns the number of columns in this grid.
Definition at line 1300 of file qgridlayout.cpp.
Referenced by QMessageBox::setDetailedText().
 {
     Q_D(const QGridLayout);
     return d->numCols();
 }
columnMinimumWidth()
int QGridLayout::columnMinimumWidth (int column) const
Returns the column spacing for column column.
See also
setColumnMinimumWidth()
Definition at line 1777 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     return d->colSpacing(column);
 }
columnStretch()
int QGridLayout::columnStretch (int column) const
Returns the stretch factor for column column.
See also
setColumnStretch()
Definition at line 1705 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     return d->colStretch(column);
 }
count()
int QGridLayout::count () const virtual
Reimplemented Function
Implements QLayout.
Definition at line 1407 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     return d->count();
 }
expandingDirections()
Qt::Orientations QGridLayout::expandingDirections () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 1786 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     return d->expandingDirections(horizontalSpacing(), verticalSpacing());
 }
getItemPosition()
void QGridLayout::getItemPosition (int index, int * row, int * column, int * rowSpan, int * columnSpan)
Returns the position information of the item with the given index.
The variables passed as row and column are updated with the position of the item in the layout, and the rowSpan and columnSpan variables are updated with the vertical and horizontal spans of the item.
See also
itemAtPosition(), itemAt()
Definition at line 1466 of file qgridlayout.cpp.
 {
     Q_D(QGridLayout);
     d->getItemPosition(index, row, column, rowSpan, columnSpan);
 }
hasHeightForWidth()
bool QGridLayout::hasHeightForWidth () const virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 1354 of file qgridlayout.cpp.
 {
     return ((QGridLayout*)this)->d_func()->hasHeightForWidth(horizontalSpacing(), verticalSpacing());
 }
heightForWidth()
int QGridLayout::heightForWidth (int w) const virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 1362 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     QGridLayoutPrivate *dat = const_cast<QGridLayoutPrivate *>(d);
     return dat->heightForWidth(w, horizontalSpacing(), verticalSpacing());
 }
horizontalSpacing()
int QGridLayout::horizontalSpacing () const
the spacing between widgets that are laid out side by side
Since
4.3
If no value is explicitly set, the layout's horizontal spacing is inherited from the parent layout, or from the style settings for the parent widget.
See also
verticalSpacing, QStyle::pixelMetric(), {QStyle::}{PM_LayoutHorizontalSpacing}
Definition at line 1218 of file qgridlayout.cpp.
Referenced by expandingDirections(), hasHeightForWidth(), heightForWidth(), maximumSize(), minimumHeightForWidth(), minimumSize(), setGeometry(), sizeHint(), and spacing().
 {
     Q_D(const QGridLayout);
     if (d->horizontalSpacing >= 0) {
         return d->horizontalSpacing;
     } else {
         return qSmartSpacing(this, QStyle::PM_LayoutHorizontalSpacing);
     }
 }
invalidate()
void QGridLayout::invalidate () virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 1819 of file qgridlayout.cpp.
Referenced by addItem(), addWidget(), setColumnMinimumWidth(), setColumnStretch(), setHorizontalSpacing(), setRowMinimumHeight(), setRowStretch(), setSpacing(), and setVerticalSpacing().
 {
     Q_D(QGridLayout);
     d->setDirty();
     QLayout::invalidate();
 }
itemAt()
QLayoutItem * QGridLayout::itemAt (int index) const virtual
Reimplemented Function
Implements QLayout.
Definition at line 1417 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     return d->itemAt(index);
 }
itemAtPosition()
QLayoutItem * QGridLayout::itemAtPosition (int row, int column) const
Returns the layout item that occupies cell (row, column), or 0 if the cell is empty.
Since
4.4
See also
getItemPosition(), indexOf()
Definition at line 1434 of file qgridlayout.cpp.
Referenced by qt_mainwindow_layout().
 {
     Q_D(const QGridLayout);
     int n = d->things.count();
     for (int i = 0; i < n; ++i) {
         QGridBox *box = d->things.at(i);
         if (row >= box->row && row <= box->toRow(d->rr)
                 && column >= box->col && column <= box->toCol(d->cc)) {
             return box->item();
         }
     }
     return 0;
 }
maximumSize()
QSize QGridLayout::maximumSize () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 1335 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     QSize s = d->maximumSize(horizontalSpacing(), verticalSpacing());
     int left, top, right, bottom;
     d->effectiveMargins(&left, &top, &right, &bottom);
     s += QSize(left + right, top + bottom);
     s = s.boundedTo(QSize(QLAYOUTSIZE_MAX, QLAYOUTSIZE_MAX));
     if (alignment() & Qt::AlignHorizontal_Mask)
         s.setWidth(QLAYOUTSIZE_MAX);
     if (alignment() & Qt::AlignVertical_Mask)
         s.setHeight(QLAYOUTSIZE_MAX);
     return s;
 }
minimumHeightForWidth()
int QGridLayout::minimumHeightForWidth (int w) const virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 1372 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     QGridLayoutPrivate *dat = const_cast<QGridLayoutPrivate *>(d);
     return dat->minimumHeightForWidth(w, horizontalSpacing(), verticalSpacing());
 }
minimumSize()
QSize QGridLayout::minimumSize () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 1322 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     QSize result(d->minimumSize(horizontalSpacing(), verticalSpacing()));
     int left, top, right, bottom;
     d->effectiveMargins(&left, &top, &right, &bottom);
     result += QSize(left + right, top + bottom);
     return result;
 }
originCorner()
Qt::Corner QGridLayout::originCorner () const
Returns the corner that's used for the grid's origin, i.e.
for position (0, 0).
Definition at line 1806 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     if (d->horReversed()) {
         return d->verReversed() ? Qt::BottomRightCorner : Qt::TopRightCorner;
     } else {
         return d->verReversed() ? Qt::BottomLeftCorner : Qt::TopLeftCorner;
     }
 }
rowCount()
int QGridLayout::rowCount () const
Returns the number of rows in this grid.
Definition at line 1291 of file qgridlayout.cpp.
Referenced by QMessageBox::setDetailedText().
 {
     Q_D(const QGridLayout);
     return d->numRows();
 }
rowMinimumHeight()
int QGridLayout::rowMinimumHeight (int row) const
Returns the minimum width set for row row.
See also
setRowMinimumHeight()
Definition at line 1754 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     return d->rowSpacing(row);
 }
rowStretch()
int QGridLayout::rowStretch (int row) const
Returns the stretch factor for row row.
See also
setRowStretch()
Definition at line 1694 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     return d->rowStretch(row);
 }
setColumnMinimumWidth()
void QGridLayout::setColumnMinimumWidth (int column, int minSize)
Sets the minimum width of column column to minSize pixels.
See also
columnMinimumWidth(), setRowMinimumHeight()
Definition at line 1765 of file qgridlayout.cpp.
Referenced by QFontDialogPrivate::init().
 {
     Q_D(QGridLayout);
     d->setColumnMinimumWidth(column, minSize);
     invalidate();
 }
setColumnStretch()
void QGridLayout::setColumnStretch (int column, int stretch)
Sets the stretch factor of column column to stretch.
The first column is number 0.
The stretch factor is relative to the other columns in this grid. Columns with a higher stretch factor take more of the available space.
The default stretch factor is 0. If the stretch factor is 0 and no other column in this table can grow at all, the column may still grow.
An alternative approach is to add spacing using addItem() with a QSpacerItem.
See also
columnStretch(), setRowStretch()
Definition at line 1728 of file qgridlayout.cpp.
Referenced by QFontDialogPrivate::init(), and QErrorMessage::QErrorMessage().
 {
     Q_D(QGridLayout);
     d->setColStretch(column, stretch);
     invalidate();
 }
setDefaultPositioning()
void QGridLayout::setDefaultPositioning (int n, Qt::Orientation orient)
Warning
This function is not part of the public interface. (mostly)
Sets the positioning mode used by addItem(). If orient is Qt::Horizontal, this layout is expanded to n columns, and items will be added columns-first. Otherwise it is expanded to n rows and items will be added rows-first.
Definition at line 1172 of file qgridlayout.cpp.
 {
     Q_D(QGridLayout);
     if (orient == Qt::Horizontal) {
         d->expand(1, n);
         d->addVertical = false;
     } else {
         d->expand(n,1);
         d->addVertical = true;
     }
 }
setGeometry()
void QGridLayout::setGeometry (const QRect & rect) virtual
Reimplemented Function
Reimplemented from QLayout.
Definition at line 1476 of file qgridlayout.cpp.
 {
     Q_D(QGridLayout);
     if (d->isDirty() || rect != geometry()) {
         QRect cr = alignment() ? alignmentRect(rect) : rect;
         d->distribute(cr, horizontalSpacing(), verticalSpacing());
         QLayout::setGeometry(rect);
     }
 }
setHorizontalSpacing()
void QGridLayout::setHorizontalSpacing (int spacing)
Definition at line 1211 of file qgridlayout.cpp.
Referenced by QMessageBoxPrivate::init().
 {
     Q_D(QGridLayout);
     d->horizontalSpacing = spacing;
     invalidate();
 }
setOriginCorner()
void QGridLayout::setOriginCorner (Qt::Corner corner)
Sets the grid's origin corner, i.e.
position (0, 0), to corner.
Definition at line 1795 of file qgridlayout.cpp.
 {
     Q_D(QGridLayout);
     d->setReversed(corner == Qt::BottomLeftCorner || corner == Qt::BottomRightCorner,
                    corner == Qt::TopRightCorner || corner == Qt::BottomRightCorner);
 }
setRowMinimumHeight()
void QGridLayout::setRowMinimumHeight (int row, int minSize)
Sets the minimum height of row row to minSize pixels.
See also
rowMinimumHeight(), setColumnMinimumWidth()
Definition at line 1742 of file qgridlayout.cpp.
Referenced by QFontDialogPrivate::init(), and QMessageBoxPrivate::init().
 {
     Q_D(QGridLayout);
     d->setRowMinimumHeight(row, minSize);
     invalidate();
 }
setRowStretch()
void QGridLayout::setRowStretch (int row, int stretch)
Sets the stretch factor of row row to stretch.
The first row is number 0.
The stretch factor is relative to the other rows in this grid. Rows with a higher stretch factor take more of the available space.
The default stretch factor is 0. If the stretch factor is 0 and no other row in this table can grow at all, the row may still grow.
See also
rowStretch(), setRowMinimumHeight(), setColumnStretch()
Definition at line 1682 of file qgridlayout.cpp.
Referenced by QMessageBoxPrivate::init(), and QErrorMessage::QErrorMessage().
 {
     Q_D(QGridLayout);
     d->setRowStretch(row, stretch);
     invalidate();
 }
setSpacing()
void QGridLayout::setSpacing (int spacing)
This function sets both the vertical and horizontal spacing to spacing.
See also
setVerticalSpacing(), setHorizontalSpacing()
Definition at line 1265 of file qgridlayout.cpp.
Referenced by QFontDialogPrivate::init(), and QGridLayout().
 {
     Q_D(QGridLayout);
     d->horizontalSpacing = d->verticalSpacing = spacing;
     invalidate();
 }
setVerticalSpacing()
void QGridLayout::setVerticalSpacing (int spacing)
Definition at line 1242 of file qgridlayout.cpp.
Referenced by QMessageBoxPrivate::init().
 {
     Q_D(QGridLayout);
     d->verticalSpacing = spacing;
     invalidate();
 }
sizeHint()
QSize QGridLayout::sizeHint () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 1309 of file qgridlayout.cpp.
 {
     Q_D(const QGridLayout);
     QSize result(d->sizeHint(horizontalSpacing(), verticalSpacing()));
     int left, top, right, bottom;
     d->effectiveMargins(&left, &top, &right, &bottom);
     result += QSize(left + right, top + bottom);
     return result;
 }
spacing()
int QGridLayout::spacing () const
If the vertical spacing is equal to the horizontal spacing, this function returns that value; otherwise it return -1.
See also
setSpacing(), verticalSpacing(), horizontalSpacing()
Definition at line 1278 of file qgridlayout.cpp.
Referenced by QFontDialogPrivate::init(), QColorShower::QColorShower(), QGridLayout(), setHorizontalSpacing(), setSpacing(), and setVerticalSpacing().
 {
     int hSpacing = horizontalSpacing();
     if (hSpacing == verticalSpacing()) {
         return hSpacing;
     } else {
         return -1;
     }
 }
takeAt()
QLayoutItem * QGridLayout::takeAt (int index) virtual
Reimplemented Function
Implements QLayout.
Definition at line 1451 of file qgridlayout.cpp.
 {
     Q_D(QGridLayout);
     return d->takeAt(index);
 }
verticalSpacing()
int QGridLayout::verticalSpacing () const
the spacing between widgets that are laid out on top of each other
Since
4.3
If no value is explicitly set, the layout's vertical spacing is inherited from the parent layout, or from the style settings for the parent widget.
See also
horizontalSpacing, QStyle::pixelMetric(), {QStyle::}{PM_LayoutHorizontalSpacing}
Definition at line 1249 of file qgridlayout.cpp.
Referenced by expandingDirections(), hasHeightForWidth(), heightForWidth(), maximumSize(), minimumHeightForWidth(), minimumSize(), setGeometry(), sizeHint(), and spacing().
 {
     Q_D(const QGridLayout);
     if (d->verticalSpacing >= 0) {
         return d->verticalSpacing;
     } else {
         return qSmartSpacing(this, QStyle::PM_LayoutVerticalSpacing);
     }
 }
The documentation for this class was generated from the following files:
/src/gui/kernel/qgridlayout.h
/src/gui/kernel/qgridlayout.cpp