Qt 4.8: QSortFilterProxyModel Class Reference
QSortFilterProxyModel Class Reference
The QSortFilterProxyModel class provides support for sorting and filtering data passed between another model and a view.
#include <qsortfilterproxymodel.h>
Public Slots
void clear ()
This function is obsolete.
void invalidate ()
Invalidates the current sorting and filtering.
void setFilterFixedString (const QString &pattern)
Sets the fixed string used to filter the contents of the source model to the given pattern.
void setFilterRegExp (const QString &pattern)
Sets the regular expression used to filter the contents of the source model to pattern.
void setFilterWildcard (const QString &pattern)
Sets the wildcard expression used to filter the contents of the source model to the given pattern.
Public Slots inherited from QAbstractItemModel
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
QModelIndex buddy (const QModelIndex &index) const
Reimplemented Function
bool canFetchMore (const QModelIndex &parent) const
Reimplemented Function
int columnCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Reimplemented Function
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
bool dynamicSortFilter () const
void fetchMore (const QModelIndex &parent)
Reimplemented Function
Qt::CaseSensitivity filterCaseSensitivity () const
int filterKeyColumn () const
QRegExp filterRegExp () const
int filterRole () const
Qt::ItemFlags flags (const QModelIndex &index) const
Reimplemented Function
bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Reimplemented Function
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
bool isSortLocaleAware () const
QModelIndex mapFromSource (const QModelIndex &sourceIndex) const
Returns the model index in the QSortFilterProxyModel given the sourceIndex from the source model.
QItemSelection mapSelectionFromSource (const QItemSelection &sourceSelection) const
Reimplemented Function
QItemSelection mapSelectionToSource (const QItemSelection &proxySelection) const
Reimplemented Function
QModelIndex mapToSource (const QModelIndex &proxyIndex) const
Returns the source model index corresponding to the given proxyIndex from the sorting filter model.
QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Reimplemented Function
QMimeData * mimeData (const QModelIndexList &indexes) const
Reimplemented Function
QStringList mimeTypes () const
Reimplemented Function
QModelIndex parent (const QModelIndex &child) const
Reimplemented Function
QSortFilterProxyModel (QObject *parent=0)
Constructs a sorting filter model with the given parent.
bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
int rowCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
void setDynamicSortFilter (bool enable)
void setFilterCaseSensitivity (Qt::CaseSensitivity cs)
void setFilterKeyColumn (int column)
void setFilterRegExp (const QRegExp &regExp)
void setFilterRole (int role)
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
void setSortCaseSensitivity (Qt::CaseSensitivity cs)
void setSortLocaleAware (bool on)
void setSortRole (int role)
void setSourceModel (QAbstractItemModel *sourceModel)
Reimplemented Function
void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Reimplemented Function
Qt::CaseSensitivity sortCaseSensitivity () const
int sortColumn () const
the column currently used for sorting
Qt::SortOrder sortOrder () const
the order currently used for sorting
int sortRole () const
QSize span (const QModelIndex &index) const
Reimplemented Function
Qt::DropActions supportedDropActions () const
Reimplemented Function
~QSortFilterProxyModel ()
Destroys this sorting filter model.
Public Functions inherited from QAbstractProxyModel
QMap< int, QVariant > itemData (const QModelIndex &index) const
Reimplemented Function
QAbstractProxyModel (QObject *parent=0)
Constructs a proxy model with the given parent.
void revert ()
Reimplemented Function
bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Reimplemented Function
QAbstractItemModel * sourceModel () const
Returns the model that contains the data that is available through the proxy model.
bool submit ()
Reimplemented Function
~QAbstractProxyModel ()
Destroys the proxy model.
Public Functions inherited from QAbstractItemModel
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual bool filterAcceptsColumn (int source_column, const QModelIndex &source_parent) const
Returns true if the item in the column indicated by the given source_column and source_parent should be included in the model; otherwise returns false.
virtual bool filterAcceptsRow (int source_row, const QModelIndex &source_parent) const
Returns true if the item in the row indicated by the given source_row and source_parent should be included in the model; otherwise returns false.
void filterChanged ()
This function is obsolete.
void invalidateFilter ()
Invalidates the current filtering.
virtual bool lessThan (const QModelIndex &left, const QModelIndex &right) const
Returns true if the value of the item referred to by the given index left is less than the value of the item referred to by the given index right, otherwise returns false.
Protected Functions inherited from QAbstractProxyModel
QAbstractProxyModel (QAbstractProxyModelPrivate &, QObject *parent)
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
bool dynamicSortFilter
whether the proxy model is dynamically sorted and filtered whenever the contents of the source model change
Qt::CaseSensitivity filterCaseSensitivity
the case sensitivity of the QRegExp pattern used to filter the contents of the source model
int filterKeyColumn
the column where the key used to filter the contents of the source model is read from.
QRegExp filterRegExp
the QRegExp used to filter the contents of the source model
int filterRole
the item role that is used to query the source model's data when filtering items
bool isSortLocaleAware
the local aware setting used for comparing strings when sorting
Qt::CaseSensitivity sortCaseSensitivity
the case sensitivity setting used for comparing strings when sorting
int sortRole
the item role that is used to query the source model's data when sorting items
Friends
class QSortFilterProxyModelGreaterThan
class QSortFilterProxyModelLessThan
Additional Inherited Members
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSortFilterProxyModel class provides support for sorting and filtering data passed between another model and a view.
Since
4.1
QSortFilterProxyModel can be used for sorting items, filtering out items, or both. The model transforms the structure of a source model by mapping the model indexes it supplies to new indexes, corresponding to different locations, for views to use. This approach allows a given source model to be restructured as far as views are concerned without requiring any transformations on the underlying data, and without duplicating the data in memory.
Let's assume that we want to sort and filter the items provided by a custom model. The code to set up the model and the view, without sorting and filtering, would look like this:
        QTreeView *treeView = new QTreeView;
        MyItemModel *model = new MyItemModel(this);
        treeView->setModel(model);
To add sorting and filtering support to MyItemModel, we need to create a QSortFilterProxyModel, call setSourceModel() with the MyItemModel as argument, and install the QSortFilterProxyModel on the view:
        QTreeView *treeView = new QTreeView;
        MyItemModel *sourceModel = new MyItemModel(this);
        QSortFilterProxyModel *proxyModel = new QSortFilterProxyModel(this);
        proxyModel->setSourceModel(sourceModel);
        treeView->setModel(proxyModel);
At this point, neither sorting nor filtering is enabled; the original data is displayed in the view. Any changes made through the QSortFilterProxyModel are applied to the original model.
The QSortFilterProxyModel acts as a wrapper for the original model. If you need to convert source to sorted/filtered model indexes or vice versa, use mapToSource(), mapFromSource(), mapSelectionToSource(), and mapSelectionFromSource(). By default, the model does not dynamically re-sort and re-filter data whenever the original model changes. This behavior can be changed by setting the QSortFilterProxyModel::dynamicSortFilter "dynamicSortFilter" property. The itemviews/basicsortfiltermodel "Basic Sort/Filter Model" and itemviews/customsortfiltermodel "Custom Sort/Filter Model" examples illustrate how to use QSortFilterProxyModel to perform basic sorting and filtering and how to subclass it to implement custom behavior. Sorting QTableView and QTreeView have a sortingEnabled property that controls whether the user can sort the view by clicking the view's horizontal header. For example:
        treeView->setSortingEnabled(true);
When this feature is on (the default is off), clicking on a header section sorts the items according to that column. By clicking repeatedly, the user can alternate between ascending and descending order.
A sorted QTreeView
Behind the scene, the view calls the sort() virtual function on the model to reorder the data in the model. To make your data sortable, you can either implement sort() in your model, or use a QSortFilterProxyModel to wrap your model – QSortFilterProxyModel provides a generic sort() reimplementation that operates on the sortRole() (Qt::DisplayRole by default) of the items and that understands several data types, including int, QString, and QDateTime. For hierarchical models, sorting is applied recursively to all child items. String comparisons are case sensitive by default; this can be changed by setting the QSortFilterProxyModel::sortCaseSensitivity property.
Custom sorting behavior is achieved by subclassing QSortFilterProxyModel and reimplementing lessThan(), which is used to compare items. For example:
bool MySortFilterProxyModel::lessThan(const QModelIndex &left,
                                      const QModelIndex &right) const
{
    QVariant leftData = sourceModel()->data(left);
    QVariant rightData = sourceModel()->data(right);
    if (leftData.type() == QVariant::DateTime) {
        return leftData.toDateTime() < rightData.toDateTime();
    } else {
        QRegExp *emailPattern = new QRegExp("([\\w\\.]*@[\\w\\.]*)");
        QString leftString = leftData.toString();
        if(left.column() == 1 && emailPattern->indexIn(leftString) != -1)
            leftString = emailPattern->cap(1);
        QString rightString = rightData.toString();
        if(right.column() == 1 && emailPattern->indexIn(rightString) != -1)
            rightString = emailPattern->cap(1);
        return QString::localeAwareCompare(leftString, rightString) < 0;
    }
}
(This code snippet comes from the Custom Sort/Filter Model example.)
An alternative approach to sorting is to disable sorting on the view and to impose a certain order to the user. This is done by explicitly calling sort() with the desired column and order as arguments on the QSortFilterProxyModel (or on the original model if it implements sort()). For example:
        proxyModel->sort(2, Qt::AscendingOrder);
QSortFilterProxyModel can be sorted by column -1, in which case it returns to the sort order of the underlying source model.
Filtering
In addition to sorting, QSortFilterProxyModel can be used to hide items that do not match a certain filter. The filter is specified using a QRegExp object and is applied to the filterRole() (Qt::DisplayRole by default) of each item, for a given column. The QRegExp object can be used to match a regular expression, a wildcard pattern, or a fixed string. For example:
        proxyModel->setFilterRegExp(QRegExp(".png", Qt::CaseInsensitive,
                                            QRegExp::FixedString));
        proxyModel->setFilterKeyColumn(1);
For hierarchical models, the filter is applied recursively to all children. If a parent item doesn't match the filter, none of its children will be shown.
A common use case is to let the user specify the filter regexp, wildcard pattern, or fixed string in a QLineEdit and to connect the textChanged() signal to setFilterRegExp(), setFilterWildcard(), or setFilterFixedString() to reapply the filter.
Custom filtering behavior can be achieved by reimplementing the filterAcceptsRow() and filterAcceptsColumn() functions. For example (from the Custom Sort/Filter Model example), the following implementation ignores the filterKeyColumn property and performs filtering on columns 0, 1, and 2:
bool MySortFilterProxyModel::filterAcceptsRow(int sourceRow,
        const QModelIndex &sourceParent) const
{
    QModelIndex index0 = sourceModel()->index(sourceRow, 0, sourceParent);
    QModelIndex index1 = sourceModel()->index(sourceRow, 1, sourceParent);
    QModelIndex index2 = sourceModel()->index(sourceRow, 2, sourceParent);
    return (sourceModel()->data(index0).toString().contains(filterRegExp())
            || sourceModel()->data(index1).toString().contains(filterRegExp()))
           && dateInRange(sourceModel()->data(index2).toDate());
}
(This code snippet comes from the Custom Sort/Filter Model example.)
If you are working with large amounts of filtering and have to invoke invalidateFilter() repeatedly, using reset() may be more efficient, depending on the implementation of your model. However, reset() returns the proxy model to its original state, losing selection information, and will cause the proxy model to be repopulated.
Subclassing
Since QAbstractProxyModel and its subclasses are derived from QAbstractItemModel, much of the same advice about subclassing normal models also applies to proxy models. In addition, it is worth noting that many of the default implementations of functions in this class are written so that they call the equivalent functions in the relevant source model. This simple proxying mechanism may need to be overridden for source models with more complex behavior; for example, if the source model provides a custom hasChildren() implementation, you should also provide one in the proxy model.
Note
Some general guidelines for subclassing models are available in the Model Subclassing Reference.
See also
QAbstractProxyModel, QAbstractItemModel, {Model/View Programming}, {Basic Sort/Filter Model Example}, {Custom Sort/Filter Model Example}, QIdentityProxyModel
Definition at line 61 of file qsortfilterproxymodel.h.
Constructors and Destructors
QSortFilterProxyModel()
QSortFilterProxyModel::QSortFilterProxyModel (QObject * parent = 0)
Constructs a sorting filter model with the given parent.
Definition at line 1569 of file qsortfilterproxymodel.cpp.
     : QAbstractProxyModel(*new QSortFilterProxyModelPrivate, parent)
 {
     Q_D(QSortFilterProxyModel);
     d->proxy_sort_column = d->source_sort_column = -1;
     d->sort_order = Qt::AscendingOrder;
     d->sort_casesensitivity = Qt::CaseSensitive;
     d->sort_role = Qt::DisplayRole;
     d->sort_localeaware = false;
     d->filter_column = 0;
     d->filter_role = Qt::DisplayRole;
     d->dynamic_sortfilter = false;
     connect(this, SIGNAL(modelReset()), this, SLOT(_q_clearMapping()));
 }
~QSortFilterProxyModel()
QSortFilterProxyModel::~QSortFilterProxyModel ()
Destroys this sorting filter model.
Definition at line 1587 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     qDeleteAll(d->source_index_mapping);
     d->source_index_mapping.clear();
 }
Functions
buddy()
QModelIndex QSortFilterProxyModel::buddy (const QModelIndex & index) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 2049 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     if (!d->indexValid(index))
         return QModelIndex();
     QModelIndex source_index = mapToSource(index);
     QModelIndex source_buddy = d->model->buddy(source_index);
     if (source_index == source_buddy)
         return index;
     return mapFromSource(source_buddy);
 }
canFetchMore()
bool QSortFilterProxyModel::canFetchMore (const QModelIndex & parent) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 2025 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     QModelIndex source_parent;
     if (d->indexValid(parent))
         source_parent = mapToSource(parent);
     return d->model->canFetchMore(source_parent);
 }
clear
void QSortFilterProxyModel::clear () slot
This function is obsolete.
Use invalidate() instead.
Definition at line 2406 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     emit layoutAboutToBeChanged();
     d->_q_clearMapping();
     emit layoutChanged();
 }
columnCount()
int QSortFilterProxyModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 1737 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     QModelIndex source_parent = mapToSource(parent);
     if (parent.isValid() && !source_parent.isValid())
         return 0;
     IndexMap::const_iterator it = d->create_mapping(source_parent);
     return it.value()->source_columns.count();
 }
data()
QVariant QSortFilterProxyModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 1769 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     QModelIndex source_index = mapToSource(index);
     if (index.isValid() && !source_index.isValid())
         return QVariant();
     return d->model->data(source_index, role);
 }
dropMimeData()
bool QSortFilterProxyModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 1868 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     if ((row == -1) && (column == -1))
         return d->model->dropMimeData(data, action, -1, -1, mapToSource(parent));
     int source_destination_row = -1;
     int source_destination_column = -1;
     QModelIndex source_parent;
     if (row == rowCount(parent)) {
         source_parent = mapToSource(parent);
         source_destination_row = d->model->rowCount(source_parent);
     } else {
         QModelIndex proxy_index = index(row, column, parent);
         QModelIndex source_index = mapToSource(proxy_index);
         source_destination_row = source_index.row();
         source_destination_column = source_index.column();
         source_parent = source_index.parent();
     }
     return d->model->dropMimeData(data, action, source_destination_row,
                                   source_destination_column, source_parent);
 }
dynamicSortFilter()
bool QSortFilterProxyModel::dynamicSortFilter () const
Referenced by setFilterFixedString().
fetchMore()
void QSortFilterProxyModel::fetchMore (const QModelIndex & parent) virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 2013 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     QModelIndex source_parent;
     if (d->indexValid(parent))
         source_parent = mapToSource(parent);
     d->model->fetchMore(source_parent);
 }
filterAcceptsColumn()
bool QSortFilterProxyModel::filterAcceptsColumn (int source_column, const QModelIndex & source_parent) const protected virtual
Returns true if the item in the column indicated by the given source_column and source_parent should be included in the model; otherwise returns false.
The default implementation returns true if the value held by the relevant item matches the filter string, wildcard string or regular expression.
Note
By default, the Qt::DisplayRole is used to determine if the row should be accepted or not. This can be changed by setting the filterRole property.
See also
filterAcceptsRow(), setFilterFixedString(), setFilterRegExp(), setFilterWildcard()
Definition at line 2587 of file qsortfilterproxymodel.cpp.
 {
     Q_UNUSED(source_column);
     Q_UNUSED(source_parent);
     return true;
 }
filterAcceptsRow()
bool QSortFilterProxyModel::filterAcceptsRow (int source_row, const QModelIndex & source_parent) const protected virtual
Returns true if the item in the row indicated by the given source_row and source_parent should be included in the model; otherwise returns false.
The default implementation returns true if the value held by the relevant item matches the filter string, wildcard string or regular expression.
Note
By default, the Qt::DisplayRole is used to determine if the row should be accepted or not. This can be changed by setting the filterRole property.
See also
filterAcceptsColumn(), setFilterFixedString(), setFilterRegExp(), setFilterWildcard()
Definition at line 2553 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     if (d->filter_regexp.isEmpty())
         return true;
     if (d->filter_column == -1) {
         int column_count = d->model->columnCount(source_parent);
         for (int column = 0; column < column_count; ++column) {
             QModelIndex source_index = d->model->index(source_row, column, source_parent);
             QString key = d->model->data(source_index, d->filter_role).toString();
             if (key.contains(d->filter_regexp))
                 return true;
         }
         return false;
     }
     QModelIndex source_index = d->model->index(source_row, d->filter_column, source_parent);
     if (!source_index.isValid()) // the column may not exist
         return true;
     QString key = d->model->data(source_index, d->filter_role).toString();
     return key.contains(d->filter_regexp);
 }
filterCaseSensitivity()
Qt::CaseSensitivity QSortFilterProxyModel::filterCaseSensitivity () const
Referenced by setFilterKeyColumn().
filterChanged()
void QSortFilterProxyModel::filterChanged () protected
This function is obsolete.
Use invalidateFilter() instead.
Definition at line 2440 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     d->filter_changed();
 }
filterKeyColumn()
int QSortFilterProxyModel::filterKeyColumn () const
Referenced by setFilterRegExp().
filterRegExp()
QRegExp QSortFilterProxyModel::filterRegExp () const
Referenced by sortOrder().
filterRole()
int QSortFilterProxyModel::filterRole () const
Referenced by setSortRole().
flags()
Qt::ItemFlags QSortFilterProxyModel::flags (const QModelIndex & index) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 2037 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     QModelIndex source_index;
     if (d->indexValid(index))
         source_index = mapToSource(index);
     return d->model->flags(source_index);
 }
hasChildren()
bool QSortFilterProxyModel::hasChildren (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 1750 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     QModelIndex source_parent = mapToSource(parent);
     if (parent.isValid() && !source_parent.isValid())
         return false;
     if (!d->model->hasChildren(source_parent))
         return false;
     if (d->model->canFetchMore(source_parent))
         return true; //we assume we might have children that can be fetched
     QSortFilterProxyModelPrivate::Mapping *m = d->create_mapping(source_parent).value();
     return m->source_rows.count() != 0 && m->source_columns.count() != 0;
 }
headerData()
QVariant QSortFilterProxyModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 1793 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     IndexMap::const_iterator it = d->create_mapping(QModelIndex());
     if (it.value()->source_rows.count() * it.value()->source_columns.count() > 0)
         return QAbstractProxyModel::headerData(section, orientation, role);
     int source_section;
     if (orientation == Qt::Vertical) {
         if (section < 0 || section >= it.value()->source_rows.count())
             return QVariant();
         source_section = it.value()->source_rows.at(section);
     } else {
         if (section < 0 || section >= it.value()->source_columns.count())
             return QVariant();
         source_section = it.value()->source_columns.at(section);
     }
     return d->model->headerData(source_section, orientation, role);
 }
index()
QModelIndex QSortFilterProxyModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 1692 of file qsortfilterproxymodel.cpp.
Referenced by buddy(), and dropMimeData().
 {
     Q_D(const QSortFilterProxyModel);
     if (row < 0 || column < 0)
         return QModelIndex();
     QModelIndex source_parent = mapToSource(parent); // parent is already mapped at this point
     IndexMap::const_iterator it = d->create_mapping(source_parent); // but make sure that the children are mapped
     if (it.value()->source_rows.count() <= row || it.value()->source_columns.count() <= column)
         return QModelIndex();
     return d->create_index(row, column, it);
 }
insertColumns()
bool QSortFilterProxyModel::insertColumns (int column, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 1914 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     if (column < 0|| count <= 0)
         return false;
     QModelIndex source_parent = mapToSource(parent);
     if (parent.isValid() && !source_parent.isValid())
         return false;
     QSortFilterProxyModelPrivate::Mapping *m = d->create_mapping(source_parent).value();
     if (column > m->source_columns.count())
         return false;
     int source_column = (column >= m->source_columns.count()
                          ? m->source_columns.count()
                          : m->source_columns.at(column));
     return d->model->insertColumns(source_column, count, source_parent);
 }
insertRows()
bool QSortFilterProxyModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 1894 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     if (row < 0 || count <= 0)
         return false;
     QModelIndex source_parent = mapToSource(parent);
     if (parent.isValid() && !source_parent.isValid())
         return false;
     QSortFilterProxyModelPrivate::Mapping *m = d->create_mapping(source_parent).value();
     if (row > m->source_rows.count())
         return false;
     int source_row = (row >= m->source_rows.count()
                       ? m->source_rows.count()
                       : m->source_rows.at(row));
     return d->model->insertRows(source_row, count, source_parent);
 }
invalidate
void QSortFilterProxyModel::invalidate () slot
Invalidates the current sorting and filtering.
Since
4.3
See also
invalidateFilter()
Definition at line 2424 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     emit layoutAboutToBeChanged();
     d->_q_clearMapping();
     emit layoutChanged();
 }
invalidateFilter()
void QSortFilterProxyModel::invalidateFilter () protected
Invalidates the current filtering.
Since
4.3
This function should be called if you are implementing custom filtering (e.g. filterAcceptsRow()), and your filter parameters have changed.
See also
invalidate()
Definition at line 2459 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     d->filter_changed();
 }
isSortLocaleAware()
bool QSortFilterProxyModel::isSortLocaleAware () const
Referenced by setSortCaseSensitivity().
lessThan()
bool QSortFilterProxyModel::lessThan (const QModelIndex & left, const QModelIndex & right) const protected virtual
Returns true if the value of the item referred to by the given index left is less than the value of the item referred to by the given index right, otherwise returns false.
This function is used as the < operator when sorting, and handles the following QVariant types:
QVariant::Int
QVariant::UInt
QVariant::LongLong
QVariant::ULongLong
QVariant::Double
QVariant::Char
QVariant::Date
QVariant::Time
QVariant::DateTime
QVariant::String
Any other type will be converted to a QString using QVariant::toString().
Comparison of QString is case sensitive by default; this can be changed using the QSortFilterProxyModel::sortCaseSensitivity {sortCaseSensitivity} property.
By default, the Qt::DisplayRole associated with the is used for comparisons. This can be changed by setting the QSortFilterProxyModel::sortRole {sortRole} property.
Note
The indices passed in correspond to the source model.
See also
sortRole, sortCaseSensitivity, dynamicSortFilter
Definition at line 2501 of file qsortfilterproxymodel.cpp.
Referenced by QSortFilterProxyModelLessThan::operator()(), and QSortFilterProxyModelGreaterThan::operator()().
 {
     Q_D(const QSortFilterProxyModel);
     QVariant l = (left.model() ? left.model()->data(left, d->sort_role) : QVariant());
     QVariant r = (right.model() ? right.model()->data(right, d->sort_role) : QVariant());
     switch (l.userType()) {
     case QVariant::Invalid:
         return (r.type() != QVariant::Invalid);
     case QVariant::Int:
         return l.toInt() < r.toInt();
     case QVariant::UInt:
         return l.toUInt() < r.toUInt();
     case QVariant::LongLong:
         return l.toLongLong() < r.toLongLong();
     case QVariant::ULongLong:
         return l.toULongLong() < r.toULongLong();
     case QMetaType::Float:
         return l.toFloat() < r.toFloat();
     case QVariant::Double:
         return l.toDouble() < r.toDouble();
     case QVariant::Char:
         return l.toChar() < r.toChar();
     case QVariant::Date:
         return l.toDate() < r.toDate();
     case QVariant::Time:
         return l.toTime() < r.toTime();
     case QVariant::DateTime:
         return l.toDateTime() < r.toDateTime();
     case QVariant::String:
     default:
         if (d->sort_localeaware)
             return l.toString().localeAwareCompare(r.toString()) < 0;
         else
             return l.toString().compare(r.toString(), d->sort_casesensitivity) < 0;
     }
     return false;
 }
mapFromSource()
QModelIndex QSortFilterProxyModel::mapFromSource (const QModelIndex & sourceIndex) const virtual
Returns the model index in the QSortFilterProxyModel given the sourceIndex from the source model.
See also
mapToSource()
Implements QAbstractProxyModel.
Definition at line 2612 of file qsortfilterproxymodel.cpp.
Referenced by buddy(), and parent().
 {
     Q_D(const QSortFilterProxyModel);
     return d->source_to_proxy(sourceIndex);
 }
mapSelectionFromSource()
QItemSelection QSortFilterProxyModel::mapSelectionFromSource (const QItemSelection & sourceSelection) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 2629 of file qsortfilterproxymodel.cpp.
 {
     return QAbstractProxyModel::mapSelectionFromSource(sourceSelection);
 }
mapSelectionToSource()
QItemSelection QSortFilterProxyModel::mapSelectionToSource (const QItemSelection & proxySelection) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 2621 of file qsortfilterproxymodel.cpp.
 {
     return QAbstractProxyModel::mapSelectionToSource(proxySelection);
 }
mapToSource()
QModelIndex QSortFilterProxyModel::mapToSource (const QModelIndex & proxyIndex) const virtual
Returns the source model index corresponding to the given proxyIndex from the sorting filter model.
See also
mapFromSource()
Implements QAbstractProxyModel.
Definition at line 2600 of file qsortfilterproxymodel.cpp.
Referenced by buddy(), canFetchMore(), columnCount(), data(), dropMimeData(), fetchMore(), flags(), hasChildren(), index(), insertColumns(), insertRows(), mimeData(), removeColumns(), removeRows(), rowCount(), setData(), and span().
 {
     Q_D(const QSortFilterProxyModel);
     return d->proxy_to_source(proxyIndex);
 }
match()
QModelIndexList QSortFilterProxyModel::match (const QModelIndex & start, int role, const QVariant & value, int hits = 1, Qt::MatchFlags flags = Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 2064 of file qsortfilterproxymodel.cpp.
 {
     return QAbstractProxyModel::match(start, role, value, hits, flags);
 }
mimeData()
QMimeData * QSortFilterProxyModel::mimeData (const QModelIndexList & indexes) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 1838 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     QModelIndexList source_indexes;
     for (int i = 0; i < indexes.count(); ++i)
         source_indexes << mapToSource(indexes.at(i));
     return d->model->mimeData(source_indexes);
 }
mimeTypes()
QStringList QSortFilterProxyModel::mimeTypes () const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 1850 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     return d->model->mimeTypes();
 }
parent()
QObject * QSortFilterProxyModel::parent (const QModelIndex & child) const virtual
Reimplemented Function
Warning
This function is not part of the public interface.
Implements QAbstractItemModel.
Definition at line 1709 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     if (!d->indexValid(child))
         return QModelIndex();
     IndexMap::const_iterator it = d->index_to_iterator(child);
     Q_ASSERT(it != d->source_index_mapping.constEnd());
     QModelIndex source_parent = it.key();
     QModelIndex proxy_parent = mapFromSource(source_parent);
     return proxy_parent;
 }
removeColumns()
bool QSortFilterProxyModel::removeColumns (int column, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 1975 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     if (column < 0 || count <= 0)
         return false;
     QModelIndex source_parent = mapToSource(parent);
     if (parent.isValid() && !source_parent.isValid())
         return false;
     QSortFilterProxyModelPrivate::Mapping *m = d->create_mapping(source_parent).value();
     if (column + count > m->source_columns.count())
         return false;
     if ((count == 1) || (m->proxy_columns.count() == m->source_columns.count())) {
         int source_column = m->source_columns.at(column);
         return d->model->removeColumns(source_column, count, source_parent);
     }
     // remove corresponding source intervals
     QVector<int> columns;
     for (int i = column; i < column + count; ++i)
         columns.append(m->source_columns.at(i));
     int pos = columns.count() - 1;
     bool ok = true;
     while (pos >= 0) {
         const int source_end = columns.at(pos--);
         int source_start = source_end;
         while ((pos >= 0) && (columns.at(pos) == (source_start - 1))) {
             --source_start;
             --pos;
         }
         ok = ok && d->model->removeColumns(source_start, source_end - source_start + 1,
                                            source_parent);
     }
     return ok;
 }
removeRows()
bool QSortFilterProxyModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 1934 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     if (row < 0 || count <= 0)
         return false;
     QModelIndex source_parent = mapToSource(parent);
     if (parent.isValid() && !source_parent.isValid())
         return false;
     QSortFilterProxyModelPrivate::Mapping *m = d->create_mapping(source_parent).value();
     if (row + count > m->source_rows.count())
         return false;
     if ((count == 1)
         || ((d->source_sort_column < 0) && (m->proxy_rows.count() == m->source_rows.count()))) {
         int source_row = m->source_rows.at(row);
         return d->model->removeRows(source_row, count, source_parent);
     }
     // remove corresponding source intervals
     // ### if this proves to be slow, we can switch to single-row removal
     QVector<int> rows;
     for (int i = row; i < row + count; ++i)
         rows.append(m->source_rows.at(i));
     qSort(rows.begin(), rows.end());
     int pos = rows.count() - 1;
     bool ok = true;
     while (pos >= 0) {
         const int source_end = rows.at(pos--);
         int source_start = source_end;
         while ((pos >= 0) && (rows.at(pos) == (source_start - 1))) {
             --source_start;
             --pos;
         }
         ok = ok && d->model->removeRows(source_start, source_end - source_start + 1,
                                         source_parent);
     }
     return ok;
 }
rowCount()
int QSortFilterProxyModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 1724 of file qsortfilterproxymodel.cpp.
Referenced by dropMimeData().
 {
     Q_D(const QSortFilterProxyModel);
     QModelIndex source_parent = mapToSource(parent);
     if (parent.isValid() && !source_parent.isValid())
         return 0;
     IndexMap::const_iterator it = d->create_mapping(source_parent);
     return it.value()->source_rows.count();
 }
setData()
bool QSortFilterProxyModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 1781 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     QModelIndex source_index = mapToSource(index);
     if (index.isValid() && !source_index.isValid())
         return false;
     return d->model->setData(source_index, value, role);
 }
setDynamicSortFilter()
void QSortFilterProxyModel::setDynamicSortFilter (bool enable)
Definition at line 2336 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     d->dynamic_sortfilter = enable;
     if (enable)
         d->sort();
 }
setFilterCaseSensitivity()
void QSortFilterProxyModel::setFilterCaseSensitivity (Qt::CaseSensitivity cs)
Definition at line 2199 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     if (cs == d->filter_regexp.caseSensitivity())
         return;
     d->filter_regexp.setCaseSensitivity(cs);
     d->filter_changed();
 }
setFilterFixedString
void QSortFilterProxyModel::setFilterFixedString (const QString & pattern) slot
Sets the fixed string used to filter the contents of the source model to the given pattern.
See also
setFilterCaseSensitivity(), setFilterRegExp(), setFilterWildcard(), filterRegExp()
Definition at line 2303 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     d->filter_regexp.setPatternSyntax(QRegExp::FixedString);
     d->filter_regexp.setPattern(pattern);
     d->filter_changed();
 }
setFilterKeyColumn()
void QSortFilterProxyModel::setFilterKeyColumn (int column)
Definition at line 2173 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     d->filter_column = column;
     d->filter_changed();
 }
setFilterRegExp() [1/2]
void QSortFilterProxyModel::setFilterRegExp (const QRegExp & regExp)
Definition at line 2149 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     d->filter_regexp = regExp;
     d->filter_changed();
 }
setFilterRegExp [2/2]
void QSortFilterProxyModel::setFilterRegExp (const QString & pattern) slot
Sets the regular expression used to filter the contents of the source model to pattern.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setFilterCaseSensitivity(), setFilterWildcard(), setFilterFixedString(), filterRegExp()
Definition at line 2275 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     d->filter_regexp.setPatternSyntax(QRegExp::RegExp);
     d->filter_regexp.setPattern(pattern);
     d->filter_changed();
 }
setFilterRole()
void QSortFilterProxyModel::setFilterRole (int role)
Definition at line 2389 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     if (d->filter_role == role)
         return;
     d->filter_role = role;
     d->filter_changed();
 }
setFilterWildcard
void QSortFilterProxyModel::setFilterWildcard (const QString & pattern) slot
Sets the wildcard expression used to filter the contents of the source model to the given pattern.
See also
setFilterCaseSensitivity(), setFilterRegExp(), setFilterFixedString(), filterRegExp()
Definition at line 2289 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     d->filter_regexp.setPatternSyntax(QRegExp::Wildcard);
     d->filter_regexp.setPattern(pattern);
     d->filter_changed();
 }
setHeaderData()
bool QSortFilterProxyModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole) virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 1815 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     IndexMap::const_iterator it = d->create_mapping(QModelIndex());
     if (it.value()->source_rows.count() * it.value()->source_columns.count() > 0)
         return QAbstractProxyModel::setHeaderData(section, orientation, value, role);
     int source_section;
     if (orientation == Qt::Vertical) {
         if (section < 0 || section >= it.value()->source_rows.count())
             return false;
         source_section = it.value()->source_rows.at(section);
     } else {
         if (section < 0 || section >= it.value()->source_columns.count())
             return false;
         source_section = it.value()->source_columns.at(section);
     }
     return d->model->setHeaderData(source_section, orientation, value, role);
 }
setSortCaseSensitivity()
void QSortFilterProxyModel::setSortCaseSensitivity (Qt::CaseSensitivity cs)
Definition at line 2226 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     if (d->sort_casesensitivity == cs)
         return;
     d->sort_casesensitivity = cs;
     d->sort();
 }
setSortLocaleAware()
void QSortFilterProxyModel::setSortLocaleAware (bool on)
Definition at line 2254 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     if (d->sort_localeaware == on)
         return;
     d->sort_localeaware = on;
     d->sort();
 }
setSortRole()
void QSortFilterProxyModel::setSortRole (int role)
Definition at line 2362 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     if (d->sort_role == role)
         return;
     d->sort_role = role;
     d->sort();
 }
setSourceModel()
void QSortFilterProxyModel::setSourceModel (QAbstractItemModel * sourceModel) virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 1597 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     beginResetModel();
     disconnect(d->model, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
                this, SLOT(_q_sourceDataChanged(QModelIndex,QModelIndex)));
     disconnect(d->model, SIGNAL(headerDataChanged(Qt::Orientation,int,int)),
                this, SLOT(_q_sourceHeaderDataChanged(Qt::Orientation,int,int)));
     disconnect(d->model, SIGNAL(rowsAboutToBeInserted(QModelIndex,int,int)),
                this, SLOT(_q_sourceRowsAboutToBeInserted(QModelIndex,int,int)));
     disconnect(d->model, SIGNAL(rowsInserted(QModelIndex,int,int)),
                this, SLOT(_q_sourceRowsInserted(QModelIndex,int,int)));
     disconnect(d->model, SIGNAL(columnsAboutToBeInserted(QModelIndex,int,int)),
                this, SLOT(_q_sourceColumnsAboutToBeInserted(QModelIndex,int,int)));
     disconnect(d->model, SIGNAL(columnsInserted(QModelIndex,int,int)),
                this, SLOT(_q_sourceColumnsInserted(QModelIndex,int,int)));
     disconnect(d->model, SIGNAL(rowsAboutToBeRemoved(QModelIndex,int,int)),
                this, SLOT(_q_sourceRowsAboutToBeRemoved(QModelIndex,int,int)));
     disconnect(d->model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                this, SLOT(_q_sourceRowsRemoved(QModelIndex,int,int)));
     disconnect(d->model, SIGNAL(columnsAboutToBeRemoved(QModelIndex,int,int)),
                this, SLOT(_q_sourceColumnsAboutToBeRemoved(QModelIndex,int,int)));
     disconnect(d->model, SIGNAL(columnsRemoved(QModelIndex,int,int)),
                this, SLOT(_q_sourceColumnsRemoved(QModelIndex,int,int)));
     disconnect(d->model, SIGNAL(layoutAboutToBeChanged()),
                this, SLOT(_q_sourceLayoutAboutToBeChanged()));
     disconnect(d->model, SIGNAL(layoutChanged()),
                this, SLOT(_q_sourceLayoutChanged()));
     disconnect(d->model, SIGNAL(modelAboutToBeReset()), this, SLOT(_q_sourceAboutToBeReset()));
     disconnect(d->model, SIGNAL(modelReset()), this, SLOT(_q_sourceReset()));
     QAbstractProxyModel::setSourceModel(sourceModel);
     connect(d->model, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
             this, SLOT(_q_sourceDataChanged(QModelIndex,QModelIndex)));
     connect(d->model, SIGNAL(headerDataChanged(Qt::Orientation,int,int)),
             this, SLOT(_q_sourceHeaderDataChanged(Qt::Orientation,int,int)));
     connect(d->model, SIGNAL(rowsAboutToBeInserted(QModelIndex,int,int)),
             this, SLOT(_q_sourceRowsAboutToBeInserted(QModelIndex,int,int)));
     connect(d->model, SIGNAL(rowsInserted(QModelIndex,int,int)),
             this, SLOT(_q_sourceRowsInserted(QModelIndex,int,int)));
     connect(d->model, SIGNAL(columnsAboutToBeInserted(QModelIndex,int,int)),
             this, SLOT(_q_sourceColumnsAboutToBeInserted(QModelIndex,int,int)));
     connect(d->model, SIGNAL(columnsInserted(QModelIndex,int,int)),
             this, SLOT(_q_sourceColumnsInserted(QModelIndex,int,int)));
     connect(d->model, SIGNAL(rowsAboutToBeRemoved(QModelIndex,int,int)),
             this, SLOT(_q_sourceRowsAboutToBeRemoved(QModelIndex,int,int)));
     connect(d->model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
             this, SLOT(_q_sourceRowsRemoved(QModelIndex,int,int)));
     connect(d->model, SIGNAL(columnsAboutToBeRemoved(QModelIndex,int,int)),
             this, SLOT(_q_sourceColumnsAboutToBeRemoved(QModelIndex,int,int)));
     connect(d->model, SIGNAL(columnsRemoved(QModelIndex,int,int)),
             this, SLOT(_q_sourceColumnsRemoved(QModelIndex,int,int)));
     connect(d->model, SIGNAL(layoutAboutToBeChanged()),
             this, SLOT(_q_sourceLayoutAboutToBeChanged()));
     connect(d->model, SIGNAL(layoutChanged()),
             this, SLOT(_q_sourceLayoutChanged()));
     connect(d->model, SIGNAL(modelAboutToBeReset()), this, SLOT(_q_sourceAboutToBeReset()));
     connect(d->model, SIGNAL(modelReset()), this, SLOT(_q_sourceReset()));
     d->_q_clearMapping();
     endResetModel();
     if (d->update_source_sort_column() && d->dynamic_sortfilter)
         d->sort();
 }
sort()
void QSortFilterProxyModel::sort (int column, Qt::SortOrder order = Qt::AscendingOrder) virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 2086 of file qsortfilterproxymodel.cpp.
 {
     Q_D(QSortFilterProxyModel);
     if (d->dynamic_sortfilter && d->proxy_sort_column == column && d->sort_order == order)
         return;
     d->sort_order = order;
     d->proxy_sort_column = column;
     d->update_source_sort_column();
     d->sort();
 }
sortCaseSensitivity()
Qt::CaseSensitivity QSortFilterProxyModel::sortCaseSensitivity () const
Referenced by setFilterCaseSensitivity().
sortColumn()
int QSortFilterProxyModel::sortColumn () const
the column currently used for sorting
Since
4.5
This returns the most recently used sort column.
Definition at line 2106 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     return d->proxy_sort_column;
 }
sortOrder()
Qt::SortOrder QSortFilterProxyModel::sortOrder () const
the order currently used for sorting
Since
4.5
This returns the most recently used sort order.
Definition at line 2121 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     return d->sort_order;
 }
sortRole()
int QSortFilterProxyModel::sortRole () const
Referenced by setDynamicSortFilter().
span()
QSize QSortFilterProxyModel::span (const QModelIndex & index) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 2074 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     QModelIndex source_index = mapToSource(index);
     if (index.isValid() && !source_index.isValid())
         return QSize();
     return d->model->span(source_index);
 }
supportedDropActions()
Qt::DropActions QSortFilterProxyModel::supportedDropActions () const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 1859 of file qsortfilterproxymodel.cpp.
 {
     Q_D(const QSortFilterProxyModel);
     return d->model->supportedDropActions();
 }
Friends and Related Functions
QSortFilterProxyModelGreaterThan
friend class QSortFilterProxyModelGreaterThan friend
Definition at line 64 of file qsortfilterproxymodel.h.
QSortFilterProxyModelLessThan
friend class QSortFilterProxyModelLessThan friend
Definition at line 63 of file qsortfilterproxymodel.h.
Properties
dynamicSortFilter
bool QSortFilterProxyModel::dynamicSortFilter private
whether the proxy model is dynamically sorted and filtered whenever the contents of the source model change
Since
4.2
Note that you should not update the source model through the proxy model when dynamicSortFilter is true. For instance, if you set the proxy model on a QComboBox, then using functions that update the model, e.g., QComboBox::addItem(), will not work as expected. An alternative is to set dynamicSortFilter to false and call QSortFilterProxyModel::sort() after adding items to the QComboBox.
The default value is false.
Definition at line 69 of file qsortfilterproxymodel.h.
filterCaseSensitivity
Qt::CaseSensitivity QSortFilterProxyModel::filterCaseSensitivity private
the case sensitivity of the QRegExp pattern used to filter the contents of the source model
By default, the filter is case sensitive.
See also
filterRegExp, sortCaseSensitivity
Definition at line 70 of file qsortfilterproxymodel.h.
filterKeyColumn
int QSortFilterProxyModel::filterKeyColumn private
the column where the key used to filter the contents of the source model is read from.
The default value is 0. If the value is -1, the keys will be read from all columns.
Definition at line 68 of file qsortfilterproxymodel.h.
filterRegExp
QRegExp QSortFilterProxyModel::filterRegExp private
the QRegExp used to filter the contents of the source model
Setting this property overwrites the current filterCaseSensitivity. By default, the QRegExp is an empty string matching all contents.
If no QRegExp or an empty string is set, everything in the source model will be accepted.
See also
filterCaseSensitivity, setFilterWildcard(), setFilterFixedString()
Definition at line 67 of file qsortfilterproxymodel.h.
filterRole
int QSortFilterProxyModel::filterRole private
the item role that is used to query the source model's data when filtering items
Since
4.2
The default value is Qt::DisplayRole.
See also
filterAcceptsRow()
Definition at line 74 of file qsortfilterproxymodel.h.
isSortLocaleAware
bool QSortFilterProxyModel::isSortLocaleAware private
the local aware setting used for comparing strings when sorting
Since
4.3
By default, sorting is not local aware.
See also
sortCaseSensitivity, lessThan()
Definition at line 72 of file qsortfilterproxymodel.h.
sortCaseSensitivity
Qt::CaseSensitivity QSortFilterProxyModel::sortCaseSensitivity private
the case sensitivity setting used for comparing strings when sorting
Since
4.2
By default, sorting is case sensitive.
See also
filterCaseSensitivity, lessThan()
Definition at line 71 of file qsortfilterproxymodel.h.
sortRole
int QSortFilterProxyModel::sortRole private
the item role that is used to query the source model's data when sorting items
Since
4.2
The default value is Qt::DisplayRole.
See also
lessThan()
Definition at line 73 of file qsortfilterproxymodel.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qsortfilterproxymodel.h
/src/gui/itemviews/qsortfilterproxymodel.cpp