Qt 4.8: QDeclarativeDebugServerConnection Class Reference
QDeclarativeDebugServerConnection Class Reference abstract
#include <qdeclarativedebugserverconnection_p.h>
Public Functions
virtual void disconnect ()=0
virtual bool isConnected () const =0
QDeclarativeDebugServerConnection ()
virtual void send (const QByteArray &message)=0
virtual void setPort (int port, bool bock)=0
virtual void setServer (QDeclarativeDebugServer *server)=0
virtual bool waitForMessage ()=0
virtual ~QDeclarativeDebugServerConnection ()
Detailed Description
Definition at line 54 of file qdeclarativedebugserverconnection_p.h.
Constructors and Destructors
QDeclarativeDebugServerConnection()
QDeclarativeDebugServerConnection::QDeclarativeDebugServerConnection () inline
Definition at line 57 of file qdeclarativedebugserverconnection_p.h.
 {}
~QDeclarativeDebugServerConnection()
virtual QDeclarativeDebugServerConnection::~QDeclarativeDebugServerConnection () inline virtual
Definition at line 58 of file qdeclarativedebugserverconnection_p.h.
 {}
Functions
disconnect()
virtual void QDeclarativeDebugServerConnection::disconnect () pure virtual
Implemented in QmlOstPlugin, and QTcpServerConnection.
isConnected()
virtual bool QDeclarativeDebugServerConnection::isConnected () const pure virtual
Implemented in QmlOstPlugin, and QTcpServerConnection.
send()
virtual void QDeclarativeDebugServerConnection::send (const QByteArray & message) pure virtual
Implemented in QmlOstPlugin, and QTcpServerConnection.
Referenced by QDeclarativeDebugServerPrivate::advertisePlugins().
setPort()
virtual void QDeclarativeDebugServerConnection::setPort (int port, bool bock) pure virtual
Implemented in QmlOstPlugin, and QTcpServerConnection.
Referenced by QDeclarativeDebugServer::instance().
setServer()
virtual void QDeclarativeDebugServerConnection::setServer (QDeclarativeDebugServer * server) pure virtual
Implemented in QmlOstPlugin, and QTcpServerConnection.
Referenced by QDeclarativeDebugServer::instance().
waitForMessage()
virtual bool QDeclarativeDebugServerConnection::waitForMessage () pure virtual
Implemented in QmlOstPlugin, and QTcpServerConnection.
The documentation for this class was generated from the following file:
/src/declarative/debugger/qdeclarativedebugserverconnection_p.h