Qt 4.8: QGLFunctions Class Reference
QGLFunctions Class Reference
The QGLFunctions class provides cross-platform access to the OpenGL/ES 2.0 API.
#include <qglfunctions.h>
Public Types
enum OpenGLFeature {
Multitexture = 0x0001, Shaders = 0x0002, Buffers = 0x0004, Framebuffers = 0x0008,
BlendColor = 0x0010, BlendEquation = 0x0020, BlendEquationSeparate = 0x0040, BlendFuncSeparate = 0x0080,
BlendSubtract = 0x0100, CompressedTextures = 0x0200, Multisample = 0x0400, StencilSeparate = 0x0800,
NPOTTextures = 0x1000
}
This enum defines OpenGL/ES 2.
Public Functions
void glActiveTexture (GLenum texture)
Convenience function that calls glActiveTexture(texture).
void glAttachShader (GLuint program, GLuint shader)
Convenience function that calls glAttachShader(program, shader).
void glBindAttribLocation (GLuint program, GLuint index, const char *name)
Convenience function that calls glBindAttribLocation(program, index, name).
void glBindBuffer (GLenum target, GLuint buffer)
Convenience function that calls glBindBuffer(target, buffer).
void glBindFramebuffer (GLenum target, GLuint framebuffer)
Convenience function that calls glBindFramebuffer(target, framebuffer).
void glBindRenderbuffer (GLenum target, GLuint renderbuffer)
Convenience function that calls glBindRenderbuffer(target, renderbuffer).
void glBlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Convenience function that calls glBlendColor(red, green, blue, alpha).
void glBlendEquation (GLenum mode)
Convenience function that calls glBlendEquation(mode).
void glBlendEquationSeparate (GLenum modeRGB, GLenum modeAlpha)
Convenience function that calls glBlendEquationSeparate(modeRGB, modeAlpha).
void glBlendFuncSeparate (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
Convenience function that calls glBlendFuncSeparate(srcRGB, dstRGB, srcAlpha, dstAlpha).
void glBufferData (GLenum target, qgl_GLsizeiptr size, const void *data, GLenum usage)
Convenience function that calls glBufferData(target, size, data, usage).
void glBufferSubData (GLenum target, qgl_GLintptr offset, qgl_GLsizeiptr size, const void *data)
Convenience function that calls glBufferSubData(target, offset, size, data).
GLenum glCheckFramebufferStatus (GLenum target)
Convenience function that calls glCheckFramebufferStatus(target).
void glClearDepthf (GLclampf depth)
Convenience function that calls glClearDepth(depth) on desktop OpenGL systems and glClearDepthf(depth) on embedded OpenGL/ES systems.
void glCompileShader (GLuint shader)
Convenience function that calls glCompileShader(shader).
void glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data)
Convenience function that calls glCompressedTexImage2D(target, level, internalformat, width, height, border, imageSize, data).
void glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data)
Convenience function that calls glCompressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, data).
GLuint glCreateProgram ()
Convenience function that calls glCreateProgram().
GLuint glCreateShader (GLenum type)
Convenience function that calls glCreateShader(type).
void glDeleteBuffers (GLsizei n, const GLuint *buffers)
Convenience function that calls glDeleteBuffers(n, buffers).
void glDeleteFramebuffers (GLsizei n, const GLuint *framebuffers)
Convenience function that calls glDeleteFramebuffers(n, framebuffers).
void glDeleteProgram (GLuint program)
Convenience function that calls glDeleteProgram(program).
void glDeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers)
Convenience function that calls glDeleteRenderbuffers(n, renderbuffers).
void glDeleteShader (GLuint shader)
Convenience function that calls glDeleteShader(shader).
void glDepthRangef (GLclampf zNear, GLclampf zFar)
Convenience function that calls glDepthRange(zNear, zFar) on desktop OpenGL systems and glDepthRangef(zNear, zFar) on embedded OpenGL/ES systems.
void glDetachShader (GLuint program, GLuint shader)
Convenience function that calls glDetachShader(program, shader).
void glDisableVertexAttribArray (GLuint index)
Convenience function that calls glDisableVertexAttribArray(index).
void glEnableVertexAttribArray (GLuint index)
Convenience function that calls glEnableVertexAttribArray(index).
void glFramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
Convenience function that calls glFramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer).
void glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Convenience function that calls glFramebufferTexture2D(target, attachment, textarget, texture, level).
void glGenBuffers (GLsizei n, GLuint *buffers)
Convenience function that calls glGenBuffers(n, buffers).
void glGenerateMipmap (GLenum target)
Convenience function that calls glGenerateMipmap(target).
void glGenFramebuffers (GLsizei n, GLuint *framebuffers)
Convenience function that calls glGenFramebuffers(n, framebuffers).
void glGenRenderbuffers (GLsizei n, GLuint *renderbuffers)
Convenience function that calls glGenRenderbuffers(n, renderbuffers).
void glGetActiveAttrib (GLuint program, GLuint index, GLsizei bufsize, GLsizei *length, GLint *size, GLenum *type, char *name)
Convenience function that calls glGetActiveAttrib(program, index, bufsize, length, size, type, name).
void glGetActiveUniform (GLuint program, GLuint index, GLsizei bufsize, GLsizei *length, GLint *size, GLenum *type, char *name)
Convenience function that calls glGetActiveUniform(program, index, bufsize, length, size, type, name).
void glGetAttachedShaders (GLuint program, GLsizei maxcount, GLsizei *count, GLuint *shaders)
Convenience function that calls glGetAttachedShaders(program, maxcount, count, shaders).
int glGetAttribLocation (GLuint program, const char *name)
Convenience function that calls glGetAttribLocation(program, name).
void glGetBufferParameteriv (GLenum target, GLenum pname, GLint *params)
Convenience function that calls glGetBufferParameteriv(target, pname, params).
void glGetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params)
Convenience function that calls glGetFramebufferAttachmentParameteriv(target, attachment, pname, params).
void glGetProgramInfoLog (GLuint program, GLsizei bufsize, GLsizei *length, char *infolog)
Convenience function that calls glGetProgramInfoLog(program, bufsize, length, infolog).
void glGetProgramiv (GLuint program, GLenum pname, GLint *params)
Convenience function that calls glGetProgramiv(program, pname, params).
void glGetRenderbufferParameteriv (GLenum target, GLenum pname, GLint *params)
Convenience function that calls glGetRenderbufferParameteriv(target, pname, params).
void glGetShaderInfoLog (GLuint shader, GLsizei bufsize, GLsizei *length, char *infolog)
Convenience function that calls glGetShaderInfoLog(shader, bufsize, length, infolog).
void glGetShaderiv (GLuint shader, GLenum pname, GLint *params)
Convenience function that calls glGetShaderiv(shader, pname, params).
void glGetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision)
Convenience function that calls glGetShaderPrecisionFormat(shadertype, precisiontype, range, precision).
void glGetShaderSource (GLuint shader, GLsizei bufsize, GLsizei *length, char *source)
Convenience function that calls glGetShaderSource(shader, bufsize, length, source).
void glGetUniformfv (GLuint program, GLint location, GLfloat *params)
Convenience function that calls glGetUniformfv(program, location, params).
void glGetUniformiv (GLuint program, GLint location, GLint *params)
Convenience function that calls glGetUniformiv(program, location, params).
int glGetUniformLocation (GLuint program, const char *name)
Convenience function that calls glGetUniformLocation(program, name).
void glGetVertexAttribfv (GLuint index, GLenum pname, GLfloat *params)
Convenience function that calls glGetVertexAttribfv(index, pname, params).
void glGetVertexAttribiv (GLuint index, GLenum pname, GLint *params)
Convenience function that calls glGetVertexAttribiv(index, pname, params).
void glGetVertexAttribPointerv (GLuint index, GLenum pname, void **pointer)
Convenience function that calls glGetVertexAttribPointerv(index, pname, pointer).
GLboolean glIsBuffer (GLuint buffer)
Convenience function that calls glIsBuffer(buffer).
GLboolean glIsFramebuffer (GLuint framebuffer)
Convenience function that calls glIsFramebuffer(framebuffer).
GLboolean glIsProgram (GLuint program)
Convenience function that calls glIsProgram(program).
GLboolean glIsRenderbuffer (GLuint renderbuffer)
Convenience function that calls glIsRenderbuffer(renderbuffer).
GLboolean glIsShader (GLuint shader)
Convenience function that calls glIsShader(shader).
void glLinkProgram (GLuint program)
Convenience function that calls glLinkProgram(program).
void glReleaseShaderCompiler ()
Convenience function that calls glReleaseShaderCompiler().
void glRenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
Convenience function that calls glRenderbufferStorage(target, internalformat, width, height).
void glSampleCoverage (GLclampf value, GLboolean invert)
Convenience function that calls glSampleCoverage(value, invert).
void glShaderBinary (GLint n, const GLuint *shaders, GLenum binaryformat, const void *binary, GLint length)
Convenience function that calls glShaderBinary(n, shaders, binaryformat, binary, length).
void glShaderSource (GLuint shader, GLsizei count, const char **string, const GLint *length)
Convenience function that calls glShaderSource(shader, count, string, length).
void glStencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask)
Convenience function that calls glStencilFuncSeparate(face, func, ref, mask).
void glStencilMaskSeparate (GLenum face, GLuint mask)
Convenience function that calls glStencilMaskSeparate(face, mask).
void glStencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
Convenience function that calls glStencilOpSeparate(face, fail, zfail, zpass).
void glUniform1f (GLint location, GLfloat x)
Convenience function that calls glUniform1f(location, x).
void glUniform1fv (GLint location, GLsizei count, const GLfloat *v)
Convenience function that calls glUniform1fv(location, count, v).
void glUniform1i (GLint location, GLint x)
Convenience function that calls glUniform1i(location, x).
void glUniform1iv (GLint location, GLsizei count, const GLint *v)
Convenience function that calls glUniform1iv(location, count, v).
void glUniform2f (GLint location, GLfloat x, GLfloat y)
Convenience function that calls glUniform2f(location, x, y).
void glUniform2fv (GLint location, GLsizei count, const GLfloat *v)
Convenience function that calls glUniform2fv(location, count, v).
void glUniform2i (GLint location, GLint x, GLint y)
Convenience function that calls glUniform2i(location, x, y).
void glUniform2iv (GLint location, GLsizei count, const GLint *v)
Convenience function that calls glUniform2iv(location, count, v).
void glUniform3f (GLint location, GLfloat x, GLfloat y, GLfloat z)
Convenience function that calls glUniform3f(location, x, y, z).
void glUniform3fv (GLint location, GLsizei count, const GLfloat *v)
Convenience function that calls glUniform3fv(location, count, v).
void glUniform3i (GLint location, GLint x, GLint y, GLint z)
Convenience function that calls glUniform3i(location, x, y, z).
void glUniform3iv (GLint location, GLsizei count, const GLint *v)
Convenience function that calls glUniform3iv(location, count, v).
void glUniform4f (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Convenience function that calls glUniform4f(location, x, y, z, w).
void glUniform4fv (GLint location, GLsizei count, const GLfloat *v)
Convenience function that calls glUniform4fv(location, count, v).
void glUniform4i (GLint location, GLint x, GLint y, GLint z, GLint w)
Convenience function that calls glUniform4i(location, x, y, z, w).
void glUniform4iv (GLint location, GLsizei count, const GLint *v)
Convenience function that calls glUniform4iv(location, count, v).
void glUniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
Convenience function that calls glUniformMatrix2fv(location, count, transpose, value).
void glUniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
Convenience function that calls glUniformMatrix3fv(location, count, transpose, value).
void glUniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
Convenience function that calls glUniformMatrix4fv(location, count, transpose, value).
void glUseProgram (GLuint program)
Convenience function that calls glUseProgram(program).
void glValidateProgram (GLuint program)
Convenience function that calls glValidateProgram(program).
void glVertexAttrib1f (GLuint indx, GLfloat x)
Convenience function that calls glVertexAttrib1f(indx, x).
void glVertexAttrib1fv (GLuint indx, const GLfloat *values)
Convenience function that calls glVertexAttrib1fv(indx, values).
void glVertexAttrib2f (GLuint indx, GLfloat x, GLfloat y)
Convenience function that calls glVertexAttrib2f(indx, x, y).
void glVertexAttrib2fv (GLuint indx, const GLfloat *values)
Convenience function that calls glVertexAttrib2fv(indx, values).
void glVertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z)
Convenience function that calls glVertexAttrib3f(indx, x, y, z).
void glVertexAttrib3fv (GLuint indx, const GLfloat *values)
Convenience function that calls glVertexAttrib3fv(indx, values).
void glVertexAttrib4f (GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Convenience function that calls glVertexAttrib4f(indx, x, y, z, w).
void glVertexAttrib4fv (GLuint indx, const GLfloat *values)
Convenience function that calls glVertexAttrib4fv(indx, values).
void glVertexAttribPointer (GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *ptr)
Convenience function that calls glVertexAttribPointer(indx, size, type, normalized, stride, ptr).
bool hasOpenGLFeature (QGLFunctions::OpenGLFeature feature) const
Returns true if feature is present on this system's OpenGL implementation; false otherwise.
void initializeGLFunctions (const QGLContext *context=0)
Initializes GL function resolution for context.
QGLFunctions::OpenGLFeatures openGLFeatures () const
Returns the set of features that are present on this system's OpenGL implementation.
QGLFunctions ()
Constructs a default function resolver.
QGLFunctions (const QGLContext *context)
Constructs a function resolver for context.
~QGLFunctions ()
Destroys this function resolver.
Static Private Functions
static bool isInitialized (const QGLFunctionsPrivate *d)
Properties
QGLFunctionsPrivate * d_ptr
Detailed Description
The QGLFunctions class provides cross-platform access to the OpenGL/ES 2.0 API.
Since
4.8
OpenGL/ES 2.0 defines a subset of the OpenGL specification that is common across many desktop and embedded OpenGL implementations. However, it can be difficult to use the functions from that subset because they need to be resolved manually on desktop systems.
QGLFunctions provides a guaranteed API that is available on all OpenGL systems and takes care of function resolution on systems that need it. The recommended way to use QGLFunctions is by direct inheritance:
class MyGLWidget : public QGLWidget, protected QGLFunctions
{
    Q_OBJECT
public:
    MyGLWidget(QWidget *parent = 0) : QGLWidget(parent) {}
protected:
    void initializeGL();
    void paintGL();
};
void MyGLWidget::initializeGL()
{
    initializeGLFunctions();
}
The paintGL() function can then use any of the OpenGL/ES 2.0 functions without explicit resolution, such as glActiveTexture() in the following example:
void MyGLWidget::paintGL()
{
    glActiveTexture(GL_TEXTURE1);
    glBindTexture(GL_TEXTURE_2D, textureId);
    ...
}
QGLFunctions can also be used directly for ad-hoc invocation of OpenGL/ES 2.0 functions on all platforms:
QGLFunctions glFuncs(QGLContext::currentContext());
glFuncs.glActiveTexture(GL_TEXTURE1);
QGLFunctions provides wrappers for all OpenGL/ES 2.0 functions, except those like glDrawArrays(), glViewport(), and glBindTexture() that don't have portability issues.
Including the header for QGLFunctions will also define all of the OpenGL/ES 2.0 macro constants that are not already defined by the system's OpenGL headers, such as GL_TEXTURE1 above.
The hasOpenGLFeature() and openGLFeatures() functions can be used to determine if the OpenGL implementation has a major OpenGL/ES 2.0 feature. For example, the following checks if non power of two textures are available:
QGLFunctions funcs(QGLContext::currentContext());
bool npot = funcs.hasOpenGLFeature(QGLFunctions::NPOTTextures);
Definition at line 178 of file qglfunctions.h.
Enumerations
OpenGLFeature
enum QGLFunctions::OpenGLFeature
This enum defines OpenGL/ES 2.
0 features that may be optional on other platforms.
Multitexture glActiveTexture() function is available.
Shaders Shader functions are available.
Buffers Vertex and index buffer functions are available.
Framebuffers Framebuffer object functions are available.
BlendColor glBlendColor() is available.
BlendEquation glBlendEquation() is available.
BlendEquationSeparate glBlendEquationSeparate() is available.
BlendFuncSeparate glBlendFuncSeparate() is available.
BlendSubtract Blend subtract mode is available.
CompressedTextures Compressed texture functions are available.
Multisample glSampleCoverage() function is available.
StencilSeparate Separate stencil functions are available.
NPOTTextures Non power of two textures are available.
Enumerator
Multitexture
Shaders
Buffers
Framebuffers
BlendColor
BlendEquation
BlendEquationSeparate
BlendFuncSeparate
BlendSubtract
CompressedTextures
Multisample
StencilSeparate
NPOTTextures
Definition at line 185 of file qglfunctions.h.
     {
         Multitexture          = 0x0001,
         Shaders               = 0x0002,
         Buffers               = 0x0004,
         Framebuffers          = 0x0008,
         BlendColor            = 0x0010,
         BlendEquation         = 0x0020,
         BlendEquationSeparate = 0x0040,
         BlendFuncSeparate     = 0x0080,
         BlendSubtract         = 0x0100,
         CompressedTextures    = 0x0200,
         Multisample           = 0x0400,
         StencilSeparate       = 0x0800,
         NPOTTextures          = 0x1000
     };
Constructors and Destructors
QGLFunctions() [1/2]
QGLFunctions::QGLFunctions ()
Constructs a default function resolver.
The resolver cannot be used until initializeGLFunctions() is called to specify the context.
See also
initializeGLFunctions()
Definition at line 191 of file qglfunctions.cpp.
     : d_ptr(0)
 {
 }
QGLFunctions() [2/2]
QGLFunctions::QGLFunctions (const QGLContext * context) explicit
Constructs a function resolver for context.
If context is null, then the resolver will be created for the current QGLContext.
An object constructed in this way can only be used with context and other contexts that share with it. Use initializeGLFunctions() to change the object's context association.
See also
initializeGLFunctions()
Definition at line 206 of file qglfunctions.cpp.
     : d_ptr(qt_gl_functions(context))
 {
 }
~QGLFunctions()
QGLFunctions::~QGLFunctions () inline
Destroys this function resolver.
Definition at line 183 of file qglfunctions.h.
 {}
Functions
glActiveTexture()
void QGLFunctions::glActiveTexture (GLenum texture) inline
Convenience function that calls glActiveTexture(texture).
For more information, see the OpenGL/ES 2.0 documentation for glActiveTexture().
Definition at line 416 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_1) || defined(QT_OPENGL_ES_2)
     ::glActiveTexture(texture);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->activeTexture(texture);
 #endif
 }
glAttachShader()
void QGLFunctions::glAttachShader (GLuint program, GLuint shader) inline
Convenience function that calls glAttachShader(program, shader).
For more information, see the OpenGL/ES 2.0 documentation for glAttachShader().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 426 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glAttachShader(program, shader);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->attachShader(program, shader);
 #endif
 }
glBindAttribLocation()
void QGLFunctions::glBindAttribLocation (GLuint program, GLuint index, const char * name) inline
Convenience function that calls glBindAttribLocation(program, index, name).
For more information, see the OpenGL/ES 2.0 documentation for glBindAttribLocation().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 436 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glBindAttribLocation(program, index, name);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->bindAttribLocation(program, index, name);
 #endif
 }
glBindBuffer()
void QGLFunctions::glBindBuffer (GLenum target, GLuint buffer) inline
Convenience function that calls glBindBuffer(target, buffer).
For more information, see the OpenGL/ES 2.0 documentation for glBindBuffer().
Definition at line 446 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_1) || defined(QT_OPENGL_ES_2)
     ::glBindBuffer(target, buffer);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->bindBuffer(target, buffer);
 #endif
 }
glBindFramebuffer()
void QGLFunctions::glBindFramebuffer (GLenum target, GLuint framebuffer) inline
Convenience function that calls glBindFramebuffer(target, framebuffer).
For more information, see the OpenGL/ES 2.0 documentation for glBindFramebuffer().
Definition at line 456 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glBindFramebuffer(target, framebuffer);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->bindFramebuffer(target, framebuffer);
 #endif
 }
glBindRenderbuffer()
void QGLFunctions::glBindRenderbuffer (GLenum target, GLuint renderbuffer) inline
Convenience function that calls glBindRenderbuffer(target, renderbuffer).
For more information, see the OpenGL/ES 2.0 documentation for glBindRenderbuffer().
Definition at line 466 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glBindRenderbuffer(target, renderbuffer);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->bindRenderbuffer(target, renderbuffer);
 #endif
 }
glBlendColor()
void QGLFunctions::glBlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) inline
Convenience function that calls glBlendColor(red, green, blue, alpha).
For more information, see the OpenGL/ES 2.0 documentation for glBlendColor().
Definition at line 476 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glBlendColor(red, green, blue, alpha);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->blendColor(red, green, blue, alpha);
 #endif
 }
glBlendEquation()
void QGLFunctions::glBlendEquation (GLenum mode) inline
Convenience function that calls glBlendEquation(mode).
For more information, see the OpenGL/ES 2.0 documentation for glBlendEquation().
Definition at line 486 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glBlendEquation(mode);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->blendEquation(mode);
 #endif
 }
glBlendEquationSeparate()
void QGLFunctions::glBlendEquationSeparate (GLenum modeRGB, GLenum modeAlpha) inline
Convenience function that calls glBlendEquationSeparate(modeRGB, modeAlpha).
For more information, see the OpenGL/ES 2.0 documentation for glBlendEquationSeparate().
Definition at line 496 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glBlendEquationSeparate(modeRGB, modeAlpha);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->blendEquationSeparate(modeRGB, modeAlpha);
 #endif
 }
glBlendFuncSeparate()
void QGLFunctions::glBlendFuncSeparate (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha) inline
Convenience function that calls glBlendFuncSeparate(srcRGB, dstRGB, srcAlpha, dstAlpha).
For more information, see the OpenGL/ES 2.0 documentation for glBlendFuncSeparate().
Definition at line 506 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glBlendFuncSeparate(srcRGB, dstRGB, srcAlpha, dstAlpha);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->blendFuncSeparate(srcRGB, dstRGB, srcAlpha, dstAlpha);
 #endif
 }
glBufferData()
void QGLFunctions::glBufferData (GLenum target, qgl_GLsizeiptr size, const void * data, GLenum usage) inline
Convenience function that calls glBufferData(target, size, data, usage).
For more information, see the OpenGL/ES 2.0 documentation for glBufferData().
Definition at line 516 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_1) || defined(QT_OPENGL_ES_2)
     ::glBufferData(target, size, data, usage);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->bufferData(target, size, data, usage);
 #endif
 }
glBufferSubData()
void QGLFunctions::glBufferSubData (GLenum target, qgl_GLintptr offset, qgl_GLsizeiptr size, const void * data) inline
Convenience function that calls glBufferSubData(target, offset, size, data).
For more information, see the OpenGL/ES 2.0 documentation for glBufferSubData().
Definition at line 526 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_1) || defined(QT_OPENGL_ES_2)
     ::glBufferSubData(target, offset, size, data);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->bufferSubData(target, offset, size, data);
 #endif
 }
glCheckFramebufferStatus()
GLenum QGLFunctions::glCheckFramebufferStatus (GLenum target) inline
Convenience function that calls glCheckFramebufferStatus(target).
For more information, see the OpenGL/ES 2.0 documentation for glCheckFramebufferStatus().
Definition at line 536 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     return ::glCheckFramebufferStatus(target);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     return d_ptr->checkFramebufferStatus(target);
 #endif
 }
glClearDepthf()
void QGLFunctions::glClearDepthf (GLclampf depth) inline
Convenience function that calls glClearDepth(depth) on desktop OpenGL systems and glClearDepthf(depth) on embedded OpenGL/ES systems.
For more information, see the OpenGL/ES 2.0 documentation for glClearDepthf().
Definition at line 546 of file qglfunctions.h.
 {
 #ifndef QT_OPENGL_ES
     ::glClearDepth(depth);
 #else
     ::glClearDepthf(depth);
 #endif
 }
glCompileShader()
void QGLFunctions::glCompileShader (GLuint shader) inline
Convenience function that calls glCompileShader(shader).
For more information, see the OpenGL/ES 2.0 documentation for glCompileShader().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 555 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glCompileShader(shader);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->compileShader(shader);
 #endif
 }
glCompressedTexImage2D()
void QGLFunctions::glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void * data) inline
Convenience function that calls glCompressedTexImage2D(target, level, internalformat, width, height, border, imageSize, data).
For more information, see the OpenGL/ES 2.0 documentation for glCompressedTexImage2D().
Definition at line 565 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_1) || defined(QT_OPENGL_ES_2)
     ::glCompressedTexImage2D(target, level, internalformat, width, height, border, imageSize, data);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->compressedTexImage2D(target, level, internalformat, width, height, border, imageSize, data);
 #endif
 }
glCompressedTexSubImage2D()
void QGLFunctions::glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void * data) inline
Convenience function that calls glCompressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, data).
For more information, see the OpenGL/ES 2.0 documentation for glCompressedTexSubImage2D().
Definition at line 575 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_1) || defined(QT_OPENGL_ES_2)
     ::glCompressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, data);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->compressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, data);
 #endif
 }
glCreateProgram()
GLuint QGLFunctions::glCreateProgram () inline
Convenience function that calls glCreateProgram().
For more information, see the OpenGL/ES 2.0 documentation for glCreateProgram().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 585 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     return ::glCreateProgram();
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     return d_ptr->createProgram();
 #endif
 }
glCreateShader()
GLuint QGLFunctions::glCreateShader (GLenum type) inline
Convenience function that calls glCreateShader(type).
For more information, see the OpenGL/ES 2.0 documentation for glCreateShader().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 595 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     return ::glCreateShader(type);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     return d_ptr->createShader(type);
 #endif
 }
glDeleteBuffers()
void QGLFunctions::glDeleteBuffers (GLsizei n, const GLuint * buffers) inline
Convenience function that calls glDeleteBuffers(n, buffers).
For more information, see the OpenGL/ES 2.0 documentation for glDeleteBuffers().
Definition at line 605 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_1) || defined(QT_OPENGL_ES_2)
     ::glDeleteBuffers(n, buffers);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->deleteBuffers(n, buffers);
 #endif
 }
glDeleteFramebuffers()
void QGLFunctions::glDeleteFramebuffers (GLsizei n, const GLuint * framebuffers) inline
Convenience function that calls glDeleteFramebuffers(n, framebuffers).
For more information, see the OpenGL/ES 2.0 documentation for glDeleteFramebuffers().
Definition at line 615 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glDeleteFramebuffers(n, framebuffers);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->deleteFramebuffers(n, framebuffers);
 #endif
 }
glDeleteProgram()
void QGLFunctions::glDeleteProgram (GLuint program) inline
Convenience function that calls glDeleteProgram(program).
For more information, see the OpenGL/ES 2.0 documentation for glDeleteProgram().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 625 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glDeleteProgram(program);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->deleteProgram(program);
 #endif
 }
glDeleteRenderbuffers()
void QGLFunctions::glDeleteRenderbuffers (GLsizei n, const GLuint * renderbuffers) inline
Convenience function that calls glDeleteRenderbuffers(n, renderbuffers).
For more information, see the OpenGL/ES 2.0 documentation for glDeleteRenderbuffers().
Definition at line 635 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glDeleteRenderbuffers(n, renderbuffers);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->deleteRenderbuffers(n, renderbuffers);
 #endif
 }
glDeleteShader()
void QGLFunctions::glDeleteShader (GLuint shader) inline
Convenience function that calls glDeleteShader(shader).
For more information, see the OpenGL/ES 2.0 documentation for glDeleteShader().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 645 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glDeleteShader(shader);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->deleteShader(shader);
 #endif
 }
glDepthRangef()
void QGLFunctions::glDepthRangef (GLclampf zNear, GLclampf zFar) inline
Convenience function that calls glDepthRange(zNear, zFar) on desktop OpenGL systems and glDepthRangef(zNear, zFar) on embedded OpenGL/ES systems.
For more information, see the OpenGL/ES 2.0 documentation for glDepthRangef().
Definition at line 655 of file qglfunctions.h.
 {
 #ifndef QT_OPENGL_ES
     ::glDepthRange(zNear, zFar);
 #else
     ::glDepthRangef(zNear, zFar);
 #endif
 }
glDetachShader()
void QGLFunctions::glDetachShader (GLuint program, GLuint shader) inline
Convenience function that calls glDetachShader(program, shader).
For more information, see the OpenGL/ES 2.0 documentation for glDetachShader().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 664 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glDetachShader(program, shader);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->detachShader(program, shader);
 #endif
 }
glDisableVertexAttribArray()
void QGLFunctions::glDisableVertexAttribArray (GLuint index) inline
Convenience function that calls glDisableVertexAttribArray(index).
For more information, see the OpenGL/ES 2.0 documentation for glDisableVertexAttribArray().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 674 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glDisableVertexAttribArray(index);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->disableVertexAttribArray(index);
 #endif
 }
glEnableVertexAttribArray()
void QGLFunctions::glEnableVertexAttribArray (GLuint index) inline
Convenience function that calls glEnableVertexAttribArray(index).
For more information, see the OpenGL/ES 2.0 documentation for glEnableVertexAttribArray().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 684 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glEnableVertexAttribArray(index);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->enableVertexAttribArray(index);
 #endif
 }
glFramebufferRenderbuffer()
void QGLFunctions::glFramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) inline
Convenience function that calls glFramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer).
For more information, see the OpenGL/ES 2.0 documentation for glFramebufferRenderbuffer().
Definition at line 694 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glFramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->framebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer);
 #endif
 }
glFramebufferTexture2D()
void QGLFunctions::glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) inline
Convenience function that calls glFramebufferTexture2D(target, attachment, textarget, texture, level).
For more information, see the OpenGL/ES 2.0 documentation for glFramebufferTexture2D().
Definition at line 704 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glFramebufferTexture2D(target, attachment, textarget, texture, level);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->framebufferTexture2D(target, attachment, textarget, texture, level);
 #endif
 }
glGenBuffers()
void QGLFunctions::glGenBuffers (GLsizei n, GLuint * buffers) inline
Convenience function that calls glGenBuffers(n, buffers).
For more information, see the OpenGL/ES 2.0 documentation for glGenBuffers().
Definition at line 714 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_1) || defined(QT_OPENGL_ES_2)
     ::glGenBuffers(n, buffers);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->genBuffers(n, buffers);
 #endif
 }
glGenerateMipmap()
void QGLFunctions::glGenerateMipmap (GLenum target) inline
Convenience function that calls glGenerateMipmap(target).
For more information, see the OpenGL/ES 2.0 documentation for glGenerateMipmap().
Definition at line 724 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGenerateMipmap(target);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->generateMipmap(target);
 #endif
 }
glGenFramebuffers()
void QGLFunctions::glGenFramebuffers (GLsizei n, GLuint * framebuffers) inline
Convenience function that calls glGenFramebuffers(n, framebuffers).
For more information, see the OpenGL/ES 2.0 documentation for glGenFramebuffers().
Definition at line 734 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGenFramebuffers(n, framebuffers);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->genFramebuffers(n, framebuffers);
 #endif
 }
glGenRenderbuffers()
void QGLFunctions::glGenRenderbuffers (GLsizei n, GLuint * renderbuffers) inline
Convenience function that calls glGenRenderbuffers(n, renderbuffers).
For more information, see the OpenGL/ES 2.0 documentation for glGenRenderbuffers().
Definition at line 744 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGenRenderbuffers(n, renderbuffers);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->genRenderbuffers(n, renderbuffers);
 #endif
 }
glGetActiveAttrib()
void QGLFunctions::glGetActiveAttrib (GLuint program, GLuint index, GLsizei bufsize, GLsizei * length, GLint * size, GLenum * type, char * name) inline
Convenience function that calls glGetActiveAttrib(program, index, bufsize, length, size, type, name).
For more information, see the OpenGL/ES 2.0 documentation for glGetActiveAttrib().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 754 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetActiveAttrib(program, index, bufsize, length, size, type, name);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getActiveAttrib(program, index, bufsize, length, size, type, name);
 #endif
 }
glGetActiveUniform()
void QGLFunctions::glGetActiveUniform (GLuint program, GLuint index, GLsizei bufsize, GLsizei * length, GLint * size, GLenum * type, char * name) inline
Convenience function that calls glGetActiveUniform(program, index, bufsize, length, size, type, name).
For more information, see the OpenGL/ES 2.0 documentation for glGetActiveUniform().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 764 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetActiveUniform(program, index, bufsize, length, size, type, name);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getActiveUniform(program, index, bufsize, length, size, type, name);
 #endif
 }
glGetAttachedShaders()
void QGLFunctions::glGetAttachedShaders (GLuint program, GLsizei maxcount, GLsizei * count, GLuint * shaders) inline
Convenience function that calls glGetAttachedShaders(program, maxcount, count, shaders).
For more information, see the OpenGL/ES 2.0 documentation for glGetAttachedShaders().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 774 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetAttachedShaders(program, maxcount, count, shaders);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getAttachedShaders(program, maxcount, count, shaders);
 #endif
 }
glGetAttribLocation()
int QGLFunctions::glGetAttribLocation (GLuint program, const char * name) inline
Convenience function that calls glGetAttribLocation(program, name).
For more information, see the OpenGL/ES 2.0 documentation for glGetAttribLocation().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 784 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     return ::glGetAttribLocation(program, name);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     return d_ptr->getAttribLocation(program, name);
 #endif
 }
glGetBufferParameteriv()
void QGLFunctions::glGetBufferParameteriv (GLenum target, GLenum pname, GLint * params) inline
Convenience function that calls glGetBufferParameteriv(target, pname, params).
For more information, see the OpenGL/ES 2.0 documentation for glGetBufferParameteriv().
Definition at line 794 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetBufferParameteriv(target, pname, params);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getBufferParameteriv(target, pname, params);
 #endif
 }
glGetFramebufferAttachmentParameteriv()
void QGLFunctions::glGetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint * params) inline
Convenience function that calls glGetFramebufferAttachmentParameteriv(target, attachment, pname, params).
For more information, see the OpenGL/ES 2.0 documentation for glGetFramebufferAttachmentParameteriv().
Definition at line 804 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetFramebufferAttachmentParameteriv(target, attachment, pname, params);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getFramebufferAttachmentParameteriv(target, attachment, pname, params);
 #endif
 }
glGetProgramInfoLog()
void QGLFunctions::glGetProgramInfoLog (GLuint program, GLsizei bufsize, GLsizei * length, char * infolog) inline
Convenience function that calls glGetProgramInfoLog(program, bufsize, length, infolog).
For more information, see the OpenGL/ES 2.0 documentation for glGetProgramInfoLog().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 824 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetProgramInfoLog(program, bufsize, length, infolog);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getProgramInfoLog(program, bufsize, length, infolog);
 #endif
 }
glGetProgramiv()
void QGLFunctions::glGetProgramiv (GLuint program, GLenum pname, GLint * params) inline
Convenience function that calls glGetProgramiv(program, pname, params).
For more information, see the OpenGL/ES 2.0 documentation for glGetProgramiv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 814 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetProgramiv(program, pname, params);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getProgramiv(program, pname, params);
 #endif
 }
glGetRenderbufferParameteriv()
void QGLFunctions::glGetRenderbufferParameteriv (GLenum target, GLenum pname, GLint * params) inline
Convenience function that calls glGetRenderbufferParameteriv(target, pname, params).
For more information, see the OpenGL/ES 2.0 documentation for glGetRenderbufferParameteriv().
Definition at line 834 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetRenderbufferParameteriv(target, pname, params);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getRenderbufferParameteriv(target, pname, params);
 #endif
 }
glGetShaderInfoLog()
void QGLFunctions::glGetShaderInfoLog (GLuint shader, GLsizei bufsize, GLsizei * length, char * infolog) inline
Convenience function that calls glGetShaderInfoLog(shader, bufsize, length, infolog).
For more information, see the OpenGL/ES 2.0 documentation for glGetShaderInfoLog().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 854 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetShaderInfoLog(shader, bufsize, length, infolog);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getShaderInfoLog(shader, bufsize, length, infolog);
 #endif
 }
glGetShaderiv()
void QGLFunctions::glGetShaderiv (GLuint shader, GLenum pname, GLint * params) inline
Convenience function that calls glGetShaderiv(shader, pname, params).
For more information, see the OpenGL/ES 2.0 documentation for glGetShaderiv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 844 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetShaderiv(shader, pname, params);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getShaderiv(shader, pname, params);
 #endif
 }
glGetShaderPrecisionFormat()
void QGLFunctions::glGetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint * range, GLint * precision) inline
Convenience function that calls glGetShaderPrecisionFormat(shadertype, precisiontype, range, precision).
For more information, see the OpenGL/ES 2.0 documentation for glGetShaderPrecisionFormat().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 864 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetShaderPrecisionFormat(shadertype, precisiontype, range, precision);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getShaderPrecisionFormat(shadertype, precisiontype, range, precision);
 #endif
 }
glGetShaderSource()
void QGLFunctions::glGetShaderSource (GLuint shader, GLsizei bufsize, GLsizei * length, char * source) inline
Convenience function that calls glGetShaderSource(shader, bufsize, length, source).
For more information, see the OpenGL/ES 2.0 documentation for glGetShaderSource().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 874 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetShaderSource(shader, bufsize, length, source);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getShaderSource(shader, bufsize, length, source);
 #endif
 }
glGetUniformfv()
void QGLFunctions::glGetUniformfv (GLuint program, GLint location, GLfloat * params) inline
Convenience function that calls glGetUniformfv(program, location, params).
For more information, see the OpenGL/ES 2.0 documentation for glGetUniformfv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 884 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetUniformfv(program, location, params);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getUniformfv(program, location, params);
 #endif
 }
glGetUniformiv()
void QGLFunctions::glGetUniformiv (GLuint program, GLint location, GLint * params) inline
Convenience function that calls glGetUniformiv(program, location, params).
For more information, see the OpenGL/ES 2.0 documentation for glGetUniformiv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 894 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetUniformiv(program, location, params);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getUniformiv(program, location, params);
 #endif
 }
glGetUniformLocation()
int QGLFunctions::glGetUniformLocation (GLuint program, const char * name) inline
Convenience function that calls glGetUniformLocation(program, name).
For more information, see the OpenGL/ES 2.0 documentation for glGetUniformLocation().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 904 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     return ::glGetUniformLocation(program, name);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     return d_ptr->getUniformLocation(program, name);
 #endif
 }
glGetVertexAttribfv()
void QGLFunctions::glGetVertexAttribfv (GLuint index, GLenum pname, GLfloat * params) inline
Convenience function that calls glGetVertexAttribfv(index, pname, params).
For more information, see the OpenGL/ES 2.0 documentation for glGetVertexAttribfv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 914 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetVertexAttribfv(index, pname, params);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getVertexAttribfv(index, pname, params);
 #endif
 }
glGetVertexAttribiv()
void QGLFunctions::glGetVertexAttribiv (GLuint index, GLenum pname, GLint * params) inline
Convenience function that calls glGetVertexAttribiv(index, pname, params).
For more information, see the OpenGL/ES 2.0 documentation for glGetVertexAttribiv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 924 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetVertexAttribiv(index, pname, params);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getVertexAttribiv(index, pname, params);
 #endif
 }
glGetVertexAttribPointerv()
void QGLFunctions::glGetVertexAttribPointerv (GLuint index, GLenum pname, void ** pointer) inline
Convenience function that calls glGetVertexAttribPointerv(index, pname, pointer).
For more information, see the OpenGL/ES 2.0 documentation for glGetVertexAttribPointerv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 934 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glGetVertexAttribPointerv(index, pname, pointer);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->getVertexAttribPointerv(index, pname, pointer);
 #endif
 }
glIsBuffer()
GLboolean QGLFunctions::glIsBuffer (GLuint buffer) inline
Convenience function that calls glIsBuffer(buffer).
For more information, see the OpenGL/ES 2.0 documentation for glIsBuffer().
Definition at line 944 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_1) || defined(QT_OPENGL_ES_2)
     return ::glIsBuffer(buffer);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     return d_ptr->isBuffer(buffer);
 #endif
 }
glIsFramebuffer()
GLboolean QGLFunctions::glIsFramebuffer (GLuint framebuffer) inline
Convenience function that calls glIsFramebuffer(framebuffer).
For more information, see the OpenGL/ES 2.0 documentation for glIsFramebuffer().
Definition at line 954 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     return ::glIsFramebuffer(framebuffer);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     return d_ptr->isFramebuffer(framebuffer);
 #endif
 }
glIsProgram()
GLboolean QGLFunctions::glIsProgram (GLuint program) inline
Convenience function that calls glIsProgram(program).
For more information, see the OpenGL/ES 2.0 documentation for glIsProgram().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 964 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     return ::glIsProgram(program);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     return d_ptr->isProgram(program);
 #endif
 }
glIsRenderbuffer()
GLboolean QGLFunctions::glIsRenderbuffer (GLuint renderbuffer) inline
Convenience function that calls glIsRenderbuffer(renderbuffer).
For more information, see the OpenGL/ES 2.0 documentation for glIsRenderbuffer().
Definition at line 974 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     return ::glIsRenderbuffer(renderbuffer);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     return d_ptr->isRenderbuffer(renderbuffer);
 #endif
 }
glIsShader()
GLboolean QGLFunctions::glIsShader (GLuint shader) inline
Convenience function that calls glIsShader(shader).
For more information, see the OpenGL/ES 2.0 documentation for glIsShader().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 984 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     return ::glIsShader(shader);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     return d_ptr->isShader(shader);
 #endif
 }
glLinkProgram()
void QGLFunctions::glLinkProgram (GLuint program) inline
Convenience function that calls glLinkProgram(program).
For more information, see the OpenGL/ES 2.0 documentation for glLinkProgram().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 994 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glLinkProgram(program);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->linkProgram(program);
 #endif
 }
glReleaseShaderCompiler()
void QGLFunctions::glReleaseShaderCompiler () inline
Convenience function that calls glReleaseShaderCompiler().
For more information, see the OpenGL/ES 2.0 documentation for glReleaseShaderCompiler().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1004 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glReleaseShaderCompiler();
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->releaseShaderCompiler();
 #endif
 }
glRenderbufferStorage()
void QGLFunctions::glRenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height) inline
Convenience function that calls glRenderbufferStorage(target, internalformat, width, height).
For more information, see the OpenGL/ES 2.0 documentation for glRenderbufferStorage().
Definition at line 1014 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glRenderbufferStorage(target, internalformat, width, height);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->renderbufferStorage(target, internalformat, width, height);
 #endif
 }
glSampleCoverage()
void QGLFunctions::glSampleCoverage (GLclampf value, GLboolean invert) inline
Convenience function that calls glSampleCoverage(value, invert).
For more information, see the OpenGL/ES 2.0 documentation for glSampleCoverage().
Definition at line 1024 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_1) || defined(QT_OPENGL_ES_2)
     ::glSampleCoverage(value, invert);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->sampleCoverage(value, invert);
 #endif
 }
glShaderBinary()
void QGLFunctions::glShaderBinary (GLint n, const GLuint * shaders, GLenum binaryformat, const void * binary, GLint length) inline
Convenience function that calls glShaderBinary(n, shaders, binaryformat, binary, length).
For more information, see the OpenGL/ES 2.0 documentation for glShaderBinary().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1034 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glShaderBinary(n, shaders, binaryformat, binary, length);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->shaderBinary(n, shaders, binaryformat, binary, length);
 #endif
 }
glShaderSource()
void QGLFunctions::glShaderSource (GLuint shader, GLsizei count, const char ** string, const GLint * length) inline
Convenience function that calls glShaderSource(shader, count, string, length).
For more information, see the OpenGL/ES 2.0 documentation for glShaderSource().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1044 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glShaderSource(shader, count, string, length);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->shaderSource(shader, count, string, length);
 #endif
 }
glStencilFuncSeparate()
void QGLFunctions::glStencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask) inline
Convenience function that calls glStencilFuncSeparate(face, func, ref, mask).
For more information, see the OpenGL/ES 2.0 documentation for glStencilFuncSeparate().
Definition at line 1054 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glStencilFuncSeparate(face, func, ref, mask);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->stencilFuncSeparate(face, func, ref, mask);
 #endif
 }
glStencilMaskSeparate()
void QGLFunctions::glStencilMaskSeparate (GLenum face, GLuint mask) inline
Convenience function that calls glStencilMaskSeparate(face, mask).
For more information, see the OpenGL/ES 2.0 documentation for glStencilMaskSeparate().
Definition at line 1064 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glStencilMaskSeparate(face, mask);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->stencilMaskSeparate(face, mask);
 #endif
 }
glStencilOpSeparate()
void QGLFunctions::glStencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass) inline
Convenience function that calls glStencilOpSeparate(face, fail, zfail, zpass).
For more information, see the OpenGL/ES 2.0 documentation for glStencilOpSeparate().
Definition at line 1074 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glStencilOpSeparate(face, fail, zfail, zpass);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->stencilOpSeparate(face, fail, zfail, zpass);
 #endif
 }
glUniform1f()
void QGLFunctions::glUniform1f (GLint location, GLfloat x) inline
Convenience function that calls glUniform1f(location, x).
For more information, see the OpenGL/ES 2.0 documentation for glUniform1f().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1084 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform1f(location, x);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform1f(location, x);
 #endif
 }
glUniform1fv()
void QGLFunctions::glUniform1fv (GLint location, GLsizei count, const GLfloat * v) inline
Convenience function that calls glUniform1fv(location, count, v).
For more information, see the OpenGL/ES 2.0 documentation for glUniform1fv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1094 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform1fv(location, count, v);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform1fv(location, count, v);
 #endif
 }
glUniform1i()
void QGLFunctions::glUniform1i (GLint location, GLint x) inline
Convenience function that calls glUniform1i(location, x).
For more information, see the OpenGL/ES 2.0 documentation for glUniform1i().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1104 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform1i(location, x);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform1i(location, x);
 #endif
 }
glUniform1iv()
void QGLFunctions::glUniform1iv (GLint location, GLsizei count, const GLint * v) inline
Convenience function that calls glUniform1iv(location, count, v).
For more information, see the OpenGL/ES 2.0 documentation for glUniform1iv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1114 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform1iv(location, count, v);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform1iv(location, count, v);
 #endif
 }
glUniform2f()
void QGLFunctions::glUniform2f (GLint location, GLfloat x, GLfloat y) inline
Convenience function that calls glUniform2f(location, x, y).
For more information, see the OpenGL/ES 2.0 documentation for glUniform2f().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1124 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform2f(location, x, y);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform2f(location, x, y);
 #endif
 }
glUniform2fv()
void QGLFunctions::glUniform2fv (GLint location, GLsizei count, const GLfloat * v) inline
Convenience function that calls glUniform2fv(location, count, v).
For more information, see the OpenGL/ES 2.0 documentation for glUniform2fv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1134 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform2fv(location, count, v);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform2fv(location, count, v);
 #endif
 }
glUniform2i()
void QGLFunctions::glUniform2i (GLint location, GLint x, GLint y) inline
Convenience function that calls glUniform2i(location, x, y).
For more information, see the OpenGL/ES 2.0 documentation for glUniform2i().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1144 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform2i(location, x, y);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform2i(location, x, y);
 #endif
 }
glUniform2iv()
void QGLFunctions::glUniform2iv (GLint location, GLsizei count, const GLint * v) inline
Convenience function that calls glUniform2iv(location, count, v).
For more information, see the OpenGL/ES 2.0 documentation for glUniform2iv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1154 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform2iv(location, count, v);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform2iv(location, count, v);
 #endif
 }
glUniform3f()
void QGLFunctions::glUniform3f (GLint location, GLfloat x, GLfloat y, GLfloat z) inline
Convenience function that calls glUniform3f(location, x, y, z).
For more information, see the OpenGL/ES 2.0 documentation for glUniform3f().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1164 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform3f(location, x, y, z);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform3f(location, x, y, z);
 #endif
 }
glUniform3fv()
void QGLFunctions::glUniform3fv (GLint location, GLsizei count, const GLfloat * v) inline
Convenience function that calls glUniform3fv(location, count, v).
For more information, see the OpenGL/ES 2.0 documentation for glUniform3fv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1174 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform3fv(location, count, v);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform3fv(location, count, v);
 #endif
 }
glUniform3i()
void QGLFunctions::glUniform3i (GLint location, GLint x, GLint y, GLint z) inline
Convenience function that calls glUniform3i(location, x, y, z).
For more information, see the OpenGL/ES 2.0 documentation for glUniform3i().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1184 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform3i(location, x, y, z);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform3i(location, x, y, z);
 #endif
 }
glUniform3iv()
void QGLFunctions::glUniform3iv (GLint location, GLsizei count, const GLint * v) inline
Convenience function that calls glUniform3iv(location, count, v).
For more information, see the OpenGL/ES 2.0 documentation for glUniform3iv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1194 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform3iv(location, count, v);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform3iv(location, count, v);
 #endif
 }
glUniform4f()
void QGLFunctions::glUniform4f (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w) inline
Convenience function that calls glUniform4f(location, x, y, z, w).
For more information, see the OpenGL/ES 2.0 documentation for glUniform4f().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1204 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform4f(location, x, y, z, w);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform4f(location, x, y, z, w);
 #endif
 }
glUniform4fv()
void QGLFunctions::glUniform4fv (GLint location, GLsizei count, const GLfloat * v) inline
Convenience function that calls glUniform4fv(location, count, v).
For more information, see the OpenGL/ES 2.0 documentation for glUniform4fv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1214 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform4fv(location, count, v);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform4fv(location, count, v);
 #endif
 }
glUniform4i()
void QGLFunctions::glUniform4i (GLint location, GLint x, GLint y, GLint z, GLint w) inline
Convenience function that calls glUniform4i(location, x, y, z, w).
For more information, see the OpenGL/ES 2.0 documentation for glUniform4i().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1224 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform4i(location, x, y, z, w);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform4i(location, x, y, z, w);
 #endif
 }
glUniform4iv()
void QGLFunctions::glUniform4iv (GLint location, GLsizei count, const GLint * v) inline
Convenience function that calls glUniform4iv(location, count, v).
For more information, see the OpenGL/ES 2.0 documentation for glUniform4iv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1234 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniform4iv(location, count, v);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniform4iv(location, count, v);
 #endif
 }
glUniformMatrix2fv()
void QGLFunctions::glUniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) inline
Convenience function that calls glUniformMatrix2fv(location, count, transpose, value).
For more information, see the OpenGL/ES 2.0 documentation for glUniformMatrix2fv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1244 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniformMatrix2fv(location, count, transpose, value);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniformMatrix2fv(location, count, transpose, value);
 #endif
 }
glUniformMatrix3fv()
void QGLFunctions::glUniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) inline
Convenience function that calls glUniformMatrix3fv(location, count, transpose, value).
For more information, see the OpenGL/ES 2.0 documentation for glUniformMatrix3fv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1254 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniformMatrix3fv(location, count, transpose, value);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniformMatrix3fv(location, count, transpose, value);
 #endif
 }
glUniformMatrix4fv()
void QGLFunctions::glUniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) inline
Convenience function that calls glUniformMatrix4fv(location, count, transpose, value).
For more information, see the OpenGL/ES 2.0 documentation for glUniformMatrix4fv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1264 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUniformMatrix4fv(location, count, transpose, value);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->uniformMatrix4fv(location, count, transpose, value);
 #endif
 }
glUseProgram()
void QGLFunctions::glUseProgram (GLuint program) inline
Convenience function that calls glUseProgram(program).
For more information, see the OpenGL/ES 2.0 documentation for glUseProgram().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1274 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glUseProgram(program);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->useProgram(program);
 #endif
 }
glValidateProgram()
void QGLFunctions::glValidateProgram (GLuint program) inline
Convenience function that calls glValidateProgram(program).
For more information, see the OpenGL/ES 2.0 documentation for glValidateProgram().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1284 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glValidateProgram(program);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->validateProgram(program);
 #endif
 }
glVertexAttrib1f()
void QGLFunctions::glVertexAttrib1f (GLuint indx, GLfloat x) inline
Convenience function that calls glVertexAttrib1f(indx, x).
For more information, see the OpenGL/ES 2.0 documentation for glVertexAttrib1f().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1294 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glVertexAttrib1f(indx, x);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->vertexAttrib1f(indx, x);
 #endif
 }
glVertexAttrib1fv()
void QGLFunctions::glVertexAttrib1fv (GLuint indx, const GLfloat * values) inline
Convenience function that calls glVertexAttrib1fv(indx, values).
For more information, see the OpenGL/ES 2.0 documentation for glVertexAttrib1fv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1304 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glVertexAttrib1fv(indx, values);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->vertexAttrib1fv(indx, values);
 #endif
 }
glVertexAttrib2f()
void QGLFunctions::glVertexAttrib2f (GLuint indx, GLfloat x, GLfloat y) inline
Convenience function that calls glVertexAttrib2f(indx, x, y).
For more information, see the OpenGL/ES 2.0 documentation for glVertexAttrib2f().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1314 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glVertexAttrib2f(indx, x, y);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->vertexAttrib2f(indx, x, y);
 #endif
 }
glVertexAttrib2fv()
void QGLFunctions::glVertexAttrib2fv (GLuint indx, const GLfloat * values) inline
Convenience function that calls glVertexAttrib2fv(indx, values).
For more information, see the OpenGL/ES 2.0 documentation for glVertexAttrib2fv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1324 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glVertexAttrib2fv(indx, values);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->vertexAttrib2fv(indx, values);
 #endif
 }
glVertexAttrib3f()
void QGLFunctions::glVertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z) inline
Convenience function that calls glVertexAttrib3f(indx, x, y, z).
For more information, see the OpenGL/ES 2.0 documentation for glVertexAttrib3f().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1334 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glVertexAttrib3f(indx, x, y, z);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->vertexAttrib3f(indx, x, y, z);
 #endif
 }
glVertexAttrib3fv()
void QGLFunctions::glVertexAttrib3fv (GLuint indx, const GLfloat * values) inline
Convenience function that calls glVertexAttrib3fv(indx, values).
For more information, see the OpenGL/ES 2.0 documentation for glVertexAttrib3fv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1344 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glVertexAttrib3fv(indx, values);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->vertexAttrib3fv(indx, values);
 #endif
 }
glVertexAttrib4f()
void QGLFunctions::glVertexAttrib4f (GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w) inline
Convenience function that calls glVertexAttrib4f(indx, x, y, z, w).
For more information, see the OpenGL/ES 2.0 documentation for glVertexAttrib4f().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1354 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glVertexAttrib4f(indx, x, y, z, w);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->vertexAttrib4f(indx, x, y, z, w);
 #endif
 }
glVertexAttrib4fv()
void QGLFunctions::glVertexAttrib4fv (GLuint indx, const GLfloat * values) inline
Convenience function that calls glVertexAttrib4fv(indx, values).
For more information, see the OpenGL/ES 2.0 documentation for glVertexAttrib4fv().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1364 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glVertexAttrib4fv(indx, values);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->vertexAttrib4fv(indx, values);
 #endif
 }
glVertexAttribPointer()
void QGLFunctions::glVertexAttribPointer (GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void * ptr) inline
Convenience function that calls glVertexAttribPointer(indx, size, type, normalized, stride, ptr).
For more information, see the OpenGL/ES 2.0 documentation for glVertexAttribPointer().
This convenience function will do nothing on OpenGL/ES 1.x systems.
Definition at line 1374 of file qglfunctions.h.
 {
 #if defined(QT_OPENGL_ES_2)
     ::glVertexAttribPointer(indx, size, type, normalized, stride, ptr);
 #else
     Q_ASSERT(QGLFunctions::isInitialized(d_ptr));
     d_ptr->vertexAttribPointer(indx, size, type, normalized, stride, ptr);
 #endif
 }
hasOpenGLFeature()
bool QGLFunctions::hasOpenGLFeature (QGLFunctions::OpenGLFeature feature) const
Returns true if feature is present on this system's OpenGL implementation; false otherwise.
It is assumed that the QGLContext associated with this function resolver is current.
See also
openGLFeatures()
Definition at line 340 of file qglfunctions.cpp.
Referenced by QGL2PaintEngineExPrivate::updateBrushTexture().
 {
     QGLFunctionsPrivateEx *d = static_cast<QGLFunctionsPrivateEx *>(d_ptr);
     if (!d)
         return false;
     if (d->m_features == -1)
         d->m_features = qt_gl_resolve_features();
     return (d->m_features & int(feature)) != 0;
 }
initializeGLFunctions()
void QGLFunctions::initializeGLFunctions (const QGLContext * context = 0)
Initializes GL function resolution for context.
If context is null, then the current QGLContext will be used.
After calling this function, the QGLFunctions object can only be used with context and other contexts that share with it. Call initializeGLFunctions() again to change the object's context association.
Definition at line 359 of file qglfunctions.cpp.
 {
     d_ptr = qt_gl_functions(context);
 }
isInitialized()
static bool QGLFunctions::isInitialized (const QGLFunctionsPrivate * d) inline static private
Definition at line 308 of file qglfunctions.h.
Referenced by glActiveTexture(), glAttachShader(), glBindAttribLocation(), glBindBuffer(), glBindFramebuffer(), glBindRenderbuffer(), glBlendColor(), glBlendEquation(), glBlendEquationSeparate(), glBlendFuncSeparate(), glBufferData(), glBufferSubData(), glCheckFramebufferStatus(), glCompileShader(), glCompressedTexImage2D(), glCompressedTexSubImage2D(), glCreateProgram(), glCreateShader(), glDeleteBuffers(), glDeleteFramebuffers(), glDeleteProgram(), glDeleteRenderbuffers(), glDeleteShader(), glDetachShader(), glDisableVertexAttribArray(), glEnableVertexAttribArray(), glFramebufferRenderbuffer(), glFramebufferTexture2D(), glGenBuffers(), glGenerateMipmap(), glGenFramebuffers(), glGenRenderbuffers(), glGetActiveAttrib(), glGetActiveUniform(), glGetAttachedShaders(), glGetAttribLocation(), glGetBufferParameteriv(), glGetFramebufferAttachmentParameteriv(), glGetProgramInfoLog(), glGetProgramiv(), glGetRenderbufferParameteriv(), glGetShaderInfoLog(), glGetShaderiv(), glGetShaderPrecisionFormat(), glGetShaderSource(), glGetUniformfv(), glGetUniformiv(), glGetUniformLocation(), glGetVertexAttribfv(), glGetVertexAttribiv(), glGetVertexAttribPointerv(), glIsBuffer(), glIsFramebuffer(), glIsProgram(), glIsRenderbuffer(), glIsShader(), glLinkProgram(), glReleaseShaderCompiler(), glRenderbufferStorage(), glSampleCoverage(), glShaderBinary(), glShaderSource(), glStencilFuncSeparate(), glStencilMaskSeparate(), glStencilOpSeparate(), glUniform1f(), glUniform1fv(), glUniform1i(), glUniform1iv(), glUniform2f(), glUniform2fv(), glUniform2i(), glUniform2iv(), glUniform3f(), glUniform3fv(), glUniform3i(), glUniform3iv(), glUniform4f(), glUniform4fv(), glUniform4i(), glUniform4iv(), glUniformMatrix2fv(), glUniformMatrix3fv(), glUniformMatrix4fv(), glUseProgram(), glValidateProgram(), glVertexAttrib1f(), glVertexAttrib1fv(), glVertexAttrib2f(), glVertexAttrib2fv(), glVertexAttrib3f(), glVertexAttrib3fv(), glVertexAttrib4f(), glVertexAttrib4fv(), and glVertexAttribPointer().
 { return d != 0; }
openGLFeatures()
QGLFunctions::OpenGLFeatures QGLFunctions::openGLFeatures () const
Returns the set of features that are present on this system's OpenGL implementation.
It is assumed that the QGLContext associated with this function resolver is current.
See also
hasOpenGLFeature()
Definition at line 321 of file qglfunctions.cpp.
 {
     QGLFunctionsPrivateEx *d = static_cast<QGLFunctionsPrivateEx *>(d_ptr);
     if (!d)
         return 0;
     if (d->m_features == -1)
         d->m_features = qt_gl_resolve_features();
     return QGLFunctions::OpenGLFeatures(d->m_features);
 }
Properties
d_ptr
QGLFunctionsPrivate* QGLFunctions::d_ptr private
Definition at line 307 of file qglfunctions.h.
Referenced by hasOpenGLFeature(), initializeGLFunctions(), and openGLFeatures().
The documentation for this class was generated from the following files:
/src/opengl/qglfunctions.h
/src/opengl/qglfunctions.cpp