Qt 4.8: QBenchmarkMeasurerBase Class Reference
QBenchmarkMeasurerBase Class Reference abstract
#include <qbenchmarkmeasurement_p.h>
Public Functions
virtual int adjustIterationCount (int suggestion)=0
virtual int adjustMedianCount (int suggestion)=0
virtual qint64 checkpoint ()=0
virtual void init ()
virtual bool isMeasurementAccepted (qint64 measurement)=0
virtual QTest::QBenchmarkMetric metricType ()=0
virtual bool needsWarmupIteration ()
virtual bool repeatCount ()
virtual void start ()=0
virtual qint64 stop ()=0
virtual ~QBenchmarkMeasurerBase ()
Detailed Description
Definition at line 62 of file qbenchmarkmeasurement_p.h.
Constructors and Destructors
~QBenchmarkMeasurerBase()
virtual QBenchmarkMeasurerBase::~QBenchmarkMeasurerBase () inline virtual
Definition at line 65 of file qbenchmarkmeasurement_p.h.
 {};
Functions
adjustIterationCount()
virtual int QBenchmarkMeasurerBase::adjustIterationCount (int suggestion) pure virtual
Implemented in QBenchmarkTimeMeasurer, QBenchmarkCallgrindMeasurer, and QBenchmarkEvent.
Referenced by QBenchmarkTestMethodData::adjustIterationCount(), and init().
adjustMedianCount()
virtual int QBenchmarkMeasurerBase::adjustMedianCount (int suggestion) pure virtual
Implemented in QBenchmarkTimeMeasurer, QBenchmarkCallgrindMeasurer, and QBenchmarkEvent.
Referenced by QBenchmarkGlobalData::adjustMedianIterationCount(), and init().
checkpoint()
virtual qint64 QBenchmarkMeasurerBase::checkpoint () pure virtual
Implemented in QBenchmarkTimeMeasurer, QBenchmarkCallgrindMeasurer, and QBenchmarkEvent.
Referenced by init().
init()
virtual void QBenchmarkMeasurerBase::init () inline virtual
Definition at line 66 of file qbenchmarkmeasurement_p.h.
Referenced by QBenchmarkGlobalData::createMeasurer().
 {};
isMeasurementAccepted()
virtual bool QBenchmarkMeasurerBase::isMeasurementAccepted (qint64 measurement) pure virtual
Implemented in QBenchmarkTimeMeasurer, QBenchmarkCallgrindMeasurer, and QBenchmarkEvent.
Referenced by init(), and QBenchmarkTestMethodData::setResult().
metricType()
virtual QTest::QBenchmarkMetric QBenchmarkMeasurerBase::metricType () pure virtual
Implemented in QBenchmarkTimeMeasurer, QBenchmarkCallgrindMeasurer, and QBenchmarkEvent.
Referenced by needsWarmupIteration().
needsWarmupIteration()
virtual bool QBenchmarkMeasurerBase::needsWarmupIteration () inline virtual
Reimplemented in QBenchmarkTimeMeasurer, and QBenchmarkCallgrindMeasurer.
Definition at line 74 of file qbenchmarkmeasurement_p.h.
Referenced by QTest::qInvokeTestMethodDataEntry().
 { return false; }
repeatCount()
virtual bool QBenchmarkMeasurerBase::repeatCount () inline virtual
Reimplemented in QBenchmarkEvent.
Definition at line 73 of file qbenchmarkmeasurement_p.h.
 { return 1; }
start()
virtual void QBenchmarkMeasurerBase::start () pure virtual
Implemented in QBenchmarkTimeMeasurer, QBenchmarkCallgrindMeasurer, and QBenchmarkEvent.
Referenced by QTest::beginBenchmarkMeasurement(), and init().
stop()
virtual qint64 QBenchmarkMeasurerBase::stop () pure virtual
Implemented in QBenchmarkTimeMeasurer, QBenchmarkCallgrindMeasurer, and QBenchmarkEvent.
Referenced by QTest::endBenchmarkMeasurement(), and init().
The documentation for this class was generated from the following file:
/src/testlib/qbenchmarkmeasurement_p.h