Qt 4.8: QGraphicsItemAnimation Class Reference
QGraphicsItemAnimation Class Reference
The QGraphicsItemAnimation class provides simple animation support for QGraphicsItem.
#include <qgraphicsitemanimation.h>
Public Slots
void reset ()
Resets the item to its starting position and transformation.
void setStep (qreal x)
Sets the current step value for the animation, causing the transformations scheduled at this step to be performed.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
void clear ()
Clears the scheduled transformations used for the animation, but retains the item and timeline.
qreal horizontalScaleAt (qreal step) const
Returns the horizontal scale for the item at the specified step value.
qreal horizontalShearAt (qreal step) const
Returns the horizontal shear for the item at the specified step value.
QGraphicsItem * item () const
Returns the item on which the animation object operates.
QMatrix matrixAt (qreal step) const
Returns the matrix used to transform the item at the specified step value.
QPointF posAt (qreal step) const
Returns the position of the item at the given step value.
QList< QPair< qreal, QPointF > > posList () const
Returns all explicitly inserted positions.
QGraphicsItemAnimation (QObject *parent=0)
Constructs an animation object with the given parent.
qreal rotationAt (qreal step) const
Returns the angle at which the item is rotated at the specified step value.
QList< QPair< qreal, qreal > > rotationList () const
Returns all explicitly inserted rotations.
QList< QPair< qreal, QPointF > > scaleList () const
Returns all explicitly inserted scales.
void setItem (QGraphicsItem *item)
Sets the specified item to be used in the animation.
void setPosAt (qreal step, const QPointF &pos)
Sets the position of the item at the given step value to the point specified.
void setRotationAt (qreal step, qreal angle)
Sets the rotation of the item at the given step value to the angle specified.
void setScaleAt (qreal step, qreal sx, qreal sy)
Sets the scale of the item at the given step value using the horizontal and vertical scale factors specified by sx and sy.
void setShearAt (qreal step, qreal sh, qreal sv)
Sets the shear of the item at the given step value using the horizontal and vertical shear factors specified by sh and sv.
void setTimeLine (QTimeLine *timeLine)
Sets the timeline object used to control the rate of animation to the timeLine specified.
void setTranslationAt (qreal step, qreal dx, qreal dy)
Sets the translation of the item at the given step value using the horizontal and vertical coordinates specified by dx and dy.
QList< QPair< qreal, QPointF > > shearList () const
Returns all explicitly inserted shears.
QTimeLine * timeLine () const
Returns the timeline object used to control the rate at which the animation occurs.
QList< QPair< qreal, QPointF > > translationList () const
Returns all explicitly inserted translations.
qreal verticalScaleAt (qreal step) const
Returns the vertical scale for the item at the specified step value.
qreal verticalShearAt (qreal step) const
Returns the vertical shear for the item at the specified step value.
qreal xTranslationAt (qreal step) const
Returns the horizontal translation of the item at the specified step value.
qreal yTranslationAt (qreal step) const
Returns the vertical translation of the item at the specified step value.
virtual ~QGraphicsItemAnimation ()
Destroys the animation object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual void afterAnimationStep (qreal step)
This method is meant to be overridden in subclasses that need to execute additional code after a new step has taken place.
virtual void beforeAnimationStep (qreal step)
This method is meant to be overridden by subclassed that needs to execute additional code before a new step takes place.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
QGraphicsItemAnimationPrivate * d
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGraphicsItemAnimation class provides simple animation support for QGraphicsItem.
Since
4.2
The QGraphicsItemAnimation class animates a QGraphicsItem. You can schedule changes to the item's transformation matrix at specified steps. The QGraphicsItemAnimation class has a current step value. When this value changes the transformations scheduled at that step are performed. The current step of the animation is set with the setStep() function.
QGraphicsItemAnimation will do a simple linear interpolation between the nearest adjacent scheduled changes to calculate the matrix. For instance, if you set the position of an item at values 0.0 and 1.0, the animation will show the item moving in a straight line between these positions. The same is true for scaling and rotation.
It is usual to use the class with a QTimeLine. The timeline's QTimeLine::valueChanged() signal is then connected to the setStep() slot. For example, you can set up an item for rotation by calling setRotationAt() for different step values. The animations timeline is set with the setTimeLine() function.
An example animation with a timeline follows:
    QGraphicsItem *ball = new QGraphicsEllipseItem(0, 0, 20, 20);
    QTimeLine *timer = new QTimeLine(5000);
    timer->setFrameRange(0, 100);
    QGraphicsItemAnimation *animation = new QGraphicsItemAnimation;
    animation->setItem(ball);
    animation->setTimeLine(timer);
    for (int i = 0; i < 200; ++i)
    animation->setPosAt(i / 200.0, QPointF(i, i));
    QGraphicsScene *scene = new QGraphicsScene();
    scene->setSceneRect(0, 0, 250, 250);
    scene->addItem(ball);
    QGraphicsView *view = new QGraphicsView(scene);
    view->show();
    timer->start();
Note that steps lie between 0.0 and 1.0. It may be necessary to use QTimeLine::setUpdateInterval(). The default update interval is 40 ms. A scheduled transformation cannot be removed when set, so scheduling several transformations of the same kind (e.g., rotations) at the same step is not recommended.
See also
QTimeLine, {Graphics View Framework}
Definition at line 62 of file qgraphicsitemanimation.h.
Constructors and Destructors
QGraphicsItemAnimation()
QGraphicsItemAnimation::QGraphicsItemAnimation (QObject * parent = 0)
Constructs an animation object with the given parent.
Definition at line 191 of file qgraphicsitemanimation.cpp.
     : QObject(parent), d(new QGraphicsItemAnimationPrivate)
 {
     d->q = this;
 }
~QGraphicsItemAnimation()
QGraphicsItemAnimation::~QGraphicsItemAnimation () virtual
Destroys the animation object.
Definition at line 200 of file qgraphicsitemanimation.cpp.
 {
     delete d;
 }
Functions
afterAnimationStep()
void QGraphicsItemAnimation::afterAnimationStep (qreal step) protected virtual
This method is meant to be overridden in subclasses that need to execute additional code after a new step has taken place.
The animation step is provided for use in cases where the action depends on its value.
Definition at line 607 of file qgraphicsitemanimation.cpp.
Referenced by setStep().
 {
     Q_UNUSED(step);
 }
beforeAnimationStep()
void QGraphicsItemAnimation::beforeAnimationStep (qreal step) protected virtual
This method is meant to be overridden by subclassed that needs to execute additional code before a new step takes place.
The animation step is provided for use in cases where the action depends on its value.
Definition at line 591 of file qgraphicsitemanimation.cpp.
Referenced by setStep().
 {
     Q_UNUSED(step);
 }
clear()
void QGraphicsItemAnimation::clear ()
Clears the scheduled transformations used for the animation, but retains the item and timeline.
Definition at line 516 of file qgraphicsitemanimation.cpp.
 {
     d->xPosition.clear();
     d->yPosition.clear();
     d->rotation.clear();
     d->verticalScale.clear();
     d->horizontalScale.clear();
     d->verticalShear.clear();
     d->horizontalShear.clear();
     d->xTranslation.clear();
     d->yTranslation.clear();
 }
horizontalScaleAt()
qreal QGraphicsItemAnimation::horizontalScaleAt (qreal step) const
Returns the horizontal scale for the item at the specified step value.
See also
setScaleAt()
Definition at line 426 of file qgraphicsitemanimation.cpp.
Referenced by matrixAt().
 {
     if (step < 0.0 || step > 1.0)
         qWarning("QGraphicsItemAnimation::horizontalScaleAt: invalid step = %f", step);
     return d->linearValueForStep(step, &d->horizontalScale, 1);
 }
horizontalShearAt()
qreal QGraphicsItemAnimation::horizontalShearAt (qreal step) const
Returns the horizontal shear for the item at the specified step value.
See also
setShearAt()
Definition at line 478 of file qgraphicsitemanimation.cpp.
Referenced by matrixAt().
 {
     if (step < 0.0 || step > 1.0)
         qWarning("QGraphicsItemAnimation::horizontalShearAt: invalid step = %f", step);
     return d->linearValueForStep(step, &d->horizontalShear, 0);
 }
item()
QGraphicsItem * QGraphicsItemAnimation::item () const
Returns the item on which the animation object operates.
See also
setItem()
Definition at line 210 of file qgraphicsitemanimation.cpp.
Referenced by setItem().
 {
     return d->item;
 }
matrixAt()
QMatrix QGraphicsItemAnimation::matrixAt (qreal step) const
Returns the matrix used to transform the item at the specified step value.
Definition at line 302 of file qgraphicsitemanimation.cpp.
Referenced by setStep().
 {
     if (step < 0.0 || step > 1.0)
         qWarning("QGraphicsItemAnimation::matrixAt: invalid step = %f", step);
     QMatrix matrix;
     if (!d->rotation.isEmpty())
         matrix.rotate(rotationAt(step));
     if (!d->verticalScale.isEmpty())
         matrix.scale(horizontalScaleAt(step), verticalScaleAt(step));
     if (!d->verticalShear.isEmpty())
         matrix.shear(horizontalShearAt(step), verticalShearAt(step));
     if (!d->xTranslation.isEmpty())
         matrix.translate(xTranslationAt(step), yTranslationAt(step));
     return matrix;
 }
posAt()
QPointF QGraphicsItemAnimation::posAt (qreal step) const
Returns the position of the item at the given step value.
See also
setPosAt()
Definition at line 260 of file qgraphicsitemanimation.cpp.
Referenced by setStep().
 {
     if (step < 0.0 || step > 1.0)
         qWarning("QGraphicsItemAnimation::posAt: invalid step = %f", step);
     return QPointF(d->linearValueForStep(step, &d->xPosition, d->startPos.x()),
                    d->linearValueForStep(step, &d->yPosition, d->startPos.y()));
 }
posList()
QList< QPair< qreal, QPointF > > QGraphicsItemAnimation::posList () const
Returns all explicitly inserted positions.
See also
posAt(), setPosAt()
Definition at line 290 of file qgraphicsitemanimation.cpp.
 {
     QList<QPair<qreal, QPointF> > list;
     for (int i = 0; i < d->xPosition.size(); ++i)
         list << QPair<qreal, QPointF>(d->xPosition.at(i).step, QPointF(d->xPosition.at(i).value, d->yPosition.at(i).value));
     return list;
 }
reset
void QGraphicsItemAnimation::reset () slot
Resets the item to its starting position and transformation.
You can call setStep(0) instead.
Definition at line 572 of file qgraphicsitemanimation.cpp.
 {
     if (!d->item)
         return;
     d->startPos = d->item->pos();
     d->startMatrix = d->item->matrix();
 }
rotationAt()
qreal QGraphicsItemAnimation::rotationAt (qreal step) const
Returns the angle at which the item is rotated at the specified step value.
See also
setRotationAt()
Definition at line 324 of file qgraphicsitemanimation.cpp.
Referenced by matrixAt().
 {
     if (step < 0.0 || step > 1.0)
         qWarning("QGraphicsItemAnimation::rotationAt: invalid step = %f", step);
     return d->linearValueForStep(step, &d->rotation);
 }
rotationList()
QList< QPair< qreal, qreal > > QGraphicsItemAnimation::rotationList () const
Returns all explicitly inserted rotations.
See also
rotationAt(), setRotationAt()
Definition at line 347 of file qgraphicsitemanimation.cpp.
 {
     QList<QPair<qreal, qreal> > list;
     for (int i = 0; i < d->rotation.size(); ++i)
         list << QPair<qreal, qreal>(d->rotation.at(i).step, d->rotation.at(i).value);
     return list;
 }
scaleList()
QList< QPair< qreal, QPointF > > QGraphicsItemAnimation::scaleList () const
Returns all explicitly inserted scales.
See also
verticalScaleAt(), horizontalScaleAt(), setScaleAt()
Definition at line 451 of file qgraphicsitemanimation.cpp.
 {
     QList<QPair<qreal, QPointF> > list;
     for (int i = 0; i < d->horizontalScale.size(); ++i)
         list << QPair<qreal, QPointF>(d->horizontalScale.at(i).step, QPointF(d->horizontalScale.at(i).value, d->verticalScale.at(i).value));
     return list;
 }
setItem()
void QGraphicsItemAnimation::setItem (QGraphicsItem * item)
Sets the specified item to be used in the animation.
See also
item()
Definition at line 220 of file qgraphicsitemanimation.cpp.
 {
     d->item = item;
     d->startPos = d->item->pos();
 }
setPosAt()
void QGraphicsItemAnimation::setPosAt (qreal step, const QPointF & point)
Sets the position of the item at the given step value to the point specified.
See also
posAt()
Definition at line 279 of file qgraphicsitemanimation.cpp.
 {
     d->insertUniquePair(step, pos.x(), &d->xPosition, "setPosAt");
     d->insertUniquePair(step, pos.y(), &d->yPosition, "setPosAt");
 }
setRotationAt()
void QGraphicsItemAnimation::setRotationAt (qreal step, qreal angle)
Sets the rotation of the item at the given step value to the angle specified.
See also
rotationAt()
Definition at line 337 of file qgraphicsitemanimation.cpp.
 {
     d->insertUniquePair(step, angle, &d->rotation, "setRotationAt");
 }
setScaleAt()
void QGraphicsItemAnimation::setScaleAt (qreal step, qreal sx, qreal sy)
Sets the scale of the item at the given step value using the horizontal and vertical scale factors specified by sx and sy.
See also
verticalScaleAt(), horizontalScaleAt()
Definition at line 440 of file qgraphicsitemanimation.cpp.
 {
     d->insertUniquePair(step, sx, &d->horizontalScale, "setScaleAt");
     d->insertUniquePair(step, sy, &d->verticalScale, "setScaleAt");
 }
setShearAt()
void QGraphicsItemAnimation::setShearAt (qreal step, qreal sh, qreal sv)
Sets the shear of the item at the given step value using the horizontal and vertical shear factors specified by sh and sv.
See also
verticalShearAt(), horizontalShearAt()
Definition at line 492 of file qgraphicsitemanimation.cpp.
 {
     d->insertUniquePair(step, sh, &d->horizontalShear, "setShearAt");
     d->insertUniquePair(step, sv, &d->verticalShear, "setShearAt");
 }
setStep
void QGraphicsItemAnimation::setStep (qreal x) slot
Sets the current step value for the animation, causing the transformations scheduled at this step to be performed.
Definition at line 538 of file qgraphicsitemanimation.cpp.
Referenced by setTimeLine().
 {
     if (x < 0.0 || x > 1.0) {
         qWarning("QGraphicsItemAnimation::setStep: invalid step = %f", x);
         return;
     }
     beforeAnimationStep(x);
     d->step = x;
     if (d->item) {
         if (!d->xPosition.isEmpty() || !d->yPosition.isEmpty())
             d->item->setPos(posAt(x));
         if (!d->rotation.isEmpty()
             || !d->verticalScale.isEmpty()
             || !d->horizontalScale.isEmpty()
             || !d->verticalShear.isEmpty()
             || !d->horizontalShear.isEmpty()
             || !d->xTranslation.isEmpty()
             || !d->yTranslation.isEmpty()) {
             d->item->setMatrix(d->startMatrix * matrixAt(x));
         }
     }
     afterAnimationStep(x);
 }
setTimeLine()
void QGraphicsItemAnimation::setTimeLine (QTimeLine * timeLine)
Sets the timeline object used to control the rate of animation to the timeLine specified.
See also
timeLine()
Definition at line 243 of file qgraphicsitemanimation.cpp.
 {
     if (d->timeLine == timeLine)
         return;
     if (d->timeLine)
         delete d->timeLine;
     if (!timeLine)
         return;
     d->timeLine = timeLine;
     connect(timeLine, SIGNAL(valueChanged(qreal)), this, SLOT(setStep(qreal)));
 }
setTranslationAt()
void QGraphicsItemAnimation::setTranslationAt (qreal step, qreal dx, qreal dy)
Sets the translation of the item at the given step value using the horizontal and vertical coordinates specified by dx and dy.
See also
xTranslationAt(), yTranslationAt()
Definition at line 388 of file qgraphicsitemanimation.cpp.
 {
     d->insertUniquePair(step, dx, &d->xTranslation, "setTranslationAt");
     d->insertUniquePair(step, dy, &d->yTranslation, "setTranslationAt");
 }
shearList()
QList< QPair< qreal, QPointF > > QGraphicsItemAnimation::shearList () const
Returns all explicitly inserted shears.
See also
verticalShearAt(), horizontalShearAt(), setShearAt()
Definition at line 503 of file qgraphicsitemanimation.cpp.
 {
     QList<QPair<qreal, QPointF> > list;
     for (int i = 0; i < d->horizontalShear.size(); ++i)
         list << QPair<qreal, QPointF>(d->horizontalShear.at(i).step, QPointF(d->horizontalShear.at(i).value, d->verticalShear.at(i).value));
     return list;
 }
timeLine()
QTimeLine * QGraphicsItemAnimation::timeLine () const
Returns the timeline object used to control the rate at which the animation occurs.
See also
setTimeLine()
Definition at line 232 of file qgraphicsitemanimation.cpp.
Referenced by setTimeLine().
 {
     return d->timeLine;
 }
translationList()
QList< QPair< qreal, QPointF > > QGraphicsItemAnimation::translationList () const
Returns all explicitly inserted translations.
See also
xTranslationAt(), yTranslationAt(), setTranslationAt()
Definition at line 399 of file qgraphicsitemanimation.cpp.
 {
     QList<QPair<qreal, QPointF> > list;
     for (int i = 0; i < d->xTranslation.size(); ++i)
         list << QPair<qreal, QPointF>(d->xTranslation.at(i).step, QPointF(d->xTranslation.at(i).value, d->yTranslation.at(i).value));
     return list;
 }
verticalScaleAt()
qreal QGraphicsItemAnimation::verticalScaleAt (qreal step) const
Returns the vertical scale for the item at the specified step value.
See also
setScaleAt()
Definition at line 413 of file qgraphicsitemanimation.cpp.
Referenced by matrixAt().
 {
     if (step < 0.0 || step > 1.0)
         qWarning("QGraphicsItemAnimation::verticalScaleAt: invalid step = %f", step);
     return d->linearValueForStep(step, &d->verticalScale, 1);
 }
verticalShearAt()
qreal QGraphicsItemAnimation::verticalShearAt (qreal step) const
Returns the vertical shear for the item at the specified step value.
See also
setShearAt()
Definition at line 465 of file qgraphicsitemanimation.cpp.
Referenced by matrixAt().
 {
     if (step < 0.0 || step > 1.0)
         qWarning("QGraphicsItemAnimation::verticalShearAt: invalid step = %f", step);
     return d->linearValueForStep(step, &d->verticalShear, 0);
 }
xTranslationAt()
qreal QGraphicsItemAnimation::xTranslationAt (qreal step) const
Returns the horizontal translation of the item at the specified step value.
See also
setTranslationAt()
Definition at line 361 of file qgraphicsitemanimation.cpp.
Referenced by matrixAt().
 {
     if (step < 0.0 || step > 1.0)
         qWarning("QGraphicsItemAnimation::xTranslationAt: invalid step = %f", step);
     return d->linearValueForStep(step, &d->xTranslation);
 }
yTranslationAt()
qreal QGraphicsItemAnimation::yTranslationAt (qreal step) const
Returns the vertical translation of the item at the specified step value.
See also
setTranslationAt()
Definition at line 374 of file qgraphicsitemanimation.cpp.
Referenced by matrixAt().
 {
     if (step < 0.0 || step > 1.0)
         qWarning("QGraphicsItemAnimation::yTranslationAt: invalid step = %f", step);
     return d->linearValueForStep(step, &d->yTranslation);
 }
Properties
d
QGraphicsItemAnimationPrivate* QGraphicsItemAnimation::d private
Definition at line 112 of file qgraphicsitemanimation.h.
Referenced by clear(), horizontalScaleAt(), horizontalShearAt(), item(), matrixAt(), posAt(), posList(), QGraphicsItemAnimation(), reset(), rotationAt(), rotationList(), scaleList(), setItem(), setPosAt(), setRotationAt(), setScaleAt(), setShearAt(), setStep(), setTimeLine(), setTranslationAt(), shearList(), timeLine(), translationList(), verticalScaleAt(), verticalShearAt(), xTranslationAt(), yTranslationAt(), and ~QGraphicsItemAnimation().
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicsitemanimation.h
/src/gui/graphicsview/qgraphicsitemanimation.cpp