Qt 4.8: QWorkspace Class Reference
QWorkspace Class Reference
The QWorkspace widget provides a workspace window that can be used in an MDI application.
#include <qworkspace.h>
Public Types
enum WindowOrder { CreationOrder, StackingOrder }
Specifies the order in which child windows are returned from windowList().
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void activateNextWindow ()
Gives the input focus to the next window in the list of child windows.
void activatePreviousWindow ()
Gives the input focus to the previous window in the list of child windows.
void arrangeIcons ()
Arranges all iconified windows at the bottom of the workspace.
void cascade ()
Arranges all the child windows in a cascade pattern.
void closeActiveWindow ()
Closes the child window that is currently active.
void closeAllWindows ()
Closes all child windows.
void setActiveWindow (QWidget *w)
Makes the child window that contains w the active child window.
void tile ()
Arranges all child windows in a tile pattern.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void windowActivated (QWidget *w)
This signal is emitted when the child window w becomes active.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QWidget * activeWindow () const
Returns a pointer to the widget corresponding to the active child window, or 0 if no window is active.
QWidget * addWindow (QWidget *w, Qt::WindowFlags flags=0)
Adds widget w as new sub window to the workspace.
QBrush background () const
QWorkspace (QWidget *parent=0)
Constructs a workspace with the given parent.
bool scrollBarsEnabled () const
void setBackground (const QBrush &background)
void setScrollBarsEnabled (bool enable)
QSize sizeHint () const
Reimplemented Function
QWidgetList windowList (WindowOrder order=CreationOrder) const
Returns a list of all visible or minimized child windows.
~QWorkspace ()
Destroys the workspace and frees any allocated resources.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
virtual QSize minimumSizeHint () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *)
Reimplemented Function
void childEvent (QChildEvent *)
Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
bool eventFilter (QObject *, QEvent *)
Reimplemented Function
void hideEvent (QHideEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *e)
Reimplemented Function
void resizeEvent (QResizeEvent *)
Reimplemented Function
void showEvent (QShowEvent *e)
Reimplemented Function
void wheelEvent (QWheelEvent *e)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyPressEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key press events for the widget.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
QBrush background
the workspace's background
bool scrollBarsEnabled
whether the workspace provides scroll bars
Friends
class QWorkspaceChild
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QWorkspace widget provides a workspace window that can be used in an MDI application.
This class is deprecated. Use QMdiArea instead.
Multiple Document Interface (MDI) applications are typically composed of a main window containing a menu bar, a toolbar, and a central QWorkspace widget. The workspace itself is used to display a number of child windows, each of which is a widget.
The workspace itself is an ordinary Qt widget. It has a standard constructor that takes a parent widget. Workspaces can be placed in any layout, but are typically given as the central widget in a QMainWindow:
MainWindow::MainWindow()
{
    workspace = new QWorkspace;
    setCentralWidget(workspace);
    ...
}
Child windows (MDI windows) are standard Qt widgets that are inserted into the workspace with addWindow(). As with top-level widgets, you can call functions such as show(), hide(), showMaximized(), and setWindowTitle() on a child window to change its appearance within the workspace. You can also provide widget flags to determine the layout of the decoration or the behavior of the widget itself.
To change or retrieve the geometry of a child window, you must operate on its parentWidget(). The parentWidget() provides access to the decorated frame that contains the child window widget. When a child window is maximised, its decorated frame is hidden. If the top-level widget contains a menu bar, it will display the maximised window's operations menu to the left of the menu entries, and the window's controls to the right.
A child window becomes active when it gets the keyboard focus, or when setFocus() is called. The user can activate a window by moving focus in the usual ways, for example by clicking a window or by pressing Tab. The workspace emits a signal windowActivated() when the active window changes, and the function activeWindow() returns a pointer to the active child window, or 0 if no window is active.
The convenience function windowList() returns a list of all child windows. This information could be used in a popup menu containing a list of windows, for example. This feature is also available as part of the Window Menu Solution.
QWorkspace provides two built-in layout strategies for child windows: cascade() and tile(). Both are slots so you can easily connect menu entries to them.
If you want your users to be able to work with child windows larger than the visible workspace area, set the scrollBarsEnabled property to true.
See also
QDockWidget, {MDI Example}
Definition at line 60 of file qworkspace.h.
Enumerations
WindowOrder
enum QWorkspace::WindowOrder
Specifies the order in which child windows are returned from windowList().
CreationOrder The windows are returned in the order of their creation
StackingOrder The windows are returned in the order of their stacking
Enumerator
CreationOrder
StackingOrder
Definition at line 70 of file qworkspace.h.
 { CreationOrder, StackingOrder };
Constructors and Destructors
QWorkspace()
QWorkspace::QWorkspace (QWidget * parent = 0) explicit
Constructs a workspace with the given parent.
Definition at line 1050 of file qworkspace.cpp.
     : QWidget(*new QWorkspacePrivate, parent, 0)
 {
     Q_D(QWorkspace);
     d->init();
 }
~QWorkspace()
QWorkspace::~QWorkspace ()
Destroys the workspace and frees any allocated resources.
Definition at line 1165 of file qworkspace.cpp.
 {
 }
Functions
activateNextWindow
void QWorkspace::activateNextWindow () slot
Gives the input focus to the next window in the list of child windows.
See also
activatePreviousWindow()
Definition at line 2240 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     if (d->focus.isEmpty())
         return;
     if (!d->active) {
         if (d->focus.first())
             d->activateWindow(d->focus.first()->windowWidget(), false);
         return;
     }
     int a = d->focus.indexOf(d->active) + 1;
     a = a % d->focus.count();
     if (d->focus.at(a))
         d->activateWindow(d->focus.at(a)->windowWidget(), false);
     else
         d->activateWindow(0);
 }
activatePreviousWindow
void QWorkspace::activatePreviousWindow () slot
Gives the input focus to the previous window in the list of child windows.
See also
activateNextWindow()
Definition at line 2268 of file qworkspace.cpp.
Referenced by QWorkspaceChild::~QWorkspaceChild().
 {
     Q_D(QWorkspace);
     if (d->focus.isEmpty())
         return;
     if (!d->active) {
         if (d->focus.last())
             d->activateWindow(d->focus.first()->windowWidget(), false);
         else
             d->activateWindow(0);
         return;
     }
     int a = d->focus.indexOf(d->active) - 1;
     if (a < 0)
         a = d->focus.count()-1;
     if (d->focus.at(a))
         d->activateWindow(d->focus.at(a)->windowWidget(), false);
     else
         d->activateWindow(0);
 }
activeWindow()
QWidget * QWorkspace::activeWindow () const
Returns a pointer to the widget corresponding to the active child window, or 0 if no window is active.
See also
setActiveWindow()
Definition at line 1382 of file qworkspace.cpp.
Referenced by QAccessibleWorkspace::state().
 {
     Q_D(const QWorkspace);
     return d->active? d->active->windowWidget() : 0;
 }
addWindow()
QWidget * QWorkspace::addWindow (QWidget * w, Qt::WindowFlags flags = 0)
Adds widget w as new sub window to the workspace.
If flags are non-zero, they will override the flags set on the widget.
Returns the widget used for the window frame.
To remove the widget w from the workspace, simply call setParent() with the new parent (or 0 to make it a stand-alone window).
Definition at line 1230 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     if (!w)
         return 0;
     w->setAutoFillBackground(true);
     QWidgetPrivate::adjustFlags(flags);
 #if 0
     bool wasMaximized = w->isMaximized();
     bool wasMinimized = w->isMinimized();
 #endif
     bool hasSize = w->testAttribute(Qt::WA_Resized);
     int x = w->x();
     int y = w->y();
     bool hasPos = w->testAttribute(Qt::WA_Moved);
     if (!hasSize && w->sizeHint().isValid())
         w->adjustSize();
     QWorkspaceChild* child = new QWorkspaceChild(w, this, flags);
     child->setObjectName(QLatin1String("qt_workspacechild"));
     child->installEventFilter(this);
     connect(child, SIGNAL(popupOperationMenu(QPoint)),
             this, SLOT(_q_popupOperationMenu(QPoint)));
     connect(child, SIGNAL(showOperationMenu()),
             this, SLOT(_q_showOperationMenu()));
     d->windows.append(child);
     if (child->isVisibleTo(this))
         d->focus.append(child);
     child->internalRaise();
     if (!hasPos)
         d->place(child);
     if (!hasSize)
         child->adjustSize();
     if (hasPos)
         child->move(x, y);
     return child;
 #if 0
     if (wasMaximized)
         w->showMaximized();
     else if (wasMinimized)
         w->showMinimized();
     else if (!hasBeenHidden)
         d->activateWindow(w);
     d->updateWorkspace();
     return child;
 #endif
 }
arrangeIcons
void QWorkspace::arrangeIcons () slot
Arranges all iconified windows at the bottom of the workspace.
See also
cascade(), tile()
Definition at line 2486 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     QRect cr = d->updateWorkspace();
     int x = 0;
     int y = -1;
     QList<QWidget *>::Iterator it(d->icons.begin());
     while (it != d->icons.end()) {
         QWidget* i = *it;
         if (y == -1)
             y = cr.height() - i->height();
         if (x > 0 && x + i->width() > cr.width()) {
             x = 0;
             y -= i->height();
         }
         i->move(x, y);
         x += i->width();
         ++it;
     }
     d->updateWorkspace();
 }
background()
QBrush QWorkspace::background () const
Referenced by setBackground(), and sizeHint().
cascade
void QWorkspace::cascade () slot
Arranges all the child windows in a cascade pattern.
See also
tile(), arrangeIcons()
Definition at line 2308 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     blockSignals(true);
     if  (d->maxWindow)
         d->maxWindow->showNormal();
     if (d->vbar) {
         d->vbar->blockSignals(true);
         d->vbar->setValue(0);
         d->vbar->blockSignals(false);
         d->hbar->blockSignals(true);
         d->hbar->setValue(0);
         d->hbar->blockSignals(false);
         d->_q_scrollBarChanged();
     }
     const int xoffset = 13;
     const int yoffset = 20;
     // make a list of all relevant mdi clients
     QList<QWorkspaceChild *> widgets;
     QList<QWorkspaceChild *>::Iterator it(d->windows.begin());
     QWorkspaceChild* wc = 0;
     for (it = d->focus.begin(); it != d->focus.end(); ++it) {
         wc = *it;
         if (wc->windowWidget()->isVisibleTo(this) && !(wc->titlebar && wc->titlebar->isTool()))
             widgets.append(wc);
     }
     int x = 0;
     int y = 0;
     it = widgets.begin();
     while (it != widgets.end()) {
         QWorkspaceChild *child = *it;
         ++it;
         QSize prefSize = child->windowWidget()->sizeHint().expandedTo(qSmartMinSize(child->windowWidget()));
         if (!prefSize.isValid())
             prefSize = child->windowWidget()->size();
         prefSize = prefSize.expandedTo(qSmartMinSize(child->windowWidget()));
         if (prefSize.isValid())
             prefSize += QSize(child->baseSize().width(), child->baseSize().height());
         int w = prefSize.width();
         int h = prefSize.height();
         child->showNormal();
         if (y + h > height())
             y = 0;
         if (x + w > width())
             x = 0;
         child->setGeometry(x, y, w, h);
         x += xoffset;
         y += yoffset;
         child->internalRaise();
     }
     d->updateWorkspace();
     blockSignals(false);
 }
changeEvent()
void QWorkspace::changeEvent (QEvent * ev) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3368 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     if(ev->type() == QEvent::StyleChange) {
         if (isVisible() && d->maxWindow && d->maxmenubar) {
             if(style()->styleHint(QStyle::SH_Workspace_FillSpaceOnMaximize, 0, this)) {
                 d->hideMaximizeControls(); //hide any visible maximized controls
                 d->showMaximizeControls(); //updates the modification state as well
             }
         }
     }
     QWidget::changeEvent(ev);
 }
childEvent()
void QWorkspace::childEvent (QChildEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 1287 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     if (e->removed()) {
         if (d->windows.removeAll(static_cast<QWorkspaceChild*>(e->child()))) {
             d->focus.removeAll(static_cast<QWorkspaceChild*>(e->child()));
             if (d->maxWindow == e->child())
                 d->maxWindow = 0;
             d->updateWorkspace();
         }
     }
 }
closeActiveWindow
void QWorkspace::closeActiveWindow () slot
Closes the child window that is currently active.
See also
closeAllWindows()
Definition at line 2055 of file qworkspace.cpp.
Referenced by eventFilter(), QWorkspacePrivate::init(), and QWorkspacePrivate::showMaximizeControls().
 {
     Q_D(QWorkspace);
     if (d->maxWindow && d->maxWindow->windowWidget())
         d->maxWindow->windowWidget()->close();
     else if (d->active && d->active->windowWidget())
         d->active->windowWidget()->close();
     d->updateWorkspace();
 }
closeAllWindows
void QWorkspace::closeAllWindows () slot
Closes all child windows.
If any child window fails to accept the close event, the remaining windows will remain open.
See also
closeActiveWindow()
Definition at line 2073 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     bool did_close = true;
     QList<QWorkspaceChild *>::const_iterator it = d->windows.constBegin();
     while (it != d->windows.constEnd() && did_close) {
         QWorkspaceChild *c = *it;
         ++it;
         if (c->windowWidget() && !c->windowWidget()->isHidden())
             did_close = c->windowWidget()->close();
     }
 }
event()
bool QWorkspace::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1826 of file qworkspace.cpp.
 {
 #ifndef QT_NO_SHORTCUT
     Q_D(QWorkspace);
     if (e->type() == QEvent::Shortcut) {
         QShortcutEvent *se = static_cast<QShortcutEvent *>(e);
         const char *theSlot = d->shortcutMap.value(se->shortcutId(), 0);
         if (theSlot)
             QMetaObject::invokeMethod(this, theSlot);
     } else
 #endif
     if (e->type() == QEvent::FocusIn || e->type() == QEvent::FocusOut){
         return true;
     }
     return QWidget::event(e);
 }
eventFilter()
bool QWorkspace::eventFilter (QObject * o, QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 1844 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     static QElapsedTimer* t = 0;
     static QWorkspace* tc = 0;
     if (o == d->maxtools) {
         switch (e->type()) {
         case QEvent::MouseButtonPress:
             {
                 QMenuBar* b = (QMenuBar*)o->parent();
                 if (!t)
                     t = new QElapsedTimer;
                 if (tc != this || t->elapsed() > QApplication::doubleClickInterval()) {
                     if (isRightToLeft()) {
                         QPoint p = b->mapToGlobal(QPoint(b->x() + b->width(), b->y() + b->height()));
                         p.rx() -= d->popup->sizeHint().width();
                         d->_q_popupOperationMenu(p);
                     } else {
                         d->_q_popupOperationMenu(b->mapToGlobal(QPoint(b->x(), b->y() + b->height())));
                     }
                     t->start();
                     tc = this;
                 } else {
                     tc = 0;
                     closeActiveWindow();
                 }
                 return true;
             }
         default:
             break;
         }
         return QWidget::eventFilter(o, e);
     }
     switch (e->type()) {
     case QEvent::HideToParent:
         break;
     case QEvent::ShowToParent:
         if (QWorkspaceChild *c = qobject_cast<QWorkspaceChild*>(o))
             if (!d->focus.contains(c))
                 d->focus.append(c);
         d->updateWorkspace();
         break;
     case QEvent::WindowTitleChange:
         if (!d->inTitleChange) {
             if (o == window())
                 d->topTitle = window()->windowTitle();
             if (d->maxWindow && d->maxWindow->windowWidget() && d->topTitle.size()) {
                 d->inTitleChange = true;
                 window()->setWindowTitle(tr("%1 - [%2]")
                                          .arg(d->topTitle).arg(d->maxWindow->windowWidget()->windowTitle()));
                 d->inTitleChange = false;
             }
         }
         break;
     case QEvent::ModifiedChange:
         if (o == d->maxWindow)
             window()->setWindowModified(d->maxWindow->isWindowModified());
         break;
     case QEvent::Close:
         if (o == window())
         {
             QList<QWorkspaceChild *>::Iterator it(d->windows.begin());
             while (it != d->windows.end()) {
                 QWorkspaceChild* c = *it;
                 ++it;
                 if (c->shademode)
                     c->showShaded();
             }
         } else if (qobject_cast<QWorkspaceChild*>(o)) {
             d->popup->hide();
         }
         d->updateWorkspace();
         break;
     default:
         break;
     }
     return QWidget::eventFilter(o, e);
 }
hideEvent()
void QWorkspace::hideEvent (QHideEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1616 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     if (!isVisible())
         d->hideMaximizeControls();
 }
paintEvent()
void QWorkspace::paintEvent (QPaintEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1624 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     if (d->background.style() != Qt::NoBrush) {
         QPainter p(this);
         p.fillRect(0, 0, width(), height(), d->background);
     }
 }
resizeEvent()
void QWorkspace::resizeEvent (QResizeEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1579 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     if (d->maxWindow) {
         d->maxWindow->adjustToFullscreen();
         if (d->maxWindow->windowWidget())
             d->maxWindow->windowWidget()->overrideWindowState(Qt::WindowMaximized);
     }
     d->updateWorkspace();
 }
scrollBarsEnabled()
bool QWorkspace::scrollBarsEnabled () const
Referenced by QWorkspaceChild::show(), and wheelEvent().
setActiveWindow
void QWorkspace::setActiveWindow (QWidget * w) slot
Makes the child window that contains w the active child window.
See also
activeWindow()
Definition at line 1393 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     d->activateWindow(w, true);
     if (w && w->isMinimized())
         w->setWindowState(w->windowState() & ~Qt::WindowMinimized);
 }
setBackground()
void QWorkspace::setBackground (const QBrush & background)
Definition at line 1212 of file qworkspace.cpp.
Referenced by sizeHint().
 {
     Q_D(QWorkspace);
     d->background = background;
     setAttribute(Qt::WA_OpaquePaintEvent, background.style() == Qt::NoBrush);
     update();
 }
setScrollBarsEnabled()
void QWorkspace::setScrollBarsEnabled (bool enable)
Definition at line 3200 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     if ((d->vbar != 0) == enable)
         return;
     d->xoffset = d->yoffset = 0;
     if (enable) {
         d->vbar = new QScrollBar(Qt::Vertical, this);
         d->vbar->setObjectName(QLatin1String("vertical scrollbar"));
         connect(d->vbar, SIGNAL(valueChanged(int)), this, SLOT(_q_scrollBarChanged()));
         d->hbar = new QScrollBar(Qt::Horizontal, this);
         d->hbar->setObjectName(QLatin1String("horizontal scrollbar"));
         connect(d->hbar, SIGNAL(valueChanged(int)), this, SLOT(_q_scrollBarChanged()));
         d->corner = new QWidget(this);
         d->corner->setBackgroundRole(QPalette::Window);
         d->corner->setObjectName(QLatin1String("qt_corner"));
         d->updateWorkspace();
     } else {
         delete d->vbar;
         delete d->hbar;
         delete d->corner;
         d->vbar = d->hbar = 0;
         d->corner = 0;
     }
     QList<QWorkspaceChild *>::Iterator it(d->windows.begin());
     while (it != d->windows.end()) {
         QWorkspaceChild *child = *it;
         ++it;
         child->widgetResizeHandler->setSizeProtection(!enable);
     }
 }
showEvent()
void QWorkspace::showEvent (QShowEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1591 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     if (d->maxWindow)
         d->showMaximizeControls();
     QWidget::showEvent(e);
     if (d->becomeActive) {
         d->activateWindow(d->becomeActive);
         d->becomeActive = 0;
     } else if (d->windows.count() > 0 && !d->active) {
         d->activateWindow(d->windows.first()->windowWidget());
     }
 //     // force a frame repaint - this is a workaround for what seems to be a bug
 //     // introduced when changing the QWidget::show() implementation. Might be
 //     // a windows bug as well though.
 //     for (int i = 0; i < d->windows.count(); ++i) {
 //      QWorkspaceChild* c = d->windows.at(i);
 //         c->update(c->rect());
 //     }
     d->updateWorkspace();
 }
sizeHint()
QSize QWorkspace::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1170 of file qworkspace.cpp.
 {
     QSize s(QApplication::desktop()->size());
     return QSize(s.width()*2/3, s.height()*2/3);
 }
tile
void QWorkspace::tile () slot
Arranges all child windows in a tile pattern.
See also
cascade(), arrangeIcons()
Definition at line 2376 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     blockSignals(true);
     QWidget *oldActive = d->active ? d->active->windowWidget() : 0;
     if  (d->maxWindow)
         d->maxWindow->showNormal();
     if (d->vbar) {
         d->vbar->blockSignals(true);
         d->vbar->setValue(0);
         d->vbar->blockSignals(false);
         d->hbar->blockSignals(true);
         d->hbar->setValue(0);
         d->hbar->blockSignals(false);
         d->_q_scrollBarChanged();
     }
     int rows = 1;
     int cols = 1;
     int n = 0;
     QWorkspaceChild* c;
     QList<QWorkspaceChild *>::Iterator it(d->windows.begin());
     while (it != d->windows.end()) {
         c = *it;
         ++it;
         if (!c->windowWidget()->isHidden()
             && !(c->windowWidget()->windowFlags() & Qt::WindowStaysOnTopHint)
             && !c->iconw)
             n++;
     }
     while (rows * cols < n) {
         if (cols <= rows)
             cols++;
         else
             rows++;
     }
     int add = cols * rows - n;
     bool* used = new bool[cols*rows];
     for (int i = 0; i < rows*cols; i++)
         used[i] = false;
     int row = 0;
     int col = 0;
     int w = width() / cols;
     int h = height() / rows;
     it = d->windows.begin();
     while (it != d->windows.end()) {
         c = *it;
         ++it;
         if (c->iconw || c->windowWidget()->isHidden() || (c->titlebar && c->titlebar->isTool()))
             continue;
         if (!row && !col) {
             w -= c->baseSize().width();
             h -= c->baseSize().height();
         }
         if ((c->windowWidget()->windowFlags() & Qt::WindowStaysOnTopHint)) {
             QPoint p = c->pos();
             if (p.x()+c->width() < 0)
                 p.setX(0);
             if (p.x() > width())
                 p.setX(width() - c->width());
             if (p.y() + 10 < 0)
                 p.setY(0);
             if (p.y() > height())
                 p.setY(height() - c->height());
             if (p != c->pos())
                 c->QWidget::move(p);
         } else {
             c->showNormal();
             used[row*cols+col] = true;
             QSize sz(w, h);
             QSize bsize(c->baseSize());
             sz = sz.expandedTo(c->windowWidget()->minimumSize()).boundedTo(c->windowWidget()->maximumSize());
             sz += bsize;
             if ( add ) {
                 if (sz.height() == h + bsize.height()) // no relevant constrains
                     sz.rheight() *= 2;
                 used[(row+1)*cols+col] = true;
                 add--;
             }
             c->setGeometry(col*w + col*bsize.width(), row*h + row*bsize.height(), sz.width(), sz.height());
             while(row < rows && col < cols && used[row*cols+col]) {
                 col++;
                 if (col == cols) {
                     col = 0;
                     row++;
                 }
             }
         }
     }
     delete [] used;
     d->activateWindow(oldActive);
     d->updateWorkspace();
     blockSignals(false);
 }
wheelEvent()
void QWorkspace::wheelEvent (QWheelEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1302 of file qworkspace.cpp.
 {
     Q_D(QWorkspace);
     if (!scrollBarsEnabled())
         return;
     // the scroll bars are children of the workspace, so if we receive
     // a wheel event we redirect to the scroll bars using a direct event
     // call, /not/ using sendEvent() because if the scroll bar ignores the
     // event QApplication::sendEvent() will propagate the event to the parent widget,
     // which is us, who /just/ sent it.
     if (d->vbar && d->vbar->isVisible() && !(e->modifiers() & Qt::AltModifier))
         d->vbar->event(e);
     else if (d->hbar && d->hbar->isVisible())
         d->hbar->event(e);
 }
windowActivated
void QWorkspace::windowActivated (QWidget * w) signal
This signal is emitted when the child window w becomes active.
Note that w can be 0, and that more than one signal may be emitted for a single activation event.
See also
activeWindow(), windowList()
windowList()
QWidgetList QWorkspace::windowList (WindowOrder order = CreationOrder) const
Returns a list of all visible or minimized child windows.
If order is CreationOrder (the default), the windows are listed in the order in which they were inserted into the workspace. If order is StackingOrder, the windows are listed in their stacking order, with the topmost window as the last item in the list.
Definition at line 1801 of file qworkspace.cpp.
Referenced by QAccessibleWorkspace::childCount(), QAccessibleWorkspace::indexOfChild(), QAccessibleWorkspace::navigate(), and QAccessibleWorkspace::state().
 {
     Q_D(const QWorkspace);
     QWidgetList windows;
     if (order == StackingOrder) {
         QObjectList cl = children();
         for (int i = 0; i < cl.size(); ++i) {
             QWorkspaceChild *c = qobject_cast<QWorkspaceChild*>(cl.at(i));
             if (c && c->isWindowOrIconVisible())
                 windows.append(c->windowWidget());
         }
     } else {
         QList<QWorkspaceChild *>::ConstIterator it(d->windows.begin());
         while (it != d->windows.end()) {
             QWorkspaceChild* c = *it;
             ++it;
             if (c && c->isWindowOrIconVisible())
                 windows.append(c->windowWidget());
         }
     }
     return windows;
 }
Friends and Related Functions
QWorkspaceChild
friend class QWorkspaceChild friend
Definition at line 128 of file qworkspace.h.
Referenced by addWindow().
Properties
background
QBrush QWorkspace::background private
the workspace's background
Definition at line 64 of file qworkspace.h.
scrollBarsEnabled
QWorkspace::scrollBarsEnabled private
whether the workspace provides scroll bars
If this property is true, the workspace will provide scroll bars if any of the child windows extend beyond the edges of the visible workspace. The workspace area will automatically increase to contain child windows if they are resized beyond the right or bottom edges of the visible area.
If this property is false (the default), resizing child windows out of the visible area of the workspace is not permitted, although it is still possible to position them partially outside the visible area.
Definition at line 63 of file qworkspace.h.
Referenced by QWorkspaceChild::QWorkspaceChild().
The documentation for this class was generated from the following files:
/src/gui/widgets/qworkspace.h
/src/gui/widgets/qworkspace.cpp