Qt 4.8: QPlatformSoftwareCursor Class Reference
QPlatformSoftwareCursor Class Reference
#include <fb_base.h>
Public Functions
virtual void changeCursor (QCursor *widgetCursor, QWidget *widget)
This method is called by Qt whenever the cursor graphic should be changed.
QRect dirtyRect ()
virtual QRect drawCursor (QPainter &painter)
virtual bool isDirty ()
virtual bool isOnScreen ()
virtual QRect lastPainted ()
virtual void pointerEvent (const QMouseEvent &event)
This method is called by Qt whenever a QMouseEvent is generated by the underlying pointer input.
QPlatformSoftwareCursor (QPlatformScreen *scr)
virtual void setDirty ()
Public Functions inherited from QPlatformCursor
virtual QPoint pos () const
QPlatformCursor (QPlatformScreen *)
Constructs a QPlatformCursor for the given screen.
virtual void setPos (const QPoint &pos)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Variables
QPlatformCursorImage * graphic
Protected Variables inherited from QPlatformCursor
QPlatformScreen * screen
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Private Functions
QRect getCurrentRect ()
void setCursor (const uchar *data, const uchar *mask, int width, int height, int hotX, int hotY)
void setCursor (Qt::CursorShape shape)
void setCursor (const QImage &image, int hotx, int hoty)
Properties
QRect currentRect
bool dirty
bool onScreen
QRect prevRect
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 60 of file fb_base.h.
Constructors and Destructors
QPlatformSoftwareCursor()
QPlatformSoftwareCursor::QPlatformSoftwareCursor (QPlatformScreen * scr)
Definition at line 49 of file fb_base.cpp.
         : QPlatformCursor(scr), currentRect(QRect()), prevRect(QRect())
 {
     graphic = new QPlatformCursorImage(0, 0, 0, 0, 0, 0);
     setCursor(Qt::ArrowCursor);
 }
Functions
changeCursor()
void QPlatformSoftwareCursor::changeCursor (QCursor * widgetCursor, QWidget * widget) virtual
This method is called by Qt whenever the cursor graphic should be changed.
Implementation of this method is mandatory for a subclass of QPlatformCursor.
widgetCursor is a pointer to the QCursor that should be displayed.
widget is a pointer to the widget currently displayed at QCursor::pos(). Note that this may be 0 if the current position is not occupied by a displayed widget.
See also
QCursor::pos()
Implements QPlatformCursor.
Reimplemented in QVNCCursor.
Definition at line 120 of file fb_base.cpp.
Referenced by QVNCCursor::changeCursor().
 {
 #ifdef QT_NO_CURSOR
     Q_UNUSED(widgetCursor);
     Q_UNUSED(widget);
 #else
     Q_UNUSED(widget);
     Qt::CursorShape shape = widgetCursor->shape();
     if (shape == Qt::BitmapCursor) {
         // application supplied cursor
         QPoint spot = widgetCursor->hotSpot();
         setCursor(widgetCursor->pixmap().toImage(), spot.x(), spot.y());
     } else {
         // system cursor
         setCursor(shape);
     }
     currentRect = getCurrentRect();
     QPoint screenOffset = screen->geometry().topLeft(); // global to local translation
     if (onScreen || screen->geometry().intersects(currentRect.translated(screenOffset)))
         setDirty();
 #endif
 }
dirtyRect()
QRect QPlatformSoftwareCursor::dirtyRect ()
Definition at line 96 of file fb_base.cpp.
Referenced by QFbScreen::doRedraw().
 {
     if (onScreen) {
         onScreen = false;
         return prevRect;
     }
     return QRect();
 }
drawCursor()
QRect QPlatformSoftwareCursor::drawCursor (QPainter & painter) virtual
Reimplemented in QVNCCursor.
Definition at line 78 of file fb_base.cpp.
Referenced by QFbScreen::doRedraw(), and QVNCCursor::drawCursor().
 {
     dirty = false;
     if (currentRect.isNull())
         return QRect();
     // We need this because the cursor might be dirty due to moving off screen
     QPoint screenOffset = screen->geometry().topLeft();
     // global to local translation
     if (!currentRect.translated(screenOffset).intersects(screen->geometry()))
         return QRect();
     prevRect = currentRect;
     painter.drawImage(prevRect, *graphic->image());
     onScreen = true;
     return prevRect;
 }
getCurrentRect()
QRect QPlatformSoftwareCursor::getCurrentRect () private
Definition at line 56 of file fb_base.cpp.
Referenced by changeCursor(), and pointerEvent().
 {
     QRect rect = graphic->image()->rect().translated(-graphic->hotspot().x(),
                                                      -graphic->hotspot().y());
     rect.translate(QCursor::pos());
     QPoint screenOffset = screen->geometry().topLeft();
     rect.translate(-screenOffset);  // global to local translation
     return rect;
 }
isDirty()
virtual bool QPlatformSoftwareCursor::isDirty () inline virtual
Definition at line 74 of file fb_base.h.
Referenced by QFbScreen::doRedraw().
 { return dirty; }
isOnScreen()
virtual bool QPlatformSoftwareCursor::isOnScreen () inline virtual
Definition at line 75 of file fb_base.h.
Referenced by QFbScreen::doRedraw().
 { return onScreen; }
lastPainted()
virtual QRect QPlatformSoftwareCursor::lastPainted () inline virtual
Definition at line 76 of file fb_base.h.
Referenced by QFbScreen::doRedraw().
 { return prevRect; }
pointerEvent()
void QPlatformSoftwareCursor::pointerEvent (const QMouseEvent & event) virtual
This method is called by Qt whenever a QMouseEvent is generated by the underlying pointer input.
event is a reference to the QMouseEvent in question. A default do-nothing implementation is provided.
Reimplemented from QPlatformCursor.
Definition at line 67 of file fb_base.cpp.
Referenced by QVNCServer::hasClientCursor(), and QVNCServer::setCursor().
 {
     Q_UNUSED(e);
     QPoint screenOffset = screen->geometry().topLeft();
     currentRect = getCurrentRect();
     // global to local translation
     if (onScreen || screen->geometry().intersects(currentRect.translated(screenOffset))) {
         setDirty();
     }
 }
setCursor() [1/3]
void QPlatformSoftwareCursor::setCursor (const uchar * data, const uchar * mask, int width, int height, int hotX, int hotY) private
Definition at line 115 of file fb_base.cpp.
Referenced by changeCursor(), and QPlatformSoftwareCursor().
 {
     graphic->set(data, mask, width, height, hotX, hotY);
 }
setCursor() [2/3]
void QPlatformSoftwareCursor::setCursor (Qt::CursorShape shape) private
Definition at line 105 of file fb_base.cpp.
 {
     graphic->set(shape);
 }
setCursor() [3/3]
void QPlatformSoftwareCursor::setCursor (const QImage & image, int hotx, int hoty) private
Definition at line 110 of file fb_base.cpp.
 {
     graphic->set(image, hotx, hoty);
 }
setDirty()
virtual void QPlatformSoftwareCursor::setDirty () inline virtual
Definition at line 73 of file fb_base.h.
Referenced by QVNCCursor::changeCursor(), changeCursor(), QVNCCursor::hide(), QVNCCursor::move(), QFbScreen::physicalSize(), pointerEvent(), QVNCCursor::set(), QVNCCursor::setCursorMode(), QVNCServer::setDirtyCursor(), QVNCCursor::show(), and QVNCDirtyMapOptimized< T >::~QVNCDirtyMapOptimized().
 { dirty = true; screen->setDirty(QRect()); }
Properties
currentRect
QRect QPlatformSoftwareCursor::currentRect private
Definition at line 85 of file fb_base.h.
Referenced by changeCursor(), drawCursor(), and pointerEvent().
dirty
bool QPlatformSoftwareCursor::dirty private
Definition at line 88 of file fb_base.h.
Referenced by drawCursor(), isDirty(), QVNCCursor::move(), QVNCCursor::set(), and setDirty().
graphic
QPlatformCursorImage* QPlatformSoftwareCursor::graphic protected
Definition at line 79 of file fb_base.h.
Referenced by drawCursor(), getCurrentRect(), QPlatformSoftwareCursor(), QVNCCursor::sendClientCursor(), and setCursor().
onScreen
bool QPlatformSoftwareCursor::onScreen private
Definition at line 89 of file fb_base.h.
Referenced by changeCursor(), dirtyRect(), drawCursor(), isOnScreen(), and pointerEvent().
prevRect
QRect QPlatformSoftwareCursor::prevRect private
Definition at line 86 of file fb_base.h.
Referenced by dirtyRect(), drawCursor(), and lastPainted().
The documentation for this class was generated from the following files:
/src/plugins/platforms/fb_base/fb_base.h
/src/plugins/platforms/fb_base/fb_base.cpp