Qt 4.8: QSvgTinyDocument Class Reference
QSvgTinyDocument Class Reference
#include <qsvgtinydocument_p.h>
Public Functions
void addNamedNode (const QString &id, QSvgNode *node)
void addNamedStyle (const QString &id, QSvgFillStyleProperty *style)
void addSvgFont (QSvgFont *)
bool animated () const
int animationDuration () const
QRectF boundsOnElement (const QString &id) const
int currentElapsed () const
int currentFrame () const
virtual void draw (QPainter *p, QSvgExtraStates &)
void draw (QPainter *p)
void draw (QPainter *p, const QRectF &bounds)
void draw (QPainter *p, const QString &id, const QRectF &bounds=QRectF())
bool elementExists (const QString &id) const
int height () const
bool heightPercent () const
QMatrix matrixForElement (const QString &id) const
QSvgNode * namedNode (const QString &id) const
QSvgFillStyleProperty * namedStyle (const QString &id) const
bool preserveAspectRatio () const
QSvgTinyDocument ()
void restartAnimation ()
void setAnimated (bool a)
void setCurrentFrame (int)
void setFramesPerSecond (int num)
void setHeight (int len, bool percent)
void setViewBox (const QRectF &rect)
void setWidth (int len, bool percent)
QSize size () const
QSvgFont * svgFont (const QString &family) const
Type type () const
QRectF viewBox () const
int width () const
bool widthPercent () const
~QSvgTinyDocument ()
Public Functions inherited from QSvgStructureNode
void addChild (QSvgNode *child, const QString &id)
virtual QRectF bounds (QPainter *p, QSvgExtraStates &states) const
QSvgNode * previousSiblingNode (QSvgNode *n) const
QSvgStructureNode (QSvgNode *parent)
QList< QSvgNode * > renderers () const
QSvgNode * scopeNode (const QString &id) const
~QSvgStructureNode ()
Public Functions inherited from QSvgNode
void appendStyleProperty (QSvgStyleProperty *prop, const QString &id)
void applyStyle (QPainter *p, QSvgExtraStates &states) const
DisplayMode displayMode () const
QSvgTinyDocument * document () const
bool isVisible () const
QString nodeId () const
QSvgNode * parent () const
QSvgNode (QSvgNode *parent=0)
const QStringList & requiredExtensions () const
const QStringList & requiredFeatures () const
const QStringList & requiredFonts () const
const QStringList & requiredFormats () const
const QStringList & requiredLanguages () const
void revertStyle (QPainter *p, QSvgExtraStates &states) const
void setDisplayMode (DisplayMode display)
void setNodeId (const QString &i)
void setRequiredExtensions (const QStringList &lst)
void setRequiredFeatures (const QStringList &lst)
void setRequiredFonts (const QStringList &lst)
void setRequiredFormats (const QStringList &lst)
void setRequiredLanguages (const QStringList &lst)
void setVisible (bool visible)
void setXmlClass (const QString &str)
QSvgStyleProperty * styleProperty (QSvgStyleProperty::Type type) const
QSvgFillStyleProperty * styleProperty (const QString &id) const
virtual QRectF transformedBounds (QPainter *p, QSvgExtraStates &states) const
QRectF transformedBounds () const
QString xmlClass () const
virtual ~QSvgNode ()
Static Public Functions
static QSvgTinyDocument * load (const QString &file)
static QSvgTinyDocument * load (const QByteArray &contents)
static QSvgTinyDocument * load (QXmlStreamReader *contents)
Private Functions
void mapSourceToTarget (QPainter *p, const QRectF &targetRect, const QRectF &sourceRect=QRectF())
Properties
bool m_animated
int m_animationDuration
QHash< QString, QSvgRefCounter< QSvgFont > > m_fonts
int m_fps
bool m_heightPercent
QHash< QString, QSvgNode * > m_namedNodes
QHash< QString, QSvgRefCounter< QSvgFillStyleProperty > > m_namedStyles
QSize m_size
QSvgExtraStates m_states
QTime m_time
QRectF m_viewBox
bool m_widthPercent
Additional Inherited Members
Public Types inherited from QSvgNode
enum DisplayMode {
InlineMode, BlockMode, ListItemMode, RunInMode,
CompactMode, MarkerMode, TableMode, InlineTableMode,
TableRowGroupMode, TableHeaderGroupMode, TableFooterGroupMode, TableRowMode,
TableColumnGroupMode, TableColumnMode, TableCellMode, TableCaptionMode,
NoneMode, InheritMode
}
enum Type {
DOC, G, DEFS, SWITCH,
ANIMATION, ARC, CIRCLE, ELLIPSE,
IMAGE, LINE, PATH, POLYGON,
POLYLINE, RECT, TEXT, TEXTAREA,
TSPAN, USE, VIDEO
}
Static Protected Functions inherited from QSvgNode
static qreal strokeWidth (QPainter *p)
Protected Variables inherited from QSvgStructureNode
QList< QSvgStructureNode * > m_linkedScopes
QList< QSvgNode * > m_renderers
QHash< QString, QSvgNode * > m_scope
Protected Variables inherited from QSvgNode
QSvgStyle m_style
Detailed Description
Definition at line 74 of file qsvgtinydocument_p.h.
Constructors and Destructors
QSvgTinyDocument()
QSvgTinyDocument::QSvgTinyDocument ()
Definition at line 63 of file qsvgtinydocument.cpp.
     : QSvgStructureNode(0)
     , m_widthPercent(false)
     , m_heightPercent(false)
     , m_animated(false)
     , m_animationDuration(0)
     , m_fps(30)
 {
 }
~QSvgTinyDocument()
QSvgTinyDocument::~QSvgTinyDocument ()
Definition at line 73 of file qsvgtinydocument.cpp.
 {
 }
Functions
addNamedNode()
void QSvgTinyDocument::addNamedNode (const QString & id, QSvgNode * node)
Definition at line 353 of file qsvgtinydocument.cpp.
Referenced by QSvgStructureNode::addChild().
 {
     m_namedNodes.insert(id, node);
 }
addNamedStyle()
void QSvgTinyDocument::addNamedStyle (const QString & id, QSvgFillStyleProperty * style)
Definition at line 363 of file qsvgtinydocument.cpp.
Referenced by QSvgNode::appendStyleProperty().
 {
     m_namedStyles.insert(id, style);
 }
addSvgFont()
void QSvgTinyDocument::addSvgFont (QSvgFont * font)
Definition at line 343 of file qsvgtinydocument.cpp.
Referenced by createFontNode(), parseFontFaceNameNode(), and parseFontFaceNode().
 {
     m_fonts.insert(font->familyName(), font);
 }
animated()
bool QSvgTinyDocument::animated () const
Definition at line 378 of file qsvgtinydocument.cpp.
Referenced by loadDocument().
 {
     return m_animated;
 }
animationDuration()
int QSvgTinyDocument::animationDuration () const inline
Definition at line 192 of file qsvgtinydocument_p.h.
 {
     return m_animationDuration;
 }
boundsOnElement()
QRectF QSvgTinyDocument::boundsOnElement (const QString & id) const
Definition at line 430 of file qsvgtinydocument.cpp.
 {
     const QSvgNode *node = scopeNode(id);
     if (!node)
         node = this;
     return node->transformedBounds();
 }
currentElapsed()
int QSvgTinyDocument::currentElapsed () const inline
Definition at line 187 of file qsvgtinydocument_p.h.
Referenced by QSvgAnimateColor::apply(), QSvgStyle::apply(), and QSvgAnimateTransform::resolveMatrix().
 {
     return m_time.elapsed();
 }
currentFrame()
int QSvgTinyDocument::currentFrame () const
Definition at line 466 of file qsvgtinydocument.cpp.
 {
     double runningPercentage = qMin(m_time.elapsed()/double(m_animationDuration), 1.);
     int totalFrames = m_fps * m_animationDuration;
     return int(runningPercentage * totalFrames);
 }
draw() [1/4]
void QSvgTinyDocument::draw (QPainter * p, QSvgExtraStates &) virtual
Implements QSvgNode.
Definition at line 393 of file qsvgtinydocument.cpp.
Referenced by draw().
 {
     draw(p);
 }
draw() [2/4]
void QSvgTinyDocument::draw (QPainter * p)
Definition at line 388 of file qsvgtinydocument.cpp.
 {
     draw(p, QRectF());
 }
draw() [3/4]
void QSvgTinyDocument::draw (QPainter * p, const QRectF & bounds)
Definition at line 230 of file qsvgtinydocument.cpp.
 {
     if (m_time.isNull()) {
         m_time.start();
     }
     if (displayMode() == QSvgNode::NoneMode)
         return;
     p->save();
     //sets default style on the painter
     //### not the most optimal way
     mapSourceToTarget(p, bounds);
     QPen pen(Qt::NoBrush, 1, Qt::SolidLine, Qt::FlatCap, Qt::MiterJoin);
     pen.setMiterLimit(4);
     p->setPen(pen);
     p->setBrush(Qt::black);
     p->setRenderHint(QPainter::Antialiasing);
     p->setRenderHint(QPainter::SmoothPixmapTransform);
     QList<QSvgNode*>::iterator itr = m_renderers.begin();
     applyStyle(p, m_states);
     while (itr != m_renderers.end()) {
         QSvgNode *node = *itr;
         if ((node->isVisible()) && (node->displayMode() != QSvgNode::NoneMode))
             node->draw(p, m_states);
         ++itr;
     }
     revertStyle(p, m_states);
     p->restore();
 }
draw() [4/4]
void QSvgTinyDocument::draw (QPainter * p, const QString & id, const QRectF & bounds = QRectF())
Definition at line 262 of file qsvgtinydocument.cpp.
 {
     QSvgNode *node = scopeNode(id);
     if (!node) {
         qDebug("Couldn't find node %s. Skipping rendering.", qPrintable(id));
         return;
     }
     if (m_time.isNull()) {
         m_time.start();
     }
     if (node->displayMode() == QSvgNode::NoneMode)
         return;
     p->save();
     const QRectF elementBounds = node->transformedBounds();
     mapSourceToTarget(p, bounds, elementBounds);
     QTransform originalTransform = p->worldTransform();
     //XXX set default style on the painter
     QPen pen(Qt::NoBrush, 1, Qt::SolidLine, Qt::FlatCap, Qt::MiterJoin);
     pen.setMiterLimit(4);
     p->setPen(pen);
     p->setBrush(Qt::black);
     p->setRenderHint(QPainter::Antialiasing);
     p->setRenderHint(QPainter::SmoothPixmapTransform);
     QStack<QSvgNode*> parentApplyStack;
     QSvgNode *parent = node->parent();
     while (parent) {
         parentApplyStack.push(parent);
         parent = parent->parent();
     }
     for (int i = parentApplyStack.size() - 1; i >= 0; --i)
         parentApplyStack[i]->applyStyle(p, m_states);
     // Reset the world transform so that our parents don't affect
     // the position
     QTransform currentTransform = p->worldTransform();
     p->setWorldTransform(originalTransform);
     node->draw(p, m_states);
     p->setWorldTransform(currentTransform);
     for (int i = 0; i < parentApplyStack.size(); ++i)
         parentApplyStack[i]->revertStyle(p, m_states);
     //p->fillRect(bounds.adjusted(-5, -5, 5, 5), QColor(0, 0, 255, 100));
     p->restore();
 }
elementExists()
bool QSvgTinyDocument::elementExists (const QString & id) const
Definition at line 438 of file qsvgtinydocument.cpp.
 {
     QSvgNode *node = scopeNode(id);
     return (node!=0);
 }
height()
int QSvgTinyDocument::height () const inline
Definition at line 159 of file qsvgtinydocument_p.h.
 {
     return size().height();
 }
heightPercent()
bool QSvgTinyDocument::heightPercent () const inline
Definition at line 169 of file qsvgtinydocument_p.h.
 {
     return m_heightPercent;
 }
load() [1/3]
QSvgTinyDocument * QSvgTinyDocument::load (const QString & file) static
Definition at line 170 of file qsvgtinydocument.cpp.
Referenced by load(), and loadDocument().
 {
     QFile file(fileName);
     if (!file.open(QFile::ReadOnly)) {
         qWarning("Cannot open file '%s', because: %s",
                  qPrintable(fileName), qPrintable(file.errorString()));
         return 0;
     }
 #ifndef QT_NO_COMPRESS
     if (fileName.endsWith(QLatin1String(".svgz"), Qt::CaseInsensitive)
             || fileName.endsWith(QLatin1String(".svg.gz"), Qt::CaseInsensitive)) {
         return load(qt_inflateGZipDataFrom(&file));
     }
 #endif
     QSvgTinyDocument *doc = 0;
     QSvgHandler handler(&file);
     if (handler.ok()) {
         doc = handler.document();
         doc->m_animationDuration = handler.animationDuration();
     } else {
         qWarning("Cannot read file '%s', because: %s (line %d)",
                  qPrintable(fileName), qPrintable(handler.errorString()), handler.lineNumber());
     }
     return doc;
 }
load() [2/3]
QSvgTinyDocument * QSvgTinyDocument::load (const QByteArray & contents) static
Definition at line 198 of file qsvgtinydocument.cpp.
 {
 #ifndef QT_NO_COMPRESS
     // Check for gzip magic number and inflate if appropriate
     if (contents.startsWith("\x1f\x8b")) {
         QBuffer buffer(const_cast<QByteArray *>(&contents));
         return load(qt_inflateGZipDataFrom(&buffer));
     }
 #endif
     QSvgHandler handler(contents);
     QSvgTinyDocument *doc = 0;
     if (handler.ok()) {
         doc = handler.document();
         doc->m_animationDuration = handler.animationDuration();
     }
     return doc;
 }
load() [3/3]
QSvgTinyDocument * QSvgTinyDocument::load (QXmlStreamReader * contents) static
Definition at line 218 of file qsvgtinydocument.cpp.
 {
     QSvgHandler handler(contents);
     QSvgTinyDocument *doc = 0;
     if (handler.ok()) {
         doc = handler.document();
         doc->m_animationDuration = handler.animationDuration();
     }
     return doc;
 }
mapSourceToTarget()
void QSvgTinyDocument::mapSourceToTarget (QPainter * p, const QRectF & targetRect, const QRectF & sourceRect = QRectF()) private
Definition at line 398 of file qsvgtinydocument.cpp.
Referenced by draw().
 {
     QRectF target = targetRect;
     if (target.isNull()) {
         QPaintDevice *dev = p->device();
         QRectF deviceRect(0, 0, dev->width(), dev->height());
         if (deviceRect.isNull()) {
             if (sourceRect.isNull())
                 target = QRectF(QPointF(0, 0), size());
             else
                 target = QRectF(QPointF(0, 0), sourceRect.size());
         } else {
             target = deviceRect;
         }
     }
     QRectF source = sourceRect;
     if (source.isNull())
         source = viewBox();
     if (source != target && !source.isNull()) {
         QTransform transform;
         transform.scale(target.width() / source.width(),
                   target.height() / source.height());
         QRectF c2 = transform.mapRect(source);
         p->translate(target.x() - c2.x(),
                      target.y() - c2.y());
         p->scale(target.width() / source.width(),
                  target.height() / source.height());
     }
 }
matrixForElement()
QMatrix QSvgTinyDocument::matrixForElement (const QString & id) const
Definition at line 445 of file qsvgtinydocument.cpp.
 {
     QSvgNode *node = scopeNode(id);
     if (!node) {
         qDebug("Couldn't find node %s. Skipping rendering.", qPrintable(id));
         return QMatrix();
     }
     QTransform t;
     node = node->parent();
     while (node) {
         if (node->m_style.transform)
             t *= node->m_style.transform->qtransform();
         node = node->parent();
     }
     return t.toAffine();
 }
namedNode()
QSvgNode * QSvgTinyDocument::namedNode (const QString & id) const
Definition at line 358 of file qsvgtinydocument.cpp.
Referenced by QSvgStructureNode::scopeNode().
 {
     return m_namedNodes.value(id);
 }
namedStyle()
QSvgFillStyleProperty * QSvgTinyDocument::namedStyle (const QString & id) const
Definition at line 368 of file qsvgtinydocument.cpp.
Referenced by QSvgNode::styleProperty().
 {
     return m_namedStyles.value(id);
 }
preserveAspectRatio()
bool QSvgTinyDocument::preserveAspectRatio () const inline
Definition at line 182 of file qsvgtinydocument_p.h.
 {
     return false;
 }
restartAnimation()
void QSvgTinyDocument::restartAnimation ()
Definition at line 373 of file qsvgtinydocument.cpp.
 {
     m_time.restart();
 }
setAnimated()
void QSvgTinyDocument::setAnimated (bool a)
Definition at line 383 of file qsvgtinydocument.cpp.
Referenced by parseAnimateColorNode(), and parseAnimateTransformNode().
 {
     m_animated = a;
 }
setCurrentFrame()
void QSvgTinyDocument::setCurrentFrame (int frame)
Definition at line 475 of file qsvgtinydocument.cpp.
 {
     int totalFrames = m_fps * m_animationDuration;
     double framePercentage = frame/double(totalFrames);
     double timeForFrame = m_animationDuration * framePercentage; //in S
     timeForFrame *= 1000; //in ms
     int timeToAdd = int(timeForFrame - m_time.elapsed());
     m_time = m_time.addMSecs(timeToAdd);
 }
setFramesPerSecond()
void QSvgTinyDocument::setFramesPerSecond (int num)
Definition at line 485 of file qsvgtinydocument.cpp.
 {
     m_fps = num;
 }
setHeight()
void QSvgTinyDocument::setHeight (int len, bool percent)
Definition at line 332 of file qsvgtinydocument.cpp.
Referenced by createSvgNode().
 {
     m_size.setHeight(len);
     m_heightPercent = percent;
 }
setViewBox()
void QSvgTinyDocument::setViewBox (const QRectF & rect)
Definition at line 338 of file qsvgtinydocument.cpp.
Referenced by createSvgNode().
 {
     m_viewBox = rect;
 }
setWidth()
void QSvgTinyDocument::setWidth (int len, bool percent)
Definition at line 326 of file qsvgtinydocument.cpp.
Referenced by createSvgNode().
 {
     m_size.setWidth(len);
     m_widthPercent = percent;
 }
size()
QSize QSvgTinyDocument::size () const inline
Definition at line 145 of file qsvgtinydocument_p.h.
Referenced by mapSourceToTarget().
 {
     if (m_size.isEmpty()) {
         return viewBox().size().toSize();
     } else {
         return m_size;
     }
 }
svgFont()
QSvgFont * QSvgTinyDocument::svgFont (const QString & family) const
Definition at line 348 of file qsvgtinydocument.cpp.
Referenced by createFontNode(), parseFont(), parseFontFaceNameNode(), and parseFontFaceNode().
 {
     return m_fonts[family];
 }
type()
QSvgNode::Type QSvgTinyDocument::type () const virtual
Implements QSvgNode.
Definition at line 321 of file qsvgtinydocument.cpp.
 {
     return DOC;
 }
viewBox()
QRectF QSvgTinyDocument::viewBox () const inline
Definition at line 174 of file qsvgtinydocument_p.h.
Referenced by mapSourceToTarget().
 {
     if (m_viewBox.isNull())
         m_viewBox = transformedBounds();
     return m_viewBox;
 }
width()
int QSvgTinyDocument::width () const inline
Definition at line 154 of file qsvgtinydocument_p.h.
 {
     return size().width();
 }
widthPercent()
bool QSvgTinyDocument::widthPercent () const inline
Definition at line 164 of file qsvgtinydocument_p.h.
 {
     return m_widthPercent;
 }
Properties
m_animated
bool QSvgTinyDocument::m_animated private
Definition at line 138 of file qsvgtinydocument_p.h.
Referenced by animated(), and setAnimated().
m_animationDuration
int QSvgTinyDocument::m_animationDuration private
Definition at line 139 of file qsvgtinydocument_p.h.
Referenced by currentFrame(), load(), and setCurrentFrame().
m_fonts
QHash<QString, QSvgRefCounter<QSvgFont> > QSvgTinyDocument::m_fonts private
Definition at line 133 of file qsvgtinydocument_p.h.
Referenced by addSvgFont(), and svgFont().
m_fps
int QSvgTinyDocument::m_fps private
Definition at line 140 of file qsvgtinydocument_p.h.
Referenced by currentFrame(), setCurrentFrame(), and setFramesPerSecond().
m_heightPercent
bool QSvgTinyDocument::m_heightPercent private
Definition at line 129 of file qsvgtinydocument_p.h.
Referenced by setHeight().
m_namedNodes
QHash<QString, QSvgNode *> QSvgTinyDocument::m_namedNodes private
Definition at line 134 of file qsvgtinydocument_p.h.
Referenced by addNamedNode(), and namedNode().
m_namedStyles
QHash<QString, QSvgRefCounter<QSvgFillStyleProperty> > QSvgTinyDocument::m_namedStyles private
Definition at line 135 of file qsvgtinydocument_p.h.
Referenced by addNamedStyle(), and namedStyle().
m_size
QSize QSvgTinyDocument::m_size private
Definition at line 127 of file qsvgtinydocument_p.h.
Referenced by setHeight(), and setWidth().
m_states
QSvgExtraStates QSvgTinyDocument::m_states private
Definition at line 142 of file qsvgtinydocument_p.h.
Referenced by draw().
m_time
QTime QSvgTinyDocument::m_time private
Definition at line 137 of file qsvgtinydocument_p.h.
Referenced by currentFrame(), draw(), restartAnimation(), and setCurrentFrame().
m_viewBox
QRectF QSvgTinyDocument::m_viewBox mutable private
Definition at line 131 of file qsvgtinydocument_p.h.
Referenced by setViewBox().
m_widthPercent
bool QSvgTinyDocument::m_widthPercent private
Definition at line 128 of file qsvgtinydocument_p.h.
Referenced by setWidth().
The documentation for this class was generated from the following files:
/src/svg/qsvgtinydocument_p.h
/src/svg/qsvgtinydocument.cpp