Qt 4.8: QPalette Class Reference
QPalette Class Reference
The QPalette class contains color groups for each widget state.
#include <qpalette.h>
Public Types
enum ColorGroup {
Active, Disabled, Inactive, NColorGroups,
Current, All, Normal = Active
}
enum ColorRole {
WindowText, Button, Light, Midlight,
Dark, Mid, Text, BrightText,
ButtonText, Base, Window, Shadow,
Highlight, HighlightedText, Link, LinkVisited,
AlternateBase, NoRole, ToolTipBase, ToolTipText,
NColorRoles = ToolTipText + 1, Foreground = WindowText, Background = Window
}
The ColorRole enum defines the different symbolic color roles used in current GUIs.
Public Functions
const QBrush & alternateBase () const
Returns the alternate base brush of the current color group.
const QBrush & background () const
Use window() instead.
const QBrush & base () const
Returns the base brush of the current color group.
const QBrush & brightText () const
Returns the bright text foreground brush of the current color group.
const QBrush & brush (ColorGroup cg, ColorRole cr) const
Returns the brush in the specified color group, used for the given color role.
const QBrush & brush (ColorRole cr) const
Returns the brush that has been set for the given color role in the current ColorGroup.
const QBrush & button () const
Returns the button brush of the current color group.
const QBrush & buttonText () const
Returns the button text foreground brush of the current color group.
qint64 cacheKey () const
Returns a number that identifies the contents of this QPalette object.
const QColor & color (ColorGroup cg, ColorRole cr) const
Returns the color in the specified color group, used for the given color role.
const QColor & color (ColorRole cr) const
Returns the color that has been set for the given color role in the current ColorGroup.
ColorGroup currentColorGroup () const
Returns the palette's current color group.
const QBrush & dark () const
Returns the dark brush of the current color group.
const QBrush & foreground () const
Use windowText() instead.
const QBrush & highlight () const
Returns the highlight brush of the current color group.
const QBrush & highlightedText () const
Returns the highlighted text brush of the current color group.
bool isBrushSet (ColorGroup cg, ColorRole cr) const
Returns true if the ColorGroup cg and ColorRole cr has been set previously on this palette; otherwise returns false.
bool isCopyOf (const QPalette &p) const
Returns true if this palette and p are copies of each other, i.e.
bool isEqual (ColorGroup cr1, ColorGroup cr2) const
Returns true (usually quickly) if color group cg1 is equal to cg2; otherwise returns false.
const QBrush & light () const
Returns the light brush of the current color group.
const QBrush & link () const
Returns the unvisited link text brush of the current color group.
const QBrush & linkVisited () const
Returns the visited link text brush of the current color group.
const QBrush & mid () const
Returns the mid brush of the current color group.
const QBrush & midlight () const
Returns the midlight brush of the current color group.
operator QVariant () const
Returns the palette as a QVariant.
bool operator!= (const QPalette &p) const
Returns true (slowly) if this palette is different from p; otherwise returns false (usually quickly).
QPalette & operator= (const QPalette &palette)
Assigns p to this palette and returns a reference to this palette.
bool operator== (const QPalette &p) const
Returns true (usually quickly) if this palette is equal to p; otherwise returns false (slowly).
QPalette ()
Constructs a palette object that uses the application's default palette.
QPalette (const QColor &button)
Constructs a palette from the button color.
QPalette (Qt::GlobalColor button)
Constructs a palette from the button color.
QPalette (const QColor &button, const QColor &window)
Constructs a palette from a button color and a window.
QPalette (const QBrush &windowText, const QBrush &button, const QBrush &light, const QBrush &dark, const QBrush &mid, const QBrush &text, const QBrush &bright_text, const QBrush &base, const QBrush &window)
Constructs a palette.
QPalette (const QColor &windowText, const QColor &window, const QColor &light, const QColor &dark, const QColor &mid, const QColor &text, const QColor &base)
QPalette (const QPalette &palette)
Constructs a copy of p.
QPalette resolve (const QPalette &) const
Returns a new QPalette that has attributes copied from other.
uint resolve () const
void resolve (uint mask)
int serialNumber () const
Returns a number that identifies the contents of this QPalette object.
void setBrush (ColorRole cr, const QBrush &brush)
Sets the brush for the given color role to the specified brush for all groups in the palette.
void setBrush (ColorGroup cg, ColorRole cr, const QBrush &brush)
Sets the brush in the specified color group, used for the given color role, to brush.
void setColor (ColorGroup cg, ColorRole cr, const QColor &color)
Sets the color in the specified color group, used for the given color role, to the specified solid color.
void setColor (ColorRole cr, const QColor &color)
Sets the color used for the given color role, in all color groups, to the specified solid color.
void setColorGroup (ColorGroup cr, const QBrush &windowText, const QBrush &button, const QBrush &light, const QBrush &dark, const QBrush &mid, const QBrush &text, const QBrush &bright_text, const QBrush &base, const QBrush &window)
Sets a the group at cg.
void setCurrentColorGroup (ColorGroup cg)
Set the palette's current color group to cg.
const QBrush & shadow () const
Returns the shadow brush of the current color group.
const QBrush & text () const
Returns the text foreground brush of the current color group.
const QBrush & toolTipBase () const
Returns the tool tip base brush of the current color group.
const QBrush & toolTipText () const
Returns the tool tip text brush of the current color group.
const QBrush & window () const
Returns the window (general background) brush of the current color group.
const QBrush & windowText () const
Returns the window text (general foreground) brush of the current color group.
~QPalette ()
Destroys the palette.
Private Functions
void detach ()
void init ()
void setColorGroup (ColorGroup cr, const QBrush &windowText, const QBrush &button, const QBrush &light, const QBrush &dark, const QBrush &mid, const QBrush &text, const QBrush &bright_text, const QBrush &base, const QBrush &alternate_base, const QBrush &window, const QBrush &midlight, const QBrush &button_text, const QBrush &shadow, const QBrush &highlight, const QBrush &highlighted_text, const QBrush &link, const QBrush &link_visited)
void setColorGroup (ColorGroup cr, const QBrush &windowText, const QBrush &button, const QBrush &light, const QBrush &dark, const QBrush &mid, const QBrush &text, const QBrush &bright_text, const QBrush &base, const QBrush &alternate_base, const QBrush &window, const QBrush &midlight, const QBrush &button_text, const QBrush &shadow, const QBrush &highlight, const QBrush &highlighted_text, const QBrush &link, const QBrush &link_visited, const QBrush &toolTipBase, const QBrush &toolTipText)
Properties
uint current_group: 4
QPalettePrivate * d
uint resolve_mask: 28
Friends
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &s, const QPalette &p)
Writes the palette, p to the stream s and returns a reference to the stream.
Related Functions
(Note that these are not member functions.)
QDataStream & operator>> (QDataStream &s, QPalette &p)
Reads a palette from the stream, s into the palette p, and returns a reference to the stream.
Detailed Description
The QPalette class contains color groups for each widget state.
A palette consists of three color groups: Active, Disabled, and Inactive. All widgets in Qt contain a palette and use their palette to draw themselves. This makes the user interface easily configurable and easier to keep consistent.
If you create a new widget we strongly recommend that you use the colors in the palette rather than hard-coding specific colors.
The color groups:
The Active group is used for the window that has keyboard focus.
The Inactive group is used for other windows.
The Disabled group is used for widgets (not windows) that are disabled for some reason.
Both active and inactive windows can contain disabled widgets. (Disabled widgets are often called inaccessible or grayed out.)
In most styles, Active and Inactive look the same.
Colors and brushes can be set for particular roles in any of a palette's color groups with setColor() and setBrush(). A color group contains a group of colors used by widgets for drawing themselves. We recommend that widgets use color group roles from the palette such as "foreground" and "base" rather than literal colors like "red" or "turquoise". The color roles are enumerated and defined in the ColorRole documentation.
We strongly recommend that you use the default palette of the current style (returned by QApplication::palette()) and modify that as necessary. This is done by Qt's widgets when they are drawn.
To modify a color group you call the functions setColor() and setBrush(), depending on whether you want a pure color or a pixmap pattern.
There are also corresponding color() and brush() getters, and a commonly used convenience function to get the ColorRole for the current ColorGroup: window(), windowText(), base(), etc.
You can copy a palette using the copy constructor and test to see if two palettes are identical using isCopyOf().
QPalette is optimized by the use of implicit sharing, so it is very efficient to pass QPalette objects as arguments.
Warning
Some styles do not use the palette for all drawing, for instance, if they make use of native theme engines. This is the case for both the Windows XP, Windows Vista, and the Mac OS X styles.
See also
QApplication::setPalette(), QWidget::setPalette(), QColor
Definition at line 61 of file qpalette.h.
Enumerations
ColorGroup
enum QPalette::ColorGroup
Disabled
Active
Inactive
Normal synonym for Active
All
NColorGroups
Current
Enumerator
Active
Disabled
Inactive
NColorGroups
Current
All
Normal
Definition at line 92 of file qpalette.h.
 { Active, Disabled, Inactive, NColorGroups, Current, All, Normal = Active };
ColorRole
enum QPalette::ColorRole
The ColorRole enum defines the different symbolic color roles used in current GUIs.
Color Roles
The central roles are:
Window A general background color.
Background This value is obsolete. Use Window instead.
WindowText A general foreground color.
Foreground This value is obsolete. Use WindowText instead.
Base Used mostly as the background color for text entry widgets, but can also be used for other painting - such as the background of combobox drop down lists and toolbar handles. It is usually white or another light color.
AlternateBase Used as the alternate background color in views with alternating row colors (see QAbstractItemView::setAlternatingRowColors()).
ToolTipBase Used as the background color for QToolTip and QWhatsThis. Tool tips use the Inactive color group of QPalette, because tool tips are not active windows.
ToolTipText Used as the foreground color for QToolTip and QWhatsThis. Tool tips use the Inactive color group of QPalette, because tool tips are not active windows.
Text The foreground color used with Base. This is usually the same as the WindowText, in which case it must provide good contrast with Window and Base.
Button The general button background color. This background can be different from Window as some styles require a different background color for buttons.
ButtonText A foreground color used with the Button color.
BrightText A text color that is very different from WindowText, and contrasts well with e.g. Dark. Typically used for text that needs to be drawn where Text or WindowText would give poor contrast, such as on pressed push buttons. Note that text colors can be used for things other than just words; text colors are usually used for text, but it's quite common to use the text color roles for lines, icons, etc.
There are some color roles used mostly for 3D bevel and shadow effects. All of these are normally derived from Window, and used in ways that depend on that relationship. For example, buttons depend on it to make the bevels look attractive, and Motif scroll bars depend on Mid to be slightly different from Window.
Light Lighter than Button color.
Midlight Between Button and Light.
Dark Darker than Button.
Mid Between Button and Dark.
Shadow A very dark color. By default, the shadow color is Qt::black.
Selected (marked) items have two roles:
Highlight A color to indicate a selected item or the current item. By default, the highlight color is Qt::darkBlue.
HighlightedText A text color that contrasts with Highlight. By default, the highlighted text color is Qt::white.
There are two color roles related to hyperlinks:
Link A text color used for unvisited hyperlinks. By default, the link color is Qt::blue.
LinkVisited A text color used for already visited hyperlinks. By default, the linkvisited color is Qt::magenta.
Note that we do not use the Link and LinkVisited roles when rendering rich text in Qt, and that we recommend that you use CSS and the QTextDocument::setDefaultStyleSheet() function to alter the appearance of links. For example:
    QTextBrowser browser;
    QColor linkColor(Qt::red);
    QString sheet = QString::fromLatin1("a { text-decoration: underline; color: %1 }").arg(linkColor.name());
    browser.document()->setDefaultStyleSheet(sheet);
NoRole No role; this special role is often used to indicate that a role has not been assigned.
NColorRoles
Enumerator
WindowText
Button
Light
Midlight
Dark
Mid
Text
BrightText
ButtonText
Base
Window
Shadow
Highlight
HighlightedText
Link
LinkVisited
AlternateBase
NoRole
ToolTipBase
ToolTipText
NColorRoles
Foreground
Background
Definition at line 93 of file qpalette.h.
                    { WindowText, Button, Light, Midlight, Dark, Mid,
                      Text, BrightText, ButtonText, Base, Window, Shadow,
                      Highlight, HighlightedText,
                      Link, LinkVisited, // ### Qt 5: remove
                      AlternateBase,
                      NoRole, // ### Qt 5: value should be 0 or -1
                      ToolTipBase, ToolTipText,
                      NColorRoles = ToolTipText + 1,
                      Foreground = WindowText, Background = Window // ### Qt 5: remove
                    };
Constructors and Destructors
QPalette() [1/7]
QPalette::QPalette ()
Constructs a palette object that uses the application's default palette.
See also
QApplication::setPalette(), QApplication::palette()
Definition at line 673 of file qpalette.cpp.
Referenced by operator>>(), qt_mix_colors(), and setBrush().
     : d(QApplication::palette().d),
       current_group(Active),
       resolve_mask(0)
 {
     d->ref.ref();
 }
QPalette() [2/7]
QPalette::QPalette (const QColor & button)
Constructs a palette from the button color.
The other colors are automatically calculated, based on this color. Window will be the button color as well.
Definition at line 713 of file qpalette.cpp.
 {
     init();
     qt_palette_from_color(*this, button);
 }
QPalette() [3/7]
QPalette::QPalette (Qt::GlobalColor button)
Constructs a palette from the button color.
The other colors are automatically calculated, based on this color. Window will be the button color as well.
Definition at line 724 of file qpalette.cpp.
 {
     init();
     qt_palette_from_color(*this, button);
 }
QPalette() [4/7]
QPalette::QPalette (const QColor & button, const QColor & window)
Constructs a palette from a button color and a window.
The other colors are automatically calculated, based on these colors.
Definition at line 770 of file qpalette.cpp.
 {
     init();
     QColor bg = window, btn = button, fg, base, disfg;
     int h, s, v;
     bg.getHsv(&h, &s, &v);
     if(v > 128) {
         fg   = Qt::black;
         base = Qt::white;
         disfg = Qt::darkGray;
     } else {
         fg   = Qt::white;
         base = Qt::black;
         disfg = Qt::darkGray;
     }
     //inactive and active are identical
     setColorGroup(Inactive, QBrush(fg), QBrush(btn), QBrush(btn.lighter(150)), QBrush(btn.darker()),
                   QBrush(btn.darker(150)), QBrush(fg), QBrush(Qt::white), QBrush(base),
                   QBrush(bg));
     setColorGroup(Active, QBrush(fg), QBrush(btn), QBrush(btn.lighter(150)), QBrush(btn.darker()),
                   QBrush(btn.darker(150)), QBrush(fg), QBrush(Qt::white), QBrush(base),
                   QBrush(bg));
     setColorGroup(Disabled, QBrush(disfg), QBrush(btn), QBrush(btn.lighter(150)),
                   QBrush(btn.darker()), QBrush(btn.darker(150)), QBrush(disfg),
                   QBrush(Qt::white), QBrush(base), QBrush(bg));
 }
QPalette() [5/7]
QPalette::QPalette (const QBrush & windowText, const QBrush & button, const QBrush & light, const QBrush & dark, const QBrush & mid, const QBrush & text, const QBrush & bright_text, const QBrush & base, const QBrush & window)
Constructs a palette.
You can pass either brushes, pixmaps or plain colors for windowText, button, light, dark, mid, text, bright_text, base and window.
See also
QBrush
Definition at line 737 of file qpalette.cpp.
 {
     init();
     setColorGroup(All, windowText, button, light, dark, mid, text, bright_text,
                   base, window);
 }
QPalette() [6/7]
QPalette::QPalette (const QColor & windowText, const QColor & window, const QColor & light, const QColor & dark, const QColor & mid, const QColor & text, const QColor & base)
Constructs a palette with the specified windowText, window, light, dark, mid, text, and base colors. The button color will be set to the window color.
Definition at line 755 of file qpalette.cpp.
 {
     init();
     setColorGroup(All, QBrush(windowText), QBrush(window), QBrush(light),
                   QBrush(dark), QBrush(mid), QBrush(text), QBrush(light),
                   QBrush(base), QBrush(window));
 }
QPalette() [7/7]
QPalette::QPalette (const QPalette & p)
Constructs a copy of p.
This constructor is fast thanks to implicit sharing.
Definition at line 802 of file qpalette.cpp.
 {
     d = p.d;
     d->ref.ref();
     resolve_mask = p.resolve_mask;
     current_group = p.current_group;
 }
~QPalette()
QPalette::~QPalette ()
Destroys the palette.
Definition at line 813 of file qpalette.cpp.
 {
     if(!d->ref.deref())
         delete d;
 }
Functions
alternateBase()
const QBrush & QPalette::alternateBase () const inline
Returns the alternate base brush of the current color group.
See also
ColorRole brush()
Definition at line 131 of file qpalette.h.
Referenced by QWindowsVistaStyle::drawPrimitive().
 { return brush(AlternateBase); }
background()
const QBrush & QPalette::background () const inline
Use window() instead.
Definition at line 134 of file qpalette.h.
Referenced by QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QWindowsCEStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QComboMenuDelegate::paint(), QPlainTextEdit::paintEvent(), QWindowsStyle::polish(), qt_plastique_draw_handle(), qt_plastique_drawFrame(), qt_plastique_drawShadedPanel(), qt_set_windows_color_resources(), setBrush(), QInputContext::standardFormat(), and QCleanlooksStyle::styleHint().
 { return brush(Window); }
base()
const QBrush & QPalette::base () const inline
Returns the base brush of the current color group.
See also
ColorRole brush()
Definition at line 130 of file qpalette.h.
Referenced by QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QMotifStyle::drawControl(), QWindowsCEStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QWizardHeader::paintEvent(), QWindowsXPStyle::polish(), QWindowsVistaStyle::polish(), QPalette(), qt_palette_from_color(), qt_set_windows_color_resources(), setBrush(), and QGtkStyle::standardPalette().
 { return brush(Base); }
brightText()
const QBrush & QPalette::brightText () const inline
Returns the bright text foreground brush of the current color group.
See also
ColorRole brush()
Definition at line 137 of file qpalette.h.
Referenced by QWindowsCEStyle::drawPrimitive(), qt_set_windows_color_resources(), and setBrush().
 { return brush(BrightText); }
brush() [1/2]
const QBrush & QPalette::brush (ColorGroup group, ColorRole role) const
Returns the brush in the specified color group, used for the given color role.
See also
color() setBrush() ColorRole
Definition at line 874 of file qpalette.cpp.
Referenced by QLineControl::draw(), QItemDelegate::drawBackground(), QWindowsCEStyle::drawComplexControl(), QCommonStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QCommonStyle::drawControl(), QCDEStyle::drawControl(), QWindowsMobileStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QStyleSheetStyle::drawControl(), QItemDelegate::drawDisplay(), QCleanlooksStyle::drawItemText(), QStyle::drawItemText(), QTextDocumentLayoutPrivate::drawListItem(), QWindowsMobileStylePrivate::drawPanelItemViewSelected(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QStyleSheetStyle::drawPrimitive(), QCalendarModel::formatForCell(), QTextControl::getPaintContext(), QPainter::initFrom(), QApplicationPrivate::initializeWidgetPaletteHash(), QWidgetPrivate::isBackgroundInherited(), QDecorationDefault::paint(), QDecorationWindows::paintButton(), QDecorationDefault::paintButton(), QGraphicsView::paintEvent(), QMotifStyle::polish(), qDrawPlainRect(), qt_mac_display_change_callbk(), QWidget::testAttribute(), QDirectFBWindowSurface::updateIsOpaque(), and QWidgetPrivate::updateIsOpaque().
 {
     Q_ASSERT(cr < NColorRoles);
     if(gr >= (int)NColorGroups) {
         if(gr == Current) {
             gr = (ColorGroup)current_group;
         } else {
             qWarning("QPalette::brush: Unknown ColorGroup: %d", (int)gr);
             gr = Active;
         }
     }
     return d->br[gr][cr];
 }
brush() [2/2]
const QBrush & QPalette::brush (ColorRole role) const inline
Returns the brush that has been set for the given color role in the current ColorGroup.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
color() setBrush() ColorRole
Definition at line 122 of file qpalette.h.
Referenced by brush().
 { return brush(Current, cr); }
button()
const QBrush & QPalette::button () const inline
Returns the button brush of the current color group.
See also
ColorRole brush()
Definition at line 125 of file qpalette.h.
Referenced by QCommonStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QStyleHelper::drawDial(), QWindowsCEStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QWindowsMobileStylePrivate::drawScrollbarGrip(), QWindowsMobileStylePrivate::drawScrollbarGroove(), QWindowsMobileStylePrivate::drawScrollbarHandleDown(), QWindowsMobileStylePrivate::drawScrollbarHandleUp(), QWindowsMobileStylePrivate::drawTabBarTab(), QWindowsCEStylePrivate::drawWinCEButton(), QWindowsCEStylePrivate::drawWinCEPanel(), QWindowsMobileStyle::polish(), qDrawPlainRect(), qDrawWinButton(), QPalette(), qt_cleanlooks_draw_mdibutton(), qt_palette_from_color(), qt_plastique_drawFrame(), qt_plastique_drawShadedPanel(), qt_set_windows_color_resources(), and setBrush().
 { return brush(Button); }
buttonText()
const QBrush & QPalette::buttonText () const inline
Returns the button text foreground brush of the current color group.
See also
ColorRole brush()
Definition at line 138 of file qpalette.h.
Referenced by QPlastiqueStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QStyleSheetStyle::drawControl(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QCommandLinkButton::paintEvent(), and setBrush().
 { return brush(ButtonText); }
cacheKey()
qint64 QPalette::cacheKey () const
Returns a number that identifies the contents of this QPalette object.
Distinct QPalette objects can have the same key if they refer to the same contents.
The cacheKey() will change when the palette is altered.
Definition at line 1093 of file qpalette.cpp.
Referenced by QPixmapIconEngine::pixmap(), and QStyleHelper::uniqueName().
 {
     return (((qint64) d->ser_no) << 32) | ((qint64) (d->detach_no));
 }
color() [1/2]
const QColor & QPalette::color (ColorGroup group, ColorRole role) const inline
Returns the color in the specified color group, used for the given color role.
See also
brush() setColor() ColorRole
Definition at line 107 of file qpalette.h.
Referenced by brushFromData(), QCss::Declaration::brushValue(), QCss::Declaration::brushValues(), colorFromData(), QCss::Declaration::colorValue(), QCss::Declaration::colorValues(), QEgl::createSurface(), QGraphicsTextItem::defaultTextColor(), QMdiSubWindowPrivate::desktopPalette(), QTextDocumentLayoutPrivate::drawBlock(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QCDEStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QMacStyle::drawControl(), QItemDelegate::drawDisplay(), QItemDelegate::drawFocus(), QTextDocumentLayoutPrivate::drawFrame(), QWindowsCEStyle::drawItemText(), QPlastiqueStyle::drawPrimitive(), QTreeView::drawRow(), QLCDNumberPrivate::drawSegment(), QScriptEdit::extraAreaPaintEvent(), QCommonStyle::generatedIconPixmap(), QDeclarativeTextEditPrivate::init(), QDeclarativeTextInputPrivate::init(), QApplicationPrivate::initializeWidgetPaletteHash(), QAxClientSite::Invoke(), QAccessibleWidgetEx::invokeMethodEx(), QApplication::isLeftToRight(), QDecorationWindows::paint(), QDecorationStyled::paint(), QDecorationDefault::paint(), QDecorationWindows::paintButton(), QLabel::paintEvent(), QCalToolButton::paintEvent(), QmlJSDebugger::ColorPickerTool::pickColor(), QMotifStyle::polish(), qDrawShadeLine(), QRenderRule::QRenderRule(), qt_plastique_draw_handle(), qt_plastique_drawFrame(), qt_set_windows_color_resources(), QWorkspaceTitleBarPrivate::readColors(), QItemDelegate::selected(), setBrush(), QGraphicsTextItem::setDefaultTextColor(), QApplicationPrivate::setSystemPalette(), QPlastiqueStyle::standardPalette(), QMotifStyle::standardPixmap(), QCommonStyle::styleHint(), QWindowsVistaStyle::styleHint(), QWidget::testAttribute(), and QToolBoxPrivate::updateTabs().
     { return brush(cg, cr).color(); }
color() [2/2]
const QColor & QPalette::color (ColorRole role) const inline
Returns the color that has been set for the given color role in the current ColorGroup.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
brush() ColorRole
Definition at line 121 of file qpalette.h.
Referenced by color().
 { return color(Current, cr); }
currentColorGroup()
ColorGroup QPalette::currentColorGroup () const inline
Returns the palette's current color group.
Definition at line 104 of file qpalette.h.
Referenced by QCleanlooksStyle::drawControl(), QMacStyle::drawPrimitive(), QMacStylePrivate::initComboboxBdi(), QMacStylePrivate::initHIThemePushButton(), and QLineEdit::paintEvent().
 { return static_cast<ColorGroup>(current_group); }
dark()
const QBrush & QPalette::dark () const inline
Returns the dark brush of the current color group.
See also
ColorRole brush()
Definition at line 127 of file qpalette.h.
Referenced by QCommonStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QStyleHelper::drawDial(), QWindowsCEStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QLCDNumberPrivate::drawSegment(), QWindowsCEStylePrivate::drawWinCEButton(), QWindowsCEStylePrivate::drawWinCEPanel(), QWindowsStyle::polish(), qDrawPlainRect(), qDrawShadeLine(), qDrawShadePanel(), qDrawShadeRect(), qDrawWinButton(), qDrawWinPanel(), qt_set_windows_color_resources(), setBrush(), and QWorkspace::sizeHint().
 { return brush(Dark); }
detach()
void QPalette::detach () private
Warning
This function is not part of the public interface.
Definition at line 953 of file qpalette.cpp.
Referenced by linkVisited(), resolve(), setBrush(), and setColorGroup().
 {
     if (d->ref != 1) {
         QPalettePrivate *x = new QPalettePrivate;
         for(int grp = 0; grp < (int)NColorGroups; grp++) {
             for(int role = 0; role < (int)NColorRoles; role++)
                 x->br[grp][role] = d->br[grp][role];
         }
         if(!d->ref.deref())
             delete d;
         d = x;
     }
     ++d->detach_no;
 }
foreground()
const QBrush & QPalette::foreground () const inline
Use windowText() instead.
Definition at line 123 of file qpalette.h.
Referenced by QCommonStyle::drawComplexControl(), QCommonStyle::drawControl(), QMotifStyle::drawControl(), QCommonStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QColorLuminancePicker::paintEvent(), qDrawPlainRect(), qt_set_windows_color_resources(), and setBrush().
 { return brush(WindowText); }
highlight()
const QBrush & QPalette::highlight () const inline
Returns the highlight brush of the current color group.
See also
ColorRole brush()
Definition at line 140 of file qpalette.h.
Referenced by QCleanlooksStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsMobileStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QStyleHelper::drawDial(), QWindowsMobileStylePrivate::drawPanelItemViewSelected(), QPlastiqueStylePrivate::drawPartialFrame(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QWindowsMobileStylePrivate::drawScrollbarHandleDown(), QWindowsMobileStylePrivate::drawScrollbarHandleUp(), QWindowsMobileStyle::generatedIconPixmap(), QFontFamilyDelegate::paint(), QWindowsStyle::polish(), QCleanlooksStyle::polish(), qt_cleanlooks_draw_mdibutton(), qt_plastique_draw_frame(), qt_set_windows_color_resources(), setBrush(), and QWindowsMobileStyle::standardPixmap().
 { return brush(Highlight); }
highlightedText()
const QBrush & QPalette::highlightedText () const inline
Returns the highlighted text brush of the current color group.
See also
ColorRole brush()
Definition at line 141 of file qpalette.h.
Referenced by QWindowsXPStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QFontFamilyDelegate::paint(), QCleanlooksStyle::polish(), setBrush(), and QWindowsMobileStyle::standardPixmap().
 { return brush(HighlightedText); }
init()
void QPalette::init () private
Warning
This function is not part of the public interface.
Definition at line 820 of file qpalette.cpp.
Referenced by QPalette().
                     {
     d = new QPalettePrivate;
     resolve_mask = 0;
     current_group = Active; //as a default..
 }
isBrushSet()
bool QPalette::isBrushSet (ColorGroup cg, ColorRole cr) const
Returns true if the ColorGroup cg and ColorRole cr has been set previously on this palette; otherwise returns false.
Since
4.2
See also
setBrush()
Definition at line 944 of file qpalette.cpp.
Referenced by QGroupBox::initStyleOption().
 {
     Q_UNUSED(cg);
     return (resolve_mask & (1<<cr));
 }
isCopyOf()
bool QPalette::isCopyOf (const QPalette & p) const
Returns true if this palette and p are copies of each other, i.e.
one of them was created as a copy of the other and neither was subsequently modified; otherwise returns false. This is much stricter than equality.
See also
operator=() operator==()
Definition at line 1233 of file qpalette.cpp.
Referenced by QWidgetPrivate::naturalWidgetPalette(), operator==(), and QApplicationPrivate::setPalette_helper().
 {
     return d == p.d;
 }
isEqual()
bool QPalette::isEqual (QPalette::ColorGroup group1, QPalette::ColorGroup group2) const
Returns true (usually quickly) if color group cg1 is equal to cg2; otherwise returns false.
Definition at line 1035 of file qpalette.cpp.
Referenced by QLineEdit::changeEvent(), and QWidget::event().
 {
     if(group1 >= (int)NColorGroups) {
         if(group1 == Current) {
             group1 = (ColorGroup)current_group;
         } else {
             qWarning("QPalette::brush: Unknown ColorGroup(1): %d", (int)group1);
             group1 = Active;
         }
     }
     if(group2 >= (int)NColorGroups) {
         if(group2 == Current) {
             group2 = (ColorGroup)current_group;
         } else {
             qWarning("QPalette::brush: Unknown ColorGroup(2): %d", (int)group2);
             group2 = Active;
         }
     }
     if(group1 == group2)
         return true;
     for(int role = 0; role < (int)NColorRoles; role++) {
         if(d->br[group1][role] != d->br[group2][role])
                 return false;
     }
     return true;
 }
light()
const QBrush & QPalette::light () const inline
Returns the light brush of the current color group.
See also
ColorRole brush()
Definition at line 126 of file qpalette.h.
Referenced by QCommonStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QCommonStyle::drawControl(), QWindowsMobileStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QStyleSheetStyle::drawControl(), QWindowsCEStyle::drawItemText(), QStyle::drawItemText(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QWindowsMobileStylePrivate::drawScrollbarGroove(), QLCDNumberPrivate::drawSegment(), QWindowsMobileStylePrivate::drawTabBarTab(), QWindowsCEStylePrivate::drawWinCEButton(), QWindowsCEStylePrivate::drawWinCEPanel(), QLabel::paintEvent(), qDrawPlainRect(), qDrawShadeLine(), qDrawShadePanel(), qDrawShadeRect(), qDrawWinButton(), qDrawWinPanel(), qt_plastique_draw_handle(), qt_set_windows_color_resources(), and setBrush().
 { return brush(Light); }
link()
const QBrush & QPalette::link () const inline
Returns the unvisited link text brush of the current color group.
See also
ColorRole brush()
Definition at line 142 of file qpalette.h.
Referenced by QWindowsCEStyle::drawPrimitive(), and setBrush().
 { return brush(Link); }
linkVisited()
const QBrush & QPalette::linkVisited () const inline
Returns the visited link text brush of the current color group.
See also
ColorRole brush()
Definition at line 143 of file qpalette.h.
Referenced by setBrush().
 { return brush(LinkVisited); }
mid()
const QBrush & QPalette::mid () const inline
Returns the mid brush of the current color group.
See also
ColorRole brush()
Definition at line 128 of file qpalette.h.
Referenced by QCleanlooksStyle::drawComplexControl(), QWindowsCEStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QWizardHeader::paintEvent(), qDrawPlainRect(), qDrawShadeLine(), qDrawShadeRect(), qt_set_windows_color_resources(), setBrush(), and QCleanlooksStyle::standardPalette().
 { return brush(Mid); }
midlight()
const QBrush & QPalette::midlight () const inline
Returns the midlight brush of the current color group.
See also
ColorRole brush()
Definition at line 136 of file qpalette.h.
Referenced by QWindowsCEStyle::drawComplexControl(), QWindowsCEStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QWindowsCEStylePrivate::drawWinCEButton(), QWindowsCEStylePrivate::drawWinCEPanel(), qDrawShadePanel(), qDrawWinPanel(), qt_set_windows_color_resources(), and setBrush().
 { return brush(Midlight); }
operator QVariant()
QPalette::operator QVariant () const
Returns the palette as a QVariant.
Definition at line 846 of file qpalette.cpp.
 {
     return QVariant(QVariant::Palette, this);
 }
operator!=()
bool QPalette::operator!= (const QPalette & p) const inline
Returns true (slowly) if this palette is different from p; otherwise returns false (usually quickly).
Note
The current ColorGroup is not taken into account when comparing palettes
See also
operator==()
Definition at line 159 of file qpalette.h.
Referenced by setBrush().
 { return !(operator==(p)); }
operator=()
QPalette & QPalette::operator= (const QPalette & p)
Assigns p to this palette and returns a reference to this palette.
This operation is fast thanks to implicit sharing.
Definition at line 832 of file qpalette.cpp.
 {
     p.d->ref.ref();
     resolve_mask = p.resolve_mask;
     current_group = p.current_group;
     if(!d->ref.deref())
         delete d;
     d = p.d;
     return *this;
 }
operator==()
bool QPalette::operator== (const QPalette & p) const
Returns true (usually quickly) if this palette is equal to p; otherwise returns false (slowly).
Note
The current ColorGroup is not taken into account when comparing palettes
See also
operator!=()
Definition at line 992 of file qpalette.cpp.
Referenced by setBrush().
 {
     if (isCopyOf(p))
         return true;
     for(int grp = 0; grp < (int)NColorGroups; grp++) {
         for(int role = 0; role < (int)NColorRoles; role++) {
             if(d->br[grp][role] != p.d->br[grp][role])
                 return false;
         }
     }
     return true;
 }
resolve() [1/3]
QPalette QPalette::resolve (const QPalette & other) const
Returns a new QPalette that has attributes copied from other.
Definition at line 1101 of file qpalette.cpp.
Referenced by QGtkStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QGtkStyle::drawControl(), QGtkStyle::drawPrimitive(), QComboMenuDelegate::getStyleOption(), QGraphicsWidgetPrivate::naturalWidgetPalette(), QWidgetPrivate::naturalWidgetPalette(), QGtkStyle::polish(), QWidgetPrivate::propagatePaletteChange(), QGraphicsWidgetPrivate::resolvePalette(), QGraphicsScenePrivate::resolvePalette(), QWidgetPrivate::resolvePalette(), QGraphicsWidget::setPalette(), QGraphicsScene::setPalette(), QWidget::setPalette(), QGraphicsWidgetPrivate::setPalette_helper(), QGraphicsScenePrivate::setPalette_helper(), QWidgetPrivate::setPalette_helper(), QGraphicsWidgetPrivate::updatePalette(), and QGraphicsScenePrivate::updatePalette().
 {
     if ((*this == other && resolve_mask == other.resolve_mask)
         || resolve_mask == 0) {
         QPalette o = other;
         o.resolve_mask = resolve_mask;
         return o;
     }
     QPalette palette(*this);
     palette.detach();
     for(int role = 0; role < (int)NColorRoles; role++)
         if (!(resolve_mask & (1<<role)))
             for(int grp = 0; grp < (int)NColorGroups; grp++)
                 palette.d->br[grp][role] = other.d->br[grp][role];
     return palette;
 }
resolve() [2/3]
uint QPalette::resolve () const inline
Warning
This function is not part of the public interface.
Definition at line 166 of file qpalette.h.
 { return resolve_mask; }
resolve() [3/3]
void QPalette::resolve (uint mask) inline
Warning
This function is not part of the public interface.
Definition at line 167 of file qpalette.h.
 { resolve_mask = mask; }
serialNumber()
int QPalette::serialNumber () const
Returns a number that identifies the contents of this QPalette object.
Distinct QPalette objects can only have the same serial number if they refer to the same contents (but they don't have to). Also, the serial number of a QPalette may change during the lifetime of the object.
Use cacheKey() instead.
Warning
The serial number doesn't necessarily change when the palette is altered. This means that it may be dangerous to use it as a cache key.
See also
operator==()
Definition at line 1081 of file qpalette.cpp.
 {
     return d->ser_no;
 }
setBrush() [1/2]
void QPalette::setBrush (ColorRole role, const QBrush & brush) inline
Sets the brush for the given color role to the specified brush for all groups in the palette.
See also
brush() setColor() ColorRole
Definition at line 206 of file qpalette.h.
Referenced by QGtkStylePrivate::applyCustomPaletteHash(), QRenderRule::configurePalette(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QCleanlooksStyle::drawControl(), QGtkStyle::drawControl(), QStyleSheetStyle::drawControl(), QStyleSheetStyle::drawPrimitive(), QComboMenuDelegate::getStyleOption(), QGtkStylePrivate::gtkWidgetPalette(), QApplicationPrivate::initializeWidgetPaletteHash(), QStyledItemDelegate::initStyleOption(), kdeColor(), operator>>(), QWhatsThat::paintEvent(), QHeaderView::paintSection(), QWindowsXPStyle::polish(), QMacStyle::polish(), QWindowsVistaStyle::polish(), QPlastiqueStyle::polish(), QCleanlooksStyle::polish(), QWizardPrivate::recreateLayout(), setColorGroup(), QItemDelegate::setOptions(), QTabBarPrivate::setupMovableTab(), QCleanlooksStyle::standardPalette(), QCDEStyle::standardPalette(), QPlastiqueStyle::standardPalette(), QStyle::standardPalette(), QMotifStyle::standardPalette(), QWidget::testAttribute(), and QCalendarTextNavigator::updateDateLabel().
 { setBrush(All, acr, abrush); }
setBrush() [2/2]
void QPalette::setBrush (ColorGroup group, ColorRole role, const QBrush & brush)
Sets the brush in the specified color group, used for the given color role, to brush.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
brush() setColor() ColorRole
Definition at line 912 of file qpalette.cpp.
 {
     Q_ASSERT(cr < NColorRoles);
     detach();
     if(cg >= (int)NColorGroups) {
         if(cg == All) {
             for(int i = 0; i < (int)NColorGroups; i++)
                 d->br[i][cr] = b;
             resolve_mask |= (1<<cr);
             return;
         } else if(cg == Current) {
             cg = (ColorGroup)current_group;
         } else {
             qWarning("QPalette::setBrush: Unknown ColorGroup: %d", (int)cg);
             cg = Active;
         }
     }
     d->br[cg][cr] = b;
     resolve_mask |= (1<<cr);
 }
setColor() [1/2]
void QPalette::setColor (ColorGroup group, ColorRole role, const QColor & color) inline
Sets the color in the specified color group, used for the given color role, to the specified solid color.
See also
setBrush() color() ColorRole
Definition at line 201 of file qpalette.h.
Referenced by QMdiSubWindowPrivate::desktopPalette(), QWindowsCEStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QStyleSheetStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QWindowsMobileStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), QWindowsCEStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QDeclarativeTextEditPrivate::init(), QApplicationPrivate::initializeWidgetPaletteHash(), QTabBar::initStyleOption(), QApplication::isLeftToRight(), QAxServerBase::OnAmbientPropertyChange(), QDecorationStyled::paint(), QDeclarativeText::paint(), QCommandLinkButton::paintEvent(), QLabel::paintEvent(), QCalToolButton::paintEvent(), QStaticTextPrivate::paintText(), QMotifStyle::polish(), QMacStyle::polish(), QWindowsVistaStyle::polish(), QWindowsMobileStyle::polish(), printPage(), QBalloonTip::QBalloonTip(), QApplicationPrivate::qt_mac_apply_settings(), qt_mix_colors(), qt_set_windows_color_resources(), QWorkspaceTitleBarPrivate::readColors(), readV1ColorGroup(), QWizardPrivate::recreateLayout(), QDeclarativeTextEdit::setColor(), QGraphicsTextItem::setDefaultTextColor(), QScriptDebuggerCodeFinderWidget::setOK(), QDeclarativeTextInput::setSelectedTextColor(), QDeclarativeTextEdit::setSelectedTextColor(), QDeclarativeTextInput::setSelectionColor(), QDeclarativeTextEdit::setSelectionColor(), QApplicationPrivate::setSystemPalette(), QGtkStyle::standardPalette(), QWindowsCEStyle::standardPalette(), QMacStyle::standardPalette(), QWindowsMobileStyle::standardPalette(), QWidget::testAttribute(), QDeclarativeTextPrivate::textDocumentImage(), QToolBoxPrivate::updateTabs(), and QApplicationPrivate::x11_apply_settings().
 { setBrush(acg, acr, QBrush(acolor)); }
setColor() [2/2]
void QPalette::setColor (ColorRole role, const QColor & color) inline
Sets the color used for the given color role, in all color groups, to the specified solid color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
brush() setColor() ColorRole
Definition at line 204 of file qpalette.h.
 { setColor(All, acr, acolor); }
setColorGroup() [1/3]
void QPalette::setColorGroup (ColorGroup cg, const QBrush & windowText, const QBrush & button, const QBrush & light, const QBrush & dark, const QBrush & mid, const QBrush & text, const QBrush & bright_text, const QBrush & base, const QBrush & window)
Sets a the group at cg.
You can pass either brushes, pixmaps or plain colors for windowText, button, light, dark, mid, text, bright_text, base and window.
See also
QBrush
Definition at line 1246 of file qpalette.cpp.
Referenced by QPalette(), qt_mix_colors(), qt_palette_from_color(), qt_set_windows_color_resources(), and setColorGroup().
 {
     QBrush alt_base = QBrush(qt_mix_colors(base.color(), button.color()));
     QBrush mid_light = QBrush(qt_mix_colors(button.color(), light.color()));
     QColor toolTipBase(255, 255, 220);
     QColor toolTipText(0, 0, 0);
     setColorGroup(cg, windowText, button, light, dark, mid, text, bright_text, base,
                   alt_base, window, mid_light, text,
                   QBrush(Qt::black), QBrush(Qt::darkBlue), QBrush(Qt::white),
                   QBrush(Qt::blue), QBrush(Qt::magenta), QBrush(toolTipBase),
                   QBrush(toolTipText));
     resolve_mask &= ~(1 << Highlight);
     resolve_mask &= ~(1 << HighlightedText);
     resolve_mask &= ~(1 << LinkVisited);
     resolve_mask &= ~(1 << Link);
 }
setColorGroup() [2/3]
void QPalette::setColorGroup (ColorGroup cg, const QBrush & foreground, const QBrush & button, const QBrush & light, const QBrush & dark, const QBrush & mid, const QBrush & text, const QBrush & bright_text, const QBrush & base, const QBrush & alternate_base, const QBrush & background, const QBrush & midlight, const QBrush & button_text, const QBrush & shadow, const QBrush & highlight, const QBrush & highlighted_text, const QBrush & link, const QBrush & link_visited) private
Warning
This function is not part of the public interface.
Definition at line 1271 of file qpalette.cpp.
 {
     setColorGroup(cg, foreground, button, light, dark, mid,
                   text, bright_text, base, alternate_base, background,
                   midlight, button_text, shadow, highlight, highlighted_text,
                   link, link_visited, background, foreground);
 }
setColorGroup() [3/3]
void QPalette::setColorGroup (ColorGroup cg, const QBrush & foreground, const QBrush & button, const QBrush & light, const QBrush & dark, const QBrush & mid, const QBrush & text, const QBrush & bright_text, const QBrush & base, const QBrush & alternate_base, const QBrush & background, const QBrush & midlight, const QBrush & button_text, const QBrush & shadow, const QBrush & highlight, const QBrush & highlighted_text, const QBrush & link, const QBrush & link_visited, const QBrush & toolTipBase, const QBrush & toolTipText) private
Warning
This function is not part of the public interface.
Definition at line 1287 of file qpalette.cpp.
 {
     detach();
     setBrush(cg, WindowText, foreground);
     setBrush(cg, Button, button);
     setBrush(cg, Light, light);
     setBrush(cg, Dark, dark);
     setBrush(cg, Mid, mid);
     setBrush(cg, Text, text);
     setBrush(cg, BrightText, bright_text);
     setBrush(cg, Base, base);
     setBrush(cg, AlternateBase, alternate_base);
     setBrush(cg, Window, background);
     setBrush(cg, Midlight, midlight);
     setBrush(cg, ButtonText, button_text);
     setBrush(cg, Shadow, shadow);
     setBrush(cg, Highlight, highlight);
     setBrush(cg, HighlightedText, highlighted_text);
     setBrush(cg, Link, link);
     setBrush(cg, LinkVisited, link_visited);
     setBrush(cg, ToolTipBase, toolTipBase);
     setBrush(cg, ToolTipText, toolTipText);
 }
setCurrentColorGroup()
void QPalette::setCurrentColorGroup (ColorGroup cg) inline
Set the palette's current color group to cg.
Definition at line 105 of file qpalette.h.
Referenced by QTableViewPrivate::drawCell(), QWindowsCEStyle::drawComplexControl(), QCommonStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QMacStyle::drawControl(), QPlastiqueStyle::drawPrimitive(), QTreeView::drawRow(), QScriptEdit::extraAreaPaintEvent(), QComboMenuDelegate::getStyleOption(), QMenuBar::initStyleOption(), QMenu::initStyleOption(), QGraphicsWidget::initStyleOption(), QListView::paintEvent(), QTabBar::paintEvent(), QWorkspaceTitleBar::paintEvent(), QGraphicsWidget::paintWindowFrame(), QWidget::setForegroundRole(), and QMdiSubWindowPrivate::titleBarOptions().
 { current_group = cg; }
shadow()
const QBrush & QPalette::shadow () const inline
Returns the shadow brush of the current color group.
See also
ColorRole brush()
Definition at line 139 of file qpalette.h.
Referenced by QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QWindowsMobileStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QWindowsCEStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QWindowsMobileStylePrivate::drawScrollbarHandleDown(), QWindowsMobileStylePrivate::drawScrollbarHandleUp(), QWindowsMobileStylePrivate::drawTabBarTab(), QWindowsCEStylePrivate::drawWinCEButton(), QWindowsCEStylePrivate::drawWinCEPanel(), qDrawShadePanel(), qDrawWinButton(), qDrawWinPanel(), qt_plastique_draw_frame(), setBrush(), and QWindowsMobileStyle::standardPixmap().
 { return brush(Shadow); }
text()
const QBrush & QPalette::text () const inline
Returns the text foreground brush of the current color group.
See also
ColorRole brush()
Definition at line 129 of file qpalette.h.
Referenced by QWindowsXPStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QMacStyle::drawComplexControl(), QCleanlooksStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QStyleSheetStyle::drawControl(), QTextDocumentLayoutPrivate::drawListItem(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QLineEdit::paintEvent(), qDrawPlainRect(), qt_set_windows_color_resources(), setBrush(), and QInputContext::standardFormat().
 { return brush(Text); }
toolTipBase()
const QBrush & QPalette::toolTipBase () const inline
Returns the tool tip base brush of the current color group.
Since
4.4
This brush is used by QToolTip and QWhatsThis.
Note
Tool tips use the Inactive color group of QPalette, because tool tips are not active windows.
See also
ColorRole brush()
Definition at line 132 of file qpalette.h.
Referenced by QCommonStyle::drawPrimitive(), and setColorGroup().
 { return brush(ToolTipBase); }
toolTipText()
const QBrush & QPalette::toolTipText () const inline
Returns the tool tip text brush of the current color group.
Since
4.4
This brush is used by QToolTip and QWhatsThis.
Note
Tool tips use the Inactive color group of QPalette, because tool tips are not active windows.
See also
ColorRole brush()
Definition at line 133 of file qpalette.h.
Referenced by QCommonStyle::drawPrimitive(), QWhatsThat::paintEvent(), and setColorGroup().
 { return brush(ToolTipText); }
window()
const QBrush & QPalette::window () const inline
Returns the window (general background) brush of the current color group.
See also
ColorRole brush()
Definition at line 135 of file qpalette.h.
Referenced by _q_paintItem(), QPlastiqueStyle::drawControl(), QPlastiqueStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QWindowsMobileStylePrivate::drawTabBarTab(), make_widget_eventUPP(), QDecorationStyled::paint(), and QPalette().
 { return brush(Window); }
windowText()
const QBrush & QPalette::windowText () const inline
Returns the window text (general foreground) brush of the current color group.
See also
ColorRole brush()
Definition at line 124 of file qpalette.h.
Referenced by QPlastiqueStyle::drawControl(), QMacStyle::drawControl(), and qt_graphicsItem_highlightSelected().
 { return brush(WindowText); }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & s, const QPalette & p) friend
Writes the palette, p to the stream s and returns a reference to the stream.
See also
Format of the QDataStream operators
Definition at line 1154 of file qpalette.cpp.
Referenced by setBrush().
 {
     for (int grp = 0; grp < (int)QPalette::NColorGroups; grp++) {
         if (s.version() == 1) {
             // Qt 1.x
             for (int i = 0; i < NumOldRoles; ++i)
                 s << p.d->br[grp][oldRoles[i]].color();
         } else {
             int max = QPalette::ToolTipText + 1;
             if (s.version() <= QDataStream::Qt_2_1)
                 max = QPalette::HighlightedText + 1;
             else if (s.version() <= QDataStream::Qt_4_3)
                 max = QPalette::AlternateBase + 1;
             for (int r = 0; r < max; r++)
                 s << p.d->br[grp][r];
         }
     }
     return s;
 }
operator>>()
QDataStream & operator>> (QDataStream & s, QPalette & p) related
Reads a palette from the stream, s into the palette p, and returns a reference to the stream.
See also
Format of the QDataStream operators
Definition at line 1195 of file qpalette.cpp.
Referenced by setBrush().
 {
     if(s.version() == 1) {
         p = QPalette();
         readV1ColorGroup(s, p, QPalette::Active);
         readV1ColorGroup(s, p, QPalette::Disabled);
         readV1ColorGroup(s, p, QPalette::Inactive);
     } else {
         int max = QPalette::NColorRoles;
         if (s.version() <= QDataStream::Qt_2_1) {
             p = QPalette();
             max = QPalette::HighlightedText + 1;
         } else if (s.version() <= QDataStream::Qt_4_3) {
             p = QPalette();
             max = QPalette::AlternateBase + 1;
         }
         QBrush tmp;
         for(int grp = 0; grp < (int)QPalette::NColorGroups; ++grp) {
             for(int role = 0; role < max; ++role) {
                 s >> tmp;
                 p.setBrush((QPalette::ColorGroup)grp, (QPalette::ColorRole)role, tmp);
             }
         }
     }
     return s;
 }
Properties
current_group
uint QPalette::current_group private
Definition at line 196 of file qpalette.h.
Referenced by brush(), init(), isEqual(), operator=(), operator==(), QPalette(), and setBrush().
d
QPalettePrivate* QPalette::d private
Definition at line 195 of file qpalette.h.
Referenced by brush(), cacheKey(), detach(), init(), isCopyOf(), isEqual(), operator=(), operator==(), QPalette(), resolve(), serialNumber(), setBrush(), and ~QPalette().
resolve_mask
uint QPalette::resolve_mask private
Definition at line 197 of file qpalette.h.
Referenced by init(), isBrushSet(), operator=(), QPalette(), resolve(), setBrush(), and setColorGroup().
The documentation for this class was generated from the following files:
/src/gui/kernel/qpalette.h
/src/gui/kernel/qpalette.cpp