Qt 4.8: QFileSystemEntry Class Reference
QFileSystemEntry Class Reference
#include <qfilesystementry_p.h>
Classes
struct FromInternalPath
struct FromNativePath
Public Types
typedef QString NativePath
Public Functions
QString baseName () const
void clear ()
QString completeBaseName () const
QString completeSuffix () const
QString fileName () const
QString filePath () const
bool isAbsolute () const
bool isClean () const
bool isDriveRoot () const
bool isEmpty () const
bool isRelative () const
bool isRoot () const
NativePath nativeFilePath () const
QString path () const
QFileSystemEntry ()
QFileSystemEntry (const QString &filePath)
Use this constructor when the path is supplied by user code, as it may contain a mix of '/' and the native separator.
QFileSystemEntry (const QString &filePath, FromInternalPath dummy)
Use this constructor when the path is guaranteed to be in internal format, i.
QFileSystemEntry (const NativePath &nativeFilePath, FromNativePath dummy)
QFileSystemEntry (const QString &filePath, const NativePath &nativeFilePath)
QString suffix () const
Private Functions
void findFileNameSeparators () const
void findLastSeparator () const
void resolveFilePath () const
void resolveNativeFilePath () const
Properties
QString m_filePath
qint16 m_firstDotInFileName
qint16 m_lastDotInFileName
qint16 m_lastSeparator
NativePath m_nativeFilePath
Detailed Description
Definition at line 65 of file qfilesystementry_p.h.
Typedefs
NativePath
typedef QString QFileSystemEntry::NativePath
Definition at line 72 of file qfilesystementry_p.h.
Constructors and Destructors
QFileSystemEntry() [1/5]
QFileSystemEntry::QFileSystemEntry ()
Definition at line 77 of file qfilesystementry.cpp.
Referenced by clear().
     : m_lastSeparator(0),
     m_firstDotInFileName(0),
     m_lastDotInFileName(0)
 {
 }
QFileSystemEntry() [2/5]
QFileSystemEntry::QFileSystemEntry (const QString & filePath) explicit
Use this constructor when the path is supplied by user code, as it may contain a mix of '/' and the native separator.
Warning
This function is not part of the public interface.
Definition at line 92 of file qfilesystementry.cpp.
     : m_filePath(QDir::fromNativeSeparators(filePath)),
     m_lastSeparator(-2),
     m_firstDotInFileName(-2),
     m_lastDotInFileName(0)
 {
 }
QFileSystemEntry() [3/5]
QFileSystemEntry::QFileSystemEntry (const QString & filePath, FromInternalPath dummy)
Use this constructor when the path is guaranteed to be in internal format, i.
Warning
This function is not part of the public interface. e. all directory separators are '/' and not the native separator.
Definition at line 108 of file qfilesystementry.cpp.
     : m_filePath(filePath),
     m_lastSeparator(-2),
     m_firstDotInFileName(-2),
     m_lastDotInFileName(0)
 {
 }
QFileSystemEntry() [4/5]
QFileSystemEntry::QFileSystemEntry (const NativePath & nativeFilePath, FromNativePath dummy)
Warning
This function is not part of the public interface. Use this constructor when the path comes from a native API
Definition at line 120 of file qfilesystementry.cpp.
     : m_nativeFilePath(nativeFilePath),
     m_lastSeparator(-2),
     m_firstDotInFileName(-2),
     m_lastDotInFileName(0)
 {
 }
QFileSystemEntry() [5/5]
QFileSystemEntry::QFileSystemEntry (const QString & filePath, const NativePath & nativeFilePath)
Definition at line 128 of file qfilesystementry.cpp.
     : m_filePath(QDir::fromNativeSeparators(filePath)),
     m_nativeFilePath(nativeFilePath),
     m_lastSeparator(-2),
     m_firstDotInFileName(-2),
     m_lastDotInFileName(0)
 {
 }
Functions
baseName()
QString QFileSystemEntry::baseName () const
Definition at line 211 of file qfilesystementry.cpp.
 {
     findFileNameSeparators();
     int length = -1;
     if (m_firstDotInFileName >= 0) {
         length = m_firstDotInFileName;
         if (m_lastSeparator != -1) // avoid off by one
             length--;
     }
 #if defined(Q_OS_WIN)
     if (m_lastSeparator == -1 && m_filePath.length() >= 2 && m_filePath.at(1) == QLatin1Char(':'))
         return m_filePath.mid(2, length - 2);
 #endif
     return m_filePath.mid(m_lastSeparator + 1, length);
 }
clear()
void QFileSystemEntry::clear () inline
Definition at line 102 of file qfilesystementry_p.h.
     {
         *this = QFileSystemEntry();
     }
completeBaseName()
QString QFileSystemEntry::completeBaseName () const
Definition at line 227 of file qfilesystementry.cpp.
Referenced by QLibraryPrivate::load_sys().
 {
     findFileNameSeparators();
     int length = -1;
     if (m_firstDotInFileName >= 0) {
         length = m_firstDotInFileName + m_lastDotInFileName;
         if (m_lastSeparator != -1) // avoid off by one
             length--;
     }
 #if defined(Q_OS_WIN)
     if (m_lastSeparator == -1 && m_filePath.length() >= 2 && m_filePath.at(1) == QLatin1Char(':'))
         return m_filePath.mid(2, length - 2);
 #endif
     return m_filePath.mid(m_lastSeparator + 1, length);
 }
completeSuffix()
QString QFileSystemEntry::completeSuffix () const
Definition at line 253 of file qfilesystementry.cpp.
 {
     findFileNameSeparators();
     if (m_firstDotInFileName == -1)
         return QString();
     return m_filePath.mid(qMax((qint16)0, m_lastSeparator) + m_firstDotInFileName + 1);
 }
fileName()
QString QFileSystemEntry::fileName () const
Definition at line 182 of file qfilesystementry.cpp.
Referenced by QDirIteratorPrivate::advance(), QDir::dirName(), QFileSystemEngine::fillMetaData(), and QLibraryPrivate::load_sys().
 {
     findLastSeparator();
 #if defined(Q_OS_WIN) || defined(Q_OS_SYMBIAN)
     if (m_lastSeparator == -1 && m_filePath.length() >= 2 && m_filePath.at(1) == QLatin1Char(':'))
         return m_filePath.mid(2);
 #endif
     return m_filePath.mid(m_lastSeparator + 1);
 }
filePath()
QString QFileSystemEntry::filePath () const
Definition at line 137 of file qfilesystementry.cpp.
Referenced by _q_resolveEntryAndCreateLegacyEngine_recursive(), QDir::absoluteFilePath(), QFileSystemEngine::absoluteName(), QDir::absolutePath(), QFileSystemEngine::bundleName(), QFileSystemEngine::canonicalName(), QDir::canonicalPath(), QDir::cd(), QAbstractFileEngine::create(), QFileSystemEngine::createDirectory(), QFSFileEngine::currentPath(), QDir::currentPath(), QDir::entryInfoList(), QDir::entryList(), QFSFileEngine::fileName(), QDir::filePath(), QFileSystemEngine::fillMetaData(), QFileSystemEngine::fillPermissions(), QFileInfoPrivate::getFileName(), QFileSystemEngine::getLinkTarget(), isDirPath(), QFSFileEnginePrivate::longFileName(), QDir::makeAbsolute(), QFileSystemEngine::nativeAbsoluteFilePath(), QFileInfo::operator==(), QDir::operator==(), QDirIterator::path(), QDir::path(), readLink(), QFileSystemEngine::removeDirectory(), QDirPrivate::resolveAbsoluteEntry(), resolveNativeFilePath(), and tryDriveUNCFallback().
 {
     resolveFilePath();
     return m_filePath;
 }
findFileNameSeparators()
void QFileSystemEntry::findFileNameSeparators () const private
Definition at line 341 of file qfilesystementry.cpp.
Referenced by baseName(), clear(), completeBaseName(), completeSuffix(), and suffix().
 {
     if (m_firstDotInFileName == -2) {
         resolveFilePath();
         int firstDotInFileName = -1;
         int lastDotInFileName = -1;
         int lastSeparator = m_lastSeparator;
         int stop;
         if (lastSeparator < 0) {
             lastSeparator = -1;
             stop = 0;
         } else {
             stop = lastSeparator;
         }
         int i = m_filePath.size() - 1;
         for (; i >= stop; --i) {
             if (m_filePath[i].unicode() == '.') {
                 firstDotInFileName = lastDotInFileName = i;
                 break;
             } else if (m_filePath[i].unicode() == '/') {
                 lastSeparator = i;
                 break;
             }
         }
         if (lastSeparator != i) {
             for (--i; i >= stop; --i) {
                 if (m_filePath[i].unicode() == '.')
                     firstDotInFileName = i;
                 else if (m_filePath[i].unicode() == '/') {
                     lastSeparator = i;
                     break;
                 }
             }
         }
         m_lastSeparator = lastSeparator;
         m_firstDotInFileName = firstDotInFileName == -1 ? -1 : firstDotInFileName - qMax(0, lastSeparator);
         if (lastDotInFileName == -1)
             m_lastDotInFileName = -1;
         else if (firstDotInFileName == lastDotInFileName)
             m_lastDotInFileName = 0;
         else
             m_lastDotInFileName = lastDotInFileName - firstDotInFileName;
     }
 }
findLastSeparator()
void QFileSystemEntry::findLastSeparator () const private
Definition at line 327 of file qfilesystementry.cpp.
Referenced by clear(), fileName(), and path().
 {
     if (m_lastSeparator == -2) {
         resolveFilePath();
         m_lastSeparator = -1;
         for (int i = m_filePath.size() - 1; i >= 0; --i) {
             if (m_filePath[i].unicode() == '/') {
                 m_lastSeparator = i;
                 break;
             }
         }
     }
 }
isAbsolute()
bool QFileSystemEntry::isAbsolute () const
Definition at line 270 of file qfilesystementry.cpp.
Referenced by QFileSystemEngine::absoluteName(), QLibraryPrivate::load_sys(), and QFileSystemEngine::nativeAbsoluteFilePath().
 {
     resolveFilePath();
     return (!m_filePath.isEmpty() && ((m_filePath.length() >= 3
                                        && (m_filePath[0].isLetter() && m_filePath[1].unicode() == ':' && m_filePath[2].unicode() == '/'))
 #ifdef Q_OS_WIN
                                       || (m_filePath.length() >= 2 && (m_filePath.at(0) == QLatin1Char('/') && m_filePath.at(1) == QLatin1Char('/')))
 #endif
                                       ));
 }
isClean()
bool QFileSystemEntry::isClean () const
Definition at line 389 of file qfilesystementry.cpp.
Referenced by QFileSystemEngine::absoluteName(), QFileSystemEngine::nativeAbsoluteFilePath(), and QDirPrivate::resolveAbsoluteEntry().
 {
     resolveFilePath();
     int dots = 0;
     bool dotok = true; // checking for ".." or "." starts to relative paths
     bool slashok = true;
     for (QString::const_iterator iter = m_filePath.constBegin(); iter != m_filePath.constEnd(); iter++) {
         if (*iter == QLatin1Char('/')) {
             if (dots == 1 || dots == 2)
                 return false; // path contains "./" or "../"
             if (!slashok)
                 return false; // path contains "//"
             dots = 0;
             dotok = true;
             slashok = false;
         } else if (dotok) {
             slashok = true;
             if (*iter == QLatin1Char('.')) {
                 dots++;
                 if (dots > 2)
                     dotok = false;
             } else {
                 //path element contains a character other than '.', it's clean
                 dots = 0;
                 dotok = false;
             }
         }
     }
     return (dots != 1 && dots != 2); // clean if path doesn't end in . or ..
 }
isDriveRoot()
bool QFileSystemEntry::isDriveRoot () const
Definition at line 294 of file qfilesystementry.cpp.
Referenced by QFileSystemEngine::fillMetaData(), isRoot(), tryDriveUNCFallback(), and tryFindFallback().
 {
     resolveFilePath();
     return (m_filePath.length() == 3
            && m_filePath.at(0).isLetter() && m_filePath.at(1) == QLatin1Char(':')
            && m_filePath.at(2) == QLatin1Char('/'));
 }
isEmpty()
bool QFileSystemEntry::isEmpty () const
Definition at line 319 of file qfilesystementry.cpp.
Referenced by QFileSystemEngine::canonicalName(), QFileSystemEngine::currentPath(), QFSFileEnginePrivate::doStat(), QFileSystemEngine::fillMetaData(), QFSFileEnginePrivate::longFileName(), openModeToFopenMode(), and QDirPrivate::resolveAbsoluteEntry().
 {
     resolveNativeFilePath();
     return m_nativeFilePath.isEmpty();
 }
isRelative()
bool QFileSystemEntry::isRelative () const
Definition at line 263 of file qfilesystementry.cpp.
Referenced by isAbsolute(), QDir::isRelative(), QFileInfo::makeAbsolute(), QFileSystemEngine::nativeAbsoluteFilePath(), QDirPrivate::resolveAbsoluteEntry(), and resolveNativeFilePath().
 {
     resolveFilePath();
     return (m_filePath.isEmpty() || (!m_filePath.isEmpty() && (m_filePath[0].unicode() != '/')
         && (!(m_filePath.length() >= 2 && m_filePath[1].unicode() == ':'))));
 }
isRoot()
bool QFileSystemEntry::isRoot () const
Definition at line 303 of file qfilesystementry.cpp.
Referenced by QDir::absoluteFilePath(), QFileSystemEngine::canonicalName(), and QDir::isRoot().
 {
     resolveFilePath();
     if (m_filePath == QLatin1String("/")
 #if defined(Q_OS_WIN) || defined(Q_OS_SYMBIAN)
             || isDriveRoot()
 #if defined(Q_OS_WIN)
             || isUncRoot(m_filePath)
 #endif
 #endif
             )
         return true;
     return false;
 }
nativeFilePath()
QFileSystemEntry::NativePath QFileSystemEntry::nativeFilePath () const
Definition at line 143 of file qfilesystementry.cpp.
Referenced by QFileSystemEngine::absoluteName(), QFileSystemEngine::canonicalName(), QFileSystemEngine::createLink(), QFileSystemEngine::fillMetaData(), QFileSystemEngine::fillPermissions(), QFileSystemEngine::getLinkTarget(), isDirPath(), QFSFileEnginePrivate::longFileName(), QFSFileEnginePrivate::map(), QFSFileEnginePrivate::nativeHandle(), QFSFileEnginePrivate::nativeOpen(), QTemporaryFileEngine::open(), QFileSystemEngine::owner(), readLink(), readSymLink(), QFileSystemEngine::removeFile(), QFileSystemEngine::renameFile(), QFileSystemEngine::setCurrentPath(), QFileSystemEngine::setPermissions(), tryDriveUNCFallback(), and tryFindFallback().
 {
     resolveNativeFilePath();
     return m_nativeFilePath;
 }
path()
QString QFileSystemEntry::path () const
Definition at line 192 of file qfilesystementry.cpp.
Referenced by QFSFileEngine::fileName(), QFileInfoPrivate::getFileName(), QLibraryPrivate::load_sys(), and QFSFileEnginePrivate::longFileName().
 {
     findLastSeparator();
     if (m_lastSeparator == -1) {
 #if defined(Q_OS_WIN) || defined(Q_OS_SYMBIAN)
         if (m_filePath.length() >= 2 && m_filePath.at(1) == QLatin1Char(':'))
             return m_filePath.left(2);
 #endif
         return QString(QLatin1Char('.'));
     }
     if (m_lastSeparator == 0)
         return QString(QLatin1Char('/'));
 #if defined(Q_OS_WIN) || defined(Q_OS_SYMBIAN)
     if (m_lastSeparator == 2 && m_filePath.at(1) == QLatin1Char(':'))
         return m_filePath.left(m_lastSeparator + 1);
 #endif
     return m_filePath.left(m_lastSeparator);
 }
resolveFilePath()
void QFileSystemEntry::resolveFilePath () const private
Definition at line 149 of file qfilesystementry.cpp.
Referenced by clear(), filePath(), findFileNameSeparators(), findLastSeparator(), isAbsolute(), isClean(), isDriveRoot(), isRelative(), and isRoot().
 {
     if (m_filePath.isEmpty() && !m_nativeFilePath.isEmpty()) {
 #if defined(QFILESYSTEMENTRY_NATIVE_PATH_IS_UTF16)
         m_filePath = QDir::fromNativeSeparators(m_nativeFilePath);
 #ifdef Q_OS_WIN
         if (m_filePath.startsWith(QLatin1String("//?/UNC/")))
             m_filePath = m_filePath.remove(2,6);
         if (m_filePath.startsWith(QLatin1String("//?/")))
             m_filePath = m_filePath.remove(0,4);
 #endif
 #else
         m_filePath = QDir::fromNativeSeparators(QFile::decodeName(m_nativeFilePath));
 #endif
     }
 }
resolveNativeFilePath()
void QFileSystemEntry::resolveNativeFilePath () const private
Definition at line 166 of file qfilesystementry.cpp.
Referenced by clear(), isEmpty(), and nativeFilePath().
 {
     if (!m_filePath.isEmpty() && m_nativeFilePath.isEmpty()) {
 #ifdef Q_OS_WIN
         QString filePath = m_filePath;
         if (isRelative())
             filePath = fixIfRelativeUncPath(m_filePath);
         m_nativeFilePath = QFSFileEnginePrivate::longFileName(QDir::toNativeSeparators(filePath));
 #elif defined(QFILESYSTEMENTRY_NATIVE_PATH_IS_UTF16)
         m_nativeFilePath = QDir::toNativeSeparators(m_filePath);
 #else
         m_nativeFilePath = QFile::encodeName(QDir::toNativeSeparators(m_filePath));
 #endif
     }
 }
suffix()
QString QFileSystemEntry::suffix () const
Definition at line 243 of file qfilesystementry.cpp.
Referenced by QLibraryPrivate::load_sys().
 {
     findFileNameSeparators();
     if (m_lastDotInFileName == -1)
         return QString();
     return m_filePath.mid(qMax((qint16)0, m_lastSeparator) + m_firstDotInFileName + m_lastDotInFileName + 1);
 }
Properties
m_filePath
QString QFileSystemEntry::m_filePath mutable private
Definition at line 117 of file qfilesystementry_p.h.
Referenced by baseName(), completeBaseName(), completeSuffix(), fileName(), filePath(), findFileNameSeparators(), findLastSeparator(), isAbsolute(), isClean(), isDriveRoot(), isRelative(), isRoot(), path(), resolveFilePath(), resolveNativeFilePath(), and suffix().
m_firstDotInFileName
qint16 QFileSystemEntry::m_firstDotInFileName mutable private
Definition at line 121 of file qfilesystementry_p.h.
Referenced by baseName(), completeBaseName(), completeSuffix(), findFileNameSeparators(), and suffix().
m_lastDotInFileName
qint16 QFileSystemEntry::m_lastDotInFileName mutable private
Definition at line 122 of file qfilesystementry_p.h.
Referenced by completeBaseName(), findFileNameSeparators(), and suffix().
m_lastSeparator
qint16 QFileSystemEntry::m_lastSeparator mutable private
Definition at line 120 of file qfilesystementry_p.h.
Referenced by baseName(), completeBaseName(), completeSuffix(), fileName(), findFileNameSeparators(), findLastSeparator(), path(), and suffix().
m_nativeFilePath
NativePath QFileSystemEntry::m_nativeFilePath mutable private
Definition at line 118 of file qfilesystementry_p.h.
Referenced by isEmpty(), nativeFilePath(), resolveFilePath(), and resolveNativeFilePath().
The documentation for this class was generated from the following files:
/src/corelib/io/qfilesystementry_p.h
/src/corelib/io/qfilesystementry.cpp