Qt 4.8: QLineF Class Reference
QLineF Class Reference
The QLineF class provides a two-dimensional vector using floating point precision.
#include <qline.h>
Public Types
enum IntersectType { NoIntersection, BoundedIntersection, UnboundedIntersection }
Describes the intersection between two lines.
Public Functions
qreal angle () const
Returns the angle of the line in degrees.
qreal angle (const QLineF &l) const
Returns the angle (in degrees) between this line and the given line, taking the direction of the lines into account.
qreal angleTo (const QLineF &l) const
Returns the angle (in positive degrees) from this line to the given line, taking the direction of the lines into account.
qreal dx () const
Returns the horizontal component of the line's vector.
qreal dy () const
Returns the vertical component of the line's vector.
IntersectType intersect (const QLineF &l, QPointF *intersectionPoint) const
Returns a value indicating whether or not this line intersects with the given line.
bool isNull () const
Returns true if the line is not set up with valid start and end point; otherwise returns false.
qreal length () const
Returns the length of the line.
QLineF normalVector () const
Returns a line that is perpendicular to this line with the same starting point and length.
bool operator!= (const QLineF &d) const
Returns true if the given line is not the same as this line.
bool operator== (const QLineF &d) const
Returns true if the given line is the same as this line.
QPointF p1 () const
Returns the line's start point.
QPointF p2 () const
Returns the line's end point.
QPointF pointAt (qreal t) const
Returns the point at the parameterized position specified by t.
QLineF ()
Constructs a null line.
QLineF (const QPointF &pt1, const QPointF &pt2)
Constructs a line object that represents the line between p1 and p2.
QLineF (qreal x1, qreal y1, qreal x2, qreal y2)
Constructs a line object that represents the line between (x1, y1) and (x2, y2).
QLineF (const QLine &line)
Construct a QLineF object from the given integer-based line.
void setAngle (qreal angle)
Sets the angle of the line to the given angle (in degrees).
void setLength (qreal len)
Sets the length of the line to the given length.
void setLine (qreal x1, qreal y1, qreal x2, qreal y2)
Sets this line to the start in x1, y1 and end in x2, y2.
void setP1 (const QPointF &p1)
Sets the starting point of this line to p1.
void setP2 (const QPointF &p2)
Sets the end point of this line to p2.
void setPoints (const QPointF &p1, const QPointF &p2)
Sets the start point of this line to p1 and the end point of this line to p2.
QLine toLine () const
Returns an integer based copy of this line.
void translate (const QPointF &p)
Translates this line by the given offset.
void translate (qreal dx, qreal dy)
Translates this line the distance specified by dx and dy.
QLineF translated (const QPointF &p) const
Returns this line translated by the given offset.
QLineF translated (qreal dx, qreal dy) const
Returns this line translated the distance specified by dx and dy.
QLineF unitVector () const
Returns the unit vector for this line, i.e a line starting at the same point as this line with a length of 1.0.
qreal x1 () const
Returns the x-coordinate of the line's start point.
qreal x2 () const
Returns the x-coordinate of the line's end point.
qreal y1 () const
Returns the y-coordinate of the line's start point.
qreal y2 () const
Returns the y-coordinate of the line's end point.
Static Public Functions
static QLineF fromPolar (qreal length, qreal angle)
Returns a QLineF with the given length and angle.
Properties
QPointF pt1
QPointF pt2
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QLineF &line)
Writes the given line to the given stream and returns a reference to the stream.
QDataStream & operator>> (QDataStream &stream, QLineF &line)
Reads a line from the given stream into the given line and returns a reference to the stream.
Detailed Description
The QLineF class provides a two-dimensional vector using floating point precision.
A QLineF describes a finite length line (or line segment) on a two-dimensional surface. QLineF defines the start and end points of the line using floating point accuracy for coordinates. Use the toLine() function to retrieve an integer based copy of this line.
The positions of the line's start and end points can be retrieved using the p1(), x1(), y1(), p2(), x2(), and y2() functions. The dx() and dy() functions return the horizontal and vertical components of the line, respectively.
The line's length can be retrieved using the length() function, and altered using the setLength() function. Similarly, angle() and setAngle() are respectively used for retrieving and altering the angle of the line. Use the isNull() function to determine whether the QLineF represents a valid line or a null line.
The intersect() function determines the IntersectType for this line and a given line, while the angle() function returns the angle between the lines. In addition, the unitVector() function returns a line that has the same starting point as this line, but with a length of only 1, while the normalVector() function returns a line that is perpendicular to this line with the same starting point and length.
Finally, the line can be translated a given offset using the translate() function, and can be traversed using the pointAt() function.
See also
QLine, QPolygonF, QRectF
Definition at line 212 of file qline.h.
Enumerations
IntersectType
enum QLineF::IntersectType
Describes the intersection between two lines.
QLineF::UnboundedIntersection QLineF::BoundedIntersection
NoIntersection Indicates that the lines do not intersect; i.e. they are parallel.
UnboundedIntersection The two lines intersect, but not within the range defined by their lengths. This will be the case if the lines are not parallel.
intersect() will also return this value if the intersect point is within the start and end point of only one of the lines.
BoundedIntersection The two lines intersect with each other within the start and end points of each line.
See also
intersect()
Enumerator
NoIntersection
BoundedIntersection
UnboundedIntersection
Definition at line 215 of file qline.h.
 { NoIntersection, BoundedIntersection, UnboundedIntersection };
Constructors and Destructors
QLineF() [1/4]
QLineF::QLineF () inline
Constructs a null line.
Definition at line 280 of file qline.h.
Referenced by fromPolar(), normalVector(), operator>>(), and translated().
 {
 }
QLineF() [2/4]
QLineF::QLineF (const QPointF & pt1, const QPointF & pt2) inline
Constructs a line object that represents the line between p1 and p2.
Definition at line 284 of file qline.h.
     : pt1(apt1), pt2(apt2)
 {
 }
QLineF() [3/4]
QLineF::QLineF (qreal x1, qreal y1, qreal x2, qreal y2) inline
Constructs a line object that represents the line between (x1, y1) and (x2, y2).
Definition at line 289 of file qline.h.
     : pt1(x1pos, y1pos), pt2(x2pos, y2pos)
 {
 }
QLineF() [4/4]
QLineF::QLineF (const QLine & line) inline
Construct a QLineF object from the given integer-based line.
See also
toLine()
Definition at line 220 of file qline.h.
 : pt1(line.p1()), pt2(line.p2()) { }
Functions
angle() [1/2]
qreal QLineF::angle () const
Returns the angle of the line in degrees.
Since
4.4
The return value will be in the range of values from 0.0 up to but not including 360.0. The angles are measured counter-clockwise from a point on the x-axis to the right of the origin (x > 0).
See also
setAngle()
Definition at line 719 of file qline.cpp.
Referenced by adapted_angle_on_x(), QPainterPath::angleAtPercent(), angleTo(), and QDeclarativePinchArea::updatePinch().
 {
     const qreal dx = pt2.x() - pt1.x();
     const qreal dy = pt2.y() - pt1.y();
     const qreal theta = q_rad2deg(qAtan2(-dy, dx));
     const qreal theta_normalized = theta < 0 ? theta + 360 : theta;
     if (qFuzzyCompare(theta_normalized, qreal(360)))
         return qreal(0);
     else
         return theta_normalized;
 }
angle() [2/2]
qreal QLineF::angle (const QLineF & line) const
Returns the angle (in degrees) between this line and the given line, taking the direction of the lines into account.
If the lines do not intersect within their range, it is the intersection point of the extended lines that serves as origin (see QLineF::UnboundedIntersection).
When the lines are parallel, this function returns 0 if they have the same direction; otherwise it returns 180.
See also
intersect()
Definition at line 993 of file qline.cpp.
 {
     if (isNull() || l.isNull())
         return 0;
     qreal cos_line = (dx()*l.dx() + dy()*l.dy()) / (length()*l.length());
     qreal rad = 0;
     // only accept cos_line in the range [-1,1], if it is outside, use 0 (we return 0 rather than PI for those cases)
     if (cos_line >= qreal(-1.0) && cos_line <= qreal(1.0)) rad = qAcos( cos_line );
     return q_rad2deg(rad);
 }
angleTo()
qreal QLineF::angleTo (const QLineF & line) const
Returns the angle (in positive degrees) from this line to the given line, taking the direction of the lines into account.
Since
4.4
If the lines do not intersect within their range, it is the intersection point of the extended lines that serves as origin (see QLineF::UnboundedIntersection).
The returned value represents the number of degrees you need to add to this line to make it have the same angle as the given line, going counter-clockwise.
See also
intersect()
Definition at line 951 of file qline.cpp.
 {
     if (isNull() || l.isNull())
         return 0;
     const qreal a1 = angle();
     const qreal a2 = l.angle();
     const qreal delta = a2 - a1;
     const qreal delta_normalized = delta < 0 ? delta + 360 : delta;
     if (qFuzzyCompare(delta, qreal(360)))
         return 0;
     else
         return delta_normalized;
 }
dx()
qreal QLineF::dx () const inline
Returns the horizontal component of the line's vector.
Return value is positive if x2() >= x1() and negative if x2() < x1().
See also
dy(), pointAt()
Definition at line 324 of file qline.h.
Referenced by angle(), QStroker::joinPoints(), QBezier::midTangent(), normalVector(), qt_stroke_side(), setAngle(), and setLength().
 {
     return pt2.x() - pt1.x();
 }
dy()
qreal QLineF::dy () const inline
Returns the vertical component of the line's vector.
Return value is positive if y2() >= y1() and negative if y2() < y1().
See also
dx(), pointAt()
Definition at line 329 of file qline.h.
Referenced by adapted_angle_on_x(), angle(), QStroker::joinPoints(), QBezier::midTangent(), normalVector(), qt_stroke_side(), setAngle(), and setLength().
 {
     return pt2.y() - pt1.y();
 }
fromPolar()
QLineF QLineF::fromPolar (qreal length, qreal angle) static
Returns a QLineF with the given length and angle.
Since
4.4
The first point of the line will be on the origin.
Positive values for the angles mean counter-clockwise while negative values mean the clockwise direction. Zero degrees is at the 3 o'clock position.
Definition at line 774 of file qline.cpp.
 {
     const qreal angleR = q_deg2rad(angle);
     return QLineF(0, 0, qCos(angleR) * length, -qSin(angleR) * length);
 }
intersect()
QLineF::IntersectType QLineF::intersect (const QLineF & line, QPointF * intersectionPoint) const
Returns a value indicating whether or not this line intersects with the given line.
The actual intersection point is extracted to intersectionPoint (if the pointer is valid). If the lines are parallel, the intersection point is undefined.
Definition at line 813 of file qline.cpp.
Referenced by QStroker::joinPoints().
 {
     // ipmlementation is based on Graphics Gems III's "Faster Line Segment Intersection"
     const QPointF a = pt2 - pt1;
     const QPointF b = l.pt1 - l.pt2;
     const QPointF c = pt1 - l.pt1;
     const qreal denominator = a.y() * b.x() - a.x() * b.y();
     if (denominator == 0 || !qt_is_finite(denominator))
         return NoIntersection;
     const qreal reciprocal = 1 / denominator;
     const qreal na = (b.y() * c.x() - b.x() * c.y()) * reciprocal;
     if (intersectionPoint)
         *intersectionPoint = pt1 + a * na;
     if (na < 0 || na > 1)
         return UnboundedIntersection;
     const qreal nb = (a.x() * c.y() - a.y() * c.x()) * reciprocal;
     if (nb < 0 || nb > 1)
         return UnboundedIntersection;
     return BoundedIntersection;
 }
isNull()
bool QLineF::isNull () const
Returns true if the line is not set up with valid start and end point; otherwise returns false.
Definition at line 517 of file qline.cpp.
Referenced by angle(), angleTo(), QBezier::endTangent(), setLength(), and QBezier::startTangent().
 {
     return (qFuzzyCompare(pt1.x(), pt2.x()) && qFuzzyCompare(pt1.y(), pt2.y())) ? true : false;
 }
length()
qreal QLineF::length () const
Returns the length of the line.
See also
setLength()
Definition at line 698 of file qline.cpp.
Referenced by QBezier::addIfClose(), angle(), bezierAtT(), QStroker::joinPoints(), nextBezier(), QPainterPath::percentAtLength(), qt_radial_gradient_adapt_focal_point(), QRasterPaintEnginePrivate::rasterizeLine_dashed(), setAngle(), QRasterPaintEngine::stroke(), and unitVector().
 {
     qreal x = pt2.x() - pt1.x();
     qreal y = pt2.y() - pt1.y();
     return qSqrt(x*x + y*y);
 }
normalVector()
QLineF QLineF::normalVector () const inline
Returns a line that is perpendicular to this line with the same starting point and length.
See also
unitVector()
Definition at line 334 of file qline.h.
Referenced by qt_stroke_side(), and shift().
 {
     return QLineF(p1(), p1() + QPointF(dy(), -dx()));
 }
operator!=()
bool QLineF::operator!= (const QLineF & line) const inline
Returns true if the given line is not the same as this line.
A line is different from another line if their start or end points differ, or the internal order of the points is different.
Definition at line 267 of file qline.h.
 { return !(*this == d); }
operator==()
bool QLineF::operator== (const QLineF & line) const inline
Returns true if the given line is the same as this line.
A line is identical to another line if the start and end points are identical, and the internal order of the points is the same.
Definition at line 404 of file qline.h.
 {
     return pt1 == d.pt1 && pt2 == d.pt2;
 }
p1()
QPointF QLineF::p1 () const inline
Returns the line's start point.
See also
x1(), y1(), p2()
Definition at line 314 of file qline.h.
Referenced by _q_interpolate(), QPathSegments::addPath(), QCoreGraphicsPaintEngine::drawLines(), QVGPaintEngine::drawLines(), QOpenGLPaintEngine::drawLines(), QPaintEngine::drawLines(), QRasterPaintEngine::drawLines(), QIntersectionFinder::hasIntersections(), QStroker::joinPoints(), QIntersectionFinder::linesIntersect(), QMatrix::map(), normalVector(), operator<<(), operator<<(), qt_stroke_side(), QRasterPaintEnginePrivate::rasterizeLine_dashed(), QRasterPaintEngine::stroke(), and unitVector().
 {
     return pt1;
 }
p2()
QPointF QLineF::p2 () const inline
Returns the line's end point.
See also
x2(), y2(), p1()
Definition at line 319 of file qline.h.
Referenced by _q_interpolate(), QPathSegments::addPath(), QCoreGraphicsPaintEngine::drawLines(), QVGPaintEngine::drawLines(), QOpenGLPaintEngine::drawLines(), QPaintEngine::drawLines(), QRasterPaintEngine::drawLines(), QIntersectionFinder::hasIntersections(), QStroker::joinPoints(), QIntersectionFinder::linesIntersect(), QMatrix::map(), operator<<(), operator<<(), qt_radial_gradient_adapt_focal_point(), qt_stroke_side(), QRasterPaintEnginePrivate::rasterizeLine_dashed(), shift(), and QRasterPaintEngine::stroke().
 {
     return pt2;
 }
pointAt()
QPointF QLineF::pointAt (qreal t) const inline
Returns the point at the parameterized position specified by t.
The function returns the line's start point if t = 0, and its end point if t = 1.
See also
dx(), dy()
Definition at line 368 of file qline.h.
 {
     qreal vx = pt2.x() - pt1.x();
     qreal vy = pt2.y() - pt1.y();
     return QPointF(pt1.x() + vx * t, pt1.y() + vy * t);
 }
setAngle()
void QLineF::setAngle (qreal angle)
Sets the angle of the line to the given angle (in degrees).
Since
4.4
This will change the position of the second point of the line such that the line has the given angle.
Positive values for the angles mean counter-clockwise while negative values mean the clockwise direction. Zero degrees is at the 3 o'clock position.
See also
angle()
Definition at line 749 of file qline.cpp.
 {
     const qreal angleR = q_deg2rad(angle);
     const qreal l = length();
     const qreal dx = qCos(angleR) * l;
     const qreal dy = -qSin(angleR) * l;
     pt2.rx() = pt1.x() + dx;
     pt2.ry() = pt1.y() + dy;
 }
setLength()
void QLineF::setLength (qreal length) inline
Sets the length of the line to the given length.
QLineF will move the end point - p2() - of the line to give the line its new length. If the given length is negative the angle() is also changed.
If the line is a null line, the length will remain zero regardless of the length specified.
See also
length(), isNull()
Definition at line 360 of file qline.h.
Referenced by QStroker::joinPoints(), qt_radial_gradient_adapt_focal_point(), qt_stroke_side(), and QRasterPaintEnginePrivate::rasterizeLine_dashed().
 {
     if (isNull())
         return;
     QLineF v = unitVector();
     pt2 = QPointF(pt1.x() + v.dx() * len, pt1.y() + v.dy() * len);
 }
setLine()
void QLineF::setLine (qreal x1, qreal y1, qreal x2, qreal y2) inline
Sets this line to the start in x1, y1 and end in x2, y2.
Since
4.4
See also
setP1(), setP2(), p1(), p2()
Definition at line 397 of file qline.h.
 {
     pt1 = QPointF(aX1, aY1);
     pt2 = QPointF(aX2, aY2);
 }
setP1()
void QLineF::setP1 (const QPointF & p1) inline
Sets the starting point of this line to p1.
Since
4.4
See also
setP2(), p1()
Definition at line 381 of file qline.h.
Referenced by QRasterPaintEnginePrivate::rasterizeLine_dashed().
 {
     pt1 = aP1;
 }
setP2()
void QLineF::setP2 (const QPointF & p2) inline
Sets the end point of this line to p2.
Since
4.4
See also
setP1(), p2()
Definition at line 386 of file qline.h.
 {
     pt2 = aP2;
 }
setPoints()
void QLineF::setPoints (const QPointF & p1, const QPointF & p2) inline
Sets the start point of this line to p1 and the end point of this line to p2.
Since
4.4
See also
setP1(), setP2(), p1(), p2()
Definition at line 391 of file qline.h.
 {
     pt1 = aP1;
     pt2 = aP2;
 }
toLine()
QLine QLineF::toLine () const inline
Returns an integer based copy of this line.
Note that the returned line's start and end points are rounded to the nearest integer.
See also
QLineF()
Definition at line 375 of file qline.h.
 {
     return QLine(pt1.toPoint(), pt2.toPoint());
 }
translate() [1/2]
void QLineF::translate (const QPointF & p) inline
Translates this line by the given offset.
Definition at line 339 of file qline.h.
Referenced by QPainter::drawLines(), drawTextItemDecoration(), QStroker::joinPoints(), qt_stroke_side(), and translate().
 {
     pt1 += point;
     pt2 += point;
 }
translate() [2/2]
void QLineF::translate (qreal dx, qreal dy) inline
Translates this line the distance specified by dx and dy.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 345 of file qline.h.
 {
     this->translate(QPointF(adx, ady));
 }
translated() [1/2]
QLineF QLineF::translated (const QPointF & offset) const inline
Returns this line translated by the given offset.
Since
4.4
Definition at line 350 of file qline.h.
Referenced by translated().
 {
     return QLineF(pt1 + p, pt2 + p);
 }
translated() [2/2]
QLineF QLineF::translated (qreal dx, qreal dy) const inline
Returns this line translated the distance specified by dx and dy.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.4
Definition at line 355 of file qline.h.
 {
     return translated(QPointF(adx, ady));
 }
unitVector()
QLineF QLineF::unitVector () const
Returns the unit vector for this line, i.e a line starting at the same point as this line with a length of 1.0.
See also
normalVector()
Definition at line 786 of file qline.cpp.
Referenced by setLength(), and shift().
 {
     qreal x = pt2.x() - pt1.x();
     qreal y = pt2.y() - pt1.y();
     qreal len = qSqrt(x*x + y*y);
     QLineF f(p1(), QPointF(pt1.x() + x/len, pt1.y() + y/len));
 #ifndef QT_NO_DEBUG
     if (qAbs(f.length() - 1) >= 0.001)
         qWarning("QLine::unitVector: New line does not have unit length");
 #endif
     return f;
 }
x1()
qreal QLineF::x1 () const inline
Returns the x-coordinate of the line's start point.
See also
p1()
Definition at line 294 of file qline.h.
Referenced by clipLine(), QX11PaintEngine::drawLines(), QVGPaintEngine::drawLines(), QOpenGLPaintEngine::drawLines(), QStroker::joinPoints(), QTransform::map(), and qt_stroke_side().
 {
     return pt1.x();
 }
x2()
qreal QLineF::x2 () const inline
Returns the x-coordinate of the line's end point.
See also
p2()
Definition at line 304 of file qline.h.
Referenced by clipLine(), QX11PaintEngine::drawLines(), QVGPaintEngine::drawLines(), QOpenGLPaintEngine::drawLines(), QStroker::joinPoints(), QTransform::map(), and qt_stroke_side().
 {
     return pt2.x();
 }
y1()
qreal QLineF::y1 () const inline
Returns the y-coordinate of the line's start point.
See also
p1()
Definition at line 299 of file qline.h.
Referenced by clipLine(), QX11PaintEngine::drawLines(), QVGPaintEngine::drawLines(), QOpenGLPaintEngine::drawLines(), QStroker::joinPoints(), QTransform::map(), and qt_stroke_side().
 {
     return pt1.y();
 }
y2()
qreal QLineF::y2 () const inline
Returns the y-coordinate of the line's end point.
See also
p2()
Definition at line 309 of file qline.h.
Referenced by clipLine(), QX11PaintEngine::drawLines(), QVGPaintEngine::drawLines(), QOpenGLPaintEngine::drawLines(), QStroker::joinPoints(), QTransform::map(), and qt_stroke_side().
 {
     return pt2.y();
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & stream, const QLineF & line) related
Writes the given line to the given stream and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 1026 of file qline.cpp.
Referenced by operator==().
 {
     stream << line.p1() << line.p2();
     return stream;
 }
operator>>()
QDataStream & operator>> (QDataStream & stream, QLineF & line) related
Reads a line from the given stream into the given line and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 1044 of file qline.cpp.
Referenced by operator==().
 {
     QPointF start, end;
     stream >> start;
     stream >> end;
     line = QLineF(start, end);
     return stream;
 }
Properties
pt1
QPointF QLineF::pt1 private
Definition at line 272 of file qline.h.
Referenced by angle(), dx(), dy(), intersect(), isNull(), length(), operator==(), p1(), pointAt(), setAngle(), setLength(), setLine(), setP1(), setPoints(), toLine(), translate(), translated(), unitVector(), x1(), and y1().
pt2
QPointF QLineF::pt2 private
Definition at line 272 of file qline.h.
Referenced by angle(), dx(), dy(), intersect(), isNull(), length(), operator==(), p2(), pointAt(), setAngle(), setLength(), setLine(), setP2(), setPoints(), toLine(), translate(), translated(), unitVector(), x2(), and y2().
The documentation for this class was generated from the following files:
/src/corelib/tools/qline.h
/src/corelib/tools/qline.cpp