Qt 4.8: QWizard Class Reference
QWizard Class Reference
The QWizard class provides a framework for wizards.
#include <qwizard.h>
Public Types
enum WizardButton {
BackButton, NextButton, CommitButton, FinishButton,
CancelButton, HelpButton, CustomButton1, CustomButton2,
CustomButton3, Stretch, NoButton = -1, NStandardButtons = 6,
NButtons = 9
}
This enum specifies the buttons in a wizard.
enum WizardOption {
IndependentPages = 0x00000001, IgnoreSubTitles = 0x00000002, ExtendedWatermarkPixmap = 0x00000004, NoDefaultButton = 0x00000008,
NoBackButtonOnStartPage = 0x00000010, NoBackButtonOnLastPage = 0x00000020, DisabledBackButtonOnLastPage = 0x00000040, HaveNextButtonOnLastPage = 0x00000080,
HaveFinishButtonOnEarlyPages = 0x00000100, NoCancelButton = 0x00000200, CancelButtonOnLeft = 0x00000400, HaveHelpButton = 0x00000800,
HelpButtonOnRight = 0x00001000, HaveCustomButton1 = 0x00002000, HaveCustomButton2 = 0x00004000, HaveCustomButton3 = 0x00008000
}
This enum specifies various options that affect the look and feel of a wizard.
enum WizardPixmap {
WatermarkPixmap, LogoPixmap, BannerPixmap, BackgroundPixmap,
NPixmaps
}
This enum specifies the pixmaps that can be associated with a page.
enum WizardStyle {
ClassicStyle, ModernStyle, MacStyle, AeroStyle,
NStyles
}
This enum specifies the different looks supported by QWizard.
Public Types inherited from QDialog
enum DialogCode { Rejected, Accepted }
The value returned by a modal dialog.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void back ()
Goes back to the previous page.
void next ()
Advances to the next page.
void restart ()
Restarts the wizard at the start page.
Public Slots inherited from QDialog
virtual void accept ()
Hides the modal dialog and sets the result code to Accepted.
int exec ()
Shows the dialog as a modal dialog, blocking until the user closes it.
void open ()
Shows the dialog as a window modal dialog, returning immediately.
virtual void reject ()
Hides the modal dialog and sets the result code to Rejected.
void showExtension (bool)
If showIt is true, the dialog's extension is shown; otherwise the extension is hidden.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void currentIdChanged (int id)
This signal is emitted when the current page changes, with the new current id.
void customButtonClicked (int which)
This signal is emitted when the user clicks a custom button.
void helpRequested ()
This signal is emitted when the user clicks the Help button.
void pageAdded (int id)
This signal is emitted whenever a page is added to the wizard.
void pageRemoved (int id)
This signal is emitted whenever a page is removed from the wizard.
Signals inherited from QDialog
void accepted ()
This signal is emitted when the dialog has been accepted either by the user or by calling accept() or done() with the QDialog::Accepted argument.
void finished (int result)
This signal is emitted when the dialog's result code has been set, either by the user or by calling done(), accept(), or reject().
void rejected ()
This signal is emitted when the dialog has been rejected either by the user or by calling reject() or done() with the QDialog::Rejected argument.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int addPage (QWizardPage *page)
Adds the given page to the wizard, and returns the page's ID.
QAbstractButton * button (WizardButton which) const
Returns the button corresponding to role which.
QString buttonText (WizardButton which) const
Returns the text on button which.
int currentId () const
QWizardPage * currentPage () const
Returns a pointer to the current page, or 0 if there is no current page (e.g., before the wizard is shown).
QVariant field (const QString &name) const
Returns the value of the field called name.
bool hasVisitedPage (int id) const
Returns true if the page history contains page id; otherwise, returns false.
virtual int nextId () const
This virtual function is called by QWizard to find out which page to show when the user clicks the Next button.
WizardOptions options () const
QWizardPage * page (int id) const
Returns the page with the given id, or 0 if there is no such page.
QList< int > pageIds () const
Returns the list of page IDs.
QPixmap pixmap (WizardPixmap which) const
Returns the pixmap set for role which.
QWizard (QWidget *parent=0, Qt::WindowFlags flags=0)
Constructs a wizard with the given parent and window flags.
void removePage (int id)
Removes the page with the given id.
void setButton (WizardButton which, QAbstractButton *button)
Sets the button corresponding to role which to button.
void setButtonLayout (const QList< WizardButton > &layout)
Sets the order in which buttons are displayed to layout, where layout is a list of WizardButton.
void setButtonText (WizardButton which, const QString &text)
Sets the text on button which to be text.
void setDefaultProperty (const char *className, const char *property, const char *changedSignal)
Sets the default property for className to be property, and the associated change signal to be changedSignal.
void setField (const QString &name, const QVariant &value)
Sets the value of the field called name to value.
void setOption (WizardOption option, bool on=true)
Sets the given option to be enabled if on is true; otherwise, clears the given option.
void setOptions (WizardOptions options)
void setPage (int id, QWizardPage *page)
Adds the given page to the wizard with the given id.
void setPixmap (WizardPixmap which, const QPixmap &pixmap)
Sets the pixmap for role which to pixmap.
void setSideWidget (QWidget *widget)
Sets the given widget to be shown on the left side of the wizard.
void setStartId (int id)
void setSubTitleFormat (Qt::TextFormat format)
void setTitleFormat (Qt::TextFormat format)
void setVisible (bool visible)
Reimplemented Function
void setWizardStyle (WizardStyle style)
QWidget * sideWidget () const
Returns the widget on the left side of the wizard or 0.
QSize sizeHint () const
Reimplemented Function
int startId () const
Qt::TextFormat subTitleFormat () const
bool testOption (WizardOption option) const
Returns true if the given option is enabled; otherwise, returns false.
Qt::TextFormat titleFormat () const
virtual bool validateCurrentPage ()
This virtual function is called by QWizard when the user clicks Next or Finish to perform some last-minute validation.
QList< int > visitedPages () const
Returns the list of IDs of visited pages, in the order in which the pages were visited.
WizardStyle wizardStyle () const
~QWizard ()
Destroys the wizard and its pages, releasing any allocated resources.
Public Functions inherited from QDialog
QWidget * extension () const
Returns the dialog's extension or 0 if no extension has been defined.
bool isSizeGripEnabled () const
QSize minimumSizeHint () const
Reimplemented Function
Qt::Orientation orientation () const
Returns the dialog's extension orientation.
QDialog (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a dialog with parent parent.
int result () const
In general returns the modal dialog's result code, Accepted or Rejected.
void setExtension (QWidget *extension)
Sets the widget, extension, to be the dialog's extension, deleting any previous extension.
void setModal (bool modal)
void setOrientation (Qt::Orientation orientation)
If orientation is Qt::Horizontal, the extension will be displayed to the right of the dialog's main area.
void setResult (int r)
Sets the modal dialog's result code to i.
void setSizeGripEnabled (bool)
~QDialog ()
Destroys the QDialog, deleting all its children.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
virtual void cleanupPage (int id)
This virtual function is called by QWizard to clean up page id just before the user leaves it by clicking Back (unless the QWizard::IndependentPages option is set).
void done (int result)
Reimplemented Function
bool event (QEvent *event)
Reimplemented Function
virtual void initializePage (int id)
This virtual function is called by QWizard to prepare page id just before it is shown either as a result of QWizard::restart() being called, or as a result of the user clicking Next.
void paintEvent (QPaintEvent *event)
Reimplemented Function
void resizeEvent (QResizeEvent *event)
Reimplemented Function
bool winEvent (MSG *message, long *result)
Reimplemented Function
Protected Functions inherited from QDialog
void adjustPosition (QWidget *)
void closeEvent (QCloseEvent *)
Reimplemented Function
void contextMenuEvent (QContextMenuEvent *)
Reimplemented Function
bool eventFilter (QObject *, QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
Reimplemented Function
QDialog (QDialogPrivate &, QWidget *parent, Qt::WindowFlags f=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool event (QEvent *)
This is the main event handler; it handles event event.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
int currentId
the ID of the current page
WizardOptions options
the various options that affect the look and feel of the wizard
int startId
the ID of the first page
Qt::TextFormat subTitleFormat
the text format used by page subtitles
Qt::TextFormat titleFormat
the text format used by page titles
WizardStyle wizardStyle
the look and feel of the wizard
Friends
class QWizardPage
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QWizard class provides a framework for wizards.
Since
4.3
A wizard (also called an assistant on Mac OS X) is a special type of input dialog that consists of a sequence of pages. A wizard's purpose is to guide the user through a process step by step. Wizards are useful for complex or infrequent tasks that users may find difficult to learn.
QWizard inherits QDialog and represents a wizard. Each page is a QWizardPage (a QWidget subclass). To create your own wizards, you can use these classes directly, or you can subclass them for more control.
Topics:
A Trivial Example
The following example illustrates how to create wizard pages and add them to a wizard. For more advanced examples, see Class Wizard and License Wizard.
QWizardPage *createIntroPage()
{
    QWizardPage *page = new QWizardPage;
    page->setTitle("Introduction");
    QLabel *label = new QLabel("This wizard will help you register your copy "
                               "of Super Product Two.");
    label->setWordWrap(true);
    QVBoxLayout *layout = new QVBoxLayout;
    layout->addWidget(label);
    page->setLayout(layout);
    return page;
}
QWizardPage *createRegistrationPage()
{
...
}
QWizardPage *createConclusionPage()
{
...
}
int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    QString translatorFileName = QLatin1String("qt_");
    translatorFileName += QLocale::system().name();
    QTranslator *translator = new QTranslator(&app);
    if (translator->load(translatorFileName, QLibraryInfo::location(QLibraryInfo::TranslationsPath)))
        app.installTranslator(translator);
    QWizard wizard;
    wizard.addPage(createIntroPage());
    wizard.addPage(createRegistrationPage());
    wizard.addPage(createConclusionPage());
    wizard.setWindowTitle("Trivial Wizard");
#ifdef Q_OS_SYMBIAN
    wizard.showMaximized();
#else
    wizard.show();
#endif
    return app.exec();
}
Wizard Look and Feel
QWizard supports four wizard looks:
ClassicStyle
ModernStyle
MacStyle
AeroStyle
You can explicitly set the look to use using setWizardStyle() (e.g., if you want the same look on all platforms).
ClassicStyle ModernStyle MacStyle AeroStyle
Note: AeroStyle has effect only on a Windows Vista system with alpha compositing enabled. ModernStyle is used as a fallback when this condition is not met.
In addition to the wizard style, there are several options that control the look and feel of the wizard. These can be set using setOption() or setOptions(). For example, HaveHelpButton makes QWizard show a Help button along with the other wizard buttons.
You can even change the order of the wizard buttons to any arbitrary order using setButtonLayout(), and you can add up to three custom buttons (e.g., a Print button) to the button row. This is achieved by calling setButton() or setButtonText() with CustomButton1, CustomButton2, or CustomButton3 to set up the button, and by enabling the HaveCustomButton1, HaveCustomButton2, or HaveCustomButton3 options. Whenever the user clicks a custom button, customButtonClicked() is emitted. For example:
        wizard()->setButtonText(QWizard::CustomButton1, tr("&Print"));
        wizard()->setOption(QWizard::HaveCustomButton1, true);
        connect(wizard(), SIGNAL(customButtonClicked(int)),
                this, SLOT(printButtonClicked()));
Elements of a Wizard Page
Wizards consist of a sequence of QWizardPage. At any time, only one page is shown. A page has the following attributes:
A QWizardPage::title.
A QWizardPage::subTitle.
A set of pixmaps, which may or may not be honored, depending on the wizard's style:
WatermarkPixmap (used by ClassicStyle and ModernStyle)
BannerPixmap (used by ModernStyle)
LogoPixmap (used by ClassicStyle and ModernStyle)
BackgroundPixmap (used by MacStyle)
The diagram belows shows how QWizard renders these attributes, assuming they are all present and ModernStyle is used:
When a QWizardPage::subTitle is set, QWizard displays it in a header, in which case it also uses the BannerPixmap and the LogoPixmap to decorate the header. The WatermarkPixmap is displayed on the left side, below the header. At the bottom, there is a row of buttons allowing the user to navigate through the pages.
The page itself (the QWizardPage widget) occupies the area between the header, the watermark, and the button row. Typically, the page is a QWizardPage on which a QGridLayout is installed, with standard child widgets (QLabel, QLineEdit, etc.).
If the wizard's style is MacStyle, the page looks radically different:
The watermark, banner, and logo pixmaps are ignored by the MacStyle. If the BackgroundPixmap is set, it is used as the background for the wizard; otherwise, a default "assistant" image is used.
The title and subtitle are set by calling QWizardPage::setTitle() and QWizardPage::setSubTitle() on the individual pages. They may be plain text or HTML (see titleFormat and subTitleFormat). The pixmaps can be set globally for the entire wizard using setPixmap(), or on a per-page basis using QWizardPage::setPixmap().
Registering and Using Fields
In many wizards, the contents of a page may affect the default values of the fields of a later page. To make it easy to communicate between pages, QWizard supports a "field" mechanism that allows you to register a field (e.g., a QLineEdit) on a page and to access its value from any page. It is also possible to specify mandatory fields (i.e., fields that must be filled before the user can advance to the next page).
To register a field, call QWizardPage::registerField() field. For example:
ClassInfoPage::ClassInfoPage(QWidget *parent)
    : QWizardPage(parent)
{
...
    classNameLabel = new QLabel(tr("&Class name:"));
    classNameLineEdit = new QLineEdit;
    classNameLabel->setBuddy(classNameLineEdit);
    baseClassLabel = new QLabel(tr("B&ase class:"));
    baseClassLineEdit = new QLineEdit;
    baseClassLabel->setBuddy(baseClassLineEdit);
    qobjectMacroCheckBox = new QCheckBox(tr("Generate Q_OBJECT &macro"));
    registerField("className*", classNameLineEdit);
    registerField("baseClass", baseClassLineEdit);
    registerField("qobjectMacro", qobjectMacroCheckBox);
...
}
The above code registers three fields, className, baseClass, and qobjectMacro, which are associated with three child widgets. The asterisk (*) next to className denotes a mandatory field.
The fields of any page are accessible from any other page. For example:
void OutputFilesPage::initializePage()
{
    QString className = field("className").toString();
    headerLineEdit->setText(className.toLower() + ".h");
    implementationLineEdit->setText(className.toLower() + ".cpp");
    outputDirLineEdit->setText(QDir::convertSeparators(QDir::tempPath()));
}
Here, we call QWizardPage::field() to access the contents of the className field (which was defined in the ClassInfoPage) and use it to initialize the OuputFilePage. The field's contents is returned as a QVariant.
When we create a field using QWizardPage::registerField(), we pass a unique field name and a widget. We can also provide a Qt property name and a "changed" signal (a signal that is emitted when the property changes) as third and fourth arguments; however, this is not necessary for the most common Qt widgets, such as QLineEdit, QCheckBox, and QComboBox, because QWizard knows which properties to look for.
If an asterisk (*) is appended to the name when the property is registered, the field is a mandatory field. When a page has mandatory fields, the Next and/or Finish buttons are enabled only when all mandatory fields are filled.
To consider a field "filled", QWizard simply checks that the field's current value doesn't equal the original value (the value it had when initializePage() was called). For QLineEdit and QAbstractSpinBox subclasses, QWizard also checks that hasAcceptableInput() returns true, to honor any validator or mask.
QWizard's mandatory field mechanism is provided for convenience. A more powerful (but also more cumbersome) alternative is to reimplement QWizardPage::isComplete() and to emit the QWizardPage::completeChanged() signal whenever the page becomes complete or incomplete.
The enabled/disabled state of the Next and/or Finish buttons is one way to perform validation on the user input. Another way is to reimplement validateCurrentPage() (or QWizardPage::validatePage()) to perform some last-minute validation (and show an error message if the user has entered incomplete or invalid information). If the function returns true, the next page is shown (or the wizard finishes); otherwise, the current page stays up.
Creating Linear Wizards
Most wizards have a linear structure, with page 1 followed by page 2 and so on until the last page. The Class Wizard example is such a wizard. With QWizard, linear wizards are created by instantiating the QWizardPage and inserting them using addPage(). By default, the pages are shown in the order in which they were added. For example:
ClassWizard::ClassWizard(QWidget *parent)
    : QWizard(parent)
{
    addPage(new IntroPage);
    addPage(new ClassInfoPage);
    addPage(new CodeStylePage);
    addPage(new OutputFilesPage);
    addPage(new ConclusionPage);
...
}
When a page is about to be shown, QWizard calls initializePage() (which in turn calls QWizardPage::initializePage()) to fill the page with default values. By default, this function does nothing, but it can be reimplemented to initialize the page's contents based on other pages' fields (see the initialize page{example above}).
If the user presses Back, cleanupPage() is called (which in turn calls QWizardPage::cleanupPage()). The default implementation resets the page's fields to their original values (the values they had before initializePage() was called). If you want the Back button to be non-destructive and keep the values entered by the user, simply enable the IndependentPages option.
Creating Non-Linear Wizards
Some wizards are more complex in that they allow different traversal paths based on the information provided by the user. The License Wizard example illustrates this. It provides five wizard pages; depending on which options are selected, the user can reach different pages.
In complex wizards, pages are identified by IDs. These IDs are typically defined using an enum. For example:
class LicenseWizard : public QWizard
{
...
    enum { Page_Intro, Page_Evaluate, Page_Register, Page_Details,
           Page_Conclusion };
...
};
The pages are inserted using setPage(), which takes an ID and an instance of QWizardPage (or of a subclass):
LicenseWizard::LicenseWizard(QWidget *parent)
    : QWizard(parent)
{
    setPage(Page_Intro, new IntroPage);
    setPage(Page_Evaluate, new EvaluatePage);
    setPage(Page_Register, new RegisterPage);
    setPage(Page_Details, new DetailsPage);
    setPage(Page_Conclusion, new ConclusionPage);
...
}
By default, the pages are shown in increasing ID order. To provide a dynamic order that depends on the options chosen by the user, we must reimplement QWizardPage::nextId(). For example:
int IntroPage::nextId() const
{
    if (evaluateRadioButton->isChecked()) {
        return LicenseWizard::Page_Evaluate;
    } else {
        return LicenseWizard::Page_Register;
    }
}
int EvaluatePage::nextId() const
{
    return LicenseWizard::Page_Conclusion;
}
int RegisterPage::nextId() const
{
    if (upgradeKeyLineEdit->text().isEmpty()) {
        return LicenseWizard::Page_Details;
    } else {
        return LicenseWizard::Page_Conclusion;
    }
}
int DetailsPage::nextId() const
{
    return LicenseWizard::Page_Conclusion;
}
int ConclusionPage::nextId() const
{
    return -1;
}
It would also be possible to put all the logic in one place, in a QWizard::nextId() reimplementation. For example:
int LicenseWizard::nextId() const
{
    switch (currentId()) {
    case Page_Intro:
        if (field("intro.evaluate").toBool()) {
            return Page_Evaluate;
        } else {
            return Page_Register;
        }
    case Page_Evaluate:
        return Page_Conclusion;
    case Page_Register:
        if (field("register.upgradeKey").toString().isEmpty()) {
            return Page_Details;
        } else {
            return Page_Conclusion;
        }
    case Page_Details:
        return Page_Conclusion;
    case Page_Conclusion:
    default:
        return -1;
    }
}
To start at another page than the page with the lowest ID, call setStartId().
To test whether a page has been visited or not, call hasVisitedPage(). For example:
void ConclusionPage::initializePage()
{
    QString licenseText;
    if (wizard()->hasVisitedPage(LicenseWizard::Page_Evaluate)) {
        licenseText = tr("<u>Evaluation License Agreement:</u> "
                         "You can use this software for 30 days and make one "
                         "backup, but you are not allowed to distribute it.");
    } else if (wizard()->hasVisitedPage(LicenseWizard::Page_Details)) {
        licenseText = tr("<u>First-Time License Agreement:</u> "
                         "You can use this software subject to the license "
                         "you will receive by email.");
    } else {
        licenseText = tr("<u>Upgrade License Agreement:</u> "
                         "This software is licensed under the terms of your "
                         "current license.");
    }
    bottomLabel->setText(licenseText);
}
See also
QWizardPage, {Class Wizard Example}, {License Wizard Example}
Definition at line 59 of file qwizard.h.
Enumerations
WizardButton
enum QWizard::WizardButton
This enum specifies the buttons in a wizard.
BackButton The Back button ({Go Back} on Mac OS X)
NextButton The Next button (Continue on Mac OS X)
CommitButton The Commit button
FinishButton The Finish button (Done on Mac OS X)
CancelButton The Cancel button (see also NoCancelButton)
HelpButton The Help button (see also HaveHelpButton)
CustomButton1 The first user-defined button (see also HaveCustomButton1)
CustomButton2 The second user-defined button (see also HaveCustomButton2)
CustomButton3 The third user-defined button (see also HaveCustomButton3)
The following value is only useful when calling setButtonLayout():
Stretch A horizontal stretch in the button layout
NoButton
NStandardButtons
NButtons
See also
setButton(), setButtonText(), setButtonLayout(), customButtonClicked()
Enumerator
BackButton
NextButton
CommitButton
FinishButton
CancelButton
HelpButton
CustomButton1
CustomButton2
CustomButton3
Stretch
NoButton
NStandardButtons
NButtons
Definition at line 72 of file qwizard.h.
                       {
         BackButton,
         NextButton,
         CommitButton,
         FinishButton,
         CancelButton,
         HelpButton,
         CustomButton1,
         CustomButton2,
         CustomButton3,
         Stretch,
         NoButton = -1,
         NStandardButtons = 6,
         NButtons = 9
     };
WizardOption
enum QWizard::WizardOption
This enum specifies various options that affect the look and feel of a wizard.
IndependentPages The pages are independent of each other (i.e., they don't derive values from each other).
IgnoreSubTitles Don't show any subtitles, even if they are set.
ExtendedWatermarkPixmap Extend any WatermarkPixmap all the way down to the window's edge.
NoDefaultButton Don't make the Next or Finish button the dialog's default button.
NoBackButtonOnStartPage Don't show the Back button on the start page.
NoBackButtonOnLastPage Don't show the Back button on the last page.
DisabledBackButtonOnLastPage Disable the Back button on the last page.
HaveNextButtonOnLastPage Show the (disabled) Next button on the last page.
HaveFinishButtonOnEarlyPages Show the (disabled) Finish button on non-final pages.
NoCancelButton Don't show the Cancel button.
CancelButtonOnLeft Put the Cancel button on the left of Back (rather than on the right of Finish or Next).
HaveHelpButton Show the Help button.
HelpButtonOnRight Put the Help button on the far right of the button layout (rather than on the far left).
HaveCustomButton1 Show the first user-defined button (CustomButton1).
HaveCustomButton2 Show the second user-defined button (CustomButton2).
HaveCustomButton3 Show the third user-defined button (CustomButton3).
See also
setOptions(), setOption(), testOption()
Enumerator
IndependentPages
IgnoreSubTitles
ExtendedWatermarkPixmap
NoDefaultButton
NoBackButtonOnStartPage
NoBackButtonOnLastPage
DisabledBackButtonOnLastPage
HaveNextButtonOnLastPage
HaveFinishButtonOnEarlyPages
NoCancelButton
CancelButtonOnLeft
HaveHelpButton
HelpButtonOnRight
HaveCustomButton1
HaveCustomButton2
HaveCustomButton3
Definition at line 105 of file qwizard.h.
                       {
         IndependentPages                = 0x00000001,
         IgnoreSubTitles                 = 0x00000002,
         ExtendedWatermarkPixmap         = 0x00000004,
         NoDefaultButton                 = 0x00000008,
         NoBackButtonOnStartPage         = 0x00000010,
         NoBackButtonOnLastPage          = 0x00000020,
         DisabledBackButtonOnLastPage    = 0x00000040,
         HaveNextButtonOnLastPage        = 0x00000080,
         HaveFinishButtonOnEarlyPages    = 0x00000100,
         NoCancelButton                  = 0x00000200,
         CancelButtonOnLeft              = 0x00000400,
         HaveHelpButton                  = 0x00000800,
         HelpButtonOnRight               = 0x00001000,
         HaveCustomButton1               = 0x00002000,
         HaveCustomButton2               = 0x00004000,
         HaveCustomButton3               = 0x00008000
     };
WizardPixmap
enum QWizard::WizardPixmap
This enum specifies the pixmaps that can be associated with a page.
WatermarkPixmap The tall pixmap on the left side of a ClassicStyle or ModernStyle page
LogoPixmap The small pixmap on the right side of a ClassicStyle or ModernStyle page header
BannerPixmap The pixmap that occupies the background of a ModernStyle page header
BackgroundPixmap The pixmap that occupies the background of a MacStyle wizard
NPixmaps
See also
setPixmap(), QWizardPage::setPixmap(), {Elements of a Wizard Page}
Enumerator
WatermarkPixmap
LogoPixmap
BannerPixmap
BackgroundPixmap
NPixmaps
Definition at line 89 of file qwizard.h.
                       {
         WatermarkPixmap,
         LogoPixmap,
         BannerPixmap,
         BackgroundPixmap,
         NPixmaps
     };
WizardStyle
enum QWizard::WizardStyle
This enum specifies the different looks supported by QWizard.
ClassicStyle Classic Windows look
ModernStyle Modern Windows look
MacStyle Mac OS X look
AeroStyle Windows Aero look
NStyles
See also
setWizardStyle(), WizardOption, {Wizard Look and Feel}
Enumerator
ClassicStyle
ModernStyle
MacStyle
AeroStyle
NStyles
Definition at line 97 of file qwizard.h.
                      {
         ClassicStyle,
         ModernStyle,
         MacStyle,
         AeroStyle,
         NStyles
     };
Constructors and Destructors
QWizard()
QWizard::QWizard (QWidget * parent = 0, Qt::WindowFlags flags = 0) explicit
Constructs a wizard with the given parent and window flags.
See also
parent(), windowFlags()
Definition at line 2214 of file qwizard.cpp.
     : QDialog(*new QWizardPrivate, parent, flags)
 {
     Q_D(QWizard);
     d->init();
 #ifdef Q_WS_WINCE
     if (!qt_wince_is_mobile())
         setWindowFlags(windowFlags() & ~Qt::WindowOkButtonHint);
 #endif
 }
~QWizard()
QWizard::~QWizard ()
Destroys the wizard and its pages, releasing any allocated resources.
Definition at line 2228 of file qwizard.cpp.
 {
     Q_D(QWizard);
     delete d->buttonLayout;
 }
Functions
addPage()
int QWizard::addPage (QWizardPage * page)
Adds the given page to the wizard, and returns the page's ID.
The ID is guaranteed to be larger than any other ID in the QWizard so far.
See also
setPage(), page(), pageAdded()
Definition at line 2242 of file qwizard.cpp.
 {
     Q_D(QWizard);
     int theid = 0;
     if (!d->pageMap.isEmpty())
         theid = (d->pageMap.constEnd() - 1).key() + 1;
     setPage(theid, page);
     return theid;
 }
back
void QWizard::back () slot
Goes back to the previous page.
This is equivalent to pressing the Back button.
See also
next(), accept(), reject(), restart()
Definition at line 3159 of file qwizard.cpp.
Referenced by removePage().
 {
     Q_D(QWizard);
     int n = d->history.count() - 2;
     if (n < 0)
         return;
     d->switchToPage(d->history.at(n), QWizardPrivate::Backward);
 }
button()
QAbstractButton * QWizard::button (WizardButton which) const
Returns the button corresponding to role which.
See also
setButton(), setButtonText()
Definition at line 2829 of file qwizard.cpp.
Referenced by setButton().
 {
     Q_D(const QWizard);
 #if !defined(QT_NO_STYLE_WINDOWSVISTA)
     if (d->wizStyle == AeroStyle && which == BackButton)
         return d->vistaHelper->backButton();
 #endif
     if (!d->ensureButton(which))
         return 0;
     return d->btns[which];
 }
buttonText()
QString QWizard::buttonText (WizardButton which) const
Returns the text on button which.
If a text has ben set using setButtonText(), this text is returned.
By default, the text on buttons depends on the wizardStyle. For example, on Mac OS X, the Next button is called Continue.
See also
button(), setButton(), setButtonText(), QWizardPage::buttonText(), QWizardPage::setButtonText()
Definition at line 2729 of file qwizard.cpp.
Referenced by QWizardPage::buttonText().
 {
     Q_D(const QWizard);
     if (!d->ensureButton(which))
         return QString();
     if (d->buttonCustomTexts.contains(which))
         return d->buttonCustomTexts.value(which);
     const QString defText = buttonDefaultText(d->wizStyle, which, d);
     if(!defText.isNull())
         return defText;
     return d->btns[which]->text();
 }
cleanupPage()
void QWizard::cleanupPage (int id) protected virtual
This virtual function is called by QWizard to clean up page id just before the user leaves it by clicking Back (unless the QWizard::IndependentPages option is set).
The default implementation calls QWizardPage::cleanupPage() on page(id).
See also
QWizardPage::cleanupPage(), initializePage()
Definition at line 3378 of file qwizard.cpp.
Referenced by removePage().
 {
     QWizardPage *page = this->page(theid);
     if (page)
         page->cleanupPage();
 }
currentId()
int QWizard::currentId () const
Referenced by currentPage().
currentIdChanged
void QWizard::currentIdChanged (int id) signal
This signal is emitted when the current page changes, with the new current id.
See also
currentId(), currentPage()
currentPage()
QWizardPage * QWizard::currentPage () const
Returns a pointer to the current page, or 0 if there is no current page (e.g., before the wizard is shown).
This is equivalent to calling page(currentId()).
See also
page(), currentId(), restart()
Definition at line 2488 of file qwizard.cpp.
Referenced by QWizardPage::isFinalPage(), nextId(), paintEvent(), setButtonText(), QWizardPage::setCommitPage(), QWizardPage::setFinalPage(), sizeHint(), and validateCurrentPage().
 {
     Q_D(const QWizard);
     return page(d->current);
 }
customButtonClicked
void QWizard::customButtonClicked (int which) signal
This signal is emitted when the user clicks a custom button.
which can be CustomButton1, CustomButton2, or CustomButton3.
By default, no custom button is shown. Call setOption() with HaveCustomButton1, HaveCustomButton2, or HaveCustomButton3 to have one, and use setButtonText() or setButton() to configure it.
See also
helpRequested()
done()
void QWizard::done (int result) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 3324 of file qwizard.cpp.
 {
     Q_D(QWizard);
     // canceling leaves the wizard in a known state
     if (result == Rejected) {
         d->reset();
     } else {
         if (!validateCurrentPage())
             return;
     }
     QDialog::done(result);
 }
event()
bool QWizard::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 3216 of file qwizard.cpp.
 {
     Q_D(QWizard);
     if (event->type() == QEvent::StyleChange) { // Propagate style
         d->setStyle(style());
         d->updateLayout();
     }
 #if !defined(QT_NO_STYLE_WINDOWSVISTA)
     else if (event->type() == QEvent::Show && d->vistaInitPending) {
         d->vistaInitPending = false;
         d->wizStyle = AeroStyle;
         d->handleAeroStyleChange();
     }
     else if (d->isVistaThemeEnabled()) {
         if (event->type() == QEvent::Resize
                 || event->type() == QEvent::LayoutDirectionChange) {
             const int buttonLeft = (layoutDirection() == Qt::RightToLeft
                                     ? width() - d->vistaHelper->backButton()->sizeHint().width()
                                     : 0);
             d->vistaHelper->backButton()->move(buttonLeft,
                                                d->vistaHelper->backButton()->y());
         }
         d->vistaHelper->mouseEvent(event);
     }
 #endif
     return QDialog::event(event);
 }
field()
QVariant QWizard::field (const QString & name) const
Returns the value of the field called name.
This function can be used to access fields on any page of the wizard.
See also
QWizardPage::registerField(), QWizardPage::field(), setField()
Definition at line 2545 of file qwizard.cpp.
Referenced by setField().
 {
     Q_D(const QWizard);
     int index = d->fieldIndexMap.value(name, -1);
     if (index != -1) {
         const QWizardField &field = d->fields.at(index);
         return field.object->property(field.property);
     }
     qWarning("QWizard::field: No such field '%s'", qPrintable(name));
     return QVariant();
 }
hasVisitedPage()
bool QWizard::hasVisitedPage (int id) const
Returns true if the page history contains page id; otherwise, returns false.
Pressing Back marks the current page as "unvisited" again.
See also
visitedPages()
Definition at line 2411 of file qwizard.cpp.
 {
     Q_D(const QWizard);
     return d->history.contains(theid);
 }
helpRequested
void QWizard::helpRequested () signal
This signal is emitted when the user clicks the Help button.
By default, no Help button is shown. Call setOption(HaveHelpButton, true) to have one.
Example:
LicenseWizard::LicenseWizard(QWidget *parent)
    : QWizard(parent)
{
...
    setOption(HaveHelpButton, true);
    connect(this, SIGNAL(helpRequested()), this, SLOT(showHelp()));
...
}
void LicenseWizard::showHelp()
{
    static QString lastHelpMessage;
    QString message;
    switch (currentId()) {
    case Page_Intro:
        message = tr("The decision you make here will affect which page you "
                     "get to see next.");
        break;
...
    default:
        message = tr("This help is likely not to be of any help.");
    }
    QMessageBox::information(this, tr("License Wizard Help"), message);
}
See also
customButtonClicked()
initializePage()
void QWizard::initializePage (int id) protected virtual
This virtual function is called by QWizard to prepare page id just before it is shown either as a result of QWizard::restart() being called, or as a result of the user clicking Next.
(However, if the QWizard::IndependentPages option is set, this function is only called the first time the page is shown.)
By reimplementing this function, you can ensure that the page's fields are properly initialized based on fields from previous pages.
The default implementation calls QWizardPage::initializePage() on page(id).
See also
QWizardPage::initializePage(), cleanupPage()
Definition at line 3357 of file qwizard.cpp.
 {
     QWizardPage *page = this->page(theid);
     if (page)
         page->initializePage();
 }
next
void QWizard::next () slot
Advances to the next page.
This is equivalent to pressing the Next or Commit button.
See also
nextId(), back(), accept(), reject(), restart()
Definition at line 3175 of file qwizard.cpp.
 {
     Q_D(QWizard);
     if (d->current == -1)
         return;
     if (validateCurrentPage()) {
         int next = nextId();
         if (next != -1) {
             if (d->history.contains(next)) {
                 qWarning("QWizard::next: Page %d already met", next);
                 return;
             }
             if (!d->pageMap.contains(next)) {
                 qWarning("QWizard::next: No such page %d", next);
                 return;
             }
             d->switchToPage(next, QWizardPrivate::Forward);
         }
     }
 }
nextId()
int QWizard::nextId () const virtual
This virtual function is called by QWizard to find out which page to show when the user clicks the Next button.
The return value is the ID of the next page, or -1 if no page follows.
The default implementation calls QWizardPage::nextId() on the currentPage().
By reimplementing this function, you can specify a dynamic page order.
See also
QWizardPage::nextId(), currentPage()
Definition at line 3424 of file qwizard.cpp.
Referenced by QWizardPage::isFinalPage(), and next().
 {
     const QWizardPage *page = currentPage();
     if (!page)
         return -1;
     return page->nextId();
 }
options()
WizardOptions QWizard::options () const
Referenced by setOptions().
page()
QWizardPage * QWizard::page (int id) const
Returns the page with the given id, or 0 if there is no such page.
See also
addPage(), setPage()
Definition at line 2392 of file qwizard.cpp.
Referenced by cleanupPage(), currentPage(), initializePage(), nextId(), and validateCurrentPage().
 {
     Q_D(const QWizard);
     return d->pageMap.value(theid);
 }
pageAdded
void QWizard::pageAdded (int id) signal
This signal is emitted whenever a page is added to the wizard.
Since
4.7
The page's id is passed as parameter.
See also
addPage(), setPage(), startId()
Referenced by setPage().
pageIds()
QList< int > QWizard::pageIds () const
Returns the list of page IDs.
Since
4.5
Definition at line 2435 of file qwizard.cpp.
 {
   Q_D(const QWizard);
   return d->pageMap.keys();
 }
pageRemoved
void QWizard::pageRemoved (int id) signal
This signal is emitted whenever a page is removed from the wizard.
Since
4.7
The page's id is passed as parameter.
See also
removePage(), startId()
Referenced by removePage().
paintEvent()
void QWizard::paintEvent (QPaintEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3271 of file qwizard.cpp.
 {
     Q_D(QWizard);
     if (d->wizStyle == MacStyle && currentPage()) {
         QPixmap backgroundPixmap = currentPage()->pixmap(BackgroundPixmap);
         if (backgroundPixmap.isNull())
             return;
         QPainter painter(this);
         painter.drawPixmap(0, (height() - backgroundPixmap.height()) / 2, backgroundPixmap);
     }
 #if !defined(QT_NO_STYLE_WINDOWSVISTA)
     else if (d->isVistaThemeEnabled()) {
         if (d->isVistaThemeEnabled(QVistaHelper::VistaBasic)) {
             QPainter painter(this);
             QColor color = d->vistaHelper->basicWindowFrameColor();
             painter.fillRect(0, 0, width(), QVistaHelper::topOffset(), color);
         }
         d->vistaHelper->paintEvent(event);
     }
 #else
     Q_UNUSED(event);
 #endif
 }
pixmap()
QPixmap QWizard::pixmap (WizardPixmap which) const
Returns the pixmap set for role which.
By default, the only pixmap that is set is the BackgroundPixmap on Mac OS X.
See also
QWizardPage::pixmap(), {Elements of a Wizard Page}
Definition at line 2917 of file qwizard.cpp.
Referenced by QWizardPage::pixmap(), setPixmap(), and sizeHint().
 {
     Q_D(const QWizard);
     Q_ASSERT(uint(which) < NPixmaps);
 #ifdef Q_WS_MAC
     if (which == BackgroundPixmap && d->defaultPixmaps[BackgroundPixmap].isNull())
         d->defaultPixmaps[BackgroundPixmap] = d->findDefaultBackgroundPixmap();
 #endif
     return d->defaultPixmaps[which];
 }
removePage()
void QWizard::removePage (int id)
Removes the page with the given id.
cleanupPage() will be called if necessary.
Note
Removing a page may influence the value of the startId property.
Since
4.5
See also
addPage(), setPage(), pageRemoved(), startId()
Definition at line 2318 of file qwizard.cpp.
 {
     Q_D(QWizard);
     QWizardPage *removedPage = 0;
     // update startItem accordingly
     if (d->pageMap.count() > 0) { // only if we have any pages
         if (d->start == id) {
             const int firstId = d->pageMap.constBegin().key();
             if (firstId == id) {
                 if (d->pageMap.count() > 1)
                     d->start = (++d->pageMap.constBegin()).key(); // secondId
                 else
                     d->start = -1; // removing the last page
             } else { // startSetByUser has to be "true" here
                 d->start = firstId;
             }
             d->startSetByUser = false;
         }
     }
     if (d->pageMap.contains(id))
         emit pageRemoved(id);
     if (!d->history.contains(id)) {
         // Case 1: removing a page not in the history
         removedPage = d->pageMap.take(id);
         d->updateCurrentPage();
     } else if (id != d->current) {
         // Case 2: removing a page in the history before the current page
         removedPage = d->pageMap.take(id);
         d->history.removeOne(id);
         d->_q_updateButtonStates();
     } else if (d->history.count() == 1) {
         // Case 3: removing the current page which is the first (and only) one in the history
         d->reset();
         removedPage = d->pageMap.take(id);
         if (d->pageMap.isEmpty())
             d->updateCurrentPage();
         else
             restart();
     } else {
         // Case 4: removing the current page which is not the first one in the history
         back();
         removedPage = d->pageMap.take(id);
         d->updateCurrentPage();
     }
     if (removedPage) {
         if (d->initialized.contains(id)) {
             cleanupPage(id);
             d->initialized.remove(id);
         }
         d->pageVBoxLayout->removeWidget(removedPage);
         for (int i = d->fields.count() - 1; i >= 0; --i) {
             if (d->fields.at(i).page == removedPage) {
                 removedPage->d_func()->pendingFields += d->fields.at(i);
                 d->removeFieldAt(i);
             }
         }
     }
 }
resizeEvent()
void QWizard::resizeEvent (QResizeEvent * event) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 3249 of file qwizard.cpp.
 {
     Q_D(QWizard);
     int heightOffset = 0;
 #if !defined(QT_NO_STYLE_WINDOWSVISTA)
     if (d->isVistaThemeEnabled()) {
         heightOffset = d->vistaHelper->topOffset();
         if (d->isVistaThemeEnabled(QVistaHelper::VistaAero))
             heightOffset += d->vistaHelper->titleBarSize();
     }
 #endif
     d->antiFlickerWidget->resize(event->size().width(), event->size().height() - heightOffset);
 #if !defined(QT_NO_STYLE_WINDOWSVISTA)
     if (d->isVistaThemeEnabled())
         d->vistaHelper->resizeEvent(event);
 #endif
     QDialog::resizeEvent(event);
 }
restart
void QWizard::restart () slot
Restarts the wizard at the start page.
This function is called automatically when the wizard is shown.
See also
startId()
Definition at line 3204 of file qwizard.cpp.
Referenced by removePage(), and setVisible().
 {
     Q_D(QWizard);
     d->disableUpdates();
     d->reset();
     d->switchToPage(startId(), QWizardPrivate::Forward);
     d->enableUpdates();
 }
setButton()
void QWizard::setButton (WizardButton which, QAbstractButton * button)
Sets the button corresponding to role which to button.
To add extra buttons to the wizard (e.g., a Print button), one way is to call setButton() with CustomButton1 to CustomButton3, and make the buttons visible using the HaveCustomButton1 to HaveCustomButton3 options.
See also
setButtonText(), setButtonLayout(), options
Definition at line 2799 of file qwizard.cpp.
 {
     Q_D(QWizard);
     if (uint(which) >= NButtons || d->btns[which] == button)
         return;
     if (QAbstractButton *oldButton = d->btns[which]) {
         d->buttonLayout->removeWidget(oldButton);
         delete oldButton;
     }
     d->btns[which] = button;
     if (button) {
         button->setParent(d->antiFlickerWidget);
         d->buttonCustomTexts.insert(which, button->text());
         d->connectButton(which);
     } else {
         d->buttonCustomTexts.remove(which); // ### what about page-specific texts set for 'which'
         d->ensureButton(which);             // (QWizardPage::setButtonText())? Clear them as well?
     }
     d->updateButtonLayout();
 }
setButtonLayout()
void QWizard::setButtonLayout (const QList< WizardButton > & layout)
Sets the order in which buttons are displayed to layout, where layout is a list of WizardButton.
The default layout depends on the options (e.g., whether HelpButtonOnRight) that are set. You can call this function if you need more control over the buttons' layout than what options already provides.
You can specify horizontal stretches in the layout using Stretch .
Example:
MyWizard::MyWizard(QWidget *parent)
    : QWizard(parent)
{
    ...
    QList<QWizard::WizardButton> layout;
    layout << QWizard::Stretch << QWizard::BackButton << QWizard::CancelButton
           << QWizard::NextButton << QWizard::FinishButton;
    setButtonLayout(layout);
    ...
}
See also
setButton(), setButtonText(), setOptions()
Definition at line 2762 of file qwizard.cpp.
 {
     Q_D(QWizard);
     for (int i = 0; i < layout.count(); ++i) {
         WizardButton button1 = layout.at(i);
         if (button1 == NoButton || button1 == Stretch)
             continue;
         if (!d->ensureButton(button1))
             return;
         // O(n^2), but n is very small
         for (int j = 0; j < i; ++j) {
             WizardButton button2 = layout.at(j);
             if (button2 == button1) {
                 qWarning("QWizard::setButtonLayout: Duplicate button in layout");
                 return;
             }
         }
     }
     d->buttonsHaveCustomLayout = true;
     d->buttonsCustomLayout = layout;
     d->updateButtonLayout();
 }
setButtonText()
void QWizard::setButtonText (WizardButton which, const QString & text)
Sets the text on button which to be text.
By default, the text on buttons depends on the wizardStyle. For example, on Mac OS X, the Next button is called Continue.
To add extra buttons to the wizard (e.g., a Print button), one way is to call setButtonText() with CustomButton1, CustomButton2, or CustomButton3 to set their text, and make the buttons visible using the HaveCustomButton1, HaveCustomButton2, and/or HaveCustomButton3 options.
Button texts may also be set on a per-page basis using QWizardPage::setButtonText().
See also
setButton(), button(), setButtonLayout(), setOptions(), QWizardPage::setButtonText()
Definition at line 2704 of file qwizard.cpp.
 {
     Q_D(QWizard);
     if (!d->ensureButton(which))
         return;
     d->buttonCustomTexts.insert(which, text);
     if (!currentPage() || !currentPage()->d_func()->buttonCustomTexts.contains(which))
         d->btns[which]->setText(text);
 }
setDefaultProperty()
void QWizard::setDefaultProperty (const char * className, const char * property, const char * changedSignal)
Sets the default property for className to be property, and the associated change signal to be changedSignal.
The default property is used when an instance of className (or of one of its subclasses) is passed to QWizardPage::registerField() and no property is specified.
QWizard knows the most common Qt widgets. For these (or their subclasses), you don't need to specify a property or a changedSignal. The table below lists these widgets:
Widget Property Change Notification Signal
QAbstractButton bool QAbstractButton::checked QAbstractButton::toggled()
QAbstractSlider int QAbstractSlider::value QAbstractSlider::valueChanged()
QComboBox int QComboBox::currentIndex QComboBox::currentIndexChanged()
QDateTimeEdit QDateTime QDateTimeEdit::dateTime QDateTimeEdit::dateTimeChanged()
QLineEdit QString QLineEdit::text QLineEdit::textChanged()
QListWidget int QListWidget::currentRow QListWidget::currentRowChanged()
QSpinBox int QSpinBox::value QSpinBox::valueChanged()
See also
QWizardPage::registerField()
Definition at line 2953 of file qwizard.cpp.
 {
     Q_D(QWizard);
     for (int i = d->defaultPropertyTable.count() - 1; i >= 0; --i) {
         if (qstrcmp(d->defaultPropertyTable.at(i).className, className) == 0) {
             d->defaultPropertyTable.remove(i);
             break;
         }
     }
     d->defaultPropertyTable.append(QWizardDefaultProperty(className, property, changedSignal));
 }
setField()
void QWizard::setField (const QString & name, const QVariant & value)
Sets the value of the field called name to value.
This function can be used to set fields on any page of the wizard.
See also
QWizardPage::registerField(), QWizardPage::setField(), field()
Definition at line 2522 of file qwizard.cpp.
 {
     Q_D(QWizard);
     int index = d->fieldIndexMap.value(name, -1);
     if (index != -1) {
         const QWizardField &field = d->fields.at(index);
         if (!field.object->setProperty(field.property, value))
             qWarning("QWizard::setField: Couldn't write to property '%s'",
                      field.property.constData());
         return;
     }
     qWarning("QWizard::setField: No such field '%s'", qPrintable(name));
 }
setOption()
void QWizard::setOption (WizardOption option, bool on = true)
Sets the given option to be enabled if on is true; otherwise, clears the given option.
See also
options, testOption(), setWizardStyle()
Definition at line 2617 of file qwizard.cpp.
 {
     Q_D(QWizard);
     if (!(d->opts & option) != !on)
         setOptions(d->opts ^ option);
 }
setOptions()
void QWizard::setOptions (WizardOptions options)
Definition at line 2653 of file qwizard.cpp.
Referenced by setOption().
 {
     Q_D(QWizard);
     WizardOptions changed = (options ^ d->opts);
     if (!changed)
         return;
     d->disableUpdates();
     d->opts = options;
     if ((changed & IndependentPages) && !(d->opts & IndependentPages))
         d->cleanupPagesNotInHistory();
     if (changed & (NoDefaultButton | HaveHelpButton | HelpButtonOnRight | NoCancelButton
                    | CancelButtonOnLeft | HaveCustomButton1 | HaveCustomButton2
                    | HaveCustomButton3)) {
         d->updateButtonLayout();
     } else if (changed & (NoBackButtonOnStartPage | NoBackButtonOnLastPage
                           | HaveNextButtonOnLastPage | HaveFinishButtonOnEarlyPages
                           | DisabledBackButtonOnLastPage)) {
         d->_q_updateButtonStates();
     }
     d->enableUpdates();
     d->updateLayout();
 }
setPage()
void QWizard::setPage (int id, QWizardPage * page)
Adds the given page to the wizard with the given id.
Note
Adding a page may influence the value of the startId property in case it was not set explicitly.
See also
addPage(), page(), pageAdded()
Definition at line 2262 of file qwizard.cpp.
Referenced by addPage().
 {
     Q_D(QWizard);
     if (!page) {
         qWarning("QWizard::setPage: Cannot insert null page");
         return;
     }
     if (theid == -1) {
         qWarning("QWizard::setPage: Cannot insert page with ID -1");
         return;
     }
     if (d->pageMap.contains(theid)) {
         qWarning("QWizard::setPage: Page with duplicate ID %d ignored", theid);
         return;
     }
     page->setParent(d->pageFrame);
     QVector<QWizardField> &pendingFields = page->d_func()->pendingFields;
     for (int i = 0; i < pendingFields.count(); ++i)
         d->addField(pendingFields.at(i));
     pendingFields.clear();
     connect(page, SIGNAL(completeChanged()), this, SLOT(_q_updateButtonStates()));
     d->pageMap.insert(theid, page);
     page->d_func()->wizard = this;
     int n = d->pageVBoxLayout->count();
     // disable layout to prevent layout updates while adding
     bool pageVBoxLayoutEnabled = d->pageVBoxLayout->isEnabled();
     d->pageVBoxLayout->setEnabled(false);
     d->pageVBoxLayout->insertWidget(n - 1, page);
     // hide new page and reset layout to old status
     page->hide();
     d->pageVBoxLayout->setEnabled(pageVBoxLayoutEnabled);
     if (!d->startSetByUser && d->pageMap.constBegin().key() == theid)
         d->start = theid;
     emit pageAdded(theid);
 }
setPixmap()
void QWizard::setPixmap (WizardPixmap which, const QPixmap & pixmap)
Sets the pixmap for role which to pixmap.
The pixmaps are used by QWizard when displaying a page. Which pixmaps are actually used depend on the Wizard Look and Feel{wizard style}.
Pixmaps can also be set for a specific page using QWizardPage::setPixmap().
See also
QWizardPage::setPixmap(), {Elements of a Wizard Page}
Definition at line 2901 of file qwizard.cpp.
 {
     Q_D(QWizard);
     Q_ASSERT(uint(which) < NPixmaps);
     d->defaultPixmaps[which] = pixmap;
     d->updatePixmap(which);
 }
setSideWidget()
void QWizard::setSideWidget (QWidget * widget)
Sets the given widget to be shown on the left side of the wizard.
Since
4.7
For styles which use the WatermarkPixmap (ClassicStyle and ModernStyle) the side widget is displayed on top of the watermark, for other styles or when the watermark is not provided the side widget is displayed on the left side of the wizard.
Passing 0 shows no side widget.
When the widget is not 0 the wizard reparents it.
Any previous side widget is hidden.
You may call setSideWidget() with the same widget at different times.
All widgets set here will be deleted by the wizard when it is destroyed unless you separately reparent the widget after setting some other side widget (or 0).
By default, no side widget is present.
Definition at line 2993 of file qwizard.cpp.
 {
     Q_D(QWizard);
     d->sideWidget = widget;
     if (d->watermarkLabel) {
         d->watermarkLabel->setSideWidget(widget);
         d->updateLayout();
     }
 }
setStartId()
void QWizard::setStartId (int id)
Definition at line 2454 of file qwizard.cpp.
 {
     Q_D(QWizard);
     int newStart = theid;
     if (theid == -1)
         newStart = d->pageMap.count() ? d->pageMap.constBegin().key() : -1;
     if (d->start == newStart) {
         d->startSetByUser = theid != -1;
         return;
     }
     if (!d->pageMap.contains(newStart)) {
         qWarning("QWizard::setStartId: Invalid page ID %d", newStart);
         return;
     }
     d->start = newStart;
     d->startSetByUser = theid != -1;
 }
setSubTitleFormat()
void QWizard::setSubTitleFormat (Qt::TextFormat format)
Definition at line 2876 of file qwizard.cpp.
 {
     Q_D(QWizard);
     d->subTitleFmt = format;
     d->updateLayout();
 }
setTitleFormat()
void QWizard::setTitleFormat (Qt::TextFormat format)
Definition at line 2852 of file qwizard.cpp.
 {
     Q_D(QWizard);
     d->titleFmt = format;
     d->updateLayout();
 }
setVisible()
void QWizard::setVisible (bool visible) virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 3024 of file qwizard.cpp.
 {
     Q_D(QWizard);
     if (visible) {
         if (d->current == -1)
             restart();
     }
     QDialog::setVisible(visible);
 }
setWizardStyle()
void QWizard::setWizardStyle (WizardStyle style)
Definition at line 2574 of file qwizard.cpp.
Referenced by winEvent().
 {
     Q_D(QWizard);
     const bool styleChange = style != d->wizStyle;
 #if !defined(QT_NO_STYLE_WINDOWSVISTA)
     const bool aeroStyleChange =
         d->vistaInitPending || d->vistaStateChanged || (styleChange && (style == AeroStyle || d->wizStyle == AeroStyle));
     d->vistaStateChanged = false;
     d->vistaInitPending = false;
 #endif
     if (styleChange
 #if !defined(QT_NO_STYLE_WINDOWSVISTA)
         || aeroStyleChange
 #endif
         ) {
         d->disableUpdates();
         d->wizStyle = style;
         d->updateButtonTexts();
         d->updateLayout();
         updateGeometry();
         d->enableUpdates();
 #if !defined(QT_NO_STYLE_WINDOWSVISTA)
         if (aeroStyleChange)
             d->handleAeroStyleChange();
 #endif
     }
 }
sideWidget()
QWidget * QWizard::sideWidget () const
Returns the widget on the left side of the wizard or 0.
Since
4.7
By default, no side widget is present.
Definition at line 3014 of file qwizard.cpp.
 {
     Q_D(const QWizard);
     return d->sideWidget;
 }
sizeHint()
QSize QWizard::sizeHint () const virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 3037 of file qwizard.cpp.
 {
     Q_D(const QWizard);
     QSize result = d->mainLayout->totalSizeHint();
 #ifdef Q_WS_S60
     QSize extra(QApplication::desktop()->availableGeometry(QCursor::pos()).size());
 #else
     QSize extra(500, 360);
 #endif
     if (d->wizStyle == MacStyle && d->current != -1) {
         QSize pixmap(currentPage()->pixmap(BackgroundPixmap).size());
         extra.setWidth(616);
         if (!pixmap.isNull()) {
             extra.setHeight(pixmap.height());
             /*
                 The width isn't always reliable as a size hint, as
                 some wizard backgrounds just cover the leftmost area.
                 Use a rule of thumb to determine if the width is
                 reliable or not.
             */
             if (pixmap.width() >= pixmap.height())
                 extra.setWidth(pixmap.width());
         }
     }
     return result.expandedTo(extra);
 }
startId()
int QWizard::startId () const
Referenced by restart(), and setStartId().
subTitleFormat()
Qt::TextFormat QWizard::subTitleFormat () const
Referenced by setSubTitleFormat().
testOption()
bool QWizard::testOption (WizardOption option) const
Returns true if the given option is enabled; otherwise, returns false.
See also
options, setOption(), setWizardStyle()
Definition at line 2630 of file qwizard.cpp.
 {
     Q_D(const QWizard);
     return (d->opts & option) != 0;
 }
titleFormat()
Qt::TextFormat QWizard::titleFormat () const
Referenced by setTitleFormat().
validateCurrentPage()
bool QWizard::validateCurrentPage () virtual
This virtual function is called by QWizard when the user clicks Next or Finish to perform some last-minute validation.
If it returns true, the next page is shown (or the wizard finishes); otherwise, the current page stays up.
The default implementation calls QWizardPage::validatePage() on the currentPage().
When possible, it is usually better style to disable the Next or Finish button (by specifying mandatory fields or by reimplementing QWizardPage::isComplete()) than to reimplement validateCurrentPage().
See also
QWizardPage::validatePage(), currentPage()
Definition at line 3401 of file qwizard.cpp.
Referenced by done(), and next().
 {
     QWizardPage *page = currentPage();
     if (!page)
         return true;
     return page->validatePage();
 }
visitedPages()
QList< int > QWizard::visitedPages () const
Returns the list of IDs of visited pages, in the order in which the pages were visited.
Pressing Back marks the current page as "unvisited" again.
See also
hasVisitedPage()
Definition at line 2425 of file qwizard.cpp.
 {
     Q_D(const QWizard);
     return d->history;
 }
winEvent()
bool QWizard::winEvent (MSG * message, long * result) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3300 of file qwizard.cpp.
 {
 #if !defined(QT_NO_STYLE_WINDOWSVISTA)
     Q_D(QWizard);
     if (d->isVistaThemeEnabled()) {
         const bool winEventResult = d->vistaHelper->handleWinEvent(message, result);
         if (QVistaHelper::vistaState() != d->vistaState) {
             d->vistaState = QVistaHelper::vistaState();
             d->vistaStateChanged = true;
             setWizardStyle(AeroStyle);
         }
         return winEventResult;
     } else {
         return QDialog::winEvent(message, result);
     }
 #else
     return QDialog::winEvent(message, result);
 #endif
 }
wizardStyle()
WizardStyle QWizard::wizardStyle () const
Referenced by setWizardStyle().
Friends and Related Functions
QWizardPage
friend class QWizardPage friend
Definition at line 207 of file qwizard.h.
Properties
currentId
int QWizard::currentId private
the ID of the current page
This property cannot be set directly. To change the current page, call next(), back(), or restart().
By default, this property has a value of -1, indicating that no page is currently shown.
See also
currentIdChanged(), currentPage()
Definition at line 69 of file qwizard.h.
options
QWizard::WizardOptions QWizard::options private
the various options that affect the look and feel of the wizard
By default, the following options are set (depending on the platform):
Windows: HelpButtonOnRight.
Mac OS X: NoDefaultButton and NoCancelButton.
X11 and QWS (Qt for Embedded Linux): none.
See also
wizardStyle
Definition at line 65 of file qwizard.h.
startId
int QWizard::startId private
the ID of the first page
If this property isn't explicitly set, this property defaults to the lowest page ID in this wizard, or -1 if no page has been inserted yet.
See also
restart(), nextId()
Definition at line 68 of file qwizard.h.
subTitleFormat
Qt::TextFormat QWizard::subTitleFormat private
the text format used by page subtitles
The default format is Qt::AutoText.
See also
QWizardPage::title, titleFormat
Definition at line 67 of file qwizard.h.
titleFormat
Qt::TextFormat QWizard::titleFormat private
the text format used by page titles
The default format is Qt::AutoText.
See also
QWizardPage::title, subTitleFormat
Definition at line 66 of file qwizard.h.
wizardStyle
QWizard::WizardStyle QWizard::wizardStyle private
the look and feel of the wizard
By default, QWizard uses the AeroStyle on a Windows Vista system with alpha compositing enabled, regardless of the current widget style. If this is not the case, the default wizard style depends on the current widget style as follows: MacStyle is the default if the current widget style is QMacStyle, ModernStyle is the default if the current widget style is QWindowsStyle, and ClassicStyle is the default in all other cases.
See also
{Wizard Look and Feel}, options
Definition at line 64 of file qwizard.h.
Referenced by QVistaHelper::handleWinEvent().
The documentation for this class was generated from the following files:
/src/gui/dialogs/qwizard.h
/src/gui/dialogs/qwizard.cpp