Qt 4.8: QIBaseResult Class Reference
QIBaseResult Class Reference
#include <qsql_ibase.h>
Public Functions
bool exec ()
Executes the query, returning true if successful; otherwise returns false.
QVariant handle () const
Returns the low-level database handle for this result set wrapped in a QVariant or an invalid QVariant if there is no handle.
bool prepare (const QString &query)
Prepares the given query for execution; the query will normally use placeholders so that it can be executed repeatedly.
QIBaseResult (const QIBaseDriver *db)
virtual ~QIBaseResult ()
Public Functions inherited from QSqlCachedResult
virtual ~QSqlCachedResult ()
Public Functions inherited from QSqlResult
virtual ~QSqlResult ()
Destroys the object and frees any allocated resources.
Protected Functions
bool gotoNext (QSqlCachedResult::ValueCache &row, int rowIdx)
int numRowsAffected ()
Returns the number of rows affected by the last query executed, or -1 if it cannot be determined or if the query is a SELECT statement.
QSqlRecord record () const
Returns the current record if the query is active; otherwise returns an empty QSqlRecord.
bool reset (const QString &query)
Sets the result to use the SQL statement query for subsequent data retrieval.
int size ()
Returns the size of the SELECT result, or -1 if it cannot be determined or if the query is not a SELECT statement.
Protected Functions inherited from QSqlCachedResult
ValueCache & cache ()
void cleanup ()
void clearValues ()
int colCount () const
QVariant data (int i)
Returns the data for field index in the current row as a QVariant.
bool fetch (int i)
Positions the result to an arbitrary (zero-based) row index.
bool fetchFirst ()
Positions the result to the first record (row 0) in the result.
bool fetchLast ()
Positions the result to the last record (last row) in the result.
bool fetchNext ()
Positions the result to the next available record (row) in the result.
bool fetchPrevious ()
Positions the result to the previous record (row) in the result.
void init (int colCount)
bool isNull (int i)
Returns true if the field at position index in the current row is null; otherwise returns false.
QSqlCachedResult (const QSqlDriver *db)
void virtual_hook (int id, void *data)
Protected Functions inherited from QSqlResult
void addBindValue (const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to the next available position in the current record (row).
int at () const
Returns the current (zero-based) row position of the result.
BindingSyntax bindingSyntax () const
Returns the binding syntax used by prepared queries.
virtual void bindValue (int pos, const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to position index in the current record (row).
virtual void bindValue (const QString &placeholder, const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to the placeholder name in the current record (row).
QSql::ParamType bindValueType (const QString &placeholder) const
Returns the parameter type for the value bound with the given placeholder name.
QSql::ParamType bindValueType (int pos) const
Returns the parameter type for the value bound at position index.
QVariant boundValue (const QString &placeholder) const
Returns the value bound by the given placeholder name in the current record (row).
QVariant boundValue (int pos) const
Returns the value bound at position index in the current record (row).
int boundValueCount () const
Returns the number of bound values in the result.
QString boundValueName (int pos) const
Returns the name of the bound value at position index in the current record (row).
QVector< QVariant > & boundValues () const
Returns a vector of the result's bound values for the current record (row).
void clear ()
Clears the entire result set and releases any associated resources.
void detachFromResultSet ()
const QSqlDriver * driver () const
Returns the driver associated with the result.
bool execBatch (bool arrayBind=false)
Executes a prepared query in batch mode if the driver supports it, otherwise emulates a batch execution using bindValue() and exec().
QString executedQuery () const
Returns the query that was actually executed.
bool hasOutValues () const
Returns true if at least one of the query's bound values is a QSql::Out or a QSql::InOut; otherwise returns false.
bool isActive () const
Returns true if the result has records to be retrieved; otherwise returns false.
bool isForwardOnly () const
Returns true if you can only scroll forward through the result set; otherwise returns false.
bool isSelect () const
Returns true if the current result is from a SELECT statement; otherwise returns false.
bool isValid () const
Returns true if the result is positioned on a valid record (that is, the result is not positioned before the first or after the last record); otherwise returns false.
QSqlError lastError () const
Returns the last error associated with the result.
virtual QVariant lastInsertId () const
Returns the object ID of the most recent inserted row if the database supports it.
QString lastQuery () const
Returns the current SQL query text, or an empty string if there isn't one.
bool nextResult ()
QSql::NumericalPrecisionPolicy numericalPrecisionPolicy () const
QSqlResult (const QSqlDriver *db)
Creates a QSqlResult using database driver db.
virtual bool savePrepare (const QString &sqlquery)
Prepares the given query, using the underlying database functionality where possible.
virtual void setActive (bool a)
This function is provided for derived classes to set the internal active state to active.
virtual void setAt (int at)
This function is provided for derived classes to set the internal (zero-based) row position to index.
virtual void setForwardOnly (bool forward)
Sets forward only mode to forward.
virtual void setLastError (const QSqlError &e)
This function is provided for derived classes to set the last error to error.
void setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy policy)
virtual void setQuery (const QString &query)
Sets the current query for the result to query.
virtual void setSelect (bool s)
This function is provided for derived classes to indicate whether or not the current statement is a SQL SELECT statement.
Properties
QIBaseResultPrivate * d
Friends
class QIBaseResultPrivate
Additional Inherited Members
Public Types inherited from QSqlCachedResult
typedef QVector< QVariant > ValueCache
Protected Types inherited from QSqlResult
enum BindingSyntax { PositionalBinding, NamedBinding }
This enum type specifies the different syntaxes for specifying placeholders in prepared queries.
enum VirtualHookOperation { BatchOperation, DetachFromResultSet, SetNumericalPrecision, NextResult }
Detailed Description
Definition at line 57 of file qsql_ibase.h.
Constructors and Destructors
QIBaseResult()
QIBaseResult::QIBaseResult (const QIBaseDriver * db) explicit
Definition at line 870 of file qsql_ibase.cpp.
Referenced by record().
                                                 :
     QSqlCachedResult(db)
 {
     d = new QIBaseResultPrivate(this, db);
 }
~QIBaseResult()
QIBaseResult::~QIBaseResult () virtual
Definition at line 876 of file qsql_ibase.cpp.
 {
     delete d;
 }
Functions
exec()
bool QIBaseResult::exec () virtual
Executes the query, returning true if successful; otherwise returns false.
See also
prepare()
Reimplemented from QSqlResult.
Definition at line 957 of file qsql_ibase.cpp.
Referenced by reset().
 {
     bool ok = true;
     if (!d->trans)
         d->transaction();
     if (!driver() || !driver()->isOpen() || driver()->isOpenError())
         return false;
     setActive(false);
     setAt(QSql::BeforeFirstRow);
     if (d->inda) {
         QVector<QVariant>& values = boundValues();
         int i;
         if (values.count() > d->inda->sqld) {
             qWarning("QIBaseResult::exec: Parameter mismatch, expected %d, got %d parameters",
                      d->inda->sqld, values.count());
             return false;
         }
         int para = 0;
         for (i = 0; i < values.count(); ++i) {
             para = i;
             if (!d->inda->sqlvar[para].sqldata)
                 // skip unknown datatypes
                 continue;
             const QVariant val(values[i]);
             if (d->inda->sqlvar[para].sqltype & 1) {
                 if (val.isNull()) {
                     // set null indicator
                     *(d->inda->sqlvar[para].sqlind) = -1;
                     // and set the value to 0, otherwise it would count as empty string.
                     // it seems to be working with just setting sqlind to -1
                     //*((char*)d->inda->sqlvar[para].sqldata) = 0;
                     continue;
                 }
                 // a value of 0 means non-null.
                 *(d->inda->sqlvar[para].sqlind) = 0;
             }
             switch(d->inda->sqlvar[para].sqltype & ~1) {
             case SQL_INT64:
                 if (d->inda->sqlvar[para].sqlscale < 0)
                     *((qint64*)d->inda->sqlvar[para].sqldata) =
                         (qint64)floor(0.5 + val.toDouble() * pow(10.0, d->inda->sqlvar[para].sqlscale * -1));
                 else
                     *((qint64*)d->inda->sqlvar[para].sqldata) = val.toLongLong();
                 break;
             case SQL_LONG:
                 if (d->inda->sqlvar[para].sqlscale < 0)
                     *((long*)d->inda->sqlvar[para].sqldata) =
                         (long)floor(0.5 + val.toDouble() * pow(10.0, d->inda->sqlvar[para].sqlscale * -1));
                 else
                     *((long*)d->inda->sqlvar[para].sqldata) = (long)val.toLongLong();
                 break;
             case SQL_SHORT:
                 if (d->inda->sqlvar[para].sqlscale < 0)
                     *((short*)d->inda->sqlvar[para].sqldata) =
                         (short)floor(0.5 + val.toDouble() * pow(10.0, d->inda->sqlvar[para].sqlscale * -1));
                 else
                     *((short*)d->inda->sqlvar[para].sqldata) = (short)val.toInt();
                 break;
             case SQL_FLOAT:
                 *((float*)d->inda->sqlvar[para].sqldata) = (float)val.toDouble();
                 break;
             case SQL_DOUBLE:
                 *((double*)d->inda->sqlvar[para].sqldata) = val.toDouble();
                 break;
             case SQL_TIMESTAMP:
                 *((ISC_TIMESTAMP*)d->inda->sqlvar[para].sqldata) = toTimeStamp(val.toDateTime());
                 break;
             case SQL_TYPE_TIME:
                 *((ISC_TIME*)d->inda->sqlvar[para].sqldata) = toTime(val.toTime());
                 break;
             case SQL_TYPE_DATE:
                 *((ISC_DATE*)d->inda->sqlvar[para].sqldata) = toDate(val.toDate());
                 break;
             case SQL_VARYING:
             case SQL_TEXT:
                 qFillBufferWithString(d->inda->sqlvar[para].sqldata, val.toString(),
                                       d->inda->sqlvar[para].sqllen,
                                       (d->inda->sqlvar[para].sqltype & ~1) == SQL_VARYING, false, d->tc);
                 break;
             case SQL_BLOB:
                     ok &= d->writeBlob(para, val.toByteArray());
                     break;
             case SQL_ARRAY:
                     ok &= d->writeArray(para, val.toList());
                     break;
             default:
                     qWarning("QIBaseResult::exec: Unknown datatype %d",
                              d->inda->sqlvar[para].sqltype & ~1);
                     break;
             }
         }
     }
     if (ok) {
         if (colCount() && d->queryType != isc_info_sql_stmt_exec_procedure) {
             isc_dsql_free_statement(d->status, &d->stmt, DSQL_close);
             if (d->isError(QT_TRANSLATE_NOOP("QIBaseResult", "Unable to close statement")))
                 return false;
             cleanup();
         }
         if (d->queryType == isc_info_sql_stmt_exec_procedure)
             isc_dsql_execute2(d->status, &d->trans, &d->stmt, FBVERSION, d->inda, d->sqlda);
         else
             isc_dsql_execute(d->status, &d->trans, &d->stmt, FBVERSION, d->inda);
         if (d->isError(QT_TRANSLATE_NOOP("QIBaseResult", "Unable to execute query")))
             return false;
         // Not all stored procedures necessarily return values.
         if (d->queryType == isc_info_sql_stmt_exec_procedure && d->sqlda && d->sqlda->sqld == 0)
             delDA(d->sqlda);
         if (d->sqlda)
             init(d->sqlda->sqld);
         if (!isSelect())
              d->commit();
         setActive(true);
         return true;
     }
     return false;
 }
gotoNext()
bool QIBaseResult::gotoNext (QSqlCachedResult::ValueCache & row, int rowIdx) protected virtual
Implements QSqlCachedResult.
Definition at line 1090 of file qsql_ibase.cpp.
 {
     ISC_STATUS stat = 0;
     // Stored Procedures are special - they populate our d->sqlda when executing,
     // so we don't have to call isc_dsql_fetch
     if (d->queryType == isc_info_sql_stmt_exec_procedure) {
         // the first "fetch" shall succeed, all consecutive ones will fail since
         // we only have one row to fetch for stored procedures
         if (rowIdx != 0)
             stat = 100;
     } else {
         stat = isc_dsql_fetch(d->status, &d->stmt, FBVERSION, d->sqlda);
     }
     if (stat == 100) {
         // no more rows
         setAt(QSql::AfterLastRow);
         return false;
     }
     if (d->isError(QT_TRANSLATE_NOOP("QIBaseResult", "Could not fetch next item"),
                    QSqlError::StatementError))
         return false;
     if (rowIdx < 0) // not interested in actual values
         return true;
     for (int i = 0; i < d->sqlda->sqld; ++i) {
         int idx = rowIdx + i;
         char *buf = d->sqlda->sqlvar[i].sqldata;
         int size = d->sqlda->sqlvar[i].sqllen;
         Q_ASSERT(buf);
         if ((d->sqlda->sqlvar[i].sqltype & 1) && *d->sqlda->sqlvar[i].sqlind) {
             // null value
             QVariant v;
             v.convert(qIBaseTypeName2(d->sqlda->sqlvar[i].sqltype, d->sqlda->sqlvar[i].sqlscale < 0));
             if(v.type() == QVariant::Double) {
                 switch(numericalPrecisionPolicy()) {
                 case QSql::LowPrecisionInt32:
                     v.convert(QVariant::Int);
                     break;
                 case QSql::LowPrecisionInt64:
                     v.convert(QVariant::LongLong);
                     break;
                 case QSql::HighPrecision:
                     v.convert(QVariant::String);
                     break;
                 }
             }
             row[idx] = v;
             continue;
         }
         switch(d->sqlda->sqlvar[i].sqltype & ~1) {
         case SQL_VARYING:
             // pascal strings - a short with a length information followed by the data
             if (d->tc)
                 row[idx] = d->tc->toUnicode(buf + sizeof(short), *(short*)buf);
             else
                 row[idx] = QString::fromUtf8(buf + sizeof(short), *(short*)buf);
             break;
         case SQL_INT64:
             if (d->sqlda->sqlvar[i].sqlscale < 0)
                 row[idx] = *(qint64*)buf * pow(10.0, d->sqlda->sqlvar[i].sqlscale);
             else
                 row[idx] = QVariant(*(qint64*)buf);
             break;
         case SQL_LONG:
             if (d->sqlda->sqlvar[i].sqllen == 4)
                 if (d->sqlda->sqlvar[i].sqlscale < 0)
                     row[idx] = QVariant(*(qint32*)buf * pow(10.0, d->sqlda->sqlvar[i].sqlscale));
                 else
                     row[idx] = QVariant(*(qint32*)buf);
             else
                 row[idx] = QVariant(*(qint64*)buf);
             break;
         case SQL_SHORT:
             if (d->sqlda->sqlvar[i].sqlscale < 0)
                 row[idx] = QVariant(long((*(short*)buf)) * pow(10.0, d->sqlda->sqlvar[i].sqlscale));
             else
                 row[idx] = QVariant(int((*(short*)buf)));
             break;
         case SQL_FLOAT:
             row[idx] = QVariant(double((*(float*)buf)));
             break;
         case SQL_DOUBLE:
             row[idx] = QVariant(*(double*)buf);
             break;
         case SQL_TIMESTAMP:
             row[idx] = fromTimeStamp(buf);
             break;
         case SQL_TYPE_TIME:
             row[idx] = fromTime(buf);
             break;
         case SQL_TYPE_DATE:
             row[idx] = fromDate(buf);
             break;
         case SQL_TEXT:
             if (d->tc)
                 row[idx] = d->tc->toUnicode(buf, size);
             else
                 row[idx] = QString::fromUtf8(buf, size);
             break;
         case SQL_BLOB:
             row[idx] = d->fetchBlob((ISC_QUAD*)buf);
             break;
         case SQL_ARRAY:
             row[idx] = d->fetchArray(i, (ISC_QUAD*)buf);
             break;
         default:
             // unknown type - don't even try to fetch
             row[idx] = QVariant();
             break;
         }
         if (d->sqlda->sqlvar[i].sqlscale < 0) {
             QVariant v = row[idx];
             switch(numericalPrecisionPolicy()) {
             case QSql::LowPrecisionInt32:
                 if(v.convert(QVariant::Int))
                     row[idx]=v;
                 break;
             case QSql::LowPrecisionInt64:
                 if(v.convert(QVariant::LongLong))
                     row[idx]=v;
                 break;
             case QSql::LowPrecisionDouble:
                 if(v.convert(QVariant::Double))
                     row[idx]=v;
                 break;
             case QSql::HighPrecision:
                 if(v.convert(QVariant::String))
                     row[idx]=v;
                 break;
             }
         }
     }
     return true;
 }
handle()
QVariant QIBaseResult::handle () const virtual
Returns the low-level database handle for this result set wrapped in a QVariant or an invalid QVariant if there is no handle.
Warning
Use this with uttermost care and only if you know what you're doing.
The handle returned here can become a stale pointer if the result is modified (for example, if you clear it).
The handle can be NULL if the result was not executed yet.
The handle returned here is database-dependent, you should query the type name of the variant before accessing it.
This example retrieves the handle for a sqlite result:
QSqlQuery query = ...
QVariant v = query.result()->handle();
if (v.isValid() && qstrcmp(v.typeName(), "sqlite3_stmt*")) {
    // v.data() returns a pointer to the handle
    sqlite3_stmt *handle = *static_cast<sqlite3_stmt **>(v.data());
    if (handle != 0) { // check that it is not NULL
        ...
    }
}
This snippet returns the handle for PostgreSQL or MySQL:
if (v.typeName() == "PGresult*") {
    PGresult *handle = *static_cast<PGresult **>(v.data());
    if (handle != 0) ...
}
if (v.typeName() == "MYSQL_STMT*") {
    MYSQL_STMT *handle = *static_cast<MYSQL_STMT **>(v.data());
    if (handle != 0) ...
}
See also
QSqlDriver::handle()
Reimplemented from QSqlResult.
Definition at line 1364 of file qsql_ibase.cpp.
Referenced by QIBaseDriver::open().
 {
     return QVariant(qRegisterMetaType<isc_stmt_handle>("isc_stmt_handle"), &d->stmt);
 }
numRowsAffected()
int QIBaseResult::numRowsAffected () protected virtual
Returns the number of rows affected by the last query executed, or -1 if it cannot be determined or if the query is a SELECT statement.
See also
size()
Implements QSqlResult.
Definition at line 1281 of file qsql_ibase.cpp.
 {
     static char acCountInfo[] = {isc_info_sql_records};
     char cCountType;
     switch (d->queryType) {
     case isc_info_sql_stmt_select:
         cCountType = isc_info_req_select_count;
         break;
     case isc_info_sql_stmt_update:
         cCountType = isc_info_req_update_count;
         break;
     case isc_info_sql_stmt_delete:
         cCountType = isc_info_req_delete_count;
         break;
     case isc_info_sql_stmt_insert:
         cCountType = isc_info_req_insert_count;
         break;
     default:
         qWarning() << "numRowsAffected: Unknown statement type (" << d->queryType << ")";
         return -1;
     }
     char acBuffer[33];
     int iResult = -1;
     isc_dsql_sql_info(d->status, &d->stmt, sizeof(acCountInfo), acCountInfo, sizeof(acBuffer), acBuffer);
     if (d->isError(QT_TRANSLATE_NOOP("QIBaseResult", "Could not get statement info"),
                    QSqlError::StatementError))
         return -1;
     for (char *pcBuf = acBuffer + 3; *pcBuf != isc_info_end; /*nothing*/) {
         char cType = *pcBuf++;
         short sLength = isc_vax_integer (pcBuf, 2);
         pcBuf += 2;
         int iValue = isc_vax_integer (pcBuf, sLength);
         pcBuf += sLength;
         if (cType == cCountType) {
             iResult = iValue;
             break;
         }
     }
     return iResult;
 }
prepare()
bool QIBaseResult::prepare (const QString & query) virtual
Prepares the given query for execution; the query will normally use placeholders so that it can be executed repeatedly.
Returns true if the query is prepared successfully; otherwise returns false.
See also
exec()
Reimplemented from QSqlResult.
Definition at line 881 of file qsql_ibase.cpp.
Referenced by reset().
 {
 //     qDebug("prepare: %s", qPrintable(query));
     if (!driver() || !driver()->isOpen() || driver()->isOpenError())
         return false;
     d->cleanup();
     setActive(false);
     setAt(QSql::BeforeFirstRow);
     createDA(d->sqlda);
     if (d->sqlda == (XSQLDA*)0) {
         qWarning()<<"QIOBaseResult: createDA(): failed to allocate memory";
         return false;
     }
     createDA(d->inda);
     if (d->inda == (XSQLDA*)0){
         qWarning()<<"QIOBaseResult: createDA():  failed to allocate memory";
         return false;
     }
     if (!d->transaction())
         return false;
     isc_dsql_allocate_statement(d->status, &d->ibase, &d->stmt);
     if (d->isError(QT_TRANSLATE_NOOP("QIBaseResult", "Could not allocate statement"),
                    QSqlError::StatementError))
         return false;
     isc_dsql_prepare(d->status, &d->trans, &d->stmt, 0,
         const_cast<char*>(encodeString(d->tc, query).constData()), FBVERSION, d->sqlda);
     if (d->isError(QT_TRANSLATE_NOOP("QIBaseResult", "Could not prepare statement"),
                    QSqlError::StatementError))
         return false;
     isc_dsql_describe_bind(d->status, &d->stmt, FBVERSION, d->inda);
     if (d->isError(QT_TRANSLATE_NOOP("QIBaseResult",
                     "Could not describe input statement"), QSqlError::StatementError))
         return false;
     if (d->inda->sqld > d->inda->sqln) {
         enlargeDA(d->inda, d->inda->sqld);
         if (d->inda == (XSQLDA*)0) {
             qWarning()<<"QIOBaseResult: enlargeDA(): failed to allocate memory";
             return false;
         }
         isc_dsql_describe_bind(d->status, &d->stmt, FBVERSION, d->inda);
         if (d->isError(QT_TRANSLATE_NOOP("QIBaseResult",
                         "Could not describe input statement"), QSqlError::StatementError))
             return false;
     }
     initDA(d->inda);
     if (d->sqlda->sqld > d->sqlda->sqln) {
         // need more field descriptors
         enlargeDA(d->sqlda, d->sqlda->sqld);
         if (d->sqlda == (XSQLDA*)0) {
             qWarning()<<"QIOBaseResult: enlargeDA(): failed to allocate memory";
             return false;
         }
         isc_dsql_describe(d->status, &d->stmt, FBVERSION, d->sqlda);
         if (d->isError(QT_TRANSLATE_NOOP("QIBaseResult", "Could not describe statement"),
                        QSqlError::StatementError))
             return false;
     }
     initDA(d->sqlda);
     setSelect(d->isSelect());
     if (!isSelect()) {
         free(d->sqlda);
         d->sqlda = 0;
     }
     return true;
 }
record()
QSqlRecord QIBaseResult::record () const protected virtual
Returns the current record if the query is active; otherwise returns an empty QSqlRecord.
The default implementation always returns an empty QSqlRecord.
See also
isActive()
Reimplemented from QSqlResult.
Definition at line 1325 of file qsql_ibase.cpp.
Referenced by QIBaseDriver::open().
 {
     QSqlRecord rec;
     if (!isActive() || !d->sqlda)
         return rec;
     XSQLVAR v;
     for (int i = 0; i < d->sqlda->sqld; ++i) {
         v = d->sqlda->sqlvar[i];
         QSqlField f(QString::fromLatin1(v.aliasname, v.aliasname_length).simplified(),
                     qIBaseTypeName2(v.sqltype, v.sqlscale < 0));
         f.setLength(v.sqllen);
         f.setPrecision(qAbs(v.sqlscale));
         f.setRequiredStatus((v.sqltype & 1) == 0 ? QSqlField::Required : QSqlField::Optional);
         if(v.sqlscale < 0) {
             QSqlQuery q(new QIBaseResult(d->db));
             q.setForwardOnly(true);
             q.exec(QLatin1String("select b.RDB$FIELD_PRECISION, b.RDB$FIELD_SCALE, b.RDB$FIELD_LENGTH, a.RDB$NULL_FLAG "
                     "FROM RDB$RELATION_FIELDS a, RDB$FIELDS b "
                     "WHERE b.RDB$FIELD_NAME = a.RDB$FIELD_SOURCE "
                     "AND a.RDB$RELATION_NAME = '") + QString::fromAscii(v.relname, v.relname_length).toUpper() + QLatin1String("' "
                     "AND a.RDB$FIELD_NAME = '") + QString::fromAscii(v.sqlname, v.sqlname_length).toUpper() + QLatin1String("' "));
             if(q.first()) {
                 if(v.sqlscale < 0) {
                     f.setLength(q.value(0).toInt());
                     f.setPrecision(qAbs(q.value(1).toInt()));
                 } else {
                     f.setLength(q.value(2).toInt());
                     f.setPrecision(0);
                 }
                 f.setRequiredStatus(q.value(3).toBool() ? QSqlField::Required : QSqlField::Optional);
             }
         }
         f.setSqlType(v.sqltype);
         rec.append(f);
     }
     return rec;
 }
reset()
bool QIBaseResult::reset (const QString & query) protected virtual
Sets the result to use the SQL statement query for subsequent data retrieval.
Derived classes must reimplement this function and apply the query to the database. This function is only called after the result is set to an inactive state and is positioned before the first record of the new result. Derived classes should return true if the query was successful and ready to be used, or false otherwise.
See also
setQuery()
Implements QSqlResult.
Definition at line 1083 of file qsql_ibase.cpp.
 {
     if (!prepare(query))
         return false;
     return exec();
 }
size()
int QIBaseResult::size () protected virtual
Returns the size of the SELECT result, or -1 if it cannot be determined or if the query is not a SELECT statement.
See also
numRowsAffected()
FIXME
Implements QSqlResult.
Definition at line 1230 of file qsql_ibase.cpp.
Referenced by gotoNext().
 {
     return -1;
 #if 0
     static char sizeInfo[] = {isc_info_sql_records};
     char buf[64];
     //qDebug() << sizeInfo;
     if (!isActive() || !isSelect())
         return -1;
         char ct;
         short len;
         int val = 0;
 //    while(val == 0) {
         isc_dsql_sql_info(d->status, &d->stmt, sizeof(sizeInfo), sizeInfo, sizeof(buf), buf);
 //        isc_database_info(d->status, &d->ibase, sizeof(sizeInfo), sizeInfo, sizeof(buf), buf);
         for(int i = 0; i < 66; ++i)
             qDebug() << QString::number(buf[i]);
         for (char* c = buf + 3; *c != isc_info_end; /*nothing*/) {
             ct = *(c++);
             len = isc_vax_integer(c, 2);
             c += 2;
             val = isc_vax_integer(c, len);
             c += len;
             qDebug() << "size" << val;
             if (ct == isc_info_req_select_count)
                 return val;
         }
         //qDebug() << "size -1";
         return -1;
         unsigned int i, result_size;
         if (buf[0] == isc_info_sql_records) {
             i = 3;
             result_size = isc_vax_integer(&buf[1],2);
             while (buf[i] != isc_info_end && i < result_size) {
                 len = (short)isc_vax_integer(&buf[i+1],2);
                 if (buf[i] == isc_info_req_select_count)
                      return (isc_vax_integer(&buf[i+3],len));
                 i += len+3;
            }
         }
 //    }
     return -1;
 #endif
 }
Friends and Related Functions
QIBaseResultPrivate
friend class QIBaseResultPrivate friend
Definition at line 59 of file qsql_ibase.h.
Referenced by QIBaseResult().
Properties
d
QIBaseResultPrivate* QIBaseResult::d private
Definition at line 77 of file qsql_ibase.h.
Referenced by exec(), gotoNext(), handle(), numRowsAffected(), prepare(), QIBaseResult(), record(), size(), and ~QIBaseResult().
The documentation for this class was generated from the following files:
/src/sql/drivers/ibase/qsql_ibase.h
/src/sql/drivers/ibase/qsql_ibase.cpp