Qt 4.8: QScriptDebuggerCommand Class Reference
QScriptDebuggerCommand Class Reference
The QScriptDebuggerCommand class represents a command issued to a QScriptDebuggerFrontend.
#include <qscriptdebuggercommand_p.h>
Public Types
enum Attribute {
ScriptID, FileName, LineNumber, Program,
BreakpointID, BreakpointData, ContextIndex, ScriptValue,
StepCount, IteratorID, Name, SubordinateScriptValue,
SnapshotID, UserAttribute = 1000, MaxUserAttribute = 32767
}
enum Type {
None, Interrupt, Continue, StepInto,
StepOver, StepOut, RunToLocation, RunToLocationByID,
ForceReturn, Resume, SetBreakpoint, DeleteBreakpoint,
DeleteAllBreakpoints, GetBreakpoints, GetBreakpointData, SetBreakpointData,
GetScripts, GetScriptData, ScriptsCheckpoint, GetScriptsDelta,
ResolveScript, GetBacktrace, GetContextCount, GetContextInfo,
GetContextState, GetContextID, GetThisObject, GetActivationObject,
GetScopeChain, ContextsCheckpoint, GetPropertyExpressionValue, GetCompletions,
NewScriptObjectSnapshot, ScriptObjectSnapshotCapture, DeleteScriptObjectSnapshot, NewScriptValueIterator,
GetPropertiesByIterator, DeleteScriptValueIterator, Evaluate, SetScriptValueProperty,
ScriptValueToString, ClearExceptions, UserCommand = 1000, MaxUserCommand = 32767
}
Public Functions
QVariant attribute (Attribute attribute, const QVariant &defaultValue=QVariant()) const
Returns the value of the given attribute, or defaultValue if the attribute is not defined.
QHash< Attribute, QVariant > attributes () const
QScriptBreakpointData breakpointData () const
int breakpointId () const
int contextIndex () const
QString fileName () const
Returns the FileName attribute of this command converted to a string.
int iteratorId () const
int lineNumber () const
Returns the LineNumber attribute of this command converted to an int.
QString name () const
bool operator!= (const QScriptDebuggerCommand &other) const
Returns true if this QScriptDebuggerCommand is not equal to the other command, otherwise returns false.
QScriptDebuggerCommand & operator= (const QScriptDebuggerCommand &other)
Assigns the other value to this QScriptDebuggerCommand.
bool operator== (const QScriptDebuggerCommand &other) const
Returns true if this QScriptDebuggerCommand is equal to the other command, otherwise returns false.
QString program () const
QScriptDebuggerCommand ()
Constructs a QScriptDebuggerCommand of type None.
QScriptDebuggerCommand (Type type)
Constructs a QScriptDebuggerCommand of the given type, with no attributes defined.
QScriptDebuggerCommand (const QScriptDebuggerCommand &other)
Constructs a QScriptDebuggerCommand that is a copy of the other command.
qint64 scriptId () const
Returns the ScriptID attribute of this command converted to a qint64.
QScriptDebuggerValue scriptValue () const
void setAttribute (Attribute attribute, const QVariant &value)
Sets the value of the given attribute.
void setBreakpointData (const QScriptBreakpointData &data)
void setBreakpointId (int id)
void setContextIndex (int index)
void setFileName (const QString &fileName)
void setIteratorId (int id)
void setLineNumber (int lineNumber)
void setName (const QString &name)
void setProgram (const QString &program)
void setScriptId (qint64 id)
void setScriptValue (const QScriptDebuggerValue &value)
void setSnapshotId (int id)
void setSubordinateScriptValue (const QScriptDebuggerValue &value)
int snapshotId () const
QScriptDebuggerValue subordinateScriptValue () const
Type type () const
Returns the type of this command.
~QScriptDebuggerCommand ()
Destroys this QScriptDebuggerCommand.
Static Public Functions
static QScriptDebuggerCommand clearExceptionsCommand ()
static QScriptDebuggerCommand contextsCheckpoint ()
static QScriptDebuggerCommand continueCommand ()
static QScriptDebuggerCommand deleteAllBreakpointsCommand ()
static QScriptDebuggerCommand deleteBreakpointCommand (int id)
static QScriptDebuggerCommand deleteScriptObjectSnapshotCommand (int id)
static QScriptDebuggerCommand deleteScriptValueIteratorCommand (int id)
static QScriptDebuggerCommand evaluateCommand (int contextIndex, const QString &program, const QString &fileName=QString(), int lineNumber=1)
static QScriptDebuggerCommand forceReturnCommand (int contextIndex, const QScriptDebuggerValue &value)
static QScriptDebuggerCommand getActivationObjectCommand (int contextIndex)
static QScriptDebuggerCommand getBacktraceCommand ()
static QScriptDebuggerCommand getBreakpointDataCommand (int id)
static QScriptDebuggerCommand getBreakpointsCommand ()
static QScriptDebuggerCommand getCompletions (int contextIndex, const QStringList &path)
static QScriptDebuggerCommand getContextCountCommand ()
static QScriptDebuggerCommand getContextIdCommand (int contextIndex)
static QScriptDebuggerCommand getContextInfoCommand (int contextIndex)
static QScriptDebuggerCommand getContextStateCommand (int contextIndex)
static QScriptDebuggerCommand getPropertiesByIteratorCommand (int id, int count)
static QScriptDebuggerCommand getPropertyExpressionValue (int contextIndex, int lineNumber, const QStringList &path)
static QScriptDebuggerCommand getScopeChainCommand (int contextIndex)
static QScriptDebuggerCommand getScriptDataCommand (qint64 id)
static QScriptDebuggerCommand getScriptsCommand ()
static QScriptDebuggerCommand getScriptsDeltaCommand ()
static QScriptDebuggerCommand getThisObjectCommand (int contextIndex)
static QScriptDebuggerCommand interruptCommand ()
static QScriptDebuggerCommand newScriptObjectSnapshotCommand ()
static QScriptDebuggerCommand newScriptValueIteratorCommand (const QScriptDebuggerValue &object)
static QScriptDebuggerCommand resolveScriptCommand (const QString &fileName)
static QScriptDebuggerCommand resumeCommand ()
static QScriptDebuggerCommand runToLocationCommand (const QString &fileName, int lineNumber)
static QScriptDebuggerCommand runToLocationCommand (qint64 scriptId, int lineNumber)
static QScriptDebuggerCommand scriptObjectSnapshotCaptureCommand (int id, const QScriptDebuggerValue &object)
static QScriptDebuggerCommand scriptsCheckpointCommand ()
static QScriptDebuggerCommand scriptValueToStringCommand (const QScriptDebuggerValue &value)
static QScriptDebuggerCommand setBreakpointCommand (const QString &fileName, int lineNumber)
static QScriptDebuggerCommand setBreakpointCommand (const QScriptBreakpointData &data)
static QScriptDebuggerCommand setBreakpointDataCommand (int id, const QScriptBreakpointData &data)
static QScriptDebuggerCommand setScriptValuePropertyCommand (const QScriptDebuggerValue &object, const QString &name, const QScriptDebuggerValue &value)
static QScriptDebuggerCommand stepIntoCommand (int count=1)
static QScriptDebuggerCommand stepOutCommand ()
static QScriptDebuggerCommand stepOverCommand (int count=1)
Properties
QScopedPointer< QScriptDebuggerCommandPrivate > d_ptr
Friends
Q_AUTOTEST_EXPORT QDataStream & operator<< (QDataStream &, const QScriptDebuggerCommand &)
Writes the given command to the specified stream.
Q_AUTOTEST_EXPORT QDataStream & operator>> (QDataStream &, QScriptDebuggerCommand &)
Reads a QScriptDebuggerCommand from the specified stream into the given command.
Detailed Description
The QScriptDebuggerCommand class represents a command issued to a QScriptDebuggerFrontend.
Since
4.5
Warning
This function is not part of the public interface.
A debugger command is described by a command type and zero or more attributes. Such commands are generated internally by the QScriptDebuggerFrontend class (through the scheduleXXX commands). A command is typically passed on to a QScriptDebuggerCommandExecutor that applies the command to a QScriptDebuggerBackend.
Definition at line 68 of file qscriptdebuggercommand_p.h.
Enumerations
Attribute
enum QScriptDebuggerCommand::Attribute
Enumerator
ScriptID
FileName
LineNumber
Program
BreakpointID
BreakpointData
ContextIndex
ScriptValue
StepCount
IteratorID
Name
SubordinateScriptValue
SnapshotID
UserAttribute
MaxUserAttribute
Definition at line 131 of file qscriptdebuggercommand_p.h.
                    {
         ScriptID,
         FileName,
         LineNumber,
         Program,
         BreakpointID,
         BreakpointData,
         ContextIndex,
         ScriptValue,
         StepCount,
         IteratorID,
         Name,
         SubordinateScriptValue,
         SnapshotID,
         UserAttribute = 1000,
         MaxUserAttribute = 32767
     };
Type
enum QScriptDebuggerCommand::Type
Enumerator
None
Interrupt
Continue
StepInto
StepOver
StepOut
RunToLocation
RunToLocationByID
ForceReturn
Resume
SetBreakpoint
DeleteBreakpoint
DeleteAllBreakpoints
GetBreakpoints
GetBreakpointData
SetBreakpointData
GetScripts
GetScriptData
ScriptsCheckpoint
GetScriptsDelta
ResolveScript
GetBacktrace
GetContextCount
GetContextInfo
GetContextState
GetContextID
GetThisObject
GetActivationObject
GetScopeChain
ContextsCheckpoint
GetPropertyExpressionValue
GetCompletions
NewScriptObjectSnapshot
ScriptObjectSnapshotCapture
DeleteScriptObjectSnapshot
NewScriptValueIterator
GetPropertiesByIterator
DeleteScriptValueIterator
Evaluate
SetScriptValueProperty
ScriptValueToString
ClearExceptions
UserCommand
MaxUserCommand
Definition at line 74 of file qscriptdebuggercommand_p.h.
               {
         None,
         Interrupt,
         Continue,
         StepInto,
         StepOver,
         StepOut,
         RunToLocation,
         RunToLocationByID,
         ForceReturn,
         Resume,
         SetBreakpoint,
         DeleteBreakpoint,
         DeleteAllBreakpoints,
         GetBreakpoints,
         GetBreakpointData,
         SetBreakpointData,
         GetScripts,
         GetScriptData,
         ScriptsCheckpoint,
         GetScriptsDelta,
         ResolveScript,
         GetBacktrace,
         GetContextCount,
         GetContextInfo,
         GetContextState,
         GetContextID,
         GetThisObject,
         GetActivationObject,
         GetScopeChain,
         ContextsCheckpoint,
         GetPropertyExpressionValue,
         GetCompletions,
         NewScriptObjectSnapshot,
         ScriptObjectSnapshotCapture,
         DeleteScriptObjectSnapshot,
         NewScriptValueIterator,
         GetPropertiesByIterator,
         DeleteScriptValueIterator,
         Evaluate,
         SetScriptValueProperty,
         ScriptValueToString,
         ClearExceptions,
         UserCommand = 1000,
         MaxUserCommand = 32767
     };
Constructors and Destructors
QScriptDebuggerCommand() [1/3]
QScriptDebuggerCommand::QScriptDebuggerCommand ()
Constructs a QScriptDebuggerCommand of type None.
Definition at line 94 of file qscriptdebuggercommand.cpp.
     : d_ptr(new QScriptDebuggerCommandPrivate)
 {
     d_ptr->type = None;
 }
QScriptDebuggerCommand() [2/3]
QScriptDebuggerCommand::QScriptDebuggerCommand (Type type)
Constructs a QScriptDebuggerCommand of the given type, with no attributes defined.
Definition at line 104 of file qscriptdebuggercommand.cpp.
     : d_ptr(new QScriptDebuggerCommandPrivate)
 {
     d_ptr->type = type;
 }
QScriptDebuggerCommand() [3/3]
QScriptDebuggerCommand::QScriptDebuggerCommand (const QScriptDebuggerCommand & other)
Constructs a QScriptDebuggerCommand that is a copy of the other command.
Definition at line 114 of file qscriptdebuggercommand.cpp.
     : d_ptr(new QScriptDebuggerCommandPrivate)
 {
     *d_ptr = *other.d_ptr;
 }
~QScriptDebuggerCommand()
QScriptDebuggerCommand::~QScriptDebuggerCommand ()
Destroys this QScriptDebuggerCommand.
Definition at line 123 of file qscriptdebuggercommand.cpp.
 {
 }
Functions
attribute()
QVariant QScriptDebuggerCommand::attribute (Attribute attribute, const QVariant & defaultValue = QVariant()) const
Returns the value of the given attribute, or defaultValue if the attribute is not defined.
Definition at line 149 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), and setAttribute().
 {
     Q_D(const QScriptDebuggerCommand);
     return d->attributes.value(attribute, defaultValue);
 }
attributes()
QHash< QScriptDebuggerCommand::Attribute, QVariant > QScriptDebuggerCommand::attributes () const
Definition at line 169 of file qscriptdebuggercommand.cpp.
 {
     Q_D(const QScriptDebuggerCommand);
     return d->attributes;
 }
breakpointData()
QScriptBreakpointData QScriptDebuggerCommand::breakpointData () const
Definition at line 253 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), and QScriptDebuggerPrivate::handleResponse().
 {
     Q_D(const QScriptDebuggerCommand);
     return qvariant_cast<QScriptBreakpointData>(d->attributes.value(BreakpointData));
 }
breakpointId()
int QScriptDebuggerCommand::breakpointId () const
Definition at line 241 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), and QScriptDebuggerPrivate::handleResponse().
 {
     Q_D(const QScriptDebuggerCommand);
     return d->attributes.value(BreakpointID, -1).toInt();
 }
clearExceptionsCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::clearExceptionsCommand () static
Definition at line 657 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleClearExceptions().
 {
     QScriptDebuggerCommand cmd(ClearExceptions);
     return cmd;
 }
contextIndex()
int QScriptDebuggerCommand::contextIndex () const
Definition at line 277 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerCommand);
     return d->attributes.value(ContextIndex, -1).toInt();
 }
contextsCheckpoint()
QScriptDebuggerCommand QScriptDebuggerCommand::contextsCheckpoint () static
Definition at line 558 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleContextsCheckpoint().
 {
     QScriptDebuggerCommand cmd(ContextsCheckpoint);
     return cmd;
 }
continueCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::continueCommand () static
Definition at line 368 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleContinue().
 {
     QScriptDebuggerCommand cmd(Continue);
     return cmd;
 }
deleteAllBreakpointsCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::deleteAllBreakpointsCommand () static
Definition at line 445 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleDeleteAllBreakpoints().
 {
     QScriptDebuggerCommand cmd(DeleteAllBreakpoints);
     return cmd;
 }
deleteBreakpointCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::deleteBreakpointCommand (int id) static
Definition at line 438 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleDeleteBreakpoint().
 {
     QScriptDebuggerCommand cmd(DeleteBreakpoint);
     cmd.setBreakpointId(id);
     return cmd;
 }
deleteScriptObjectSnapshotCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::deleteScriptObjectSnapshotCommand (int id) static
Definition at line 598 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleDeleteScriptObjectSnapshot().
 {
     QScriptDebuggerCommand cmd(DeleteScriptObjectSnapshot);
     cmd.setSnapshotId(id);
     return cmd;
 }
deleteScriptValueIteratorCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::deleteScriptValueIteratorCommand (int id) static
Definition at line 621 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleDeleteScriptValueIterator().
 {
     QScriptDebuggerCommand cmd(DeleteScriptValueIterator);
     cmd.setIteratorId(id);
     return cmd;
 }
evaluateCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::evaluateCommand (int contextIndex, const QString & program, const QString & fileName = QString(), int lineNumber = 1) static
Definition at line 628 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleEvaluate().
 {
     QScriptDebuggerCommand cmd(Evaluate);
     cmd.setContextIndex(contextIndex);
     cmd.setProgram(program);
     cmd.setFileName(fileName);
     cmd.setLineNumber(lineNumber);
     return cmd;
 }
fileName()
QString QScriptDebuggerCommand::fileName () const
Returns the FileName attribute of this command converted to a string.
This function is provided for convenience.
See also
attribute()
Definition at line 181 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), and setFileName().
 {
     Q_D(const QScriptDebuggerCommand);
     return d->attributes.value(FileName).toString();
 }
forceReturnCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::forceReturnCommand (int contextIndex, const QScriptDebuggerValue & value) static
Definition at line 410 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleForceReturn().
 {
     QScriptDebuggerCommand cmd(ForceReturn);
     cmd.setContextIndex(contextIndex);
     cmd.setScriptValue(value);
     return cmd;
 }
getActivationObjectCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getActivationObjectCommand (int contextIndex) static
Definition at line 544 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetActivationObject().
 {
     QScriptDebuggerCommand cmd(GetActivationObject);
     cmd.setContextIndex(contextIndex);
     return cmd;
 }
getBacktraceCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getBacktraceCommand () static
Definition at line 504 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetBacktrace().
 {
     QScriptDebuggerCommand cmd(GetBacktrace);
     return cmd;
 }
getBreakpointDataCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getBreakpointDataCommand (int id) static
Definition at line 457 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetBreakpointData().
 {
     QScriptDebuggerCommand cmd(GetBreakpointData);
     cmd.setBreakpointId(id);
     return cmd;
 }
getBreakpointsCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getBreakpointsCommand () static
Definition at line 451 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetBreakpoints().
 {
     QScriptDebuggerCommand cmd(GetBreakpoints);
     return cmd;
 }
getCompletions()
QScriptDebuggerCommand QScriptDebuggerCommand::getCompletions (int contextIndex, const QStringList & path) static
Definition at line 574 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetCompletions().
 {
     QScriptDebuggerCommand cmd(GetCompletions);
     cmd.setContextIndex(contextIndex);
     cmd.setAttribute(UserAttribute, path);
     return cmd;
 }
getContextCountCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getContextCountCommand () static
Definition at line 510 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetContextCount().
 {
     QScriptDebuggerCommand cmd(GetContextCount);
     return cmd;
 }
getContextIdCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getContextIdCommand (int contextIndex) static
Definition at line 530 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetContextId().
 {
     QScriptDebuggerCommand cmd(GetContextID);
     cmd.setContextIndex(contextIndex);
     return cmd;
 }
getContextInfoCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getContextInfoCommand (int contextIndex) static
Definition at line 523 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetContextInfo().
 {
     QScriptDebuggerCommand cmd(GetContextInfo);
     cmd.setContextIndex(contextIndex);
     return cmd;
 }
getContextStateCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getContextStateCommand (int contextIndex) static
Definition at line 516 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetContextState().
 {
     QScriptDebuggerCommand cmd(GetContextState);
     cmd.setContextIndex(contextIndex);
     return cmd;
 }
getPropertiesByIteratorCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getPropertiesByIteratorCommand (int id, int count) static
Definition at line 613 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetPropertiesByIterator().
 {
     Q_UNUSED(count);
     QScriptDebuggerCommand cmd(GetPropertiesByIterator);
     cmd.setIteratorId(id);
     return cmd;
 }
getPropertyExpressionValue()
QScriptDebuggerCommand QScriptDebuggerCommand::getPropertyExpressionValue (int contextIndex, int lineNumber, const QStringList & path) static
Definition at line 564 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetPropertyExpressionValue().
 {
     QScriptDebuggerCommand cmd(GetPropertyExpressionValue);
     cmd.setContextIndex(contextIndex);
     cmd.setLineNumber(lineNumber);
     cmd.setAttribute(UserAttribute, path);
     return cmd;
 }
getScopeChainCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getScopeChainCommand (int contextIndex) static
Definition at line 551 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetScopeChain().
 {
     QScriptDebuggerCommand cmd(GetScopeChain);
     cmd.setContextIndex(contextIndex);
     return cmd;
 }
getScriptDataCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getScriptDataCommand (qint64 id) static
Definition at line 478 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetScriptData().
 {
     QScriptDebuggerCommand cmd(GetScriptData);
     cmd.setScriptId(id);
     return cmd;
 }
getScriptsCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getScriptsCommand () static
Definition at line 472 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetScripts().
 {
     QScriptDebuggerCommand cmd(GetScripts);
     return cmd;
 }
getScriptsDeltaCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getScriptsDeltaCommand () static
Definition at line 491 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetScriptsDelta().
 {
     QScriptDebuggerCommand cmd(GetScriptsDelta);
     return cmd;
 }
getThisObjectCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::getThisObjectCommand (int contextIndex) static
Definition at line 537 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleGetThisObject().
 {
     QScriptDebuggerCommand cmd(GetThisObject);
     cmd.setContextIndex(contextIndex);
     return cmd;
 }
interruptCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::interruptCommand () static
Definition at line 362 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleInterrupt().
 {
     QScriptDebuggerCommand cmd(Interrupt);
     return cmd;
 }
iteratorId()
int QScriptDebuggerCommand::iteratorId () const
Definition at line 289 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerCommand);
     return d->attributes.value(IteratorID, -1).toInt();
 }
lineNumber()
int QScriptDebuggerCommand::lineNumber () const
Returns the LineNumber attribute of this command converted to an int.
This function is provided for convenience.
See also
attribute()
Definition at line 199 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), and setLineNumber().
 {
     Q_D(const QScriptDebuggerCommand);
     return d->attributes.value(LineNumber, -1).toInt();
 }
name()
QString QScriptDebuggerCommand::name () const
Definition at line 301 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), and setName().
 {
     Q_D(const QScriptDebuggerCommand);
     return d->attributes.value(Name).toString();
 }
newScriptObjectSnapshotCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::newScriptObjectSnapshotCommand () static
Definition at line 583 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleNewScriptObjectSnapshot().
 {
     QScriptDebuggerCommand cmd(NewScriptObjectSnapshot);
     return cmd;
 }
newScriptValueIteratorCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::newScriptValueIteratorCommand (const QScriptDebuggerValue & object) static
Definition at line 605 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleNewScriptValueIterator().
 {
     QScriptDebuggerCommand cmd(NewScriptValueIterator);
     Q_ASSERT(object.type() == QScriptDebuggerValue::ObjectValue);
     cmd.setScriptValue(object);
     return cmd;
 }
operator!=()
bool QScriptDebuggerCommand::operator!= (const QScriptDebuggerCommand & other) const
Returns true if this QScriptDebuggerCommand is not equal to the other command, otherwise returns false.
Definition at line 357 of file qscriptdebuggercommand.cpp.
 {
     return !(*this == other);
 }
operator=()
QScriptDebuggerCommand & QScriptDebuggerCommand::operator= (const QScriptDebuggerCommand & other)
Assigns the other value to this QScriptDebuggerCommand.
Definition at line 130 of file qscriptdebuggercommand.cpp.
 {
     *d_ptr = *other.d_ptr;
     return *this;
 }
operator==()
bool QScriptDebuggerCommand::operator== (const QScriptDebuggerCommand & other) const
Returns true if this QScriptDebuggerCommand is equal to the other command, otherwise returns false.
Definition at line 341 of file qscriptdebuggercommand.cpp.
 {
     Q_D(const QScriptDebuggerCommand);
     const QScriptDebuggerCommandPrivate *od = other.d_func();
     if (d == od)
         return true;
     if (!d || !od)
         return false;
     return ((d->type == od->type)
             && (d->attributes == od->attributes));
 }
program()
QString QScriptDebuggerCommand::program () const
Definition at line 229 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), and setProgram().
 {
     Q_D(const QScriptDebuggerCommand);
     return d->attributes.value(Program).toString();
 }
resolveScriptCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::resolveScriptCommand (const QString & fileName) static
Definition at line 497 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleResolveScript().
 {
     QScriptDebuggerCommand cmd(ResolveScript);
     cmd.setFileName(fileName);
     return cmd;
 }
resumeCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::resumeCommand () static
Definition at line 418 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerFrontendPrivate::event().
 {
     QScriptDebuggerCommand cmd(Resume);
     return cmd;
 }
runToLocationCommand() [1/2]
QScriptDebuggerCommand QScriptDebuggerCommand::runToLocationCommand (const QString & fileName, int lineNumber) static
Definition at line 394 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleRunToLocation().
 {
     QScriptDebuggerCommand cmd(RunToLocation);
     cmd.setFileName(fileName);
     cmd.setLineNumber(lineNumber);
     return cmd;
 }
runToLocationCommand() [2/2]
QScriptDebuggerCommand QScriptDebuggerCommand::runToLocationCommand (qint64 scriptId, int lineNumber) static
Definition at line 402 of file qscriptdebuggercommand.cpp.
 {
     QScriptDebuggerCommand cmd(RunToLocationByID);
     cmd.setScriptId(scriptId);
     cmd.setLineNumber(lineNumber);
     return cmd;
 }
scriptId()
qint64 QScriptDebuggerCommand::scriptId () const
Returns the ScriptID attribute of this command converted to a qint64.
This function is provided for convenience.
See also
attribute()
Definition at line 217 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerCommand);
     return d->attributes.value(ScriptID, -1).toLongLong();
 }
scriptObjectSnapshotCaptureCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::scriptObjectSnapshotCaptureCommand (int id, const QScriptDebuggerValue & object) static
Definition at line 589 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleScriptObjectSnapshotCapture().
 {
     Q_ASSERT(object.type() == QScriptDebuggerValue::ObjectValue);
     QScriptDebuggerCommand cmd(ScriptObjectSnapshotCapture);
     cmd.setSnapshotId(id);
     cmd.setScriptValue(object);
     return cmd;
 }
scriptsCheckpointCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::scriptsCheckpointCommand () static
Definition at line 485 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleScriptsCheckpoint().
 {
     QScriptDebuggerCommand cmd(ScriptsCheckpoint);
     return cmd;
 }
scriptValue()
QScriptDebuggerValue QScriptDebuggerCommand::scriptValue () const
Definition at line 265 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerCommand);
     return qvariant_cast<QScriptDebuggerValue>(d->attributes.value(ScriptValue));
 }
scriptValueToStringCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::scriptValueToStringCommand (const QScriptDebuggerValue & value) static
Definition at line 639 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleScriptValueToString().
 {
     QScriptDebuggerCommand cmd(ScriptValueToString);
     cmd.setScriptValue(value);
     return cmd;
 }
setAttribute()
void QScriptDebuggerCommand::setAttribute (Attribute attribute, const QVariant & value)
Sets the value of the given attribute.
Definition at line 159 of file qscriptdebuggercommand.cpp.
Referenced by getCompletions(), getPropertyExpressionValue(), stepIntoCommand(), and stepOverCommand().
 {
     Q_D(QScriptDebuggerCommand);
     if (!value.isValid())
         d->attributes.remove(attribute);
     else
         d->attributes[attribute] = value;
 }
setBreakpointCommand() [1/2]
QScriptDebuggerCommand QScriptDebuggerCommand::setBreakpointCommand (const QString & fileName, int lineNumber) static
Definition at line 424 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleSetBreakpoint().
 {
     QScriptDebuggerCommand cmd(SetBreakpoint);
     cmd.setBreakpointData(QScriptBreakpointData(fileName, lineNumber));
     return cmd;
 }
setBreakpointCommand() [2/2]
QScriptDebuggerCommand QScriptDebuggerCommand::setBreakpointCommand (const QScriptBreakpointData & data) static
Definition at line 431 of file qscriptdebuggercommand.cpp.
 {
     QScriptDebuggerCommand cmd(SetBreakpoint);
     cmd.setBreakpointData(data);
     return cmd;
 }
setBreakpointData()
void QScriptDebuggerCommand::setBreakpointData (const QScriptBreakpointData & data)
Definition at line 259 of file qscriptdebuggercommand.cpp.
Referenced by setBreakpointCommand(), and setBreakpointDataCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[BreakpointData] = QVariant::fromValue(data);
 }
setBreakpointDataCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::setBreakpointDataCommand (int id, const QScriptBreakpointData & data) static
Definition at line 464 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleSetBreakpointData().
 {
     QScriptDebuggerCommand cmd(SetBreakpointData);
     cmd.setBreakpointId(id);
     cmd.setBreakpointData(data);
     return cmd;
 }
setBreakpointId()
void QScriptDebuggerCommand::setBreakpointId (int id)
Definition at line 247 of file qscriptdebuggercommand.cpp.
Referenced by deleteBreakpointCommand(), getBreakpointDataCommand(), and setBreakpointDataCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[BreakpointID] = id;
 }
setContextIndex()
void QScriptDebuggerCommand::setContextIndex (int index)
Definition at line 283 of file qscriptdebuggercommand.cpp.
Referenced by evaluateCommand(), forceReturnCommand(), getActivationObjectCommand(), getCompletions(), getContextIdCommand(), getContextInfoCommand(), getContextStateCommand(), getPropertyExpressionValue(), getScopeChainCommand(), and getThisObjectCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[ContextIndex] = index;
 }
setFileName()
void QScriptDebuggerCommand::setFileName (const QString & fileName)
Definition at line 187 of file qscriptdebuggercommand.cpp.
Referenced by evaluateCommand(), resolveScriptCommand(), and runToLocationCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[FileName] = fileName;
 }
setIteratorId()
void QScriptDebuggerCommand::setIteratorId (int id)
Definition at line 295 of file qscriptdebuggercommand.cpp.
Referenced by deleteScriptValueIteratorCommand(), and getPropertiesByIteratorCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[IteratorID] = id;
 }
setLineNumber()
void QScriptDebuggerCommand::setLineNumber (int lineNumber)
Definition at line 205 of file qscriptdebuggercommand.cpp.
Referenced by evaluateCommand(), getPropertyExpressionValue(), and runToLocationCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[LineNumber] = lineNumber;
 }
setName()
void QScriptDebuggerCommand::setName (const QString & name)
Definition at line 307 of file qscriptdebuggercommand.cpp.
Referenced by setScriptValuePropertyCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[Name] = name;
 }
setProgram()
void QScriptDebuggerCommand::setProgram (const QString & program)
Definition at line 235 of file qscriptdebuggercommand.cpp.
Referenced by evaluateCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[Program] = program;
 }
setScriptId()
void QScriptDebuggerCommand::setScriptId (qint64 id)
Definition at line 223 of file qscriptdebuggercommand.cpp.
Referenced by getScriptDataCommand(), and runToLocationCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[ScriptID] = id;
 }
setScriptValue()
void QScriptDebuggerCommand::setScriptValue (const QScriptDebuggerValue & value)
Definition at line 271 of file qscriptdebuggercommand.cpp.
Referenced by forceReturnCommand(), newScriptValueIteratorCommand(), scriptObjectSnapshotCaptureCommand(), scriptValueToStringCommand(), and setScriptValuePropertyCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[ScriptValue] = QVariant::fromValue(value);
 }
setScriptValuePropertyCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::setScriptValuePropertyCommand (const QScriptDebuggerValue & object, const QString & name, const QScriptDebuggerValue & value) static
Definition at line 646 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleSetScriptValueProperty().
 {
     QScriptDebuggerCommand cmd(SetScriptValueProperty);
     cmd.setScriptValue(object);
     cmd.setName(name);
     cmd.setSubordinateScriptValue(value);
     return cmd;
 }
setSnapshotId()
void QScriptDebuggerCommand::setSnapshotId (int id)
Definition at line 331 of file qscriptdebuggercommand.cpp.
Referenced by deleteScriptObjectSnapshotCommand(), and scriptObjectSnapshotCaptureCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[SnapshotID] = id;
 }
setSubordinateScriptValue()
void QScriptDebuggerCommand::setSubordinateScriptValue (const QScriptDebuggerValue & value)
Definition at line 319 of file qscriptdebuggercommand.cpp.
Referenced by setScriptValuePropertyCommand().
 {
     Q_D(QScriptDebuggerCommand);
     d->attributes[SubordinateScriptValue] = QVariant::fromValue(value);
 }
snapshotId()
int QScriptDebuggerCommand::snapshotId () const
Definition at line 325 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerCommand);
     return d->attributes.value(SnapshotID, -1).toInt();
 }
stepIntoCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::stepIntoCommand (int count = 1) static
Definition at line 374 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleStepInto().
 {
     QScriptDebuggerCommand cmd(StepInto);
     cmd.setAttribute(StepCount, count);
     return cmd;
 }
stepOutCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::stepOutCommand () static
Definition at line 388 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleStepOut().
 {
     QScriptDebuggerCommand cmd(StepOut);
     return cmd;
 }
stepOverCommand()
QScriptDebuggerCommand QScriptDebuggerCommand::stepOverCommand (int count = 1) static
Definition at line 381 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandSchedulerFrontend::scheduleStepOver().
 {
     QScriptDebuggerCommand cmd(StepOver);
     cmd.setAttribute(StepCount, count);
     return cmd;
 }
subordinateScriptValue()
QScriptDebuggerValue QScriptDebuggerCommand::subordinateScriptValue () const
Definition at line 313 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerCommand);
     return qvariant_cast<QScriptDebuggerValue>(d->attributes.value(SubordinateScriptValue));
 }
type()
QScriptDebuggerCommand::Type QScriptDebuggerCommand::type () const
Returns the type of this command.
Definition at line 139 of file qscriptdebuggercommand.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), QScriptDebuggerPrivate::handleResponse(), newScriptValueIteratorCommand(), operator>>(), QScriptDebuggerCommand(), QScriptDebuggerPrivate::scheduleCommand(), and scriptObjectSnapshotCaptureCommand().
 {
     Q_D(const QScriptDebuggerCommand);
     return d->type;
 }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & out, const QScriptDebuggerCommand & command) friend
Writes the given command to the specified stream.
Definition at line 672 of file qscriptdebuggercommand.cpp.
 {
     const QScriptDebuggerCommandPrivate *d = command.d_ptr.data();
     out << (quint32)d->type;
     out << (qint32)d->attributes.size();
     QHash<QScriptDebuggerCommand::Attribute, QVariant>::const_iterator it;
     for (it = d->attributes.constBegin(); it != d->attributes.constEnd(); ++it) {
         out << (quint32)it.key();
         out << it.value();
     }
     return out;
 }
operator>>
QDataStream & operator>> (QDataStream & in, QScriptDebuggerCommand & command) friend
Reads a QScriptDebuggerCommand from the specified stream into the given command.
Definition at line 695 of file qscriptdebuggercommand.cpp.
 {
     QScriptDebuggerCommandPrivate *d = command.d_ptr.data();
     quint32 type;
     in >> type;
     d->type = QScriptDebuggerCommand::Type(type);
     qint32 attribCount;
     in >> attribCount;
     QHash<QScriptDebuggerCommand::Attribute, QVariant> attribs;
     for (qint32 i = 0; i < attribCount; ++i) {
         quint32 key;
         in >> key;
         QVariant value;
         in >> value;
         attribs[QScriptDebuggerCommand::Attribute(key)] = value;
     }
     d->attributes = attribs;
     return in;
 }
Properties
d_ptr
QScopedPointer<QScriptDebuggerCommandPrivate> QScriptDebuggerCommand::d_ptr private
Definition at line 258 of file qscriptdebuggercommand_p.h.
Referenced by operator<<(), operator=(), operator>>(), and QScriptDebuggerCommand().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggercommand_p.h
/src/scripttools/debugging/qscriptdebuggercommand.cpp