Qt 4.8: QPatternist::ArithmeticExpression Class Reference
QPatternist::ArithmeticExpression Class Reference
Implements arithmetics, such as multiplication and subtraction.
#include <qarithmeticexpression_p.h>
Public Functions
virtual ExpressionVisitorResult::Ptr accept (const ExpressionVisitor::Ptr &visitor) const
ArithmeticExpression (const Expression::Ptr &operand1, const AtomicMathematician::Operator op, const Expression::Ptr &operand2)
virtual Item evaluateSingleton (const DynamicContext::Ptr &context) const
virtual SequenceType::List expectedOperandTypes () const
AtomicMathematician::Operator operatorID () const
virtual SequenceType::Ptr staticType () const
virtual Expression::Ptr typeCheck (const StaticContext::Ptr &context, const SequenceType::Ptr &reqType)
Public Functions inherited from QPatternist::PairContainer
virtual bool compressOperands (const StaticContext::Ptr &)
virtual Expression::List operands () const
virtual void setOperands (const Expression::List &operands)
Public Functions inherited from QPatternist::Expression
virtual const SourceLocationReflection * actualReflection () const
Returns this.
virtual void announceFocusType (const ItemType::Ptr &itemType)
virtual Expression::Ptr compress (const StaticContext::Ptr &context)
Properties deepProperties () const
Computes the union of properties for this Expression and all its descending children.
virtual Properties dependencies () const
virtual QString description () const
virtual bool evaluateEBV (const DynamicContext::Ptr &context) const
virtual Item::Iterator::Ptr evaluateSequence (const DynamicContext::Ptr &context) const
virtual void evaluateToSequenceReceiver (const DynamicContext::Ptr &context) const
virtual ItemType::Ptr expectedContextItemType () const
Expression ()
bool has (const Property prop) const
bool hasDependency (const Property prop) const
virtual ID id () const
bool is (const ID id) const
bool isEvaluated () const
virtual ItemType::Ptr newFocusType () const
virtual QList< QExplicitlySharedDataPointer< OptimizationPass > > optimizationPasses () const
virtual PatternPriority patternPriority () const
virtual Properties properties () const
const Expression::Ptr & rewrite (const Expression::Ptr &to, const StaticContext::Ptr &context) const
Rewrites this Expression to to, and return to.
virtual ~Expression ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< Expression >
const TCastTarget * as () const
TCastTarget * as ()
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Static Public Functions
static AtomicMathematician::Ptr fetchMathematician (Expression::Ptr &t1, Expression::Ptr &t2, const AtomicMathematician::Operator op, const bool issueError, const ReportContext::Ptr &context, const SourceLocationReflection *const reflection, const ReportContext::ErrorCode code=ReportContext::XPTY0004, const bool isCompat=false)
static Item flexiblyCalculate (const Item &op1, const AtomicMathematician::Operator op, const Item &op2, const AtomicMathematician::Ptr &mather, const DynamicContext::Ptr &context, const SourceLocationReflection *const reflection, const ReportContext::ErrorCode code=ReportContext::XPTY0004, const bool isCompat=false)
Static Public Functions inherited from QPatternist::Expression
static void rewrite (Expression::Ptr &old, const Expression::Ptr &New, const StaticContext::Ptr &context)
Properties
bool m_isCompat
AtomicMathematician::Ptr m_mather
const AtomicMathematician::Operator m_op
Additional Inherited Members
Public Types inherited from QPatternist::Expression
typedef QExplicitlySharedDataPointer< const Expression > ConstPtr
A smart pointer wrapping const Expression instances.
enum ID {
IDBooleanValue = 1, IDCountFN, IDEmptyFN, IDExistsFN,
IDExpressionSequence, IDGeneralComparison, IDIfThenClause, IDIgnorableExpression,
IDIntegerValue, IDPositionFN, IDStringValue, IDValueComparison,
IDRangeVariableReference, IDContextItem, IDUserFunctionCallsite, IDExpressionVariableReference,
IDAttributeConstructor, IDUpperCaseFN, IDLowerCaseFN, IDFirstItemPredicate,
IDEmptySequence, IDReturnOrderBy, IDLetClause, IDForClause,
IDPath, IDNamespaceConstructor, IDArgumentReference, IDGenericPredicate,
IDAxisStep, IDFloat, IDCombineNodes, IDUnresolvedVariableReference,
IDCardinalityVerifier
}
typedef QList< Expression::Ptr > List
typedef QFlags< Property > Properties
enum Property {
UseContextItem = 1, DisableElimination = 1 << 1, IsEvaluated = 1 << 2, DisableTypingDeduction = 1 << 3,
EmptynessFollowsChild = 1 << 4, RewriteToEmptyOnEmpty = 1 << 5, RequiresFocus = 1 << 6, AffectsOrderOnly = 1 << 7,
RequiresContextItem = (1 << 8) | RequiresFocus, CreatesFocusForLast = 1 << 9, LastOperandIsCollation = 1 << 10, DependsOnLocalVariable = (1 << 11) | DisableElimination,
EvaluationCacheRedundant = (1 << 12), IsNodeConstructor = 1 << 13, RequiresCurrentItem = 1 << 14
}
typedef QExplicitlySharedDataPointer< Expression > Ptr
A smart pointer wrapping mutable Expression instances.
typedef ::QAbstractXmlForwardIterator< Expression::Ptr > QAbstractXmlForwardIterator
typedef QVector< Expression::Ptr > Vector
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::PairContainer
PairContainer (const Expression::Ptr &operand1, const Expression::Ptr &operand2)
Protected Functions inherited from QPatternist::Expression
void typeCheckOperands (const StaticContext::Ptr &context)
Protected Functions inherited from QPatternist::CppCastingHelper< Expression >
CppCastingHelper ()
Protected Variables inherited from QPatternist::PairContainer
Expression::Ptr m_operand1
Expression::Ptr m_operand2
Detailed Description
Implements arithmetics, such as multiplication and subtraction.
Optimizations: there's some operator/value combos that are no ops. For instance, 0 +
, which is the case of unary plus. We can't compile those away early due to that type checks needs to be done but one can check for them in compress().
See also
XML Path Language (XPath) 2.0, 3.4 Arithmetic Expressions
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 78 of file qarithmeticexpression_p.h.
Constructors and Destructors
ArithmeticExpression()
ArithmeticExpression::ArithmeticExpression (const Expression::Ptr & operand1, const AtomicMathematician::Operator op, const Expression::Ptr & operand2)
Definition at line 58 of file qarithmeticexpression.cpp.
                                                                      : PairContainer(op1, op2)
                                                                        , m_op(op)
                                                                        , m_isCompat(false)
 {
 }
Functions
accept()
ExpressionVisitorResult::Ptr ArithmeticExpression::accept (const ExpressionVisitor::Ptr & visitor) const virtual
Implements QPatternist::Expression.
Definition at line 358 of file qarithmeticexpression.cpp.
Referenced by fetchMathematician().
 {
     return visitor->visit(this);
 }
evaluateSingleton()
Item ArithmeticExpression::evaluateSingleton (const DynamicContext::Ptr & context) const virtual
Reimplemented from QPatternist::Expression.
Reimplemented in QPatternist::UnaryExpression.
Definition at line 66 of file qarithmeticexpression.cpp.
 {
     const Item op1(m_operand1->evaluateSingleton(context));
     if(!op1)
         return Item();
     const Item op2(m_operand2->evaluateSingleton(context));
     if(!op2)
         return Item();
     return flexiblyCalculate(op1, m_op, op2, m_mather, context, this,
                              ReportContext::XPTY0004, m_isCompat);
 }
expectedOperandTypes()
SequenceType::List ArithmeticExpression::expectedOperandTypes () const virtual
Returns a list of Sequence Types, describing the type of each of the expression's operands. Hence, this function has a relationship to the operands() function:
- The lengths of the lists returned by expectedOperandTypes()
and operands() should always be equal in length, since one
cannot describe the type of a non-existent operand(and all
operands must have type information).
- A significant difference between the two functions is that while
the type of objects in the list returned by operands() may vary
between compilations/static context, simply because the particular
Expression is part of different XPath expressions, the
types in the list returned by expectedOperandTypes is always the same
since the function/operator signature never changes.
This function should not be confused with staticType(), which returns the static type of the expression itself, not its operands. The function call is an expression where this is clear: the type of the return value is not the same as the arguments' types. The static type of the operands supplied to the expression can be determined via the staticType() function of the instances returned by operands().
If the expression has no operands, an empty list should be returned.
Implements QPatternist::Expression.
Definition at line 350 of file qarithmeticexpression.cpp.
 {
     SequenceType::List result;
     result.append(CommonSequenceTypes::ZeroOrOneAtomicType);
     result.append(CommonSequenceTypes::ZeroOrOneAtomicType);
     return result;
 }
fetchMathematician()
AtomicMathematician::Ptr ArithmeticExpression::fetchMathematician (Expression::Ptr & t1, Expression::Ptr & t2, const AtomicMathematician::Operator op, const bool issueError, const ReportContext::Ptr & context, const SourceLocationReflection *const reflection, const ReportContext::ErrorCode code = ReportContext::XPTY0004, const bool isCompat = false) static
Definition at line 169 of file qarithmeticexpression.cpp.
Referenced by flexiblyCalculate(), typeCheck(), QPatternist::AddingAggregate::typeCheck(), and QPatternist::AvgFN::typeCheck().
 {
     ItemType::Ptr t1(op1->staticType()->itemType());
     ItemType::Ptr t2(op2->staticType()->itemType());
     if(BuiltinTypes::xsUntypedAtomic->xdtTypeMatches(t1)
        || (isCompat && (BuiltinTypes::xsString->xdtTypeMatches(t1)
                         || BuiltinTypes::xsDecimal->xdtTypeMatches(t1))))
     {
         op1 = Expression::Ptr(new UntypedAtomicConverter(op1, BuiltinTypes::xsDouble));
         /* The types might have changed, reload. */
         t1 = op1->staticType()->itemType();
     }
     if(BuiltinTypes::xsUntypedAtomic->xdtTypeMatches(t2)
        || (isCompat && (BuiltinTypes::xsString->xdtTypeMatches(t1)
                         || BuiltinTypes::xsDecimal->xdtTypeMatches(t1))))
     {
         op2 = Expression::Ptr(new UntypedAtomicConverter(op2, BuiltinTypes::xsDouble));
         /* The types might have changed, reload. */
         t2 = op2->staticType()->itemType();
     }
     const AtomicMathematicianLocator::Ptr locator
         (static_cast<const AtomicType *>(t1.data())->mathematicianLocator());
     if(!locator)
     {
         if(!issueError)
             return AtomicMathematician::Ptr();
         context->error(QtXmlPatterns::tr(
                        "Operator %1 cannot be used on type %2.")
                        .arg(formatKeyword(AtomicMathematician::displayName(op)))
                        .arg(formatType(context->namePool(), t1)),
                        code, reflection);
         return AtomicMathematician::Ptr();
     }
     const AtomicMathematician::Ptr comp
         (static_cast<const AtomicType *>(t2.data())->accept(locator, op, reflection));
     if(comp)
         return comp;
     if(!issueError)
         return AtomicMathematician::Ptr();
     context->error(QtXmlPatterns::tr("Operator %1 cannot be used on "
                                      "atomic values of type %2 and %3.")
                    .arg(formatKeyword(AtomicMathematician::displayName(op)))
                    .arg(formatType(context->namePool(), t1))
                    .arg(formatType(context->namePool(), t2)),
                    code, reflection);
     return AtomicMathematician::Ptr();
 }
flexiblyCalculate()
Item ArithmeticExpression::flexiblyCalculate (const Item & op1, const AtomicMathematician::Operator op, const Item & op2, const AtomicMathematician::Ptr & mather, const DynamicContext::Ptr & context, const SourceLocationReflection *const reflection, const ReportContext::ErrorCode code = ReportContext::XPTY0004, const bool isCompat = false) static
Definition at line 112 of file qarithmeticexpression.cpp.
Referenced by evaluateSingleton(), QPatternist::AvgFN::evaluateSingleton(), and QPatternist::SumFN::evaluateSingleton().
 {
     if(mather)
         return mather->calculate(op1, op, op2, context);
     /* This is a very heavy code path. */
     Expression::Ptr a1(new DelegatingReflectionExpression(op1, reflection));
     Expression::Ptr a2(new DelegatingReflectionExpression(op2, reflection));
     const AtomicMathematician::Ptr ingela(fetchMathematician(a1, a2, op, true, context, reflection, code, isCompat));
     return ingela->calculate(a1->evaluateSingleton(context),
                              op,
                              a2->evaluateSingleton(context),
                              context);
 }
operatorID()
AtomicMathematician::Operator QPatternist::ArithmeticExpression::operatorID () const inline
Definition at line 122 of file qarithmeticexpression_p.h.
Referenced by QPatternist::UnaryExpression::evaluateSingleton().
     {
         return m_op;
     }
staticType()
SequenceType::Ptr ArithmeticExpression::staticType () const virtual
Returns
the static type of this Expression. For example, an 'and' expression have as static type xs:boolean
Implements QPatternist::Expression.
Definition at line 233 of file qarithmeticexpression.cpp.
 {
     Cardinality card;
     /* These variables are important because they ensure staticType() only
      * gets called once from this function. Before, this lead to strange
      * semi-infinite recursion involving many arithmetic expressions. */
     const SequenceType::Ptr st1(m_operand1->staticType());
     const SequenceType::Ptr st2(m_operand2->staticType());
     if(st1->cardinality().allowsEmpty() ||
        st2->cardinality().allowsEmpty())
     {
         card = Cardinality::zeroOrOne();
     }
     else
         card = Cardinality::exactlyOne();
     if(m_op == AtomicMathematician::IDiv)
         return makeGenericSequenceType(BuiltinTypes::xsInteger, card);
     const ItemType::Ptr t1(st1->itemType());
     const ItemType::Ptr t2(st2->itemType());
     ItemType::Ptr returnType;
     /* Please, make this beautiful? */
     if(BuiltinTypes::xsTime->xdtTypeMatches(t1) ||
        BuiltinTypes::xsDate->xdtTypeMatches(t1) ||
        BuiltinTypes::xsDateTime->xdtTypeMatches(t1))
     {
         if(BuiltinTypes::xsDuration->xdtTypeMatches(t2))
             returnType = t1;
         else
             returnType = BuiltinTypes::xsDayTimeDuration;
     }
     else if(BuiltinTypes::xsYearMonthDuration->xdtTypeMatches(t1))
     {
         if(m_op == AtomicMathematician::Div &&
            BuiltinTypes::xsYearMonthDuration->xdtTypeMatches(t2))
         {
             returnType = BuiltinTypes::xsDecimal;
         }
         else if(BuiltinTypes::numeric->xdtTypeMatches(t2))
             returnType = BuiltinTypes::xsYearMonthDuration;
         else
             returnType = t2;
     }
     else if(BuiltinTypes::xsYearMonthDuration->xdtTypeMatches(t2))
     {
         returnType = BuiltinTypes::xsYearMonthDuration;
     }
     else if(BuiltinTypes::xsDayTimeDuration->xdtTypeMatches(t1))
     {
         if(m_op == AtomicMathematician::Div &&
            BuiltinTypes::xsDayTimeDuration->xdtTypeMatches(t2))
         {
             returnType = BuiltinTypes::xsDecimal;
         }
         else if(BuiltinTypes::numeric->xdtTypeMatches(t2))
             returnType = BuiltinTypes::xsDayTimeDuration;
         else
             returnType = t2;
     }
     else if(BuiltinTypes::xsDayTimeDuration->xdtTypeMatches(t2))
     {
         returnType = BuiltinTypes::xsDayTimeDuration;
     }
     else if(BuiltinTypes::xsDouble->xdtTypeMatches(t1) ||
             BuiltinTypes::xsDouble->xdtTypeMatches(t2))
     {
         returnType = BuiltinTypes::xsDouble;
     }
     else if(BuiltinTypes::xsFloat->xdtTypeMatches(t1) ||
             BuiltinTypes::xsFloat->xdtTypeMatches(t2))
     {
         if(m_isCompat)
             returnType = BuiltinTypes::xsFloat;
         else
             returnType = BuiltinTypes::xsDouble;
     }
     else if(BuiltinTypes::xsInteger->xdtTypeMatches(t1) &&
             BuiltinTypes::xsInteger->xdtTypeMatches(t2))
     {
         if(m_isCompat)
             returnType = BuiltinTypes::xsDouble;
         else
         {
             /* "A div B  numeric  numeric  op:numeric-divide(A, B)
              * numeric; but xs:decimal if both operands are xs:integer" */
             if(m_op == AtomicMathematician::Div)
                 returnType = BuiltinTypes::xsDecimal;
             else
                 returnType = BuiltinTypes::xsInteger;
         }
     }
     else if(m_isCompat && (BuiltinTypes::xsInteger->xdtTypeMatches(t1) &&
                            BuiltinTypes::xsInteger->xdtTypeMatches(t2)))
     {
         returnType = BuiltinTypes::xsDouble;
     }
     else
     {
         /* If typeCheck() has been called, our operands conform to expectedOperandTypes(), and
          * the types are hence either xs:decimals, or xs:anyAtomicType(meaning the static type could
          * not be inferred), or empty-sequence(). So we use the union of the two types. The combinations
          * could also be wrong.*/
         returnType = t1 | t2;
         /* However, if we're called before typeCheck(), we could potentially have nodes, so we need to make
          * sure that the type is at least atomic. */
         if(!BuiltinTypes::xsAnyAtomicType->xdtTypeMatches(returnType))
             returnType = BuiltinTypes::xsAnyAtomicType;
     }
     return makeGenericSequenceType(returnType, card);
 }
typeCheck()
Expression::Ptr ArithmeticExpression::typeCheck (const StaticContext::Ptr & context, const SequenceType::Ptr & reqType) virtual
This implementation guarantees to never rewrite away this Expression, but at most rewrite it as a child of another expression(that presumably have a type checking role). It is therefore always safe to override this function and call this implementation and not worry about that this Expression becomes deleted.
Many Expressions override typeCheck() and performs optimizations, as opposed to doing it in the compress() stage. This is due to that the design of those Expressions often are tied to that certain simplifications are done at the typeCheck() stage of the compilation process or that it in some other way is related to what the typeCheck() do. Also, the earlier the AST can be simplified, the better the chances are for subsequent optimizations.
It is important that the super class's typeCheck() is called before doing any custom type checking, since the call can change the children(notably, the childrens' static types). For example, if the Expression, MyExpression in the example, does not match the required type, typeCheck returns the Expression wrapped in for example ItemVerifier, CardinalityVerifier, or both.
typeCheck() may be called many times. typeCheck() must either raise an error if this Expression is an invalid expression. Thus, it is guaranteed that an Expression is valid after typeCheck() is called.
Parameters
context supplies information, such as namespace bindings and available function signatures, that can be needed at compilation time. context is guaranteed by the caller to never null.
reqType the static type that this Expression must match when evaluated. reqType is guaranteed by the caller to never null.
Returns
an Expression that can be this Expression, or another expression, which somehow is necessary for making this Expression conforming to reqType
Reimplemented from QPatternist::Expression.
Definition at line 136 of file qarithmeticexpression.cpp.
 {
     m_isCompat = context->compatModeEnabled();
     const Expression::Ptr me(PairContainer::typeCheck(context, reqType));
     const ItemType::Ptr t1(m_operand1->staticType()->itemType());
     const ItemType::Ptr t2(m_operand2->staticType()->itemType());
     if(*CommonSequenceTypes::Empty == *t1 ||
        *CommonSequenceTypes::Empty == *t2)
     {
         return EmptySequence::create(this, context);
     }
     if(*BuiltinTypes::xsAnyAtomicType == *t1    ||
        *BuiltinTypes::xsAnyAtomicType == *t2    ||
        *BuiltinTypes::numeric == *t1            ||
        *BuiltinTypes::numeric == *t2)
     {
         /* The static type of (at least) one of the operands could not
          * be narrowed further than xs:anyAtomicType, so we do the operator
          * lookup at runtime. */
         return me;
     }
     m_mather = fetchMathematician(m_operand1, m_operand2, m_op, true, context, this,
                                   ReportContext::XPTY0004, m_isCompat);
     return me;
 }
Properties
m_isCompat
bool QPatternist::ArithmeticExpression::m_isCompat private
Definition at line 119 of file qarithmeticexpression_p.h.
Referenced by evaluateSingleton(), staticType(), and typeCheck().
m_mather
AtomicMathematician::Ptr QPatternist::ArithmeticExpression::m_mather private
Definition at line 118 of file qarithmeticexpression_p.h.
Referenced by evaluateSingleton(), and typeCheck().
m_op
const AtomicMathematician::Operator QPatternist::ArithmeticExpression::m_op private
Definition at line 117 of file qarithmeticexpression_p.h.
Referenced by evaluateSingleton(), staticType(), and typeCheck().
The documentation for this class was generated from the following files:
/src/xmlpatterns/expr/qarithmeticexpression_p.h
/src/xmlpatterns/expr/qarithmeticexpression.cpp