Qt 4.8: QScript::QtFunction Class Reference
QScript::QtFunction Class Reference
#include <qscriptqobject_p.h>
Classes
struct Data
Public Functions
virtual const JSC::ClassInfo * classInfo () const
JSC::JSValue execute (JSC::ExecState *exec, JSC::JSValue thisValue, const JSC::ArgList &args)
virtual JSC::CallType getCallData (JSC::CallData &)
int initialIndex () const
virtual void markChildren (JSC::MarkStack &)
bool maybeOverloaded () const
const QMetaObject * metaObject () const
int mostGeneralMethod (QMetaMethod *out=0) const
QList< int > overloadedIndexes () const
QObject * qobject () const
QtFunction (JSC::JSValue object, int initialIndex, bool maybeOverloaded, JSC::JSGlobalData *, WTF::PassRefPtr< JSC::Structure >, const JSC::Identifier &)
QScriptObject * wrapperObject () const
virtual ~QtFunction ()
Static Public Functions
static JSC::JSValue JSC_HOST_CALL call (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
Static Public Variables
static const JSC::ClassInfo info = { "QtFunction", &InternalFunction::info, 0, 0 }
Properties
Data * data
Detailed Description
Definition at line 174 of file qscriptqobject_p.h.
Constructors and Destructors
QtFunction()
QScript::QtFunction::QtFunction (JSC::JSValue object, int initialIndex, bool maybeOverloaded, JSC::JSGlobalData * data, WTF::PassRefPtr< JSC::Structure > sid, const JSC::Identifier & ident)
Definition at line 273 of file qscriptqobject.cpp.
     : JSC::InternalFunction(data, sid, ident),
       data(new Data(object, initialIndex, maybeOverloaded))
 {
 }
~QtFunction()
QScript::QtFunction::~QtFunction () virtual
Definition at line 281 of file qscriptqobject.cpp.
 {
     delete data;
 }
Functions
call()
JSC::JSValue JSC_HOST_CALL QScript::QtFunction::call (JSC::ExecState * exec, JSC::JSObject * callee, JSC::JSValue thisValue, const JSC::ArgList & args) static
Definition at line 1029 of file qscriptqobject.cpp.
Referenced by getCallData().
 {
     if (!callee->inherits(&QtFunction::info))
         return throwError(exec, JSC::TypeError, "callee is not a QtFunction object");
     QtFunction *qfun =  static_cast<QtFunction*>(callee);
     QScriptEnginePrivate *eng_p = scriptEngineFromExec(exec);
     JSC::ExecState *previousFrame = eng_p->currentFrame;
     eng_p->currentFrame = exec;
     eng_p->pushContext(exec, thisValue, args, callee);
     JSC::JSValue result = qfun->execute(eng_p->currentFrame, thisValue, args);
     eng_p->popContext();
     eng_p->currentFrame = previousFrame;
     return result;
 }
classInfo()
virtual const JSC::ClassInfo* QScript::QtFunction::classInfo () const inline virtual
Definition at line 195 of file qscriptqobject_p.h.
 { return &info; }
execute()
JSC::JSValue QScript::QtFunction::execute (JSC::ExecState * exec, JSC::JSValue thisValue, const JSC::ArgList & args)
Definition at line 995 of file qscriptqobject.cpp.
Referenced by call().
 {
     Q_ASSERT(data->object.inherits(&QScriptObject::info));
     QScriptObject *scriptObject = static_cast<QScriptObject*>(JSC::asObject(data->object));
     QScriptObjectDelegate *delegate = scriptObject->delegate();
     Q_ASSERT(delegate && (delegate->type() == QScriptObjectDelegate::QtObject));
     QObject *qobj = static_cast<QScript::QObjectDelegate*>(delegate)->value();
     if (!qobj)
         return JSC::throwError(exec, JSC::GeneralError, QString::fromLatin1("cannot call function of deleted QObject"));
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     const QMetaObject *meta = qobj->metaObject();
     QObject *thisQObject = 0;
     thisValue = engine->toUsableValue(thisValue);
     if (thisValue.inherits(&QScriptObject::info)) {
         delegate = static_cast<QScriptObject*>(JSC::asObject(thisValue))->delegate();
         if (delegate && (delegate->type() == QScriptObjectDelegate::QtObject))
             thisQObject = static_cast<QScript::QObjectDelegate*>(delegate)->value();
     }
     if (!thisQObject)
         thisQObject = qobj; // ### TypeError
     if (!meta->cast(thisQObject)) {
         // invoking a function in the prototype
         thisQObject = qobj;
     }
     return callQtMethod(exec, QMetaMethod::Method, thisQObject, scriptArgs,
                         meta, data->initialIndex, data->maybeOverloaded);
 }
getCallData()
JSC::CallType QScript::QtFunction::getCallData (JSC::CallData & callData) virtual
Definition at line 286 of file qscriptqobject.cpp.
 {
     callData.native.function = call;
     return JSC::CallTypeHost;
 }
initialIndex()
int QScript::QtFunction::initialIndex () const
Definition at line 321 of file qscriptqobject.cpp.
Referenced by QScript::functionConnect(), QScript::functionDisconnect(), mostGeneralMethod(), and overloadedIndexes().
 {
     return data->initialIndex;
 }
markChildren()
void QScript::QtFunction::markChildren (JSC::MarkStack & markStack) virtual
Definition at line 292 of file qscriptqobject.cpp.
 {
     if (data->object)
         markStack.append(data->object);
     JSC::InternalFunction::markChildren(markStack);
 }
maybeOverloaded()
bool QScript::QtFunction::maybeOverloaded () const
Definition at line 326 of file qscriptqobject.cpp.
Referenced by mostGeneralMethod(), and overloadedIndexes().
 {
     return data->maybeOverloaded;
 }
metaObject()
const QMetaObject * QScript::QtFunction::metaObject () const
Definition at line 313 of file qscriptqobject.cpp.
Referenced by QScript::functionConnect(), QScript::functionDisconnect(), mostGeneralMethod(), and overloadedIndexes().
 {
     QObject *qobj = qobject();
     if (!qobj)
         return 0;
     return qobj->metaObject();
 }
mostGeneralMethod()
int QScript::QtFunction::mostGeneralMethod (QMetaMethod * out = 0) const
Definition at line 331 of file qscriptqobject.cpp.
Referenced by overloadedIndexes(), QScriptEnginePrivate::scriptConnect(), and QScriptEnginePrivate::scriptDisconnect().
 {
     const QMetaObject *meta = metaObject();
     if (!meta)
         return -1;
     int index = initialIndex();
     QMetaMethod method = meta->method(index);
     if (maybeOverloaded() && (method.attributes() & QMetaMethod::Cloned)) {
         // find the most general method
         do {
             method = meta->method(--index);
         } while (method.attributes() & QMetaMethod::Cloned);
     }
     if (out)
         *out = method;
     return index;
 }
overloadedIndexes()
QList< int > QScript::QtFunction::overloadedIndexes () const
Definition at line 349 of file qscriptqobject.cpp.
Referenced by QScript::functionConnect().
 {
     if (!maybeOverloaded())
         return QList<int>();
     QList<int> result;
     const QMetaObject *meta = metaObject();
     QMetaMethod method = meta->method(initialIndex());
     int nameLength = methodNameLength(method);
     for (int index = mostGeneralMethod() - 1; index >= 0; --index) {
         if (methodNameEquals(meta->method(index), method.signature(), nameLength))
             result.append(index);
     }
     return result;
 }
qobject()
QObject * QScript::QtFunction::qobject () const
Definition at line 305 of file qscriptqobject.cpp.
Referenced by metaObject(), QScriptEnginePrivate::scriptConnect(), and QScriptEnginePrivate::scriptDisconnect().
 {
     QScriptObject *scriptObject = wrapperObject();
     QScriptObjectDelegate *delegate = scriptObject->delegate();
     Q_ASSERT(delegate && (delegate->type() == QScriptObjectDelegate::QtObject));
     return static_cast<QScript::QObjectDelegate*>(delegate)->value();
 }
wrapperObject()
QScriptObject * QScript::QtFunction::wrapperObject () const
Definition at line 299 of file qscriptqobject.cpp.
Referenced by qobject(), and QScriptEnginePrivate::scriptConnect().
 {
     Q_ASSERT(JSC::asObject(data->object)->inherits(&QScriptObject::info));
     return static_cast<QScriptObject*>(JSC::asObject(data->object));
 }
Properties
data
Data* QScript::QtFunction::data private
Definition at line 213 of file qscriptqobject_p.h.
Referenced by execute(), initialIndex(), markChildren(), maybeOverloaded(), wrapperObject(), and ~QtFunction().
info
const JSC::ClassInfo QScript::QtFunction::info = { "QtFunction", &InternalFunction::info, 0, 0 } static
Definition at line 196 of file qscriptqobject_p.h.
Referenced by execute(), QScript::functionConnect(), QScript::functionDisconnect(), and QScriptContextInfoPrivate::QScriptContextInfoPrivate().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptqobject_p.h
/src/script/bridge/qscriptqobject.cpp