Qt 4.8: QDeclarativeStateGroupPrivate Class Reference
QDeclarativeStateGroupPrivate Class Reference
Public Functions
QDeclarativeTransition * findTransition (const QString &from, const QString &to)
QDeclarativeStateGroupPrivate ()
void setCurrentStateInternal (const QString &state, bool=false)
bool updateAutoState ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static void append_state (QDeclarativeListProperty< QDeclarativeState > *list, QDeclarativeState *state)
static void append_transition (QDeclarativeListProperty< QDeclarativeTransition > *list, QDeclarativeTransition *state)
static QDeclarativeState * at_state (QDeclarativeListProperty< QDeclarativeState > *list, int index)
static QDeclarativeTransition * at_transition (QDeclarativeListProperty< QDeclarativeTransition > *list, int index)
static void clear_states (QDeclarativeListProperty< QDeclarativeState > *list)
static void clear_transitions (QDeclarativeListProperty< QDeclarativeTransition > *list)
static int count_state (QDeclarativeListProperty< QDeclarativeState > *list)
static int count_transitions (QDeclarativeListProperty< QDeclarativeTransition > *list)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
bool applyingState
bool componentComplete
QString currentState
bool ignoreTrans
QDeclarativeState * nullState
QList< QDeclarativeState * > states
QList< QDeclarativeTransition * > transitions
int unnamedCount
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 60 of file qdeclarativestategroup.cpp.
Constructors and Destructors
QDeclarativeStateGroupPrivate()
QDeclarativeStateGroupPrivate::QDeclarativeStateGroupPrivate () inline
Definition at line 64 of file qdeclarativestategroup.cpp.
     : nullState(0), componentComplete(true),
       ignoreTrans(false), applyingState(false), unnamedCount(0) {}
Functions
append_state()
void QDeclarativeStateGroupPrivate::append_state (QDeclarativeListProperty< QDeclarativeState > * list, QDeclarativeState * state) static
Definition at line 177 of file qdeclarativestategroup.cpp.
Referenced by QDeclarativeStateGroup::statesProperty().
 {
     QDeclarativeStateGroup *_this = static_cast<QDeclarativeStateGroup *>(list->object);
     if (state) {
         _this->d_func()->states.append(state);
         state->setStateGroup(_this);
     }
 }
append_transition()
void QDeclarativeStateGroupPrivate::append_transition (QDeclarativeListProperty< QDeclarativeTransition > * list, QDeclarativeTransition * state) static
Definition at line 241 of file qdeclarativestategroup.cpp.
Referenced by QDeclarativeStateGroup::transitionsProperty().
 {
     QDeclarativeStateGroup *_this = static_cast<QDeclarativeStateGroup *>(list->object);
     if (trans)
         _this->d_func()->transitions.append(trans);
 }
at_state()
QDeclarativeState * QDeclarativeStateGroupPrivate::at_state (QDeclarativeListProperty< QDeclarativeState > * list, int index) static
Definition at line 193 of file qdeclarativestategroup.cpp.
Referenced by QDeclarativeStateGroup::statesProperty().
 {
     QDeclarativeStateGroup *_this = static_cast<QDeclarativeStateGroup *>(list->object);
     return _this->d_func()->states.at(index);
 }
at_transition()
QDeclarativeTransition * QDeclarativeStateGroupPrivate::at_transition (QDeclarativeListProperty< QDeclarativeTransition > * list, int index) static
Definition at line 254 of file qdeclarativestategroup.cpp.
Referenced by QDeclarativeStateGroup::transitionsProperty().
 {
     QDeclarativeStateGroup *_this = static_cast<QDeclarativeStateGroup *>(list->object);
     return _this->d_func()->transitions.at(index);
 }
clear_states()
void QDeclarativeStateGroupPrivate::clear_states (QDeclarativeListProperty< QDeclarativeState > * list) static
Definition at line 199 of file qdeclarativestategroup.cpp.
Referenced by QDeclarativeStateGroup::statesProperty().
 {
     QDeclarativeStateGroup *_this = static_cast<QDeclarativeStateGroup *>(list->object);
     _this->d_func()->setCurrentStateInternal(QString(), true);
     for (int i = 0; i < _this->d_func()->states.count(); ++i) {
         _this->d_func()->states.at(i)->setStateGroup(0);
     }
     _this->d_func()->states.clear();
 }
clear_transitions()
void QDeclarativeStateGroupPrivate::clear_transitions (QDeclarativeListProperty< QDeclarativeTransition > * list) static
Definition at line 260 of file qdeclarativestategroup.cpp.
Referenced by QDeclarativeStateGroup::transitionsProperty().
 {
     QDeclarativeStateGroup *_this = static_cast<QDeclarativeStateGroup *>(list->object);
     _this->d_func()->transitions.clear();
 }
count_state()
int QDeclarativeStateGroupPrivate::count_state (QDeclarativeListProperty< QDeclarativeState > * list) static
Definition at line 187 of file qdeclarativestategroup.cpp.
Referenced by QDeclarativeStateGroup::statesProperty().
 {
     QDeclarativeStateGroup *_this = static_cast<QDeclarativeStateGroup *>(list->object);
     return _this->d_func()->states.count();
 }
count_transitions()
int QDeclarativeStateGroupPrivate::count_transitions (QDeclarativeListProperty< QDeclarativeTransition > * list) static
Definition at line 248 of file qdeclarativestategroup.cpp.
Referenced by QDeclarativeStateGroup::transitionsProperty().
 {
     QDeclarativeStateGroup *_this = static_cast<QDeclarativeStateGroup *>(list->object);
     return _this->d_func()->transitions.count();
 }
findTransition()
QDeclarativeTransition * QDeclarativeStateGroupPrivate::findTransition (const QString & from, const QString & to)
Definition at line 378 of file qdeclarativestategroup.cpp.
 {
     QDeclarativeTransition *highest = 0;
     int score = 0;
     bool reversed = false;
     bool done = false;
     for (int ii = 0; !done && ii < transitions.count(); ++ii) {
         QDeclarativeTransition *t = transitions.at(ii);
         for (int ii = 0; ii < 2; ++ii)
         {
             if (ii && (!t->reversible() ||
                       (t->fromState() == QLatin1String("*") &&
                        t->toState() == QLatin1String("*"))))
                 break;
             QStringList fromState;
             QStringList toState;
             fromState = t->fromState().split(QLatin1Char(','));
             toState = t->toState().split(QLatin1Char(','));
             if (ii == 1)
                 qSwap(fromState, toState);
             int tScore = 0;
             if (fromState.contains(from))
                 tScore += 2;
             else if (fromState.contains(QLatin1String("*")))
                 tScore += 1;
             else
                 continue;
             if (toState.contains(to))
                 tScore += 2;
             else if (toState.contains(QLatin1String("*")))
                 tScore += 1;
             else
                 continue;
             if (ii == 1)
                 reversed = true;
             else
                 reversed = false;
             if (tScore == 4) {
                 highest = t;
                 done = true;
                 break;
             } else if (tScore > score) {
                 score = tScore;
                 highest = t;
             }
         }
     }
     if (highest)
         highest->setReversed(reversed);
     return highest;
 }
setCurrentStateInternal()
void QDeclarativeStateGroupPrivate::setCurrentStateInternal (const QString & state, bool ignoreTrans = false)
Definition at line 437 of file qdeclarativestategroup.cpp.
 {
     Q_Q(QDeclarativeStateGroup);
     if (!componentComplete) {
         currentState = state;
         return;
     }
     if (applyingState) {
         qmlInfo(q) << "Can't apply a state change as part of a state definition.";
         return;
     }
     applyingState = true;
     QDeclarativeTransition *transition = (ignoreTrans || ignoreTrans) ? 0 : findTransition(currentState, state);
     if (stateChangeDebug()) {
         qWarning() << this << "Changing state.  From" << currentState << ". To" << state;
         if (transition)
             qWarning() << "   using transition" << transition->fromState()
                        << transition->toState();
     }
     QDeclarativeState *oldState = 0;
     if (!currentState.isEmpty()) {
         for (int ii = 0; ii < states.count(); ++ii) {
             if (states.at(ii)->name() == currentState) {
                 oldState = states.at(ii);
                 break;
             }
         }
     }
     currentState = state;
     emit q->stateChanged(currentState);
     QDeclarativeState *newState = 0;
     for (int ii = 0; ii < states.count(); ++ii) {
         if (states.at(ii)->name() == currentState) {
             newState = states.at(ii);
             break;
         }
     }
     if (oldState == 0 || newState == 0) {
         if (!nullState) { nullState = new QDeclarativeState; QDeclarative_setParent_noEvent(nullState, q); }
         if (!oldState) oldState = nullState;
         if (!newState) newState = nullState;
     }
     newState->apply(q, transition, oldState);
     applyingState = false;
     if (!transition)
         static_cast<QDeclarativeStatePrivate*>(QObjectPrivate::get(newState))->complete();
 }
updateAutoState()
bool QDeclarativeStateGroupPrivate::updateAutoState ()
Definition at line 342 of file qdeclarativestategroup.cpp.
 {
     Q_Q(QDeclarativeStateGroup);
     if (!componentComplete)
         return false;
     bool revert = false;
     for (int ii = 0; ii < states.count(); ++ii) {
         QDeclarativeState *state = states.at(ii);
         if (state->isWhenKnown()) {
             if (state->isNamed()) {
                 if (state->when() && state->when()->evaluate().toBool()) {
                     if (stateChangeDebug())
                         qWarning() << "Setting auto state due to:"
                                    << state->when()->expression();
                     if (currentState != state->name()) {
                         q->setState(state->name());
                         return true;
                     } else {
                         return false;
                     }
                 } else if (state->name() == currentState) {
                     revert = true;
                 }
             }
         }
     }
     if (revert) {
         bool rv = !currentState.isEmpty();
         q->setState(QString());
         return rv;
     } else {
         return false;
     }
 }
Properties
applyingState
bool QDeclarativeStateGroupPrivate::applyingState
Definition at line 86 of file qdeclarativestategroup.cpp.
componentComplete
bool QDeclarativeStateGroupPrivate::componentComplete
Definition at line 84 of file qdeclarativestategroup.cpp.
currentState
QString QDeclarativeStateGroupPrivate::currentState
Definition at line 68 of file qdeclarativestategroup.cpp.
ignoreTrans
bool QDeclarativeStateGroupPrivate::ignoreTrans
Definition at line 85 of file qdeclarativestategroup.cpp.
nullState
QDeclarativeState* QDeclarativeStateGroupPrivate::nullState
Definition at line 69 of file qdeclarativestategroup.cpp.
states
QList<QDeclarativeState *> QDeclarativeStateGroupPrivate::states
Definition at line 81 of file qdeclarativestategroup.cpp.
transitions
QList<QDeclarativeTransition *> QDeclarativeStateGroupPrivate::transitions
Definition at line 82 of file qdeclarativestategroup.cpp.
unnamedCount
int QDeclarativeStateGroupPrivate::unnamedCount
Definition at line 87 of file qdeclarativestategroup.cpp.
The documentation for this class was generated from the following file:
/src/declarative/util/qdeclarativestategroup.cpp