Qt 4.8: QScript::ClassObjectDelegate Class Reference
QScript::ClassObjectDelegate Class Reference
#include <qscriptclassobject_p.h>
Public Functions
ClassObjectDelegate (QScriptClass *scriptClass)
virtual bool deleteProperty (QScriptObject *, JSC::ExecState *, const JSC::Identifier &propertyName)
virtual JSC::CallType getCallData (QScriptObject *, JSC::CallData &)
virtual JSC::ConstructType getConstructData (QScriptObject *, JSC::ConstructData &)
virtual bool getOwnPropertyDescriptor (QScriptObject *, JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertyDescriptor &)
virtual void getOwnPropertyNames (QScriptObject *, JSC::ExecState *, JSC::PropertyNameArray &, JSC::EnumerationMode mode=JSC::ExcludeDontEnumProperties)
virtual bool getOwnPropertySlot (QScriptObject *, JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertySlot &)
virtual bool hasInstance (QScriptObject *, JSC::ExecState *, JSC::JSValue value, JSC::JSValue proto)
virtual void put (QScriptObject *, JSC::ExecState *exec, const JSC::Identifier &propertyName, JSC::JSValue, JSC::PutPropertySlot &)
QScriptClass * scriptClass () const
void setScriptClass (QScriptClass *scriptClass)
virtual Type type () const
~ClassObjectDelegate ()
Public Functions inherited from QScriptObjectDelegate
virtual bool compareToObject (QScriptObject *, JSC::ExecState *, JSC::JSObject *)
virtual void markChildren (QScriptObject *, JSC::MarkStack &markStack)
QScriptObjectDelegate ()
virtual ~QScriptObjectDelegate ()
Static Public Functions
static JSC::JSValue JSC_HOST_CALL call (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSObject * construct (JSC::ExecState *, JSC::JSObject *, const JSC::ArgList &)
Properties
QScriptClass * m_scriptClass
Additional Inherited Members
Public Types inherited from QScriptObjectDelegate
enum Type { QtObject, Variant, ClassObject, DeclarativeClassObject }
Detailed Description
Definition at line 49 of file qscriptclassobject_p.h.
Constructors and Destructors
ClassObjectDelegate()
QScript::ClassObjectDelegate::ClassObjectDelegate (QScriptClass * scriptClass)
Definition at line 46 of file qscriptclassobject.cpp.
     : m_scriptClass(scriptClass)
 {
 }
~ClassObjectDelegate()
QScript::ClassObjectDelegate::~ClassObjectDelegate ()
Definition at line 51 of file qscriptclassobject.cpp.
 {
 }
Functions
call()
JSC::JSValue JSC_HOST_CALL QScript::ClassObjectDelegate::call (JSC::ExecState * exec, JSC::JSObject * callee, JSC::JSValue thisValue, const JSC::ArgList & args) static
Definition at line 212 of file qscriptclassobject.cpp.
Referenced by getCallData().
 {
     if (!callee->inherits(&QScriptObject::info))
         return JSC::throwError(exec, JSC::TypeError, "callee is not a ClassObject object");
     QScriptObject *obj = static_cast<QScriptObject*>(callee);
     QScriptObjectDelegate *delegate = obj->delegate();
     if (!delegate || (delegate->type() != QScriptObjectDelegate::ClassObject))
         return JSC::throwError(exec, JSC::TypeError, "callee is not a ClassObject object");
     QScriptClass *scriptClass = static_cast<ClassObjectDelegate*>(delegate)->scriptClass();
     QScriptEnginePrivate *eng_p = scriptEngineFromExec(exec);
     JSC::ExecState *oldFrame = eng_p->currentFrame;
     eng_p->pushContext(exec, thisValue, args, callee);
     QScriptContext *ctx = eng_p->contextForFrame(eng_p->currentFrame);
     QScriptValue scriptObject = eng_p->scriptValueFromJSCValue(obj);
     QVariant result = scriptClass->extension(QScriptClass::Callable, QVariant::fromValue(ctx));
     eng_p->popContext();
     eng_p->currentFrame = oldFrame;
     return QScriptEnginePrivate::jscValueFromVariant(exec, result);
 }
construct()
JSC::JSObject * QScript::ClassObjectDelegate::construct (JSC::ExecState * exec, JSC::JSObject * callee, const JSC::ArgList & args) static
Definition at line 243 of file qscriptclassobject.cpp.
Referenced by getConstructData().
 {
     Q_ASSERT(callee->inherits(&QScriptObject::info));
     QScriptObject *obj = static_cast<QScriptObject*>(callee);
     QScriptObjectDelegate *delegate = obj->delegate();
     QScriptClass *scriptClass = static_cast<ClassObjectDelegate*>(delegate)->scriptClass();
     QScriptEnginePrivate *eng_p = scriptEngineFromExec(exec);
     JSC::ExecState *oldFrame = eng_p->currentFrame;
     eng_p->pushContext(exec, JSC::JSValue(), args, callee, true);
     QScriptContext *ctx = eng_p->contextForFrame(eng_p->currentFrame);
     QScriptValue defaultObject = ctx->thisObject();
     QScriptValue result = qvariant_cast<QScriptValue>(scriptClass->extension(QScriptClass::Callable, QVariant::fromValue(ctx)));
     if (!result.isObject())
         result = defaultObject;
     eng_p->popContext();
     eng_p->currentFrame = oldFrame;
     return JSC::asObject(eng_p->scriptValueToJSCValue(result));
 }
deleteProperty()
bool QScript::ClassObjectDelegate::deleteProperty (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 160 of file qscriptclassobject.cpp.
 {
     // ### avoid duplication of put()
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     QScript::SaveFrameHelper saveFrame(engine, exec);
     QScriptValue scriptObject = engine->scriptValueFromJSCValue(object);
     QScriptString scriptName;
     QScriptStringPrivate scriptName_d(engine, propertyName, QScriptStringPrivate::StackAllocated);
     QScriptStringPrivate::init(scriptName, &scriptName_d);
     uint id = 0;
     QScriptClass::QueryFlags flags = m_scriptClass->queryProperty(
         scriptObject, scriptName, QScriptClass::HandlesWriteAccess, &id);
     if (flags & QScriptClass::HandlesWriteAccess) {
         if (m_scriptClass->propertyFlags(scriptObject, scriptName, id) & QScriptValue::Undeletable)
             return false;
         m_scriptClass->setProperty(scriptObject, scriptName, id, QScriptValue());
         return true;
     }
     return QScriptObjectDelegate::deleteProperty(object, exec, propertyName);
 }
getCallData()
JSC::CallType QScript::ClassObjectDelegate::getCallData (QScriptObject * , JSC::CallData & callData) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 204 of file qscriptclassobject.cpp.
 {
     if (!m_scriptClass->supportsExtension(QScriptClass::Callable))
         return JSC::CallTypeNone;
     callData.native.function = call;
     return JSC::CallTypeHost;
 }
getConstructData()
JSC::ConstructType QScript::ClassObjectDelegate::getConstructData (QScriptObject * , JSC::ConstructData & constructData) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 235 of file qscriptclassobject.cpp.
 {
     if (!m_scriptClass->supportsExtension(QScriptClass::Callable))
         return JSC::ConstructTypeNone;
     constructData.native.function = construct;
     return JSC::ConstructTypeHost;
 }
getOwnPropertyDescriptor()
bool QScript::ClassObjectDelegate::getOwnPropertyDescriptor (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertyDescriptor & descriptor) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 93 of file qscriptclassobject.cpp.
 {
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     QScript::SaveFrameHelper saveFrame(engine, exec);
     // for compatibility with the old back-end, normal JS properties
     // are queried first.
     if (QScriptObjectDelegate::getOwnPropertyDescriptor(object, exec, propertyName, descriptor))
         return true;
     QScriptValue scriptObject = engine->scriptValueFromJSCValue(object);
     QScriptString scriptName;
     QScriptStringPrivate scriptName_d(engine, propertyName, QScriptStringPrivate::StackAllocated);
     QScriptStringPrivate::init(scriptName, &scriptName_d);
     uint id = 0;
     QScriptClass::QueryFlags qflags = m_scriptClass->queryProperty(
         scriptObject, scriptName, QScriptClass::HandlesReadAccess, &id);
     if (qflags & QScriptClass::HandlesReadAccess) {
         QScriptValue::PropertyFlags pflags = m_scriptClass->propertyFlags(scriptObject, scriptName, id);
         unsigned attribs = 0;
         if (pflags & QScriptValue::ReadOnly)
             attribs |= JSC::ReadOnly;
         if (pflags & QScriptValue::SkipInEnumeration)
             attribs |= JSC::DontEnum;
         if (pflags & QScriptValue::Undeletable)
             attribs |= JSC::DontDelete;
         if (pflags & QScriptValue::PropertyGetter)
             attribs |= JSC::Getter;
         if (pflags & QScriptValue::PropertySetter)
             attribs |= JSC::Setter;
         attribs |= pflags & QScriptValue::UserRange;
         // Rather than calling the getter, we could return an access descriptor here.
         QScriptValue value = m_scriptClass->property(scriptObject, scriptName, id);
         if (!value.isValid()) {
             // The class claims to have the property, but returned an invalid
             // value. Silently convert to undefined to avoid the invalid value
             // "escaping" into JS.
             value = QScriptValue(QScriptValue::UndefinedValue);
         }
         descriptor.setDescriptor(engine->scriptValueToJSCValue(value), attribs);
         return true;
     }
     return false;
 }
getOwnPropertyNames()
void QScript::ClassObjectDelegate::getOwnPropertyNames (QScriptObject * object, JSC::ExecState * exec, JSC::PropertyNameArray & propertyNames, JSC::EnumerationMode mode = JSC::ExcludeDontEnumProperties) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 182 of file qscriptclassobject.cpp.
 {
     // For compatibility with the old back-end, normal JS properties
     // are added first.
     QScriptObjectDelegate::getOwnPropertyNames(object, exec, propertyNames, mode);
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     QScript::SaveFrameHelper saveFrame(engine, exec);
     QScriptValue scriptObject = engine->scriptValueFromJSCValue(object);
     QScriptClassPropertyIterator *it = m_scriptClass->newIterator(scriptObject);
     if (it != 0) {
         while (it->hasNext()) {
             it->next();
             QString name = it->name().toString();
             propertyNames.add(JSC::Identifier(exec, name));
         }
         delete it;
     }
 }
getOwnPropertySlot()
bool QScript::ClassObjectDelegate::getOwnPropertySlot (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertySlot & slot) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 60 of file qscriptclassobject.cpp.
 {
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     QScript::SaveFrameHelper saveFrame(engine, exec);
     // for compatibility with the old back-end, normal JS properties
     // are queried first.
     if (QScriptObjectDelegate::getOwnPropertySlot(object, exec, propertyName, slot))
         return true;
     QScriptValue scriptObject = engine->scriptValueFromJSCValue(object);
     QScriptString scriptName;
     QScriptStringPrivate scriptName_d(engine, propertyName, QScriptStringPrivate::StackAllocated);
     QScriptStringPrivate::init(scriptName, &scriptName_d);
     uint id = 0;
     QScriptClass::QueryFlags flags = m_scriptClass->queryProperty(
         scriptObject, scriptName, QScriptClass::HandlesReadAccess, &id);
     if (flags & QScriptClass::HandlesReadAccess) {
         QScriptValue value = m_scriptClass->property(scriptObject, scriptName, id);
         if (!value.isValid()) {
             // The class claims to have the property, but returned an invalid
             // value. Silently convert to undefined to avoid the invalid value
             // "escaping" into JS.
             value = QScriptValue(QScriptValue::UndefinedValue);
         }
         slot.setValue(engine->scriptValueToJSCValue(value));
         return true;
     }
     return false;
 }
hasInstance()
bool QScript::ClassObjectDelegate::hasInstance (QScriptObject * object, JSC::ExecState * exec, JSC::JSValue value, JSC::JSValue proto) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 265 of file qscriptclassobject.cpp.
 {
     if (!scriptClass()->supportsExtension(QScriptClass::HasInstance))
         return QScriptObjectDelegate::hasInstance(object, exec, value, proto);
     QScriptValueList args;
     QScriptEnginePrivate *eng_p = scriptEngineFromExec(exec);
     QScript::SaveFrameHelper saveFrame(eng_p, exec);
     args << eng_p->scriptValueFromJSCValue(object) << eng_p->scriptValueFromJSCValue(value);
     QVariant result = scriptClass()->extension(QScriptClass::HasInstance, QVariant::fromValue(args));
     return result.toBool();
 }
put()
void QScript::ClassObjectDelegate::put (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSValue value, JSC::PutPropertySlot & slot) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 140 of file qscriptclassobject.cpp.
 {
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     QScript::SaveFrameHelper saveFrame(engine, exec);
     QScriptValue scriptObject = engine->scriptValueFromJSCValue(object);
     QScriptString scriptName;
     QScriptStringPrivate scriptName_d(engine, propertyName, QScriptStringPrivate::StackAllocated);
     QScriptStringPrivate::init(scriptName, &scriptName_d);
     uint id = 0;
     QScriptClass::QueryFlags flags = m_scriptClass->queryProperty(
         scriptObject, scriptName, QScriptClass::HandlesWriteAccess, &id);
     if (flags & QScriptClass::HandlesWriteAccess) {
         m_scriptClass->setProperty(scriptObject, scriptName, id, engine->scriptValueFromJSCValue(value));
         return;
     }
     QScriptObjectDelegate::put(object, exec, propertyName, value, slot);
 }
scriptClass()
QScriptClass * QScript::ClassObjectDelegate::scriptClass () const inline
Definition at line 89 of file qscriptclassobject_p.h.
Referenced by call(), construct(), hasInstance(), and setScriptClass().
 {
     return m_scriptClass;
 }
setScriptClass()
void QScript::ClassObjectDelegate::setScriptClass (QScriptClass * scriptClass) inline
Definition at line 94 of file qscriptclassobject_p.h.
 {
     Q_ASSERT(scriptClass != 0);
     m_scriptClass = scriptClass;
 }
type()
QScriptObjectDelegate::Type QScript::ClassObjectDelegate::type () const virtual
Implements QScriptObjectDelegate.
Definition at line 55 of file qscriptclassobject.cpp.
 {
     return ClassObject;
 }
Properties
m_scriptClass
QScriptClass* QScript::ClassObjectDelegate::m_scriptClass private
Definition at line 86 of file qscriptclassobject_p.h.
Referenced by deleteProperty(), getCallData(), getConstructData(), getOwnPropertyDescriptor(), getOwnPropertyNames(), getOwnPropertySlot(), put(), scriptClass(), and setScriptClass().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptclassobject_p.h
/src/script/bridge/qscriptclassobject.cpp