Qt 4.8: QPatternist::NamespaceResolver Class Reference
QPatternist::NamespaceResolver Class Reference abstract
Base class for namespace resolvers.
#include <qnamespaceresolver_p.h>
Public Types
typedef QHash< QXmlName::PrefixCode, QXmlName::NamespaceCode > Bindings
enum Constants { NoBinding = -1 }
typedef QExplicitlySharedDataPointer< NamespaceResolver > Ptr
Public Functions
virtual void addBinding (const QXmlName nb)=0
virtual Bindings bindings () const =0
virtual QXmlName::NamespaceCode lookupNamespaceURI (const QXmlName::PrefixCode prefix) const =0
NamespaceResolver ()
virtual ~NamespaceResolver ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Base class for namespace resolvers.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 74 of file qnamespaceresolver_p.h.
Typedefs
Bindings
typedef QHash<QXmlName::PrefixCode, QXmlName::NamespaceCode> QPatternist::NamespaceResolver::Bindings
A list of namespace bindings. The key is the prefix, and the value is the namespace URI.
Definition at line 88 of file qnamespaceresolver_p.h.
Ptr
typedef QExplicitlySharedDataPointer<NamespaceResolver> QPatternist::NamespaceResolver::Ptr
Definition at line 82 of file qnamespaceresolver_p.h.
Enumerations
Constants
enum QPatternist::NamespaceResolver::Constants
Enumerator
NoBinding
Definition at line 77 of file qnamespaceresolver_p.h.
         {
             NoBinding = -1
         };
Constructors and Destructors
NamespaceResolver()
NamespaceResolver::NamespaceResolver ()
Definition at line 49 of file qnamespaceresolver.cpp.
 {
 }
~NamespaceResolver()
NamespaceResolver::~NamespaceResolver () virtual
Definition at line 53 of file qnamespaceresolver.cpp.
 {
 }
Functions
addBinding()
virtual void QPatternist::NamespaceResolver::addBinding (const QXmlName nb) pure virtual
Adds the mapping from prefix to namespaceURI to this NamespaceResolver. If this NamespaceResolver already contains a binding involving prefix, the old binding is replaced.
Implemented in QPatternist::DelegatingNamespaceResolver, QPatternist::NodeNamespaceResolver, and QPatternist::GenericNamespaceResolver.
bindings()
virtual Bindings QPatternist::NamespaceResolver::bindings () const pure virtual
Returns
all bindings this NamespaceResolver handles.
Implemented in QPatternist::GenericNamespaceResolver, QPatternist::DelegatingNamespaceResolver, and QPatternist::NodeNamespaceResolver.
Referenced by QPatternist::DelegatingNamespaceResolver::bindings(), and QPatternist::GenericStaticContext::copy().
lookupNamespaceURI()
virtual QXmlName::NamespaceCode QPatternist::NamespaceResolver::lookupNamespaceURI (const QXmlName::PrefixCode prefix) const pure virtual
Resolves the prefix to the corresponding namespace URI. If no binding exists for prefix, NoBinding is returned.
Returns
the namespace corresponding to prefix.
Implemented in QPatternist::DelegatingNamespaceResolver, QPatternist::NodeNamespaceResolver, and QPatternist::GenericNamespaceResolver.
Referenced by QPatternist::DelegatingNamespaceResolver::lookupNamespaceURI(), and QPatternist::QNameConstructor::namespaceForPrefix().
The documentation for this class was generated from the following files:
/src/xmlpatterns/utils/qnamespaceresolver_p.h
/src/xmlpatterns/utils/qnamespaceresolver.cpp