Qt 4.8: QLayoutParameter< T > Class Template Reference
QLayoutParameter< T > Class Template Reference
#include <qgridlayoutengine_p.h>
Public Types
enum State { Default, User, Cached }
Public Functions
bool isCached () const
bool isDefault () const
bool isUser () const
QLayoutParameter ()
QLayoutParameter (T value, State state=Default)
void setCachedValue (T value) const
void setUserValue (T value)
T value () const
T value (T defaultValue) const
Properties
State q_state
T q_value
Detailed Description
template<typename T>
class QLayoutParameter< T >
Definition at line 103 of file qgridlayoutengine_p.h.
Enumerations
State
template<typename T> enum QLayoutParameter::State
Enumerator
Default
User
Cached
Definition at line 106 of file qgridlayoutengine_p.h.
 { Default, User, Cached };
Constructors and Destructors
QLayoutParameter() [1/2]
template<typename T> QLayoutParameter< T >::QLayoutParameter () inline
Definition at line 108 of file qgridlayoutengine_p.h.
 : q_value(T()), q_state(Default) {}
QLayoutParameter() [2/2]
template<typename T> QLayoutParameter< T >::QLayoutParameter (T value, State state = Default) inline
Definition at line 109 of file qgridlayoutengine_p.h.
 : q_value(value), q_state(state) {}
Functions
isCached()
template<typename T> bool QLayoutParameter< T >::isCached () const inline
Definition at line 125 of file qgridlayoutengine_p.h.
 { return q_state == Cached; }
isDefault()
template<typename T> bool QLayoutParameter< T >::isDefault () const inline
Definition at line 123 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::fillRowData(), QGridLayoutEngine::rowSpacing(), and QGridLayoutEngine::rowStretchFactor().
 { return q_state == Default; }
isUser()
template<typename T> bool QLayoutParameter< T >::isUser () const inline
Definition at line 124 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::fillRowData(), and QLayoutParameter< int >::value().
 { return q_state == User; }
setCachedValue()
template<typename T> void QLayoutParameter< T >::setCachedValue (T value) const inline
Definition at line 115 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::fillRowData().
{
         if (q_state != User) {
             q_value = value;
             q_state = Cached;
         }
     }
setUserValue()
template<typename T> void QLayoutParameter< T >::setUserValue (T value) inline
Definition at line 111 of file qgridlayoutengine_p.h.
{
         q_value = value;
         q_state = User;
     }
value() [1/2]
template<typename T> T QLayoutParameter< T >::value () const inline
Definition at line 121 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::fillRowData(), QGridLayoutEngine::rowSpacing(), QGridLayoutEngine::rowStretchFactor(), QLayoutParameter< int >::setCachedValue(), and QLayoutParameter< int >::setUserValue().
 { return q_value; }
value() [2/2]
template<typename T> T QLayoutParameter< T >::value (T defaultValue) const inline
Definition at line 122 of file qgridlayoutengine_p.h.
 { return isUser() ? q_value : defaultValue; }
Properties
q_state
template<typename T> State QLayoutParameter< T >::q_state mutable private
Definition at line 129 of file qgridlayoutengine_p.h.
Referenced by QLayoutParameter< int >::isCached(), QLayoutParameter< int >::isDefault(), QLayoutParameter< int >::isUser(), QLayoutParameter< int >::setCachedValue(), and QLayoutParameter< int >::setUserValue().
q_value
template<typename T> T QLayoutParameter< T >::q_value mutable private
Definition at line 128 of file qgridlayoutengine_p.h.
Referenced by QLayoutParameter< int >::setCachedValue(), QLayoutParameter< int >::setUserValue(), and QLayoutParameter< int >::value().
The documentation for this class was generated from the following file:
/src/gui/graphicsview/qgridlayoutengine_p.h