Qt 4.8: QHash< Key, T >::iterator Class Reference
QHash< Key, T >::iterator Class Reference
The QHash::iterator class provides an STL-style non-const iterator for QHash and QMultiHash.
#include <qhash.h>
Public Types
typedef qptrdiff difference_type
typedef std::bidirectional_iterator_tag iterator_category
typedef T * pointer
typedef T & reference
typedef T value_type
Public Functions
iterator ()
Constructs an uninitialized iterator.
iterator (void *node)
const Key & key () const
Returns the current item's key as a const reference.
operator Node * () const
bool operator!= (const iterator &o) const
Returns true if other points to a different item than this iterator; otherwise returns false.
bool operator!= (const const_iterator &o) const
T & operator* () const
Returns a modifiable reference to the current item's value.
iterator operator+ (int j) const
Returns an iterator to the item at j positions forward from this iterator.
iterator & operator++ ()
The prefix ++ operator (++i) advances the iterator to the next item in the hash and returns an iterator to the new current item.
iterator operator++ (int)
The postfix ++ operator (i++) advances the iterator to the next item in the hash and returns an iterator to the previously current item.
iterator & operator+= (int j)
Advances the iterator by j items.
iterator operator- (int j) const
Returns an iterator to the item at j positions backward from this iterator.
iterator & operator-- ()
The prefix – operator (–i) makes the preceding item current and returns an iterator pointing to the new current item.
iterator operator-- (int)
The postfix – operator (i–) makes the preceding item current and returns an iterator pointing to the previously current item.
iterator & operator-= (int j)
Makes the iterator go back by j items.
T * operator-> () const
Returns a pointer to the current item's value.
bool operator== (const iterator &o) const
Returns true if other points to the same item as this iterator; otherwise returns false.
bool operator== (const const_iterator &o) const
T & value () const
Returns a modifiable reference to the current item's value.
Private Functions
operator bool () const
Properties
QHashData::Node * i
Friends
class const_iterator
Detailed Description
template<class Key, class T>
class QHash< Key, T >::iterator
The QHash::iterator class provides an STL-style non-const iterator for QHash and QMultiHash.
QHash features both STL-style iterators and Java-style iterators. The STL-style iterators are more low-level and more cumbersome to use; on the other hand, they are slightly faster and, for developers who already know STL, have the advantage of familiarity.
QHash<Key, T>::iterator allows you to iterate over a QHash (or QMultiHash) and to modify the value (but not the key) associated with a particular key. If you want to iterate over a const QHash, you should use QHash::const_iterator. It is generally good practice to use QHash::const_iterator on a non-const QHash as well, unless you need to change the QHash through the iterator. Const iterators are slightly faster, and can improve code readability.
The default QHash::iterator constructor creates an uninitialized iterator. You must initialize it using a QHash function like QHash::begin(), QHash::end(), or QHash::find() before you can start iterating. Here's a typical loop that prints all the (key, value) pairs stored in a hash:
QHash<QString, int> hash;
hash.insert("January", 1);
hash.insert("February", 2);
...
hash.insert("December", 12);
QHash<QString, int>::iterator i;
for (i = hash.begin(); i != hash.end(); ++i)
    cout << i.key() << ": " << i.value() << endl;
Unlike QMap, which orders its items by key, QHash stores its items in an arbitrary order. The only guarantee is that items that share the same key (because they were inserted using QHash::insertMulti()) will appear consecutively, from the most recently to the least recently inserted value.
Let's see a few examples of things we can do with a QHash::iterator that we cannot do with a QHash::const_iterator. Here's an example that increments every value stored in the QHash by 2:
QHash<QString, int>::iterator i;
for (i = hash.begin(); i != hash.end(); ++i)
    i.value() += 2;
Here's an example that removes all the items whose key is a string that starts with an underscore character:
QHash<QString, int>::iterator i = hash.begin();
while (i != hash.end()) {
    if (i.key().startsWith("_"))
        i = hash.erase(i);
    else
        ++i;
}
The call to QHash::erase() removes the item pointed to by the iterator from the hash, and returns an iterator to the next item. Here's another way of removing an item while iterating:
QHash<QString, int>::iterator i = hash.begin();
while (i != hash.end()) {
    QHash<QString, int>::iterator prev = i;
    ++i;
    if (prev.key().startsWith("_"))
        hash.erase(prev);
}
It might be tempting to write code like this:
// WRONG
while (i != hash.end()) {
    if (i.key().startsWith("_"))
        hash.erase(i);
    ++i;
}
However, this will potentially crash in ++i, because i is a dangling iterator after the call to erase().
Multiple iterators can be used on the same hash. However, be aware that any modification performed directly on the QHash has the potential of dramatically changing the order in which the items are stored in the hash, as they might cause QHash to rehash its internal data structure. There is one notable exception: QHash::erase(). This function can safely be called while iterating, and won't affect the order of items in the hash. If you need to keep iterators over a long period of time, we recommend that you use QMap rather than QHash.
See also
QHash::const_iterator, QMutableHashIterator
Definition at line 330 of file qhash.h.
Typedefs
difference_type
template<class Key, class T> QHash< Key, T >::iterator::difference_type
Warning
This function is not part of the public interface.
Definition at line 337 of file qhash.h.
iterator_category
template<class Key, class T> QHash< Key, T >::iterator::iterator_category
Warning
This function is not part of the public interface.
Definition at line 336 of file qhash.h.
pointer
template<class Key, class T> QHash< Key, T >::iterator::pointer
Warning
This function is not part of the public interface.
Definition at line 339 of file qhash.h.
reference
template<class Key, class T> QHash< Key, T >::iterator::reference
Warning
This function is not part of the public interface.
Definition at line 340 of file qhash.h.
value_type
template<class Key, class T> QHash< Key, T >::iterator::value_type
Warning
This function is not part of the public interface.
Definition at line 338 of file qhash.h.
Constructors and Destructors
iterator() [1/2]
template<class Key, class T> QHash< Key, T >::iterator::iterator () inline
Constructs an uninitialized iterator.
Functions like key(), value(), and operator++() must not be called on an uninitialized iterator. Use operator=() to assign a value to it before using it.
See also
QHash::begin() QHash::end()
Definition at line 344 of file qhash.h.
 : i(0) { }
iterator() [2/2]
template<class Key, class T> QHash< Key, T >::iterator::iterator (void * node) inline explicit
Warning
This function is not part of the public interface.
Definition at line 345 of file qhash.h.
 : i(reinterpret_cast<QHashData::Node *>(node)) { }
Functions
key()
template<class Key, class T> const Key & QHash< Key, T >::iterator::key () const inline
Returns the current item's key as a const reference.
There is no direct way of changing an item's key through an iterator, although it can be done by calling QHash::erase() followed by QHash::insert() or QHash::insertMulti().
See also
value()
Definition at line 347 of file qhash.h.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onScriptsChanged(), QGraphicsScenePrivate::cancelGesturesForChildren(), QMetaObject::changeGuard(), QObjectPrivate::clearGuards(), QTextureGlyphCache::fillInPendingGlyphs(), QMultiHash< const QGLContext *, GLProgram >::find(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::insert(), QAbstractItemModelPrivate::Persistent::insertMultiAtEnd(), ModelNode::object(), qDBusRemoveTimeout(), QDeclarativeDebugConnectionPrivate::readyRead(), QDeclarativeDebugServer::receiveMessage(), QMultiHash< const QGLContext *, GLProgram >::remove(), QMainWindowLayout::removeFromMacToolbar(), QMetaObject::removeGuard(), QGtkStylePrivate::removeWidgetFromMap(), QApplication::syncX(), QPollingFileSystemWatcherEngine::timeout(), QMenuPrivate::QMacMenuPrivate::~QMacMenuPrivate(), and QMenu::~QMenu().
 { return concrete(i)->key; }
operator bool()
template<class Key, class T> QHash< Key, T >::iterator::operator bool () const inline private
Definition at line 391 of file qhash.h.
 { return false; }
operator Node *()
template<class Key, class T> QHash< Key, T >::iterator::operator Node * () const inline
Warning
This function is not part of the public interface.
Definition at line 343 of file qhash.h.
 { return concrete(i); }
operator!=() [1/2]
template<class Key, class T> bool QHash< Key, T >::iterator::operator!= (const iterator & o) const inline
Returns true if other points to a different item than this iterator; otherwise returns false.
Definition at line 352 of file qhash.h.
 { return i != o.i; }
operator!=() [2/2]
template<class Key, class T> bool QHash< Key, T >::iterator::operator!= (const const_iterator & other) const inline
See also
operator==()
Definition at line 386 of file qhash.h.
             { return i != o.i; }
operator*()
template<class Key, class T> T & QHash< Key, T >::iterator::operator* () const inline
Returns a modifiable reference to the current item's value.
Same as value().
See also
key()
Definition at line 349 of file qhash.h.
 { return concrete(i)->value; }
operator+()
template<class Key, class T> QHash::iterator QHash< Key, T >::iterator::operator+ (int j) const inline
Returns an iterator to the item at j positions forward from this iterator.
(If j is negative, the iterator goes backward.)
This operation can be slow for large j values.
See also
operator-()
Definition at line 372 of file qhash.h.
         { iterator r = *this; if (j > 0) while (j--) ++r; else while (j++) --r; return r; }
operator++() [1/2]
template<class Key, class T> QHash::iterator & QHash< Key, T >::iterator::operator++ () inline
The prefix ++ operator (++i) advances the iterator to the next item in the hash and returns an iterator to the new current item.
Calling this function on QHash::end() leads to undefined results.
See also
operator--()
Definition at line 354 of file qhash.h.
{
             i = QHashData::nextNode(i);
             return *this;
         }
operator++() [2/2]
template<class Key, class T> QHash::iterator QHash< Key, T >::iterator::operator++ (int) inline
The postfix ++ operator (i++) advances the iterator to the next item in the hash and returns an iterator to the previously current item.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 358 of file qhash.h.
{
             iterator r = *this;
             i = QHashData::nextNode(i);
             return r;
         }
operator+=()
template<class Key, class T> QHash::iterator & QHash< Key, T >::iterator::operator+= (int j) inline
Advances the iterator by j items.
(If j is negative, the iterator goes backward.)
See also
operator-=(), operator+()
Definition at line 375 of file qhash.h.
 { return *this = *this + j; }
operator-()
template<class Key, class T> QHash::iterator QHash< Key, T >::iterator::operator- (int j) const inline
Returns an iterator to the item at j positions backward from this iterator.
(If j is negative, the iterator goes forward.)
This operation can be slow for large j values.
See also
operator+()
Definition at line 374 of file qhash.h.
 { return operator+(-j); }
operator--() [1/2]
template<class Key, class T> QHash::iterator & QHash< Key, T >::iterator::operator-- () inline
The prefix – operator (–i) makes the preceding item current and returns an iterator pointing to the new current item.
Calling this function on QHash::begin() leads to undefined results.
See also
operator++()
Definition at line 363 of file qhash.h.
{
             i = QHashData::previousNode(i);
             return *this;
         }
operator--() [2/2]
template<class Key, class T> QHash::iterator QHash< Key, T >::iterator::operator-- (int) inline
The postfix – operator (i–) makes the preceding item current and returns an iterator pointing to the previously current item.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 367 of file qhash.h.
{
             iterator r = *this;
             i = QHashData::previousNode(i);
             return r;
         }
operator-=()
template<class Key, class T> QHash::iterator & QHash< Key, T >::iterator::operator-= (int j) inline
Makes the iterator go back by j items.
(If j is negative, the iterator goes forward.)
See also
operator+=(), operator-()
Definition at line 376 of file qhash.h.
 { return *this = *this - j; }
operator->()
template<class Key, class T> T * QHash< Key, T >::iterator::operator-> () const inline
Returns a pointer to the current item's value.
See also
value()
Definition at line 350 of file qhash.h.
 { return &concrete(i)->value; }
operator==() [1/2]
template<class Key, class T> bool QHash< Key, T >::iterator::operator== (const iterator & o) const inline
Returns true if other points to the same item as this iterator; otherwise returns false.
Definition at line 351 of file qhash.h.
 { return i == o.i; }
operator==() [2/2]
template<class Key, class T> bool QHash< Key, T >::iterator::operator== (const const_iterator & other) const inline
See also
operator!=()
Definition at line 384 of file qhash.h.
             { return i == o.i; }
value()
template<class Key, class T> T & QHash< Key, T >::iterator::value () const inline
Returns a modifiable reference to the current item's value.
You can change the value of an item by using value() on the left side of an assignment, for example:
if (i.key() == "Hello")
    i.value() = "Bonjour";
See also
key(), operator*()
Definition at line 348 of file qhash.h.
Referenced by QApplicationPrivate::_q_alertTimeOut(), QScriptEnginePrivate::_q_objectDestroyed(), QNetworkConfigurationManagerPrivate::allConfigurations(), QGLGlyphCache::cacheGlyphs(), QGraphicsScenePrivate::cancelGesturesForChildren(), QProcessManager::catchDeadChildren(), QMetaObject::changeGuard(), QGLGlyphCache::cleanCache(), QAxBase::clear(), QObjectPrivate::clearGuards(), QNetworkConfigurationManagerPrivate::defaultConfiguration(), QTextureGlyphCache::fillInPendingGlyphs(), QAuServerQWS::find(), QMultiHash< const QGLContext *, GLProgram >::find(), QNetworkDiskCache::insert(), QCache< QPixmapCache::Key, QPixmapCacheEntry >::insert(), QPaintBufferResource::insert(), qDBusRemoveTimeout(), QDeclarativeDebugConnectionPrivate::readyRead(), QDeclarativeDebugServer::receiveMessage(), QItemEditorFactory::registerEditor(), QPaintBufferResource::remove(), QMultiHash< const QGLContext *, GLProgram >::remove(), QMainWindowLayout::removeFromMacToolbar(), QMetaObject::removeGuard(), QGraphicsScenePrivate::removeItemHelper(), QApplication::syncX(), QPollingFileSystemWatcherEngine::timeout(), QEventDispatcherMac::unregisterTimers(), QPaintBufferResource::value(), QBearerEngine::~QBearerEngine(), QDeclarativeDebugConnection::~QDeclarativeDebugConnection(), QDeclarativeEngineDebugPrivate::~QDeclarativeEngineDebugPrivate(), QEventDispatcherMac::~QEventDispatcherMac(), QMenuPrivate::QMacMenuPrivate::~QMacMenuPrivate(), QMenu::~QMenu(), QPageSetupDialogPrivate::~QPageSetupDialogPrivate(), and QPrintDialogPrivate::~QPrintDialogPrivate().
 { return concrete(i)->value; }
Friends and Related Functions
const_iterator
template<class Key, class T> friend class const_iterator friend
Definition at line 332 of file qhash.h.
Properties
i
template<class Key, class T> QHashData::Node* QHash< Key, T >::iterator::i private
Definition at line 333 of file qhash.h.
Referenced by QHash< Key, T >::const_iterator::const_iterator(), QHash< Key, T >::iterator::operator!=(), and QHash< Key, T >::iterator::operator==().
The documentation for this class was generated from the following files:
/src/corelib/tools/qhash.h
/src/corelib/tools/qhash.cpp