Qt 4.8: QXcbScreen Class Reference
QXcbScreen Class Reference
#include <qxcbscreen.h>
Public Functions
int depth () const
Reimplement in subclass to return current depth of the screen.
QImage::Format format () const
Reimplement in subclass to return the image format which corresponds to the screen format.
QRect geometry () const
Reimplement in subclass to return the pixel geometry of the screen.
QSize physicalSize () const
Reimplement this function in subclass to return the physical size of the screen.
QXcbScreen (QXcbConnection *connection, xcb_screen_t *screen, int number)
xcb_window_t root () const
xcb_screen_t * screen () const
int screenNumber () const
bool syncRequestSupported () const
QString windowManagerName () const
~QXcbScreen ()
Public Functions inherited from QXcbObject
xcb_atom_t atom (QXcbAtom::Atom atom) const
QXcbConnection * connection () const
QXcbObject (QXcbConnection *connection=0)
void setConnection (QXcbConnection *connection)
xcb_connection_t * xcb_connection () const
Public Functions inherited from QPlatformScreen
virtual QRect availableGeometry () const
Reimplement in subclass to return the pixel geometry of the available space This normally is the desktop screen minus the task manager, global menubar etc.
virtual void setDirty (const QRect &)
virtual QWidget * topLevelAt (const QPoint &point) const
Return the given top level widget for a given position.
virtual ~QPlatformScreen ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
int m_number
xcb_screen_t * m_screen
bool m_syncRequestSupported
QString m_windowManagerName
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QPlatformScreen
static QPlatformScreen * platformScreenForWidget (const QWidget *widget)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 54 of file qxcbscreen.h.
Constructors and Destructors
QXcbScreen()
QXcbScreen::QXcbScreen (QXcbConnection * connection, xcb_screen_t * screen, int number)
Definition at line 46 of file qxcbscreen.cpp.
     : QXcbObject(connection)
     , m_screen(screen)
     , m_number(number)
 {
     printf ("\n");
     printf ("Information of screen %d:\n", screen->root);
     printf ("  width.........: %d\n", screen->width_in_pixels);
     printf ("  height........: %d\n", screen->height_in_pixels);
     printf ("  depth.........: %d\n", screen->root_depth);
     printf ("  white pixel...: %x\n", screen->white_pixel);
     printf ("  black pixel...: %x\n", screen->black_pixel);
     printf ("\n");
     const quint32 mask = XCB_CW_EVENT_MASK;
     const quint32 values[] = {
         // XCB_CW_EVENT_MASK
         XCB_EVENT_MASK_ENTER_WINDOW
         | XCB_EVENT_MASK_LEAVE_WINDOW
         | XCB_EVENT_MASK_PROPERTY_CHANGE
     };
     xcb_change_window_attributes(xcb_connection(), screen->root, mask, values);
     xcb_generic_error_t *error;
     xcb_get_property_reply_t *reply =
         xcb_get_property_reply(xcb_connection(),
             xcb_get_property(xcb_connection(), false, screen->root,
                              atom(QXcbAtom::_NET_SUPPORTING_WM_CHECK),
                              XCB_ATOM_WINDOW, 0, 1024), &error);
     if (reply && reply->format == 32 && reply->type == XCB_ATOM_WINDOW) {
         xcb_window_t windowManager = *((xcb_window_t *)xcb_get_property_value(reply));
         if (windowManager != XCB_WINDOW_NONE) {
             xcb_get_property_reply_t *windowManagerReply =
                 xcb_get_property_reply(xcb_connection(),
                     xcb_get_property(xcb_connection(), false, windowManager,
                                      atom(QXcbAtom::_NET_WM_NAME),
                                      atom(QXcbAtom::UTF8_STRING), 0, 1024), &error);
             if (windowManagerReply && windowManagerReply->format == 8 && windowManagerReply->type == atom(QXcbAtom::UTF8_STRING)) {
                 m_windowManagerName = QString::fromUtf8((const char *)xcb_get_property_value(windowManagerReply), xcb_get_property_value_length(windowManagerReply));
                 printf("Running window manager: %s\n", qPrintable(m_windowManagerName));
             } else if (error) {
                 connection->handleXcbError(error);
                 free(error);
             }
             free(windowManagerReply);
         }
     } else if (error) {
         connection->handleXcbError(error);
         free(error);
     }
     free(reply);
     m_syncRequestSupported = m_windowManagerName != QLatin1String("KWin");
 }
~QXcbScreen()
QXcbScreen::~QXcbScreen ()
Definition at line 107 of file qxcbscreen.cpp.
 {
 }
Functions
depth()
int QXcbScreen::depth () const virtual
Reimplement in subclass to return current depth of the screen.
Implements QPlatformScreen.
Definition at line 116 of file qxcbscreen.cpp.
 {
     return m_screen->root_depth;
 }
format()
QImage::Format QXcbScreen::format () const virtual
Reimplement in subclass to return the image format which corresponds to the screen format.
Implements QPlatformScreen.
Definition at line 121 of file qxcbscreen.cpp.
 {
     return QImage::Format_RGB32;
 }
geometry()
QRect QXcbScreen::geometry () const virtual
Reimplement in subclass to return the pixel geometry of the screen.
Implements QPlatformScreen.
Definition at line 111 of file qxcbscreen.cpp.
 {
     return QRect(0, 0, m_screen->width_in_pixels, m_screen->height_in_pixels);
 }
physicalSize()
QSize QXcbScreen::physicalSize () const virtual
Reimplement this function in subclass to return the physical size of the screen.
This function is used by QFont to convert point sizes to pixel sizes.
The default implementation takes the pixel size of the screen, considers a resolution of 100 dots per inch, and returns the calculated physical size. A device with a screen that has different resolutions will need to be supported by a suitable reimplementation of this function.
Reimplemented from QPlatformScreen.
Definition at line 126 of file qxcbscreen.cpp.
 {
     return QSize(m_screen->width_in_millimeters, m_screen->height_in_millimeters);
 }
root()
xcb_window_t QXcbScreen::root () const inline
Definition at line 68 of file qxcbscreen.h.
Referenced by QXcbWindow::handleClientMessageEvent(), QXcbWindow::QXcbWindow(), and QXcbWindow::setVisible().
 { return m_screen->root; }
screen()
xcb_screen_t* QXcbScreen::screen () const inline
Definition at line 67 of file qxcbscreen.h.
Referenced by QXcbWindow::QXcbWindow(), and QXcbNativeInterface::screenForWidget().
 { return m_screen; }
screenNumber()
int QXcbScreen::screenNumber () const
Definition at line 131 of file qxcbscreen.cpp.
Referenced by QGLXContext::QGLXContext(), and QXcbWindow::QXcbWindow().
 {
     return m_number;
 }
syncRequestSupported()
bool QXcbScreen::syncRequestSupported () const inline
Definition at line 71 of file qxcbscreen.h.
Referenced by QXcbWindow::QXcbWindow(), QXcbWindow::updateSyncRequestCounter(), and QXcbWindow::~QXcbWindow().
 { return m_syncRequestSupported; }
windowManagerName()
QString QXcbScreen::windowManagerName () const inline
Definition at line 70 of file qxcbscreen.h.
 { return m_windowManagerName; }
Properties
m_number
int QXcbScreen::m_number private
Definition at line 75 of file qxcbscreen.h.
Referenced by screenNumber().
m_screen
xcb_screen_t* QXcbScreen::m_screen private
Definition at line 74 of file qxcbscreen.h.
Referenced by depth(), geometry(), physicalSize(), root(), and screen().
m_syncRequestSupported
bool QXcbScreen::m_syncRequestSupported private
Definition at line 77 of file qxcbscreen.h.
Referenced by QXcbScreen(), and syncRequestSupported().
m_windowManagerName
QString QXcbScreen::m_windowManagerName private
Definition at line 76 of file qxcbscreen.h.
Referenced by QXcbScreen(), and windowManagerName().
The documentation for this class was generated from the following files:
/src/plugins/platforms/xcb/qxcbscreen.h
/src/plugins/platforms/xcb/qxcbscreen.cpp