Qt 4.8: QPlainTextEdit Class Reference
QPlainTextEdit Class Reference
The QPlainTextEdit class provides a widget that is used to edit and display plain text.
#include <qplaintextedit.h>
Public Types
enum LineWrapMode { NoWrap, WidgetWidth }
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void appendHtml (const QString &html)
Appends a new paragraph with html to the end of the text edit.
void appendPlainText (const QString &text)
Appends a new paragraph with text to the end of the text edit.
void centerCursor ()
Scrolls the document in order to center the cursor vertically.
void clear ()
Deletes all the text in the text edit.
void copy ()
Copies any selected text to the clipboard.
void cut ()
Copies the selected text to the clipboard and deletes it from the text edit.
void insertPlainText (const QString &text)
Convenience slot that inserts text at the current cursor position.
void paste ()
Pastes the text from the clipboard into the text edit at the current cursor position.
void redo ()
Redoes the last operation.
void selectAll ()
Selects all text.
void setPlainText (const QString &text)
Changes the text of the text edit to the string text.
void undo ()
Undoes the last operation.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void blockCountChanged (int newBlockCount)
This signal is emitted whenever the block count changes.
void copyAvailable (bool b)
This signal is emitted when text is selected or de-selected in the text edit.
void cursorPositionChanged ()
This signal is emitted whenever the position of the cursor changed.
void modificationChanged (bool)
This signal is emitted whenever the content of the document changes in a way that affects the modification state.
void redoAvailable (bool b)
This signal is emitted whenever redo operations become available (available is true) or unavailable (available is false).
void selectionChanged ()
This signal is emitted whenever the selection changes.
void textChanged ()
This signal is emitted whenever the document's content changes; for example, when text is inserted or deleted, or when formatting is applied.
void undoAvailable (bool b)
This signal is emitted whenever undo operations become available (available is true) or unavailable (available is false).
void updateRequest (const QRect &rect, int dy)
This signal is emitted when the text document needs an update of the specified rect.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QString anchorAt (const QPoint &pos) const
Returns the reference of the anchor at position pos, or an empty string if no anchor exists at that point.
bool backgroundVisible () const
int blockCount () const
bool canPaste () const
Returns whether text can be pasted from the clipboard into the textedit.
bool centerOnScroll () const
QMenu * createStandardContextMenu ()
This function creates the standard context menu which is shown when the user clicks on the line edit with the right mouse button.
QTextCharFormat currentCharFormat () const
Returns the char format that is used when inserting new text.
QTextCursor cursorForPosition (const QPoint &pos) const
returns a QTextCursor at position pos (in viewport coordinates).
QRect cursorRect (const QTextCursor &cursor) const
returns a rectangle (in viewport coordinates) that includes the cursor.
QRect cursorRect () const
returns a rectangle (in viewport coordinates) that includes the cursor of the text edit.
int cursorWidth () const
QTextDocument * document () const
Returns a pointer to the underlying document.
QString documentTitle () const
void ensureCursorVisible ()
Ensures that the cursor is visible by scrolling the text edit if necessary.
QList< QTextEdit::ExtraSelection > extraSelections () const
Returns previously set extra selections.
bool find (const QString &exp, QTextDocument::FindFlags options=0)
Finds the next occurrence of the string, exp, using the given options.
bool isReadOnly () const
bool isUndoRedoEnabled () const
LineWrapMode lineWrapMode () const
virtual QVariant loadResource (int type, const QUrl &name)
Loads the resource specified by the given type and name.
int maximumBlockCount () const
void mergeCurrentCharFormat (const QTextCharFormat &modifier)
Merges the properties specified in modifier into the current character format by calling QTextCursor::mergeCharFormat on the editor's cursor.
void moveCursor (QTextCursor::MoveOperation operation, QTextCursor::MoveMode mode=QTextCursor::MoveAnchor)
Moves the cursor by performing the given operation.
bool overwriteMode () const
void print (QPrinter *printer) const
Convenience function to print the text edit's document to the given printer.
QPlainTextEdit (QWidget *parent=0)
Constructs an empty QPlainTextEdit with parent parent.
QPlainTextEdit (const QString &text, QWidget *parent=0)
Constructs a QPlainTextEdit with parent parent.
void setBackgroundVisible (bool visible)
void setCenterOnScroll (bool enabled)
void setCurrentCharFormat (const QTextCharFormat &format)
Sets the char format that is be used when inserting new text to format by calling QTextCursor::setCharFormat() on the editor's cursor.
void setCursorWidth (int width)
void setDocument (QTextDocument *document)
Makes document the new document of the text editor.
void setDocumentTitle (const QString &title)
void setExtraSelections (const QList< QTextEdit::ExtraSelection > &selections)
This function allows temporarily marking certain regions in the document with a given color, specified as selections.
void setLineWrapMode (LineWrapMode mode)
void setMaximumBlockCount (int maximum)
void setOverwriteMode (bool overwrite)
void setReadOnly (bool ro)
void setTabChangesFocus (bool b)
void setTabStopWidth (int width)
void setTextCursor (const QTextCursor &cursor)
Sets the visible cursor.
void setTextInteractionFlags (Qt::TextInteractionFlags flags)
void setUndoRedoEnabled (bool enable)
void setWordWrapMode (QTextOption::WrapMode policy)
bool tabChangesFocus () const
int tabStopWidth () const
QTextCursor textCursor () const
Returns a copy of the QTextCursor that represents the currently visible cursor.
Qt::TextInteractionFlags textInteractionFlags () const
QString toPlainText () const
Returns the text of the text edit as plain text.
QTextOption::WrapMode wordWrapMode () const
the mode QPlainTextEdit will use when wrapping text by words
virtual ~QPlainTextEdit ()
Destructor.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
QRectF blockBoundingGeometry (const QTextBlock &block) const
Returns the bounding rectangle of the text block in content coordinates.
QRectF blockBoundingRect (const QTextBlock &block) const
Returns the bounding rectangle of the text block in the block's own coordinates.
virtual bool canInsertFromMimeData (const QMimeData *source) const
This function returns true if the contents of the MIME data object, specified by source, can be decoded and inserted into the document.
virtual void changeEvent (QEvent *e)
Reimplemented Function
QPointF contentOffset () const
Returns the content's origin in viewport coordinates.
virtual void contextMenuEvent (QContextMenuEvent *e)
Shows the standard context menu created with createStandardContextMenu().
virtual QMimeData * createMimeDataFromSelection () const
This function returns a new MIME data object to represent the contents of the text edit's current selection.
virtual void dragEnterEvent (QDragEnterEvent *e)
Reimplemented Function
virtual void dragLeaveEvent (QDragLeaveEvent *e)
Reimplemented Function
virtual void dragMoveEvent (QDragMoveEvent *e)
Reimplemented Function
virtual void dropEvent (QDropEvent *e)
Reimplemented Function
virtual bool event (QEvent *e)
QTextBlock firstVisibleBlock () const
Returns the first visible block.
virtual void focusInEvent (QFocusEvent *e)
Reimplemented Function
virtual bool focusNextPrevChild (bool next)
Reimplemented Function
virtual void focusOutEvent (QFocusEvent *e)
Reimplemented Function
QAbstractTextDocumentLayout::PaintContext getPaintContext () const
Returns the paint context for the viewport(), useful only when reimplementing paintEvent().
virtual void inputMethodEvent (QInputMethodEvent *)
Reimplemented Function
QVariant inputMethodQuery (Qt::InputMethodQuery property) const
This method is only relevant for input widgets.
virtual void insertFromMimeData (const QMimeData *source)
This function inserts the contents of the MIME data object, specified by source, into the text edit at the current cursor position.
virtual void keyPressEvent (QKeyEvent *e)
Reimplemented Function
virtual void keyReleaseEvent (QKeyEvent *e)
Reimplemented Function
virtual void mouseDoubleClickEvent (QMouseEvent *e)
Reimplemented Function
virtual void mouseMoveEvent (QMouseEvent *e)
Reimplemented Function
virtual void mousePressEvent (QMouseEvent *e)
Reimplemented Function
virtual void mouseReleaseEvent (QMouseEvent *e)
Reimplemented Function
virtual void paintEvent (QPaintEvent *e)
Reimplemented Function
QPlainTextEdit (QPlainTextEditPrivate &dd, QWidget *parent)
virtual void resizeEvent (QResizeEvent *e)
Reimplemented Function
virtual void scrollContentsBy (int dx, int dy)
em>Reimplemented Function
virtual void showEvent (QShowEvent *)
Reimplemented Function
virtual void timerEvent (QTimerEvent *e)
virtual void wheelEvent (QWheelEvent *e)
Reimplemented Function
Protected Functions inherited from QAbstractScrollArea
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
virtual bool viewportEvent (QEvent *)
The main event handler for the scrolling area (the viewport() widget).
Protected Functions inherited from QFrame
void drawFrame (QPainter *)
em>Reimplemented Function
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool backgroundVisible
whether the palette background is visible outside the document area
int blockCount
the number of text blocks in the document.
bool centerOnScroll
whether the cursor should be centered on screen
int cursorWidth
This property specifies the width of the cursor in pixels.
QString documentTitle
the title of the document parsed from the text.
LineWrapMode lineWrapMode
the line wrap mode
int maximumBlockCount
the limit for blocks in the document.
bool overwriteMode
whether text entered by the user will overwrite existing text
QString plainText
This property gets and sets the plain text editor's contents.
bool readOnly
whether the text edit is read-only
bool tabChangesFocus
whether Tab changes focus or is accepted as input
int tabStopWidth
the tab stop width in pixels
Qt::TextInteractionFlags textInteractionFlags
Specifies how the label should interact with user input if it displays text.
bool undoRedoEnabled
whether undo and redo are enabled
Friends
class QPlainTextEditControl
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QPlainTextEdit class provides a widget that is used to edit and display plain text.
Since
4.4
Introduction and Concepts
QPlainTextEdit is an advanced viewer/editor supporting plain text. It is optimized to handle large documents and to respond quickly to user input.
QPlainText uses very much the same technology and concepts as QTextEdit, but is optimized for plain text handling.
QPlainTextEdit works on paragraphs and characters. A paragraph is a formatted string which is word-wrapped to fit into the width of the widget. By default when reading plain text, one newline signifies a paragraph. A document consists of zero or more paragraphs. Paragraphs are separated by hard line breaks. Each character within a paragraph has its own attributes, for example, font and color.
The shape of the mouse cursor on a QPlainTextEdit is Qt::IBeamCursor by default. It can be changed through the viewport()'s cursor property.
Using QPlainTextEdit as a Display Widget
The text is set or replaced using setPlainText() which deletes the existing text and replaces it with the text passed to setPlainText().
Text can be inserted using the QTextCursor class or using the convenience functions insertPlainText(), appendPlainText() or paste().
By default, the text edit wraps words at whitespace to fit within the text edit widget. The setLineWrapMode() function is used to specify the kind of line wrap you want, WidgetWidth or NoWrap if you don't want any wrapping. If you use word wrap to the widget's width WidgetWidth , you can specify whether to break on whitespace or anywhere with setWordWrapMode().
The find() function can be used to find and select a given string within the text.
If you want to limit the total number of paragraphs in a QPlainTextEdit, as it is for example useful in a log viewer, then you can use the maximumBlockCount property. The combination of setMaximumBlockCount() and appendPlainText() turns QPlainTextEdit into an efficient viewer for log text. The scrolling can be reduced with the centerOnScroll() property, making the log viewer even faster. Text can be formatted in a limited way, either using a syntax highlighter (see below), or by appending html-formatted text with appendHtml(). While QPlainTextEdit does not support complex rich text rendering with tables and floats, it does support limited paragraph-based formatting that you may need in a log viewer.
Read-only Key Bindings
When QPlainTextEdit is used read-only the key bindings are limited to navigation, and text may only be selected with the mouse:
Keypresses Action
Qt::UpArrow Moves one line up.
Qt::DownArrow Moves one line down.
Qt::LeftArrow Moves one character to the left.
Qt::RightArrow Moves one character to the right.
PageUp Moves one (viewport) page up.
PageDown Moves one (viewport) page down.
Home Moves to the beginning of the text.
End Moves to the end of the text.
Alt+Wheel Scrolls the page horizontally (the Wheel is the mouse wheel).
Ctrl+Wheel Zooms the text.
Ctrl+A Selects all text.
Using QPlainTextEdit as an Editor
All the information about using QPlainTextEdit as a display widget also applies here.
Selection of text is handled by the QTextCursor class, which provides functionality for creating selections, retrieving the text contents or deleting selections. You can retrieve the object that corresponds with the user-visible cursor using the textCursor() method. If you want to set a selection in QPlainTextEdit just create one on a QTextCursor object and then make that cursor the visible cursor using setCursor(). The selection can be copied to the clipboard with copy(), or cut to the clipboard with cut(). The entire text can be selected using selectAll().
QPlainTextEdit holds a QTextDocument object which can be retrieved using the document() method. You can also set your own document object using setDocument(). QTextDocument emits a textChanged() signal if the text changes and it also provides a isModified() function which will return true if the text has been modified since it was either loaded or since the last call to setModified with false as argument. In addition it provides methods for undo and redo.
Syntax Highlighting
Just like QTextEdit, QPlainTextEdit works together with QSyntaxHighlighter.
Editing Key Bindings
The list of key bindings which are implemented for editing:
Keypresses Action
Backspace Deletes the character to the left of the cursor.
Delete Deletes the character to the right of the cursor.
Ctrl+C Copy the selected text to the clipboard.
Ctrl+Insert Copy the selected text to the clipboard.
Ctrl+K Deletes to the end of the line.
Ctrl+V Pastes the clipboard text into text edit.
Shift+Insert Pastes the clipboard text into text edit.
Ctrl+X Deletes the selected text and copies it to the clipboard.
Shift+Delete Deletes the selected text and copies it to the clipboard.
Ctrl+Z Undoes the last operation.
Ctrl+Y Redoes the last operation.
LeftArrow Moves the cursor one character to the left.
Ctrl+LeftArrow Moves the cursor one word to the left.
RightArrow Moves the cursor one character to the right.
Ctrl+RightArrow Moves the cursor one word to the right.
UpArrow Moves the cursor one line up.
Ctrl+UpArrow Moves the cursor one word up.
DownArrow Moves the cursor one line down.
Ctrl+Down Arrow Moves the cursor one word down.
PageUp Moves the cursor one page up.
PageDown Moves the cursor one page down.
Home Moves the cursor to the beginning of the line.
Ctrl+Home Moves the cursor to the beginning of the text.
End Moves the cursor to the end of the line.
Ctrl+End Moves the cursor to the end of the text.
Alt+Wheel Scrolls the page horizontally (the Wheel is the mouse wheel).
Ctrl+Wheel Zooms the text.
To select (mark) text hold down the Shift key whilst pressing one of the movement keystrokes, for example, Shift+Right Arrow will select the character to the right, and Shift+Ctrl+Right Arrow will select the word to the right, etc.
Differences to QTextEdit
QPlainTextEdit is a thin class, implemented by using most of the technology that is behind QTextEdit and QTextDocument. Its performance benefits over QTextEdit stem mostly from using a different and simplified text layout called QPlainTextDocumentLayout on the text document (see QTextDocument::setDocumentLayout()). The plain text document layout does not support tables nor embedded frames, and replaces a pixel-exact height calculation with a line-by-line respectively paragraph-by-paragraph scrolling approach. This makes it possible to handle significantly larger documents, and still resize the editor with line wrap enabled in real time. It also makes for a fast log viewer (see setMaximumBlockCount()).
See also
QTextDocument, QTextCursor, {Application Example}, {Code Editor Example}, {Syntax Highlighter Example}, {Rich Text Processing}
Definition at line 69 of file qplaintextedit.h.
Enumerations
LineWrapMode
enum QPlainTextEdit::LineWrapMode
NoWrap
WidgetWidth
Enumerator
NoWrap
WidgetWidth
Definition at line 90 of file qplaintextedit.h.
                       {
         NoWrap,
         WidgetWidth
     };
Constructors and Destructors
QPlainTextEdit() [1/3]
QPlainTextEdit::QPlainTextEdit (QWidget * parent = 0) explicit
Constructs an empty QPlainTextEdit with parent parent.
Definition at line 1244 of file qplaintextedit.cpp.
     : QAbstractScrollArea(*new QPlainTextEditPrivate, parent)
 {
     Q_D(QPlainTextEdit);
     d->init();
 }
QPlainTextEdit() [2/3]
QPlainTextEdit::QPlainTextEdit (const QString & text, QWidget * parent = 0) explicit
Constructs a QPlainTextEdit with parent parent.
The text edit will display the plain text text.
Definition at line 1265 of file qplaintextedit.cpp.
     : QAbstractScrollArea(*new QPlainTextEditPrivate, parent)
 {
     Q_D(QPlainTextEdit);
     d->init(text);
 }
~QPlainTextEdit()
QPlainTextEdit::~QPlainTextEdit () virtual
Destructor.
Definition at line 1276 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     if (d->documentLayoutPtr) {
         if (d->documentLayoutPtr->priv()->mainViewPrivate == d)
             d->documentLayoutPtr->priv()->mainViewPrivate = 0;
     }
 }
QPlainTextEdit() [3/3]
QPlainTextEdit::QPlainTextEdit (QPlainTextEditPrivate & dd, QWidget * parent) protected
Warning
This function is not part of the public interface.
Definition at line 1254 of file qplaintextedit.cpp.
     : QAbstractScrollArea(dd, parent)
 {
     Q_D(QPlainTextEdit);
     d->init();
 }
Functions
anchorAt()
QString QPlainTextEdit::anchorAt (const QPoint & pos) const
Returns the reference of the anchor at position pos, or an empty string if no anchor exists at that point.
Since
4.7
Definition at line 1359 of file qplaintextedit.cpp.
 {
     Q_D(const QPlainTextEdit);
     int cursorPos = d->control->hitTest(pos + QPointF(d->horizontalOffset(),
                                                      d->verticalOffset()),
                                         Qt::ExactHit);
     if (cursorPos < 0)
         return QString();
     QTextDocumentPrivate *pieceTable = document()->docHandle();
     QTextDocumentPrivate::FragmentIterator it = pieceTable->find(cursorPos);
     QTextCharFormat fmt = pieceTable->formatCollection()->charFormat(it->format);
     return fmt.anchorHref();
 }
appendHtml
void QPlainTextEdit::appendHtml (const QString & html) slot
Appends a new paragraph with html to the end of the text edit.
appendPlainText()
Definition at line 2914 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->append(html, Qt::RichText);
 }
appendPlainText
void QPlainTextEdit::appendPlainText (const QString & text) slot
Appends a new paragraph with text to the end of the text edit.
See also
appendHtml()
Definition at line 2902 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->append(text, Qt::PlainText);
 }
backgroundVisible()
bool QPlainTextEdit::backgroundVisible () const
Referenced by paintEvent(), and setWordWrapMode().
blockBoundingGeometry()
QRectF QPlainTextEdit::blockBoundingGeometry (const QTextBlock & block) const protected
Returns the bounding rectangle of the text block in content coordinates.
Translate the rectangle with the contentOffset() to get visual coordinates on the viewport.
See also
firstVisibleBlock(), blockBoundingRect()
Definition at line 2996 of file qplaintextedit.cpp.
Referenced by QScriptEdit::extraAreaPaintEvent().
 {
     Q_D(const QPlainTextEdit);
     return d->control->blockBoundingRect(block);
 }
blockBoundingRect()
QRectF QPlainTextEdit::blockBoundingRect (const QTextBlock & block) const protected
Returns the bounding rectangle of the text block in the block's own coordinates.
See also
blockBoundingGeometry()
Definition at line 3007 of file qplaintextedit.cpp.
Referenced by QScriptEdit::extraAreaPaintEvent(), and paintEvent().
 {
     QPlainTextDocumentLayout *documentLayout = qobject_cast<QPlainTextDocumentLayout*>(document()->documentLayout());
     Q_ASSERT(documentLayout);
     return documentLayout->blockBoundingRect(block);
 }
blockCount()
int QPlainTextEdit::blockCount () const
Referenced by blockBoundingRect(), and QScriptEdit::extraAreaWidth().
blockCountChanged
void QPlainTextEdit::blockCountChanged (int newBlockCount) signal
This signal is emitted whenever the block count changes.
The new block count is passed in newBlockCount.
Referenced by QScriptEdit::QScriptEdit().
canInsertFromMimeData()
bool QPlainTextEdit::canInsertFromMimeData (const QMimeData * source) const protected virtual
This function returns true if the contents of the MIME data object, specified by source, can be decoded and inserted into the document.
It is called for example when during a drag operation the mouse enters this widget and it is necessary to determine whether it is possible to accept the drag.
Definition at line 2407 of file qplaintextedit.cpp.
Referenced by QPlainTextEditControl::canInsertFromMimeData().
 {
     Q_D(const QPlainTextEdit);
     return d->control->QTextControl::canInsertFromMimeData(source);
 }
canPaste()
bool QPlainTextEdit::canPaste () const
Returns whether text can be pasted from the clipboard into the textedit.
Definition at line 2555 of file qplaintextedit.cpp.
 {
     Q_D(const QPlainTextEdit);
     return d->control->canPaste();
 }
centerCursor
void QPlainTextEdit::centerCursor () slot
Scrolls the document in order to center the cursor vertically.
See also
ensureCursorVisible(), centerOnScroll
Definition at line 2953 of file qplaintextedit.cpp.
Referenced by QScriptEdit::gotoLine().
 {
     Q_D(QPlainTextEdit);
     d->ensureVisible(textCursor().position(), true, true);
 }
centerOnScroll()
bool QPlainTextEdit::centerOnScroll () const
Referenced by QPlainTextEditPrivate::append(), paintEvent(), and setBackgroundVisible().
changeEvent()
void QPlainTextEdit::changeEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QFrame.
Definition at line 2202 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     QAbstractScrollArea::changeEvent(e);
     if (e->type() == QEvent::ApplicationFontChange
         || e->type() == QEvent::FontChange) {
         d->control->document()->setDefaultFont(font());
     }  else if(e->type() == QEvent::ActivationChange) {
         if (!isActiveWindow())
             d->autoScrollTimer.stop();
     } else if (e->type() == QEvent::EnabledChange) {
         e->setAccepted(isEnabled());
         d->sendControlEvent(e);
     } else if (e->type() == QEvent::PaletteChange) {
         d->control->setPalette(palette());
     } else if (e->type() == QEvent::LayoutDirectionChange) {
         d->sendControlEvent(e);
     }
 }
clear
void QPlainTextEdit::clear () slot
Deletes all the text in the text edit.
Note that the undo/redo history is cleared by this function.
See also
cut() setPlainText()
Definition at line 1464 of file qplaintextedit.cpp.
Referenced by keyPressEvent(), and timerEvent().
 {
     Q_D(QPlainTextEdit);
     // clears and sets empty content
     d->control->topBlock = d->topLine = d->topLineFracture = 0;
     d->control->clear();
 }
contentOffset()
QPointF QPlainTextEdit::contentOffset () const protected
Returns the content's origin in viewport coordinates.
The origin of the content of a plain text edit is always the top left corner of the first visible text block. The content offset is different from (0,0) when the text has been scrolled horizontally, or when the first visible block has been scrolled partially off the screen, i.e. the visible text does not start with the first line of the first visible block, or when the first visible block is the very first block and the editor displays a margin.
See also
firstVisibleBlock(), horizontalScrollBar(), verticalScrollBar()
Definition at line 2983 of file qplaintextedit.cpp.
Referenced by QScriptEdit::extraAreaPaintEvent(), and paintEvent().
 {
     Q_D(const QPlainTextEdit);
     return QPointF(-d->horizontalOffset(), -d->verticalOffset());
 }
contextMenuEvent()
void QPlainTextEdit::contextMenuEvent (QContextMenuEvent * event) protected virtual
Shows the standard context menu created with createStandardContextMenu().
If you do not want the text edit to have a context menu, you can set its contextMenuPolicy to Qt::NoContextMenu. If you want to customize the context menu, reimplement this function. If you want to extend the standard context menu, reimplement this function, call createStandardContextMenu() and extend the menu returned.
Information about the event is passed in the event object.
void MyQPlainTextEdit::contextMenuEvent(QContextMenuEvent *event)
{
    QMenu *menu = createStandardContextMenu();
    menu->addAction(tr("My Menu Item"));
    //...
    menu->exec(event->globalPos());
    delete menu;
}
Reimplemented from QAbstractScrollArea.
Definition at line 2075 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->sendControlEvent(e);
 }
copy
void QPlainTextEdit::copy () slot
Copies any selected text to the clipboard.
See also
copyAvailable()
Definition at line 1430 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->copy();
 }
copyAvailable
void QPlainTextEdit::copyAvailable (bool yes) signal
This signal is emitted when text is selected or de-selected in the text edit.
When text is selected this signal will be emitted with yes set to true. If no text has been selected or if the selected text is de-selected this signal is emitted with yes set to false.
If yes is true then copy() can be used to copy the selection to the clipboard. If yes is false then copy() does nothing.
See also
selectionChanged()
createMimeDataFromSelection()
QMimeData * QPlainTextEdit::createMimeDataFromSelection () const protected virtual
This function returns a new MIME data object to represent the contents of the text edit's current selection.
It is called when the selection needs to be encapsulated into a new QMimeData object; for example, when a drag and drop operation is started, or when data is copied to the clipboard.
If you reimplement this function, note that the ownership of the returned QMimeData object is passed to the caller. The selection can be retrieved by using the textCursor() function.
Definition at line 2395 of file qplaintextedit.cpp.
Referenced by QPlainTextEditControl::createMimeDataFromSelection().
 {
     Q_D(const QPlainTextEdit);
     return d->control->QTextControl::createMimeDataFromSelection();
 }
createStandardContextMenu()
QMenu * QPlainTextEdit::createStandardContextMenu ()
This function creates the standard context menu which is shown when the user clicks on the line edit with the right mouse button.
It is called from the default contextMenuEvent() handler. The popup menu's ownership is transferred to the caller.
Definition at line 2239 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     return d->control->createStandardContextMenu(QPointF(), this);
 }
currentCharFormat()
QTextCharFormat QPlainTextEdit::currentCharFormat () const
Returns the char format that is used when inserting new text.
Definition at line 2514 of file qplaintextedit.cpp.
 {
     Q_D(const QPlainTextEdit);
     return d->control->currentCharFormat();
 }
cursorForPosition()
QTextCursor QPlainTextEdit::cursorForPosition (const QPoint & pos) const
returns a QTextCursor at position pos (in viewport coordinates).
Definition at line 2249 of file qplaintextedit.cpp.
Referenced by QScriptEdit::extraAreaMouseEvent().
 {
     Q_D(const QPlainTextEdit);
     return d->control->cursorForPosition(d->mapToContents(pos));
 }
cursorPositionChanged
void QPlainTextEdit::cursorPositionChanged () signal
This signal is emitted whenever the position of the cursor changed.
Referenced by QScriptEdit::QScriptEdit().
cursorRect() [1/2]
QRect QPlainTextEdit::cursorRect (const QTextCursor & cursor) const
returns a rectangle (in viewport coordinates) that includes the cursor.
Definition at line 2259 of file qplaintextedit.cpp.
 {
     Q_D(const QPlainTextEdit);
     if (cursor.isNull())
         return QRect();
     QRect r = d->control->cursorRect(cursor).toRect();
     r.translate(-d->horizontalOffset(),-(int)d->verticalOffset());
     return r;
 }
cursorRect() [2/2]
QRect QPlainTextEdit::cursorRect () const
returns a rectangle (in viewport coordinates) that includes the cursor of the text edit.
Definition at line 2274 of file qplaintextedit.cpp.
Referenced by event().
 {
     Q_D(const QPlainTextEdit);
     QRect r = d->control->cursorRect().toRect();
     r.translate(-d->horizontalOffset(),-(int)d->verticalOffset());
     return r;
 }
cursorWidth()
int QPlainTextEdit::cursorWidth () const
Referenced by paintEvent(), and setTabStopWidth().
cut
void QPlainTextEdit::cut () slot
Copies the selected text to the clipboard and deletes it from the text edit.
If there is no selected text nothing happens.
See also
copy() paste()
Definition at line 1418 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->cut();
 }
document()
QTextDocument * QPlainTextEdit::document () const
Returns a pointer to the underlying document.
See also
setDocument()
Definition at line 1327 of file qplaintextedit.cpp.
Referenced by anchorAt(), QPlainTextEditPrivate::append(), blockBoundingRect(), event(), QScriptEdit::gotoLine(), keyPressEvent(), paintEvent(), QAccessiblePlainTextEdit::textDocument(), and QScriptEdit::updateExtraSelections().
 {
     Q_D(const QPlainTextEdit);
     return d->control->document();
 }
documentTitle()
QString QPlainTextEdit::documentTitle () const inline
Definition at line 120 of file qplaintextedit.h.
     { return document()->metaInformation(QTextDocument::DocumentTitle); }
dragEnterEvent()
void QPlainTextEdit::dragEnterEvent (QDragEnterEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2085 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->inDrag = true;
     d->sendControlEvent(e);
 }
dragLeaveEvent()
void QPlainTextEdit::dragLeaveEvent (QDragLeaveEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2094 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->inDrag = false;
     d->autoScrollTimer.stop();
     d->sendControlEvent(e);
 }
dragMoveEvent()
void QPlainTextEdit::dragMoveEvent (QDragMoveEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2104 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->autoScrollDragPos = e->pos();
     if (!d->autoScrollTimer.isActive())
         d->autoScrollTimer.start(100, this);
     d->sendControlEvent(e);
 }
dropEvent()
void QPlainTextEdit::dropEvent (QDropEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2115 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->inDrag = false;
     d->autoScrollTimer.stop();
     d->sendControlEvent(e);
 }
ensureCursorVisible()
void QPlainTextEdit::ensureCursorVisible ()
Ensures that the cursor is visible by scrolling the text edit if necessary.
See also
centerCursor(), centerOnScroll
Definition at line 2942 of file qplaintextedit.cpp.
Referenced by QPlainTextEditControl::ensureCursorVisible(), event(), inputMethodEvent(), setLineWrapMode(), and showEvent().
 {
     Q_D(QPlainTextEdit);
     d->ensureCursorVisible(d->centerOnScroll);
 }
event()
bool QPlainTextEdit::event (QEvent * e) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractScrollArea.
Definition at line 1486 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
 #ifndef QT_NO_CONTEXTMENU
     if (e->type() == QEvent::ContextMenu
         && static_cast<QContextMenuEvent *>(e)->reason() == QContextMenuEvent::Keyboard) {
         ensureCursorVisible();
         const QPoint cursorPos = cursorRect().center();
         QContextMenuEvent ce(QContextMenuEvent::Keyboard, cursorPos, d->viewport->mapToGlobal(cursorPos));
         ce.setAccepted(e->isAccepted());
         const bool result = QAbstractScrollArea::event(&ce);
         e->setAccepted(ce.isAccepted());
         return result;
     }
 #endif // QT_NO_CONTEXTMENU
     if (e->type() == QEvent::ShortcutOverride
                || e->type() == QEvent::ToolTip) {
         d->sendControlEvent(e);
     }
 #ifdef QT_KEYPAD_NAVIGATION
     else if (e->type() == QEvent::EnterEditFocus || e->type() == QEvent::LeaveEditFocus) {
         if (QApplication::keypadNavigationEnabled())
             d->sendControlEvent(e);
     }
 #endif
 #ifndef QT_NO_GESTURES
     else if (e->type() == QEvent::Gesture) {
         QGestureEvent *ge = static_cast<QGestureEvent *>(e);
         QPanGesture *g = static_cast<QPanGesture *>(ge->gesture(Qt::PanGesture));
         if (g) {
             QScrollBar *hBar = horizontalScrollBar();
             QScrollBar *vBar = verticalScrollBar();
             if (g->state() == Qt::GestureStarted)
                 d->originalOffsetY = vBar->value();
             QPointF offset = g->offset();
             if (!offset.isNull()) {
                 if (QApplication::isRightToLeft())
                     offset.rx() *= -1;
                 // QPlainTextEdit scrolls by lines only in vertical direction
                 QFontMetrics fm(document()->defaultFont());
                 int lineHeight = fm.height();
                 int newX = hBar->value() - g->delta().x();
                 int newY = d->originalOffsetY - offset.y()/lineHeight;
                 hBar->setValue(newX);
                 vBar->setValue(newY);
             }
         }
         return true;
     }
 #endif // QT_NO_GESTURES
     return QAbstractScrollArea::event(e);
 }
extraSelections()
QList< QTextEdit::ExtraSelection > QPlainTextEdit::extraSelections () const
Returns previously set extra selections.
See also
setExtraSelections()
Definition at line 2379 of file qplaintextedit.cpp.
Referenced by QScriptEdit::updateExtraSelections().
 {
     Q_D(const QPlainTextEdit);
     return d->control->extraSelections();
 }
find()
bool QPlainTextEdit::find (const QString & exp, QTextDocument::FindFlags options = 0)
Finds the next occurrence of the string, exp, using the given options.
Returns true if exp was found and changes the cursor to select the match; otherwise returns false.
Definition at line 2741 of file qplaintextedit.cpp.
Referenced by QScriptDebuggerCodeView::find().
 {
     Q_D(QPlainTextEdit);
     return d->control->find(exp, options);
 }
firstVisibleBlock()
QTextBlock QPlainTextEdit::firstVisibleBlock () const protected
Returns the first visible block.
See also
blockBoundingRect()
Definition at line 2964 of file qplaintextedit.cpp.
Referenced by QScriptEdit::extraAreaPaintEvent(), and paintEvent().
 {
     Q_D(const QPlainTextEdit);
     return d->control->firstVisibleBlock();
 }
focusInEvent()
void QPlainTextEdit::focusInEvent (QFocusEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2170 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     if (e->reason() == Qt::MouseFocusReason) {
         d->clickCausedFocus = 1;
     }
     QAbstractScrollArea::focusInEvent(e);
     d->sendControlEvent(e);
 }
focusNextPrevChild()
bool QPlainTextEdit::focusNextPrevChild (bool next) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2051 of file qplaintextedit.cpp.
 {
     Q_D(const QPlainTextEdit);
     if (!d->tabChangesFocus && d->control->textInteractionFlags() & Qt::TextEditable)
         return false;
     return QAbstractScrollArea::focusNextPrevChild(next);
 }
focusOutEvent()
void QPlainTextEdit::focusOutEvent (QFocusEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2182 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     QAbstractScrollArea::focusOutEvent(e);
     d->sendControlEvent(e);
 }
getPaintContext()
QAbstractTextDocumentLayout::PaintContext QPlainTextEdit::getPaintContext () const protected
Returns the paint context for the viewport(), useful only when reimplementing paintEvent().
Definition at line 3031 of file qplaintextedit.cpp.
Referenced by paintEvent().
 {
     Q_D(const QPlainTextEdit);
     return d->control->getPaintContext(d->viewport);
 }
inputMethodEvent()
void QPlainTextEdit::inputMethodEvent (QInputMethodEvent * e) protected virtual
Reimplemented Function
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 2127 of file qplaintextedit.cpp.
inputMethodQuery()
QVariant QPlainTextEdit::inputMethodQuery (Qt::InputMethodQuery query) const protected virtual
This method is only relevant for input widgets.
It is used by the input method to query a set of properties of the widget to be able to support complex input method operations as support for surrounding text and reconversions.
query specifies which property is queried.
See also
inputMethodEvent(), QInputMethodEvent, QInputContext, inputMethodHints
Reimplemented from QWidget.
Definition at line 2152 of file qplaintextedit.cpp.
 {
     Q_D(const QPlainTextEdit);
     QVariant v = d->control->inputMethodQuery(property);
     const QPoint offset(-d->horizontalOffset(), -0);
     if (v.type() == QVariant::RectF)
         v = v.toRectF().toRect().translated(offset);
     else if (v.type() == QVariant::PointF)
         v = v.toPointF().toPoint() + offset;
     else if (v.type() == QVariant::Rect)
         v = v.toRect().translated(offset);
     else if (v.type() == QVariant::Point)
         v = v.toPoint() + offset;
     return v;
 }
insertFromMimeData()
void QPlainTextEdit::insertFromMimeData (const QMimeData * source) protected virtual
This function inserts the contents of the MIME data object, specified by source, into the text edit at the current cursor position.
It is called whenever text is inserted as the result of a clipboard paste operation, or when the text edit accepts data from a drag and drop operation.
Definition at line 2420 of file qplaintextedit.cpp.
Referenced by QPlainTextEditControl::insertFromMimeData().
 {
     Q_D(QPlainTextEdit);
     d->control->QTextControl::insertFromMimeData(source);
 }
insertPlainText
void QPlainTextEdit::insertPlainText (const QString & text) slot
Convenience slot that inserts text at the current cursor position.
It is equivalent to
edit->textCursor().insertText(text);
Definition at line 2530 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->insertPlainText(text);
 }
isReadOnly()
bool QPlainTextEdit::isReadOnly () const
Definition at line 2439 of file qplaintextedit.cpp.
Referenced by mouseReleaseEvent(), paintEvent(), and shouldEnableInputMethod().
 {
     Q_D(const QPlainTextEdit);
     return !(d->control->textInteractionFlags() & Qt::TextEditable);
 }
isUndoRedoEnabled()
bool QPlainTextEdit::isUndoRedoEnabled () const inline
Definition at line 123 of file qplaintextedit.h.
     { return document()->isUndoRedoEnabled(); }
keyPressEvent()
void QPlainTextEdit::keyPressEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1616 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
 #ifdef QT_KEYPAD_NAVIGATION
     switch (e->key()) {
         case Qt::Key_Select:
             if (QApplication::keypadNavigationEnabled()) {
                 if (!(d->control->textInteractionFlags() & Qt::LinksAccessibleByKeyboard))
                     setEditFocus(!hasEditFocus());
                 else {
                     if (!hasEditFocus())
                         setEditFocus(true);
                     else {
                         QTextCursor cursor = d->control->textCursor();
                         QTextCharFormat charFmt = cursor.charFormat();
                         if (!cursor.hasSelection() || charFmt.anchorHref().isEmpty()) {
                             setEditFocus(false);
                         }
                     }
                 }
             }
             break;
         case Qt::Key_Back:
         case Qt::Key_No:
             if (!QApplication::keypadNavigationEnabled()
                     || (QApplication::keypadNavigationEnabled() && !hasEditFocus())) {
                 e->ignore();
                 return;
             }
             break;
         default:
             if (QApplication::keypadNavigationEnabled()) {
                 if (!hasEditFocus() && !(e->modifiers() & Qt::ControlModifier)) {
                     if (e->text()[0].isPrint()) {
                         setEditFocus(true);
                         clear();
                     } else {
                         e->ignore();
                         return;
                     }
                 }
             }
             break;
     }
 #endif
 #ifndef QT_NO_SHORTCUT
     Qt::TextInteractionFlags tif = d->control->textInteractionFlags();
     if (tif & Qt::TextSelectableByKeyboard){
         if (e == QKeySequence::SelectPreviousPage) {
             e->accept();
             d->pageUpDown(QTextCursor::Up, QTextCursor::KeepAnchor);
             return;
         } else if (e ==QKeySequence::SelectNextPage) {
             e->accept();
             d->pageUpDown(QTextCursor::Down, QTextCursor::KeepAnchor);
             return;
         }
     }
     if (tif & (Qt::TextSelectableByKeyboard | Qt::TextEditable)) {
         if (e == QKeySequence::MoveToPreviousPage) {
             e->accept();
             d->pageUpDown(QTextCursor::Up, QTextCursor::MoveAnchor);
             return;
         } else if (e == QKeySequence::MoveToNextPage) {
             e->accept();
             d->pageUpDown(QTextCursor::Down, QTextCursor::MoveAnchor);
             return;
         }
     }
     if (!(tif & Qt::TextEditable)) {
         switch (e->key()) {
             case Qt::Key_Space:
                 e->accept();
                 if (e->modifiers() & Qt::ShiftModifier)
                     d->vbar->triggerAction(QAbstractSlider::SliderPageStepSub);
                 else
                     d->vbar->triggerAction(QAbstractSlider::SliderPageStepAdd);
                 break;
             default:
                 d->sendControlEvent(e);
                 if (!e->isAccepted() && e->modifiers() == Qt::NoModifier) {
                     if (e->key() == Qt::Key_Home) {
                         d->vbar->triggerAction(QAbstractSlider::SliderToMinimum);
                         e->accept();
                     } else if (e->key() == Qt::Key_End) {
                         d->vbar->triggerAction(QAbstractSlider::SliderToMaximum);
                         e->accept();
                     }
                 }
                 if (!e->isAccepted()) {
                     QAbstractScrollArea::keyPressEvent(e);
                 }
         }
         return;
     }
 #endif // QT_NO_SHORTCUT
     d->sendControlEvent(e);
 #ifdef QT_KEYPAD_NAVIGATION
     if (!e->isAccepted()) {
         switch (e->key()) {
             case Qt::Key_Up:
             case Qt::Key_Down:
                 if (QApplication::keypadNavigationEnabled()) {
                     // Cursor position didn't change, so we want to leave
                     // these keys to change focus.
                     e->ignore();
                     return;
                 }
                 break;
             case Qt::Key_Left:
             case Qt::Key_Right:
                 if (QApplication::keypadNavigationEnabled()
                         && QApplication::navigationMode() == Qt::NavigationModeKeypadDirectional) {
                     // Same as for Key_Up and Key_Down.
                     e->ignore();
                     return;
                 }
                 break;
             case Qt::Key_Back:
                 if (!e->isAutoRepeat()) {
                     if (QApplication::keypadNavigationEnabled()) {
                         if (document()->isEmpty()) {
                             setEditFocus(false);
                             e->accept();
                         } else if (!d->deleteAllTimer.isActive()) {
                             e->accept();
                             d->deleteAllTimer.start(750, this);
                         }
                     } else {
                         e->ignore();
                         return;
                     }
                 }
                 break;
             default: break;
         }
     }
 #endif
 }
keyReleaseEvent()
void QPlainTextEdit::keyReleaseEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1764 of file qplaintextedit.cpp.
 {
 #ifdef QT_KEYPAD_NAVIGATION
     Q_D(QPlainTextEdit);
     if (QApplication::keypadNavigationEnabled()) {
         if (!e->isAutoRepeat() && e->key() == Qt::Key_Back
             && d->deleteAllTimer.isActive()) {
             d->deleteAllTimer.stop();
             QTextCursor cursor = d->control->textCursor();
             QTextBlockFormat blockFmt = cursor.blockFormat();
             QTextList *list = cursor.currentList();
             if (list && cursor.atBlockStart()) {
                 list->remove(cursor.block());
             } else if (cursor.atBlockStart() && blockFmt.indent() > 0) {
                 blockFmt.setIndent(blockFmt.indent() - 1);
                 cursor.setBlockFormat(blockFmt);
             } else {
                 cursor.deletePreviousChar();
             }
             setTextCursor(cursor);
         }
     }
 #else
     Q_UNUSED(e);
 #endif
 }
lineWrapMode()
LineWrapMode QPlainTextEdit::lineWrapMode () const
Referenced by setTabChangesFocus().
loadResource()
QVariant QPlainTextEdit::loadResource (int type, const QUrl & name) virtual
Loads the resource specified by the given type and name.
This function is an extension of QTextDocument::loadResource().
See also
QTextDocument::loadResource()
Definition at line 1799 of file qplaintextedit.cpp.
Referenced by QPlainTextEditControl::loadResource().
 {
     Q_UNUSED(type);
     Q_UNUSED(name);
     return QVariant();
 }
maximumBlockCount()
int QPlainTextEdit::maximumBlockCount () const inline
Definition at line 130 of file qplaintextedit.h.
Referenced by QPlainTextEditPrivate::append().
     { return document()->maximumBlockCount(); }
mergeCurrentCharFormat()
void QPlainTextEdit::mergeCurrentCharFormat (const QTextCharFormat & modifier)
Merges the properties specified in modifier into the current character format by calling QTextCursor::mergeCharFormat on the editor's cursor.
If the editor has a selection then the properties of modifier are directly applied to the selection.
See also
QTextCursor::mergeCharFormat()
Definition at line 2493 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->mergeCurrentCharFormat(modifier);
 }
modificationChanged
void QPlainTextEdit::modificationChanged (bool changed) signal
This signal is emitted whenever the content of the document changes in a way that affects the modification state.
If changed is true, the document has been modified; otherwise it is false.
For example, calling setModified(false) on a document and then inserting text causes the signal to get emitted. If you undo that operation, causing the document to return to its original unmodified state, the signal will get emitted again.
mouseDoubleClickEvent()
void QPlainTextEdit::mouseDoubleClickEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2043 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->sendControlEvent(e);
 }
mouseMoveEvent()
void QPlainTextEdit::mouseMoveEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2010 of file qplaintextedit.cpp.
Referenced by timerEvent().
 {
     Q_D(QPlainTextEdit);
     d->inDrag = false; // paranoia
     const QPoint pos = e->pos();
     d->sendControlEvent(e);
     if (!(e->buttons() & Qt::LeftButton))
         return;
     QRect visible = d->viewport->rect();
     if (visible.contains(pos))
         d->autoScrollTimer.stop();
     else if (!d->autoScrollTimer.isActive())
         d->autoScrollTimer.start(100, this);
 }
mousePressEvent()
void QPlainTextEdit::mousePressEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1998 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
 #ifdef QT_KEYPAD_NAVIGATION
     if (QApplication::keypadNavigationEnabled() && !hasEditFocus())
         setEditFocus(true);
 #endif
     d->sendControlEvent(e);
 }
mouseReleaseEvent()
void QPlainTextEdit::mouseReleaseEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2027 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->sendControlEvent(e);
     if (d->autoScrollTimer.isActive()) {
         d->autoScrollTimer.stop();
         d->ensureCursorVisible();
     }
     if (!isReadOnly() && rect().contains(e->pos()))
         d->handleSoftwareInputPanel(e->button(), d->clickCausedFocus);
     d->clickCausedFocus = 0;
 }
moveCursor()
void QPlainTextEdit::moveCursor (QTextCursor::MoveOperation operation, QTextCursor::MoveMode mode = QTextCursor::MoveAnchor)
Moves the cursor by performing the given operation.
If mode is QTextCursor::KeepAnchor, the cursor selects the text it moves over. This is the same effect that the user achieves when they hold down the Shift key and move the cursor with the cursor keys.
See also
QTextCursor::movePosition()
Definition at line 2546 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->moveCursor(operation, mode);
 }
overwriteMode()
bool QPlainTextEdit::overwriteMode () const
Referenced by cursorRect(), and paintEvent().
paintEvent()
void QPlainTextEdit::paintEvent (QPaintEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Reimplemented in QScriptEdit.
Definition at line 1854 of file qplaintextedit.cpp.
Referenced by QScriptEdit::paintEvent().
 {
     QPainter painter(viewport());
     Q_ASSERT(qobject_cast<QPlainTextDocumentLayout*>(document()->documentLayout()));
     QPointF offset(contentOffset());
     QRect er = e->rect();
     QRect viewportRect = viewport()->rect();
     bool editable = !isReadOnly();
     QTextBlock block = firstVisibleBlock();
     qreal maximumWidth = document()->documentLayout()->documentSize().width();
     // Set a brush origin so that the WaveUnderline knows where the wave started
     painter.setBrushOrigin(offset);
     // keep right margin clean from full-width selection
     int maxX = offset.x() + qMax((qreal)viewportRect.width(), maximumWidth)
                - document()->documentMargin();
     er.setRight(qMin(er.right(), maxX));
     painter.setClipRect(er);
     QAbstractTextDocumentLayout::PaintContext context = getPaintContext();
     while (block.isValid()) {
         QRectF r = blockBoundingRect(block).translated(offset);
         QTextLayout *layout = block.layout();
         if (!block.isVisible()) {
             offset.ry() += r.height();
             block = block.next();
             continue;
         }
         if (r.bottom() >= er.top() && r.top() <= er.bottom()) {
             QTextBlockFormat blockFormat = block.blockFormat();
             QBrush bg = blockFormat.background();
             if (bg != Qt::NoBrush) {
                 QRectF contentsRect = r;
                 contentsRect.setWidth(qMax(r.width(), maximumWidth));
                 fillBackground(&painter, contentsRect, bg);
             }
             QVector<QTextLayout::FormatRange> selections;
             int blpos = block.position();
             int bllen = block.length();
             for (int i = 0; i < context.selections.size(); ++i) {
                 const QAbstractTextDocumentLayout::Selection &range = context.selections.at(i);
                 const int selStart = range.cursor.selectionStart() - blpos;
                 const int selEnd = range.cursor.selectionEnd() - blpos;
                 if (selStart < bllen && selEnd > 0
                     && selEnd > selStart) {
                     QTextLayout::FormatRange o;
                     o.start = selStart;
                     o.length = selEnd - selStart;
                     o.format = range.format;
                     selections.append(o);
                 } else if (!range.cursor.hasSelection() && range.format.hasProperty(QTextFormat::FullWidthSelection)
                            && block.contains(range.cursor.position())) {
                     // for full width selections we don't require an actual selection, just
                     // a position to specify the line. that's more convenience in usage.
                     QTextLayout::FormatRange o;
                     QTextLine l = layout->lineForTextPosition(range.cursor.position() - blpos);
                     o.start = l.textStart();
                     o.length = l.textLength();
                     if (o.start + o.length == bllen - 1)
                         ++o.length; // include newline
                     o.format = range.format;
                     selections.append(o);
                 }
             }
             bool drawCursor = ((editable || (textInteractionFlags() & Qt::TextSelectableByKeyboard))
                                && context.cursorPosition >= blpos
                                && context.cursorPosition < blpos + bllen);
             bool drawCursorAsBlock = drawCursor && overwriteMode() ;
             if (drawCursorAsBlock) {
                 if (context.cursorPosition == blpos + bllen - 1) {
                     drawCursorAsBlock = false;
                 } else {
                     QTextLayout::FormatRange o;
                     o.start = context.cursorPosition - blpos;
                     o.length = 1;
                     o.format.setForeground(palette().base());
                     o.format.setBackground(palette().text());
                     selections.append(o);
                 }
             }
             layout->draw(&painter, offset, selections, er);
             if ((drawCursor && !drawCursorAsBlock)
                 || (editable && context.cursorPosition < -1
                     && !layout->preeditAreaText().isEmpty())) {
                 int cpos = context.cursorPosition;
                 if (cpos < -1)
                     cpos = layout->preeditAreaPosition() - (cpos + 2);
                 else
                     cpos -= blpos;
                 layout->drawCursor(&painter, offset, cpos, cursorWidth());
             }
         }
         offset.ry() += r.height();
         if (offset.y() > viewportRect.height())
             break;
         block = block.next();
     }
     if (backgroundVisible() && !block.isValid() && offset.y() <= er.bottom()
         && (centerOnScroll() || verticalScrollBar()->maximum() == verticalScrollBar()->minimum())) {
         painter.fillRect(QRect(QPoint((int)er.left(), (int)offset.y()), er.bottomRight()), palette().background());
     }
 }
paste
void QPlainTextEdit::paste () slot
Pastes the text from the clipboard into the text edit at the current cursor position.
If there is no text in the clipboard nothing happens.
To change the behavior of this function, i.e. to modify what QPlainTextEdit can paste and how it is being pasted, reimplement the virtual canInsertFromMimeData() and insertFromMimeData() functions.
See also
cut() copy()
Definition at line 1450 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->paste();
 }
print()
void QPlainTextEdit::print (QPrinter * printer) const
Convenience function to print the text edit's document to the given printer.
This is equivalent to calling the print method on the document directly except that this function also supports QPrinter::Selection as print range.
See also
QTextDocument::print()
Definition at line 2569 of file qplaintextedit.cpp.
 {
     Q_D(const QPlainTextEdit);
     d->control->print(printer);
 }
redo
void QPlainTextEdit::redo () slot
Redoes the last operation.
If there is no operation to redo, i.e. there is no redo step in the undo/redo history, nothing happens.
See also
undo()
Definition at line 1388 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->redo();
 }
redoAvailable
void QPlainTextEdit::redoAvailable (bool b) signal
This signal is emitted whenever redo operations become available (available is true) or unavailable (available is false).
resizeEvent()
void QPlainTextEdit::resizeEvent (QResizeEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Reimplemented in QScriptEdit.
Definition at line 1808 of file qplaintextedit.cpp.
Referenced by QScriptEdit::resizeEvent().
 {
     Q_D(QPlainTextEdit);
     if (e->oldSize().width() != e->size().width())
         d->relayoutDocument();
     d->_q_adjustScrollbars();
 }
scrollContentsBy()
void QPlainTextEdit::scrollContentsBy (int dx, int dy) protected virtual
em>Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2144 of file qplaintextedit.cpp.
selectAll
void QPlainTextEdit::selectAll () slot
Selects all text.
See also
copy() cut() textCursor()
Definition at line 1478 of file qplaintextedit.cpp.
Referenced by inputMethodEvent().
 {
     Q_D(QPlainTextEdit);
     d->control->selectAll();
 }
selectionChanged
void QPlainTextEdit::selectionChanged () signal
This signal is emitted whenever the selection changes.
See also
copyAvailable()
setBackgroundVisible()
void QPlainTextEdit::setBackgroundVisible (bool visible)
Definition at line 2691 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     if (visible == d->backgroundVisible)
         return;
     d->backgroundVisible = visible;
     d->updateViewport();
 }
setCenterOnScroll()
void QPlainTextEdit::setCenterOnScroll (bool enabled)
Definition at line 2726 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     if (enabled == d->centerOnScroll)
         return;
     d->centerOnScroll = enabled;
 }
setCurrentCharFormat()
void QPlainTextEdit::setCurrentCharFormat (const QTextCharFormat & format)
Sets the char format that is be used when inserting new text to format by calling QTextCursor::setCharFormat() on the editor's cursor.
If the editor has a selection then the char format is directly applied to the selection.
Definition at line 2505 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->setCurrentCharFormat(format);
 }
setCursorWidth()
void QPlainTextEdit::setCursorWidth (int width)
Definition at line 2352 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->setCursorWidth(width);
 }
setDocument()
void QPlainTextEdit::setDocument (QTextDocument * document)
Makes document the new document of the text editor.
The parent QObject of the provided document remains the owner of the object. If the current document is a child of the text editor, then it is deleted.
The document must have a document layout that inherits QPlainTextDocumentLayout (see QTextDocument::setDocumentLayout()).
See also
document()
Definition at line 1297 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     QPlainTextDocumentLayout *documentLayout = 0;
     if (!document) {
         document = new QTextDocument(d->control);
         documentLayout = new QPlainTextDocumentLayout(document);
         document->setDocumentLayout(documentLayout);
     } else {
         documentLayout = qobject_cast<QPlainTextDocumentLayout*>(document->documentLayout());
         if (!documentLayout) {
             qWarning("QPlainTextEdit::setDocument: Document set does not support QPlainTextDocumentLayout");
             return;
         }
     }
     d->control->setDocument(document);
     if (!documentLayout->priv()->mainViewPrivate)
         documentLayout->priv()->mainViewPrivate = d;
     d->documentLayoutPtr = documentLayout;
     d->updateDefaultTextOption();
     d->relayoutDocument();
     d->_q_adjustScrollbars();
 }
setDocumentTitle()
void QPlainTextEdit::setDocumentTitle (const QString & title) inline
Definition at line 118 of file qplaintextedit.h.
     { document()->setMetaInformation(QTextDocument::DocumentTitle, title); }
setExtraSelections()
void QPlainTextEdit::setExtraSelections (const QList< QTextEdit::ExtraSelection > & selections)
This function allows temporarily marking certain regions in the document with a given color, specified as selections.
This can be useful for example in a programming editor to mark a whole line of text with a given background color to indicate the existence of a breakpoint.
See also
QTextEdit::ExtraSelection, extraSelections()
Definition at line 2368 of file qplaintextedit.cpp.
Referenced by QScriptEdit::updateExtraSelections().
 {
     Q_D(QPlainTextEdit);
     d->control->setExtraSelections(selections);
 }
setLineWrapMode()
void QPlainTextEdit::setLineWrapMode (LineWrapMode mode)
Definition at line 2629 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     if (d->lineWrap == wrap)
         return;
     d->lineWrap = wrap;
     d->updateDefaultTextOption();
     d->relayoutDocument();
     d->_q_adjustScrollbars();
     ensureCursorVisible();
 }
setMaximumBlockCount()
void QPlainTextEdit::setMaximumBlockCount (int maximum) inline
Definition at line 128 of file qplaintextedit.h.
     { document()->setMaximumBlockCount(maximum); }
setOverwriteMode()
void QPlainTextEdit::setOverwriteMode (bool overwrite)
Definition at line 2306 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->setOverwriteMode(overwrite);
 }
setPlainText
void QPlainTextEdit::setPlainText (const QString & text) slot
Changes the text of the text edit to the string text.
Any previous text is removed.
text is interpreted as plain text.
Note that the undo/redo history is cleared by this function.
See also
toText()
Definition at line 1597 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->setPlainText(text);
 }
setReadOnly()
void QPlainTextEdit::setReadOnly (bool ro)
Definition at line 2445 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     Qt::TextInteractionFlags flags = Qt::NoTextInteraction;
     if (ro) {
         flags = Qt::TextSelectableByMouse;
     } else {
         flags = Qt::TextEditorInteraction;
     }
     setAttribute(Qt::WA_InputMethodEnabled, shouldEnableInputMethod(this));
     d->control->setTextInteractionFlags(flags);
 }
setTabChangesFocus()
void QPlainTextEdit::setTabChangesFocus (bool b)
Definition at line 2594 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->tabChangesFocus = b;
 }
setTabStopWidth()
void QPlainTextEdit::setTabStopWidth (int width)
Definition at line 2328 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     QTextOption opt = d->control->document()->defaultTextOption();
     if (opt.tabStop() == width || width < 0)
         return;
     opt.setTabStop(width);
     d->control->document()->setDefaultTextOption(opt);
 }
setTextCursor()
void QPlainTextEdit::setTextCursor (const QTextCursor & cursor)
Sets the visible cursor.
Definition at line 1336 of file qplaintextedit.cpp.
Referenced by QScriptDebuggerCodeView::find(), QScriptEdit::gotoLine(), keyReleaseEvent(), and QAccessiblePlainTextEdit::setTextCursor().
 {
     Q_D(QPlainTextEdit);
     d->control->setTextCursor(cursor);
 }
setTextInteractionFlags()
void QPlainTextEdit::setTextInteractionFlags (Qt::TextInteractionFlags flags)
Definition at line 2473 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->setTextInteractionFlags(flags);
 }
setUndoRedoEnabled()
void QPlainTextEdit::setUndoRedoEnabled (bool enable) inline
Definition at line 125 of file qplaintextedit.h.
     { document()->setUndoRedoEnabled(enable); }
setWordWrapMode()
void QPlainTextEdit::setWordWrapMode (QTextOption::WrapMode policy)
Definition at line 2659 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     if (mode == d->wordWrap)
         return;
     d->wordWrap = mode;
     d->updateDefaultTextOption();
 }
showEvent()
void QPlainTextEdit::showEvent (QShowEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2191 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     if (d->showCursorOnInitialShow) {
         d->showCursorOnInitialShow = false;
         ensureCursorVisible();
     }
 }
tabChangesFocus()
bool QPlainTextEdit::tabChangesFocus () const
Referenced by print().
tabStopWidth()
int QPlainTextEdit::tabStopWidth () const
Referenced by setOverwriteMode().
textChanged
void QPlainTextEdit::textChanged () signal
This signal is emitted whenever the document's content changes; for example, when text is inserted or deleted, or when formatting is applied.
textCursor()
QTextCursor QPlainTextEdit::textCursor () const
Returns a copy of the QTextCursor that represents the currently visible cursor.
Note that changes on the returned cursor do not affect QPlainTextEdit's cursor; use setTextCursor() to update the visible cursor.
Definition at line 1347 of file qplaintextedit.cpp.
Referenced by centerCursor(), QScriptEdit::currentLineNumber(), QScriptDebuggerCodeView::find(), QAccessiblePlainTextEdit::textCursor(), and QScriptEdit::updateExtraSelections().
 {
     Q_D(const QPlainTextEdit);
     return d->control->textCursor();
 }
textInteractionFlags()
Qt::TextInteractionFlags QPlainTextEdit::textInteractionFlags () const
Referenced by paintEvent(), and setTextInteractionFlags().
timerEvent()
void QPlainTextEdit::timerEvent (QTimerEvent * e) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QObject.
Definition at line 1543 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     if (e->timerId() == d->autoScrollTimer.timerId()) {
         QRect visible = d->viewport->rect();
         QPoint pos;
         if (d->inDrag) {
             pos = d->autoScrollDragPos;
             visible.adjust(qMin(visible.width()/3,20), qMin(visible.height()/3,20),
                            -qMin(visible.width()/3,20), -qMin(visible.height()/3,20));
         } else {
             const QPoint globalPos = QCursor::pos();
             pos = d->viewport->mapFromGlobal(globalPos);
             QMouseEvent ev(QEvent::MouseMove, pos, globalPos, Qt::LeftButton, Qt::LeftButton, Qt::NoModifier);
             mouseMoveEvent(&ev);
         }
         int deltaY = qMax(pos.y() - visible.top(), visible.bottom() - pos.y()) - visible.height();
         int deltaX = qMax(pos.x() - visible.left(), visible.right() - pos.x()) - visible.width();
         int delta = qMax(deltaX, deltaY);
         if (delta >= 0) {
             if (delta < 7)
                 delta = 7;
             int timeout = 4900 / (delta * delta);
             d->autoScrollTimer.start(timeout, this);
             if (deltaY > 0)
                 d->vbar->triggerAction(pos.y() < visible.center().y() ?
                                        QAbstractSlider::SliderSingleStepSub
                                        : QAbstractSlider::SliderSingleStepAdd);
             if (deltaX > 0)
                 d->hbar->triggerAction(pos.x() < visible.center().x() ?
                                        QAbstractSlider::SliderSingleStepSub
                                        : QAbstractSlider::SliderSingleStepAdd);
         }
     }
 #ifdef QT_KEYPAD_NAVIGATION
     else if (e->timerId() == d->deleteAllTimer.timerId()) {
         d->deleteAllTimer.stop();
         clear();
     }
 #endif
 }
toPlainText()
QString QPlainTextEdit::toPlainText () const inline
Returns the text of the text edit as plain text.
See also
QPlainTextEdit::setPlainText()
Definition at line 148 of file qplaintextedit.h.
     { return document()->toPlainText(); }
undo
void QPlainTextEdit::undo () slot
Undoes the last operation.
If there is no operation to undo, i.e. there is no undo step in the undo/redo history, nothing happens.
See also
redo()
Definition at line 1382 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextEdit);
     d->control->undo();
 }
undoAvailable
void QPlainTextEdit::undoAvailable (bool b) signal
This signal is emitted whenever undo operations become available (available is true) or unavailable (available is false).
updateRequest
void QPlainTextEdit::updateRequest (const QRect & rect, int dy) signal
This signal is emitted when the text document needs an update of the specified rect.
If the text is scrolled, rect will cover the entire viewport area. If the text is scrolled vertically, dy carries the amount of pixels the viewport was scrolled.
The purpose of the signal is to support extra widgets in plain text edit subclasses that e.g. show line numbers, breakpoints, or other extra information.
Referenced by QScriptEdit::QScriptEdit().
wheelEvent()
void QPlainTextEdit::wheelEvent (QWheelEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2225 of file qplaintextedit.cpp.
 {
     QAbstractScrollArea::wheelEvent(e);
     updateMicroFocus();
 }
wordWrapMode()
QTextOption::WrapMode QPlainTextEdit::wordWrapMode () const
the mode QPlainTextEdit will use when wrapping text by words
By default, this property is set to QTextOption::WrapAtWordBoundaryOrAnywhere.
See also
QTextOption::WrapMode
Definition at line 2653 of file qplaintextedit.cpp.
 {
     Q_D(const QPlainTextEdit);
     return d->wordWrap;
 }
Friends and Related Functions
QPlainTextEditControl
friend class QPlainTextEditControl friend
Definition at line 275 of file qplaintextedit.h.
Properties
backgroundVisible
bool QPlainTextEdit::backgroundVisible private
whether the palette background is visible outside the document area
If set to true, the plain text edit paints the palette background on the viewport area not covered by the text document. Otherwise, if set to false, it won't. The feature makes it possible for the user to visually distinguish between the area of the document, painted with the base color of the palette, and the empty area not covered by any document.
The default is false.
Definition at line 87 of file qplaintextedit.h.
blockCount
int QPlainTextEdit::blockCount private
the number of text blocks in the document.
By default, in an empty document, this property contains a value of 1.
Definition at line 85 of file qplaintextedit.h.
centerOnScroll
bool QPlainTextEdit::centerOnScroll private
whether the cursor should be centered on screen
If set to true, the plain text edit scrolls the document vertically to make the cursor visible at the center of the viewport. This also allows the text edit to scroll below the end of the document. Otherwise, if set to false, the plain text edit scrolls the smallest amount possible to ensure the cursor is visible. The same algorithm is applied to any new line appended through appendPlainText().
The default is false.
See also
centerCursor(), ensureCursorVisible()
Definition at line 88 of file qplaintextedit.h.
cursorWidth
int QPlainTextEdit::cursorWidth private
This property specifies the width of the cursor in pixels.
The default value is 1.
Definition at line 83 of file qplaintextedit.h.
documentTitle
QPlainTextEdit::documentTitle private
the title of the document parsed from the text.
By default, this property contains an empty string.
Definition at line 75 of file qplaintextedit.h.
lineWrapMode
QPlainTextEdit::LineWrapMode QPlainTextEdit::lineWrapMode private
the line wrap mode
The default mode is WidgetWidth which causes words to be wrapped at the right edge of the text edit. Wrapping occurs at whitespace, keeping whole words intact. If you want wrapping to occur within words use setWordWrapMode().
Definition at line 77 of file qplaintextedit.h.
maximumBlockCount
QPlainTextEdit::maximumBlockCount private
the limit for blocks in the document.
Specifies the maximum number of blocks the document may have. If there are more blocks in the document that specified with this property blocks are removed from the beginning of the document.
A negative or zero value specifies that the document may contain an unlimited amount of blocks.
The default value is 0.
Note that setting this property will apply the limit immediately to the document contents. Setting this property also disables the undo redo history.
Definition at line 86 of file qplaintextedit.h.
overwriteMode
bool QPlainTextEdit::overwriteMode private
whether text entered by the user will overwrite existing text
As with many text editors, the plain text editor widget can be configured to insert or overwrite existing text with new text entered by the user.
If this property is true, existing text is overwritten, character-for-character by new text; otherwise, text is inserted at the cursor position, displacing existing text.
By default, this property is false (new text does not overwrite existing text).
Definition at line 81 of file qplaintextedit.h.
plainText
QPlainTextEdit::plainText private
This property gets and sets the plain text editor's contents.
The previous contents are removed and undo/redo history is reset when this property is set.
By default, for an editor with no contents, this property contains an empty string.
Definition at line 80 of file qplaintextedit.h.
readOnly
QPlainTextEdit::readOnly private
whether the text edit is read-only
In a read-only text edit the user can only navigate through the text and select text; modifying the text is not possible.
This property's default is false.
Definition at line 79 of file qplaintextedit.h.
tabChangesFocus
bool QPlainTextEdit::tabChangesFocus private
whether Tab changes focus or is accepted as input
In some occasions text edits should not allow the user to input tabulators or change indentation using the Tab key, as this breaks the focus chain. The default is false.
Definition at line 74 of file qplaintextedit.h.
tabStopWidth
int QPlainTextEdit::tabStopWidth private
the tab stop width in pixels
By default, this property contains a value of 80.
Definition at line 82 of file qplaintextedit.h.
textInteractionFlags
Qt::TextInteractionFlags QPlainTextEdit::textInteractionFlags private
Specifies how the label should interact with user input if it displays text.
If the flags contain either Qt::LinksAccessibleByKeyboard or Qt::TextSelectableByKeyboard then the focus policy is also automatically set to Qt::ClickFocus.
The default value depends on whether the QPlainTextEdit is read-only or editable.
Definition at line 84 of file qplaintextedit.h.
undoRedoEnabled
QPlainTextEdit::undoRedoEnabled private
whether undo and redo are enabled
Users are only able to undo or redo actions if this property is true, and if there is an action that can be undone (or redone).
By default, this property is true.
Definition at line 76 of file qplaintextedit.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qplaintextedit.h
/src/gui/widgets/qplaintextedit.cpp