Qt 4.8: QDeclarativeObjectScriptClass Class Reference
QDeclarativeObjectScriptClass Class Reference
#include <qdeclarativeobjectscriptclass_p.h>
Public Types
enum QueryHint { ImplicitObject = 0x01, SkipAttachedProperties = 0x02 }
Public Types inherited from QScriptDeclarativeClass
typedef void * Identifier
Public Functions
virtual bool compare (Object *, Object *)
QScriptValue newQObject (QObject *, int type=QMetaType::QObjectStar)
int objectType (const QScriptValue &) const
Value property (QObject *, const Identifier &)
virtual QStringList propertyNames (Object *)
QDeclarativeObjectScriptClass (QDeclarativeEngine *)
QScriptClass::QueryFlags queryProperty (QObject *, const Identifier &, QScriptClass::QueryFlags flags, QDeclarativeContextData *evalContext, QueryHints hints=0)
void setProperty (QObject *, const Identifier &name, const QScriptValue &, QScriptContext *context, QDeclarativeContextData *evalContext=0)
QObject * toQObject (const QScriptValue &) const
~QDeclarativeObjectScriptClass ()
Public Functions inherited from QScriptDeclarativeClass
virtual Value call (Object *, QScriptContext *)
QScriptContext * context () const
PersistentIdentifier createPersistentIdentifier (const QString &)
PersistentIdentifier createPersistentIdentifier (const Identifier &)
QScriptEngine * engine () const
virtual QScriptValue::PropertyFlags propertyFlags (Object *, const Identifier &)
QScriptDeclarativeClass (QScriptEngine *engine)
void setSupportsCall (bool)
bool startsWithUpper (const Identifier &)
bool supportsCall () const
quint32 toArrayIndex (const Identifier &, bool *ok)
QString toString (const Identifier &)
virtual QVariant toVariant (Object *, bool *ok=0)
virtual ~QScriptDeclarativeClass ()
Protected Functions
virtual bool isQObject () const
virtual Value property (Object *, const Identifier &)
virtual QScriptClass::QueryFlags queryProperty (Object *, const Identifier &, QScriptClass::QueryFlags flags)
virtual void setProperty (Object *, const Identifier &name, const QScriptValue &)
virtual QObject * toQObject (Object *, bool *ok=0)
Static Private Functions
static QScriptValue destroy (QScriptContext *context, QScriptEngine *engine)
static QScriptValue tostring (QScriptContext *context, QScriptEngine *engine)
Properties
QDeclarativeEngine * engine
QDeclarativePropertyCache::Data * lastData
QDeclarativeTypeNameCache::Data * lastTNData
QDeclarativePropertyCache::Data local
QScriptValue m_destroy
PersistentIdentifier m_destroyId
QScriptValue m_toString
PersistentIdentifier m_toStringId
QDeclarativeObjectMethodScriptClass methods
Friends
class QDeclarativeObjectMethodScriptClass
Additional Inherited Members
Static Public Functions inherited from QScriptDeclarativeClass
static QScriptValue function (const QScriptValue &, const Identifier &)
static Value functionValue (const QScriptValue &, const Identifier &)
static QScriptValue newObject (QScriptEngine *, QScriptDeclarativeClass *, Object *)
static Value newObjectValue (QScriptEngine *, QScriptDeclarativeClass *, Object *)
static QScriptValue newStaticScopeObject (QScriptEngine *, int propertyCount, const QString *names, const QScriptValue *values, const QScriptValue::PropertyFlags *flags)
Creates a scope object with a fixed set of undeletable properties.
static QScriptValue newStaticScopeObject (QScriptEngine *)
Creates a static scope object that's initially empty, but to which new properties can be added.
static Object * object (const QScriptValue &)
static QScriptValue property (const QScriptValue &, const Identifier &)
static Value propertyValue (const QScriptValue &, const Identifier &)
static QScriptContext * pushCleanContext (QScriptEngine *)
Enters a new execution context and returns the associated QScriptContext object.
static QScriptValue scopeChainValue (QScriptContext *, int index)
static QScriptDeclarativeClass * scriptClass (const QScriptValue &)
Protected Variables inherited from QScriptDeclarativeClass
QScopedPointer< QScriptDeclarativeClassPrivate > d_ptr
Detailed Description
Definition at line 105 of file qdeclarativeobjectscriptclass_p.h.
Enumerations
QueryHint
enum QDeclarativeObjectScriptClass::QueryHint
Enumerator
ImplicitObject
SkipAttachedProperties
Definition at line 116 of file qdeclarativeobjectscriptclass_p.h.
                    {
         ImplicitObject = 0x01,
         SkipAttachedProperties = 0x02
     };
Constructors and Destructors
QDeclarativeObjectScriptClass()
QDeclarativeObjectScriptClass::QDeclarativeObjectScriptClass (QDeclarativeEngine * bindEngine)
Definition at line 94 of file qdeclarativeobjectscriptclass.cpp.
 : QScriptDeclarativeClass(QDeclarativeEnginePrivate::getScriptEngine(bindEngine)),
   methods(bindEngine), lastData(0), engine(bindEngine)
 {
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     m_destroy = scriptEngine->newFunction(destroy);
     m_destroyId = createPersistentIdentifier(QLatin1String("destroy"));
     m_toString = scriptEngine->newFunction(tostring);
     m_toStringId = createPersistentIdentifier(QLatin1String("toString"));
 }
~QDeclarativeObjectScriptClass()
QDeclarativeObjectScriptClass::~QDeclarativeObjectScriptClass ()
Definition at line 106 of file qdeclarativeobjectscriptclass.cpp.
 {
 }
Functions
compare()
bool QDeclarativeObjectScriptClass::compare (Object * o1, Object * o2) virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 556 of file qdeclarativeobjectscriptclass.cpp.
 {
     ObjectData *d1 = (ObjectData *)o1;
     ObjectData *d2 = (ObjectData *)o2;
     return d1 == d2 || d1->object == d2->object;
 }
destroy()
QScriptValue QDeclarativeObjectScriptClass::destroy (QScriptContext * context, QScriptEngine * engine) static private
Definition at line 496 of file qdeclarativeobjectscriptclass.cpp.
Referenced by QDeclarativeObjectScriptClass().
 {
     QDeclarativeEnginePrivate *p = QDeclarativeEnginePrivate::get(engine);
     QScriptValue that = context->thisObject();
     if (scriptClass(that) != p->objectClass)
         return engine->undefinedValue();
     ObjectData *data = (ObjectData *)p->objectClass->object(that);
     if (!data->object)
         return engine->undefinedValue();
     QDeclarativeData *ddata = QDeclarativeData::get(data->object, false);
     if (!ddata || ddata->indestructible)
         return engine->currentContext()->throwError(QLatin1String("Invalid attempt to destroy() an indestructible object"));
     QObject *obj = data->object;
     int delay = 0;
     if (context->argumentCount() > 0)
         delay = context->argument(0).toInt32();
     if (delay > 0)
         QTimer::singleShot(delay, obj, SLOT(deleteLater()));
     else
         obj->deleteLater();
     return engine->undefinedValue();
 }
isQObject()
bool QDeclarativeObjectScriptClass::isQObject () const protected virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 458 of file qdeclarativeobjectscriptclass.cpp.
 {
     return true;
 }
newQObject()
QScriptValue QDeclarativeObjectScriptClass::newQObject (QObject * object, int type = QMetaType::QObjectStar)
Definition at line 110 of file qdeclarativeobjectscriptclass.cpp.
Referenced by QDeclarativeEnginePrivate::createComponent(), QDeclarativeComponentPrivate::createObject(), QDeclarativeEnginePrivate::createQmlObject(), QDeclarativeQtScriptExpression::eval(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeListScriptClass::property(), QDeclarativeObjectMethodScriptClass::property(), QDeclarativeContextScriptClass::property(), property(), QDeclarativeEnginePrivate::qmlScriptObject(), and QDeclarativeVMEMetaObject::readVarProperty().
 {
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     if (!object)
         return scriptEngine->nullValue();
 //        return newObject(scriptEngine, this, new ObjectData(object, type));
     if (QObjectPrivate::get(object)->wasDeleted)
        return scriptEngine->undefinedValue();
     QDeclarativeData *ddata = QDeclarativeData::get(object, true);
     if (!ddata) {
        return scriptEngine->undefinedValue();
     } else if (!ddata->indestructible && !object->parent()) {
         return newObject(scriptEngine, this, new ObjectData(object, type));
     } else if (!ddata->scriptValue) {
         ddata->scriptValue = new QScriptValue(newObject(scriptEngine, this, new ObjectData(object, type)));
         return *ddata->scriptValue;
     } else if (ddata->scriptValue->engine() == QDeclarativeEnginePrivate::getScriptEngine(engine)) {
         return *ddata->scriptValue;
     } else {
         return newObject(scriptEngine, this, new ObjectData(object, type));
     }
 }
objectType()
int QDeclarativeObjectScriptClass::objectType (const QScriptValue & value) const
Definition at line 142 of file qdeclarativeobjectscriptclass.cpp.
Referenced by QDeclarativeBinding::update().
 {
     if (scriptClass(value) != this)
         return QVariant::Invalid;
     Object *o = object(value);
     return ((ObjectData*)(o))->type;
 }
property() [1/2]
QDeclarativeObjectScriptClass::Value QDeclarativeObjectScriptClass::property (QObject * obj, const Identifier & name)
Definition at line 222 of file qdeclarativeobjectscriptclass.cpp.
Referenced by QDeclarativeTypeNameScriptClass::property(), QDeclarativeContextScriptClass::property(), and property().
 {
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     if (name == m_destroyId.identifier)
         return Value(scriptEngine, m_destroy);
     else if (name == m_toStringId.identifier)
         return Value(scriptEngine, m_toString);
     if (lastData && !lastData->isValid())
         return Value();
     Q_ASSERT(obj);
     QDeclarativeEnginePrivate *enginePriv = QDeclarativeEnginePrivate::get(engine);
     if (lastTNData) {
         if (lastTNData->type)
             return Value(scriptEngine, enginePriv->typeNameClass->newObject(obj, lastTNData->type));
         else
             return Value(scriptEngine, enginePriv->typeNameClass->newObject(obj, lastTNData->typeNamespace));
     } else if (lastData->flags & QDeclarativePropertyCache::Data::IsFunction) {
         if (lastData->flags & QDeclarativePropertyCache::Data::IsVMEFunction) {
             return Value(scriptEngine, ((QDeclarativeVMEMetaObject *)(obj->metaObject()))->vmeMethod(lastData->coreIndex));
         } else {
             // Uncomment to use QtScript method call logic
             // QScriptValue sobj = scriptEngine->newQObject(obj);
             // return Value(scriptEngine, sobj.property(toString(name)));
             return Value(scriptEngine, methods.newMethod(obj, lastData));
         }
     } else {
         if (enginePriv->captureProperties && !(lastData->flags & QDeclarativePropertyCache::Data::IsConstant)) {
             if (lastData->coreIndex == 0) {
                 enginePriv->capturedProperties <<
                     QDeclarativeEnginePrivate::CapturedProperty(QDeclarativeData::get(obj, true)->objectNameNotifier());
             } else {
                 enginePriv->capturedProperties <<
                     QDeclarativeEnginePrivate::CapturedProperty(obj, lastData->coreIndex, lastData->notifyIndex);
             }
         }
         if (QDeclarativeValueTypeFactory::isValueType((uint)lastData->propType)) {
             QDeclarativeValueType *valueType = enginePriv->valueTypes[lastData->propType];
             if (valueType)
                 return Value(scriptEngine, enginePriv->valueTypeClass->newObject(obj, lastData->coreIndex, valueType));
         }
         if (lastData->flags & QDeclarativePropertyCache::Data::IsQList) {
             return Value(scriptEngine, enginePriv->listClass->newList(obj, lastData->coreIndex, lastData->propType));
         } else if (lastData->flags & QDeclarativePropertyCache::Data::IsQObjectDerived) {
             QObject *rv = 0;
             void *args[] = { &rv, 0 };
             QMetaObject::metacall(obj, QMetaObject::ReadProperty, lastData->coreIndex, args);
             return Value(scriptEngine, newQObject(rv, lastData->propType));
         } else if (lastData->flags & QDeclarativePropertyCache::Data::IsQScriptValue) {
             QScriptValue rv = scriptEngine->nullValue();
             void *args[] = { &rv, 0 };
             QMetaObject::metacall(obj, QMetaObject::ReadProperty, lastData->coreIndex, args);
             return Value(scriptEngine, rv);
         } else if (lastData->propType == QMetaType::QReal) {
             qreal rv = 0;
             void *args[] = { &rv, 0 };
             QMetaObject::metacall(obj, QMetaObject::ReadProperty, lastData->coreIndex, args);
             return Value(scriptEngine, rv);
         } else if (lastData->propType == QMetaType::Int || lastData->flags & QDeclarativePropertyCache::Data::IsEnumType) {
             int rv = 0;
             void *args[] = { &rv, 0 };
             QMetaObject::metacall(obj, QMetaObject::ReadProperty, lastData->coreIndex, args);
             return Value(scriptEngine, rv);
         } else if (lastData->propType == QMetaType::Bool) {
             bool rv = false;
             void *args[] = { &rv, 0 };
             QMetaObject::metacall(obj, QMetaObject::ReadProperty, lastData->coreIndex, args);
             return Value(scriptEngine, rv);
         } else if (lastData->propType == QMetaType::QString) {
             QString rv;
             void *args[] = { &rv, 0 };
             QMetaObject::metacall(obj, QMetaObject::ReadProperty, lastData->coreIndex, args);
             return Value(scriptEngine, rv);
         } else if (lastData->propType == QMetaType::UInt) {
             uint rv = 0;
             void *args[] = { &rv, 0 };
             QMetaObject::metacall(obj, QMetaObject::ReadProperty, lastData->coreIndex, args);
             return Value(scriptEngine, rv);
         } else if (lastData->propType == QMetaType::Float) {
             float rv = 0;
             void *args[] = { &rv, 0 };
             QMetaObject::metacall(obj, QMetaObject::ReadProperty, lastData->coreIndex, args);
             return Value(scriptEngine, rv);
         } else if (lastData->propType == QMetaType::Double) {
             double rv = 0;
             void *args[] = { &rv, 0 };
             QMetaObject::metacall(obj, QMetaObject::ReadProperty, lastData->coreIndex, args);
             return Value(scriptEngine, rv);
         } else {
             QVariant var = obj->metaObject()->property(lastData->coreIndex).read(obj);
             return Value(scriptEngine, enginePriv->scriptValueFromVariant(var));
         }
     }
 }
property() [2/2]
QDeclarativeObjectScriptClass::Value QDeclarativeObjectScriptClass::property (Object * object, const Identifier & name) protected virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 216 of file qdeclarativeobjectscriptclass.cpp.
 {
     return property(toQObject(object), name);
 }
propertyNames()
QStringList QDeclarativeObjectScriptClass::propertyNames (Object * object) virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 524 of file qdeclarativeobjectscriptclass.cpp.
 {
     QObject *obj = toQObject(object);
     if (!obj)
         return QStringList();
     QDeclarativeEnginePrivate *enginePrivate = QDeclarativeEnginePrivate::get(engine);
     QDeclarativePropertyCache *cache = 0;
     QDeclarativeData *ddata = QDeclarativeData::get(obj);
     if (ddata)
         cache = ddata->propertyCache;
     if (!cache) {
         cache = enginePrivate->cache(obj);
         if (cache) {
             if (ddata) { cache->addref(); ddata->propertyCache = cache; }
         } else {
             // Not cachable - fall back to QMetaObject (eg. dynamic meta object)
             // XXX QDeclarativeOpenMetaObject has a cache, so this is suboptimal.
             // XXX This is a workaround for QTBUG-9420.
             const QMetaObject *mo = obj->metaObject();
             QStringList r;
             int pc = mo->propertyCount();
             int po = mo->propertyOffset();
             for (int i=po; i<pc; ++i)
                 r += QString::fromUtf8(mo->property(i).name());
             return r;
         }
     }
     return cache->propertyNames();
 }
queryProperty() [1/2]
QScriptClass::QueryFlags QDeclarativeObjectScriptClass::queryProperty (QObject * obj, const Identifier & name, QScriptClass::QueryFlags flags, QDeclarativeContextData * evalContext, QueryHints hints = 0)
Definition at line 159 of file qdeclarativeobjectscriptclass.cpp.
Referenced by QDeclarativeTypeNameScriptClass::queryProperty(), QDeclarativeContextScriptClass::queryProperty(), and queryProperty().
 {
     Q_UNUSED(flags);
     lastData = 0;
     lastTNData = 0;
     if (name == m_destroyId.identifier ||
         name == m_toStringId.identifier)
         return QScriptClass::HandlesReadAccess;
     if (!obj)
         return 0;
     QDeclarativeEnginePrivate *enginePrivate = QDeclarativeEnginePrivate::get(engine);
     lastData = QDeclarativePropertyCache::property(engine, obj, name, local);
     if ((hints & ImplicitObject) && lastData && lastData->revision != 0) {
         QDeclarativeData *ddata = QDeclarativeData::get(obj);
         if (ddata && ddata->propertyCache && !ddata->propertyCache->isAllowedInRevision(lastData))
             return 0;
     }
     if (lastData)
         return QScriptClass::HandlesReadAccess | QScriptClass::HandlesWriteAccess;
     if (!(hints & SkipAttachedProperties)) {
         if (!evalContext && context()) {
             // Global object, QScriptContext activation object, QDeclarativeContext object
             QScriptValue scopeNode = scopeChainValue(context(), -3);
             if (scopeNode.isValid()) {
                 Q_ASSERT(scriptClass(scopeNode) == enginePrivate->contextClass);
                 evalContext = enginePrivate->contextClass->contextFromValue(scopeNode);
             }
         }
         if (evalContext && evalContext->imports) {
             QDeclarativeTypeNameCache::Data *data = evalContext->imports->data(name);
             if (data) {
                 lastTNData = data;
                 return QScriptClass::HandlesReadAccess;
             }
         }
     }
     if (!(hints & ImplicitObject)) {
         local.coreIndex = -1;
         lastData = &local;
         return QScriptClass::HandlesWriteAccess;
     }
     return 0;
 }
queryProperty() [2/2]
QScriptClass::QueryFlags QDeclarativeObjectScriptClass::queryProperty (Object * object, const Identifier & name, QScriptClass::QueryFlags flags) protected virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 152 of file qdeclarativeobjectscriptclass.cpp.
 {
     return queryProperty(toQObject(object), name, flags, 0);
 }
setProperty() [1/2]
void QDeclarativeObjectScriptClass::setProperty (QObject * obj, const Identifier & name, const QScriptValue & value, QScriptContext * context, QDeclarativeContextData * evalContext = 0)
Definition at line 337 of file qdeclarativeobjectscriptclass.cpp.
Referenced by QDeclarativeTypeNameScriptClass::setProperty(), QDeclarativeContextScriptClass::setProperty(), and setProperty().
 {
     Q_UNUSED(name);
     Q_ASSERT(obj);
     Q_ASSERT(lastData);
     Q_ASSERT(context);
     if (!lastData->isValid()) {
         QString error = QLatin1String("Cannot assign to non-existent property \"") +
                         toString(name) + QLatin1Char('\"');
         context->throwError(error);
         return;
     }
     if (!(lastData->flags & QDeclarativePropertyCache::Data::IsWritable) &&
         !(lastData->flags & QDeclarativePropertyCache::Data::IsQList)) {
         QString error = QLatin1String("Cannot assign to read-only property \"") +
                         toString(name) + QLatin1Char('\"');
         context->throwError(error);
         return;
     }
     QDeclarativeEnginePrivate *enginePriv = QDeclarativeEnginePrivate::get(engine);
     if (!evalContext) {
         // Global object, QScriptContext activation object, QDeclarativeContext object
         QScriptValue scopeNode = scopeChainValue(context, -3);
         if (scopeNode.isValid()) {
             Q_ASSERT(scriptClass(scopeNode) == enginePriv->contextClass);
             evalContext = enginePriv->contextClass->contextFromValue(scopeNode);
         }
     }
     QDeclarativeBinding *newBinding = 0;
     if (value.isFunction() && !value.isRegExp()) {
         QScriptContextInfo ctxtInfo(context);
         QDeclarativePropertyCache::ValueTypeData valueTypeData;
         newBinding = new QDeclarativeBinding(value, obj, evalContext);
         newBinding->setSourceLocation(ctxtInfo.fileName(), ctxtInfo.functionStartLineNumber());
         newBinding->setTarget(QDeclarativePropertyPrivate::restore(*lastData, valueTypeData, obj, evalContext));
         if (newBinding->expression().contains(QLatin1String("this")))
             newBinding->setEvaluateFlags(newBinding->evaluateFlags() | QDeclarativeBinding::RequiresThisObject);
     }
     QDeclarativeAbstractBinding *delBinding =
         QDeclarativePropertyPrivate::setBinding(obj, lastData->coreIndex, -1, newBinding);
     if (delBinding)
         delBinding->destroy();
     if (value.isNull() && lastData->flags & QDeclarativePropertyCache::Data::IsQObjectDerived) {
         QObject *o = 0;
         int status = -1;
         int flags = 0;
         void *argv[] = { &o, 0, &status, &flags };
         QMetaObject::metacall(obj, QMetaObject::WriteProperty, lastData->coreIndex, argv);
     } else if (value.isUndefined() && lastData->flags & QDeclarativePropertyCache::Data::IsResettable) {
         void *a[] = { 0 };
         QMetaObject::metacall(obj, QMetaObject::ResetProperty, lastData->coreIndex, a);
     } else if (value.isUndefined() && lastData->propType == qMetaTypeId<QVariant>()) {
         QDeclarativePropertyPrivate::write(obj, *lastData, QVariant(), evalContext);
     } else if (value.isUndefined()) {
         QString error = QLatin1String("Cannot assign [undefined] to ") +
                         QLatin1String(QMetaType::typeName(lastData->propType));
         context->throwError(error);
     } else if (value.isFunction() && !value.isRegExp()) {
         // this is handled by the binding creation above
     } else {
         //### expand optimization for other known types
         if (lastData->propType == QMetaType::Int && value.isNumber()) {
             int rawValue = qRoundDouble(value.toNumber());
             int status = -1;
             int flags = 0;
             void *a[] = { (void *)&rawValue, 0, &status, &flags };
             QMetaObject::metacall(obj, QMetaObject::WriteProperty,
                                   lastData->coreIndex, a);
             return;
         } else if (lastData->propType == QMetaType::QReal && value.isNumber()) {
             qreal rawValue = qreal(value.toNumber());
             int status = -1;
             int flags = 0;
             void *a[] = { (void *)&rawValue, 0, &status, &flags };
             QMetaObject::metacall(obj, QMetaObject::WriteProperty,
                                   lastData->coreIndex, a);
             return;
         } else if (lastData->propType == QMetaType::QString && value.isString()) {
             const QString &rawValue = value.toString();
             int status = -1;
             int flags = 0;
             void *a[] = { (void *)&rawValue, 0, &status, &flags };
             QMetaObject::metacall(obj, QMetaObject::WriteProperty,
                                   lastData->coreIndex, a);
             return;
         }
         QVariant v;
         if (lastData->flags & QDeclarativePropertyCache::Data::IsQList)
             v = enginePriv->scriptValueToVariant(value, qMetaTypeId<QList<QObject *> >());
         else
             v = enginePriv->scriptValueToVariant(value, lastData->propType);
         if (!QDeclarativePropertyPrivate::write(obj, *lastData, v, evalContext)) {
             const char *valueType = 0;
             if (v.userType() == QVariant::Invalid) valueType = "null";
             else valueType = QMetaType::typeName(v.userType());
             QString error = QLatin1String("Cannot assign ") +
                             QLatin1String(valueType) +
                             QLatin1String(" to ") +
                             QLatin1String(QMetaType::typeName(lastData->propType));
             context->throwError(error);
         }
     }
 }
setProperty() [2/2]
void QDeclarativeObjectScriptClass::setProperty (Object * object, const Identifier & name, const QScriptValue & value) protected virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 325 of file qdeclarativeobjectscriptclass.cpp.
 {
     return setProperty(toQObject(object), name, value, context());
 }
toQObject() [1/2]
QObject * QDeclarativeObjectScriptClass::toQObject (const QScriptValue & value) const
Definition at line 137 of file qdeclarativeobjectscriptclass.cpp.
Referenced by QDeclarativeEnginePrivate::createQmlObject(), property(), propertyNames(), queryProperty(), and setProperty().
 {
     return value.toQObject();
 }
toQObject() [2/2]
QObject * QDeclarativeObjectScriptClass::toQObject (Object * object, bool * ok = 0) protected virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 463 of file qdeclarativeobjectscriptclass.cpp.
 {
     if (ok) *ok = true;
     ObjectData *data = (ObjectData*)object;
     return data->object.data();
 }
tostring()
QScriptValue QDeclarativeObjectScriptClass::tostring (QScriptContext * context, QScriptEngine * engine) static private
Definition at line 471 of file qdeclarativeobjectscriptclass.cpp.
Referenced by QDeclarativeObjectScriptClass().
 {
     QObject* obj = context->thisObject().toQObject();
     QString ret;
     if(obj){
         QString objectName = obj->objectName();
         ret += QString::fromUtf8(obj->metaObject()->className());
         ret += QLatin1String("(0x");
         ret += QString::number((quintptr)obj,16);
         if (!objectName.isEmpty()) {
             ret += QLatin1String(", \"");
             ret += objectName;
             ret += QLatin1Char('\"');
         }
         ret += QLatin1Char(')');
     }else{
         ret += QLatin1String("null");
     }
     return QScriptValue(ret);
 }
Friends and Related Functions
QDeclarativeObjectMethodScriptClass
friend class QDeclarativeObjectMethodScriptClass friend
Definition at line 144 of file qdeclarativeobjectscriptclass_p.h.
Properties
engine
QDeclarativeEngine* QDeclarativeObjectScriptClass::engine private
Definition at line 159 of file qdeclarativeobjectscriptclass_p.h.
lastData
QDeclarativePropertyCache::Data* QDeclarativeObjectScriptClass::lastData private
Definition at line 148 of file qdeclarativeobjectscriptclass_p.h.
Referenced by property(), queryProperty(), and setProperty().
lastTNData
QDeclarativeTypeNameCache::Data* QDeclarativeObjectScriptClass::lastTNData private
Definition at line 147 of file qdeclarativeobjectscriptclass_p.h.
Referenced by property(), and queryProperty().
local
QDeclarativePropertyCache::Data QDeclarativeObjectScriptClass::local private
Definition at line 149 of file qdeclarativeobjectscriptclass_p.h.
Referenced by queryProperty().
m_destroy
QScriptValue QDeclarativeObjectScriptClass::m_destroy private
Definition at line 153 of file qdeclarativeobjectscriptclass_p.h.
Referenced by property(), and QDeclarativeObjectScriptClass().
m_destroyId
PersistentIdentifier QDeclarativeObjectScriptClass::m_destroyId private
Definition at line 151 of file qdeclarativeobjectscriptclass_p.h.
Referenced by property(), QDeclarativeObjectScriptClass(), and queryProperty().
m_toString
QScriptValue QDeclarativeObjectScriptClass::m_toString private
Definition at line 154 of file qdeclarativeobjectscriptclass_p.h.
Referenced by property(), and QDeclarativeObjectScriptClass().
m_toStringId
PersistentIdentifier QDeclarativeObjectScriptClass::m_toStringId private
Definition at line 152 of file qdeclarativeobjectscriptclass_p.h.
Referenced by property(), QDeclarativeObjectScriptClass(), and queryProperty().
methods
QDeclarativeObjectMethodScriptClass QDeclarativeObjectScriptClass::methods private
Definition at line 145 of file qdeclarativeobjectscriptclass_p.h.
Referenced by QDeclarativeObjectMethodScriptClass::connect(), QDeclarativeObjectMethodScriptClass::disconnect(), and property().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeobjectscriptclass_p.h
/src/declarative/qml/qdeclarativeobjectscriptclass.cpp