Qt 4.8: QTextBlock::iterator Class Reference
QTextBlock::iterator Class Reference
The QTextBlock::iterator class provides an iterator for reading the contents of a QTextBlock.
#include <qtextobject.h>
Public Functions
bool atEnd () const
Returns true if the current item is the last item in the text block.
QTextFragment fragment () const
Returns the text fragment the iterator currently points to.
iterator ()
Constructs an iterator for this text block.
iterator (const iterator &o)
Copy constructor.
bool operator!= (const iterator &o) const
Retuns true if this iterator is different from the other iterator; otherwise returns false.
iterator & operator++ ()
The prefix ++ operator (++i) advances the iterator to the next item in the hash and returns an iterator to the new current item.
iterator operator++ (int)
The postfix ++ operator (i++) advances the iterator to the next item in the text block and returns an iterator to the old current item.
iterator & operator-- ()
The prefix – operator (–i) makes the preceding item current and returns an iterator pointing to the new current item.
iterator operator-- (int)
The postfix – operator (i–) makes the preceding item current and returns an iterator to the old current item.
bool operator== (const iterator &o) const
Retuns true if this iterator is the same as the other iterator; otherwise returns false.
Private Functions
iterator (const QTextDocumentPrivate *priv, int begin, int end, int f)
Properties
int b
int e
int n
const QTextDocumentPrivate * p
Friends
class QTextBlock
Detailed Description
The QTextBlock::iterator class provides an iterator for reading the contents of a QTextBlock.
Note
This class or function is reentrant.
A block consists of a sequence of text fragments. This class provides a way to iterate over these, and read their contents. It does not provide a way to modify the internal structure or contents of the block.
An iterator can be constructed and used to access the fragments within a text block in the following way:
    QTextBlock::iterator it;
    for (it = currentBlock.begin(); !(it.atEnd()); ++it) {
        QTextFragment currentFragment = it.fragment();
        if (currentFragment.isValid())
            processFragment(currentFragment);
    }
See also
QTextFragment
Definition at line 251 of file qtextobject.h.
Constructors and Destructors
iterator() [1/3]
QTextBlock::iterator::iterator (const QTextDocumentPrivate * priv, int begin, int end, int f) inline private
Definition at line 257 of file qtextobject.h.
 : p(priv), b(begin), e(end), n(f) {}
iterator() [2/3]
QTextBlock::iterator::iterator () inline
Constructs an iterator for this text block.
Definition at line 259 of file qtextobject.h.
 : p(0), b(0), e(0), n(0) {}
iterator() [3/3]
QTextBlock::iterator::iterator (const iterator & other) inline
Copy constructor.
Constructs a copy of the other iterator.
Definition at line 260 of file qtextobject.h.
 : p(o.p), b(o.b), e(o.e), n(o.n) {}
Functions
atEnd()
bool QTextBlock::iterator::atEnd () const inline
Returns true if the current item is the last item in the text block.
Definition at line 264 of file qtextobject.h.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), QTextHtmlExporter::emitBlock(), QTextHtmlExporter::emitBlockAttributes(), QTextHtmlExporter::emitFrame(), QTextControl::findNextPrevAnchor(), and QTextOdfWriter::writeBlock().
 { return n == e; }
fragment()
QTextFragment QTextBlock::iterator::fragment () const
Returns the text fragment the iterator currently points to.
Definition at line 1640 of file qtextobject.cpp.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), QTextHtmlExporter::emitBlock(), and QTextControl::findNextPrevAnchor().
 {
     int ne = n;
     int formatIndex = p->fragmentMap().fragment(n)->format;
     do {
         ne = p->fragmentMap().next(ne);
     } while (ne != e && p->fragmentMap().fragment(ne)->format == formatIndex);
     return QTextFragment(p, n, ne);
 }
operator!=()
bool QTextBlock::iterator::operator!= (const iterator & o) const inline
Retuns true if this iterator is different from the other iterator; otherwise returns false.
Definition at line 267 of file qtextobject.h.
 { return p != o.p || n != o.n; }
operator++() [1/2]
QTextBlock::iterator & QTextBlock::iterator::operator++ ()
The prefix ++ operator (++i) advances the iterator to the next item in the hash and returns an iterator to the new current item.
Definition at line 1656 of file qtextobject.cpp.
 {
     int ne = n;
     int formatIndex = p->fragmentMap().fragment(n)->format;
     do {
         ne = p->fragmentMap().next(ne);
     } while (ne != e && p->fragmentMap().fragment(ne)->format == formatIndex);
     n = ne;
     return *this;
 }
operator++() [2/2]
QTextBlock::iterator QTextBlock::iterator::operator++ (int) inline
The postfix ++ operator (i++) advances the iterator to the next item in the text block and returns an iterator to the old current item.
Definition at line 269 of file qtextobject.h.
Referenced by operator++().
 { iterator tmp = *this; operator++(); return tmp; }
operator--() [1/2]
QTextBlock::iterator & QTextBlock::iterator::operator-- ()
The prefix – operator (–i) makes the preceding item current and returns an iterator pointing to the new current item.
Definition at line 1672 of file qtextobject.cpp.
 {
     n = p->fragmentMap().previous(n);
     if (n == b)
         return *this;
     int formatIndex = p->fragmentMap().fragment(n)->format;
     int last = n;
     while (n != b && p->fragmentMap().fragment(n)->format != formatIndex) {
         last = n;
         n = p->fragmentMap().previous(n);
     }
     n = last;
     return *this;
 }
operator--() [2/2]
QTextBlock::iterator QTextBlock::iterator::operator-- (int) inline
The postfix – operator (i–) makes the preceding item current and returns an iterator to the old current item.
Definition at line 271 of file qtextobject.h.
Referenced by operator--().
 { iterator tmp = *this; operator--(); return tmp; }
operator==()
bool QTextBlock::iterator::operator== (const iterator & o) const inline
Retuns true if this iterator is the same as the other iterator; otherwise returns false.
Definition at line 266 of file qtextobject.h.
 { return p == o.p && n == o.n; }
Friends and Related Functions
QTextBlock
friend class QTextBlock friend
Definition at line 256 of file qtextobject.h.
Properties
b
int QTextBlock::iterator::b private
Definition at line 253 of file qtextobject.h.
e
int QTextBlock::iterator::e private
Definition at line 254 of file qtextobject.h.
n
int QTextBlock::iterator::n private
Definition at line 255 of file qtextobject.h.
Referenced by operator!=(), and operator==().
p
const QTextDocumentPrivate* QTextBlock::iterator::p private
Definition at line 252 of file qtextobject.h.
Referenced by operator!=(), and operator==().
The documentation for this class was generated from the following files:
/src/gui/text/qtextobject.h
/src/gui/text/qtextobject.cpp