Qt 4.8: QDeclarativeGridViewAttached Class Reference
QDeclarativeGridViewAttached Class Reference
#include <qdeclarativegridview_p.h>
Signals
void add ()
void currentItemChanged ()
void delayRemoveChanged ()
void remove ()
void viewChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool delayRemove () const
void emitAdd ()
void emitRemove ()
bool isCurrentItem () const
QDeclarativeGridViewAttached (QObject *parent)
void setDelayRemove (bool delay)
void setIsCurrentItem (bool c)
void setView (QDeclarativeGridView *view)
QDeclarativeGridView * view ()
~QDeclarativeGridViewAttached ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
bool delayRemove
bool isCurrentItem
bool m_delayRemove: 1
bool m_isCurrent: 1
QDeclarativeGuard< QDeclarativeGridView > m_view
QDeclarativeGridView * view
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 227 of file qdeclarativegridview_p.h.
Constructors and Destructors
QDeclarativeGridViewAttached()
QDeclarativeGridViewAttached::QDeclarativeGridViewAttached (QObject * parent) inline
Definition at line 231 of file qdeclarativegridview_p.h.
         : QObject(parent), m_view(0), m_isCurrent(false), m_delayRemove(false) {}
~QDeclarativeGridViewAttached()
QDeclarativeGridViewAttached::~QDeclarativeGridViewAttached () inline
Definition at line 233 of file qdeclarativegridview_p.h.
 {}
Functions
add
void QDeclarativeGridViewAttached::add () signal
currentItemChanged
void QDeclarativeGridViewAttached::currentItemChanged () signal
delayRemove()
bool QDeclarativeGridViewAttached::delayRemove () const inline
Definition at line 254 of file qdeclarativegridview_p.h.
 { return m_delayRemove; }
delayRemoveChanged
void QDeclarativeGridViewAttached::delayRemoveChanged () signal
emitAdd()
void QDeclarativeGridViewAttached::emitAdd () inline
Definition at line 262 of file qdeclarativegridview_p.h.
Referenced by QDeclarativeGridView::itemsInserted().
 { emit add(); }
emitRemove()
void QDeclarativeGridViewAttached::emitRemove () inline
Definition at line 263 of file qdeclarativegridview_p.h.
Referenced by QDeclarativeGridView::itemsRemoved().
 { emit remove(); }
isCurrentItem()
bool QDeclarativeGridViewAttached::isCurrentItem () const inline
Definition at line 245 of file qdeclarativegridview_p.h.
 { return m_isCurrent; }
remove
void QDeclarativeGridViewAttached::remove () signal
setDelayRemove()
void QDeclarativeGridViewAttached::setDelayRemove (bool delay) inline
Definition at line 255 of file qdeclarativegridview_p.h.
{
         if (m_delayRemove != delay) {
             m_delayRemove = delay;
             emit delayRemoveChanged();
         }
     }
setIsCurrentItem()
void QDeclarativeGridViewAttached::setIsCurrentItem (bool c) inline
Definition at line 246 of file qdeclarativegridview_p.h.
Referenced by QDeclarativeGridViewPrivate::updateCurrent().
{
         if (m_isCurrent != c) {
             m_isCurrent = c;
             emit currentItemChanged();
         }
     }
setView()
void QDeclarativeGridViewAttached::setView (QDeclarativeGridView * view) inline
Definition at line 237 of file qdeclarativegridview_p.h.
Referenced by FxGridItem::FxGridItem().
{
         if (view != m_view) {
             m_view = view;
             emit viewChanged();
         }
     }
view()
QDeclarativeGridView* QDeclarativeGridViewAttached::view () inline
Definition at line 236 of file qdeclarativegridview_p.h.
 { return m_view; }
viewChanged
void QDeclarativeGridViewAttached::viewChanged () signal
Properties
delayRemove
bool QDeclarativeGridViewAttached::delayRemove
Definition at line 253 of file qdeclarativegridview_p.h.
Referenced by QDeclarativeGridView::destroyRemoved(), QDeclarativeGridView::itemsRemoved(), and QDeclarativeGridViewPrivate::refill().
isCurrentItem
bool QDeclarativeGridViewAttached::isCurrentItem
Definition at line 244 of file qdeclarativegridview_p.h.
m_delayRemove
bool QDeclarativeGridViewAttached::m_delayRemove
Definition at line 275 of file qdeclarativegridview_p.h.
m_isCurrent
bool QDeclarativeGridViewAttached::m_isCurrent
Definition at line 274 of file qdeclarativegridview_p.h.
m_view
QDeclarativeGuard<QDeclarativeGridView> QDeclarativeGridViewAttached::m_view
Definition at line 273 of file qdeclarativegridview_p.h.
view
QDeclarativeGridView* QDeclarativeGridViewAttached::view
Definition at line 235 of file qdeclarativegridview_p.h.
The documentation for this class was generated from the following file:
/src/declarative/graphicsitems/qdeclarativegridview_p.h