Qt 4.8: QCFString Class Reference
QCFString Class Reference
#include <qcore_mac_p.h>
Public Functions
operator CFStringRef () const
operator QString () const
QCFString (const QString &str)
QCFString (const CFStringRef cfstr=0)
QCFString (const QCFType< CFStringRef > &other)
Public Functions inherited from QCFType< CFStringRef >
X as () const
operator CFStringRef ()
CFStringRef * operator& ()
QCFType operator= (const QCFType &helper)
QCFType (const CFStringRef &t=0)
QCFType (const QCFType &helper)
~QCFType ()
Static Public Functions
static CFStringRef toCFStringRef (const QString &str)
static QString toQString (CFStringRef cfstr)
Static Public Functions inherited from QCFType< CFStringRef >
static QCFType constructFromGet (const CFStringRef &t)
Properties
QString string
Additional Inherited Members
Protected Variables inherited from QCFType< CFStringRef >
CFStringRef type
Detailed Description
Definition at line 138 of file qcore_mac_p.h.
Constructors and Destructors
QCFString() [1/3]
QCFString::QCFString (const QString & str) inline
Definition at line 141 of file qcore_mac_p.h.
Referenced by qt_mac_from_pascal_string(), and qt_mac_to_pascal_string().
 : QCFType<CFStringRef>(0), string(str) {}
QCFString() [2/3]
QCFString::QCFString (const CFStringRef cfstr = 0) inline
Definition at line 142 of file qcore_mac_p.h.
 : QCFType<CFStringRef>(cfstr) {}
QCFString() [3/3]
QCFString::QCFString (const QCFType< CFStringRef > & other) inline
Definition at line 143 of file qcore_mac_p.h.
 : QCFType<CFStringRef>(other) {}
Functions
operator CFStringRef()
QCFString::operator CFStringRef () const
Definition at line 75 of file qcore_mac.cpp.
 {
     if (!type) {
         if (string.d->data != string.d->array)
             const_cast<QCFString*>(this)->string.realloc(); // ### Qt5: do we really need this stupid user protection?
         const_cast<QCFString*>(this)->type =
             CFStringCreateWithCharactersNoCopy(0,
                                                reinterpret_cast<const UniChar *>(string.unicode()),
                                                string.length(),
                                                kCFAllocatorNull);
     }
     return type;
 }
operator QString()
QCFString::operator QString () const
Definition at line 62 of file qcore_mac.cpp.
 {
     if (string.isEmpty() && type)
         const_cast<QCFString*>(this)->string = toQString(type);
     return string;
 }
toCFStringRef()
CFStringRef QCFString::toCFStringRef (const QString & str) static
Definition at line 69 of file qcore_mac.cpp.
Referenced by QFileDialogPrivate::createNavServicesDialog(), QAuServerMac::createNSSound(), flipYCoordinate(), getAllActionNames(), handleStringAttribute(), loadFromDatabase(), macFormatCurrency(), macKey(), macValue(), qt_getOpenGLBundle(), QFileDialogPrivate::qt_mac_filedialog_event_proc(), qt_mac_QStringListToNSMutableArrayVoid(), QMacPrintEnginePrivate::setPaperSize(), and QPrinterInfo::supportedPaperSizes().
 {
     return CFStringCreateWithCharacters(0, reinterpret_cast<const UniChar *>(string.unicode()),
                                         string.length());
 }
toQString()
QString QCFString::toQString (CFStringRef cfstr) static
Definition at line 47 of file qcore_mac.cpp.
Referenced by QPrinterInfo::availablePrinters(), QFileSystemEngine::bundleName(), QFileSystemEngine::canonicalName(), QCoreWlanEngine::connectToId(), QMacPasteboardMimeVCard::convertFromMime(), QCoreWlanEngine::doRequestUpdate(), QDragManager::drag(), familyNameFromPostScriptName(), QMacSettingsPrivate::fileName(), flipYCoordinate(), QMacPasteboard::formats(), QFSEventsFileSystemWatcherEngine::fseventsCallback(), get_device_info(), getCFLocaleValue(), QFileSystemEngine::getLinkTarget(), getMacDateFormat(), getMacLocaleName(), getMacTimeFormat(), QScanThread::getUserConfigurations(), QMacPasteboard::hasFormat(), isHostExcluded(), macCurrencySymbol(), macDayName(), macFormatCurrency(), macMeasurementSystem(), macMonthName(), macQueryInternal(), macQuoteString(), networkChangeCallback(), operator QString(), performNamedAction(), QCoreTextFontDatabase::populateFontDatabase(), QMacPasteboard::promiseKeeper(), QMacPrintEngine::property(), proxyFromDictionary(), qfontForCocoaFont(), QMacPasteboard::QMacPasteboard(), qt_init(), QFileDialogPrivate::qt_mac_filedialog_event_proc(), qtKey(), qtKey2CocoaKey(), qtValue(), QMacPasteboard::retrieveData(), QScanThread::run(), QFileDialogPrivate::selectedFiles_sys(), setNamedAttribute(), QMacPrintEngine::setProperty(), QCoreWlanEngine::startTime(), and QKeyMapperPrivate::~QKeyMapperPrivate().
 {
     if (!str)
         return QString();
     CFIndex length = CFStringGetLength(str);
     if (length == 0)
         return QString();
     QString string(length, Qt::Uninitialized);
     CFStringGetCharacters(str, CFRangeMake(0, length), reinterpret_cast<UniChar *>(const_cast<QChar *>(string.unicode())));
     return string;
 }
Properties
string
QString QCFString::string private
Definition at line 149 of file qcore_mac_p.h.
Referenced by operator QString(), and toQString().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qcore_mac_p.h
/src/corelib/kernel/qcore_mac.cpp