Qt 4.8: QFontEngine Class Reference
QFontEngine Class Reference abstract
#include <qfontengine_p.h>
Classes
struct FaceId
struct GlyphCacheEntry
struct KernPair
struct Properties
Public Types
enum GlyphFormat {
Format_None, Format_Render = Format_None, Format_Mono, Format_A8,
Format_A32
}
enum SynthesizedFlags { SynthesizedItalic = 0x1, SynthesizedBold = 0x2, SynthesizedStretch = 0x4 }
enum Type {
Box, Multi, XLFD, Win,
Mac, Freetype, QPF1, QPF2,
Proxy, S60FontEngine, DirectWrite, TestFontEngine = 0x1000
}
Public Functions
void addBitmapFontToPath (qreal x, qreal y, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags)
virtual void addGlyphsToPath (glyph_t *glyphs, QFixedPoint *positions, int nglyphs, QPainterPath *path, QTextItem::RenderFlags flags)
virtual void addOutlineToPath (qreal, qreal, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags flags)
virtual glyph_metrics_t alphaMapBoundingBox (glyph_t glyph, QFixed, const QTransform &matrix, GlyphFormat)
virtual QImage alphaMapForGlyph (glyph_t)
virtual QImage alphaMapForGlyph (glyph_t glyph, QFixed subPixelPosition)
virtual QImage alphaMapForGlyph (glyph_t, const QTransform &t)
virtual QImage alphaMapForGlyph (glyph_t, QFixed subPixelPosition, const QTransform &t)
virtual QImage alphaRGBMapForGlyph (glyph_t, QFixed subPixelPosition, int margin, const QTransform &t)
virtual QFixed ascent () const =0
virtual QFixed averageCharWidth () const
virtual glyph_metrics_t boundingBox (const QGlyphLayout &glyphs)=0
virtual glyph_metrics_t boundingBox (glyph_t glyph)=0
virtual glyph_metrics_t boundingBox (glyph_t glyph, const QTransform &matrix)
virtual bool canRender (const QChar *string, int len)=0
virtual QFontEngine * cloneWithSize (qreal) const
virtual QFixed descent () const =0
virtual void doKerning (QGlyphLayout *, QTextEngine::ShaperFlags) const
virtual QFixed emSquareSize () const
virtual FaceId faceId () const
virtual void getGlyphBearings (glyph_t glyph, qreal *leftBearing=0, qreal *rightBearing=0)
void getGlyphPositions (const QGlyphLayout &glyphs, const QTransform &matrix, QTextItem::RenderFlags flags, QVarLengthArray< glyph_t > &glyphs_out, QVarLengthArray< QFixedPoint > &positions)
virtual HB_Error getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed *xpos, HB_Fixed *ypos, hb_uint32 *nPoints)
QByteArray getSfntTable (uint) const
virtual bool getSfntTableData (uint, uchar *, uint *) const
virtual void getUnscaledGlyph (glyph_t glyph, QPainterPath *path, glyph_metrics_t *metrics)
QFontEngineGlyphCache * glyphCache (void *key, QFontEngineGlyphCache::Type type, const QTransform &transform) const
virtual int glyphCount () const
HB_Face harfbuzzFace () const
HB_Font harfbuzzFont () const
virtual QFixed leading () const =0
virtual QFixed lineThickness () const
void loadKerningPairs (QFixed scalingFactor)
virtual qreal maxCharWidth () const =0
virtual qreal minLeftBearing () const
virtual qreal minRightBearing () const
virtual const char * name () const =0
virtual Properties properties () const
QFontEngine ()
virtual void recalcAdvances (QGlyphLayout *, QTextEngine::ShaperFlags) const
virtual void removeGlyphFromCache (glyph_t)
void setGlyphCache (void *key, QFontEngineGlyphCache *data)
virtual bool stringToCMap (const QChar *str, int len, QGlyphLayout *glyphs, int *nglyphs, QTextEngine::ShaperFlags flags) const =0
virtual bool supportsSubPixelPositions () const
virtual int synthesized () const
glyph_metrics_t tightBoundingBox (const QGlyphLayout &glyphs)
virtual Type type () const =0
virtual QFixed underlinePosition () const
virtual QFixed xHeight () const
virtual ~QFontEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QByteArray convertToPostscriptFontFamilyName (const QByteArray &fontFamily)
static const uchar * getCMap (const uchar *table, uint tableSize, bool *isSymbolFont, int *cmapSize)
static quint32 getTrueTypeGlyphIndex (const uchar *cmap, uint unicode)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables
uint cache_cost
int cache_count
QFontDef fontDef
uint fsType: 16
int glyphFormat
HB_Face hbFace
HB_FontRec hbFont
QVector< KernPair > kerning_pairs
QAtomicInt ref
bool symbol
Protected Functions
QFixed lastRightBearing (const QGlyphLayout &glyphs, bool round=false)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Protected Functions
static const QVector< QRgb > & grayPalette ()
Properties
QLinkedList< GlyphCacheEntry > m_glyphCaches
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 95 of file qfontengine_p.h.
Enumerations
GlyphFormat
enum QFontEngine::GlyphFormat
Enumerator
Format_None
Format_Render
Format_Mono
Format_A8
Format_A32
Definition at line 125 of file qfontengine_p.h.
                      {
         Format_None,
         Format_Render = Format_None,
         Format_Mono,
         Format_A8,
         Format_A32
     };
SynthesizedFlags
enum QFontEngine::SynthesizedFlags
Enumerator
SynthesizedItalic
SynthesizedBold
SynthesizedStretch
Definition at line 163 of file qfontengine_p.h.
{
         SynthesizedItalic = 0x1,
         SynthesizedBold = 0x2,
         SynthesizedStretch = 0x4
     };
Type
enum QFontEngine::Type
Enumerator
Box
Multi
XLFD
Win
Mac
Freetype
QPF1
QPF2
Proxy
S60FontEngine
DirectWrite
TestFontEngine
Definition at line 98 of file qfontengine_p.h.
               {
         Box,
         Multi,
         // X11 types
         XLFD,
         // MS Windows types
         Win,
         // Apple Mac OS types
         Mac,
         // QWS types
         Freetype,
         QPF1,
         QPF2,
         Proxy,
         // S60 types
         S60FontEngine, // Cannot be simply called "S60". Reason is qt_s60Data.h
         DirectWrite,
         TestFontEngine = 0x1000
     };
Constructors and Destructors
QFontEngine()
QFontEngine::QFontEngine ()
Definition at line 176 of file qfontengine.cpp.
     : QObject()
 {
     ref = 0;
     cache_count = 0;
     fsType = 0;
     symbol = false;
     memset(&hbFont, 0, sizeof(hbFont));
     hbFont.klass = &hb_fontClass;
     hbFont.userData = this;
     hbFace = 0;
     glyphFormat = -1;
 }
~QFontEngine()
QFontEngine::~QFontEngine () virtual
Definition at line 191 of file qfontengine.cpp.
 {
     m_glyphCaches.clear();
     qHBFreeFace(hbFace);
 }
Functions
addBitmapFontToPath()
void QFontEngine::addBitmapFontToPath (qreal x, qreal y, const QGlyphLayout & glyphs, QPainterPath * path, QTextItem::RenderFlags flags)
Definition at line 526 of file qfontengine.cpp.
Referenced by addGlyphsToPath(), QFontEngineWin::addOutlineToPath(), QFontEngineQPA::addOutlineToPath(), and QFontEngineQPF::addOutlineToPath().
 {
 // TODO what to do with 'flags' ??
     Q_UNUSED(flags);
     QFixed advanceX = QFixed::fromReal(x);
     QFixed advanceY = QFixed::fromReal(y);
     for (int i=0; i < glyphs.numGlyphs; ++i) {
         glyph_metrics_t metrics = boundingBox(glyphs.glyphs[i]);
         if (metrics.width.value() == 0 || metrics.height.value() == 0) {
             advanceX += glyphs.advances_x[i];
             advanceY += glyphs.advances_y[i];
             continue;
         }
         const QImage alphaMask = alphaMapForGlyph(glyphs.glyphs[i]);
         const int w = alphaMask.width();
         const int h = alphaMask.height();
         const int srcBpl = alphaMask.bytesPerLine();
         QImage bitmap;
         if (alphaMask.depth() == 1) {
             bitmap = alphaMask;
         } else {
             bitmap = QImage(w, h, QImage::Format_Mono);
             const uchar *imageData = alphaMask.bits();
             const int destBpl = bitmap.bytesPerLine();
             uchar *bitmapData = bitmap.bits();
             for (int yi = 0; yi < h; ++yi) {
                 const uchar *src = imageData + yi*srcBpl;
                 uchar *dst = bitmapData + yi*destBpl;
                 for (int xi = 0; xi < w; ++xi) {
                     const int byte = xi / 8;
                     const int bit = xi % 8;
                     if (bit == 0)
                         dst[byte] = 0;
                     if (src[xi])
                         dst[byte] |= 128 >> bit;
                 }
             }
         }
         const uchar *bitmap_data = bitmap.bits();
         QFixedPoint offset = glyphs.offsets[i];
         advanceX += offset.x;
         advanceY += offset.y;
         qt_addBitmapToPath((advanceX + metrics.x).toReal(), (advanceY + metrics.y).toReal(), bitmap_data, bitmap.bytesPerLine(), w, h, path);
         advanceX += glyphs.advances_x[i];
         advanceY += glyphs.advances_y[i];
     }
 }
addGlyphsToPath()
void QFontEngine::addGlyphsToPath (glyph_t * glyphs, QFixedPoint * positions, int nglyphs, QPainterPath * path, QTextItem::RenderFlags flags) virtual
Reimplemented in QFontEngineFT, QFontEngineDirectWrite, QCoreTextFontEngine, QFontEngineWin, QProxyFontEngine, and QFontEngineMac.
Definition at line 577 of file qfontengine.cpp.
Referenced by QProxyFontEngine::addGlyphsToPath(), addOutlineToPath(), alphaMapForGlyph(), alphaMapFromPath(), QTextureGlyphCache::calculateSubPixelPositionCount(), QPaintEngineEx::drawStaticTextItem(), getUnscaledGlyph(), and QRawFont::pathForGlyph().
 {
     qreal x = positions[0].x.toReal();
     qreal y = positions[0].y.toReal();
     QVarLengthGlyphLayoutArray g(nGlyphs);
     for (int i = 0; i < nGlyphs; ++i) {
         g.glyphs[i] = glyphs[i];
         if (i < nGlyphs - 1) {
             g.advances_x[i] = positions[i+1].x - positions[i].x;
             g.advances_y[i] = positions[i+1].y - positions[i].y;
         } else {
             g.advances_x[i] = QFixed::fromReal(maxCharWidth());
             g.advances_y[i] = 0;
         }
     }
     addBitmapFontToPath(x, y, g, path, flags);
 }
addOutlineToPath()
void QFontEngine::addOutlineToPath (qreal x, qreal y, const QGlyphLayout & glyphs, QPainterPath * path, QTextItem::RenderFlags flags) virtual
Reimplemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineXLFD, and QFontEngineWin.
Definition at line 419 of file qfontengine.cpp.
Referenced by QFontEngineWin::addOutlineToPath(), QFontEngineQPF::addOutlineToPath(), QFontEngineFT::addOutlineToPath(), QPainterPath::addText(), and QPaintEngine::drawTextItem().
 {
     if (!glyphs.numGlyphs)
         return;
     QVarLengthArray<QFixedPoint> positions;
     QVarLengthArray<glyph_t> positioned_glyphs;
     QTransform matrix = QTransform::fromTranslate(x, y);
     getGlyphPositions(glyphs, matrix, flags, positioned_glyphs, positions);
     addGlyphsToPath(positioned_glyphs.data(), positions.data(), positioned_glyphs.size(), path, flags);
 }
alphaMapBoundingBox()
virtual glyph_metrics_t QFontEngine::alphaMapBoundingBox (glyph_t glyph, QFixed , const QTransform & matrix, GlyphFormat) inline virtual
Reimplemented in QFontEngineFT, and QFontEngineDirectWrite.
Definition at line 204 of file qfontengine_p.h.
Referenced by QTextureGlyphCache::populate().
     {
         return boundingBox(glyph, matrix);
     }
alphaMapForGlyph() [1/4]
QImage QFontEngine::alphaMapForGlyph (glyph_t glyph) virtual
Create a qimage with the alpha values for the glyph. Returns an image indexed_8 with index values ranging from 0=fully transparent to 255=opaque
Reimplemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineXLFD, QFontEngineWin, QFontEngineMac, and QProxyFontEngine.
Definition at line 645 of file qfontengine.cpp.
Referenced by addBitmapFontToPath(), QRawFont::alphaMapForGlyph(), alphaMapForGlyph(), QFontEngineFT::alphaMapForGlyph(), alphaRGBMapForGlyph(), QGLGlyphCache::cacheGlyphs(), QRasterPaintEngine::drawTextItem(), QVGFontEngineCleaner::fontEngineDestroyed(), QFontEngineQPF::loadGlyph(), and QTextureGlyphCache::textureMapForGlyph().
 {
     glyph_metrics_t gm = boundingBox(glyph);
     int glyph_x = qFloor(gm.x.toReal());
     int glyph_y = qFloor(gm.y.toReal());
     int glyph_width = qCeil((gm.x + gm.width).toReal()) -  glyph_x;
     int glyph_height = qCeil((gm.y + gm.height).toReal()) - glyph_y;
     if (glyph_width <= 0 || glyph_height <= 0)
         return QImage();
     QFixedPoint pt;
     pt.x = -glyph_x;
     pt.y = -glyph_y; // the baseline
     QPainterPath path;
     QImage im(glyph_width + 4, glyph_height, QImage::Format_ARGB32_Premultiplied);
     im.fill(Qt::transparent);
     QPainter p(&im);
     p.setRenderHint(QPainter::Antialiasing);
     addGlyphsToPath(&glyph, &pt, 1, &path, 0);
     p.setPen(Qt::NoPen);
     p.setBrush(Qt::black);
     p.drawPath(path);
     p.end();
     QImage indexed(im.width(), im.height(), QImage::Format_Indexed8);
     QVector<QRgb> colors(256);
     for (int i=0; i<256; ++i)
         colors[i] = qRgba(0, 0, 0, i);
     indexed.setColorTable(colors);
     for (int y=0; y<im.height(); ++y) {
         uchar *dst = (uchar *) indexed.scanLine(y);
         uint *src = (uint *) im.scanLine(y);
         for (int x=0; x<im.width(); ++x)
             dst[x] = qAlpha(src[x]);
     }
     return indexed;
 }
alphaMapForGlyph() [2/4]
QImage QFontEngine::alphaMapForGlyph (glyph_t glyph, QFixed subPixelPosition) virtual
Reimplemented in QFontEngineFT, and QCoreTextFontEngine.
Definition at line 598 of file qfontengine.cpp.
 {
     // For font engines don't support subpixel positioning
     return alphaMapForGlyph(glyph);
 }
alphaMapForGlyph() [3/4]
QImage QFontEngine::alphaMapForGlyph (glyph_t glyph, const QTransform & t) virtual
Reimplemented in QFontEngineWin.
Definition at line 604 of file qfontengine.cpp.
 {
     QImage i = alphaMapForGlyph(glyph);
     if (t.type() > QTransform::TxTranslate)
         i = i.transformed(t).convertToFormat(QImage::Format_Indexed8);
     Q_ASSERT(i.depth() <= 8); // To verify that transformed didn't change the format...
     return i;
 }
alphaMapForGlyph() [4/4]
QImage QFontEngine::alphaMapForGlyph (glyph_t glyph, QFixed subPixelPosition, const QTransform & t) virtual
Reimplemented in QFontEngineDirectWrite.
Definition at line 614 of file qfontengine.cpp.
 {
     if (! supportsSubPixelPositions())
         return alphaMapForGlyph(glyph, t);
     QImage i = alphaMapForGlyph(glyph, subPixelPosition);
     if (t.type() > QTransform::TxTranslate)
         i = i.transformed(t).convertToFormat(QImage::Format_Indexed8);
     Q_ASSERT(i.depth() <= 8); // To verify that transformed didn't change the format...
     return i;
 }
alphaRGBMapForGlyph()
QImage QFontEngine::alphaRGBMapForGlyph (glyph_t glyph, QFixed subPixelPosition, int margin, const QTransform & t) virtual
Reimplemented in QFontEngineFT, QFontEngineWin, QFontEngineDirectWrite, QCoreTextFontEngine, and QFontEngineMac.
Definition at line 627 of file qfontengine.cpp.
Referenced by QRawFont::alphaMapForGlyph(), QFontEngineFT::alphaRGBMapForGlyph(), and QTextureGlyphCache::textureMapForGlyph().
 {
     QImage alphaMask = alphaMapForGlyph(glyph, t);
     QImage rgbMask(alphaMask.width(), alphaMask.height(), QImage::Format_RGB32);
     QVector<QRgb> colorTable = alphaMask.colorTable();
     for (int y=0; y<alphaMask.height(); ++y) {
         uint *dst = (uint *) rgbMask.scanLine(y);
         uchar *src = (uchar *) alphaMask.scanLine(y);
         for (int x=0; x<alphaMask.width(); ++x) {
             int val = qAlpha(colorTable.at(src[x]));
             dst[x] = qRgb(val, val, val);
         }
     }
     return rgbMask;
 }
ascent()
virtual QFixed QFontEngine::ascent () const pure virtual
Implemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineXLFD, QFontEngineDirectWrite, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Referenced by QPainterPath::addText(), QFontMetrics::ascent(), QRawFont::ascent(), QFontMetricsF::ascent(), QGLGlyphCache::cacheGlyphs(), QTextLine::draw(), QPaintEnginePrivate::drawBoxTextItem(), drawTextItemDecoration(), QTextEngine::fontEngine(), hb_getFontMetric(), QFontMetrics::height(), QFontMetricsF::height(), QFontMetrics::lineSpacing(), QFontMetricsF::lineSpacing(), properties(), QScriptLine::setDefaultHeight(), QTextEngine::shapeTextWithHarfbuzz(), QFontMetrics::xHeight(), and QFontMetricsF::xHeight().
averageCharWidth()
QFixed QFontEngine::averageCharWidth () const virtual
Reimplemented in QFontEngineMulti, QFontEngineFT, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Definition at line 257 of file qfontengine.cpp.
Referenced by QFontMetrics::averageCharWidth(), QRawFont::averageCharWidth(), QFontMetricsF::averageCharWidth(), QFontEngineFT::averageCharWidth(), and QTextLine::layout_helper().
 {
     QGlyphLayoutArray<8> glyphs;
     int nglyphs = 7;
     QChar x((ushort)'x');
     stringToCMap(&x, 1, &glyphs, &nglyphs, QTextEngine::GlyphIndicesOnly);
     glyph_metrics_t bb = const_cast<QFontEngine *>(this)->boundingBox(glyphs.glyphs[0]);
     return bb.xoff;
 }
boundingBox() [1/3]
virtual glyph_metrics_t QFontEngine::boundingBox (const QGlyphLayout & glyphs) pure virtual
Implemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineXLFD, QFontEngineDirectWrite, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Referenced by addBitmapFontToPath(), QFontEngineDirectWrite::alphaMapBoundingBox(), alphaMapForGlyph(), alphaMapFromPath(), averageCharWidth(), boundingBox(), QTextEngine::boundingBox(), QFontMetrics::boundingRect(), QFontMetricsF::boundingRect(), QGLGlyphCache::cacheGlyphs(), QPainterPrivate::drawGlyphs(), QRasterPaintEngine::drawTextItem(), QVGFontEngineCleaner::fontEngineDestroyed(), getGlyphBearings(), getUnscaledGlyph(), hb_getGlyphMetrics(), lastRightBearing(), QFontEngineQPF::loadGlyph(), qt_draw_decoration_for_glyphs(), tightBoundingBox(), and xHeight().
boundingBox() [2/3]
virtual glyph_metrics_t QFontEngine::boundingBox (glyph_t glyph) pure virtual
Implemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineXLFD, QFontEngineDirectWrite, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
boundingBox() [3/3]
glyph_metrics_t QFontEngine::boundingBox (glyph_t glyph, const QTransform & matrix) virtual
Reimplemented in QFontEngineFT, and QFontEngineWin.
Definition at line 236 of file qfontengine.cpp.
 {
     glyph_metrics_t metrics = boundingBox(glyph);
     if (matrix.type() > QTransform::TxTranslate) {
         return metrics.transformed(matrix);
     }
     return metrics;
 }
canRender()
virtual bool QFontEngine::canRender (const QChar * string, int len) pure virtual
Implemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineMacMulti, QFontEngineXLFD, QFontEngineDirectWrite, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Referenced by QTextEngine::elidedText(), hb_canRender(), QFontMetrics::inFont(), QFontMetricsF::inFont(), QFontMetrics::inFontUcs4(), QFontMetricsF::inFontUcs4(), and QRawFont::supportsCharacter().
cloneWithSize()
virtual QFontEngine* QFontEngine::cloneWithSize (qreal) const inline virtual
Reimplemented in QFontEngineFT, QFontEngineX11FT, QFontEngineWin, QFontEngineDirectWrite, and QCoreTextFontEngine.
Definition at line 239 of file qfontengine_p.h.
Referenced by QFontEngineX11FT::QFontEngineX11FT(), and QRawFont::setPixelSize().
 { return 0; }
convertToPostscriptFontFamilyName()
QByteArray QFontEngine::convertToPostscriptFontFamilyName (const QByteArray & fontFamily) static
Definition at line 1104 of file qfontengine.cpp.
Referenced by QFontEngineWin::properties(), QFontEngineMac::properties(), properties(), and QFontEngineFT::properties().
 {
     QByteArray f = family;
     f.replace(' ', "");
     f.replace('(', "");
     f.replace(')', "");
     f.replace('<', "");
     f.replace('>', "");
     f.replace('[', "");
     f.replace(']', "");
     f.replace('{', "");
     f.replace('}', "");
     f.replace('/', "");
     f.replace('%', "");
     return f;
 }
descent()
virtual QFixed QFontEngine::descent () const pure virtual
Implemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineXLFD, QFontEngineDirectWrite, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Referenced by QGLGlyphCache::cacheGlyphs(), QFontMetrics::descent(), QRawFont::descent(), QFontMetricsF::descent(), QTextLine::draw(), drawTextItemDecoration(), QTextEngine::fontEngine(), hb_getFontMetric(), QFontMetrics::height(), QFontMetricsF::height(), QFontMetrics::lineSpacing(), QFontMetricsF::lineSpacing(), properties(), QScriptLine::setDefaultHeight(), and QTextEngine::shapeTextWithHarfbuzz().
doKerning()
void QFontEngine::doKerning (QGlyphLayout * glyphs, QTextEngine::ShaperFlags flags) const virtual
Reimplemented in QFontEngineMulti, QFontEngineFT, QFontEngineQPF, and QFontEngineMacMulti.
Definition at line 785 of file qfontengine.cpp.
Referenced by QFontEngineQPF::doKerning(), QFontEngineFT::doKerning(), loadKerningPairs(), and QTextEngine::shapeTextWithHarfbuzz().
 {
     int numPairs = kerning_pairs.size();
     if(!numPairs)
         return;
     const KernPair *pairs = kerning_pairs.constData();
     if(flags & QTextEngine::DesignMetrics) {
         for(int i = 0; i < glyphs->numGlyphs - 1; ++i)
             glyphs->advances_x[i] += kerning(glyphs->glyphs[i], glyphs->glyphs[i+1] , pairs, numPairs);
     } else {
         for(int i = 0; i < glyphs->numGlyphs - 1; ++i)
             glyphs->advances_x[i] += qRound(kerning(glyphs->glyphs[i], glyphs->glyphs[i+1] , pairs, numPairs));
     }
 }
emSquareSize()
virtual QFixed QFontEngine::emSquareSize () const inline virtual
Reimplemented in QFontEngineQPF, QFontEngineFT, QCoreTextFontEngine, QFontEngineDirectWrite, and QFontEngineWin.
Definition at line 171 of file qfontengine_p.h.
Referenced by QFontEngineDirectWrite::emSquareSize(), QFontEngineQPF::emSquareSize(), harfbuzzFont(), and QRawFont::unitsPerEm().
 { return ascent(); }
faceId()
virtual FaceId QFontEngine::faceId () const inline virtual
Reimplemented in QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QCoreTextFontEngine, QFontEngineXLFD, QFontEngineMac, and QFontEngineWin.
Definition at line 162 of file qfontengine_p.h.
Referenced by QPdfBaseEnginePrivate::drawTextItem().
 { return FaceId(); }
getCMap()
const uchar * QFontEngine::getCMap (const uchar * table, uint tableSize, bool * isSymbolFont, int * cmapSize) static
Definition at line 878 of file qfontengine.cpp.
Referenced by QFontEngineWin::getCMap(), QFontEngineQPA::QFontEngineQPA(), QFontEngineQPF::QFontEngineQPF(), and QFontEngineMac::stringToCMap().
 {
     const uchar *header = table;
     if (tableSize < 4)
         return 0;
     const uchar *endPtr = table + tableSize;
     // version check
     if (qFromBigEndian<quint16>(header) != 0)
         return 0;
     unsigned short numTables = qFromBigEndian<quint16>(header + 2);
     const uchar *maps = table + 4;
     if (maps + 8 * numTables > endPtr)
         return 0;
     enum {
         Invalid,
         AppleRoman,
         Symbol,
         Unicode11,
         Unicode,
         MicrosoftUnicode,
         MicrosoftUnicodeExtended
     };
     int symbolTable = -1;
     int tableToUse = -1;
     int score = Invalid;
     for (int n = 0; n < numTables; ++n) {
         const quint16 platformId = qFromBigEndian<quint16>(maps + 8 * n);
         const quint16 platformSpecificId = qFromBigEndian<quint16>(maps + 8 * n + 2);
         switch (platformId) {
         case 0: // Unicode
             if (score < Unicode &&
                 (platformSpecificId == 0 ||
                  platformSpecificId == 2 ||
                  platformSpecificId == 3)) {
                 tableToUse = n;
                 score = Unicode;
             } else if (score < Unicode11 && platformSpecificId == 1) {
                 tableToUse = n;
                 score = Unicode11;
             }
             break;
         case 1: // Apple
             if (score < AppleRoman && platformSpecificId == 0) { // Apple Roman
                 tableToUse = n;
                 score = AppleRoman;
             }
             break;
         case 3: // Microsoft
             switch (platformSpecificId) {
             case 0:
                 symbolTable = n;
                 if (score < Symbol) {
                     tableToUse = n;
                     score = Symbol;
                 }
                 break;
             case 1:
                 if (score < MicrosoftUnicode) {
                     tableToUse = n;
                     score = MicrosoftUnicode;
                 }
                 break;
             case 0xa:
                 if (score < MicrosoftUnicodeExtended) {
                     tableToUse = n;
                     score = MicrosoftUnicodeExtended;
                 }
                 break;
             default:
                 break;
             }
         default:
             break;
         }
     }
     if(tableToUse < 0)
         return 0;
 resolveTable:
     *isSymbolFont = (symbolTable > -1);
     unsigned int unicode_table = qFromBigEndian<quint32>(maps + 8*tableToUse + 4);
     if (!unicode_table || unicode_table + 8 > tableSize)
         return 0;
     // get the header of the unicode table
     header = table + unicode_table;
     unsigned short format = qFromBigEndian<quint16>(header);
     unsigned int length;
     if(format < 8)
         length = qFromBigEndian<quint16>(header + 2);
     else
         length = qFromBigEndian<quint32>(header + 4);
     if (table + unicode_table + length > endPtr)
         return 0;
     *cmapSize = length;
     // To support symbol fonts that contain a unicode table for the symbol area
     // we check the cmap tables and fall back to symbol font unless that would
     // involve losing information from the unicode table
     if (symbolTable > -1 && ((score == Unicode) || (score == Unicode11))) {
         const uchar *selectedTable = table + unicode_table;
         // Check that none of the latin1 range are in the unicode table
         bool unicodeTableHasLatin1 = false;
         for (int uc=0x00; uc<0x100; ++uc) {
             if (getTrueTypeGlyphIndex(selectedTable, uc) != 0) {
                 unicodeTableHasLatin1 = true;
                 break;
             }
         }
         // Check that at least one symbol char is in the unicode table
         bool unicodeTableHasSymbols = false;
         if (!unicodeTableHasLatin1) {
             for (int uc=0xf000; uc<0xf100; ++uc) {
                 if (getTrueTypeGlyphIndex(selectedTable, uc) != 0) {
                     unicodeTableHasSymbols = true;
                     break;
                 }
             }
         }
         // Fall back to symbol table
         if (!unicodeTableHasLatin1 && unicodeTableHasSymbols) {
             tableToUse = symbolTable;
             score = Symbol;
             goto resolveTable;
         }
     }
     return table + unicode_table;
 }
getGlyphBearings()
void QFontEngine::getGlyphBearings (glyph_t glyph, qreal * leftBearing = 0, qreal * rightBearing = 0) virtual
Reimplemented in QFontEngineMulti, and QFontEngineWin.
Definition at line 385 of file qfontengine.cpp.
Referenced by QFontEngineWin::getGlyphBearings(), QFontMetrics::leftBearing(), QFontMetricsF::leftBearing(), QFontMetrics::rightBearing(), and QFontMetricsF::rightBearing().
 {
     glyph_metrics_t gi = boundingBox(glyph);
     bool isValid = gi.isValid();
     if (leftBearing != 0)
         *leftBearing = isValid ? gi.x.toReal() : qreal(0.0);
     if (rightBearing != 0)
         *rightBearing = isValid ? (gi.xoff - gi.x - gi.width).toReal() : qreal(0.0);
 }
getGlyphPositions()
void QFontEngine::getGlyphPositions (const QGlyphLayout & glyphs, const QTransform & matrix, QTextItem::RenderFlags flags, QVarLengthArray< glyph_t > & glyphs_out, QVarLengthArray< QFixedPoint > & positions)
Definition at line 269 of file qfontengine.cpp.
Referenced by addOutlineToPath(), QFontEngineBox::addOutlineToPath(), QFontEngineBox::boundingBox(), QProxyFontEngine::canRender(), QFontEngineMac::draw(), QFontEngineQPF::draw(), draw_text_item_win(), QPaintEnginePrivate::drawBoxTextItem(), QRasterPaintEngine::drawCachedGlyphs(), QX11PaintEngine::drawFreetype(), QGL2PaintEngineEx::drawTextItem(), QOpenGLPaintEngine::drawTextItem(), QVGPaintEngine::drawTextItem(), QRasterPaintEngine::drawTextItem(), QPdfBaseEnginePrivate::drawTextItem(), QX11PaintEngine::drawXLFD(), QStaticTextPrivate::get(), and QTextLine::glyphs().
 {
     QFixed xpos;
     QFixed ypos;
     const bool transform = matrix.m11() != 1.
                            || matrix.m12() != 0.
                            || matrix.m21() != 0.
                            || matrix.m22() != 1.;
     if (!transform) {
         xpos = QFixed::fromReal(matrix.dx());
         ypos = QFixed::fromReal(matrix.dy());
     }
     int current = 0;
     if (flags & QTextItem::RightToLeft) {
         int i = glyphs.numGlyphs;
         int totalKashidas = 0;
         while(i--) {
             if (glyphs.attributes[i].dontPrint)
                 continue;
             xpos += glyphs.advances_x[i] + QFixed::fromFixed(glyphs.justifications[i].space_18d6);
             ypos += glyphs.advances_y[i];
             totalKashidas += glyphs.justifications[i].nKashidas;
         }
         positions.resize(glyphs.numGlyphs+totalKashidas);
         glyphs_out.resize(glyphs.numGlyphs+totalKashidas);
         i = 0;
         while(i < glyphs.numGlyphs) {
             if (glyphs.attributes[i].dontPrint) {
                 ++i;
                 continue;
             }
             xpos -= glyphs.advances_x[i];
             ypos -= glyphs.advances_y[i];
             QFixed gpos_x = xpos + glyphs.offsets[i].x;
             QFixed gpos_y = ypos + glyphs.offsets[i].y;
             if (transform) {
                 QPointF gpos(gpos_x.toReal(), gpos_y.toReal());
                 gpos = gpos * matrix;
                 gpos_x = QFixed::fromReal(gpos.x());
                 gpos_y = QFixed::fromReal(gpos.y());
             }
             positions[current].x = gpos_x;
             positions[current].y = gpos_y;
             glyphs_out[current] = glyphs.glyphs[i];
             ++current;
             if (glyphs.justifications[i].nKashidas) {
                 QChar ch(0x640); // Kashida character
                 QGlyphLayoutArray<8> g;
                 int nglyphs = 7;
                 stringToCMap(&ch, 1, &g, &nglyphs, 0);
                 for (uint k = 0; k < glyphs.justifications[i].nKashidas; ++k) {
                     xpos -= g.advances_x[0];
                     ypos -= g.advances_y[0];
                     QFixed gpos_x = xpos + glyphs.offsets[i].x;
                     QFixed gpos_y = ypos + glyphs.offsets[i].y;
                     if (transform) {
                         QPointF gpos(gpos_x.toReal(), gpos_y.toReal());
                         gpos = gpos * matrix;
                         gpos_x = QFixed::fromReal(gpos.x());
                         gpos_y = QFixed::fromReal(gpos.y());
                     }
                     positions[current].x = gpos_x;
                     positions[current].y = gpos_y;
                     glyphs_out[current] = g.glyphs[0];
                     ++current;
                 }
             } else {
                 xpos -= QFixed::fromFixed(glyphs.justifications[i].space_18d6);
             }
             ++i;
         }
     } else {
         positions.resize(glyphs.numGlyphs);
         glyphs_out.resize(glyphs.numGlyphs);
         int i = 0;
         if (!transform) {
             while (i < glyphs.numGlyphs) {
                 if (!glyphs.attributes[i].dontPrint) {
                     positions[current].x = xpos + glyphs.offsets[i].x;
                     positions[current].y = ypos + glyphs.offsets[i].y;
                     glyphs_out[current] = glyphs.glyphs[i];
                     xpos += glyphs.advances_x[i] + QFixed::fromFixed(glyphs.justifications[i].space_18d6);
                     ypos += glyphs.advances_y[i];
                     ++current;
                 }
                 ++i;
             }
         } else {
             while (i < glyphs.numGlyphs) {
                 if (!glyphs.attributes[i].dontPrint) {
                     QFixed gpos_x = xpos + glyphs.offsets[i].x;
                     QFixed gpos_y = ypos + glyphs.offsets[i].y;
                     QPointF gpos(gpos_x.toReal(), gpos_y.toReal());
                     gpos = gpos * matrix;
                     positions[current].x = QFixed::fromReal(gpos.x());
                     positions[current].y = QFixed::fromReal(gpos.y());
                     glyphs_out[current] = glyphs.glyphs[i];
                     xpos += glyphs.advances_x[i] + QFixed::fromFixed(glyphs.justifications[i].space_18d6);
                     ypos += glyphs.advances_y[i];
                     ++current;
                 }
                 ++i;
             }
         }
     }
     positions.resize(current);
     glyphs_out.resize(current);
     Q_ASSERT(positions.size() == glyphs_out.size());
 }
getPointInOutline()
HB_Error QFontEngine::getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed * xpos, HB_Fixed * ypos, hb_uint32 * nPoints) virtual
Reimplemented in QFontEngineFT, and QFontEngineQPF.
Definition at line 144 of file qfontengine.cpp.
Referenced by hb_getPointInOutline().
 {
     Q_UNUSED(glyph)
     Q_UNUSED(flags)
     Q_UNUSED(point)
     Q_UNUSED(xpos)
     Q_UNUSED(ypos)
     Q_UNUSED(nPoints)
     return HB_Err_Not_Covered;
 }
getSfntTable()
QByteArray QFontEngine::getSfntTable (uint tag) const
Definition at line 719 of file qfontengine.cpp.
Referenced by QRawFont::fontTable(), glyphCount(), loadKerningPairs(), loadSingleEngine(), QFontEngineQPF::QFontEngineQPF(), and QFontSubset::toTruetype().
 {
     QByteArray table;
     uint len = 0;
     if (!getSfntTableData(tag, 0, &len))
         return table;
     if (!len)
         return table;
     table.resize(len);
     if (!getSfntTableData(tag, reinterpret_cast<uchar *>(table.data()), &len))
         return QByteArray();
     return table;
 }
getSfntTableData()
virtual bool QFontEngine::getSfntTableData (uint , uchar * , uint *) const inline virtual
Reimplemented in QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QCoreTextFontEngine, QFontEngineXLFD, QFontEngineDirectWrite, and QFontEngineWin.
Definition at line 153 of file qfontengine_p.h.
Referenced by getSfntTable(), and hb_getSFntTable().
 { return false; }
getTrueTypeGlyphIndex()
quint32 QFontEngine::getTrueTypeGlyphIndex (const uchar * cmap, uint unicode) static
Definition at line 1020 of file qfontengine.cpp.
Referenced by QFontEngineQPA::canRender(), QFontEngineQPF::canRender(), getCMap(), QFontEngineMac::stringToCMap(), QFontEngineQPA::stringToCMap(), and QFontEngineQPF::stringToCMap().
 {
     unsigned short format = qFromBigEndian<quint16>(cmap);
     if (format == 0) {
         if (unicode < 256)
             return (int) *(cmap+6+unicode);
     } else if (format == 4) {
         /* some fonts come with invalid cmap tables, where the last segment
            specified end = start = rangeoffset = 0xffff, delta = 0x0001
            Since 0xffff is never a valid Unicode char anyway, we just get rid of the issue
            by returning 0 for 0xffff
         */
         if(unicode >= 0xffff)
             return 0;
         quint16 segCountX2 = qFromBigEndian<quint16>(cmap + 6);
         const unsigned char *ends = cmap + 14;
         int i = 0;
         for (; i < segCountX2/2 && qFromBigEndian<quint16>(ends + 2*i) < unicode; i++) {}
         const unsigned char *idx = ends + segCountX2 + 2 + 2*i;
         quint16 startIndex = qFromBigEndian<quint16>(idx);
         if (startIndex > unicode)
             return 0;
         idx += segCountX2;
         qint16 idDelta = (qint16)qFromBigEndian<quint16>(idx);
         idx += segCountX2;
         quint16 idRangeoffset_t = (quint16)qFromBigEndian<quint16>(idx);
         quint16 glyphIndex;
         if (idRangeoffset_t) {
             quint16 id = qFromBigEndian<quint16>(idRangeoffset_t + 2*(unicode - startIndex) + idx);
             if (id)
                 glyphIndex = (idDelta + id) % 0x10000;
             else
                 glyphIndex = 0;
         } else {
             glyphIndex = (idDelta + unicode) % 0x10000;
         }
         return glyphIndex;
     } else if (format == 6) {
         quint16 tableSize = qFromBigEndian<quint16>(cmap + 2);
         quint16 firstCode6 = qFromBigEndian<quint16>(cmap + 6);
         if (unicode < firstCode6)
             return 0;
         quint16 entryCount6 = qFromBigEndian<quint16>(cmap + 8);
         if (entryCount6 * 2 + 10 > tableSize)
             return 0;
         quint16 sentinel6 = firstCode6 + entryCount6;
         if (unicode >= sentinel6)
             return 0;
         quint16 entryIndex6 = unicode - firstCode6;
         return qFromBigEndian<quint16>(cmap + 10 + (entryIndex6 * 2));
     } else if (format == 12) {
         quint32 nGroups = qFromBigEndian<quint32>(cmap + 12);
         cmap += 16; // move to start of groups
         int left = 0, right = nGroups - 1;
         while (left <= right) {
             int middle = left + ( ( right - left ) >> 1 );
             quint32 startCharCode = qFromBigEndian<quint32>(cmap + 12*middle);
             if(unicode < startCharCode)
                 right = middle - 1;
             else {
                 quint32 endCharCode = qFromBigEndian<quint32>(cmap + 12*middle + 4);
                 if(unicode <= endCharCode)
                     return qFromBigEndian<quint32>(cmap + 12*middle + 8) + unicode - startCharCode;
                 left = middle + 1;
             }
         }
     } else {
         qDebug("cmap table of format %d not implemented", format);
     }
     return 0;
 }
getUnscaledGlyph()
void QFontEngine::getUnscaledGlyph (glyph_t glyph, QPainterPath * path, glyph_metrics_t * metrics) virtual
Reimplemented in QFontEngineFT, QCoreTextFontEngine, QFontEngineXLFD, QFontEngineMac, and QFontEngineWin.
Definition at line 710 of file qfontengine.cpp.
Referenced by QVGFontEngineCleaner::fontEngineDestroyed(), QFontSubset::toTruetype(), and QFontSubset::type1AddedGlyphs().
 {
     *metrics = boundingBox(glyph);
     QFixedPoint p;
     p.x = 0;
     p.y = 0;
     addGlyphsToPath(&glyph, &p, 1, path, QFlag(0));
 }
glyphCache()
QFontEngineGlyphCache * QFontEngine::glyphCache (void * key, QFontEngineGlyphCache::Type type, const QTransform & transform) const
Definition at line 752 of file qfontengine.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs(), and QRasterPaintEngine::drawCachedGlyphs().
 {
     for (QLinkedList<GlyphCacheEntry>::const_iterator it = m_glyphCaches.constBegin(), end = m_glyphCaches.constEnd(); it != end; ++it) {
         QFontEngineGlyphCache *c = it->cache.data();
         if (key == it->context
             && type == c->cacheType()
             && qtransform_equals_no_translate(c->m_transform, transform)) {
             return c;
         }
     }
     return 0;
 }
glyphCount()
int QFontEngine::glyphCount () const virtual
Reimplemented in QFontEngineFT, QFontEngineQPF, QFontEngineQPA, and QProxyFontEngine.
Definition at line 870 of file qfontengine.cpp.
Referenced by QFontEngineMacMulti::stringToCMap().
 {
     QByteArray maxpTable = getSfntTable(MAKE_TAG('m', 'a', 'x', 'p'));
     if (maxpTable.size() < 6)
         return 0;
     return qFromBigEndian<quint16>(reinterpret_cast<const uchar *>(maxpTable.constData() + 4));
 }
grayPalette()
static const QVector<QRgb>& QFontEngine::grayPalette () static protected
Referenced by Q_GLOBAL_STATIC_WITH_INITIALIZER().
harfbuzzFace()
HB_Face QFontEngine::harfbuzzFace () const
Definition at line 227 of file qfontengine.cpp.
Referenced by QFontconfigDatabase::fontEngine(), QBasicUnixFontDatabase::fontEngine(), loadEngine(), QTextEngine::shapeText(), QTextEngine::shapeTextWithHarfbuzz(), and tryPatternLoad().
 {
     if (!hbFace) {
         hbFace = qHBNewFace(const_cast<QFontEngine *>(this), hb_getSFntTable);
         Q_CHECK_PTR(hbFace);
     }
     return hbFace;
 }
harfbuzzFont()
HB_Font QFontEngine::harfbuzzFont () const
Definition at line 215 of file qfontengine.cpp.
Referenced by QTextEngine::shapeTextWithHarfbuzz().
 {
     if (!hbFont.x_ppem) {
         QFixed emSquare = emSquareSize();
         hbFont.x_ppem = fontDef.pixelSize;
         hbFont.y_ppem = fontDef.pixelSize * fontDef.stretch / 100;
         hbFont.x_scale = (QFixed(hbFont.x_ppem * (1 << 16)) / emSquare).value();
         hbFont.y_scale = (QFixed(hbFont.y_ppem * (1 << 16)) / emSquare).value();
     }
     return &hbFont;
 }
lastRightBearing()
QFixed QFontEngine::lastRightBearing (const QGlyphLayout & glyphs, bool round = false) protected
Definition at line 1133 of file qfontengine.cpp.
Referenced by QFontEngineMac::boundingBox(), and QFontEngineDirectWrite::boundingBox().
 {
     if (glyphs.numGlyphs >= 1) {
         glyph_t glyph = glyphs.glyphs[glyphs.numGlyphs - 1];
         glyph_metrics_t gi = boundingBox(glyph);
         if (gi.isValid())
             return round ? QFixed(qRound(gi.xoff - gi.x - gi.width))
                          : QFixed(gi.xoff - gi.x - gi.width);
     }
     return 0;
 }
leading()
virtual QFixed QFontEngine::leading () const pure virtual
Implemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineXLFD, QFontEngineDirectWrite, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Referenced by QTextEngine::fontEngine(), QFontMetrics::leading(), QRawFont::leading(), QFontMetricsF::leading(), QFontMetrics::lineSpacing(), QFontMetricsF::lineSpacing(), properties(), QScriptLine::setDefaultHeight(), and QTextEngine::shapeTextWithHarfbuzz().
lineThickness()
QFixed QFontEngine::lineThickness () const virtual
Reimplemented in QFontEngineMulti, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QProxyFontEngine, QFontEngineDirectWrite, and QFontEngineWin.
Definition at line 197 of file qfontengine.cpp.
Referenced by QPainterPath::addText(), QFontEngineBox::boundingBox(), QFontEngineMac::draw(), QTextLine::draw(), QPaintEnginePrivate::drawBoxTextItem(), QPdfBaseEnginePrivate::drawTextItem(), drawTextItemDecoration(), QFontEngineMac::imageForGlyph(), QFontEngineWin::lineThickness(), QFontEngineDirectWrite::lineThickness(), QFontMetrics::lineWidth(), QFontMetricsF::lineWidth(), properties(), and underlinePosition().
 {
     // ad hoc algorithm
     int score = fontDef.weight * fontDef.pixelSize;
     int lw = score / 700;
     // looks better with thicker line for small pointsizes
     if (lw < 2 && score >= 1050) lw = 2;
     if (lw == 0) lw = 1;
     return lw;
 }
loadKerningPairs()
void QFontEngine::loadKerningPairs (QFixed scalingFactor)
Definition at line 802 of file qfontengine.cpp.
Referenced by QFontEngineQPF::doKerning().
 {
     kerning_pairs.clear();
     QByteArray tab = getSfntTable(MAKE_TAG('k', 'e', 'r', 'n'));
     if (tab.isEmpty())
         return;
     const uchar *table = reinterpret_cast<const uchar *>(tab.constData());
     unsigned short version = qFromBigEndian<quint16>(table);
     if (version != 0) {
 //        qDebug("wrong version");
        return;
     }
     unsigned short numTables = qFromBigEndian<quint16>(table + 2);
     {
         int offset = 4;
         for(int i = 0; i < numTables; ++i) {
             if (offset + 6 > tab.size()) {
 //                qDebug("offset out of bounds");
                 goto end;
             }
             const uchar *header = table + offset;
             ushort version = qFromBigEndian<quint16>(header);
             ushort length = qFromBigEndian<quint16>(header+2);
             ushort coverage = qFromBigEndian<quint16>(header+4);
 //            qDebug("subtable: version=%d, coverage=%x",version, coverage);
             if(version == 0 && coverage == 0x0001) {
                 if (offset + length > tab.size()) {
 //                    qDebug("length ouf ot bounds");
                     goto end;
                 }
                 const uchar *data = table + offset + 6;
                 ushort nPairs = qFromBigEndian<quint16>(data);
                 if(nPairs * 6 + 8 > length - 6) {
 //                    qDebug("corrupt table!");
                     // corrupt table
                     goto end;
                 }
                 int off = 8;
                 for(int i = 0; i < nPairs; ++i) {
                     QFontEngine::KernPair p;
                     p.left_right = (((uint)qFromBigEndian<quint16>(data+off)) << 16) + qFromBigEndian<quint16>(data+off+2);
                     p.adjust = QFixed(((int)(short)qFromBigEndian<quint16>(data+off+4))) / scalingFactor;
                     kerning_pairs.append(p);
                     off += 6;
                 }
             }
             offset += length;
         }
     }
 end:
     qSort(kerning_pairs);
 //    for (int i = 0; i < kerning_pairs.count(); ++i)
 //        qDebug() << 'i' << i << "left_right" << hex << kerning_pairs.at(i).left_right;
 }
maxCharWidth()
virtual qreal QFontEngine::maxCharWidth () const pure virtual
Implemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineXLFD, QFontEngineDirectWrite, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Referenced by addGlyphsToPath(), QRawFont::maxCharWidth(), QFontMetrics::maxWidth(), QFontMetricsF::maxWidth(), QTextureGlyphCache::populate(), properties(), and QFontSubset::toTruetype().
minLeftBearing()
virtual qreal QFontEngine::minLeftBearing () const inline virtual
Reimplemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineXLFD, QCoreTextFontEngine, QFontEngineWin, and QProxyFontEngine.
Definition at line 226 of file qfontengine_p.h.
Referenced by QFontMetrics::minLeftBearing(), QFontMetricsF::minLeftBearing(), and QFontSubset::toTruetype().
 { return qreal(); }
minRightBearing()
virtual qreal QFontEngine::minRightBearing () const inline virtual
Reimplemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineXLFD, QCoreTextFontEngine, QFontEngineWin, and QProxyFontEngine.
Definition at line 227 of file qfontengine_p.h.
Referenced by QTextLine::layout_helper(), QFontMetrics::minRightBearing(), QFontMetricsF::minRightBearing(), and QFontSubset::toTruetype().
 { return qreal(); }
name()
virtual const char* QFontEngine::name () const pure virtual
Implemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineMacMulti, QCoreTextFontEngineMulti, QFontEngineXLFD, QFontEngineDirectWrite, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Referenced by qt_x11_set_fallback_font_family(), and QFontDialogPrivate::setFont().
properties()
QFontEngine::Properties QFontEngine::properties () const virtual
Reimplemented in QFontEngineFT, QFontEngineXLFD, QFontEngineMac, and QFontEngineWin.
Definition at line 689 of file qfontengine.cpp.
Referenced by QPdfEnginePrivate::embedFont(), QFontEngineXLFD::faceId(), QVGFontEngineCleaner::fontEngineDestroyed(), QFontSubset::toTruetype(), QFontSubset::toType1(), QFontSubset::type1AddedGlyphs(), and QFontSubset::widthArray().
 {
     Properties p;
     QByteArray psname = QFontEngine::convertToPostscriptFontFamilyName(fontDef.family.toUtf8());
     psname += '-';
     psname += QByteArray::number(fontDef.style);
     psname += '-';
     psname += QByteArray::number(fontDef.weight);
     p.postscriptName = psname;
     p.ascent = ascent();
     p.descent = descent();
     p.leading = leading();
     p.emSquare = p.ascent;
     p.boundingBox = QRectF(0, -p.ascent.toReal(), maxCharWidth(), (p.ascent + p.descent).toReal());
     p.italicAngle = 0;
     p.capHeight = p.ascent;
     p.lineWidth = lineThickness();
     return p;
 }
recalcAdvances()
virtual void QFontEngine::recalcAdvances (QGlyphLayout * , QTextEngine::ShaperFlags) const inline virtual
This is a callback from harfbuzz. The font engine uses the font-system in use to find out the advances of each glyph and set it on the layout.
Reimplemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineMacMulti, QFontEngineXLFD, QFontEngineDirectWrite, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Definition at line 180 of file qfontengine_p.h.
Referenced by QRawFont::advancesForGlyphIndexes(), and hb_getAdvances().
 {}
removeGlyphFromCache()
void QFontEngine::removeGlyphFromCache (glyph_t) virtual
Reimplemented in QFontEngineFT.
Definition at line 685 of file qfontengine.cpp.
Referenced by QFontEngineQPF::loadGlyph().
 {
 }
setGlyphCache()
void QFontEngine::setGlyphCache (void * key, QFontEngineGlyphCache * data)
Definition at line 733 of file qfontengine.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs(), and QRasterPaintEngine::drawCachedGlyphs().
 {
     Q_ASSERT(data);
     GlyphCacheEntry entry;
     entry.context = key;
     entry.cache = data;
     if (m_glyphCaches.contains(entry))
         return;
     // Limit the glyph caches to 4. This covers all 90 degree rotations and limits
     // memory use when there is continuous or random rotation
     if (m_glyphCaches.size() == 4)
         m_glyphCaches.removeLast();
     m_glyphCaches.push_front(entry);
 }
stringToCMap()
virtual bool QFontEngine::stringToCMap (const QChar * str, int len, QGlyphLayout * glyphs, int * nglyphs, QTextEngine::ShaperFlags flags) const pure virtual
Implemented in QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineMacMulti, QCoreTextFontEngineMulti, QFontEngineXLFD, QFontEngineDirectWrite, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Referenced by averageCharWidth(), QFontMetrics::boundingRect(), QFontMetricsF::boundingRect(), QFontMetrics::charWidth(), QPainter::drawText(), QTextEngine::elidedText(), QFontInfo::fixedPitch(), getGlyphPositions(), QFontSubset::getReverseMap(), QRawFont::glyphIndexesForChars(), hb_stringToGlyphs(), QFontMetrics::leftBearing(), QFontMetricsF::leftBearing(), QFontMetrics::rightBearing(), QFontMetricsF::rightBearing(), QTextEngine::shapeTextWithCE(), QFontEngineQPF::stringToCMap(), QFontEngineMulti::stringToCMap(), stringToGlyphs(), QFontMetrics::width(), QFontMetricsF::width(), and xHeight().
supportsSubPixelPositions()
virtual bool QFontEngine::supportsSubPixelPositions () const inline virtual
Reimplemented in QFontEngineFT, QFontEngineDirectWrite, and QCoreTextFontEngine.
Definition at line 169 of file qfontengine_p.h.
Referenced by alphaMapForGlyph(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QTextLine::glyphs(), and QTextureGlyphCache::populate().
 { return false; }
synthesized()
virtual int QFontEngine::synthesized () const inline virtual
Reimplemented in QFontEngineFT, QFontEngineXLFD, QCoreTextFontEngine, QFontEngineMac, and QFontEngineWin.
Definition at line 168 of file qfontengine_p.h.
Referenced by QPdfEnginePrivate::drawTextItem(), and QPdfBaseEnginePrivate::drawTextItem().
 { return 0; }
tightBoundingBox()
glyph_metrics_t QFontEngine::tightBoundingBox (const QGlyphLayout & glyphs)
Definition at line 395 of file qfontengine.cpp.
Referenced by QTextEngine::tightBoundingBox().
 {
     glyph_metrics_t overall;
     QFixed ymax = 0;
     QFixed xmax = 0;
     for (int i = 0; i < glyphs.numGlyphs; i++) {
         glyph_metrics_t bb = boundingBox(glyphs.glyphs[i]);
         QFixed x = overall.xoff + glyphs.offsets[i].x + bb.x;
         QFixed y = overall.yoff + glyphs.offsets[i].y + bb.y;
         overall.x = qMin(overall.x, x);
         overall.y = qMin(overall.y, y);
         xmax = qMax(xmax, x + bb.width);
         ymax = qMax(ymax, y + bb.height);
         overall.xoff += bb.xoff;
         overall.yoff += bb.yoff;
     }
     overall.height = qMax(overall.height, ymax - overall.y);
     overall.width = xmax - overall.x;
     return overall;
 }
type()
virtual Type QFontEngine::type () const pure virtual
Implemented in QTestFontEngine, QFontEngineMulti, QFontEngineBox, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, QFontEngineDirectWrite, QFontEngineXLFD, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Referenced by QFontEngineQPF::addOutlineToPath(), draw_text_item_win(), QRasterPaintEngine::drawCachedGlyphs(), QWin32PrintEngine::drawTextItem(), QCoreGraphicsPaintEngine::drawTextItem(), QX11PaintEngine::drawTextItem(), QPdfEnginePrivate::drawTextItem(), QRasterPaintEngine::drawTextItem(), QPdfBaseEngine::drawTextItem(), QPdfBaseEnginePrivate::drawTextItem(), QTextEngine::elidedText(), QFontInfo::exactMatch(), QFont::exactMatch(), QFontDatabase::findFont(), QFont::freetypeFace(), QRawFont::fromFont(), ft_face(), QFontSubset::glyphName(), QTextLine::glyphs(), QFont::handle(), QFontMetrics::inFont(), QFontMetricsF::inFont(), QFontMetrics::inFontUcs4(), QFontMetricsF::inFontUcs4(), QFontMetrics::leftBearing(), QFontMetricsF::leftBearing(), QFont::macFontID(), pointSize(), qgl_use_font(), qt_x11_set_fallback_font_family(), registerFont(), QFontMetrics::rightBearing(), QFontMetricsF::rightBearing(), QTextEngine::shapeText(), QTextEngine::shapeTextMac(), QTextEngine::shapeTextWithHarfbuzz(), QFontEngineMulti::stringToCMap(), QRasterPaintEngine::supportsTransformations(), and QTextureGlyphCache::textureMapForGlyph().
underlinePosition()
QFixed QFontEngine::underlinePosition () const virtual
Reimplemented in QFontEngineMulti, QFontEngineQPF1, QFontEngineFT, QFontEngineQPF, QFontEngineQPA, and QProxyFontEngine.
Definition at line 210 of file qfontengine.cpp.
Referenced by QPainterPath::addText(), QTextLine::draw(), drawTextItemDecoration(), QFontMetrics::underlinePos(), and QFontMetricsF::underlinePos().
 {
     return ((lineThickness() * 2) + 3) / 6;
 }
xHeight()
QFixed QFontEngine::xHeight () const virtual
Reimplemented in QFontEngineMulti, QFontEngineFT, QFontEngineDirectWrite, QFontEngineWin, QProxyFontEngine, QCoreTextFontEngine, and QFontEngineMac.
Definition at line 246 of file qfontengine.cpp.
Referenced by QFontMetrics::xHeight(), QFontEngineWin::xHeight(), QRawFont::xHeight(), QFontMetricsF::xHeight(), and QFontEngineFT::xHeight().
 {
     QGlyphLayoutArray<8> glyphs;
     int nglyphs = 7;
     QChar x((ushort)'x');
     stringToCMap(&x, 1, &glyphs, &nglyphs, QTextEngine::GlyphIndicesOnly);
     glyph_metrics_t bb = const_cast<QFontEngine *>(this)->boundingBox(glyphs.glyphs[0]);
     return bb.height;
 }
Properties
cache_cost
uint QFontEngine::cache_cost
Definition at line 256 of file qfontengine_p.h.
Referenced by QFontCache::insertEngine(), QFontEngineBox::QFontEngineBox(), QFontEngineMulti::QFontEngineMulti(), QFontEngineMultiFT::QFontEngineMultiFT(), QFontEngineMultiWin::QFontEngineMultiWin(), QFontEngineQPA::QFontEngineQPA(), QFontEngineQPF::QFontEngineQPF(), and QFontEngineXLFD::QFontEngineXLFD().
cache_count
int QFontEngine::cache_count
Definition at line 257 of file qfontengine_p.h.
Referenced by QFontCache::insertEngine(), QFontEngine(), releaseCachedFontEngine(), QRawFont::setPixelSize(), and QFontEngineMulti::~QFontEngineMulti().
fontDef
QFontDef QFontEngine::fontDef
Definition at line 255 of file qfontengine_p.h.
Referenced by QFontEngineDirectWrite::addGlyphsToPath(), QFontEngineDirectWrite::alphaMapBoundingBox(), QFontEngineMac::ascent(), QFontEngineDirectWrite::ascent(), QFontEngineMac::averageCharWidth(), QFontEngineMac::boundingBox(), QFontEngineDirectWrite::boundingBox(), QFontEngineDirectWrite::cloneWithSize(), QFontEngineWin::cloneWithSize(), QFontEngineX11FT::cloneWithSize(), QFontEngineFT::cloneWithSize(), QFontEngineMac::descent(), QFontEngineDirectWrite::descent(), QFontEngineMac::draw(), QPainter::drawGlyphRun(), QOpenGLPaintEngine::drawStaticTextItem(), QGL2PaintEngineEx::drawStaticTextItem(), QPaintEngineEx::drawStaticTextItem(), QCoreGraphicsPaintEngine::drawTextItem(), QGL2PaintEngineEx::drawTextItem(), QPdfEnginePrivate::drawTextItem(), QPdfBaseEnginePrivate::drawTextItem(), engineForPattern(), QFontInfo::exactMatch(), QFont::exactMatch(), QFontInfo::family(), QRawFont::familyName(), QFontDatabase::findFont(), QFontInfo::fixedPitch(), QFontEngineMacMulti::fontIndexForFontID(), harfbuzzFont(), QFontEngineMac::imageForGlyph(), QFontEngineDirectWrite::imageForGlyph(), initFontInfo(), QFontInfo::italic(), QFontEngineMac::leading(), QFontEngineDirectWrite::leading(), lineThickness(), QFontDatabase::load(), QFontEngineMultiFT::loadEngine(), QFontEngineMultiWin::loadEngine(), QFontEngineMultiQPA::loadEngine(), QFontEngineMultiQWS::loadEngine(), loadEngine(), loadFc(), loadWin(), QFontDatabase::loadXlfd(), QFontEngineQPF::lockFace(), QFontEngineMac::maxCharWidth(), QFontInfo::pixelSize(), QRawFont::pixelSize(), QRawFontPrivate::platformLoadFromData(), QFontInfo::pointSize(), QFontInfo::pointSizeF(), properties(), QFontEngineDirectWrite::QFontEngineDirectWrite(), QFontEngineMac::QFontEngineMac(), QFontEngineMacMulti::QFontEngineMacMulti(), QFontEngineMultiFT::QFontEngineMultiFT(), QFontEngineMultiQPA::QFontEngineMultiQPA(), QFontEngineMultiQWS::QFontEngineMultiQWS(), QFontEngineMultiWin::QFontEngineMultiWin(), QFontEngineMultiXLFD::QFontEngineMultiXLFD(), QFontEngineQPA::QFontEngineQPA(), QFontEngineQPF::QFontEngineQPF(), QProxyFontEngine::QProxyFontEngine(), QFontEngineMac::recalcAdvances(), QFontEngineDirectWrite::recalcAdvances(), registerFont(), QFontEngineMacMulti::stringToCMapInternal(), QFontInfo::style(), QRawFont::style(), QFontInfo::styleHint(), QFontInfo::styleName(), QRawFont::styleName(), QRasterPaintEngine::supportsTransformations(), QFontSubset::toTruetype(), QFontSubset::toType1(), QFontInfo::weight(), QRawFont::weight(), QFontEngineMac::xHeight(), and QFontEngineDirectWrite::xHeight().
fsType
uint QFontEngine::fsType
Definition at line 258 of file qfontengine_p.h.
Referenced by QPdfBaseEnginePrivate::drawTextItem(), QFontEngineXLFD::faceId(), QFontEngine(), QFontEngineMac::QFontEngineMac(), and QFontSubset::toType1().
glyphFormat
int QFontEngine::glyphFormat
Definition at line 276 of file qfontengine_p.h.
Referenced by QRasterPaintEngine::drawCachedGlyphs(), QGL2PaintEngineEx::drawStaticTextItem(), QGL2PaintEngineEx::drawTextItem(), loadEngine(), QFontEngine(), and QFontEngineQPF::QFontEngineQPF().
hbFace
HB_Face QFontEngine::hbFace mutable
Definition at line 261 of file qfontengine_p.h.
Referenced by harfbuzzFace(), QFontEngine(), and ~QFontEngine().
hbFont
HB_FontRec QFontEngine::hbFont mutable
Definition at line 260 of file qfontengine_p.h.
Referenced by harfbuzzFont(), and QFontEngine().
kerning_pairs
QVector<KernPair> QFontEngine::kerning_pairs
Definition at line 272 of file qfontengine_p.h.
Referenced by doKerning(), and loadKerningPairs().
m_glyphCaches
QLinkedList<GlyphCacheEntry> QFontEngine::m_glyphCaches mutable private
Definition at line 289 of file qfontengine_p.h.
Referenced by glyphCache(), setGlyphCache(), and ~QFontEngine().
ref
QAtomicInt QFontEngine::ref
Definition at line 254 of file qfontengine_p.h.
Referenced by QFontCache::clear(), QFontEngineMac::faceId(), QFontDatabase::findFont(), QTextEngine::fontEngine(), QFontEngineMacMulti::fontIndexForFontID(), QRawFont::fromFont(), QTextLine::glyphs(), QFontDatabase::load(), QFontEngineMultiXLFD::loadEngine(), QFontEngineMultiFT::loadEngine(), loadWin(), QFontDatabase::loadXlfd(), QRawFontPrivate::platformLoadFromData(), QPainterReplayer::process(), QFontEngine(), QFontEngineMacMulti::QFontEngineMacMulti(), QFontEngineMultiFT::QFontEngineMultiFT(), QFontEngineMultiQPA::QFontEngineMultiQPA(), QFontEngineMultiQWS::QFontEngineMultiQWS(), QFontEngineMultiWin::QFontEngineMultiWin(), QFontSubset::QFontSubset(), QTextItemIntCopy::QTextItemIntCopy(), registerFont(), releaseCachedFontEngine(), releaseFontData(), QStaticTextItem::setFontEngine(), QRawFont::setPixelSize(), QFontEngineData::~QFontEngineData(), QFontEngineMacMulti::~QFontEngineMacMulti(), QFontEngineMulti::~QFontEngineMulti(), QFontSubset::~QFontSubset(), QRawFontPrivate::~QRawFontPrivate(), and QTextItemIntCopy::~QTextItemIntCopy().
symbol
bool QFontEngine::symbol
Definition at line 259 of file qfontengine_p.h.
Referenced by QFontEngineQPA::canRender(), QFontEngineQPF::canRender(), QFontDatabase::findFont(), loadEngine(), loadFc(), QFontDatabase::loadXlfd(), QFontEngine(), QFontEngineQPA::QFontEngineQPA(), QFontEngineQPF::QFontEngineQPF(), QFontEngineQPA::stringToCMap(), and QFontEngineQPF::stringToCMap().
The documentation for this class was generated from the following files:
/src/gui/text/qfontengine_p.h
/src/gui/text/qfontengine.cpp