Qt 4.8: QWindowsCEStyle Class Reference
QWindowsCEStyle Class Reference
#include <qwindowscestyle.h>
Public Functions
void drawComplexControl (ComplexControl control, const QStyleOptionComplex *option, QPainter *painter, const QWidget *widget) const
Reimplemented Function
void drawControl (ControlElement element, const QStyleOption *option, QPainter *painter, const QWidget *widget) const
Reimplemented Function
virtual void drawItemText (QPainter *painter, const QRect &rect, int flags, const QPalette &pal, bool enabled, const QString &text, QPalette::ColorRole textRole=QPalette::NoRole) const
Draws the given text in the specified rectangle using the provided painter and palette.
void drawPrimitive (PrimitiveElement element, const QStyleOption *option, QPainter *painter, const QWidget *widget=0) const
Reimplemented Function
SubControl hitTestComplexControl (ComplexControl control, const QStyleOptionComplex *option, const QPoint &pos, const QWidget *widget=0) const
Reimplemented Function
int pixelMetric (PixelMetric metric, const QStyleOption *option=0, const QWidget *widget=0) const
Reimplemented Function
void polish (QWidget *widget)
Reimplemented Function
void polish (QPalette &palette)
Reimplemented Function
void polish (QApplication *app)
Reimplemented Function
QWindowsCEStyle ()
QSize sizeFromContents (ContentsType type, const QStyleOption *option, const QSize &size, const QWidget *widget) const
Reimplemented Function
QPalette standardPalette () const
Returns the style's standard palette.
QPixmap standardPixmap (StandardPixmap standardPixmap, const QStyleOption *opt, const QWidget *widget=0) const
Reimplemented Function
int styleHint (StyleHint hint, const QStyleOption *opt=0, const QWidget *widget=0, QStyleHintReturn *returnData=0) const
Reimplemented Function
QRect subControlRect (ComplexControl cc, const QStyleOptionComplex *opt, SubControl sc, const QWidget *widget) const
Reimplemented Function
QRect subElementRect (SubElement element, const QStyleOption *option, const QWidget *widget) const
Reimplemented Function
Public Functions inherited from QWindowsStyle
void drawComplexControl (ComplexControl cc, const QStyleOptionComplex *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
void drawControl (ControlElement element, const QStyleOption *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
void drawPrimitive (PrimitiveElement pe, const QStyleOption *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
int pixelMetric (PixelMetric pm, const QStyleOption *option=0, const QWidget *widget=0) const
Reimplemented Function
void polish (QApplication *)
Reimplemented Function
void polish (QWidget *)
Reimplemented Function
void polish (QPalette &)
Reimplemented Function
QWindowsStyle ()
Constructs a QWindowsStyle object.
QSize sizeFromContents (ContentsType ct, const QStyleOption *opt, const QSize &contentsSize, const QWidget *widget=0) const
Reimplemented Function
QPixmap standardPixmap (StandardPixmap standardPixmap, const QStyleOption *opt, const QWidget *widget=0) const
Reimplemented Function
int styleHint (StyleHint hint, const QStyleOption *opt=0, const QWidget *widget=0, QStyleHintReturn *returnData=0) const
Reimplemented Function
QRect subElementRect (SubElement r, const QStyleOption *opt, const QWidget *widget=0) const
Reimplemented Function
void unpolish (QApplication *)
Reimplemented Function
void unpolish (QWidget *)
Reimplemented Function
~QWindowsStyle ()
Destroys the QWindowsStyle object.
Public Functions inherited from QCommonStyle
QPixmap generatedIconPixmap (QIcon::Mode iconMode, const QPixmap &pixmap, const QStyleOption *opt) const
Reimplemented Function
QCommonStyle ()
Constructs a QCommonStyle.
~QCommonStyle ()
Destroys the style.
Public Functions inherited from QStyle
int combinedLayoutSpacing (QSizePolicy::ControlTypes controls1, QSizePolicy::ControlTypes controls2, Qt::Orientation orientation, QStyleOption *option=0, QWidget *widget=0) const
Returns the spacing that should be used between controls1 and controls2 in a layout.
virtual void drawItemPixmap (QPainter *painter, const QRect &rect, int alignment, const QPixmap &pixmap) const
Draws the given pixmap in the specified rectangle, according to the specified alignment, using the provided painter.
virtual QRect itemPixmapRect (const QRect &r, int flags, const QPixmap &pixmap) const
Returns the area within the given rectangle in which to draw the specified pixmap according to the defined alignment.
virtual QRect itemTextRect (const QFontMetrics &fm, const QRect &r, int flags, bool enabled, const QString &text) const
Returns the area within the given rectangle in which to draw the provided text according to the specified font metrics and alignment.
int layoutSpacing (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption *option=0, const QWidget *widget=0) const
Returns the spacing that should be used between control1 and control2 in a layout.
const QStyle * proxy () const
QStyle ()
Constructs a style object.
QIcon standardIcon (StandardPixmap standardIcon, const QStyleOption *option=0, const QWidget *widget=0) const
Returns an icon for the given standardIcon.
virtual ~QStyle ()
Destroys the style object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Types inherited from QStyle
enum ComplexControl {
CC_SpinBox, CC_ComboBox, CC_ScrollBar, CC_Slider,
CC_ToolButton, CC_TitleBar, CC_Q3ListView, CC_Dial,
CC_GroupBox, CC_MdiControls, CC_CustomBase = 0xf0000000
}
This enum describes the available complex controls.
enum ContentsType {
CT_PushButton, CT_CheckBox, CT_RadioButton, CT_ToolButton,
CT_ComboBox, CT_Splitter, CT_Q3DockWindow, CT_ProgressBar,
CT_MenuItem, CT_MenuBarItem, CT_MenuBar, CT_Menu,
CT_TabBarTab, CT_Slider, CT_ScrollBar, CT_Q3Header,
CT_LineEdit, CT_SpinBox, CT_SizeGrip, CT_TabWidget,
CT_DialogButtons, CT_HeaderSection, CT_GroupBox, CT_MdiControls,
CT_ItemViewItem, CT_CustomBase = 0xf0000000
}
This enum describes the available contents types.
enum ControlElement {
CE_PushButton, CE_PushButtonBevel, CE_PushButtonLabel, CE_CheckBox,
CE_CheckBoxLabel, CE_RadioButton, CE_RadioButtonLabel, CE_TabBarTab,
CE_TabBarTabShape, CE_TabBarTabLabel, CE_ProgressBar, CE_ProgressBarGroove,
CE_ProgressBarContents, CE_ProgressBarLabel, CE_MenuItem, CE_MenuScroller,
CE_MenuVMargin, CE_MenuHMargin, CE_MenuTearoff, CE_MenuEmptyArea,
CE_MenuBarItem, CE_MenuBarEmptyArea, CE_ToolButtonLabel, CE_Header,
CE_HeaderSection, CE_HeaderLabel, CE_Q3DockWindowEmptyArea, CE_ToolBoxTab,
CE_SizeGrip, CE_Splitter, CE_RubberBand, CE_DockWidgetTitle,
CE_ScrollBarAddLine, CE_ScrollBarSubLine, CE_ScrollBarAddPage, CE_ScrollBarSubPage,
CE_ScrollBarSlider, CE_ScrollBarFirst, CE_ScrollBarLast, CE_FocusFrame,
CE_ComboBoxLabel, CE_ToolBar, CE_ToolBoxTabShape, CE_ToolBoxTabLabel,
CE_HeaderEmptyArea, CE_ColumnViewGrip, CE_ItemViewItem, CE_ShapedFrame,
CE_CustomBase = 0xf0000000
}
This enum represents a control element.
enum PixelMetric {
PM_ButtonMargin, PM_ButtonDefaultIndicator, PM_MenuButtonIndicator, PM_ButtonShiftHorizontal,
PM_ButtonShiftVertical, PM_DefaultFrameWidth, PM_SpinBoxFrameWidth, PM_ComboBoxFrameWidth,
PM_MaximumDragDistance, PM_ScrollBarExtent, PM_ScrollBarSliderMin, PM_SliderThickness,
PM_SliderControlThickness, PM_SliderLength, PM_SliderTickmarkOffset, PM_SliderSpaceAvailable,
PM_DockWidgetSeparatorExtent, PM_DockWidgetHandleExtent, PM_DockWidgetFrameWidth, PM_TabBarTabOverlap,
PM_TabBarTabHSpace, PM_TabBarTabVSpace, PM_TabBarBaseHeight, PM_TabBarBaseOverlap,
PM_ProgressBarChunkWidth, PM_SplitterWidth, PM_TitleBarHeight, PM_MenuScrollerHeight,
PM_MenuHMargin, PM_MenuVMargin, PM_MenuPanelWidth, PM_MenuTearoffHeight,
PM_MenuDesktopFrameWidth, PM_MenuBarPanelWidth, PM_MenuBarItemSpacing, PM_MenuBarVMargin,
PM_MenuBarHMargin, PM_IndicatorWidth, PM_IndicatorHeight, PM_ExclusiveIndicatorWidth,
PM_ExclusiveIndicatorHeight, PM_CheckListButtonSize, PM_CheckListControllerSize, PM_DialogButtonsSeparator,
PM_DialogButtonsButtonWidth, PM_DialogButtonsButtonHeight, PM_MdiSubWindowFrameWidth, PM_MDIFrameWidth = PM_MdiSubWindowFrameWidth,
PM_MdiSubWindowMinimizedWidth, PM_MDIMinimizedWidth = PM_MdiSubWindowMinimizedWidth, PM_HeaderMargin, PM_HeaderMarkSize,
PM_HeaderGripMargin, PM_TabBarTabShiftHorizontal, PM_TabBarTabShiftVertical, PM_TabBarScrollButtonWidth,
PM_ToolBarFrameWidth, PM_ToolBarHandleExtent, PM_ToolBarItemSpacing, PM_ToolBarItemMargin,
PM_ToolBarSeparatorExtent, PM_ToolBarExtensionExtent, PM_SpinBoxSliderHeight, PM_DefaultTopLevelMargin,
PM_DefaultChildMargin, PM_DefaultLayoutSpacing, PM_ToolBarIconSize, PM_ListViewIconSize,
PM_IconViewIconSize, PM_SmallIconSize, PM_LargeIconSize, PM_FocusFrameVMargin,
PM_FocusFrameHMargin, PM_ToolTipLabelFrameWidth, PM_CheckBoxLabelSpacing, PM_TabBarIconSize,
PM_SizeGripSize, PM_DockWidgetTitleMargin, PM_MessageBoxIconSize, PM_ButtonIconSize,
PM_DockWidgetTitleBarButtonMargin, PM_RadioButtonLabelSpacing, PM_LayoutLeftMargin, PM_LayoutTopMargin,
PM_LayoutRightMargin, PM_LayoutBottomMargin, PM_LayoutHorizontalSpacing, PM_LayoutVerticalSpacing,
PM_TabBar_ScrollButtonOverlap, PM_TextCursorWidth, PM_TabCloseIndicatorWidth, PM_TabCloseIndicatorHeight,
PM_ScrollView_ScrollBarSpacing, PM_SubMenuOverlap, PM_CustomBase = 0xf0000000
}
This enum describes the various available pixel metrics.
enum PrimitiveElement {
PE_Q3CheckListController, PE_Q3CheckListExclusiveIndicator, PE_Q3CheckListIndicator, PE_Q3DockWindowSeparator,
PE_Q3Separator, PE_Frame, PE_FrameDefaultButton, PE_FrameDockWidget,
PE_FrameFocusRect, PE_FrameGroupBox, PE_FrameLineEdit, PE_FrameMenu,
PE_FrameStatusBar, PE_FrameStatusBarItem = PE_FrameStatusBar, PE_FrameTabWidget, PE_FrameWindow,
PE_FrameButtonBevel, PE_FrameButtonTool, PE_FrameTabBarBase, PE_PanelButtonCommand,
PE_PanelButtonBevel, PE_PanelButtonTool, PE_PanelMenuBar, PE_PanelToolBar,
PE_PanelLineEdit, PE_IndicatorArrowDown, PE_IndicatorArrowLeft, PE_IndicatorArrowRight,
PE_IndicatorArrowUp, PE_IndicatorBranch, PE_IndicatorButtonDropDown, PE_IndicatorViewItemCheck,
PE_IndicatorItemViewItemCheck = PE_IndicatorViewItemCheck, PE_IndicatorCheckBox, PE_IndicatorDockWidgetResizeHandle, PE_IndicatorHeaderArrow,
PE_IndicatorMenuCheckMark, PE_IndicatorProgressChunk, PE_IndicatorRadioButton, PE_IndicatorSpinDown,
PE_IndicatorSpinMinus, PE_IndicatorSpinPlus, PE_IndicatorSpinUp, PE_IndicatorToolBarHandle,
PE_IndicatorToolBarSeparator, PE_PanelTipLabel, PE_IndicatorTabTear, PE_PanelScrollAreaCorner,
PE_Widget, PE_IndicatorColumnViewArrow, PE_IndicatorItemViewItemDrop, PE_PanelItemViewItem,
PE_PanelItemViewRow, PE_PanelStatusBar, PE_IndicatorTabClose, PE_PanelMenu,
PE_CustomBase = 0xf000000
}
This enum describes the various primitive elements.
enum RequestSoftwareInputPanel { RSIP_OnMouseClickAndAlreadyFocused, RSIP_OnMouseClick }
This enum describes under what circumstances a software input panel will be requested by input capable widgets.
enum StandardPixmap {
SP_TitleBarMenuButton, SP_TitleBarMinButton, SP_TitleBarMaxButton, SP_TitleBarCloseButton,
SP_TitleBarNormalButton, SP_TitleBarShadeButton, SP_TitleBarUnshadeButton, SP_TitleBarContextHelpButton,
SP_DockWidgetCloseButton, SP_MessageBoxInformation, SP_MessageBoxWarning, SP_MessageBoxCritical,
SP_MessageBoxQuestion, SP_DesktopIcon, SP_TrashIcon, SP_ComputerIcon,
SP_DriveFDIcon, SP_DriveHDIcon, SP_DriveCDIcon, SP_DriveDVDIcon,
SP_DriveNetIcon, SP_DirOpenIcon, SP_DirClosedIcon, SP_DirLinkIcon,
SP_FileIcon, SP_FileLinkIcon, SP_ToolBarHorizontalExtensionButton, SP_ToolBarVerticalExtensionButton,
SP_FileDialogStart, SP_FileDialogEnd, SP_FileDialogToParent, SP_FileDialogNewFolder,
SP_FileDialogDetailedView, SP_FileDialogInfoView, SP_FileDialogContentsView, SP_FileDialogListView,
SP_FileDialogBack, SP_DirIcon, SP_DialogOkButton, SP_DialogCancelButton,
SP_DialogHelpButton, SP_DialogOpenButton, SP_DialogSaveButton, SP_DialogCloseButton,
SP_DialogApplyButton, SP_DialogResetButton, SP_DialogDiscardButton, SP_DialogYesButton,
SP_DialogNoButton, SP_ArrowUp, SP_ArrowDown, SP_ArrowLeft,
SP_ArrowRight, SP_ArrowBack, SP_ArrowForward, SP_DirHomeIcon,
SP_CommandLink, SP_VistaShield, SP_BrowserReload, SP_BrowserStop,
SP_MediaPlay, SP_MediaStop, SP_MediaPause, SP_MediaSkipForward,
SP_MediaSkipBackward, SP_MediaSeekForward, SP_MediaSeekBackward, SP_MediaVolume,
SP_MediaVolumeMuted, SP_CustomBase = 0xf0000000
}
This enum describes the available standard pixmaps.
enum StateFlag {
State_None = 0x00000000, State_Enabled = 0x00000001, State_Raised = 0x00000002, State_Sunken = 0x00000004,
State_Off = 0x00000008, State_NoChange = 0x00000010, State_On = 0x00000020, State_DownArrow = 0x00000040,
State_Horizontal = 0x00000080, State_HasFocus = 0x00000100, State_Top = 0x00000200, State_Bottom = 0x00000400,
State_FocusAtBorder = 0x00000800, State_AutoRaise = 0x00001000, State_MouseOver = 0x00002000, State_UpArrow = 0x00004000,
State_Selected = 0x00008000, State_Active = 0x00010000, State_Window = 0x00020000, State_Open = 0x00040000,
State_Children = 0x00080000, State_Item = 0x00100000, State_Sibling = 0x00200000, State_Editing = 0x00400000,
State_KeyboardFocusChange = 0x00800000, State_ReadOnly = 0x02000000, State_Small = 0x04000000, State_Mini = 0x08000000
}
This enum describes flags that are used when drawing primitive elements.
enum StyleHint {
SH_EtchDisabledText, SH_DitherDisabledText, SH_ScrollBar_MiddleClickAbsolutePosition, SH_ScrollBar_ScrollWhenPointerLeavesControl,
SH_TabBar_SelectMouseType, SH_TabBar_Alignment, SH_Header_ArrowAlignment, SH_Slider_SnapToValue,
SH_Slider_SloppyKeyEvents, SH_ProgressDialog_CenterCancelButton, SH_ProgressDialog_TextLabelAlignment, SH_PrintDialog_RightAlignButtons,
SH_MainWindow_SpaceBelowMenuBar, SH_FontDialog_SelectAssociatedText, SH_Menu_AllowActiveAndDisabled, SH_Menu_SpaceActivatesItem,
SH_Menu_SubMenuPopupDelay, SH_ScrollView_FrameOnlyAroundContents, SH_MenuBar_AltKeyNavigation, SH_ComboBox_ListMouseTracking,
SH_Menu_MouseTracking, SH_MenuBar_MouseTracking, SH_ItemView_ChangeHighlightOnFocus, SH_Widget_ShareActivation,
SH_Workspace_FillSpaceOnMaximize, SH_ComboBox_Popup, SH_TitleBar_NoBorder, SH_Slider_StopMouseOverSlider,
SH_ScrollBar_StopMouseOverSlider = SH_Slider_StopMouseOverSlider, SH_BlinkCursorWhenTextSelected, SH_RichText_FullWidthSelection, SH_Menu_Scrollable,
SH_GroupBox_TextLabelVerticalAlignment, SH_GroupBox_TextLabelColor, SH_Menu_SloppySubMenus, SH_Table_GridLineColor,
SH_LineEdit_PasswordCharacter, SH_DialogButtons_DefaultButton, SH_ToolBox_SelectedPageTitleBold, SH_TabBar_PreferNoArrows,
SH_ScrollBar_LeftClickAbsolutePosition, SH_Q3ListViewExpand_SelectMouseType, SH_UnderlineShortcut, SH_SpinBox_AnimateButton,
SH_SpinBox_KeyPressAutoRepeatRate, SH_SpinBox_ClickAutoRepeatRate, SH_Menu_FillScreenWithScroll, SH_ToolTipLabel_Opacity,
SH_DrawMenuBarSeparator, SH_TitleBar_ModifyNotification, SH_Button_FocusPolicy, SH_MenuBar_DismissOnSecondClick,
SH_MessageBox_UseBorderForButtonSpacing, SH_TitleBar_AutoRaise, SH_ToolButton_PopupDelay, SH_FocusFrame_Mask,
SH_RubberBand_Mask, SH_WindowFrame_Mask, SH_SpinControls_DisableOnBounds, SH_Dial_BackgroundRole,
SH_ComboBox_LayoutDirection, SH_ItemView_EllipsisLocation, SH_ItemView_ShowDecorationSelected, SH_ItemView_ActivateItemOnSingleClick,
SH_ScrollBar_ContextMenu, SH_ScrollBar_RollBetweenButtons, SH_Slider_AbsoluteSetButtons, SH_Slider_PageSetButtons,
SH_Menu_KeyboardSearch, SH_TabBar_ElideMode, SH_DialogButtonLayout, SH_ComboBox_PopupFrameStyle,
SH_MessageBox_TextInteractionFlags, SH_DialogButtonBox_ButtonsHaveIcons, SH_SpellCheckUnderlineStyle, SH_MessageBox_CenterButtons,
SH_Menu_SelectionWrap, SH_ItemView_MovementWithoutUpdatingSelection, SH_ToolTip_Mask, SH_FocusFrame_AboveWidget,
SH_TextControl_FocusIndicatorTextCharFormat, SH_WizardStyle, SH_ItemView_ArrowKeysNavigateIntoChildren, SH_Menu_Mask,
SH_Menu_FlashTriggeredItem, SH_Menu_FadeOutOnHide, SH_SpinBox_ClickAutoRepeatThreshold, SH_ItemView_PaintAlternatingRowColorsForEmptyArea,
SH_FormLayoutWrapPolicy, SH_TabWidget_DefaultTabPosition, SH_ToolBar_Movable, SH_FormLayoutFieldGrowthPolicy,
SH_FormLayoutFormAlignment, SH_FormLayoutLabelAlignment, SH_ItemView_DrawDelegateFrame, SH_TabBar_CloseButtonPosition,
SH_DockWidget_ButtonsHaveFrame, SH_ToolButtonStyle, SH_RequestSoftwareInputPanel, SH_CustomBase = 0xf0000000
}
This enum describes the available style hints.
enum SubControl {
SC_None = 0x00000000, SC_ScrollBarAddLine = 0x00000001, SC_ScrollBarSubLine = 0x00000002, SC_ScrollBarAddPage = 0x00000004,
SC_ScrollBarSubPage = 0x00000008, SC_ScrollBarFirst = 0x00000010, SC_ScrollBarLast = 0x00000020, SC_ScrollBarSlider = 0x00000040,
SC_ScrollBarGroove = 0x00000080, SC_SpinBoxUp = 0x00000001, SC_SpinBoxDown = 0x00000002, SC_SpinBoxFrame = 0x00000004,
SC_SpinBoxEditField = 0x00000008, SC_ComboBoxFrame = 0x00000001, SC_ComboBoxEditField = 0x00000002, SC_ComboBoxArrow = 0x00000004,
SC_ComboBoxListBoxPopup = 0x00000008, SC_SliderGroove = 0x00000001, SC_SliderHandle = 0x00000002, SC_SliderTickmarks = 0x00000004,
SC_ToolButton = 0x00000001, SC_ToolButtonMenu = 0x00000002, SC_TitleBarSysMenu = 0x00000001, SC_TitleBarMinButton = 0x00000002,
SC_TitleBarMaxButton = 0x00000004, SC_TitleBarCloseButton = 0x00000008, SC_TitleBarNormalButton = 0x00000010, SC_TitleBarShadeButton = 0x00000020,
SC_TitleBarUnshadeButton = 0x00000040, SC_TitleBarContextHelpButton = 0x00000080, SC_TitleBarLabel = 0x00000100, SC_Q3ListView = 0x00000001,
SC_Q3ListViewBranch = 0x00000002, SC_Q3ListViewExpand = 0x00000004, SC_DialGroove = 0x00000001, SC_DialHandle = 0x00000002,
SC_DialTickmarks = 0x00000004, SC_GroupBoxCheckBox = 0x00000001, SC_GroupBoxLabel = 0x00000002, SC_GroupBoxContents = 0x00000004,
SC_GroupBoxFrame = 0x00000008, SC_MdiMinButton = 0x00000001, SC_MdiNormalButton = 0x00000002, SC_MdiCloseButton = 0x00000004,
SC_CustomBase = 0xf0000000, SC_All = 0xffffffff
}
This enum describes the available sub controls.
enum SubElement {
SE_PushButtonContents, SE_PushButtonFocusRect, SE_CheckBoxIndicator, SE_CheckBoxContents,
SE_CheckBoxFocusRect, SE_CheckBoxClickRect, SE_RadioButtonIndicator, SE_RadioButtonContents,
SE_RadioButtonFocusRect, SE_RadioButtonClickRect, SE_ComboBoxFocusRect, SE_SliderFocusRect,
SE_Q3DockWindowHandleRect, SE_ProgressBarGroove, SE_ProgressBarContents, SE_ProgressBarLabel,
SE_DialogButtonAccept, SE_DialogButtonReject, SE_DialogButtonApply, SE_DialogButtonHelp,
SE_DialogButtonAll, SE_DialogButtonAbort, SE_DialogButtonIgnore, SE_DialogButtonRetry,
SE_DialogButtonCustom, SE_ToolBoxTabContents, SE_HeaderLabel, SE_HeaderArrow,
SE_TabWidgetTabBar, SE_TabWidgetTabPane, SE_TabWidgetTabContents, SE_TabWidgetLeftCorner,
SE_TabWidgetRightCorner, SE_ViewItemCheckIndicator, SE_ItemViewItemCheckIndicator = SE_ViewItemCheckIndicator, SE_TabBarTearIndicator,
SE_TreeViewDisclosureItem, SE_LineEditContents, SE_FrameContents, SE_DockWidgetCloseButton,
SE_DockWidgetFloatButton, SE_DockWidgetTitleBarText, SE_DockWidgetIcon, SE_CheckBoxLayoutItem,
SE_ComboBoxLayoutItem, SE_DateTimeEditLayoutItem, SE_DialogButtonBoxLayoutItem, SE_LabelLayoutItem,
SE_ProgressBarLayoutItem, SE_PushButtonLayoutItem, SE_RadioButtonLayoutItem, SE_SliderLayoutItem,
SE_SpinBoxLayoutItem, SE_ToolButtonLayoutItem, SE_FrameLayoutItem, SE_GroupBoxLayoutItem,
SE_TabWidgetLayoutItem, SE_ItemViewItemDecoration, SE_ItemViewItemText, SE_ItemViewItemFocusRect,
SE_TabBarTabLeftButton, SE_TabBarTabRightButton, SE_TabBarTabText, SE_ShapedFrameContents,
SE_ToolBarHandle, SE_CustomBase = 0xf0000000
}
This enum represents a sub-area of a widget.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QStyle
static QRect alignedRect (Qt::LayoutDirection direction, Qt::Alignment alignment, const QSize &size, const QRect &rectangle)
Returns a new rectangle of the specified size that is aligned to the given rectangle according to the specified alignment and direction.
static int sliderPositionFromValue (int min, int max, int val, int space, bool upsideDown=false)
Converts the given logicalValue to a pixel position.
static int sliderValueFromPosition (int min, int max, int pos, int space, bool upsideDown=false)
Converts the given pixel position to a logical value.
static Qt::Alignment visualAlignment (Qt::LayoutDirection direction, Qt::Alignment alignment)
Transforms an alignment of Qt::AlignLeft or Qt::AlignRight without Qt::AlignAbsolute into Qt::AlignLeft or Qt::AlignRight with Qt::AlignAbsolute according to the layout direction.
static QPoint visualPos (Qt::LayoutDirection direction, const QRect &boundingRect, const QPoint &logicalPos)
Returns the given logicalPosition converted to screen coordinates based on the specified direction.
static QRect visualRect (Qt::LayoutDirection direction, const QRect &boundingRect, const QRect &logicalRect)
Returns the given logicalRectangle converted to screen coordinates based on the specified direction.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWindowsStyle
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *option, const QWidget *widget=0) const
Protected Slots inherited from QCommonStyle
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *opt=0, const QWidget *widget=0) const
Protected Slots inherited from QStyle
int layoutSpacingImplementation (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption *option=0, const QWidget *widget=0) const
This slot is called by layoutSpacing() to determine the spacing that should be used between control1 and control2 in a layout.
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *opt=0, const QWidget *widget=0) const
Returns an icon for the given standardIcon.
Protected Functions inherited from QWindowsStyle
bool eventFilter (QObject *o, QEvent *e)
Reimplemented Function
QWindowsStyle (QWindowsStylePrivate &dd)
Constructs a QWindowsStyle object.
void timerEvent (QTimerEvent *event)
Reimplemented Function
Protected Functions inherited from QCommonStyle
QCommonStyle (QCommonStylePrivate &dd)
Protected Functions inherited from QStyle
QStyle (QStylePrivate &dd)
Constructs a style object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 55 of file qwindowscestyle.h.
Constructors and Destructors
QWindowsCEStyle()
QWindowsCEStyle::QWindowsCEStyle ()
Definition at line 77 of file qwindowscestyle.cpp.
                                  : QWindowsStyle() {
     qApp->setEffectEnabled(Qt::UI_FadeMenu, false);
     qApp->setEffectEnabled(Qt::UI_AnimateMenu, false);
 }
Functions
drawComplexControl()
void QWindowsCEStyle::drawComplexControl (ComplexControl cc, const QStyleOptionComplex * opt, QPainter * p, const QWidget * w) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 1182 of file qwindowscestyle.cpp.
{
     switch (control) {
         #ifndef QT_NO_SLIDER
     case CC_Slider:
         if (const QStyleOptionSlider *slider = qstyleoption_cast<const QStyleOptionSlider *>(option)) {
             int thickness  = pixelMetric(PM_SliderControlThickness, slider, widget);
             int len        = pixelMetric(PM_SliderLength, slider, widget);
             int ticks = slider->tickPosition;
             QRect groove = subControlRect(CC_Slider, slider, SC_SliderGroove, widget);
             QRect handle = subControlRect(CC_Slider, slider, SC_SliderHandle, widget);
             if ((slider->subControls & SC_SliderGroove) && groove.isValid()) {
                 int mid = thickness / 2;
                 if (ticks & QSlider::TicksAbove)
                     mid += len / 8;
                 if (ticks & QSlider::TicksBelow)
                     mid -= len / 8;
                 painter->setPen(slider->palette.shadow().color());
                 if (slider->orientation == Qt::Horizontal) {
                     QWindowsCEStylePrivate::drawWinCEPanel(painter, groove.x(), groove.y() + mid - 2,
                                    groove.width(), 4, option->palette, true);
                     painter->drawLine(groove.x() + 1, groove.y() + mid - 1,
                                 groove.x() + groove.width() - 3, groove.y() + mid - 1);
                 } else {
                     QWindowsCEStylePrivate::drawWinCEPanel(painter, groove.x() + mid - 2, groove.y(),
                                   4, groove.height(), option->palette, true);
                     painter->drawLine(groove.x() + mid - 1, groove.y() + 1,
                                 groove.x() + mid - 1, groove.y() + groove.height() - 3);
                 }
             }
             if (slider->subControls & SC_SliderTickmarks) {
                 QStyleOptionSlider tmpSlider = *slider;
                 tmpSlider.subControls = SC_SliderTickmarks;
                 QCommonStyle::drawComplexControl(control, &tmpSlider, painter, widget);
             }
             if (slider->subControls & SC_SliderHandle) {
                 // 4444440
                 // 4333310
                 // 4322210
                 // 4322210
                 // 4322210
                 // 4322210
                 // *43210*
                 // **440**
                 // ***0***
                 const QColor c0 = slider->palette.shadow().color();
                 const QColor c1 = slider->palette.dark().color();
                 // const QColor c2 = g.button();
                 const QColor c3 = slider->palette.midlight().color();
                 const QColor c4 = slider->palette.dark().color();
                 QBrush handleBrush;
                 if (slider->state & State_Enabled) {
                     handleBrush = slider->palette.color(QPalette::Button);
                 } else {
                     handleBrush = QBrush(slider->palette.color(QPalette::Button),
                                          Qt::Dense4Pattern);
                 }
                 int x = handle.x(), y = handle.y(),
                    wi = handle.width(), he = handle.height();
                 int x1 = x;
                 int x2 = x + wi - 1;
                 int y1 = y;
                 int y2 = y + he - 1;
                 Qt::Orientation orient = slider->orientation;
                 bool tickAbove = slider->tickPosition == QSlider::TicksAbove;
                 bool tickBelow = slider->tickPosition == QSlider::TicksBelow;
                 if (slider->state & State_HasFocus) {
                     QStyleOptionFocusRect fropt;
                     fropt.QStyleOption::operator=(*slider);
                     fropt.rect = subElementRect(SE_SliderFocusRect, slider, widget);
                     drawPrimitive(PE_FrameFocusRect, &fropt, painter, widget);
                 }
                 if ((tickAbove && tickBelow) || (!tickAbove && !tickBelow)) {
                     Qt::BGMode oldMode = painter->backgroundMode();
                     painter->setBackgroundMode(Qt::OpaqueMode);
                     QWindowsCEStylePrivate::drawWinCEButton(painter, QRect(x, y, wi, he), slider->palette, false,
                                                             &handleBrush);
                     painter->setBackgroundMode(oldMode);
                     QBrush fill = QBrush(option->palette.light().color(), Qt::Dense4Pattern);
                     if (slider->state & State_Sunken)
                       painter->fillRect(QRectF(x1 + 2, y1 + 2, x2 - x1 - 3, y2 - y1 - 3),fill);
                     return;
                 }
                 QSliderDirection dir;
                 if (orient == Qt::Horizontal)
                     if (tickAbove)
                         dir = SlUp;
                     else
                         dir = SlDown;
                 else
                     if (tickAbove)
                         dir = SlLeft;
                     else
                         dir = SlRight;
                 QPolygon a;
                 int d = 0;
                 switch (dir) {
                 case SlUp:
                     x2++;
                     y1 = y1 + wi / 2;
                     d =  (wi + 1) / 2 - 1;
                     a.setPoints(5, x1, y1, x1, y2, x2, y2, x2, y1, x1 + d, y1 - d);
                     break;
                 case SlDown:
                     x2++;
                     y2 = y2 - wi / 2;
                     d =  (wi + 1) / 2 - 1;
                     a.setPoints(5, x1, y1, x1, y2, x1 + d, y2+d, x2, y2, x2, y1);
                     break;
                 case SlLeft:
                     d =  (he + 1) / 2 - 1;
                     x1 = x1 + he / 2;
                     a.setPoints(5, x1, y1, x1 - d, y1 + d, x1, y2, x2, y2, x2, y1);
                     y1--;
                     break;
                 case SlRight:
                     d =  (he + 1) / 2 - 1;
                     x2 = x2 - he / 2;
                     a.setPoints(5, x1, y1, x1, y2, x2, y2, x2 + d, y1 + d, x2, y1);
                     y1--;
                     break;
                 }
                 QBrush oldBrush = painter->brush();
                 painter->setPen(Qt::NoPen);
                 painter->setBrush(handleBrush);
                 Qt::BGMode oldMode = painter->backgroundMode();
                 painter->setBackgroundMode(Qt::OpaqueMode);
                 painter->drawRect(x1, y1, x2 - x1 + 1, y2 - y1 + 1);
                 painter->drawPolygon(a);
                 QBrush fill = QBrush(option->palette.light().color(), Qt::Dense4Pattern);
                 if (slider->state & State_Sunken)
                   painter->fillRect(QRectF(x1, y1, x2 - x1 + 1, y2 - y1 + 1),fill);
                 painter->setBrush(oldBrush);
                 painter->setBackgroundMode(oldMode);
                 if (dir != SlUp) {
                     painter->setPen(c4);
                     painter->drawLine(x1, y1, x2, y1);
                     painter->setPen(c3);
                     painter->drawLine(x1, y1 + 1, x2, y1 + 1);
                 }
                 if (dir != SlLeft) {
                     painter->setPen(c3);
                     painter->drawLine(x1 + 1, y1 + 1, x1 + 1, y2);
                     painter->setPen(c4);
                     painter->drawLine(x1, y1, x1, y2);
                 }
                 if (dir != SlRight) {
                     painter->setPen(c0);
                     painter->drawLine(x2, y1, x2, y2);
                     painter->setPen(c1);
                     painter->drawLine(x2 - 1, y1 + 1, x2 - 1, y2 - 1);
                 }
                 if (dir != SlDown) {
                     painter->setPen(c0);
                     painter->drawLine(x1, y2, x2, y2);
                     painter->setPen(c1);
                     painter->drawLine(x1+1, y2 - 1, x2 - 1, y2 - 1);
                 }
                switch (dir) {
                 case SlUp:
                     if (slider->state & State_Sunken)
                       painter->fillRect(QRectF(x1 + 3, y1 - d + 2, x2 - x1 - 4,y1), fill);
                     painter->setPen(c4);
                     painter->drawLine(x1, y1, x1 + d, y1 - d);
                     painter->setPen(c0);
                     d = wi - d - 1;
                     painter->drawLine(x2, y1, x2 - d, y1 - d);
                     d--;
                     painter->setPen(c3);
                     painter->drawLine(x1 + 1, y1, x1 + 1 + d-1, y1 - d + 1);
                     painter->setPen(c1);
                     painter->drawLine(x2 - 1, y1, x2-1 - d, y1 - d);
                     break;
                 case SlDown:
                     if (slider->state & State_Sunken)
                       painter->fillRect(QRectF(x1 + 3, y2 - d, x2 - x1 - 4,y2 - 8), fill);
                     painter->setPen(c4);
                     painter->drawLine(x1, y2, x1 + d, y2 + d);
                     painter->setPen(c0);
                     d = wi - d - 1;
                     painter->drawLine(x2, y2, x2 - d, y2 + d);
                     d--;
                     painter->setPen(c3);
                     painter->drawLine(x1 + 1, y2, x1 + 1 + d - 1, y2 + d - 1);
                     painter->setPen(c1);
                     painter->drawLine(x2 - 1, y2, x2 - 1 - d, y2 + d);
                     break;
                 case SlLeft:
                     if (slider->state & State_Sunken)
                       painter->fillRect(QRectF(x1 - d + 2, y1 + 2, x1,y2 - y1 - 3), fill);
                     painter->setPen(c4);
                     painter->drawLine(x1, y1, x1 - d, y1 + d);
                     painter->setPen(c0);
                     d = he - d - 1;
                     painter->drawLine(x1, y2, x1 - d, y2 - d);
                     d--;
                     painter->setPen(c3);
                     painter->drawLine(x1, y1 + 1, x1 - d + 1, y1 + 1 + d - 1);
                     painter->setPen(c1);
                     painter->drawLine(x1, y2 - 1, x1 - d, y2 - 1 - d);
                     break;
                 case SlRight:
                     if (slider->state & State_Sunken)
                       painter->fillRect(QRectF(x2 - d - 4, y1 + 2, x2 - 4, y2 - y1 - 3), fill);
                     painter->setPen(c4);
                     painter->drawLine(x2, y1, x2 + d, y1 + d);
                     painter->setPen(c0);
                     d = he - d - 1;
                     painter->drawLine(x2, y2, x2 + d, y2 - d);
                     d--;
                     painter->setPen(c3);
                     painter->drawLine(x2, y1 + 1, x2 + d - 1, y1 + 1 + d - 1);
                     painter->setPen(c1);
                     painter->drawLine(x2, y2 - 1, x2 + d, y2 - 1 - d);
                     break;
                 }
             }
         }
         break;
 #endif // QT_NO_SLIDER
     case CC_ToolButton:
         if (const QStyleOptionToolButton *toolbutton
                 = qstyleoption_cast<const QStyleOptionToolButton *>(option)) {
             QRect button, menuarea;
 #ifndef QT_NO_TOOLBAR
             bool flat = !(widget ? qobject_cast<QToolBar*>(widget->parentWidget()) : 0);
 #else
             bool flat = true;
 #endif
             button = subControlRect(control, toolbutton, SC_ToolButton, widget);
             menuarea = subControlRect(control, toolbutton, SC_ToolButtonMenu, widget);
             if (flat && (toolbutton->subControls & SC_ToolButtonMenu)) {
                 menuarea.setLeft(menuarea.left() - 4);
                 button.setRight(button.right() - 4);
             }
             State bflags = toolbutton->state;
             if (bflags & State_AutoRaise)
                 if (!(bflags & State_MouseOver)) {
                     bflags &= ~State_Raised;
                 }
             State mflags = bflags;
             if (toolbutton->activeSubControls & SC_ToolButton)
                 bflags |= State_Sunken;
             if (toolbutton->activeSubControls & SC_ToolButtonMenu)
                 mflags |= State_Sunken;
             QStyleOption tool(0);
             tool.palette = toolbutton->palette;
             if (toolbutton->subControls & SC_ToolButton) {
                     tool.rect = button;
                     tool.state = bflags;
                     drawPrimitive(PE_PanelButtonTool, &tool, painter, widget);
                 }
             if (toolbutton->subControls & SC_ToolButtonMenu) {
                 tool.rect = menuarea;
                 tool.state = mflags;
                 tool.state = bflags;
                 drawPrimitive(PE_IndicatorButtonDropDown, &tool, painter, widget);
                 if (!flat) {
                     //connect buttons
                     painter->save();
                     painter->setPen(tool.palette.button().color());
                     painter->drawLine(tool.rect.x() - 2, tool.rect.y(), tool.rect.x() - 2, tool.rect.y() + tool.rect.height());
                     painter->drawLine(tool.rect.x() - 1, tool.rect.y(), tool.rect.x() - 1, tool.rect.y() + tool.rect.height());
                     painter->drawLine(tool.rect.x(), tool.rect.y(), tool.rect.x(), tool.rect.y() + tool.rect.height());
                     painter->drawLine(tool.rect.x() + 1, tool.rect.y(), tool.rect.x() + 1, tool.rect.y() + tool.rect.height());
                     if (tool.state & State_Sunken)
                     {
                         painter->setPen(tool.palette.midlight().color());
                         painter->drawLine(tool.rect.x() - 2, tool.rect.y() + tool.rect.height() - 2,
                             tool.rect.x() + 1, tool.rect.y() + tool.rect.height() -2 );
                         painter->setPen(tool.palette.shadow().color());
                         painter->drawLine(tool.rect.x() - 2, tool.rect.y() + 1,tool.rect.x() + 1, tool.rect.y() + 1);
                         painter->drawLine(tool.rect.x() - 2, tool.rect.y(), tool.rect.x() + 1, tool.rect.y());
                         painter->setPen(tool.palette.light().color());
                         painter->drawLine(tool.rect.x() - 2, tool.rect.y() + tool.rect.height() - 1,
                             tool.rect.x() + 1, tool.rect.y() + tool.rect.height() - 1);
                     }
                     else
                     {
                         painter->setPen(tool.palette.dark().color());
                         painter->drawLine(tool.rect.x() - 2, tool.rect.y(),tool.rect.x() + 1, tool.rect.y());
                         painter->drawLine(tool.rect.x() - 2, tool.rect.y()+tool.rect.height() - 2,tool.rect.x() + 1,
                             tool.rect.y() + tool.rect.height() - 2);
                         painter->setPen(tool.palette.midlight().color());
                         painter->drawLine(tool.rect.x() - 2, tool.rect.y() + 1,tool.rect.x() + 1, tool.rect.y() + 1);
                         painter->setPen(tool.palette.shadow().color());
                         painter->drawLine(tool.rect.x() - 2, tool.rect.y() + tool.rect.height() - 1,
                             tool.rect.x() + 1, tool.rect.y() + tool.rect.height() - 1);
                     }
                     painter->restore();
                 }
                 if (!flat) {
                     tool.rect.adjust(-3,0,-3,0);
                     painter->save();
                     painter->setPen(tool.palette.button().color());
                     if (tool.state & State_Sunken)
                         painter->drawLine(tool.rect.x() + 2, tool.rect.y() + 10,
                         tool.rect.x() + tool.rect.width(), tool.rect.y() + 10);
                     else
                         painter->drawLine(tool.rect.x() + 1, tool.rect.y() + 9, tool.rect.x() +
                         tool.rect.width() - 1, tool.rect.y() + 9);
                     painter->restore();
                 } else {
                     tool.rect.adjust(-1,0,-1,0);
                 }
                 drawPrimitive(PE_IndicatorArrowDown, &tool, painter, widget);
             }
             if (toolbutton->state & State_HasFocus) {
                 QStyleOptionFocusRect fr;
                 fr.QStyleOption::operator=(*toolbutton);
                 fr.rect.adjust(3, 3, -3, -3);
                 if (toolbutton->features & QStyleOptionToolButton::Menu)
                     fr.rect.adjust(0, 0, -pixelMetric(QStyle::PM_MenuButtonIndicator,
                                                          toolbutton, widget), 0);
                 drawPrimitive(PE_FrameFocusRect, &fr, painter, widget);
             }
             QStyleOptionToolButton label = *toolbutton;
             int fw = pixelMetric(PM_DefaultFrameWidth, option, widget);
             label.rect = button.adjusted(fw, fw, -fw, -fw);
             drawControl(CE_ToolButtonLabel, &label, painter, widget);
         }
         break;
 #ifndef QT_NO_GROUPBOX
     case CC_GroupBox:
         if (const QStyleOptionGroupBox *groupBox = qstyleoption_cast<const QStyleOptionGroupBox *>(option)) {
             // Draw frame
             painter->save();
             QFont f = painter->font();
             f.setBold(true);
             painter->setFont(f);
             QStyleOptionGroupBox groupBoxFont = *groupBox;
             groupBoxFont.fontMetrics = QFontMetrics(f);
             QRect textRect = subControlRect(CC_GroupBox, &groupBoxFont, SC_GroupBoxLabel, widget);
             QRect checkBoxRect = subControlRect(CC_GroupBox, option, SC_GroupBoxCheckBox, widget);
             if (groupBox->subControls & QStyle::SC_GroupBoxFrame) {
                 QStyleOptionFrameV2 frame;
                 frame.QStyleOption::operator=(*groupBox);
                 frame.features = groupBox->features;
                 frame.lineWidth = groupBox->lineWidth;
                 frame.midLineWidth = groupBox->midLineWidth;
                 frame.rect = subControlRect(CC_GroupBox, option, SC_GroupBoxFrame, widget);
                 painter->save();
                 QRegion region(groupBox->rect);
                 if (!groupBox->text.isEmpty()) {
                     bool ltr = groupBox->direction == Qt::LeftToRight;
                     QRect finalRect = checkBoxRect.united(textRect);
                     if (groupBox->subControls & QStyle::SC_GroupBoxCheckBox)
                         finalRect.adjust(ltr ? -4 : 0, 0, ltr ? 0 : 4, 0);
                     region -= finalRect;
                 }
                 painter->setClipRegion(region);
                 drawPrimitive(PE_FrameGroupBox, &frame, painter, widget);
                 painter->restore();
             }
             // Draw title
             if ((groupBox->subControls & QStyle::SC_GroupBoxLabel) && !groupBox->text.isEmpty()) {
                 QColor textColor = groupBox->textColor;
                 if (textColor.isValid())
                     painter->setPen(textColor);
                 int alignment = int(groupBox->textAlignment);
                 if (!styleHint(QStyle::SH_UnderlineShortcut, option, widget))
                     alignment |= Qt::TextHideMnemonic;
                 drawItemText(painter, textRect,  Qt::TextShowMnemonic | Qt::AlignHCenter | alignment,
                              groupBox->palette, groupBox->state & State_Enabled, groupBox->text,
                              textColor.isValid() ? QPalette::NoRole : QPalette::WindowText);
                 if (groupBox->state & State_HasFocus) {
                     QStyleOptionFocusRect fropt;
                     fropt.QStyleOption::operator=(*groupBox);
                     fropt.rect = textRect;
                     drawPrimitive(PE_FrameFocusRect, &fropt, painter, widget);
                 }
             }
             // Draw checkbox
             if (groupBox->subControls & SC_GroupBoxCheckBox) {
                 QStyleOptionButton box;
                 box.QStyleOption::operator=(*groupBox);
                 box.rect = checkBoxRect;
                 drawPrimitive(PE_IndicatorCheckBox, &box, painter, widget);
             }
             painter->restore();
         }
         break;
 #endif //QT_NO_GROUPBOX
 #ifndef QT_NO_COMBOBOX
     case CC_ComboBox:
         if (const QStyleOptionComboBox *cmb = qstyleoption_cast<const QStyleOptionComboBox *>(option)) {
             QBrush editBrush = cmb->palette.brush(QPalette::Base);
             if ((cmb->subControls & SC_ComboBoxFrame) && cmb->frame)
                 QWindowsCEStylePrivate::drawWinCEPanel(painter, option->rect, option->palette, true, &editBrush);
             else
                 painter->fillRect(option->rect, editBrush);
             if (cmb->subControls & SC_ComboBoxArrow) {
                 State flags = State_None;
                 QRect ar = subControlRect(CC_ComboBox, cmb, SC_ComboBoxArrow, widget);
                 if (cmb->activeSubControls == SC_ComboBoxArrow) {
                     painter->setPen(cmb->palette.dark().color());
                     painter->setBrush(cmb->palette.brush(QPalette::Button));
                     painter->drawRect(ar.adjusted(0, 0, -1, -1));
                     QWindowsCEStylePrivate::drawWinCEButton(painter, ar.adjusted(0, 0, -1, -1), option->palette, true,
                     &cmb->palette.brush(QPalette::Button));
                 } else {
                     // Make qDrawWinButton use the right colors for drawing the shade of the button
                     QWindowsCEStylePrivate::drawWinCEButton(painter, ar, option->palette, false,
                                    &cmb->palette.brush(QPalette::Button));
                 }
                 ar.adjust(2, 2, -2, -2);
                 if (option->state & State_Enabled)
                     flags |= State_Enabled;
                 if (cmb->activeSubControls == SC_ComboBoxArrow)
                     flags |= State_Sunken;
                 QStyleOption arrowOpt(0);
                 arrowOpt.rect = ar;
                 arrowOpt.palette = cmb->palette;
                 arrowOpt.state = flags;
                 drawPrimitive(PE_IndicatorArrowDown, &arrowOpt, painter, widget);
             }
             if (cmb->subControls & SC_ComboBoxEditField) {
                 QRect re = subControlRect(CC_ComboBox, cmb, SC_ComboBoxEditField, widget);
                 if (cmb->state & State_HasFocus && !cmb->editable)
                     painter->fillRect(re.x(), re.y(), re.width(), re.height(),
                  cmb->palette.brush(QPalette::Highlight));
                  if (cmb->state & State_HasFocus) {
                     painter->setPen(cmb->palette.highlightedText().color());
                     painter->setBackground(cmb->palette.highlight());
                  } else {
                     painter->setPen(cmb->palette.text().color());
                     painter->setBackground(cmb->palette.background());
                  }
                  if (cmb->state & State_HasFocus && !cmb->editable) {
                     QStyleOptionFocusRect focus;
                     focus.QStyleOption::operator=(*cmb);
                     focus.rect = subElementRect(SE_ComboBoxFocusRect, cmb, widget);
                     focus.state |= State_FocusAtBorder;
                     focus.backgroundColor = cmb->palette.highlight().color();
                     drawPrimitive(PE_FrameFocusRect, &focus, painter, widget);
                }
             }
         }
         break;
 #endif // QT_NO_COMBOBOX
 #ifndef QT_NO_SPINBOX
     case CC_SpinBox:
         if (const QStyleOptionSpinBox *sb = qstyleoption_cast<const QStyleOptionSpinBox *>(option)) {
             QStyleOptionSpinBox copy = *sb;
             PrimitiveElement pe;
             if (sb->frame && (sb->subControls & SC_SpinBoxFrame)) {
                 QRect r = subControlRect(CC_SpinBox, sb, SC_SpinBoxFrame, widget);
                 QWindowsCEStylePrivate::drawWinCEPanel(painter, r, option->palette, true);
             }
             QPalette shadePal(option->palette);
             shadePal.setColor(QPalette::Button, option->palette.light().color());
             shadePal.setColor(QPalette::Light, option->palette.button().color());
             bool reverse = QApplication::layoutDirection() == Qt::RightToLeft;
             if (sb->subControls & SC_SpinBoxUp) {
                 copy.subControls = SC_SpinBoxUp;
                 QPalette pal2 = sb->palette;
                 if (!(sb->stepEnabled & QAbstractSpinBox::StepUpEnabled)) {
                     pal2.setCurrentColorGroup(QPalette::Disabled);
                     copy.state &= ~State_Enabled;
                 }
                 copy.palette = pal2;
                 if (sb->activeSubControls == SC_SpinBoxUp && (sb->state & State_Sunken)) {
                     copy.state |= State_On;
                     copy.state |= State_Sunken;
                 } else {
                     copy.state |= State_Raised;
                     copy.state &= ~State_Sunken;
                 }
                 if (reverse)
                     pe = (sb->buttonSymbols == QAbstractSpinBox::PlusMinus ? PE_IndicatorSpinMinus
                     : PE_IndicatorSpinDown);
                 else
                     pe = (sb->buttonSymbols == QAbstractSpinBox::PlusMinus ? PE_IndicatorSpinPlus
                     : PE_IndicatorSpinUp);
                 copy.rect = subControlRect(CC_SpinBox, sb, SC_SpinBoxUp, widget);
                 QWindowsCEStylePrivate::drawWinCEButton(painter, copy.rect, option->palette, copy.state & (State_Sunken | State_On),
                                 &copy.palette.brush(QPalette::Button));
                 copy.rect.adjust(3, 0, -4, 0);
                 drawPrimitive(pe, &copy, painter, widget);
             }
             if (sb->subControls & SC_SpinBoxDown) {
                 copy.subControls = SC_SpinBoxDown;
                 copy.state = sb->state;
                 QPalette pal2 = sb->palette;
                 if (!(sb->stepEnabled & QAbstractSpinBox::StepDownEnabled)) {
                     pal2.setCurrentColorGroup(QPalette::Disabled);
                     copy.state &= ~State_Enabled;
                 }
                 copy.palette = pal2;
                 if (sb->activeSubControls == SC_SpinBoxDown && (sb->state & State_Sunken)) {
                     copy.state |= State_On;
                     copy.state |= State_Sunken;
                 } else {
                     copy.state |= State_Raised;
                     copy.state &= ~State_Sunken;
                 }
                 if (reverse)
                     pe = (sb->buttonSymbols == QAbstractSpinBox::PlusMinus ? PE_IndicatorSpinPlus
                     : PE_IndicatorSpinUp);
                 else
                     pe = (sb->buttonSymbols == QAbstractSpinBox::PlusMinus ? PE_IndicatorSpinMinus
                     : PE_IndicatorSpinDown);
                 copy.rect = subControlRect(CC_SpinBox, sb, SC_SpinBoxDown, widget);
                 QWindowsCEStylePrivate::drawWinCEButton(painter, copy.rect, shadePal, copy.state & (State_Sunken | State_On),
                                 &copy.palette.brush(QPalette::Button));
                 copy.rect.adjust(3, 0, -4, 0);
                 if (pe == PE_IndicatorArrowUp || pe == PE_IndicatorArrowDown) {
                     copy.rect = copy.rect.adjusted(1, 1, -1, -1);
                     drawPrimitive(pe, &copy, painter, widget);
                 }
                 else {
                     drawPrimitive(pe, &copy, painter, widget);
                 }
                 if (sb->frame && (sb->subControls & SC_SpinBoxFrame)) {
                     QRect r = subControlRect(CC_SpinBox, sb, SC_SpinBoxEditField, widget);
                     painter->save();
                     painter->setPen(option->palette.light().color());
                     painter->drawLine(r.x() + 1 + r.width(), r.y() - 2, r.x() + 1 + r.width(), r.y() + r.height() + 1);
                     painter->setPen(option->palette.midlight().color());
                     painter->drawLine(r.x() + r.width(), r.y() - 1, r.x() + r.width(), r.y() + r.height());
                     painter->restore();
                 }
             }
         }
         break;
 #endif // QT_NO_SPINBOX
     default:
         QWindowsStyle::drawComplexControl(control, option, painter, widget);
         break;
     }
 }
drawControl()
void QWindowsCEStyle::drawControl (ControlElement element, const QStyleOption * opt, QPainter * p, const QWidget * w) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 555 of file qwindowscestyle.cpp.
Referenced by drawComplexControl().
{
    switch (element) {
    #ifndef QT_NO_MENU
    case CE_MenuTearoff: {
         if(option->state & State_Selected) {
             if(pixelMetric(PM_MenuPanelWidth, option, widget) > 1)
                 qDrawShadePanel(painter, option->rect.x(), option->rect.y(), option->rect.width(),
                                 option->rect.height(), option->palette, false, 2,
                                 &option->palette.brush(QPalette::Button));
             else
                 qDrawShadePanel(painter, option->rect.x() + 1, option->rect.y() + 1, option->rect.width() - 2,
                                 option->rect.height() - 2, option->palette, true, 1, &option->palette.brush(QPalette::Button));
         } else {
             painter->fillRect(option->rect, option->palette.brush(QPalette::Button));
         }
         painter->setPen(QPen(option->palette.dark().color(), 1, Qt::DashLine));
         painter->drawLine(option->rect.x()+2, option->rect.y()+option->rect.height()/2-1, option->rect.x()+option->rect.width()-4,
                     option->rect.y()+option->rect.height()/2-1);
         painter->setPen(QPen(option->palette.light().color(), 1, Qt::DashLine));
         painter->drawLine(option->rect.x()+2, option->rect.y()+option->rect.height()/2, option->rect.x()+option->rect.width()-4,
                     option->rect.y()+option->rect.height()/2);
         break; }
    case CE_MenuBarItem:
         if (const QStyleOptionMenuItem *mbi = qstyleoption_cast<const QStyleOptionMenuItem *>(option)) {
             bool active = mbi->state & State_Selected;
             bool hasFocus = mbi->state & State_HasFocus;
             bool down = mbi->state & State_Sunken;
             QStyleOptionMenuItem newMbi = *mbi;
             if (active || hasFocus) {
                 QBrush b = mbi->palette.brush(QPalette::Highlight);
                 if (active && down) {
                     painter->fillRect(mbi->rect.adjusted(0, 1, 0, -1), b);
                 }
             }
             uint alignment = Qt::AlignCenter | Qt::TextShowMnemonic | Qt::TextDontClip
                             | Qt::TextSingleLine;
             if (!styleHint(SH_UnderlineShortcut, mbi, widget))
                 alignment |= Qt::TextHideMnemonic;
             painter->save();
             QFont f = painter->font();
             f.setBold(true);
             painter->setFont(f);
             QPixmap pix = mbi->icon.pixmap(pixelMetric(PM_SmallIconSize),
                                           (mbi->state & State_Enabled) ? QIcon::Normal : QIcon::Disabled);
             if (!pix.isNull())
                 drawItemPixmap(painter,mbi->rect, alignment, pix);
             else
                 if (active && down)
                   drawItemText(painter, mbi->rect, alignment, mbi->palette, mbi->state & State_Enabled,
                              mbi->text, QPalette::Light);
                 else
                   drawItemText(painter, mbi->rect, alignment, mbi->palette, mbi->state & State_Enabled,
                              mbi->text, QPalette::ButtonText);
             painter->restore();
         }
         break;
    case CE_MenuBarEmptyArea:
         painter->save();
         painter->setPen(option->palette.shadow().color());
         if (widget && !widget->testAttribute(Qt::WA_NoSystemBackground)) {
             painter->eraseRect(option->rect);
             QRect r = option->rect;
             painter->drawLine(r.x() + 1, r.y() + 1, r.x()+ 1, r.y()+ r.height() - 2);
             painter->drawLine(r.x() - 2 + r.width(), r.y()  + 1, r.x() - 2 + r.width(), r.y() + r.height() - 2);
             painter->drawLine(r.x() + 1, r.y() +1, r.x() - 1 + r.width(), r.y() + 1);
             painter->drawLine(r.x() + 1, r.y() + r.height()-2 , r.x() - 2 + r.width(), r.y() + r.height() - 2);
         }
         painter->restore();
         break;
     case CE_MenuItem:
           if (const QStyleOptionMenuItem *menuitem = qstyleoption_cast<const QStyleOptionMenuItem *>(option)) {
             int x, y, w, h;
             menuitem->rect.getRect(&x, &y, &w, &h);
             int tab = menuitem->tabWidth;
             bool dis = !(menuitem->state & State_Enabled);
             bool checked = menuitem->checkType != QStyleOptionMenuItem::NotCheckable
                             ? menuitem->checked : false;
             bool act = menuitem->state & State_Selected;
             // windows always has a check column, regardless whether we have an icon or not
             int checkcol = qMax(menuitem->maxIconWidth, windowsCheckMarkWidth);
             QBrush fill = menuitem->palette.brush(act ? QPalette::Highlight : QPalette::Button);
             painter->fillRect(menuitem->rect.adjusted(1, 1, 0, 0), fill);
             if (menuitem->menuItemType == QStyleOptionMenuItem::Separator) {
                 int yoff = y-1 + h / 2;
                 painter->setPen(menuitem->palette.shadow().color());
                 painter->drawLine(x + 4, yoff + 1, x + w - 8, yoff + 1);
                 return;
             }
             QRect vCheckRect = visualRect(option->direction, menuitem->rect, QRect(menuitem->rect.x(),
                                           menuitem->rect.y(), checkcol, menuitem->rect.height()));
             if (checked) {
                 if (act && !dis) {
                     qDrawPlainRect(painter, vCheckRect,
                         menuitem->palette.button().color(), 1,
                                     &menuitem->palette.brush(QPalette::Button));
                 } else {
                     QBrush fill(menuitem->palette.button().color(), Qt::Dense4Pattern);
                     qDrawPlainRect(painter, vCheckRect,menuitem->palette.button().color(), 1, &fill);
                 }
             } else if (!act) {
                 painter->fillRect(vCheckRect, menuitem->palette.brush(QPalette::Button));
             }
             // On Windows Style, if we have a checkable item and an icon we
             // draw the icon recessed to indicate an item is checked. If we
             // have no icon, we draw a checkmark instead.
             if (!menuitem->icon.isNull()) {
                 QIcon::Mode mode = dis ? QIcon::Disabled : QIcon::Normal;
                 if (act && !dis)
                     mode = QIcon::Active;
                 QPixmap pixmap;
                 if (checked)
                     pixmap = menuitem->icon.pixmap(pixelMetric(PM_SmallIconSize), mode, QIcon::On);
                 else
                     pixmap = menuitem->icon.pixmap(pixelMetric(PM_SmallIconSize), mode);
                 int pixw = pixmap.width();
                 int pixh = pixmap.height();
                 if (act && !dis && !checked)
                     qDrawPlainRect(painter, vCheckRect,  menuitem->palette.button().color(), 1,
                                     &menuitem->palette.brush(QPalette::Button));
                 QRect pmr(0, 0, pixw, pixh);
                 pmr.moveCenter(vCheckRect.center());
                 painter->setPen(menuitem->palette.text().color());
                 painter->drawPixmap(pmr.topLeft(), pixmap);
             } else if (checked) {
                 QStyleOptionMenuItem newMi = *menuitem;
                 newMi.state = State_None;
                 if (!dis)
                     newMi.state |= State_Enabled;
                 if (act)
                     newMi.state |= State_On;
                 newMi.rect = visualRect(option->direction, menuitem->rect, QRect(menuitem->rect.x()
                            + windowsItemFrame, menuitem->rect.y() + windowsItemFrame,
                              checkcol - 2 * windowsItemFrame, menuitem->rect.height() - 2*windowsItemFrame));
                 drawPrimitive(PE_IndicatorMenuCheckMark, &newMi, painter, widget);
             }
             painter->setPen(act ? menuitem->palette.highlightedText().color() : menuitem->palette.buttonText().color());
             QColor discol;
             if (dis) {
                 discol = menuitem->palette.text().color();
                 painter->setPen(discol);
             }
             int xm = windowsItemFrame + checkcol + windowsItemHMargin;
             int xpos = menuitem->rect.x() + xm;
             QRect textRect(xpos, y + windowsItemVMargin, w - xm - windowsRightBorder - tab + 1, h - 2 * windowsItemVMargin);
             QRect vTextRect = visualRect(option->direction, menuitem->rect, textRect);
             QString s = menuitem->text;
             if (!s.isEmpty()) {                     // draw text
                 painter->save();
                 int t = s.indexOf(QLatin1Char('\t'));
                 int text_flags = Qt::AlignVCenter | Qt::TextShowMnemonic | Qt::TextDontClip | Qt::TextSingleLine;
                 if (!styleHint(SH_UnderlineShortcut, menuitem, widget))
                     text_flags |= Qt::TextHideMnemonic;
                 text_flags |= Qt::AlignLeft;
                 if (t >= 0) {
                     QRect vShortcutRect = visualRect(option->direction, menuitem->rect,
                         QRect(textRect.topRight(), QPoint(menuitem->rect.right(), textRect.bottom())));
                     if (dis && !act)
                         painter->setPen(discol);
                     painter->drawText(vShortcutRect, text_flags, s.mid(t + 1));
                     s = s.left(t);
                 }
                 QFont font = menuitem->font;
                 if (menuitem->menuItemType == QStyleOptionMenuItem::DefaultItem)
                     font.setBold(true);
                 painter->setFont(font);
                 if (dis && !act)
                     painter->setPen(discol);
                 painter->drawText(vTextRect, text_flags, s.left(t));
                 painter->restore();
             }
             if (menuitem->menuItemType == QStyleOptionMenuItem::SubMenu) {// draw sub menu arrow
                 int dim = (h - 2 * windowsItemFrame) / 2;
                 PrimitiveElement arrow;
                 arrow = (option->direction == Qt::RightToLeft) ? PE_IndicatorSpinDown : PE_IndicatorSpinUp;
                 xpos = x + w - windowsArrowHMargin - windowsItemFrame - dim;
                 QRect  vSubMenuRect = visualRect(option->direction, menuitem->rect, QRect(xpos, y + h / 2 - dim / 2, dim, dim));
                 QStyleOptionMenuItem newMI = *menuitem;
                 newMI.rect = vSubMenuRect;
                 newMI.state = dis ? State_None : State_Enabled;
                 if (act)
                     newMI.palette.setColor(QPalette::ButtonText,
                                            newMI.palette.highlightedText().color());
                 drawPrimitive(arrow, &newMI, painter, widget);
             }
         }
         break;
 #endif // QT_NO_MENU
     case CE_MenuVMargin:
         painter->fillRect(option->rect, Qt::white);
         break;
     case CE_MenuEmptyArea:
         QWindowsStyle::drawControl(element,option, painter, widget);
         break;
 #ifndef QT_NO_TABBAR
         case CE_TabBarTab:
             if (const QStyleOptionTab *tab = qstyleoption_cast<const QStyleOptionTab *>(option)) {
                 drawControl(CE_TabBarTabShape, tab, painter, widget);
                 drawControl(CE_TabBarTabLabel, tab, painter, widget);
             }
             break;
     case CE_TabBarTabShape:
         if (const QStyleOptionTab *tab = qstyleoption_cast<const QStyleOptionTab *>(option)) {
             bool rtlHorTabs = (tab->direction == Qt::RightToLeft
                                && (tab->shape == QTabBar::RoundedNorth
                                    || tab->shape == QTabBar::RoundedSouth));
             bool selected = tab->state & State_Selected;
             bool lastTab = ((!rtlHorTabs && tab->position == QStyleOptionTab::End)
                             || (rtlHorTabs
                                 && tab->position == QStyleOptionTab::Beginning));
             bool firstTab = ((!rtlHorTabs
                                && tab->position == QStyleOptionTab::Beginning)
                              || (rtlHorTabs
                                  && tab->position == QStyleOptionTab::End));
             bool onlyOne = tab->position == QStyleOptionTab::OnlyOneTab;
             bool previousSelected =
                 ((!rtlHorTabs
                   && tab->selectedPosition == QStyleOptionTab::PreviousIsSelected)
                 || (rtlHorTabs
                     && tab->selectedPosition == QStyleOptionTab::NextIsSelected));
             bool nextSelected =
                 ((!rtlHorTabs
                   && tab->selectedPosition == QStyleOptionTab::NextIsSelected)
                  || (rtlHorTabs
                      && tab->selectedPosition
                             == QStyleOptionTab::PreviousIsSelected));
             int tabBarAlignment = styleHint(SH_TabBar_Alignment, tab, widget);
             bool leftAligned = (!rtlHorTabs && tabBarAlignment == Qt::AlignLeft)
                                 || (rtlHorTabs
                                     && tabBarAlignment == Qt::AlignRight);
             bool rightAligned = (!rtlHorTabs && tabBarAlignment == Qt::AlignRight)
                                  || (rtlHorTabs
                                          && tabBarAlignment == Qt::AlignLeft);
             QColor light = tab->palette.light().color();
             QColor midlight = tab->palette.midlight().color();
             QColor dark = tab->palette.dark().color();
             QColor shadow = tab->palette.shadow().color();
             QColor background = tab->palette.background().color();
             int borderThinkness = pixelMetric(PM_TabBarBaseOverlap, tab, widget);
             if (selected)
                 borderThinkness /= 2;
             QRect r2(option->rect);
             int x1 = r2.left();
             int x2 = r2.right();
             int y1 = r2.top();
             int y2 = r2.bottom();
             switch (tab->shape) {
             default:
                 QCommonStyle::drawControl(element, tab, painter, widget);
                 break;
             case QTabBar::RoundedNorth: {
                 if (!selected) {
                     y1 += 2;
                     x1 += firstTab ? borderThinkness : 0;
                     x2 -= lastTab ? borderThinkness : 0;
                 }
                 painter->fillRect(QRect(x1 + 1, y1 + 1, (x2 - x1) - 1, (y2 - y1) - 2), tab->palette.background());
                 // Delete border
                 if (selected) {
                     painter->setPen(background);
                     painter->drawLine(x1, y2 - 1, x2, y2 - 1);
                     painter->drawLine(x1, y2 + 1, x2, y2 + 1);
                     painter->drawLine(x1, y2, x2, y2);
                 }
                 // Left
                 if (firstTab || selected || onlyOne || !previousSelected) {
                     painter->setPen(dark);
                     painter->drawLine(x1, y1 + 2, x1, y2 - ((onlyOne || firstTab) && selected && leftAligned ? 0 : borderThinkness));
                     painter->drawPoint(x1 + 1, y1 + 1);
                         painter->setPen(midlight);
                         painter->drawLine(x1 + 1, y1 + 2, x1 + 1, y2 -
                                          ((onlyOne || firstTab) && selected && leftAligned ? 0 : borderThinkness));
                 }
                 // Top
                 {
                     int beg = x1 + (previousSelected ? 0 : 2);
                     int end = x2 - (nextSelected ? 0 : 2);
                     painter->setPen(dark);
                     painter->drawLine(beg, y1, end, y1);
                     painter->setPen(midlight);
                     painter->drawLine(beg, y1 + 1, end, y1 + 1);
                 }
                 // Right
                 if (lastTab || selected || onlyOne || !nextSelected) {
                     painter->setPen(shadow);
                     painter->drawLine(x2, y1 + 2, x2, y2 - ((onlyOne || lastTab) && selected && rightAligned ? 0 : borderThinkness));
                     painter->drawPoint(x2 - 1, y1 + 1);
                     painter->setPen(dark);
                     painter->drawLine(x2 - 1, y1 + 2, x2 - 1, y2 - ((onlyOne || lastTab) && selected && rightAligned ? 0 : borderThinkness));
                 }
                 break; }
             case QTabBar::RoundedSouth: {
                 if (!selected) {
                     y2 -= 2;
                     x1 += firstTab ? borderThinkness : 0;
                     x2 -= lastTab ? borderThinkness : 0;
                 }
                 painter->fillRect(QRect(x1 + 1, y1 + 2, (x2 - x1) - 1, (y2 - y1) - 1), tab->palette.background());
                 // Delete border
                 if (selected) {
                     painter->setPen(background);
                     painter->drawLine(x1, y1 + 1, x2 - 1, y1 + 1);
                     painter->drawLine(x1, y1 - 1, x2 - 1, y1 - 1);
                     painter->drawLine(x1, y1, x2 - 1, y1);
                 }
                 // Left
                 if (firstTab || selected || onlyOne || !previousSelected) {
                     painter->setPen(dark);
                     painter->drawLine(x1, y2 - 2, x1, y1 + ((onlyOne || firstTab) && selected && leftAligned ? 0 : borderThinkness));
                     painter->drawPoint(x1 + 1, y2 - 1);
                     painter->setPen(midlight);
                     painter->drawLine(x1 + 1, y2 - 2, x1 + 1, y1 + ((onlyOne || firstTab) && selected && leftAligned ? 0 : borderThinkness));
                 }
                 // Bottom
                 {
                     int beg = x1 + (previousSelected ? 0 : 2);
                     int end = x2 - (nextSelected ? 0 : 2);
                     painter->setPen(shadow);
                     painter->drawLine(beg, y2, end, y2);
                     painter->setPen(dark);
                     painter->drawLine(beg, y2 - 1, end, y2 - 1);
                 }
                 // Right
                 if (lastTab || selected || onlyOne || !nextSelected) {
                     painter->setPen(shadow);
                     painter->drawLine(x2, y2 - 2, x2, y1 + ((onlyOne || lastTab) && selected &&
                                       rightAligned ? 0 : borderThinkness));
                     painter->drawPoint(x2 - 1, y2 - 1);
                     painter->setPen(dark);
                     painter->drawLine(x2 - 1, y2 - 2, x2 - 1, y1 + ((onlyOne || lastTab) && selected &&
                                       rightAligned ? 0 : borderThinkness));
                 }
                 break; }
             case QTabBar::RoundedWest: {
                 if (!selected) {
                     x1 += 2;
                     y1 += firstTab ? borderThinkness : 0;
                     y2 -= lastTab ? borderThinkness : 0;
                 }
                 painter->fillRect(QRect(x1 + 1, y1 + 1, (x2 - x1) - 2, (y2 - y1) - 1), tab->palette.background());
                 // Delete border
                 if (selected) {
                     painter->setPen(background);
                     painter->drawLine(x2 - 1, y1, x2 - 1, y2);
                     painter->drawLine(x2, y1, x2, y2);
                 }
                 // Top
                 if (firstTab || selected || onlyOne || !previousSelected) {
                     painter->setPen(dark);
                     painter->drawLine(x1 + 2, y1, x2 - ((onlyOne || firstTab) && selected &&
                                       leftAligned ? 0 : borderThinkness), y1);
                     painter->drawPoint(x1 + 1, y1 + 1);
                     painter->setPen(midlight);
                     painter->drawLine(x1 + 2, y1 + 1, x2 - ((onlyOne || firstTab) && selected &&
                                       leftAligned ? 0 : borderThinkness), y1 + 1);
                 }
                 // Left
                 {
                     int beg = y1 + (previousSelected ? 0 : 2);
                     int end = y2 - (nextSelected ? 0 : 2);
                     painter->setPen(dark);
                     painter->drawLine(x1, beg, x1, end);
                     painter->setPen(midlight);
                     painter->drawLine(x1 + 1, beg, x1 + 1, end);
                 }
                 // Bottom
                 if (lastTab || selected || onlyOne || !nextSelected) {
                     painter->setPen(shadow);
                     painter->drawLine(x1 + 3, y2, x2 - ((onlyOne || lastTab) && selected &&
                                       rightAligned ? 0 : borderThinkness), y2);
                     painter->drawPoint(x1 + 2, y2 - 1);
                     painter->setPen(dark);
                     painter->drawLine(x1 + 3, y2 - 1, x2 - ((onlyOne || lastTab) && selected &&
                                       rightAligned ? 0 : borderThinkness), y2 - 1);
                     painter->drawPoint(x1 + 1, y2 - 1);
                     painter->drawPoint(x1 + 2, y2);
                 }
                 break; }
             case QTabBar::RoundedEast: {
                 if (!selected) {
                     x2 -= 2;
                     y1 += firstTab ? borderThinkness : 0;
                     y2 -= lastTab ? borderThinkness : 0;
                 }
                 painter->fillRect(QRect(x1 + 2, y1 + 1, (x2 - x1) - 1, (y2 - y1) - 1), tab->palette.background());
                 // Delete border
                 if (selected) {
                     painter->setPen(background);
                     painter->drawLine(x1 + 1, y1, x1 + 1, y2 - 1);
                     painter->drawLine(x1, y1, x1, y2 - 1);
                 }
                 // Top
                 if (firstTab || selected || onlyOne || !previousSelected) {
                     painter->setPen(dark);
                     painter->drawLine(x2 - 2, y1, x1 + ((onlyOne || firstTab) && selected &&
                                       leftAligned ? 0 : borderThinkness), y1);
                     painter->drawPoint(x2 - 1, y1 + 1);
                     painter->setPen(midlight);
                     painter->drawLine(x2 - 3, y1 + 1, x1 + ((onlyOne || firstTab) &&
                                       selected && leftAligned ? 0 : borderThinkness), y1 + 1);
                     painter->drawPoint(x2 - 1, y1);
                 }
                 // Right
                 {
                     int beg = y1 + (previousSelected ? 0 : 2);
                     int end = y2 - (nextSelected ? 0 : 2);
                     painter->setPen(shadow);
                     painter->drawLine(x2, beg, x2, end);
                     painter->setPen(dark);
                     painter->drawLine(x2 - 1, beg, x2 - 1, end);
                 }
                 // Bottom
                 if (lastTab || selected || onlyOne || !nextSelected) {
                     painter->setPen(shadow);
                     painter->drawLine(x2 - 2, y2, x1 + ((onlyOne || lastTab) &&
                                       selected && rightAligned ? 0 : borderThinkness), y2);
                     painter->drawPoint(x2 - 1, y2 - 1);
                     painter->setPen(dark);
                     painter->drawLine(x2 - 2, y2 - 1, x1 + ((onlyOne || lastTab) &&
                                       selected && rightAligned ? 0 : borderThinkness), y2 - 1);
                 }
                 break; }
             }
         }
         break;
 #endif // QT_NO_TABBAR
     case CE_ToolBar: {
         QRect rect = option->rect;
         painter->setPen(QPen(option->palette.dark().color()));
         painter->drawLine(rect.topRight().x()-1,
             rect.topRight().y(),
             rect.bottomRight().x()-1,
             rect.bottomRight().y());
         painter->drawLine(rect.bottomLeft().x(),
             rect.bottomLeft().y(),
             rect.bottomRight().x(),
             rect.bottomRight().y());
         painter->setPen(QPen(option->palette.light().color()));
         painter->drawLine(rect.topRight().x(),
             rect.topRight().y(),
             rect.bottomRight().x(),
             rect.bottomRight().y());
         painter->drawLine(rect.topLeft().x(),
             rect.topLeft().y(),
             rect.topRight().x(),
             rect.topRight().y());
         break; }
 #ifndef QT_NO_SCROLLBAR
     case CE_ScrollBarSubLine:
     case CE_ScrollBarAddLine: {
         if (option->state & State_Sunken) {
             QStyleOption buttonOpt = *option;
             drawPrimitive(PE_PanelButtonBevel, &buttonOpt, painter, widget);
         } else {
             QStyleOption buttonOpt = *option;
             if (!(buttonOpt.state & State_Sunken))
                 buttonOpt.state |= State_Raised;
             drawPrimitive(PE_PanelButtonBevel, &buttonOpt, painter, widget);
         }
         PrimitiveElement arrow;
         if (option->state & State_Horizontal) {
             if (element == CE_ScrollBarAddLine)
                 arrow = option->direction == Qt::LeftToRight ? PE_IndicatorArrowRight : PE_IndicatorArrowLeft;
             else
                 arrow = option->direction == Qt::LeftToRight ? PE_IndicatorArrowLeft : PE_IndicatorArrowRight;
         } else {
             if (element == CE_ScrollBarAddLine)
                 arrow = PE_IndicatorArrowDown;
             else
                 arrow = PE_IndicatorArrowUp;
         }
         drawPrimitive(arrow, option, painter, widget);
         break; }
     case CE_ScrollBarAddPage:
     case CE_ScrollBarSubPage: {
             QBrush br;
             QBrush bg = painter->background();
             Qt::BGMode bg_mode = painter->backgroundMode();
             painter->setPen(Qt::NoPen);
             painter->setBackgroundMode(Qt::OpaqueMode);
             if (option->state & State_Sunken) {
                 br = QBrush(option->palette.shadow().color(), Qt::Dense4Pattern);
                 painter->setBackground(option->palette.dark().color());
                 painter->setBrush(br);
             } else {
                 QPixmap pm = option->palette.brush(QPalette::Light).texture();
                 if (option->state & State_Enabled)
                     br = !pm.isNull() ? QBrush(pm) : QBrush(option->palette.button().color(), Qt::Dense4Pattern);
                 else
                     br = !pm.isNull() ? QBrush(pm) : QBrush(option->palette.light().color(), Qt::Dense4Pattern);
                 painter->setBackground(option->palette.base().color());
                 painter->setBrush(br);
             }
             painter->drawRect(option->rect);
             painter->setBackground(bg);
             painter->setBackgroundMode(bg_mode);
             break; }
     case CE_ScrollBarSlider:
         if (!(option->state & State_Enabled)) {
             QStyleOptionButton buttonOpt;
             buttonOpt.QStyleOption::operator=(*option);
             buttonOpt.state = State_Enabled | State_Raised;
             drawPrimitive(PE_PanelButtonBevel, &buttonOpt, painter, widget);
             QPixmap pm = option->palette.brush(QPalette::Light).texture();
             QBrush br = !pm.isNull() ? QBrush(pm) : QBrush(option->palette.light().color(), Qt::Dense4Pattern);
             painter->setPen(Qt::NoPen);
             painter->setBrush(br);
             painter->setBackgroundMode(Qt::OpaqueMode);
             painter->drawRect(option->rect.adjusted(2, 2, -2, -2));
         } else {
             QStyleOptionButton buttonOpt;
             buttonOpt.QStyleOption::operator=(*option);
             buttonOpt.state = State_Enabled | State_Raised;
             drawPrimitive(PE_PanelButtonBevel, &buttonOpt, painter, widget);
         }
         break;
 #endif // QT_NO_SCROLLBAR
     case CE_HeaderSection: {
         QBrush fill;
         if (option->state & State_On)
             fill = QBrush(option->palette.light().color(), Qt::Dense4Pattern);
         else
             fill = option->palette.brush(QPalette::Button);
         if (option->state & (State_Raised | State_Sunken)) {
             QWindowsCEStylePrivate::drawWinCEButton(painter, option->rect, option->palette,
                                                     option->state & State_Sunken, &fill);
         } else {
             painter->fillRect(option->rect, fill);
         }
         break; }
     case CE_DockWidgetTitle:
         QWindowsStyle::drawControl(element,option, painter, widget);
         break;
         case CE_PushButtonLabel:
         if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(option)) {
             painter->save();
             QFont f = painter->font();
             f.setBold(true);
             painter->setFont(f);
             QRect ir = btn->rect;
             uint tf = Qt::AlignVCenter | Qt::TextShowMnemonic;
             if (!styleHint(SH_UnderlineShortcut, btn, widget))
                 tf |= Qt::TextHideMnemonic;
             if (btn->state & (State_On | State_Sunken))
                 ir.translate(pixelMetric(PM_ButtonShiftHorizontal, option, widget),
                              pixelMetric(PM_ButtonShiftVertical, option, widget));
             if (!btn->icon.isNull()) {
                 QIcon::Mode mode = btn->state & State_Enabled ? QIcon::Normal
                                                               : QIcon::Disabled;
                 if (mode == QIcon::Normal && btn->state & State_HasFocus)
                     mode = QIcon::Active;
                 QIcon::State state = QIcon::Off;
                 if (btn->state & State_On)
                     state = QIcon::On;
                 QPixmap pixmap = btn->icon.pixmap(btn->iconSize, mode, state);
                 int pixw = pixmap.width();
                 int pixh = pixmap.height();
                 //Center the icon if there is no text
                 QPoint point;
                 if (btn->text.isEmpty()) {
                     point = QPoint(ir.x() + ir.width() / 2 - pixw / 2,
                                    ir.y() + ir.height() / 2 - pixh / 2);
                 } else {
                     point = QPoint(ir.x() + 2, ir.y() + ir.height() / 2 - pixh / 2);
                 }
                 if (btn->direction == Qt::RightToLeft)
                     point.rx() += pixw;
                 if ((btn->state & (State_On | State_Sunken)) && btn->direction == Qt::RightToLeft)
                     point.rx() -= pixelMetric(PM_ButtonShiftHorizontal, option, widget) * 2;
                 painter->drawPixmap(visualPos(btn->direction, btn->rect, point), pixmap);
                 if (btn->direction == Qt::RightToLeft)
                     ir.translate(-4, 0);
                 else
                     ir.translate(pixw + 4, 0);
                 ir.setWidth(ir.width() - (pixw + 4));
                 // left-align text if there is
                 if (!btn->text.isEmpty())
                     tf |= Qt::AlignLeft;
             } else {
                 tf |= Qt::AlignHCenter;
             }
             drawItemText(painter, ir, tf, btn->palette, (btn->state & State_Enabled),
                          btn->text, QPalette::ButtonText);
             painter->restore();
         }
         break;
         default:
             QWindowsStyle::drawControl(element, option, painter, widget);
             break;
     }
 }
drawItemText()
void QWindowsCEStyle::drawItemText (QPainter * painter, const QRect & rectangle, int alignment, const QPalette & palette, bool enabled, const QString & text, QPalette::ColorRole textRole = QPalette::NoRole) const virtual
Draws the given text in the specified rectangle using the provided painter and palette.
The text is drawn using the painter's pen, and aligned and wrapped according to the specified alignment. If an explicit textRole is specified, the text is drawn using the palette's color for the given role. The enabled parameter indicates whether or not the item is enabled; when reimplementing this function, the enabled parameter should influence how the item is drawn.
See also
Qt::Alignment, drawItemPixmap()
Reimplemented from QStyle.
Definition at line 1755 of file qwindowscestyle.cpp.
Referenced by drawComplexControl(), and drawControl().
{
     if (text.isEmpty())
         return;
     QPen savedPen;
     if (textRole != QPalette::NoRole) {
         savedPen = painter->pen();
         painter->setPen(pal.color(textRole));
     }
     if (!enabled) {
             QPen pen = painter->pen();
             painter->setPen(pal.light().color());
             //painter->drawText(rect.adjusted(1, 1, 1, 1), alignment, text);
             painter->setPen(pen);
         }
     painter->drawText(rect, alignment, text);
     if (textRole != QPalette::NoRole)
         painter->setPen(savedPen);
 }
drawPrimitive()
void QWindowsCEStyle::drawPrimitive (PrimitiveElement pe, const QStyleOption * opt, QPainter * p, const QWidget * w = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 82 of file qwindowscestyle.cpp.
Referenced by drawComplexControl(), and drawControl().
{
     bool doRestore = false;
     QRect rect = option->rect;
     switch (element) {
     case PE_PanelButtonTool: {
         if (
 #ifndef QT_NO_TOOLBAR
              (widget && qobject_cast<QToolBar*>(widget->parentWidget())) ||
 #endif
 #ifndef QT_NO_DOCKWIDGET
              (widget && widget->inherits("QDockWidgetTitleButton")) ||
 #endif
             (option->state & (State_Sunken | State_On)))
                QWindowsCEStylePrivate::drawWinCEButton(painter, option->rect.adjusted(0, 0, 0, 0),
                   option->palette, option->state & (State_Sunken | State_On),
                   &option->palette.button());
         if (option->state & (State_On)){
             QBrush fill = QBrush(option->palette.midlight().color(), Qt::Dense4Pattern);
             painter->fillRect(option->rect.adjusted(windowsItemFrame , windowsItemFrame ,
                               -windowsItemFrame , -windowsItemFrame ), fill);
         }
         break; }
     case PE_IndicatorButtonDropDown:
         QWindowsCEStylePrivate::drawWinCEButton(painter, option->rect, option->palette,
             option->state & (State_Sunken | State_On),
             &option->palette.brush(QPalette::Button));
         break;
 #ifndef QT_NO_TABBAR
         case PE_IndicatorTabTear:
         if (const QStyleOptionTab *tab = qstyleoption_cast<const QStyleOptionTab *>(option)) {
             bool rtl = tab->direction == Qt::RightToLeft;
             QRect rect = tab->rect;
             QPainterPath path;
             rect.setTop(rect.top() + ((tab->state & State_Selected) ? 1 : 3));
             rect.setBottom(rect.bottom() - ((tab->state & State_Selected) ? 0 : 2));
             path.moveTo(QPoint(rtl ? rect.right() : rect.left(), rect.top()));
             int count = 3;
             for(int jags = 1; jags <= count; ++jags, rtl = !rtl)
                 path.lineTo(QPoint(rtl ? rect.left() : rect.right(), rect.top() + jags * rect.height()/count));
             painter->setPen(QPen(tab->palette.light(), qreal(.8)));
             painter->setBrush(tab->palette.background());
             painter->setRenderHint(QPainter::Antialiasing);
             painter->drawPath(path);
         }
         break;
 #endif //QT_NO_TABBAR
 #ifndef QT_NO_TOOLBAR
         case PE_IndicatorToolBarSeparator:
             //nothing to draw on WindowsCE
             break;
         case PE_IndicatorToolBarHandle:
             painter->save();
             painter->translate(option->rect.x(), option->rect.y());
             if (option->state & State_Horizontal) {
                 int x = option->rect.width() / 2 - 4;
                 if (QApplication::layoutDirection() == Qt::RightToLeft)
                     x -= 2;
                 if (option->rect.height() > 4) {
                     QWindowsCEStylePrivate::drawWinCEButton(painter,x - 1, 0, 7, option->rect.height(),
                         option->palette, false,  0);
                     QWindowsCEStylePrivate::drawWinCEPanel(painter, x, 1, 3, option->rect.height() - 1,
                         option->palette, false, 0);
                     QWindowsCEStylePrivate::drawWinCEPanel(painter, x + 3, 1, 3, option->rect.height() - 1,
                         option->palette, false, 0);
                     painter->setPen(option->palette.button().color());
                     painter->drawLine(x + 4, 2, x + 4,option->rect.height() - 2);
                 }
             } else {
                 if (option->rect.width() > 4) {
                     int y = option->rect.height() / 2 - 4;
                     QWindowsCEStylePrivate::drawWinCEPanel(painter, 2, y, option->rect.width() - 2, 3,
                         option->palette, false,  0);
                     QWindowsCEStylePrivate::drawWinCEPanel(painter, 2, y + 3, option->rect.width() - 2, 3,
                         option->palette, false,  0);
                 }
             }
             painter->restore();
             break;
 #endif // QT_NO_TOOLBAR
         case PE_FrameButtonTool: {
 #ifndef QT_NO_DOCKWIDGET
             if (widget && widget->inherits("QDockWidgetTitleButton")) {
                 if (const QDockWidget *dw = qobject_cast<const QDockWidget *>(widget->parent()))
                     if (dw->isFloating()){
                         QWindowsCEStylePrivate::drawWinCEButton(painter, option->rect.adjusted(1, 1, 0, 0),
                                                                 option->palette, option->state & (State_Sunken | State_On),
                             &option->palette.button());
                         return;
                     }
             }
 #endif // QT_NO_DOCKWIDGET
         QBrush fill;
         bool stippled;
         bool panel = (element == PE_PanelButtonTool);
         if ((!(option->state & State_Sunken ))
             && (!(option->state & State_Enabled)
             || ((option->state & State_Enabled ) && !(option->state & State_MouseOver)))
             && (option->state & State_On)) {
                 fill = QBrush(option->palette.light().color(), Qt::Dense4Pattern);
                 stippled = true;
         } else {
             fill = option->palette.brush(QPalette::Button);
             stippled = false;
         }
         if (option->state & (State_Raised | State_Sunken | State_On)) {
             if (option->state & State_AutoRaise) {
                 if(option->state & (State_Enabled | State_Sunken | State_On)){
                     if (panel)
                         QWindowsCEStylePrivate::drawWinCEPanel(painter, option->rect, option->palette,
                         option->state & (State_Sunken | State_On), &fill);
                     else
                         qDrawShadeRect(painter, option->rect, option->palette,
                         option->state & (State_Sunken | State_On), 1);
                 }
                 if (stippled) {
                     painter->setPen(option->palette.button().color());
                     painter->drawRect(option->rect.adjusted(1, 1, -2, -2));
                 }
             } else {
                 QWindowsCEStylePrivate::drawWinCEButton(painter, option->rect, option->palette,
                     option->state & (State_Sunken | State_On), panel ? &fill : 0);
             }
         } else {
             painter->fillRect(option->rect, fill);
         }
         break; }
     case PE_PanelButtonBevel: {
         QBrush fill;
         bool panel = element != PE_FrameButtonBevel;
         painter->setBrushOrigin(option->rect.topLeft());
         if (!(option->state & State_Sunken) && (option->state & State_On))
             fill = QBrush(option->palette.light().color(), Qt::Dense4Pattern);
         else
             fill = option->palette.brush(QPalette::Button);
         if (option->state & (State_Raised | State_On | State_Sunken)) {
             QWindowsCEStylePrivate::drawWinCEButton(painter, option->rect, option->palette,
                                                     option->state & (State_Sunken | State_On),
                 panel ? &fill : 0); ;
         } else {
             if (panel)
                 painter->fillRect(option->rect, fill);
             else
                 painter->drawRect(option->rect);
         }
         break; }
     case PE_FrameGroupBox:
         if (const QStyleOptionFrame *frame = qstyleoption_cast<const QStyleOptionFrame *>(option)) {
             QRect fr = frame->rect;
             painter->setPen(frame->palette.shadow().color());
             painter->drawRect(fr.x(), fr.y(), fr.x() + fr.width() - 1,
                               fr.y() + fr.height() - windowsCEFrameGroupBoxOffset);
         }
         break;
    case PE_IndicatorCheckBox: {
         QBrush fill;
         if (option->state & State_NoChange)
             fill = QBrush(option->palette.base().color(), Qt::Dense4Pattern);
         else if (option->state & State_Sunken)
             fill = option->palette.button();
         else if (option->state & State_Enabled)
             fill = option->palette.base();
         else
             fill = option->palette.background();
         painter->save();
         doRestore = true;
         painter->fillRect(option->rect,fill);
         painter->setPen(option->palette.dark().color());
         painter->drawRect(option->rect);
         painter->setPen(option->palette.shadow().color());
         painter->drawLine(option->rect.x() + 1,option->rect.y() + 1,
                           option->rect.x() + option->rect.width() - 1, option->rect.y() + 1);
         painter->drawLine(option->rect.x() + 1,option->rect.y() + 1,
                           option->rect.x() + 1, option->rect.y() + option->rect.height() - 1);
         //fall through...
     }
     case PE_IndicatorViewItemCheck:
     case PE_Q3CheckListIndicator: {
         if (!doRestore) {
             painter->save();
             doRestore = true;
         }
         int arrowSize= 2;
         if (element == PE_Q3CheckListIndicator || element == PE_IndicatorViewItemCheck) {
             QLinearGradient linearGradient(QPoint(option->rect.x(),option->rect.y()), QPoint(option->rect.x()+option->rect.width(),
                                            option->rect.y()+option->rect.height()));
             linearGradient.setColorAt(0, windowsCECheckBoxGradientColorBegin);
             linearGradient.setColorAt(1, windowsCECheckBoxGradientColorEnd);
             painter->setBrush(linearGradient);
             painter->setPen(Qt::NoPen);
             if (option->state & State_NoChange)
                 painter->setBrush(option->palette.brush(QPalette::Button));
             painter->setPen(option->palette.link().color());
             painter->drawRect(option->rect.x(), option->rect.y(), windowsCEitemViewCheckBoxSize, windowsCEitemViewCheckBoxSize);
             painter->setPen(option->palette.brightText().color());
             arrowSize= 3;
         }
         if (!(option->state & State_Off)) {
             QLineF lines[9];
             int i, xx, yy;
             xx = option->rect.x() + 4;
             yy = option->rect.y() + 6;
             for (i = 0; i < 4; ++i) {
                 lines[i] = QLineF(xx, yy, xx, yy + arrowSize);
                 ++xx;
                 ++yy;
             }
             yy -= 2;
             for (i = 4; i < 9; ++i) {
                 lines[i] = QLineF(xx, yy, xx, yy + arrowSize);
                 ++xx;
                 --yy;
             }
             painter->drawLines(lines, 9);
         }
         if (doRestore)
             painter->restore();
         break; }
     case PE_IndicatorRadioButton: {
         QRect ir = option->rect;
         painter->save();
         painter->setPen(Qt::NoPen);
         painter->setBrush(option->palette.light());
         painter->drawEllipse(option->rect);
         painter->setPen(option->palette.shadow().color());
         painter->setBrush(option->palette.shadow().color());
         painter->drawArc(option->rect, 0, 360 * 16);
         painter->drawArc(option->rect.x() + 1, option->rect.y() + 1, option->rect.width() - 2,
                          option->rect.height() - 2, 40 * 16, 180 * 16);
         painter->setPen(option->palette.light().color());
         painter->drawPoint(option->rect.x() + 11, option->rect.y() + 3);
         painter->drawPoint(option->rect.x() + 3,option->rect.y() + 3);
         painter->setPen(option->palette.shadow().color());
         painter->drawPoint(option->rect.x() +3,option->rect.y() + 12);
         if (option->state & (State_Sunken | State_On)) {
             painter->setPen(Qt::NoPen);
             painter->setBrush(option->palette.text());
             painter->drawEllipse(option->rect.x() +3,option->rect.y()+ 2,9,10);
         }
         painter->restore();
         break; }
    case PE_PanelMenuBar:
        painter->save();
        painter->setPen(option->palette.shadow().color());
        painter->drawRect(option->rect);
        painter->restore();
        break;
    case PE_PanelButtonCommand:
        if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(option)) {
            QBrush fill;
            State flags = option->state;
            QPalette pal = option->palette;
            QRect r = option->rect;
            if (! (flags & State_Sunken) && (flags & State_On))
                fill = QBrush(pal.light().color(), Qt::Dense4Pattern);
            else
                fill = pal.brush(QPalette::Button);
            if (btn->features & QStyleOptionButton::DefaultButton && flags & State_Sunken) {
                painter->setPen(pal.dark().color());
                painter->setBrush(fill);
                painter->drawRect(r.adjusted(0, 0, -1, -1));
            } else if (flags & (State_Raised | State_Sunken | State_On | State_Sunken)) {
                QWindowsCEStylePrivate::drawWinCEButton(painter, r, pal, flags & (State_Sunken | State_On),
                    &fill);
            } else {
                painter->fillRect(r, fill);
            }
        }
        break;
    case PE_FrameDefaultButton: {
        painter->setPen(option->palette.shadow().color());
        QRect rect = option->rect;
        rect.adjust(0, 0, -1, -1);
        painter->drawRect(rect);
        break; }
    case PE_IndicatorSpinPlus:
    case PE_IndicatorSpinMinus: {
        QRect r = option->rect;
        int fw = pixelMetric(PM_DefaultFrameWidth, option, widget)+2;
        QRect br = r.adjusted(fw, fw, -fw, -fw);
        int offset = (option->state & State_Sunken) ? 1 : 0;
        int step = (br.width() + 4) / 5;
        painter->fillRect(br.x() + offset, br.y() + offset +br.height() / 2 - step / 2,
            br.width(), step,
            option->palette.buttonText());
        if (element == PE_IndicatorSpinPlus)
            painter->fillRect(br.x() + br.width() / 2 - step / 2 + offset, br.y() + offset+4,
            step, br.height()-7,
            option->palette.buttonText());
        break; }
     case PE_IndicatorSpinUp:
     case PE_IndicatorSpinDown: {
         painter->save();
             QPoint points[7];
             switch (element) {
                 case PE_IndicatorSpinUp:
                     points[0] = QPoint(-2, -4);
                     points[1] = QPoint(-2, 2);
                     points[2] = QPoint(-1, -3);
                     points[3] = QPoint(-1, 1);
                     points[4] = QPoint(0, -2);
                     points[5] = QPoint(0, 0);
                     points[6] = QPoint(1, -1);
                 break;
                 case PE_IndicatorSpinDown:
                     points[0] = QPoint(0, -4);
                     points[1] = QPoint(0, 2);
                     points[2] = QPoint(-1, -3);
                     points[3] = QPoint(-1, 1);
                     points[4] = QPoint(-2, -2);
                     points[5] = QPoint(-2, 0);
                     points[6] = QPoint(-3, -1);
                 break;
                 default:
                 break;
             }
             if (option->state & State_Sunken)
                 painter->translate(pixelMetric(PM_ButtonShiftHorizontal),
                 pixelMetric(PM_ButtonShiftVertical));
             if (option->state & State_Enabled) {
                 painter->translate(option->rect.x() + option->rect.width() / 2,
                                    option->rect.y() + option->rect.height() / 2);
                 painter->setPen(option->palette.buttonText().color());
                 painter->drawLine(points[0], points[1]);
                 painter->drawLine(points[2], points[3]);
                 painter->drawLine(points[4], points[5]);
                 painter->drawPoint(points[6]);
             } else {
                 painter->translate(option->rect.x() + option->rect.width() / 2 + 1,
                                    option->rect.y() + option->rect.height() / 2 + 1);
                 painter->setPen(option->palette.light().color());
                 painter->drawLine(points[0], points[1]);
                 painter->drawLine(points[2], points[3]);
                 painter->drawLine(points[4], points[5]);
                 painter->drawPoint(points[6]);
                 painter->translate(-1, -1);
                 painter->setPen(option->palette.mid().color());
                 painter->drawLine(points[0], points[1]);
                 painter->drawLine(points[2], points[3]);
                 painter->drawLine(points[4], points[5]);
                 painter->drawPoint(points[6]);
             }
         painter->restore();
         break; }
     case PE_IndicatorArrowUp:
     case PE_IndicatorArrowDown:
     case PE_IndicatorArrowRight:
     case PE_IndicatorArrowLeft: {
             painter->save();
             QPoint points[9];
             switch (element) {
                 case PE_IndicatorArrowUp:
                     points[0] = QPoint(-4, 2);
                     points[1] = QPoint(4, 2);
                     points[2] = QPoint(-3, 1);
                     points[3] = QPoint(3, 1);
                     points[4] = QPoint(-2, 0);
                     points[5] = QPoint(2, 0);
                     points[6] = QPoint(-1, -1);
                     points[7] = QPoint(1, -1);
                     points[8] = QPoint(0, -2);
                 break;
                 case PE_IndicatorArrowDown:
                     points[0] = QPoint(-4, -2);
                     points[1] = QPoint(4, -2);
                     points[2] = QPoint(-3, -1);
                     points[3] = QPoint(3, -1);
                     points[4] = QPoint(-2, 0);
                     points[5] = QPoint(2, 0);
                     points[6] = QPoint(-1, 1);
                     points[7] = QPoint(1, 1);
                     points[8] = QPoint(0, 2);
                 break;
                 case PE_IndicatorArrowRight:
                     points[0] = QPoint(-3, -4);
                     points[1] = QPoint(-3, 4);
                     points[2] = QPoint(-2, -3);
                     points[3] = QPoint(-2, 3);
                     points[4] = QPoint(-1, -2);
                     points[5] = QPoint(-1, 2);
                     points[6] = QPoint(0, -1);
                     points[7] = QPoint(0, 1);
                     points[8] = QPoint(1, 0);
                 break;
                 case PE_IndicatorArrowLeft:
                     points[0] = QPoint(1, -4);
                     points[1] = QPoint(1, 4);
                     points[2] = QPoint(0, -3);
                     points[3] = QPoint(0, 3);
                     points[4] = QPoint(-1, -2);
                     points[5] = QPoint(-1, 2);
                     points[6] = QPoint(-2, -1);
                     points[7] = QPoint(-2, 1);
                     points[8] = QPoint(-3, 0);
                 break;
                 default:
                 break;
             }
             if (option->state & State_Sunken)
                 painter->translate(pixelMetric(PM_ButtonShiftHorizontal),
                 pixelMetric(PM_ButtonShiftVertical));
             if (option->state & State_Enabled) {
                 painter->translate(option->rect.x() + option->rect.width() / 2,
                     option->rect.y() + option->rect.height() / 2);
                 painter->setPen(option->palette.buttonText().color());
                 painter->drawLine(points[0], points[1]);
                 painter->drawLine(points[2], points[3]);
                 painter->drawLine(points[4], points[5]);
                 painter->drawLine(points[6], points[7]);
                 painter->drawPoint(points[8]);
             } else {
                 painter->translate(option->rect.x() + option->rect.width() / 2 + 1,
                     option->rect.y() + option->rect.height() / 2 + 1);
                 painter->setPen(option->palette.light().color());
                 painter->drawLine(points[0], points[1]);
                 painter->drawLine(points[2], points[3]);
                 painter->drawLine(points[4], points[5]);
                 painter->drawLine(points[6], points[7]);
                 painter->drawPoint(points[8]);
                 painter->translate(-1, -1);
                 painter->setPen(option->palette.mid().color());
                 painter->drawLine(points[0], points[1]);
                 painter->drawLine(points[2], points[3]);
                 painter->drawLine(points[4], points[5]);
                 painter->drawLine(points[6], points[7]);
                 painter->drawPoint(points[8]);
             }
         painter->restore();
         break; }
     case PE_FrameWindow: {
         QPalette popupPal = option->palette;
         popupPal.setColor(QPalette::Light, option->palette.background().color());
         popupPal.setColor(QPalette::Midlight, option->palette.light().color());
         QWindowsCEStylePrivate::drawWinCEPanel(painter, option->rect, popupPal, option->state & State_Sunken);
         break; }
     case PE_Frame:
     case PE_FrameMenu:
         if (const QStyleOptionFrame *frame = qstyleoption_cast<const QStyleOptionFrame *>(option)) {
             QPalette popupPal = frame->palette;
             QRect r = frame->rect;
             qDrawPlainRect(painter, r, frame->palette.shadow().color(),1);
         }
         break;
     case PE_FrameStatusBar:
         QWindowsCEStylePrivate::drawWinCEPanel(painter, option->rect, option->palette, true, 0);
         break;
     case PE_FrameTabWidget: {
         QRect rect = option->rect;
         QPalette pal = option->palette;
         QWindowsCEStylePrivate::drawWinCEButton(painter, option->rect, option->palette, false, 0);
         break; }
     default:
         QWindowsStyle::drawPrimitive(element, option, painter, widget);
         break;
     }
 }
hitTestComplexControl()
QStyle::SubControl QWindowsCEStyle::hitTestComplexControl (ComplexControl cc, const QStyleOptionComplex * opt, const QPoint & pt, const QWidget * w = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2066 of file qwindowscestyle.cpp.
{
     /*switch (control) {
     default:
         break;
     }*/
     return QWindowsStyle::hitTestComplexControl(control, option, pos, widget);
 }
pixelMetric()
int QWindowsCEStyle::pixelMetric (PixelMetric m, const QStyleOption * opt = 0, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2106 of file qwindowscestyle.cpp.
Referenced by drawComplexControl(), drawControl(), drawPrimitive(), sizeFromContents(), and subControlRect().
{
     int ret;
     switch (pm) {
     case PM_DefaultFrameWidth:
         ret = 1;
         break;
     case PM_MenuBarHMargin:
         ret = 2;
         break;
     case PM_MenuBarVMargin:
         ret = 2;
         break;
     /*case PM_MenuBarItemSpacing:
         ret = 2;
         break;*/
     case PM_MenuButtonIndicator:
         ret = 10;
         break;
     case PM_SpinBoxFrameWidth:
         ret = 2;
         break;
     case PM_ButtonDefaultIndicator:
     case PM_ButtonShiftHorizontal:
     case PM_ButtonShiftVertical:
         ret = 1;
         break;
 #ifndef QT_NO_TABBAR
     case PM_TabBarTabShiftHorizontal:
         ret = 0;
         break;
     case PM_TabBarTabShiftVertical:
         ret = 6;
         break;
 #endif
     case PM_MaximumDragDistance:
         ret = 60;
         break;
       case PM_IndicatorWidth:
         ret = windowsCEIndicatorSize;
         break;
     case PM_IndicatorHeight:
         ret = windowsCEIndicatorSize;
         break;
     case PM_ExclusiveIndicatorWidth:
         ret = windowsCEExclusiveIndicatorSize;
         break;
     case PM_ExclusiveIndicatorHeight:
         ret = windowsCEExclusiveIndicatorSize;;
         break;
 #ifndef QT_NO_SLIDER
     case PM_SliderLength:
         ret = 12;
         break;
     case PM_SliderThickness:
         ret = windowsCESliderThickness;
         break;
      case PM_TabBarScrollButtonWidth:
         ret = 18;
         break;
         // Returns the number of pixels to use for the business part of the
         // slider (i.e., the non-tickmark portion). The remaining space is shared
         // equally between the tickmark regions.
     case PM_SliderControlThickness:
         if (const QStyleOptionSlider *sl = qstyleoption_cast<const QStyleOptionSlider *>(opt)) {
             int space = (sl->orientation == Qt::Horizontal) ? sl->rect.height() : sl->rect.width();
             int ticks = sl->tickPosition;
             int n = 0;
             if (ticks & QSlider::TicksAbove)
                 ++n;
             if (ticks & QSlider::TicksBelow)
                 ++n;
             if (!n) {
                 ret = space;
                 break;
             }
             int thick = 12;
             if (ticks != QSlider::TicksBothSides && ticks != QSlider::NoTicks)
                 thick += pixelMetric(PM_SliderLength, sl, widget) / 4;
             space -= thick;
             if (space > 0)
                 thick += (space * 2) / (n + 2);
             ret = thick;
         } else {
             ret = 0;
         }
         break;
 #endif // QT_NO_SLIDER
 #ifndef QT_NO_MENU
     case PM_SmallIconSize:
         ret = windowsCEIconSize;
         break;
     case PM_ButtonMargin:
         ret = 6;
         break;
     case PM_LargeIconSize:
         ret = 32;
         break;
     case PM_IconViewIconSize:
         ret = pixelMetric(PM_LargeIconSize, opt, widget);
         break;
     case PM_ToolBarIconSize:
         ret = windowsCEIconSize;
         break;
     case PM_DockWidgetTitleMargin:
         ret = 2;
         break;
 #if defined(Q_WS_WIN)
 //    case PM_DockWidgetFrameWidth:
 //        ret = GetSystemMetrics(SM_CXFRAME);
 //        break;
 #else
     case PM_DockWidgetFrameWidth:
         ret = 4;
         break;
 #endif // Q_WS_WIN
     break;
 #endif // QT_NO_MENU
    case PM_TitleBarHeight:
           ret = 30;
         break;
     case PM_ScrollBarExtent:
         ret = 19;
         break;
     case PM_SplitterWidth:
         ret = qMax(4, QApplication::globalStrut().width());
         break;
 #if defined(Q_WS_WIN)
     case PM_MDIFrameWidth:
         ret = 3;
         break;
 #endif
     case PM_ToolBarItemMargin:
         ret = 1;
         break;
     case PM_ToolBarItemSpacing:
         ret = 0;
         break;
     case PM_ToolBarHandleExtent:
         ret = 10;
         break;
     case PM_ButtonIconSize:
         ret = 22;
         break;
     default:
         ret = QWindowsStyle::pixelMetric(pm, opt, widget);
         break;
     }
     return ret;
 }
polish() [1/3]
void QWindowsCEStyle::polish (QWidget * widget) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2098 of file qwindowscestyle.cpp.
{
     QWindowsStyle::polish(widget);
 }
polish() [2/3]
void QWindowsCEStyle::polish (QPalette & pal) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2102 of file qwindowscestyle.cpp.
{
     QWindowsStyle::polish(palette);
 }
polish() [3/3]
void QWindowsCEStyle::polish (QApplication * app) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2094 of file qwindowscestyle.cpp.
{
     QWindowsStyle::polish(app);
 }
sizeFromContents()
QSize QWindowsCEStyle::sizeFromContents (ContentsType ct, const QStyleOption * opt, const QSize & contentsSize, const QWidget * widget) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 1776 of file qwindowscestyle.cpp.
{
     QSize newSize = QWindowsStyle::sizeFromContents(type, option, size, widget);
     switch (type) {
     case CT_PushButton:
        if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(option)) {
             newSize = QWindowsStyle::sizeFromContents(type, option, size, widget);
             int w = newSize.width(),
                 h = newSize.height();
             int defwidth = 0;
             if (btn->features & QStyleOptionButton::AutoDefaultButton)
                 defwidth = 2 * pixelMetric(PM_ButtonDefaultIndicator, btn, widget);
             if (w < 75 + defwidth && btn->icon.isNull())
                 w = 75 + defwidth;
             if (h < 23 + defwidth)
                 h = 23 + defwidth;
             newSize = QSize(w+14, h);
         }
         break;
     case CT_RadioButton:
     case CT_CheckBox:
         if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(option)) {
             bool isRadio = (type == CT_RadioButton);
             QRect irect = visualRect(btn->direction, btn->rect,
                                      subElementRect(isRadio ? SE_RadioButtonIndicator
                                                             : SE_CheckBoxIndicator, btn, widget));
             int h = pixelMetric(isRadio ? PM_ExclusiveIndicatorHeight
                                         : PM_IndicatorHeight, btn, widget);
             int margins = (!btn->icon.isNull() && btn->text.isEmpty()) ? 0 : 10;
             newSize += QSize(irect.right() + margins, 4);
             newSize.setHeight(qMax(newSize.height(), h));
         }
         break;
     case CT_ComboBox:
         if (const QStyleOptionComboBox *cmb = qstyleoption_cast<const QStyleOptionComboBox *>(option)) {
             int fw = cmb->frame ? pixelMetric(PM_ComboBoxFrameWidth, option, widget) * 2 : 0;
             newSize = QSize(newSize.width() + fw -1, qMax(24, newSize.height() + fw-1));
         }
         break;
 #ifndef QT_NO_SPINBOX
     case CT_SpinBox:
         if (const QStyleOptionSpinBox *spnb = qstyleoption_cast<const QStyleOptionSpinBox *>(option)) {
             int fw = spnb->frame ? pixelMetric(PM_SpinBoxFrameWidth, option, widget) * 2 : 0;
             newSize = QSize(newSize.width() + fw - 5, newSize.height() + fw - 6);
         }
         break;
 #endif
     case CT_LineEdit:
         newSize += QSize(0,1);
         break;
     case CT_MenuBarItem:
         newSize += QSize(5, 1);
         break;
     case CT_MenuItem:
         newSize += QSize(0, -2);
         break;
     case CT_MenuBar:
         newSize += QSize(0, -1);
         break;
     case CT_ToolButton:
         if (const QStyleOptionToolButton *b = qstyleoption_cast<const QStyleOptionToolButton *>(option)) {
           if (b->toolButtonStyle != Qt::ToolButtonIconOnly)
             newSize = QSize(newSize.width() + 1, newSize.height() - 1);
           else
             newSize = QSize(newSize.width() + 1, newSize.height());
         }
         break;
     default:
         break;
     }
     return newSize;
 }
standardPalette()
QPalette QWindowsCEStyle::standardPalette () const virtual
Returns the style's standard palette.
Note that on systems that support system colors, the style's standard palette is not used. In particular, the Windows XP, Vista, and Mac styles do not use the standard palette, but make use of native theme engines. With these styles, you should not set the palette with QApplication::setStandardPalette().
Reimplemented from QStyle.
Definition at line 2076 of file qwindowscestyle.cpp.
{
     QPalette palette (Qt::black,QColor(198, 195, 198), QColor(222, 223, 222 ),
                       QColor(132, 130, 132), QColor(198, 195, 198) ,  Qt::black,  Qt::white, Qt::white, QColor(198, 195, 198));
     palette.setColor(QPalette::Window, QColor(198, 195, 198));
     palette.setColor(QPalette::Base, Qt::white);
     palette.setColor(QPalette::Button, QColor(198, 195, 198));
     palette.setColor(QPalette::Highlight, QColor(0, 0, 132));
     palette.setColor(QPalette::Light, Qt::white);
     palette.setColor(QPalette::Midlight, QColor(222, 223, 222 ));
     palette.setColor(QPalette::Dark, QColor(132, 130, 132));
     palette.setColor(QPalette::Mid, QColor(132, 130, 132));
     palette.setColor(QPalette::Shadow, QColor(0, 0, 0));
     palette.setColor(QPalette::BrightText, QColor(33, 162, 33)); //color for ItemView checked indicator (arrow)
     palette.setColor(QPalette::Link, QColor(24,81,132)); // color for the box around the ItemView indicator
     return palette;
 }
standardPixmap()
QPixmap QWindowsCEStyle::standardPixmap (StandardPixmap sp, const QStyleOption * opt, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2276 of file qwindowscestyle.cpp.
{
 #ifndef QT_NO_IMAGEFORMAT_XPM
     /*switch (standardPixmap) {
     default:
         break;
     }*/
 #endif //QT_NO_IMAGEFORMAT_XPM
     return QWindowsStyle::standardPixmap(standardPixmap, opt, widget);
 }
styleHint()
int QWindowsCEStyle::styleHint (StyleHint sh, const QStyleOption * opt = 0, const QWidget * w = 0, QStyleHintReturn * shret = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 2288 of file qwindowscestyle.cpp.
Referenced by drawComplexControl(), drawControl(), and subControlRect().
{
     int ret;
     switch (hint) {
     case SH_TabBar_ElideMode:
         ret = Qt::ElideMiddle;
         break;
     case SH_EtchDisabledText:
         ret = false;
         break;
     case SH_RequestSoftwareInputPanel:
         ret = RSIP_OnMouseClick;
         break;
     default:
         ret = QWindowsStyle::styleHint(hint, opt, widget, returnData);
         break;
     }
     return ret;
 }
subControlRect()
QRect QWindowsCEStyle::subControlRect (ComplexControl cc, const QStyleOptionComplex * opt, SubControl sc, const QWidget * w) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 1869 of file qwindowscestyle.cpp.
Referenced by drawComplexControl().
{
     QRect rect = QWindowsStyle::subControlRect(control, option, subControl, widget);
     switch (control) {
 #ifndef QT_NO_SLIDER
         case CC_Slider:
         if (const QStyleOptionSlider *slider = qstyleoption_cast<const QStyleOptionSlider *>(option)) {
             int tickOffset = pixelMetric(PM_SliderTickmarkOffset, slider, widget);
             int thickness = pixelMetric(PM_SliderControlThickness, slider, widget);
             switch (subControl) {
             case SC_SliderHandle: {
                 int sliderPos = 0;
                 int len = pixelMetric(PM_SliderLength, slider, widget);
                 bool horizontal = slider->orientation == Qt::Horizontal;
                 sliderPos = sliderPositionFromValue(slider->minimum, slider->maximum,
                                                     slider->sliderPosition,
                                                     (horizontal ? slider->rect.width()
                                                                 : slider->rect.height()) - len,
                                                     slider->upsideDown);
                 if (horizontal)
                     rect.setRect(slider->rect.x() + sliderPos, slider->rect.y() + tickOffset, len, thickness);
                 else
                     rect.setRect(slider->rect.x() + tickOffset, slider->rect.y() + sliderPos, thickness, len);
                 break; }
             default:
                 break;
             }
             rect = visualRect(slider->direction, slider->rect, rect);
         }
         break;
 #endif //QT_NO_SLIDER
 #ifndef QT_NO_COMBOBOX
     case CC_ComboBox:
         if (const QStyleOptionComboBox *cb = qstyleoption_cast<const QStyleOptionComboBox *>(option)) {
         int x = cb->rect.x(),
             y = cb->rect.y(),
             wi = cb->rect.width(),
             he = cb->rect.height();
         int xpos = x;
         int margin = cb->frame ? 3 : 0;
         int bmarg = cb->frame ? 2 : 0;
         xpos += wi - (he - 2*bmarg) - bmarg;
         switch (subControl) {
           case SC_ComboBoxArrow:
             rect.setRect(xpos, y + bmarg, he - 2*bmarg, he - 2*bmarg);
             break;
            case SC_ComboBoxEditField:
                 rect.setRect(x + margin, y + margin, wi - 2 * margin - (he - 2*bmarg), he - 2 * margin);
                 break;
             case SC_ComboBoxListBoxPopup:
                 rect = cb->rect;
                 break;
             case SC_ComboBoxFrame:
                 rect = cb->rect;
                 break;
         default:
         break;
         }
         rect = visualRect(cb->direction, cb->rect, rect);
     }
 #endif //QT_NO_COMBOBOX
 #ifndef QT_NO_SPINBOX
     case CC_SpinBox:
         if (const QStyleOptionSpinBox *spinbox = qstyleoption_cast<const QStyleOptionSpinBox *>(option)) {
             QSize bs;
             int fw = spinbox->frame ? pixelMetric(PM_SpinBoxFrameWidth, spinbox, widget) : 0;
             bs.setWidth(qMax(18, (spinbox->rect.height() / 2 - fw + 1)));
             // 1.6 -approximate golden mean
             bs.setHeight(qMax(18, qMin((bs.height() * 8 / 5), (spinbox->rect.width() / 4))));
             bs = bs.expandedTo(QApplication::globalStrut());
             int y = fw;
             int x, lx, rx;
             x = spinbox->rect.width() - y - bs.width() * 2;
             lx = fw;
             rx = x - fw;
           switch (subControl) {
           case SC_SpinBoxUp:
                 rect = QRect(x + bs.width(), y, bs.width(), bs.height());
                 break;
           case SC_SpinBoxDown:
                 rect = QRect(x, y , bs.width(), bs.height());
                 break;
           case SC_SpinBoxEditField:
                 if (spinbox->buttonSymbols == QAbstractSpinBox::NoButtons) {
                     rect = QRect(lx, fw, spinbox->rect.width() - 2*fw - 2, spinbox->rect.height() - 2*fw);
                 } else {
                     rect = QRect(lx, fw, rx-2, spinbox->rect.height() - 2*fw);
                 }
                 break;
           case SC_SpinBoxFrame:
                 rect = spinbox->rect;
           default:
                 break;
           }
           rect = visualRect(spinbox->direction, spinbox->rect, rect);
         }
         break;
 #endif // Qt_NO_SPINBOX
 #ifndef QT_NO_GROUPBOX
     case CC_GroupBox: {
         if (const QStyleOptionGroupBox *groupBox = qstyleoption_cast<const QStyleOptionGroupBox *>(option)) {
             switch (subControl) {
             case SC_GroupBoxFrame:
                 // FALL THROUGH
             case SC_GroupBoxContents: {
                 int topMargin = 0;
                 int topHeight = 0;
                 int bottomMargin = 0;
                 int noLabelMargin = 0;
                 QRect frameRect = groupBox->rect;
                 int verticalAlignment = styleHint(SH_GroupBox_TextLabelVerticalAlignment, groupBox, widget);
                 if (groupBox->text.size()) {
                     topHeight = groupBox->fontMetrics.height();
                     if (verticalAlignment & Qt::AlignVCenter)
                         topMargin = topHeight / 2;
                     else if (verticalAlignment & Qt::AlignTop)
                         topMargin = -topHeight/2;
                 }
                 else {
                   topHeight = groupBox->fontMetrics.height();
                   noLabelMargin = topHeight / 2;
                   if (verticalAlignment & Qt::AlignVCenter) {
                         topMargin = topHeight / 4 - 4;
                         bottomMargin = topHeight / 4 - 4;
                   }
                   else if (verticalAlignment & Qt::AlignTop) {
                         topMargin = topHeight/2 - 4;
                         bottomMargin = topHeight/2 - 4;
                   }
                 }
                 if (subControl == SC_GroupBoxFrame) {
                     frameRect.setTop(topMargin);
                     frameRect.setBottom(frameRect.height() + bottomMargin);
                     rect = frameRect;
                     break;
                 }
                 int frameWidth = 0;
                 if ((groupBox->features & QStyleOptionFrameV2::Flat) == 0)
                     frameWidth = pixelMetric(PM_DefaultFrameWidth, groupBox, widget);
                 rect = frameRect.adjusted(frameWidth, frameWidth + topHeight, -frameWidth, -frameWidth - noLabelMargin);
                 break;
             }
             case SC_GroupBoxCheckBox:
                 // FALL THROUGH
             case SC_GroupBoxLabel: {
                 QFontMetrics fontMetrics = groupBox->fontMetrics;
                 int h = fontMetrics.height();
                 int tw = fontMetrics.size(Qt::TextShowMnemonic, groupBox->text + QLatin1Char(' ')).width();
                 int marg = (groupBox->features & QStyleOptionFrameV2::Flat) ? 0 : 8;
                 rect = groupBox->rect.adjusted(marg, 0, -marg, 0);
                 rect.setHeight(h);
                 int indicatorWidth = pixelMetric(PM_IndicatorWidth, option, widget);
                 int indicatorSpace = pixelMetric(PM_CheckBoxLabelSpacing, option, widget) - 1;
                 bool hasCheckBox = groupBox->subControls & QStyle::SC_GroupBoxCheckBox;
                 int checkBoxSize = hasCheckBox ? (indicatorWidth + indicatorSpace) : 0;
                 // Adjusted rect for label + indicatorWidth + indicatorSpace
                 QRect totalRect = alignedRect(groupBox->direction, groupBox->textAlignment,
                                               QSize(tw + checkBoxSize, h), rect);
                 // Adjust totalRect if checkbox is set
                 if (hasCheckBox) {
                     bool ltr = groupBox->direction == Qt::LeftToRight;
                     int left = 0;
                     // Adjust for check box
                     if (subControl == SC_GroupBoxCheckBox) {
                         int indicatorHeight = pixelMetric(PM_IndicatorHeight, option, widget);
                         left = ltr ? totalRect.left() : (totalRect.right() - indicatorWidth);
                         int top = totalRect.top() + (fontMetrics.height() - indicatorHeight) / 2;
                         totalRect.setRect(left, top, indicatorWidth, indicatorHeight);
                     // Adjust for label
                     } else {
                         left = ltr ? (totalRect.left() + checkBoxSize - 2) : totalRect.left();
                         totalRect.setRect(left, totalRect.top(),
                                           totalRect.width() - checkBoxSize, totalRect.height());
                     }
                 }
                 rect = totalRect;
                 break;
             }
             default:
                 break;
             }
         }
         break;
     }
 #endif // QT_NO_GROUPBOX
     default:
         break;
     }
     return rect;
 }
subElementRect()
QRect QWindowsCEStyle::subElementRect (SubElement r, const QStyleOption * opt, const QWidget * widget) const virtual
Reimplemented Function
we need to access the widget here because the style option doesn't
Reimplemented from QCommonStyle.
Definition at line 1851 of file qwindowscestyle.cpp.
Referenced by drawComplexControl(), and sizeFromContents().
{
     QRect rect = QWindowsStyle::subElementRect(element, option, widget);
     switch (element) {
 #ifndef QT_NO_COMBOBOX
     case SE_ComboBoxFocusRect:
         if (const QStyleOptionComboBox *cb = qstyleoption_cast<const QStyleOptionComboBox *>(option)) {
             int margin = cb->frame ? 3 : 0;
             rect.setRect(margin, margin, option->rect.width() - 2*margin - 20, option->rect.height() - 2*margin);
             rect = visualRect(option->direction, option->rect, rect);
         }
         break;
 #endif // QT_NO_COMBOBOX
     default:
         break;
     }
     return rect;
 }
The documentation for this class was generated from the following files:
/src/gui/styles/qwindowscestyle.h
/src/gui/styles/qwindowscestyle.cpp