Qt 4.8: QScriptObjectDelegate Class Reference
QScriptObjectDelegate Class Reference abstract
#include <qscriptobject_p.h>
Public Types
enum Type { QtObject, Variant, ClassObject, DeclarativeClassObject }
Public Functions
virtual bool compareToObject (QScriptObject *, JSC::ExecState *, JSC::JSObject *)
virtual bool deleteProperty (QScriptObject *, JSC::ExecState *, const JSC::Identifier &propertyName)
virtual JSC::CallType getCallData (QScriptObject *, JSC::CallData &)
virtual JSC::ConstructType getConstructData (QScriptObject *, JSC::ConstructData &)
virtual bool getOwnPropertyDescriptor (QScriptObject *, JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertyDescriptor &)
virtual void getOwnPropertyNames (QScriptObject *, JSC::ExecState *, JSC::PropertyNameArray &, JSC::EnumerationMode mode=JSC::ExcludeDontEnumProperties)
virtual bool getOwnPropertySlot (QScriptObject *, JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertySlot &)
virtual bool hasInstance (QScriptObject *, JSC::ExecState *, JSC::JSValue value, JSC::JSValue proto)
virtual void markChildren (QScriptObject *, JSC::MarkStack &markStack)
virtual void put (QScriptObject *, JSC::ExecState *exec, const JSC::Identifier &propertyName, JSC::JSValue, JSC::PutPropertySlot &)
QScriptObjectDelegate ()
virtual Type type () const =0
virtual ~QScriptObjectDelegate ()
Detailed Description
Definition at line 106 of file qscriptobject_p.h.
Enumerations
Type
enum QScriptObjectDelegate::Type
Enumerator
QtObject
Variant
ClassObject
DeclarativeClassObject
Definition at line 109 of file qscriptobject_p.h.
               {
         QtObject,
         Variant,
         ClassObject,
         DeclarativeClassObject
     };
Constructors and Destructors
QScriptObjectDelegate()
QScriptObjectDelegate::QScriptObjectDelegate ()
Definition at line 152 of file qscriptobject.cpp.
 {
 }
~QScriptObjectDelegate()
QScriptObjectDelegate::~QScriptObjectDelegate () virtual
Definition at line 156 of file qscriptobject.cpp.
 {
 }
Functions
compareToObject()
bool QScriptObjectDelegate::compareToObject (QScriptObject * object, JSC::ExecState * exec, JSC::JSObject * o) virtual
Reimplemented in QScript::DeclarativeObjectDelegate, QScript::QObjectDelegate, and QScript::QVariantDelegate.
Definition at line 217 of file qscriptobject.cpp.
Referenced by QScriptObject::compareToObject().
 {
     return object->JSC::JSObject::compareToObject(exec, o);
 }
deleteProperty()
bool QScriptObjectDelegate::deleteProperty (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName) virtual
Reimplemented in QScript::QObjectDelegate, QScript::DeclarativeObjectDelegate, and QScript::ClassObjectDelegate.
Definition at line 182 of file qscriptobject.cpp.
Referenced by QScript::ClassObjectDelegate::deleteProperty(), QScriptObject::deleteProperty(), and QScript::DeclarativeObjectDelegate::deleteProperty().
 {
     return object->JSC::JSObject::deleteProperty(exec, propertyName);
 }
getCallData()
JSC::CallType QScriptObjectDelegate::getCallData (QScriptObject * object, JSC::CallData & data) virtual
Reimplemented in QScript::DeclarativeObjectDelegate, and QScript::ClassObjectDelegate.
Definition at line 201 of file qscriptobject.cpp.
Referenced by QScript::QtFunction::Data::Data(), QScript::QtPropertyFunction::Data::Data(), QScript::QMetaObjectWrapperObject::Data::Data(), and QScriptObject::getCallData().
 {
     return object->JSC::JSObject::getCallData(data);
 }
getConstructData()
JSC::ConstructType QScriptObjectDelegate::getConstructData (QScriptObject * object, JSC::ConstructData & data) virtual
Reimplemented in QScript::DeclarativeObjectDelegate, and QScript::ClassObjectDelegate.
Definition at line 206 of file qscriptobject.cpp.
Referenced by QScript::QMetaObjectWrapperObject::Data::Data(), QScriptObject::getConstructData(), and QScript::DeclarativeObjectDelegate::getConstructData().
 {
     return object->JSC::JSObject::getConstructData(data);
 }
getOwnPropertyDescriptor()
bool QScriptObjectDelegate::getOwnPropertyDescriptor (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertyDescriptor & descriptor) virtual
Reimplemented in QScript::QObjectDelegate, and QScript::ClassObjectDelegate.
Definition at line 167 of file qscriptobject.cpp.
Referenced by QScript::ClassObjectDelegate::getOwnPropertyDescriptor(), QScriptObject::getOwnPropertyDescriptor(), and QScript::QObjectDelegate::getOwnPropertyDescriptor().
 {
     return object->JSC::JSObject::getOwnPropertyDescriptor(exec, propertyName, descriptor);
 }
getOwnPropertyNames()
void QScriptObjectDelegate::getOwnPropertyNames (QScriptObject * object, JSC::ExecState * exec, JSC::PropertyNameArray & propertyNames, JSC::EnumerationMode mode = JSC::ExcludeDontEnumProperties) virtual
Reimplemented in QScript::QObjectDelegate, QScript::DeclarativeObjectDelegate, and QScript::ClassObjectDelegate.
Definition at line 188 of file qscriptobject.cpp.
Referenced by QScript::ClassObjectDelegate::getOwnPropertyNames(), QScriptObject::getOwnPropertyNames(), QScript::DeclarativeObjectDelegate::getOwnPropertyNames(), and QScript::QObjectDelegate::getOwnPropertyNames().
 {
     object->JSC::JSObject::getOwnPropertyNames(exec, propertyNames, mode);
 }
getOwnPropertySlot()
bool QScriptObjectDelegate::getOwnPropertySlot (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertySlot & slot) virtual
Reimplemented in QScript::QObjectDelegate, QScript::DeclarativeObjectDelegate, and QScript::ClassObjectDelegate.
Definition at line 160 of file qscriptobject.cpp.
Referenced by QScript::ClassObjectDelegate::getOwnPropertySlot(), QScriptObject::getOwnPropertySlot(), QScript::DeclarativeObjectDelegate::getOwnPropertySlot(), and QScript::QObjectDelegate::getOwnPropertySlot().
 {
     return object->JSC::JSObject::getOwnPropertySlot(exec, propertyName, slot);
 }
hasInstance()
bool QScriptObjectDelegate::hasInstance (QScriptObject * object, JSC::ExecState * exec, JSC::JSValue value, JSC::JSValue proto) virtual
Reimplemented in QScript::DeclarativeObjectDelegate, and QScript::ClassObjectDelegate.
Definition at line 211 of file qscriptobject.cpp.
Referenced by QScriptObject::hasInstance(), QScript::ClassObjectDelegate::hasInstance(), and QScript::DeclarativeObjectDelegate::hasInstance().
 {
     return object->JSC::JSObject::hasInstance(exec, value, proto);
 }
markChildren()
void QScriptObjectDelegate::markChildren (QScriptObject * object, JSC::MarkStack & markStack) virtual
Reimplemented in QScript::QObjectDelegate.
Definition at line 195 of file qscriptobject.cpp.
Referenced by QScriptObject::markChildren(), and QScript::QObjectDelegate::markChildren().
 {
     // ### should this call the virtual function instead??
     object->JSC::JSObject::markChildren(markStack);
 }
put()
void QScriptObjectDelegate::put (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSValue value, JSC::PutPropertySlot & slot) virtual
Reimplemented in QScript::QObjectDelegate, QScript::DeclarativeObjectDelegate, and QScript::ClassObjectDelegate.
Definition at line 175 of file qscriptobject.cpp.
Referenced by QScript::ClassObjectDelegate::put(), QScriptObject::put(), and QScript::DeclarativeObjectDelegate::put().
 {
     object->JSC::JSObject::put(exec, propertyName, value, slot);
 }
type()
virtual Type QScriptObjectDelegate::type () const pure virtual
Implemented in QScript::QObjectDelegate, QScript::DeclarativeObjectDelegate, QScript::ClassObjectDelegate, and QScript::QVariantDelegate.
Referenced by QScript::ClassObjectDelegate::call(), QScript::DeclarativeObjectDelegate::call(), QScript::QObjectDelegate::compareToObject(), QScript::DeclarativeObjectDelegate::compareToObject(), QScriptEnginePrivate::declarativeClass(), QScriptEnginePrivate::declarativeObject(), QScript::QtFunction::execute(), QScriptEnginePrivate::isQObject(), QScriptEnginePrivate::isVariant(), QScript::QObjectConnection::mark(), QScript::QtFunction::qobject(), QScript::qobjectProtoFuncFindChild(), QScript::qobjectProtoFuncFindChildren(), QScript::qobjectProtoFuncToString(), QScriptValue::scriptClass(), QScriptValue::setScriptClass(), QScriptEnginePrivate::toQObject(), QScript::variantProtoFuncToString(), and QScript::variantProtoFuncValueOf().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptobject_p.h
/src/script/bridge/qscriptobject.cpp