Qt 4.8: QSocks5SocketEngine Class Reference
QSocks5SocketEngine Class Reference
#include <qsocks5socketengine_p.h>
Public Functions
int accept ()
bool bind (const QHostAddress &address, quint16 port)
qint64 bytesAvailable () const
qint64 bytesToWrite () const
void close ()
bool connectInternal ()
bool connectToHost (const QHostAddress &address, quint16 port)
bool connectToHostByName (const QString &name, quint16 port)
bool hasPendingDatagrams () const
bool initialize (QAbstractSocket::SocketType type, QAbstractSocket::NetworkLayerProtocol protocol=QAbstractSocket::IPv4Protocol)
bool initialize (int socketDescriptor, QAbstractSocket::SocketState socketState=QAbstractSocket::ConnectedState)
bool isExceptionNotificationEnabled () const
bool isReadNotificationEnabled () const
bool isValid () const
bool isWriteNotificationEnabled () const
bool joinMulticastGroup (const QHostAddress &groupAddress, const QNetworkInterface &interface)
bool leaveMulticastGroup (const QHostAddress &groupAddress, const QNetworkInterface &interface)
bool listen ()
QNetworkInterface multicastInterface () const
int option (SocketOption option) const
qint64 pendingDatagramSize () const
QSocks5SocketEngine (QObject *parent=0)
qint64 read (char *data, qint64 maxlen)
qint64 readDatagram (char *data, qint64 maxlen, QHostAddress *addr=0, quint16 *port=0)
void setExceptionNotificationEnabled (bool enable)
bool setMulticastInterface (const QNetworkInterface &iface)
bool setOption (SocketOption option, int value)
void setProxy (const QNetworkProxy &networkProxy)
void setReadNotificationEnabled (bool enable)
void setWriteNotificationEnabled (bool enable)
int socketDescriptor () const
bool waitForRead (int msecs=30000, bool *timedOut=0)
bool waitForReadOrWrite (bool *readyToRead, bool *readyToWrite, bool checkRead, bool checkWrite, int msecs=30000, bool *timedOut=0)
bool waitForWrite (int msecs=30000, bool *timedOut=0)
qint64 write (const char *data, qint64 len)
qint64 writeDatagram (const char *data, qint64 len, const QHostAddress &addr, quint16 port)
~QSocks5SocketEngine ()
Public Functions inherited from QAbstractSocketEngine
QAbstractSocket::SocketError error () const
QString errorString () const
QHostAddress localAddress () const
quint16 localPort () const
QHostAddress peerAddress () const
quint16 peerPort () const
QAbstractSocket::NetworkLayerProtocol protocol () const
QAbstractSocketEngine (QObject *parent=0)
void setReceiver (QAbstractSocketEngineReceiver *receiver)
QAbstractSocket::SocketType socketType () const
QAbstractSocket::SocketState state () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Types inherited from QAbstractSocketEngine
enum SocketOption {
NonBlockingSocketOption, BroadcastSocketOption, ReceiveBufferSocketOption, SendBufferSocketOption,
AddressReusable, BindExclusively, ReceiveOutOfBandData, LowDelayOption,
KeepAliveOption, MulticastTtlOption, MulticastLoopbackOption
}
Public Slots inherited from QAbstractSocketEngine
void connectionNotification ()
void exceptionNotification ()
void proxyAuthenticationRequired (const QNetworkProxy &proxy, QAuthenticator *authenticator)
void readNotification ()
void writeNotification ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QAbstractSocketEngine
static QAbstractSocketEngine * createSocketEngine (QAbstractSocket::SocketType socketType, const QNetworkProxy &, QObject *parent)
static QAbstractSocketEngine * createSocketEngine (int socketDescripter, QObject *parent)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QAbstractSocketEngine
QAbstractSocketEngine (QAbstractSocketEnginePrivate &dd, QObject *parent=0)
void setError (QAbstractSocket::SocketError error, const QString &errorString) const
void setLocalAddress (const QHostAddress &address)
void setLocalPort (quint16 port)
void setPeerAddress (const QHostAddress &address)
void setPeerPort (quint16 port)
void setProtocol (QAbstractSocket::NetworkLayerProtocol protocol)
void setSocketType (QAbstractSocket::SocketType socketType)
void setState (QAbstractSocket::SocketState state)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 65 of file qsocks5socketengine_p.h.
Constructors and Destructors
QSocks5SocketEngine()
QSocks5SocketEngine::QSocks5SocketEngine (QObject * parent = 0)
Definition at line 986 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEngineHandler::createSocketEngine().
 :QAbstractSocketEngine(*new QSocks5SocketEnginePrivate(), parent)
 {
 }
~QSocks5SocketEngine()
QSocks5SocketEngine::~QSocks5SocketEngine ()
Definition at line 991 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     if (d->data) {
         delete d->data->authenticator;
         delete d->data->controlSocket;
     }
     if (d->connectData)
         delete d->connectData;
 #ifndef QT_NO_UDPSOCKET
     if (d->udpData) {
         delete d->udpData->udpSocket;
         delete d->udpData;
     }
 #endif
     if (d->bindData)
         delete d->bindData;
 }
Functions
accept()
int QSocks5SocketEngine::accept () virtual
Implements QAbstractSocketEngine.
Definition at line 1436 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     // check we are listing ---
     QSOCKS5_Q_DEBUG << "accept()";
     if (d->socks5State == QSocks5SocketEnginePrivate::BindSuccess) {
         QSOCKS5_Q_DEBUG << "BindSuccess adding" << d->socketDescriptor << "to the bind store";
         d->data->controlSocket->disconnect();
         d->data->controlSocket->setParent(0);
         d->bindData->localAddress = d->localAddress;
         d->bindData->localPort = d->localPort;
         int sd = d->socketDescriptor;
         socks5BindStore()->add(sd, d->bindData);
         d->data = 0;
         d->bindData = 0;
         d->socketDescriptor = 0;
         //### do something about this socket layer ... set it closed and an error about why ...
         // reset state and local port/address
         d->socks5State = QSocks5SocketEnginePrivate::Uninitialized; // ..??
         d->socketState = QAbstractSocket::UnconnectedState;
         return sd;
     }
     return -1;
 }
bind()
bool QSocks5SocketEngine::bind (const QHostAddress & address, quint16 port) virtual
delete d->udpSocket;
d->udpSocket = 0;
Implements QAbstractSocketEngine.
Definition at line 1328 of file qsocks5socketengine.cpp.
Referenced by connectInternal(), and writeDatagram().
 {
     Q_D(QSocks5SocketEngine);
     // when bind wee will block until the bind is finished as the info from the proxy server is needed
     if (!d->data) {
         if (socketType() == QAbstractSocket::TcpSocket) {
             d->initialize(QSocks5SocketEnginePrivate::BindMode);
 #ifndef QT_NO_UDPSOCKET
         } else if (socketType() == QAbstractSocket::UdpSocket) {
             d->initialize(QSocks5SocketEnginePrivate::UdpAssociateMode);
 #endif
         } else {
             //### something invalid
             return false;
         }
     }
 #ifndef QT_NO_UDPSOCKET
     if (d->mode == QSocks5SocketEnginePrivate::UdpAssociateMode) {
         if (!d->udpData->udpSocket->bind(address, port)) {
             QSOCKS5_Q_DEBUG << "local udp bind failed";
             setError(d->udpData->udpSocket->error(), d->udpData->udpSocket->errorString());
             return false;
         }
         d->localAddress = d->udpData->udpSocket->localAddress();
         d->localPort = d->udpData->udpSocket->localPort();
     } else
 #endif
     if (d->mode == QSocks5SocketEnginePrivate::BindMode) {
         d->localAddress = address;
         d->localPort = port;
     } else {
         //### something invalid
         return false;
     }
     int msecs = SOCKS5_BLOCKING_BIND_TIMEOUT;
     QElapsedTimer stopWatch;
     stopWatch.start();
     d->data->controlSocket->connectToHost(d->proxyInfo.hostName(), d->proxyInfo.port());
     if (!d->waitForConnected(msecs, 0) ||
         d->data->controlSocket->state() == QAbstractSocket::UnconnectedState) {
         // waitForConnected sets the error state and closes the socket
         QSOCKS5_Q_DEBUG << "waitForConnected to proxy server" << d->data->controlSocket->errorString();
         return false;
     }
     if (d->socks5State == QSocks5SocketEnginePrivate::BindSuccess) {
         setState(QAbstractSocket::BoundState);
         return true;
 #ifndef QT_NO_UDPSOCKET
     } else if (d->socks5State == QSocks5SocketEnginePrivate::UdpAssociateSuccess) {
         setState(QAbstractSocket::BoundState);
         d->udpData->associateAddress = d->localAddress;
         d->localAddress = QHostAddress();
         d->udpData->associatePort = d->localPort;
         d->localPort = 0;
         QUdpSocket dummy;
 #ifndef QT_NO_BEARERMANAGEMENT
         dummy.setProperty("_q_networksession", property("_q_networksession"));
 #endif
         dummy.setProxy(QNetworkProxy::NoProxy);
         if (!dummy.bind()
             || writeDatagram(0,0, d->data->controlSocket->localAddress(), dummy.localPort()) != 0
             || !dummy.waitForReadyRead(qt_timeout_value(msecs, stopWatch.elapsed()))
             || dummy.readDatagram(0,0, &d->localAddress, &d->localPort) != 0) {
             QSOCKS5_DEBUG << "udp actual address and port lookup failed";
             setState(QAbstractSocket::UnconnectedState);
             setError(dummy.error(), dummy.errorString());
             d->data->controlSocket->close();
             //### reset and error
             return false;
         }
         QSOCKS5_DEBUG << "udp actual address and port" << d->localAddress << ':' << d->localPort;
         return true;
 #endif // QT_NO_UDPSOCKET
     }
     // binding timed out
     setError(QAbstractSocket::SocketTimeoutError,
              QLatin1String(QT_TRANSLATE_NOOP("QSocks5SocketEngine", "Network operation timed out")));
     return false;
 }
bytesAvailable()
qint64 QSocks5SocketEngine::bytesAvailable () const virtual
Implements QAbstractSocketEngine.
Definition at line 1485 of file qsocks5socketengine.cpp.
 {
     Q_D(const QSocks5SocketEngine);
     if (d->mode == QSocks5SocketEnginePrivate::ConnectMode)
         return d->connectData->readBuffer.size();
 #ifndef QT_NO_UDPSOCKET
     else if (d->mode == QSocks5SocketEnginePrivate::UdpAssociateMode
              && !d->udpData->pendingDatagrams.isEmpty())
         return d->udpData->pendingDatagrams.first().data.size();
 #endif
     return 0;
 }
bytesToWrite()
qint64 QSocks5SocketEngine::bytesToWrite () const virtual
Implements QAbstractSocketEngine.
Definition at line 1678 of file qsocks5socketengine.cpp.
 {
     Q_D(const QSocks5SocketEngine);
     if (d->data && d->data->controlSocket) {
         return d->data->controlSocket->bytesToWrite();
     } else {
         return 0;
     }
 }
close()
void QSocks5SocketEngine::close () virtual
Implements QAbstractSocketEngine.
Definition at line 1463 of file qsocks5socketengine.cpp.
Referenced by read().
 {
     QSOCKS5_Q_DEBUG << "close()";
     Q_D(QSocks5SocketEngine);
     if (d->data && d->data->controlSocket) {
         if (d->data->controlSocket->state() == QAbstractSocket::ConnectedState) {
             int msecs = 100;
             QElapsedTimer stopWatch;
             stopWatch.start();
             while (!d->data->controlSocket->bytesToWrite()) {
                if (!d->data->controlSocket->waitForBytesWritten(qt_timeout_value(msecs, stopWatch.elapsed())))
                    break;
             }
         }
         d->data->controlSocket->close();
     }
 #ifndef QT_NO_UDPSOCKET
     if (d->udpData && d->udpData->udpSocket)
         d->udpData->udpSocket->close();
 #endif
 }
connectInternal()
bool QSocks5SocketEngine::connectInternal ()
Definition at line 1103 of file qsocks5socketengine.cpp.
Referenced by connectToHost(), and connectToHostByName().
 {
     Q_D(QSocks5SocketEngine);
     if (!d->data) {
         if (socketType() == QAbstractSocket::TcpSocket) {
             d->initialize(QSocks5SocketEnginePrivate::ConnectMode);
 #ifndef QT_NO_UDPSOCKET
         } else if (socketType() == QAbstractSocket::UdpSocket) {
             d->initialize(QSocks5SocketEnginePrivate::UdpAssociateMode);
             // all udp needs to be bound
             if (!bind(QHostAddress(QLatin1String("0.0.0.0")), 0))
                 return false;
             setState(QAbstractSocket::ConnectedState);
             return true;
 #endif
         } else {
             qFatal("QSocks5SocketEngine::connectToHost: in QTcpServer mode");
             return false;
         }
     }
     if (d->socks5State == QSocks5SocketEnginePrivate::Uninitialized
         && d->socketState != QAbstractSocket::ConnectingState) {
         setState(QAbstractSocket::ConnectingState);
         //limit buffer in internal socket, data is buffered in the external socket under application control
         d->data->controlSocket->setReadBufferSize(65536);
         d->data->controlSocket->connectToHost(d->proxyInfo.hostName(), d->proxyInfo.port());
         return false;
     }
     return false;
 }
connectToHost()
bool QSocks5SocketEngine::connectToHost (const QHostAddress & address, quint16 port) virtual
Implements QAbstractSocketEngine.
Definition at line 1137 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     QSOCKS5_DEBUG << "connectToHost" << address << ':' << port;
     setPeerAddress(address);
     setPeerPort(port);
     d->peerName.clear();
     return connectInternal();
 }
connectToHostByName()
bool QSocks5SocketEngine::connectToHostByName (const QString & name, quint16 port) virtual
Implements QAbstractSocketEngine.
Definition at line 1149 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     setPeerAddress(QHostAddress());
     setPeerPort(port);
     d->peerName = hostname;
     return connectInternal();
 }
hasPendingDatagrams()
bool QSocks5SocketEngine::hasPendingDatagrams () const virtual
Implements QAbstractSocketEngine.
Definition at line 1656 of file qsocks5socketengine.cpp.
 {
     Q_D(const QSocks5SocketEngine);
     Q_INIT_CHECK(false);
     d->checkForDatagrams();
     return !d->udpData->pendingDatagrams.isEmpty();
 }
initialize() [1/2]
bool QSocks5SocketEngine::initialize (QAbstractSocket::SocketType type, QAbstractSocket::NetworkLayerProtocol protocol = QAbstractSocket::IPv4Protocol) virtual
Implements QAbstractSocketEngine.
Definition at line 1013 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     d->socketDescriptor = descriptorCounter.fetchAndAddRelaxed(1);
     d->socketType = type;
     d->socketProtocol = protocol;
     return true;
 }
initialize() [2/2]
bool QSocks5SocketEngine::initialize (int socketDescriptor, QAbstractSocket::SocketState socketState = QAbstractSocket::ConnectedState) virtual
Implements QAbstractSocketEngine.
Definition at line 1025 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     QSOCKS5_Q_DEBUG << "initialize" << socketDescriptor;
     // this is only valid for the other side of a bind, nothing else is supported
     if (socketState != QAbstractSocket::ConnectedState) {
         //### must be connected state ???
         return false;
     }
     QSocks5BindData *bindData = socks5BindStore()->retrieve(socketDescriptor);
     if (bindData) {
         d->socketState = QAbstractSocket::ConnectedState;
         d->socketType = QAbstractSocket::TcpSocket;
         d->connectData = new QSocks5ConnectData;
         d->data = d->connectData;
         d->mode = QSocks5SocketEnginePrivate::ConnectMode;
         d->data->controlSocket = bindData->controlSocket;
         bindData->controlSocket = 0;
         d->data->controlSocket->setParent(this);
         d->socketProtocol = d->data->controlSocket->localAddress().protocol();
         d->data->authenticator = bindData->authenticator;
         bindData->authenticator = 0;
         d->localPort = bindData->localPort;
         d->localAddress = bindData->localAddress;
         d->peerPort = bindData->peerPort;
         d->peerAddress = bindData->peerAddress;
         delete bindData;
         QObject::connect(d->data->controlSocket, SIGNAL(connected()), this, SLOT(_q_controlSocketConnected()),
                          Qt::DirectConnection);
         QObject::connect(d->data->controlSocket, SIGNAL(readyRead()), this, SLOT(_q_controlSocketReadNotification()),
                          Qt::DirectConnection);
         QObject::connect(d->data->controlSocket, SIGNAL(bytesWritten(qint64)), this, SLOT(_q_controlSocketBytesWritten()),
                          Qt::DirectConnection);
         QObject::connect(d->data->controlSocket, SIGNAL(error(QAbstractSocket::SocketError)), this, SLOT(_q_controlSocketError(QAbstractSocket::SocketError)),
                          Qt::DirectConnection);
         QObject::connect(d->data->controlSocket, SIGNAL(disconnected()), this, SLOT(_q_controlSocketDisconnected()),
                          Qt::DirectConnection);
         QObject::connect(d->data->controlSocket, SIGNAL(stateChanged(QAbstractSocket::SocketState)),
                          this, SLOT(_q_controlSocketStateChanged(QAbstractSocket::SocketState)),
                          Qt::DirectConnection);
         d->socks5State = QSocks5SocketEnginePrivate::Connected;
         if (d->data->controlSocket->bytesAvailable() != 0)
             d->_q_controlSocketReadNotification();
         return true;
     }
     return false;
 }
isExceptionNotificationEnabled()
bool QSocks5SocketEngine::isExceptionNotificationEnabled () const virtual
Implements QAbstractSocketEngine.
Definition at line 1890 of file qsocks5socketengine.cpp.
 {
     Q_D(const QSocks5SocketEngine);
     return d->exceptNotificationEnabled;
 }
isReadNotificationEnabled()
bool QSocks5SocketEngine::isReadNotificationEnabled () const virtual
Implements QAbstractSocketEngine.
Definition at line 1839 of file qsocks5socketengine.cpp.
 {
     Q_D(const QSocks5SocketEngine);
     return d->readNotificationEnabled;
 }
isValid()
bool QSocks5SocketEngine::isValid () const virtual
Implements QAbstractSocketEngine.
Definition at line 1093 of file qsocks5socketengine.cpp.
 {
     Q_D(const QSocks5SocketEngine);
     return d->socketType != QAbstractSocket::UnknownSocketType
            && d->socks5State != QSocks5SocketEnginePrivate::SocksError
            && (d->socketError == QAbstractSocket::UnknownSocketError
                || d->socketError == QAbstractSocket::SocketTimeoutError
                || d->socketError == QAbstractSocket::UnfinishedSocketOperationError);
 }
isWriteNotificationEnabled()
bool QSocks5SocketEngine::isWriteNotificationEnabled () const virtual
Implements QAbstractSocketEngine.
Definition at line 1872 of file qsocks5socketengine.cpp.
 {
     Q_D(const QSocks5SocketEngine);
     return d->writeNotificationEnabled;
 }
joinMulticastGroup()
bool QSocks5SocketEngine::joinMulticastGroup (const QHostAddress & groupAddress, const QNetworkInterface & interface) virtual
Implements QAbstractSocketEngine.
Definition at line 1565 of file qsocks5socketengine.cpp.
 {
     setError(QAbstractSocket::UnsupportedSocketOperationError,
              QLatin1String("Operation on socket is not supported"));
     return false;
 }
leaveMulticastGroup()
bool QSocks5SocketEngine::leaveMulticastGroup (const QHostAddress & groupAddress, const QNetworkInterface & interface) virtual
Implements QAbstractSocketEngine.
Definition at line 1573 of file qsocks5socketengine.cpp.
 {
     setError(QAbstractSocket::UnsupportedSocketOperationError,
              QLatin1String("Operation on socket is not supported"));
     return false;
 }
listen()
bool QSocks5SocketEngine::listen () virtual
Implements QAbstractSocketEngine.
Definition at line 1417 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     QSOCKS5_Q_DEBUG << "listen()";
     // check that we are in bound and then go to listening.
     if (d->socketState == QAbstractSocket::BoundState) {
         d->socketState = QAbstractSocket::ListeningState;
         // check if we already have a connection
         if (d->socks5State == QSocks5SocketEnginePrivate::BindSuccess)
             d->emitReadNotification();
         return true;
     }
     return false;
 }
multicastInterface()
QNetworkInterface QSocks5SocketEngine::multicastInterface () const virtual
Implements QAbstractSocketEngine.
Definition at line 1582 of file qsocks5socketengine.cpp.
 {
     return QNetworkInterface();
 }
option()
int QSocks5SocketEngine::option (SocketOption option) const virtual
Implements QAbstractSocketEngine.
Definition at line 1688 of file qsocks5socketengine.cpp.
 {
     Q_D(const QSocks5SocketEngine);
     if (d->data && d->data->controlSocket) {
         // convert the enum and call the real socket
         if (option == QAbstractSocketEngine::LowDelayOption)
             return d->data->controlSocket->socketOption(QAbstractSocket::LowDelayOption).toInt();
         if (option == QAbstractSocketEngine::KeepAliveOption)
             return d->data->controlSocket->socketOption(QAbstractSocket::KeepAliveOption).toInt();
     }
     return -1;
 }
pendingDatagramSize()
qint64 QSocks5SocketEngine::pendingDatagramSize () const virtual
Implements QAbstractSocketEngine.
Definition at line 1666 of file qsocks5socketengine.cpp.
 {
     Q_D(const QSocks5SocketEngine);
     d->checkForDatagrams();
     if (!d->udpData->pendingDatagrams.isEmpty())
         return d->udpData->pendingDatagrams.head().data.size();
     return 0;
 }
read()
qint64 QSocks5SocketEngine::read (char * data, qint64 maxlen) virtual
Implements QAbstractSocketEngine.
Definition at line 1498 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     QSOCKS5_Q_DEBUG << "read( , maxlen = " << maxlen << ')';
     if (d->mode == QSocks5SocketEnginePrivate::ConnectMode) {
         if (d->connectData->readBuffer.size() == 0) {
             if (d->data->controlSocket->state() == QAbstractSocket::UnconnectedState) {
                 //imitate remote closed
                 close();
                 setError(QAbstractSocket::RemoteHostClosedError,
                          QLatin1String("Remote host closed connection###"));
                 setState(QAbstractSocket::UnconnectedState);
                 return -1;
             } else {
                 return 0;       // nothing to be read
             }
         }
         qint64 copy = qMin<qint64>(d->connectData->readBuffer.size(), maxlen);
         memcpy(data, d->connectData->readBuffer.constData(), copy);
         d->connectData->readBuffer.remove(0, copy);
         QSOCKS5_DEBUG << "read" << dump(QByteArray(data, copy));
         return copy;
 #ifndef QT_NO_UDPSOCKET
     } else if (d->mode == QSocks5SocketEnginePrivate::UdpAssociateMode) {
         return readDatagram(data, maxlen);
 #endif
     }
     return 0;
 }
readDatagram()
qint64 QSocks5SocketEngine::readDatagram (char * data, qint64 maxlen, QHostAddress * addr = 0, quint16 * port = 0) virtual
Implements QAbstractSocketEngine.
Definition at line 1595 of file qsocks5socketengine.cpp.
Referenced by read().
 {
     Q_D(QSocks5SocketEngine);
     d->checkForDatagrams();
     if (d->udpData->pendingDatagrams.isEmpty())
         return 0;
     QSocks5RevivedDatagram datagram = d->udpData->pendingDatagrams.dequeue();
     int copyLen = qMin<int>(maxlen, datagram.data.size());
     memcpy(data, datagram.data.constData(), copyLen);
     if (addr)
         *addr = datagram.address;
     if (port)
         *port = datagram.port;
     return copyLen;
 }
setExceptionNotificationEnabled()
void QSocks5SocketEngine::setExceptionNotificationEnabled (bool enable) virtual
Implements QAbstractSocketEngine.
Definition at line 1896 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     d->exceptNotificationEnabled = enable;
 }
setMulticastInterface()
bool QSocks5SocketEngine::setMulticastInterface (const QNetworkInterface & iface) virtual
Implements QAbstractSocketEngine.
Definition at line 1587 of file qsocks5socketengine.cpp.
 {
     setError(QAbstractSocket::UnsupportedSocketOperationError,
              QLatin1String("Operation on socket is not supported"));
     return false;
 }
setOption()
bool QSocks5SocketEngine::setOption (SocketOption option, int value) virtual
Implements QAbstractSocketEngine.
Definition at line 1701 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     if (d->data && d->data->controlSocket) {
         // convert the enum and call the real socket
         if (option == QAbstractSocketEngine::LowDelayOption)
             d->data->controlSocket->setSocketOption(QAbstractSocket::LowDelayOption, value);
         if (option == QAbstractSocketEngine::KeepAliveOption)
             d->data->controlSocket->setSocketOption(QAbstractSocket::KeepAliveOption, value);
         return true;
     }
     return false;
 }
setProxy()
void QSocks5SocketEngine::setProxy (const QNetworkProxy & networkProxy)
Definition at line 1081 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEngineHandler::createSocketEngine().
 {
     Q_D(QSocks5SocketEngine);
     d->proxyInfo = networkProxy;
 }
setReadNotificationEnabled()
void QSocks5SocketEngine::setReadNotificationEnabled (bool enable) virtual
Implements QAbstractSocketEngine.
Definition at line 1845 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     QSOCKS5_Q_DEBUG << "setReadNotificationEnabled(" << enable << ')';
     bool emitSignal = false;
     if (!d->readNotificationEnabled
         && enable) {
         if (d->mode == QSocks5SocketEnginePrivate::ConnectMode)
             emitSignal = !d->connectData->readBuffer.isEmpty();
 #ifndef QT_NO_UDPSOCKET
         else if (d->mode == QSocks5SocketEnginePrivate::UdpAssociateMode)
             emitSignal = !d->udpData->pendingDatagrams.isEmpty();
 #endif
         else if (d->mode == QSocks5SocketEnginePrivate::BindMode
             && d->socketState == QAbstractSocket::ListeningState
             && d->socks5State == QSocks5SocketEnginePrivate::BindSuccess)
             emitSignal = true;
     }
     d->readNotificationEnabled = enable;
     if (emitSignal)
         d->emitReadNotification();
 }
setWriteNotificationEnabled()
void QSocks5SocketEngine::setWriteNotificationEnabled (bool enable) virtual
Implements QAbstractSocketEngine.
Definition at line 1878 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     d->writeNotificationEnabled = enable;
     if (enable && d->socketState == QAbstractSocket::ConnectedState) {
         if (d->mode == QSocks5SocketEnginePrivate::ConnectMode && d->data->controlSocket->bytesToWrite())
             return; // will be emitted as a result of bytes written
        d->emitWriteNotification();
        d->writeNotificationActivated = false;
     }
 }
socketDescriptor()
int QSocks5SocketEngine::socketDescriptor () const virtual
Implements QAbstractSocketEngine.
Definition at line 1087 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEngineHandler::createSocketEngine(), and initialize().
 {
     Q_D(const QSocks5SocketEngine);
     return d->socketDescriptor;
 }
waitForRead()
bool QSocks5SocketEngine::waitForRead (int msecs = 30000, bool * timedOut = 0) virtual
Implements QAbstractSocketEngine.
Definition at line 1743 of file qsocks5socketengine.cpp.
Referenced by waitForReadOrWrite().
 {
     Q_D(QSocks5SocketEngine);
     QSOCKS5_DEBUG << "waitForRead" << msecs;
     d->readNotificationActivated = false;
     QElapsedTimer stopWatch;
     stopWatch.start();
     // are we connected yet?
     if (!d->waitForConnected(msecs, timedOut))
         return false;
     if (d->data->controlSocket->state() == QAbstractSocket::UnconnectedState)
         return true;
     // we're connected
     if (d->mode == QSocks5SocketEnginePrivate::ConnectMode ||
         d->mode == QSocks5SocketEnginePrivate::BindMode) {
         while (!d->readNotificationActivated) {
             if (!d->data->controlSocket->waitForReadyRead(qt_timeout_value(msecs, stopWatch.elapsed()))) {
                 if (d->data->controlSocket->state() == QAbstractSocket::UnconnectedState)
                     return true;
                 setError(d->data->controlSocket->error(), d->data->controlSocket->errorString());
                 if (timedOut && d->data->controlSocket->error() == QAbstractSocket::SocketTimeoutError)
                     *timedOut = true;
                 return false;
             }
         }
 #ifndef QT_NO_UDPSOCKET
     } else {
         while (!d->readNotificationActivated) {
             if (!d->udpData->udpSocket->waitForReadyRead(qt_timeout_value(msecs, stopWatch.elapsed()))) {
                 setError(d->udpData->udpSocket->error(), d->udpData->udpSocket->errorString());
                 if (timedOut && d->udpData->udpSocket->error() == QAbstractSocket::SocketTimeoutError)
                     *timedOut = true;
                 return false;
             }
         }
 #endif // QT_NO_UDPSOCKET
     }
     bool ret = d->readNotificationActivated;
     d->readNotificationActivated = false;
     QSOCKS5_DEBUG << "waitForRead returned" << ret;
     return ret;
 }
waitForReadOrWrite()
bool QSocks5SocketEngine::waitForReadOrWrite (bool * readyToRead, bool * readyToWrite, bool checkRead, bool checkWrite, int msecs = 30000, bool * timedOut = 0) virtual
Implements QAbstractSocketEngine.
Definition at line 1821 of file qsocks5socketengine.cpp.
 {
     Q_UNUSED(checkRead);
     if (!checkWrite) {
         bool canRead = waitForRead(msecs, timedOut);
         if (readyToRead)
             *readyToRead = canRead;
         return canRead;
     }
     bool canWrite = waitForWrite(msecs, timedOut);
     if (readyToWrite)
         *readyToWrite = canWrite;
     return canWrite;
 }
waitForWrite()
bool QSocks5SocketEngine::waitForWrite (int msecs = 30000, bool * timedOut = 0) virtual
Implements QAbstractSocketEngine.
Definition at line 1795 of file qsocks5socketengine.cpp.
Referenced by waitForReadOrWrite().
 {
     Q_D(QSocks5SocketEngine);
     QSOCKS5_DEBUG << "waitForWrite" << msecs;
     QElapsedTimer stopWatch;
     stopWatch.start();
     // are we connected yet?
     if (!d->waitForConnected(msecs, timedOut))
         return false;
     if (d->data->controlSocket->state() == QAbstractSocket::UnconnectedState)
         return true;
     // we're connected
     // flush any bytes we may still have buffered in the time that we have left
     if (d->data->controlSocket->bytesToWrite())
         d->data->controlSocket->waitForBytesWritten(qt_timeout_value(msecs, stopWatch.elapsed()));
     while ((msecs == -1 || stopWatch.elapsed() < msecs)
            && d->data->controlSocket->state() == QAbstractSocket::ConnectedState
            && d->data->controlSocket->bytesToWrite() >= MaxWriteBufferSize)
         d->data->controlSocket->waitForBytesWritten(qt_timeout_value(msecs, stopWatch.elapsed()));
     return d->data->controlSocket->bytesToWrite() < MaxWriteBufferSize;
 }
write()
qint64 QSocks5SocketEngine::write (const char * data, qint64 len) virtual
Implements QAbstractSocketEngine.
Definition at line 1528 of file qsocks5socketengine.cpp.
 {
     Q_D(QSocks5SocketEngine);
     QSOCKS5_Q_DEBUG << "write" << dump(QByteArray(data, len));
     if (d->mode == QSocks5SocketEnginePrivate::ConnectMode) {
         // clamp down the amount of bytes to transfer at once
         len = qMin<qint64>(len, MaxWriteBufferSize) - d->data->controlSocket->bytesToWrite();
         if (len <= 0)
             return 0;
         QByteArray buf = QByteArray::fromRawData(data, len);
         QByteArray sealedBuf;
         if (!d->data->authenticator->seal(buf, &sealedBuf)) {
             // ### Handle this error.
         }
         qint64 written = d->data->controlSocket->write(sealedBuf);
         if (written <= 0) {
             QSOCKS5_Q_DEBUG << "native write returned" << written;
             return written;
         }
         d->data->controlSocket->waitForBytesWritten(0);
         //NB: returning len rather than written for the OK case, because the "sealing" may increase the length
         return len;
 #ifndef QT_NO_UDPSOCKET
     } else if (d->mode == QSocks5SocketEnginePrivate::UdpAssociateMode) {
         // send to connected address
         return writeDatagram(data, len, d->peerAddress, d->peerPort);
 #endif
     }
     //### set an error ???
     return -1;
 }
writeDatagram()
qint64 QSocks5SocketEngine::writeDatagram (const char * data, qint64 len, const QHostAddress & addr, quint16 port) virtual
Implements QAbstractSocketEngine.
Definition at line 1615 of file qsocks5socketengine.cpp.
Referenced by bind(), and write().
 {
     Q_D(QSocks5SocketEngine);
     // it is possible to send with out first binding with udp, but socks5 requires a bind.
     if (!d->data) {
         d->initialize(QSocks5SocketEnginePrivate::UdpAssociateMode);
         // all udp needs to be bound
         if (!bind(QHostAddress(QLatin1String("0.0.0.0")), 0)) {
             //### set error
             return -1;
         }
     }
     QByteArray outBuf;
     outBuf.reserve(270 + len);
     outBuf[0] = 0x00;
     outBuf[1] = 0x00;
     outBuf[2] = 0x00;
     if (!qt_socks5_set_host_address_and_port(address, port, &outBuf)) {
     }
     outBuf += QByteArray(data, len);
     QSOCKS5_DEBUG << "sending" << dump(outBuf);
     QByteArray sealedBuf;
     if (!d->data->authenticator->seal(outBuf, &sealedBuf)) {
         QSOCKS5_DEBUG << "sealing data failed";
         setError(QAbstractSocket::SocketAccessError, d->data->authenticator->errorString());
         return -1;
     }
     if (d->udpData->udpSocket->writeDatagram(sealedBuf, d->udpData->associateAddress, d->udpData->associatePort) != sealedBuf.size()) {
         //### try frgamenting
         if (d->udpData->udpSocket->error() == QAbstractSocket::DatagramTooLargeError)
             setError(d->udpData->udpSocket->error(), d->udpData->udpSocket->errorString());
         //### else maybe more serious error
         return -1;
     }
     return len;
 }
The documentation for this class was generated from the following files:
/src/network/socket/qsocks5socketengine_p.h
/src/network/socket/qsocks5socketengine.cpp