Qt 4.8: QPatternist::BasicTypesFactory Class Reference
QPatternist::BasicTypesFactory Class Reference
Factory for creating schema types for the types defined in XSL-T 2.0.
#include <qbasictypesfactory_p.h>
Public Functions
virtual SchemaType::Ptr createSchemaType (const QXmlName) const
virtual SchemaType::Hash types () const
Public Functions inherited from QPatternist::SchemaTypeFactory
SchemaTypeFactory ()
virtual ~SchemaTypeFactory ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Static Public Functions
static SchemaTypeFactory::Ptr self (const NamePool::Ptr &np)
Protected Functions
BasicTypesFactory (const NamePool::Ptr &np)
Properties
SchemaType::Hash m_types
Additional Inherited Members
Public Types inherited from QPatternist::SchemaTypeFactory
typedef QExplicitlySharedDataPointer< SchemaTypeFactory > Ptr
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Factory for creating schema types for the types defined in XSL-T 2.0.
Theses types are essentially the builtin primitive types, plus xs:integer, and the types defined in the XPath Data Model.
See also
XQuery 1.0 and XPath 2.0 Data Model, 2.6.2 Predefined Types
XSL Transformations (XSLT) Version 2.0, 3.13 Built-in Types
XML Schema Part 2: Datatypes Second Edition, 3.2 Primitive datatypes
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 80 of file qbasictypesfactory_p.h.
Constructors and Destructors
BasicTypesFactory()
BasicTypesFactory::BasicTypesFactory (const NamePool::Ptr & np) protected
This constructor is protected. Use the static self() function to retrieve a singleton instance.
Definition at line 58 of file qbasictypesfactory.cpp.
Referenced by self().
 {
     m_types.reserve(48);
 #define add(aName)   m_types.insert(BuiltinTypes::aName->name(np), AtomicType::Ptr(BuiltinTypes::aName))
 #define addNA(aName) m_types.insert(BuiltinTypes::aName->name(np), BuiltinTypes::aName)
     add(xsString);
     add(xsBoolean);
     add(xsDecimal);
     add(xsDouble);
     add(xsFloat);
     add(xsDate);
     add(xsTime);
     add(xsDateTime);
     add(xsDuration);
     add(xsAnyURI);
     add(xsGDay);
     add(xsGMonthDay);
     add(xsGMonth);
     add(xsGYearMonth);
     add(xsGYear);
     add(xsBase64Binary);
     add(xsHexBinary);
     add(xsQName);
     add(xsInteger);
     addNA(xsAnyType);
     addNA(xsAnySimpleType);
     add(xsYearMonthDuration);
     add(xsDayTimeDuration);
     add(xsAnyAtomicType);
     addNA(xsUntyped);
     add(xsUntypedAtomic);
     add(xsNOTATION);
     /* Add derived primitives. */
     add(xsNonPositiveInteger);
     add(xsNegativeInteger);
     add(xsLong);
     add(xsInt);
     add(xsShort);
     add(xsByte);
     add(xsNonNegativeInteger);
     add(xsUnsignedLong);
     add(xsUnsignedInt);
     add(xsUnsignedShort);
     add(xsUnsignedByte);
     add(xsPositiveInteger);
     add(xsNormalizedString);
     add(xsToken);
     add(xsLanguage);
     add(xsNMTOKEN);
     add(xsName);
     add(xsNCName);
     add(xsID);
     add(xsIDREF);
     add(xsENTITY);
 #undef add
 #undef addNA
 }
Functions
createSchemaType()
SchemaType::Ptr BasicTypesFactory::createSchemaType (const QXmlName name) const virtual
Creates a primitive type for name. If name is not supported, null is returned. The intened supported types are the builtin primitive and derived types. That is, the 19 W3C XML Schema types, and the additional 5 in the XPath Data MOdel.
Note
This does not handle user defined types, only builtin types.
Implements QPatternist::SchemaTypeFactory.
Definition at line 118 of file qbasictypesfactory.cpp.
 {
     return m_types.value(name);
 }
self()
SchemaTypeFactory::Ptr BasicTypesFactory::self (const NamePool::Ptr & np) static
Returns
the singleton instance of BasicTypesFactory.
Definition at line 52 of file qbasictypesfactory.cpp.
Referenced by QPatternist::XsdSchemaTypesFactory::createSchemaType(), QPatternist::GenericStaticContext::schemaDefinitions(), and QPatternist::FunctionFactoryCollection::xpath20Factory().
 {
     /* We don't store a global static here, because it's dependent on the NamePool. */
     return SchemaTypeFactory::Ptr(new BasicTypesFactory(np));
 }
types()
SchemaType::Hash BasicTypesFactory::types () const virtual
Returns
a dictionary containing the types this factory serves. The key is the type's QName in Clark name syntax.
Implements QPatternist::SchemaTypeFactory.
Definition at line 123 of file qbasictypesfactory.cpp.
 {
     return m_types;
 }
Properties
m_types
SchemaType::Hash QPatternist::BasicTypesFactory::m_types private
A dictonary of builtin primitive and derived primitives.
Definition at line 113 of file qbasictypesfactory_p.h.
Referenced by BasicTypesFactory(), createSchemaType(), and types().
The documentation for this class was generated from the following files:
/src/xmlpatterns/type/qbasictypesfactory_p.h
/src/xmlpatterns/type/qbasictypesfactory.cpp