Qt 4.8: QPatternist::XsdModelGroup Class Reference
QPatternist::XsdModelGroup Class Reference
XML Schema Processing
Represents a XSD model group object.
#include <qxsdmodelgroup_p.h>
Public Types
typedef QList< XsdModelGroup::Ptr > List
enum ModelCompositor { SequenceCompositor, ChoiceCompositor, AllCompositor }
typedef QExplicitlySharedDataPointer< XsdModelGroup > Ptr
Public Types inherited from QPatternist::XsdTerm
typedef QExplicitlySharedDataPointer< XsdTerm > Ptr
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
ModelCompositor compositor () const
virtual bool isModelGroup () const
XsdParticle::List particles () const
void setCompositor (ModelCompositor compositor)
void setParticles (const XsdParticle::List &particles)
XsdModelGroup ()
Public Functions inherited from QPatternist::XsdTerm
virtual bool isElement () const
virtual bool isReference () const
virtual bool isWildcard () const
Public Functions inherited from QPatternist::NamedSchemaComponent
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Properties
ModelCompositor m_compositor
XsdParticle::List m_particles
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::XsdTerm
XsdTerm ()
Detailed Description
Represents a XSD model group object.
This class represents the model group object of a XML schema as described here.
It contains information from either a sequence object, a choice object or an all object.
See also
XML Schema API reference
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 79 of file qxsdmodelgroup_p.h.
Typedefs
List
typedef QList<XsdModelGroup::Ptr> QPatternist::XsdModelGroup::List
Definition at line 83 of file qxsdmodelgroup_p.h.
Ptr
typedef QExplicitlySharedDataPointer<XsdModelGroup> QPatternist::XsdModelGroup::Ptr
Definition at line 82 of file qxsdmodelgroup_p.h.
Enumerations
ModelCompositor
enum QPatternist::XsdModelGroup::ModelCompositor
Describes the compositor of the model group.
Enumerator
SequenceCompositor
The model group is a sequence.
ChoiceCompositor
The model group is a choice.
AllCompositor
The model group contains elements only.
Definition at line 88 of file qxsdmodelgroup_p.h.
             {
                 SequenceCompositor,
                 ChoiceCompositor,
                 AllCompositor
             };
Constructors and Destructors
XsdModelGroup()
XsdModelGroup::XsdModelGroup ()
Creates a new model group object.
Definition at line 48 of file qxsdmodelgroup.cpp.
     : m_compositor(SequenceCompositor)
 {
 }
Functions
compositor()
XsdModelGroup::ModelCompositor XsdModelGroup::compositor () const
Returns the compositor of the model group.
Definition at line 63 of file qxsdmodelgroup.cpp.
Referenced by QPatternist::XsdStateMachineBuilder::buildTerm(), effectiveTotalRangeMinimum(), QPatternist::XsdSchemaChecker::isValidParticleExtension(), QPatternist::XsdSchemaParser::resolveComplexContentType(), QPatternist::XsdSchemaResolver::resolveTermReference(), and setCompositor().
 {
     return m_compositor;
 }
isModelGroup()
bool XsdModelGroup::isModelGroup () const virtual
Returns always true, used to avoid dynamic casts.
Reimplemented from QPatternist::XsdTerm.
Definition at line 53 of file qxsdmodelgroup.cpp.
 {
     return true;
 }
particles()
XsdParticle::List XsdModelGroup::particles () const
Returns the list of particles of the model group.
Definition at line 73 of file qxsdmodelgroup.cpp.
Referenced by QPatternist::XsdStateMachineBuilder::buildTerm(), collectAllElements(), collectGroupRef(), effectiveTotalRangeMinimum(), QPatternist::XsdSchemaChecker::elementSequenceAccepted(), hasDuplicatedElementsInternal(), QPatternist::XsdSchemaChecker::isValidParticleExtension(), QPatternist::XsdSchemaChecker::particleEqualsRecursively(), QPatternist::XsdSchemaParser::resolveComplexContentType(), QPatternist::XsdSchemaResolver::resolveTermReference(), and setParticles().
 {
     return m_particles;
 }
setCompositor()
void XsdModelGroup::setCompositor (ModelCompositor compositor)
Sets the compositor of the model group.
See also
ModelCompositor
Definition at line 58 of file qxsdmodelgroup.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::anyType(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseChoice(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalSequence(), QPatternist::XsdSchemaParser::parseSequence(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), and QPatternist::XsdValidatingInstanceReader::validate().
 {
     m_compositor = compositor;
 }
setParticles()
void XsdModelGroup::setParticles (const XsdParticle::List & particles)
Sets the list of particles of the model group.
See also
Particles Definition
Definition at line 68 of file qxsdmodelgroup.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::anyType(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseChoice(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalSequence(), QPatternist::XsdSchemaParser::parseSequence(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), and QPatternist::XsdValidatingInstanceReader::validate().
 {
     m_particles = particles;
 }
Properties
m_compositor
ModelCompositor QPatternist::XsdModelGroup::m_compositor private
Definition at line 130 of file qxsdmodelgroup_p.h.
Referenced by compositor(), and setCompositor().
m_particles
XsdParticle::List QPatternist::XsdModelGroup::m_particles private
Definition at line 131 of file qxsdmodelgroup_p.h.
Referenced by particles(), and setParticles().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdmodelgroup_p.h
/src/xmlpatterns/schema/qxsdmodelgroup.cpp