Qt 4.8: QScript::QObjectData Class Reference
QScript::QObjectData Class Reference
#include <qscriptqobject_p.h>
Public Functions
bool addSignalHandler (QObject *sender, int signalIndex, JSC::JSValue receiver, JSC::JSValue slot, JSC::JSValue senderWrapper, Qt::ConnectionType type)
QScriptObject * findWrapper (QScriptEngine::ValueOwnership ownership, const QScriptEngine::QObjectWrapOptions &options) const
void mark (JSC::MarkStack &)
QObjectData (QScriptEnginePrivate *engine)
void registerWrapper (QScriptObject *wrapper, QScriptEngine::ValueOwnership ownership, const QScriptEngine::QObjectWrapOptions &options)
bool removeSignalHandler (QObject *sender, int signalIndex, JSC::JSValue receiver, JSC::JSValue slot)
~QObjectData ()
Properties
QScript::QObjectConnectionManager * connectionManager
QScriptEnginePrivate * engine
QList< QScript::QObjectWrapperInfo > wrappers
Detailed Description
Definition at line 143 of file qscriptqobject_p.h.
Constructors and Destructors
QObjectData()
QObjectData::QObjectData (QScriptEnginePrivate * engine)
Definition at line 2251 of file qscriptqobject.cpp.
     : engine(eng), connectionManager(0)
 {
 }
~QObjectData()
QObjectData::~QObjectData ()
Definition at line 2256 of file qscriptqobject.cpp.
 {
     if (connectionManager) {
         delete connectionManager;
         connectionManager = 0;
     }
 }
Functions
addSignalHandler()
bool QObjectData::addSignalHandler (QObject * sender, int signalIndex, JSC::JSValue receiver, JSC::JSValue slot, JSC::JSValue senderWrapper, Qt::ConnectionType type)
Definition at line 2280 of file qscriptqobject.cpp.
Referenced by QScriptEnginePrivate::scriptConnect().
 {
     if (!connectionManager)
         connectionManager = new QObjectConnectionManager(engine);
     return connectionManager->addSignalHandler(
         sender, signalIndex, receiver, slot, senderWrapper, type);
 }
findWrapper()
QScriptObject * QObjectData::findWrapper (QScriptEngine::ValueOwnership ownership, const QScriptEngine::QObjectWrapOptions & options) const
Definition at line 2304 of file qscriptqobject.cpp.
Referenced by QScriptEnginePrivate::newQObject().
 {
     for (int i = 0; i < wrappers.size(); ++i) {
         const QObjectWrapperInfo &info = wrappers.at(i);
         if ((info.ownership == ownership) && (info.options == options))
             return info.object;
     }
     return 0;
 }
mark()
void QObjectData::mark (JSC::MarkStack & markStack)
Definition at line 2264 of file qscriptqobject.cpp.
Referenced by QScriptEnginePrivate::mark().
 {
     if (connectionManager)
         connectionManager->mark(markStack);
     {
         QList<QScript::QObjectWrapperInfo>::iterator it;
         for (it = wrappers.begin(); it != wrappers.end(); ) {
             const QScript::QObjectWrapperInfo &info = *it;
             // ### don't mark if there are no other references.
             // we need something like isMarked()
             markStack.append(info.object);
             ++it;
         }
     }
 }
registerWrapper()
void QObjectData::registerWrapper (QScriptObject * wrapper, QScriptEngine::ValueOwnership ownership, const QScriptEngine::QObjectWrapOptions & options)
Definition at line 2315 of file qscriptqobject.cpp.
Referenced by QScriptEnginePrivate::newQObject().
 {
     wrappers.append(QObjectWrapperInfo(wrapper, ownership, options));
 }
removeSignalHandler()
bool QObjectData::removeSignalHandler (QObject * sender, int signalIndex, JSC::JSValue receiver, JSC::JSValue slot)
Definition at line 2293 of file qscriptqobject.cpp.
Referenced by QScriptEnginePrivate::scriptDisconnect().
 {
     if (!connectionManager)
         return false;
     return connectionManager->removeSignalHandler(
         sender, signalIndex, receiver, slot);
 }
Properties
connectionManager
QScript::QObjectConnectionManager* QScript::QObjectData::connectionManager private
Definition at line 170 of file qscriptqobject_p.h.
Referenced by addSignalHandler(), mark(), removeSignalHandler(), and ~QObjectData().
engine
QScriptEnginePrivate* QScript::QObjectData::engine private
Definition at line 169 of file qscriptqobject_p.h.
Referenced by addSignalHandler().
wrappers
QList<QScript::QObjectWrapperInfo> QScript::QObjectData::wrappers private
Definition at line 171 of file qscriptqobject_p.h.
Referenced by findWrapper(), mark(), and registerWrapper().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptqobject_p.h
/src/script/bridge/qscriptqobject.cpp