Qt 4.8: QSvgStrokeStyle Class Reference
QSvgStrokeStyle Class Reference
#include <qsvgstyle_p.h>
Public Functions
virtual void apply (QPainter *p, const QSvgNode *node, QSvgExtraStates &states)
QString gradientId () const
bool isGradientResolved () const
QSvgStrokeStyle ()
virtual void revert (QPainter *p, QSvgExtraStates &states)
void setDashArray (const QVector< qreal > &dashes)
void setDashArrayNone ()
void setDashOffset (qreal offset)
void setGradientId (const QString &Id)
void setGradientResolved (bool resolved)
void setLineCap (Qt::PenCapStyle cap)
void setLineJoin (Qt::PenJoinStyle join)
void setMiterLimit (qreal limit)
void setOpacity (qreal opacity)
void setStroke (QBrush brush)
void setStyle (QSvgFillStyleProperty *style)
void setVectorEffect (bool nonScalingStroke)
void setWidth (qreal width)
QPen stroke () const
QSvgFillStyleProperty * style () const
virtual Type type () const
qreal width ()
Public Functions inherited from QSvgStyleProperty
virtual ~QSvgStyleProperty ()
Public Functions inherited from QSvgRefCounted
void deref ()
QSvgRefCounted ()
void ref ()
virtual ~QSvgRefCounted ()
Properties
QString m_gradientId
uint m_gradientResolved: 1
QPen m_oldStroke
qreal m_oldStrokeDashOffset
qreal m_oldStrokeOpacity
uint m_oldVectorEffect: 1
QPen m_stroke
uint m_strokeDashArraySet: 1
qreal m_strokeDashOffset
uint m_strokeDashOffsetSet: 1
uint m_strokeLineCapSet: 1
uint m_strokeLineJoinSet: 1
uint m_strokeMiterLimitSet: 1
qreal m_strokeOpacity
uint m_strokeOpacitySet: 1
uint m_strokeSet: 1
uint m_strokeWidthSet: 1
QSvgFillStyleProperty * m_style
uint m_vectorEffect: 1
uint m_vectorEffectSet: 1
Additional Inherited Members
Public Types inherited from QSvgStyleProperty
enum Type {
QUALITY, FILL, VIEWPORT_FILL, FONT,
STROKE, SOLID_COLOR, GRADIENT, TRANSFORM,
ANIMATE_TRANSFORM, ANIMATE_COLOR, OPACITY, COMP_OP
}
Detailed Description
Definition at line 409 of file qsvgstyle_p.h.
Constructors and Destructors
QSvgStrokeStyle()
QSvgStrokeStyle::QSvgStrokeStyle ()
Definition at line 274 of file qsvgstyle.cpp.
     : m_strokeOpacity(1.0)
     , m_oldStrokeOpacity(0.0)
     , m_strokeDashOffset(0)
     , m_oldStrokeDashOffset(0)
     , m_style(0)
     , m_gradientResolved(1)
     , m_vectorEffect(0)
     , m_oldVectorEffect(0)
     , m_strokeSet(0)
     , m_strokeDashArraySet(0)
     , m_strokeDashOffsetSet(0)
     , m_strokeLineCapSet(0)
     , m_strokeLineJoinSet(0)
     , m_strokeMiterLimitSet(0)
     , m_strokeOpacitySet(0)
     , m_strokeWidthSet(0)
     , m_vectorEffectSet(0)
 {
 }
Functions
apply()
void QSvgStrokeStyle::apply (QPainter * p, const QSvgNode * node, QSvgExtraStates & states) virtual
Implements QSvgStyleProperty.
Definition at line 295 of file qsvgstyle.cpp.
 {
     m_oldStroke = p->pen();
     m_oldStrokeOpacity = states.strokeOpacity;
     m_oldStrokeDashOffset = states.strokeDashOffset;
     m_oldVectorEffect = states.vectorEffect;
     QPen pen = p->pen();
     qreal oldWidth = pen.widthF();
     qreal width = m_stroke.widthF();
     if (oldWidth == 0)
         oldWidth = 1;
     if (width == 0)
         width = 1;
     qreal scale = oldWidth / width;
     if (m_strokeOpacitySet)
         states.strokeOpacity = m_strokeOpacity;
     if (m_vectorEffectSet)
         states.vectorEffect = m_vectorEffect;
     if (m_strokeSet) {
         if (m_style)
             pen.setBrush(m_style->brush(p, states));
         else
             pen.setBrush(m_stroke.brush());
     }
     if (m_strokeWidthSet)
         pen.setWidthF(m_stroke.widthF());
     bool setDashOffsetNeeded = false;
     if (m_strokeDashOffsetSet) {
         states.strokeDashOffset = m_strokeDashOffset;
         setDashOffsetNeeded = true;
     }
     if (m_strokeDashArraySet) {
         if (m_stroke.style() == Qt::SolidLine) {
             pen.setStyle(Qt::SolidLine);
         } else if (m_strokeWidthSet || oldWidth == 1) {
             // If both width and dash array was set, the dash array is already scaled correctly.
             pen.setDashPattern(m_stroke.dashPattern());
             setDashOffsetNeeded = true;
         } else {
             // If dash array was set, but not the width, the dash array has to be scaled with respect to the old width.
             QVector<qreal> dashes = m_stroke.dashPattern();
             for (int i = 0; i < dashes.size(); ++i)
                 dashes[i] /= oldWidth;
             pen.setDashPattern(dashes);
             setDashOffsetNeeded = true;
         }
     } else if (m_strokeWidthSet && pen.style() != Qt::SolidLine && scale != 1) {
         // If the width was set, but not the dash array, the old dash array must be scaled with respect to the new width.
         QVector<qreal> dashes = pen.dashPattern();
         for (int i = 0; i < dashes.size(); ++i)
             dashes[i] *= scale;
         pen.setDashPattern(dashes);
         setDashOffsetNeeded = true;
     }
     if (m_strokeLineCapSet)
         pen.setCapStyle(m_stroke.capStyle());
     if (m_strokeLineJoinSet)
         pen.setJoinStyle(m_stroke.joinStyle());
     if (m_strokeMiterLimitSet)
         pen.setMiterLimit(m_stroke.miterLimit());
     // You can have dash offset on solid strokes in SVG files, but not in Qt.
     // QPen::setDashOffset() will set the pen style to Qt::CustomDashLine,
     // so don't call the method if the pen is solid.
     if (setDashOffsetNeeded && pen.style() != Qt::SolidLine) {
         qreal currentWidth = pen.widthF();
         if (currentWidth == 0)
             currentWidth = 1;
         pen.setDashOffset(states.strokeDashOffset / currentWidth);
     }
     pen.setCosmetic(states.vectorEffect);
     p->setPen(pen);
 }
gradientId()
QString QSvgStrokeStyle::gradientId () const inline
Definition at line 496 of file qsvgstyle_p.h.
Referenced by QSvgHandler::resolveGradients().
     {
         return m_gradientId;
     }
isGradientResolved()
bool QSvgStrokeStyle::isGradientResolved () const inline
Definition at line 506 of file qsvgstyle_p.h.
Referenced by QSvgHandler::resolveGradients().
     {
         return m_gradientResolved;
     }
revert()
void QSvgStrokeStyle::revert (QPainter * p, QSvgExtraStates & states) virtual
Implements QSvgStyleProperty.
Definition at line 381 of file qsvgstyle.cpp.
 {
     p->setPen(m_oldStroke);
     states.strokeOpacity = m_oldStrokeOpacity;
     states.strokeDashOffset = m_oldStrokeDashOffset;
     states.vectorEffect = m_oldVectorEffect;
 }
setDashArray()
void QSvgStrokeStyle::setDashArray (const QVector< qreal > & dashes)
Definition at line 389 of file qsvgstyle.cpp.
Referenced by parsePen().
 {
     if (m_strokeWidthSet) {
         QVector<qreal> d = dashes;
         qreal w = m_stroke.widthF();
         if (w != 0 && w != 1) {
             for (int i = 0; i < d.size(); ++i)
                 d[i] /= w;
         }
         m_stroke.setDashPattern(d);
     } else {
         m_stroke.setDashPattern(dashes);
     }
     m_strokeDashArraySet = 1;
 }
setDashArrayNone()
void QSvgStrokeStyle::setDashArrayNone () inline
Definition at line 432 of file qsvgstyle_p.h.
Referenced by parsePen().
     {
         m_stroke.setStyle(Qt::SolidLine);
         m_strokeDashArraySet = 1;
     }
setDashOffset()
void QSvgStrokeStyle::setDashOffset (qreal offset) inline
Definition at line 438 of file qsvgstyle_p.h.
Referenced by parsePen().
     {
         m_strokeDashOffset = offset;
         m_strokeDashOffsetSet = 1;
     }
setGradientId()
void QSvgStrokeStyle::setGradientId (const QString & Id) inline
Definition at line 491 of file qsvgstyle_p.h.
Referenced by parsePen().
     {
         m_gradientId = Id;
     }
setGradientResolved()
void QSvgStrokeStyle::setGradientResolved (bool resolved) inline
Definition at line 501 of file qsvgstyle_p.h.
Referenced by parsePen().
     {
         m_gradientResolved = resolved;
     }
setLineCap()
void QSvgStrokeStyle::setLineCap (Qt::PenCapStyle cap) inline
Definition at line 444 of file qsvgstyle_p.h.
Referenced by parsePen().
     {
         m_stroke.setCapStyle(cap);
         m_strokeLineCapSet = 1;
     }
setLineJoin()
void QSvgStrokeStyle::setLineJoin (Qt::PenJoinStyle join) inline
Definition at line 450 of file qsvgstyle_p.h.
Referenced by parsePen().
     {
         m_stroke.setJoinStyle(join);
         m_strokeLineJoinSet = 1;
     }
setMiterLimit()
void QSvgStrokeStyle::setMiterLimit (qreal limit) inline
Definition at line 456 of file qsvgstyle_p.h.
Referenced by parsePen().
     {
         m_stroke.setMiterLimit(limit);
         m_strokeMiterLimitSet = 1;
     }
setOpacity()
void QSvgStrokeStyle::setOpacity (qreal opacity) inline
Definition at line 462 of file qsvgstyle_p.h.
Referenced by parsePen().
     {
         m_strokeOpacity = opacity;
         m_strokeOpacitySet = 1;
     }
setStroke()
void QSvgStrokeStyle::setStroke (QBrush brush) inline
Definition at line 417 of file qsvgstyle_p.h.
Referenced by parsePen(), and QSvgHandler::resolveGradients().
     {
         m_stroke.setBrush(brush);
         m_style = 0;
         m_strokeSet = 1;
     }
setStyle()
void QSvgStrokeStyle::setStyle (QSvgFillStyleProperty * style) inline
Definition at line 424 of file qsvgstyle_p.h.
Referenced by parsePen(), and QSvgHandler::resolveGradients().
     {
         m_style = style;
         m_strokeSet = 1;
     }
setVectorEffect()
void QSvgStrokeStyle::setVectorEffect (bool nonScalingStroke) inline
Definition at line 480 of file qsvgstyle_p.h.
Referenced by parsePen().
     {
         m_vectorEffect = nonScalingStroke;
         m_vectorEffectSet = 1;
     }
setWidth()
void QSvgStrokeStyle::setWidth (qreal width) inline
Definition at line 468 of file qsvgstyle_p.h.
Referenced by parsePen().
     {
         m_stroke.setWidthF(width);
         m_strokeWidthSet = 1;
         Q_ASSERT(!m_strokeDashArraySet); // set width before dash array.
     }
stroke()
QPen QSvgStrokeStyle::stroke () const inline
Definition at line 511 of file qsvgstyle_p.h.
     {
         return m_stroke;
     }
style()
QSvgFillStyleProperty* QSvgStrokeStyle::style () const inline
Definition at line 486 of file qsvgstyle_p.h.
     {
         return m_style;
     }
type()
QSvgStyleProperty::Type QSvgStrokeStyle::type () const virtual
Implements QSvgStyleProperty.
Definition at line 477 of file qsvgstyle.cpp.
 {
     return STROKE;
 }
width()
qreal QSvgStrokeStyle::width () inline
Definition at line 475 of file qsvgstyle_p.h.
Referenced by apply().
     {
         return m_stroke.widthF();
     }
Properties
m_gradientId
QString QSvgStrokeStyle::m_gradientId private
Definition at line 533 of file qsvgstyle_p.h.
m_gradientResolved
uint QSvgStrokeStyle::m_gradientResolved private
Definition at line 534 of file qsvgstyle_p.h.
m_oldStroke
QPen QSvgStrokeStyle::m_oldStroke private
Definition at line 526 of file qsvgstyle_p.h.
Referenced by apply(), and revert().
m_oldStrokeDashOffset
qreal QSvgStrokeStyle::m_oldStrokeDashOffset private
Definition at line 530 of file qsvgstyle_p.h.
Referenced by apply(), and revert().
m_oldStrokeOpacity
qreal QSvgStrokeStyle::m_oldStrokeOpacity private
Definition at line 528 of file qsvgstyle_p.h.
Referenced by apply(), and revert().
m_oldVectorEffect
uint QSvgStrokeStyle::m_oldVectorEffect private
Definition at line 536 of file qsvgstyle_p.h.
Referenced by apply(), and revert().
m_stroke
QPen QSvgStrokeStyle::m_stroke private
Definition at line 525 of file qsvgstyle_p.h.
Referenced by apply(), and setDashArray().
m_strokeDashArraySet
uint QSvgStrokeStyle::m_strokeDashArraySet private
Definition at line 539 of file qsvgstyle_p.h.
Referenced by apply(), and setDashArray().
m_strokeDashOffset
qreal QSvgStrokeStyle::m_strokeDashOffset private
Definition at line 529 of file qsvgstyle_p.h.
Referenced by apply().
m_strokeDashOffsetSet
uint QSvgStrokeStyle::m_strokeDashOffsetSet private
Definition at line 540 of file qsvgstyle_p.h.
Referenced by apply().
m_strokeLineCapSet
uint QSvgStrokeStyle::m_strokeLineCapSet private
Definition at line 541 of file qsvgstyle_p.h.
Referenced by apply().
m_strokeLineJoinSet
uint QSvgStrokeStyle::m_strokeLineJoinSet private
Definition at line 542 of file qsvgstyle_p.h.
Referenced by apply().
m_strokeMiterLimitSet
uint QSvgStrokeStyle::m_strokeMiterLimitSet private
Definition at line 543 of file qsvgstyle_p.h.
Referenced by apply().
m_strokeOpacity
qreal QSvgStrokeStyle::m_strokeOpacity private
Definition at line 527 of file qsvgstyle_p.h.
Referenced by apply().
m_strokeOpacitySet
uint QSvgStrokeStyle::m_strokeOpacitySet private
Definition at line 544 of file qsvgstyle_p.h.
Referenced by apply().
m_strokeSet
uint QSvgStrokeStyle::m_strokeSet private
Definition at line 538 of file qsvgstyle_p.h.
Referenced by apply().
m_strokeWidthSet
uint QSvgStrokeStyle::m_strokeWidthSet private
Definition at line 545 of file qsvgstyle_p.h.
Referenced by apply(), and setDashArray().
m_style
QSvgFillStyleProperty* QSvgStrokeStyle::m_style private
Definition at line 532 of file qsvgstyle_p.h.
Referenced by apply().
m_vectorEffect
uint QSvgStrokeStyle::m_vectorEffect private
Definition at line 535 of file qsvgstyle_p.h.
Referenced by apply().
m_vectorEffectSet
uint QSvgStrokeStyle::m_vectorEffectSet private
Definition at line 546 of file qsvgstyle_p.h.
Referenced by apply().
The documentation for this class was generated from the following files:
/src/svg/qsvgstyle_p.h
/src/svg/qsvgstyle.cpp