Qt 4.8: QPatternist::HexBinary Class Reference
QPatternist::HexBinary Class Reference
Implements the value instance of the xs:hexBinary type.
#include <qhexbinary_p.h>
Public Types
typedef AtomicValue::Ptr Ptr
Public Types inherited from QPatternist::Base64Binary
typedef AtomicValue::Ptr Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual QString stringValue () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::Base64Binary
const QByteArray & asByteArray () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static AtomicValue::Ptr fromLexical (const NamePool::Ptr &np, const QString &value)
static HexBinary::Ptr fromValue (const QByteArray &data)
Static Public Functions inherited from QPatternist::Base64Binary
static AtomicValue::Ptr fromLexical (const QString &value)
static Base64Binary::Ptr fromValue (const QByteArray &data)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
HexBinary (const QByteArray &val)
Protected Functions inherited from QPatternist::Base64Binary
Base64Binary (const QByteArray &val)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Static Private Functions
static qint8 fromHex (const QChar &c)
Returns -1 on invalid input.
Friends
class CommonValues
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Variables inherited from QPatternist::Base64Binary
const QByteArray m_value
Detailed Description
Implements the value instance of the xs:hexBinary type.
HexBinary inherits from Base64Binary for implementation reasons. The two classes are similar, and inheritance therefore save code.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 74 of file qhexbinary_p.h.
Typedefs
Ptr
typedef AtomicValue::Ptr QPatternist::HexBinary::Ptr
Definition at line 79 of file qhexbinary_p.h.
Constructors and Destructors
HexBinary()
HexBinary::HexBinary (const QByteArray & val) protected
Definition at line 55 of file qhexbinary.cpp.
Referenced by fromLexical(), and fromValue().
                                           : Base64Binary(val)
 {
 }
Functions
fromHex()
qint8 HexBinary::fromHex (const QChar & c) inline static private
Returns -1 on invalid input.
Definition at line 59 of file qhexbinary.cpp.
Referenced by fromLexical().
 {
     if(c.unicode() > 'f')
         return -1;
     const char *const range = "0123456789ABCDEFabcdef";
     const char *const in = strchr(range, c.unicode());
     if(!in)
         return -1;
     /* Pointer arithmetic. */
     int digit = in - range;
     if(digit > 15)
         digit -= 6;
     return digit;
 }
fromLexical()
AtomicValue::Ptr HexBinary::fromLexical (const NamePool::Ptr & np, const QString & value) static
Creates a xs:hexBinary from the lexical representation value.
Definition at line 80 of file qhexbinary.cpp.
Referenced by QPatternist::StringToHexBinaryCaster::castFrom().
 {
     const QString lexical(str.trimmed());
     const int len = lexical.length();
     if(len == 0)
         return AtomicValue::Ptr(new HexBinary(QByteArray()));
     if((len & 1) != 0)
     {
         /* Catch a common case. */
         return ValidationError::createError(QtXmlPatterns::tr(
                   "A value of type %1 must contain an even number of "
                   "digits. The value %2 does not.")
                   .arg(formatType(np, BuiltinTypes::xsHexBinary),
                        formatData(QString::number(len))));
     }
     QByteArray val;
     val.resize(len / 2);
     for(int i = 0; i < len / 2; ++i)
     {
         qint8 p1 = fromHex(lexical[i * 2]);
         qint8 p2 = fromHex(lexical[i * 2 + 1]);
         if(p1 == -1 || p2 == -1)
         {
             const QString hex(QString::fromLatin1("%1%2").arg(lexical[i * 2], lexical[i * 2 + 1]));
             return ValidationError::createError(QtXmlPatterns::tr(
                              "%1 is not valid as a value of type %2.")
                              .arg(formatData(hex),
                                   formatType(np, BuiltinTypes::xsHexBinary)));
         }
         val[i] = static_cast<char>(p1 * 16 + p2);
     }
     Q_ASSERT(!val.isEmpty());
     return AtomicValue::Ptr(new HexBinary(val));
 }
fromValue()
HexBinary::Ptr HexBinary::fromValue (const QByteArray & data) static
Creates an instance representing value.
Definition at line 123 of file qhexbinary.cpp.
Referenced by QPatternist::Base64BinaryToHexBinaryCaster::castFrom(), and QPatternist::AtomicValue::toXDM().
 {
     return HexBinary::Ptr(new HexBinary(data));
 }
stringValue()
QString HexBinary::stringValue () const virtual
Reimplemented from QPatternist::Base64Binary.
Definition at line 128 of file qhexbinary.cpp.
 {
     static const char s_toHex[] = "0123456789ABCDEF";
     const int len = m_value.count();
     QString result;
     result.reserve(len * 2);
     for(int i = 0; i < len; ++i)
     {
         // This cast is significant.
         const unsigned char val = static_cast<unsigned char>(m_value.at(i));
         result += QLatin1Char(s_toHex[val >> 4]);
         result += QLatin1Char(s_toHex[val & 0x0F]);
     }
     return result;
 }
type()
ItemType::Ptr HexBinary::type () const virtual
Reimplemented from QPatternist::Base64Binary.
Definition at line 146 of file qhexbinary.cpp.
 {
     return BuiltinTypes::xsHexBinary;
 }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 77 of file qhexbinary_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qhexbinary_p.h
/src/xmlpatterns/data/qhexbinary.cpp