Qt 4.8: QPatternist::XsdSchema Class Reference
QPatternist::XsdSchema Class Reference
XML Schema Processing
Represents a XSD schema object.
#include <qxsdschema_p.h>
Public Types
typedef QList< XsdSchema::Ptr > List
typedef QExplicitlySharedDataPointer< XsdSchema > Ptr
Public Functions
void addAnonymousType (const SchemaType::Ptr &type)
void addAttribute (const XsdAttribute::Ptr &attribute)
void addAttributeGroup (const XsdAttributeGroup::Ptr &group)
void addElement (const XsdElement::Ptr &element)
void addElementGroup (const XsdModelGroup::Ptr &group)
void addIdentityConstraint (const XsdIdentityConstraint::Ptr &constraint)
void addNotation (const XsdNotation::Ptr &notation)
void addType (const SchemaType::Ptr &type)
SchemaType::List anonymousTypes () const
XsdAttribute::Ptr attribute (const QXmlName &name) const
XsdAttributeGroup::Ptr attributeGroup (const QXmlName name) const
XsdAttributeGroup::List attributeGroups () const
XsdAttribute::List attributes () const
XsdComplexType::List complexTypes () const
XsdElement::Ptr element (const QXmlName &name) const
XsdModelGroup::Ptr elementGroup (const QXmlName &name) const
XsdModelGroup::List elementGroups () const
XsdElement::List elements () const
XsdIdentityConstraint::Ptr identityConstraint (const QXmlName &name) const
XsdIdentityConstraint::List identityConstraints () const
NamePool::Ptr namePool () const
XsdNotation::Ptr notation (const QXmlName &name) const
XsdNotation::List notations () const
void setTargetNamespace (const QString &targetNamespace)
XsdSimpleType::List simpleTypes () const
QString targetNamespace () const
SchemaType::Ptr type (const QXmlName &name) const
SchemaType::List types () const
XsdSchema (const NamePool::Ptr &namePool)
~XsdSchema ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Properties
QHash< QXmlName, SchemaType::Ptr > m_anonymousTypes
QHash< QXmlName, XsdAttributeGroup::Ptr > m_attributeGroups
QHash< QXmlName, XsdAttribute::Ptr > m_attributes
QHash< QXmlName, XsdModelGroup::Ptr > m_elementGroups
QHash< QXmlName, XsdElement::Ptr > m_elements
QHash< QXmlName, XsdIdentityConstraint::Ptr > m_identityConstraints
QReadWriteLock m_lock
NamePool::Ptr m_namePool
QHash< QXmlName, XsdNotation::Ptr > m_notations
QString m_targetNamespace
QHash< QXmlName, SchemaType::Ptr > m_types
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Represents a XSD schema object.
The class provides access to all components of a parsed XSD.
Note
In the documentation of this class objects, which are direct children of the schema object, are called top-level objects.
See also
XML Schema API reference
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 91 of file qxsdschema_p.h.
Typedefs
List
typedef QList<XsdSchema::Ptr> QPatternist::XsdSchema::List
Definition at line 95 of file qxsdschema_p.h.
Ptr
typedef QExplicitlySharedDataPointer<XsdSchema> QPatternist::XsdSchema::Ptr
Definition at line 94 of file qxsdschema_p.h.
Constructors and Destructors
XsdSchema()
XsdSchema::XsdSchema (const NamePool::Ptr & namePool)
Creates a new schema object.
Parameters
namePool The namepool that should be used for names of all schema components.
Definition at line 51 of file qxsdschema.cpp.
     : m_namePool(namePool)
 {
 }
~XsdSchema()
XsdSchema::~XsdSchema ()
Destroys the schema object.
Definition at line 56 of file qxsdschema.cpp.
 {
 }
Functions
addAnonymousType()
void XsdSchema::addAnonymousType (const SchemaType::Ptr & type)
Adds an anonymous type to the schema. Anonymous types have no name and are declared locally inside an element object.
Parameters
type The new anonymous type.
Definition at line 168 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::addAnonymousType(), QPatternist::XsdSchemaMerger::merge(), and QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes().
 {
     const QWriteLocker locker(&m_lock);
     // search for not used anonymous type name
     QXmlName typeName = type->name(m_namePool);
     while (m_anonymousTypes.contains(typeName)) {
         typeName = m_namePool->allocateQName(QString(), QLatin1String("merged_") + m_namePool->stringForLocalName(typeName.localName()), QString());
     }
     m_anonymousTypes.insert(typeName, type);
 }
addAttribute()
void XsdSchema::addAttribute (const XsdAttribute::Ptr & attribute)
Adds a new top-level attribute to the schema.
Parameters
attribute The new attribute.
See also
Attribute Declaration
Definition at line 96 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::addAttribute(), and QPatternist::XsdSchemaMerger::merge().
 {
     const QWriteLocker locker(&m_lock);
     m_attributes.insert(attribute->name(m_namePool), attribute);
 }
addAttributeGroup()
void XsdSchema::addAttributeGroup (const XsdAttributeGroup::Ptr & group)
Adds a new top-level attribute group to the schema.
Parameters
group The new attribute group.
See also
Attribute Group Declaration
Definition at line 188 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::addAttributeGroup(), and QPatternist::XsdSchemaMerger::merge().
 {
     const QWriteLocker locker(&m_lock);
     m_attributeGroups.insert(group->name(m_namePool), group);
 }
addElement()
void XsdSchema::addElement (const XsdElement::Ptr & element)
Adds a new top-level element to the schema.
Parameters
element The new element.
See also
Element Declaration
Definition at line 75 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::addElement(), and QPatternist::XsdSchemaMerger::merge().
 {
     const QWriteLocker locker(&m_lock);
     m_elements.insert(element->name(m_namePool), element);
 }
addElementGroup()
void XsdSchema::addElementGroup (const XsdModelGroup::Ptr & group)
Adds a new top-level element group to the schema.
Parameters
group The new element group.
See also
Element Group Declaration
Definition at line 209 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::addElementGroup(), and QPatternist::XsdSchemaMerger::merge().
 {
     const QWriteLocker locker(&m_lock);
     m_elementGroups.insert(group->name(m_namePool), group);
 }
addIdentityConstraint()
void XsdSchema::addIdentityConstraint (const XsdIdentityConstraint::Ptr & constraint)
Adds a new identity constraint to the schema.
Definition at line 251 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::addIdentityConstraint(), and QPatternist::XsdSchemaMerger::merge().
 {
     const QWriteLocker locker(&m_lock);
     m_identityConstraints.insert(constraint->name(m_namePool), constraint);
 }
addNotation()
void XsdSchema::addNotation (const XsdNotation::Ptr & notation)
Adds a new top-level notation to the schema.
Parameters
notation The new notation.
See also
Notation Declaration
Definition at line 230 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::addNotation(), and QPatternist::XsdSchemaMerger::merge().
 {
     const QWriteLocker locker(&m_lock);
     m_notations.insert(notation->name(m_namePool), notation);
 }
addType()
void XsdSchema::addType (const SchemaType::Ptr & type)
Adds a new top-level type to the schema. That can be a simple or a complex type.
Parameters
type The new type.
See also
Simple Type Declaration
Complex Type Declaration
Definition at line 117 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::addType(), and QPatternist::XsdSchemaMerger::merge().
 {
     const QWriteLocker locker(&m_lock);
     m_types.insert(type->name(m_namePool), type);
 }
anonymousTypes()
SchemaType::List XsdSchema::anonymousTypes () const
Returns the list of all anonymous types.
Definition at line 181 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaChecker::checkAttributeUseConstraints(), QPatternist::XsdSchemaChecker::checkBasicCircularInheritances(), QPatternist::XsdSchemaChecker::checkBasicComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkBasicSimpleTypeConstraints(), QPatternist::XsdSchemaChecker::checkCircularInheritances(), QPatternist::XsdSchemaChecker::checkComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdSchemaChecker::checkDuplicatedAttributeUses(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), QPatternist::XsdSchemaChecker::checkInheritanceRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleDerivationRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), collectAllElements(), QPatternist::XsdSchemaDebugger::dumpSchema(), QPatternist::XsdSchemaMerger::merge(), QPatternist::XsdSchemaResolver::resolveAttributeInheritance(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), and QPatternist::XsdSchemaResolver::resolveTermReferences().
 {
     const QReadLocker locker(&m_lock);
     return m_anonymousTypes.values();
 }
attribute()
XsdAttribute::Ptr XsdSchema::attribute (const QXmlName & name) const
Returns the top-level attribute of the schema with the given name or an empty pointer if none exist.
Definition at line 103 of file qxsdschema.cpp.
Referenced by addAttribute(), QPatternist::XsdSchemaParser::addAttribute(), QPatternist::XsdValidatingInstanceReader::attributeByName(), QPatternist::XsdSchemaMerger::merge(), and QPatternist::XsdSchemaResolver::resolveAttributeTermReferences().
 {
     const QReadLocker locker(&m_lock);
     return m_attributes.value(name);
 }
attributeGroup()
XsdAttributeGroup::Ptr XsdSchema::attributeGroup (const QXmlName name) const
Returns the top-level attribute group of the schema with the given name or an empty pointer if none exist.
Definition at line 195 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::addAttributeGroup(), QPatternist::XsdSchemaMerger::merge(), and QPatternist::XsdSchemaResolver::resolveAttributeTermReferences().
 {
     const QReadLocker locker(&m_lock);
     return m_attributeGroups.value(name);
 }
attributeGroups()
XsdAttributeGroup::List XsdSchema::attributeGroups () const
Returns the list of all top-level attribute groups.
Definition at line 202 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkDuplicatedAttributeUses(), QPatternist::XsdSchemaMerger::merge(), QPatternist::XsdSchemaParser::parseRedefine(), and QPatternist::XsdSchemaResolver::resolveAttributeTermReferences().
 {
     const QReadLocker locker(&m_lock);
     return m_attributeGroups.values();
 }
attributes()
XsdAttribute::List XsdSchema::attributes () const
Returns the list of all top-level attributes.
Definition at line 110 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaDebugger::dumpSchema(), QPatternist::XsdSchemaMerger::merge(), and QPatternist::XsdSchemaParser::parseRedefine().
 {
     const QReadLocker locker(&m_lock);
     return m_attributes.values();
 }
complexTypes()
XsdComplexType::List XsdSchema::complexTypes () const
Returns the list of all top-level complex types.
Definition at line 153 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::parseRedefine().
 {
     QReadLocker locker(&m_lock);
     XsdComplexType::List retval;
     const SchemaType::List types = m_types.values();
     for (int i = 0; i < types.count(); ++i) {
         if (types.at(i)->isComplexType() && types.at(i)->isDefinedBySchema())
             retval.append(types.at(i));
     }
     return retval;
 }
element()
XsdElement::Ptr XsdSchema::element (const QXmlName & name) const
Returns the top-level element of the schema with the given name or an empty pointer if none exist.
Definition at line 82 of file qxsdschema.cpp.
Referenced by addElement(), QPatternist::XsdSchemaParser::addElement(), QPatternist::XsdValidatingInstanceReader::elementByName(), QPatternist::XsdSchemaMerger::merge(), QPatternist::XsdSchemaResolver::resolveSubstitutionGroupAffiliations(), and QPatternist::XsdSchemaResolver::resolveTermReference().
 {
     const QReadLocker locker(&m_lock);
     return m_elements.value(name);
 }
elementGroup()
XsdModelGroup::Ptr XsdSchema::elementGroup (const QXmlName & name) const
Returns the top-level element group of the schema with the given name or an empty pointer if none exist.
Definition at line 216 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::addElementGroup(), QPatternist::XsdSchemaMerger::merge(), and QPatternist::XsdSchemaResolver::resolveTermReference().
 {
     const QReadLocker locker(&m_lock);
     return m_elementGroups.value(name);
 }
elementGroups()
XsdModelGroup::List XsdSchema::elementGroups () const
Returns the list of all top-level element groups.
Definition at line 223 of file qxsdschema.cpp.
Referenced by collectAllElements(), QPatternist::XsdSchemaMerger::merge(), QPatternist::XsdSchemaParser::parseRedefine(), and QPatternist::XsdSchemaResolver::resolveTermReferences().
 {
     const QReadLocker locker(&m_lock);
     return m_elementGroups.values();
 }
elements()
XsdElement::List XsdSchema::elements () const
Returns the list of all top-level elements.
Definition at line 89 of file qxsdschema.cpp.
Referenced by collectAllElements(), QPatternist::XsdSchemaDebugger::dumpSchema(), QPatternist::XsdSchemaMerger::merge(), QPatternist::XsdSchemaParser::parseRedefine(), and QPatternist::XsdSchemaResolver::resolveSubstitutionGroups().
 {
     const QReadLocker locker(&m_lock);
     return m_elements.values();
 }
identityConstraint()
XsdIdentityConstraint::Ptr XsdSchema::identityConstraint (const QXmlName & name) const
Returns the identity constraint with the given name or an empty pointer if none exist.
Definition at line 258 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::addIdentityConstraint(), QPatternist::XsdSchemaMerger::merge(), and QPatternist::XsdSchemaResolver::resolveKeyReferences().
 {
     const QReadLocker locker(&m_lock);
     return m_identityConstraints.value(name);
 }
identityConstraints()
XsdIdentityConstraint::List XsdSchema::identityConstraints () const
Returns the list of all identity constraints in this schema.
Definition at line 265 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaMerger::merge().
 {
     const QReadLocker locker(&m_lock);
     return m_identityConstraints.values();
 }
namePool()
NamePool::Ptr XsdSchema::namePool () const
Returns the namepool that is used for names of all schema components.
Definition at line 60 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaMerger::merge().
 {
     return m_namePool;
 }
notation()
XsdNotation::Ptr XsdSchema::notation (const QXmlName & name) const
Returns the top-level notation of the schema with the given name or an empty pointer if none exist.
Definition at line 237 of file qxsdschema.cpp.
Referenced by addNotation(), QPatternist::XsdSchemaParser::addNotation(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), and QPatternist::XsdSchemaMerger::merge().
 {
     const QReadLocker locker(&m_lock);
     return m_notations.value(name);
 }
notations()
XsdNotation::List XsdSchema::notations () const
Returns the list of all top-level notations.
Definition at line 244 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaMerger::merge(), and QPatternist::XsdSchemaParser::parseRedefine().
 {
     const QReadLocker locker(&m_lock);
     return m_notations.values();
 }
setTargetNamespace()
void XsdSchema::setTargetNamespace (const QString & targetNamespace)
Sets the targetNamespace of the schema.
Definition at line 65 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::parseSchema().
 {
     m_targetNamespace = targetNamespace;
 }
simpleTypes()
XsdSimpleType::List XsdSchema::simpleTypes () const
Returns the list of all top-level simple types.
Definition at line 138 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaParser::parseRedefine().
 {
     QReadLocker locker(&m_lock);
     XsdSimpleType::List retval;
     const SchemaType::List types = m_types.values();
     for (int i = 0; i < types.count(); ++i) {
         if (types.at(i)->isSimpleType() && types.at(i)->isDefinedBySchema())
             retval.append(types.at(i));
     }
     return retval;
 }
targetNamespace()
QString XsdSchema::targetNamespace () const
Returns the target namespace of the schema.
Definition at line 70 of file qxsdschema.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::addSchema(), and setTargetNamespace().
 {
     return m_targetNamespace;
 }
type()
SchemaType::Ptr XsdSchema::type (const QXmlName & name) const
Returns the top-level type of the schema with the given name or an empty pointer if none exist.
Definition at line 124 of file qxsdschema.cpp.
Referenced by addType(), QPatternist::XsdSchemaParser::addType(), QPatternist::XsdSchemaMerger::merge(), QPatternist::XsdSchemaResolver::resolveAlternativeTypes(), QPatternist::XsdSchemaResolver::resolveAttributeTypes(), QPatternist::XsdSchemaResolver::resolveComplexBaseTypes(), QPatternist::XsdSchemaResolver::resolveElementTypes(), QPatternist::XsdSchemaResolver::resolveSimpleListType(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictionBaseTypes(), QPatternist::XsdSchemaResolver::resolveSimpleUnionTypes(), and QPatternist::XsdValidatingInstanceReader::typeByName().
 {
     const QReadLocker locker(&m_lock);
     return m_types.value(name);
 }
types()
SchemaType::List XsdSchema::types () const
Returns the list of all top-level types.
Definition at line 131 of file qxsdschema.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaChecker::checkAttributeUseConstraints(), QPatternist::XsdSchemaChecker::checkBasicCircularInheritances(), QPatternist::XsdSchemaChecker::checkBasicComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkBasicSimpleTypeConstraints(), QPatternist::XsdSchemaChecker::checkCircularInheritances(), QPatternist::XsdSchemaChecker::checkComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdSchemaChecker::checkDuplicatedAttributeUses(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), QPatternist::XsdSchemaChecker::checkInheritanceRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleDerivationRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), collectAllElements(), complexTypes(), QPatternist::XsdSchemaDebugger::dumpSchema(), QPatternist::XsdSchemaMerger::merge(), QPatternist::XsdSchemaResolver::resolveAttributeInheritance(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), QPatternist::XsdSchemaResolver::resolveTermReferences(), and simpleTypes().
 {
     const QReadLocker locker(&m_lock);
     return m_types.values();
 }
Properties
m_anonymousTypes
QHash<QXmlName, SchemaType::Ptr> QPatternist::XsdSchema::m_anonymousTypes private
Definition at line 288 of file qxsdschema_p.h.
Referenced by addAnonymousType(), and anonymousTypes().
m_attributeGroups
QHash<QXmlName, XsdAttributeGroup::Ptr> QPatternist::XsdSchema::m_attributeGroups private
Definition at line 289 of file qxsdschema_p.h.
Referenced by addAttributeGroup(), attributeGroup(), and attributeGroups().
m_attributes
QHash<QXmlName, XsdAttribute::Ptr> QPatternist::XsdSchema::m_attributes private
Definition at line 286 of file qxsdschema_p.h.
Referenced by addAttribute(), attribute(), and attributes().
m_elementGroups
QHash<QXmlName, XsdModelGroup::Ptr> QPatternist::XsdSchema::m_elementGroups private
Definition at line 290 of file qxsdschema_p.h.
Referenced by addElementGroup(), elementGroup(), and elementGroups().
m_elements
QHash<QXmlName, XsdElement::Ptr> QPatternist::XsdSchema::m_elements private
Definition at line 285 of file qxsdschema_p.h.
Referenced by addElement(), element(), and elements().
m_identityConstraints
QHash<QXmlName, XsdIdentityConstraint::Ptr> QPatternist::XsdSchema::m_identityConstraints private
Definition at line 292 of file qxsdschema_p.h.
Referenced by addIdentityConstraint(), identityConstraint(), and identityConstraints().
m_lock
QReadWriteLock QPatternist::XsdSchema::m_lock mutable private
Definition at line 293 of file qxsdschema_p.h.
Referenced by addAnonymousType(), addAttribute(), addAttributeGroup(), addElement(), addElementGroup(), addIdentityConstraint(), addNotation(), addType(), anonymousTypes(), attribute(), attributeGroup(), attributeGroups(), attributes(), complexTypes(), element(), elementGroup(), elementGroups(), elements(), identityConstraint(), identityConstraints(), notation(), notations(), simpleTypes(), type(), and types().
m_namePool
NamePool::Ptr QPatternist::XsdSchema::m_namePool private
Definition at line 283 of file qxsdschema_p.h.
Referenced by addAnonymousType(), addAttribute(), addAttributeGroup(), addElement(), addElementGroup(), addIdentityConstraint(), addNotation(), addType(), and namePool().
m_notations
QHash<QXmlName, XsdNotation::Ptr> QPatternist::XsdSchema::m_notations private
Definition at line 291 of file qxsdschema_p.h.
Referenced by addNotation(), notation(), and notations().
m_targetNamespace
QString QPatternist::XsdSchema::m_targetNamespace private
Definition at line 284 of file qxsdschema_p.h.
Referenced by setTargetNamespace(), and targetNamespace().
m_types
QHash<QXmlName, SchemaType::Ptr> QPatternist::XsdSchema::m_types private
Definition at line 287 of file qxsdschema_p.h.
Referenced by addType(), complexTypes(), simpleTypes(), type(), and types().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdschema_p.h
/src/xmlpatterns/schema/qxsdschema.cpp