Qt 4.8: QGLExtensionMatcher Class Reference
QGLExtensionMatcher Class Reference
#include <qgl_p.h>
Public Functions
bool match (const char *str) const
Properties
QByteArray m_extensions
QVector< int > m_offsets
QGLExtensionMatcher (const char *str)
QGLExtensionMatcher ()
void init (const char *str)
Detailed Description
Definition at line 900 of file qgl_p.h.
Constructors and Destructors
QGLExtensionMatcher() [1/2]
QGLExtensionMatcher::QGLExtensionMatcher (const char * str)
Definition at line 5619 of file qgl.cpp.
 {
     init(str);
 }
QGLExtensionMatcher() [2/2]
QGLExtensionMatcher::QGLExtensionMatcher ()
Definition at line 5624 of file qgl.cpp.
 {
     const char *extensionStr = reinterpret_cast<const char *>(glGetString(GL_EXTENSIONS));
     if (extensionStr) {
         init(extensionStr);
     } else {
         // clear error state
         while (glGetError()) {}
         const QGLContext *ctx = QGLContext::currentContext();
         if (ctx) {
             qt_glGetStringi glGetStringi = (qt_glGetStringi)ctx->getProcAddress(QLatin1String("glGetStringi"));
             GLint numExtensions;
             glGetIntegerv(GL_NUM_EXTENSIONS, &numExtensions);
             for (int i = 0; i < numExtensions; ++i) {
                 const char *str = reinterpret_cast<const char *>(glGetStringi(GL_EXTENSIONS, i));
                 m_offsets << m_extensions.size();
                 while (*str != 0)
                     m_extensions.append(*str++);
                 m_extensions.append(' ');
             }
         }
     }
 }
Functions
init()
void QGLExtensionMatcher::init (const char * str) private
Definition at line 5654 of file qgl.cpp.
 {
     m_extensions = str;
     // make sure extension string ends with a space
     if (!m_extensions.endsWith(' '))
         m_extensions.append(' ');
     int index = 0;
     int next = 0;
     while ((next = m_extensions.indexOf(' ', index)) >= 0) {
         m_offsets << index;
         index = next + 1;
     }
 }
match()
bool QGLExtensionMatcher::match (const char * str) const inline
Definition at line 906 of file qgl_p.h.
Referenced by QGL2PaintEngineEx::begin(), buildSpec(), qgl_use_font(), qglx_getProcAddress(), qt_gl_resolve_features(), qt_resolve_buffer_extensions(), and QGLContext::tryVisual().
{
         int str_length = qstrlen(str);
         Q_ASSERT(str);
         Q_ASSERT(str_length > 0);
         Q_ASSERT(str[str_length-1] != ' ');
         for (int i = 0; i < m_offsets.size(); ++i) {
             const char *extension = m_extensions.constData() + m_offsets.at(i);
             if (qstrncmp(extension, str, str_length) == 0 && extension[str_length] == ' ')
                 return true;
         }
         return false;
     }
Properties
m_extensions
QByteArray QGLExtensionMatcher::m_extensions private
Definition at line 924 of file qgl_p.h.
m_offsets
QVector<int> QGLExtensionMatcher::m_offsets private
Definition at line 925 of file qgl_p.h.
The documentation for this class was generated from the following files:
/src/opengl/qgl_p.h
/src/opengl/qgl.cpp