Qt 4.8: QPatternist::GeneralComparison Class Reference
QPatternist::GeneralComparison Class Reference
Implements XPath 2.0's general comparions, such as the = operator.
#include <qgeneralcomparison_p.h>
Public Functions
virtual ExpressionVisitorResult::Ptr accept (const ExpressionVisitor::Ptr &visitor) const
virtual Expression::Ptr compress (const StaticContext::Ptr &context)
virtual bool evaluateEBV (const DynamicContext::Ptr &) const
virtual SequenceType::List expectedOperandTypes () const
GeneralComparison (const Expression::Ptr &op1, const AtomicComparator::Operator op, const Expression::Ptr &op2, const bool isBackwardsCompat=false)
virtual ID id () const
AtomicComparator::Operator operatorID () const
virtual QList< QExplicitlySharedDataPointer< OptimizationPass > > optimizationPasses () const
virtual SequenceType::Ptr staticType () const
virtual Expression::Ptr typeCheck (const StaticContext::Ptr &context, const SequenceType::Ptr &reqType)
Public Functions inherited from QPatternist::PairContainer
virtual bool compressOperands (const StaticContext::Ptr &)
virtual Expression::List operands () const
virtual void setOperands (const Expression::List &operands)
Public Functions inherited from QPatternist::Expression
virtual const SourceLocationReflection * actualReflection () const
Returns this.
virtual void announceFocusType (const ItemType::Ptr &itemType)
Properties deepProperties () const
Computes the union of properties for this Expression and all its descending children.
virtual Properties dependencies () const
virtual QString description () const
virtual Item::Iterator::Ptr evaluateSequence (const DynamicContext::Ptr &context) const
virtual Item evaluateSingleton (const DynamicContext::Ptr &context) const
virtual void evaluateToSequenceReceiver (const DynamicContext::Ptr &context) const
virtual ItemType::Ptr expectedContextItemType () const
Expression ()
bool has (const Property prop) const
bool hasDependency (const Property prop) const
bool is (const ID id) const
bool isEvaluated () const
virtual ItemType::Ptr newFocusType () const
virtual PatternPriority patternPriority () const
virtual Properties properties () const
const Expression::Ptr & rewrite (const Expression::Ptr &to, const StaticContext::Ptr &context) const
Rewrites this Expression to to, and return to.
virtual ~Expression ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< Expression >
const TCastTarget * as () const
TCastTarget * as ()
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Private Functions
AtomicComparator::Ptr fetchGeneralComparator (Expression::Ptr &op1, Expression::Ptr &op2, const ReportContext::Ptr &context) const
bool generalCompare (const Item &op1, const Item &op2, const DynamicContext::Ptr &context) const
Static Private Functions
static void updateType (ItemType::Ptr &type, const Expression::Ptr &source)
Properties
const bool m_isBackwardsCompat
const AtomicComparator::Operator m_operator
Additional Inherited Members
Public Types inherited from QPatternist::Expression
typedef QExplicitlySharedDataPointer< const Expression > ConstPtr
A smart pointer wrapping const Expression instances.
enum ID {
IDBooleanValue = 1, IDCountFN, IDEmptyFN, IDExistsFN,
IDExpressionSequence, IDGeneralComparison, IDIfThenClause, IDIgnorableExpression,
IDIntegerValue, IDPositionFN, IDStringValue, IDValueComparison,
IDRangeVariableReference, IDContextItem, IDUserFunctionCallsite, IDExpressionVariableReference,
IDAttributeConstructor, IDUpperCaseFN, IDLowerCaseFN, IDFirstItemPredicate,
IDEmptySequence, IDReturnOrderBy, IDLetClause, IDForClause,
IDPath, IDNamespaceConstructor, IDArgumentReference, IDGenericPredicate,
IDAxisStep, IDFloat, IDCombineNodes, IDUnresolvedVariableReference,
IDCardinalityVerifier
}
typedef QList< Expression::Ptr > List
typedef QFlags< Property > Properties
enum Property {
UseContextItem = 1, DisableElimination = 1 << 1, IsEvaluated = 1 << 2, DisableTypingDeduction = 1 << 3,
EmptynessFollowsChild = 1 << 4, RewriteToEmptyOnEmpty = 1 << 5, RequiresFocus = 1 << 6, AffectsOrderOnly = 1 << 7,
RequiresContextItem = (1 << 8) | RequiresFocus, CreatesFocusForLast = 1 << 9, LastOperandIsCollation = 1 << 10, DependsOnLocalVariable = (1 << 11) | DisableElimination,
EvaluationCacheRedundant = (1 << 12), IsNodeConstructor = 1 << 13, RequiresCurrentItem = 1 << 14
}
typedef QExplicitlySharedDataPointer< Expression > Ptr
A smart pointer wrapping mutable Expression instances.
typedef ::QAbstractXmlForwardIterator< Expression::Ptr > QAbstractXmlForwardIterator
typedef QVector< Expression::Ptr > Vector
Static Public Functions inherited from QPatternist::Expression
static void rewrite (Expression::Ptr &old, const Expression::Ptr &New, const StaticContext::Ptr &context)
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::PairContainer
PairContainer (const Expression::Ptr &operand1, const Expression::Ptr &operand2)
Protected Functions inherited from QPatternist::Expression
void typeCheckOperands (const StaticContext::Ptr &context)
Protected Functions inherited from QPatternist::CppCastingHelper< Expression >
CppCastingHelper ()
Protected Functions inherited from QPatternist::ComparisonPlatform< GeneralComparison, true, AtomicComparator::AsGeneralComparison >
const AtomicComparator::Ptr & comparator () const
bool compare (const Item &i1, const Item &i2, const AtomicComparator::Ptr &comp, const AtomicComparator::Operator op) const
Compares i1 and i2 with operator op, using comparator comp. All input arguments must be valid, and not null.
ComparisonPlatform ()
AtomicComparator::ComparisonResult detailedFlexibleCompare (const Item &it1, const Item &it2, const DynamicContext::Ptr &context) const
like flexibleCompare(), but returns the result as an AtomicComparator::Operator instead of bool.
AtomicComparator::Ptr fetchComparator (const ItemType::Ptr &type1, const ItemType::Ptr &type2, const ReportContext::Ptr &context) const
bool flexibleCompare (const Item &it1, const Item &it2, const DynamicContext::Ptr &context) const
Compares it1 against it2, using comparator() and operatorID().
void prepareComparison (const AtomicComparator::Ptr &comparator)
void useCaseInsensitiveComparator ()
Protected Variables inherited from QPatternist::PairContainer
Expression::Ptr m_operand1
Expression::Ptr m_operand2
Detailed Description
Implements XPath 2.0's general comparions, such as the = operator.
ComparisonPlatform is inherited with protected scope because ComparisonPlatform must access members of GeneralComparison.
See also
XML Path Language (XPath) 2.0, 3.5.2 General Comparisons
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 77 of file qgeneralcomparison_p.h.
Constructors and Destructors
GeneralComparison()
GeneralComparison::GeneralComparison (const Expression::Ptr & op1, const AtomicComparator::Operator op, const Expression::Ptr & op2, const bool isBackwardsCompat = false)
Definition at line 58 of file qgeneralcomparison.cpp.
                                                                    : PairContainer(op1, op2)
                                                                    , m_operator(op)
                                                                    , m_isBackwardsCompat(isBackwardsCompat)
 {
 }
Functions
accept()
ExpressionVisitorResult::Ptr GeneralComparison::accept (const ExpressionVisitor::Ptr & visitor) const virtual
Implements QPatternist::Expression.
Definition at line 287 of file qgeneralcomparison.cpp.
 {
     return visitor->visit(this);
 }
compress()
Expression::Ptr GeneralComparison::compress (const StaticContext::Ptr & context) virtual
Overridden to optimize case-insensitive compares.
Reimplemented from QPatternist::Expression.
Definition at line 135 of file qgeneralcomparison.cpp.
Referenced by operatorID().
 {
     const Expression::Ptr me(PairContainer::compress(context));
     if(me != this)
         return me;
     if(ValueComparison::isCaseInsensitiveCompare(m_operand1, m_operand2))
         useCaseInsensitiveComparator();
     return me;
 }
evaluateEBV()
bool GeneralComparison::evaluateEBV (const DynamicContext::Ptr & context) const virtual
Determines the Effective Boolean Value of the expression.
The Effective Boolean Value of a value is not necessarily the same as converting the value to a new value of type xs:boolean.
Note that this function cannot return the empty sequence, evaluateSingleton() must be overridden in order to be able to do that.
The default implementation results in a type error. Hence, this function must be overridden if such behavior is not of interest.
See also
XML Path Language (XPath) 2.0, 2.4.3 Effective Boolean Value
Reimplemented from QPatternist::Expression.
Definition at line 92 of file qgeneralcomparison.cpp.
 {
     const Item::Iterator::Ptr it1(m_operand1->evaluateSequence(context));
     Item item1(it1->next());
     if(!item1)
         return false;
     const Item::Iterator::Ptr it2(m_operand2->evaluateSequence(context));
     Item::List cache;
     Item item2;
     while(true)
     {
         item2 = it2->next();
         if(!item2)
             break;
         if(generalCompare(item1, item2, context))
             return true;
         cache.append(item2);
     }
     while(true)
     {
         item1 = it1->next();
         if(!item1)
             return false;
         const Item::List::const_iterator end(cache.constEnd());
         Item::List::const_iterator it(cache.constBegin());
         for(; it != end; ++it)
             if(generalCompare(item1, *it, context))
                 return true;
     }
     Q_ASSERT(false);
     return false;
 }
expectedOperandTypes()
SequenceType::List GeneralComparison::expectedOperandTypes () const virtual
Returns a list of Sequence Types, describing the type of each of the expression's operands. Hence, this function has a relationship to the operands() function:
- The lengths of the lists returned by expectedOperandTypes()
and operands() should always be equal in length, since one
cannot describe the type of a non-existent operand(and all
operands must have type information).
- A significant difference between the two functions is that while
the type of objects in the list returned by operands() may vary
between compilations/static context, simply because the particular
Expression is part of different XPath expressions, the
types in the list returned by expectedOperandTypes is always the same
since the function/operator signature never changes.
This function should not be confused with staticType(), which returns the static type of the expression itself, not its operands. The function call is an expression where this is clear: the type of the return value is not the same as the arguments' types. The static type of the operands supplied to the expression can be determined via the staticType() function of the instances returned by operands().
If the expression has no operands, an empty list should be returned.
Implements QPatternist::Expression.
Definition at line 274 of file qgeneralcomparison.cpp.
 {
     SequenceType::List result;
     result.append(CommonSequenceTypes::ZeroOrMoreAtomicTypes);
     result.append(CommonSequenceTypes::ZeroOrMoreAtomicTypes);
     return result;
 }
fetchGeneralComparator()
AtomicComparator::Ptr GeneralComparison::fetchGeneralComparator (Expression::Ptr & op1, Expression::Ptr & op2, const ReportContext::Ptr & context) const private
Definition at line 189 of file qgeneralcomparison.cpp.
Referenced by generalCompare(), operatorID(), and typeCheck().
 {
     ItemType::Ptr t1(op1->staticType()->itemType());
     ItemType::Ptr t2(op2->staticType()->itemType());
     /* a. "If one of the atomic values is an instance of xs:untypedAtomic and
      *    the other is an instance of a numeric type, then the xs:untypedAtomic
      *    value is cast to the type xs:double." */
     if(BuiltinTypes::numeric->xdtTypeMatches(t1) &&
        BuiltinTypes::xsUntypedAtomic->xdtTypeMatches(t2))
     {
         op2 = Expression::Ptr(new UntypedAtomicConverter(op2, BuiltinTypes::xsDouble));
         /* The types might have changed, reload. */
         updateType(t2, op2);
     }
     else if(BuiltinTypes::numeric->xdtTypeMatches(t2) &&
             BuiltinTypes::xsUntypedAtomic->xdtTypeMatches(t1))
     {
         op1 = Expression::Ptr(new UntypedAtomicConverter(op1, BuiltinTypes::xsDouble));
         /* The types might have changed, reload. */
         updateType(t1, op1);
     }
     /* "If XPath 1.0 compatibility mode is true, a general comparison is
      *  evaluated by applying the following rules, in order:
      *  1. If either operand is a single atomic value that is an instance of
      *  xs:boolean, then the other operand is converted to xs:boolean by taking
      *  its effective boolean value."
      *
      * Notably, it's not conversion to boolean, it is EBV extraction.
      */
     else if(m_isBackwardsCompat && BuiltinTypes::xsBoolean->xdtTypeMatches(t1))
     {
         op2 = Expression::Ptr(new EBVExtractor(op2));
         updateType(t2, op2);
     }
     else if(m_isBackwardsCompat && BuiltinTypes::xsBoolean->xdtTypeMatches(t2))
     {
         op1 = Expression::Ptr(new EBVExtractor(op1));
         updateType(t1, op1);
     }
     /* b. "If one of the atomic values is an instance of xs:untypedAtomic and
      *    the other is an instance of xs:untypedAtomic or xs:string, then the
      *    xs:untypedAtomic value (or values) is (are) cast to the type xs:string."
      *
      * c. "If one of the atomic values is an instance of xs:untypedAtomic and the
      *    other is not an instance of xs:string, xs:untypedAtomic, or any numeric
      *    type, then the xs:untypedAtomic value is cast to the dynamic type of the
      *    other value." */
     else if(BuiltinTypes::xsUntypedAtomic->xdtTypeMatches(t1) &&
             !BuiltinTypes::xsString->xdtTypeMatches(t2) &&
             !BuiltinTypes::xsUntypedAtomic->xdtTypeMatches(t2) &&
             !BuiltinTypes::xsAnyURI->xdtTypeMatches(t2))
     {
         op1 = Expression::Ptr(new UntypedAtomicConverter(op1, t2));
         updateType(t1, op1);
     }
     else if(BuiltinTypes::xsUntypedAtomic->xdtTypeMatches(t2) &&
             !BuiltinTypes::xsString->xdtTypeMatches(t1) &&
             !BuiltinTypes::xsUntypedAtomic->xdtTypeMatches(t1) &&
             !BuiltinTypes::xsAnyURI->xdtTypeMatches(t1))
     {
         op2 = Expression::Ptr(new UntypedAtomicConverter(op2, t1));
         updateType(t2, op2);
     }
     /* d. "After performing the conversions described above, the atomic
      *     values are compared using one of the value comparison operators
      *     eq, ne, lt, le, gt, or ge, depending on whether the general comparison
      *     operator was =, !=, <, <=, >, or >=. The values have the required
      *     magnitude relationship if and only if the result of this value comparison
      *     is true." */
     return fetchComparator(t1, t2, context);
 }
generalCompare()
bool GeneralComparison::generalCompare (const Item & op1, const Item & op2, const DynamicContext::Ptr & context) const private
Definition at line 67 of file qgeneralcomparison.cpp.
Referenced by evaluateEBV(), and operatorID().
 {
     Q_ASSERT(op1);
     Q_ASSERT(op2);
     if(comparator())
         return compare(op1, op2, comparator(), m_operator);
     Expression::Ptr a1(new Literal(op1));
     Expression::Ptr a2(new Literal(op2));
     const AtomicComparator::Ptr comp(fetchGeneralComparator(a1, a2, context));
     /* The fetchGeneralComparator call may rewrite a1 and/or a2. */
     Q_ASSERT(a1);
     Q_ASSERT(a2);
     Q_ASSERT(comp);
     return compare(a1->evaluateSingleton(context),
                    a2->evaluateSingleton(context),
                    comp,
                    m_operator);
 }
id()
Expression::ID GeneralComparison::id () const virtual
Returns
always IDGeneralComparison
Reimplemented from QPatternist::Expression.
Definition at line 292 of file qgeneralcomparison.cpp.
 {
     return IDGeneralComparison;
 }
operatorID()
AtomicComparator::Operator QPatternist::GeneralComparison::operatorID () const inline
Returns
the operator that this GeneralComparison is using.
Definition at line 107 of file qgeneralcomparison_p.h.
Referenced by QPatternist::ComparisonIdentifier::matches().
         {
             return m_operator;
         }
optimizationPasses()
OptimizationPass::List GeneralComparison::optimizationPasses () const virtual
Returns the OptimizationPasses that applies for this Expression. The default implementation returns an empty list. Sub-classes can re-implement this function and return actual OptimizationPasses.
Returns
always an empty list.
Reimplemented from QPatternist::Expression.
Definition at line 268 of file qgeneralcomparison.cpp.
 {
     Q_ASSERT(!OptimizationPasses::comparisonPasses.isEmpty());
     return OptimizationPasses::comparisonPasses;
 }
staticType()
SequenceType::Ptr GeneralComparison::staticType () const virtual
Returns
the static type of this Expression. For example, an 'and' expression have as static type xs:boolean
Implements QPatternist::Expression.
Definition at line 282 of file qgeneralcomparison.cpp.
 {
     return CommonSequenceTypes::ExactlyOneBoolean;
 }
typeCheck()
Expression::Ptr GeneralComparison::typeCheck (const StaticContext::Ptr & context, const SequenceType::Ptr & reqType) virtual
This implementation guarantees to never rewrite away this Expression, but at most rewrite it as a child of another expression(that presumably have a type checking role). It is therefore always safe to override this function and call this implementation and not worry about that this Expression becomes deleted.
Many Expressions override typeCheck() and performs optimizations, as opposed to doing it in the compress() stage. This is due to that the design of those Expressions often are tied to that certain simplifications are done at the typeCheck() stage of the compilation process or that it in some other way is related to what the typeCheck() do. Also, the earlier the AST can be simplified, the better the chances are for subsequent optimizations.
It is important that the super class's typeCheck() is called before doing any custom type checking, since the call can change the children(notably, the childrens' static types). For example, if the Expression, MyExpression in the example, does not match the required type, typeCheck returns the Expression wrapped in for example ItemVerifier, CardinalityVerifier, or both.
typeCheck() may be called many times. typeCheck() must either raise an error if this Expression is an invalid expression. Thus, it is guaranteed that an Expression is valid after typeCheck() is called.
Parameters
context supplies information, such as namespace bindings and available function signatures, that can be needed at compilation time. context is guaranteed by the caller to never null.
reqType the static type that this Expression must match when evaluated. reqType is guaranteed by the caller to never null.
Returns
an Expression that can be this Expression, or another expression, which somehow is necessary for making this Expression conforming to reqType
Reimplemented from QPatternist::Expression.
Definition at line 148 of file qgeneralcomparison.cpp.
 {
     const Expression::Ptr me(PairContainer::typeCheck(context, reqType));
     const ItemType::Ptr t1(m_operand1->staticType()->itemType());
     const ItemType::Ptr t2(m_operand2->staticType()->itemType());
     if(*CommonSequenceTypes::Empty == *t1 ||
        *CommonSequenceTypes::Empty == *t2)
     {
         return wrapLiteral(CommonValues::BooleanFalse, context, this);
     }
     if(*BuiltinTypes::xsAnyAtomicType == *t1 ||
        *BuiltinTypes::xsAnyAtomicType == *t2)
         return me;
     prepareComparison(fetchGeneralComparator(m_operand1, m_operand2, context));
     if(!m_operand1->staticType()->cardinality().allowsMany() &&
        !m_operand2->staticType()->cardinality().allowsMany())
     {
         /* Rewrite to a ValueComparison whose operands uses typing rules
          * as for an general comparison(that's what's done above). */
         return rewrite(Expression::Ptr(new ValueComparison(m_operand1,
                                                            m_operator,
                                                            m_operand2))->typeCheck(context, reqType),
                        context);
     }
     else
         return me;
 }
updateType()
void GeneralComparison::updateType (ItemType::Ptr & type, const Expression::Ptr & source) inline static private
Definition at line 183 of file qgeneralcomparison.cpp.
Referenced by fetchGeneralComparator(), and operatorID().
 {
     type = source->staticType()->itemType();
 }
Properties
m_isBackwardsCompat
const bool QPatternist::GeneralComparison::m_isBackwardsCompat private
Definition at line 128 of file qgeneralcomparison_p.h.
Referenced by fetchGeneralComparator().
m_operator
const AtomicComparator::Operator QPatternist::GeneralComparison::m_operator private
Definition at line 127 of file qgeneralcomparison_p.h.
Referenced by generalCompare(), operatorID(), and typeCheck().
The documentation for this class was generated from the following files:
/src/xmlpatterns/expr/qgeneralcomparison_p.h
/src/xmlpatterns/expr/qgeneralcomparison.cpp