Qt 4.8: QGestureRecognizer Class Reference
QGestureRecognizer Class Reference abstract
The QGestureRecognizer class provides the infrastructure for gesture recognition.
#include <qgesturerecognizer.h>
Public Types
enum ResultFlag {
Ignore = 0x0001, MayBeGesture = 0x0002, TriggerGesture = 0x0004, FinishGesture = 0x0008,
CancelGesture = 0x0010, ResultState_Mask = 0x00ff, ConsumeEventHint = 0x0100, ResultHint_Mask = 0xff00
}
This enum describes the result of the current event filtering step in a gesture recognizer state machine.
Public Functions
virtual QGesture * create (QObject *target)
This function is called by Qt to create a new QGesture object for the given target (QWidget or QGraphicsObject).
QGestureRecognizer ()
Constructs a new gesture recognizer object.
virtual Result recognize (QGesture *state, QObject *watched, QEvent *event)=0
Handles the given event for the watched object, updating the state of the gesture object as required, and returns a suitable result for the current recognition step.
virtual void reset (QGesture *state)
This function is called by the framework to reset a given gesture.
virtual ~QGestureRecognizer ()
Destroys the gesture recognizer.
Static Public Functions
static Qt::GestureType registerRecognizer (QGestureRecognizer *recognizer)
Registers the given recognizer in the gesture framework and returns a gesture ID for it.
static void unregisterRecognizer (Qt::GestureType type)
Unregisters all gesture recognizers of the specified type.
Detailed Description
The QGestureRecognizer class provides the infrastructure for gesture recognition.
Since
4.6
Gesture recognizers are responsible for creating and managing QGesture objects and monitoring input events sent to QWidget and QGraphicsObject subclasses. QGestureRecognizer is the base class for implementing custom gestures.
Developers that only need to provide gesture recognition for standard gestures do not need to use this class directly. Instances will be created behind the scenes by the framework.
For an overview of gesture handling in Qt and information on using gestures in your applications, see the Gestures Programming document.
Recognizing Gestures
The process of recognizing gestures involves filtering input events sent to specific objects, and modifying the associated QGesture objects to include relevant information about the user's input.
Gestures are created when the framework calls create() to handle user input for a particular instance of a QWidget or QGraphicsObject subclass. A QGesture object is created for each widget or item that is configured to use gestures.
Once a QGesture has been created for a target object, the gesture recognizer will receive events for it in its recognize() handler function.
When a gesture is canceled, the reset() function is called, giving the recognizer the chance to update the appropriate properties in the corresponding QGesture object.
Supporting New Gestures
To add support for new gestures, you need to derive from QGestureRecognizer to create a custom recognizer class, construct an instance of this class, and register it with the application by calling QGestureRecognizer::registerRecognizer(). You can also subclass QGesture to create a custom gesture class, or rely on dynamic properties to express specific details of the gesture you want to handle.
Your custom QGestureRecognizer subclass needs to reimplement the recognize() function to handle and filter the incoming input events for QWidget and QGraphicsObject subclasses. Although the logic for gesture recognition is implemented in this function, you can store persistent information about the state of the recognition process in the QGesture object supplied. The recognize() function must return a value of QGestureRecognizer::Result that indicates the state of recognition for a given gesture and target object. This determines whether or not a gesture event will be delivered to a target object.
If you choose to represent a gesture by a custom QGesture subclass, you will need to reimplement the create() function to construct instances of your gesture class. Similarly, you may need to reimplement the reset() function if your custom gesture objects need to be specially handled when a gesture is canceled.
See also
QGesture
Definition at line 59 of file qgesturerecognizer.h.
Enumerations
ResultFlag
enum QGestureRecognizer::ResultFlag
This enum describes the result of the current event filtering step in a gesture recognizer state machine.
The result consists of a state value (one of Ignore, MayBeGesture, TriggerGesture, FinishGesture, CancelGesture) and an optional hint (ConsumeEventHint).
Ignore The event does not change the state of the recognizer.
MayBeGesture The event changed the internal state of the recognizer, but it isn't clear yet if it is a gesture or not. The recognizer needs to filter more events to decide. Gesture recognizers in the MayBeGesture state may be reset automatically if they take too long to recognize gestures.
TriggerGesture The gesture has been triggered and the appropriate QGesture object will be delivered to the target as a part of a QGestureEvent.
FinishGesture The gesture has been finished successfully and the appropriate QGesture object will be delivered to the target as a part of a QGestureEvent.
CancelGesture The event made it clear that it is not a gesture. If the gesture recognizer was in GestureTriggered state before, then the gesture is canceled and the appropriate QGesture object will be delivered to the target as a part of a QGestureEvent.
ConsumeEventHint This hint specifies that the gesture framework should consume the filtered event and not deliver it to the receiver.
ResultState_Mask
ResultHint_Mask
See also
QGestureRecognizer::recognize()
Enumerator
Ignore
MayBeGesture
TriggerGesture
FinishGesture
CancelGesture
ResultState_Mask
ConsumeEventHint
ResultHint_Mask
Definition at line 62 of file qgesturerecognizer.h.
     {
         Ignore           = 0x0001,
         MayBeGesture     = 0x0002,
         TriggerGesture   = 0x0004,
         FinishGesture    = 0x0008,
         CancelGesture    = 0x0010,
         ResultState_Mask = 0x00ff,
         ConsumeEventHint        = 0x0100,
         // StoreEventHint          = 0x0200,
         // ReplayStoredEventsHint  = 0x0400,
         // DiscardStoredEventsHint = 0x0800,
         ResultHint_Mask = 0xff00
     };
Constructors and Destructors
QGestureRecognizer()
QGestureRecognizer::QGestureRecognizer ()
Constructs a new gesture recognizer object.
Definition at line 158 of file qgesturerecognizer.cpp.
 {
 }
~QGestureRecognizer()
QGestureRecognizer::~QGestureRecognizer () virtual
Destroys the gesture recognizer.
Definition at line 165 of file qgesturerecognizer.cpp.
 {
 }
Functions
create()
QGesture * QGestureRecognizer::create (QObject * target) virtual
This function is called by Qt to create a new QGesture object for the given target (QWidget or QGraphicsObject).
Reimplement this function to create a custom QGesture-derived gesture object if necessary.
The application takes ownership of the created gesture object.
Reimplemented in QTapAndHoldGestureRecognizer, QFlickGestureRecognizer, QTapGestureRecognizer, QSwipeGestureRecognizer, QMacPinchGestureRecognizer, QPinchGestureRecognizer, QMacSwipeGestureRecognizer, QWinNativePanGestureRecognizer, and QPanGestureRecognizer.
Definition at line 178 of file qgesturerecognizer.cpp.
Referenced by QGestureManager::getState(), and QGestureManager::registerGestureRecognizer().
 {
     Q_UNUSED(target);
     return new QGesture;
 }
recognize()
QGestureRecognizer::recognize (QGesture * gesture, QObject * watched, QEvent * event) pure virtual
Handles the given event for the watched object, updating the state of the gesture object as required, and returns a suitable result for the current recognition step.
This function is called by the framework to allow the recognizer to filter input events dispatched to QWidget or QGraphicsObject instances that it is monitoring.
The result reflects how much of the gesture has been recognized. The state of the gesture object is set depending on the result.
See also
QGestureRecognizer::Result
Implemented in QTapAndHoldGestureRecognizer, QFlickGestureRecognizer, QTapGestureRecognizer, QSwipeGestureRecognizer, QMacPinchGestureRecognizer, QPinchGestureRecognizer, QMacSwipeGestureRecognizer, QWinNativePanGestureRecognizer, and QPanGestureRecognizer.
Referenced by QGestureManager::filterEventThroughContexts().
registerRecognizer()
Qt::GestureType QGestureRecognizer::registerRecognizer (QGestureRecognizer * recognizer) static
Registers the given recognizer in the gesture framework and returns a gesture ID for it.
The application takes ownership of the recognizer and returns the gesture type ID associated with it. For gesture recognizers which handle custom QGesture objects (i.e., those which return Qt::CustomGesture in a QGesture::gestureType() function) the return value is a generated gesture ID with the Qt::CustomGesture flag set.
See also
unregisterRecognizer(), QGestureRecognizer::create(), QGesture
Definition at line 229 of file qgesturerecognizer.cpp.
 {
     return QGestureManager::instance()->registerGestureRecognizer(recognizer);
 }
reset()
void QGestureRecognizer::reset (QGesture * gesture) virtual
This function is called by the framework to reset a given gesture.
Reimplement this function to implement additional requirements for custom QGesture objects. This may be necessary if you implement a custom QGesture whose properties need special handling when the gesture is reset.
Reimplemented in QTapAndHoldGestureRecognizer, QFlickGestureRecognizer, QTapGestureRecognizer, QSwipeGestureRecognizer, QMacPinchGestureRecognizer, QPinchGestureRecognizer, QMacSwipeGestureRecognizer, QWinNativePanGestureRecognizer, and QPanGestureRecognizer.
Definition at line 191 of file qgesturerecognizer.cpp.
Referenced by QGestureManager::recycle(), QPanGestureRecognizer::reset(), QWinNativePanGestureRecognizer::reset(), QMacSwipeGestureRecognizer::reset(), QPinchGestureRecognizer::reset(), QMacPinchGestureRecognizer::reset(), QSwipeGestureRecognizer::reset(), QTapGestureRecognizer::reset(), and QTapAndHoldGestureRecognizer::reset().
 {
     if (gesture) {
         QGesturePrivate *d = gesture->d_func();
         d->state = Qt::NoGesture;
         d->hotSpot = QPointF();
         d->sceneHotSpot = QPointF();
         d->isHotSpotSet = false;
     }
 }
unregisterRecognizer()
void QGestureRecognizer::unregisterRecognizer (Qt::GestureType type) static
Unregisters all gesture recognizers of the specified type.
See also
registerRecognizer()
Definition at line 239 of file qgesturerecognizer.cpp.
 {
     QGestureManager::instance()->unregisterGestureRecognizer(type);
 }
The documentation for this class was generated from the following files:
/src/gui/kernel/qgesturerecognizer.h
/src/gui/kernel/qgesturerecognizer.cpp