Qt 4.8: QGraphicsDropShadowEffect Class Reference
QGraphicsDropShadowEffect Class Reference
The QGraphicsDropShadowEffect class provides a drop shadow effect.
#include <qgraphicseffect.h>
Public Slots
void setBlurRadius (qreal blurRadius)
void setColor (const QColor &color)
void setOffset (const QPointF &ofs)
void setOffset (qreal dx, qreal dy)
void setOffset (qreal d)
void setXOffset (qreal dx)
void setYOffset (qreal dy)
Public Slots inherited from QGraphicsEffect
void setEnabled (bool enable)
void update ()
Schedules a redraw of the effect.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void blurRadiusChanged (qreal blurRadius)
This signal is emitted whenever the effect's blur radius changes.
void colorChanged (const QColor &color)
This signal is emitted whenever the effect's color changes.
void offsetChanged (const QPointF &offset)
This signal is emitted whenever the effect's shadow offset changes.
Signals inherited from QGraphicsEffect
void enabledChanged (bool enabled)
This signal is emitted whenever the effect is enabled or disabled.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
qreal blurRadius () const
QRectF boundingRectFor (const QRectF &rect) const
Reimplemented Function
QColor color () const
QPointF offset () const
QGraphicsDropShadowEffect (QObject *parent=0)
Constructs a new QGraphicsDropShadowEffect instance.
qreal xOffset () const
qreal yOffset () const
~QGraphicsDropShadowEffect ()
Destroys the effect.
Public Functions inherited from QGraphicsEffect
QRectF boundingRect () const
Returns the effective bounding rectangle for this effect, i.e., the bounding rectangle of the source in device coordinates, adjusted by any margins applied by the effect itself.
bool isEnabled () const
QGraphicsEffect (QObject *parent=0)
Constructs a new QGraphicsEffect instance having the specified parent.
QGraphicsEffectSource * source () const
Returns a pointer to the source, which provides extra context information that can be useful for the effect.
virtual ~QGraphicsEffect ()
Removes the effect from the source, and destroys the graphics effect.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void draw (QPainter *painter)
Reimplemented Function
Protected Functions inherited from QGraphicsEffect
void drawSource (QPainter *painter)
Draws the source directly using the given painter.
QGraphicsEffect (QGraphicsEffectPrivate &d, QObject *parent=0)
QRectF sourceBoundingRect (Qt::CoordinateSystem system=Qt::LogicalCoordinates) const
Returns the bounding rectangle of the source mapped to the given system.
virtual void sourceChanged (ChangeFlags flags)
This virtual function is called by QGraphicsEffect to notify the effect that the source has changed.
bool sourceIsPixmap () const
Returns true if the source effectively is a pixmap, e.g., a QGraphicsPixmapItem.
QPixmap sourcePixmap (Qt::CoordinateSystem system=Qt::LogicalCoordinates, QPoint *offset=0, PixmapPadMode mode=PadToEffectiveBoundingRect) const
Returns a pixmap with the source painted into it.
void updateBoundingRect ()
This function notifies the effect framework when the effect's bounding rectangle has changed.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
qreal blurRadius
the blur radius in pixels of the drop shadow.
QColor color
the color of the drop shadow.
QPointF offset
the shadow offset in pixels.
qreal xOffset
the horizontal shadow offset in pixels.
qreal yOffset
the vertical shadow offset in pixels.
Additional Inherited Members
Public Types inherited from QGraphicsEffect
enum ChangeFlag { SourceAttached = 0x1, SourceDetached = 0x2, SourceBoundingRectChanged = 0x4, SourceInvalidated = 0x8 }
This enum describes what has changed in QGraphicsEffectSource.
enum PixmapPadMode { NoPad, PadToTransparentBorder, PadToEffectiveBoundingRect }
This enum describes how the pixmap returned from sourcePixmap should be padded.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGraphicsDropShadowEffect class provides a drop shadow effect.
Since
4.6
A drop shadow effect renders the source with a drop shadow. The color of the drop shadow can be modified using the setColor() function. The drop shadow offset can be modified using the setOffset() function and the blur radius of the drop shadow can be changed with the setBlurRadius() function.
By default, the drop shadow is a semi-transparent dark gray (QColor(63, 63, 63, 180)) shadow, blurred with a radius of 1 at an offset of 8 pixels towards the lower right. The drop shadow offset is specified in device coordinates.
See also
QGraphicsBlurEffect, QGraphicsColorizeEffect, QGraphicsOpacityEffect
Definition at line 199 of file qgraphicseffect.h.
Constructors and Destructors
QGraphicsDropShadowEffect()
QGraphicsDropShadowEffect::QGraphicsDropShadowEffect (QObject * parent = 0)
Constructs a new QGraphicsDropShadowEffect instance.
The parent parameter is passed to QGraphicsEffect's constructor.
Definition at line 957 of file qgraphicseffect.cpp.
     : QGraphicsEffect(*new QGraphicsDropShadowEffectPrivate, parent)
 {
 }
~QGraphicsDropShadowEffect()
QGraphicsDropShadowEffect::~QGraphicsDropShadowEffect ()
Destroys the effect.
Definition at line 965 of file qgraphicseffect.cpp.
 {
 }
Functions
blurRadius()
qreal QGraphicsDropShadowEffect::blurRadius () const
Referenced by setBlurRadius(), and setOffset().
blurRadiusChanged
void QGraphicsDropShadowEffect::blurRadiusChanged (qreal blurRadius) signal
This signal is emitted whenever the effect's blur radius changes.
The blurRadius parameter holds the effect's new blur radius.
Referenced by setBlurRadius().
boundingRectFor()
QRectF QGraphicsDropShadowEffect::boundingRectFor (const QRectF & rect) const virtual
Reimplemented Function
Reimplemented from QGraphicsEffect.
Definition at line 1119 of file qgraphicseffect.cpp.
 {
     Q_D(const QGraphicsDropShadowEffect);
     return d->filter->boundingRectFor(rect);
 }
color()
QColor QGraphicsDropShadowEffect::color () const
Referenced by setBlurRadius(), and setColor().
colorChanged
void QGraphicsDropShadowEffect::colorChanged (const QColor & color) signal
This signal is emitted whenever the effect's color changes.
The color parameter holds the effect's new color.
Referenced by setColor().
draw()
void QGraphicsDropShadowEffect::draw (QPainter * painter) protected virtual
Reimplemented Function
Implements QGraphicsEffect.
Definition at line 1128 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsDropShadowEffect);
     if (d->filter->blurRadius() <= 0 && d->filter->offset().isNull()) {
         drawSource(painter);
         return;
     }
     PixmapPadMode mode = PadToEffectiveBoundingRect;
     if (painter->paintEngine()->type() == QPaintEngine::OpenGL2)
         mode = NoPad;
     // Draw pixmap in device coordinates to avoid pixmap scaling.
     QPoint offset;
     const QPixmap pixmap = sourcePixmap(Qt::DeviceCoordinates, &offset, mode);
     if (pixmap.isNull())
         return;
     QTransform restoreTransform = painter->worldTransform();
     painter->setWorldTransform(QTransform());
     d->filter->draw(painter, offset, pixmap);
     painter->setWorldTransform(restoreTransform);
 }
offset()
QPointF QGraphicsDropShadowEffect::offset () const
Referenced by draw(), setOffset(), and ~QGraphicsDropShadowEffect().
offsetChanged
void QGraphicsDropShadowEffect::offsetChanged (const QPointF & offset) signal
This signal is emitted whenever the effect's shadow offset changes.
The offset parameter holds the effect's new shadow offset.
Referenced by setOffset().
setBlurRadius
void QGraphicsDropShadowEffect::setBlurRadius (qreal blurRadius) slot
Definition at line 1056 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsDropShadowEffect);
     if (qFuzzyCompare(d->filter->blurRadius(), blurRadius))
         return;
     d->filter->setBlurRadius(blurRadius);
     updateBoundingRect();
     emit blurRadiusChanged(blurRadius);
 }
setColor
void QGraphicsDropShadowEffect::setColor (const QColor & color) slot
Definition at line 1095 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsDropShadowEffect);
     if (d->filter->color() == color)
         return;
     d->filter->setColor(color);
     update();
     emit colorChanged(color);
 }
setOffset [1/3]
void QGraphicsDropShadowEffect::setOffset (const QPointF & ofs) slot
Definition at line 989 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsDropShadowEffect);
     if (d->filter->offset() == offset)
         return;
     d->filter->setOffset(offset);
     updateBoundingRect();
     emit offsetChanged(offset);
 }
setOffset [2/3]
void QGraphicsDropShadowEffect::setOffset (qreal dx, qreal dy) inline slot
Definition at line 226 of file qgraphicseffect.h.
     { setOffset(QPointF(dx, dy)); }
setOffset [3/3]
void QGraphicsDropShadowEffect::setOffset (qreal d) inline slot
Definition at line 229 of file qgraphicseffect.h.
     { setOffset(QPointF(d, d)); }
setXOffset
void QGraphicsDropShadowEffect::setXOffset (qreal dx) inline slot
Definition at line 232 of file qgraphicseffect.h.
     { setOffset(QPointF(dx, yOffset())); }
setYOffset
void QGraphicsDropShadowEffect::setYOffset (qreal dy) inline slot
Definition at line 235 of file qgraphicseffect.h.
     { setOffset(QPointF(xOffset(), dy)); }
xOffset()
qreal QGraphicsDropShadowEffect::xOffset () const inline
Definition at line 214 of file qgraphicseffect.h.
     { return offset().x(); }
yOffset()
qreal QGraphicsDropShadowEffect::yOffset () const inline
Definition at line 217 of file qgraphicseffect.h.
     { return offset().y(); }
Properties
blurRadius
qreal QGraphicsDropShadowEffect::blurRadius private
the blur radius in pixels of the drop shadow.
Using a smaller radius results in a sharper shadow, whereas using a bigger radius results in a more blurred shadow.
By default, the blur radius is 1 pixel.
See also
color(), offset().
Definition at line 205 of file qgraphicseffect.h.
color
QColor QGraphicsDropShadowEffect::color private
the color of the drop shadow.
By default, the drop color is a semi-transparent dark gray (QColor(63, 63, 63, 180)).
See also
offset(), blurRadius()
Definition at line 206 of file qgraphicseffect.h.
offset
QPointF QGraphicsDropShadowEffect::offset private
the shadow offset in pixels.
By default, the offset is 8 pixels towards the lower right.
The offset is given in device coordinates, which means it is unaffected by scale.
See also
xOffset(), yOffset(), blurRadius(), color()
Definition at line 202 of file qgraphicseffect.h.
xOffset
QGraphicsDropShadowEffect::xOffset private
the horizontal shadow offset in pixels.
By default, the horizontal shadow offset is 8 pixels.
See also
yOffset(), offset()
Definition at line 203 of file qgraphicseffect.h.
yOffset
QGraphicsDropShadowEffect::yOffset private
the vertical shadow offset in pixels.
By default, the vertical shadow offset is 8 pixels.
See also
xOffset(), offset()
Definition at line 204 of file qgraphicseffect.h.
The documentation for this class was generated from the following files:
/src/gui/effects/qgraphicseffect.h
/src/gui/effects/qgraphicseffect.cpp