Qt 4.8: QNetworkAccessCache::CacheableObject Class Reference
QNetworkAccessCache::CacheableObject Class Reference abstract
#include <qnetworkaccesscache_p.h>
Public Functions
CacheableObject ()
QByteArray cacheKey () const
virtual void dispose ()=0
virtual ~CacheableObject ()
Protected Functions
void setExpires (bool enable)
void setShareable (bool enable)
Properties
bool expires
QByteArray key
bool shareable
Friends
class QNetworkAccessCache
Detailed Description
Definition at line 77 of file qnetworkaccesscache_p.h.
Constructors and Destructors
CacheableObject()
QNetworkAccessCache::CacheableObject::CacheableObject ()
Definition at line 81 of file qnetworkaccesscache.cpp.
 {
     // leave the members uninitialized
     // they must be initialized by the derived class's constructor
 }
~CacheableObject()
QNetworkAccessCache::CacheableObject::~CacheableObject () virtual
Definition at line 87 of file qnetworkaccesscache.cpp.
 {
 #if 0 //def QT_DEBUG
     if (!key.isEmpty() && Ptr()->hasEntry(key))
         qWarning() << "QNetworkAccessCache: object" << (void*)this << "key" << key
                    << "destroyed without being removed from cache first!";
 #endif
 }
Functions
cacheKey()
QByteArray QNetworkAccessCache::CacheableObject::cacheKey () const inline
Definition at line 87 of file qnetworkaccesscache_p.h.
Referenced by QNetworkAccessAuthenticationManager::cacheCredentials(), QNetworkAccessAuthenticationManager::cacheProxyCredentials(), QNetworkAccessAuthenticationManager::fetchCachedCredentials(), QNetworkAccessAuthenticationManager::fetchCachedProxyCredentials(), and QHttpThreadDelegate::~QHttpThreadDelegate().
 { return key; }
dispose()
virtual void QNetworkAccessCache::CacheableObject::dispose () pure virtual
Implemented in QNetworkAccessCachedHttpConnection, QNetworkAuthenticationCache, and QNetworkAccessCachedFtpConnection.
Referenced by QNetworkAccessCache::addEntry(), and QNetworkAccessCache::timerEvent().
setExpires()
void QNetworkAccessCache::CacheableObject::setExpires (bool enable) protected
Definition at line 96 of file qnetworkaccesscache.cpp.
Referenced by cacheKey(), QNetworkAccessCachedHttpConnection::QNetworkAccessCachedHttpConnection(), and QNetworkAuthenticationCache::QNetworkAuthenticationCache().
 {
     expires = enable;
 }
setShareable()
void QNetworkAccessCache::CacheableObject::setShareable (bool enable) protected
Definition at line 101 of file qnetworkaccesscache.cpp.
Referenced by cacheKey(), QNetworkAccessCachedHttpConnection::QNetworkAccessCachedHttpConnection(), and QNetworkAuthenticationCache::QNetworkAuthenticationCache().
 {
     shareable = enable;
 }
Friends and Related Functions
QNetworkAccessCache
friend class QNetworkAccessCache friend
Definition at line 79 of file qnetworkaccesscache_p.h.
Referenced by cacheKey().
Properties
expires
bool QNetworkAccessCache::CacheableObject::expires private
Definition at line 81 of file qnetworkaccesscache_p.h.
Referenced by QNetworkAccessCache::releaseEntry().
key
QByteArray QNetworkAccessCache::CacheableObject::key private
Definition at line 80 of file qnetworkaccesscache_p.h.
Referenced by QNetworkAccessCache::addEntry(), cacheKey(), proxyAuthenticationKey(), and QNetworkAccessCache::removeEntry().
shareable
bool QNetworkAccessCache::CacheableObject::shareable private
Definition at line 82 of file qnetworkaccesscache_p.h.
Referenced by QNetworkAccessCache::requestEntry().
The documentation for this class was generated from the following files:
/src/network/access/qnetworkaccesscache_p.h
/src/network/access/qnetworkaccesscache.cpp