Qt 4.8: QGraphicsSceneMouseEvent Class Reference
QGraphicsSceneMouseEvent Class Reference
The QGraphicsSceneMouseEvent class provides mouse events in the graphics view framework.
#include <qgraphicssceneevent.h>
Public Functions
Qt::MouseButton button () const
Returns the mouse button (if any) that caused the event.
QPointF buttonDownPos (Qt::MouseButton button) const
Returns the mouse cursor position in item coordinates where the specified button was clicked.
QPointF buttonDownScenePos (Qt::MouseButton button) const
Returns the mouse cursor position in scene coordinates where the specified button was clicked.
QPoint buttonDownScreenPos (Qt::MouseButton button) const
Returns the mouse cursor position in screen coordinates where the specified button was clicked.
Qt::MouseButtons buttons () const
Returns the combination of mouse buttons that were pressed at the time the event was sent.
QPointF lastPos () const
Returns the last recorded mouse cursor position in item coordinates.
QPointF lastScenePos () const
Returns the last recorded mouse cursor position in scene coordinates.
QPoint lastScreenPos () const
Returns the last recorded mouse cursor position in screen coordinates.
Qt::KeyboardModifiers modifiers () const
Returns the keyboard modifiers in use at the time the event was sent.
QPointF pos () const
Returns the mouse cursor position in item coordinates.
QGraphicsSceneMouseEvent (Type type=None)
Constructs a generic graphics scene mouse event of the specified type.
QPointF scenePos () const
Returns the mouse cursor position in scene coordinates.
QPoint screenPos () const
Returns the mouse cursor position in screen coordinates.
void setButton (Qt::MouseButton button)
void setButtonDownPos (Qt::MouseButton button, const QPointF &pos)
void setButtonDownScenePos (Qt::MouseButton button, const QPointF &pos)
void setButtonDownScreenPos (Qt::MouseButton button, const QPoint &pos)
void setButtons (Qt::MouseButtons buttons)
void setLastPos (const QPointF &pos)
void setLastScenePos (const QPointF &pos)
void setLastScreenPos (const QPoint &pos)
void setModifiers (Qt::KeyboardModifiers modifiers)
void setPos (const QPointF &pos)
void setScenePos (const QPointF &pos)
void setScreenPos (const QPoint &pos)
~QGraphicsSceneMouseEvent ()
Destroys the event.
Public Functions inherited from QGraphicsSceneEvent
QGraphicsSceneEvent (Type type)
Constructs a generic graphics scene event of the specified type.
void setWidget (QWidget *widget)
Sets the widget related to this event.
QWidget * widget () const
Returns the widget where the event originated, or 0 if the event originates from another application.
~QGraphicsSceneEvent ()
Destroys the event.
Public Functions inherited from QEvent
void accept ()
Sets the accept flag of the event object, the equivalent of calling setAccepted(true).
void ignore ()
Clears the accept flag parameter of the event object, the equivalent of calling setAccepted(false).
bool isAccepted () const
QEvent (Type type)
Contructs an event object of type type.
void setAccepted (bool accepted)
bool spontaneous () const
Returns true if the event originated outside the application (a system event); otherwise returns false.
Type type () const
Returns the event type.
virtual ~QEvent ()
Destroys the event.
Additional Inherited Members
Public Types inherited from QEvent
enum Type {
None = 0, Timer = 1, MouseButtonPress = 2, MouseButtonRelease = 3,
MouseButtonDblClick = 4, MouseMove = 5, KeyPress = 6, KeyRelease = 7,
FocusIn = 8, FocusOut = 9, Enter = 10, Leave = 11,
Paint = 12, Move = 13, Resize = 14, Create = 15,
Destroy = 16, Show = 17, Hide = 18, Close = 19,
Quit = 20, ParentChange = 21, ParentAboutToChange = 131, ThreadChange = 22,
WindowActivate = 24, WindowDeactivate = 25, ShowToParent = 26, HideToParent = 27,
Wheel = 31, WindowTitleChange = 33, WindowIconChange = 34, ApplicationWindowIconChange = 35,
ApplicationFontChange = 36, ApplicationLayoutDirectionChange = 37, ApplicationPaletteChange = 38, PaletteChange = 39,
Clipboard = 40, Speech = 42, MetaCall = 43, SockAct = 50,
WinEventAct = 132, DeferredDelete = 52, DragEnter = 60, DragMove = 61,
DragLeave = 62, Drop = 63, DragResponse = 64, ChildAdded = 68,
ChildPolished = 69, ChildRemoved = 71, ShowWindowRequest = 73, PolishRequest = 74,
Polish = 75, LayoutRequest = 76, UpdateRequest = 77, UpdateLater = 78,
EmbeddingControl = 79, ActivateControl = 80, DeactivateControl = 81, ContextMenu = 82,
InputMethod = 83, AccessibilityPrepare = 86, TabletMove = 87, LocaleChange = 88,
LanguageChange = 89, LayoutDirectionChange = 90, Style = 91, TabletPress = 92,
TabletRelease = 93, OkRequest = 94, HelpRequest = 95, IconDrag = 96,
FontChange = 97, EnabledChange = 98, ActivationChange = 99, StyleChange = 100,
IconTextChange = 101, ModifiedChange = 102, MouseTrackingChange = 109, WindowBlocked = 103,
WindowUnblocked = 104, WindowStateChange = 105, ToolTip = 110, WhatsThis = 111,
StatusTip = 112, ActionChanged = 113, ActionAdded = 114, ActionRemoved = 115,
FileOpen = 116, Shortcut = 117, ShortcutOverride = 51, WhatsThisClicked = 118,
ToolBarChange = 120, ApplicationActivate = 121, ApplicationActivated = ApplicationActivate, ApplicationDeactivate = 122,
ApplicationDeactivated = ApplicationDeactivate, QueryWhatsThis = 123, EnterWhatsThisMode = 124, LeaveWhatsThisMode = 125,
ZOrderChange = 126, HoverEnter = 127, HoverLeave = 128, HoverMove = 129,
AccessibilityHelp = 119, AccessibilityDescription = 130, AcceptDropsChange = 152, MenubarUpdated = 153,
ZeroTimerEvent = 154, GraphicsSceneMouseMove = 155, GraphicsSceneMousePress = 156, GraphicsSceneMouseRelease = 157,
GraphicsSceneMouseDoubleClick = 158, GraphicsSceneContextMenu = 159, GraphicsSceneHoverEnter = 160, GraphicsSceneHoverMove = 161,
GraphicsSceneHoverLeave = 162, GraphicsSceneHelp = 163, GraphicsSceneDragEnter = 164, GraphicsSceneDragMove = 165,
GraphicsSceneDragLeave = 166, GraphicsSceneDrop = 167, GraphicsSceneWheel = 168, KeyboardLayoutChange = 169,
DynamicPropertyChange = 170, TabletEnterProximity = 171, TabletLeaveProximity = 172, NonClientAreaMouseMove = 173,
NonClientAreaMouseButtonPress = 174, NonClientAreaMouseButtonRelease = 175, NonClientAreaMouseButtonDblClick = 176, MacSizeChange = 177,
ContentsRectChange = 178, MacGLWindowChange = 179, FutureCallOut = 180, GraphicsSceneResize = 181,
GraphicsSceneMove = 182, CursorChange = 183, ToolTipChange = 184, NetworkReplyUpdated = 185,
GrabMouse = 186, UngrabMouse = 187, GrabKeyboard = 188, UngrabKeyboard = 189,
MacGLClearDrawable = 191, StateMachineSignal = 192, StateMachineWrapped = 193, TouchBegin = 194,
TouchUpdate = 195, TouchEnd = 196, NativeGesture = 197, RequestSoftwareInputPanel = 199,
CloseSoftwareInputPanel = 200, UpdateSoftKeys = 201, WinIdChange = 203, Gesture = 198,
GestureOverride = 202, PlatformPanel = 212, User = 1000, MaxUser = 65535
}
This enum type defines the valid event types in Qt.
Static Public Functions inherited from QEvent
static int registerEventType (int hint=-1)
Registers and returns a custom event type.
Protected Functions inherited from QGraphicsSceneEvent
QGraphicsSceneEvent (QGraphicsSceneEventPrivate &dd, Type type=None)
Constructs a generic graphics scene event.
Protected Variables inherited from QGraphicsSceneEvent
QScopedPointer< QGraphicsSceneEventPrivate > d_ptr
Protected Variables inherited from QEvent
QEventPrivate * d
ushort t
Detailed Description
The QGraphicsSceneMouseEvent class provides mouse events in the graphics view framework.
Since
4.2
When a QGraphicsView receives a QMouseEvent, it translates it to a QGraphicsSceneMouseEvent. The event is then forwarded to the QGraphicsScene associated with the view. If the event is not handled by the scene, the view may use it, e.g., for the QGraphicsView::DragMode.
In addition to containing the item, scene, and screen coordinates of the event (as pos(), scenePos(), and screenPos()), mouse events also contain the coordinates of the previous mouse event received by the view. These can be retrieved with lastPos(), lastScreenPos(), and lastScenePos().
See also
QGraphicsSceneContextMenuEvent, QGraphicsSceneHoverEvent, QGraphicsSceneWheelEvent, QMouseEvent
Definition at line 85 of file qgraphicssceneevent.h.
Constructors and Destructors
QGraphicsSceneMouseEvent()
QGraphicsSceneMouseEvent::QGraphicsSceneMouseEvent (Type type = None)
Constructs a generic graphics scene mouse event of the specified type.
Warning
This function is not part of the public interface.
Definition at line 406 of file qgraphicssceneevent.cpp.
     : QGraphicsSceneEvent(*new QGraphicsSceneMouseEventPrivate, type)
 {
 }
~QGraphicsSceneMouseEvent()
QGraphicsSceneMouseEvent::~QGraphicsSceneMouseEvent ()
Destroys the event.
Definition at line 414 of file qgraphicssceneevent.cpp.
 {
 }
Functions
button()
Qt::MouseButton QGraphicsSceneMouseEvent::button () const
Returns the mouse button (if any) that caused the event.
See also
buttons(), modifiers()
Definition at line 634 of file qgraphicssceneevent.cpp.
Referenced by QDeclarativeFlickablePrivate::captureDelayedPress(), cloneEvent(), QGraphicsItem::mousePressEvent(), QGraphicsScenePrivate::mousePressEventHandler(), QDeclarativeTextInput::mouseReleaseEvent(), QDeclarativeTextEdit::mouseReleaseEvent(), QGraphicsItem::mouseReleaseEvent(), QGraphicsTextItem::mouseReleaseEvent(), QTextControl::processEvent(), QLineControl::processEvent(), QGraphicsScenePrivate::sendMouseEvent(), QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent(), setButton(), and QGraphicsWidgetPrivate::windowFrameMousePressEvent().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->button;
 }
buttonDownPos()
QPointF QGraphicsSceneMouseEvent::buttonDownPos (Qt::MouseButton button) const
Returns the mouse cursor position in item coordinates where the specified button was clicked.
See also
buttonDownScenePos(), buttonDownScreenPos(), pos()
Definition at line 484 of file qgraphicssceneevent.cpp.
Referenced by QDeclarativeFlickablePrivate::captureDelayedPress(), cloneEvent(), QGraphicsItemPrivate::remapItemPos(), QDeclarativePathView::sendMouseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativeFlickable::sendMouseEvent(), and QDeclarativePinchArea::sendMouseEvent().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->buttonDownPos.value(button);
 }
buttonDownScenePos()
QPointF QGraphicsSceneMouseEvent::buttonDownScenePos (Qt::MouseButton button) const
Returns the mouse cursor position in scene coordinates where the specified button was clicked.
See also
buttonDownPos(), buttonDownScreenPos(), scenePos()
Definition at line 505 of file qgraphicssceneevent.cpp.
Referenced by QDeclarativeFlickablePrivate::captureDelayedPress(), QGraphicsItem::mouseMoveEvent(), and QGraphicsWidgetPrivate::windowFrameMouseMoveEvent().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->buttonDownScenePos.value(button);
 }
buttonDownScreenPos()
QPoint QGraphicsSceneMouseEvent::buttonDownScreenPos (Qt::MouseButton button) const
Returns the mouse cursor position in screen coordinates where the specified button was clicked.
See also
screenPos(), buttonDownPos(), buttonDownScenePos()
Definition at line 526 of file qgraphicssceneevent.cpp.
Referenced by QDeclarativeFlickablePrivate::captureDelayedPress(), cloneEvent(), and QGraphicsItem::mouseMoveEvent().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->buttonDownScreenPos.value(button);
 }
buttons()
Qt::MouseButtons QGraphicsSceneMouseEvent::buttons () const
Returns the combination of mouse buttons that were pressed at the time the event was sent.
See also
button(), modifiers()
Definition at line 614 of file qgraphicssceneevent.cpp.
Referenced by QDeclarativeFlickablePrivate::captureDelayedPress(), cloneEvent(), QGraphicsScene::mouseMoveEvent(), QGraphicsItem::mouseMoveEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsTextItem::mousePressEvent(), QGraphicsView::mouseReleaseEvent(), QGraphicsScene::mouseReleaseEvent(), QGraphicsItem::mouseReleaseEvent(), QGraphicsTextItem::mouseReleaseEvent(), QTextControl::processEvent(), QLineControl::processEvent(), QGraphicsItemPrivate::remapItemPos(), QDeclarativePathView::sendMouseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativeFlickable::sendMouseEvent(), QGraphicsScenePrivate::sendMouseEvent(), QDeclarativePinchArea::sendMouseEvent(), QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent(), setButtons(), QGraphicsScenePrivate::storeMouseButtonsForMouseGrabber(), and QGraphicsWidgetPrivate::windowFrameMouseMoveEvent().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->buttons;
 }
lastPos()
QPointF QGraphicsSceneMouseEvent::lastPos () const
Returns the last recorded mouse cursor position in item coordinates.
See also
lastScenePos(), lastScreenPos(), pos()
Definition at line 547 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), QDeclarativeFlickablePrivate::captureDelayedPress(), and cloneEvent().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->lastPos;
 }
lastScenePos()
QPointF QGraphicsSceneMouseEvent::lastScenePos () const
Returns the last recorded mouse cursor position in scene coordinates.
The last recorded position is the position of the previous mouse event received by the view that created the event.
See also
lastPos(), lastScreenPos(), scenePos()
Definition at line 570 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), QDeclarativeFlickablePrivate::captureDelayedPress(), cloneEvent(), QDeclarativePathView::sendMouseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativeFlickable::sendMouseEvent(), QGraphicsScenePrivate::sendMouseEvent(), and QDeclarativePinchArea::sendMouseEvent().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->lastScenePos;
 }
lastScreenPos()
QPoint QGraphicsSceneMouseEvent::lastScreenPos () const
Returns the last recorded mouse cursor position in screen coordinates.
The last recorded position is the position of the previous mouse event received by the view that created the event.
See also
lastPos(), lastScenePos(), screenPos()
Definition at line 593 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), QDeclarativeFlickablePrivate::captureDelayedPress(), and cloneEvent().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->lastScreenPos;
 }
modifiers()
Qt::KeyboardModifiers QGraphicsSceneMouseEvent::modifiers () const
Returns the keyboard modifiers in use at the time the event was sent.
See also
buttons(), button()
Definition at line 655 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), QDeclarativeFlickablePrivate::captureDelayedPress(), cloneEvent(), QTextControl::processEvent(), QLineControl::processEvent(), and setModifiers().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->modifiers;
 }
pos()
QPointF QGraphicsSceneMouseEvent::pos () const
Returns the mouse cursor position in item coordinates.
See also
scenePos(), screenPos(), lastPos()
Definition at line 423 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), QGraphicsTextItemPrivate::_q_mouseOnEdge(), QDeclarativeFlickablePrivate::captureDelayedPress(), cloneEvent(), QDeclarativePathViewPrivate::handleMouseMoveEvent(), QDeclarativeFlickablePrivate::handleMouseMoveEvent(), QDeclarativePathViewPrivate::handleMousePressEvent(), QDeclarativeFlickablePrivate::handleMouseReleaseEvent(), QDeclarativeTextInput::mouseDoubleClickEvent(), QDeclarativeTextInput::mouseMoveEvent(), QDeclarativeText::mousePressEvent(), QDeclarativeTextInput::mousePressEvent(), QGraphicsItem::mousePressEvent(), QDeclarativeText::mouseReleaseEvent(), QDeclarativeTextInput::mouseReleaseEvent(), QDeclarativeTextEdit::mouseReleaseEvent(), QGraphicsTextItem::mouseReleaseEvent(), QTextControl::processEvent(), QLineControl::processEvent(), QGraphicsItemPrivate::remapItemPos(), QDeclarativeTextInputPrivate::sendMouseEventToInputContext(), QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent(), setLastPos(), setLastScenePos(), setLastScreenPos(), setPos(), setScenePos(), setScreenPos(), QGraphicsWidgetPrivate::windowFrameMouseMoveEvent(), and QGraphicsWidgetPrivate::windowFrameMousePressEvent().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->pos;
 }
scenePos()
QPointF QGraphicsSceneMouseEvent::scenePos () const
Returns the mouse cursor position in scene coordinates.
See also
pos(), screenPos(), lastScenePos()
Definition at line 443 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), QDeclarativeFlickablePrivate::captureDelayedPress(), cloneEvent(), QGraphicsScene::event(), QDeclarativeMouseArea::mouseMoveEvent(), QGraphicsItem::mouseMoveEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsScenePrivate::mousePressEventHandler(), QGraphicsItem::mouseReleaseEvent(), QDeclarativePathView::sendMouseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativeFlickable::sendMouseEvent(), QGraphicsScenePrivate::sendMouseEvent(), QDeclarativePinchArea::sendMouseEvent(), and QGraphicsScenePrivate::storeMouseButtonsForMouseGrabber().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->scenePos;
 }
screenPos()
QPoint QGraphicsSceneMouseEvent::screenPos () const
Returns the mouse cursor position in screen coordinates.
See also
pos(), scenePos(), lastScreenPos()
Definition at line 463 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), QDeclarativeFlickablePrivate::captureDelayedPress(), cloneEvent(), QGraphicsItem::mouseMoveEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsScenePrivate::mousePressEventHandler(), QTextControl::processEvent(), QTapAndHoldGestureRecognizer::recognize(), QGraphicsScenePrivate::sendMouseEvent(), QDeclarativeTextInputPrivate::sendMouseEventToInputContext(), and QGraphicsScenePrivate::storeMouseButtonsForMouseGrabber().
 {
     Q_D(const QGraphicsSceneMouseEvent);
     return d->screenPos;
 }
setButton()
void QGraphicsSceneMouseEvent::setButton (Qt::MouseButton button)
Warning
This function is not part of the public interface.
Definition at line 643 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsView::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsView::mousePressEvent(), QGraphicsView::mouseReleaseEvent(), and QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->button = button;
 }
setButtonDownPos()
void QGraphicsSceneMouseEvent::setButtonDownPos (Qt::MouseButton button, const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 493 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsItemPrivate::remapItemPos(), and QGraphicsScenePrivate::sendMouseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->buttonDownPos.insert(button, pos);
 }
setButtonDownScenePos()
void QGraphicsSceneMouseEvent::setButtonDownScenePos (Qt::MouseButton button, const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 514 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsView::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsView::mousePressEvent(), QGraphicsView::mouseReleaseEvent(), and QGraphicsScenePrivate::sendMouseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->buttonDownScenePos.insert(button, pos);
 }
setButtonDownScreenPos()
void QGraphicsSceneMouseEvent::setButtonDownScreenPos (Qt::MouseButton button, const QPoint & pos)
Warning
This function is not part of the public interface.
Definition at line 535 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsView::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsView::mousePressEvent(), QGraphicsView::mouseReleaseEvent(), and QGraphicsScenePrivate::sendMouseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->buttonDownScreenPos.insert(button, pos);
 }
setButtons()
void QGraphicsSceneMouseEvent::setButtons (Qt::MouseButtons buttons)
Warning
This function is not part of the public interface.
Definition at line 623 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsView::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsView::mousePressEvent(), QGraphicsView::mouseReleaseEvent(), and QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->buttons = buttons;
 }
setLastPos()
void QGraphicsSceneMouseEvent::setLastPos (const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 556 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsItemPrivate::remapItemPos(), and QGraphicsScenePrivate::sendMouseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->lastPos = pos;
 }
setLastScenePos()
void QGraphicsSceneMouseEvent::setLastScenePos (const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 579 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsView::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsView::mousePressEvent(), and QGraphicsView::mouseReleaseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->lastScenePos = pos;
 }
setLastScreenPos()
void QGraphicsSceneMouseEvent::setLastScreenPos (const QPoint & pos)
Warning
This function is not part of the public interface.
Definition at line 602 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsView::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsView::mousePressEvent(), and QGraphicsView::mouseReleaseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->lastScreenPos = pos;
 }
setModifiers()
void QGraphicsSceneMouseEvent::setModifiers (Qt::KeyboardModifiers modifiers)
Warning
This function is not part of the public interface.
Definition at line 664 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsView::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsView::mousePressEvent(), QGraphicsView::mouseReleaseEvent(), and QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->modifiers = modifiers;
 }
setPos()
void QGraphicsSceneMouseEvent::setPos (const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 432 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsItemPrivate::remapItemPos(), QGraphicsScenePrivate::sendMouseEvent(), and QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->pos = pos;
 }
setScenePos()
void QGraphicsSceneMouseEvent::setScenePos (const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 452 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsView::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsView::mousePressEvent(), and QGraphicsView::mouseReleaseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->scenePos = pos;
 }
setScreenPos()
void QGraphicsSceneMouseEvent::setScreenPos (const QPoint & pos)
Warning
This function is not part of the public interface.
Definition at line 472 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsView::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsView::mousePressEvent(), QGraphicsView::mouseReleaseEvent(), and QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent().
 {
     Q_D(QGraphicsSceneMouseEvent);
     d->screenPos = pos;
 }
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicssceneevent.h
/src/gui/graphicsview/qgraphicssceneevent.cpp