Qt 4.8: QWSMouseHandler Class Reference
QWSMouseHandler Class Reference abstract
The QWSMouseHandler class is a base class for mouse drivers in Qt for Embedded Linux.
#include <qmouse_qws.h>
Public Functions
virtual void calibrate (const QWSPointerCalibrationData *)
This virtual function allows subclasses of QWSMouseHandler to set the calibration information passed in the given data.
virtual void clearCalibration ()
This virtual function allows subclasses of QWSMouseHandler to clear the calibration information.
virtual void getCalibration (QWSPointerCalibrationData *) const
This virtual function allows subclasses of QWSMouseHandler to fill in the device coordinates in data with values that correspond to screen coordinates that are already in data.
void limitToScreen (QPoint &pt)
Ensures that the given position is within the screen's boundaries, changing the position if necessary.
void mouseChanged (const QPoint &pos, int bstate, int wheel=0)
Notifies the system of a new mouse event.
const QPoint & pos () const
Returns the current mouse position.
QWSMouseHandler (const QString &driver=QString(), const QString &device=QString())
Constructs a mouse driver.
virtual void resume ()=0
Implement this function to resume reading and handling mouse events, e.
void setScreen (const QScreen *screen)
Sets the screen for this mouse driver to be the given screen.
virtual void suspend ()=0
Implement this function to suspend reading and handling of mouse events, e.
virtual ~QWSMouseHandler ()
Destroys this mouse driver.
Protected Variables
QWSMouseHandlerPrivate * d_ptr
QPoint & mousePos
Detailed Description
The QWSMouseHandler class is a base class for mouse drivers in Qt for Embedded Linux.
Note that this class is only available in Qt for Embedded Linux.
Qt for Embedded Linux provides ready-made drivers for several mouse protocols, see the Qt for Embedded Linux Pointer Handling{pointer handling} documentation for details. Custom mouse drivers can be implemented by subclassing the QWSMouseHandler class and creating a mouse driver plugin (derived from QMouseDriverPlugin). The default implementation of the QMouseDriverFactory class will automatically detect the plugin, and load the driver into the server application at run-time using Qt's How to Create Qt Plugins.
The mouse driver receives mouse events from the system device and encapsulates each event with an instance of the QWSEvent class which it then passes to the server application (the server is responsible for propagating the event to the appropriate client). To receive mouse events, a QWSMouseHandler object will usually create a QSocketNotifier object for the given device. The QSocketNotifier class provides support for monitoring activity on a file descriptor. When the socket notifier receives data, it will call the mouse driver's mouseChanged() function to send the event to the Qt for Embedded Linux server application for relaying to clients.
If you are creating a driver for a device that needs calibration or noise reduction, such as a touchscreen, use the QWSCalibratedMouseHandler subclass instead to take advantage of the calibrate() and clearCalibration() functions. The Mouse Calibration demonstrates how to write a simple program using the mechanisms provided by the QWSMouseHandler class to calibrate a mouse driver.
Note that when deriving from the QWSMouseHandler class, the resume() and suspend() functions must be reimplemented to control the flow of mouse input, i.e., the default implementation does nothing. Reimplementations of these functions typically call the QSocketNotifier::setEnabled() function to enable or disable the socket notifier, respectively.
In addition, QWSMouseHandler provides the setScreen() function that allows you to specify a screen for your mouse driver and the limitToScreen() function that ensures that a given position is within this screen's boundaries (changing the position if necessary). Finally, QWSMouseHandler provides the pos() function returning the current mouse position.
See also
QMouseDriverPlugin, QMouseDriverFactory, {Qt for Embedded Linux Pointer Handling}
Definition at line 66 of file qmouse_qws.h.
Constructors and Destructors
QWSMouseHandler()
QWSMouseHandler::QWSMouseHandler (const QString & driver = QString(), const QString & device = QString()) explicit
Constructs a mouse driver.
The driver and device arguments are passed by the QWS_MOUSE_PROTO environment variable.
Call the QWSServer::setMouseHandler() function to make the newly created mouse driver, the primary driver. Note that the primary driver is controlled by the system, i.e., the system will delete it upon exit.
Definition at line 223 of file qmouse_qws.cpp.
     : mousePos(QWSServer::mousePosition), d_ptr(new QWSMouseHandlerPrivate)
 {
 }
~QWSMouseHandler()
QWSMouseHandler::~QWSMouseHandler () virtual
Destroys this mouse driver.
Do not call this function if this driver is the primary mouse driver, i.e., if QWSServer::setMouseHandler() function has been called passing this driver as argument. The primary mouse driver is deleted by the system.
Definition at line 236 of file qmouse_qws.cpp.
 {
     delete d_ptr;
 }
Functions
calibrate()
QWSMouseHandler::calibrate (const QWSPointerCalibrationData * data) inline virtual
This virtual function allows subclasses of QWSMouseHandler to set the calibration information passed in the given data.
Note that the default implementation does nothing.
See also
QWSCalibratedMouseHandler::calibrate(), clearCalibration()
Reimplemented in QWSCalibratedMouseHandler, QIntMouseHandler, and QWSTslibMouseHandler.
Definition at line 74 of file qmouse_qws.h.
 {}
clearCalibration()
QWSMouseHandler::clearCalibration () inline virtual
This virtual function allows subclasses of QWSMouseHandler to clear the calibration information.
Note that the default implementation does nothing.
See also
QWSCalibratedMouseHandler::clearCalibration(), calibrate()
Reimplemented in QWSCalibratedMouseHandler, QIntMouseHandler, and QWSTslibMouseHandler.
Definition at line 73 of file qmouse_qws.h.
 {}
getCalibration()
QWSMouseHandler::getCalibration (QWSPointerCalibrationData * data) const inline virtual
This virtual function allows subclasses of QWSMouseHandler to fill in the device coordinates in data with values that correspond to screen coordinates that are already in data.
Note that the default implementation does nothing.
Reimplemented in QWSCalibratedMouseHandler.
Definition at line 75 of file qmouse_qws.h.
 {}
limitToScreen()
void QWSMouseHandler::limitToScreen (QPoint & position)
Ensures that the given position is within the screen's boundaries, changing the position if necessary.
See also
pos(), setScreen()
Definition at line 248 of file qmouse_qws.cpp.
Referenced by QWSLinuxInputMousePrivate::readMouseData(), QIntMouseHandler::readMouseData(), QDirectFBMouseHandlerPrivate::readMouseData(), QWSPcMouseHandlerPrivate::sendEvent(), and QQnxMouseHandler::socketActivated().
 {
     position.setX(qMin(d_ptr->screen->deviceWidth() - 1, qMax(0, position.x())));
     position.setY(qMin(d_ptr->screen->deviceHeight() - 1, qMax(0, position.y())));
 }
mouseChanged()
void QWSMouseHandler::mouseChanged (const QPoint & position, int state, int wheel = 0)
Notifies the system of a new mouse event.
This function updates the current mouse position and sends the event to the Qt for Embedded Linux server application for delivery to the correct widget. Note that a custom mouse driver must call this function whenever it wants to deliver a new mouse event.
The given position is the global position of the mouse cursor. The state parameter is a bitmask of the Qt::MouseButton enum's values, indicating which mouse buttons are pressed. The wheel parameter is the delta value of the mouse wheel as returned by QWheelEvent::delta().
See also
pos()
Definition at line 285 of file qmouse_qws.cpp.
Referenced by QWSLinuxInputMousePrivate::readMouseData(), QIntMouseHandler::readMouseData(), QVFbMouseHandler::readMouseData(), QDirectFBMouseHandlerPrivate::readMouseData(), QWSLinuxTPMouseHandlerPrivate::readMouseData(), QWSPcMouseHandlerPrivate::sendEvent(), QWSCalibratedMouseHandler::sendFiltered(), and QQnxMouseHandler::socketActivated().
 {
     mousePos = position + d_ptr->screen->offset();
     QWSServer::sendMouseEvent(mousePos, state, wheel);
 }
pos()
const QPoint & QWSMouseHandler::pos () const inline
Returns the current mouse position.
See also
mouseChanged(), limitToScreen()
Definition at line 82 of file qmouse_qws.h.
Referenced by QIntMouseHandler::readMouseData(), QWSPcMouseHandlerPrivate::sendEvent(), and QWSCalibratedMouseHandler::sendFiltered().
 { return mousePos; }
resume()
void QWSMouseHandler::resume () pure virtual
Implement this function to resume reading and handling mouse events, e.
g., call the QSocketNotifier::setEnabled() function to enable the socket notifier.
See also
suspend()
Implemented in QWSLinuxTPMouseHandler, QDirectFBMouseHandler, QIntMouseHandler, QWSPcMouseHandler, QWSTslibMouseHandler, QWSLinuxInputMouseHandler, QQnxMouseHandler, and QVFbMouseHandler.
setScreen()
void QWSMouseHandler::setScreen (const QScreen * screen)
Sets the screen for this mouse driver to be the given screen.
Since
4.2
See also
limitToScreen()
Definition at line 264 of file qmouse_qws.cpp.
Referenced by QVFbScreen::initDevice(), and QWSServerPrivate::newMouseHandler().
 {
     d_ptr->screen = (screen ? screen : qt_screen);
 }
suspend()
void QWSMouseHandler::suspend () pure virtual
Implement this function to suspend reading and handling of mouse events, e.
g., call the QSocketNotifier::setEnabled() function to disable the socket notifier.
See also
resume()
Implemented in QIntMouseHandler, QWSLinuxTPMouseHandler, QQnxMouseHandler, QVFbMouseHandler, QDirectFBMouseHandler, QWSPcMouseHandler, QWSTslibMouseHandler, and QWSLinuxInputMouseHandler.
Properties
d_ptr
QWSMouseHandlerPrivate* QWSMouseHandler::d_ptr protected
Definition at line 88 of file qmouse_qws.h.
Referenced by limitToScreen(), mouseChanged(), setScreen(), and ~QWSMouseHandler().
mousePos
QPoint& QWSMouseHandler::mousePos protected
Definition at line 87 of file qmouse_qws.h.
Referenced by mouseChanged(), QVFbMouseHandler::readMouseData(), QWSCalibratedMouseHandler::sendFiltered(), and QQnxMouseHandler::socketActivated().
The documentation for this class was generated from the following files:
/src/gui/embedded/qmouse_qws.h
/src/gui/embedded/qmouse_qws.cpp