Qt 4.8: QXlibKeyboard Class Reference
QXlibKeyboard Class Reference
#include <qxlibkeyboard.h>
Public Functions
void changeLayout ()
void handleKeyEvent (QWidget *widget, QEvent::Type type, XKeyEvent *ev)
QXlibKeyboard (QXlibScreen *screen)
Qt::KeyboardModifiers translateModifiers (int s)
Private Functions
void setMask (KeySym sym, uint mask)
int translateKeySym (uint key) const
QString translateKeySym (KeySym keysym, uint xmodifiers, int &code, Qt::KeyboardModifiers &modifiers, QByteArray &chars, int &count)
Properties
uint m_alt_mask
uint m_hyper_mask
uint m_meta_mask
uint m_mode_switch_mask
uint m_num_lock_mask
QXlibScreen * m_screen
uint m_super_mask
Detailed Description
Definition at line 47 of file qxlibkeyboard.h.
Constructors and Destructors
QXlibKeyboard()
QXlibKeyboard::QXlibKeyboard (QXlibScreen * screen)
Definition at line 943 of file qxlibkeyboard.cpp.
     : m_screen(screen)
     , m_alt_mask(0)
     , m_super_mask(0)
     , m_hyper_mask(0)
     , m_meta_mask(0)
 {
     changeLayout();
 }
Functions
changeLayout()
void QXlibKeyboard::changeLayout ()
Definition at line 953 of file qxlibkeyboard.cpp.
Referenced by QXlibKeyboard().
 {
     XkbDescPtr xkbDesc = XkbGetMap(m_screen->display()->nativeDisplay(), XkbAllClientInfoMask, XkbUseCoreKbd);
     for (int i = xkbDesc->min_key_code; i < xkbDesc->max_key_code; ++i) {
         const uint mask = xkbDesc->map->modmap ? xkbDesc->map->modmap[i] : 0;
         if (mask == 0) {
             // key is not bound to a modifier
             continue;
         }
         for (int j = 0; j < XkbKeyGroupsWidth(xkbDesc, i); ++j) {
             KeySym keySym = XkbKeySym(xkbDesc, i, j);
             if (keySym == NoSymbol)
                 continue;
             setMask(keySym, mask);
         }
     }
     XkbFreeKeyboard(xkbDesc, XkbAllComponentsMask, true);
 }
handleKeyEvent()
void QXlibKeyboard::handleKeyEvent (QWidget * widget, QEvent::Type type, XKeyEvent * ev)
Definition at line 990 of file qxlibkeyboard.cpp.
Referenced by QXlibScreen::handleEvent().
 {
     int qtcode = 0;
     Qt::KeyboardModifiers modifiers = translateModifiers(ev->state);
     QByteArray chars;
     chars.resize(513);
     int count = 0;
     KeySym keySym;
     count = XLookupString(ev,chars.data(),chars.size(),&keySym,0);
     QString text = translateKeySym(keySym,ev->state,qtcode,modifiers,chars,count);
     QWindowSystemInterface::handleExtendedKeyEvent(widget,ev->time,type,qtcode,modifiers,ev->keycode,0,ev->state,text.left(count));
 }
setMask()
void QXlibKeyboard::setMask (KeySym sym, uint mask) private
Definition at line 760 of file qxlibkeyboard.cpp.
Referenced by changeLayout().
 {
         if (m_alt_mask == 0
             && m_meta_mask != mask
             && m_super_mask != mask
             && m_hyper_mask != mask
             && (sym == XK_Alt_L || sym == XK_Alt_R)) {
             m_alt_mask = mask;
         }
         if (m_meta_mask == 0
             && m_alt_mask != mask
             && m_super_mask != mask
             && m_hyper_mask != mask
             && (sym == XK_Meta_L || sym == XK_Meta_R)) {
             m_meta_mask = mask;
         }
         if (m_super_mask == 0
             && m_alt_mask != mask
             && m_meta_mask != mask
             && m_hyper_mask != mask
             && (sym == XK_Super_L || sym == XK_Super_R)) {
             m_super_mask = mask;
         }
         if (m_hyper_mask == 0
             && m_alt_mask != mask
             && m_meta_mask != mask
             && m_super_mask != mask
             && (sym == XK_Hyper_L || sym == XK_Hyper_R)) {
             m_hyper_mask = mask;
         }
         if (m_mode_switch_mask == 0
             && m_alt_mask != mask
             && m_meta_mask != mask
             && m_super_mask != mask
             && m_hyper_mask != mask
             && sym == XK_Mode_switch) {
             m_mode_switch_mask = mask;
         }
         if (m_num_lock_mask == 0
             && sym == XK_Num_Lock) {
             m_num_lock_mask = mask;
         }
 }
translateKeySym() [1/2]
int QXlibKeyboard::translateKeySym (uint key) const private
Definition at line 804 of file qxlibkeyboard.cpp.
Referenced by handleKeyEvent(), and translateKeySym().
 {
     int code = -1;
     int i = 0;                                // any other keys
     while (KeyTbl[i]) {
         if (key == KeyTbl[i]) {
             code = (int)KeyTbl[i+1];
             break;
         }
         i += 2;
     }
     if (m_meta_mask) {
         // translate Super/Hyper keys to Meta if we're using them as the MetaModifier
         if (m_meta_mask == m_super_mask && (code == Qt::Key_Super_L || code == Qt::Key_Super_R)) {
             code = Qt::Key_Meta;
         } else if (m_meta_mask == m_hyper_mask && (code == Qt::Key_Hyper_L || code == Qt::Key_Hyper_R)) {
             code = Qt::Key_Meta;
         }
     }
     return code;
 }
translateKeySym() [2/2]
QString QXlibKeyboard::translateKeySym (KeySym keysym, uint xmodifiers, int & code, Qt::KeyboardModifiers & modifiers, QByteArray & chars, int & count) private
Definition at line 826 of file qxlibkeyboard.cpp.
 {
     // all keysyms smaller than 0xff00 are actally keys that can be mapped to unicode chars
     QTextCodec *mapper = QTextCodec::codecForLocale();
     QChar converted;
     if (/*count == 0 &&*/ keysym < 0xff00) {
         unsigned char byte3 = (unsigned char)(keysym >> 8);
         int mib = -1;
         switch(byte3) {
         case 0: // Latin 1
         case 1: // Latin 2
         case 2: //latin 3
         case 3: // latin4
             mib = byte3 + 4; break;
         case 5: // arabic
             mib = 82; break;
         case 12: // Hebrew
             mib = 85; break;
         case 13: // Thai
             mib = 2259; break;
         case 4: // kana
         case 6: // cyrillic
         case 7: // greek
         case 8: // technical, no mapping here at the moment
         case 9: // Special
         case 10: // Publishing
         case 11: // APL
         case 14: // Korean, no mapping
             mib = -1; // manual conversion
             mapper= 0;
 #if !defined(QT_NO_XIM)
             converted = keysymToUnicode(byte3, keysym & 0xff);
 #endif
         case 0x20:
             // currency symbols
             if (keysym >= 0x20a0 && keysym <= 0x20ac) {
                 mib = -1; // manual conversion
                 mapper = 0;
                 converted = (uint)keysym;
             }
             break;
         default:
             break;
         }
         if (mib != -1) {
             mapper = QTextCodec::codecForMib(mib);
             if (chars.isEmpty())
                 chars.resize(1);
             chars[0] = (unsigned char) (keysym & 0xff); // get only the fourth bit for conversion later
             count = 1;
         }
     } else if (keysym >= 0x1000000 && keysym <= 0x100ffff) {
         converted = (ushort) (keysym - 0x1000000);
         mapper = 0;
     }
     if (count < (int)chars.size()-1)
         chars[count] = '\0';
     QString text;
     if (!mapper && converted.unicode() != 0x0) {
         text = converted;
     } else if (!chars.isEmpty()) {
         // convert chars (8bit) to text (unicode).
         if (mapper)
             text = mapper->toUnicode(chars.data(), count, 0);
         if (text.isEmpty()) {
             // no mapper, or codec couldn't convert to unicode (this
             // can happen when running in the C locale or with no LANG
             // set). try converting from latin-1
             text = QString::fromLatin1(chars);
         }
     }
     modifiers = translateModifiers(xmodifiers);
     // Commentary in X11/keysymdef says that X codes match ASCII, so it
     // is safe to use the locale functions to process X codes in ISO8859-1.
     //
     // This is mainly for compatibility - applications should not use the
     // Qt keycodes between 128 and 255, but should rather use the
     // QKeyEvent::text().
     //
     if (keysym < 128 || (keysym < 256 && (!mapper || mapper->mibEnum()==4))) {
         // upper-case key, if known
         code = isprint((int)keysym) ? toupper((int)keysym) : 0;
     } else if (keysym >= XK_F1 && keysym <= XK_F35) {
         // function keys
         code = Qt::Key_F1 + ((int)keysym - XK_F1);
     } else if (keysym >= XK_KP_Space && keysym <= XK_KP_9) {
         if (keysym >= XK_KP_0) {
             // numeric keypad keys
             code = Qt::Key_0 + ((int)keysym - XK_KP_0);
         } else {
             code = translateKeySym(keysym);
         }
         modifiers |= Qt::KeypadModifier;
     } else if (text.length() == 1 && text.unicode()->unicode() > 0x1f && text.unicode()->unicode() != 0x7f && !(keysym >= XK_dead_grave && keysym <= XK_dead_horn)) {
         code = text.unicode()->toUpper().unicode();
     } else {
         // any other keys
         code = translateKeySym(keysym);
         if (code == Qt::Key_Tab && (modifiers & Qt::ShiftModifier)) {
             // map shift+tab to shift+backtab, QShortcutMap knows about it
             // and will handle it.
             code = Qt::Key_Backtab;
             text = QString();
         }
     }
     return text;
 }
translateModifiers()
Qt::KeyboardModifiers QXlibKeyboard::translateModifiers (int s)
Definition at line 744 of file qxlibkeyboard.cpp.
Referenced by handleKeyEvent(), QXlibWindow::handleMouseEvent(), and translateKeySym().
 {
     Qt::KeyboardModifiers ret = 0;
     if (s & ShiftMask)
         ret |= Qt::ShiftModifier;
     if (s & ControlMask)
         ret |= Qt::ControlModifier;
     if (s & m_alt_mask)
         ret |= Qt::AltModifier;
     if (s & m_meta_mask)
         ret |= Qt::MetaModifier;
 //    if (s & m_mode_switch_mask) //doesn't seem to work correctly
 //        ret |= Qt::GroupSwitchModifier;
     return ret;
 }
Properties
m_alt_mask
uint QXlibKeyboard::m_alt_mask private
Definition at line 68 of file qxlibkeyboard.h.
Referenced by setMask(), and translateModifiers().
m_hyper_mask
uint QXlibKeyboard::m_hyper_mask private
Definition at line 70 of file qxlibkeyboard.h.
Referenced by setMask(), and translateKeySym().
m_meta_mask
uint QXlibKeyboard::m_meta_mask private
Definition at line 71 of file qxlibkeyboard.h.
Referenced by setMask(), translateKeySym(), and translateModifiers().
m_mode_switch_mask
uint QXlibKeyboard::m_mode_switch_mask private
Definition at line 72 of file qxlibkeyboard.h.
Referenced by setMask().
m_num_lock_mask
uint QXlibKeyboard::m_num_lock_mask private
Definition at line 73 of file qxlibkeyboard.h.
Referenced by setMask().
m_screen
QXlibScreen* QXlibKeyboard::m_screen private
Definition at line 66 of file qxlibkeyboard.h.
Referenced by changeLayout().
m_super_mask
uint QXlibKeyboard::m_super_mask private
Definition at line 69 of file qxlibkeyboard.h.
Referenced by setMask(), and translateKeySym().
The documentation for this class was generated from the following files:
/src/plugins/platforms/xlib/qxlibkeyboard.h
/src/plugins/platforms/xlib/qxlibkeyboard.cpp