Qt 4.8: QPSQLDriver Class Reference
QPSQLDriver Class Reference
#include <qsql_psql.h>
Public Types
enum Protocol {
VersionUnknown = -1, Version6 = 6, Version7 = 7, Version71 = 8,
Version73 = 9, Version74 = 10, Version8 = 11, Version81 = 12,
Version82 = 13, Version83 = 14, Version84 = 15, Version9 = 16
}
Public Types inherited from QSqlDriver
enum DriverFeature {
Transactions, QuerySize, BLOB, Unicode,
PreparedQueries, NamedPlaceholders, PositionalPlaceholders, LastInsertId,
BatchOperations, SimpleLocking, LowPrecisionNumbers, EventNotifications,
FinishQuery, MultipleResultSets
}
This enum contains a list of features a driver might support.
enum IdentifierType { FieldName, TableName }
This enum contains a list of SQL identifier types.
enum StatementType {
WhereStatement, SelectStatement, UpdateStatement, InsertStatement,
DeleteStatement
}
This enum contains a list of SQL statement (or clause) types the driver can create.
Public Functions
void close ()
Derived classes must reimplement this pure virtual function in order to close the database connection.
QSqlResult * createResult () const
Creates an empty SQL result on the database.
QString escapeIdentifier (const QString &identifier, IdentifierType type) const
Returns the identifier escaped according to the database rules.
QString formatValue (const QSqlField &field, bool trimStrings) const
Returns a string representation of the field value for the database.
QVariant handle () const
Returns the low-level database handle wrapped in a QVariant or an invalid variant if there is no handle.
bool hasFeature (DriverFeature f) const
Returns true if the driver supports feature feature; otherwise returns false.
bool isOpen () const
Returns true if the database connection is open; otherwise returns false.
bool open (const QString &db, const QString &user, const QString &password, const QString &host, int port, const QString &connOpts)
Derived classes must reimplement this pure virtual function to open a database connection on database db, using user name user, password password, host host, port port and connection options options.
QSqlIndex primaryIndex (const QString &tablename) const
Returns the primary index for table tableName.
Protocol protocol () const
QPSQLDriver (QObject *parent=0)
QPSQLDriver (PGconn *conn, QObject *parent=0)
QSqlRecord record (const QString &tablename) const
Returns a QSqlRecord populated with the names of the fields in table tableName.
QStringList tables (QSql::TableType) const
Returns a list of the names of the tables in the database.
~QPSQLDriver ()
Public Functions inherited from QSqlDriver
bool isIdentifierEscaped (const QString &identifier, IdentifierType type) const
Returns whether identifier is escaped according to the database rules.
bool isOpenError () const
Returns true if the there was an error opening the database connection; otherwise returns false.
QSqlError lastError () const
Returns a QSqlError object which contains information about the last error that occurred on the database.
QSql::NumericalPrecisionPolicy numericalPrecisionPolicy () const
Returns the current default precision policy for the database connection.
QSqlDriver (QObject *parent=0)
Constructs a new driver with the given parent.
void setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy precisionPolicy)
Sets the default numerical precision policy used by queries created by this driver to precisionPolicy.
virtual QString sqlStatement (StatementType type, const QString &tableName, const QSqlRecord &rec, bool preparedStatement) const
Returns a SQL statement of type type for the table tableName with the values from rec.
QString stripDelimiters (const QString &identifier, IdentifierType type) const
Returns the identifier with the leading and trailing delimiters removed, identifier can either be a table name or field name, dependent on type.
QStringList subscribedToNotifications () const
Returns a list of the names of the event notifications that are currently subscribed to.
bool subscribeToNotification (const QString &name)
This function is called to subscribe to event notifications from the database.
bool unsubscribeFromNotification (const QString &name)
This function is called to unsubscribe from event notifications from the database.
~QSqlDriver ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Slots
QStringList subscribedToNotificationsImplementation () const
bool subscribeToNotificationImplementation (const QString &name)
bool unsubscribeFromNotificationImplementation (const QString &name)
Protected Slots inherited from QSqlDriver
bool isIdentifierEscapedImplementation (const QString &identifier, IdentifierType type) const
This slot returns whether identifier is escaped according to the database rules.
QString stripDelimitersImplementation (const QString &identifier, IdentifierType type) const
This slot returns identifier with the leading and trailing delimiters removed, identifier can either be a tablename or field name, dependent on type.
QStringList subscribedToNotificationsImplementation () const
Returns a list of the names of the event notifications that are currently subscribed to.
bool subscribeToNotificationImplementation (const QString &name)
This slot is called to subscribe to event notifications from the database.
bool unsubscribeFromNotificationImplementation (const QString &name)
This slot is called to unsubscribe from event notifications from the database.
Protected Functions
bool beginTransaction ()
This function is called to begin a transaction.
bool commitTransaction ()
This function is called to commit a transaction.
bool rollbackTransaction ()
This function is called to rollback a transaction.
Protected Functions inherited from QSqlDriver
virtual void setLastError (const QSqlError &e)
This function is used to set the value of the last error, error, that occurred on the database.
virtual void setOpen (bool o)
This function sets the open state of the database to open.
virtual void setOpenError (bool e)
This function sets the open error state of the database to error.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void _q_handleNotification (int)
Private Functions
void init ()
Properties
QPSQLDriverPrivate * d
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QSqlDriver
void notification (const QString &name)
This signal is emitted when the database posts an event notification that the driver subscribes to.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 95 of file qsql_psql.h.
Enumerations
Protocol
enum QPSQLDriver::Protocol
Enumerator
VersionUnknown
Version6
Version7
Version71
Version73
Version74
Version8
Version81
Version82
Version83
Version84
Version9
Definition at line 99 of file qsql_psql.h.
                   {
         VersionUnknown = -1,
         Version6 = 6,
         Version7 = 7,
         Version71 = 8,
         Version73 = 9,
         Version74 = 10,
         Version8 = 11,
         Version81 = 12,
         Version82 = 13,
         Version83 = 14,
         Version84 = 15,
         Version9 = 16,
     };
Constructors and Destructors
QPSQLDriver() [1/2]
QPSQLDriver::QPSQLDriver (QObject * parent = 0) explicit
Definition at line 760 of file qsql_psql.cpp.
     : QSqlDriver(parent)
 {
     init();
 }
QPSQLDriver() [2/2]
QPSQLDriver::QPSQLDriver (PGconn * conn, QObject * parent = 0) explicit
Definition at line 766 of file qsql_psql.cpp.
     : QSqlDriver(parent)
 {
     init();
     d->connection = conn;
     if (conn) {
         d->pro = d->getPSQLVersion();
         d->detectBackslashEscape();
         setOpen(true);
         setOpenError(false);
     }
 }
~QPSQLDriver()
QPSQLDriver::~QPSQLDriver ()
Definition at line 784 of file qsql_psql.cpp.
 {
     if (d->connection)
         PQfinish(d->connection);
     delete d;
 }
Functions
_q_handleNotification
void QPSQLDriver::_q_handleNotification (int) private slot
Definition at line 1402 of file qsql_psql.cpp.
Referenced by close(), subscribeToNotificationImplementation(), and unsubscribeFromNotificationImplementation().
 {
     d->pendingNotifyCheck = false;
     PQconsumeInput(d->connection);
     PGnotify *notify = 0;
     while((notify = PQnotifies(d->connection)) != 0) {
         QString name(QLatin1String(notify->relname));
         if (d->seid.contains(name))
             emit notification(name);
         else
             qWarning("QPSQLDriver: received notification for '%s' which isn't subscribed to.",
                     qPrintable(name));
         qPQfreemem(notify);
     }
 }
beginTransaction()
bool QPSQLDriver::beginTransaction () protected virtual
This function is called to begin a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
commitTransaction(), rollbackTransaction()
Reimplemented from QSqlDriver.
Definition at line 907 of file qsql_psql.cpp.
 {
     if (!isOpen()) {
         qWarning("QPSQLDriver::beginTransaction: Database not open");
         return false;
     }
     PGresult* res = d->exec("BEGIN");
     if (!res || PQresultStatus(res) != PGRES_COMMAND_OK) {
         setLastError(qMakeError(tr("Could not begin transaction"),
                                 QSqlError::TransactionError, d, res));
         PQclear(res);
         return false;
     }
     PQclear(res);
     return true;
 }
close()
void QPSQLDriver::close () virtual
Derived classes must reimplement this pure virtual function in order to close the database connection.
Return true on success, false on failure.
See also
open(), setOpen()
Implements QSqlDriver.
Definition at line 883 of file qsql_psql.cpp.
Referenced by open().
 {
     if (isOpen()) {
         d->seid.clear();
         if (d->sn) {
             disconnect(d->sn, SIGNAL(activated(int)), this, SLOT(_q_handleNotification(int)));
             delete d->sn;
             d->sn = 0;
         }
         if (d->connection)
             PQfinish(d->connection);
         d->connection = 0;
         setOpen(false);
         setOpenError(false);
     }
 }
commitTransaction()
bool QPSQLDriver::commitTransaction () protected virtual
This function is called to commit a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
beginTransaction(), rollbackTransaction()
Reimplemented from QSqlDriver.
Definition at line 924 of file qsql_psql.cpp.
 {
     if (!isOpen()) {
         qWarning("QPSQLDriver::commitTransaction: Database not open");
         return false;
     }
     PGresult* res = d->exec("COMMIT");
     bool transaction_failed = false;
     // XXX
     // This hack is used to tell if the transaction has succeeded for the protocol versions of
     // PostgreSQL below. For 7.x and other protocol versions we are left in the dark.
     // This hack can dissapear once there is an API to query this sort of information.
     if (d->pro == QPSQLDriver::Version8 ||
         d->pro == QPSQLDriver::Version81 ||
         d->pro == QPSQLDriver::Version82 ||
         d->pro == QPSQLDriver::Version83 ||
         d->pro == QPSQLDriver::Version84 ||
         d->pro == QPSQLDriver::Version9) {
         transaction_failed = qstrcmp(PQcmdStatus(res), "ROLLBACK") == 0;
     }
     if (!res || PQresultStatus(res) != PGRES_COMMAND_OK || transaction_failed) {
         setLastError(qMakeError(tr("Could not commit transaction"),
                                 QSqlError::TransactionError, d, res));
         PQclear(res);
         return false;
     }
     PQclear(res);
     return true;
 }
createResult()
QSqlResult * QPSQLDriver::createResult () const virtual
Creates an empty SQL result on the database.
Derived classes must reimplement this function and return a QSqlResult object appropriate for their database to the caller.
Implements QSqlDriver.
Definition at line 902 of file qsql_psql.cpp.
Referenced by primaryIndex(), record(), and tables().
 {
     return new QPSQLResult(this, d);
 }
escapeIdentifier()
QString QPSQLDriver::escapeIdentifier (const QString & identifier, IdentifierType type) const virtual
Returns the identifier escaped according to the database rules.
identifier can either be a table name or field name, dependent on type.
The default implementation does nothing.
See also
isIdentifierEscaped()
Reimplemented from QSqlDriver.
Definition at line 1308 of file qsql_psql.cpp.
Referenced by subscribeToNotificationImplementation(), and unsubscribeFromNotificationImplementation().
 {
     QString res = identifier;
     if(!identifier.isEmpty() && !identifier.startsWith(QLatin1Char('"')) && !identifier.endsWith(QLatin1Char('"')) ) {
         res.replace(QLatin1Char('"'), QLatin1String("\"\""));
         res.prepend(QLatin1Char('"')).append(QLatin1Char('"'));
         res.replace(QLatin1Char('.'), QLatin1String("\".\""));
     }
     return res;
 }
formatValue()
QString QPSQLDriver::formatValue (const QSqlField & field, bool trimStrings) const virtual
Returns a string representation of the field value for the database.
Use the other formatValue() overload instead.
This is used, for example, when constructing INSERT and UPDATE statements.
The default implementation returns the value formatted as a string according to the following rules:
If field is character data, the value is returned enclosed in single quotation marks, which is appropriate for many SQL databases. Any embedded single-quote characters are escaped (replaced with two single-quote characters). If trimStrings is true (the default is false), all trailing whitespace is trimmed from the field.
If field is date/time data, the value is formatted in ISO format and enclosed in single quotation marks. If the date/time data is invalid, "NULL" is returned.
If field is bytearray data, and the driver can edit binary fields, the value is formatted as a hexadecimal string.
For any other field type, toString() is called on its value and the result of this is returned.
See also
QVariant::toString()
Reimplemented from QSqlDriver.
Definition at line 1223 of file qsql_psql.cpp.
 {
     QString r;
     if (field.isNull()) {
         r = QLatin1String("NULL");
     } else {
         switch (field.type()) {
         case QVariant::DateTime:
 #ifndef QT_NO_DATESTRING
             if (field.value().toDateTime().isValid()) {
                 QDate dt = field.value().toDateTime().date();
                 QTime tm = field.value().toDateTime().time();
                 // msecs need to be right aligned otherwise psql
                 // interpretes them wrong
                 r = QLatin1Char('\'') + QString::number(dt.year()) + QLatin1Char('-')
                           + QString::number(dt.month()) + QLatin1Char('-')
                           + QString::number(dt.day()) + QLatin1Char(' ')
                           + tm.toString() + QLatin1Char('.')
                           + QString::number(tm.msec()).rightJustified(3, QLatin1Char('0'))
                           + QLatin1Char('\'');
             } else {
                 r = QLatin1String("NULL");
             }
 #else
             r = QLatin1String("NULL");
 #endif // QT_NO_DATESTRING
             break;
         case QVariant::Time:
 #ifndef QT_NO_DATESTRING
             if (field.value().toTime().isValid()) {
                 r = QLatin1Char('\'') + field.value().toTime().toString(QLatin1String("hh:mm:ss.zzz")) + QLatin1Char('\'');
             } else
 #endif
             {
                 r = QLatin1String("NULL");
             }
             break;
         case QVariant::String:
             r = QSqlDriver::formatValue(field, trimStrings);
             if (d->hasBackslashEscape)
                 r.replace(QLatin1String("\\"), QLatin1String("\\\\"));
             break;
         case QVariant::Bool:
             if (field.value().toBool())
                 r = QLatin1String("TRUE");
             else
                 r = QLatin1String("FALSE");
             break;
         case QVariant::ByteArray: {
             QByteArray ba(field.value().toByteArray());
             size_t len;
 #if defined PG_VERSION_NUM && PG_VERSION_NUM-0 >= 80200
             unsigned char *data = PQescapeByteaConn(d->connection, (unsigned char*)ba.constData(), ba.size(), &len);
 #else
             unsigned char *data = PQescapeBytea((unsigned char*)ba.constData(), ba.size(), &len);
 #endif
             r += QLatin1Char('\'');
             r += QLatin1String((const char*)data);
             r += QLatin1Char('\'');
             qPQfreemem(data);
             break;
         }
         case QVariant::Double: {
             double val = field.value().toDouble();
             if (isnan(val))
                 r = QLatin1String("'NaN'");
             else {
                 int res = isinf(val);
                 if (res == 1)
                     r = QLatin1String("'Infinity'");
                 else if (res == -1)
                     r = QLatin1String("'-Infinity'");
                 else
                     r = QSqlDriver::formatValue(field, trimStrings);
             }
             break;
         }
         default:
             r = QSqlDriver::formatValue(field, trimStrings);
             break;
         }
     }
     return r;
 }
handle()
QVariant QPSQLDriver::handle () const virtual
Returns the low-level database handle wrapped in a QVariant or an invalid variant if there is no handle.
Warning
Use this with uttermost care and only if you know what you're doing.
The handle returned here can become a stale pointer if the connection is modified (for example, if you close the connection).
The handle can be NULL if the connection is not open yet.
The handle returned here is database-dependent, you should query the type name of the variant before accessing it.
This example retrieves the handle for a connection to sqlite:
QSqlDatabase db = ...;
QVariant v = db.driver()->handle();
if (v.isValid() && qstrcmp(v.typeName(), "sqlite3*") == 0) {
    // v.data() returns a pointer to the handle
    sqlite3 *handle = *static_cast<sqlite3 **>(v.data());
    if (handle != 0) { // check that it is not NULL
        ...
    }
}
This snippet returns the handle for PostgreSQL or MySQL:
if (qstrcmp(v.typeName(), "PGconn*") == 0) {
    PGconn *handle = *static_cast<PGconn **>(v.data());
    if (handle != 0) ...
}
if (qstrcmp(v.typeName(), "MYSQL*") == 0) {
    MYSQL *handle = *static_cast<MYSQL **>(v.data());
    if (handle != 0) ...
}
See also
QSqlResult::handle()
Reimplemented from QSqlDriver.
Definition at line 791 of file qsql_psql.cpp.
 {
     return QVariant::fromValue(d->connection);
 }
hasFeature()
bool QPSQLDriver::hasFeature (DriverFeature feature) const virtual
Returns true if the driver supports feature feature; otherwise returns false.
Note that some databases need to be open() before this can be determined.
See also
DriverFeature
Implements QSqlDriver.
Definition at line 796 of file qsql_psql.cpp.
Referenced by QPSQLResult::QPSQLResult().
 {
     switch (f) {
     case Transactions:
     case QuerySize:
     case LastInsertId:
     case LowPrecisionNumbers:
     case EventNotifications:
         return true;
     case PreparedQueries:
     case PositionalPlaceholders:
         return d->pro >= QPSQLDriver::Version82;
     case BatchOperations:
     case NamedPlaceholders:
     case SimpleLocking:
     case FinishQuery:
     case MultipleResultSets:
         return false;
     case BLOB:
         return d->pro >= QPSQLDriver::Version71;
     case Unicode:
         return d->isUtf8;
     }
     return false;
 }
init()
void QPSQLDriver::init () private
Definition at line 779 of file qsql_psql.cpp.
Referenced by QPSQLDriver().
 {
     d = new QPSQLDriverPrivate(this);
 }
isOpen()
bool QPSQLDriver::isOpen () const virtual
Returns true if the database connection is open; otherwise returns false.
Reimplemented from QSqlDriver.
Definition at line 1319 of file qsql_psql.cpp.
Referenced by beginTransaction(), close(), commitTransaction(), open(), primaryIndex(), record(), rollbackTransaction(), subscribeToNotificationImplementation(), tables(), and unsubscribeFromNotificationImplementation().
 {
     return PQstatus(d->connection) == CONNECTION_OK;
 }
open()
bool QPSQLDriver::open (const QString & db, const QString & user, const QString & password, const QString & host, int port, const QString & options) virtual
Derived classes must reimplement this pure virtual function to open a database connection on database db, using user name user, password password, host host, port port and connection options options.
The function must return true on success and false on failure.
See also
setOpen()
Implements QSqlDriver.
Definition at line 836 of file qsql_psql.cpp.
 {
     if (isOpen())
         close();
     QString connectString;
     if (!host.isEmpty())
         connectString.append(QLatin1String("host=")).append(qQuote(host));
     if (!db.isEmpty())
         connectString.append(QLatin1String(" dbname=")).append(qQuote(db));
     if (!user.isEmpty())
         connectString.append(QLatin1String(" user=")).append(qQuote(user));
     if (!password.isEmpty())
         connectString.append(QLatin1String(" password=")).append(qQuote(password));
     if (port != -1)
         connectString.append(QLatin1String(" port=")).append(qQuote(QString::number(port)));
     // add any connect options - the server will handle error detection
     if (!connOpts.isEmpty()) {
         QString opt = connOpts;
         opt.replace(QLatin1Char(';'), QLatin1Char(' '), Qt::CaseInsensitive);
         connectString.append(QLatin1Char(' ')).append(opt);
     }
     d->connection = PQconnectdb(connectString.toLocal8Bit().constData());
     if (PQstatus(d->connection) == CONNECTION_BAD) {
         setLastError(qMakeError(tr("Unable to connect"), QSqlError::ConnectionError, d));
         setOpenError(true);
         PQfinish(d->connection);
         d->connection = 0;
         return false;
     }
     d->pro = d->getPSQLVersion();
     d->detectBackslashEscape();
     d->isUtf8 = d->setEncodingUtf8();
     d->setDatestyle();
     setOpen(true);
     setOpenError(false);
     return true;
 }
primaryIndex()
QSqlIndex QPSQLDriver::primaryIndex (const QString & tableName) const virtual
Returns the primary index for table tableName.
Returns an empty QSqlIndex if the table doesn't have a primary index. The default implementation returns an empty index.
Reimplemented from QSqlDriver.
Definition at line 1005 of file qsql_psql.cpp.
 {
     QSqlIndex idx(tablename);
     if (!isOpen())
         return idx;
     QSqlQuery i(createResult());
     QString stmt;
     QString tbl = tablename;
     QString schema;
     qSplitTableName(tbl, schema);
     if (isIdentifierEscaped(tbl, QSqlDriver::TableName))
         tbl = stripDelimiters(tbl, QSqlDriver::TableName);
     else
         tbl = tbl.toLower();
     if (isIdentifierEscaped(schema, QSqlDriver::TableName))
         schema = stripDelimiters(schema, QSqlDriver::TableName);
     else
         schema = schema.toLower();
     switch(d->pro) {
     case QPSQLDriver::Version6:
         stmt = QLatin1String("select pg_att1.attname, int(pg_att1.atttypid), pg_cl.relname "
                 "from pg_attribute pg_att1, pg_attribute pg_att2, pg_class pg_cl, pg_index pg_ind "
                 "where pg_cl.relname = '%1_pkey' "
                 "and pg_cl.oid = pg_ind.indexrelid "
                 "and pg_att2.attrelid = pg_ind.indexrelid "
                 "and pg_att1.attrelid = pg_ind.indrelid "
                 "and pg_att1.attnum = pg_ind.indkey[pg_att2.attnum-1] "
                 "order by pg_att2.attnum");
         break;
     case QPSQLDriver::Version7:
     case QPSQLDriver::Version71:
         stmt = QLatin1String("select pg_att1.attname, pg_att1.atttypid::int, pg_cl.relname "
                 "from pg_attribute pg_att1, pg_attribute pg_att2, pg_class pg_cl, pg_index pg_ind "
                 "where pg_cl.relname = '%1_pkey' "
                 "and pg_cl.oid = pg_ind.indexrelid "
                 "and pg_att2.attrelid = pg_ind.indexrelid "
                 "and pg_att1.attrelid = pg_ind.indrelid "
                 "and pg_att1.attnum = pg_ind.indkey[pg_att2.attnum-1] "
                 "order by pg_att2.attnum");
         break;
     case QPSQLDriver::Version73:
     case QPSQLDriver::Version74:
     case QPSQLDriver::Version8:
     case QPSQLDriver::Version81:
     case QPSQLDriver::Version82:
     case QPSQLDriver::Version83:
     case QPSQLDriver::Version84:
     case QPSQLDriver::Version9:
         stmt = QLatin1String("SELECT pg_attribute.attname, pg_attribute.atttypid::int, "
                 "pg_class.relname "
                 "FROM pg_attribute, pg_class "
                 "WHERE %1 pg_class.oid IN "
                 "(SELECT indexrelid FROM pg_index WHERE indisprimary = true AND indrelid IN "
                 " (SELECT oid FROM pg_class WHERE relname = '%2')) "
                 "AND pg_attribute.attrelid = pg_class.oid "
                 "AND pg_attribute.attisdropped = false "
                 "ORDER BY pg_attribute.attnum");
         if (schema.isEmpty())
             stmt = stmt.arg(QLatin1String("pg_table_is_visible(pg_class.oid) AND"));
         else
             stmt = stmt.arg(QString::fromLatin1("pg_class.relnamespace = (select oid from "
                    "pg_namespace where pg_namespace.nspname = '%1') AND ").arg(schema));
         break;
     case QPSQLDriver::VersionUnknown:
         qFatal("PSQL version is unknown");
         break;
     }
     i.exec(stmt.arg(tbl));
     while (i.isActive() && i.next()) {
         QSqlField f(i.value(0).toString(), qDecodePSQLType(i.value(1).toInt()));
         idx.append(f);
         idx.setName(i.value(2).toString());
     }
     return idx;
 }
protocol()
QPSQLDriver::Protocol QPSQLDriver::protocol () const
Definition at line 1324 of file qsql_psql.cpp.
 {
     return d->pro;
 }
record()
QSqlRecord QPSQLDriver::record (const QString & tableName) const virtual
Returns a QSqlRecord populated with the names of the fields in table tableName.
Use query.
If no such table exists, an empty record is returned. The default implementation returns an empty record.
record() instead.
Reimplemented from QSqlDriver.
Definition at line 1086 of file qsql_psql.cpp.
 {
     QSqlRecord info;
     if (!isOpen())
         return info;
     QString tbl = tablename;
     QString schema;
     qSplitTableName(tbl, schema);
     if (isIdentifierEscaped(tbl, QSqlDriver::TableName))
         tbl = stripDelimiters(tbl, QSqlDriver::TableName);
     else
         tbl = tbl.toLower();
     if (isIdentifierEscaped(schema, QSqlDriver::TableName))
         schema = stripDelimiters(schema, QSqlDriver::TableName);
     else
         schema = schema.toLower();
     QString stmt;
     switch(d->pro) {
     case QPSQLDriver::Version6:
         stmt = QLatin1String("select pg_attribute.attname, int(pg_attribute.atttypid), "
                 "pg_attribute.attnotnull, pg_attribute.attlen, pg_attribute.atttypmod, "
                 "int(pg_attribute.attrelid), pg_attribute.attnum "
                 "from pg_class, pg_attribute "
                 "where pg_class.relname = '%1' "
                 "and pg_attribute.attnum > 0 "
                 "and pg_attribute.attrelid = pg_class.oid ");
         break;
     case QPSQLDriver::Version7:
         stmt = QLatin1String("select pg_attribute.attname, pg_attribute.atttypid::int, "
                 "pg_attribute.attnotnull, pg_attribute.attlen, pg_attribute.atttypmod, "
                 "pg_attribute.attrelid::int, pg_attribute.attnum "
                 "from pg_class, pg_attribute "
                 "where pg_class.relname = '%1' "
                 "and pg_attribute.attnum > 0 "
                 "and pg_attribute.attrelid = pg_class.oid ");
         break;
     case QPSQLDriver::Version71:
         stmt = QLatin1String("select pg_attribute.attname, pg_attribute.atttypid::int, "
                 "pg_attribute.attnotnull, pg_attribute.attlen, pg_attribute.atttypmod, "
                 "pg_attrdef.adsrc "
                 "from pg_class, pg_attribute "
                 "left join pg_attrdef on (pg_attrdef.adrelid = "
                 "pg_attribute.attrelid and pg_attrdef.adnum = pg_attribute.attnum) "
                 "where pg_class.relname = '%1' "
                 "and pg_attribute.attnum > 0 "
                 "and pg_attribute.attrelid = pg_class.oid "
                 "order by pg_attribute.attnum ");
         break;
     case QPSQLDriver::Version73:
     case QPSQLDriver::Version74:
     case QPSQLDriver::Version8:
     case QPSQLDriver::Version81:
     case QPSQLDriver::Version82:
     case QPSQLDriver::Version83:
     case QPSQLDriver::Version84:
     case QPSQLDriver::Version9:
         stmt = QLatin1String("select pg_attribute.attname, pg_attribute.atttypid::int, "
                 "pg_attribute.attnotnull, pg_attribute.attlen, pg_attribute.atttypmod, "
                 "pg_attrdef.adsrc "
                 "from pg_class, pg_attribute "
                 "left join pg_attrdef on (pg_attrdef.adrelid = "
                 "pg_attribute.attrelid and pg_attrdef.adnum = pg_attribute.attnum) "
                 "where %1 "
                 "and pg_class.relname = '%2' "
                 "and pg_attribute.attnum > 0 "
                 "and pg_attribute.attrelid = pg_class.oid "
                 "and pg_attribute.attisdropped = false "
                 "order by pg_attribute.attnum ");
         if (schema.isEmpty())
             stmt = stmt.arg(QLatin1String("pg_table_is_visible(pg_class.oid)"));
         else
             stmt = stmt.arg(QString::fromLatin1("pg_class.relnamespace = (select oid from "
                    "pg_namespace where pg_namespace.nspname = '%1')").arg(schema));
         break;
     case QPSQLDriver::VersionUnknown:
         qFatal("PSQL version is unknown");
         break;
     }
     QSqlQuery query(createResult());
     query.exec(stmt.arg(tbl));
     if (d->pro >= QPSQLDriver::Version71) {
         while (query.next()) {
             int len = query.value(3).toInt();
             int precision = query.value(4).toInt();
             // swap length and precision if length == -1
             if (len == -1 && precision > -1) {
                 len = precision - 4;
                 precision = -1;
             }
             QString defVal = query.value(5).toString();
             if (!defVal.isEmpty() && defVal.at(0) == QLatin1Char('\''))
                 defVal = defVal.mid(1, defVal.length() - 2);
             QSqlField f(query.value(0).toString(), qDecodePSQLType(query.value(1).toInt()));
             f.setRequired(query.value(2).toBool());
             f.setLength(len);
             f.setPrecision(precision);
             f.setDefaultValue(defVal);
             f.setSqlType(query.value(1).toInt());
             info.append(f);
         }
     } else {
         // Postgres < 7.1 cannot handle outer joins
         while (query.next()) {
             QString defVal;
             QString stmt2 = QLatin1String("select pg_attrdef.adsrc from pg_attrdef where "
                             "pg_attrdef.adrelid = %1 and pg_attrdef.adnum = %2 ");
             QSqlQuery query2(createResult());
             query2.exec(stmt2.arg(query.value(5).toInt()).arg(query.value(6).toInt()));
             if (query2.isActive() && query2.next())
                 defVal = query2.value(0).toString();
             if (!defVal.isEmpty() && defVal.at(0) == QLatin1Char('\''))
                 defVal = defVal.mid(1, defVal.length() - 2);
             int len = query.value(3).toInt();
             int precision = query.value(4).toInt();
             // swap length and precision if length == -1
             if (len == -1 && precision > -1) {
                 len = precision - 4;
                 precision = -1;
             }
             QSqlField f(query.value(0).toString(), qDecodePSQLType(query.value(1).toInt()));
             f.setRequired(query.value(2).toBool());
             f.setLength(len);
             f.setPrecision(precision);
             f.setDefaultValue(defVal);
             f.setSqlType(query.value(1).toInt());
             info.append(f);
         }
     }
     return info;
 }
rollbackTransaction()
bool QPSQLDriver::rollbackTransaction () protected virtual
This function is called to rollback a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
beginTransaction(), commitTransaction()
Reimplemented from QSqlDriver.
Definition at line 957 of file qsql_psql.cpp.
 {
     if (!isOpen()) {
         qWarning("QPSQLDriver::rollbackTransaction: Database not open");
         return false;
     }
     PGresult* res = d->exec("ROLLBACK");
     if (!res || PQresultStatus(res) != PGRES_COMMAND_OK) {
         setLastError(qMakeError(tr("Could not rollback transaction"),
                                 QSqlError::TransactionError, d, res));
         PQclear(res);
         return false;
     }
     PQclear(res);
     return true;
 }
subscribedToNotificationsImplementation
QStringList QPSQLDriver::subscribedToNotificationsImplementation () const protected slot
Definition at line 1397 of file qsql_psql.cpp.
 {
     return d->seid;
 }
subscribeToNotificationImplementation
bool QPSQLDriver::subscribeToNotificationImplementation (const QString & name) protected slot
Definition at line 1329 of file qsql_psql.cpp.
 {
     if (!isOpen()) {
         qWarning("QPSQLDriver::subscribeToNotificationImplementation: database not open.");
         return false;
     }
     if (d->seid.contains(name)) {
         qWarning("QPSQLDriver::subscribeToNotificationImplementation: already subscribing to '%s'.",
             qPrintable(name));
         return false;
     }
     int socket = PQsocket(d->connection);
     if (socket) {
         // Add the name to the list of subscriptions here so that QSQLDriverPrivate::exec knows
         // to check for notifications immediately after executing the LISTEN
         d->seid << name;
         QString query = QLatin1String("LISTEN ") + escapeIdentifier(name, QSqlDriver::TableName);
         PGresult *result = d->exec(query);
         if (PQresultStatus(result) != PGRES_COMMAND_OK) {
             setLastError(qMakeError(tr("Unable to subscribe"), QSqlError::StatementError, d, result));
             return false;
         }
         if (!d->sn) {
             d->sn = new QSocketNotifier(socket, QSocketNotifier::Read);
             connect(d->sn, SIGNAL(activated(int)), this, SLOT(_q_handleNotification(int)));
         }
     } else {
         qWarning("QPSQLDriver::subscribeToNotificationImplementation: PQsocket didn't return a valid socket to listen on");
         return false;
     }
     return true;
 }
tables()
QStringList QPSQLDriver::tables (QSql::TableType tableType) const virtual
Returns a list of the names of the tables in the database.
The default implementation returns an empty list.
The tableType argument describes what types of tables should be returned. Due to binary compatibility, the string contains the value of the enum QSql::TableTypes as text. An empty string should be treated as QSql::Tables for backward compatibility.
Reimplemented from QSqlDriver.
Definition at line 974 of file qsql_psql.cpp.
 {
     QStringList tl;
     if (!isOpen())
         return tl;
     QSqlQuery t(createResult());
     t.setForwardOnly(true);
     if (type & QSql::Tables)
         d->appendTables(tl, t, QLatin1Char('r'));
     if (type & QSql::Views)
         d->appendTables(tl, t, QLatin1Char('v'));
     if (type & QSql::SystemTables) {
         t.exec(QLatin1String("select relname from pg_class where (relkind = 'r') "
                 "and (relname like 'pg_%') "));
         while (t.next())
             tl.append(t.value(0).toString());
     }
     return tl;
 }
unsubscribeFromNotificationImplementation
bool QPSQLDriver::unsubscribeFromNotificationImplementation (const QString & name) protected slot
Definition at line 1366 of file qsql_psql.cpp.
 {
     if (!isOpen()) {
         qWarning("QPSQLDriver::unsubscribeFromNotificationImplementation: database not open.");
         return false;
     }
     if (!d->seid.contains(name)) {
         qWarning("QPSQLDriver::unsubscribeFromNotificationImplementation: not subscribed to '%s'.",
             qPrintable(name));
         return false;
     }
     QString query = QLatin1String("UNLISTEN ") + escapeIdentifier(name, QSqlDriver::TableName);
     PGresult *result = d->exec(query);
     if (PQresultStatus(result) != PGRES_COMMAND_OK) {
         setLastError(qMakeError(tr("Unable to unsubscribe"), QSqlError::StatementError, d, result));
         return false;
     }
     d->seid.removeAll(name);
     if (d->seid.isEmpty()) {
         disconnect(d->sn, SIGNAL(activated(int)), this, SLOT(_q_handleNotification(int)));
         delete d->sn;
         d->sn = 0;
     }
     return true;
 }
Properties
d
QPSQLDriverPrivate* QPSQLDriver::d private
Definition at line 152 of file qsql_psql.h.
Referenced by _q_handleNotification(), beginTransaction(), close(), commitTransaction(), createResult(), formatValue(), handle(), hasFeature(), init(), isOpen(), open(), primaryIndex(), protocol(), QPSQLDriver(), record(), rollbackTransaction(), subscribedToNotificationsImplementation(), subscribeToNotificationImplementation(), tables(), unsubscribeFromNotificationImplementation(), and ~QPSQLDriver().
The documentation for this class was generated from the following files:
/src/sql/drivers/psql/qsql_psql.h
/src/sql/drivers/psql/qsql_psql.cpp