Qt 4.8: QDeclarativeItem Class Reference
QDeclarativeItem Class Reference
The QDeclarativeItem class provides the most basic of all visual items in QML.
#include <qdeclarativeitem.h>
Public Types
enum TransformOrigin {
TopLeft, Top, TopRight, Left,
Center, Right, BottomLeft, Bottom,
BottomRight
}
Controls the point about which simple transforms like scale apply.
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Signals
void activeFocusChanged (bool)
void baselineOffsetChanged (qreal)
void childrenRectChanged (const QRectF &)
void clipChanged (bool)
void focusChanged (bool)
void implicitHeightChanged ()
void implicitWidthChanged ()
void parentChanged (QDeclarativeItem *)
void smoothChanged (bool)
void stateChanged (const QString &)
void transformOriginChanged (TransformOrigin)
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
qreal baselineOffset () const
QRectF boundingRect () const
Q_INVOKABLE QDeclarativeItem * childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
QRectF childrenRect ()
bool clip () const
Q_INVOKABLE void forceActiveFocus ()
Forces active focus on the item.
bool hasActiveFocus () const
bool hasFocus () const
qreal height () const
qreal implicitHeight () const
qreal implicitWidth () const
bool keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
Q_INVOKABLE QScriptValue mapFromItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
Q_INVOKABLE QScriptValue mapToItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
virtual void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
QDeclarativeItem * parentItem () const
Returns the QDeclarativeItem parent of this item.
QDeclarativeItem (QDeclarativeItem *parent=0)
Constructs a QDeclarativeItem with the given parent.
void resetHeight ()
void resetWidth ()
void setBaselineOffset (qreal)
void setClip (bool)
void setFocus (bool)
void setHeight (qreal)
void setKeepMouseGrab (bool)
The flag indicating whether the mouse should remain with this item is set to keep.
void setParentItem (QDeclarativeItem *parent)
void setSize (const QSizeF &size)
void setSmooth (bool)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
void setTransformOrigin (TransformOrigin)
Set the transform origin.
void setWidth (qreal)
bool smooth () const
QDeclarativeListProperty< QGraphicsTransform > transform ()
TransformOrigin transformOrigin () const
qreal width () const
virtual ~QDeclarativeItem ()
Destroys the QDeclarativeItem.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
virtual void classBegin ()
virtual void componentComplete ()
virtual bool event (QEvent *)
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
bool heightValid () const
Returns whether the height property has been set explicitly.
virtual void inputMethodEvent (QInputMethodEvent *)
void inputMethodPreHandler (QInputMethodEvent *)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
bool isComponentComplete () const
Returns true if construction of the QML component is complete; otherwise returns false.
virtual QVariant itemChange (GraphicsItemChange, const QVariant &)
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
virtual void keyPressEvent (QKeyEvent *event)
void keyPressPreHandler (QKeyEvent *)
virtual void keyReleaseEvent (QKeyEvent *event)
void keyReleasePreHandler (QKeyEvent *)
QDeclarativeItem (QDeclarativeItemPrivate &dd, QDeclarativeItem *parent=0)
virtual bool sceneEvent (QEvent *)
void setImplicitHeight (qreal)
Sets the implied height of the item to h.
void setImplicitWidth (qreal)
Sets the implied width of the item to w.
bool widthValid () const
Returns whether the width property has been set explicitly.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
Filters events for the item watched.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
Properties
bool activeFocus
qreal baselineOffset
The position of the item's baseline in local coordinates.
QDeclarativeItem *QRectF childrenRect
The geometry of an item's children.
bool clip
This property holds whether clipping is enabled.
bool focus
qreal implicitHeight
Returns the height of the item that is implied by other properties that determine the content.
qreal implicitWidth
Returns the width of the item that is implied by other properties that determine the content.
bool smooth
whether the item is smoothly transformed.
QDeclarativeListProperty< QGraphicsTransform > transform
TransformOrigin transformOrigin
Returns the current transform origin.
QPointF transformOriginPoint
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
The QDeclarativeItem class provides the most basic of all visual items in QML.
Since
4.7
All visual items in Qt Declarative inherit from QDeclarativeItem. Although QDeclarativeItem has no visual appearance, it defines all the properties that are common across visual items - such as the x and y position, the width and height, anchor-layout{anchoring} and key handling.
You can subclass QDeclarativeItem to provide your own custom visual item that inherits these features. Note that, because it does not draw anything, QDeclarativeItem sets the QGraphicsItem::ItemHasNoContents flag. If you subclass QDeclarativeItem to create a visual item, you will need to unset this flag.
Definition at line 67 of file qdeclarativeitem.h.
Enumerations
TransformOrigin
enum QDeclarativeItem::TransformOrigin
Controls the point about which simple transforms like scale apply.
TopLeft The top-left corner of the item.
Top The center point of the top of the item.
TopRight The top-right corner of the item.
Left The left most point of the vertical middle.
Center The center of the item.
Right The right most point of the vertical middle.
BottomLeft The bottom-left corner of the item.
Bottom The center point of the bottom of the item.
BottomRight The bottom-right corner of the item.
Enumerator
TopLeft
Top
TopRight
Left
Center
Right
BottomLeft
Bottom
BottomRight
Definition at line 102 of file qdeclarativeitem.h.
{
         TopLeft, Top, TopRight,
         Left, Center, Right,
         BottomLeft, Bottom, BottomRight
     };
Constructors and Destructors
QDeclarativeItem() [1/2]
QDeclarativeItem::QDeclarativeItem (QDeclarativeItem * parent = 0)
Constructs a QDeclarativeItem with the given parent.
Definition at line 1830 of file qdeclarativeitem.cpp.
   : QGraphicsObject(*(new QDeclarativeItemPrivate), parent, 0)
 {
     Q_D(QDeclarativeItem);
     d->init(parent);
 }
~QDeclarativeItem()
QDeclarativeItem::~QDeclarativeItem () virtual
Destroys the QDeclarativeItem.
Definition at line 1849 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeItem);
     for (int ii = 0; ii < d->changeListeners.count(); ++ii) {
         QDeclarativeAnchorsPrivate *anchor = d->changeListeners.at(ii).listener->anchorPrivate();
         if (anchor)
             anchor->clearItem(this);
     }
     if (!d->parent || (parentItem() && !parentItem()->QGraphicsItem::d_ptr->inDestructor)) {
         for (int ii = 0; ii < d->changeListeners.count(); ++ii) {
             QDeclarativeAnchorsPrivate *anchor = d->changeListeners.at(ii).listener->anchorPrivate();
             if (anchor && anchor->item && anchor->item->parentItem() != this) //child will be deleted anyway
                 anchor->updateOnComplete();
         }
     }
     for(int ii = 0; ii < d->changeListeners.count(); ++ii) {
         const QDeclarativeItemPrivate::ChangeListener &change = d->changeListeners.at(ii);
         if (change.types & QDeclarativeItemPrivate::Destroyed)
             change.listener->itemDestroyed(this);
     }
     d->changeListeners.clear();
     delete d->_anchorLines; d->_anchorLines = 0;
     delete d->_anchors; d->_anchors = 0;
     delete d->_stateGroup; d->_stateGroup = 0;
     delete d->_contents; d->_contents = 0;
 }
QDeclarativeItem() [2/2]
QDeclarativeItem::QDeclarativeItem (QDeclarativeItemPrivate & dd, QDeclarativeItem * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 1839 of file qdeclarativeitem.cpp.
   : QGraphicsObject(dd, parent, 0)
 {
     Q_D(QDeclarativeItem);
     d->init(parent);
 }
Functions
activeFocusChanged
void QDeclarativeItem::activeFocusChanged (bool) signal
Warning
This function is not part of the public interface.
baselineOffset()
qreal QDeclarativeItem::baselineOffset () const
Referenced by QDeclarativeItemPrivate::baseline().
baselineOffsetChanged
void QDeclarativeItem::baselineOffsetChanged (qreal) signal
Warning
This function is not part of the public interface.
Referenced by setBaselineOffset().
boundingRect()
QRectF QDeclarativeItem::boundingRect () const virtual
Warning
This function is not part of the public interface.
Implements QGraphicsItem.
Reimplemented in QDeclarativeTextEdit, QDeclarativeTextInput, QDeclarativeText, QDeclarativeRectangle, and QDeclarativePaintedItem.
Definition at line 3372 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeMouseArea::mouseMoveEvent().
 {
     Q_D(const QDeclarativeItem);
     return QRectF(0, 0, d->mWidth, d->mHeight);
 }
childAt()
QDeclarativeItem * QDeclarativeItem::childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
Definition at line 2966 of file qdeclarativeitem.cpp.
 {
     const QList<QGraphicsItem *> children = childItems();
     for (int i = children.count()-1; i >= 0; --i) {
         if (QDeclarativeItem *child = qobject_cast<QDeclarativeItem *>(children.at(i))) {
             if (child->isVisible() && child->x() <= x
                 && child->x() + child->width() >= x
                 && child->y() <= y
                 && child->y() + child->height() >= y)
                 return child;
         }
     }
     return 0;
 }
childrenRect()
QRectF QDeclarativeItem::childrenRect ()
Referenced by QDeclarativeItemPrivate::data().
childrenRectChanged
void QDeclarativeItem::childrenRectChanged (const QRectF &) signal
Warning
This function is not part of the public interface.
classBegin()
void QDeclarativeItem::classBegin () protected virtual
Warning
This function is not part of the public interface.
classBegin() is called when the item is constructed, but its properties have not yet been set.
See also
componentComplete(), isComponentComplete()
Implements QDeclarativeParserStatus.
Definition at line 3194 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeItem);
     d->componentComplete = false;
     if (d->_stateGroup)
         d->_stateGroup->classBegin();
     if (d->_anchors)
         d->_anchors->classBegin();
 }
clip()
bool QDeclarativeItem::clip () const
Referenced by QDeclarativeItemPrivate::data(), QDeclarativeImage::paint(), QDeclarativePaintedItem::paint(), QDeclarativeText::paint(), and setClip().
clipChanged
void QDeclarativeItem::clipChanged (bool) signal
Warning
This function is not part of the public interface.
Referenced by setClip().
componentComplete()
void QDeclarativeItem::componentComplete () protected virtual
Warning
This function is not part of the public interface.
componentComplete() is called when all items in the component have been constructed. It is often desirable to delay some processing until the component is complete an all bindings in the component have been resolved.
Implements QDeclarativeParserStatus.
Reimplemented in QDeclarativeListView, QDeclarativeParticles, QDeclarativeGridView, QDeclarativeTextEdit, QDeclarativePathView, QDeclarativeText, QDeclarativeAnimatedImage, QDeclarativeImageBase, QDeclarativeLoader, QDeclarativeRepeater, QDeclarativeBasePositioner, QDeclarativeGestureArea, and ShaderEffectItem.
Definition at line 3212 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeItemPrivate::_states(), ShaderEffectItem::componentComplete(), QDeclarativeGestureArea::componentComplete(), QDeclarativeBasePositioner::componentComplete(), QDeclarativeRepeater::componentComplete(), QDeclarativeLoader::componentComplete(), QDeclarativeImageBase::componentComplete(), QDeclarativeAnimatedImage::componentComplete(), QDeclarativeText::componentComplete(), QDeclarativePathView::componentComplete(), QDeclarativeTextEdit::componentComplete(), QDeclarativeGridView::componentComplete(), QDeclarativeParticles::componentComplete(), QDeclarativeListView::componentComplete(), and QDeclarativeFlickablePrivate::data_append().
 {
     Q_D(QDeclarativeItem);
     d->componentComplete = true;
     if (d->_stateGroup)
         d->_stateGroup->componentComplete();
     if (d->_anchors) {
         d->_anchors->componentComplete();
         d->_anchors->d_func()->updateOnComplete();
     }
     if (d->keyHandler)
         d->keyHandler->componentComplete();
     if (d->_contents)
         d->_contents->complete();
 }
event()
bool QDeclarativeItem::event (QEvent * ev) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QObject.
Reimplemented in QDeclarativePinchArea, QDeclarativeTextEdit, QDeclarativeTextInput, QDeclarativeListView, QDeclarativeGridView, and QDeclarativePathView.
Definition at line 3987 of file qdeclarativeitem.cpp.
Referenced by QDeclarativePathView::event(), QDeclarativeGridView::event(), QDeclarativeListView::event(), QDeclarativeTextInput::event(), QDeclarativeTextEdit::event(), QDeclarativePinchArea::event(), sceneEvent(), and QDeclarativeFlickable::sendMouseEvent().
 {
     Q_D(QDeclarativeItem);
     switch (ev->type()) {
     case QEvent::KeyPress:
     case QEvent::KeyRelease:
     case QEvent::InputMethod:
         d->doneEventPreHandler = false;
         break;
     default:
         break;
     }
     return QGraphicsObject::event(ev);
 }
focusChanged
void QDeclarativeItem::focusChanged (bool) signal
Warning
This function is not part of the public interface.
forceActiveFocus()
void QDeclarativeItem::forceActiveFocus ()
Forces active focus on the item.
This method sets focus on the item and makes sure that all the focus scopes higher in the object hierarchy are also given the focus.
Definition at line 2940 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeTextInput::mousePressEvent(), and QDeclarativeTextEdit::mousePressEvent().
 {
     setFocus(true);
     QGraphicsItem *parent = parentItem();
     while (parent) {
         if (parent->flags() & QGraphicsItem::ItemIsFocusScope)
             parent->setFocus(Qt::OtherFocusReason);
         parent = parent->parentItem();
     }
 }
geometryChanged()
void QDeclarativeItem::geometryChanged (const QRectF & newGeometry, const QRectF & oldGeometry) protected virtual
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
If the two geometries are the same, it doesn't do anything.
Reimplemented in QDeclarativePinchArea, QDeclarativeTextEdit, QDeclarativeListView, QDeclarativeTextInput, QDeclarativeFlickable, QDeclarativeMouseArea, QDeclarativeText, ShaderEffectItem, QDeclarativeLoader, QDeclarativePaintedItem, and QDeclarativeImage.
Definition at line 2350 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeImage::geometryChanged(), QDeclarativePaintedItem::geometryChanged(), QDeclarativeLoader::geometryChanged(), ShaderEffectItem::geometryChanged(), QDeclarativeText::geometryChanged(), QDeclarativeMouseArea::geometryChanged(), QDeclarativeFlickable::geometryChanged(), QDeclarativePinchArea::geometryChanged(), setImplicitHeight(), setImplicitWidth(), and setSize().
 {
     Q_D(QDeclarativeItem);
     if (d->_anchors)
         d->_anchors->d_func()->updateMe();
     if (transformOrigin() != QDeclarativeItem::TopLeft
         && (newGeometry.width() != oldGeometry.width() || newGeometry.height() != oldGeometry.height())) {
         if (d->transformData) {
             QPointF origin = d->computeTransformOrigin();
             if (transformOriginPoint() != origin)
                 setTransformOriginPoint(origin);
         } else {
             d->transformOriginDirty = true;
         }
     }
     for(int ii = 0; ii < d->changeListeners.count(); ++ii) {
         const QDeclarativeItemPrivate::ChangeListener &change = d->changeListeners.at(ii);
         if (change.types & QDeclarativeItemPrivate::Geometry)
             change.listener->itemGeometryChanged(this, newGeometry, oldGeometry);
     }
     if (newGeometry.width() != oldGeometry.width())
         emit widthChanged();
     if (newGeometry.height() != oldGeometry.height())
         emit heightChanged();
 }
hasActiveFocus()
bool QDeclarativeItem::hasActiveFocus () const
Warning
This function is not part of the public interface.
Definition at line 3908 of file qdeclarativeitem.cpp.
Referenced by hasFocus(), QDeclarativeTextInput::mousePressEvent(), QDeclarativeTextEdit::mousePressEvent(), and sceneEvent().
 {
     Q_D(const QDeclarativeItem);
     QGraphicsItem *fi = focusItem();
     QGraphicsScene *s = scene();
     bool hasOrWillGainFocus = fi && fi->isVisible() && (!s || s->focusItem() == fi);
     bool isOrIsScopeOfFocusItem = (fi == this || (d->flags & QGraphicsItem::ItemIsFocusScope));
     return hasOrWillGainFocus && isOrIsScopeOfFocusItem;
 }
hasFocus()
bool QDeclarativeItem::hasFocus () const
Warning
This function is not part of the public interface.
Definition at line 3954 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeTextInputPrivate::focusChanged().
 {
     Q_D(const QDeclarativeItem);
     QGraphicsItem *p = d->parent;
     while (p) {
         if (p->flags() & QGraphicsItem::ItemIsFocusScope) {
             return p->focusScopeItem() == this;
         }
         p = p->parentItem();
     }
     return hasActiveFocus();
 }
height()
qreal QDeclarativeItem::height () const
Warning
This function is not part of the public interface. Return the height of the item
Definition at line 3696 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeText::boundingRect(), QDeclarativeContents::calcHeight(), QDeclarativeFlow::doPositioning(), QDeclarativeRectangle::drawRect(), QDeclarativeFlickable::geometryChanged(), QDeclarativeFlickable::maxYExtent(), QDeclarativeGridView::maxYExtent(), QDeclarativeListView::maxYExtent(), operator<<(), QDeclarativeImage::paint(), QDeclarativeRectangle::paint(), QDeclarativeText::paint(), QDeclarativePathView::sendMouseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativeFlickable::sendMouseEvent(), QDeclarativePinchArea::sendMouseEvent(), QDeclarativeFlickable::setContentHeight(), QDeclarativeItemPrivate::setHeight(), setImplicitHeight(), setImplicitWidth(), setSize(), QDeclarativeImageBase::setSourceSize(), QDeclarativeItemPrivate::setWidth(), QDeclarativeParentAnimation::transition(), ShaderEffectSource::updateBackbuffer(), ShaderEffectItem::updateGeometry(), QDeclarativePathViewPrivate::updateItem(), QDeclarativeImage::updatePaintedGeometry(), QDeclarativeTextEdit::updateSize(), QDeclarativeTextInput::updateSize(), ShaderEffectSource::updateSizeAndTexture(), QDeclarativeListViewPrivate::updateUnrequestedPositions(), QDeclarativeFlickableVisibleArea::updateVisible(), QDeclarativeFlickable::vHeight(), QDeclarativeFlickable::viewportMoved(), QDeclarativeListView::viewportMoved(), and QDeclarativeFlickable::yflick().
 {
     Q_D(const QDeclarativeItem);
     return d->height();
 }
heightValid()
bool QDeclarativeItem::heightValid () const protected
Returns whether the height property has been set explicitly.
Definition at line 3852 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeFlow::doPositioning(), QDeclarativeItemPrivate::resetHeight(), QDeclarativeItemPrivate::setHeight(), setImplicitHeight(), QDeclarativeImage::updatePaintedGeometry(), and QDeclarativeTextEdit::updateSize().
 {
     Q_D(const QDeclarativeItem);
     return d->heightValid;
 }
implicitHeight()
qreal QDeclarativeItem::implicitHeight () const
Referenced by QDeclarativeItemPrivate::implicitHeight().
implicitHeightChanged
void QDeclarativeItem::implicitHeightChanged () signal
Referenced by QDeclarativeImplicitSizePaintedItem::drawContents().
implicitWidth()
qreal QDeclarativeItem::implicitWidth () const
Referenced by QDeclarativeItemPrivate::implicitWidth().
implicitWidthChanged
void QDeclarativeItem::implicitWidthChanged () signal
Referenced by QDeclarativeImplicitSizePaintedItem::drawContents().
inputMethodEvent()
void QDeclarativeItem::inputMethodEvent (QInputMethodEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItem.
Reimplemented in QDeclarativeTextEdit, and QDeclarativeTextInput.
Definition at line 2414 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeTextInput::inputMethodEvent().
 {
     Q_D(QDeclarativeItem);
     inputMethodPreHandler(event);
     if (event->isAccepted())
         return;
     if (d->keyHandler)
         d->keyHandler->inputMethodEvent(event, true);
     else
         event->ignore();
 }
inputMethodPreHandler()
void QDeclarativeItem::inputMethodPreHandler (QInputMethodEvent * event) protected
Warning
This function is not part of the public interface.
Definition at line 2469 of file qdeclarativeitem.cpp.
Referenced by inputMethodEvent(), and QDeclarativeTextInput::inputMethodEvent().
 {
     Q_D(QDeclarativeItem);
     if (d->keyHandler && !d->doneEventPreHandler)
         d->keyHandler->inputMethodEvent(event, false);
     else
         event->ignore();
     d->doneEventPreHandler = true;
 }
inputMethodQuery()
QVariant QDeclarativeItem::inputMethodQuery (Qt::InputMethodQuery query) const protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItem.
Reimplemented in QDeclarativeTextInput, and QDeclarativeTextEdit.
Definition at line 2427 of file qdeclarativeitem.cpp.
 {
     Q_D(const QDeclarativeItem);
     QVariant v;
     if (d->keyHandler)
         v = d->keyHandler->inputMethodQuery(query);
     if (!v.isValid())
         v = QGraphicsObject::inputMethodQuery(query);
     return v;
 }
isComponentComplete()
bool QDeclarativeItem::isComponentComplete () const protected
Returns true if construction of the QML component is complete; otherwise returns false.
It is often desirable to delay some processing until the component is completed.
See also
componentComplete()
Definition at line 1984 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeRepeater::clear(), QDeclarativeRepeater::itemsInserted(), QDeclarativePathView::itemsInserted(), QDeclarativeGridView::itemsInserted(), QDeclarativeListView::itemsInserted(), QDeclarativeRepeater::itemsMoved(), QDeclarativePathView::itemsMoved(), QDeclarativeGridView::itemsMoved(), QDeclarativeListView::itemsMoved(), QDeclarativeRepeater::itemsRemoved(), QDeclarativePathView::itemsRemoved(), QDeclarativeGridView::itemsRemoved(), QDeclarativeListView::itemsRemoved(), QDeclarativeRepeater::modelReset(), QDeclarativeBasePositioner::prePositioning(), QDeclarativePathView::refill(), QDeclarativeRepeater::regenerate(), QDeclarativeText::resetHAlign(), QDeclarativeTextInput::resetHAlign(), QDeclarativeTextEdit::resetHAlign(), QDeclarativeImageBase::resetSourceSize(), QDeclarativeImageBase::setCache(), QDeclarativeGridView::setCacheBuffer(), QDeclarativeListView::setCacheBuffer(), QDeclarativePathView::setCurrentIndex(), QDeclarativeGridView::setCurrentIndex(), QDeclarativeListView::setCurrentIndex(), QDeclarativeGridView::setDelegate(), QDeclarativeListView::setDelegate(), QDeclarativeGridView::setFooter(), QDeclarativeListView::setFooter(), ShaderEffectItem::setFragmentShader(), QDeclarativeText::setHAlign(), QDeclarativeTextInput::setHAlign(), QDeclarativeTextEdit::setHAlign(), QDeclarativeGridView::setHeader(), QDeclarativeListView::setHeader(), QDeclarativeImageBase::setMirror(), QDeclarativePathView::setModel(), QDeclarativeGridView::setModel(), QDeclarativeListView::setModel(), QDeclarativePathView::setPath(), QDeclarativePathView::setPathItemCount(), QDeclarativeLoader::setSource(), QDeclarativeImageBase::setSource(), QDeclarativeBorderImage::setSource(), QDeclarativeAnimatedImage::setSource(), QDeclarativeLoader::setSourceComponent(), QDeclarativeImageBase::setSourceSize(), QDeclarativeText::setStyle(), QDeclarativeText::setText(), QDeclarativeText::setTextFormat(), QDeclarativeText::setVAlign(), ShaderEffectItem::setVertexShader(), QDeclarativeListView::updateSections(), and QDeclarativeTextEdit::updateSize().
 {
     Q_D(const QDeclarativeItem);
     return d->componentComplete;
 }
itemChange()
QVariant QDeclarativeItem::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
Warning
This function is not part of the public interface.
Items wishing to optimize start-up construction should instead consider using componentComplete().
Reimplemented from QGraphicsItem.
Reimplemented in QDeclarativePinchArea, QDeclarativeMouseArea, QDeclarativePaintedItem, QDeclarativeLoader, QDeclarativeRepeater, and QDeclarativeBasePositioner.
Definition at line 3326 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeBasePositioner::itemChange(), QDeclarativeLoader::itemChange(), QDeclarativeRepeater::itemChange(), QDeclarativePaintedItem::itemChange(), QDeclarativeMouseArea::itemChange(), and QDeclarativePinchArea::itemChange().
 {
     Q_D(QDeclarativeItem);
     switch (change) {
     case ItemParentHasChanged:
         d->resolveLayoutMirror();
         emit parentChanged(parentItem());
         d->parentNotifier.notify();
         break;
     case ItemVisibleHasChanged: {
             for(int ii = 0; ii < d->changeListeners.count(); ++ii) {
                 const QDeclarativeItemPrivate::ChangeListener &change = d->changeListeners.at(ii);
                 if (change.types & QDeclarativeItemPrivate::Visibility) {
                     change.listener->itemVisibilityChanged(this);
                 }
             }
         }
         break;
     case ItemOpacityHasChanged: {
             for(int ii = 0; ii < d->changeListeners.count(); ++ii) {
                 const QDeclarativeItemPrivate::ChangeListener &change = d->changeListeners.at(ii);
                 if (change.types & QDeclarativeItemPrivate::Opacity) {
                     change.listener->itemOpacityChanged(this);
                 }
             }
         }
         break;
     case ItemChildAddedChange:
         if (d->_contents && d->componentComplete)
             d->_contents->childAdded(qobject_cast<QDeclarativeItem*>(
                     value.value<QGraphicsItem*>()));
         break;
     case ItemChildRemovedChange:
         if (d->_contents && d->componentComplete)
             d->_contents->childRemoved(qobject_cast<QDeclarativeItem*>(
                     value.value<QGraphicsItem*>()));
         break;
     default:
         break;
     }
     return QGraphicsItem::itemChange(change, value);
 }
keepMouseGrab()
bool QDeclarativeItem::keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
See also
setKeepMouseGrab()
Definition at line 2796 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeMouseArea::mouseMoveEvent(), QDeclarativePathView::sendMouseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativeFlickable::sendMouseEvent(), and QDeclarativePinchArea::sendMouseEvent().
 {
     Q_D(const QDeclarativeItem);
     return d->keepMouse;
 }
keyPressEvent()
void QDeclarativeItem::keyPressEvent (QKeyEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItem.
Reimplemented in QDeclarativeTextEdit, QDeclarativeTextInput, QDeclarativeListView, and QDeclarativeGridView.
Definition at line 2388 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeGridView::keyPressEvent(), QDeclarativeListView::keyPressEvent(), QDeclarativeTextInput::keyPressEvent(), QDeclarativeTextEdit::keyPressEvent(), and sceneEvent().
 {
     Q_D(QDeclarativeItem);
     keyPressPreHandler(event);
     if (event->isAccepted())
         return;
     if (d->keyHandler)
         d->keyHandler->keyPressed(event, true);
     else
         event->ignore();
 }
keyPressPreHandler()
void QDeclarativeItem::keyPressPreHandler (QKeyEvent * event) protected
Warning
This function is not part of the public interface.
Definition at line 2443 of file qdeclarativeitem.cpp.
Referenced by keyPressEvent(), QDeclarativeGridView::keyPressEvent(), QDeclarativeListView::keyPressEvent(), QDeclarativeTextInput::keyPressEvent(), and QDeclarativeTextEdit::keyPressEvent().
 {
     Q_D(QDeclarativeItem);
     if (d->keyHandler && !d->doneEventPreHandler)
         d->keyHandler->keyPressed(event, false);
     else
         event->ignore();
     d->doneEventPreHandler = true;
 }
keyReleaseEvent()
void QDeclarativeItem::keyReleaseEvent (QKeyEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItem.
Reimplemented in QDeclarativeTextEdit.
Definition at line 2401 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeTextEdit::keyReleaseEvent().
 {
     Q_D(QDeclarativeItem);
     keyReleasePreHandler(event);
     if (event->isAccepted())
         return;
     if (d->keyHandler)
         d->keyHandler->keyReleased(event, true);
     else
         event->ignore();
 }
keyReleasePreHandler()
void QDeclarativeItem::keyReleasePreHandler (QKeyEvent * event) protected
Warning
This function is not part of the public interface.
Definition at line 2456 of file qdeclarativeitem.cpp.
Referenced by keyReleaseEvent(), and QDeclarativeTextEdit::keyReleaseEvent().
 {
     Q_D(QDeclarativeItem);
     if (d->keyHandler && !d->doneEventPreHandler)
         d->keyHandler->keyReleased(event, false);
     else
         event->ignore();
     d->doneEventPreHandler = true;
 }
mapFromItem()
QScriptValue QDeclarativeItem::mapFromItem (const QScriptValue & item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
If item is a null value, this maps the point from the coordinate system of the root QML view.
See also
Item::mapFromItem()
Definition at line 2850 of file qdeclarativeitem.cpp.
 {
     QDeclarativeItem *itemObj = qobject_cast<QDeclarativeItem*>(item.toQObject());
     if (!itemObj && !item.isNull()) {
         qmlInfo(this) << "mapFromItem() given argument \"" << item.toString() << "\" which is neither null nor an Item";
         return 0;
     }
     // If QGraphicsItem::mapFromItem() is called with 0, behaves the same as mapFromScene()
     QPointF p = qobject_cast<QGraphicsItem*>(this)->mapFromItem(itemObj, x, y);
     // Use the script engine from the passed item, if available. Use this item's one otherwise.
     QScriptEngine* const se = itemObj ? item.engine() : QDeclarativeEnginePrivate::getScriptEngine(qmlEngine(this));
     // Engine-less items are unlikely, but nevertheless possible. Handle them.
     if (0 == se)
         return QScriptValue(QScriptValue::UndefinedValue);
     QScriptValue sv = se->newObject();
     sv.setProperty(QLatin1String("x"), p.x());
     sv.setProperty(QLatin1String("y"), p.y());
     return sv;
 }
mapToItem()
QScriptValue QDeclarativeItem::mapToItem (const QScriptValue & item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
If item is a null value, this maps x and y to the coordinate system of the root QML view.
See also
Item::mapToItem()
Definition at line 2898 of file qdeclarativeitem.cpp.
 {
     QDeclarativeItem *itemObj = qobject_cast<QDeclarativeItem*>(item.toQObject());
     if (!itemObj && !item.isNull()) {
         qmlInfo(this) << "mapToItem() given argument \"" << item.toString() << "\" which is neither null nor an Item";
         return 0;
     }
     // If QGraphicsItem::mapToItem() is called with 0, behaves the same as mapToScene()
     QPointF p = qobject_cast<QGraphicsItem*>(this)->mapToItem(itemObj, x, y);
     // Use the script engine from the passed item, if available. Use this item's one otherwise.
     QScriptEngine* const se = itemObj ? item.engine() : QDeclarativeEnginePrivate::getScriptEngine(qmlEngine(this));
     // Engine-less items are unlikely, but nevertheless possible. Handle them.
     if (0 == se)
         return QScriptValue(QScriptValue::UndefinedValue);
     QScriptValue sv = se->newObject();
     sv.setProperty(QLatin1String("x"), p.x());
     sv.setProperty(QLatin1String("y"), p.y());
     return sv;
 }
paint()
void QDeclarativeItem::paint (QPainter * , const QStyleOptionGraphicsItem * , QWidget *) virtual
Warning
This function is not part of the public interface.
Implements QGraphicsItem.
Reimplemented in QDeclarativeParticlesPainter, QDeclarativeParticles, QDeclarativeText, QDeclarativeRectangle, QDeclarativePaintedItem, QDeclarativeBorderImage, QDeclarativeImage, and ShaderEffectItem.
Definition at line 3980 of file qdeclarativeitem.cpp.
 {
 }
parentChanged
void QDeclarativeItem::parentChanged (QDeclarativeItem *) signal
Warning
This function is not part of the public interface.
parentItem()
QDeclarativeItem * QDeclarativeItem::parentItem () const
Returns the QDeclarativeItem parent of this item.
Definition at line 1925 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeParentChangePrivate::doChange(), QDeclarativeItemPrivate::focusChanged(), forceActiveFocus(), QDeclarativeFlickablePrivate::isOutermostPressDelay(), itemChange(), QDeclarativeRepeater::itemsInserted(), QDeclarativeMouseArea::mouseMoveEvent(), operator<<(), QDeclarativeParticlesPainter::paint(), QDeclarativeItemPrivate::parentProperty(), QDeclarativeRepeater::regenerate(), QDeclarativeItemPrivate::resolveLayoutMirror(), ShaderEffectSource::setSourceItem(), QDeclarativeParticlesPainter::updateSize(), and ~QDeclarativeItem().
 {
     return qobject_cast<QDeclarativeItem *>(QGraphicsObject::parentItem());
 }
resetHeight()
void QDeclarativeItem::resetHeight ()
Warning
This function is not part of the public interface. Reset the height of the item
Definition at line 3716 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeItem);
     d->resetHeight();
 }
resetWidth()
void QDeclarativeItem::resetWidth ()
Warning
This function is not part of the public interface. Reset the width of the item
Definition at line 3589 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeItem);
     d->resetWidth();
 }
sceneEvent()
bool QDeclarativeItem::sceneEvent (QEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItem.
Reimplemented in QDeclarativePinchArea, QDeclarativeTextInput, QDeclarativeFlickable, QDeclarativeMouseArea, QDeclarativeGestureArea, and QDeclarativeFocusPanel.
Definition at line 3290 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeFocusPanel::sceneEvent(), QDeclarativeGestureArea::sceneEvent(), QDeclarativeMouseArea::sceneEvent(), QDeclarativeFlickable::sceneEvent(), QDeclarativeTextInput::sceneEvent(), and QDeclarativePinchArea::sceneEvent().
 {
     Q_D(QDeclarativeItem);
     if (event->type() == QEvent::KeyPress) {
         QKeyEvent *k = static_cast<QKeyEvent *>(event);
         if ((k->key() == Qt::Key_Tab || k->key() == Qt::Key_Backtab) &&
             !(k->modifiers() & (Qt::ControlModifier | Qt::AltModifier))) {
             keyPressEvent(static_cast<QKeyEvent *>(event));
             if (!event->isAccepted())
                 return QGraphicsItem::sceneEvent(event);
             else
                 return true;
         } else {
             return QGraphicsItem::sceneEvent(event);
         }
     } else {
         bool rv = QGraphicsItem::sceneEvent(event);
         if (event->type() == QEvent::FocusIn ||
             event->type() == QEvent::FocusOut) {
             d->focusChanged(hasActiveFocus());
         }
         return rv;
     }
 }
setBaselineOffset()
void QDeclarativeItem::setBaselineOffset (qreal offset)
Definition at line 2647 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeTextEdit::updateSize().
 {
     Q_D(QDeclarativeItem);
     if (offset == d->baselineOffset)
         return;
     d->baselineOffset = offset;
     for(int ii = 0; ii < d->changeListeners.count(); ++ii) {
         const QDeclarativeItemPrivate::ChangeListener &change = d->changeListeners.at(ii);
         if (change.types & QDeclarativeItemPrivate::Geometry) {
             QDeclarativeAnchorsPrivate *anchor = change.listener->anchorPrivate();
             if (anchor)
                 anchor->updateVerticalAnchors();
         }
     }
     emit baselineOffsetChanged(offset);
 }
setClip()
void QDeclarativeItem::setClip (bool c)
Definition at line 2211 of file qdeclarativeitem.cpp.
 {
     if (clip() == c)
         return;
     setFlag(ItemClipsChildrenToShape, c);
     emit clipChanged(c);
 }
setFocus()
void QDeclarativeItem::setFocus (bool focus)
Warning
This function is not part of the public interface.
Definition at line 3969 of file qdeclarativeitem.cpp.
Referenced by forceActiveFocus(), QDeclarativePathView::refill(), and QDeclarativeKeyNavigationAttached::setFocusNavigation().
 {
     if (focus)
         QGraphicsItem::setFocus(Qt::OtherFocusReason);
     else
         QGraphicsItem::clearFocus();
 }
setHeight()
void QDeclarativeItem::setHeight (qreal h)
Warning
This function is not part of the public interface. Set the height of the item
Definition at line 3706 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeLayoutItem::setGeometry(), and QDeclarativeParticlesPainter::updateSize().
 {
     Q_D(QDeclarativeItem);
     d->setHeight(h);
 }
setImplicitHeight()
void QDeclarativeItem::setImplicitHeight (qreal h) protected
Sets the implied height of the item to h.
This is the height implied by other properties that determine the content.
Definition at line 3826 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeBorderImage::load(), QDeclarativeImageBase::pixmapChange(), QDeclarativeBasePositioner::prePositioning(), QDeclarativeBorderImage::requestFinished(), QDeclarativeBorderImage::setGridScaledImage(), QDeclarativeImage::updatePaintedGeometry(), QDeclarativeTextEdit::updateSize(), and QDeclarativeTextInput::updateSize().
 {
     Q_D(QDeclarativeItem);
     bool changed = h != d->mImplicitHeight;
     d->mImplicitHeight = h;
     if (d->mHeight == h || heightValid()) {
         if (changed)
             d->implicitHeightChanged();
         return;
     }
     qreal oldHeight = d->mHeight;
     prepareGeometryChange();
     d->mHeight = h;
     geometryChanged(QRectF(x(), y(), width(), height()),
                     QRectF(x(), y(), width(), oldHeight));
     if (changed)
         d->implicitHeightChanged();
 }
setImplicitWidth()
void QDeclarativeItem::setImplicitWidth (qreal w) protected
Sets the implied width of the item to w.
This is the width implied by other properties that determine the content.
Definition at line 3660 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeBorderImage::load(), QDeclarativeImageBase::pixmapChange(), QDeclarativeBasePositioner::prePositioning(), QDeclarativeBorderImage::requestFinished(), QDeclarativeBorderImage::setGridScaledImage(), QDeclarativeImage::updatePaintedGeometry(), QDeclarativeTextEdit::updateSize(), and QDeclarativeTextInput::updateSize().
 {
     Q_D(QDeclarativeItem);
     bool changed = w != d->mImplicitWidth;
     d->mImplicitWidth = w;
     if (d->mWidth == w || widthValid()) {
         if (changed)
             d->implicitWidthChanged();
         return;
     }
     qreal oldWidth = d->mWidth;
     prepareGeometryChange();
     d->mWidth = w;
     geometryChanged(QRectF(x(), y(), width(), height()),
                     QRectF(x(), y(), oldWidth, height()));
     if (changed)
         d->implicitWidthChanged();
 }
setKeepMouseGrab()
void QDeclarativeItem::setKeepMouseGrab (bool keep)
The flag indicating whether the mouse should remain with this item is set to keep.
This is useful for items that wish to grab and keep mouse interaction following a predefined gesture. For example, an item that is interested in horizontal mouse movement may set keepMouseGrab to true once a threshold has been exceeded. Once keepMouseGrab has been set to true, filtering items will not react to mouse events.
If the item does not indicate that it wishes to retain mouse grab, a filtering item may steal the grab. For example, Flickable may attempt to steal a mouse grab if it detects that the user has begun to move the viewport.
See also
keepMouseGrab()
Definition at line 2820 of file qdeclarativeitem.cpp.
Referenced by QDeclarativePathView::mouseMoveEvent(), QDeclarativeMouseArea::mouseMoveEvent(), QDeclarativeTextInput::mouseMoveEvent(), QDeclarativeMouseArea::mousePressEvent(), QDeclarativeTextInput::mousePressEvent(), QDeclarativePinchArea::mousePressEvent(), QDeclarativeMouseArea::mouseReleaseEvent(), QDeclarativeTextInput::mouseReleaseEvent(), QDeclarativePinchArea::mouseReleaseEvent(), QDeclarativeMouseArea::sceneEvent(), QDeclarativeFlickable::sceneEvent(), QDeclarativeTextInput::sceneEvent(), QDeclarativePinchArea::sceneEvent(), QDeclarativePinchArea::sendMouseEvent(), QDeclarativeMouseArea::setPreventStealing(), QDeclarativeTextEdit::setSelectByMouse(), and QDeclarativePinchArea::updatePinch().
 {
     Q_D(QDeclarativeItem);
     d->keepMouse = keep;
 }
setParentItem()
void QDeclarativeItem::setParentItem (QDeclarativeItem * parent)
Definition at line 1917 of file qdeclarativeitem.cpp.
Referenced by QDeclarativePathView::createdItem(), QDeclarativeGridView::createdItem(), QDeclarativeListView::createdItem(), QDeclarativePathViewPrivate::createHighlight(), QDeclarativeGridViewPrivate::createHighlight(), QDeclarativeListViewPrivate::createHighlight(), QDeclarativeGridViewPrivate::createItem(), QDeclarativeListViewPrivate::createItem(), QDeclarativeListViewPrivate::createSection(), QDeclarativeParentChangePrivate::doChange(), QDeclarativePathViewPrivate::getItem(), QDeclarativeFlickablePrivate::init(), QDeclarativeRepeater::itemsInserted(), QDeclarativeRepeater::regenerate(), QmlJSDebugger::QDeclarativeViewInspector::reparentQmlObject(), ShaderEffectSource::setSourceItem(), QDeclarativeGridViewPrivate::updateFooter(), QDeclarativeListViewPrivate::updateFooter(), QDeclarativeGridViewPrivate::updateHeader(), and QDeclarativeListViewPrivate::updateHeader().
 {
     QGraphicsObject::setParentItem(parent);
 }
setSize()
void QDeclarativeItem::setSize (const QSizeF & size)
Warning
This function is not part of the public interface.
Definition at line 3859 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeItem);
     d->heightValid = true;
     d->widthValid = true;
     if (d->height() == size.height() && d->width() == size.width())
         return;
     qreal oldHeight = d->height();
     qreal oldWidth = d->width();
     prepareGeometryChange();
     d->setHeight(size.height());
     d->setWidth(size.width());
     geometryChanged(QRectF(x(), y(), width(), height()),
                     QRectF(x(), y(), oldWidth, oldHeight));
 }
setSmooth()
void QDeclarativeItem::setSmooth (bool smooth)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
See also
smooth()
Definition at line 3465 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeItem);
     if (d->smooth == smooth)
         return;
     d->smooth = smooth;
     emit smoothChanged(smooth);
     update();
 }
setTransformOrigin()
void QDeclarativeItem::setTransformOrigin (TransformOrigin origin)
Set the transform origin.
Definition at line 3409 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeItem);
     if (origin != d->origin) {
         d->origin = origin;
         if (d->transformData)
             QGraphicsItem::setTransformOriginPoint(d->computeTransformOrigin());
         else
             d->transformOriginDirty = true;
         emit transformOriginChanged(d->origin);
     }
 }
setWidth()
void QDeclarativeItem::setWidth (qreal w)
Warning
This function is not part of the public interface. Set the width of the item
Definition at line 3579 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeLayoutItem::setGeometry(), and QDeclarativeParticlesPainter::updateSize().
 {
     Q_D(QDeclarativeItem);
     d->setWidth(w);
 }
smooth()
bool QDeclarativeItem::smooth () const
Referenced by ShaderEffectSource::bind(), QDeclarativeTextEditPrivate::init(), QDeclarativeTextInputPrivate::init(), setSmooth(), and QDeclarativeItemPrivate::transformChanged().
smoothChanged
void QDeclarativeItem::smoothChanged (bool) signal
Warning
This function is not part of the public interface.
Referenced by setSmooth().
stateChanged
void QDeclarativeItem::stateChanged (const QString & state) signal
Warning
This function is not part of the public interface.
Referenced by QDeclarativeItemPrivate::_states(), QDeclarativeAnimatedImage::load(), and QDeclarativeAnimatedImage::movieRequestFinished().
transform()
QDeclarativeListProperty<QGraphicsTransform> QDeclarativeItem::transform ()
Referenced by QDeclarativeImage::paint(), and QDeclarativeItemPrivate::setState().
transformOrigin()
TransformOrigin QDeclarativeItem::transformOrigin () const
Referenced by boundingRect(), and geometryChanged().
transformOriginChanged
void QDeclarativeItem::transformOriginChanged (TransformOrigin) signal
Warning
This function is not part of the public interface.
Referenced by setTransformOrigin().
width()
qreal QDeclarativeItem::width () const
Warning
This function is not part of the public interface. Return the width of the item
Definition at line 3569 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeContents::calcWidth(), FxGridItem::colPos(), QDeclarativeListView::createdItem(), QDeclarativeRow::doPositioning(), QDeclarativeGrid::doPositioning(), QDeclarativeFlow::doPositioning(), QDeclarativeRectangle::drawRect(), QDeclarativeFlickable::geometryChanged(), QDeclarativeFlickable::maxXExtent(), QDeclarativeGridView::maxXExtent(), QDeclarativeListView::maxXExtent(), operator<<(), QDeclarativeImage::paint(), QDeclarativeRectangle::paint(), QDeclarativeText::paint(), QDeclarativePathView::sendMouseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativeFlickable::sendMouseEvent(), QDeclarativePinchArea::sendMouseEvent(), QDeclarativeFlickable::setContentWidth(), QDeclarativeItemPrivate::setHeight(), setImplicitHeight(), setImplicitWidth(), FxGridItem::setPosition(), setSize(), QDeclarativeImageBase::setSourceSize(), QDeclarativeItemPrivate::setWidth(), QDeclarativeParentAnimation::transition(), ShaderEffectSource::updateBackbuffer(), ShaderEffectItem::updateGeometry(), QDeclarativePathViewPrivate::updateItem(), QDeclarativeImage::updatePaintedGeometry(), QDeclarativeTextEdit::updateSize(), QDeclarativeTextInput::updateSize(), ShaderEffectSource::updateSizeAndTexture(), QDeclarativeGridViewPrivate::updateUnrequestedPositions(), QDeclarativeListViewPrivate::updateUnrequestedPositions(), QDeclarativeFlickableVisibleArea::updateVisible(), QDeclarativeFlickable::viewportMoved(), QDeclarativeListView::viewportMoved(), QDeclarativeFlickable::vWidth(), and QDeclarativeFlickable::xflick().
 {
     Q_D(const QDeclarativeItem);
     return d->width();
 }
widthValid()
bool QDeclarativeItem::widthValid () const protected
Returns whether the width property has been set explicitly.
Definition at line 3686 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeRow::doPositioning(), QDeclarativeGrid::doPositioning(), QDeclarativeFlow::doPositioning(), QDeclarativeText::geometryChanged(), QDeclarativeItemPrivate::resetWidth(), setImplicitWidth(), QDeclarativeItemPrivate::setWidth(), QDeclarativeImage::updatePaintedGeometry(), and QDeclarativeTextEdit::updateSize().
 {
     Q_D(const QDeclarativeItem);
     return d->widthValid;
 }
Properties
activeFocus
QDeclarativeItem::activeFocus private
Warning
This function is not part of the public interface.
Definition at line 90 of file qdeclarativeitem.h.
baselineOffset
qreal QDeclarativeItem::baselineOffset private
The position of the item's baseline in local coordinates.
The baseline of a Text item is the imaginary line on which the text sits. Controls containing text usually set their baseline to the baseline of their text.
For non-text items, a default baseline offset of 0 is used.
Definition at line 87 of file qdeclarativeitem.h.
childrenRect
QRectF QDeclarativeItem::childrenRect private
The geometry of an item's children.
This property holds the (collective) position and size of the item's children.
Definition at line 72 of file qdeclarativeitem.h.
clip
QDeclarativeItem::clip private
This property holds whether clipping is enabled.
The default clip value is false.
If clipping is enabled, an item will clip its own painting, as well as the painting of its children, to its bounding rectangle. If you set clipping during an item's paint operation, remember to re-set it to prevent clipping the rest of your scene.
Non-rectangular clipping regions are not supported for performance reasons.
Definition at line 88 of file qdeclarativeitem.h.
focus
QDeclarativeItem::focus private
Warning
This function is not part of the public interface.
Definition at line 89 of file qdeclarativeitem.h.
implicitHeight
qreal QDeclarativeItem::implicitHeight private
Returns the height of the item that is implied by other properties that determine the content.
Definition at line 96 of file qdeclarativeitem.h.
implicitWidth
qreal QDeclarativeItem::implicitWidth private
Returns the width of the item that is implied by other properties that determine the content.
Definition at line 95 of file qdeclarativeitem.h.
smooth
bool QDeclarativeItem::smooth private
whether the item is smoothly transformed.
Returns true if the item should be drawn with antialiasing and smooth pixmap filtering, false otherwise.
This property is provided purely for the purpose of optimization. Turning smooth transforms off is faster, but looks worse; turning smooth transformations on is slower, but looks better.
By default smooth transformations are off.
The default is false.
See also
setSmooth()
Definition at line 94 of file qdeclarativeitem.h.
transform
QDeclarativeItem::transform private
Warning
This function is not part of the public interface.
Definition at line 91 of file qdeclarativeitem.h.
transformOrigin
QDeclarativeItem::transformOrigin private
Returns the current transform origin.
Warning
This function is not part of the public interface.
Definition at line 92 of file qdeclarativeitem.h.
Referenced by QDeclarativeParentChangePrivate::doChange(), and QDeclarativeParentAnimation::transition().
transformOriginPoint
QDeclarativeItem::transformOriginPoint private
Warning
This function is not part of the public interface.
Definition at line 93 of file qdeclarativeitem.h.
Referenced by QDeclarativeParentChangePrivate::doChange().
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativeitem.h
/src/declarative/graphicsitems/qdeclarativeitem.cpp