Qt 4.8: QGraphicsOpacityEffect Class Reference
QGraphicsOpacityEffect Class Reference
The QGraphicsOpacityEffect class provides an opacity effect.
#include <qgraphicseffect.h>
Public Slots
void setOpacity (qreal opacity)
void setOpacityMask (const QBrush &mask)
Public Slots inherited from QGraphicsEffect
void setEnabled (bool enable)
void update ()
Schedules a redraw of the effect.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void opacityChanged (qreal opacity)
This signal is emitted whenever the effect's opacity changes.
void opacityMaskChanged (const QBrush &mask)
This signal is emitted whenever the effect's opacity mask changes.
Signals inherited from QGraphicsEffect
void enabledChanged (bool enabled)
This signal is emitted whenever the effect is enabled or disabled.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
qreal opacity () const
QBrush opacityMask () const
QGraphicsOpacityEffect (QObject *parent=0)
Constructs a new QGraphicsOpacityEffect instance.
~QGraphicsOpacityEffect ()
Destroys the effect.
Public Functions inherited from QGraphicsEffect
QRectF boundingRect () const
Returns the effective bounding rectangle for this effect, i.e., the bounding rectangle of the source in device coordinates, adjusted by any margins applied by the effect itself.
virtual QRectF boundingRectFor (const QRectF &sourceRect) const
Returns the effective bounding rectangle for this effect, given the provided rect in the device coordinates.
bool isEnabled () const
QGraphicsEffect (QObject *parent=0)
Constructs a new QGraphicsEffect instance having the specified parent.
QGraphicsEffectSource * source () const
Returns a pointer to the source, which provides extra context information that can be useful for the effect.
virtual ~QGraphicsEffect ()
Removes the effect from the source, and destroys the graphics effect.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void draw (QPainter *painter)
Reimplemented Function
Protected Functions inherited from QGraphicsEffect
void drawSource (QPainter *painter)
Draws the source directly using the given painter.
QGraphicsEffect (QGraphicsEffectPrivate &d, QObject *parent=0)
QRectF sourceBoundingRect (Qt::CoordinateSystem system=Qt::LogicalCoordinates) const
Returns the bounding rectangle of the source mapped to the given system.
virtual void sourceChanged (ChangeFlags flags)
This virtual function is called by QGraphicsEffect to notify the effect that the source has changed.
bool sourceIsPixmap () const
Returns true if the source effectively is a pixmap, e.g., a QGraphicsPixmapItem.
QPixmap sourcePixmap (Qt::CoordinateSystem system=Qt::LogicalCoordinates, QPoint *offset=0, PixmapPadMode mode=PadToEffectiveBoundingRect) const
Returns a pixmap with the source painted into it.
void updateBoundingRect ()
This function notifies the effect framework when the effect's bounding rectangle has changed.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
qreal opacity
the opacity of the effect.
QBrush opacityMask
the opacity mask of the effect.
Additional Inherited Members
Public Types inherited from QGraphicsEffect
enum ChangeFlag { SourceAttached = 0x1, SourceDetached = 0x2, SourceBoundingRectChanged = 0x4, SourceInvalidated = 0x8 }
This enum describes what has changed in QGraphicsEffectSource.
enum PixmapPadMode { NoPad, PadToTransparentBorder, PadToEffectiveBoundingRect }
This enum describes how the pixmap returned from sourcePixmap should be padded.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGraphicsOpacityEffect class provides an opacity effect.
Since
4.6
An opacity effect renders the source with an opacity. This effect is useful for making the source semi-transparent, similar to a fade-in/fade-out sequence. The opacity can be modified using the setOpacity() function.
By default, the opacity is 0.7.
See also
QGraphicsDropShadowEffect, QGraphicsBlurEffect, QGraphicsColorizeEffect
Definition at line 255 of file qgraphicseffect.h.
Constructors and Destructors
QGraphicsOpacityEffect()
QGraphicsOpacityEffect::QGraphicsOpacityEffect (QObject * parent = 0)
Constructs a new QGraphicsOpacityEffect instance.
The parent parameter is passed to QGraphicsEffect's constructor.
Definition at line 1175 of file qgraphicseffect.cpp.
     : QGraphicsEffect(*new QGraphicsOpacityEffectPrivate, parent)
 {
 }
~QGraphicsOpacityEffect()
QGraphicsOpacityEffect::~QGraphicsOpacityEffect ()
Destroys the effect.
Definition at line 1183 of file qgraphicseffect.cpp.
 {
 }
Functions
draw()
void QGraphicsOpacityEffect::draw (QPainter * painter) protected virtual
Reimplemented Function
Implements QGraphicsEffect.
Definition at line 1283 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsOpacityEffect);
     // Transparent; nothing to draw.
     if (d->isFullyTransparent)
         return;
     // Opaque; draw directly without going through a pixmap.
     if (d->isFullyOpaque && !d->hasOpacityMask) {
         drawSource(painter);
         return;
     }
     QPoint offset;
     Qt::CoordinateSystem system = sourceIsPixmap() ? Qt::LogicalCoordinates : Qt::DeviceCoordinates;
     QPixmap pixmap = sourcePixmap(system, &offset, QGraphicsEffect::NoPad);
     if (pixmap.isNull())
         return;
     painter->save();
     painter->setOpacity(d->opacity);
     if (d->hasOpacityMask) {
         QPainter pixmapPainter(&pixmap);
         pixmapPainter.setRenderHints(painter->renderHints());
         pixmapPainter.setCompositionMode(QPainter::CompositionMode_DestinationIn);
         if (system == Qt::DeviceCoordinates) {
             QTransform worldTransform = painter->worldTransform();
             worldTransform *= QTransform::fromTranslate(-offset.x(), -offset.y());
             pixmapPainter.setWorldTransform(worldTransform);
             pixmapPainter.fillRect(sourceBoundingRect(), d->opacityMask);
         } else {
             pixmapPainter.translate(-offset);
             pixmapPainter.fillRect(pixmap.rect(), d->opacityMask);
         }
     }
     if (system == Qt::DeviceCoordinates)
         painter->setWorldTransform(QTransform());
     painter->drawPixmap(offset, pixmap);
     painter->restore();
 }
opacity()
qreal QGraphicsOpacityEffect::opacity () const
Referenced by setOpacity(), and ~QGraphicsOpacityEffect().
opacityChanged
void QGraphicsOpacityEffect::opacityChanged (qreal opacity) signal
This signal is emitted whenever the effect's opacity changes.
The opacity parameter holds the effect's new opacity.
Referenced by setOpacity().
opacityMask()
QBrush QGraphicsOpacityEffect::opacityMask () const
Referenced by setOpacity().
opacityMaskChanged
void QGraphicsOpacityEffect::opacityMaskChanged (const QBrush & mask) signal
This signal is emitted whenever the effect's opacity mask changes.
The mask parameter holds the effect's new opacity mask.
Referenced by setOpacityMask().
setOpacity
void QGraphicsOpacityEffect::setOpacity (qreal opacity) slot
Definition at line 1207 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsOpacityEffect);
     opacity = qBound(qreal(0.0), opacity, qreal(1.0));
     if (qFuzzyCompare(d->opacity, opacity))
         return;
     d->opacity = opacity;
     if ((d->isFullyTransparent = qFuzzyIsNull(d->opacity)))
         d->isFullyOpaque = 0;
     else
         d->isFullyOpaque = qFuzzyIsNull(d->opacity - 1);
     update();
     emit opacityChanged(opacity);
 }
setOpacityMask
void QGraphicsOpacityEffect::setOpacityMask (const QBrush & mask) slot
Definition at line 1257 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsOpacityEffect);
     if (d->opacityMask == mask)
         return;
     d->opacityMask = mask;
     d->hasOpacityMask = (mask.style() != Qt::NoBrush);
     update();
     emit opacityMaskChanged(mask);
 }
Properties
opacity
qreal QGraphicsOpacityEffect::opacity private
the opacity of the effect.
The value should be in the range of 0.0 to 1.0, where 0.0 is fully transparent and 1.0 is fully opaque.
By default, the opacity is 0.7.
See also
setOpacityMask()
Definition at line 258 of file qgraphicseffect.h.
opacityMask
QBrush QGraphicsOpacityEffect::opacityMask private
the opacity mask of the effect.
An opacity mask allows you apply opacity to portions of an element.
For example:
...
QLinearGradient alphaGradient(rect.topLeft(), rect.bottomLeft());
alphaGradient.setColorAt(0.0, Qt::transparent);
alphaGradient.setColorAt(0.5, Qt::black);
alphaGradient.setColorAt(1.0, Qt::transparent);
QGraphicsOpacityEffect *effect = new QGraphicsOpacityEffect;
effect->setOpacityMask(alphaGradient);
...
There is no opacity mask by default.
See also
setOpacity()
Definition at line 259 of file qgraphicseffect.h.
The documentation for this class was generated from the following files:
/src/gui/effects/qgraphicseffect.h
/src/gui/effects/qgraphicseffect.cpp