Qt 4.8: QSequentialAnimationGroup Class Reference
QSequentialAnimationGroup Class Reference
The QSequentialAnimationGroup class provides a sequential group of animations.
#include <qsequentialanimationgroup.h>
Signals
void currentAnimationChanged (QAbstractAnimation *current)
QSequentialAnimationGroup emits this signal when currentAnimation has been changed.
Signals inherited from QAbstractAnimation
void currentLoopChanged (int currentLoop)
QAbstractAnimation emits this signal whenever the current loop changes.
void directionChanged (QAbstractAnimation::Direction)
QAbstractAnimation emits this signal whenever the direction has been changed.
void finished ()
QAbstractAnimation emits this signal after the animation has stopped and has reached the end.
void stateChanged (QAbstractAnimation::State newState, QAbstractAnimation::State oldState)
QAbstractAnimation emits this signal whenever the state of the animation has changed from oldState to newState.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QPauseAnimation * addPause (int msecs)
Adds a pause of msecs to this animation group.
QAbstractAnimation * currentAnimation () const
int duration () const
Reimplemented Function
QPauseAnimation * insertPause (int index, int msecs)
Inserts a pause of msecs milliseconds at index in this animation group.
QSequentialAnimationGroup (QObject *parent=0)
Constructs a QSequentialAnimationGroup.
~QSequentialAnimationGroup ()
Destroys the animation group.
Public Functions inherited from QAnimationGroup
void addAnimation (QAbstractAnimation *animation)
Adds animation to this group.
QAbstractAnimation * animationAt (int index) const
Returns a pointer to the animation at index in this group.
int animationCount () const
Returns the number of animations managed by this group.
void clear ()
Removes and deletes all animations in this animation group, and resets the current time to 0.
int indexOfAnimation (QAbstractAnimation *animation) const
Returns the index of animation.
void insertAnimation (int index, QAbstractAnimation *animation)
Inserts animation into this animation group at index.
QAnimationGroup (QObject *parent=0)
Constructs a QAnimationGroup.
void removeAnimation (QAbstractAnimation *animation)
Removes animation from this group.
QAbstractAnimation * takeAnimation (int index)
Returns the animation at index and removes it from the animation group.
~QAnimationGroup ()
Destroys the animation group.
Public Functions inherited from QAbstractAnimation
int currentLoop () const
int currentLoopTime () const
Returns the current time inside the current loop.
int currentTime () const
Direction direction () const
QAnimationGroup * group () const
If this animation is part of a QAnimationGroup, this function returns a pointer to the group; otherwise, it returns 0.
int loopCount () const
QAbstractAnimation (QObject *parent=0)
Constructs the QAbstractAnimation base class, and passes parent to QObject's constructor.
void setDirection (Direction direction)
void setLoopCount (int loopCount)
State state () const
int totalDuration () const
Returns the total and effective duration of the animation, including the loop count.
virtual ~QAbstractAnimation ()
Stops the animation if it's running, then destroys the QAbstractAnimation.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *event)
Reimplemented Function
QSequentialAnimationGroup (QSequentialAnimationGroupPrivate &dd, QObject *parent)
void updateCurrentTime (int)
Reimplemented Function
void updateDirection (QAbstractAnimation::Direction direction)
Reimplemented Function
void updateState (QAbstractAnimation::State newState, QAbstractAnimation::State oldState)
Reimplemented Function
Protected Functions inherited from QAnimationGroup
QAnimationGroup (QAnimationGroupPrivate &dd, QObject *parent)
Protected Functions inherited from QAbstractAnimation
QAbstractAnimation (QAbstractAnimationPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
QAbstractAnimation * currentAnimation
Returns the animation in the current time.
Additional Inherited Members
Public Types inherited from QAbstractAnimation
enum DeletionPolicy { KeepWhenStopped = 0, DeleteWhenStopped }
enum Direction { Forward, Backward }
This enum describes the direction of the animation when in Running state.
enum State { Stopped, Paused, Running }
This enum describes the state of the animation.
Public Slots inherited from QAbstractAnimation
void pause ()
Pauses the animation.
void resume ()
Resumes the animation after it was paused.
void setCurrentTime (int msecs)
void setPaused (bool)
If paused is true, the animation is paused.
void start (QAbstractAnimation::DeletionPolicy policy=KeepWhenStopped)
Starts the animation.
void stop ()
Stops the animation.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSequentialAnimationGroup class provides a sequential group of animations.
Since
4.6
QSequentialAnimationGroup is a QAnimationGroup that runs its animations in sequence, i.e., it starts one animation after another has finished playing. The animations are played in the order they are added to the group (using QAnimationGroup::addAnimation() or QAnimationGroup::insertAnimation()). The animation group finishes when its last animation has finished.
At each moment there is at most one animation that is active in the group; it is returned by currentAnimation(). An empty group has no current animation.
A sequential animation group can be treated as any other animation, i.e., it can be started, stopped, and added to other groups. You can also call addPause() or insertPause() to add a pause to a sequential animation group.
QSequentialAnimationGroup *group = new QSequentialAnimationGroup;
group->addAnimation(anim1);
group->addAnimation(anim2);
group->start();
In this example, anim1 and anim2 are two already set up QPropertyAnimation.
See also
QAnimationGroup, QAbstractAnimation, {The Animation Framework}
Definition at line 58 of file qsequentialanimationgroup.h.
Constructors and Destructors
QSequentialAnimationGroup() [1/2]
QSequentialAnimationGroup::QSequentialAnimationGroup (QObject * parent = 0)
Constructs a QSequentialAnimationGroup.
parent is passed to QObject's constructor.
Definition at line 254 of file qsequentialanimationgroup.cpp.
     : QAnimationGroup(*new QSequentialAnimationGroupPrivate, parent)
 {
 }
~QSequentialAnimationGroup()
QSequentialAnimationGroup::~QSequentialAnimationGroup ()
Destroys the animation group.
It will also destroy all its animations.
Definition at line 271 of file qsequentialanimationgroup.cpp.
 {
 }
QSequentialAnimationGroup() [2/2]
QSequentialAnimationGroup::QSequentialAnimationGroup (QSequentialAnimationGroupPrivate & dd, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 262 of file qsequentialanimationgroup.cpp.
     : QAnimationGroup(dd, parent)
 {
 }
Functions
addPause()
QPauseAnimation * QSequentialAnimationGroup::addPause (int msecs)
Adds a pause of msecs to this animation group.
The pause is considered as a special type of animation, thus animationCount will be increased by one.
See also
insertPause(), QAnimationGroup::addAnimation()
Definition at line 283 of file qsequentialanimationgroup.cpp.
 {
     QPauseAnimation *pause = new QPauseAnimation(msecs);
     addAnimation(pause);
     return pause;
 }
currentAnimation()
QAbstractAnimation* QSequentialAnimationGroup::currentAnimation () const
Referenced by QSequentialAnimationGroupPrivate::_q_uncontrolledAnimationFinished(), QSequentialAnimationGroupPrivate::activateCurrentAnimation(), QSequentialAnimationGroupPrivate::animationInsertedAt(), QSequentialAnimationGroupPrivate::animationRemoved(), insertPause(), and QSequentialAnimationGroupPrivate::setCurrentAnimation().
currentAnimationChanged
QSequentialAnimationGroup::currentAnimationChanged (QAbstractAnimation * current) signal
QSequentialAnimationGroup emits this signal when currentAnimation has been changed.
current is the current animation.
See also
currentAnimation()
duration()
int QSequentialAnimationGroup::duration () const virtual
Reimplemented Function
Implements QAbstractAnimation.
Definition at line 329 of file qsequentialanimationgroup.cpp.
 {
     Q_D(const QSequentialAnimationGroup);
     int ret = 0;
     for (int i = 0; i < d->animations.size(); ++i) {
         QAbstractAnimation *animation = d->animations.at(i);
         const int currentDuration = animation->totalDuration();
         if (currentDuration == -1)
             return -1; // Undetermined length
         ret += currentDuration;
     }
     return ret;
 }
event()
bool QSequentialAnimationGroup::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAnimationGroup.
Definition at line 442 of file qsequentialanimationgroup.cpp.
 {
     return QAnimationGroup::event(event);
 }
insertPause()
QPauseAnimation * QSequentialAnimationGroup::insertPause (int index, int msecs)
Inserts a pause of msecs milliseconds at index in this animation group.
See also
addPause(), QAnimationGroup::insertAnimation()
Definition at line 296 of file qsequentialanimationgroup.cpp.
 {
     Q_D(const QSequentialAnimationGroup);
     if (index < 0 || index > d->animations.size()) {
         qWarning("QSequentialAnimationGroup::insertPause: index is out of bounds");
         return 0;
     }
     QPauseAnimation *pause = new QPauseAnimation(msecs);
     insertAnimation(index, pause);
     return pause;
 }
updateCurrentTime()
void QSequentialAnimationGroup::updateCurrentTime (int currentTime) protected virtual
Reimplemented Function
Implements QAbstractAnimation.
Definition at line 349 of file qsequentialanimationgroup.cpp.
 {
     Q_D(QSequentialAnimationGroup);
     if (!d->currentAnimation)
         return;
     const QSequentialAnimationGroupPrivate::AnimationIndex newAnimationIndex = d->indexForCurrentTime();
     // remove unneeded animations from actualDuration list
     while (newAnimationIndex.index < d->actualDuration.size())
         d->actualDuration.removeLast();
     // newAnimationIndex.index is the new current animation
     if (d->lastLoop < d->currentLoop
         || (d->lastLoop == d->currentLoop && d->currentAnimationIndex < newAnimationIndex.index)) {
             // advancing with forward direction is the same as rewinding with backwards direction
             d->advanceForwards(newAnimationIndex);
     } else if (d->lastLoop > d->currentLoop
         || (d->lastLoop == d->currentLoop && d->currentAnimationIndex > newAnimationIndex.index)) {
             // rewinding with forward direction is the same as advancing with backwards direction
             d->rewindForwards(newAnimationIndex);
     }
     d->setCurrentAnimation(newAnimationIndex.index);
     const int newCurrentTime = currentTime - newAnimationIndex.timeOffset;
     if (d->currentAnimation) {
         d->currentAnimation->setCurrentTime(newCurrentTime);
         if (d->atEnd()) {
             //we make sure that we don't exceed the duration here
             d->currentTime += QAbstractAnimationPrivate::get(d->currentAnimation)->totalCurrentTime - newCurrentTime;
             stop();
         }
     } else {
         //the only case where currentAnimation could be null
         //is when all animations have been removed
         Q_ASSERT(d->animations.isEmpty());
         d->currentTime = 0;
         stop();
     }
     d->lastLoop = d->currentLoop;
 }
updateDirection()
void QSequentialAnimationGroup::updateDirection (QAbstractAnimation::Direction direction) protected virtual
Reimplemented Function
Reimplemented from QAbstractAnimation.
Definition at line 431 of file qsequentialanimationgroup.cpp.
 {
     Q_D(QSequentialAnimationGroup);
     // we need to update the direction of the current animation
     if (state() != Stopped && d->currentAnimation)
         d->currentAnimation->setDirection(direction);
 }
updateState()
void QSequentialAnimationGroup::updateState (QAbstractAnimation::State newState, QAbstractAnimation::State oldState) protected virtual
Reimplemented Function
Reimplemented from QAbstractAnimation.
Definition at line 397 of file qsequentialanimationgroup.cpp.
 {
     Q_D(QSequentialAnimationGroup);
     QAnimationGroup::updateState(newState, oldState);
     if (!d->currentAnimation)
         return;
     switch (newState) {
     case Stopped:
         d->currentAnimation->stop();
         break;
     case Paused:
         if (oldState == d->currentAnimation->state()
             && oldState == QSequentialAnimationGroup::Running) {
                 d->currentAnimation->pause();
             }
         else
             d->restart();
         break;
     case Running:
         if (oldState == d->currentAnimation->state()
             && oldState == QSequentialAnimationGroup::Paused)
             d->currentAnimation->start();
         else
             d->restart();
         break;
     }
 }
Properties
currentAnimation
QAbstractAnimation * QSequentialAnimationGroup::currentAnimation private
Returns the animation in the current time.
See also
currentAnimationChanged()
Definition at line 61 of file qsequentialanimationgroup.h.
The documentation for this class was generated from the following files:
/src/corelib/animation/qsequentialanimationgroup.h
/src/corelib/animation/qsequentialanimationgroup.cpp