Qt 4.8: QUndoGroup Class Reference
QUndoGroup Class Reference
The QUndoGroup class is a group of QUndoStack objects.
#include <qundogroup.h>
Public Slots
void redo ()
Calls QUndoStack::redo() on the active stack.
void setActiveStack (QUndoStack *stack)
Sets the active stack of this group to stack.
void undo ()
Calls QUndoStack::undo() on the active stack.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void activeStackChanged (QUndoStack *stack)
This signal is emitted whenever the active stack of the group changes.
void canRedoChanged (bool canRedo)
This signal is emitted whenever the active stack emits QUndoStack::canRedoChanged() or the active stack changes.
void canUndoChanged (bool canUndo)
This signal is emitted whenever the active stack emits QUndoStack::canUndoChanged() or the active stack changes.
void cleanChanged (bool clean)
This signal is emitted whenever the active stack emits QUndoStack::cleanChanged() or the active stack changes.
void indexChanged (int idx)
This signal is emitted whenever the active stack emits QUndoStack::indexChanged() or the active stack changes.
void redoTextChanged (const QString &redoText)
This signal is emitted whenever the active stack emits QUndoStack::redoTextChanged() or the active stack changes.
void undoTextChanged (const QString &undoText)
This signal is emitted whenever the active stack emits QUndoStack::undoTextChanged() or the active stack changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QUndoStack * activeStack () const
Returns the active stack of this group.
void addStack (QUndoStack *stack)
Adds stack to this group.
bool canRedo () const
Returns the value of the active stack's QUndoStack::canRedo().
bool canUndo () const
Returns the value of the active stack's QUndoStack::canUndo().
QAction * createRedoAction (QObject *parent, const QString &prefix=QString()) const
Creates an redo QAction object with parent parent.
QAction * createUndoAction (QObject *parent, const QString &prefix=QString()) const
Creates an undo QAction object with parent parent.
bool isClean () const
Returns the value of the active stack's QUndoStack::isClean().
QUndoGroup (QObject *parent=0)
Creates an empty QUndoGroup object with parent parent.
QString redoText () const
Returns the value of the active stack's QUndoStack::redoText().
void removeStack (QUndoStack *stack)
Removes stack from this group.
QList< QUndoStack * > stacks () const
Returns a list of stacks in this group.
QString undoText () const
Returns the value of the active stack's QUndoStack::undoText().
~QUndoGroup ()
Destroys the QUndoGroup.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QUndoGroup class is a group of QUndoStack objects.
Since
4.2
For an overview of the Qt's undo framework, see the overview.
An application often has multiple undo stacks, one for each opened document. At the same time, an application usually has one undo action and one redo action, which triggers undo or redo in the active document.
QUndoGroup is a group of QUndoStack objects, one of which may be active. It has an undo() and redo() slot, which calls QUndoStack::undo() and QUndoStack::redo() for the active stack. It also has the functions createUndoAction() and createRedoAction(). The actions returned by these functions behave in the same way as those returned by QUndoStack::createUndoAction() and QUndoStack::createRedoAction() of the active stack.
Stacks are added to a group with addStack() and removed with removeStack(). A stack is implicitly added to a group when it is created with the group as its parent QObject.
It is the programmer's responsibility to specify which stack is active by calling QUndoStack::setActive(), usually when the associated document window receives focus. The active stack may also be set with setActiveStack(), and is returned by activeStack().
When a stack is added to a group using addStack(), the group does not take ownership of the stack. This means the stack has to be deleted separately from the group. When a stack is deleted, it is automatically removed from a group. A stack may belong to only one group. Adding it to another group will cause it to be removed from the previous group.
A QUndoGroup is also useful in conjunction with QUndoView. If a QUndoView is set to watch a group using QUndoView::setGroup(), it will update itself to display the active stack.
Definition at line 60 of file qundogroup.h.
Constructors and Destructors
QUndoGroup()
QUndoGroup::QUndoGroup (QObject * parent = 0) explicit
Creates an empty QUndoGroup object with parent parent.
See also
addStack()
Definition at line 106 of file qundogroup.cpp.
     : QObject(*new QUndoGroupPrivate(), parent)
 {
 }
~QUndoGroup()
QUndoGroup::~QUndoGroup ()
Destroys the QUndoGroup.
Definition at line 114 of file qundogroup.cpp.
 {
     // Ensure all QUndoStacks no longer refer to this group.
     Q_D(QUndoGroup);
     QList<QUndoStack *>::iterator it = d->stack_list.begin();
     QList<QUndoStack *>::iterator end = d->stack_list.end();
     while (it != end) {
         (*it)->d_func()->group = 0;
         ++it;
     }
 }
Functions
activeStack()
QUndoStack * QUndoGroup::activeStack () const
Returns the active stack of this group.
If none of the stacks are active, or if the group is empty, this function returns 0.
See also
setActiveStack() QUndoStack::setActive()
Definition at line 255 of file qundogroup.cpp.
 {
     Q_D(const QUndoGroup);
     return d->active;
 }
activeStackChanged
void QUndoGroup::activeStackChanged (QUndoStack * stack) signal
This signal is emitted whenever the active stack of the group changes.
This can happen when setActiveStack() or QUndoStack::setActive() is called, or when the active stack is removed form the group. stack is the new active stack. If no stack is active, stack is 0.
See also
setActiveStack() QUndoStack::setActive()
Referenced by setActiveStack().
addStack()
void QUndoGroup::addStack (QUndoStack * stack)
Adds stack to this group.
The group does not take ownership of the stack. Another way of adding a stack to a group is by specifying the group as the stack's parent QObject in QUndoStack::QUndoStack(). In this case, the stack is deleted when the group is deleted, in the usual manner of QObjects.
See also
removeStack() stacks() QUndoStack::QUndoStack()
Definition at line 135 of file qundogroup.cpp.
 {
     Q_D(QUndoGroup);
     if (d->stack_list.contains(stack))
         return;
     d->stack_list.append(stack);
     if (QUndoGroup *other = stack->d_func()->group)
         other->removeStack(stack);
     stack->d_func()->group = this;
 }
canRedo()
bool QUndoGroup::canRedo () const
Returns the value of the active stack's QUndoStack::canRedo().
If none of the stacks are active, or if the group is empty, this function returns false.
See also
canUndo() setActiveStack()
Definition at line 318 of file qundogroup.cpp.
Referenced by createRedoAction().
 {
     Q_D(const QUndoGroup);
     return d->active != 0 && d->active->canRedo();
 }
canRedoChanged
void QUndoGroup::canRedoChanged (bool canRedo) signal
This signal is emitted whenever the active stack emits QUndoStack::canRedoChanged() or the active stack changes.
canRedo is the new state, or false if the active stack is 0.
See also
QUndoStack::canRedoChanged() setActiveStack()
Referenced by createRedoAction(), and setActiveStack().
canUndo()
bool QUndoGroup::canUndo () const
Returns the value of the active stack's QUndoStack::canUndo().
If none of the stacks are active, or if the group is empty, this function returns false.
See also
canRedo() setActiveStack()
Definition at line 303 of file qundogroup.cpp.
Referenced by createUndoAction().
 {
     Q_D(const QUndoGroup);
     return d->active != 0 && d->active->canUndo();
 }
canUndoChanged
void QUndoGroup::canUndoChanged (bool canUndo) signal
This signal is emitted whenever the active stack emits QUndoStack::canUndoChanged() or the active stack changes.
canUndo is the new state, or false if the active stack is 0.
See also
QUndoStack::canUndoChanged() setActiveStack()
Referenced by createUndoAction(), and setActiveStack().
cleanChanged
void QUndoGroup::cleanChanged (bool clean) signal
This signal is emitted whenever the active stack emits QUndoStack::cleanChanged() or the active stack changes.
clean is the new state, or true if the active stack is 0.
See also
QUndoStack::cleanChanged() setActiveStack()
Referenced by setActiveStack().
createRedoAction()
QAction * QUndoGroup::createRedoAction (QObject * parent, const QString & prefix = QString()) const
Creates an redo QAction object with parent parent.
Triggering this action will cause a call to QUndoStack::redo() on the active stack. The text of this action will always be the text of the command which will be redone in the next call to redo(), prefixed by prefix. If there is no command available for redo, if the group is empty or if none of the stacks are active, this action will be disabled.
If prefix is empty, the default template "Redo %1" is used instead of prefix. Before Qt 4.8, the prefix "Redo" was used by default.
See also
createUndoAction() canRedo() QUndoCommand::text()
Definition at line 417 of file qundogroup.cpp.
 {
     QUndoAction *result = new QUndoAction(prefix, parent);
     if (prefix.isEmpty())
         result->setTextFormat(tr("Redo %1"), tr("Redo", "Default text for redo action"));
     result->setEnabled(canRedo());
     result->setPrefixedText(redoText());
     connect(this, SIGNAL(canRedoChanged(bool)),
             result, SLOT(setEnabled(bool)));
     connect(this, SIGNAL(redoTextChanged(QString)),
             result, SLOT(setPrefixedText(QString)));
     connect(result, SIGNAL(triggered()), this, SLOT(redo()));
     return result;
 }
createUndoAction()
QAction * QUndoGroup::createUndoAction (QObject * parent, const QString & prefix = QString()) const
Creates an undo QAction object with parent parent.
Triggering this action will cause a call to QUndoStack::undo() on the active stack. The text of this action will always be the text of the command which will be undone in the next call to undo(), prefixed by prefix. If there is no command available for undo, if the group is empty or if none of the stacks are active, this action will be disabled.
If prefix is empty, the default template "Undo %1" is used instead of prefix. Before Qt 4.8, the prefix "Undo" was used by default.
See also
createRedoAction() canUndo() QUndoCommand::text()
Definition at line 386 of file qundogroup.cpp.
 {
     QUndoAction *result = new QUndoAction(prefix, parent);
     if (prefix.isEmpty())
         result->setTextFormat(tr("Undo %1"), tr("Undo", "Default text for undo action"));
     result->setEnabled(canUndo());
     result->setPrefixedText(undoText());
     connect(this, SIGNAL(canUndoChanged(bool)),
             result, SLOT(setEnabled(bool)));
     connect(this, SIGNAL(undoTextChanged(QString)),
             result, SLOT(setPrefixedText(QString)));
     connect(result, SIGNAL(triggered()), this, SLOT(undo()));
     return result;
 }
indexChanged
void QUndoGroup::indexChanged (int idx) signal
This signal is emitted whenever the active stack emits QUndoStack::indexChanged() or the active stack changes.
idx is the new current index, or 0 if the active stack is 0.
See also
QUndoStack::indexChanged() setActiveStack()
Referenced by setActiveStack().
isClean()
bool QUndoGroup::isClean () const
Returns the value of the active stack's QUndoStack::isClean().
If none of the stacks are active, or if the group is empty, this function returns true.
See also
setActiveStack()
Definition at line 363 of file qundogroup.cpp.
 {
     Q_D(const QUndoGroup);
     return d->active == 0 || d->active->isClean();
 }
redo
void QUndoGroup::redo () slot
Calls QUndoStack::redo() on the active stack.
If none of the stacks are active, or if the group is empty, this function does nothing.
See also
undo() canRedo() setActiveStack()
Definition at line 287 of file qundogroup.cpp.
Referenced by createRedoAction().
 {
     Q_D(QUndoGroup);
     if (d->active != 0)
         d->active->redo();
 }
redoText()
QString QUndoGroup::redoText () const
Returns the value of the active stack's QUndoStack::redoText().
If none of the stacks are active, or if the group is empty, this function returns an empty string.
See also
undoText() setActiveStack()
Definition at line 348 of file qundogroup.cpp.
Referenced by createRedoAction().
 {
     Q_D(const QUndoGroup);
     return d->active == 0 ? QString() : d->active->redoText();
 }
redoTextChanged
void QUndoGroup::redoTextChanged (const QString & redoText) signal
This signal is emitted whenever the active stack emits QUndoStack::redoTextChanged() or the active stack changes.
redoText is the new state, or an empty string if the active stack is 0.
See also
QUndoStack::redoTextChanged() setActiveStack()
Referenced by createRedoAction(), and setActiveStack().
removeStack()
void QUndoGroup::removeStack (QUndoStack * stack)
Removes stack from this group.
If the stack was the active stack in the group, the active stack becomes 0.
See also
addStack() stacks() QUndoStack::~QUndoStack()
Definition at line 155 of file qundogroup.cpp.
 {
     Q_D(QUndoGroup);
     if (d->stack_list.removeAll(stack) == 0)
         return;
     if (stack == d->active)
         setActiveStack(0);
     stack->d_func()->group = 0;
 }
setActiveStack
void QUndoGroup::setActiveStack (QUndoStack * stack) slot
Sets the active stack of this group to stack.
If the stack is not a member of this group, this function does nothing.
Synonymous with calling QUndoStack::setActive() on stack.
The actions returned by createUndoAction() and createRedoAction() will now behave in the same way as those returned by stack's QUndoStack::createUndoAction() and QUndoStack::createRedoAction().
See also
QUndoStack::setActive() activeStack()
Definition at line 192 of file qundogroup.cpp.
Referenced by removeStack().
 {
     Q_D(QUndoGroup);
     if (d->active == stack)
         return;
     if (d->active != 0) {
         disconnect(d->active, SIGNAL(canUndoChanged(bool)),
                     this, SIGNAL(canUndoChanged(bool)));
         disconnect(d->active, SIGNAL(undoTextChanged(QString)),
                     this, SIGNAL(undoTextChanged(QString)));
         disconnect(d->active, SIGNAL(canRedoChanged(bool)),
                     this, SIGNAL(canRedoChanged(bool)));
         disconnect(d->active, SIGNAL(redoTextChanged(QString)),
                     this, SIGNAL(redoTextChanged(QString)));
         disconnect(d->active, SIGNAL(indexChanged(int)),
                     this, SIGNAL(indexChanged(int)));
         disconnect(d->active, SIGNAL(cleanChanged(bool)),
                     this, SIGNAL(cleanChanged(bool)));
     }
     d->active = stack;
     if (d->active == 0) {
         emit canUndoChanged(false);
         emit undoTextChanged(QString());
         emit canRedoChanged(false);
         emit redoTextChanged(QString());
         emit cleanChanged(true);
         emit indexChanged(0);
     } else {
         connect(d->active, SIGNAL(canUndoChanged(bool)),
                 this, SIGNAL(canUndoChanged(bool)));
         connect(d->active, SIGNAL(undoTextChanged(QString)),
                 this, SIGNAL(undoTextChanged(QString)));
         connect(d->active, SIGNAL(canRedoChanged(bool)),
                 this, SIGNAL(canRedoChanged(bool)));
         connect(d->active, SIGNAL(redoTextChanged(QString)),
                 this, SIGNAL(redoTextChanged(QString)));
         connect(d->active, SIGNAL(indexChanged(int)),
                 this, SIGNAL(indexChanged(int)));
         connect(d->active, SIGNAL(cleanChanged(bool)),
                 this, SIGNAL(cleanChanged(bool)));
         emit canUndoChanged(d->active->canUndo());
         emit undoTextChanged(d->active->undoText());
         emit canRedoChanged(d->active->canRedo());
         emit redoTextChanged(d->active->redoText());
         emit cleanChanged(d->active->isClean());
         emit indexChanged(d->active->index());
     }
     emit activeStackChanged(d->active);
 }
stacks()
QList< QUndoStack * > QUndoGroup::stacks () const
Returns a list of stacks in this group.
See also
addStack() removeStack()
Definition at line 172 of file qundogroup.cpp.
 {
     Q_D(const QUndoGroup);
     return d->stack_list;
 }
undo
void QUndoGroup::undo () slot
Calls QUndoStack::undo() on the active stack.
If none of the stacks are active, or if the group is empty, this function does nothing.
See also
redo() canUndo() setActiveStack()
Definition at line 270 of file qundogroup.cpp.
Referenced by createUndoAction().
 {
     Q_D(QUndoGroup);
     if (d->active != 0)
         d->active->undo();
 }
undoText()
QString QUndoGroup::undoText () const
Returns the value of the active stack's QUndoStack::undoText().
If none of the stacks are active, or if the group is empty, this function returns an empty string.
See also
redoText() setActiveStack()
Definition at line 333 of file qundogroup.cpp.
Referenced by createUndoAction().
 {
     Q_D(const QUndoGroup);
     return d->active == 0 ? QString() : d->active->undoText();
 }
undoTextChanged
void QUndoGroup::undoTextChanged (const QString & undoText) signal
This signal is emitted whenever the active stack emits QUndoStack::undoTextChanged() or the active stack changes.
undoText is the new state, or an empty string if the active stack is 0.
See also
QUndoStack::undoTextChanged() setActiveStack()
Referenced by createUndoAction(), and setActiveStack().
The documentation for this class was generated from the following files:
/src/gui/util/qundogroup.h
/src/gui/util/qundogroup.cpp