Qt 4.8: QPatternist::ReportContext Class Reference
QPatternist::ReportContext Class Reference abstract
A callback for reporting errors.
#include <qreportcontext_p.h>
Public Types
enum ErrorCode {
XSDError, XPST0001, XPDY0002, XPST0003,
XPTY0004, XPST0005, XPTY0006, XPTY0007,
XPST0008, XQST0009, XPST0010, XQST0012,
XQST0013, XQST0014, XQST0015, XQST0016,
XPST0017, XPTY0018, XPTY0019, XPTY0020,
XPDY0021, XQST0022, XQTY0023, XQTY0024,
XQDY0025, XQDY0026, XQDY0027, XQTY0028,
XQDY0029, XQTY0030, XQST0031, XQST0032,
XQST0033, XQST0034, XQST0035, XQST0036,
XQST0037, XQST0038, XQST0039, XQST0040,
XQDY0041, XQST0042, XQST0043, XQDY0044,
XQST0045, XQST0046, XQST0047, XQST0048,
XQST0049, XPDY0050, XPST0051, XQDY0052,
XQST0053, XQST0054, XQST0055, XQST0056,
XQST0057, XQST0058, XQST0059, XQST0060,
XQDY0061, XQDY0062, XQST0063, XQDY0064,
XQST0065, XQST0066, XQST0067, XQST0068,
XQST0069, XQST0070, XQST0071, XQDY0072,
XQST0073, XQDY0074, XQST0075, XQST0076,
XQST0077, XQST0078, XQST0079, XPST0080,
XPST0081, XQST0082, XPST0083, XQDY0084,
XQST0085, XQTY0086, XQST0087, XQST0088,
XQST0089, XQST0090, XQDY0091, XQDY0092,
XQST0093, FOER0000, FOAR0001, FOAR0002,
FOCA0001, FOCA0002, FOCA0003, FOCA0005,
FOCA0006, FOCH0001, FOCH0002, FOCH0003,
FOCH0004, FODC0001, FODC0002, FODC0003,
FODC0004, FODC0005, FODT0001, FODT0002,
FODT0003, FONS0004, FONS0005, FORG0001,
FORG0002, FORG0003, FORG0004, FORG0005,
FORG0006, FORG0008, FORG0009, FORX0001,
FORX0002, FORX0003, FORX0004, FOTY0012,
SENR0001, SERE0003, SEPM0004, SERE0005,
SERE0006, SESU0007, SERE0008, SEPM0009,
SEPM0010, SESU0011, SERE0012, SESU0013,
SERE0014, SERE0015, SEPM0016, XTSE0010,
XTSE0020, XTSE0080, XTSE0090, XTSE0110,
XTSE0120, XTSE0125, XTSE0130, XTSE0150,
XTSE0165, XTSE0170, XTSE0180, XTSE0190,
XTSE0200, XTSE0210, XTSE0215, XTSE0220,
XTSE0260, XTSE0265, XTSE0280, XTSE0340,
XTSE0350, XTSE0370, XTSE0500, XTSE0530,
XTSE0550, XTSE0580, XTSE0620, XTSE0630,
XTSE0650, XTSE0660, XTSE0670, XTSE0680,
XTSE0690, XTSE0710, XTSE0720, XTSE0740,
XTSE0760, XTSE0770, XTSE0805, XTSE0808,
XTSE0809, XTSE0810, XTSE0812, XTSE0840,
XTSE0870, XTSE0880, XTSE0910, XTSE0940,
XTTE0950, XTSE0975, XTSE1015, XTSE1017,
XTSE1040, XTSE1060, XTSE1070, XTSE1080,
XTSE1090, XTSE1130, XTSE1205, XTSE1210,
XTSE1220, XTSE1290, XTSE1295, XTSE1300,
XTSE1430, XTSE1505, XTSE1520, XTSE1530,
XTSE1560, XTSE1570, XTSE1580, XTSE1590,
XTSE1600, XTSE1650, XTSE1660, XTTE0505,
XTTE0510, XTTE0520, XTTE0570, XTTE0590,
XTTE0600, XTTE0780, XTTE0790, XTTE0990,
XTTE1000, XTTE1020, XTTE1100, XTTE1120,
XTTE1510, XTTE1512, XTTE1515, XTTE1540,
XTTE1545, XTTE1550, XTTE1555, XTDE0030,
XTDE0040, XTDE0045, XTDE0047, XTDE0050,
XTDE0060, XTDE0160, XTRE0270, XTDE0290,
XTDE0410, XTDE0420, XTDE0430, XTDE0440,
XTDE0485, XTRE0540, XTDE0560, XTDE0610,
XTDE0640, XTDE0700, XTRE0795, XTDE0820,
XTDE0830, XTDE0835, XTDE0850, XTDE0855,
XTDE0860, XTDE0865, XTDE0890, XTDE0905,
XTDE0920, XTDE0925, XTDE0930, XTDE0980,
XTDE1030, XTDE1035, XTDE1110, XTDE1140,
XTDE1145, XTDE1150, XTRE1160, XTDE1170,
XTDE1190, XTDE1200, XTDE1260, XTDE1270,
XTDE1280, XTDE1310, XTDE1340, XTDE1350,
XTDE1360, XTDE1370, XTDE1380, XTDE1390,
XTMM9000, XTDE1400, XTDE1420, XTDE1425,
XTDE1428, XTDE1440, XTDE1450, XTDE1460,
XTDE1480, XTDE1490, XTRE1495, XTRE1500,
XTRE1620, XTRE1630, XTDE1665
}
typedef QHash< const SourceLocationReflection *, QSourceLocation > LocationHash
typedef QExplicitlySharedDataPointer< ReportContext > Ptr
Public Functions
void error (const QString &message, const ReportContext::ErrorCode errorCode, const QSourceLocation &sourceLocation)
void error (const QString &message, const ReportContext::ErrorCode errorCode, const SourceLocationReflection *const reflection)
void error (const QString &message, const QXmlName qName, const SourceLocationReflection *const r)
virtual QSourceLocation locationFor (const SourceLocationReflection *const reflection) const =0
Returns the source location applying for reflection.
virtual QAbstractMessageHandler * messageHandler () const =0
virtual NamePool::Ptr namePool () const =0
ReportContext ()
Default constructors.
QUrl resolveURI (const QUrl &relative, const QUrl &baseURI) const
virtual const QAbstractUriResolver * uriResolver () const =0
The URI resolver in use.
void warning (const QString &message, const QSourceLocation &sourceLocation=QSourceLocation())
virtual ~ReportContext ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Static Public Functions
static QString codeFromURI (const QString &typeURI, QString &uri)
static QString codeToString (const ReportContext::ErrorCode errorCode)
Private Functions
void createError (const QString &description, const QtMsgType type, const QUrl &id, const QSourceLocation &sourceLocation) const
QSourceLocation lookupSourceLocation (const SourceLocationReflection *const ref) const
Static Private Functions
static QString finalizeDescription (const QString &desc)
Related Functions
(Note that these are not member functions.)
typedef bool Exception
This is the class type that is being thrown when a query error occur.
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
A callback for reporting errors.
ReportContext receives messages of various severity and type via its functions warning() and error(). In turn, ReportContext create Message instances and submit them to the QAbstractMessageHandler instance returned by messageHandler().
The Message attributes are set as follows:
Message::description() - A translated, human-readable description
Message::type() - Message::Error if a static, dynamic or type error was encountered that halted compilation or evaluation, or Message::Warning in case of a warning
Message::identifier() - This is a URI consisting of the error namespace with the error code as fragment. For example, a Message representing a syntax error would return the type "http://www.w3.org/2005/xqt-errors#XPST0003". The convenience function codeFromURI() can be used to extract the error code. The error namespace is typically the namespace for XPath and XQuery errors(as in the previous example), but can also be user defined.
See also
XML Path Language (XPath) 2.0, 2.3.2 Identifying and Reporting Errors
XQuery 1.0 and XPath 2.0 Functions and Operators, 3 The Error Function
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Warning
This file is auto-generated from extractErrorCodes.xsl. Any modifications done to this file are lost.
Definition at line 101 of file qreportcontext_p.h.
Typedefs
LocationHash
typedef QHash<const SourceLocationReflection *, QSourceLocation> QPatternist::ReportContext::LocationHash
Definition at line 104 of file qreportcontext_p.h.
Ptr
typedef QExplicitlySharedDataPointer<ReportContext> QPatternist::ReportContext::Ptr
A smart pointer wrapping ReportContext instances.
Definition at line 109 of file qreportcontext_p.h.
Enumerations
ErrorCode
enum QPatternist::ReportContext::ErrorCode
Error codes that corresponds to the error codes defined in the relevant specifications. They are used throughout the API for identifying error conditions.
While strings could have been used for identifying errors, enums reduces bugs by providing type safety.
See also
XML Path Language (XPath) 2.0, 2.3 Error Handling
XQuery 1.0 and XPath 2.0 Functions and Operators, C Error Summary
XSL Transformations (XSLT) Version 2.0, E Summary of Error Conditions (Non-Normative)
Note
The enumerator values' Doxygen documentation is copied from the W3C documents XQuery 1.0 and XPath 2.0 Functions and Operators, XML Path Language (XPath) 2.0, and XSL Transformations (XSLT) Version 2.0, respectively. The doxygen documentation is therefore covered by the following legal notice: "Copyright @ 2005 W3C&reg; (MIT, ERCIM, Keio), All Rights Reserved. W3C <a href="http://www.w3.org/Consortium/Legal/ipr-notice#Legal_Disclaimer">liability</a>, <a href="http://www.w3.org/Consortium/Legal/ipr-notice#W3C_Trademarks">trademark</a> and <a href="http://www.w3.org/Consortium/Legal/copyright-documents">document use</a> rules apply."
Warning
This enumerator is auto-generated from the relevant specifications by the XSL-T stylesheet extractErrorCodes.xsl. Hence, any modifications done to this file, in contrary to the stylesheet, are therefore lost.
Enumerator
XSDError
XML Schema error code.
XPST0001
It is a static error if analysis of an expression relies on some component of the static context that has not been assigned a value.
XPDY0002
It is a dynamic error if evaluation of an expression relies on some part of the dynamic context that has not been assigned a value.
XPST0003
It is a static error if an expression is not a valid instance of the grammar defined in A.1 EBNF.
XPTY0004
It is a type error if, during the static analysis phase, an expression is found to have a static type that is not appropriate for the context in which the expression occurs, or during the dynamic evaluation phase, the dynamic type of a value does not match a required type as specified by the matching rules in 2.5.4 SequenceType Matching.
XPST0005
During the analysis phase, it is a static error if the static type assigned to an expression other than the expression () or data(()) is empty-sequence().
XPTY0006
(Not currently used.)
XPTY0007
(Not currently used.)
XPST0008
It is a static error if an expression refers to an element name, attribute name, schema type name, namespace prefix, or variable name that is not defined in the static context, except for an ElementName in an ElementTest or an AttributeName in an AttributeTest.
XQST0009
An implementation that does not support the Schema Import Feature must raise a static error if a Prolog contains a schema import.
XPST0010
An implementation must raise a static error if it encounters a reference to an axis that it does not support.
XQST0012
It is a static error if the set of definitions contained in all schemas imported by a Prolog do not satisfy the conditions for schema validity specified in Sections 3 and 5 of [XML Schema] Part 1–i.e., each definition must be valid, complete, and unique.
XQST0013
It is a static error if an implementation recognizes a pragma but determines that its content is invalid.
XQST0014
(Not currently used.)
XQST0015
(Not currently used.)
XQST0016
An implementation that does not support the Module Feature raises a static error if it encounters a module declaration or a module import.
XPST0017
It is a static error if the expanded QName and number of arguments in a function call do not match the name and arity of a function signature in the static context.
XPTY0018
It is a type error if the result of the last step in a path expression contains both nodes and atomic values.
XPTY0019
It is a type error if the result of a step (other than the last step) in a path expression contains an atomic value.
XPTY0020
It is a type error if, in an axis step, the context item is not a node.
XPDY0021
(Not currently used.)
XQST0022
It is a static error if the value of a namespace declaration attribute is not a URILiteral.
XQTY0023
(Not currently used.)
XQTY0024
It is a type error if the content sequence in an element constructor contains an attribute node following a node that is not an attribute node.
XQDY0025
It is a dynamic error if any attribute of a constructed element does not have a name that is distinct from the names of all other attributes of the constructed element.
XQDY0026
It is a dynamic error if the result of the content expression of a computed processing instruction constructor contains the string "?&gt;".
XQDY0027
In a validate expression, it is a dynamic error if the root element information item in the PSVI resulting from validation does not have the expected validity property: valid if validation mode is strict, or either valid or notKnown if validation mode is lax.
XQTY0028
(Not currently used.)
XQDY0029
(Not currently used.)
XQTY0030
It is a type error if the argument of a validate expression does not evaluate to exactly one document or element node.
XQST0031
It is a static error if the version number specified in a version declaration is not supported by the implementation.
XQST0032
A static error is raised if a Prolog contains more than one base URI declaration.
XQST0033
It is a static error if a module contains multiple bindings for the same namespace prefix.
XQST0034
It is a static error if multiple functions declared or imported by a module have the number of arguments and their expanded QNames are equal (as defined by the eq operator).
XQST0035
It is a static error to import two schema components that both define the same name in the same symbol space and in the same scope.
XQST0036
It is a static error to import a module if the importing module's in-scope schema types do not include definitions for the schema type names that appear in the declarations of variables and functions (whether in an argument type or return type) that are present in the imported module and are referenced in the importing module.
XQST0037
(Not currently used.)
XQST0038
It is a static error if a Prolog contains more than one default collation declaration, or the value specified by a default collation declaration is not present in statically known collations.
XQST0039
It is a static error for a function declaration to have more than one parameter with the same name.
XQST0040
It is a static error if the attributes specified by a direct element constructor do not have distinct expanded QNames.
XQDY0041
It is a dynamic error if the value of the name expression in a computed processing instruction constructor cannot be cast to the type xs:NCName.
XQST0042
(Not currently used.)
XQST0043
(Not currently used.)
XQDY0044
It is a dynamic error if the node-name property of the node constructed by a computed attribute constructor is in the namespace http://www.w3.org/2000/xmlns/ (corresponding to namespace prefix xmlns), or is in no namespace and has local name xmlns.
XQST0045
It is a static error if the function name in a function declaration is in one of the following namespaces: http://www.w3.org/XML/1998/namespace, http://www.w3.org/2001/XMLSchema, http://www.w3.org/2001/XMLSchema-instance, http://www.w3.org/2005/xpath-functions.
XQST0046
An implementation MAY raise a static error if the value of a URILiteral is of nonzero length and is not in the lexical space of xs:anyURI.
XQST0047
It is a static error if multiple module imports in the same Prolog specify the same target namespace.
XQST0048
It is a static error if a function or variable declared in a library module is not in the target namespace of the library module.
XQST0049
It is a static error if two or more variables declared or imported by a module have equal expanded QNames (as defined by the eq operator.)
XPDY0050
It is a dynamic error if the dynamic type of the operand of a treat expression does not match the sequence type specified by the treat expression. This error might also be raised by a path expression beginning with "/" or "//" if the context node is not in a tree that is rooted at a document node. This is because a leading "/" or "//" in a path expression is an abbreviation for an initial step that includes the clause treat as document-node().
XPST0051
It is a static error if a QName that is used as an AtomicType in a SequenceType is not defined in the in-scope schema types as an atomic type.
XQDY0052
(Not currently used.)
XQST0053
(Not currently used.)
XQST0054
It is a static error if a variable depends on itself.
XQST0055
It is a static error if a Prolog contains more than one copy-namespaces declaration.
XQST0056
(Not currently used.)
XQST0057
It is a static error if a schema import binds a namespace prefix but does not specify a target namespace other than a zero-length string.
XQST0058
It is a static error if multiple schema imports specify the same target namespace.
XQST0059
It is a static error if an implementation is unable to process a schema or module import by finding a schema or module with the specified target namespace.
XQST0060
It is a static error if the name of a function in a function declaration is not in a namespace (expanded QName has a null namespace URI).
XQDY0061
It is a dynamic error if the operand of a validate expression is a document node whose children do not consist of exactly one element node and zero or more comment and processing instruction nodes, in any order.
XQDY0062
(Not currently used.)
XQST0063
(Not currently used.)
XQDY0064
It is a dynamic error if the value of the name expression in a computed processing instruction constructor is equal to "XML" (in any combination of upper and lower case).
XQST0065
A static error is raised if a Prolog contains more than one ordering mode declaration.
XQST0066
A static error is raised if a Prolog contains more than one default element/type namespace declaration, or more than one default function namespace declaration.
XQST0067
A static error is raised if a Prolog contains more than one construction declaration.
XQST0068
A static error is raised if a Prolog contains more than one boundary-space declaration.
XQST0069
A static error is raised if a Prolog contains more than one empty order declaration.
XQST0070
A static error is raised if a namespace URI is bound to the predefined prefix xmlns, or if a namespace URI other than http://www.w3.org/XML/1998/namespace is bound to the prefix xml, or if the prefix xml is bound to a namespace URI other than http://www.w3.org/XML/1998/namespace.
XQST0071
A static error is raised if the namespace declaration attributes of a direct element constructor do not have distinct names.
XQDY0072
It is a dynamic error if the result of the content expression of a computed comment constructor contains two adjacent hyphens or ends with a hyphen.
XQST0073
It is a static error if the graph of module imports contains a cycle (that is, if there exists a sequence of modules M1 ... Mn such that each Mi imports Mi+1 and Mn imports M1), unless all the modules in the cycle share a common namespace.
XQDY0074
It is a dynamic error if the value of the name expression in a computed element or attribute constructor cannot be converted to an expanded QName (for example, because it contains a namespace prefix not found in statically known namespaces.)
XQST0075
An implementation that does not support the Validation Feature must raise a static error if it encounters a validate expression.
XQST0076
It is a static error if a collation subclause in an order by clause of a FLWOR expression does not identify a collation that is present in statically known collations.
XQST0077
(Not currently used.)
XQST0078
(Not currently used.)
XQST0079
It is a static error if an extension expression contains neither a pragma that is recognized by the implementation nor an expression enclosed in curly braces.
XPST0080
It is a static error if the target type of a cast or castable expression is xs:NOTATION or xs:anyAtomicType.
XPST0081
It is a static error if a QName used in a query contains a namespace prefix that cannot be expanded into a namespace URI by using the statically known namespaces.
XQST0082
(Not currently used.)
XPST0083
(Not currently used.)
XQDY0084
It is a dynamic error if the element validated by a validate statement does not have a top-level element declaration in the in-scope element declarations, if validation mode is strict.
XQST0085
It is a static error if the namespace URI in a namespace declaration attribute is a zero-length string, and the implementation does not support [XML Names 1.1].
XQTY0086
It is a type error if the typed value of a copied element or attribute node is namespace-sensitive when construction mode is preserve and copy-namespaces mode is no-preserve.
XQST0087
It is a static error if the encoding specified in a Version Declaration does not conform to the definition of EncName specified in [XML 1.0].
XQST0088
It is a static error if the literal that specifies the target namespace in a module import or a module declaration is of zero length.
XQST0089
It is a static error if a variable bound in a for clause of a FLWOR expression, and its associated positional variable, do not have distinct names (expanded QNames).
XQST0090
It is a static error if a character reference does not identify a valid character in the version of XML that is in use.
XQDY0091
An implementation MAY raise a dynamic error if an xml:id error, as defined in [XML ID], is encountered during construction of an attribute named xml:id.
XQDY0092
An implementation MAY raise a dynamic error if a constructed attribute named xml:space has a value other than preserve or default.
XQST0093
It is a static error to import a module M1 if there exists a sequence of modules M1 ... Mi ... M1 such that each module directly depends on the next module in the sequence (informally, if M1 depends on itself through some chain of module dependencies.)
FOER0000
Unidentified error.
FOAR0001
Division by zero.
FOAR0002
Numeric operation overflow/underflow.
FOCA0001
Input value too large for decimal.
FOCA0002
Invalid lexical value.
FOCA0003
Input value too large for integer.
FOCA0005
NaN supplied as float/double value.
FOCA0006
String to be cast to decimal has too many digits of precision.
FOCH0001
Code point not valid.
FOCH0002
Unsupported collation.
FOCH0003
Unsupported normalization form.
FOCH0004
Collation does not support collation units.
FODC0001
No context document.
FODC0002
Error retrieving resource.
FODC0003
Function stability not defined.
FODC0004
Invalid argument to fn:collection.
FODC0005
Invalid argument to fn:doc or fn:doc-available.
FODT0001
Overflow/underflow in date/time operation.
FODT0002
Overflow/underflow in duration operation.
FODT0003
Invalid timezone value.
FONS0004
No namespace found for prefix.
FONS0005
Base-uri not defined in the static context.
FORG0001
Invalid value for cast/constructor.
FORG0002
Invalid argument to fn:resolve-uri().
FORG0003
fn:zero-or-one called with a sequence containing more than one item.
FORG0004
fn:one-or-more called with a sequence containing no items.
FORG0005
fn:exactly-one called with a sequence containing zero or more than one item.
FORG0006
Invalid argument type.
FORG0008
Both arguments to fn:dateTime have a specified timezone.
FORG0009
Error in resolving a relative URI against a base URI in fn:resolve-uri.
FORX0001
Invalid regular expression. flags
FORX0002
Invalid regular expression.
FORX0003
Regular expression matches zero-length string.
FORX0004
Invalid replacement string.
FOTY0012
Argument node does not have a typed value.
SENR0001
It is an error if an item in S6 in sequence normalization is an attribute node or a namespace node.
SERE0003
It is an error if the serializer is unable to satisfy the rules for either a well-formed XML document entity or a well-formed XML external general parsed entity, or both, except for content modified by the character expansion phase of serialization.
SEPM0004
It is an error to specify the doctype-system parameter, or to specify the standalone parameter with a value other than omit, if the instance of the data model contains text nodes or multiple element nodes as children of the root node.
SERE0005
It is an error if the serialized result would contain an NCName Names that contains a character that is not permitted by the version of Namespaces in XML specified by the version parameter.
SERE0006
It is an error if the serialized result would contain a character that is not permitted by the version of XML specified by the version parameter.
SESU0007
It is an error if an output encoding other than UTF-8 or UTF-16 is requested and the serializer does not support that encoding.
SERE0008
It is an error if a character that cannot be represented in the encoding that the serializer is using for output appears in a context where character references are not allowed (for example if the character occurs in the name of an element).
SEPM0009
It is an error if the omit-xml-declaration parameter has the value yes, and the standalone attribute has a value other than omit; or the version parameter has a value other than 1.0 and the doctype-system parameter is specified.
SEPM0010
It is an error if the output method is xml, the value of the undeclare-prefixes parameter is yes, and the value of the version parameter is 1.0.
SESU0011
It is an error if the value of the normalization-form parameter specifies a normalization form that is not supported by the serializer.
SERE0012
It is an error if the value of the normalization-form parameter is fully-normalized and any relevant construct of the result begins with a combining character.
SESU0013
It is an error if the serializer does not support the version of XML or HTML specified by the version parameter.
SERE0014
It is an error to use the HTML output method when characters which are legal in XML but not in HTML, specifically the control characters #x7F-#x9F, appear in the instance of the data model.
SERE0015
It is an error to use the HTML output method when > appears within a processing instruction in the data model instance being serialized.
SEPM0016
It is a an error if a parameter value is invalid for the defined domain.
XTSE0010
A static error is signaled if an XSLT-defined element is used in a context where it is not permitted, if a required attribute is omitted, or if the content of the element does not correspond to the content that is allowed for the element.
XTSE0020
It is a static error if an attribute (other than an attribute written using curly brackets in a position where an attribute value template is permitted) contains a value that is not one of the permitted values for that attribute.
XTSE0080
It is a static error to use a reserved namespace in the name of a named template, a mode, an attribute set, a key, a decimal-format, a variable or parameter, a stylesheet function, a named output definition, or a character map.
XTSE0090
It is a static error for an element from the XSLT namespace to have an attribute whose namespace is either null (that is, an attribute with an unprefixed name) or the XSLT namespace, other than attributes defined for the element in this document.
XTSE0110
The value of the version attribute must be a number: specifically, it must be a a valid instance of the type xs:decimal as defined in [XML Schema Part 2].
XTSE0120
An xsl:stylesheet element must not have any text node children.
XTSE0125
It is a static error if the value of an [xsl:]default-collation attribute, after resolving against the base URI, contains no URI that the implementation recognizes as a collation URI.
XTSE0130
It is a static error if the xsl:stylesheet element has a child element whose name has a null namespace URI.
XTSE0150
A literal result element that is used as the outermost element of a simplified stylesheet module must have an xsl:version attribute.
XTSE0165
It is a static error if the processor is not able to retrieve the resource identified by the URI reference [ in the href attribute of xsl:include or xsl:import] , or if the resource that is retrieved does not contain a stylesheet module conforming to this specification.
XTSE0170
An xsl:include element must be a top-level element.
XTSE0180
It is a static error if a stylesheet module directly or indirectly includes itself.
XTSE0190
An xsl:import element must be a top-level element.
XTSE0200
The xsl:import element children must precede all other element children of an xsl:stylesheet element, including any xsl:include element children and any user-defined data elements.
XTSE0210
It is a static error if a stylesheet module directly or indirectly imports itself.
XTSE0215
It is a static error if an xsl:import-schema element that contains an xs:schema element has a schema-location attribute, or if it has a namespace attribute that conflicts with the target namespace of the contained schema.
XTSE0220
It is a static error if the synthetic schema document does not satisfy the constraints described in XML Schema Part 1. This includes, without loss of generality, conflicts such as multiple definitions of the same name.
XTSE0260
Within an XSLT element that is required to be empty, any content other than comments or processing instructions, including any whitespace text node preserved using the xml:space="preserve" attribute, is a static error.
XTSE0265
It is a static error if there is a stylesheet module in the stylesheet that specifies input-type-annotations="strip" and another stylesheet module that specifies input-type-annotations="preserve".
XTSE0280
In the case of a prefixed QName used as the value of an attribute in the stylesheet, or appearing within an XPath expression in the stylesheet, it is a static error if the defining element has no namespace node whose name matches the prefix of the QName.
XTSE0340
Where an attribute is defined to contain a pattern, it is a static error if the pattern does not match the production Pattern.
XTSE0350
It is a static error if an unescaped left curly bracket appears in a fixed part of an attribute value template without a matching right curly bracket.
XTSE0370
It is a static error if an unescaped right curly bracket occurs in a fixed part of an attribute value template.
XTSE0500
An xsl:template element must have either a match attribute or a name attribute, or both. An xsl:template element that has no match attribute must have no mode attribute and no priority attribute.
XTSE0530
The value of this attribute [the priority attribute of the xsl:template element] must conform to the rules for the xs:decimal type defined in [XML Schema Part 2]. Negative values are permitted..
XTSE0550
It is a static error if the list [of modes in the mode attribute of xsl:template] is empty, if the same token is included more than once in the list, if the list contains an invalid token, or if the token #all appears together with any other value.
XTSE0580
It is a static error if two parameters of a template or of a stylesheet function have the same name.
XTSE0620
It is a static error if a variable-binding element has a select attribute and has non-empty content.
XTSE0630
It is a static error if a stylesheet contains more than one binding of a global variable with the same name and same import precedence, unless it also contains another binding with the same name and higher import precedence.
XTSE0650
It is a static error if a stylesheet contains an xsl:call-template instruction whose name attribute does not match the name attribute of any xsl:template in the stylesheet.
XTSE0660
It is a static error if a stylesheet contains more than one template with the same name and the same import precedence, unless it also contains a template with the same name and higher import precedence.
XTSE0670
It is a static error if a single xsl:call-template, xsl:apply-templates, xsl:apply-imports, or xsl:next-match element contains two or more xsl:with-param elements with matching name attributes.
XTSE0680
In the case of xsl:call-template, it is a static error to pass a non-tunnel parameter named x to a template that does not have a template parameter named x, unless backwards compatible behavior is enabled for the xsl:call-template instruction.
XTSE0690
It is a static error if a template that is invoked using xsl:call-template declares a template parameter specifying required="yes" and not specifying tunnel="yes", if no value for this parameter is supplied by the calling instruction.
XTSE0710
It is a static error if the value of the use-attribute-sets attribute of an xsl:copy, xsl:element, or xsl:attribute-set element, or the xsl:use-attribute-sets attribute of a literal result element, is not a whitespace-separated sequence of QNames, or if it contains a QName that does not match the name attribute of any xsl:attribute-set declaration in the stylesheet.
XTSE0720
It is a static error if an xsl:attribute-set element directly or indirectly references itself via the names contained in the use-attribute-sets attribute.
XTSE0740
A stylesheet function must have a prefixed name, to remove any risk of a clash with a function in the default function namespace. It is a static error if the name has no prefix.
XTSE0760
Because arguments to a stylesheet function call must all be specified, the xsl:param elements within an xsl:function element must not specify a default value: this means they must be empty, and must not have a select attribute.
XTSE0770
It is a static error for a stylesheet to contain two or more functions with the same expanded-QName, the same arity, and the same import precedence, unless there is another function with the same expanded-QName and arity, and a higher import precedence.
XTSE0805
It is a static error if an attribute on a literal result element is in the XSLT namespace, unless it is one of the attributes explicitly defined in this specification.
XTSE0808
It is a static error if a namespace prefix is used within the [xsl:]exclude-result-prefixes attribute and there is no namespace binding in scope for that prefix.
XTSE0809
It is a static error if the value #default is used within the [xsl:]exclude-result-prefixes attribute and the parent element of the [xsl:]exclude-result-prefixes attribute has no default namespace.
XTSE0810
It is a static error if there is more than one such declaration [more than one xsl:namespace-alias declaration] with the same literal namespace URI and the same import precedence and different values for the target namespace URI, unless there is also an xsl:namespace-alias declaration with the same literal namespace URI and a higher import precedence.
XTSE0812
It is a static error if a value other than #default is specified for either the stylesheet-prefix or the result-prefix attributes of the xsl:namespace-alias element when there is no in-scope binding for that namespace prefix.
XTSE0840
It is a static error if the select attribute of the xsl:attribute element is present unless the element has empty content.
XTSE0870
It is a static error if the select attribute of the xsl:value-of element is present when the content of the element is non-empty, or if the select attribute is absent when the content is empty.
XTSE0880
It is a static error if the select attribute of the xsl:processing-instruction element is present unless the element has empty content.
XTSE0910
It is a static error if the select attribute of the xsl:namespace element is present when the element has content other than one or more xsl:fallback instructions, or if the select attribute is absent when the element has empty content.
XTSE0940
It is a static error if the select attribute of the xsl:comment element is present unless the element has empty content.
XTTE0950
It is a type error to use the xsl:copy or xsl:copy-of instruction to copy a node that has namespace-sensitive content if the copy-namespaces attribute has the value no and its explicit or implicit validation attribute has the value preserve. It is also a type error if either of these instructions (with validation="preserve") is used to copy an attribute having namespace-sensitive content, unless the parent element is also copied. A node has namespace-sensitive content if its typed value contains an item of type xs:QName or xs:NOTATION or a type derived therefrom. The reason this is an error is because the validity of the content depends on the namespace context being preserved.
XTSE0975
It is a static error if the value attribute of xsl:number is present unless the select, level, count, and from attributes are all absent.
XTSE1015
It is a static error if an xsl:sort element with a select attribute has non-empty content.
XTSE1017
It is a static error if an xsl:sort element other than the first in a sequence of sibling xsl:sort elements has a stable attribute.
XTSE1040
It is a static error if an xsl:perform-sort instruction with a select attribute has any content other than xsl:sort and xsl:fallback instructions.
XTSE1060
It is a static error if the current-group function is used within a pattern.
XTSE1070
It is a static error if the current-grouping-key function is used within a pattern.
XTSE1080
These four attributes [the group-by, group-adjacent, group-starting-with, and group-ending-with attributes of xsl:for-each-group ] are mutually exclusive: it is a static error if none of these four attributes is present, or if more than one of them is present.
XTSE1090
It is an error to specify the collation attribute if neither the group-by attribute nor group-adjacent attribute is specified.
XTSE1130
It is a static error if the xsl:analyze-string instruction contains neither an xsl:matching-substring nor an xsl:non-matching-substring element.
XTSE1205
It is a static error if an xsl:key declaration has a use attribute and has non-empty content, or if it has empty content and no use attribute.
XTSE1210
It is a static error if the xsl:key declaration has a collation attribute whose value (after resolving against the base URI) is not a URI recognized by the implementation as referring to a collation.
XTSE1220
It is a static error if there are several xsl:key declarations in the stylesheet with the same key name and different effective collations. Two collations are the same if their URIs are equal under the rules for comparing xs:anyURI values, or if the implementation can determine that they are different URIs referring to the same collation.
XTSE1290
It is a static error if a named or unnamed decimal format contains two conflicting values for the same attribute in different xsl:decimal-format declarations having the same import precedence, unless there is another definition of the same attribute with higher import precedence.
XTSE1295
It is a static error if the character specified in the zero-digit attribute is not a digit or is a digit that does not have the numeric value zero.
XTSE1300
It is a static error if, for any named or unnamed decimal format, the variables representing characters used in a picture string do not each have distinct values. These variables are decimal-separator-sign, grouping-sign, percent-sign, per-mille-sign, digit-zero-sign, digit-sign, and pattern-separator-sign.
XTSE1430
It is a static error if there is no namespace bound to the prefix on the element bearing the [xsl:]extension-element-prefixes attribute or, when #default is specified, if there is no default namespace.
XTSE1505
It is a static error if both the [xsl:]type and [xsl:]validation attributes are present on the xsl:element, xsl:attribute, xsl:copy, xsl:copy-of, xsl:document, or xsl:result-document instructions, or on a literal result element.
XTSE1520
It is a static error if the value of the type attribute of an xsl:element, xsl:attribute, xsl:copy, xsl:copy-of, xsl:document, or xsl:result-document instruction, or the xsl:type attribute of a literal result element, is not a valid QName, or if it uses a prefix that is not defined in an in-scope namespace declaration, or if the QName is not the name of a type definition included in the in-scope schema components for the stylesheet.
XTSE1530
It is a static error if the value of the type attribute of an xsl:attribute instruction refers to a complex type definition
XTSE1560
It is a static error if two xsl:output declarations within an output definition specify explicit values for the same attribute (other than cdata-section-elements and use-character-maps), with the values of the attributes being not equal, unless there is another xsl:output declaration within the same output definition that has higher import precedence and that specifies an explicit value for the same attribute.
XTSE1570
The value [of the method attribute on xsl:output ] must (if present) be a valid QName. If the QName does not have a prefix, then it identifies a method specified in [XSLT and XQuery Serialization] and must be one of xml, html, xhtml, or text.
XTSE1580
It is a static error if the stylesheet contains two or more character maps with the same name and the same import precedence, unless it also contains another character map with the same name and higher import precedence.
XTSE1590
It is a static error if a name in the use-character-maps attribute of the xsl:output or xsl:character-map elements does not match the name attribute of any xsl:character-map in the stylesheet.
XTSE1600
It is a static error if a character map references itself, directly or indirectly, via a name in the use-character-maps attribute.
XTSE1650
A basic XSLT processor must signal a static error if the stylesheet includes an xsl:import-schema declaration.
XTSE1660
A basic XSLT processor must signal a static error if the stylesheet includes an [xsl:]type attribute, or an [xsl:]validation or default-validation attribute with a value other than strip.
XTTE0505
It is a type error if the result of evaluating the sequence constructor cannot be converted to the required type.
XTTE0510
It is a type error if an xsl:apply-templates instruction with no select attribute is evaluated when the context item is not a node.
XTTE0520
It is a type error if the sequence returned by the select expression [of xsl:apply-templates] contains an item that is not a node.
XTTE0570
It is a type error if the supplied value of a variable cannot be converted to the required type.
XTTE0590
It is a type error if the conversion of the supplied value of a parameter to its required type fails.
XTTE0600
If a default value is given explicitly, that is, if there is either a select attribute or a non-empty sequence constructor, then it is a type error if the default value cannot be converted to the required type, using the function conversion rules.
XTTE0780
If the as attribute [of xsl:function ] is specified, then the result evaluated by the sequence constructor (see 5.7 Sequence Constructors) is converted to the required type, using the function conversion rules. It is a type error if this conversion fails.
XTTE0790
If the value of a parameter to a stylesheet function cannot be converted to the required type, a type error is signaled.
XTTE0990
It is a type error if the xsl:number instruction is evaluated, with no value or select attribute, when the context item is not a node.
XTTE1000
It is a type error if the result of evaluating the select attribute of the xsl:number instruction is anything other than a single node.
XTTE1020
If any sort key value, after atomization and any type conversion required by the data-type attribute, is a sequence containing more than one item, then the effect depends on whether the xsl:sort element is evaluated with backwards compatible behavior. With backwards compatible behavior, the effective sort key value is the first item in the sequence. In other cases, this is a type error.
XTTE1100
It is a type error if the grouping key evaluated using the group-adjacent attribute is an empty sequence, or a sequence containing more than one item.
XTTE1120
When the group-starting-with or group-ending-with attribute [of the xsl:for-each-group instruction] is used, it is a type error if the result of evaluating the select expression contains an item that is not a node.
XTTE1510
If the validation attribute of an xsl:element, xsl:attribute, xsl:copy, xsl:copy-of, or xsl:result-document instruction, or the xsl:validation attribute of a literal result element, has the effective value strict, and schema validity assessment concludes that the validity of the element or attribute is invalid or unknown, a type error occurs. As with other type errors, the error may be signaled statically if it can be detected statically.
XTTE1512
If the validation attribute of an xsl:element, xsl:attribute, xsl:copy, xsl:copy-of, or xsl:result-document instruction, or the xsl:validation attribute of a literal result element, has the effective value strict, and there is no matching top-level declaration in the schema, then a type error occurs. As with other type errors, the error may be signaled statically if it can be detected statically.
XTTE1515
If the validation attribute of an xsl:element, xsl:attribute, xsl:copy, xsl:copy-of, or xsl:result-document instruction, or the xsl:validation attribute of a literal result element, has the effective value lax, and schema validity assessment concludes that the element or attribute is invalid, a type error occurs. As with other type errors, the error may be signaled statically if it can be detected statically.
XTTE1540
It is a type error if an [xsl:]type attribute is defined for a constructed element or attribute, and the outcome of schema validity assessment against that type is that the validity property of that element or attribute information item is other than valid.
XTTE1545
A type error occurs if a type or validation attribute is defined (explicitly or implicitly) for an instruction that constructs a new attribute node, if the effect of this is to cause the attribute value to be validated against a type that is derived from, or constructed by list or union from, the primitive types xs:QName or xs:NOTATION.
XTTE1550
A type error occurs [when a document node is validated] unless the children of the document node comprise exactly one element node, no text nodes, and zero or more comment and processing instruction nodes, in any order.
XTTE1555
It is a type error if, when validating a document node, document-level constraints are not satisfied. These constraints include identity constraints (xs:unique, xs:key, and xs:keyref) and ID/IDREF constraints.
XTDE0030
It is a non-recoverable dynamic error if the effective value of an attribute written using curly brackets, in a position where an attribute value template is permitted, is a value that is not one of the permitted values for that attribute. If the processor is able to detect the error statically (for example, when any XPath expressions within the curly brackets can be evaluated statically), then the processor may optionally signal this as a static error.
XTDE0040
It is a non-recoverable dynamic error if the invocation of the stylesheet specifies a template name that does not match the expanded-QName of a named template defined in the stylesheet.
XTDE0045
It is a non-recoverable dynamic error if the invocation of the stylesheet specifies an initial mode (other than the default mode) that does not match the expanded-QName in the mode attribute of any template defined in the stylesheet.
XTDE0047
It is a non-recoverable dynamic error if the invocation of the stylesheet specifies both an initial mode and an initial template.
XTDE0050
It is a non-recoverable dynamic error if the stylesheet that is invoked declares a visible stylesheet parameter with required="yes" and no value for this parameter is supplied during the invocation of the stylesheet. A stylesheet parameter is visible if it is not masked by another global variable or parameter with the same name and higher import precedence.
XTDE0060
It is a non-recoverable dynamic error if the initial template defines a template parameter that specifies required="yes".
XTDE0160
If an implementation does not support backwards-compatible behavior, then it is a non-recoverable dynamic error if any element is evaluated that enables backwards-compatible behavior.
XTRE0270
It is a recoverable dynamic error if this [the process of finding an xsl:strip-space or xsl:preserve-space declaration to match an element in the source document] leaves more than one match, unless all the matched declarations are equivalent (that is, they are all xsl:strip-space or they are all xsl:preserve-space). Action: The optional recovery action is to select, from the matches that are left, the one that occurs last in declaration order.
XTDE0290
Where the result of evaluating an XPath expression (or an attribute value template) is required to be a lexical QName, then unless otherwise specified it is a non-recoverable dynamic error if the defining element has no namespace node whose name matches the prefix of the lexical QName. This error may be signaled as a static error if the value of the expression can be determined statically.
XTDE0410
It is a non-recoverable dynamic error if the result sequence used to construct the content of an element node contains a namespace node or attribute node that is preceded in the sequence by a node that is neither a namespace node nor an attribute node.
XTDE0420
It is a non-recoverable dynamic error if the result sequence used to construct the content of a document node contains a namespace node or attribute node.
XTDE0430
It is a non-recoverable dynamic error if the result sequence contains two or more namespace nodes having the same name but different string values (that is, namespace nodes that map the same prefix to different namespace URIs).
XTDE0440
It is a non-recoverable dynamic error if the result sequence contains a namespace node with no name and the element node being constructed has a null namespace URI (that is, it is an error to define a default namespace when the element is in no namespace).
XTDE0485
It is a non-recoverable dynamic error if namespace fixup is performed on an element that contains among the typed values of the element and its attributes two values of type xs:QName or xs:NOTATION containing conflicting namespace prefixes, that is, two values that use the same prefix to refer to different namespace URIs.
XTRE0540
It is a recoverable dynamic error if the conflict resolution algorithm for template rules leaves more than one matching template rule. Action: The optional recovery action is to select, from the matching template rules that are left, the one that occurs last in declaration order.
XTDE0560
It is a non-recoverable dynamic error if xsl:apply-imports or xsl:next-match is evaluated when the current template rule is null.
XTDE0610
If an optional parameter has no select attribute and has an empty sequence constructor, and if there is an as attribute, then the default value of the parameter is an empty sequence. If the empty sequence is not a valid instance of the required type defined in the as attribute, then the parameter is treated as a required parameter, which means that it is a non-recoverable dynamic error if the caller supplies no value for the parameter.
XTDE0640
In general, a circularity in a stylesheet is a non-recoverable dynamic error.
XTDE0700
In other cases, [with xsl:apply-templates, xsl:apply-imports, and xsl:next-match, or xsl:call-template with tunnel parameters] it is a non-recoverable dynamic error if the template that is invoked declares a template parameter with required="yes" and no value for this parameter is supplied by the calling instruction.
XTRE0795
It is a recoverable dynamic error if the name of a constructed attribute is xml:space and the value is not either default or preserve. Action: The optional recovery action is to construct the attribute with the value as requested.
XTDE0820
It is a non-recoverable dynamic error if the effective value of the name attribute [of the xsl:element instruction] is not a lexical QName.
XTDE0830
In the case of an xsl:element instruction with no namespace attribute, it is a non-recoverable dynamic error if the effective value of the name attribute is a QName whose prefix is not declared in an in-scope namespace declaration for the xsl:element instruction.
XTDE0835
It is a non-recoverable dynamic error if the effective value of the namespace attribute [of the xsl:element instruction] is not in the lexical space of the xs:anyURI data type.
XTDE0850
It is a non-recoverable dynamic error if the effective value of the name attribute [of an xsl:attribute instruction] is not a lexical QName.
XTDE0855
In the case of an xsl:attribute instruction with no namespace attribute, it is a non-recoverable dynamic error if the effective value of the name attribute is the string xmlns.
XTDE0860
In the case of an xsl:attribute instruction with no namespace attribute, it is a non-recoverable dynamic error if the effective value of the name attribute is a lexical QName whose prefix is not declared in an in-scope namespace declaration for the xsl:attribute instruction.
XTDE0865
It is a non-recoverable dynamic error if the effective value of the namespace attribute [of the xsl:attribute instruction] is not in the lexical space of the xs:anyURI data type.
XTDE0890
It is a non-recoverable dynamic error if the effective value of the name attribute [of the xsl:processing-instruction instruction] is not both an NCName Names and a PITarget XML.
XTDE0905
It is a non-recoverable dynamic error if the string value of the new namespace node [created using xsl:namespace] is not valid in the lexical space of the data type xs:anyURI. [see ERR XTDE0835]
XTDE0920
It is a non-recoverable dynamic error if the effective value of the name attribute [of the xsl:namespace instruction] is neither a zero-length string nor an NCName Names, or if it is xmlns.
XTDE0925
It is a non-recoverable dynamic error if the xsl:namespace instruction generates a namespace node whose name is xml and whose string value is not http://www.w3.org/XML/1998/namespace, or a namespace node whose string value is http://www.w3.org/XML/1998/namespace and whose name is not xml.
XTDE0930
It is a non-recoverable dynamic error if evaluating the select attribute or the contained sequence constructor of an xsl:namespace instruction results in a zero-length string.
XTDE0980
It is a non-recoverable dynamic error if any undiscarded item in the atomized sequence supplied as the value of the value attribute of xsl:number cannot be converted to an integer, or if the resulting integer is less than 0 (zero).
XTDE1030
It is a non-recoverable dynamic error if, for any sort key component, the set of sort key values evaluated for all the items in the initial sequence, after any type conversion requested, contains a pair of ordinary values for which the result of the XPath lt operator is an error.
XTDE1035
It is a non-recoverable dynamic error if the collation attribute of xsl:sort (after resolving against the base URI) is not a URI that is recognized by the implementation as referring to a collation.
XTDE1110
It is a non-recoverable dynamic error if the collation URI specified to xsl:for-each-group (after resolving against the base URI) is a collation that is not recognized by the implementation. (For notes, [see ERR XTDE1035].)
XTDE1140
It is a non-recoverable dynamic error if the effective value of the regex attribute [of the xsl:analyze-string instruction] does not conform to the required syntax for regular expressions, as specified in [Functions and Operators]. If the regular expression is known statically (for example, if the attribute does not contain any expressions enclosed in curly brackets) then the processor may signal the error as a static error.
XTDE1145
It is a non-recoverable dynamic error if the effective value of the flags attribute [of the xsl:analyze-string instruction] has a value other than the values defined in [Functions and Operators]. If the value of the attribute is known statically (for example, if the attribute does not contain any expressions enclosed in curly brackets) then the processor may signal the error as a static error.
XTDE1150
It is a non-recoverable dynamic error if the effective value of the regex attribute [of the xsl:analyze-string instruction] is a regular expression that matches a zero-length string: or more specifically, if the regular expression $r and flags $f are such that matches("", $r, $f) returns true. If the regular expression is known statically (for example, if the attribute does not contain any expressions enclosed in curly brackets) then the processor may signal the error as a static error.
XTRE1160
When a URI reference [supplied to the document function] contains a fragment identifier, it is a recoverable dynamic error if the media type is not one that is recognized by the processor, or if the fragment identifier does not conform to the rules for fragment identifiers for that media type, or if the fragment identifier selects something other than a sequence of nodes (for example, if it selects a range of characters within a text node). Action: The optional recovery action is to ignore the fragment identifier and return the document node.
XTDE1170
It is a non-recoverable dynamic error if a URI [supplied in the first argument to the unparsed-text function] contains a fragment identifier, or if it cannot be used to retrieve a resource containing text.
XTDE1190
It is a non-recoverable dynamic error if a resource [retrieved using the unparsed-text function] contains octets that cannot be decoded into Unicode characters using the specified encoding, or if the resulting characters are not permitted XML characters. This includes the case where the processor does not support the requested encoding.
XTDE1200
It is a non-recoverable dynamic error if the second argument of the unparsed-text function is omitted and the processor cannot infer the encoding using external information and the encoding is not UTF-8.
XTDE1260
It is a non-recoverable dynamic error if the value [of the first argument to the key function] is not a valid QName, or if there is no namespace declaration in scope for the prefix of the QName, or if the name obtained by expanding the QName is not the same as the expanded name of any xsl:key declaration in the stylesheet. If the processor is able to detect the error statically (for example, when the argument is supplied as a string literal), then the processor may optionally signal this as a static error.
XTDE1270
It is a non-recoverable dynamic error to call the key function with two arguments if there is no context node, or if the root of the tree containing the context node is not a document node; or to call the function with three arguments if the root of the tree containing the node supplied in the third argument is not a document node.
XTDE1280
It is a non-recoverable dynamic error if the name specified as the $decimal-format-name argument [ to the format-number function] is not a valid QName, or if its prefix has not been declared in an in-scope namespace declaration, or if the stylesheet does not contain a declaration of a decimal-format with a matching expanded-QName. If the processor is able to detect the error statically (for example, when the argument is supplied as a string literal), then the processor may optionally signal this as a static error.
XTDE1310
The picture string [supplied to the format-number function] must conform to the following rules. [ See full specification.] It is a non-recoverable dynamic error if the picture string does not satisfy these rules.
XTDE1340
It is a non-recoverable dynamic error if the syntax of the picture [used for date/time formatting] is incorrect.
XTDE1350
It is a non-recoverable dynamic error if a component specifier within the picture [used for date/time formatting] refers to components that are not available in the given type of $value, for example if the picture supplied to the format-time refers to the year, month, or day component.
XTDE1360
If the current function is evaluated within an expression that is evaluated when the context item is undefined, a non-recoverable dynamic error occurs.
XTDE1370
It is a non-recoverable dynamic error if the unparsed-entity-uri function is called when there is no context node, or when the root of the tree containing the context node is not a document node.
XTDE1380
It is a non-recoverable dynamic error if the unparsed-entity-public-id function is called when there is no context node, or when the root of the tree containing the context node is not a document node.
XTDE1390
It is a non-recoverable dynamic error if the value [supplied as the $property-name argument to the system-property function] is not a valid QName, or if there is no namespace declaration in scope for the prefix of the QName. If the processor is able to detect the error statically (for example, when the argument is supplied as a string literal), then the processor may optionally signal this as a static error.
XTMM9000
When a transformation is terminated by use of xsl:message terminate="yes", the effect is the same as when a non-recoverable dynamic error occurs during the transformation.
XTDE1400
It is a non-recoverable dynamic error if the argument [passed to the function-available function] does not evaluate to a string that is a valid QName, or if there is no namespace declaration in scope for the prefix of the QName. If the processor is able to detect the error statically (for example, when the argument is supplied as a string literal), then the processor may optionally signal this as a static error.
XTDE1420
It is a non-recoverable dynamic error if the arguments supplied to a call on an extension function do not satisfy the rules defined for that particular extension function, or if the extension function reports an error, or if the result of the extension function cannot be converted to an XPath value.
XTDE1425
When backwards compatible behavior is enabled, it is a non-recoverable dynamic error to evaluate an extension function call if no implementation of the extension function is available.
XTDE1428
It is a non-recoverable dynamic error if the argument [passed to the type-available function] does not evaluate to a string that is a valid QName, or if there is no namespace declaration in scope for the prefix of the QName. If the processor is able to detect the error statically (for example, when the argument is supplied as a string literal), then the processor may optionally signal this as a static error.
XTDE1440
It is a non-recoverable dynamic error if the argument [passed to the element-available function] does not evaluate to a string that is a valid QName, or if there is no namespace declaration in scope for the prefix of the QName. If the processor is able to detect the error statically (for example, when the argument is supplied as a string literal), then the processor may optionally signal this as a static error.
XTDE1450
When a processor performs fallback for an extension instruction that is not recognized, if the instruction element has one or more xsl:fallback children, then the content of each of the xsl:fallback children must be evaluated; it is a non-recoverable dynamic error if it has no xsl:fallback children.
XTDE1460
It is a non-recoverable dynamic error if the effective value of the format attribute [of an xsl:result-document element] is not a valid lexical QName, or if it does not match the expanded-QName of an output definition in the stylesheet. If the processor is able to detect the error statically (for example, when the format attribute contains no curly brackets), then the processor may optionally signal this as a static error.
XTDE1480
It is a non-recoverable dynamic error to evaluate the xsl:result-document instruction in temporary output state.
XTDE1490
It is a non-recoverable dynamic error for a transformation to generate two or more final result trees with the same URI.
XTRE1495
It is a recoverable dynamic error for a transformation to generate two or more final result trees with URIs that identify the same physical resource. The optional recovery action is implementation-dependent, since it may be impossible for the processor to detect the error.
XTRE1500
It is a recoverable dynamic error for a stylesheet to write to an external resource and read from the same resource during a single transformation, whether or not the same URI is used to access the resource in both cases. Action: The optional recovery action is implementation-dependent: implementations are not required to detect the error condition. Note that if the error is not detected, it is undefined whether the document that is read from the resource reflects its state before or after the result tree is written.
XTRE1620
It is a recoverable dynamic error if an xsl:value-of or xsl:text instruction specifies that output escaping is to be disabled and the implementation does not support this. Action: The optional recovery action is to ignore the disable-output-escaping attribute.
XTRE1630
It is a recoverable dynamic error if an xsl:value-of or xsl:text instruction specifies that output escaping is to be disabled when writing to a final result tree that is not being serialized. Action: The optional recovery action is to ignore the disable-output-escaping attribute.
XTDE1665
A basic XSLT processor must raise a non-recoverable dynamic error if the input to the processor includes a node with a type annotation other than xs:untyped or xs:untypedAtomic, or an atomic value of a type other than those which a basic XSLT processor supports.
Definition at line 152 of file qreportcontext_p.h.
         {
             XSDError,
             XPST0001,
             XPDY0002,
             XPST0003,
             XPTY0004,
             XPST0005,
             XPTY0006,
             XPTY0007,
             XPST0008,
             XQST0009,
             XPST0010,
             XQST0012,
             XQST0013,
             XQST0014,
             XQST0015,
             XQST0016,
             XPST0017,
             XPTY0018,
             XPTY0019,
             XPTY0020,
             XPDY0021,
             XQST0022,
             XQTY0023,
             XQTY0024,
             XQDY0025,
             XQDY0026,
             XQDY0027,
             XQTY0028,
             XQDY0029,
             XQTY0030,
             XQST0031,
             XQST0032,
             XQST0033,
             XQST0034,
             XQST0035,
             XQST0036,
             XQST0037,
             XQST0038,
             XQST0039,
             XQST0040,
             XQDY0041,
             XQST0042,
             XQST0043,
             XQDY0044,
             XQST0045,
             XQST0046,
             XQST0047,
             XQST0048,
             XQST0049,
             XPDY0050,
             XPST0051,
             XQDY0052,
             XQST0053,
             XQST0054,
             XQST0055,
             XQST0056,
             XQST0057,
             XQST0058,
             XQST0059,
             XQST0060,
             XQDY0061,
             XQDY0062,
             XQST0063,
             XQDY0064,
             XQST0065,
             XQST0066,
             XQST0067,
             XQST0068,
             XQST0069,
             XQST0070,
             XQST0071,
             XQDY0072,
             XQST0073,
             XQDY0074,
             XQST0075,
             XQST0076,
             XQST0077,
             XQST0078,
             XQST0079,
             XPST0080,
             XPST0081,
             XQST0082,
             XPST0083,
             XQDY0084,
             XQST0085,
             XQTY0086,
             XQST0087,
             XQST0088,
             XQST0089,
             XQST0090,
             XQDY0091,
             XQDY0092,
             XQST0093,
             FOER0000,
             FOAR0001,
             FOAR0002,
             FOCA0001,
             FOCA0002,
             FOCA0003,
             FOCA0005,
             FOCA0006,
             FOCH0001,
             FOCH0002,
             FOCH0003,
             FOCH0004,
             FODC0001,
             FODC0002,
             FODC0003,
             FODC0004,
             FODC0005,
             FODT0001,
             FODT0002,
             FODT0003,
             FONS0004,
             FONS0005,
             FORG0001,
             FORG0002,
             FORG0003,
             FORG0004,
             FORG0005,
             FORG0006,
             FORG0008,
             FORG0009,
             FORX0001,
             FORX0002,
             FORX0003,
             FORX0004,
             FOTY0012,
             SENR0001,
             SERE0003,
             SEPM0004,
             SERE0005,
             SERE0006,
             SESU0007,
             SERE0008,
             SEPM0009,
             SEPM0010,
             SESU0011,
             SERE0012,
             SESU0013,
             SERE0014,
             SERE0015,
             SEPM0016,
             XTSE0010,
             XTSE0020,
             XTSE0080,
             XTSE0090,
             XTSE0110,
             XTSE0120,
             XTSE0125,
             XTSE0130,
             XTSE0150,
             XTSE0165,
             XTSE0170,
             XTSE0180,
             XTSE0190,
             XTSE0200,
             XTSE0210,
             XTSE0215,
             XTSE0220,
             XTSE0260,
             XTSE0265,
             XTSE0280,
             XTSE0340,
             XTSE0350,
             XTSE0370,
             XTSE0500,
             XTSE0530,
             XTSE0550,
             XTSE0580,
             XTSE0620,
             XTSE0630,
             XTSE0650,
             XTSE0660,
             XTSE0670,
             XTSE0680,
             XTSE0690,
             XTSE0710,
             XTSE0720,
             XTSE0740,
             XTSE0760,
             XTSE0770,
             XTSE0805,
             XTSE0808,
             XTSE0809,
             XTSE0810,
             XTSE0812,
             XTSE0840,
             XTSE0870,
             XTSE0880,
             XTSE0910,
             XTSE0940,
             XTTE0950,
             XTSE0975,
             XTSE1015,
             XTSE1017,
             XTSE1040,
             XTSE1060,
             XTSE1070,
             XTSE1080,
             XTSE1090,
             XTSE1130,
             XTSE1205,
             XTSE1210,
             XTSE1220,
             XTSE1290,
             XTSE1295,
             XTSE1300,
             XTSE1430,
             XTSE1505,
             XTSE1520,
             XTSE1530,
             XTSE1560,
             XTSE1570,
             XTSE1580,
             XTSE1590,
             XTSE1600,
             XTSE1650,
             XTSE1660,
             XTTE0505,
             XTTE0510,
             XTTE0520,
             XTTE0570,
             XTTE0590,
             XTTE0600,
             XTTE0780,
             XTTE0790,
             XTTE0990,
             XTTE1000,
             XTTE1020,
             XTTE1100,
             XTTE1120,
             XTTE1510,
             XTTE1512,
             XTTE1515,
             XTTE1540,
             XTTE1545,
             XTTE1550,
             XTTE1555,
             XTDE0030,
             XTDE0040,
             XTDE0045,
             XTDE0047,
             XTDE0050,
             XTDE0060,
             XTDE0160,
             XTRE0270,
             XTDE0290,
             XTDE0410,
             XTDE0420,
             XTDE0430,
             XTDE0440,
             XTDE0485,
             XTRE0540,
             XTDE0560,
             XTDE0610,
             XTDE0640,
             XTDE0700,
             XTRE0795,
             XTDE0820,
             XTDE0830,
             XTDE0835,
             XTDE0850,
             XTDE0855,
             XTDE0860,
             XTDE0865,
             XTDE0890,
             XTDE0905,
             XTDE0920,
             XTDE0925,
             XTDE0930,
             XTDE0980,
             XTDE1030,
             XTDE1035,
             XTDE1110,
             XTDE1140,
             XTDE1145,
             XTDE1150,
             XTRE1160,
             XTDE1170,
             XTDE1190,
             XTDE1200,
             XTDE1260,
             XTDE1270,
             XTDE1280,
             XTDE1310,
             XTDE1340,
             XTDE1350,
             XTDE1360,
             XTDE1370,
             XTDE1380,
             XTDE1390,
             XTMM9000,
             XTDE1400,
             XTDE1420,
             XTDE1425,
             XTDE1428,
             XTDE1440,
             XTDE1450,
             XTDE1460,
             XTDE1480,
             XTDE1490,
             XTRE1495,
             XTRE1500,
             XTRE1620,
             XTRE1630,
             XTDE1665
         };
Constructors and Destructors
ReportContext()
QPatternist::ReportContext::ReportContext () inline
Default constructors.
For some reason GCC fails to synthesize it, so we provide an empty one here.
Definition at line 117 of file qreportcontext_p.h.
 {}
~ReportContext()
ReportContext::~ReportContext () virtual
Definition at line 55 of file qreportcontext.cpp.
 {
 }
Functions
codeFromURI()
QString ReportContext::codeFromURI (const QString & typeURI, QString & uri) static
Returns
the error code part of typeURI and sets uri to the error namespace. Note that the error namespace not necessarily is the namespace for XPath and XQuery errors, http://www.w3.org/2005/xqt-errors, but can be user defined.
Definition at line 126 of file qreportcontext.cpp.
 {
     /* Wouldn't surprise me if this can be done more efficiently. */
     QUrl source(typeURI);
     const QString code(source.fragment());
     source.setFragment(QString());
     uri = source.toString();
     return code;
 }
codeToString()
QString ReportContext::codeToString (const ReportContext::ErrorCode errorCode) static
Returns a string representation of the error code code.
See also
ReportContext::ErrorCode
Parameters
errorCode identifies the error condition, as described in XML Path Language (XPath) 2.0, G Error Conditions
Definition at line 138 of file qreportcontext.cpp.
Referenced by QPatternist::TypeChecker::applyFunctionConversion(), and error().
 {
     const char *result = 0;
     switch(code)
     {
         /* Alphabetically. */
         case FOAR0001: result = "FOAR0001"; break;
         case FOAR0002: result = "FOAR0002"; break;
         case FOCA0001: result = "FOCA0001"; break;
         case FOCA0002: result = "FOCA0002"; break;
         case FOCA0003: result = "FOCA0003"; break;
         case FOCA0005: result = "FOCA0005"; break;
         case FOCA0006: result = "FOCA0006"; break;
         case FOCH0001: result = "FOCH0001"; break;
         case FOCH0002: result = "FOCH0002"; break;
         case FOCH0003: result = "FOCH0003"; break;
         case FOCH0004: result = "FOCH0004"; break;
         case FODC0001: result = "FODC0001"; break;
         case FODC0002: result = "FODC0002"; break;
         case FODC0003: result = "FODC0003"; break;
         case FODC0004: result = "FODC0004"; break;
         case FODC0005: result = "FODC0005"; break;
         case FODT0001: result = "FODT0001"; break;
         case FODT0002: result = "FODT0002"; break;
         case FODT0003: result = "FODT0003"; break;
         case FOER0000: result = "FOER0000"; break;
         case FONS0004: result = "FONS0004"; break;
         case FONS0005: result = "FONS0005"; break;
         case FORG0001: result = "FORG0001"; break;
         case FORG0002: result = "FORG0002"; break;
         case FORG0003: result = "FORG0003"; break;
         case FORG0004: result = "FORG0004"; break;
         case FORG0005: result = "FORG0005"; break;
         case FORG0006: result = "FORG0006"; break;
         case FORG0008: result = "FORG0008"; break;
         case FORG0009: result = "FORG0009"; break;
         case FORX0001: result = "FORX0001"; break;
         case FORX0002: result = "FORX0002"; break;
         case FORX0003: result = "FORX0003"; break;
         case FORX0004: result = "FORX0004"; break;
         case FOTY0012: result = "FOTY0012"; break;
         case SENR0001: result = "SENR0001"; break;
         case SEPM0004: result = "SEPM0004"; break;
         case SEPM0009: result = "SEPM0009"; break;
         case SEPM0010: result = "SEPM0010"; break;
         case SEPM0016: result = "SEPM0016"; break;
         case SERE0003: result = "SERE0003"; break;
         case SERE0005: result = "SERE0005"; break;
         case SERE0006: result = "SERE0006"; break;
         case SERE0008: result = "SERE0008"; break;
         case SERE0012: result = "SERE0012"; break;
         case SERE0014: result = "SERE0014"; break;
         case SERE0015: result = "SERE0015"; break;
         case SESU0007: result = "SESU0007"; break;
         case SESU0011: result = "SESU0011"; break;
         case SESU0013: result = "SESU0013"; break;
         case XPDY0002: result = "XPDY0002"; break;
         case XPDY0021: result = "XPDY0021"; break;
         case XPDY0050: result = "XPDY0050"; break;
         case XPST0001: result = "XPST0001"; break;
         case XPST0003: result = "XPST0003"; break;
         case XPST0005: result = "XPST0005"; break;
         case XPST0008: result = "XPST0008"; break;
         case XPST0010: result = "XPST0010"; break;
         case XPST0017: result = "XPST0017"; break;
         case XPST0051: result = "XPST0051"; break;
         case XPST0080: result = "XPST0080"; break;
         case XPST0081: result = "XPST0081"; break;
         case XPST0083: result = "XPST0083"; break;
         case XPTY0004: result = "XPTY0004"; break;
         case XPTY0006: result = "XPTY0006"; break;
         case XPTY0007: result = "XPTY0007"; break;
         case XPTY0018: result = "XPTY0018"; break;
         case XPTY0019: result = "XPTY0019"; break;
         case XPTY0020: result = "XPTY0020"; break;
         case XQDY0025: result = "XQDY0025"; break;
         case XQDY0026: result = "XQDY0026"; break;
         case XQDY0027: result = "XQDY0027"; break;
         case XQDY0029: result = "XQDY0029"; break;
         case XQDY0041: result = "XQDY0041"; break;
         case XQDY0044: result = "XQDY0044"; break;
         case XQDY0052: result = "XQDY0052"; break;
         case XQDY0061: result = "XQDY0061"; break;
         case XQDY0062: result = "XQDY0062"; break;
         case XQDY0064: result = "XQDY0064"; break;
         case XQDY0072: result = "XQDY0072"; break;
         case XQDY0074: result = "XQDY0074"; break;
         case XQDY0084: result = "XQDY0084"; break;
         case XQDY0091: result = "XQDY0091"; break;
         case XQDY0092: result = "XQDY0092"; break;
         case XQST0009: result = "XQST0009"; break;
         case XQST0012: result = "XQST0012"; break;
         case XQST0013: result = "XQST0013"; break;
         case XQST0014: result = "XQST0014"; break;
         case XQST0015: result = "XQST0015"; break;
         case XQST0016: result = "XQST0016"; break;
         case XQST0022: result = "XQST0022"; break;
         case XQST0031: result = "XQST0031"; break;
         case XQST0032: result = "XQST0032"; break;
         case XQST0033: result = "XQST0033"; break;
         case XQST0034: result = "XQST0034"; break;
         case XQST0035: result = "XQST0035"; break;
         case XQST0036: result = "XQST0036"; break;
         case XQST0037: result = "XQST0037"; break;
         case XQST0038: result = "XQST0038"; break;
         case XQST0039: result = "XQST0039"; break;
         case XQST0040: result = "XQST0040"; break;
         case XQST0042: result = "XQST0042"; break;
         case XQST0043: result = "XQST0043"; break;
         case XQST0045: result = "XQST0045"; break;
         case XQST0046: result = "XQST0046"; break;
         case XQST0047: result = "XQST0047"; break;
         case XQST0048: result = "XQST0048"; break;
         case XQST0049: result = "XQST0049"; break;
         case XQST0053: result = "XQST0053"; break;
         case XQST0054: result = "XQST0054"; break;
         case XQST0055: result = "XQST0055"; break;
         case XQST0056: result = "XQST0056"; break;
         case XQST0057: result = "XQST0057"; break;
         case XQST0058: result = "XQST0058"; break;
         case XQST0059: result = "XQST0059"; break;
         case XQST0060: result = "XQST0060"; break;
         case XQST0063: result = "XQST0063"; break;
         case XQST0065: result = "XQST0065"; break;
         case XQST0066: result = "XQST0066"; break;
         case XQST0067: result = "XQST0067"; break;
         case XQST0068: result = "XQST0068"; break;
         case XQST0069: result = "XQST0069"; break;
         case XQST0070: result = "XQST0070"; break;
         case XQST0071: result = "XQST0071"; break;
         case XQST0073: result = "XQST0073"; break;
         case XQST0075: result = "XQST0075"; break;
         case XQST0076: result = "XQST0076"; break;
         case XQST0077: result = "XQST0077"; break;
         case XQST0078: result = "XQST0078"; break;
         case XQST0079: result = "XQST0079"; break;
         case XQST0082: result = "XQST0082"; break;
         case XQST0085: result = "XQST0085"; break;
         case XQST0087: result = "XQST0087"; break;
         case XQST0088: result = "XQST0088"; break;
         case XQST0089: result = "XQST0089"; break;
         case XQST0090: result = "XQST0090"; break;
         case XQST0093: result = "XQST0093"; break;
         case XQTY0023: result = "XQTY0023"; break;
         case XQTY0024: result = "XQTY0024"; break;
         case XQTY0028: result = "XQTY0028"; break;
         case XQTY0030: result = "XQTY0030"; break;
         case XQTY0086: result = "XQTY0086"; break;
         case XTDE0030: result = "XTDE0030"; break;
         case XTDE0040: result = "XTDE0040"; break;
         case XTDE0045: result = "XTDE0045"; break;
         case XTDE0047: result = "XTDE0047"; break;
         case XTDE0050: result = "XTDE0050"; break;
         case XTDE0060: result = "XTDE0060"; break;
         case XTDE0160: result = "XTDE0160"; break;
         case XTDE0290: result = "XTDE0290"; break;
         case XTDE0410: result = "XTDE0410"; break;
         case XTDE0420: result = "XTDE0420"; break;
         case XTDE0430: result = "XTDE0430"; break;
         case XTDE0440: result = "XTDE0440"; break;
         case XTDE0485: result = "XTDE0485"; break;
         case XTDE0560: result = "XTDE0560"; break;
         case XTDE0610: result = "XTDE0610"; break;
         case XTDE0640: result = "XTDE0640"; break;
         case XTDE0700: result = "XTDE0700"; break;
         case XTDE0820: result = "XTDE0820"; break;
         case XTDE0830: result = "XTDE0830"; break;
         case XTDE0835: result = "XTDE0835"; break;
         case XTDE0850: result = "XTDE0850"; break;
         case XTDE0855: result = "XTDE0855"; break;
         case XTDE0860: result = "XTDE0860"; break;
         case XTDE0865: result = "XTDE0865"; break;
         case XTDE0890: result = "XTDE0890"; break;
         case XTDE0905: result = "XTDE0905"; break;
         case XTDE0920: result = "XTDE0920"; break;
         case XTDE0925: result = "XTDE0925"; break;
         case XTDE0930: result = "XTDE0930"; break;
         case XTDE0980: result = "XTDE0980"; break;
         case XTDE1030: result = "XTDE1030"; break;
         case XTDE1035: result = "XTDE1035"; break;
         case XTDE1110: result = "XTDE1110"; break;
         case XTDE1140: result = "XTDE1140"; break;
         case XTDE1145: result = "XTDE1145"; break;
         case XTDE1150: result = "XTDE1150"; break;
         case XTDE1170: result = "XTDE1170"; break;
         case XTDE1190: result = "XTDE1190"; break;
         case XTDE1200: result = "XTDE1200"; break;
         case XTDE1260: result = "XTDE1260"; break;
         case XTDE1270: result = "XTDE1270"; break;
         case XTDE1280: result = "XTDE1280"; break;
         case XTDE1310: result = "XTDE1310"; break;
         case XTDE1340: result = "XTDE1340"; break;
         case XTDE1350: result = "XTDE1350"; break;
         case XTDE1360: result = "XTDE1360"; break;
         case XTDE1370: result = "XTDE1370"; break;
         case XTDE1380: result = "XTDE1380"; break;
         case XTDE1390: result = "XTDE1390"; break;
         case XTDE1400: result = "XTDE1400"; break;
         case XTDE1420: result = "XTDE1420"; break;
         case XTDE1425: result = "XTDE1425"; break;
         case XTDE1428: result = "XTDE1428"; break;
         case XTDE1440: result = "XTDE1440"; break;
         case XTDE1450: result = "XTDE1450"; break;
         case XTDE1460: result = "XTDE1460"; break;
         case XTDE1480: result = "XTDE1480"; break;
         case XTDE1490: result = "XTDE1490"; break;
         case XTDE1665: result = "XTDE1665"; break;
         case XTMM9000: result = "XTMM9000"; break;
         case XTRE0270: result = "XTRE0270"; break;
         case XTRE0540: result = "XTRE0540"; break;
         case XTRE0795: result = "XTRE0795"; break;
         case XTRE1160: result = "XTRE1160"; break;
         case XTRE1495: result = "XTRE1495"; break;
         case XTRE1500: result = "XTRE1500"; break;
         case XTRE1620: result = "XTRE1620"; break;
         case XTRE1630: result = "XTRE1630"; break;
         case XTSE0010: result = "XTSE0010"; break;
         case XTSE0020: result = "XTSE0020"; break;
         case XTSE0080: result = "XTSE0080"; break;
         case XTSE0090: result = "XTSE0090"; break;
         case XTSE0110: result = "XTSE0110"; break;
         case XTSE0120: result = "XTSE0120"; break;
         case XTSE0125: result = "XTSE0125"; break;
         case XTSE0130: result = "XTSE0130"; break;
         case XTSE0150: result = "XTSE0150"; break;
         case XTSE0165: result = "XTSE0165"; break;
         case XTSE0170: result = "XTSE0170"; break;
         case XTSE0180: result = "XTSE0180"; break;
         case XTSE0190: result = "XTSE0190"; break;
         case XTSE0200: result = "XTSE0200"; break;
         case XTSE0210: result = "XTSE0210"; break;
         case XTSE0215: result = "XTSE0215"; break;
         case XTSE0220: result = "XTSE0220"; break;
         case XTSE0260: result = "XTSE0260"; break;
         case XTSE0265: result = "XTSE0265"; break;
         case XTSE0280: result = "XTSE0280"; break;
         case XTSE0340: result = "XTSE0340"; break;
         case XTSE0350: result = "XTSE0350"; break;
         case XTSE0370: result = "XTSE0370"; break;
         case XTSE0500: result = "XTSE0500"; break;
         case XTSE0530: result = "XTSE0530"; break;
         case XTSE0550: result = "XTSE0550"; break;
         case XTSE0580: result = "XTSE0580"; break;
         case XTSE0620: result = "XTSE0620"; break;
         case XTSE0630: result = "XTSE0630"; break;
         case XTSE0650: result = "XTSE0650"; break;
         case XTSE0660: result = "XTSE0660"; break;
         case XTSE0670: result = "XTSE0670"; break;
         case XTSE0680: result = "XTSE0680"; break;
         case XTSE0690: result = "XTSE0690"; break;
         case XTSE0710: result = "XTSE0710"; break;
         case XTSE0720: result = "XTSE0720"; break;
         case XTSE0740: result = "XTSE0740"; break;
         case XTSE0760: result = "XTSE0760"; break;
         case XTSE0770: result = "XTSE0770"; break;
         case XTSE0805: result = "XTSE0805"; break;
         case XTSE0808: result = "XTSE0808"; break;
         case XTSE0809: result = "XTSE0809"; break;
         case XTSE0810: result = "XTSE0810"; break;
         case XTSE0812: result = "XTSE0812"; break;
         case XTSE0840: result = "XTSE0840"; break;
         case XTSE0870: result = "XTSE0870"; break;
         case XTSE0880: result = "XTSE0880"; break;
         case XTSE0910: result = "XTSE0910"; break;
         case XTSE0940: result = "XTSE0940"; break;
         case XTSE0975: result = "XTSE0975"; break;
         case XTSE1015: result = "XTSE1015"; break;
         case XTSE1017: result = "XTSE1017"; break;
         case XTSE1040: result = "XTSE1040"; break;
         case XTSE1060: result = "XTSE1060"; break;
         case XTSE1070: result = "XTSE1070"; break;
         case XTSE1080: result = "XTSE1080"; break;
         case XTSE1090: result = "XTSE1090"; break;
         case XTSE1130: result = "XTSE1130"; break;
         case XTSE1205: result = "XTSE1205"; break;
         case XTSE1210: result = "XTSE1210"; break;
         case XTSE1220: result = "XTSE1220"; break;
         case XTSE1290: result = "XTSE1290"; break;
         case XTSE1295: result = "XTSE1295"; break;
         case XTSE1300: result = "XTSE1300"; break;
         case XTSE1430: result = "XTSE1430"; break;
         case XTSE1505: result = "XTSE1505"; break;
         case XTSE1520: result = "XTSE1520"; break;
         case XTSE1530: result = "XTSE1530"; break;
         case XTSE1560: result = "XTSE1560"; break;
         case XTSE1570: result = "XTSE1570"; break;
         case XTSE1580: result = "XTSE1580"; break;
         case XTSE1590: result = "XTSE1590"; break;
         case XTSE1600: result = "XTSE1600"; break;
         case XTSE1650: result = "XTSE1650"; break;
         case XTSE1660: result = "XTSE1660"; break;
         case XTTE0505: result = "XTTE0505"; break;
         case XTTE0510: result = "XTTE0510"; break;
         case XTTE0520: result = "XTTE0520"; break;
         case XTTE0570: result = "XTTE0570"; break;
         case XTTE0590: result = "XTTE0590"; break;
         case XTTE0600: result = "XTTE0600"; break;
         case XTTE0780: result = "XTTE0780"; break;
         case XTTE0790: result = "XTTE0790"; break;
         case XTTE0950: result = "XTTE0950"; break;
         case XTTE0990: result = "XTTE0990"; break;
         case XTTE1000: result = "XTTE1000"; break;
         case XTTE1020: result = "XTTE1020"; break;
         case XTTE1100: result = "XTTE1100"; break;
         case XTTE1120: result = "XTTE1120"; break;
         case XTTE1510: result = "XTTE1510"; break;
         case XTTE1512: result = "XTTE1512"; break;
         case XTTE1515: result = "XTTE1515"; break;
         case XTTE1540: result = "XTTE1540"; break;
         case XTTE1545: result = "XTTE1545"; break;
         case XTTE1550: result = "XTTE1550"; break;
         case XTTE1555: result = "XTTE1555"; break;
         case XSDError: result = "XSDError"; break;
     }
     Q_ASSERT_X(result, Q_FUNC_INFO, "Unknown enum value.");
     return QLatin1String(result);
 }
createError()
void ReportContext::createError (const QString & description, const QtMsgType type, const QUrl & id, const QSourceLocation & sourceLocation) const private
Definition at line 72 of file qreportcontext.cpp.
Referenced by error().
 {
     messageHandler()->message(type, finalizeDescription(description), id, sourceLocation);
     throw Exception(true);
 }
error() [1/3]
void ReportContext::error (const QString & message, const ReportContext::ErrorCode errorCode, const QSourceLocation & sourceLocation)
Issues an error. May be used at the static analysis phase or the dynamic evaluation phase.
For SourceLocationReflection instances, the overload taking an SouourceLocationReflection should be used.
See also
XML Path Language (XPath) 2.0, 2.3 Error Handling
Parameters
message the message to be read by the user.
errorCode identifies the error condition, as described
sourceLocation the location of where the error originates from in "XML Path Language (XPath) 2.0" section "G Error Conditions"
Definition at line 81 of file qreportcontext.cpp.
Referenced by QPatternist::allowedIn(), QPatternist::DocumentContentValidator::attribute(), QPatternist::OutputValidator::attribute(), QPatternist::DecimalMathematician::calculate(), QPatternist::IntegerMathematician::calculate(), QPatternist::DurationNumericMathematician::calculate(), QPatternist::DateTimeDurationMathematician::calculate(), QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaChecker::checkAttributeUseConstraints(), QPatternist::XsdSchemaChecker::checkBasicCircularInheritances(), QPatternist::XsdSchemaChecker::checkBasicComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkBasicSimpleTypeConstraints(), QPatternist::XsdSchemaChecker::checkCircularInheritances(), QPatternist::XsdSchemaChecker::checkComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdSchemaChecker::checkDuplicatedAttributeUses(), QPatternist::XsdSchemaChecker::checkElementConstraints(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), QPatternist::XsdSchemaChecker::checkInheritanceRestrictions(), QPatternist::XsdSchemaResolver::checkRedefinedAttributeGroups(), QPatternist::XsdSchemaResolver::checkRedefinedGroups(), QPatternist::XsdSchemaChecker::checkSimpleDerivationRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), QPatternist::ContextNodeChecker::checkTargetNode(), QPatternist::GenericPredicate::create(), QPatternist::Template::createContext(), QPatternist::ProcessingInstructionConstructor::data(), QPatternist::NormalizeUnicodeFN::determineNormalizationForm(), QPatternist::XsdValidatingInstanceReader::error(), error(), QPatternist::CommentConstructor::evaluateContent(), QPatternist::Boolean::evaluateEBV(), QPatternist::AtomicValue::evaluateEBV(), QPatternist::CardinalityVerifier::evaluateSequence(), QPatternist::Path::evaluateSequence(), QPatternist::CollectionFN::evaluateSequence(), QPatternist::DateTimeFN::evaluateSingleton(), QPatternist::UnparsedTextFN::evaluateSingleton(), QPatternist::CardinalityVerifier::evaluateSingleton(), QPatternist::AttributeNameValidator::evaluateSingleton(), QPatternist::ErrorFN::evaluateSingleton(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::CodepointsToStringFN::evaluateSingleton(), QPatternist::AdjustTimezone::evaluateSingleton(), QPatternist::CastAs::evaluateSingleton(), QPatternist::ComputedNamespaceConstructor::evaluateToSequenceReceiver(), QPatternist::ApplyTemplate::findTemplate(), QPatternist::GenericPredicate::mapToItem(), QPatternist::QNameConstructor::namespaceForPrefix(), QPatternist::PatternPlatform::parseFlags(), QPatternist::ReplaceFN::parseReplacement(), QPatternist::XsdSchemaResolver::resolveAlternativeTypes(), QPatternist::XsdSchemaResolver::resolveAttributeInheritance(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveAttributeTypes(), QPatternist::XsdSchemaResolver::resolveComplexBaseTypes(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveElementTypes(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), QPatternist::XsdSchemaResolver::resolveKeyReferences(), QPatternist::XsdSchemaResolver::resolveSimpleListType(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictionBaseTypes(), QPatternist::XsdSchemaResolver::resolveSimpleUnionTypes(), QPatternist::XsdSchemaResolver::resolveSubstitutionGroupAffiliations(), QPatternist::XsdSchemaResolver::resolveTermReference(), QPatternist::AddingAggregate::typeCheck(), QPatternist::CastAs::typeCheck(), QPatternist::AvgFN::typeCheck(), QPatternist::DocFN::typeCheck(), QPatternist::SumFN::typeCheck(), QPatternist::AbstractFunctionFactory::verifyArity(), QPatternist::CardinalityVerifier::verifyCardinality(), QPatternist::ItemVerifier::verifyItem(), and QPatternist::TypeChecker::verifyType().
 {
     createError(msg, QtFatalMsg,
                 QUrl(CommonNamespaces::XPERR + QLatin1Char('#') + codeToString(code)),
                 sourceLocation);
 }
error() [2/3]
void ReportContext::error (const QString & message, const ReportContext::ErrorCode errorCode, const SourceLocationReflection *const reflection)
Overload.
Same as the above, but passes the SourceLocationReflection as reference for error reporting.
Definition at line 108 of file qreportcontext.cpp.
 {
     Q_ASSERT(reflection);
     error(message, errorCode, lookupSourceLocation(reflection));
 }
error() [3/3]
void ReportContext::error (const QString & message, const QXmlName qName, const SourceLocationReflection *const r)
Issues an error which is not identified in the XPath specifications. This function is among other things used for implementing the fn:error() function.
Definition at line 116 of file qreportcontext.cpp.
 {
     Q_ASSERT(!qname.isNull());
     createError(msg, QtFatalMsg,
                 QUrl(namePool()->stringForNamespace(qname.namespaceURI()) + QLatin1Char('#') + namePool()->stringForLocalName(qname.localName())),
                 lookupSourceLocation(reflection));
 }
finalizeDescription()
QString ReportContext::finalizeDescription (const QString & desc) inline static private
Definition at line 59 of file qreportcontext.cpp.
Referenced by createError(), and warning().
 {
     return QLatin1String("<html xmlns='http://www.w3.org/1999/xhtml/'><body><p>")
            + desc
            + QLatin1String("</p></body></html>");
 }
locationFor()
virtual QSourceLocation QPatternist::ReportContext::locationFor (const SourceLocationReflection *const reflection) const pure virtual
Returns the source location applying for reflection.
Implemented in QPatternist::GenericStaticContext, QPatternist::XsdSchemaContext, QPatternist::DelegatingStaticContext, QPatternist::GenericDynamicContext, and QPatternist::DelegatingDynamicContext.
Referenced by QPatternist::DelegatingDynamicContext::locationFor(), QPatternist::DelegatingStaticContext::locationFor(), lookupSourceLocation(), QPatternist::DocumentFN::typeCheck(), and QPatternist::StaticContext::wrapExpressionWith().
lookupSourceLocation()
QSourceLocation ReportContext::lookupSourceLocation (const SourceLocationReflection *const ref) const private
Definition at line 90 of file qreportcontext.cpp.
Referenced by error().
 {
     Q_ASSERT(r);
     const SourceLocationReflection *const actual = r->actualReflection();
     Q_ASSERT(actual);
     const QSourceLocation &sl = actual->sourceLocation();
     if(sl.isNull())
     {
         Q_ASSERT_X(!locationFor(actual).isNull(), Q_FUNC_INFO,
                    qPrintable(QString::fromLatin1("No location is available for: %1").arg(actual->description())));
         return locationFor(actual);
     }
     else
         return sl;
 }
messageHandler()
virtual QAbstractMessageHandler* QPatternist::ReportContext::messageHandler () const pure virtual
Returns
the QAbstractMessageHandler which functions such as warning() and error() should submit messages to. This function may never return null; a valid QAbstractMessageHandler pointer must always be returned.
Implemented in QPatternist::XsdSchemaContext, QPatternist::GenericStaticContext, QPatternist::DelegatingDynamicContext, QPatternist::GenericDynamicContext, and QPatternist::DelegatingStaticContext.
Referenced by createError(), QPatternist::DelegatingStaticContext::messageHandler(), QPatternist::DelegatingDynamicContext::messageHandler(), and warning().
namePool()
virtual NamePool::Ptr QPatternist::ReportContext::namePool () const pure virtual
Implemented in QPatternist::StaticContext, QPatternist::GenericStaticContext, QPatternist::DynamicContext, QPatternist::DelegatingStaticContext, QPatternist::GenericDynamicContext, QPatternist::DelegatingDynamicContext, and QPatternist::XsdSchemaContext.
Referenced by error().
resolveURI()
QUrl ReportContext::resolveURI (const QUrl & relative, const QUrl & baseURI) const
Resolves relative against baseURI, possibly using a URI resolver.
Definition at line 458 of file qreportcontext.cpp.
Referenced by QPatternist::UnparsedTextAvailableFN::evaluateEBV(), QPatternist::DocAvailableFN::evaluateEBV(), QPatternist::UnparsedTextFN::evaluateSingleton(), QPatternist::DocFN::evaluateSingleton(), and QPatternist::DocFN::typeCheck().
 {
     Q_ASSERT_X(!baseURI.isRelative(), Q_FUNC_INFO,
                "The base URI passed from the engine wasn't absolute.");
     const QAbstractUriResolver *const resolver(uriResolver());
     if(resolver)
     {
         const QUrl final(resolver->resolve(relative, baseURI));
         Q_ASSERT_X(final.isValid() || final.isEmpty(), Q_FUNC_INFO,
                    "The QAbstractUriResolver must return a valid URI.");
         Q_ASSERT_X(!final.isRelative(), Q_FUNC_INFO,
                    "The QAbstractUriResolver must return an absolute URI.");
         return final;
     }
     else
         return baseURI.resolved(relative);
 }
uriResolver()
virtual const QAbstractUriResolver* QPatternist::ReportContext::uriResolver () const pure virtual
The URI resolver in use.
If no URI resolver is in use, a null pointer is returned.
Note
You should probably use resolveURI(), which handles the case of when uriResolver() is null.
Implemented in QPatternist::GenericStaticContext, QPatternist::XsdSchemaContext, QPatternist::DelegatingStaticContext, QPatternist::GenericDynamicContext, and QPatternist::DelegatingDynamicContext.
Referenced by resolveURI(), QPatternist::DelegatingDynamicContext::uriResolver(), and QPatternist::DelegatingStaticContext::uriResolver().
warning()
void ReportContext::warning (const QString & message, const QSourceLocation & sourceLocation = QSourceLocation())
Issues a warning, should not be used excessively. This can be used to communicate that a certain implementation defined feature is unsupported or that a certain expression most likely doesn't do what the users wants, to name a few examples.
See also
XML Path Language (XPath) 2.0, 2.3 Error Handling
Parameters
message the message to be read by the user.
sourceLocation the location of where the warning originates from.
Definition at line 66 of file qreportcontext.cpp.
Referenced by QPatternist::ParserContext::finalizePushedVariable(), and QPatternist::TypeChecker::promotionPossible().
 {
     messageHandler()->message(QtWarningMsg, finalizeDescription(description), QUrl(), sourceLocation);
 }
Friends and Related Functions
Exception
typedef bool Exception related
This is the class type that is being thrown when a query error occur.
Definition at line 2457 of file qreportcontext_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/environment/qreportcontext_p.h
/src/xmlpatterns/environment/qreportcontext.cpp