Qt 4.8: QScriptEnginePrivate Class Reference
QScriptEnginePrivate Class Reference
#include <qscriptengine_p.h>
Public Types
enum ContextFlags { NativeContext = 1, CalledAsConstructorContext = 2, HasScopeContext = 4, ShouldRestoreCallFrame = 8 }
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
void _q_objectDestroyed (QObject *)
void agentDeleted (QScriptEngineAgent *agent)
QScriptValuePrivate * allocateScriptValuePrivate (size_t)
void clearCurrentException ()
void collectGarbage ()
QScriptValue currentException () const
JSC::JSObject * customGlobalObject () const
JSC::JSValue defaultPrototype (int metaTypeId) const
void detachAllRegisteredScriptPrograms ()
void detachAllRegisteredScriptStrings ()
void detachAllRegisteredScriptValues ()
void disposeQObject (QObject *object)
void emitSignalHandlerException ()
JSC::JSValue evaluateHelper (JSC::ExecState *exec, intptr_t sourceId, JSC::EvalExecutable *executable, bool &compile)
void freeScriptValuePrivate (QScriptValuePrivate *p)
JSC::JSObject * getOriginalGlobalObjectProxy ()
JSC::ExecState * globalExec () const
JSC::JSObject * globalObject () const
bool hasDemarshalFunction (int type) const
bool isCollecting () const
void mark (JSC::MarkStack &markStack)
JSC::JSValue newObject ()
JSC::JSValue newQMetaObject (const QMetaObject *metaObject, JSC::JSValue ctor)
JSC::JSValue newQObject (QObject *object, QScriptEngine::ValueOwnership ownership=QScriptEngine::QtOwnership, const QScriptEngine::QObjectWrapOptions &options=0)
JSC::JSValue newVariant (const QVariant &)
JSC::JSValue newVariant (JSC::JSValue objectValue, const QVariant &)
JSC::JSGlobalObject * originalGlobalObject () const
void popContext ()
JSC::CallFrame * pushContext (JSC::CallFrame *exec, JSC::JSValue thisObject, const JSC::ArgList &args, JSC::JSObject *callee, bool calledAsConstructor=false, bool clearScopeChain=false)
JSC native function doesn't have different stackframe or context.
QScript::QObjectData * qobjectData (QObject *object)
QScriptEnginePrivate ()
void registerScriptProgram (QScriptProgramPrivate *program)
void registerScriptString (QScriptStringPrivate *value)
void registerScriptValue (QScriptValuePrivate *value)
void reportAdditionalMemoryCost (int size)
bool scriptConnect (QObject *sender, const char *signal, JSC::JSValue receiver, JSC::JSValue function, Qt::ConnectionType type)
bool scriptConnect (QObject *sender, int index, JSC::JSValue receiver, JSC::JSValue function, JSC::JSValue senderWrapper, Qt::ConnectionType type)
bool scriptConnect (JSC::JSValue signal, JSC::JSValue receiver, JSC::JSValue function, Qt::ConnectionType type)
bool scriptDisconnect (QObject *sender, const char *signal, JSC::JSValue receiver, JSC::JSValue function)
bool scriptDisconnect (QObject *sender, int index, JSC::JSValue receiver, JSC::JSValue function)
bool scriptDisconnect (JSC::JSValue signal, JSC::JSValue receiver, JSC::JSValue function)
QScriptValue scriptValueFromJSCValue (JSC::JSValue value)
JSC::JSValue scriptValueToJSCValue (const QScriptValue &value)
void setCurrentException (QScriptValue exception)
void setDefaultPrototype (int metaTypeId, JSC::JSValue prototype)
void setGlobalObject (JSC::JSObject *object)
QScript::TimeoutCheckerProxy * timeoutChecker () const
QScriptString toStringHandle (const JSC::Identifier &name)
JSC::JSValue toUsableValue (JSC::JSValue value)
If the given value is the original global object, returns the custom global object or a proxy to the original global object; otherwise returns value.
JSC::UString translationContextFromUrl (const JSC::UString &)
void unregisterScriptProgram (QScriptProgramPrivate *program)
void unregisterScriptString (QScriptStringPrivate *value)
void unregisterScriptValue (QScriptValuePrivate *value)
virtual ~QScriptEnginePrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static JSC::JSValue arrayFromStringList (JSC::ExecState *, const QStringList &lst)
static JSC::JSValue arrayFromVariantList (JSC::ExecState *, const QVariantList &lst)
static bool canEvaluate (const QString &program)
static QScriptSyntaxCheckResult checkSyntax (const QString &program)
static uint contextFlags (JSC::ExecState *)
For native context, we use the ReturnValueRegister entry in the stackframe header to store flags.
static QScriptContext * contextForFrame (JSC::ExecState *frame)
static bool convertNumber (qsreal, int type, void *ptr)
static bool convertString (const QString &, int type, void *ptr)
static bool convertToNativeQObject (JSC::ExecState *, JSC::JSValue, const QByteArray &targetType, void **result)
static bool convertValue (JSC::ExecState *, JSC::JSValue value, int type, void *ptr)
static JSC::JSValue create (JSC::ExecState *, int type, const void *ptr)
static QScriptDeclarativeClass * declarativeClass (JSC::JSValue)
static QScriptDeclarativeClass::Object * declarativeObject (JSC::JSValue)
static JSC::ExecState * frameForContext (QScriptContext *context)
static const JSC::ExecState * frameForContext (const QScriptContext *context)
static QScriptEnginePrivate * get (QScriptEngine *q)
static QScriptEngine * get (QScriptEnginePrivate *d)
static bool hasValidCodeBlockRegister (JSC::ExecState *frame)
static bool isArray (JSC::JSValue)
static bool isDate (JSC::JSValue)
static bool isError (JSC::JSValue)
static bool isObject (JSC::JSValue)
static bool isQMetaObject (JSC::JSValue)
static bool isQObject (JSC::JSValue)
static bool isRegExp (JSC::JSValue)
static bool isVariant (JSC::JSValue)
static JSC::JSValue jscValueFromVariant (JSC::ExecState *, const QVariant &value)
static QVariant jscValueToVariant (JSC::ExecState *, JSC::JSValue value, int targetType)
static JSC::JSValue newArray (JSC::ExecState *, uint length)
static JSC::JSValue newDate (JSC::ExecState *, qsreal value)
static JSC::JSValue newDate (JSC::ExecState *, const QDateTime &)
static JSC::JSValue newRegExp (JSC::ExecState *, const QRegExp &)
static JSC::JSValue newRegExp (JSC::ExecState *, const QString &pattern, const QString &flags)
static JSC::JSValue objectFromVariantMap (JSC::ExecState *, const QVariantMap &vmap)
static JSC::JSValue property (JSC::ExecState *, JSC::JSValue, const JSC::Identifier &id, int resolveMode=QScriptValue::ResolvePrototype)
static JSC::JSValue property (JSC::ExecState *, JSC::JSValue, quint32 index, int resolveMode=QScriptValue::ResolvePrototype)
static JSC::JSValue property (JSC::ExecState *, JSC::JSValue, const JSC::UString &, int resolveMode)
static QScriptValue::PropertyFlags propertyFlags (JSC::ExecState *, JSC::JSValue value, const JSC::Identifier &id, const QScriptValue::ResolveFlags &mode)
static QScriptValue::PropertyFlags propertyFlags (JSC::ExecState *, JSC::JSValue value, const JSC::UString &name, const QScriptValue::ResolveFlags &mode)
static unsigned propertyFlagsToJSCAttributes (const QScriptValue::PropertyFlags &flags)
static JSC::JSValue propertyHelper (JSC::ExecState *, JSC::JSValue, const JSC::Identifier &id, int resolveMode)
static JSC::JSValue propertyHelper (JSC::ExecState *, JSC::JSValue, quint32, int resolveMode)
static void restoreException (JSC::ExecState *, JSC::JSValue)
static void saveException (JSC::ExecState *, JSC::JSValue *)
static void setContextFlags (JSC::ExecState *, uint)
static void setProperty (JSC::ExecState *, JSC::JSValue object, const JSC::UString &name, JSC::JSValue, const QScriptValue::PropertyFlags &flags=QScriptValue::KeepExistingFlags)
static void setProperty (JSC::ExecState *, JSC::JSValue object, const JSC::Identifier &id, JSC::JSValue, const QScriptValue::PropertyFlags &flags=QScriptValue::KeepExistingFlags)
static void setProperty (JSC::ExecState *, JSC::JSValue object, quint32 index, JSC::JSValue, const QScriptValue::PropertyFlags &flags=QScriptValue::KeepExistingFlags)
static void setVariantValue (JSC::JSValue objectValue, const QVariant &value)
static QStringList stringListFromArray (JSC::ExecState *, JSC::JSValue arr)
static JSC::JSValue thisForContext (JSC::ExecState *frame)
static JSC::Register * thisRegisterForFrame (JSC::ExecState *frame)
static bool toBool (JSC::ExecState *, JSC::JSValue)
static QDateTime toDateTime (JSC::ExecState *, JSC::JSValue)
static qint32 toInt32 (JSC::ExecState *, JSC::JSValue)
static qsreal toInteger (JSC::ExecState *, JSC::JSValue)
static qsreal toNumber (JSC::ExecState *, JSC::JSValue)
static const QMetaObject * toQMetaObject (JSC::ExecState *, JSC::JSValue)
static QObject * toQObject (JSC::ExecState *, JSC::JSValue)
static QRegExp toRegExp (JSC::ExecState *, JSC::JSValue)
static JSC::UString toString (JSC::ExecState *, JSC::JSValue)
static quint16 toUInt16 (JSC::ExecState *, JSC::JSValue)
static quint32 toUInt32 (JSC::ExecState *, JSC::JSValue)
static QVariant toVariant (JSC::ExecState *, JSC::JSValue)
static QVariantList variantListFromArray (JSC::ExecState *, JSC::JSArray *arr)
static QVariantMap variantMapFromObject (JSC::ExecState *, JSC::JSObject *obj)
static QVariant & variantValue (JSC::JSValue value)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QScriptValue abortResult
QScriptEngineAgent * activeAgent
int agentLineNumber
JSC::UString cachedTranslationContext
JSC::UString cachedTranslationUrl
JSC::ExecState * currentFrame
QSet< QString > extensionsBeingImported
QScriptValuePrivate * freeScriptValues
int freeScriptValuesCount
JSC::JSGlobalData * globalData
QSet< QString > importedExtensions
bool inEval
QHash< intptr_t, QScript::UStringSourceProviderWithFeedback * > loadedScripts
QScriptValue m_currentException
QHash< QObject *, QScript::QObjectData * > m_qobjectData
QHash< int, QScriptTypeInfo * > m_typeInfos
JSC::JSObject * originalGlobalObjectProxy
QList< QScriptEngineAgent * > ownedAgents
int processEventsInterval
QScript::QMetaObjectPrototype * qmetaobjectPrototype
WTF::RefPtr< JSC::Structure > qmetaobjectWrapperObjectStructure
QScript::QObjectPrototype * qobjectPrototype
WTF::RefPtr< JSC::Structure > qobjectWrapperObjectStructure
QSet< QScriptProgramPrivate * > registeredScriptPrograms
QScriptStringPrivate * registeredScriptStrings
QScriptValuePrivate * registeredScriptValues
WTF::RefPtr< JSC::Structure > scriptObjectStructure
WTF::RefPtr< JSC::Structure > staticScopeObjectStructure
QScript::QVariantPrototype * variantPrototype
WTF::RefPtr< JSC::Structure > variantWrapperObjectStructure
QSet< JSC::JSObject * > visitedConversionObjects
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Static Public Variables
static const int maxFreeScriptValues = 256
Detailed Description
Definition at line 148 of file qscriptengine_p.h.
Enumerations
ContextFlags
enum QScriptEnginePrivate::ContextFlags
Enumerator
NativeContext
CalledAsConstructorContext
HasScopeContext
ShouldRestoreCallFrame
Definition at line 258 of file qscriptengine_p.h.
                       {
         NativeContext = 1,
         CalledAsConstructorContext = 2,
         HasScopeContext = 4, // Specifies that the is a QScriptActivationObject
         ShouldRestoreCallFrame = 8
     };
Constructors and Destructors
QScriptEnginePrivate()
QScriptEnginePrivate::QScriptEnginePrivate ()
Definition at line 975 of file qscriptengine.cpp.
     : originalGlobalObjectProxy(0), currentFrame(0),
       qobjectPrototype(0), qmetaobjectPrototype(0), variantPrototype(0),
       activeAgent(0), agentLineNumber(-1),
       registeredScriptValues(0), freeScriptValues(0), freeScriptValuesCount(0),
       registeredScriptStrings(0), processEventsInterval(-1), inEval(false)
 {
     qMetaTypeId<QScriptValue>();
     qMetaTypeId<QList<int> >();
 #ifndef QT_NO_QOBJECT
     qMetaTypeId<QObjectList>();
 #endif
     if (!QCoreApplication::instance()) {
         qFatal("QScriptEngine: Must construct a Q(Core)Application before a QScriptEngine");
         return;
     }
     JSC::initializeThreading();
     JSC::IdentifierTable *oldTable = JSC::currentIdentifierTable();
     globalData = JSC::JSGlobalData::create().releaseRef();
     globalData->clientData = new QScript::GlobalClientData(this);
     JSC::JSGlobalObject *globalObject = new (globalData)QScript::GlobalObject();
     JSC::ExecState* exec = globalObject->globalExec();
     scriptObjectStructure = QScriptObject::createStructure(globalObject->objectPrototype());
     staticScopeObjectStructure = QScriptStaticScopeObject::createStructure(JSC::jsNull());
     qobjectPrototype = new (exec) QScript::QObjectPrototype(exec, QScript::QObjectPrototype::createStructure(globalObject->objectPrototype()), globalObject->prototypeFunctionStructure());
     qobjectWrapperObjectStructure = QScriptObject::createStructure(qobjectPrototype);
     qmetaobjectPrototype = new (exec) QScript::QMetaObjectPrototype(exec, QScript::QMetaObjectPrototype::createStructure(globalObject->objectPrototype()), globalObject->prototypeFunctionStructure());
     qmetaobjectWrapperObjectStructure = QScript::QMetaObjectWrapperObject::createStructure(qmetaobjectPrototype);
     variantPrototype = new (exec) QScript::QVariantPrototype(exec, QScript::QVariantPrototype::createStructure(globalObject->objectPrototype()), globalObject->prototypeFunctionStructure());
     variantWrapperObjectStructure = QScriptObject::createStructure(variantPrototype);
     globalObject->putDirectFunction(exec, new (exec)JSC::NativeFunctionWrapper(exec, globalObject->prototypeFunctionStructure(), 1, JSC::Identifier(exec, "print"), QScript::functionPrint));
     globalObject->putDirectFunction(exec, new (exec)JSC::NativeFunctionWrapper(exec, globalObject->prototypeFunctionStructure(), 0, JSC::Identifier(exec, "gc"), QScript::functionGC));
     globalObject->putDirectFunction(exec, new (exec)JSC::NativeFunctionWrapper(exec, globalObject->prototypeFunctionStructure(), 0, JSC::Identifier(exec, "version"), QScript::functionVersion));
     // ### rather than extending Function.prototype, consider creating a QtSignal.prototype
     globalObject->functionPrototype()->putDirectFunction(exec, new (exec)JSC::NativeFunctionWrapper(exec, globalObject->prototypeFunctionStructure(), 1, JSC::Identifier(exec, "disconnect"), QScript::functionDisconnect));
     globalObject->functionPrototype()->putDirectFunction(exec, new (exec)JSC::NativeFunctionWrapper(exec, globalObject->prototypeFunctionStructure(), 1, JSC::Identifier(exec, "connect"), QScript::functionConnect));
     JSC::TimeoutChecker* originalChecker = globalData->timeoutChecker;
     globalData->timeoutChecker = new QScript::TimeoutCheckerProxy(*originalChecker);
     delete originalChecker;
     currentFrame = exec;
     cachedTranslationUrl = JSC::UString();
     cachedTranslationContext = JSC::UString();
     JSC::setCurrentIdentifierTable(oldTable);
 }
~QScriptEnginePrivate()
QScriptEnginePrivate::~QScriptEnginePrivate () virtual
Definition at line 1031 of file qscriptengine.cpp.
 {
     QScript::APIShim shim(this);
     //disconnect all loadedScripts and generate all jsc::debugger::scriptUnload events
     QHash<intptr_t,QScript::UStringSourceProviderWithFeedback*>::const_iterator it;
     for (it = loadedScripts.constBegin(); it != loadedScripts.constEnd(); ++it)
         it.value()->disconnectFromEngine();
     while (!ownedAgents.isEmpty())
         delete ownedAgents.takeFirst();
     detachAllRegisteredScriptPrograms();
     detachAllRegisteredScriptValues();
     detachAllRegisteredScriptStrings();
     qDeleteAll(m_qobjectData);
     qDeleteAll(m_typeInfos);
     globalData->heap.destroy();
     globalData->deref();
     while (freeScriptValues) {
         QScriptValuePrivate *p = freeScriptValues;
         freeScriptValues = p->next;
         qFree(p);
     }
 }
Functions
_q_objectDestroyed()
void QScriptEnginePrivate::_q_objectDestroyed (QObject * object)
Definition at line 1516 of file qscriptengine.cpp.
Referenced by qobjectData().
 {
     QHash<QObject*, QScript::QObjectData*>::iterator it;
     it = m_qobjectData.find(object);
     Q_ASSERT(it != m_qobjectData.end());
     QScript::QObjectData *data = it.value();
     m_qobjectData.erase(it);
     delete data;
 }
agentDeleted()
void QScriptEnginePrivate::agentDeleted (QScriptEngineAgent * agent)
Definition at line 1359 of file qscriptengine.cpp.
Referenced by QScriptEngineAgent::~QScriptEngineAgent().
 {
     ownedAgents.removeOne(agent);
     if (activeAgent == agent) {
         QScriptEngineAgentPrivate::get(agent)->detach();
         activeAgent = 0;
     }
 }
allocateScriptValuePrivate()
QScriptValuePrivate * QScriptEnginePrivate::allocateScriptValuePrivate (size_t size) inline
Definition at line 591 of file qscriptengine_p.h.
 {
     if (freeScriptValues) {
         QScriptValuePrivate *p = freeScriptValues;
         freeScriptValues = p->next;
         --freeScriptValuesCount;
         return p;
     }
     return reinterpret_cast<QScriptValuePrivate*>(qMalloc(size));
 }
arrayFromStringList()
JSC::JSValue QScriptEnginePrivate::arrayFromStringList (JSC::ExecState * exec, const QStringList & lst) static
Definition at line 1079 of file qscriptengine.cpp.
 {
     JSC::JSValue arr =  newArray(exec, lst.size());
     for (int i = 0; i < lst.size(); ++i)
         setProperty(exec, arr, i, JSC::jsString(exec, lst.at(i)));
     return arr;
 }
arrayFromVariantList()
JSC::JSValue QScriptEnginePrivate::arrayFromVariantList (JSC::ExecState * exec, const QVariantList & lst) static
Definition at line 1096 of file qscriptengine.cpp.
 {
     JSC::JSValue arr = newArray(exec, lst.size());
     for (int i = 0; i < lst.size(); ++i)
         setProperty(exec, arr, i, jscValueFromVariant(exec, lst.at(i)));
     return arr;
 }
canEvaluate()
bool QScriptEnginePrivate::canEvaluate (const QString & program) static
Definition at line 2598 of file qscriptengine.cpp.
Referenced by QScriptEngine::canEvaluate().
 {
     QScript::SyntaxChecker checker;
     QScript::SyntaxChecker::Result result = checker.checkSyntax(program);
     return (result.state != QScript::SyntaxChecker::Intermediate);
 }
checkSyntax()
QScriptSyntaxCheckResult QScriptEnginePrivate::checkSyntax (const QString & program) static
Definition at line 2619 of file qscriptengine.cpp.
Referenced by QScriptEngine::checkSyntax().
 {
     QScript::SyntaxChecker checker;
     QScript::SyntaxChecker::Result result = checker.checkSyntax(program);
     QScriptSyntaxCheckResultPrivate *p = new QScriptSyntaxCheckResultPrivate();
     switch (result.state) {
     case QScript::SyntaxChecker::Error:
         p->state = QScriptSyntaxCheckResult::Error;
         break;
     case QScript::SyntaxChecker::Intermediate:
         p->state = QScriptSyntaxCheckResult::Intermediate;
         break;
     case QScript::SyntaxChecker::Valid:
         p->state = QScriptSyntaxCheckResult::Valid;
         break;
     }
     p->errorLineNumber = result.errorLineNumber;
     p->errorColumnNumber = result.errorColumnNumber;
     p->errorMessage = result.errorMessage;
     return QScriptSyntaxCheckResult(p);
 }
clearCurrentException()
void QScriptEnginePrivate::clearCurrentException () inline
Definition at line 276 of file qscriptengine_p.h.
Referenced by QScriptEngineAgentPrivate::exceptionCatch().
 { m_currentException.d_ptr.reset(); }
collectGarbage()
void QScriptEnginePrivate::collectGarbage ()
Definition at line 1342 of file qscriptengine.cpp.
Referenced by QScript::functionGC().
 {
     QScript::APIShim shim(this);
     globalData->heap.collectAllGarbage();
 }
contextFlags()
uint QScriptEnginePrivate::contextFlags (JSC::ExecState * exec) static
For native context, we use the ReturnValueRegister entry in the stackframe header to store flags.
Warning
This function is not part of the public interface.
We can do that because this header is not used as the native function return their value thought C++
when setting flags, NativeContext should always be set
contextFlags returns 0 for non native context
Definition at line 1260 of file qscriptengine.cpp.
Referenced by QScriptContext::activationObject(), QScriptContext::callee(), QScriptContext::isCalledAsConstructor(), and QScriptContext::setActivationObject().
 {
     if (exec->codeBlock())
         return 0; //js function doesn't have flags
     return exec->returnValueRegister();
 }
contextForFrame()
QScriptContext * QScriptEnginePrivate::contextForFrame (JSC::ExecState * frame) inline static
Definition at line 849 of file qscriptengine_p.h.
Referenced by QScript::ClassObjectDelegate::call(), QScript::DeclarativeObjectDelegate::call(), QScript::ClassObjectDelegate::construct(), QScript::QMetaObjectWrapperObject::execute(), QScript::GlobalObject::getOwnPropertyDescriptor(), QScript::GlobalObject::getOwnPropertySlot(), QScriptContext::parentContext(), QScript::FunctionWrapper::proxyCall(), QScript::FunctionWithArgWrapper::proxyCall(), QScript::FunctionWrapper::proxyConstruct(), QScript::FunctionWithArgWrapper::proxyConstruct(), QScriptDeclarativeClass::pushCleanContext(), and QScriptContextInfoPrivate::QScriptContextInfoPrivate().
 {
     if (frame && frame->callerFrame()->hasHostCallFrameFlag() && !frame->callee()
         && frame->callerFrame()->removeHostCallFrameFlag() == QScript::scriptEngineFromExec(frame)->globalExec()) {
         //skip the "fake" context created in Interpreter::execute.
         frame = frame->callerFrame()->removeHostCallFrameFlag();
     }
     return reinterpret_cast<QScriptContext *>(frame);
 }
convertNumber()
bool QScriptEnginePrivate::convertNumber (qsreal value, int type, void * ptr) static
Definition at line 3347 of file qscriptengine.cpp.
Referenced by QScriptEngine::convertV2().
 {
     switch (QMetaType::Type(type)) {
     case QMetaType::Bool:
         *reinterpret_cast<bool*>(ptr) = QScript::ToBool(value);
         return true;
     case QMetaType::Int:
         *reinterpret_cast<int*>(ptr) = QScript::ToInt32(value);
         return true;
     case QMetaType::UInt:
         *reinterpret_cast<uint*>(ptr) = QScript::ToUInt32(value);
         return true;
     case QMetaType::LongLong:
         *reinterpret_cast<qlonglong*>(ptr) = qlonglong(QScript::ToInteger(value));
         return true;
     case QMetaType::ULongLong:
         *reinterpret_cast<qulonglong*>(ptr) = qulonglong(QScript::ToInteger(value));
         return true;
     case QMetaType::Double:
         *reinterpret_cast<double*>(ptr) = value;
         return true;
     case QMetaType::QString:
         *reinterpret_cast<QString*>(ptr) = QScript::ToString(value);
         return true;
     case QMetaType::Float:
         *reinterpret_cast<float*>(ptr) = value;
         return true;
     case QMetaType::Short:
         *reinterpret_cast<short*>(ptr) = short(QScript::ToInt32(value));
         return true;
     case QMetaType::UShort:
         *reinterpret_cast<unsigned short*>(ptr) = QScript::ToUInt16(value);
         return true;
     case QMetaType::Char:
         *reinterpret_cast<char*>(ptr) = char(QScript::ToInt32(value));
         return true;
     case QMetaType::UChar:
         *reinterpret_cast<unsigned char*>(ptr) = (unsigned char)(QScript::ToInt32(value));
         return true;
     case QMetaType::QChar:
         *reinterpret_cast<QChar*>(ptr) = QChar(QScript::ToUInt16(value));
         return true;
     default:
         break;
     }
     return false;
 }
convertString()
bool QScriptEnginePrivate::convertString (const QString & value, int type, void * ptr) static
Definition at line 3395 of file qscriptengine.cpp.
Referenced by QScriptEngine::convertV2().
 {
     switch (QMetaType::Type(type)) {
     case QMetaType::Bool:
         *reinterpret_cast<bool*>(ptr) = QScript::ToBool(value);
         return true;
     case QMetaType::Int:
         *reinterpret_cast<int*>(ptr) = QScript::ToInt32(value);
         return true;
     case QMetaType::UInt:
         *reinterpret_cast<uint*>(ptr) = QScript::ToUInt32(value);
         return true;
     case QMetaType::LongLong:
         *reinterpret_cast<qlonglong*>(ptr) = qlonglong(QScript::ToInteger(value));
         return true;
     case QMetaType::ULongLong:
         *reinterpret_cast<qulonglong*>(ptr) = qulonglong(QScript::ToInteger(value));
         return true;
     case QMetaType::Double:
         *reinterpret_cast<double*>(ptr) = QScript::ToNumber(value);
         return true;
     case QMetaType::QString:
         *reinterpret_cast<QString*>(ptr) = value;
         return true;
     case QMetaType::Float:
         *reinterpret_cast<float*>(ptr) = QScript::ToNumber(value);
         return true;
     case QMetaType::Short:
         *reinterpret_cast<short*>(ptr) = short(QScript::ToInt32(value));
         return true;
     case QMetaType::UShort:
         *reinterpret_cast<unsigned short*>(ptr) = QScript::ToUInt16(value);
         return true;
     case QMetaType::Char:
         *reinterpret_cast<char*>(ptr) = char(QScript::ToInt32(value));
         return true;
     case QMetaType::UChar:
         *reinterpret_cast<unsigned char*>(ptr) = (unsigned char)(QScript::ToInt32(value));
         return true;
     case QMetaType::QChar:
         *reinterpret_cast<QChar*>(ptr) = QChar(QScript::ToUInt16(value));
         return true;
     default:
         break;
     }
     return false;
 }
convertToNativeQObject()
bool QScriptEnginePrivate::convertToNativeQObject (JSC::ExecState * exec, JSC::JSValue value, const QByteArray & targetType, void ** result) static
Definition at line 1485 of file qscriptengine.cpp.
Referenced by QScript::callQtMethod().
 {
     if (!targetType.endsWith('*'))
         return false;
     if (QObject *qobject = toQObject(exec, value)) {
         int start = targetType.startsWith("const ") ? 6 : 0;
         QByteArray className = targetType.mid(start, targetType.size()-start-1);
         if (void *instance = qobject->qt_metacast(className)) {
             *result = instance;
             return true;
         }
     }
     return false;
 }
convertValue()
bool QScriptEnginePrivate::convertValue (JSC::ExecState * exec, JSC::JSValue value, int type, void * ptr) static
Definition at line 3159 of file qscriptengine.cpp.
Referenced by QScript::callQtMethod(), QScriptEngine::convert(), QScriptEngine::convertV2(), jscValueToVariant(), and QScript::variantFromValue().
 {
     QScriptEnginePrivate *eng = exec ? QScript::scriptEngineFromExec(exec) : 0;
     if (eng) {
         QScriptTypeInfo *info = eng->m_typeInfos.value(type);
         if (info && info->demarshal) {
             info->demarshal(eng->scriptValueFromJSCValue(value), ptr);
             return true;
         }
     }
     // check if it's one of the types we know
     switch (QMetaType::Type(type)) {
     case QMetaType::Bool:
         *reinterpret_cast<bool*>(ptr) = toBool(exec, value);
         return true;
     case QMetaType::Int:
         *reinterpret_cast<int*>(ptr) = toInt32(exec, value);
         return true;
     case QMetaType::UInt:
         *reinterpret_cast<uint*>(ptr) = toUInt32(exec, value);
         return true;
     case QMetaType::LongLong:
         *reinterpret_cast<qlonglong*>(ptr) = qlonglong(toInteger(exec, value));
         return true;
     case QMetaType::ULongLong:
         *reinterpret_cast<qulonglong*>(ptr) = qulonglong(toInteger(exec, value));
         return true;
     case QMetaType::Double:
         *reinterpret_cast<double*>(ptr) = toNumber(exec, value);
         return true;
     case QMetaType::QString:
         if (value.isUndefined() || value.isNull())
             *reinterpret_cast<QString*>(ptr) = QString();
         else
             *reinterpret_cast<QString*>(ptr) = toString(exec, value);
         return true;
     case QMetaType::Float:
         *reinterpret_cast<float*>(ptr) = toNumber(exec, value);
         return true;
     case QMetaType::Short:
         *reinterpret_cast<short*>(ptr) = short(toInt32(exec, value));
         return true;
     case QMetaType::UShort:
         *reinterpret_cast<unsigned short*>(ptr) = QScript::ToUInt16(toNumber(exec, value));
         return true;
     case QMetaType::Char:
         *reinterpret_cast<char*>(ptr) = char(toInt32(exec, value));
         return true;
     case QMetaType::UChar:
         *reinterpret_cast<unsigned char*>(ptr) = (unsigned char)(toInt32(exec, value));
         return true;
     case QMetaType::QChar:
         if (value.isString()) {
             QString str = toString(exec, value);
             *reinterpret_cast<QChar*>(ptr) = str.isEmpty() ? QChar() : str.at(0);
         } else {
             *reinterpret_cast<QChar*>(ptr) = QChar(QScript::ToUInt16(toNumber(exec, value)));
         }
         return true;
     case QMetaType::QDateTime:
         if (isDate(value)) {
             *reinterpret_cast<QDateTime *>(ptr) = toDateTime(exec, value);
             return true;
         } break;
     case QMetaType::QDate:
         if (isDate(value)) {
             *reinterpret_cast<QDate *>(ptr) = toDateTime(exec, value).date();
             return true;
         } break;
 #ifndef QT_NO_REGEXP
     case QMetaType::QRegExp:
         if (isRegExp(value)) {
             *reinterpret_cast<QRegExp *>(ptr) = toRegExp(exec, value);
             return true;
         } break;
 #endif
 #ifndef QT_NO_QOBJECT
     case QMetaType::QObjectStar:
         if (isQObject(value) || value.isNull()) {
             *reinterpret_cast<QObject* *>(ptr) = toQObject(exec, value);
             return true;
         } break;
     case QMetaType::QWidgetStar:
         if (isQObject(value) || value.isNull()) {
             QObject *qo = toQObject(exec, value);
             if (!qo || qo->isWidgetType()) {
                 *reinterpret_cast<QWidget* *>(ptr) = reinterpret_cast<QWidget*>(qo);
                 return true;
             }
         } break;
 #endif
     case QMetaType::QStringList:
         if (isArray(value)) {
             *reinterpret_cast<QStringList *>(ptr) = stringListFromArray(exec, value);
             return true;
         } break;
     case QMetaType::QVariantList:
         if (isArray(value)) {
             *reinterpret_cast<QVariantList *>(ptr) = variantListFromArray(exec, JSC::asArray(value));
             return true;
         } break;
     case QMetaType::QVariantMap:
         if (isObject(value)) {
             *reinterpret_cast<QVariantMap *>(ptr) = variantMapFromObject(exec, JSC::asObject(value));
             return true;
         } break;
     case QMetaType::QVariant:
         *reinterpret_cast<QVariant*>(ptr) = toVariant(exec, value);
         return true;
     default:
     ;
     }
     QByteArray name = QMetaType::typeName(type);
 #ifndef QT_NO_QOBJECT
     if (convertToNativeQObject(exec, value, name, reinterpret_cast<void* *>(ptr)))
         return true;
 #endif
     if (isVariant(value) && name.endsWith('*')) {
         int valueType = QMetaType::type(name.left(name.size()-1));
         QVariant &var = variantValue(value);
         if (valueType == var.userType()) {
             *reinterpret_cast<void* *>(ptr) = var.data();
             return true;
         } else {
             // look in the prototype chain
             JSC::JSValue proto = JSC::asObject(value)->prototype();
             while (proto.isObject()) {
                 bool canCast = false;
                 if (isVariant(proto)) {
                     canCast = (type == variantValue(proto).userType())
                               || (valueType && (valueType == variantValue(proto).userType()));
                 }
 #ifndef QT_NO_QOBJECT
                 else if (isQObject(proto)) {
                     QByteArray className = name.left(name.size()-1);
                     if (QObject *qobject = toQObject(exec, proto))
                         canCast = qobject->qt_metacast(className) != 0;
                 }
 #endif
                 if (canCast) {
                     QByteArray varTypeName = QMetaType::typeName(var.userType());
                     if (varTypeName.endsWith('*'))
                         *reinterpret_cast<void* *>(ptr) = *reinterpret_cast<void* *>(var.data());
                     else
                         *reinterpret_cast<void* *>(ptr) = var.data();
                     return true;
                 }
                 proto = JSC::asObject(proto)->prototype();
             }
         }
     } else if (value.isNull() && name.endsWith('*')) {
         *reinterpret_cast<void* *>(ptr) = 0;
         return true;
     } else if (type == qMetaTypeId<QScriptValue>()) {
         if (!eng)
             return false;
         *reinterpret_cast<QScriptValue*>(ptr) = eng->scriptValueFromJSCValue(value);
         return true;
     }
     // lazy registration of some common list types
 #ifndef QT_NO_QOBJECT
     else if (type == qMetaTypeId<QObjectList>()) {
         if (!eng)
             return false;
         qScriptRegisterSequenceMetaType<QObjectList>(eng->q_func());
         return convertValue(exec, value, type, ptr);
     }
 #endif
     else if (type == qMetaTypeId<QList<int> >()) {
         if (!eng)
             return false;
         qScriptRegisterSequenceMetaType<QList<int> >(eng->q_func());
         return convertValue(exec, value, type, ptr);
     }
 #if 0
     if (!name.isEmpty()) {
         qWarning("QScriptEngine::convert: unable to convert value to type `%s'",
                  name.constData());
     }
 #endif
     return false;
 }
create()
JSC::JSValue QScriptEnginePrivate::create (JSC::ExecState * exec, int type, const void * ptr) static
Definition at line 3056 of file qscriptengine.cpp.
Referenced by QScript::callQtMethod(), and QScript::QObjectConnectionManager::execute().
 {
     Q_ASSERT(ptr != 0);
     JSC::JSValue result;
     QScriptEnginePrivate *eng = exec ? QScript::scriptEngineFromExec(exec) : 0;
     QScriptTypeInfo *info = eng ? eng->m_typeInfos.value(type) : 0;
     if (info && info->marshal) {
         result = eng->scriptValueToJSCValue(info->marshal(eng->q_func(), ptr));
     } else {
         // check if it's one of the types we know
         switch (QMetaType::Type(type)) {
         case QMetaType::Void:
             return JSC::jsUndefined();
         case QMetaType::Bool:
             return JSC::jsBoolean(*reinterpret_cast<const bool*>(ptr));
         case QMetaType::Int:
             return JSC::jsNumber(exec, *reinterpret_cast<const int*>(ptr));
         case QMetaType::UInt:
             return JSC::jsNumber(exec, *reinterpret_cast<const uint*>(ptr));
         case QMetaType::LongLong:
             return JSC::jsNumber(exec, qsreal(*reinterpret_cast<const qlonglong*>(ptr)));
         case QMetaType::ULongLong:
             return JSC::jsNumber(exec, qsreal(*reinterpret_cast<const qulonglong*>(ptr)));
         case QMetaType::Double:
             return JSC::jsNumber(exec, qsreal(*reinterpret_cast<const double*>(ptr)));
         case QMetaType::QString:
             return JSC::jsString(exec, *reinterpret_cast<const QString*>(ptr));
         case QMetaType::Float:
             return JSC::jsNumber(exec, *reinterpret_cast<const float*>(ptr));
         case QMetaType::Short:
             return JSC::jsNumber(exec, *reinterpret_cast<const short*>(ptr));
         case QMetaType::UShort:
             return JSC::jsNumber(exec, *reinterpret_cast<const unsigned short*>(ptr));
         case QMetaType::Char:
             return JSC::jsNumber(exec, *reinterpret_cast<const char*>(ptr));
         case QMetaType::UChar:
             return JSC::jsNumber(exec, *reinterpret_cast<const unsigned char*>(ptr));
         case QMetaType::QChar:
             return JSC::jsNumber(exec, (*reinterpret_cast<const QChar*>(ptr)).unicode());
         case QMetaType::QStringList:
             result = arrayFromStringList(exec, *reinterpret_cast<const QStringList *>(ptr));
             break;
         case QMetaType::QVariantList:
             result = arrayFromVariantList(exec, *reinterpret_cast<const QVariantList *>(ptr));
             break;
         case QMetaType::QVariantMap:
             result = objectFromVariantMap(exec, *reinterpret_cast<const QVariantMap *>(ptr));
             break;
         case QMetaType::QDateTime:
             result = newDate(exec, *reinterpret_cast<const QDateTime *>(ptr));
             break;
         case QMetaType::QDate:
             result = newDate(exec, QDateTime(*reinterpret_cast<const QDate *>(ptr)));
             break;
 #ifndef QT_NO_REGEXP
         case QMetaType::QRegExp:
             result = newRegExp(exec, *reinterpret_cast<const QRegExp *>(ptr));
             break;
 #endif
 #ifndef QT_NO_QOBJECT
         case QMetaType::QObjectStar:
         case QMetaType::QWidgetStar:
             result = eng->newQObject(*reinterpret_cast<QObject* const *>(ptr));
             break;
 #endif
         case QMetaType::QVariant:
             result = eng->newVariant(*reinterpret_cast<const QVariant*>(ptr));
             break;
         default:
             if (type == qMetaTypeId<QScriptValue>()) {
                 result = eng->scriptValueToJSCValue(*reinterpret_cast<const QScriptValue*>(ptr));
                 if (!result)
                     return JSC::jsUndefined();
             }
 #ifndef QT_NO_QOBJECT
             // lazy registration of some common list types
             else if (type == qMetaTypeId<QObjectList>()) {
                 qScriptRegisterSequenceMetaType<QObjectList>(eng->q_func());
                 return create(exec, type, ptr);
             }
 #endif
             else if (type == qMetaTypeId<QList<int> >()) {
                 qScriptRegisterSequenceMetaType<QList<int> >(eng->q_func());
                 return create(exec, type, ptr);
             }
             else {
                 QByteArray typeName = QMetaType::typeName(type);
                 if (typeName.endsWith('*') && !*reinterpret_cast<void* const *>(ptr))
                     return JSC::jsNull();
                 else
                     result = eng->newVariant(QVariant(type, ptr));
             }
         }
     }
     if (result && result.isObject() && info && info->prototype
         && JSC::JSValue::strictEqual(exec, JSC::asObject(result)->prototype(), eng->originalGlobalObject()->objectPrototype())) {
         JSC::asObject(result)->setPrototype(info->prototype);
     }
     return result;
 }
currentException()
QScriptValue QScriptEnginePrivate::currentException () const inline
Definition at line 275 of file qscriptengine_p.h.
 { return m_currentException; }
customGlobalObject()
JSC::JSObject * QScriptEnginePrivate::customGlobalObject () const
Definition at line 1166 of file qscriptengine.cpp.
Referenced by toUsableValue().
 {
     QScript::GlobalObject *glob = static_cast<QScript::GlobalObject*>(originalGlobalObject());
     return glob->customGlobalObject;
 }
declarativeClass()
QScriptDeclarativeClass * QScriptEnginePrivate::declarativeClass (JSC::JSValue v) inline static
Definition at line 1097 of file qscriptengine_p.h.
Referenced by QScriptDeclarativeClass::scriptClass(), and toVariant().
 {
     if (!QScriptEnginePrivate::isObject(v) || !v.inherits(&QScriptObject::info))
         return 0;
     QScriptObject *scriptObject = static_cast<QScriptObject*>(JSC::asObject(v));
     QScriptObjectDelegate *delegate = scriptObject->delegate();
     if (!delegate || (delegate->type() != QScriptObjectDelegate::DeclarativeClassObject))
         return 0;
     return static_cast<QScript::DeclarativeObjectDelegate*>(delegate)->scriptClass();
 }
declarativeObject()
QScriptDeclarativeClass::Object * QScriptEnginePrivate::declarativeObject (JSC::JSValue v) inline static
Definition at line 1108 of file qscriptengine_p.h.
Referenced by QScriptDeclarativeClass::object(), and toVariant().
 {
     if (!QScriptEnginePrivate::isObject(v) || !v.inherits(&QScriptObject::info))
         return 0;
     QScriptObject *scriptObject = static_cast<QScriptObject*>(JSC::asObject(v));
     QScriptObjectDelegate *delegate = scriptObject->delegate();
     if (!delegate || (delegate->type() != QScriptObjectDelegate::DeclarativeClassObject))
         return 0;
     return static_cast<QScript::DeclarativeObjectDelegate*>(delegate)->object();
 }
defaultPrototype()
JSC::JSValue QScriptEnginePrivate::defaultPrototype (int metaTypeId) const
Definition at line 1143 of file qscriptengine.cpp.
Referenced by newQObject(), and newVariant().
 {
     QScriptTypeInfo *info = m_typeInfos.value(metaTypeId);
     if (!info)
         return JSC::JSValue();
     return info->prototype;
 }
detachAllRegisteredScriptPrograms()
void QScriptEnginePrivate::detachAllRegisteredScriptPrograms ()
Definition at line 1606 of file qscriptengine.cpp.
Referenced by ~QScriptEnginePrivate().
 {
     QSet<QScriptProgramPrivate*>::const_iterator it;
     for (it = registeredScriptPrograms.constBegin(); it != registeredScriptPrograms.constEnd(); ++it)
         (*it)->detachFromEngine();
     registeredScriptPrograms.clear();
 }
detachAllRegisteredScriptStrings()
void QScriptEnginePrivate::detachAllRegisteredScriptStrings ()
Definition at line 1627 of file qscriptengine.cpp.
Referenced by ~QScriptEnginePrivate().
 {
     QScriptStringPrivate *it;
     QScriptStringPrivate *next;
     for (it = registeredScriptStrings; it != 0; it = next) {
         it->detachFromEngine();
         next = it->next;
         it->prev = 0;
         it->next = 0;
     }
     registeredScriptStrings = 0;
 }
detachAllRegisteredScriptValues()
void QScriptEnginePrivate::detachAllRegisteredScriptValues ()
Definition at line 1614 of file qscriptengine.cpp.
Referenced by ~QScriptEnginePrivate().
 {
     QScriptValuePrivate *it;
     QScriptValuePrivate *next;
     for (it = registeredScriptValues; it != 0; it = next) {
         it->detachFromEngine();
         next = it->next;
         it->prev = 0;
         it->next = 0;
     }
     registeredScriptValues = 0;
 }
disposeQObject()
void QScriptEnginePrivate::disposeQObject (QObject * object)
Definition at line 1526 of file qscriptengine.cpp.
 {
     // TODO
 /*    if (isCollecting()) {
         // wait until we're done with GC before deleting it
         int index = m_qobjectsToBeDeleted.indexOf(object);
         if (index == -1)
             m_qobjectsToBeDeleted.append(object);
             } else*/ {
         delete object;
     }
 }
emitSignalHandlerException()
void QScriptEnginePrivate::emitSignalHandlerException ()
Definition at line 1539 of file qscriptengine.cpp.
 {
     Q_Q(QScriptEngine);
     emit q->signalHandlerException(q->uncaughtException());
 }
evaluateHelper()
JSC::JSValue QScriptEnginePrivate::evaluateHelper (JSC::ExecState * exec, intptr_t sourceId, JSC::EvalExecutable * executable, bool & compile)
Definition at line 1368 of file qscriptengine.cpp.
 {
     Q_Q(QScriptEngine);
     QBoolBlocker inEvalBlocker(inEval, true);
     q->currentContext()->activationObject(); //force the creation of a context for native function;
     JSC::Debugger* debugger = originalGlobalObject()->debugger();
     if (debugger)
         debugger->evaluateStart(sourceId);
     q->clearExceptions();
     JSC::DynamicGlobalObjectScope dynamicGlobalObjectScope(exec, exec->scopeChain()->globalObject);
     if (compile && !executable->isCompiled()) {
         JSC::JSObject* error = executable->compile(exec, exec->scopeChain());
         if (error) {
             compile = false;
             exec->setException(error);
             if (debugger) {
                 debugger->exceptionThrow(JSC::DebuggerCallFrame(exec, error), sourceId, false);
                 debugger->evaluateStop(error, sourceId);
             }
             return error;
         }
     }
     JSC::JSValue thisValue = thisForContext(exec);
     JSC::JSObject* thisObject = (!thisValue || thisValue.isUndefinedOrNull())
                                 ? exec->dynamicGlobalObject() : thisValue.toObject(exec);
     JSC::JSValue exceptionValue;
     timeoutChecker()->setShouldAbort(false);
     if (processEventsInterval > 0)
         timeoutChecker()->reset();
     JSC::JSValue result = exec->interpreter()->execute(executable, exec, thisObject, exec->scopeChain(), &exceptionValue);
     if (timeoutChecker()->shouldAbort()) {
         if (abortResult.isError())
             exec->setException(scriptValueToJSCValue(abortResult));
         if (debugger)
             debugger->evaluateStop(scriptValueToJSCValue(abortResult), sourceId);
         return scriptValueToJSCValue(abortResult);
     }
     if (exceptionValue) {
         exec->setException(exceptionValue);
         if (debugger)
             debugger->evaluateStop(exceptionValue, sourceId);
         return exceptionValue;
     }
     if (debugger)
         debugger->evaluateStop(result, sourceId);
     Q_ASSERT(!exec->hadException());
     return result;
 }
frameForContext() [1/2]
JSC::ExecState * QScriptEnginePrivate::frameForContext (QScriptContext * context) inline static
Definition at line 859 of file qscriptengine_p.h.
Referenced by QScriptContext::activationObject(), QScriptContext::argumentCount(), QScriptContext::argumentsObject(), QScriptContext::callee(), QScriptContext::engine(), QScriptContext::isCalledAsConstructor(), mark(), QScriptContext::parentContext(), QScriptContext::popScope(), QScriptContext::pushScope(), QScriptContextInfoPrivate::QScriptContextInfoPrivate(), QScriptContext::scopeChain(), QScriptDeclarativeClass::scopeChainValue(), QScriptContext::setActivationObject(), QScriptContext::setReturnValue(), QScriptContext::setThisObject(), QScriptContext::state(), QScriptContext::thisObject(), QScriptContext::throwError(), QScriptContext::throwValue(), QScriptContext::toString(), and QScriptDeclarativeClass::Value::Value().
 {
     return reinterpret_cast<JSC::ExecState*>(context);
 }
frameForContext() [2/2]
const JSC::ExecState * QScriptEnginePrivate::frameForContext (const QScriptContext * context) inline static
Definition at line 864 of file qscriptengine_p.h.
 {
     return reinterpret_cast<const JSC::ExecState*>(context);
 }
freeScriptValuePrivate()
void QScriptEnginePrivate::freeScriptValuePrivate (QScriptValuePrivate * p) inline
Definition at line 602 of file qscriptengine_p.h.
Referenced by QScriptValuePrivate::operator delete().
 {
     if (freeScriptValuesCount < maxFreeScriptValues) {
         p->next = freeScriptValues;
         freeScriptValues = p;
         ++freeScriptValuesCount;
     } else {
         qFree(p);
     }
 }
get() [1/2]
static QScriptEnginePrivate* QScriptEnginePrivate::get (QScriptEngine * q) inline static
Definition at line 158 of file qscriptengine_p.h.
Referenced by QScriptContext::argumentsObject(), QScriptEngineAgentPrivate::attach(), QScript::callQtMethod(), QScriptContext::engine(), QScriptEngineAgent::engine(), QScriptValueIteratorPrivate::engine(), QScriptValue::engine(), QScript::QtPropertyFunction::execute(), QScript::QMetaObjectWrapperObject::execute(), QScriptDeclarativeClass::newStaticScopeObject(), QScript::FunctionWrapper::proxyCall(), QScript::FunctionWithArgWrapper::proxyCall(), QScript::FunctionWrapper::proxyConstruct(), QScript::FunctionWithArgWrapper::proxyConstruct(), QScriptDeclarativeClass::pushCleanContext(), QScriptEngine::qScriptConnect(), QScriptContextInfoPrivate::QScriptContextInfoPrivate(), QScriptEngine::qScriptDisconnect(), QScriptEngineAgent::QScriptEngineAgent(), QScriptDeclarativeClass::Value::toScriptValue(), and QScriptDeclarativeClass::Value::Value().
 { return q ? q->d_func() : 0; }
get() [2/2]
static QScriptEngine* QScriptEnginePrivate::get (QScriptEnginePrivate * d) inline static
Definition at line 159 of file qscriptengine_p.h.
 { return d ? d->q_func() : 0; }
getOriginalGlobalObjectProxy()
JSC::JSObject * QScriptEnginePrivate::getOriginalGlobalObjectProxy ()
Definition at line 1172 of file qscriptengine.cpp.
 {
     if (!originalGlobalObjectProxy) {
         JSC::ExecState* exec = currentFrame;
         originalGlobalObjectProxy = new (exec)QScript::OriginalGlobalObjectProxy(scriptObjectStructure, originalGlobalObject());
     }
     return originalGlobalObjectProxy;
 }
globalExec()
JSC::ExecState * QScriptEnginePrivate::globalExec () const inline
Definition at line 884 of file qscriptengine_p.h.
Referenced by contextForFrame(), and QScriptValueIteratorPrivate::ensureInitialized().
 {
     return originalGlobalObject()->globalExec();
 }
globalObject()
JSC::JSObject * QScriptEnginePrivate::globalObject () const
Definition at line 1181 of file qscriptengine.cpp.
Referenced by mark(), QScriptEnginePrivate(), and setGlobalObject().
 {
     QScript::GlobalObject *glob = static_cast<QScript::GlobalObject*>(originalGlobalObject());
     if (glob->customGlobalObject)
         return glob->customGlobalObject;
     return glob;
 }
hasDemarshalFunction()
bool QScriptEnginePrivate::hasDemarshalFunction (int type) const
Definition at line 3443 of file qscriptengine.cpp.
Referenced by QScript::QtPropertyFunction::execute().
 {
     QScriptTypeInfo *info = m_typeInfos.value(type);
     return info && (info->demarshal != 0);
 }
hasValidCodeBlockRegister()
bool QScriptEnginePrivate::hasValidCodeBlockRegister (JSC::ExecState * frame) inline static
Definition at line 869 of file qscriptengine_p.h.
Referenced by QScriptContext::argumentsObject(), QScript::functionQsTr(), and QScriptContextInfoPrivate::QScriptContextInfoPrivate().
 {
 #if ENABLE(JIT)
     // Frames created by the VM don't have their CodeBlock register
     // initialized. We can detect such frames by checking if the
     // callee is a host JSFunction.
     JSC::JSObject *callee = frame->callee();
     return !(callee && callee->inherits(&JSC::JSFunction::info)
              && JSC::asFunction(callee)->isHostFunction());
 #else
     Q_UNUSED(frame);
     return true;
 #endif
 }
isArray()
bool QScriptEnginePrivate::isArray (JSC::JSValue value) inline static
Definition at line 916 of file qscriptengine_p.h.
Referenced by QScript::callQtMethod(), QScriptValue::isArray(), and toVariant().
 {
     return isObject(value) && value.inherits(&JSC::JSArray::info);
 }
isCollecting()
bool QScriptEnginePrivate::isCollecting () const
Definition at line 1337 of file qscriptengine.cpp.
 {
     return globalData->heap.isBusy();
 }
isDate()
bool QScriptEnginePrivate::isDate (JSC::JSValue value) inline static
Definition at line 921 of file qscriptengine_p.h.
Referenced by QScript::callQtMethod(), QScriptValue::isDate(), and toVariant().
 {
     return isObject(value) && value.inherits(&JSC::DateInstance::info);
 }
isError()
bool QScriptEnginePrivate::isError (JSC::JSValue value) inline static
Definition at line 926 of file qscriptengine_p.h.
Referenced by QScriptValue::isError().
 {
     return isObject(value) && value.inherits(&JSC::ErrorInstance::info);
 }
isObject()
bool QScriptEnginePrivate::isObject (JSC::JSValue value) inline static
Definition at line 911 of file qscriptengine_p.h.
Referenced by declarativeClass(), declarativeObject(), newVariant(), propertyHelper(), and toVariant().
 {
     return value && value.isObject();
 }
isQMetaObject()
bool QScriptEnginePrivate::isQMetaObject (JSC::JSValue value) inline static
Definition at line 960 of file qscriptengine_p.h.
Referenced by QScriptValue::isQMetaObject().
 {
 #ifndef QT_NO_QOBJECT
     return isObject(value) && JSC::asObject(value)->inherits(&QScript::QMetaObjectWrapperObject::info);
 #else
     return false;
 #endif
 }
isQObject()
bool QScriptEnginePrivate::isQObject (JSC::JSValue value) inline static
Definition at line 945 of file qscriptengine_p.h.
Referenced by QScript::callQtMethod(), QScriptValue::isQObject(), and toVariant().
 {
 #ifndef QT_NO_QOBJECT
     if (!isObject(value) || !value.inherits(&QScriptObject::info))
         return false;
     QScriptObject *object = static_cast<QScriptObject*>(JSC::asObject(value));
     QScriptObjectDelegate *delegate = object->delegate();
     return (delegate && (delegate->type() == QScriptObjectDelegate::QtObject ||
                          (delegate->type() == QScriptObjectDelegate::DeclarativeClassObject &&
                           static_cast<QScript::DeclarativeObjectDelegate*>(delegate)->scriptClass()->isQObject())));
 #else
     return false;
 #endif
 }
isRegExp()
bool QScriptEnginePrivate::isRegExp (JSC::JSValue value) inline static
Definition at line 931 of file qscriptengine_p.h.
Referenced by QScript::callQtMethod(), QScriptValue::isRegExp(), toRegExp(), and toVariant().
 {
     return isObject(value) && value.inherits(&JSC::RegExpObject::info);
 }
isVariant()
bool QScriptEnginePrivate::isVariant (JSC::JSValue value) inline static
Definition at line 936 of file qscriptengine_p.h.
Referenced by QScript::callQtMethod(), QScriptValue::isVariant(), jscValueToVariant(), newVariant(), toVariant(), and QScript::variantFromValue().
 {
     if (!isObject(value) || !value.inherits(&QScriptObject::info))
         return false;
     QScriptObject *object = static_cast<QScriptObject*>(JSC::asObject(value));
     QScriptObjectDelegate *delegate = object->delegate();
     return (delegate && (delegate->type() == QScriptObjectDelegate::Variant));
 }
jscValueFromVariant()
JSC::JSValue QScriptEnginePrivate::jscValueFromVariant (JSC::ExecState * exec, const QVariant & value) inline static
Definition at line 634 of file qscriptengine_p.h.
Referenced by arrayFromVariantList(), QScript::ClassObjectDelegate::call(), QScript::callQtMethod(), QScript::QObjectConnectionManager::execute(), QScript::QtPropertyFunction::execute(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertySlot(), and objectFromVariantMap().
 {
     JSC::JSValue result = create(exec, v.userType(), v.data());
     Q_ASSERT(result);
     return result;
 }
jscValueToVariant()
QVariant QScriptEnginePrivate::jscValueToVariant (JSC::ExecState * exec, JSC::JSValue value, int targetType) static
Definition at line 1057 of file qscriptengine.cpp.
 {
     QVariant v(targetType, (void *)0);
     if (convertValue(exec, value, targetType, v.data()))
         return v;
     if (uint(targetType) == QVariant::LastType)
         return toVariant(exec, value);
     if (isVariant(value)) {
         v = variantValue(value);
         if (v.canConvert(QVariant::Type(targetType))) {
             v.convert(QVariant::Type(targetType));
             return v;
         }
         QByteArray typeName = v.typeName();
         if (typeName.endsWith('*')
             && (QMetaType::type(typeName.left(typeName.size()-1)) == targetType)) {
             return QVariant(targetType, *reinterpret_cast<void* *>(v.data()));
         }
     }
     return QVariant();
 }
mark()
void QScriptEnginePrivate::mark (JSC::MarkStack & markStack)
Definition at line 1275 of file qscriptengine.cpp.
 {
     Q_Q(QScriptEngine);
     if (originalGlobalObject()) {
         markStack.append(originalGlobalObject());
         markStack.append(globalObject());
         if (originalGlobalObjectProxy)
             markStack.append(originalGlobalObjectProxy);
     }
     if (qobjectPrototype)
         markStack.append(qobjectPrototype);
     if (qmetaobjectPrototype)
         markStack.append(qmetaobjectPrototype);
     if (variantPrototype)
         markStack.append(variantPrototype);
     {
         QScriptValuePrivate *it;
         for (it = registeredScriptValues; it != 0; it = it->next) {
             if (it->isJSC())
                 markStack.append(it->jscValue);
         }
     }
     {
         QHash<int, QScriptTypeInfo*>::const_iterator it;
         for (it = m_typeInfos.constBegin(); it != m_typeInfos.constEnd(); ++it) {
             if ((*it)->prototype)
                 markStack.append((*it)->prototype);
         }
     }
     if (q) {
         QScriptContext *context = q->currentContext();
         while (context) {
             JSC::ScopeChainNode *node = frameForContext(context)->scopeChain();
             JSC::ScopeChainIterator it(node);
             for (it = node->begin(); it != node->end(); ++it) {
                 JSC::JSObject *object = *it;
                 if (object)
                     markStack.append(object);
             }
             context = context->parentContext();
         }
     }
 #ifndef QT_NO_QOBJECT
     markStack.drain(); // make sure everything is marked before marking qobject data
     {
         QHash<QObject*, QScript::QObjectData*>::const_iterator it;
         for (it = m_qobjectData.constBegin(); it != m_qobjectData.constEnd(); ++it) {
             QScript::QObjectData *qdata = it.value();
             qdata->mark(markStack);
         }
     }
 #endif
 }
newArray()
JSC::JSValue QScriptEnginePrivate::newArray (JSC::ExecState * exec, uint length) inline static
Definition at line 889 of file qscriptengine_p.h.
Referenced by arrayFromStringList(), and arrayFromVariantList().
 {
     return JSC::constructEmptyArray(exec, length);
 }
newDate() [1/2]
JSC::JSValue QScriptEnginePrivate::newDate (JSC::ExecState * exec, qsreal value) inline static
Definition at line 894 of file qscriptengine_p.h.
 {
     JSC::JSValue val = JSC::jsNumber(exec, value);
     JSC::ArgList args(&val, 1);
     return JSC::constructDate(exec, args);
 }
newDate() [2/2]
JSC::JSValue QScriptEnginePrivate::newDate (JSC::ExecState * exec, const QDateTime & value) inline static
Definition at line 901 of file qscriptengine_p.h.
 {
     return newDate(exec, QScript::DateTimeToMs(exec, value));
 }
newObject()
JSC::JSValue QScriptEnginePrivate::newObject () inline
Definition at line 906 of file qscriptengine_p.h.
Referenced by QScriptContext::argumentsObject().
 {
     return new (currentFrame)QScriptObject(scriptObjectStructure);
 }
newQMetaObject()
JSC::JSValue QScriptEnginePrivate::newQMetaObject (const QMetaObject * metaObject, JSC::JSValue ctor)
Definition at line 1475 of file qscriptengine.cpp.
 {
     if (!metaObject)
         return JSC::jsNull();
     JSC::ExecState* exec = currentFrame;
     QScript::QMetaObjectWrapperObject *result = new (exec) QScript::QMetaObjectWrapperObject(exec, metaObject, ctor, qmetaobjectWrapperObjectStructure);
     return result;
 }
newQObject()
JSC::JSValue QScriptEnginePrivate::newQObject (QObject * object, QScriptEngine::ValueOwnership ownership = QScriptEngine::QtOwnership, const QScriptEngine::QObjectWrapOptions & options = 0)
Definition at line 1436 of file qscriptengine.cpp.
Referenced by create(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertySlot(), QScript::qobjectProtoFuncFindChild(), and QScript::qobjectProtoFuncFindChildren().
 {
     if (!object)
         return JSC::jsNull();
     JSC::ExecState* exec = currentFrame;
     QScript::QObjectData *data = qobjectData(object);
     bool preferExisting = (options & QScriptEngine::PreferExistingWrapperObject) != 0;
     QScriptEngine::QObjectWrapOptions opt = options & ~QScriptEngine::PreferExistingWrapperObject;
     QScriptObject *result = 0;
     if (preferExisting) {
         result = data->findWrapper(ownership, opt);
         if (result)
             return result;
     }
     result = new (exec) QScriptObject(qobjectWrapperObjectStructure);
     if (preferExisting)
         data->registerWrapper(result, ownership, opt);
     result->setDelegate(new QScript::QObjectDelegate(object, ownership, options));
     /*if (setDefaultPrototype)*/ {
         const QMetaObject *meta = object->metaObject();
         while (meta) {
             QByteArray typeString = meta->className();
             typeString.append('*');
             int typeId = QMetaType::type(typeString);
             if (typeId != 0) {
                 JSC::JSValue proto = defaultPrototype(typeId);
                 if (proto) {
                     result->setPrototype(proto);
                     break;
                 }
             }
             meta = meta->superClass();
         }
     }
     return result;
 }
newRegExp() [1/2]
JSC::JSValue QScriptEnginePrivate::newRegExp (JSC::ExecState * exec, const QRegExp & regexp) static
Definition at line 1644 of file qscriptengine.cpp.
 {
     JSC::JSValue buf[2];
     JSC::ArgList args(buf, sizeof(buf));
     //convert the pattern to a ECMAScript pattern
     QString pattern = qt_regexp_toCanonical(regexp.pattern(), regexp.patternSyntax());
     if (regexp.isMinimal()) {
         QString ecmaPattern;
         int len = pattern.length();
         ecmaPattern.reserve(len);
         int i = 0;
         const QChar *wc = pattern.unicode();
         bool inBracket = false;
         while (i < len) {
             QChar c = wc[i++];
             ecmaPattern += c;
             switch (c.unicode()) {
             case '?':
             case '+':
             case '*':
             case '}':
                 if (!inBracket)
                     ecmaPattern += QLatin1Char('?');
                 break;
             case '\\':
                 if (i < len)
                     ecmaPattern += wc[i++];
                 break;
             case '[':
                 inBracket = true;
                 break;
             case ']':
                 inBracket = false;
                break;
             default:
                 break;
             }
         }
         pattern = ecmaPattern;
     }
     JSC::UString jscPattern = pattern;
     QString flags;
     if (regexp.caseSensitivity() == Qt::CaseInsensitive)
         flags.append(QLatin1Char('i'));
     JSC::UString jscFlags = flags;
     buf[0] = JSC::jsString(exec, jscPattern);
     buf[1] = JSC::jsString(exec, jscFlags);
     return JSC::constructRegExp(exec, args);
 }
newRegExp() [2/2]
JSC::JSValue QScriptEnginePrivate::newRegExp (JSC::ExecState * exec, const QString & pattern, const QString & flags) static
Definition at line 1698 of file qscriptengine.cpp.
 {
     JSC::JSValue buf[2];
     JSC::ArgList args(buf, sizeof(buf));
     JSC::UString jscPattern = pattern;
     QString strippedFlags;
     if (flags.contains(QLatin1Char('i')))
         strippedFlags += QLatin1Char('i');
     if (flags.contains(QLatin1Char('m')))
         strippedFlags += QLatin1Char('m');
     if (flags.contains(QLatin1Char('g')))
         strippedFlags += QLatin1Char('g');
     JSC::UString jscFlags = strippedFlags;
     buf[0] = JSC::jsString(exec, jscPattern);
     buf[1] = JSC::jsString(exec, jscFlags);
     return JSC::constructRegExp(exec, args);
 }
newVariant() [1/2]
JSC::JSValue QScriptEnginePrivate::newVariant (const QVariant & value)
Definition at line 1716 of file qscriptengine.cpp.
Referenced by QScript::callQtMethod(), create(), and newVariant().
 {
     QScriptObject *obj = new (currentFrame) QScriptObject(variantWrapperObjectStructure);
     obj->setDelegate(new QScript::QVariantDelegate(value));
     JSC::JSValue proto = defaultPrototype(value.userType());
     if (proto)
         obj->setPrototype(proto);
     return obj;
 }
newVariant() [2/2]
JSC::JSValue QScriptEnginePrivate::newVariant (JSC::JSValue objectValue, const QVariant & value)
Definition at line 1726 of file qscriptengine.cpp.
 {
     if (!isObject(objectValue))
         return newVariant(value);
     JSC::JSObject *jscObject = JSC::asObject(objectValue);
     if (!jscObject->inherits(&QScriptObject::info)) {
         qWarning("QScriptEngine::newVariant(): changing class of non-QScriptObject not supported");
         return JSC::JSValue();
     }
     QScriptObject *jscScriptObject = static_cast<QScriptObject*>(jscObject);
     if (!isVariant(objectValue)) {
         jscScriptObject->setDelegate(new QScript::QVariantDelegate(value));
     } else {
         setVariantValue(objectValue, value);
     }
     return objectValue;
 }
objectFromVariantMap()
JSC::JSValue QScriptEnginePrivate::objectFromVariantMap (JSC::ExecState * exec, const QVariantMap & vmap) static
Definition at line 1118 of file qscriptengine.cpp.
 {
     JSC::JSValue obj = JSC::constructEmptyObject(exec);
     QVariantMap::const_iterator it;
     for (it = vmap.constBegin(); it != vmap.constEnd(); ++it)
         setProperty(exec, obj, it.key(), jscValueFromVariant(exec, it.value()));
     return obj;
 }
originalGlobalObject()
JSC::JSGlobalObject * QScriptEnginePrivate::originalGlobalObject () const
Definition at line 1161 of file qscriptengine.cpp.
Referenced by QScriptEngineAgentPrivate::attach(), QScriptContext::callee(), create(), customGlobalObject(), QScriptEngineAgentPrivate::detach(), evaluateHelper(), getOriginalGlobalObjectProxy(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertySlot(), globalObject(), mark(), QScript::FunctionWrapper::proxyConstruct(), QScriptContext::pushScope(), QScript::QObjectDelegate::put(), QScript::qobjectProtoFuncFindChildren(), QScriptContext::setActivationObject(), setGlobalObject(), and toUsableValue().
 {
     return globalData->head;
 }
popContext()
void QScriptEnginePrivate::popContext ()
Warning
This function is not part of the public interface. counter part of QScriptEnginePrivate::pushContext
Definition at line 2868 of file qscriptengine.cpp.
Referenced by QScript::ClassObjectDelegate::call(), QScript::DeclarativeObjectDelegate::call(), QScript::QtFunction::call(), QScript::QMetaObjectWrapperObject::call(), QScript::ClassObjectDelegate::construct(), QScript::QMetaObjectWrapperObject::construct(), QScript::QtPropertyFunction::execute(), QScript::FunctionWrapper::proxyCall(), QScript::FunctionWithArgWrapper::proxyCall(), QScript::FunctionWrapper::proxyConstruct(), and QScript::FunctionWithArgWrapper::proxyConstruct().
 {
     uint flags = contextFlags(currentFrame);
     bool hasScope = flags & HasScopeContext;
     if (flags & ShouldRestoreCallFrame) { //normal case
         JSC::RegisterFile &registerFile = currentFrame->interpreter()->registerFile();
         JSC::Register *const newEnd = currentFrame->registers() - JSC::RegisterFile::CallFrameHeaderSize - currentFrame->argumentCount();
         if (hasScope)
             currentFrame->scopeChain()->pop()->deref();
         registerFile.shrink(newEnd);
     } else if(hasScope) { //the stack frame was created by the Interpreter, we don't need to rewind it.
         currentFrame->setScopeChain(currentFrame->scopeChain()->pop());
         currentFrame->scopeChain()->deref();
     }
     currentFrame = currentFrame->callerFrame();
 }
property() [1/3]
JSC::JSValue QScriptEnginePrivate::property (JSC::ExecState * exec, JSC::JSValue value, const JSC::Identifier & id, int resolveMode = QScriptValue::ResolvePrototype) inline static
Definition at line 720 of file qscriptengine_p.h.
Referenced by QScript::functionConnect(), QScript::functionDisconnect(), QScriptValuePrivate::property(), propertyHelper(), stringListFromArray(), toRegExp(), variantListFromArray(), and variantMapFromObject().
 {
     Q_ASSERT(isObject(value));
     JSC::JSObject *object = JSC::asObject(value);
     JSC::PropertySlot slot(object);
     if ((resolveMode & QScriptValue::ResolvePrototype) && object->getPropertySlot(exec, id, slot))
         return slot.getValue(exec, id);
     return propertyHelper(exec, value, id, resolveMode);
 }
property() [2/3]
JSC::JSValue QScriptEnginePrivate::property (JSC::ExecState * exec, JSC::JSValue value, quint32 index, int resolveMode = QScriptValue::ResolvePrototype) inline static
Definition at line 730 of file qscriptengine_p.h.
 {
     Q_ASSERT(isObject(value));
     JSC::JSObject *object = JSC::asObject(value);
     JSC::PropertySlot slot(object);
     if ((resolveMode & QScriptValue::ResolvePrototype) && object->getPropertySlot(exec, index, slot))
         return slot.getValue(exec, index);
     return propertyHelper(exec, value, index, resolveMode);
 }
property() [3/3]
JSC::JSValue QScriptEnginePrivate::property (JSC::ExecState * exec, JSC::JSValue value, const JSC::UString & name, int resolveMode) inline static
Definition at line 715 of file qscriptengine_p.h.
 {
     return property(exec, value, JSC::Identifier(exec, name), resolveMode);
 }
propertyFlags() [1/2]
QScriptValue::PropertyFlags QScriptEnginePrivate::propertyFlags (JSC::ExecState * exec, JSC::JSValue value, const JSC::Identifier & id, const QScriptValue::ResolveFlags & mode) static
Definition at line 1917 of file qscriptengine.cpp.
Referenced by QScriptValuePrivate::propertyFlags().
 {
     JSC::JSObject *object = JSC::asObject(value);
     unsigned attribs = 0;
     JSC::PropertyDescriptor descriptor;
     if (object->getOwnPropertyDescriptor(exec, id, descriptor))
         attribs = descriptor.attributes();
     else {
         if ((mode & QScriptValue::ResolvePrototype) && object->prototype() && object->prototype().isObject()) {
             JSC::JSValue proto = object->prototype();
             return propertyFlags(exec, proto, id, mode);
         }
         return 0;
     }
     QScriptValue::PropertyFlags result = 0;
     if (attribs & JSC::ReadOnly)
         result |= QScriptValue::ReadOnly;
     if (attribs & JSC::DontEnum)
         result |= QScriptValue::SkipInEnumeration;
     if (attribs & JSC::DontDelete)
         result |= QScriptValue::Undeletable;
     //We cannot rely on attribs JSC::Setter/Getter because they are not necesserly set by JSC (bug?)
     if (attribs & JSC::Getter || !object->lookupGetter(exec, id).isUndefinedOrNull())
         result |= QScriptValue::PropertyGetter;
     if (attribs & JSC::Setter || !object->lookupSetter(exec, id).isUndefinedOrNull())
         result |= QScriptValue::PropertySetter;
 #ifndef QT_NO_QOBJECT
     if (attribs & QScript::QObjectMemberAttribute)
         result |= QScriptValue::QObjectMember;
 #endif
     result |= QScriptValue::PropertyFlag(attribs & QScriptValue::UserRange);
     return result;
 }
propertyFlags() [2/2]
QScriptValue::PropertyFlags QScriptEnginePrivate::propertyFlags (JSC::ExecState * exec, JSC::JSValue value, const JSC::UString & name, const QScriptValue::ResolveFlags & mode) inline static
Definition at line 740 of file qscriptengine_p.h.
 {
     return propertyFlags(exec, value, JSC::Identifier(exec, name), mode);
 }
propertyFlagsToJSCAttributes()
unsigned QScriptEnginePrivate::propertyFlagsToJSCAttributes (const QScriptValue::PropertyFlags & flags) inline static
Definition at line 668 of file qscriptengine_p.h.
Referenced by QScriptDeclarativeClass::newStaticScopeObject(), and setProperty().
 {
     unsigned attribs = 0;
     if (flags & QScriptValue::ReadOnly)
         attribs |= JSC::ReadOnly;
     if (flags & QScriptValue::SkipInEnumeration)
         attribs |= JSC::DontEnum;
     if (flags & QScriptValue::Undeletable)
         attribs |= JSC::DontDelete;
     attribs |= flags & QScriptValue::UserRange;
     return attribs;
 }
propertyHelper() [1/2]
JSC::JSValue QScriptEnginePrivate::propertyHelper (JSC::ExecState * exec, JSC::JSValue value, const JSC::Identifier & id, int resolveMode) static
Definition at line 1794 of file qscriptengine.cpp.
 {
     JSC::JSValue result;
     if (!(resolveMode & QScriptValue::ResolvePrototype)) {
         // Look in the object's own properties
         JSC::JSObject *object = JSC::asObject(value);
         JSC::PropertySlot slot(object);
         if (object->getOwnPropertySlot(exec, id, slot))
             result = slot.getValue(exec, id);
     }
     if (!result && (resolveMode & QScriptValue::ResolveScope)) {
         // ### check if it's a function object and look in the scope chain
         JSC::JSValue scope = property(exec, value, "__qt_scope__", QScriptValue::ResolveLocal);
         if (isObject(scope))
             result = property(exec, scope, id, resolveMode);
     }
     return result;
 }
propertyHelper() [2/2]
JSC::JSValue QScriptEnginePrivate::propertyHelper (JSC::ExecState * exec, JSC::JSValue value, quint32 index, int resolveMode) static
Definition at line 1813 of file qscriptengine.cpp.
 {
     JSC::JSValue result;
     if (!(resolveMode & QScriptValue::ResolvePrototype)) {
         // Look in the object's own properties
         JSC::JSObject *object = JSC::asObject(value);
         JSC::PropertySlot slot(object);
         if (object->getOwnPropertySlot(exec, index, slot))
             result = slot.getValue(exec, index);
     }
     return result;
 }
pushContext()
JSC::CallFrame * QScriptEnginePrivate::pushContext (JSC::CallFrame * exec, JSC::JSValue _thisObject, const JSC::ArgList & args, JSC::JSObject * callee, bool calledAsConstructor = false, bool clearScopeChain = false)
JSC native function doesn't have different stackframe or context.
Warning
This function is not part of the public interface. push a context for a native function. so we need to create one.
use popContext right after to go back to the previous context the context if no stack overflow has hapenned
exec is the current top frame.
return the new top frame. (might be the same as exec if a new stackframe was not needed) or 0 if stack overflow
Definition at line 2778 of file qscriptengine.cpp.
Referenced by QScript::ClassObjectDelegate::call(), QScript::DeclarativeObjectDelegate::call(), QScript::QtFunction::call(), QScript::QMetaObjectWrapperObject::call(), QScript::ClassObjectDelegate::construct(), QScript::QMetaObjectWrapperObject::construct(), QScript::QtPropertyFunction::execute(), QScript::FunctionWrapper::proxyCall(), QScript::FunctionWithArgWrapper::proxyCall(), QScript::FunctionWrapper::proxyConstruct(), QScript::FunctionWithArgWrapper::proxyConstruct(), and QScriptDeclarativeClass::pushCleanContext().
 {
     JSC::JSValue thisObject = _thisObject;
     if (!callee) {
         // callee can't be zero, as this can cause JSC to crash during GC
         // marking phase if the context's Arguments object has been created.
         // Fake it by using the global object. Note that this is also handled
         // in QScriptContext::callee(), as that function should still return
         // an invalid value.
         callee = originalGlobalObject();
     }
     if (calledAsConstructor) {
         //JSC doesn't create default created object for native functions. so we do it
         JSC::JSValue prototype = callee->get(exec, exec->propertyNames().prototype);
         JSC::Structure *structure = prototype.isObject() ? JSC::asObject(prototype)->inheritorID()
                                                          : originalGlobalObject()->emptyObjectStructure();
         thisObject = new (exec) QScriptObject(structure);
     }
     int flags = NativeContext;
     if (calledAsConstructor)
         flags |= CalledAsConstructorContext;
     //build a frame
     JSC::CallFrame *newCallFrame = exec;
     if (callee == 0 //called from  public QScriptEngine::pushContext
         || exec->returnPC() == 0 || (contextFlags(exec) & NativeContext) //called from native-native call
         || (exec->codeBlock() && exec->callee() != callee)) { //the interpreter did not build a frame for us.
         //We need to check if the Interpreter might have already created a frame for function called from JS.
         JSC::Interpreter *interp = exec->interpreter();
         JSC::Register *oldEnd = interp->registerFile().end();
         int argc = args.size() + 1; //add "this"
         JSC::Register *newEnd = oldEnd + argc + JSC::RegisterFile::CallFrameHeaderSize;
         if (!interp->registerFile().grow(newEnd))
             return 0; //### Stack overflow
         newCallFrame = JSC::CallFrame::create(oldEnd);
         newCallFrame[0] = thisObject;
         int dst = 0;
         JSC::ArgList::const_iterator it;
         for (it = args.begin(); it != args.end(); ++it)
             newCallFrame[++dst] = *it;
         newCallFrame += argc + JSC::RegisterFile::CallFrameHeaderSize;
         if (!clearScopeChain) {
             newCallFrame->init(0, /*vPC=*/0, exec->scopeChain(), exec, flags | ShouldRestoreCallFrame, argc, callee);
         } else {
             newCallFrame->init(0, /*vPC=*/0, globalExec()->scopeChain(), exec, flags | ShouldRestoreCallFrame, argc, callee);
         }
     } else {
         setContextFlags(newCallFrame, flags);
 #if ENABLE(JIT)
         exec->registers()[JSC::RegisterFile::Callee] = JSC::JSValue(callee); //JIT let the callee set the 'callee'
 #endif
         if (calledAsConstructor) {
             //update the new created this
             JSC::Register* thisRegister = thisRegisterForFrame(newCallFrame);
             *thisRegister = thisObject;
         }
     }
     currentFrame = newCallFrame;
     return newCallFrame;
 }
qobjectData()
QScript::QObjectData * QScriptEnginePrivate::qobjectData (QObject * object)
Definition at line 1502 of file qscriptengine.cpp.
Referenced by newQObject(), scriptConnect(), and scriptDisconnect().
 {
     QHash<QObject*, QScript::QObjectData*>::const_iterator it;
     it = m_qobjectData.constFind(object);
     if (it != m_qobjectData.constEnd())
         return it.value();
     QScript::QObjectData *data = new QScript::QObjectData(this);
     m_qobjectData.insert(object, data);
     QObject::connect(object, SIGNAL(destroyed(QObject*)),
                      q_func(), SLOT(_q_objectDestroyed(QObject*)));
     return data;
 }
registerScriptProgram()
void QScriptEnginePrivate::registerScriptProgram (QScriptProgramPrivate * program) inline
Definition at line 579 of file qscriptengine_p.h.
Referenced by QScriptProgramPrivate::executable().
 {
     Q_ASSERT(!registeredScriptPrograms.contains(program));
     registeredScriptPrograms.insert(program);
 }
registerScriptString()
void QScriptEnginePrivate::registerScriptString (QScriptStringPrivate * value) inline
Definition at line 826 of file qscriptengine_p.h.
Referenced by toStringHandle().
 {
     Q_ASSERT(value->type == QScriptStringPrivate::HeapAllocated);
     value->prev = 0;
     value->next = registeredScriptStrings;
     if (registeredScriptStrings)
         registeredScriptStrings->prev = value;
     registeredScriptStrings = value;
 }
registerScriptValue()
void QScriptEnginePrivate::registerScriptValue (QScriptValuePrivate * value) inline
Definition at line 613 of file qscriptengine_p.h.
 {
     value->prev = 0;
     value->next = registeredScriptValues;
     if (registeredScriptValues)
         registeredScriptValues->prev = value;
     registeredScriptValues = value;
 }
reportAdditionalMemoryCost()
void QScriptEnginePrivate::reportAdditionalMemoryCost (int size)
Definition at line 1348 of file qscriptengine.cpp.
 {
     if (size > 0)
         globalData->heap.reportExtraMemoryCost(size);
 }
restoreException()
void QScriptEnginePrivate::restoreException (JSC::ExecState * exec, JSC::JSValue val) inline static
Definition at line 820 of file qscriptengine_p.h.
Referenced by QScriptValue::call(), QScriptValue::construct(), QScriptValue::equals(), and QScript::ToPrimitive().
 {
     if (exec && val)
         exec->setException(val);
 }
saveException()
void QScriptEnginePrivate::saveException (JSC::ExecState * exec, JSC::JSValue * val) inline static
Definition at line 810 of file qscriptengine_p.h.
Referenced by QScriptValue::call(), QScriptValue::construct(), QScriptValue::equals(), and QScript::ToPrimitive().
 {
     if (exec) {
         *val = exec->exception();
         exec->clearException();
     } else {
         *val = JSC::JSValue();
     }
 }
scriptConnect() [1/3]
bool QScriptEnginePrivate::scriptConnect (QObject * sender, const char * signal, JSC::JSValue receiver, JSC::JSValue function, Qt::ConnectionType type)
Definition at line 1545 of file qscriptengine.cpp.
Referenced by QScript::functionConnect(), QScriptEngine::qScriptConnect(), and scriptConnect().
 {
     Q_ASSERT(sender);
     Q_ASSERT(signal);
     const QMetaObject *meta = sender->metaObject();
     int index = meta->indexOfSignal(QMetaObject::normalizedSignature(signal+1));
     if (index == -1)
         return false;
     return scriptConnect(sender, index, receiver, function, /*wrapper=*/JSC::JSValue(), type);
 }
scriptConnect() [2/3]
bool QScriptEnginePrivate::scriptConnect (QObject * sender, int index, JSC::JSValue receiver, JSC::JSValue function, JSC::JSValue senderWrapper, Qt::ConnectionType type)
Definition at line 1570 of file qscriptengine.cpp.
 {
     QScript::QObjectData *data = qobjectData(sender);
     return data->addSignalHandler(sender, signalIndex, receiver, function, senderWrapper, type);
 }
scriptConnect() [3/3]
bool QScriptEnginePrivate::scriptConnect (JSC::JSValue signal, JSC::JSValue receiver, JSC::JSValue function, Qt::ConnectionType type)
Definition at line 1588 of file qscriptengine.cpp.
 {
     QScript::QtFunction *fun = static_cast<QScript::QtFunction*>(JSC::asObject(signal));
     int index = fun->mostGeneralMethod();
     return scriptConnect(fun->qobject(), index, receiver, function, fun->wrapperObject(), type);
 }
scriptDisconnect() [1/3]
bool QScriptEnginePrivate::scriptDisconnect (QObject * sender, const char * signal, JSC::JSValue receiver, JSC::JSValue function)
Definition at line 1558 of file qscriptengine.cpp.
Referenced by QScript::functionDisconnect(), QScriptEngine::qScriptDisconnect(), and scriptDisconnect().
 {
     Q_ASSERT(sender);
     Q_ASSERT(signal);
     const QMetaObject *meta = sender->metaObject();
     int index = meta->indexOfSignal(QMetaObject::normalizedSignature(signal+1));
     if (index == -1)
         return false;
     return scriptDisconnect(sender, index, receiver, function);
 }
scriptDisconnect() [2/3]
bool QScriptEnginePrivate::scriptDisconnect (QObject * sender, int index, JSC::JSValue receiver, JSC::JSValue function)
Definition at line 1579 of file qscriptengine.cpp.
 {
     QScript::QObjectData *data = qobjectData(sender);
     if (!data)
         return false;
     return data->removeSignalHandler(sender, signalIndex, receiver, function);
 }
scriptDisconnect() [3/3]
bool QScriptEnginePrivate::scriptDisconnect (JSC::JSValue signal, JSC::JSValue receiver, JSC::JSValue function)
Definition at line 1596 of file qscriptengine.cpp.
 {
     QScript::QtFunction *fun = static_cast<QScript::QtFunction*>(JSC::asObject(signal));
     int index = fun->mostGeneralMethod();
     return scriptDisconnect(fun->qobject(), index, receiver, function);
 }
scriptValueFromJSCValue()
QScriptValue QScriptEnginePrivate::scriptValueFromJSCValue (JSC::JSValue value) inline
Definition at line 641 of file qscriptengine_p.h.
Referenced by QScriptContext::activationObject(), QScriptContext::argumentsObject(), QScript::ClassObjectDelegate::call(), QScript::DeclarativeObjectDelegate::call(), QScriptContext::callee(), convertValue(), QScript::ClassObjectDelegate::deleteProperty(), QScriptEngineAgentPrivate::evaluateStop(), QScriptEngineAgentPrivate::exceptionCatch(), QScriptEngineAgentPrivate::exceptionThrow(), QScriptDeclarativeClass::function(), QScriptEngineAgentPrivate::functionExit(), QScript::ClassObjectDelegate::getOwnPropertyDescriptor(), QScript::ClassObjectDelegate::getOwnPropertyNames(), QScript::ClassObjectDelegate::getOwnPropertySlot(), QScript::ClassObjectDelegate::hasInstance(), QScriptDeclarativeClass::newObject(), QScriptDeclarativeClass::newStaticScopeObject(), QScriptContext::popScope(), QScriptDeclarativeClass::property(), QScript::ClassObjectDelegate::put(), QScript::DeclarativeObjectDelegate::put(), QScriptContext::scopeChain(), QScriptDeclarativeClass::scopeChainValue(), QScriptContext::thisObject(), QScriptContext::throwError(), QScript::ToPrimitive(), and QScriptDeclarativeClass::Value::toScriptValue().
 {
     if (!value)
         return QScriptValue();
     QScriptValuePrivate *p_value = new (this)QScriptValuePrivate(this);
     p_value->initFrom(value);
     return QScriptValuePrivate::toPublic(p_value);
 }
scriptValueToJSCValue()
JSC::JSValue QScriptEnginePrivate::scriptValueToJSCValue (const QScriptValue & value) inline
Definition at line 651 of file qscriptengine_p.h.
Referenced by QScript::ClassObjectDelegate::construct(), create(), evaluateHelper(), QScript::QMetaObjectWrapperObject::execute(), QScript::GlobalObject::getOwnPropertyDescriptor(), QScript::ClassObjectDelegate::getOwnPropertyDescriptor(), QScript::GlobalObject::getOwnPropertySlot(), QScript::ClassObjectDelegate::getOwnPropertySlot(), QScriptDeclarativeClass::newStaticScopeObject(), QScript::FunctionWrapper::proxyCall(), QScript::FunctionWithArgWrapper::proxyCall(), QScript::FunctionWrapper::proxyConstruct(), QScript::FunctionWithArgWrapper::proxyConstruct(), QScriptContext::pushScope(), QScriptEngine::qScriptConnect(), QScriptEngine::qScriptDisconnect(), QScriptContext::setActivationObject(), QScriptContext::setReturnValue(), QScriptContext::setThisObject(), QScriptValue::strictlyEquals(), QScriptContext::throwValue(), and QScriptDeclarativeClass::Value::Value().
 {
     QScriptValuePrivate *vv = QScriptValuePrivate::get(value);
     if (!vv)
         return JSC::JSValue();
     if (vv->type != QScriptValuePrivate::JavaScriptCore) {
         Q_ASSERT(!vv->engine || vv->engine == this);
         vv->engine = this;
         if (vv->type == QScriptValuePrivate::Number) {
             vv->initFrom(JSC::jsNumber(currentFrame, vv->numberValue));
         } else { //QScriptValuePrivate::String
             vv->initFrom(JSC::jsString(currentFrame, vv->stringValue));
         }
     }
     return vv->jscValue;
 }
setContextFlags()
void QScriptEnginePrivate::setContextFlags (JSC::ExecState * exec, uint flags) static
Definition at line 1268 of file qscriptengine.cpp.
Referenced by QScriptContext::activationObject(), and QScriptContext::setActivationObject().
 {
     Q_ASSERT(!exec->codeBlock());
     exec->registers()[JSC::RegisterFile::ReturnValueRegister] = JSC::Register::withInt(flags);
 }
setCurrentException()
void QScriptEnginePrivate::setCurrentException (QScriptValue exception) inline
Definition at line 274 of file qscriptengine_p.h.
Referenced by QScriptEngineAgentPrivate::exceptionThrow().
 { m_currentException = exception; }
setDefaultPrototype()
void QScriptEnginePrivate::setDefaultPrototype (int metaTypeId, JSC::JSValue prototype)
Definition at line 1151 of file qscriptengine.cpp.
 {
     QScriptTypeInfo *info = m_typeInfos.value(metaTypeId);
     if (!info) {
         info = new QScriptTypeInfo();
         m_typeInfos.insert(metaTypeId, info);
     }
     info->prototype = prototype;
 }
setGlobalObject()
void QScriptEnginePrivate::setGlobalObject (JSC::JSObject * object)
Definition at line 1189 of file qscriptengine.cpp.
 {
     if (object == globalObject())
         return;
     QScript::GlobalObject *glob = static_cast<QScript::GlobalObject*>(originalGlobalObject());
     if (object == originalGlobalObjectProxy) {
         glob->customGlobalObject = 0;
         // Sync the internal prototype, since JSObject::prototype() is not virtual.
         glob->setPrototype(originalGlobalObjectProxy->prototype());
     } else {
         Q_ASSERT(object != originalGlobalObject());
         glob->customGlobalObject = object;
         // Sync the internal prototype, since JSObject::prototype() is not virtual.
         glob->setPrototype(object->prototype());
     }
 }
setProperty() [1/3]
void QScriptEnginePrivate::setProperty (JSC::ExecState * exec, JSC::JSValue object, const JSC::UString & name, JSC::JSValue value, const QScriptValue::PropertyFlags & flags = QScriptValue::KeepExistingFlags) inline static
Definition at line 747 of file qscriptengine_p.h.
Referenced by arrayFromStringList(), arrayFromVariantList(), objectFromVariantMap(), QScriptValuePrivate::setProperty(), and setProperty().
 {
     setProperty(exec, objectValue, JSC::Identifier(exec, name), value, flags);
 }
setProperty() [2/3]
void QScriptEnginePrivate::setProperty (JSC::ExecState * exec, JSC::JSValue object, const JSC::Identifier & id, JSC::JSValue value, const QScriptValue::PropertyFlags & flags = QScriptValue::KeepExistingFlags) static
Definition at line 1826 of file qscriptengine.cpp.
 {
     JSC::JSObject *thisObject = JSC::asObject(objectValue);
     JSC::JSValue setter = thisObject->lookupSetter(exec, id);
     JSC::JSValue getter = thisObject->lookupGetter(exec, id);
     if ((flags & QScriptValue::PropertyGetter) || (flags & QScriptValue::PropertySetter)) {
         if (!value) {
             // deleting getter/setter
             if ((flags & QScriptValue::PropertyGetter) && (flags & QScriptValue::PropertySetter)) {
                 // deleting both: just delete the property
                 thisObject->deleteProperty(exec, id);
             } else if (flags & QScriptValue::PropertyGetter) {
                 // preserve setter, if there is one
                 thisObject->deleteProperty(exec, id);
                 if (setter && setter.isObject())
                     thisObject->defineSetter(exec, id, JSC::asObject(setter));
             } else { // flags & QScriptValue::PropertySetter
                 // preserve getter, if there is one
                 thisObject->deleteProperty(exec, id);
                 if (getter && getter.isObject())
                     thisObject->defineGetter(exec, id, JSC::asObject(getter));
             }
         } else {
             if (value.isObject()) { // ### should check if it has callData()
                 // defining getter/setter
                 if (id == exec->propertyNames().underscoreProto) {
                     qWarning("QScriptValue::setProperty() failed: "
                              "cannot set getter or setter of native property `__proto__'");
                 } else {
                     if (flags & QScriptValue::PropertyGetter)
                         thisObject->defineGetter(exec, id, JSC::asObject(value));
                     if (flags & QScriptValue::PropertySetter)
                         thisObject->defineSetter(exec, id, JSC::asObject(value));
                 }
             } else {
                 qWarning("QScriptValue::setProperty(): getter/setter must be a function");
             }
         }
     } else {
         // setting the value
         if (getter && getter.isObject() && !(setter && setter.isObject())) {
             qWarning("QScriptValue::setProperty() failed: "
                      "property '%s' has a getter but no setter",
                      qPrintable(QString(id.ustring())));
             return;
         }
         if (!value) {
             // ### check if it's a getter/setter property
             thisObject->deleteProperty(exec, id);
         } else if (flags != QScriptValue::KeepExistingFlags) {
             if (thisObject->hasOwnProperty(exec, id))
                 thisObject->deleteProperty(exec, id); // ### hmmm - can't we just update the attributes?
             thisObject->putWithAttributes(exec, id, value, propertyFlagsToJSCAttributes(flags));
         } else {
             JSC::PutPropertySlot slot;
             thisObject->put(exec, id, value, slot);
         }
     }
 }
setProperty() [3/3]
void QScriptEnginePrivate::setProperty (JSC::ExecState * exec, JSC::JSValue object, quint32 index, JSC::JSValue value, const QScriptValue::PropertyFlags & flags = QScriptValue::KeepExistingFlags) static
Definition at line 1887 of file qscriptengine.cpp.
 {
     if (!value) {
         JSC::asObject(objectValue)->deleteProperty(exec, index);
     } else {
         if ((flags & QScriptValue::PropertyGetter) || (flags & QScriptValue::PropertySetter)) {
             // fall back to string-based setProperty(), since there is no
             // JSC::JSObject::defineGetter(unsigned)
             setProperty(exec, objectValue, JSC::Identifier::from(exec, index), value, flags);
         } else {
             if (flags != QScriptValue::KeepExistingFlags) {
                 //                if (JSC::asObject(d->jscValue)->hasOwnProperty(exec, arrayIndex))
                 //                    JSC::asObject(d->jscValue)->deleteProperty(exec, arrayIndex);
                 unsigned attribs = 0;
                 if (flags & QScriptValue::ReadOnly)
                     attribs |= JSC::ReadOnly;
                 if (flags & QScriptValue::SkipInEnumeration)
                     attribs |= JSC::DontEnum;
                 if (flags & QScriptValue::Undeletable)
                     attribs |= JSC::DontDelete;
                 attribs |= flags & QScriptValue::UserRange;
                 JSC::asObject(objectValue)->putWithAttributes(exec, index, value, attribs);
             } else {
                 JSC::asObject(objectValue)->put(exec, index, value);
             }
         }
     }
 }
setVariantValue()
void QScriptEnginePrivate::setVariantValue (JSC::JSValue objectValue, const QVariant & value) inline static
Definition at line 1089 of file qscriptengine_p.h.
Referenced by newVariant().
 {
     Q_ASSERT(objectValue.inherits(&QScriptObject::info));
     QScriptObjectDelegate *delegate = static_cast<QScriptObject*>(JSC::asObject(objectValue))->delegate();
     Q_ASSERT(delegate && (delegate->type() == QScriptObjectDelegate::Variant));
     static_cast<QScript::QVariantDelegate*>(delegate)->setValue(value);
 }
stringListFromArray()
QStringList QScriptEnginePrivate::stringListFromArray (JSC::ExecState * exec, JSC::JSValue arr) static
Definition at line 1087 of file qscriptengine.cpp.
 {
     QStringList lst;
     uint len = toUInt32(exec, property(exec, arr, exec->propertyNames().length));
     for (uint i = 0; i < len; ++i)
         lst.append(toString(exec, property(exec, arr, i)));
     return lst;
 }
thisForContext()
JSC::JSValue QScriptEnginePrivate::thisForContext (JSC::ExecState * frame) static
Warning
This function is not part of the public interface. Return the 'this' value for a given context
Definition at line 1231 of file qscriptengine.cpp.
Referenced by evaluateHelper(), and QScriptContext::thisObject().
 {
     if (frame->codeBlock() != 0) {
         return frame->thisValue();
     } else if(frame == frame->lexicalGlobalObject()->globalExec()) {
         return frame->globalThisValue();
     } else {
         JSC::Register *thisRegister = thisRegisterForFrame(frame);
         return thisRegister->jsValue();
     }
 }
thisRegisterForFrame()
JSC::Register * QScriptEnginePrivate::thisRegisterForFrame (JSC::ExecState * frame) static
Definition at line 1243 of file qscriptengine.cpp.
Referenced by QScriptContext::setThisObject(), and thisForContext().
 {
     Q_ASSERT(frame->codeBlock() == 0); // only for native calls
     return frame->registers() - JSC::RegisterFile::CallFrameHeaderSize - frame->argumentCount();
 }
timeoutChecker()
QScript::TimeoutCheckerProxy * QScriptEnginePrivate::timeoutChecker () const
Definition at line 1354 of file qscriptengine.cpp.
Referenced by evaluateHelper().
 {
     return static_cast<QScript::TimeoutCheckerProxy*>(globalData->timeoutChecker);
 }
toBool()
bool QScriptEnginePrivate::toBool (JSC::ExecState * exec, JSC::JSValue value) inline static
Definition at line 969 of file qscriptengine_p.h.
Referenced by QScriptValue::toBool(), QScriptValue::toBoolean(), toRegExp(), and toVariant().
 {
     JSC::JSValue savedException;
     saveException(exec, &savedException);
     bool result = value.toBoolean(exec);
     restoreException(exec, savedException);
     return result;
 }
toDateTime()
QDateTime QScriptEnginePrivate::toDateTime (JSC::ExecState * exec, JSC::JSValue value) inline static
Definition at line 1038 of file qscriptengine_p.h.
Referenced by QScriptValue::toDateTime(), and toVariant().
 {
     if (!isDate(value))
         return QDateTime();
     qsreal t = static_cast<JSC::DateInstance*>(JSC::asObject(value))->internalNumber();
     return QScript::MsToDateTime(exec, t);
 }
toInt32()
qint32 QScriptEnginePrivate::toInt32 (JSC::ExecState * exec, JSC::JSValue value) inline static
Definition at line 996 of file qscriptengine_p.h.
Referenced by QScript::callQtMethod(), QScriptValue::toInt32(), and toVariant().
 {
     JSC::JSValue savedException;
     saveException(exec, &savedException);
     qint32 result = value.toInt32(exec);
     restoreException(exec, savedException);
     return result;
 }
toInteger()
qsreal QScriptEnginePrivate::toInteger (JSC::ExecState * exec, JSC::JSValue value) inline static
Definition at line 978 of file qscriptengine_p.h.
Referenced by QScriptValue::toInteger().
 {
     JSC::JSValue savedException;
     saveException(exec, &savedException);
     qsreal result = value.toInteger(exec);
     restoreException(exec, savedException);
     return result;
 }
toNumber()
qsreal QScriptEnginePrivate::toNumber (JSC::ExecState * exec, JSC::JSValue value) inline static
Definition at line 987 of file qscriptengine_p.h.
Referenced by QScriptValue::toNumber(), and toVariant().
 {
     JSC::JSValue savedException;
     saveException(exec, &savedException);
     qsreal result = value.toNumber(exec);
     restoreException(exec, savedException);
     return result;
 }
toQMetaObject()
const QMetaObject * QScriptEnginePrivate::toQMetaObject (JSC::ExecState * , JSC::JSValue value) inline static
Definition at line 1072 of file qscriptengine_p.h.
Referenced by QScriptValue::toQMetaObject().
 {
 #ifndef QT_NO_QOBJECT
     if (isQMetaObject(value))
         return static_cast<QScript::QMetaObjectWrapperObject*>(JSC::asObject(value))->value();
 #endif
     return 0;
 }
toQObject()
QObject * QScriptEnginePrivate::toQObject (JSC::ExecState * exec, JSC::JSValue value) inline static
Definition at line 1046 of file qscriptengine_p.h.
Referenced by convertToNativeQObject(), QScript::QtPropertyFunction::execute(), QScriptValue::toQObject(), and toVariant().
 {
 #ifndef QT_NO_QOBJECT
     if (isObject(value) && value.inherits(&QScriptObject::info)) {
         QScriptObject *object = static_cast<QScriptObject*>(JSC::asObject(value));
         QScriptObjectDelegate *delegate = object->delegate();
         if (!delegate)
             return 0;
         if (delegate->type() == QScriptObjectDelegate::QtObject)
             return static_cast<QScript::QObjectDelegate*>(delegate)->value();
         if (delegate->type() == QScriptObjectDelegate::DeclarativeClassObject)
             return static_cast<QScript::DeclarativeObjectDelegate*>(delegate)->scriptClass()->toQObject(declarativeObject(value));
         if (delegate->type() == QScriptObjectDelegate::Variant) {
             QVariant var = variantValue(value);
             int type = var.userType();
             if ((type == QMetaType::QObjectStar) || (type == QMetaType::QWidgetStar))
                 return *reinterpret_cast<QObject* const *>(var.constData());
         }
     } else if (isObject(value) && value.inherits(&QScript::QScriptActivationObject::info)) {
         QScript::QScriptActivationObject *proxy = static_cast<QScript::QScriptActivationObject *>(JSC::asObject(value));
         return toQObject(exec, proxy->delegate());
     }
 #endif
     return 0;
 }
toRegExp()
QRegExp QScriptEnginePrivate::toRegExp (JSC::ExecState * exec, JSC::JSValue value) static
Definition at line 1747 of file qscriptengine.cpp.
Referenced by QScriptValue::toRegExp(), and toVariant().
 {
     if (!isRegExp(value))
         return QRegExp();
     QString pattern = toString(exec, property(exec, value, "source", QScriptValue::ResolvePrototype));
     Qt::CaseSensitivity kase = Qt::CaseSensitive;
     if (toBool(exec, property(exec, value, "ignoreCase", QScriptValue::ResolvePrototype)))
         kase = Qt::CaseInsensitive;
     return QRegExp(pattern, kase, QRegExp::RegExp2);
 }
toString()
JSC::UString QScriptEnginePrivate::toString (JSC::ExecState * exec, JSC::JSValue value) inline static
Definition at line 1020 of file qscriptengine_p.h.
Referenced by QScript::callQtMethod(), QScript::functionConnect(), QScript::functionDisconnect(), stringListFromArray(), toRegExp(), QScriptValue::toString(), and toVariant().
 {
     if (!value)
         return JSC::UString();
     JSC::JSValue savedException;
     saveException(exec, &savedException);
     JSC::UString str = value.toString(exec);
     if (exec && exec->hadException() && !str.size()) {
         JSC::JSValue savedException2;
         saveException(exec, &savedException2);
         str = savedException2.toString(exec);
         restoreException(exec, savedException2);
     }
     if (savedException)
         restoreException(exec, savedException);
     return str;
 }
toStringHandle()
QScriptString QScriptEnginePrivate::toStringHandle (const JSC::Identifier & name)
Definition at line 1952 of file qscriptengine.cpp.
 {
     QScriptString result;
     QScriptStringPrivate *p = new QScriptStringPrivate(this, name, QScriptStringPrivate::HeapAllocated);
     QScriptStringPrivate::init(result, p);
     registerScriptString(p);
     return result;
 }
toUInt16()
quint16 QScriptEnginePrivate::toUInt16 (JSC::ExecState * exec, JSC::JSValue value) inline static
Definition at line 1014 of file qscriptengine_p.h.
Referenced by QScriptValue::toUInt16().
 {
     // ### no equivalent function in JSC
     return QScript::ToUInt16(toNumber(exec, value));
 }
toUInt32()
quint32 QScriptEnginePrivate::toUInt32 (JSC::ExecState * exec, JSC::JSValue value) inline static
Definition at line 1005 of file qscriptengine_p.h.
Referenced by stringListFromArray(), QScriptValue::toUInt32(), and variantListFromArray().
 {
     JSC::JSValue savedException;
     saveException(exec, &savedException);
     quint32 result = value.toUInt32(exec);
     restoreException(exec, savedException);
     return result;
 }
toUsableValue()
JSC::JSValue QScriptEnginePrivate::toUsableValue (JSC::JSValue value)
If the given value is the original global object, returns the custom global object or a proxy to the original global object; otherwise returns value.
Warning
This function is not part of the public interface.
Definition at line 1216 of file qscriptengine.cpp.
Referenced by QScript::QMetaObjectWrapperObject::call(), QScript::QtFunction::execute(), QScript::QtPropertyFunction::execute(), QScript::qmetaobjectProtoFuncClassName(), QScript::qobjectProtoFuncFindChild(), QScript::qobjectProtoFuncFindChildren(), QScript::qobjectProtoFuncToString(), QScript::variantProtoFuncToString(), and QScript::variantProtoFuncValueOf().
 {
     if (!value || !value.isObject() || !JSC::asObject(value)->isGlobalObject())
         return value;
     Q_ASSERT(JSC::asObject(value) == originalGlobalObject());
     if (customGlobalObject())
         return customGlobalObject();
     if (!originalGlobalObjectProxy)
         originalGlobalObjectProxy = new (currentFrame)QScript::OriginalGlobalObjectProxy(scriptObjectStructure, originalGlobalObject());
     return originalGlobalObjectProxy;
 }
toVariant()
QVariant QScriptEnginePrivate::toVariant (JSC::ExecState * exec, JSC::JSValue value) static
Definition at line 1760 of file qscriptengine.cpp.
Referenced by QScript::callQtMethod(), QScript::QVariantDelegate::compareToObject(), jscValueToVariant(), QScriptValue::toVariant(), QScript::variantFromValue(), variantListFromArray(), and variantMapFromObject().
 {
     if (!value) {
         return QVariant();
     } else if (isObject(value)) {
         if (isVariant(value))
             return variantValue(value);
 #ifndef QT_NO_QOBJECT
         else if (isQObject(value))
             return QVariant::fromValue(toQObject(exec, value));
 #endif
         else if (isDate(value))
             return QVariant(toDateTime(exec, value));
 #ifndef QT_NO_REGEXP
         else if (isRegExp(value))
             return QVariant(toRegExp(exec, value));
 #endif
         else if (isArray(value))
             return variantListFromArray(exec, JSC::asArray(value));
         else if (QScriptDeclarativeClass *dc = declarativeClass(value))
             return dc->toVariant(declarativeObject(value));
         return variantMapFromObject(exec, JSC::asObject(value));
     } else if (value.isInt32()) {
         return QVariant(toInt32(exec, value));
     } else if (value.isDouble()) {
         return QVariant(toNumber(exec, value));
     } else if (value.isString()) {
         return QVariant(toString(exec, value));
     } else if (value.isBoolean()) {
         return QVariant(toBool(exec, value));
     }
     return QVariant();
 }
translationContextFromUrl()
JSC::UString QScriptEnginePrivate::translationContextFromUrl (const JSC::UString & url)
Definition at line 3449 of file qscriptengine.cpp.
Referenced by QScript::functionQsTr().
 {
     if (url != cachedTranslationUrl) {
         cachedTranslationContext = QFileInfo(url).baseName();
         cachedTranslationUrl = url;
     }
     return cachedTranslationContext;
 }
unregisterScriptProgram()
void QScriptEnginePrivate::unregisterScriptProgram (QScriptProgramPrivate * program) inline
Definition at line 585 of file qscriptengine_p.h.
Referenced by QScriptProgramPrivate::executable(), and QScriptProgramPrivate::~QScriptProgramPrivate().
 {
     Q_ASSERT(registeredScriptPrograms.contains(program));
     registeredScriptPrograms.remove(program);
 }
unregisterScriptString()
void QScriptEnginePrivate::unregisterScriptString (QScriptStringPrivate * value) inline
Definition at line 836 of file qscriptengine_p.h.
 {
     Q_ASSERT(value->type == QScriptStringPrivate::HeapAllocated);
     if (value->prev)
         value->prev->next = value->next;
     if (value->next)
         value->next->prev = value->prev;
     if (value == registeredScriptStrings)
         registeredScriptStrings = value->next;
     value->prev = 0;
     value->next = 0;
 }
unregisterScriptValue()
void QScriptEnginePrivate::unregisterScriptValue (QScriptValuePrivate * value) inline
Definition at line 622 of file qscriptengine_p.h.
 {
     if (value->prev)
         value->prev->next = value->next;
     if (value->next)
         value->next->prev = value->prev;
     if (value == registeredScriptValues)
         registeredScriptValues = value->next;
     value->prev = 0;
     value->next = 0;
 }
variantListFromArray()
QVariantList QScriptEnginePrivate::variantListFromArray (JSC::ExecState * exec, JSC::JSArray * arr) static
Definition at line 1104 of file qscriptengine.cpp.
Referenced by toVariant().
 {
     QScriptEnginePrivate *eng = QScript::scriptEngineFromExec(exec);
     if (eng->visitedConversionObjects.contains(arr))
         return QVariantList(); // Avoid recursion.
     eng->visitedConversionObjects.insert(arr);
     QVariantList lst;
     uint len = toUInt32(exec, property(exec, arr, exec->propertyNames().length));
     for (uint i = 0; i < len; ++i)
         lst.append(toVariant(exec, property(exec, arr, i)));
     eng->visitedConversionObjects.remove(arr);
     return lst;
 }
variantMapFromObject()
QVariantMap QScriptEnginePrivate::variantMapFromObject (JSC::ExecState * exec, JSC::JSObject * obj) static
Definition at line 1127 of file qscriptengine.cpp.
Referenced by toVariant().
 {
     QScriptEnginePrivate *eng = QScript::scriptEngineFromExec(exec);
     if (eng->visitedConversionObjects.contains(obj))
         return QVariantMap(); // Avoid recursion.
     eng->visitedConversionObjects.insert(obj);
     JSC::PropertyNameArray propertyNames(exec);
     obj->getOwnPropertyNames(exec, propertyNames, JSC::IncludeDontEnumProperties);
     QVariantMap vmap;
     JSC::PropertyNameArray::const_iterator it = propertyNames.begin();
     for( ; it != propertyNames.end(); ++it)
         vmap.insert(it->ustring(), toVariant(exec, property(exec, obj, *it)));
     eng->visitedConversionObjects.remove(obj);
     return vmap;
 }
variantValue()
QVariant & QScriptEnginePrivate::variantValue (JSC::JSValue value) inline static
Definition at line 1081 of file qscriptengine_p.h.
Referenced by QScript::callQtMethod(), jscValueToVariant(), toVariant(), and QScript::variantFromValue().
 {
     Q_ASSERT(value.inherits(&QScriptObject::info));
     QScriptObjectDelegate *delegate = static_cast<QScriptObject*>(JSC::asObject(value))->delegate();
     Q_ASSERT(delegate && (delegate->type() == QScriptObjectDelegate::Variant));
     return static_cast<QScript::QVariantDelegate*>(delegate)->value();
 }
Properties
abortResult
QScriptValue QScriptEnginePrivate::abortResult
Definition at line 383 of file qscriptengine_p.h.
Referenced by evaluateHelper().
activeAgent
QScriptEngineAgent* QScriptEnginePrivate::activeAgent
Definition at line 373 of file qscriptengine_p.h.
Referenced by agentDeleted().
agentLineNumber
int QScriptEnginePrivate::agentLineNumber
Definition at line 374 of file qscriptengine_p.h.
Referenced by QScriptEngineAgentPrivate::atStatement(), QScriptEngineAgentPrivate::didReachBreakpoint(), QScriptEngineAgentPrivate::exceptionThrow(), and QScriptContextInfoPrivate::QScriptContextInfoPrivate().
cachedTranslationContext
JSC::UString QScriptEnginePrivate::cachedTranslationContext
Definition at line 387 of file qscriptengine_p.h.
Referenced by QScriptEnginePrivate().
cachedTranslationUrl
JSC::UString QScriptEnginePrivate::cachedTranslationUrl
Definition at line 386 of file qscriptengine_p.h.
Referenced by QScriptEnginePrivate().
currentFrame
JSC::ExecState* QScriptEnginePrivate::currentFrame
Definition at line 358 of file qscriptengine_p.h.
Referenced by QScriptEngineAgentPrivate::atStatement(), QScript::ClassObjectDelegate::call(), QScript::DeclarativeObjectDelegate::call(), QScript::QtFunction::call(), QScript::QMetaObjectWrapperObject::call(), QScript::ClassObjectDelegate::construct(), QScript::QMetaObjectWrapperObject::construct(), QScriptEngine::convertV2(), QScriptDeclarativeClass::createPersistentIdentifier(), QScriptEngineAgentPrivate::didReachBreakpoint(), QScriptValue::equals(), QScriptEngineAgentPrivate::exceptionCatch(), QScriptEngineAgentPrivate::exceptionThrow(), QScript::QtPropertyFunction::execute(), QScriptDeclarativeClass::function(), QScriptDeclarativeClass::functionValue(), getOriginalGlobalObjectProxy(), QScript::GlobalObject::getOwnPropertyDescriptor(), QScript::GlobalObject::getOwnPropertySlot(), QScriptDeclarativeClass::newObject(), QScriptDeclarativeClass::newObjectValue(), newQMetaObject(), newQObject(), QScriptDeclarativeClass::newStaticScopeObject(), newVariant(), QScriptDeclarativeClass::property(), QScriptDeclarativeClass::propertyValue(), QScript::FunctionWrapper::proxyCall(), QScript::FunctionWithArgWrapper::proxyCall(), QScript::FunctionWrapper::proxyConstruct(), QScript::FunctionWithArgWrapper::proxyConstruct(), QScriptDeclarativeClass::pushCleanContext(), QScriptEnginePrivate(), QScriptValue::QScriptValue(), QScript::SaveFrameHelper::SaveFrameHelper(), QScriptValue::strictlyEquals(), QScript::ToPrimitive(), toUsableValue(), and QScriptDeclarativeClass::Value::Value().
extensionsBeingImported
QSet<QString> QScriptEnginePrivate::extensionsBeingImported
Definition at line 390 of file qscriptengine_p.h.
freeScriptValues
QScriptValuePrivate* QScriptEnginePrivate::freeScriptValues
Definition at line 376 of file qscriptengine_p.h.
Referenced by ~QScriptEnginePrivate().
freeScriptValuesCount
int QScriptEnginePrivate::freeScriptValuesCount
Definition at line 378 of file qscriptengine_p.h.
globalData
JSC::JSGlobalData* QScriptEnginePrivate::globalData
Definition at line 356 of file qscriptengine_p.h.
Referenced by QScriptEngineAgentPrivate::attach(), collectGarbage(), isCollecting(), originalGlobalObject(), QScriptEnginePrivate(), reportAdditionalMemoryCost(), timeoutChecker(), and ~QScriptEnginePrivate().
importedExtensions
QSet<QString> QScriptEnginePrivate::importedExtensions
Definition at line 389 of file qscriptengine_p.h.
inEval
bool QScriptEnginePrivate::inEval
Definition at line 384 of file qscriptengine_p.h.
Referenced by evaluateHelper().
loadedScripts
QHash<intptr_t, QScript::UStringSourceProviderWithFeedback*> QScriptEnginePrivate::loadedScripts
Definition at line 392 of file qscriptengine_p.h.
Referenced by QScriptEngineAgentPrivate::atStatement(), QScriptEngineAgentPrivate::didReachBreakpoint(), and ~QScriptEnginePrivate().
m_currentException
QScriptValue QScriptEnginePrivate::m_currentException
Definition at line 393 of file qscriptengine_p.h.
m_qobjectData
QHash<QObject*, QScript::QObjectData*> QScriptEnginePrivate::m_qobjectData
Definition at line 398 of file qscriptengine_p.h.
Referenced by _q_objectDestroyed(), mark(), qobjectData(), and ~QScriptEnginePrivate().
m_typeInfos
QHash<int, QScriptTypeInfo*> QScriptEnginePrivate::m_typeInfos
Definition at line 381 of file qscriptengine_p.h.
Referenced by convertValue(), create(), defaultPrototype(), mark(), setDefaultPrototype(), and ~QScriptEnginePrivate().
maxFreeScriptValues
const int QScriptEnginePrivate::maxFreeScriptValues = 256 static
Definition at line 377 of file qscriptengine_p.h.
originalGlobalObjectProxy
JSC::JSObject* QScriptEnginePrivate::originalGlobalObjectProxy
Definition at line 357 of file qscriptengine_p.h.
Referenced by getOriginalGlobalObjectProxy(), mark(), QScriptContext::pushScope(), QScriptContext::setActivationObject(), setGlobalObject(), and toUsableValue().
ownedAgents
QList<QScriptEngineAgent*> QScriptEnginePrivate::ownedAgents
Definition at line 372 of file qscriptengine_p.h.
Referenced by agentDeleted(), QScriptEngineAgent::QScriptEngineAgent(), and ~QScriptEnginePrivate().
processEventsInterval
int QScriptEnginePrivate::processEventsInterval
Definition at line 382 of file qscriptengine_p.h.
Referenced by evaluateHelper().
qmetaobjectPrototype
QScript::QMetaObjectPrototype* QScriptEnginePrivate::qmetaobjectPrototype
Definition at line 366 of file qscriptengine_p.h.
Referenced by mark(), and QScriptEnginePrivate().
qmetaobjectWrapperObjectStructure
WTF::RefPtr<JSC::Structure> QScriptEnginePrivate::qmetaobjectWrapperObjectStructure
Definition at line 367 of file qscriptengine_p.h.
Referenced by newQMetaObject(), and QScriptEnginePrivate().
qobjectPrototype
QScript::QObjectPrototype* QScriptEnginePrivate::qobjectPrototype
Definition at line 363 of file qscriptengine_p.h.
Referenced by mark(), and QScriptEnginePrivate().
qobjectWrapperObjectStructure
WTF::RefPtr<JSC::Structure> QScriptEnginePrivate::qobjectWrapperObjectStructure
Definition at line 364 of file qscriptengine_p.h.
Referenced by newQObject(), and QScriptEnginePrivate().
registeredScriptPrograms
QSet<QScriptProgramPrivate*> QScriptEnginePrivate::registeredScriptPrograms
Definition at line 380 of file qscriptengine_p.h.
Referenced by detachAllRegisteredScriptPrograms().
registeredScriptStrings
QScriptStringPrivate* QScriptEnginePrivate::registeredScriptStrings
Definition at line 379 of file qscriptengine_p.h.
Referenced by detachAllRegisteredScriptStrings().
registeredScriptValues
QScriptValuePrivate* QScriptEnginePrivate::registeredScriptValues
Definition at line 375 of file qscriptengine_p.h.
Referenced by detachAllRegisteredScriptValues(), and mark().
scriptObjectStructure
WTF::RefPtr<JSC::Structure> QScriptEnginePrivate::scriptObjectStructure
Definition at line 360 of file qscriptengine_p.h.
Referenced by getOriginalGlobalObjectProxy(), QScriptDeclarativeClass::newObject(), QScriptDeclarativeClass::newObjectValue(), QScriptEnginePrivate(), and toUsableValue().
staticScopeObjectStructure
WTF::RefPtr<JSC::Structure> QScriptEnginePrivate::staticScopeObjectStructure
Definition at line 361 of file qscriptengine_p.h.
Referenced by QScriptDeclarativeClass::newStaticScopeObject(), and QScriptEnginePrivate().
variantPrototype
QScript::QVariantPrototype* QScriptEnginePrivate::variantPrototype
Definition at line 369 of file qscriptengine_p.h.
Referenced by mark(), and QScriptEnginePrivate().
variantWrapperObjectStructure
WTF::RefPtr<JSC::Structure> QScriptEnginePrivate::variantWrapperObjectStructure
Definition at line 370 of file qscriptengine_p.h.
Referenced by newVariant(), and QScriptEnginePrivate().
visitedConversionObjects
QSet<JSC::JSObject*> QScriptEnginePrivate::visitedConversionObjects
Definition at line 395 of file qscriptengine_p.h.
Referenced by variantListFromArray(), and variantMapFromObject().
The documentation for this class was generated from the following files:
/src/script/api/qscriptengine_p.h
/src/script/api/qscriptengine.cpp