Qt 4.8: QSvgFont Class Reference
QSvgFont Class Reference
#include <qsvgfont_p.h>
Public Functions
void addGlyph (QChar unicode, const QPainterPath &path, qreal horizAdvX=-1)
void draw (QPainter *p, const QPointF &point, const QString &str, qreal pixelSize, Qt::Alignment alignment) const
QString familyName () const
QSvgFont (qreal horizAdvX)
void setFamilyName (const QString &name)
void setUnitsPerEm (qreal upem)
Public Functions inherited from QSvgRefCounted
void deref ()
QSvgRefCounted ()
void ref ()
virtual ~QSvgRefCounted ()
Public Variables
qreal m_ascent
qreal m_descent
QString m_familyName
QHash< QChar, QSvgGlyph > m_glyphs
qreal m_horizAdvX
qreal m_unitsPerEm
Detailed Description
Definition at line 78 of file qsvgfont_p.h.
Constructors and Destructors
QSvgFont()
QSvgFont::QSvgFont (qreal horizAdvX)
Definition at line 60 of file qsvgfont.cpp.
     : m_horizAdvX(horizAdvX)
 {
 }
Functions
addGlyph()
void QSvgFont::addGlyph (QChar unicode, const QPainterPath & path, qreal horizAdvX = -1)
Definition at line 72 of file qsvgfont.cpp.
Referenced by createSvgGlyph().
 {
     m_glyphs.insert(unicode, QSvgGlyph(unicode, path,
                                        (horizAdvX==-1)?m_horizAdvX:horizAdvX));
 }
draw()
void QSvgFont::draw (QPainter * p, const QPointF & point, const QString & str, qreal pixelSize, Qt::Alignment alignment) const
Definition at line 79 of file qsvgfont.cpp.
Referenced by QSvgText::draw().
 {
     p->save();
     p->translate(point);
     p->scale(pixelSize / m_unitsPerEm, -pixelSize / m_unitsPerEm);
     // Calculate the text width to be used for alignment
     int textWidth = 0;
     QString::const_iterator itr = str.constBegin();
     for ( ; itr != str.constEnd(); ++itr) {
         QChar unicode = *itr;
         if (!m_glyphs.contains(*itr)) {
             unicode = 0;
             if (!m_glyphs.contains(unicode))
                 continue;
         }
         textWidth += static_cast<int>(m_glyphs[unicode].m_horizAdvX);
     }
     QPoint alignmentOffset(0, 0);
     if (alignment == Qt::AlignHCenter) {
         alignmentOffset.setX(-textWidth / 2);
     } else if (alignment == Qt::AlignRight) {
         alignmentOffset.setX(-textWidth);
     }
     p->translate(alignmentOffset);
     // since in SVG the embedded font ain't really a path
     // the outline has got to stay untransformed...
     qreal penWidth = p->pen().widthF();
     penWidth /= (pixelSize/m_unitsPerEm);
     QPen pen = p->pen();
     pen.setWidthF(penWidth);
     p->setPen(pen);
     itr = str.constBegin();
     for ( ; itr != str.constEnd(); ++itr) {
         QChar unicode = *itr;
         if (!m_glyphs.contains(*itr)) {
             unicode = 0;
             if (!m_glyphs.contains(unicode))
                 continue;
         }
         p->drawPath(m_glyphs[unicode].m_path);
         p->translate(m_glyphs[unicode].m_horizAdvX, 0);
     }
     p->restore();
 }
familyName()
QString QSvgFont::familyName () const
Definition at line 66 of file qsvgfont.cpp.
Referenced by QSvgTinyDocument::addSvgFont(), createFontNode(), parseFontFaceNameNode(), and parseFontFaceNode().
 {
     return m_familyName;
 }
setFamilyName()
void QSvgFont::setFamilyName (const QString & name)
Definition at line 130 of file qsvgfont.cpp.
Referenced by createFontNode(), parseFontFaceNameNode(), and parseFontFaceNode().
 {
     m_familyName = name;
 }
setUnitsPerEm()
void QSvgFont::setUnitsPerEm (qreal upem)
Definition at line 135 of file qsvgfont.cpp.
Referenced by parseFontFaceNode().
 {
     m_unitsPerEm = upem;
 }
Properties
m_ascent
qreal QSvgFont::m_ascent
Definition at line 94 of file qsvgfont_p.h.
m_descent
qreal QSvgFont::m_descent
Definition at line 95 of file qsvgfont_p.h.
m_familyName
QString QSvgFont::m_familyName
Definition at line 92 of file qsvgfont_p.h.
Referenced by familyName(), and setFamilyName().
m_glyphs
QHash<QChar, QSvgGlyph> QSvgFont::m_glyphs
Definition at line 97 of file qsvgfont_p.h.
Referenced by addGlyph(), and draw().
m_horizAdvX
qreal QSvgFont::m_horizAdvX
Definition at line 96 of file qsvgfont_p.h.
Referenced by addGlyph(), and draw().
m_unitsPerEm
qreal QSvgFont::m_unitsPerEm
Definition at line 93 of file qsvgfont_p.h.
Referenced by draw(), and setUnitsPerEm().
The documentation for this class was generated from the following files:
/src/svg/qsvgfont_p.h
/src/svg/qsvgfont.cpp