Qt 4.8: QTextCharFormat Class Reference
QTextCharFormat Class Reference
The QTextCharFormat class provides formatting information for characters in a QTextDocument.
#include <qtextformat.h>
Public Types
enum UnderlineStyle {
NoUnderline, SingleUnderline, DashUnderline, DotLine,
DashDotLine, DashDotDotLine, WaveUnderline, SpellCheckUnderline
}
This enum describes the different ways drawing underlined text.
enum VerticalAlignment {
AlignNormal = 0, AlignSuperScript, AlignSubScript, AlignMiddle,
AlignTop, AlignBottom, AlignBaseline
}
This enum describes the ways that adjacent characters can be vertically aligned.
Public Types inherited from QTextFormat
enum FormatType {
InvalidFormat = -1, BlockFormat = 1, CharFormat = 2, ListFormat = 3,
TableFormat = 4, FrameFormat = 5, UserFormat = 100
}
This enum describes the text item a QTextFormat object is formatting.
enum ObjectTypes {
NoObject, ImageObject, TableObject, TableCellObject,
UserObject = 0x1000
}
This enum describes what kind of QTextObject this format is associated with.
enum PageBreakFlag { PageBreak_Auto = 0, PageBreak_AlwaysBefore = 0x001, PageBreak_AlwaysAfter = 0x010 }
This enum describes how page breaking is performed when printing.
enum Property {
ObjectIndex = 0x0, CssFloat = 0x0800, LayoutDirection = 0x0801, OutlinePen = 0x810,
BackgroundBrush = 0x820, ForegroundBrush = 0x821, BackgroundImageUrl = 0x823, BlockAlignment = 0x1010,
BlockTopMargin = 0x1030, BlockBottomMargin = 0x1031, BlockLeftMargin = 0x1032, BlockRightMargin = 0x1033,
TextIndent = 0x1034, TabPositions = 0x1035, BlockIndent = 0x1040, LineHeight = 0x1048,
LineHeightType = 0x1049, BlockNonBreakableLines = 0x1050, BlockTrailingHorizontalRulerWidth = 0x1060, FirstFontProperty = 0x1FE0,
FontCapitalization = FirstFontProperty, FontLetterSpacing = 0x1FE1, FontWordSpacing = 0x1FE2, FontStyleHint = 0x1FE3,
FontStyleStrategy = 0x1FE4, FontKerning = 0x1FE5, FontHintingPreference = 0x1FE6, FontFamily = 0x2000,
FontPointSize = 0x2001, FontSizeAdjustment = 0x2002, FontSizeIncrement = FontSizeAdjustment, FontWeight = 0x2003,
FontItalic = 0x2004, FontUnderline = 0x2005, FontOverline = 0x2006, FontStrikeOut = 0x2007,
FontFixedPitch = 0x2008, FontPixelSize = 0x2009, LastFontProperty = FontPixelSize, TextUnderlineColor = 0x2010,
TextVerticalAlignment = 0x2021, TextOutline = 0x2022, TextUnderlineStyle = 0x2023, TextToolTip = 0x2024,
IsAnchor = 0x2030, AnchorHref = 0x2031, AnchorName = 0x2032, ObjectType = 0x2f00,
ListStyle = 0x3000, ListIndent = 0x3001, ListNumberPrefix = 0x3002, ListNumberSuffix = 0x3003,
FrameBorder = 0x4000, FrameMargin = 0x4001, FramePadding = 0x4002, FrameWidth = 0x4003,
FrameHeight = 0x4004, FrameTopMargin = 0x4005, FrameBottomMargin = 0x4006, FrameLeftMargin = 0x4007,
FrameRightMargin = 0x4008, FrameBorderBrush = 0x4009, FrameBorderStyle = 0x4010, TableColumns = 0x4100,
TableColumnWidthConstraints = 0x4101, TableCellSpacing = 0x4102, TableCellPadding = 0x4103, TableHeaderRowCount = 0x4104,
TableCellRowSpan = 0x4810, TableCellColumnSpan = 0x4811, TableCellTopPadding = 0x4812, TableCellBottomPadding = 0x4813,
TableCellLeftPadding = 0x4814, TableCellRightPadding = 0x4815, ImageName = 0x5000, ImageWidth = 0x5010,
ImageHeight = 0x5011, FullWidthSelection = 0x06000, PageBreakPolicy = 0x7000, UserProperty = 0x100000
}
This enum describes the different properties a format can have.
Public Functions
QString anchorHref () const
Returns the text format's hypertext link, or an empty string if none has been set.
QString anchorName () const
This function is deprecated.
QStringList anchorNames () const
Returns the anchor names associated with this text format, or an empty string list if none has been set.
QFont font () const
Returns the font for this character format.
QFont::Capitalization fontCapitalization () const
Returns the current capitalization type of the font.
QString fontFamily () const
Returns the text format's font family.
bool fontFixedPitch () const
Returns true if the text format's font is fixed pitch; otherwise returns false.
QFont::HintingPreference fontHintingPreference () const
Returns the hinting preference set for this text format.
bool fontItalic () const
Returns true if the text format's font is italic; otherwise returns false.
bool fontKerning () const
Returns true if the font kerning is enabled.
qreal fontLetterSpacing () const
Returns the current letter spacing percentage.
bool fontOverline () const
Returns true if the text format's font is overlined; otherwise returns false.
qreal fontPointSize () const
Returns the font size used to display text in this format.
bool fontStrikeOut () const
Returns true if the text format's font is struck out (has a horizontal line drawn through it); otherwise returns false.
QFont::StyleHint fontStyleHint () const
Returns the font style hint.
QFont::StyleStrategy fontStyleStrategy () const
Returns the current font style strategy.
bool fontUnderline () const
Returns true if the text format's font is underlined; otherwise returns false.
int fontWeight () const
Returns the text format's font weight.
qreal fontWordSpacing () const
Returns the current word spacing value.
bool isAnchor () const
Returns true if the text is formatted as an anchor; otherwise returns false.
bool isValid () const
Returns true if this character format is valid; otherwise returns false.
QTextCharFormat ()
Constructs a new character format object.
void setAnchor (bool anchor)
If anchor is true, text with this format represents an anchor, and is formatted in the appropriate way; otherwise the text is formatted normally.
void setAnchorHref (const QString &value)
Sets the hypertext link for the text format to the given value.
void setAnchorName (const QString &name)
This function is deprecated.
void setAnchorNames (const QStringList &names)
Sets the text format's anchor names.
void setFont (const QFont &font)
Sets the text format's font.
void setFontCapitalization (QFont::Capitalization capitalization)
Sets the capitalization of the text that apppears in this font to capitalization.
void setFontFamily (const QString &family)
Sets the text format's font family.
void setFontFixedPitch (bool fixedPitch)
If fixedPitch is true, sets the text format's font to be fixed pitch; otherwise a non-fixed pitch font is used.
void setFontHintingPreference (QFont::HintingPreference hintingPreference)
Sets the hinting preference of the text format's font to be hintingPreference.
void setFontItalic (bool italic)
If italic is true, sets the text format's font to be italic; otherwise the font will be non-italic.
void setFontKerning (bool enable)
Enables kerning for this font if enable is true; otherwise disables it.
void setFontLetterSpacing (qreal spacing)
Sets the letter spacing of this format to the given spacing, in percent.
void setFontOverline (bool overline)
If overline is true, sets the text format's font to be overlined; otherwise the font is displayed non-overlined.
void setFontPointSize (qreal size)
Sets the text format's font size.
void setFontStrikeOut (bool strikeOut)
If strikeOut is true, sets the text format's font with strike-out enabled (with a horizontal line through it); otherwise it is displayed without strikeout.
void setFontStyleHint (QFont::StyleHint hint, QFont::StyleStrategy strategy=QFont::PreferDefault)
Sets the font style hint and strategy.
void setFontStyleStrategy (QFont::StyleStrategy strategy)
Sets the font style strategy.
void setFontUnderline (bool underline)
If underline is true, sets the text format's font to be underlined; otherwise it is displayed non-underlined.
void setFontWeight (int weight)
Sets the text format's font weight to weight.
void setFontWordSpacing (qreal spacing)
Sets the word spacing of this format to the given spacing, in pixels.
void setTableCellColumnSpan (int tableCellColumnSpan)
If this character format is applied to characters in a table cell, the cell will span tableCellColumnSpan columns.
void setTableCellRowSpan (int tableCellRowSpan)
If this character format is applied to characters in a table cell, the cell will span tableCellRowSpan rows.
void setTextOutline (const QPen &pen)
Sets the pen used to draw the outlines of characters to the given pen.
void setToolTip (const QString &tip)
Sets the tool tip for a fragment of text to the given text.
void setUnderlineColor (const QColor &color)
Sets the underline color used for the characters with this format to the color specified.
void setUnderlineStyle (UnderlineStyle style)
Sets the style of underlining the text to style.
void setVerticalAlignment (VerticalAlignment alignment)
Sets the vertical alignment used for the characters with this format to the alignment specified.
int tableCellColumnSpan () const
If this character format is applied to characters in a table cell, this function returns the number of columns spanned by the text (this may be 1); otherwise it returns 1.
int tableCellRowSpan () const
If this character format is applied to characters in a table cell, this function returns the number of rows spanned by the text (this may be 1); otherwise it returns 1.
QPen textOutline () const
Returns the pen used to draw the outlines of characters in this format.
QString toolTip () const
Returns the tool tip that is displayed for a fragment of text.
QColor underlineColor () const
Returns the color used to underline the characters with this format.
UnderlineStyle underlineStyle () const
Returns the style of underlining the text.
VerticalAlignment verticalAlignment () const
Returns the vertical alignment used for characters with this format.
Public Functions inherited from QTextFormat
QBrush background () const
Returns the brush used to paint the document's background.
bool boolProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush brushProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Brush type, Qt::NoBrush is returned instead.
void clearBackground ()
Clears the brush used to paint the document's background.
void clearForeground ()
Clears the brush used to paint the document's foreground.
void clearProperty (int propertyId)
Clears the value of the property given by propertyId.
QColor colorProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Color type, an invalid color is returned instead.
qreal doubleProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush foreground () const
Returns the brush used to render foreground details, such as text, frame outlines, and table borders.
bool hasProperty (int propertyId) const
Returns true if the text format has a property with the given propertyId; otherwise returns false.
int intProperty (int propertyId) const
Returns the value of the property specified by propertyId.
bool isBlockFormat () const
Returns true if this text format is a BlockFormat; otherwise returns false.
bool isCharFormat () const
Returns true if this text format is a CharFormat; otherwise returns false.
bool isFrameFormat () const
Returns true if this text format is a FrameFormat; otherwise returns false.
bool isImageFormat () const
Returns true if this text format is an image format; otherwise returns false.
bool isListFormat () const
Returns true if this text format is a ListFormat; otherwise returns false.
bool isTableCellFormat () const
Returns true if this text format is a TableCellFormat; otherwise returns false.
bool isTableFormat () const
Returns true if this text format is a TableFormat; otherwise returns false.
bool isValid () const
Returns true if the format is valid (i.
Qt::LayoutDirection layoutDirection () const
Returns the document's layout direction.
QTextLength lengthProperty (int propertyId) const
Returns the value of the property given by propertyId.
QVector< QTextLength > lengthVectorProperty (int propertyId) const
Returns the value of the property given by propertyId.
void merge (const QTextFormat &other)
Merges the other format with this format; where there are conflicts the other format takes precedence.
int objectIndex () const
Returns the index of the format object, or -1 if the format object is invalid.
int objectType () const
Returns the text format's object type.
operator QVariant () const
Returns the text format as a QVariant.
bool operator!= (const QTextFormat &rhs) const
Returns true if this text format is different from the other text format.
QTextFormat & operator= (const QTextFormat &rhs)
Assigns the other text format to this text format, and returns a reference to this text format.
bool operator== (const QTextFormat &rhs) const
Returns true if this text format is the same as the other text format.
QPen penProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Pen type, Qt::NoPen is returned instead.
QMap< int, QVariant > properties () const
Returns a map with all properties of this text format.
QVariant property (int propertyId) const
Returns the property specified by the given propertyId.
int propertyCount () const
Returns the number of properties stored in the format.
QTextFormat ()
Creates a new text format with an InvalidFormat.
QTextFormat (int type)
Creates a new text format of the given type.
QTextFormat (const QTextFormat &rhs)
Creates a new text format with the same attributes as the other text format.
void setBackground (const QBrush &brush)
Sets the brush use to paint the document's background to the brush specified.
void setForeground (const QBrush &brush)
Sets the foreground brush to the specified brush.
void setLayoutDirection (Qt::LayoutDirection direction)
Sets the document's layout direction to the specified direction.
void setObjectIndex (int object)
Sets the format object's object index.
void setObjectType (int type)
Sets the text format's object type to type.
void setProperty (int propertyId, const QVariant &value)
Sets the property specified by the propertyId to the given value.
void setProperty (int propertyId, const QVector< QTextLength > &lengths)
Sets the value of the property given by propertyId to value.
QString stringProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::String type, an empty string is returned instead.
QTextBlockFormat toBlockFormat () const
Returns this format as a block format.
QTextCharFormat toCharFormat () const
Returns this format as a character format.
QTextFrameFormat toFrameFormat () const
Returns this format as a frame format.
QTextImageFormat toImageFormat () const
Returns this format as an image format.
QTextListFormat toListFormat () const
Returns this format as a list format.
QTextTableCellFormat toTableCellFormat () const
Returns this format as a table cell format.
QTextTableFormat toTableFormat () const
Returns this format as a table format.
int type () const
Returns the type of this format.
~QTextFormat ()
Destroys this text format.
Protected Functions
QTextCharFormat (const QTextFormat &fmt)
Creates a new character format with the same attributes as the given text format.
Friends
class QTextFormat
Detailed Description
The QTextCharFormat class provides formatting information for characters in a QTextDocument.
Note
This class or function is reentrant.
The character format of text in a document specifies the visual properties of the text, as well as information about its role in a hypertext document.
The font used can be set by supplying a font to the setFont() function, and each aspect of its appearance can be adjusted to give the desired effect. setFontFamily() and setFontPointSize() define the font's family (e.g. Times) and printed size; setFontWeight() and setFontItalic() provide control over the style of the font. setFontUnderline(), setFontOverline(), setFontStrikeOut(), and setFontFixedPitch() provide additional effects for text.
The color is set with setForeground(). If the text is intended to be used as an anchor (for hyperlinks), this can be enabled with setAnchor(). The setAnchorHref() and setAnchorNames() functions are used to specify the information about the hyperlink's destination and the anchor's name.
See also
QTextFormat QTextBlockFormat QTextTableFormat QTextListFormat
Definition at line 372 of file qtextformat.h.
Enumerations
UnderlineStyle
enum QTextCharFormat::UnderlineStyle
This enum describes the different ways drawing underlined text.
NoUnderline Text is draw without any underlining decoration.
SingleUnderline A line is drawn using Qt::SolidLine.
DashUnderline Dashes are drawn using Qt::DashLine.
DotLine Dots are drawn using Qt::DotLine;
DashDotLine Dashs and dots are drawn using Qt::DashDotLine.
DashDotDotLine Underlines draw drawn using Qt::DashDotDotLine.
WaveUnderline The text is underlined using a wave shaped line.
SpellCheckUnderline The underline is drawn depending on the QStyle::SH_SpellCeckUnderlineStyle style hint of the QApplication style. By default this is mapped to WaveUnderline, on Mac OS X it is mapped to DashDotLine.
See also
Qt::PenStyle
Enumerator
NoUnderline
SingleUnderline
DashUnderline
DotLine
DashDotLine
DashDotDotLine
WaveUnderline
SpellCheckUnderline
Definition at line 384 of file qtextformat.h.
                         { // keep in sync with Qt::PenStyle!
         NoUnderline,
         SingleUnderline,
         DashUnderline,
         DotLine,
         DashDotLine,
         DashDotDotLine,
         WaveUnderline,
         SpellCheckUnderline
     };
VerticalAlignment
enum QTextCharFormat::VerticalAlignment
This enum describes the ways that adjacent characters can be vertically aligned.
AlignNormal Adjacent characters are positioned in the standard way for text in the writing system in use.
AlignSuperScript Characters are placed above the base line for normal text.
AlignSubScript Characters are placed below the base line for normal text.
AlignMiddle The center of the object is vertically aligned with the base line. Currently, this is only implemented for inline objects.
AlignBottom The bottom edge of the object is vertically aligned with the base line.
AlignTop The top edge of the object is vertically aligned with the base line.
AlignBaseline The base lines of the characters are aligned.
Enumerator
AlignNormal
AlignSuperScript
AlignSubScript
AlignMiddle
AlignTop
AlignBottom
AlignBaseline
Definition at line 375 of file qtextformat.h.
{
         AlignNormal = 0,
         AlignSuperScript,
         AlignSubScript,
         AlignMiddle,
         AlignTop,
         AlignBottom,
         AlignBaseline
     };
Constructors and Destructors
QTextCharFormat() [1/2]
QTextCharFormat::QTextCharFormat ()
Constructs a new character format object.
Definition at line 1416 of file qtextformat.cpp.
Referenced by tableCellColumnSpan().
 : QTextFormat(CharFormat) {}
QTextCharFormat() [2/2]
QTextCharFormat::QTextCharFormat (const QTextFormat & other) explicit protected
Creates a new character format with the same attributes as the given text format.
Warning
This function is not part of the public interface.
Definition at line 1428 of file qtextformat.cpp.
  : QTextFormat(fmt)
 {
 }
Functions
anchorHref()
QString QTextCharFormat::anchorHref () const inline
Returns the text format's hypertext link, or an empty string if none has been set.
Definition at line 506 of file qtextformat.h.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), QAbstractTextDocumentLayout::anchorAt(), QPlainTextEdit::anchorAt(), QPdfEnginePrivate::drawTextItem(), QTextHtmlExporter::emitFragment(), QTextControl::findNextPrevAnchor(), QTextBrowser::keyPressEvent(), QPlainTextEdit::keyPressEvent(), and QTextEdit::keyPressEvent().
     { return stringProperty(AnchorHref); }
anchorName()
QString QTextCharFormat::anchorName () const
This function is deprecated.
Use anchorNames() instead.
Returns the anchor name associated with this text format, or an empty string if none has been set. If the anchor name is set, text with this format can be the destination of a hypertext link.
Definition at line 1964 of file qtextformat.cpp.
Referenced by QTextHtmlExporter::emitFragment(), QTextHtmlImporter::import(), and setAnchorName().
 {
     QVariant prop = property(AnchorName);
     if (prop.userType() == QVariant::StringList)
         return prop.toStringList().value(0);
     else if (prop.userType() != QVariant::String)
         return QString();
     return prop.toString();
 }
anchorNames()
QStringList QTextCharFormat::anchorNames () const
Returns the anchor names associated with this text format, or an empty string list if none has been set.
Since
4.3
If the anchor names are set, text with this format can be the destination of a hypertext link.
Definition at line 1985 of file qtextformat.cpp.
Referenced by QTextControl::anchorPosition(), and setAnchorNames().
 {
     QVariant prop = property(AnchorName);
     if (prop.userType() == QVariant::StringList)
         return prop.toStringList();
     else if (prop.userType() != QVariant::String)
         return QStringList();
     return QStringList(prop.toString());
 }
font()
QFont QTextCharFormat::font () const
Returns the font for this character format.
Definition at line 2124 of file qtextformat.cpp.
Referenced by QTextEditPrivate::_q_currentCharFormatChanged(), QAccessibleTextWidget::attributes(), QCalendarModel::data(), QTextDocumentLayoutPrivate::drawListItem(), QTextEngine::font(), QTextEngine::fontEngine(), isValid(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayout::resizeInlineObject(), and QScriptLine::setDefaultHeight().
 {
     return d ? d->font() : QFont();
 }
fontCapitalization()
Capitalization QTextCharFormat::fontCapitalization () const inline
Returns the current capitalization type of the font.
Since
4.4
Definition at line 421 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitCharFormatStyle(), and QTextOdfWriter::writeCharacterFormat().
     { return static_cast<QFont::Capitalization>(intProperty(FontCapitalization)); }
fontFamily()
QString QTextCharFormat::fontFamily () const inline
Returns the text format's font family.
See also
font()
Definition at line 403 of file qtextformat.h.
Referenced by QAccessibleTextWidget::attributes(), QTextHtmlExporter::emitCharFormatStyle(), QTextHtmlExporter::toHtml(), and QTextOdfWriter::writeCharacterFormat().
     { return stringProperty(FontFamily); }
fontFixedPitch()
bool QTextCharFormat::fontFixedPitch () const inline
Returns true if the text format's font is fixed pitch; otherwise returns false.
See also
font()
Definition at line 453 of file qtextformat.h.
     { return boolProperty(FontFixedPitch); }
fontHintingPreference()
QFont::HintingPreference QTextCharFormat::fontHintingPreference () const inline
Returns the hinting preference set for this text format.
Since
4.8
See also
font(), QFont::hintingPreference()
Definition at line 470 of file qtextformat.h.
     {
         return static_cast<QFont::HintingPreference>(intProperty(FontHintingPreference));
     }
fontItalic()
bool QTextCharFormat::fontItalic () const inline
Returns true if the text format's font is italic; otherwise returns false.
See also
font()
Definition at line 417 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitCharFormatStyle(), QTextHtmlExporter::toHtml(), and QTextOdfWriter::writeCharacterFormat().
     { return boolProperty(FontItalic); }
fontKerning()
bool QTextCharFormat::fontKerning () const inline
Returns true if the font kerning is enabled.
Since
4.5
See also
setFontKerning()
font()
Definition at line 477 of file qtextformat.h.
     { return boolProperty(FontKerning); }
fontLetterSpacing()
qreal QTextCharFormat::fontLetterSpacing () const inline
Returns the current letter spacing percentage.
Since
4.4
Definition at line 425 of file qtextformat.h.
Referenced by QTextOdfWriter::writeCharacterFormat().
     { return doubleProperty(FontLetterSpacing); }
fontOverline()
bool QTextCharFormat::fontOverline () const inline
Returns true if the text format's font is overlined; otherwise returns false.
See also
font()
Definition at line 438 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitCharFormatStyle(), and QTextItemInt::initWithScriptItem().
     { return boolProperty(FontOverline); }
fontPointSize()
qreal QTextCharFormat::fontPointSize () const inline
Returns the font size used to display text in this format.
See also
font()
Definition at line 408 of file qtextformat.h.
Referenced by QAccessibleTextWidget::attributes(), QTextHtmlExporter::emitCharFormatStyle(), QTextHtmlExporter::toHtml(), and QTextOdfWriter::writeCharacterFormat().
     { return doubleProperty(FontPointSize); }
fontStrikeOut()
bool QTextCharFormat::fontStrikeOut () const inline
Returns true if the text format's font is struck out (has a horizontal line drawn through it); otherwise returns false.
See also
font()
Definition at line 443 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitCharFormatStyle(), QTextItemInt::initWithScriptItem(), and QTextOdfWriter::writeCharacterFormat().
     { return boolProperty(FontStrikeOut); }
fontStyleHint()
QTextCharFormat::StyleHint QTextCharFormat::fontStyleHint () const inline
Returns the font style hint.
Since
4.5
See also
setFontStyleHint(), font()
Definition at line 460 of file qtextformat.h.
     { return static_cast<QFont::StyleHint>(intProperty(FontStyleHint)); }
fontStyleStrategy()
QTextCharFormat::StyleStrategy QTextCharFormat::fontStyleStrategy () const inline
Returns the current font style strategy.
Since
4.5
See also
setFontStyleStrategy()
font()
Definition at line 462 of file qtextformat.h.
     { return static_cast<QFont::StyleStrategy>(intProperty(FontStyleStrategy)); }
fontUnderline()
bool QTextCharFormat::fontUnderline () const
Returns true if the text format's font is underlined; otherwise returns false.
See also
font()
Definition at line 1566 of file qtextformat.cpp.
Referenced by QTextHtmlExporter::emitCharFormatStyle(), setFontUnderline(), and QTextOdfWriter::writeCharacterFormat().
 {
     if (hasProperty(TextUnderlineStyle))
         return underlineStyle() == SingleUnderline;
     return boolProperty(FontUnderline);
 }
fontWeight()
int QTextCharFormat::fontWeight () const inline
Returns the text format's font weight.
See also
font(), QFont::Weight
Definition at line 413 of file qtextformat.h.
Referenced by QAccessibleTextWidget::attributes(), QTextHtmlExporter::emitCharFormatStyle(), QTextHtmlExporter::toHtml(), and QTextOdfWriter::writeCharacterFormat().
     { int weight = intProperty(FontWeight); if (weight == 0) weight = QFont::Normal; return weight; }
fontWordSpacing()
qreal QTextCharFormat::fontWordSpacing () const inline
Returns the current word spacing value.
Since
4.4
Definition at line 429 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitCharFormatStyle(), and QTextOdfWriter::writeCharacterFormat().
     { return doubleProperty(FontWordSpacing); }
isAnchor()
bool QTextCharFormat::isAnchor () const inline
Returns true if the text is formatted as an anchor; otherwise returns false.
See also
setAnchor() setAnchorHref() setAnchorNames()
Definition at line 501 of file qtextformat.h.
Referenced by QTextControlPrivate::anchorForCursor(), QTextControl::anchorPosition(), QPdfEnginePrivate::drawTextItem(), QTextHtmlExporter::emitFragment(), QTextControl::findNextPrevAnchor(), and QTextHtmlImporter::import().
     { return boolProperty(IsAnchor); }
isValid()
bool QTextCharFormat::isValid () const inline
Returns true if this character format is valid; otherwise returns false.
Definition at line 397 of file qtextformat.h.
Referenced by QTextCursor::charFormat(), QTextDocumentLayout::drawInlineObject(), QAbstractTextDocumentLayout::drawInlineObject(), QTextControlPrivate::inputMethodEvent(), QTextCursor::insertText(), QTextDocumentLayout::positionInlineObject(), QLineControl::processInputMethodEvent(), QTextDocumentLayout::resizeInlineObject(), QAbstractTextDocumentLayout::resizeInlineObject(), and QTextDocumentPrivate::setCharFormat().
 { return isCharFormat(); }
setAnchor()
void QTextCharFormat::setAnchor (bool anchor) inline
If anchor is true, text with this format represents an anchor, and is formatted in the appropriate way; otherwise the text is formatted normally.
(Anchors are hyperlinks which are often shown underlined and in a different color from plain text.)
The way the text is rendered is independent of whether or not the format has a valid anchor defined. Use setAnchorHref(), and optionally setAnchorNames() to create a hypertext link.
See also
isAnchor()
Definition at line 499 of file qtextformat.h.
Referenced by QTextHtmlImporter::appendBlock(), QTextHtmlImporter::appendNodeText(), QTextHtmlParser::applyAttributes(), and QTextHtmlParserNode::initializeProperties().
     { setProperty(IsAnchor, anchor); }
setAnchorHref()
void QTextCharFormat::setAnchorHref (const QString & value) inline
Sets the hypertext link for the text format to the given value.
This is typically a URL like "http://example.com/index.html".
The anchor will be displayed with the value as its display text; if you want to display different text call setAnchorNames().
To format the text as a hypertext link use setAnchor().
Definition at line 504 of file qtextformat.h.
Referenced by QTextHtmlParser::applyAttributes().
     { setProperty(AnchorHref, value); }
setAnchorName()
void QTextCharFormat::setAnchorName (const QString & name) inline
This function is deprecated.
Use setAnchorNames() instead.
Sets the text format's anchor name. For the anchor to work as a hyperlink, the destination must be set with setAnchorHref() and the anchor must be enabled with setAnchor().
Definition at line 509 of file qtextformat.h.
Referenced by QTextHtmlParser::applyAttributes().
     { setAnchorNames(QStringList(name)); }
setAnchorNames()
void QTextCharFormat::setAnchorNames (const QStringList & names) inline
Sets the text format's anchor names.
Since
4.3
For the anchor to work as a hyperlink, the destination must be set with setAnchorHref() and the anchor must be enabled with setAnchor().
Definition at line 513 of file qtextformat.h.
Referenced by QTextHtmlImporter::appendBlock(), QTextHtmlImporter::appendNodeText(), and setAnchorName().
     { setProperty(AnchorName, names); }
setFont()
void QTextCharFormat::setFont (const QFont & font)
Sets the text format's font.
Definition at line 2093 of file qtextformat.cpp.
Referenced by QSvgText::draw(), QCalendarModel::formatForCell(), isValid(), QTextHtmlExporter::QTextHtmlExporter(), QTextEdit::setCurrentFont(), and QSyntaxHighlighter::setFormat().
 {
     setFontFamily(font.family());
     const qreal pointSize = font.pointSizeF();
     if (pointSize > 0) {
         setFontPointSize(pointSize);
     } else {
         const int pixelSize = font.pixelSize();
         if (pixelSize > 0)
             setProperty(QTextFormat::FontPixelSize, pixelSize);
     }
     setFontWeight(font.weight());
     setFontItalic(font.italic());
     setUnderlineStyle(font.underline() ? SingleUnderline : NoUnderline);
     setFontOverline(font.overline());
     setFontStrikeOut(font.strikeOut());
     setFontFixedPitch(font.fixedPitch());
     setFontCapitalization(font.capitalization());
     setFontWordSpacing(font.wordSpacing());
     if (font.letterSpacingType() == QFont::PercentageSpacing)
         setFontLetterSpacing(font.letterSpacing());
     setFontStyleHint(font.styleHint());
     setFontStyleStrategy(font.styleStrategy());
     setFontKerning(font.kerning());
 }
setFontCapitalization()
void QTextCharFormat::setFontCapitalization (QFont::Capitalization capitalization) inline
Sets the capitalization of the text that apppears in this font to capitalization.
Since
4.4
A font's capitalization makes the text appear in the selected capitalization mode.
See also
fontCapitalization()
Definition at line 419 of file qtextformat.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), and setFont().
     { setProperty(FontCapitalization, capitalization); }
setFontFamily()
void QTextCharFormat::setFontFamily (const QString & family) inline
Sets the text format's font family.
See also
setFont()
Definition at line 401 of file qtextformat.h.
Referenced by QTextHtmlParser::applyAttributes(), QTextHtmlParserNode::applyCssDeclarations(), QTextHtmlParserNode::initializeProperties(), setFont(), and QTextEdit::setFontFamily().
     { setProperty(FontFamily, family); }
setFontFixedPitch()
void QTextCharFormat::setFontFixedPitch (bool fixedPitch) inline
If fixedPitch is true, sets the text format's font to be fixed pitch; otherwise a non-fixed pitch font is used.
See also
setFont()
Definition at line 451 of file qtextformat.h.
Referenced by QTextHtmlParserNode::initializeProperties(), and setFont().
     { setProperty(FontFixedPitch, fixedPitch); }
setFontHintingPreference()
void QTextCharFormat::setFontHintingPreference (QFont::HintingPreference hintingPreference) inline
Sets the hinting preference of the text format's font to be hintingPreference.
Since
4.8
See also
setFont(), QFont::setHintingPreference()
Definition at line 465 of file qtextformat.h.
     {
         setProperty(FontHintingPreference, hintingPreference);
     }
setFontItalic()
void QTextCharFormat::setFontItalic (bool italic) inline
If italic is true, sets the text format's font to be italic; otherwise the font will be non-italic.
See also
setFont()
Definition at line 415 of file qtextformat.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QTextHtmlParserNode::initializeProperties(), QDeclarativeStyledTextPrivate::parseTag(), QScriptSyntaxHighlighter::QScriptSyntaxHighlighter(), setFont(), and QTextEdit::setFontItalic().
     { setProperty(FontItalic, italic); }
setFontKerning()
void QTextCharFormat::setFontKerning (bool enable) inline
Enables kerning for this font if enable is true; otherwise disables it.
Since
4.5
When kerning is enabled, glyph metrics do not add up anymore, even for Latin text. In other words, the assumption that width('a') + width('b') is equal to width("ab") is not neccesairly true.
See also
setFont()
Definition at line 475 of file qtextformat.h.
Referenced by setFont().
     { setProperty(FontKerning, enable); }
setFontLetterSpacing()
void QTextCharFormat::setFontLetterSpacing (qreal spacing) inline
Sets the letter spacing of this format to the given spacing, in percent.
Since
4.4
A value of 100 indicates default spacing; a value of 200 doubles the amount of space a letter takes.
See also
fontLetterSpacing()
Definition at line 423 of file qtextformat.h.
Referenced by setFont().
     { setProperty(FontLetterSpacing, spacing); }
setFontOverline()
void QTextCharFormat::setFontOverline (bool overline) inline
If overline is true, sets the text format's font to be overlined; otherwise the font is displayed non-overlined.
See also
setFont()
Definition at line 436 of file qtextformat.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), and setFont().
     { setProperty(FontOverline, overline); }
setFontPointSize()
void QTextCharFormat::setFontPointSize (qreal size) inline
Sets the text format's font size.
See also
setFont()
Definition at line 406 of file qtextformat.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QDeclarativeStyledTextPrivate::parseFontAttributes(), setFont(), and QTextEdit::setFontPointSize().
     { setProperty(FontPointSize, size); }
setFontStrikeOut()
void QTextCharFormat::setFontStrikeOut (bool strikeOut) inline
If strikeOut is true, sets the text format's font with strike-out enabled (with a horizontal line through it); otherwise it is displayed without strikeout.
See also
setFont()
Definition at line 441 of file qtextformat.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QTextHtmlParserNode::initializeProperties(), and setFont().
     { setProperty(FontStrikeOut, strikeOut); }
setFontStyleHint()
void QTextCharFormat::setFontStyleHint (QFont::StyleHint hint, QFont::StyleStrategy strategy = QFont::PreferDefault) inline
Sets the font style hint and strategy.
Since
4.5
Qt does not support style hints on X11 since this information is not provided by the window system.
See also
setFont()
QFont::setStyleHint()
Definition at line 456 of file qtextformat.h.
Referenced by setFont().
     { setProperty(FontStyleHint, hint); setProperty(FontStyleStrategy, strategy); }
setFontStyleStrategy()
void QTextCharFormat::setFontStyleStrategy (QFont::StyleStrategy strategy) inline
Sets the font style strategy.
Since
4.5
See also
setFont()
QFont::setStyleStrategy()
Definition at line 458 of file qtextformat.h.
Referenced by setFont().
     { setProperty(FontStyleStrategy, strategy); }
setFontUnderline()
void QTextCharFormat::setFontUnderline (bool underline) inline
If underline is true, sets the text format's font to be underlined; otherwise it is displayed non-underlined.
See also
setFont()
Definition at line 432 of file qtextformat.h.
Referenced by QMacInputContext::globalEventProcessor(), QTextControlPrivate::inputMethodEvent(), QLabel::paintEvent(), QLineControl::processInputMethodEvent(), qt_mac_compose_format(), QBBInputContext::setComposingText(), and QTextEdit::setFontUnderline().
     { setProperty(TextUnderlineStyle, underline ? SingleUnderline : NoUnderline); }
setFontWeight()
void QTextCharFormat::setFontWeight (int weight) inline
Sets the text format's font weight to weight.
See also
setFont(), QFont::Weight
Definition at line 411 of file qtextformat.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QTextHtmlParserNode::initializeProperties(), QDeclarativeStyledTextPrivate::parseTag(), setFont(), and QTextEdit::setFontWeight().
     { if (weight == QFont::Normal) weight = 0; setProperty(FontWeight, weight); }
setFontWordSpacing()
void QTextCharFormat::setFontWordSpacing (qreal spacing) inline
Sets the word spacing of this format to the given spacing, in pixels.
Since
4.4
See also
fontWordSpacing()
Definition at line 427 of file qtextformat.h.
Referenced by setFont().
     { setProperty(FontWordSpacing, spacing); }
setTableCellColumnSpan()
void QTextCharFormat::setTableCellColumnSpan (int tableCellColumnSpan) inline
If this character format is applied to characters in a table cell, the cell will span tableCellColumnSpan columns.
Warning
This function is not part of the public interface.
Definition at line 537 of file qtextformat.h.
Referenced by QTextCopyHelper::copy(), QTextTable::insertColumns(), QTextTable::mergeCells(), QTextTableCell::setFormat(), QTextTable::splitCell(), and tableCellRowSpan().
 {
     if (_tableCellColumnSpan <= 1)
         clearProperty(TableCellColumnSpan); // the getter will return 1 here.
     else
         setProperty(TableCellColumnSpan, _tableCellColumnSpan);
 }
setTableCellRowSpan()
void QTextCharFormat::setTableCellRowSpan (int tableCellRowSpan) inline
If this character format is applied to characters in a table cell, the cell will span tableCellRowSpan rows.
Warning
This function is not part of the public interface.
Definition at line 529 of file qtextformat.h.
Referenced by QTextCopyHelper::copy(), QTextTable::insertColumns(), QTextTable::insertRows(), QTextTable::mergeCells(), setAnchorNames(), QTextTableCell::setFormat(), and QTextTable::splitCell().
 {
     if (_tableCellRowSpan <= 1)
         clearProperty(TableCellRowSpan); // the getter will return 1 here.
     else
         setProperty(TableCellRowSpan, _tableCellRowSpan);
 }
setTextOutline()
void QTextCharFormat::setTextOutline (const QPen & pen) inline
Sets the pen used to draw the outlines of characters to the given pen.
Definition at line 489 of file qtextformat.h.
Referenced by QSvgText::draw(), and QGraphicsSimpleTextItem::paint().
     { setProperty(TextOutline, pen); }
setToolTip()
void QTextCharFormat::setToolTip (const QString & text) inline
Sets the tool tip for a fragment of text to the given text.
Since
4.3
Definition at line 494 of file qtextformat.h.
Referenced by QTextHtmlParser::applyAttributes().
     { setProperty(TextToolTip, tip); }
setUnderlineColor()
void QTextCharFormat::setUnderlineColor (const QColor & color) inline
Sets the underline color used for the characters with this format to the color specified.
See also
underlineColor()
Definition at line 446 of file qtextformat.h.
Referenced by QMacInputContext::globalEventProcessor().
     { setProperty(TextUnderlineColor, color); }
setUnderlineStyle()
void QTextCharFormat::setUnderlineStyle (UnderlineStyle style)
Sets the style of underlining the text to style.
Since
4.2
Definition at line 1592 of file qtextformat.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), fontKerning(), QTextHtmlParserNode::initializeProperties(), QTextControlPrivate::inputMethodEvent(), QLineControl::processInputMethodEvent(), setFont(), and QInputContext::standardFormat().
 {
     setProperty(TextUnderlineStyle, style);
     // for compatibility
     setProperty(FontUnderline, style == SingleUnderline);
 }
setVerticalAlignment()
void QTextCharFormat::setVerticalAlignment (VerticalAlignment alignment) inline
Sets the vertical alignment used for the characters with this format to the alignment specified.
See also
verticalAlignment()
Definition at line 484 of file qtextformat.h.
Referenced by QTextHtmlParser::applyAttributes(), QTextHtmlParserNode::applyCssDeclarations(), QTextHtmlExporter::emitTable(), and QTextHtmlParserNode::initializeProperties().
     { setProperty(TextVerticalAlignment, alignment); }
tableCellColumnSpan()
int QTextCharFormat::tableCellColumnSpan () const inline
If this character format is applied to characters in a table cell, this function returns the number of columns spanned by the text (this may be 1); otherwise it returns 1.
Warning
This function is not part of the public interface.
Definition at line 521 of file qtextformat.h.
Referenced by QTextTableCell::columnSpan(), QTextTable::mergeCells(), QTextTable::removeColumns(), QTextTableCell::setFormat(), QTextTable::splitCell(), tableCellRowSpan(), and QTextTablePrivate::update().
     { int s = intProperty(TableCellColumnSpan); if (s == 0) s = 1; return s; }
tableCellRowSpan()
int QTextCharFormat::tableCellRowSpan () const inline
If this character format is applied to characters in a table cell, this function returns the number of rows spanned by the text (this may be 1); otherwise it returns 1.
Warning
This function is not part of the public interface.
Definition at line 518 of file qtextformat.h.
Referenced by QTextTable::mergeCells(), QTextTable::removeRows(), QTextTableCell::rowSpan(), setAnchorNames(), QTextTableCell::setFormat(), QTextTable::splitCell(), and QTextTablePrivate::update().
     { int s = intProperty(TableCellRowSpan); if (s == 0) s = 1; return s; }
textOutline()
QPen QTextCharFormat::textOutline () const inline
Returns the pen used to draw the outlines of characters in this format.
Definition at line 491 of file qtextformat.h.
Referenced by QTextLine::draw().
     { return penProperty(TextOutline); }
toolTip()
QString QTextCharFormat::toolTip () const inline
Returns the tool tip that is displayed for a fragment of text.
Since
4.3
Definition at line 496 of file qtextformat.h.
Referenced by QCalendarModel::data().
     { return stringProperty(TextToolTip); }
underlineColor()
QColor QTextCharFormat::underlineColor () const inline
Returns the color used to underline the characters with this format.
See also
setUnderlineColor()
Definition at line 448 of file qtextformat.h.
Referenced by drawTextItemDecoration(), and QTextOdfWriter::writeCharacterFormat().
     { return colorProperty(TextUnderlineColor); }
underlineStyle()
UnderlineStyle QTextCharFormat::underlineStyle () const inline
Returns the style of underlining the text.
Since
4.2
Definition at line 481 of file qtextformat.h.
Referenced by fontUnderline(), QTextItemInt::initWithScriptItem(), and QTextOdfWriter::writeCharacterFormat().
     { return static_cast<UnderlineStyle>(intProperty(TextUnderlineStyle)); }
verticalAlignment()
VerticalAlignment QTextCharFormat::verticalAlignment () const inline
Returns the vertical alignment used for characters with this format.
See also
setVerticalAlignment()
Definition at line 486 of file qtextformat.h.
Referenced by QAccessibleTextWidget::attributes(), QTextLine::draw(), QTextHtmlExporter::emitCharFormatStyle(), QTextHtmlExporter::emitFragment(), QTextHtmlExporter::emitTable(), QTextEngine::font(), QTextEngine::fontEngine(), QTextDocumentLayoutPrivate::layoutTable(), QTextDocumentLayout::resizeInlineObject(), QTextOdfWriter::writeCharacterFormat(), and QTextOdfWriter::writeTableCellFormat().
     { return static_cast<VerticalAlignment>(intProperty(TextVerticalAlignment)); }
Friends and Related Functions
QTextFormat
friend class QTextFormat friend
Definition at line 526 of file qtextformat.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextformat.h
/src/gui/text/qtextformat.cpp