Qt 4.8: QSystemTrayIconPrivate Class Reference
QSystemTrayIconPrivate Class Reference
#include <qsystemtrayicon_p.h>
Public Functions
QRect geometry_sys () const
void install_sys ()
QSystemTrayIconPrivate ()
void remove_sys ()
void showMessage_sys (const QString &msg, const QString &title, QSystemTrayIcon::MessageIcon icon, int secs)
void updateIcon_sys ()
void updateMenu_sys ()
void updateToolTip_sys ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static bool isSystemTrayAvailable_sys ()
static bool supportsMessages_sys ()
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QIcon icon
QPointer< QMenu > menu
QSystemTrayIconSys * sys
QString toolTip
bool visible
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 72 of file qsystemtrayicon_p.h.
Constructors and Destructors
QSystemTrayIconPrivate()
QSystemTrayIconPrivate::QSystemTrayIconPrivate () inline
Definition at line 77 of file qsystemtrayicon_p.h.
 : sys(0), visible(false) { }
Functions
geometry_sys()
QRect QSystemTrayIconPrivate::geometry_sys () const
Definition at line 171 of file qsystemtrayicon_mac.mm.
Referenced by QSystemTrayIconSys::findIconGeometry(), QSystemTrayIconSys::findTrayGeometry(), QSystemTrayIconPrivate(), and QSystemTrayIconSys::x11Event().
 {
     if(sys) {
         const QRectF geom = [sys->item geometry];
         if(!geom.isNull())
             return geom.toRect();
     }
     return QRect();
 }
install_sys()
void QSystemTrayIconPrivate::install_sys ()
Definition at line 160 of file qsystemtrayicon_mac.mm.
Referenced by QSystemTrayIconSys::findTrayGeometry(), QSystemTrayIconPrivate(), QSystemTrayIconSys::winEvent(), and QSystemTrayIconSys::x11Event().
 {
     Q_Q(QSystemTrayIcon);
     if (!sys) {
         sys = new QSystemTrayIconSys(q, this);
         updateIcon_sys();
         updateMenu_sys();
         updateToolTip_sys();
     }
 }
isSystemTrayAvailable_sys()
bool QSystemTrayIconPrivate::isSystemTrayAvailable_sys () static
Definition at line 224 of file qsystemtrayicon_mac.mm.
Referenced by QSystemTrayIconSys::findIconGeometry(), QSystemTrayIconSys::findTrayGeometry(), QSystemTrayIcon::isSystemTrayAvailable(), QSystemTrayIconPrivate(), and QSystemTrayIconSys::x11Event().
 {
     return true;
 }
remove_sys()
void QSystemTrayIconPrivate::remove_sys ()
Definition at line 181 of file qsystemtrayicon_mac.mm.
Referenced by QSystemTrayIconSys::findIconGeometry(), QSystemTrayIconSys::findTrayGeometry(), QSystemTrayIconPrivate(), and QSystemTrayIconSys::x11Event().
 {
     delete sys;
     sys = 0;
 }
showMessage_sys()
void QSystemTrayIconPrivate::showMessage_sys (const QString & msg, const QString & title, QSystemTrayIcon::MessageIcon icon, int secs)
Definition at line 234 of file qsystemtrayicon_mac.mm.
Referenced by QSystemTrayIconSys::findIconGeometry(), QSystemTrayIconSys::findTrayGeometry(), QSystemTrayIconPrivate(), and QSystemTrayIconSys::x11Event().
 {
     if(sys) {
 #ifdef QT_MAC_SYSTEMTRAY_USE_GROWL
         // Make sure that we have Growl installed on the machine we are running on.
         QCFType<CFURLRef> cfurl;
         OSStatus status = LSGetApplicationForInfo(kLSUnknownType, kLSUnknownCreator,
                                                   CFSTR("growlTicket"), kLSRolesAll, 0, &cfurl);
         if (status == kLSApplicationNotFoundErr)
             return;
         QCFType<CFBundleRef> bundle = CFBundleCreate(0, cfurl);
         if (CFStringCompare(CFBundleGetIdentifier(bundle), CFSTR("com.Growl.GrowlHelperApp"),
                     kCFCompareCaseInsensitive |  kCFCompareBackwards) != kCFCompareEqualTo)
             return;
         QPixmap notificationIconPixmap;
         if(icon == QSystemTrayIcon::Information)
             notificationIconPixmap = QApplication::style()->standardPixmap(QStyle::SP_MessageBoxInformation);
         else if(icon == QSystemTrayIcon::Warning)
             notificationIconPixmap = QApplication::style()->standardPixmap(QStyle::SP_MessageBoxWarning);
         else if(icon == QSystemTrayIcon::Critical)
             notificationIconPixmap = QApplication::style()->standardPixmap(QStyle::SP_MessageBoxCritical);
         QTemporaryFile notificationIconFile;
         QString notificationType(QLatin1String("Notification")), notificationIcon, notificationApp(QApplication::applicationName());
         if(notificationApp.isEmpty())
             notificationApp = QLatin1String("Application");
         if(!notificationIconPixmap.isNull() && notificationIconFile.open()) {
             QImageWriter writer(&notificationIconFile, "PNG");
             if(writer.write(notificationIconPixmap.toImage()))
                 notificationIcon = QLatin1String("image from location \"file://") + notificationIconFile.fileName() + QLatin1String("\"");
         }
         const QString script(QLatin1String(
             "tell application \"GrowlHelperApp\"\n"
             "-- Make a list of all the notification types (all)\n"
             "set the allNotificationsList to {\"") + notificationType + QLatin1String("\"}\n"
             "-- Make a list of the notifications (enabled)\n"
             "set the enabledNotificationsList to {\"") + notificationType + QLatin1String("\"}\n"
             "-- Register our script with growl.\n"
             "register as application \"") + notificationApp + QLatin1String("\" all notifications allNotificationsList default notifications enabledNotificationsList\n"
             "-- Send a Notification...\n") +
             QLatin1String("notify with name \"") + notificationType +
             QLatin1String("\" title \"") + title +
             QLatin1String("\" description \"") + message +
             QLatin1String("\" application name \"") + notificationApp +
             QLatin1String("\" ")  + notificationIcon +
             QLatin1String("\nend tell"));
         qt_mac_execute_apple_script(script, 0);
 #elif 0
         Q_Q(QSystemTrayIcon);
         NSView *v = [[sys->item item] view];
         NSWindow *w = [v window];
         w = [[sys->item item] window];
         qDebug() << w << v;
         QPoint p(qRound([w frame].origin.x), qRound([w frame].origin.y));
         qDebug() << p;
         QBalloonTip::showBalloon(icon, message, title, q, QPoint(0, 0), msecs);
 #else
         Q_UNUSED(icon);
         Q_UNUSED(title);
         Q_UNUSED(message);
 #endif
     }
 }
supportsMessages_sys()
bool QSystemTrayIconPrivate::supportsMessages_sys () static
Definition at line 229 of file qsystemtrayicon_mac.mm.
Referenced by QSystemTrayIconSys::findIconGeometry(), QSystemTrayIconSys::findTrayGeometry(), QSystemTrayIconPrivate(), QSystemTrayIcon::supportsMessages(), and QSystemTrayIconSys::x11Event().
 {
     return true;
 }
updateIcon_sys()
void QSystemTrayIconPrivate::updateIcon_sys ()
Definition at line 187 of file qsystemtrayicon_mac.mm.
Referenced by QSystemTrayIconSys::findIconGeometry(), QSystemTrayIconSys::findTrayGeometry(), QSystemTrayIconPrivate(), and QSystemTrayIconSys::x11Event().
 {
     if(sys && !icon.isNull()) {
         QMacCocoaAutoReleasePool pool;
 #ifndef QT_MAC_USE_COCOA
         const short scale = GetMBarHeight()-4;
 #else
         CGFloat hgt = [[[NSApplication sharedApplication] mainMenu] menuBarHeight];
         const short scale = hgt - 4;
 #endif
         NSImage *nsimage = static_cast<NSImage *>(qt_mac_create_nsimage(icon.pixmap(QSize(scale, scale))));
         [(NSImageView*)[[sys->item item] view] setImage: nsimage];
         [nsimage release];
     }
 }
updateMenu_sys()
void QSystemTrayIconPrivate::updateMenu_sys ()
Definition at line 203 of file qsystemtrayicon_mac.mm.
Referenced by QSystemTrayIconSys::findIconGeometry(), QSystemTrayIconSys::findTrayGeometry(), QSystemTrayIconPrivate(), and QSystemTrayIconSys::x11Event().
 {
     if(sys) {
         QMacCocoaAutoReleasePool pool;
         if(menu && !menu->isEmpty()) {
             [[sys->item item] setHighlightMode:YES];
         } else {
             [[sys->item item] setHighlightMode:NO];
         }
     }
 }
updateToolTip_sys()
void QSystemTrayIconPrivate::updateToolTip_sys ()
Definition at line 215 of file qsystemtrayicon_mac.mm.
Referenced by QSystemTrayIconSys::findIconGeometry(), QSystemTrayIconSys::findTrayGeometry(), QSystemTrayIconPrivate(), and QSystemTrayIconSys::x11Event().
 {
     if(sys) {
         QMacCocoaAutoReleasePool pool;
         QCFString string(toolTip);
         [[[sys->item item] view] setToolTip:(NSString*)static_cast<CFStringRef>(string)];
     }
 }
Properties
icon
QIcon QSystemTrayIconPrivate::icon
Definition at line 91 of file qsystemtrayicon_p.h.
Referenced by QSystemTrayIconPrivate().
menu
QPointer<QMenu> QSystemTrayIconPrivate::menu
Definition at line 90 of file qsystemtrayicon_p.h.
sys
QSystemTrayIconSys* QSystemTrayIconPrivate::sys
Definition at line 93 of file qsystemtrayicon_p.h.
Referenced by geometry_sys(), showMessage_sys(), updateIcon_sys(), updateMenu_sys(), and updateToolTip_sys().
toolTip
QString QSystemTrayIconPrivate::toolTip
Definition at line 92 of file qsystemtrayicon_p.h.
visible
bool QSystemTrayIconPrivate::visible
Definition at line 94 of file qsystemtrayicon_p.h.
The documentation for this class was generated from the following files:
/src/gui/util/qsystemtrayicon_p.h
/src/gui/util/qsystemtrayicon_mac.mm
/src/gui/util/qsystemtrayicon_qws.cpp
/src/gui/util/qsystemtrayicon_win.cpp
/src/gui/util/qsystemtrayicon_wince.cpp
/src/gui/util/qsystemtrayicon_x11.cpp