Qt 4.8: QXcbConnection Class Reference
QXcbConnection Class Reference
#include <qxcbconnection.h>
Classes
struct CallInfo
Public Functions
xcb_atom_t atom (QXcbAtom::Atom atom)
QXcbConnection * connection () const
const char * displayName () const
void handleXcbError (xcb_generic_error_t *error)
QXcbKeyboard * keyboard () const
int primaryScreen () const
QXcbConnection (const char *displayName=0)
QList< QXcbScreen * > screens () const
void sync ()
xcb_connection_t * xcb_connection () const
~QXcbConnection ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void processXcbEvents ()
Private Functions
void initializeAllAtoms ()
void log (const char *file, int line, int sequence)
void sendConnectionEvent (QXcbAtom::Atom atom, uint id=0)
Properties
xcb_atom_t m_allAtoms [QXcbAtom::NAtoms]
QVector< CallInfo > m_callLog
xcb_connection_t * m_connection
QByteArray m_displayName
QXcbKeyboard * m_keyboard
int m_primaryScreen
QList< QXcbScreen * > m_screens
const xcb_setup_t * m_setup
Friends
template<typename cookie_t >
cookie_t q_xcb_call_template (const cookie_t &cookie, QXcbConnection *connection, const char *file, int line)
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 220 of file qxcbconnection.h.
Constructors and Destructors
QXcbConnection()
QXcbConnection::QXcbConnection (const char * displayName = 0)
Definition at line 78 of file qxcbconnection.cpp.
     : m_displayName(displayName ? QByteArray(displayName) : qgetenv("DISPLAY"))
 #ifdef XCB_USE_DRI2
     , m_dri2_major(0)
     , m_dri2_minor(0)
     , m_dri2_support_probed(false)
     , m_has_support_for_dri2(false)
 #endif
 {
     int primaryScreen = 0;
 #ifdef XCB_USE_XLIB
     Display *dpy = XOpenDisplay(m_displayName.constData());
     primaryScreen = DefaultScreen(dpy);
     m_connection = XGetXCBConnection(dpy);
     XSetEventQueueOwner(dpy, XCBOwnsEventQueue);
     m_xlib_display = dpy;
 #ifdef XCB_USE_EGL
     EGLDisplay eglDisplay = eglGetDisplay(dpy);
     m_egl_display = eglDisplay;
     EGLint major, minor;
     eglBindAPI(EGL_OPENGL_ES_API);
     m_has_egl = eglInitialize(eglDisplay,&major,&minor);
 #endif //XCB_USE_EGL
 #else
     m_connection = xcb_connect(m_displayName.constData(), &primaryScreen);
 #endif //XCB_USE_XLIB
     m_setup = xcb_get_setup(xcb_connection());
     initializeAllAtoms();
     xcb_screen_iterator_t it = xcb_setup_roots_iterator(m_setup);
     int screenNumber = 0;
     while (it.rem) {
         m_screens << new QXcbScreen(this, it.data, screenNumber++);
         xcb_screen_next(&it);
     }
     m_keyboard = new QXcbKeyboard(this);
 #ifdef XCB_USE_DRI2
     initializeDri2();
 #endif
     QSocketNotifier *notifier = new QSocketNotifier(xcb_get_file_descriptor(xcb_connection()), QSocketNotifier::Read, this);
     connect(notifier, SIGNAL(activated(int)), this, SLOT(processXcbEvents()));
     QAbstractEventDispatcher *dispatcher = QAbstractEventDispatcher::instance(qApp->thread());
     connect(dispatcher, SIGNAL(aboutToBlock()), this, SLOT(processXcbEvents()));
     sync();
 }
~QXcbConnection()
QXcbConnection::~QXcbConnection ()
Definition at line 133 of file qxcbconnection.cpp.
 {
     qDeleteAll(m_screens);
 #ifdef XCB_USE_XLIB
     XCloseDisplay((Display *)m_xlib_display);
 #else
     xcb_disconnect(xcb_connection());
 #endif
     delete m_keyboard;
 }
Functions
atom()
xcb_atom_t QXcbConnection::atom (QXcbAtom::Atom atom)
Definition at line 633 of file qxcbconnection.cpp.
Referenced by QXcbObject::atom().
 {
     return m_allAtoms[atom];
 }
connection()
QXcbConnection* QXcbConnection::connection () const inline
Definition at line 227 of file qxcbconnection.h.
 { return const_cast<QXcbConnection *>(this); }
displayName()
const char* QXcbConnection::displayName () const inline
Definition at line 234 of file qxcbconnection.h.
 { return m_displayName.constData(); }
handleXcbError()
void QXcbConnection::handleXcbError (xcb_generic_error_t * error)
Definition at line 384 of file qxcbconnection.cpp.
Referenced by processXcbEvents(), and QXcbScreen::QXcbScreen().
 {
     uint clamped_error_code = qMin<uint>(error->error_code, (sizeof(xcb_errors) / sizeof(xcb_errors[0])) - 1);
     uint clamped_major_code = qMin<uint>(error->major_code, (sizeof(xcb_protocol_request_codes) / sizeof(xcb_protocol_request_codes[0])) - 1);
     printf("XCB error: %d (%s), sequence: %d, resource id: %d, major code: %d (%s), minor code: %d\n",
            int(error->error_code), xcb_errors[clamped_error_code],
            int(error->sequence), int(error->resource_id),
            int(error->major_code), xcb_protocol_request_codes[clamped_major_code],
            int(error->minor_code));
 #ifdef Q_XCB_DEBUG
     int i = 0;
     for (; i < m_callLog.size(); ++i) {
         if (m_callLog.at(i).sequence == error->sequence) {
             printf("Caused by: %s:%d\n", qPrintable(m_callLog.at(i).file), m_callLog.at(i).line);
             break;
         } else if (m_callLog.at(i).sequence > error->sequence) {
             printf("Caused some time before: %s:%d\n", qPrintable(m_callLog.at(i).file), m_callLog.at(i).line);
             if (i > 0)
                 printf("and after: %s:%d\n", qPrintable(m_callLog.at(i-1).file), m_callLog.at(i-1).line);
             break;
         }
     }
     if (i == m_callLog.size() && !m_callLog.isEmpty())
         printf("Caused some time after: %s:%d\n", qPrintable(m_callLog.first().file), m_callLog.first().line);
 #endif
 }
initializeAllAtoms()
void QXcbConnection::initializeAllAtoms () private
Definition at line 638 of file qxcbconnection.cpp.
Referenced by QXcbConnection().
{
     const char *names[QXcbAtom::NAtoms];
     const char *ptr = xcb_atomnames;
     int i = 0;
     while (*ptr) {
         names[i++] = ptr;
         while (*ptr)
             ++ptr;
         ++ptr;
     }
     Q_ASSERT(i == QXcbAtom::NPredefinedAtoms);
     QByteArray settings_atom_name("_QT_SETTINGS_TIMESTAMP_");
     settings_atom_name += m_displayName;
     names[i++] = settings_atom_name;
     xcb_intern_atom_cookie_t cookies[QXcbAtom::NAtoms];
     Q_ASSERT(i == QXcbAtom::NAtoms);
     for (i = 0; i < QXcbAtom::NAtoms; ++i)
         cookies[i] = xcb_intern_atom(xcb_connection(), false, strlen(names[i]), names[i]);
     for (i = 0; i < QXcbAtom::NAtoms; ++i)
         m_allAtoms[i] = xcb_intern_atom_reply(xcb_connection(), cookies[i], 0)->atom;
 }
keyboard()
QXcbKeyboard* QXcbConnection::keyboard () const inline
Definition at line 238 of file qxcbconnection.h.
 { return m_keyboard; }
log()
void QXcbConnection::log (const char * file, int line, int sequence) private
Definition at line 374 of file qxcbconnection.cpp.
Referenced by q_xcb_call_template().
 {
     CallInfo info;
     info.sequence = sequence;
     info.file = file;
     info.line = line;
     m_callLog << info;
 }
primaryScreen()
int QXcbConnection::primaryScreen () const inline
Definition at line 230 of file qxcbconnection.h.
Referenced by QXcbConnection().
 { return m_primaryScreen; }
processXcbEvents
void QXcbConnection::processXcbEvents () private slot
Definition at line 412 of file qxcbconnection.cpp.
Referenced by QXcbConnection().
 {
     while (xcb_generic_event_t *event = xcb_poll_for_event(xcb_connection())) {
         bool handled = true;
         uint response_type = event->response_type & ~0x80;
         if (!response_type) {
             handleXcbError((xcb_generic_error_t *)event);
             continue;
         }
 #ifdef Q_XCB_DEBUG
         {
             int i = 0;
             for (; i < m_callLog.size(); ++i)
                 if (m_callLog.at(i).sequence >= event->sequence)
                     break;
             m_callLog.remove(0, i);
         }
 #endif
         switch (response_type) {
         case XCB_EXPOSE:
             HANDLE_PLATFORM_WINDOW_EVENT(xcb_expose_event_t, window, handleExposeEvent);
         case XCB_BUTTON_PRESS:
             HANDLE_PLATFORM_WINDOW_EVENT(xcb_button_press_event_t, event, handleButtonPressEvent);
         case XCB_BUTTON_RELEASE:
             HANDLE_PLATFORM_WINDOW_EVENT(xcb_button_release_event_t, event, handleButtonReleaseEvent);
         case XCB_MOTION_NOTIFY:
             HANDLE_PLATFORM_WINDOW_EVENT(xcb_motion_notify_event_t, event, handleMotionNotifyEvent);
         case XCB_CONFIGURE_NOTIFY:
             HANDLE_PLATFORM_WINDOW_EVENT(xcb_configure_notify_event_t, event, handleConfigureNotifyEvent);
         case XCB_CLIENT_MESSAGE:
             HANDLE_PLATFORM_WINDOW_EVENT(xcb_client_message_event_t, window, handleClientMessageEvent);
         case XCB_ENTER_NOTIFY:
             HANDLE_PLATFORM_WINDOW_EVENT(xcb_enter_notify_event_t, event, handleEnterNotifyEvent);
         case XCB_LEAVE_NOTIFY:
             HANDLE_PLATFORM_WINDOW_EVENT(xcb_leave_notify_event_t, event, handleLeaveNotifyEvent);
         case XCB_FOCUS_IN:
             HANDLE_PLATFORM_WINDOW_EVENT(xcb_focus_in_event_t, event, handleFocusInEvent);
         case XCB_FOCUS_OUT:
             HANDLE_PLATFORM_WINDOW_EVENT(xcb_focus_out_event_t, event, handleFocusOutEvent);
         case XCB_KEY_PRESS:
             HANDLE_KEYBOARD_EVENT(xcb_key_press_event_t, handleKeyPressEvent);
         case XCB_KEY_RELEASE:
             HANDLE_KEYBOARD_EVENT(xcb_key_release_event_t, handleKeyReleaseEvent);
         case XCB_MAPPING_NOTIFY:
             m_keyboard->handleMappingNotifyEvent((xcb_mapping_notify_event_t *)event);
             break;
         default:
             handled = false;
             break;
         }
         if (handled)
             printXcbEvent("Handled XCB event", event);
         else
             printXcbEvent("Unhandled XCB event", event);
     }
     xcb_flush(xcb_connection());
 }
screens()
QList<QXcbScreen *> QXcbConnection::screens () const inline
Definition at line 229 of file qxcbconnection.h.
Referenced by QXcbIntegration::QXcbIntegration().
 { return m_screens; }
sendConnectionEvent()
void QXcbConnection::sendConnectionEvent (QXcbAtom::Atom atom, uint id = 0) private
sync()
void QXcbConnection::sync ()
Definition at line 666 of file qxcbconnection.cpp.
Referenced by QXcbWindowSurface::flush(), QXcbShmImage::preparePaint(), QXcbConnection(), QXcbWindow::requestActivateWindow(), QXcbWindow::setVisible(), and QXcbWindow::updateSyncRequestCounter().
 {
     // from xcb_aux_sync
     xcb_get_input_focus_cookie_t cookie = Q_XCB_CALL(xcb_get_input_focus(xcb_connection()));
     free(xcb_get_input_focus_reply(xcb_connection(), cookie, 0));
 }
xcb_connection()
xcb_connection_t* QXcbConnection::xcb_connection () const inline
Definition at line 236 of file qxcbconnection.h.
Referenced by initializeAllAtoms(), processXcbEvents(), QXcbConnection(), sync(), QXcbObject::xcb_connection(), and ~QXcbConnection().
 { return m_connection; }
Friends and Related Functions
q_xcb_call_template
template<typename cookie_t > cookie_t q_xcb_call_template (const cookie_t & cookie, QXcbConnection * connection, const char * file, int line) friend
Definition at line 312 of file qxcbconnection.h.
 {
     connection->log(file, line, cookie.sequence);
     return cookie;
 }
Properties
m_allAtoms
xcb_atom_t QXcbConnection::m_allAtoms[QXcbAtom::NAtoms] private
Definition at line 274 of file qxcbconnection.h.
Referenced by atom(), and initializeAllAtoms().
m_callLog
QVector<CallInfo> QXcbConnection::m_callLog private
Definition at line 301 of file qxcbconnection.h.
Referenced by handleXcbError(), log(), and processXcbEvents().
m_connection
xcb_connection_t* QXcbConnection::m_connection private
Definition at line 268 of file qxcbconnection.h.
Referenced by QXcbConnection(), and sync().
m_displayName
QByteArray QXcbConnection::m_displayName private
Definition at line 276 of file qxcbconnection.h.
Referenced by initializeAllAtoms(), and QXcbConnection().
m_keyboard
QXcbKeyboard* QXcbConnection::m_keyboard private
Definition at line 278 of file qxcbconnection.h.
Referenced by processXcbEvents(), QXcbConnection(), and ~QXcbConnection().
m_primaryScreen
int QXcbConnection::m_primaryScreen private
Definition at line 272 of file qxcbconnection.h.
m_screens
QList<QXcbScreen *> QXcbConnection::m_screens private
Definition at line 271 of file qxcbconnection.h.
Referenced by QXcbConnection(), sync(), and ~QXcbConnection().
m_setup
const xcb_setup_t* QXcbConnection::m_setup private
Definition at line 269 of file qxcbconnection.h.
Referenced by QXcbConnection().
The documentation for this class was generated from the following files:
/src/plugins/platforms/xcb/qxcbconnection.h
/src/plugins/platforms/xcb/qxcbconnection.cpp