Qt 4.8: QGLCustomShaderStage Class Reference
QGLCustomShaderStage Class Reference
#include <qglcustomshaderstage_p.h>
Public Functions
QGLCustomShaderStage ()
void removeFromPainter (QPainter *)
void setInactive ()
bool setOnPainter (QPainter *)
virtual void setUniforms (QGLShaderProgram *)
void setUniformsDirty ()
QByteArray source () const
virtual ~QGLCustomShaderStage ()
Protected Functions
void setSource (const QByteArray &)
Properties
QGLCustomShaderStagePrivate * d_ptr
Detailed Description
Definition at line 65 of file qglcustomshaderstage_p.h.
Constructors and Destructors
QGLCustomShaderStage()
QGLCustomShaderStage::QGLCustomShaderStage ()
Definition at line 62 of file qglcustomshaderstage.cpp.
     : d_ptr(new QGLCustomShaderStagePrivate)
 {
 }
~QGLCustomShaderStage()
QGLCustomShaderStage::~QGLCustomShaderStage () virtual
Definition at line 67 of file qglcustomshaderstage.cpp.
 {
     Q_D(QGLCustomShaderStage);
     if (d->m_manager) {
         d->m_manager->removeCustomStage();
         d->m_manager->sharedShaders->cleanupCustomStage(this);
     }
 }
Functions
removeFromPainter()
void QGLCustomShaderStage::removeFromPainter (QPainter * p)
Definition at line 101 of file qglcustomshaderstage.cpp.
Referenced by QGLPixmapColorizeFilter::processGL(), QGLPixmapConvolutionFilter::processGL(), and QGLPixmapDropShadowFilter::processGL().
 {
     Q_D(QGLCustomShaderStage);
     if (p->paintEngine()->type() != QPaintEngine::OpenGL2)
         return;
     QGL2PaintEngineEx *engine = static_cast<QGL2PaintEngineEx*>(p->paintEngine());
     d->m_manager = QGL2PaintEngineExPrivate::shaderManagerForEngine(engine);
     Q_ASSERT(d->m_manager);
     // Just set the stage to null, don't call removeCustomStage().
     // This should leave the program in a compiled/linked state
     // if the next custom shader stage is this one again.
     d->m_manager->setCustomStage(0);
     d->m_manager = 0;
 }
setInactive()
void QGLCustomShaderStage::setInactive ()
Definition at line 126 of file qglcustomshaderstage.cpp.
Referenced by QGLEngineShaderManager::removeCustomStage().
 {
     Q_D(QGLCustomShaderStage);
     d->m_manager = 0;
 }
setOnPainter()
bool QGLCustomShaderStage::setOnPainter (QPainter * p)
Definition at line 83 of file qglcustomshaderstage.cpp.
Referenced by QGLPixmapColorizeFilter::processGL(), QGLPixmapConvolutionFilter::processGL(), and QGLPixmapDropShadowFilter::processGL().
 {
     Q_D(QGLCustomShaderStage);
     if (p->paintEngine()->type() != QPaintEngine::OpenGL2) {
         qWarning("QGLCustomShaderStage::setOnPainter() - paint engine not OpenGL2");
         return false;
     }
     if (d->m_manager)
         qWarning("Custom shader is already set on a painter");
     QGL2PaintEngineEx *engine = static_cast<QGL2PaintEngineEx*>(p->paintEngine());
     d->m_manager = QGL2PaintEngineExPrivate::shaderManagerForEngine(engine);
     Q_ASSERT(d->m_manager);
     d->m_manager->setCustomStage(this);
     return true;
 }
setSource()
void QGLCustomShaderStage::setSource (const QByteArray & s) protected
Definition at line 132 of file qglcustomshaderstage.cpp.
Referenced by QGLPixmapConvolutionFilter::processGL(), QGLCustomShaderEffectStage::QGLCustomShaderEffectStage(), and QGLPixmapDropShadowFilter::QGLPixmapDropShadowFilter().
 {
     Q_D(QGLCustomShaderStage);
     d->m_source = s;
 }
setUniforms()
virtual void QGLCustomShaderStage::setUniforms (QGLShaderProgram *) inline virtual
Reimplemented in QGLCustomShaderEffectStage, QGLPixmapDropShadowFilter, QGLPixmapConvolutionFilter, and QGLPixmapColorizeFilter.
Definition at line 71 of file qglcustomshaderstage_p.h.
Referenced by QGLEngineShaderManager::useCorrectShaderProg().
 {}
setUniformsDirty()
void QGLCustomShaderStage::setUniformsDirty ()
Definition at line 76 of file qglcustomshaderstage.cpp.
 {
     Q_D(QGLCustomShaderStage);
     if (d->m_manager)
         d->m_manager->setDirty(); // ### Probably a bit overkill!
 }
source()
QByteArray QGLCustomShaderStage::source () const
Definition at line 118 of file qglcustomshaderstage.cpp.
Referenced by QGLEngineSharedShaders::cleanupCustomStage(), and QGLEngineShaderManager::useCorrectShaderProg().
 {
     Q_D(const QGLCustomShaderStage);
     return d->m_source;
 }
Properties
d_ptr
QGLCustomShaderStagePrivate* QGLCustomShaderStage::d_ptr private
Definition at line 84 of file qglcustomshaderstage_p.h.
The documentation for this class was generated from the following files:
/src/opengl/gl2paintengineex/qglcustomshaderstage_p.h
/src/opengl/gl2paintengineex/qglcustomshaderstage.cpp