Qt 4.8: QFontEngineMulti Class Reference
QFontEngineMulti Class Reference abstract
#include <qfontengine_p.h>
Public Functions
virtual void addOutlineToPath (qreal, qreal, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags flags)
virtual QImage alphaMapForGlyph (glyph_t)
virtual QFixed ascent () const
virtual QFixed averageCharWidth () const
virtual glyph_metrics_t boundingBox (const QGlyphLayout &glyphs)
virtual glyph_metrics_t boundingBox (glyph_t glyph)
virtual bool canRender (const QChar *string, int len)
virtual QFixed descent () const
virtual void doKerning (QGlyphLayout *, QTextEngine::ShaperFlags) const
QFontEngine * engine (int at) const
virtual void getGlyphBearings (glyph_t glyph, qreal *leftBearing=0, qreal *rightBearing=0)
virtual QFixed leading () const
virtual QFixed lineThickness () const
virtual qreal maxCharWidth () const
virtual qreal minLeftBearing () const
virtual qreal minRightBearing () const
virtual const char * name () const
QFontEngineMulti (int engineCount)
virtual void recalcAdvances (QGlyphLayout *, QTextEngine::ShaperFlags) const
virtual bool stringToCMap (const QChar *str, int len, QGlyphLayout *glyphs, int *nglyphs, QTextEngine::ShaperFlags flags) const
virtual Type type () const
virtual QFixed underlinePosition () const
virtual QFixed xHeight () const
~QFontEngineMulti ()
Public Functions inherited from QFontEngine
void addBitmapFontToPath (qreal x, qreal y, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags)
virtual void addGlyphsToPath (glyph_t *glyphs, QFixedPoint *positions, int nglyphs, QPainterPath *path, QTextItem::RenderFlags flags)
virtual glyph_metrics_t alphaMapBoundingBox (glyph_t glyph, QFixed, const QTransform &matrix, GlyphFormat)
virtual QImage alphaMapForGlyph (glyph_t glyph, QFixed subPixelPosition)
virtual QImage alphaMapForGlyph (glyph_t, const QTransform &t)
virtual QImage alphaMapForGlyph (glyph_t, QFixed subPixelPosition, const QTransform &t)
virtual QImage alphaRGBMapForGlyph (glyph_t, QFixed subPixelPosition, int margin, const QTransform &t)
virtual glyph_metrics_t boundingBox (glyph_t glyph, const QTransform &matrix)
virtual QFontEngine * cloneWithSize (qreal) const
virtual QFixed emSquareSize () const
virtual FaceId faceId () const
void getGlyphPositions (const QGlyphLayout &glyphs, const QTransform &matrix, QTextItem::RenderFlags flags, QVarLengthArray< glyph_t > &glyphs_out, QVarLengthArray< QFixedPoint > &positions)
virtual HB_Error getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed *xpos, HB_Fixed *ypos, hb_uint32 *nPoints)
QByteArray getSfntTable (uint) const
virtual bool getSfntTableData (uint, uchar *, uint *) const
virtual void getUnscaledGlyph (glyph_t glyph, QPainterPath *path, glyph_metrics_t *metrics)
QFontEngineGlyphCache * glyphCache (void *key, QFontEngineGlyphCache::Type type, const QTransform &transform) const
virtual int glyphCount () const
HB_Face harfbuzzFace () const
HB_Font harfbuzzFont () const
void loadKerningPairs (QFixed scalingFactor)
virtual Properties properties () const
QFontEngine ()
virtual void removeGlyphFromCache (glyph_t)
void setGlyphCache (void *key, QFontEngineGlyphCache *data)
virtual bool supportsSubPixelPositions () const
virtual int synthesized () const
glyph_metrics_t tightBoundingBox (const QGlyphLayout &glyphs)
virtual ~QFontEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual void loadEngine (int at)=0
Protected Functions inherited from QFontEngine
QFixed lastRightBearing (const QGlyphLayout &glyphs, bool round=false)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables
QVector< QFontEngine * > engines
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Friends
class QPSPrintEngineFontMulti
class QPSPrintEnginePrivate
class QRawFont
Additional Inherited Members
Public Types inherited from QFontEngine
enum GlyphFormat {
Format_None, Format_Render = Format_None, Format_Mono, Format_A8,
Format_A32
}
enum SynthesizedFlags { SynthesizedItalic = 0x1, SynthesizedBold = 0x2, SynthesizedStretch = 0x4 }
enum Type {
Box, Multi, XLFD, Win,
Mac, Freetype, QPF1, QPF2,
Proxy, S60FontEngine, DirectWrite, TestFontEngine = 0x1000
}
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QFontEngine
static QByteArray convertToPostscriptFontFamilyName (const QByteArray &fontFamily)
static const uchar * getCMap (const uchar *table, uint tableSize, bool *isSymbolFont, int *cmapSize)
static quint32 getTrueTypeGlyphIndex (const uchar *cmap, uint unicode)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables inherited from QFontEngine
uint cache_cost
int cache_count
QFontDef fontDef
uint fsType: 16
int glyphFormat
HB_Face hbFace
HB_FontRec hbFont
QVector< KernPair > kerning_pairs
QAtomicInt ref
bool symbol
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Static Protected Functions inherited from QFontEngine
static const QVector< QRgb > & grayPalette ()
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 389 of file qfontengine_p.h.
Constructors and Destructors
QFontEngineMulti()
QFontEngineMulti::QFontEngineMulti (int engineCount) explicit
Definition at line 1318 of file qfontengine.cpp.
 {
     engines.fill(0, engineCount);
     cache_cost = 0;
 }
~QFontEngineMulti()
QFontEngineMulti::~QFontEngineMulti ()
Definition at line 1324 of file qfontengine.cpp.
 {
     for (int i = 0; i < engines.size(); ++i) {
         QFontEngine *fontEngine = engines.at(i);
         if (fontEngine) {
             fontEngine->ref.deref();
             if (fontEngine->cache_count == 0 && fontEngine->ref == 0)
                 delete fontEngine;
         }
     }
 }
Functions
addOutlineToPath()
void QFontEngineMulti::addOutlineToPath (qreal x, qreal y, const QGlyphLayout & glyphs, QPainterPath * path, QTextItem::RenderFlags flags) virtual
Reimplemented from QFontEngine.
Definition at line 1455 of file qfontengine.cpp.
 {
     if (glyphs.numGlyphs <= 0)
         return;
     int which = highByte(glyphs.glyphs[0]);
     int start = 0;
     int end, i;
     if (flags & QTextItem::RightToLeft) {
         for (int gl = 0; gl < glyphs.numGlyphs; gl++) {
             x += glyphs.advances_x[gl].toReal();
             y += glyphs.advances_y[gl].toReal();
         }
     }
     for (end = 0; end < glyphs.numGlyphs; ++end) {
         const int e = highByte(glyphs.glyphs[end]);
         if (e == which)
             continue;
         if (flags & QTextItem::RightToLeft) {
             for (i = start; i < end; ++i) {
                 x -= glyphs.advances_x[i].toReal();
                 y -= glyphs.advances_y[i].toReal();
             }
         }
         // set the high byte to zero
         for (i = start; i < end; ++i)
             glyphs.glyphs[i] = stripped(glyphs.glyphs[i]);
         engine(which)->addOutlineToPath(x, y, glyphs.mid(start, end - start), path, flags);
         // reset the high byte for all glyphs and update x and y
         const int hi = which << 24;
         for (i = start; i < end; ++i)
             glyphs.glyphs[i] = hi | glyphs.glyphs[i];
         if (!(flags & QTextItem::RightToLeft)) {
             for (i = start; i < end; ++i) {
                 x += glyphs.advances_x[i].toReal();
                 y += glyphs.advances_y[i].toReal();
             }
         }
         // change engine
         start = end;
         which = e;
     }
     if (flags & QTextItem::RightToLeft) {
         for (i = start; i < end; ++i) {
             x -= glyphs.advances_x[i].toReal();
             y -= glyphs.advances_y[i].toReal();
         }
     }
     // set the high byte to zero
     for (i = start; i < end; ++i)
         glyphs.glyphs[i] = stripped(glyphs.glyphs[i]);
     engine(which)->addOutlineToPath(x, y, glyphs.mid(start, end - start), path, flags);
     // reset the high byte for all glyphs
     const int hi = which << 24;
     for (i = start; i < end; ++i)
         glyphs.glyphs[i] = hi | glyphs.glyphs[i];
 }
alphaMapForGlyph()
QImage QFontEngineMulti::alphaMapForGlyph (glyph_t glyph) virtual
Create a qimage with the alpha values for the glyph. Returns an image indexed_8 with index values ranging from 0=fully transparent to 255=opaque
Reimplemented from QFontEngine.
Definition at line 1684 of file qfontengine.cpp.
 {
     Q_ASSERT(false);
     return QImage();
 }
ascent()
QFixed QFontEngineMulti::ascent () const virtual
Implements QFontEngine.
Definition at line 1615 of file qfontengine.cpp.
 { return engine(0)->ascent(); }
averageCharWidth()
QFixed QFontEngineMulti::averageCharWidth () const virtual
Reimplemented from QFontEngine.
Definition at line 1631 of file qfontengine.cpp.
 {
     return engine(0)->averageCharWidth();
 }
boundingBox() [1/2]
glyph_metrics_t QFontEngineMulti::boundingBox (const QGlyphLayout & glyphs) virtual
Implements QFontEngine.
Definition at line 1386 of file qfontengine.cpp.
 {
     if (glyphs.numGlyphs <= 0)
         return glyph_metrics_t();
     glyph_metrics_t overall;
     int which = highByte(glyphs.glyphs[0]);
     int start = 0;
     int end, i;
     for (end = 0; end < glyphs.numGlyphs; ++end) {
         const int e = highByte(glyphs.glyphs[end]);
         if (e == which)
             continue;
         // set the high byte to zero
         for (i = start; i < end; ++i)
             glyphs.glyphs[i] = stripped(glyphs.glyphs[i]);
         // merge the bounding box for this run
         const glyph_metrics_t gm = engine(which)->boundingBox(glyphs.mid(start, end - start));
         overall.x = qMin(overall.x, gm.x);
         overall.y = qMin(overall.y, gm.y);
         overall.width = overall.xoff + gm.width;
         overall.height = qMax(overall.height + overall.y, gm.height + gm.y) -
                          qMin(overall.y, gm.y);
         overall.xoff += gm.xoff;
         overall.yoff += gm.yoff;
         // reset the high byte for all glyphs
         const int hi = which << 24;
         for (i = start; i < end; ++i)
             glyphs.glyphs[i] = hi | glyphs.glyphs[i];
         // change engine
         start = end;
         which = e;
     }
     // set the high byte to zero
     for (i = start; i < end; ++i)
         glyphs.glyphs[i] = stripped(glyphs.glyphs[i]);
     // merge the bounding box for this run
     const glyph_metrics_t gm = engine(which)->boundingBox(glyphs.mid(start, end - start));
     overall.x = qMin(overall.x, gm.x);
     overall.y = qMin(overall.y, gm.y);
     overall.width = overall.xoff + gm.width;
     overall.height = qMax(overall.height + overall.y, gm.height + gm.y) -
                      qMin(overall.y, gm.y);
     overall.xoff += gm.xoff;
     overall.yoff += gm.yoff;
     // reset the high byte for all glyphs
     const int hi = which << 24;
     for (i = start; i < end; ++i)
         glyphs.glyphs[i] = hi | glyphs.glyphs[i];
     return overall;
 }
boundingBox() [2/2]
glyph_metrics_t QFontEngineMulti::boundingBox (glyph_t glyph) virtual
Implements QFontEngine.
Definition at line 1608 of file qfontengine.cpp.
 {
     const int which = highByte(glyph);
     Q_ASSERT(which < engines.size());
     return engine(which)->boundingBox(stripped(glyph));
 }
canRender()
bool QFontEngineMulti::canRender (const QChar * string, int len) virtual
Implements QFontEngine.
Reimplemented in QFontEngineMacMulti.
Definition at line 1661 of file qfontengine.cpp.
Referenced by QFontEngineXLFD::type().
 {
     if (engine(0)->canRender(string, len))
         return true;
     QVarLengthGlyphLayoutArray glyphs(len);
     int nglyphs = len;
     if (stringToCMap(string, len, &glyphs, &nglyphs, QTextEngine::GlyphIndicesOnly) == false) {
         glyphs.resize(nglyphs);
         stringToCMap(string, len, &glyphs, &nglyphs, QTextEngine::GlyphIndicesOnly);
     }
     bool allExist = true;
     for (int i = 0; i < nglyphs; i++) {
         if (!glyphs.glyphs[i]) {
             allExist = false;
             break;
         }
     }
     return allExist;
 }
descent()
QFixed QFontEngineMulti::descent () const virtual
Implements QFontEngine.
Definition at line 1618 of file qfontengine.cpp.
 { return engine(0)->descent(); }
doKerning()
void QFontEngineMulti::doKerning (QGlyphLayout * glyphs, QTextEngine::ShaperFlags flags) const virtual
Reimplemented from QFontEngine.
Reimplemented in QFontEngineMacMulti.
Definition at line 1565 of file qfontengine.cpp.
 {
     if (glyphs->numGlyphs <= 0)
         return;
     int which = highByte(glyphs->glyphs[0]);
     int start = 0;
     int end, i;
     for (end = 0; end < glyphs->numGlyphs; ++end) {
         const int e = highByte(glyphs->glyphs[end]);
         if (e == which)
             continue;
         // set the high byte to zero
         for (i = start; i < end; ++i)
             glyphs->glyphs[i] = stripped(glyphs->glyphs[i]);
         QGlyphLayout offs = glyphs->mid(start, end - start);
         engine(which)->doKerning(&offs, flags);
         // reset the high byte for all glyphs and update x and y
         const int hi = which << 24;
         for (i = start; i < end; ++i)
             glyphs->glyphs[i] = hi | glyphs->glyphs[i];
         // change engine
         start = end;
         which = e;
     }
     // set the high byte to zero
     for (i = start; i < end; ++i)
         glyphs->glyphs[i] = stripped(glyphs->glyphs[i]);
     QGlyphLayout offs = glyphs->mid(start, end - start);
     engine(which)->doKerning(&offs, flags);
     // reset the high byte for all glyphs
     const int hi = which << 24;
     for (i = start; i < end; ++i)
         glyphs->glyphs[i] = hi | glyphs->glyphs[i];
 }
engine()
QFontEngine* QFontEngineMulti::engine (int at) const inline
Definition at line 426 of file qfontengine_p.h.
Referenced by QPainter::drawTextItem(), QFontDatabase::findFont(), QRawFont::fromFont(), QTextLine::glyphs(), QFontDatabase::load(), loadEngine(), and loadSingleEngine().
     {Q_ASSERT(at < engines.size()); return engines.at(at); }
getGlyphBearings()
void QFontEngineMulti::getGlyphBearings (glyph_t glyph, qreal * leftBearing = 0, qreal * rightBearing = 0) virtual
Reimplemented from QFontEngine.
Definition at line 1449 of file qfontengine.cpp.
 {
     int which = highByte(glyph);
     engine(which)->getGlyphBearings(stripped(glyph), leftBearing, rightBearing);
 }
leading()
QFixed QFontEngineMulti::leading () const virtual
Implements QFontEngine.
Definition at line 1621 of file qfontengine.cpp.
 {
     return engine(0)->leading();
 }
lineThickness()
QFixed QFontEngineMulti::lineThickness () const virtual
Reimplemented from QFontEngine.
Definition at line 1636 of file qfontengine.cpp.
 {
     return engine(0)->lineThickness();
 }
loadEngine()
virtual void QFontEngineMulti::loadEngine (int at) protected pure virtual
Implemented in QFontEngineMultiQWS, QFontEngineMultiQPA, QFontEngineMultiWin, QFontEngineMacMulti, QFontEngineMultiFT, QCoreTextFontEngineMulti, and QFontEngineMultiXLFD.
Referenced by QRawFont::fromFont().
maxCharWidth()
qreal QFontEngineMulti::maxCharWidth () const virtual
Implements QFontEngine.
Definition at line 1646 of file qfontengine.cpp.
Referenced by QFontEngineMacMulti::stringToCMap().
 {
     return engine(0)->maxCharWidth();
 }
minLeftBearing()
qreal QFontEngineMulti::minLeftBearing () const virtual
Reimplemented from QFontEngine.
Definition at line 1651 of file qfontengine.cpp.
 {
     return engine(0)->minLeftBearing();
 }
minRightBearing()
qreal QFontEngineMulti::minRightBearing () const virtual
Reimplemented from QFontEngine.
Definition at line 1656 of file qfontengine.cpp.
 {
     return engine(0)->minRightBearing();
 }
name()
virtual const char* QFontEngineMulti::name () const inline virtual
Implements QFontEngine.
Reimplemented in QFontEngineMacMulti, and QCoreTextFontEngineMulti.
Definition at line 423 of file qfontengine_p.h.
Referenced by QFontEngineXLFD::type().
     { return "Multi"; }
recalcAdvances()
void QFontEngineMulti::recalcAdvances (QGlyphLayout * , QTextEngine::ShaperFlags) const virtual
This is a callback from harfbuzz. The font engine uses the font-system in use to find out the advances of each glyph and set it on the layout.
Reimplemented from QFontEngine.
Reimplemented in QFontEngineMacMulti.
Definition at line 1522 of file qfontengine.cpp.
 {
     if (glyphs->numGlyphs <= 0)
         return;
     int which = highByte(glyphs->glyphs[0]);
     int start = 0;
     int end, i;
     for (end = 0; end < glyphs->numGlyphs; ++end) {
         const int e = highByte(glyphs->glyphs[end]);
         if (e == which)
             continue;
         // set the high byte to zero
         for (i = start; i < end; ++i)
             glyphs->glyphs[i] = stripped(glyphs->glyphs[i]);
         QGlyphLayout offs = glyphs->mid(start, end - start);
         engine(which)->recalcAdvances(&offs, flags);
         // reset the high byte for all glyphs and update x and y
         const int hi = which << 24;
         for (i = start; i < end; ++i)
             glyphs->glyphs[i] = hi | glyphs->glyphs[i];
         // change engine
         start = end;
         which = e;
     }
     // set the high byte to zero
     for (i = start; i < end; ++i)
         glyphs->glyphs[i] = stripped(glyphs->glyphs[i]);
     QGlyphLayout offs = glyphs->mid(start, end - start);
     engine(which)->recalcAdvances(&offs, flags);
     // reset the high byte for all glyphs
     const int hi = which << 24;
     for (i = start; i < end; ++i)
         glyphs->glyphs[i] = hi | glyphs->glyphs[i];
 }
stringToCMap()
bool QFontEngineMulti::stringToCMap (const QChar * str, int len, QGlyphLayout * glyphs, int * nglyphs, QTextEngine::ShaperFlags flags) const virtual
Implements QFontEngine.
Reimplemented in QFontEngineMacMulti, and QCoreTextFontEngineMulti.
Definition at line 1336 of file qfontengine.cpp.
 {
     int ng = *nglyphs;
     if (!engine(0)->stringToCMap(str, len, glyphs, &ng, flags))
         return false;
     int glyph_pos = 0;
     for (int i = 0; i < len; ++i) {
         bool surrogate = (str[i].isHighSurrogate() && i < len-1 && str[i+1].isLowSurrogate());
         if (glyphs->glyphs[glyph_pos] == 0 && str[i].category() != QChar::Separator_Line) {
             QGlyphLayoutInstance tmp = glyphs->instance(glyph_pos);
             for (int x = 1; x < engines.size(); ++x) {
                 QFontEngine *engine = engines.at(x);
                 if (!engine) {
                     const_cast<QFontEngineMulti *>(this)->loadEngine(x);
                     engine = engines.at(x);
                 }
                 Q_ASSERT(engine != 0);
                 if (engine->type() == Box)
                     continue;
                 glyphs->advances_x[glyph_pos] = glyphs->advances_y[glyph_pos] = 0;
                 glyphs->offsets[glyph_pos] = QFixedPoint();
                 int num = 2;
                 QGlyphLayout offs = glyphs->mid(glyph_pos, num);
                 engine->stringToCMap(str + i, surrogate ? 2 : 1, &offs, &num, flags);
                 Q_ASSERT(num == 1); // surrogates only give 1 glyph
                 if (glyphs->glyphs[glyph_pos]) {
                     // set the high byte to indicate which engine the glyph came from
                     glyphs->glyphs[glyph_pos] |= (x << 24);
                     break;
                 }
             }
             // ensure we use metrics from the 1st font when we use the fallback image.
             if (!glyphs->glyphs[glyph_pos]) {
                 glyphs->setInstance(glyph_pos, tmp);
             }
         }
         if (surrogate)
             ++i;
         ++glyph_pos;
     }
     *nglyphs = ng;
     glyphs->numGlyphs = ng;
     return true;
 }
type()
virtual Type QFontEngineMulti::type () const inline virtual
Implements QFontEngine.
Definition at line 419 of file qfontengine_p.h.
     { return QFontEngine::Multi; }
underlinePosition()
QFixed QFontEngineMulti::underlinePosition () const virtual
Reimplemented from QFontEngine.
Definition at line 1641 of file qfontengine.cpp.
 {
     return engine(0)->underlinePosition();
 }
xHeight()
QFixed QFontEngineMulti::xHeight () const virtual
Reimplemented from QFontEngine.
Definition at line 1626 of file qfontengine.cpp.
 {
     return engine(0)->xHeight();
 }
Friends and Related Functions
QPSPrintEngineFontMulti
friend class QPSPrintEngineFontMulti friend
Definition at line 432 of file qfontengine_p.h.
QPSPrintEnginePrivate
friend class QPSPrintEnginePrivate friend
Definition at line 431 of file qfontengine_p.h.
QRawFont
friend class QRawFont friend
Definition at line 433 of file qfontengine_p.h.
Properties
engines
QVector<QFontEngine *> QFontEngineMulti::engines protected
Definition at line 435 of file qfontengine_p.h.
Referenced by QFontEngineMacMulti::fontIndexForFontID(), QFontEngineMultiXLFD::loadEngine(), QFontEngineMultiFT::loadEngine(), QFontEngineMultiWin::loadEngine(), QFontEngineMultiQPA::loadEngine(), QFontEngineMultiQWS::loadEngine(), QFontEngineMacMulti::QFontEngineMacMulti(), QFontEngineMultiFT::QFontEngineMultiFT(), QFontEngineMultiQPA::QFontEngineMultiQPA(), QFontEngineMultiQWS::QFontEngineMultiQWS(), QFontEngineMultiWin::QFontEngineMultiWin(), QFontEngineMultiXLFD::QFontEngineMultiXLFD(), and QFontEngineMacMulti::~QFontEngineMacMulti().
The documentation for this class was generated from the following files:
/src/gui/text/qfontengine_p.h
/src/gui/text/qfontengine.cpp