Qt 4.8: QTextCodecPlugin Class Reference
QTextCodecPlugin Class Reference abstract
The QTextCodecPlugin class provides an abstract base for custom QTextCodec plugins.
#include <qtextcodecplugin.h>
Public Functions
virtual QList< QByteArray > aliases () const =0
Returns the list of aliases supported by this plugin.
virtual QTextCodec * createForMib (int mib)=0
Creates a QTextCodec object for the mib enum mib.
virtual QTextCodec * createForName (const QByteArray &name)=0
Creates a QTextCodec object for the codec called name.
virtual QList< int > mibEnums () const =0
Returns the list of mib enums supported by this plugin.
virtual QList< QByteArray > names () const =0
Returns the list of MIME names supported by this plugin.
QTextCodecPlugin (QObject *parent=0)
Constructs a text codec plugin with the given parent.
~QTextCodecPlugin ()
Destroys the text codec plugin.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QFactoryInterface
virtual ~QFactoryInterface ()
Private Functions
QTextCodec * create (const QString &name)
QStringList keys () const
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QTextCodecPlugin class provides an abstract base for custom QTextCodec plugins.
Note
This class or function is reentrant.
The text codec plugin is a simple plugin interface that makes it easy to create custom text codecs that can be loaded dynamically into applications.
Writing a text codec plugin is achieved by subclassing this base class, reimplementing the pure virtual functions names(), aliases(), createForName(), mibEnums() and createForMib(), and exporting the class with the Q_EXPORT_PLUGIN2() macro. See How to Create Qt Plugins for details.
See the IANA character-sets encoding file for more information on mime names and mib enums.
Definition at line 70 of file qtextcodecplugin.h.
Constructors and Destructors
QTextCodecPlugin()
QTextCodecPlugin::QTextCodecPlugin (QObject * parent = 0) explicit
Constructs a text codec plugin with the given parent.
This is invoked automatically by the Q_EXPORT_PLUGIN2() macro.
Definition at line 134 of file qtextcodecplugin.cpp.
     : QObject(parent)
 {
 }
~QTextCodecPlugin()
QTextCodecPlugin::~QTextCodecPlugin ()
Destroys the text codec plugin.
You never have to call this explicitly. Qt destroys a plugin automatically when it is no longer used.
Definition at line 145 of file qtextcodecplugin.cpp.
 {
 }
Functions
aliases()
QList< QByteArray > QTextCodecPlugin::aliases () const pure virtual
Returns the list of aliases supported by this plugin.
Implemented in JPTextCodecs, CNTextCodecs, KRTextCodecs, and TWTextCodecs.
Referenced by keys().
create()
QTextCodec * QTextCodecPlugin::create (const QString & name) private virtual
Implements QTextCodecFactoryInterface.
Definition at line 162 of file qtextcodecplugin.cpp.
 {
     if (name.startsWith(QLatin1String("MIB: ")))
         return createForMib(name.mid(4).toInt());
     return createForName(name.toLatin1());
 }
createForMib()
QTextCodec * QTextCodecPlugin::createForMib (int mib) pure virtual
Creates a QTextCodec object for the mib enum mib.
See the IANA character-sets encoding file for more information.
See also
mibEnums()
Implemented in JPTextCodecs, CNTextCodecs, KRTextCodecs, and TWTextCodecs.
Referenced by create().
createForName()
QTextCodec * QTextCodecPlugin::createForName (const QByteArray & name) pure virtual
Creates a QTextCodec object for the codec called name.
The name must come from the list of encodings returned by names(). Encoding names are case sensitive.
Example:
QList<QByteArray> MyCodecPlugin::names() const
{
    return QList<QByteArray> << "IBM01140" << "hp15-tw";
}
QTextCodec *MyCodecPlugin::createForName(const QByteArray &name)
{
    if (name == "IBM01140") {
        return new Ibm01140Codec;
    } else if (name == "hp15-tw") {
        return new Hp15TwCodec;
    }
    return 0;
}
See also
names()
Implemented in JPTextCodecs, CNTextCodecs, KRTextCodecs, and TWTextCodecs.
Referenced by create().
keys()
QStringList QTextCodecPlugin::keys () const private virtual
Implements QFactoryInterface.
Definition at line 149 of file qtextcodecplugin.cpp.
 {
     QStringList keys;
     QList<QByteArray> list = names();
     list += aliases();
     for (int i = 0; i < list.size(); ++i)
         keys += QString::fromLatin1(list.at(i));
     QList<int> mibs = mibEnums();
     for (int i = 0; i < mibs.count(); ++i)
         keys += QLatin1String("MIB: ") + QString::number(mibs.at(i));
     return keys;
 }
mibEnums()
QList< int > QTextCodecPlugin::mibEnums () const pure virtual
Returns the list of mib enums supported by this plugin.
See also
createForMib()
Implemented in JPTextCodecs, CNTextCodecs, KRTextCodecs, and TWTextCodecs.
Referenced by keys().
names()
QStringList QTextCodecPlugin::names () const pure virtual
Returns the list of MIME names supported by this plugin.
If a codec has several names, the extra names are returned by aliases().
See also
createForName(), aliases()
Implemented in JPTextCodecs, CNTextCodecs, KRTextCodecs, and TWTextCodecs.
Referenced by keys().
The documentation for this class was generated from the following files:
/src/corelib/codecs/qtextcodecplugin.h
/src/corelib/codecs/qtextcodecplugin.cpp