Qt 4.8: QMacPasteboard Class Reference
QMacPasteboard Class Reference
#include <qt_mac_p.h>
Classes
struct Promise
Public Functions
void clear ()
QStringList formats () const
bool hasFlavor (QString flavor) const
bool hasFormat (const QString &format) const
bool hasOSType (int c_flavor) const
QMimeData * mimeData () const
OSPasteboardRef pasteBoard () const
QMacPasteboard (OSPasteboardRef p, uchar mime_type=0)
QMacPasteboard (uchar mime_type)
QMacPasteboard (CFStringRef name=0, uchar mime_type=0)
QVariant retrieveData (const QString &format, QVariant::Type) const
void setMimeData (QMimeData *mime)
bool sync () const
~QMacPasteboard ()
Private Functions
void clear_helper ()
Static Private Functions
static OSStatus promiseKeeper (OSPasteboardRef, PasteboardItemID, CFStringRef, void *)
Properties
bool mac_mime_source
QPointer< QMimeData > mime
uchar mime_type
OSPasteboardRef paste
QList< Promise > promises
Detailed Description
Definition at line 211 of file qt_mac_p.h.
Constructors and Destructors
QMacPasteboard() [1/3]
QMacPasteboard::QMacPasteboard (OSPasteboardRef p, uchar mime_type = 0)
Definition at line 168 of file qclipboard_mac.cpp.
 {
     mac_mime_source = false;
     mime_type = mt ? mt : uchar(QMacPasteboardMime::MIME_ALL);
     paste = p;
     CFRetain(paste);
 }
QMacPasteboard() [2/3]
QMacPasteboard::QMacPasteboard (uchar mime_type)
Definition at line 176 of file qclipboard_mac.cpp.
 {
     mac_mime_source = false;
     mime_type = mt ? mt : uchar(QMacPasteboardMime::MIME_ALL);
     paste = 0;
     OSStatus err = PasteboardCreate(0, &paste);
     if(err == noErr) {
         PasteboardSetPromiseKeeper(paste, promiseKeeper, this);
     } else {
         qDebug("PasteBoard: Error creating pasteboard: [%d]", (int)err);
     }
 }
QMacPasteboard() [3/3]
QMacPasteboard::QMacPasteboard (CFStringRef name = 0, uchar mime_type = 0)
Definition at line 189 of file qclipboard_mac.cpp.
 {
     mac_mime_source = false;
     mime_type = mt ? mt : uchar(QMacPasteboardMime::MIME_ALL);
     paste = 0;
     OSStatus err = PasteboardCreate(name, &paste);
     if(err == noErr) {
         PasteboardSetPromiseKeeper(paste, promiseKeeper, this);
     } else {
         qDebug("PasteBoard: Error creating pasteboard: %s [%d]", QCFString::toQString(name).toLatin1().constData(), (int)err);
     }
 }
~QMacPasteboard()
QMacPasteboard::~QMacPasteboard ()
Definition at line 202 of file qclipboard_mac.cpp.
 {
     // commit all promises for paste after exit close
     for (int i = 0; i < promises.count(); ++i) {
         const Promise &promise = promises.at(i);
         QCFString flavor = QCFString(promise.convertor->flavorFor(promise.mime));
         promiseKeeper(paste, (PasteboardItemID)promise.itemId, flavor, this);
     }
     if(paste)
         CFRelease(paste);
 }
Functions
clear()
void QMacPasteboard::clear ()
Definition at line 606 of file qclipboard_mac.cpp.
Referenced by QClipboard::clear().
 {
 #ifdef DEBUG_PASTEBOARD
     qDebug("PasteBoard: clear!");
 #endif
     clear_helper();
 }
clear_helper()
void QMacPasteboard::clear_helper () private
Definition at line 598 of file qclipboard_mac.cpp.
 {
     if (paste)
         PasteboardClear(paste);
     promises.clear();
 }
formats()
QStringList QMacPasteboard::formats () const
Definition at line 434 of file qclipboard_mac.cpp.
Referenced by QMacPasteboardMimeSource::formats(), QDropData::formats_sys(), and QCocoaDropData::formats_sys().
 {
     if (!paste)
         return QStringList();
     sync();
     QStringList ret;
     ItemCount cnt = 0;
     if(PasteboardGetItemCount(paste, &cnt) || !cnt)
         return ret;
 #ifdef DEBUG_PASTEBOARD
     qDebug("PasteBoard: Formats [%d]", (int)cnt);
 #endif
     for(uint index = 1; index <= cnt; ++index) {
         PasteboardItemID id;
         if(PasteboardGetItemIdentifier(paste, index, &id) != noErr)
             continue;
         QCFType<CFArrayRef> types;
         if(PasteboardCopyItemFlavors(paste, id, &types ) != noErr)
             continue;
         const int type_count = CFArrayGetCount(types);
         for(int i = 0; i < type_count; ++i) {
             const QString flavor = QCFString::toQString((CFStringRef)CFArrayGetValueAtIndex(types, i));
 #ifdef DEBUG_PASTEBOARD
             qDebug(" -%s", qPrintable(QString(flavor)));
 #endif
             QString mimeType = QMacPasteboardMime::flavorToMime(mime_type, flavor);
             if(!mimeType.isEmpty() && !ret.contains(mimeType)) {
 #ifdef DEBUG_PASTEBOARD
                 qDebug("   -<%d> %s [%s]", ret.size(), qPrintable(mimeType), qPrintable(QString(flavor)));
 #endif
                 ret << mimeType;
             }
         }
     }
     return ret;
 }
hasFlavor()
bool QMacPasteboard::hasFlavor (QString flavor) const
Definition at line 312 of file qclipboard_mac.cpp.
 {
     if (!paste)
         return false;
     sync();
     ItemCount cnt = 0;
     if(PasteboardGetItemCount(paste, &cnt) || !cnt)
         return false;
 #ifdef DEBUG_PASTEBOARD
     qDebug("PasteBoard: hasFlavor [%s]", qPrintable(c_flavor));
 #endif
     for(uint index = 1; index <= cnt; ++index) {
         PasteboardItemID id;
         if(PasteboardGetItemIdentifier(paste, index, &id) != noErr)
             return false;
         PasteboardFlavorFlags flags;
         if(PasteboardGetItemFlavorFlags(paste, id, QCFString(c_flavor), &flags) == noErr) {
 #ifdef DEBUG_PASTEBOARD
             qDebug("  - Found!");
 #endif
             return true;
         }
     }
 #ifdef DEBUG_PASTEBOARD
     qDebug("  - NotFound!");
 #endif
     return false;
 }
hasFormat()
bool QMacPasteboard::hasFormat (const QString & format) const
Definition at line 478 of file qclipboard_mac.cpp.
Referenced by QDropData::hasFormat_sys(), and QCocoaDropData::hasFormat_sys().
 {
     if (!paste)
         return false;
     sync();
     ItemCount cnt = 0;
     if(PasteboardGetItemCount(paste, &cnt) || !cnt)
         return false;
 #ifdef DEBUG_PASTEBOARD
     qDebug("PasteBoard: hasFormat [%s]", qPrintable(format));
 #endif
     for(uint index = 1; index <= cnt; ++index) {
         PasteboardItemID id;
         if(PasteboardGetItemIdentifier(paste, index, &id) != noErr)
             continue;
         QCFType<CFArrayRef> types;
         if(PasteboardCopyItemFlavors(paste, id, &types ) != noErr)
             continue;
         const int type_count = CFArrayGetCount(types);
         for(int i = 0; i < type_count; ++i) {
             const QString flavor = QCFString::toQString((CFStringRef)CFArrayGetValueAtIndex(types, i));
 #ifdef DEBUG_PASTEBOARD
             qDebug(" -%s [0x%x]", qPrintable(QString(flavor)), mime_type);
 #endif
             QString mimeType = QMacPasteboardMime::flavorToMime(mime_type, flavor);
 #ifdef DEBUG_PASTEBOARD
             if(!mimeType.isEmpty())
                 qDebug("   - %s", qPrintable(mimeType));
 #endif
             if(mimeType == format)
                 return true;
         }
     }
     return false;
 }
hasOSType()
bool QMacPasteboard::hasOSType (int c_flavor) const
Definition at line 268 of file qclipboard_mac.cpp.
 {
     if (!paste)
         return false;
     sync();
     ItemCount cnt = 0;
     if(PasteboardGetItemCount(paste, &cnt) || !cnt)
         return false;
 #ifdef DEBUG_PASTEBOARD
     qDebug("PasteBoard: hasOSType [%c%c%c%c]", (c_flavor>>24)&0xFF, (c_flavor>>16)&0xFF,
            (c_flavor>>8)&0xFF, (c_flavor>>0)&0xFF);
 #endif
     for(uint index = 1; index <= cnt; ++index) {
         PasteboardItemID id;
         if(PasteboardGetItemIdentifier(paste, index, &id) != noErr)
             return false;
         QCFType<CFArrayRef> types;
         if(PasteboardCopyItemFlavors(paste, id, &types ) != noErr)
             return false;
         const int type_count = CFArrayGetCount(types);
         for(int i = 0; i < type_count; ++i) {
             CFStringRef flavor = (CFStringRef)CFArrayGetValueAtIndex(types, i);
             const int os_flavor = UTGetOSTypeFromString(UTTypeCopyPreferredTagWithClass(flavor, kUTTagClassOSType));
             if(os_flavor == c_flavor) {
 #ifdef DEBUG_PASTEBOARD
                 qDebug("  - Found!");
 #endif
                 return true;
             }
         }
     }
 #ifdef DEBUG_PASTEBOARD
     qDebug("  - NotFound!");
 #endif
     return false;
 }
mimeData()
QMimeData * QMacPasteboard::mimeData () const
Definition at line 356 of file qclipboard_mac.cpp.
Referenced by QClipboard::mimeData().
 {
     if(!mime) {
         mac_mime_source = true;
         mime = new QMacPasteboardMimeSource(this);
     }
     return mime;
 }
pasteBoard()
PasteboardRef QMacPasteboard::pasteBoard () const
Definition at line 216 of file qclipboard_mac.cpp.
Referenced by QDragManager::drag().
 {
     return paste;
 }
promiseKeeper()
OSStatus QMacPasteboard::promiseKeeper (OSPasteboardRef paste, PasteboardItemID id, CFStringRef flavor, void * _qpaste) static private
Definition at line 221 of file qclipboard_mac.cpp.
 {
     QMacPasteboard *qpaste = (QMacPasteboard*)_qpaste;
     const long promise_id = (long)id;
     // Find the kept promise
     const QString flavorAsQString = QCFString::toQString(flavor);
     QMacPasteboard::Promise promise;
     for (int i = 0; i < qpaste->promises.size(); i++){
         QMacPasteboard::Promise tmp = qpaste->promises[i];
         if (tmp.itemId == promise_id && tmp.convertor->canConvert(tmp.mime, flavorAsQString)){
             promise = tmp;
             break;
         }
     }
     if (!promise.itemId && flavorAsQString == QLatin1String("com.trolltech.qt.MimeTypeName")) {
         // we have promised this data, but wont be able to convert, so return null data.
         // This helps in making the application/x-qt-mime-type-name hidden from normal use.
         QByteArray ba;
         QCFType<CFDataRef> data = CFDataCreate(0, (UInt8*)ba.constData(), ba.size());
         PasteboardPutItemFlavor(paste, id, flavor, data, kPasteboardFlavorNoFlags);
         return noErr;
     }
     if (!promise.itemId) {
         // There was no promise that could deliver data for the
         // given id and flavor. This should not happend.
         qDebug("Pasteboard: %d: Request for %ld, %s, but no promise found!", __LINE__, promise_id, qPrintable(flavorAsQString));
         return cantGetFlavorErr;
     }
 #ifdef DEBUG_PASTEBOARD
     qDebug("PasteBoard: Calling in promise for %s[%ld] [%s] (%s) [%d]", qPrintable(promise.mime), promise_id,
            qPrintable(flavorAsQString), qPrintable(promise.convertor->convertorName()), promise.offset);
 #endif
     QList<QByteArray> md = promise.convertor->convertFromMime(promise.mime, promise.data, flavorAsQString);
     if (md.size() <= promise.offset)
         return cantGetFlavorErr;
     const QByteArray &ba = md[promise.offset];
     QCFType<CFDataRef> data = CFDataCreate(0, (UInt8*)ba.constData(), ba.size());
     PasteboardPutItemFlavor(paste, id, flavor, data, kPasteboardFlavorNoFlags);
     return noErr;
 }
retrieveData()
QVariant QMacPasteboard::retrieveData (const QString & format, QVariant::Type) const
Definition at line 521 of file qclipboard_mac.cpp.
Referenced by QMacPasteboardMimeSource::retrieveData(), QDropData::retrieveData_sys(), and QCocoaDropData::retrieveData_sys().
 {
     if (!paste)
         return QVariant();
     sync();
     ItemCount cnt = 0;
     if(PasteboardGetItemCount(paste, &cnt) || !cnt)
         return QByteArray();
 #ifdef DEBUG_PASTEBOARD
     qDebug("Pasteboard: retrieveData [%s]", qPrintable(format));
 #endif
     const QList<QMacPasteboardMime *> mimes = QMacPasteboardMime::all(mime_type);
     for(int mime = 0; mime < mimes.size(); ++mime) {
         QMacPasteboardMime *c = mimes.at(mime);
         QString c_flavor = c->flavorFor(format);
         if(!c_flavor.isEmpty()) {
             // Handle text/plain a little differently. Try handling Unicode first.
             bool checkForUtf16 = (c_flavor == QLatin1String("com.apple.traditional-mac-plain-text")
                                   || c_flavor == QLatin1String("public.utf8-plain-text"));
             if (checkForUtf16 || c_flavor == QLatin1String("public.utf16-plain-text")) {
                 // Try to get the NSStringPboardType from NSPasteboard, newlines are mapped
                 // correctly (as '\n') in this data. The 'public.utf16-plain-text' type
                 // usually maps newlines to '\r' instead.
                 QString str = qt_mac_get_pasteboardString(paste);
                 if (!str.isEmpty())
                     return str;
             }
             if (checkForUtf16 && hasFlavor(QLatin1String("public.utf16-plain-text")))
                 c_flavor = QLatin1String("public.utf16-plain-text");
             QVariant ret;
             QList<QByteArray> retList;
             for(uint index = 1; index <= cnt; ++index) {
                 PasteboardItemID id;
                 if(PasteboardGetItemIdentifier(paste, index, &id) != noErr)
                     continue;
                 QCFType<CFArrayRef> types;
                 if(PasteboardCopyItemFlavors(paste, id, &types ) != noErr)
                     continue;
                 const int type_count = CFArrayGetCount(types);
                 for(int i = 0; i < type_count; ++i) {
                     CFStringRef flavor = static_cast<CFStringRef>(CFArrayGetValueAtIndex(types, i));
                     if(c_flavor == QCFString::toQString(flavor)) {
                         QCFType<CFDataRef> macBuffer;
                         if(PasteboardCopyItemFlavorData(paste, id, flavor, &macBuffer) == noErr) {
                             QByteArray buffer((const char *)CFDataGetBytePtr(macBuffer), CFDataGetLength(macBuffer));
                             if(!buffer.isEmpty()) {
 #ifdef DEBUG_PASTEBOARD
                                 qDebug("  - %s [%s] (%s)", qPrintable(format), qPrintable(QCFString::toQString(flavor)), qPrintable(c->convertorName()));
 #endif
                                 buffer.detach(); //detach since we release the macBuffer
                                 retList.append(buffer);
                                 break; //skip to next element
                             }
                         }
                     } else {
 #ifdef DEBUG_PASTEBOARD
                         qDebug("  - NoMatch %s [%s] (%s)", qPrintable(c_flavor), qPrintable(QCFString::toQString(flavor)), qPrintable(c->convertorName()));
 #endif
                     }
                 }
             }
             if (!retList.isEmpty()) {
                 ret = c->convertToMime(format, retList, c_flavor);
                 return ret;
             }
         }
     }
     return QVariant();
 }
setMimeData()
void QMacPasteboard::setMimeData (QMimeData * mime)
Definition at line 375 of file qclipboard_mac.cpp.
Referenced by QDragManager::drag(), and QClipboard::setMimeData().
 {
     if (!paste)
         return;
     if (mime == mime_src || (!mime_src && mime && mac_mime_source))
         return;
     mac_mime_source = false;
     delete mime;
     mime = mime_src;
     QList<QMacPasteboardMime*> availableConverters = QMacPasteboardMime::all(mime_type);
     if (mime != 0) {
         clear_helper();
         QStringList formats = mime_src->formats();
 #ifdef QT_MAC_USE_COCOA
         // QMimeData sub classes reimplementing the formats() might not expose the
         // temporary "application/x-qt-mime-type-name" mimetype. So check the existence
         // of this mime type while doing drag and drop.
         QString dummyMimeType(QLatin1String("application/x-qt-mime-type-name"));
         if (!formats.contains(dummyMimeType)) {
             QByteArray dummyType = mime_src->data(dummyMimeType);
             if (!dummyType.isEmpty()) {
                 formats.append(dummyMimeType);
             }
         }
 #endif
         for(int f = 0; f < formats.size(); ++f) {
             QString mimeType = formats.at(f);
             for (QList<QMacPasteboardMime *>::Iterator it = availableConverters.begin(); it != availableConverters.end(); ++it) {
                 QMacPasteboardMime *c = (*it);
                 QString flavor(c->flavorFor(mimeType));
                 if(!flavor.isEmpty()) {
                     QVariant mimeData = static_cast<QMacMimeData*>(mime_src)->variantData(mimeType);
 #if 0
                     //### Grrr, why didn't I put in a virtual int QMacPasteboardMime::count()? --Sam
                     const int numItems = c->convertFromMime(mimeType, mimeData, flavor).size();
 #else
                     int numItems = 1; //this is a hack but it is much faster than allowing conversion above
                     if(c->convertorName() == QLatin1String("FileURL"))
                         numItems = mime_src->urls().count();
 #endif
                     for(int item = 0; item < numItems; ++item) {
                         const int itemID = item+1; //id starts at 1
                         promises.append(QMacPasteboard::Promise(itemID, c, mimeType, mimeData, item));
                         PasteboardPutItemFlavor(paste, (PasteboardItemID)itemID, QCFString(flavor), 0, kPasteboardFlavorNoFlags);
 #ifdef DEBUG_PASTEBOARD
                         qDebug(" -  adding %d %s [%s] <%s> [%d]",
                                itemID, qPrintable(mimeType), qPrintable(flavor), qPrintable(c->convertorName()), item);
 #endif
                     }
                 }
             }
         }
     }
 }
sync()
bool QMacPasteboard::sync () const
Definition at line 615 of file qclipboard_mac.cpp.
Referenced by qt_mac_updateScrap().
 {
     if (!paste)
         return false;
     const bool fromGlobal = PasteboardSynchronize(paste) & kPasteboardModified;
     if (fromGlobal)
         const_cast<QMacPasteboard *>(this)->setMimeData(0);
 #ifdef DEBUG_PASTEBOARD
     if(fromGlobal)
         qDebug("Pasteboard: Synchronize!");
 #endif
     return fromGlobal;
 }
Properties
mac_mime_source
bool QMacPasteboard::mac_mime_source mutable private
Definition at line 226 of file qt_mac_p.h.
mime
QPointer<QMimeData> QMacPasteboard::mime mutable private
Definition at line 225 of file qt_mac_p.h.
mime_type
uchar QMacPasteboard::mime_type private
Definition at line 224 of file qt_mac_p.h.
paste
OSPasteboardRef QMacPasteboard::paste private
Definition at line 223 of file qt_mac_p.h.
promises
QList<Promise> QMacPasteboard::promises private
Definition at line 221 of file qt_mac_p.h.
Referenced by promiseKeeper().
The documentation for this class was generated from the following files:
/src/gui/kernel/qt_mac_p.h
/src/gui/kernel/qclipboard_mac.cpp