Qt 4.8: QDeclarativeListViewAttached Class Reference
QDeclarativeListViewAttached Class Reference
#include <qdeclarativelistview_p.h>
Signals
void add ()
void currentItemChanged ()
void delayRemoveChanged ()
void nextSectionChanged ()
void prevSectionChanged ()
void remove ()
void sectionChanged ()
void viewChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool delayRemove () const
void emitAdd ()
void emitRemove ()
bool isCurrentItem () const
QString nextSection () const
QString prevSection () const
QDeclarativeListViewAttached (QObject *parent)
QString section () const
void setDelayRemove (bool delay)
void setIsCurrentItem (bool c)
void setNextSection (const QString &sect)
void setPrevSection (const QString &sect)
void setSection (const QString &sect)
void setView (QDeclarativeListView *view)
QDeclarativeListView * view ()
~QDeclarativeListViewAttached ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
bool delayRemove
bool isCurrentItem
bool m_delayRemove: 1
bool m_isCurrent: 1
QString m_nextSection
QString m_prevSection
QString m_section
QDeclarativeGuard< QDeclarativeListView > m_view
QString nextSection
QString previousSection
QString section
QDeclarativeListView * view
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 277 of file qdeclarativelistview_p.h.
Constructors and Destructors
QDeclarativeListViewAttached()
QDeclarativeListViewAttached::QDeclarativeListViewAttached (QObject * parent) inline
Definition at line 281 of file qdeclarativelistview_p.h.
         : QObject(parent), m_view(0), m_isCurrent(false), m_delayRemove(false) {}
~QDeclarativeListViewAttached()
QDeclarativeListViewAttached::~QDeclarativeListViewAttached () inline
Definition at line 283 of file qdeclarativelistview_p.h.
 {}
Functions
add
void QDeclarativeListViewAttached::add () signal
currentItemChanged
void QDeclarativeListViewAttached::currentItemChanged () signal
delayRemove()
bool QDeclarativeListViewAttached::delayRemove () const inline
Definition at line 331 of file qdeclarativelistview_p.h.
 { return m_delayRemove; }
delayRemoveChanged
void QDeclarativeListViewAttached::delayRemoveChanged () signal
emitAdd()
void QDeclarativeListViewAttached::emitAdd () inline
Definition at line 339 of file qdeclarativelistview_p.h.
Referenced by QDeclarativeListView::itemsInserted().
 { emit add(); }
emitRemove()
void QDeclarativeListViewAttached::emitRemove () inline
Definition at line 340 of file qdeclarativelistview_p.h.
Referenced by QDeclarativeListView::itemsRemoved().
 { emit remove(); }
isCurrentItem()
bool QDeclarativeListViewAttached::isCurrentItem () const inline
Definition at line 295 of file qdeclarativelistview_p.h.
 { return m_isCurrent; }
nextSection()
QString QDeclarativeListViewAttached::nextSection () const inline
Definition at line 313 of file qdeclarativelistview_p.h.
 { return m_nextSection; }
nextSectionChanged
void QDeclarativeListViewAttached::nextSectionChanged () signal
prevSection()
QString QDeclarativeListViewAttached::prevSection () const inline
Definition at line 304 of file qdeclarativelistview_p.h.
 { return m_prevSection; }
prevSectionChanged
void QDeclarativeListViewAttached::prevSectionChanged () signal
remove
void QDeclarativeListViewAttached::remove () signal
section()
QString QDeclarativeListViewAttached::section () const inline
Definition at line 322 of file qdeclarativelistview_p.h.
 { return m_section; }
sectionChanged
void QDeclarativeListViewAttached::sectionChanged () signal
setDelayRemove()
void QDeclarativeListViewAttached::setDelayRemove (bool delay) inline
Definition at line 332 of file qdeclarativelistview_p.h.
{
         if (m_delayRemove != delay) {
             m_delayRemove = delay;
             emit delayRemoveChanged();
         }
     }
setIsCurrentItem()
void QDeclarativeListViewAttached::setIsCurrentItem (bool c) inline
Definition at line 296 of file qdeclarativelistview_p.h.
Referenced by QDeclarativeListViewPrivate::updateCurrent().
{
         if (m_isCurrent != c) {
             m_isCurrent = c;
             emit currentItemChanged();
         }
     }
setNextSection()
void QDeclarativeListViewAttached::setNextSection (const QString & sect) inline
Definition at line 314 of file qdeclarativelistview_p.h.
Referenced by QDeclarativeListViewPrivate::updateSections().
{
         if (m_nextSection != sect) {
             m_nextSection = sect;
             emit nextSectionChanged();
         }
     }
setPrevSection()
void QDeclarativeListViewAttached::setPrevSection (const QString & sect) inline
Definition at line 305 of file qdeclarativelistview_p.h.
Referenced by QDeclarativeListViewPrivate::updateSections().
{
         if (m_prevSection != sect) {
             m_prevSection = sect;
             emit prevSectionChanged();
         }
     }
setSection()
void QDeclarativeListViewAttached::setSection (const QString & sect) inline
Definition at line 323 of file qdeclarativelistview_p.h.
Referenced by QDeclarativeListViewPrivate::updateSections().
{
         if (m_section != sect) {
             m_section = sect;
             emit sectionChanged();
         }
     }
setView()
void QDeclarativeListViewAttached::setView (QDeclarativeListView * view) inline
Definition at line 287 of file qdeclarativelistview_p.h.
Referenced by FxListItem::FxListItem().
{
         if (view != m_view) {
             m_view = view;
             emit viewChanged();
         }
     }
view()
QDeclarativeListView* QDeclarativeListViewAttached::view () inline
Definition at line 286 of file qdeclarativelistview_p.h.
 { return m_view; }
viewChanged
void QDeclarativeListViewAttached::viewChanged () signal
Properties
delayRemove
bool QDeclarativeListViewAttached::delayRemove
Definition at line 330 of file qdeclarativelistview_p.h.
Referenced by QDeclarativeListView::destroyRemoved(), QDeclarativeListView::itemsRemoved(), and QDeclarativeListViewPrivate::refill().
isCurrentItem
bool QDeclarativeListViewAttached::isCurrentItem
Definition at line 294 of file qdeclarativelistview_p.h.
m_delayRemove
bool QDeclarativeListViewAttached::m_delayRemove
Definition at line 358 of file qdeclarativelistview_p.h.
m_isCurrent
bool QDeclarativeListViewAttached::m_isCurrent
Definition at line 357 of file qdeclarativelistview_p.h.
m_nextSection
QString QDeclarativeListViewAttached::m_nextSection
Definition at line 356 of file qdeclarativelistview_p.h.
Referenced by QDeclarativeListViewPrivate::createItem().
m_prevSection
QString QDeclarativeListViewAttached::m_prevSection
Definition at line 355 of file qdeclarativelistview_p.h.
Referenced by QDeclarativeListViewPrivate::createItem(), and QDeclarativeListViewPrivate::createSection().
m_section
QString QDeclarativeListViewAttached::m_section mutable
Definition at line 354 of file qdeclarativelistview_p.h.
Referenced by QDeclarativeListViewPrivate::createItem(), and QDeclarativeListViewPrivate::createSection().
m_view
QDeclarativeGuard<QDeclarativeListView> QDeclarativeListViewAttached::m_view
Definition at line 353 of file qdeclarativelistview_p.h.
nextSection
QString QDeclarativeListViewAttached::nextSection
Definition at line 312 of file qdeclarativelistview_p.h.
previousSection
QString QDeclarativeListViewAttached::previousSection
Definition at line 303 of file qdeclarativelistview_p.h.
section
QString QDeclarativeListViewAttached::section
Definition at line 321 of file qdeclarativelistview_p.h.
Referenced by QDeclarativeListViewPrivate::sectionAt(), and QDeclarativeListViewPrivate::updateSections().
view
QDeclarativeListView* QDeclarativeListViewAttached::view
Definition at line 285 of file qdeclarativelistview_p.h.
The documentation for this class was generated from the following file:
/src/declarative/graphicsitems/qdeclarativelistview_p.h