Qt 4.8: /src/corelib/xml/qxmlstream.h File Reference
qxmlstream.h File Reference
#include <QtCore/qiodevice.h>
#include <QtCore/qstring.h>
#include <QtCore/qvector.h>
#include <QtCore/qscopedpointer.h>
Classes
class QXmlStreamAttribute
The QXmlStreamAttribute class represents a single XML attribute.
class QXmlStreamAttributes
The QXmlStreamAttributes class represents a vector of QXmlStreamAttribute.
class QXmlStreamEntityDeclaration
The QXmlStreamEntityDeclaration class represents a DTD entity declaration.
class QXmlStreamEntityResolver
The QXmlStreamEntityResolver class provides an entity resolver for a QXmlStreamReader.
class QXmlStreamNamespaceDeclaration
The QXmlStreamNamespaceDeclaration class represents a namespace declaration.
class QXmlStreamNotationDeclaration
The QXmlStreamNotationDeclaration class represents a DTD notation declaration.
class QXmlStreamReader
The QXmlStreamReader class provides a fast parser for reading well-formed XML via a simple streaming API.
class QXmlStreamStringRef
class QXmlStreamWriter
The QXmlStreamWriter class provides an XML writer with a simple streaming API.
Macros
#define Q_XMLSTREAM_EXPORT Q_CORE_EXPORT
Typedefs
typedef QVector< QXmlStreamEntityDeclaration > QXmlStreamEntityDeclarations
typedef QVector< QXmlStreamNamespaceDeclaration > QXmlStreamNamespaceDeclarations
typedef QVector< QXmlStreamNotationDeclaration > QXmlStreamNotationDeclarations
Functions
Q_DECLARE_TYPEINFO (QXmlStreamAttribute, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QXmlStreamNamespaceDeclaration, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QXmlStreamNotationDeclaration, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QXmlStreamEntityDeclaration, Q_MOVABLE_TYPE)
Macro Definition Documentation
Q_XMLSTREAM_EXPORT
#define Q_XMLSTREAM_EXPORT Q_CORE_EXPORT
Definition at line 97 of file qxmlstream.h.
Typedef Documentation
QXmlStreamEntityDeclarations
typedef QVector<QXmlStreamEntityDeclaration> QXmlStreamEntityDeclarations related
Definition at line 278 of file qxmlstream.h.
QXmlStreamNamespaceDeclarations
typedef QVector<QXmlStreamNamespaceDeclaration> QXmlStreamNamespaceDeclarations related
Definition at line 225 of file qxmlstream.h.
QXmlStreamNotationDeclarations
typedef QVector<QXmlStreamNotationDeclaration> QXmlStreamNotationDeclarations related
Definition at line 249 of file qxmlstream.h.
Function Documentation
Q_DECLARE_TYPEINFO() [1/4]
Q_DECLARE_TYPEINFO (QXmlStreamAttribute , Q_MOVABLE_TYPE)
Referenced by QXmlStreamAttribute::operator!=(), QXmlStreamNamespaceDeclaration::operator!=(), QXmlStreamNotationDeclaration::operator!=(), and QXmlStreamEntityDeclaration::operator!=().
Q_DECLARE_TYPEINFO() [2/4]
Q_DECLARE_TYPEINFO (QXmlStreamNamespaceDeclaration , Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO() [3/4]
Q_DECLARE_TYPEINFO (QXmlStreamNotationDeclaration , Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO() [4/4]
Q_DECLARE_TYPEINFO (QXmlStreamEntityDeclaration , Q_MOVABLE_TYPE)