Qt 4.8: /src/plugins/gfxdrivers/eglnullws/eglnullwsscreen.cpp File Reference
eglnullwsscreen.cpp File Reference
#include "eglnullwsscreen.h"
#include "eglnullwswindowsurface.h"
#include "eglnullwsscreenplugin.h"
#include <QHash>
#include <QDebug>
Functions
static int depthForFormat (QImage::Format format)
static const QHash< QString, QImage::Format > formatDictionary ()
static void printHelp (const QHash< QString, QImage::Format > &formatDictionary)
Function Documentation
depthForFormat()
static int depthForFormat (QImage::Format format) static
Definition at line 82 of file eglnullwsscreen.cpp.
Referenced by EGLNullWSScreen::connect().
 {
     switch (format) {
     case QImage::Format_RGB32:  return 32;
     case QImage::Format_ARGB32: return 32;
     case QImage::Format_RGB16:  return 16;
     case QImage::Format_RGB666: return 24;
     case QImage::Format_RGB555: return 16;
     case QImage::Format_RGB888: return 24;
     case QImage::Format_RGB444: return 16;
     default:
         Q_ASSERT_X(false, "EGLNullWSScreen", "Unknown format");
         return -1;
     }
 }
formatDictionary()
static const QHash<QString, QImage::Format> formatDictionary () static
Definition at line 69 of file eglnullwsscreen.cpp.
Referenced by EGLNullWSScreen::connect().
 {
     QHash<QString, QImage::Format> dictionary;
     dictionary["rgb32"]     = QImage::Format_RGB32;
     dictionary["argb32"]    = QImage::Format_ARGB32;
     dictionary["rgb16"]     = QImage::Format_RGB16;
     dictionary["rgb666"]    = QImage::Format_RGB666;
     dictionary["rgb555"]    = QImage::Format_RGB555;
     dictionary["rgb888"]    = QImage::Format_RGB888;
     dictionary["rgb444"]    = QImage::Format_RGB444;
     return dictionary;
 }
printHelp()
static void printHelp (const QHash< QString, QImage::Format > & formatDictionary) static
Definition at line 98 of file eglnullwsscreen.cpp.
Referenced by EGLNullWSScreen::connect().
 {
     QByteArray formatsBuf;
     QTextStream(&formatsBuf) << QStringList(formatDictionary.keys()).join(", ");
     qWarning(
         "%s: Valid options are:\n"
         "size=WIDTHxHEIGHT   Screen size reported by this driver\n"
         "format=FORMAT       Screen format, where FORMAT is one of the following:\n"
         "                      %s\n",
         PluginName,
         formatsBuf.constData());
 }