Qt 4.8: /src/plugins/gfxdrivers/directfb/qdirectfbscreen.cpp File Reference
qdirectfbscreen.cpp File Reference
#include "qdirectfbscreen.h"
#include "qdirectfbwindowsurface.h"
#include "qdirectfbpixmap.h"
#include "qdirectfbmouse.h"
#include "qdirectfbkeyboard.h"
#include <QtGui/qwsdisplay_qws.h>
#include <QtGui/qcolor.h>
#include <QtGui/qapplication.h>
#include <QtGui/qwindowsystem_qws.h>
#include <QtGui/private/qgraphicssystem_qws_p.h>
#include <QtGui/private/qwssignalhandler_p.h>
#include <QtCore/qvarlengtharray.h>
#include <QtCore/qvector.h>
#include <QtCore/qrect.h>
#include "qdirectfbscreen.moc"
Classes
class QDirectFBScreenCursor
class QDirectFBScreenPrivate
Functions
static void clearRect (IDirectFBSurface *surface, const QColor &color, const QRect &rect)
static QColor colorFromName (const QString &name)
static bool isFullUpdate (IDirectFBSurface *surface, const QRegion &region, const QPoint &offset)
Q_GUI_EXPORT IDirectFBSurface * qt_directfb_surface_for_widget (const QWidget *widget, QRect *rect)
Q_GUI_EXPORT IDirectFBWindow * qt_directfb_window_for_widget (const QWidget *widget)
static bool setIntOption (const QStringList &arguments, const QString &variable, int *value)
Function Documentation
clearRect()
static void clearRect (IDirectFBSurface * surface, const QColor & color, const QRect & rect) inline static
Definition at line 1635 of file qdirectfbscreen.cpp.
Referenced by QDirectFBScreen::solidFill(), and QVGPaintEngine::supportsTransformations().
 {
     Q_ASSERT(surface);
     const DFBRegion region = { rect.left(), rect.top(), rect.right(), rect.bottom() };
     // could just reinterpret_cast this to a DFBRegion
     surface->SetClip(surface, &region);
     surface->Clear(surface, color.red(), color.green(), color.blue(), color.alpha());
 }
colorFromName()
static QColor colorFromName (const QString & name) inline static
Definition at line 1064 of file qdirectfbscreen.cpp.
Referenced by QDirectFBScreen::connect().
 {
     QRegExp rx(QLatin1String("#([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])"));
     rx.setCaseSensitivity(Qt::CaseInsensitive);
     if (rx.exactMatch(name)) {
         Q_ASSERT(rx.captureCount() == 4);
         int ints[4];
         int i;
         for (i=0; i<4; ++i) {
             bool ok;
             ints[i] = rx.cap(i + 1).toUInt(&ok, 16);
             if (!ok || ints[i] > 255)
                 break;
         }
         if (i == 4)
             return QColor(ints[0], ints[1], ints[2], ints[3]);
     }
     return QColor(name);
 }
isFullUpdate()
static bool isFullUpdate (IDirectFBSurface * surface, const QRegion & region, const QPoint & offset) inline static
Definition at line 1696 of file qdirectfbscreen.cpp.
Referenced by QDirectFBScreen::flipSurface().
 {
     if (offset == QPoint(0, 0) && region.rectCount() == 1) {
     QSize size;
     surface->GetSize(surface, &size.rwidth(), &size.rheight());
     if (region.boundingRect().size() == size)
         return true;
     }
     return false;
 }
qt_directfb_surface_for_widget()
Q_GUI_EXPORT IDirectFBSurface* qt_directfb_surface_for_widget (const QWidget * widget, QRect * rect)
Definition at line 1797 of file qdirectfbscreen.cpp.
 {
     return QDirectFBScreen::instance() ? QDirectFBScreen::instance()->surfaceForWidget(widget, rect) : 0;
 }
qt_directfb_window_for_widget()
Q_GUI_EXPORT IDirectFBWindow* qt_directfb_window_for_widget (const QWidget * widget)
Definition at line 1808 of file qdirectfbscreen.cpp.
 {
     return QDirectFBScreen::instance() ? QDirectFBScreen::instance()->windowForWidget(widget) : 0;
 }
setIntOption()
static bool setIntOption (const QStringList & arguments, const QString & variable, int * value) inline static
Definition at line 1052 of file qdirectfbscreen.cpp.
Referenced by QDirectFBScreen::connect().
 {
     Q_ASSERT(value);
     QRegExp rx(QString::fromLatin1("%1=?(\\d+)").arg(variable));
     rx.setCaseSensitivity(Qt::CaseInsensitive);
     if (arguments.indexOf(rx) != -1) {
         *value = rx.cap(1).toInt();
         return true;
     }
     return false;
 }