Qt 4.8: EAGLView Class Reference
EAGLView Class Reference
#import <quikitwindow.h>
Public Functions
(void) - createFramebuffer
(void) - deleteFramebuffer
(void) - makeCurrent
(void) - presentFramebuffer
(void) - sendMouseEventForTouches:withEvent:fakeButtons:
(void) - setContext:
(void) - setWindow:
Protected Variables
GLuint mColorRenderbuffer
EAGLContext * mContext
GLuint mDepthRenderbuffer
GLuint mFramebuffer
GLint mFramebufferHeight
GLint mFramebufferWidth
QPlatformWindow * mWindow
Properties
UITextAutocapitalizationType autocapitalizationType
UITextAutocorrectionType autocorrectionType
id delegate
BOOL enablesReturnKeyAutomatically
GLint fbo
UIKeyboardAppearance keyboardAppearance
UIKeyboardType keyboardType
UIReturnKeyType returnKeyType
BOOL secureTextEntry
Detailed Description
Definition at line 54 of file quikitwindow.h.
Functions
createFramebuffer()
- (void) createFramebuffer
Definition at line 206 of file quikitwindow.mm.
 {
     if (mContext && !mFramebuffer)
     {
         [EAGLContext setCurrentContext:mContext];
         glGenFramebuffers(1, &mFramebuffer);
         glBindFramebuffer(GL_FRAMEBUFFER, mFramebuffer);
         glGenRenderbuffers(1, &mColorRenderbuffer);
         glBindRenderbuffer(GL_RENDERBUFFER, mColorRenderbuffer);
         [mContext renderbufferStorage:GL_RENDERBUFFER fromDrawable:(CAEAGLLayer *)self.layer];
         glGetRenderbufferParameteriv(GL_RENDERBUFFER, GL_RENDERBUFFER_WIDTH, &mFramebufferWidth);
         glGetRenderbufferParameteriv(GL_RENDERBUFFER, GL_RENDERBUFFER_HEIGHT, &mFramebufferHeight);
         glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_RENDERBUFFER, mColorRenderbuffer);
         glGenRenderbuffers(1, &mDepthRenderbuffer);
         glBindRenderbuffer(GL_RENDERBUFFER, mDepthRenderbuffer);
         if (stencilBits() > 0) {
             glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH24_STENCIL8_OES, mFramebufferWidth, mFramebufferHeight);
             glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT, GL_RENDERBUFFER, mDepthRenderbuffer);
         } else {
             glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT16, mFramebufferWidth, mFramebufferHeight);
         }
         glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, mDepthRenderbuffer);
         if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE)
             NSLog(@"Failed to make complete framebuffer object %x", glCheckFramebufferStatus(GL_FRAMEBUFFER));
         if (delegate && [delegate respondsToSelector:@selector(eaglView:usesFramebuffer:)]) {
             [delegate eaglView:self usesFramebuffer:mFramebuffer];
         }
     }
 }
deleteFramebuffer()
- (void) deleteFramebuffer
Definition at line 186 of file quikitwindow.mm.
Referenced by QUIKitWindow::ensureNativeWindow().
 {
     if (mContext)
     {
         [EAGLContext setCurrentContext:mContext];
         if (mFramebuffer) {
             glDeleteFramebuffers(1, &mFramebuffer);
             mFramebuffer = 0;
         }
         if (mColorRenderbuffer) {
             glDeleteRenderbuffers(1, &mColorRenderbuffer);
             mColorRenderbuffer = 0;
         }
         if (mDepthRenderbuffer) {
             glDeleteRenderbuffers(1, &mDepthRenderbuffer);
             mDepthRenderbuffer = 0;
         }
     }
 }
makeCurrent()
- (void) makeCurrent
Definition at line 239 of file quikitwindow.mm.
 {
     if (mContext)
     {
         [EAGLContext setCurrentContext:mContext];
         if (!mFramebuffer)
             [self createFramebuffer];
         glBindFramebuffer(GL_FRAMEBUFFER, mFramebuffer);
         glViewport(0, 0, mFramebufferWidth, mFramebufferHeight);
     }
 }
presentFramebuffer()
- (void) presentFramebuffer
Definition at line 177 of file quikitwindow.mm.
 {
     if (mContext) {
         [EAGLContext setCurrentContext:mContext];
         glBindRenderbuffer(GL_RENDERBUFFER, mColorRenderbuffer);
         [mContext presentRenderbuffer:GL_RENDERBUFFER];
     }
 }
sendMouseEventForTouches:withEvent:fakeButtons:()
- (void) sendMouseEventForTouches: (NSSet *) touches withEvent: (UIEvent *) event fakeButtons: (Qt::MouseButtons) buttons
Definition at line 261 of file quikitwindow.mm.
                                 :(NSSet *)touches withEvent:(UIEvent *)event fakeButtons:(Qt::MouseButtons)buttons
 {
     UITouch *touch = [touches anyObject];
     CGPoint locationInView = [touch locationInView:self];
     CGFloat scaleFactor = [self contentScaleFactor];
     QPoint p(locationInView.x * scaleFactor, locationInView.y * scaleFactor);
     // TODO handle global touch point? for status bar?
     QWindowSystemInterface::handleMouseEvent(mWindow->widget(), (ulong)(event.timestamp*1000),
         p, p, buttons);
 }
setContext:()
- (void) setContext: (EAGLContext *) newContext
Definition at line 166 of file quikitwindow.mm.
                   :(EAGLContext *)newContext
 {
     if (mContext != newContext)
     {
         [self deleteFramebuffer];
         [mContext release];
         mContext = [newContext retain];
         [EAGLContext setCurrentContext:nil];
     }
 }
setWindow:()
- (void) setWindow: (QPlatformWindow *) window
Definition at line 256 of file quikitwindow.mm.
Referenced by QUIKitWindow::ensureNativeWindow().
                  :(QPlatformWindow *)window
 {
     mWindow = window;
 }
Properties
mColorRenderbuffer
- (GLuint) mColorRenderbuffer protected
Definition at line 63 of file quikitwindow.h.
mContext
- (EAGLContext*) mContext protected
Definition at line 58 of file quikitwindow.h.
mDepthRenderbuffer
- (GLuint) mDepthRenderbuffer protected
Definition at line 63 of file quikitwindow.h.
mFramebuffer
- (GLuint) mFramebuffer protected
Definition at line 63 of file quikitwindow.h.
mFramebufferHeight
- (GLint) mFramebufferHeight protected
Definition at line 61 of file quikitwindow.h.
mFramebufferWidth
- (GLint) mFramebufferWidth protected
Definition at line 60 of file quikitwindow.h.
mWindow
- (QPlatformWindow*) mWindow protected
Definition at line 57 of file quikitwindow.h.
Property Documentation
autocapitalizationType
- (UITextAutocapitalizationType) autocapitalizationType read write nonatomic assign
Definition at line 67 of file quikitwindow.h.
autocorrectionType
- (UITextAutocorrectionType) autocorrectionType read write nonatomic assign
Definition at line 68 of file quikitwindow.h.
delegate
- (id) delegate read write nonatomic assign
Definition at line 65 of file quikitwindow.h.
Referenced by EAGLPaintDevice::EAGLPaintDevice().
enablesReturnKeyAutomatically
- (BOOL) enablesReturnKeyAutomatically read write nonatomic assign
Definition at line 69 of file quikitwindow.h.
fbo
- (GLint) fbo read atomic assign
Definition at line 84 of file quikitwindow.h.
Referenced by EAGLPaintDevice::EAGLPaintDevice().
keyboardAppearance
- (UIKeyboardAppearance) keyboardAppearance read write nonatomic assign
Definition at line 70 of file quikitwindow.h.
keyboardType
- (UIKeyboardType) keyboardType read write nonatomic assign
Definition at line 71 of file quikitwindow.h.
returnKeyType
- (UIReturnKeyType) returnKeyType read write nonatomic assign
Definition at line 72 of file quikitwindow.h.
Referenced by QUIKitSoftwareInputHandler::eventFilter().
secureTextEntry
- (BOOL) secureTextEntry read write nonatomic assign
Definition at line 73 of file quikitwindow.h.
The documentation for this class was generated from the following files:
/src/plugins/platforms/uikit/quikitwindow.h
/src/plugins/platforms/uikit/quikitwindow.mm