Qt 4.8: QKde Namespace Reference
QKde Namespace Reference
Functions
QString kdeHome ()
QPalette kdePalette ()
QString kdeStyle ()
int kdeToolBarIconSize ()
int kdeToolButtonStyle ()
Detailed Description
Warning
This function is not part of the public interface. This namespace contains helper function to help KDE integration They are only used if we detect the use of KDE and the KDE platform plugin is not found (old KDE version) Or if the detected KDE version is KDE3
Function Documentation
kdeHome()
QString QKde::kdeHome ()
Warning
This function is not part of the public interface. Gets the current KDE home path like "/home/troll/.kde"
Definition at line 59 of file qkde.cpp.
Referenced by QGuiPlatformPlugin::iconThemeSearchPaths(), kdePalette(), kdeStyle(), kdeToolBarIconSize(), kdeToolButtonStyle(), QGuiPlatformPlugin::systemIconThemeName(), and QApplicationPrivate::x11_apply_settings().
 {
     static QString kdeHomePath;
     if (kdeHomePath.isEmpty()) {
         kdeHomePath = QString::fromLocal8Bit(qgetenv("KDEHOME"));
         if (kdeHomePath.isEmpty()) {
             QDir homeDir(QDir::homePath());
             QString kdeConfDir(QLatin1String("/.kde"));
             if (4 == X11->desktopVersion && homeDir.exists(QLatin1String(".kde4")))
             kdeConfDir = QLatin1String("/.kde4");
             kdeHomePath = QDir::homePath() + kdeConfDir;
         }
     }
     return kdeHomePath;
 }
kdePalette()
QPalette QKde::kdePalette ()
Warning
This function is not part of the public interface. Returns the KDE palette
Definition at line 100 of file qkde.cpp.
Referenced by QGuiPlatformPlugin::palette().
 {
     const QSettings theKdeSettings(QKde::kdeHome() +
         QLatin1String("/share/config/kdeglobals"), QSettings::IniFormat);
     QPalette pal;
     // Setup KDE palette
     kdeColor(&pal, QPalette::Button, theKdeSettings, QLatin1String("Colors:Button/BackgroundNormal"), QLatin1String("buttonBackground"));
     kdeColor(&pal, QPalette::Window, theKdeSettings, QLatin1String("Colors:Window/BackgroundNormal"), QLatin1String("background"));
     kdeColor(&pal, QPalette::Text, theKdeSettings, QLatin1String("Colors:View/ForegroundNormal"), QLatin1String("foreground"));
     kdeColor(&pal, QPalette::WindowText, theKdeSettings, QLatin1String("Colors:Window/ForegroundNormal"), QLatin1String("windowForeground"));
     kdeColor(&pal, QPalette::Base, theKdeSettings, QLatin1String("Colors:View/BackgroundNormal"), QLatin1String("windowBackground"));
     kdeColor(&pal, QPalette::Highlight, theKdeSettings, QLatin1String("Colors:Selection/BackgroundNormal"), QLatin1String("selectBackground"));
     kdeColor(&pal, QPalette::HighlightedText, theKdeSettings, QLatin1String("Colors:Selection/ForegroundNormal"), QLatin1String("selectForeground"));
     kdeColor(&pal, QPalette::AlternateBase, theKdeSettings, QLatin1String("Colors:View/BackgroundAlternate"), QLatin1String("alternateBackground"));
     kdeColor(&pal, QPalette::ButtonText, theKdeSettings, QLatin1String("Colors:Button/ForegroundNormal"), QLatin1String("buttonForeground"));
     kdeColor(&pal, QPalette::Link, theKdeSettings, QLatin1String("Colors:View/ForegroundLink"), QLatin1String("linkColor"));
     kdeColor(&pal, QPalette::LinkVisited, theKdeSettings, QLatin1String("Colors:View/ForegroundVisited"), QLatin1String("visitedLinkColor"));
    //## TODO tooltip color
     return pal;
 }
kdeStyle()
QString QKde::kdeStyle ()
Warning
This function is not part of the public interface. Returns the name of the QStyle to use. (read from the kde config if needed)
Definition at line 127 of file qkde.cpp.
Referenced by QGuiPlatformPlugin::styleName().
 {
     if (X11->desktopVersion >= 4) {
         QSettings kdeSettings(QKde::kdeHome() + QLatin1String("/share/config/kdeglobals"), QSettings::IniFormat);
         QString style = kdeSettings.value(QLatin1String("widgetStyle"), QLatin1String("Oxygen")).toString();
         QStringList availableStyles = QStyleFactory::keys();
         if(availableStyles.contains(style, Qt::CaseInsensitive))
             return style;
     }
     if (X11->use_xrender)
         return QLatin1String("plastique");
     else
         return QLatin1String("windows");
 }
kdeToolBarIconSize()
int QKde::kdeToolBarIconSize ()
Definition at line 161 of file qkde.cpp.
Referenced by QGuiPlatformPlugin::platformHint().
 {
     static int iconSize = -1;
     if (iconSize == -1) {
         QSettings settings(QKde::kdeHome() + QLatin1String("/share/config/kdeglobals"),
                             QSettings::IniFormat);
                             settings.beginGroup(QLatin1String("ToolbarIcons"));
         iconSize = settings.value(QLatin1String("Size")).toInt();
     }
     return iconSize;
 }
kdeToolButtonStyle()
int QKde::kdeToolButtonStyle ()
Definition at line 145 of file qkde.cpp.
Referenced by QGuiPlatformPlugin::platformHint().
 {
     QSettings settings(QKde::kdeHome() + QLatin1String("/share/config/kdeglobals"),
                         QSettings::IniFormat);
     settings.beginGroup(QLatin1String("Toolbar style"));
     QString toolbarStyle = settings.value(QLatin1String("ToolButtonStyle"), QLatin1String("TextBesideIcon")).toString();
     if (toolbarStyle == QLatin1String("TextBesideIcon"))
         return Qt::ToolButtonTextBesideIcon;
     else if (toolbarStyle == QLatin1String("TextOnly"))
         return Qt::ToolButtonTextOnly;
     else if (toolbarStyle == QLatin1String("TextUnderIcon"))
         return Qt::ToolButtonTextUnderIcon;
     return Qt::ToolButtonTextBesideIcon;
 }