Qt 4.8: QScript Namespace Reference
QScript Namespace Reference
Namespaces
AST
Classes
class APIShim
class ClassObjectDelegate
class DeclarativeObjectDelegate
class FunctionWithArgWrapper
class FunctionWrapper
struct GlobalClientData
class GlobalObject
class Lexer
class OriginalGlobalObjectProxy
class QMetaObjectPrototype
class QMetaObjectWrapperObject
struct QObjectConnection
class QObjectConnectionManager
class QObjectData
class QObjectDelegate
class QObjectNotifyCaller
class QObjectPrototype
class QObjectPrototypeObject
struct QObjectWrapperInfo
class QScriptActivationObject
Represent a scope for native function call.
struct QScriptMetaArguments
class QScriptMetaMethod
class QScriptMetaType
class QtFunction
class QtPropertyFunction
class QVariantDelegate
class QVariantPrototype
class SaveFrameHelper
struct StaticQtMetaObject
class SyntaxChecker
class TimeoutCheckerProxy
class UStringSourceProviderWithFeedback
Enumerations
enum AttributeExtension { QObjectMemberAttribute = 1 << 12 }
enum Type {
Undefined, Null, Boolean, String,
Number, Object
}
Functions
static QScriptValue __setupPackage__ (QScriptContext *ctx, QScriptEngine *eng)
static JSC::JSValue callQtMethod (JSC::ExecState *exec, QMetaMethod::MethodType callType, QObject *thisQObject, const JSC::ArgList &scriptArgs, const QMetaObject *meta, int initialIndex, bool maybeOverloaded)
QByteArray convertToLatin1 (const JSC::UString &str)
void convertToLatin1_helper (const UChar *i, int length, char *s)
qsreal DateTimeToMs (JSC::ExecState *exec, const QDateTime &dt)
Converts a QDateTime to a JS date value (milliseconds).
static bool Equals (QScriptValue lhs, QScriptValue rhs)
static unsigned flagsForMetaProperty (const QMetaProperty &prop)
static JSC::JSValue JSC_HOST_CALL functionConnect (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSValue JSC_HOST_CALL functionDisconnect (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSValue JSC_HOST_CALL functionGC (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSValue JSC_HOST_CALL functionPrint (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSValue JSC_HOST_CALL functionQsTr (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSValue JSC_HOST_CALL functionQsTranslate (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSValue JSC_HOST_CALL functionQsTranslateNoOp (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSValue JSC_HOST_CALL functionQsTrId (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSValue JSC_HOST_CALL functionQsTrIdNoOp (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSValue JSC_HOST_CALL functionQsTrNoOp (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSValue JSC_HOST_CALL functionVersion (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static bool hasMethodAccess (const QMetaMethod &method, int index, const QScriptEngine::QObjectWrapOptions &opt)
static int indexOfMetaEnum (const QMetaObject *meta, const QByteArray &str)
qsreal integerFromString (const char *buf, int size, int radix)
qsreal integerFromString (const QString &str, int radix)
static bool isEnumerableMetaProperty (const QMetaProperty &prop, const QMetaObject *mo, int index)
bool isFunction (JSC::JSValue value)
static bool IsNumerical (const QScriptValue &value)
static bool LessThan (QScriptValue lhs, QScriptValue rhs)
static QMetaMethod metaMethod (const QMetaObject *meta, QMetaMethod::MethodType type, int index)
static QByteArray methodName (const char *signature, int nameLength)
Makes a deep copy of the first nameLength characters of the given method signature and returns the copy.
static bool methodNameEquals (const QMetaMethod &method, const char *signature, int nameLength)
Returns true if the name of the given method is the same as that specified by the (signature, nameLength) pair, otherwise returns false.
static int methodNameLength (const QMetaMethod &method)
Calculates the length of the name of the given method by looking for the first '(' character.
static int MsFromTime (qsreal t)
QDateTime MsToDateTime (JSC::ExecState *exec, qsreal t)
Converts a JS date value (milliseconds) to a QDateTime (local time).
static JSC::JSValue JSC_HOST_CALL qmetaobjectProtoFuncClassName (JSC::ExecState *exec, JSC::JSObject *, JSC::JSValue thisValue, const JSC::ArgList &)
static JSC::JSValue JSC_HOST_CALL qobjectProtoFuncFindChild (JSC::ExecState *exec, JSC::JSObject *, JSC::JSValue thisValue, const JSC::ArgList &args)
static JSC::JSValue JSC_HOST_CALL qobjectProtoFuncFindChildren (JSC::ExecState *exec, JSC::JSObject *, JSC::JSValue thisValue, const JSC::ArgList &args)
static JSC::JSValue JSC_HOST_CALL qobjectProtoFuncToString (JSC::ExecState *exec, JSC::JSObject *, JSC::JSValue thisValue, const JSC::ArgList &)
static QScriptable * scriptableFromQObject (QObject *qobj)
QScriptEnginePrivate * scriptEngineFromExec (const JSC::ExecState *exec)
static JSC::JSValue JSC_HOST_CALL stringProtoFuncArg (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
bool ToBool (qsreal)
bool ToBool (const QString &)
static int toDigit (char c)
qint32 ToInt32 (const QString &)
qint32 ToInt32 (qsreal n)
qsreal ToInteger (const QString &)
qsreal ToInteger (qsreal n)
qsreal ToNumber (const QString &)
static QScriptValue ToPrimitive (const QScriptValue &object, JSC::PreferredPrimitiveType hint=JSC::NoPreference)
QString ToString (qsreal)
quint16 ToUInt16 (const QString &)
quint16 ToUInt16 (qsreal n)
quint32 ToUInt32 (const QString &)
quint32 ToUInt32 (qsreal n)
static Type type (const QScriptValue &v)
static QVariant variantFromValue (JSC::ExecState *exec, int targetType, JSC::JSValue value)
static JSC::JSValue JSC_HOST_CALL variantProtoFuncToString (JSC::ExecState *exec, JSC::JSObject *callee, JSC::JSValue thisValue, const JSC::ArgList &args)
static JSC::JSValue JSC_HOST_CALL variantProtoFuncValueOf (JSC::ExecState *exec, JSC::JSObject *, JSC::JSValue thisValue, const JSC::ArgList &)
Variables
static const qsreal D32 = 4294967296.0
static const bool GeneratePropertyFunctions = true
static const qsreal MsPerSecond = 1000.0
static const uint qt_meta_data_QObjectConnectionManager []
static const char qt_meta_stringdata_QObjectConnectionManager []
Enumeration Type Documentation
AttributeExtension
enum QScript::AttributeExtension
Enumerator
QObjectMemberAttribute
Definition at line 50 of file qscriptqobject_p.h.
{
     // ### Make sure there's no conflict with JSC::Attribute
     QObjectMemberAttribute = 1 << 12
 };
Type
enum QScript::Type
Enumerator
Undefined
Null
Boolean
String
Number
Object
Definition at line 686 of file qscriptvalue.cpp.
           {
     Undefined,
     Null,
     Boolean,
     String,
     Number,
     Object
 };
Function Documentation
__setupPackage__()
static QScriptValue QScript::__setupPackage__ (QScriptContext * ctx, QScriptEngine * eng) static
Definition at line 955 of file qscriptengine.cpp.
Referenced by QScriptEngine::importExtension().
 {
     QString path = ctx->argument(0).toString();
     QStringList components = path.split(QLatin1Char('.'));
     QScriptValue o = eng->globalObject();
     for (int i = 0; i < components.count(); ++i) {
         QString name = components.at(i);
         QScriptValue oo = o.property(name);
         if (!oo.isValid()) {
             oo = eng->newObject();
             o.setProperty(name, oo);
         }
         o = oo;
     }
     return o;
 }
callQtMethod()
static JSC::JSValue QScript::callQtMethod (JSC::ExecState * exec, QMetaMethod::MethodType callType, QObject * thisQObject, const JSC::ArgList & scriptArgs, const QMetaObject * meta, int initialIndex, bool maybeOverloaded) static
Definition at line 523 of file qscriptqobject.cpp.
Referenced by QScript::QtFunction::execute(), and QScript::QMetaObjectWrapperObject::execute().
 {
     QScriptMetaMethod chosenMethod;
     int chosenIndex = -1;
     QVarLengthArray<QVariant, 9> args;
     QVector<QScriptMetaArguments> candidates;
     QVector<QScriptMetaArguments> unresolved;
     QVector<int> tooFewArgs;
     QVector<int> conversionFailed;
     int index;
     int nameLength = 0;
     const char *initialMethodSignature = 0;
     exec->clearException();
     QScriptEnginePrivate *engine = QScript::scriptEngineFromExec(exec);
     for (index = initialIndex; index >= 0; --index) {
         QMetaMethod method = metaMethod(meta, callType, index);
         if (index == initialIndex) {
             initialMethodSignature = method.signature();
             nameLength = methodNameLength(method);
         } else {
             if (!methodNameEquals(method, initialMethodSignature, nameLength))
                 continue;
         }
         QList<QByteArray> parameterTypeNames = method.parameterTypes();
         QVector<QScriptMetaType> types;
         types.resize(1 + parameterTypeNames.size());
         QScriptMetaType *typesData = types.data();
         // resolve return type
         QByteArray returnTypeName = method.typeName();
         int rtype = QMetaType::type(returnTypeName);
         if ((rtype == 0) && !returnTypeName.isEmpty()) {
             int enumIndex = indexOfMetaEnum(meta, returnTypeName);
             if (enumIndex != -1)
                 typesData[0] = QScriptMetaType::metaEnum(enumIndex, returnTypeName);
             else
                 typesData[0] = QScriptMetaType::unresolved(returnTypeName);
         } else {
             if (callType == QMetaMethod::Constructor)
                 typesData[0] = QScriptMetaType::metaType(QMetaType::QObjectStar, "QObject*");
             else if (rtype == QMetaType::QVariant)
                 typesData[0] = QScriptMetaType::variant();
             else
                 typesData[0] = QScriptMetaType::metaType(rtype, returnTypeName);
         }
         // resolve argument types
         for (int i = 0; i < parameterTypeNames.count(); ++i) {
             QByteArray argTypeName = parameterTypeNames.at(i);
             int atype = QMetaType::type(argTypeName);
             if (atype == 0) {
                 int enumIndex = indexOfMetaEnum(meta, argTypeName);
                 if (enumIndex != -1)
                     typesData[1 + i] = QScriptMetaType::metaEnum(enumIndex, argTypeName);
                 else
                     typesData[1 + i] = QScriptMetaType::unresolved(argTypeName);
             } else if (atype == QMetaType::QVariant) {
                 typesData[1 + i] = QScriptMetaType::variant();
             } else {
                 typesData[1 + i] = QScriptMetaType::metaType(atype, argTypeName);
             }
         }
         QScriptMetaMethod mtd = QScriptMetaMethod(types);
         if (int(scriptArgs.size()) < mtd.argumentCount()) {
             tooFewArgs.append(index);
             continue;
         }
         if (!mtd.fullyResolved()) {
             // remember it so we can give an error message later, if necessary
             unresolved.append(QScriptMetaArguments(/*matchDistance=*/INT_MAX, index,
                                                    mtd, QVarLengthArray<QVariant, 9>()));
             if (mtd.hasUnresolvedReturnType())
                 continue;
         }
         if (args.count() != mtd.count())
             args.resize(mtd.count());
         QScriptMetaType retType = mtd.returnType();
         args[0] = QVariant(retType.typeId(), (void *)0); // the result
         // try to convert arguments
         bool converted = true;
         int matchDistance = 0;
         for (int i = 0; converted && i < mtd.argumentCount(); ++i) {
             JSC::JSValue actual;
             if (i < (int)scriptArgs.size())
                 actual = scriptArgs.at(i);
             else
                 actual = JSC::jsUndefined();
             QScriptMetaType argType = mtd.argumentType(i);
             int tid = -1;
             QVariant v;
             if (argType.isUnresolved()) {
                 v = QVariant(QMetaType::QObjectStar, (void *)0);
                 converted = QScriptEnginePrivate::convertToNativeQObject(
                     exec, actual, argType.name(), reinterpret_cast<void* *>(v.data()));
             } else if (argType.isVariant()) {
                 if (QScriptEnginePrivate::isVariant(actual)) {
                     v = QScriptEnginePrivate::variantValue(actual);
                 } else {
                     v = QScriptEnginePrivate::toVariant(exec, actual);
                     converted = v.isValid() || actual.isUndefined() || actual.isNull();
                 }
             } else {
                 tid = argType.typeId();
                 v = QVariant(tid, (void *)0);
                 converted = QScriptEnginePrivate::convertValue(exec, actual, tid, v.data());
                 if (exec->hadException())
                     return exec->exception();
             }
             if (!converted) {
                 if (QScriptEnginePrivate::isVariant(actual)) {
                     if (tid == -1)
                         tid = argType.typeId();
                     QVariant vv = QScriptEnginePrivate::variantValue(actual);
                     if (vv.canConvert(QVariant::Type(tid))) {
                         v = vv;
                         converted = v.convert(QVariant::Type(tid));
                         if (converted && (vv.userType() != tid))
                             matchDistance += 10;
                     } else {
                         QByteArray vvTypeName = vv.typeName();
                         if (vvTypeName.endsWith('*')
                             && (vvTypeName.left(vvTypeName.size()-1) == argType.name())) {
                             v = QVariant(tid, *reinterpret_cast<void* *>(vv.data()));
                             converted = true;
                             matchDistance += 10;
                         }
                     }
                 } else if (actual.isNumber() || actual.isString()) {
                     // see if it's an enum value
                     QMetaEnum m;
                     if (argType.isMetaEnum()) {
                         m = meta->enumerator(argType.enumeratorIndex());
                     } else {
                         int mi = indexOfMetaEnum(meta, argType.name());
                         if (mi != -1)
                             m = meta->enumerator(mi);
                     }
                     if (m.isValid()) {
                         if (actual.isNumber()) {
                             int ival = QScriptEnginePrivate::toInt32(exec, actual);
                             if (m.valueToKey(ival) != 0) {
                                 v.setValue(ival);
                                 converted = true;
                                 matchDistance += 10;
                             }
                         } else {
                             JSC::UString sval = QScriptEnginePrivate::toString(exec, actual);
                             int ival = m.keyToValue(convertToLatin1(sval));
                             if (ival != -1) {
                                 v.setValue(ival);
                                 converted = true;
                                 matchDistance += 10;
                             }
                         }
                     }
                 }
             } else {
                 // determine how well the conversion matched
                 if (actual.isNumber()) {
                     switch (tid) {
                     case QMetaType::Double:
                         // perfect
                         break;
                     case QMetaType::Float:
                         matchDistance += 1;
                         break;
                     case QMetaType::LongLong:
                     case QMetaType::ULongLong:
                         matchDistance += 2;
                         break;
                     case QMetaType::Long:
                     case QMetaType::ULong:
                         matchDistance += 3;
                         break;
                     case QMetaType::Int:
                     case QMetaType::UInt:
                         matchDistance += 4;
                         break;
                     case QMetaType::Short:
                     case QMetaType::UShort:
                         matchDistance += 5;
                         break;
                     case QMetaType::Char:
                     case QMetaType::UChar:
                         matchDistance += 6;
                         break;
                     default:
                         matchDistance += 10;
                         break;
                     }
                 } else if (actual.isString()) {
                     switch (tid) {
                     case QMetaType::QString:
                         // perfect
                         break;
                     default:
                         matchDistance += 10;
                         break;
                     }
                 } else if (actual.isBoolean()) {
                     switch (tid) {
                     case QMetaType::Bool:
                         // perfect
                         break;
                     default:
                         matchDistance += 10;
                         break;
                     }
                 } else if (QScriptEnginePrivate::isDate(actual)) {
                     switch (tid) {
                     case QMetaType::QDateTime:
                         // perfect
                         break;
                     case QMetaType::QDate:
                         matchDistance += 1;
                         break;
                     case QMetaType::QTime:
                         matchDistance += 2;
                         break;
                     default:
                         matchDistance += 10;
                         break;
                     }
                 } else if (QScriptEnginePrivate::isRegExp(actual)) {
                     switch (tid) {
                     case QMetaType::QRegExp:
                         // perfect
                         break;
                     default:
                         matchDistance += 10;
                         break;
                     }
                 } else if (QScriptEnginePrivate::isVariant(actual)) {
                     if (argType.isVariant()
                         || (QScriptEnginePrivate::toVariant(exec, actual).userType() == tid)) {
                         // perfect
                     } else {
                         matchDistance += 10;
                     }
                 } else if (QScriptEnginePrivate::isArray(actual)) {
                     switch (tid) {
                     case QMetaType::QStringList:
                     case QMetaType::QVariantList:
                         matchDistance += 5;
                         break;
                     default:
                         matchDistance += 10;
                         break;
                     }
                 } else if (QScriptEnginePrivate::isQObject(actual)) {
                     switch (tid) {
                     case QMetaType::QObjectStar:
                     case QMetaType::QWidgetStar:
                         // perfect
                         break;
                     default:
                         matchDistance += 10;
                         break;
                     }
                 } else if (actual.isNull()) {
                     switch (tid) {
                     case QMetaType::VoidStar:
                     case QMetaType::QObjectStar:
                     case QMetaType::QWidgetStar:
                         // perfect
                         break;
                     default:
                         if (!argType.name().endsWith('*'))
                             matchDistance += 10;
                         break;
                     }
                 } else {
                     matchDistance += 10;
                 }
             }
             if (converted)
                 args[i+1] = v;
         }
         if (converted) {
             if ((scriptArgs.size() == (size_t)mtd.argumentCount())
                 && (matchDistance == 0)) {
                 // perfect match, use this one
                 chosenMethod = mtd;
                 chosenIndex = index;
                 break;
             } else {
                 bool redundant = false;
                 if ((callType != QMetaMethod::Constructor)
                     && (index < meta->methodOffset())) {
                     // it is possible that a virtual method is redeclared in a subclass,
                     // in which case we want to ignore the superclass declaration
                     for (int i = 0; i < candidates.size(); ++i) {
                         const QScriptMetaArguments &other = candidates.at(i);
                         if (mtd.types() == other.method.types()) {
                             redundant = true;
                             break;
                         }
                     }
                 }
                 if (!redundant) {
                     QScriptMetaArguments metaArgs(matchDistance, index, mtd, args);
                     if (candidates.isEmpty()) {
                         candidates.append(metaArgs);
                     } else {
                         const QScriptMetaArguments &otherArgs = candidates.at(0);
                         if ((args.count() > otherArgs.args.count())
                             || ((args.count() == otherArgs.args.count())
                                 && (matchDistance <= otherArgs.matchDistance))) {
                             candidates.prepend(metaArgs);
                         } else {
                             candidates.append(metaArgs);
                         }
                     }
                 }
             }
         } else if (mtd.fullyResolved()) {
             conversionFailed.append(index);
         }
         if (!maybeOverloaded)
             break;
     }
     JSC::JSValue result;
     if ((chosenIndex == -1) && candidates.isEmpty()) {
 //        context->calleeMetaIndex = initialIndex;
 //#ifndef Q_SCRIPT_NO_EVENT_NOTIFY
 //        engine->notifyFunctionEntry(context);
 //#endif
         QString funName = QString::fromLatin1(methodName(initialMethodSignature, nameLength));
         if (!conversionFailed.isEmpty()) {
             QString message = QString::fromLatin1("incompatible type of argument(s) in call to %0(); candidates were\n")
                               .arg(funName);
             for (int i = 0; i < conversionFailed.size(); ++i) {
                 if (i > 0)
                     message += QLatin1String("\n");
                 QMetaMethod mtd = metaMethod(meta, callType, conversionFailed.at(i));
                 message += QString::fromLatin1("    %0").arg(QString::fromLatin1(mtd.signature()));
             }
             result = JSC::throwError(exec, JSC::TypeError, message);
         } else if (!unresolved.isEmpty()) {
             QScriptMetaArguments argsInstance = unresolved.first();
             int unresolvedIndex = argsInstance.method.firstUnresolvedIndex();
             Q_ASSERT(unresolvedIndex != -1);
             QScriptMetaType unresolvedType = argsInstance.method.type(unresolvedIndex);
             QString unresolvedTypeName = QString::fromLatin1(unresolvedType.name());
             QString message = QString::fromLatin1("cannot call %0(): ")
                               .arg(funName);
             if (unresolvedIndex > 0) {
                 message.append(QString::fromLatin1("argument %0 has unknown type `%1'").
                                arg(unresolvedIndex).arg(unresolvedTypeName));
             } else {
                 message.append(QString::fromLatin1("unknown return type `%0'")
                                .arg(unresolvedTypeName));
             }
             message.append(QString::fromLatin1(" (register the type with qScriptRegisterMetaType())"));
             result = JSC::throwError(exec, JSC::TypeError, message);
         } else {
             QString message = QString::fromLatin1("too few arguments in call to %0(); candidates are\n")
                               .arg(funName);
             for (int i = 0; i < tooFewArgs.size(); ++i) {
                 if (i > 0)
                     message += QLatin1String("\n");
                 QMetaMethod mtd = metaMethod(meta, callType, tooFewArgs.at(i));
                 message += QString::fromLatin1("    %0").arg(QString::fromLatin1(mtd.signature()));
             }
             result = JSC::throwError(exec, JSC::SyntaxError, message);
         }
     } else {
         if (chosenIndex == -1) {
             QScriptMetaArguments metaArgs = candidates.at(0);
             if ((candidates.size() > 1)
                 && (metaArgs.args.count() == candidates.at(1).args.count())
                 && (metaArgs.matchDistance == candidates.at(1).matchDistance)) {
                 // ambiguous call
                 QByteArray funName = methodName(initialMethodSignature, nameLength);
                 QString message = QString::fromLatin1("ambiguous call of overloaded function %0(); candidates were\n")
                                   .arg(QLatin1String(funName));
                 for (int i = 0; i < candidates.size(); ++i) {
                     if (i > 0)
                         message += QLatin1String("\n");
                     QMetaMethod mtd = metaMethod(meta, callType, candidates.at(i).index);
                     message += QString::fromLatin1("    %0").arg(QString::fromLatin1(mtd.signature()));
                 }
                 result = JSC::throwError(exec, JSC::TypeError, message);
             } else {
                 chosenMethod = metaArgs.method;
                 chosenIndex = metaArgs.index;
                 args = metaArgs.args;
             }
         }
         if (chosenIndex != -1) {
             // call it
 //            context->calleeMetaIndex = chosenIndex;
             QVarLengthArray<void*, 9> array(args.count());
             void **params = array.data();
             for (int i = 0; i < args.count(); ++i) {
                 const QVariant &v = args[i];
                 switch (chosenMethod.type(i).kind()) {
                 case QScriptMetaType::Variant:
                     params[i] = const_cast<QVariant*>(&v);
                     break;
                 case QScriptMetaType::MetaType:
                 case QScriptMetaType::MetaEnum:
                 case QScriptMetaType::Unresolved:
                     params[i] = const_cast<void*>(v.constData());
                     break;
                 default:
                     Q_ASSERT(0);
                 }
             }
             QScriptable *scriptable = 0;
             if (thisQObject)
                 scriptable = scriptableFromQObject(thisQObject);
             QScriptEngine *oldEngine = 0;
             if (scriptable) {
                 oldEngine = QScriptablePrivate::get(scriptable)->engine;
                 QScriptablePrivate::get(scriptable)->engine = QScriptEnginePrivate::get(engine);
             }
 // ### fixme
 //#ifndef Q_SCRIPT_NO_EVENT_NOTIFY
 //            engine->notifyFunctionEntry(context);
 //#endif
             if (callType == QMetaMethod::Constructor) {
                 Q_ASSERT(meta != 0);
                 meta->static_metacall(QMetaObject::CreateInstance, chosenIndex, params);
             } else {
                 QMetaObject::metacall(thisQObject, QMetaObject::InvokeMetaMethod, chosenIndex, params);
             }
             if (scriptable)
                 QScriptablePrivate::get(scriptable)->engine = oldEngine;
             if (exec->hadException()) {
                 result = exec->exception() ; // propagate
             } else {
                 QScriptMetaType retType = chosenMethod.returnType();
                 if (retType.isVariant()) {
                     result = QScriptEnginePrivate::jscValueFromVariant(exec, *(QVariant *)params[0]);
                 } else if (retType.typeId() != 0) {
                     result = QScriptEnginePrivate::create(exec, retType.typeId(), params[0]);
                     if (!result)
                         result = engine->newVariant(QVariant(retType.typeId(), params[0]));
                 } else {
                     result = JSC::jsUndefined();
                 }
             }
         }
     }
     return result;
 }
convertToLatin1()
QByteArray QScript::convertToLatin1 (const JSC::UString & str) inline
Definition at line 570 of file qscriptengine_p.h.
Referenced by callQtMethod(), QAbstractConcatenable::convertToAscii(), QScript::QObjectDelegate::deleteProperty(), QScript::QMetaObjectWrapperObject::deleteProperty(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertySlot(), QScript::QMetaObjectWrapperObject::getOwnPropertySlot(), QScript::QObjectDelegate::put(), and QScript::QMetaObjectWrapperObject::put().
 {
     QByteArray ba(str.size(), Qt::Uninitialized);
     convertToLatin1_helper(str.data(), str.size(), ba.data());
     return ba;
 }
convertToLatin1_helper()
void QScript::convertToLatin1_helper (const UChar * i, int length, char * s) inline
Definition at line 562 of file qscriptengine_p.h.
Referenced by convertToLatin1().
 {
     const UChar *e = i + length;
     while (i != e)
         *(s++) = (uchar) *(i++);
     *s = '\0';
 }
DateTimeToMs()
qsreal QScript::DateTimeToMs (JSC::ExecState * exec, const QDateTime & dt)
Converts a QDateTime to a JS date value (milliseconds).
Warning
This function is not part of the public interface.
Definition at line 483 of file qscriptengine.cpp.
Referenced by QScriptEnginePrivate::newDate().
 {
     if (!dt.isValid())
         return qSNaN();
     QDateTime utc = dt.toUTC();
     QDate date = utc.date();
     QTime time = utc.time();
     JSC::GregorianDateTime tm;
     tm.year = date.year() - 1900;
     tm.month = date.month() - 1;
     tm.monthDay = date.day();
     tm.weekDay = date.dayOfWeek();
     tm.yearDay = date.dayOfYear();
     tm.hour = time.hour();
     tm.minute = time.minute();
     tm.second = time.second();
     return JSC::gregorianDateTimeToMS(exec, tm, time.msec(), /*inputIsUTC=*/true);
 }
Equals()
static bool QScript::Equals (QScriptValue lhs, QScriptValue rhs) static
Definition at line 764 of file qscriptvalue.cpp.
Referenced by QScriptValue::equals().
 {
     if (type(lhs) == type(rhs)) {
         switch (type(lhs)) {
         case QScript::Undefined:
         case QScript::Null:
             return true;
         case QScript::Number:
             return lhs.toNumber() == rhs.toNumber();
         case QScript::Boolean:
             return lhs.toBool() == rhs.toBool();
         case QScript::String:
             return lhs.toString() == rhs.toString();
         case QScript::Object:
             if (lhs.isVariant())
                 return lhs.strictlyEquals(rhs) || (lhs.toVariant() == rhs.toVariant());
 #ifndef QT_NO_QOBJECT
             else if (lhs.isQObject())
                 return (lhs.strictlyEquals(rhs)) || (lhs.toQObject() == rhs.toQObject());
 #endif
             else
                 return lhs.strictlyEquals(rhs);
         }
     }
     if (lhs.isNull() && rhs.isUndefined())
         return true;
     else if (lhs.isUndefined() && rhs.isNull())
         return true;
     else if (IsNumerical(lhs) && rhs.isString())
         return lhs.toNumber() == rhs.toNumber();
     else if (lhs.isString() && IsNumerical(rhs))
         return lhs.toNumber() == rhs.toNumber();
     else if (lhs.isBool())
         return Equals(lhs.toNumber(), rhs);
     else if (rhs.isBool())
         return Equals(lhs, rhs.toNumber());
     else if (lhs.isObject() && !rhs.isNull()) {
         lhs = ToPrimitive(lhs);
         if (lhs.isValid() && !lhs.isObject())
             return Equals(lhs, rhs);
     }
     else if (rhs.isObject() && ! lhs.isNull()) {
         rhs = ToPrimitive(rhs);
         if (rhs.isValid() && !rhs.isObject())
             return Equals(lhs, rhs);
     }
     return false;
 }
flagsForMetaProperty()
static unsigned QScript::flagsForMetaProperty (const QMetaProperty & prop) static
Definition at line 238 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::getOwnPropertyDescriptor().
 {
     return (JSC::DontDelete
             | (!prop.isWritable() ? unsigned(JSC::ReadOnly) : unsigned(0))
             | (GeneratePropertyFunctions
                ? unsigned(JSC::Getter | JSC::Setter)
                   : unsigned(0))
             | QObjectMemberAttribute);
 }
functionConnect()
JSC::JSValue JSC_HOST_CALL QScript::functionConnect (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue thisObject, const JSC::ArgList & args) static
Definition at line 681 of file qscriptengine.cpp.
Referenced by isFunction(), and QScriptEnginePrivate::QScriptEnginePrivate().
 {
 #ifndef QT_NO_QOBJECT
     if (args.size() == 0) {
         return JSC::throwError(exec, JSC::GeneralError,"Function.prototype.connect: no arguments given");
     }
     if (!JSC::asObject(thisObject)->inherits(&QScript::QtFunction::info)) {
         return JSC::throwError(exec, JSC::TypeError, "Function.prototype.connect: this object is not a signal");
     }
     QScript::QtFunction *qtSignal = static_cast<QScript::QtFunction*>(JSC::asObject(thisObject));
     const QMetaObject *meta = qtSignal->metaObject();
     if (!meta) {
         return JSC::throwError(exec, JSC::TypeError, "Function.prototype.connect: cannot connect to deleted QObject");
     }
     QMetaMethod sig = meta->method(qtSignal->initialIndex());
     if (sig.methodType() != QMetaMethod::Signal) {
         QString message = QString::fromLatin1("Function.prototype.connect: %0::%1 is not a signal")
                           .arg(QLatin1String(qtSignal->metaObject()->className()))
                           .arg(QLatin1String(sig.signature()));
         return JSC::throwError(exec, JSC::TypeError, message);
     }
     {
         QList<int> overloads = qtSignal->overloadedIndexes();
         if (!overloads.isEmpty()) {
             overloads.append(qtSignal->initialIndex());
             QByteArray signature = sig.signature();
             QString message = QString::fromLatin1("Function.prototype.connect: ambiguous connect to %0::%1(); candidates are\n")
                               .arg(QLatin1String(qtSignal->metaObject()->className()))
                               .arg(QLatin1String(signature.left(signature.indexOf('('))));
             for (int i = 0; i < overloads.size(); ++i) {
                 QMetaMethod mtd = meta->method(overloads.at(i));
                 message.append(QString::fromLatin1("    %0\n").arg(QString::fromLatin1(mtd.signature())));
             }
             message.append(QString::fromLatin1("Use e.g. object['%0'].connect() to connect to a particular overload")
                            .arg(QLatin1String(signature)));
             return JSC::throwError(exec, JSC::GeneralError, message);
         }
     }
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     JSC::JSValue receiver;
     JSC::JSValue slot;
     JSC::JSValue arg0 = args.at(0);
     if (args.size() < 2) {
         slot = arg0;
     } else {
         receiver = arg0;
         JSC::JSValue arg1 = args.at(1);
         if (isFunction(arg1))
             slot = arg1;
         else {
             QScript::SaveFrameHelper saveFrame(engine, exec);
             JSC::UString propertyName = QScriptEnginePrivate::toString(exec, arg1);
             slot = QScriptEnginePrivate::property(exec, arg0, propertyName, QScriptValue::ResolvePrototype);
         }
     }
     if (!isFunction(slot)) {
         return JSC::throwError(exec, JSC::TypeError, "Function.prototype.connect: target is not a function");
     }
     bool ok = engine->scriptConnect(thisObject, receiver, slot, Qt::AutoConnection);
     if (!ok) {
         QString message = QString::fromLatin1("Function.prototype.connect: failed to connect to %0::%1")
                           .arg(QLatin1String(qtSignal->metaObject()->className()))
                           .arg(QLatin1String(sig.signature()));
         return JSC::throwError(exec, JSC::GeneralError, message);
     }
     return JSC::jsUndefined();
 #else
     Q_UNUSED(eng);
     Q_UNUSED(classInfo);
     return context->throwError(QScriptContext::TypeError,
                                QLatin1String("Function.prototype.connect"));
 #endif // QT_NO_QOBJECT
 }
functionDisconnect()
JSC::JSValue JSC_HOST_CALL QScript::functionDisconnect (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue thisObject, const JSC::ArgList & args) static
Definition at line 617 of file qscriptengine.cpp.
Referenced by isFunction(), and QScriptEnginePrivate::QScriptEnginePrivate().
 {
 #ifndef QT_NO_QOBJECT
     if (args.size() == 0) {
         return JSC::throwError(exec, JSC::GeneralError, "Function.prototype.disconnect: no arguments given");
     }
     if (!JSC::asObject(thisObject)->inherits(&QScript::QtFunction::info)) {
         return JSC::throwError(exec, JSC::TypeError, "Function.prototype.disconnect: this object is not a signal");
     }
     QScript::QtFunction *qtSignal = static_cast<QScript::QtFunction*>(JSC::asObject(thisObject));
     const QMetaObject *meta = qtSignal->metaObject();
     if (!meta) {
         return JSC::throwError(exec, JSC::TypeError, "Function.prototype.discconnect: cannot disconnect from deleted QObject");
     }
     QMetaMethod sig = meta->method(qtSignal->initialIndex());
     if (sig.methodType() != QMetaMethod::Signal) {
         QString message = QString::fromLatin1("Function.prototype.disconnect: %0::%1 is not a signal")
                           .arg(QLatin1String(qtSignal->metaObject()->className()))
                           .arg(QLatin1String(sig.signature()));
         return JSC::throwError(exec, JSC::TypeError, message);
     }
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     JSC::JSValue receiver;
     JSC::JSValue slot;
     JSC::JSValue arg0 = args.at(0);
     if (args.size() < 2) {
         slot = arg0;
     } else {
         receiver = arg0;
         JSC::JSValue arg1 = args.at(1);
         if (isFunction(arg1))
             slot = arg1;
         else {
             QScript::SaveFrameHelper saveFrame(engine, exec);
             JSC::UString propertyName = QScriptEnginePrivate::toString(exec, arg1);
             slot = QScriptEnginePrivate::property(exec, arg0, propertyName, QScriptValue::ResolvePrototype);
         }
     }
     if (!isFunction(slot)) {
         return JSC::throwError(exec, JSC::TypeError, "Function.prototype.disconnect: target is not a function");
     }
     bool ok = engine->scriptDisconnect(thisObject, receiver, slot);
     if (!ok) {
         QString message = QString::fromLatin1("Function.prototype.disconnect: failed to disconnect from %0::%1")
                           .arg(QLatin1String(qtSignal->metaObject()->className()))
                           .arg(QLatin1String(sig.signature()));
         return JSC::throwError(exec, JSC::GeneralError, message);
     }
     return JSC::jsUndefined();
 #else
     Q_UNUSED(eng);
     return context->throwError(QScriptContext::TypeError,
                                QLatin1String("Function.prototype.disconnect"));
 #endif // QT_NO_QOBJECT
 }
functionGC()
JSC::JSValue JSC_HOST_CALL QScript::functionGC (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue , const JSC::ArgList &) static
Definition at line 785 of file qscriptengine.cpp.
Referenced by functionConnect(), and QScriptEnginePrivate::QScriptEnginePrivate().
 {
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     engine->collectGarbage();
     return JSC::jsUndefined();
 }
functionPrint()
JSC::JSValue JSC_HOST_CALL QScript::functionPrint (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue , const JSC::ArgList & args) static
Definition at line 768 of file qscriptengine.cpp.
Referenced by functionConnect(), and QScriptEnginePrivate::QScriptEnginePrivate().
 {
     QString result;
     for (unsigned i = 0; i < args.size(); ++i) {
         if (i != 0)
             result.append(QLatin1Char(' '));
         QString s(args.at(i).toString(exec));
         if (exec->hadException())
             break;
         result.append(s);
     }
     if (exec->hadException())
         return exec->exception();
     qDebug("%s", qPrintable(result));
     return JSC::jsUndefined();
 }
functionQsTr()
JSC::JSValue JSC_HOST_CALL QScript::functionQsTr (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue , const JSC::ArgList & args) static
Definition at line 861 of file qscriptengine.cpp.
Referenced by functionVersion(), and QScriptEngine::installTranslatorFunctions().
 {
     if (args.size() < 1)
         return JSC::throwError(exec, JSC::GeneralError, "qsTr() requires at least one argument");
     if (!args.at(0).isString())
         return JSC::throwError(exec, JSC::GeneralError, "qsTr(): first argument (text) must be a string");
     if ((args.size() > 1) && !args.at(1).isString())
         return JSC::throwError(exec, JSC::GeneralError, "qsTr(): second argument (comment) must be a string");
     if ((args.size() > 2) && !args.at(2).isNumber())
         return JSC::throwError(exec, JSC::GeneralError, "qsTr(): third argument (n) must be a number");
 #ifndef QT_NO_QOBJECT
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     JSC::UString context;
     // The first non-empty source URL in the call stack determines the translation context.
     {
         JSC::ExecState *frame = exec->callerFrame()->removeHostCallFrameFlag();
         while (frame) {
             if (frame->codeBlock() && QScriptEnginePrivate::hasValidCodeBlockRegister(frame)
                 && frame->codeBlock()->source()
                 && !frame->codeBlock()->source()->url().isEmpty()) {
                 context = engine->translationContextFromUrl(frame->codeBlock()->source()->url());
                 break;
             }
             frame = frame->callerFrame()->removeHostCallFrameFlag();
         }
     }
 #endif
     JSC::UString text = args.at(0).toString(exec);
 #ifndef QT_NO_QOBJECT
     JSC::UString comment;
     if (args.size() > 1)
         comment = args.at(1).toString(exec);
     int n = -1;
     if (args.size() > 2)
         n = args.at(2).toInt32(exec);
 #endif
     JSC::UString result;
 #ifndef QT_NO_QOBJECT
     result = QCoreApplication::translate(context.UTF8String().c_str(),
                                          text.UTF8String().c_str(),
                                          comment.UTF8String().c_str(),
                                          QCoreApplication::UnicodeUTF8, n);
 #else
     result = text;
 #endif
     return JSC::jsString(exec, result);
 }
functionQsTranslate()
JSC::JSValue JSC_HOST_CALL QScript::functionQsTranslate (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue , const JSC::ArgList & args) static
Definition at line 806 of file qscriptengine.cpp.
Referenced by functionVersion(), and QScriptEngine::installTranslatorFunctions().
 {
     if (args.size() < 2)
         return JSC::throwError(exec, JSC::GeneralError, "qsTranslate() requires at least two arguments");
     if (!args.at(0).isString())
         return JSC::throwError(exec, JSC::GeneralError, "qsTranslate(): first argument (context) must be a string");
     if (!args.at(1).isString())
         return JSC::throwError(exec, JSC::GeneralError, "qsTranslate(): second argument (text) must be a string");
     if ((args.size() > 2) && !args.at(2).isString())
         return JSC::throwError(exec, JSC::GeneralError, "qsTranslate(): third argument (comment) must be a string");
     if ((args.size() > 3) && !args.at(3).isString())
         return JSC::throwError(exec, JSC::GeneralError, "qsTranslate(): fourth argument (encoding) must be a string");
     if ((args.size() > 4) && !args.at(4).isNumber())
         return JSC::throwError(exec, JSC::GeneralError, "qsTranslate(): fifth argument (n) must be a number");
 #ifndef QT_NO_QOBJECT
     JSC::UString context = args.at(0).toString(exec);
 #endif
     JSC::UString text = args.at(1).toString(exec);
 #ifndef QT_NO_QOBJECT
     JSC::UString comment;
     if (args.size() > 2)
         comment = args.at(2).toString(exec);
     QCoreApplication::Encoding encoding = QCoreApplication::UnicodeUTF8;
     if (args.size() > 3) {
         JSC::UString encStr = args.at(3).toString(exec);
         if (encStr == "CodecForTr")
             encoding = QCoreApplication::CodecForTr;
         else if (encStr == "UnicodeUTF8")
             encoding = QCoreApplication::UnicodeUTF8;
         else
             return JSC::throwError(exec, JSC::GeneralError, QString::fromLatin1("qsTranslate(): invalid encoding '%0'").arg(encStr));
     }
     int n = -1;
     if (args.size() > 4)
         n = args.at(4).toInt32(exec);
 #endif
     JSC::UString result;
 #ifndef QT_NO_QOBJECT
     result = QCoreApplication::translate(context.UTF8String().c_str(),
                                          text.UTF8String().c_str(),
                                          comment.UTF8String().c_str(),
                                          encoding, n);
 #else
     result = text;
 #endif
     return JSC::jsString(exec, result);
 }
functionQsTranslateNoOp()
JSC::JSValue JSC_HOST_CALL QScript::functionQsTranslateNoOp (JSC::ExecState * , JSC::JSObject * , JSC::JSValue , const JSC::ArgList & args) static
Definition at line 854 of file qscriptengine.cpp.
Referenced by functionVersion(), and QScriptEngine::installTranslatorFunctions().
 {
     if (args.size() < 2)
         return JSC::jsUndefined();
     return args.at(1);
 }
functionQsTrId()
JSC::JSValue JSC_HOST_CALL QScript::functionQsTrId (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue , const JSC::ArgList & args) static
Definition at line 916 of file qscriptengine.cpp.
Referenced by functionVersion(), and QScriptEngine::installTranslatorFunctions().
 {
     if (args.size() < 1)
         return JSC::throwError(exec, JSC::GeneralError, "qsTrId() requires at least one argument");
     if (!args.at(0).isString())
         return JSC::throwError(exec, JSC::TypeError, "qsTrId(): first argument (id) must be a string");
     if ((args.size() > 1) && !args.at(1).isNumber())
         return JSC::throwError(exec, JSC::TypeError, "qsTrId(): second argument (n) must be a number");
     JSC::UString id = args.at(0).toString(exec);
     int n = -1;
     if (args.size() > 1)
         n = args.at(1).toInt32(exec);
     return JSC::jsString(exec, qtTrId(id.UTF8String().c_str(), n));
 }
functionQsTrIdNoOp()
JSC::JSValue JSC_HOST_CALL QScript::functionQsTrIdNoOp (JSC::ExecState * , JSC::JSObject * , JSC::JSValue , const JSC::ArgList & args) static
Definition at line 931 of file qscriptengine.cpp.
Referenced by functionVersion(), and QScriptEngine::installTranslatorFunctions().
 {
     if (args.size() < 1)
         return JSC::jsUndefined();
     return args.at(0);
 }
functionQsTrNoOp()
JSC::JSValue JSC_HOST_CALL QScript::functionQsTrNoOp (JSC::ExecState * , JSC::JSObject * , JSC::JSValue , const JSC::ArgList & args) static
Definition at line 909 of file qscriptengine.cpp.
Referenced by functionVersion(), and QScriptEngine::installTranslatorFunctions().
 {
     if (args.size() < 1)
         return JSC::jsUndefined();
     return args.at(0);
 }
functionVersion()
JSC::JSValue JSC_HOST_CALL QScript::functionVersion (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue , const JSC::ArgList &) static
Definition at line 792 of file qscriptengine.cpp.
Referenced by functionConnect(), and QScriptEnginePrivate::QScriptEnginePrivate().
 {
     return JSC::JSValue(exec, 1);
 }
hasMethodAccess()
static bool QScript::hasMethodAccess (const QMetaMethod & method, int index, const QScriptEngine::QObjectWrapOptions & opt) static
Definition at line 152 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertyNames(), QScript::QObjectDelegate::getOwnPropertySlot(), and QScript::QObjectDelegate::put().
 {
     return (method.access() != QMetaMethod::Private)
         && ((index != 2) || !(opt & QScriptEngine::ExcludeDeleteLater))
         && (!(opt & QScriptEngine::ExcludeSlots) || (method.methodType() != QMetaMethod::Slot));
 }
indexOfMetaEnum()
static int QScript::indexOfMetaEnum (const QMetaObject * meta, const QByteArray & str) static
Definition at line 248 of file qscriptqobject.cpp.
Referenced by callQtMethod().
 {
     QByteArray scope;
     QByteArray name;
     int scopeIdx = str.lastIndexOf("::");
     if (scopeIdx != -1) {
         scope = str.left(scopeIdx);
         name = str.mid(scopeIdx + 2);
     } else {
         name = str;
     }
     for (int i = meta->enumeratorCount() - 1; i >= 0; --i) {
         QMetaEnum m = meta->enumerator(i);
         if ((m.name() == name) && (scope.isEmpty() || (m.scope() == scope)))
             return i;
     }
     return -1;
 }
integerFromString() [1/2]
qsreal QScript::integerFromString (const char * buf, int size, int radix)
Definition at line 547 of file qscriptengine.cpp.
Referenced by QScript::Lexer::lex().
 {
     if (size == 0)
         return qSNaN();
     qsreal sign = 1.0;
     int i = 0;
     if (buf[0] == '+') {
         ++i;
     } else if (buf[0] == '-') {
         sign = -1.0;
         ++i;
     }
     if (((size-i) >= 2) && (buf[i] == '0')) {
         if (((buf[i+1] == 'x') || (buf[i+1] == 'X'))
             && (radix < 34)) {
             if ((radix != 0) && (radix != 16))
                 return 0;
             radix = 16;
             i += 2;
         } else {
             if (radix == 0) {
                 radix = 8;
                 ++i;
             }
         }
     } else if (radix == 0) {
         radix = 10;
     }
     int j = i;
     for ( ; i < size; ++i) {
         int d = toDigit(buf[i]);
         if ((d == -1) || (d >= radix))
             break;
     }
     qsreal result;
     if (j == i) {
         if (!qstrcmp(buf, "Infinity"))
             result = qInf();
         else
             result = qSNaN();
     } else {
         result = 0;
         qsreal multiplier = 1;
         for (--i ; i >= j; --i, multiplier *= radix)
             result += toDigit(buf[i]) * multiplier;
     }
     result *= sign;
     return result;
 }
integerFromString() [2/2]
qsreal QScript::integerFromString (const QString & str, int radix)
Definition at line 600 of file qscriptengine.cpp.
 {
     QByteArray ba = str.trimmed().toUtf8();
     return integerFromString(ba.constData(), ba.size(), radix);
 }
isEnumerableMetaProperty()
static bool QScript::isEnumerableMetaProperty (const QMetaProperty & prop, const QMetaObject * mo, int index) static
Definition at line 159 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::getOwnPropertyNames().
 {
     return prop.isScriptable() && prop.isValid()
         // the following lookup is to ensure that we have the
         // "most derived" occurrence of the property with this name
         && (mo->indexOfProperty(prop.name()) == index);
 }
isFunction()
bool QScript::isFunction (JSC::JSValue value)
Definition at line 606 of file qscriptengine.cpp.
Referenced by QScriptDeclarativeClass::function(), functionConnect(), functionDisconnect(), QScriptDeclarativeClass::functionValue(), QScriptValue::isFunction(), QScriptEngine::qScriptConnect(), and QScriptEngine::qScriptDisconnect().
 {
     if (!value || !value.isObject())
         return false;
     JSC::CallData callData;
     return (JSC::asObject(value)->getCallData(callData) != JSC::CallTypeNone);
 }
IsNumerical()
static bool QScript::IsNumerical (const QScriptValue & value) static
Definition at line 725 of file qscriptvalue.cpp.
Referenced by Equals().
 {
     return value.isNumber() || value.isBool();
 }
LessThan()
static bool QScript::LessThan (QScriptValue lhs, QScriptValue rhs) static
Definition at line 730 of file qscriptvalue.cpp.
Referenced by QScriptValue::lessThan().
 {
     if (type(lhs) == type(rhs)) {
         switch (type(lhs)) {
         case Undefined:
         case Null:
             return false;
         case Number:
             return lhs.toNumber() < rhs.toNumber();
         case Boolean:
             return lhs.toBool() < rhs.toBool();
         case String:
             return lhs.toString() < rhs.toString();
         case Object:
             break;
         } // switch
     }
     if (lhs.isObject())
         lhs = ToPrimitive(lhs, JSC::PreferNumber);
     if (rhs.isObject())
         rhs = ToPrimitive(rhs, JSC::PreferNumber);
     if (lhs.isString() && rhs.isString())
         return lhs.toString() < rhs.toString();
     return lhs.toNumber() < rhs.toNumber();
 }
metaMethod()
static QMetaMethod QScript::metaMethod (const QMetaObject * meta, QMetaMethod::MethodType type, int index) static
Definition at line 513 of file qscriptqobject.cpp.
Referenced by callQtMethod(), and QDeclarativeEngineDebugService::setMethodBody().
 {
     if (type != QMetaMethod::Constructor)
         return meta->method(index);
     else
         return meta->constructor(index);
 }
methodName()
static QByteArray QScript::methodName (const char * signature, int nameLength) inline static
Makes a deep copy of the first nameLength characters of the given method signature and returns the copy.
Warning
This function is not part of the public interface.
Definition at line 191 of file qscriptqobject.cpp.
Referenced by QDeclarativePropertyCache::append(), QDeclarativeEngineDebugService::buildObjectDump(), callQtMethod(), QDeclarativePropertyCache::create(), QDeclarativePropertyPrivate::findSignalByName(), QDBusXmlParser::interfaces(), QDeclarativeEngineDebugService::messageReceived(), QDBusInterfacePrivate::metacall(), QDeclarativeObjectMethodScriptClass::relatedMethod(), and QSingleShotTimer::timerEvent().
 {
     return QByteArray(signature, nameLength);
 }
methodNameEquals()
static bool QScript::methodNameEquals (const QMetaMethod & method, const char * signature, int nameLength) inline static
Returns true if the name of the given method is the same as that specified by the (signature, nameLength) pair, otherwise returns false.
Warning
This function is not part of the public interface.
Definition at line 205 of file qscriptqobject.cpp.
Referenced by callQtMethod(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertySlot(), and QScript::QtFunction::overloadedIndexes().
 {
     const char *otherSignature = method.signature();
     return !qstrncmp(otherSignature, signature, nameLength)
         && (otherSignature[nameLength] == '(');
 }
methodNameLength()
static int QScript::methodNameLength (const QMetaMethod & method) inline static
Calculates the length of the name of the given method by looking for the first '(' character.
Warning
This function is not part of the public interface.
Definition at line 175 of file qscriptqobject.cpp.
Referenced by callQtMethod(), and QScript::QtFunction::overloadedIndexes().
 {
     const char *signature = method.signature();
     const char *s = signature;
     while (*s && (*s != '('))
         ++s;
     return s - signature;
 }
MsFromTime()
static int QScript::MsFromTime (qsreal t) inline static
Definition at line 451 of file qscriptengine.cpp.
Referenced by MsToDateTime().
 {
     int r = int(::fmod(t, MsPerSecond));
     return (r >= 0) ? r : r + int(MsPerSecond);
 }
MsToDateTime()
QDateTime QScript::MsToDateTime (JSC::ExecState * exec, qsreal t)
Converts a JS date value (milliseconds) to a QDateTime (local time).
Warning
This function is not part of the public interface.
Definition at line 464 of file qscriptengine.cpp.
Referenced by QScriptEnginePrivate::toDateTime().
 {
     if (qIsNaN(t))
         return QDateTime();
     JSC::GregorianDateTime tm;
     JSC::msToGregorianDateTime(exec, t, /*output UTC=*/true, tm);
     int ms = MsFromTime(t);
     QDateTime convertedUTC = QDateTime(QDate(tm.year + 1900, tm.month + 1, tm.monthDay),
                                        QTime(tm.hour, tm.minute, tm.second, ms), Qt::UTC);
     return convertedUTC.toLocalTime();
 }
qmetaobjectProtoFuncClassName()
static JSC::JSValue JSC_HOST_CALL QScript::qmetaobjectProtoFuncClassName (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue thisValue, const JSC::ArgList &) static
Definition at line 2012 of file qscriptqobject.cpp.
Referenced by QScript::QMetaObjectPrototype::QMetaObjectPrototype().
 {
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     thisValue = engine->toUsableValue(thisValue);
     if (!thisValue.inherits(&QMetaObjectWrapperObject::info))
         return throwError(exec, JSC::TypeError, "this object is not a QMetaObject");
     const QMetaObject *meta = static_cast<QMetaObjectWrapperObject*>(JSC::asObject(thisValue))->value();
     return JSC::jsString(exec, meta->className());
 }
qobjectProtoFuncFindChild()
static JSC::JSValue JSC_HOST_CALL QScript::qobjectProtoFuncFindChild (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue thisValue, const JSC::ArgList & args) static
Definition at line 1665 of file qscriptqobject.cpp.
Referenced by QScript::QObjectPrototype::QObjectPrototype().
 {
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     thisValue = engine->toUsableValue(thisValue);
     if (!thisValue.inherits(&QScriptObject::info))
         return throwError(exec, JSC::TypeError, "this object is not a QObject");
     QScriptObject *scriptObject = static_cast<QScriptObject*>(JSC::asObject(thisValue));
     QScriptObjectDelegate *delegate = scriptObject->delegate();
     if (!delegate || (delegate->type() != QScriptObjectDelegate::QtObject))
         return throwError(exec, JSC::TypeError, "this object is not a QObject");
     QObject *obj = static_cast<QObjectDelegate*>(delegate)->value();
     QString name;
     if (args.size() != 0)
         name = args.at(0).toString(exec);
     QObject *child = obj->findChild<QObject*>(name);
     QScriptEngine::QObjectWrapOptions opt = QScriptEngine::PreferExistingWrapperObject;
     return engine->newQObject(child, QScriptEngine::QtOwnership, opt);
 }
qobjectProtoFuncFindChildren()
static JSC::JSValue JSC_HOST_CALL QScript::qobjectProtoFuncFindChildren (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue thisValue, const JSC::ArgList & args) static
Definition at line 1685 of file qscriptqobject.cpp.
Referenced by QScript::QObjectPrototype::QObjectPrototype().
 {
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     thisValue = engine->toUsableValue(thisValue);
     // extract the QObject
     if (!thisValue.inherits(&QScriptObject::info))
         return throwError(exec, JSC::TypeError, "this object is not a QObject");
     QScriptObject *scriptObject = static_cast<QScriptObject*>(JSC::asObject(thisValue));
     QScriptObjectDelegate *delegate = scriptObject->delegate();
     if (!delegate || (delegate->type() != QScriptObjectDelegate::QtObject))
         return throwError(exec, JSC::TypeError, "this object is not a QObject");
     const QObject *const obj = static_cast<QObjectDelegate*>(delegate)->value();
     // find the children
     QList<QObject *> children;
     if (args.size() != 0) {
         const JSC::JSValue arg = args.at(0);
         if (arg.inherits(&JSC::RegExpObject::info)) {
             const QObjectList allChildren= obj->children();
             JSC::RegExpObject *const regexp = JSC::asRegExpObject(arg);
             const int allChildrenCount = allChildren.size();
             for (int i = 0; i < allChildrenCount; ++i) {
                 QObject *const child = allChildren.at(i);
                 const JSC::UString childName = child->objectName();
                 JSC::RegExpConstructor* regExpConstructor = engine->originalGlobalObject()->regExpConstructor();
                 int position;
                 int length;
                 regExpConstructor->performMatch(regexp->regExp(), childName, 0, position, length);
                 if (position >= 0)
                     children.append(child);
             }
         } else {
             const QString name(args.at(0).toString(exec));
             children = obj->findChildren<QObject*>(name);
         }
     } else {
         children = obj->findChildren<QObject*>(QString());
     }
     // create the result array with the children
     const int length = children.size();
     JSC::JSArray *const result = JSC::constructEmptyArray(exec, length);
     QScriptEngine::QObjectWrapOptions opt = QScriptEngine::PreferExistingWrapperObject;
     for (int i = 0; i < length; ++i) {
         QObject *const child = children.at(i);
         result->put(exec, i, engine->newQObject(child, QScriptEngine::QtOwnership, opt));
     }
     return JSC::JSValue(result);
 }
qobjectProtoFuncToString()
static JSC::JSValue JSC_HOST_CALL QScript::qobjectProtoFuncToString (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue thisValue, const JSC::ArgList &) static
Definition at line 1738 of file qscriptqobject.cpp.
Referenced by QScript::QObjectPrototype::QObjectPrototype().
 {
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     thisValue = engine->toUsableValue(thisValue);
     if (!thisValue.inherits(&QScriptObject::info))
         return JSC::jsUndefined();
     QScriptObject *scriptObject = static_cast<QScriptObject*>(JSC::asObject(thisValue));
     QScriptObjectDelegate *delegate = scriptObject->delegate();
     if (!delegate || (delegate->type() != QScriptObjectDelegate::QtObject))
         return JSC::jsUndefined();
     QObject *obj = static_cast<QObjectDelegate*>(delegate)->value();
     const QMetaObject *meta = obj ? obj->metaObject() : &QObject::staticMetaObject;
     QString name = obj ? obj->objectName() : QString::fromUtf8("unnamed");
     QString str = QString::fromUtf8("%0(name = \"%1\")")
                   .arg(QLatin1String(meta->className())).arg(name);
     return JSC::jsString(exec, str);
 }
scriptableFromQObject()
static QScriptable* QScript::scriptableFromQObject (QObject * qobj) inline static
Definition at line 267 of file qscriptqobject.cpp.
Referenced by callQtMethod(), and QScript::QtPropertyFunction::execute().
 {
     void *ptr = qobj->qt_metacast("QScriptable");
     return reinterpret_cast<QScriptable*>(ptr);
 }
scriptEngineFromExec()
QScriptEnginePrivate * QScript::scriptEngineFromExec (const JSC::ExecState * exec) inline
Definition at line 512 of file qscriptengine_p.h.
Referenced by QScriptContext::activationObject(), QScriptContext::argumentsObject(), QScript::ClassObjectDelegate::call(), QScript::DeclarativeObjectDelegate::call(), QScript::QtFunction::call(), QScript::QMetaObjectWrapperObject::call(), QScriptContext::callee(), callQtMethod(), QScript::ClassObjectDelegate::construct(), QScript::QMetaObjectWrapperObject::construct(), QScriptEnginePrivate::contextForFrame(), QScriptEnginePrivate::convertValue(), QScriptEnginePrivate::create(), QScript::ClassObjectDelegate::deleteProperty(), QScriptContext::engine(), QScript::QtFunction::execute(), QScript::QtPropertyFunction::execute(), QScript::QMetaObjectWrapperObject::execute(), functionConnect(), functionDisconnect(), functionGC(), functionQsTr(), QScript::GlobalObject::getOwnPropertyDescriptor(), QScript::ClassObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::ClassObjectDelegate::getOwnPropertyNames(), QScript::GlobalObject::getOwnPropertySlot(), QScript::ClassObjectDelegate::getOwnPropertySlot(), QScript::QObjectDelegate::getOwnPropertySlot(), QScript::ClassObjectDelegate::hasInstance(), QScriptContext::isCalledAsConstructor(), QScriptContext::parentContext(), QScriptContext::popScope(), QScript::FunctionWrapper::proxyCall(), QScript::FunctionWithArgWrapper::proxyCall(), QScript::FunctionWrapper::proxyConstruct(), QScript::FunctionWithArgWrapper::proxyConstruct(), QScriptContext::pushScope(), QScript::ClassObjectDelegate::put(), QScript::DeclarativeObjectDelegate::put(), QScript::QObjectDelegate::put(), qmetaobjectProtoFuncClassName(), qobjectProtoFuncFindChild(), qobjectProtoFuncFindChildren(), qobjectProtoFuncToString(), QScriptContextInfoPrivate::QScriptContextInfoPrivate(), QScriptContext::scopeChain(), QScriptDeclarativeClass::scopeChainValue(), QScriptContext::setActivationObject(), QScriptContext::setReturnValue(), QScriptContext::setThisObject(), QScriptContext::thisObject(), QScriptContext::throwError(), QScriptContext::throwValue(), QScriptEnginePrivate::variantListFromArray(), QScriptEnginePrivate::variantMapFromObject(), variantProtoFuncToString(), and variantProtoFuncValueOf().
 {
     return static_cast<GlobalClientData*>(exec->globalData().clientData)->engine;
 }
stringProtoFuncArg()
JSC::JSValue JSC_HOST_CALL QScript::stringProtoFuncArg (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue thisObject, const JSC::ArgList & args) static
Definition at line 941 of file qscriptengine.cpp.
Referenced by functionQsTrIdNoOp(), and QScriptEngine::installTranslatorFunctions().
 {
     QString value(thisObject.toString(exec));
     JSC::JSValue arg = (args.size() != 0) ? args.at(0) : JSC::jsUndefined();
     QString result;
     if (arg.isString())
         result = value.arg(arg.toString(exec));
     else if (arg.isNumber())
         result = value.arg(arg.toNumber(exec));
     return JSC::jsString(exec, result);
 }
ToBool() [1/2]
bool QScript::ToBool (qsreal value) inline
Definition at line 552 of file qscriptengine_p.h.
Referenced by QScriptEnginePrivate::convertNumber(), QScriptEnginePrivate::convertString(), QScriptValue::toBool(), and QScriptValue::toBoolean().
 {
     return (value != 0) && !qIsNaN(value);
 }
ToBool() [2/2]
bool QScript::ToBool (const QString & value) inline
Definition at line 557 of file qscriptengine_p.h.
 {
      return !value.isEmpty();
 }
toDigit()
static int QScript::toDigit (char c) static
Definition at line 536 of file qscriptengine.cpp.
Referenced by integerFromString().
 {
     if ((c >= '0') && (c <= '9'))
         return c - '0';
     else if ((c >= 'a') && (c <= 'z'))
         return 10 + c - 'a';
     else if ((c >= 'A') && (c <= 'Z'))
         return 10 + c - 'A';
     return -1;
 }
ToInt32() [1/2]
qint32 QScript::ToInt32 (const QString & value) inline
Definition at line 532 of file qscriptengine_p.h.
 {
     return ToInt32(ToNumber(value));
 }
ToInt32() [2/2]
qint32 QScript::ToInt32 (qsreal n)
Definition at line 368 of file qscriptengine.cpp.
Referenced by QScriptEnginePrivate::convertNumber(), QScriptEnginePrivate::convertString(), and QScriptValue::toInt32().
 {
     if (qIsNaN(n) || qIsInf(n) || (n == 0))
         return 0;
     qsreal sign = (n < 0) ? -1.0 : 1.0;
     qsreal abs_n = fabs(n);
     n = ::fmod(sign * ::floor(abs_n), D32);
     const double D31 = D32 / 2.0;
     if (sign == -1 && n < -D31)
         n += D32;
     else if (sign != -1 && n >= D31)
         n -= D32;
     return qint32 (n);
 }
ToInteger() [1/2]
qsreal QScript::ToInteger (const QString & value) inline
Definition at line 547 of file qscriptengine_p.h.
 {
     return ToInteger(ToNumber(value));
 }
ToInteger() [2/2]
qsreal QScript::ToInteger (qsreal n)
Definition at line 422 of file qscriptengine.cpp.
Referenced by QScriptEnginePrivate::convertNumber(), QScriptEnginePrivate::convertString(), and QScriptValue::toInteger().
 {
     if (qIsNaN(n))
         return 0;
     if (n == 0 || qIsInf(n))
         return n;
     int sign = n < 0 ? -1 : 1;
     return sign * ::floor(::fabs(n));
 }
ToNumber()
qsreal QScript::ToNumber (const QString & value) inline
Definition at line 525 of file qscriptengine_p.h.
Referenced by QScriptEnginePrivate::convertString(), ToInt32(), ToInteger(), QScriptValue::toNumber(), ToUInt16(), and ToUInt32().
 {
     return ((JSC::UString)value).toDouble();
 }
ToPrimitive()
static QScriptValue QScript::ToPrimitive (const QScriptValue & object, JSC::PreferredPrimitiveType hint = JSC::NoPreference) static
Definition at line 711 of file qscriptvalue.cpp.
Referenced by Equals(), and LessThan().
 {
     Q_ASSERT(object.isObject());
     QScriptValuePrivate *pp = QScriptValuePrivate::get(object);
     Q_ASSERT(pp->engine != 0);
     QScript::APIShim shim(pp->engine);
     JSC::ExecState *exec = pp->engine->currentFrame;
     JSC::JSValue savedException;
     QScriptEnginePrivate::saveException(exec, &savedException);
     JSC::JSValue result = JSC::asObject(pp->jscValue)->toPrimitive(exec, hint);
     QScriptEnginePrivate::restoreException(exec, savedException);
     return pp->engine->scriptValueFromJSCValue(result);
 }
ToString()
QString QScript::ToString (qsreal value) inline
Definition at line 520 of file qscriptengine_p.h.
Referenced by QScriptEnginePrivate::convertNumber(), ToInteger(), and QScriptValue::toString().
 {
     return JSC::UString::from(value);
 }
ToUInt16() [1/2]
quint16 QScript::ToUInt16 (const QString & value) inline
Definition at line 542 of file qscriptengine_p.h.
 {
     return ToUInt16(ToNumber(value));
 }
ToUInt16() [2/2]
quint16 QScript::ToUInt16 (qsreal n)
Definition at line 404 of file qscriptengine.cpp.
Referenced by QScriptEnginePrivate::convertNumber(), QScriptEnginePrivate::convertString(), QScriptEnginePrivate::convertValue(), QScriptValue::toUInt16(), and QScriptEnginePrivate::toUInt16().
 {
     static const qsreal D16 = 65536.0;
     if (qIsNaN(n) || qIsInf(n) || (n == 0))
         return 0;
     qsreal sign = (n < 0) ? -1.0 : 1.0;
     qsreal abs_n = fabs(n);
     n = ::fmod(sign * ::floor(abs_n), D16);
     if (n < 0)
         n += D16;
     return quint16 (n);
 }
ToUInt32() [1/2]
quint32 QScript::ToUInt32 (const QString & value) inline
Definition at line 537 of file qscriptengine_p.h.
 {
     return ToUInt32(ToNumber(value));
 }
ToUInt32() [2/2]
quint32 QScript::ToUInt32 (qsreal n)
Definition at line 388 of file qscriptengine.cpp.
Referenced by QScriptEnginePrivate::convertNumber(), QScriptEnginePrivate::convertString(), and QScriptValue::toUInt32().
 {
     if (qIsNaN(n) || qIsInf(n) || (n == 0))
         return 0;
     qsreal sign = (n < 0) ? -1.0 : 1.0;
     qsreal abs_n = fabs(n);
     n = ::fmod(sign * ::floor(abs_n), D32);
     if (n < 0)
         n += D32;
     return quint32 (n);
 }
type()
static Type QScript::type (const QScriptValue & v) static
Definition at line 695 of file qscriptvalue.cpp.
 {
     if (v.isUndefined())
         return Undefined;
     else if (v.isNull())
         return Null;
     else if (v.isBoolean())
         return Boolean;
     else if (v.isString())
         return String;
     else if (v.isNumber())
         return Number;
     Q_ASSERT(v.isObject());
     return Object;
 }
variantFromValue()
static QVariant QScript::variantFromValue (JSC::ExecState * exec, int targetType, JSC::JSValue value) static
Definition at line 213 of file qscriptqobject.cpp.
Referenced by QScript::QtPropertyFunction::execute().
 {
     QVariant v(targetType, (void *)0);
     if (QScriptEnginePrivate::convertValue(exec, value, targetType, v.data()))
         return v;
     if (uint(targetType) == QVariant::LastType)
         return QScriptEnginePrivate::toVariant(exec, value);
     if (QScriptEnginePrivate::isVariant(value)) {
         v = QScriptEnginePrivate::variantValue(value);
         if (v.canConvert(QVariant::Type(targetType))) {
             v.convert(QVariant::Type(targetType));
             return v;
         }
         QByteArray typeName = v.typeName();
         if (typeName.endsWith('*')
             && (QMetaType::type(typeName.left(typeName.size()-1)) == targetType)) {
             return QVariant(targetType, *reinterpret_cast<void* *>(v.data()));
         }
     }
     return QVariant();
 }
variantProtoFuncToString()
static JSC::JSValue JSC_HOST_CALL QScript::variantProtoFuncToString (JSC::ExecState * exec, JSC::JSObject * callee, JSC::JSValue thisValue, const JSC::ArgList & args) static
Definition at line 109 of file qscriptvariant.cpp.
Referenced by QScript::QVariantPrototype::QVariantPrototype().
 {
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     thisValue = engine->toUsableValue(thisValue);
     if (!thisValue.inherits(&QScriptObject::info))
         return throwError(exec, JSC::TypeError, "This object is not a QVariant");
     QScriptObjectDelegate *delegate = static_cast<QScriptObject*>(JSC::asObject(thisValue))->delegate();
     if (!delegate || (delegate->type() != QScriptObjectDelegate::Variant))
         return throwError(exec, JSC::TypeError, "This object is not a QVariant");
     const QVariant &v = static_cast<QVariantDelegate*>(delegate)->value();
     JSC::UString result;
     JSC::JSValue value = variantProtoFuncValueOf(exec, callee, thisValue, args);
     if (value.isObject()) {
         result = v.toString();
         if (result.isEmpty() && !v.canConvert(QVariant::String))
             result = QString::fromLatin1("QVariant(%0)").arg(QString::fromLatin1(v.typeName()));
     } else {
         result = value.toString(exec);
     }
     return JSC::jsString(exec, result);
 }
variantProtoFuncValueOf()
static JSC::JSValue JSC_HOST_CALL QScript::variantProtoFuncValueOf (JSC::ExecState * exec, JSC::JSObject * , JSC::JSValue thisValue, const JSC::ArgList &) static
Definition at line 71 of file qscriptvariant.cpp.
Referenced by QScript::QVariantPrototype::QVariantPrototype(), and variantProtoFuncToString().
 {
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     thisValue = engine->toUsableValue(thisValue);
     if (!thisValue.inherits(&QScriptObject::info))
         return throwError(exec, JSC::TypeError);
     QScriptObjectDelegate *delegate = static_cast<QScriptObject*>(JSC::asObject(thisValue))->delegate();
     if (!delegate || (delegate->type() != QScriptObjectDelegate::Variant))
         return throwError(exec, JSC::TypeError);
     const QVariant &v = static_cast<QVariantDelegate*>(delegate)->value();
     switch (v.type()) {
     case QVariant::Invalid:
         return JSC::jsUndefined();
     case QVariant::String:
         return JSC::jsString(exec, v.toString());
     case QVariant::Int:
         return JSC::jsNumber(exec, v.toInt());
     case QVariant::Bool:
         return JSC::jsBoolean(v.toBool());
     case QVariant::Double:
         return JSC::jsNumber(exec, v.toDouble());
 //    case QVariant::Char:
 //        return JSC::jsNumber(exec, v.toChar().unicode());
     case QVariant::UInt:
         return JSC::jsNumber(exec, v.toUInt());
     default:
         ;
     }
     return thisValue;
 }
Variable Documentation
D32
const qsreal QScript::D32 = 4294967296.0 static
Definition at line 366 of file qscriptengine.cpp.
Referenced by ToInt32(), and ToUInt32().
GeneratePropertyFunctions
const bool QScript::GeneratePropertyFunctions = true static
Definition at line 236 of file qscriptqobject.cpp.
MsPerSecond
const qsreal QScript::MsPerSecond = 1000.0 static
Definition at line 449 of file qscriptengine.cpp.
qt_meta_data_QObjectConnectionManager
const uint QScript::qt_meta_data_QObjectConnectionManager[] static
Initial value:
= {
       1,
       0,
       0,    0,
       1,   10,
       0,    0,
       0,    0,
      35,   34,   34,   34, 0x0a,
       0
}
Definition at line 2031 of file qscriptqobject.cpp.
qt_meta_stringdata_QObjectConnectionManager
const char QScript::qt_meta_stringdata_QObjectConnectionManager[] static
Initial value:
= {
    "QScript::QObjectConnectionManager\0\0execute()\0"
}
Definition at line 2047 of file qscriptqobject.cpp.