Qt 4.8: QImageScale Namespace Reference
QImageScale Namespace Reference
Classes
struct QImageScaleInfo
Functions
int * qimageCalcApoints (int s, int d, int up)
QImageScaleInfo * qimageCalcScaleInfo (const QImage &img, int sw, int sh, int dw, int dh, char aa)
int * qimageCalcXPoints (int sw, int dw)
unsigned int ** qimageCalcYPoints (unsigned int *src, int sw, int sh, int dh)
QImageScaleInfo * qimageFreeScaleInfo (QImageScaleInfo *isi)
Function Documentation
qimageCalcApoints()
int * QImageScale::qimageCalcApoints (int s, int d, int up)
Definition at line 209 of file qimagescale.cpp.
Referenced by qimageCalcScaleInfo().
 {
     int *p, i, j = 0, rv = 0;
     if(d < 0){
         rv = 1;
         d = -d;
     }
     p = new int[d];
     /* scaling up */
     if(up){
         int val, inc;
         val = 0x8000 * s / d - 0x8000;
         inc = (s << 16) / d;
         for(i = 0; i < d; i++){
             int pos = val >> 16;
             if (pos < 0)
                 p[j++] = 0;
             else if (pos >= (s - 1))
                 p[j++] = 0;
             else
                 p[j++] = (val >> 8) - ((val >> 8) & 0xffffff00);
             val += inc;
         }
     }
     /* scaling down */
     else{
         int val, inc, ap, Cp;
         val = 0;
         inc = (s << 16) / d;
         Cp = ((d << 14) / s) + 1;
         for(i = 0; i < d; i++){
             ap = ((0x100 - ((val >> 8) & 0xff)) * Cp) >> 8;
             p[j] = ap | (Cp << 16);
             j++;
             val += inc;
         }
     }
     if(rv){
         int tmp;
         for(i = d / 2; --i >= 0; ){
             tmp = p[i];
             p[i] = p[d - i - 1];
             p[d - i - 1] = tmp;
         }
     }
     return(p);
 }
qimageCalcScaleInfo()
QImageScaleInfo * QImageScale::qimageCalcScaleInfo (const QImage & img, int sw, int sh, int dw, int dh, char aa)
Definition at line 272 of file qimagescale.cpp.
Referenced by qSmoothScaleImage().
 {
     QImageScaleInfo *isi;
     int scw, sch;
     scw = dw * qlonglong(img.width()) / sw;
     sch = dh * qlonglong(img.height()) / sh;
     isi = new QImageScaleInfo;
     if(!isi)
         return 0;
     memset(isi, 0, sizeof(QImageScaleInfo));
     isi->xup_yup = (qAbs(dw) >= sw) + ((qAbs(dh) >= sh) << 1);
     isi->xpoints = qimageCalcXPoints(img.width(), scw);
     if(!isi->xpoints)
         return(qimageFreeScaleInfo(isi));
     isi->ypoints = qimageCalcYPoints((unsigned int *)img.scanLine(0),
                                      img.bytesPerLine() / 4, img.height(), sch);
     if (!isi->ypoints)
         return(qimageFreeScaleInfo(isi));
     if(aa) {
         isi->xapoints = qimageCalcApoints(img.width(), scw, isi->xup_yup & 1);
         if(!isi->xapoints)
             return(qimageFreeScaleInfo(isi));
         isi->yapoints = qimageCalcApoints(img.height(), sch, isi->xup_yup & 2);
         if(!isi->yapoints)
             return(qimageFreeScaleInfo(isi));
     }
     return(isi);
 }
qimageCalcXPoints()
int * QImageScale::qimageCalcXPoints (int sw, int dw)
Definition at line 180 of file qimagescale.cpp.
Referenced by qimageCalcScaleInfo().
 {
     int *p, i, j = 0;
     int val, inc, rv = 0;
     if(dw < 0){
         dw = -dw;
         rv = 1;
     }
     p = new int[dw+1];
     int up = qAbs(dw) >= sw;
     val = up ? 0x8000 * sw / dw - 0x8000 : 0;
     inc = (sw << 16) / dw;
     for(i = 0; i < dw; i++){
         p[j++] = qMax(0, val >> 16);
         val += inc;
     }
     if(rv){
         for(i = dw / 2; --i >= 0; ){
             int tmp = p[i];
             p[i] = p[dw - i - 1];
             p[dw - i - 1] = tmp;
         }
     }
    return(p);
 }
qimageCalcYPoints()
unsigned int ** QImageScale::qimageCalcYPoints (unsigned int * src, int sw, int sh, int dh)
Definition at line 150 of file qimagescale.cpp.
Referenced by qimageCalcScaleInfo().
 {
     unsigned int **p;
     int i, j = 0;
     int val, inc, rv = 0;
     if(dh < 0){
         dh = -dh;
         rv = 1;
     }
     p = new unsigned int* [dh+1];
     int up = qAbs(dh) >= sh;
     val = up ? 0x8000 * sh / dh - 0x8000 : 0;
     inc = (sh << 16) / dh;
     for(i = 0; i < dh; i++){
         p[j++] = src + qMax(0, val >> 16) * sw;
         val += inc;
     }
     if(rv){
         for(i = dh / 2; --i >= 0; ){
             unsigned int *tmp = p[i];
             p[i] = p[dh - i - 1];
             p[dh - i - 1] = tmp;
         }
     }
     return(p);
 }
qimageFreeScaleInfo()
QImageScaleInfo * QImageScale::qimageFreeScaleInfo (QImageScaleInfo * isi)
Definition at line 260 of file qimagescale.cpp.
Referenced by qimageCalcScaleInfo(), and qSmoothScaleImage().
 {
     if(isi){
         delete[] isi->xpoints;
         delete[] isi->ypoints;
         delete[] isi->xapoints;
         delete[] isi->yapoints;
         delete isi;
     }
     return 0;
 }