Qt 4.8: QmlJSDebugger Namespace Reference
QmlJSDebugger Namespace Reference
Namespaces
Constants
Classes
class AbstractLiveEditTool
class AbstractTool
class AbstractViewInspector
class BoundingBox
class BoundingBoxPolygonItem
class BoundingRectHighlighter
class ColorPickerTool
class InspectorProtocol
class LiveLayerItem
class LiveRubberBandSelectionManipulator
class LiveSelectionIndicator
class LiveSelectionRectangle
class LiveSelectionTool
class LiveSingleSelectionManipulator
class QDeclarativeInspectorPlugin
class QDeclarativeViewInspector
class QDeclarativeViewInspectorPrivate
class QmlToolBar
class SelectionRectShape
class SubcomponentMaskLayerItem
class ToolBarColorBox
class ZoomTool
Functions
static bool isEditorItem (QGraphicsItem *item)
QDataStream & operator<< (QDataStream &stream, InspectorProtocol::Message message)
QDebug operator<< (QDebug dbg, InspectorProtocol::Message message)
QDataStream & operator<< (QDataStream &stream, InspectorProtocol::Tool tool)
QDebug operator<< (QDebug dbg, InspectorProtocol::Tool tool)
QDataStream & operator>> (QDataStream &stream, InspectorProtocol::Message &message)
QDataStream & operator>> (QDataStream &stream, InspectorProtocol::Tool &tool)
static QPolygonF regionToPolygon (const QRegion &region)
static QRectF resizeRect (const QRectF &newRect, const QRectF &oldRect)
Function Documentation
isEditorItem()
static bool QmlJSDebugger::isEditorItem (QGraphicsItem * item) static
Definition at line 390 of file qdeclarativeviewinspector.cpp.
Referenced by QmlJSDebugger::QDeclarativeViewInspectorPrivate::filterForSelection().
 {
     return (item->type() == Constants::EditorItemType
             || item->type() == Constants::ResizeHandleItemType
             || item->data(Constants::EditorItemDataKey).toBool());
 }
operator<<() [1/4]
QDataStream& QmlJSDebugger::operator<< (QDataStream & stream, InspectorProtocol::Message message) inline
Definition at line 97 of file qdeclarativeinspectorprotocol.h.
 {
     return stream << static_cast<quint32>(message);
 }
operator<<() [2/4]
QDebug QmlJSDebugger::operator<< (QDebug dbg, InspectorProtocol::Message message) inline
Definition at line 110 of file qdeclarativeinspectorprotocol.h.
 {
     dbg << InspectorProtocol::toString(message);
     return dbg;
 }
operator<<() [3/4]
QDataStream& QmlJSDebugger::operator<< (QDataStream & stream, InspectorProtocol::Tool tool) inline
Definition at line 116 of file qdeclarativeinspectorprotocol.h.
 {
     return stream << static_cast<quint32>(tool);
 }
operator<<() [4/4]
QDebug QmlJSDebugger::operator<< (QDebug dbg, InspectorProtocol::Tool tool) inline
Definition at line 129 of file qdeclarativeinspectorprotocol.h.
 {
     dbg << InspectorProtocol::toString(tool);
     return dbg;
 }
operator>>() [1/2]
QDataStream& QmlJSDebugger::operator>> (QDataStream & stream, InspectorProtocol::Message & message) inline
Definition at line 102 of file qdeclarativeinspectorprotocol.h.
 {
     quint32 i;
     stream >> i;
     message = static_cast<InspectorProtocol::Message>(i);
     return stream;
 }
operator>>() [2/2]
QDataStream& QmlJSDebugger::operator>> (QDataStream & stream, InspectorProtocol::Tool & tool) inline
Definition at line 121 of file qdeclarativeinspectorprotocol.h.
 {
     quint32 i;
     stream >> i;
     tool = static_cast<InspectorProtocol::Tool>(i);
     return stream;
 }
regionToPolygon()
static QPolygonF QmlJSDebugger::regionToPolygon (const QRegion & region) static
Definition at line 89 of file subcomponentmasklayeritem.cpp.
Referenced by QmlJSDebugger::SubcomponentMaskLayerItem::setCurrentItem().
 {
     QPainterPath path;
     foreach (const QRect &rect, region.rects())
         path.addRect(rect);
     return path.toFillPolygon();
 }
resizeRect()
static QRectF QmlJSDebugger::resizeRect (const QRectF & newRect, const QRectF & oldRect) static
Definition at line 71 of file subcomponentmasklayeritem.cpp.
Referenced by QmlJSDebugger::SubcomponentMaskLayerItem::setCurrentItem().
 {
     QRectF result = newRect;
     if (oldRect.left() < newRect.left())
         result.setLeft(oldRect.left());
     if (oldRect.top() < newRect.top())
         result.setTop(oldRect.top());
     if (oldRect.right() > newRect.right())
         result.setRight(oldRect.right());
     if (oldRect.bottom() > newRect.bottom())
         result.setBottom(oldRect.bottom());
     return result;
 }