Qt 4.8: QUnicodeTables Namespace Reference
QUnicodeTables Namespace Reference
Classes
struct Properties
Enumerations
enum { ScriptSentinel = 32 }
enum GraphemeBreak {
GraphemeBreakOther, GraphemeBreakCR, GraphemeBreakLF, GraphemeBreakControl,
GraphemeBreakExtend, GraphemeBreakL, GraphemeBreakV, GraphemeBreakT,
GraphemeBreakLV, GraphemeBreakLVT
}
enum LineBreakClass {
LineBreak_OP, LineBreak_CL, LineBreak_QU, LineBreak_GL,
LineBreak_NS, LineBreak_EX, LineBreak_SY, LineBreak_IS,
LineBreak_PR, LineBreak_PO, LineBreak_NU, LineBreak_AL,
LineBreak_ID, LineBreak_IN, LineBreak_HY, LineBreak_BA,
LineBreak_BB, LineBreak_B2, LineBreak_ZW, LineBreak_CM,
LineBreak_WJ, LineBreak_H2, LineBreak_H3, LineBreak_JL,
LineBreak_JV, LineBreak_JT, LineBreak_SA, LineBreak_SG,
LineBreak_SP, LineBreak_CR, LineBreak_LF, LineBreak_BK
}
enum Script {
Common, Greek, Cyrillic, Armenian,
Hebrew, Arabic, Syriac, Thaana,
Devanagari, Bengali, Gurmukhi, Gujarati,
Oriya, Tamil, Telugu, Kannada,
Malayalam, Sinhala, Thai, Lao,
Tibetan, Myanmar, Georgian, Hangul,
Ogham, Runic, Khmer, Nko,
Inherited, ScriptCount = Inherited, Latin = Common, Ethiopic = Common,
Cherokee = Common, CanadianAboriginal = Common, Mongolian = Common, Hiragana = Common,
Katakana = Common, Bopomofo = Common, Han = Common, Yi = Common,
OldItalic = Common, Gothic = Common, Deseret = Common, Tagalog = Common,
Hanunoo = Common, Buhid = Common, Tagbanwa = Common, Limbu = Common,
TaiLe = Common, LinearB = Common, Ugaritic = Common, Shavian = Common,
Osmanya = Common, Cypriot = Common, Braille = Common, Buginese = Common,
Coptic = Common, NewTaiLue = Common, Glagolitic = Common, Tifinagh = Common,
SylotiNagri = Common, OldPersian = Common, Kharoshthi = Common, Balinese = Common,
Cuneiform = Common, Phoenician = Common, PhagsPa = Common
}
enum SentenceBreak {
SentenceBreakOther, SentenceBreakSep, SentenceBreakFormat, SentenceBreakSp,
SentenceBreakLower, SentenceBreakUpper, SentenceBreakOLetter, SentenceBreakNumeric,
SentenceBreakATerm, SentenceBreakSTerm, SentenceBreakClose
}
enum WordBreak {
WordBreakOther, WordBreakFormat, WordBreakKatakana, WordBreakALetter,
WordBreakMidLetter, WordBreakMidNum, WordBreakNumeric, WordBreakExtendNumLet
}
Functions
Q_CORE_EXPORT QUnicodeTables::LineBreakClass QT_FASTCALL lineBreakClass (uint ucs4)
int lineBreakClass (const QChar &ch)
Q_CORE_EXPORT const Properties *QT_FASTCALL properties (uint ucs4)
Q_CORE_EXPORT const Properties *QT_FASTCALL properties (ushort ucs2)
Q_CORE_EXPORT int QT_FASTCALL script (uint ucs4)
int script (const QChar &ch)
Variables
static const unsigned char uc_scripts []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ScriptSentinel
Definition at line 162 of file qunicodetables_p.h.
 { ScriptSentinel = 32 };
GraphemeBreak
enum QUnicodeTables::GraphemeBreak
Enumerator
GraphemeBreakOther
GraphemeBreakCR
GraphemeBreakLF
GraphemeBreakControl
GraphemeBreakExtend
GraphemeBreakL
GraphemeBreakV
GraphemeBreakT
GraphemeBreakLV
GraphemeBreakLVT
Definition at line 165 of file qunicodetables_p.h.
{
         GraphemeBreakOther,
         GraphemeBreakCR,
         GraphemeBreakLF,
         GraphemeBreakControl,
         GraphemeBreakExtend,
         GraphemeBreakL,
         GraphemeBreakV,
         GraphemeBreakT,
         GraphemeBreakLV,
         GraphemeBreakLVT
     };
LineBreakClass
enum QUnicodeTables::LineBreakClass
Enumerator
LineBreak_OP
LineBreak_CL
LineBreak_QU
LineBreak_GL
LineBreak_NS
LineBreak_EX
LineBreak_SY
LineBreak_IS
LineBreak_PR
LineBreak_PO
LineBreak_NU
LineBreak_AL
LineBreak_ID
LineBreak_IN
LineBreak_HY
LineBreak_BA
LineBreak_BB
LineBreak_B2
LineBreak_ZW
LineBreak_CM
LineBreak_WJ
LineBreak_H2
LineBreak_H3
LineBreak_JL
LineBreak_JV
LineBreak_JT
LineBreak_SA
LineBreak_SG
LineBreak_SP
LineBreak_CR
LineBreak_LF
LineBreak_BK
Definition at line 209 of file qunicodetables_p.h.
{
         LineBreak_OP, LineBreak_CL, LineBreak_QU, LineBreak_GL, LineBreak_NS,
         LineBreak_EX, LineBreak_SY, LineBreak_IS, LineBreak_PR, LineBreak_PO,
         LineBreak_NU, LineBreak_AL, LineBreak_ID, LineBreak_IN, LineBreak_HY,
         LineBreak_BA, LineBreak_BB, LineBreak_B2, LineBreak_ZW, LineBreak_CM,
         LineBreak_WJ, LineBreak_H2, LineBreak_H3, LineBreak_JL, LineBreak_JV,
         LineBreak_JT, LineBreak_SA, LineBreak_SG,
         LineBreak_SP, LineBreak_CR, LineBreak_LF, LineBreak_BK
     };
Script
enum QUnicodeTables::Script
Enumerator
Common
Greek
Cyrillic
Armenian
Hebrew
Arabic
Syriac
Thaana
Devanagari
Bengali
Gurmukhi
Gujarati
Oriya
Tamil
Telugu
Kannada
Malayalam
Sinhala
Thai
Lao
Tibetan
Myanmar
Georgian
Hangul
Ogham
Runic
Khmer
Nko
Inherited
ScriptCount
Latin
Ethiopic
Cherokee
CanadianAboriginal
Mongolian
Hiragana
Katakana
Bopomofo
Han
Yi
OldItalic
Gothic
Deseret
Tagalog
Hanunoo
Buhid
Tagbanwa
Limbu
TaiLe
LinearB
Ugaritic
Shavian
Osmanya
Cypriot
Braille
Buginese
Coptic
NewTaiLue
Glagolitic
Tifinagh
SylotiNagri
OldPersian
Kharoshthi
Balinese
Cuneiform
Phoenician
PhagsPa
Definition at line 93 of file qunicodetables_p.h.
                 {
         Common,
         Greek,
         Cyrillic,
         Armenian,
         Hebrew,
         Arabic,
         Syriac,
         Thaana,
         Devanagari,
         Bengali,
         Gurmukhi,
         Gujarati,
         Oriya,
         Tamil,
         Telugu,
         Kannada,
         Malayalam,
         Sinhala,
         Thai,
         Lao,
         Tibetan,
         Myanmar,
         Georgian,
         Hangul,
         Ogham,
         Runic,
         Khmer,
         Nko,
         Inherited,
         ScriptCount = Inherited,
         Latin = Common,
         Ethiopic = Common,
         Cherokee = Common,
         CanadianAboriginal = Common,
         Mongolian = Common,
         Hiragana = Common,
         Katakana = Common,
         Bopomofo = Common,
         Han = Common,
         Yi = Common,
         OldItalic = Common,
         Gothic = Common,
         Deseret = Common,
         Tagalog = Common,
         Hanunoo = Common,
         Buhid = Common,
         Tagbanwa = Common,
         Limbu = Common,
         TaiLe = Common,
         LinearB = Common,
         Ugaritic = Common,
         Shavian = Common,
         Osmanya = Common,
         Cypriot = Common,
         Braille = Common,
         Buginese = Common,
         Coptic = Common,
         NewTaiLue = Common,
         Glagolitic = Common,
         Tifinagh = Common,
         SylotiNagri = Common,
         OldPersian = Common,
         Kharoshthi = Common,
         Balinese = Common,
         Cuneiform = Common,
         Phoenician = Common,
         PhagsPa = Common
     };
SentenceBreak
enum QUnicodeTables::SentenceBreak
Enumerator
SentenceBreakOther
SentenceBreakSep
SentenceBreakFormat
SentenceBreakSp
SentenceBreakLower
SentenceBreakUpper
SentenceBreakOLetter
SentenceBreakNumeric
SentenceBreakATerm
SentenceBreakSTerm
SentenceBreakClose
Definition at line 191 of file qunicodetables_p.h.
{
         SentenceBreakOther,
         SentenceBreakSep,
         SentenceBreakFormat,
         SentenceBreakSp,
         SentenceBreakLower,
         SentenceBreakUpper,
         SentenceBreakOLetter,
         SentenceBreakNumeric,
         SentenceBreakATerm,
         SentenceBreakSTerm,
         SentenceBreakClose
     };
WordBreak
enum QUnicodeTables::WordBreak
Enumerator
WordBreakOther
WordBreakFormat
WordBreakKatakana
WordBreakALetter
WordBreakMidLetter
WordBreakMidNum
WordBreakNumeric
WordBreakExtendNumLet
Definition at line 179 of file qunicodetables_p.h.
                    {
         WordBreakOther,
         WordBreakFormat,
         WordBreakKatakana,
         WordBreakALetter,
         WordBreakMidLetter,
         WordBreakMidNum,
         WordBreakNumeric,
         WordBreakExtendNumLet
     };
Function Documentation
lineBreakClass() [1/2]
Q_CORE_EXPORT QUnicodeTables::LineBreakClass QT_FASTCALL QUnicodeTables::lineBreakClass (uint ucs4)
Definition at line 4349 of file qunicodetables.cpp.
Referenced by HB_GetLineBreakClass(), and lineBreakClass().
 {
     return (QUnicodeTables::LineBreakClass)qGetProp(ucs4)->line_break_class;
 }
lineBreakClass() [2/2]
int QUnicodeTables::lineBreakClass (const QChar & ch) inline
Definition at line 221 of file qunicodetables_p.h.
     { return lineBreakClass(ch.unicode()); }
properties() [1/2]
Q_CORE_EXPORT const QUnicodeTables::Properties *QT_FASTCALL QUnicodeTables::properties (uint ucs4)
Definition at line 4337 of file qunicodetables.cpp.
Referenced by HB_GetGraphemeAndLineBreakClass(), HB_GetGraphemeClass(), HB_GetSentenceClass(), HB_GetUnicodeCharProperties(), HB_GetWordClass(), and heuristicSetGlyphAttributes().
 {
     int index = GET_PROP_INDEX(ucs4);
     return uc_properties + index;
 }
properties() [2/2]
Q_CORE_EXPORT const QUnicodeTables::Properties *QT_FASTCALL QUnicodeTables::properties (ushort ucs2)
Definition at line 4343 of file qunicodetables.cpp.
 {
     int index = GET_PROP_INDEX_UCS2(ucs2);
     return uc_properties + index;
 }
script() [1/2]
Q_CORE_EXPORT int QT_FASTCALL QUnicodeTables::script (uint ucs4)
Definition at line 9475 of file qunicodetables.cpp.
Referenced by addFontToDatabase(), QLocalePrivate::bcp47Name(), QFontMetrics::boundingRect(), QFontMetricsF::boundingRect(), QDeclarativeCompiler::buildSignal(), QLocale::c(), QFontMetrics::charWidth(), QDeclarativeListModelParser::compileProperty(), QDeclarativeCompiler::compileTree(), QDeclarativeGestureArea::connectSignals(), QDeclarativeConnections::connectSignals(), QLocalePrivate::countryId(), QLocalePrivate::digitToCLocale(), QDeclarativeTypeData::done(), findEncoding(), QFontDatabase::findFont(), QLocalePrivate::findLocale(), findLocale(), QTextEngine::fontEngine(), QRawFont::fromFont(), getFcPattern(), getMacLocaleName(), getWinLocaleName(), QDeclarativeWorkerScriptEnginePrivate::getWorker(), QFontMetrics::inFont(), QFontMetricsF::inFont(), QFontMetrics::inFontUcs4(), QFontMetricsF::inFontUcs4(), init(), QTextEngine::itemize(), QFontMetrics::leftBearing(), QFontMetricsF::leftBearing(), lineBreakClass(), load(), loadEngine(), loadWin(), QFontDatabase::loadXlfd(), QDeclarativeWorkerScriptEnginePrivate::onMessage(), QScriptAnalysis::operator==(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), QDeclarativeWorkerScriptEnginePrivate::processMessage(), registerFont(), QDeclarativeWorkerScriptEngine::registerWorkerScript(), QFontMetrics::rightBearing(), QFontMetricsF::rightBearing(), script(), QDeclarativeWorkerScriptEnginePrivate::sendMessage(), QFontComboBox::setWritingSystem(), QTextEngine::shapeText(), QSystemTrayIconPrivate::showMessage_sys(), storeFont(), QFontMetrics::width(), QFontMetricsF::width(), and QSystemLocalePrivate::winToQtFormat().
 {
     if (ucs4 > 0xffff)
         return Common;
     int script = uc_scripts[ucs4 >> 7];
     if (script < ScriptSentinel)
         return script;
     script = (((script - ScriptSentinel) * UnicodeBlockSize) + UnicodeBlockCount);
     script = uc_scripts[script + (ucs4 & 0x7f)];
     return script;
 }
script() [2/2]
int QUnicodeTables::script (const QChar & ch) inline
Definition at line 225 of file qunicodetables_p.h.
     { return script(ch.unicode()); }
Variable Documentation
uc_scripts
const unsigned char QUnicodeTables::uc_scripts[] static
Definition at line 8039 of file qunicodetables.cpp.
Referenced by script().