Qt 4.8: QDBusUtil Namespace Reference
QDBusUtil Namespace Reference
The QDBusUtil namespace contains a few functions that are of general use when dealing with D-Bus strings.
Enumerations
enum AllowEmptyFlag { EmptyAllowed, EmptyNotAllowed }
Functions
QString argumentToString (const QVariant &arg)
Dumps the contents of a QtDBus argument from arg into a string.
bool checkBusName (const QString &name, AllowEmptyFlag empty, QDBusError *error)
bool checkErrorName (const QString &name, AllowEmptyFlag empty, QDBusError *error)
bool checkInterfaceName (const QString &name, AllowEmptyFlag empty, QDBusError *error)
bool checkMemberName (const QString &name, AllowEmptyFlag empty, QDBusError *error, const char *nameType=0)
bool checkObjectPath (const QString &path, AllowEmptyFlag empty, QDBusError *error)
bool isValidBasicType (int c)
Returns true if c is a valid, basic D-Bus type.
bool isValidBusName (const QString &busName)
Returns true if busName is a valid bus name.
bool isValidErrorName (const QString &errorName)
Returns true if errorName is a valid error name.
bool isValidFixedType (int c)
Returns true if c is a valid, fixed D-Bus type.
bool isValidInterfaceName (const QString &ifaceName)
Returns true if this is ifaceName is a valid interface name.
bool isValidMemberName (const QString &memberName)
Returns true if memberName is a valid member name.
bool isValidObjectPath (const QString &path)
Returns true if path is valid object path.
bool isValidPartOfObjectPath (const QString &part)
bool isValidSignature (const QString &signature)
Returns true if signature is a valid D-Bus type signature for one or more types.
bool isValidSingleSignature (const QString &signature)
Returns true if signature is a valid D-Bus type signature for exactly one full type.
bool isValidUniqueConnectionName (const QString &connName)
Returns true if connName is a valid unique connection name.
Detailed Description
The QDBusUtil namespace contains a few functions that are of general use when dealing with D-Bus strings.
Attention
Module: QtDBus
Warning
This function is not part of the public interface.
Enumeration Type Documentation
AllowEmptyFlag
enum QDBusUtil::AllowEmptyFlag
Enumerator
EmptyAllowed
EmptyNotAllowed
Definition at line 94 of file qdbusutil_p.h.
{
         EmptyAllowed,
         EmptyNotAllowed
     };
Function Documentation
argumentToString()
Q_DBUS_EXPORT QString QDBusUtil::argumentToString (const QVariant & arg)
Dumps the contents of a QtDBus argument from arg into a string.
Warning
This function is not part of the public interface.
Since
4.5
Definition at line 324 of file qdbusutil.cpp.
Referenced by debugVariantList().
     {
         QString out;
         variantToString(arg, out);
         return out;
     }
checkBusName()
bool QDBusUtil::checkBusName (const QString & name, AllowEmptyFlag empty, QDBusError * error) inline
Definition at line 111 of file qdbusutil_p.h.
Referenced by QDBusAbstractInterfacePrivate::canMakeCalls(), checkIfValid(), and QDBusMessagePrivate::toDBusMessage().
     {
         if (name.isEmpty()) {
             if (empty == EmptyAllowed) return true;
             *error = QDBusError(QDBusError::InvalidService, QLatin1String("Service name cannot be empty"));
             return false;
         }
         if (isValidBusName(name)) return true;
         *error = QDBusError(QDBusError::InvalidService, QString::fromLatin1("Invalid service name: %1").arg(name));
         return false;
     }
checkErrorName()
bool QDBusUtil::checkErrorName (const QString & name, AllowEmptyFlag empty, QDBusError * error) inline
Definition at line 149 of file qdbusutil_p.h.
Referenced by QDBusMessagePrivate::toDBusMessage().
     {
         if (name.isEmpty()) {
             if (empty == EmptyAllowed) return true;
             *error = QDBusError(QDBusError::InvalidInterface, QLatin1String("Error name cannot be empty"));
             return false;
         }
         if (isValidErrorName(name)) return true;
         *error = QDBusError(QDBusError::InvalidInterface, QString::fromLatin1("Invalid error name: %1").arg(name));
         return false;
     }
checkInterfaceName()
bool QDBusUtil::checkInterfaceName (const QString & name, AllowEmptyFlag empty, QDBusError * error) inline
Definition at line 99 of file qdbusutil_p.h.
Referenced by checkIfValid(), and QDBusMessagePrivate::toDBusMessage().
     {
         if (name.isEmpty()) {
             if (empty == EmptyAllowed) return true;
             *error = QDBusError(QDBusError::InvalidInterface, QLatin1String("Interface name cannot be empty"));
             return false;
         }
         if (isValidInterfaceName(name)) return true;
         *error = QDBusError(QDBusError::InvalidInterface, QString::fromLatin1("Invalid interface class: %1").arg(name));
         return false;
     }
checkMemberName()
bool QDBusUtil::checkMemberName (const QString & name, AllowEmptyFlag empty, QDBusError * error, const char * nameType = 0) inline
Definition at line 135 of file qdbusutil_p.h.
Referenced by QDBusMessagePrivate::toDBusMessage().
     {
         if (!nameType) nameType = "member";
         if (name.isEmpty()) {
             if (empty == EmptyAllowed) return true;
             *error = QDBusError(QDBusError::InvalidMember, QLatin1String(nameType) + QLatin1String(" name cannot be empty"));
             return false;
         }
         if (isValidMemberName(name)) return true;
         *error = QDBusError(QDBusError::InvalidMember, QString::fromLatin1("Invalid %1 name: %2")
                             .arg(QString::fromLatin1(nameType), name));
         return false;
     }
checkObjectPath()
bool QDBusUtil::checkObjectPath (const QString & path, AllowEmptyFlag empty, QDBusError * error) inline
Definition at line 123 of file qdbusutil_p.h.
Referenced by QDBusAbstractInterfacePrivate::canMakeCalls(), checkIfValid(), and QDBusMessagePrivate::toDBusMessage().
     {
         if (path.isEmpty()) {
             if (empty == EmptyAllowed) return true;
             *error = QDBusError(QDBusError::InvalidObjectPath, QLatin1String("Object path cannot be empty"));
             return false;
         }
         if (isValidObjectPath(path)) return true;
         *error = QDBusError(QDBusError::InvalidObjectPath, QString::fromLatin1("Invalid object path: %1").arg(path));
         return false;
     }
isValidBasicType()
Q_DBUS_EXPORT bool QDBusUtil::isValidBasicType (int c)
Returns true if c is a valid, basic D-Bus type.
Definition at line 542 of file qdbusutil.cpp.
Referenced by QDBusMarshaller::appendCrossMarshalling(), and QDBusMarshaller::beginMap().
     {
         return isBasicType(c);
     }
isValidBusName()
Q_DBUS_EXPORT bool QDBusUtil::isValidBusName (const QString & busName)
Returns true if busName is a valid bus name.
A valid bus name is either a valid unique connection name or follows the rules:
is not empty
does not exceed 255 characters in length
be composed of dot-separated string components that contain only ASCII letters, digits, hyphens or underscores ("_"), but don't start with a digit
contains at least two such elements
See also
isValidUniqueConnectionName()
Definition at line 435 of file qdbusutil.cpp.
Referenced by checkBusName(), and QDBusConnection::connect().
     {
         if (busName.isEmpty() || busName.length() > DBUS_MAXIMUM_NAME_LENGTH)
             return false;
         if (busName.startsWith(QLatin1Char(':')))
             return isValidUniqueConnectionName(busName);
         QStringList parts = busName.split(QLatin1Char('.'));
         if (parts.count() < 1)
             return false;
         for (int i = 0; i < parts.count(); ++i) {
             const QString &part = parts.at(i);
             if (part.isEmpty())
                 return false;
             const QChar *c = part.unicode();
             if (isValidNumber(c[0]))
                 return false;
             for (int j = 0; j < part.length(); ++j)
                 if (!isValidCharacter(c[j]))
                     return false;
         }
         return true;
     }
isValidErrorName()
Q_DBUS_EXPORT bool QDBusUtil::isValidErrorName (const QString & errorName)
Returns true if errorName is a valid error name.
Valid error names are valid interface names and vice-versa, so this function is actually an alias for isValidInterfaceName.
Definition at line 494 of file qdbusutil.cpp.
Referenced by checkErrorName().
     {
         return isValidInterfaceName(errorName);
     }
isValidFixedType()
Q_DBUS_EXPORT bool QDBusUtil::isValidFixedType (int c)
Returns true if c is a valid, fixed D-Bus type.
Definition at line 554 of file qdbusutil.cpp.
Referenced by QDBusMarshaller::appendCrossMarshalling().
     {
         return isFixedType(c);
     }
isValidInterfaceName()
Q_DBUS_EXPORT bool QDBusUtil::isValidInterfaceName (const QString & ifaceName)
Returns true if this is ifaceName is a valid interface name.
Valid interface names must:
not be empty
not exceed 255 characters in length
be composed of dot-separated string components that contain only ASCII letters, digits and the underscore ("_") character
contain at least two such components
Definition at line 367 of file qdbusutil.cpp.
Referenced by checkInterfaceName(), QDBusConnection::connect(), QDBusConnection::disconnect(), QDBusXmlParser::interfaces(), isValidErrorName(), QDBusXmlParser::object(), and parseAnnotations().
     {
         if (ifaceName.isEmpty() || ifaceName.length() > DBUS_MAXIMUM_NAME_LENGTH)
             return false;
         QStringList parts = ifaceName.split(QLatin1Char('.'));
         if (parts.count() < 2)
             return false;           // at least two parts
         for (int i = 0; i < parts.count(); ++i)
             if (!isValidMemberName(parts.at(i)))
                 return false;
         return true;
     }
isValidMemberName()
Q_DBUS_EXPORT bool QDBusUtil::isValidMemberName (const QString & memberName)
Returns true if memberName is a valid member name.
A valid member name does not exceed 255 characters in length, is not empty, is composed only of ASCII letters, digits and underscores, but does not start with a digit.
Definition at line 472 of file qdbusutil.cpp.
Referenced by checkMemberName(), QDBusXmlParser::interfaces(), and isValidInterfaceName().
     {
         if (memberName.isEmpty() || memberName.length() > DBUS_MAXIMUM_NAME_LENGTH)
             return false;
         const QChar* c = memberName.unicode();
         if (isValidNumber(c[0]))
             return false;
         for (int j = 0; j < memberName.length(); ++j)
             if (!isValidCharacterNoDash(c[j]))
                 return false;
         return true;
     }
isValidObjectPath()
Q_DBUS_EXPORT bool QDBusUtil::isValidObjectPath (const QString & path)
Returns true if path is valid object path.
Valid object paths follow the rules:
start with the slash character ("/")
do not end in a slash, unless the path is just the initial slash
do not contain any two slashes in sequence
contain slash-separated parts, each of which is composed of ASCII letters, digits and underscores ("_")
Definition at line 515 of file qdbusutil.cpp.
Referenced by QDBusObjectPath::check(), checkObjectPath(), QDBusConnection::connect(), QDBusXmlParser::object(), QDBusConnection::objectRegisteredAt(), QDBusConnection::registerObject(), and QDBusConnection::unregisterObject().
     {
         if (path == QLatin1String("/"))
             return true;
         if (!path.startsWith(QLatin1Char('/')) || path.indexOf(QLatin1String("//")) != -1 ||
             path.endsWith(QLatin1Char('/')))
             return false;
         QStringList parts = path.split(QLatin1Char('/'));
         Q_ASSERT(parts.count() >= 1);
         parts.removeFirst();    // it starts with /, so we get an empty first part
         for (int i = 0; i < parts.count(); ++i)
             if (!isValidPartOfObjectPath(parts.at(i)))
                 return false;
         return true;
     }
isValidPartOfObjectPath()
Q_DBUS_EXPORT bool QDBusUtil::isValidPartOfObjectPath (const QString & part)
Warning
This function is not part of the public interface.
See QDBusUtil::isValidObjectPath
Definition at line 338 of file qdbusutil.cpp.
Referenced by generateSubObjectXml(), and isValidObjectPath().
     {
         if (part.isEmpty())
             return false;       // can't be valid if it's empty
         const QChar *c = part.unicode();
         for (int i = 0; i < part.length(); ++i)
             if (!isValidCharacterNoDash(c[i]))
                 return false;
         return true;
     }
isValidSignature()
Q_DBUS_EXPORT bool QDBusUtil::isValidSignature (const QString & signature)
Returns true if signature is a valid D-Bus type signature for one or more types.
This function returns true if it can all of signature into valid, individual types and no characters remain in signature.
See also
isValidSingleSignature()
Definition at line 571 of file qdbusutil.cpp.
Referenced by QDBusSignature::check().
     {
         QByteArray ba = signature.toLatin1();
         const char *data = ba.constData();
         while (true) {
             data = validateSingleType(data);
             if (!data)
                 return false;
             if (*data == '\0')
                 return true;
         }
     }
isValidSingleSignature()
Q_DBUS_EXPORT bool QDBusUtil::isValidSingleSignature (const QString & signature)
Returns true if signature is a valid D-Bus type signature for exactly one full type.
This function tries to convert the type signature into a D-Bus type and, if it succeeds and no characters remain in the signature, it returns true.
Definition at line 593 of file qdbusutil.cpp.
Referenced by QDBusArgumentPrivate::createSignature(), QDBusXmlParser::interfaces(), and parseArgs().
     {
         QByteArray ba = signature.toLatin1();
         const char *data = validateSingleType(ba.constData());
         return data && *data == '\0';
     }
isValidUniqueConnectionName()
Q_DBUS_EXPORT bool QDBusUtil::isValidUniqueConnectionName (const QString & connName)
Returns true if connName is a valid unique connection name.
Unique connection names start with a colon (":") and are followed by a list of dot-separated components composed of ASCII letters, digits, the hyphen or the underscore ("_") character.
Definition at line 393 of file qdbusutil.cpp.
Referenced by QDBusConnectionPrivate::getNameOwner(), and isValidBusName().
     {
         if (connName.isEmpty() || connName.length() > DBUS_MAXIMUM_NAME_LENGTH ||
             !connName.startsWith(QLatin1Char(':')))
             return false;
         QStringList parts = connName.mid(1).split(QLatin1Char('.'));
         if (parts.count() < 1)
             return false;
         for (int i = 0; i < parts.count(); ++i) {
             const QString &part = parts.at(i);
             if (part.isEmpty())
                  return false;
             const QChar* c = part.unicode();
             for (int j = 0; j < part.length(); ++j)
                 if (!isValidCharacter(c[j]))
                     return false;
         }
         return true;
     }