Qt 4.8: QDeclarativeJS::AST Namespace Reference
QDeclarativeJS::AST Namespace Reference
Classes
class ArgumentList
class ArrayLiteral
class ArrayMemberExpression
class BinaryExpression
class Block
class BreakStatement
class CallExpression
class CaseBlock
class CaseClause
class CaseClauses
class Catch
class ConditionalExpression
class ContinueStatement
class DebuggerStatement
class DefaultClause
class DeleteExpression
class DoWhileStatement
class ElementList
class Elision
class EmptyStatement
class Expression
class ExpressionNode
class ExpressionStatement
class FalseLiteral
class FieldMemberExpression
class Finally
class ForEachStatement
class FormalParameterList
class ForStatement
class FunctionBody
class FunctionDeclaration
class FunctionExpression
class FunctionSourceElement
class IdentifierExpression
class IdentifierPropertyName
class IfStatement
class LabelledStatement
class LocalForEachStatement
class LocalForStatement
class NestedExpression
class NewExpression
class NewMemberExpression
class Node
class NotExpression
class NullExpression
class NumericLiteral
class NumericLiteralPropertyName
class ObjectLiteral
class PostDecrementExpression
class PostIncrementExpression
class PreDecrementExpression
class PreIncrementExpression
class Program
class PropertyName
class PropertyNameAndValueList
class RegExpLiteral
class ReturnStatement
class SourceElement
class SourceElements
class SourceLocation
class Statement
class StatementList
class StatementSourceElement
class StringLiteral
class StringLiteralPropertyName
class SwitchStatement
class ThisExpression
class ThrowStatement
class TildeExpression
class TrueLiteral
class TryStatement
class TypeOfExpression
class UiArrayBinding
class UiArrayMemberList
class UiFormal
class UiFormalList
class UiImport
class UiImportList
class UiObjectBinding
class UiObjectDefinition
class UiObjectInitializer
class UiObjectMember
class UiObjectMemberList
class UiParameterList
class UiProgram
class UiPublicMember
class UiQualifiedId
class UiScriptBinding
class UiSignature
class UiSourceElement
class UnaryMinusExpression
class UnaryPlusExpression
class VariableDeclaration
class VariableDeclarationList
class VariableStatement
class Visitor
class VoidExpression
class WhileStatement
class WithStatement
Functions
template<typename _T1 , typename _T2 >
_T1 cast (_T2 *ast)
Function Documentation
cast()
template<typename _T1 , typename _T2 > _T1 QDeclarativeJS::AST::cast (_T2 * ast)
Definition at line 114 of file qdeclarativejsast_p.h.
Referenced by QDBusMarshaller::append(), QDeclarativePrivate::StaticCastSelector< From, To >::cast(), QPatternist::ComparingAggregator< oper, result >::evaluateSingleton(), QPatternist::NumberFN::evaluateSingleton(), QDeclarativeBoundSignal::isEvaluating(), PerformValueConstruction::operator()(), and QVariant::swap().
 {
     if (ast && ast->kind == static_cast<_T1>(0)->K)
         return static_cast<_T1>(ast);
     return 0;
 }