Qt 4.8: QDeclarativePrivate Namespace Reference
QDeclarativePrivate Namespace Reference
Classes
class AttachedPropertySelector
class AttachedPropertySelector< T, 1 >
struct has_attachedPropertiesMember
class has_attachedPropertiesMethod
class has_attachedPropertiesMethod< T, false >
class QDeclarativeElement
struct RegisterAutoParent
struct RegisterComponent
struct RegisterInterface
struct RegisterType
struct StaticCastSelector
struct StaticCastSelectorClass
struct StaticCastSelectorClass< From, To, sizeof(int)>
Typedefs
typedef AutoParentResult(* AutoParentFunction) (QObject *object, QObject *parent)
Enumerations
enum AutoParentResult { Parented, IncompatibleObject, IncompatibleParent }
enum RegistrationType { TypeRegistration = 0, InterfaceRegistration = 1, AutoParentRegistration = 2, ComponentRegistration = 3 }
Functions
template<typename T >
QDeclarativeAttachedPropertiesFunc attachedPropertiesFunc ()
template<typename T >
const QMetaObject * attachedPropertiesMetaObject ()
template<typename T >
void createInto (void *memory)
template<typename T >
QObject * createParent (QObject *p)
void Q_DECLARATIVE_EXPORT qdeclarativeelement_destructor (QObject *)
int Q_DECLARATIVE_EXPORT qmlregister (RegistrationType, void *)
int qmlRegisterType (const QUrl &url, const char *uri, int versionMajor, int versionMinor, const char *qmlName)
template<typename T , int metaObjectRevision>
int qmlRegisterUncreatableType (const char *uri, int versionMajor, int versionMinor, const char *qmlName, const QString &reason)
Typedef Documentation
AutoParentFunction
typedef AutoParentResult(* QDeclarativePrivate::AutoParentFunction) (QObject *object, QObject *parent)
Definition at line 194 of file qdeclarativeprivate.h.
Enumeration Type Documentation
AutoParentResult
enum QDeclarativePrivate::AutoParentResult
Enumerator
Parented
IncompatibleObject
IncompatibleParent
Definition at line 193 of file qdeclarativeprivate.h.
 { Parented, IncompatibleObject, IncompatibleParent };
RegistrationType
enum QDeclarativePrivate::RegistrationType
Enumerator
TypeRegistration
InterfaceRegistration
AutoParentRegistration
ComponentRegistration
Definition at line 249 of file qdeclarativeprivate.h.
{
         TypeRegistration       = 0,
         InterfaceRegistration  = 1,
         AutoParentRegistration = 2,
         ComponentRegistration  = 3
     };
Function Documentation
attachedPropertiesFunc()
template<typename T > QDeclarativeAttachedPropertiesFunc QDeclarativePrivate::attachedPropertiesFunc () inline
Definition at line 182 of file qdeclarativeprivate.h.
     {
         return AttachedPropertySelector<T, has_attachedPropertiesMethod<T, has_attachedPropertiesMember<T>::value>::value>::func();
     }
attachedPropertiesMetaObject()
template<typename T > const QMetaObject* QDeclarativePrivate::attachedPropertiesMetaObject () inline
Definition at line 188 of file qdeclarativeprivate.h.
Referenced by QDeclarativePrivate::AttachedPropertySelector< T, 1 >::metaObject().
     {
         return AttachedPropertySelector<T, has_attachedPropertiesMethod<T, has_attachedPropertiesMember<T>::value>::value>::metaObject();
     }
createInto()
template<typename T > void QDeclarativePrivate::createInto (void * memory)
Definition at line 96 of file qdeclarativeprivate.h.
 { new (memory) QDeclarativeElement<T>; }
createParent()
template<typename T > QObject* QDeclarativePrivate::createParent (QObject * p)
Definition at line 99 of file qdeclarativeprivate.h.
 { return new T(p); }
qdeclarativeelement_destructor()
void QDeclarativePrivate::qdeclarativeelement_destructor (QObject * o)
Definition at line 549 of file qdeclarativeengine.cpp.
Referenced by QDeclarativePrivate::QDeclarativeElement< T >::~QDeclarativeElement().
 {
     QObjectPrivate *p = QObjectPrivate::get(o);
     if (p->declarativeData) {
         QDeclarativeData *d = static_cast<QDeclarativeData*>(p->declarativeData);
         if (d->ownContext && d->context) {
             d->context->destroy();
             d->context = 0;
         }
         // Disconnect the notifiers now - during object destruction this would be too late, since
         // the disconnect call wouldn't be able to call disconnectNotify(), as it isn't possible to
         // get the metaobject anymore.
         d->disconnectNotifiers();
     }
 }
qmlregister()
int QDeclarativePrivate::qmlregister (RegistrationType type, void * data)
Definition at line 722 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeItemModule::defineModule(), qmlRegisterCustomType(), qmlRegisterExtendedType(), qmlRegisterInterface(), qmlRegisterRevision(), qmlRegisterType(), qmlRegisterType(), qmlRegisterUncreatableType(), qmlRegisterUncreatableType(), and qmlRegisterValueTypeEnums().
 {
     if (type == TypeRegistration) {
         return registerType(*reinterpret_cast<RegisterType *>(data));
     } else if (type == InterfaceRegistration) {
         return registerInterface(*reinterpret_cast<RegisterInterface *>(data));
     } else if (type == AutoParentRegistration) {
         return registerAutoParentFunction(*reinterpret_cast<RegisterAutoParent *>(data));
     } else if (type == ComponentRegistration) {
         return registerComponent(*reinterpret_cast<RegisterComponent *>(data));
     }
     return -1;
 }
qmlRegisterType()
int QDeclarativePrivate::qmlRegisterType (const QUrl & url, const char * uri, int versionMajor, int versionMinor, const char * qmlName) inline
Definition at line 274 of file qdeclarativeprivate.h.
     {
         RegisterComponent type = {
             url,
             uri,
             qmlName,
             versionMajor,
             versionMinor
         };
         return qmlregister(QDeclarativePrivate::ComponentRegistration, &type);
     }
qmlRegisterUncreatableType()
template<typename T , int metaObjectRevision> int QDeclarativePrivate::qmlRegisterUncreatableType (const char * uri, int versionMajor, int versionMinor, const char * qmlName, const QString & reason)
Definition at line 294 of file qdeclarativeprivate.h.
     {
         QByteArray name(T::staticMetaObject.className());
         QByteArray pointerName(name + '*');
         QByteArray listName("QDeclarativeListProperty<" + name + ">");
         QDeclarativePrivate::RegisterType type = {
             1,
             qRegisterMetaType<T *>(pointerName.constData()),
             qRegisterMetaType<QDeclarativeListProperty<T> >(listName.constData()),
             0, 0,
             reason,
             uri, versionMajor, versionMinor, qmlName, &T::staticMetaObject,
             QDeclarativePrivate::attachedPropertiesFunc<T>(),
             QDeclarativePrivate::attachedPropertiesMetaObject<T>(),
             QDeclarativePrivate::StaticCastSelector<T,QDeclarativeParserStatus>::cast(),
             QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueSource>::cast(),
             QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueInterceptor>::cast(),
             0, 0,
             0,
             metaObjectRevision
         };
         return QDeclarativePrivate::qmlregister(QDeclarativePrivate::TypeRegistration, &type);
     }