Qt 4.8: QCss Namespace Reference
QCss Namespace Reference
Classes
struct AttributeSelector
struct BackgroundData
struct BasicSelector
struct BorderData
struct BrushData
struct ColorData
struct Declaration
struct ImportRule
struct LengthData
struct MediaRule
struct PageRule
class Parser
struct Pseudo
class Scanner
struct Selector
struct StyleRule
class StyleSelector
struct StyleSheet
struct Symbol
struct Value
struct ValueExtractor
Enumerations
enum Attachment { Attachment_Unknown, Attachment_Fixed, Attachment_Scroll, NumKnownAttachments }
enum BorderStyle {
BorderStyle_Unknown, BorderStyle_None, BorderStyle_Dotted, BorderStyle_Dashed,
BorderStyle_Solid, BorderStyle_Double, BorderStyle_DotDash, BorderStyle_DotDotDash,
BorderStyle_Groove, BorderStyle_Ridge, BorderStyle_Inset, BorderStyle_Outset,
BorderStyle_Native, NumKnownBorderStyles
}
enum Corner { TopLeftCorner, TopRightCorner, BottomLeftCorner, BottomRightCorner }
enum Edge {
TopEdge, RightEdge, BottomEdge, LeftEdge,
NumEdges
}
enum KnownValue {
UnknownValue, Value_Normal, Value_Pre, Value_NoWrap,
Value_PreWrap, Value_Small, Value_Medium, Value_Large,
Value_XLarge, Value_XXLarge, Value_Italic, Value_Oblique,
Value_Bold, Value_Underline, Value_Overline, Value_LineThrough,
Value_Sub, Value_Super, Value_Left, Value_Right,
Value_Top, Value_Bottom, Value_Center, Value_Native,
Value_Solid, Value_Dotted, Value_Dashed, Value_DotDash,
Value_DotDotDash, Value_Double, Value_Groove, Value_Ridge,
Value_Inset, Value_Outset, Value_Wave, Value_Middle,
Value_Auto, Value_Always, Value_None, Value_Transparent,
Value_Disc, Value_Circle, Value_Square, Value_Decimal,
Value_LowerAlpha, Value_UpperAlpha, Value_LowerRoman, Value_UpperRoman,
Value_SmallCaps, Value_Uppercase, Value_Lowercase, Value_FirstColorRole,
Value_WindowText = Value_FirstColorRole, Value_Button, Value_Light, Value_Midlight,
Value_Dark, Value_Mid, Value_Text, Value_BrightText,
Value_ButtonText, Value_Base, Value_Window, Value_Shadow,
Value_Highlight, Value_HighlightedText, Value_Link, Value_LinkVisited,
Value_AlternateBase, Value_LastColorRole = Value_AlternateBase, Value_Disabled, Value_Active,
Value_Selected, Value_On, Value_Off, NumKnownValues
}
enum Origin {
Origin_Unknown, Origin_Padding, Origin_Border, Origin_Content,
Origin_Margin, NumKnownOrigins
}
enum PositionMode {
PositionMode_Unknown, PositionMode_Static, PositionMode_Relative, PositionMode_Absolute,
PositionMode_Fixed, NumKnownPositionModes
}
enum Property {
UnknownProperty, BackgroundColor, Color, Float,
Font, FontFamily, FontSize, FontStyle,
FontWeight, Margin, MarginBottom, MarginLeft,
MarginRight, MarginTop, QtBlockIndent, QtListIndent,
QtParagraphType, QtTableType, QtUserState, TextDecoration,
TextIndent, TextUnderlineStyle, VerticalAlignment, Whitespace,
QtSelectionForeground, QtSelectionBackground, Border, BorderLeft,
BorderRight, BorderTop, BorderBottom, Padding,
PaddingLeft, PaddingRight, PaddingTop, PaddingBottom,
PageBreakBefore, PageBreakAfter, QtAlternateBackground, BorderLeftStyle,
BorderRightStyle, BorderTopStyle, BorderBottomStyle, BorderStyles,
BorderLeftColor, BorderRightColor, BorderTopColor, BorderBottomColor,
BorderColor, BorderLeftWidth, BorderRightWidth, BorderTopWidth,
BorderBottomWidth, BorderWidth, BorderTopLeftRadius, BorderTopRightRadius,
BorderBottomLeftRadius, BorderBottomRightRadius, BorderRadius, Background,
BackgroundOrigin, BackgroundClip, BackgroundRepeat, BackgroundPosition,
BackgroundAttachment, BackgroundImage, BorderImage, QtSpacing,
Width, Height, MinimumWidth, MinimumHeight,
MaximumWidth, MaximumHeight, QtImage, Left,
Right, Top, Bottom, QtOrigin,
QtPosition, Position, QtStyleFeatures, QtBackgroundRole,
ListStyleType, ListStyle, QtImageAlignment, TextAlignment,
Outline, OutlineOffset, OutlineWidth, OutlineColor,
OutlineStyle, OutlineRadius, OutlineTopLeftRadius, OutlineTopRightRadius,
OutlineBottomLeftRadius, OutlineBottomRightRadius, FontVariant, TextTransform,
QtListNumberPrefix, QtListNumberSuffix, LineHeight, NumProperties
}
enum Repeat {
Repeat_Unknown, Repeat_None, Repeat_X, Repeat_Y,
Repeat_XY, NumKnownRepeats
}
enum StyleFeature { StyleFeature_None = 0, StyleFeature_BackgroundColor = 1, StyleFeature_BackgroundGradient = 2, NumKnownStyleFeatures = 4 }
enum StyleSheetOrigin {
StyleSheetOrigin_Unspecified, StyleSheetOrigin_UserAgent, StyleSheetOrigin_User, StyleSheetOrigin_Author,
StyleSheetOrigin_Inline
}
enum TileMode {
TileMode_Unknown, TileMode_Round, TileMode_Stretch, TileMode_Repeat,
NumKnownTileModes
}
enum TokenType {
NONE, S, CDO, CDC,
INCLUDES, DASHMATCH, LBRACE, PLUS,
GREATER, COMMA, STRING, INVALID,
IDENT, HASH, ATKEYWORD_SYM, EXCLAMATION_SYM,
LENGTH, PERCENTAGE, NUMBER, FUNCTION,
COLON, SEMICOLON, RBRACE, SLASH,
MINUS, DOT, STAR, LBRACKET,
RBRACKET, EQUAL, LPAREN, RPAREN,
OR
}
Variables
const int NumPseudos = 46
const quint64 PseudoClass_Active = Q_UINT64_C(0x0000000080000000)
const quint64 PseudoClass_Alternate = Q_UINT64_C(0x0000100000000000)
const quint64 PseudoClass_Any = Q_UINT64_C(0x0000ffffffffffff)
const quint64 PseudoClass_Bottom = Q_UINT64_C(0x0000000004000000)
const quint64 PseudoClass_Checked = Q_UINT64_C(0x0000000000000020)
const quint64 PseudoClass_Children = Q_UINT64_C(0x0000000000002000)
const quint64 PseudoClass_Closable = Q_UINT64_C(0x0000000100000000)
const quint64 PseudoClass_Closed = Q_UINT64_C(0x0000020000000000)
const quint64 PseudoClass_Default = Q_UINT64_C(0x0000000000008000)
const quint64 PseudoClass_Disabled = Q_UINT64_C(0x0000000000000002)
const quint64 PseudoClass_Editable = Q_UINT64_C(0x0000008000000000)
const quint64 PseudoClass_EditFocus = Q_UINT64_C(0x0000080000000000)
const quint64 PseudoClass_Enabled = Q_UINT64_C(0x0000000000000001)
const quint64 PseudoClass_Exclusive = Q_UINT64_C(0x0000000008000000)
const quint64 PseudoClass_First = Q_UINT64_C(0x0000000000010000)
const quint64 PseudoClass_Flat = Q_UINT64_C(0x0000000000400000)
const quint64 PseudoClass_Floatable = Q_UINT64_C(0x0000000400000000)
const quint64 PseudoClass_Focus = Q_UINT64_C(0x0000000000000008)
const quint64 PseudoClass_Frameless = Q_UINT64_C(0x0000000020000000)
const quint64 PseudoClass_Horizontal = Q_UINT64_C(0x0000000000000400)
const quint64 PseudoClass_Hover = Q_UINT64_C(0x0000000000000010)
const quint64 PseudoClass_Indeterminate = Q_UINT64_C(0x0000000000000080)
const quint64 PseudoClass_Item = Q_UINT64_C(0x0000010000000000)
const quint64 PseudoClass_Last = Q_UINT64_C(0x0000000000020000)
const quint64 PseudoClass_Left = Q_UINT64_C(0x0000000000800000)
const quint64 PseudoClass_Maximized = Q_UINT64_C(0x0000001000000000)
const quint64 PseudoClass_Middle = Q_UINT64_C(0x0000000000040000)
const quint64 PseudoClass_Minimized = Q_UINT64_C(0x0000000800000000)
const quint64 PseudoClass_Movable = Q_UINT64_C(0x0000000200000000)
const quint64 PseudoClass_NextSelected = Q_UINT64_C(0x0000000000200000)
const quint64 PseudoClass_NonExclusive = Q_UINT64_C(0x0000000010000000)
const quint64 PseudoClass_Off = Q_UINT64_C(0x0000004000000000)
const quint64 PseudoClass_On = Q_UINT64_C(0x0000002000000000)
const quint64 PseudoClass_OnlyOne = Q_UINT64_C(0x0000000000080000)
const quint64 PseudoClass_Open = Q_UINT64_C(0x0000040000000000)
const quint64 PseudoClass_Pressed = Q_UINT64_C(0x0000000000000004)
const quint64 PseudoClass_PreviousSelected = Q_UINT64_C(0x0000000000100000)
const quint64 PseudoClass_ReadOnly = Q_UINT64_C(0x0000000040000000)
const quint64 PseudoClass_Right = Q_UINT64_C(0x0000000001000000)
const quint64 PseudoClass_Selected = Q_UINT64_C(0x0000000000000200)
const quint64 PseudoClass_Sibling = Q_UINT64_C(0x0000000000004000)
const quint64 PseudoClass_Top = Q_UINT64_C(0x0000000002000000)
const quint64 PseudoClass_Unchecked = Q_UINT64_C(0x0000000000000040)
const quint64 PseudoClass_Unknown = Q_UINT64_C(0x0000000000000000)
const quint64 PseudoClass_Unspecified = Q_UINT64_C(0x0000000000000100)
const quint64 PseudoClass_Vertical = Q_UINT64_C(0x0000000000000800)
const quint64 PseudoClass_Window = Q_UINT64_C(0x0000000000001000)
Enumeration Type Documentation
Attachment
enum QCss::Attachment
Enumerator
Attachment_Unknown
Attachment_Fixed
Attachment_Scroll
NumKnownAttachments
Definition at line 340 of file qcssparser_p.h.
                 {
     Attachment_Unknown,
     Attachment_Fixed,
     Attachment_Scroll,
     NumKnownAttachments
 };
BorderStyle
enum QCss::BorderStyle
Enumerator
BorderStyle_Unknown
BorderStyle_None
BorderStyle_Dotted
BorderStyle_Dashed
BorderStyle_Solid
BorderStyle_Double
BorderStyle_DotDash
BorderStyle_DotDotDash
BorderStyle_Groove
BorderStyle_Ridge
BorderStyle_Inset
BorderStyle_Outset
BorderStyle_Native
NumKnownBorderStyles
Definition at line 273 of file qcssparser_p.h.
                  {
     BorderStyle_Unknown,
     BorderStyle_None,
     BorderStyle_Dotted,
     BorderStyle_Dashed,
     BorderStyle_Solid,
     BorderStyle_Double,
     BorderStyle_DotDash,
     BorderStyle_DotDotDash,
     BorderStyle_Groove,
     BorderStyle_Ridge,
     BorderStyle_Inset,
     BorderStyle_Outset,
     BorderStyle_Native,
     NumKnownBorderStyles
 };
Corner
enum QCss::Corner
Enumerator
TopLeftCorner
TopRightCorner
BottomLeftCorner
BottomRightCorner
Definition at line 298 of file qcssparser_p.h.
             {
     TopLeftCorner,
     TopRightCorner,
     BottomLeftCorner,
     BottomRightCorner
 };
Edge
enum QCss::Edge
Enumerator
TopEdge
RightEdge
BottomEdge
LeftEdge
NumEdges
Definition at line 290 of file qcssparser_p.h.
           {
     TopEdge,
     RightEdge,
     BottomEdge,
     LeftEdge,
     NumEdges
 };
KnownValue
enum QCss::KnownValue
Enumerator
UnknownValue
Value_Normal
Value_Pre
Value_NoWrap
Value_PreWrap
Value_Small
Value_Medium
Value_Large
Value_XLarge
Value_XXLarge
Value_Italic
Value_Oblique
Value_Bold
Value_Underline
Value_Overline
Value_LineThrough
Value_Sub
Value_Super
Value_Left
Value_Right
Value_Top
Value_Bottom
Value_Center
Value_Native
Value_Solid
Value_Dotted
Value_Dashed
Value_DotDash
Value_DotDotDash
Value_Double
Value_Groove
Value_Ridge
Value_Inset
Value_Outset
Value_Wave
Value_Middle
Value_Auto
Value_Always
Value_None
Value_Transparent
Value_Disc
Value_Circle
Value_Square
Value_Decimal
Value_LowerAlpha
Value_UpperAlpha
Value_LowerRoman
Value_UpperRoman
Value_SmallCaps
Value_Uppercase
Value_Lowercase
Value_FirstColorRole
Value_WindowText
Value_Button
Value_Light
Value_Midlight
Value_Dark
Value_Mid
Value_Text
Value_BrightText
Value_ButtonText
Value_Base
Value_Window
Value_Shadow
Value_Highlight
Value_HighlightedText
Value_Link
Value_LinkVisited
Value_AlternateBase
Value_LastColorRole
Value_Disabled
Value_Active
Value_Selected
Value_On
Value_Off
NumKnownValues
Definition at line 190 of file qcssparser_p.h.
                 {
     UnknownValue,
     Value_Normal,
     Value_Pre,
     Value_NoWrap,
     Value_PreWrap,
     Value_Small,
     Value_Medium,
     Value_Large,
     Value_XLarge,
     Value_XXLarge,
     Value_Italic,
     Value_Oblique,
     Value_Bold,
     Value_Underline,
     Value_Overline,
     Value_LineThrough,
     Value_Sub,
     Value_Super,
     Value_Left,
     Value_Right,
     Value_Top,
     Value_Bottom,
     Value_Center,
     Value_Native,
     Value_Solid,
     Value_Dotted,
     Value_Dashed,
     Value_DotDash,
     Value_DotDotDash,
     Value_Double,
     Value_Groove,
     Value_Ridge,
     Value_Inset,
     Value_Outset,
     Value_Wave,
     Value_Middle,
     Value_Auto,
     Value_Always,
     Value_None,
     Value_Transparent,
     Value_Disc,
     Value_Circle,
     Value_Square,
     Value_Decimal,
     Value_LowerAlpha,
     Value_UpperAlpha,
     Value_LowerRoman,
     Value_UpperRoman,
     Value_SmallCaps,
     Value_Uppercase,
     Value_Lowercase,
     /* keep these in same order as QPalette::ColorRole */
     Value_FirstColorRole,
     Value_WindowText = Value_FirstColorRole,
     Value_Button,
     Value_Light,
     Value_Midlight,
     Value_Dark,
     Value_Mid,
     Value_Text,
     Value_BrightText,
     Value_ButtonText,
     Value_Base,
     Value_Window,
     Value_Shadow,
     Value_Highlight,
     Value_HighlightedText,
     Value_Link,
     Value_LinkVisited,
     Value_AlternateBase,
     Value_LastColorRole = Value_AlternateBase,
     Value_Disabled,
     Value_Active,
     Value_Selected,
     Value_On,
     Value_Off,
     NumKnownValues
 };
Origin
enum QCss::Origin
Enumerator
Origin_Unknown
Origin_Padding
Origin_Border
Origin_Content
Origin_Margin
NumKnownOrigins
Definition at line 322 of file qcssparser_p.h.
             {
     Origin_Unknown,
     Origin_Padding,
     Origin_Border,
     Origin_Content,
     Origin_Margin,
     NumKnownOrigins
 };
PositionMode
enum QCss::PositionMode
Enumerator
PositionMode_Unknown
PositionMode_Static
PositionMode_Relative
PositionMode_Absolute
PositionMode_Fixed
NumKnownPositionModes
Definition at line 331 of file qcssparser_p.h.
                   {
     PositionMode_Unknown,
     PositionMode_Static,
     PositionMode_Relative,
     PositionMode_Absolute,
     PositionMode_Fixed,
     NumKnownPositionModes
 };
Property
enum QCss::Property
Enumerator
UnknownProperty
BackgroundColor
Color
Float
Font
FontFamily
FontSize
FontStyle
FontWeight
Margin
MarginBottom
MarginLeft
MarginRight
MarginTop
QtBlockIndent
QtListIndent
QtParagraphType
QtTableType
QtUserState
TextDecoration
TextIndent
TextUnderlineStyle
VerticalAlignment
Whitespace
QtSelectionForeground
QtSelectionBackground
Border
BorderLeft
BorderRight
BorderTop
BorderBottom
Padding
PaddingLeft
PaddingRight
PaddingTop
PaddingBottom
PageBreakBefore
PageBreakAfter
QtAlternateBackground
BorderLeftStyle
BorderRightStyle
BorderTopStyle
BorderBottomStyle
BorderStyles
BorderLeftColor
BorderRightColor
BorderTopColor
BorderBottomColor
BorderColor
BorderLeftWidth
BorderRightWidth
BorderTopWidth
BorderBottomWidth
BorderWidth
BorderTopLeftRadius
BorderTopRightRadius
BorderBottomLeftRadius
BorderBottomRightRadius
BorderRadius
Background
BackgroundOrigin
BackgroundClip
BackgroundRepeat
BackgroundPosition
BackgroundAttachment
BackgroundImage
BorderImage
QtSpacing
Width
Height
MinimumWidth
MinimumHeight
MaximumWidth
MaximumHeight
QtImage
Left
Right
Top
Bottom
QtOrigin
QtPosition
Position
QtStyleFeatures
QtBackgroundRole
ListStyleType
ListStyle
QtImageAlignment
TextAlignment
Outline
OutlineOffset
OutlineWidth
OutlineColor
OutlineStyle
OutlineRadius
OutlineTopLeftRadius
OutlineTopRightRadius
OutlineBottomLeftRadius
OutlineBottomRightRadius
FontVariant
TextTransform
QtListNumberPrefix
QtListNumberSuffix
LineHeight
NumProperties
Definition at line 83 of file qcssparser_p.h.
               {
     UnknownProperty,
     BackgroundColor,
     Color,
     Float,
     Font,
     FontFamily,
     FontSize,
     FontStyle,
     FontWeight,
     Margin,
     MarginBottom,
     MarginLeft,
     MarginRight,
     MarginTop,
     QtBlockIndent,
     QtListIndent,
     QtParagraphType,
     QtTableType,
     QtUserState,
     TextDecoration,
     TextIndent,
     TextUnderlineStyle,
     VerticalAlignment,
     Whitespace,
     QtSelectionForeground,
     QtSelectionBackground,
     Border,
     BorderLeft,
     BorderRight,
     BorderTop,
     BorderBottom,
     Padding,
     PaddingLeft,
     PaddingRight,
     PaddingTop,
     PaddingBottom,
     PageBreakBefore,
     PageBreakAfter,
     QtAlternateBackground,
     BorderLeftStyle,
     BorderRightStyle,
     BorderTopStyle,
     BorderBottomStyle,
     BorderStyles,
     BorderLeftColor,
     BorderRightColor,
     BorderTopColor,
     BorderBottomColor,
     BorderColor,
     BorderLeftWidth,
     BorderRightWidth,
     BorderTopWidth,
     BorderBottomWidth,
     BorderWidth,
     BorderTopLeftRadius,
     BorderTopRightRadius,
     BorderBottomLeftRadius,
     BorderBottomRightRadius,
     BorderRadius,
     Background,
     BackgroundOrigin,
     BackgroundClip,
     BackgroundRepeat,
     BackgroundPosition,
     BackgroundAttachment,
     BackgroundImage,
     BorderImage,
     QtSpacing,
     Width,
     Height,
     MinimumWidth,
     MinimumHeight,
     MaximumWidth,
     MaximumHeight,
     QtImage,
     Left,
     Right,
     Top,
     Bottom,
     QtOrigin,
     QtPosition,
     Position,
     QtStyleFeatures,
     QtBackgroundRole,
     ListStyleType,
     ListStyle,
     QtImageAlignment,
     TextAlignment,
     Outline,
     OutlineOffset,
     OutlineWidth,
     OutlineColor,
     OutlineStyle,
     OutlineRadius,
     OutlineTopLeftRadius,
     OutlineTopRightRadius,
     OutlineBottomLeftRadius,
     OutlineBottomRightRadius,
     FontVariant,
     TextTransform,
     QtListNumberPrefix,
     QtListNumberSuffix,
     LineHeight,
     NumProperties
 };
Repeat
enum QCss::Repeat
Enumerator
Repeat_Unknown
Repeat_None
Repeat_X
Repeat_Y
Repeat_XY
NumKnownRepeats
Definition at line 313 of file qcssparser_p.h.
             {
     Repeat_Unknown,
     Repeat_None,
     Repeat_X,
     Repeat_Y,
     Repeat_XY,
     NumKnownRepeats
 };
StyleFeature
enum QCss::StyleFeature
Enumerator
StyleFeature_None
StyleFeature_BackgroundColor
StyleFeature_BackgroundGradient
NumKnownStyleFeatures
Definition at line 347 of file qcssparser_p.h.
                   {
     StyleFeature_None = 0,
     StyleFeature_BackgroundColor = 1,
     StyleFeature_BackgroundGradient = 2,
     NumKnownStyleFeatures = 4
 };
StyleSheetOrigin
enum QCss::StyleSheetOrigin
Enumerator
StyleSheetOrigin_Unspecified
StyleSheetOrigin_UserAgent
StyleSheetOrigin_User
StyleSheetOrigin_Author
StyleSheetOrigin_Inline
Definition at line 628 of file qcssparser_p.h.
                       {
     StyleSheetOrigin_Unspecified,
     StyleSheetOrigin_UserAgent,
     StyleSheetOrigin_User,
     StyleSheetOrigin_Author,
     StyleSheetOrigin_Inline
 };
TileMode
enum QCss::TileMode
Enumerator
TileMode_Unknown
TileMode_Round
TileMode_Stretch
TileMode_Repeat
NumKnownTileModes
Definition at line 305 of file qcssparser_p.h.
               {
     TileMode_Unknown,
     TileMode_Round,
     TileMode_Stretch,
     TileMode_Repeat,
     NumKnownTileModes
 };
TokenType
enum QCss::TokenType
Enumerator
NONE
S
CDO
CDC
INCLUDES
DASHMATCH
LBRACE
PLUS
GREATER
COMMA
STRING
INVALID
IDENT
HASH
ATKEYWORD_SYM
EXCLAMATION_SYM
LENGTH
PERCENTAGE
NUMBER
FUNCTION
COLON
SEMICOLON
RBRACE
SLASH
MINUS
DOT
STAR
LBRACKET
RBRACKET
EQUAL
LPAREN
RPAREN
OR
Definition at line 685 of file qcssparser_p.h.
                {
     NONE,
     S,
     CDO,
     CDC,
     INCLUDES,
     DASHMATCH,
     LBRACE,
     PLUS,
     GREATER,
     COMMA,
     STRING,
     INVALID,
     IDENT,
     HASH,
     ATKEYWORD_SYM,
     EXCLAMATION_SYM,
     LENGTH,
     PERCENTAGE,
     NUMBER,
     FUNCTION,
     COLON,
     SEMICOLON,
     RBRACE,
     SLASH,
     MINUS,
     DOT,
     STAR,
     LBRACKET,
     RBRACKET,
     EQUAL,
     LPAREN,
     RPAREN,
     OR
 };
Variable Documentation
NumPseudos
const int QCss::NumPseudos = 46
Definition at line 509 of file qcssparser_p.h.
PseudoClass_Active
const quint64 QCss::PseudoClass_Active = Q_UINT64_C(0x0000000080000000)
Definition at line 493 of file qcssparser_p.h.
Referenced by pseudoClass(), QStyleSheetStyle::setPalette(), and QStyleSheetStyle::updateStyleSheetFont().
PseudoClass_Alternate
const quint64 QCss::PseudoClass_Alternate = Q_UINT64_C(0x0000100000000000)
Definition at line 506 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Any
const quint64 QCss::PseudoClass_Any = Q_UINT64_C(0x0000ffffffffffff)
Definition at line 508 of file qcssparser_p.h.
Referenced by declarations(), QStyleSheetStyle::drawControl(), and QStyleSheetStyle::polish().
PseudoClass_Bottom
const quint64 QCss::PseudoClass_Bottom = Q_UINT64_C(0x0000000004000000)
Definition at line 488 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Checked
const quint64 QCss::PseudoClass_Checked = Q_UINT64_C(0x0000000000000020)
Definition at line 467 of file qcssparser_p.h.
Referenced by pseudoClass(), and QStyleSheetStyle::renderRule().
PseudoClass_Children
const quint64 QCss::PseudoClass_Children = Q_UINT64_C(0x0000000000002000)
Definition at line 475 of file qcssparser_p.h.
Referenced by pseudoClass().
PseudoClass_Closable
const quint64 QCss::PseudoClass_Closable = Q_UINT64_C(0x0000000100000000)
Definition at line 494 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Closed
const quint64 QCss::PseudoClass_Closed = Q_UINT64_C(0x0000020000000000)
Definition at line 503 of file qcssparser_p.h.
Referenced by pseudoClass().
PseudoClass_Default
const quint64 QCss::PseudoClass_Default = Q_UINT64_C(0x0000000000008000)
Definition at line 477 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Disabled
const quint64 QCss::PseudoClass_Disabled = Q_UINT64_C(0x0000000000000002)
Definition at line 463 of file qcssparser_p.h.
Referenced by pseudoClass(), and QStyleSheetStyle::setPalette().
PseudoClass_Editable
const quint64 QCss::PseudoClass_Editable = Q_UINT64_C(0x0000008000000000)
Definition at line 501 of file qcssparser_p.h.
Referenced by extendedPseudoClass(), and QStyleSheetStyle::renderRule().
PseudoClass_EditFocus
const quint64 QCss::PseudoClass_EditFocus = Q_UINT64_C(0x0000080000000000)
Definition at line 505 of file qcssparser_p.h.
Referenced by pseudoClass().
PseudoClass_Enabled
const quint64 QCss::PseudoClass_Enabled = Q_UINT64_C(0x0000000000000001)
Definition at line 462 of file qcssparser_p.h.
Referenced by QCss::StyleSelector::declarationsForNode(), QStyleSheetStyle::polish(), pseudoClass(), QStyleSheetStyle::setGeometry(), QStyleSheetStyle::setPalette(), and QStyleSheetStyle::updateStyleSheetFont().
PseudoClass_Exclusive
const quint64 QCss::PseudoClass_Exclusive = Q_UINT64_C(0x0000000008000000)
Definition at line 489 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_First
const quint64 QCss::PseudoClass_First = Q_UINT64_C(0x0000000000010000)
Definition at line 478 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Flat
const quint64 QCss::PseudoClass_Flat = Q_UINT64_C(0x0000000000400000)
Definition at line 484 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Floatable
const quint64 QCss::PseudoClass_Floatable = Q_UINT64_C(0x0000000400000000)
Definition at line 496 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Focus
const quint64 QCss::PseudoClass_Focus = Q_UINT64_C(0x0000000000000008)
Definition at line 465 of file qcssparser_p.h.
Referenced by pseudoClass().
PseudoClass_Frameless
const quint64 QCss::PseudoClass_Frameless = Q_UINT64_C(0x0000000020000000)
Definition at line 491 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::getDefaultStyleSheet(), and QStyleSheetStyle::renderRule().
PseudoClass_Horizontal
const quint64 QCss::PseudoClass_Horizontal = Q_UINT64_C(0x0000000000000400)
Definition at line 472 of file qcssparser_p.h.
Referenced by extendedPseudoClass(), pseudoClass(), and QStyleSheetStyle::renderRule().
PseudoClass_Hover
const quint64 QCss::PseudoClass_Hover = Q_UINT64_C(0x0000000000000010)
Definition at line 466 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::polish(), and pseudoClass().
PseudoClass_Indeterminate
const quint64 QCss::PseudoClass_Indeterminate = Q_UINT64_C(0x0000000000000080)
Definition at line 469 of file qcssparser_p.h.
Referenced by pseudoClass().
PseudoClass_Item
const quint64 QCss::PseudoClass_Item = Q_UINT64_C(0x0000010000000000)
Definition at line 502 of file qcssparser_p.h.
Referenced by pseudoClass().
PseudoClass_Last
const quint64 QCss::PseudoClass_Last = Q_UINT64_C(0x0000000000020000)
Definition at line 479 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Left
const quint64 QCss::PseudoClass_Left = Q_UINT64_C(0x0000000000800000)
Definition at line 485 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Maximized
const quint64 QCss::PseudoClass_Maximized = Q_UINT64_C(0x0000001000000000)
Definition at line 498 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Middle
const quint64 QCss::PseudoClass_Middle = Q_UINT64_C(0x0000000000040000)
Definition at line 480 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Minimized
const quint64 QCss::PseudoClass_Minimized = Q_UINT64_C(0x0000000800000000)
Definition at line 497 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::pixelMetric(), and QStyleSheetStyle::renderRule().
PseudoClass_Movable
const quint64 QCss::PseudoClass_Movable = Q_UINT64_C(0x0000000200000000)
Definition at line 495 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_NextSelected
const quint64 QCss::PseudoClass_NextSelected = Q_UINT64_C(0x0000000000200000)
Definition at line 483 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_NonExclusive
const quint64 QCss::PseudoClass_NonExclusive = Q_UINT64_C(0x0000000010000000)
Definition at line 490 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Off
const quint64 QCss::PseudoClass_Off = Q_UINT64_C(0x0000004000000000)
Definition at line 500 of file qcssparser_p.h.
Referenced by pseudoClass(), and QStyleSheetStyle::renderRule().
PseudoClass_On
const quint64 QCss::PseudoClass_On = Q_UINT64_C(0x0000002000000000)
Definition at line 499 of file qcssparser_p.h.
Referenced by pseudoClass(), and QStyleSheetStyle::renderRule().
PseudoClass_OnlyOne
const quint64 QCss::PseudoClass_OnlyOne = Q_UINT64_C(0x0000000000080000)
Definition at line 481 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Open
const quint64 QCss::PseudoClass_Open = Q_UINT64_C(0x0000040000000000)
Definition at line 504 of file qcssparser_p.h.
Referenced by pseudoClass().
PseudoClass_Pressed
const quint64 QCss::PseudoClass_Pressed = Q_UINT64_C(0x0000000000000004)
Definition at line 464 of file qcssparser_p.h.
Referenced by pseudoClass().
PseudoClass_PreviousSelected
const quint64 QCss::PseudoClass_PreviousSelected = Q_UINT64_C(0x0000000000100000)
Definition at line 482 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_ReadOnly
const quint64 QCss::PseudoClass_ReadOnly = Q_UINT64_C(0x0000000040000000)
Definition at line 492 of file qcssparser_p.h.
Referenced by extendedPseudoClass(), pseudoClass(), and QStyleSheetStyle::renderRule().
PseudoClass_Right
const quint64 QCss::PseudoClass_Right = Q_UINT64_C(0x0000000001000000)
Definition at line 486 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Selected
const quint64 QCss::PseudoClass_Selected = Q_UINT64_C(0x0000000000000200)
Definition at line 471 of file qcssparser_p.h.
Referenced by pseudoClass().
PseudoClass_Sibling
const quint64 QCss::PseudoClass_Sibling = Q_UINT64_C(0x0000000000004000)
Definition at line 476 of file qcssparser_p.h.
Referenced by pseudoClass().
PseudoClass_Top
const quint64 QCss::PseudoClass_Top = Q_UINT64_C(0x0000000002000000)
Definition at line 487 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::renderRule().
PseudoClass_Unchecked
const quint64 QCss::PseudoClass_Unchecked = Q_UINT64_C(0x0000000000000040)
Definition at line 468 of file qcssparser_p.h.
Referenced by pseudoClass(), and QStyleSheetStyle::renderRule().
PseudoClass_Unknown
const quint64 QCss::PseudoClass_Unknown = Q_UINT64_C(0x0000000000000000)
Definition at line 461 of file qcssparser_p.h.
Referenced by QStyleSheetStyle::getDefaultStyleSheet(), QCss::Selector::pseudoClass(), and QCss::Selector::pseudoElement().
PseudoClass_Unspecified
const quint64 QCss::PseudoClass_Unspecified = Q_UINT64_C(0x0000000000000100)
Definition at line 470 of file qcssparser_p.h.
Referenced by declarations(), QCss::StyleSelector::declarationsForNode(), and QCss::Selector::pseudoClass().
PseudoClass_Vertical
const quint64 QCss::PseudoClass_Vertical = Q_UINT64_C(0x0000000000000800)
Definition at line 473 of file qcssparser_p.h.
Referenced by extendedPseudoClass(), pseudoClass(), and QStyleSheetStyle::renderRule().
PseudoClass_Window
const quint64 QCss::PseudoClass_Window = Q_UINT64_C(0x0000000000001000)
Definition at line 474 of file qcssparser_p.h.
Referenced by extendedPseudoClass(), and pseudoClass().