Qt 4.8: QPatternist::CommonNamespaces Namespace Reference
QPatternist::CommonNamespaces Namespace Reference
Contains common, standardized XML namespaces.
Functions
const QLatin1String WXS ("http://www.w3.org/2001/XMLSchema")
const QLatin1String XDT_LOCAL ("http://www.w3.org/2005/xquery-local-functions")
const QLatin1String XFN ("http://www.w3.org/2005/xpath-functions")
const QLatin1String XML ("http://www.w3.org/XML/1998/namespace")
const QLatin1String XMLNS ("http://www.w3.org/2000/xmlns/")
const QLatin1String XPERR ("http://www.w3.org/2005/xqt-errors")
const QLatin1String XSI ("http://www.w3.org/2001/XMLSchema-instance")
const QLatin1String XSLT ("http://www.w3.org/1999/XSL/Transform")
Variables
const char *const UNICODE_COLLATION = "http://www.w3.org/2005/xpath-functions/collation/codepoint"
Detailed Description
Contains common, standardized XML namespaces.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Function Documentation
WXS()
const QLatin1String QPatternist::CommonNamespaces::WXS ("http://www.w3.org/2001/XMLSchema")
The namespace for W3C XML Schema. This is used for the XML language it is, as well as its built-in data types.
Specification: http://www.w3.org/TR/xmlschema-2/
See also
XML Schema Part 2: Datatypes Second Edition, 3.1 Namespace considerations
Referenced by QPatternist::XsdSchemaTypesFactory::XsdSchemaTypesFactory(), and QPatternist::XsdValidatingInstanceReader::XsdValidatingInstanceReader().
XDT_LOCAL()
const QLatin1String QPatternist::CommonNamespaces::XDT_LOCAL ("http://www.w3.org/2005/xquery-local-functions")
A namespace provided in XQuery 1.0, to easily declare local variables and functions.
XFN()
const QLatin1String QPatternist::CommonNamespaces::XFN ("http://www.w3.org/2005/xpath-functions")
The namespace for built-in XPath functions, as defined in for example XQuery 1.0 and XPath 2.0 Functions and Operators and XSLT.
Specification: http://www.w3.org/TR/xquery-operators/
XML()
const QLatin1String QPatternist::CommonNamespaces::XML ("http://www.w3.org/XML/1998/namespace")
Namespace for the special XML namespace. It is by definition bound to the "xml" prefix, and should have no usage in ordinary code.
Specification: http://www.w3.org/TR/REC-xml-names/
Referenced by QPatternist::XSLTTokenizer::handleStandardAttributes(), QPatternist::XsdSchemaParser::parseDocumentation(), QPatternist::XsdSchemaParser::parseSchema(), and QPatternist::yyparse().
XMLNS()
const QLatin1String QPatternist::CommonNamespaces::XMLNS ("http://www.w3.org/2000/xmlns/")
The namespace for the xmlns prefix. The Namespaces in XML recommendation explicitly states that xmlns should not have a namespace, but has since been changed. See:
http://www.w3.org/2000/xmlns/
Referenced by QPatternist::AttributeNameValidator::evaluateSingleton().
XPERR()
const QLatin1String QPatternist::CommonNamespaces::XPERR ("http://www.w3.org/2005/xqt-errors")
The namespace for identifying errors in XPath.
See also
XML Path Language (XPath) 2.0, 2.3.2 Identifying and Reporting Errors
Referenced by QPatternist::ReportContext::error().
XSI()
const QLatin1String QPatternist::CommonNamespaces::XSI ("http://www.w3.org/2001/XMLSchema-instance")
The namespace for W3C XML Schema attributes used in schema instances.
Specification: http://www.w3.org/TR/xmlschema-2/
See also
XML Schema Part 1: Structures Second Edition, 2.6 Schema-Related Markup in Documents Being Validated
Referenced by QPatternist::XsdSchemaParser::parseGlobalAttribute(), and QPatternist::XsdSchemaParser::parseLocalAttribute().
XSLT()
const QLatin1String QPatternist::CommonNamespaces::XSLT ("http://www.w3.org/1999/XSL/Transform")
The namespace for XSL-T 1.0 and 2.0.
See also
XSL Transformations (XSLT) Version 2.0, 3.1 XSLT Namespace
XSL Transformations (XSLT) Version 1.0
Referenced by QPatternist::XSLTTokenizer::handleStandardAttributes(), QPatternist::XSLTTokenizer::handleValidationAttributes(), QPatternist::XSLTTokenizer::handleXSLTVersion(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), QPatternist::XSLTTokenizer::isXSLT(), and QPatternist::XSLTTokenizer::outsideDocumentElement().
Variable Documentation
UNICODE_COLLATION
const char* const QPatternist::CommonNamespaces::UNICODE_COLLATION = "http://www.w3.org/2005/xpath-functions/collation/codepoint"
The XPath 2.0 Unicode codepoint collation URI identifier. Collations specifies how strings are compared and ordered.
Definition at line 138 of file qcommonnamespaces_p.h.
Referenced by QPatternist::XPathHelper::checkCollationSupport().