Qt 4.8: QPdf Namespace Reference
QPdf Namespace Reference
Classes
class ByteStream
struct PaperSize
struct Stroker
Enumerations
enum PathFlags { ClipPath, FillPath, StrokePath, FillAndStrokePath }
Functions
QByteArray ascii85Encode (const QByteArray &input)
QByteArray generateDashes (const QPen &pen)
QByteArray generateMatrix (const QTransform &matrix)
QByteArray generatePath (const QPainterPath &path, const QTransform &matrix, PathFlags flags)
PaperSize paperSize (QPrinter::PaperSize paperSize)
const char * paperSizeToString (QPrinter::PaperSize paperSize)
QByteArray patternForBrush (const QBrush &b)
const char * toHex (ushort u, char *buffer)
const char * toHex (uchar u, char *buffer)
Enumeration Type Documentation
PathFlags
enum QPdf::PathFlags
Enumerator
ClipPath
FillPath
StrokePath
FillAndStrokePath
Definition at line 119 of file qpdf_p.h.
                    {
         ClipPath,
         FillPath,
         StrokePath,
         FillAndStrokePath
     };
Function Documentation
ascii85Encode()
QByteArray QPdf::ascii85Encode (const QByteArray & input)
Definition at line 806 of file qpdf.cpp.
Referenced by compressHelper().
 {
     int isize = input.size()/4*4;
     QByteArray output;
     output.resize(input.size()*5/4+7);
     char *out = output.data();
     const uchar *in = (const uchar *)input.constData();
     for (int i = 0; i < isize; i += 4) {
         uint val = (((uint)in[i])<<24) + (((uint)in[i+1])<<16) + (((uint)in[i+2])<<8) + (uint)in[i+3];
         if (val == 0) {
             *out = 'z';
             ++out;
         } else {
             char base[5];
             base[4] = val % 85;
             val /= 85;
             base[3] = val % 85;
             val /= 85;
             base[2] = val % 85;
             val /= 85;
             base[1] = val % 85;
             val /= 85;
             base[0] = val % 85;
             *(out++) = base[0] + '!';
             *(out++) = base[1] + '!';
             *(out++) = base[2] + '!';
             *(out++) = base[3] + '!';
             *(out++) = base[4] + '!';
         }
     }
     //write the last few bytes
     int remaining = input.size() - isize;
     if (remaining) {
         uint val = 0;
         for (int i = isize; i < input.size(); ++i)
             val = (val << 8) + in[i];
         val <<= 8*(4-remaining);
         char base[5];
         base[4] = val % 85;
         val /= 85;
         base[3] = val % 85;
         val /= 85;
         base[2] = val % 85;
         val /= 85;
         base[1] = val % 85;
         val /= 85;
         base[0] = val % 85;
         for (int i = 0; i < remaining+1; ++i)
             *(out++) = base[i] + '!';
     }
     *(out++) = '~';
     *(out++) = '>';
     output.resize(out-output.data());
     return output;
 }
generateDashes()
QByteArray QPdf::generateDashes (const QPen & pen)
Definition at line 348 of file qpdf.cpp.
Referenced by QPdfBaseEngine::setPen().
 {
     QByteArray result;
     ByteStream s(&result);
     s << '[';
     QVector<qreal> dasharray = pen.dashPattern();
     qreal w = pen.widthF();
     if (w < 0.001)
         w = 1;
     for (int i = 0; i < dasharray.size(); ++i) {
         qreal dw = dasharray.at(i)*w;
         if (dw < 0.0001) dw = 0.0001;
         s << dw;
     }
     s << ']';
     //qDebug() << "dasharray: pen has" << dasharray;
     //qDebug() << "  => " << result;
     return result;
 }
generateMatrix()
QByteArray QPdf::generateMatrix (const QTransform & matrix)
Definition at line 334 of file qpdf.cpp.
Referenced by QPdfEnginePrivate::addBrushPattern(), QPdfEngine::drawImage(), QPSPrintEngine::drawImageInternal(), QPdfEngine::drawPixmap(), QPdfBaseEngine::drawRects(), QPdfBaseEngine::drawTextItem(), QPdfEnginePrivate::newPage(), and QPdfBaseEngine::setupGraphicsState().
 {
     QByteArray result;
     ByteStream s(&result);
     s << matrix.m11()
       << matrix.m12()
       << matrix.m21()
       << matrix.m22()
       << matrix.dx()
       << matrix.dy()
       << "cm\n";
     return result;
 }
generatePath()
QByteArray QPdf::generatePath (const QPainterPath & path, const QTransform & matrix, PathFlags flags)
Definition at line 272 of file qpdf.cpp.
Referenced by QPdfBaseEngine::drawPath(), and QPdfBaseEngine::setupGraphicsState().
 {
     QByteArray result;
     if (!path.elementCount())
         return result;
     ByteStream s(&result);
     int start = -1;
     for (int i = 0; i < path.elementCount(); ++i) {
         const QPainterPath::Element &elm = path.elementAt(i);
         switch (elm.type) {
         case QPainterPath::MoveToElement:
             if (start >= 0
                 && path.elementAt(start).x == path.elementAt(i-1).x
                 && path.elementAt(start).y == path.elementAt(i-1).y)
                 s << "h\n";
             s << matrix.map(QPointF(elm.x, elm.y)) << "m\n";
             start = i;
                 break;
         case QPainterPath::LineToElement:
             s << matrix.map(QPointF(elm.x, elm.y)) << "l\n";
             break;
         case QPainterPath::CurveToElement:
             Q_ASSERT(path.elementAt(i+1).type == QPainterPath::CurveToDataElement);
             Q_ASSERT(path.elementAt(i+2).type == QPainterPath::CurveToDataElement);
             s << matrix.map(QPointF(elm.x, elm.y))
               << matrix.map(QPointF(path.elementAt(i+1).x, path.elementAt(i+1).y))
               << matrix.map(QPointF(path.elementAt(i+2).x, path.elementAt(i+2).y))
               << "c\n";
             i += 2;
             break;
         default:
             qFatal("QPdf::generatePath(), unhandled type: %d", elm.type);
         }
     }
     if (start >= 0
         && path.elementAt(start).x == path.elementAt(path.elementCount()-1).x
         && path.elementAt(start).y == path.elementAt(path.elementCount()-1).y)
         s << "h\n";
     Qt::FillRule fillRule = path.fillRule();
     const char *op = "";
     switch (flags) {
     case ClipPath:
         op = (fillRule == Qt::WindingFill) ? "W n\n" : "W* n\n";
         break;
     case FillPath:
         op = (fillRule == Qt::WindingFill) ? "f\n" : "f*\n";
         break;
     case StrokePath:
         op = "S\n";
         break;
     case FillAndStrokePath:
         op = (fillRule == Qt::WindingFill) ? "B\n" : "B*\n";
         break;
     }
     s << op;
     return result;
 }
paperSize()
QPdf::PaperSize QPdf::paperSize (QPrinter::PaperSize paperSize)
Definition at line 905 of file qpdf.cpp.
Referenced by QPdfBaseEnginePrivate::pageRect(), QtopiaPrintEngine::paperRect(), QPdfBaseEnginePrivate::paperRect(), paperSizeToString(), QPrintPreviewWidgetPrivate::populateScene(), QMacPrintEnginePrivate::QMacPrintEnginePrivate(), QUnixPrintWidgetPrivate::setCupsProperties(), QPageSetupWidget::setupPrinter(), and QWin32PrintEnginePrivate::updateCustomPaperSize().
 {
     QSizeF s = qt_paperSizeToQSizeF(paperSize);
     PaperSize p = { Q_MM(s.width()), Q_MM(s.height()) };
     return p;
 }
paperSizeToString()
const char * QPdf::paperSizeToString (QPrinter::PaperSize paperSize)
Definition at line 912 of file qpdf.cpp.
 {
     return psToStr[paperSize];
 }
patternForBrush()
QByteArray QPdf::patternForBrush (const QBrush & b)
Definition at line 524 of file qpdf.cpp.
Referenced by QPdfEnginePrivate::addBrushPattern().
 {
     int style = b.style();
     if (style > Qt::DiagCrossPattern)
         return QByteArray();
     return pattern_for_brush[style];
 }
toHex() [1/2]
const char * QPdf::toHex (ushort u, char * buffer)
Definition at line 862 of file qpdf.cpp.
Referenced by QFontSubset::createToUnicodeMap(), QPdfBaseEnginePrivate::drawTextItem(), encodeNumber(), and QFontSubset::glyphName().
 {
     int i = 3;
     while (i >= 0) {
         ushort hex = (u & 0x000f);
         if (hex < 0x0a)
             buffer[i] = '0'+hex;
         else
             buffer[i] = 'A'+(hex-0x0a);
         u = u >> 4;
         i--;
     }
     buffer[4] = '\0';
     return buffer;
 }
toHex() [2/2]
const char * QPdf::toHex (uchar u, char * buffer)
Definition at line 878 of file qpdf.cpp.
 {
     int i = 1;
     while (i >= 0) {
         ushort hex = (u & 0x000f);
         if (hex < 0x0a)
             buffer[i] = '0'+hex;
         else
             buffer[i] = 'A'+(hex-0x0a);
         u = u >> 4;
         i--;
     }
     buffer[2] = '\0';
     return buffer;
 }