Qt 4.8: QtPrivate Namespace Reference
QtPrivate Namespace Reference
Classes
class HasResultType
struct QEnableIf
struct QEnableIf< true, T >
struct QMetaTypeIdHelper
struct QMetaTypeIdHelper< T, false >
struct QScopedArrayEnsureSameType
struct QScopedArrayEnsureSameType< const X, X >
struct QScopedArrayEnsureSameType< X, X >
Functions
QBool Q_CORE_EXPORT QStringList_contains (const QStringList *that, const QString &str, Qt::CaseSensitivity cs)
QStringList Q_CORE_EXPORT QStringList_filter (const QStringList *that, const QString &str, Qt::CaseSensitivity cs)
QStringList Q_CORE_EXPORT QStringList_filter (const QStringList *that, const QRegExp &re)
int Q_CORE_EXPORT QStringList_indexOf (const QStringList *that, const QRegExp &rx, int from)
int Q_CORE_EXPORT QStringList_indexOf (const QStringList *that, QRegExp &rx, int from)
QString Q_CORE_EXPORT QStringList_join (const QStringList *that, const QString &sep)
int Q_CORE_EXPORT QStringList_lastIndexOf (const QStringList *that, const QRegExp &rx, int from)
int Q_CORE_EXPORT QStringList_lastIndexOf (const QStringList *that, QRegExp &rx, int from)
int Q_CORE_EXPORT QStringList_removeDuplicates (QStringList *that)
void Q_CORE_EXPORT QStringList_replaceInStrings (QStringList *that, const QString &before, const QString &after, Qt::CaseSensitivity cs)
void Q_CORE_EXPORT QStringList_replaceInStrings (QStringList *that, const QRegExp &rx, const QString &after)
void Q_CORE_EXPORT QStringList_sort (QStringList *that)
Function Documentation
QStringList_contains()
QBool QtPrivate::QStringList_contains (const QStringList * that, const QString & str, Qt::CaseSensitivity cs)
Definition at line 349 of file qstringlist.cpp.
Referenced by QStringList::contains(), and QStringList::operator<<().
 {
     for (int i = 0; i < that->size(); ++i) {
         const QString & string = that->at(i);
         if (string.length() == str.length() && str.compare(string, cs) == 0)
             return QBool(true);
     }
     return QBool(false);
 }
QStringList_filter() [1/2]
QStringList QtPrivate::QStringList_filter (const QStringList * that, const QString & str, Qt::CaseSensitivity cs)
Definition at line 325 of file qstringlist.cpp.
Referenced by QStringList::filter(), and QStringList::operator<<().
 {
     QStringMatcher matcher(str, cs);
     QStringList res;
     for (int i = 0; i < that->size(); ++i)
         if (matcher.indexIn(that->at(i)) != -1)
             res << that->at(i);
     return res;
 }
QStringList_filter() [2/2]
QStringList QtPrivate::QStringList_filter (const QStringList * that, const QRegExp & re)
Definition at line 372 of file qstringlist.cpp.
 {
     QStringList res;
     for (int i = 0; i < that->size(); ++i)
         if (that->at(i).contains(rx))
             res << that->at(i);
     return res;
 }
QStringList_indexOf() [1/2]
int QtPrivate::QStringList_indexOf (const QStringList * that, const QRegExp & rx, int from)
Definition at line 645 of file qstringlist.cpp.
Referenced by QStringList::indexOf(), and QStringList::operator<<().
 {
     QRegExp rx2(rx);
     return indexOfMutating(that, rx2, from);
 }
QStringList_indexOf() [2/2]
int QtPrivate::QStringList_indexOf (const QStringList * that, QRegExp & rx, int from)
Definition at line 670 of file qstringlist.cpp.
 {
     return indexOfMutating(that, rx, from);
 }
QStringList_join()
QString QtPrivate::QStringList_join (const QStringList * that, const QString & sep)
Definition at line 453 of file qstringlist.cpp.
Referenced by QStringList::join(), and QStringList::operator<<().
 {
     int totalLength = 0;
     const int size = that->size();
     for (int i = 0; i < size; ++i)
         totalLength += that->at(i).size();
     if(size > 0)
         totalLength += sep.size() * (size - 1);
     QString res;
     if (totalLength == 0)
     return res;
     res.reserve(totalLength);
     for (int i = 0; i < that->size(); ++i) {
         if (i)
             res += sep;
         res += that->at(i);
     }
     return res;
 }
QStringList_lastIndexOf() [1/2]
int QtPrivate::QStringList_lastIndexOf (const QStringList * that, const QRegExp & rx, int from)
Definition at line 690 of file qstringlist.cpp.
Referenced by QStringList::lastIndexOf(), and QStringList::operator<<().
 {
     QRegExp rx2(rx);
     return lastIndexOfMutating(that, rx2, from);
 }
QStringList_lastIndexOf() [2/2]
int QtPrivate::QStringList_lastIndexOf (const QStringList * that, QRegExp & rx, int from)
Definition at line 716 of file qstringlist.cpp.
 {
     return lastIndexOfMutating(that, rx, from);
 }
QStringList_removeDuplicates()
int QtPrivate::QStringList_removeDuplicates (QStringList * that)
Definition at line 765 of file qstringlist.cpp.
Referenced by QStringList::operator<<(), and QStringList::removeDuplicates().
 {
     int n = that->size();
     int j = 0;
     QSet<QString> seen;
     seen.reserve(n);
     for (int i = 0; i < n; ++i) {
         const QString &s = that->at(i);
         if (seen.contains(s))
             continue;
         seen.insert(s);
         if (j != i)
             (*that)[j] = s;
         ++j;
     }
     if (n != j)
         that->erase(that->begin() + j, that->end());
     return n - j;
 }
QStringList_replaceInStrings() [1/2]
void QtPrivate::QStringList_replaceInStrings (QStringList * that, const QString & before, const QString & after, Qt::CaseSensitivity cs)
Definition at line 400 of file qstringlist.cpp.
Referenced by QStringList::operator<<(), and QStringList::replaceInStrings().
 {
     for (int i = 0; i < that->size(); ++i)
         (*that)[i].replace(before, after, cs);
 }
QStringList_replaceInStrings() [2/2]
void QtPrivate::QStringList_replaceInStrings (QStringList * that, const QRegExp & rx, const QString & after)
Definition at line 434 of file qstringlist.cpp.
 {
     for (int i = 0; i < that->size(); ++i)
         (*that)[i].replace(rx, after);
 }
QStringList_sort()
void QtPrivate::QStringList_sort (QStringList * that)
Definition at line 252 of file qstringlist.cpp.
Referenced by QStringList::operator<<(), and QStringList::sort().
 {
     qSort(*that);
 }