Qt 4.8: Qt Namespace Reference
Qt Namespace Reference
Typedefs
typedef void * HANDLE
typedef WindowFlags WFlags
Enumerations
enum AlignmentFlag {
AlignLeft = 0x0001, AlignLeading = AlignLeft, AlignRight = 0x0002, AlignTrailing = AlignRight,
AlignHCenter = 0x0004, AlignJustify = 0x0008, AlignAbsolute = 0x0010, AlignHorizontal_Mask = AlignLeft | AlignRight | AlignHCenter | AlignJustify | AlignAbsolute,
AlignTop = 0x0020, AlignBottom = 0x0040, AlignVCenter = 0x0080, AlignVertical_Mask = AlignTop | AlignBottom | AlignVCenter,
AlignCenter = AlignVCenter | AlignHCenter
}
enum AnchorAttribute { AnchorName, AnchorHref }
enum AnchorPoint {
AnchorLeft = 0, AnchorHorizontalCenter, AnchorRight, AnchorTop,
AnchorVerticalCenter, AnchorBottom
}
enum ApplicationAttribute {
AA_ImmediateWidgetCreation = 0, AA_MSWindowsUseDirect3DByDefault = 1, AA_DontShowIconsInMenus = 2, AA_NativeWindows = 3,
AA_DontCreateNativeWidgetSiblings = 4, AA_MacPluginApplication = 5, AA_DontUseNativeMenuBar = 6, AA_MacDontSwapCtrlAndMeta = 7,
AA_S60DontConstructApplicationPanes = 8, AA_S60DisablePartialScreenInputMode = 9, AA_X11InitThreads = 10, AA_CaptureMultimediaKeys = 11,
AA_AttributeCount
}
enum ArrowType {
NoArrow, UpArrow, DownArrow, LeftArrow,
RightArrow
}
enum AspectRatioMode { IgnoreAspectRatio, KeepAspectRatio, KeepAspectRatioByExpanding }
enum Axis { XAxis, YAxis, ZAxis }
enum BGMode { TransparentMode, OpaqueMode }
enum BrushStyle {
NoBrush, SolidPattern, Dense1Pattern, Dense2Pattern,
Dense3Pattern, Dense4Pattern, Dense5Pattern, Dense6Pattern,
Dense7Pattern, HorPattern, VerPattern, CrossPattern,
BDiagPattern, FDiagPattern, DiagCrossPattern, LinearGradientPattern,
RadialGradientPattern, ConicalGradientPattern, TexturePattern = 24
}
enum CaseSensitivity { CaseInsensitive, CaseSensitive }
enum CheckState { Unchecked, PartiallyChecked, Checked }
enum ClipOperation { NoClip, ReplaceClip, IntersectClip, UniteClip }
enum ConnectionType {
AutoConnection, DirectConnection, QueuedConnection, AutoCompatConnection,
BlockingQueuedConnection, UniqueConnection = 0x80
}
enum ContextMenuPolicy {
NoContextMenu, DefaultContextMenu, ActionsContextMenu, CustomContextMenu,
PreventContextMenu
}
enum CoordinateSystem { DeviceCoordinates, LogicalCoordinates }
enum Corner { TopLeftCorner = 0x00000, TopRightCorner = 0x00001, BottomLeftCorner = 0x00002, BottomRightCorner = 0x00003 }
enum CursorMoveStyle { LogicalMoveStyle, VisualMoveStyle }
This enum describes the movement style available to text cursors.
enum CursorShape {
ArrowCursor, UpArrowCursor, CrossCursor, WaitCursor,
IBeamCursor, SizeVerCursor, SizeHorCursor, SizeBDiagCursor,
SizeFDiagCursor, SizeAllCursor, BlankCursor, SplitVCursor,
SplitHCursor, PointingHandCursor, ForbiddenCursor, WhatsThisCursor,
BusyCursor, OpenHandCursor, ClosedHandCursor, DragCopyCursor,
DragMoveCursor, DragLinkCursor, LastCursor = DragLinkCursor, BitmapCursor = 24,
CustomCursor = 25
}
enum DateFormat {
TextDate, ISODate, SystemLocaleDate, LocalDate = SystemLocaleDate,
LocaleDate, SystemLocaleShortDate, SystemLocaleLongDate, DefaultLocaleShortDate,
DefaultLocaleLongDate
}
enum DayOfWeek {
Monday = 1, Tuesday = 2, Wednesday = 3, Thursday = 4,
Friday = 5, Saturday = 6, Sunday = 7
}
enum DockWidgetArea {
LeftDockWidgetArea = 0x1, RightDockWidgetArea = 0x2, TopDockWidgetArea = 0x4, BottomDockWidgetArea = 0x8,
DockWidgetArea_Mask = 0xf, AllDockWidgetAreas = DockWidgetArea_Mask, NoDockWidgetArea = 0
}
enum DockWidgetAreaSizes { NDockWidgetAreas = 4 }
enum DropAction {
CopyAction = 0x1, MoveAction = 0x2, LinkAction = 0x4, ActionMask = 0xff,
TargetMoveAction = 0x8002, IgnoreAction = 0x0
}
enum EventPriority { HighEventPriority = 1, NormalEventPriority = 0, LowEventPriority = -1 }
enum FillRule { OddEvenFill, WindingFill }
enum FocusPolicy {
NoFocus = 0, TabFocus = 0x1, ClickFocus = 0x2, StrongFocus = TabFocus | ClickFocus | 0x8,
WheelFocus = StrongFocus | 0x4
}
enum FocusReason {
MouseFocusReason, TabFocusReason, BacktabFocusReason, ActiveWindowFocusReason,
PopupFocusReason, ShortcutFocusReason, MenuBarFocusReason, OtherFocusReason,
NoFocusReason
}
enum GestureFlag { DontStartGestureOnChildren = 0x01, ReceivePartialGestures = 0x02, IgnoredGesturesPropagateToParent = 0x04 }
enum GestureState {
NoGesture, GestureStarted = 1, GestureUpdated = 2, GestureFinished = 3,
GestureCanceled = 4
}
enum GestureType {
TapGesture = 1, TapAndHoldGesture = 2, PanGesture = 3, PinchGesture = 4,
SwipeGesture = 5, CustomGesture = 0x0100, LastGestureType = ~0u
}
enum GlobalColor {
color0, color1, black, white,
darkGray, gray, lightGray, red,
green, blue, cyan, magenta,
yellow, darkRed, darkGreen, darkBlue,
darkCyan, darkMagenta, darkYellow, transparent
}
enum HitTestAccuracy { ExactHit, FuzzyHit }
enum ImageConversionFlag {
ColorMode_Mask = 0x00000003, AutoColor = 0x00000000, ColorOnly = 0x00000003, MonoOnly = 0x00000002,
AlphaDither_Mask = 0x0000000c, ThresholdAlphaDither = 0x00000000, OrderedAlphaDither = 0x00000004, DiffuseAlphaDither = 0x00000008,
NoAlpha = 0x0000000c, Dither_Mask = 0x00000030, DiffuseDither = 0x00000000, OrderedDither = 0x00000010,
ThresholdDither = 0x00000020, DitherMode_Mask = 0x000000c0, AutoDither = 0x00000000, PreferDither = 0x00000040,
AvoidDither = 0x00000080, NoOpaqueDetection = 0x00000100, NoFormatConversion = 0x00000200
}
enum Initialization { Uninitialized }
enum InputMethodHint {
ImhNone = 0x0, ImhHiddenText = 0x1, ImhNoAutoUppercase = 0x2, ImhPreferNumbers = 0x4,
ImhPreferUppercase = 0x8, ImhPreferLowercase = 0x10, ImhNoPredictiveText = 0x20, ImhDigitsOnly = 0x10000,
ImhFormattedNumbersOnly = 0x20000, ImhUppercaseOnly = 0x40000, ImhLowercaseOnly = 0x80000, ImhDialableCharactersOnly = 0x100000,
ImhEmailCharactersOnly = 0x200000, ImhUrlCharactersOnly = 0x400000, ImhExclusiveInputMask = 0xffff0000
}
enum InputMethodQuery {
ImMicroFocus, ImFont, ImCursorPosition, ImSurroundingText,
ImCurrentSelection, ImMaximumTextLength, ImAnchorPosition
}
enum ItemDataRole {
DisplayRole = 0, DecorationRole = 1, EditRole = 2, ToolTipRole = 3,
StatusTipRole = 4, WhatsThisRole = 5, FontRole = 6, TextAlignmentRole = 7,
BackgroundColorRole = 8, BackgroundRole = 8, TextColorRole = 9, ForegroundRole = 9,
CheckStateRole = 10, AccessibleTextRole = 11, AccessibleDescriptionRole = 12, SizeHintRole = 13,
InitialSortOrderRole = 14, DisplayPropertyRole = 27, DecorationPropertyRole = 28, ToolTipPropertyRole = 29,
StatusTipPropertyRole = 30, WhatsThisPropertyRole = 31, UserRole = 32
}
enum ItemFlag {
NoItemFlags = 0, ItemIsSelectable = 1, ItemIsEditable = 2, ItemIsDragEnabled = 4,
ItemIsDropEnabled = 8, ItemIsUserCheckable = 16, ItemIsEnabled = 32, ItemIsTristate = 64
}
enum ItemSelectionMode { ContainsItemShape = 0x0, IntersectsItemShape = 0x1, ContainsItemBoundingRect = 0x2, IntersectsItemBoundingRect = 0x3 }
enum Key {
Key_Escape = 0x01000000, Key_Tab = 0x01000001, Key_Backtab = 0x01000002, Key_Backspace = 0x01000003,
Key_Return = 0x01000004, Key_Enter = 0x01000005, Key_Insert = 0x01000006, Key_Delete = 0x01000007,
Key_Pause = 0x01000008, Key_Print = 0x01000009, Key_SysReq = 0x0100000a, Key_Clear = 0x0100000b,
Key_Home = 0x01000010, Key_End = 0x01000011, Key_Left = 0x01000012, Key_Up = 0x01000013,
Key_Right = 0x01000014, Key_Down = 0x01000015, Key_PageUp = 0x01000016, Key_PageDown = 0x01000017,
Key_Shift = 0x01000020, Key_Control = 0x01000021, Key_Meta = 0x01000022, Key_Alt = 0x01000023,
Key_CapsLock = 0x01000024, Key_NumLock = 0x01000025, Key_ScrollLock = 0x01000026, Key_F1 = 0x01000030,
Key_F2 = 0x01000031, Key_F3 = 0x01000032, Key_F4 = 0x01000033, Key_F5 = 0x01000034,
Key_F6 = 0x01000035, Key_F7 = 0x01000036, Key_F8 = 0x01000037, Key_F9 = 0x01000038,
Key_F10 = 0x01000039, Key_F11 = 0x0100003a, Key_F12 = 0x0100003b, Key_F13 = 0x0100003c,
Key_F14 = 0x0100003d, Key_F15 = 0x0100003e, Key_F16 = 0x0100003f, Key_F17 = 0x01000040,
Key_F18 = 0x01000041, Key_F19 = 0x01000042, Key_F20 = 0x01000043, Key_F21 = 0x01000044,
Key_F22 = 0x01000045, Key_F23 = 0x01000046, Key_F24 = 0x01000047, Key_F25 = 0x01000048,
Key_F26 = 0x01000049, Key_F27 = 0x0100004a, Key_F28 = 0x0100004b, Key_F29 = 0x0100004c,
Key_F30 = 0x0100004d, Key_F31 = 0x0100004e, Key_F32 = 0x0100004f, Key_F33 = 0x01000050,
Key_F34 = 0x01000051, Key_F35 = 0x01000052, Key_Super_L = 0x01000053, Key_Super_R = 0x01000054,
Key_Menu = 0x01000055, Key_Hyper_L = 0x01000056, Key_Hyper_R = 0x01000057, Key_Help = 0x01000058,
Key_Direction_L = 0x01000059, Key_Direction_R = 0x01000060, Key_Space = 0x20, Key_Any = Key_Space,
Key_Exclam = 0x21, Key_QuoteDbl = 0x22, Key_NumberSign = 0x23, Key_Dollar = 0x24,
Key_Percent = 0x25, Key_Ampersand = 0x26, Key_Apostrophe = 0x27, Key_ParenLeft = 0x28,
Key_ParenRight = 0x29, Key_Asterisk = 0x2a, Key_Plus = 0x2b, Key_Comma = 0x2c,
Key_Minus = 0x2d, Key_Period = 0x2e, Key_Slash = 0x2f, Key_0 = 0x30,
Key_1 = 0x31, Key_2 = 0x32, Key_3 = 0x33, Key_4 = 0x34,
Key_5 = 0x35, Key_6 = 0x36, Key_7 = 0x37, Key_8 = 0x38,
Key_9 = 0x39, Key_Colon = 0x3a, Key_Semicolon = 0x3b, Key_Less = 0x3c,
Key_Equal = 0x3d, Key_Greater = 0x3e, Key_Question = 0x3f, Key_At = 0x40,
Key_A = 0x41, Key_B = 0x42, Key_C = 0x43, Key_D = 0x44,
Key_E = 0x45, Key_F = 0x46, Key_G = 0x47, Key_H = 0x48,
Key_I = 0x49, Key_J = 0x4a, Key_K = 0x4b, Key_L = 0x4c,
Key_M = 0x4d, Key_N = 0x4e, Key_O = 0x4f, Key_P = 0x50,
Key_Q = 0x51, Key_R = 0x52, Key_S = 0x53, Key_T = 0x54,
Key_U = 0x55, Key_V = 0x56, Key_W = 0x57, Key_X = 0x58,
Key_Y = 0x59, Key_Z = 0x5a, Key_BracketLeft = 0x5b, Key_Backslash = 0x5c,
Key_BracketRight = 0x5d, Key_AsciiCircum = 0x5e, Key_Underscore = 0x5f, Key_QuoteLeft = 0x60,
Key_BraceLeft = 0x7b, Key_Bar = 0x7c, Key_BraceRight = 0x7d, Key_AsciiTilde = 0x7e,
Key_nobreakspace = 0x0a0, Key_exclamdown = 0x0a1, Key_cent = 0x0a2, Key_sterling = 0x0a3,
Key_currency = 0x0a4, Key_yen = 0x0a5, Key_brokenbar = 0x0a6, Key_section = 0x0a7,
Key_diaeresis = 0x0a8, Key_copyright = 0x0a9, Key_ordfeminine = 0x0aa, Key_guillemotleft = 0x0ab,
Key_notsign = 0x0ac, Key_hyphen = 0x0ad, Key_registered = 0x0ae, Key_macron = 0x0af,
Key_degree = 0x0b0, Key_plusminus = 0x0b1, Key_twosuperior = 0x0b2, Key_threesuperior = 0x0b3,
Key_acute = 0x0b4, Key_mu = 0x0b5, Key_paragraph = 0x0b6, Key_periodcentered = 0x0b7,
Key_cedilla = 0x0b8, Key_onesuperior = 0x0b9, Key_masculine = 0x0ba, Key_guillemotright = 0x0bb,
Key_onequarter = 0x0bc, Key_onehalf = 0x0bd, Key_threequarters = 0x0be, Key_questiondown = 0x0bf,
Key_Agrave = 0x0c0, Key_Aacute = 0x0c1, Key_Acircumflex = 0x0c2, Key_Atilde = 0x0c3,
Key_Adiaeresis = 0x0c4, Key_Aring = 0x0c5, Key_AE = 0x0c6, Key_Ccedilla = 0x0c7,
Key_Egrave = 0x0c8, Key_Eacute = 0x0c9, Key_Ecircumflex = 0x0ca, Key_Ediaeresis = 0x0cb,
Key_Igrave = 0x0cc, Key_Iacute = 0x0cd, Key_Icircumflex = 0x0ce, Key_Idiaeresis = 0x0cf,
Key_ETH = 0x0d0, Key_Ntilde = 0x0d1, Key_Ograve = 0x0d2, Key_Oacute = 0x0d3,
Key_Ocircumflex = 0x0d4, Key_Otilde = 0x0d5, Key_Odiaeresis = 0x0d6, Key_multiply = 0x0d7,
Key_Ooblique = 0x0d8, Key_Ugrave = 0x0d9, Key_Uacute = 0x0da, Key_Ucircumflex = 0x0db,
Key_Udiaeresis = 0x0dc, Key_Yacute = 0x0dd, Key_THORN = 0x0de, Key_ssharp = 0x0df,
Key_division = 0x0f7, Key_ydiaeresis = 0x0ff, Key_AltGr = 0x01001103, Key_Multi_key = 0x01001120,
Key_Codeinput = 0x01001137, Key_SingleCandidate = 0x0100113c, Key_MultipleCandidate = 0x0100113d, Key_PreviousCandidate = 0x0100113e,
Key_Mode_switch = 0x0100117e, Key_Kanji = 0x01001121, Key_Muhenkan = 0x01001122, Key_Henkan = 0x01001123,
Key_Romaji = 0x01001124, Key_Hiragana = 0x01001125, Key_Katakana = 0x01001126, Key_Hiragana_Katakana = 0x01001127,
Key_Zenkaku = 0x01001128, Key_Hankaku = 0x01001129, Key_Zenkaku_Hankaku = 0x0100112a, Key_Touroku = 0x0100112b,
Key_Massyo = 0x0100112c, Key_Kana_Lock = 0x0100112d, Key_Kana_Shift = 0x0100112e, Key_Eisu_Shift = 0x0100112f,
Key_Eisu_toggle = 0x01001130, Key_Hangul = 0x01001131, Key_Hangul_Start = 0x01001132, Key_Hangul_End = 0x01001133,
Key_Hangul_Hanja = 0x01001134, Key_Hangul_Jamo = 0x01001135, Key_Hangul_Romaja = 0x01001136, Key_Hangul_Jeonja = 0x01001138,
Key_Hangul_Banja = 0x01001139, Key_Hangul_PreHanja = 0x0100113a, Key_Hangul_PostHanja = 0x0100113b, Key_Hangul_Special = 0x0100113f,
Key_Dead_Grave = 0x01001250, Key_Dead_Acute = 0x01001251, Key_Dead_Circumflex = 0x01001252, Key_Dead_Tilde = 0x01001253,
Key_Dead_Macron = 0x01001254, Key_Dead_Breve = 0x01001255, Key_Dead_Abovedot = 0x01001256, Key_Dead_Diaeresis = 0x01001257,
Key_Dead_Abovering = 0x01001258, Key_Dead_Doubleacute = 0x01001259, Key_Dead_Caron = 0x0100125a, Key_Dead_Cedilla = 0x0100125b,
Key_Dead_Ogonek = 0x0100125c, Key_Dead_Iota = 0x0100125d, Key_Dead_Voiced_Sound = 0x0100125e, Key_Dead_Semivoiced_Sound = 0x0100125f,
Key_Dead_Belowdot = 0x01001260, Key_Dead_Hook = 0x01001261, Key_Dead_Horn = 0x01001262, Key_Back = 0x01000061,
Key_Forward = 0x01000062, Key_Stop = 0x01000063, Key_Refresh = 0x01000064, Key_VolumeDown = 0x01000070,
Key_VolumeMute = 0x01000071, Key_VolumeUp = 0x01000072, Key_BassBoost = 0x01000073, Key_BassUp = 0x01000074,
Key_BassDown = 0x01000075, Key_TrebleUp = 0x01000076, Key_TrebleDown = 0x01000077, Key_MediaPlay = 0x01000080,
Key_MediaStop = 0x01000081, Key_MediaPrevious = 0x01000082, Key_MediaNext = 0x01000083, Key_MediaRecord = 0x01000084,
Key_MediaPause = 0x1000085, Key_MediaTogglePlayPause = 0x1000086, Key_HomePage = 0x01000090, Key_Favorites = 0x01000091,
Key_Search = 0x01000092, Key_Standby = 0x01000093, Key_OpenUrl = 0x01000094, Key_LaunchMail = 0x010000a0,
Key_LaunchMedia = 0x010000a1, Key_Launch0 = 0x010000a2, Key_Launch1 = 0x010000a3, Key_Launch2 = 0x010000a4,
Key_Launch3 = 0x010000a5, Key_Launch4 = 0x010000a6, Key_Launch5 = 0x010000a7, Key_Launch6 = 0x010000a8,
Key_Launch7 = 0x010000a9, Key_Launch8 = 0x010000aa, Key_Launch9 = 0x010000ab, Key_LaunchA = 0x010000ac,
Key_LaunchB = 0x010000ad, Key_LaunchC = 0x010000ae, Key_LaunchD = 0x010000af, Key_LaunchE = 0x010000b0,
Key_LaunchF = 0x010000b1, Key_MonBrightnessUp = 0x010000b2, Key_MonBrightnessDown = 0x010000b3, Key_KeyboardLightOnOff = 0x010000b4,
Key_KeyboardBrightnessUp = 0x010000b5, Key_KeyboardBrightnessDown = 0x010000b6, Key_PowerOff = 0x010000b7, Key_WakeUp = 0x010000b8,
Key_Eject = 0x010000b9, Key_ScreenSaver = 0x010000ba, Key_WWW = 0x010000bb, Key_Memo = 0x010000bc,
Key_LightBulb = 0x010000bd, Key_Shop = 0x010000be, Key_History = 0x010000bf, Key_AddFavorite = 0x010000c0,
Key_HotLinks = 0x010000c1, Key_BrightnessAdjust = 0x010000c2, Key_Finance = 0x010000c3, Key_Community = 0x010000c4,
Key_AudioRewind = 0x010000c5, Key_BackForward = 0x010000c6, Key_ApplicationLeft = 0x010000c7, Key_ApplicationRight = 0x010000c8,
Key_Book = 0x010000c9, Key_CD = 0x010000ca, Key_Calculator = 0x010000cb, Key_ToDoList = 0x010000cc,
Key_ClearGrab = 0x010000cd, Key_Close = 0x010000ce, Key_Copy = 0x010000cf, Key_Cut = 0x010000d0,
Key_Display = 0x010000d1, Key_DOS = 0x010000d2, Key_Documents = 0x010000d3, Key_Excel = 0x010000d4,
Key_Explorer = 0x010000d5, Key_Game = 0x010000d6, Key_Go = 0x010000d7, Key_iTouch = 0x010000d8,
Key_LogOff = 0x010000d9, Key_Market = 0x010000da, Key_Meeting = 0x010000db, Key_MenuKB = 0x010000dc,
Key_MenuPB = 0x010000dd, Key_MySites = 0x010000de, Key_News = 0x010000df, Key_OfficeHome = 0x010000e0,
Key_Option = 0x010000e1, Key_Paste = 0x010000e2, Key_Phone = 0x010000e3, Key_Calendar = 0x010000e4,
Key_Reply = 0x010000e5, Key_Reload = 0x010000e6, Key_RotateWindows = 0x010000e7, Key_RotationPB = 0x010000e8,
Key_RotationKB = 0x010000e9, Key_Save = 0x010000ea, Key_Send = 0x010000eb, Key_Spell = 0x010000ec,
Key_SplitScreen = 0x010000ed, Key_Support = 0x010000ee, Key_TaskPane = 0x010000ef, Key_Terminal = 0x010000f0,
Key_Tools = 0x010000f1, Key_Travel = 0x010000f2, Key_Video = 0x010000f3, Key_Word = 0x010000f4,
Key_Xfer = 0x010000f5, Key_ZoomIn = 0x010000f6, Key_ZoomOut = 0x010000f7, Key_Away = 0x010000f8,
Key_Messenger = 0x010000f9, Key_WebCam = 0x010000fa, Key_MailForward = 0x010000fb, Key_Pictures = 0x010000fc,
Key_Music = 0x010000fd, Key_Battery = 0x010000fe, Key_Bluetooth = 0x010000ff, Key_WLAN = 0x01000100,
Key_UWB = 0x01000101, Key_AudioForward = 0x01000102, Key_AudioRepeat = 0x01000103, Key_AudioRandomPlay = 0x01000104,
Key_Subtitle = 0x01000105, Key_AudioCycleTrack = 0x01000106, Key_Time = 0x01000107, Key_Hibernate = 0x01000108,
Key_View = 0x01000109, Key_TopMenu = 0x0100010a, Key_PowerDown = 0x0100010b, Key_Suspend = 0x0100010c,
Key_ContrastAdjust = 0x0100010d, Key_LaunchG = 0x0100010e, Key_LaunchH = 0x0100010f, Key_MediaLast = 0x0100ffff,
Key_Select = 0x01010000, Key_Yes = 0x01010001, Key_No = 0x01010002, Key_Cancel = 0x01020001,
Key_Printer = 0x01020002, Key_Execute = 0x01020003, Key_Sleep = 0x01020004, Key_Play = 0x01020005,
Key_Zoom = 0x01020006, Key_Context1 = 0x01100000, Key_Context2 = 0x01100001, Key_Context3 = 0x01100002,
Key_Context4 = 0x01100003, Key_Call = 0x01100004, Key_Hangup = 0x01100005, Key_Flip = 0x01100006,
Key_ToggleCallHangup = 0x01100007, Key_VoiceDial = 0x01100008, Key_LastNumberRedial = 0x01100009, Key_Camera = 0x01100020,
Key_CameraFocus = 0x01100021, Key_unknown = 0x01ffffff
}
enum KeyboardModifier {
NoModifier = 0x00000000, ShiftModifier = 0x02000000, ControlModifier = 0x04000000, AltModifier = 0x08000000,
MetaModifier = 0x10000000, KeypadModifier = 0x20000000, GroupSwitchModifier = 0x40000000, KeyboardModifierMask = 0xfe000000
}
enum LayoutDirection { LeftToRight, RightToLeft, LayoutDirectionAuto }
enum MaskMode { MaskInColor, MaskOutColor }
enum MatchFlag {
MatchExactly = 0, MatchContains = 1, MatchStartsWith = 2, MatchEndsWith = 3,
MatchRegExp = 4, MatchWildcard = 5, MatchFixedString = 8, MatchCaseSensitive = 16,
MatchWrap = 32, MatchRecursive = 64
}
enum Modifier {
META = Qt::MetaModifier, SHIFT = Qt::ShiftModifier, CTRL = Qt::ControlModifier, ALT = Qt::AltModifier,
MODIFIER_MASK = KeyboardModifierMask, UNICODE_ACCEL = 0x00000000
}
enum MouseButton {
NoButton = 0x00000000, LeftButton = 0x00000001, RightButton = 0x00000002, MidButton = 0x00000004,
MiddleButton = MidButton, XButton1 = 0x00000008, XButton2 = 0x00000010, MouseButtonMask = 0x000000ff
}
enum NavigationMode {
NavigationModeNone, NavigationModeKeypadTabOrder, NavigationModeKeypadDirectional, NavigationModeCursorAuto,
NavigationModeCursorForceVisible
}
enum Orientation { Horizontal = 0x1, Vertical = 0x2 }
enum PenCapStyle { FlatCap = 0x00, SquareCap = 0x10, RoundCap = 0x20, MPenCapStyle = 0x30 }
enum PenJoinStyle {
MiterJoin = 0x00, BevelJoin = 0x40, RoundJoin = 0x80, SvgMiterJoin = 0x100,
MPenJoinStyle = 0x1c0
}
enum PenStyle {
NoPen, SolidLine, DashLine, DotLine,
DashDotLine, DashDotDotLine, CustomDashLine, MPenStyle = 0x0f
}
enum ScrollBarPolicy { ScrollBarAsNeeded, ScrollBarAlwaysOff, ScrollBarAlwaysOn }
enum ShortcutContext { WidgetShortcut, WindowShortcut, ApplicationShortcut, WidgetWithChildrenShortcut }
enum SizeHint {
MinimumSize, PreferredSize, MaximumSize, MinimumDescent,
NSizeHints
}
enum SizeMode { AbsoluteSize, RelativeSize }
enum SortOrder { AscendingOrder, DescendingOrder }
enum TextElideMode { ElideLeft, ElideRight, ElideMiddle, ElideNone }
enum TextFlag {
TextSingleLine = 0x0100, TextDontClip = 0x0200, TextExpandTabs = 0x0400, TextShowMnemonic = 0x0800,
TextWordWrap = 0x1000, TextWrapAnywhere = 0x2000, TextDontPrint = 0x4000, TextIncludeTrailingSpaces = 0x08000000,
TextHideMnemonic = 0x8000, TextJustificationForced = 0x10000, TextForceLeftToRight = 0x20000, TextForceRightToLeft = 0x40000,
TextLongestVariant = 0x80000, TextBypassShaping = 0x100000
}
enum TextFormat { PlainText, RichText, AutoText, LogText }
enum TextInteractionFlag {
NoTextInteraction = 0, TextSelectableByMouse = 1, TextSelectableByKeyboard = 2, LinksAccessibleByMouse = 4,
LinksAccessibleByKeyboard = 8, TextEditable = 16, TextEditorInteraction = TextSelectableByMouse | TextSelectableByKeyboard | TextEditable, TextBrowserInteraction = TextSelectableByMouse | LinksAccessibleByMouse | LinksAccessibleByKeyboard
}
enum TileRule { StretchTile, RepeatTile, RoundTile }
enum TimeSpec { LocalTime, UTC, OffsetFromUTC }
enum ToolBarArea {
LeftToolBarArea = 0x1, RightToolBarArea = 0x2, TopToolBarArea = 0x4, BottomToolBarArea = 0x8,
ToolBarArea_Mask = 0xf, AllToolBarAreas = ToolBarArea_Mask, NoToolBarArea = 0
}
enum ToolBarAreaSizes { NToolBarAreas = 4 }
enum ToolButtonStyle {
ToolButtonIconOnly, ToolButtonTextOnly, ToolButtonTextBesideIcon, ToolButtonTextUnderIcon,
ToolButtonFollowStyle
}
enum TouchPointState {
TouchPointPressed = 0x01, TouchPointMoved = 0x02, TouchPointStationary = 0x04, TouchPointReleased = 0x08,
TouchPointStateMask = 0x0f, TouchPointPrimary = 0x10
}
This enum represents the state of a touch point at the time the QTouchEvent occurred.
enum TransformationMode { FastTransformation, SmoothTransformation }
enum UIEffect {
UI_General, UI_AnimateMenu, UI_FadeMenu, UI_AnimateCombo,
UI_AnimateTooltip, UI_FadeTooltip, UI_AnimateToolBox
}
enum WhiteSpaceMode { WhiteSpaceNormal, WhiteSpacePre, WhiteSpaceNoWrap, WhiteSpaceModeUndefined = -1 }
enum WidgetAttribute {
WA_Disabled = 0, WA_UnderMouse = 1, WA_MouseTracking = 2, WA_ContentsPropagated = 3,
WA_OpaquePaintEvent = 4, WA_NoBackground = WA_OpaquePaintEvent, WA_StaticContents = 5, WA_LaidOut = 7,
WA_PaintOnScreen = 8, WA_NoSystemBackground = 9, WA_UpdatesDisabled = 10, WA_Mapped = 11,
WA_MacNoClickThrough = 12, WA_PaintOutsidePaintEvent = 13, WA_InputMethodEnabled = 14, WA_WState_Visible = 15,
WA_WState_Hidden = 16, WA_ForceDisabled = 32, WA_KeyCompression = 33, WA_PendingMoveEvent = 34,
WA_PendingResizeEvent = 35, WA_SetPalette = 36, WA_SetFont = 37, WA_SetCursor = 38,
WA_NoChildEventsFromChildren = 39, WA_WindowModified = 41, WA_Resized = 42, WA_Moved = 43,
WA_PendingUpdate = 44, WA_InvalidSize = 45, WA_MacBrushedMetal = 46, WA_MacMetalStyle = WA_MacBrushedMetal,
WA_CustomWhatsThis = 47, WA_LayoutOnEntireRect = 48, WA_OutsideWSRange = 49, WA_GrabbedShortcut = 50,
WA_TransparentForMouseEvents = 51, WA_PaintUnclipped = 52, WA_SetWindowIcon = 53, WA_NoMouseReplay = 54,
WA_DeleteOnClose = 55, WA_RightToLeft = 56, WA_SetLayoutDirection = 57, WA_NoChildEventsForParent = 58,
WA_ForceUpdatesDisabled = 59, WA_WState_Created = 60, WA_WState_CompressKeys = 61, WA_WState_InPaintEvent = 62,
WA_WState_Reparented = 63, WA_WState_ConfigPending = 64, WA_WState_Polished = 66, WA_WState_DND = 67,
WA_WState_OwnSizePolicy = 68, WA_WState_ExplicitShowHide = 69, WA_ShowModal = 70, WA_MouseNoMask = 71,
WA_GroupLeader = 72, WA_NoMousePropagation = 73, WA_Hover = 74, WA_InputMethodTransparent = 75,
WA_QuitOnClose = 76, WA_KeyboardFocusChange = 77, WA_AcceptDrops = 78, WA_DropSiteRegistered = 79,
WA_ForceAcceptDrops = WA_DropSiteRegistered, WA_WindowPropagation = 80, WA_NoX11EventCompression = 81, WA_TintedBackground = 82,
WA_X11OpenGLOverlay = 83, WA_AlwaysShowToolTips = 84, WA_MacOpaqueSizeGrip = 85, WA_SetStyle = 86,
WA_SetLocale = 87, WA_MacShowFocusRect = 88, WA_MacNormalSize = 89, WA_MacSmallSize = 90,
WA_MacMiniSize = 91, WA_LayoutUsesWidgetRect = 92, WA_StyledBackground = 93, WA_MSWindowsUseDirect3D = 94,
WA_CanHostQMdiSubWindowTitleBar = 95, WA_MacAlwaysShowToolWindow = 96, WA_StyleSheet = 97, WA_ShowWithoutActivating = 98,
WA_X11BypassTransientForHint = 99, WA_NativeWindow = 100, WA_DontCreateNativeAncestors = 101, WA_MacVariableSize = 102,
WA_DontShowOnScreen = 103, WA_X11NetWmWindowTypeDesktop = 104, WA_X11NetWmWindowTypeDock = 105, WA_X11NetWmWindowTypeToolBar = 106,
WA_X11NetWmWindowTypeMenu = 107, WA_X11NetWmWindowTypeUtility = 108, WA_X11NetWmWindowTypeSplash = 109, WA_X11NetWmWindowTypeDialog = 110,
WA_X11NetWmWindowTypeDropDownMenu = 111, WA_X11NetWmWindowTypePopupMenu = 112, WA_X11NetWmWindowTypeToolTip = 113, WA_X11NetWmWindowTypeNotification = 114,
WA_X11NetWmWindowTypeCombo = 115, WA_X11NetWmWindowTypeDND = 116, WA_MacFrameworkScaled = 117, WA_SetWindowModality = 118,
WA_WState_WindowOpacitySet = 119, WA_TranslucentBackground = 120, WA_AcceptTouchEvents = 121, WA_WState_AcceptedTouchBeginEvent = 122,
WA_TouchPadAcceptSingleTouchEvents = 123, WA_MergeSoftkeys = 124, WA_MergeSoftkeysRecursively = 125, WA_LockPortraitOrientation = 128,
WA_LockLandscapeOrientation = 129, WA_AutoOrientation = 130, WA_X11DoNotAcceptFocus = 132, WA_SymbianNoSystemRotation = 133,
WA_MacNoShadow = 134, WA_AttributeCount
}
enum WindowFrameSection {
NoSection, LeftSection, TopLeftSection, TopSection,
TopRightSection, RightSection, BottomRightSection, BottomSection,
BottomLeftSection, TitleBarArea
}
enum WindowModality { NonModal, WindowModal, ApplicationModal }
enum WindowState {
WindowNoState = 0x00000000, WindowMinimized = 0x00000001, WindowMaximized = 0x00000002, WindowFullScreen = 0x00000004,
WindowActive = 0x00000008
}
enum WindowType {
Widget = 0x00000000, Window = 0x00000001, Dialog = 0x00000002 | Window, Sheet = 0x00000004 | Window,
Drawer = 0x00000006 | Window, Popup = 0x00000008 | Window, Tool = 0x0000000a | Window, ToolTip = 0x0000000c | Window,
SplashScreen = 0x0000000e | Window, Desktop = 0x00000010 | Window, SubWindow = 0x00000012, WindowType_Mask = 0x000000ff,
MSWindowsFixedSizeDialogHint = 0x00000100, MSWindowsOwnDC = 0x00000200, X11BypassWindowManagerHint = 0x00000400, FramelessWindowHint = 0x00000800,
WindowTitleHint = 0x00001000, WindowSystemMenuHint = 0x00002000, WindowMinimizeButtonHint = 0x00004000, WindowMaximizeButtonHint = 0x00008000,
WindowMinMaxButtonsHint = WindowMinimizeButtonHint | WindowMaximizeButtonHint, WindowContextHelpButtonHint = 0x00010000, WindowShadeButtonHint = 0x00020000, WindowStaysOnTopHint = 0x00040000,
CustomizeWindowHint = 0x02000000, WindowStaysOnBottomHint = 0x04000000, WindowCloseButtonHint = 0x08000000, MacWindowToolBarButtonHint = 0x10000000,
BypassGraphicsProxyWidget = 0x20000000, WindowOkButtonHint = 0x00080000, WindowCancelButtonHint = 0x00100000, WindowSoftkeysVisibleHint = 0x40000000,
WindowSoftkeysRespondHint = 0x80000000
}
Functions
Q_GUI_EXPORT QTextCodec * codecForHtml (const QByteArray &ba)
This function is defined in the <QTextDocument> header file.
Q_GUI_EXPORT QString convertFromPlainText (const QString &plain, WhiteSpaceMode mode=WhiteSpacePre)
Converts the plain text string plain to an HTML-formatted paragraph while preserving most of its look.
Q_GUI_EXPORT QString escape (const QString &plain)
Converts the plain text string plain to a HTML string with HTML metacharacters <, >, &, and " replaced by HTML entities.
Q_GUI_EXPORT bool mightBeRichText (const QString &)
Returns true if the string text is likely to be rich text; otherwise returns false.
Typedef Documentation
HANDLE
typedef void* Qt::HANDLE
Definition at line 1671 of file qnamespace.h.
WFlags
typedef WindowFlags Qt::WFlags
Definition at line 1681 of file qnamespace.h.
Enumeration Type Documentation
AlignmentFlag
enum Qt::AlignmentFlag
Enumerator
AlignLeft
AlignLeading
AlignRight
AlignTrailing
AlignHCenter
AlignJustify
AlignAbsolute
AlignHorizontal_Mask
AlignTop
AlignBottom
AlignVCenter
AlignVertical_Mask
AlignCenter
Definition at line 208 of file qnamespace.h.
{
         AlignLeft = 0x0001,
         AlignLeading = AlignLeft,
         AlignRight = 0x0002,
         AlignTrailing = AlignRight,
         AlignHCenter = 0x0004,
         AlignJustify = 0x0008,
         AlignAbsolute = 0x0010,
         AlignHorizontal_Mask = AlignLeft | AlignRight | AlignHCenter | AlignJustify | AlignAbsolute,
         AlignTop = 0x0020,
         AlignBottom = 0x0040,
         AlignVCenter = 0x0080,
         AlignVertical_Mask = AlignTop | AlignBottom | AlignVCenter,
         AlignCenter = AlignVCenter | AlignHCenter
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         , AlignAuto = AlignLeft
 #endif
     };
AnchorAttribute
enum Qt::AnchorAttribute
Enumerator
AnchorName
AnchorHref
Definition at line 1332 of file qnamespace.h.
{
         AnchorName,
         AnchorHref
     };
AnchorPoint
enum Qt::AnchorPoint
Enumerator
AnchorLeft
AnchorHorizontalCenter
AnchorRight
AnchorTop
AnchorVerticalCenter
AnchorBottom
Definition at line 1586 of file qnamespace.h.
                      {
         AnchorLeft = 0,
         AnchorHorizontalCenter,
         AnchorRight,
         AnchorTop,
         AnchorVerticalCenter,
         AnchorBottom
     };
ApplicationAttribute
enum Qt::ApplicationAttribute
Enumerator
AA_ImmediateWidgetCreation
AA_MSWindowsUseDirect3DByDefault
AA_DontShowIconsInMenus
AA_NativeWindows
AA_DontCreateNativeWidgetSiblings
AA_MacPluginApplication
AA_DontUseNativeMenuBar
AA_MacDontSwapCtrlAndMeta
AA_S60DontConstructApplicationPanes
AA_S60DisablePartialScreenInputMode
AA_X11InitThreads
AA_CaptureMultimediaKeys
AA_AttributeCount
Definition at line 536 of file qnamespace.h.
     {
         AA_ImmediateWidgetCreation = 0,
         AA_MSWindowsUseDirect3DByDefault = 1, // Win only
         AA_DontShowIconsInMenus = 2,
         AA_NativeWindows = 3,
         AA_DontCreateNativeWidgetSiblings = 4,
         AA_MacPluginApplication = 5,
         AA_DontUseNativeMenuBar = 6,
         AA_MacDontSwapCtrlAndMeta = 7,
         AA_S60DontConstructApplicationPanes = 8,
         AA_S60DisablePartialScreenInputMode = 9,
         AA_X11InitThreads = 10,
         AA_CaptureMultimediaKeys = 11,
         // Add new attributes before this line
         AA_AttributeCount
     };
ArrowType
enum Qt::ArrowType
Enumerator
NoArrow
UpArrow
DownArrow
LeftArrow
RightArrow
Definition at line 1126 of file qnamespace.h.
                    {
         NoArrow,
         UpArrow,
         DownArrow,
         LeftArrow,
         RightArrow
     };
AspectRatioMode
enum Qt::AspectRatioMode
Enumerator
IgnoreAspectRatio
KeepAspectRatio
KeepAspectRatioByExpanding
Definition at line 1317 of file qnamespace.h.
{
         IgnoreAspectRatio,
         KeepAspectRatio,
         KeepAspectRatioByExpanding
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         , ScaleFree = IgnoreAspectRatio,
         ScaleMin = KeepAspectRatio,
         ScaleMax = KeepAspectRatioByExpanding
 #endif
     };
Axis
enum Qt::Axis
Enumerator
XAxis
YAxis
ZAxis
Definition at line 1515 of file qnamespace.h.
               {
         XAxis,
         YAxis,
         ZAxis
     };
BGMode
enum Qt::BGMode
Enumerator
TransparentMode
OpaqueMode
Definition at line 588 of file qnamespace.h.
                 {
         TransparentMode,
         OpaqueMode
     };
BrushStyle
enum Qt::BrushStyle
Enumerator
NoBrush
SolidPattern
Dense1Pattern
Dense2Pattern
Dense3Pattern
Dense4Pattern
Dense5Pattern
Dense6Pattern
Dense7Pattern
HorPattern
VerPattern
CrossPattern
BDiagPattern
FDiagPattern
DiagCrossPattern
LinearGradientPattern
RadialGradientPattern
ConicalGradientPattern
TexturePattern
Definition at line 1162 of file qnamespace.h.
                     { // brush style
         NoBrush,
         SolidPattern,
         Dense1Pattern,
         Dense2Pattern,
         Dense3Pattern,
         Dense4Pattern,
         Dense5Pattern,
         Dense6Pattern,
         Dense7Pattern,
         HorPattern,
         VerPattern,
         CrossPattern,
         BDiagPattern,
         FDiagPattern,
         DiagCrossPattern,
         LinearGradientPattern,
         RadialGradientPattern,
         ConicalGradientPattern,
         TexturePattern = 24
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         , CustomPattern = TexturePattern
 #endif
     };
CaseSensitivity
enum Qt::CaseSensitivity
Enumerator
CaseInsensitive
CaseSensitive
Definition at line 1451 of file qnamespace.h.
{
         CaseInsensitive,
         CaseSensitive
     };
CheckState
enum Qt::CheckState
Enumerator
Unchecked
PartiallyChecked
Checked
Definition at line 1607 of file qnamespace.h.
                     {
         Unchecked,
         PartiallyChecked,
         Checked
     };
ClipOperation
enum Qt::ClipOperation
Enumerator
NoClip
ReplaceClip
IntersectClip
UniteClip
Definition at line 1495 of file qnamespace.h.
{
         NoClip,
         ReplaceClip,
         IntersectClip,
         UniteClip
     };
ConnectionType
enum Qt::ConnectionType
Enumerator
AutoConnection
DirectConnection
QueuedConnection
AutoCompatConnection
BlockingQueuedConnection
UniqueConnection
Definition at line 1469 of file qnamespace.h.
{
         AutoConnection,
         DirectConnection,
         QueuedConnection,
         AutoCompatConnection,
         BlockingQueuedConnection,
         UniqueConnection =  0x80
     };
ContextMenuPolicy
enum Qt::ContextMenuPolicy
Enumerator
NoContextMenu
DefaultContextMenu
ActionsContextMenu
CustomContextMenu
PreventContextMenu
Definition at line 1533 of file qnamespace.h.
{
         NoContextMenu,
         DefaultContextMenu,
         ActionsContextMenu,
         CustomContextMenu,
         PreventContextMenu
     };
CoordinateSystem
enum Qt::CoordinateSystem
Enumerator
DeviceCoordinates
LogicalCoordinates
Definition at line 1733 of file qnamespace.h.
{
         DeviceCoordinates,
         LogicalCoordinates
     };
Corner
enum Qt::Corner
Enumerator
TopLeftCorner
TopRightCorner
BottomLeftCorner
BottomRightCorner
Definition at line 1456 of file qnamespace.h.
                 {
         TopLeftCorner = 0x00000,
         TopRightCorner = 0x00001,
         BottomLeftCorner = 0x00002,
         BottomRightCorner = 0x00003
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         ,TopLeft = TopLeftCorner,
         TopRight = TopRightCorner,
         BottomLeft = BottomLeftCorner,
         BottomRight = BottomRightCorner
 #endif
     };
CursorMoveStyle
enum Qt::CursorMoveStyle
This enum describes the movement style available to text cursors.
Since
4.8
The options are:
LogicalMoveStyle Within a left-to-right text block, decrease cursor position when pressing left arrow key, increase cursor position when pressing the right arrow key. If the text block is right-to-left, the opposite behavior applies.
VisualMoveStyle Pressing the left arrow key will always cause the cursor to move left, regardless of the text's writing direction. Pressing the right arrow key will always cause the cursor to move right.
Enumerator
LogicalMoveStyle
VisualMoveStyle
Definition at line 1790 of file qnamespace.h.
{
         LogicalMoveStyle,
         VisualMoveStyle
     };
CursorShape
enum Qt::CursorShape
Enumerator
ArrowCursor
UpArrowCursor
CrossCursor
WaitCursor
IBeamCursor
SizeVerCursor
SizeHorCursor
SizeBDiagCursor
SizeFDiagCursor
SizeAllCursor
BlankCursor
SplitVCursor
SplitHCursor
PointingHandCursor
ForbiddenCursor
WhatsThisCursor
BusyCursor
OpenHandCursor
ClosedHandCursor
DragCopyCursor
DragMoveCursor
DragLinkCursor
LastCursor
BitmapCursor
CustomCursor
Definition at line 1262 of file qnamespace.h.
                      {
         ArrowCursor,
         UpArrowCursor,
         CrossCursor,
         WaitCursor,
         IBeamCursor,
         SizeVerCursor,
         SizeHorCursor,
         SizeBDiagCursor,
         SizeFDiagCursor,
         SizeAllCursor,
         BlankCursor,
         SplitVCursor,
         SplitHCursor,
         PointingHandCursor,
         ForbiddenCursor,
         WhatsThisCursor,
         BusyCursor,
         OpenHandCursor,
         ClosedHandCursor,
         DragCopyCursor,
         DragMoveCursor,
         DragLinkCursor,
         LastCursor = DragLinkCursor,
         BitmapCursor = 24,
         CustomCursor = 25
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         ,
         arrowCursor = ArrowCursor,
         upArrowCursor = UpArrowCursor,
         crossCursor = CrossCursor,
         waitCursor = WaitCursor,
         ibeamCursor = IBeamCursor,
         sizeVerCursor = SizeVerCursor,
         sizeHorCursor = SizeHorCursor,
         sizeBDiagCursor = SizeBDiagCursor,
         sizeFDiagCursor = SizeFDiagCursor,
         sizeAllCursor = SizeAllCursor,
         blankCursor = BlankCursor,
         splitVCursor = SplitVCursor,
         splitHCursor = SplitHCursor,
         pointingHandCursor = PointingHandCursor,
         forbiddenCursor = ForbiddenCursor,
         whatsThisCursor = WhatsThisCursor
 #endif
     };
DateFormat
enum Qt::DateFormat
Enumerator
TextDate
ISODate
SystemLocaleDate
LocalDate
LocaleDate
SystemLocaleShortDate
SystemLocaleLongDate
DefaultLocaleShortDate
DefaultLocaleLongDate
Definition at line 1392 of file qnamespace.h.
                     {
         TextDate,      // default Qt
         ISODate,       // ISO 8601
         SystemLocaleDate, // deprecated
         LocalDate = SystemLocaleDate, // deprecated
         LocaleDate,     // deprecated
         SystemLocaleShortDate,
         SystemLocaleLongDate,
         DefaultLocaleShortDate,
         DefaultLocaleLongDate
     };
DayOfWeek
enum Qt::DayOfWeek
Enumerator
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
Definition at line 1410 of file qnamespace.h.
                    {
         Monday = 1,
         Tuesday = 2,
         Wednesday = 3,
         Thursday = 4,
         Friday = 5,
         Saturday = 6,
         Sunday = 7
     };
DockWidgetArea
enum Qt::DockWidgetArea
Enumerator
LeftDockWidgetArea
RightDockWidgetArea
TopDockWidgetArea
BottomDockWidgetArea
DockWidgetArea_Mask
AllDockWidgetAreas
NoDockWidgetArea
Definition at line 1337 of file qnamespace.h.
{
         LeftDockWidgetArea = 0x1,
         RightDockWidgetArea = 0x2,
         TopDockWidgetArea = 0x4,
         BottomDockWidgetArea = 0x8,
         DockWidgetArea_Mask = 0xf,
         AllDockWidgetAreas = DockWidgetArea_Mask,
         NoDockWidgetArea = 0
     };
DockWidgetAreaSizes
enum Qt::DockWidgetAreaSizes
Enumerator
NDockWidgetAreas
Definition at line 1347 of file qnamespace.h.
{
         NDockWidgetAreas = 4
     };
DropAction
enum Qt::DropAction
Enumerator
CopyAction
MoveAction
LinkAction
ActionMask
TargetMoveAction
IgnoreAction
Definition at line 1597 of file qnamespace.h.
                     {
         CopyAction = 0x1,
         MoveAction = 0x2,
         LinkAction = 0x4,
         ActionMask = 0xff,
         TargetMoveAction = 0x8002,
         IgnoreAction = 0x0
     };
EventPriority
enum Qt::EventPriority
Enumerator
HighEventPriority
NormalEventPriority
LowEventPriority
Definition at line 1702 of file qnamespace.h.
{
         HighEventPriority = 1,
         NormalEventPriority = 0,
         LowEventPriority = -1
     };
FillRule
enum Qt::FillRule
Enumerator
OddEvenFill
WindingFill
Definition at line 1485 of file qnamespace.h.
                   {
         OddEvenFill,
         WindingFill
     };
FocusPolicy
enum Qt::FocusPolicy
Enumerator
NoFocus
TabFocus
ClickFocus
StrongFocus
WheelFocus
Definition at line 181 of file qnamespace.h.
                      {
         NoFocus = 0,
         TabFocus = 0x1,
         ClickFocus = 0x2,
         StrongFocus = TabFocus | ClickFocus | 0x8,
         WheelFocus = StrongFocus | 0x4
     };
FocusReason
enum Qt::FocusReason
Enumerator
MouseFocusReason
TabFocusReason
BacktabFocusReason
ActiveWindowFocusReason
PopupFocusReason
ShortcutFocusReason
MenuBarFocusReason
OtherFocusReason
NoFocusReason
Definition at line 1521 of file qnamespace.h.
                      {
         MouseFocusReason,
         TabFocusReason,
         BacktabFocusReason,
         ActiveWindowFocusReason,
         PopupFocusReason,
         ShortcutFocusReason,
         MenuBarFocusReason,
         OtherFocusReason,
         NoFocusReason
     };
GestureFlag
enum Qt::GestureFlag
Enumerator
DontStartGestureOnChildren
ReceivePartialGestures
IgnoredGesturesPropagateToParent
Definition at line 1772 of file qnamespace.h.
     {
         DontStartGestureOnChildren = 0x01,
         ReceivePartialGestures     = 0x02,
         IgnoredGesturesPropagateToParent = 0x04
     };
GestureState
enum Qt::GestureState
Enumerator
NoGesture
GestureStarted
GestureUpdated
GestureFinished
GestureCanceled
Definition at line 1750 of file qnamespace.h.
     {
         NoGesture,
         GestureStarted  = 1,
         GestureUpdated  = 2,
         GestureFinished = 3,
         GestureCanceled = 4
     };
GestureType
enum Qt::GestureType
Enumerator
TapGesture
TapAndHoldGesture
PanGesture
PinchGesture
SwipeGesture
CustomGesture
LastGestureType
Definition at line 1759 of file qnamespace.h.
     {
         TapGesture        = 1,
         TapAndHoldGesture = 2,
         PanGesture        = 3,
         PinchGesture      = 4,
         SwipeGesture      = 5,
         CustomGesture     = 0x0100,
         LastGestureType   = ~0u
     };
GlobalColor
enum Qt::GlobalColor
Enumerator
color0
color1
black
white
darkGray
gray
lightGray
red
green
blue
cyan
magenta
yellow
darkRed
darkGreen
darkBlue
darkCyan
darkMagenta
darkYellow
transparent
Definition at line 104 of file qnamespace.h.
                      {
         color0,
         color1,
         black,
         white,
         darkGray,
         gray,
         lightGray,
         red,
         green,
         blue,
         cyan,
         magenta,
         yellow,
         darkRed,
         darkGreen,
         darkBlue,
         darkCyan,
         darkMagenta,
         darkYellow,
         transparent
     };
HitTestAccuracy
enum Qt::HitTestAccuracy
Enumerator
ExactHit
FuzzyHit
Definition at line 78 of file qtextdocument.h.
 { ExactHit, FuzzyHit };
ImageConversionFlag
enum Qt::ImageConversionFlag
Enumerator
ColorMode_Mask
AutoColor
ColorOnly
MonoOnly
AlphaDither_Mask
ThresholdAlphaDither
OrderedAlphaDither
DiffuseAlphaDither
NoAlpha
Dither_Mask
DiffuseDither
OrderedDither
ThresholdDither
DitherMode_Mask
AutoDither
PreferDither
AvoidDither
NoOpaqueDetection
NoFormatConversion
Definition at line 559 of file qnamespace.h.
{
         ColorMode_Mask          = 0x00000003,
         AutoColor               = 0x00000000,
         ColorOnly               = 0x00000003,
         MonoOnly                = 0x00000002,
         // Reserved             = 0x00000001,
         AlphaDither_Mask        = 0x0000000c,
         ThresholdAlphaDither    = 0x00000000,
         OrderedAlphaDither      = 0x00000004,
         DiffuseAlphaDither      = 0x00000008,
         NoAlpha                 = 0x0000000c, // Not supported
         Dither_Mask             = 0x00000030,
         DiffuseDither           = 0x00000000,
         OrderedDither           = 0x00000010,
         ThresholdDither         = 0x00000020,
         // ReservedDither       = 0x00000030,
         DitherMode_Mask         = 0x000000c0,
         AutoDither              = 0x00000000,
         PreferDither            = 0x00000040,
         AvoidDither             = 0x00000080,
         NoOpaqueDetection       = 0x00000100,
         NoFormatConversion      = 0x00000200
     };
Initialization
enum Qt::Initialization
Enumerator
Uninitialized
Definition at line 1729 of file qnamespace.h.
{
         Uninitialized
     };
InputMethodHint
enum Qt::InputMethodHint
Enumerator
ImhNone
ImhHiddenText
ImhNoAutoUppercase
ImhPreferNumbers
ImhPreferUppercase
ImhPreferLowercase
ImhNoPredictiveText
ImhDigitsOnly
ImhFormattedNumbersOnly
ImhUppercaseOnly
ImhLowercaseOnly
ImhDialableCharactersOnly
ImhEmailCharactersOnly
ImhUrlCharactersOnly
ImhExclusiveInputMask
Definition at line 1551 of file qnamespace.h.
{
         ImhNone = 0x0,
         ImhHiddenText = 0x1,
         ImhNoAutoUppercase = 0x2,
         ImhPreferNumbers = 0x4,
         ImhPreferUppercase = 0x8,
         ImhPreferLowercase = 0x10,
         ImhNoPredictiveText = 0x20,
         ImhDigitsOnly = 0x10000,
         ImhFormattedNumbersOnly = 0x20000,
         ImhUppercaseOnly = 0x40000,
         ImhLowercaseOnly = 0x80000,
         ImhDialableCharactersOnly = 0x100000,
         ImhEmailCharactersOnly = 0x200000,
         ImhUrlCharactersOnly = 0x400000,
         ImhExclusiveInputMask = 0xffff0000
     };
InputMethodQuery
enum Qt::InputMethodQuery
Enumerator
ImMicroFocus
ImFont
ImCursorPosition
ImSurroundingText
ImCurrentSelection
ImMaximumTextLength
ImAnchorPosition
Definition at line 1541 of file qnamespace.h.
{
         ImMicroFocus,
         ImFont,
         ImCursorPosition,
         ImSurroundingText,
         ImCurrentSelection,
         ImMaximumTextLength,
         ImAnchorPosition
     };
ItemDataRole
enum Qt::ItemDataRole
Enumerator
DisplayRole
DecorationRole
EditRole
ToolTipRole
StatusTipRole
WhatsThisRole
FontRole
TextAlignmentRole
BackgroundColorRole
BackgroundRole
TextColorRole
ForegroundRole
CheckStateRole
AccessibleTextRole
AccessibleDescriptionRole
SizeHintRole
InitialSortOrderRole
DisplayPropertyRole
DecorationPropertyRole
ToolTipPropertyRole
StatusTipPropertyRole
WhatsThisPropertyRole
UserRole
Definition at line 1613 of file qnamespace.h.
                       {
         DisplayRole = 0,
         DecorationRole = 1,
         EditRole = 2,
         ToolTipRole = 3,
         StatusTipRole = 4,
         WhatsThisRole = 5,
         // Metadata
         FontRole = 6,
         TextAlignmentRole = 7,
         BackgroundColorRole = 8,
         BackgroundRole = 8,
         TextColorRole = 9,
         ForegroundRole = 9,
         CheckStateRole = 10,
         // Accessibility
         AccessibleTextRole = 11,
         AccessibleDescriptionRole = 12,
         // More general purpose
         SizeHintRole = 13,
         InitialSortOrderRole = 14,
         // Internal UiLib roles. Start worrying when public roles go that high.
         DisplayPropertyRole = 27,
         DecorationPropertyRole = 28,
         ToolTipPropertyRole = 29,
         StatusTipPropertyRole = 30,
         WhatsThisPropertyRole = 31,
         // Reserved
         UserRole = 32
     };
ItemFlag
enum Qt::ItemFlag
Enumerator
NoItemFlags
ItemIsSelectable
ItemIsEditable
ItemIsDragEnabled
ItemIsDropEnabled
ItemIsUserCheckable
ItemIsEnabled
ItemIsTristate
Definition at line 1644 of file qnamespace.h.
                   {
         NoItemFlags = 0,
         ItemIsSelectable = 1,
         ItemIsEditable = 2,
         ItemIsDragEnabled = 4,
         ItemIsDropEnabled = 8,
         ItemIsUserCheckable = 16,
         ItemIsEnabled = 32,
         ItemIsTristate = 64
     };
ItemSelectionMode
enum Qt::ItemSelectionMode
Enumerator
ContainsItemShape
IntersectsItemShape
ContainsItemBoundingRect
IntersectsItemBoundingRect
Definition at line 1503 of file qnamespace.h.
{
         ContainsItemShape = 0x0,
         IntersectsItemShape = 0x1,
         ContainsItemBoundingRect = 0x2,
         IntersectsItemBoundingRect = 0x3
     };
Key
enum Qt::Key
Enumerator
Key_Escape
Key_Tab
Key_Backtab
Key_Backspace
Key_Return
Key_Enter
Key_Insert
Key_Delete
Key_Pause
Key_Print
Key_SysReq
Key_Clear
Key_Home
Key_End
Key_Left
Key_Up
Key_Right
Key_Down
Key_PageUp
Key_PageDown
Key_Shift
Key_Control
Key_Meta
Key_Alt
Key_CapsLock
Key_NumLock
Key_ScrollLock
Key_F1
Key_F2
Key_F3
Key_F4
Key_F5
Key_F6
Key_F7
Key_F8
Key_F9
Key_F10
Key_F11
Key_F12
Key_F13
Key_F14
Key_F15
Key_F16
Key_F17
Key_F18
Key_F19
Key_F20
Key_F21
Key_F22
Key_F23
Key_F24
Key_F25
Key_F26
Key_F27
Key_F28
Key_F29
Key_F30
Key_F31
Key_F32
Key_F33
Key_F34
Key_F35
Key_Super_L
Key_Super_R
Key_Menu
Key_Hyper_L
Key_Hyper_R
Key_Help
Key_Direction_L
Key_Direction_R
Key_Space
Key_Any
Key_Exclam
Key_QuoteDbl
Key_NumberSign
Key_Dollar
Key_Percent
Key_Ampersand
Key_Apostrophe
Key_ParenLeft
Key_ParenRight
Key_Asterisk
Key_Plus
Key_Comma
Key_Minus
Key_Period
Key_Slash
Key_0
Key_1
Key_2
Key_3
Key_4
Key_5
Key_6
Key_7
Key_8
Key_9
Key_Colon
Key_Semicolon
Key_Less
Key_Equal
Key_Greater
Key_Question
Key_At
Key_A
Key_B
Key_C
Key_D
Key_E
Key_F
Key_G
Key_H
Key_I
Key_J
Key_K
Key_L
Key_M
Key_N
Key_O
Key_P
Key_Q
Key_R
Key_S
Key_T
Key_U
Key_V
Key_W
Key_X
Key_Y
Key_Z
Key_BracketLeft
Key_Backslash
Key_BracketRight
Key_AsciiCircum
Key_Underscore
Key_QuoteLeft
Key_BraceLeft
Key_Bar
Key_BraceRight
Key_AsciiTilde
Key_nobreakspace
Key_exclamdown
Key_cent
Key_sterling
Key_currency
Key_yen
Key_brokenbar
Key_section
Key_diaeresis
Key_copyright
Key_ordfeminine
Key_guillemotleft
Key_notsign
Key_hyphen
Key_registered
Key_macron
Key_degree
Key_plusminus
Key_twosuperior
Key_threesuperior
Key_acute
Key_mu
Key_paragraph
Key_periodcentered
Key_cedilla
Key_onesuperior
Key_masculine
Key_guillemotright
Key_onequarter
Key_onehalf
Key_threequarters
Key_questiondown
Key_Agrave
Key_Aacute
Key_Acircumflex
Key_Atilde
Key_Adiaeresis
Key_Aring
Key_AE
Key_Ccedilla
Key_Egrave
Key_Eacute
Key_Ecircumflex
Key_Ediaeresis
Key_Igrave
Key_Iacute
Key_Icircumflex
Key_Idiaeresis
Key_ETH
Key_Ntilde
Key_Ograve
Key_Oacute
Key_Ocircumflex
Key_Otilde
Key_Odiaeresis
Key_multiply
Key_Ooblique
Key_Ugrave
Key_Uacute
Key_Ucircumflex
Key_Udiaeresis
Key_Yacute
Key_THORN
Key_ssharp
Key_division
Key_ydiaeresis
Key_AltGr
Key_Multi_key
Key_Codeinput
Key_SingleCandidate
Key_MultipleCandidate
Key_PreviousCandidate
Key_Mode_switch
Key_Kanji
Key_Muhenkan
Key_Henkan
Key_Romaji
Key_Hiragana
Key_Katakana
Key_Hiragana_Katakana
Key_Zenkaku
Key_Hankaku
Key_Zenkaku_Hankaku
Key_Touroku
Key_Massyo
Key_Kana_Lock
Key_Kana_Shift
Key_Eisu_Shift
Key_Eisu_toggle
Key_Hangul
Key_Hangul_Start
Key_Hangul_End
Key_Hangul_Hanja
Key_Hangul_Jamo
Key_Hangul_Romaja
Key_Hangul_Jeonja
Key_Hangul_Banja
Key_Hangul_PreHanja
Key_Hangul_PostHanja
Key_Hangul_Special
Key_Dead_Grave
Key_Dead_Acute
Key_Dead_Circumflex
Key_Dead_Tilde
Key_Dead_Macron
Key_Dead_Breve
Key_Dead_Abovedot
Key_Dead_Diaeresis
Key_Dead_Abovering
Key_Dead_Doubleacute
Key_Dead_Caron
Key_Dead_Cedilla
Key_Dead_Ogonek
Key_Dead_Iota
Key_Dead_Voiced_Sound
Key_Dead_Semivoiced_Sound
Key_Dead_Belowdot
Key_Dead_Hook
Key_Dead_Horn
Key_Back
Key_Forward
Key_Stop
Key_Refresh
Key_VolumeDown
Key_VolumeMute
Key_VolumeUp
Key_BassBoost
Key_BassUp
Key_BassDown
Key_TrebleUp
Key_TrebleDown
Key_MediaPlay
Key_MediaStop
Key_MediaPrevious
Key_MediaNext
Key_MediaRecord
Key_MediaPause
Key_MediaTogglePlayPause
Key_HomePage
Key_Favorites
Key_Search
Key_Standby
Key_OpenUrl
Key_LaunchMail
Key_LaunchMedia
Key_Launch0
Key_Launch1
Key_Launch2
Key_Launch3
Key_Launch4
Key_Launch5
Key_Launch6
Key_Launch7
Key_Launch8
Key_Launch9
Key_LaunchA
Key_LaunchB
Key_LaunchC
Key_LaunchD
Key_LaunchE
Key_LaunchF
Key_MonBrightnessUp
Key_MonBrightnessDown
Key_KeyboardLightOnOff
Key_KeyboardBrightnessUp
Key_KeyboardBrightnessDown
Key_PowerOff
Key_WakeUp
Key_Eject
Key_ScreenSaver
Key_WWW
Key_Memo
Key_LightBulb
Key_Shop
Key_History
Key_AddFavorite
Key_HotLinks
Key_BrightnessAdjust
Key_Finance
Key_Community
Key_AudioRewind
Key_BackForward
Key_ApplicationLeft
Key_ApplicationRight
Key_Book
Key_CD
Key_Calculator
Key_ToDoList
Key_ClearGrab
Key_Close
Key_Copy
Key_Cut
Key_Display
Key_DOS
Key_Documents
Key_Excel
Key_Explorer
Key_Game
Key_Go
Key_iTouch
Key_LogOff
Key_Market
Key_Meeting
Key_MenuKB
Key_MenuPB
Key_MySites
Key_News
Key_OfficeHome
Key_Option
Key_Paste
Key_Phone
Key_Calendar
Key_Reply
Key_Reload
Key_RotateWindows
Key_RotationPB
Key_RotationKB
Key_Save
Key_Send
Key_Spell
Key_SplitScreen
Key_Support
Key_TaskPane
Key_Terminal
Key_Tools
Key_Travel
Key_Video
Key_Word
Key_Xfer
Key_ZoomIn
Key_ZoomOut
Key_Away
Key_Messenger
Key_WebCam
Key_MailForward
Key_Pictures
Key_Music
Key_Battery
Key_Bluetooth
Key_WLAN
Key_UWB
Key_AudioForward
Key_AudioRepeat
Key_AudioRandomPlay
Key_Subtitle
Key_AudioCycleTrack
Key_Time
Key_Hibernate
Key_View
Key_TopMenu
Key_PowerDown
Key_Suspend
Key_ContrastAdjust
Key_LaunchG
Key_LaunchH
Key_MediaLast
Key_Select
Key_Yes
Key_No
Key_Cancel
Key_Printer
Key_Execute
Key_Sleep
Key_Play
Key_Zoom
Key_Context1
Key_Context2
Key_Context3
Key_Context4
Key_Call
Key_Hangup
Key_Flip
Key_ToggleCallHangup
Key_VoiceDial
Key_LastNumberRedial
Key_Camera
Key_CameraFocus
Key_unknown
Definition at line 612 of file qnamespace.h.
              {
         Key_Escape = 0x01000000,                // misc keys
         Key_Tab = 0x01000001,
         Key_Backtab = 0x01000002,
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         Key_BackTab = Key_Backtab,
 #endif
         Key_Backspace = 0x01000003,
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         Key_BackSpace = Key_Backspace,
 #endif
         Key_Return = 0x01000004,
         Key_Enter = 0x01000005,
         Key_Insert = 0x01000006,
         Key_Delete = 0x01000007,
         Key_Pause = 0x01000008,
         Key_Print = 0x01000009,
         Key_SysReq = 0x0100000a,
         Key_Clear = 0x0100000b,
         Key_Home = 0x01000010,                // cursor movement
         Key_End = 0x01000011,
         Key_Left = 0x01000012,
         Key_Up = 0x01000013,
         Key_Right = 0x01000014,
         Key_Down = 0x01000015,
         Key_PageUp = 0x01000016,
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         Key_Prior = Key_PageUp,
 #endif
         Key_PageDown = 0x01000017,
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         Key_Next = Key_PageDown,
 #endif
         Key_Shift = 0x01000020,                // modifiers
         Key_Control = 0x01000021,
         Key_Meta = 0x01000022,
         Key_Alt = 0x01000023,
         Key_CapsLock = 0x01000024,
         Key_NumLock = 0x01000025,
         Key_ScrollLock = 0x01000026,
         Key_F1 = 0x01000030,                // function keys
         Key_F2 = 0x01000031,
         Key_F3 = 0x01000032,
         Key_F4 = 0x01000033,
         Key_F5 = 0x01000034,
         Key_F6 = 0x01000035,
         Key_F7 = 0x01000036,
         Key_F8 = 0x01000037,
         Key_F9 = 0x01000038,
         Key_F10 = 0x01000039,
         Key_F11 = 0x0100003a,
         Key_F12 = 0x0100003b,
         Key_F13 = 0x0100003c,
         Key_F14 = 0x0100003d,
         Key_F15 = 0x0100003e,
         Key_F16 = 0x0100003f,
         Key_F17 = 0x01000040,
         Key_F18 = 0x01000041,
         Key_F19 = 0x01000042,
         Key_F20 = 0x01000043,
         Key_F21 = 0x01000044,
         Key_F22 = 0x01000045,
         Key_F23 = 0x01000046,
         Key_F24 = 0x01000047,
         Key_F25 = 0x01000048,                // F25 .. F35 only on X11
         Key_F26 = 0x01000049,
         Key_F27 = 0x0100004a,
         Key_F28 = 0x0100004b,
         Key_F29 = 0x0100004c,
         Key_F30 = 0x0100004d,
         Key_F31 = 0x0100004e,
         Key_F32 = 0x0100004f,
         Key_F33 = 0x01000050,
         Key_F34 = 0x01000051,
         Key_F35 = 0x01000052,
         Key_Super_L = 0x01000053,                 // extra keys
         Key_Super_R = 0x01000054,
         Key_Menu = 0x01000055,
         Key_Hyper_L = 0x01000056,
         Key_Hyper_R = 0x01000057,
         Key_Help = 0x01000058,
         Key_Direction_L = 0x01000059,
         Key_Direction_R = 0x01000060,
         Key_Space = 0x20,                // 7 bit printable ASCII
         Key_Any = Key_Space,
         Key_Exclam = 0x21,
         Key_QuoteDbl = 0x22,
         Key_NumberSign = 0x23,
         Key_Dollar = 0x24,
         Key_Percent = 0x25,
         Key_Ampersand = 0x26,
         Key_Apostrophe = 0x27,
         Key_ParenLeft = 0x28,
         Key_ParenRight = 0x29,
         Key_Asterisk = 0x2a,
         Key_Plus = 0x2b,
         Key_Comma = 0x2c,
         Key_Minus = 0x2d,
         Key_Period = 0x2e,
         Key_Slash = 0x2f,
         Key_0 = 0x30,
         Key_1 = 0x31,
         Key_2 = 0x32,
         Key_3 = 0x33,
         Key_4 = 0x34,
         Key_5 = 0x35,
         Key_6 = 0x36,
         Key_7 = 0x37,
         Key_8 = 0x38,
         Key_9 = 0x39,
         Key_Colon = 0x3a,
         Key_Semicolon = 0x3b,
         Key_Less = 0x3c,
         Key_Equal = 0x3d,
         Key_Greater = 0x3e,
         Key_Question = 0x3f,
         Key_At = 0x40,
         Key_A = 0x41,
         Key_B = 0x42,
         Key_C = 0x43,
         Key_D = 0x44,
         Key_E = 0x45,
         Key_F = 0x46,
         Key_G = 0x47,
         Key_H = 0x48,
         Key_I = 0x49,
         Key_J = 0x4a,
         Key_K = 0x4b,
         Key_L = 0x4c,
         Key_M = 0x4d,
         Key_N = 0x4e,
         Key_O = 0x4f,
         Key_P = 0x50,
         Key_Q = 0x51,
         Key_R = 0x52,
         Key_S = 0x53,
         Key_T = 0x54,
         Key_U = 0x55,
         Key_V = 0x56,
         Key_W = 0x57,
         Key_X = 0x58,
         Key_Y = 0x59,
         Key_Z = 0x5a,
         Key_BracketLeft = 0x5b,
         Key_Backslash = 0x5c,
         Key_BracketRight = 0x5d,
         Key_AsciiCircum = 0x5e,
         Key_Underscore = 0x5f,
         Key_QuoteLeft = 0x60,
         Key_BraceLeft = 0x7b,
         Key_Bar = 0x7c,
         Key_BraceRight = 0x7d,
         Key_AsciiTilde = 0x7e,
         Key_nobreakspace = 0x0a0,
         Key_exclamdown = 0x0a1,
         Key_cent = 0x0a2,
         Key_sterling = 0x0a3,
         Key_currency = 0x0a4,
         Key_yen = 0x0a5,
         Key_brokenbar = 0x0a6,
         Key_section = 0x0a7,
         Key_diaeresis = 0x0a8,
         Key_copyright = 0x0a9,
         Key_ordfeminine = 0x0aa,
         Key_guillemotleft = 0x0ab,        // left angle quotation mark
         Key_notsign = 0x0ac,
         Key_hyphen = 0x0ad,
         Key_registered = 0x0ae,
         Key_macron = 0x0af,
         Key_degree = 0x0b0,
         Key_plusminus = 0x0b1,
         Key_twosuperior = 0x0b2,
         Key_threesuperior = 0x0b3,
         Key_acute = 0x0b4,
         Key_mu = 0x0b5,
         Key_paragraph = 0x0b6,
         Key_periodcentered = 0x0b7,
         Key_cedilla = 0x0b8,
         Key_onesuperior = 0x0b9,
         Key_masculine = 0x0ba,
         Key_guillemotright = 0x0bb,        // right angle quotation mark
         Key_onequarter = 0x0bc,
         Key_onehalf = 0x0bd,
         Key_threequarters = 0x0be,
         Key_questiondown = 0x0bf,
         Key_Agrave = 0x0c0,
         Key_Aacute = 0x0c1,
         Key_Acircumflex = 0x0c2,
         Key_Atilde = 0x0c3,
         Key_Adiaeresis = 0x0c4,
         Key_Aring = 0x0c5,
         Key_AE = 0x0c6,
         Key_Ccedilla = 0x0c7,
         Key_Egrave = 0x0c8,
         Key_Eacute = 0x0c9,
         Key_Ecircumflex = 0x0ca,
         Key_Ediaeresis = 0x0cb,
         Key_Igrave = 0x0cc,
         Key_Iacute = 0x0cd,
         Key_Icircumflex = 0x0ce,
         Key_Idiaeresis = 0x0cf,
         Key_ETH = 0x0d0,
         Key_Ntilde = 0x0d1,
         Key_Ograve = 0x0d2,
         Key_Oacute = 0x0d3,
         Key_Ocircumflex = 0x0d4,
         Key_Otilde = 0x0d5,
         Key_Odiaeresis = 0x0d6,
         Key_multiply = 0x0d7,
         Key_Ooblique = 0x0d8,
         Key_Ugrave = 0x0d9,
         Key_Uacute = 0x0da,
         Key_Ucircumflex = 0x0db,
         Key_Udiaeresis = 0x0dc,
         Key_Yacute = 0x0dd,
         Key_THORN = 0x0de,
         Key_ssharp = 0x0df,
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         Key_agrave = Key_Agrave,
         Key_aacute = Key_Aacute,
         Key_acircumflex = Key_Acircumflex,
         Key_atilde = Key_Atilde,
         Key_adiaeresis = Key_Adiaeresis,
         Key_aring = Key_Aring,
         Key_ae = Key_AE,
         Key_ccedilla = Key_Ccedilla,
         Key_egrave = Key_Egrave,
         Key_eacute = Key_Eacute,
         Key_ecircumflex = Key_Ecircumflex,
         Key_ediaeresis = Key_Ediaeresis,
         Key_igrave = Key_Igrave,
         Key_iacute = Key_Iacute,
         Key_icircumflex = Key_Icircumflex,
         Key_idiaeresis = Key_Idiaeresis,
         Key_eth = Key_ETH,
         Key_ntilde = Key_Ntilde,
         Key_ograve = Key_Ograve,
         Key_oacute = Key_Oacute,
         Key_ocircumflex = Key_Ocircumflex,
         Key_otilde = Key_Otilde,
         Key_odiaeresis = Key_Odiaeresis,
 #endif
         Key_division = 0x0f7,
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         Key_oslash = Key_Ooblique,
         Key_ugrave = Key_Ugrave,
         Key_uacute = Key_Uacute,
         Key_ucircumflex = Key_Ucircumflex,
         Key_udiaeresis = Key_Udiaeresis,
         Key_yacute = Key_Yacute,
         Key_thorn = Key_THORN,
 #endif
         Key_ydiaeresis = 0x0ff,
         // International input method support (X keycode - 0xEE00, the
         // definition follows Qt/Embedded 2.3.7) Only interesting if
         // you are writing your own input method
         // International & multi-key character composition
         Key_AltGr               = 0x01001103,
         Key_Multi_key           = 0x01001120,  // Multi-key character compose
         Key_Codeinput           = 0x01001137,
         Key_SingleCandidate     = 0x0100113c,
         Key_MultipleCandidate   = 0x0100113d,
         Key_PreviousCandidate   = 0x0100113e,
         // Misc Functions
         Key_Mode_switch         = 0x0100117e,  // Character set switch
         //Key_script_switch       = 0x0100117e,  // Alias for mode_switch
         // Japanese keyboard support
         Key_Kanji               = 0x01001121,  // Kanji, Kanji convert
         Key_Muhenkan            = 0x01001122,  // Cancel Conversion
         //Key_Henkan_Mode         = 0x01001123,  // Start/Stop Conversion
         Key_Henkan              = 0x01001123,  // Alias for Henkan_Mode
         Key_Romaji              = 0x01001124,  // to Romaji
         Key_Hiragana            = 0x01001125,  // to Hiragana
         Key_Katakana            = 0x01001126,  // to Katakana
         Key_Hiragana_Katakana   = 0x01001127,  // Hiragana/Katakana toggle
         Key_Zenkaku             = 0x01001128,  // to Zenkaku
         Key_Hankaku             = 0x01001129,  // to Hankaku
         Key_Zenkaku_Hankaku     = 0x0100112a,  // Zenkaku/Hankaku toggle
         Key_Touroku             = 0x0100112b,  // Add to Dictionary
         Key_Massyo              = 0x0100112c,  // Delete from Dictionary
         Key_Kana_Lock           = 0x0100112d,  // Kana Lock
         Key_Kana_Shift          = 0x0100112e,  // Kana Shift
         Key_Eisu_Shift          = 0x0100112f,  // Alphanumeric Shift
         Key_Eisu_toggle         = 0x01001130,  // Alphanumeric toggle
         //Key_Kanji_Bangou        = 0x01001137,  // Codeinput
         //Key_Zen_Koho            = 0x0100113d,  // Multiple/All Candidate(s)
         //Key_Mae_Koho            = 0x0100113e,  // Previous Candidate
         // Korean keyboard support
         //
         // In fact, many Korean users need only 2 keys, Key_Hangul and
         // Key_Hangul_Hanja. But rest of the keys are good for future.
         Key_Hangul              = 0x01001131,  // Hangul start/stop(toggle)
         Key_Hangul_Start        = 0x01001132,  // Hangul start
         Key_Hangul_End          = 0x01001133,  // Hangul end, English start
         Key_Hangul_Hanja        = 0x01001134,  // Start Hangul->Hanja Conversion
         Key_Hangul_Jamo         = 0x01001135,  // Hangul Jamo mode
         Key_Hangul_Romaja       = 0x01001136,  // Hangul Romaja mode
         //Key_Hangul_Codeinput    = 0x01001137,  // Hangul code input mode
         Key_Hangul_Jeonja       = 0x01001138,  // Jeonja mode
         Key_Hangul_Banja        = 0x01001139,  // Banja mode
         Key_Hangul_PreHanja     = 0x0100113a,  // Pre Hanja conversion
         Key_Hangul_PostHanja    = 0x0100113b,  // Post Hanja conversion
         //Key_Hangul_SingleCandidate   = 0x0100113c,  // Single candidate
         //Key_Hangul_MultipleCandidate = 0x0100113d,  // Multiple candidate
         //Key_Hangul_PreviousCandidate = 0x0100113e,  // Previous candidate
         Key_Hangul_Special      = 0x0100113f,  // Special symbols
         //Key_Hangul_switch       = 0x0100117e,  // Alias for mode_switch
         // dead keys (X keycode - 0xED00 to avoid the conflict)
         Key_Dead_Grave          = 0x01001250,
         Key_Dead_Acute          = 0x01001251,
         Key_Dead_Circumflex     = 0x01001252,
         Key_Dead_Tilde          = 0x01001253,
         Key_Dead_Macron         = 0x01001254,
         Key_Dead_Breve          = 0x01001255,
         Key_Dead_Abovedot       = 0x01001256,
         Key_Dead_Diaeresis      = 0x01001257,
         Key_Dead_Abovering      = 0x01001258,
         Key_Dead_Doubleacute    = 0x01001259,
         Key_Dead_Caron          = 0x0100125a,
         Key_Dead_Cedilla        = 0x0100125b,
         Key_Dead_Ogonek         = 0x0100125c,
         Key_Dead_Iota           = 0x0100125d,
         Key_Dead_Voiced_Sound   = 0x0100125e,
         Key_Dead_Semivoiced_Sound = 0x0100125f,
         Key_Dead_Belowdot       = 0x01001260,
         Key_Dead_Hook           = 0x01001261,
         Key_Dead_Horn           = 0x01001262,
         // multimedia/internet keys - ignored by default - see QKeyEvent c'tor
         Key_Back  = 0x01000061,
         Key_Forward  = 0x01000062,
         Key_Stop  = 0x01000063,
         Key_Refresh  = 0x01000064,
         Key_VolumeDown = 0x01000070,
         Key_VolumeMute  = 0x01000071,
         Key_VolumeUp = 0x01000072,
         Key_BassBoost = 0x01000073,
         Key_BassUp = 0x01000074,
         Key_BassDown = 0x01000075,
         Key_TrebleUp = 0x01000076,
         Key_TrebleDown = 0x01000077,
         Key_MediaPlay  = 0x01000080,
         Key_MediaStop  = 0x01000081,
         Key_MediaPrevious  = 0x01000082,
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         Key_MediaPrev  = Key_MediaPrevious,
 #endif
         Key_MediaNext  = 0x01000083,
         Key_MediaRecord = 0x01000084,
         Key_MediaPause = 0x1000085,
         Key_MediaTogglePlayPause = 0x1000086,
         Key_HomePage  = 0x01000090,
         Key_Favorites  = 0x01000091,
         Key_Search  = 0x01000092,
         Key_Standby = 0x01000093,
         Key_OpenUrl = 0x01000094,
         Key_LaunchMail  = 0x010000a0,
         Key_LaunchMedia = 0x010000a1,
         Key_Launch0  = 0x010000a2,
         Key_Launch1  = 0x010000a3,
         Key_Launch2  = 0x010000a4,
         Key_Launch3  = 0x010000a5,
         Key_Launch4  = 0x010000a6,
         Key_Launch5  = 0x010000a7,
         Key_Launch6  = 0x010000a8,
         Key_Launch7  = 0x010000a9,
         Key_Launch8  = 0x010000aa,
         Key_Launch9  = 0x010000ab,
         Key_LaunchA  = 0x010000ac,
         Key_LaunchB  = 0x010000ad,
         Key_LaunchC  = 0x010000ae,
         Key_LaunchD  = 0x010000af,
         Key_LaunchE  = 0x010000b0,
         Key_LaunchF  = 0x010000b1,
         Key_MonBrightnessUp = 0x010000b2,
         Key_MonBrightnessDown = 0x010000b3,
         Key_KeyboardLightOnOff = 0x010000b4,
         Key_KeyboardBrightnessUp = 0x010000b5,
         Key_KeyboardBrightnessDown = 0x010000b6,
         Key_PowerOff = 0x010000b7,
         Key_WakeUp = 0x010000b8,
         Key_Eject = 0x010000b9,
         Key_ScreenSaver = 0x010000ba,
         Key_WWW = 0x010000bb,
         Key_Memo = 0x010000bc,
         Key_LightBulb = 0x010000bd,
         Key_Shop = 0x010000be,
         Key_History = 0x010000bf,
         Key_AddFavorite = 0x010000c0,
         Key_HotLinks = 0x010000c1,
         Key_BrightnessAdjust = 0x010000c2,
         Key_Finance = 0x010000c3,
         Key_Community = 0x010000c4,
         Key_AudioRewind = 0x010000c5,
         Key_BackForward = 0x010000c6,
         Key_ApplicationLeft = 0x010000c7,
         Key_ApplicationRight = 0x010000c8,
         Key_Book = 0x010000c9,
         Key_CD = 0x010000ca,
         Key_Calculator = 0x010000cb,
         Key_ToDoList = 0x010000cc,
         Key_ClearGrab = 0x010000cd,
         Key_Close = 0x010000ce,
         Key_Copy = 0x010000cf,
         Key_Cut = 0x010000d0,
         Key_Display = 0x010000d1,
         Key_DOS = 0x010000d2,
         Key_Documents = 0x010000d3,
         Key_Excel = 0x010000d4,
         Key_Explorer = 0x010000d5,
         Key_Game = 0x010000d6,
         Key_Go = 0x010000d7,
         Key_iTouch = 0x010000d8,
         Key_LogOff = 0x010000d9,
         Key_Market = 0x010000da,
         Key_Meeting = 0x010000db,
         Key_MenuKB = 0x010000dc,
         Key_MenuPB = 0x010000dd,
         Key_MySites = 0x010000de,
         Key_News = 0x010000df,
         Key_OfficeHome = 0x010000e0,
         Key_Option = 0x010000e1,
         Key_Paste = 0x010000e2,
         Key_Phone = 0x010000e3,
         Key_Calendar = 0x010000e4,
         Key_Reply = 0x010000e5,
         Key_Reload = 0x010000e6,
         Key_RotateWindows = 0x010000e7,
         Key_RotationPB = 0x010000e8,
         Key_RotationKB = 0x010000e9,
         Key_Save = 0x010000ea,
         Key_Send = 0x010000eb,
         Key_Spell = 0x010000ec,
         Key_SplitScreen = 0x010000ed,
         Key_Support = 0x010000ee,
         Key_TaskPane = 0x010000ef,
         Key_Terminal = 0x010000f0,
         Key_Tools = 0x010000f1,
         Key_Travel = 0x010000f2,
         Key_Video = 0x010000f3,
         Key_Word = 0x010000f4,
         Key_Xfer = 0x010000f5,
         Key_ZoomIn = 0x010000f6,
         Key_ZoomOut = 0x010000f7,
         Key_Away = 0x010000f8,
         Key_Messenger = 0x010000f9,
         Key_WebCam = 0x010000fa,
         Key_MailForward = 0x010000fb,
         Key_Pictures = 0x010000fc,
         Key_Music = 0x010000fd,
         Key_Battery = 0x010000fe,
         Key_Bluetooth = 0x010000ff,
         Key_WLAN = 0x01000100,
         Key_UWB = 0x01000101,
         Key_AudioForward = 0x01000102,
         Key_AudioRepeat = 0x01000103,
         Key_AudioRandomPlay = 0x01000104,
         Key_Subtitle = 0x01000105,
         Key_AudioCycleTrack = 0x01000106,
         Key_Time = 0x01000107,
         Key_Hibernate = 0x01000108,
         Key_View = 0x01000109,
         Key_TopMenu = 0x0100010a,
         Key_PowerDown = 0x0100010b,
         Key_Suspend = 0x0100010c,
         Key_ContrastAdjust = 0x0100010d,
         Key_LaunchG  = 0x0100010e,
         Key_LaunchH  = 0x0100010f,
         Key_MediaLast = 0x0100ffff,
         // Keypad navigation keys
         Key_Select = 0x01010000,
         Key_Yes = 0x01010001,
         Key_No = 0x01010002,
         // Newer misc keys
         Key_Cancel  = 0x01020001,
         Key_Printer = 0x01020002,
         Key_Execute = 0x01020003,
         Key_Sleep   = 0x01020004,
         Key_Play    = 0x01020005, // Not the same as Key_MediaPlay
         Key_Zoom    = 0x01020006,
         //Key_Jisho   = 0x01020007, // IME: Dictionary key
         //Key_Oyayubi_Left = 0x01020008, // IME: Left Oyayubi key
         //Key_Oyayubi_Right = 0x01020009, // IME: Right Oyayubi key
         // Device keys
         Key_Context1 = 0x01100000,
         Key_Context2 = 0x01100001,
         Key_Context3 = 0x01100002,
         Key_Context4 = 0x01100003,
         Key_Call = 0x01100004,      // set absolute state to in a call (do not toggle state)
         Key_Hangup = 0x01100005,    // set absolute state to hang up (do not toggle state)
         Key_Flip = 0x01100006,
         Key_ToggleCallHangup = 0x01100007, // a toggle key for answering, or hanging up, based on current call state
         Key_VoiceDial = 0x01100008,
         Key_LastNumberRedial = 0x01100009,
         Key_Camera = 0x01100020,
         Key_CameraFocus = 0x01100021,
         Key_unknown = 0x01ffffff
     };
KeyboardModifier
enum Qt::KeyboardModifier
Enumerator
NoModifier
ShiftModifier
ControlModifier
AltModifier
MetaModifier
KeypadModifier
GroupSwitchModifier
KeyboardModifierMask
Definition at line 127 of file qnamespace.h.
{
         NoModifier           = 0x00000000,
         ShiftModifier        = 0x02000000,
         ControlModifier      = 0x04000000,
         AltModifier          = 0x08000000,
         MetaModifier         = 0x10000000,
         KeypadModifier       = 0x20000000,
         GroupSwitchModifier  = 0x40000000,
         // Do not extend the mask to include 0x01000000
         KeyboardModifierMask = 0xfe000000
     };
LayoutDirection
enum Qt::LayoutDirection
Enumerator
LeftToRight
RightToLeft
LayoutDirectionAuto
Definition at line 1580 of file qnamespace.h.
{
         LeftToRight,
         RightToLeft,
         LayoutDirectionAuto
     };
MaskMode
enum Qt::MaskMode
Enumerator
MaskInColor
MaskOutColor
Definition at line 1490 of file qnamespace.h.
                   {
         MaskInColor,
         MaskOutColor
     };
MatchFlag
enum Qt::MatchFlag
Enumerator
MatchExactly
MatchContains
MatchStartsWith
MatchEndsWith
MatchRegExp
MatchWildcard
MatchFixedString
MatchCaseSensitive
MatchWrap
MatchRecursive
Definition at line 1656 of file qnamespace.h.
                    {
         MatchExactly = 0,
         MatchContains = 1,
         MatchStartsWith = 2,
         MatchEndsWith = 3,
         MatchRegExp = 4,
         MatchWildcard = 5,
         MatchFixedString = 8,
         MatchCaseSensitive = 16,
         MatchWrap = 32,
         MatchRecursive = 64
     };
Modifier
enum Qt::Modifier
Enumerator
META
SHIFT
CTRL
ALT
MODIFIER_MASK
UNICODE_ACCEL
Definition at line 141 of file qnamespace.h.
                   {
         META          = Qt::MetaModifier,
         SHIFT         = Qt::ShiftModifier,
         CTRL          = Qt::ControlModifier,
         ALT           = Qt::AltModifier,
         MODIFIER_MASK = KeyboardModifierMask,
         UNICODE_ACCEL = 0x00000000
     };
MouseButton
enum Qt::MouseButton
Enumerator
NoButton
LeftButton
RightButton
MidButton
MiddleButton
XButton1
XButton2
MouseButtonMask
Definition at line 150 of file qnamespace.h.
                      {
         NoButton         = 0x00000000,
         LeftButton       = 0x00000001,
         RightButton      = 0x00000002,
         MidButton        = 0x00000004, // ### Qt 5: remove me
         MiddleButton     = MidButton,
         XButton1         = 0x00000008,
         XButton2         = 0x00000010,
         MouseButtonMask  = 0x000000ff
     };
NavigationMode
enum Qt::NavigationMode
Enumerator
NavigationModeNone
NavigationModeKeypadTabOrder
NavigationModeKeypadDirectional
NavigationModeCursorAuto
NavigationModeCursorForceVisible
Definition at line 1781 of file qnamespace.h.
     {
         NavigationModeNone,
         NavigationModeKeypadTabOrder,
         NavigationModeKeypadDirectional,
         NavigationModeCursorAuto,
         NavigationModeCursorForceVisible
     };
Orientation
enum Qt::Orientation
Enumerator
Horizontal
Vertical
Definition at line 174 of file qnamespace.h.
                      {
         Horizontal = 0x1,
         Vertical = 0x2
     };
PenCapStyle
enum Qt::PenCapStyle
Enumerator
FlatCap
SquareCap
RoundCap
MPenCapStyle
Definition at line 1147 of file qnamespace.h.
                      { // line endcap style
         FlatCap = 0x00,
         SquareCap = 0x10,
         RoundCap = 0x20,
         MPenCapStyle = 0x30
     };
PenJoinStyle
enum Qt::PenJoinStyle
Enumerator
MiterJoin
BevelJoin
RoundJoin
SvgMiterJoin
MPenJoinStyle
Definition at line 1154 of file qnamespace.h.
                       { // line join style
         MiterJoin = 0x00,
         BevelJoin = 0x40,
         RoundJoin = 0x80,
         SvgMiterJoin = 0x100,
         MPenJoinStyle = 0x1c0
     };
PenStyle
enum Qt::PenStyle
Enumerator
NoPen
SolidLine
DashLine
DotLine
DashDotLine
DashDotDotLine
CustomDashLine
MPenStyle
Definition at line 1134 of file qnamespace.h.
                   { // pen style
         NoPen,
         SolidLine,
         DashLine,
         DotLine,
         DashDotLine,
         DashDotDotLine,
         CustomDashLine
 #ifndef Q_MOC_RUN
         , MPenStyle = 0x0f
 #endif
     };
ScrollBarPolicy
enum Qt::ScrollBarPolicy
Enumerator
ScrollBarAsNeeded
ScrollBarAlwaysOff
ScrollBarAlwaysOn
Definition at line 1420 of file qnamespace.h.
{
         ScrollBarAsNeeded,
         ScrollBarAlwaysOff,
         ScrollBarAlwaysOn
     };
ShortcutContext
enum Qt::ShortcutContext
Enumerator
WidgetShortcut
WindowShortcut
ApplicationShortcut
WidgetWithChildrenShortcut
Definition at line 1478 of file qnamespace.h.
{
         WidgetShortcut,
         WindowShortcut,
         ApplicationShortcut,
         WidgetWithChildrenShortcut
     };
SizeHint
enum Qt::SizeHint
Enumerator
MinimumSize
PreferredSize
MaximumSize
MinimumDescent
NSizeHints
Definition at line 1708 of file qnamespace.h.
                   {
         MinimumSize,
         PreferredSize,
         MaximumSize,
         MinimumDescent,
         NSizeHints
     };
SizeMode
enum Qt::SizeMode
Enumerator
AbsoluteSize
RelativeSize
Definition at line 1187 of file qnamespace.h.
                   {
         AbsoluteSize,
         RelativeSize
     };
SortOrder
enum Qt::SortOrder
Enumerator
AscendingOrder
DescendingOrder
Definition at line 189 of file qnamespace.h.
                    {
         AscendingOrder,
         DescendingOrder
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         ,Ascending = AscendingOrder,
         Descending = DescendingOrder
 #endif
     };
TextElideMode
enum Qt::TextElideMode
Enumerator
ElideLeft
ElideRight
ElideMiddle
ElideNone
Definition at line 263 of file qnamespace.h.
{
         ElideLeft,
         ElideRight,
         ElideMiddle,
         ElideNone
     };
TextFlag
enum Qt::TextFlag
Enumerator
TextSingleLine
TextDontClip
TextExpandTabs
TextShowMnemonic
TextWordWrap
TextWrapAnywhere
TextDontPrint
TextIncludeTrailingSpaces
TextHideMnemonic
TextJustificationForced
TextForceLeftToRight
TextForceRightToLeft
TextLongestVariant
TextBypassShaping
Definition at line 231 of file qnamespace.h.
                   {
         TextSingleLine = 0x0100,
         TextDontClip = 0x0200,
         TextExpandTabs = 0x0400,
         TextShowMnemonic = 0x0800,
         TextWordWrap = 0x1000,
         TextWrapAnywhere = 0x2000,
         TextDontPrint = 0x4000,
         TextIncludeTrailingSpaces = 0x08000000,
         TextHideMnemonic = 0x8000,
         TextJustificationForced = 0x10000,
         TextForceLeftToRight = 0x20000,
         TextForceRightToLeft = 0x40000,
         TextLongestVariant = 0x80000,
         TextBypassShaping = 0x100000
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         ,SingleLine = TextSingleLine,
         DontClip = TextDontClip,
         ExpandTabs = TextExpandTabs,
         ShowPrefix = TextShowMnemonic,
         WordBreak = TextWordWrap,
         BreakAnywhere = TextWrapAnywhere,
         DontPrint = TextDontPrint,
         IncludeTrailingSpaces = TextIncludeTrailingSpaces,
         NoAccel = TextHideMnemonic
 #endif
     };
TextFormat
enum Qt::TextFormat
Enumerator
PlainText
RichText
AutoText
LogText
Definition at line 1310 of file qnamespace.h.
                     {
         PlainText,
         RichText,
         AutoText,
         LogText
     };
TextInteractionFlag
enum Qt::TextInteractionFlag
Enumerator
NoTextInteraction
TextSelectableByMouse
TextSelectableByKeyboard
LinksAccessibleByMouse
LinksAccessibleByKeyboard
TextEditable
TextEditorInteraction
TextBrowserInteraction
Definition at line 1689 of file qnamespace.h.
{
         NoTextInteraction         = 0,
         TextSelectableByMouse     = 1,
         TextSelectableByKeyboard  = 2,
         LinksAccessibleByMouse    = 4,
         LinksAccessibleByKeyboard = 8,
         TextEditable              = 16,
         TextEditorInteraction     = TextSelectableByMouse | TextSelectableByKeyboard | TextEditable,
         TextBrowserInteraction    = TextSelectableByMouse | LinksAccessibleByMouse | LinksAccessibleByKeyboard
     };
TileRule
enum Qt::TileRule
Enumerator
StretchTile
RepeatTile
RoundTile
Definition at line 198 of file qnamespace.h.
                   {
         StretchTile,
         RepeatTile,
         RoundTile
     };
TimeSpec
enum Qt::TimeSpec
Enumerator
LocalTime
UTC
OffsetFromUTC
Definition at line 1404 of file qnamespace.h.
                   {
         LocalTime,
         UTC,
         OffsetFromUTC
     };
ToolBarArea
enum Qt::ToolBarArea
Enumerator
LeftToolBarArea
RightToolBarArea
TopToolBarArea
BottomToolBarArea
ToolBarArea_Mask
AllToolBarAreas
NoToolBarArea
Definition at line 1353 of file qnamespace.h.
                      {
         LeftToolBarArea = 0x1,
         RightToolBarArea = 0x2,
         TopToolBarArea = 0x4,
         BottomToolBarArea = 0x8,
         ToolBarArea_Mask = 0xf,
         AllToolBarAreas = ToolBarArea_Mask,
         NoToolBarArea = 0
     };
ToolBarAreaSizes
enum Qt::ToolBarAreaSizes
Enumerator
NToolBarAreas
Definition at line 1364 of file qnamespace.h.
{
         NToolBarAreas = 4
     };
ToolButtonStyle
enum Qt::ToolButtonStyle
Enumerator
ToolButtonIconOnly
ToolButtonTextOnly
ToolButtonTextBesideIcon
ToolButtonTextUnderIcon
ToolButtonFollowStyle
Definition at line 1572 of file qnamespace.h.
{
         ToolButtonIconOnly,
         ToolButtonTextOnly,
         ToolButtonTextBesideIcon,
         ToolButtonTextUnderIcon,
         ToolButtonFollowStyle
     };
TouchPointState
enum Qt::TouchPointState
This enum represents the state of a touch point at the time the QTouchEvent occurred.
Since
4.6
TouchPointPressed The touch point is now pressed.
TouchPointMoved The touch point moved.
TouchPointStationary The touch point did not move.
TouchPointReleased The touch point was released.
TouchPointStateMask
TouchPointPrimary
Enumerator
TouchPointPressed
TouchPointMoved
TouchPointStationary
TouchPointReleased
TouchPointStateMask
TouchPointPrimary
Definition at line 1738 of file qnamespace.h.
{
         TouchPointPressed    = 0x01,
         TouchPointMoved      = 0x02,
         TouchPointStationary = 0x04,
         TouchPointReleased   = 0x08,
         TouchPointStateMask  = 0x0f,
         TouchPointPrimary    = 0x10
     };
TransformationMode
enum Qt::TransformationMode
Enumerator
FastTransformation
SmoothTransformation
Definition at line 1510 of file qnamespace.h.
{
         FastTransformation,
         SmoothTransformation
     };
UIEffect
enum Qt::UIEffect
Enumerator
UI_General
UI_AnimateMenu
UI_FadeMenu
UI_AnimateCombo
UI_AnimateTooltip
UI_FadeTooltip
UI_AnimateToolBox
Definition at line 1252 of file qnamespace.h.
                   {
         UI_General,
         UI_AnimateMenu,
         UI_FadeMenu,
         UI_AnimateCombo,
         UI_AnimateTooltip,
         UI_FadeTooltip,
         UI_AnimateToolBox
     };
WhiteSpaceMode
enum Qt::WhiteSpaceMode
Enumerator
WhiteSpaceNormal
WhiteSpacePre
WhiteSpaceNoWrap
WhiteSpaceModeUndefined
Definition at line 79 of file qtextdocument.h.
{
         WhiteSpaceNormal,
         WhiteSpacePre,
         WhiteSpaceNoWrap,
         WhiteSpaceModeUndefined = -1
     };
WidgetAttribute
enum Qt::WidgetAttribute
Enumerator
WA_Disabled
WA_UnderMouse
WA_MouseTracking
WA_ContentsPropagated
WA_OpaquePaintEvent
WA_NoBackground
WA_StaticContents
WA_LaidOut
WA_PaintOnScreen
WA_NoSystemBackground
WA_UpdatesDisabled
WA_Mapped
WA_MacNoClickThrough
WA_PaintOutsidePaintEvent
WA_InputMethodEnabled
WA_WState_Visible
WA_WState_Hidden
WA_ForceDisabled
WA_KeyCompression
WA_PendingMoveEvent
WA_PendingResizeEvent
WA_SetPalette
WA_SetFont
WA_SetCursor
WA_NoChildEventsFromChildren
WA_WindowModified
WA_Resized
WA_Moved
WA_PendingUpdate
WA_InvalidSize
WA_MacBrushedMetal
WA_MacMetalStyle
WA_CustomWhatsThis
WA_LayoutOnEntireRect
WA_OutsideWSRange
WA_GrabbedShortcut
WA_TransparentForMouseEvents
WA_PaintUnclipped
WA_SetWindowIcon
WA_NoMouseReplay
WA_DeleteOnClose
WA_RightToLeft
WA_SetLayoutDirection
WA_NoChildEventsForParent
WA_ForceUpdatesDisabled
WA_WState_Created
WA_WState_CompressKeys
WA_WState_InPaintEvent
WA_WState_Reparented
WA_WState_ConfigPending
WA_WState_Polished
WA_WState_DND
WA_WState_OwnSizePolicy
WA_WState_ExplicitShowHide
WA_ShowModal
WA_MouseNoMask
WA_GroupLeader
WA_NoMousePropagation
WA_Hover
WA_InputMethodTransparent
WA_QuitOnClose
WA_KeyboardFocusChange
WA_AcceptDrops
WA_DropSiteRegistered
WA_ForceAcceptDrops
WA_WindowPropagation
WA_NoX11EventCompression
WA_TintedBackground
WA_X11OpenGLOverlay
WA_AlwaysShowToolTips
WA_MacOpaqueSizeGrip
WA_SetStyle
WA_SetLocale
WA_MacShowFocusRect
WA_MacNormalSize
WA_MacSmallSize
WA_MacMiniSize
WA_LayoutUsesWidgetRect
WA_StyledBackground
WA_MSWindowsUseDirect3D
WA_CanHostQMdiSubWindowTitleBar
WA_MacAlwaysShowToolWindow
WA_StyleSheet
WA_ShowWithoutActivating
WA_X11BypassTransientForHint
WA_NativeWindow
WA_DontCreateNativeAncestors
WA_MacVariableSize
WA_DontShowOnScreen
WA_X11NetWmWindowTypeDesktop
WA_X11NetWmWindowTypeDock
WA_X11NetWmWindowTypeToolBar
WA_X11NetWmWindowTypeMenu
WA_X11NetWmWindowTypeUtility
WA_X11NetWmWindowTypeSplash
WA_X11NetWmWindowTypeDialog
WA_X11NetWmWindowTypeDropDownMenu
WA_X11NetWmWindowTypePopupMenu
WA_X11NetWmWindowTypeToolTip
WA_X11NetWmWindowTypeNotification
WA_X11NetWmWindowTypeCombo
WA_X11NetWmWindowTypeDND
WA_MacFrameworkScaled
WA_SetWindowModality
WA_WState_WindowOpacitySet
WA_TranslucentBackground
WA_AcceptTouchEvents
WA_WState_AcceptedTouchBeginEvent
WA_TouchPadAcceptSingleTouchEvents
WA_MergeSoftkeys
WA_MergeSoftkeysRecursively
WA_LockPortraitOrientation
WA_LockLandscapeOrientation
WA_AutoOrientation
WA_X11DoNotAcceptFocus
WA_SymbianNoSystemRotation
WA_MacNoShadow
WA_AttributeCount
Definition at line 376 of file qnamespace.h.
{
         WA_Disabled = 0,
         WA_UnderMouse = 1,
         WA_MouseTracking = 2,
         WA_ContentsPropagated = 3, // ## deprecated
         WA_OpaquePaintEvent = 4,
         WA_NoBackground = WA_OpaquePaintEvent, // ## deprecated
         WA_StaticContents = 5,
         WA_LaidOut = 7,
         WA_PaintOnScreen = 8,
         WA_NoSystemBackground = 9,
         WA_UpdatesDisabled = 10,
         WA_Mapped = 11,
         WA_MacNoClickThrough = 12, // Mac only
         WA_PaintOutsidePaintEvent = 13,
         WA_InputMethodEnabled = 14,
         WA_WState_Visible = 15,
         WA_WState_Hidden = 16,
         WA_ForceDisabled = 32,
         WA_KeyCompression = 33,
         WA_PendingMoveEvent = 34,
         WA_PendingResizeEvent = 35,
         WA_SetPalette = 36,
         WA_SetFont = 37,
         WA_SetCursor = 38,
         WA_NoChildEventsFromChildren = 39,
         WA_WindowModified = 41,
         WA_Resized = 42,
         WA_Moved = 43,
         WA_PendingUpdate = 44,
         WA_InvalidSize = 45,
         WA_MacBrushedMetal = 46, // Mac only
         WA_MacMetalStyle = WA_MacBrushedMetal, // obsolete
         WA_CustomWhatsThis = 47,
         WA_LayoutOnEntireRect = 48,
         WA_OutsideWSRange = 49,
         WA_GrabbedShortcut = 50,
         WA_TransparentForMouseEvents = 51,
         WA_PaintUnclipped = 52,
         WA_SetWindowIcon = 53,
         WA_NoMouseReplay = 54,
         WA_DeleteOnClose = 55,
         WA_RightToLeft = 56,
         WA_SetLayoutDirection = 57,
         WA_NoChildEventsForParent = 58,
         WA_ForceUpdatesDisabled = 59,
         WA_WState_Created = 60,
         WA_WState_CompressKeys = 61,
         WA_WState_InPaintEvent = 62,
         WA_WState_Reparented = 63,
         WA_WState_ConfigPending = 64,
         WA_WState_Polished = 66,
         WA_WState_DND = 67, // ## deprecated
         WA_WState_OwnSizePolicy = 68,
         WA_WState_ExplicitShowHide = 69,
         WA_ShowModal = 70, // ## deprecated
         WA_MouseNoMask = 71,
         WA_GroupLeader = 72, // ## deprecated
         WA_NoMousePropagation = 73, // ## for now, might go away.
         WA_Hover = 74,
         WA_InputMethodTransparent = 75, // Don't reset IM when user clicks on this (for virtual keyboards on embedded)
         WA_QuitOnClose = 76,
         WA_KeyboardFocusChange = 77,
         WA_AcceptDrops = 78,
         WA_DropSiteRegistered = 79, // internal
         WA_ForceAcceptDrops = WA_DropSiteRegistered, // ## deprecated
         WA_WindowPropagation = 80,
         WA_NoX11EventCompression = 81,
         WA_TintedBackground = 82,
         WA_X11OpenGLOverlay = 83,
         WA_AlwaysShowToolTips = 84,
         WA_MacOpaqueSizeGrip = 85,
         WA_SetStyle = 86,
         WA_SetLocale = 87,
         WA_MacShowFocusRect = 88,
         WA_MacNormalSize = 89,  // Mac only
         WA_MacSmallSize = 90,   // Mac only
         WA_MacMiniSize = 91,    // Mac only
         WA_LayoutUsesWidgetRect = 92,
         WA_StyledBackground = 93, // internal
         WA_MSWindowsUseDirect3D = 94, // Win only
         WA_CanHostQMdiSubWindowTitleBar = 95, // Internal
         WA_MacAlwaysShowToolWindow = 96, // Mac only
         WA_StyleSheet = 97, // internal
         WA_ShowWithoutActivating = 98,
         WA_X11BypassTransientForHint = 99,
         WA_NativeWindow = 100,
         WA_DontCreateNativeAncestors = 101,
         WA_MacVariableSize = 102,    // Mac only
         WA_DontShowOnScreen = 103,
         // window types from http://standards.freedesktop.org/wm-spec/
         WA_X11NetWmWindowTypeDesktop = 104,
         WA_X11NetWmWindowTypeDock = 105,
         WA_X11NetWmWindowTypeToolBar = 106,
         WA_X11NetWmWindowTypeMenu = 107,
         WA_X11NetWmWindowTypeUtility = 108,
         WA_X11NetWmWindowTypeSplash = 109,
         WA_X11NetWmWindowTypeDialog = 110,
         WA_X11NetWmWindowTypeDropDownMenu = 111,
         WA_X11NetWmWindowTypePopupMenu = 112,
         WA_X11NetWmWindowTypeToolTip = 113,
         WA_X11NetWmWindowTypeNotification = 114,
         WA_X11NetWmWindowTypeCombo = 115,
         WA_X11NetWmWindowTypeDND = 116,
         WA_MacFrameworkScaled  = 117,
         WA_SetWindowModality = 118,
         WA_WState_WindowOpacitySet = 119, // internal
         WA_TranslucentBackground = 120,
         WA_AcceptTouchEvents = 121,
         WA_WState_AcceptedTouchBeginEvent = 122,
         WA_TouchPadAcceptSingleTouchEvents = 123,
         WA_MergeSoftkeys =  124,
         WA_MergeSoftkeysRecursively =  125,
 #if 0 // these values are reserved for Maemo5 - do not re-use them
         WA_Maemo5NonComposited = 126,
         WA_Maemo5StackedWindow = 127,
 #endif
         WA_LockPortraitOrientation = 128,
         WA_LockLandscapeOrientation = 129,
         WA_AutoOrientation = 130,
 #if 0 // these values are reserved for Maemo5 - do not re-use them
         WA_Maemo5PortraitOrientation = WA_LockPortraitOrientation,
         WA_Maemo5LandscapeOrientation = WA_LockLandscapeOrientation,
         WA_Maemo5AutoOrientation = WA_AutoOrientation,
         WA_Maemo5ShowProgressIndicator = 131,
 #endif
         WA_X11DoNotAcceptFocus = 132,
         WA_SymbianNoSystemRotation = 133,
         WA_MacNoShadow = 134,
         // Add new attributes before this line
         WA_AttributeCount
     };
WindowFrameSection
enum Qt::WindowFrameSection
Enumerator
NoSection
LeftSection
TopLeftSection
TopSection
TopRightSection
RightSection
BottomRightSection
BottomSection
BottomLeftSection
TitleBarArea
Definition at line 1716 of file qnamespace.h.
{
         NoSection,
         LeftSection,           // For resize
         TopLeftSection,
         TopSection,
         TopRightSection,
         RightSection,
         BottomRightSection,
         BottomSection,
         BottomLeftSection,
         TitleBarArea    // For move
     };
WindowModality
enum Qt::WindowModality
Enumerator
NonModal
WindowModal
ApplicationModal
Definition at line 1683 of file qnamespace.h.
{
         NonModal,
         WindowModal,
         ApplicationModal
     };
WindowState
enum Qt::WindowState
Enumerator
WindowNoState
WindowMinimized
WindowMaximized
WindowFullScreen
WindowActive
Definition at line 366 of file qnamespace.h.
                      {
         WindowNoState    = 0x00000000,
         WindowMinimized  = 0x00000001,
         WindowMaximized  = 0x00000002,
         WindowFullScreen = 0x00000004,
         WindowActive     = 0x00000008
     };
WindowType
enum Qt::WindowType
Enumerator
Widget
Window
Dialog
Sheet
Drawer
Popup
Tool
ToolTip
SplashScreen
Desktop
SubWindow
WindowType_Mask
MSWindowsFixedSizeDialogHint
MSWindowsOwnDC
X11BypassWindowManagerHint
FramelessWindowHint
WindowTitleHint
WindowSystemMenuHint
WindowMinimizeButtonHint
WindowMaximizeButtonHint
WindowMinMaxButtonsHint
WindowContextHelpButtonHint
WindowShadeButtonHint
WindowStaysOnTopHint
CustomizeWindowHint
WindowStaysOnBottomHint
WindowCloseButtonHint
MacWindowToolBarButtonHint
BypassGraphicsProxyWidget
WindowOkButtonHint
WindowCancelButtonHint
WindowSoftkeysVisibleHint
WindowSoftkeysRespondHint
Definition at line 270 of file qnamespace.h.
                     {
         Widget = 0x00000000,
         Window = 0x00000001,
         Dialog = 0x00000002 | Window,
         Sheet = 0x00000004 | Window,
         Drawer = 0x00000006 | Window,
         Popup = 0x00000008 | Window,
         Tool = 0x0000000a | Window,
         ToolTip = 0x0000000c | Window,
         SplashScreen = 0x0000000e | Window,
         Desktop = 0x00000010 | Window,
         SubWindow =  0x00000012,
         WindowType_Mask = 0x000000ff,
         MSWindowsFixedSizeDialogHint = 0x00000100,
         MSWindowsOwnDC = 0x00000200,
         X11BypassWindowManagerHint = 0x00000400,
         FramelessWindowHint = 0x00000800,
         WindowTitleHint = 0x00001000,
         WindowSystemMenuHint = 0x00002000,
         WindowMinimizeButtonHint = 0x00004000,
         WindowMaximizeButtonHint = 0x00008000,
         WindowMinMaxButtonsHint = WindowMinimizeButtonHint | WindowMaximizeButtonHint,
         WindowContextHelpButtonHint = 0x00010000,
         WindowShadeButtonHint = 0x00020000,
         WindowStaysOnTopHint = 0x00040000,
         // reserved for Qt3Support:
         // WMouseNoMask = 0x00080000,
         // WDestructiveClose = 0x00100000,
         // WStaticContents = 0x00200000,
         // WGroupLeader = 0x00400000,
         // WShowModal = 0x00800000,
         // WNoMousePropagation = 0x01000000,
         CustomizeWindowHint = 0x02000000,
         WindowStaysOnBottomHint = 0x04000000,
         WindowCloseButtonHint = 0x08000000,
         MacWindowToolBarButtonHint = 0x10000000,
         BypassGraphicsProxyWidget = 0x20000000,
         WindowOkButtonHint = 0x00080000,
         WindowCancelButtonHint = 0x00100000,
         WindowSoftkeysVisibleHint = 0x40000000,
         WindowSoftkeysRespondHint = 0x80000000
 #ifdef QT3_SUPPORT
         ,
         WMouseNoMask = 0x00080000,
         WDestructiveClose = 0x00100000,
         WStaticContents = 0x00200000,
         WGroupLeader = 0x00400000,
         WShowModal = 0x00800000,
         WNoMousePropagation = 0x01000000,
         WType_TopLevel = Window,
         WType_Dialog = Dialog,
         WType_Popup = Popup,
         WType_Desktop = Desktop,
         WType_Mask = WindowType_Mask,
         WStyle_Customize = 0,
         WStyle_NormalBorder = 0,
         WStyle_DialogBorder = MSWindowsFixedSizeDialogHint,
         WStyle_NoBorder = FramelessWindowHint,
         WStyle_Title = WindowTitleHint,
         WStyle_SysMenu = WindowSystemMenuHint,
         WStyle_Minimize = WindowMinimizeButtonHint,
         WStyle_Maximize = WindowMaximizeButtonHint,
         WStyle_MinMax = WStyle_Minimize | WStyle_Maximize,
         WStyle_Tool = Tool,
         WStyle_StaysOnTop = WindowStaysOnTopHint,
         WStyle_ContextHelp = WindowContextHelpButtonHint,
         // misc flags
         WPaintDesktop = 0,
         WPaintClever = 0,
         WX11BypassWM            = X11BypassWindowManagerHint,
         WWinOwnDC               = MSWindowsOwnDC,
         WMacSheet               = Sheet,
         WMacDrawer              = Drawer,
         WStyle_Splash           = SplashScreen,
         WNoAutoErase           = 0,
         WRepaintNoErase        = 0,
         WNorthWestGravity      = WStaticContents,
         WType_Modal            = Dialog | WShowModal,
         WStyle_Dialog          = Dialog,
         WStyle_NoBorderEx      = FramelessWindowHint,
         WResizeNoErase = 0,
         WMacNoSheet = 0
 #endif
     };
Function Documentation
codecForHtml()
QTextCodec * Qt::codecForHtml (const QByteArray & ba)
This function is defined in the <QTextDocument> header file.
Warning
This function is not part of the public interface.
Definition at line 250 of file qtextdocument.cpp.
Referenced by QTextCodec::codecForHtml(), QTextCodec::codecForName(), and QTextBrowserPrivate::setSource().
 {
     return QTextCodec::codecForHtml(ba);
 }
convertFromPlainText()
QString Qt::convertFromPlainText (const QString & plain, Qt::WhiteSpaceMode mode = WhiteSpacePre)
Converts the plain text string plain to an HTML-formatted paragraph while preserving most of its look.
mode defines how whitespace is handled.
This function is defined in the <QTextDocument> header file.
See also
escape(), mightBeRichText()
Definition at line 193 of file qtextdocument.cpp.
Referenced by jump().
 {
     int col = 0;
     QString rich;
     rich += QLatin1String("<p>");
     for (int i = 0; i < plain.length(); ++i) {
         if (plain[i] == QLatin1Char('\n')){
             int c = 1;
             while (i+1 < plain.length() && plain[i+1] == QLatin1Char('\n')) {
                 i++;
                 c++;
             }
             if (c == 1)
                 rich += QLatin1String("<br>\n");
             else {
                 rich += QLatin1String("</p>\n");
                 while (--c > 1)
                     rich += QLatin1String("<br>\n");
                 rich += QLatin1String("<p>");
             }
             col = 0;
         } else {
             if (mode == Qt::WhiteSpacePre && plain[i] == QLatin1Char('\t')){
                 rich += QChar(0x00a0U);
                 ++col;
                 while (col % 8) {
                     rich += QChar(0x00a0U);
                     ++col;
                 }
             }
             else if (mode == Qt::WhiteSpacePre && plain[i].isSpace())
                 rich += QChar(0x00a0U);
             else if (plain[i] == QLatin1Char('<'))
                 rich += QLatin1String("&lt;");
             else if (plain[i] == QLatin1Char('>'))
                 rich += QLatin1String("&gt;");
             else if (plain[i] == QLatin1Char('&'))
                 rich += QLatin1String("&amp;");
             else
                 rich += plain[i];
             ++col;
         }
     }
     if (col != 0)
         rich += QLatin1String("</p>");
     return rich;
 }
escape()
QString Qt::escape (const QString & input)
Converts the plain text string plain to a HTML string with HTML metacharacters <, >, &, and " replaced by HTML entities.
Example:
QString plain = "#include <QtCore>"
QString html = Qt::escape(plain);
// html == "#include &lt;QtCore&gt;"
This function is defined in the <QTextDocument> header file.
See also
convertFromPlainText(), mightBeRichText()
Converts the plain text string plain to a HTML string with HTML metacharacters <, >, &, and " replaced by HTML entities.
Since Qt::escape() is in QtGui, using it creates a dependency on that library. This function does not.
The implementation resides in qpatternistlocale.cpp.
See also
Qt::escape()
Definition at line 159 of file qtextdocument.cpp.
Referenced by QPatternist::XSLTTokenizer::checkForParseError(), QSvgPaintEngine::drawTextItem(), QTextHtmlExporter::emitAttribute(), QTextHtmlExporter::emitFontFamily(), QTextHtmlExporter::emitFragment(), findArgEscapes(), QPatternist::formatData(), QPatternist::formatExpression(), QPatternist::formatFunction(), QPatternist::formatKeyword(), QXmlName::formatKeyword(), QPatternist::formatResourcePath(), QPatternist::formatType(), QPatternist::formatURI(), getEscape(), QPatternist::AccelTreeResourceLoader::load(), QScriptErrorLogWidget::message(), QRegExp::operator!=(), QLineControl::parseInputMask(), replaceArgEscapes(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), QPatternist::XSLTTokenizer::unexpectedContent(), and QPatternist::XPatherror().
 {
     QString rich;
     rich.reserve(int(plain.length() * qreal(1.1)));
     for (int i = 0; i < plain.length(); ++i) {
         if (plain.at(i) == QLatin1Char('<'))
             rich += QLatin1String("&lt;");
         else if (plain.at(i) == QLatin1Char('>'))
             rich += QLatin1String("&gt;");
         else if (plain.at(i) == QLatin1Char('&'))
             rich += QLatin1String("&amp;");
         else if (plain.at(i) == QLatin1Char('"'))
             rich += QLatin1String("&quot;");
         else
             rich += plain.at(i);
     }
     return rich;
 }
mightBeRichText()
bool Qt::mightBeRichText (const QString & text)
Returns true if the string text is likely to be rich text; otherwise returns false.
This function uses a fast and therefore simple heuristic. It mainly checks whether there is something that looks like a tag before the first line break. Although the result may be correct for common cases, there is no guarantee.
This function is defined in the <QTextDocument> header file.
Definition at line 88 of file qtextdocument.cpp.
Referenced by QTextControlPrivate::append(), QSplashScreen::drawContents(), QStaticTextPrivate::paintText(), QWhatsThat::QWhatsThat(), QTipLabel::reuseTip(), QDeclarativeText::setText(), QLabel::setText(), QDeclarativeTextEdit::setText(), QMessageBox::setText(), QTextEdit::setText(), QDeclarativeTextEdit::setTextFormat(), QDeclarativeText::setTextFormat(), QMessageBox::setTextFormat(), and QAccessibleDisplay::text().
 {
     if (text.isEmpty())
         return false;
     int start = 0;
     while (start < text.length() && text.at(start).isSpace())
         ++start;
     // skip a leading <?xml ... ?> as for example with xhtml
     if (text.mid(start, 5) == QLatin1String("<?xml")) {
         while (start < text.length()) {
             if (text.at(start) == QLatin1Char('?')
                 && start + 2 < text.length()
                 && text.at(start + 1) == QLatin1Char('>')) {
                 start += 2;
                 break;
             }
             ++start;
         }
         while (start < text.length() && text.at(start).isSpace())
             ++start;
     }
     if (text.mid(start, 5).toLower() == QLatin1String("<!doc"))
         return true;
     int open = start;
     while (open < text.length() && text.at(open) != QLatin1Char('<')
             && text.at(open) != QLatin1Char('\n')) {
         if (text.at(open) == QLatin1Char('&') &&  text.mid(open+1,3) == QLatin1String("lt;"))
             return true; // support desperate attempt of user to see <...>
         ++open;
     }
     if (open < text.length() && text.at(open) == QLatin1Char('<')) {
         const int close = text.indexOf(QLatin1Char('>'), open);
         if (close > -1) {
             QString tag;
             for (int i = open+1; i < close; ++i) {
                 if (text[i].isDigit() || text[i].isLetter())
                     tag += text[i];
                 else if (!tag.isEmpty() && text[i].isSpace())
                     break;
                 else if (!tag.isEmpty() && text[i] == QLatin1Char('/') && i + 1 == close)
                     break;
                 else if (!text[i].isSpace() && (!tag.isEmpty() || text[i] != QLatin1Char('!')))
                     return false; // that's not a tag
             }
 #ifndef QT_NO_TEXTHTMLPARSER
             return QTextHtmlParser::lookupElement(tag.toLower()) != -1;
 #else
             return false;
 #endif // QT_NO_TEXTHTMLPARSER
         }
     }
     return false;
 }