Qt 4.8: QPatternist Namespace Reference
QPatternist Namespace Reference
The namespace for the internal API of QtXmlPatterns.
Namespaces
CommonNamespaces
Contains common, standardized XML namespaces.
OptimizationPasses
Contains a set of common OptimizerPass instances.
Classes
class AbsFN
Implements the function fn:abs().
class AbstractDateTime
Base class for classes implementing values related to time, date or both.
class AbstractDateTimeComparator
Compares sub-classes of AbstractDateTime.
class AbstractDateTimeMathematician
Performs arithmetics between two AbstractDateTime values.
class AbstractDateTimeToDateCaster
Casts an AbstractDateTime instance to SchemaTime.
class AbstractDateTimeToDateTimeCaster
Casts an AbstractDateTime instance to DateTime.
class AbstractDateTimeToGDayCaster
Casts a xs:date or xs:dateTime atomic value to xs:gDay.
class AbstractDateTimeToGMonthCaster
Casts a xs:date or xs:dateTime atomic value to xs:gMonth.
class AbstractDateTimeToGMonthDayCaster
Casts a xs:date or xs:dateTime atomic value to xs:gMonthDay.
class AbstractDateTimeToGYearCaster
Casts a xs:date or xs:dateTime atomic value to xs:gYear.
class AbstractDateTimeToGYearMonthCaster
Casts a xs:date or xs:dateTime atomic value to xs:gYearMonth.
class AbstractDateTimeToTimeCaster
Casts an AbstractDateTime instance to SchemaTime.
class AbstractDuration
Base class for classes implementing durations.
class AbstractDurationComparator
Compares sub-classes of AbstractDuration.
class AbstractDurationToDayTimeDurationCaster
Casts an AbstractDuration instance to DayTimeDuration.
class AbstractDurationToDurationCaster
Casts an AbstractDuration instance to Duration.
class AbstractDurationToYearMonthDurationCaster
Casts an AbstractDuration instance to YearMonthDuration.
class AbstractFloat
Base template class for Float and Double classes.
class AbstractFloatComparator
Compares xs:double values.
class AbstractFloatMathematician
Performs arithmetics between AbstractFloat values (Float and Double classes).
class AbstractFloatSortComparator
Compares xs:double values for the purpose of sorting.
class AbstractFunctionFactory
Supplies convenience code for the function factories.
class AbstractNodeTest
A name test that is of the type prefix:ncName.
class AbstractXmlPullProvider
class AccelIterator
Abstract base class for Iterators for the AccelTree, that contains common functions and members.
class AccelTree
Stores an XML document using the XPath Accelerator scheme, also known as pre/post numbering.
class AccelTreeBuilder
Builds an AccelTree from a stream of XML/Item events received through the NodeBuilder interface.
class AccelTreePrivate
class AccelTreeResourceLoader
Handles requests for documents, and instantiates them as AccelTree instances.
class AddingAggregate
Base class for the implementations of the fn:avg() and fn:sum() function.
class AdjustDateTimeToTimezoneFN
Implements the function fn:adjust-dateTime-to-timezone().
class AdjustDateToTimezoneFN
Implements the function fn:adjust-dateTime-to-timezone().
class AdjustTimeToTimezoneFN
Implements the function fn:adjust-time-to-timezone().
class AdjustTimezone
Base class for classes implementing functions changing the timezone on values.
class Aggregator
Carries a staticType() implementation appropriate for functions which returns a singleton value derived from its first argument.
class AncestorIterator
Iterates along the ancestor or ancestor-or-self axis in an AccelTree.
class AndExpression
Implements XPath 2.0's logical expression and.
class AnyAtomicType
Implements the type xs:anyAtomicType.
class AnyItemType
Represents the item() item type.
class AnyNodeType
Represents the node() item type.
class AnySimpleType
Represents the xs:anySimpleType item type.
class AnyToDerivedStringCaster
Casts an xs:boolean instance to a derived type of xs:integer.
class AnyType
Represents the xs:anyType item type.
class AnyURI
A value of type xs:anyURI.
class AnyURIType
Implements the type xs:anyURI.
class ApplyTemplate
When combined with other components, implements xsl:apply-templates.
class ArgumentConverter
UntypedAtomicConverter for ArgumentReference, if needed.
class ArgumentReference
A reference to an argument declared in a UserFunction.
class ArithmeticExpression
Implements arithmetics, such as multiplication and subtraction.
class AtomicCaster
AtomicCaster is an abstract base class for classes that performs casting between two atomic values of specific types.
class AtomicCasterLocator
class AtomicComparator
Base class for classes responsible of comparing two atomic values.
class AtomicComparatorLocator
class AtomicMathematician
Base class for classes that performs arithmetic operations between atomic values.
class AtomicMathematicianLocator
class AtomicString
Implements the value instance of the xs:string type.
class AtomicType
Base class for all classes that implements atomic types.
class AtomicTypeVisitor
class AtomicTypeVisitorResult
class AtomicValue
Base class for all classes representing atomic values.
class Atomizer
Performs atomization. Effectively, it is an implementation of the fn:data() function.
class AttributeConstructor
Constructs an element node. This covers both computed and directly constructed element nodes.
class AttributeIterator
Implements axis attribute for the AccelTree.
class AttributeNameValidator
Ensures the lexical space of the string value of the Item returned from its child Expression is an NCName. Also possibly changes the name by generating a prefix if one is needed.
class AutoPtr
A smart pointer very similar to std::auto_ptr.
class AutoPtrRef
class AvgFN
Implements the function fn:avg().
class AxisStep
A step in a path expression that with an axis and a node test evaluates to a sequence of nodes from the context item.
class Base64Binary
Implements the value instance of the xs:base64Binary type.
class Base64BinaryComparatorLocator
class Base64BinaryToHexBinaryCaster
Casts a xs:base64Binary atomic value to xs:hexBinary.
class Base64BinaryType
Implements the type xs:base64Binary.
class BaseURIFN
Implements the function fn:base-uri().
class BasicTypesFactory
Factory for creating schema types for the types defined in XSL-T 2.0.
class BinaryDataComparator
Compares xs:base64Binary and xs:hexBinary values.
class Boolean
Implements the value instance of the xs:boolean type.
class BooleanComparator
Compares xs:boolean values.
class BooleanComparatorLocator
class BooleanFN
Implements the function fn:boolean().
class BooleanIdentifier
Matches boolean literals.
class BooleanToAbstractFloatCaster
Casts a value of type xs:boolean to xs:double or xs:float.
class BooleanToDecimalCaster
Casts a value of type xs:boolean to xs:decimal.
class BooleanToDerivedIntegerCaster
Casts an xs:boolean instance to a derived type of xs:integer.
class BooleanToIntegerCaster
Casts a value of type xs:boolean to xs:integer.
class BooleanType
Implements the type xs:boolean.
class BuiltinAtomicType
Instances of this class represents types that are sub-classes of xs:anyAtomicType.
class BuiltinNodeType
Instances of this class represents types that are sub-classes of node(), such as processing-instruction().
class BuiltinTypes
Provides access to singleton instances of ItemType and SchemaType sub-classes.
class ByIDCreator
Creates a particular Expression instance identified by an Expression::ID.
class ByIDIdentifier
Identifies Expression instances by their Expression::id().
class BySequenceTypeIdentifier
Identifies Expression instances based on their static type.
class CachingIterator
An QAbstractXmlForwardIterator that gets its item from a cache unless its empty, in which case it continues to populate the cache as well as deliver on its own from a source QAbstractXmlForwardIterator.
class CallSite
Abstract base-class for Expression instances that are callsites to other components, such as templates or user functions.
class CallTargetDescription
Contains metadata for a callable component, such as a function or template.
class CallTemplate
Implements xsl:call-template.
class Cardinality
Represents a cardinality, a possible , often represented by occurrence indicators.
class CardinalityVerifier
Verifies that the sequence an Expression evaluates to conforms to a Cardinality.
class CaseInsensitiveStringComparator
Performs case insensitive string comparison between xs:anyUri, xs:string, and xs:untypedAtomic.
class CastableAs
Implements XPath 2.0's castable as expression.
class CastAs
Implements XPath 2.0's cast as expression.
class CastingPlatform
Provides casting functionality for classes, such as CastAs or NumberFN, which needs to perform casting.
class CeilingFN
Implements the function fn:ceiling().
class ChildIterator
Iterates along the child axis in an AccelTree.
class CodepointEqualFN
Implements the function fn:codepoint-equal().
class CodepointsToStringFN
Implements the function fn:codepoints-to-string().
class CollationChecker
Checks that its operand evaluates to a supported string collation.
class CollectionFN
Implements the function fn:collection().
class ColoringMessageHandler
class ColorOutput
class ColorOutputPrivate
class CombineNodes
Implements XPath 2.0's operators for combining node sequences: union, intersect and except.
class CommentConstructor
Constructs a comment node. This covers both computed and directly constructed text nodes.
class CommonSequenceTypes
Provides access to singleton instances of SequenceType sub-classes.
class CommonValues
A collection of common values.
class CompareFN
Implements the function fn:compare().
class ComparesCaseAware
Base-class for functions that compares strings and provides an opportunity to optimize compares intended to be case insensitive.
class ComparingAggregator
Base class for the implementations of the fn:min() and fn:max() function.
class ComparisonFactory
Provides compare(), which is a high-level helper function for comparing atomic values.
class ComparisonIdentifier
Determines whether an Expression is a value or general comparison or both, with a certain operator.
class ComparisonPlatform
Provides comparison functionality for classes that compare Items, such as ValueComparison or MaxFN.
class CompressedWhitespace
A compression facility for whitespace nodes.
class ComputedNamespaceConstructor
Constructs a namespace on an element, and naturally only appears as a child of ElementConstructor.
class ConcatFN
Implements the function fn:concat().
class ConstructorFunctionsFactory
A function factory that handles the builtin constructor functions, such as xs:time().
class ContainsFN
Implements the function fn:contains().
class ContextItem
Implements the context item, the dot: ..
class ContextNodeChecker
Helper class that checks that the context node is a document node.
class CopyOf
Does node copying in a parameterized way, in order to deal with namespace preservation/inheritance.
class CountFN
Implements the function fn:count().
class CppCastingHelper
Provides convenience methods for performing static casts between C++ classes.
class CurrentDateFN
Implements the function fn:current-date().
class CurrentDateTimeFN
Implements the function fn:current-dateTime().
class CurrentFN
Implements XSL-T's function fn:current().
class CurrentItemContext
A DynamicContext that maintains the focus, a sequence of items.
class CurrentItemStore
Creates a DynamicContext which provides the focus item for the function fn:current().
class CurrentTimeFN
Implements the function fn:current-time().
class Date
Implements the value instance of the xs:date type.
class DateComparatorLocator
class DateMathematicianLocator
class DateTime
Implements the value instance of the xs:dateTime type.
class DateTimeComparatorLocator
class DateTimeDurationMathematician
Performs arithmetics between an AbstractDateTime value and an AbstractDuration value.
class DateTimeFN
Implements the function fn:dateTime().
class DateTimeMathematicianLocator
class DateTimeType
Implements the type xs:dateTime.
class DateType
Implements the type xs:date.
class DayFromAbstractDateTimeFN
Extracts the day property from a sub-class of AbstractDateTime such as DateTime or Date. This function implements fn:day-from-dateTime() and fn:day-from-date().
class DaysFromDurationFN
Implements the function fn:days-from-duration().
class DayTimeDuration
Implements the value instance of the xs:dayTimeDuration type.
class DayTimeDurationComparatorLocator
class DayTimeDurationMathematicianLocator
class DayTimeDurationType
Implements the type xs:dayTimeDuration.
class Decimal
Implements the value instance of the xs:decimal type.
class DecimalComparator
Compares xs:decimal values.
class DecimalComparatorLocator
class DecimalMathematician
class DecimalMathematicianLocator
class DecimalType
Implements the type xs:decimal.
class DeduplicateIterator
Performs deduplication of the nodes on its source list.
class DeepEqualFN
Implements the function fn:deep-equal().
class DefaultCollationFN
Implements the function fn:default-collation().
class DelegatingDynamicContext
Base class for dynamic contexts that are created from an existing one.
class DelegatingNamespaceResolver
Contains a set of bindings, plus a pointer to another resolver which is delegates requests to, in case it can't handle a lookup on its own.
class DelegatingSourceLocationReflection
class DelegatingStaticContext
Delegates all members to a second instance. Used for sub-classing.
class DerivedInteger
Represents instances of derived xs:integer types, such as xs:byte.
class DerivedIntegerDetails
class DerivedIntegerDetails< TypeByte >
class DerivedIntegerDetails< TypeInt >
class DerivedIntegerDetails< TypeLong >
class DerivedIntegerDetails< TypeNegativeInteger >
class DerivedIntegerDetails< TypeNonNegativeInteger >
class DerivedIntegerDetails< TypeNonPositiveInteger >
class DerivedIntegerDetails< TypePositiveInteger >
class DerivedIntegerDetails< TypeShort >
class DerivedIntegerDetails< TypeUnsignedByte >
class DerivedIntegerDetails< TypeUnsignedInt >
class DerivedIntegerDetails< TypeUnsignedLong >
class DerivedIntegerDetails< TypeUnsignedShort >
class DerivedIntegerType
class DerivedString
Represents instances of derived xs:string types, such as xs:normalizedString.
class DerivedStringType
class DescendantIterator
Implements axis descendant and descendant-or-self for the AccelTree.
class DeviceResourceLoader
Base class for resource loaders that manage device variables.
class DistinctIterator
Filters another sequence by removing duplicates such that the items are unique.
class DistinctValuesFN
Implements the function fn:distinct-values().
class DocAvailableFN
Implements the function fn:doc-available().
class DocFN
Implements the function fn:doc().
class DocumentConstructor
Constructs a text node. This covers both computed and directly constructed text nodes.
class DocumentContentValidator
Receives QAbstractXmlReceiver events and validates that they are correct, before sending them on to a second QAbstractXmlReceiver.
class DocumentFN
Implements XSL-T's function fn:document().
class DocumentProjector
class DocumentURIFN
Implements the function fn:document-uri().
class DoubleComparatorLocator
class DoubleMathematicianLocator
class DoubleType
Implements the type xs:double.
class Duration
Implements the value instance of the xs:duration type.
class DurationComparatorLocator
class DurationDurationDivisor
Performs division between DayTimeDuration and DayTimeDuration, or YearMonthDuration and YearMonthDuration.
class DurationDurationMathematician
Performs arithmetics between DayTimeDuration and DayTimeDuration, or YearMonthDuration and YearMonthDuration.
class DurationNumericMathematician
Performs division or multiplication between either DayTimeDuration or YearMonthDuration and Double values.
class DurationType
Implements the type xs:duration.
class DynamicContext
Carries information and facilities used at runtime, and hence provides a state for that stage in a thread-safe manner.
class DynamicContextStore
Evaluates its operand with an assigned DynamicContext, not the one passed to one of the evaluation functions.
class EBVExtractor
Calculates the Effective Boolean Value of its operand.
class EBVType
Represents the type for which a value of can an Effective Boolean Value be extracted from.
class ElementAvailableFN
Implements the function fn:unparsed-text().
class ElementConstructor
Constructs an element node. This covers both computed and directly constructed element nodes.
class ElementDescription
A structure that lists the optional and required attributes of an element. Used with MaintainingReader.
class ElementNamespaceHandler
A helper class for automatically handling namespace scopes of elements.
class EmptyContainer
Base class for expressions that has no operands.
class EmptyIterator
An QAbstractXmlForwardIterator which always is empty.
class EmptySequence
Implements the value instance of empty sequence: ().
class EmptySequenceType
Represents the empty-sequence() type.
class EncodeForURIFN
Implements the function fn:encode-for-uri().
class EncodeString
Provides functionality for encoding strings. Sub-classed by various function implementations.
class EndsWithFN
Implements the function fn:ends-with().
union EnumUnion
A union of all the enums the parser uses.
class ErrorFN
Implements the function fn:error().
class EscapeHtmlURIFN
Implements the function fn:escape-html-uri().
class EvaluationCache
Evaluates to the same result as its operand, but ensures the operand is evaluated once even if this Expression is evaluated several times.
class ExceptIterator
Implements the except operator. That is, the computation of the sequence of nodes from one sequence, that doesn't appear in the other.
class Existence
Implements the functions fn:exists() and fn:empty().
class Expression
Base class for all AST nodes in an XPath/XQuery/XSL-T expression.
class ExpressionCreator
A factory for creating Expression instances.
class ExpressionFactory
The central entry point for compiling expressions.
class ExpressionIdentifier
Abstract base class for all classes that identify Expressions based on some criteria.
class ExpressionSequence
Implements the comma(",") operator, the sequence constructor.
class ExpressionVariableReference
A reference to a variable declared with declare variable or let.
class ExpressionVisitor
class ExpressionVisitorResult
class ExternalVariableLoader
Responsible for loading and declaring available external variables.
class ExternalVariableReference
A reference to an external variable.
class ExtractFromDateTimeFN
Helper class for implementing functions extracting components from date/time values.
class ExtractFromDurationFN
Helper class for implementing functions extracting components from durations.
class FalseFN
Implements the function fn:false().
class FieldNode
A helper class for validating identity constraints.
class FirstItemPredicate
A predicate that always selects the first item from its sequence.
class FloatComparatorLocator
class FloatMathematicianLocator
class FloatType
Implements the type xs:float.
class FloorFN
Implements the function fn:floor().
class Focus
A DynamicContext that maintains the focus, a sequence of items.
class FollowingIterator
Implements axis following for the AccelTree.
class ForClause
Implements XPath 2.0's for expression.
class FunctionArgument
Carries meta data for a function argument as found in XPath's builtin functions and user declared functions in XQuery and XSL-T.
class FunctionAvailableFN
Implements XSL-T 2.0's XPath function fn:function-available().
class FunctionCall
Base class for implementations of builtin functions.
class FunctionFactory
An entry point for looking up and creating FunctionCall instances.
class FunctionFactoryCollection
A FunctionFactoryCollection instance is a FunctionFactory in its own right, but looks in its contained collection of factories for requested functions.
class FunctionSignature
Represents the signature of an XPath function.
class GDay
Implements the value instance of the xs:gDay type.
class GDayComparatorLocator
class GDayType
Implements the type xs:gDay.
class GeneralComparison
Implements XPath 2.0's general comparions, such as the = operator.
class GenerateIDFN
Implements the function fn:generate-id().
class GenericDynamicContext
A DynamicContext supplying basic information that always is used.
class GenericNamespaceResolver
Generic namespace resolver which resolves lookups against entries in a QHash.
class GenericPredicate
A predicate that can handle all kinds of predicates and is therefore not very efficient, but can cope with all the tricky scenarios.
class GenericSequenceType
class GenericStaticContext
Provides setters and getters for the properties defined in StaticContext.
class GMonth
Implements the value instance of the xs:gMonth type.
class GMonthComparatorLocator
class GMonthDay
Implements the value instance of the xs:gYearMonth type.
class GMonthDayComparatorLocator
class GMonthDayType
Implements the type xs:gMonthDay.
class GMonthType
Implements the type xs:gMonth.
class GYear
Implements the value instance of the xs:gYear type.
class GYearComparatorLocator
class GYearMonth
Implements the value instance of the xs:gYearMonth type.
class GYearMonthComparatorLocator
class GYearMonthType
Implements the type xs:gYearMonth.
class GYearType
Implements the type xs:gYear.
class HexBinary
Implements the value instance of the xs:hexBinary type.
class HexBinaryComparatorLocator
class HexBinaryToBase64BinaryCaster
Casts a xs:hexBinary atomic value to xs:base64Binary.
class HexBinaryType
Implements the type xs:hexBinary.
class HoursFromAbstractDateTimeFN
Extracts the minute property from a sub-class of AbstractDateTime such as DateTime or SchemaTime. Implements the functions fn:hours-from-dateTime() and fn:hours-from-time().
class HoursFromDurationFN
Implements the function fn:hours-from-duration().
class IdFN
Implements the function fn:id().
class IdrefFN
Implements the function fn:idref().
class IfThenClause
Implements XPath 2.0's conditional expression if([expr]) then [expr] else [expr].
class ImplicitTimezoneFN
Implements the function fn:implicit-timezone().
class IndexOfFN
Implements the function fn:index-of().
class IndexOfIterator
Forms an QAbstractXmlForwardIterator over a sequence of integers, which each is the position of where a search parameter appeared in another QAbstractXmlForwardIterator.
class InScopePrefixesFN
Implements the function fn:in-scope-prefixes().
class InsertBeforeFN
Implements the function fn:insert-before().
class InsertionIterator
Conceptually inserts one QAbstractXmlForwardIterator into another, make two QAbstractXmlForwardIterator instances appear as one.
class InstanceOf
Implements XPath 2.0's instance of expression.
class Integer
Implements the value instance of the xs:integer type.
class IntegerComparator
Compares xs:integer values.
class IntegerComparatorLocator
class IntegerIdentifier
Matches numeric literals that are of type xs:integer and has a specific value.
class IntegerMathematician
Performs arithmetics between Integer values.
class IntegerMathematicianLocator
class IntegerType
Implements the type xs:integer.
class IntersectIterator
Implements the intersect operator. That is, the computation of the intersection between two sequences of nodes.
class IriToURIFN
Implements the function fn:iri-to-uri().
class Item
Represents an item in the XPath 2.0 Data Model.
class ItemCacheCell
Represents a cache entry for a single Item, as opposed to for a sequence of items.
class ItemMappingIterator
Proxies another QAbstractXmlForwardIterator, and for each item, returns the Item returned from a mapping function.
class ItemSequenceCacheCell
Represents a cache entry for a sequence of items.
class ItemType
Base class for the XPath Data Model's type hierarchy.
class ItemVerifier
Verifies that the items in a sequence an Expression evaluates is of a certain ItemType.
class IteratorVector
class LangFN
Implements the function fn:lang().
class LastFN
Implements the function fn:last().
class LetClause
Represents a let-clause, but is only used at compile time.
class ListIterator
Bridges values in Qt's QList container class into an QAbstractXmlForwardIterator.
class ListIteratorPlatform
Helper class for ListIterator, and should only be instantiated through sub-classing.
class Literal
Houses an AtomicValue, making it available as an Expression.
class LiteralSequence
Houses a sequence of atomic values, making it available as an Expression.
class LocalNameFN
Implements the function fn:local-name().
class LocalNameFromQNameFN
Implements the function fn:local-name-from-QXmlName().
class LocalNameTest
A name test that is of the type *:local-name.
class LowerCaseFN
Implements the function fn:lower-case().
class MaintainingReader
Base class for tokenizers that reads XML formats. This is XSLTTokenizer, and the W3C XML Schema parser.
class MatchesFN
Implements the function fn:matches().
class MergeIterator
class MinutesFromAbstractDateTimeFN
Extracts the minutes property from a sub-class of AbstractDateTime such as DateTime or Date. Implements the functions fn:minutes-from-dateTime() and fn:minutes-from-time().
class MinutesFromDurationFN
Implements the function fn:minutes-from-duration().
class MonthFromAbstractDateTimeFN
implements the functions fn:month-from-dateTime() and fn:month-from-date().
class MonthsFromDurationFN
Implements the function fn:months-from-duration().
class MultiItemType
Represents multiple types such as document() or xs:integer.
class NamedSchemaComponent
Base class for all named components that can appear in a W3C XML Schema.
class NameFN
Implements the function fn:name().
class NamePool
Store names such as namespace bindings and QNames and allows them to be referenced in efficient ways.
class NamespaceBinding
Represents a namespace binding: a prefix, and a namespace URI.
class NamespaceConstructor
Constructs a namespace on an element, and naturally only appears as a child of ElementConstructor.
class NamespaceNameTest
A name test that is of the type prefix:*.
class NamespaceResolver
Base class for namespace resolvers.
class NamespaceSupport
A helper class for handling nested namespace declarations.
class NamespaceURIFN
Implements the function fn:namespace-uri().
class NamespaceURIForPrefixFN
Implements the function fn:namespace-uri-from-QXmlName().
class NamespaceURIFromQNameFN
Implements the function fn:local-name-from-QXmlName().
class NCNameConstructor
Ensures the lexical space of the string value of the Item returned from its child Expression is an NCName.
class NetworkAccessDelegator
A value based class that hands out QNetworkAccessManager appropriately for variable bindings.
class NetworkLoop
An helper class which enables QNetworkAccessManager to be used in a blocking manner.
class NilledFN
Implements the function fn:nilled().
class NodeBuilder
Receives QAbstractXmlReceiver events and builds a node tree in memory that afterwards can be retrieved via builtNode()
class NodeComparison
Implements the node comparison operators >>, <<, and is.
class NodeIndexStorage
class NodeNameFN
Implements the function fn:node-name().
class NodeNamespaceResolver
A NamespaceResolver that use a QXmlNodeModelIndex's in-scope namespace bindings for resolving namespaces.
class NodeSortExpression
De-duplicates and sorts in document order the content that its operand returns.
class NoneType
Represents the special none type.
class NormalizeSpaceFN
Implements the function fn:normalize-space().
class NormalizeUnicodeFN
Implements the function fn:normalize-unicode().
class NOTATIONType
Implements the type xs:NOTATION.
class NotFN
Implements the function fn:not().
class NumberFN
Implements the function fn:number().
class Numeric
Base class for all numeric values.
class NumericToAbstractFloatCaster
Casts a numeric value, such as xs:integer or xs:float, to xs:double or xs:float.
class NumericToBooleanCaster
Casts any numeric value to xs:boolean.
class NumericToDecimalCaster
Casts a numeric value, such as xs:double or xs:decimal, to xs:integer or xs:decimal, depending on IsInteger.
class NumericToDerivedIntegerCaster
Casts any numeric instance to a derived type of xs:integer.
class NumericType
Represents the internal and abstract type fs:numeric.
class OperandsIterator
A helper class that iterates a tree of Expression instances. It is not a sub-class of QAbstractXmlForwardIterator.
class OperandSwitcherMathematician
Delegates an AtomicMathematician and switches its operands.
class OptimizationPass
Describes how a particular optimization pass should be carried out.
class OrderBy
Performs the sorting by being a parent to ForClause.
class OrderSpecTransfer
class OrExpression
Implements XPath 2.0's logical expression or.
class OutputValidator
Receives QAbstractXmlReceiver events and validates that they are correct, before sending them on to a second QAbstractXmlReceiver.
class PairContainer
Base class for expressions that has exactly two operands.
class ParameterizedAtomicTypeVisitor
class ParentNodeAxis
Corresponds to the expression parent::node().
class ParserContext
Contains data used when parsing and tokenizing.
class Path
Implements the path expression, containing two steps, such as in html/body.
class PatternFlag
Used internally by PatternPlatform and describes a flag that affects how a pattern is treated.
class PatternPlatform
Contains functionality for functions and expressions that uses regular expressions.
class PositionalVariableReference
A reference to an at variable, declared with the for-part in XQuery's FLWOR expression.
class PositionFN
Implements the function fn:position().
class PrecedingIterator
Implements axis preceding for the AccelTree.
class PrefixFromQNameFN
Implements the function fn:prefix-from-QXmlName().
class ProcessingInstructionConstructor
Constructs an element node. This covers both computed and directly constructed element nodes.
class ProjectedExpression
class ProjectedNodeTest
class ProjectedPath
class ProjectedStep
class PullBridge
Bridges a QPatternist::SequenceIterator to QAbstractXmlPullProvider.
class QAbstractXmlReceiver
A push interface for the XPath Data Model. Similar to SAX's ContentHandler.
class QIODeviceDelegate
class QNameComparator
Compares xs:QName values.
class QNameComparatorLocator
class QNameConstructor
Creates an xs:QName value from a lexical QName using statically known namespace bindings.
class QNameFN
Implements the function fn:QXmlName().
class QNameTest
A name test that is of the type prefix:ncName.
class QNameType
Implements the type xs:QName.
class QNameValue
Implements the value instance of the xs:QName type.
class QtXmlPatterns
Provides a translation context & functions for the QtXmlPatterns module.
class QuantifiedExpression
Implements XPath 2.0's quantification expressions some and every.
class RangeExpression
Implements XPath 2.0's to expression.
class RangeIterator
RangeIterator represents a sequence of integers between a start and end value.
class RangeVariableReference
A reference to a variable declared with for or a quantification expression, but not for instance a let binding.
class ReceiverDynamicContext
A DynamicContext that has a specialized QAbstractXmlReceiver.
class ReferenceCountedValue
A template class that reference counts a value.
class ReflectYYLTYPE
class RemovalIterator
Removes one items at a specified position from an input QAbstractXmlForwardIterator.
class RemoveFN
Implements the function fn:remove().
class ReplaceFN
Implements the function fn:replace().
class ReportContext
A callback for reporting errors.
class ResolveQNameFN
Implements the function fn:resolve-QXmlName().
class ResolveURIFN
Implements the function fn:resolve-uri().
class ResourceDelegator
Delegates to another ResourceLoader, but in case a URI is in an exception list, it delegates to a different loader.
class ResourceLoader
Responsible for handling requests for opening files and node collections.
class ReturnOrderBy
Together with OrderBy, it implements XQuery 1.0's order by expression.
class ReverseFN
Implements the function fn:reverse().
class RootFN
Implements the function fn:root().
class RoundFN
Implements the function fn:round().
class RoundHalfToEvenFN
Implements the function fn:round-half-to-even().
class SchemaComponent
Base class for all constructs that can appear in a W3C XML Schema.
class SchemaTime
Implements the value instance of the xs:time type.
class SchemaTimeComparatorLocator
class SchemaTimeMathematicianLocator
class SchemaTimeType
Implements the type xs:time.
class SchemaType
Base class for W3C XML Schema types.
class SchemaTypeFactory
A factory creating schema types.
class SecondsFromAbstractDateTimeFN
Extracts the seconds property from a sub-class of AbstractDateTime such as DateTime or Date. Implements the functions fn:seconds-from-dateTime() and fn:seconds-from-time().
class SecondsFromDurationFN
Implements the function fn:seconds-from-duration().
class SelfToSelfCaster
Casts a value to itself. Essentially, this AtomicCaster does nothing.
class SequenceMappingIterator
Proxies another QAbstractXmlForwardIterator, and for each item, returns the Sequence returned from a mapping function.
class SequenceType
A SequenceType instance represents the type of a sequence of Item instances.
class SiblingIterator
Iterates along the sibling axes in an AccelTree.
class SimpleContentConstructor
Constructs simple content as specified for attributes in direct element constructors in XQuery.
class SingleContainer
Base class for expressions that has exactly one operand.
class SingleTokenContainer
A TokenSource which contains one Tokenizer::Token.
class SingletonIterator
An QAbstractXmlForwardIterator over exactly one item.
class SortTuple
Represents a value and its sort keys in FLOWR's order by clause.
class SourceLocationReflection
Base class for all instances that represents something at a certain location.
class StackContextBase
Base class for all DynamicContext classes that needs to supply variables. It has a new frame for local caches, position iterators, expressions, range variables, template parameters but notably continues to delegate global caches.
class StandardLocalNames
class StandardNamespaces
class StandardPrefixes
class StartsWithFN
Implements the function fn:starts-with().
class StaticBaseUriContainer
Base class for functions that needs to store the static base URI for use at runtime.
class StaticBaseURIContext
A StaticContext that changes the static base URI. of items.
class StaticBaseURIFN
Implements the function fn:static-base-uri().
class StaticBaseURIStore
A compile time only AST node that changes the static base URI, used when xml:base attributes appears.
class StaticCompatibilityContext
Has the XPath Compatibility Mode activated. Used for XSL-T 2.0's compatibility mode.
class StaticCompatibilityStore
A compile time only AST node that changes the backwareds compatibility mode. Used for XSL-T 2.0's backwards compatibility mode.
class StaticContext
Carries information and facilities used at compilation time.
class StaticCurrentContext
A StaticContext that carries a specified static type for the current item, as returned by fn:current(), but otherwise delegates to another StaticContext.
class StaticFocusContext
A StaticContext that carries a specified static type for the context item, but otherwise delegates to another StaticContext.
class StaticNamespaceContext
A StaticContext that carries a specified namespace resolver for the context item, but otherwise delegates to another StaticContext.
class StaticNamespacesContainer
A helper subclass that stores a NamespaceResolver for the static namespaces.
class StringComparator
Performs case sensitive string comparison between xs:anyUri, xs:string, and xs:untypedAtomic.
class StringComparatorLocator
class StringFN
Implements the function fn:string().
class StringJoinFN
Implements the function fn:string-join().
class StringLengthFN
Implements the function fn:string-length().
class StringListIterator
class StringToAbstractFloatCaster
Casts a string value, xs:string or xs:untypedAtomic, to xs:double or xs:float.
class StringToBase64BinaryCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:base64Binary.
class StringToBooleanCaster
Casts any string value, xs:string or xs:untypedAtomic, to xs:boolean.
class StringToCodepointsFN
Implements the function fn:string-to-codepoints().
class StringToDateCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:date.
class StringToDateTimeCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:dateTime.
class StringToDayTimeDurationCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:dayTimeDuration.
class StringToDecimalCaster
Casts a string value, xs:string or xs:untypedAtomic, to xs:decimal.
class StringToDerivedIntegerCaster
Casts an xs:string instance to a derived type of xs:integer.
class StringToDurationCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:duration.
class StringToGDayCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:gDay.
class StringToGMonthCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:gMonth.
class StringToGMonthDayCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:gYearMonth.
class StringToGYearCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:gYear.
class StringToGYearMonthCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:gYearMonth.
class StringToHexBinaryCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:hexBinary.
class StringToIntegerCaster
Casts a string value, xs:string or xs:untypedAtomic, to xs:integer.
class StringToTimeCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:time.
class StringToYearMonthDurationCaster
Casts a xs:string or xs:untypedAtomic atomic value to xs:yearMonthDuration.
class StringType
class SubsequenceFN
Implements the function fn:subsequence().
class SubsequenceIterator
Picks out a slice from another QAbstractXmlForwardIterator, specified by a start and end position.
class SubstringAfterFN
Implements the function fn:substring-after().
class SubstringBeforeFN
Implements the function fn:substring-before().
class SubstringFN
Implements the function fn:substring().
class SumFN
Implements the function fn:sum().
class SystemPropertyFN
Implements XSL-T 2.0's XPath function fn:system-property().
class TagValidationHandler
class TargetNode
A helper class for validating identity constraints.
class Template
Contains data related to a template.
class TemplateInvoker
Base class for classes that invokes templates, such as CallTemplate and ApplyTemplate.
class TemplateMode
Houses the data specific to the templates for a certain mode.
class TemplateParameterReference
A reference to a template parameter declared with xsl:param.
class TemplatePattern
Houses the data necessary for a template pattern.
class TemporaryTreesRedirectingContext
class TextNodeConstructor
Constructs a text node. This covers both computed and directly constructed text nodes.
class TimezoneFromAbstractDateTimeFN
Extracts the timezone property from a sub-class of AbstractDateTime such as DateTime or Date. Implements the functions fn:timezone-from-dateTime(), fn:timezone-from-time() and fn:timezone-from-date().
class ToAnyURICaster
Casts a string value to xs:anyURI.
class ToAnyURICasterLocator
class ToBase64BinaryCasterLocator
class ToBooleanCasterLocator
class ToCodepointsIterator
Represents a stream of Unicode codepoints, which are computed from a string.
class ToDateCasterLocator
class ToDateTimeCasterLocator
class ToDayTimeDurationCasterLocator
class ToDecimalCasterLocator
class ToDerivedIntegerCasterLocator
class ToDerivedStringCasterLocator
class ToDoubleCasterLocator
class ToDurationCasterLocator
class ToFloatCasterLocator
class ToGDayCasterLocator
class ToGMonthCasterLocator
class ToGMonthDayCasterLocator
class ToGYearCasterLocator
class ToGYearMonthCasterLocator
class ToHexBinaryCasterLocator
class ToIntegerCasterLocator
class TokenizeFN
Implements the function fn:tokenize().
class Tokenizer
Base class for all tokenizers.
class TokenLookup
struct TokenMap
class TokenRevealer
Delegates another Tokenizer, and while doing so prints the tokens it delivers to stderr.
class TokenSource
Base class for components that needs to return tokens.
class TokenValue
The value the parser, but not the tokenizers, uses for tokens and non-terminals.
class ToQNameCasterLocator
class ToSchemaTimeCasterLocator
class ToStringCaster
Casts any atomic value to xs:string.
class ToStringCasterLocator
class ToUntypedAtomicCaster
Casts any atomic value to xs:untypedAtomic.
class ToUntypedAtomicCasterLocator
class ToYearMonthDurationCasterLocator
class TraceCallback
TraceCallback is a MappingCallback and takes care of the tracing of each individual item.
class TraceFN
Implements the function fn:trace().
class TranslateFN
Implements the function fn:translate().
class TreatAs
Implements XPath 2.0's treat as expression.
class TripleContainer
Base class for expressions that has exactly three operands.
class TrueFN
Implements the function fn:true().
class TruthPredicate
A predicate which is optimized for filter expressions that are of type xs:boolean.
class TypeAvailableFN
Implements XSL-T 2.0's XPath function fn:type-available().
class TypeChecker
Contains functions that applies Function Conversion Rules and other kinds of compile-time type checking tasks.
class UnaryExpression
Implements XPath 2.0 unary expression, (-|+)ValueExpr.
class UnionIterator
Implements the except operator. That is, the computation of the sequence of nodes from one sequence, that doesn't appear in the other.
class UnlimitedContainer
Base class for expressions that has any amount of operands.
class UnparsedEntityPublicIDFN
Implements XSL-T 2.0's XPath function fn:unparsed-entity-public-id().
class UnparsedEntityURIFN
Implements XSL-T 2.0's XPath function fn:unparsed-entity-uri().
class UnparsedTextAvailableFN
Implements the function fn:unparsed-text-available().
class UnparsedTextFN
Implements the function fn:unparsed-text().
class UnresolvedVariableReference
Compile time only AST-node which is a marker for variable references whose declaration has not yet appeared in the source code.
class Untyped
Represents the complex W3C XML Schema type xs:untyped.
class UntypedAtomic
Implements the value instance of the xs:untypedAtomic type.
class UntypedAtomicConverter
Casts every item in a sequence obtained from evaluating an Expression, to a requested atomic type.
class UntypedAtomicType
Implements the type xs:untypedAtomic.
class UpperCaseFN
Implements the function fn:upper-case().
class URILoader
class UserFunction
A function created with XQuery's declare function declaration.
class UserFunctionCallsite
Performs a call to a UserFunction.
class Validate
Handles XQuery 1.0's validate expression.
class ValidationError
Used for signalling casting errors.
class ValueComparison
Implements XPath 2.0 value comparions, such as the eq operator.
class ValueFactory
Provides fromLexical(), which allows instantiation of atomic values from arbitrary types.
class VariableDeclaration
Represents a declared variable. Only used at the compilation stage.
class VariableLoader
class VariableReference
Baseclass for classes being references to variables.
class VariantListIterator
class WithParam
Carries meta data for xsl:with-param as encountered in template callsites such as xsl:call-template and xsl:apply-templates.
class XPath10CoreFunctions
Supplies the functions available in XPath 1.0.
class XPath20CoreFunctions
Handles the functions defines in XQuery 1.0 and XPath 2.0 Function and Operators, except those also available in XPath 1.0.
class XPathHelper
Contains helper and utility functions.
class XQueryTokenizer
A hand-written tokenizer which tokenizes XQuery 1.0 & XPath 2.0, and delivers tokens to the Bison generated parser.
class XsdAlternative
Represents a XSD alternative object.
class XsdAnnotated
Base class for all XSD components with annotation content.
class XsdAnnotation
Represents a XSD annotation object.
class XsdApplicationInformation
Represents a XSD appinfo object.
class XsdAssertion
Represents a XSD assertion object.
class XsdAttribute
Represents a XSD attribute object.
class XsdAttributeGroup
Represents the XSD attributeGroup object.
class XsdAttributeReference
A helper class for attribute reference resolving.
class XsdAttributeTerm
A base class for all attribute types.
class XsdAttributeUse
Represents a XSD attribute use object.
class XsdComplexType
Represents a XSD complexType object.
class XsdDocumentation
Represents a XSD documentation object.
class XsdElement
Represents a XSD element object.
class XsdFacet
Represents a XSD facet object.
class XsdIdCache
Helper class for keeping track of all existing IDs in a schema.
class XsdIdentityConstraint
Represents a XSD identity constraint object.
class XsdInstanceReader
The schema instance reader.
class XsdModelGroup
Represents a XSD model group object.
class XsdNotation
Represents a XSD notation object, which should not be confused with the atomic type xs:NOTATION.
class XsdParticle
Represents a XSD particle object.
class XsdParticleChecker
A helper class to check validity of particles.
class XsdReference
A helper class for element and group reference resolving.
class XsdSchema
Represents a XSD schema object.
class XsdSchemaChecker
Encapsulates the checking of schema valitity after reference resolving has finished.
class XsdSchemaContext
A context for schema parsing and validation.
class XsdSchemaDebugger
class XsdSchemaHelper
Contains helper methods that are used by XsdSchemaParser, XsdSchemaResolver and XsdSchemaChecker.
class XsdSchemaMerger
A helper class that merges two schemas into one.
class XsdSchemaParser
Implements the parsing of XML schema file.
class XsdSchemaParserContext
A context for schema parsing.
class XsdSchemaResolver
Encapsulates the resolving of type/element references in a schema after parsing has finished.
class XsdSchemaSourceLocationReflection
An implementation of SourceLocationReflection that takes a QSourceLocation.
class XsdSchemaTypesFactory
Factory for creating schema types for the types defined in XSD.
class XsdSimpleType
Represents a XSD simpleType object.
class XsdStateMachine
A state machine used for evaluation.
class XsdStateMachineBuilder
A helper class to build up validation state machines.
class XsdTagScope
A namespace class that contains identifiers for the different scopes a tag from the xml schema spec can appear in.
class XsdTerm
A base class for all particles of a model group.
class XsdTypeChecker
The class that provides methods for checking a string against a type.
class XsdUserSchemaType
A base class for all user defined simple and complex types.
class XsdValidatedXmlNodeModel
A delegate class that wraps around a QAbstractXmlNodeModel and provides additional validation specific information.
class XsdValidatingInstanceReader
The validating schema instance reader.
class XsdWildcard
Represents a XSD wildcard object.
class XsdXPathExpression
Represents a XSD assertion object.
class XSLT20CoreFunctions
Handles the functions defines in XSL-T 2.0, except those also available in XPath 2.0.
class XSLTNodeTest
Represents node() in patterns in XSL-T, which are just like how node() usually is, except that it doesn't match document nodes.
class XSLTSimpleContentConstructor
Implements XSL-T's construction of simple content, which is different from XQuery's approach.
class XSLTTokenizer
Tokenizes XSL-T 2.0 documents.
class XSLTTokenLookup
class YearFromAbstractDateTimeFN
Extracts the year property from a sub-class of AbstractDateTime such as DateTime or Date. This function implements fn:year-from-dateTime() and fn:year-from-date().
class YearMonthDuration
Implements the value instance of the xs:yearMonthDuration type.
class YearMonthDurationComparatorLocator
class YearMonthDurationMathematicianLocator
class YearMonthDurationType
Implements the type xs:yearMonthDuration.
class YearsFromDurationFN
Implements the function fn:years-from-duration().
Typedefs
typedef QPair< QString, Expression::Ptr > AttributeHolder
typedef QVector< AttributeHolder > AttributeHolderVector
typedef BooleanToAbstractFloatCaster< true > BooleanToDoubleCaster
Casts a value of type xs:boolean to xs:double.
typedef BooleanToAbstractFloatCaster< false > BooleanToFloatCaster
Casts a value of type xs:boolean to xs:float.
typedef QHash< NamedSchemaComponent::Ptr, QSourceLocation > ComponentLocationHash
typedef qint32 DayCountProperty
typedef qint8 DayProperty
typedef AbstractFloat< true > Double
An instantiation of AbsbstractFloat suitable for xs:double.
typedef AbstractFloatMathematician< true > DoubleMathematician
typedef AbstractFloat< false > Float
An instantiation of AbstractFloat suitable for xs:float.
typedef AbstractFloatMathematician< false > FloatMathematician
typedef qint32 HourCountProperty
typedef qint8 HourProperty
typedef int ImportPrecedence
typedef QExplicitlySharedDataPointer< QAbstractXmlForwardIterator< Item > > ItemIteratorPtr
typedef QExplicitlySharedDataPointer< ItemType > ItemTypePtr
typedef ComparingAggregator< AtomicComparator::OperatorGreaterThan, AtomicComparator::GreaterThan > MaxFN
An instantiation of ComparingAggregator suitable for fn:max().
typedef ComparingAggregator< AtomicComparator::OperatorLessThan, AtomicComparator::LessThan > MinFN
An instantiation of ComparingAggregator suitable for fn:max().
typedef qint32 MinuteCountProperty
typedef qint8 MinuteProperty
typedef qint32 MonthCountProperty
typedef qint8 MonthProperty
typedef qint64 MSecondCountProperty
typedef qint16 MSecondProperty
typedef NumericToAbstractFloatCaster< true > NumericToDoubleCaster
Casts a numeric value, such as xs:integer or xs:float, to xs:double.
typedef NumericToAbstractFloatCaster< false > NumericToFloatCaster
Casts a numeric value, such as xs:double or xs:decimal, to xs:float.
typedef xsDouble PatternPriority
typedef QVector< QXmlName > QXmlNameVector
typedef qint32 SecondCountProperty
typedef qint32 SecondProperty
typedef StackContextBase< DelegatingDynamicContext > StackContext
A DynamicContext that creates a new scope for variables.
typedef StringToAbstractFloatCaster< true > StringToDoubleCaster
Casts a string value, xs:string or xs:untypedAtomic, to xs:double.
typedef StringToAbstractFloatCaster< false > StringToFloatCaster
Casts a string value, xs:string or xs:untypedAtomic, to xs:float.
typedef qint32 VariableSlotID
typedef xsDouble xsDecimal
typedef qreal xsDouble
typedef xsDouble xsFloat
typedef qint64 xsInteger
typedef qint32 YearProperty
typedef short int yytype_int16
typedef signed char yytype_int8
typedef unsigned short int yytype_uint16
typedef unsigned char yytype_uint8
typedef qint8 ZOHourProperty
typedef qint8 ZOMinuteProperty
typedef qint32 ZOTotal
Enumerations
enum { IgnorableSignedValue = 0, IgnorableUnsignedValue = 0 }
enum DerivedIntegerLimitsUsage
enum TypeOfDerivedInteger {
TypeByte, TypeInt, TypeLong, TypeNegativeInteger,
TypeNonNegativeInteger, TypeNonPositiveInteger, TypePositiveInteger, TypeShort,
TypeUnsignedByte, TypeUnsignedInt, TypeUnsignedLong, TypeUnsignedShort
}
enum TypeOfDerivedString {
TypeString, TypeNormalizedString, TypeToken, TypeLanguage,
TypeNMTOKEN, TypeName, TypeNCName, TypeID,
TypeIDREF, TypeENTITY
}
Functions
static void allowedIn (const QueryLanguages allowedLanguages, const ParserContext *const parseInfo, const YYLTYPE &sourceLocator, const bool isInternal=false)
Flags invalid expressions and declarations in the currently parsed language.
static void changeToTopAxis (const Expression::Ptr &op)
static void checkVariableCircularity (const VariableDeclaration::Ptr &var, const Expression::Ptr &checkee, const VariableDeclaration::Type type, FunctionSignature::List &signList, const ParserContext *const parseInfo)
Checks for variable initialization circularity.
static Expression::Ptr create (Expression *const expr, const YYLTYPE &sourceLocator, const ParserContext *const parseInfo)
static Template::Ptr create (Template *const expr, const YYLTYPE &sourceLocator, const ParserContext *const parseInfo)
static Expression::Ptr create (const Expression::Ptr &expr, const YYLTYPE &sourceLocator, const ParserContext *const parseInfo)
static Expression::Ptr createCompatStore (const Expression::Ptr &expr, const YYLTYPE &sourceLocator, const ParserContext *const parseInfo)
static Expression::Ptr createConcatFN (const ParserContext *const parseInfo, const Expression::List &args, const YYLTYPE &sourceLocator)
Creates a call to fn:concat() with args as the arguments.
static Expression::Ptr createCopyOf (const Expression::Ptr &operand, const ParserContext *const parseInfo, const YYLTYPE &sl)
static Expression::Ptr createDirAttributeValue (const Expression::List &content, const ParserContext *const parseInfo, const YYLTYPE &sourceLocator)
template<const bool isDouble>
Numeric::Ptr createFloat (const xsDouble num)
static Expression::Ptr createIdPatternPath (const Expression::Ptr &operand1, const Expression::Ptr &operand2, const QXmlNodeModelIndex::Axis axis, const YYLTYPE &sl, const ParserContext *const parseInfo)
Performs the same role as createPatternPath(), but is tailored for fn:key() and fn:id().
template<typename TNumberClass >
Expression::Ptr createNumericLiteral (const QString &in, const YYLTYPE &sl, const ParserContext *const parseInfo)
Centralizes code for creating numeric literals.
static Expression::Ptr createPatternPath (const Expression::Ptr &operand1, const Expression::Ptr &operand2, const QXmlNodeModelIndex::Axis axis, const YYLTYPE &sl, const ParserContext *const parseInfo)
Writes operand1 and operand2, two operands in an XSL-T pattern, into an equivalent XPath expression.
static Expression::Ptr createReturnOrderBy (const OrderSpecTransfer::List &orderSpecTransfer, const Expression::Ptr &returnExpr, const OrderBy::Stability stability, const YYLTYPE &sourceLocator, const ParserContext *const parseInfo)
static Expression::Ptr createRootExpression (const ParserContext *const parseInfo, const YYLTYPE &sl)
Creates an Expression that corresponds to /. This is literally fn:root(self::node()) treat as document-node().
static Expression::Ptr createSimpleContent (const Expression::Ptr &source, const YYLTYPE &sourceLocator, const ParserContext *const parseInfo)
static Expression::Ptr createSlashSlashPath (const Expression::Ptr &begin, const Expression::Ptr &end, const YYLTYPE &sourceLocator, const ParserContext *const parseInfo)
Creates a path expression which contains the step // between begin and and end.
QString Q_AUTOTEST_EXPORT escape (const QString &input)
Similar to Qt::escape(), but also escapes apostrophes and quotes, such that the result is suitable as attribute content too.
static Expression::Ptr findAxisStep (const Expression::Ptr &expr, const bool throughStructures=true)
static QString formatAttribute (const QString &attribute)
Formats attribute name.
static QString formatAttribute (const char *const attribute)
static QString formatData (const QString &data)
static QString formatData (const xsInteger data)
static QString formatData (const char *const data)
static QString formatData (const QLatin1Char &data)
static QString formatElement (const QString &element)
Formats element name.
static QString formatElement (const char *const element)
static QString formatExpression (const QString &expr)
static QString formatFunction (const NamePool::Ptr &np, const FunctionSignature::Ptr &func)
Formats FunctionSignature.
QString formatKeyword (const QString &keyword)
static QString formatKeyword (const QStringRef &keyword)
static QString formatKeyword (const char *const keyword)
static QString formatKeyword (const QChar keyword)
static QString formatResourcePath (const QUrl &uri)
Formats uri as a path to a resource, typically it's a filename or a URI.
template<typename T >
QString formatType (const NamePool::Ptr &np, const T &type)
Formats ItemType and SequenceType.
static QString formatType (const NamePool::Ptr &np, const QXmlName &name)
Formats name of any type.
static QString formatType (const Cardinality &type)
Formats Cardinality.
static QString formatURI (const NamePool::Ptr &np, const QXmlName::NamespaceCode &uri)
Formats uri, that's considered to be a URI, for display.
static QString formatURI (const QUrl &uri)
Formats uri for display.
static QString formatURI (const QString &uri)
Formats uri, that's considered to be a URI, for display.
static QSourceLocation fromYYLTYPE (const YYLTYPE &sourceLocator, const ParserContext *const parseInfo)
static bool isPredicate (const Expression::ID id)
static bool isVariableReference (const Expression::ID id)
static void loadPattern (const Expression::Ptr &matchPattern, TemplatePattern::Vector &ourPatterns, const TemplatePattern::ID id, const PatternPriority priority, const Template::Ptr &temp)
static ReturnOrderBy * locateReturnClause (const Expression::Ptr &expr)
template<typename T >
static QAbstractXmlForwardIterator< T >::Ptr makeEmptyIterator ()
template<typename T >
QAbstractXmlForwardIterator< T >::Ptr makeListIterator (const QList< T > &list)
template<typename T >
QAbstractXmlForwardIterator< T >::Ptr makeVectorIterator (const QVector< T > &vector)
static QXmlNodeModelIndex::NodeKind operator| (const QXmlNodeModelIndex::NodeKind &op1, const QXmlNodeModelIndex::NodeKind &op2)
QNoDebug pDebug ()
static QString prologMessage (const char *const msg)
Centralizes a translation message, for the purpose of consistency and modularization.
static Expression::Ptr pushVariable (const QXmlName name, const SequenceType::Ptr &seqType, const Expression::Ptr &expr, const VariableDeclaration::Type type, const YYLTYPE &sourceLocator, ParserContext *const parseInfo, const bool checkSource=true)
uint qHash (const QPatternist::TargetNode &node)
static SequenceType::Ptr quantificationType (const SequenceType::Ptr &type)
static void registerNamedTemplate (const QXmlName &name, const Expression::Ptr &body, ParserContext *const parseInfo, const YYLTYPE &sourceLocator, const Template::Ptr &temp)
template<const ReportContext::ErrorCode errorCode>
static QUrl resolveAndCheckCollation (const QString &collation, const ParserContext *const parseInfo, const YYLTYPE &sl)
Resolves against the static base URI and checks that collation is a supported Unicode Collation.
static Expression::Ptr resolveVariable (const QXmlName &name, const YYLTYPE &sourceLocator, ParserContext *const parseInfo, const bool raiseErrorOnUnavailability)
template<typename T >
Item toItem (const QExplicitlySharedDataPointer< T > atomicValue)
static Expression::Ptr typeCheckTemplateBody (const Expression::Ptr &body, const SequenceType::Ptr &reqType, const ParserContext *const parseInfo)
static QString unknownType ()
Centralizes a translation string for the purpose of increasing consistency.
static VariableDeclaration::Ptr variableByName (const QXmlName name, const ParserContext *const parseInfo)
static void variableUnavailable (const QXmlName &variableName, const ParserContext *const parseInfo, const YYLTYPE &location)
static int XPatherror (YYLTYPE *sourceLocator, const ParserContext *const parseInfo, const char *const msg)
The generated Bison parser calls this function when there is a parse error.
static int XPathlex (YYSTYPE *lexVal, YYLTYPE *sourceLocator, const ParserContext *const parseInfo)
int XPathparse (QPatternist::ParserContext *const info)
The entry point to the parser.
static void yydestruct (const char *yymsg, int yytype, YYSTYPE *yyvaluep, YYLTYPE *yylocationp, ParserContext *const parseInfo)
int yyparse (ParserContext *const parseInfo)
static char * yystpcpy (char *yydest, const char *yysrc)
static YYSIZE_T yystrlen (const char *yystr)
static YYSIZE_T yysyntax_error (char *yyresult, int yystate, int yychar)
static YYSIZE_T yytnamerr (char *yyres, const char *yystr)
Variables
static const MergeIterator mergeIterator
static const yytype_int16 yycheck []
static const yytype_uint16 yydefact []
static const yytype_int16 yydefgoto []
static const yytype_int16 yypact []
static const yytype_int16 yypgoto []
static const yytype_uint16 yyr1 []
static const yytype_uint8 yyr2 []
static const yytype_uint16 yystos []
static const yytype_int16 yytable []
static const char *const yytname []
static const yytype_uint8 yytranslate []
Detailed Description
The namespace for the internal API of QtXmlPatterns.
Warning
This function is not part of the public interface.
Typedef Documentation
AttributeHolder
typedef QPair<QString, Expression::Ptr> QPatternist::AttributeHolder
Definition at line 74 of file qtokenizer_p.h.
AttributeHolderVector
typedef QVector<AttributeHolder> QPatternist::AttributeHolderVector
Definition at line 75 of file qtokenizer_p.h.
BooleanToDoubleCaster
typedef BooleanToAbstractFloatCaster<true> QPatternist::BooleanToDoubleCaster
Casts a value of type xs:boolean to xs:double.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 160 of file qabstractfloatcasters_p.h.
BooleanToFloatCaster
typedef BooleanToAbstractFloatCaster<false> QPatternist::BooleanToFloatCaster
Casts a value of type xs:boolean to xs:float.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 168 of file qabstractfloatcasters_p.h.
ComponentLocationHash
typedef QHash<NamedSchemaComponent::Ptr, QSourceLocation> QPatternist::ComponentLocationHash
A hash that keeps the mapping between the single components that can appear in a schema document (e.g. elements, attributes, type definitions) and their source locations inside the document.
Definition at line 147 of file qxsdschemaparsercontext_p.h.
DayCountProperty
typedef qint32 QPatternist::DayCountProperty
Definition at line 141 of file qprimitives_p.h.
DayProperty
typedef qint8 QPatternist::DayProperty
Definition at line 149 of file qprimitives_p.h.
Double
typedef AbstractFloat<true> QPatternist::Double
An instantiation of AbsbstractFloat suitable for xs:double.
Definition at line 160 of file qabstractfloat_p.h.
DoubleMathematician
AllMathOperators AllMathOperators AtomicMathematician::Multiply AllMathOperators AllMathOperators AtomicMathematician::Multiply AllMathOperators AllMathOperators AtomicMathematician::Multiply DoubleMathematician
An instantiation of AbstractFloatMathematician that handles xs:double.
Definition at line 93 of file qabstractfloatmathematician_p.h.
Float
typedef AbstractFloat<false> QPatternist::Float
An instantiation of AbstractFloat suitable for xs:float.
Definition at line 167 of file qabstractfloat_p.h.
FloatMathematician
typedef AbstractFloatMathematician<false> QPatternist::FloatMathematician
An instantiation of AbstractFloatMathematician that handles xs:float.
Definition at line 98 of file qabstractfloatmathematician_p.h.
HourCountProperty
typedef qint32 QPatternist::HourCountProperty
Definition at line 142 of file qprimitives_p.h.
HourProperty
typedef qint8 QPatternist::HourProperty
Definition at line 150 of file qprimitives_p.h.
ImportPrecedence
typedef int QPatternist::ImportPrecedence
Signifies the import precedence of a template. For instance, the first stylesheet module has 1, the first import 2, and so forth. Smaller means higher import precedence. 0 is reserved for builtin templates.
Definition at line 183 of file qprimitives_p.h.
ItemIteratorPtr
typedef QExplicitlySharedDataPointer<QAbstractXmlForwardIterator<Item> > QPatternist::ItemIteratorPtr
Definition at line 78 of file qabstractxmlnodemodel.h.
ItemTypePtr
typedef QExplicitlySharedDataPointer<ItemType> QPatternist::ItemTypePtr
Definition at line 76 of file qabstractxmlnodemodel.h.
MaxFN
typedef ComparingAggregator<AtomicComparator::OperatorGreaterThan, AtomicComparator::GreaterThan> QPatternist::MaxFN
An instantiation of ComparingAggregator suitable for fn:max().
Definition at line 132 of file qcomparingaggregator_p.h.
MinFN
typedef ComparingAggregator<AtomicComparator::OperatorLessThan, AtomicComparator::LessThan> QPatternist::MinFN
An instantiation of ComparingAggregator suitable for fn:max().
Definition at line 139 of file qcomparingaggregator_p.h.
MinuteCountProperty
typedef qint32 QPatternist::MinuteCountProperty
Definition at line 143 of file qprimitives_p.h.
MinuteProperty
typedef qint8 QPatternist::MinuteProperty
Definition at line 151 of file qprimitives_p.h.
MonthCountProperty
typedef qint32 QPatternist::MonthCountProperty
Definition at line 144 of file qprimitives_p.h.
MonthProperty
typedef qint8 QPatternist::MonthProperty
Definition at line 152 of file qprimitives_p.h.
MSecondCountProperty
typedef qint64 QPatternist::MSecondCountProperty
Definition at line 146 of file qprimitives_p.h.
MSecondProperty
typedef qint16 QPatternist::MSecondProperty
Milliseconds. 1 equals 0.001 SecondProperty.
Definition at line 157 of file qprimitives_p.h.
NumericToDoubleCaster
typedef NumericToAbstractFloatCaster<true> QPatternist::NumericToDoubleCaster
Casts a numeric value, such as xs:integer or xs:float, to xs:double.
castFrom() uses Numeric::toDouble() for doing the actual casting.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 126 of file qabstractfloatcasters_p.h.
NumericToFloatCaster
typedef NumericToAbstractFloatCaster<false> QPatternist::NumericToFloatCaster
Casts a numeric value, such as xs:double or xs:decimal, to xs:float.
castFrom() uses Numeric::toFloat() for doing the actual casting.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 136 of file qabstractfloatcasters_p.h.
PatternPriority
typedef xsDouble QPatternist::PatternPriority
Definition at line 176 of file qprimitives_p.h.
QXmlNameVector
typedef QVector<QXmlName> QPatternist::QXmlNameVector
Definition at line 79 of file qabstractxmlnodemodel.h.
SecondCountProperty
typedef qint32 QPatternist::SecondCountProperty
Definition at line 145 of file qprimitives_p.h.
SecondProperty
typedef qint32 QPatternist::SecondProperty
Definition at line 147 of file qprimitives_p.h.
StackContext
typedef StackContextBase<DelegatingDynamicContext> QPatternist::StackContext
A DynamicContext that creates a new scope for variables.
This DynamicContext is used for recursive user function calls, for example.
Definition at line 129 of file qstackcontextbase_p.h.
StringToDoubleCaster
typedef StringToAbstractFloatCaster<true> QPatternist::StringToDoubleCaster
Casts a string value, xs:string or xs:untypedAtomic, to xs:double.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 144 of file qabstractfloatcasters_p.h.
StringToFloatCaster
typedef StringToAbstractFloatCaster<false> QPatternist::StringToFloatCaster
Casts a string value, xs:string or xs:untypedAtomic, to xs:float.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 152 of file qabstractfloatcasters_p.h.
YearProperty
typedef qint32 QPatternist::YearProperty
Definition at line 148 of file qprimitives_p.h.
yytype_int16
typedef short int QPatternist::yytype_int16
Definition at line 1372 of file qquerytransformparser.cpp.
yytype_int8
typedef signed char QPatternist::yytype_int8
Definition at line 1358 of file qquerytransformparser.cpp.
yytype_uint16
typedef unsigned short int QPatternist::yytype_uint16
Definition at line 1366 of file qquerytransformparser.cpp.
yytype_uint8
typedef unsigned char QPatternist::yytype_uint8
Definition at line 1351 of file qquerytransformparser.cpp.
ZOHourProperty
typedef qint8 QPatternist::ZOHourProperty
The hour property of a zone offset. For example, -13 in the zone offset "-13:08".
Definition at line 163 of file qprimitives_p.h.
ZOMinuteProperty
typedef qint8 QPatternist::ZOMinuteProperty
The minute property of a zone offset. For example, -08 in the zone offset "-13:08".
Definition at line 169 of file qprimitives_p.h.
ZOTotal
typedef qint32 QPatternist::ZOTotal
The full zone offset in minutes.
Definition at line 174 of file qprimitives_p.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IgnorableSignedValue
IgnorableUnsignedValue
Definition at line 77 of file qderivedinteger_p.h.
     {
         IgnorableSignedValue = 0,
         IgnorableUnsignedValue = 0
     };
DerivedIntegerLimitsUsage
template<TypeOfDerivedInteger DerivedType> enum DerivedIntegerLimitsUsage related
Definition at line 69 of file qderivedinteger_p.h.
     {
         None            = 1,
         LimitUpwards    = 2,
         LimitDownwards  = 4,
         LimitBoth       = LimitUpwards | LimitDownwards
     };
TypeOfDerivedInteger
enum QPatternist::TypeOfDerivedInteger
Enumerator
TypeByte
TypeInt
TypeLong
TypeNegativeInteger
TypeNonNegativeInteger
TypeNonPositiveInteger
TypePositiveInteger
TypeShort
TypeUnsignedByte
TypeUnsignedInt
TypeUnsignedLong
TypeUnsignedShort
Definition at line 90 of file qatomictypedispatch_p.h.
     {
         TypeByte,
         TypeInt,
         TypeLong,
         TypeNegativeInteger,
         TypeNonNegativeInteger,
         TypeNonPositiveInteger,
         TypePositiveInteger,
         TypeShort,
         TypeUnsignedByte,
         TypeUnsignedInt,
         TypeUnsignedLong,
         TypeUnsignedShort
     };
TypeOfDerivedString
enum QPatternist::TypeOfDerivedString
Enumerator
TypeString
TypeNormalizedString
TypeToken
TypeLanguage
TypeNMTOKEN
TypeName
TypeNCName
TypeID
TypeIDREF
TypeENTITY
Definition at line 108 of file qatomictypedispatch_p.h.
     {
         TypeString,
         TypeNormalizedString,
         TypeToken,
         TypeLanguage,
         TypeNMTOKEN,
         TypeName,
         TypeNCName,
         TypeID,
         TypeIDREF,
         TypeENTITY
     };
Function Documentation
allowedIn()
static void QPatternist::allowedIn (const QueryLanguages allowedLanguages, const ParserContext *const parseInfo, const YYLTYPE & sourceLocator, const bool isInternal = false) static
Flags invalid expressions and declarations in the currently parsed language.
Since this grammar is used for several languages: XQuery 1.0, XSL-T 2.0, and XPath 2.0 inside XSL-T, and field and selector patterns in W3C XML Schema's identity constraints, it is the union of all the constructs in these languages. However, when dealing with each language individually, we regularly need to disallow some expressions, such as direct element constructors when parsing XSL-T, or the typeswitch when parsing XPath.
This is further complicated by that XSLTTokenizer sometimes generates code which is allowed in XQuery but not in XPath. For that reason the token INTERNAL is sometimes generated, which signals that an expression, for instance the let clause, should not be flagged as an error, because it's used for internal purposes.
Hence, this function is called from each expression and declaration with allowedLanguages stating what languages it is allowed in.
If isInternal is true, no error is raised. Otherwise, if the current language is not in allowedLanguages, an error is raised.
Definition at line 270 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     /* We treat XPath 2.0 as a subset of XSL-T 2.0, so if XPath 2.0 is allowed
      * and XSL-T is the language, it's ok. */
     if(!isInternal &&
        (!allowedLanguages.testFlag(parseInfo->languageAccent) && !(allowedLanguages.testFlag(QXmlQuery::XPath20) && parseInfo->languageAccent == QXmlQuery::XSLT20)))
     {
         QString langName;
         switch(parseInfo->languageAccent)
         {
             case QXmlQuery::XPath20:
                 langName = QLatin1String("XPath 2.0");
                 break;
             case QXmlQuery::XSLT20:
                 langName = QLatin1String("XSL-T 2.0");
                 break;
             case QXmlQuery::XQuery10:
                 langName = QLatin1String("XQuery 1.0");
                 break;
             case QXmlQuery::XmlSchema11IdentityConstraintSelector:
                 langName = QtXmlPatterns::tr("W3C XML Schema identity constraint selector");
                 break;
             case QXmlQuery::XmlSchema11IdentityConstraintField:
                 langName = QtXmlPatterns::tr("W3C XML Schema identity constraint field");
                 break;
         }
         parseInfo->staticContext->error(QtXmlPatterns::tr("A construct was encountered "
                                                           "which is disallowed in the current language(%1).").arg(langName),
                                         ReportContext::XPST0003,
                                         fromYYLTYPE(sourceLocator, parseInfo));
     }
 }
changeToTopAxis()
static void QPatternist::changeToTopAxis (const Expression::Ptr & op) static
Definition at line 530 of file qquerytransformparser.cpp.
Referenced by createIdPatternPath().
 {
     /* This axis must have been written away by now. */
     Q_ASSERT(op->as<AxisStep>()->axis() != QXmlNodeModelIndex::AxisChild);
     if(op->as<AxisStep>()->axis() != QXmlNodeModelIndex::AxisSelf)
         op->as<AxisStep>()->setAxis(QXmlNodeModelIndex::AxisAttributeOrTop);
 }
checkVariableCircularity()
static void QPatternist::checkVariableCircularity (const VariableDeclaration::Ptr & var, const Expression::Ptr & checkee, const VariableDeclaration::Type type, FunctionSignature::List & signList, const ParserContext *const parseInfo) static
Checks for variable initialization circularity.
"A recursive function that checks for recursion is full of ironies."
 -- The Salsa Master
Issues an error via parseInfo's StaticContext if the initialization expression checkee for the global variable var, contains a variable reference to var. That is, if there's a circularity.
See also
XQuery 1.0: An XML Query Language, err:XQST0054
Definition at line 803 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     Q_ASSERT(var);
     Q_ASSERT(checkee);
     Q_ASSERT(parseInfo);
     const Expression::ID id = checkee->id();
     if(id == Expression::IDExpressionVariableReference)
     {
         const ExpressionVariableReference *const ref =
                     static_cast<const ExpressionVariableReference *>(checkee.data());
         if(var->slot == ref->slot() && type == ref->variableDeclaration()->type)
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("The initialization of variable %1 "
                                                               "depends on itself").arg(formatKeyword(var, parseInfo->staticContext->namePool())),
                                             parseInfo->isXSLT() ? ReportContext::XTDE0640 : ReportContext::XQST0054, ref);
             return;
         }
         else
         {
             /* If the variable we're checking is below another variable, it can be a recursive
              * dependency through functions, so we need to check variable references too. */
             checkVariableCircularity(var, ref->sourceExpression(), type, signList, parseInfo);
             return;
         }
     }
     else if(id == Expression::IDUserFunctionCallsite)
     {
         const UserFunctionCallsite::Ptr callsite(checkee);
         const FunctionSignature::Ptr sign(callsite->callTargetDescription());
         const FunctionSignature::List::const_iterator end(signList.constEnd());
         FunctionSignature::List::const_iterator it(signList.constBegin());
         bool noMatch = true;
         for(; it != end; ++it)
         {
             if(*it == sign)
             {
                 /* The variable we're checking is depending on a function that's recursive. The
                  * user has written a weird query, in other words. Since it's the second time
                  * we've encountered a callsite, we now skip it. */
                 noMatch = false;
                 break;
             }
         }
         if(noMatch)
         {
             signList.append(sign);
             /* Check the body of the function being called. */
             checkVariableCircularity(var, callsite->body(), type, signList, parseInfo);
         }
         /* Continue with the operands, such that we also check the arguments of the callsite. */
     }
     else if(id == Expression::IDUnresolvedVariableReference)
     {
         /* We're called before it has rewritten itself. */
         checkVariableCircularity(var, checkee->as<UnresolvedVariableReference>()->replacement(), type, signList, parseInfo);
     }
     /* Check the operands. */
     const Expression::List ops(checkee->operands());
     if(ops.isEmpty())
         return;
     const Expression::List::const_iterator end(ops.constEnd());
     Expression::List::const_iterator it(ops.constBegin());
     for(; it != end; ++it)
         checkVariableCircularity(var, *it, type, signList, parseInfo);
 }
create() [1/3]
static Expression::Ptr QPatternist::create (Expression *const expr, const YYLTYPE & sourceLocator, const ParserContext *const parseInfo) inline static
Definition at line 355 of file qquerytransformparser.cpp.
Referenced by QPixmapData::cacheKey(), createCompatStore(), createConcatFN(), createCopyOf(), createDirAttributeValue(), createIdPatternPath(), createNumericLiteral(), createPatternPath(), createReturnOrderBy(), createRootExpression(), createSimpleContent(), createSlashSlashPath(), QScriptStaticScopeObject::createStructure(), QScriptObject::createStructure(), QScript::QMetaObjectWrapperObject::createStructure(), effectiveState(), QScriptEngine::evaluate(), QScriptProgramPrivate::executable(), QImage::format(), QImage::fromData(), QScriptEngine::fromScriptValue(), QDeclarativeCompiler::genComponent(), QDeclarativeCompiler::genObject(), QScriptEnginePrivate::get(), QWSDisplay::Data::init(), QWSDisplay::instance(), QScriptEnginePrivate::jscValueFromVariant(), QScriptEnginePrivate::pushContext(), pushVariable(), QLock::QLock(), qmlAttachedPropertiesObject(), qmlRegisterCustomType(), QScriptEnginePrivate::QScriptEnginePrivate(), QMacPinchGestureRecognizer::reset(), resolveVariable(), QWidget::setShown(), QVariant::swap(), QWSDisplay::Data::takeId(), QPatternist::ComparingAggregator< oper, result >::typeCheck(), and yyparse().
 {
     parseInfo->staticContext->addLocation(expr, fromYYLTYPE(sourceLocator, parseInfo));
     return Expression::Ptr(expr);
 }
create() [2/3]
static Template::Ptr QPatternist::create (Template *const expr, const YYLTYPE & sourceLocator, const ParserContext *const parseInfo) inline static
Definition at line 363 of file qquerytransformparser.cpp.
 {
     parseInfo->staticContext->addLocation(expr, fromYYLTYPE(sourceLocator, parseInfo));
     return Template::Ptr(expr);
 }
create() [3/3]
static Expression::Ptr QPatternist::create (const Expression::Ptr & expr, const YYLTYPE & sourceLocator, const ParserContext *const parseInfo) inline static
Definition at line 371 of file qquerytransformparser.cpp.
 {
     parseInfo->staticContext->addLocation(expr.data(), fromYYLTYPE(sourceLocator, parseInfo));
     return expr;
 }
createCompatStore()
static Expression::Ptr QPatternist::createCompatStore (const Expression::Ptr & expr, const YYLTYPE & sourceLocator, const ParserContext *const parseInfo) static
Definition at line 691 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     return create(new StaticCompatibilityStore(expr), sourceLocator, parseInfo);
 }
createConcatFN()
static Expression::Ptr QPatternist::createConcatFN (const ParserContext *const parseInfo, const Expression::List & args, const YYLTYPE & sourceLocator) inline static
Creates a call to fn:concat() with args as the arguments.
Definition at line 765 of file qquerytransformparser.cpp.
Referenced by createDirAttributeValue().
 {
     Q_ASSERT(parseInfo);
     const QXmlName name(StandardNamespaces::fn, StandardLocalNames::concat);
     const ReflectYYLTYPE ryy(sourceLocator, parseInfo);
     return create(parseInfo->staticContext->functionSignatures()->createFunctionCall(name, args, parseInfo->staticContext, &ryy),
                   sourceLocator, parseInfo);
 }
createCopyOf()
static Expression::Ptr QPatternist::createCopyOf (const Expression::Ptr & operand, const ParserContext *const parseInfo, const YYLTYPE & sl) static
Wraps operand with a CopyOf in case it makes any difference.
There is no need to wrap the return value in a call to create(), it's already done.
Definition at line 683 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     return create(new CopyOf(operand, parseInfo->inheritNamespacesMode,
                              parseInfo->preserveNamespacesMode), sl, parseInfo);
 }
createDirAttributeValue()
static Expression::Ptr QPatternist::createDirAttributeValue (const Expression::List & content, const ParserContext *const parseInfo, const YYLTYPE & sourceLocator) inline static
Definition at line 777 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     if(content.isEmpty())
         return create(new EmptySequence(), sourceLocator, parseInfo);
     else if(content.size() == 1)
         return content.first();
     else
         return createConcatFN(parseInfo, content, sourceLocator);
 }
createFloat()
template<const bool isDouble> Numeric::Ptr QPatternist::createFloat (const xsDouble num)
createIdPatternPath()
static Expression::Ptr QPatternist::createIdPatternPath (const Expression::Ptr & operand1, const Expression::Ptr & operand2, const QXmlNodeModelIndex::Axis axis, const YYLTYPE & sl, const ParserContext *const parseInfo) inline static
Performs the same role as createPatternPath(), but is tailored for fn:key() and fn:id().
fn:key() and fn:id() can be part of path patterns(only as the first step, to be precise) and that poses a challenge to rewriting because what createPatternPath() is not possible to express, since the functions cannot be node tests. E.g, this rewrite is not possible:
id-or-key/abc => child-or-top::abc[parent::id-or-key]
Our approach is to rewrite like this:
id-or-key/abc => child-or-top::abc[parent::node is id-or-key]
operand1 is the call to fn:key() or fn:id(), operand2 the right operand, and axis the target axis to rewrite to.
See also
createPatternPath()
Definition at line 604 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     const Expression::Ptr operandR(findAxisStep(operand2));
     Q_ASSERT(operandR);
     changeToTopAxis(operandR);
     const Expression::Ptr parentStep(create(new AxisStep(axis, BuiltinTypes::node),
                                             sl,
                                             parseInfo));
     const Expression::Ptr isComp(create(new NodeComparison(parentStep,
                                                            QXmlNodeModelIndex::Is,
                                                            operand1),
                                          sl,
                                          parseInfo));
     return create(GenericPredicate::create(operandR, isComp,
                                            parseInfo->staticContext, fromYYLTYPE(sl, parseInfo)), sl, parseInfo);
 }
createNumericLiteral()
template<typename TNumberClass > Expression::Ptr QPatternist::createNumericLiteral (const QString & in, const YYLTYPE & sl, const ParserContext *const parseInfo)
Centralizes code for creating numeric literals.
Definition at line 439 of file qquerytransformparser.cpp.
 {
     const Item num(TNumberClass::fromLexical(in));
     if(num.template as<AtomicValue>()->hasError())
     {
         parseInfo->staticContext->error(QtXmlPatterns::tr("%1 is not a valid numeric literal.")
                                            .arg(formatData(in)),
                                         ReportContext::XPST0003, fromYYLTYPE(sl, parseInfo));
         return Expression::Ptr(); /* Avoid compiler warning. */
     }
     else
         return create(new Literal(num), sl, parseInfo);
 }
createPatternPath()
static Expression::Ptr QPatternist::createPatternPath (const Expression::Ptr & operand1, const Expression::Ptr & operand2, const QXmlNodeModelIndex::Axis axis, const YYLTYPE & sl, const ParserContext *const parseInfo) inline static
Writes operand1 and operand2, two operands in an XSL-T pattern, into an equivalent XPath expression.
Essentially, the following rewrite is done:
axis1::test1(a)/axis2::test2(b) => child-or-top::test2(b)[parent::test1(a)]
Section 5.5.3 The Meaning of a Pattern talks about rewrites that are applied to only the first step in a pattern, but since we're doing rewrites more radically, its line of reasoning cannot be followed.
Keep in mind the rewrites that non-terminal PatternStep do.
See also
createIdPatternPath()
Definition at line 559 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     const Expression::Ptr operandL(findAxisStep(operand1, false));
     if(operandL->is(Expression::IDAxisStep))
         operandL->as<AxisStep>()->setAxis(axis);
     else
         findAxisStep(operand1)->as<AxisStep>()->setAxis(axis);
     return create(GenericPredicate::create(operand2, operandL,
                                            parseInfo->staticContext, fromYYLTYPE(sl, parseInfo)), sl, parseInfo);
 }
createReturnOrderBy()
static Expression::Ptr QPatternist::createReturnOrderBy (const OrderSpecTransfer::List & orderSpecTransfer, const Expression::Ptr & returnExpr, const OrderBy::Stability stability, const YYLTYPE & sourceLocator, const ParserContext *const parseInfo) static
Definition at line 1097 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     // TODO do resize(orderSpec.size() + 1)
     Expression::List exprs;
     OrderBy::OrderSpec::Vector orderSpecs;
     exprs.append(returnExpr);
     const int len = orderSpecTransfer.size();
     for(int i = 0; i < len; ++i)
     {
         exprs.append(orderSpecTransfer.at(i).expression);
         orderSpecs.append(orderSpecTransfer.at(i).orderSpec);
     }
     return create(new ReturnOrderBy(stability, orderSpecs, exprs), sourceLocator, parseInfo);
 }
createRootExpression()
static Expression::Ptr QPatternist::createRootExpression (const ParserContext *const parseInfo, const YYLTYPE & sl) static
Creates an Expression that corresponds to /. This is literally fn:root(self::node()) treat as document-node().
Definition at line 702 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     Q_ASSERT(parseInfo);
     const QXmlName name(StandardNamespaces::fn, StandardLocalNames::root);
     Expression::List args;
     args.append(create(new ContextItem(), sl, parseInfo));
     const ReflectYYLTYPE ryy(sl, parseInfo);
     const Expression::Ptr fnRoot(parseInfo->staticContext->functionSignatures()
                                  ->createFunctionCall(name, args, parseInfo->staticContext, &ryy));
     Q_ASSERT(fnRoot);
     return create(new TreatAs(create(fnRoot, sl, parseInfo), CommonSequenceTypes::ExactlyOneDocumentNode), sl, parseInfo);
 }
createSimpleContent()
static Expression::Ptr QPatternist::createSimpleContent (const Expression::Ptr & source, const YYLTYPE & sourceLocator, const ParserContext *const parseInfo) static
Definition at line 379 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     return create(parseInfo->isXSLT() ? new XSLTSimpleContentConstructor(source) : new SimpleContentConstructor(source),
                   sourceLocator,
                   parseInfo);
 }
createSlashSlashPath()
static Expression::Ptr QPatternist::createSlashSlashPath (const Expression::Ptr & begin, const Expression::Ptr & end, const YYLTYPE & sourceLocator, const ParserContext *const parseInfo) static
Creates a path expression which contains the step // between begin and and end.
begin//end is a short form for: begin/descendant-or-self::node()/end
This will be compiled as two-path expression: (/)/(//.)/step/
Definition at line 751 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     const Expression::Ptr twoSlash(create(new AxisStep(QXmlNodeModelIndex::AxisDescendantOrSelf, BuiltinTypes::node), sourceLocator, parseInfo));
     const Expression::Ptr p1(create(new Path(begin, twoSlash), sourceLocator, parseInfo));
     return create(new Path(p1, end), sourceLocator, parseInfo);
 }
escape()
QString QPatternist::escape (const QString & input)
Similar to Qt::escape(), but also escapes apostrophes and quotes, such that the result is suitable as attribute content too.
Converts the plain text string plain to a HTML string with HTML metacharacters <, >, &, and " replaced by HTML entities.
Since Qt::escape() is in QtGui, using it creates a dependency on that library. This function does not.
The implementation resides in qpatternistlocale.cpp.
See also
Qt::escape()
Definition at line 48 of file qpatternistlocale.cpp.
Referenced by QPatternist::XSLTTokenizer::checkForParseError(), QSvgPaintEngine::drawTextItem(), QTextHtmlExporter::emitAttribute(), QTextHtmlExporter::emitFontFamily(), QTextHtmlExporter::emitFragment(), findArgEscapes(), formatData(), formatExpression(), formatFunction(), formatKeyword(), QXmlName::formatKeyword(), formatResourcePath(), formatType(), formatURI(), getEscape(), QPatternist::AccelTreeResourceLoader::load(), QScriptErrorLogWidget::message(), QRegExp::operator!=(), QLineControl::parseInputMask(), replaceArgEscapes(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), QPatternist::XSLTTokenizer::unexpectedContent(), and XPatherror().
     {
         QString rich;
         rich.reserve(int(input.length() * 1.1));
         for(int i = 0; i < input.length(); ++i)
         {
             switch(input.at(i).unicode())
             {
                 case '<':
                 {
                     rich += QLatin1String("&lt;");
                     break;
                 }
                 case '>':
                 {
                     rich += QLatin1String("&gt;");
                     break;
                 }
                 case '&':
                 {
                     rich += QLatin1String("&amp;");
                     break;
                 }
                 case '"':
                 {
                     rich += QLatin1String("&quot;");
                     break;
                 }
                 case '\'':
                 {
                     rich += QLatin1String("&apos;");
                     break;
                 }
                 default:
                     rich += input.at(i);
             }
         }
         return rich;
     }
findAxisStep()
static Expression::Ptr QPatternist::findAxisStep (const Expression::Ptr & expr, const bool throughStructures = true) static
Assumes expr is an AxisStep wrapped in some kind of predicates or paths. Filters through the predicates and returns the AxisStep.
Definition at line 498 of file qquerytransformparser.cpp.
Referenced by createIdPatternPath(), createPatternPath(), and yyparse().
 {
     Q_ASSERT(expr);
     if(!throughStructures)
         return expr;
     Expression *candidate = expr.data();
     Expression::ID id = candidate->id();
     while(isPredicate(id) || id == Expression::IDPath)
     {
         const Expression::List &children = candidate->operands();
         if(children.isEmpty())
             return Expression::Ptr();
         else
         {
             candidate = children.first().data();
             id = candidate->id();
         }
     }
     if(id == Expression::IDEmptySequence)
         return Expression::Ptr();
     else
     {
         Q_ASSERT(candidate->is(Expression::IDAxisStep));
         return Expression::Ptr(candidate);
     }
 }
formatAttribute() [1/2]
static QString QPatternist::formatAttribute (const QString & attribute) inline static
Formats attribute name.
Definition at line 139 of file qpatternistlocale_p.h.
Referenced by QPatternist::XsdSchemaParser::addAttribute(), QPatternist::XsdSchemaParser::attributeContentError(), QPatternist::XsdSchemaChecker::checkAttributeUseConstraints(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), formatAttribute(), QPatternist::XsdSchemaHelper::isValidAttributeUsesRestriction(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseMinMaxConstraint(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaParser::readBlockingConstraintAttribute(), QPatternist::XsdSchemaParser::readDerivationConstraintAttribute(), QPatternist::XsdSchemaResolver::resolveAttributeInheritance(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), and QPatternist::XsdSchemaResolver::resolveTermReference().
     {
         // for the moment we forward to formatKeyword, that will change later
         return formatKeyword(attribute);
     }
formatAttribute() [2/2]
static QString QPatternist::formatAttribute (const char *const attribute) inline static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 148 of file qpatternistlocale_p.h.
     {
         return formatAttribute(QLatin1String(attribute));
     }
formatData() [1/4]
static QString QPatternist::formatData (const QString & data) inline static
Definition at line 228 of file qpatternistlocale_p.h.
Referenced by QPatternist::AccelTreeBuilder< true >::attribute(), QPatternist::XsdSchemaParser::attributeContentError(), QPatternist::DurationNumericMathematician::calculate(), QPatternist::NumericToDecimalCaster< IsInteger >::castFrom(), QPatternist::NumericToDerivedIntegerCaster< type >::castFrom(), QPatternist::XsdSchemaChecker::checkAttributeUseConstraints(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdTypeChecker::checkConstrainingFacetsQName(), QPatternist::XsdSchemaResolver::checkRedefinedAttributeGroups(), QPatternist::XsdSchemaResolver::checkRedefinedGroups(), QPatternist::ContextNodeChecker::checkTargetNode(), QPatternist::AbstractDateTime::create(), createNumericLiteral(), QPatternist::ProcessingInstructionConstructor::data(), divZeroInvalid(), QPatternist::DerivedString< TypeToken >::error(), QPatternist::CommentConstructor::evaluateContent(), QPatternist::DateTimeFN::evaluateSingleton(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::CodepointsToStringFN::evaluateSingleton(), QPatternist::AdjustTimezone::evaluateSingleton(), QPatternist::QNameConstructor::expandQName(), formatData(), QPatternist::HexBinary::fromLexical(), QPatternist::DerivedInteger< DerivedType >::fromValue(), QPatternist::XSLTTokenizer::handleXSLTVersion(), idivZeroInvalid(), QPatternist::XsdTypeChecker::isValidString(), modZeroInvalid(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdValidatingInstanceReader::qNameAttribute(), QPatternist::XSLTTokenizer::readAlternativeAttribute(), QPatternist::XsdSchemaParser::readBlockingConstraintAttribute(), QPatternist::XsdSchemaParser::readDerivationConstraintAttribute(), QPatternist::XSLTTokenizer::readToggleAttribute(), QPatternist::XsdSchemaResolver::resolveAttributeInheritance(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), QPatternist::XsdSchemaResolver::resolveTermReference(), QPatternist::AccelTreeResourceLoader::retrieveUnparsedText(), QPatternist::XsdValidatingInstanceReader::selectNodeSets(), QPatternist::XsdValidatingInstanceReader::validateElement(), QPatternist::XsdSchemaParser::validateIdAttribute(), QPatternist::ItemVerifier::verifyItem(), and yyparse().
     {
         return QLatin1String("<span class='XQuery-data'>")  +
                escape(data)                                 +
                QLatin1String("</span>");
     }
formatData() [2/4]
static QString QPatternist::formatData (const xsInteger data) inline static
This is an overload, provided for convenience.
Definition at line 238 of file qpatternistlocale_p.h.
     {
         return formatData(QString::number(data));
     }
formatData() [3/4]
static QString QPatternist::formatData (const char *const data) inline static
This is an overload, provided for convenience.
Definition at line 246 of file qpatternistlocale_p.h.
     {
         return formatData(QLatin1String(data));
     }
formatData() [4/4]
static QString QPatternist::formatData (const QLatin1Char & data) inline static
This is an overload, provided for convenience.
Definition at line 254 of file qpatternistlocale_p.h.
     {
         return formatData(QString(data));
     }
formatElement() [1/2]
static QString QPatternist::formatElement (const QString & element) inline static
Formats element name.
Definition at line 122 of file qpatternistlocale_p.h.
Referenced by QPatternist::XsdSchemaParser::addElement(), QPatternist::XsdSchemaParser::attributeContentError(), QPatternist::XsdSchemaResolver::checkRedefinedAttributeGroups(), QPatternist::XsdSchemaResolver::checkRedefinedGroups(), QPatternist::TagValidationHandler::finalize(), formatElement(), QPatternist::XsdSchemaHelper::isValidAttributeUsesExtension(), QPatternist::XsdSchemaHelper::isValidAttributeUsesRestriction(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseMinMaxConstraint(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaParser::parseUnknown(), QPatternist::XsdSchemaParser::readBlockingConstraintAttribute(), QPatternist::XsdSchemaParser::readDerivationConstraintAttribute(), QPatternist::XsdSchemaResolver::resolveAlternativeTypes(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveAttributeTypes(), QPatternist::XsdSchemaResolver::resolveComplexBaseTypes(), QPatternist::XsdSchemaResolver::resolveElementTypes(), QPatternist::XsdSchemaResolver::resolveKeyReferences(), QPatternist::XsdSchemaResolver::resolveSimpleListType(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictionBaseTypes(), QPatternist::XsdSchemaResolver::resolveSimpleUnionTypes(), QPatternist::XsdSchemaResolver::resolveSubstitutionGroupAffiliations(), QPatternist::XsdSchemaResolver::resolveTermReference(), and QPatternist::TagValidationHandler::validate().
     {
         // for the moment we forward to formatKeyword, that will change later
         return formatKeyword(element);
     }
formatElement() [2/2]
static QString QPatternist::formatElement (const char *const element) inline static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 131 of file qpatternistlocale_p.h.
     {
         return formatElement(QLatin1String(element));
     }
formatExpression()
static QString QPatternist::formatExpression (const QString & expr) inline static
Formats an arbitrary expression, such as a regular expression or XQuery query.
Definition at line 263 of file qpatternistlocale_p.h.
Referenced by QPatternist::PatternPlatform::parsePattern(), and yyparse().
     {
         return QLatin1String("<span class='XQuery-expression'>")    +
                escape(expr)                                         +
                QLatin1String("</span>");
     }
formatFunction()
static QString QPatternist::formatFunction (const NamePool::Ptr & np, const FunctionSignature::Ptr & func) inline static
Formats FunctionSignature.
Definition at line 201 of file qfunctionsignature_p.h.
Referenced by QPatternist::ContextNodeChecker::checkTargetNode(), QPatternist::ErrorFN::evaluateSingleton(), QPatternist::ComparingAggregator< oper, result >::typeCheck(), QPatternist::AddingAggregate::typeCheck(), QPatternist::SumFN::typeCheck(), QPatternist::AbstractFunctionFactory::verifyArity(), and yyparse().
     {
         return QLatin1String("<span class='XQuery-function'>")  +
                escape(func->displayName(np))                    +
                QLatin1String("</span>");
     }
formatKeyword() [1/4]
QString QPatternist::formatKeyword (const QString & keyword) inline
Definition at line 94 of file qpatternistlocale_p.h.
Referenced by QPatternist::XsdSchemaParser::addAttributeGroup(), QPatternist::XsdSchemaParser::addElementGroup(), QPatternist::XsdSchemaParser::addIdentityConstraint(), QPatternist::XsdValidatingInstanceReader::addIdIdRefBinding(), QPatternist::XsdSchemaParser::addNotation(), QXmlSerializer::attribute(), QPatternist::DocumentContentValidator::attribute(), QPatternist::OutputValidator::attribute(), QPatternist::AccelTreeBuilder< true >::attribute(), QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaChecker::checkAttributeUseConstraints(), QPatternist::XsdSchemaChecker::checkComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdSchemaChecker::checkDuplicatedAttributeUses(), QPatternist::XsdSchemaChecker::checkElementConstraints(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), checkVariableCircularity(), QPatternist::XsdSchemaParser::convertName(), QPatternist::AbstractDuration::create(), QPatternist::Template::createContext(), QPatternist::ExpressionFactory::createExpression(), derivedTermValid(), QPatternist::NormalizeUnicodeFN::determineNormalizationForm(), divZeroInvalid(), QPatternist::ReplaceFN::errorAtEnd(), QPatternist::AttributeNameValidator::evaluateSingleton(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::ComputedNamespaceConstructor::evaluateToSequenceReceiver(), QPatternist::QNameConstructor::expandQName(), QPatternist::ArithmeticExpression::fetchMathematician(), QPatternist::ParserContext::finalizePushedVariable(), flagDescriptions(), formatAttribute(), formatElement(), formatKeyword(), QPatternist::XSLTTokenizer::handleStandardAttributes(), QPatternist::XSLTTokenizer::handleValidationAttributes(), idivZeroInvalid(), QPatternist::XSLTTokenizer::insideChoose(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), QPatternist::XSLTTokenizer::insideStylesheetModule(), QPatternist::XSLTTokenizer::insideTemplate(), QPatternist::XsdSchemaHelper::isValidAttributeUsesExtension(), QPatternist::XsdSchemaHelper::isValidAttributeUsesRestriction(), modZeroInvalid(), QPatternist::NCNameConstructor::nameIsXML(), QPatternist::QNameConstructor::namespaceForPrefix(), QPatternist::XSLTTokenizer::outsideDocumentElement(), QPatternist::PatternPlatform::parseFlags(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::ReplaceFN::parseReplacement(), prologMessage(), QPatternist::XSLTTokenizer::queueParams(), QPatternist::XSLTTokenizer::queueSelectOrSequenceConstructor(), QPatternist::XSLTTokenizer::queueSorting(), QPatternist::XSLTTokenizer::queueVariableDeclaration(), QPatternist::Template::raiseXTSE0680(), QPatternist::XsdValidatingInstanceReader::read(), QPatternist::XSLTTokenizer::readAlternativeAttribute(), QPatternist::XSLTTokenizer::readToggleAttribute(), registerNamedTemplate(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveKeyReferences(), QPatternist::XsdSchemaResolver::resolveSubstitutionGroupAffiliations(), QPatternist::XsdSchemaResolver::resolveTermReference(), QPatternist::XSLTTokenizer::skipBodyOfParam(), QXmlSerializer::startElement(), QPatternist::XSLTTokenizer::unexpectedContent(), QPatternist::XsdValidatingInstanceReader::validate(), QPatternist::XsdValidatingInstanceReader::validateAttribute(), QPatternist::XsdValidatingInstanceReader::validateElement(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), QPatternist::XsdValidatingInstanceReader::validateElementSimpleType(), QPatternist::XsdValidatingInstanceReader::validateKeyIdentityConstraint(), QPatternist::XsdValidatingInstanceReader::validateKeyRefIdentityConstraint(), QPatternist::NCNameConstructor::validateTargetName(), QPatternist::XsdValidatingInstanceReader::validateUniqueIdentityConstraint(), variableUnavailable(), and yyparse().
     {
         return QLatin1String("<span class='XQuery-keyword'>")   +
                escape(keyword)                                  +
                QLatin1String("</span>");
     }
formatKeyword() [2/4]
static QString QPatternist::formatKeyword (const QStringRef & keyword) inline static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 104 of file qpatternistlocale_p.h.
     {
         return formatKeyword(keyword.toString());
     }
formatKeyword() [3/4]
static QString QPatternist::formatKeyword (const char *const keyword) inline static
Definition at line 109 of file qpatternistlocale_p.h.
     {
         return formatKeyword(QLatin1String(keyword));
     }
formatKeyword() [4/4]
static QString QPatternist::formatKeyword (const QChar keyword) inline static
Definition at line 114 of file qpatternistlocale_p.h.
     {
         return formatKeyword(QString(keyword));
     }
formatResourcePath()
static QString QPatternist::formatResourcePath (const QUrl & uri) inline static
Formats uri as a path to a resource, typically it's a filename or a URI.
Definition at line 192 of file qpatternistlocale_p.h.
Referenced by QPatternist::CollectionFN::evaluateSequence().
     {
         const QString normalizedURI(escape(uri.toString(QUrl::RemovePassword)));
         return QLatin1String("<span class='XQuery-filepath'><a href='") +
                normalizedURI                                            +
                QLatin1String("'>")                                      +
                normalizedURI                                            +
                QLatin1String("</a></span>");
     }
formatType() [1/3]
template<typename T > QString QPatternist::formatType (const NamePool::Ptr & np, const T & type) inline
Formats ItemType and SequenceType.
This function is not declared static, because the compiler on target aix-xlc-64 won't accept it.
Definition at line 160 of file qpatternistlocale_p.h.
Referenced by QPatternist::XsdSchemaParser::addFacet(), QPatternist::XsdSchemaParser::addType(), QPatternist::AccelTreeBuilder< true >::attribute(), QPatternist::XsdSchemaParser::attributeContentError(), QPatternist::DurationNumericMathematician::calculate(), QPatternist::NumericToDecimalCaster< IsInteger >::castFrom(), QPatternist::NumericToDerivedIntegerCaster< type >::castFrom(), QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaChecker::checkBasicCircularInheritances(), QPatternist::XsdSchemaChecker::checkBasicComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkBasicSimpleTypeConstraints(), QPatternist::XsdSchemaChecker::checkCircularInheritances(), QPatternist::XsdSchemaChecker::checkComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdSchemaChecker::checkDuplicatedAttributeUses(), QPatternist::XsdSchemaChecker::checkElementConstraints(), QPatternist::XsdSchemaChecker::checkInheritanceRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleDerivationRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), QPatternist::CastingPlatform< UntypedAtomicConverter, true >::checkTargetType(), QPatternist::GenericPredicate::create(), QPatternist::DerivedString< TypeToken >::error(), QPatternist::AtomicValue::evaluateEBV(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::CastAs::evaluateSingleton(), QPatternist::ComputedNamespaceConstructor::evaluateToSequenceReceiver(), QPatternist::QNameConstructor::expandQName(), QPatternist::ComparisonPlatform< IndexOfIterator, false >::fetchComparator(), QPatternist::ArithmeticExpression::fetchMathematician(), QPatternist::HexBinary::fromLexical(), QPatternist::XsdTypeChecker::fromLexical(), QPatternist::DerivedInteger< DerivedType >::fromValue(), QPatternist::XSLTTokenizer::handleXSLTVersion(), QPatternist::CastingPlatform< UntypedAtomicConverter, true >::issueCastError(), QPatternist::XsdTypeChecker::isValidString(), QPatternist::CastingPlatform< UntypedAtomicConverter, true >::locateCaster(), QPatternist::TraceCallback::mapToItem(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::TypeChecker::promotionPossible(), QPatternist::XsdSchemaResolver::resolveAlternativeTypes(), QPatternist::XsdSchemaResolver::resolveAttributeInheritance(), QPatternist::XsdSchemaResolver::resolveAttributeTypes(), QPatternist::XsdSchemaResolver::resolveComplexBaseTypes(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveElementTypes(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), QPatternist::XsdSchemaResolver::resolveSimpleListType(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictionBaseTypes(), QPatternist::XsdSchemaResolver::resolveSimpleUnionTypes(), QPatternist::AnyURI::toQUrl(), QPatternist::ComparingAggregator< oper, result >::typeCheck(), QPatternist::AddingAggregate::typeCheck(), QPatternist::CastAs::typeCheck(), QPatternist::AvgFN::typeCheck(), QPatternist::SumFN::typeCheck(), QPatternist::XsdValidatingInstanceReader::validate(), QPatternist::XsdValidatingInstanceReader::validateElement(), QPatternist::XsdValidatingInstanceReader::validateElementType(), QPatternist::NCNameConstructor::validateTargetName(), QPatternist::ItemVerifier::verifyItem(), QPatternist::CardinalityVerifier::wrongCardinality(), QPatternist::TypeChecker::wrongType(), and yyparse().
     {
         Q_ASSERT(type);
         return QLatin1String("<span class='XQuery-type'>")  +
                escape(type->displayName(np))                +
                QLatin1String("</span>");
     }
formatType() [2/3]
static QString QPatternist::formatType (const NamePool::Ptr & np, const QXmlName & name) inline static
Formats name of any type.
Definition at line 171 of file qpatternistlocale_p.h.
     {
         return QLatin1String("<span class='XQuery-type'>")  +
                escape(np->displayName(name))                +
                QLatin1String("</span>");
     }
formatType() [3/3]
static QString QPatternist::formatType (const Cardinality & type) inline static
Formats Cardinality.
Definition at line 181 of file qpatternistlocale_p.h.
     {
         return QLatin1String("<span class='XQuery-type'>")                      +
                escape(type.displayName(Cardinality::IncludeExplanation))        +
                QLatin1String("</span>");
     }
formatURI() [1/3]
static QString QPatternist::formatURI (const NamePool::Ptr & np, const QXmlName::NamespaceCode & uri) inline static
Formats uri, that's considered to be a URI, for display.
Definition at line 202 of file qanyuri_p.h.
Referenced by QPatternist::XPathHelper::checkCollationSupport(), QPatternist::AttributeNameValidator::evaluateSingleton(), formatURI(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseSchema(), QPatternist::AccelTreeResourceLoader::retrieveUnparsedText(), QPatternist::AnyURI::toQUrl(), QPatternist::DocFN::typeCheck(), and yyparse().
     {
         return formatURI(np->stringForNamespace(uri));
     }
formatURI() [2/3]
static QString QPatternist::formatURI (const QUrl & uri) inline static
Formats uri for display.
Note
It's not guaranteed that URIs being formatted are valid. That can be an arbitrary string.
Definition at line 209 of file qpatternistlocale_p.h.
     {
         return QLatin1String("<span class='XQuery-uri'>")       +
                escape(uri.toString(QUrl::RemovePassword))       +
                QLatin1String("</span>");
     }
formatURI() [3/3]
static QString QPatternist::formatURI (const QString & uri) inline static
Formats uri, that's considered to be a URI, for display.
uri does not have to be a valid QUrl or valid instance of xs:anyURI.
Definition at line 222 of file qpatternistlocale_p.h.
     {
         const QUrl realURI(uri);
         return formatURI(realURI);
     }
fromYYLTYPE()
static QSourceLocation QPatternist::fromYYLTYPE (const YYLTYPE & sourceLocator, const ParserContext *const parseInfo) inline static
Definition at line 233 of file qquerytransformparser.cpp.
Referenced by allowedIn(), create(), createIdPatternPath(), createNumericLiteral(), createPatternPath(), registerNamedTemplate(), QPatternist::ReflectYYLTYPE::sourceLocation(), variableUnavailable(), XPatherror(), and yyparse().
 {
     return QSourceLocation(parseInfo->tokenizer->queryURI(),
                            sourceLocator.first_line,
                            sourceLocator.first_column);
 }
isPredicate()
static bool QPatternist::isPredicate (const Expression::ID id) inline static
Definition at line 488 of file qquerytransformparser.cpp.
Referenced by findAxisStep(), and yyparse().
 {
     return id == Expression::IDGenericPredicate ||
            id == Expression::IDFirstItemPredicate;
 }
isVariableReference()
static bool QPatternist::isVariableReference (const Expression::ID id) inline static
Definition at line 310 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     return    id == Expression::IDExpressionVariableReference
            || id == Expression::IDRangeVariableReference
            || id == Expression::IDArgumentReference;
 }
loadPattern()
static void QPatternist::loadPattern (const Expression::Ptr & matchPattern, TemplatePattern::Vector & ourPatterns, const TemplatePattern::ID id, const PatternPriority priority, const Template::Ptr & temp) static
Definition at line 388 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     Q_ASSERT(temp);
     const PatternPriority effectivePriority = qIsNaN(priority) ? matchPattern->patternPriority() : priority;
     ourPatterns.append(TemplatePattern::Ptr(new TemplatePattern(matchPattern, effectivePriority, id, temp)));
 }
locateReturnClause()
static ReturnOrderBy* QPatternist::locateReturnClause (const Expression::Ptr & expr) static
When we want to connect the OrderBy and ReturnOrderBy, it might be that we have other expressions, such as where and let inbetween. We need to continue through them. This function does that.
Definition at line 475 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     Q_ASSERT(expr);
     const Expression::ID id = expr->id();
     if(id == Expression::IDLetClause || id == Expression::IDIfThenClause || id == Expression::IDForClause)
         return locateReturnClause(expr->operands()[1]);
     else if(id == Expression::IDReturnOrderBy)
         return expr->as<ReturnOrderBy>();
     else
         return 0;
 }
makeEmptyIterator()
template<typename T > static QAbstractXmlForwardIterator<T>::Ptr QPatternist::makeEmptyIterator () inline static
Definition at line 135 of file qemptyiterator_p.h.
     {
         return typename QAbstractXmlForwardIterator<T>::Ptr(new EmptyIterator<T>());
     }
makeListIterator()
template<typename T > QAbstractXmlForwardIterator<T>::Ptr QPatternist::makeListIterator (const QList< T > & list) related
Definition at line 250 of file qabstractxmlforwarditerator_p.h.
Referenced by QPatternist::CachingIterator::copy(), QPatternist::NodeSortExpression::evaluateSequence(), QPatternist::CardinalityVerifier::evaluateSequence(), QPatternist::ExpressionSequence::evaluateSequence(), QPatternist::LiteralSequence::evaluateSequence(), QPatternist::Path::evaluateSequence(), QPatternist::TokenizeFN::evaluateSequence(), QPatternist::OrderBy::evaluateSequence(), QPatternist::InScopePrefixesFN::evaluateSequence(), QPatternist::ReturnOrderBy::evaluateSingleton(), and QAbstractXmlNodeModel::iterate().
     {
         return typename ListIterator<T>::Ptr(new ListIterator<T>(list));
     }
makeVectorIterator()
template<typename T > QAbstractXmlForwardIterator<T>::Ptr QPatternist::makeVectorIterator (const QVector< T > & vector) inline
Definition at line 258 of file qabstractxmlforwarditerator_p.h.
Referenced by QAbstractXmlNodeModel::iterate().
     {
         return typename ListIterator<T, QVector<T> >::Ptr(new ListIterator<T, QVector<T> >(vector));
     }
operator|()
static QXmlNodeModelIndex::NodeKind QPatternist::operator| (const QXmlNodeModelIndex::NodeKind & op1, const QXmlNodeModelIndex::NodeKind & op2) inline static
This operator is needed for the s_whenAxisNodeKindEmpty array. The int constructors ensure we invoke another operator| such that we don't get an infinite loop.
Definition at line 60 of file qaxisstep.cpp.
     {
         return QXmlNodeModelIndex::NodeKind(int(op1) | int(op2));
     }
pDebug()
QNoDebug QPatternist::pDebug () inline
Definition at line 99 of file qdebug_p.h.
Referenced by QPatternist::ExpressionFactory::createExpression(), QPatternist::ApplyTemplate::evaluateSequence(), QPatternist::AccelTree::printStats(), and QPatternist::Expression::rewrite().
     {
         return QNoDebug();
     }
prologMessage()
static QString QPatternist::prologMessage (const char *const msg) inline static
Centralizes a translation message, for the purpose of consistency and modularization.
Definition at line 631 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     Q_ASSERT(msg);
     return QtXmlPatterns::tr("Only one %1 declaration can occur in the query prolog.").arg(formatKeyword(msg));
 }
pushVariable()
static Expression::Ptr QPatternist::pushVariable (const QXmlName name, const SequenceType::Ptr & seqType, const Expression::Ptr & expr, const VariableDeclaration::Type type, const YYLTYPE & sourceLocator, ParserContext *const parseInfo, const bool checkSource = true) static
seqType and expr may be null.
Definition at line 907 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     Q_ASSERT(!name.isNull());
     Q_ASSERT(parseInfo);
     /* -2 will cause Q_ASSERTs to trigger if it isn't changed. */
     VariableSlotID slot = -2;
     switch(type)
     {
         case VariableDeclaration::FunctionArgument:
         /* Fallthrough. */
         case VariableDeclaration::ExpressionVariable:
         {
             slot = parseInfo->allocateExpressionSlot();
             break;
         }
         case VariableDeclaration::GlobalVariable:
         {
             slot = parseInfo->allocateGlobalVariableSlot();
             break;
         }
         case VariableDeclaration::RangeVariable:
         {
             slot = parseInfo->staticContext->allocateRangeSlot();
             break;
         }
         case VariableDeclaration::PositionalVariable:
         {
             slot = parseInfo->allocatePositionalSlot();
             break;
         }
         case VariableDeclaration::TemplateParameter:
             /* Fallthrough. We do nothing, template parameters
              * doesn't use context slots at all, they're hashed
              * on the name. */
         case VariableDeclaration::ExternalVariable:
             /* We do nothing, external variables doesn't use
              *context slots/stack frames at all. */
             ;
     }
     const VariableDeclaration::Ptr var(new VariableDeclaration(name, slot, type, seqType));
     Expression::Ptr checked;
     if(checkSource && seqType)
     {
         if(expr)
         {
             /* We only want to add conversion for function arguments, and variables
              * if we're XSL-T.
              *
              * We unconditionally skip TypeChecker::CheckFocus because the StaticContext we
              * pass hasn't set up the focus yet, since that's the parent's responsibility. */
             const TypeChecker::Options options((   type == VariableDeclaration::FunctionArgument
                                                 || type == VariableDeclaration::TemplateParameter
                                                 || parseInfo->isXSLT())
                                                ? TypeChecker::AutomaticallyConvert : TypeChecker::Options());
             checked = TypeChecker::applyFunctionConversion(expr, seqType, parseInfo->staticContext,
                                                            parseInfo->isXSLT() ? ReportContext::XTTE0570 : ReportContext::XPTY0004,
                                                            options);
         }
     }
     else
         checked = expr;
     /* Add an evaluation cache for all expression variables. No EvaluationCache is needed for
      * positional variables because in the end they are calls to Iterator::position(). Similarly,
      * no need to cache range variables either because they are calls to DynamicContext::rangeVariable().
      *
      * We don't do it for function arguments because the Expression being cached depends -- it depends
      * on the callsite. UserFunctionCallsite is responsible for the evaluation caches in that case.
      *
      * In some cases the EvaluationCache instance isn't necessary, but in those cases EvaluationCache
      * optimizes itself away. */
     if(type == VariableDeclaration::ExpressionVariable)
         checked = create(new EvaluationCache<false>(checked, var.data(), parseInfo->allocateCacheSlot()), sourceLocator, parseInfo);
     else if(type == VariableDeclaration::GlobalVariable)
         checked = create(new EvaluationCache<true>(checked, var.data(), parseInfo->allocateCacheSlot()), sourceLocator, parseInfo);
     var->setExpression(checked);
     parseInfo->variables.push(var);
     return checked;
 }
qHash()
uint QPatternist::qHash (const QPatternist::TargetNode & node) inline
Creates a hash value for the given target node.
Definition at line 176 of file qxsdidchelper_p.h.
Referenced by qHash().
     {
         return qHash(node.item().toNodeModelIndex());
     }
quantificationType()
static SequenceType::Ptr QPatternist::quantificationType (const SequenceType::Ptr & type) inline static
The Cardinality in a TypeDeclaration for a variable in a quantification has no effect, and this function ensures this by changing type to Cardinality Cardinality::zeroOrMore().
See also
Bugzilla Bug 3305 Cardinality + on range variables
ParserContext::finalizePushedVariable()
Definition at line 898 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     Q_ASSERT(type);
     return makeGenericSequenceType(type->itemType(), Cardinality::zeroOrMore());
 }
registerNamedTemplate()
static void QPatternist::registerNamedTemplate (const QXmlName & name, const Expression::Ptr & body, ParserContext *const parseInfo, const YYLTYPE & sourceLocator, const Template::Ptr & temp) static
Definition at line 411 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     Template::Ptr &e = parseInfo->namedTemplates[name];
     if(e)
     {
         parseInfo->staticContext->error(QtXmlPatterns::tr("A template with name %1 "
                                                           "has already been declared.")
                                         .arg(formatKeyword(parseInfo->staticContext->namePool(),
                                                                          name)),
                                         ReportContext::XTSE0660,
                                         fromYYLTYPE(sourceLocator, parseInfo));
     }
     else
     {
         e = temp;
         e->body = body;
     }
 }
resolveAndCheckCollation()
template<const ReportContext::ErrorCode errorCode> static QUrl QPatternist::resolveAndCheckCollation (const QString & collation, const ParserContext *const parseInfo, const YYLTYPE & sl) static
Resolves against the static base URI and checks that collation is a supported Unicode Collation.
"If a default collation declaration specifies a collation by a relative URI, that relative URI is resolved to an absolute URI using the base URI in the static context."
Returns
the Unicode Collation properly resolved, if collation is a valid collation
Definition at line 648 of file qquerytransformparser.cpp.
 {
     Q_ASSERT(parseInfo);
     const ReflectYYLTYPE ryy(sl, parseInfo);
     QUrl uri(AnyURI::toQUrl<ReportContext::XQST0046>(collation, parseInfo->staticContext, &ryy));
     if(uri.isRelative())
         uri = parseInfo->staticContext->baseURI().resolved(uri);
     XPathHelper::checkCollationSupport<errorCode>(uri.toString(), parseInfo->staticContext, &ryy);
     return uri;
 }
resolveVariable()
static Expression::Ptr QPatternist::resolveVariable (const QXmlName & name, const YYLTYPE & sourceLocator, ParserContext *const parseInfo, const bool raiseErrorOnUnavailability) static
Definition at line 1022 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     const VariableDeclaration::Ptr var(variableByName(name, parseInfo));
     Expression::Ptr retval;
     if(var && var->type != VariableDeclaration::ExternalVariable)
     {
         switch(var->type)
         {
             case VariableDeclaration::RangeVariable:
             {
                 retval = create(new RangeVariableReference(var->expression(), var->slot), sourceLocator, parseInfo);
                 break;
             }
             case VariableDeclaration::GlobalVariable:
             /* Fallthrough. From the perspective of an ExpressionVariableReference, it can't tell
              * a difference between a global and a local expression variable. However, the cache
              * mechanism must. */
             case VariableDeclaration::ExpressionVariable:
             {
                 retval = create(new ExpressionVariableReference(var->slot, var.data()), sourceLocator, parseInfo);
                 break;
             }
             case VariableDeclaration::FunctionArgument:
             {
                 retval = create(new ArgumentReference(var->sequenceType, var->slot), sourceLocator, parseInfo);
                 break;
             }
             case VariableDeclaration::PositionalVariable:
             {
                 retval = create(new PositionalVariableReference(var->slot), sourceLocator, parseInfo);
                 break;
             }
             case VariableDeclaration::TemplateParameter:
             {
                 retval = create(new TemplateParameterReference(var.data()), sourceLocator, parseInfo);
                 break;
             }
             case VariableDeclaration::ExternalVariable:
                 /* This code path will never be hit, but the case
                  * label silences a warning. See above. */
                 ;
         }
         Q_ASSERT(retval);
         var->references.append(retval);
     }
     else
     {
         /* Let's see if your external variable loader can provide us with one. */
         const SequenceType::Ptr varType(parseInfo->staticContext->
                                         externalVariableLoader()->announceExternalVariable(name, CommonSequenceTypes::ZeroOrMoreItems));
         if(varType)
         {
             const Expression::Ptr extRef(create(new ExternalVariableReference(name, varType), sourceLocator, parseInfo));
             const Expression::Ptr checked(TypeChecker::applyFunctionConversion(extRef, varType, parseInfo->staticContext));
             retval = checked;
         }
         else if(!raiseErrorOnUnavailability && parseInfo->isXSLT())
         {
             /* In XSL-T, global variables are in scope for the whole
              * stylesheet, so we must resolve this first at the end. */
             retval = create(new UnresolvedVariableReference(name), sourceLocator, parseInfo);
             parseInfo->unresolvedVariableReferences.insert(name, retval);
         }
         else
             variableUnavailable(name, parseInfo, sourceLocator);
     }
     return retval;
 }
toItem()
template<typename T > Item QPatternist::toItem (const QExplicitlySharedDataPointer< T > atomicValue) inline
Definition at line 431 of file qitem_p.h.
Referenced by QPatternist::ComparingAggregator< oper, result >::applyNumericPromotion(), QPatternist::AbstractFloatMathematician< isDouble >::calculate(), QPatternist::DecimalMathematician::calculate(), QPatternist::IntegerMathematician::calculate(), QPatternist::DurationDurationMathematician::calculate(), QPatternist::AbstractDateTimeMathematician::calculate(), QPatternist::NumericToAbstractFloatCaster< isDouble >::castFrom(), QPatternist::StringToAbstractFloatCaster< isDouble >::castFrom(), QPatternist::BooleanToAbstractFloatCaster< isDouble >::castFrom(), QPatternist::ToAnyURICaster::castFrom(), QPatternist::NumericToDecimalCaster< IsInteger >::castFrom(), QPatternist::StringToDayTimeDurationCaster::castFrom(), QPatternist::AbstractDurationToDayTimeDurationCaster::castFrom(), QPatternist::AbstractDurationToYearMonthDurationCaster::castFrom(), QPatternist::NumericToDerivedIntegerCaster< type >::castFrom(), QPatternist::CastAs::castToQName(), QPatternist::ResolveURIFN::evaluateSingleton(), QPatternist::UnparsedEntityURIFN::evaluateSingleton(), QPatternist::NodeNameFN::evaluateSingleton(), QPatternist::FloorFN::evaluateSingleton(), QPatternist::QNameConstructor::evaluateSingleton(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::AbsFN::evaluateSingleton(), QPatternist::ResolveQNameFN::evaluateSingleton(), QPatternist::StringJoinFN::evaluateSingleton(), QPatternist::NamespaceURIFN::evaluateSingleton(), QPatternist::RoundFN::evaluateSingleton(), QPatternist::ImplicitTimezoneFN::evaluateSingleton(), QPatternist::CeilingFN::evaluateSingleton(), QPatternist::BaseURIFN::evaluateSingleton(), QPatternist::LocalNameFromQNameFN::evaluateSingleton(), QPatternist::CurrentDateTimeFN::evaluateSingleton(), QPatternist::DocumentURIFN::evaluateSingleton(), QPatternist::NamespaceURIFromQNameFN::evaluateSingleton(), QPatternist::RoundHalfToEvenFN::evaluateSingleton(), QPatternist::NormalizeSpaceFN::evaluateSingleton(), QPatternist::CurrentDateFN::evaluateSingleton(), QPatternist::NamespaceURIForPrefixFN::evaluateSingleton(), QPatternist::CurrentTimeFN::evaluateSingleton(), QPatternist::NormalizeUnicodeFN::evaluateSingleton(), QPatternist::SecondsFromDurationFN::extract(), QPatternist::SecondsFromAbstractDateTimeFN::extract(), QPatternist::TimezoneFromAbstractDateTimeFN::extract(), QPatternist::Integer::fromValue(), QPatternist::YearMonthDuration::fromValue(), QPatternist::DayTimeDuration::fromValue(), QPatternist::ResolveURIFN::typeCheck(), QPatternist::StaticBaseURIFN::typeCheck(), and yyparse().
     {
         return Item(atomicValue.data());
     }
typeCheckTemplateBody()
static Expression::Ptr QPatternist::typeCheckTemplateBody (const Expression::Ptr & body, const SequenceType::Ptr & reqType, const ParserContext *const parseInfo) static
Definition at line 401 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
     return TypeChecker::applyFunctionConversion(body, reqType,
                                                 parseInfo->staticContext,
                                                 ReportContext::XTTE0505,
                                                 TypeChecker::Options(TypeChecker::AutomaticallyConvert | TypeChecker::GeneratePromotion));
 }
unknownType()
static QString QPatternist::unknownType () inline static
Centralizes a translation string for the purpose of increasing consistency.
Definition at line 350 of file qquerytransformparser.cpp.
Referenced by QDeclarativeBindingCompilerPrivate::Result::operator==(), and yyparse().
 {
     return QtXmlPatterns::tr("%1 is an unknown schema type.");
 }
variableByName()
static VariableDeclaration::Ptr QPatternist::variableByName (const QXmlName name, const ParserContext *const parseInfo) inline static
Definition at line 1001 of file qquerytransformparser.cpp.
Referenced by resolveVariable(), and yyparse().
 {
     Q_ASSERT(!name.isNull());
     Q_ASSERT(parseInfo);
     /* We walk the list backwards. */
     const VariableDeclaration::Stack::const_iterator start(parseInfo->variables.constBegin());
     VariableDeclaration::Stack::const_iterator it(parseInfo->variables.constEnd());
     while(it != start)
     {
         --it;
         Q_ASSERT(*it);
         if((*it)->name == name)
             return *it;
     }
     return VariableDeclaration::Ptr();
 }
variableUnavailable()
static void QPatternist::variableUnavailable (const QXmlName & variableName, const ParserContext *const parseInfo, const YYLTYPE & location) static
Definition at line 881 of file qquerytransformparser.cpp.
Referenced by resolveVariable().
 {
     parseInfo->staticContext->error(QtXmlPatterns::tr("No variable with name %1 exists")
                                        .arg(formatKeyword(parseInfo->staticContext->namePool(), variableName)),
                                     ReportContext::XPST0008, fromYYLTYPE(location, parseInfo));
 }
XPatherror()
static int QPatternist::XPatherror (YYLTYPE * sourceLocator, const ParserContext *const parseInfo, const char *const msg) static
The generated Bison parser calls this function when there is a parse error.
It is not called, nor should be, for logical errors(which the Bison not know about). For those, ReportContext::error() is called.
Definition at line 462 of file qquerytransformparser.cpp.
 {
     Q_UNUSED(sourceLocator);
     Q_ASSERT(parseInfo);
     parseInfo->staticContext->error(escape(QLatin1String(msg)), ReportContext::XPST0003, fromYYLTYPE(*sourceLocator, parseInfo));
     return 1;
 }
XPathlex()
static int QPatternist::XPathlex (YYSTYPE * lexVal, YYLTYPE * sourceLocator, const ParserContext *const parseInfo) static
Definition at line 720 of file qquerytransformparser.cpp.
 {
 #ifdef Patternist_DEBUG_PARSER
 #   define YYDEBUG 1
     extern int XPathdebug;
     XPathdebug = 1;
 #endif
     Q_ASSERT(parseInfo);
     const Tokenizer::Token tok(parseInfo->tokenizer->nextToken(sourceLocator));
     (*lexVal).sval = tok.value;
     return static_cast<int>(tok.type);
 }
XPathparse()
int QPatternist::XPathparse (QPatternist::ParserContext *const info)
The entry point to the parser.
Parameters
info supplies the information the parser & scanner needs to create expressions. The created expression, if everything succeeds, can be retrieved via the object info points to.
Returns
non-negative if the parser fails.
See also
ExpressionFactory::createExpression()
Referenced by QPatternist::ExpressionFactory::createExpression().
yydestruct()
static void QPatternist::yydestruct (const char * yymsg, int yytype, YYSTYPE * yyvaluep, YYLTYPE * yylocationp, ParserContext *const parseInfo) static
Definition at line 3360 of file qquerytransformparser.cpp.
 {
   YYUSE (yyvaluep);
   YYUSE (yylocationp);
   YYUSE (parseInfo);
   if (!yymsg)
     yymsg = "Deleting";
   YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);
   switch (yytype)
     {
       default:
     break;
     }
 }
yyparse()
int QPatternist::yyparse (ParserContext *const parseInfo)
xsl:param doesn't make life easy:
If it only has name, it's default value is an empty string(hence has type xs:string), but the value that (maybe) is supplied can be anything, typically a node.
Therefore, for that very common case we can't rely on the Expression's type, but have to force it to item()*.
So if we're supplied the type item()*, we pass a null SequenceType. TemplateParameterReference recognizes this and has item()* as its static type, regardless of if the expression has a more specific type.
xsl:param doesn't make life easy:
If it only has name, it's default value is an empty string(hence has type xs:string), but the value that (maybe) is supplied can be anything, typically a node.
Therefore, for that very common case we can't rely on the Expression's type, but have to force it to item()*.
So if we're supplied the type item()*, we pass a null SequenceType. TemplateParameterReference recognizes this and has item()* as its static type, regardless of if the expression has a more specific type.
Definition at line 3427 of file qquerytransformparser.cpp.
Referenced by yydestruct().
 {
   /* The lookahead symbol.  */
 int yychar;
 /* The semantic value of the lookahead symbol.  */
 YYSTYPE yylval;
 /* Number of syntax errors so far.  */
 int yynerrs;
 /* Location data for the lookahead symbol.  */
 YYLTYPE yylloc;
   int yystate;
   int yyn;
   int yyresult;
   /* Number of tokens to shift before error messages enabled.  */
   int yyerrstatus;
   /* Lookahead token as an internal (translated) token number.  */
   int yytoken = 0;
 #if YYERROR_VERBOSE
   /* Buffer for error messages, and its allocated size.  */
   char yymsgbuf[128];
   char *yymsg = yymsgbuf;
   YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
 #endif
   /* Three stacks and their tools:
      `yyss': related to states,
      `yyvs': related to semantic values,
      `yyls': related to locations.
      Refer to the stacks thru separate pointers, to allow yyoverflow
      to reallocate them elsewhere.  */
   /* The state stack.  */
   yytype_int16 yyssa[YYINITDEPTH];
   yytype_int16 *yyss = yyssa;
   yytype_int16 *yyssp;
   /* The semantic value stack.  */
   YYSTYPE yyvsa[YYINITDEPTH];
   YYSTYPE *yyvs = yyvsa;
   YYSTYPE *yyvsp;
   /* The location stack.  */
   YYLTYPE yylsa[YYINITDEPTH];
   YYLTYPE *yyls = yylsa;
   YYLTYPE *yylsp;
   /* The locations where the error started and ended.  */
   YYLTYPE yyerror_range[2];
 #define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N), yylsp -= (N))
   YYSIZE_T yystacksize = YYINITDEPTH;
   /* The variables used to return semantic value and location from the
      action routines.  */
   YYSTYPE yyval;
   YYLTYPE yyloc;
   /* The number of symbols on the RHS of the reduced rule.
      Keep to zero when no symbol should be popped.  */
   int yylen = 0;
   YYDPRINTF ((stderr, "Starting parse\n"));
   yystate = 0;
   yyerrstatus = 0;
   yynerrs = 0;
   yychar = YYEMPTY;     /* Cause a token to be read.  */
   /* Initialize stack pointers.
      Waste one element of value and location stack
      so that they stay on the same level as the state stack.
      The wasted elements are never initialized.  */
   yyssp = yyss;
   yyvsp = yyvs;
   yylsp = yyls;
 #if YYLTYPE_IS_TRIVIAL
   /* Initialize the default location before parsing starts.  */
   yylloc.first_line   = yylloc.last_line   = 1;
   yylloc.first_column = yylloc.last_column = 1;
 #endif
   goto yysetstate;
 /*------------------------------------------------------------.
 | yynewstate -- Push a new state, which is found in yystate.  |
 `------------------------------------------------------------*/
  yynewstate:
   /* In all cases, when you get here, the value and location stacks
      have just been pushed.  So pushing a state here evens the stacks.  */
   yyssp++;
  yysetstate:
   *yyssp = yystate;
   if (yyss + yystacksize - 1 <= yyssp)
     {
       /* Get the current used size of the three stacks, in elements.  */
       YYSIZE_T yysize = yyssp - yyss + 1;
 #ifdef yyoverflow
       {
     /* Give user a chance to reallocate the stack.  Use copies of
        these so that the &'s don't force the real ones into
        memory.  */
     YYSTYPE *yyvs1 = yyvs;
     yytype_int16 *yyss1 = yyss;
     YYLTYPE *yyls1 = yyls;
     /* Each stack pointer address is followed by the size of the
        data in use in that stack, in bytes.  This used to be a
        conditional around just the two extra args, but that might
        be undefined if yyoverflow is a macro.  */
     yyoverflow (YY_("memory exhausted"),
             &yyss1, yysize * sizeof (*yyssp),
             &yyvs1, yysize * sizeof (*yyvsp),
             &yyls1, yysize * sizeof (*yylsp),
             &yystacksize);
     yyls = yyls1;
     yyss = yyss1;
     yyvs = yyvs1;
       }
 #else /* no yyoverflow */
 # ifndef YYSTACK_RELOCATE
       goto yyexhaustedlab;
 # else
       /* Extend the stack our own way.  */
       if (YYMAXDEPTH <= yystacksize)
     goto yyexhaustedlab;
       yystacksize *= 2;
       if (YYMAXDEPTH < yystacksize)
     yystacksize = YYMAXDEPTH;
       {
     yytype_int16 *yyss1 = yyss;
     union yyalloc *yyptr =
       (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
     if (! yyptr)
       goto yyexhaustedlab;
     YYSTACK_RELOCATE (yyss);
     YYSTACK_RELOCATE (yyvs);
     YYSTACK_RELOCATE (yyls);
 #  undef YYSTACK_RELOCATE
     if (yyss1 != yyssa)
       YYSTACK_FREE (yyss1);
       }
 # endif
 #endif /* no yyoverflow */
       yyssp = yyss + yysize - 1;
       yyvsp = yyvs + yysize - 1;
       yylsp = yyls + yysize - 1;
       YYDPRINTF ((stderr, "Stack size increased to %lu\n",
           (unsigned long int) yystacksize));
       if (yyss + yystacksize - 1 <= yyssp)
     YYABORT;
     }
   YYDPRINTF ((stderr, "Entering state %d\n", yystate));
   if (yystate == YYFINAL)
     YYACCEPT;
   goto yybackup;
 /*-----------.
 | yybackup.  |
 `-----------*/
 yybackup:
   /* Do appropriate processing given the current state.  Read a
      lookahead token if we need one and don't already have one.  */
   /* First try to decide what to do without reference to lookahead token.  */
   yyn = yypact[yystate];
   if (yyn == YYPACT_NINF)
     goto yydefault;
   /* Not known => get a lookahead token if don't already have one.  */
   /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
   if (yychar == YYEMPTY)
     {
       YYDPRINTF ((stderr, "Reading a token: "));
       yychar = YYLEX;
     }
   if (yychar <= YYEOF)
     {
       yychar = yytoken = YYEOF;
       YYDPRINTF ((stderr, "Now at end of input.\n"));
     }
   else
     {
       yytoken = YYTRANSLATE (yychar);
       YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
     }
   /* If the proper action on seeing token YYTOKEN is to reduce or to
      detect an error, take that action.  */
   yyn += yytoken;
   if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
     goto yydefault;
   yyn = yytable[yyn];
   if (yyn <= 0)
     {
       if (yyn == 0 || yyn == YYTABLE_NINF)
     goto yyerrlab;
       yyn = -yyn;
       goto yyreduce;
     }
   /* Count tokens shifted since error; after three, turn off error
      status.  */
   if (yyerrstatus)
     yyerrstatus--;
   /* Shift the lookahead token.  */
   YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
   /* Discard the shifted token.  */
   yychar = YYEMPTY;
   yystate = yyn;
   *++yyvsp = yylval;
   *++yylsp = yylloc;
   goto yynewstate;
 /*-----------------------------------------------------------.
 | yydefault -- do the default action for the current state.  |
 `-----------------------------------------------------------*/
 yydefault:
   yyn = yydefact[yystate];
   if (yyn == 0)
     goto yyerrlab;
   goto yyreduce;
 /*-----------------------------.
 | yyreduce -- Do a reduction.  |
 `-----------------------------*/
 yyreduce:
   /* yyn is the number of a rule to reduce with.  */
   yylen = yyr2[yyn];
   /* If YYLEN is nonzero, implement the default value of the action:
      `$$ = $1'.
      Otherwise, the following line sets YYVAL to garbage.
      This behavior is undocumented and Bison
      users should not rely upon it.  Assigning to YYVAL
      unconditionally makes the parser a bit smaller, and it avoids a
      GCC warning that YYVAL may be used uninitialized.  */
   yyval = yyvsp[1-yylen];
   /* Default location.  */
   YYLLOC_DEFAULT (yyloc, (yylsp - yylen), yylen);
   YY_REDUCE_PRINT (yyn);
   switch (yyn)
     {
         case 5:
 /* Line 1269 of yacc.c.  */
 #line 1380 "querytransformparser.ypp"
     {
 /* Suppress more compiler warnings about unused defines. */
 #if    defined(YYNNTS)              \
     || defined(yyerrok)             \
     || defined(YYNSTATES)           \
     || defined(YYRHSLOC)            \
     || defined(YYRECOVERING)        \
     || defined(YYFAIL)              \
     || defined(YYERROR)             \
     || defined(YYNRULES)            \
     || defined(YYBACKUP)            \
     || defined(YYMAXDEPTH)          \
     || defined(yyclearin)           \
     || defined(YYERRCODE)           \
     || defined(YY_LOCATION_PRINT)   \
     || defined(YYLLOC_DEFAULT)
 #endif
         if((yyvsp[(3) - (5)].sval) != QLatin1String("1.0"))
         {
             const ReflectYYLTYPE ryy((yyloc), parseInfo);
             parseInfo->staticContext->error(QtXmlPatterns::tr("Version %1 is not supported. The supported "
                                                "XQuery version is 1.0.")
                                                .arg(formatData((yyvsp[(3) - (5)].sval))),
                                             ReportContext::XQST0031, &ryy);
         }
     }
     break;
   case 7:
 /* Line 1269 of yacc.c.  */
 #line 1412 "querytransformparser.ypp"
     {
         const QRegExp encNameRegExp(QLatin1String("[A-Za-z][A-Za-z0-9._\\-]*"));
         if(!encNameRegExp.exactMatch((yyvsp[(2) - (2)].sval)))
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("The encoding %1 is invalid. "
                                                "It must contain Latin characters only, "
                                                "must not contain whitespace, and must match "
                                                "the regular expression %2.")
                                             .arg(formatKeyword((yyvsp[(2) - (2)].sval)),
                                                  formatExpression(encNameRegExp.pattern())),
                                             ReportContext::XQST0087, fromYYLTYPE((yyloc), parseInfo));
         }
     }
     break;
   case 8:
 /* Line 1269 of yacc.c.  */
 #line 1428 "querytransformparser.ypp"
     {
         /* In XSL-T, we can have dangling variable references, so resolve them
          * before we proceed with other steps, such as checking circularity. */
         if(parseInfo->isXSLT())
         {
             typedef QHash<QXmlName, Expression::Ptr> Hash;
             const Hash::const_iterator end(parseInfo->unresolvedVariableReferences.constEnd());
             for(Hash::const_iterator it(parseInfo->unresolvedVariableReferences.constBegin()); it != end; ++it)
             {
                 const Expression::Ptr body(resolveVariable(it.key(), (yyloc), parseInfo, true)); // TODO source locations vaise
                 Q_ASSERT(body);
                 it.value()->as<UnresolvedVariableReference>()->bindTo(body);
             }
         }
         /* The UserFunction callsites aren't bound yet, so bind them(if possible!). */
         {
             const UserFunctionCallsite::List::const_iterator cend(parseInfo->userFunctionCallsites.constEnd());
             UserFunctionCallsite::List::const_iterator cit(parseInfo->userFunctionCallsites.constBegin());
             for(; cit != cend; ++cit) /* For each callsite. */
             {
                 const UserFunctionCallsite::Ptr callsite(*cit);
                 Q_ASSERT(callsite);
                 const UserFunction::List::const_iterator end(parseInfo->userFunctions.constEnd());
                 UserFunction::List::const_iterator it(parseInfo->userFunctions.constBegin());
                 for(; it != end; ++it) /* For each UserFunction. */
                 {
                     const FunctionSignature::Ptr sign((*it)->signature());
                     Q_ASSERT(sign);
                     if(callsite->isSignatureValid(sign))
                     {
                         callsite->setSource((*it),
                                             parseInfo->allocateCacheSlots((*it)->argumentDeclarations().count()));
                         break;
                     }
                 }
                 if(it == end)
                 {
                     parseInfo->staticContext->error(QtXmlPatterns::tr("No function with signature %1 is available")
                                                        .arg(formatFunction(callsite)),
                                                     ReportContext::XPST0017, fromYYLTYPE((yyloc), parseInfo));
                 }
             }
         }
         /* Mark callsites in UserFunction bodies as recursive, if they are. */
         {
             const UserFunction::List::const_iterator fend(parseInfo->userFunctions.constEnd());
             UserFunction::List::const_iterator fit(parseInfo->userFunctions.constBegin());
             for(; fit != fend; ++fit)
             {
                 CallTargetDescription::List signList;
                 signList.append((*fit)->signature());
                 CallTargetDescription::checkCallsiteCircularity(signList, (*fit)->body());
             }
         }
         /* Now, check all global variables for circularity.  This is done
          * backwards because global variables are only in scope below them,
          * in XQuery. */
         {
             const VariableDeclaration::List::const_iterator start(parseInfo->declaredVariables.constBegin());
             VariableDeclaration::List::const_iterator it(parseInfo->declaredVariables.constEnd());
             while(it != start)
             {
                 --it;
                 if((*it)->type != VariableDeclaration::ExpressionVariable && (*it)->type != VariableDeclaration::GlobalVariable)
                     continue; /* We want to ignore 'external' variables. */
                 FunctionSignature::List signList;
                 checkVariableCircularity(*it, (*it)->expression(), (*it)->type, signList, parseInfo);
                 ExpressionFactory::registerLastPath((*it)->expression());
                 parseInfo->finalizePushedVariable(1, false); /* Warn if it's unused. */
             }
         }
         /* Generate code for doing initial template name calling. One problem
          * is that we compilation in the initial template name, since we throw away the
          * code if we don't have the requested template. */
         if(parseInfo->languageAccent == QXmlQuery::XSLT20
            && !parseInfo->initialTemplateName.isNull()
            && parseInfo->namedTemplates.contains(parseInfo->initialTemplateName))
         {
             parseInfo->queryBody = create(new CallTemplate(parseInfo->initialTemplateName,
                                                            WithParam::Hash()),
                                           (yyloc), parseInfo);
             parseInfo->templateCalls.append(parseInfo->queryBody);
             /* We just discard the template body that XSLTTokenizer generated. */
         }
         else
             parseInfo->queryBody = (yyvsp[(2) - (2)].expr);
     }
     break;
   case 10:
 /* Line 1269 of yacc.c.  */
 #line 1528 "querytransformparser.ypp"
     {
         // TODO add to namespace context
         parseInfo->moduleNamespace = parseInfo->staticContext->namePool()->allocateNamespace((yyvsp[(3) - (6)].sval));
     }
     break;
   case 12:
 /* Line 1269 of yacc.c.  */
 #line 1536 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
         if(parseInfo->hasSecondPrologPart)
             parseInfo->staticContext->error(QtXmlPatterns::tr("A default namespace declaration must occur before function, "
                                                "variable, and option declarations."), ReportContext::XPST0003, fromYYLTYPE((yyloc), parseInfo));
     }
     break;
   case 13:
 /* Line 1269 of yacc.c.  */
 #line 1543 "querytransformparser.ypp"
     {
         if(parseInfo->hasSecondPrologPart)
             parseInfo->staticContext->error(QtXmlPatterns::tr("A default namespace declaration must occur before function, "
                                                "variable, and option declarations."), ReportContext::XPST0003, fromYYLTYPE((yyloc), parseInfo));
     }
     break;
   case 14:
 /* Line 1269 of yacc.c.  */
 #line 1549 "querytransformparser.ypp"
     {
         if(parseInfo->hasSecondPrologPart)
             parseInfo->staticContext->error(QtXmlPatterns::tr("Namespace declarations must occur before function, "
                                                "variable, and option declarations."), ReportContext::XPST0003, fromYYLTYPE((yyloc), parseInfo));
     }
     break;
   case 15:
 /* Line 1269 of yacc.c.  */
 #line 1555 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
         if(parseInfo->hasSecondPrologPart)
             parseInfo->staticContext->error(QtXmlPatterns::tr("Module imports must occur before function, "
                                                "variable, and option declarations."), ReportContext::XPST0003, fromYYLTYPE((yyloc), parseInfo));
     }
     break;
   case 17:
 /* Line 1269 of yacc.c.  */
 #line 1565 "querytransformparser.ypp"
     {
         parseInfo->hasSecondPrologPart = true;
     }
     break;
   case 18:
 /* Line 1269 of yacc.c.  */
 #line 1569 "querytransformparser.ypp"
     {
         parseInfo->hasSecondPrologPart = true;
     }
     break;
   case 19:
 /* Line 1269 of yacc.c.  */
 #line 1573 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
         parseInfo->hasSecondPrologPart = true;
     }
     break;
   case 20:
 /* Line 1269 of yacc.c.  */
 #line 1596 "querytransformparser.ypp"
     {
         Template::Ptr temp(create(new Template(parseInfo->currentImportPrecedence, (yyvsp[(5) - (7)].sequenceType)), (yyloc), parseInfo));
         registerNamedTemplate((yyvsp[(3) - (7)].qName), typeCheckTemplateBody((yyvsp[(6) - (7)].expr), (yyvsp[(5) - (7)].sequenceType), parseInfo),
                               parseInfo, (yylsp[(1) - (7)]), temp);
         temp->templateParameters = parseInfo->templateParameters;
         parseInfo->templateParametersHandled();
     }
     break;
   case 21:
 /* Line 1269 of yacc.c.  */
 #line 1606 "querytransformparser.ypp"
     {
     parseInfo->isParsingPattern = true;
   }
     break;
   case 22:
 /* Line 1269 of yacc.c.  */
 #line 1610 "querytransformparser.ypp"
     {
     parseInfo->isParsingPattern = false;
   }
     break;
   case 23:
 /* Line 1269 of yacc.c.  */
 #line 1619 "querytransformparser.ypp"
     {
         /* In this grammar branch, we're guaranteed to be a template rule, but
          * may also be a named template. */
         const ImportPrecedence ip = parseInfo->isFirstTemplate() ? 0 : parseInfo->currentImportPrecedence;
         Expression::Ptr pattern((yyvsp[(7) - (15)].expr));
         const TemplatePattern::ID templateID = parseInfo->allocateTemplateID();
         Template::Ptr templ(create(new Template(ip, (yyvsp[(13) - (15)].sequenceType)), (yyloc), parseInfo));
         templ->body = typeCheckTemplateBody((yyvsp[(14) - (15)].expr), (yyvsp[(13) - (15)].sequenceType), parseInfo);
         templ->templateParameters = parseInfo->templateParameters;
         parseInfo->templateParametersHandled();
         TemplatePattern::Vector ourPatterns;
         /* We do it as per 6.4 Conflict Resolution for Template Rules:
          *
          * "If the pattern contains multiple alternatives separated by |, then
          * the template rule is treated equivalently to a set of template
          * rules, one for each alternative. However, it is not an error if a
          * node matches more than one of the alternatives." */
         while(pattern->is(Expression::IDCombineNodes))
         {
             const Expression::List operands(pattern->operands());
             pattern = operands.first();
             loadPattern(operands.at(1), ourPatterns, templateID, (yyvsp[(11) - (15)].enums.Double), templ);
         }
         loadPattern(pattern, ourPatterns, templateID, (yyvsp[(11) - (15)].enums.Double), templ);
         if(!(yyvsp[(3) - (15)].qName).isNull())
             registerNamedTemplate((yyvsp[(3) - (15)].qName), (yyvsp[(14) - (15)].expr), parseInfo, (yylsp[(1) - (15)]), templ);
         /* Now, let's add it to all the relevant templates. */
         for(int i = 0; i < (yyvsp[(10) - (15)].qNameVector).count(); ++i) /* For each mode. */
         {
             const QXmlName &modeName = (yyvsp[(10) - (15)].qNameVector).at(i);
             if(modeName == QXmlName(StandardNamespaces::InternalXSLT, StandardLocalNames::all) && (yyvsp[(10) - (15)].qNameVector).count() > 1)
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("The keyword %1 cannot occur with any other mode name.")
                                                                  .arg(formatKeyword(QLatin1String("#all"))),
                                                 ReportContext::XTSE0530,
                                                 fromYYLTYPE((yyloc), parseInfo));
             }
             /* For each pattern the template use. */
             const TemplateMode::Ptr mode(parseInfo->modeFor(modeName));
             for(int t = 0; t < ourPatterns.count(); ++t)
                 mode->templatePatterns.append(ourPatterns.at(t));
         }
     }
     break;
   case 24:
 /* Line 1269 of yacc.c.  */
 #line 1673 "querytransformparser.ypp"
     {
         (yyval.enums.Double) = std::numeric_limits<xsDouble>::quiet_NaN();
     }
     break;
   case 25:
 /* Line 1269 of yacc.c.  */
 #line 1678 "querytransformparser.ypp"
     {
         const AtomicValue::Ptr val(Decimal::fromLexical((yyvsp[(2) - (2)].sval)));
         if(val->hasError())
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("The value of attribute %1 must be of type %2, which %3 isn't.")
                                                              .arg(formatKeyword(QLatin1String("priority")),
                                                                   formatType(parseInfo->staticContext->namePool(), BuiltinTypes::xsDecimal),
                                                                   formatData((yyvsp[(2) - (2)].sval))),
                                             ReportContext::XTSE0530,
                                             fromYYLTYPE((yyloc), parseInfo));
         }
         else
             (yyval.enums.Double) = val->as<Numeric>()->toDouble();
     }
     break;
   case 26:
 /* Line 1269 of yacc.c.  */
 #line 1694 "querytransformparser.ypp"
     {
         (yyval.qName) = QXmlName();
     }
     break;
   case 28:
 /* Line 1269 of yacc.c.  */
 #line 1700 "querytransformparser.ypp"
     {
         (yyval.qName) = (yyvsp[(2) - (2)].qName);
     }
     break;
   case 30:
 /* Line 1269 of yacc.c.  */
 #line 1706 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
     }
     break;
   case 32:
 /* Line 1269 of yacc.c.  */
 #line 1711 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
     }
     break;
   case 33:
 /* Line 1269 of yacc.c.  */
 #line 1715 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
     }
     break;
   case 34:
 /* Line 1269 of yacc.c.  */
 #line 1719 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
     }
     break;
   case 39:
 /* Line 1269 of yacc.c.  */
 #line 1730 "querytransformparser.ypp"
     {
         if(!(yyvsp[(6) - (7)].enums.Bool))
             allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
         if((yyvsp[(3) - (7)].sval) == QLatin1String("xmlns"))
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("It is not possible to redeclare prefix %1.")
                                                .arg(formatKeyword(QLatin1String("xmlns"))),
                                             ReportContext::XQST0070, fromYYLTYPE((yyloc), parseInfo));
         }
         else if ((yyvsp[(5) - (7)].sval) == CommonNamespaces::XML || (yyvsp[(3) - (7)].sval) == QLatin1String("xml"))
         {
              parseInfo->staticContext->error(QtXmlPatterns::tr(
                                             "The prefix %1 cannot be bound. By default, it is already bound "
                                             "to the namespace %2.")
                                              .arg(formatKeyword("xml"))
                                              .arg(formatURI(CommonNamespaces::XML)),
                                              ReportContext::XQST0070,
                                              fromYYLTYPE((yyloc), parseInfo));
         }
         else if(parseInfo->declaredPrefixes.contains((yyvsp[(3) - (7)].sval)))
         {
             /* This includes the case where the user has bound a default prefix(such
              * as 'local') and now tries to do it again. */
             parseInfo->staticContext->error(QtXmlPatterns::tr("Prefix %1 is already declared in the prolog.")
                                                .arg(formatKeyword((yyvsp[(3) - (7)].sval))),
                                             ReportContext::XQST0033, fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             parseInfo->declaredPrefixes.append((yyvsp[(3) - (7)].sval));
             if((yyvsp[(5) - (7)].sval).isEmpty())
             {
                 parseInfo->staticContext->namespaceBindings()->addBinding(QXmlName(StandardNamespaces::UndeclarePrefix,
                                                                                    StandardLocalNames::empty,
                                                                                    parseInfo->staticContext->namePool()->allocatePrefix((yyvsp[(3) - (7)].sval))));
             }
             else
             {
                 parseInfo->staticContext->namespaceBindings()->addBinding(parseInfo->staticContext->namePool()->allocateBinding((yyvsp[(3) - (7)].sval), (yyvsp[(5) - (7)].sval)));
             }
         }
     }
     break;
   case 40:
 /* Line 1269 of yacc.c.  */
 #line 1776 "querytransformparser.ypp"
     {
         if(parseInfo->hasDeclaration(ParserContext::BoundarySpaceDecl))
         {
             parseInfo->staticContext->error(prologMessage("declare boundary-space"),
                                             ReportContext::XQST0068, fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             parseInfo->staticContext->setBoundarySpacePolicy((yyvsp[(3) - (4)].enums.boundarySpacePolicy));
             parseInfo->registerDeclaration(ParserContext::BoundarySpaceDecl);
         }
     }
     break;
   case 41:
 /* Line 1269 of yacc.c.  */
 #line 1790 "querytransformparser.ypp"
     {
         (yyval.enums.boundarySpacePolicy) = StaticContext::BSPStrip;
     }
     break;
   case 42:
 /* Line 1269 of yacc.c.  */
 #line 1795 "querytransformparser.ypp"
     {
         (yyval.enums.boundarySpacePolicy) = StaticContext::BSPPreserve;
     }
     break;
   case 45:
 /* Line 1269 of yacc.c.  */
 #line 1804 "querytransformparser.ypp"
     {
         if(parseInfo->hasDeclaration(ParserContext::DeclareDefaultElementNamespace))
         {
             parseInfo->staticContext->error(prologMessage("declare default element namespace"),
                                             ReportContext::XQST0066, fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             parseInfo->staticContext->namespaceBindings()->addBinding(QXmlName(parseInfo->staticContext->namePool()->allocateNamespace((yyvsp[(5) - (6)].sval)), StandardLocalNames::empty));
             parseInfo->registerDeclaration(ParserContext::DeclareDefaultElementNamespace);
         }
     }
     break;
   case 46:
 /* Line 1269 of yacc.c.  */
 #line 1819 "querytransformparser.ypp"
     {
         if(parseInfo->hasDeclaration(ParserContext::DeclareDefaultFunctionNamespace))
         {
             parseInfo->staticContext->error(prologMessage("declare default function namespace"),
                                             ReportContext::XQST0066, fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             parseInfo->staticContext->setDefaultFunctionNamespace((yyvsp[(5) - (6)].sval));
             parseInfo->registerDeclaration(ParserContext::DeclareDefaultFunctionNamespace);
         }
     }
     break;
   case 47:
 /* Line 1269 of yacc.c.  */
 #line 1833 "querytransformparser.ypp"
     {
         if((yyvsp[(3) - (5)].qName).prefix() == StandardPrefixes::empty)
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("The name of an option must have a prefix. "
                                                "There is no default namespace for options."),
                                             ReportContext::XPST0081, fromYYLTYPE((yyloc), parseInfo));
         }
     }
     break;
   case 48:
 /* Line 1269 of yacc.c.  */
 #line 1843 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
         if(parseInfo->hasDeclaration(ParserContext::OrderingModeDecl))
         {
             parseInfo->staticContext->error(prologMessage("declare ordering"),
                                             ReportContext::XQST0065, fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             parseInfo->registerDeclaration(ParserContext::OrderingModeDecl);
             parseInfo->staticContext->setOrderingMode((yyvsp[(3) - (4)].enums.orderingMode));
         }
     }
     break;
   case 49:
 /* Line 1269 of yacc.c.  */
 #line 1858 "querytransformparser.ypp"
     {
         (yyval.enums.orderingMode) = StaticContext::Ordered;
     }
     break;
   case 50:
 /* Line 1269 of yacc.c.  */
 #line 1862 "querytransformparser.ypp"
     {
         (yyval.enums.orderingMode) = StaticContext::Unordered;
     }
     break;
   case 51:
 /* Line 1269 of yacc.c.  */
 #line 1867 "querytransformparser.ypp"
     {
         if(parseInfo->hasDeclaration(ParserContext::EmptyOrderDecl))
         {
             parseInfo->staticContext->error(prologMessage("declare default order"),
                                             ReportContext::XQST0069, fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             parseInfo->registerDeclaration(ParserContext::EmptyOrderDecl);
             parseInfo->staticContext->setOrderingEmptySequence((yyvsp[(4) - (5)].enums.orderingEmptySequence));
         }
     }
     break;
   case 52:
 /* Line 1269 of yacc.c.  */
 #line 1881 "querytransformparser.ypp"
     {
         (yyval.enums.orderingEmptySequence) = StaticContext::Least;
     }
     break;
   case 53:
 /* Line 1269 of yacc.c.  */
 #line 1885 "querytransformparser.ypp"
     {
         (yyval.enums.orderingEmptySequence) = StaticContext::Greatest;
     }
     break;
   case 54:
 /* Line 1269 of yacc.c.  */
 #line 1891 "querytransformparser.ypp"
     {
         if(parseInfo->hasDeclaration(ParserContext::CopyNamespacesDecl))
         {
             parseInfo->staticContext->error(prologMessage("declare copy-namespaces"),
                                             ReportContext::XQST0055, fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             parseInfo->registerDeclaration(ParserContext::CopyNamespacesDecl);
         }
     }
     break;
   case 55:
 /* Line 1269 of yacc.c.  */
 #line 1904 "querytransformparser.ypp"
     {
         parseInfo->preserveNamespacesMode = true;
     }
     break;
   case 56:
 /* Line 1269 of yacc.c.  */
 #line 1909 "querytransformparser.ypp"
     {
         parseInfo->preserveNamespacesMode = false;
     }
     break;
   case 57:
 /* Line 1269 of yacc.c.  */
 #line 1914 "querytransformparser.ypp"
     {
         parseInfo->inheritNamespacesMode = true;
     }
     break;
   case 58:
 /* Line 1269 of yacc.c.  */
 #line 1919 "querytransformparser.ypp"
     {
         parseInfo->inheritNamespacesMode = false;
     }
     break;
   case 59:
 /* Line 1269 of yacc.c.  */
 #line 1924 "querytransformparser.ypp"
     {
         if(parseInfo->hasDeclaration(ParserContext::DefaultCollationDecl))
         {
             parseInfo->staticContext->error(prologMessage("declare default collation"),
                                             ReportContext::XQST0038, fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             const QUrl coll(resolveAndCheckCollation<ReportContext::XQST0038>((yyvsp[(4) - (5)].sval), parseInfo, (yyloc)));
             parseInfo->registerDeclaration(ParserContext::DefaultCollationDecl);
             parseInfo->staticContext->setDefaultCollation(coll);
         }
     }
     break;
   case 60:
 /* Line 1269 of yacc.c.  */
 #line 1940 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XSLT20), parseInfo, (yyloc), (yyvsp[(3) - (5)].enums.Bool));
         if(parseInfo->hasDeclaration(ParserContext::BaseURIDecl))
         {
             parseInfo->staticContext->error(prologMessage("declare base-uri"),
                                             ReportContext::XQST0032, fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             parseInfo->registerDeclaration(ParserContext::BaseURIDecl);
             const ReflectYYLTYPE ryy((yyloc), parseInfo);
             QUrl toBeBase(AnyURI::toQUrl<ReportContext::XQST0046>((yyvsp[(4) - (5)].sval), parseInfo->staticContext, &ryy));
             /* Now we're guaranteed that base is a valid lexical representation, but it can still be relative. */
             if(toBeBase.isRelative())
                 toBeBase = parseInfo->staticContext->baseURI().resolved(toBeBase);
             parseInfo->staticContext->setBaseURI(toBeBase);
         }
     }
     break;
   case 61:
 /* Line 1269 of yacc.c.  */
 #line 1963 "querytransformparser.ypp"
     {
         parseInfo->staticContext->error(QtXmlPatterns::tr("The Schema Import feature is not supported, "
                                            "and therefore %1 declarations cannot occur.")
                                            .arg(formatKeyword("import schema")),
                                         ReportContext::XQST0009, fromYYLTYPE((yyloc), parseInfo));
     }
     break;
   case 65:
 /* Line 1269 of yacc.c.  */
 #line 1975 "querytransformparser.ypp"
     {
         if((yyvsp[(4) - (6)].sval).isEmpty())
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("The target namespace of a %1 cannot be empty.")
                                                .arg(formatKeyword("module import")),
                                            ReportContext::XQST0088, fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             /* This is temporary until we have implemented it. */
             parseInfo->staticContext->error(QtXmlPatterns::tr("The module import feature is not supported"),
                                             ReportContext::XQST0016, fromYYLTYPE((yyloc), parseInfo));
         }
     }
     break;
   case 72:
 /* Line 1269 of yacc.c.  */
 #line 2002 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc), (yyvsp[(3) - (9)].enums.Bool));
         if(variableByName((yyvsp[(5) - (9)].qName), parseInfo))
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("A variable with name %1 has already "
                                                               "been declared.")
                                                .arg(formatKeyword(parseInfo->staticContext->namePool()->toLexical((yyvsp[(5) - (9)].qName)))),
                                             parseInfo->isXSLT() ? ReportContext::XTSE0630 : ReportContext::XQST0049,
                                             fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             if((yyvsp[(7) - (9)].expr)) /* We got a value assigned. */
             {
                 const Expression::Ptr checked
                         (TypeChecker::applyFunctionConversion((yyvsp[(7) - (9)].expr), (yyvsp[(6) - (9)].sequenceType), parseInfo->staticContext,
                                                               (yyvsp[(3) - (9)].enums.Bool) ? ReportContext::XTTE0570 : ReportContext::XPTY0004,
                                                               (yyvsp[(3) - (9)].enums.Bool) ? TypeChecker::Options(TypeChecker::CheckFocus | TypeChecker::AutomaticallyConvert) : TypeChecker::CheckFocus));
                 pushVariable((yyvsp[(5) - (9)].qName), (yyvsp[(6) - (9)].sequenceType), checked, VariableDeclaration::GlobalVariable, (yyloc), parseInfo);
                 parseInfo->declaredVariables.append(parseInfo->variables.last());
             }
             else /* We got an 'external' declaration. */
             {
                 const SequenceType::Ptr varType(parseInfo->staticContext->
                                                 externalVariableLoader()->announceExternalVariable((yyvsp[(5) - (9)].qName), (yyvsp[(6) - (9)].sequenceType)));
                 if(varType)
                 {
                     /* We push the declaration such that we can see name clashes and so on, but we don't use it for tying
                      * any references to it. */
                     pushVariable((yyvsp[(5) - (9)].qName), varType, Expression::Ptr(), VariableDeclaration::ExternalVariable, (yyloc), parseInfo);
                 }
                 else if((yyvsp[(8) - (9)].expr))
                 {
                     /* Ok, the xsl:param got a default value, we make it
                      * available as a regular variable declaration. */
                     // TODO turn into checked
                     pushVariable((yyvsp[(5) - (9)].qName), (yyvsp[(6) - (9)].sequenceType), (yyvsp[(8) - (9)].expr), VariableDeclaration::GlobalVariable, (yyloc), parseInfo);
                     // TODO ensure that duplicates are trapped.
                 }
                 else
                 {
                     parseInfo->staticContext->error(QtXmlPatterns::tr("No value is available for the external "
                                                                       "variable with name %1.")
                                                        .arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(5) - (9)].qName))),
                                                     parseInfo->isXSLT() ? ReportContext::XTDE0050 : ReportContext::XPDY0002,
                                                     fromYYLTYPE((yyloc), parseInfo));
                 }
             }
         }
     }
     break;
   case 73:
 /* Line 1269 of yacc.c.  */
 #line 2056 "querytransformparser.ypp"
     {
         (yyval.expr).reset();
     }
     break;
   case 74:
 /* Line 1269 of yacc.c.  */
 #line 2060 "querytransformparser.ypp"
     {
         (yyval.expr) = (yyvsp[(2) - (2)].expr);
     }
     break;
   case 75:
 /* Line 1269 of yacc.c.  */
 #line 2065 "querytransformparser.ypp"
     {
         (yyval.expr).reset();
     }
     break;
   case 76:
 /* Line 1269 of yacc.c.  */
 #line 2069 "querytransformparser.ypp"
     {
         (yyval.expr) = (yyvsp[(2) - (2)].expr);
     }
     break;
   case 77:
 /* Line 1269 of yacc.c.  */
 #line 2074 "querytransformparser.ypp"
     {
         if(parseInfo->hasDeclaration(ParserContext::ConstructionDecl))
         {
             parseInfo->staticContext->error(prologMessage("declare ordering"),
                                             ReportContext::XQST0067, fromYYLTYPE((yyloc), parseInfo));
         }
         else
         {
             parseInfo->registerDeclaration(ParserContext::ConstructionDecl);
             parseInfo->staticContext->setConstructionMode((yyvsp[(3) - (4)].enums.constructionMode));
         }
     }
     break;
   case 78:
 /* Line 1269 of yacc.c.  */
 #line 2088 "querytransformparser.ypp"
     {
         (yyval.enums.constructionMode) = StaticContext::CMStrip;
     }
     break;
   case 79:
 /* Line 1269 of yacc.c.  */
 #line 2092 "querytransformparser.ypp"
     {
         (yyval.enums.constructionMode) = StaticContext::CMPreserve;
     }
     break;
   case 80:
 /* Line 1269 of yacc.c.  */
 #line 2097 "querytransformparser.ypp"
     {
                 (yyval.enums.slot) = parseInfo->currentExpressionSlot() - (yyvsp[(6) - (7)].functionArguments).count();
               }
     break;
   case 81:
 /* Line 1269 of yacc.c.  */
 #line 2101 "querytransformparser.ypp"
     {
         if(!(yyvsp[(3) - (11)].enums.Bool))
             allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc), (yyvsp[(3) - (11)].enums.Bool));
         /* If FunctionBody is null, it is 'external', otherwise the value is the body. */
         const QXmlName::NamespaceCode ns((yyvsp[(4) - (11)].qName).namespaceURI());
         if(parseInfo->isXSLT() && !(yyvsp[(4) - (11)].qName).hasPrefix())
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("A stylesheet function must have a prefixed name."),
                                             ReportContext::XTSE0740,
                                             fromYYLTYPE((yyloc), parseInfo));
         }
         if((yyvsp[(10) - (11)].expr)) /* We got a function body. */
         {
             if(ns == StandardNamespaces::empty)
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("The namespace for a user defined function "
                                                    "cannot be empty (try the predefined "
                                                    "prefix %1, which exists for cases "
                                                    "like this)")
                                                    .arg(formatKeyword("local")),
                                                 ReportContext::XQST0060, fromYYLTYPE((yyloc), parseInfo));
             }
             else if(XPathHelper::isReservedNamespace(ns))
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr(
                                                    "The namespace %1 is reserved; therefore "
                                                    "user defined functions may not use it. "
                                                    "Try the predefined prefix %2, which "
                                                    "exists for these cases.")
                                                 .arg(formatURI(parseInfo->staticContext->namePool(), ns), formatKeyword("local")),
                                                 parseInfo->isXSLT() ? ReportContext::XTSE0080 : ReportContext::XQST0045,
                                                 fromYYLTYPE((yyloc), parseInfo));
             }
             else if(parseInfo->moduleNamespace != StandardNamespaces::empty &&
                     ns != parseInfo->moduleNamespace)
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr(
                                                    "The namespace of a user defined "
                                                    "function in a library module must be "
                                                    "equivalent to the module namespace. "
                                                    "In other words, it should be %1 instead "
                                                    "of %2")
                                                 .arg(formatURI(parseInfo->staticContext->namePool(), parseInfo->moduleNamespace),
                                                      formatURI(parseInfo->staticContext->namePool(), ns)),
                                                 ReportContext::XQST0048, fromYYLTYPE((yyloc), parseInfo));
             }
             else
             {
                 /* Apply function conversion such that the body matches the declared
                  * return type. */
                 const Expression::Ptr checked(TypeChecker::applyFunctionConversion((yyvsp[(10) - (11)].expr), (yyvsp[(9) - (11)].sequenceType),
                                                                                    parseInfo->staticContext,
                                                                                    ReportContext::XPTY0004,
                                                                                    TypeChecker::Options(TypeChecker::AutomaticallyConvert |
                                                                                                         TypeChecker::CheckFocus |
                                                                                                         TypeChecker::GeneratePromotion)));
                 const int argCount = (yyvsp[(6) - (11)].functionArguments).count();
                 const FunctionSignature::Ptr sign(new FunctionSignature((yyvsp[(4) - (11)].qName) /* name */,
                                                                         argCount /* minArgs */,
                                                                         argCount /* maxArgs */,
                                                                         (yyvsp[(9) - (11)].sequenceType) /* returnType */));
                 sign->setArguments((yyvsp[(6) - (11)].functionArguments));
                 const UserFunction::List::const_iterator end(parseInfo->userFunctions.constEnd());
                 UserFunction::List::const_iterator it(parseInfo->userFunctions.constBegin());
                 for(; it != end; ++it)
                 {
                     if(*(*it)->signature() == *sign)
                     {
                         parseInfo->staticContext->error(QtXmlPatterns::tr("A function already exists with "
                                                            "the signature %1.")
                                                            .arg(formatFunction(parseInfo->staticContext->namePool(), sign)),
                                                         parseInfo->isXSLT() ? ReportContext::XTSE0770 : ReportContext::XQST0034, fromYYLTYPE((yyloc), parseInfo));
                     }
                 }
                 VariableDeclaration::List argDecls;
                 for(int i = 0; i < argCount; ++i)
                     argDecls.append(parseInfo->variables.at(i));
                 if((yyvsp[(8) - (11)].enums.slot) > -1)
                 {
                     /* We have allocated slots, so now push them out of scope. */
                     parseInfo->finalizePushedVariable(argCount);
                 }
                 parseInfo->userFunctions.append(UserFunction::Ptr(new UserFunction(sign, checked, (yyvsp[(8) - (11)].enums.slot), argDecls)));
             }
         }
         else /* We got an 'external' declaration. */
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("No external functions are supported. "
                                                "All supported functions can be used directly, "
                                                "without first declaring them as external"),
                                             ReportContext::XPST0017, fromYYLTYPE((yyloc), parseInfo));
         }
     }
     break;
   case 82:
 /* Line 1269 of yacc.c.  */
 #line 2205 "querytransformparser.ypp"
     {
         (yyval.functionArguments) = FunctionArgument::List();
     }
     break;
   case 83:
 /* Line 1269 of yacc.c.  */
 #line 2209 "querytransformparser.ypp"
     {
         FunctionArgument::List l;
         l.append((yyvsp[(1) - (1)].functionArgument));
         (yyval.functionArguments) = l;
     }
     break;
   case 84:
 /* Line 1269 of yacc.c.  */
 #line 2215 "querytransformparser.ypp"
     {
         FunctionArgument::List::const_iterator it((yyvsp[(1) - (3)].functionArguments).constBegin());
         const FunctionArgument::List::const_iterator end((yyvsp[(1) - (3)].functionArguments).constEnd());
         for(; it != end; ++it)
         {
             if((*it)->name() == (yyvsp[(3) - (3)].functionArgument)->name())
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("An argument with name %1 has already "
                                                    "been declared. Every argument name "
                                                    "must be unique.")
                                                    .arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(3) - (3)].functionArgument)->name())),
                                                 ReportContext::XQST0039, fromYYLTYPE((yyloc), parseInfo));
             }
         }
         (yyvsp[(1) - (3)].functionArguments).append((yyvsp[(3) - (3)].functionArgument));
         (yyval.functionArguments) = (yyvsp[(1) - (3)].functionArguments);
     }
     break;
   case 85:
 /* Line 1269 of yacc.c.  */
 #line 2236 "querytransformparser.ypp"
     {
         pushVariable((yyvsp[(2) - (3)].qName), (yyvsp[(3) - (3)].sequenceType), Expression::Ptr(), VariableDeclaration::FunctionArgument, (yyloc), parseInfo);
         (yyval.functionArgument) = FunctionArgument::Ptr(new FunctionArgument((yyvsp[(2) - (3)].qName), (yyvsp[(3) - (3)].sequenceType)));
     }
     break;
   case 86:
 /* Line 1269 of yacc.c.  */
 #line 2242 "querytransformparser.ypp"
     {
         (yyval.expr).reset();
     }
     break;
   case 88:
 /* Line 1269 of yacc.c.  */
 #line 2248 "querytransformparser.ypp"
     {
         (yyval.expr) = (yyvsp[(2) - (3)].expr);
     }
     break;
   case 91:
 /* Line 1269 of yacc.c.  */
 #line 2264 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new CombineNodes((yyvsp[(1) - (3)].expr), CombineNodes::Union, (yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
     }
     break;
   case 93:
 /* Line 1269 of yacc.c.  */
 #line 2270 "querytransformparser.ypp"
     {
         /* We write this into a node test. The spec says, 5.5.3 The Meaning of a Pattern:
          * "Similarly, / matches a document node, and only a document node,
          * because the result of the expression root(.)//(/) returns the root
          * node of the tree containing the context node if and only if it is a
          * document node." */
         (yyval.expr) = create(new AxisStep(QXmlNodeModelIndex::AxisSelf, BuiltinTypes::document), (yyloc), parseInfo);
     }
     break;
   case 94:
 /* Line 1269 of yacc.c.  */
 #line 2279 "querytransformparser.ypp"
     {
         /* /axis::node-test
          *       =>
          * axis::node-test[parent::document-node()]
          *
          * In practice it looks like this. $2 is:
          *
          *     TruthPredicate
          *          AxisStep    self::element(c)
          *          TruthPredicate
          *              AxisStep    parent::element(b)
          *              AxisStep    parent::element(a)
          *
          * and we want this:
          *
          *      TruthPredicate
          *          AxisStep    self::element(c)
          *          TruthPredicate
          *              AxisStep    self::element(b)
          *              TruthPredicate
          *                  AxisStep    parent::element(a)
          *                  AxisStep    parent::document()
          *
          * So we want to rewrite the predicate deepest down into a
          * another TruthPredicate containing the AxisStep.
          *
          * The simplest case where $2 is only an axis step is special. When $2 is:
          *
          *  AxisStep self::element(a)
          *
          * we want:
          *
          *  TruthPredicate
          *      AxisStep self::element(a)
          *      AxisStep parent::document()
          */
         /* First, find the target. */
         Expression::Ptr target((yyvsp[(2) - (2)].expr));
         while(isPredicate(target->id()))
         {
             const Expression::Ptr candidate(target->operands().at(1));
             if(isPredicate(candidate->id()))
                 target = candidate;
             else
                 break; /* target is now the last predicate. */
         }
         if(target->is(Expression::IDAxisStep))
         {
             (yyval.expr) = create(GenericPredicate::create((yyvsp[(2) - (2)].expr), create(new AxisStep(QXmlNodeModelIndex::AxisParent, BuiltinTypes::document), (yyloc), parseInfo),
                                                  parseInfo->staticContext, fromYYLTYPE((yylsp[(1) - (2)]), parseInfo)), (yylsp[(1) - (2)]), parseInfo);
         }
         else
         {
             const Expression::List targetOperands(target->operands());
             Expression::List newOps;
             newOps.append(targetOperands.at(0));
             newOps.append(create(GenericPredicate::create(targetOperands.at(1),
                                                           create(new AxisStep(QXmlNodeModelIndex::AxisParent, BuiltinTypes::document), (yyloc), parseInfo),
                                                           parseInfo->staticContext, fromYYLTYPE((yylsp[(1) - (2)]), parseInfo)), (yylsp[(1) - (2)]), parseInfo));
             target->setOperands(newOps);
             (yyval.expr) = (yyvsp[(2) - (2)].expr);
         }
     }
     break;
   case 95:
 /* Line 1269 of yacc.c.  */
 #line 2349 "querytransformparser.ypp"
     {
         /* //axis::node-test
          *        =>
          * axis::node-test[parent::node()]
          *
          * Spec says: "//para matches any para element that has a parent node."
          */
         (yyval.expr) = create(GenericPredicate::create((yyvsp[(2) - (2)].expr), create(new AxisStep(QXmlNodeModelIndex::AxisParent, BuiltinTypes::node), (yyloc), parseInfo),
                                              parseInfo->staticContext, fromYYLTYPE((yylsp[(1) - (2)]), parseInfo)), (yylsp[(1) - (2)]), parseInfo);
     }
     break;
   case 97:
 /* Line 1269 of yacc.c.  */
 #line 2361 "querytransformparser.ypp"
     {
         createIdPatternPath((yyvsp[(1) - (3)].expr), (yyvsp[(3) - (3)].expr), QXmlNodeModelIndex::AxisParent, (yylsp[(2) - (3)]), parseInfo);
     }
     break;
   case 98:
 /* Line 1269 of yacc.c.  */
 #line 2365 "querytransformparser.ypp"
     {
         createIdPatternPath((yyvsp[(1) - (3)].expr), (yyvsp[(3) - (3)].expr), QXmlNodeModelIndex::AxisAncestor, (yylsp[(2) - (3)]), parseInfo);
     }
     break;
   case 99:
 /* Line 1269 of yacc.c.  */
 #line 2370 "querytransformparser.ypp"
     {
         const Expression::List ands((yyvsp[(1) - (1)].expr)->operands());
         const FunctionSignature::Ptr signature((yyvsp[(1) - (1)].expr)->as<FunctionCall>()->signature());
         const QXmlName name(signature->name());
         const QXmlName key(StandardNamespaces::fn, StandardLocalNames::key);
         const QXmlName id(StandardNamespaces::fn, StandardLocalNames::id);
         if(name == id)
         {
             const Expression::ID id = ands.first()->id();
             if(!isVariableReference(id) && id != Expression::IDStringValue)
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("When function %1 is used for matching inside a pattern, "
                                                                   "the argument must be a variable reference or a string literal.")
                                                                   .arg(formatFunction(parseInfo->staticContext->namePool(), signature)),
                                                 ReportContext::XPST0003,
                                                 fromYYLTYPE((yyloc), parseInfo));
             }
         }
         else if(name == key)
         {
             if(ands.first()->id() != Expression::IDStringValue)
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("In an XSL-T pattern, the first argument to function %1 "
                                                                   "must be a string literal, when used for matching.")
                                                                   .arg(formatFunction(parseInfo->staticContext->namePool(), signature)),
                                                 ReportContext::XPST0003,
                                                 fromYYLTYPE((yyloc), parseInfo));
             }
             const Expression::ID id2 = ands.at(1)->id();
             if(!isVariableReference(id2) &&
                id2 != Expression::IDStringValue &&
                id2 != Expression::IDIntegerValue &&
                id2 != Expression::IDBooleanValue &&
                id2 != Expression::IDFloat)
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("In an XSL-T pattern, the first argument to function %1 "
                                                                   "must be a literal or a variable reference, when used for matching.")
                                                                   .arg(formatFunction(parseInfo->staticContext->namePool(), signature)),
                                                 ReportContext::XPST0003,
                                                 fromYYLTYPE((yyloc), parseInfo));
             }
             if(ands.count() == 3)
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("In an XSL-T pattern, function %1 cannot have a third argument.")
                                                                   .arg(formatFunction(parseInfo->staticContext->namePool(), signature)),
                                                 ReportContext::XPST0003,
                                                 fromYYLTYPE((yyloc), parseInfo));
             }
         }
         else
         {
             const FunctionSignature::Hash signs(parseInfo->staticContext->functionSignatures()->functionSignatures());
             parseInfo->staticContext->error(QtXmlPatterns::tr("In an XSL-T pattern, only function %1 "
                                                               "and %2, not %3, can be used for matching.")
                                                               .arg(formatFunction(parseInfo->staticContext->namePool(), signs.value(id)),
                                                                    formatFunction(parseInfo->staticContext->namePool(), signs.value(key)),
                                                                    formatFunction(parseInfo->staticContext->namePool(), signature)),
                                             ReportContext::XPST0003,
                                             fromYYLTYPE((yyloc), parseInfo));
         }
         (yyval.expr) = (yyvsp[(1) - (1)].expr);
     }
     break;
   case 101:
 /* Line 1269 of yacc.c.  */
 #line 2440 "querytransformparser.ypp"
     {
         (yyval.expr) = createPatternPath((yyvsp[(1) - (3)].expr), (yyvsp[(3) - (3)].expr), QXmlNodeModelIndex::AxisParent, (yylsp[(2) - (3)]), parseInfo);
     }
     break;
   case 102:
 /* Line 1269 of yacc.c.  */
 #line 2444 "querytransformparser.ypp"
     {
         (yyval.expr) = createPatternPath((yyvsp[(1) - (3)].expr), (yyvsp[(3) - (3)].expr), QXmlNodeModelIndex::AxisAncestor, (yylsp[(2) - (3)]), parseInfo);
     }
     break;
   case 103:
 /* Line 1269 of yacc.c.  */
 #line 2449 "querytransformparser.ypp"
     {
         const Expression::Ptr expr(findAxisStep((yyvsp[(1) - (1)].expr)));
         const QXmlNodeModelIndex::Axis axis = expr->as<AxisStep>()->axis();
         AxisStep *const axisStep = expr->as<AxisStep>();
         /* Here we constrain the possible axes, and we rewrite the axes as according
          * to 5.5.3 The Meaning of a Pattern.
          *
          * However, we also rewrite axis child and attribute to axis self. The
          * reason for this is that if we don't, we will match the children of
          * the context node, instead of the context node itself. The formal
          * definition of a pattern, root(.)//EE is insensitive to context,
          * while the way we implement pattern, "the other way of seeing it",
          * e.g from right to left, are very much. */
         if(axisStep->nodeTest() == BuiltinTypes::document
            || axis == QXmlNodeModelIndex::AxisChild)
             axisStep->setAxis(QXmlNodeModelIndex::AxisSelf);
         else if(axis == QXmlNodeModelIndex::AxisAttribute)
         {
             axisStep->setAxis(QXmlNodeModelIndex::AxisSelf);
             /* Consider that the user write attribute::node().  This is
              * semantically equivalent to attribute::attribute(), but since we have changed
              * the axis to axis self, we also need to change the node test, such that we
              * have self::attribute(). */
             if(*axisStep->nodeTest() == *BuiltinTypes::node)
                 axisStep->setNodeTest(BuiltinTypes::attribute);
         }
         else
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("In an XSL-T pattern, axis %1 cannot be used, "
                                                               "only axis %2 or %3 can.")
                                             .arg(formatKeyword(AxisStep::axisName(axis)),
                                                  formatKeyword(AxisStep::axisName(QXmlNodeModelIndex::AxisChild)),
                                                  formatKeyword(AxisStep::axisName(QXmlNodeModelIndex::AxisAttribute))),
                                             ReportContext::XPST0003,
                                             fromYYLTYPE((yyloc), parseInfo));
         }
         (yyval.expr) = (yyvsp[(1) - (1)].expr);
     }
     break;
   case 105:
 /* Line 1269 of yacc.c.  */
 #line 2494 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new ExpressionSequence((yyvsp[(1) - (1)].expressionList)), (yyloc), parseInfo);
     }
     break;
   case 106:
 /* Line 1269 of yacc.c.  */
 #line 2499 "querytransformparser.ypp"
     {
         Expression::List l;
         l.append((yyvsp[(1) - (3)].expr));
         l.append((yyvsp[(3) - (3)].expr));
         (yyval.expressionList) = l;
     }
     break;
   case 107:
 /* Line 1269 of yacc.c.  */
 #line 2506 "querytransformparser.ypp"
     {
         (yyvsp[(1) - (3)].expressionList).append((yyvsp[(3) - (3)].expr));
         (yyval.expressionList) = (yyvsp[(1) - (3)].expressionList);
     }
     break;
   case 113:
 /* Line 1269 of yacc.c.  */
 #line 2517 "querytransformparser.ypp"
     {
         (yyval.expr) = createDirAttributeValue((yyvsp[(3) - (4)].expressionList), parseInfo, (yyloc));
     }
     break;
   case 114:
 /* Line 1269 of yacc.c.  */
 #line 2522 "querytransformparser.ypp"
     {
         QVector<QXmlName> result;
         result.append(QXmlName(StandardNamespaces::InternalXSLT, StandardLocalNames::Default));
         (yyval.qNameVector) = result;
     }
     break;
   case 115:
 /* Line 1269 of yacc.c.  */
 #line 2528 "querytransformparser.ypp"
     {
         (yyval.qNameVector) = (yyvsp[(2) - (2)].qNameVector);
     }
     break;
   case 116:
 /* Line 1269 of yacc.c.  */
 #line 2533 "querytransformparser.ypp"
     {
             (yyval.qName) = QXmlName(StandardNamespaces::InternalXSLT, StandardLocalNames::Default);
     }
     break;
   case 117:
 /* Line 1269 of yacc.c.  */
 #line 2537 "querytransformparser.ypp"
     {
         (yyval.qName) = (yyvsp[(2) - (2)].qName);
     }
     break;
   case 118:
 /* Line 1269 of yacc.c.  */
 #line 2542 "querytransformparser.ypp"
     {
         QVector<QXmlName> result;
         result.append((yyvsp[(1) - (1)].qName));
         (yyval.qNameVector) = result;
     }
     break;
   case 119:
 /* Line 1269 of yacc.c.  */
 #line 2548 "querytransformparser.ypp"
     {
         (yyvsp[(1) - (3)].qNameVector).append((yyvsp[(3) - (3)].qName));
         (yyval.qNameVector) = (yyvsp[(1) - (3)].qNameVector);
     }
     break;
   case 120:
 /* Line 1269 of yacc.c.  */
 #line 2554 "querytransformparser.ypp"
     {
         (yyval.qName) = (yyvsp[(1) - (1)].qName);
     }
     break;
   case 121:
 /* Line 1269 of yacc.c.  */
 #line 2558 "querytransformparser.ypp"
     {
         if((yyvsp[(1) - (1)].sval) == QLatin1String("#current"))
             (yyval.qName) = QXmlName(StandardNamespaces::InternalXSLT, StandardLocalNames::current);
         else if((yyvsp[(1) - (1)].sval) == QLatin1String("#default"))
             (yyval.qName) = QXmlName(StandardNamespaces::InternalXSLT, StandardLocalNames::Default);
         else if((yyvsp[(1) - (1)].sval) == QLatin1String("#all"))
             (yyval.qName) = QXmlName(StandardNamespaces::InternalXSLT, StandardLocalNames::all);
         else
         {
             const ReflectYYLTYPE ryy((yyloc), parseInfo);
             if(!QXmlUtils::isNCName((yyvsp[(1) - (1)].sval)))
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("%1 is an invalid template mode name.")
                                                                   .arg(formatKeyword((yyvsp[(1) - (1)].sval))),
                                                 ReportContext::XTSE0550,
                                                 fromYYLTYPE((yyloc), parseInfo));
             }
             (yyval.qName) = parseInfo->staticContext->namePool()->allocateQName(StandardNamespaces::empty, (yyvsp[(1) - (1)].sval));
         }
     }
     break;
   case 124:
 /* Line 1269 of yacc.c.  */
 #line 2587 "querytransformparser.ypp"
     {
                /* We're pushing the range variable here, not the positional. */
                (yyval.expr) = pushVariable((yyvsp[(3) - (7)].qName), quantificationType((yyvsp[(4) - (7)].sequenceType)), (yyvsp[(7) - (7)].expr), VariableDeclaration::RangeVariable, (yyloc), parseInfo);
            }
     break;
   case 125:
 /* Line 1269 of yacc.c.  */
 #line 2591 "querytransformparser.ypp"
     {
                /* It is ok this appears after PositionalVar, because currentRangeSlot()
                 * uses a different "channel" than currentPositionSlot(), so they can't trash
                 * each other. */
                (yyval.enums.slot) = parseInfo->staticContext->currentRangeSlot();
            }
     break;
   case 126:
 /* Line 1269 of yacc.c.  */
 #line 2598 "querytransformparser.ypp"
     {
         Q_ASSERT((yyvsp[(7) - (10)].expr));
         Q_ASSERT((yyvsp[(10) - (10)].expr));
         /* We want the next last pushed variable, since we push the range variable after the
          * positional variable. */
         if((yyvsp[(5) - (10)].enums.slot) != -1 && parseInfo->variables.at(parseInfo->variables.count() -2)->name == (yyvsp[(3) - (10)].qName))
         {
             /* Ok, a positional variable is used since its slot is not -1, and its name is equal
              * to our range variable. This is an error. */
             parseInfo->staticContext->error(QtXmlPatterns::tr("The name of a variable bound in a for-expression must be different "
                                                "from the positional variable. Hence, the two variables named %1 collide.")
                                                .arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(3) - (10)].qName))),
                                             ReportContext::XQST0089,
                                             fromYYLTYPE((yyloc), parseInfo));
         }
         const Expression::Ptr retBody(create(new ForClause((yyvsp[(9) - (10)].enums.slot), (yyvsp[(8) - (10)].expr), (yyvsp[(10) - (10)].expr), (yyvsp[(5) - (10)].enums.slot)), (yyloc), parseInfo));
         ReturnOrderBy *const rob = locateReturnClause((yyvsp[(10) - (10)].expr));
         if(rob)
             (yyval.expr) = create(new OrderBy(rob->stability(), rob->orderSpecs(), retBody, rob), (yyloc), parseInfo);
         else
             (yyval.expr) = retBody;
         parseInfo->finalizePushedVariable();
         if((yyvsp[(5) - (10)].enums.slot) != -1) /* We also have a positional variable to remove from the scope. */
             parseInfo->finalizePushedVariable();
     }
     break;
   case 127:
 /* Line 1269 of yacc.c.  */
 #line 2632 "querytransformparser.ypp"
     {
              pushVariable((yyvsp[(3) - (7)].qName), quantificationType((yyvsp[(4) - (7)].sequenceType)), (yyvsp[(7) - (7)].expr), VariableDeclaration::RangeVariable, (yyloc), parseInfo);
          }
     break;
   case 128:
 /* Line 1269 of yacc.c.  */
 #line 2635 "querytransformparser.ypp"
     {
              /* It is ok this appears after PositionalVar, because currentRangeSlot()
               * uses a different "channel" than currentPositionSlot(), so they can't trash
               * each other. */
              (yyval.enums.slot) = parseInfo->staticContext->currentRangeSlot();
          }
     break;
   case 129:
 /* Line 1269 of yacc.c.  */
 #line 2642 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new ForClause((yyvsp[(9) - (10)].enums.slot), (yyvsp[(7) - (10)].expr), (yyvsp[(10) - (10)].expr), (yyvsp[(5) - (10)].enums.slot)), (yyloc), parseInfo);
         parseInfo->finalizePushedVariable();
         if((yyvsp[(5) - (10)].enums.slot) != -1) /* We also have a positional variable to remove from the scope. */
             parseInfo->finalizePushedVariable();
     }
     break;
   case 133:
 /* Line 1269 of yacc.c.  */
 #line 2656 "querytransformparser.ypp"
     {
         (yyval.enums.slot) = -1;
     }
     break;
   case 134:
 /* Line 1269 of yacc.c.  */
 #line 2661 "querytransformparser.ypp"
     {
         pushVariable((yyvsp[(3) - (3)].qName), CommonSequenceTypes::ExactlyOneInteger, Expression::Ptr(),
                      VariableDeclaration::PositionalVariable, (yyloc), parseInfo);
         (yyval.enums.slot) = parseInfo->currentPositionSlot();
     }
     break;
   case 135:
 /* Line 1269 of yacc.c.  */
 #line 2668 "querytransformparser.ypp"
     {
                 (yyval.expr) = pushVariable((yyvsp[(4) - (7)].qName), quantificationType((yyvsp[(5) - (7)].sequenceType)), (yyvsp[(7) - (7)].expr), VariableDeclaration::ExpressionVariable, (yyloc), parseInfo);
            }
     break;
   case 136:
 /* Line 1269 of yacc.c.  */
 #line 2672 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc), (yyvsp[(2) - (9)].enums.Bool));
         Q_ASSERT(parseInfo->variables.top()->name == (yyvsp[(4) - (9)].qName));
         (yyval.expr) = create(new LetClause((yyvsp[(8) - (9)].expr), (yyvsp[(9) - (9)].expr), parseInfo->variables.top()), (yyloc), parseInfo);
         parseInfo->finalizePushedVariable();
     }
     break;
   case 137:
 /* Line 1269 of yacc.c.  */
 #line 2681 "querytransformparser.ypp"
     { (yyval.expr) = pushVariable((yyvsp[(3) - (6)].qName), quantificationType((yyvsp[(4) - (6)].sequenceType)), (yyvsp[(6) - (6)].expr), VariableDeclaration::ExpressionVariable, (yyloc), parseInfo);}
     break;
   case 138:
 /* Line 1269 of yacc.c.  */
 #line 2683 "querytransformparser.ypp"
     {
         Q_ASSERT(parseInfo->variables.top()->name == (yyvsp[(3) - (8)].qName));
         (yyval.expr) = create(new LetClause((yyvsp[(7) - (8)].expr), (yyvsp[(8) - (8)].expr), parseInfo->variables.top()), (yyloc), parseInfo);
         parseInfo->finalizePushedVariable();
     }
     break;
   case 142:
 /* Line 1269 of yacc.c.  */
 #line 2694 "querytransformparser.ypp"
     {
         if((yyvsp[(1) - (3)].orderSpecs).isEmpty())
             (yyval.expr) = (yyvsp[(3) - (3)].expr);
         else
             (yyval.expr) = createReturnOrderBy((yyvsp[(1) - (3)].orderSpecs), (yyvsp[(3) - (3)].expr), parseInfo->orderStability.pop(), (yyloc), parseInfo);
     }
     break;
   case 143:
 /* Line 1269 of yacc.c.  */
 #line 2702 "querytransformparser.ypp"
     {
         if((yyvsp[(3) - (5)].orderSpecs).isEmpty())
             (yyval.expr) = create(new IfThenClause((yyvsp[(2) - (5)].expr), (yyvsp[(5) - (5)].expr), create(new EmptySequence, (yyloc), parseInfo)), (yyloc), parseInfo);
         else
             (yyval.expr) = create(new IfThenClause((yyvsp[(2) - (5)].expr), createReturnOrderBy((yyvsp[(3) - (5)].orderSpecs), (yyvsp[(5) - (5)].expr), parseInfo->orderStability.pop(), (yyloc), parseInfo),
                                          create(new EmptySequence, (yyloc), parseInfo)),
                         (yyloc), parseInfo);
     }
     break;
   case 144:
 /* Line 1269 of yacc.c.  */
 #line 2712 "querytransformparser.ypp"
     {
         (yyval.orderSpecs) = OrderSpecTransfer::List();
     }
     break;
   case 146:
 /* Line 1269 of yacc.c.  */
 #line 2718 "querytransformparser.ypp"
     {
         (yyval.orderSpecs) = (yyvsp[(2) - (2)].orderSpecs);
     }
     break;
   case 147:
 /* Line 1269 of yacc.c.  */
 #line 2723 "querytransformparser.ypp"
     {
         OrderSpecTransfer::List list;
         list += (yyvsp[(1) - (3)].orderSpecs);
         list.append((yyvsp[(3) - (3)].orderSpec));
         (yyval.orderSpecs) = list;
     }
     break;
   case 148:
 /* Line 1269 of yacc.c.  */
 #line 2730 "querytransformparser.ypp"
     {
         OrderSpecTransfer::List list;
         list.append((yyvsp[(1) - (1)].orderSpec));
         (yyval.orderSpecs) = list;
     }
     break;
   case 149:
 /* Line 1269 of yacc.c.  */
 #line 2737 "querytransformparser.ypp"
     {
         (yyval.orderSpec) = OrderSpecTransfer((yyvsp[(1) - (4)].expr), OrderBy::OrderSpec((yyvsp[(2) - (4)].enums.sortDirection), (yyvsp[(3) - (4)].enums.orderingEmptySequence)));
     }
     break;
   case 150:
 /* Line 1269 of yacc.c.  */
 #line 2742 "querytransformparser.ypp"
     {
         /* Where does the specification state the default value is ascending?
          *
          * It is implicit, in the first enumerated list in 3.8.3 Order By and Return Clauses:
          *
          * "If T1 and T2 are two tuples in the tuple stream, and V1 and V2 are the first pair
          *  of values encountered when evaluating their orderspecs from left to right for
          *  which one value is greater-than the other (as defined above), then:
          *
          *      1. If V1 is greater-than V2: If the orderspec specifies descending,
          *         then T1 precedes T2 in the tuple stream; otherwise, T2 precedes T1 in the tuple stream.
          *      2. If V2 is greater-than V1: If the orderspec specifies descending,
          *         then T2 precedes T1 in the tuple stream; otherwise, T1 precedes T2 in the tuple stream."
          *
          * which means that if you don't specify anything, or you
          * specify ascending, you get the same result.
          */
         (yyval.enums.sortDirection) = OrderBy::OrderSpec::Ascending;
     }
     break;
   case 151:
 /* Line 1269 of yacc.c.  */
 #line 2763 "querytransformparser.ypp"
     {
         (yyval.enums.sortDirection) = OrderBy::OrderSpec::Ascending;
     }
     break;
   case 152:
 /* Line 1269 of yacc.c.  */
 #line 2768 "querytransformparser.ypp"
     {
         (yyval.enums.sortDirection) = OrderBy::OrderSpec::Descending;
     }
     break;
   case 153:
 /* Line 1269 of yacc.c.  */
 #line 2773 "querytransformparser.ypp"
     {
         (yyval.enums.orderingEmptySequence) = parseInfo->staticContext->orderingEmptySequence();
     }
     break;
   case 156:
 /* Line 1269 of yacc.c.  */
 #line 2780 "querytransformparser.ypp"
     {
         if(parseInfo->isXSLT())
             resolveAndCheckCollation<ReportContext::XTDE1035>((yyvsp[(2) - (2)].sval), parseInfo, (yyloc));
         else
             resolveAndCheckCollation<ReportContext::XQST0076>((yyvsp[(2) - (2)].sval), parseInfo, (yyloc));
     }
     break;
   case 157:
 /* Line 1269 of yacc.c.  */
 #line 2787 "querytransformparser.ypp"
     {
         /* We do nothing. We don't use collations, and we have this non-terminal
          * in order to accept expressions. */
     }
     break;
   case 158:
 /* Line 1269 of yacc.c.  */
 #line 2793 "querytransformparser.ypp"
     {
         parseInfo->orderStability.push(OrderBy::StableOrder);
     }
     break;
   case 159:
 /* Line 1269 of yacc.c.  */
 #line 2797 "querytransformparser.ypp"
     {
         parseInfo->orderStability.push(OrderBy::UnstableOrder);
     }
     break;
   case 162:
 /* Line 1269 of yacc.c.  */
 #line 2805 "querytransformparser.ypp"
     {
                             pushVariable((yyvsp[(3) - (6)].qName), quantificationType((yyvsp[(4) - (6)].sequenceType)), (yyvsp[(6) - (6)].expr),
                                          VariableDeclaration::RangeVariable, (yyloc), parseInfo);
                         }
     break;
   case 163:
 /* Line 1269 of yacc.c.  */
 #line 2809 "querytransformparser.ypp"
     {(yyval.enums.slot) = parseInfo->staticContext->currentRangeSlot();}
     break;
   case 164:
 /* Line 1269 of yacc.c.  */
 #line 2811 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new QuantifiedExpression((yyvsp[(8) - (9)].enums.slot),
                                              QuantifiedExpression::Some, (yyvsp[(6) - (9)].expr), (yyvsp[(9) - (9)].expr)), (yyloc), parseInfo);
         parseInfo->finalizePushedVariable();
     }
     break;
   case 165:
 /* Line 1269 of yacc.c.  */
 #line 2819 "querytransformparser.ypp"
     {
                             (yyval.expr) = pushVariable((yyvsp[(3) - (6)].qName), quantificationType((yyvsp[(4) - (6)].sequenceType)), (yyvsp[(6) - (6)].expr),
                                                     VariableDeclaration::RangeVariable, (yyloc), parseInfo);
                         }
     break;
   case 166:
 /* Line 1269 of yacc.c.  */
 #line 2823 "querytransformparser.ypp"
     {(yyval.enums.slot) = parseInfo->staticContext->currentRangeSlot();}
     break;
   case 167:
 /* Line 1269 of yacc.c.  */
 #line 2825 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new QuantifiedExpression((yyvsp[(8) - (9)].enums.slot),
                                              QuantifiedExpression::Some, (yyvsp[(7) - (9)].expr), (yyvsp[(9) - (9)].expr)), (yyloc), parseInfo);
         parseInfo->finalizePushedVariable();
     }
     break;
   case 169:
 /* Line 1269 of yacc.c.  */
 #line 2834 "querytransformparser.ypp"
     {
                             pushVariable((yyvsp[(3) - (6)].qName), quantificationType((yyvsp[(4) - (6)].sequenceType)), (yyvsp[(6) - (6)].expr),
                                          VariableDeclaration::RangeVariable, (yyloc), parseInfo);
                          }
     break;
   case 170:
 /* Line 1269 of yacc.c.  */
 #line 2838 "querytransformparser.ypp"
     {(yyval.enums.slot) = parseInfo->staticContext->currentRangeSlot();}
     break;
   case 171:
 /* Line 1269 of yacc.c.  */
 #line 2840 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new QuantifiedExpression((yyvsp[(8) - (9)].enums.slot),
                                              QuantifiedExpression::Every, (yyvsp[(6) - (9)].expr), (yyvsp[(9) - (9)].expr)), (yyloc), parseInfo);
         parseInfo->finalizePushedVariable();
     }
     break;
   case 172:
 /* Line 1269 of yacc.c.  */
 #line 2848 "querytransformparser.ypp"
     {
                             (yyval.expr) = pushVariable((yyvsp[(3) - (6)].qName), quantificationType((yyvsp[(4) - (6)].sequenceType)), (yyvsp[(6) - (6)].expr),
                                                     VariableDeclaration::RangeVariable, (yyloc), parseInfo);
                          }
     break;
   case 173:
 /* Line 1269 of yacc.c.  */
 #line 2852 "querytransformparser.ypp"
     {(yyval.enums.slot) = parseInfo->staticContext->currentRangeSlot();}
     break;
   case 174:
 /* Line 1269 of yacc.c.  */
 #line 2854 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new QuantifiedExpression((yyvsp[(8) - (9)].enums.slot),
                                              QuantifiedExpression::Every, (yyvsp[(7) - (9)].expr), (yyvsp[(9) - (9)].expr)), (yyloc), parseInfo);
         parseInfo->finalizePushedVariable();
     }
     break;
   case 176:
 /* Line 1269 of yacc.c.  */
 #line 2863 "querytransformparser.ypp"
     {
         (yyval.expr) = (yyvsp[(2) - (2)].expr);
     }
     break;
   case 177:
 /* Line 1269 of yacc.c.  */
 #line 2890 "querytransformparser.ypp"
     {
                     parseInfo->typeswitchSource.push((yyvsp[(3) - (4)].expr));
                 }
     break;
   case 178:
 /* Line 1269 of yacc.c.  */
 #line 2894 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
         parseInfo->typeswitchSource.pop();
         (yyval.expr) = (yyvsp[(6) - (6)].expr);
     }
     break;
   case 179:
 /* Line 1269 of yacc.c.  */
 #line 2901 "querytransformparser.ypp"
     {
         if(!(yyvsp[(2) - (3)].qName).isNull())
         {
             pushVariable((yyvsp[(2) - (3)].qName), (yyvsp[(3) - (3)].sequenceType), parseInfo->typeswitchSource.top(),
                          VariableDeclaration::ExpressionVariable, (yyloc), parseInfo, false);
         }
     }
     break;
   case 180:
 /* Line 1269 of yacc.c.  */
 #line 2909 "querytransformparser.ypp"
     {
         /* The variable shouldn't be in-scope for other case branches. */
         if(!(yyvsp[(2) - (6)].qName).isNull())
             parseInfo->finalizePushedVariable();
     }
     break;
   case 181:
 /* Line 1269 of yacc.c.  */
 #line 2915 "querytransformparser.ypp"
     {
         const Expression::Ptr instanceOf(create(new InstanceOf(parseInfo->typeswitchSource.top(), (yyvsp[(3) - (8)].sequenceType)), (yyloc), parseInfo));
         (yyval.expr) = create(new IfThenClause(instanceOf, (yyvsp[(6) - (8)].expr), (yyvsp[(8) - (8)].expr)), (yyloc), parseInfo);
     }
     break;
   case 184:
 /* Line 1269 of yacc.c.  */
 #line 2924 "querytransformparser.ypp"
     {
         (yyval.qName) = QXmlName();
     }
     break;
   case 185:
 /* Line 1269 of yacc.c.  */
 #line 2929 "querytransformparser.ypp"
     {
         (yyval.qName) = (yyvsp[(2) - (3)].qName);
     }
     break;
   case 186:
 /* Line 1269 of yacc.c.  */
 #line 2934 "querytransformparser.ypp"
     {
         (yyval.expr) = (yyvsp[(3) - (3)].expr);
     }
     break;
   case 187:
 /* Line 1269 of yacc.c.  */
 #line 2938 "querytransformparser.ypp"
     {
         if(!(yyvsp[(3) - (3)].qName).isNull())
         {
             pushVariable((yyvsp[(3) - (3)].qName), parseInfo->typeswitchSource.top()->staticType(),
                          parseInfo->typeswitchSource.top(),
                          VariableDeclaration::ExpressionVariable, (yyloc), parseInfo, false);
         }
     }
     break;
   case 188:
 /* Line 1269 of yacc.c.  */
 #line 2947 "querytransformparser.ypp"
     {
         if(!(yyvsp[(3) - (6)].qName).isNull())
             parseInfo->finalizePushedVariable();
         (yyval.expr) = (yyvsp[(6) - (6)].expr);
     }
     break;
   case 189:
 /* Line 1269 of yacc.c.  */
 #line 2954 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new IfThenClause((yyvsp[(3) - (8)].expr), (yyvsp[(6) - (8)].expr), (yyvsp[(8) - (8)].expr)), (yyloc), parseInfo);
     }
     break;
   case 191:
 /* Line 1269 of yacc.c.  */
 #line 2961 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new OrExpression((yyvsp[(1) - (3)].expr), (yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
     }
     break;
   case 193:
 /* Line 1269 of yacc.c.  */
 #line 2968 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new AndExpression((yyvsp[(1) - (3)].expr), (yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
     }
     break;
   case 199:
 /* Line 1269 of yacc.c.  */
 #line 2980 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new RangeExpression((yyvsp[(1) - (3)].expr), (yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
     }
     break;
   case 201:
 /* Line 1269 of yacc.c.  */
 #line 2987 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new ArithmeticExpression((yyvsp[(1) - (3)].expr), (yyvsp[(2) - (3)].enums.mathOperator), (yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
     }
     break;
   case 202:
 /* Line 1269 of yacc.c.  */
 #line 2992 "querytransformparser.ypp"
     {(yyval.enums.mathOperator) = AtomicMathematician::Add;}
     break;
   case 203:
 /* Line 1269 of yacc.c.  */
 #line 2993 "querytransformparser.ypp"
     {(yyval.enums.mathOperator) = AtomicMathematician::Substract;}
     break;
   case 205:
 /* Line 1269 of yacc.c.  */
 #line 2997 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new ArithmeticExpression((yyvsp[(1) - (3)].expr), (yyvsp[(2) - (3)].enums.mathOperator), (yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
     }
     break;
   case 206:
 /* Line 1269 of yacc.c.  */
 #line 3002 "querytransformparser.ypp"
     {(yyval.enums.mathOperator) = AtomicMathematician::Multiply;}
     break;
   case 207:
 /* Line 1269 of yacc.c.  */
 #line 3003 "querytransformparser.ypp"
     {(yyval.enums.mathOperator) = AtomicMathematician::Div;}
     break;
   case 208:
 /* Line 1269 of yacc.c.  */
 #line 3004 "querytransformparser.ypp"
     {(yyval.enums.mathOperator) = AtomicMathematician::IDiv;}
     break;
   case 209:
 /* Line 1269 of yacc.c.  */
 #line 3005 "querytransformparser.ypp"
     {(yyval.enums.mathOperator) = AtomicMathematician::Mod;}
     break;
   case 211:
 /* Line 1269 of yacc.c.  */
 #line 3009 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10
                                  | QXmlQuery::XPath20
                                  | QXmlQuery::XmlSchema11IdentityConstraintField
                                  | QXmlQuery::XmlSchema11IdentityConstraintSelector),
                   parseInfo, (yyloc));
         (yyval.expr) = create(new CombineNodes((yyvsp[(1) - (3)].expr), CombineNodes::Union, (yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
     }
     break;
   case 213:
 /* Line 1269 of yacc.c.  */
 #line 3020 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new CombineNodes((yyvsp[(1) - (3)].expr), (yyvsp[(2) - (3)].enums.combinedNodeOp), (yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
     }
     break;
   case 216:
 /* Line 1269 of yacc.c.  */
 #line 3029 "querytransformparser.ypp"
     {
         (yyval.enums.combinedNodeOp) = CombineNodes::Intersect;
     }
     break;
   case 217:
 /* Line 1269 of yacc.c.  */
 #line 3033 "querytransformparser.ypp"
     {
         (yyval.enums.combinedNodeOp) = CombineNodes::Except;
     }
     break;
   case 219:
 /* Line 1269 of yacc.c.  */
 #line 3039 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new InstanceOf((yyvsp[(1) - (4)].expr),
                     SequenceType::Ptr((yyvsp[(4) - (4)].sequenceType))), (yyloc), parseInfo);
     }
     break;
   case 221:
 /* Line 1269 of yacc.c.  */
 #line 3047 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new TreatAs((yyvsp[(1) - (4)].expr), (yyvsp[(4) - (4)].sequenceType)), (yyloc), parseInfo);
     }
     break;
   case 223:
 /* Line 1269 of yacc.c.  */
 #line 3054 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new CastableAs((yyvsp[(1) - (4)].expr), (yyvsp[(4) - (4)].sequenceType)), (yyloc), parseInfo);
     }
     break;
   case 225:
 /* Line 1269 of yacc.c.  */
 #line 3061 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new CastAs((yyvsp[(1) - (4)].expr), (yyvsp[(4) - (4)].sequenceType)), (yyloc), parseInfo);
     }
     break;
   case 227:
 /* Line 1269 of yacc.c.  */
 #line 3068 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new UnaryExpression((yyvsp[(1) - (2)].enums.mathOperator), (yyvsp[(2) - (2)].expr), parseInfo->staticContext), (yyloc), parseInfo);
     }
     break;
   case 228:
 /* Line 1269 of yacc.c.  */
 #line 3074 "querytransformparser.ypp"
     {
         (yyval.enums.mathOperator) = AtomicMathematician::Add;
     }
     break;
   case 229:
 /* Line 1269 of yacc.c.  */
 #line 3078 "querytransformparser.ypp"
     {
         (yyval.enums.mathOperator) = AtomicMathematician::Substract;
     }
     break;
   case 233:
 /* Line 1269 of yacc.c.  */
 #line 3087 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new GeneralComparison((yyvsp[(1) - (3)].expr), (yyvsp[(2) - (3)].enums.valueOperator), (yyvsp[(3) - (3)].expr), parseInfo->isBackwardsCompat.top()), (yyloc), parseInfo);
     }
     break;
   case 234:
 /* Line 1269 of yacc.c.  */
 #line 3092 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorEqual;}
     break;
   case 235:
 /* Line 1269 of yacc.c.  */
 #line 3093 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorNotEqual;}
     break;
   case 236:
 /* Line 1269 of yacc.c.  */
 #line 3094 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorGreaterOrEqual;}
     break;
   case 237:
 /* Line 1269 of yacc.c.  */
 #line 3095 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorGreaterThan;}
     break;
   case 238:
 /* Line 1269 of yacc.c.  */
 #line 3096 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorLessOrEqual;}
     break;
   case 239:
 /* Line 1269 of yacc.c.  */
 #line 3097 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorLessThan;}
     break;
   case 240:
 /* Line 1269 of yacc.c.  */
 #line 3100 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new ValueComparison((yyvsp[(1) - (3)].expr), (yyvsp[(2) - (3)].enums.valueOperator), (yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
     }
     break;
   case 241:
 /* Line 1269 of yacc.c.  */
 #line 3104 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorEqual;}
     break;
   case 242:
 /* Line 1269 of yacc.c.  */
 #line 3105 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorNotEqual;}
     break;
   case 243:
 /* Line 1269 of yacc.c.  */
 #line 3106 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorGreaterOrEqual;}
     break;
   case 244:
 /* Line 1269 of yacc.c.  */
 #line 3107 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorGreaterThan;}
     break;
   case 245:
 /* Line 1269 of yacc.c.  */
 #line 3108 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorLessOrEqual;}
     break;
   case 246:
 /* Line 1269 of yacc.c.  */
 #line 3109 "querytransformparser.ypp"
     {(yyval.enums.valueOperator) = AtomicComparator::OperatorLessThan;}
     break;
   case 247:
 /* Line 1269 of yacc.c.  */
 #line 3112 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new NodeComparison((yyvsp[(1) - (3)].expr), (yyvsp[(2) - (3)].enums.nodeOperator), (yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
     }
     break;
   case 248:
 /* Line 1269 of yacc.c.  */
 #line 3116 "querytransformparser.ypp"
     {(yyval.enums.nodeOperator) = QXmlNodeModelIndex::Is;}
     break;
   case 249:
 /* Line 1269 of yacc.c.  */
 #line 3117 "querytransformparser.ypp"
     {(yyval.enums.nodeOperator) = QXmlNodeModelIndex::Precedes;}
     break;
   case 250:
 /* Line 1269 of yacc.c.  */
 #line 3118 "querytransformparser.ypp"
     {(yyval.enums.nodeOperator) = QXmlNodeModelIndex::Follows;}
     break;
   case 251:
 /* Line 1269 of yacc.c.  */
 #line 3121 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
         parseInfo->staticContext->error(QtXmlPatterns::tr("The Schema Validation Feature is not supported. "
                                                           "Hence, %1-expressions may not be used.")
                                            .arg(formatKeyword("validate")),
                                         ReportContext::XQST0075, fromYYLTYPE((yyloc), parseInfo));
         /*
         $$ = Validate::create($2, $1, parseInfo->staticContext);
         */
     }
     break;
   case 252:
 /* Line 1269 of yacc.c.  */
 #line 3134 "querytransformparser.ypp"
     {(yyval.enums.validationMode) = Validate::Strict;}
     break;
   case 253:
 /* Line 1269 of yacc.c.  */
 #line 3135 "querytransformparser.ypp"
     {(yyval.enums.validationMode) = Validate::Strict;}
     break;
   case 254:
 /* Line 1269 of yacc.c.  */
 #line 3136 "querytransformparser.ypp"
     {(yyval.enums.validationMode) = Validate::Lax;}
     break;
   case 255:
 /* Line 1269 of yacc.c.  */
 #line 3139 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
         /* We don't support any pragmas, so we only do the
          * necessary validation and use the fallback expression. */
         if((yyvsp[(2) - (2)].expr))
             (yyval.expr) = (yyvsp[(2) - (2)].expr);
         else
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("None of the pragma expressions are supported. "
                                                "Therefore, a fallback expression "
                                                "must be present"),
                                             ReportContext::XQST0079, fromYYLTYPE((yyloc), parseInfo));
         }
     }
     break;
   case 256:
 /* Line 1269 of yacc.c.  */
 #line 3156 "querytransformparser.ypp"
     {
         (yyval.expr).reset();
     }
     break;
   case 257:
 /* Line 1269 of yacc.c.  */
 #line 3160 "querytransformparser.ypp"
     {
         (yyval.expr) = (yyvsp[(2) - (3)].expr);
     }
     break;
   case 260:
 /* Line 1269 of yacc.c.  */
 #line 3168 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
     }
     break;
   case 263:
 /* Line 1269 of yacc.c.  */
 #line 3176 "querytransformparser.ypp"
     {
         /* This is "/step". That is, fn:root(self::node()) treat as document-node()/RelativePathExpr. */
         (yyval.expr) = create(new Path(createRootExpression(parseInfo, (yyloc)), (yyvsp[(2) - (2)].expr)), (yyloc), parseInfo);
     }
     break;
   case 264:
 /* Line 1269 of yacc.c.  */
 #line 3182 "querytransformparser.ypp"
     {
         (yyval.expr) = createSlashSlashPath(createRootExpression(parseInfo, (yyloc)), (yyvsp[(2) - (2)].expr), (yyloc), parseInfo);
     }
     break;
   case 265:
 /* Line 1269 of yacc.c.  */
 #line 3186 "querytransformparser.ypp"
     {
         /* This is "/". That is, fn:root(self::node()) treat as document-node(). */
         (yyval.expr) = createRootExpression(parseInfo, (yyloc));
     }
     break;
   case 268:
 /* Line 1269 of yacc.c.  */
 #line 3196 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new Path((yyvsp[(1) - (3)].expr), (yyvsp[(3) - (3)].expr), (yyvsp[(2) - (3)].enums.pathKind)), (yyloc), parseInfo);
     }
     break;
   case 269:
 /* Line 1269 of yacc.c.  */
 #line 3200 "querytransformparser.ypp"
     {
         const Expression::Ptr orderBy(createReturnOrderBy((yyvsp[(4) - (7)].orderSpecs), (yyvsp[(6) - (7)].expr), parseInfo->orderStability.pop(), (yyloc), parseInfo));
         ReturnOrderBy *const rob = orderBy->as<ReturnOrderBy>();
         const Expression::Ptr path(create(new Path((yyvsp[(1) - (7)].expr), orderBy, (yyvsp[(2) - (7)].enums.pathKind)), (yyloc), parseInfo));
         (yyval.expr) = create(new OrderBy(rob->stability(), rob->orderSpecs(), path, rob), (yyloc), parseInfo);
     }
     break;
   case 270:
 /* Line 1269 of yacc.c.  */
 #line 3209 "querytransformparser.ypp"
     {
         (yyval.expr) = createSlashSlashPath((yyvsp[(1) - (3)].expr), (yyvsp[(3) - (3)].expr), (yyloc), parseInfo);
     }
     break;
   case 271:
 /* Line 1269 of yacc.c.  */
 #line 3214 "querytransformparser.ypp"
     {
         (yyval.expr) = NodeSortExpression::wrapAround((yyvsp[(1) - (1)].expr), parseInfo->staticContext);
     }
     break;
   case 273:
 /* Line 1269 of yacc.c.  */
 #line 3219 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new CurrentItemStore((yyvsp[(2) - (2)].expr)), (yyloc), parseInfo);
     }
     break;
   case 274:
 /* Line 1269 of yacc.c.  */
 #line 3223 "querytransformparser.ypp"
     {
         const xsDouble version = (yyvsp[(1) - (1)].sval).toDouble();
         parseInfo->isBackwardsCompat.push(version != 2);
         (yyval.enums.Double) = version;
     }
     break;
   case 275:
 /* Line 1269 of yacc.c.  */
 #line 3231 "querytransformparser.ypp"
     {
         if((yyvsp[(2) - (3)].enums.Double) < 2)
             (yyval.expr) = createCompatStore((yyvsp[(3) - (3)].expr), (yyloc), parseInfo);
         else
             (yyval.expr) = (yyvsp[(3) - (3)].expr);
     }
     break;
   case 276:
 /* Line 1269 of yacc.c.  */
 #line 3238 "querytransformparser.ypp"
     {
     allowedIn(QXmlQuery::XSLT20, parseInfo, (yyloc));
     Q_ASSERT(!(yyvsp[(2) - (5)].sval).isEmpty());
     (yyval.expr) = create(new StaticBaseURIStore((yyvsp[(2) - (5)].sval), (yyvsp[(4) - (5)].expr)), (yyloc), parseInfo);
 }
     break;
   case 277:
 /* Line 1269 of yacc.c.  */
 #line 3245 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XSLT20), parseInfo, (yyloc));
         parseInfo->resolvers.push(parseInfo->staticContext->namespaceBindings());
         const NamespaceResolver::Ptr resolver(new DelegatingNamespaceResolver(parseInfo->staticContext->namespaceBindings()));
         resolver->addBinding(QXmlName(parseInfo->staticContext->namePool()->allocateNamespace((yyvsp[(5) - (6)].sval)),
                                       StandardLocalNames::empty,
                                       parseInfo->staticContext->namePool()->allocatePrefix((yyvsp[(3) - (6)].sval))));
         parseInfo->staticContext->setNamespaceBindings(resolver);
     }
     break;
   case 278:
 /* Line 1269 of yacc.c.  */
 #line 3256 "querytransformparser.ypp"
     {
         parseInfo->staticContext->setNamespaceBindings(parseInfo->resolvers.pop());
         (yyval.expr) = (yyvsp[(8) - (9)].expr);
     }
     break;
   case 279:
 /* Line 1269 of yacc.c.  */
 #line 3261 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new CallTemplate((yyvsp[(2) - (5)].qName), parseInfo->templateWithParams), (yyloc), parseInfo);
         parseInfo->templateWithParametersHandled();
         parseInfo->templateCalls.append((yyval.expr));
     }
     break;
   case 280:
 /* Line 1269 of yacc.c.  */
 #line 3268 "querytransformparser.ypp"
     {
         parseInfo->startParsingWithParam();
     }
     break;
   case 281:
 /* Line 1269 of yacc.c.  */
 #line 3272 "querytransformparser.ypp"
     {
         parseInfo->endParsingWithParam();
     }
     break;
   case 282:
 /* Line 1269 of yacc.c.  */
 #line 3277 "querytransformparser.ypp"
     {
     }
     break;
   case 283:
 /* Line 1269 of yacc.c.  */
 #line 3280 "querytransformparser.ypp"
     {
     }
     break;
   case 284:
 /* Line 1269 of yacc.c.  */
 #line 3283 "querytransformparser.ypp"
     {
     }
     break;
   case 285:
 /* Line 1269 of yacc.c.  */
 #line 3287 "querytransformparser.ypp"
     {
     }
     break;
   case 286:
 /* Line 1269 of yacc.c.  */
 #line 3290 "querytransformparser.ypp"
     {
     }
     break;
   case 287:
 /* Line 1269 of yacc.c.  */
 #line 3294 "querytransformparser.ypp"
     {
         /* Note, this grammar rule is invoked for @c xsl:param @em and @c
          * xsl:with-param. */
         const bool isParsingWithParam = parseInfo->isParsingWithParam();
         SequenceType::Ptr type;
         if(!(yyvsp[(4) - (5)].sequenceType)->is(CommonSequenceTypes::ZeroOrMoreItems))
             type = (yyvsp[(4) - (5)].sequenceType);
         Expression::Ptr expr;
         /* The default value is an empty sequence. */
         if(!(yyvsp[(5) - (5)].expr) && ((type && (yyvsp[(4) - (5)].sequenceType)->cardinality().allowsEmpty())
                    || isParsingWithParam))
             expr = create(new EmptySequence, (yyloc), parseInfo);
         else
             expr = (yyvsp[(5) - (5)].expr);
         /* We ensure we have some type, so CallTemplate, Template and friends
          * are happy. */
         if(!isParsingWithParam && !type)
             type = CommonSequenceTypes::ZeroOrMoreItems;
         if((yyvsp[(1) - (5)].enums.Bool))
             /* TODO, handle tunnel parameters. */;
         else
         {
             if((!isParsingWithParam && VariableDeclaration::contains(parseInfo->templateParameters, (yyvsp[(3) - (5)].qName))) ||
                (isParsingWithParam && parseInfo->templateWithParams.contains((yyvsp[(3) - (5)].qName))))
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("Each name of a template parameter must be unique; %1 is duplicated.")
                                                                  .arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(3) - (5)].qName))),
                                                 isParsingWithParam ? ReportContext::XTSE0670 : ReportContext::XTSE0580, fromYYLTYPE((yyloc), parseInfo));
             }
             else
             {
                 if(isParsingWithParam)
                     parseInfo->templateWithParams[(yyvsp[(3) - (5)].qName)] = WithParam::Ptr(new WithParam((yyvsp[(3) - (5)].qName), (yyvsp[(4) - (5)].sequenceType), expr));
                 else
                 {
                     Q_ASSERT(type);
                     pushVariable((yyvsp[(3) - (5)].qName), type, expr, VariableDeclaration::TemplateParameter, (yyloc), parseInfo);
                     parseInfo->templateParameters.append(parseInfo->variables.top());
                 }
             }
         }
     }
     break;
   case 288:
 /* Line 1269 of yacc.c.  */
 #line 3359 "querytransformparser.ypp"
     {
         (yyval.enums.Bool) = false;
     }
     break;
   case 289:
 /* Line 1269 of yacc.c.  */
 #line 3363 "querytransformparser.ypp"
     {
         (yyval.enums.Bool) = true;
     }
     break;
   case 290:
 /* Line 1269 of yacc.c.  */
 #line 3368 "querytransformparser.ypp"
     {
         (yyval.expr) = Expression::Ptr();
     }
     break;
   case 291:
 /* Line 1269 of yacc.c.  */
 #line 3372 "querytransformparser.ypp"
     {
         (yyval.expr) = (yyvsp[(2) - (2)].expr);
     }
     break;
   case 292:
 /* Line 1269 of yacc.c.  */
 #line 3381 "querytransformparser.ypp"
     {
         (yyval.enums.pathKind) = Path::RegularPath;
     }
     break;
   case 293:
 /* Line 1269 of yacc.c.  */
 #line 3385 "querytransformparser.ypp"
     {
         (yyval.enums.pathKind) = Path::XSLTForEach;
     }
     break;
   case 294:
 /* Line 1269 of yacc.c.  */
 #line 3389 "querytransformparser.ypp"
     {
         (yyval.enums.pathKind) = Path::ForApplyTemplate;
     }
     break;
   case 296:
 /* Line 1269 of yacc.c.  */
 #line 3395 "querytransformparser.ypp"
     {
         (yyval.expr) = create(GenericPredicate::create((yyvsp[(1) - (4)].expr), (yyvsp[(3) - (4)].expr), parseInfo->staticContext, fromYYLTYPE((yyloc), parseInfo)), (yyloc), parseInfo);
     }
     break;
   case 299:
 /* Line 1269 of yacc.c.  */
 #line 3403 "querytransformparser.ypp"
     {
                 if((yyvsp[(1) - (1)].enums.axis) == QXmlNodeModelIndex::AxisAttribute)
                     parseInfo->nodeTestSource = BuiltinTypes::attribute;
              }
     break;
   case 300:
 /* Line 1269 of yacc.c.  */
 #line 3408 "querytransformparser.ypp"
     {
         if((yyvsp[(3) - (3)].itemType))
         {
             /* A node test was explicitly specified. The un-abbreviated syntax was used. */
             (yyval.expr) = create(new AxisStep((yyvsp[(1) - (3)].enums.axis), (yyvsp[(3) - (3)].itemType)), (yyloc), parseInfo);
         }
         else
         {
             /* Quote from 3.2.1.1 Axes
              *
              * [Definition: Every axis has a principal node kind. If an axis
              *  can contain elements, then the principal node kind is element;
              *  otherwise, it is the kind of nodes that the axis can contain.] Thus:
              * - For the attribute axis, the principal node kind is attribute.
              * - For all other axes, the principal node kind is element. */
             if((yyvsp[(1) - (3)].enums.axis) == QXmlNodeModelIndex::AxisAttribute)
                 (yyval.expr) = create(new AxisStep(QXmlNodeModelIndex::AxisAttribute, BuiltinTypes::attribute), (yyloc), parseInfo);
             else
                 (yyval.expr) = create(new AxisStep((yyvsp[(1) - (3)].enums.axis), BuiltinTypes::element), (yyloc), parseInfo);
         }
         parseInfo->restoreNodeTestSource();
     }
     break;
   case 304:
 /* Line 1269 of yacc.c.  */
 #line 3438 "querytransformparser.ypp"
     {
         if((yyvsp[(1) - (2)].enums.axis) == QXmlNodeModelIndex::AxisNamespace)
         {
             /* We don't raise XPST0010 here because the namespace axis isn't an optional
              * axis. It simply is not part of the XQuery grammar. */
             parseInfo->staticContext->error(QtXmlPatterns::tr("The %1-axis is unsupported in XQuery")
                                                .arg(formatKeyword("namespace")),
                                             ReportContext::XPST0003, fromYYLTYPE((yyloc), parseInfo));
         }
         else
             (yyval.enums.axis) = (yyvsp[(1) - (2)].enums.axis);
         switch((yyvsp[(1) - (2)].enums.axis))
         {
             case QXmlNodeModelIndex::AxisAttribute:
             {
                 allowedIn(QueryLanguages(  QXmlQuery::XPath20
                                          | QXmlQuery::XQuery10
                                          | QXmlQuery::XmlSchema11IdentityConstraintField
                                          | QXmlQuery::XSLT20),
                           parseInfo, (yyloc));
                 break;
             }
             case QXmlNodeModelIndex::AxisChild:
             {
                 allowedIn(QueryLanguages(  QXmlQuery::XPath20
                                          | QXmlQuery::XQuery10
                                          | QXmlQuery::XmlSchema11IdentityConstraintField
                                          | QXmlQuery::XmlSchema11IdentityConstraintSelector
                                          | QXmlQuery::XSLT20),
                           parseInfo, (yyloc));
                 break;
             }
             default:
             {
                 allowedIn(QueryLanguages(  QXmlQuery::XPath20
                                          | QXmlQuery::XQuery10
                                          | QXmlQuery::XSLT20),
                           parseInfo, (yyloc));
             }
         }
     }
     break;
   case 305:
 /* Line 1269 of yacc.c.  */
 #line 3481 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisAncestorOrSelf  ;}
     break;
   case 306:
 /* Line 1269 of yacc.c.  */
 #line 3482 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisAncestor        ;}
     break;
   case 307:
 /* Line 1269 of yacc.c.  */
 #line 3483 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisAttribute       ;}
     break;
   case 308:
 /* Line 1269 of yacc.c.  */
 #line 3484 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisChild           ;}
     break;
   case 309:
 /* Line 1269 of yacc.c.  */
 #line 3485 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisDescendantOrSelf;}
     break;
   case 310:
 /* Line 1269 of yacc.c.  */
 #line 3486 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisDescendant      ;}
     break;
   case 311:
 /* Line 1269 of yacc.c.  */
 #line 3487 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisFollowing       ;}
     break;
   case 312:
 /* Line 1269 of yacc.c.  */
 #line 3488 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisPreceding       ;}
     break;
   case 313:
 /* Line 1269 of yacc.c.  */
 #line 3489 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisFollowingSibling;}
     break;
   case 314:
 /* Line 1269 of yacc.c.  */
 #line 3490 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisPrecedingSibling;}
     break;
   case 315:
 /* Line 1269 of yacc.c.  */
 #line 3491 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisParent          ;}
     break;
   case 316:
 /* Line 1269 of yacc.c.  */
 #line 3492 "querytransformparser.ypp"
     {(yyval.enums.axis) = QXmlNodeModelIndex::AxisSelf            ;}
     break;
   case 317:
 /* Line 1269 of yacc.c.  */
 #line 3495 "querytransformparser.ypp"
     {
                         parseInfo->nodeTestSource = BuiltinTypes::attribute;
                    }
     break;
   case 318:
 /* Line 1269 of yacc.c.  */
 #line 3499 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XSLT20 | QXmlQuery::XmlSchema11IdentityConstraintField), parseInfo, (yyloc));
         (yyval.expr) = create(new AxisStep(QXmlNodeModelIndex::AxisAttribute, (yyvsp[(3) - (3)].itemType)), (yyloc), parseInfo);
         parseInfo->restoreNodeTestSource();
     }
     break;
   case 319:
 /* Line 1269 of yacc.c.  */
 #line 3506 "querytransformparser.ypp"
     {
         ItemType::Ptr nodeTest;
         if(parseInfo->isParsingPattern && *(yyvsp[(1) - (1)].itemType) == *BuiltinTypes::node)
             nodeTest = BuiltinTypes::xsltNodeTest;
         else
             nodeTest = (yyvsp[(1) - (1)].itemType);
         (yyval.expr) = create(new AxisStep(QXmlNodeModelIndex::AxisChild, nodeTest), (yyloc), parseInfo);
     }
     break;
   case 320:
 /* Line 1269 of yacc.c.  */
 #line 3517 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new AxisStep(QXmlNodeModelIndex::AxisAttribute, (yyvsp[(1) - (1)].itemType)), (yyloc), parseInfo);
     }
     break;
   case 322:
 /* Line 1269 of yacc.c.  */
 #line 3524 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new AxisStep(QXmlNodeModelIndex::AxisParent, BuiltinTypes::node), (yyloc), parseInfo);
     }
     break;
   case 324:
 /* Line 1269 of yacc.c.  */
 #line 3530 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
     }
     break;
   case 325:
 /* Line 1269 of yacc.c.  */
 #line 3535 "querytransformparser.ypp"
     {
         (yyval.itemType) = QNameTest::create(parseInfo->nodeTestSource, (yyvsp[(1) - (1)].qName));
     }
     break;
   case 327:
 /* Line 1269 of yacc.c.  */
 #line 3541 "querytransformparser.ypp"
     {
         (yyval.itemType) = parseInfo->nodeTestSource;
     }
     break;
   case 328:
 /* Line 1269 of yacc.c.  */
 #line 3545 "querytransformparser.ypp"
     {
         const NamePool::Ptr np(parseInfo->staticContext->namePool());
         const ReflectYYLTYPE ryy((yyloc), parseInfo);
         const QXmlName::NamespaceCode ns(QNameConstructor::namespaceForPrefix(np->allocatePrefix((yyvsp[(1) - (1)].sval)), parseInfo->staticContext, &ryy));
         (yyval.itemType) = NamespaceNameTest::create(parseInfo->nodeTestSource, ns);
     }
     break;
   case 329:
 /* Line 1269 of yacc.c.  */
 #line 3554 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         const QXmlName::LocalNameCode c = parseInfo->staticContext->namePool()->allocateLocalName((yyvsp[(1) - (1)].sval));
         (yyval.itemType) = LocalNameTest::create(parseInfo->nodeTestSource, c);
     }
     break;
   case 331:
 /* Line 1269 of yacc.c.  */
 #line 3562 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(GenericPredicate::create((yyvsp[(1) - (4)].expr), (yyvsp[(3) - (4)].expr), parseInfo->staticContext, fromYYLTYPE((yylsp[(4) - (4)]), parseInfo)), (yyloc), parseInfo);
     }
     break;
   case 339:
 /* Line 1269 of yacc.c.  */
 #line 3575 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new ApplyTemplate(parseInfo->modeFor((yyvsp[(2) - (5)].qName)),
                                       parseInfo->templateWithParams,
                                       parseInfo->modeFor(QXmlName(StandardNamespaces::InternalXSLT,
                                                                   StandardLocalNames::Default))),
                     (yylsp[(1) - (5)]), parseInfo);
         parseInfo->templateWithParametersHandled();
     }
     break;
   case 341:
 /* Line 1269 of yacc.c.  */
 #line 3586 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new Literal(AtomicString::fromValue((yyvsp[(1) - (1)].sval))), (yyloc), parseInfo);
     }
     break;
   case 342:
 /* Line 1269 of yacc.c.  */
 #line 3591 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = createNumericLiteral<Double>((yyvsp[(1) - (1)].sval), (yyloc), parseInfo);
     }
     break;
   case 343:
 /* Line 1269 of yacc.c.  */
 #line 3596 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = createNumericLiteral<Numeric>((yyvsp[(1) - (1)].sval), (yyloc), parseInfo);
     }
     break;
   case 344:
 /* Line 1269 of yacc.c.  */
 #line 3602 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = resolveVariable((yyvsp[(2) - (2)].qName), (yyloc), parseInfo, false);
     }
     break;
   case 345:
 /* Line 1269 of yacc.c.  */
 #line 3608 "querytransformparser.ypp"
     {
         /* See: http://www.w3.org/TR/xpath20/#id-variables */
         (yyval.qName) = parseInfo->staticContext->namePool()->allocateQName(QString(), (yyvsp[(1) - (1)].sval));
     }
     break;
   case 346:
 /* Line 1269 of yacc.c.  */
 #line 3613 "querytransformparser.ypp"
     {
         (yyval.qName) = (yyvsp[(1) - (1)].qName);
     }
     break;
   case 347:
 /* Line 1269 of yacc.c.  */
 #line 3618 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = (yyvsp[(2) - (3)].expr);
     }
     break;
   case 348:
 /* Line 1269 of yacc.c.  */
 #line 3623 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         (yyval.expr) = create(new EmptySequence, (yyloc), parseInfo);
     }
     break;
   case 349:
 /* Line 1269 of yacc.c.  */
 #line 3629 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new ContextItem(), (yyloc), parseInfo);
     }
     break;
   case 350:
 /* Line 1269 of yacc.c.  */
 #line 3634 "querytransformparser.ypp"
     {
         (yyval.expr) = (yyvsp[(2) - (2)].expr);
     }
     break;
   case 351:
 /* Line 1269 of yacc.c.  */
 #line 3639 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
         if(XPathHelper::isReservedNamespace((yyvsp[(1) - (4)].qName).namespaceURI()) || (yyvsp[(1) - (4)].qName).namespaceURI() == StandardNamespaces::InternalXSLT)
         { /* We got a call to a builtin function. */
             const ReflectYYLTYPE ryy((yyloc), parseInfo);
             const Expression::Ptr
                 func(parseInfo->staticContext->
                 functionSignatures()->createFunctionCall((yyvsp[(1) - (4)].qName), (yyvsp[(3) - (4)].expressionList), parseInfo->staticContext, &ryy));
             if(func)
                 (yyval.expr) = create(func, (yyloc), parseInfo);
             else
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("No function with name %1 is available.")
                                                    .arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(1) - (4)].qName))),
                                                 ReportContext::XPST0017, fromYYLTYPE((yyloc), parseInfo));
             }
         }
         else /* It's a call to a function created with 'declare function'.*/
         {
             (yyval.expr) = create(new UserFunctionCallsite((yyvsp[(1) - (4)].qName), (yyvsp[(3) - (4)].expressionList).count()), (yyloc), parseInfo);
             (yyval.expr)->setOperands((yyvsp[(3) - (4)].expressionList));
             parseInfo->userFunctionCallsites.append((yyval.expr));
         }
     }
     break;
   case 352:
 /* Line 1269 of yacc.c.  */
 #line 3668 "querytransformparser.ypp"
     {
         (yyval.expressionList) = Expression::List();
     }
     break;
   case 353:
 /* Line 1269 of yacc.c.  */
 #line 3673 "querytransformparser.ypp"
     {
         Expression::List list;
         list.append((yyvsp[(1) - (1)].expr));
         (yyval.expressionList) = list;
     }
     break;
   case 355:
 /* Line 1269 of yacc.c.  */
 #line 3682 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc));
     }
     break;
   case 360:
 /* Line 1269 of yacc.c.  */
 #line 3726 "querytransformparser.ypp"
     {
                         (yyval.enums.tokenizerPosition) = parseInfo->tokenizer->commenceScanOnly();
                         parseInfo->scanOnlyStack.push(true);
                     }
     break;
   case 361:
 /* Line 1269 of yacc.c.  */
 #line 3735 "querytransformparser.ypp"
     {
                         ++parseInfo->elementConstructorDepth;
                         Expression::List constructors;
                         parseInfo->resolvers.push(parseInfo->staticContext->namespaceBindings());
                         /* Fix up attributes and namespace declarations. */
                         const NamespaceResolver::Ptr resolver(new DelegatingNamespaceResolver(parseInfo->staticContext->namespaceBindings()));
                         const NamePool::Ptr namePool(parseInfo->staticContext->namePool());
                         const int len = (yyvsp[(4) - (4)].attributeHolders).size();
                         QSet<QXmlName::PrefixCode> usedDeclarations;
                         /* Whether xmlns="" has been encountered. */
                         bool hasDefaultDeclaration = false;
                         /* For each attribute & namespace declaration, do: */
                         for(int i = 0; i < len; ++i)
{
                             QString strLocalName;
                             QString strPrefix;
                             XPathHelper::splitQName((yyvsp[(4) - (4)].attributeHolders).at(i).first, strPrefix, strLocalName);
                             const QXmlName::PrefixCode prefix = namePool->allocatePrefix(strPrefix);
                             /* This can seem a bit weird. However, this name is ending up in a QXmlName
                              * which consider its prefix a... prefix. So, a namespace binding name can in some cases
                              * be a local name, but that's just as the initial syntactical construct. */
                             const QXmlName::LocalNameCode localName = namePool->allocatePrefix(strLocalName);
                             /* Not that localName is "foo" in "xmlns:foo" and that prefix is "xmlns". */
                             if(prefix == StandardPrefixes::xmlns ||
                                (prefix == StandardPrefixes::empty && localName == StandardPrefixes::xmlns))
{
                                 if(localName == StandardPrefixes::xmlns)
                                     hasDefaultDeclaration = true;
                                 /* We have a namespace declaration. */
                                 const Expression::Ptr nsExpr((yyvsp[(4) - (4)].attributeHolders).at(i).second);
                                 const QString strNamespace(nsExpr->is(Expression::IDEmptySequence) ? QString() : nsExpr->as<Literal>()->item().stringValue());
                                 const QXmlName::NamespaceCode ns = namePool->allocateNamespace(strNamespace);
                                 if(ns == StandardNamespaces::empty)
{
                                     if(localName != StandardPrefixes::xmlns)
{
                                         parseInfo->staticContext->error(QtXmlPatterns::tr("The namespace URI cannot be the empty string when binding to a prefix, %1.")
                                                                            .arg(formatURI(strPrefix)),
                                                                         ReportContext::XQST0085, fromYYLTYPE((yyloc), parseInfo));
                                     }
                                 }
                                 else if(!AnyURI::isValid(strNamespace))
{
                                     parseInfo->staticContext->error(QtXmlPatterns::tr("%1 is an invalid namespace URI.").arg(formatURI(strNamespace)),
                                                                     ReportContext::XQST0022, fromYYLTYPE((yyloc), parseInfo));
                                 }
                                 if(prefix == StandardPrefixes::xmlns && localName == StandardPrefixes::xmlns)
{
                                     parseInfo->staticContext->error(QtXmlPatterns::tr("It is not possible to bind to the prefix %1")
                                                                        .arg(formatKeyword("xmlns")),
                                                                     ReportContext::XQST0070, fromYYLTYPE((yyloc), parseInfo));
                                 }
                                 if(ns == StandardNamespaces::xml && localName != StandardPrefixes::xml)
{
                                     parseInfo->staticContext->error(QtXmlPatterns::tr("Namespace %1 can only be bound to %2 (and it is, in either case, pre-declared).")
                                                                        .arg(formatURI(namePool->stringForNamespace(StandardNamespaces::xml)))
                                                                        .arg(formatKeyword("xml")),
                                                                     ReportContext::XQST0070, fromYYLTYPE((yyloc), parseInfo));
                                 }
                                 if(localName == StandardPrefixes::xml && ns != StandardNamespaces::xml)
{
                                     parseInfo->staticContext->error(QtXmlPatterns::tr("Prefix %1 can only be bound to %2 (and it is, in either case, pre-declared).")
                                                                        .arg(formatKeyword("xml"))
                                                                        .arg(formatURI(namePool->stringForNamespace(StandardNamespaces::xml))),
                                                                     ReportContext::XQST0070, fromYYLTYPE((yyloc), parseInfo));
                                 }
                                 QXmlName nb;
                                 if(localName == StandardPrefixes::xmlns)
                                     nb = QXmlName(ns, StandardLocalNames::empty);
                                 else
                                     nb = QXmlName(ns, StandardLocalNames::empty, localName);
                                 if(usedDeclarations.contains(nb.prefix()))
{
                                     parseInfo->staticContext->error(QtXmlPatterns::tr("Two namespace declaration attributes have the same name: %1.")
                                                                        .arg(formatKeyword(namePool->stringForPrefix(nb.prefix()))),
                                                                     ReportContext::XQST0071, fromYYLTYPE((yyloc), parseInfo));
                                 }
                                 else
                                     usedDeclarations.insert(nb.prefix());
                                 /* If the user has bound the XML namespace correctly, we in either
                                  * case don't want to output it.
                                  *
                                  * We only have to check the namespace parts since the above checks has ensured
                                  * consistency in the prefix parts. */
                                 if(ns != StandardNamespaces::xml)
{
                                     /* We don't want default namespace declarations when the
                                      * default namespace already is empty. */
                                     if(!(ns == StandardNamespaces::empty          &&
                                          localName == StandardNamespaces::xmlns   &&
                                          resolver->lookupNamespaceURI(StandardPrefixes::empty) == StandardNamespaces::empty))
{
                                         constructors.append(create(new NamespaceConstructor(nb), (yyloc), parseInfo));
                                         resolver->addBinding(nb);
                                     }
                                 }
                             }
                         }
                         if(parseInfo->elementConstructorDepth == 1 && !hasDefaultDeclaration)
{
                             /* TODO But mostly this isn't needed, since the default element
                              * namespace is empty? How does this at all work? */
                             const QXmlName def(resolver->lookupNamespaceURI(StandardPrefixes::empty), StandardLocalNames::empty);
                             constructors.append(create(new NamespaceConstructor(def), (yyloc), parseInfo));
                         }
                         parseInfo->staticContext->setNamespaceBindings(resolver);
                         (yyval.expressionList) = constructors;
                         /* Resolve the name of the element, now that the namespace attributes are read. */
{
                             const ReflectYYLTYPE ryy((yyloc), parseInfo);
                             const QXmlName ele = QNameConstructor::expandQName<StaticContext::Ptr,
                                                                                ReportContext::XPST0081,
                                                                                ReportContext::XPST0081>((yyvsp[(2) - (4)].sval), parseInfo->staticContext, resolver, &ryy);
                             parseInfo->tagStack.push(ele);
                         }
                         parseInfo->tokenizer->resumeTokenizationFrom((yyvsp[(3) - (4)].enums.tokenizerPosition));
                     }
     break;
   case 362:
 /* Line 1269 of yacc.c.  */
 #line 3881 "querytransformparser.ypp"
     {
         /* We add the content constructor after the attribute constructors. This might result
          * in nested ExpressionSequences, but it will be optimized away later on. */
         Expression::List attributes((yyvsp[(5) - (8)].expressionList));
         const NamePool::Ptr namePool(parseInfo->staticContext->namePool());
         const int len = (yyvsp[(7) - (8)].attributeHolders).size();
         QSet<QXmlName> declaredAttributes;
         declaredAttributes.reserve(len);
         /* For each namespace, resolve its name(now that we have resolved the namespace declarations) and
          * turn it into an attribute constructor. */
         for(int i = 0; i < len; ++i)
         {
             QString strLocalName;
             QString strPrefix;
             XPathHelper::splitQName((yyvsp[(7) - (8)].attributeHolders).at(i).first, strPrefix, strLocalName);
             const QXmlName::PrefixCode prefix = namePool->allocatePrefix(strPrefix);
             const QXmlName::LocalNameCode localName = namePool->allocateLocalName(strLocalName);
             if(prefix == StandardPrefixes::xmlns ||
                (prefix == StandardPrefixes::empty && localName == StandardLocalNames::xmlns))
             {
                 const Expression::ID id = (yyvsp[(7) - (8)].attributeHolders).at(i).second->id();
                 if(id == Expression::IDStringValue || id == Expression::IDEmptySequence)
                 {
                     /* It's a namespace declaration, and we've already handled those above. */
                     continue;
                 }
                 else
                 {
                     parseInfo->staticContext->error(QtXmlPatterns::tr("The namespace URI must be a constant and cannot "
                                                        "use enclosed expressions."),
                                                     ReportContext::XQST0022, fromYYLTYPE((yyloc), parseInfo));
                 }
             }
             else
             {
                 const ReflectYYLTYPE ryy((yyloc), parseInfo);
                 const QXmlName att = QNameConstructor::expandQName<StaticContext::Ptr,
                                                                    ReportContext::XPST0081,
                                                                    ReportContext::XPST0081>((yyvsp[(7) - (8)].attributeHolders).at(i).first, parseInfo->staticContext,
                                                                                             parseInfo->staticContext->namespaceBindings(),
                                                                                             &ryy, true);
                 if(declaredAttributes.contains(att))
                 {
                     parseInfo->staticContext->error(QtXmlPatterns::tr("An attribute with name %1 has already appeared on this element.")
                                                       .arg(formatKeyword(parseInfo->staticContext->namePool(), att)),
                                             ReportContext::XQST0040, fromYYLTYPE((yyloc), parseInfo));
                 }
                 else
                     declaredAttributes.insert(att);
                 /* wrapLiteral() needs the SourceLocationReflection of the AttributeConstructor, but
                  * it's unknown inside the arguments to its constructor. Hence we have to do this workaround of setting
                  * it twice.
                  *
                  * The AttributeConstructor's arguments are just dummies. */
                 const Expression::Ptr ctor(create(new AttributeConstructor((yyvsp[(7) - (8)].attributeHolders).at(i).second, (yyvsp[(7) - (8)].attributeHolders).at(i).second), (yyloc), parseInfo));
                 Expression::List ops;
                 ops.append(wrapLiteral(toItem(QNameValue::fromValue(namePool, att)), parseInfo->staticContext, ctor.data()));
                 ops.append((yyvsp[(7) - (8)].attributeHolders).at(i).second);
                 ctor->setOperands(ops);
                 attributes.append(ctor);
             }
         }
         Expression::Ptr contentOp;
         if(attributes.isEmpty())
             contentOp = (yyvsp[(8) - (8)].expr);
         else
         {
             attributes.append((yyvsp[(8) - (8)].expr));
             contentOp = create(new ExpressionSequence(attributes), (yyloc), parseInfo);
         }
         const Expression::Ptr name(create(new Literal(toItem(QNameValue::fromValue(parseInfo->staticContext->namePool(), parseInfo->tagStack.top()))), (yyloc), parseInfo));
         (yyval.expr) = create(new ElementConstructor(name, contentOp, parseInfo->isXSLT()), (yyloc), parseInfo);
         /* Restore the old context. We don't want the namespaces
          * to be in-scope for expressions appearing after the
          * element they appeared on. */
         parseInfo->staticContext->setNamespaceBindings(parseInfo->resolvers.pop());
         parseInfo->tagStack.pop();
         --parseInfo->elementConstructorDepth;
     }
     break;
   case 363:
 /* Line 1269 of yacc.c.  */
 #line 3977 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new EmptySequence(), (yyloc), parseInfo);
     }
     break;
   case 364:
 /* Line 1269 of yacc.c.  */
 #line 3981 "querytransformparser.ypp"
     {
         if(!(yyvsp[(4) - (5)].qName).isLexicallyEqual(parseInfo->tagStack.top()))
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("A direct element constructor is not "
                                                "well-formed. %1 is ended with %2.")
                                                .arg(formatKeyword(parseInfo->staticContext->namePool()->toLexical(parseInfo->tagStack.top())),
                                                     formatKeyword(parseInfo->staticContext->namePool()->toLexical((yyvsp[(4) - (5)].qName)))),
                                             ReportContext::XPST0003, fromYYLTYPE((yyloc), parseInfo));
         }
         if((yyvsp[(2) - (5)].expressionList).isEmpty())
             (yyval.expr) = create(new EmptySequence(), (yyloc), parseInfo);
         else if((yyvsp[(2) - (5)].expressionList).size() == 1)
             (yyval.expr) = (yyvsp[(2) - (5)].expressionList).first();
         else
             (yyval.expr) = create(new ExpressionSequence((yyvsp[(2) - (5)].expressionList)), (yyloc), parseInfo);
     }
     break;
   case 365:
 /* Line 1269 of yacc.c.  */
 #line 4000 "querytransformparser.ypp"
     {
         (yyval.attributeHolders) = AttributeHolderVector();
     }
     break;
   case 366:
 /* Line 1269 of yacc.c.  */
 #line 4004 "querytransformparser.ypp"
     {
         (yyvsp[(1) - (2)].attributeHolders).append((yyvsp[(2) - (2)].attributeHolder));
         (yyval.attributeHolders) = (yyvsp[(1) - (2)].attributeHolders);
     }
     break;
   case 367:
 /* Line 1269 of yacc.c.  */
 #line 4010 "querytransformparser.ypp"
     {
         (yyval.attributeHolder) = qMakePair((yyvsp[(1) - (3)].sval), (yyvsp[(3) - (3)].expr));
     }
     break;
   case 368:
 /* Line 1269 of yacc.c.  */
 #line 4015 "querytransformparser.ypp"
     {
         (yyval.expr) = createDirAttributeValue((yyvsp[(2) - (3)].expressionList), parseInfo, (yyloc));
     }
     break;
   case 369:
 /* Line 1269 of yacc.c.  */
 #line 4020 "querytransformparser.ypp"
     {
         (yyval.expr) = createDirAttributeValue((yyvsp[(2) - (3)].expressionList), parseInfo, (yyloc));
     }
     break;
   case 370:
 /* Line 1269 of yacc.c.  */
 #line 4025 "querytransformparser.ypp"
     {
         (yyval.expressionList) = Expression::List();
     }
     break;
   case 371:
 /* Line 1269 of yacc.c.  */
 #line 4029 "querytransformparser.ypp"
     {
         Expression::Ptr content((yyvsp[(1) - (2)].expr));
         if(parseInfo->isBackwardsCompat.top())
             content = create(GenericPredicate::createFirstItem(content), (yyloc), parseInfo);
         (yyvsp[(2) - (2)].expressionList).prepend(createSimpleContent(content, (yyloc), parseInfo));
         (yyval.expressionList) = (yyvsp[(2) - (2)].expressionList);
     }
     break;
   case 372:
 /* Line 1269 of yacc.c.  */
 #line 4039 "querytransformparser.ypp"
     {
         (yyvsp[(2) - (2)].expressionList).prepend(create(new Literal(AtomicString::fromValue((yyvsp[(1) - (2)].sval))), (yyloc), parseInfo));
         (yyval.expressionList) = (yyvsp[(2) - (2)].expressionList);
     }
     break;
   case 373:
 /* Line 1269 of yacc.c.  */
 #line 4045 "querytransformparser.ypp"
     {
         (yyval.expressionList) = Expression::List();
         parseInfo->isPreviousEnclosedExpr = false;
     }
     break;
   case 374:
 /* Line 1269 of yacc.c.  */
 #line 4050 "querytransformparser.ypp"
     {
         (yyvsp[(1) - (2)].expressionList).append((yyvsp[(2) - (2)].expr));
         (yyval.expressionList) = (yyvsp[(1) - (2)].expressionList);
         parseInfo->isPreviousEnclosedExpr = false;
     }
     break;
   case 375:
 /* Line 1269 of yacc.c.  */
 #line 4056 "querytransformparser.ypp"
     {
         if(parseInfo->staticContext->boundarySpacePolicy() == StaticContext::BSPStrip &&
            XPathHelper::isWhitespaceOnly((yyvsp[(2) - (2)].sval)))
         {
             (yyval.expressionList) = (yyvsp[(1) - (2)].expressionList);
         }
         else
         {
             (yyvsp[(1) - (2)].expressionList).append(create(new TextNodeConstructor(create(new Literal(AtomicString::fromValue((yyvsp[(2) - (2)].sval))), (yyloc), parseInfo)), (yyloc), parseInfo));
             (yyval.expressionList) = (yyvsp[(1) - (2)].expressionList);
             parseInfo->isPreviousEnclosedExpr = false;
         }
     }
     break;
   case 376:
 /* Line 1269 of yacc.c.  */
 #line 4070 "querytransformparser.ypp"
     {
         (yyvsp[(1) - (2)].expressionList).append(create(new TextNodeConstructor(create(new Literal(AtomicString::fromValue((yyvsp[(2) - (2)].sval))), (yyloc), parseInfo)), (yyloc), parseInfo));
         (yyval.expressionList) = (yyvsp[(1) - (2)].expressionList);
         parseInfo->isPreviousEnclosedExpr = false;
     }
     break;
   case 377:
 /* Line 1269 of yacc.c.  */
 #line 4076 "querytransformparser.ypp"
     {
         /* We insert a text node constructor that send an empty text node between
          * the two enclosed expressions, in order to ensure that no space is inserted.
          *
          * However, we only do it when we have no node constructors. */
         if(parseInfo->isPreviousEnclosedExpr &&
            BuiltinTypes::xsAnyAtomicType->xdtTypeMatches((yyvsp[(2) - (2)].expr)->staticType()->itemType()) &&
            BuiltinTypes::xsAnyAtomicType->xdtTypeMatches((yyvsp[(1) - (2)].expressionList).last()->staticType()->itemType()))
             (yyvsp[(1) - (2)].expressionList).append(create(new TextNodeConstructor(create(new Literal(AtomicString::fromValue(QString())), (yyloc), parseInfo)), (yyloc), parseInfo));
         else
             parseInfo->isPreviousEnclosedExpr = true;
         (yyvsp[(1) - (2)].expressionList).append(createCopyOf((yyvsp[(2) - (2)].expr), parseInfo, (yyloc)));
         (yyval.expressionList) = (yyvsp[(1) - (2)].expressionList);
     }
     break;
   case 378:
 /* Line 1269 of yacc.c.  */
 #line 4093 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new CommentConstructor(create(new Literal(AtomicString::fromValue((yyvsp[(2) - (2)].sval))), (yyloc), parseInfo)), (yyloc), parseInfo);
     }
     break;
   case 379:
 /* Line 1269 of yacc.c.  */
 #line 4098 "querytransformparser.ypp"
     {
         const ReflectYYLTYPE ryy((yyloc), parseInfo);
         NCNameConstructor::validateTargetName<StaticContext::Ptr,
                                               ReportContext::XPST0003,
                                               ReportContext::XPST0003>((yyvsp[(2) - (3)].sval),
                                                                        parseInfo->staticContext, &ryy);
         (yyval.expr) = create(new ProcessingInstructionConstructor(
                              create(new Literal(AtomicString::fromValue((yyvsp[(2) - (3)].sval))), (yyloc), parseInfo),
                              create(new Literal(AtomicString::fromValue((yyvsp[(3) - (3)].sval))), (yyloc), parseInfo)), (yyloc), parseInfo);
     }
     break;
   case 387:
 /* Line 1269 of yacc.c.  */
 #line 4119 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc), (yyvsp[(2) - (3)].enums.Bool));
         (yyval.expr) = create(new DocumentConstructor((yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
     }
     break;
   case 388:
 /* Line 1269 of yacc.c.  */
 #line 4126 "querytransformparser.ypp"
     {
                         /* This value is incremented before the action below is executed. */
                         ++parseInfo->elementConstructorDepth;
                      }
     break;
   case 389:
 /* Line 1269 of yacc.c.  */
 #line 4131 "querytransformparser.ypp"
     {
         Q_ASSERT(5);
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc), (yyvsp[(2) - (5)].enums.Bool));
         Expression::Ptr effExpr;
         if((yyvsp[(5) - (5)].expr))
             effExpr = createCopyOf((yyvsp[(5) - (5)].expr), parseInfo, (yyloc));
         else
             effExpr = create(new EmptySequence(), (yyloc), parseInfo);
         const QXmlName::NamespaceCode ns = parseInfo->resolvers.top()->lookupNamespaceURI(StandardPrefixes::empty);
         /* Ensure the default namespace gets counted as an in-scope binding, if such a one exists. If we're
          * a child of another constructor, it has already been done. */
         if(parseInfo->elementConstructorDepth == 1 && ns != StandardNamespaces::empty)
         {
             Expression::List exprList;
             /* We append the namespace constructor before the body, in order to
              * comply with QAbstractXmlPushHandler's contract. */
             const QXmlName def(parseInfo->resolvers.top()->lookupNamespaceURI(StandardPrefixes::empty), StandardLocalNames::empty);
             exprList.append(create(new NamespaceConstructor(def), (yyloc), parseInfo));
             exprList.append(effExpr);
             effExpr = create(new ExpressionSequence(exprList), (yyloc), parseInfo);
         }
         --parseInfo->elementConstructorDepth;
         (yyval.expr) = create(new ElementConstructor((yyvsp[(3) - (5)].expr), effExpr, parseInfo->isXSLT()), (yyloc), parseInfo);
     }
     break;
   case 390:
 /* Line 1269 of yacc.c.  */
 #line 4165 "querytransformparser.ypp"
     {
         (yyval.enums.Bool) = false;
     }
     break;
   case 391:
 /* Line 1269 of yacc.c.  */
 #line 4169 "querytransformparser.ypp"
     {
         (yyval.enums.Bool) = true;
     }
     break;
   case 392:
 /* Line 1269 of yacc.c.  */
 #line 4177 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc), (yyvsp[(2) - (4)].enums.Bool));
         const Expression::Ptr name(create(new AttributeNameValidator((yyvsp[(3) - (4)].expr)), (yyloc), parseInfo));
         if((yyvsp[(4) - (4)].expr))
             (yyval.expr) = create(new AttributeConstructor(name, createSimpleContent((yyvsp[(4) - (4)].expr), (yyloc), parseInfo)), (yyloc), parseInfo);
         else
             (yyval.expr) = create(new AttributeConstructor(name, create(new EmptySequence(), (yyloc), parseInfo)), (yyloc), parseInfo);
     }
     break;
   case 393:
 /* Line 1269 of yacc.c.  */
 #line 4189 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new TextNodeConstructor(createSimpleContent((yyvsp[(3) - (3)].expr), (yyloc), parseInfo)), (yyloc), parseInfo);
     }
     break;
   case 394:
 /* Line 1269 of yacc.c.  */
 #line 4194 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc), (yyvsp[(2) - (3)].enums.Bool));
         (yyval.expr) = create(new CommentConstructor(createSimpleContent((yyvsp[(3) - (3)].expr), (yyloc), parseInfo)), (yyloc), parseInfo);
     }
     break;
   case 395:
 /* Line 1269 of yacc.c.  */
 #line 4201 "querytransformparser.ypp"
     {
         allowedIn(QXmlQuery::XQuery10, parseInfo, (yyloc), (yyvsp[(2) - (3)].expr));
         if((yyvsp[(3) - (3)].expr))
         {
             (yyval.expr) = create(new ProcessingInstructionConstructor((yyvsp[(2) - (3)].expr), createSimpleContent((yyvsp[(3) - (3)].expr), (yyloc), parseInfo)), (yyloc), parseInfo);
         }
         else
             (yyval.expr) = create(new ProcessingInstructionConstructor((yyvsp[(2) - (3)].expr), create(new EmptySequence(), (yyloc), parseInfo)), (yyloc), parseInfo);
     }
     break;
   case 396:
 /* Line 1269 of yacc.c.  */
 #line 4212 "querytransformparser.ypp"
     {
                         parseInfo->nodeTestSource = BuiltinTypes::attribute;
                    }
     break;
   case 397:
 /* Line 1269 of yacc.c.  */
 #line 4216 "querytransformparser.ypp"
     {
                         parseInfo->restoreNodeTestSource();
                    }
     break;
   case 398:
 /* Line 1269 of yacc.c.  */
 #line 4219 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new Literal(toItem(QNameValue::fromValue(parseInfo->staticContext->namePool(), (yyvsp[(2) - (3)].qName)))), (yyloc), parseInfo);
     }
     break;
   case 400:
 /* Line 1269 of yacc.c.  */
 #line 4225 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new Literal(toItem(QNameValue::fromValue(parseInfo->staticContext->namePool(), (yyvsp[(1) - (1)].qName)))), (yyloc), parseInfo);
     }
     break;
   case 402:
 /* Line 1269 of yacc.c.  */
 #line 4231 "querytransformparser.ypp"
     {
         if(BuiltinTypes::xsQName->xdtTypeMatches((yyvsp[(1) - (1)].expr)->staticType()->itemType()))
             (yyval.expr) = (yyvsp[(1) - (1)].expr);
         else
         {
             (yyval.expr) = create(new QNameConstructor((yyvsp[(1) - (1)].expr),
                                              parseInfo->staticContext->namespaceBindings()),
                         (yyloc), parseInfo);
         }
     }
     break;
   case 403:
 /* Line 1269 of yacc.c.  */
 #line 4246 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new NCNameConstructor(create(new Literal(AtomicString::fromValue((yyvsp[(1) - (1)].sval))), (yyloc), parseInfo)), (yyloc), parseInfo);
     }
     break;
   case 404:
 /* Line 1269 of yacc.c.  */
 #line 4250 "querytransformparser.ypp"
     {
         (yyval.expr) = create(new NCNameConstructor((yyvsp[(1) - (1)].expr)), (yyloc), parseInfo);
     }
     break;
   case 405:
 /* Line 1269 of yacc.c.  */
 #line 4259 "querytransformparser.ypp"
     {
     (yyval.expr) = create(new ComputedNamespaceConstructor((yyvsp[(2) - (3)].expr), (yyvsp[(3) - (3)].expr)), (yyloc), parseInfo);
 }
     break;
   case 406:
 /* Line 1269 of yacc.c.  */
 #line 4264 "querytransformparser.ypp"
     {
         (yyval.sequenceType) = makeGenericSequenceType((yyvsp[(1) - (1)].itemType), Cardinality::exactlyOne());
     }
     break;
   case 407:
 /* Line 1269 of yacc.c.  */
 #line 4268 "querytransformparser.ypp"
     {
         (yyval.sequenceType) = makeGenericSequenceType((yyvsp[(1) - (2)].itemType), Cardinality::zeroOrOne());
     }
     break;
   case 408:
 /* Line 1269 of yacc.c.  */
 #line 4273 "querytransformparser.ypp"
     {
         (yyval.sequenceType) = CommonSequenceTypes::ZeroOrMoreItems;
     }
     break;
   case 409:
 /* Line 1269 of yacc.c.  */
 #line 4277 "querytransformparser.ypp"
     {
         (yyval.sequenceType) = (yyvsp[(2) - (2)].sequenceType);
     }
     break;
   case 410:
 /* Line 1269 of yacc.c.  */
 #line 4282 "querytransformparser.ypp"
     {
         (yyval.sequenceType) = makeGenericSequenceType((yyvsp[(1) - (2)].itemType), (yyvsp[(2) - (2)].cardinality));
     }
     break;
   case 411:
 /* Line 1269 of yacc.c.  */
 #line 4287 "querytransformparser.ypp"
     {
         (yyval.sequenceType) = CommonSequenceTypes::Empty;
     }
     break;
   case 412:
 /* Line 1269 of yacc.c.  */
 #line 4291 "querytransformparser.ypp"
     {(yyval.cardinality) = Cardinality::exactlyOne();}
     break;
   case 413:
 /* Line 1269 of yacc.c.  */
 #line 4292 "querytransformparser.ypp"
     {(yyval.cardinality) = Cardinality::oneOrMore();}
     break;
   case 414:
 /* Line 1269 of yacc.c.  */
 #line 4293 "querytransformparser.ypp"
     {(yyval.cardinality) = Cardinality::zeroOrMore();}
     break;
   case 415:
 /* Line 1269 of yacc.c.  */
 #line 4294 "querytransformparser.ypp"
     {(yyval.cardinality) = Cardinality::zeroOrOne();}
     break;
   case 419:
 /* Line 1269 of yacc.c.  */
 #line 4300 "querytransformparser.ypp"
     {
         (yyval.itemType) = BuiltinTypes::item;
     }
     break;
   case 420:
 /* Line 1269 of yacc.c.  */
 #line 4305 "querytransformparser.ypp"
     {
         const SchemaType::Ptr t(parseInfo->staticContext->schemaDefinitions()->createSchemaType((yyvsp[(1) - (1)].qName)));
         if(!t)
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("The name %1 does not refer to any schema type.")
                                                .arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(1) - (1)].qName))), ReportContext::XPST0051, fromYYLTYPE((yyloc), parseInfo));
         }
         else if(BuiltinTypes::xsAnyAtomicType->wxsTypeMatches(t))
             (yyval.itemType) = AtomicType::Ptr(t);
         else
         {
             /* Try to give an intelligent message. */
             if(t->isComplexType())
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("%1 is an complex type. Casting to complex "
                                                    "types is not possible. However, casting "
                                                    "to atomic types such as %2 works.")
                                                    .arg(formatType(parseInfo->staticContext->namePool(), t))
                                                    .arg(formatType(parseInfo->staticContext->namePool(), BuiltinTypes::xsInteger)),
                                                 ReportContext::XPST0051, fromYYLTYPE((yyloc), parseInfo));
             }
             else
             {
                 parseInfo->staticContext->error(QtXmlPatterns::tr("%1 is not an atomic type. Casting "
                                                    "is only possible to atomic types.")
                                                    .arg(formatType(parseInfo->staticContext->namePool(), t)),
                                                 ReportContext::XPST0051, fromYYLTYPE((yyloc), parseInfo));
             }
         }
     }
     break;
   case 428:
 /* Line 1269 of yacc.c.  */
 #line 4349 "querytransformparser.ypp"
     {
         (yyval.itemType) = BuiltinTypes::node;
     }
     break;
   case 429:
 /* Line 1269 of yacc.c.  */
 #line 4354 "querytransformparser.ypp"
     {
         (yyval.itemType) = BuiltinTypes::document;
     }
     break;
   case 430:
 /* Line 1269 of yacc.c.  */
 #line 4359 "querytransformparser.ypp"
     {
         // TODO support for document element testing
         (yyval.itemType) = BuiltinTypes::document;
     }
     break;
   case 433:
 /* Line 1269 of yacc.c.  */
 #line 4368 "querytransformparser.ypp"
     {
         (yyval.itemType) = BuiltinTypes::text;
     }
     break;
   case 434:
 /* Line 1269 of yacc.c.  */
 #line 4373 "querytransformparser.ypp"
     {
         (yyval.itemType) = BuiltinTypes::comment;
     }
     break;
   case 435:
 /* Line 1269 of yacc.c.  */
 #line 4378 "querytransformparser.ypp"
     {
         (yyval.itemType) = BuiltinTypes::pi;
     }
     break;
   case 436:
 /* Line 1269 of yacc.c.  */
 #line 4383 "querytransformparser.ypp"
     {
         (yyval.itemType) = LocalNameTest::create(BuiltinTypes::pi, parseInfo->staticContext->namePool()->allocateLocalName((yyvsp[(3) - (4)].sval)));
     }
     break;
   case 437:
 /* Line 1269 of yacc.c.  */
 #line 4388 "querytransformparser.ypp"
     {
         if(QXmlUtils::isNCName((yyvsp[(3) - (4)].sval)))
         {
             (yyval.itemType) = LocalNameTest::create(BuiltinTypes::pi, parseInfo->staticContext->namePool()->allocateLocalName((yyvsp[(3) - (4)].sval)));
         }
         else
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("%1 is not a valid name for a "
                                                               "processing-instruction.")
                                                  .arg(formatKeyword((yyvsp[(3) - (4)].sval))),
                                             ReportContext::XPTY0004,
                                             fromYYLTYPE((yyloc), parseInfo));
         }
     }
     break;
   case 440:
 /* Line 1269 of yacc.c.  */
 #line 4407 "querytransformparser.ypp"
     {
         (yyval.itemType) = BuiltinTypes::attribute;
     }
     break;
   case 441:
 /* Line 1269 of yacc.c.  */
 #line 4412 "querytransformparser.ypp"
     {
         (yyval.itemType) = BuiltinTypes::attribute;
     }
     break;
   case 442:
 /* Line 1269 of yacc.c.  */
 #line 4417 "querytransformparser.ypp"
     {
         (yyval.itemType) = QNameTest::create(BuiltinTypes::attribute, (yyvsp[(3) - (4)].qName));
     }
     break;
   case 443:
 /* Line 1269 of yacc.c.  */
 #line 4421 "querytransformparser.ypp"
     {
         const SchemaType::Ptr t(parseInfo->staticContext->schemaDefinitions()->createSchemaType((yyvsp[(5) - (6)].qName)));
         if(t)
             (yyval.itemType) = BuiltinTypes::attribute;
         else
         {
             parseInfo->staticContext->error(unknownType().arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(5) - (6)].qName))),
                                             ReportContext::XPST0008, fromYYLTYPE((yyloc), parseInfo));
         }
     }
     break;
   case 444:
 /* Line 1269 of yacc.c.  */
 #line 4433 "querytransformparser.ypp"
     {
         const SchemaType::Ptr t(parseInfo->staticContext->schemaDefinitions()->createSchemaType((yyvsp[(5) - (6)].qName)));
         if(t)
             (yyval.itemType) = BuiltinTypes::attribute;
         else
         {
             parseInfo->staticContext->error(unknownType().arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(5) - (6)].qName))),
                                             ReportContext::XPST0008, fromYYLTYPE((yyloc), parseInfo));
         }
     }
     break;
   case 445:
 /* Line 1269 of yacc.c.  */
 #line 4446 "querytransformparser.ypp"
     {
         parseInfo->staticContext->error(QtXmlPatterns::tr("%1 is not in the in-scope attribute "
                                            "declarations. Note that the schema import "
                                            "feature is not supported.")
                                            .arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(3) - (4)].qName))),
                                         ReportContext::XPST0008, fromYYLTYPE((yyloc), parseInfo));
         (yyval.itemType).reset();
     }
     break;
   case 446:
 /* Line 1269 of yacc.c.  */
 #line 4456 "querytransformparser.ypp"
     {
         (yyval.itemType) = BuiltinTypes::element;
     }
     break;
   case 447:
 /* Line 1269 of yacc.c.  */
 #line 4461 "querytransformparser.ypp"
     {
         (yyval.itemType) = BuiltinTypes::element;
     }
     break;
   case 448:
 /* Line 1269 of yacc.c.  */
 #line 4466 "querytransformparser.ypp"
     {
         (yyval.itemType) = QNameTest::create(BuiltinTypes::element, (yyvsp[(3) - (4)].qName));
     }
     break;
   case 449:
 /* Line 1269 of yacc.c.  */
 #line 4471 "querytransformparser.ypp"
     {
         const SchemaType::Ptr t(parseInfo->staticContext->schemaDefinitions()->createSchemaType((yyvsp[(5) - (7)].qName)));
         if(t)
             (yyval.itemType) = BuiltinTypes::element;
         else
         {
             parseInfo->staticContext->error(unknownType()
                                                .arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(5) - (7)].qName))),
                                             ReportContext::XPST0008, fromYYLTYPE((yyloc), parseInfo));
         }
     }
     break;
   case 450:
 /* Line 1269 of yacc.c.  */
 #line 4485 "querytransformparser.ypp"
     {
         const SchemaType::Ptr t(parseInfo->staticContext->schemaDefinitions()->createSchemaType((yyvsp[(5) - (7)].qName)));
         if(t)
             (yyval.itemType) = BuiltinTypes::element;
         else
         {
             parseInfo->staticContext->error(QtXmlPatterns::tr("%1 is an unknown schema type.")
                                                .arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(5) - (7)].qName))),
                                             ReportContext::XPST0008, fromYYLTYPE((yyloc), parseInfo));
         }
     }
     break;
   case 453:
 /* Line 1269 of yacc.c.  */
 #line 4502 "querytransformparser.ypp"
     {
         parseInfo->staticContext->error(QtXmlPatterns::tr("%1 is not in the in-scope attribute "
                                            "declarations. Note that the schema import "
                                            "feature is not supported.")
                                            .arg(formatKeyword(parseInfo->staticContext->namePool(), (yyvsp[(3) - (4)].qName))),
                                         ReportContext::XPST0008, fromYYLTYPE((yyloc), parseInfo));
         (yyval.itemType).reset();
     }
     break;
   case 455:
 /* Line 1269 of yacc.c.  */
 #line 4514 "querytransformparser.ypp"
     {
         (yyval.qName) = parseInfo->staticContext->namePool()->allocateQName(StandardNamespaces::empty, (yyvsp[(1) - (1)].sval));
     }
     break;
   case 457:
 /* Line 1269 of yacc.c.  */
 #line 4526 "querytransformparser.ypp"
     {
         if(parseInfo->nodeTestSource == BuiltinTypes::element)
             (yyval.qName) = parseInfo->staticContext->namePool()->allocateQName(parseInfo->staticContext->namespaceBindings()->lookupNamespaceURI(StandardPrefixes::empty), (yyvsp[(1) - (1)].sval));
         else
             (yyval.qName) = parseInfo->staticContext->namePool()->allocateQName(StandardNamespaces::empty, (yyvsp[(1) - (1)].sval));
     }
     break;
   case 462:
 /* Line 1269 of yacc.c.  */
 #line 4540 "querytransformparser.ypp"
     {
         (yyval.qName) = parseInfo->staticContext->namePool()->allocateQName(parseInfo->staticContext->defaultFunctionNamespace(), (yyvsp[(1) - (1)].sval));
     }
     break;
   case 463:
 /* Line 1269 of yacc.c.  */
 #line 4544 "querytransformparser.ypp"
     {
         (yyval.qName) = parseInfo->staticContext->namePool()->allocateQName(StandardNamespaces::InternalXSLT, (yyvsp[(2) - (2)].sval));
     }
     break;
   case 466:
 /* Line 1269 of yacc.c.  */
 #line 4552 "querytransformparser.ypp"
     {
         parseInfo->staticContext->error(QtXmlPatterns::tr("The name of an extension expression must be in "
                                                           "a namespace."),
                                         ReportContext::XPST0081, fromYYLTYPE((yyloc), parseInfo));
     }
     break;
   case 469:
 /* Line 1269 of yacc.c.  */
 #line 4562 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
     }
     break;
   case 470:
 /* Line 1269 of yacc.c.  */
 #line 4566 "querytransformparser.ypp"
     {
         allowedIn(QueryLanguages(QXmlQuery::XQuery10 | QXmlQuery::XPath20), parseInfo, (yyloc));
     }
     break;
   case 471:
 /* Line 1269 of yacc.c.  */
 #line 4571 "querytransformparser.ypp"
     {
         const ReflectYYLTYPE ryy((yyloc), parseInfo);
         (yyval.qName) = QNameConstructor::
              expandQName<StaticContext::Ptr,
                          ReportContext::XPST0081,
                          ReportContext::XPST0081>((yyvsp[(1) - (1)].sval), parseInfo->staticContext,
                                                   parseInfo->staticContext->namespaceBindings(), &ryy);
     }
     break;
   case 472:
 /* Line 1269 of yacc.c.  */
 #line 4583 "querytransformparser.ypp"
     {
         (yyval.qName) = parseInfo->staticContext->namePool()->fromClarkName((yyvsp[(1) - (1)].sval));
     }
     break;
 /* Line 1269 of yacc.c.  */
 #line 7763 "qquerytransformparser.cpp"
       default: break;
     }
   YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   *++yyvsp = yyval;
   *++yylsp = yyloc;
   /* Now `shift' the result of the reduction.  Determine what state
      that goes to, based on the state we popped back to and the rule
      number reduced by.  */
   yyn = yyr1[yyn];
   yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
   if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
     yystate = yytable[yystate];
   else
     yystate = yydefgoto[yyn - YYNTOKENS];
   goto yynewstate;
 /*------------------------------------.
 | yyerrlab -- here on detecting error |
 `------------------------------------*/
 yyerrlab:
   /* If not already recovering from an error, report this error.  */
   if (!yyerrstatus)
     {
       ++yynerrs;
 #if ! YYERROR_VERBOSE
       yyerror (&yylloc, parseInfo, YY_("syntax error"));
 #else
       {
     YYSIZE_T yysize = yysyntax_error (0, yystate, yychar);
     if (yymsg_alloc < yysize && yymsg_alloc < YYSTACK_ALLOC_MAXIMUM)
       {
         YYSIZE_T yyalloc = 2 * yysize;
         if (! (yysize <= yyalloc && yyalloc <= YYSTACK_ALLOC_MAXIMUM))
           yyalloc = YYSTACK_ALLOC_MAXIMUM;
         if (yymsg != yymsgbuf)
           YYSTACK_FREE (yymsg);
         yymsg = (char *) YYSTACK_ALLOC (yyalloc);
         if (yymsg)
           yymsg_alloc = yyalloc;
         else
           {
         yymsg = yymsgbuf;
         yymsg_alloc = sizeof yymsgbuf;
           }
       }
     if (0 < yysize && yysize <= yymsg_alloc)
       {
         (void) yysyntax_error (yymsg, yystate, yychar);
         yyerror (&yylloc, parseInfo, yymsg);
       }
     else
       {
         yyerror (&yylloc, parseInfo, YY_("syntax error"));
         if (yysize != 0)
           goto yyexhaustedlab;
       }
       }
 #endif
     }
   yyerror_range[0] = yylloc;
   if (yyerrstatus == 3)
     {
       /* If just tried and failed to reuse lookahead token after an
      error, discard it.  */
       if (yychar <= YYEOF)
     {
       /* Return failure if at end of input.  */
       if (yychar == YYEOF)
         YYABORT;
     }
       else
     {
       yydestruct ("Error: discarding",
               yytoken, &yylval, &yylloc, parseInfo);
       yychar = YYEMPTY;
     }
     }
   /* Else will try to reuse lookahead token after shifting the error
      token.  */
   goto yyerrlab1;
 /*---------------------------------------------------.
 | yyerrorlab -- error raised explicitly by YYERROR.  |
 `---------------------------------------------------*/
 yyerrorlab:
   /* Pacify compilers like GCC when the user code never invokes
      YYERROR and the label yyerrorlab therefore never appears in user
      code.  */
   if (/*CONSTCOND*/ 0)
      goto yyerrorlab;
   yyerror_range[0] = yylsp[1-yylen];
   /* Do not reclaim the symbols of the rule which action triggered
      this YYERROR.  */
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   yystate = *yyssp;
   goto yyerrlab1;
 /*-------------------------------------------------------------.
 | yyerrlab1 -- common code for both syntax error and YYERROR.  |
 `-------------------------------------------------------------*/
 yyerrlab1:
   yyerrstatus = 3;  /* Each real token shifted decrements this.  */
   for (;;)
     {
       yyn = yypact[yystate];
       if (yyn != YYPACT_NINF)
     {
       yyn += YYTERROR;
       if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
         {
           yyn = yytable[yyn];
           if (0 < yyn)
         break;
         }
     }
       /* Pop the current state because it cannot handle the error token.  */
       if (yyssp == yyss)
     YYABORT;
       yyerror_range[0] = *yylsp;
       yydestruct ("Error: popping",
           yystos[yystate], yyvsp, yylsp, parseInfo);
       YYPOPSTACK (1);
       yystate = *yyssp;
       YY_STACK_PRINT (yyss, yyssp);
     }
   *++yyvsp = yylval;
   yyerror_range[1] = yylloc;
   /* Using YYLLOC is tempting, but would change the location of
      the lookahead.  YYLOC is available though.  */
   YYLLOC_DEFAULT (yyloc, (yyerror_range - 1), 2);
   *++yylsp = yyloc;
   /* Shift the error token.  */
   YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);
   yystate = yyn;
   goto yynewstate;
 /*-------------------------------------.
 | yyacceptlab -- YYACCEPT comes here.  |
 `-------------------------------------*/
 yyacceptlab:
   yyresult = 0;
   goto yyreturn;
 /*-----------------------------------.
 | yyabortlab -- YYABORT comes here.  |
 `-----------------------------------*/
 yyabortlab:
   yyresult = 1;
   goto yyreturn;
 #ifndef yyoverflow
 /*-------------------------------------------------.
 | yyexhaustedlab -- memory exhaustion comes here.  |
 `-------------------------------------------------*/
 yyexhaustedlab:
   yyerror (&yylloc, parseInfo, YY_("memory exhausted"));
   yyresult = 2;
   /* Fall through.  */
 #endif
 yyreturn:
   if (yychar != YYEMPTY)
      yydestruct ("Cleanup: discarding lookahead",
          yytoken, &yylval, &yylloc, parseInfo);
   /* Do not reclaim the symbols of the rule which action triggered
      this YYABORT or YYACCEPT.  */
   YYPOPSTACK (yylen);
   YY_STACK_PRINT (yyss, yyssp);
   while (yyssp != yyss)
     {
       yydestruct ("Cleanup: popping",
           yystos[*yyssp], yyvsp, yylsp, parseInfo);
       YYPOPSTACK (1);
     }
 #ifndef yyoverflow
   if (yyss != yyssa)
     YYSTACK_FREE (yyss);
 #endif
 #if YYERROR_VERBOSE
   if (yymsg != yymsgbuf)
     YYSTACK_FREE (yymsg);
 #endif
   /* Make sure YYID is used.  */
   return YYID (yyresult);
 }
yystpcpy()
static char* QPatternist::yystpcpy (char * yydest, const char * yysrc) static
Definition at line 3175 of file qquerytransformparser.cpp.
Referenced by yysyntax_error(), and yytnamerr().
 {
   char *yyd = yydest;
   const char *yys = yysrc;
   while ((*yyd++ = *yys++) != '\0')
     continue;
   return yyd - 1;
 }
yystrlen()
static YYSIZE_T QPatternist::yystrlen (const char * yystr) static
Definition at line 3151 of file qquerytransformparser.cpp.
Referenced by yysyntax_error(), and yytnamerr().
 {
   YYSIZE_T yylen;
   for (yylen = 0; yystr[yylen]; yylen++)
     continue;
   return yylen;
 }
yysyntax_error()
static YYSIZE_T QPatternist::yysyntax_error (char * yyresult, int yystate, int yychar) static
Definition at line 3250 of file qquerytransformparser.cpp.
Referenced by yyparse().
 {
   int yyn = yypact[yystate];
   if (! (YYPACT_NINF < yyn && yyn <= YYLAST))
     return 0;
   else
     {
       int yytype = YYTRANSLATE (yychar);
       YYSIZE_T yysize0 = yytnamerr (0, yytname[yytype]);
       YYSIZE_T yysize = yysize0;
       YYSIZE_T yysize1;
       int yysize_overflow = 0;
       enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
       char const *yyarg[YYERROR_VERBOSE_ARGS_MAXIMUM];
       int yyx;
 # if 0
       /* This is so xgettext sees the translatable formats that are
      constructed on the fly.  */
       YY_("syntax error, unexpected %s");
       YY_("syntax error, unexpected %s, expecting %s");
       YY_("syntax error, unexpected %s, expecting %s or %s");
       YY_("syntax error, unexpected %s, expecting %s or %s or %s");
       YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s");
 # endif
       char *yyfmt;
       char const *yyf;
       static char const yyunexpected[] = "syntax error, unexpected %s";
       static char const yyexpecting[] = ", expecting %s";
       static char const yyor[] = " or %s";
       char yyformat[sizeof yyunexpected
             + sizeof yyexpecting - 1
             + ((YYERROR_VERBOSE_ARGS_MAXIMUM - 2)
                * (sizeof yyor - 1))];
       char const *yyprefix = yyexpecting;
       /* Start YYX at -YYN if negative to avoid negative indexes in
      YYCHECK.  */
       int yyxbegin = yyn < 0 ? -yyn : 0;
       /* Stay within bounds of both yycheck and yytname.  */
       int yychecklim = YYLAST - yyn + 1;
       int yyxend = yychecklim < YYNTOKENS ? yychecklim : YYNTOKENS;
       int yycount = 1;
       yyarg[0] = yytname[yytype];
       yyfmt = yystpcpy (yyformat, yyunexpected);
       for (yyx = yyxbegin; yyx < yyxend; ++yyx)
     if (yycheck[yyx + yyn] == yyx && yyx != YYTERROR)
       {
         if (yycount == YYERROR_VERBOSE_ARGS_MAXIMUM)
           {
         yycount = 1;
         yysize = yysize0;
         yyformat[sizeof yyunexpected - 1] = '\0';
         break;
           }
         yyarg[yycount++] = yytname[yyx];
         yysize1 = yysize + yytnamerr (0, yytname[yyx]);
         yysize_overflow |= (yysize1 < yysize);
         yysize = yysize1;
         yyfmt = yystpcpy (yyfmt, yyprefix);
         yyprefix = yyor;
       }
       yyf = YY_(yyformat);
       yysize1 = yysize + yystrlen (yyf);
       yysize_overflow |= (yysize1 < yysize);
       yysize = yysize1;
       if (yysize_overflow)
     return YYSIZE_MAXIMUM;
       if (yyresult)
     {
       /* Avoid sprintf, as that infringes on the user's name space.
          Don't have undefined behavior even if the translation
          produced a string with the wrong number of "%s"s.  */
       char *yyp = yyresult;
       int yyi = 0;
       while ((*yyp = *yyf) != '\0')
         {
           if (*yyp == '%' && yyf[1] == 's' && yyi < yycount)
         {
           yyp += yytnamerr (yyp, yyarg[yyi++]);
           yyf += 2;
         }
           else
         {
           yyp++;
           yyf++;
         }
         }
     }
       return yysize;
     }
 }
yytnamerr()
static YYSIZE_T QPatternist::yytnamerr (char * yyres, const char * yystr) static
Definition at line 3203 of file qquerytransformparser.cpp.
Referenced by yysyntax_error().
 {
   if (*yystr == '"')
     {
       YYSIZE_T yyn = 0;
       char const *yyp = yystr;
       for (;;)
     switch (*++yyp)
       {
       case '\'':
       case ',':
         goto do_not_strip_quotes;
       case '\\':
         if (*++yyp != '\\')
           goto do_not_strip_quotes;
         /* Fall through.  */
       default:
         if (yyres)
           yyres[yyn] = *yyp;
         yyn++;
         break;
       case '"':
         if (yyres)
           yyres[yyn] = '\0';
         return yyn;
       }
     do_not_strip_quotes: ;
     }
   if (! yyres)
     return yystrlen (yystr);
   return yystpcpy (yyres, yystr) - yyres;
 }
Variable Documentation
mergeIterator
const MergeIterator QPatternist::mergeIterator static
Definition at line 493 of file qabstractxmlnodemodel.cpp.
Referenced by QAbstractXmlNodeModel::iterate(), and mergeIterators().
yycheck
const yytype_int16 QPatternist::yycheck[] static
Definition at line 2561 of file qquerytransformparser.cpp.
yydefact
const yytype_uint16 QPatternist::yydefact[] static
Definition at line 2113 of file qquerytransformparser.cpp.
yydefgoto
const yytype_int16 QPatternist::yydefgoto[] static
Initial value:
=
{
      -1,     2,     3,   185,     7,     8,     9,    10,    77,   593,
     669,   756,   366,   367,    78,    79,   320,    80,    81,   350,
      82,    83,    84,    85,    86,    87,    88,   458,    89,   356,
     532,    90,    91,    92,   386,    93,   383,   560,   606,    94,
     641,   676,    95,   353,    96,   664,   589,   590,   730,   341,
      97,   631,   632,   633,   634,   635,    98,    99,   100,   733,
     189,   753,   324,   101,   102,   678,   709,   738,   806,   809,
     553,   103,   686,   717,   796,   718,   719,   720,   579,   580,
     619,   659,   692,   512,   104,   105,   654,   687,   722,   797,
     803,   106,   644,   677,   707,   794,   800,   708,   107,   567,
     614,   725,   774,   784,   656,   785,   804,   108,   109,   110,
     111,   112,   113,   287,   114,   292,   115,   116,   295,   298,
     117,   118,   119,   120,   121,   122,   123,   124,   281,   125,
     282,   126,   283,   127,   128,   129,   306,   130,   131,   393,
     132,   133,   134,   253,   626,   437,   438,   520,   468,   521,
     522,   694,   312,   135,   136,   137,   314,   427,   138,   139,
     140,   190,   141,   142,   143,   144,   145,   146,   147,   148,
     149,   150,   219,   151,   152,   153,   154,   433,   155,   156,
     157,   380,   554,   681,   479,   555,   650,   342,   710,   158,
     159,   160,   161,   162,   475,   193,   163,   164,   165,   166,
     338,   339,   526,   375,   340,   246,   167,   505,   477,   498,
     573,   499,   500,   168,   169,   170,   370,   171,   172,   173,
     174,   175,   176,   177,   598,   178,   194,   335,   179,   524,
     180,   181,   556,   241,   541,   182,   183
}
Definition at line 2200 of file qquerytransformparser.cpp.
yypact
const yytype_int16 QPatternist::yypact[] static
Definition at line 2231 of file qquerytransformparser.cpp.
yypgoto
const yytype_int16 QPatternist::yypgoto[] static
Initial value:
=
{
    -668,  -668,  -668,  -668,  -668,  -668,  -668,   613,  -668,  -668,
    -668,  -668,  -668,  -668,  -668,  -668,  -285,  -668,  -668,  -668,
    -668,  -668,  -668,  -668,  -668,   418,  -668,     5,  -668,  -668,
    -668,  -668,  -668,  -668,  -668,  -668,  -668,   142,  -668,  -668,
    -668,  -668,  -668,  -668,  -668,  -668,  -668,     4,  -668,   -51,
    -668,  -668,   -35,  -668,  -397,  -340,   -47,   317,  -255,  -668,
    -668,  -668,  -641,  -668,  -619,  -668,  -668,  -174,  -668,  -668,
    -142,  -583,  -668,  -159,  -668,  -657,  -109,   216,  -668,    27,
    -668,  -668,  -668,  -668,  -668,  -668,  -668,  -668,  -157,  -668,
    -668,  -668,  -668,  -668,  -152,  -668,  -668,  -667,  -668,  -668,
    -125,  -668,  -668,  -668,  -668,  -668,  -668,  -668,  -668,   387,
     385,   131,   366,  -668,   397,  -668,   361,   359,  -668,  -668,
     362,  -668,  -668,  -668,   535,  -668,  -668,  -668,  -668,  -668,
    -668,  -668,  -668,  -668,  -668,  -668,  -245,  -668,   526,  -668,
    -668,   279,  -294,  -668,  -668,   313,  -668,   194,   -91,    85,
    -668,  -668,  -668,   -87,  -668,  -668,  -668,  -668,  -668,  -668,
    -668,  -668,  -668,  -668,  -175,  -668,  -668,  -668,  -668,  -668,
    -668,  -668,  -183,  -668,  -668,  -668,  -538,  -668,  -668,   -42,
    -668,  -668,  -668,  -668,    67,  -668,  -668,  -327,  -668,  -668,
    -668,  -668,  -668,  -668,  -668,     3,  -668,  -668,  -668,  -668,
    -668,  -668,  -668,  -668,   458,  -668,  -668,   252,  -341,  -412,
    -668,  -668,   -55,  -394,  -668,  -668,  -668,  -668,  -668,  -668,
    -304,  -668,  -668,   467,   124,   469,   -11,  -668,   -24,  -170,
     321,  -668,   639,  -668,  -308,    15,   -30
}
Definition at line 2318 of file qquerytransformparser.cpp.
yyr1
const yytype_uint16 QPatternist::yyr1[] static
Definition at line 2005 of file qquerytransformparser.cpp.
yyr2
const yytype_uint8 QPatternist::yyr2[] static
Definition at line 2058 of file qquerytransformparser.cpp.
yystos
const yytype_uint16 QPatternist::yystos[] static
Definition at line 2773 of file qquerytransformparser.cpp.
yytable
const yytype_int16 QPatternist::yytable[] static
Definition at line 2351 of file qquerytransformparser.cpp.
yytname
const char* const QPatternist::yytname[] static
Definition at line 1880 of file qquerytransformparser.cpp.
yytranslate
const yytype_uint8 QPatternist::yytranslate[] static
Definition at line 1578 of file qquerytransformparser.cpp.