Qt 4.8: QDeclarativeJS Namespace Reference
QDeclarativeJS Namespace Reference
Namespaces
AST
Ecma
Classes
class DiagnosticMessage
class Engine
class Lexer
class MemoryPool
class NameId
class NodePool
class Parser
class TextWriter
Functions
double integerFromString (const char *buf, int size, int radix)
double integerFromString (const QString &str, int radix)
template<typename NodeType >
NodeType * makeAstNode (MemoryPool *storage)
template<typename NodeType , typename Arg1 >
NodeType * makeAstNode (MemoryPool *storage, Arg1 arg1)
template<typename NodeType , typename Arg1 , typename Arg2 >
NodeType * makeAstNode (MemoryPool *storage, Arg1 arg1, Arg2 arg2)
template<typename NodeType , typename Arg1 , typename Arg2 , typename Arg3 >
NodeType * makeAstNode (MemoryPool *storage, Arg1 arg1, Arg2 arg2, Arg3 arg3)
template<typename NodeType , typename Arg1 , typename Arg2 , typename Arg3 , typename Arg4 >
NodeType * makeAstNode (MemoryPool *storage, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4)
QString numberToString (double value)
uint qHash (const QDeclarativeJS::NameId &id)
static int toDigit (char c)
Function Documentation
integerFromString() [1/2]
double QDeclarativeJS::integerFromString (const char * buf, int size, int radix)
Definition at line 114 of file qdeclarativejsengine_p.cpp.
Referenced by integerFromString(), and QDeclarativeJS::Lexer::lex().
 {
     if (size == 0)
         return qSNaN();
     double sign = 1.0;
     int i = 0;
     if (buf[0] == '+') {
         ++i;
     } else if (buf[0] == '-') {
         sign = -1.0;
         ++i;
     }
     if (((size-i) >= 2) && (buf[i] == '0')) {
         if (((buf[i+1] == 'x') || (buf[i+1] == 'X'))
             && (radix < 34)) {
             if ((radix != 0) && (radix != 16))
                 return 0;
             radix = 16;
             i += 2;
         } else {
             if (radix == 0) {
                 radix = 8;
                 ++i;
             }
         }
     } else if (radix == 0) {
         radix = 10;
     }
     int j = i;
     for ( ; i < size; ++i) {
         int d = toDigit(buf[i]);
         if ((d == -1) || (d >= radix))
             break;
     }
     double result;
     if (j == i) {
         if (!qstrcmp(buf, "Infinity"))
             result = qInf();
         else
             result = qSNaN();
     } else {
         result = 0;
         double multiplier = 1;
         for (--i ; i >= j; --i, multiplier *= radix)
             result += toDigit(buf[i]) * multiplier;
     }
     result *= sign;
     return result;
 }
integerFromString() [2/2]
double QDeclarativeJS::integerFromString (const QString & str, int radix)
Definition at line 167 of file qdeclarativejsengine_p.cpp.
 {
     QByteArray ba = str.trimmed().toLatin1();
     return integerFromString(ba.constData(), ba.size(), radix);
 }
makeAstNode() [1/5]
template<typename NodeType > NodeType* QDeclarativeJS::makeAstNode (MemoryPool * storage) inline
Definition at line 75 of file qdeclarativejsnodepool_p.h.
 {
     NodeType *node = new (storage->allocate(sizeof(NodeType))) NodeType();
     return node;
 }
makeAstNode() [2/5]
template<typename NodeType , typename Arg1 > NodeType* QDeclarativeJS::makeAstNode (MemoryPool * storage, Arg1 arg1) inline
Definition at line 82 of file qdeclarativejsnodepool_p.h.
 {
     NodeType *node = new (storage->allocate(sizeof(NodeType))) NodeType(arg1);
     return node;
 }
makeAstNode() [3/5]
template<typename NodeType , typename Arg1 , typename Arg2 > NodeType* QDeclarativeJS::makeAstNode (MemoryPool * storage, Arg1 arg1, Arg2 arg2) inline
Definition at line 89 of file qdeclarativejsnodepool_p.h.
 {
     NodeType *node = new (storage->allocate(sizeof(NodeType))) NodeType(arg1, arg2);
     return node;
 }
makeAstNode() [4/5]
template<typename NodeType , typename Arg1 , typename Arg2 , typename Arg3 > NodeType* QDeclarativeJS::makeAstNode (MemoryPool * storage, Arg1 arg1, Arg2 arg2, Arg3 arg3) inline
Definition at line 96 of file qdeclarativejsnodepool_p.h.
 {
     NodeType *node = new (storage->allocate(sizeof(NodeType))) NodeType(arg1, arg2, arg3);
     return node;
 }
makeAstNode() [5/5]
template<typename NodeType , typename Arg1 , typename Arg2 , typename Arg3 , typename Arg4 > NodeType* QDeclarativeJS::makeAstNode (MemoryPool * storage, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4) inline
Definition at line 103 of file qdeclarativejsnodepool_p.h.
 {
     NodeType *node = new (storage->allocate(sizeof(NodeType))) NodeType(arg1, arg2, arg3, arg4);
     return node;
 }
numberToString()
QString QDeclarativeJS::numberToString (double value)
Definition at line 57 of file qdeclarativejsengine_p.cpp.
 { return QString::number(value); }
qHash()
uint QDeclarativeJS::qHash (const QDeclarativeJS::NameId & id)
Definition at line 54 of file qdeclarativejsengine_p.cpp.
Referenced by QDeclarativeJS::NameId::operator<().
 { return qHash(id.asString()); }
toDigit()
static int QDeclarativeJS::toDigit (char c) static
Definition at line 103 of file qdeclarativejsengine_p.cpp.
Referenced by integerFromString().
 {
     if ((c >= '0') && (c <= '9'))
         return c - '0';
     else if ((c >= 'a') && (c <= 'z'))
         return 10 + c - 'a';
     else if ((c >= 'A') && (c <= 'Z'))
         return 10 + c - 'A';
     return -1;
 }