Qt 4.8: /src/plugins/script/qtdbus/main.cpp File Reference
main.cpp File Reference
#include "main.h"
#include <QDebug>
#include <QMetaMethod>
#include <QScriptExtensionPlugin>
Classes
class QtDBusScriptPlugin
Functions
static QScriptValue do_dbus_call (QScriptContext *context, QScriptEngine *engine)
static QScriptValue messageToScriptValue (QScriptEngine *engine, const QDBusMessage &message)
QScriptValue qDBusErrorToScriptValue (QScriptEngine *engine, const QDBusError &error)
template<typename T >
void qDBusReplyFromScriptValue (const QScriptValue &, QDBusReply< T > &)
template<typename T >
QScriptValue qDBusReplyToScriptValue (QScriptEngine *eng, const QDBusReply< T > &reply)
template<>
QScriptValue qDBusReplyToScriptValue (QScriptEngine *eng, const QDBusReply< QStringList > &reply)
static void scriptValueToMessage (const QScriptValue &value, QDBusMessage &message)
void scriptValueToQDBusError (const QScriptValue &value, QDBusError &error)
static QScriptValue setupDBusInterface (QScriptEngine *engine, QDBusAbstractInterface *iface)
Function Documentation
do_dbus_call()
static QScriptValue do_dbus_call (QScriptContext * context, QScriptEngine * engine) static
Definition at line 53 of file main.cpp.
Referenced by setupDBusInterface().
 {
     int firstArgument = 0;
     QString functionName = context->callee().property(QLatin1String("functionName")).toString();
     if (functionName.isEmpty()) {
         functionName = context->argument(0).toString();
         ++firstArgument;
     }
     QScriptValue thisObject = context->thisObject();
     QDBusAbstractInterface *iface = qobject_cast<QDBusAbstractInterface *>(thisObject.toQObject());
     if (!iface)
         return QScriptValue();
     QDBusMessage msg = QDBusMessage::createMethodCall(iface->service(),
                                                       iface->path(),
                                                       iface->interface(),
                                                       functionName);
     QList<QVariant> args;
     for (int i = firstArgument; i < context->argumentCount(); ++i) {
         args.append(context->argument(i).toVariant());
     }
     msg.setArguments(args);
     msg = iface->connection().call(msg);
     QScriptValue returnValue = engine->nullValue();
     args = msg.arguments();
     if (args.count() != 1)
         return returnValue;
     QVariant variant = args.first();
     if (variant.type() == QVariant::UserType
         && variant.userType() == qMetaTypeId<QDBusObjectPath>()) {
         QDBusObjectPath path = qvariant_cast<QDBusObjectPath>(variant);
         QDBusInterface *returnedIface = new QDBusInterface(iface->service(),
                                                            path.path(),
                                                            /*interface*/QString(),
                                                            iface->connection(),
                                                            engine);
         returnValue = setupDBusInterface(engine, returnedIface);
     } else {
         returnValue = engine->newVariant(variant);
     }
     return returnValue;
 }
messageToScriptValue()
static QScriptValue messageToScriptValue (QScriptEngine * engine, const QDBusMessage & message) static
Definition at line 241 of file main.cpp.
Referenced by QScriptDBusMessageConstructor::createErrorReply(), QScriptDBusMessageConstructor::createReply(), and QtDBusScriptPlugin::initialize().
 {
     QScriptValue v = engine->newVariant(QVariant::fromValue(message));
     v.setProperty(QLatin1String("service"), QScriptValue(engine, message.service()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("path"), QScriptValue(engine, message.path()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("interface"), QScriptValue(engine, message.interface()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("member"), QScriptValue(engine, message.member()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("type"), QScriptValue(engine, message.type()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("signature"), QScriptValue(engine, message.signature()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("isReplyRequired"), QScriptValue(engine, message.isReplyRequired()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("delayedReply"), QScriptValue(engine, message.isDelayedReply()));
     QScriptValue argValue = engine->newArray();
     const QList<QVariant> args = message.arguments();
     for (int i = 0; i < args.count(); ++i)
         argValue.setProperty(QScriptValue(engine, i).toString(),
                              engine->newVariant(args.at(i)));
     v.setProperty(QLatin1String("arguments"), argValue);
     return v;
 }
qDBusErrorToScriptValue()
QScriptValue qDBusErrorToScriptValue (QScriptEngine * engine, const QDBusError & error)
Definition at line 328 of file main.cpp.
Referenced by QtDBusScriptPlugin::initialize().
 {
     QScriptValue v = engine->newObject();
     v.setProperty(QLatin1String("type"), QScriptValue(engine, error.type()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("name"), QScriptValue(engine, error.name()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("message"), QScriptValue(engine, error.message()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("isValid"), QScriptValue(engine, error.isValid()), QScriptValue::ReadOnly);
     return v;
 }
qDBusReplyFromScriptValue()
template<typename T > void qDBusReplyFromScriptValue (const QScriptValue & , QDBusReply< T > &)
Definition at line 323 of file main.cpp.
Referenced by QtDBusScriptPlugin::initialize().
 {
     // never called
 }
qDBusReplyToScriptValue() [1/2]
template<typename T > QScriptValue qDBusReplyToScriptValue (QScriptEngine * eng, const QDBusReply< T > & reply)
Definition at line 307 of file main.cpp.
Referenced by QtDBusScriptPlugin::initialize().
 {
     return QScriptValue(eng, reply.value());
 }
qDBusReplyToScriptValue() [2/2]
template<> QScriptValue qDBusReplyToScriptValue (QScriptEngine * eng, const QDBusReply< QStringList > & reply)
Definition at line 313 of file main.cpp.
 {
     QScriptValue v = eng->newArray();
     const QStringList &lst = reply.value();
     for (int i = 0; i < lst.count(); ++i)
         v.setProperty(i, QScriptValue(eng, lst.at(i)));
     return v;
 }
scriptValueToMessage()
static void scriptValueToMessage (const QScriptValue & value, QDBusMessage & message) static
Definition at line 264 of file main.cpp.
Referenced by QScriptDBusMessageConstructor::createErrorReply(), QScriptDBusMessageConstructor::createReply(), and QtDBusScriptPlugin::initialize().
 {
     QVariant v = value.toVariant();
     message = qvariant_cast<QDBusMessage>(v);
     message.setDelayedReply(value.property(QLatin1String("delayedReply")).toBoolean());
     QList<QVariant> args;
     quint32 len = value.property(QLatin1String("length")).toUInt32();
     for (quint32 i = 0; i < len; ++i) {
         QScriptValue item = value.property(i);
         args.append(item.toVariant());
     }
     message.setArguments(args);
 }
scriptValueToQDBusError()
void scriptValueToQDBusError (const QScriptValue & value, QDBusError & error)
Definition at line 338 of file main.cpp.
Referenced by QtDBusScriptPlugin::initialize().
 {
     Q_UNUSED(value)
     Q_UNUSED(error)
     // never called
 }
setupDBusInterface()
static QScriptValue setupDBusInterface (QScriptEngine * engine, QDBusAbstractInterface * iface) static
Definition at line 103 of file main.cpp.
Referenced by do_dbus_call(), QScriptDBusInterfaceConstructor::qscript_call(), and QScriptDBusConnection::QScriptDBusConnection().
 {
     QScriptValue v = engine->newQObject(iface);
     if (!qobject_cast<QDBusConnectionInterface *>(iface)) {
         const QMetaObject *mo = iface->metaObject();
         for (int i = 0; i < mo->methodCount(); ++i) {
             const QMetaMethod method = mo->method(i);
             const QByteArray signature = method.signature();
             //qDebug() << "signature" << signature;
             int parenIndex = signature.indexOf('(');
             if (parenIndex == -1)
                 continue;
             const QByteArray name = signature.left(parenIndex);
             if (name.isEmpty())
                 continue;
             // don't try to override properties
             if (mo->indexOfProperty(name) != -1)
                 continue;
             QScriptValue callWrapper = engine->newFunction(do_dbus_call);
             const QString nameString = QString::fromAscii(name);
             callWrapper.setProperty(QLatin1String("functionName"), QScriptValue(engine, nameString));
             v.setProperty(nameString, callWrapper);
         }
     }
     v.setProperty(QLatin1String("service"), QScriptValue(engine, iface->service()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("path"), QScriptValue(engine, iface->path()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("interface"), QScriptValue(engine, iface->interface()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("isValid"), QScriptValue(engine, iface->isValid()), QScriptValue::ReadOnly);
     v.setProperty(QLatin1String("connection"), engine->newQObject(new QScriptDBusConnection(iface->connection(), engine)), QScriptValue::ReadOnly);
     return v;
 }