Qt 4.8: /src/plugins/codecs/jp/main.cpp File Reference
main.cpp File Reference
#include <qtextcodecplugin.h>
#include <qtextcodec.h>
#include <qstringlist.h>
#include "qeucjpcodec.h"
#include "qjiscodec.h"
#include "qsjiscodec.h"
#include "qfontjpcodec.h"
Classes
class JPTextCodecs
Functions
Q_EXPORT_PLUGIN2 (qjpcodecs, JPTextCodecs)
Q_EXPORT_STATIC_PLUGIN (JPTextCodecs)
Function Documentation
Q_EXPORT_PLUGIN2()
Q_EXPORT_PLUGIN2 (qjpcodecs , JPTextCodecs)
Referenced by QVGGraphicsSystemPlugin::create(), QEglIntegrationPlugin::create(), QLinuxFbIntegrationPlugin::create(), QOpenKODEPlugin::create(), ShivaVGGraphicsSystemPlugin::create(), QTraceGraphicsSystemPlugin::create(), QWaylandIntegrationPlugin::create(), QXcbIntegrationPlugin::create(), QXlibIntegrationPlugin::create(), QBBIntegrationPlugin::create(), QMinimalIntegrationPlugin::create(), QVFbIntegrationPlugin::create(), QVNCIntegrationPlugin::create(), QGLGraphicsSystemPlugin::create(), DecorationWindows::create(), QLinuxInputPlugin::create(), QLinuxInputKbdDriver::create(), QLinuxTPMouseDriver::create(), QTsLibPlugin::create(), QPcMouseDriver::create(), TslibMouseDriver::create(), DecorationStyled::create(), DecorationDefault::create(), QScreenLinuxFbPlugin::create(), GfxTransformedDriver::create(), ScreenVfbDriver::create(), GfxVncDriver::create(), QNlaEnginePlugin::create(), QBBEnginePlugin::create(), QICOPlugin::create(), QCoreWlanEnginePlugin::create(), QConnmanEnginePlugin::create(), QJpegPlugin::create(), QGenericEnginePlugin::create(), CompatAccessibleFactory::create(), QSvgIconPlugin::create(), QIcdEnginePlugin::create(), QSvgPlugin::create(), QNetworkManagerEnginePlugin::create(), QDirectFbIntegrationPlugin::create(), QMngPlugin::create(), QGifPlugin::create(), AccessibleFactory::create(), QNativeWifiEnginePlugin::create(), TWTextCodecs::createForName(), CNTextCodecs::createForName(), KRTextCodecs::createForName(), JPTextCodecs::createForName(), QDB2DriverPlugin::keys(), QSymSQLDriverPlugin::keys(), QMYSQLDriverPlugin::keys(), QOCIDriverPlugin::keys(), QPSQLDriverPlugin::keys(), QIBaseDriverPlugin::keys(), QODBCDriverPlugin::keys(), QTiffPlugin::keys(), QTgaPlugin::keys(), and QTDSDriverPlugin::keys().
Q_EXPORT_STATIC_PLUGIN()
Q_EXPORT_STATIC_PLUGIN (JPTextCodecs)
Referenced by TslibMouseDriver::create(), GfxTransformedDriver::create(), ScreenVfbDriver::create(), GfxVncDriver::create(), QNlaEnginePlugin::create(), QBBEnginePlugin::create(), QSvgIconPlugin::create(), QConnmanEnginePlugin::create(), QCoreWlanEnginePlugin::create(), QJpegPlugin::create(), QGenericEnginePlugin::create(), CompatAccessibleFactory::create(), QIcdEnginePlugin::create(), QNetworkManagerEnginePlugin::create(), QSvgPlugin::create(), QGifPlugin::create(), QMngPlugin::create(), AccessibleFactory::create(), QNativeWifiEnginePlugin::create(), CNTextCodecs::createForName(), KRTextCodecs::createForName(), TWTextCodecs::createForName(), JPTextCodecs::createForName(), QDB2DriverPlugin::keys(), QPSQLDriverPlugin::keys(), QODBCDriverPlugin::keys(), QOCIDriverPlugin::keys(), QSymSQLDriverPlugin::keys(), QMYSQLDriverPlugin::keys(), QIBaseDriverPlugin::keys(), QTiffPlugin::keys(), and QTDSDriverPlugin::keys().