Qt 4.8: /src/plugins/gfxdrivers/powervr/QWSWSEGL/pvrqwswsegl.c File Reference
pvrqwswsegl.c File Reference
#include <GLES/eglplatform.h>
#include <wsegl.h>
#include <pvr2d.h>
#include <string.h>
#include <sys/mman.h>
#include "pvrqwsdrawable_p.h"
Macros
#define WSEGL_CAP_PIXMAPS_USE_HW_SYNC WSEGL_CAP_PIXMAPS_USE_MBX_SYNC
#define WSEGL_CAP_WINDOWS_USE_HW_SYNC WSEGL_CAP_WINDOWS_USE_MBX_SYNC
#define WSEGL_UNUSED(x) (void)x;
Functions
const WSEGL_FunctionTable * WSEGL_GetFunctionTablePointer (void)
static WSEGLError wseglCloseDisplay (WSEGLDisplayHandle display)
static WSEGLError wseglCopyFromDrawable (WSEGLDrawableHandle _drawable, NativePixmapType nativePixmap)
static WSEGLError wseglCopyFromPBuffer (void *address, unsigned long width, unsigned long height, unsigned long stride, WSEGLPixelFormat format, NativePixmapType nativePixmap)
static WSEGLError wseglCreatePixmapDrawable (WSEGLDisplayHandle display, WSEGLConfig *config, WSEGLDrawableHandle *drawable, NativePixmapType nativePixmap, WSEGLRotationAngle *rotationAngle)
static WSEGLError wseglCreateWindowDrawable (WSEGLDisplayHandle display, WSEGLConfig *config, WSEGLDrawableHandle *drawable, NativeWindowType nativeWindow, WSEGLRotationAngle *rotationAngle)
static WSEGLError wseglDeleteDrawable (WSEGLDrawableHandle _drawable)
static WSEGLError wseglGetDrawableParameters (WSEGLDrawableHandle _drawable, WSEGLDrawableParams *sourceParams, WSEGLDrawableParams *renderParams)
static WSEGLError wseglInitializeDisplay (NativeDisplayType nativeDisplay, WSEGLDisplayHandle *display, const WSEGLCaps **caps, WSEGLConfig **configs)
static WSEGLError wseglIsDisplayValid (NativeDisplayType nativeDisplay)
static WSEGLRotationAngle wseglRotationValue (int degrees)
static WSEGLError wseglSwapControlInterval (WSEGLDrawableHandle drawable, unsigned long interval)
static WSEGLError wseglSwapDrawable (WSEGLDrawableHandle _drawable, unsigned long data)
static WSEGLError wseglWaitNative (WSEGLDrawableHandle drawable, unsigned long engine)
Variables
static WSEGLCaps const wseglDisplayCaps []
static WSEGLConfig wseglDisplayConfigs []
static WSEGL_FunctionTable const wseglFunctions
Macro Definition Documentation
WSEGL_CAP_PIXMAPS_USE_HW_SYNC
#define WSEGL_CAP_PIXMAPS_USE_HW_SYNC WSEGL_CAP_PIXMAPS_USE_MBX_SYNC
Definition at line 55 of file pvrqwswsegl.c.
WSEGL_CAP_WINDOWS_USE_HW_SYNC
#define WSEGL_CAP_WINDOWS_USE_HW_SYNC WSEGL_CAP_WINDOWS_USE_MBX_SYNC
Definition at line 54 of file pvrqwswsegl.c.
WSEGL_UNUSED
#define WSEGL_UNUSED (x) (void)x;
Definition at line 49 of file pvrqwswsegl.c.
Referenced by wseglCreatePixmapDrawable(), wseglCreateWindowDrawable(), wseglSwapControlInterval(), wseglSwapDrawable(), and wseglWaitNative().
Function Documentation
WSEGL_GetFunctionTablePointer()
const WSEGL_FunctionTable* WSEGL_GetFunctionTablePointer (void)
Definition at line 399 of file pvrqwswsegl.c.
 {
     return &wseglFunctions;
 }
wseglCloseDisplay()
static WSEGLError wseglCloseDisplay (WSEGLDisplayHandle display) static
Definition at line 128 of file pvrqwswsegl.c.
 {
     if (display == (WSEGLDisplayHandle)&pvrQwsDisplay)
         pvrQwsDisplayClose();
     return WSEGL_SUCCESS;
 }
wseglCopyFromDrawable()
static WSEGLError wseglCopyFromDrawable (WSEGLDrawableHandle _drawable, NativePixmapType nativePixmap) static
Definition at line 250 of file pvrqwswsegl.c.
Referenced by wseglWaitNative().
 {
     PvrQwsDrawable *drawable = (PvrQwsDrawable *)_drawable;
     PvrQwsDrawable *pixmap = (PvrQwsDrawable *)nativePixmap;
     PVR2DBLTINFO blit;
     if (!drawable || !drawable->backBuffersValid)
         return WSEGL_BAD_NATIVE_WINDOW;
     if (!pixmap || !pixmap->backBuffersValid)
         return WSEGL_BAD_NATIVE_PIXMAP;
     memset(&blit, 0, sizeof(blit));
     blit.CopyCode = PVR2DROPcopy;
     blit.BlitFlags = PVR2D_BLIT_DISABLE_ALL;
     blit.pSrcMemInfo = drawable->backBuffers[drawable->currentBackBuffer];
     blit.SrcStride = drawable->strideBytes;
     blit.SrcX = 0;
     blit.SrcY = 0;
     blit.SizeX = drawable->rect.width;
     blit.SizeY = drawable->rect.height;
     blit.SrcFormat = drawable->pixelFormat;
     blit.pDstMemInfo = pixmap->backBuffers[pixmap->currentBackBuffer];
     blit.DstStride = pixmap->strideBytes;
     blit.DstX = 0;
     blit.DstY = 0;
     blit.DSizeX = pixmap->rect.width;
     blit.DSizeY = pixmap->rect.height;
     blit.DstFormat = pixmap->pixelFormat;
     PVR2DBlt(pvrQwsDisplay.context, &blit);
     PVR2DQueryBlitsComplete
         (pvrQwsDisplay.context, pixmap->backBuffers[pixmap->currentBackBuffer], 1);
     return WSEGL_SUCCESS;
 }
wseglCopyFromPBuffer()
static WSEGLError wseglCopyFromPBuffer (void * address, unsigned long width, unsigned long height, unsigned long stride, WSEGLPixelFormat format, NativePixmapType nativePixmap) static
Definition at line 291 of file pvrqwswsegl.c.
Referenced by wseglCopyFromDrawable().
 {
     PvrQwsDrawable *pixmap = (PvrQwsDrawable *)nativePixmap;
     PVR2DFORMAT pixelFormat;
     if (!pixmap)
         return WSEGL_BAD_NATIVE_PIXMAP;
     /* We can only copy under certain conditions */
     switch (format) {
     case WSEGL_PIXELFORMAT_565:
             pixelFormat = PVR2D_RGB565; break;
     case WSEGL_PIXELFORMAT_4444:
             pixelFormat = PVR2D_ARGB4444; break;
     case WSEGL_PIXELFORMAT_8888:
             pixelFormat = PVR2D_ARGB8888; break;
         default:
             return WSEGL_BAD_CONFIG;
     }
     if (width > (unsigned long)(pixmap->rect.width) ||
         height > (unsigned long)(pixmap->rect.height) ||
         pixelFormat != pixmap->pixelFormat) {
         return WSEGL_BAD_CONFIG;
     }
     /* We'd like to use PVR2DBlt to do this, but there is no easy way
        to map the virtual "address" into physical space to be able
        to use the hardware assist.  Use memcpy to do the work instead.
        Note: PBuffer's are upside down, so we copy from the bottom up */
     char *srcaddr = (char *)address;
     char *dstaddr = (char *)(pixmap->backBuffers[pixmap->currentBackBuffer]->pBase);
     int dststride = pixmap->strideBytes;
     int srcwidth = ((int)width) * pvrQwsDisplay.screens[0].bytesPerPixel;
     srcaddr += height * stride;
     while (height > 0) {
         srcaddr -= (int)stride;
         memcpy(dstaddr, srcaddr, srcwidth);
         dstaddr += dststride;
         --height;
     }
     return WSEGL_SUCCESS;
 }
wseglCreatePixmapDrawable()
static WSEGLError wseglCreatePixmapDrawable (WSEGLDisplayHandle display, WSEGLConfig * config, WSEGLDrawableHandle * drawable, NativePixmapType nativePixmap, WSEGLRotationAngle * rotationAngle) static
Definition at line 184 of file pvrqwswsegl.c.
Referenced by wseglCreateWindowDrawable().
 {
     WSEGL_UNUSED(display);
     WSEGL_UNUSED(config);
     if (!nativePixmap)
         return WSEGL_BAD_NATIVE_PIXMAP;
     if (!pvrQwsAllocBuffers((PvrQwsDrawable *)nativePixmap))
         return WSEGL_OUT_OF_MEMORY;
     *drawable = (WSEGLDrawableHandle)nativePixmap;
     *rotationAngle = WSEGL_ROTATE_0;
     return WSEGL_SUCCESS;
 }
wseglCreateWindowDrawable()
static WSEGLError wseglCreateWindowDrawable (WSEGLDisplayHandle display, WSEGLConfig * config, WSEGLDrawableHandle * drawable, NativeWindowType nativeWindow, WSEGLRotationAngle * rotationAngle) static
Definition at line 147 of file pvrqwswsegl.c.
Referenced by wseglRotationValue().
 {
     PvrQwsDrawable *draw;
     WSEGL_UNUSED(display);
     WSEGL_UNUSED(config);
     /* Check for special handles that indicate framebuffer screens */
     if (nativeWindow >= (NativeWindowType)0 &&
             nativeWindow < (NativeWindowType)PVRQWS_MAX_SCREENS) {
         PvrQwsDrawable *screen = pvrQwsScreenWindow((int)nativeWindow);
         if (!screen)
             return WSEGL_OUT_OF_MEMORY;
         *drawable = (WSEGLDrawableHandle)screen;
         if (!pvrQwsAllocBuffers(screen))
             return WSEGL_OUT_OF_MEMORY;
         *rotationAngle = wseglRotationValue(screen->rotationAngle);
         return WSEGL_SUCCESS;
     }
     /* The native window is the winId - fetch the underlying drawable */
     draw = pvrQwsFetchWindow((long)nativeWindow);
     if (!draw)
         return WSEGL_BAD_DRAWABLE;
     /* The drawable is ready to go */
     *drawable = (WSEGLDrawableHandle)draw;
     *rotationAngle = wseglRotationValue(draw->rotationAngle);
     if (!pvrQwsAllocBuffers(draw))
         return WSEGL_OUT_OF_MEMORY;
     return WSEGL_SUCCESS;
 }
wseglDeleteDrawable()
static WSEGLError wseglDeleteDrawable (WSEGLDrawableHandle _drawable) static
Definition at line 200 of file pvrqwswsegl.c.
 {
     PvrQwsDrawable *drawable = (PvrQwsDrawable *)_drawable;
     if (!drawable || drawable->type == PvrQwsScreen)
         return WSEGL_SUCCESS;
     if (pvrQwsDisplay.numFlipBuffers == 0)
         pvrQwsFreeBuffers(drawable);
     if (pvrQwsReleaseWindow(drawable))
         pvrQwsDestroyDrawable(drawable);
     return WSEGL_SUCCESS;
 }
wseglGetDrawableParameters()
static WSEGLError wseglGetDrawableParameters (WSEGLDrawableHandle _drawable, WSEGLDrawableParams * sourceParams, WSEGLDrawableParams * renderParams) static
Definition at line 338 of file pvrqwswsegl.c.
Referenced by wseglCopyFromPBuffer().
 {
     PvrQwsDrawable *drawable = (PvrQwsDrawable *)_drawable;
     PVR2DMEMINFO *source, *render;
     WSEGLPixelFormat pixelFormat;
     if (!pvrQwsGetBuffers(drawable, &source, &render))
         return WSEGL_BAD_DRAWABLE;
     switch (drawable->pixelFormat) {
         case PVR2D_RGB565:
         default:
             pixelFormat = WSEGL_PIXELFORMAT_565;
             break;
     case PVR2D_ARGB4444:
             pixelFormat = WSEGL_PIXELFORMAT_4444;
             break;
     case PVR2D_ARGB8888:
             pixelFormat = WSEGL_PIXELFORMAT_8888;
             break;
     }
     sourceParams->ui32Width = drawable->rect.width;
     sourceParams->ui32Height = drawable->rect.height;
     sourceParams->ui32Stride = drawable->stridePixels;
     sourceParams->ePixelFormat = pixelFormat;
     sourceParams->pvLinearAddress = source->pBase;
     sourceParams->ui32HWAddress = source->ui32DevAddr;
     sourceParams->hPrivateData = source->hPrivateData;
     renderParams->ui32Width = drawable->rect.width;
     renderParams->ui32Height = drawable->rect.height;
     renderParams->ui32Stride = drawable->stridePixels;
     renderParams->ePixelFormat = pixelFormat;
     renderParams->pvLinearAddress = render->pBase;
     renderParams->ui32HWAddress = render->ui32DevAddr;
     renderParams->hPrivateData = render->hPrivateData;
     return WSEGL_SUCCESS;
 }
wseglInitializeDisplay()
static WSEGLError wseglInitializeDisplay (NativeDisplayType nativeDisplay, WSEGLDisplayHandle * display, const WSEGLCaps ** caps, WSEGLConfig ** configs) static
Definition at line 86 of file pvrqwswsegl.c.
Referenced by wseglIsDisplayValid().
 {
     WSEGLPixelFormat pixelFormat;
     /* Bail out if the native display is incorrect */
     if (nativeDisplay != WSEGL_DEFAULT_DISPLAY)
         return WSEGL_CANNOT_INITIALISE;
     /* Open the PVR/QWS display, which will initialize the framebuffer */
     if (!pvrQwsDisplayOpen())
         return WSEGL_CANNOT_INITIALISE;
     /* Convert the PVR2D pixel format into a WSEGL pixel format */
     switch (pvrQwsDisplay.screens[0].pixelFormat) {
         case PVR2D_RGB565:
             pixelFormat = WSEGL_PIXELFORMAT_565;
             break;
     case PVR2D_ARGB4444:
             pixelFormat = WSEGL_PIXELFORMAT_4444;
             break;
     case PVR2D_ARGB8888:
             pixelFormat = WSEGL_PIXELFORMAT_8888;
             break;
         default:
             pvrQwsDisplayClose();
             return WSEGL_CANNOT_INITIALISE;
     }
     wseglDisplayConfigs[0].ePixelFormat = pixelFormat;
     wseglDisplayConfigs[1].ePixelFormat = pixelFormat;
     /* The display has been initialized */
     *display = (WSEGLDisplayHandle)&pvrQwsDisplay;
     *caps = wseglDisplayCaps;
     *configs = wseglDisplayConfigs;
     return WSEGL_SUCCESS;
 }
wseglIsDisplayValid()
static WSEGLError wseglIsDisplayValid (NativeDisplayType nativeDisplay) static
Definition at line 75 of file pvrqwswsegl.c.
 {
     /* We only have the default display in this system */
     if (nativeDisplay == WSEGL_DEFAULT_DISPLAY)
         return WSEGL_SUCCESS;
     else
         return WSEGL_BAD_NATIVE_DISPLAY;
 }
wseglRotationValue()
static WSEGLRotationAngle wseglRotationValue (int degrees) static
Definition at line 135 of file pvrqwswsegl.c.
Referenced by wseglCreateWindowDrawable().
 {
     switch (degrees) {
     case 90:  return WSEGL_ROTATE_90;
     case 180: return WSEGL_ROTATE_180;
     case 270: return WSEGL_ROTATE_270;
     default:  return WSEGL_ROTATE_0;
     }
 }
wseglSwapControlInterval()
static WSEGLError wseglSwapControlInterval (WSEGLDrawableHandle drawable, unsigned long interval) static
Definition at line 226 of file pvrqwswsegl.c.
Referenced by wseglSwapDrawable().
 {
     WSEGL_UNUSED(drawable);
     if (pvrQwsDisplay.flipChain) {
         PVR2DSetPresentFlipProperties
             (pvrQwsDisplay.context, pvrQwsDisplay.flipChain,
              PVR2D_PRESENT_PROPERTY_INTERVAL, 0, 0, 0, NULL, interval);
     }
     return WSEGL_SUCCESS;
 }
wseglSwapDrawable()
static WSEGLError wseglSwapDrawable (WSEGLDrawableHandle _drawable, unsigned long data) static
Definition at line 214 of file pvrqwswsegl.c.
Referenced by wseglDeleteDrawable().
 {
     WSEGL_UNUSED(data);
     PvrQwsDrawable *drawable = (PvrQwsDrawable *)_drawable;
     if (drawable->type != PvrQwsPixmap && !pvrQwsSwapBuffers(drawable, 0))
         return WSEGL_BAD_DRAWABLE;
     else
         return WSEGL_SUCCESS;
 }
wseglWaitNative()
static WSEGLError wseglWaitNative (WSEGLDrawableHandle drawable, unsigned long engine) static
Definition at line 239 of file pvrqwswsegl.c.
Referenced by wseglSwapControlInterval().
 {
     WSEGL_UNUSED(drawable);
     if (engine == WSEGL_DEFAULT_NATIVE_ENGINE)
         return WSEGL_SUCCESS;
     else
         return WSEGL_BAD_NATIVE_ENGINE;
 }
Variable Documentation
wseglDisplayCaps
WSEGLCaps const wseglDisplayCaps[] static
Initial value:
= {
    {WSEGL_CAP_WINDOWS_USE_HW_SYNC, 1},
    {WSEGL_CAP_PIXMAPS_USE_HW_SYNC, 1},
    {WSEGL_NO_CAPS, 0}
}
Definition at line 59 of file pvrqwswsegl.c.
Referenced by wseglInitializeDisplay().
wseglDisplayConfigs
WSEGLConfig wseglDisplayConfigs[] static
Initial value:
= {
    {WSEGL_DRAWABLE_WINDOW, WSEGL_PIXELFORMAT_565, WSEGL_FALSE,
     0, 0, 0, WSEGL_OPAQUE, 0},
    {WSEGL_DRAWABLE_PIXMAP, WSEGL_PIXELFORMAT_565, WSEGL_FALSE,
     0, 0, 0, WSEGL_OPAQUE, 0},
    {WSEGL_NO_DRAWABLE, 0, 0, 0, 0, 0, 0, 0}
}
Definition at line 66 of file pvrqwswsegl.c.
Referenced by wseglInitializeDisplay().
wseglFunctions
WSEGL_FunctionTable const wseglFunctions static
Initial value:
= {
    WSEGL_VERSION,
    wseglIsDisplayValid,
    wseglInitializeDisplay,
    wseglCloseDisplay,
    wseglCreateWindowDrawable,
    wseglCreatePixmapDrawable,
    wseglDeleteDrawable,
    wseglSwapDrawable,
    wseglSwapControlInterval,
    wseglWaitNative,
    wseglCopyFromDrawable,
    wseglCopyFromPBuffer,
    wseglGetDrawableParameters
}
Definition at line 382 of file pvrqwswsegl.c.
Referenced by WSEGL_GetFunctionTablePointer().