Qt 4.8: /src/corelib/kernel/qabstracteventdispatcher_p.h File Reference
qabstracteventdispatcher_p.h File Reference
#include "QtCore/qabstracteventdispatcher.h"
#include "private/qobject_p.h"
Classes
class QAbstractEventDispatcherPrivate
Functions
Q_CORE_EXPORT uint qGlobalPostedEventsCount ()
Function Documentation
qGlobalPostedEventsCount()
Q_CORE_EXPORT uint qGlobalPostedEventsCount ()
Definition at line 348 of file qcoreapplication.cpp.
Referenced by QEventDispatcherQPA::hasPendingEvents(), QEventDispatcherX11::hasPendingEvents(), QEventDispatcherQWS::hasPendingEvents(), QEventDispatcherMac::hasPendingEvents(), and QEventDispatcherUNIX::hasPendingEvents().
 {
     QThreadData *currentThreadData = QThreadData::current();
     return currentThreadData->postEventList.size() - currentThreadData->postEventList.startOffset;
 }