Qt 4.8: /src/network/socket/qabstractsocket.cpp File Reference
qabstractsocket.cpp File Reference
#include "qabstractsocket.h"
#include "qabstractsocket_p.h"
#include "private/qhostinfo_p.h"
#include "private/qnetworksession_p.h"
#include <qabstracteventdispatcher.h>
#include <qhostaddress.h>
#include <qhostinfo.h>
#include <qmetaobject.h>
#include <qpointer.h>
#include <qtimer.h>
#include <qelapsedtimer.h>
#include <qscopedvaluerollback.h>
#include <QtNetwork/qsslsocket.h>
#include <private/qthread_p.h>
#include <time.h>
#include "moc_qabstractsocket.cpp"
Macros
#define Q_CHECK_SOCKETENGINE(returnValue)
#define QABSTRACTSOCKET_BUFFERSIZE 32768
#define QT_CONNECT_TIMEOUT 30000
#define QT_TRANSFER_TIMEOUT 120000
Functions
static bool isProxyError (QAbstractSocket::SocketError error)
Q_NETWORK_EXPORT QDebug operator<< (QDebug debug, QAbstractSocket::SocketError error)
Q_NETWORK_EXPORT QDebug operator<< (QDebug debug, QAbstractSocket::SocketState state)
static int qt_timeout_value (int msecs, int elapsed)
Macro Definition Documentation
Q_CHECK_SOCKETENGINE
#define Q_CHECK_SOCKETENGINE (returnValue)
Value:
do { \
    if (!d->socketEngine) { \
        return returnValue; \
    } } while (0)
Definition at line 429 of file qabstractsocket.cpp.
Referenced by QAbstractSocket::flush().
QABSTRACTSOCKET_BUFFERSIZE
#define QABSTRACTSOCKET_BUFFERSIZE 32768
Definition at line 435 of file qabstractsocket.cpp.
QT_CONNECT_TIMEOUT
#define QT_CONNECT_TIMEOUT 30000
Definition at line 437 of file qabstractsocket.cpp.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress(), and QAbstractSocket::waitForConnected().
QT_TRANSFER_TIMEOUT
#define QT_TRANSFER_TIMEOUT 120000
Definition at line 438 of file qabstractsocket.cpp.
Function Documentation
isProxyError()
static bool isProxyError (QAbstractSocket::SocketError error) static
Definition at line 478 of file qabstractsocket.cpp.
Referenced by QAbstractSocketPrivate::_q_testConnection().
 {
     switch (error) {
     case QAbstractSocket::ProxyAuthenticationRequiredError:
     case QAbstractSocket::ProxyConnectionRefusedError:
     case QAbstractSocket::ProxyConnectionClosedError:
     case QAbstractSocket::ProxyConnectionTimeoutError:
     case QAbstractSocket::ProxyNotFoundError:
     case QAbstractSocket::ProxyProtocolError:
         return true;
     default:
         return false;
     }
 }
operator<<() [1/2]
Q_NETWORK_EXPORT QDebug operator<< (QDebug debug, QAbstractSocket::SocketError error)
Definition at line 2957 of file qabstractsocket.cpp.
 {
     switch (error) {
     case QAbstractSocket::ConnectionRefusedError:
         debug << "QAbstractSocket::ConnectionRefusedError";
         break;
     case QAbstractSocket::RemoteHostClosedError:
         debug << "QAbstractSocket::RemoteHostClosedError";
         break;
     case QAbstractSocket::HostNotFoundError:
         debug << "QAbstractSocket::HostNotFoundError";
         break;
     case QAbstractSocket::SocketAccessError:
         debug << "QAbstractSocket::SocketAccessError";
         break;
     case QAbstractSocket::SocketResourceError:
         debug << "QAbstractSocket::SocketResourceError";
         break;
     case QAbstractSocket::SocketTimeoutError:
         debug << "QAbstractSocket::SocketTimeoutError";
         break;
     case QAbstractSocket::DatagramTooLargeError:
         debug << "QAbstractSocket::DatagramTooLargeError";
         break;
     case QAbstractSocket::NetworkError:
         debug << "QAbstractSocket::NetworkError";
         break;
     case QAbstractSocket::AddressInUseError:
         debug << "QAbstractSocket::AddressInUseError";
         break;
     case QAbstractSocket::SocketAddressNotAvailableError:
         debug << "QAbstractSocket::SocketAddressNotAvailableError";
         break;
     case QAbstractSocket::UnsupportedSocketOperationError:
         debug << "QAbstractSocket::UnsupportedSocketOperationError";
         break;
     case QAbstractSocket::UnfinishedSocketOperationError:
         debug << "QAbstractSocket::UnfinishedSocketOperationError";
         break;
     case QAbstractSocket::ProxyAuthenticationRequiredError:
         debug << "QAbstractSocket::ProxyAuthenticationRequiredError";
         break;
     case QAbstractSocket::UnknownSocketError:
         debug << "QAbstractSocket::UnknownSocketError";
         break;
     case QAbstractSocket::ProxyConnectionRefusedError:
         debug << "QAbstractSocket::ProxyConnectionRefusedError";
         break;
     case QAbstractSocket::ProxyConnectionClosedError:
         debug << "QAbstractSocket::ProxyConnectionClosedError";
         break;
     case QAbstractSocket::ProxyConnectionTimeoutError:
         debug << "QAbstractSocket::ProxyConnectionTimeoutError";
         break;
     case QAbstractSocket::ProxyNotFoundError:
         debug << "QAbstractSocket::ProxyNotFoundError";
         break;
     case QAbstractSocket::ProxyProtocolError:
         debug << "QAbstractSocket::ProxyProtocolError";
         break;
     default:
         debug << "QAbstractSocket::SocketError(" << int(error) << ')';
         break;
     }
     return debug;
 }
operator<<() [2/2]
Q_NETWORK_EXPORT QDebug operator<< (QDebug debug, QAbstractSocket::SocketState state)
Definition at line 3024 of file qabstractsocket.cpp.
 {
     switch (state) {
     case QAbstractSocket::UnconnectedState:
         debug << "QAbstractSocket::UnconnectedState";
         break;
     case QAbstractSocket::HostLookupState:
         debug << "QAbstractSocket::HostLookupState";
         break;
     case QAbstractSocket::ConnectingState:
         debug << "QAbstractSocket::ConnectingState";
         break;
     case QAbstractSocket::ConnectedState:
         debug << "QAbstractSocket::ConnectedState";
         break;
     case QAbstractSocket::BoundState:
         debug << "QAbstractSocket::BoundState";
         break;
     case QAbstractSocket::ListeningState:
         debug << "QAbstractSocket::ListeningState";
         break;
     case QAbstractSocket::ClosingState:
         debug << "QAbstractSocket::ClosingState";
         break;
     default:
         debug << "QAbstractSocket::SocketState(" << int(state) << ')';
         break;
     }
     return debug;
 }
qt_timeout_value()
static int qt_timeout_value (int msecs, int elapsed) static
Definition at line 1820 of file qabstractsocket.cpp.
Referenced by QAbstractSocket::waitForBytesWritten(), QAbstractSocket::waitForConnected(), QAbstractSocket::waitForDisconnected(), and QAbstractSocket::waitForReadyRead().
 {
     if (msecs == -1)
         return -1;
     int timeout = msecs - elapsed;
     return timeout < 0 ? 0 : timeout;
 }