Qt 4.8: /src/corelib/kernel/qabstracteventdispatcher.cpp File Reference
qabstracteventdispatcher.cpp File Reference
#include "qabstracteventdispatcher.h"
#include "qabstracteventdispatcher_p.h"
#include "qthread.h"
#include <private/qthread_p.h>
#include <private/qcoreapplication_p.h>
Macros
#define q_static_assert(expr) (void)QStaticAssertType<expr>::Value
Enumerations
enum {
FirstBucketOffset = 0, SecondBucketOffset = sizeof(FirstBucket) / sizeof(FirstBucket[0]), ThirdBucketOffset = 0x100, FourthBucketOffset = 0x1000,
FifthBucketOffset = 0x10000, SixthBucketOffset = 0x100000
}
enum {
FirstBucketSize = SecondBucketOffset, SecondBucketSize = ThirdBucketOffset - SecondBucketOffset, ThirdBucketSize = FourthBucketOffset - ThirdBucketOffset, FourthBucketSize = FifthBucketOffset - FourthBucketOffset,
FifthBucketSize = SixthBucketOffset - FifthBucketOffset, SixthBucketSize = MaxTimerId - SixthBucketOffset
}
enum { NumberOfBuckets = sizeof(BucketSize) / sizeof(BucketSize[0]) }
Functions
static int * allocateBucket (int bucket)
static int bucketIndex (int bucket, int timerId)
static int bucketOffset (int timerId)
static int prepareNewValueWithSerialNumber (int oldId, int newId)
static void timerIdsDestructorFunction ()
Variables
static const int BucketOffset []
static const int BucketSize []
static int FirstBucket []
static const int MaxTimerId = TimerIdMask
static QBasicAtomicInt nextFreeTimerId = Q_BASIC_ATOMIC_INITIALIZER(1)
static const int TimerIdMask = 0x00ffffff
static QBasicAtomicPointer< int > timerIds []
static const int TimerSerialCounter = TimerIdMask + 1
static const int TimerSerialMask = ~TimerIdMask & ~0x80000000
Macro Definition Documentation
q_static_assert
#define q_static_assert (expr) (void)QStaticAssertType<expr>::Value
Definition at line 119 of file qabstracteventdispatcher.cpp.
Referenced by bucketOffset().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FirstBucketOffset
SecondBucketOffset
ThirdBucketOffset
FourthBucketOffset
FifthBucketOffset
SixthBucketOffset
Definition at line 62 of file qabstracteventdispatcher.cpp.
      {
     FirstBucketOffset  = 0,
     SecondBucketOffset = sizeof(FirstBucket) / sizeof(FirstBucket[0]),
     ThirdBucketOffset  = 0x100,
     FourthBucketOffset = 0x1000,
     FifthBucketOffset  = 0x10000,
     SixthBucketOffset  = 0x100000
 };
anonymous enum
anonymous enum
Enumerator
FirstBucketSize
SecondBucketSize
ThirdBucketSize
FourthBucketSize
FifthBucketSize
SixthBucketSize
Definition at line 71 of file qabstracteventdispatcher.cpp.
      {
     FirstBucketSize  = SecondBucketOffset,
     SecondBucketSize = ThirdBucketOffset - SecondBucketOffset,
     ThirdBucketSize  = FourthBucketOffset - ThirdBucketOffset,
     FourthBucketSize = FifthBucketOffset - FourthBucketOffset,
     FifthBucketSize  = SixthBucketOffset - FifthBucketOffset,
     SixthBucketSize  = MaxTimerId - SixthBucketOffset
 };
anonymous enum
anonymous enum
Enumerator
NumberOfBuckets
Definition at line 84 of file qabstracteventdispatcher.cpp.
 { NumberOfBuckets = sizeof(BucketSize) / sizeof(BucketSize[0]) };
Function Documentation
allocateBucket()
static int* allocateBucket (int bucket) inline static
Definition at line 140 of file qabstracteventdispatcher.cpp.
Referenced by QAbstractEventDispatcherPrivate::allocateTimerId().
 {
     // allocate a new bucket
     const int size = BucketSize[bucket];
     const int offset = BucketOffset[bucket];
     int *b = new int[size];
     for (int i = 0; i != size; ++i)
         b[i] = offset + i + 1;
     return b;
 }
bucketIndex()
static int bucketIndex (int bucket, int timerId) inline static
Definition at line 135 of file qabstracteventdispatcher.cpp.
Referenced by QAbstractEventDispatcherPrivate::allocateTimerId(), and QAbstractEventDispatcherPrivate::releaseTimerId().
 {
     return timerId - BucketOffset[bucket];
 }
bucketOffset()
static int bucketOffset (int timerId) inline static
Definition at line 121 of file qabstracteventdispatcher.cpp.
Referenced by QAbstractEventDispatcherPrivate::allocateTimerId(), and QAbstractEventDispatcherPrivate::releaseTimerId().
 {
     q_static_assert(sizeof BucketSize == sizeof BucketOffset);
     q_static_assert(sizeof(timerIds) / sizeof(timerIds[0]) == NumberOfBuckets);
     for (int i = 0; i < NumberOfBuckets; ++i) {
         if (timerId < BucketSize[i])
             return i;
         timerId -= BucketSize[i];
     }
     qFatal("QAbstractEventDispatcher: INTERNAL ERROR, timer ID %d is too large", timerId);
     return -1;
 }
prepareNewValueWithSerialNumber()
static int prepareNewValueWithSerialNumber (int oldId, int newId) inline static
Definition at line 110 of file qabstracteventdispatcher.cpp.
Referenced by QAbstractEventDispatcherPrivate::allocateTimerId(), and QAbstractEventDispatcherPrivate::releaseTimerId().
 {
     return (newId & TimerIdMask) | ((oldId + TimerSerialCounter) & TimerSerialMask);
 }
timerIdsDestructorFunction()
static void timerIdsDestructorFunction () static
Definition at line 99 of file qabstracteventdispatcher.cpp.
 {
     // start at one, the first bucket is pre-allocated
     for (int i = 1; i < NumberOfBuckets; ++i)
         delete [] static_cast<int *>(timerIds[i]);
 }
Variable Documentation
BucketOffset
const int BucketOffset[] static
Initial value:
= {
    FirstBucketOffset, SecondBucketOffset, ThirdBucketOffset,
    FourthBucketOffset, FifthBucketOffset, SixthBucketOffset
}
Definition at line 86 of file qabstracteventdispatcher.cpp.
Referenced by allocateBucket(), bucketIndex(), and bucketOffset().
BucketSize
const int BucketSize[] static
Initial value:
= {
    FirstBucketSize, SecondBucketSize, ThirdBucketSize,
    FourthBucketSize, FifthBucketSize, SixthBucketSize
}
Definition at line 80 of file qabstracteventdispatcher.cpp.
Referenced by allocateBucket(), and bucketOffset().
FirstBucket
int FirstBucket[] static
Initial value:
= {
     1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32
}
Definition at line 57 of file qabstracteventdispatcher.cpp.
MaxTimerId
const int MaxTimerId = TimerIdMask static
Definition at line 55 of file qabstracteventdispatcher.cpp.
nextFreeTimerId
QBasicAtomicInt nextFreeTimerId = Q_BASIC_ATOMIC_INITIALIZER(1) static
Definition at line 107 of file qabstracteventdispatcher.cpp.
Referenced by QAbstractEventDispatcherPrivate::allocateTimerId(), and QAbstractEventDispatcherPrivate::releaseTimerId().
TimerIdMask
const int TimerIdMask = 0x00ffffff static
Definition at line 52 of file qabstracteventdispatcher.cpp.
Referenced by QAbstractEventDispatcherPrivate::allocateTimerId(), prepareNewValueWithSerialNumber(), and QAbstractEventDispatcherPrivate::releaseTimerId().
timerIds
QBasicAtomicPointer<int> timerIds[] static
Initial value:
=
    { Q_BASIC_ATOMIC_INITIALIZER(FirstBucket),
      Q_BASIC_ATOMIC_INITIALIZER(0),
      Q_BASIC_ATOMIC_INITIALIZER(0),
      Q_BASIC_ATOMIC_INITIALIZER(0),
      Q_BASIC_ATOMIC_INITIALIZER(0),
      Q_BASIC_ATOMIC_INITIALIZER(0) }
Definition at line 91 of file qabstracteventdispatcher.cpp.
Referenced by QAbstractEventDispatcherPrivate::allocateTimerId(), bucketOffset(), and QAbstractEventDispatcherPrivate::releaseTimerId().
TimerSerialCounter
const int TimerSerialCounter = TimerIdMask + 1 static
Definition at line 54 of file qabstracteventdispatcher.cpp.
Referenced by prepareNewValueWithSerialNumber().
TimerSerialMask
const int TimerSerialMask = ~TimerIdMask & ~0x80000000 static
Definition at line 53 of file qabstracteventdispatcher.cpp.
Referenced by prepareNewValueWithSerialNumber().