Qt 4.8: /src/gui/accessible/qaccessible_mac.mm File Reference
qaccessible_mac.mm File Reference
#include "qaccessible.h"
#include "qaccessible_mac_p.h"
#include "qhash.h"
#include "qset.h"
#include "qpointer.h"
#include "qapplication.h"
#include "qmainwindow.h"
#include "qtextdocument.h"
#include "qdebug.h"
#include "qabstractslider.h"
#include "qsplitter.h"
#include "qtabwidget.h"
#include "qlistview.h"
#include "qtableview.h"
#include "qdockwidget.h"
#include <private/qt_mac_p.h>
#include <private/qwidget_p.h>
#include <CoreFoundation/CoreFoundation.h>
#include "qaccessible_mac_carbon.cpp"
Classes
struct IsWindowAndNotDrawerOrSheetTest
struct IsWindowTest
struct QAccessibleTextBinding
class QItemViewInterfaceFactory
class QMultipleHIObjectFactory
class QStandardInterfaceFactory
Macros
#define QAXApplicationRole kAXApplicationRole
#define QAXButtonRole kAXButtonRole
#define QAXCancelAction kAXCancelAction
#define QAXCheckBoxRole kAXCheckBoxRole
#define QAXChildrenAttribute kAXChildrenAttribute
#define QAXCloseButtonAttribute kAXCloseButtonAttribute
#define QAXColumnRole kAXColumnRole
#define QAXConfirmAction kAXConfirmAction
#define QAXContentsAttribute kAXContentsAttribute
#define QAXDecrementAction kAXDecrementAction
#define QAXDecrementArrowSubrole kAXDecrementArrowSubrole
#define QAXDecrementPageSubrole kAXDecrementPageSubrole
#define QAXDescriptionAttribute kAXDescriptionAttribute
#define QAXEnabledAttribute kAXEnabledAttribute
#define QAXExpandedAttribute kAXExpandedAttribute
#define QAXFocusedAttribute kAXFocusedAttribute
#define QAXFocusedUIElementChangedNotification kAXFocusedUIElementChangedNotification
#define QAXFocusedWindowChangedNotification kAXFocusedWindowChangedNotification
#define QAXGroupRole kAXGroupRole
#define QAXGrowAreaAttribute kAXGrowAreaAttribute
#define QAXGrowAreaRole kAXGrowAreaRole
#define QAXHelpAttribute kAXHelpAttribute
#define QAXHorizontalOrientationValue kAXHorizontalOrientationValue
#define QAXHorizontalScrollBarAttribute kAXHorizontalScrollBarAttribute
#define QAXIncrementAction kAXIncrementAction
#define QAXIncrementArrowSubrole kAXIncrementArrowSubrole
#define QAXIncrementorRole kAXIncrementorRole
#define QAXIncrementPageSubrole kAXIncrementPageSubrole
#define QAXLinkedUIElementsAttribute kAXLinkedUIElementsAttribute
#define QAXListRole kAXListRole
#define QAXMainAttribute kAXMainAttribute
#define QAXMaxValueAttribute kAXMaxValueAttribute
#define QAXMenuBarRole kAXMenuBarRole
#define QAXMenuButtonRole kAXMenuButtonRole
#define QAXMenuClosedNotification kAXMenuClosedNotification
#define QAXMenuItemRole kAXMenuItemRole
#define QAXMenuOpenedNotification kAXMenuOpenedNotification
#define QAXMenuRole kAXMenuRole
#define QAXMinimizeButtonAttribute kAXMinimizeButtonAttribute
#define QAXMinimizedAttribute kAXMinimizedAttribute
#define QAXMinValueAttribute kAXMinValueAttribute
#define QAXNextContentsAttribute kAXNextContentsAttribute
#define QAXOrientationAttribute kAXOrientationAttribute
#define QAXParentAttribute kAXParentAttribute
#define QAXPickAction kAXPickAction
#define QAXPopUpButtonRole kAXPopUpButtonRole
#define QAXPositionAttribute kAXPositionAttribute
#define QAXPressAction kAXPressAction
#define QAXPreviousContentsAttribute kAXPreviousContentsAttribute
#define QAXProgressIndicatorRole kAXProgressIndicatorRole
#define QAXRadioButtonRole kAXRadioButtonRole
#define QAXRoleAttribute kAXRoleAttribute
#define QAXRoleDescriptionAttribute kAXRoleDescriptionAttribute
#define QAXRowRole kAXRowRole
#define QAXRowsAttribute kAXRowsAttribute
#define QAXScrollAreaRole kAXScrollAreaRole
#define QAXScrollBarRole kAXScrollBarRole
#define QAXSelectedAttribute kAXSelectedAttribute
#define QAXSelectedChildrenAttribute kAXSelectedChildrenAttribute
#define QAXSelectedRowsAttribute kAXSelectedRowsAttribute
#define QAXSizeAttribute kAXSizeAttribute
#define QAXSliderRole kAXSliderRole
#define QAXSplitGroupRole kAXSplitGroupRole
#define QAXSplitterRole kAXSplitterRole
#define QAXSplittersAttribute kAXSplittersAttribute
#define QAXStaticTextRole kAXStaticTextRole
#define QAXSubroleAttribute kAXSubroleAttribute
#define QAXTabGroupRole kAXTabGroupRole
#define QAXTableRole kAXTableRole
#define QAXTabsAttribute kAXTabsAttribute
#define QAXTextFieldRole kAXTextFieldRole
#define QAXTitleAttribute kAXTitleAttribute
#define QAXTitleUIElementAttribute kAXTitleUIElementAttribute
#define QAXToolbarButtonAttribute kAXToolbarButtonAttribute
#define QAXToolbarRole kAXToolbarRole
#define QAXTopLevelUIElementAttribute kAXTopLevelUIElementAttribute
#define QAXUnknownRole kAXUnknownRole
#define QAXValueAttribute kAXValueAttribute
#define QAXValueChangedNotification kAXValueChangedNotification
#define QAXValueIndicatorRole kAXValueIndicatorRole
#define QAXVerticalOrientationValue kAXVerticalOrientationValue
#define QAXVerticalScrollBarAttribute kAXVerticalScrollBarAttribute
#define QAXVisibleRowsAttribute kAXVisibleRowsAttribute
#define QAXWindowAttribute kAXWindowAttribute
#define QAXWindowCreatedNotification kAXWindowCreatedNotification
#define QAXWindowMovedNotification kAXWindowMovedNotification
#define QAXWindowRole kAXWindowRole
#define QAXZoomButtonAttribute kAXZoomButtonAttribute
Typedefs
typedef CFStringRef const QAXRoleType
Functions
static OSStatus accessibilityEventHandler (EventHandlerCallRef next_ref, EventRef event, void *data)
static void appendIfSupported (CFMutableArrayRef array, CFStringRef attribute, const QAInterface &interface)
static OSStatus applicationEventHandler (EventHandlerCallRef next_ref, EventRef event, void *)
static int buttonValue (QAInterface element)
static QInterfaceFactory * createFactory (const QAInterface &interface)
static AXUIElementRef getAccessibleObjectParameter (EventRef event)
static OSStatus getAllActionNames (EventHandlerCallRef next_ref, EventRef event, const QAInterface &interface)
static OSStatus getAllAttributeNames (EventRef event, const QAInterface &interface, EventHandlerCallRef next_ref)
static OSStatus getChildAtPoint (EventHandlerCallRef next_ref, EventRef event, QAInterface &interface)
static OSStatus getNamedAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface &interface)
static QString getValue (const QAInterface &interface)
static OSStatus handleChildrenAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface &interface)
static OSStatus handleContentsAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface &interface)
static OSStatus handleOrientationAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface &interface)
static OSStatus handleParentAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface &interface)
static OSStatus handlePositionAttribute (EventHandlerCallRef, EventRef event, const QAInterface &interface)
static OSStatus handleRowsAttribute (EventHandlerCallRef, EventRef event, QAInterface &tableView)
static OSStatus handleScrollBarAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface &scrollArea, Qt::Orientation orientation)
static OSStatus handleSelectedRowsAttribute (EventHandlerCallRef, EventRef event, QAInterface &tableView)
static OSStatus handleSizeAttribute (EventHandlerCallRef, EventRef event, const QAInterface &interface)
static OSStatus handleSplitterContentsAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface &interface, QCFString nextOrPrev)
static OSStatus handleSplittersAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface &interface)
static void handleStringAttribute (EventRef event, QAccessible::Text text, const QAInterface &interface)
static OSStatus handleSubroleAttribute (EventHandlerCallRef, EventRef event, const QAInterface &interface)
static OSStatus handleTabsAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface &interface)
static OSStatus handleTopLevelUIElementAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface &interface)
static OSStatus handleVisibleRowsAttribute (EventHandlerCallRef, EventRef event, QAInterface &tableView)
static OSStatus handleWindowAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface &interface)
static bool isEmbeddedTabBar (const QAInterface &interface)
static bool isItemView (const QAInterface &interface)
bool isItInteresting (const QAInterface &interface)
static OSStatus isNamedAttributeSettable (EventRef event, const QAInterface &interface)
static bool isStandaloneTabBar (const QAInterface &interface)
static bool isTabWidget (const QAInterface &interface)
QList< QAElement > lookup (const QList< QAInterface > &interfaces)
static CFStringRef macRole (const QAInterface &interface)
static bool managesChildren (const QAInterface &interface)
template<typename TestType >
OSStatus navigateAncestors (EventHandlerCallRef next_ref, EventRef event, const QAInterface &interface, CFStringRef attribute)
QDebug operator<< (QDebug debug, const QAInterface &interface)
static OSStatus performNamedAction (EventHandlerCallRef next_ref, EventRef event, const QAInterface &interface)
Q_GLOBAL_STATIC (QAccessibleHierarchyManager, accessibleHierarchyManager)
uint qHash (const QAInterface &item)
uint qHash (QAElement element)
static bool qt_mac_append_cf_uniq (CFMutableArrayRef array, CFTypeRef value)
bool qt_mac_is_macdrawer (const QWidget *w)
bool qt_mac_is_macsheet (const QWidget *w)
static QAElement scrollAreaGetContents (const QAInterface &scrollArea)
static QAElement scrollAreaGetScrollBar (const QAInterface &scrollArea, Qt::Orientation orientation)
static QAInterface scrollAreaGetScrollBarInterface (const QAInterface &scrollArea, Qt::Orientation orientation)
static bool scrollAreaHasScrollBar (const QAInterface &scrollArea, Qt::Orientation orientation)
static Qt::Orientation scrollBarOrientation (const QAInterface &scrollBar)
static OSStatus setAttributeValue (EventRef event, const QList< QAElement > &elements)
static OSStatus setNamedAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface &interface)
static QCFString subrole (const QAInterface &interface)
static QList< QAccessible::Action > supportedPredefinedActions (const QAInterface &interface)
static bool supportsAttribute (CFStringRef attribute, const QAInterface &interface)
static QList< QAElement > tabBarGetTabs (const QAInterface &interface)
static QList< QAElement > tabWidgetGetChildren (const QAInterface &interface)
static QAElement tabWidgetGetContents (const QAInterface &interface)
static QList< QAElement > tabWidgetGetTabs (const QAInterface &interface)
static int textForRoleAndAttribute (QAccessible::Role role, CFStringRef attribute)
static QCFString translateAction (const QAccessible::Action action)
static QAccessible::Action translateAction (const CFStringRef actionName)
Variables
static QObject * rootObject = 0
struct QAccessibleTextBinding text_bindings [][10]
Macro Definition Documentation
QAXApplicationRole
#define QAXApplicationRole kAXApplicationRole
Definition at line 164 of file qaccessible_mac.mm.
QAXButtonRole
#define QAXButtonRole kAXButtonRole
Definition at line 165 of file qaccessible_mac.mm.
QAXCancelAction
#define QAXCancelAction kAXCancelAction
Definition at line 166 of file qaccessible_mac.mm.
Referenced by translateAction().
QAXCheckBoxRole
#define QAXCheckBoxRole kAXCheckBoxRole
Definition at line 167 of file qaccessible_mac.mm.
QAXChildrenAttribute
#define QAXChildrenAttribute kAXChildrenAttribute
Definition at line 168 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), getNamedAttribute(), and supportsAttribute().
QAXCloseButtonAttribute
#define QAXCloseButtonAttribute kAXCloseButtonAttribute
Definition at line 169 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXColumnRole
#define QAXColumnRole kAXColumnRole
Definition at line 170 of file qaccessible_mac.mm.
QAXConfirmAction
#define QAXConfirmAction kAXConfirmAction
Definition at line 171 of file qaccessible_mac.mm.
Referenced by translateAction().
QAXContentsAttribute
#define QAXContentsAttribute kAXContentsAttribute
Definition at line 172 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXDecrementAction
#define QAXDecrementAction kAXDecrementAction
Definition at line 173 of file qaccessible_mac.mm.
Referenced by translateAction().
QAXDecrementArrowSubrole
#define QAXDecrementArrowSubrole kAXDecrementArrowSubrole
Definition at line 174 of file qaccessible_mac.mm.
Referenced by subrole().
QAXDecrementPageSubrole
#define QAXDecrementPageSubrole kAXDecrementPageSubrole
Definition at line 175 of file qaccessible_mac.mm.
Referenced by subrole().
QAXDescriptionAttribute
#define QAXDescriptionAttribute kAXDescriptionAttribute
Definition at line 176 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), getNamedAttribute(), and textForRoleAndAttribute().
QAXEnabledAttribute
#define QAXEnabledAttribute kAXEnabledAttribute
Definition at line 177 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXExpandedAttribute
#define QAXExpandedAttribute kAXExpandedAttribute
Definition at line 178 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
QAXFocusedAttribute
#define QAXFocusedAttribute kAXFocusedAttribute
Definition at line 179 of file qaccessible_mac.mm.
Referenced by getNamedAttribute(), isNamedAttributeSettable(), and setNamedAttribute().
QAXFocusedUIElementChangedNotification
#define QAXFocusedUIElementChangedNotification kAXFocusedUIElementChangedNotification
Definition at line 180 of file qaccessible_mac.mm.
Referenced by QAccessible::updateAccessibility().
QAXFocusedWindowChangedNotification
#define QAXFocusedWindowChangedNotification kAXFocusedWindowChangedNotification
Definition at line 181 of file qaccessible_mac.mm.
Referenced by QAccessible::updateAccessibility().
QAXGroupRole
#define QAXGroupRole kAXGroupRole
Definition at line 182 of file qaccessible_mac.mm.
QAXGrowAreaAttribute
#define QAXGrowAreaAttribute kAXGrowAreaAttribute
Definition at line 183 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXGrowAreaRole
#define QAXGrowAreaRole kAXGrowAreaRole
Definition at line 184 of file qaccessible_mac.mm.
QAXHelpAttribute
#define QAXHelpAttribute kAXHelpAttribute
Definition at line 185 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), getNamedAttribute(), and textForRoleAndAttribute().
QAXHorizontalOrientationValue
#define QAXHorizontalOrientationValue kAXHorizontalOrientationValue
Definition at line 186 of file qaccessible_mac.mm.
Referenced by handleOrientationAttribute().
QAXHorizontalScrollBarAttribute
#define QAXHorizontalScrollBarAttribute kAXHorizontalScrollBarAttribute
Definition at line 187 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXIncrementAction
#define QAXIncrementAction kAXIncrementAction
Definition at line 188 of file qaccessible_mac.mm.
Referenced by translateAction().
QAXIncrementArrowSubrole
#define QAXIncrementArrowSubrole kAXIncrementArrowSubrole
Definition at line 189 of file qaccessible_mac.mm.
Referenced by subrole().
QAXIncrementorRole
#define QAXIncrementorRole kAXIncrementorRole
Definition at line 191 of file qaccessible_mac.mm.
QAXIncrementPageSubrole
#define QAXIncrementPageSubrole kAXIncrementPageSubrole
Definition at line 190 of file qaccessible_mac.mm.
Referenced by subrole().
QAXLinkedUIElementsAttribute
#define QAXLinkedUIElementsAttribute kAXLinkedUIElementsAttribute
Definition at line 192 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXListRole
#define QAXListRole kAXListRole
Definition at line 193 of file qaccessible_mac.mm.
QAXMainAttribute
#define QAXMainAttribute kAXMainAttribute
Definition at line 194 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames().
QAXMaxValueAttribute
#define QAXMaxValueAttribute kAXMaxValueAttribute
Definition at line 195 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXMenuBarRole
#define QAXMenuBarRole kAXMenuBarRole
Definition at line 196 of file qaccessible_mac.mm.
QAXMenuButtonRole
#define QAXMenuButtonRole kAXMenuButtonRole
Definition at line 197 of file qaccessible_mac.mm.
QAXMenuClosedNotification
#define QAXMenuClosedNotification kAXMenuClosedNotification
Definition at line 198 of file qaccessible_mac.mm.
Referenced by QAccessible::updateAccessibility().
QAXMenuItemRole
#define QAXMenuItemRole kAXMenuItemRole
Definition at line 199 of file qaccessible_mac.mm.
QAXMenuOpenedNotification
#define QAXMenuOpenedNotification kAXMenuOpenedNotification
Definition at line 200 of file qaccessible_mac.mm.
Referenced by QAccessible::updateAccessibility().
QAXMenuRole
#define QAXMenuRole kAXMenuRole
Definition at line 201 of file qaccessible_mac.mm.
QAXMinimizeButtonAttribute
#define QAXMinimizeButtonAttribute kAXMinimizeButtonAttribute
Definition at line 203 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXMinimizedAttribute
#define QAXMinimizedAttribute kAXMinimizedAttribute
Definition at line 204 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXMinValueAttribute
#define QAXMinValueAttribute kAXMinValueAttribute
Definition at line 202 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXNextContentsAttribute
#define QAXNextContentsAttribute kAXNextContentsAttribute
Definition at line 205 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXOrientationAttribute
#define QAXOrientationAttribute kAXOrientationAttribute
Definition at line 206 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXParentAttribute
#define QAXParentAttribute kAXParentAttribute
Definition at line 207 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
QAXPickAction
#define QAXPickAction kAXPickAction
Definition at line 208 of file qaccessible_mac.mm.
Referenced by translateAction().
QAXPopUpButtonRole
#define QAXPopUpButtonRole kAXPopUpButtonRole
Definition at line 209 of file qaccessible_mac.mm.
QAXPositionAttribute
#define QAXPositionAttribute kAXPositionAttribute
Definition at line 210 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXPressAction
#define QAXPressAction kAXPressAction
Definition at line 211 of file qaccessible_mac.mm.
Referenced by translateAction().
QAXPreviousContentsAttribute
#define QAXPreviousContentsAttribute kAXPreviousContentsAttribute
Definition at line 212 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), getNamedAttribute(), and handleSplitterContentsAttribute().
QAXProgressIndicatorRole
#define QAXProgressIndicatorRole kAXProgressIndicatorRole
Definition at line 213 of file qaccessible_mac.mm.
QAXRadioButtonRole
#define QAXRadioButtonRole kAXRadioButtonRole
Definition at line 214 of file qaccessible_mac.mm.
QAXRoleAttribute
#define QAXRoleAttribute kAXRoleAttribute
Definition at line 215 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXRoleDescriptionAttribute
#define QAXRoleDescriptionAttribute kAXRoleDescriptionAttribute
Definition at line 216 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
QAXRowRole
#define QAXRowRole kAXRowRole
Definition at line 217 of file qaccessible_mac.mm.
QAXRowsAttribute
#define QAXRowsAttribute kAXRowsAttribute
Definition at line 218 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXScrollAreaRole
#define QAXScrollAreaRole kAXScrollAreaRole
Definition at line 219 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), macRole(), and scrollAreaGetScrollBarInterface().
QAXScrollBarRole
#define QAXScrollBarRole kAXScrollBarRole
Definition at line 220 of file qaccessible_mac.mm.
QAXSelectedAttribute
#define QAXSelectedAttribute kAXSelectedAttribute
Definition at line 221 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
QAXSelectedChildrenAttribute
#define QAXSelectedChildrenAttribute kAXSelectedChildrenAttribute
Definition at line 222 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
QAXSelectedRowsAttribute
#define QAXSelectedRowsAttribute kAXSelectedRowsAttribute
Definition at line 223 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXSizeAttribute
#define QAXSizeAttribute kAXSizeAttribute
Definition at line 224 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXSliderRole
#define QAXSliderRole kAXSliderRole
Definition at line 225 of file qaccessible_mac.mm.
QAXSplitGroupRole
#define QAXSplitGroupRole kAXSplitGroupRole
Definition at line 226 of file qaccessible_mac.mm.
QAXSplitterRole
#define QAXSplitterRole kAXSplitterRole
Definition at line 227 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and macRole().
QAXSplittersAttribute
#define QAXSplittersAttribute kAXSplittersAttribute
Definition at line 228 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXStaticTextRole
#define QAXStaticTextRole kAXStaticTextRole
Definition at line 229 of file qaccessible_mac.mm.
QAXSubroleAttribute
#define QAXSubroleAttribute kAXSubroleAttribute
Definition at line 230 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), getNamedAttribute(), and supportsAttribute().
QAXTabGroupRole
#define QAXTabGroupRole kAXTabGroupRole
Definition at line 231 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames().
QAXTableRole
#define QAXTableRole kAXTableRole
Definition at line 232 of file qaccessible_mac.mm.
QAXTabsAttribute
#define QAXTabsAttribute kAXTabsAttribute
Definition at line 233 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXTextFieldRole
#define QAXTextFieldRole kAXTextFieldRole
Definition at line 234 of file qaccessible_mac.mm.
QAXTitleAttribute
#define QAXTitleAttribute kAXTitleAttribute
Definition at line 235 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), getNamedAttribute(), supportsAttribute(), and textForRoleAndAttribute().
QAXTitleUIElementAttribute
#define QAXTitleUIElementAttribute kAXTitleUIElementAttribute
Definition at line 236 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames().
QAXToolbarButtonAttribute
#define QAXToolbarButtonAttribute kAXToolbarButtonAttribute
Definition at line 237 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXToolbarRole
#define QAXToolbarRole kAXToolbarRole
Definition at line 238 of file qaccessible_mac.mm.
QAXTopLevelUIElementAttribute
#define QAXTopLevelUIElementAttribute kAXTopLevelUIElementAttribute
Definition at line 239 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), getNamedAttribute(), and handleTopLevelUIElementAttribute().
QAXUnknownRole
#define QAXUnknownRole kAXUnknownRole
Definition at line 240 of file qaccessible_mac.mm.
Referenced by isItInteresting(), and macRole().
QAXValueAttribute
#define QAXValueAttribute kAXValueAttribute
Definition at line 241 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), getNamedAttribute(), and textForRoleAndAttribute().
QAXValueChangedNotification
#define QAXValueChangedNotification kAXValueChangedNotification
Definition at line 242 of file qaccessible_mac.mm.
Referenced by QAccessible::updateAccessibility().
QAXValueIndicatorRole
#define QAXValueIndicatorRole kAXValueIndicatorRole
Definition at line 243 of file qaccessible_mac.mm.
QAXVerticalOrientationValue
#define QAXVerticalOrientationValue kAXVerticalOrientationValue
Definition at line 244 of file qaccessible_mac.mm.
Referenced by handleOrientationAttribute().
QAXVerticalScrollBarAttribute
#define QAXVerticalScrollBarAttribute kAXVerticalScrollBarAttribute
Definition at line 245 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXVisibleRowsAttribute
#define QAXVisibleRowsAttribute kAXVisibleRowsAttribute
Definition at line 246 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
QAXWindowAttribute
#define QAXWindowAttribute kAXWindowAttribute
Definition at line 247 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), getNamedAttribute(), and handleWindowAttribute().
QAXWindowCreatedNotification
#define QAXWindowCreatedNotification kAXWindowCreatedNotification
Definition at line 248 of file qaccessible_mac.mm.
Referenced by QAccessible::updateAccessibility().
QAXWindowMovedNotification
#define QAXWindowMovedNotification kAXWindowMovedNotification
Definition at line 249 of file qaccessible_mac.mm.
Referenced by QAccessible::updateAccessibility().
QAXWindowRole
#define QAXWindowRole kAXWindowRole
Definition at line 250 of file qaccessible_mac.mm.
QAXZoomButtonAttribute
#define QAXZoomButtonAttribute kAXZoomButtonAttribute
Definition at line 251 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), and getNamedAttribute().
Typedef Documentation
QAXRoleType
typedef CFStringRef const QAXRoleType
Definition at line 163 of file qaccessible_mac.mm.
Function Documentation
accessibilityEventHandler()
static OSStatus accessibilityEventHandler (EventHandlerCallRef next_ref, EventRef event, void * data) static
Definition at line 2288 of file qaccessible_mac.mm.
 {
     Q_UNUSED(data)
     // Return if this event is not a AccessibleGetNamedAttribute event.
     const UInt32 eclass = GetEventClass(event);
     if (eclass != kEventClassAccessibility)
         return eventNotHandledErr;
     // Get the AXUIElementRef and QAInterface pointer
     AXUIElementRef element = 0;
     GetEventParameter(event, kEventParamAccessibleObject, typeCFTypeRef, 0, sizeof(element), 0, &element);
     QAInterface interface = accessibleHierarchyManager()->lookup(element);
     if (interface.isValid() == false)
         return eventNotHandledErr;
     const UInt32 ekind = GetEventKind(event);
     OSStatus status = noErr;
     switch (ekind) {
         case kEventAccessibleGetAllAttributeNames:
              status = getAllAttributeNames(event, interface, next_ref);
         break;
         case kEventAccessibleGetNamedAttribute:
              status = getNamedAttribute(next_ref, event, interface);
         break;
         case kEventAccessibleIsNamedAttributeSettable:
              status = isNamedAttributeSettable(event, interface);
         break;
         case kEventAccessibleGetChildAtPoint:
             status = getChildAtPoint(next_ref, event, interface);
         break;
         case kEventAccessibleGetAllActionNames:
             status = getAllActionNames(next_ref, event, interface);
         break;
         case kEventAccessibleGetFocusedChild:
             status = CallNextEventHandler(next_ref, event);
         break;
         case kEventAccessibleSetNamedAttribute:
             status = setNamedAttribute(next_ref, event, interface);
         break;
         case kEventAccessiblePerformNamedAction:
             status = performNamedAction(next_ref, event, interface);
         break;
         default:
             status = CallNextEventHandler(next_ref, event);
         break;
     };
     return status;
 }
appendIfSupported()
static void appendIfSupported (CFMutableArrayRef array, CFStringRef attribute, const QAInterface & interface) static
Definition at line 1410 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames().
 {
     if (supportsAttribute(attribute, interface))
         qt_mac_append_cf_uniq(array, attribute);
 }
applicationEventHandler()
static OSStatus applicationEventHandler (EventHandlerCallRef next_ref, EventRef event, void *) static
Definition at line 1110 of file qaccessible_mac.mm.
 {
     QAInterface rootInterface(QAccessible::queryAccessibleInterface(rootObject ? rootObject : qApp), 0);
     accessibleHierarchyManager()->registerChildren(rootInterface);
     return CallNextEventHandler(next_ref, event);
 }
buttonValue()
static int buttonValue (QAInterface element) static
Definition at line 1127 of file qaccessible_mac.mm.
Referenced by getNamedAttribute(), and getValue().
 {
     const QAccessible::State state = element.state();
     if (state & QAccessible::Mixed)
         return 2;
     else if(state & QAccessible::Checked)
         return 1;
     else
         return 0;
 }
createFactory()
static QInterfaceFactory * createFactory (const QAInterface & interface) static
Definition at line 1022 of file qaccessible_mac.mm.
Referenced by qHash(), and QAccessibleHierarchyManager::registerInterface().
 {
     if (isItemView(interface)) {
         return new QItemViewInterfaceFactory(interface);
     }  if (managesChildren(interface)) {
         return new QMultipleHIObjectFactory(interface);
     }
     return new QStandardInterfaceFactory(interface);
 }
getAccessibleObjectParameter()
static AXUIElementRef getAccessibleObjectParameter (EventRef event) inline static
Definition at line 1097 of file qaccessible_mac.mm.
 {
     AXUIElementRef element;
     GetEventParameter(event, kEventParamAccessibleObject, typeCFTypeRef, 0,
                         sizeof(element), 0, &element);
     return element;
 }
getAllActionNames()
static OSStatus getAllActionNames (EventHandlerCallRef next_ref, EventRef event, const QAInterface & interface) static
Definition at line 2181 of file qaccessible_mac.mm.
Referenced by accessibilityEventHandler().
 {
     Q_UNUSED(next_ref);
     CFMutableArrayRef actions = 0;
     GetEventParameter(event, kEventParamAccessibleActionNames, typeCFMutableArrayRef, 0,
                       sizeof(actions), 0, &actions);
     // Add supported predefined actions.
     const QList<QAccessible::Action> predefinedActions = supportedPredefinedActions(interface);
     for (int i = 0; i < predefinedActions.count(); ++i) {
         const QCFString action = translateAction(predefinedActions.at(i));
         if (action != QCFString())
             qt_mac_append_cf_uniq(actions, action);
     }
     // Add user actions
     const int actionCount = interface.userActionCount();
     for (int i = 0; i < actionCount; ++i) {
         const QString actionName = interface.actionText(i, QAccessible::Name);
         qt_mac_append_cf_uniq(actions, QCFString::toCFStringRef(actionName));
     }
     return noErr;
 }
getAllAttributeNames()
static OSStatus getAllAttributeNames (EventRef event, const QAInterface & interface, EventHandlerCallRef next_ref) static
Definition at line 1419 of file qaccessible_mac.mm.
Referenced by accessibilityEventHandler().
 {
     // Call system event handler.
     OSStatus err = CallNextEventHandler(next_ref, event);
     if(err != noErr && err != eventNotHandledErr)
         return err;
     CFMutableArrayRef attrs = 0;
     GetEventParameter(event, kEventParamAccessibleAttributeNames, typeCFMutableArrayRef, 0,
                       sizeof(attrs), 0, &attrs);
     if (!attrs)
         return eventNotHandledErr;
     // Append attribute names that are always supported.
     qt_mac_append_cf_uniq(attrs, CFStringRef(QAXPositionAttribute));
     qt_mac_append_cf_uniq(attrs, CFStringRef(QAXSizeAttribute));
     qt_mac_append_cf_uniq(attrs, CFStringRef(QAXRoleAttribute));
     qt_mac_append_cf_uniq(attrs, CFStringRef(QAXEnabledAttribute));
     qt_mac_append_cf_uniq(attrs, CFStringRef(QAXWindowAttribute));
     qt_mac_append_cf_uniq(attrs, CFStringRef(QAXTopLevelUIElementAttribute));
     // Append these names if the QInterafceItem returns any data for them.
     appendIfSupported(attrs, CFStringRef(QAXTitleAttribute), interface);
     appendIfSupported(attrs, CFStringRef(QAXValueAttribute), interface);
     appendIfSupported(attrs, CFStringRef(QAXDescriptionAttribute), interface);
     appendIfSupported(attrs, CFStringRef(QAXLinkedUIElementsAttribute), interface);
     appendIfSupported(attrs, CFStringRef(QAXHelpAttribute), interface);
     appendIfSupported(attrs, CFStringRef(QAXTitleUIElementAttribute), interface);
     appendIfSupported(attrs, CFStringRef(QAXChildrenAttribute), interface);
     appendIfSupported(attrs, CFStringRef(QAXSubroleAttribute), interface);
     // Append attribute names based on the interaface role.
     switch (interface.role())  {
         case QAccessible::Window:
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXMainAttribute));
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXMinimizedAttribute));
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXCloseButtonAttribute));
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXZoomButtonAttribute));
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXMinimizeButtonAttribute));
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXToolbarButtonAttribute));
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXGrowAreaAttribute));
         break;
         case QAccessible::RadioButton:
         case QAccessible::CheckBox:
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXMinValueAttribute));
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXMaxValueAttribute));
         break;
         case QAccessible::ScrollBar:
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXOrientationAttribute));
         break;
         case QAccessible::Splitter:
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXSplittersAttribute));
         break;
         case QAccessible::Table:
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXRowsAttribute));
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXVisibleRowsAttribute));
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXSelectedRowsAttribute));
         break;
         default:
         break;
     }
     // Append attribute names based on the mac accessibility role.
     const QCFString mac_role = macRole(interface);
     if (mac_role == CFStringRef(QAXSplitterRole)) {
         qt_mac_append_cf_uniq(attrs, CFStringRef(QAXPreviousContentsAttribute));
         qt_mac_append_cf_uniq(attrs, CFStringRef(QAXNextContentsAttribute));
         qt_mac_append_cf_uniq(attrs, CFStringRef(QAXOrientationAttribute));
     } else if (mac_role == CFStringRef(QAXScrollAreaRole)) {
         if (scrollAreaHasScrollBar(interface, Qt::Horizontal))
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXHorizontalScrollBarAttribute));
         if (scrollAreaHasScrollBar(interface, Qt::Vertical))
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXVerticalScrollBarAttribute));
         qt_mac_append_cf_uniq(attrs, CFStringRef(QAXContentsAttribute));
     } else if (mac_role == CFStringRef(QAXTabGroupRole)) {
         qt_mac_append_cf_uniq(attrs, CFStringRef(QAXTabsAttribute));
         // Only tab widgets can have the contents attribute, there is no way of getting
         // the contents from a QTabBar.
         if (isTabWidget(interface))
             qt_mac_append_cf_uniq(attrs, CFStringRef(QAXContentsAttribute));
     }
     return noErr;
 }
getChildAtPoint()
static OSStatus getChildAtPoint (EventHandlerCallRef next_ref, EventRef event, QAInterface & interface) static
Definition at line 2076 of file qaccessible_mac.mm.
Referenced by accessibilityEventHandler().
 {
     Q_UNUSED(next_ref);
     if (interface.isValid() == false)
         return eventNotHandledErr;
     // Add the children for this interface to the global QAccessibelHierachyManager.
     accessibleHierarchyManager()->registerChildren(interface);
     Point where;
     GetEventParameter(event, kEventParamMouseLocation, typeQDPoint, 0, sizeof(where), 0, &where);
     const QAInterface childInterface = interface.childAt(where.h, where.v);
     if (childInterface.isValid() == false || childInterface == interface)
         return eventNotHandledErr;
     const QAElement element = accessibleHierarchyManager()->lookup(childInterface);
     if (element.isValid() == false)
         return eventNotHandledErr;
     AXUIElementRef elementRef = element.element();
     CFRetain(elementRef);
     SetEventParameter(event, kEventParamAccessibleChild, typeCFTypeRef,
                                   sizeof(elementRef), &elementRef);
     return noErr;
 }
getNamedAttribute()
static OSStatus getNamedAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface & interface) static
Definition at line 1870 of file qaccessible_mac.mm.
Referenced by accessibilityEventHandler().
 {
     CFStringRef var;
     GetEventParameter(event, kEventParamAccessibleAttributeName, typeCFStringRef, 0,
                               sizeof(var), 0, &var);
     if (CFStringCompare(var, CFStringRef(QAXChildrenAttribute), 0) == kCFCompareEqualTo) {
         return handleChildrenAttribute(next_ref, event, interface);
     } else if(CFStringCompare(var, CFStringRef(QAXTopLevelUIElementAttribute), 0) == kCFCompareEqualTo) {
         return handleTopLevelUIElementAttribute(next_ref, event, interface);
     } else if(CFStringCompare(var, CFStringRef(QAXWindowAttribute), 0) == kCFCompareEqualTo) {
         return handleWindowAttribute(next_ref, event, interface);
     } else if(CFStringCompare(var, CFStringRef(QAXParentAttribute), 0) == kCFCompareEqualTo) {
         return handleParentAttribute(next_ref, event, interface);
     } else if (CFStringCompare(var, CFStringRef(QAXPositionAttribute), 0) == kCFCompareEqualTo) {
         return handlePositionAttribute(next_ref, event, interface);
     } else if (CFStringCompare(var, CFStringRef(QAXSizeAttribute), 0) == kCFCompareEqualTo) {
         return handleSizeAttribute(next_ref, event, interface);
     } else  if (CFStringCompare(var, CFStringRef(QAXRoleAttribute), 0) == kCFCompareEqualTo) {
         CFStringRef role = macRole(interface);
 // ###
 //        QWidget * const widget = qobject_cast<QWidget *>(interface.object());
 //        if (role == CFStringRef(QAXUnknownRole) && widget && widget->isWindow())
 //            role = CFStringRef(QAXWindowRole);
         SetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFStringRef,
                           sizeof(role), &role);
     } else if (CFStringCompare(var, CFStringRef(QAXEnabledAttribute), 0) == kCFCompareEqualTo) {
         Boolean val =  !((interface.state() & QAccessible::Unavailable))
                      && !((interface.state() & QAccessible::Invisible));
         SetEventParameter(event, kEventParamAccessibleAttributeValue, typeBoolean,
                           sizeof(val), &val);
     } else if (CFStringCompare(var, CFStringRef(QAXExpandedAttribute), 0) == kCFCompareEqualTo) {
         Boolean val = (interface.state() & QAccessible::Expanded);
         SetEventParameter(event, kEventParamAccessibleAttributeValue, typeBoolean,
                           sizeof(val), &val);
     } else if (CFStringCompare(var, CFStringRef(QAXSelectedAttribute), 0) == kCFCompareEqualTo) {
         Boolean val = (interface.state() & QAccessible::Selection);
         SetEventParameter(event, kEventParamAccessibleAttributeValue, typeBoolean,
                           sizeof(val), &val);
     } else if (CFStringCompare(var, CFStringRef(QAXFocusedAttribute), 0) == kCFCompareEqualTo) {
         Boolean val = (interface.state() & QAccessible::Focus);
         SetEventParameter(event, kEventParamAccessibleAttributeValue, typeBoolean,
                           sizeof(val), &val);
     } else if (CFStringCompare(var, CFStringRef(QAXSelectedChildrenAttribute), 0) == kCFCompareEqualTo) {
         const int cc = interface.childCount();
         QList<QAElement> selected;
         for (int i = 1; i <= cc; ++i) {
             const QAInterface child_iface = interface.navigate(QAccessible::Child, i);
             if (child_iface.isValid() && child_iface.state() & QAccessible::Selected)
                 selected.append(accessibleHierarchyManager()->lookup(child_iface));
         }
         return setAttributeValue(event, selected);
       } else if (CFStringCompare(var, CFStringRef(QAXCloseButtonAttribute), 0) == kCFCompareEqualTo) {
         if(interface.object() && interface.object()->isWidgetType()) {
             Boolean val = true; //do we want to add a WState for this?
             SetEventParameter(event, kEventParamAccessibleAttributeValue, typeBoolean,
                               sizeof(val), &val);
         }
     } else if (CFStringCompare(var, CFStringRef(QAXZoomButtonAttribute), 0) == kCFCompareEqualTo) {
         if(interface.object() && interface.object()->isWidgetType()) {
             QWidget *widget = (QWidget*)interface.object();
             Boolean val = (widget->windowFlags() & Qt::WindowMaximizeButtonHint);
             SetEventParameter(event, kEventParamAccessibleAttributeValue, typeBoolean,
                               sizeof(val), &val);
         }
     } else if (CFStringCompare(var, CFStringRef(QAXMinimizeButtonAttribute), 0) == kCFCompareEqualTo) {
         if(interface.object() && interface.object()->isWidgetType()) {
             QWidget *widget = (QWidget*)interface.object();
             Boolean val = (widget->windowFlags() & Qt::WindowMinimizeButtonHint);
             SetEventParameter(event, kEventParamAccessibleAttributeValue, typeBoolean,
                               sizeof(val), &val);
         }
     } else if (CFStringCompare(var, CFStringRef(QAXToolbarButtonAttribute), 0) == kCFCompareEqualTo) {
         if(interface.object() && interface.object()->isWidgetType()) {
             QWidget *widget = (QWidget*)interface.object();
             Boolean val = qobject_cast<QMainWindow *>(widget) != 0;
             SetEventParameter(event, kEventParamAccessibleAttributeValue, typeBoolean,
                               sizeof(val), &val);
         }
     } else if (CFStringCompare(var, CFStringRef(QAXGrowAreaAttribute), 0) == kCFCompareEqualTo) {
         if(interface.object() && interface.object()->isWidgetType()) {
             Boolean val = true; //do we want to add a WState for this?
             SetEventParameter(event, kEventParamAccessibleAttributeValue, typeBoolean,
                               sizeof(val), &val);
         }
     } else if (CFStringCompare(var, CFStringRef(QAXMinimizedAttribute), 0) == kCFCompareEqualTo) {
         if (interface.object() && interface.object()->isWidgetType()) {
             QWidget *widget = (QWidget*)interface.object();
             Boolean val = (widget->windowState() & Qt::WindowMinimized);
             SetEventParameter(event, kEventParamAccessibleAttributeValue, typeBoolean,
                               sizeof(val), &val);
         }
     } else if (CFStringCompare(var, CFStringRef(QAXSubroleAttribute), 0) == kCFCompareEqualTo) {
         return handleSubroleAttribute(next_ref, event, interface);
     } else if (CFStringCompare(var, CFStringRef(QAXRoleDescriptionAttribute), 0) == kCFCompareEqualTo) {
 #if !defined(QT_MAC_USE_COCOA)
         if (HICopyAccessibilityRoleDescription) {
             const CFStringRef roleDescription = HICopyAccessibilityRoleDescription(macRole(interface), 0);
             SetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFStringRef,
                           sizeof(roleDescription), &roleDescription);
         } else
 #endif
         {
             // Just use Qt::Description on 10.3
             handleStringAttribute(event, QAccessible::Description, interface);
         }
     } else if (CFStringCompare(var, CFStringRef(QAXTitleAttribute), 0) == kCFCompareEqualTo) {
         const QAccessible::Role role = interface.role();
         const QAccessible::Text text = (QAccessible::Text)textForRoleAndAttribute(role, var);
         handleStringAttribute(event, text, interface);
     } else if (CFStringCompare(var, CFStringRef(QAXValueAttribute), 0) == kCFCompareEqualTo) {
         const QAccessible::Role role = interface.role();
         const QAccessible::Text text = (QAccessible::Text)textForRoleAndAttribute(role, var);
         if (role == QAccessible::CheckBox || role == QAccessible::RadioButton) {
             int value = buttonValue(interface);
             SetEventParameter(event, kEventParamAccessibleAttributeValue, typeUInt32, sizeof(value), &value);
         } else {
             handleStringAttribute(event, text, interface);
         }
     } else if (CFStringCompare(var, CFStringRef(QAXDescriptionAttribute), 0) == kCFCompareEqualTo) {
         const QAccessible::Role role = interface.role();
         const QAccessible::Text text = (QAccessible::Text)textForRoleAndAttribute(role, var);
         handleStringAttribute(event, text, interface);
     } else if (CFStringCompare(var, CFStringRef(QAXLinkedUIElementsAttribute), 0) == kCFCompareEqualTo) {
         return CallNextEventHandler(next_ref, event);
     } else if (CFStringCompare(var, CFStringRef(QAXHelpAttribute), 0) == kCFCompareEqualTo) {
         const QAccessible::Role role = interface.role();
         const QAccessible::Text text = (QAccessible::Text)textForRoleAndAttribute(role, var);
         handleStringAttribute(event, text, interface);
     } else if (CFStringCompare(var, kAXTitleUIElementAttribute, 0) == kCFCompareEqualTo) {
         return CallNextEventHandler(next_ref, event);
     } else if (CFStringCompare(var, CFStringRef(QAXTabsAttribute), 0) == kCFCompareEqualTo) {
         return handleTabsAttribute(next_ref, event, interface);
     } else if (CFStringCompare(var, CFStringRef(QAXMinValueAttribute), 0) == kCFCompareEqualTo) {
         // tabs we first go to the tab bar which is child #2.
         QAInterface tabBarInterface = interface.childAt(2);
         return handleTabsAttribute(next_ref, event, tabBarInterface);
     } else if (CFStringCompare(var, CFStringRef(QAXMinValueAttribute), 0) == kCFCompareEqualTo) {
         if (interface.role() == QAccessible::RadioButton || interface.role() == QAccessible::CheckBox) {
             uint value = 0;
             SetEventParameter(event, kEventParamAccessibleAttributeValue, typeUInt32, sizeof(value), &value);
         } else {
             return CallNextEventHandler(next_ref, event);
         }
     } else if (CFStringCompare(var, CFStringRef(QAXMaxValueAttribute), 0) == kCFCompareEqualTo) {
         if (interface.role() == QAccessible::RadioButton || interface.role() == QAccessible::CheckBox) {
             uint value = 2;
             SetEventParameter(event, kEventParamAccessibleAttributeValue, typeUInt32, sizeof(value), &value);
         } else {
             return CallNextEventHandler(next_ref, event);
         }
     } else if (CFStringCompare(var, CFStringRef(QAXOrientationAttribute), 0) == kCFCompareEqualTo) {
         return handleOrientationAttribute(next_ref, event, interface);
     } else if (CFStringCompare(var, CFStringRef(QAXPreviousContentsAttribute), 0) == kCFCompareEqualTo) {
         return handleSplitterContentsAttribute(next_ref, event, interface, CFStringRef(QAXPreviousContentsAttribute));
     } else if (CFStringCompare(var, CFStringRef(QAXNextContentsAttribute), 0) == kCFCompareEqualTo) {
         return handleSplitterContentsAttribute(next_ref, event, interface, CFStringRef(QAXNextContentsAttribute));
     } else if (CFStringCompare(var, CFStringRef(QAXSplittersAttribute), 0) == kCFCompareEqualTo) {
         return handleSplittersAttribute(next_ref, event, interface);
     } else if (CFStringCompare(var, CFStringRef(QAXHorizontalScrollBarAttribute), 0) == kCFCompareEqualTo) {
         return handleScrollBarAttribute(next_ref, event, interface, Qt::Horizontal);
     } else if (CFStringCompare(var, CFStringRef(QAXVerticalScrollBarAttribute), 0) == kCFCompareEqualTo) {
         return handleScrollBarAttribute(next_ref, event, interface, Qt::Vertical);
     } else if (CFStringCompare(var, CFStringRef(QAXContentsAttribute), 0) == kCFCompareEqualTo) {
         return handleContentsAttribute(next_ref, event, interface);
     } else if (CFStringCompare(var, CFStringRef(QAXRowsAttribute), 0) == kCFCompareEqualTo) {
         return handleRowsAttribute(next_ref, event, interface);
     } else if (CFStringCompare(var, CFStringRef(QAXVisibleRowsAttribute), 0) == kCFCompareEqualTo) {
         return handleVisibleRowsAttribute(next_ref, event, interface);
     } else if (CFStringCompare(var, CFStringRef(QAXSelectedRowsAttribute), 0) == kCFCompareEqualTo) {
         return handleSelectedRowsAttribute(next_ref, event, interface);
     } else {
         return CallNextEventHandler(next_ref, event);
     }
     return noErr;
 }
getValue()
static QString getValue (const QAInterface & interface) static
Definition at line 1138 of file qaccessible_mac.mm.
Referenced by supportsAttribute().
 {
     const QAccessible::Role role = interface.role();
     if (role == QAccessible::RadioButton || role == QAccessible::CheckBox)
         return QString::number(buttonValue(interface));
     else
         return interface.text(QAccessible::Value);
 }
handleChildrenAttribute()
static OSStatus handleChildrenAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface & interface) static
Definition at line 1526 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
    // Add the children for this interface to the global QAccessibelHierachyManager.
     accessibleHierarchyManager()->registerChildren(interface);
     if (isTabWidget(interface)) {
         QList<QAElement> children = tabWidgetGetChildren(interface);
         const int childCount = children.count();
         CFMutableArrayRef array = 0;
         array = CFArrayCreateMutable(0, 0, &kCFTypeArrayCallBacks);
         for (int i = 0; i < childCount; ++i)  {
             qt_mac_append_cf_uniq(array, children.at(i).element());
         }
         OSStatus err;
         err = SetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFArrayRef, sizeof(array), &array);
         if (err != noErr)
             qWarning("Qt:Internal error (%s:%d)", __FILE__, __LINE__);
         return noErr;
     }
     const QList<QAElement> children = lookup(interface.children());
     const int childCount = children.count();
     OSStatus err = eventNotHandledErr;
     if (interface.isHIView())
         err = CallNextEventHandler(next_ref, event);
     CFMutableArrayRef array = 0;
     int arraySize = 0;
     if (err == noErr) {
         CFTypeRef obj = 0;
         err = GetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFTypeRef, NULL , sizeof(obj), NULL, &obj);
         if (err == noErr && obj != 0) {
             array = (CFMutableArrayRef)obj;
             arraySize = CFArrayGetCount(array);
         }
     }
     if (array) {
         CFArrayRemoveAllValues(array);
         for (int i = 0; i < childCount; ++i)  {
             qt_mac_append_cf_uniq(array, children.at(i).element());
         }
     } else {
         array = CFArrayCreateMutable(0, 0, &kCFTypeArrayCallBacks);
         for (int i = 0; i < childCount; ++i)  {
             qt_mac_append_cf_uniq(array, children.at(i).element());
         }
         err = SetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFArrayRef, sizeof(array), &array);
         if (err != noErr)
             qWarning("Qt:Internal error (%s:%d)", __FILE__, __LINE__);
     }
     return noErr;
 }
handleContentsAttribute()
static OSStatus handleContentsAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface & interface) static
Definition at line 1818 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     const QCFString mac_role = macRole(interface);
     QAElement contents;
     if (mac_role == kAXTabGroupRole) {
         contents = tabWidgetGetContents(interface);
     } else {
         contents = scrollAreaGetContents(interface);
         if (contents.isValid() == false)
             return CallNextEventHandler(next_ref, event);
     }
     return setAttributeValue(event, QList<QAElement>() << contents);
 }
handleOrientationAttribute()
static OSStatus handleOrientationAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface & interface) static
Definition at line 1742 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     QObject *const object = interface.object();
     Qt::Orientation orientation;
     if (interface.role() == QAccessible::ScrollBar) {
         orientation  = scrollBarOrientation(interface);
     } else if (QSplitterHandle * const splitter = qobject_cast<QSplitterHandle * const>(object)) {
         // Qt reports the layout orientation, but we want the splitter handle orientation.
         orientation = (splitter->orientation() == Qt::Horizontal) ? Qt::Vertical : Qt::Horizontal;
     } else {
         return CallNextEventHandler(next_ref, event);
     }
     const CFStringRef orientationString = (orientation == Qt::Vertical)
         ? CFStringRef(QAXVerticalOrientationValue) : CFStringRef(QAXHorizontalOrientationValue);
     SetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFStringRef, sizeof(orientationString), &orientationString);
     return noErr;
 }
handleParentAttribute()
static OSStatus handleParentAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface & interface) static
Definition at line 1589 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     OSStatus err = eventNotHandledErr;
     if (interface.isHIView()) {
          err = CallNextEventHandler(next_ref, event);
     }
     if (err == noErr)
         return err;
     const QAInterface parentInterface  = interface.navigate(QAccessible::Ancestor, 1);
     const QAElement parentElement = accessibleHierarchyManager()->lookup(parentInterface);
     if (parentElement.isValid() == false)
         return eventNotHandledErr;
     AXUIElementRef elementRef = parentElement.element();
     SetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFTypeRef, sizeof(elementRef), &elementRef);
     return noErr;
 }
handlePositionAttribute()
static OSStatus handlePositionAttribute (EventHandlerCallRef , EventRef event, const QAInterface & interface) static
Definition at line 1714 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     QPoint qpoint(interface.rect().topLeft());
     HIPoint point;
     point.x = qpoint.x();
     point.y = qpoint.y();
     SetEventParameter(event, kEventParamAccessibleAttributeValue, typeHIPoint, sizeof(point), &point);
     return noErr;
 }
handleRowsAttribute()
static OSStatus handleRowsAttribute (EventHandlerCallRef , EventRef event, QAInterface & tableView) static
Definition at line 1835 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     QList<QAElement> rows = lookup(tableView.children());
     // kill the first row which is the horizontal header.
     rows.removeAt(0);
     return setAttributeValue(event, rows);
 }
handleScrollBarAttribute()
static OSStatus handleScrollBarAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface & scrollArea, Qt::Orientation orientation) static
Definition at line 1806 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     QAElement scrollBar = scrollAreaGetScrollBar(scrollArea, orientation);
     if (scrollBar.isValid() == false)
         return CallNextEventHandler(next_ref, event);
     AXUIElementRef elementRef = scrollBar.element();
     SetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFTypeRef, sizeof(elementRef), &elementRef);
     return noErr;
 }
handleSelectedRowsAttribute()
static OSStatus handleSelectedRowsAttribute (EventHandlerCallRef , EventRef event, QAInterface & tableView) static
Definition at line 1860 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     QList<QAElement> selectedRows;
     foreach (const QAInterface &interface, tableView.children())
         if ((interface.state() & QAccessible::Selected))
             selectedRows.append(accessibleHierarchyManager()->lookup(interface));
     return setAttributeValue(event, selectedRows);
 }
handleSizeAttribute()
static OSStatus handleSizeAttribute (EventHandlerCallRef , EventRef event, const QAInterface & interface) static
Definition at line 1724 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     QSize qSize(interface.rect().size());
     HISize size;
     size.width = qSize.width();
     size.height = qSize.height();
     SetEventParameter(event, kEventParamAccessibleAttributeValue, typeHISize, sizeof(size), &size);
     return noErr;
 }
handleSplitterContentsAttribute()
static OSStatus handleSplitterContentsAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface & interface, QCFString nextOrPrev) static
Definition at line 1763 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     if (interface.isValid() == false || interface.role() != QAccessible::Grip)
         return eventNotHandledErr;
     const QAInterface parent = interface.parent();
     if (parent.isValid() == false)
         return CallNextEventHandler(next_ref, event);
     if (parent.role() != QAccessible::Splitter)
         return CallNextEventHandler(next_ref, event);
     const QSplitter * const splitter = qobject_cast<const QSplitter * const>(parent.object());
     if (splitter == 0)
         return CallNextEventHandler(next_ref, event);
     QWidget * const splitterHandle = qobject_cast<QWidget * const>(interface.object());
     const int splitterHandleIndex = splitter->indexOf(splitterHandle);
     const int widgetIndex = (nextOrPrev == QCFString(CFStringRef(QAXPreviousContentsAttribute))) ? splitterHandleIndex - 1 : splitterHandleIndex;
     const QAElement contentsElement = accessibleHierarchyManager()->lookup(splitter->widget(widgetIndex), 0);
     return setAttributeValue(event, QList<QAElement>() << contentsElement);
 }
handleSplittersAttribute()
static OSStatus handleSplittersAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface & interface) static
Definition at line 1789 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     const QSplitter * const splitter = qobject_cast<const QSplitter * const>(interface.object());
     if (splitter == 0)
         return CallNextEventHandler(next_ref, event);
     accessibleHierarchyManager()->registerChildren(interface);
     QList<QAElement> handles;
     const int visibleSplitterCount = splitter->count() -1; // skip first handle, it's always invisible.
     for (int i = 0; i < visibleSplitterCount; ++i)
         handles.append(accessibleHierarchyManager()->lookup(splitter->handle(i + 1), 0));
     return setAttributeValue(event, handles);
 }
handleStringAttribute()
static void handleStringAttribute (EventRef event, QAccessible::Text text, const QAInterface & interface) static
Definition at line 1504 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     QString str = interface.text(text);
     if (str.isEmpty())
         return;
     // Remove any html markup from the text string, or VoiceOver will read the html tags.
     static QTextDocument document;
     document.setHtml(str);
     str = document.toPlainText();
     CFStringRef cfstr = QCFString::toCFStringRef(str);
     SetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFStringRef, sizeof(cfstr), &cfstr);
 }
handleSubroleAttribute()
static OSStatus handleSubroleAttribute (EventHandlerCallRef , EventRef event, const QAInterface & interface) static
Definition at line 1734 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     const QCFString role = subrole(interface);
     CFStringRef rolestr = (CFStringRef)role;
     SetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFTypeRef, sizeof(rolestr), &rolestr);
     return noErr;
 }
handleTabsAttribute()
static OSStatus handleTabsAttribute (EventHandlerCallRef next_ref, EventRef event, QAInterface & interface) static
Definition at line 1705 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     Q_UNUSED(next_ref);
     if (isTabWidget(interface))
         return setAttributeValue(event, tabWidgetGetTabs(interface));
     else
         return setAttributeValue(event, tabBarGetTabs(interface));
 }
handleTopLevelUIElementAttribute()
static OSStatus handleTopLevelUIElementAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface & interface) static
Definition at line 1697 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     return navigateAncestors<IsWindowTest>(next_ref, event, interface, CFStringRef(QAXTopLevelUIElementAttribute));
 }
handleVisibleRowsAttribute()
static OSStatus handleVisibleRowsAttribute (EventHandlerCallRef , EventRef event, QAInterface & tableView) static
Definition at line 1845 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     QList<QAElement> visibleRows;
     QList<QAInterface> rows = tableView.children();
     // kill the first row which is the horizontal header.
     rows.removeAt(0);
     foreach (const QAInterface &interface, rows)
         if ((interface.state() & QAccessible::Invisible) == false)
             visibleRows.append(accessibleHierarchyManager()->lookup(interface));
     return setAttributeValue(event, visibleRows);
 }
handleWindowAttribute()
static OSStatus handleWindowAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface & interface) static
Definition at line 1688 of file qaccessible_mac.mm.
Referenced by getNamedAttribute().
 {
     return navigateAncestors<IsWindowAndNotDrawerOrSheetTest>(next_ref, event, interface, CFStringRef(QAXWindowAttribute));
 }
isEmbeddedTabBar()
static bool isEmbeddedTabBar (const QAInterface & interface) static
Definition at line 619 of file qaccessible_mac.mm.
Referenced by isItInteresting().
 {
     QObject *object = interface.object();
     if (interface.role() == QAccessible::PageTabList && object)
         return (qobject_cast<QTabWidget *>(object->parent()));
     return false;
 }
isItemView()
static bool isItemView (const QAInterface & interface) static
Definition at line 593 of file qaccessible_mac.mm.
Referenced by createFactory(), and QAccessible::updateAccessibility().
 {
     QObject *object = interface.object();
     return (interface.role() == QAccessible::List || interface.role() == QAccessible::Table
             || (object && qobject_cast<QAbstractItemView *>(interface.object()))
             || (object && object->objectName() == QLatin1String("qt_scrollarea_viewport")
                 && qobject_cast<QAbstractItemView *>(object->parent())));
 }
isItInteresting()
bool isItInteresting (const QAInterface & interface)
Definition at line 631 of file qaccessible_mac.mm.
Referenced by QMultipleHIObjectFactory::registerChildren(), QAccessibleHierarchyManager::registerInterface(), and QAccessible::updateAccessibility().
 {
     // Mac accessibility does not have an attribute that corresponds to the Invisible/Offscreen
     // state, so we disable the interface here.
     const QAccessible::State state = interface.state();
     if (state & QAccessible::Invisible ||
         state & QAccessible::Offscreen )
         return false;
     const QAccessible::Role role = interface.role();
     if (QObject * const object = interface.object()) {
         const QString className = QLatin1String(object->metaObject()->className());
         // VoiceOver focusing on tool tips can be confusing. The contents of the
         // tool tip is avalible through the description attribute anyway, so
         // we disable accessibility for tool tips.
         if (className == QLatin1String("QTipLabel"))
             return false;
         // Hide TabBars that has a QTabWidget parent (the tab widget handles the accessibility)
         if (isEmbeddedTabBar(interface))
             return false;
          // Hide docked dockwidgets. ### causes infinitie loop in the apple accessibility code.
      /*    if (QDockWidget *dockWidget = qobject_cast<QDockWidget *>(object)) {
             if (dockWidget->isFloating() == false)
                 return false;
          }
     */
     }
     // Client is a generic role returned by plain QWidgets or other
     // widgets that does not have separate QAccessible interface, such
     // as the TabWidget. Return false unless macRole gives the interface
     // a special role.
     if (role == QAccessible::Client && macRole(interface) == CFStringRef(QAXUnknownRole))
         return false;
     // Some roles are not interesting:
     if (role == QAccessible::Border ||    // QFrame
         role == QAccessible::Application || // We use the system-provided application element.
         role == QAccessible::MenuItem)      // The system also provides the menu items.
         return false;
     // It is probably better to access the toolbar buttons directly than having
     // to navigate through the toolbar.
     if (role == QAccessible::ToolBar)
         return false;
     return true;
 }
isNamedAttributeSettable()
static OSStatus isNamedAttributeSettable (EventRef event, const QAInterface & interface) static
Definition at line 2051 of file qaccessible_mac.mm.
Referenced by accessibilityEventHandler().
 {
     CFStringRef var;
     GetEventParameter(event, kEventParamAccessibleAttributeName, typeCFStringRef, 0,
                       sizeof(var), 0, &var);
     Boolean settable = false;
     if (CFStringCompare(var, CFStringRef(QAXFocusedAttribute), 0) == kCFCompareEqualTo) {
         settable = true;
     } else {
         for (int r = 0; text_bindings[r][0].qt != -1; r++) {
             if(interface.role() == (QAccessible::Role)text_bindings[r][0].qt) {
                 for (int a = 1; text_bindings[r][a].qt != -1; a++) {
                     if (CFStringCompare(var, CFStringRef(text_bindings[r][a].mac), 0) == kCFCompareEqualTo) {
                         settable = text_bindings[r][a].settable;
                         break;
                     }
                 }
             }
         }
     }
     SetEventParameter(event, kEventParamAccessibleAttributeSettable, typeBoolean,
                       sizeof(settable), &settable);
     return noErr;
 }
isStandaloneTabBar()
static bool isStandaloneTabBar (const QAInterface & interface) static
Definition at line 610 of file qaccessible_mac.mm.
Referenced by macRole().
 {
     QObject *object = interface.object();
     if (interface.role() == QAccessible::PageTabList && object)
         return (qobject_cast<QTabWidget *>(object->parent()) == 0);
     return false;
 }
isTabWidget()
static bool isTabWidget (const QAInterface & interface) static
Definition at line 603 of file qaccessible_mac.mm.
Referenced by QWindowsMobileStyle::drawComplexControl(), getAllAttributeNames(), handleChildrenAttribute(), handleTabsAttribute(), and macRole().
 {
     if (QObject *object = interface.object())
         return (object->inherits("QTabWidget") && interface.id() == 0);
     return false;
 }
lookup()
QList<QAElement> lookup (const QList< QAInterface > & interfaces)
Definition at line 1034 of file qaccessible_mac.mm.
Referenced by getNamedAttribute(), handleChildrenAttribute(), handleRowsAttribute(), handleSelectedRowsAttribute(), handleSplittersAttribute(), handleVisibleRowsAttribute(), QAccessibleHierarchyManager::lookup(), QCss::Parser::lookupElementName(), QCss::Parser::parseCombinator(), QCss::Parser::parseElementName(), QCss::Parser::parseTerm(), QGLGlyphCache::QGLGlyphCache(), tabBarGetTabs(), QCss::Parser::unquotedLexem(), QAccessible::updateAccessibility(), QPatternist::VariableDeclaration::usedByMany(), and QAccessibleHierarchyManager::~QAccessibleHierarchyManager().
 {
     QList<QAElement> elements;
     foreach (const QAInterface &interface, interfaces)
         if (interface.isValid()) {
             const QAElement element = accessibleHierarchyManager()->lookup(interface);
             if (element.isValid())
                 elements.append(element);
         }
     return elements;
 }
macRole()
static CFStringRef macRole (const QAInterface & interface) static
Definition at line 1151 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames(), getNamedAttribute(), handleContentsAttribute(), isItInteresting(), and scrollAreaGetScrollBarInterface().
 {
     const QAccessible::Role qtRole = interface.role();
 //    qDebug() << "role for" << interface.object() << "interface role" << hex << qtRole;
     // Qt accessibility:  QAccessible::Splitter contains QAccessible::Grip.
     // Mac accessibility: AXSplitGroup contains AXSplitter.
     if (qtRole == QAccessible::Grip) {
         const QAInterface parent = interface.parent();
         if (parent.isValid() && parent.role() == QAccessible::Splitter)
             return CFStringRef(QAXSplitterRole);
     }
     // Tab widgets and standalone tab bars get the kAXTabGroupRole. Accessibility
     // for tab bars emebedded in a tab widget is handled by the tab widget.
     if (isTabWidget(interface) || isStandaloneTabBar(interface))
         return kAXTabGroupRole;
     if (QObject *object = interface.object()) {
         // ### The interface for an abstract scroll area returns the generic "Client"
         // role, so we have to to an extra detect on the QObject here.
         if (object->inherits("QAbstractScrollArea") && interface.id() == 0)
             return CFStringRef(QAXScrollAreaRole);
         if (object->inherits("QDockWidget"))
             return CFStringRef(QAXUnknownRole);
     }
     int i = 0;
     int testRole = text_bindings[i][0].qt;
     while (testRole != -1) {
         if (testRole == qtRole)
             return CFStringRef(text_bindings[i][0].mac);
         ++i;
         testRole = text_bindings[i][0].qt;
     }
 //    qDebug() << "got unknown role!" << interface << interface.parent();
     return CFStringRef(QAXUnknownRole);
 }
managesChildren()
static bool managesChildren (const QAInterface & interface) static
Definition at line 1017 of file qaccessible_mac.mm.
Referenced by createFactory(), and QAccessible::updateAccessibility().
 {
     return (interface.childCount() > 0 && interface.childAt(1).id() > 0);
 }
navigateAncestors()
template<typename TestType > OSStatus navigateAncestors (EventHandlerCallRef next_ref, EventRef event, const QAInterface & interface, CFStringRef attribute)
Definition at line 1636 of file qaccessible_mac.mm.
 {
     if (interface.isHIView())
         return CallNextEventHandler(next_ref, event);
     QAInterface current = interface;
     QAElement element;
     while (current.isValid()) {
         if (TestType::test(interface)) {
             element = accessibleHierarchyManager()->lookup(current);
             break;
         }
         // If we reach an InterfaceItem that is a HiView we can hand of the search to
         // the system event handler. This is the common case.
         if (current.isHIView()) {
             CFTypeRef value = 0;
             const QAElement currentElement = accessibleHierarchyManager()->lookup(current);
             AXError err = AXUIElementCopyAttributeValue(currentElement.element(), attribute, &value);
             AXUIElementRef newElement = (AXUIElementRef)value;
             if (err == noErr)
                 element = QAElement(newElement);
             if (newElement != 0)
                 CFRelease(newElement);
             break;
         }
         QAInterface next = current.parent();
         if (next.isValid() == false)
             break;
         if (next == current)
             break;
         current = next;
     }
     if (element.isValid() == false)
         return eventNotHandledErr;
     AXUIElementRef elementRef = element.element();
     SetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFTypeRef,
                                       sizeof(elementRef), &elementRef);
     return noErr;
 }
operator<<()
QDebug operator<< (QDebug debug, const QAInterface & interface)
Definition at line 397 of file qaccessible_mac.mm.
 {
     if (interface.isValid() == false)
         debug << "invalid interface";
     else
         debug << interface.object() << "id" << interface.id() << "role" << hex << interface.role();
     return debug;
 }
performNamedAction()
static OSStatus performNamedAction (EventHandlerCallRef next_ref, EventRef event, const QAInterface & interface) static
Definition at line 2212 of file qaccessible_mac.mm.
Referenced by accessibilityEventHandler().
 {
     Q_UNUSED(next_ref);
     CFStringRef act;
     GetEventParameter(event, kEventParamAccessibleActionName, typeCFStringRef, 0,
                       sizeof(act), 0, &act);
     const QAccessible::Action action = translateAction(act);
     // Perform built-in action
     if (action != QAccessible::DefaultAction) {
         interface.doAction(action, QVariantList());
         return noErr;
     }
     // Search for user-defined actions and perform it if found.
     const int actCount = interface.userActionCount();
     const QString qAct = QCFString::toQString(act);
     for(int i = 0; i < actCount; i++) {
         if(interface.actionText(i, QAccessible::Name) == qAct) {
             interface.doAction(i, QVariantList());
             break;
         }
     }
     return noErr;
 }
Q_GLOBAL_STATIC()
Q_GLOBAL_STATIC (QAccessibleHierarchyManager , accessibleHierarchyManager)
Referenced by qHash().
qHash() [1/2]
uint qHash (const QAInterface & item)
Definition at line 441 of file qaccessible_mac.mm.
Referenced by qHash().
 {
     if (item.isValid())
         return qHash(item.object()) + qHash(item.id());
     else
         return qHash(item.cachedObject()) + qHash(item.id());
 }
qHash() [2/2]
uint qHash (QAElement element)
Definition at line 555 of file qaccessible_mac.mm.
 {
     return qHash(element.object()) + qHash(element.id());
 }
qt_mac_append_cf_uniq()
static bool qt_mac_append_cf_uniq (CFMutableArrayRef array, CFTypeRef value) static
Definition at line 1064 of file qaccessible_mac.mm.
Referenced by appendIfSupported(), getAllActionNames(), getAllAttributeNames(), and handleChildrenAttribute().
 {
     if (value == 0)
         return false;
     CFRange range;
     range.location = 0;
     range.length = CFArrayGetCount(array);
     if(!CFArrayContainsValue(array, range, value)) {
         CFArrayAppendValue(array, value);
         return true;
     }
     return false;
 }
qt_mac_is_macdrawer()
bool qt_mac_is_macdrawer (const QWidget * w)
Definition at line 306 of file qwidget_mac.mm.
Referenced by QMainWindow::addDockWidget(), QWidget::previousInFocusChain(), QDockAreaLayoutInfo::restoreState(), and IsWindowAndNotDrawerOrSheetTest::test().
 {
     return (w && w->parentWidget() && w->windowType() == Qt::Drawer);
 }
qt_mac_is_macsheet()
bool qt_mac_is_macsheet (const QWidget * w)
Definition at line 295 of file qwidget_mac.mm.
Referenced by IsWindowAndNotDrawerOrSheetTest::test().
 {
     if (!w)
         return false;
     Qt::WindowModality modality = w->windowModality();
     if (modality == Qt::ApplicationModal)
         return false;
     return w->parentWidget() && (modality == Qt::WindowModal || w->windowType() == Qt::Sheet);
 }
scrollAreaGetContents()
static QAElement scrollAreaGetContents (const QAInterface & scrollArea) static
Definition at line 1301 of file qaccessible_mac.mm.
Referenced by handleContentsAttribute().
 {
     // Child 1 is the contents widget,
     return accessibleHierarchyManager()->lookup(scrollArea.navigate(QAccessible::Child, 1));
 }
scrollAreaGetScrollBar()
static QAElement scrollAreaGetScrollBar (const QAInterface & scrollArea, Qt::Orientation orientation) static
Definition at line 1296 of file qaccessible_mac.mm.
Referenced by handleScrollBarAttribute().
 {
     return accessibleHierarchyManager()->lookup(scrollAreaGetScrollBarInterface(scrollArea, orientation));
 }
scrollAreaGetScrollBarInterface()
static QAInterface scrollAreaGetScrollBarInterface (const QAInterface & scrollArea, Qt::Orientation orientation) static
Definition at line 1271 of file qaccessible_mac.mm.
Referenced by scrollAreaGetScrollBar(), and scrollAreaHasScrollBar().
 {
     if (macRole(scrollArea) != CFStringRef(CFStringRef(QAXScrollAreaRole)))
         return QAInterface();
     // Child 1 is the contents widget, 2 and 3 are the scroll bar containers wich contains possible scroll bars.
     for (int i = 2; i <= 3; ++i) {
         QAInterface scrollBarContainer = scrollArea.childAt(i);
         for (int i = 1; i <= scrollBarContainer.childCount(); ++i) {
             QAInterface scrollBar = scrollBarContainer.childAt(i);
             if (scrollBar.isValid() &&
                 scrollBar.role() == QAccessible::ScrollBar &&
                 scrollBarOrientation(scrollBar) == orientation)
                 return scrollBar;
         }
     }
     return QAInterface();
 }
scrollAreaHasScrollBar()
static bool scrollAreaHasScrollBar (const QAInterface & scrollArea, Qt::Orientation orientation) static
Definition at line 1291 of file qaccessible_mac.mm.
Referenced by getAllAttributeNames().
 {
     return scrollAreaGetScrollBarInterface(scrollArea, orientation).isValid();
 }
scrollBarOrientation()
static Qt::Orientation scrollBarOrientation (const QAInterface & scrollBar) static
Definition at line 1262 of file qaccessible_mac.mm.
Referenced by QAbstractScrollArea::addScrollBarWidget(), handleOrientationAttribute(), and scrollAreaGetScrollBarInterface().
 {
     QObject *const object = scrollBar.object();
     if (QAbstractSlider * const sliderObject = qobject_cast<QAbstractSlider * const>(object))
         return sliderObject->orientation();
     return Qt::Vertical; // D'oh! The interface wasn't a scroll bar.
 }
setAttributeValue()
static OSStatus setAttributeValue (EventRef event, const QList< QAElement > & elements) static
Definition at line 1079 of file qaccessible_mac.mm.
Referenced by getNamedAttribute(), handleContentsAttribute(), handleRowsAttribute(), handleSelectedRowsAttribute(), handleSplitterContentsAttribute(), handleSplittersAttribute(), handleTabsAttribute(), and handleVisibleRowsAttribute().
 {
     CFMutableArrayRef array = CFArrayCreateMutable(0, 0, &kCFTypeArrayCallBacks);
     foreach (const QAElement &element, elements) {
         if (element.isValid())
             CFArrayAppendValue(array, element.element());
     }
     const OSStatus err = SetEventParameter(event, kEventParamAccessibleAttributeValue,
                                            typeCFTypeRef, sizeof(array), &array);
     CFRelease(array);
     return err;
 }
setNamedAttribute()
static OSStatus setNamedAttribute (EventHandlerCallRef next_ref, EventRef event, const QAInterface & interface) static
Definition at line 2240 of file qaccessible_mac.mm.
Referenced by accessibilityEventHandler().
 {
     Q_UNUSED(next_ref);
     Q_UNUSED(event);
     CFStringRef var;
     GetEventParameter(event, kEventParamAccessibleAttributeName, typeCFStringRef, 0,
                       sizeof(var), 0, &var);
     if(CFStringCompare(var, CFStringRef(QAXFocusedAttribute), 0) == kCFCompareEqualTo) {
         CFTypeRef val;
         if(GetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFTypeRef, 0,
                              sizeof(val), 0, &val) == noErr) {
             if(CFGetTypeID(val) == CFBooleanGetTypeID() &&
                CFEqual(static_cast<CFBooleanRef>(val), kCFBooleanTrue)) {
                 interface.doAction(QAccessible::SetFocus);
             }
         }
     } else {
         bool found = false;
         for(int r = 0; text_bindings[r][0].qt != -1; r++) {
             if(interface.role() == (QAccessible::Role)text_bindings[r][0].qt) {
                 for(int a = 1; text_bindings[r][a].qt != -1; a++) {
                     if(CFStringCompare(var, CFStringRef(text_bindings[r][a].mac), 0) == kCFCompareEqualTo) {
                         if(!text_bindings[r][a].settable) {
                         } else {
                             CFTypeRef val;
                             if(GetEventParameter(event, kEventParamAccessibleAttributeValue, typeCFTypeRef, 0,
                                                  sizeof(val), 0, &val) == noErr) {
                                 if(CFGetTypeID(val) == CFStringGetTypeID())
                                     interface.setText((QAccessible::Text)text_bindings[r][a].qt,
                                                    QCFString::toQString(static_cast<CFStringRef>(val)));
                             }
                         }
                         found = true;
                         break;
                     }
                 }
                 break;
             }
         }
     }
     return noErr;
 }
subrole()
static QCFString subrole (const QAInterface & interface) static
Definition at line 1240 of file qaccessible_mac.mm.
Referenced by handleSubroleAttribute(), and supportsAttribute().
 {
     const QAInterface parent = interface.parent();
     if (parent.isValid() == false)
         return QCFString();
     if (parent.role() == QAccessible::ScrollBar) {
         QCFString subrole;
         switch(interface.id()) {
             case 1: subrole = CFStringRef(QAXDecrementArrowSubrole); break;
             case 2: subrole = CFStringRef(QAXDecrementPageSubrole); break;
             case 4: subrole = CFStringRef(QAXIncrementPageSubrole); break;
             case 5: subrole = CFStringRef(QAXIncrementArrowSubrole); break;
             default:
             break;
         }
         return subrole;
     }
     return QCFString();
 }
supportedPredefinedActions()
static QList<QAccessible::Action> supportedPredefinedActions (const QAInterface & interface) static
Definition at line 2108 of file qaccessible_mac.mm.
Referenced by getAllActionNames().
 {
     QList<QAccessible::Action> actions;
     switch (interface.role()) {
         default:
             // Most things can be pressed.
             actions.append(QAccessible::Press);
         break;
     }
     return actions;
 }
supportsAttribute()
static bool supportsAttribute (CFStringRef attribute, const QAInterface & interface) static
Definition at line 1382 of file qaccessible_mac.mm.
Referenced by appendIfSupported().
 {
     const int text = textForRoleAndAttribute(interface.role(), attribute);
     // Special case: Static texts don't have a title.
     if (interface.role() == QAccessible::StaticText && attribute == CFStringRef(QAXTitleAttribute))
         return false;
     // Return true if we the attribute matched a QAccessible::Role and we get text for that role from the interface.
     if (text != -1) {
         if (text == QAccessible::Value) // Special case for Value, see getValue()
             return !getValue(interface).isEmpty();
         else
             return !interface.text((QAccessible::Text)text).isEmpty();
     }
     if (CFStringCompare(attribute, CFStringRef(QAXChildrenAttribute),  0) == kCFCompareEqualTo) {
         if (interface.childCount() > 0)
             return true;
     }
     if (CFStringCompare(attribute, CFStringRef(QAXSubroleAttribute),  0) == kCFCompareEqualTo) {
         return (subrole(interface) != QCFString());
     }
     return false;
 }
tabBarGetTabs()
static QList<QAElement> tabBarGetTabs (const QAInterface & interface) static
Definition at line 1319 of file qaccessible_mac.mm.
Referenced by handleTabsAttribute(), and tabWidgetGetTabs().
 {
     // Get the tabs by searching for children with the "PageTab" role.
     // This filters out the left/right navigation buttons.
     accessibleHierarchyManager()->registerChildren(interface);
     QList<QAElement> tabs;
     const int numChildren = interface.childCount();
     for (int i = 1; i < numChildren + 1; ++i) {
         QAInterface child = interface.navigate(QAccessible::Child, i);
         if (child.isValid() && child.role() == QAccessible::PageTab) {
             tabs.append(accessibleHierarchyManager()->lookup(child));
         }
     }
     return tabs;
 }
tabWidgetGetChildren()
static QList<QAElement> tabWidgetGetChildren (const QAInterface & interface) static
Definition at line 1342 of file qaccessible_mac.mm.
Referenced by handleChildrenAttribute().
 {
     // The children for a kAXTabGroup should consist of the tabs and the
     // contents of the current open tab page.
     QList<QAElement> children = tabWidgetGetTabs(interface);
     children += tabWidgetGetContents(interface);
     return children;
 }
tabWidgetGetContents()
static QAElement tabWidgetGetContents (const QAInterface & interface) static
Definition at line 1307 of file qaccessible_mac.mm.
Referenced by handleContentsAttribute(), and tabWidgetGetChildren().
 {
     // A kAXTabGroup has a kAXContents attribute, which consists of the
     // ui elements for the current tab page. Get the current tab page
     // from the QStackedWidget, where the current visible page can
     // be found at index 1.
     QAInterface stackedWidget = interface.childAt(1);
     accessibleHierarchyManager()->registerChildren(stackedWidget);
     QAInterface tabPageInterface = stackedWidget.childAt(1);
     return accessibleHierarchyManager()->lookup(tabPageInterface);
 }
tabWidgetGetTabs()
static QList<QAElement> tabWidgetGetTabs (const QAInterface & interface) static
Definition at line 1335 of file qaccessible_mac.mm.
Referenced by handleTabsAttribute(), and tabWidgetGetChildren().
 {
     // Each QTabWidget has two children, a QStackedWidget and a QTabBar.
     // Get the tabs from the QTabBar.
     return tabBarGetTabs(interface.childAt(2));
 }
textForRoleAndAttribute()
static int textForRoleAndAttribute (QAccessible::Role role, CFStringRef attribute) static
custom compare
custom compare
Definition at line 1199 of file qaccessible_mac.mm.
Referenced by getNamedAttribute(), and supportsAttribute().
 {
      // Search for exception, return it if found.
     int testRole = text_bindings[0][0].qt;
     int i = 0;
     while (testRole != -1) {
         if (testRole == role) {
             int j = 1;
             int qtRole = text_bindings[i][j].qt;
             CFStringRef testAttribute = CFStringRef(text_bindings[i][j].mac);
             while (qtRole != -1) {
                 if (CFStringCompare(attribute, testAttribute, 0) == kCFCompareEqualTo) {
                     return (QAccessible::Text)qtRole;
                 }
                 ++j;
                 testAttribute = CFStringRef(text_bindings[i][j].mac);
                 qtRole = text_bindings[i][j].qt;
             }
             break;
         }
         ++i;
         testRole = text_bindings[i][0].qt;
     }
     // Return default mappping
     if (CFStringCompare(attribute, CFStringRef(QAXTitleAttribute), 0) == kCFCompareEqualTo)
         return QAccessible::Name;
     else if (CFStringCompare(attribute, CFStringRef(QAXValueAttribute), 0) == kCFCompareEqualTo)
         return QAccessible::Value;
     else if (CFStringCompare(attribute, CFStringRef(QAXHelpAttribute), 0) == kCFCompareEqualTo)
         return QAccessible::Help;
     else if (CFStringCompare(attribute, CFStringRef(QAXDescriptionAttribute), 0) == kCFCompareEqualTo)
         return QAccessible::Description;
     else
         return -1;
 }
translateAction() [1/2]
static QCFString translateAction (const QAccessible::Action action) static
Definition at line 2125 of file qaccessible_mac.mm.
Referenced by getAllActionNames(), and performNamedAction().
 {
     switch (action) {
         case QAccessible::Press:
             return CFStringRef(QAXPressAction);
         break;
         case QAccessible::Increase:
             return CFStringRef(QAXIncrementAction);
         break;
         case QAccessible::Decrease:
             return CFStringRef(QAXDecrementAction);
         break;
         case QAccessible::Accept:
             return CFStringRef(QAXConfirmAction);
         break;
         case QAccessible::Select:
             return CFStringRef(QAXPickAction);
         break;
         case QAccessible::Cancel:
             return CFStringRef(QAXCancelAction);
         break;
         default:
             return QCFString();
         break;
     }
 }
translateAction() [2/2]
static QAccessible::Action translateAction (const CFStringRef actionName) static
Definition at line 2156 of file qaccessible_mac.mm.
 {
     if(CFStringCompare(actionName, CFStringRef(QAXPressAction), 0) == kCFCompareEqualTo) {
         return QAccessible::Press;
     } else if(CFStringCompare(actionName, CFStringRef(QAXIncrementAction), 0) == kCFCompareEqualTo) {
         return QAccessible::Increase;
     } else if(CFStringCompare(actionName, CFStringRef(QAXDecrementAction), 0) == kCFCompareEqualTo) {
         return QAccessible::Decrease;
     } else if(CFStringCompare(actionName, CFStringRef(QAXConfirmAction), 0) == kCFCompareEqualTo) {
         return QAccessible::Accept;
     } else if(CFStringCompare(actionName, CFStringRef(QAXPickAction), 0) == kCFCompareEqualTo) {
         return QAccessible::Select;
     } else if(CFStringCompare(actionName, CFStringRef(QAXCancelAction), 0) == kCFCompareEqualTo) {
         return QAccessible::Cancel;
     } else {
         return QAccessible::DefaultAction;
     }
 }
Variable Documentation
rootObject
QObject* rootObject = 0 static
Definition at line 407 of file qaccessible_mac.mm.
text_bindings
struct QAccessibleTextBinding text_bindings[][10]
Referenced by isNamedAttributeSettable(), macRole(), setNamedAttribute(), and textForRoleAndAttribute().