Qt 4.8: /src/gui/accessible/qaccessible_mac_p.h File Reference
qaccessible_mac_p.h File Reference
#include <qglobal.h>
#include <private/qt_mac_p.h>
#include <qaccessible.h>
#include <qwidget.h>
#include <qdebug.h>
Classes
class QAccessibleHierarchyManager
class QAccessibleInterfaceWrapper
class QAElement
class QAInterface
class QInterfaceFactory
Functions
Q_AUTOTEST_EXPORT bool isItInteresting (const QAInterface &interface)
Q_AUTOTEST_EXPORT QDebug operator<< (QDebug debug, const QAInterface &interface)
Function Documentation
isItInteresting()
Q_AUTOTEST_EXPORT bool isItInteresting (const QAInterface & interface)
Definition at line 631 of file qaccessible_mac.mm.
Referenced by QMultipleHIObjectFactory::registerChildren(), QAccessibleHierarchyManager::registerInterface(), and QAccessible::updateAccessibility().
 {
     // Mac accessibility does not have an attribute that corresponds to the Invisible/Offscreen
     // state, so we disable the interface here.
     const QAccessible::State state = interface.state();
     if (state & QAccessible::Invisible ||
         state & QAccessible::Offscreen )
         return false;
     const QAccessible::Role role = interface.role();
     if (QObject * const object = interface.object()) {
         const QString className = QLatin1String(object->metaObject()->className());
         // VoiceOver focusing on tool tips can be confusing. The contents of the
         // tool tip is avalible through the description attribute anyway, so
         // we disable accessibility for tool tips.
         if (className == QLatin1String("QTipLabel"))
             return false;
         // Hide TabBars that has a QTabWidget parent (the tab widget handles the accessibility)
         if (isEmbeddedTabBar(interface))
             return false;
          // Hide docked dockwidgets. ### causes infinitie loop in the apple accessibility code.
      /*    if (QDockWidget *dockWidget = qobject_cast<QDockWidget *>(object)) {
             if (dockWidget->isFloating() == false)
                 return false;
          }
     */
     }
     // Client is a generic role returned by plain QWidgets or other
     // widgets that does not have separate QAccessible interface, such
     // as the TabWidget. Return false unless macRole gives the interface
     // a special role.
     if (role == QAccessible::Client && macRole(interface) == CFStringRef(QAXUnknownRole))
         return false;
     // Some roles are not interesting:
     if (role == QAccessible::Border ||    // QFrame
         role == QAccessible::Application || // We use the system-provided application element.
         role == QAccessible::MenuItem)      // The system also provides the menu items.
         return false;
     // It is probably better to access the toolbar buttons directly than having
     // to navigate through the toolbar.
     if (role == QAccessible::ToolBar)
         return false;
     return true;
 }
operator<<()
Q_AUTOTEST_EXPORT QDebug operator<< (QDebug debug, const QAInterface & interface)
Definition at line 397 of file qaccessible_mac.mm.
 {
     if (interface.isValid() == false)
         debug << "invalid interface";
     else
         debug << interface.object() << "id" << interface.id() << "role" << hex << interface.role();
     return debug;
 }