Qt 4.8: /src/gui/accessible/qaccessiblewidget.cpp File Reference
qaccessiblewidget.cpp File Reference
#include "qaccessiblewidget.h"
#include "qaction.h"
#include "qapplication.h"
#include "qgroupbox.h"
#include "qlabel.h"
#include "qtooltip.h"
#include "qwhatsthis.h"
#include "qwidget.h"
#include "qdebug.h"
#include <qmath.h>
#include <QRubberBand>
#include <QtGui/QFocusFrame>
#include <QtGui/QMenu>
#include <private/qobject_p.h>
Classes
class QAccessibleWidgetPrivate
class QACConnectionObject
Functions
static QString buddyString (const QWidget *widget)
static QList< QWidget * > childWidgets (const QWidget *widget)
static bool isAncestor (const QObject *obj, const QObject *child)
static int qt_accAmpIndex (const QString &text)
QString Q_GUI_EXPORT qt_accHotKey (const QString &text)
QString Q_GUI_EXPORT qt_accStripAmp (const QString &text)
QString qt_setWindowTitle_helperHelper (const QString &, const QWidget *)
Returns a modified window title with the [*] place holder replaced according to the rules described in QWidget::setWindowTitle.
Function Documentation
buddyString()
static QString buddyString (const QWidget * widget) static
Definition at line 78 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidget::text().
 {
     if (!widget)
         return QString();
     QWidget *parent = widget->parentWidget();
     if (!parent)
         return QString();
 #ifndef QT_NO_SHORTCUT
     QObjectList ol = parent->children();
     for (int i = 0; i < ol.size(); ++i) {
         QLabel *label = qobject_cast<QLabel*>(ol.at(i));
         if (label && label->buddy() == widget)
             return label->text();
     }
 #endif
 #ifndef QT_NO_GROUPBOX
     QGroupBox *groupbox = qobject_cast<QGroupBox*>(parent);
     if (groupbox)
         return groupbox->title();
 #endif
     return QString();
 }
childWidgets()
static QList<QWidget*> childWidgets (const QWidget * widget) static
Definition at line 61 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidget::childAt(), QAccessibleWidget::childCount(), QAccessibleWidget::indexOfChild(), QAccessibleWidget::navigate(), and QAccessibleWidget::role().
 {
     QList<QObject*> list = widget->children();
     QList<QWidget*> widgets;
     for (int i = 0; i < list.size(); ++i) {
         QWidget *w = qobject_cast<QWidget *>(list.at(i));
         if (w && !w->isWindow()
             && !qobject_cast<QFocusFrame*>(w)
 #if !defined(QT_NO_MENU)
             && !qobject_cast<QMenu*>(w)
 #endif
             && w->objectName() != QLatin1String("qt_rubberband"))
             widgets.append(w);
     }
     return widgets;
 }
isAncestor()
static bool isAncestor (const QObject * obj, const QObject * child) inline static
Definition at line 367 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidget::navigate(), and QAccessibleWidget::relationTo().
 {
     while (child) {
         if (child == obj)
             return true;
         child = child->parent();
     }
     return false;
 }
qt_accAmpIndex()
static int qt_accAmpIndex (const QString & text) static
Definition at line 106 of file qaccessiblewidget.cpp.
Referenced by qt_accHotKey(), and qt_accStripAmp().
 {
 #ifndef QT_NO_SHORTCUT
     if (text.isEmpty())
         return -1;
     int fa = 0;
     QChar ac;
     while ((fa = text.indexOf(QLatin1Char('&'), fa)) != -1) {
         ++fa;
         if (fa < text.length()) {
             // ignore "&&"
             if (text.at(fa) == QLatin1Char('&')) {
                 ++fa;
                 continue;
             } else {
                 return fa - 1;
                 break;
             }
         }
     }
     return -1;
 #else
     Q_UNUSED(text);
     return -1;
 #endif
 }
qt_accHotKey()
QString Q_GUI_EXPORT qt_accHotKey (const QString & text)
Definition at line 145 of file qaccessiblewidget.cpp.
Referenced by QAccessibleButton::text(), QAccessibleWidget::text(), QAccessibleMenuBar::text(), and QAccessibleMenuItem::text().
 {
     int ampIndex = qt_accAmpIndex(text);
     if (ampIndex != -1)
         return (QString)QKeySequence(Qt::ALT) + text.at(ampIndex + 1);
     return QString();
 }
qt_accStripAmp()
QString Q_GUI_EXPORT qt_accStripAmp (const QString & text)
Definition at line 135 of file qaccessiblewidget.cpp.
Referenced by QAccessibleMenu::text(), QAccessibleButton::text(), QAccessibleWidget::text(), QAccessibleMenuBar::text(), QAccessibleToolButton::text(), QAccessibleDisplay::text(), QAccessibleMenuItem::text(), QAccessibleGroupBox::text(), QAccessibleLineEdit::text(), QAccessibleTabBar::text(), and QAccessibleTitleBar::text().
 {
     QString newText(text);
     int ampIndex = qt_accAmpIndex(newText);
     if (ampIndex != -1)
         newText.remove(ampIndex, 1);
     return newText.replace(QLatin1String("&&"), QLatin1String("&"));
 }
qt_setWindowTitle_helperHelper()
QString qt_setWindowTitle_helperHelper (const QString & title, const QWidget * widget)
Returns a modified window title with the [*] place holder replaced according to the rules described in QWidget::setWindowTitle.
This function assumes that "[*]" can be quoted by another "[*]", so it will replace two place holders by one and a single last one by either "*" or nothing depending on the modified flag.
Warning
This function is not part of the public interface.
Definition at line 6240 of file qwidget.cpp.
Referenced by QAccessibleWidget::indexOfChild(), tabTextFor(), and QAccessibleWidget::text().
 {
     Q_ASSERT(widget);
 #ifdef QT_EVAL
     extern QString qt_eval_adapt_window_title(const QString &title);
     QString cap = qt_eval_adapt_window_title(title);
 #else
     QString cap = title;
 #endif
     if (cap.isEmpty())
         return cap;
     QLatin1String placeHolder("[*]");
     int placeHolderLength = 3; // QLatin1String doesn't have length()
     int index = cap.indexOf(placeHolder);
     // here the magic begins
     while (index != -1) {
         index += placeHolderLength;
         int count = 1;
         while (cap.indexOf(placeHolder, index) == index) {
             ++count;
             index += placeHolderLength;
         }
         if (count%2) { // odd number of [*] -> replace last one
             int lastIndex = cap.lastIndexOf(placeHolder, index - 1);
             if (widget->isWindowModified()
              && widget->style()->styleHint(QStyle::SH_TitleBar_ModifyNotification, 0, widget))
                 cap.replace(lastIndex, 3, QWidget::tr("*"));
             else
                 cap.remove(lastIndex, 3);
         }
         index = cap.indexOf(placeHolder, index);
     }
     cap.replace(QLatin1String("[*][*]"), placeHolder);
     return cap;
 }