Qt 4.8: /src/plugins/accessible/compat/qaccessiblecompat.cpp File Reference
qaccessiblecompat.cpp File Reference
#include "qaccessiblecompat.h"
#include "q3widgetstack.h"
#include <q3listview.h>
#include <q3textedit.h>
#include <q3iconview.h>
#include <q3listbox.h>
Functions
static Q3IconViewItem * findIVItem (Q3IconView *iconView, int child)
static Q3ListViewItem * findLVItem (Q3ListView *listView, int child)
Function Documentation
findIVItem()
static Q3IconViewItem* findIVItem (Q3IconView * iconView, int child) static
Definition at line 327 of file qaccessiblecompat.cpp.
Referenced by QAccessibleIconView::itemRect(), QAccessibleIconView::setSelected(), QAccessibleIconView::state(), and QAccessibleIconView::text().
 {
     int id = 1;
     Q3IconViewItem *item = iconView->firstItem();
     while (item && id < child) {
         item = item->nextItem();
         ++id;
     }
     return item;
 }
findLVItem()
static Q3ListViewItem* findLVItem (Q3ListView * listView, int child) static
Definition at line 97 of file qaccessiblecompat.cpp.
Referenced by QAccessibleListView::itemRect(), QAccessibleListView::setSelected(), QAccessibleListView::state(), and QAccessibleListView::text().
 {
     int id = 1;
     Q3ListViewItemIterator it(listView);
     Q3ListViewItem *item = it.current();
     while (item && id < child) {
         ++it;
         ++id;
         item = it.current();
     }
     return item;
 }