Qt 4.8: /src/plugins/accessible/widgets/qaccessiblewidgets.cpp File Reference
qaccessiblewidgets.cpp File Reference
#include "qaccessiblewidgets.h"
#include "qabstracttextdocumentlayout.h"
#include "qapplication.h"
#include "qclipboard.h"
#include "qtextedit.h"
#include "private/qtextedit_p.h"
#include "qtextdocument.h"
#include "qtextobject.h"
#include "qplaintextedit.h"
#include "qscrollbar.h"
#include "qdebug.h"
#include <QApplication>
#include <QStackedWidget>
#include <QToolBox>
#include <QMdiArea>
#include <QMdiSubWindow>
#include <QWorkspace>
#include <QDialogButtonBox>
#include <limits.h>
#include <QRubberBand>
#include <QTextBrowser>
#include <QCalendarWidget>
#include <QAbstractItemView>
#include <QDockWidget>
#include <QMainWindow>
#include <QAbstractButton>
#include <private/qdockwidget_p.h>
#include <QtGui/QFocusFrame>
Functions
QList< QWidget * > childWidgets (const QWidget *widget, bool includeTopLevel)
static int distance (QWidget *source, QWidget *target, QAccessible::RelationFlag relation)
static QWidget * mdiAreaNavigate (QWidget *area, QAccessible::RelationFlag relation, int entry)
QString Q_GUI_EXPORT qt_accHotKey (const QString &text)
QString Q_GUI_EXPORT qt_accStripAmp (const QString &text)
static QTextBlock qTextBlockAt (const QTextDocument *doc, int pos)
static int qTextBlockPosition (QTextBlock block)
Function Documentation
childWidgets()
QList<QWidget*> childWidgets (const QWidget * widget, bool includeTopLevel)
Definition at line 80 of file qaccessiblewidgets.cpp.
Referenced by QAccessibleMainWindow::childAt(), QAccessibleMainWindow::childCount(), QAccessibleMainWindow::indexOfChild(), and QAccessibleMainWindow::navigate().
 {
     if (widget == 0)
         return QList<QWidget*>();
     QList<QObject*> list = widget->children();
     QList<QWidget*> widgets;
     for (int i = 0; i < list.size(); ++i) {
         QWidget *w = qobject_cast<QWidget *>(list.at(i));
         if (!w)
             continue;
         QString objectName = w->objectName();
         if ((includeTopLevel || !w->isWindow())
               && !qobject_cast<QFocusFrame*>(w)
               && !qobject_cast<QMenu*>(w)
               && objectName != QLatin1String("qt_rubberband")
               && objectName != QLatin1String("qt_qmainwindow_extended_splitter")) {
             widgets.append(w);
         }
     }
     return widgets;
 }
distance()
static int distance (QWidget * source, QWidget * target, QAccessible::RelationFlag relation) inline static
Definition at line 102 of file qaccessiblewidgets.cpp.
Referenced by QDeclarativeTimeLine::accelDistance(), QListViewPrivate::closestIndex(), QIconLoaderEngine::entryForSize(), QGraphicsScenePrivate::findClosestTouchPointId(), QApplicationPrivate::findClosestTouchPointId(), findEncoding(), QDeclarativePathViewPrivate::handleMousePressEvent(), mdiAreaNavigate(), QTextEditPrivate::pageUpDown(), QSwipeGestureRecognizer::recognize(), QMacPrintEngine::setProperty(), QDeclarativePathViewPrivate::snapToCurrent(), and QDeclarativePathViewPrivate::updateHighlight().
 {
     if (!source || !target)
         return -1;
     int returnValue = -1;
     switch (relation) {
     case QAccessible::Up:
         if (target->y() <= source->y())
             returnValue = source->y() - target->y();
         break;
     case QAccessible::Down:
         if (target->y() >= source->y() + source->height())
             returnValue = target->y() - (source->y() + source->height());
         break;
     case QAccessible::Right:
         if (target->x() >= source->x() + source->width())
             returnValue = target->x() - (source->x() + source->width());
         break;
     case QAccessible::Left:
         if (target->x() <= source->x())
             returnValue = source->x() - target->x();
         break;
     default:
         break;
     }
     return returnValue;
 }
mdiAreaNavigate()
static QWidget* mdiAreaNavigate (QWidget * area, QAccessible::RelationFlag relation, int entry) inline static
Definition at line 132 of file qaccessiblewidgets.cpp.
Referenced by QAccessibleMdiArea::navigate(), QAccessibleMdiSubWindow::navigate(), and QAccessibleWorkspace::navigate().
 {
 #if defined(QT_NO_MDIAREA) && defined(QT_NO_WORKSPACE)
     Q_UNUSED(area);
 #endif
 #ifndef QT_NO_MDIAREA
     const QMdiArea *mdiArea = qobject_cast<QMdiArea *>(area);
 #endif
 #ifndef QT_NO_WORKSPACE
     const QWorkspace *workspace = qobject_cast<QWorkspace *>(area);
 #endif
     if (true
 #ifndef QT_NO_MDIAREA
         && !mdiArea
 #endif
 #ifndef QT_NO_WORKSPACE
     && !workspace
 #endif
     )
         return 0;
     QWidgetList windows;
 #ifndef QT_NO_MDIAREA
     if (mdiArea) {
         foreach (QMdiSubWindow *window, mdiArea->subWindowList())
             windows.append(window);
     } else
 #endif
     {
 #ifndef QT_NO_WORKSPACE
         foreach (QWidget *window, workspace->windowList())
             windows.append(window->parentWidget());
 #endif
     }
     if (windows.isEmpty() || entry < 1 || entry > windows.count())
         return 0;
     QWidget *source = windows.at(entry - 1);
     QMap<int, QWidget *> candidates;
     foreach (QWidget *window, windows) {
         if (source == window)
             continue;
         int candidateDistance = distance(source, window, relation);
         if (candidateDistance >= 0)
             candidates.insert(candidateDistance, window);
     }
     int minimumDistance = INT_MAX;
     QWidget *target = 0;
     foreach (QWidget *candidate, candidates) {
         switch (relation) {
         case QAccessible::Up:
         case QAccessible::Down:
             if (qAbs(candidate->x() - source->x()) < minimumDistance) {
                 target = candidate;
                 minimumDistance = qAbs(candidate->x() - source->x());
             }
             break;
         case QAccessible::Left:
         case QAccessible::Right:
             if (qAbs(candidate->y() - source->y()) < minimumDistance) {
                 target = candidate;
                 minimumDistance = qAbs(candidate->y() - source->y());
             }
             break;
         default:
             break;
         }
         if (minimumDistance == 0)
             break;
     }
 #ifndef QT_NO_WORKSPACE
     if (workspace) {
         foreach (QWidget *widget, workspace->windowList()) {
             if (widget->parentWidget() == target)
                 target = widget;
         }
     }
 #endif
     return target;
 }
qt_accHotKey()
QString Q_GUI_EXPORT qt_accHotKey (const QString & text)
Definition at line 145 of file qaccessiblewidget.cpp.
 {
     int ampIndex = qt_accAmpIndex(text);
     if (ampIndex != -1)
         return (QString)QKeySequence(Qt::ALT) + text.at(ampIndex + 1);
     return QString();
 }
qt_accStripAmp()
QString Q_GUI_EXPORT qt_accStripAmp (const QString & text)
Definition at line 135 of file qaccessiblewidget.cpp.
Referenced by QAccessibleTitleBar::text().
 {
     QString newText(text);
     int ampIndex = qt_accAmpIndex(newText);
     if (ampIndex != -1)
         newText.remove(ampIndex, 1);
     return newText.replace(QLatin1String("&&"), QLatin1String("&"));
 }
qTextBlockAt()
static QTextBlock qTextBlockAt (const QTextDocument * doc, int pos) static
Definition at line 228 of file qaccessiblewidgets.cpp.
Referenced by QAccessibleTextEdit::rect(), QAccessibleTextEdit::setText(), and QAccessibleTextEdit::text().
 {
     Q_ASSERT(pos >= 0);
     QTextBlock block = doc->begin();
     int i = 0;
     while (block.isValid() && i < pos) {
         block = block.next();
         ++i;
     }
     return block;
 }
qTextBlockPosition()
static int qTextBlockPosition (QTextBlock block) static
Definition at line 241 of file qaccessiblewidgets.cpp.
Referenced by QAccessibleTextEdit::childAt().
 {
     int child = 0;
     while (block.isValid()) {
         block = block.previous();
         ++child;
     }
     return child;
 }