Qt 4.8: /src/gui/accessible/qaccessibleobject.cpp File Reference
qaccessibleobject.cpp File Reference
#include "qaccessibleobject.h"
#include "qapplication.h"
#include "qwidget.h"
#include "qpointer.h"
#include "qmetaobject.h"
#include "qvarlengtharray.h"
Classes
class QAccessibleObjectPrivate
Functions
static QWidgetList topLevelWidgets ()
Variables
static const char *const action_text [][5]
Function Documentation
topLevelWidgets()
static QWidgetList topLevelWidgets () static
Definition at line 218 of file qaccessibleobject.cpp.
Referenced by QApplication::alert(), alert_widget(), QAccessibleApplication::childAt(), QAccessibleApplication::childCount(), QAccessibleApplication::doAction(), QAccessibleApplication::indexOfChild(), QAccessibleApplication::navigate(), parseGeometry(), qt_mac_should_disable_menu(), QApplication::qwsSetCustomColors(), QAccessibleApplication::relationTo(), and QApplication::syncX().
 {
     QWidgetList list;
     const QWidgetList tlw(QApplication::topLevelWidgets());
     for (int i = 0; i < tlw.count(); ++i) {
         QWidget *w = tlw.at(i);
         if (!(w->windowType() == Qt::Popup) && !(w->windowType() == Qt::Desktop))
             list.append(w);
     }
     return list;
 }
Variable Documentation
action_text
const char* const action_text[][5] static
Initial value:
=
{
    { "Press", "", "", "", "Space" },
    { "SetFocus", "Passes focus to this widget", "", "", "" },
    { "Increase", "", "", "", "" },
    { "Decrease", "", "", "", "" },
    { "Accept", "", "", "", "" },
    { "Cancel", "", "", "", "" },
    { "Select", "", "", "", "" },
    { "ClearSelection", "", "", "", "" },
    { "RemoveSelection", "", "", "", "" },
    { "ExtendSelection", "", "", "", "" },
    { "AddToSelection", "", "", "", "" }
}
Definition at line 171 of file qaccessibleobject.cpp.
Referenced by QAccessibleObject::actionText().