Qt 4.8: /src/gui/accessible/qaccessible2.cpp File Reference
qaccessible2.cpp File Reference
#include "qaccessible2.h"
#include "qapplication.h"
#include "qclipboard.h"
#include "qtextboundaryfinder.h"
Namespaces
QAccessible2
The QAccessible2 namespace defines constants relating to IAccessible2-based interfaces.
Functions
QString Q_GUI_EXPORT qTextAfterOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset, const QString &text)
QString Q_GUI_EXPORT qTextAtOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset, const QString &text)
QString Q_GUI_EXPORT qTextBeforeOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset, const QString &text)
static QString textForRange (QAccessibleInterface *iface, int startOffset, int endOffset)
Function Documentation
qTextAfterOffsetFromString()
QString Q_GUI_EXPORT qTextAfterOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int * startOffset, int * endOffset, const QString & text)
Warning
This function is not part of the public interface.
Definition at line 199 of file qaccessible2.cpp.
Referenced by QAccessibleLineEdit::textAfterOffset().
 {
     QTextBoundaryFinder::BoundaryType type;
     switch (boundaryType) {
     case QAccessible2::CharBoundary:
         type = QTextBoundaryFinder::Grapheme;
         break;
     case QAccessible2::WordBoundary:
         type = QTextBoundaryFinder::Word;
         break;
     case QAccessible2::SentenceBoundary:
         type = QTextBoundaryFinder::Sentence;
         break;
     default:
         // in any other case return the whole line
         *startOffset = 0;
         *endOffset = text.length();
         return text;
     }
     QTextBoundaryFinder boundary(type, text);
     boundary.setPosition(offset);
     boundary.toNextBoundary();
     *startOffset = boundary.position();
     boundary.toNextBoundary();
     *endOffset = boundary.position();
     return text.mid(*startOffset, *endOffset - *startOffset);
 }
qTextAtOffsetFromString()
QString Q_GUI_EXPORT qTextAtOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int * startOffset, int * endOffset, const QString & text)
Warning
This function is not part of the public interface.
Definition at line 234 of file qaccessible2.cpp.
Referenced by QAccessibleLineEdit::textAtOffset().
 {
     QTextBoundaryFinder::BoundaryType type;
     switch (boundaryType) {
     case QAccessible2::CharBoundary:
         type = QTextBoundaryFinder::Grapheme;
         break;
     case QAccessible2::WordBoundary:
         type = QTextBoundaryFinder::Word;
         break;
     case QAccessible2::SentenceBoundary:
         type = QTextBoundaryFinder::Sentence;
         break;
     default:
         // in any other case return the whole line
         *startOffset = 0;
         *endOffset = text.length();
         return text;
     }
     QTextBoundaryFinder boundary(type, text);
     boundary.setPosition(offset);
     if (!boundary.isAtBoundary()) {
         boundary.toPreviousBoundary();
     }
     *startOffset = boundary.position();
     boundary.toNextBoundary();
     *endOffset = boundary.position();
     return text.mid(*startOffset, *endOffset - *startOffset);
 }
qTextBeforeOffsetFromString()
QString Q_GUI_EXPORT qTextBeforeOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int * startOffset, int * endOffset, const QString & text)
Warning
This function is not part of the public interface.
Definition at line 161 of file qaccessible2.cpp.
Referenced by QAccessibleLineEdit::textBeforeOffset().
 {
     QTextBoundaryFinder::BoundaryType type;
     switch (boundaryType) {
     case QAccessible2::CharBoundary:
         type = QTextBoundaryFinder::Grapheme;
         break;
     case QAccessible2::WordBoundary:
         type = QTextBoundaryFinder::Word;
         break;
     case QAccessible2::SentenceBoundary:
         type = QTextBoundaryFinder::Sentence;
         break;
     default:
         // in any other case return the whole line
         *startOffset = 0;
         *endOffset = text.length();
         return text;
     }
     QTextBoundaryFinder boundary(type, text);
     boundary.setPosition(offset);
     if (!boundary.isAtBoundary()) {
         boundary.toPreviousBoundary();
     }
     boundary.toPreviousBoundary();
     *startOffset = boundary.position();
     boundary.toNextBoundary();
     *endOffset = boundary.position();
     return text.mid(*startOffset, *endOffset - *startOffset);
 }
textForRange()
static QString textForRange (QAccessibleInterface * iface, int startOffset, int endOffset) static
Definition at line 276 of file qaccessible2.cpp.
Referenced by QAccessibleSimpleEditableTextInterface::copyText(), and QAccessibleSimpleEditableTextInterface::cutText().
 {
     return iface->text(QAccessible::Value, 0).mid(startOffset, endOffset - startOffset);
 }