Qt 4.8: /src/gui/accessible/qaccessible_mac_carbon.cpp File Reference
qaccessible_mac_carbon.cpp File Reference
Functions
static OSStatus accessibilityEventHandler (EventHandlerCallRef next_ref, EventRef event, void *data)
static OSStatus applicationEventHandler (EventHandlerCallRef next_ref, EventRef event, void *data)
static void installAcessibilityEventHandler (HIObjectRef hiObject)
static void installApplicationEventhandler ()
static OSStatus objectCreateEventHandler (EventHandlerCallRef next_ref, EventRef event, void *data)
static void registerQtAccessibilityHIObjectSubclass ()
static void removeEventhandler (EventHandlerUPP eventHandler)
Variables
static EventHandlerUPP accessibilityEventHandlerUPP = 0
static EventTypeSpec accessibilityEvents []
static EventTypeSpec application_events []
static EventHandlerUPP applicationEventHandlerUPP = 0
static CFStringRef kObjectQtAccessibility = CFSTR("com.trolltech.qt.accessibility")
static EventHandlerUPP objectCreateEventHandlerUPP = 0
static EventTypeSpec objectCreateEvents []
Function Documentation
accessibilityEventHandler()
static OSStatus accessibilityEventHandler (EventHandlerCallRef next_ref, EventRef event, void * data) static
Referenced by installAcessibilityEventHandler().
applicationEventHandler()
static OSStatus applicationEventHandler (EventHandlerCallRef next_ref, EventRef event, void * data) static
Referenced by installApplicationEventhandler().
installAcessibilityEventHandler()
static void installAcessibilityEventHandler (HIObjectRef hiObject) static
Definition at line 72 of file qaccessible_mac_carbon.cpp.
Referenced by QAccessibleHierarchyManager::registerInterface().
 {
     if (!accessibilityEventHandlerUPP)
         accessibilityEventHandlerUPP = NewEventHandlerUPP(accessibilityEventHandler);
     InstallHIObjectEventHandler(hiObject, accessibilityEventHandlerUPP,
                                         GetEventTypeCount(accessibilityEvents),
                                         accessibilityEvents, 0, 0);
 }
installApplicationEventhandler()
static void installApplicationEventhandler () static
Definition at line 100 of file qaccessible_mac_carbon.cpp.
Referenced by QAccessible::initialize().
 {
     if (!applicationEventHandlerUPP)
         applicationEventHandlerUPP = NewEventHandlerUPP(applicationEventHandler);
     OSStatus err = InstallApplicationEventHandler(applicationEventHandlerUPP,
                             GetEventTypeCount(application_events), application_events,
                             0, 0);
     if (err && err != eventHandlerAlreadyInstalledErr)
         qWarning("qaccessible_mac internal error: Could not install application accessibility event handler");
 }
objectCreateEventHandler()
static OSStatus objectCreateEventHandler (EventHandlerCallRef next_ref, EventRef event, void * data) static
Definition at line 82 of file qaccessible_mac_carbon.cpp.
Referenced by registerQtAccessibilityHIObjectSubclass().
 {
     Q_UNUSED(data)
     Q_UNUSED(event)
     Q_UNUSED(next_ref)
     return noErr;
 }
registerQtAccessibilityHIObjectSubclass()
static void registerQtAccessibilityHIObjectSubclass () static
Definition at line 90 of file qaccessible_mac_carbon.cpp.
Referenced by QAccessible::initialize().
 {
     if (!objectCreateEventHandlerUPP)
         objectCreateEventHandlerUPP = NewEventHandlerUPP(objectCreateEventHandler);
     OSStatus err = HIObjectRegisterSubclass(kObjectQtAccessibility, 0, 0, objectCreateEventHandlerUPP,
                                          GetEventTypeCount(objectCreateEvents), objectCreateEvents, 0, 0);
     if (err && err != hiObjectClassExistsErr)
         qWarning("qaccessible_mac internal error: Could not register accessibility HIObject subclass");
 }
removeEventhandler()
static void removeEventhandler (EventHandlerUPP eventHandler) static
Definition at line 113 of file qaccessible_mac_carbon.cpp.
Referenced by QAccessible::cleanup().
 {
     if (eventHandler) {
         DisposeEventHandlerUPP(eventHandler);
         eventHandler = 0;
     }
 }
Variable Documentation
accessibilityEventHandlerUPP
EventHandlerUPP accessibilityEventHandlerUPP = 0 static
Definition at line 59 of file qaccessible_mac_carbon.cpp.
Referenced by QAccessible::cleanup(), and installAcessibilityEventHandler().
accessibilityEvents
EventTypeSpec accessibilityEvents[] static
Initial value:
= {
    { kEventClassAccessibility,  kEventAccessibleGetChildAtPoint },
    { kEventClassAccessibility,  kEventAccessibleGetFocusedChild },
    { kEventClassAccessibility,  kEventAccessibleGetAllAttributeNames },
    { kEventClassAccessibility,  kEventAccessibleGetNamedAttribute },
    { kEventClassAccessibility,  kEventAccessibleSetNamedAttribute },
    { kEventClassAccessibility,  kEventAccessibleIsNamedAttributeSettable },
    { kEventClassAccessibility,  kEventAccessibleGetAllActionNames },
    { kEventClassAccessibility,  kEventAccessiblePerformNamedAction },
    { kEventClassAccessibility,  kEventAccessibleGetNamedActionDescription }
}
Definition at line 60 of file qaccessible_mac_carbon.cpp.
Referenced by installAcessibilityEventHandler().
application_events
EventTypeSpec application_events[] static
Initial value:
= {
    { kEventClassAccessibility,  kEventAccessibleGetChildAtPoint },
    { kEventClassAccessibility,  kEventAccessibleGetNamedAttribute }
}
Definition at line 44 of file qaccessible_mac_carbon.cpp.
Referenced by installApplicationEventhandler().
applicationEventHandlerUPP
EventHandlerUPP applicationEventHandlerUPP = 0 static
Definition at line 43 of file qaccessible_mac_carbon.cpp.
Referenced by QAccessible::cleanup(), and installApplicationEventhandler().
kObjectQtAccessibility
CFStringRef kObjectQtAccessibility = CFSTR("com.trolltech.qt.accessibility") static
Definition at line 49 of file qaccessible_mac_carbon.cpp.
Referenced by QMultipleHIObjectFactory::registerChildren(), and registerQtAccessibilityHIObjectSubclass().
objectCreateEventHandlerUPP
EventHandlerUPP objectCreateEventHandlerUPP = 0 static
Definition at line 50 of file qaccessible_mac_carbon.cpp.
Referenced by QAccessible::cleanup(), and registerQtAccessibilityHIObjectSubclass().
objectCreateEvents
EventTypeSpec objectCreateEvents[] static
Initial value:
= {
    { kEventClassHIObject,  kEventHIObjectConstruct },
    { kEventClassHIObject,  kEventHIObjectInitialize },
    { kEventClassHIObject,  kEventHIObjectDestruct },
    { kEventClassHIObject,  kEventHIObjectPrintDebugInfo }
}
Definition at line 51 of file qaccessible_mac_carbon.cpp.
Referenced by registerQtAccessibilityHIObjectSubclass().