Qt 4.8: /src/corelib/tools/qalgorithms.h File Reference
qalgorithms.h File Reference
#include <QtCore/qglobal.h>
Namespaces
QAlgorithmsPrivate
Functions
template<typename RandomAccessIterator , typename T >
Q_OUTOFLINE_TEMPLATE RandomAccessIterator qBinaryFind (RandomAccessIterator begin, RandomAccessIterator end, const T &value)
template<typename RandomAccessIterator , typename T , typename LessThan >
Q_OUTOFLINE_TEMPLATE RandomAccessIterator qBinaryFind (RandomAccessIterator begin, RandomAccessIterator end, const T &value, LessThan lessThan)
template<typename Container , typename T >
Q_OUTOFLINE_TEMPLATE Container::const_iterator qBinaryFind (const Container &container, const T &value)
template<typename RandomAccessIterator , typename T , typename LessThan >
Q_OUTOFLINE_TEMPLATE RandomAccessIterator QAlgorithmsPrivate::qBinaryFindHelper (RandomAccessIterator begin, RandomAccessIterator end, const T &value, LessThan lessThan)
template<typename InputIterator , typename OutputIterator >
OutputIterator qCopy (InputIterator begin, InputIterator end, OutputIterator dest)
template<typename BiIterator1 , typename BiIterator2 >
BiIterator2 qCopyBackward (BiIterator1 begin, BiIterator1 end, BiIterator2 dest)
template<typename InputIterator , typename T , typename Size >
void qCount (InputIterator first, InputIterator last, const T &value, Size &n)
template<typename Container , typename T , typename Size >
void qCount (const Container &container, const T &value, Size &n)
template<typename ForwardIterator >
Q_OUTOFLINE_TEMPLATE void qDeleteAll (ForwardIterator begin, ForwardIterator end)
template<typename Container >
void qDeleteAll (const Container &c)
template<typename InputIterator1 , typename InputIterator2 >
bool qEqual (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2)
template<typename ForwardIterator , typename T >
void qFill (ForwardIterator first, ForwardIterator last, const T &val)
template<typename Container , typename T >
void qFill (Container &container, const T &val)
template<typename InputIterator , typename T >
InputIterator qFind (InputIterator first, InputIterator last, const T &val)
template<typename Container , typename T >
Container::const_iterator qFind (const Container &container, const T &val)
template<typename T >
LessThan qGreater ()
template<typename T >
LessThan qLess ()
template<typename RandomAccessIterator , typename T >
Q_OUTOFLINE_TEMPLATE RandomAccessIterator qLowerBound (RandomAccessIterator begin, RandomAccessIterator end, const T &value)
template<typename RandomAccessIterator , typename T , typename LessThan >
Q_OUTOFLINE_TEMPLATE RandomAccessIterator qLowerBound (RandomAccessIterator begin, RandomAccessIterator end, const T &value, LessThan lessThan)
template<typename Container , typename T >
Q_OUTOFLINE_TEMPLATE Container::const_iterator qLowerBound (const Container &container, const T &value)
template<typename RandomAccessIterator , typename T , typename LessThan >
Q_OUTOFLINE_TEMPLATE RandomAccessIterator QAlgorithmsPrivate::qLowerBoundHelper (RandomAccessIterator begin, RandomAccessIterator end, const T &value, LessThan lessThan)
template<typename RandomAccessIterator , typename T , typename LessThan >
Q_OUTOFLINE_TEMPLATE void QAlgorithmsPrivate::qMerge (RandomAccessIterator begin, RandomAccessIterator pivot, RandomAccessIterator end, T &t, LessThan lessThan)
template<typename RandomAccessIterator >
Q_OUTOFLINE_TEMPLATE void QAlgorithmsPrivate::qReverse (RandomAccessIterator begin, RandomAccessIterator end)
template<typename RandomAccessIterator >
Q_OUTOFLINE_TEMPLATE void QAlgorithmsPrivate::qRotate (RandomAccessIterator begin, RandomAccessIterator middle, RandomAccessIterator end)
template<typename RandomAccessIterator >
void qSort (RandomAccessIterator start, RandomAccessIterator end)
template<typename RandomAccessIterator , typename LessThan >
void qSort (RandomAccessIterator start, RandomAccessIterator end, LessThan lessThan)
template<typename Container >
void qSort (Container &c)
template<typename RandomAccessIterator , typename T , typename LessThan >
Q_OUTOFLINE_TEMPLATE void QAlgorithmsPrivate::qSortHelper (RandomAccessIterator start, RandomAccessIterator end, const T &t, LessThan lessThan)
template<typename RandomAccessIterator , typename T >
void QAlgorithmsPrivate::qSortHelper (RandomAccessIterator begin, RandomAccessIterator end, const T &dummy)
template<typename RandomAccessIterator >
void qStableSort (RandomAccessIterator start, RandomAccessIterator end)
template<typename RandomAccessIterator , typename LessThan >
void qStableSort (RandomAccessIterator start, RandomAccessIterator end, LessThan lessThan)
template<typename Container >
void qStableSort (Container &c)
template<typename RandomAccessIterator , typename T , typename LessThan >
Q_OUTOFLINE_TEMPLATE void QAlgorithmsPrivate::qStableSortHelper (RandomAccessIterator start, RandomAccessIterator end, const T &t, LessThan lessThan)
template<typename RandomAccessIterator , typename T >
void QAlgorithmsPrivate::qStableSortHelper (RandomAccessIterator, RandomAccessIterator, const T &)
template<typename RandomAccessIterator , typename T >
Q_OUTOFLINE_TEMPLATE RandomAccessIterator qUpperBound (RandomAccessIterator begin, RandomAccessIterator end, const T &value)
template<typename RandomAccessIterator , typename T , typename LessThan >
Q_OUTOFLINE_TEMPLATE RandomAccessIterator qUpperBound (RandomAccessIterator begin, RandomAccessIterator end, const T &value, LessThan lessThan)
template<typename Container , typename T >
Q_OUTOFLINE_TEMPLATE Container::const_iterator qUpperBound (const Container &container, const T &value)
template<typename RandomAccessIterator , typename T , typename LessThan >
Q_OUTOFLINE_TEMPLATE RandomAccessIterator QAlgorithmsPrivate::qUpperBoundHelper (RandomAccessIterator begin, RandomAccessIterator end, const T &value, LessThan lessThan)
Function Documentation
qBinaryFind() [1/3]
template<typename RandomAccessIterator , typename T > Q_OUTOFLINE_TEMPLATE RandomAccessIterator qBinaryFind (RandomAccessIterator begin, RandomAccessIterator end, const T & value)
Definition at line 295 of file qalgorithms.h.
Referenced by QFileSystemModelPrivate::_q_directoryChanged(), QRegExpEngine::addPlusTransitions(), QCP949Codec::convertFromUnicode(), QTextTablePrivate::findCellIndex(), findKnownValue(), get_named_rgb(), QGraphicsItemAnimationPrivate::insertUniquePair(), isKeyword(), ligatureHelper(), lookupElementHelper(), mapToLowerCase(), QTextTable::mergeCells(), qt_get_named_xpm_rgb(), qt_macSymbolForQtKey(), qtKey2CocoaKey(), resolveEntity(), string2PaperSize(), and QVariantAnimationPrivate::valueAt().
 {
     // Implementation is duplicated from QAlgorithmsPrivate.
     RandomAccessIterator it = qLowerBound(begin, end, value);
     if (it == end || value < *it)
         return end;
     return it;
 }
qBinaryFind() [2/3]
template<typename RandomAccessIterator , typename T , typename LessThan > Q_OUTOFLINE_TEMPLATE RandomAccessIterator qBinaryFind (RandomAccessIterator begin, RandomAccessIterator end, const T & value, LessThan lessThan)
Definition at line 307 of file qalgorithms.h.
 {
     return QAlgorithmsPrivate::qBinaryFindHelper(begin, end, value, lessThan);
 }
qBinaryFind() [3/3]
template<typename Container , typename T > Q_OUTOFLINE_TEMPLATE Container::const_iterator qBinaryFind (const Container & container, const T & value)
Definition at line 313 of file qalgorithms.h.
 {
     return QAlgorithmsPrivate::qBinaryFindHelper(container.constBegin(), container.constEnd(), value, qLess<T>());
 }
qCopy()
template<typename InputIterator , typename OutputIterator > OutputIterator qCopy (InputIterator begin, InputIterator end, OutputIterator dest) inline
Definition at line 79 of file qalgorithms.h.
Referenced by QVarLengthArray< QVariant, 9 >::erase(), QVector< QPoint >::erase(), QLinkedList< JSC::Identifier >::fromStdList(), QList< QPostEvent >::fromStdList(), QVector< QPoint >::fromStdVector(), QList< QPostEvent >::swap(), QLinkedList< JSC::Identifier >::toStdList(), QList< QPostEvent >::toStdList(), and QVector< QPoint >::toStdVector().
 {
     while (begin != end)
         *dest++ = *begin++;
     return dest;
 }
qCopyBackward()
template<typename BiIterator1 , typename BiIterator2 > BiIterator2 qCopyBackward (BiIterator1 begin, BiIterator1 end, BiIterator2 dest) inline
Definition at line 87 of file qalgorithms.h.
 {
     while (begin != end)
         *--dest = *--end;
     return dest;
 }
qCount() [1/2]
template<typename InputIterator , typename T , typename Size > void qCount (InputIterator first, InputIterator last, const T & value, Size & n) inline
Definition at line 131 of file qalgorithms.h.
Referenced by qCount().
 {
     for (; first != last; ++first)
         if (*first == value)
             ++n;
 }
qCount() [2/2]
template<typename Container , typename T , typename Size > void qCount (const Container & container, const T & value, Size & n) inline
Definition at line 139 of file qalgorithms.h.
 {
     qCount(container.constBegin(), container.constEnd(), value, n);
 }
qDeleteAll() [1/2]
template<typename ForwardIterator > Q_OUTOFLINE_TEMPLATE void qDeleteAll (ForwardIterator begin, ForwardIterator end)
Definition at line 319 of file qalgorithms.h.
Referenced by QSortFilterProxyModelPrivate::_q_clearMapping(), QWSServerPrivate::_q_deleteWindowsLater(), QSortFilterProxyModelPrivate::_q_sourceLayoutChanged(), QStateMachinePrivate::_q_start(), QPreviewPaintEngine::abort(), QPreviewPaintEngine::begin(), QGraphicsAnchorLayoutPrivate::calculateGraphs(), QGraphicsAnchorLayoutPrivate::calculateTrunk(), QGLGlyphCache::cleanCache(), cleanDriverDict(), cleanup(), QGestureManager::cleanupGesturesForRemovedRecognizer(), QAnimationGroup::clear(), QDeclarativeIntegerCache::clear(), QDeclarativeTypeNameCache::clear(), FlatListModel::clear(), QUndoStack::clear(), QSpanCollection::clear(), QDeclarativeScriptParser::clear(), QDeclarativeCompiledData::clear(), QDialogButtonBox::clear(), QTestEventList::clear(), QFontEngineFT::QGlyphSet::clear(), QHostInfoLookupManager::clear(), ModelNode::clear(), QStandardItemModel::clear(), QDeclarativePaintedItem::clearCache(), QDeclarativeTypeLoader::clearCache(), QTcpServer::close(), QLocalServer::close(), QWSPcMouseHandlerPrivate::closeDevices(), QWSServer::closeKeyboard(), QWSServer::closeMouse(), QScriptDebuggerLocalsModelPrivate::depopulate(), QBBIntegration::destroyDisplays(), QScriptDebuggerBackend::detach(), QFutureWatcherBase::disconnectOutputInterface(), QPdfBaseEngine::end(), QWindowSurface::endPaint(), QFutureWatcherBase::event(), QGestureManager::filterEventThroughContexts(), QPrintPreviewWidgetPrivate::populateScene(), QWaitConditionPrivate::post(), qDeleteAll(), qt_cleanup(), qt_delete_glyph_hash(), QFactoryLoader::refreshAll(), QDeclarativeWatcher::removeWatch(), QAccessibleHierarchyManager::reset(), QGraphicsAnchorLayoutPrivate::restoreVertices(), QDialogButtonBox::setStandardButtons(), QTextDocumentWithImageResources::setText(), QGraphicsAnchorLayoutPrivate::solvePreferred(), QDeclarativeParentAnimation::transition(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateRemovedRows(), QMYSQLResult::virtual_hook(), QWSDisplay::windowList(), QWSDisplay::Data::~Data(), FlatListModel::~FlatListModel(), QAxBasePrivate::~QAxBasePrivate(), QDBusConnectionPrivate::~QDBusConnectionPrivate(), QDeclarativeCompiledData::~QDeclarativeCompiledData(), QDeclarativeWorkerScriptEngine::~QDeclarativeWorkerScriptEngine(), QDirIteratorPrivateIteratorStack< QFileSystemIterator >::~QDirIteratorPrivateIteratorStack(), QDockWidgetLayout::~QDockWidgetLayout(), QEventDispatcherGlib::~QEventDispatcherGlib(), QEventDispatcherUNIXPrivate::~QEventDispatcherUNIXPrivate(), QFormLayout::~QFormLayout(), QGestureManager::~QGestureManager(), QGLEngineSharedShaders::~QGLEngineSharedShaders(), QGridLayoutEngine::~QGridLayoutEngine(), QItemEditorFactory::~QItemEditorFactory(), QNetworkAccessManager::~QNetworkAccessManager(), QNetworkConfigurationManagerPrivate::~QNetworkConfigurationManagerPrivate(), QNetworkManagerEngine::~QNetworkManagerEngine(), QObjectPrivate::~QObjectPrivate(), QPdfBaseEnginePrivate::~QPdfBaseEnginePrivate(), QPreviewPaintEngine::~QPreviewPaintEngine(), QProcessManager::~QProcessManager(), QRegExpEngine::~QRegExpEngine(), QScriptDebuggerBackendPrivate::~QScriptDebuggerBackendPrivate(), QScriptDebuggerConsoleCommandManagerPrivate::~QScriptDebuggerConsoleCommandManagerPrivate(), QScriptDebuggerLocalsModelNode::~QScriptDebuggerLocalsModelNode(), QScriptDebuggerPrivate::~QScriptDebuggerPrivate(), QScriptDebuggerScriptsModelPrivate::~QScriptDebuggerScriptsModelPrivate(), QScriptEnginePrivate::~QScriptEnginePrivate(), QSortFilterProxyModel::~QSortFilterProxyModel(), QSpanCollection::~QSpanCollection(), QStackedLayout::~QStackedLayout(), QStandardItemModelPrivate::~QStandardItemModelPrivate(), QStateMachinePrivate::~QStateMachinePrivate(), QSvgStructureNode::~QSvgStructureNode(), QTextDocumentWithImageResources::~QTextDocumentWithImageResources(), QUndoCommand::~QUndoCommand(), QWaylandClipboard::~QWaylandClipboard(), QWidgetAction::~QWidgetAction(), QWindowsVistaStylePrivate::~QWindowsVistaStylePrivate(), QWSClient::~QWSClient(), QWSServerPrivate::~QWSServerPrivate(), QWSSoundServerPrivate::~QWSSoundServerPrivate(), and QXcbConnection::~QXcbConnection().
 {
     while (begin != end) {
         delete *begin;
         ++begin;
     }
 }
qDeleteAll() [2/2]
template<typename Container > void qDeleteAll (const Container & c) inline
Definition at line 328 of file qalgorithms.h.
 {
     qDeleteAll(c.begin(), c.end());
 }
qEqual()
template<typename InputIterator1 , typename InputIterator2 > bool qEqual (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2) inline
Definition at line 95 of file qalgorithms.h.
 {
     for (; first1 != last1; ++first1, ++first2)
         if (!(*first1 == *first2))
             return false;
     return true;
 }
qFill() [1/2]
template<typename ForwardIterator , typename T > void qFill (ForwardIterator first, ForwardIterator last, const T & val) inline
Definition at line 104 of file qalgorithms.h.
Referenced by qFill().
 {
     for (; first != last; ++first)
         *first = val;
 }
qFill() [2/2]
template<typename Container , typename T > void qFill (Container & container, const T & val) inline
Definition at line 111 of file qalgorithms.h.
 {
     qFill(container.begin(), container.end(), val);
 }
qFind() [1/2]
template<typename InputIterator , typename T > InputIterator qFind (InputIterator first, InputIterator last, const T & val) inline
Definition at line 117 of file qalgorithms.h.
Referenced by qFind(), and QLinkedList< JSC::Identifier >::removeOne().
 {
     while (first != last && !(*first == val))
         ++first;
     return first;
 }
qFind() [2/2]
template<typename Container , typename T > Container::const_iterator qFind (const Container & container, const T & val) inline
Definition at line 125 of file qalgorithms.h.
 {
     return qFind(container.constBegin(), container.constEnd(), val);
 }
qGreater()
template<typename T > LessThan qGreater ()
Definition at line 151 of file qalgorithms.h.
 {
 }
qLess()
template<typename T > LessThan qLess ()
Definition at line 146 of file qalgorithms.h.
Referenced by qGreater().
 {
 }
qLowerBound() [1/3]
template<typename RandomAccessIterator , typename T > Q_OUTOFLINE_TEMPLATE RandomAccessIterator qLowerBound (RandomAccessIterator begin, RandomAccessIterator end, const T & value)
Definition at line 227 of file qalgorithms.h.
Referenced by QDBusConnectionPrivate::activateObject(), QDBusAdaptorConnector::addAdaptor(), QTextBlockGroup::blockInserted(), boundingRectOfFloatsInSelection(), QTextTable::cellAt(), QTextDocumentLayoutPrivate::drawFlow(), QTextDocumentLayoutPrivate::drawFrame(), QShortcutMap::find(), QNetworkAuthenticationCache::findClosestMatch(), findObject(), QTextTablePrivate::fragmentAdded(), QTextDocumentLayoutPrivate::frameIteratorForYPosition(), QShortcutMap::hasShortcutForKeySequence(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutFlow(), QDBusConnection::objectRegisteredAt(), qBinaryFind(), qDBusPropertyGet(), qDBusPropertyGetAll(), qDBusPropertySet(), QAlgorithmsPrivate::qMerge(), QVariantAnimationPrivate::recalculateCurrentInterval(), QDBusConnection::registerObject(), QVariantAnimationPrivate::setValueAt(), QListModel::sortedInsertionIterator(), QTreeModel::sortedInsertionIterator(), QTableModel::sortedInsertionIterator(), and QDBusConnection::unregisterObject().
 {
     // Implementation is duplicated from QAlgorithmsPrivate to keep existing code
     // compiling. We have to allow using *begin and value with different types,
     // and then implementing operator< for those types.
     RandomAccessIterator middle;
     int n = end - begin;
     int half;
     while (n > 0) {
         half = n >> 1;
         middle = begin + half;
         if (*middle < value) {
             begin = middle + 1;
             n -= half + 1;
         } else {
             n = half;
         }
     }
     return begin;
 }
qLowerBound() [2/3]
template<typename RandomAccessIterator , typename T , typename LessThan > Q_OUTOFLINE_TEMPLATE RandomAccessIterator qLowerBound (RandomAccessIterator begin, RandomAccessIterator end, const T & value, LessThan lessThan)
Definition at line 250 of file qalgorithms.h.
 {
     return QAlgorithmsPrivate::qLowerBoundHelper(begin, end, value, lessThan);
 }
qLowerBound() [3/3]
template<typename Container , typename T > Q_OUTOFLINE_TEMPLATE Container::const_iterator qLowerBound (const Container & container, const T & value)
Definition at line 256 of file qalgorithms.h.
 {
     return QAlgorithmsPrivate::qLowerBoundHelper(container.constBegin(), container.constEnd(), value, qLess<T>());
 }
qSort() [1/3]
template<typename RandomAccessIterator > void qSort (RandomAccessIterator start, RandomAccessIterator end) inline
Definition at line 177 of file qalgorithms.h.
Referenced by QFileSystemModelPrivate::_q_directoryChanged(), QFileSystemModelPrivate::_q_fileSystemChanged(), QScriptDebuggerConsoleWidgetPrivate::_q_onCompletionTaskFinished(), QGraphicsSceneBspTreeIndexPrivate::_q_updateSortCache(), QButtonGroup::addButton(), QDeclarativeTimeLinePrivate::advance(), QScriptEngine::availableExtensions(), bindFont(), QDeclarativeCompiler::buildObject(), QTessellatorPrivate::cancelCoincidingEdges(), QGraphicsSceneBspTreeIndexPrivate::climbTree(), QTessellatorPrivate::collectAndSortVertices(), QTreeViewPrivate::columnRanges(), QPathClipper::doClip(), QListWidget::dropEvent(), QGraphicsItemPrivate::ensureSequentialSiblingIndex(), QGraphicsScenePrivate::ensureSequentialTopLevelSiblingIndexes(), QListModel::ensureSorted(), QGraphicsItemPrivate::ensureSortedChildren(), QGraphicsScenePrivate::ensureSortedTopLevelItems(), QStateMachinePrivate::enterStates(), QPatternist::NodeSortExpression::evaluateSequence(), QPatternist::OrderBy::evaluateSequence(), QStateMachinePrivate::exitStates(), QPatternist::TemplateMode::finalize(), findAllLibCrypto(), findAllLibSsl(), generateGlyphTables(), QGraphicsScenePrivate::gestureEventHandler(), QMdi::MinOverlapPlacer::getCandidatePlacements(), QPathClipper::handleCrossingEdges(), QmlJSDebugger::BoundingRectHighlighter::highlight(), QScriptEngine::importedExtensions(), QPictureIO::inputFormats(), QGraphicsItemAnimationPrivate::insertUniquePair(), QWingedEdge::intersectAndAdd(), QFontEngine::loadKerningPairs(), operator<<(), QFontDatabase::pointSizes(), QDBusAdaptorConnector::polish(), QDeclarativeBasePositioner::prePositioning(), QTessellatorPrivate::processIntersections(), qGeomCalc(), QTest::qMedian(), qScanConvert(), QtPrivate::QStringList_sort(), qtKey2CocoaKey(), QWindowsXPStyle::QWindowsXPStyle(), QSortFilterProxyModel::removeRows(), QDeclarativeImportsPrivate::resolvedUri(), QVariantAnimation::setKeyValues(), QFontDatabase::smoothSizes(), QStringListModel::sort(), QListModel::sort(), QDirPrivate::sortFileList(), QGraphicsSceneBspTreeIndexPrivate::sortItems(), splitPolygon(), QTextDocumentWriter::supportedDocumentFormats(), QImageWriter::supportedImageFormats(), QImageReader::supportedImageFormats(), QConfFileSettingsPrivate::writeIniFile(), and QFontDatabase::writingSystems().
 {
     if (start != end)
         QAlgorithmsPrivate::qSortHelper(start, end, *start);
 }
qSort() [2/3]
template<typename RandomAccessIterator , typename LessThan > void qSort (RandomAccessIterator start, RandomAccessIterator end, LessThan lessThan) inline
Definition at line 184 of file qalgorithms.h.
 {
     if (start != end)
         QAlgorithmsPrivate::qSortHelper(start, end, *start, lessThan);
 }
qSort() [3/3]
template<typename Container > void qSort (Container & c) inline
Definition at line 191 of file qalgorithms.h.
 {
 #ifdef Q_CC_BOR
     // Work around Borland 5.5 optimizer bug
     c.detach();
 #endif
     if (!c.empty())
         QAlgorithmsPrivate::qSortHelper(c.begin(), c.end(), *c.begin());
 }
qStableSort() [1/3]
template<typename RandomAccessIterator > void qStableSort (RandomAccessIterator start, RandomAccessIterator end) inline
Definition at line 202 of file qalgorithms.h.
Referenced by QItemSelectionModelPrivate::_q_layoutChanged(), QScriptDebuggerConsoleCommandManager::completions(), QTreeModel::ensureSorted(), QTableModel::ensureSorted(), QPatternist::OrderBy::evaluateSequence(), QScriptDebuggerCommandExecutor::execute(), QSortFilterProxyModelPrivate::proxy_intervals_for_source_items(), QTableModel::sort(), QSortFilterProxyModelPrivate::sort_source_rows(), QStandardItemPrivate::sortChildren(), QFileSystemModelPrivate::sortChildren(), QTreeModel::sortItems(), and QScriptCompletionTask::start().
 {
     if (start != end)
         QAlgorithmsPrivate::qStableSortHelper(start, end, *start);
 }
qStableSort() [2/3]
template<typename RandomAccessIterator , typename LessThan > void qStableSort (RandomAccessIterator start, RandomAccessIterator end, LessThan lessThan) inline
Definition at line 209 of file qalgorithms.h.
 {
     if (start != end)
         QAlgorithmsPrivate::qStableSortHelper(start, end, *start, lessThan);
 }
qStableSort() [3/3]
template<typename Container > void qStableSort (Container & c) inline
Definition at line 216 of file qalgorithms.h.
 {
 #ifdef Q_CC_BOR
     // Work around Borland 5.5 optimizer bug
     c.detach();
 #endif
     if (!c.empty())
         QAlgorithmsPrivate::qStableSortHelper(c.begin(), c.end(), *c.begin());
 }
qUpperBound() [1/3]
template<typename RandomAccessIterator , typename T > Q_OUTOFLINE_TEMPLATE RandomAccessIterator qUpperBound (RandomAccessIterator begin, RandomAccessIterator end, const T & value)
Definition at line 262 of file qalgorithms.h.
Referenced by QPostEventList::addEvent(), QShortcutMap::addShortcut(), boundingRectOfFloatsInSelection(), QTextDocumentLayoutPrivate::drawFrame(), QThreadPoolPrivate::enqueueTask(), QAlgorithmsPrivate::qMerge(), QTextEngine::setBoundary(), and QTextTable::splitCell().
 {
     // Implementation is duplicated from QAlgorithmsPrivate.
     RandomAccessIterator middle;
     int n = end - begin;
     int half;
     while (n > 0) {
         half = n >> 1;
         middle = begin + half;
         if (value < *middle) {
             n = half;
         } else {
             begin = middle + 1;
             n -= half + 1;
         }
     }
     return begin;
 }
qUpperBound() [2/3]
template<typename RandomAccessIterator , typename T , typename LessThan > Q_OUTOFLINE_TEMPLATE RandomAccessIterator qUpperBound (RandomAccessIterator begin, RandomAccessIterator end, const T & value, LessThan lessThan)
Definition at line 283 of file qalgorithms.h.
 {
     return QAlgorithmsPrivate::qUpperBoundHelper(begin, end, value, lessThan);
 }
qUpperBound() [3/3]
template<typename Container , typename T > Q_OUTOFLINE_TEMPLATE Container::const_iterator qUpperBound (const Container & container, const T & value)
Definition at line 289 of file qalgorithms.h.
 {
     return QAlgorithmsPrivate::qUpperBoundHelper(container.constBegin(), container.constEnd(), value, qLess<T>());
 }