Qt 4.8: /src/gui/kernel/qapplication.cpp File Reference
qapplication.cpp File Reference
#include "qplatformdefs.h"
#include "qabstracteventdispatcher.h"
#include "qaccessible.h"
#include "qapplication.h"
#include "qclipboard.h"
#include "qcursor.h"
#include "qdesktopwidget.h"
#include "qdir.h"
#include "qevent.h"
#include "qfile.h"
#include "qfileinfo.h"
#include "qgraphicsscene.h"
#include "qhash.h"
#include "qset.h"
#include "qlayout.h"
#include "qsessionmanager.h"
#include "qstyle.h"
#include "qstylefactory.h"
#include "qtextcodec.h"
#include "qtranslator.h"
#include "qvariant.h"
#include "qwidget.h"
#include "qdnd_p.h"
#include "qcolormap.h"
#include "qdebug.h"
#include "private/qgraphicssystemfactory_p.h"
#include "private/qgraphicssystem_p.h"
#include "private/qstylesheetstyle_p.h"
#include "private/qstyle_p.h"
#include "qmessagebox.h"
#include <QtGui/qgraphicsproxywidget.h>
#include "qinputcontext.h"
#include "qkeymapper_p.h"
#include <private/qt_x11_p.h>
#include "qinputcontextfactory.h"
#include "qguiplatformplugin_p.h"
#include <qthread.h>
#include <private/qthread_p.h>
#include <private/qfont_p.h>
#include <stdlib.h>
#include <link.h>
#include "qapplication_p.h"
#include "qevent_p.h"
#include "qwidget_p.h"
#include "qgesture.h"
#include "private/qgesturemanager_p.h"
#include "qlibrary.h"
#include "qdatetime.h"
#include "qguifunctions_wince.h"
#include "moc_qapplication.cpp"
Classes
class QSessionManagerPrivate
Macros
#define CoCreateGuid qt_CoCreateGuid
#define QT_GUI_DRAG_DISTANCE 4
Functions
static void initResources ()
void qInitDrawhelperAsm ()
void qInitImageConversions ()
int qRegisterGuiStateMachine ()
int qRegisterGuiVariant ()
FontHash * qt_app_fonts_hash ()
PaletteHash * qt_app_palettes_hash ()
Q_CORE_EXPORT void qt_call_post_routines ()
void qt_cleanup ()
HRESULT qt_CoCreateGuid (GUID *guid)
static bool qt_detectRTLLanguage ()
void qt_init (QApplicationPrivate *priv, int type, Display *display=0, Qt::HANDLE visual=0, Qt::HANDLE colormap=0)
QString qt_mac_applicationmenu_string (int type)
em>Reimplemented Function
static int qt_matchLibraryName (dl_phdr_info *info, size_t, void *data)
bool qt_sendSpontaneousEvent (QObject *receiver, QEvent *event)
Q_GUI_EXPORT void qt_translateRawTouchEvent (QWidget *window, QTouchEvent::DeviceType deviceType, const QList< QTouchEvent::TouchPoint > &touchPoints)
Q_GUI_EXPORT bool qt_tryModalHelper (QWidget *widget, QWidget **rettop)
bool qt_wince_is_mobile ()
bool qt_wince_is_pocket_pc ()
bool qt_wince_is_smartphone ()
int qUnregisterGuiStateMachine ()
int qUnregisterGuiVariant ()
Variables
static int aargc = 1
static char * aargv [] = { (char*)"unknown", 0 }
static const char * application_menu_strings []
static const char *const copy_xpm []
static int drag_distance = QT_GUI_DRAG_DISTANCE
static int drag_time = 500
static bool force_reverse = false
static const char *const ignore_xpm []
static Qt::LayoutDirection layout_direction = Qt::LeftToRight
static const char *const link_xpm []
static const char *const move_xpm []
int qt_antialiasing_threshold = -1
QApplication::Type qt_appType =QApplication::Tty
QWidget * qt_button_down
QClipboard * qt_clipboard = 0
QDesktopWidget * qt_desktopWidget = 0
bool qt_in_tab_key_event = false
bool qt_is_gui_used
QPointer< QWidget > qt_last_mouse_receiver
QWidgetList * qt_modal_stack =0
QSessionManager * qt_session_manager_self = 0
bool Q_GUI_EXPORT qt_tab_all_widgets = true
bool qt_tabletChokeMouse = false
Macro Definition Documentation
CoCreateGuid
#define CoCreateGuid qt_CoCreateGuid
Definition at line 5038 of file qapplication.cpp.
Referenced by QUuid::operator>(), QSessionManager::QSessionManager(), and resolveGdi32().
QT_GUI_DRAG_DISTANCE
#define QT_GUI_DRAG_DISTANCE 4
Definition at line 498 of file qapplication.cpp.
Function Documentation
initResources()
static void initResources () static
Definition at line 135 of file qapplication.cpp.
Referenced by QApplicationPrivate::construct().
 {
 #if defined(Q_WS_WINCE)
     Q_INIT_RESOURCE_EXTERN(qstyle_wince)
     Q_INIT_RESOURCE(qstyle_wince);
 #elif defined(Q_OS_SYMBIAN)
     Q_INIT_RESOURCE_EXTERN(qstyle_s60)
     Q_INIT_RESOURCE(qstyle_s60);
 #else
     Q_INIT_RESOURCE_EXTERN(qstyle)
     Q_INIT_RESOURCE(qstyle);
 #endif
     Q_INIT_RESOURCE_EXTERN(qmessagebox)
     Q_INIT_RESOURCE(qmessagebox);
 #if !defined(QT_NO_PRINTDIALOG)
     Q_INIT_RESOURCE_EXTERN(qprintdialog)
     Q_INIT_RESOURCE(qprintdialog);
 #endif
 #ifdef Q_WS_MAC
     Q_INIT_RESOURCE_EXTERN(macresources)
     Q_INIT_RESOURCE(macresources);
 #endif
 }
qInitDrawhelperAsm()
void qInitDrawhelperAsm ()
Definition at line 7659 of file qdrawhelper.cpp.
Referenced by QApplication::QApplication(), and qt_qimageScaleAARGB().
 {
     qt_memfill32 = qt_memfill_template<quint32, quint32>;
     qt_memfill16 = qt_memfill_quint16; //qt_memfill_template<quint16, quint16>;
     CompositionFunction *functionForModeAsm = 0;
     CompositionFunctionSolid *functionForModeSolidAsm = 0;
     const uint features = qDetectCPUFeatures();
     if (false) {
 #ifdef QT_HAVE_SSE2
     } else if (features & SSE2) {
         qt_memfill32 = qt_memfill32_sse2;
         qt_memfill16 = qt_memfill16_sse2;
         qDrawHelper[QImage::Format_RGB32].bitmapBlit = qt_bitmapblit32_sse2;
         qDrawHelper[QImage::Format_ARGB32].bitmapBlit = qt_bitmapblit32_sse2;
         qDrawHelper[QImage::Format_ARGB32_Premultiplied].bitmapBlit = qt_bitmapblit32_sse2;
         qDrawHelper[QImage::Format_RGB16].bitmapBlit = qt_bitmapblit16_sse2;
 #endif
 #ifdef QT_HAVE_SSE
     } else if (features & SSE) {
 //        qt_memfill32 = qt_memfill32_sse;
         qDrawHelper[QImage::Format_RGB16].bitmapBlit = qt_bitmapblit16_sse;
 #ifdef QT_HAVE_3DNOW
         if (features & MMX3DNOW) {
             qt_memfill32 = qt_memfill32_sse3dnow;
             qDrawHelper[QImage::Format_RGB16].bitmapBlit = qt_bitmapblit16_sse3dnow;
         }
 #endif
 #endif // SSE
     }
 #ifdef QT_HAVE_MMX
     if (features & MMX) {
         functionForModeAsm = qt_functionForMode_MMX;
         functionForModeSolidAsm = qt_functionForModeSolid_MMX;
         qDrawHelper[QImage::Format_ARGB32_Premultiplied].blendColor = qt_blend_color_argb_mmx;
 #ifdef QT_HAVE_3DNOW
         if (features & MMX3DNOW) {
             functionForModeAsm = qt_functionForMode_MMX3DNOW;
             functionForModeSolidAsm = qt_functionForModeSolid_MMX3DNOW;
             qDrawHelper[QImage::Format_ARGB32_Premultiplied].blendColor = qt_blend_color_argb_mmx3dnow;
         }
 #endif // 3DNOW
         extern void qt_blend_rgb32_on_rgb32_mmx(uchar *destPixels, int dbpl,
                                                 const uchar *srcPixels, int sbpl,
                                                 int w, int h,
                                                 int const_alpha);
         extern void qt_blend_argb32_on_argb32_mmx(uchar *destPixels, int dbpl,
                                                   const uchar *srcPixels, int sbpl,
                                                   int w, int h,
                                                   int const_alpha);
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_mmx;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_mmx;
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_mmx;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_mmx;
     }
 #endif // MMX
 #ifdef QT_HAVE_SSE
     if (features & SSE) {
         extern void qt_blend_rgb32_on_rgb32_sse(uchar *destPixels, int dbpl,
                                                 const uchar *srcPixels, int sbpl,
                                                 int w, int h,
                                                 int const_alpha);
         extern void qt_blend_argb32_on_argb32_sse(uchar *destPixels, int dbpl,
                                                   const uchar *srcPixels, int sbpl,
                                                   int w, int h,
                                                   int const_alpha);
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_sse;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_sse;
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_sse;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_sse;
     }
 #endif // SSE
 #ifdef QT_HAVE_SSE2
     if (features & SSE2) {
         extern void qt_blend_rgb32_on_rgb32_sse2(uchar *destPixels, int dbpl,
                                                  const uchar *srcPixels, int sbpl,
                                                  int w, int h,
                                                  int const_alpha);
         extern void qt_blend_argb32_on_argb32_sse2(uchar *destPixels, int dbpl,
                                                    const uchar *srcPixels, int sbpl,
                                                    int w, int h,
                                                    int const_alpha);
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_sse2;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_sse2;
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_sse2;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_sse2;
         extern const uint * QT_FASTCALL qt_fetch_radial_gradient_sse2(uint *buffer, const Operator *op, const QSpanData *data,
                                                                       int y, int x, int length);
         qt_fetch_radial_gradient = qt_fetch_radial_gradient_sse2;
     }
 #ifdef QT_HAVE_SSSE3
     if (features & SSSE3) {
         extern void qt_blend_argb32_on_argb32_ssse3(uchar *destPixels, int dbpl,
                                                     const uchar *srcPixels, int sbpl,
                                                     int w, int h,
                                                     int const_alpha);
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_ssse3;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_ssse3;
     }
 #endif // SSSE3
 #endif // SSE2
 #ifdef QT_HAVE_SSE
     if (features & SSE) {
         functionForModeAsm = qt_functionForMode_SSE;
         functionForModeSolidAsm = qt_functionForModeSolid_SSE;
         qDrawHelper[QImage::Format_ARGB32_Premultiplied].blendColor = qt_blend_color_argb_sse;
 #ifdef QT_HAVE_3DNOW
         if (features & MMX3DNOW) {
             functionForModeAsm = qt_functionForMode_SSE3DNOW;
             functionForModeSolidAsm = qt_functionForModeSolid_SSE3DNOW;
             qDrawHelper[QImage::Format_ARGB32_Premultiplied].blendColor = qt_blend_color_argb_sse3dnow;
         }
 #endif // 3DNOW
 #ifdef QT_HAVE_SSE2
         if (features & SSE2) {
             extern void QT_FASTCALL comp_func_SourceOver_sse2(uint *destPixels,
                                                               const uint *srcPixels,
                                                               int length,
                                                               uint const_alpha);
             extern void QT_FASTCALL comp_func_solid_SourceOver_sse2(uint *destPixels, int length, uint color, uint const_alpha);
             extern void QT_FASTCALL comp_func_Plus_sse2(uint *dst, const uint *src, int length, uint const_alpha);
             extern void QT_FASTCALL comp_func_Source_sse2(uint *dst, const uint *src, int length, uint const_alpha);
             functionForModeAsm[0] = comp_func_SourceOver_sse2;
             functionForModeAsm[QPainter::CompositionMode_Source] = comp_func_Source_sse2;
             functionForModeAsm[QPainter::CompositionMode_Plus] = comp_func_Plus_sse2;
             functionForModeSolidAsm[0] = comp_func_solid_SourceOver_sse2;
         }
 #endif
     }
 #elif defined(QT_HAVE_SSE2)
     // this is the special case when SSE2 is usable but MMX/SSE is not usable (e.g.: Windows x64 + visual studio)
     if (features & SSE2) {
         functionForModeAsm = qt_functionForMode_onlySSE2;
         functionForModeSolidAsm = qt_functionForModeSolid_onlySSE2;
     }
 #endif
 #ifdef QT_HAVE_IWMMXT
     if (features & IWMMXT) {
         functionForModeAsm = qt_functionForMode_IWMMXT;
         functionForModeSolidAsm = qt_functionForModeSolid_IWMMXT;
         qDrawHelper[QImage::Format_ARGB32_Premultiplied].blendColor = qt_blend_color_argb_iwmmxt;
     }
 #endif // IWMMXT
 #if defined(QT_HAVE_ARM_SIMD)
     qBlendFunctions[QImage::Format_RGB32][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_arm_simd;
     qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_arm_simd;
     qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_arm_simd;
     qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_arm_simd;
 #elif defined(QT_HAVE_NEON)
     if (features & NEON) {
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_neon;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_neon;
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_neon;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_neon;
         qBlendFunctions[QImage::Format_RGB16][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_rgb16_neon;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB16] = qt_blend_rgb16_on_argb32_neon;
         qBlendFunctions[QImage::Format_RGB16][QImage::Format_RGB16] = qt_blend_rgb16_on_rgb16_neon;
         qScaleFunctions[QImage::Format_RGB16][QImage::Format_ARGB32_Premultiplied] = qt_scale_image_argb32_on_rgb16_neon;
         qScaleFunctions[QImage::Format_RGB16][QImage::Format_RGB16] = qt_scale_image_rgb16_on_rgb16_neon;
         qTransformFunctions[QImage::Format_RGB16][QImage::Format_ARGB32_Premultiplied] = qt_transform_image_argb32_on_rgb16_neon;
         qTransformFunctions[QImage::Format_RGB16][QImage::Format_RGB16] = qt_transform_image_rgb16_on_rgb16_neon;
         qDrawHelper[QImage::Format_RGB16].alphamapBlit = qt_alphamapblit_quint16_neon;
         functionForMode_C[QPainter::CompositionMode_SourceOver] = qt_blend_argb32_on_argb32_scanline_neon;
         functionForModeSolid_C[QPainter::CompositionMode_SourceOver] = comp_func_solid_SourceOver_neon;
         functionForMode_C[QPainter::CompositionMode_Plus] = comp_func_Plus_neon;
         destFetchProc[QImage::Format_RGB16] = qt_destFetchRGB16_neon;
         destStoreProc[QImage::Format_RGB16] = qt_destStoreRGB16_neon;
         qMemRotateFunctions[QImage::Format_RGB16][0] = qt_memrotate90_16_neon;
         qMemRotateFunctions[QImage::Format_RGB16][2] = qt_memrotate270_16_neon;
         qt_memfill32 = qt_memfill32_neon;
         extern const uint * QT_FASTCALL qt_fetch_radial_gradient_neon(uint *buffer, const Operator *op, const QSpanData *data,
                                                                       int y, int x, int length);
         qt_fetch_radial_gradient = qt_fetch_radial_gradient_neon;
     }
 #endif
     if (functionForModeSolidAsm) {
         const int destinationMode = QPainter::CompositionMode_Destination;
         functionForModeSolidAsm[destinationMode] = functionForModeSolid_C[destinationMode];
         // use the default qdrawhelper implementation for the
         // extended composition modes
         for (int mode = 12; mode < 24; ++mode)
             functionForModeSolidAsm[mode] = functionForModeSolid_C[mode];
         functionForModeSolid = functionForModeSolidAsm;
     }
     if (functionForModeAsm)
         functionForMode = functionForModeAsm;
     qt_build_pow_tables();
 }
qInitImageConversions()
void qInitImageConversions ()
Definition at line 3909 of file qimage.cpp.
Referenced by QApplication::QApplication().
 {
     const uint features = qDetectCPUFeatures();
     Q_UNUSED(features);
 #ifdef QT_HAVE_SSE2
     if (features & SSE2) {
         extern bool convert_ARGB_to_ARGB_PM_inplace_sse2(QImageData *data, Qt::ImageConversionFlags);
         inplace_converter_map[QImage::Format_ARGB32][QImage::Format_ARGB32_Premultiplied] = convert_ARGB_to_ARGB_PM_inplace_sse2;
     }
 #endif
 #ifdef QT_HAVE_SSSE3
     if (features & SSSE3) {
         extern void convert_RGB888_to_RGB32_ssse3(QImageData *dest, const QImageData *src, Qt::ImageConversionFlags);
         converter_map[QImage::Format_RGB888][QImage::Format_RGB32] = convert_RGB888_to_RGB32_ssse3;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32] = convert_RGB888_to_RGB32_ssse3;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32_Premultiplied] = convert_RGB888_to_RGB32_ssse3;
     }
 #endif
 #ifdef QT_HAVE_NEON
     if (features & NEON) {
         extern void convert_RGB888_to_RGB32_neon(QImageData *dest, const QImageData *src, Qt::ImageConversionFlags);
         converter_map[QImage::Format_RGB888][QImage::Format_RGB32] = convert_RGB888_to_RGB32_neon;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32] = convert_RGB888_to_RGB32_neon;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32_Premultiplied] = convert_RGB888_to_RGB32_neon;
     }
 #endif
 }
qRegisterGuiStateMachine()
int qRegisterGuiStateMachine ()
Definition at line 506 of file qguistatemachine.cpp.
Referenced by QApplication::QApplication().
 {
     qt_guistatemachine_last_handler = QStateMachinePrivate::handler;
     QStateMachinePrivate::handler = &qt_gui_statemachine_handler;
     return 1;
 }
qRegisterGuiVariant()
int qRegisterGuiVariant ()
Definition at line 811 of file qguivariant.cpp.
Referenced by QVariant::operator!=(), and QApplication::QApplication().
 {
     qt_guivariant_last_handler = QVariant::handler;
     QVariant::handler = &qt_gui_variant_handler;
     qMetaTypeGuiHelper = qVariantGuiHelper;
     return 1;
 }
qt_app_fonts_hash()
FontHash* qt_app_fonts_hash ()
Definition at line 553 of file qapplication.cpp.
Referenced by QMacStyle::drawControl(), QComboMenuDelegate::getStyleOption(), QMacStyle::polish(), qt_aqua_get_known_size(), QMessageBox::setInformativeText(), QMacStyle::subControlRect(), and QDockWidgetLayout::titleHeight().
 {
     return app_fonts();
 }
qt_app_palettes_hash()
PaletteHash* qt_app_palettes_hash ()
Definition at line 547 of file qapplication.cpp.
Referenced by QGtkStyleFilter::eventFilter(), and QApplicationPrivate::initializeWidgetPaletteHash().
 {
     return app_palettes();
 }
qt_call_post_routines()
Q_CORE_EXPORT void qt_call_post_routines ()
Definition at line 289 of file qcoreapplication.cpp.
Referenced by initResources(), QApplication::~QApplication(), and QCoreApplication::~QCoreApplication().
 {
     QVFuncList *list = 0;
     QT_TRY {
         list = postRList();
     } QT_CATCH(const std::bad_alloc &) {
         // ignore - if we can't allocate a post routine list,
         // there's a high probability that there's no post
         // routine to be executed :)
     }
     if (!list)
         return;
     while (!list->isEmpty())
         (list->takeFirst())();
 }
qt_cleanup()
void qt_cleanup ()
Definition at line 1328 of file qapplication_mac.mm.
Referenced by QApplication::~QApplication(), and QApplicationPrivate::~QApplicationPrivate().
 {
     CGDisplayRemoveReconfigurationCallback(qt_mac_display_change_callbk, 0);
     CFNotificationCenterRef center = CFNotificationCenterGetDistributedCenter();
     CFNotificationCenterRemoveObserver(center, qApp, kCMDeviceUnregisteredNotification, 0);
     CFNotificationCenterRemoveObserver(center, qApp, kCMDefaultDeviceNotification, 0);
     CFNotificationCenterRemoveObserver(center, qApp, kCMDeviceProfilesNotification, 0);
     CFNotificationCenterRemoveObserver(center, qApp, kCMDefaultDeviceProfileNotification, 0);
 #ifndef QT_MAC_USE_COCOA
     qt_release_app_proc_handler();
     if (app_proc_handlerUPP) {
         DisposeEventHandlerUPP(app_proc_handlerUPP);
         app_proc_handlerUPP = 0;
     }
 #endif
     qt_release_apple_event_handler();
 #ifdef QT_MAC_USE_COCOA
     qt_resetNSApplicationSendEvent();
 #endif
     qt_release_tablet_proximity_handler();
     if (tablet_proximity_UPP)
         DisposeEventHandlerUPP(tablet_proximity_UPP);
     QPixmapCache::clear();
     if (qt_is_gui_used) {
 #ifndef QT_NO_ACCESSIBILITY
         QAccessible::cleanup();
 #endif
 #ifndef QT_NO_IM
         QMacInputContext::cleanup();
 #endif
         QCursorData::cleanup();
         QFont::cleanup();
         QColormap::cleanup();
         if (qt_mac_safe_pdev) {
             delete qt_mac_safe_pdev;
             qt_mac_safe_pdev = 0;
         }
         extern void qt_mac_unregister_widget(); // qapplication_mac.cpp
         qt_mac_unregister_widget();
     }
 }
qt_CoCreateGuid()
HRESULT qt_CoCreateGuid (GUID * guid)
Definition at line 5021 of file qapplication.cpp.
 {
     // We will use the following information to create the GUID
     // 1. absolute path to application
     wchar_t tempFilename[MAX_PATH];
     if (!GetModuleFileName(0, tempFilename, MAX_PATH))
         return S_FALSE;
     unsigned int hash = qHash(QString::fromWCharArray(tempFilename));
     guid->Data1 = hash;
     // 2. creation time of file
     QFileInfo info(QString::fromWCharArray(tempFilename));
     guid->Data2 = qHash(info.created().toTime_t());
     // 3. current system time
     guid->Data3 = qHash(QDateTime::currentDateTime().toTime_t());
     return S_OK;
 }
qt_detectRTLLanguage()
static bool qt_detectRTLLanguage () static
Definition at line 2470 of file qapplication.cpp.
Referenced by QApplication::event().
 {
     return force_reverse ^
         (QApplication::tr("QT_LAYOUT_DIRECTION",
                          "Translate this string to the string 'LTR' in left-to-right"
                          " languages or to 'RTL' in right-to-left languages (such as Hebrew"
                          " and Arabic) to get proper widget layout.") == QLatin1String("RTL"));
 }
qt_init()
void qt_init (QApplicationPrivate * priv, int type, Display * display = 0, Qt::HANDLE visual = 0, Qt::HANDLE colormap = 0)
Definition at line 1666 of file qapplication_x11.cpp.
Referenced by QApplicationPrivate::construct(), and QApplicationPrivate::~QApplicationPrivate().
 {
     X11 = new QX11Data;
     X11->display = display;
     X11->displayName = 0;
     X11->foreignDisplay = (display != 0);
     X11->focus_model = -1;
     // RANDR
     X11->use_xrandr = false;
     X11->xrandr_major = 0;
     X11->xrandr_eventbase = 0;
     X11->xrandr_errorbase = 0;
     // RENDER
     X11->use_xrender = false;
     X11->xrender_major = 0;
     X11->xrender_version = 0;
     // XFIXES
     X11->use_xfixes = false;
     X11->xfixes_major = 0;
     X11->xfixes_eventbase = 0;
     X11->xfixes_errorbase = 0;
     // XInputExtension
     X11->use_xinput = false;
     X11->xinput_major = 0;
     X11->xinput_eventbase = 0;
     X11->xinput_errorbase = 0;
     X11->use_xkb = false;
     X11->xkb_major = 0;
     X11->xkb_eventbase = 0;
     X11->xkb_errorbase = 0;
     // MIT-SHM
     X11->use_mitshm = false;
     X11->use_mitshm_pixmaps = false;
     X11->mitshm_major = 0;
     X11->sip_serial = 0;
     X11->net_supported_list = 0;
     X11->net_virtual_root_list = 0;
     X11->wm_client_leader = 0;
     X11->screens = 0;
     X11->argbVisuals = 0;
     X11->argbColormaps = 0;
     X11->screenCount = 0;
     X11->time = CurrentTime;
     X11->userTime = CurrentTime;
     X11->ignore_badwindow = false;
     X11->seen_badwindow = false;
     X11->motifdnd_active = false;
     X11->default_im = QLatin1String("imsw-multi");
     priv->inputContext = 0;
     // colormap control
     X11->visual_class = -1;
     X11->visual_id = -1;
     X11->color_count = 0;
     X11->custom_cmap = false;
     // outside visual/colormap
     X11->visual = reinterpret_cast<Visual *>(visual);
     X11->colormap = colormap;
     // Fontconfig
     X11->has_fontconfig = false;
 #if !defined(QT_NO_FONTCONFIG)
     if (qgetenv("QT_X11_NO_FONTCONFIG").isNull())
         X11->has_fontconfig = FcInit();
     X11->fc_antialias = true;
 #endif
 #ifndef QT_NO_XRENDER
     memset(X11->solid_fills, 0, sizeof(X11->solid_fills));
     for (int i = 0; i < X11->solid_fill_count; ++i)
         X11->solid_fills[i].screen = -1;
     memset(X11->pattern_fills, 0, sizeof(X11->pattern_fills));
     for (int i = 0; i < X11->pattern_fill_count; ++i)
         X11->pattern_fills[i].screen = -1;
 #endif
     X11->startupId = 0;
     int argc = priv->argc;
     char **argv = priv->argv;
     if (X11->display) {
         // Qt part of other application
         // Set application name and class
         appName = qstrdup("Qt-subapplication");
         char *app_class = 0;
         if (argv) {
             const char* p = strrchr(argv[0], '/');
             app_class = qstrdup(p ? p + 1 : argv[0]);
             if (app_class[0])
                 app_class[0] = toupper(app_class[0]);
         }
         appClass = app_class;
     } else {
         // Qt controls everything (default)
         if (QApplication::testAttribute(Qt::AA_X11InitThreads))
             XInitThreads();
         // Set application name and class
         char *app_class = 0;
         if (argv && argv[0]) {
             const char *p = strrchr(argv[0], '/');
             appName = p ? p + 1 : argv[0];
             app_class = qstrdup(appName);
             if (app_class[0])
                 app_class[0] = toupper(app_class[0]);
         }
         appClass = app_class;
     }
     // Install default error handlers
     original_x_errhandler = XSetErrorHandler(qt_x_errhandler);
     original_xio_errhandler = XSetIOErrorHandler(qt_xio_errhandler);
     // Get command line params
     int j = argc ? 1 : 0;
     for (int i=1; i<argc; i++) {
         if (argv[i] && *argv[i] != '-') {
             argv[j++] = argv[i];
             continue;
         }
         QByteArray arg(argv[i]);
         if (arg == "-display") {
             if (++i < argc && !X11->display)
                 X11->displayName = argv[i];
         } else if (arg == "-fn" || arg == "-font") {
             if (++i < argc)
                 appFont = argv[i];
         } else if (arg == "-bg" || arg == "-background") {
             if (++i < argc)
                 appBGCol = argv[i];
         } else if (arg == "-btn" || arg == "-button") {
             if (++i < argc)
                 appBTNCol = argv[i];
         } else if (arg == "-fg" || arg == "-foreground") {
             if (++i < argc)
                 appFGCol = argv[i];
         } else if (arg == "-name") {
             if (++i < argc)
                 appName = argv[i];
         } else if (arg == "-title") {
             if (++i < argc)
                 mwTitle = argv[i];
         } else if (arg == "-geometry") {
             if (++i < argc)
                 mwGeometry = argv[i];
         } else if (arg == "-im") {
             if (++i < argc)
                 qt_ximServer = argv[i];
         } else if (arg == "-ncols") {   // xv and netscape use this name
             if (++i < argc)
                 X11->color_count = qMax(0,atoi(argv[i]));
         } else if (arg == "-visual") {  // xv and netscape use this name
             if (++i < argc && !X11->visual) {
                 QString s = QString::fromLocal8Bit(argv[i]).toLower();
                 if (s == QLatin1String("staticgray"))
                     X11->visual_class = StaticGray;
                 else if (s == QLatin1String("grayscale"))
                     X11->visual_class = XGrayScale;
                 else if (s == QLatin1String("staticcolor"))
                     X11->visual_class = StaticColor;
                 else if (s == QLatin1String("pseudocolor"))
                     X11->visual_class = PseudoColor;
                 else if (s == QLatin1String("truecolor"))
                     X11->visual_class = TrueColor;
                 else if (s == QLatin1String("directcolor"))
                     X11->visual_class = DirectColor;
                 else
                     X11->visual_id = static_cast<int>(strtol(argv[i], 0, 0));
             }
 #ifndef QT_NO_XIM
         } else if (arg == "-inputstyle") {
             if (++i < argc) {
                 QString s = QString::fromLocal8Bit(argv[i]).toLower();
                 if (s == QLatin1String("onthespot"))
                     qt_xim_preferred_style = XIMPreeditCallbacks |
                                              XIMStatusNothing;
                 else if (s == QLatin1String("overthespot"))
                     qt_xim_preferred_style = XIMPreeditPosition |
                                              XIMStatusNothing;
                 else if (s == QLatin1String("offthespot"))
                     qt_xim_preferred_style = XIMPreeditArea |
                                              XIMStatusArea;
                 else if (s == QLatin1String("root"))
                     qt_xim_preferred_style = XIMPreeditNothing |
                                              XIMStatusNothing;
             }
 #endif
         } else if (arg == "-cmap") {    // xv uses this name
             if (!X11->colormap)
                 X11->custom_cmap = true;
         }
         else if (arg == "-sync")
             appSync = !appSync;
 #if defined(QT_DEBUG)
         else if (arg == "-nograb")
             appNoGrab = !appNoGrab;
         else if (arg == "-dograb")
             appDoGrab = !appDoGrab;
 #endif
         else
             argv[j++] = argv[i];
     }
     priv->argc = j;
 #if defined(QT_DEBUG) && defined(Q_OS_LINUX)
     if (!appNoGrab && !appDoGrab && runningUnderDebugger()) {
         appNoGrab = true;
         qDebug("Qt: gdb: -nograb added to command-line options.\n"
                "\t Use the -dograb option to enforce grabbing.");
     }
 #endif
     // Connect to X server
     if (qt_is_gui_used && !X11->display) {
         if ((X11->display = XOpenDisplay(X11->displayName)) == 0) {
             qWarning("%s: cannot connect to X server %s", appName,
                      XDisplayName(X11->displayName));
             QApplicationPrivate::reset_instance_pointer();
             exit(1);
         }
         if (appSync)                                // if "-sync" argument
             XSynchronize(X11->display, true);
     }
     // Common code, regardless of whether display is foreign.
     // Get X parameters
     if (qt_is_gui_used) {
         X11->defaultScreen = DefaultScreen(X11->display);
         X11->screenCount = ScreenCount(X11->display);
         int formatCount = 0;
         XPixmapFormatValues *values = XListPixmapFormats(X11->display, &formatCount);
         for (int i = 0; i < formatCount; ++i)
             X11->bppForDepth[values[i].depth] = values[i].bits_per_pixel;
         XFree(values);
         X11->screens = new QX11InfoData[X11->screenCount];
         X11->argbVisuals = new Visual *[X11->screenCount];
         X11->argbColormaps = new Colormap[X11->screenCount];
         for (int s = 0; s < X11->screenCount; s++) {
             QX11InfoData *screen = X11->screens + s;
             screen->ref = 1; // ensures it doesn't get deleted
             screen->screen = s;
             int widthMM = DisplayWidthMM(X11->display, s);
             if (widthMM != 0) {
                 screen->dpiX = (DisplayWidth(X11->display, s) * 254 + widthMM * 5) / (widthMM * 10);
             } else {
                 screen->dpiX = 72;
             }
             int heightMM = DisplayHeightMM(X11->display, s);
             if (heightMM != 0) {
                 screen->dpiY = (DisplayHeight(X11->display, s) * 254 + heightMM * 5) / (heightMM * 10);
             } else {
                 screen->dpiY = 72;
             }
             X11->argbVisuals[s] = 0;
             X11->argbColormaps[s] = 0;
         }
 #ifndef QT_NO_XRENDER
         int xrender_eventbase,  xrender_errorbase;
         // See if XRender is supported on the connected display
         if (XQueryExtension(X11->display, "RENDER", &X11->xrender_major,
                             &xrender_eventbase, &xrender_errorbase)
             && XRenderQueryExtension(X11->display, &xrender_eventbase,
                                      &xrender_errorbase)) {
             // Check the version as well - we need v0.4 or higher
             int major = 0;
             int minor = 0;
             XRenderQueryVersion(X11->display, &major, &minor);
             if (qgetenv("QT_X11_NO_XRENDER").isNull()) {
                 X11->use_xrender = (major >= 0 && minor >= 5);
                 X11->xrender_version = major*100+minor;
                 // workaround for broken XServer on Ubuntu Breezy (6.8 compiled with 7.0
                 // protocol headers)
                 if (X11->xrender_version == 10
                     && VendorRelease(X11->display) < 60900000
                     && QByteArray(ServerVendor(X11->display)).contains("X.Org"))
                     X11->xrender_version = 9;
             }
         }
 #endif // QT_NO_XRENDER
 #ifndef QT_NO_MITSHM
         int mitshm_minor;
         int mitshm_major;
         int mitshm_eventbase;
         int mitshm_errorbase;
         int mitshm_pixmaps;
         if (XQueryExtension(X11->display, "MIT-SHM", &X11->mitshm_major,
                             &mitshm_eventbase, &mitshm_errorbase)
             && XShmQueryVersion(X11->display, &mitshm_major, &mitshm_minor,
                                 &mitshm_pixmaps))
         {
             QString displayName = QLatin1String(XDisplayName(NULL));
             // MITSHM only works for local displays, so do a quick check here
             // to determine whether the display is local or not (not 100 % accurate).
             // BGR server layouts are not supported either, since it requires the raster
             // engine to work on a QImage with BGR layout.
             bool local = displayName.isEmpty() || displayName.lastIndexOf(QLatin1Char(':')) == 0;
             if (local && (qgetenv("QT_X11_NO_MITSHM").toInt() == 0)) {
                 Visual *defaultVisual = DefaultVisual(X11->display, DefaultScreen(X11->display));
                 X11->use_mitshm = ((defaultVisual->red_mask == 0xff0000
                                     || defaultVisual->red_mask == 0xf800)
                                    && (defaultVisual->green_mask == 0xff00
                                        || defaultVisual->green_mask == 0x7e0)
                                    && (defaultVisual->blue_mask == 0xff
                                        || defaultVisual->blue_mask == 0x1f));
                 X11->use_mitshm_pixmaps = X11->use_mitshm && mitshm_pixmaps;
             }
         }
 #endif // QT_NO_MITSHM
         // initialize the graphics system - order is imporant here - it must be done before
         // the QColormap::initialize() call
         QApplicationPrivate::graphics_system = QGraphicsSystemFactory::create(QApplicationPrivate::graphics_system_name);
         QColormap::initialize();
         // Support protocols
         X11->xdndSetup();
         // Finally create all atoms
         qt_x11_create_intern_atoms();
         // initialize NET lists
         qt_get_net_supported();
         qt_get_net_virtual_roots();
 #ifndef QT_NO_XRANDR
         // See if XRandR is supported on the connected display
         if (XQueryExtension(X11->display, "RANDR", &X11->xrandr_major,
                             &X11->xrandr_eventbase, &X11->xrandr_errorbase)) {
 #  ifdef QT_RUNTIME_XRANDR
             X11->ptrXRRSelectInput = 0;
             X11->ptrXRRUpdateConfiguration = 0;
             X11->ptrXRRRootToScreen = 0;
             X11->ptrXRRQueryExtension = 0;
             QLibrary xrandrLib(QLatin1String("Xrandr"), 2);
             xrandrLib.setLoadHints(QLibrary::ImprovedSearchHeuristics);
             if (!xrandrLib.load()) { // try without the version number
                 xrandrLib.setFileName(QLatin1String("Xrandr"));
                 xrandrLib.load();
             }
             if (xrandrLib.isLoaded()) {
                 X11->ptrXRRSelectInput =
                     (PtrXRRSelectInput) xrandrLib.resolve("XRRSelectInput");
                 X11->ptrXRRUpdateConfiguration =
                     (PtrXRRUpdateConfiguration) xrandrLib.resolve("XRRUpdateConfiguration");
                 X11->ptrXRRRootToScreen =
                     (PtrXRRRootToScreen) xrandrLib.resolve("XRRRootToScreen");
                 X11->ptrXRRQueryExtension =
                     (PtrXRRQueryExtension) xrandrLib.resolve("XRRQueryExtension");
             }
 #  else
             X11->ptrXRRSelectInput = XRRSelectInput;
             X11->ptrXRRUpdateConfiguration = XRRUpdateConfiguration;
             X11->ptrXRRRootToScreen = XRRRootToScreen;
             X11->ptrXRRQueryExtension = XRRQueryExtension;
 #  endif
             if (X11->ptrXRRQueryExtension
                 && X11->ptrXRRQueryExtension(X11->display, &X11->xrandr_eventbase, &X11->xrandr_errorbase)) {
                 // XRandR is supported
                 X11->use_xrandr = true;
             }
         }
 #endif // QT_NO_XRANDR
 #ifndef QT_NO_XRENDER
         if (X11->use_xrender) {
             // XRender is supported, let's see if we have a PictFormat for the
             // default visual
             XRenderPictFormat *format =
                 XRenderFindVisualFormat(X11->display,
                                         (Visual *) QX11Info::appVisual(X11->defaultScreen));
             if (!format) {
                 X11->use_xrender = false;
             }
         }
 #endif // QT_NO_XRENDER
 #ifndef QT_NO_XFIXES
         // See if Xfixes is supported on the connected display
         if (XQueryExtension(X11->display, "XFIXES", &X11->xfixes_major,
                             &X11->xfixes_eventbase, &X11->xfixes_errorbase)) {
             X11->ptrXFixesQueryExtension  = XFIXES_LOAD_V1(XFixesQueryExtension);
             X11->ptrXFixesQueryVersion    = XFIXES_LOAD_V1(XFixesQueryVersion);
             X11->ptrXFixesSetCursorName   = XFIXES_LOAD_V2(XFixesSetCursorName);
             X11->ptrXFixesSelectSelectionInput = XFIXES_LOAD_V2(XFixesSelectSelectionInput);
             if(X11->ptrXFixesQueryExtension && X11->ptrXFixesQueryVersion
                && X11->ptrXFixesQueryExtension(X11->display, &X11->xfixes_eventbase,
                                                &X11->xfixes_errorbase)) {
                 // Xfixes is supported.
                 // Note: the XFixes protocol version is negotiated using QueryVersion.
                 // We supply the highest version we support, the X server replies with
                 // the highest version it supports, but no higher than the version we
                 // asked for. The version sent back is the protocol version the X server
                 // will use to talk us. If this call is removed, the behavior of the
                 // X server when it receives an XFixes request is undefined.
                 int major = 3;
                 int minor = 0;
                 X11->ptrXFixesQueryVersion(X11->display, &major, &minor);
                 X11->use_xfixes = (major >= 1);
                 X11->xfixes_major = major;
             }
         } else {
             X11->ptrXFixesQueryExtension  = 0;
             X11->ptrXFixesQueryVersion    = 0;
             X11->ptrXFixesSetCursorName   = 0;
             X11->ptrXFixesSelectSelectionInput = 0;
         }
 #endif // QT_NO_XFIXES
 #ifndef QT_NO_XCURSOR
 #ifdef QT_RUNTIME_XCURSOR
         X11->ptrXcursorLibraryLoadCursor = 0;
         QLibrary xcursorLib(QLatin1String("Xcursor"), 1);
         xcursorLib.setLoadHints(QLibrary::ImprovedSearchHeuristics);
         bool xcursorFound = xcursorLib.load();
         if (!xcursorFound) { //try without the version number
             xcursorLib.setFileName(QLatin1String("Xcursor"));
             xcursorFound = xcursorLib.load();
         }
         if (xcursorFound) {
             X11->ptrXcursorLibraryLoadCursor =
                 (PtrXcursorLibraryLoadCursor) xcursorLib.resolve("XcursorLibraryLoadCursor");
         }
 #else
         X11->ptrXcursorLibraryLoadCursor = XcursorLibraryLoadCursor;
 #endif // QT_RUNTIME_XCURSOR
 #endif // QT_NO_XCURSOR
 #ifndef QT_NO_XSYNC
         int xsync_evbase, xsync_errbase;
         int major, minor;
         if (XSyncQueryExtension(X11->display, &xsync_evbase, &xsync_errbase))
             XSyncInitialize(X11->display, &major, &minor);
 #endif // QT_NO_XSYNC
 #ifndef QT_NO_XINERAMA
 #ifdef QT_RUNTIME_XINERAMA
         X11->ptrXineramaQueryExtension = 0;
         X11->ptrXineramaIsActive = 0;
         X11->ptrXineramaQueryScreens = 0;
         QLibrary xineramaLib(QLatin1String("Xinerama"), 1);
         xineramaLib.setLoadHints(QLibrary::ImprovedSearchHeuristics);
         bool xineramaFound = xineramaLib.load();
         if (!xineramaFound) { //try without the version number
             xineramaLib.setFileName(QLatin1String("Xinerama"));
             xineramaFound = xineramaLib.load();
         }
         if (xineramaFound) {
             X11->ptrXineramaQueryExtension =
                 (PtrXineramaQueryExtension) xineramaLib.resolve("XineramaQueryExtension");
             X11->ptrXineramaIsActive =
                 (PtrXineramaIsActive) xineramaLib.resolve("XineramaIsActive");
             X11->ptrXineramaQueryScreens =
                 (PtrXineramaQueryScreens) xineramaLib.resolve("XineramaQueryScreens");
         }
 #else
         X11->ptrXineramaQueryScreens = XineramaQueryScreens;
         X11->ptrXineramaIsActive = XineramaIsActive;
         X11->ptrXineramaQueryExtension = XineramaQueryExtension;
 #endif // QT_RUNTIME_XINERAMA
 #endif // QT_NO_XINERAMA
 #ifndef QT_NO_XINPUT
         // See if Xinput is supported on the connected display
         X11->ptrXCloseDevice = 0;
         X11->ptrXListInputDevices = 0;
         X11->ptrXOpenDevice = 0;
         X11->ptrXFreeDeviceList = 0;
         X11->ptrXSelectExtensionEvent = 0;
         X11->use_xinput = XQueryExtension(X11->display, "XInputExtension", &X11->xinput_major,
                                           &X11->xinput_eventbase, &X11->xinput_errorbase);
         if (X11->use_xinput) {
             X11->ptrXCloseDevice = XINPUT_LOAD(XCloseDevice);
             X11->ptrXListInputDevices = XINPUT_LOAD(XListInputDevices);
             X11->ptrXOpenDevice = XINPUT_LOAD(XOpenDevice);
             X11->ptrXFreeDeviceList = XINPUT_LOAD(XFreeDeviceList);
             X11->ptrXSelectExtensionEvent = XINPUT_LOAD(XSelectExtensionEvent);
         }
 #endif // QT_NO_XINPUT
 #ifndef QT_NO_XKB
         int xkblibMajor = XkbMajorVersion;
         int xkblibMinor = XkbMinorVersion;
         X11->use_xkb = XkbQueryExtension(X11->display,
                                          &X11->xkb_major,
                                          &X11->xkb_eventbase,
                                          &X11->xkb_errorbase,
                                          &xkblibMajor,
                                          &xkblibMinor);
         if (X11->use_xkb) {
             // If XKB is detected, set the GrabsUseXKBState option so input method
             // compositions continue to work (ie. deadkeys)
             unsigned int state = XkbPCF_GrabsUseXKBStateMask;
             (void) XkbSetPerClientControls(X11->display, state, &state);
             // select for group change events
             XkbSelectEventDetails(X11->display,
                                   XkbUseCoreKbd,
                                   XkbStateNotify,
                                   XkbAllStateComponentsMask,
                                   XkbGroupStateMask);
             // current group state is queried when creating the keymapper, no need to do it here
         }
 #endif
 #if !defined(QT_NO_FONTCONFIG)
         int dpi = 0;
         getXDefault("Xft", FC_DPI, &dpi);
         if (dpi) {
             for (int s = 0; s < ScreenCount(X11->display); ++s) {
                 QX11Info::setAppDpiX(s, dpi);
                 QX11Info::setAppDpiY(s, dpi);
             }
         }
         double fc_scale = 1.;
         getXDefault("Xft", FC_SCALE, &fc_scale);
         X11->fc_scale = fc_scale;
         for (int s = 0; s < ScreenCount(X11->display); ++s) {
             int subpixel = FC_RGBA_UNKNOWN;
 #if !defined(QT_NO_XRENDER) && (RENDER_MAJOR > 0 || RENDER_MINOR >= 6)
             if (X11->use_xrender) {
                 int rsp = XRenderQuerySubpixelOrder(X11->display, s);
                 switch (rsp) {
                 default:
                 case SubPixelUnknown:
                     subpixel = FC_RGBA_UNKNOWN;
                     break;
                 case SubPixelHorizontalRGB:
                     subpixel = FC_RGBA_RGB;
                     break;
                 case SubPixelHorizontalBGR:
                     subpixel = FC_RGBA_BGR;
                     break;
                 case SubPixelVerticalRGB:
                     subpixel = FC_RGBA_VRGB;
                     break;
                 case SubPixelVerticalBGR:
                     subpixel = FC_RGBA_VBGR;
                     break;
                 case SubPixelNone:
                     subpixel = FC_RGBA_NONE;
                     break;
                 }
             }
 #endif
             char *rgba = XGetDefault(X11->display, "Xft", FC_RGBA);
             if (rgba) {
                 char *end = 0;
                 int v = strtol(rgba, &end, 0);
                 if (rgba != end) {
                     subpixel = v;
                 } else if (qstrncmp(rgba, "unknown", 7) == 0) {
                     subpixel = FC_RGBA_UNKNOWN;
                 } else if (qstrncmp(rgba, "rgb", 3) == 0) {
                     subpixel = FC_RGBA_RGB;
                 } else if (qstrncmp(rgba, "bgr", 3) == 0) {
                     subpixel = FC_RGBA_BGR;
                 } else if (qstrncmp(rgba, "vrgb", 4) == 0) {
                     subpixel = FC_RGBA_VRGB;
                 } else if (qstrncmp(rgba, "vbgr", 4) == 0) {
                     subpixel = FC_RGBA_VBGR;
                 } else if (qstrncmp(rgba, "none", 4) == 0) {
                     subpixel = FC_RGBA_NONE;
                 }
             }
             X11->screens[s].subpixel = subpixel;
         }
         getXDefault("Xft", FC_ANTIALIAS, &X11->fc_antialias);
 #ifdef FC_HINT_STYLE
         X11->fc_hint_style = -1;
         getXDefault("Xft", FC_HINT_STYLE, &X11->fc_hint_style);
 #endif
 #if 0
         // ###### these are implemented by Xft, not sure we need them
         getXDefault("Xft", FC_AUTOHINT, &X11->fc_autohint);
         getXDefault("Xft", FC_HINTING, &X11->fc_autohint);
         getXDefault("Xft", FC_MINSPACE, &X11->fc_autohint);
 #endif
 #endif // QT_NO_XRENDER
         // initialize key mapper
         QKeyMapper::changeKeyboard();
         // Misc. initialization
 #if 0 //disabled for now..
         QSegfaultHandler::initialize(priv->argv, priv->argc);
 #endif
         QCursorData::initialize();
     }
     QFont::initialize();
     if(qt_is_gui_used) {
         qApp->setObjectName(QString::fromLocal8Bit(appName));
         int screen;
         for (screen = 0; screen < X11->screenCount; ++screen) {
             XSelectInput(X11->display, QX11Info::appRootWindow(screen),
                          KeymapStateMask | EnterWindowMask | LeaveWindowMask | PropertyChangeMask);
 #ifndef QT_NO_XRANDR
             if (X11->use_xrandr)
                 X11->ptrXRRSelectInput(X11->display, QX11Info::appRootWindow(screen), True);
 #endif // QT_NO_XRANDR
         }
     }
     if (qt_is_gui_used) {
         // Attempt to determine the current running X11 Desktop Enviornment
         // Use dbus if/when we can, but fall back to using windowManagerName() for now
 #ifndef QT_NO_XFIXES
         if (X11->ptrXFixesSelectSelectionInput)
             X11->ptrXFixesSelectSelectionInput(X11->display, QX11Info::appRootWindow(), ATOM(_NET_WM_CM_S0),
                                        XFixesSetSelectionOwnerNotifyMask
                                        | XFixesSelectionWindowDestroyNotifyMask
                                        | XFixesSelectionClientCloseNotifyMask);
 #endif // QT_NO_XFIXES
         X11->compositingManagerRunning = XGetSelectionOwner(X11->display,
                                                             ATOM(_NET_WM_CM_S0));
         X11->desktopEnvironment = DE_UNKNOWN;
         X11->desktopVersion = 0;
         Atom type;
         int format;
         unsigned long length, after;
         uchar *data = 0;
         int rc;
         do {
             if (!qgetenv("KDE_FULL_SESSION").isEmpty()) {
                 X11->desktopEnvironment = DE_KDE;
                 X11->desktopVersion = qgetenv("KDE_SESSION_VERSION").toInt();
                 break;
             }
             if (qgetenv("DESKTOP_SESSION") == "gnome") {
                 X11->desktopEnvironment = DE_GNOME;
                 break;
             }
             // GNOME_DESKTOP_SESSION_ID is deprecated for some reason, but still check it
             if (!qgetenv("GNOME_DESKTOP_SESSION_ID").isEmpty()) {
                 X11->desktopEnvironment = DE_GNOME;
                 break;
             }
             rc = XGetWindowProperty(X11->display, QX11Info::appRootWindow(), ATOM(_DT_SAVE_MODE),
                                     0, 2, False, XA_STRING, &type, &format, &length,
                                     &after, &data);
             if (rc == Success && length) {
                 if (!strcmp(reinterpret_cast<char *>(data), "xfce4")) {
                     // Pretend that xfce4 is gnome, as it uses the same libraries.
                     // The detection above is stolen from xdg-open.
                     X11->desktopEnvironment = DE_GNOME;
                     break;
                 }
                 // We got the property but it wasn't xfce4. Free data before it gets overwritten.
                 XFree(data);
                 data = 0;
             }
             rc = XGetWindowProperty(X11->display, QX11Info::appRootWindow(), ATOM(DTWM_IS_RUNNING),
                                     0, 1, False, AnyPropertyType, &type, &format, &length,
                                     &after, &data);
             if (rc == Success && length) {
                 // DTWM is running, meaning most likely CDE is running...
                 X11->desktopEnvironment = DE_CDE;
                 break;
             }
             rc = XGetWindowProperty(X11->display, QX11Info::appRootWindow(),
                                     ATOM(_SGI_DESKS_MANAGER), 0, 1, False, XA_WINDOW,
                                     &type, &format, &length, &after, &data);
             if (rc == Success && length) {
                 X11->desktopEnvironment = DE_4DWM;
                 break;
             }
             if (XGetWindowProperty(X11->display, QX11Info::appRootWindow(),
                                ATOM(_NET_SUPPORTING_WM_CHECK),
                                0, 1024, False, XA_WINDOW, &type,
                                &format, &length, &after, &data) == Success) {
                 if (type == XA_WINDOW && format == 32) {
                     Window windowManagerWindow = *((Window*) data);
                     XFree(data);
                     data = 0;
                     if (windowManagerWindow != XNone) {
                         Atom utf8atom = ATOM(UTF8_STRING);
                         if (XGetWindowProperty(QX11Info::display(), windowManagerWindow, ATOM(_NET_WM_NAME),
                                                0, 1024, False, utf8atom, &type,
                                                &format, &length, &after, &data) == Success) {
                             if (type == utf8atom && format == 8) {
                                 if (qstrcmp((const char *)data, "MCompositor") == 0)
                                     X11->desktopEnvironment = DE_MEEGO_COMPOSITOR;
                             }
                         }
                     }
                 }
             }
         } while(0);
         if (data)
             XFree((char *)data);
 #if !defined(QT_NO_STYLE_GTK)
         if (X11->desktopEnvironment == DE_GNOME) {
             static bool menusHaveIcons = QGtkStyle::getGConfBool(QLatin1String("/desktop/gnome/interface/menus_have_icons"), true);
             QApplication::setAttribute(Qt::AA_DontShowIconsInMenus, !menusHaveIcons);
         }
 #endif
         qt_set_input_encoding();
         qt_set_x11_resources(appFont, appFGCol, appBGCol, appBTNCol);
         // be smart about the size of the default font. most X servers have helvetica
         // 12 point available at 2 resolutions:
         //     75dpi (12 pixels) and 100dpi (17 pixels).
         // At 95 DPI, a 12 point font should be 16 pixels tall - in which case a 17
         // pixel font is a closer match than a 12 pixel font
         int ptsz = (X11->use_xrender
                     ? 9
                     : (int) (((QX11Info::appDpiY() >= 95 ? 17. : 12.) *
                               72. / (float) QX11Info::appDpiY()) + 0.5));
         if (!QApplicationPrivate::sys_font) {
             // no font from settings or RESOURCE_MANAGER, provide a fallback
             QFont f(X11->has_fontconfig ? QLatin1String("Sans Serif") : QLatin1String("Helvetica"),
                     ptsz);
             QApplicationPrivate::setSystemFont(f);
         }
 #if !defined (QT_NO_TABLET)
         if (X11->use_xinput) {
             int ndev,
                 i,
                 j;
             bool gotStylus,
                 gotEraser;
             XDeviceInfo *devices = 0, *devs;
             XInputClassInfo *ip;
             XAnyClassPtr any;
             XValuatorInfoPtr v;
             XAxisInfoPtr a;
             XDevice *dev = 0;
             if (X11->ptrXListInputDevices) {
                 devices = X11->ptrXListInputDevices(X11->display, &ndev);
                 if (!devices)
                     qWarning("QApplication: Failed to get list of tablet devices");
             }
             if (!devices)
                 ndev = -1;
             QTabletEvent::TabletDevice deviceType;
             for (devs = devices, i = 0; i < ndev && devs; i++, devs++) {
                 dev = 0;
                 deviceType = QTabletEvent::NoDevice;
                 gotStylus = false;
                 gotEraser = false;
 #if defined(Q_OS_IRIX)
                 QString devName = QString::fromLocal8Bit(devs->name).toLower();
                 if (devName == QLatin1String(WACOM_NAME)) {
                     deviceType = QTabletEvent::Stylus;
                     gotStylus = true;
                 }
 #else
                 // qDebug() << "found input device" << devs->name << "type" << devs->type << XGetAtomName(X11->display, devs->type);
                 if (devs->type == ATOM(XWacomStylus) || devs->type == ATOM(XTabletStylus) || devs->type == ATOM(XTablet)) {
                     deviceType = QTabletEvent::Stylus;
                     if (wacomDeviceName()->isEmpty())
                         wacomDeviceName()->append(devs->name);
                     gotStylus = true;
                 } else if (devs->type == ATOM(XWacomEraser) || devs->type == ATOM(XTabletEraser)) {
                     deviceType = QTabletEvent::XFreeEraser;
                     gotEraser = true;
                 }
 #endif
                 if (deviceType == QTabletEvent::NoDevice)
                     continue;
                 if (gotStylus || gotEraser) {
                     if (X11->ptrXOpenDevice)
                         dev = X11->ptrXOpenDevice(X11->display, devs->id);
                     if (!dev)
                         continue;
                     QTabletDeviceData device_data;
                     device_data.deviceType = deviceType;
                     device_data.eventCount = 0;
                     device_data.device = dev;
                     device_data.xinput_motion = -1;
                     device_data.xinput_key_press = -1;
                     device_data.xinput_key_release = -1;
                     device_data.xinput_button_press = -1;
                     device_data.xinput_button_release = -1;
                     device_data.xinput_proximity_in = -1;
                     device_data.xinput_proximity_out = -1;
                     device_data.widgetToGetPress = 0;
                     if (dev->num_classes > 0) {
                         for (ip = dev->classes, j = 0; j < dev->num_classes;
                              ip++, j++) {
                             switch (ip->input_class) {
                             case KeyClass:
                                 DeviceKeyPress(dev, device_data.xinput_key_press,
                                                device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 DeviceKeyRelease(dev, device_data.xinput_key_release,
                                                  device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 break;
                             case ButtonClass:
                                 DeviceButtonPress(dev, device_data.xinput_button_press,
                                                   device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 DeviceButtonRelease(dev, device_data.xinput_button_release,
                                                     device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 break;
                             case ValuatorClass:
                                 // I'm only going to be interested in motion when the
                                 // stylus is already down anyway!
                                 DeviceMotionNotify(dev, device_data.xinput_motion,
                                                    device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 ProximityIn(dev, device_data.xinput_proximity_in, device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 ProximityOut(dev, device_data.xinput_proximity_out, device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                             default:
                                 break;
                             }
                         }
                     }
                     // get the min/max value for pressure!
                     any = (XAnyClassPtr) (devs->inputclassinfo);
                     for (j = 0; j < devs->num_classes; j++) {
                         if (any->c_class == ValuatorClass) {
                             v = (XValuatorInfoPtr) any;
                             a = (XAxisInfoPtr) ((char *) v +
                                                 sizeof (XValuatorInfo));
 #if defined (Q_OS_IRIX)
                             // I'm not exaclty wild about this, but the
                             // dimensions of the tablet are more relevant here
                             // than the min and max values from the axis
                             // (actually it seems to be 2/3 or what is in the
                             // axis.  So we'll try to parse it from this
                             // string. --tws
                             char returnString[SGIDeviceRtrnLen];
                             int tmp;
                             if (XSGIMiscQueryExtension(X11->display, &tmp, &tmp)
                                 && XSGIDeviceQuery(X11->display, devs->id,
                                                    "dimensions", returnString)) {
                                 QString str = QLatin1String(returnString);
                                 int comma = str.indexOf(',');
                                 device_data.minX = 0;
                                 device_data.minY = 0;
                                 device_data.maxX = str.left(comma).toInt();
                                 device_data.maxY = str.mid(comma + 1).toInt();
                             } else {
                                 device_data.minX = a[WAC_XCOORD_I].min_value;
                                 device_data.maxX = a[WAC_XCOORD_I].max_value;
                                 device_data.minY = a[WAC_YCOORD_I].min_value;
                                 device_data.maxY = a[WAC_YCOORD_I].max_value;
                             }
                             device_data.minPressure = a[WAC_PRESSURE_I].min_value;
                             device_data.maxPressure = a[WAC_PRESSURE_I].max_value;
                             device_data.minTanPressure = a[WAC_TAN_PRESSURE_I].min_value;
                             device_data.maxTanPressure = a[WAC_TAN_PRESSURE_I].max_value;
                             device_data.minZ = a[WAC_ZCOORD_I].min_value;
                             device_data.maxZ = a[WAC_ZCOORD_I].max_value;
 #else
                             device_data.minX = a[0].min_value;
                             device_data.maxX = a[0].max_value;
                             device_data.minY = a[1].min_value;
                             device_data.maxY = a[1].max_value;
                             device_data.minPressure = a[2].min_value;
                             device_data.maxPressure = a[2].max_value;
                             device_data.minTanPressure = 0;
                             device_data.maxTanPressure = 0;
                             device_data.minZ = 0;
                             device_data.maxZ = 0;
 #endif
                             // got the max pressure no need to go further...
                             break;
                         }
                         any = (XAnyClassPtr) ((char *) any + any->length);
                     } // end of for loop
                     tablet_devices()->append(device_data);
                 } // if (gotStylus || gotEraser)
             }
             if (X11->ptrXFreeDeviceList)
                 X11->ptrXFreeDeviceList(devices);
         }
 #endif // QT_NO_TABLET
         X11->startupId = getenv("DESKTOP_STARTUP_ID");
         if (X11->startupId) {
 #ifndef QT_NO_UNSETENV
             unsetenv("DESKTOP_STARTUP_ID");
 #else
             // it's a small memory leak, however we won't crash if Qt is
             // unloaded and someones tries to use the envoriment.
             putenv(strdup("DESKTOP_STARTUP_ID="));
 #endif
         }
    } else {
         // read some non-GUI settings when not using the X server...
         if (QApplication::desktopSettingsAware()) {
             QSettings settings(QSettings::UserScope, QLatin1String("Trolltech"));
             settings.beginGroup(QLatin1String("Qt"));
             // read library (ie. plugin) path list
             QString libpathkey = QString::fromLatin1("%1.%2/libraryPath")
                                  .arg(QT_VERSION >> 16)
                                  .arg((QT_VERSION & 0xff00) >> 8);
             QStringList pathlist =
                 settings.value(libpathkey).toString().split(QLatin1Char(':'));
             if (! pathlist.isEmpty()) {
                 QStringList::ConstIterator it = pathlist.constBegin();
                 while (it != pathlist.constEnd())
                     QApplication::addLibraryPath(*it++);
             }
             QString defaultcodec = settings.value(QLatin1String("defaultCodec"),
                                                   QVariant(QLatin1String("none"))).toString();
             if (defaultcodec != QLatin1String("none")) {
                 QTextCodec *codec = QTextCodec::codecForName(defaultcodec.toLatin1());
                 if (codec)
                     QTextCodec::setCodecForTr(codec);
             }
             settings.endGroup(); // Qt
         }
     }
 #if !defined (Q_OS_IRIX) && !defined (QT_NO_TABLET)
     QLibrary wacom(QString::fromLatin1("wacomcfg"), 0); // version 0 is the latest release at time of writing this.
     wacom.setLoadHints(QLibrary::ImprovedSearchHeuristics);
     // NOTE: C casts instead of reinterpret_cast for GCC 3.3.x
     ptrWacomConfigInit = (PtrWacomConfigInit)wacom.resolve("WacomConfigInit");
     ptrWacomConfigOpenDevice = (PtrWacomConfigOpenDevice)wacom.resolve("WacomConfigOpenDevice");
     ptrWacomConfigGetRawParam  = (PtrWacomConfigGetRawParam)wacom.resolve("WacomConfigGetRawParam");
     ptrWacomConfigCloseDevice = (PtrWacomConfigCloseDevice)wacom.resolve("WacomConfigCloseDevice");
     ptrWacomConfigTerm = (PtrWacomConfigTerm)wacom.resolve("WacomConfigTerm");
     if (ptrWacomConfigInit == 0 || ptrWacomConfigOpenDevice == 0 || ptrWacomConfigGetRawParam == 0
         || ptrWacomConfigCloseDevice == 0 || ptrWacomConfigTerm == 0) { // either we have all, or we have none.
             ptrWacomConfigInit = 0;
             ptrWacomConfigOpenDevice = 0;
             ptrWacomConfigGetRawParam  = 0;
             ptrWacomConfigCloseDevice = 0;
             ptrWacomConfigTerm = 0;
     }
 #endif
 }
qt_mac_applicationmenu_string()
QString qt_mac_applicationmenu_string (int type)
em>Reimplemented Function
Definition at line 2488 of file qapplication.cpp.
Referenced by qt_mac_menu_merge_text().
qt_matchLibraryName()
static int qt_matchLibraryName (dl_phdr_info * info, size_t , void * data) static
Definition at line 805 of file qapplication.cpp.
Referenced by QApplicationPrivate::construct().
 {
     const char *name = static_cast<const char *>(data);
     return strstr(info->dlpi_name, name) != 0;
 }
qt_sendSpontaneousEvent()
bool qt_sendSpontaneousEvent (QObject * receiver, QEvent * event)
Definition at line 5779 of file qapplication.cpp.
Referenced by QEventDispatcherMacPrivate::activateTimer(), QKeyMapper::changeKeyboard(), QWinInputContext::composition(), QWinInputContext::endComposition(), flipPoint(), QMacInputContext::globalEventProcessor(), macSendToolbarChangeEvent(), QGraphicsView::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsView::mousePressEvent(), QGraphicsView::mouseReleaseEvent(), onApplicationChangedActivation(), onApplicationWindowChangedActivation(), QMacWindowFader::performFade(), QKeyMapper::possibleKeys(), qt_dispatchTabletProximityEvent(), qt_init(), qt_keyrelease_scanner(), qt_mac_handleTabletEvent(), qt_mac_menu_event(), qt_mac_send_modifiers_changed(), qtKey2CocoaKey(), QtWndProc(), QWinInputContext::reconvertString(), QMacInputContext::reset(), QWinInputContext::reset(), QAxServerBase::resize(), QGraphicsScenePrivate::sendEvent(), QKeyMapper::sendKeyEvent(), QAxServerBase::SetColorScheme(), QCursor::setPos(), QETWidget::translateGestureEvent(), QWSInputContext::translateIMEvent(), and QGraphicsProxyWidget::wheelEvent().
 {
     return QCoreApplication::sendSpontaneousEvent(receiver, event);
 }
qt_translateRawTouchEvent()
Q_GUI_EXPORT void qt_translateRawTouchEvent (QWidget * window, QTouchEvent::DeviceType deviceType, const QList< QTouchEvent::TouchPoint > & touchPoints)
Definition at line 6191 of file qapplication.cpp.
Referenced by QTest::QTouchEventSequence::commit().
 {
     QApplicationPrivate::translateRawTouchEvent(window, deviceType, touchPoints);
 }
qt_tryModalHelper()
Q_GUI_EXPORT bool qt_tryModalHelper (QWidget * widget, QWidget ** rettop)
Definition at line 2949 of file qapplication.cpp.
 {
     return QApplicationPrivate::tryModalHelper(widget, rettop);
 }
qt_wince_is_mobile()
bool qt_wince_is_mobile ()
Definition at line 296 of file qguifunctions_wince.cpp.
{
      return (qt_wince_is_smartphone() || qt_wince_is_pocket_pc());
 }
qt_wince_is_pocket_pc()
bool qt_wince_is_pocket_pc ()
Definition at line 289 of file qguifunctions_wince.cpp.
{
     return qt_wince_is_platform(QString::fromLatin1("PocketPC"));
 }
qt_wince_is_smartphone()
bool qt_wince_is_smartphone ()
Definition at line 293 of file qguifunctions_wince.cpp.
{
        return qt_wince_is_platform(QString::fromLatin1("Smartphone"));
 }
qUnregisterGuiStateMachine()
int qUnregisterGuiStateMachine ()
Definition at line 514 of file qguistatemachine.cpp.
Referenced by QApplication::QApplication(), and QApplication::~QApplication().
 {
     QStateMachinePrivate::handler = qt_guistatemachine_last_handler;
     return 1;
 }
qUnregisterGuiVariant()
int qUnregisterGuiVariant ()
Definition at line 820 of file qguivariant.cpp.
Referenced by QVariant::operator!=(), QApplication::QApplication(), and QApplication::~QApplication().
 {
     QVariant::handler = qt_guivariant_last_handler;
     qMetaTypeGuiHelper = 0;
     return 1;
 }
Variable Documentation
aargc
int aargc = 1 static
Definition at line 896 of file qapplication.cpp.
Referenced by QApplication::QApplication().
aargv
char* aargv[] = { (char*)"unknown", 0 } static
Definition at line 897 of file qapplication.cpp.
Referenced by QApplication::QApplication().
application_menu_strings
const char* application_menu_strings[] static
Initial value:
= {
    QT_TRANSLATE_NOOP("MAC_APPLICATION_MENU","Services"),
    QT_TRANSLATE_NOOP("MAC_APPLICATION_MENU","Hide %1"),
    QT_TRANSLATE_NOOP("MAC_APPLICATION_MENU","Hide Others"),
    QT_TRANSLATE_NOOP("MAC_APPLICATION_MENU","Show All"),
    QT_TRANSLATE_NOOP("MAC_APPLICATION_MENU","Preferences..."),
    QT_TRANSLATE_NOOP("MAC_APPLICATION_MENU","Quit %1"),
    }
Definition at line 2479 of file qapplication.cpp.
Referenced by qt_mac_applicationmenu_string().
copy_xpm
const char* const copy_xpm[] static
Definition at line 6285 of file qapplication.cpp.
Referenced by QApplicationPrivate::getPixmapCursor().
drag_distance
int drag_distance = QT_GUI_DRAG_DISTANCE static
Definition at line 504 of file qapplication.cpp.
Referenced by QApplication::setStartDragDistance(), and QApplication::~QApplication().
drag_time
int drag_time = 500 static
Definition at line 496 of file qapplication.cpp.
Referenced by QApplication::setStartDragTime(), and QApplication::~QApplication().
force_reverse
bool force_reverse = false static
Definition at line 527 of file qapplication.cpp.
Referenced by QApplicationPrivate::process_cmdline(), and qt_detectRTLLanguage().
ignore_xpm
const char* const ignore_xpm[] static
Definition at line 6247 of file qapplication.cpp.
Referenced by QApplicationPrivate::getPixmapCursor().
layout_direction
Qt::LayoutDirection layout_direction = Qt::LeftToRight static
Definition at line 506 of file qapplication.cpp.
Referenced by qt_format_text(), QApplication::setLayoutDirection(), and QApplication::~QApplication().
link_xpm
const char* const link_xpm[] static
Definition at line 6345 of file qapplication.cpp.
Referenced by QApplicationPrivate::getPixmapCursor().
move_xpm
const char* const move_xpm[] static
Initial value:
= {
"11 20 3 1",
".        c None",
"a        c #000000",
"X        c #FFFFFF",
"aa.........",
"aXa........",
"aXXa.......",
"aXXXa......",
"aXXXXa.....",
"aXXXXXa....",
"aXXXXXXa...",
"aXXXXXXXa..",
"aXXXXXXXXa.",
"aXXXXXXXXXa",
"aXXXXXXaaaa",
"aXXXaXXa...",
"aXXaaXXa...",
"aXa..aXXa..",
"aa...aXXa..",
"a.....aXXa.",
"......aXXa.",
".......aXXa",
".......aXXa",
"........aa."}
Definition at line 6214 of file qapplication.cpp.
Referenced by QApplicationPrivate::getPixmapCursor().
qt_antialiasing_threshold
int qt_antialiasing_threshold = -1
Definition at line 495 of file qapplication.cpp.
Referenced by QCoreGraphicsPaintEngine::drawTextItem(), QFontEngineMac::imageForGlyph(), and qt_mac_update_os_settings().
qt_appType
QApplication::Type qt_appType =QApplication::Tty
Definition at line 163 of file qapplication.cpp.
Referenced by QApplicationPrivate::construct(), QPixmap::init(), QApplicationPrivate::initialize(), QApplicationPrivate::QApplicationPrivate(), qt_init(), and QApplication::type().
qt_button_down
QWidget* qt_button_down
Definition at line 188 of file qapplication_mac.mm.
Referenced by QApplicationPrivate::sendMouseEvent().
qt_clipboard
QClipboard* qt_clipboard = 0
Definition at line 562 of file qapplication.cpp.
Referenced by QApplication::clipboard(), QApplicationPrivate::globalEventProcessor(), onApplicationChangedActivation(), QtWndProc(), QApplication::qwsProcessEvent(), QApplication::x11ProcessEvent(), and QApplication::~QApplication().
qt_desktopWidget
QDesktopWidget* qt_desktopWidget = 0
Definition at line 560 of file qapplication.cpp.
Referenced by QApplication::desktop(), and QApplication::~QApplication().
qt_in_tab_key_event
bool qt_in_tab_key_event = false
Definition at line 494 of file qapplication.cpp.
Referenced by QApplicationPrivate::focusNextPrevChild_helper(), QApplication::notify(), and QApplicationPrivate::setFocusWidget().
qt_is_gui_used
bool qt_is_gui_used
Definition at line 492 of file qapplication.cpp.
Referenced by QApplicationPrivate::appName(), QApplicationPrivate::construct(), QFontDef::exactMatch(), QEventDispatcherMac::hasPendingEvents(), init_wintab_functions(), QFontDatabase::loadXlfd(), QApplicationPrivate::process_cmdline(), qt_cleanup(), qt_defaultDpiX(), qt_defaultDpiY(), qt_get_tablet_widget(), qt_init(), qt_init_display(), QApplicationPrivate::qt_mac_apply_settings(), QApplication::style(), QETWidget::translateTabletEvent(), and QApplication::~QApplication().
qt_last_mouse_receiver
QPointer<QWidget> qt_last_mouse_receiver
Definition at line 189 of file qapplication_mac.mm.
Referenced by QApplicationPrivate::sendMouseEvent().
qt_modal_stack
QWidgetList* qt_modal_stack =0
Definition at line 564 of file qapplication.cpp.
Referenced by QApplicationPrivate::leaveModal_sys(), qt_try_modal(), QtWndProc(), QApplication::qwsSetCustomColors(), and QApplication::x11EventFilter().
qt_session_manager_self
QSessionManager* qt_session_manager_self = 0
Definition at line 5053 of file qapplication.cpp.
qt_tab_all_widgets
bool Q_GUI_EXPORT qt_tab_all_widgets = true
Definition at line 493 of file qapplication.cpp.
Referenced by QGraphicsProxyWidgetPrivate::findFocusChild(), QApplicationPrivate::focusNextPrevChild_helper(), QX11EmbedWidgetPrivate::getFocusWidget(), QAbstractButtonPrivate::moveFocus(), and qt_mac_update_os_settings().
qt_tabletChokeMouse
bool qt_tabletChokeMouse = false
Definition at line 526 of file qapplication.cpp.
Referenced by QApplication::notify(), qt_tablet_devices(), QtWndProc(), QETWidget::translateMouseEvent(), and QApplication::x11ProcessEvent().