Qt 4.8: /src/gui/kernel/qapplication_p.h File Reference
qapplication_p.h File Reference
#include "QtGui/qapplication.h"
#include "QtGui/qevent.h"
#include "QtGui/qfont.h"
#include "QtGui/qcursor.h"
#include "QtGui/qregion.h"
#include "QtCore/qmutex.h"
#include "QtCore/qtranslator.h"
#include "QtCore/qbasictimer.h"
#include "QtCore/qhash.h"
#include "QtCore/qpointer.h"
#include "private/qcoreapplication_p.h"
#include "QtGui/private/qshortcutmap_p.h"
#include <private/qthread_p.h>
#include "QtCore/qpoint.h"
#include <QTime>
#include "QtGui/qscreen_qws.h"
#include <private/qgraphicssystem_qws_p.h>
Classes
class QApplicationPrivate
struct QTabletDeviceData
struct QWSServerCleaner
struct tagGESTURECONFIG
struct tagGESTUREINFO
Macros
#define GC_PAN 0x00000001
#define GC_PAN_WITH_SINGLE_FINGER_HORIZONTALLY 0x00000004
#define GC_PAN_WITH_SINGLE_FINGER_VERTICALLY 0x00000002
#define GC_ROTATE 0x00000001
#define GC_ZOOM 0x00000001
#define GID_BEGIN 1
#define GID_END 2
#define GID_PAN 4
#define GID_ROLLOVER 7
#define GID_ROTATE 5
#define GID_ROTATE_ANGLE_FROM_ARGUMENT(arg) ((((double)(arg) / 65535.0) * 4.0 * 3.14159265) - 2.0*3.14159265)
#define GID_TWOFINGERTAP 6
#define GID_ZOOM 3
#define WM_GESTURE 0x0119
Typedefs
typedef QHash< QByteArray, QFont > FontHash
typedef struct tagGESTURECONFIG GESTURECONFIG
typedef struct tagGESTUREINFO GESTUREINFO
typedef QHash< QByteArray, QPalette > PaletteHash
typedef BOOL(WINAPI * PtrBeginPanningFeedback) (HWND)
typedef BOOL(WINAPI * PtrCloseGestureInfoHandle) (HANDLE)
typedef BOOL(WINAPI * PtrCloseTouchInputHandle) (HANDLE)
typedef BOOL(WINAPI * PtrEndPanningFeedback) (HWND, BOOL)
typedef BOOL(WINAPI * PtrGetGestureConfig) (HWND, DWORD, DWORD, PUINT, PVOID, UINT)
typedef BOOL(WINAPI * PtrGetGestureExtraArgs) (HANDLE, UINT, PBYTE)
typedef BOOL(WINAPI * PtrGetGestureInfo) (HANDLE, PVOID)
typedef BOOL(WINAPI * PtrGetTouchInputInfo) (HANDLE, UINT, PVOID, int)
typedef BOOL(WINAPI * PtrRegisterTouchWindow) (HWND, ULONG)
typedef BOOL(WINAPI * PtrSetGestureConfig) (HWND, DWORD, UINT, PVOID, UINT)
typedef BOOL(WINAPI * PtrUpdatePanningFeedback) (HWND, LONG, LONG, BOOL)
typedef QHash< int, QTabletDeviceData > QMacTabletHash
typedef QList< QTabletDeviceData > QTabletDeviceDataList
Enumerations
enum { QT_TABLET_NPACKETQSIZE = 128 }
Functions
FontHash * qt_app_fonts_hash ()
PaletteHash * qt_app_palettes_hash ()
QMacTabletHash * qt_mac_tablet_hash ()
QTabletDeviceDataList * qt_tablet_devices ()
Q_GUI_EXPORT void qt_translateRawTouchEvent (QWidget *window, QTouchEvent::DeviceType deviceType, const QList< QTouchEvent::TouchPoint > &touchPoints)
void qt_win_set_cursor (QWidget *, bool)
static int sign (int x)
Variables
DWORD qt_cever
QClipboard * qt_clipboard
bool qt_is_gui_used
QSysInfo::WinVersion qt_winver
Macro Definition Documentation
GC_PAN
#define GC_PAN 0x00000001
Definition at line 247 of file qapplication_p.h.
GC_PAN_WITH_SINGLE_FINGER_HORIZONTALLY
#define GC_PAN_WITH_SINGLE_FINGER_HORIZONTALLY 0x00000004
Definition at line 249 of file qapplication_p.h.
GC_PAN_WITH_SINGLE_FINGER_VERTICALLY
#define GC_PAN_WITH_SINGLE_FINGER_VERTICALLY 0x00000002
Definition at line 248 of file qapplication_p.h.
GC_ROTATE
#define GC_ROTATE 0x00000001
Definition at line 252 of file qapplication_p.h.
GC_ZOOM
#define GC_ZOOM 0x00000001
Definition at line 251 of file qapplication_p.h.
GID_BEGIN
#define GID_BEGIN 1
Definition at line 226 of file qapplication_p.h.
Referenced by QtWndProc(), and QETWidget::translateGestureEvent().
GID_END
#define GID_END 2
Definition at line 227 of file qapplication_p.h.
Referenced by QtWndProc(), and QETWidget::translateGestureEvent().
GID_PAN
#define GID_PAN 4
Definition at line 229 of file qapplication_p.h.
Referenced by QETWidget::translateGestureEvent().
GID_ROLLOVER
#define GID_ROLLOVER 7
Definition at line 232 of file qapplication_p.h.
GID_ROTATE
#define GID_ROTATE 5
Definition at line 230 of file qapplication_p.h.
Referenced by QETWidget::translateGestureEvent().
GID_ROTATE_ANGLE_FROM_ARGUMENT
#define GID_ROTATE_ANGLE_FROM_ARGUMENT (arg) ((((double)(arg) / 65535.0) * 4.0 * 3.14159265) - 2.0*3.14159265)
Definition at line 261 of file qapplication_p.h.
GID_TWOFINGERTAP
#define GID_TWOFINGERTAP 6
Definition at line 231 of file qapplication_p.h.
GID_ZOOM
#define GID_ZOOM 3
Definition at line 228 of file qapplication_p.h.
WM_GESTURE
#define WM_GESTURE 0x0119
Definition at line 224 of file qapplication_p.h.
Typedef Documentation
FontHash
typedef QHash<QByteArray, QFont> FontHash
Definition at line 280 of file qapplication_p.h.
GESTURECONFIG
typedef struct tagGESTURECONFIG GESTURECONFIG
GESTUREINFO
typedef struct tagGESTUREINFO GESTUREINFO
PaletteHash
typedef QHash<QByteArray, QPalette> PaletteHash
Definition at line 283 of file qapplication_p.h.
PtrBeginPanningFeedback
typedef BOOL(WINAPI * PtrBeginPanningFeedback) (HWND)
Definition at line 219 of file qapplication_p.h.
PtrCloseGestureInfoHandle
typedef BOOL(WINAPI * PtrCloseGestureInfoHandle) (HANDLE)
Definition at line 215 of file qapplication_p.h.
PtrCloseTouchInputHandle
typedef BOOL(WINAPI * PtrCloseTouchInputHandle) (HANDLE)
Definition at line 210 of file qapplication_p.h.
PtrEndPanningFeedback
typedef BOOL(WINAPI * PtrEndPanningFeedback) (HWND, BOOL)
Definition at line 221 of file qapplication_p.h.
PtrGetGestureConfig
typedef BOOL(WINAPI * PtrGetGestureConfig) (HWND, DWORD, DWORD, PUINT, PVOID, UINT)
Definition at line 217 of file qapplication_p.h.
PtrGetGestureExtraArgs
typedef BOOL(WINAPI * PtrGetGestureExtraArgs) (HANDLE, UINT, PBYTE)
Definition at line 214 of file qapplication_p.h.
PtrGetGestureInfo
typedef BOOL(WINAPI * PtrGetGestureInfo) (HANDLE, PVOID)
Definition at line 213 of file qapplication_p.h.
PtrGetTouchInputInfo
typedef BOOL(WINAPI * PtrGetTouchInputInfo) (HANDLE, UINT, PVOID, int)
Definition at line 209 of file qapplication_p.h.
PtrRegisterTouchWindow
typedef BOOL(WINAPI * PtrRegisterTouchWindow) (HWND, ULONG)
Definition at line 208 of file qapplication_p.h.
PtrSetGestureConfig
typedef BOOL(WINAPI * PtrSetGestureConfig) (HWND, DWORD, UINT, PVOID, UINT)
Definition at line 216 of file qapplication_p.h.
PtrUpdatePanningFeedback
typedef BOOL(WINAPI * PtrUpdatePanningFeedback) (HWND, LONG, LONG, BOOL)
Definition at line 220 of file qapplication_p.h.
QMacTabletHash
typedef QHash<int, QTabletDeviceData> QMacTabletHash
Definition at line 194 of file qapplication_p.h.
QTabletDeviceDataList
typedef QList<QTabletDeviceData> QTabletDeviceDataList
Definition at line 191 of file qapplication_p.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QT_TABLET_NPACKETQSIZE
Definition at line 105 of file qapplication_p.h.
 { QT_TABLET_NPACKETQSIZE = 128 };
Function Documentation
qt_app_fonts_hash()
FontHash* qt_app_fonts_hash ()
Definition at line 553 of file qapplication.cpp.
Referenced by QMacStyle::drawControl(), QComboMenuDelegate::getStyleOption(), QMacStyle::polish(), qt_aqua_get_known_size(), QMessageBox::setInformativeText(), QMacStyle::subControlRect(), and QDockWidgetLayout::titleHeight().
 {
     return app_fonts();
 }
qt_app_palettes_hash()
PaletteHash* qt_app_palettes_hash ()
Definition at line 547 of file qapplication.cpp.
Referenced by QGtkStyleFilter::eventFilter(), and QApplicationPrivate::initializeWidgetPaletteHash().
 {
     return app_palettes();
 }
qt_mac_tablet_hash()
QMacTabletHash* qt_mac_tablet_hash ()
Definition at line 442 of file qt_cocoa_helpers_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor(), qt_dispatchTabletProximityEvent(), and qt_mac_handleTabletEvent().
 {
     return tablet_hash();
 }
qt_tablet_devices()
QTabletDeviceDataList* qt_tablet_devices ()
Definition at line 395 of file qapplication_x11.cpp.
Referenced by getNetWmState(), qt_cleanup(), QETWidget::translateMouseEvent(), QETWidget::translateXinputEvent(), and QApplication::x11ProcessEvent().
 {
     return tablet_devices();
 }
qt_translateRawTouchEvent()
Q_GUI_EXPORT void qt_translateRawTouchEvent (QWidget * window, QTouchEvent::DeviceType deviceType, const QList< QTouchEvent::TouchPoint > & touchPoints)
Definition at line 6191 of file qapplication.cpp.
 {
     QApplicationPrivate::translateRawTouchEvent(window, deviceType, touchPoints);
 }
qt_win_set_cursor()
void qt_win_set_cursor (QWidget * , bool)
Definition at line 1282 of file qapplication_win.cpp.
Referenced by QApplicationPrivate::dispatchEnterLeave().
 {
     static QPointer<QWidget> lastUnderMouse = 0;
     if (force) {
         lastUnderMouse = w;
     } else if (w->testAttribute(Qt::WA_WState_Created) && lastUnderMouse
                && lastUnderMouse->effectiveWinId() == w->effectiveWinId()) {
         w = lastUnderMouse;
     }
     if (!curWin && w && w->internalWinId())
         return;
     QWidget* cW = w && !w->internalWinId() ? w : QWidget::find(curWin);
     if (!cW || cW->window() != w->window() ||
          !cW->isVisible() || !cW->underMouse() || QApplication::overrideCursor())
         return;
     SetCursor(cW->cursor().handle());
 }
sign()
static int sign (int x) inline static
Definition at line 163 of file qapplication_p.h.
Referenced by _qdtoa(), addCircle(), QDateTimePrivate::addMSecs(), QPatternist::UserFunctionCallsite::body(), QPatternist::DateTimeDurationMathematician::calculate(), QPatternist::checkVariableCircularity(), QPatternist::AbstractFunctionFactory::createFunctionCall(), QLocalePrivate::doubleToString(), QTextLayout::drawCursor(), QDateTime::fromString(), QTextStreamPrivate::getNumber(), QDeclarativeJS::integerFromString(), QScript::integerFromString(), QPatternist::FunctionFactory::isAvailable(), isZero(), parseDateString(), QTextStreamPrivate::putString(), qstrtod(), QPatternist::FunctionCall::setSignature(), QPatternist::CallTemplate::setTemplate(), QPatternist::AbstractFloat< isDouble >::stringValue(), QScript::ToInt32(), QScript::ToInteger(), QPatternist::Decimal::toString(), QDateTime::toString(), QScript::ToUInt16(), QScript::ToUInt32(), and QPatternist::yyparse().
 {
     return x >= 0 ? 1 : -1;
 }
Variable Documentation
qt_cever
DWORD qt_cever
Referenced by macVersion().
qt_clipboard
QClipboard* qt_clipboard
Definition at line 562 of file qapplication.cpp.
Referenced by QApplication::clipboard(), QApplicationPrivate::globalEventProcessor(), onApplicationChangedActivation(), QtWndProc(), QApplication::qwsProcessEvent(), QApplication::x11ProcessEvent(), and QApplication::~QApplication().
qt_is_gui_used
bool qt_is_gui_used
Definition at line 492 of file qapplication.cpp.
qt_winver
QSysInfo::WinVersion qt_winver